### PR TITLE
Allow using a clusterIP as endpoint in iptables

### LINKED ISSUE #40870: Services without selectors cannot forward to other services as documented
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:

Google Container Engine, 1.5.2

**What happened**:

I created a selectorless service and configured the endpoint to point at the ClusterIP of another service in a different namespace, as described in the documentation: 
https://kubernetes.io/docs/user-guide/services/#services-without-selectors

This is supported behaviour ("You want to point your service to a service in another Namespace or on another cluster").

Any requests on the External IP of the selectorless service hang.

**What you expected to happen**:

Requests to be sent to the target service.

**How to reproduce it** (as minimally and precisely as possible):

Start this stack:

```yaml
---
kind: Namespace
apiVersion: v1
metadata:
  name: reproducer-alpha
---
kind: Pod
apiVersion: v1
metadata:
  name: alpha
  namespace: reproducer-alpha
  labels:
    service: alpha
spec:
  containers:
    - name: alpha
      image: robhaswell/hello-env
      env:
        - name: HELLO_MSG
          value: I am ALPHA
      ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: alpha
  namespace: reproducer-alpha
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    service: alpha
  clusterIP: 10.3.250.250
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
kind: Endpoints
apiVersion: v1
metadata:
  name: frontend
  namespace: default
subsets:
  - addresses:
    - ip: 10.3.250.250
    ports:
    - port: 8080
```

Wait for the `frontend` service to be allocated an IP, then try to hit it with curl on port 8080: `curl http://EXTERNAL-IP:8080`. There is no output. I would expect the output to be 'I am ALPHA'.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

Allows to use a clusterIP as endpoint when using kube-proxy in iptables mode

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #40870

**Special notes for your reviewer**:

**Release note**:

```release-note
It is now possible to use a clusterIP as endpoint when running kube-proxy in iptables mode
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
Is there a change necessary for IPVS and userspace proxy modes?  Will networking plugin providers need to change to support this correctly?  I didn't see any discussion of that in the linked thread, but if this can't work in IPVS for some reason we should know now.

**Comment by alvaroaleman** [comment]
hey @smarterclayton 

thanks for taking a look.

> Is there a change necessary for IPVS and userspace proxy modes? 

For IPVS yes, for userspace no

> Will networking plugin providers need to change to support this correctly? 

Do you mean providers that built a `kube-proxy` replacement? Yes, that may be the case, depends a lot on what underlying technology they use, hard to make a general statement here

> I didn't see any discussion of that in the linked thread, but if this can't work in IPVS for some reason we should know now.

Well, this can work on IPVS, allthought the implementation would differ a little from what I did here.

The approach here for the `iptables` mode is:

* Find out if target is a clusterIP and that clusterIP has an endpoint count > 0
* Jump from the original clusterIP chain to the target clusterIP chain

For IPVS, using an IPVS-managed VIP as target only works if that VIP has the same port as its endpoints, or in other words if on the service that holds the target `clusterIP` `port==targetPort` (No idea if this is intended or a bug).

So the approach for `ipvs` mode would be:

* Find out if target is a clusterIP
* Copy all endpoints from the target clusterIP

I'd like to create a follow-up for IPVS once this is in.

**Comment by alvaroaleman** [comment]
@smarterclayton Any chance you can take another look?

**Comment by danwinship** [comment]
This is marked as "fixes #40870", but that issue was closed and the docs were changed to reflect that we *don't* expect this to work any more (https://github.com/kubernetes/website/pull/8028). Given that, I think this PR should be closed as well?

(As for the code itself, which I had already reviewed before discovering the parent issue was closed, it looks like it does what it claims to do, although `isEndpointAService()` seems kind of inefficient and I think if we actually wanted to implement this feature we might want to tweak what bits of information we're caching and what bits we have to recompute every time the function gets called.)

**Comment by alvaroaleman** [comment]
@danwinship Yes #40870 was closed but the "fix" was to document that it does not work. From how I read the issue there was no one having an issue with the general concept, just no one with the knowledge to implement this wanted to go ahead.

Do you want me to reopen #40870 first?

**Comment by danwinship** [comment]
@alvaroaleman It seemed to me like @thockin and @caseydavenport both felt that since you can implement the same functionality via ExternalName services instead, that we should steer people that way rather than trying to make this work, particularly given that it needs to be separately fixed for at least iptables and IPVS, and maybe also the various Windows and third-party kube-proxies.

**Comment by alvaroaleman** [comment]
I created #64668 to clarify if we want this.

**Pull request closed without merging**
