### PR TITLE
kubectl run add pull-policy flag to control image pull policy

### LINKED ISSUE #30493: kubectl run and pull policy
I find myself iterating on a `:latest` container, which means I really want to be able to specify `pullPolicy` from the CLI.

### PR DESCRIPTION
**Pull request by adohe-zz**
``` release-note
Add support for --image-pull-policy to 'kubectl run'
```

Fix #30493 
@pwittrock @thockin ptal

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30614)

### CODE REVIEW

**Comment by pwittrock** [comment]
@ymqytw Please shadow this code review.

**Comment by pwittrock** [comment]
@AdoHe Thanks for the ping.  Will review this today.

**Comment by pwittrock** [comment]
@k8s-bot node e2e test this issue: #24451

**Comment by pwittrock** [comment]
@AdoHe Started looking at this, will pick it up tomorrow.

**Comment by AdoHe** [comment]
@pwittrock thanks very much.

**Comment by pwittrock** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/kubectl/run.go, line 620 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614#-KPJBJmjUgOZqD50M-Tl:-KPJBJmkYityEAtnNuMU:b-w5o20b) ([raw file](https://github.com/kubernetes/kubernetes/blob/feda040c45a4c485dc5b289ae47905fe7c001ef3/pkg/kubectl/run.go#L620)):*
> ```Go
> 	imagePullPolicy := api.PullPolicy(params["image-pull-policy"])
> 	if len(imagePullPolicy) == 0 {
> 		imagePullPolicy = api.PullAlways
> ```

We should either:
- Only set the imagePullPolicy if it is set, and leave it empty if unset (this will rely on server side defaulting)
- Set the default imagePullPolicy value in the flag default so that it is better documented what the default is

I am leaning towards the former - e.g. don't set the imagePullPolicy here if the flag is empty.

---

*[pkg/kubectl/run.go, line 654 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614#-KPJBp71_HW-wLnwRIT5:-KPJBp71_HW-wLnwRIT6:b-yey068) ([raw file](https://github.com/kubernetes/kubernetes/blob/feda040c45a4c485dc5b289ae47905fe7c001ef3/pkg/kubectl/run.go#L654)):*
> ```Go
> 
> 	imagePullPolicy := v1.PullPolicy(params["image-pull-policy"])
> 	if len(imagePullPolicy) == 0 {
> ```

Same comment here about defaulting.

---

*[pkg/kubectl/run.go, line 911 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614#-KPJC1FWxW5dv7NcwXMu:-KPJC1FWxW5dv7NcwXMv:b-7pozhr) ([raw file](https://github.com/kubernetes/kubernetes/blob/feda040c45a4c485dc5b289ae47905fe7c001ef3/pkg/kubectl/run.go#L911)):*
> ```Go
> 	imagePullPolicy := api.PullPolicy(params["image-pull-policy"])
> 	if len(imagePullPolicy) == 0 {
> 		imagePullPolicy = api.PullIfNotPresent
> ```

Why do we use a different default here than elsewhere?  Why do we set client-side defaults here but not elsewhere?

---

*[pkg/kubectl/run_test.go, line 40 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614#-KPJCBvxrUZyALwwHFFy:-KPJCBvxrUZyALwwHFFz:bysogbr) ([raw file](https://github.com/kubernetes/kubernetes/blob/feda040c45a4c485dc5b289ae47905fe7c001ef3/pkg/kubectl/run_test.go#L40)):*
> ```Go
> 				"name":              "foo",
> 				"image":             "someimage",
> 				"image-pull-policy": "Always",
> ```

If we only explicitly set the value in the config when the flag is supplied, then we can get rid of most of these changes.

---

*[pkg/kubectl/cmd/run.go, line 108 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614#-KPJCK28-QgtVI1VXNdo:-KPJCK28-QgtVI1VXNdp:bdzfzlh) ([raw file](https://github.com/kubernetes/kubernetes/blob/feda040c45a4c485dc5b289ae47905fe7c001ef3/pkg/kubectl/cmd/run.go#L108)):*
Explain the unset behavior.  e.g.

>
If left empty, this value will not be specified by the client and defaulted by the server.

---

*[pkg/kubectl/cmd/run.go, line 172 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614#-KPJAQ1oAZ3YyuUGx8HW:-KPJAQ1oAZ3YyuUGx8HX:b-1cxwi4) ([raw file](https://github.com/kubernetes/kubernetes/blob/feda040c45a4c485dc5b289ae47905fe7c001ef3/pkg/kubectl/cmd/run.go#L172)):*
> ```Go
> 
> 	if err := verifyImagePullPolicy(cmd); err != nil {
> 		return nil
> ```

Shouldn't this return the err?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614)*

**Comment by pwittrock** [comment]
Review Pass Finished

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614#-:-KPJDV5fMjMEE4SiCray:bk589z2)*

**Comment by AdoHe** [comment]
Thanks @pwittrock, this reviewable tool looks great.

**Comment by AdoHe** [comment]
*[pkg/kubectl/run.go, line 911 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614#-KPJC1FWxW5dv7NcwXMu:-KPKk6SzvEOirrFVjufq:birjpjv) ([raw file](https://github.com/kubernetes/kubernetes/blob/feda040c45a4c485dc5b289ae47905fe7c001ef3/pkg/kubectl/run.go#L911)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Why do we use a different default here than elsewhere?  Why do we set client-side defaults here but not elsewhere?
</details>
I have no idea why do this for BasicPod generator, but we did do it. I just respect the old behavior.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614)*

**Comment by AdoHe** [comment]
*[pkg/kubectl/run.go, line 620 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614#-KPJBJmjUgOZqD50M-Tl:-KPKkmPitytmwxAYa-d1:b-pbdqz3) ([raw file](https://github.com/kubernetes/kubernetes/blob/feda040c45a4c485dc5b289ae47905fe7c001ef3/pkg/kubectl/run.go#L620)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> We should either:
> - Only set the imagePullPolicy if it is set, and leave it empty if unset (this will rely on server side defaulting)
> - Set the default imagePullPolicy value in the flag default so that it is better documented what the default is
> 
> I am leaning towards the former - e.g. don't set the imagePullPolicy here if the flag is empty.
> 
</details>
Agreed.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614)*

**Comment by AdoHe** [comment]
*[pkg/kubectl/cmd/run.go, line 172 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614#-KPJAQ1oAZ3YyuUGx8HW:-KPKl6-1kQk2JKjp0WmP:bfpv0tr) ([raw file](https://github.com/kubernetes/kubernetes/blob/feda040c45a4c485dc5b289ae47905fe7c001ef3/pkg/kubectl/cmd/run.go#L172)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Shouldn't this return the err?
</details>
ohh~some stupid mistake I just made.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614)*

**Comment by pwittrock** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/kubectl/run.go, line 911 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614#-KPJC1FWxW5dv7NcwXMu:-KPKrxRVQ2OxoKiXCqee:bc4aiyn) ([raw file](https://github.com/kubernetes/kubernetes/blob/feda040c45a4c485dc5b289ae47905fe7c001ef3/pkg/kubectl/run.go#L911)):*
Alright, sounds good for now.  Consider adding a comment stating we don't know why this is specificed:

>
// TODO: Figure out why this is set here, and whether we can make it consistent with the other places imagePullPolicy is set using the flag

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614)*

**Comment by pwittrock** [comment]
Yeah I really like the new tool.  It is much more powerful and allows you to do diffs against arbitrary versions.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614#-:-KPKsHOpIbop6sk54znk:bm4js35)*

**Comment by AdoHe** [comment]
*[pkg/kubectl/run.go, line 911 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614#-KPJC1FWxW5dv7NcwXMu:-KPLdz6ccC_qJdQ0KVmF:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/feda040c45a4c485dc5b289ae47905fe7c001ef3/pkg/kubectl/run.go#L911)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Alright, sounds good for now.  Consider adding a comment stating we don't know why this is specificed:
> 
> >
> // TODO: Figure out why this is set here, and whether we can make it consistent with the other places imagePullPolicy is set using the flag
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614)*

**Comment by AdoHe** [comment]
*[pkg/kubectl/cmd/run.go, line 172 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614#-KPJAQ1oAZ3YyuUGx8HW:-KPLe4SWFYzar1n-1mPi:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/feda040c45a4c485dc5b289ae47905fe7c001ef3/pkg/kubectl/cmd/run.go#L172)):*
<details><summary><i>Previously, AdoHe (TonyAdo) wrote…</i></summary>
> ohh~some stupid mistake I just made.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614)*

**Comment by AdoHe** [comment]
@pwittrock Just update, ptal.

**Comment by ymqytw** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614#-:-KPMTSB-Tl-aB-B2xmhF:bnfp4nl)*

**Comment by pwittrock** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614#-:-KPOR_11sB238uzr_GSc:bnfp4nl)*

**Comment by pwittrock** [comment]
Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614)*

**Comment by pwittrock** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30614#-:-KPOSKWS5UVFRnrh6mXc:bnfp4nl)*

**Comment by pwittrock** [comment]
@AdoHe I thin there is a way for you to mark my comments as done in Reviewable.  In the future would you see if this is possible?

**Comment by AdoHe** [comment]
@pwittrock yes, it should be possible to do that.

**Pull request merged**
