### PR TITLE
Add port constants

### PR DESCRIPTION
**Pull request by ping035627**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
Add port constants for 10250-10252.

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

/release-note-none
/priority backlog

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks for the PR @ping035627 
so this seems OK to me.

let's see what others think.
@kubernetes/sig-cluster-lifecycle-pr-reviews 

/ok-to-test

**Review by rosti — CHANGES_REQUESTED** [review]
Thanks @ping035627 !

However there are constants, that are already defined for these ports and we should use them instead.
You can checkout `k8s.io/kubernetes/pkg/master/ports` for those.

**Comment by neolit123** [comment]
> Thanks @ping035627 !
> 
> However there are constants, that are already defined for these ports and we should use them instead.
> You can checkout `k8s.io/kubernetes/pkg/master/ports` for those.

i think the ports package is fine for this as it contains only ports.go with constants.

however i see this in our `app/constants/constants.go` file:

> 	// LeaseEndpointReconcilerType will select a storage based reconciler
	// Copied from pkg/master/reconcilers to avoid pulling extra dependencies
	// TODO: Import this constant from a consts only package, that does not pull any further dependencies.
	LeaseEndpointReconcilerType = "lease"

so maybe the pkg/master dependency is undesired.
pkg/master is unused in kubeadm for the time being.

**Comment by rosti** [comment]
> however i see this in our `app/constants/constants.go` file:
> 
> > // LeaseEndpointReconcilerType will select a storage based reconciler
> > // Copied from pkg/master/reconcilers to avoid pulling extra dependencies
> > // TODO: Import this constant from a consts only package, that does not pull any further dependencies.
> > LeaseEndpointReconcilerType = "lease"
> 
> so maybe the pkg/master dependency is undesired.
> (pkg/master is unused in kubeadm for the time being)

`pkg/master/reconcilers` is a totally different package. It pulls a huge amount of dependencies with itself and causes kubeadm to gain several MB of compiled binary size because of it. And we were pulling it because of a single string constant.
`pkg/master/ports`, however, contains only constants and has no dependencies.

**Comment by neolit123** [comment]
SGTM, @ping035627 please update the PR to use the suggested constants / package by @rosti

**Comment by ping035627** [comment]
@neolit123 @rosti so, should we move the 'EtcdListenClientPort' and 'EtcdListenPeerPort' to pkg/master/ports?

**Comment by neolit123** [comment]
@ping035627 

> @neolit123 @rosti so, should we move the 'EtcdListenClientPort' and 'EtcdListenPeerPort' to pkg/master/ports?

let's not do that for now.

**Comment by ping035627** [comment]
@neolit123 ok, I have updated the PR to use the suggested constants.

**Comment by neolit123** [comment]
try running `./hack/update-bazel.sh` first and adding the changes as part of the same commit.

**Review by dixudx — APPROVED** [review]
/lgtm

**Pull request merged**
