### PR TITLE
fix some typo

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test
/release-note-none
/lgtm

**Comment by zjj2wry** [comment]
@cblecker i watch test can be sucess, so rebase master. can you apply lgtm again. think you

**Comment by zjj2wry** [comment]
ping @lavalamp mind for approval?

**Comment by wojtek-t** [comment]
@k8s-bot pull-kubernetes-unit test this

**Pull request merged**
