### PR TITLE
Bump kube-dns version for kubeadm upgrade

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <ha.chuck@gmail.com>

**What this PR does / why we need it**: This PR bumps the version of kube-dns to the correct version for the kubeadm upgrade path.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Related to kubernetes/kubeadm#739 although that is a different ticket, the bug was reported there.

**Special notes for your reviewer**:

This should also be cherry picked to the 1.9 release since the kube-dns was also cherry picked.

related PR
https://github.com/kubernetes/kubernetes/pull/62678

**Release note**:

```release-note
NONE
```
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews

### CODE REVIEW

**Comment by detiber** [comment]
@chuckha It looks like this needs to be backported to release-1.10 in addition to release-1.9

**Comment by chuckha** [comment]
Yeah, both for sure makes sense. also it looks like I will have to update those tests! oh well

**Review by timothysc — APPROVED** [review]
/approve

**Pull request merged**
