### PR TITLE
fix: correct incorrect comment & function name about SchedulingGated

### LINKED ISSUE #123043: incorrect comment & function name about SchedulingGated
### What happened?

image
https://github.com/kubernetes/kubernetes/blob/4f910fe47cc9a0cf648a049a6cccc38be17b0ad6/pkg/printers/internalversion/printers.go#L839-L844

image

https://github.com/kubernetes/kubernetes/blob/4f910fe47cc9a0cf648a049a6cccc38be17b0ad6/pkg/registry/core/pod/strategy.go#L740-L742

Here are some incorrect comments and function name about SchedulingGated

### What did you expect to happen?

Comments and function names need to be changed to SchedulingGated

### How can we reproduce it (as minimally and precisely as possible)?

nothing

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by yanhuan0802**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Correct incorrect comment & function name about SchedulingGated.

#### Which issue(s) this PR fixes:
Fixes #123043 

#### Special notes for your reviewer:
 @Huang-Wei   PTAL, thanks.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
NONE
```

### CODE REVIEW

**Review by kerthcet — COMMENTED** [review]
/lgtm
/approve

Thanks!

**Comment by Huang-Wei** [comment]
/lgtm

Kind ping @kubernetes/sig-cli-kubectl-maintainers  to approve changes on `pkg/printers/*`.

**Review by justankiit — COMMENTED** [review]
/Thanks
Looks fixed now!

**Comment by kerthcet** [comment]
Seems no one put an eye on this, can you help to take a look @liggitt approved from scheduling.

**Pull request merged**
