### PR TITLE
Split informers by internal and external to allow inclusion in client-go

### PR DESCRIPTION
**Pull request by deads2k**
client-go doesn't have any internal clients, so informers which require internal clients can never be included in it.  This splits the informer generation into internal and external so we can safely include them.

@kubernetes/sig-api-machinery-misc @ncdc

### CODE REVIEW

**Comment by ncdc** [comment]
Seems reasonable, but something is up with verifying the generated code:

```
unable to read file "internalversion/pod.go" for comparison: open /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/internalversion/core/internalversion/pod.go: no such file or directory
```

**Comment by deads2k** [comment]
> Seems reasonable, but something is up with verifying the generated code:

Well, that's neat

**Comment by deads2k** [comment]
Found it.  Just a default path that was updated with `sed`.

**Comment by deads2k** [comment]
@ncdc think I got it this time

**Comment by deads2k** [comment]
@ncdc just linting now

**Pull request merged**
