### PR TITLE
Update the code to be in sync and pass CI tests.

### PR DESCRIPTION
**Pull request by mbruzek**
I updated the code to pass our charm CI tests and need to put those changes in the kubernetes repsoitory.  

Changes involved getting the charm code to pass `flake8` and `charm proof` linting tools.
Updates to the tests and charm code to pass CI test.

### CODE REVIEW

**Comment by mbruzek** [comment]
I would like to request some help here.  The travis error is:

Boilerplate header is wrong for: /home/travis/gopath/src/github.com/kubernetes/kubernetes/cluster/juju/charms/trusty/kubernetes-master/hooks/__init__.py
Boilerplate header is wrong for: /home/travis/gopath/src/github.com/kubernetes/kubernetes/cluster/juju/charms/trusty/kubernetes/hooks/lib/__init__.py

These are blank files that allow the installation of a package.  The travis tool wants a blank line after the copyright header.  The lint tools that we use (flake8) complains in error if these files have a blank line at the end of the file so I added # noqa, and how these files fail with wrong header.

The two tools directly conflict with the messages.  Can someone suggest an alternative?

**Comment by mbruzek** [comment]
I ended up adding an ignore flag to the flake8 tool for that specific rule that conflicts with the verify-boilerplate.sh tool.

**Comment by zmerlynn** [comment]
@k8s-bot ok to test

**Comment by zmerlynn** [comment]
Reopening to kick Shippable.

**Comment by mbruzek** [comment]
@zmerlynn I don't know what failed on shippable, or how to fix this.  Can you help?

**Comment by zmerlynn** [comment]
I was trying to figure that out, too. It doesn't seem related to your change. Kicking again. There's possibly one more thing we can do after that.

**Pull request merged**
