### PR TITLE
List RSes once when getting old/new RSes in deployment e2e tests

### PR DESCRIPTION
**Pull request by janetkuo**
Ref #26509 #26204

[Analytics]()

### CODE REVIEW

**Comment by janetkuo** [comment]
Code updated to address comments.

**Comment by pwittrock** [comment]
@k8s-bot unit test this issue: #26345 

[test artifacts](https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/26654/kubernetes-pull-test-unit-integration/28789/artifacts/)

**Comment by pwittrock** [comment]
This is really clean.  Thanks Janet.

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please, issue: #26682

**Comment by wojtek-t** [comment]
@janetkuo - thanks for this change, for it seems that it would fix the problem; shouldn't we close the bug once the PR is fixed?

**Pull request merged**
