### PR TITLE
Automated cherry pick of #64427: add external resource group support for azure disk

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #64427 on release-1.9.

#64427: add external resource group support for azure disk

### CODE REVIEW

**Comment by andyzhangx** [comment]
/assign @jsafrane @rootfs 
This is a combined cherry-pick with https://github.com/kubernetes/kubernetes/pull/64427, https://github.com/kubernetes/kubernetes/pull/65443 & https://github.com/kubernetes/kubernetes/pull/65516

**Comment by andyzhangx** [comment]
@jsafrane I have cherry-picked with https://github.com/kubernetes/kubernetes/pull/65691 now, PTAL

**Comment by nikhita** [comment]
/assign @colemickens 
for approval

/assign @mbohlool 
for cherry-pick approval

**Comment by andyzhangx** [comment]
@brendandburns for approval

**Comment by feiskyer** [comment]
ping @colemickens for approval

**Comment by mbohlool** [comment]
/hold

1.9 branch is frozen for the release.

**Pull request merged**
