### PR TITLE
code-generator: unify generator main funcs and prepare for launching from one binary

### PR DESCRIPTION
**Pull request by sttts**
- remove "generated by client-gen with custom arguments" message as this does not
  make sense in the times of k8s.io/code-generator
- unify generator main funcs and explicitly call pflag.AddFlags and pflag.Parse. This
  will allow to instantiate the generators also from other places.

Requires https://github.com/kubernetes/gengo/pull/80.

Closes https://github.com/kubernetes/kubernetes/issues/53522.

### CODE REVIEW

**Comment by thockin** [comment]
What is the ultimate goal?

**Comment by sttts** [comment]
@thockin the mid term goal is to be able to launch generators for certain use-cases from one go binary, something like kube-gen, i.e. the go variant of https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/code-generator/generate-internal-groups.sh. Short term having a unified structure for our generators' main funcs has value in its own.

**Comment by thockin** [comment]
/lgtm
This needs an associated issue and a `closes #12345` in the FIRST COMMENT, or it can not be approved.

**Comment by sttts** [comment]
> Is there a proposal or design doc about this goal? I have some things I have been playing with in regards to making the build around codegen and the horrible Makefile simpler. If you have other goals, I'd like to be aware so I don't waste time.

Created https://github.com/kubernetes/kubernetes/issues/53524. Until now I was mainly thinking about providing a "kube-gen" tool and/or Docker containers. But if we can use this for Kubernetes itself as well, even better.

**Pull request merged**
