### PR TITLE
RBAC: compare output

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zjj2wry** [comment]
@deads2k sorry for ping you again. the pkg/kubectl/cmd/create_rolebinding.go alse you write.  😊

**Comment by deads2k** [comment]
What I'd really like to see is something like the openshift style of `test-cmd.sh` (https://github.com/openshift/origin/blob/master/test/cmd/policy.sh) to check for scripting compatibilty.  I don't care for enforcing these in unit tests since their "home" is in a script.

**Comment by zjj2wry** [comment]
@deads2k cool and concise, but i think that more like e2e test. can you do something get-started with that?

**Comment by deads2k** [comment]
> @deads2k cool and concise, but i think that more like e2e test. can you do something get-started with that?

I'm not particularly bash literate, so I'd really like someone better in the bash space to port the helpers down and demonstrate integrating them in a couple of the test-cmd checks.

**Comment by zjj2wry** [comment]
@deads2k i am willing study it. but now i am more intersting with openshift/origin. i will set up it in local today and study use it. just now i find **fabianofranz** and **soltysh** alse in openshift team.
i spend 1 month in k8s just remember them alse you :). any suggest for know openshift/origin more quick? i am attention with productization and test.

**Comment by deads2k** [comment]
> @deads2k i am willing study it. but now i am more intersting with openshift/origin. i will set up it in local today and study use it. just now i find fabianofranz and soltysh alse in openshift team.
> i spend 1 month in k8s just remember them alse you :). any suggest for know openshift/origin more quick? i am attention with productization and test.

The original author of those functions is @stevekuznetsov and @sttts could probably find some cycles for a porting review to fix up `test-cmd.sh`.  There are tests for the bash functions since the logic isn't simple.

**Comment by zjj2wry** [comment]
@deads2k think you. i use openshift command line **oc cluster up**. just spend 5 minutes and set up my app. very cool~ has question: 1. why monitor just app status and log, can i get some cpu/mem matrics? 2.[rbac] openshift different with k8s? because i can not find access-control in my ui.

**Comment by deads2k** [comment]
> why monitor just app status and log, can i get some cpu/mem matrics?

Prometheus ought to be exposed.  Are you looking for a different API?




> [rbac] openshift different with k8s?

Yes.  RBAC is a port of the openshift types.  `oc policy create-role-to-user <clusterrolename> <username>` generally gets you where you need to go.  The types are very close if you need to convert.  We will collapse back onto RBAC in the near future.

**Comment by stevekuznetsov** [comment]
FWIW I think it's too easy to write poor tests in Bash, even with those helpers. I'd suggest Ginkgo, if you _need_ speed, don't start the kubelet for the test.

**Comment by zjj2wry** [comment]
@deads2k think you for answer，solved. i really like openshift/origin rollout feature in ui. has question: 1. openshift “project”==namespace? and how can i control resouce use? because i can not find create quota entrance in my dashboard. 2.sometime kubectl rollout history i can not get **cauth rollout reason**,openshift different with k8s? 3.kind: BuildConfig api implement by thirtpartyresource?

**Comment by zjj2wry** [comment]
@deads2k i find others write bash test for RBAC in hack/make-rules/test-cmd-util.sh. Do you know some work can do in that?

**Pull request closed without merging**
