### PR TITLE
Speed up master reconciler tests

### PR DESCRIPTION
**Pull request by gitlawr**
**What type of PR is this?**
/kind bug
/kind flake

**What this PR does / why we need it**:
Speed up master reconciler tests.
Start apiservers in parallel. It reduce the time for starting 3 instances of apiservers from ~13s to ~6s.

The comparison result is shown in the following diagram. On average, it reduces the test time from 85s to 57s(-33%). Tests are done by running the following command for 10 times:
```
make test-integration WHAT="./test/integration/master" GOFLAGS="-v" KUBE_TEST_ARGS="-run ^TestReconcilerMasterLease.*$"
```
image

**Which issue(s) this PR fixes**:

Related to issue https://github.com/kubernetes/kubernetes/issues/93609

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by liggitt — COMMENTED** [review]
Thanks, this looks promising. I'd also consider lowering the numbers of masters in the test from 3 to 2, like

```diff
diff --git a/test/integration/master/kube_apiserver_test.go b/test/integration/master/kube_apiserver_test.go
index d4d52a7506f..01becece577 100644
--- a/test/integration/master/kube_apiserver_test.go
+++ b/test/integration/master/kube_apiserver_test.go
@@ -488,15 +488,15 @@ func testReconcilersMasterLease(t *testing.T, leaseCount int, masterCount int) {
 }
 
 func TestReconcilerMasterLeaseCombined(t *testing.T) {
-	testReconcilersMasterLease(t, 1, 3)
+	testReconcilersMasterLease(t, 1, 2)
 }
 
 func TestReconcilerMasterLeaseMultiMoreMasters(t *testing.T) {
-	testReconcilersMasterLease(t, 3, 2)
+	testReconcilersMasterLease(t, 2, 1)
 }
 
 func TestReconcilerMasterLeaseMultiCombined(t *testing.T) {
-	testReconcilersMasterLease(t, 3, 3)
+	testReconcilersMasterLease(t, 2, 2)
 }
 
 func TestMultiMasterNodePortAllocation(t *testing.T) {
```

The main thing we want to exercise is multiple processes interacting, which that still does. I'd be curious how that impacted the test speed as well.

**Comment by gitlawr** [comment]
By reducing the number of masters the testing duration drops to ~41s.
The following is the comparison diagram:
compare-new

@liggitt  I've updated the pr per your suggestion

**Comment by liggitt** [comment]
/lgtm
/approve

thanks! I still think we should look for ways to improve this in the future, but this is a big initial improvement for a minimal change

**Comment by liggitt** [comment]
/milestone v1.19

this package timeout is currently the [primary source of flakes](https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&job=integration&xtest=run_kubectl_apply_tests%7CTestLimits) in the pull-integration job

**Pull request merged**
