### PR TITLE
Fix golint failure - "cmd/cloud-controller-manager/app/apis/config/v1alpha1"

### PR DESCRIPTION
**Pull request by jiefeng-xu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix golint failure - "cmd/cloud-controller-manager/app/apis/config/v1alpha1"

**Which issue(s) this PR fixes**:

Fixes #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by jiahuif** [comment]
The build fails understandably. What is the rationale of removing `cmd/cloud-controller-manager/app/apis/config/v1alpha1` from `cmd/cloud-controller-manager/app/apis/config/BUILD`?

**Comment by stantonxu** [comment]
It is messed by my accidental merge to master. I will create a new PR for it.

**Comment by stantonxu** [comment]
PR #92121 created to replace this one, hence close this one here.

**Pull request closed without merging**
