### PR TITLE
graduate IngressClassNamespacedParams to beta

### PR DESCRIPTION
**Pull request by hbagdi**
#### What type of PR is this?

/kind feature
#### What this PR does / why we need it:

Graduates IngressClassNamespacedParams feature gate to beta and enabling it by default.

#### Does this PR introduce a user-facing change?

```release-note
IngressClassNamespacedParams feature gate has graduated to beta and is enabled by default. This means IngressClass resource will now have two new fields - `spec.paramters.namespace` and `spec.parameters.scope`.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2365-ingressclass-namespaced-params
Enhancement issue: https://github.com/kubernetes/enhancements/issues/2365

/sig network
/priority important-soon
/assign @robscott

### CODE REVIEW

**Comment by hbagdi** [comment]
`TestRoundTripTypes` is failing because the default is now being injected by by the defaulting logic but that is not expected.
Any pointer on where to look to fix this would be helpful.

**Comment by robscott** [comment]
This PR LGTM but I can't figure out how to get the test to pass. The relevant [test code is here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/roundtrip.go#L361), it's attempting a `runtime.Encode` followed by a `runtime.Decode` and in that process the default is getting added. I'm not really sure how to avoid this though. I looked at the relevant [fuzzer](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/networking/fuzzer/fuzzer.go) in case an addition was needed there, but that doesn't seem to be the case, so I'm not really sure what it is. So that's a lot of words just to say that I really don't know, but maybe this will help someone figure out what's missing?

**Comment by aojea** [comment]
> This PR LGTM but I can't figure out how to get the test to pass. The relevant [test code is here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/apitesting/roundtrip/roundtrip.go#L361), it's attempting a `runtime.Encode` followed by a `runtime.Decode` and in that process the default is getting added. I'm not really sure how to avoid this though. I looked at the relevant [fuzzer](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/networking/fuzzer/fuzzer.go) in case an addition was needed there, but that doesn't seem to be the case, so I'm not really sure what it is. So that's a lot of words just to say that I really don't know, but maybe this will help someone figure out what's missing?

I'm not going to pretend that I know why this fixes it, I checked other fuzzers and find out that they set default values, so I did the same

```diff
diff --git a/pkg/apis/networking/fuzzer/fuzzer.go b/pkg/apis/networking/fuzzer/fuzzer.go
index a9f2f552990..7284773a782 100644
--- a/pkg/apis/networking/fuzzer/fuzzer.go
+++ b/pkg/apis/networking/fuzzer/fuzzer.go
@@ -20,6 +20,7 @@ import (
        fuzz "github.com/google/gofuzz"
        runtimeserializer "k8s.io/apimachinery/pkg/runtime/serializer"
        "k8s.io/kubernetes/pkg/apis/networking"
+ utilpointer "k8s.io/utils/pointer"
 )
 
 // Funcs returns the fuzzer functions for the networking api group.
@@ -64,5 +65,14 @@ var Funcs = func(codecs runtimeserializer.CodecFactory) []interface{} {
                                }
                        }
                },
+         func(p *networking.IngressClass, c fuzz.Continue) {
+                 c.FuzzNoCustom(p) // fuzz self without calling this function again
+                 // default Parameters to Cluster
+                 if p.Spec.Parameters == nil || p.Spec.Parameters.Scope == nil {
+                         p.Spec.Parameters = &networking.IngressClassParametersReference{
+                                 Scope: utilpointer.StringPtr(networking.IngressClassParametersReferenceScopeCluster),
+                         }
+                 }
+         },
        }
 }
```

@liggitt is this the right fix? ^^^

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Review by thockin — COMMENTED** [review]
It looks like some tests were not running with the gate disabled now fails.  Those need to be fixed.

**Comment by thockin** [comment]
Let's remember to update https://github.com/orgs/kubernetes/projects/10 when this merges

**Comment by hbagdi** [comment]
@aojea @robscott I included the fuzzer update from Antonio's comment and it looks like tests are green now.
What I don't know is if there is any side-effect of that patch, like hiding a bug that the failed test was representing.
Please take another look and review. Thanks!

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Comment by thockin** [comment]
I moved it on the project board.

**Pull request merged**
