### PR TITLE
[FEATURE BRANCH] Check flowcontrol api group enabled

### PR DESCRIPTION
**Pull request by yue9944882**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@MikeSpreitzer

**Comment by MikeSpreitzer** [comment]
BTW, the title of this PR says "ensure" but perhaps better terminology would be about "check".  The word "ensure" has connotations of "make condition X hold if it does not already hold", but the code here does not make any changes, it only checks whether the condition holds.

**Comment by yue9944882** [comment]
reworded titile

**Pull request merged**
