### PR TITLE
Fix non-masquerade CIDR

### PR DESCRIPTION
**Pull request by justinsb**
Building on #22879 to try to get a PR that passes our very-stringent tests!

### CODE REVIEW

**Comment by justinsb** [comment]
@k8s-bot test this github flake #20916

**Comment by mikedanese** [comment]
@mm0 can you acknowledge that you are ok with this commit being contributed?

**Comment by mm0** [comment]
I'm ok with this commit being contributed

**Comment by justinsb** [comment]
Thanks @mikedanese.  I manually tested that the AWS 100.64 example works as well.

**Pull request merged**
