### PR TITLE
Move some docs files out of top-level into admin/, devel/, or user-guide/

### PR DESCRIPTION
**Pull request by davidopp**
The ones that remain fell into one of two categories
(1) Should not exist on their own -- should be merged into other docs and then deleted (kube-apiserver.md, kube-controller-manager.md, kubelet.md, services-firewall.md)
(2) Geuinely feel like they belong at top-level (api.md, glossary.md, roadmap.md, troubleshooting.md)

@bgrant0607 @erictune @lavalamp

### CODE REVIEW

**Comment by lavalamp** [comment]
Should docs/devel/developer-guide.md be docs/devel/README.md?

**Comment by lavalamp** [comment]
LGTM otherwise. I definitely intended to have moved some of these files already, I guess I missed them.

**Comment by bgrant0607** [comment]
Link checker needs to be run.

**Comment by bgrant0607** [comment]
Yes, developer-guide.md should become devel/README.md.

**Comment by bgrant0607** [comment]
Or rather be unified with the existing README.md.

**Comment by davidopp** [comment]
Ran link checker.

How about we leave the move of developer-guide.md as-is, then I can unify with devel/README.md in a separate PR?

**Comment by bgrant0607** [comment]
I'm fine with unification in a separate PR

**Comment by bgrant0607** [comment]
LGTM

**Comment by davidopp** [comment]
It's not really possible to rebase this after #11191, which was just merged. I'll redo and send out a new PR.

**Pull request closed without merging**
