### PR TITLE
Isolate the logic related to the configuration of kube-apiserver into a separate script.

### PR DESCRIPTION
**Pull request by immutableT**
**What type of PR is this?**
> /kind feature

**What this PR does / why we need it**:
I am working on removing the logic related to rendering of kube-apiservers' manifest out of configure-helper.sh. To this end, I will be refactoring start-kube-apiserver function to isolate the components that do need to stay in configure-helper (ex. audit config logic).
Having a separate script that encapsulates the logic of configuring kube-apiserver will simplify refactoring and testing.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Comment by yguo0905** [comment]
Have we verified this on GKE?

**Comment by immutableT** [comment]
@yguo0905  Yes, this was tested on GKE.

**Pull request merged**
