### PR TITLE
Add kubelet to the master via standard mechanisms.

### PR DESCRIPTION
**Pull request by brendandburns**

### CODE REVIEW

**Comment by vmarmol** [comment]
LGTM

**Comment by antoineco** [comment]
Sorry if I missed some bits of information, but why do we need a kubelet running on the master?

**Comment by vmarmol** [comment]
@antoineco we run the Kubelet on the master today. The master components run as pods as well.

**Comment by antoineco** [comment]
Thanks @vmarmol for the quick answer. So this commit (and the ones which followed for other cloud providers) are just meant to prepare the field for running k8s components in pods in the near future right?

In the current setup the master's kubelet logs are flooded with warning because the master itself is not registered as a node, can it already be handled in some way? (apart from registering the master and making it unschedulable :) )

**Comment by vmarmol** [comment]
Yes, although this change in particular was to make explicit something that we relied on but didn't verify.

Handling the master (by doing exactly what you describe) is being worked on right now :)

**Pull request merged**
