### PR TITLE
Pseudo Cherrypick: Fix the node controller in an emulation of #12546

### PR DESCRIPTION
**Pull request by brendandburns**
@zmerlynn @roberthbailey (our first PR that isn't officially cherry pickable, one of many, I assume)

### CODE REVIEW

**Comment by zmerlynn** [comment]
Cross-link #12546.

**Comment by brendandburns** [comment]
I think that Shippable is borked on `release-1.0` due to the grand rename.

**Comment by zmerlynn** [comment]
@mikedanese Can you send cherry picks along to fix the release branch?

**Comment by mikedanese** [comment]
still needs a rebase to pick up shippable fix (since shippable uses "ours" shippabl.yml, not the merge result)

**Comment by zmerlynn** [comment]
> (since shippable uses "ours" shippabl.yml, not the merge result)

I'm confused, what's it merging from? They should be checking out `release-1.0` and merging in the PR.

**Comment by mikedanese** [comment]
@zmerlynn It's somewhat braindead but the shippable process is:

1. Checkout the pr branch (brendandburns:cherrypick)
2. Load shippable.yml
3. Merge target branch (kubernetes:release-1.0)
4. Run tests according to the previously loaded shippable.yml

I only know this because I ran into it before. As a consequence,  changes to shippable.yml (like the repository move change) sometimes require rebasing lot's of (or all) PRs.

**Comment by zmerlynn** [comment]
@mikedanese: Thanks for the explanation, but sigh. So they all have to be rebased beyond this change now, which is kind of painful because many of them are from the script.

**Comment by zmerlynn** [comment]
@brendandburns: Please rebase and repush this. There won't be any conflicts, it'll just fix Shippable.

**Comment by zmerlynn** [comment]
@brendandburns: Thanks!

**Comment by brendandburns** [comment]
Shippable is a flake, I kicked it again.

**Pull request merged**
