### PR TITLE
Don't pull from docker hub in deployment e2e test

### PR DESCRIPTION
**Pull request by janetkuo**
Partially addresses #13288

@kubernetes/sig-config

### CODE REVIEW

**Comment by janetkuo** [comment]
@k8s-bot e2e test this issue: #21940

**Comment by bgrant0607** [comment]
Thanks. Judging by the patterns of failures I've seen during Docker hub outages, I'd guess there are non-Deployment tests that hit Docker Hub, so we should leave the issue open until we confirm that all occurences have been updated.

**Comment by bgrant0607** [comment]
Ideally these images would be tagged rather than just using the latest, but this is an improvement over Docker Hub, so LGTM.

**Comment by eparis** [comment]
This PR has added the `cherrypick-candidate` label but did not set a milestone. This is an invalid state and will not be considered for cherrypick-ing to any release branch. The `cherrypick-candidate` label will be automatically removed from such PRs in the future.

**Comment by eparis** [comment]
This PR is already included in the release-1.2 branch and does not require cherrypick-ing

**Pull request merged**
