### PR TITLE
Implement a FakeClient interface

### PR DESCRIPTION
**Pull request by markusthoemmes**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

As a followup to #100085, this adds an interface for Fake clients and asserts the Fake client actually implements it.

#### Does this PR introduce a user-facing change?

```release-note
Fake clients now implement a `FakeClient` interface
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by markusthoemmes** [comment]
Pokeroo @liggitt in case this has fallen between the cracks.

**Comment by liggitt** [comment]
/lgtm
/approve

thanks!

**Pull request merged**
