### PR TITLE
Re-enabled HPA e2e in autoscaling suite

### PR DESCRIPTION
**Pull request by piosz**
Fixes issue with Autoscaling suite introduced in #17180

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM

**Comment by ixdy** [comment]
Sorry, missed this in all the rebasing. @karlkfi

**Comment by karlkfi** [comment]
Rebase hell strikes again!

As mentioned in https://github.com/kubernetes/kubernetes/pull/17180#issuecomment-159345868 I believe that (unless it was recently reverted) the Deployment tests were recently tagged for `[Autoscaling]` too. So it probably makes sense to just tag the parent describe block.

**Comment by karlkfi** [comment]
Confirmed above: https://github.com/kubernetes/kubernetes/commit/d246e7833b0653e8e82c129a44a444dc090004ad

**Pull request merged**
