### PR TITLE
[WIP] Trying PID Namespace sharing from Docker 1.12 release candidates

### PR DESCRIPTION
**Pull request by dims**
Seems to work!

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29677)

### CODE REVIEW

**Comment by dims** [comment]
@thockin thought you may be interested :)

**Comment by yujuhong** [comment]
/cc @kubernetes/sig-node 

Can we add a node e2e test for this?

**Comment by vishh** [comment]
I'd prefer converting the infra container to be an init before enabling this feature.

**Comment by vishh** [comment]
@dims Interested in writing some `C` code to morph [`pause`](https://github.com/kubernetes/kubernetes/blob/f2ddd60eb9e7e9e29f7a105a9a8fa020042e8e52/build/pause/pause.c) into a light-weight init that can forward signals and reap zombies?

**Comment by dims** [comment]
@vishh oooo...zombie hunting. sign me up :) 

more seriously, will take a stab at it. Any pointers? let me know please.

-- Dims

**Comment by dims** [comment]
Found a bunch of options in this discussion: https://news.ycombinator.com/item?id=10852055

**Comment by dims** [comment]
Tini seems to be best of the lot - MIT License - https://github.com/krallin/tini/blob/master/src/tini.c

**Comment by Random-Liu** [comment]
Ref https://github.com/kubernetes/kubernetes/issues/28698

**Comment by thockin** [comment]
nice!

**Comment by thockin** [comment]
We will need some good docs on this, and maybe an example of the power of it.

**Comment by dims** [comment]
@vishh please see https://github.com/kubernetes/kubernetes/pull/29747

**Comment by dims** [comment]
@thockin yes of course will work on docs once i get the light weight init thingy working

**Comment by dims** [comment]
Related to https://github.com/kubernetes/kubernetes/issues/1615

**Comment by dims** [comment]
need to watch https://github.com/opencontainers/runc/pull/976

**Pull request closed without merging**
