### PR TITLE
Support for BSD/Darwin in cluster/saltbase/install.sh Fixes #30703

### LINKED ISSUE #30703: `kubernetes/cluster/saltbase/install.sh` doesn't work on BSD/Darwin based systems
Running `kubernetes/cluster/saltbase/install.sh` in Darwin (e.g: macos) or BSD (freebsd) won't work due to slight incompatibilities in `cp` and `sed`.

No need to work on it, I'm creating a PR to fix it.

### PR DESCRIPTION
**Pull request by vromero**
**What this PR does / why we need it**:

Adds support for BSD-style systems in `cluster/saltbase/install.sh`.

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #

Fixes #30703

**Special notes for your reviewer**:

**Release note**:

``` release-note
Added support for BSD/Darwin in `cluster/saltbase/install.sh`.
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30705)

### CODE REVIEW

**Comment by vromero** [comment]
I signed it!

**Comment by zmerlynn** [comment]
I edited your first comment slightly. It said "non BSD systems" originally.

@k8s-bot ok to test

**Comment by zmerlynn** [comment]
What is the need of this? In general, we're trying to put a nail in the Salt, even though it's the primary templating / config mechanism on GCE nodes, but not master, right now. I'm a little leery extending the arch support.

**Comment by vromero** [comment]
I see your point about not changing this it if it is meant to be removed, but if you take a look to the changes, they are so small given that it is just compatibility around UNIX flavors (vs, for instance, adding support for powershell) that I believe they make sense.
I bet a very sensible portion of the user base use Darwin/Mac, and they could potentially leverage this change now while salt is being phased out or moved to an external project in the future.

**Comment by zmerlynn** [comment]
We have a substantial portion of our userbase that uses Darwin/Mac for controlling deployment and build, so things like `make release` and `cluster/kube-up.sh` are areas where I tend to see a fair amount of difference with OS X changes, but `cluster/saltbase/install.sh` is run on the master/nodes as part of deployment. I don't know of anyone trying to get FreeBSD or Darwin working as a host OS for k8s with the Salt deployment. Is that what you're working on? If so, that's fine.

**Comment by vromero** [comment]
To be honest I'm hacking around with salt having as salt master my very own (mac) machine, just for the sake of understanding the whole process top to bottom, that is why it is useful to me.
But value wise for the wider audience: I see frebsd as relevant k8s master side and darwin relevant for k8s hackers just like it was for me. This said, I see and share up to an extent your previous point, it is just the change is small enough to be valuable.

**Comment by zmerlynn** [comment]
If you're trying to play around with simple deployment, you may want to look at https://github.com/kelseyhightower/kubernetes-the-hard-way. Alternately, you can take a look at https://github.com/kubernetes/kubernetes-anywhere, especially after https://github.com/kubernetes/kubernetes-anywhere/pull/197 lands.

I'm reluctant to take this PR until someone is signed up to support FreeBSD masters, and Darwin as a server machine is almost 0 market. Code has cost, and the minor belief that the Salt code supports FreeBSD might make someone else believe that everything will be hunky-dory. I suspect you will run into other issues pretty quickly once you fix the basic userland pieces, simply because `kubelet` relies so heavily on Linux-isms (I know FBSD has a Linux syscall emulation layer, but we strain Linux, and we've obviously done zero testing elsewhere).

**Comment by vromero** [comment]
Please feel free to close, the change so small that it is not worthy of being over discussed.

Not related but just in case you are the right person to ask, if I find potential improvements/fixed in saltbase while playing. Is it worthy to PR them?

**Comment by zmerlynn** [comment]
Sure, definitely. Thanks!

**Pull request closed without merging**
