### PR TITLE
typo of errUnsuportedVersion

### PR DESCRIPTION
**Pull request by tianshapjq**
**What this PR does / why we need it**:
typo of errUnsuportedVersion in pkg/kubelet/cm/deviceplugin/types.go

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```NONE

### CODE REVIEW

**Comment by mindprince** [comment]
This could have been combined with #58058. But separate is fine as well.

**Comment by RenaudWasTaken** [comment]
/area hw-accelerators 

@mindprince I think we need to add this label more so that we can have a better issue coordination :)

**Pull request merged**
