### PR TITLE
Remove nested SIGDescribe calls

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref https://github.com/kubernetes/kubernetes/issues/98326

```release-note
NONE
```

/kind cleanup
/priority important-soon

### CODE REVIEW

**Comment by pohly** [comment]
pull-kubernetes-dependencies seems to be failing for everyone at the moment. I brought it up here: https://kubernetes.slack.com/archives/C2C40FMNF/p1614780753136400

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/retest

**Pull request merged**
