### PR TITLE
Build etcd image v3.5.17

### PR DESCRIPTION
**Pull request by bzsuni**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
etcd is now released in [3.5.17](https://github.com/etcd-io/etcd/releases/tag/v3.5.17)
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
none
```

### CODE REVIEW

**Comment by humblec** [comment]
why 2 PRs here @bzsuni for the bump (https://github.com/kubernetes/kubernetes/pull/128773) ?

**Comment by bzsuni** [comment]
> why 2 PRs here @bzsuni for the bump (https://github.com/kubernetes/kubernetes/pull/128773) ? 

We need to build it first before updating, correct?

**Comment by aladesawe** [comment]
@bzsuni @humblec lgtm, comparing to [v3.5.16 build](https://github.com/kubernetes/kubernetes/pull/127283/files). I'm new to the project though, so I may be missing the bigger picture for this upgrade.

**Comment by humblec** [comment]
/lgtm
cc @ahrtr @serathius

**Comment by bzsuni** [comment]
@liggitt  for approval please

**Pull request merged**
