### PR TITLE
Use “comma ok” idiom to get value from map

### PR DESCRIPTION
**Pull request by nayihz**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Use “comma ok” idiom is a common way to judge if one key exist in map.

**Which issue(s) this PR fixes**:
Use “comma ok” idiom to get value from map

### CODE REVIEW

**Comment by lavalamp** [comment]
I think the existing code is safer, in that everything works OK if somehow a nil value gets stored in the map. It looks like that wouldn't be intentional, but without analyzing every map access it's hard to be certain that's not happening.

**Comment by latteczy** [comment]
> I think the existing code is safer, in that everything works OK if somehow a nil value gets stored in the map. It looks like that wouldn't be intentional, but without analyzing every map access it's hard to be certain that's not happening.

I check the logic and find that the value in map will never be set to nil. @lavalamp 

https://github.com/kubernetes/kubernetes/blob/5832c44dbf06b147739a5f7e9179e4a022de9951/pkg/registry/core/service/portallocator/controller/repair.go#L218-L227

**Comment by lavalamp** [comment]
Even if it's fine now, the code isn't static, and people might add bugs.
It's better to be defensive.

**Comment by latteczy** [comment]
OK. I will close this pr.

**Pull request closed without merging**
