### PR TITLE
rkt: Map kubelet's `--stage1-image` flag to rkt's `--stage1-name` flag.

### PR DESCRIPTION
**Pull request by yifan-gu**
This enables rkt to use cached stage1 image instead of unpacking the stage1 image every time for every pod.

After this change, users need to preload the stage1 images in order to enable rkt to find the stage1 image with the name specified by this flag.

Also, the cloud config is modified to pre-load the stage1 images.

cc @kubernetes/sig-rktnetes @kubernetes/sig-node

### CODE REVIEW

**Comment by vishh** [comment]
@yifan-gu I personally dislike the idea of adding rkt specific flags to kubelet directly. Would it be possible to decouple rkt configuration from kubelet?

**Comment by yifan-gu** [comment]
@vishh Today we have 3 rkt flags: (`rkt-path`, `rkt-api-endpoint`, `rkt-stage1-image`).
I think we have plan to deprecate the other two except the `rkt-api-endpoint`. The configuration (such as stage1 image) will be inferred from the rkt api service once the kubelet connects to the rkt api service.

And we will clean up all the rkt binary shell out calls with API calls, so the rkt-path will be deprecated as well.

**Comment by tmrts** [comment]
LGTM after @vishh is okay about the flags

**Comment by yifan-gu** [comment]
Ping @vishh

**Comment by vishh** [comment]
SGTM!

**Comment by tmrts** [comment]
LGTM

**Pull request merged**
