### PR TITLE
Automated cherry pick of #45055

### PR DESCRIPTION
**Pull request by nicksardo**
Cherry pick of #45055 on release-1.6.

#45055: Bump GLBC version to 0.9.3

**Release note**:
```release-note
Bump GLBC version to 0.9.3
```

### CODE REVIEW

**Comment by nicksardo** [comment]
@k8s-bot node e2e test this
@k8s-bot gce etcd3 e2e test this

**Comment by nicksardo** [comment]
@k8s-bot node e2e test this

**Comment by nicksardo** [comment]
Node test failing in other PRs as well. https://github.com/kubernetes/kubernetes/pull/45083#issuecomment-297994289

**Comment by nicksardo** [comment]
@k8s-bot node e2e test this

**Comment by nicksardo** [comment]
@k8s-bot node e2e test this

**Comment by dchen1107** [comment]
I quickly looked into all failures in #45068, #45121 and #45083, and the all volume related tests failed because volume cannot be gc properly, thus pod cannot be deleted.

I believe we hit a known issue: #43534 which is triggered by bumping to go1.8 (#41636)

**Comment by nicksardo** [comment]
@k8s-bot node e2e test this

**Comment by nicksardo** [comment]
@mwielgus Tests have been fixed - can you please set the appropriate cherry pick label and 1.6 milestone? Thanks

**Pull request merged**
