### PR TITLE
Automated cherry pick of #37562

### PR DESCRIPTION
**Pull request by roberthbailey**
Cherry pick of #37562 on release-1.4.

#37562: Use gsed on the mac.

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37673)

**Comment by roberthbailey** [comment]
The jenkins verification is failing golint:

```
W1130 00:47:43.549] Errors from golint:
W1130 00:47:43.550] pkg/storage/etcd3/store_test.go:548:1: context.Context should be the first parameter of a function
W1130 00:47:43.550] 
W1130 00:47:43.550] Please fix the above errors. You can test via "golint" and commit the result.
W1130 00:47:43.550] 
I1130 00:47:43.553] FAILED   hack/make-rules/../../hack/verify-golint.sh	20s
```

which is unrelated to this PR. Did that break on a previous cherry pick?

**Comment by jessfraz** [comment]
This is being tracked here: https://github.com/kubernetes/kubernetes/issues/37254 I am going to update the image for 1.4 to be pinned to a specific version, then we can merge this.

**Comment by jessfraz** [comment]
@k8s-bot verify test this

**Comment by roberthbailey** [comment]
@k8s-bot verify test this

**Comment by jessfraz** [comment]
manually merging since all green and the submit queue is blocked

**Pull request merged**
