### PR TITLE
Migrate the update-demo to use v1beta3.

### PR DESCRIPTION
**Pull request by roberthbailey**
Small part of #6584.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Thanks a lot @roberthbailey!
LGTM.

**Comment by ixdy** [comment]
I think this change broke kubernetes/examples/examples_test.go but was masked by #7052.

https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/59004529:
```
--- FAIL: TestExampleObjectSchemas (0.23s)
	examples_test.go:207: Expected no error, Got lstat ../examples/update-demo/v1beta3: no such file or directory
	examples_test.go:210: Expected 2 examples, Got 0
	examples_test.go:207: Expected no error, Got lstat ../examples/update-demo/v1beta1: no such file or directory
	examples_test.go:210: Expected 2 examples, Got 0
FAIL
coverage: 0.0% of statements
FAIL	github.com/GoogleCloudPlatform/kubernetes/examples	0.436s
```


https://travis-ci.org/GoogleCloudPlatform/kubernetes/jobs/59004530:
```
--- FAIL: TestExampleObjectSchemas (0.34 seconds)
	examples_test.go:207: Expected no error, Got lstat ../examples/update-demo/v1beta1: no such file or directory
	examples_test.go:210: Expected 2 examples, Got 0
	examples_test.go:207: Expected no error, Got lstat ../examples/update-demo/v1beta3: no such file or directory
	examples_test.go:210: Expected 2 examples, Got 0
FAIL
coverage: 0.0% of statements
FAIL	github.com/GoogleCloudPlatform/kubernetes/examples	0.621s
```

**Comment by jlowdermilk** [comment]
Yeah, I'm currently testing one-line fix. Will send to @roberthbailey shortly.

**Comment by roberthbailey** [comment]
Ugh. I even ran e2e on this to make sure I did it correctly. :/

**Pull request merged**
