### PR TITLE
CHANGELOG: fix hyperlink failure for author

### PR DESCRIPTION
**Pull request by 249043822**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by 249043822** [comment]
/ assgin @saschagrunert @cpanato

**Review by hasheddan — APPROVED** [review]
/lgtm
/priority backlog

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
