### PR TITLE
Using a fixed set of locks, then we don't need to free unused locks anymore.

### LINKED ISSUE #65113: volume plugins use of keymutex never cleans up
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-bugs 

**What happened**:
The keymutex library in many volume plugins (azure, cinder, local, scalio, vsphere) creates new mutexes for new keys, but never cleans them up, so the memory will slowly increase as new volumes are created. 

**What you expected to happen**:
 Either keymutex should be fixed to do some cleanup, or an alternative locking mechanism should be used.

### PR DESCRIPTION
**Pull request by cofyc**
**What this PR does / why we need it**:

Using a fixed set of locks, then we don't need to free unused locks anymore.
See kubernetes/kubernetes/pull/66442 for discussions.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #65113

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/assign @msau42 
/assign @thockin

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Should we get rid of the older KeyMutex implementation, since we know it is buggy?

Sorry to be a pain, can we rename to HashedMutex or even to just `keymutex.Hashed` (and NewHashed), which seems more in-line with Go's naming conventions.

**Comment by cofyc** [comment]
Sure, keymutex is only be used in this particular scenario. 
Old implementation is removed and `keymutex.(New)FixedKeyMutex` has been renamed to `keymutex.(New)Hashed`.

**Pull request merged**
