### PR TITLE
Add selector to PersistentVolumeClaim

### PR DESCRIPTION
**Pull request by pmorie**
Refresh of #21308, original credit to @markturansky 

@bgrant0607 for API changes.
@kubernetes/sig-storage

### CODE REVIEW

**Comment by saad-ali** [comment]
The change looks fine. I'm a little apprehensive about merging API changes without the underlying wiring. It would make for a slightly larger PR, but I prefer API change bundled with the business logic.

**Comment by pmorie** [comment]
@saad-ali I can understand that point of view, but most of the features I have written that were sizable were API-first, example: https://github.com/kubernetes/kubernetes/issues/18455.

**Comment by markturansky** [comment]
@pmorie This should only require an additional bit of logic in the binder.  

Start here:  https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/persistentvolume/types.go#L142

At this point, it's already filtered by AccessModes, the line above sorts and searches by Capacity.  We just need an "if selector not nil, then apply selector to labels" as a 3rd filter on available volumes.

This should be a relatively easy addition + unit test along with the API changes.

**Comment by saad-ali** [comment]
> @saad-ali I can understand that point of view, but most of the features I have written that were sizable were API-first, example: #18455.

Your call, I can be convinced either way.

**Comment by pmorie** [comment]
I'm going to close this for now until the proposal that deals with it is merged and the refactor it's going to be on top of is merged.

**Pull request closed without merging**
