### PR TITLE
Ubuntu cluster: run flannel on master

### PR DESCRIPTION
**Pull request by deyuanix**
Running flannel on master allows me to use kubectl proxy; otherwise, master can't reach out to my pods.  Let me know if this is desired.

Please review by commit.  Another commit is all about shell clean up.

@WIZARD-CXY

### CODE REVIEW

**Comment by WIZARD-CXY** [comment]
Thanks for the shell clean up.I'll test your code in my lab and see if it breaks anything.

**Comment by mbforbes** [comment]
@brendandburns can you please help with triage & reviewer assigning?

**Comment by WIZARD-CXY** [comment]
＠ddysher, I tested the code in my lab. The flannel network is working. I didn't use `kubectl proxy` before,j ust want to ask can you  run `kubectl proxy` on the minion node which has a overlay flannel network?

**Comment by ddysher** [comment]
IIUC, `kubectl proxy` runs on host machine to allow proxying from the host machine to the cluster (to master).  I don't know if you can proxy though minion, and I didn't try running proxy on minion node neither.   Maybe others have more background.

**Comment by brendandburns** [comment]
LGTM.  kubectl proxy should be able to contact pods.  On GCE this "just works" so I think this is the right setup for flanneld based installs.

**Pull request merged**
