### PR TITLE
Problem about use google.golang.org/api/monitoring/v3

### PR DESCRIPTION
**Pull request by navist2020**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
On the official website of `monitoring/v3`.
https://pkg.go.dev/google.golang.org/api/monitoring/v3
`gcm.New` is deprecated. Official advice use `NewService` instead.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by hwdef** [comment]
/ok-to-test
Thanks for your contribution!

**Comment by navist2020** [comment]
I found this problem had been fixed. So i close.

**Pull request closed without merging**
