### PR TITLE
cleanup: remove deprecated azure blob disk feature

### LINKED ISSUE #92704: Potential license conflict
I ran an OSS license scan of a codebase that has this project as a dependency and came across an interesting hit.

This go-vhd dependency specified here:
https://github.com/kubernetes/legacy-cloud-providers/blob/1bd57a2af8f3a65a82398a87ce5a99f855e277f1/go.mod#L22
has a snippet of code from StackOverflow which is license under creative commons sharealike. Here's the code in question:
https://github.com/rubiojr/go-vhd/blob/0bfd3b39853cdde5762efda92289f14b0ac0491b/vhd/util.go#L59-L73

I'm not a license expert, so I don't know if there are any real issues/conflicts here or not, but wanted to share to see what you all think. 

Here's SO's license info for reference:
https://creativecommons.org/licenses/by-sa/4.0/

My understanding is that the potential issue would be with this clause:
> ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

which could potentially require go-vhd and projects that depend on it to use the Creative Commons license as well.

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
cleanup: remove deprecated azure blob disk feature in v1.19
Azure blob disk feature has been deprecated from 1.10, now it's time to remove this feature totally, we only support `managed` disk.
This would also solve the go-vhd lib license issue mentioned in #92704

**Which issue(s) this PR fixes**:

Fixes #92704

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
cleanup: remove deprecated azure blob disk feature
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
cleanup: remove deprecated azure blob disk feature
```

/kind bug
/assign @feiskyer
/priority important-soon
/sig cloud-provider
/area provider/azure

### CODE REVIEW

**Comment by andyzhangx** [comment]
/hold
hold a moment to confirm removal of blob disk support

**Comment by andyzhangx** [comment]
cc @gnufied @jsafrane we are going to remove Azure blob disk feature in v1.19, could you make sure in ARO is all using managed disk in higher k8s version, e.g. 1.18

**Comment by jsafrane** [comment]
Hold on, this is quite a breaking change. Reading https://kubernetes.io/docs/reference/using-api/deprecation-policy/:

* Enum values are "API elements"
* "API elements may only be removed by incrementing the version of the API group".

I see you don't remove the enum element from API, but you remove its implementation. A PV with `spec.azureDisk.kind: Dedicated` will quietly stop working.

> Azure blob disk feature has been deprecated from 1.10.

Can you please link the deprecation notice? I haven't found anything in 1.10 release notes nor Kubernetes documentation.

I think it requires more formal dicussion. Can you please bring it to the next sig-storage meeting?

**Comment by nikhita** [comment]
We wanted to get this in 1.19 to remove dependency on `github.com/rubiojr/go-vhd` due to a potential license conflict (https://github.com/kubernetes/kubernetes/issues/92704).

Since this might not be feasible for 1.19, I've created an issue upstream https://github.com/rubiojr/go-vhd/issues/3 to check if we can solve it there.

**Comment by andyzhangx** [comment]
close this PR, there is another PR to address this license issue: https://github.com/kubernetes/kubernetes/pull/92824
thanks for the comments.

**Pull request closed without merging**
