### PR TITLE
update the kubelet authorizer to allow system:masters access without a SAR

### PR DESCRIPTION
**Pull request by deads2k**
`system:masters` group is defined in kube-apiserver to always have access.  Because of this, we know that every delegated authorization check for this group on every kubernetes cluster, will always return allowed.  We can add the system:masters authorizer first.

/kind cleanup
/priority important-soon
@kubernetes/sig-auth-bugs @kubernetes/sig-node-pr-reviews 

```release-note
NONE
```

### CODE REVIEW

**Comment by enj** [comment]
Can we migrate the Kubelet to `NewDelegatingAuthorizationOptions` (just the struct, not the flag set)?  The Kubelet is a bit of a unicorn in regards to its authn and authz stack.  It would be nice to normalize it to what the API server uses.

**Comment by deads2k** [comment]
> Can we migrate the Kubelet to `NewDelegatingAuthorizationOptions` (just the struct, not the flag set)? The Kubelet is a bit of a unicorn in regards to its authn and authz stack. It would be nice to normalize it to what the API server uses.

I looked at that first, but doing so requires disconnecting the way they build the client.  It's a significantly more invasive change.

**Comment by enj** [comment]
> I looked at that first, but doing so requires disconnecting the way they build the client. It's a significantly more invasive change.

Right, but it is also the correct change.  If the Kubelet was already using the API server code, #98325 would have already fixed its defaulting to include `system:masters`.

**Pull request closed without merging**
