### PR TITLE
Automated cherry pick of #17689 to release-1.1

### PR DESCRIPTION
**Pull request by karlkfi**
Add DCOS to getting started guide list (docs): #17689

### CODE REVIEW

**Comment by karlkfi** [comment]
Once this is merged, I'll need to make another PR to update gh-pages using the process in these docs: #17983

**Comment by karlkfi** [comment]
e2e test failures (obviously not due to this docs change):

```
Summarizing 2 Failures:

[Fail] Services [It] should serve multiport endpoints from pods [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1048

[Fail] Services [It] should be able to up and down services 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:223

Ran 110 of 175 Specs in 770.185 seconds
FAIL! -- 108 Passed | 2 Failed | 2 Pending | 63 Skipped 
```

**Comment by bgrant0607** [comment]
LGTM

**Comment by karlkfi** [comment]
manually merging this docs cherry-pick to bypass blocked submit queue and unrelated e2e test failures.

**Pull request merged**
