### PR TITLE
add support for 3rd party object to kubectl annotate

### PR DESCRIPTION
**Pull request by adohe-zz**
## Pull Request Guidelines
1. Please read our [contributor guidelines](https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md).
2. See our [developer guide](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md).
3. Follow the instructions for [labeling and writing a release note for this PR](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/pull-requests.md#release-notes) in the block below.

``` release-note
* Use the release-note-* labels to set the release note state 
* Clear this block to use the PR title as the release note 
-OR-
* Enter your extended release note here
```

[Analytics]()

### CODE REVIEW

**Comment by AdoHe** [comment]
@brendandburns @janetkuo ptal.

**Comment by janetkuo** [comment]
@kubernetes/kubectl

**Comment by janetkuo** [comment]
Is annotating 3rd party object not working before? Suggest adding test(s).

**Comment by AdoHe** [comment]
@janetkuo test on HEAD, and just get this:
```
error: no kind "ThirdPartyResourceData" is registered for version "stable.example.com/v1"
```

**Comment by janetkuo** [comment]
Hmm it works fine on HEAD for me:
```console
# config file of a 3rd party resource
$ cat 3rd.yaml 
metadata:
  name: cron-tab.stable.example.com
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "A specification of a Pod to run on a cron style schedule"
versions:
- name: v1
- name: v2

# the annotated 3rd party resource
$ kubectl get thirdpartyresource cron-tab.stable.example.com -o yaml 
apiVersion: extensions/v1beta1
description: A specification of a Pod to run on a cron style schedule
kind: ThirdPartyResource
metadata:
  annotations:
    author: unknown
  creationTimestamp: 2016-05-03T22:45:40Z
  name: cron-tab.stable.example.com
  namespace: default
  resourceVersion: "64"
  selfLink: /apis/extensions/v1beta1/namespaces/default/thirdpartyresources/cron-tab.stable.example.com
  uid: c2f454d4-1180-11e6-8850-64510658e388
versions:
- name: v1
- name: v2
```

**Comment by janetkuo** [comment]
Just found that this PR dup with #24882

**Comment by AdoHe** [comment]
Just close this one as a duplication.

**Pull request closed without merging**
