### PR TITLE
Update admission OperationOptions match with Operation

### PR DESCRIPTION
**Pull request by kkkkun**
Signed-off-by: kkkkun <scuzk373x@gmail.com>

#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Update admission OperationOptions match with Operation

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by stlaz** [comment]
/lgtm
while the options appear to be generally disregarded by the admission, I agree that this moves the world to a state with just a little bit less entropy

**Comment by kkkkun** [comment]
lifecycle/stale

**Comment by stlaz** [comment]
> It's a simple change. Could you please merge this？

Sorry, I'm not allowed to approve PRs. I believe @enj might be able to help.

**Comment by kkkkun** [comment]
> > It's a simple change. Could you please merge this？
> 
> Sorry, I'm not allowed to approve PRs. I believe @enj might be able to help.

@enj  we should merge this，it's a minor changes.

**Pull request closed without merging**
