### PR TITLE
Update corefile-migration to v1.0.14 and update coredns to 1.8.6

### LINKED ISSUE #105189: upgrade coredns to 1.8.6 to fix a regression bug
FYI: @neolit123

Last week a regression was [reported](https://github.com/coredns/coredns/issues/4834) for 1.8.4 for the _rewrite_ plugin. There is a workaround. FYI AFAIK, AKS has [decided to defer rolling out 1.8.4](https://github.com/Azure/AKS/issues/2521#issuecomment-911901518), skipping over the version, since a fix will be in 1.8.5 (already merged).
Describing the regression as succinctly as I can:

> If using the _rewrite_ plugin, a rewrite rule that does not also rewrite the response (using the `answer` option) will cause clients to reject any response rewritten by the rule (due to question section mismatch). A work around is to append `answer auto` to affected rules. All `exact` name rewrites are not affected since they automatically perform a response rewrite.

FWIW, this has always been the case for _some_ clients (some clients are extra picky about question mismatch), but the regression caused it to affect _most_ clients (if not all).  My attempt to explain in more detail [here](https://github.com/coredns/coredns/issues/4834#issuecomment-908544954).

Also, regarding the workaround, `answer auto` is only valid in 1.8.4, so a user cannot use that option to adjust their corefile before upgrading to avoid potential downtime.  If that is desired, any affected rule should be expressed as a `regex` rule with a response rewrite, which would be valid in 1.84 and prior versions.

_Originally posted by @chrisohaver in https://github.com/kubernetes/kubernetes/issues/102466#issuecomment-915682855_

### PR DESCRIPTION
**Pull request by calvin0327**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

upgrade coredns version to 1.8.5.

#### Which issue(s) this PR fixes:

Fixes #105189

#### Special notes for your reviewer:

upgrade coredns to 1.8.5 to fix a regression bug.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
/hold
As there is a regression issue with `reload` plugin, we have to wait for next patch of coredns.

**Comment by pacoxu** [comment]
/assign @neolit123 
for kubeadm approval

**Comment by neolit123** [comment]
kind tests are green so this seems fine, not testing upgrades though in this CI.

thanks
/milestone v1.22
/priority important-soon

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
