### PR TITLE
Kubernetes UI graph component.

### PR DESCRIPTION
**Pull request by jackgr**
This PR adds the graph component developed with the dashboard component and chrome (see PR #7056) to the Kubernetes UI. It is unchanged from the demo shown at the Galvanize event on 2/25/2015, but needs minor updates to reflect changes made to the UI since the dashboard and chrome were submitted. 

The GraphTab uses a container called cluster-insight to retrieve information from the running cluster. See https://github.com/google/cluster-insight and https://registry.hub.docker.com/u/kubernetes/cluster-insight/. 

If cluster-insight is not deployed, the Graph Tab still works, but shows no data. The user can select canned data to see how it works. When it is deployed in a cluster, the Graph Tab will find it and display its data.

### CODE REVIEW

**Comment by jackgr** [comment]
Thanks to contributors @duftler, @unwornmoon, @jellzilla, @balavas, @EranGabber, @preillyme, @bcbroussard, @kenmoore, @kmerker.

cc @lavalamp

**Comment by lavalamp** [comment]
In the future, we need to develop things like this in the codebase a piece at a time...

**Comment by jackgr** [comment]
@lavalamp Understood. Like the chrome and dashboard, the initial code base was built in 3 weeks for Galvanize. Sorry.

**Comment by jackgr** [comment]
The README.md needs to be completed, so that users understand how to find and deploy the [cluster-insight](https://registry.hub.docker.com/u/kubernetes/cluster-insight/) container that generates the graph data.

**Comment by preillyme** [comment]
@jackgr I've created the following PR to your fork: https://github.com/jackgr/kubernetes/pull/1 to render the graph tab.
pr_8716

**Comment by preillyme** [comment]
@jackgr where is https://github.com/google/cluster-insight going to live for this PR?

**Comment by jackgr** [comment]
@preillyme It's available [here](https://registry.hub.docker.com/u/kubernetes/cluster-insight/) on Docker Hub, per the updated README.md. Per the comment above, plan is to package as a pod like addons, but that's just a convenience. It's usable in its current form.

**Comment by preillyme** [comment]
@jackgr: I was talking about the correct url for the configuration something like: ```/api/v1beta3/proxy/namespaces/default/services/cluster-insight```

**Comment by preillyme** [comment]
@googlebot: these commits are okay to be contributed to Google.

**Comment by jackgr** [comment]
@preillyme Yes, developers can drop cluster-insight onto the master, as described in its installation notes, but the static UI needs it to be served from the cluster, so packaging it up as a service like the other addons makes sense.

**Comment by jackgr** [comment]
Forgot to mention that cluster-insight is v1beta1. Needs to be updated to v1beta3.

**Comment by preillyme** [comment]
@jackgr: I've opened https://github.com/google/cluster-insight/issues/61 I've been testing on a ```./hack/local-up-cluster.sh``` host. I'll try on a real cluster next.

**Comment by lavalamp** [comment]
Cluster insight thingy seems to require opening up docker's port; this is a giant security hole and so we are very deliberately using the unix socket to talk to docker. We won't be able to package it on a cluster like this, at least not by default.

**Comment by preillyme** [comment]
@lavalamp what if ```cluster-insight``` was modified and talked to the unix socket and acted like a proxy for the other nodes running ```cluster-insight```?

**Comment by abonas** [comment]
> @preillyme Yes, developers can drop cluster-insight onto the master, as described in its installation notes, but the static UI needs it to be served from the cluster, so packaging it up as a service like the other addons makes sense.

@jackgr If the graph component is going to be merged and enabled by default as part of k8s, why the cluster-insight shouldn't be included and enabled by default in k8s setup as well? 
Not including it means that the UI will not work out of the box, and every user will have to deploy something extra.

**Comment by preillyme** [comment]
@abonas I think it's more an issue around security as @lavalamp pointed out. We need to fix https://github.com/google/cluster-insight/issues/62 to address this issue.

**Comment by jackgr** [comment]
Note that the UI can be tested apart from cluster-insight, using the canned data, selectable from the UI or programatically.

**Comment by jackgr** [comment]
Rebased this PR onto #8776 due to the number of dependencies. Known issue: Error: [$injector:unpr] Unknown provider: iProvider <- i <- pollK8sDataService <- pollK8sDataService.

**Comment by lavalamp** [comment]
> @lavalamp what if cluster-insight was modified and talked to the unix socket and acted like a proxy for the other nodes running cluster-insight?

Then you would have to run it on every node, which is also not ideal.

**Comment by saad-ali** [comment]
Thank you very much for the pull request - we sincerely appreciate the work that goes into sending us a change.

We are currently in a feature-freeze and general code slush as we work toward our 1.0 release.  Our initial triage indicates that this is a non-critical change at this time, so we'd like to leave it open and revisit it after 1.0.  We expect the freeze to wrap up in early to mid July.

If you feel that this triage is incorrect, please respond and let us know why.  We're currently accepting changes that meet any of the following criteria:
1. Changes [directly related to v1.0 issues](https://github.com/GoogleCloudPlatform/kubernetes/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.0)
2. Changes [addressing P0 bugs](https://github.com/GoogleCloudPlatform/kubernetes/issues?q=is%3Aopen+is%3Aissue+label%3Apriority%2FP0)
3. Changes to supported platforms to bring them up to par with the primary development platforms
4. Docs, user experience, and test related fixes

**Comment by jackgr** [comment]
@saad-ali This PR is for work that was requested by the Kubernetes leads in February, it depended on #7056, which took a while to be merged, and has follow on work in #7122, and was therefore delayed. It would not be good if this PR didn't make the release. @lavalamp has been tracking this work from the outset, so please check with him regarding its status. Thanks.

**Comment by saad-ali** [comment]
Thanks for the context Jack. Changing to 1.0 milestone.

**Comment by jackgr** [comment]
Thanks, @saad-ali.

**Comment by bgrant0607** [comment]
We are removing v1beta1 and v1beta2 in the next day or two and absolutely can't introduce any new dependencies on them.

**Comment by lavalamp** [comment]
I'm sorry, I don't have cycles to review this one.

**Comment by jackgr** [comment]
@bgrant0607 This PR has no dependencies on v1beta1 or v1beta2.

**Comment by stefwalter** [comment]
Agree with @abonas ... Use of cluster-insight makes this hard to reuse and deploy.

Building a graph like this directly against kubernetes data isn't hard. This was done in a few hours:

https://github.com/cockpit-project/cockpit/pull/2362

**Comment by jimmidyson** [comment]
Agree too, although as the cluster gets larger having a server side cache of the graph would be beneficial rather than client side building which I guess you're doing in that example @stefwalter?

Feels as though the relationships would perhaps be better served building into the API server for querying?

**Comment by stefwalter** [comment]
> Agree too, although as the cluster gets larger having a server side cache of the graph would be beneficial rather than client side building which I guess you're doing in that example @stefwalter?

That was my first reaction as well. However upon thinking about it further:

 1. If you have so many items that it's causing performance problems, you won't be able to build a decent graph out of them anyway. It would be a usability nightmare, not to mention the SVG DOM performance. Restricting items a priori (eg: to a single Kubernetes namespace) is the right way to handle this.
 2. Lastly Kubernetes already has a server side cache of certain relationships. The Endpoints items are a good example of this.

That said, I am using probabalistic hash indexes (similar properties to bloom filter) in Cockpit when processing Kubernetes data. This speeds building relationships.

**Comment by jimmidyson** [comment]
@stefwalter Very good points. In my head I see a graph that is zoomable so e.g. over a certain threshold not every pod is displayed, but rather a grouping, perhaps by service, which can be zoomed in further. Absolutely agree on namespace filtering - perhaps that could be the highest level of the graph?

**Comment by jackgr** [comment]
@jimmidyson It's already easy to filter out objects by type (e.g., show only the services, not the pods, containers, images, processes, etc.). It has been a goal from the outset to incrementally add features to the graph tab after initial release to deal with scale, including filter on search, filter on selection, filter on not selection, etc.

One feature that has been much requested is progressive disclosure, where the user finds an object using search (e.g., a minion), and it displays with its dependencies collapsed. From there, they can expand one level at a time, selecting only the objects they want to see in more detail. Selection already supports this behavior, so it will fall out easily when search is added.

**Comment by jackgr** [comment]
Added the files generated by the build from PR #8855, since Travis doesn't build the UI, and the Karma tests fail without the generated build artifacts. Squashed commits.

**Comment by jackgr** [comment]
Here's an update on this PR...

The [cluster-insight](https://github.com/google/cluster-insight) data collector is now just an ordinary Kubernetes service. It no longer requires opening firewall ports on the minions, and installs by just submitting the YAML files for two RCs and a service. The README is updated to describe the new behavior.

Removing the WIP, since now that this blocker has been addressed, there are no known issues. It's ready to merge.

**Comment by bgrant0607** [comment]
add to whitelist

**Comment by bgrant0607** [comment]
Still has the issue that the graph tab will be nonfunctional for default cluster setups.

**Comment by bgrant0607** [comment]
This PR is enormous: 105 changed files  with 174,475 additions and 3,690 deletions. Moreover, the whole GUI is enormous, requires a special build process and tools, and is in Javascript, which we can't adequately review.

As previously discussed IRL, the only viable path forward is to break the GUI back out into its own project, with its own source repo, continuous testing, and releases, and run it as a service on Kubernetes. The v1 API should be stable enough to make that feasible.

With respect to cluster-insight specifically, AIUI, it requires "root" in the cluster, since it directly accesses Docker. I haven't looked at it, I also doubt it would work for nodes running Rocket rather than Docker. We should look at the overlap with cadvisor and heapster so that we don't need to solve similar problems multiple times. 

Additionally, at some point, we'll need to figure out how to make whole-system "monitoring" components such as this play nicely with namespace-based security policies (see, e.g., #7893).

cc @kmerker

**Comment by preillyme** [comment]
I agree 100% with @bgrant0607 the direction that https://github.com/GoogleCloudPlatform/kubernetes/pull/10077 takes I think ultimately is the correct approach especially that the v1 API is now stable enough.

**Comment by lavalamp** [comment]
cluster-insight running on every node is very unfortunate.

From glancing at the code it doesn't appear to actually proxy docker, which would be a security problem. But I'm not sure even about serving the read-only data. Needing root is another problem. Interoperability (with e.g. Rkt) is another. Do you really need that level of detail for the entire cluster? Does kubelet not report enough in the pod status?

**Comment by bgrant0607** [comment]
Yes, we should improve PodStatus and/or cadvisor, if necessary.

Also note that @preillyme created https://github.com/kubernetes-ui/kube-ui

**Comment by preillyme** [comment]
@bgrant0607 once we get https://github.com/GoogleCloudPlatform/kubernetes/pull/10077 working with the container built from https://github.com/kubernetes-ui/kube-ui and published at: ```gcr.io/kube-ui/kube-ui``` we can remove the ```www``` directory completely and close this PR. @jackgr can then submit the PR to the UI repo directly.

**Comment by jackgr** [comment]
We will move this code to https://github.com/kubernetes-ui/kube-ui, per the comment from @preillyme.

However, there are several issues raised in this thread that should be addressed for the record:

* 79 of the 105 files are images, .gitkeep files or checked-in build output, which need code review.
* 26 of the 105 files are source. These are the only files that need code review.
* The build process is based on a boilerplate build file that reflects standard industry practice.
* The cluster-insight container is a vanilla python application. It needs to be a member of the docker group to access the daemon, but does not need to run as root, and has no special requirements.
* The container running on every node adds negligible CPU overhead, since the master caches the fetched data. Its memory footprint is 1/3 the size of fluentd.
* When Rocket interoperability is needed, we will add it.

The most significant factor in the difficulty surrounding this UI may be the point raised earlier, noting that it's written in Javascript, which the Kubernetes team can't adequately review. Since Javascript is currently the predominant language for client side development, and seems unlikely to be replaced by Go any time soon, this is an issue that the Kubernetes team will probably need to come to terms with.

**Comment by stefwalter** [comment]
Just for completeness, I can't help but comment:

> The cluster-insight container is a vanilla python application. It needs to be a member of the docker group to access the daemon, but does not need to run as root, and has no special requirements.

The docker group (where available) is root equivalent. It is trivial to escalate to root via the docker daemon, and bypass auth, audit, and logging. Docker upstream states this themselves in their documentation. For this reason, most operating systems do not (or no longer) create the docker group by default.

**Comment by jackgr** [comment]
It's worth noting that all of the current add ons and examples run as root. The plan is for that to change, but it hasn't yet, and it wasn't a blocker for getting the functionality integrated. Likewise, cluster-insight can be made to interact with Docker and/or Rocket through APIs given appropriate credentials, instead of using the Unix socket, but until we get to the point of locking everything down, it probably shouldn't be a blocker for getting the functionality integrated.

**Pull request closed without merging**
