### PR TITLE
Changed monitoring level in test config for GCE.

### PR DESCRIPTION
**Pull request by piosz**
To make monitoring level in tests consistent with the default one.

### CODE REVIEW

**Comment by piosz** [comment]
@vishh @saad-ali

**Comment by piosz** [comment]
@k8s-bot: retest this please

**Comment by piosz** [comment]
@k8s-bot test this please

**Comment by piosz** [comment]
@k8s-bot test this please

**Comment by piosz** [comment]
Monitoring test fails here (due to timeout while querying influxdb) and passes for me locally. Any ideas?

**Comment by a-robinson** [comment]
Reassigning since I know nothing about the test

**Comment by vishh** [comment]
@piosz: We already have way too many configs. Adding another config which dumps to both influxdb and GCM is possible. But I would rather have the tests enable the heapster sinks they use dynamically. Here is an [example](https://github.com/GoogleCloudPlatform/heapster/blob/master/integration/heapster_api_test.go#L329). WDYT?

**Comment by piosz** [comment]
This config already exists and is default option while creating cluster. I wanted to make those two config files (config-default.sh and config-test.sh) consistent.

**Pull request closed without merging**
