### PR TITLE
Update cni-plugins to v1.5.1

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Update to the latest release.
#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
cc @kubernetes/release-engineering 
#### Does this PR introduce a user-facing change?

```release-note
Updated cni-plugins to [v1.5.1](https://github.com/containernetworking/plugins/releases/tag/v1.5.1).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
* Should we cherry-pick to branches that use 1.5.0?
* Should we create a deb/rpm package for 1.5.1 for branches that use 1.5.0?

/lgtm
/approve

**Comment by saschagrunert** [comment]
> * Should we cherry-pick to branches that use 1.5.0?

Yeah, `release-1.31`

> Should we create a deb/rpm package for 1.5.1 for branches that use 1.5.0?

Yes we should update https://build.opensuse.org/package/show/isv:kubernetes:core:shared:build/kubernetes-cni

**Comment by xmudrii** [comment]
> Yes we should update https://build.opensuse.org/package/show/isv:kubernetes:core:shared:build/kubernetes-cni

I'll take care of that once the cherry-pick is merged.

**Comment by saschagrunert** [comment]
`pull-kubernetes-local-e2e` was never green: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-local-e2e

/skip

**Comment by xmudrii** [comment]
@dims Can you help with this PR? 😄

**Comment by saschagrunert** [comment]
Cherry-pick to release-1.31: https://github.com/kubernetes/kubernetes/pull/126988

**Comment by xmudrii** [comment]
The kubernetes-cni v1.5.1 package has been published on pkgs.k8s.io

**Pull request merged**
