### PR TITLE
Automated cherry pick of #84917: fix race condition when attach/delete disk

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #84917 on release-1.14.

#84917: fix race condition when attach/delete disk

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm
/retest

**Comment by justaugustus** [comment]
For CP approval: @kubernetes/patch-release-team

**Review by dougm — COMMENTED** [review]
/lgtm

**Pull request merged**
