### PR TITLE
disable cloud-provider code from kube-controller-manager

### PR DESCRIPTION
**Pull request by aojea**
Since 1.31 the core component cloud provider logic should not exist,
this disables the existing code in the kube-controller-manager that still
expects to work with the cloud-provider logic to avoid having time bombs
in the code base that can break the component.

The code can not be completely removed because this will impact existing
users that may be using some of the flags breaking their deployments, so
this just removes the code that is no longer to be used becuase it
depends on options that no longer are exposed to users.

It also adds validation on the configuration/flag level to ensure that
the --cloud-provider flag can only be set to external or empty.

/kind cleanup
```release-note
Removed legacy cloud provider integration code and the "service-lb-controller", "cloud-node-lifecycle-controller" and the "node-route-controller" from kube-controller-manager. You can now either set the `--cloud-provider` command line argument to "external", or to the empty string. All other values are invalid.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

<!--
This section can be blank if this pull request does not require a release note.

When adding links which point to resources within git repositories, like
KEPs or supporting documentation, please reference a specific commit and avoid
linking directly to the master branch. This ensures that links reference a
specific point in time, rather 
#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/2395-removing-in-tree-cloud-providers/
```

Follow up on https://github.com/kubernetes/kubernetes/issues/128121
/hold
We still need to merge https://github.com/kubernetes/kubernetes/pull/128182 first so we can backport it to 1.31

/sig cloud-provider
/sig apps

### CODE REVIEW

**Comment by aojea** [comment]
/assign @liggitt @dims @elmiko 
/cc @carlory 
> We still need to merge https://github.com/kubernetes/kubernetes/pull/128182 first so we can backport it to 1.31

**Comment by carlory** [comment]
@aojea Even if https://github.com/kubernetes/kubernetes/pull/128179 is merged, we still need this PR https://github.com/kubernetes/kubernetes/pull/128197.  kubernetes/​cloud-provider-xxx will panic, it uses `k8s.io/cloud-provider` to build the cloud controller manager.  https://grep.app/search?q=app.NewCloudControllerManagerCommand

**Comment by sftim** [comment]
Changelog suggestion
```diff
-kube-controller-manager  only allows to set the cloud-provider flag to external or empty.
+Removed legacy cloud provider integration code from kube-controller-manager. You can now either set the `--cloud-provider` command line argument to "external", or to the empty string. All other values are invalid.
```

**Comment by aojea** [comment]
gce jobs need to be modified

```
W1019 07:44:01.360761      10 requestheader_controller.go:193] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLEBINDING_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
unable to load configmap based request-header-client-ca-file: configmaps "extension-apiserver-authentication" is forbidden: User "system:cloud-controller-manager" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
Error: unable to load configmap based request-header-client-ca-file: configmaps "extension-apiserver-authentication" is forbidden: User "system:cloud-controller-manager" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
```

**Comment by aojea** [comment]
/hold cancel

fix for backporting merge, we can remove the bandaid of the cloud provider in the kube-controller-manager and avoid more possible problems because of that

**Comment by aojea** [comment]
ok, this presents interesting challenges:
- we tied the ipam controller to the kubeCloudShared configuration, so we need to keep importing all the cloud things
- the configuration API considers the service controller options, removing it is a breaking change, and things panic as we can see in the unit test
- deployments that set the flags are now a noop, removing the flags will break those users

I think the safest approach is we just validate  `cloud-provider` is external or empty and the `ipam-controller` can only be type  range-allocator, and then leave the other as a noop as they are today ... seems too late to do more and too risky for no much benefit

**Comment by carlory** [comment]
Does this PR belong to a part of the [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cloud-provider/2395-removing-in-tree-cloud-providers)?

```
## Graduation Criteria

### GA
Two releases have passed at beta status without incident or regression.

### Deprecation
Removal of all in-tree code no earlier than one release after GA release.
Removal of option to set specific cloud providers through --cloud-provider, these options should be removed at in-tree providers are removed.
```

**Comment by carlory** [comment]
And should all flags related to cloud controllers be removed or marked as deprecated?

**Comment by elmiko** [comment]
@aojea thanks for posting this! was on pto for a few days, will review this week.

@carlory we still allow, and require in some cases, the `--cloud-provider=external` flag, i don't think we are quite at the place where we want to deprecate the flags yet. but we did find some old code that could produce erroneous behavior, so we are cleaning up the extra bits.

**Comment by aojea** [comment]
@elmiko I updated the PR with a more safest approach, it keeps the user facing functionality, flags and options to avoid breaking users, but just disables the cloud provider functionality and removes the code that are not longer being able to be executed PTAL

**Comment by elmiko** [comment]
awesome, thank you so much @aojea !

**Comment by dims** [comment]
@aojea in general it looks good. Asking @kmala to take a look as well.

**Comment by elmiko** [comment]
lgtm, would like to get another review

**Comment by kmala** [comment]
the changes look good

**Comment by dims** [comment]
/approve
/lgtm

thanks @kmala

**Pull request merged**
