### PR TITLE
updates es-image to elasticsearch 6.3.2

### PR DESCRIPTION
**Pull request by monotek**
**What this PR does / why we need it**:
* updates es-image to elasticsearch 6.3.2

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
updates es-image to elasticsearch 6.3.2
```

### CODE REVIEW

**Comment by aleks-mariusz** [comment]
is this a typo?

in cluster/addons/fluentd-elasticsearch/es-image/Dockerfile you have 6.3.2

but in  cluster/addons/fluentd-elasticsearch/es-image/Makefile you only have 6.3.0

**Comment by like-inspur** [comment]
root@ubuntu:~/kubernetes/cluster/addons/fluentd-elasticsearch/es-image# docker build -t staging-k8s.gcr.io/elasticsearch:v6.3.2 .
Sending build context to Docker daemon  16.38kB
Step 1/8 : FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.2
 ---> b74c54dcb4d7
Step 2/8 : VOLUME /data
 ---> Using cache
 ---> b0b5eab4c529
Step 3/8 : EXPOSE 9200 9300
 ---> Using cache
 ---> 48dc74f45102
Step 4/8 : COPY elasticsearch_logging_discovery run.sh bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder514757004/elasticsearch_logging_discovery: no such file or directory

**Pull request merged**
