### PR TITLE
Verify that openssl is installed in local-up-cluster.sh

### PR DESCRIPTION
**Pull request by ghost**
Verify that openssl is installed in local-up-cluster.sh

### CODE REVIEW

**Comment by smarterclayton** [comment]
What's the failure mode?  Was this something unusual in the environment (testing hack/local-up-cluster.sh inside of very limited machines)?

I just ask because I'm trying to think of the last time I was on a box without openssl :)

**Comment by swagiaal** [comment]
I ran into this with a fedora 22 cloud image and it took me a while to figure it out from the error message in the apiserver's log
```
 Invalid Authentication Config: open /tmp/kube-serviceaccount.key: no such file or directory
```

There is a comment in the docs about it (https://github.com/kubernetes/kubernetes/blob/master/docs/devel/running-locally.md#openssl) but i thought this check would save someone else the time.

**Comment by smarterclayton** [comment]
Ok

**Comment by swagiaal** [comment]
@k8s-bot test this. issue #23822

**Comment by swagiaal** [comment]
@smarterclayton test are all green now. PTAL

**Comment by bprashanth** [comment]
@k8s-bot test this github issue: #25375

**Comment by ixdy** [comment]
@k8s-bot test this please, issue #IGNORE

**Comment by ixdy** [comment]
@k8s-bot test this please, issue #IGNORE

**Comment by ixdy** [comment]
@k8s-bot test this please, issue #IGNORE

**Comment by ixdy** [comment]
(sorry for the spam, trying to fix Jenkins)

@k8s-bot test this please, issue #IGNORE

**Comment by ixdy** [comment]
@k8s-bot test this please, issue #IGNORE

**Pull request merged**
