### PR TITLE
Add wait to discovery integration test to fix flakiness

### PR DESCRIPTION
**Pull request by nilebox**
**What this PR does / why we need it**:
Reduce the flakiness of the discovery test that was introduced in #66932  (see cherry-pick PR #67154 for report on flaky failure and suggestions).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
```
verify gofmt 16s

make verify WHAT=gofmt

diff -u ./test/integration/examples/apiserver_test.go.orig ./test/integration/examples/apiserver_test.go
--- ./test/integration/examples/apiserver_test.go.orig	2018-08-13 12:56:27.511396615 +0000
+++ ./test/integration/examples/apiserver_test.go	2018-08-13 12:56:27.511396615 +0000
@@ -335,7 +335,7 @@
 	}
 
 	// wait for the unavailable API service to be processed with updated status
-	err = wait.Poll(100 * time.Millisecond, 5 * time.Second, func() (done bool, err error) {
+	err = wait.Poll(100*time.Millisecond, 5*time.Second, func() (done bool, err error) {
```

**Comment by nilebox** [comment]
@liggitt could you please re-add `/lgtm`, the formatting has been fixed

**Comment by spiffxp** [comment]
/lgtm
per the above

**Comment by nilebox** [comment]
Some unrelated flakiness:
```
daemonset_test.go:880: Failed to update DaemonSet: Operation cannot be fulfilled on daemonsets.apps "foo": the object has been modified; please apply your changes to the latest version and try again
```

**Pull request merged**
