### PR TITLE
fixes #28835 Changed volume path in Dockerfile of cassandra example

### LINKED ISSUE #28835: example/cassandra: Volume statement in Dockerfile hides all data
**Situation:**
I deployed a cassandra cluster based on the [provided example](https://github.com/kubernetes/kubernetes/tree/fedc5136586dd1a3698f6ad0c734a4065fa726eb/examples/storage/cassandra), used the DaemonSet and replaced the emptyDir with hostPath.

**Problem:**
After deleting a pod all local data seems to be gone and the new cassandra pod loads its data from the other replicas.
When all replicas are deleted at the same time, all data from this replicaset seems to be gone. The data should still be on the hostPath, but the cassandra pod does not see it.

**Cause:**
There is a volume defined in the [Dockerfile](https://github.com/kubernetes/kubernetes/blob/fedc5136586dd1a3698f6ad0c734a4065fa726eb/examples/storage/cassandra/image/Dockerfile#L57) to the directory `/cassandra_data/data`
The [daemonset](https://github.com/kubernetes/kubernetes/blob/fedc5136586dd1a3698f6ad0c734a4065fa726eb/examples/storage/cassandra/cassandra-daemonset.yaml#L50) mounts the hostPath to `/cassandra_data`
In the running container we now have a volume at `/cassandra_data` and inside of it in the `data` folder we have another volume, **hiding the data directory** of our hostPath volume:

```
$ kubectl exec -ti cassandra-test-0yr4x bash
$ mount
[...]
/dev/vda1 on /cassandra_data type ext4 (rw,relatime,data=ordered)
/dev/vda1 on /cassandra_data/data type ext4 (rw,relatime,data=ordered)
[...]
```

### PR DESCRIPTION
**Pull request by ghost**
Changed volume path in Dockerfile from /cassandra_data/data to /cassandra_data because it creates a volume inside the volume provided by the example effectively hiding all existing data when the pod is recreated.
fixes #28835

[Analytics]()

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/28837)

### CODE REVIEW

**Comment by dims** [comment]
@maklemenz Want to bump the version too?
https://github.com/kubernetes/kubernetes/blob/master/examples/storage/cassandra/image/Makefile#L17

**Comment by bgrant0607** [comment]
ok to test

**Comment by maklemenz** [comment]
@dims I bumped the version to v10
@bgrant0607 do you know what caused the tests to fail?

**Comment by chrislovecnm** [comment]
@maklemenz documentation is not updated, version docker numbers.  Did you run the e2e tests locally?

Thanks for the work!

**Comment by chrislovecnm** [comment]
@maklemenz you also have to change the cassandra.yaml to get this to work.... https://github.com/kubernetes/kubernetes/blob/master/examples/storage/cassandra/image/cassandra.yaml#L99  please let me know how testing goes.

**Comment by maklemenz** [comment]
@chrislovecnm No, the path is correct. The problem was that this path was hidden by the volume docker provided.

I cannot run the e2e tests because of compiler errors

	$ make test_e2e_node
	hack/build-go.sh vendor/github.com/onsi/ginkgo/ginkgo	
	Go version: go version go1.6.2 linux/amd64
	+++ [0719 15:17:23] Building the toolchain targets:
		k8s.io/kubernetes/hack/cmd/teststale
	+++ [0719 15:17:23] Building go targets for linux/amd64:
		vendor/github.com/onsi/ginkgo/ginkgo
	+++ [0719 15:17:24] Placing binaries
	hack/e2e-node-test.sh
	Failed to compile e2e_node:

	# k8s.io/kubernetes/pkg/api/v1
	test/e2e_node/home/mk/gopath/src/k8s.io/kubernetes/pkg/api/v1/conversion.go:248: undefined: autoConvert_api_PodStatusResult_To_v1_PodStatusResult
	test/e2e_node/home/mk/gopath/src/k8s.io/kubernetes/pkg/api/v1/conversion.go:289: undefined: autoConvert_v1_PodStatusResult_To_api_PodStatusResult
	test/e2e_node/home/mk/gopath/src/k8s.io/kubernetes/pkg/api/v1/conversion.go:304: undefined: autoConvert_api_PodTemplateSpec_To_v1_PodTemplateSpec
	test/e2e_node/home/mk/gopath/src/k8s.io/kubernetes/pkg/api/v1/conversion.go:346: undefined: autoConvert_v1_PodTemplateSpec_To_api_PodTemplateSpec
	test/e2e_node/home/mk/gopath/src/k8s.io/kubernetes/pkg/api/v1/conversion.go:363: undefined: autoConvert_api_PodSpec_To_v1_PodSpec
	test/e2e_node/home/mk/gopath/src/k8s.io/kubernetes/pkg/api/v1/conversion.go:382: undefined: autoConvert_v1_PodSpec_To_api_PodSpec
	test/e2e_node/home/mk/gopath/src/k8s.io/kubernetes/pkg/api/v1/conversion.go:405: undefined: autoConvert_api_Pod_To_v1_Pod
	test/e2e_node/home/mk/gopath/src/k8s.io/kubernetes/pkg/api/v1/conversion.go:477: undefined: autoConvert_v1_Pod_To_api_Pod
	test/e2e_node/home/mk/gopath/src/k8s.io/kubernetes/pkg/api/v1/conversion.go:493: undefined: autoConvert_api_ServiceSpec_To_v1_ServiceSpec
	test/e2e_node/home/mk/gopath/src/k8s.io/kubernetes/pkg/api/v1/conversion.go:502: undefined: autoConvert_v1_Secret_To_api_Secret
	test/e2e_node/home/mk/gopath/src/k8s.io/kubernetes/pkg/api/v1/conversion.go:502: too many errors

	Ginkgo ran 1 suite in 8.285110546s
	Test Suite Failed
	!!! Error in hack/e2e-node-test.sh:131
	  '"${ginkgo}" --focus=$focus --skip=$skip "${KUBE_ROOT}/test/e2e_node/" --report-dir=${report} -- --alsologtostderr --v 2 --node-name $(hostname) --disable-kubenet=true --build-services=true --start-services=true --stop-services=true' exited with status 1
	Call stack:
	  1: hack/e2e-node-test.sh:131 main(...)
	Exiting with status 1
	Makefile:123: die Regel für Ziel „test_e2e_node“ scheiterte
	make: *** [test_e2e_node] Fehler 1

I don't see the cause in my changes. Changes to fix those compiler errors are not part on this pull request.

**Comment by chrislovecnm** [comment]
This is also fixed via https://github.com/kubernetes/kubernetes/pull/30577 @smarterclayton  / @bprashanth which one do you guys want?

**Comment by chrislovecnm** [comment]
@maklemenz PR https://github.com/kubernetes/kubernetes/pull/30577 in is

**Pull request closed without merging**
