### PR TITLE
Adding patch and cleaning up namespace code

### PR DESCRIPTION
**Pull request by krousey**
cc @kubernetes/sig-api-machinery

### CODE REVIEW

**Comment by lavalamp** [comment]
looks good, but maybe a test?

**Comment by krousey** [comment]
@lavalamp Added the test.

**Comment by lavalamp** [comment]
LGTM, since I already looked.

**Comment by krousey** [comment]
Trivial rebase. Adding LGTM back.

**Comment by krousey** [comment]
Not sure what happened on that failure. The longs don't seem to say which test case failed.

@k8s-bot e2e test this issue: #IGNORE

**Comment by krousey** [comment]
now for some reason the unit test results are missing

@k8s-bot unit test this issue: #IGNORE

**Comment by krousey** [comment]
@k8s-bot unit test this issue: #25645

**Comment by ixdy** [comment]
@k8s-bot test this please, issue #IGNORE

**Pull request merged**
