### PR TITLE
Simplify QueueSet interface by eliminating QueueSetCompleter.

### PR DESCRIPTION
**Pull request by wojtek-t**
```release-note
NONE
```

/kind cleanup
/priority important-longterm
/sig api-machinery

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@MikeSpreitzer

**Review by MikeSpreitzer — COMMENTED** [review]
We (@yue9944882 , @lavalamp , @deads2k ) did explicitly consider this alternative when we first created this abstraction.  We did not favor this approach because it creates an unnecessary opportunity for the client to make a mistake (not call the validation check as required).

**Comment by wojtek-t** [comment]
> We (@yue9944882 , @lavalamp , @deads2k ) did explicitly consider this alternative when we first created this abstraction. We did not favor this approach because it creates an unnecessary opportunity for the client to make a mistake (not call the validation check as required).

Without having full history I think it might have been a good decision back then. But now, when we already see how exactly it is used (how limited and isolated the usage of it is) and the fact that I don't think it should be used anywhere else, the pattern from this PR in my personal opinion is much easier to follow and understand.
I remember it took me quite some time to understand what exactly it does and why we need it back then.

@MikeSpreitzer @lavalamp @deads2k - thoughts?

/hold

**Comment by deads2k** [comment]
I prefer to have avoid having failures (even unexpected ones) that cannot be properly reported or handled.  The completer to get to a non-erroring retrieval is a pattern we used in the k8s.io/apiserver packages to ensure that calls that needed to happen in order were forced to happen in order using the type system.

Changing the existing code from "must call A to produce Y in order to call B" to a model where, "must call A before B" without an enforcement mechanism and where A must be perfectly validate for B, leaves a possibility of having to panic from code that cannot return an error.  Then, inside of this shared binary, we have to decide whether or not to exit on panic.  Often it is better to work as best we can, but if that choice is made, we won't have an obvious, "this broke" signal.

For these reasons, I prefer the existing code.  However, if @MikeSpreitzer and @tkashem both agree that the change is a net good even in the error cases they will support, I recognize that I have not personally debugged this code in quite some time.  If they don't agree that it is a clear win, I suggest keeping the existing code.

**Comment by MikeSpreitzer** [comment]
I do not think the proposed change is a clear win.  I agree that the current code is bit roundabout, but I agree with @deads2k 's lack of enthusiasm for coding for possible errors.

**Comment by wojtek-t** [comment]
OK - I don't fully agree, but it's very subjective.
So given I'm in minority I'm not going to push for it - closing.

**Pull request closed without merging**
