### PR TITLE
Fix TestServiceAlloc flakes

### PR DESCRIPTION
**Pull request by wojtek-t**
Cherrypick #37487 to 1.4 branch.

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37672)

**Comment by liggitt** [comment]
LGTM, looks like a bogus lint error in the 1.4 branch

**Comment by jessfraz** [comment]
the lint error is being tracked here https://github.com/kubernetes/kubernetes/issues/37254 im going to fix today

**Comment by jessfraz** [comment]
@k8s-bot verify test this

**Comment by jessfraz** [comment]
manually merging since all green and the submit queue is blocked

**Pull request merged**
