### PR TITLE
Refactor: use existing function to  simplify check for IPv6 in kubelet

### PR DESCRIPTION
**Pull request by chendotjs**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

simplify check for IPv6 in kubelet, easier to read

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

Thanks for your pr! Please fix the gofmt errors :) If you tag me after, I can readd the lgtm label.

**Comment by chendotjs** [comment]
@mattjmcnaughton 
This should be OK, thanks for your review

**Comment by chendotjs** [comment]
/assign @random-liu
ptal，thanks

**Comment by chendotjs** [comment]
/assign @tallclair 
ptal, thanks

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/assign @Random-Liu

**Comment by chendotjs** [comment]
/assign @yujuhong 
ptal, thanks

**Pull request merged**
