### PR TITLE
Set node external IP for azure node when disabling UseInstanceMetadata

### LINKED ISSUE #60958: Node external IP is not set when disabling useInstanceMetadata
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

Node external IP is set when useInstanceMetadata is set true, but not when useInstanceMetadata is disabled. 

**What you expected to happen**:

Node external IP is set regardless of useInstanceMetadata setting.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by feiskyer**
**What this PR does / why we need it**:

This PR sets node external IP for azure node disabling UseInstanceMetadata.

It also adds a check of whether it is running locally when UseInstanceMetadata.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #60958

**Special notes for your reviewer**:

**Release note**:

```release-note
Set node external IP for azure node when disabling UseInstanceMetadata
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
@feiskyer if it's a bug, is there a bug description?

**Comment by feiskyer** [comment]
@andyzhangx Yep, forgot to include it. It fixes #60958.

**Comment by khenidak** [comment]
While the code is good to go (specially in case of current node). I am not sure if we should assign public/external IPs to nodes. Do we assign public IPs to nodes?

**Comment by feiskyer** [comment]
> While the code is good to go (specially in case of current node). I am not sure if we should assign public/external IPs to nodes. Do we assign public IPs to nodes?

acs-engine or aks won't do this. It determines to users. If users assigned a public IP, then it should be included in node's addresses (we have already done this with UseInstanceMetadata=true).

**Comment by khenidak** [comment]
That is correct. 
/LGTM

**Comment by feiskyer** [comment]
Added to v1.10 milestone since it is a critical bug fix. cc @jdumars

**Pull request merged**
