### PR TITLE
Extend service accounts with optional tokenGetter provider

### PR DESCRIPTION
**Pull request by mjudeikis**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Enables users to provide their own tokenGetter function implementation to service accounts. This is needed when constructing a generic control plane and some APIs might not be available. 

Second attempt to make it nicer. First failed was https://github.com/kubernetes/kubernetes/pull/125793

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mjudeikis** [comment]
ping @enj  :) Any chance you had time to look into this?

**Comment by sttts** [comment]
This is not changing anything in the existing behaviour, just adds a way to opt-out of watching pods+nodes for generic controlplane applications, towards https://github.com/kubernetes/enhancements/issues/4080.

/lgtm
/approve

**Pull request merged**
