### PR TITLE
Automated cherry pick of #53169

### PR DESCRIPTION
**Pull request by resouer**
Cherry pick of #53169 on release-1.7.

#53169: Fix a scheduler flaky e2e test

```release-note
NONE
```

### CODE REVIEW

**Comment by bsalamat** [comment]
Thanks, Harry. The PR LGTM, of course, but please add "release note none". It also needs a cherry pick label which I don't know how to add.

**Comment by resouer** [comment]
I think the final step is approve from release team of 1.7  cc @dchen1107 @idvoretskyi

**Comment by wojtek-t** [comment]
@resouer - actually I'm 1.7 patch release manager. So approved.

**Pull request merged**
