### PR TITLE
Fix: drop arm when release etcd image

### PR DESCRIPTION
**Pull request by kkkkun**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes # https://github.com/kubernetes/kubernetes/issues/117557

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
It doesn't look like we've clearly root-caused the build failure yet?

https://github.com/kubernetes/kubernetes/issues/117557#issuecomment-1520763414

**Comment by pacoxu** [comment]
> It doesn't look like we've clearly root-caused the build failure yet?
> 
> [#117557 (comment)](https://github.com/kubernetes/kubernetes/issues/117557#issuecomment-1520763414)

Since https://github.com/kubernetes/kubernetes/pull/115742 drops the arm32 support, this fix can be merged in my opinion.

**Comment by dims** [comment]
see last comment from @BenTheElder 

/close

**Comment by pacoxu** [comment]
According to https://github.com/etcd-io/etcd/discussions/15791, droping arm is still valid for etcd image.

> I think we build arm, but not release it https://github.com/etcd-io/etcd/blob/main/scripts/release.sh#L261
> 
> Official doc about supported architectures https://etcd.io/docs/v3.5/op-guide/supported-platform/

etcd release team just build it and not release it for arm.

**Pull request closed without merging**
