### PR TITLE
Fix zero-value custom resource validation with go1.16

### LINKED ISSUE #99804: Custom resource empty string / null validation broken with go1.16
#### What happened:

Reported by @uablrek in https://github.com/projectcalico/calico/issues/4443

After the switch to go1.16, custom resource clients submitting empty string values for string fields receive the following error:
```
The $Kind "$name" is invalid: $fieldpath: Invalid value: "null": $fieldpath in body must be of type string: "null"
```

#### How to reproduce it (as minimally and precisely as possible):

Create the following crd:
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: zerovalues.example.com
spec:
  group: example.com
  names:
    kind: ZeroValue
    listKind: ZeroValueList
    plural: zerovalues
    singular: zerovalue
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          a:
            type: string
        type: object
    served: true
    storage: true
```

Try to create the following custom resource:
```yaml
apiVersion: example.com/v1
kind: ZeroValue
metadata:
  name: default
a: ""
```

Building `master` with go1.15.8, this works. Building `master` with go1.16, this fails with:

```
The ZeroValue "default" is invalid: a: Invalid value: "null": a in body must be of type string: "null"
```

/priority critical-urgent
/sig api-machinery
/milestone v1.21

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind bug
/kind regression
/priority critical-urgent

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/99804

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/cc @BenTheElder @uablrek

### CODE REVIEW

**Comment by liggitt** [comment]
Added an integration test exercising explicit and defaulted zero values and null values for all types

**Comment by liggitt** [comment]
flake is https://github.com/kubernetes/kubernetes/issues/99821

/retest

**Comment by liggitt** [comment]
```
=== RUN   TestFirewallNeedsUpdate/When_basic_flow_without_exceptions.
I0305 05:10:42.053527   96318 gce_loadbalancer_external.go:482] ensureTargetPoolAndHealthCheck(a(/fakesvc)): Deleted target pool.
I0305 05:10:42.053623   96318 gce_loadbalancer_external.go:901] Creating firewall k8s-test-cluster-id-node-http-hc for health checks.
I0305 05:10:42.053741   96318 gce_loadbalancer_external.go:905] Created firewall k8s-test-cluster-id-node-http-hc for health checks.
I0305 05:10:42.053839   96318 gce_loadbalancer_external.go:694] Did not find health check k8s-test-cluster-id-node, creating port 10256 path /healthz
I0305 05:10:42.053931   96318 gce_loadbalancer_external.go:703] Created HTTP health check k8s-test-cluster-id-node healthCheckNodePort: 10256
I0305 05:10:42.053968   96318 gce_loadbalancer_external.go:553] Creating targetpool a with 1 healthchecks
    gce_loadbalancer_external_test.go:895: 
        	Error Trace:	gce_loadbalancer_external_test.go:895
        	Error:      	Not equal: 
        	            	expected: false
        	            	actual  : true
        	Test:       	TestFirewallNeedsUpdate/When_basic_flow_without_exceptions.
        	Messages:   	'needsUpdate' didn't return as expected When basic flow without exceptions.
I0305 05:10:42.054063   96318 gce_loadbalancer_external.go:495] ensureTargetPoolAndHealthCheck(a(/fakesvc)): Created health checks k8s-test-cluster-id-node.
I0305 05:10:42.054196   96318 gce_loadbalancer_external.go:498] ensureTargetPoolAndHealthCheck(a(/fakesvc)): Created target pool.
    --- FAIL: TestFirewallNeedsUpdate/When_basic_flow_without_exceptions. (0.00s)
```

😕 

/retest

**Comment by liggitt** [comment]
#99821

/retest

**Review by uablrek — APPROVED** [review]
I applied this PR and built `v1.21.0-beta.0.566+7a491401452136-dirty`. And now calico starts ok.

**Comment by BenTheElder** [comment]
Kubelet config data race 
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99817/pull-kubernetes-unit/1367800801279348736
/retest

**Comment by liggitt** [comment]
> Kubelet config data race
> https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99817/pull-kubernetes-unit/1367800801279348736


opened https://github.com/kubernetes/kubernetes/issues/99845

**Pull request merged**
