### PR TITLE
Move pkg/kubectl/util/qos to staging

### PR DESCRIPTION
**Pull request by sallyom**
* Moves pkg/kubectl/util/qos to staging.
* Publishes this code to the new kubectl repository: https://github.com/kubernetes/kubectl/pkg/util/qos
* Code will be available for re-use after publishing.
/kind cleanup
/sig cli
/area kubectl

```release-note
NONE
```

### CODE REVIEW

**Comment by sallyom** [comment]
see same failure [here](https://github.com/kubernetes/kubernetes/pull/79202#issuecomment-504039093)

**Comment by monopole** [comment]
/lgtm
/approve
hope this is sticky over the rebase

**Review by seans3 — CHANGES_REQUESTED** [review]
Generated file: pkg/kubectl/generated/bindata.go should be removed from this PR. It is causing "hack/verify-generated-files.sh" to fail.

**Comment by seans3** [comment]
Please remove `staging/publishing/rules.yaml` from this PR. Now that we've rebased it multiple times, we shouldn't have to change that file anymore. Your current changes to that file in this PR are only indentation changes, which make it inconsistent with the rest of the `rules.yaml` file.

**Comment by sallyom** [comment]
@monopole I cleaned up the stale commit from rebase (unwanted indentation change to publishing/rules.yaml), should be good now, thanks

**Pull request merged**
