### PR TITLE
DockerCache doesn't get containers at startup.

### LINKED ISSUE #5092: kubelet initialization error
I launched a cluster that was unhealthy and was trying to diagnose why when I ran across an interesting kubelet error. 

On the master, The validate endpoint is showing that the single node in the cluster cannot be reached:

```
$ curl 127.0.0.1:8080/validate
[
  {
    "component": "scheduler",
    "health": "success",
    "msg": "ok",
    "err": "nil"
  },
  {
    "component": "etcd-0",
    "health": "success",
    "msg": "{\"action\":\"get\",\"node\":{\"dir\":true,\"nodes\":[{\"key\":\"/registry\",\"dir\":true,\"modifiedIndex\":3,\"createdIndex\":3}],\"modifiedIndex\":3,\"createdIndex\":3}}\n",
    "err": "nil"
  },
  {
    "component": "node-0",
    "health": "unknown",
    "healthCode": 2,
    "err": "Get http://xxxxx.internal:10250/healthz: dial tcp 10.240.230.53:10250: connection refused"
  },
  {
    "component": "controller-manager",
    "health": "success",
    "msg": "ok",
    "err": "nil"
  }
]
```

From ```/var/log/kubelet.log``` on the node I see:
```
E0305 08:44:41.696593    4616 server.go:299] Failed to create kubelet: API error (500): engine is shutdown
```
and the kubelet appears to keep running but never recovers.

### PR DESCRIPTION
**Pull request by vmarmol**
Fixes #5092.

### CODE REVIEW

**Comment by vmarmol** [comment]
@dchen1107 PTAL

This should restore the previous behavior, but the race still exists. I plan on following this up with a PR that waits for Docker before starting the Kubelet with a timeout.

**Comment by dchen1107** [comment]
LGTM.

**Comment by wojtek-t** [comment]
Thanks for the fix!

@vmarmol: you wrote the above:
"I plan on following this up with a PR that waits for Docker before starting the Kubelet with a timeout."

 Is it already done? If not I'm happy to help with it.

**Comment by vmarmol** [comment]
@wojtek-t I had something ready and was running e2e :) #5187 is out for review.

**Pull request merged**
