### PR TITLE
Manual Cherry pick #38818 to upstream release-1.4

### PR DESCRIPTION
**Pull request by gnufied**
Cherry-pick of #38818 to release-1.4 as discussed in AWS call today.

This was rather difficult cherry-pick because of missing https://github.com/kubernetes/kubernetes/pull/29048 in release-1.4 branch and hence I changed the type of Map manually to workaround that.

CC @jsafrane @jingxu97 @chrislovecnm @justinsb

### CODE REVIEW

**Comment by gnufied** [comment]
@k8s-bot cri node e2e test this

**Comment by jessfraz** [comment]
@k8s-bot cri node e2e test this

**Comment by jessfraz** [comment]
@dims or @jingxu97 can you just confirm this should be cherry-picked thanks ;)

**Comment by jingxu97** [comment]
@jessfraz, yes, this needs to be cherrypicked. Thank you!

**Comment by chrislovecnm** [comment]
@jingxu97 is @saad-ali the release czar?

**Comment by jessfraz** [comment]
@chrislovecnm I am for 1.4

**Comment by gnufied** [comment]
I am not sure why GCE node e2e test is failing here tbh. The code is self-contained for AWS clusters, it looks unrelated. 

@jessfraz can we merge this without that flake blocking us?

**Comment by jessfraz** [comment]
yes I can push ze button :)

**Comment by chrislovecnm** [comment]
@jessfraz you are 1.4.9 ... When are we forecasting the changes?  Who has 1.5.3?

**Comment by jessfraz** [comment]
we can cut a release two weeks from today, unless you want something earlier

**Comment by chrislovecnm** [comment]
Do we have date?

**Comment by jessfraz** [comment]
the 10th

**Pull request merged**
