### PR TITLE
Update function name for public function in commend

### PR DESCRIPTION
**Pull request by yuexiao-wang**
**What this PR does / why we need it**:
Update function name for public function in commend and fix some typos in log information.

Signed-off-by: yuexiao-wang wang.yuexiao@zte.com.cn

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34533)

### CODE REVIEW

**Comment by yuexiao-wang** [comment]
@smarterclayton PTAL
Thanks!

**Comment by smarterclayton** [comment]
ok to test

**Comment by yuexiao-wang** [comment]
@smarterclayton PTAL
CI is passed after my update.

**Comment by yuexiao-wang** [comment]
@smarterclayton PTAL
Could you give me some suggestion for this PR?
Thanks!

**Comment by yuexiao-wang** [comment]
@smarterclayton  @apelisse PTAL
Could you give me some suggestion for this PR?
Thanks!

**Comment by apelisse** [comment]
Updates to comments make sense. Why did you uncapitalize "Unsupported" ?

**Comment by yuexiao-wang** [comment]
@apelisse PTAL
Reference here: https://github.com/golang/go/wiki/CodeReviewComments#error-strings

Error Strings

Error strings should not be capitalized (unless beginning with proper nouns or acronyms) or end with punctuation, since they are usually printed following other context. That is, use fmt.Errorf("something bad") not fmt.Errorf("Something bad"), so that log.Printf("Reading %s: %v", filename, err) formats without a spurious capital letter mid-message. This does not apply to logging, which is implicitly line-oriented and not combined inside other messages.

**Comment by smarterclayton** [comment]
@k8s-bot ok to test issue #IGNORE

**Comment by apelisse** [comment]
That looks good to me, but I don't really have power here

**Comment by smarterclayton** [comment]
@k8s-bot ok to test issue #IGNORE

**Comment by yuexiao-wang** [comment]
@smarterclayton PTAL
Jenkins Bazel build failed！ But I cannot see the log about details as follows:
Unable to load build details from gs://kubernetes-jenkins/pr-logs/pull/34533/pull-kubernetes-bazel/587993870401985064

**Comment by smarterclayton** [comment]
@k8s-bot bazel test this

**Pull request merged**
