### PR TITLE
Remove folder pkg/scheduler/algorithm

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind cleanup
/sig scheduling

**What this PR does / why we need it**:

We don't have legacy code in pkg/scheduler/algorithm anymore - predicates/priorities and their helper methods have been refactored. So this PR remove the folder `pkg/scheduler/algorithm` entirely.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/cc @ahg-g

### CODE REVIEW

**Comment by ahg-g** [comment]
/lgtm

WE ARE DONE :)

**Comment by haosdent** [comment]
:+1:

**Pull request merged**
