### PR TITLE
Automated cherry pick of #74997: Track dry-run and apply in metrics

### PR DESCRIPTION
**Pull request by jennybuckley**
Cherry pick of #74997 on release-1.13.

#74997: Track dry-run and apply in metrics

### CODE REVIEW

**Comment by jennybuckley** [comment]
/priority important-soon
/cc apelisse

Third time's the charm. I had to resolve some conflicts manually on this, mostly because apply doesn't exist in 1.13

This is not an api changing PR

**Comment by jennybuckley** [comment]
needed for https://github.com/kubernetes/kubernetes/issues/68514

**Comment by jennybuckley** [comment]
@aleksandra-malinowska @tpepper @liggitt @apelisse

**Comment by tpepper** [comment]
@jennybuckley can you clarify why this needs backported?  This isn't clearly stated.

Going by the labels around feature and api-change make it at first look like something we would not backport, also the linked issue #68514 describing enabling feature promotion.  Reading the code though it looks like it is perhaps isolated and arguably test code since it's dry run validation and we do sometimes backport things like that to enable upgrade testing for example.

**Comment by jennybuckley** [comment]
/close
I don't think this is appropriate for a cherry-pick since it's not a bug fix, but adding a metric.

**Pull request closed without merging**
