### PR TITLE
Support IPv6 in echoserver

### PR DESCRIPTION
**Pull request by johngmyers**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This extends the echoserver so that it also listens on IPv6.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
@johngmyers tested this locally already?

**Comment by johngmyers** [comment]
Yes, tested a private amd64-only image build in an IPv6-only cluster.

**Comment by johngmyers** [comment]
```
curl http://'[fd00:5e4f:ce::e2b3]':80  


Hostname: echoserver-557bb6dc7c-tzhd4

Pod Information:
	-no pod information available-

Server values:
	server_version=nginx: 1.14.2 - lua: 10015

Request Information:
	client_address=2600:1f18:1e5f:8501:570d::6a35
	method=GET
	real path=/
	query=
	request_version=1.1
	request_scheme=http
	request_uri=http://[fd00:5e4f:ce::e2b3]:8080/

Request Headers:
	accept=*/*
	host=[fd00:5e4f:ce::e2b3]
	user-agent=curl/7.68.0

Request Body:
	-no body in request
```

**Comment by dims** [comment]
/approve

leaving lgtm for @mkumatag or other reviewers.

**Comment by aojea** [comment]
I think that this functionality is already in the `agnhost` image :thinking:

**Pull request merged**
