### PR TITLE
Automated cherry pick of #45127 #45129

### PR DESCRIPTION
**Pull request by ixdy**
Cherry pick of #45127 #45129 on release-1.6.

#45127: fix build
#45129: rehost debs until we have a better solution for updating

### CODE REVIEW

**Comment by ixdy** [comment]
FYI this fixed the broken bazel build on 1.6, and it future-proofs it from future breakage.

**Comment by mikedanese** [comment]
Needs approval

/assign @thockin

**Comment by enisoc** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
