### PR TITLE
add jiahuif as a reviewer to staging/src/k8s.io/controller-manager/OWNERS

### PR DESCRIPTION
**Pull request by jiahuif**
/kind cleanup

#### What this PR does / why we need it:
Add myself @jiahuif as a review of `staging/src/k8s.io/controller-manager`

#### Special notes for your reviewer:

Please merge when you think I am qualified.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jiahuif** [comment]
KEPs under `staging/controller-manager`:
- https://github.com/kubernetes/enhancements/issues/2436
PRs under `staging/controller-manager`
- https://github.com/kubernetes/kubernetes/pull/94205
- https://github.com/kubernetes/kubernetes/pull/96133
- https://github.com/kubernetes/kubernetes/pull/96133
- https://github.com/kubernetes/kubernetes/pull/99507

**Comment by deads2k** [comment]
> KEPs under `staging/controller-manager`:
> 
> * [kubernetes/enhancements#2436](https://github.com/kubernetes/enhancements/issues/2436)
> 
> PRs under `staging/controller-manager`
> 
> * #94205
> * #96133
> * #96133
> * #99507

Sorry I was a bit slow coming back to this.  Feel free to get me on slack next time.

/lgtm


I'll leave approval to @cheftako

**Pull request merged**
