### PR TITLE
Enable PodAffinity by default in scheduler

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #26144

@gmarek - FYI

### CODE REVIEW

**Comment by wojtek-t** [comment]
I would like to profile it a bit more before we merge it, so applying "do-not-merge" label for now.
But it's ready for review.

**Comment by wojtek-t** [comment]
OK - so I did some more experiments and scheduler throughput it slightly worse with this PR, but the difference is acceptable in my opinion. I think we should go with it, and optimize when needed.

@davidopp - PTAL

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
