### PR TITLE
Fixes GoLint errors for pkg/capabilities

### PR DESCRIPTION
**Pull request by BK1603**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
FIxes golint errors in the package `pkg/capabilities`

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/68026

**Special notes for your reviewer**:
This is my first time contributing to kubernetes, just let me know if something is wrong with this PR :smile: 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
@BK1603 thank you for the PR.
please squash your commits into one.

/priority backlog
/kind cleanup

**Comment by BK1603** [comment]
@neolit123 Done!

**Comment by neolit123** [comment]
thanks for the update.
needs approval by the maintainers of this code.
/ok-to-test

**Comment by BK1603** [comment]
@neolit123 An off topic question :sweat_smile: 
I have fixed more things in the package `pkg/util/bandwidth`, so should I wait for this PR to get merged and then push them?

**Comment by neolit123** [comment]
> I have fixed more things in the package pkg/util/bandwidth, so should I wait for this PR to get merged and then push them?

by adding fixes in a different package the PR might need different / more maintainers to approve, which can technically delay a PR.

if there are a lot of changes PRs per package is bettter, but if the changes are small a single PR is fine too.
your choice!

**Comment by BK1603** [comment]
@neolit123 Will wait then!! :smile:

**Pull request closed without merging**
