### PR TITLE
Use INSTANCE_PREFIX to prefix uploaded binaries in GCE

### LINKED ISSUE #8705: Jenkins GCE e2e: server version sometimes mismatches client version
We seem to have an occasional consistency issue between the client and server versions on our Jenkins GCE e2e project.

Build 6295 failed this morning because the client version was *newer* than the server version:
```
2015/05/22 11:42:29 Running: 'kubectl version --match-server-version=false'
Client Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.1-666-ge0092a1c230f6c-dirty", GitCommit:"e0092a1c230f6c2f01886823791eef24fbbd6023", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.1-629-gd9d12fd3f7036c-dirty", GitCommit:"d9d12fd3f7036c92606fc3ba9046b365212fcd70", GitTreeState:"dirty"}
```

The server version matches the build was was immediately running in 6294, which was aborted early. I wonder if (somehow) the cleanup didn't work properly? (Which is a bit worrying if so.)

Here's the version from 6294:
```
Client Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.1-629-gd9d12fd3f7036c-dirty", GitCommit:"d9d12fd3f7036c92606fc3ba9046b365212fcd70", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.1-629-gd9d12fd3f7036c-dirty", GitCommit:"d9d12fd3f7036c92606fc3ba9046b365212fcd70", GitTreeState:"dirty"}
```

A short while later, build 6297 failed, this time with the client version *older* than the server version:
```
Client Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.1-678-g17ac4b1dfc83f1-dirty", GitCommit:"17ac4b1dfc83f197a77cbc7370c7305ef93b719a", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"17+", GitVersion:"v0.17.1-680-ga823f6d1d50ccb-dirty", GitCommit:"a823f6d1d50ccb1491f4c80db68cfa63ce7a7786", GitTreeState:"dirty"}
```

This one makes a little bit more sense: there was a new build published between downloading the client/test tarballs and setting up the cluster. I'm guessing that somewhere in the cluster setup scripts the latest CI release file was read again, rather than using the version read for the client/test tarballs. (I haven't yet worked out where exactly it's read, but it should be an easier fix.)

cc @quinton-hoole @zmerlynn

### PR DESCRIPTION
**Pull request by ikehz**
@quinton-hoole @ixdy @alex-mohr Any objection to this (fixes #8705)?

In writing up the issue I mentioned in https://github.com/kubernetes/kubernetes/issues/8705#issuecomment-174083697, it became apparent this seemed like an easy fix—I see no reason not to use `INSTANCE_PREFIX` for this.  It should maybe be called something like `CLUSTER_PREFIX`, but that's a fixup we can apply if we want.

cc @spxtr for clarifying e2e deployments.

### CODE REVIEW

**Comment by alex-mohr** [comment]
Seems reasonable to me, but I don't understand util.sh well-enough to review.  Thanks Ike!

**Comment by alex-mohr** [comment]
... but you're proposing that we not move the 3 tests sharing a project into their own projects as a result of this?  I'm not convinced this PR is enough to provide sufficient isolation given all the "fun" shared-quota issues we've had too.

**Comment by ihmccreery** [comment]
@alex-mohr No, I'm not suggesting this is a fix for quota problems, just the deployment race flake; we've gone back and forth about that and #18119 is our proposed solution to that.  Isolating test runs in projects is a good stop-gap that we just haven't been keeping up with.

**Comment by ihmccreery** [comment]
Fixes #20036.

**Comment by ihmccreery** [comment]
@k8s-oncall this is a fixe for #8705, flake, so it'd be good to prioritize.

**Comment by dchen1107** [comment]
Manually merged this without waiting for GCE e2e finish since it passed before and there is no change. Our pr build e2e is totally hosed now. I am monitoring the jenkins/builds very close anyway.

**Pull request merged**
