### PR TITLE
Remove mount option validation

### PR DESCRIPTION
**Pull request by gnufied**
Remove creation time mount option validation.  Fixes for #42573

### CODE REVIEW

**Comment by gnufied** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by smarterclayton** [comment]
Is this an alpha or beta feature?  We'll have to tighten validation in the future, which is an api change, so I hope this isn't going to be considered "GA" in 1.6

**Comment by gnufied** [comment]
This is a beta feature.

**Comment by soltysh** [comment]
@saad-ali since you were the original azsignee for https://github.com/kubernetes/kubernetes/pull/41906

**Comment by gnufied** [comment]
@k8s-bot kops aws e2e test this

**Comment by gnufied** [comment]
@k8s-bot non-cri e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot kops aws e2e test this

**Comment by gnufied** [comment]
Closing this in favour of https://github.com/kubernetes/kubernetes/pull/42811

**Pull request closed without merging**
