### PR TITLE
Caller of HandlePodSyncs should be  handler in kubelet syncLoopIteration 

### PR DESCRIPTION
**Pull request by yanxuean**

### CODE REVIEW

**Comment by feiskyer** [comment]
@k8s-bot ok to test

**Comment by xiangpengzhao** [comment]
@timstclair ping for approve :)

**Comment by xiangpengzhao** [comment]
@k8s-bot pull-kubernetes-node-e2e test this

ping @timstclair or @Random-Liu for approval :)

**Comment by xiangpengzhao** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by feiskyer** [comment]
ping @timstclair @yujuhong  for approval

**Comment by feiskyer** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
