### PR TITLE
remove in-tree volume limits test now that CSIMigration is GA

### PR DESCRIPTION
**Pull request by amacaskill**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR removes the in-tree volume limits test now that CSIMigration is GA. 
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
should this removal be picked to 1.25 since it only runs in [aws / gce / gke](https://github.com/kubernetes/kubernetes/blob/v1.25.0/test/e2e/storage/volume_limits.go#L38), and CSI Migration for those [went GA in 1.25](https://github.com/kubernetes/kubernetes/blob/v1.25.0/pkg/features/kube_features.go#L112-L141)?

**Comment by msau42** [comment]
Yes, we can cherry pick this to 1.25 as well. @amacaskill do you want to open the cherry pick?

**Comment by amacaskill** [comment]
> Yes, we can cherry pick this to 1.25 as well. @amacaskill do you want to open the cherry pick?

Opened https://github.com/kubernetes/kubernetes/pull/112956#issuecomment-1275296836

**Pull request merged**
