### PR TITLE
Always use quorum reads, ignoring --etcd-quorum-read

### PR DESCRIPTION
**Pull request by anguslees**
**What this PR does / why we need it**:

Non-quorum reads are incorrect, and there is no legitimate reason to
set `--etcd-quorum-read=false`.  This change escalates the default to
simply ignoring the flag and _always_ performing quorum reads.

The flag itself is left as a compatibility measure, with a
corresponding change to its description to make it clear that it is
ignored.

**Which issue this PR fixes**

See also #53662 #53717 #53795

**Special notes for your reviewer**:

I left the code for handling quorum=false in the underlying etcd2/etcd3 storage implementations.  I can remove those options/branches too if we want to really remove this (no longer tested) code.

**Release note**:

```release-note
apiserver --etcd-quorum-read=true is now assumed.  The flag is deprecated and ignored.
```

### CODE REVIEW

**Comment by anguslees** [comment]
@liggitt fyi ^

**Comment by anguslees** [comment]
From what I understand, the only case where --etcd-quorum-read=false is safe is the degenerate case of a single etcd server, where quorum and non-quorum reads are equivalent.   Following this understanding, I found it absurd that we were documenting the existence of a "--bugs=on" parameter rather than just fixing it...

**Comment by enj** [comment]
Enabling quorum on etcd 2 can have performance impacts IIRC.

**Comment by anguslees** [comment]
> Enabling quorum on etcd 2 can have performance impacts IIRC.

Right, but are you saying it is still _correct_?  Fast and incorrect is of course not acceptable  (or at least if it was acceptable, I can think of many other approaches that would be even _faster_ and _more_ incorrect! ;)

**Comment by enj** [comment]
It is still correct because you only get stale reads, writes are always strongly consistent.  I am not saying it is a good idea, but I am not sure we should take away the choice.

I see two options:

1. Change the default value to true so you no longer need to opt-in to quorum reads, but can still opt-out.
2. Delete the flag and all of the code with it to make it obvious we took away the choice.

**Comment by anguslees** [comment]
@enj: (1) has been done very recently.  This PR is basically (2), except I'm leaving the actual flag in place (but ignored) during the deprecation period to avoid breaking existing deployments that provide it explicitly.

@enj: So my understanding behind the push to change the default to `=true` was that without quorum-reads we don't get read-after-write consistency (without tracking etcd revisions consistently across these operations), and this confuses things in the codebase.  I'd be delighted if someone could step forward and speak authoritatively on this, since if we truly _don't_ need quorum-reads then of course we shouldn't be doing them, and this PR should be removing the flag in the other direction!

(Basically, the code _must_ be structured to assume one model of consistency or the other - or we need to write two separate implementations of our most subtle logic, which we haven't done.  I struggle to understand how it would ever make sense to have this particular algorithm detail able to be changed via a user flag.)

**Comment by liggitt** [comment]
There is no inherent reason controllers could not be written to support inconsistent reads (and many controllers did and still do tolerate that), but there are several reasons we should probably deprecate and remove this flag:

* Non-quorum reads make controllers more complicated (many controllers attempt to handle it, some likely do not)
* CI does not run with etcd clusters, meaning we do not have good test coverage to catch controllers that do not handle inconsistent reads
* The cost of quorum reads went way down with etcd3

**Comment by enj** [comment]
I agree that we should deprecate the flag and always use quorum reads.  I do not agree that we should leave the flag in place and silently ignore it.  We should either remove the flag and break people using it, or leave the flag and break people who set it to `false`.  Ignoring an explicit configuration by the user with no indication seems inappropriate.

**Comment by liggitt** [comment]
Defaulting to true, marking deprecated, updating the description to say it's required for HA etcd, and removing the flag in 2 releases seems more than sufficient to me. I have seen no instances of explicitly setting this flag to false.

**Comment by enj** [comment]
@liggitt are you OK with defaulting to `true` even if explicitly set to `false`?  That is the only part I am not a fan of, everything else SGTM.

**Comment by liggitt** [comment]
> @liggitt are you OK with defaulting to true even if explicitly set to false?

No. That's not defaulting, that's forcing.

**Comment by dims** [comment]
my 2 cents, we should yank the thing out (vs not honoring the user's explicit flag)

**Comment by anguslees** [comment]
Just so we're all on the same page, the options so far are:
1. Do --etcd-quorum-read=true by default and leave it so that --etcd-quorum-read=false behaves incorrectly (this is current master behaviour, as of very recently).  Remove the flag at the end of the deprecation period.
2. Do --etcd-quorum-read=true and continue to behave correctly even if --etcd-quorum-read=false is specified (this is this PR). Remove the flag at the end of the deprecation period.
3. Do --etcd-quorum-read=true and break if the flag is explicitly specified with either value, before the end of the deprecation period.  (@enj's suggestion above)

**Comment by enj** [comment]
Option 1 is @liggitt's suggestion, though he had some tweaks:

> Defaulting to true, marking deprecated, updating the description to say it's required for HA etcd, and removing the flag in 2 releases

I am in agreement with that (and opposed to this PR because it ignores the user's explicit intent).

**Comment by lavalamp** [comment]
This requires a deprecation, so 2 releases before we can remove like this. I am fine to deprecate it in 1.9.

**Comment by lavalamp** [comment]
What's the story on this PR? Can we deprecate this field?

**Comment by liggitt** [comment]
Yes, it was marked deprecated in https://github.com/kubernetes/kubernetes/pull/53795

/close

**Pull request closed without merging**
