### PR TITLE
Revert "cr2 e2e: remove experimental-mounter-rootfs flag"

### PR DESCRIPTION
**Pull request by yujuhong**
Reverts kubernetes/kubernetes#36166

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36239)

### CODE REVIEW

**Comment by yujuhong** [comment]
@k8s-bot cri test this

**Comment by yujuhong** [comment]
The mounter rootfs flag got restored again because of the revert (#36206), revert my revert.

**Comment by yujuhong** [comment]
@mtaufen @Random-Liu @dchen1107, could any of you lgtm this once the cri tests passed? Thanks!

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
There is still some failed tests in CRI GCE e2e, but not related to your change.

**Comment by dchen1107** [comment]
@k8s-bot cri e2e test this

**Comment by yujuhong** [comment]
@k8s-bot node e2e test this

**Comment by yujuhong** [comment]
@k8s-bot node e2e test this

**Comment by yujuhong** [comment]
@saad-ali (oncall), can we manually merge this to unblock the CRI builds? This is just a test config change for CRI and does not affect others. Thanks.

**Comment by saad-ali** [comment]
Manually merged to unblock testing for other PRs

**Pull request merged**
