### PR TITLE
refractoring syncPod func for err process

### PR DESCRIPTION
**Pull request by 249043822**
-   // We failed to update status, wait for periodic sync to retry.
  -  glog.Warningf("Failed to update status for pod %q: %v", format.Pod(pod), err)

Originally, the code above may print not correct err, or maybe err is nil, so i changed the code structrue

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30064)

### CODE REVIEW

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
lgtm

**Comment by 249043822** [comment]
@vishh , there maybe some wrong on the test, could you make retest? thanks

**Comment by 249043822** [comment]
@k8s-bot test this issue: #350

**Comment by 249043822** [comment]
@vishh now it's green, neen lgtm, thanks

**Comment by 249043822** [comment]
@vishh now it's green, neen lgtm, thanks

**Pull request closed without merging**
