### PR TITLE
Bump cAdvisor to v0.23.4

### LINKED ISSUE #27194: cAdvisor /stats/summary endpoint in kubelet returns incorrect cpu usage numbers
### Environment
Kubernetes version: 1.2.3
Docker version: 1.10.3
3 node(c4.xLarge) cluster on AWS running CoreOS 1010.4.0.
### Issue
After facing an issue with incorrect metrics being reported by heapster kubernetes/heapster#1177 I tried querying the cadvisor /stats/summary endpoint directly to see if that would give me consistent values for node cpu usage.
I have one pod with cpu request=1000m and limit=1000m. In that pod I run a busy loop to consume a 100% of the cpu. This is what top shows on the node.
screen shot 2016-06-10 at 10 07 52 am

I query the /stats/summary endpoint every 5 seconds, however it seems that the latest timestamps are only updated every 15 seconds or so. Checking the `summary.Node.CPU.UsageNanoCores` value from the summary returned gives me the following output(formatted):

```
TS:2016-06-09T20:05:20-07:00, Percentage:105.539566 Val:1055395658
TS:2016-06-09T20:05:31-07:00, Percentage:107.416097 Val:1074160974
TS:2016-06-09T20:05:44-07:00, Percentage:108.195877 Val:1081958770
TS:2016-06-09T20:05:59-07:00, Percentage:106.670910 Val:1066709101
TS:2016-06-09T20:06:19-07:00, Percentage:14.360576 Val:143605762
TS:2016-06-09T20:06:31-07:00, Percentage:108.000277 Val:1080002769
TS:2016-06-09T20:06:41-07:00, Percentage:108.373232 Val:1083732315
TS:2016-06-09T20:06:56-07:00, Percentage:107.025070 Val:1070250700
TS:2016-06-09T20:07:16-07:00, Percentage:13.004869 Val:130048687
TS:2016-06-09T20:07:31-07:00, Percentage:106.839146 Val:1068391461
TS:2016-06-09T20:07:48-07:00, Percentage:107.614464 Val:1076144640
TS:2016-06-09T20:08:06-07:00, Percentage:4.232330 Val:42323305
TS:2016-06-09T20:08:20-07:00, Percentage:106.009173 Val:1060091732
TS:2016-06-09T20:08:35-07:00, Percentage:108.121440 Val:1081214401
TS:2016-06-09T20:08:50-07:00, Percentage:106.659561 Val:1066595609
TS:2016-06-09T20:09:07-07:00, Percentage:1.724644 Val:17246439
TS:2016-06-09T20:09:19-07:00, Percentage:106.633227 Val:1066332268
TS:2016-06-09T20:09:38-07:00, Percentage:9.938621 Val:99386209
TS:2016-06-09T20:09:53-07:00, Percentage:107.046112 Val:1070461118
TS:2016-06-09T20:10:10-07:00, Percentage:3.373636 Val:33736361
TS:2016-06-09T20:10:25-07:00, Percentage:107.338541 Val:1073385413
TS:2016-06-09T20:10:39-07:00, Percentage:108.575783 Val:1085757834
TS:2016-06-09T20:10:54-07:00, Percentage:107.055382 Val:1070553817
TS:2016-06-09T20:11:13-07:00, Percentage:7.869509 Val:78695088
TS:2016-06-09T20:11:32-07:00, Percentage:11.476262 Val:114762620
TS:2016-06-09T20:11:45-07:00, Percentage:106.928681 Val:1069286811
TS:2016-06-09T20:12:03-07:00, Percentage:3.309632 Val:33096320
TS:2016-06-09T20:12:15-07:00, Percentage:105.832345 Val:1058323450
TS:2016-06-09T20:12:34-07:00, Percentage:5.079409 Val:50794090
TS:2016-06-09T20:12:47-07:00, Percentage:106.305439 Val:1063054389
TS:2016-06-09T20:13:05-07:00, Percentage:3.613690 Val:36136900
TS:2016-06-09T20:13:24-07:00, Percentage:9.785441 Val:97854409
TS:2016-06-09T20:13:43-07:00, Percentage:12.661783 Val:126617830
```
As you can see I'm not getting a steady report of near 100% cpu usage values for UsageNanoCores. Any idea why this might be the case or how I can debug this issue. Also is there any way I can change the resolution of the summary stats to get more fine grained reporting.

### PR DESCRIPTION
**Pull request by dchen1107**
``` release-note
Check for thin_is binary in path for devicemapper when using ThinPoolWatcher and fix uint64 overflow issue for CPU stats
```

Fix #27194 #27573

### CODE REVIEW

**Comment by dchen1107** [comment]
cc/ @pmorie @Random-Liu

**Comment by dchen1107** [comment]
https://github.com/kubernetes/kubernetes/issues/27573

**Comment by Random-Liu** [comment]
```
FAILED   ./hack/../hack/verify-godep-licenses.sh	8s
Verifying ./hack/../hack/verify-godeps.sh
Checking for 'Godeps/' changes against 'remote/master'
Starting to download all kubernetes godeps. This takes a while
Download finished
Your Godeps.json is different:
--- /go/src/k8s.io/kubernetes/Godeps/Godeps.json	2016-06-16 20:45:21.803968809 -0700
+++ /tmp/gopath.Xqs4LH/src/k8s.io/kubernetes/Godeps/Godeps.json	2016-06-16 21:03:24.052705064 -0700
@@ -2145,10 +2150,6 @@
 			"ImportPath": "k8s.io/heapster/metrics/apis/metrics/v1alpha1",
 			"Comment": "v1.1.0-beta2",
 			"Rev": "9cb18ac0ceb193eb530a1fe339355c94ea454d85"
-		},
-		{
-			"ImportPath": "github.com/vishvananda/netns",
-			"Rev": "8ba1072b58e0c2a240eb5f6120165c7776c3e7b8"
 		}
 	]
 }
Godeps Verify failed.
Removing /tmp/gopath.Xqs4LH
FAILED   ./hack/../hack/verify-godeps.sh	406s
```

**Comment by dchen1107** [comment]
Godep was killing me yesterday. :-( Looking into it now.

**Comment by dchen1107** [comment]
Ok, including the license for github.com/vishvananda/netns and I think this should fix above godep license issue. cc/ @matchstick

**Comment by Random-Liu** [comment]
LGTM. Let's wait for the test result. Godeps is really hard to use...

**Comment by dchen1107** [comment]
All scripts passed finally.

**Comment by Random-Liu** [comment]
LGTM!

**Pull request merged**
