### PR TITLE
Add Input Validation for audit-id Header in API Server Audit Logging

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by aojea** [comment]
please add a description explaining the motivation, or just better open an issue first to describe the problem and agree on the solution with the maintainers

**Comment by aramase** [comment]
/hold

Thanks for the PR. This type of change is backward incompatible. Please start with an issue describing your motivation and we can discuss this in a future SIG Auth meeting.

(commented as part of sig-auth triage meeting)

**Comment by fedebongio** [comment]
/remove-sig api-machinery
Looks like more sig-auth

**Pull request closed without merging**
