### PR TITLE
fixed goimports nits

### PR DESCRIPTION
**Pull request by mikedanese**
This is very optional. Fixed miscellaneous goimports nits. goimports runs now which is nice.

### CODE REVIEW

**Comment by ddysher** [comment]
Thanks for the fix.  I use this config in emacs and it causes me headache...
```
(add-hook 'before-save-hook 'gofmt-before-save)
```

**Comment by brendandburns** [comment]
LGTM.  Thanks for the PR.

**Comment by thockin** [comment]
We should not need this.  If the packages are properly in your GOPATH then goimports will find them.

I did this same PR and then figured out why I did not need it.

**Comment by brendandburns** [comment]
Well, we should at least clean up the empty import() blocks...

**Comment by thockin** [comment]
Sorry I just skimmed the PR - I meant just the import-as-name changes
should not be needed.

**Comment by mikedanese** [comment]
@thockin thanks, good to know. I've pulled the named imports.

**Comment by thockin** [comment]
LGTM

**Comment by ddysher** [comment]
@thockin thanks for the tip.  

This is odd.  It doesn't work on my desktop (linux), I doubled checked the required packages.  But it works on laptop (mac).

**Comment by thockin** [comment]
Are they all in your GOPATH?  'Godep restore' or something?

If goimports can not find these, then it can not do the auto-import properly

**Comment by mikedanese** [comment]
The trick for me was to append Godeps/_workspace/ to my GOPATH. If your git working tree is clean, the packages should all be in there.

**Comment by ddysher** [comment]
I haven't append Godeps/_workspace to GOPATH, maybe I should.

Here is some info:
```
$ echo $GOPATH
/usr/local/google/home/deyuan/code/source/go-workspace
$ ls $GOPATH/src/github.com/emicklei/
go-restful
$ goimports -d $GOPATH/src/github.com/GoogleCloudPlatform/kubernetes/pkg/master/master.go
diff pkg/master/master.go gofmt/pkg/master/master.go
--- /tmp/gofmt712058473 2015-01-27 11:56:11.873413880 -0500
+++ /tmp/gofmt342704308 2015-01-27 11:56:11.873413880 -0500
@@ -55,7 +55,6 @@
        "github.com/GoogleCloudPlatform/kubernetes/pkg/ui"
        "github.com/GoogleCloudPlatform/kubernetes/pkg/util"
 
-       "github.com/emicklei/go-restful"
        "github.com/emicklei/go-restful/swagger"
        "github.com/golang/glog"
 )
```

**Comment by thockin** [comment]
or try 'godeps restore'

**Comment by ddysher** [comment]
No luck with godeps restore...

However, `godef` works find, I can jump to things defined in go-restful package.  I must did something stupid with gofmt or it's a nasty bug in gofmt.

I'll try to locate the problem.  The PR looks good and should be ready to go.

**Pull request merged**
