### PR TITLE
Revert "Merge pull request #31546 from derekwaynecarr/systemd-pod-cgr…

### PR DESCRIPTION
**Pull request by mtaufen**
We suspect that this was the cause of cross-build failures, e.g. build 1410:
```
# k8s.io/kubernetes/pkg/kubelet/cm
pkg/kubelet/cm/cgroup_manager_unsupported.go:26: cannot use unsupportedCgroupManager literal (type *unsupportedCgroupManager) as type CgroupManager in assignment:
        *unsupportedCgroupManager does not implement CgroupManager (missing CgroupName method)
pkg/kubelet/cm/cgroup_manager_unsupported.go:34: cannot use unsupportedCgroupManager literal (type *unsupportedCgroupManager) as type CgroupManager in return argument:
        *unsupportedCgroupManager does not implement CgroupManager (missing CgroupName method)
pkg/kubelet/cm/container_manager_unsupported.go:59: cannot use unsupportedPodContainerManager literal (type *unsupportedPodContainerManager) as type PodContainerManager in return argument:
        *unsupportedPodContainerManager does not implement PodContainerManager (missing Destroy method)
pkg/kubelet/cm/pod_container_manager_unsupported.go:29: cannot use unsupportedPodContainerManager literal (type *unsupportedPodContainerManager) as type PodContainerManager in assignment:
        *unsupportedPodContainerManager does not implement PodContainerManager (missing Destroy method)
+++ [1103 06:39:38] windows/amd64: go build started
# k8s.io/kubernetes/pkg/kubelet/cm
pkg/kubelet/cm/cgroup_manager_unsupported.go:26: cannot use unsupportedCgroupManager literal (type *unsupportedCgroupManager) as type CgroupManager in assignment:
        *unsupportedCgroupManager does not implement CgroupManager (missing CgroupName method)
pkg/kubelet/cm/cgroup_manager_unsupported.go:34: cannot use unsupportedCgroupManager literal (type *unsupportedCgroupManager) as type CgroupManager in return argument:
        *unsupportedCgroupManager does not implement CgroupManager (missing CgroupName method)
pkg/kubelet/cm/container_manager_unsupported.go:59: cannot use unsupportedPodContainerManager literal (type *unsupportedPodContainerManager) as type PodContainerManager in return argument:
        *unsupportedPodContainerManager does not implement PodContainerManager (missing Destroy method)
pkg/kubelet/cm/pod_container_manager_unsupported.go:29: cannot use unsupportedPodContainerManager literal (type *unsupportedPodContainerManager) as type PodContainerManager in assignment:
        *unsupportedPodContainerManager does not implement PodContainerManager (missing Destroy method)
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36168)

### CODE REVIEW

**Comment by mtaufen** [comment]
Prefer actual fix (https://github.com/kubernetes/kubernetes/pull/36163) to revert.

**Comment by ncdc** [comment]
We're working on the fix. If you can hold off reverting, we'd really appreciate it!

**Comment by mtaufen** [comment]
Yup, much prefer an actual fix :-).

**Comment by vishh** [comment]
Let's close this in favor of #36163

**Pull request closed without merging**
