### PR TITLE
Fix hyperkube's layer caching, and remove --make-symlinks at build time

### PR DESCRIPTION
**Pull request by luxas**
@david-mcmahon This is required before you release. Explanation in the code.

### CODE REVIEW

**Comment by david-mcmahon** [comment]
I see this also contains https://github.com/kubernetes/kubernetes/pull/25684.  If this one gets in first I'll close it.

**Comment by luxas** [comment]
Oops, didn't mean to include #25684, but it was required when I tested it, and then I forgot to remove it before the commit. I may remove it so we don't get any merge conflicts.

The layer patch is saving us ~130 MB/image when pulling, which is a lot

**Comment by luxas** [comment]
Fixed so it doesn't touch #25684, I think #25684 is gonna merge before this one

**Comment by luxas** [comment]
@k8s-oncall Mind merging manually?
This PR is required for the next alpha release, and now the tests seem to be unresponsive, so it doesn't reach the queue

**Comment by wojtek-t** [comment]
@k8s-bot test this please github issue: #IGNORE (tests didn't started)

**Comment by pbx0** [comment]
@luxus do you have more information on why or how `hyperkube --make-symlinks` fails? I introduced the command and I've successfully built hyperkube images using that dockerfile command above. I've also run the kubelet using the symlink entry point. 

I've just tried to reproduce any issues with the symlinks using a cut of v1.3.0 that I made today and have not seen any issues.

I'd like to fix this I just don't know how to reproduce the issues right now.

**Comment by luxus** [comment]
i think you mean @luxas 💃

**Pull request merged**
