### PR TITLE
[WIP] add grace period delay to ipvs proxier

### PR DESCRIPTION
**Pull request by sergeylanzman**
Add grace period for ipvs proxier. 
Add settings ipvs-max-grace-period (default 60s) delay before delete endpoint. 
On delete Endpoint change Weight to 0, wait ipvs-max-grace-period and delete endpoints from ipvs list

Fixes #  https://github.com/kubernetes/kubernetes/issues/57841

**Special notes for your reviewer**:
Better take gracePeriodSeconds from pod settings, but need change a lot of code for this.

**Release note**:
```release-note
   Add ipvs proxier graceful termination delay.
```

@jsravn 👁  @m1093782566 👀

### CODE REVIEW

**Comment by sergeylanzman** [comment]
@m1093782566 If it's the right way? Can I continue?

**Comment by jhorwit2** [comment]
From the original issue:

>  (that should be greater than any pod's graceful termination time).

IMO, that's a very important requirement because right now this will drop connections for anyone with long running connections that take a while to shutdown. A global value like this requires managed services/cluster admins to know the max time needed or just set something really high, probably way higher than a minute, just to be safe.

**Comment by jsravn** [comment]
60s is probably safe because this is the connection tracking timeout that the iptables proxier sets, IIRC (may be wrong - it might be 300s). Technically that is wrong as well, for some niche use cases. We probably need an overall better approach across the proxiers for dealing with grace periods - some sort of callback / trigger mechanism that is invoked when a connection should be flushed, that is then implementation specific.

**Comment by jhorwit2** [comment]
@jsravn here are the defaults as of 1.10

```
Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
```

**Comment by jsravn** [comment]
Oh so it's quite large - 1 day. So the IPVS timeout needs to be quite big too, unless we are able to get a hold of the grace periods.

**Comment by sergeylanzman** [comment]
We can set large timeout, but it's risky, because today we can schedule in memory task for this. If kube proxy restarted destination stuck with Weight 0 until next sync.
I think it's big issue, ipvs not ready for production microservices environment without grace termination. Each action with pods dangers, deploy, scale down, drain...

**Comment by jsravn** [comment]
A simple approach would be if kube-proxy is restarted it will reschedule removal tasks for any servers with weight 0.

**Comment by jhorwit2** [comment]
I'm not super familiar with IPVS so sorry if this isn't valid, but doesn't IPVS expose connection stats per service/server? So, couldn't we rely on on the kernel to timeout established connections like we do with iptables, then have kube-proxy set the weight to 0 and just remove servers as they zero out on connections? Then all we need is a single goroutine that's checking the servers every interval with weight 0. 

I worry about the current approach since a goroutine per endpoint could potentially cause a lot of goroutines in a large cluster with a lot of pod churn. Also, if kube-proxy restarts frequently enough (say a cluster has automated server restarts for xyz reason like with [kured](https://github.com/weaveworks/kured)) then you run the risk of those goroutines growing even more even though after a server restart the connections are gone, but kube-proxy doesn't know.

**Comment by jsravn** [comment]
@jhorwit2 I think that's the better approach. You'll want to wait for both active and inactive to go to 0 (inactive for UDP). Default timeouts are: 
```
$ ipvsadm -l --timeout
Timeout (tcp tcpfin udp): 900 120 300
```

I'm not sure if there are any pathological cases where they may never go to 0. For direct routing/tunnel modes, which I'm most familiar with, the connection tracking values can't be trusted. For NAT mode which I believe kube-proxy uses, these values should be accurate.

I suppose it is possible a client could keep sending a UDP packet, like for a DNS lookup, on the same socket over and over. You would hope the client would retry the connection if it fails though. I think there was a fix in the iptables proxier to explicitly handle this case (by force flushing UDP connections imnmediately), but I'm not sure that was the right approach since it breaks graceful shutdown.

**Comment by m1093782566** [comment]
I am going to close this PR as we have already supported graceful termination for IPVS proxier.

**Pull request closed without merging**
