### PR TITLE
Update dependencies in local node test runner

### PR DESCRIPTION
**Pull request by hasheddan**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Updates comment on building dependencies step in the local node test
runner to reflect the binaries that are actually produced.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

#### Which issue(s) this PR fixes:

n/a

#### Special notes for your reviewer:

We previously built etcd / apiserver / etc. prior to statically linking into a single binary in https://github.com/kubernetes/kubernetes/issues/30174.

I'll likely follow this up by conditionally building the `mounter` binary as it is not needed for local runs.

/assign @Random-Liu 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by ehashman — COMMENTED** [review]
/triage accepted
/lgtm
/priority backlog

**Comment by ehashman** [comment]
/milestone v1.21

Discussed at 2021-03-17 Node CI meeting for test freeze.

**Comment by SergeyKanzhelev** [comment]
> /approve

@mrunalp can you pls re-approve, bot has failed to react

**Pull request merged**
