### PR TITLE
Fix sync pod log format

### PR DESCRIPTION
**Pull request by kebe7jun**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
More clear logs.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by kebe7jun** [comment]
CLA signed!

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/ok-to-test

Congrats on your first commit :)

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
