### PR TITLE
Pod proxy, portforward and exec subresources

### PR DESCRIPTION
**Pull request by csrwng**
Adds the following subresources to pods:
    /pods/&lt;pod-name&gt;[:port]/proxy
    /pods/&lt;pod-name&gt;/exec?container=&lt;container&gt;&command=&lt;cmd&gt;
    /pods/&lt;pod-name&gt;/portforward
or
    /namespaces/&lt;ns&gt;/pods/&lt;pod-name&gt;[:port]/proxy
    /namespaces/&lt;ns&gt;/pods/&lt;pod-name&gt;/exec?container=&lt;container&gt;&command=&lt;cmd&gt;
    /namespaces/&lt;ns&gt;/pods/&lt;pod-name&gt;/portforward

### CODE REVIEW

**Comment by csrwng** [comment]
@smarterclayton @bgrant0607 pls take a look

**Comment by smarterclayton** [comment]
What code supports "pods/name:port/proxy"?  Questionable having port in the name field.

**Comment by csrwng** [comment]
> What code supports "pods/name:port/proxy"? Questionable having port in the name field.

The existing pod.ResourceLocation function https://github.com/csrwng/kubernetes/blob/150db22d7ad173b073fc0276fa93bcac8f032d59/pkg/registry/pod/rest.go#L153
I think we chatted about this one and couldn't come up with a better place to have the port since the rest of the path and the parameters should be passed back to the pod.

**Comment by smarterclayton** [comment]
Gah.  Ok.

**Comment by csrwng** [comment]
comments addressed except for one with a question above.

**Comment by csrwng** [comment]
comment wording fixed

**Comment by smarterclayton** [comment]
LGTM, will merge in morning

**Pull request merged**
