### PR TITLE
Change non-quantity strings to sort alphanumerically, instead of using "Natural Sort"

### LINKED ISSUE #1517: Incorrect ordering in --sort-by
**What happened**:

Pods are not sorted in the correct order when using `--sort-by .metadata.name`

**What you expected to happen**:

Pods are sorted correctly, `1..35` followed by `a..z`

**How to reproduce it (as minimally and precisely as possible)**:

I think this bug is long standing. Repro as follows

```bash
for n in {a..z} ; do kubectl run $n --image=nginx:alpine ; done
for n in {1..35} ; do kubectl run $n --image=nginx:alpine ; done 

kubectl get po --sort-by=.metadata.name 
```

Pods `u`, `m`, `n`, `k` come out first in the order and in that order.

**Anything else we need to know?**:

I have traced this to here

https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/get/sorter.go#L276

These pod names are incorrectly being identified as SI quantities, when without a numerical quantity they should be treated as plain strings. Having said that, a pod name is *never* an SI quantity, so perhaps this logic should only be used for fields where a quantity can be expected.

**Environment**:
-   Client Version: v1.28.1
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    Server Version: v1.28.1

- Killercoda playground, although as mentioned I think this is long standing
- Ubuntu 20.04 LTS

### LINKED ISSUE #1574: `kubectl --sort-by=.metadata.uid` should not use natural sort
### What happened?

After doing `kubectl get pod -A --sort-by=.metadata.uid` I realized the pods were not ordered by `uid`

### What did you expect to happen?

All the pods of the cluster being ordered by `uid`

### How can we reproduce it (as minimally and precisely as possible)?

The following screenshot shows the result of the commands trying to order the pods:
kubectl--sort-by

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2

$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"29", GitVersion:"v1.29.2", GitCommit:"4b8e819355d791d96b7e9d9efe4cbafae2311c88", GitTreeState:"clean", BuildDate:"2024-02-14T10:39:04Z", GoVersion:"go1.21.7", Compiler:"gc", Platform:"linux/amd64"}

$ kubelet --version
Kubernetes v1.29.2
```

</details>

### Cloud provider

<details>

No cloud provider. Installation done in two virtual machines (i.e., control plane and worker) using virtualbox

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux control-plane-server 5.4.0-173-generic kubernetes/kubernetes#191-Ubuntu SMP Fri Feb 2 13:55:07 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd containerd.io 1.6.28 ae07eda36dd25f8a1b98dfbf587313b99c0190bb
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by brianpursley**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
"Natural Sorting" is non-intuitive. Quantity is already handled by a special case, so all non-quantity strings should be sorted alphanumerically, which is what users expect strings to be sorted by.

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubectl/issues/1574
Fixes https://github.com/kubernetes/kubectl/issues/1517

#### Special notes for your reviewer:
Because this PR gets rid of natural sorting, it eliminates a dependency.

#### Does this PR introduce a user-facing change?
```release-note
Fixed bug where kubectl get with --sort-by flag does not sort strings alphanumerically.
```

### CODE REVIEW

**Comment by ardaguclu** [comment]
I agree that default sorting mechanism is intuitive and there is no point of relying on an external library for this;
/lgtm

**Comment by brianpursley** [comment]
/assign @soltysh 

Need someone from @kubernetes/dep-approvers to approve the removal of github.com/fvbommel/sortorder dependency.

**Comment by cblecker** [comment]
/approve
for dep removal

**Pull request merged**
