### PR TITLE
Stop requiring meta.Object for clientsets

### PR DESCRIPTION
**Pull request by skitt**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

The generic-based generator introduced in
https://github.com/kubernetes/kubernetes/pull/121439 requires that all types used with the generated clients implement both runtime.Object and meta.Object. It turns out that projects outside Kubernetes use this with types implementing only runtime.Object.

Since meta.Object is only required for Update() and UpdateStatus(), this relaxes the type parameter to only runtime.Object and changes Update() and UpdateStatus() to retrieve the meta information using meta.Accessor().

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Relaxed requirements on types in the client-go clientset generator: `meta.Object` is no longer required everywhere, only for `Update()` and `UpdateStatus()`.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sftim** [comment]
Changelog suggestion
```diff
-Relax the requirements on types in the client-go clientset generator: meta.Object is no longer required everywhere, only for Update() and UpdateStatus().
+Relaxed requirements on types in the client-go clientset generator: `meta.Object` is no longer required everywhere, only for `Update()` and `UpdateStatus()`.
```

**Comment by skitt** [comment]
> Changelog suggestion

Applied, thanks @sftim!

**Comment by aojea** [comment]
> It turns out that projects outside Kubernetes use this with types implementing only runtime.Object.

This has the benefit of detecting problems at compile time, so it seems making stricter for kubernetes types is ok ... is not easy for the other projects to adapt that extending the surface area of client-go? the leaner the better IMHO

**Comment by skitt** [comment]
> > It turns out that projects outside Kubernetes use this with types implementing only runtime.Object.
> 
> This has the benefit of detecting problems at compile time, so it seems making stricter for kubernetes types is ok ... is not easy for the other projects to adapt that extending the surface area of client-go? the leaner the better IMHO

In OpenShift (which is the project where this issue showed up), the project has indeed adapted to this change. Ultimately I agree that enforcing meta.Object makes things more consistent. My concern around this was that it is a sudden additional requirement for end users of client-go, but it seems to not have caused much fuss.

**Pull request closed without merging**
