### PR TITLE
Fix golint failure in pkg/util/labels (take 2)

### PR DESCRIPTION
**Pull request by ZP-AlwaysWin**
**What type of PR is this?**

> /kind cleanup

**What this PR does / why we need it**:
This fixes golint failures of the following file:

-  pkg/util/labels

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```
None
```

### CODE REVIEW

**Comment by ZP-AlwaysWin** [comment]
/assign @spiffxp

hi @spiffxp 

I redo this PR so it contains just my commit. #80095

The reason why I deleted this .readonly file is that I don't think it's useful. Deleting this .readonly 
 file has no effect on running. I think it was submitted by mistake and uploaded by mistake. And the upload time of this file is longer, I guess the original author also forgot whether to upload the file and the role of the file.

Since you are not sure whether you should delete it or not, this time I retained it and only corrected the error about fixing golint failure.

please review my code again.

Best Wishes.

**Comment by spiffxp** [comment]
/retitle Fix golint failure in pkg/util/labels (take 2)
/kind cleanup
/priority important-longterm
/sig api-machinery

I'm closing https://github.com/kubernetes/kubernetes/pull/80095 in favor of this

My point with asking about the `.readonly` file is to confirm:
- whether we are ok making changes to this directory at all (maybe the file signified we shouldn't; the only changes made here since that PR were bazel changes)
- whether the file can be safely removed

/assign @smarterclayton 
(earlier ask: https://github.com/kubernetes/kubernetes/pull/80095#issuecomment-514876875)
I still need that answered before we can proceed

**Comment by neolit123** [comment]
looks like there is hack/verify-readonly-packages.sh script, but it's not run as part of CI, as far as i can tell:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-testing/verify.yaml#L138-L139

the reason for this script was here:
https://github.com/kubernetes/kubernetes/issues/39528
> We create a verify script to prevent updates to "mirror" packages in k8s.io/kubernetes

and introduced here:
https://github.com/kubernetes/kubernetes/pull/39612

**Comment by spiffxp** [comment]
Thanks for the additional context @neolit123 

/assign @sttts 
maybe you can help answer whether we should allow changes here, or close in favor of leaving as readonly?

**Comment by spiffxp** [comment]
/assign @krzyzacy 
I'm trying to track down why we disabled readonly checks (ref: https://github.com/kubernetes/test-infra/pull/10679#discussion_r247267980) do you remember why?

**Comment by spiffxp** [comment]
... and now pull-kubernetes-verify is failing with
```
Found pkg/util/labels/.readonly, but files changed compared to "master" branch.
```

did someone re-enable the readonly check?

**Comment by ZP-AlwaysWin** [comment]
> ... and now pull-kubernetes-verify is failing with
> 
> ```
> Found pkg/util/labels/.readonly, but files changed compared to "master" branch.
> ```
> 
> did someone re-enable the readonly check?

hi @spiffxp 

the .readonly is empty and I don't change the file. if delete the file, it will success to "/test pull-kubernetes-verify"。 but，I not sure whether you should delete it or not

**Comment by smarterclayton** [comment]
This whole package should just be removed and anything still in use should be moved to meta/v1.  This is all lazy code that can be easily implemented inline with private methods.

**Review by fejta — APPROVED** [review]
/lgtm
/approve

**Comment by spiffxp** [comment]
/lgtm cancel
/approve cancel
/close
Per @smarterclayton's comment above, the `.readonly` file is there for a reason: a reminder that we shouldn't be changing this code.  Anything that uses this code should be using meta/v1 code instead.

**Pull request closed without merging**
