### PR TITLE
Create fewer pods in Scheduler Predicates e2e test to speed things up.

### PR DESCRIPTION
**Pull request by ghost**
This test was previously creating large numbers of pods (100 per node in the standard configuration), just to reserve all of the CPU resources in the cluster.  This made it very slow (~8 min duration).  With this PR we create a smaller number of larger pods, to speed things up.

### CODE REVIEW

**Comment by quinton-hoole** [comment]
The build failure at 11:20 today looks like a flake.  Lets see how the next run does...

**Comment by quinton-hoole** [comment]
Aah yes, it looks like it passed just fine:
SUCCESS! -- 84 Passed | 0 Failed

**Comment by gmarek** [comment]
Thanks!

**Comment by alex-mohr** [comment]
@quinton-hoole fyi, from https://travis-ci.org/kubernetes/kubernetes/builds/77725196
"""pkg/expapi is out of date. Please run hack/update-generated-conversions.sh"""

**Comment by gmarek** [comment]
@alex-mohr - this looks like a problem with travis/shippable to me (or a bug in the head at the time). This PR doesn't touch API at all, so conversions should be unchanged. I'll rerun tests.

**Comment by quinton-hoole** [comment]
That e2e failure is interesting.  That test has not failed at all recently (no signs of flakyness), yet this PR changes nothing that could introduce an error in that area.  No endpoints for the created service become visible.  The specific error is:

```
Sep  1 05:44:01.811: INFO: Service rm2 in namespace e2e-tests-kubectl-z77sr found.
Sep  1 05:44:01.817: INFO: No endpoint found, retrying
...
• Failure [86.140 seconds]
Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:631
  Kubectl expose
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:392
    should create services for rc [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:391

    Sep  1 05:45:01.858: 1 endpoint is expected
```

**Comment by quinton-hoole** [comment]
The test that is failing is:

Services 
[It] should create services for rc
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:391

**Comment by quinton-hoole** [comment]
@k8s-bot test this again please

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
Jenkins failure is a flake:
   should be able to up and down services

@k8s-bot test this please

**Comment by wojtek-t** [comment]
cluster didn't started correctly

@k8s-bot test this please

**Comment by gmarek** [comment]
It still looks like problem in the head.

@k8s-bot test this please

**Comment by gmarek** [comment]
This is certainly a problem in the head - I got exactly the same failure in completely unrelated PR.

**Comment by wojtek-t** [comment]
Services should be able to up and down services is a known issue: #13478

**Comment by quinton-hoole** [comment]
@k8s-bot test this again please

**Comment by quinton-hoole** [comment]
@k8s-bot test this please

**Comment by quinton-hoole** [comment]
GCE e2e test failure probably due to #13534, which is now fixed. Rerunning...
@k8s-bot please test this again

**Comment by quinton-hoole** [comment]
If all goes according to plan, the merge-bot will auto-merge this if the e2e tests pass this time.

**Comment by quinton-hoole** [comment]
e2e test failure was due to #13534.  Retrying to trigger auto-merge by merge-bot.
@k8s-bot test this again please

**Comment by quinton-hoole** [comment]
The build timed out while cleaning up.  Tests are sometimes taking more than the configured 30 minutes these days.  I'll up the timeout temporarily, and work on reducing the elapsed time of the parallel tests.

**Comment by quinton-hoole** [comment]
```build/make-clean.sh
+++ [0903 17:30:10] Verifying Prerequisites....
+++ [0903 17:30:11] Cleaning out _output/dockerized/bin/ via docker build image
+++ [0903 17:30:11] Running build command....
+++ [0903 17:30:14] Removing data container
+++ [0903 17:30:27] Cleaning out local _output directory
+++ [0903 17:30:28] Deleting docker image kube-build:build-ce7487f5b2
Build timed out (after 30 minutes). Marking the build as aborted.
Build timed out (after 30 minutes). Marking the build as failed.
make: *** wait: No child processes.  Stop.
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.
Build was aborted
```

**Comment by quinton-hoole** [comment]
Timeout increased  from 30 to 45 minutes.

@k8s-bot test this again please

**Comment by gmarek** [comment]
Known service flake.
@k8s-bot ok to test

**Comment by gmarek** [comment]
@k8s-bot test this again please

**Pull request merged**
