### PR TITLE
[Trival] beta.kubernetes.io/os deprecated since v1.14, are targeted for removal in v1.18

### PR DESCRIPTION
**Pull request by wawa0210**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
beta.kubernetes.io/os deprecated since v1.14, are targeted for removal in v1.18

**Does this PR introduce a user-facing change?**:

```release-note
change beta.kubernetes.io/os  to kubernetes.io/os
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#beta-kubernetes-io-os-deprecated
```
/assign @michmike

### CODE REVIEW

**Comment by michmike** [comment]
cc: @adelina-t

**Comment by wawa0210** [comment]
https://github.com/kubernetes/kubernetes/issues/89477

**Review by michmike — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
