### PR TITLE
Update go.etcd.io/bbolt to v1.3.5

### PR DESCRIPTION
**Pull request by justaugustus**
Signed-off-by: Stephen Augustus <saugustus@vmware.com>

**What type of PR is this?**

/kind cleanup
/area dependency

**What this PR does / why we need it**:

Unblocks go1.14 upgrade in https://github.com/kubernetes/kubernetes/pull/88638.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Update go.etcd.io/bbolt to v1.3.5
```

### CODE REVIEW

**Comment by justaugustus** [comment]
Ready for top-level approval:

/assign @liggitt @wojtek-t @thockin
/cc @jpbetz @wenjiaswe @jingyih

**Comment by wojtek-t** [comment]
@ptabor - FYI

**Comment by liggitt** [comment]
vendor mechanics lgtm

cc @jpbetz 

I'd like to see etcd be happy with this level of bbolt (xref https://github.com/etcd-io/etcd/pull/12047)

**Comment by jpbetz** [comment]
> /hold for green etcd CI and merge of this bbolt level

+1. We need this to be green. I've restarted the functional test for the etcd build: https://travis-ci.com/github/etcd-io/etcd/builds/172478655.

**Comment by jpbetz** [comment]
etcd is now green

**Comment by justaugustus** [comment]
/hold cancel
(now that https://github.com/etcd-io/etcd/pull/12047 has merged)

**Pull request merged**
