### PR TITLE
Fix type for DaemonSet informer

### PR DESCRIPTION
**Pull request by ncdc**
cc @mml @davidopp @bgrant0607 @kubernetes/rh-cluster-infra

### CODE REVIEW

**Comment by pweil-** [comment]
LGTM

**Comment by davidopp** [comment]
LGTM

THANK you for fixing this!

@mml I guess the reason the test didn't catch this relates to the thing we were discussing about the test, where the DaemonSets were inserted manually?

**Comment by davidopp** [comment]
@mml Can you add some kind of test that would have caught this?

**Comment by ncdc** [comment]
I was wondering about tests, but honestly I'm just as swamped as the rest of you all right now, so I figured I'd get this in as-is for now.

**Comment by davidopp** [comment]
Yeah I was hoping @mml could add some kind of test for it.

**Comment by ncdc** [comment]
@k8s-bot e2e test this github flake: 21467

**Comment by mml** [comment]
I'll think about a test, but I also want to address that the interface could be better to discourage this.

Instead of burying the type...

```go
  nc.daemonSetStore.Store, nc.daemonSetController = framework.NewInformer(                                                                                                                             
    &cache.ListWatch{
      ListFunc: func(options api.ListOptions) (runtime.Object, error) {
        return nc.kubeClient.Extensions().DaemonSets(api.NamespaceAll).List(options)
      },  
      WatchFunc: func(options api.ListOptions) (watch.Interface, error) {
        return nc.kubeClient.Extensions().DaemonSets(api.NamespaceAll).Watch(options)
      },  
    },  
    &api.Node{},
    controller.NoResyncPeriodFunc(),
    framework.ResourceEventHandlerFuncs{},
  )
```

we could put it up front and all on its own, where it would be if this was a C++ template

```go
  nc.daemonSetStore.Store, nc.daemonSetController = framework.InformerMaker(&extensions.DaemonSet).New(
    &cache.ListWatch{
      ListFunc: func(options api.ListOptions) (runtime.Object, error) {
        return nc.kubeClient.Extensions().DaemonSets(api.NamespaceAll).List(options)
      },                                                                                                                                                                                               
      WatchFunc: func(options api.ListOptions) (watch.Interface, error) {
        return nc.kubeClient.Extensions().DaemonSets(api.NamespaceAll).Watch(options)
      },
    },
    controller.NoResyncPeriodFunc(),
    framework.ResourceEventHandlerFuncs{},
  )
```

**Comment by mml** [comment]
@ncdc how did you notice this?

**Comment by ncdc** [comment]
@mml I created a DaemonSet

**Comment by mml** [comment]
And then the API server crashes?  Hard to believe we have no e2e test that creates a DaemonSet, but thanks.  Seems easy enough to add.

**Comment by ncdc** [comment]
@mml it doesn't crash. It just logs an error that the reflector was expecting a Node but got a DS

**Pull request merged**
