### PR TITLE
Remove redundant code in kubectl top pod

### PR DESCRIPTION
**Pull request by syswu**
#### What this PR does / why we need it:

when invoke 'kubectl top pod',  we found the last three lines are  redundant.

```
        ...
        metrics, err := getMetricsFromMetricsAPI(o.MetricsClient, o.Namespace, o.ResourceName, o.AllNamespaces, selector)
	if err != nil {
		return err
	}

	// First we check why no metrics have been received.
	if len(metrics.Items) == 0 {
		// If the API server query is successful but all the pods are newly created,
		// the metrics are probably not ready yet, so we return the error here in the first place.
		e := verifyEmptyMetrics(o, selector)
		if e != nil {
			return e
		}
                ....
	}

	if err != nil {
		return err
	}
```

/kind bug

### CODE REVIEW

**Comment by BenTheElder** [comment]
for future reference:

https://github.com/kubernetes/kubernetes/pull/99062#issuecomment-778627224 you're getting the `do-not-merge/release-note-label-needed`label on your PRs because you removed that part of the PR template, we have release automation that consumes this and merge automation that requires not having this label.

for PRs like this:

    ```release-note
    NONE
    ```

in the PR body / initial PR comment

in this case where no note is necessary, we can instead use
/release-note-none

and you also have the `do-not-merge/needs-kind` label for skipping the template instructions to label the PR with one of the kinds (bug, cleanup, etc.)

/kind cleanup

**Comment by rikatz** [comment]
Nit alert: Maybe you can also change the var name before [here](https://github.com/kubernetes/kubernetes/blob/80e725597be181a63a58619ad42031278827cf21/staging/src/k8s.io/kubectl/pkg/cmd/top/top_pod.go#L187-L189) 

So instead of using e := lala, use err := and always return err :D

**Comment by syswu** [comment]
@rikatz, I have updated the codes on your suggestion :)

**Comment by syswu** [comment]
Why we get different results using the same cases running several times?

**Comment by BenTheElder** [comment]
> Why we get different results using the same cases running several times?

Some of these cases run against test clusters that are provisioned during the test and the actual live distributed behavior of the cluster is not deterministic, exposing flakiness in the implementation or the tests.

**Comment by rikatz** [comment]
/lgtm
/retitle Remove redundant code in kubectl top pod
Thanks!

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
