### PR TITLE
vsphere: improve logging message on node cache refresh event

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kim.andrewsy@gmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
The logging message "secret added" and "secret updated" is ambiguous and not very helpful, update the log message to indicate that the node cache is being refreshed when an event is received for the Secret resource containing vCenter information.

The original log line was added in https://github.com/kubernetes/kubernetes/pull/90836 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
vsphere: improve logging message on node cache refresh event
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
@andrewsykim wanna backport this please?

**Comment by andrewsykim** [comment]
Opened one for v1.19, thanks for the ping @dims

**Comment by cpanato** [comment]
@andrewsykim @dims this backport is only for 1.19 or do we need to apply for 1.18 / 1.17 as well? thanks

**Comment by andrewsykim** [comment]
@cpanato I don't think so since the original PR introducing the log line merged for v1.19 only https://github.com/kubernetes/kubernetes/pull/90836

**Comment by cpanato** [comment]
thank you for your clarification @andrewsykim

**Pull request merged**
