### PR TITLE
Fix missing gitMajor/gitMinor values.

### PR DESCRIPTION
**Pull request by david-mcmahon**
ref #55353

### CODE REVIEW

**Comment by ixdy** [comment]
why is this needed?

**Comment by david-mcmahon** [comment]
I don't see those used anywhere that hack/lib/version.sh shouldn't cover, but I wanted to be sure.  
Ask your question in the form of a PR.   If we're 100% free of all the values set in base.go, then let's close this.

**Comment by enisoc** [comment]
Does this need to be a cherrypick even though we're still in branchff mode?

**Comment by david-mcmahon** [comment]
I'm thinking now that it isn't even needed as @ixdy pointed out.  I'm further wondering why base.go is needed at all anymore if these values are now all handled within the build scripts (substituted on archive) and passed as LDFLAGS.

**Comment by ixdy** [comment]
Everything in `pkg/version/base.go` gets overridden at build time:
Non-bazel: https://github.com/kubernetes/kubernetes/blob/master/hack/lib/version.sh#L143-L167

Bazel: https://github.com/kubernetes/kubernetes/blob/c98aabccb0599bed84ff04dbda2996c421f57139/pkg/version/def.bzl#L11-L18

**Comment by david-mcmahon** [comment]
I'm pretty sure -X lets you define uninitialized variables from -ldflags.  Might be an opportunity to delete more unnecessary code.

**Comment by david-mcmahon** [comment]
Either way, I guess this PR is not needed.  Closing.

**Pull request closed without merging**
