### PR TITLE
Remove deprecated NodeLegacyHostIP

### PR DESCRIPTION
**Pull request by NickrenREN**
**Release note**:
```release-note
Remove deprecated node address type `NodeLegacyHostIP`.
```

ref #44807

### CODE REVIEW

**Comment by caesarxuchao** [comment]
The changes lgtm. @liggitt could you also take a look? Thanks.

**Comment by caesarxuchao** [comment]
@NickrenREN why is the PR marked "WIP"?

**Comment by NickrenREN** [comment]
@caesarxuchao  Sorry. I first added 'WIP' and forgot to remove it. 
Removed

**Comment by NickrenREN** [comment]
@k8s-bot kops aws e2e test this

**Comment by NickrenREN** [comment]
@smarterclayton  This pr needs your approval

**Pull request merged**
