### PR TITLE
Add irfanurrehman as approver for federation.

### PR DESCRIPTION
**Pull request by ghost**
**Release note**:

```NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
Hey all,

Sorry to intrude, but I feel obligated to ask ... what is the status of this tree moving out of the k/k repo?  We've all said "yeah yeah" for quite a long time.  I think all of the big deps have been moved out - util, api, apimachinery, etc.  We're in the process of moving more significant things out of tree, too.

I'd like to propose that we put a moratorium on big changes here (including approvers) until we have a concrete plan and timeline for getting this out.  Your lives will be better once it is out, too.

@smarterclayton @brendandburns @jbeda @bgrant0607

**Comment by quinton-hoole** [comment]
@thockin, yes agreed, the move out of the main repo is long overdue.  @madhusudancs recently made an effort estimate at 2 engineer months. We discussed this today and decided to staff it immediately (realistically in the next week or two)
Adding the additional approver is intended to speed up this process, rather than slow it down.  While I understand your (presumed) motivation to speed up the migration out of the repo by putting a moratorium on changes until it's done, but in this case I think that adding this approver will help to speed it up.  Make sense?

**Comment by brendandburns** [comment]
+1m

It never should have been in here in the first place...

--brendan

________________________________

**Comment by quinton-hoole** [comment]
@brendanburns FWIW, the main reason it was put here in the first place was because APi machinery was not yet in a state to put it in a separate repo, so that SIG suggested that we put it here until they had their house in order (which it now is, as I understand).

**Comment by thockin** [comment]
I'm ok to add an approver, as the goal is move out.  Sounds like a plan.

**Comment by quinton-hoole** [comment]
@csbell ping for approval.

**Comment by spiffxp** [comment]
/lgtm
needs to be added to v1.8 milestone if you need to get this merged prior to code freeze being lifted

**Pull request merged**
