### PR TITLE
Release 0.18.0

### PR DESCRIPTION
**Pull request by j3ffml**
Rolled up from 17f6f86be688a415b50b0ae627f1695032a06969.

### CODE REVIEW

**Comment by jlowdermilk** [comment]
Do not merge. Will re-cut after #8833 is in to fix gke-e2e runs.

**Comment by bgrant0607** [comment]
cc @thockin @quinton-hoole re. other e2e failures.

**Comment by bgrant0607** [comment]
In addition to outstanding e2e failures, we have a backlog of 28 PRs with lgtm, which include the last v1beta1-to-v1beta3 conversions, the last v1 service API change, and some significant kubectl command (run, scale, exec) changes. I'd like to postpone the 0.18 cut until we get these in. In particular, we want to have a release with full v1beta3 support before we rip out v1beta1 and v1beta2. 0.18 was expected to be that release, but the merge freeze interfered with that plan.

cc @caesarxuchao @krousey

**Comment by jlowdermilk** [comment]
e2e is stable again. re-cut release from 17f6f86be688a415b50b0ae627f1695032a06969. PTAL

**Comment by roberthbailey** [comment]
LGTM. 

@bgrant0607 I believe all of the v1beta3 PRs have been merged prior to the v0.18.0 tag.

**Comment by jlowdermilk** [comment]
cc @vishh
gke-ci is still a bit flaky (it was broken overnight by #8740), but I'd still like to get this in today so we can get more test coverage over the weekend.

**Comment by bgrant0607** [comment]
Yes, thanks. Please cut the release. v1beta1 and v1beta2 will be ripped out first thing Monday morning.

**Comment by bgrant0607** [comment]
What was the gke-ci breakage due to, specifically? The env. var. change, flag change, salt change, ...?

**Comment by jlowdermilk** [comment]
The envvar change broke gke-ci. Robby fixed this morning.

**Comment by jlowdermilk** [comment]
Can has merge?

**Pull request merged**
