### PR TITLE
Promote SataQiu to an approver of test and test/e2e/framework

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
I volunteered to be an approver of `test` and `test/e2e/framework`!

Recently, based on my discussion with @oomichi, I opened an issue about test e2e sub framework refactoring(https://github.com/kubernetes/kubernetes/issues/86052). I have received some feedback and many volunteers are willing to help with this. If I can approve these PRs about test framework  refactoring, maybe we can move this forward more quickly.

In fact, I think we still have a lot of work to do about test e2e framework(such as simplify the framework and keep only the core common functions, resolving cyclic dependencies). I believe we need more reviewers/approvers to move it forward. And I'm willing to help with this.

I have been a reviewer of `test` and `test/e2e/framework` about 8 months now, and is an active contributor/reviewer. I promise to make sure to use the power wisely.

Really hope to get your support to make Kubernetes better.

/assign @fejta @oomichi

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by fejta — APPROVED** [review]
/lgtm
/approve
/hold
For lazy consensus

**Comment by neolit123** [comment]
/lgtm
thanks for the contributions @SataQiu

**Comment by BenTheElder** [comment]
/lgtm
/approve
Thanks for your contributions!

**Comment by SataQiu** [comment]
Thanks all for your support @fejta @neolit123 @BenTheElder @oomichi !

**Pull request merged**
