### PR TITLE
Cherry pick of #28850 for flake #26210

### PR DESCRIPTION
**Pull request by MHBauer**
cherry-pick of #28850 onto release 1.3 to hopefully help with toning down flake #26210.

It seems to help. @sttts 

Please advise me on the appropriate way to have this applied to the down-level release if this is inappropriate.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31454)

### CODE REVIEW

**Comment by MHBauer** [comment]
See https://github.com/kubernetes/kubernetes/issues/26210#issuecomment-240233110 & https://github.com/kubernetes/kubernetes/issues/26210#issuecomment-240362893 for reasoning.

**Comment by ixdy** [comment]
seems fine to me. we generally prefer folks to use the `hack/cherry_pick_pull.sh` script to generate these PRs, though.

**Comment by ixdy** [comment]
ok to test

**Comment by MHBauer** [comment]
My bad, I can re-do it if you want. I don't want to cause an issue in the future.

**Comment by sttts** [comment]
lgtm. @ixdy who approves cherry picks?

**Pull request merged**
