### PR TITLE
Replaced dead links in Guestbook README

### LINKED ISSUE #24373: Dead Links in Guestbook Example
In the [README for the guestbook example](https://github.com/kubernetes/kubernetes/blob/release-1.2/examples/guestbook/README.md#step-one-start-up-the-redis-master), the line `Before continuing to the gory details, we also recommend you to read Quick walkthrough, Thorough walkthough and Concept guide.` appears to contain several dead links.

### PR DESCRIPTION
**Pull request by mgoodness**
fixes #24373

[Analytics]()

### CODE REVIEW

**Comment by mgoodness** [comment]
I signed it!

**Comment by bgrant0607** [comment]
Thanks. LGTM

**Comment by wojtek-t** [comment]
@mgoodness 

FAIL: changes needed but not made due to --verify
/go/src/k8s.io/kubernetes/examples/ is out of date. Please run hack/update-generated-docs.sh
FAILED   ./hack/../hack/verify-generated-docs.sh	73s

**Comment by wojtek-t** [comment]
@mgoodness 

FAIL: changes needed but not made due to --verify
/go/src/k8s.io/kubernetes/examples/ is out of date. Please run hack/update-generated-docs.sh
FAILED   ./hack/../hack/verify-generated-docs.sh	73s

Can you please fix?

**Pull request closed without merging**
