### PR TITLE
Add default when latest not claimed

### PR DESCRIPTION
**Pull request by resouer**
Fixes: #8841 
Part of: #15634

Details:
1. When user does not provide tag, they always assumed it to be latest. 
2. rkt & docker shows inconsistency in this case

### CODE REVIEW

**Comment by resouer** [comment]
@dchen1107 Re-based, please review whenever you have time

**Comment by resouer** [comment]
cc @yujuhong

**Comment by pmorie** [comment]
@k8s-bot ok to test

**Comment by pmorie** [comment]
@k8s-bot add to whitelist

**Comment by resouer** [comment]
Do not review ... I'm looking at the error

**Comment by resouer** [comment]
CI fixed, can anyone from Node team look at this? ping @yujuhong

**Comment by resouer** [comment]
CI fixed, can any one from node team look at this? ping @yujuhong

**Comment by pmorie** [comment]
@yifan-gu This doesn't seem like it's going to place nice with rkt images, which are just URLs IIRC.  Thoughts?

**Comment by yifan-gu** [comment]
@pmorie Thanks for the heading up :)
rkt is only using the docker images now, so it doesn't matter. For rkt images(ACI), it supports pure http/https URL, such as `http://example.com/foo.aci`, as well as the discovery URL, such as `example.com/foo`. For the later, if there is no tags, then it assumes `latest` as well. so `example.com/foo` = `example.com/foo:latest`.

BTW, I am working on a proposal for adding more support for other image format [here](https://github.com/yifan-gu/kubernetes/commit/ceafce7738729822ddbb1f4e25d88c4a755b723e)

cc @jonboulle

**Comment by yujuhong** [comment]
LGTM. Thanks for fixing this! The default should be part of the api (i.e., image spec) if we change the api in the future. Given that we don't have that, the current approach seems fine.

**Comment by resouer** [comment]
May be need to re-run e2e

**Comment by yujuhong** [comment]
@k8s-bot test this

**Comment by gmarek** [comment]
@k8s-bot test this

**Pull request merged**
