### PR TITLE
Automated cherry pick of #15914

### PR DESCRIPTION
**Pull request by vishh**
Cherry pick of #15914 on release-1.1.

### CODE REVIEW

**Comment by vishh** [comment]
cc @dchen1107

**Comment by vishh** [comment]
@dchen1107: A cherry-pick of the commits in #15914 did not apply cleanly on the release-1.1 branch. I had to update the code manually. But the logic should still be the same.

**Comment by dchen1107** [comment]
LGTM

**Comment by wojtek-t** [comment]
Jenkins test flake:
"Job should run a job to completion when tasks sometimes fail and are not locally restarted"

@k8s-bot test this please

**Pull request merged**
