### PR TITLE
Code refactor for readability in `RunFilterPlugins`

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: Kante Yin <kerthcet@gmail.com>

#### What type of PR is this?
/sig scheduling
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/pull/114629#discussion_r1060869538

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by sanposhiho — APPROVED** [review]
/lgtm

**Review by sanposhiho — APPROVED** [review]
/lgtm

**Comment by kerthcet** [comment]
cc @Huang-Wei , this addressed the comment https://github.com/kubernetes/kubernetes/pull/114629#discussion_r1060869538

**Comment by Huang-Wei** [comment]
/approve

Thanks.

**Pull request merged**
