### PR TITLE
modify url https://github.com/kubernetes/autoscaler/releases/tag/1.12.0

### PR DESCRIPTION
**Pull request by timyinshi**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
modify url https://github.com/kubernetes/autoscaler/releases/tag/1.12.0 to https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.12.0

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
NONE
```

### CODE REVIEW

**Comment by tanjunchen** [comment]
@timyinshi
Please Squash your commits

**Comment by tanjunchen** [comment]
Ref:https://github.com/kubernetes/kubernetes/issues/85495

**Comment by timyinshi** [comment]
ok,thanks.

**Comment by timyinshi** [comment]
i will have a new pr

**Pull request closed without merging**
