### PR TITLE
kubectl top Documentation

### PR DESCRIPTION
**Pull request by serathius**
Adds documentation for kubectl top, describing current flow of metrics.
```release-note
NONE
```

### CODE REVIEW

**Comment by serathius** [comment]
\assign thkoch2001

**Comment by serathius** [comment]
cc @thkoch2001

**Comment by serathius** [comment]
I updated it so it reflect current state, where heapster is deprecated but still supported.

**Comment by tengqm** [comment]
Not sure if pkg/generated/bindata.go and translations/kubectl/template.pot need to be updated for patches like this.

**Pull request closed without merging**
