### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by xialonglee**
**What this PR does / why we need it**:
Fix typo.

### CODE REVIEW

**Comment by brendandburns** [comment]
@k8s-bot ok to test
/lgtm

**Comment by xialonglee** [comment]
Hi, @brendandburns , seems this PR needs a "release-note-none" label and remove the "do-not-merge" label, could you PTAL?

**Comment by brendandburns** [comment]
Done, sorry for the delay.

**Comment by xialonglee** [comment]
@brendandburns 
Oh.. the codes of kube-dns was remove to repo: kubernetes/dns ... close it and i would open same pr there...

**Pull request closed without merging**
