### PR TITLE
Delete pod_cache and rely on updating pod status by kublet.

### LINKED ISSUE #2947: Invalidate pod state cache before events from kubelet are propagated
Currently it can (sometimes) happen that when an event is observed in the `/api/v1beta1/watch/events` stream, the pod status that can be obtained by doing a GET on `/api/v1beta1/pods` is not yet updated and still shows the old value - for example it shows "Waiting" when the event of type "running" originating from the kubelet has already been received via the watched stream.

### PR DESCRIPTION
**Pull request by fgrzadkowski**
@davidopp @bgrant0607 @lavalamp 

This fixes #2947. It is also related to #2726

### CODE REVIEW

**Comment by davidopp** [comment]
LGTM

Am I correct in understanding that this is the last in the following sequence of PRs: #5205, #5555, #5624?

**Comment by davidopp** [comment]
Please check/fix test issue. (Shippable failed, Travis is just very slow right now.)

**Comment by fgrzadkowski** [comment]
@davidopp Yes, this is the last PR in the sequence (except that I think you've meant #5714 not #5624)

I checked shippable and it failed on some initial step not related with kubernetes itself (docker pull). I have restarted it - hopefully it'll be green this time.

**Comment by fgrzadkowski** [comment]
One of the shippable runs failed, the other succeeded. Looks like a flake, but I'll take a look tomorrow.

**Comment by fgrzadkowski** [comment]
FYI @bprashanth

**Comment by fgrzadkowski** [comment]
Rebased. e2e test passes.

**Comment by fgrzadkowski** [comment]
It seems there is a bug in integration tests #5872. I'm sending a separate PR to fix it.

**Pull request merged**
