### PR TITLE
[KEP-2876] Promote CRD validation rule to GA

### LINKED ISSUE #121164: [KEP-2876] Promote CRD validation rule to GA
### What would you like to be added?

This is the tracking issue of promoting CRD validation rules to GA: https://github.com/kubernetes/enhancements/issues/2876

Listed the blocking issues/features below:

- [x] https://github.com/kubernetes/kubernetes/issues/119511
- [x] https://github.com/kubernetes/kubernetes/issues/120226
- [x] https://github.com/kubernetes/kubernetes/issues/111445
- [x] https://github.com/kubernetes/kubernetes/issues/120821

Issues be aware of but should not be a GA blocker
- [ ] https://github.com/kubernetes/kubernetes/issues/120240 
- [ ] https://github.com/kubernetes/kubernetes/issues/120973
- [ ] https://github.com/kubernetes/kubernetes/issues/113220
- [ ] https://github.com/kubernetes/kubernetes/issues/121163
- [ ] https://github.com/kubernetes/kubernetes/issues/121162

### Why is this needed?

/sig api-machinery
/triage accepted

### PR DESCRIPTION
**Pull request by cici37**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
 Promote CRD validation rule to GA
#### Which issue(s) this PR fixes:

Fixes #121164 

#### Special notes for your reviewer:
This PR should be ready to merge after the issues below have been closed/merged:
- https://github.com/kubernetes/kubernetes/issues/119511
- https://github.com/kubernetes/kubernetes/issues/120226
- https://github.com/kubernetes/kubernetes/issues/111445
- https://github.com/kubernetes/kubernetes/issues/120821

#### Does this PR introduce a user-facing change?

```release-note
The CRD validation rule with feature gate `CustomResourceValidationExpressions` is promoted to GA.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/2876
```

### CODE REVIEW

**Comment by moficodes** [comment]
Hello @cici37 ! 👋🏼
Bug triage for the 1.29 release cycle is here!
This issue hasn't been updated for a long time, so I wanted to check what the status is. The code freeze will start ([01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/3b849751)), which is about 2 weeks from now. And while there is still plenty of time, we want to make sure that every PR has a chance to be merged on time.

As the issue is tagged for 1.29, is it still planned for that release?

**Comment by cici37** [comment]
> Hello @cici37 ! 👋🏼 Bug triage for the 1.29 release cycle is here! This issue hasn't been updated for a long time, so I wanted to check what the status is. The code freeze will start ([01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/3b849751)), which is about 1 week from now. And while there is still plenty of time, we want to make sure that every PR has a chance to be merged on time.
> 
> As the issue is tagged for 1.29, is it still planned for that release?

Yes it is still planned for this release and it is blocker by other PRs merging. Thanks

**Comment by cici37** [comment]
/assign @jpbetz 
Current this is blocked by the merging of https://github.com/kubernetes/kubernetes/pull/121460. When that is merged, this should be ready to merge. Thanks

**Pull request merged**
