### PR TITLE
function name change

### PR DESCRIPTION
**Pull request by timchenxiaoyu**
function name change

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37424)

### CODE REVIEW

**Comment by timchenxiaoyu** [comment]
ok

**Comment by timchenxiaoyu** [comment]
ok

**Comment by timchenxiaoyu** [comment]
ok

**Comment by timchenxiaoyu** [comment]
ok

**Comment by timchenxiaoyu** [comment]
ok

**Comment by timchenxiaoyu** [comment]
ok

**Comment by timchenxiaoyu** [comment]
ok

**Comment by timchenxiaoyu** [comment]
ok

**Comment by timchenxiaoyu** [comment]
ok

**Comment by timchenxiaoyu** [comment]
ok

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by rmmh** [comment]
@k8s-bot verify test this

**Pull request merged**
