### PR TITLE
fix: kubelet not added new worker for pod when pod worker panic

### LINKED ISSUE #119188: do cleanupPodUpdates if pod worker panic
### What happened?

pod will not be updated if pod worker panic occurred even there are new pod update event

### What did you expect to happen?

setup new pod worker if old pod worker panic when new pod event exist

### How can we reproduce it (as minimally and precisely as possible)?

1. make pod worker panic for specified pod (e.g. [panic occurred caused by some bug](https://github.com/kubernetes/kubernetes/pull/116504) )
2. update the specified pod
3. nothing happen to respond the update event

### Anything else we need to know?

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pod_workers.go#L947-L953
```
go func() {
			// TODO: this should be a wait.Until with backoff to handle panics, and
			// accept a context for shutdown
			defer runtime.HandleCrash()
                        defer cleanupPodUpdates(uid)
			defer klog.V(3).InfoS("Pod worker has stopped", "podUID", uid)
			p.podWorkerLoop(uid, outCh)
		}()
```

should call `cleanupPodUpdates` in defer

### Kubernetes version

<details>

```console
$ kubectl version
# master
```
</details>

### Cloud provider

<details>
NONE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by likakuli**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
kubelet not added a new pod worker for pod whose worker panic even new event comes
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/119188

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by likakuli** [comment]
also kindly ping @liggitt
please help to review this one, thx

**Comment by liggitt** [comment]
I'll defer detailed review to node reviewers, but at first glance, this needs a test demonstrating the issue being fixed

**Comment by marquiz** [comment]
@likakuli do you think a test case could be added?

**Comment by likakuli** [comment]
ok, i will add it

**Comment by likakuli** [comment]
close this pr for kubelet will panic if pod worker panic after this pr https://github.com/kubernetes/kubernetes/pull/101719

**Pull request closed without merging**
