### PR TITLE
pass synthetised RunAsGroup correctly

### PR DESCRIPTION
**Pull request by krmayankk**
RunAsGroup feature doesnt pass the Docker image(Dockerfile USER uid:gid) group correctly to kubelet and hence gid always comes as 0 even though Dockerfile specifies the gid. 

This PR fixes that issue

```release-note
NONE
```

### CODE REVIEW

**Comment by krmayankk** [comment]
@Random-Liu  FYI i think this fix is also needed to pass the synthesized RunAsGroup correctly.

**Comment by neolit123** [comment]
@kubernetes/sig-node-pr-reviews 
@krmayankk does this need a release note?

**Comment by feiskyer** [comment]
runAsGroup issue has been fixed in https://github.com/kubernetes/kubernetes/pull/65926. I think this change is not required because if runtimes should confirm to dockerfile if runAsGroup is not specified (runtimes could know this by checking whether it's a nil point or not).

**Comment by krmayankk** [comment]
@feiskyer I am not sure i understand your reason for not doing this. Here are the reasons this change is needed:-
- Dockerfile has USER uid:gid and runAsGroup  is not specified than we want the container to run as gid specified in Dockerfile . This change will enable that. See the proposal here https://github.com/kubernetes/community/blob/master/contributors/design-proposals/auth/runas-groupid.md
-runAsNonRootGroup change is in PR. That change needs to find out if Dockerfile specifies gid as 0 so that it can flag that as error if runAsNonRootGroup is set.

HTH

**Comment by krmayankk** [comment]
close this since all changes from this i included here https://github.com/kubernetes/kubernetes/pull/62216

**Pull request closed without merging**
