### PR TITLE
add podAntiAffinity test cases

### PR DESCRIPTION
**Pull request by yarntime**
add podAntiAffinity test cases.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34693)

### CODE REVIEW

**Comment by yarntime** [comment]
@davidopp , would you please take a moment to review this pr? thank you very much.

**Comment by davidopp** [comment]
LGTM

**Comment by yarntime** [comment]
@davidopp, can you give the "ok to test" comment? thanks.

**Comment by davidopp** [comment]
ok to test

**Comment by yarntime** [comment]
@davidopp , I'm so sorry about that, the comment should be "@k8s-bot ok to test".

**Pull request merged**
