### PR TITLE
Add some testcase in testapi_test.go 

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

These tests don't add much value for testing things that have groups in testapi_test.go and I add some testcases to cover all the running branches.

**Release note**:
`NONE`

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
Please fix the gofmt error.

```
I0816 08:29:06.835] Verifying hack/make-rules/../../hack/verify-gofmt.sh
I0816 08:29:18.564] diff ./pkg/api/testapi/testapi_test.go gofmt/./pkg/api/testapi/testapi_test.go
I0816 08:29:18.565] --- /tmp/gofmt780990462	2017-08-16 08:29:13.870580137 +0000
I0816 08:29:18.565] +++ /tmp/gofmt144882501	2017-08-16 08:29:13.870580137 +0000
I0816 08:29:18.565] @@ -99,7 +99,7 @@
I0816 08:29:18.565]  	}
I0816 08:29:18.565]  }
I0816 08:29:18.565]  
I0816 08:29:18.566] -func TestSubResourcePath(t *testing.T){
I0816 08:29:18.566] +func TestSubResourcePath(t *testing.T) {
I0816 08:29:18.566]  	testCases := []struct {
I0816 08:29:18.566]  		resource  string
I0816 08:29:18.566]  		namespace string
I0816 08:29:18.566] FAILED   hack/make-rules/../../hack/verify-gofmt.sh	12s
```

**Comment by wackxu** [comment]
@xiangpengzhao Thank you and I have fix it

**Comment by mml** [comment]
/lgtm

Thanks for the extra coverage @wackxu

**Comment by wackxu** [comment]
@erictune , Please take a look at this PR, it needs your approve, thanks.

**Comment by mml** [comment]
kubernetes/test-infra#4195
/retest

**Comment by wackxu** [comment]
kindly ping @lavalamp @tallclair for approval

**Pull request closed without merging**
