### PR TITLE
Added UndeltaStore.

### PR DESCRIPTION
**Pull request by erictune**
This will be used to connect Reflector to kubelet update channel.

Added testing.

### CODE REVIEW

**Comment by erictune** [comment]
passes all but go 1.2

**Comment by pmorie** [comment]
@erictune I see now that the consumption semantics are different for this and the `EventQueue` in OpenShift that we discussed.

One thing I notice is that it seems like this would be an ideal case to apply event compression.  Currently PushFunc has to implement thread safety, and this design implictly uses that thread safety to implement a queue of events.  Correct me if I'm wrong, but it seems like this will process unnecessary events, since you only ever want to process the latest received state.

**Comment by pmorie** [comment]
To be clear, I'm not suggesting the event compression implemented by `EventQueue` is useful here; they're not.

What I mean specifically is that the callback should be processed to process the latest state available at the next call.

**Comment by erictune** [comment]
yes, it may call the callback twice with the same data.  
I made a comment about that in the code.
It works well enough for the thing I am trying to do.

**Comment by pmorie** [comment]
@erictune Ah, I had read that comment incorrectly before; I thought it was clarifying the since the whole state was included, it was possible for the state for some object not to have changed since it was last processed.

**Comment by pmorie** [comment]
@erictune Your latest code LGTM, fwiw

**Comment by dchen1107** [comment]
LGTM

**Pull request merged**
