### PR TITLE
Fix typo in guestbook README

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by frewsxcv** [comment]
I signed it!

**Comment by ashcrow** [comment]
```is an a cluster-internal``` :arrow_right: ```is a cluster-internal```

Looks good to me!

**Comment by bgrant0607** [comment]
Thanks.

@k8s-bot unit test this

**Comment by bgrant0607** [comment]
LGTM

**Comment by ArtfulCoder** [comment]
Manually merging since k8s-bot is stuck on scalability test not passing.

**Pull request merged**
