### PR TITLE
Automated cherry pick of #11415

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixing a bad error message when kubectl expose is used without port
Original PR: #11415

### CODE REVIEW

**Comment by zmerlynn** [comment]
LGTM. Kicking Travis.

**Comment by zmerlynn** [comment]
This has a conflict and needs a rebase. You have two choices: You can re-run the script (and you'll probably get conflicts), or you can suck down `origin/automated-cherry-pick-of-#11415-upstream-release-1.0` and rebase.

**Comment by nikhiljindal** [comment]
Rebased. Ran the script again.

**Comment by nikhiljindal** [comment]
Shippable failure seemed like a flake timeout issue. Restarted shippable.

**Comment by zmerlynn** [comment]
I'm going to merge this and hope for after-the-fact build info. (Doing a full release build on my desktop now, with unit tests.)

**Pull request merged**
