### PR TITLE
Fix killing child sudo process in e2e_node tests

### LINKED ISSUE #29211: e2e_node tests leak kube-apiserver processes
The code in #26735 doesn't work for me: `sudo` does not pass on SIGTERM when the caller is in the same process group.

Then the `kill -KILL` knocks out the `sudo` process without giving it a chance to kill its child.

The `Pdeathsig` bit doesn't help: either the `sudo` process has already been killed as above, or it gets killed now with SIGKILL; either way the `kube-apiserver` process is still running.

Oddly, it does work about one time in ten.  I have no explanation for that.

I am running from the command-line like this: `make test-e2e-node FOCUS=Kubelet`, on
4.2.0-41-generic #48-Ubuntu SMP Fri Jun 24 11:28:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

CC @timstclair

### PR DESCRIPTION
**Pull request by bboreham**
Fixes #29211; re-doing #29380 which was reverted due to cross-platform build failure #29669.

The context is we are trying to kill a process started as `sudo kube-apiserver`, but `sudo` ignores signals from the same process group. Applying `Setpgid` means the `sudo kill` process won't be in the same process group, so will not fall foul of this nifty feature.

~~I also took the liberty of removing some code setting `Pdeathsig` because it claims to be doing something  in the same area, but actually it doesn't do that at all.  The setting is applied to the forked process, i.e. `sudo`, and it means the `sudo` will get killed if we (`e2e_node.test`) die.  This (a) isn't what the comment says and (b) doesn't help because sending SIGKILL to the sudo process leaves sudo's child alive.~~

We do need to use the same 'hack' to access `Setpgid` as the `e2e_node.test` program gets built on Windows (although it doesn't run there).

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29685)

### CODE REVIEW

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
Thanks for the fixes @bboreham 

> I also took the liberty of removing some code setting Pdeathsig because it claims to be doing something in the same area, but actually it doesn't do that at all. The setting is applied to the forked process, i.e. sudo, and it means the sudo will get killed if we (e2e_node.test) die. This (a) isn't what the comment says and (b) doesn't help because sending SIGKILL to the sudo process leaves sudo's child alive.

Auto-cleanup is desirable. If the test is terminated, users would ideally like the test processes to be cleaned up. Would sending SIGTERM instead result in `sudo` forwarding the signal to its child?

**Comment by bboreham** [comment]
> Auto-cleanup is desirable. If the test is terminated, users would ideally like the test processes to be cleaned up. 

OK, I will restore that code and fix the comment.

> Would sending SIGTERM instead result in sudo forwarding the signal to its child?

That ought to be an improvement, but empirically it does not fix the problem.

To test: I restored the `Pdethsig` code, fired up some `e2e_node` tests then `kill -9` the test-runner process mid-way. The `etcd` was killed, but the `sudo kube-apiserver` and its child both remained running.  Plus one extra process, a `kubelet`.

**Comment by vishh** [comment]
One more option to handle cleanup is to place all these processes inside a cgroup. We can then easily track all the processes and kill them as part of cleanup.

**Comment by vishh** [comment]
lgtm

**Comment by vishh** [comment]
Thanks for the fix @bboreham

**Comment by bboreham** [comment]
Do I have to do something else to appease the bots?

**Comment by vishh** [comment]
@bboreham The bots were supposed to apply an lgtm label automatically. Wonder why they ignored this PR.

**Pull request merged**
