### PR TITLE
add rolebinding check for bootstrap-signer

### PR DESCRIPTION
**Pull request by zhlhahaha**
Check if rolebinding system:controller:bootstrap-signer exist

Signed-off-by: Howard Zhang <howard.zhang@arm.com>

**What type of PR is this?**
/kind flake

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
@zhlhahaha
Considering that kubeadm is not responsible for the lifecycle of the `system:controller:bootstrap-signer`, IMO the test you are proposing should not be added.

Please note that, as described in the comments, we are testing the `system:controller:bootstrap-signer` Role only  to get an indirect signal that kubeadm has properly configured the controlled manager, but I'm not sure we want to go behind this in testing the behavior of other components
@neolit123 opinions ^^^

**Comment by neolit123** [comment]
> Please note that, as described in the comments, we are testing the system:controller:bootstrap-signer Role only to get an indirect signal that kubeadm has properly configured the controlled manager, but I'm not sure we want to go behind this in testing the behavior of other components

testing the Role should be enough.

**Comment by zhlhahaha** [comment]
> @zhlhahaha
> Considering that kubeadm is not responsible for the lifecycle of the `system:controller:bootstrap-signer`, IMO the test you are proposing should not be added.
> 
> Please note that, as described in the comments, we are testing the `system:controller:bootstrap-signer` Role only to get an indirect signal that kubeadm has properly configured the controlled manager, but I'm not sure we want to go behind this in testing the behavior of other components
> @neolit123 opinions ^^^

Thanks for your comment. Well noted.

**Pull request closed without merging**
