### PR TITLE
[WIP] cache apiserver-etcd connections

### PR DESCRIPTION
**Pull request by aojea**
Currently, each API Group Versions creates an independent etcd client,
consequently, and individual TCP connection from the API server to etcd.

The client can be shared, so we reduce the number of TCP connections.

/kind cleanup

```release-note
kube-apiserver: reduce the number of TCP connections required against ETCD by caching the connections with the same transport configurations.
```

With this patch the number of connections measured running one integration test goes from ~50 to ~3

### CODE REVIEW

**Comment by aojea** [comment]
> BTW - I see 100-node scalability tests passing, which I think is also a bit of a signal that there might be something else happening here...

it seems there is contention somewhere, the latencies are crazy

> > ::1,accept:application/vnd.kubernetes.protobuf, */*,protocol:HTTP/2.0 (05-Nov-2021 09:40:51.052) (total time: 10000ms):
> 2021-11-05T09:41:01.053168011Z stderr F Trace[1249581216]: ---"About to convert to expected version" 0ms (09:40:51.052)
> 2021-11-05T09:41:01.053172902Z stderr F Trace[1249581216]: ---"Conversion done" 0ms (09:40:51.052)
> 2021-11-05T09:41:01.053175953Z stderr F Trace[1249581216]: ---"About to store object in database" 0ms (09:40:51.052)
> 2021-11-05T09:41:01.053179056Z stderr F Trace[1249581216]: [10.000791157s] [10.000791157s] END

**Comment by kkkkun** [comment]
Apiserver can overwrite etcd's address  by resource. In this case, should we consider it ?

**Comment by aojea** [comment]
> Apiserver can overwrite etcd's address by resource. In this case, should we consider it ?

I'm just exploring this path, I don't know if this is a good idea yet, since the results show contention and maybe having multiple TCP connection solve them.

Can you elaborate a bit more on your statement? I can't fully understand what are you suggesting :sweat_smile:

**Comment by kkkkun** [comment]
Per-resource etcd servers can override by params '--etcd-servers-overrides' in kube-apiserver. What your means is that a etcd cluster keeps a client connection?  If so,  I didn't understand this before.

**Comment by dims** [comment]
please reopen if you still need this WIP PR. Trying to declutter the open PR(s)

**Comment by aojea** [comment]
/close 

this has been superseded by https://github.com/kubernetes/kubernetes/pull/111559

**Pull request closed without merging**
