### PR TITLE
Increase the verbosity level to gather additional information from CI failures.

### PR DESCRIPTION
**Pull request by madhusudancs**
This is likely temporary. We are going to revert this PR once this is resolved.

Required for debugging issue: #47737

**Release note**:
```release-note
NONE
```

/assign @csbell 

cc @dchen1107

### CODE REVIEW

**Comment by madhusudancs** [comment]
@kubernetes/kubernetes-build-cops could you please manually merge this to expedite debugging the issue.

**Comment by shyamjvs** [comment]
Merging manually
cc @k8s-oncall

**Comment by madhusudancs** [comment]
@shyamjvs thanks!

**Pull request merged**
