### PR TITLE
Drop unused EndpointsHandler / EndpointsConfig from pkg/proxy/config

### PR DESCRIPTION
**Pull request by danwinship**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
kube-proxy no longer supports backends that use Endpoints rather than EndpointSlice, but we still have some of the associated code.

In the process of removing this, I discovered that we were unit testing EndpointsHandler and EndpointsConfig, but _not_ testing EndpointSliceHandler / EndpointSliceConfig, so I fixed that too.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/sig network
/priority backlog
/cc @robscott

### CODE REVIEW

**Comment by aojea** [comment]
> Run ./hack/update-gofmt.sh}

the failure is legit

**Comment by danwinship** [comment]
/assign @wojtek-t 
this one has a trivial kubemark change too

**Comment by robscott** [comment]
Thanks @danwinship!

/lgtm for kube-proxy

**Comment by wojtek-t** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
