### PR TITLE
NFS and HostPath Recycle implementations

### PR DESCRIPTION
**Pull request by markturansky**
HostPath for testing and development, NFS for use.

Only the 3rd commit is interesting.  The others will drop.

4 of 5 PRs from #8334 

@thockin

### CODE REVIEW

**Comment by erictune** [comment]
Thank you very much for the pull request - we sincerely appreciate the work that goes into sending us a change.

We are currently in a feature-freeze and general code slush as we work toward our 1.0 release. Our initial triage indicates that this is a non-critical change at this time, so we'd like to leave it open and revisit it after 1.0. We expect the freeze to wrap up in early to mid July.

If you feel that this triage is incorrect, please respond and let us know why. We're currently accepting changes that meet any of the following criteria:

Changes directly related to v1.0 issues: https://github.com/GoogleCloudPlatform/kubernetes/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.0
Changes addressing P0 bugs: https://github.com/GoogleCloudPlatform/kubernetes/issues?q=is%3Aopen+is%3Aissue+label%3Apriority%2FP0
Changes to supported platforms to bring them up to par with the primary development platforms
Docs, user experience, and test related fixes
Thanks again for your contribution! The community is really what has made this project so exciting.

**Comment by thockin** [comment]
LG except a few nits on the commit

**Comment by markturansky** [comment]
@thockin I refactored the scrubber and removed a lot of code, actually.  It was easy to unit test afterwards.  Gratuitous comments added to describe what it's doing and how to use it.

**Comment by thockin** [comment]
lgtm

**Comment by thockin** [comment]
LGTM 986cbb5

**Comment by markturansky** [comment]
Closing this PR.  All commits accounted for in #9024.

**Pull request closed without merging**
