### PR TITLE
Backport konnectivity-client 0.28.3 to release-1.28.

### PR DESCRIPTION
**Pull request by jkh52**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This picks up bugfixes: https://github.com/kubernetes-sigs/apiserver-network-proxy/compare/v0.1.2...v0.28.3

#### Which issue(s) this PR fixes:

Notable fixes:
* A fix for nil deref: https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/513
* Metric bugfix: https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/511
* CVE fixes.

#### Special notes for your reviewer:

Per https://github.com/kubernetes-sigs/apiserver-network-proxy#versioning-and-releases, starting at Kubernetes 1.28, the Konnectivity Proxy repo will release minor versions 1:1 with Kubernetes (similar to client-go).

This `release-1.28` branch PR is similar to https://github.com/kubernetes/kubernetes/pull/120836

#### Does this PR introduce a user-facing change?
```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

### CODE REVIEW

**Comment by jkh52** [comment]
Flake:

```
  [FAIL] [sig-auth] ServiceAccounts [It] should set ownership and permission when RunAsUser or FsGroup is present [LinuxOnly] [NodeFeature:FSGroup]
```

/retest

**Review by elmiko — COMMENTED** [review]
/lgtm

would be good to get @andrewsykim or @cheftako to add the approval and labels

**Comment by jkh52** [comment]
Friendly ping.

/assign @sttts

**Comment by jkh52** [comment]
Updated this PR from 0.28.0 to 0.28.3, in order to pick up CVE fixes (and rebase).

This PR is in support of https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/537, for release-1.29 we have https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/547.

**Comment by jkh52** [comment]
Obsoleted by https://github.com/kubernetes/kubernetes/pull/124458

**Pull request closed without merging**
