### PR TITLE
removes Flaky from HostCleanup tests

### PR DESCRIPTION
**Pull request by jeffvance**
**What this PR does / why we need it**:
Removes [Flaky] from the e2e kubelet _HostCleanup_ tests.
Verified by the [gce-flaky](https://k8s-testgrid.appspot.com/google-gce#gce-flaky&width=6) and [gke-flaky](https://k8s-testgrid.appspot.com/google-gke#gke-flaky&width=5) test grids.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by saad-ali** [comment]
@jeffvance looks like the tests are failing when run by the `k8s-ci-robot` for this PR. Can you take a look at those?

**Comment by jeffvance** [comment]
@k8s-bot non-cri e2e test this
@k8s-bot gci gce e2e test this

**Comment by jeffvance** [comment]
@saad-ali pushed changes to address failure in gci.

**Comment by jeffvance** [comment]
@k8s-bot test this

**Comment by spxtr** [comment]
@k8s-bot test this

(don't mind me :) )

**Comment by jeffvance** [comment]
@k8s-bot node e2e test this

**Comment by jeffvance** [comment]
@saad-ali all tests now pass. Can you pls review, approve, lgtm?  Thanks.

**Comment by saad-ali** [comment]
Hmm, skipping the test on GCI images, not feeling great about that. My guess is that this creating or deleting files from the node's root FS which it can't do in GCI since GCI's root FS is mounted read-only.

Is there anything that can be done to make the test work in this environment?

**Comment by jeffvance** [comment]
@saad-ali Fair question and I am open to any suggestions. In GCE/debian I am able to `mv` the pod's uid dir, but in any GCI image I get a "busy" error. However, despite this error, the pod's uid dir and all files beneath are copied to the destination, they just cannot be `rm` 'd from _/var/lib/kubelet/pods_.

**Comment by saad-ali** [comment]
> The error I get on GCI is:
> ```
> Apr 20 10:51:49.728: INFO: ssh jvance@35.185.201.208:22: stderr:    "mv: cannot remove '/var/lib/kubelet/pods/06011c88-25f2-11e7-a196-42010af00002/volumes/kubernetes.io~nfs/nfs-vol': Device or resource busy\nmv: cannot remove '/var/lib/kubelet/pods/06011c88-25f2-11e7-a196-42010af00002/volumes/kubernetes.io~secret/default-token-pnnk9': Device or resource busy\n"
> ```

GCI (now known as COS) sets up mounts for Gluster and NFS inside a chroot extracted from a container. @jingxu97 did the work to set that up, she maybe able to offer some advice.

**Comment by jeffvance** [comment]
@jingxu97 If you have time can you help me with a CGI/ChromeOS question? When I run the _HostCleanup_ e2e tests, _kubelet.go_, on GCE-GCI I get the following error when trying to `mv` the pod's UID dir:
```Apr 20 10:51:49.728: INFO: ssh jvance@35.185.201.208:22: stderr:  "mv: cannot remove '/var/lib/kubelet/pods/06011c88-25f2-11e7-a196-42010af00002/volumes/kubernetes.io~nfs/nfs-vol': Device or resource busy\nmv: cannot remove '/var/lib/kubelet/pods/06011c88-25f2-11e7-a196-42010af00002/volumes/kubernetes.io~secret/default-token-pnnk9': Device or resource busy\n"
```
I do not get this error on GCE-debian. I am running the exact same suite in both environments.
On GCE-GCI I've manually `mv` 'd a dir containing a file being accessed (see my command to Saad above) successfully (no "busy" error). Thus, I think it may be an issue with the test suite. I am not running any other tests.

**Comment by jingxu97** [comment]
@jeffvance sorry for the delay. Before you tried to mv the file, did the test umount the pod's nfs directory "/var/lib/kubelet/pods/68530bae-297d-11e7-a9bc-42010af00002/volumes/kubernetes.io~nfs/
nfs-vol"?

**Comment by jeffvance** [comment]
@jingxu97 No the test does not unmount the pod's nfs mount before doing the `mv`. However, this exact test works fine on GCE-debian. Is an unmount required on COS?

**Comment by jeffvance** [comment]
UPDATE:
I've ssh'd to the GCI node where a nfs client pod is running and tried the following while the client pod is running:
1. `mv` the pod's uid dir to /tmp  -->
```
mv: cannot remove '/var/lib/kubelet/pods/7e4ce48b-2ab2-11e7-b1fd-42010af00002/volumes/kubernetes.io~nfs/nfs-vol': Device or resource busy
mv: cannot remove '/var/lib/kubelet/pods/7e4ce48b-2ab2-11e7-b1fd-42010af00002/volumes/kubernetes.io~secret/default-token-gvw1s': Device or resource busy
```
2. `mv -b` --> same error ^^
3. `cp -R` pod's uid dir to /tmp && `rm -rf` pod's uid dir --> same error ^^
4. `umount /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pod
s/7e4ce48b-2ab2-11e7-b1fd-42010af00002/volumes/kubernetes.io~nfs/nfs-vol/` && `mv` pod's uid dir to /tmp --> # note: umount was successful
```
mv: cannot remove '/var/lib/kubelet/pods/7e4ce48b-2ab2-11e7-b1fd-42010af00002/volumes/kubernetes.io~secret/default-token-gvw1s': Device or resource busy
```
5. let pod complete (status == "Completed") and then `mv` pod's uid dir --> SUCCESS

**Comment by jeffvance** [comment]
@saad-ali based on my observation using COS I think I need to keep the `framework.SkipIfNodeOSDistroIs("gci")` call in. Am I missing something? See above comments. Or, perhaps the test I wrote is not a good way to test kubelet cleanup when unexpected problems occur?

**Comment by jingxu97** [comment]
@jeffvance, you have to also unmount the secret directory "/var/lib/kubelet/pods/7e4ce48b-2ab2-11e7-b1fd-42010af00002/volumes/kubernetes.io~secret/default-token-gvw1s"

**Comment by jeffvance** [comment]
Closing due to mounting and 'rm' differences between gci and gce-debian. A future pr will completely remove the test which `mv`s the pod's uid dir since that is not considered a particularly useful test, and it redlines in the gci-gce-flaky test grid.

**Pull request closed without merging**
