### PR TITLE
Add Mesos hyperkube minion server (fixed quick-release)

### PR DESCRIPTION
**Pull request by sttts**
This is identical to https://github.com/GoogleCloudPlatform/kubernetes/pull/11928 with the exception that all changes outside of contrib/mesos (with the exception of the godep) are reverted in the second commit.

### CODE REVIEW

**Comment by karlkfi** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@sttts can this PR just revert 8372b0d9279ecd6557b751253937cdbbdd4c6dcf and include the changes required to fix in a following PR? This will make it much easier to review. i.e.:

```
git revert 8372b0d9279ecd6557b751253937cdbbdd4c6dcf #which creates a commit
...changes to fix build in follow up commit...
...submit PR
```

**Comment by sttts** [comment]
@mikedanese also noticed you only reverted the one patch. Adapting the patch to that.

**Comment by mikedanese** [comment]
Thanks!

**Comment by sttts** [comment]
@mikedanese now it has the right shape as requested. thanks for the patience.

**Comment by mikedanese** [comment]
@k8s-bot ok to test. I'll review and try to merge after lunch. Thanks!

**Comment by mikedanese** [comment]
LGTM on greeen

**Comment by mikedanese** [comment]
Let's try this again.

**Pull request merged**
