### PR TITLE
consolidate cloudproviders into a single import

### PR DESCRIPTION
**Pull request by stensonb**
While attempting to develop a new cloud provider plugin, I noticed each command (kube-apiserver, kubelet, kube-controller-manager) has all the plugins listed in their respective imports...

It seems like a mess to have to update three places for all/any new cloud provider...so, I've created a "providers" package, which contains ALL the plugins...and now each command (listed above), simply references the "providers" package.

(this is the fixed version of this PR: https://github.com/GoogleCloudPlatform/kubernetes/pull/12368)

### CODE REVIEW

**Comment by stensonb** [comment]
I'm happy to rebase off of master...but only if this is going to be accepted.

Any thoughts?

**Comment by erictune** [comment]
ok to test.
lgtm after tests pass.

**Comment by erictune** [comment]
please rebase to allow testing.

**Comment by stensonb** [comment]
I rebased, and somehow I got commits from other people showing up in this PR...hmm...not sure why...

**Comment by piosz** [comment]
Removing LGTM since rebase failed.

**Comment by stensonb** [comment]
I fixed it and forced it back...try to merge now

**Comment by stensonb** [comment]
@piosz ; can you give this the #lgtm tag again. :)

**Comment by piosz** [comment]
Adding LGTM label back.

**Comment by piosz** [comment]
@k8s-bot test this please

**Comment by piosz** [comment]
@k8s-bot test this please

**Comment by piosz** [comment]
Thanks for the change!

**Pull request merged**
