### PR TITLE
Remove the dependency between autoscale command and generators

### PR DESCRIPTION
**Pull request by SataQiu**
Signed-off-by: SataQiu <1527062125@qq.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Remove the dependency between `kubectl autoscale` command and generators

**Which issue(s) this PR fixes**:

Ref #91127

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubectl: the `generator` flag of `kubectl autoscale` has been deprecated and has no effect, it will be removed in a feature release
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by SataQiu** [comment]
Would you mind taking a look？ @soltysh

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/priority backlog

**Pull request merged**
