### PR TITLE
Cluster Autoscaler 1.1.1

### PR DESCRIPTION
**Pull request by mwielgus**
```release-note
Cluster Autoscaler 1.1.1 (details: https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.1.1)
```

### CODE REVIEW

**Comment by mwielgus** [comment]
Adding approve as a sub-directory owner.

**Comment by mwielgus** [comment]
cc: @mbohlool

**Comment by mbohlool** [comment]
@mwielgus  Is there anything specific in new AutoScaler that needs to be in 1.9? I prefer a little more in the release note than just saying it is a newer version of a component. the best is a link to a release note for that component.

**Comment by mwielgus** [comment]
Added the link.

**Comment by mbohlool** [comment]
Thanks

**Pull request merged**
