### PR TITLE
Automated cherry pick of #42859

### PR DESCRIPTION
**Pull request by krzyzacy**
Cherry pick of #42859 on release-1.5.

#42859: Change the junit file name format to

### CODE REVIEW

**Comment by krzyzacy** [comment]
/assign @Random-Liu 

also here while you are on it.

**Comment by krzyzacy** [comment]
@jessfraz can you still approve 1.4 cherrypicks? Or who should I turn to now?

**Comment by dchen1107** [comment]
Justification for cherrypick: The node e2e test against 5 different images (os distro, different docker versions, etc.) This pr only changes the test result's junit name format, so that it can integrate well with test-infra and testgrid dashboard. No functionalitiy change, no test change.

**Pull request merged**
