### PR TITLE
using explicit version

### PR DESCRIPTION
**Pull request by zouyee**
/kind clean-up
**What this PR does / why we need it**:
using explicit version in `volume` area

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```NONE

```

### CODE REVIEW

**Comment by gnufied** [comment]
largely looks good to me. paging @rootfs for another set of eyes.

**Comment by zouyee** [comment]
gentle ping @jsafrane

**Comment by zouyee** [comment]
ping @gnufied @saad-ali PTAL!

**Comment by dixudx** [comment]
Looks good to me. But I still prefer to bump these versions together with other changes, like fixing a bug, adding a new feature, etc. We've got so many informers/clients to be bumped. There is no need to specially do this in such a small PR. @caesarxuchao WDYT?

**Comment by zouyee** [comment]
> Looks good to me. But I still prefer to bump these versions together with other changes, like fixing a bug, adding a new feature, etc. We've got so many informers/clients to be bumped. There is no need to specially do this in such a small PR. @caesarxuchao WDYT?

these changes need to be submitted separately in different dirs.

**Pull request closed without merging**
