### PR TITLE
Enable experimental API in vagrant setups

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Self explanatory, useful for trying out the new feature set.

Default to true since vagrant is inherently a kick the tires and learn about the system option.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
Depending on merge order, if this change goes in first, https://github.com/kubernetes/kubernetes/pull/14156, will need to make an update, or vice-versa.

**Comment by erictune** [comment]
This is going to be renamed to `--runtime-config=experimental/v1alpha1` by #14156 which I will merge before this.

**Comment by derekwaynecarr** [comment]
@erictune - all updated to align with #14156

**Comment by derekwaynecarr** [comment]
I am self marking this LGTM since I am kicking the tires all the time on experimental stuff and having to jump through hoops to get my config setup to use it.

**Pull request merged**
