### PR TITLE
hack/local-up-cluster.sh: Add env to enable rkt in local cluster.

### PR DESCRIPTION
**Pull request by yifan-gu**
This makes testing rkt easier.

### CODE REVIEW

**Comment by yifan-gu** [comment]
@vmarmol @dchen1107 @yujuhong

**Comment by vmarmol** [comment]
We should add a default value, I think Kubelet won't start with an empty container runtime.

**Comment by yifan-gu** [comment]
@vmarmol Thanks for the catching!

**Comment by vmarmol** [comment]
LGTM, thanks @yifan-gu!

**Pull request merged**
