### PR TITLE
chores(controller/nodelifecycle): make node taint removal logs more a…

### PR DESCRIPTION
**Pull request by gyuho**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

N/A

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by tallclair** [comment]
/release-note-edit ```NONE```

I don't think this warrants a release note.

**Comment by pacoxu** [comment]
/release-note-edit
```release-note
None
```

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
