### PR TITLE
Add a binary that links haproxy and kubernetes services

### PR DESCRIPTION
**Pull request by brendandburns**
I know this needs tests.  I'll add them before I submit, sending for feedback in parallel.

### CODE REVIEW

**Comment by brendandburns** [comment]
example usage:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: kube-haproxy
spec:
  containers:
  - name: kube-haproxy
    image: gcr.io/google_containers/kube-haproxy:0.2
    command:
      - /kube-haproxy
      - "--services=nginx"
```

**Comment by brendandburns** [comment]
@thockin

**Comment by mikedanese** [comment]
#11679

**Comment by bprashanth** [comment]
If we want something that just works, this is it. But I'd look for a little more from an L7 I'm willing to deploy:

1. We don't need more than 1 bank of loadbalancers for all http services (assuming ssl termination, and as long as you've opened up the right ports you don't need more than 1 for tcp services). 
2. I wouldn't want a deleted endpoint to continue getting requests for 10s, so a watch would be better (on both services an endpoints).
3. Templating the haproxy.cfg file so we can modify lb algorithm and the 10 other options haproxy provides per service makes sense, at least in the long run
4. It would be nice to have a service loadbalancer cluster addon that auto-configures itself for every service created. 

I took a shot at implementing that in #11679. It is more of a WIP than this pr, but it is closer (IMO) to something deployable. 

Just my 2c. If you're looking to get his is ASAP I'm fine rebasing over it and making necessary modifications, simply mentioning a few things I thought about when writing mine.

**Comment by brendandburns** [comment]
@bprashanth how did I miss your PR...  Sorry about that!

Let's work together to get this in in the near term.  Let me know what the fastest way you think to do that is, I'm fine with dropping this PR and working from your PR.

Let me know what you think...

**Comment by brendandburns** [comment]
Offline discussion w/ @bprashanth closing this one in favor of #11679 we're going to merge some of the things from this into that one.

**Pull request closed without merging**
