### PR TITLE
update generated files

### LINKED ISSUE #73999: Master-blocking failing tests: verify.godeps and verify.staging-godeps
**Which jobs are failing**:
* [verify-master](https://testgrid.k8s.io/sig-release-master-blocking#verify-master)

**Which test(s) are failing**:

Job | Test | Reason for failure
--- | --- | ---
[verify-master](https://testgrid.k8s.io/sig-release-master-blocking#verify-master) | [verify.godeps](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-verify-master/26819) | `Your vendored results are different: diff -Naupr -x BUILD -x 'AUTHORS*' -x 'CONTRIBUTORS*' vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.proto /tmp/gopath.fjRjH3/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.proto`
[verify-master](https://testgrid.k8s.io/sig-release-master-blocking#verify-master) |  [verify.staging-godeps](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-verify-master/26819)  | `Unexpected dirty working directory`

**Since when has it been failing**:
2019-02-11

**Anything else we need to know**:

* `verify.godeps` started failing with commit [f7c4389b7](https://github.com/kubernetes/kubernetes/commit/f7c4389b7)
* `verify.staging-godeps` started failing with commit [805a9e703](https://github.com/kubernetes/kubernetes/commit/805a9e703)

cc @mortent @kacole2 @alejandrox1 @mariantalla

/kind failing-test
/priority important-soon
/sig api-machinery

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/kind bug
/sig api-machinery

**What this PR does / why we need it**:

make verify job passed.

**Which issue(s) this PR fixes**:

Fixes #73999

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by danielqsj** [comment]
cc @liggitt

**Comment by liggitt** [comment]
How did this get out of sync in master?

**Comment by danielqsj** [comment]
not sure about it. But it missing for several months.
Should it be cherry-picked to release branch ?

**Pull request merged**
