### PR TITLE
Heal the namespaceless ingresses in federation e2e.

### PR DESCRIPTION
**Pull request by ghost**
For createIngressOrFail, it incorrectly returned the ingress passed in as an argument, which does not include the namespace, instead of the ingress returned from the create call (which does).

This in turn leads to errors in e2e tests like this:

INFO: Waiting for Ingress federated-ingress to acquire IP, error an empty namespace may not be set when a resource name is provided.

Self-applying LGTM label, as this is the same code that was LGTM'd by @nikhiljindal in #33502

``` release-note
Heal the namespaceless ingresses in federation e2e.
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33977)

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@k8s-bot unit test this ISSUE #33939

**Comment by quinton-hoole** [comment]
Sorry, typo, the above should be #33979

**Comment by nikhiljindal** [comment]
@quinton-hoole Did you intend to cherrypick this?
The bot removed your label because of incorrect milestone.

**Comment by quinton-hoole** [comment]
Yup, I intended to cherrypick it.  I guess the milestone should have been v1.4.  I was just confused.  Fixing.

**Comment by jessfraz** [comment]
this seems sane to me to cherry-pick :)

**Pull request merged**
