### PR TITLE
Skip zero quantity resource check

### LINKED ISSUE #68002: Restarting kubelet causes unwanted pod rejection
/kind bug

**What happened**:

if someone submits a pod with the following yaml file

```
apiVersion: v1
kind: Pod
metadata:
 name: busybox-1
 namespace: default
spec:
 containers:
 - name: busybox-1
   image: busybox
   command:
     - sleep
     - "3600"
   imagePullPolicy: IfNotPresent
   resources:
     requests:
       cpu: 1
       memory: "100Mi"
       nvidia.com/gpu: 2
     limits:
       nvidia.com/gpu: 2
 restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
 name: busybox-2
 namespace: default
spec:
 containers:
 - name: busybox-2
   image: busybox
   command:
     - sleep
     - "3600"
   imagePullPolicy: IfNotPresent
   resources:
     requests:
       cpu: 1
       memory: "100Mi"
       nvidia.com/gpu: 0
     limits:
       nvidia.com/gpu: 0
```
Suppose the two pods run on same kubelet, if we restart the kubelet, the `busybox-1` pod will pass `PodFitsResources`, but the `busybox-2` pod will fail `PodFitsResources`. Kubelet's log shows the reason
```
I0829 18:20:22.586445   10333 server.go:457] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"busybox-2", UID:"1a2ccb08-ab75-11e8-be16-6c0b840b6709", APIVersion:"v1", ResourceVersion:"278", FieldPath:""}): type: 'Warning' reason: 'OutOfnvidia.com/gpu' Node didn't have enough resource: nvidia.com/gpu, requested: 0, used: 2, capacity: 0
```

**What you expected to happen**:

The pod with zero resource request should pass `PodFitsResources`

**How to reproduce it (as minimally and precisely as possible)**:

use `kubectl` create pods with the above yaml. When two pods are ready, restart the kubelet, you'll find the `busybox-2` will be rejected.

**Reason**
After digging, we found that
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/lifecycle/predicate.go#L73
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/devicemanager/manager.go#L764
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/predicates.go#L784
cause the problem.

After restarted, kubelet will clear all allocatableResource, waiting for others to report the capacity and allocatable resource. At this time kubelet will do `Admit` to reject the pods which are out of resource.
`busybox-1` can pass the `Admit` because it has a `>0` resource request, `sanitizeNodeAllocatable` will set allocatableResource, then `PodFitsResources` pass the check. Problem comes when kubelet try to admit `busybox-2`, it has a zero resource request, `sanitizeNodeAllocatable` will keep allocatbleResource which is zero, then `PodFitsResources` fail the check although `busybox-2` does want zero resource.

**Fix**
Skipping zero resource check can solve this problem

### PR DESCRIPTION
**Pull request by mYmNeo**
Signed-off-by: mYmNeo <thomassong2012@gmail.com>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #68002

**Special notes for your reviewer**:
this will effect all versions which has scalar resource feature

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by k82cn** [comment]
please also add some test for this case.

**Comment by misterikkit** [comment]
/hold

It seems like the bug is that the scheduler things resources used > allocatable, so I don't think checking for zero is the right fix.

**Pull request closed without merging**
