### PR TITLE
Cherrypick etcd3 changes

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #20504

From production pov, this PR is supposed to be no-op (since we are not switching the defaults still).

```release-note
Adds etcd3 changes
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36232)

### CODE REVIEW

**Comment by wojtek-t** [comment]
OK - tests are passing, so patch should be ok now

@jessfraz - do you know why verify-godeps is failing? (the failure seems completely unrelated to my changes)

**Comment by wojtek-t** [comment]
@mml @jessfraz - friendly ping

@jessfraz - do you know why verify-godeps is failing? (the failure seems completely unrelated to my changes)

**Comment by jessfraz** [comment]
Did you run godeps-save since it's a cherry pick it might have been messed up when cherry picking the Godeps patches

**Comment by jessfraz** [comment]
You'll want to rebase off of https://github.com/kubernetes/kubernetes/pull/36203 as well

**Comment by wojtek-t** [comment]
@mml @jessfraz - tests are passing - should be ready for merge.

**Comment by jessfraz** [comment]
Cool I've added all the appropriate labels

**Pull request merged**
