### PR TITLE
Regenerate auto-generated client code

### PR DESCRIPTION
**Pull request by wojtek-t**
Purely mechanical PR - I've just did:

```
go run cmd/libs/go2idl/client-gen/main.go
go run cmd/libs/go2idl/client-gen/main.go -t
```

@caesarxuchao - FYI

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Thanks. Seems it's just running the tool to make another PR I reviewed to take effect, so SGTM.

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Pull request merged**
