### PR TITLE
upgrade etcd deps to v3.5.8

### PR DESCRIPTION
**Pull request by kkkkun**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes # https://github.com/kubernetes/kubernetes/issues/117341

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by serathius — APPROVED** [review]

**Review by serathius — APPROVED** [review]

**Comment by pacoxu** [comment]
/lgtm cancel
```
staging/src/k8s.io/apiserver/pkg/storage/etcd3/testserver/test_server.go:1: : # k8s.io/apiserver/pkg/storage/etcd3/testserver
pkg/storage/etcd3/testserver/test_server.go:69:6: cfg.LPUrls undefined (type *"go.etcd.io/etcd/server/v3/embed".Config has no field or method LPUrls)
pkg/storage/etcd3/testserver/test_server.go:70:6: cfg.APUrls undefined (type *"go.etcd.io/etcd/server/v3/embed".Config has no field or method APUrls)
pkg/storage/etcd3/testserver/test_server.go:71:6: cfg.LCUrls undefined (type *"go.etcd.io/etcd/server/v3/embed".Config has no field or method LCUrls)
pkg/storage/etcd3/testserver/test_server.go:72:6: cfg.ACUrls undefined (type *"go.etcd.io/etcd/server/v3/embed".Config has no field or method ACUrls) (typecheck)
/*
```
the CI needs to be fixed.

**Pull request merged**
