### PR TITLE
removed unused test/e2e_kubeadm/runner/local/run_local.go

### PR DESCRIPTION
**Pull request by BenTheElder**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Removes an unused and broken test tool. Found as part of https://github.com/kubernetes/kubernetes/pull/106099

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

You can tell this is unused because it would not have worked throughout 1.20, 1.21, 1.22, or the nearly complete 1.23 development cycles, due to the dependency on Bazel, which was removed per https://github.com/kubernetes/enhancements/issues/2420

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

This tool was not a supported user-facing thing.

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks

/lgtm
/approve
/triage accepted

**Comment by BenTheElder** [comment]
/hold
I missed that there's also a make rule for this.

**Pull request merged**
