### PR TITLE
Experimental: deep copy optimization

### PR DESCRIPTION
**Pull request by sttts**
Experiments along the lines of https://github.com/kubernetes/kubernetes/issues/19085:
- copy all struct with `*out = *in` first instead of all elements independently
- pass structs as `in *structType` instead of `in structType`
- avoid reflection by storing generated deep-copy funcs untyped with `interface{}` in and out params. Then we avoid `reflect.Call`
- implement custom deep-copy func for `time.Time`

Before:

```
BenchmarkPodCopy-4        300000          5334 ns/op        3688 B/op         25 allocs/op
```

After:

```
BenchmarkPodCopy-4        500000          2317 ns/op        2184 B/op         18 allocs/op
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
Without the passing struct by pointer operation what's the delta?  In general it's probably a bad idea to pass structs by value anyway, but I wanted to get a feel for that change's specific impact on the overall run.

**Comment by sttts** [comment]
I have to independent hard numbers for each change (yet). My feeling is that the reduced allocation number (mainly due to the avoidance of `reflect.Call` in the generated func case) contributes most.

**Comment by smarterclayton** [comment]
We probably shouldn't have any reflect.Calls anyway (i know there are a couple, for things like map[string]struct{} and external types).  I didn't see any change in your PR?

**Comment by sttts** [comment]
In the second patch I introduce the untyped deepcopy functions. I changed the cloner top-level deepcopy function to take the short-cut via a normal go function call avoiding some reflection (compare https://github.com/kubernetes/kubernetes/pull/28592/files#diff-d45680f91eeeb7a8af4131da98a72f04L150).

**Comment by sttts** [comment]
I wonder why we don't use a DeepCopy interface for our api objects. Then we can check for that avoiding the initial lookup with reflection altogether.

**Comment by wojtek-t** [comment]
Regarding copying structs with *out = *in - this has already been fixed in the in-flight PR by @thockin https://github.com/kubernetes/kubernetes/pull/28578

**Comment by smarterclayton** [comment]
Original goal of having the function was so we could have the generated functions be in a different package.  We can't make time.Time implemented DeepCopy, for example.

**Comment by thockin** [comment]
We also don't need time.Time to have a DeepCopy - simple assignment suffices.  For cases where it doesn't suffice we wrap it into a type of our own and apply a .DeepCopy() method.

My PR(s) linked above start down that path, but I know there's much consternation about using methods on API objects.  I think we need a holistic answer to copy, default, and convert operations before we jump in.

@stts it would be super cool if you could retest on top of my PR...

I think there are a TON of optimizations to be made in deepcopy and in conversion.

**Comment by smarterclayton** [comment]
I don't think there is much left on conversion, but be sure to check out
the tracking issue so you know what's already being worked.

On Jul 7, 2016, at 7:48 PM, Tim Hockin <notifications@github.com> wrote:

We also don't need time.Time to have a DeepCopy - simple assignment
suffices. For cases where it doesn't suffice we wrap it into a type of our
own and apply a .DeepCopy() method.

My PR(s) linked above start down that path, but I know there's much
consternation about using methods on API objects. I think we need a
holistic answer to copy, default, and convert operations before we jump in.

@stts <https://github.com/stts> it would be super cool if you could retest
on top of my PR...

I think there are a TON of optimizations to be made in deepcopy and in
conversion.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/28592#issuecomment-231240274>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABG_pyN_eAG8_Nkp3fPQ0SCvpHPlPrezks5qTZBfgaJpZM4JG_yi>
.

**Comment by smarterclayton** [comment]
That tracking issue is https://github.com/kubernetes/kubernetes/issues/27667

**Comment by thockin** [comment]
The obvious one in conversion is the v1.ObjectMeta <-> api.ObjectMeta
conversions which all trigger the "TODO: Inefficient conversion" path.

**Comment by smarterclayton** [comment]
Hrm, those are all fixed in my unsafe PR and my map PR.

**Comment by smarterclayton** [comment]
The unsafe one basically makes conversion free for any struct that is memory identical.  The up front cost unfortunately is that we need to split defaulters out, and estimate how many custom conversions we'll have deep in the stack.

**Comment by sttts** [comment]
For comparison, master with @thockin's #28578 merged:

```
BenchmarkPodCopy-4   	  500000	      3302 ns/op	    3432 B/op	      17 allocs/op
```

**Comment by thockin** [comment]
So I got about half of your optimizations.  Cool.

**Comment by sttts** [comment]
Replacing the single builtin assignments with one `sw.Do("*out = *in\n", nil)` line does not help at all, even with some heuristics to only do it if there are enough builtins in a struct. Seems like the go compiler is pretty good here already.

**Comment by sttts** [comment]
How does this look like:

```
BenchmarkPodCopy-4   	 1000000	      1992 ns/op	    2056 B/op	      14 allocs/op
```

**Comment by sttts** [comment]
Rebased to @thockin's two recently merged PRs and cleaned up two changes from here https://github.com/kubernetes/kubernetes/pull/28679, leading to around 1900ns.

**Pull request closed without merging**
