### PR TITLE
Revert "Fix up alignment of columns w/ namespaces."

### PR DESCRIPTION
**Pull request by mbforbes**
Reverts GoogleCloudPlatform/kubernetes#10851

This breaks Shippable because it introduces syntax that isn't valid for Go1.3:

```
./hack/verify-gofmt.sh
./pkg/kubectl/resource_printer.go:976:6: expected operand, found 'range'
./pkg/kubectl/resource_printer.go:981:2: expected '{', found 'return'
./pkg/kubectl/resource_printer.go:984:6: expected '(', found 'IDENT' formatLabelHeaders
```

### CODE REVIEW

**Comment by mbforbes** [comment]
Oh, come-on @googlebot ....

**Comment by jbeda** [comment]
Let me see if I can fix it real quick vs. roll back, if you can wait a sec.

**Comment by mbforbes** [comment]
Ack—@vmarmol leaving to your discretion but I trust Joe's speed :-)

I've been bitten by the `for range` 1.3 annoyance multiple times...

**Comment by jbeda** [comment]
I didn't originally have that but was forced on me by the check to do `gofmt -s`.  Ug.

**Comment by mbforbes** [comment]
Yep, Go 1.4 and Go 1.3 directly fight eachother on that. One sec, let me dig up a terrible workaround...

**Comment by mbforbes** [comment]
```go
for foo := range bar {
   _ = foo
}
```

**Comment by jbeda** [comment]
That is horrid -- implementing now.

**Comment by mbforbes** [comment]
Closing in favor of #11017

**Pull request closed without merging**
