### PR TITLE
Add traces to scheduler

### PR DESCRIPTION
**Pull request by wojtek-t**
This will simplify performance debugging of scheduler.

@davidopp @hongchaodeng @xiang90

### CODE REVIEW

**Comment by hongchaodeng** [comment]
Just to clarify,

- V(2) -> V(3) change is to optimize performance due to logging latency.
- the tracing will help in debugging long scheduling latency.

Right?

**Comment by wojtek-t** [comment]
>
V(2) -> V(3) change is to optimize performance due to logging latency.

Correct. Also this log is not very useful, because we logging event right after that anyway.

>
the tracing will help in debugging long scheduling latency.

Correct.

**Comment by hongchaodeng** [comment]
Great. LGTM!

**Comment by wojtek-t** [comment]
Fixed unit tests - reapplying lgtm label.

**Pull request merged**
