### PR TITLE
Remove release-notes for the reverted PR#118895

### PR DESCRIPTION
**Pull request by sanchita-07**
#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it:
This PR removes the release-notes for the PR#118895 from RyanAoh/kep-1860 that got reverted. 
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by Verolop — COMMENTED** [review]
/lgtm

**Review by Verolop — COMMENTED** [review]
/lgtm

**Comment by aojea** [comment]
/lgtm

from sig-network

**Pull request merged**
