### PR TITLE
typo fixed

### PR DESCRIPTION
**Pull request by hTrap**
removed an extra 'a' just before '2 hours'

### CODE REVIEW

**Comment by erictune** [comment]
Thanks for the contribution.  Our lawyers say that we can't take even simple changes like this without a signed CLA on file.  CONTRIB.md explains the process.

**Comment by hTrap** [comment]
I have applied for the CLA, would update the file as soon as i receive the confirmation.

**Comment by hTrap** [comment]
how should i sign my file with the CLA?

**Comment by bgrant0607** [comment]
CLA confirmed.

**Pull request merged**
