### PR TITLE
Update node e2e test images project to the new centralized project

### PR DESCRIPTION
**Pull request by vishh**

### CODE REVIEW

**Comment by vishh** [comment]
@k8s-bot test node e2e

**Comment by vishh** [comment]
@k8s-bot test this

**Comment by vishh** [comment]
I'm bumping the priority of this PR since it will help manage the node e2e test suite. A new ubuntu image needs to be added, and I'd prefer adding that image to just one project.

**Comment by eparis** [comment]
are you hoping for this to get cherrypicked to 1.3?

**Comment by vishh** [comment]
@erictune This PR needs to be cherry picked into v1.3 branch to fix #28683.

**Pull request merged**
