### PR TITLE
continue fix the typo in staging file

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
in kubernetes has left two place to modify the word of explicit,thanks
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50680 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
@jianglingxia please don't put a PR number after `fixes` in your PR body, or that ref PR will be closed once your PR is merged.

**Comment by jianglingxia** [comment]
sorry,I didn't know that before，Just give a reference to the review,I'll pay attention later，thanks very much！ @xiangpengzhao

**Comment by xiangpengzhao** [comment]
@jianglingxia no worries :)

**Pull request merged**
