### PR TITLE
Removed a space in portforward.go.

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by GheRivero** [comment]
lgtm

**Comment by deads2k** [comment]
actually, pulled lgtm and approved.  Can you combine this with your other typo fixes

**Comment by gyliu513** [comment]
cc @deads2k created a whole PR now, thanks.

**Comment by deads2k** [comment]
> cc @deads2k created a whole PR now, thanks.

Thanks. looks good.

**Comment by deads2k** [comment]
```
I0207 08:11:12.033] !!! 'gofmt -s -w' needs to be run on the following files: 
I0207 08:11:12.033] ./plugin/pkg/admission/resourcequota/controller.go
I0207 08:11:12.042] FAILED   hack/make-rules/../../hack/verify-gofmt.sh	9s
```

**Comment by gyliu513** [comment]
cc @deads2k 

Seems k8s improved code style check?

```
@@ -101,7 +101,7 @@ func newAdmissionWaiter(a admission.Attributes) *admissionWaiter {
 // are persisted by the server this admission controller is intercepting
 func NewQuotaEvaluator(quotaAccessor QuotaAccessor, registry quota.Registry, lockAcquisitionFunc func([]api.ResourceQuota) func(), workers int, stopCh <-chan struct{}) Evaluator {
        return &quotaEvaluator{
-               quotaAccessor:      quotaAccessor,
+               quotaAccessor:       quotaAccessor,
                lockAcquisitionFunc: lockAcquisitionFunc,

                registry: registry,
```

**Comment by deads2k** [comment]
> cc @deads2k
> 
> Seems k8s improved code style check?

I don't think we changed it, but maybe `gofmt` updated

**Pull request merged**
