### PR TITLE
Fix an issue about generation of secret key with invalid key size in gce

### LINKED ISSUE #67091: Use of /dev/random generates secret key with invalid size in gce
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
In GCE env, AESGCM encryption of secrets by default generates a secret key with /dev/random instead of /dev/urandom
**What you expected to happen**:
On running cluster/kube-up.sh in GCE provider should create and initialize a cluster without any issue. However, I am seeing below error - 

error: error while parsing encryption provider configuration file "/etc/srv/kubernetes/encryption-provider-config.yml": error while creating cipher for named key key1: crypto/aes: invalid key size 8

This happens because sometime, /dev/random generates a key with smaller size than 32-byte. Replacing it with /dev/urandom fixes the issue as it consistently generates 32-byte secret key.

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup Kubernetes on Ubuntu xenial (16.04). 
2. make quick-release
3. Kick-off cluster/kube-up.sh with provider=gce

**Anything else we need to know?**:
No
**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.0-alpha.1.41+c2536e2b0d6be6-dirty
- Cloud provider or hardware configuration: GCE
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux scspa0509399001 4.4.0-122-generic #146-Ubuntu SMP Mon Apr 23 15:34:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: gce-sdk
- Others:

### PR DESCRIPTION
**Pull request by yogi-sagar**
Replace /dev/random to /dev/urandom to avoid generation of secret key with invalid key size.

**What this PR does / why we need it**:
In GCE env, AESGCM encryption of secrets by default generates a secret key with /dev/random which sometime generates a key with invalid size.
This cause the cluster/kube-up.sh to fail in gce environment.

This PR replaces /dev/random with  /dev/urandom to have a secret key generated consistently with right size.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #67091

**Special notes for your reviewer**:

**Release note**:

```release-note
cluster/gce: generate consistent key sizes in config-default.sh using /dev/urandom instead of /dev/random  
```

### CODE REVIEW

**Comment by neolit123** [comment]
/cc @kubernetes/sig-gcp-bugs 
/kind bug
/ok-to-test

@yogi-sagar please add a release note explaining the change.

**Comment by yogi-sagar** [comment]
@neolit123 Please review, if the Release Notes comment is sufficient.

**Comment by neolit123** [comment]
@yogi-sagar 

> Currently, by default secret key is being generated using /dev/random which sometimes generates the key with invalid size. Therefore, we need to use /dev/urandom to make secret key generation consistent. 

make the note in imperative form and give a location of the change, here is how:
> cluster/gce: generate consistent key sizes  in config-default.sh using /dev/urandom instead of /dev/random

**Comment by yogi-sagar** [comment]
Thanks @neolit123 ! Updated the release notes comments.

**Comment by neolit123** [comment]
@yogi-sagar 
thanks, the release note is OK.
you should wait on maintainer comments now.

**Comment by abgworrall** [comment]
/assign @tallclair 
Tim, WDYT

**Comment by tallclair** [comment]
I think this LGTM.
/assign @immutableT 
for a second opinion

**Comment by tpepper** [comment]
What about using the "iflag=fullblock" flag for dd?  And adding logic, since this is a shell script, to confirm the requested length was received?  Since this is the deprecated cluster/ area, do we not care about security implications to use of urandom?  Does GCE make a high entropy device available to guest instances?

**Comment by destijl** [comment]
Advice from internal crypto folks is that /dev/urandom entropy is fine on modern kernels. fullblock sounds like a good idea.

**Comment by destijl** [comment]
One of our crypto folks said:

"For new applications, I recommend getrandom(), and if blocking is worse than getting a bad key, use the GRND_NONBLOCK flag."

AFAICT there's no way to use that from bash so to avoid complicating this I'd stick with dd, but I think fullblock sounds like a good idea so you don't get a short key.

**Comment by saad-ali** [comment]
Remove hold once @destijl approves

**Comment by destijl** [comment]
@yogi-sagar just waiting on fullblock, can you do that today?

```
dd if=/dev/urandom bs=32 count=1 iflag=fullblock 2>/dev/null | base64 | tr -d '\r\n'
```

**Comment by yogi-sagar** [comment]
@destijl Uploaded new patch with the suggested change.

**Comment by mikedanese** [comment]
Related: https://github.com/kubernetes/kubernetes/pull/68256

/approve

**Comment by destijl** [comment]
@mikedanese can you remove the merge hold?

**Comment by mikedanese** [comment]
Low impact bug fix that reduces flakiness of cluster-up

**Pull request merged**
