### PR TITLE
remove leaked socket file in unit test

### LINKED ISSUE #47301: Leaked socket file after unit test
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**What happened**:
4 socket files is left in workspace after we run "make test"

**What you expected to happen**:
The workspace should be clean.

**How to reproduce it** (as minimally and precisely as possible):
$ make test WHAT=k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry KUBE_GOFLAGS="-v"
$ find -type s
./staging/src/k8s.io/apiserver/pkg/registry/generic/registry/127.0.0.1:2105731492
./staging/src/k8s.io/apiserver/pkg/registry/generic/registry/127.0.0.1:2105831492
./staging/src/k8s.io/apiserver/pkg/registry/generic/registry/localhost:8595437375691616229
./staging/src/k8s.io/apiserver/pkg/registry/generic/registry/localhost:85954373756916162290

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by CaoShuFeng**
Fixes #47301

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by CaoShuFeng** [comment]
@nikhiljindal

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by caesarxuchao** [comment]
@liggitt can we add the 1.7 milestone for it? The issue has not caused test failures so far but might bite us one day.

**Comment by liggitt** [comment]
agree, don't want tests that leave the tree dirty in a release branch

**Comment by CaoShuFeng** [comment]
@k8s-bot pull-kubernetes-kubemark-e2e-gce test this

**Comment by CaoShuFeng** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by CaoShuFeng** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Pull request merged**
