### PR TITLE
Update vendor package github.com/hashicorp/golang-lru

### PR DESCRIPTION
**Pull request by stafot**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
 Part of #69776 involves updating github.com/hashicorp/golang-lru

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
N/A

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
`NONE`

### CODE REVIEW

**Comment by smarterclayton** [comment]
Needs a rebase and update.  Please reopen if you get a chance to do that and I'll review.

**Comment by anarchistHH1983** [comment]
Re open

**Comment by stafot** [comment]
@smarterclayton @anarchistHH1983 I will rebase and re open. Thanks

**Comment by stafot** [comment]
@smarterclayton Re-opened [here.]( https://github.com/kubernetes/kubernetes/pull/74260)
Sorry for this. Something went wrong with my fork and couldn't push in this PR.

**Pull request closed without merging**
