### PR TITLE
move function to node util

### PR DESCRIPTION
**Pull request by zouyee**
**What this PR does / why we need it**:
move updateNode function to node util

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```NONE

```

### CODE REVIEW

**Comment by zouyee** [comment]
priority/critical-urgent

**Comment by zhangxiaoyu-zidif** [comment]
Is ‘UpdateNodeStatus’ a util function?

**Comment by dixudx** [comment]
@zouyee @zhangxiaoyu-zidif Dup of #49856.

**Comment by zhangxiaoyu-zidif** [comment]
@dixudx 
yes, we can close it because of timestamp...

**Comment by zouyee** [comment]
@zhangxiaoyu-zidif I will close it, thank you.

**Pull request closed without merging**
