### PR TITLE
kubeadm: update func CreateJoinControlPlaneKubeConfigFiles variable name

### PR DESCRIPTION
**Pull request by Jerry-yz**
#### What type of PR is this?
type fix

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
   NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve
/triage accepted
/priority backlog

**Review by chendave — COMMENTED** [review]
/lgtm

**Pull request merged**
