### PR TITLE
kubelet/network: add sig-network-approvers to OWNERS

### PR DESCRIPTION
**Pull request by dcbw**
Add sig-network-approvers to kubelet/network OWNERS

@thockin @freehan 

```release-note
NONE
```

### CODE REVIEW

**Comment by dcbw** [comment]
@liggitt here's the one we were talking about :)

**Comment by danwinship** [comment]
should this cover `pkg/kubelet/dockershim/network` too?
/assign @thockin

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by dcbw** [comment]
> should this cover `pkg/kubelet/dockershim/network` too?

@danwinship https://github.com/kubernetes/kubernetes/pull/87727

**Comment by thockin** [comment]
Same comment as #87727 applies here

**Pull request merged**
