### PR TITLE
Parsing "--metrics-bind-address" should use IPPortVar.

### LINKED ISSUE #68669: Failed to start kube-proxy with --metrics-bind-address flags
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:

Start kube-proxy with "--metrics-bind-address=0.0.0.0:10249" return: 
Error: invalid argument "0.0.0.0:10249" for "--metrics-bind-address" flag: "0.0.0.0:10249" is not a valid IP address
and with "--metrics-bind-address=0.0.0.0" return:
server.go:358] failed validate: KubeProxyConfiguration.MetricsBindAddress: Invalid value: "0.0.0.0": must be IP:port

**What you expected to happen**:

The default metrics-bind-address is "127.0.0.1:10249", I expected to change it with "--metrics-bind-address=0.0.0.0:10249"

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by Chenditang**
**What this PR does / why we need it**:
Parsing "--metrics-bind-address" should use IPPortVar.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #68669

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by mikedanese** [comment]
Can you update the flag doc?

/relnote none
/ok-to-test

**Comment by mikedanese** [comment]
@kubernetes/sig-network-bugs

**Comment by Chenditang** [comment]
@mikedanese PTAL

**Pull request closed without merging**
