### PR TITLE
kubeadm: move app/phases/upgrade to generic kubeadm utils

### PR DESCRIPTION
**Pull request by yuexiao-wang**
Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
app/phases/upgrade needs to be moved to generic kubeadm utils (not a phase),  which the new location is cmd/kubeadm/app/util/.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Ref # https://github.com/kubernetes/kubeadm/issues/1163

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/assign @neolit123  @fabriziopandini

### CODE REVIEW

**Comment by fabriziopandini** [comment]
@yuexiao-wang @neolit123 
/hold
I'm not sure that moving the upgrade logic to `/utils` is the right move, so I prefer to have another discussion at sig level before executing this refactor.

Looking at this problem, my first reaction is that phases are a UX thing and should not be reflected outside `cmd/kubeadm/app/cmd`. As a consequence then IMO we should rename `cmd/kubeadm/app/phases` into `cmd/kubeadm/app/pkg` (or in `pkg/kubeadm`, similar to other Kubernetes commnad).

Then `cmd/kubeadm/app/pkg` (or in `pkg/kubeadm`) is eligible for hosting all kubeadm logics, no matter if invoked by phases or by cobra command directly

@timothysc opinions here?

**Comment by yuexiao-wang** [comment]
@timothysc  @fabriziopandini  any suggestion?

**Comment by yuexiao-wang** [comment]
only rebase

**Comment by neolit123** [comment]
hi @yuexiao-wang thanks for the update.
we are busy with the 1.13 release and this has to wait until the 28th or after release.

**Comment by yuexiao-wang** [comment]
OK

**Comment by neolit123** [comment]
@fabriziopandini had some comments on this PR. maybe we should not move the packages like so.
/assign @fabriziopandini

**Comment by fabriziopandini** [comment]
@neolit123 I opened https://github.com/kubernetes/kubeadm/issues/1205 to trigger a broader discussion on this topic, but also https://github.com/kubernetes/kubeadm/issues/1215 seems related to me.

IMO we should wait for consensus on a long-term roadmap before executing

**Pull request closed without merging**
