### PR TITLE
kubeadm: update the version constants for 1.16

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:
- first commit: apply test fixes that prevent seemless version bumps
commit description has details.
- second commit: bump the versions.

this is still an issue:
https://github.com/kubernetes/kubeadm/issues/1260

we are defaulting ClusterConfiguration with a version that resolves a label from the internet and this is such a can of worms.

unit tests wrongly end up calling:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/config/common.go#L91

and if the bumped minimal CP version in constants.go _is newer_ than the latest stable version from the label we use, this can end up in:
```
this version of kubeadm only supports deploying clusters with the control plane version >= 1.16.0. Current version: v1.15.1
```
in a large number of unit tests...

**Which issue(s) this PR fixes**:

xref https://github.com/kubernetes/kubeadm/issues/1260

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/assign @fabriziopandini @rosti 
/cc @yagonobre 
/priority critical-urgent
/kind cleanup

### CODE REVIEW

**Comment by neolit123** [comment]
/hold
for review

**Review by fabriziopandini — APPROVED** [review]
@neolit123 thanks for this fix!
/approve
/lgtm

**Review by yagonobre — COMMENTED** [review]
Thanks!
LGTM

**Pull request merged**
