### PR TITLE
Automated cherry pick of #95655: Moving docker options to daemon.json

### PR DESCRIPTION
**Pull request by vteratipally**
Cherry pick of #95655 on release-1.20.

#95655: Moving docker options to daemon.json

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
/lgtm

this cherry pick will be needed for scripts to work with COS 89. I don't think it is needed to backport to earlier versions as they are less likely to be updated to work on COS 89.

**Comment by SergeyKanzhelev** [comment]
@kubernetes/release-managers can you please approve this cherry-pick for 1.20

**Review by hasheddan — COMMENTED** [review]
/hold we are past CP deadline

**Comment by SergeyKanzhelev** [comment]
> /hold we are past CP deadline

When was the CP deadline and when is the next wave of CP for 1.20?

**Comment by puerco** [comment]
Hey @SergeyKanzhelev my bad, I thought we could approve the cherry-pick based on the date it was filed, but as the leads pointed out to me, it has to be lgtm'ed and approved before the cherry-pick deadline (which was on March 12th). The criteria for inclusion are expressed on [the patch release schedule](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#cherry-picks) where you can also find the dates for the upcoming releases.

We'll approve and merge the PR for the April releases.

Sorry about that :(

**Comment by SergeyKanzhelev** [comment]
> We'll approve and merge the PR for the April releases.

thanks!

**Comment by vteratipally** [comment]
gentle reminder for the april release.

**Pull request merged**
