### PR TITLE
tighten and simplify owners in some staging repos

### PR DESCRIPTION
**Pull request by deads2k**
With the move to staging, we can have much cleaner owners across the related packages.  This pares down the list of OWNERS to better match for code and activity.  It should help get PRs directed to people more active and familiar with the areas for quicker review.

@kubernetes/sig-api-machinery-misc 
@lavalamp @smarterclayton ptal.

### CODE REVIEW

**Comment by deads2k** [comment]
@sttts I think I pared it down to active names.  have a look.

**Comment by sttts** [comment]
Looks sensible.

**Comment by deads2k** [comment]
@sttts I haven't heard objections and the issue just came up again: https://github.com/kubernetes/kubernetes/pull/46036#issuecomment-303363775 .  Let's move forward with this.

**Comment by sttts** [comment]
Looks good to me. @lavalamp @smarterclayton if anybody was left out, but should be reviewer/owner, we can readd them in a follow-up.

**Pull request merged**
