### PR TITLE
fix for flaky test. bundled the test assets into the dockerfile to re…

### LINKED ISSUE #109295: [sig-node] Node Performance Testing [Serial] [Slow] Run node performance testing with pre-defined workloads TensorFlow workload
### Which jobs are failing?

[sig-node-containerd#node-kubelet-containerd-performance-test](https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-performance-test)

### Which tests are failing?

E2eNode Suite.[sig-node] Node Performance Testing [Serial] [Slow] Run node performance testing with pre-defined workloads TensorFlow workload

### Since when has it been failing?

From the testgrid, it has been 1/2 flaky since the start of history (03/20/2022) and has been failing constantly (0/2) since 04/01/2022

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-performance-test

### Reason for failure (if possible)

```
E2eNode Suite: [sig-node] Node Performance Testing [Serial] [Slow] Run node performance testing with pre-defined workloads TensorFlow workload expand_less | 37s
-- | --
{ Failure test/e2e_node/node_perf_test.go:172 wait for pod "tensorflow-wide-deep-pod" to succeed Expected success, but got an error:     <*errors.errorString \| 0xc000722840>: {         s: "pod \"tensorflow-wide-deep-pod\" failed with reason: \"\", message: \"\"",     }     pod "tensorflow-wide-deep-pod" failed with reason: "", message: "" test/e2e/framework/pods.go:240}
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by xmcqueen**
…move the dependency on a blocked remote #109295

#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:

The flaking test is a slow load-generating test.

The flaking test is failing because it is **trying to pull down test assets from a remote** that is no longer legitimate.

This PR gathers the **minimum required test assets, bundles them into the docker image** - a total of 43 files.

The total size of the assets is about 10M from 2 data sets.

#### Which issue(s) this PR fixes:

Fixes #109295

#### Special notes for your reviewer:

- The tf_wide_deep.go test driver is changed to [remove the call to the remote,](test/e2e_node/perf/workloads/tf_wide_deep.go) and to specify the new data directory
- Dockerfile change to [stop pulling from the remote](test/images/node-perf/tf-wide-deep/Dockerfile), and to specify the new local directory with the test data for the default entrypoint.
- The test's tensorflow driver scripts are included and the stripped down libraries they require

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

[#97027
](https://github.com/kubernetes/kubernetes/issues/97027)

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/sig node
/sig testing

/assign @BenTheElder 

is this test really as important to bring such amount of files?

**Comment by xmcqueen** [comment]
> 
> is this test really as important to bring such amount of files?

I agree. This is the question. Is it worth it?  It's said to be just a load test.  My opinion is its not worth it, but I don't feel good about removing a test case and not replacing it with something equivalent.

**Comment by BenTheElder** [comment]
If we can’t switch to a valid remote, are we now solo maintaining a fork ..?

when we do put things form third parties in the repo they need to be clearly delineated due to licensing, we have third_party/ and vendor/ for those typically.

cc the rest of @kubernetes/dep-approvers

**Comment by xmcqueen** [comment]
> If we can’t switch to a valid remote, are we now solo maintaining a fork ..?
> 
> when we do put things form third parties in the repo they need to be clearly delineated due to licensing, we have third_party/ and vendor/ for those typically.
> 
> cc the rest of @kubernetes/dep-approvers

No. This code is already out-of-date. Its just a function load generator as far as I can tell.  If it must be up-to-date, then I can spend the effort to get it up-to-date, but the question of pulling in the remote assets would remain.  This version I have packaged up here provides a frozen working version of questionable value.

**Comment by xmcqueen** [comment]
I'll start looking for a replacement load test or something like that, since this general sense of the feedback seems to be that this PR's direction is questionable.

**Comment by xmcqueen** [comment]
I'm closing this down. None of us are enthusiastic about this approach.

**Comment by BenTheElder** [comment]
> If we can’t switch to a valid remote, are we now solo maintaining a fork ..?

I think I mis-skim-read this, we're just switching to a local copy.

Can we do a local copy in the image w/o checking in the sources here?
The images are built infrequently, if the remote will permit that (as opposed to downloading every single test run) that seems like a good solution 😅

**Pull request closed without merging**
