### PR TITLE
Revert "[kubeadm] use iteration instead of recursion in function"

### PR DESCRIPTION
**Pull request by deads2k**
Reverts kubernetes/kubernetes#36625

Removing the recursive call means that `n` is never updated, so you never succeed in the update, and you've creating an infinite loop.

Also, this entire bit of functionality should be a patch and you won't have to worry about conflicts.  

@luxas

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37813)

**Comment by deads2k** [comment]
@bruceauyeung

**Comment by luxas** [comment]
Deferring to @mikedanese, PTAL as soon as possible

@deads2k But has the last PR actually made something worse than it was before?
If fail to see the difference at a quick look...

I see it was broken from before, and I hadn't noticed that earlier (that we're never updating the values of the node, and it will just fail forever if once)
Also, as you say, a patch is the way to go for sure.

@deads2k Any possibility you can instead fix the behavior properly instead of reverting?
Thanks for the heads up!

**Comment by deads2k** [comment]
> Deferring to @mikedanese, PTAL as soon as possible
> 
> @deads2k But has the last PR actually made something worse than it was before?
> If fail to see the difference at a quick look...
> 
> I see it was broken from before, and I hadn't noticed that earlier (that we're never updating the values of the node, and it will just fail forever if once)
> Also, as you say, a patch is the way to go for sure.
> 
> @deads2k Any possibility you can instead fix the behavior properly instead of reverting?
> Thanks for the heads up!

The previous PR took it from "inelegant but works", to "completely broken and creating flaky infinite loops".  This revert should be merged and then someone closer to the area can create patch instead.

**Comment by deads2k** [comment]
> I see it was broken from before, and I hadn't noticed that earlier (that we're never updating the values of the node, and it will just fail forever if once)
> Also, as you say, a patch is the way to go for sure.

The recursive technique looked up a fresh value and relabeled that.  I caught it in a drive-by looking for why our queue is borked.

**Comment by luxas** [comment]
> The recursive technique looked up a fresh value and relabeled that.

Ah, now I see. Silly of me to miss that :sweat_smile: . LGTM to revert

> I caught it in a drive-by looking for why our queue is borked.

Whoa, is this affecting the queue in any way?
Or do you mean that you found this while looking though other failures?

**Comment by deads2k** [comment]
> Whoa, is this affecting the queue in any way?
> Or do you mean that you found this while looking though other failures?

I don't think this is it, but this still isn't good for anyone using this.  Given how frequently nodes are updated, you're pretty like to hit it.

I'll let someone close to `kubeadm` decide if this needs to be priority bumped to be stable-ish in master.

**Comment by luxas** [comment]
@mikedanese or @roberthbailey can decide the priority
AFAIU, reverts are higher priority than "normal" PRs, but I'm not sure about what the conventions are

**Comment by bruceauyeung** [comment]
@deads2k @luxas i am very sorry to make such a mistake ! 
shame on me ...

**Comment by luxas** [comment]
@mikedanese Is `kubeadm init` broken right now? If so, we should bump priority...

@bruceauyeung No worries! We all make mistakes

**Pull request merged**
