### PR TITLE
Fix leader election lock release when using LeaseLocks

### PR DESCRIPTION
**Pull request by zachomedia**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

Resolves lock release issues with leader election when using LeaseLocks when `ReleaseOnCancel` is set to `true` (like in the example https://github.com/kubernetes/client-go/blob/master/examples/leader-election/main.go):

> Failed to release lock: Lease.coordination.k8s.io "example" is invalid: spec.leaseDurationSeconds: Invalid value: 0: must be greater than 0

This PR updates the `LeaderElectionRecord` generated in the release function to:

1. Set the `LeaseDurationSeconds` to 1 so that it's valid with `LeaseLocks`
2. Fill in `RenewTime` and `AcquireTime` since it panics without that information

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by zachomedia** [comment]
Is it possible to get an update on this pull request?

cc @resouer @mikedanese @deads2k

**Comment by zachomedia** [comment]
/remove-lifecycle stale

cc @resouer @mikedanese @deads2k

**Comment by zachomedia** [comment]
@resouer @mikedanese @deads2k Is there any possibility at getting this PR looked at? While it seems minor, I did spend the time to find the issue and a fix for it. It would be great to receive some feedback (it may not be the right way to fix this) and/or have it merged into the actual code base (if it's a reasonable fix), especially since it's been open for over 8 months now.

**Comment by mikedanese** [comment]
Hi @zachomedia, thanks for the fix. Can you please add a test to demonstrate the issue and so that we don't regress when we fix it?

**Comment by zachomedia** [comment]
@mikedanese I've added a test. However, one thing I noted is that the test doesn't seem to fail if I remove my fix but it does fail against an actual cluster. Does the fake client run object validation?

**Comment by zachomedia** [comment]
@mikedanese Sorry to bother you again, but wanted to check if you've had a chance to check my last update with the test + comment

**Comment by mikedanese** [comment]
Thanks for the ping and adding a test. Sorry I missed this.

**Comment by liggitt** [comment]
/hold 

https://github.com/kubernetes/kubernetes/pull/88192 is touching the same place but handles the leader release differently. @smarterclayton which should we proceed with?

**Comment by mikedanese** [comment]
@liggitt the two changes are functionally equivalent, so it's just a matter of what information we want to convey to the user until the next leader picks up. I like that this has a test.

**Comment by ChrsMark** [comment]
Hey folks! Would be nice to have it in soon since it's has been around for some time now and it seems that it's just lacks the final ok to go. @liggitt @mikedanese is there anything blocking this?

**Comment by liggitt** [comment]
/test all
/hold cancel

+1 for the test

**Comment by zachomedia** [comment]
@liggitt I'm not sure what to do about the tests, it seems to be a different one that fails every time. I think a run of that test passed based on https://prow.k8s.io/pr-history/?org=kubernetes&repo=kubernetes&pr=80954 though?

**Comment by dprotaso** [comment]
Is this PR eligible to cherry pick?

**Comment by liggitt** [comment]
yes

**Comment by dprotaso** [comment]
Done!

**Pull request merged**
