### PR TITLE
[Federation][e2e] Provide less strict timeouts on destruction paths

### PR DESCRIPTION
**Pull request by csbell**
The CI tests show that some timeouts are too strict. This PR harmonizes some of the "ForeverWaitTimeouts" in one place. The goal is to reduce the e2e flakiness.

### CODE REVIEW

**Comment by csbell** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by csbell** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by csbell** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by csbell** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by madhusudancs** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/e2e_federation/ingress.go, line 239 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087#-KfDu28QVZPT3B1p7pEY:-KfDu28QVZPT3B1p7pEZ:b1adqls) ([raw file](https://github.com/kubernetes/kubernetes/blob/442e920085328ce28a5105888848e5baa3c8eb1e/test/e2e_federation/ingress.go#L239)):*
> ```Go
> 					deleteIngressOrFail(f.FederationClientset, ns, jig.ing.Name, nil)
> 					for clusterName, cluster := range clusters {
> 						deleteClusterIngressOrFail(clusterName, cluster.Clientset, ns, jig.ing.Name)
> ```

One difference is, this loop explicitly waits until the Ingresses are gone from all the underlying clusters. `deleteAllIngressesOrFail` in the parent `AfterEach` block however deletes the Ingresses in federation and depends on cascading deletion to delete the cluster Ingresses. It doesn't wait for them to be deleted.

Do we need to move this code to move to the parent AfterEach block instead of just getting rid of it.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087)*

**Comment by madhusudancs** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087)*

**Comment by csbell** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by csbell** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by csbell** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/e2e_federation/ingress.go, line 239 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087#-KfDu28QVZPT3B1p7pEY:-KfND_BdnsFvwldLHqBs:b-3fxdvb) ([raw file](https://github.com/kubernetes/kubernetes/blob/442e920085328ce28a5105888848e5baa3c8eb1e/test/e2e_federation/ingress.go#L239)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

One difference is, this loop explicitly waits until the Ingresses are gone from all the underlying clusters. `deleteAllIngressesOrFail` in the parent `AfterEach` block however deletes the Ingresses in federation and depends on cascading deletion to delete the cluster Ingresses. It doesn't wait for them to be deleted.

Do we need to move this code to move to the parent AfterEach block instead of just getting rid of it.
</blockquote></details>

I've restored this part. I also don't think we want to move it to the parent AfterEach since there are tests above to test for Orphan={true,false}.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087)*

**Comment by madhusudancs** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/e2e_federation/ingress.go, line 239 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087#-KfDu28QVZPT3B1p7pEY:-KfOsGfOT1eUqYfcugxq:b-ylvidk) ([raw file](https://github.com/kubernetes/kubernetes/blob/442e920085328ce28a5105888848e5baa3c8eb1e/test/e2e_federation/ingress.go#L239)):*
>  I also don't think we want to move it to the parent AfterEach since there are tests above to test for Orphan={true,false}.

`orphanDependents={true,nil}` and `orphanDepenedents=false` need different treatments. When `orphanDependents={true,nil}`, `verifyCascadingDeletionForIngress()` method does neither check nor wait until all the cluster Ingresses are gone. But it does check when `orphanDependents=false`. So in the former case you still need to ensure that the cluster Ingresses are really gone before tearing down the clusters, but you don't have to in the latter case. Moreover, it doesn't hurt that much to attempt to delete the objects twice except for the time it takes. Anyway, namespace cleanup in the final tear down phase should take care of deleting all the objects and hopefully the controllers have enough time to free up GCP resources before we tear down the clusters.

---

*[test/e2e_federation/ingress.go, line 226 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087#-KfOuQgyJRqy6DUCA0QO:-KfOuQgyJRqy6DUCA0QP:b-hykzfw) ([raw file](https://github.com/kubernetes/kubernetes/blob/7f9e13d40667b5c2cce06520350e72d30dc80690/test/e2e_federation/ingress.go#L226)):*
> ```Go
> 		})
> 
> 		var _ = Describe("pinky Ingress connectivity and DNS", func() {
> ```

pinky is back :)

---

*[test/e2e_federation/util.go, line 532 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087#-KfOudY3KagwvD-npn-2:-KfOudY3KagwvD-npn-3:b-6xt78e) ([raw file](https://github.com/kubernetes/kubernetes/blob/7f9e13d40667b5c2cce06520350e72d30dc80690/test/e2e_federation/util.go#L532)):*
> ```Go
> 	Expect(pod).ToNot(BeNil())
> 	err := c.Clientset.Core().Pods(pod.Namespace).Delete(pod.Name, metav1.NewDeleteOptions(0))
> 	msg_fmt := fmt.Sprintf("Deleting Pod %q in namespace %q in cluster %q %%v", pod.Name, pod.Namespace, c.name)
> ```

s/msg_fmt/msgFmt/

---

*[test/e2e_federation/util.go, line 534 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087#-KfOusZJ9_egwp7En_YX:-KfOusZJ9_egwp7En_YY:bwkxr5) ([raw file](https://github.com/kubernetes/kubernetes/blob/7f9e13d40667b5c2cce06520350e72d30dc80690/test/e2e_federation/util.go#L534)):*
> ```Go
> 	msg_fmt := fmt.Sprintf("Deleting Pod %q in namespace %q in cluster %q %%v", pod.Name, pod.Namespace, c.name)
> 	if errors.IsNotFound(err) {
> 		framework.Logf(msg_fmt, "does not exist. No Need to delete it.")
> ```

Was the "Need" capitalization intentional?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087)*

**Comment by csbell** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/e2e_federation/ingress.go, line 239 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087#-KfDu28QVZPT3B1p7pEY:-KfUn9IrQRP6H8jrH0Ef:b-a671fj) ([raw file](https://github.com/kubernetes/kubernetes/blob/442e920085328ce28a5105888848e5baa3c8eb1e/test/e2e_federation/ingress.go#L239)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

>  I also don't think we want to move it to the parent AfterEach since there are tests above to test for Orphan={true,false}.

`orphanDependents={true,nil}` and `orphanDepenedents=false` need different treatments. When `orphanDependents={true,nil}`, `verifyCascadingDeletionForIngress()` method does neither check nor wait until all the cluster Ingresses are gone. But it does check when `orphanDependents=false`. So in the former case you still need to ensure that the cluster Ingresses are really gone before tearing down the clusters, but you don't have to in the latter case. Moreover, it doesn't hurt that much to attempt to delete the objects twice except for the time it takes. Anyway, namespace cleanup in the final tear down phase should take care of deleting all the objects and hopefully the controllers have enough time to free up GCP resources before we tear down the clusters.


</blockquote></details>

I think deleteAllIngressesOrFail in the outermost Aftereach will satisfy your requirement. So far, there's no evidence that the e2e ingresses are leaking. Only services.

---

*[test/e2e_federation/ingress.go, line 226 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087#-KfOuQgyJRqy6DUCA0QO:-KfUnQcgea2XNkj-Mnlu:b4espi3) ([raw file](https://github.com/kubernetes/kubernetes/blob/7f9e13d40667b5c2cce06520350e72d30dc80690/test/e2e_federation/ingress.go#L226)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

pinky is back :)
</blockquote></details>

unpinked.

---

*[test/e2e_federation/util.go, line 532 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087#-KfOudY3KagwvD-npn-2:-KfUn6CIk8p6iuuwBFbM:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/7f9e13d40667b5c2cce06520350e72d30dc80690/test/e2e_federation/util.go#L532)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

s/msg_fmt/msgFmt/
</blockquote></details>

Done.

---

*[test/e2e_federation/util.go, line 534 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087#-KfOusZJ9_egwp7En_YX:-KfUn7UR1FPOp9pP4LCG:bt2vr1b) ([raw file](https://github.com/kubernetes/kubernetes/blob/7f9e13d40667b5c2cce06520350e72d30dc80690/test/e2e_federation/util.go#L534)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

Was the "Need" capitalization intentional?
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087)*

**Comment by madhusudancs** [comment]
/lgtm

---

Reviewed 1 of 2 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/e2e_federation/ingress.go, line 239 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087#-KfDu28QVZPT3B1p7pEY:-KfUoiSp704l_yRzdA2T:b-3pkxxu) ([raw file](https://github.com/kubernetes/kubernetes/blob/442e920085328ce28a5105888848e5baa3c8eb1e/test/e2e_federation/ingress.go#L239)):*
> So far, there's no evidence that the e2e ingresses are leaking. Only services.

Ok, fair enough.

---

*[test/e2e_federation/ingress.go, line 226 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087#-KfOuQgyJRqy6DUCA0QO:-KfUofyQONQHQlJKpwNf:b2nh59u) ([raw file](https://github.com/kubernetes/kubernetes/blob/7f9e13d40667b5c2cce06520350e72d30dc80690/test/e2e_federation/ingress.go#L226)):*
<details><summary><i>Previously, csbell (Christian Bell) wrote…</i></summary><blockquote>

unpinked.
</blockquote></details>

;-)

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087#-:-KfUp4gjsDOSVIGwvjaU:b-8ks5qa)*

**Comment by madhusudancs** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43087)*

**Review by madhusudancs — APPROVED** [review]

**Comment by csbell** [comment]
@k8s-bot gce e2e test this

**Pull request merged**
