### PR TITLE
[apiserver] remove magic number

### PR DESCRIPTION
**Pull request by gaurav1086**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Remove magic number. Error Code for reference: https://golang.org/src/net/http/status.go#L54
**Which issue(s) this PR fixes**:

Fixes #
N/A
**Special notes for your reviewer**:
N/A
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
/assign @deads2k 
for approval. Thanks.

**Comment by gaurav1086** [comment]
@deads2k can we merge this ? Thanks.

**Comment by kensipe** [comment]
@deads2k this seems ready to merge

**Comment by gaurav1086** [comment]
@deads2k @kensipe thanks, its been hanging around for long, can we merge this ?

**Comment by deads2k** [comment]
heh, sure.

/approve

**Pull request closed without merging**
