### PR TITLE
reduce resource quota version conflict in controller

### PR DESCRIPTION
**Pull request by Nebulazhang**
**What this PR does / why we need it**:
We can reduce resource quota version conflict.
1. Before this PR: 
There are some workers to  call this function "syncResourceQuotaFromKey" parallel. In this function, resource quota will be update!  Every worker will be blocking if the queue is empty. If some same keys come at the same time (because a quota key will be sent to controller every time delete a pod),  every worker is awakened to deal with the same key. This will lead to update resource quota parallel and many version conflicts occur.

2. After this PR:
Workers are not waiting, they will deal with the key per second. And only unique key will be hold in the queue. We can reduce many conflicts.

3. Result:
Firstly I create a quota. Secondly I create a deployment that there are 30 pod in this deployment. And I delete this deployment.
**Before this optimization**, I observe that there are many log like this `Operation cannot be fulfilled on resourcequotas \"pod-quota\": the object has been modified;`
**After this optimization**, I observe only one log.

4. Other Reason
We can reduce the possibility of pod create  error by reducing resource quota version conflict. Because api-server will also update resource quota when we create a pod. Reducing concurrency of updating the same resource quota will reduce the conflict error by create pod!

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
#67761
**Special notes for your reviewer**:
Maybe there are similar problems in other controllers.
**Release note**:
None

```release-note

```

### CODE REVIEW

**Comment by yue9944882** [comment]
/hold

thx for fixing this. plz open this pull onto master, and then cherry-pick it back to other releases after its merged. also, 1.8 is no longer actively maintained unless critical hotfixes.

**Comment by Nebulazhang** [comment]
I have registered CLA signature, please verify

**Comment by neolit123** [comment]
@Nebulazhang 
if you have CLA problems you can contact the CNCF help desk.

/kind bug
/sig api-machinery

**Pull request closed without merging**
