### PR TITLE
Fix panic when errors are nil

### PR DESCRIPTION
**Pull request by feiskyer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Fix a stupid panic when errors are nil.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/kind bug
/sig cloud-provider
/assign @andyzhangx

### CODE REVIEW

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by timuthy** [comment]
@feiskyer can you cherry-pick this change for `release-1.15`?

**Comment by feiskyer** [comment]
@timuthy have you observed panic on 1.15 branch?

**Comment by feiskyer** [comment]
@mvladev  Thanks for the cherry-pick. I have observed panic in 1.15 locally.

**Pull request merged**
