### PR TITLE
Update to aws-sdk-go v0.9.9

### PR DESCRIPTION
**Pull request by tpounds**
Updates the aws-sdk-go dependency to the latest release version. It also replaces the custom metadata client code with the version supplied by the SDK.

### CODE REVIEW

**Comment by tpounds** [comment]
AFAICT, the build checks failed due to a broken godep verification script. Appears to be fixed by PR #14198.

**Comment by justinsb** [comment]
Thanks for this, and don't worry about duplicating my PR - happy to use yours!

Do you have any insight into whether we _should_ update?  My concern is that I haven't seen any documentation for _why_ they changed the naming (capitalization) convention, and I'm kind of worried that they might change their mind back again.  This was more of a concern when 0.9.5 had only just been released a few days previously, admittedly!

**Comment by tpounds** [comment]
It looks like the change is to make the structures consistent with the API documentation. IIRC, most AWS services use Java conventions. Quote from the [v0.9.0rc1 release notes](https://aws.amazon.com/releasenotes/2948141298714307).

> This release removes the inflections and inflection maps from generated service API operations and Input/Output structs. This breaking change means that many generated API operation name, and struct field names had their casing inflections changed to match the inflection defined by the AWS service.

I'm assuming the naming changes will stick around since they are making it consistent with the actual APIs. It looks like some portion of the code is generated from the [schemas].(https://github.com/aws/aws-sdk-go/search?l=json&q=Id) I guess we could always update again if they change their mind...

**Comment by eparis** [comment]
#14198 has merged.  rebase should let you get clean CI

**Comment by tpounds** [comment]
Thanks @eparis!

**Comment by justinsb** [comment]
And I think it is reasonable to update now (so it makes it into 1.1), because we will likely want to update during the 1.1 lifetime.  It will be painful if they revert (nothing will cherry-pick cleanly), but if we don't update we are basically guaranteed that pain.  I you can rebase @tpounds so we get passing CI I think we should go for it :-)

**Comment by tpounds** [comment]
Woohoo! Finally passed. :)

**Comment by justinsb** [comment]
LGTM

**Comment by tpounds** [comment]
Is this going to be merged before v1.1?

**Comment by bgrant0607** [comment]
Please rebase.

**Comment by justinsb** [comment]
This LGTM.  I would like to see this in 1.1; it is annoying that upstream renamed much of their API, but I think it'll be even more annoying to have to deal with for any cherry-pick into 1.1.

**Pull request merged**
