### PR TITLE
Automated cherry pick of #93583: support ipv6 in e2e policy tests

### PR DESCRIPTION
**Pull request by JacobTanenbaum**
Cherry pick of #93583 on release-1.19.

#93583: support ipv6 in e2e policy tests

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by JacobTanenbaum** [comment]
/priority/important-soon

**Comment by aojea** [comment]
this is a bug in the e2e framework, network policy tests does not run in IPv6 and is something we'd like to have in 1.19.
The backport only touches one file of the e2e framework test/e2e/network/network_policy.go , so it is not risky at all.
/lgtm
/ok-to-test
/assign @alejandrox1 @danwinship

**Comment by cpanato** [comment]
from parent PR.
/kind failing-test

**Comment by aojea** [comment]
/assign @MrHohn 
need approval here, thanks :smile:

**Review by MrHohn — APPROVED** [review]
/approve

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
