### PR TITLE
Ignore 'PullNever' policy for image locality priority.

### LINKED ISSUE #40639: Ignore 'PullNever' policy for image locality priority.
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Kubernetes version** (use `kubectl version`):
master

**Description**:
There's three different image pull policy here: Never, Always, PullIfNotPresent; the image locality should only consider the containers with PullIfNotPresent policy, there's no different for the other two policy in different node.

### PR DESCRIPTION
**Pull request by k82cn**
fixes #40639

### CODE REVIEW

**Comment by k82cn** [comment]
@k8s-bot cvm gke e2e test this

**Comment by k82cn** [comment]
@k8s-bot gci gce e2e test this

**Comment by liggitt** [comment]
I don't think this is correct. See comments in https://github.com/kubernetes/kubernetes/issues/40639#issuecomment-275855886

**Comment by liggitt** [comment]
will defer to @davidopp

**Pull request closed without merging**
