### PR TITLE
Add Brian Grant to pkg/OWNERS

### PR DESCRIPTION
**Pull request by pmorie**
Fairly self explanatory

@bgrant0607

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31803)

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks, but I asked to be removed from this file: #27402

I'm awaiting the approvers/reviewers split before being added back. 

Note that I'm in the top-level OWNERS: #30743

And am an owner of the github org.

I suggest refining the incubator sponsorship criteria for now instead:
https://github.com/kubernetes/community/blob/master/incubator.md

cc @philips

**Comment by bgrant0607** [comment]
@pmorie Any particular reason why you didn't set the PR assignee when you created the PR rather than or in addition to just notifying me? We're trying to figure out how to reduce the number of unnecessary manual PR reassignments.

**Comment by bgrant0607** [comment]
ok to test

**Comment by pmorie** [comment]
@bgrant0607 

> Any particular reason why you didn't set the PR assignee when you created the PR rather than or in addition to just notifying me? We're trying to figure out how to reduce the number of unnecessary manual PR reassignments.

Just human fallibility

**Comment by philips** [comment]
Now that we have a top-level OWNERS I am OK changing that criteria in incubator. I think this can be closed then.

**Comment by pmorie** [comment]
I'll change the criteria in incubator, sorry for the confusion.

**Pull request closed without merging**
