### PR TITLE
Automated cherry pick of #70392: Lookup PX api port from k8s service

### PR DESCRIPTION
**Pull request by harsh-px**
Cherry pick of #70392 on release-1.11.

#70392: Lookup PX api port from k8s service

### CODE REVIEW

**Comment by foxish** [comment]
@saad-ali, PTAL for lgtm+approval.

**Comment by harsh-px** [comment]
@saad-ali or @jsafrane : Can you add a lgtm + approval?

This is a cherry pick and has already made it to 1.13 and master branch.

**Pull request merged**
