### PR TITLE
util: add test case for WSL kernel version parsing

### PR DESCRIPTION
**Pull request by mauri870**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This PR adds a test case for parsing a WSL 2 kernel version.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bart0sh** [comment]
/lgtm
/assing @SergeyKanzhelev @mrunalp 
for approval

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
