### PR TITLE
Create federation dns zone if missing

### PR DESCRIPTION
**Pull request by ghost**
1. Added Zones.Add() method to generic dnsprovider interface, as well as Google and AWS implementations.
2. Automatically add the configured zone name to the dnsprovider if it does not already exist.

### CODE REVIEW

**Comment by mml** [comment]
Doesn't compile.

**Comment by quinton-hoole** [comment]
Fixed compile error.  Sorry 'bout that.  Lets see how the tests do now.

**Comment by mml** [comment]
This is a good behavior but also a little surprising.  I'm not sure where we'll document it, but we should make it clear that the federation controller will do this.

**Comment by quinton-hoole** [comment]
I concur @mml.  I'll make sure that I document it clearly in the admin guide.  Come to think of it I should also add something to the description of the domain in Cloud DNS and Route 53 that the domain was auto-created by Cluster Federation.  I'll send a followup PR for that some time.  Not for 1.3 though.

**Comment by quinton-hoole** [comment]
Rebased.  Re-adding LGTM.

**Comment by mml** [comment]
:sob:

```
 I0621 15:58:19.238570       1 servicecontroller.go:269] DNS zone "kubernetes- federation.test." not found.  Creating DNS zone "kubernetes-federation.test." .
 panic: interface conversion: interfaces.ManagedZone is *internal.ManagedZone,  not internal.ManagedZone
 
 goroutine 1 [running]:
 panic(0x1a87280, 0xc820495400)
         /usr/local/go/src/runtime/panic.go:481 +0x3e6
 k8s.io/kubernetes/federation/pkg/dnsprovider/providers/google/clouddns/intern al.(*ManagedZonesService).Create(0xc820024358, 0xc8204369a0, 0x7, 0x7f02bab7a 330, 0xc820110160, 0x0, 0x0)
         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes /federation/pkg/dnsprovider/providers/google/clouddns/internal/managed_zones_ service.go:31 +0x74
 k8s.io/kubernetes/federation/pkg/dnsprovider/providers/google/clouddns.Zones. Add(0x7f02babacc90, 0xc820024358, 0xc82012f120, 0x7f02bab7a360, 0xc8204f48c0,  0x0, 0x0, 0x0, 0x0)
         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes /federation/pkg/dnsprovider/providers/google/clouddns/zones.go:47 +0x1c2
 k8s.io/kubernetes/federation/pkg/dnsprovider/providers/google/clouddns.(*Zone s).Add(0xc82012f140, 0x7f02bab7a360, 0xc8204f48c0, 0x0, 0x0, 0x0, 0x0)
         <autogenerated>:4 +0xd0
 k8s.io/kubernetes/federation/pkg/federation-controller/service.(*ServiceContr oller).init(0xc8203226c0, 0x0, 0x0)
         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes /federation/pkg/federation-controller/service/servicecontroller.go:274 +0x486
 k8s.io/kubernetes/federation/pkg/federation-controller/service.(*ServiceContr oller).Run(0xc8203226c0, 0xa, 0xc820050de0, 0x0, 0x0)
         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes /federation/pkg/federation-controller/service/servicecontroller.go:235 +0x31
 k8s.io/kubernetes/federation/cmd/federation-controller-manager/app.StartContr ollers(0xc82043c5b0, 0xc820186000, 0x0, 0x0)
         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes /federation/cmd/federation-controller-manager/app/controllermanager.go:127 +0 x332
 k8s.io/kubernetes/federation/cmd/federation-controller-manager/app.Run.func2( )
         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes /federation/cmd/federation-controller-manager/app/controllermanager.go:109 +0 x30
 k8s.io/kubernetes/federation/cmd/federation-controller-manager/app.Run(0xc820 43c5b0, 0x0, 0x0)
         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes /federation/cmd/federation-controller-manager/app/controllermanager.go:113 +0 x306
 main.main()
         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes /federation/cmd/federation-controller-manager/controller-manager.go:48 +0x1c7
```

**Comment by mml** [comment]
I don't get this conversion error, actually.  The type assertion in google/c/i/managed_zone.go is checking the struct type, not the pointer type.

**Pull request merged**
