### PR TITLE
Use local_ipv4 when public_ipv4 is not present.

### PR DESCRIPTION
**Pull request by gswallow**

### CODE REVIEW

**Comment by mikedanese** [comment]
cc @justinsb

**Comment by mikedanese** [comment]
@k8s-bot ok to test issue: #IGNORE

**Comment by justinsb** [comment]
Awesome!  LGTM.  And I learned a nice way to do express a fallback in bash!

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please github issue: #IGNORE

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please github issue: #20916

**Pull request merged**
