### PR TITLE
Fix example command for generating CA cert hashes

### PR DESCRIPTION
**Pull request by Mattias-**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by ereslibre** [comment]
Thank you @Mattias-!

Can you please fix the following files as well:

* https://github.com/ereslibre/kubernetes/blob/f430a47b606e7863f296603a3d9f6a1655539cf1/cmd/kubeadm/app/apis/kubeadm/types.go#L383 (internal type)
* https://github.com/ereslibre/kubernetes/blob/f430a47b606e7863f296603a3d9f6a1655539cf1/cmd/kubeadm/app/apis/kubeadm/v1beta1/types.go#L364 (`v1beta1`)
* https://github.com/ereslibre/kubernetes/blob/f430a47b606e7863f296603a3d9f6a1655539cf1/cmd/kubeadm/app/util/pubkeypin/pubkeypin_test.go#L51 (a test, but for completion, detected this typo as well)

/ok-to-test
/cc @rosti 
(for the proposed `v1beta3`)

**Comment by Mattias-** [comment]
Thanks for the swift response @ereslibre. I fixed those files now as well.

**Comment by neolit123** [comment]
@Mattias- 
thank you for the fix, it looks valid.

however, i'm in favor of removing example bash commands from our API types comments.
@rosti @ereslibre WDYT?

**Comment by ereslibre** [comment]
> however, i'm in favor of removing example bash commands from our API types comments.
> @rosti @ereslibre WDYT?

I'm fine removing the examples from the API documentation.

**Comment by rosti** [comment]
@neolit123 +1 from me as well. External command lines are subject to less strict rules for command line interface compatibility. Hence, those can change and become invalid over time.

**Comment by neolit123** [comment]
closing and logging an issue if someone wants to take over:
https://github.com/kubernetes/kubeadm/issues/2018

/close

**Pull request closed without merging**
