### PR TITLE
fix defer in loop and optimize test cases with explicit field name

### PR DESCRIPTION
**Pull request by major1201**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Fix defer in loop and optimize test cases with explicit field name to make it more readable.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by major1201** [comment]
@endocrimes Hi, I see you've moved this from Needs Reviewer to Waiting on Author in SIG Node PR Triage, any advice I can help?

**Comment by endocrimes** [comment]
@major1201 not on purpose 😓 - i must've misclicked

**Review by endocrimes — APPROVED** [review]
/lgtm

fixes readability which is nice, also fixes a test resourec leaking bug, which is 💯 .

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
