### PR TITLE
Fix error message typo in conntrack

### PR DESCRIPTION
**Pull request by z1cheng**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Fix typo to ensure that it will not be misunderstood.

Typo: `greater then -> greater than`

#### Which issue(s) this PR fixes:

Fixes None

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by z1cheng** [comment]
Hi @smarterclayton @thockin, could you please review and approve this PR when you're free? Thanks! 

/cc @smarterclayton @thockin

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by TernencezzZ** [comment]
good job~maybe you should have a relax starting League of L...

**Pull request merged**
