### PR TITLE
kubectl: move printObjectSpecificMessage in factory

### PR DESCRIPTION
**Pull request by 0xmichalis**
@smarterclayton @kubernetes/kubectl PTAL

### CODE REVIEW

**Comment by smarterclayton** [comment]
Compile failure.

**Comment by kargakis** [comment]
> Compile failure.

Had to move unit tests around, updated

**Comment by AdoHe** [comment]
@kargakis @smarterclayton I am just wondering whether we should put so many things in `Factory`, we have a so big Factory struct now, it seems can get bigger and bigger, which makes it hard to control and understand.

**Comment by smarterclayton** [comment]
Factory itself could be split, but it essentially prevents us from
littering our command code with encapsulation problems.  For example, this
error only was printed in create, but it should also have been printed in
apply (and wasn't).  None of our commands should be deeply coupled to
anything in pkg/api - the abstractions in factory are there to provide the
hook.

On May 24, 2016, at 10:37 AM, TonyAdo <notifications@github.com> wrote:

@kargakis <https://github.com/kargakis> @smarterclayton
<https://github.com/smarterclayton> I am just wondering whether we should
put so many things in Factory, we have a so big Factory struct now, it
seems can get bigger and bigger, which makes it hard to control and
understand.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/26161#issuecomment-221291559>

**Comment by kargakis** [comment]
@k8s-bot test this issue: https://github.com/kubernetes/kubernetes/issues/25645

**Comment by kargakis** [comment]
@smarterclayton ping

**Comment by kargakis** [comment]
pure rebase, reapplying lgtm

**Comment by kargakis** [comment]
@k8s-bot unit test this issue #IGNORE

**Pull request merged**
