### PR TITLE
ignore order of containers status allocated resources

### LINKED ISSUE #126357: [Flaking Test] TestUpdateAllocatedResourcesStatus
### Which jobs are flaking?

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit

### Which tests are flaking?

TestUpdateAllocatedResourcesStatus

### Since when has it been flaking?

Few days ago

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind flake

#### Which issue(s) this PR fixes:

Fixes #126357

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ffromani** [comment]
/cc @SergeyKanzhelev 

Thanks a ton @pacoxu 

fix LGTM. Not setting the label because I'd like to quickly discuss first if we want to do the sorting in the test or in the production code.

**Comment by ffromani** [comment]
/priority important-soon
/triage accepted

flake removal should happen ASAP

**Comment by pacoxu** [comment]
> fix LGTM. Not setting the label because I'd like to quickly discuss first if we want to do the sorting in the test or in the production code.

Sorting in production code seems to be an commitment to users. But the order seems to be not that important in my mind.

**Comment by ffromani** [comment]
> > fix LGTM. Not setting the label because I'd like to quickly discuss first if we want to do the sorting in the test or in the production code.
> 
> Sorting in production code seems to be an commitment to users. But the order seems to be not that important in my mind.

I tend to agree. Let's just hear from @SergeyKanzhelev which is sheparding the KEP which drove this code.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Comment by SergeyKanzhelev** [comment]
/milestone v1.31

Test only fix should be good to go in 1.31

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
