### PR TITLE
 refactor volume util files

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # https://github.com/kubernetes/kubernetes/issues/44460

**Special notes for your reviewer**:
/assign @jsafrane @msau42 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wackxu** [comment]
@msau42 Yeah, that is good, Thanks for your review.

**Comment by wackxu** [comment]
@msau42 @jsafrane Updated, PTAL

**Comment by wackxu** [comment]
@msau42 @jsafrane It is tedious to do the rebase work, PTAL, let us move it forward

**Comment by msau42** [comment]
I did a side by side comparison of the removed and added code.  I am ok with the new layout.

I only wonder how many external repos could be impacted by moving some of these packages if they need to upgrade their dependencies.

**Comment by jsafrane** [comment]
/assign @thockin 
for approval

**Comment by jsafrane** [comment]
I expect there will be several rounds of rebases, I'd probably wait for approval first...

**Comment by thockin** [comment]
I don't have bandwidth for a full review on this.  I trust Jan's review.

/approve

**Comment by wackxu** [comment]
@msau42 @jsafrane Rebased， PTAL

**Comment by jsafrane** [comment]
I'm afraid that #58710 has broken this PR. Some additional changes in gce_pd_block.go are needed :-(.

**Comment by wackxu** [comment]
@jsafrane @thockin Rebased and the CI is green now, PTAL

**Comment by wackxu** [comment]
@msau42 @jsafrane @thockin Make another rebase and  the CI is green again, PTAL

**Comment by jsafrane** [comment]
aehm, another conflict

**Comment by jsafrane** [comment]
Finally!
@wackxu, thanks for your patience.

**Pull request merged**
