### PR TITLE
Support shell completion for the type/name form

### LINKED ISSUE #1180: Enable `kubectl` to complete `kubectl get pod/...`
**What would you like to be added**:
Testing in PowerShell, `kubectl` can complete the pod name if you use a space:
```
kubectl get pod <pod-name>
```
However if you use a forward-slash the completion doesn't work:
```
kubectl get pod/<pod-name>
```

**Why is this needed**:
It would be nice if the completions supported both formats since `kubectl` itself accepts both formats.

### LINKED ISSUE #94927: bash completion for `kubectl exec POD -c`
**What would you like to be added**:

Bash-completion for `kubectl exec POD -c` into a specific container. Actually, choosing the container with bash_completion works with `kubectl logs`, but not with `exec`.

Let's make an example:

```
# kubectl -n build-storage get po
NAME             READY   STATUS    RESTARTS   AGE
static-sites-0   2/2     Running   0          4d
# k -n build-storage logs static-sites-0  [TAB-TAB]
http  ssh   
```

BUT

```
kubectl -n build-storage exec -ti static-sites-0 -c [TAB-TAB] static-sites-0 static-sites-0 static-sites-0 static-sites-0`
```

**Why is this needed**:

Because it is missing :)

### PR DESCRIPTION
**Pull request by marckhouzam**
#### What type of PR is this?

/kind feature
/sig cli

#### What this PR does / why we need it:

In https://github.com/kubernetes/kubernetes/pull/106755#issuecomment-1047252647 @brianpursley brought up the fact that the shell completion logic did not handle the `<type>/<name>` format for the specification of resources.

Following his suggestion and guidance, this PR adds the necessary logic to:
1.  support shell completion for the `<type>/<name>` format for all commands that support it
1. teaches the 'kubectl exec' command how to complete its `--container/-c` flag
1. for commands that work on pods, suggest completion choices of resource types that contain pods (see examples below)

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubectl/issues/1180
Fixes #94927
Supersedes #106755

#### Special notes for your reviewer:

This could have been 3 different PRs but 2 of these would have been very small so I chose to submit them all as one, to facilitate the review effort (testing everything at once).  But I can split them if required.

I feel most user-facing behaviour changes are straight-forward and should not cause any surprise to users.
The one change that is more surprising and needs special attention is the fact that for the commands:
- attach
- exec
- logs
- port-forward

completion choices will now include resource types, not just pod names.  For example:
```
$ kubectl port-forward <TAB>
bar-pod-fc87855b6-8rmqt                              baz-pod-fc87855b6-8rmqt
daemonsets/           pods/                          services/
deployments/          replicasets/                   statefulsets/
jobs/                 replicationcontrollers/        test-pod-fc87855b6-8rmqt
```

#### Does this PR introduce a user-facing change?

```release-note
kubectl now supports shell completion for the <type>/<name> format for specifying resources.

kubectl now provides shell completion for container names following the --container/-c flag of the exec command.

kubectl's shell completion now suggests resource types for commands that only apply to pods.
```

#### Examples of improvements
<details>
<summary>The new completion of containers for ' kubectl exec'</summary>

```
# NEW: container completion (normal form)
kubectl exec httpbin-777f4d8df9-zd9gd -c is<TAB>
kubectl exec httpbin-777f4d8df9-zd9gd -c istio-proxy

# NEW: container completion (type/name form)
kubectl exec deploy/httpbin -c is<TAB>
kubectl exec deploy/httpbin -c istio-proxy
```
</details>

<details>
<summary>Commands that accept any resource type</summary>

- annotate
- apply edit-last-applied
- apply view-last-applied
- delete
- describe
- edit
- get
- label
- patch

```
# NEW: completion for the 'name' in the type/name form
kubectl get deployments.apps/ht<TAB>
kubectl get deployments.apps/httpbin

# NEW: completion for the 'type' in the type/name form
kubectl get deployments.apps/httpbin dep<TAB>
kubectl get deployments.apps/httpbin deployments.apps/
```
</details>
<details>
<summary>Commands that accept a subset of resource types</summary>

- autoscale
- expose
- rollout history
- rollout pause
- rollout restart
- rollout resume
- rollout status
- rollout undo
- scale
- taint

```
# NEW: completion for the 'name' in the type/name form
kubectl expose deployment/<TAB>
kubectl expose deployment/httpbin

# NEW: completion for the 'type' in the type/name form
kubectl expose deployment/httpbin p<TAB>
kubectl expose deployment/httpbin pod/
```
</details>

<details>
<summary>Commands that apply to resource types that contain pods</summary>

- attach
- exec
- logs
- port-foward

```
# NEW: Completes a pod name AND resource types that contain pods
kubectl exec <TAB>
bar-pod-fc87855b6-8rmqt                              baz-pod-fc87855b6-8rmqt
daemonsets/           pods/                          services/
deployments/          replicasets/                   statefulsets/
jobs/                 replicationcontrollers/        test-pod-fc87855b6-8rmqt

# NEW: When a '/' is found, does completion for 'name' for the type/name form
kubectl exec deploy/ht<TAB>
kubectl exec deploy/httpbin
```
</details>

<details>
<summary>Commands that accept container names</summary>

- logs

```
# NEW: Completes a pod name AND resource types that contain pods
kubectl logs p<TAB>
php-apache-d4cf67d68-l2fv8          pods/

# NEW: When a '/' is found, does completion for 'name' for the type/name form
kubectl logs deploy/ht<TAB>
kubectl logs deploy/httpbin

# NEW: completion of container name with the type/name form
kubectl logs deploy/httpbin is<TAB>
kubectl logs deploy/httpbin istio-proxy
```
</details>

/cc @brianpursley @eddiezane

### CODE REVIEW

**Comment by brianpursley** [comment]
So the code looks good.  I went through and I think I understand what it is doing everywhere, and I think it all makes sense.

The only thing that I keep coming back to with completions is that the code is spread across two different locations:
* cmd/get/get.go
* util/completions.go

I understand the reason for this, being to avoid an import cycle which causes compilation to fail.

Thinking about this a little more today, the main problem seems to be this line in `get.go`:
```
ValidArgsFunction:     ResourceTypeAndNameCompletionFunc(f, nil, true),
```

What if...

instead of setting `ValidArgsFunction` in `NewCmdGet()`, we set it in `cmd.go`, something like this:
```
        
	getCmd := get.NewCmdGet("kubectl", f, o.IOStreams)
	getCmd.ValidArgsFunction = util.ResourceTypeAndNameCompletionFunc(f) // Avoid import cycle by setting ValidArgsFunction here instead of in NewCmdGet()

	groups := templates.CommandGroups{
		{
                ...
                {
			Message: "Basic Commands (Intermediate):",
			Commands: []*cobra.Command{
				explain.NewCmdExplain("kubectl", f, o.IOStreams),
				getCmd,
                                ...
```

We're already doing completion stuff inside this function anyway related to flags, so maybe it is fine to set the get commands arg completion function here too.

If you do this, then you can take all the completion functions out of `cmd/get/get.go` and put them all into `util/completions.go`.  Maybe even create a completions package under util, to keep all the completion code together and encapsulated.

Thoughts?  Would this work?  Does this make things better, or not much?

Otherwise, the PR looks good, I just thought since you're making some significant changes, it might be a good time to tackle this refactor.

**Comment by marckhouzam** [comment]
> instead of setting ValidArgsFunction in NewCmdGet(), we set it in cmd.go

Brilliant!  I haven't tried it but I expect it to work quite nicely.  I will update the PR ASAP.  That definitely would make the code better.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Review by brianpursley — APPROVED** [review]
/lgtm

**Comment by brianpursley** [comment]
> Any idea why the bot it not merging this PR?

For some reason it was missing the lgtm and approved labels.

**Pull request merged**
