### PR TITLE
fix metrics test with 1.16.0 prometheus client

### LINKED ISSUE #118751: e2e node test failures due to unexpected metric
There's been a quite a few failures across jobs that query node metrics.

 * https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-features
 * https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-e2e-serial
 * https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-e2e-serial

The test is `E2eNode Suite.[It] [sig-node] ResourceMetricsAPI [NodeFeature:ResourceMetrics] when querying /resource/metrics should report resource usage through the resource metrics api`

* Last passing - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv1-containerd-node-e2e-features/1670540343646359552
* First failing - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv1-containerd-node-e2e-features/1670555443560189952

[Diff](https://github.com/kubernetes/kubernetes/compare/1ff1a2642...0004ce868) appears to point to https://github.com/kubernetes/kubernetes/pull/118689 which is bump in prometheus client library. Possibly related?

##### Error text:
```
[FAILED] Timed out after 60.006s.
Expected
    <string>: KubeletMetrics
to match keys: {
."kubelet_pod_resources_endpoint_requests_get_allocatable"[]:
	Expected
	    <string>: Sample
	to match fields: {
	.Histogram:
		unexpected field Histogram: kubelet_pod_resources_endpoint_requests_get_allocatable{server_api_version="v1"} => 1 @[0]
	}
	
."kubelet_pod_resources_endpoint_requests_list"[]:
	Expected
	    <string>: Sample
	to match fields: {
	.Histogram:
		unexpected field Histogram: kubelet_pod_resources_endpoint_requests_list{server_api_version="v1"} => 1 @[0]
	}
	
."kubelet_pod_resources_endpoint_requests_total"[]:
	Expected
	    <string>: Sample
	to match fields: {
	.Histogram:
		unexpected field Histogram: kubelet_pod_resources_endpoint_requests_total{server_api_version="v1"} => 2 @[0]
	}
	
}
In [It] at: test/e2e_node/podresources_test.go:862 @ 06/18/23 23:59:02.19

```
#### Recent failures:
[6/19/2023, 11:55:56 AM ci-kubernetes-node-kubelet-serial-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-containerd/1670868007628312576)
[6/19/2023, 11:54:56 AM ci-kubernetes-node-swap-ubuntu-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-swap-ubuntu-serial/1670867755999432704)
[6/19/2023, 7:55:55 AM ci-kubernetes-node-kubelet-serial-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-containerd/1670807608723771392)
[6/19/2023, 7:54:55 AM ci-kubernetes-node-swap-ubuntu-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-swap-ubuntu-serial/1670807357292023808)
[6/19/2023, 4:34:55 AM ci-cos-cgroupv1-containerd-node-e2e-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv1-containerd-node-e2e-serial/1670757024603836416)

/kind failing-test

/sig node

### PR DESCRIPTION
**Pull request by pacoxu**
Fixes #118751 #118757

```release-note
None
```

/cc @logicalhan @bobbypage

### CODE REVIEW

**Comment by ffromani** [comment]
thanks @pacoxu for this PR. This seems indeed to fix the failures, I'd need to review the prometheus changelog to fully understand the implications.

**Comment by ffromani** [comment]
/priority important-soon
/triage accepted

fixes recent CI failures

**Comment by ffromani** [comment]
@pacoxu I think there are a couple more places to fix:
```
diff --git a/test/e2e_node/cpu_manager_metrics_test.go b/test/e2e_node/cpu_manager_metrics_test.go
index 20f9b50e74f..0b246f4148d 100644
--- a/test/e2e_node/cpu_manager_metrics_test.go
+++ b/test/e2e_node/cpu_manager_metrics_test.go
@@ -201,5 +201,6 @@ func timelessSample(value interface{}) types.GomegaMatcher {
                "Metric":    gstruct.Ignore(),
                "Value":     gomega.BeNumerically("==", value),
                "Timestamp": gstruct.Ignore(),
+               "Histogram": gstruct.Ignore(),
        }))
 }
diff --git a/test/e2e_node/topology_manager_metrics_test.go b/test/e2e_node/topology_manager_metrics_test.go
index f62aef1cb30..8544d87d32a 100644
--- a/test/e2e_node/topology_manager_metrics_test.go
+++ b/test/e2e_node/topology_manager_metrics_test.go
@@ -174,5 +174,6 @@ func checkMetricValueGreaterThan(value interface{}) types.GomegaMatcher {
                "Metric":    gstruct.Ignore(),
                "Value":     gomega.BeNumerically(">", value),
                "Timestamp": gstruct.Ignore(),
+               "Histogram": gstruct.Ignore(),
        }))
 }
```

Could you please incorporate this ^^^^^ in your fix?
Also, perhaps we can revisit how `gstruct` is used in the affected tests and be more forward compatible in the future, but let's defer to another PR.

**Comment by bobbypage** [comment]
Thanks for the fix! I think the reason for this change is due to https://github.com/prometheus/common/commit/ee927faa00941790b069b28f709d5cd05247c8c8 which added `Histogram` to prometheus common Model which is then used in k8s [here](https://github.com/kubernetes/component-base/blob/master/metrics/testutil/metrics.go#L42). The bump in `prometheus/common` was included in #118689 [here](https://github.com/kubernetes/kubernetes/pull/118689/commits/5aa5f1abc9c9d83ccc34382ae2a8e0241ec1d866#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L60)

Since the tests examine the `Sample` struct directly, it makes sense we need to ignore it now. Long term, ideally we would ignore all unknown fields to prevent breaking changes in the future, but this fix makes sense for now!

**Comment by pacoxu** [comment]
> Could you please incorporate this ^^^^^ in your fix?

@ffromani  Fixed.

> Since the tests examine the `Sample` struct directly, it makes sense we need to ignore it now. Long term, ideally we would ignore all unknown fields to prevent breaking changes in the future, but this fix makes sense for now!

Thanks for the detailed investigation.

**Comment by bobbypage** [comment]
Thank you for the fixes!

/lgtm

**Comment by akhilerm** [comment]
@pacoxu Shouldnt we also test the `pull-kubernetes-cos-cgroupv2-containerd-node-e2e-serial` job as that was also failing with the same error.

**Comment by ffromani** [comment]
/lgtm

> Since the tests examine the `Sample` struct directly, it makes sense we need to ignore it now. Long term, ideally we would ignore all unknown fields to prevent breaking changes in the future, but this fix makes sense for now!

I completely agree

**Pull request merged**
