### PR TITLE
fix function notes

### PR DESCRIPTION
**Pull request by NickrenREN**
change the function notes according to the implementations of the function AddPodToVolume()

### CODE REVIEW

**Comment by NickrenREN** [comment]
@saad-ali @dims Could you please ask the k8s-bot to test ?

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by NickrenREN** [comment]
@saad-ali   checks passed .  please review

**Comment by NickrenREN** [comment]
@saad-ali   Bazel Build Check does not start. And  I  rebased the code.   Could you help add the LGTM label.
Sorry to bother you...

**Comment by NickrenREN** [comment]
@saad-ali   Bazel Build Check does not start before.  I rebase the code and commit again. Could you help add the LGTM label.
Sorry to bother you...

**Pull request merged**
