### PR TITLE
dependencies: update google.golang.org/grpc

### PR DESCRIPTION
**Pull request by liyuerich**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR is supposed to update google.golang.org/grpc to the latest version v1.55.0

#### Which issue(s) this PR fixes:

Fixes # None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

None

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

None

### CODE REVIEW

**Review by marquiz — COMMENTED** [review]
/lgtm

**Comment by dims** [comment]
@liyuerich @marquiz is there a specific reason for this update?

**Comment by liggitt** [comment]
make sure `hack/update-vendor.sh` and `hack/lint-dependencies.sh` pass cleanly and the results are committed

**Comment by marquiz** [comment]
ping @liyuerich

**Comment by liyuerich** [comment]
thanks liggitt and marquiz for your  feedback and comments. after check hack/update-vendor.sh and hack/lint-dependencies.sh, I have to close this PR and open a new one for this dependency update due to many changes.

**Pull request closed without merging**
