### PR TITLE
Fix exec/attach test flakes

### LINKED ISSUE #19466: unit flake: TestRequestAttachRemoteCommand
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go/5941/

```
=== RUN   TestRequestAttachRemoteCommand
panic: test timed out after 5m0s

goroutine 207 [running]:
testing.startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:703 +0x16b
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:129 +0x6e
```

cc @kubernetes/goog-cluster @krousey

### PR DESCRIPTION
**Pull request by ncdc**
- Bump docker/spdystream to pick up https://github.com/docker/spdystream/pull/65
- Ensure stream reply frames are enqueued prior to any goaway frames

Fixes #19466 

Note, I still have my outstanding PR #16451 that eliminates some of the duplicate code that is shared between the unit tests and the server. I plan on rebasing that (presumably if/when this goes in) and submitting an update soon.

cc @liggitt @lavalamp @kubernetes/rh-cluster-infra @smarterclayton

### CODE REVIEW

**Comment by ncdc** [comment]
@lavalamp updated

**Comment by lavalamp** [comment]
Looks good, but there's a build failure?

**Comment by ncdc** [comment]
Ok I'll look at it sometime soon. Having a bit of a family thing to deal
with at the moment...

**Comment by ncdc** [comment]
@lavalamp I'm back! I pushed another commit to fix the compilation failure.

**Comment by lavalamp** [comment]
Awesome! I hope this fixes the five dups of the issue we've collect :)

**Comment by lavalamp** [comment]
Actually can you squash the commits (leaving the dependency change in a separate commit, though)? Thanks!

**Comment by ncdc** [comment]
@lavalamp squashed!

**Comment by smarterclayton** [comment]
Reapplying

**Comment by lavalamp** [comment]
\o/

**Pull request merged**
