### PR TITLE
Kubemark master components run by supervisord. Try 2.

### PR DESCRIPTION
**Pull request by gmarek**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36073)

### CODE REVIEW

**Comment by gmarek** [comment]
@wojtek-t PTAL

**Comment by gmarek** [comment]
Fixed rebase problem.

**Comment by gmarek** [comment]
@saad-ali - this is needed to stabilize our tests.

**Comment by wojtek-t** [comment]
@gmarek - kubemark is still not passing

**Comment by gmarek** [comment]
@k8s-bot kubemark test this issue: #IGNORE
for some reason they were running on old version of code...

**Comment by gmarek** [comment]
Another rebase...

**Comment by dims** [comment]
@k8s-bot node e2e test this

**Pull request merged**
