### PR TITLE
fix describe Persistentvolume output Format

### LINKED ISSUE #56777: flexVolume parameters parsing incorrect
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
When I try to set up a flex volume PV by following config:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-flex-lvm 
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteOnce
  flexVolume:
    driver: foo/lvm
    fsType: ext4
    readOnly: true
    options: 
      fooServer: 192.168.0.1:1234
      fooVolumeName: bar
```
Then I run `kubectl describe pv pv-flex-lvm`, the output would be as following in which `driver`, `fsType` is parsing incorrect, I tried on both v1.8, v1.9 k8s cluster, got same situation:

```
Name:            pv-flex-lvm
Labels:          <none>
Annotations:     <none>
StorageClass:
Status:          Available
Claim:
Reclaim Policy:  Retain
Access Modes:    RWO
Capacity:        1Gi
Message:
Source:
    Type:    FlexVolume (a generic volume resource that is provisioned/attached using an exec based plugin)
    Driver:      Options:  %v

    FSType:                                                                                      foo/lvm
    SecretRef:                                                                                   ext4
    ReadOnly:                                                                                    <nil>
%!(EXTRA bool=true, map[string]string=map[fooServer:192.168.0.1:1234 fooVolumeName:bar])Events:  <none>
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8, v1.9
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig storage

### PR DESCRIPTION
**Pull request by stewart-yu**
**What this PR does / why we need it**:
fix `kubectl describe persistentvolume * ` output Format

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes [https://github.com/kubernetes/kubernetes/issues/56777](https://github.com/kubernetes/kubernetes/issues/56777)

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by php-coder** [comment]
Looks like I've already fixed it in https://github.com/kubernetes/kubernetes/pull/57202 I'm surprised GitHub doesn't show a conflict and bot didn't add "needs-rebase" label.

**Comment by stewart-yu** [comment]
I  have check out master, the error still exists , So strange @php-coder

**Comment by stewart-yu** [comment]
cc @smarterclayton  Please help review this pr, thanks!

**Comment by stewart-yu** [comment]
I known it, it's kind bug in `bot`, which just compare local. it need fix also in `master` branch [https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/internalversion/describe.go#L1084](https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/internalversion/describe.go#L1084), but in others function. I will send others PR

**Pull request closed without merging**
