### PR TITLE
Automated cherry pick of #11128 #10986 #11561 upstream release 1.0

### LINKED ISSUE #11231: Kubernetes/GCE corrupted PD volume
Somehow a GCE persistent disk was corrupted when used exclusively by a single pod on a container engine. While testing, i repeatedly deleted / created the replication controller and pod (a singleton) with 4 containers all using a single PD in read-write mode.
Eventually the pod just refused to start, and the instance reported filesystem corruption in the logs.
This looks like failure to sync/unmount the volume properly
Here's /var/log/messages from the instance (there's nothing else going on in this tiny 2-node cluster so it was being assigned to the same one repeatedly) - http://pastebin.com/rH6jfHFH

### PR DESCRIPTION
**Pull request by saad-ali**
Automated cherry pick of #11128 #10986 #11561 upstream release 1.0
#11128 and #10986 are necessary to pick up #11561
#11561 fixes #11231 and #11321 (i.e. Fixes GCE PD attach/detach issues)

CC @brendanburns @zmerlynn

### CODE REVIEW

**Comment by saad-ali** [comment]
This is for the 1.0.2 release

**Comment by saad-ali** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@justinsb are you ok with contributing this code? Is that even relevant since it's already in master?

**Comment by justinsb** [comment]
@mikedanese: yes I am OK with contributing this code :-)

I think in the past we have just done a manual override of CLA bot when the original contributions were under the CLA, but obviously you should confirm with whoever makes those decisions.

**Comment by zmerlynn** [comment]
Yeah, we've been overriding CLA-bot. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/cherry-picks.md mentions the policy.

**Pull request merged**
