### PR TITLE
[1.18] Update to json-patch 4.8.0

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Includes the same version bump as #93810 on master
xref #91615

**Does this PR introduce a user-facing change?**:
```release-note
Fixed a performance issue applying json patches to deeply nested objects
```

/priority important-soon
/cc @logicalhan

### CODE REVIEW

**Comment by liggitt** [comment]
/retest
Flake already addressed in master, still present in release branches

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
