### PR TITLE
remove useless functions in fakes.go file

### PR DESCRIPTION
**Pull request by NickrenREN**

### CODE REVIEW

**Comment by NickrenREN** [comment]
@derekwaynecarr   Could you spend some time helping to ask k8s-bot to test and review ? Thanks

**Comment by NickrenREN** [comment]
@derekwaynecarr   Sorry to bother you. PTAL

**Comment by derekwaynecarr** [comment]
@k8s-bot ok to test

**Comment by derekwaynecarr** [comment]
This is on my agenda for tomorrow.  I have been catching up since the holiday.  Apologies.

**Comment by derekwaynecarr** [comment]
@NickrenREN -- take a look at the bots and update as needed, then poke.

**Comment by NickrenREN** [comment]
@derekwaynecarr  Sorry for the delay. I have modified the code and update the BUILD file. PTAL. Thanks

**Comment by NickrenREN** [comment]
@mikedanese  Thanks.  File is already deleted

**Pull request closed without merging**
