### PR TITLE
Revert "Refactor kubectl methods into utility class, so that we can easi...

### PR DESCRIPTION
**Pull request by roberthbailey**
Reverts GoogleCloudPlatform/kubernetes#5773

The e2e tests `kubectl update-demo should create and stop a replication controller` & `kubectl update-demo should scale a replication controller` have been failing consistently since this PR was merged.

### CODE REVIEW

**Comment by roberthbailey** [comment]
Self merging to fix the bleeding.

**Comment by jayunit100** [comment]
just saw this.  have a local working impl of the e2es for kubectl.  shall i reissue the pull and just paste e2e results ?  

unfortunately when i was issueing this PR my dev env had gone down...  and i guess e2e's don't run in the CI .

**Comment by quinton-hoole** [comment]
The e2e's are still failing ~25% of the time in Jenkins CI after this revert.  Please make sure that you run them, say 10 times successfully locally to confirm consistency.

**Comment by jayunit100** [comment]
the e2e's are by their nature inconsistent.  i dont think that you can get around that.  

- create a replication controller
- polling for container update 

and so on are all subject to race conditions.

**Comment by roberthbailey** [comment]
@quinton-hoole Of the three tests affected by this, I've only seen a single failure on Jenkins since the revert.

**Pull request merged**
