### PR TITLE
Add some indent in CHANGELOG-1.7

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
in changelogv1.7 there has some indent error and fixed it!
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by tengqm** [comment]
Wondering if this is the right place to make such changes. I also noticed that there are *quite some* format errors in the change log, but I think those are automatically generated from PRs.

**Comment by jianglingxia** [comment]
/cc @thockin 
the format errors is automatically generated?thanks for your reply!

**Comment by thockin** [comment]
I appreciate cleanups, but in truth, these are probably a waste of energy, overall.

**Comment by jianglingxia** [comment]
thanks @thockin @david-mcmahon and need label /ok-to-test let the robot remove the labe?

**Pull request merged**
