### PR TITLE
fix not return when channel closed

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes # https://github.com/kubernetes/kubernetes/issues/107520

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kerthcet** [comment]
kindly ping @jpbetz

**Review by able8 — APPROVED** [review]

**Comment by jpbetz** [comment]
Awesome, thanks for opening the PR!

/lgtm

**Comment by kerthcet** [comment]
Need another review from cluster approver then.

**Pull request merged**
