### PR TITLE
Fixes sigfault in case of empty TopologyInfo

### LINKED ISSUE #96519: [Failing Test] [sig-scheduling] [Feature:GPUDevicePlugin] run Nvidia GPU Device Plugin tests (ci-kubernetes-e2e-gce-device-plugin-gpu)
**Which jobs are failing**:
`ci-kubernetes-e2e-gce-device-plugin-gpu`

**Which test(s) are failing**:
`[sig-scheduling] [Feature:GPUDevicePlugin] run Nvidia GPU Device Plugin tests`

**Since when has it been failing**:
https://github.com/kubernetes/kubernetes/compare/0469db9fe...dd4560370

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#gce-device-plugin-gpu-master

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/nvidia-gpus.go:224
Nov 11 21:43:04.675: wait for pod "nvidia-gpu-13237348-f464-496a-9e10-7d2bd90a5aad" to succeed
Expected success, but got an error:
    <*errors.errorString | 0xc003262610>: {
        s: "pod \"nvidia-gpu-13237348-f464-496a-9e10-7d2bd90a5aad\" failed with reason: \"UnexpectedAdmissionError\", message: \"Pod Allocate failed due to requested number of devices unavailable for nvidia.com/gpu. Requested: 1, Available: 0, which is unexpected\"",
    }
    pod "nvidia-gpu-13237348-f464-496a-9e10-7d2bd90a5aad" failed with reason: "UnexpectedAdmissionError", message: "Pod Allocate failed due to requested number of devices unavailable for nvidia.com/gpu. Requested: 1, Available: 0, which is unexpected"
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/pods.go:212
```

**Anything else we need to know**:
Can't find this in Triage

Example spyglass links: 
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-device-plugin-gpu/1326638573817958400
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-device-plugin-gpu/1326729172260753408
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-device-plugin-gpu/1326698973720743936
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-device-plugin-gpu/1326668771879817216

/sig scheduling
/cc @kubernetes/ci-signal @kubernetes/sig-scheduling-bugs 
/priority important-soon

### PR DESCRIPTION
**Pull request by AlexeyPerevalov**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Device plugin which implements v1beta interface can return nil in
Topology field

For example nvidia-gpu-deviceplugin
https://github.com/NVIDIA/k8s-device-plugin/blob/3520254b75df872c6a3468ab2f74deba7c63c09b/nvidia.go#L14://github.com/NVIDIA/k8s-device-plugin/blob/3520254b75df872c6a3468ab2f74deba7c63c09b/nvidia.go#L147

**Which issue(s) this PR fixes**:

Fixes #96519

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
/retest
/release-note none

**Comment by ruiwen-zhao** [comment]
Looking at the [kubelet log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/96553/pull-kubernetes-e2e-gce-device-plugin-gpu/1328353158430199808/artifacts/e2e-ab944e458a-8baae-minion-group-71rs/kubelet.log) of the node reporting no GPU available, it looks like the device plugin never registers itself with device manager. (Because I searched for "Got registration request from device plugin with resource name " but got nothing).

This is weird because even before this fix, the device manager can get the registration from device plugin. See [a sample kubelet log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-device-plugin-gpu/1326940321854001152/artifacts/bootstrap-e2e-minion-group-2hjf/kubelet.log) from a previous run.

**Comment by AlexeyPerevalov** [comment]
> Looking at the [kubelet log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/96553/pull-kubernetes-e2e-gce-device-plugin-gpu/1328353158430199808/artifacts/e2e-ab944e458a-8baae-minion-group-71rs/kubelet.log) of the node reporting no GPU available, it looks like the device plugin never registers itself with device manager. (Because I searched for "Got registration request from device plugin with resource name " but got nothing).
> 
> This is weird because even before this fix, the device manager can get the registration from device plugin. See [a sample kubelet log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-device-plugin-gpu/1326940321854001152/artifacts/bootstrap-e2e-minion-group-2hjf/kubelet.log) from a previous run.

**Comment by ruiwen-zhao** [comment]
> > Looking at the [kubelet log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/96553/pull-kubernetes-e2e-gce-device-plugin-gpu/1328353158430199808/artifacts/e2e-ab944e458a-8baae-minion-group-71rs/kubelet.log) of the node reporting no GPU available, it looks like the device plugin never registers itself with device manager. (Because I searched for "Got registration request from device plugin with resource name " but got nothing).
> > This is weird because even before this fix, the device manager can get the registration from device plugin. See [a sample kubelet log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-device-plugin-gpu/1326940321854001152/artifacts/bootstrap-e2e-minion-group-2hjf/kubelet.log) from a previous run.
> 
> Is it possible to see the log from nvidia-gpu-device-plugin (https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/device-plugins/nvidia-gpu/daemonset.yaml)?

I was looking for that too, but it seems we dont keep the pod/container logs after the test. Does anyone know which GCP project do the tests run on, and does anyone have the permission to check the pod logs?

**Comment by AlexeyPerevalov** [comment]
> Got registration request from device

Let's summarize. I tested  GoogleCloudPlatform/container-engine-accelerators locally on ubuntu 20.04.
I found that after this fix  the DevicePlugin in nvidia-gpu-device-plugin pod is registered and I observed "Got registration request from device..." and the appropriate resource is observed after that, kubelet knows about resource. And there is no crash.
But nvidia-gpu-device-plugin it's not only one pod in the chain of pull-kubernetes-e2e-gce-device-plugin-gpu. There was yet another (the first one) - nvidia-driver-installer. It was failed in my case in entrypoint.sh (configure_nvidia_installation_dirs).

**Comment by ruiwen-zhao** [comment]
> > Got registration request from device
> 
> Let's summarize. I tested GoogleCloudPlatform/container-engine-accelerators locally on ubuntu 20.04.
> I found that after this fix the DevicePlugin in nvidia-gpu-device-plugin pod is registered and I observed "Got registration request from device..." and the appropriate resource is observed after that, kubelet knows about resource. And there is no crash.
> But nvidia-gpu-device-plugin it's not only one pod in the chain of pull-kubernetes-e2e-gce-device-plugin-gpu. There was yet another (the first one) - nvidia-driver-installer. It was failed in my case in entrypoint.sh (configure_nvidia_installation_dirs).

Can you elaborate on how you tested the device plugin and your change? My understanding is that the device plugin and driver installer on GoogleCloudPlatform/container-engine-accelerators can only work on GKE machines. 

The nvidia-driver-installer is a daemonset that installs the drivers. Without it the GPUs will not run, and the device plugin will not detect GPUs. So I don't fully understand why in your test the installer doesn't work but the device plugin does. Can you share the failure messages for driver installer?

**Comment by AlexeyPerevalov** [comment]
> > > Got registration request from device
> > 
> > 
> > Let's summarize. I tested GoogleCloudPlatform/container-engine-accelerators locally on ubuntu 20.04.
> > I found that after this fix the DevicePlugin in nvidia-gpu-device-plugin pod is registered and I observed "Got registration request from device..." and the appropriate resource is observed after that, kubelet knows about resource. And there is no crash.
> > But nvidia-gpu-device-plugin it's not only one pod in the chain of pull-kubernetes-e2e-gce-device-plugin-gpu. There was yet another (the first one) - nvidia-driver-installer. It was failed in my case in entrypoint.sh (configure_nvidia_installation_dirs).
> 
> Can you elaborate on how you tested the device plugin and your change? My understanding is that the device plugin and driver installer on GoogleCloudPlatform/container-engine-accelerators can only work on GKE machines.
> 
> The nvidia-driver-installer is a daemonset that installs the drivers. Without it the GPUs will not run, and the device plugin will not detect GPUs. So I don't fully understand why in your test the installer doesn't work but the device plugin does. Can you share the failure messages for driver installer?

I don't have NVidia GPU on the server, our lab has only NICs, but I have it on local computer (under Ubuntu 20.04)
The output of the: kubectl logs -n kube-system nvidia-driver-installer-x86nm -c nvidia-driver-installer
```
...
Processing triggers for libc-bin (2.31-0ubuntu9.1) ...
Downloading kernel sources... DONE.
+ pwd
+ echo 'Configuring installation directories...'
+ mkdir -p /usr/local/nvidia
/
Configuring installation directories...
+ pushd /usr/local/nvidia
/usr/local/nvidia /
+ mkdir -p bin bin-workdir
+ mount -t overlay -o lowerdir=/usr/bin,upperdir=bin,workdir=bin-workdir none /usr/bin
mount: /usr/bin: wrong fs type, bad option, bad superblock on none, missing codepage or helper program, or other error.

```

as we can see no cache version and download_kernel_src passed, but configure_nvidia_installation_dirs doesn't and contains some strange things like:
  mount -t overlay -o lowerdir=/usr/bin,upperdir=bin,workdir=bin-workdir none /usr/bin - possible only for read only rootfs, but it's not RO, and  before the mount I see directory creation.

**Review by hasheddan — COMMENTED** [review]
/milestone v1.20

Likely depends on https://github.com/kubernetes/kubernetes/pull/96718

**Comment by hasheddan** [comment]
Okay so i think this will fix the periodic, but not the presubmit. We should go ahead and get it in and I'll get the presubmit fixed up

**Review by hasheddan — APPROVED** [review]
/lgtm

@jiayingz @vishh could one of you take a look here?

**Comment by RenaudWasTaken** [comment]
> Looking at the kubelet log of the node reporting no GPU available, it looks like the device plugin never registers itself with device manager. (Because I searched for "Got registration request from device plugin with resource name " but got nothing).

We know that it initiates the registration plugin right? It's the reason we have the segfault in the first place :D

**Comment by hasheddan** [comment]
Conversation troubleshooting presubmit failures, which appear unrelated: https://kubernetes.slack.com/archives/C0BP8PW9G/p1605802045171300

**Comment by hasheddan** [comment]
More info.. the presubmit runs in a project that does not have committed GPUs:
> It runs a single test, and based on the last two weeks, the only time
the job fails is when it runs out of GPU quota (the project used doesn't
have committed GPU's).  There is likely sufficient signal being obtained
from the CI equivalent to this job.

https://github.com/kubernetes/test-infra/commit/331dbc9e95e64122cd0a351e6adf0061add58bc3#diff-97cdfe7c3ef99e9d5d25ca25722e0f07d1d3a8eef7aa717dcbf74669c4fac1c3

**Review by ruiwen-zhao — APPROVED** [review]

**Pull request merged**
