### PR TITLE
wip: fix process stats

### PR DESCRIPTION
**Pull request by bobbypage**
Signed-off-by: David Porter <david@porter.me>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bobbypage** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/115215

**Comment by bobbypage** [comment]
Testing manually:

```
$ kubectl run -i --tty --rm debug --image=k8s.gcr.io/busybox:latest --restart=Never -- /bin/sh
If you don't see a command prompt, try pressing enter.
/ # for i in $(seq 1 10); do sleep 99999999 & done
/ # ps aux
PID   USER     COMMAND
    1 root     /bin/sh
   14 root     sleep 99999999
   15 root     sleep 99999999
   16 root     sleep 99999999
   17 root     sleep 99999999
   18 root     sleep 99999999
   19 root     sleep 99999999
   20 root     sleep 99999999
   21 root     sleep 99999999
   22 root     sleep 99999999
   23 root     sleep 99999999
   24 root     ps aux
```

```
  {
   "podRef": {
    "name": "debug",
    "namespace": "default",
    "uid": "8f834b3d-8d19-427e-ac23-38f58865f384"
   },
   "startTime": "2023-01-19T22:18:24Z",
   "containers": [
    {
     "name": "debug",
     "startTime": "2023-01-19T22:18:25Z",
     "cpu": {
      "time": "2023-01-19T22:18:44Z",
      "usageNanoCores": 1300004,
      "usageCoreNanoSeconds": 80284000
     },
     "memory": {
      "time": "2023-01-19T22:18:44Z",
      "usageBytes": 1925120,
      "workingSetBytes": 1912832,
      "rssBytes": 720896,
      "pageFaults": 2650,
      "majorPageFaults": 0
     },
     "rootfs": {
      "time": "2023-01-19T22:18:41Z",
      "availableBytes": 40815300608,
      "capacityBytes": 431596691456,
      "usedBytes": 36864,
      "inodesFree": 21605980,
      "inodes": 26836992,
      "inodesUsed": 10
     },
     "logs": {
      "time": "2023-01-19T22:18:46Z",
      "availableBytes": 40815300608,
      "capacityBytes": 431596691456,
      "usedBytes": 4096,
      "inodesFree": 21605980,
      "inodes": 26836992,
      "inodesUsed": 1
     }
    }
   ],
   "cpu": {
    "time": "2023-01-19T22:18:39Z",
    "usageNanoCores": 7919830,
    "usageCoreNanoSeconds": 121436000
   },
   "memory": {
    "time": "2023-01-19T22:18:39Z",
    "usageBytes": 2240512,
    "workingSetBytes": 2228224,
    "rssBytes": 757760,
    "pageFaults": 3735,
    "majorPageFaults": 0
   },
   "network": {
    "time": "2023-01-19T22:18:39Z",
    "name": "eth0",
    "rxBytes": 0,
    "rxErrors": 0,
    "txBytes": 656,
    "txErrors": 0,
    "interfaces": [
     {
      "name": "eth0",
      "rxBytes": 0,
      "rxErrors": 0,
      "txBytes": 656,
      "txErrors": 0
     }
    ]
   },
   "ephemeral-storage": {
    "time": "2023-01-19T22:18:46Z",
    "availableBytes": 40815300608,
    "capacityBytes": 431596691456,
    "usedBytes": 45056,
    "inodesFree": 21605980,
    "inodes": 26836992,
    "inodesUsed": 12
   },
   "process_stats": {
    "process_count": 11 <--- Process count is reported correctly (10 sleep pids, plus one for the shell pid) = 11 pids
   }
  }
 ]
}
```

**Comment by pacoxu** [comment]
/remove-lifecycle rotten
@bobbypage  do you have time to move this forward? Is there any blocker?

**Comment by pacoxu** [comment]
Is this still WIP? Or can we start to review and test it?

**Comment by dims** [comment]
This work-in-progress PR needs a rebase. please rebase if this PR is still needed for the upcoming release.

**Comment by pacoxu** [comment]
/close 
feel free to reopen if you have time to follow up. 

I opened https://github.com/kubernetes/kubernetes/pull/122927/ to test.

**Pull request closed without merging**
