### PR TITLE
add NodeCondition and PodCondition to kubectl describe node/pod

### PR DESCRIPTION
**Pull request by mikedanese**
This looks like:

```
[miked@localhost]$ kubectl describe mi 127.0.0.1
Name:   127.0.0.1
Conditions:
        Ready:
                Status:                 Full
                LastProbeTime:          2015-02-09 21:16:51 -0800 PST
                LastTransitionTime:     2015-02-09 21:16:51 -0800 PST
                Reason:                 Node health check succeeded: kubelet /healthz endpoint returns ok
                Message:

```

### CODE REVIEW

**Comment by mikedanese** [comment]
Adding PodCondition to kubectl describe pod in this PR as well. This looks like:
```
[miked@localhost]$ kubectl describe po web
Name:                           web
Image(s):                       test-ready
Host:                           127.0.0.1/127.0.0.1
Labels:                         name=web
Status:                         Running
Replication Controllers:        <none>
Conditions:
        Ready:
                Status: Full
Events:
Time                            From                    SubobjectPath                           Reason          Message
Tue, 10 Feb 2015 12:51:12 -0800 {kubelet 127.0.0.1}     implicitly required container POD       pulled          Successfully pulled image "kubernetes/pause:latest"
Tue, 10 Feb 2015 12:51:12 -0800 {scheduler }                                                    scheduled       Successfully assigned web to 127.0.0.1
Tue, 10 Feb 2015 12:51:12 -0800 {kubelet 127.0.0.1}     implicitly required container POD       created         Created with docker id 34acf3dd618eb3fe4f64a7e8dc55426494a218b40afedfc3873b4718f39df0d2
Tue, 10 Feb 2015 12:51:12 -0800 {kubelet 127.0.0.1}     implicitly required container POD       started         Started with docker id 34acf3dd618eb3fe4f64a7e8dc55426494a218b40afedfc3873b4718f39df0d2
Tue, 10 Feb 2015 12:51:12 -0800 {kubelet 127.0.0.1}     spec.containers{web}                    created         Created with docker id cc225db6fe9da5d2325cf54bdd3bb9a65e5245d567d85bf3e70000fb2995d5c7
Tue, 10 Feb 2015 12:51:12 -0800 {kubelet 127.0.0.1}     spec.containers{web}                    started         Started with docker id cc225db6fe9da5d2325cf54bdd3bb9a65e5245d567d85bf3e70000fb2995d5c7

```

**Comment by ddysher** [comment]
It might be easier to read if you follow the structure from event, i.e.
```
[miked@localhost]$ kubectl describe mi 127.0.0.1
Name:   127.0.0.1
Conditions:
  Kind            Status              LastProbeTime                  LastTransitionTime              Reason           Message
  Ready           Full                xxxxxxxxxxxxxxxx              xxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxx
```

**Comment by mikedanese** [comment]
Here's the same info tab spaced.
```
[miked@localhost]$ kubectl describe mi 127.0.0.1
Name:   127.0.0.1
Conditions:
  Kind          Status  LastProbeTime                           LastTransitionTime                      Reason                                                                  Message
  Ready         Full    Tue, 10 Feb 2015 14:14:37 -0800         Tue, 10 Feb 2015 14:13:27 -0800         Node health check succeeded: kubelet /healthz endpoint returns ok 

[miked@localhost]$ kubectl describe po web
Name:                           web
Image(s):                       test-ready
Host:                           127.0.0.1/127.0.0.1
Labels:                         name=web
Status:                         Running
Replication Controllers:        <none>
Conditions:
  Kind          Status
  Ready         Full 
Events:
Time                            From                    SubobjectPath                           Reason                  Message
Tue, 10 Feb 2015 14:13:32 -0800 {scheduler }                                                    failedScheduling        Error scheduling: no minions available to schedule pods
Tue, 10 Feb 2015 14:13:33 -0800 {scheduler }                                                    failedScheduling        Error scheduling: no minions available to schedule pods
Tue, 10 Feb 2015 14:13:35 -0800 {scheduler }                                                    failedScheduling        Error scheduling: no minions available to schedule pods
Tue, 10 Feb 2015 14:13:39 -0800 {scheduler }                                                    scheduled               Successfully assigned web to 127.0.0.1
Tue, 10 Feb 2015 14:13:47 -0800 {kubelet 127.0.0.1}     spec.containers{web}                    started                 Started with docker id af79b79427d148b1628980dbd832fa71e7fac203075b19c6356db6616e521c08
Tue, 10 Feb 2015 14:13:47 -0800 {kubelet 127.0.0.1}     implicitly required container POD       pulled                  Successfully pulled image "kubernetes/pause:latest"
Tue, 10 Feb 2015 14:13:47 -0800 {kubelet 127.0.0.1}     implicitly required container POD       created                 Created with docker id 60fa0d2f81555a4cefe8d865e6e4b39f65b4d5c6e655ecb3835ac132ed744fde
Tue, 10 Feb 2015 14:13:47 -0800 {kubelet 127.0.0.1}     implicitly required container POD       started                 Started with docker id 60fa0d2f81555a4cefe8d865e6e4b39f65b4d5c6e655ecb3835ac132ed744fde
Tue, 10 Feb 2015 14:13:47 -0800 {kubelet 127.0.0.1}     spec.containers{web}                    created                 Created with docker id af79b79427d148b1628980dbd832fa71e7fac203075b19c6356db6616e521c08

```

**Comment by ddysher** [comment]
LGTM   Thanks!

**Pull request merged**
