### PR TITLE
Add pprof trace support

### PR DESCRIPTION
**Pull request by ncdc**
Add support for `/debug/pprof/trace`

Can wait for master to reopen for 1.7.

cc @smarterclayton @wojtek-t @gmarek @timothysc @jeremyeder @kubernetes/sig-scalability-pr-reviews

### CODE REVIEW

**Comment by smarterclayton** [comment]
I'd actually like this in 1.6 because it's low risk.  You might need to set the block profile rate to something useful by default though.

**Comment by ncdc** [comment]
The apiserver and scheduler currently do this:

```go
if s.EnableContentionProfiling {
  goruntime.SetBlockProfileRate(1)
}
```

Is that appropriate, and would you like me to add this flag to all the other components?

**Comment by timothysc** [comment]
I don't see a problem with enabling, but just know that every time you hit that endpoint it's pretty expensive.  You'll get xMB dump, so you may heisenbug yourself. 

It's useful for local analysis, but across processes we're going to need something like http://zipkin.io/ && http://opentracing.io/

**Comment by wojtek-t** [comment]
Assuming that it doesn't add anything if it's not called (I hope that's true assumption), then I'm also fine with having this in 1.6 (though I don't think it's extremely useful).
@ncdc @smarterclayton - do you use it often? If so, what for?

**Comment by ncdc** [comment]
@wojtek-t I honestly stumbled across it when looking into #42000 and was wondering if it could potentially have helped investigate that issue. I've never personally used it.

**Comment by smarterclayton** [comment]
I've used it for debugging time spent in sync.Mutex contention - various
bugs that we have had with locks and starvation have shown up in it.  I use
it more for lock contention than for the execution profiling, although if
you can get it to work that has also shown some value in being able to
reason about channels and various starvation things.

**Comment by smarterclayton** [comment]
1.6 due to low risk and benefit in debugging ugly problems

**Comment by smarterclayton** [comment]
@k8s-bot unit test this

was the node-v1-test replace race

**Comment by ncdc** [comment]
@smarterclayton yeah I found that flake 😄. I was holding off on a retest because I haven't done anything to set the block profile rate yet.

**Review by timothysc — APPROVED** [review]

**Comment by ncdc** [comment]
I'm going to add `--enable-contention-profiling` to the components that don't already have it that currently have pprof in them.

**Comment by gmarek** [comment]
Thanks for doing that @ncdc.

**Comment by ncdc** [comment]
Updated. I think I added the flag in all the places it was missing. PTAL.

**Comment by ethernetdan** [comment]
Removing PR from 1.6 milestone since code freeze has begun:
* If this is a bug fix, please label as `kind/bug` and reapply the milestone.
* If this is a feature for 1.6, an [exception](https://github.com/kubernetes/features/blob/master/EXCEPTIONS.md) should be filed for it before 11:00PM PST on 3/2. Note that most exceptions to code freeze are not accepted.
* If this is a feature for 1.7, feel free to add the 1.7 milestone to the PR.

/cc @kubernetes/release-team @kubernetes/kubernetes-release-managers

**Comment by gmarek** [comment]
@ethernetdan @calebamiles @ncdc - This is in an "allow testing" scope, i.e. useful for debugging possible problems, hence I think we should put it in 1.6.

**Comment by smarterclayton** [comment]
I agree with @gmarek's assessment, this is what we typically consider a feature, and fits under general polish / cleanliness things that are under bugs.

**Comment by spiffxp** [comment]
This is disabled by default. I agree it's not disruptive and worth adding back in.

**Comment by ncdc** [comment]
If it gets a green light for 1.6 I will rebase; otherwise I'll just wait until master reopens. LMK

**Comment by gmarek** [comment]
OK, I'm adding it back to 1.6.

**Comment by ncdc** [comment]
Rebased

**Pull request merged**
