### PR TITLE
Use bash ranges "{1..3}" instead of "$(seq 1 3)".

### PR DESCRIPTION
**Pull request by rmmh**
[Analytics]()

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/26790)

### CODE REVIEW

**Comment by ixdy** [comment]
on the list of code cleanups this is pretty close to the bottom, but ok. :)

**Comment by ixdy** [comment]
@rmmh ping

**Comment by rmmh** [comment]
@ixdy SYN-ACK

**Comment by ixdy** [comment]
Looks like a few new places slipped in:
* hack/lib/util.sh
* hack/jenkins/e2e-runner.sh
* a number of spots in test/

**Comment by ixdy** [comment]
@rmmh please assign back after rebase and comments addressed

**Comment by rmmh** [comment]
Note that bash brace expansion happens before variable expansion, so `$(seq 1 $times)` isn't the same as `{1..$times}`

**Comment by ixdy** [comment]
LGTM

**Pull request merged**
