### PR TITLE
chore: fix invalid package name by golint

### PR DESCRIPTION
**Pull request by mowangdk**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix invalid package name as golint check in #124690

image

#### Which issue(s) this PR fixes:

Fixes #124690

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Review by aruneshpa — APPROVED** [review]
LGTM.  Thanks for addressing this.

**Comment by pohly** [comment]
Why is it worth fixing this?

Is this showing up as a linter hint? Those can be ignored unless they highlight some real problem.

**Comment by mowangdk** [comment]
> Why is it worth fixing this?
> 
> Is this showing up as a linter hint? Those can be ignored unless they highlight some real problem.

@pohly  The CI process for PR #124690 is currently hindered by an error. I've retry the CI run. Here's the [error log](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/124690/pull-kubernetes-verify-lint/1787309034844459008) for reference.  

Either way, I think it's better to fix it even if it's just a warning~

**Comment by pohly** [comment]
> The CI process for PR https://github.com/kubernetes/kubernetes/pull/124690 is currently hindered by an error. I've retry the CI run. Here's the [error log](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/124690/pull-kubernetes-verify-lint/1787309034844459008) for reference.

So it's actually merge-blocking. Then let's fix it.

/lgtm
/approve


> Either way, I think it's better to fix it even if it's just a warning~

Warnings are things where it's up to the discretion of the developer to decide whether it's worth fixing. We don't want PRs for trivial issues that can be ignored because each PR comes with a cost.

**Comment by mowangdk** [comment]
> > The CI process for PR #124690 is currently hindered by an error. I've retry the CI run. Here's the [error log](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/124690/pull-kubernetes-verify-lint/1787309034844459008) for reference.
> 
> So it's actually merge-blocking. Then let's fix it.
> 
> /lgtm /approve
> 
> > Either way, I think it's better to fix it even if it's just a warning~
> 
> Warnings are things where it's up to the discretion of the developer to decide whether it's worth fixing. We don't want PRs for trivial issues that can be ignored because each PR comes with a cost.

@pohly  gotcha, thank for the review 👍

**Pull request merged**
