### PR TITLE
Fix cannot delete rs when connections exist.

### LINKED ISSUE #81587: Network requests would fail in service.spec.sessionAffinity= ClientIP when deleting pod in kube-proxy ipvs mode
**What happened**:
In kube-proxy ipvs mode, there is a probability failure of network requests of `service.spec.sessionAffinity= ClientIP` when deleting pod.

**What you expected to happen**:
Network requests success.

**How to reproduce it (as minimally and precisely as possible)**:
1 Create a service with `service.spec.sessionAffinity= ClientIP`.
2 Continuous access to this service
3 Delete a pod of the service
4 The access may fail

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by xiaoxubeii**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
In kube-proxy ipvs mode, kube-proxy may set rs weight=0 instead of deleting it immediately because of grateful_termination. But ipvs would proxy requests to the inactive rip even its weight is 0 when persistent. So we should delete persistent rips immediately although there are inactive connnections.

**Which issue(s) this PR fixes**:

Fixes #81587

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by MrHohn** [comment]
Looping in the expert :)
/cc @andrewsykim

**Comment by lbernail** [comment]
Hello

What should happen is the following:
- delete pod behind a service with session affinity
- real server weight is set to 0
- existing connections to the real server gracefully terminate
- the affinity rule should be removed because we set `expire_quiescent_template=1`, see https://github.com/kubernetes/kubernetes/pull/71834 for context
- new connections to this service from the same client should go to another real server

So, _in theory_, the problem you are describing should not happen, but it may be related to different behaviors of different kernels? Can you check if what I described is what actually happens?

**Comment by xiaoxubeii** [comment]
Has beed resolved.

**Comment by xiaoxubeii** [comment]
@lbernail Yes, your pr is perfect : )

**Pull request closed without merging**
