### PR TITLE
Bump Heapster to v0.20.0-alpha7

### PR DESCRIPTION
**Pull request by mwielgus**

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

**Comment by mwielgus** [comment]
Need for e2e testing. Bumping up priority.

**Comment by eparis** [comment]
Why is this a p0/p1 ? I don't see a linked issue, bug report, or reason this should be jumping the queue....

**Comment by mwielgus** [comment]
The reason for P0/P1 was that we wanted to have it merged in Polish (CET) work hours so that we can verify it and react to any possible e2e test failures without affecting other developers and build queue.

**Comment by eparis** [comment]
sadly everyone is on about a 2+ day wait.  too many e2e failures blocking up the works  :-(

**Comment by piosz** [comment]
@k8s-bot e2e test this issue: #20694

**Comment by piosz** [comment]
After looking into e2e logs should be rather #21261

**Comment by mwielgus** [comment]
Required for custom metrics to work. Marking as P1.

**Pull request merged**
