### PR TITLE
Cluster Federation RFC

### PR DESCRIPTION
**Pull request by ghost**
Moving "Ubernetes" proposal from Google Doc format to Github Markup.
There are still some comments in the original Google Doc which have not yet been incorporated into this MD format, but I'll do that in a separate PR, rather than hold up getting the doc into github.

### CODE REVIEW

**Comment by preillyme** [comment]
Awesome I'm glad to see this moved over from the Google Doc.

**Comment by kelseyhightower** [comment]
@quinton-hoole Thanks for sharing this. I love the detail here and the proposal looks awesome.

**Comment by quinton-hoole** [comment]
@erictune oncall, merge?

**Comment by quinton-hoole** [comment]
PS:  This is just a dump of the document that you've already read.  No need to reread the whole thing.

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
