### PR TITLE
route53: configure verbose authentication errors

### PR DESCRIPTION
**Pull request by justinsb**
Otherwise we get an error message which is confusingly written on
authentication failures.

Probably blocked on #39854

### CODE REVIEW

**Comment by nikhiljindal** [comment]
LGTM.
Happy to add the label once the blocking PR is merged

**Comment by thockin** [comment]
/lgtm

LGTM from the bulk LGTM tool

**Comment by justinsb** [comment]
@k8s-bot bazel test this issue #40295

**Comment by justinsb** [comment]
Reapplying LGTM after trivial rebase

**Pull request merged**
