### PR TITLE
Manual cherrypick of part of #44053 to release-1.6

### PR DESCRIPTION
**Pull request by thockin**
This is a manual application of git commit 7664b97ed2f40bdb to release-1.6 branch, because the context leading up to that commit was a lot of churn not necessary for the surgical fix.  We have at least one user report of hitting this.

```release-note
Fix for kube-proxy healthcheck handling an update that simultaneously removes one port and adds another.
```

@ethernetdan are you patch czar for 1.6 ?

### CODE REVIEW

**Comment by thockin** [comment]
@MrHohn @freehan there is significantly different context for 1.5 - do either of you have time to help me backport this?  Or should we not try?  Feedback welcome..

**Review by MrHohn — APPROVED** [review]

**Comment by MrHohn** [comment]
> there is significantly different context for 1.5 - do either of you have time to help me backport this? Or should we not try?

Let me give it a try.

**Comment by MrHohn** [comment]
Took a look at the codes, it seems a bit risky to cherrypick the whole commit (7664b97) into 1.5, given recent overhauls on kube-proxy. Specifically, for backporting the new added healthCheck update tests, we have at least these dependencies:
- Refactor OnEndpointsUpdate for testing (9507af3c79a8ecb90e6912e5f7d80de7f87385af)
- Add tests for updateEndpoints (6069d49d49f2f2477219c6028da5e5060d98458d)
- Make healthcheck an interface (cddda17d42c333fbb0749d8fc7c4a22f64b720be)

However, if we only cherrypick the `proxier.go` part (which basically just changes `map[proxy.ServicePortName]bool` to `map[types.NamespacedName][]*endpointsInfo{}`), it seems simple enough and sufficient for the bug fix.

What do you think? @thockin @freehan

**Comment by thockin** [comment]
That's even more surgical, but it means net-new code.  If we port an
equivalent testcase it could fly.

**Comment by enisoc** [comment]
@thockin I tried to reword the release note in terms of what a user might observe. Please edit it if I've mangled the meaning.

**Comment by MrHohn** [comment]
Quick update, just reproduced the same issue on with latest 1.6 codes:
- Create a LoadBalancer Service with OnlyLocal annotation on it (and the backends):
```
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  selector:
    run: my-nginx
  ports:
  - name: "port1"
    port: 80
    protocol: TCP
  type: LoadBalancer
```
- Rename the port name from "port1" to "port2"
- kube-proxy stops servicing health check for this service on nodes.

Dug a bit into it, found the bug is triggered by [OnServiceUpdate](https://github.com/kubernetes/kubernetes/blob/e6efeb5d4bf653a0c7004ecfa3d198a958d62e4b/pkg/proxy/iptables/proxier.go#L536-L549), but this cherrypick only fixes OnEndpointUpdate :(

**Comment by thockin** [comment]
We may want to roll this back, depending on what the real fix to the fix is.  This alone is not detrimental, but it seems it is incomplete.

**Comment by cblecker** [comment]
@MrHohn @thockin Do we need an additional PR to fix `OnServiceUpdate` on the 1.6 branch too?

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/pull/44315 covered it.

**Pull request merged**
