### PR TITLE
controller: fix panic in deployments

### PR DESCRIPTION
**Pull request by 0xmichalis**
Fixes https://github.com/kubernetes/kubernetes/issues/36488

@kubernetes/deployment

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36491)

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM

**Comment by kargakis** [comment]
@k8s-bot unit test this https://github.com/kubernetes/kubernetes/issues/36473

**Comment by kargakis** [comment]
@k8s-bot gci gce e2e test this https://github.com/kubernetes/kubernetes/issues/33380

**Comment by kargakis** [comment]
@k8s-bot unit test this #36473

**Pull request merged**
