### PR TITLE
Factored out simulate from nodeShouldRunDaemonPod.

### PR DESCRIPTION
**Pull request by gyliu513**
Addressed comments from https://github.com/kubernetes/kubernetes/pull/48189#issuecomment-312223162

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

/sig apps

### CODE REVIEW

**Comment by mikedanese** [comment]
Thanks for the cleanup PR. 

/lgtm

**Comment by mikedanese** [comment]
I'm going to let #48189 merge then this is good to go.

**Comment by gyliu513** [comment]
@mikedanese I think that this is ready to go.

**Pull request merged**
