### PR TITLE
fix a potential deadlock

### PR DESCRIPTION
**Pull request by charlesxsh**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR tries to fix a potential deadlock issue. If line 214 happened before line 213, line 185 will be blocked forever. 

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Similar PR/fix: https://github.com/kubernetes/kubernetes/pull/83925.

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by charlesxsh** [comment]
hi there, any update on this PR?

**Comment by charlesxsh** [comment]
@deads2k Hi there, kindly ask would you mind taking a look at this PR and approve if nothing wrong when you got time?

**Comment by songlh** [comment]
There is a leaked goroutine if the timeout at [line 215](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/serviceaccount/serviceaccounts_controller_test.go#L215) happens, because there is no other goroutine that can close channel syncCalls or receive messages from channel syncCalls. 

The patch is to increase the buffer size of channel syncCalls from 0 to 1, since syncCalls is only used to transmit one message. The patch does not change the program behavior if the timeout does not happen, and it can enable the leaked goroutine to terminate by itself when the timeout happens.

**Comment by songlh** [comment]
@deads2k Could you help review the patch?

**Comment by dims** [comment]
/assign @liggitt 

NOTE: it's one line, but you have way better context to help with this Jordan!

**Pull request merged**
