### PR TITLE
Ensuring EndpointSlice controller does not start when feature gate or API are disabled

### PR DESCRIPTION
**Pull request by robscott**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This ensures that the EndpointSlice controller will not start when the feature gate or API have been disabled.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
- Enhancement Issue: https://github.com/kubernetes/enhancements/issues/752

/sig network
/priority important-soon
/milestone v1.17
/cc @liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
/lgtm
/approve

thanks

**Comment by robscott** [comment]
In case anyone's curious what happened here, the GitHub UI showed this branch as having conflicts with master. I fetched the latest and rebased, but apparently in the minute it took me to do this, the PR actually got merged, so I ended up pushing an update to this branch that had the merge commit of the commit that this PR was originally based on.

**Pull request closed without merging**
