### PR TITLE
Add 'sc' as a short for storageclass in valid_resources

### PR DESCRIPTION
**Pull request by walteraa**
**What this PR does / why we need it**:
Just add the information to use short form of `storageclass` in the valid resource, adding `(aka 'sc')` beside of storageclass.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
/sig cli

**Release note**:

```release-note
Now users can see how to use short form to `storageclass`.
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
Like all short forms, this has to be common enough in use that benefits most users.  StorageClasses are not frequently accessed by regular users.  I don't think based on previous criteria this meets the bar for a short form.

**Comment by walteraa** [comment]
@smartrclayton the shortform already exists in Kubernetes master. The information about it is missing in the information in the `valid_resource`. I think you don't understood the proposal of this PR.

**Comment by smarterclayton** [comment]
Hrm - that should not have been added, as it doesn't meet the bar.  Not sure how that got approved.

**Comment by walteraa** [comment]
@smarterclayton some tutorials(e.g.: [this](http://blog.kubernetes.io/2017/03/dynamic-provisioning-and-storage-classes-kubernetes.html), [this](https://github.com/kubernetes/examples/blob/master/staging/volumes/scaleio/README.md) ) in the official repository are using this short form. Remove it can bring issues for user that have been using this short form in automation scripts which uses `kubectl`?

**Comment by smarterclayton** [comment]
No, we can't remove it once it is public.  This is why we have fairly
strict rules for what can become a short name, since they become part of
the public API and they limit what can be consumed.  This should have been
reserved for "service classes" which are more important for most users than
storage classes (which only admins ever deal with).

**Pull request closed without merging**
