### PR TITLE
use ControllerRevisionControllerRefManager in StatefulSet

### LINKED ISSUE #88150: use ControllerRevisionControllerRefManager in StatefulSet like DaemonSet
**What would you like to be added**:

update StatefulSet to use `ControllerRevisionControllerRefManager`, xref: https://github.com/kubernetes/kubernetes/pull/84984/files#r344144617

**Why is this needed**:

this can simplify the code in StatefulSet

### PR DESCRIPTION
**Pull request by GreyBalloonYU**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
StatefulSet can use ControllerRevisionControllerRefManager to adopt its orphan revisions.
#### Which issue(s) this PR fixes:

Fixes #88150

#### Special notes for your reviewer:
This is my first PR in k8s, please indicate my mistake.
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by GreyBalloonYU** [comment]
Can you take some time to review my code? @cofyc

**Comment by dims** [comment]
Is this PR still needed, please rebase if so (or we can close it?)

**Comment by GreyBalloonYU** [comment]
> Is this PR still needed, please rebase if so (or we can close it?)

PTAL? @cofyc @deads2k @smarterclayton

**Comment by dims** [comment]
This PR is older than 4 weeks and needs as rebase.

Please rebase the PR against latest master and reopen if still needed.

/close

**Pull request closed without merging**
