### PR TITLE
fix bad url

### PR DESCRIPTION
**Pull request by stewart-yu**
**What this PR does / why we need it**:
The link url is bad, fix it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
@stewart-yu This PR needs to be opened against the master branch and not the `release-1.7` branch.

**Comment by stewart-yu** [comment]
This pr is to fix bad url in release-1.7 branch， does to be opened against the master branch? @nikhita

**Comment by nikhita** [comment]
@stewart-yu Typically, when something needs to be merged into a previous release branch, a PR is created against the master first. Then it is cherry-picked to the release-1.7 branch, if the branch manager (@wojtek-t for 1.7) approves.

But like you said, it looks like the file does not exist on master in this case.

@wojtek-t What must be done here?

**Pull request merged**
