### PR TITLE
Automated cherry pick of #66581 upstream release 1.10

### PR DESCRIPTION
**Pull request by janetkuo**
Automated cherry pick of #66581 upstream release 1.10

**Release note**:

```release-note
extensions/v1beta1.Deployment .spec.progressDeadlineSeconds should be defaulted to "no deadline" instead of 600. 
```

### CODE REVIEW

**Comment by MaciekPytel** [comment]
@janetkuo Do we still need this? As 1.10 is in the middle of its supported lifecycle a fix that will only help people who haven't updated to 1.10 yet seems progressively less useful. At the same time the number of people who will see behavior change between patch releases grows.

**Comment by janetkuo** [comment]
@MaciekPytel 1.10 is when the bug was exposed. For users upgrading from 1.9 this fix would still be useful for them.

**Comment by janetkuo** [comment]
/assign @smarterclayton 
since you've reviewed & approved #66581

**Comment by MaciekPytel** [comment]
@janetkuo 1.10 is reaching end of life. Does it still make sense to fix this? If so it needs an approval by tomorrow EOD to make it into the final patch release.

**Comment by MaciekPytel** [comment]
With 1.13 released 1.10 has reached end of life. 1.10.12 was the last patch release and we're no longer accepting cherry-picks to 1.10 branch.

**Pull request closed without merging**
