### PR TITLE
Update NPD version to v0.3.0-alpha.0 in kubemark.

### PR DESCRIPTION
**Pull request by Random-Liu**
@wojtek-t @shyamjvs Update the NPD version in kubemark.

I just built the alpha release https://github.com/kubernetes/node-problem-detector/releases/tag/v0.3.0-alpha.0.

And the PR https://github.com/kubernetes/node-problem-detector/pull/79 is included.

However, I'm not sure whether 1 minute period is longer enough.

If it's still not longer enough, in fact we can extend it by split the resync and heartbeat:
* Every 1 minute, check whether there is inconsistency between apiserver and npd, and only update when there is inconsistency. (1 GET/m)
* Every > 2 minute, do forcibly update as heartbeat. (<0.5 PATCH/m)

And I can also make the sync period configurable after we finalize the sync mechanism.

### CODE REVIEW

**Comment by shyamjvs** [comment]
@Random-Liu Thanks for the alpha release. It would be great if you could update the heapster vendored code in npd as well, as we can then also remove the service-account overwrite hack.

**Comment by Random-Liu** [comment]
> Thanks for the alpha release. It would be great if you could update the heapster vendored code in npd as well, as we can then also remove the service-account overwrite hack.

@shyamjvs Will do that later. There are some Godep problems when I tried last time.

**Comment by shyamjvs** [comment]
> @shyamjvs Will do that later. There are some Godep problems when I tried last time.

That's ok. Recently, Godep has been giving me my fair share of miseries too :)

**Pull request merged**
