### PR TITLE
Timeout cadvisor call when updating node status

### LINKED ISSUE #53207: kubelet status updates wedging after failed CRI call
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Occasionally our nodes stop reporting their status to apiserver, and get marked as NotReady. However, they remain connected to the apiserver and receive the update to delete all their pods - which they do.

```
  OutOfDisk 		Unknown 	Thu, 28 Sep 2017 07:55:44 +0000 	Thu, 28 Sep 2017 07:57:04 +0000 	NodeStatusUnknown 	Kubelet stopped posting node status.
  MemoryPressure 	Unknown 	Thu, 28 Sep 2017 07:55:44 +0000 	Thu, 28 Sep 2017 07:57:04 +0000 	NodeStatusUnknown 	Kubelet stopped posting node status.
  DiskPressure 		Unknown 	Thu, 28 Sep 2017 07:55:44 +0000 	Thu, 28 Sep 2017 07:57:04 +0000 	NodeStatusUnknown 	Kubelet stopped posting node status.
  Ready 		Unknown 	Thu, 28 Sep 2017 07:55:44 +0000 	Thu, 28 Sep 2017 07:57:04 +0000 	NodeStatusUnknown 	Kubelet stopped posting node status.
  KernelDeadlock 	False 		Thu, 28 Sep 2017 07:58:38 +0000 	Wed, 27 Sep 2017 08:44:28 +0000 	KernelHasNoDeadlock 	kernel has no deadlock
```

In this example, the node last reported at 7:55:44.

This always seems to happen after I see these sort of log messages:
```
Sep 28 07:57:54 ip-10-50-97-190 start-kubelet.sh[1748]: E0928 07:57:54.064121    1748 remote_runtime.go:163] ListPodSandbox with filter "nil" from runtime service failed: rpc error: code = 4 desc = context deadline exceeded
Sep 28 07:57:54 ip-10-50-97-190 start-kubelet.sh[1748]: E0928 07:57:54.064194    1748 kuberuntime_sandbox.go:185] ListPodSandbox failed: rpc error: code = 4 desc = context deadline exceeded
Sep 28 07:57:54 ip-10-50-97-190 start-kubelet.sh[1748]: E0928 07:57:54.064209    1748 generic.go:198] GenericPLEG: Unable to retrieve pods: rpc error: code = 4 desc = context deadline exceeded
Sep 28 07:57:54 ip-10-50-97-190 start-kubelet.sh[1748]: E0928 07:57:54.081115    1748 remote_runtime.go:163] ListPodSandbox with filter "&PodSandboxFilter{Id:,State:&PodSandboxStateValue{State:SANDBOX_READY,},LabelSelector:map[string]string{},}" from runtime service failed: rpc error: code = 4 desc = context deadline exceeded
Sep 28 07:57:54 ip-10-50-97-190 start-kubelet.sh[1748]: E0928 07:57:54.081169    1748 kuberuntime_sandbox.go:185] ListPodSandbox failed: rpc error: code = 4 desc = context deadline exceeded
Sep 28 07:57:54 ip-10-50-97-190 start-kubelet.sh[1748]: E0928 07:57:54.081187    1748 kubelet_pods.go:842] Error listing containers: &grpc.rpcError{code:0x4, desc:"context deadline exceeded"}
Sep 28 07:57:54 ip-10-50-97-190 start-kubelet.sh[1748]: E0928 07:57:54.081210    1748 kubelet.go:1886] Failed cleaning pods: rpc error: code = 4 desc = context deadline exceeded
```

Which looks like the dockershim is timing out, maybe blocked on something.

Oddly, I never see these errors again in the kubelet logs - which indicates to me the PLEG loop continues to run successfully.

However after this time, all heartbeats to the apiserver stop. This even happened on an apiserver node, where kubelet connects to the localhost. So it doesn't seem like a network issue to me.

Next time this happens I'll try to capture a goroutine dump.

**What you expected to happen**:

Even if there is a temporary blip in the PLEG loop, kubelet should continue to send heartbeats, and then eventually go ready again.

**How to reproduce it (as minimally and precisely as possible)**:
I've been unable to reproduce it yet - it happens quite infrequently.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.9 / 1.7.10
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by jsravn**
As this will call out to the container runtime (e.g. docker) under the
hood, without any timeouts. This can lead to a hanging sync goroutine.
Guard against this by adding a timeout on the call.

It is not perfect, since it can lead to leaking goroutines. It will be
best to fix this in cadvisor as well.

Fix https://github.com/kubernetes/kubernetes/issues/53207.

```release-note
Time out hanging cadvisor calls when updating node status. This allows kubelet node sync to recover.
```

### CODE REVIEW

**Comment by jsravn** [comment]
It might be better to avoid querying docker at all as part of the node status update. I think it's unnecessary to do that so frequently. But I think that's a larger change.

**Comment by mtaufen** [comment]
seems reasonable to me, and code looks good
@yujuhong does this make sense to you?

**Comment by mtaufen** [comment]
Another option may be to add timeouts in cadvisor itself (when it constructs the http client it uses to make the call), and avoid the potential leaking goroutine issue. @dashpole

**Comment by jsravn** [comment]
I made https://github.com/google/cadvisor/pull/1830 to add the timeouts there, then we shouldn't leak goroutines. I think it'd be better to expose the context though, but not sure about breaking the API. For cherry pick at least.

**Comment by yujuhong** [comment]
@jsravn thanks for root causing the issue!

> I made google/cadvisor#1830 to add the timeouts there, then we shouldn't leak goroutines. I think it'd be better to expose the context though, but not sure about breaking the API. For cherry pick at least.

Make sense. I'm not sure if we can break or release a new cadvisor API version. /cc @dashpole 
This PR minimizes the change surface and is more suitable for cherrypicks. However, if we ever need to add timeouts for other cadvisor calls, we should either change the cadvisor api, or at least wrap the cadvisor client in kubelet with timeout support (as opposed to ad hoc timeout all over the place).

Kubelet doesn't even use the docker API version information returned by cadvisor, so it's a shame that we have to wait for docker to respond.
Another possible mitigate is to cache the OS image and kernel version in kubelet (since they shouldn't change randomly) to reduce unnecessary queries. That's more of a optimization though.

**Comment by dashpole** [comment]
we can cut a new cadvisor release if needed.

**Comment by jsravn** [comment]
Okay, let me make a cadvisor PR with API changes to take a context. Then we can handle it more nicely in kubelet. Not sure if you want to keep this PR or not for cherry picking.

**Comment by jsravn** [comment]
Made https://github.com/google/cadvisor/pull/1832 with the API changes to take a context. If that gets merged/released I can make another k8s PR with the required changes.

**Comment by jsravn** [comment]
Made the cadvisor change in https://github.com/kubernetes/kubernetes/pull/56967.

Do we still want this for 1.8? It would be nice to have a fix there.

**Comment by jsravn** [comment]
@yujuhong What do you think? I made a cherrypick of the cadvisor change but it brings in a lot of cadvisor commits (from last 3 mo). So I think it won't be viable to cherry pick the cadvisor fix. But this PR should be okay.

**Comment by dashpole** [comment]
We do not cherrypick the 0.28 cadvisor branch into 1.8.
The correct process is to cherrypick the cadvisor commit to the cadvisor 0.27 branch, cut v0.27.4 in cadvisor, and then cherrypick that into 1.8

**Comment by jsravn** [comment]
@dashpole I created a cherry pick PR for cadvisor at https://github.com/google/cadvisor/pull/1840.

**Comment by jsravn** [comment]
Cherry picked to https://github.com/kubernetes/kubernetes/pull/58074

**Pull request closed without merging**
