### PR TITLE
kubeadm: adds etcd server version for 1.13

### LINKED ISSUE #1256: kubeadm fails to recognize etcd version for v1.1.3
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): 

```
kubeadm version: &version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.0-beta.1.17+e64f3e02a5c0be", GitCommit:"e64f3e02a5c0bed379f582f06c714ab0a4eed768", GitTreeState:"clean", BuildDate:"2018-11-19T17:57:20Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
```
root@ip-10-0-0-7:~# kubeadm upgrade plan v1.13.0
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration from the cluster...
[upgrade/config] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[upgrade] Fetching available versions to upgrade to
[upgrade/versions] Cluster version: v1.12.2
[upgrade/versions] kubeadm version: v1.12.2
[upgrade/versions] WARNING: No recommended etcd for requested kubernetes version (v1.13.0)

Components that must be upgraded manually after you have upgraded the control plane with 'kubeadm upgrade apply':
COMPONENT   CURRENT       AVAILABLE
Kubelet     1 x v1.12.2   v1.13.0

Upgrade to the latest version in the v1.12 series:

COMPONENT            CURRENT   AVAILABLE
API Server           v1.12.2   v1.13.0
Controller Manager   v1.12.2   v1.13.0
Scheduler            v1.12.2   v1.13.0
Kube Proxy           v1.12.2   v1.13.0
CoreDNS              1.2.2     1.2.2
Etcd                 3.2.24    N/A

You can now apply the upgrade by executing the following command:

        kubeadm upgrade apply v1.13.0

Note: Before you can perform this upgrade, you have to update kubeadm to v1.13.0.
```

## What you expected to happen?
I expected kubeadm to know what server version 1.13 needs.

## How to reproduce it (as minimally and precisely as possible)?
run `kubeadm upgrade plan v1.13.0`

## Anything else we need to know?
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go#L387

is where the fix could be.

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <ha.chuck@gmail.com>

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR sets the etcd server version for kubeadm for upgrades.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes kubernetes/kubeadm#1256

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by chuckha** [comment]
/priority critical-urgent

this is breaking upgrades from 1.12 to 1.13

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Review by neolit123 — APPROVED** [review]
thanks @chuckha 
ok, i guess in the followup PR that @rosti promised to do we can remove the 1.10 remains.

**Review by fabriziopandini — APPROVED** [review]
@chuckha Thanks!
/approve
/lgtm

**Pull request merged**
