### PR TITLE
bump agnhost version to match fully

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
part of #92059 
next part is bumping to use the matching image in the e2e ..

**Review by hasheddan — APPROVED** [review]
Thanks @BenTheElder! I think I missed this on a PR 😕

/lgtm

**Comment by hasheddan** [comment]
Oh just kidding looks like a subsequent PR to mine, thanks anyway!

**Comment by BenTheElder** [comment]
it was me :-)

**Pull request merged**
