### PR TITLE
fix golint for /pkg/util/ipconfig and /pkg/util/resourcecontainer

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:
Fixes golint issues in /pkg/util/ipconfig and /pkg/util/resourcecontainer
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mysunshine92** [comment]
approved

**Comment by qingsenLi** [comment]
/assign @lavalamp
/cc
thanks

**Pull request merged**
