### PR TITLE
`failure-domain` is no longer used in command line arg.

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by gyliu513** [comment]
@k8s-bot unit test this

**Comment by ncdc** [comment]
@wojtek-t this comment is safe to remove?

**Comment by gyliu513** [comment]
`failure-domain` is deprecated in https://github.com/kubernetes/kubernetes/pull/41195 , and there are also some discussion here https://groups.google.com/forum/#!msg/kubernetes-sig-scheduling/P249hlfGcdw/_wfQ7UOlBQAJ @ncdc

**Comment by gyliu513** [comment]
Related with https://github.com/kubernetes/kubernetes.github.io/pull/3352

**Comment by wojtek-t** [comment]
@ncdc - yes it is.

/lgtm
/approve

**Pull request merged**
