### PR TITLE
Update gomock to 1.4.4, removing a few extra dependencies.

### PR DESCRIPTION
**Pull request by dlorenc**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This re-removes rsc.io/quote and rsc.io/sampler from the go.mod.
They never made it into the vendor/ tree, but still contribute
to dependency resolution complexity.

These were originally removed in #97337 but slipped back in.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/assign @liggitt 

Mainly the `golang.org/x/*` gets updated, all are getting bumped to newer versions ... so looks sane!

/priority important-soon
/triage accepted

/approve
/lgtm

**Review by BenTheElder — APPROVED** [review]

**Comment by liggitt** [comment]
/retest

/approve

can we add the quote and sampler deps to https://github.com/kubernetes/kubernetes/issues/102145

**Comment by liggitt** [comment]
lgtm once rebased

**Comment by dlorenc** [comment]
Rebased!

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/issues/102887
/retest

**Comment by pacoxu** [comment]
/lgtm
will rebase #102695 after this PR is merged

**Comment by liggitt** [comment]
thanks for the rebasing diligence… satisfying to see things get slimmed down

**Pull request merged**
