### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by x13n**
I should've done that in https://github.com/kubernetes/kubernetes/pull/55466. The version was already bumped, this is just to keep track of what changed.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by MrHohn** [comment]
/lgtm
though I'm not an approver.

Probably squash commits?

**Comment by x13n** [comment]
Thanks, I should've checked the OWNERS file instead of who was doing a lot of changes here. Commits squashed.

/assign @roberthbailey

**Review by MrHohn — APPROVED** [review]
/lgtm

**Pull request merged**
