### PR TITLE
Nit: Replace `errors.New(fmt.Sprintf(...))` with `fmt.Errorf(...)`

### PR DESCRIPTION
**Pull request by ialidzhikov**
/kind cleanup

The corresponding golint warning is:
```
pkg/credentialprovider/plugin/plugin_test.go
Line 814: warning: should replace errors.New(fmt.Sprintf(...)) with fmt.Errorf(...) (golint)
```

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
Friendly ping @deads2k

**Review by jiahuif — APPROVED** [review]
/lgtm
Don't forget to sign CLA.

**Comment by aojea** [comment]
lgtm
/assign @liggitt

**Comment by ialidzhikov** [comment]
> Don't forget to sign CLA.

I think this was caused by the migration to EasyCLA. The PR was opened before the migration to EasyCLA. With the migration that happened the EasyCLA was not okay. I now did a no-op force push and the check is fixed.

**Pull request merged**
