### PR TITLE
Manual-cherry-pick-for-1.23: kubeadm: apply registry.k8s.io changes

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

manual, kubeadm scoped backport of:
https://github.com/kubernetes/kubernetes/pull/109938
https://github.com/kubernetes/kubernetes/pull/110343

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/kubeadm/issues/2671

#### Special notes for your reviewer:

it is essentially a feature backport, as discussed with k8s-infra and sig-release

https://kubernetes.slack.com/archives/C2C40FMNF/p1666723622759119
https://github.com/kubernetes/kubeadm/issues/2671#issuecomment-1290991218

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: use the image registry registry.k8s.io instead of k8s.gcr.io for new clusters. During upgrade, migrate users to registry.k8s.io if they were using the default of k8s.gcr.io.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pacoxu — APPROVED** [review]
/lgtm
/approve

**Review by SataQiu — APPROVED** [review]
/lgtm
/approve

**Comment by pacoxu** [comment]
/assign @BenTheElder
for build package approval

**Comment by neolit123** [comment]
@cpanato can we get this in as it's also keeping one of the kubeadm upgrade jobs broken?
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1-22-1-23

**Review by cpanato — APPROVED** [review]
/triage accepted
/priority important-soon
/lgtm

**Pull request merged**
