### PR TITLE
Automated cherry pick of #57919: add folder named custom in gce

### PR DESCRIPTION
**Pull request by dashpole**
Cherry pick of #57919 on release-1.8.

#57919: add folder named custom in gce

### CODE REVIEW

**Comment by dashpole** [comment]
cc @yguo0905 @abgworrall

**Comment by yguo0905** [comment]
New tests running against 1.8 will be created with option `--gcp-node-image=CUSTOM`, which requires this folder to exist in the 1.8 branch.

**Comment by jpbetz** [comment]
/hold
Hold all unmerged cherrypicks for cut of patch release on Monday.

**Comment by yguo0905** [comment]
Is this OK to unhold now?

**Pull request merged**
