### PR TITLE
Fix premature return

### LINKED ISSUE #50040: kubectl apply error
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
kubectl apply fails with "unable to find api field in struct Container for the json field "$setElementOrder/env""

**What you expected to happen**:
Should not fail

**How to reproduce it (as minimally and precisely as possible)**:
Using kubectl v1.7, if the modified version
- deletes an element from an array (say `env`)
- reorders or modifies another array (say `volumeMounts`)

Applying the modified version will result in this error.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7
- Cloud provider or hardware configuration**: GKE
- OS (e.g. from /etc/os-release): Ubuntu
- Kernel (e.g. `uname -a`): 3.13.0-116-generic
- Install tools: GKE
- Others:

### PR DESCRIPTION
**Pull request by guoshimin**
**What this PR does / why we need it**: Fixes a bug where the loop is prematurely terminated.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50040 

**Special notes for your reviewer**:

**Release note**: 

```
Fixed a bug in strategic merge patch that caused kubectl apply to error under some conditions
```

### CODE REVIEW

**Comment by guoshimin** [comment]
Signed the CLA

**Comment by apelisse** [comment]
/ok-to-test

Would you mind explaining how you found that bug? This code is complicated to understand and I'd really feel more confident if we could have better tests. I have the feeling that this is a good opportunity.

**Comment by guoshimin** [comment]
I wrote a tool which used the strategicpatch package. I encountered the error `unable to find api field in struct Container for the json field "$setElementOrder/env"` for some input, but only some of the times. From there, by tracing successful runs and failed runs, I was able to find the problem. The nondeterminism was caused by the random map traversal order.

Although I found the bug via my tool, I believe the bug affects kubectl apply too. The condition to trigger the bug is when you are
- deleting one or more elements from an array,
- modifying one or more elements from the same array, and
- modifying one or more elements from another array

Here's a minimum example:
```
import "k8s.io/api/core/v1"

func TestMergeMap(t *testing.T) {
        for i := 0; i < 100; i++ {
                original := map[string]interface{}{
                        "env": []interface{}{
                                map[string]interface{}{
                                        "$patch": "delete",
                                        "name":   "AAA",
                                },
                        },
                        "$setElementOrder/env": []interface{}{
                                map[string]interface{}{
                                        "name": "BBB",
                                },
                        },
                }
                patch := map[string]interface{}{
                        "$setElementOrder/volumeMounts": []interface{}{},
                        "env": []interface{}{
                                map[string]interface{}{
                                        "name":  "BBB",
                                        "value": "BBB",
                                },
                        },
                        "$setElementOrder/env": []interface{}{
                                map[string]interface{}{
                                        "name": "BBB",
                                },
                        },
                }
                typ := reflect.TypeOf(v1.Container{})
                _, err := mergeMap(original, patch, typ, MergeOptions{})
                if err != nil {
                        t.Errorf(err.Error())
                        t.FailNow()
                }
        }
}
```

**Comment by apelisse** [comment]
Awesome @guoshimin! @mengqiy can you take a look and see if this can be included in the unit-test suite?

**Comment by mengqiy** [comment]
LGTM 
@guoshimin Thanks for fixing this bug. We need a test to cover this.
You can include the test in the existing test framework:https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch_test.go#L1114.

IMO we don't need a release note for this fix, do we? Can you update the release-note section in the PR body.

**Comment by guoshimin** [comment]
Updated the release note

**Comment by mengqiy** [comment]
Can you add the test case in https://github.com/kubernetes/kubernetes/pull/49834#issuecomment-318881567 to prevent regression in the future?

**Comment by guoshimin** [comment]
Will do

**Comment by guoshimin** [comment]
Added test. PTAL.

**Comment by mengqiy** [comment]
/lgtm
Please squash commits for merging.

**Comment by guoshimin** [comment]
gentle ping @pwittrock

**Comment by pwittrock** [comment]
Thanks!

**Comment by guoshimin** [comment]
Now that this is merged, how do we include it in the next patch release?

**Comment by mengqiy** [comment]
This will be included in v1.8.0.
It you want it in 1.7, you will need to backport it to branch `release-1.7`.

**Pull request merged**
