### PR TITLE
CRI: various spelling and typo fixes

### PR DESCRIPTION
**Pull request by jonboulle**
Also clarify whether some properties belong to containers or sandboxes.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33476)

### CODE REVIEW

**Comment by jonboulle** [comment]
@yifan-gu review?

**Comment by yifan-gu** [comment]
LGTM

**Comment by yifan-gu** [comment]
@k8s-bot ok to test

**Comment by yifan-gu** [comment]
@k8s-bot test this please, issue #IGNORE

**Comment by jonboulle** [comment]
@k8s-ci-robot test this please, issue #33672

**Comment by jonboulle** [comment]
@k8s-bot gke e2e test this please, issue #33672

**Comment by yifan-gu** [comment]
@k8s-bot gke e2e test this please, issue #33672

**Comment by jonboulle** [comment]
@yifan-gu hellppppppppppp

**Comment by xiang90** [comment]
@k8s-bot gke e2e test this please, issue #33672

**Pull request merged**
