### PR TITLE
[WIP] apiserver: annotate requests that arrive early (server not ready) or late (during shutdown)

### PR DESCRIPTION
**Pull request by tkashem**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

add audit annotations to incoming requests that:
- arrive too early (server not fully initialized yet) 
- arrive during the graceful server shutdown window

Why do we need it:
Some HA clusters front their kube-apiserver instances with load balancers, both external and internal. We want to understand how long it takes the load balancers to respect the readiness (/readyz) probes and take an unhealthy apiserver instance out of its pool.
The client (a disruption test), upon receiving an error from its probe, can use the audit ID to fetch the corresponding audit entry, check if it has these annotations.

- I am hoping that this will help toward zero-disruption maintenance of a HA kube cluster.
- This feature is enabled with a new server option `annotate-early-and-late-requests`, by default it is not enabled, in keeping with the current behavior

Below is an example of a request that arrives late:
```
annotations {
  "apiserver.k8s.io/shutdown":"elapsed=1m5s threshold=93% late=true self=false loopback=false",
}
```
it gives us the following information:
- `shutdown-delay-duration` is `70s`. and the request arrived after `1m5s` since the apiserver received the TERM signal
- it's not a kube-apiserver self (loopback to itself) request
- the remote IP is not localhost

Similarly, the following is an annotation from an early request:
```
annotations {
  "apiserver.k8s.io/startup":"early=true self=false loopback=false"
}
```

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tkashem** [comment]
Once this is ready for review, it can be triaged, thanks!

/hold

**Review by neolit123 — COMMENTED** [review]
/remove-area kubeadm
/remove-sig cluster-lifecycle

**Pull request closed without merging**
