### PR TITLE
Update Rescheduler's manifest

### PR DESCRIPTION
**Pull request by bsalamat**
**What this PR does / why we need it**: Updates Rescheduler's manifest to use version 0.4.0

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Update Rescheduler's manifest to use version 0.4.0.
```

### CODE REVIEW

**Comment by vishh** [comment]
@bsalamat can you add more details on what this change means to k8s on GCE?

**Comment by jberkus** [comment]
adding priority

/priority critical-urgent

**Comment by bsalamat** [comment]
Rescheduler is changed to work with Scheduler's preemption. In the latest version of the Rescheduler, it only evicts Pods when a critical DaemonSet Pod cannot be scheduled. Other critical system pods rely on  the scheduler preemption logic to be scheduled.
Before the recent changes in the Rescheduler, it would evict Pods for any critical system Pods. So, using older versions of the Rescheduler could cause double preemption (one by the default scheduler and one by the Rescheduler) in Kubernetes 1.11 when a system critical Pod remains pending due to lack of resources in a cluster.

**Comment by ravisantoshgudimetla** [comment]
Is this network issue, when I skimmed through logs, I am seeing continuously following error:

`{default-scheduler } FailedScheduling: 0/5 nodes are available: 1 node(s) were unschedulable, 5 node(s) had unavailable network, 5 node(s) were not ready.`

**Comment by bsalamat** [comment]
I think tests should be fine now, if they finish!

**Comment by ravisantoshgudimetla** [comment]
@bsalamat So, what has changed to make tests pass? Was this related to something on infra side?

**Comment by yguo0905** [comment]
The tests were failing because the upgraded rescheduler:v0.4.0 image was not published yet. Tests passed since the image is there now.

**Comment by ravisantoshgudimetla** [comment]
@yguo0905 Thanks but I think scheduler wouldn't throw those errors and rescheduler pod won't be in Pending state for a long time if there is an issue with container image not available in registry.

**Comment by yguo0905** [comment]
> rescheduler pod won't be in Pending state for a long time if there is an issue with container image not available in registry

It's a static pod, which I guess makes a difference here.

**Pull request merged**
