### PR TITLE
nodecontroller: record node reboot event

### PR DESCRIPTION
**Pull request by simon3z**
This patch adds the support to detect and record a node reboot.

### CODE REVIEW

**Comment by roberthbailey** [comment]
@davidopp can you take a look (or reassign appropriately) since @lavalamp is out today?

**Comment by davidopp** [comment]
LGTM, but it says there are conflicts. Can you rebase?

**Comment by simon3z** [comment]
@davidopp I rebased but now it's getting late here and I can't wait for travis to finish. Can you check later if it's possible to merge it? Thanks!

**Comment by simon3z** [comment]
@davidopp can you help me here? I suspect there's a problem in Travis. The failure shouldn't be related to my patch.

**Comment by davidopp** [comment]
We're using the rule that if Shippable or Travis passes we'll merge, so I'm going to merge now.

**Pull request merged**
