### PR TITLE
Fix the incorrect deployment.status.unavailableReplicas

### LINKED ISSUE #21900: Deployment reports invalid status.unavailableReplicas
Found this in kube-controller-manager.log. Seems unrelated to test flakes (test didn't fail when this happens). 

https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/21852/kubernetes-pull-build-test-e2e-gce/30209/artifacts/?debugUI=CLOUD
```
Error syncing deployment: Deployment.extensions "redis-deployment-2" is invalid: status.unavailableReplicas: Invalid value: -1: must be greater than or equal to 0
```

cc @bgrant0607 @kargakis @mqliang @nikhiljindal @ironcladlou @soltysh @kubernetes/sig-config

### PR DESCRIPTION
**Pull request by janetkuo**
Fixes #21900; depends on #21713 (the first commit)

cc @bgrant0607 @kargakis @mqliang @nikhiljindal @ironcladlou @soltysh @kubernetes/sig-config

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM

**Comment by janetkuo** [comment]
@bgrant0607 PTAL

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
Merging.

**Pull request merged**
