### PR TITLE
Fixed permissions on namespace actions

### LINKED ISSUE #273: chmod +x namespace actions in kubernetes-master
```
proof: E: actions.namespace-delete: actions/namespace-delete is not executable
proof: E: actions.namespace-create: actions/namespace-create is not executable
proof: E: actions.namespace-list: actions/namespace-list is not executable
```

### PR DESCRIPTION
**Pull request by lazypower**
closes

**What this PR does / why we need it**: the newly introduced namespace-* actions are failing proof. Setting them as +x resolves proof errors emitting from `charm proof`

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/273

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by marcoceppi** [comment]
@k8s-bot unit test this

**Comment by chuckbutler** [comment]
@k8s-bot unit test this

**Pull request merged**
