### PR TITLE
Removing references to the Google CLA & adding FAQ link

### PR DESCRIPTION
**Pull request by foxish**
Previously reviewed at: https://github.com/kubernetes/kubernetes/pull/37028
Closed the old one as it was a branch on the main repo making it difficult to squash.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37606)

### CODE REVIEW

**Comment by bgrant0607** [comment]
@foxish Check doc verify results.

**Comment by foxish** [comment]
Reapplying lgtm based on previous comment.

**Comment by foxish** [comment]
@k8s-bot gci gke e2e test this

**Comment by foxish** [comment]
@k8s-bot kops aws e2e test this

**Comment by foxish** [comment]
@k8s-bot gci gke e2e test this

**Comment by foxish** [comment]
@k8s-bot test this issue #IGNORE

**Comment by foxish** [comment]
@k8s-bot verify test this

**Comment by foxish** [comment]
@kubernetes/test-infra-maintainers The Jenkins unit/integration job here appears to be stuck. PTAL.

**Comment by foxish** [comment]
@k8s-bot verify test this

**Comment by foxish** [comment]
@k8s-bot unit test this

**Comment by krzyzacy** [comment]
potentially same issue as https://github.com/kubernetes/kubernetes/pull/37655#issuecomment-263742059, we will keep track of it

**Pull request merged**
