### PR TITLE
Remove update/verify-munge-docs.sh

### PR DESCRIPTION
**Pull request by caesarxuchao**
These scripts are no long needed because:
1. most docs are moved to other repos
2. the mungers are pre-processing the docs for gh pages, which are created with a whole different process now.

cc @bgrant0607 @thockin

### CODE REVIEW

**Comment by grodrigues3** [comment]
i'll add lgtm once tests pass

**Comment by bgrant0607** [comment]
Our goal is to move all significant docs and examples out of the main repo. We no longer publish docs from this repo to github pages. The verify script is mostly a hindrance at this point. So, we're nuking it.

FYI: @lavalamp @pwittrock @devin-donnelly @jaredbhatti @jeffmendoza @viglesiasce @david-mcmahon @ixdy

**Comment by thockin** [comment]
should we nix the gh-pages branch now?

**Comment by bgrant0607** [comment]
Yes

**Comment by david-mcmahon** [comment]
There are many references to `munge-docs.sh`:
```
$ fgrep -r munge-docs.sh *
docs/devel/how-to-doc.md:valid, etc. To munge a document, simply run `hack/update-munge-docs.sh`. We
docs/devel/how-to-doc.md:verify that all documents have been munged using `hack/verify-munge-docs.sh`.
docs/devel/how-to-doc.md:After running `hack/update-munge-docs.sh`, you'll see a table of contents
docs/devel/how-to-doc.md:example file. Then `hack/update-munge-docs.sh` will generate a code block with
docs/devel/how-to-doc.md:generates the following after `hack/update-munge-docs.sh`:
docs/devel/how-to-doc.md:you run `hack/update-munge-docs.sh`. See
docs/devel/how-to-doc.md:After running `hack/update-munge-docs.sh`, you may see some code / mungers in
hack/verify-munge-docs.sh:  echo "${DOCROOT} is out of date. Please run hack/update-munge-docs.sh"
hack/verify-munge-docs.sh:  echo "${EXAMPLEROOT} is out of date. Please run hack/update-munge-docs.sh"
hack/verify-munge-docs.sh:  echo "${KUBE_ROOT}/ is out of date. Please run hack/update-munge-docs.sh"
hack/verify-munge-docs.sh:  echo "Docs need munging. Please run hack/update-munge-docs.sh"
hack/generate-docs.sh:echo "Generated docs have been placed in the repository tree. Running hack/update-munge-docs.sh."
hack/generate-docs.sh:"${KUBE_ROOT}/hack/update-munge-docs.sh"
hack/update-generated-docs.sh:echo "Generated docs have been placed in the repository tree. Running hack/update-munge-docs.sh."
hack/update-generated-docs.sh:"${KUBE_ROOT}/hack/update-munge-docs.sh"
hooks/pre-commit:if ! hack/verify-munge-docs.sh > /dev/null; then
hooks/pre-commit:  echo "  hack/update-munge-docs.sh"
```

**Comment by david-mcmahon** [comment]
What's generating TOCs now then?  I ask because during the release we update `CHANGELOG.md` and run munge-docs to update the TOC.  If this is the only thing still using the TOC generator, we'll have to come up with something else.

**Comment by caesarxuchao** [comment]
Are there other use cases other than generating TOC for the CHANGELOG.md? If that's the only use case I'd say we can manually run the TOC munger. Otherwise we should keep the update-munge-docs.sh.

**Comment by david-mcmahon** [comment]
To minimize disruption, let's leave update-munge-doc.sh (and verify?) for now.  We'll need an independent TOC generator at some point.

**Comment by caesarxuchao** [comment]
Ok, I can keep the updaet-*. Do we really need the verify-*?

**Comment by david-mcmahon** [comment]
You could probably remove one, but it's a set.  Either way.

**Comment by caesarxuchao** [comment]
Updated. @david-mcmahon PTAL. Thanks.

**Comment by thockin** [comment]
gh-pages branch has been removed

**Comment by bgrant0607** [comment]
@david-mcmahon You use the TOC for CHANGELOG.md?

Pretty much all other docs should be removed.

**Comment by bgrant0607** [comment]
@thockin Thanks!

**Comment by david-mcmahon** [comment]
@bgrant0607 Yes.  munge-docs is heavy handed for that, but at the time it conveniently took care of the CHANGELOG.md TOC too.   Next step is to replace this with a lighter footprint TOC generator and fully remove *munge-docs*.

**Comment by caesarxuchao** [comment]
@david-mcmahon may I get the lgtm? Thanks.

**Comment by david-mcmahon** [comment]
Now why did I lgtm this?  Not sure.   But [all of these](https://github.com/kubernetes/kubernetes/pull/38309#issuecomment-265584125) still need to be dealt with (at least for the verify- mentions)

**Comment by caesarxuchao** [comment]
I'll send a follow-up for this mention:
```
hooks/pre-commit:if ! hack/verify-munge-docs.sh > /dev/null; then
```

I'll send a followup to the doc repo to revise the docs.

**Comment by nikhiljindal** [comment]
Deleting gh-pages branch broke http://kubernetes.io/kubernetes/third_party/swagger-ui/ which is still one of the top results when searching for "kubernetes swagger".
Fixing it in https://github.com/kubernetes/kubernetes.github.io/pull/1921

**Pull request merged**
