### PR TITLE
Cherry pick of 15813: Fix races in ClusterDns e2e test

### PR DESCRIPTION
**Pull request by sttts**
This is important for 1.1 because it fixes a conformance test and should be part of the next conformance test tag.

### CODE REVIEW

**Comment by sttts** [comment]
@k8s-bot test this please

**Comment by sttts** [comment]
@k8s-bot test this please

**Comment by sttts** [comment]
@k8s-bot test this please

**Comment by sttts** [comment]
@k8s-bot test this please

**Comment by zmerlynn** [comment]
Can you please use the cherry pick tool? See https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md . There's other tools that tie into that and consume the PRs from there for generating release notes.

**Comment by sttts** [comment]
Superseeded by https://github.com/kubernetes/kubernetes/pull/16037

**Pull request closed without merging**
