### PR TITLE
Kubelet: Use RepoDigest for ImageID when available

### PR DESCRIPTION
**Pull request by DirectXMan12**
``` release-note
Use manifest digest (as `docker-pullable://`) as ImageID when available (exposes a canonical, pullable image ID for containers).
```

Previously, we used the docker config digest (also called "image ID"
by Docker) for the value of the `ImageID` field in the container status.
This was not particularly useful, since the config manifest is not
what's used to identify the image in a registry, which uses the manifest
digest instead.  Docker 1.12+ always populates the RepoDigests field
with the manifest digests, and Docker 1.10 and 1.11 populate it when
images are pulled by digest.

This commit changes `ImageID` to point to the the manifest digest when
available, using the prefix `docker-pullable://` (instead of
`docker://`)

Related to #32159

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34473)

### CODE REVIEW

**Comment by DirectXMan12** [comment]
cc @derekwaynecarr @ncdc @dchen1107 

This is the new-and-improved "let's not break kubemark" edition.

I added a default "empty" `InspectImageBy{ID,Ref}` response in the fake docker client constructor (instead of being set in `docker_manager_test.go`, like the last PR), so it will apply to all users of the fake Docker client, including Kubemark, because it should not be possible to get a nil non-error response from `InspectImageBy{ID,Ref}`.

**Comment by DirectXMan12** [comment]
whoops, the "run on rebased branch" messed things up.  Rebased manually and restored the necessary commit.

**Comment by DirectXMan12** [comment]
(see also #33014 and #34386)

**Comment by ncdc** [comment]
@k8s-bot gci gke e2e test this
@k8s-bot gke e2e test this

**Comment by derekwaynecarr** [comment]
@k8s-bot gke e2e test this

**Comment by DirectXMan12** [comment]
looks like a version of #34483.

@k8s-bot gci gke e2e test this

**Pull request merged**
