### PR TITLE
Automated cherry pick of #72143: Fix aad support in kubectl for sovereign cloud

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #72143 on release-1.12.

#72143: Fix aad support in kubectl for sovereign cloud

### CODE REVIEW

**Comment by andyzhangx** [comment]
ping @mikedanese @karataliu

**Comment by feiskyer** [comment]
/ok-to-test

@mikedanese  Could you help to approve the cherry pick? If you want this to be included in Kubernetes v1.12.8, please get it approved by end of this Friday.

/assign @mikedanese

**Comment by andyzhangx** [comment]
could you approve this PR: @mikedanese @smarterclayton @liggitt, thanks.

**Comment by liggitt** [comment]
I'll defer to @mikedanese as the original approver

**Comment by mikedanese** [comment]
Sorry I missed this.

/lgtm
/approve

**Comment by andyzhangx** [comment]
@liggitt could you approve then? Thanks.

**Comment by andyzhangx** [comment]
@liggitt could you approve then? Thanks.

**Comment by feiskyer** [comment]
kindly ping @liggitt for approval

**Comment by feiskyer** [comment]
@liggitt @caesarxuchao Could you help to get this approved?

Please notice that v1.12.10 will be the last patch release for 1.12 branch. If you think this change is reasonable, please get it merged at the end this Friday (June 28).

**Comment by feiskyer** [comment]
ping @liggitt @caesarxuchao

**Comment by feiskyer** [comment]
Sorry, this cherry pick hasn't approved before the deadline, and the branch-1.12 would be deprecated after next Monday's release.

/close

**Pull request closed without merging**
