### PR TITLE
Fix NewNotFound method name in comments

### PR DESCRIPTION
**Pull request by jhadvig**
Small fix in comments...

### CODE REVIEW

**Comment by jhadvig** [comment]
I'm a RedHat employee

**Comment by mbforbes** [comment]
I see you're good from #9799, but ping @smarterclayton for possible checkup on CLA (just so this isn't confusing to future oncalls)?

**Comment by mbforbes** [comment]
I think this is OK with one review as it's comment only.

**Comment by lavalamp** [comment]
LGTM-- but it would be great if you could appease googlebot.

**Comment by lavalamp** [comment]
Can you fix the CLA? Please make sure the same email is:
* in the group
* public on your github account
* embedded in your commit.

Thanks!

**Comment by smarterclayton** [comment]
You're in the group, so it's either github or the commit

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
I'm rerunning shippable.

**Pull request merged**
