### PR TITLE
Automated cherry pick of #37638 upstream release 1.4

### PR DESCRIPTION
**Pull request by roberthbailey**
Automated cherry pick of #37638 on release 1.4. 

#37638: Fix the equality checks for numeric values in cluster/gce/util.sh.

*note*: I have to manually resolve some conflicts, so this wasn't a fully clean cherry pick (but the end result looks right to me).

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37780)

**Comment by roberthbailey** [comment]
ping @jessfraz for proper labels to get this into the submit queue

**Comment by jessfraz** [comment]
labels added :)

**Comment by jessfraz** [comment]
manually merging since all green and the submit queue is blocked

**Pull request merged**
