### PR TITLE
kubeadm: fix-certs-generation-for-external-etcd

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR fixes an error when using external etcd but storing some external etcd certificate in the `/etcd/kuberentes/pki` folder with the same name used by kubeadm for local etcd certificates.

**Which issue(s) this PR fixes**:
Fixes # https://github.com/kubernetes/kubeadm/issues/1276

**Does this PR introduce a user-facing change?**:
```release-note
This PR fixes an error when using external etcd but storing etcd certificates in the same folder and with the same name used by kubeadm for local etcd certificates; for an older version of kubeadm, the workaround is to avoid file name used by kubeadm for local etcd.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```

/sig cluster-lifecycle
/priority important-soon
/assign @neolit123 @rosti @yagonobre 
/cc @seh

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/hold
thanks @fabriziopandini 
please add a release note.

**Review by yagonobre — COMMENTED** [review]
Thanks @fabriziopandini 
/lgtm

**Pull request merged**
