### PR TITLE
fix: do not hardcode nginx image URL in rc e2e test case

### PR DESCRIPTION
**Pull request by chewong**
Signed-off-by: Ernest Wong <chuwon@microsoft.com>

**What type of PR is this?**

Fixes test failure in https://testgrid.k8s.io/provider-azure-windows#aks-engine-azure-windows-master-staging.

ref: #95920

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by chewong** [comment]
ping @kow3ns @smarterclayton

**Comment by chewong** [comment]
ping @kow3ns @smarterclayton

**Review by soltysh — APPROVED** [review]
/approve
/triage accepted

**Pull request merged**
