### PR TITLE
fix shellcheck in sample-controller

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

fix shellcheck failures in `staging/src/k8s.io/sample-controller`

**Which issue(s) this PR fixes**:

work towards #72956

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Comment by nikhita** [comment]
@danielqsj Thank you!

/assign @sttts 
for approval

**Comment by danielqsj** [comment]
@sttts if you have time, can you help review this? Thanks

**Pull request merged**
