### PR TITLE
Remove in-tree openstack cloud provider

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

As part of the KEP process for Removing Cloud Providers from Kubernetes Core, We have moved the code over to https://github.com/kubernetes/cloud-provider-openstack.

Please see the issue:
https://github.com/kubernetes/enhancements/issues/1489

and the following KEPs for additional information:
- https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/2395-removing-in-tree-cloud-providers/README.md
- https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/2392-cloud-controller-manager/README.md
- https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/625-csi-migration/README.md
- https://github.com/kubernetes/enhancements/blob/master/keps/sig-storage/1489-csi-migration-cinder/README.md
- https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/669-out-of-tree-openstack/README.md

There are still API data structures related to cinder volumes that will still remain here in the main k/k repository. The main thing being removed is the in-tree cloud provider and the in-tree support for cinder volumes. Please use the documentation and code from https://github.com/kubernetes/cloud-provider-openstack.

The in-tree cloud provider was deprecated in https://github.com/kubernetes/kubernetes/pull/63524

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/milestone v1.13

**Release note**:

```release-note
The in-tree cloud provider for OpenStack (and the cinder volume provider) has now been removed. Please use the external cloud provider and csi driver from https://github.com/kubernetes/cloud-provider-openstack instead.
```

### CODE REVIEW

**Comment by gnufied** [comment]
Is Cinder CSI driver has all necessary pieces to do this? Will this stop in-tree Cinder volumes from working?

**Comment by gnufied** [comment]
okay, I see this is for 1.13.. I will stop panicking now. :D

**Comment by wenjiaswe** [comment]
cc @cheftako

**Comment by dims** [comment]
will revisit this later.

**Comment by dims** [comment]
@FengyunPan2 @NickrenREN @anguslees @jingxu97 @jsafrane @msau42 @rootfs @saad-ali @hogepodge @dklyle @kubernetes/sig-openstack-misc

**Comment by derekwaynecarr** [comment]
I am in favor of moving to external cloud providers, but feel in-tree code should only be removed if it was deprecated for at least a single release so distributions can prepare appropriately.  What is timeline for the other clouds?

**Comment by dims** [comment]
@derekwaynecarr deprecation message ( https://github.com/kubernetes/kubernetes/pull/63524 ) was added in v1.11.0-beta.0, so basically v1.11 and 1.12 had notices. i believe AWS may be next (cc @d-nishi)

**Comment by derekwaynecarr** [comment]
thanks @dims

**Comment by NickrenREN** [comment]
In favor of doing this too. thanks @dims

**Comment by hogepodge** [comment]
Before merging, can we socialize this in the sig-openstack slack channel and mailing lists, as well as on the openstack-dev mailing list? I want to make sure that all parties that might have a interest in this have a chance to weigh in (even with the deprecation warning). Give it just a little bit of time and if there are no strong objections we merge earlier rather than later in the 1.13 cycle.

**Comment by hogepodge** [comment]
I've sent a notification to openstack-dev

**Comment by gnufied** [comment]
Have we finalized migration plan for in-tree Cinder volume plugin to CSI? Is Cinder CSI driver ready and on feature parity with in-tree volume plugin? afaik - CSI for example does not currently support volume resizing. Are other features covered?

**Comment by msau42** [comment]
In-tree migration to CSI is still quarters away from GA.  I don't think we can remove in-tree Cinder until that is in-tree migration is GA, otherwise we will break backwards compatibility for the cinder plugin.  cc @davidz627

**Comment by davidz627** [comment]
@gnufied and @msau42 have hit all the right points. In-tree migration to CSI is targeted for Q3 2019 GA. We can't remove the in-tree Cinder plugin as we can't break backwards compatibility for the API in Kubernetes minor versions according to [deprecation policy.](https://kubernetes.io/docs/reference/using-api/deprecation-policy/)

The most practical way of removing the in-tree cinder code is by [migrating to CSI](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/csi-migration.md) which will be a multiquarter effort that we would be happy to collaborate on with the Cinder driver.

**Comment by dims** [comment]
cc @flaper87 @j-griffith

**Comment by saad-ali** [comment]
This PR is removing support for a volume plugin that is expose in the Kubernetes API. We can not remove in-tree volume plugins, including Cinder, yet because they expose API in core v1 API group. As @davidz627 mentioned API deprecation policy applies here.

The [migration plan](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/csi-migration.md) will "proxy" the requests to the API to a CSI driver.

Please work with @davidz627 to align with the in-tree volume plugin to CSI migration plan. If the time line for that plan is not sufficient for you, @cheftako had a proposal for moving volume code out-of-tree (run an external version of each controller, disable the cloud provider on the internal version, disable everything on the external version except the cloud provider).

Happy to hop on a video chat if you'd like to discuss more in person.

**Comment by dims** [comment]
We can't entirely remove stuff .. yet

**Comment by hogepodge** [comment]
cc @adisky

**Comment by dims** [comment]
@adisky @ramineni @chrigl can you please chime in?

**Comment by dims** [comment]
cc @lingxiankong

**Comment by jsafrane** [comment]
Cinder volume plugin still needs the cloud provider and it will need it at least for few next releases. The volume plugin is being migrated to CSI, but the migration is alpha in 1.17. Is anyone actively working on the migration so it can be moved to beta at least in 1.18 and GA later? I'd suggest to migrate slowly (i.e. have beta longer than one release), because this is stuff needs to be tested really well as it can break storage of whole cluster very easily.

**Comment by adisky** [comment]
@dims CSI Migration itself is  alpha, Most probably it will go beta in v1.17, @chrigl working on Cinder Migration part, as @jsafrane said we can plan cinder migration to go beta in v1.18, then GA and then only we will be able to remove intree openstack provider.

**Comment by chrigl** [comment]
I am also afraid that we must keep the in-tree cinder-volume-code in k/k fro quite a while. Currently CSIMigration is in Phase 1 (of 4), close to land Phase 2 (#83098).

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/csi-migration

**Comment by dims** [comment]
/hold

guess 2 more releases? :)

**Comment by hogepodge** [comment]
Ugh, is there any way to separate the auth and volume bits from everything else? We've been promising this for two years already.

I also want to call out removing the code duplication on mounts that will be solved once this lands. https://github.com/kubernetes/utils/pull/100

**Comment by ramineni** [comment]
> I also want to call out removing the code duplication on mounts that will be solved once this lands. [kubernetes/utils#100](https://github.com/kubernetes/utils/pull/100)
@hogepodge But kubernetes/utils#100 PR, doesn't look like it will be merged soon . Else, we don't have option but leave duplicate code as it is.

**Comment by dims** [comment]
see https://github.com/kubernetes/cloud-provider-openstack/pull/835 for documentation that is getting added about CSI Migration

**Comment by hogepodge** [comment]
Can we please finish up this removal. I don't think that the CSI should be a limiting factor any more, given delivery has been promised for coming up on a year now.

**Comment by hogepodge** [comment]
cc @mnaser in case you're running in production

**Comment by jsafrane** [comment]
I thought the agreement was to remove cloud providers and their volume plugins in Kubernetes 1.21. Migration to Cinder CSI is only beta and you can't replace GA feature (Cinder volume plugin) with beta.

@msau42, is 1.21 recorded in any KEP?

**Comment by dims** [comment]
@jsafrane please see the date the original PR was filed Aug/2018. This has dragged on way too long :( sigh!

**Comment by dims** [comment]
@jsafrane there are no KEPs that explicitly say so. looking at https://cs.k8s.io/?q=1%5C.2(1%7C2)&i=nope&files=&repos=kubernetes/enhancements

So sig storage leads, please approve this PR for 1.19 ( cc @xing-yang @saad-ali )

**Comment by msau42** [comment]
I agree we cannot replace a GA functionality with something that is beta.

According to the [deprecation policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-feature-or-behavior), we need 1 year after deprecation before we can remove. Now it's not clear about when we can start the timer for 1 year. Can we start counting when the beta replacement is available? Or do we have to wait until the replacement is GA and then start the deprecation timer? For the other plugins, we've started the 1 year deprecation timer when their CSI migration feature has gone beta. So for openstack, csi migration went beta in 1.18, which means 1.22 for removal, assuming that csi migration for openstack goes GA sometime before that.

I understand that this particular cloud provider pkg has been deprecated for 2 years now, but the challenge here is that the volume layer is directly built into the core K8s API and that cannot be removed, hence the need for csi migration. If we want to remove the non-storage parts for now, since the other parts are not baked into the K8s api, that seems fine with me.

**Comment by xing-yang** [comment]
@dims I see that there's an issue opened to track Cinder in-tree to CSI driver migration here: https://github.com/kubernetes/enhancements/issues/1489.

The plan to remove in-tree cloud provider in k8s 1.21 has been discussed in sig-storage meetings.  I'm not sure if there's a KEP specifically mentioning that.

**Comment by xing-yang** [comment]
Michelle has a slide on CSI migration that mentioned 1.21 as the target release to remove in-tree cloud provider code:
https://static.sched.com/hosted_files/kccncna19/7b/2019-11-12%20Intro%20%2B%20Deep%20Dive_%20Kubernetes%20Storage%20SIG.pdf

**Comment by dims** [comment]
@xing-yang that enchancement issue is a left over. we already have a CI jobs that confirm that the cinder csi migration is working, please see:
https://github.com/kubernetes/kubernetes/pull/85637#issuecomment-602734721

**Comment by dims** [comment]
for the record, here's a screen shot that @xing-yang referenced:
image

**Comment by hogepodge** [comment]
@dims I've been looking over the code this weekend, and I think it's possible to remove LoadBalancer and Routes interfaces without disrupting the Cinder volume driver. Identity, Metadata, Metrics, and Volumes have to stay because of the volume driver dependence on them. It it worthwhile removing those interfaces to drive home that the only reason any of this remains is because of the deprecation and removal policies?

**Comment by dims** [comment]
@hogepodge nah. thanks for looking though. let's run the clock out

**Comment by dims** [comment]
its-been84years-its-been-a-long-time

**Comment by aojea** [comment]
Lol

**Comment by fedebongio** [comment]
Great to see this finally happening!
/remove-sig api-machinery

**Comment by thockin** [comment]
This is terrifying.  This ia massively breaking change, and I have not followed this process as closely as I would have liked, so I feel obligated to ask:

* Where/when have we talked about this and announced it previously?
* Where have we published a migration HOWTO doc?

Can we update the PR comment to reflect this?

**Comment by dims** [comment]
@thockin LOL, there's like a half a dozen keps :) updated the PR comment

**Comment by dims** [comment]
@xing-yang @msau42 if you want to add more context.

**Comment by thockin** [comment]
Mostly I just want to make sure that we set a precedent that this sort of nuclear bomb PR is self-contained enough for a poor user to find all the relevant info how to un-kill their cluster :)

/approve
/lgtm

**Comment by dims** [comment]
Also see blog that is being drafted for more context: https://github.com/kubernetes/website/pull/36183

**Pull request merged**
