### PR TITLE
migrate log in pkg/volume/csi/expander.go

### PR DESCRIPTION
**Pull request by huchengze**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Ref:

* [keps/sig-instrumentation/1602-structured-logging](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging)
* [Structured Logging migration instructions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md)

**Does this PR introduce a user-facing change?**:

```release-note
Migrate some log messages to structured logging in pkg/volume/csi/expander.go.
```

/area logging

### CODE REVIEW

**Comment by shubheksha** [comment]
@huchengze, for future PRs, could you please batch changes of at least 10-20 lines in a single PR? Makes reviewing a lot easier. 

 /priority backlog
/triage accepted

**Comment by huchengze** [comment]
@shubheksha I'm sorry I didn't take this into consideration, I will do so in the future.

**Comment by yangjunmyfm192085** [comment]
duplicated with https://github.com/kubernetes/kubernetes/pull/99527
/wg structured-logging

**Comment by humblec** [comment]
lgtm .

Cc @gnufied

**Pull request closed without merging**
