### PR TITLE
Automated cherry pick of #105122: added keys for structured logging

### PR DESCRIPTION
**Pull request by ialidzhikov**
Cherry pick of #105122 on release-1.21.

#105122: added keys for structured logging

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
/cc @xing-yang 
for `/ok-to-test`

**Comment by mattcary** [comment]
/lgtm

NB for other reviewers: the changes in pkg/proxy/healthcheck/service_health.go in the original PR don't apply to the cherry-pick because newServiceHealthServer does not have the GetNodeAddresses call in this branch yet.

**Comment by ialidzhikov** [comment]
ping @thockin 
for approval

**Pull request merged**
