### PR TITLE
Remove unused parameters and flags in Annotate command

### PR DESCRIPTION
**Pull request by hurf**
Some params and flags are set but not used, remove them.

@JanetKuo when reading the example you gave, found a small issue.

`out` and `printerFlags` are added but not used.

### CODE REVIEW

**Comment by hurf** [comment]
Also changed filenames from `annotation` to `annotate` to be consistent with other commands.

**Comment by hurf** [comment]
@JanetKuo , can you please take a look at this?

**Comment by hurf** [comment]
@k8s-bot test this please

**Comment by JanetKuo** [comment]
@k8s-bot test this please

**Comment by JanetKuo** [comment]
@hurf LGTM. Thanks!

**Comment by hurf** [comment]
@JanetKuo - Can you attach the lgtm label if it really looks good to you?

**Comment by brendandburns** [comment]
closing and re-opening to ping shippable

**Pull request merged**
