### PR TITLE
Deleting duplicate code from federated-apiserver.Run()

### PR DESCRIPTION
**Pull request by nikhiljindal**
This removes most of duplicate code from federated-apiserver.Run().
The code remaining is related to storage or authz and authn.
https://github.com/kubernetes/kubernetes/pull/24787 refactors the storage related code.
I am still figuring out authz and authn.

cc @jianhuiz

### CODE REVIEW

**Comment by nikhiljindal** [comment]
@smarterclayton Can you please take a look?
Will rebase once you have had a look (rebase should be trivial)

**Comment by smarterclayton** [comment]
Looks ok to me, just code movement and duplication?

**Comment by nikhiljindal** [comment]
Yes! Moving common code to genericapiserver and deleting the duplication from kube-apiserver and federation-apiserver.

**Comment by nikhiljindal** [comment]
Rebased

**Pull request merged**
