### PR TITLE
Automated cherry pick of #11397

### PR DESCRIPTION
**Pull request by nikhiljindal**
Cherrypicking fix for: https://github.com/GoogleCloudPlatform/kubernetes/issues/11377

Original PR:
"Updating kubectl expose to leave service port unnamed"

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @bgrant0607 @zmerlynn

**Comment by zmerlynn** [comment]
Cross-link #11397

**Comment by zmerlynn** [comment]
LGTM

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
