### PR TITLE
Mark HPA REST Clients Flag as Deprecated

### PR DESCRIPTION
**Pull request by DirectXMan12**
This marks the option to switch to Heapster for the HPA as deprecated.
It'll be removed next release when Heapster is retired.

**Release note**:

```release-note
Using the Horizontal Pod Autoscaler with metrics from Heapster is now deprecated.
```

### CODE REVIEW

**Comment by DirectXMan12** [comment]
cc @kubernetes/sig-autoscaling-pr-reviews 

/milestone v1.12

**Comment by DirectXMan12** [comment]
I realized that despite talking about and announcing this, we hand officially marked it in the code.  This fixes that omission.

**Comment by MaciekPytel** [comment]
Nice catch!
/lgtm

**Comment by DirectXMan12** [comment]
rebased.  someone with appropriate powers that's not offline monday, PTAL.

**Comment by DirectXMan12** [comment]
@deads2k or someone else, PTAL

**Pull request merged**
