### PR TITLE
sync serverside apply w/ master

### PR DESCRIPTION
**Pull request by apelisse**
Merges master into feature-serverside-apply

### CODE REVIEW

**Comment by lavalamp** [comment]
Hm, is there a commit that shows what you did to resolve conflicts?

**Comment by apelisse** [comment]
> Hm, is there a commit that shows what you did to resolve conflicts?

No, you can `git diff` the merge commit, but even that doesn't give you a good picture of how I fixed the conflict :-/

**Comment by timothysc** [comment]
Holy Cow, 250 commits and 1400 files and just a blanket approve... 
For the good of the project, no!  

/hold   

/cc @kubernetes/steering-committee

**Comment by apelisse** [comment]
This is targeting a feature branch, not master. And is actually a sync/merge of master into the feature branch. There is only on commit I authored here, which is the merge commit.

But yeah, I agree that it looks scary ;-)

**Comment by lavalamp** [comment]
@timothysc thanks for the vigilance but look at the branch :)

/hold cancel

@apelisse can you investigate and/or fix the failing tests? Hopefully it's not serious.

**Comment by apelisse** [comment]
Of course, it also looks like I have to run `update-staging`. I'm working on it.

**Comment by lavalamp** [comment]
Awesome, remaining breakage is broken on head, too.

**Pull request merged**
