### PR TITLE
KEP-4033: fulfill beta criteria

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind feature
#### What this PR does / why we need it:
bump the feature gate to beta, and remove fallback, as described in the KEP
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Promoted CRI communication of cgroup driver mechanism, to beta.
The `KubeletCgroupDriverFromCRI` feature gate is now beta and enabled by default. This means that the kubelet queries the container runtime using CRI to discover the mechanism for cgroup management that the kubelet will use; if the container runtime doesn't support this, the kubelet falls back to loading this from its configuration file (you can also use the deprecated `--cgroup-driver` command line argument).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/4033-group-driver-detection-over-cri/README.md
```

### CODE REVIEW

**Comment by haircommander** [comment]
hm it seems containerd 2.0 isn't prevelant enough to do the [second commit](https://github.com/kubernetes/kubernetes/pull/125828/commits/68902b4b487b0c6e9623039890d7958e4777bed1) https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/125828/pull-kubernetes-node-e2e-containerd/1807858650790760448/artifacts/tmp-node-e2e-036c16d4-ubuntu-gke-2204-1-29-v20240627/kubelet.log 
@mikebrow do you think there's a chance to backport RuntimeStatus to 1.7 or is that not possible?

**Comment by ffromani** [comment]
/triage accepted
/priority important-soon

AFAIR we want this work in 1.31, setting priority accordingly

**Comment by haircommander** [comment]
I think we're not ready to remove the fallback, maybe we should retarget that to GA

**Comment by mrunalp** [comment]
@haircommander Can we update the user facing change note if we aren't dropping the fallback?

**Comment by haircommander** [comment]
good point, updated

**Review by mrunalp — APPROVED** [review]
/lgtm

**Comment by sftim** [comment]
Changelog suggestion
```diff
-Bump the KubeletCgroupDriverFromCRI feature gate to beta and true by default. The kubelet will continue to use its KubeletConfiguration field as a fallback if the CRI implementation doesn't support this feature. 
+Promoted CRI communication of cgroup driver mechanism, to beta.
+The `KubeletCgroupDriverFromCRI` feature gate is now beta and enabled by default. This means that the kubelet
+querie the container runtime using CRI to discover the mechanism for cgroup management that the kubelet
+will use; if the container runtime doesn't support this, the kubelet falls back to loading this from its configuration
+file (you can also use the deprecated `--cgroup-driver` command line argument).
```

**Comment by sftim** [comment]
Also, make sure to update https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/; the text
> In Kubernetes v1.28, you can enable automatic detection of the cgroup driver as an alpha feature. See [systemd cgroup driver](https://kubernetes.io/docs/setup/production-environment/container-runtimes/#systemd-cgroup-driver) for more details.

has become stale.

**Pull request merged**
