### PR TITLE
fix: check disk status before delete azure disk

### LINKED ISSUE #88368: check disk status before delete azure disk
**What happened**:
check disk status before disk azure disk
There is little possibility that attach disk would cost 10min, and disk could be attached, deleted in same time, that would cause race condition.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/kind bug
/assign
/priority important-soon
/sig cloud-provider
/area provider/azure

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
check disk status before disk azure disk
There is little possibility that attach disk would cost 10min, and disk could be attached, deleted in same time, that would cause race condition.

**Which issue(s) this PR fixes**:

Fixes #88368

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix: check disk status before delete azure disk
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/kind bug
/assign @feiskyer 
/priority important-soon
/sig cloud-provider
/area provider/azure

cc @MSSedusch

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve
/retest

**Comment by andyzhangx** [comment]
cc @MSSedusch do you also want this fix? PR(https://github.com/kubernetes/kubernetes/pull/88444) should fix that issue, while if we merge this PR it may help in some corner case.

**Comment by MSSedusch** [comment]
@andyzhangx in case of
```
disk.ManagedBy != nil
```
would this trigger a backoff ? 
Although it does not fix the issue I had, I think this PR would reduce the number of failed Delete attempts so worth merging IMHO.

**Comment by andyzhangx** [comment]
> @andyzhangx in case of
> 
> ```
> disk.ManagedBy != nil
> ```
> 
> would this trigger a backoff ?
> Although it does not fix the issue I had, I think this PR would reduce the number of failed Delete attempts so worth merging IMHO.

if it's `disk.ManagedBy != nil`, then will return error, k8s volume controller will trigger delete volume again, that's controlled by k8s, from azure driver side, there is no backoff.

**Pull request merged**
