### PR TITLE
Fix typo in types.go

### PR DESCRIPTION
**Pull request by eltociear**
**What type of PR is this?**

fix

**What this PR does / why we need it**:

Fixed minor typo.
`assigment `-> `assignment`

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/triage accepted
/ok-to-test
/kind cleanup

**Comment by eltociear** [comment]
`/retest`

**Comment by dims** [comment]
/assign @liggitt 

NOTE: one tiny typo assigment -> assignment

**Comment by liggitt** [comment]
thanks for the PR, this was already fixed in https://github.com/kubernetes/kubernetes/commit/d7768519ee7cb1973a7ac3a923937780703c95e8

**Pull request closed without merging**
