### PR TITLE
Fix patch secret value inconsistency

### LINKED ISSUE #118588: Metadata of immutable secrets cannot be changed when the `.data` has a key with empty value
### What happened?

I have created the following secret in my cluster.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test
immutable: true
data:
  "foo": ""
  "one": dHdvCg==
```

When I add labels to my secret and try to apply it in the cluster I get the following error 
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test
  labels:
    "foo": "bar"
immutable: true
data:
  "foo": ""
  "one": dHdvCg==

```

```bash
$ k apply -f secret.yaml
The Secret "test" is invalid: data: Forbidden: field is immutable when `immutable` is set
```

This also happens when I use `kubectl edit` or using the `controller-runtime` go client.

Not sure why, but `kubectl label` works.
```bash
$ k label secret test foo=bar
secret/test labeled
```

### What did you expect to happen?

I expect that the secret can be updated with the new labels since the `data` is not actually changed.

### How can we reproduce it (as minimally and precisely as possible)?

Steps explained above.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-30T06:34:50Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by HirazawaUi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
If the value of map in data is "", it will be rejected when updating the secret

#### Which issue(s) this PR fixes:

Fixes #118588

#### Special notes for your reviewer:
When the api-server stores the Sercet, it will initialize the empty value byte slice, when updating the Sercet, we will convert a []byte of length 0 in Sercet to nil，and the value obtained from the apiserver do not match, and the update will be rejected

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by thockin** [comment]
Where is this done during CREATE?  I don't think this should be done in the validation logic, I think it probably needs to go into strategy (pkg/registry/core/secret/strategy.go) or maybe conversion (pkg/apis/core/v1/conversion.go) but I'd like to full understand it to be sure.

**Comment by HirazawaUi** [comment]
> Where is this done during CREATE? I don't think this should be done in the validation logic, I think it probably needs to go into strategy (pkg/registry/core/secret/strategy.go) or maybe conversion (pkg/apis/core/v1/conversion.go) but I'd like to full understand it to be sure.

During the creation of the Sercet, we will here (https://github.com/kubernetes/kubernetes/blob/604584d1d3cc230948498040281b2862f789c7c3/staging/src/k8s.io/ apiserver/pkg/endpoints/handlers/create.go#L126) to convert the provided data into YAML or JSON, which initializes the []byte of length 0 in the map value

When we update Sercet, we will use (https://github.com/kubernetes/kubernetes/blob/604584d1d3cc230948498040281b2862f789c7c3/staging/src/k8s.io/ apiserver/pkg/endpoints/handlers/patch.go#L509) to create `objToUpdate`, we will pass `func applyPatchToObject() `-> `func (c *unstructuredConverter) FromUnstructuredWithValidation` -> `func fromUnstructured() `eventually creates `objToUpdate`, but in (https://github.com/kubernetes/kubernetes/blob/ 604584d1d3cc230948498040281b2862f789c7c3/staging/src/k8s.io/apimachinery/pkg/runtime/converter.go#L449) will set the []byte of length 0 to nil, so there is a The value of map is inconsistent during update

I agree with you that this change should not be done in the validation logic

But I am afraid to change the logic of `func fromUnstructured()`, because the result of its change may be uncontrollable, so I suggest to change it in `pkg/apis/core/v1/conversion.go`, what do you think?

**Comment by thockin** [comment]
@jpbetz @deads2k @apelisse - you all know this area better than I do. In the past we've been hit by places which tried to intentionally make `[]` and `nil` mean different things.  I think we have mostly weeded that out.  This is different in some ways but similar.  We seem to be inconsistent about decoding empty slices.  Should we assert that they always decode one way?  Or should we find all the places that compare them and handle semantic equiv of `nil` and `[]`?

In this case, `k8s.io/apimachinery/pkg/api/validation.ValidateImmutableField` *does* call `apiequality.Semantic.DeepEqual()` so it's not even clear to me why it fails.

**Comment by thockin** [comment]
Also `kubectl replace` works, `apply` does not:

```
$ k delete secret test
Error from server (NotFound): secrets "test" not found

$ k create -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: test
immutable: true
data:
  "foo": ""
  "one": dHdvCg==
EOF
secret/test created

$ k get secret -o yaml
apiVersion: v1
items:
- apiVersion: v1
  data:
    foo: ""
    one: dHdvCg==
  immutable: true
  kind: Secret
  metadata:
    creationTimestamp: "2023-06-20T17:02:43Z"
    name: test
    namespace: default
    resourceVersion: "28060603"
    uid: 03a7e4a2-4c05-40e6-8074-0499295a9552
  type: Opaque
kind: List
metadata:
  resourceVersion: ""

$ k replace -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: test
  labels:
    foo: bar
immutable: true
data:
  "foo": ""
  "one": dHdvCg==
EOF
secret/test replaced

$ k apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: test
  labels:
    foo: bar2
immutable: true
data:
  "foo": ""
  "one": dHdvCg==
EOF
Warning: resource secrets/test is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
The Secret "test" is invalid: data: Forbidden: field is immutable when `immutable` is set

$ k apply --server-side --force-conflicts -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: test
  labels:
    foo: bar2
immutable: true
data:
  "foo": ""
  "one": dHdvCg==
EOF
The Secret "test" is invalid: data: Forbidden: field is immutable when `immutable` is set
```

**Comment by thockin** [comment]
I was wrong, validation it calls `reflect.DeepEqual` for data.  Maybe the fix is simply calling semantic DeepEqual?

**Comment by apelisse** [comment]
I don't think empty string and not specified should be the same thing? Doesn't this significantly affect how workloads would run, there's a different for a pod that references a key that exist versus the key being empty? There's a difference between mounting an empty file vs not having the file?

**Comment by apelisse** [comment]
My concern is that somethings sees empty list and then decides to remove it, looks like this is done in the patch code, and that's why create/put/replace works?

**Comment by apelisse** [comment]
cc @sttts

**Comment by thockin** [comment]
This is why I asked you. :)

I do not have good viz into patch logic, but in this case a map value of `[]` and `nil` should be the same.  Unfortunately, it seems that the marshal/unmarshal logic is inconsistent between methods (and I bet JSON vs proto should be considered, too).

This patch passes the simplest test for this one case, but a) I have no idea if there are implications beyond this; and b) it feels sloppy and likely to arise elsewhere.

@HirazawaUi what do you think of trying CI against this patch (pluys some unit tests)?

```diff
diff --git a/pkg/apis/core/validation/validation.go b/pkg/apis/core/validation/validation.go
index 6502d9c210a..6521eedd134 100644
--- a/pkg/apis/core/validation/validation.go
+++ b/pkg/apis/core/validation/validation.go
@@ -6024,7 +6024,7 @@ func ValidateSecretUpdate(newSecret, oldSecret *core.Secret) field.ErrorList {
                if newSecret.Immutable == nil || !*newSecret.Immutable {
                        allErrs = append(allErrs, field.Forbidden(field.NewPath("immutable"), "field is immutable when `immutable` is set"))
                }
-               if !reflect.DeepEqual(newSecret.Data, oldSecret.Data) {
+               if !apiequality.Semantic.DeepEqual(newSecret.Data, oldSecret.Data) {
                        allErrs = append(allErrs, field.Forbidden(field.NewPath("data"), "field is immutable when `immutable` is set"))
                }
                // We don't validate StringData, as it was already converted back to Data
```

**Comment by HirazawaUi** [comment]
> This is why I asked you. :)
> 
> I do not have good viz into patch logic, but in this case a map value of `[]` and `nil` should be the same. Unfortunately, it seems that the marshal/unmarshal logic is inconsistent between methods (and I bet JSON vs proto should be considered, too).
> 
> This patch passes the simplest test for this one case, but a) I have no idea if there are implications beyond this; and b) it feels sloppy and likely to arise elsewhere.
> 
> @HirazawaUi what do you think of trying CI against this patch (pluys some unit tests)?
> 
> ```diff
> diff --git a/pkg/apis/core/validation/validation.go b/pkg/apis/core/validation/validation.go
> index 6502d9c210a..6521eedd134 100644
> --- a/pkg/apis/core/validation/validation.go
> +++ b/pkg/apis/core/validation/validation.go
> @@ -6024,7 +6024,7 @@ func ValidateSecretUpdate(newSecret, oldSecret *core.Secret) field.ErrorList {
>                 if newSecret.Immutable == nil || !*newSecret.Immutable {
>                         allErrs = append(allErrs, field.Forbidden(field.NewPath("immutable"), "field is immutable when `immutable` is set"))
>                 }
> -               if !reflect.DeepEqual(newSecret.Data, oldSecret.Data) {
> +               if !apiequality.Semantic.DeepEqual(newSecret.Data, oldSecret.Data) {
>                         allErrs = append(allErrs, field.Forbidden(field.NewPath("data"), "field is immutable when `immutable` is set"))
>                 }
>                 // We don't validate StringData, as it was already converted back to Data
> ```

I think it's great, I didn't know of the presence of `apiequality.Semantic.DeepEqual` before. I will make the modifications and add corresponding tests.

**Comment by thockin** [comment]
@apelisse and I were discussing some possible alternatives, too.  Will wait for him to follow up

**Comment by apelisse** [comment]
I don't know if  `""` and `null` should be equivalent, and I don't think we have to decide (it'd be nice if we do, but we don't have to decide), and so we can fix this bug without changing `reflect.DeepEqual` to `semantic.DeepEqual`.

My take on the bug is that `fromUnstructured` shouldn't transform a `""` into a `[]byte(nil)` but into a `[]byte{}`. My argument is that we should do the same thing `json.Unmarshal` does, e.g.:
```golang
var barray []byte
_ = json.Unmarshal([]byte(`""`), &barray)
fmt.Printf("%#v\n", barray)
// Output: []byte{}
```
I don't see why `fromUnstructured` would behave differently, it's almost certainly a bug. I've quickly glanced at `converter_test.go` and I can't see a test for this, which we should probably add.

cc @wojtek-t

**Comment by HirazawaUi** [comment]
> I don't see why `fromUnstructured` would behave differently, it's almost certainly a bug

If it is confirmed that this is a bug, I will make a targeted fix, and as stated before, I am concerned that there may be other places that will take advantage of this bug and use it as a feature.

**Comment by thockin** [comment]
@wojtek-t or @smarterclayton do you have any recollection of this area?  The fix here is really small, but feels like it should not be needed.

**Comment by wojtek-t** [comment]
> My take on the bug is that fromUnstructured shouldn't transform a "" into a []byte(nil) but into a []byte{}. My argument is that we should do the same thing json.Unmarshal does, e.g.:

I agree.
It was long enough ago that I can't remember it, but I certainly remember that my goal when doing that was to make it compatible (so effectively that same thing as unmarshal+marshal+unmarshal through json.

Given that (as @apelisse wrote) we don't seem to have a test for it, I agree it seems more like my bug than a conscious decision.

@HirazawaUi - would you mind helping with addressing this (in a separate commit, or even better separate PR) too?

**Comment by thockin** [comment]
If we fix this, hopefully we don't need the semantic equal (though we may
want to keep it in case)

**Comment by HirazawaUi** [comment]
> > My take on the bug is that fromUnstructured shouldn't transform a "" into a []byte(nil) but into a []byte{}. My argument is that we should do the same thing json.Unmarshal does, e.g.:
> 
> I agree. It was long enough ago that I can't remember it, but I certainly remember that my goal when doing that was to make it compatible (so effectively that same thing as unmarshal+marshal+unmarshal through json.
> 
> Given that (as @apelisse wrote) we don't seem to have a test for it, I agree it seems more like my bug than a conscious decision.
> 
> @HirazawaUi - would you mind helping with addressing this (in a separate commit, or even better separate PR) too?

Ok, I'll create a new PR to fix it

**Review by thockin — COMMENTED** [review]
Even with the serialization fix, we should keep this test case, and drop the semantic-equal (I think)

**Comment by HirazawaUi** [comment]
> Even with the serialization fix, we should keep this test case, and drop the semantic-equal (I think)

I think so, too

**Review by thockin — COMMENTED** [review]
/approve

**Comment by HirazawaUi** [comment]
We may not be able to merge this PR because `[]byte(nil)` and `[]byte{}` will not be equal when we use `reflect.DeepEqual` without `apiequality.Semantic.DeepEqual`; expectedly, this test case will fail.

It successful now because I incorrectly left out the `Secret.Immutable` in the test code,The test code will skip reflect.DeepEqual:
https://github.com/kubernetes/kubernetes/blob/da2d500c80968aacf4dfa9e32f5e6ccc06dc33c7/pkg/apis/core/validation/validation.go#L6081

**Comment by thockin** [comment]
I thought the deserializtion fixed that?

**Comment by liggitt** [comment]
> My take on the bug is that fromUnstructured shouldn't transform a "" into a []byte(nil) but into a []byte{}

What does proto serialization do? Does it lose the distinction between `[]byte(nil)` and `[]byte{}` in round-tripping? I would guess it does. If so, we may still have a problem with the server and a client disagreeing about the serialization of `""` in a manifest

**Comment by HirazawaUi** [comment]
> I thought the deserializtion fixed that?

Yes, but deserializtion won't affect this test case

**Comment by HirazawaUi** [comment]
> Ahh, right. It fixes the real bug but not the test.

Yes, as you said😂, maybe we should close this PR

**Comment by thockin** [comment]
I like this test case, though.  If we close this, we should replace it with
an e2e or integration test

**Comment by HirazawaUi** [comment]
Okay, I will to provide an e2e test for this test case.

**Pull request closed without merging**
