### PR TITLE
propose: ixdy as TLA for build related changes

### PR DESCRIPTION
**Pull request by mikedanese**

### CODE REVIEW

**Comment by thockin** [comment]
The tooling is weak for this use case.  I'm happy to approve build changes, if you just assign me so I know...

Might be interesting to have a non-recursive option in BUILD..

**Comment by mikedanese** [comment]
I'm worried about the availability and latency of the "assign everything to @thockin" approach (e.g. what happens when you go on vacation or dockercon?). These approvals have been a bottleneck for incremental improvements to the build system and they haven't added value.

**Comment by ixdy** [comment]
I agree that it'd be nice if the tooling allowed non-recursive OWNERS, but it seems like we don't have any staffing to implement those features (https://github.com/kubernetes/test-infra/issues/1782) right now.

**Comment by spxtr** [comment]
One alternative that we considered is moving the `WORKSPACE` and `Makefile`s into `build/`. This is pretty gross and non idiomatic. I don't see much value in having you (@thockin) approve every bazel PR, but if you don't mind approving them reasonably quickly then we can ask you do to so. Our current process feels like 1) open the PR, 2) within a few hours someone reviews it, 3) a day later the suggested top-level approver hasn't responded, somone pings them, 4) ask another top-level approver, 5) a day later ask you for approval, 6) a few hours later you approve.

**Comment by fejta** [comment]
We need at least one person -- meaning @spxtr @ixdy @mikedanese -- working on the bazel stuff to have approval rights for these PRs.

**Comment by thockin** [comment]
I'm fine to add A couple people to OWNERS with a comment that it's for
build stuff.  It means that any PR they send will be auto-approved, so they
need extra caution.

This PR adds a comment - why not a real entry?

**Comment by spxtr** [comment]
If we add it as a real entry then @ixdy will be recommended as an approver for lots of PRs that he doesn't want to approve.

**Comment by thockin** [comment]
and if we don't then this technique will not work for people who don't
already have commit access...

**Comment by fejta** [comment]
Should we close this or??

**Comment by mikedanese** [comment]
I sent out https://github.com/kubernetes/kubernetes/pull/45855 as an alternative to this and still waiting for it to be discussed.

**Pull request closed without merging**
