### PR TITLE
Revert "All e2e tests should use NewFramework"

### PR DESCRIPTION
**Pull request by jszczepkowski**
Reverts kubernetes/kubernetes#16084.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
This PR broke kubernetes-e2e-gce:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9143/

The following test cases were failing:
**DaemonRestart Kubelet should not restart containers across restart**
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_restart.go:250
Test Panicked

**DaemonRestart Scheduler should continue assigning pods to nodes across restart**
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/daemon_restart.go:250
Test Panicked

**Comment by gmarek** [comment]
LGTM

**Comment by jszczepkowski** [comment]
CC @smarterclayton

**Comment by smarterclayton** [comment]
Is there a way for someone who doesn't work at google to trigger a full GCE run when changing e2e tests?  To ensure their e2e changes work in remotely and locally?

**Comment by gmarek** [comment]
cc @ixdy @lavalamp - you can certainly start a cluster and run tests on it yourself. AFAIU we're not running full e2e suite on each PR, as some tests are taking too long or are flaky.

**Comment by smarterclayton** [comment]
Right, but should we be requiring a full e2e Jenkins run before we merge
things that themselves change the e2es?  I would think yes

**Comment by gmarek** [comment]
I can agree with that. I don't thing we're doing it now though. Let's wait for @lavalamp or @ixdy to wake up.

**Comment by wojtek-t** [comment]
@smarterclayton I don't fully agree with that. The problem is that other code changes may also affect tests that are not running as part of parallel e2e. So how changing tests themself is different from changing the code they are implicitly running?
I completely agree that ideally we should run all tests on every PR. But unfortunately this isn't doable, because it will take too long. So we decided to run those that are relatively fast and can be run in parallel, and just monitor other tests (this is the task of merge bot) after merging PR.

**Comment by smarterclayton** [comment]
Well, to make it easier for someone doing a review of broad e2e changes to
ensure that the specific e2e changes didn't break the full suite.  We have
limited access to GCE sizes in our environment, and so a full e2e suite run
takes multiple hours hours and limits other parallel work going on. Having
a way to do a full run to review someone's changes and have confidence that
they'll work would be desirable.

**Comment by wojtek-t** [comment]
@smarterclayton 
Sure - I definitely agree that having that possibility would be beneficial.
However, I'm wondering how does "e2e changes" differ from "code changes" and why we should run tests on the former and not on the latter.

**Comment by smarterclayton** [comment]
A non-trivial amount of PRs change things for which a full e2e run is
likely required.  Some of those are refactors to e2e tests themselves,
others are just large system changes.  Being able to schedule the
occasionally full e2e run directly from a PR makes all reviewers more
productive by reducing the number of reverts.

**Comment by wojtek-t** [comment]
This one I completely agree with. [Just wanted to clarify that those changes doesn't have to be test changes]. Thanks!

**Comment by lavalamp** [comment]
Unfortunately there's like a dozen separate jenkins projects, so it's not so easy to run everything. @ixdy, any ideas?

**Comment by ixdy** [comment]
We could probably add a build on the pull request Jenkins to run everything in `kubernetes-e2e-gce`. This skips a lot of tests (flaky tests, slow tests, and everything in the "default skip" list - autoscaling, restart tests, reboot tests, example tests, density/performance, and load balancer tests.)

It'd give us a bit more data than just the regular parallel runs, but it's still possible you'd break one of the other tests.

We could have a mondo-build which really runs all of the tests, but I worry that it would be so flaky as to be unhelpful.

**Comment by lavalamp** [comment]
@ixdy what about a mondo-build, but skipping flaky?

**Comment by ixdy** [comment]
Well, how long are we willing to wait for test results?

Some timing information:
`kubernetes-e2e-gce` takes ~1h35m
`kubernetes-e2e-gce-autoscaling` takes ~2h
`kubernetes-e2e-gce-examples` takes ~45m
`kubernetes-e2e-gce-reboot` takes ~30m
`kubernetes-e2e-gce-scalability` takes ~2h30m, but also requires a lot of compute resource
`kubernetes-e2e-gce-slow` takes ~2h40m

**Comment by smarterclayton** [comment]
Yikes.

**Pull request merged**
