### PR TITLE
Order suggested FlowSchemas by matching precedence

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This PR just moves some FlowSchema definitions around in `apiserver/pkg/apis/flowcontrol/bootstrap/default.go`, so that they are ordered by increasing matching precedence.  That makes it easier to imagine their interactions while reading the source file.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-misc 
/cc @wojtek-t 
/cc @tkashem 
/cc @deads2k 
@liggitt 
@lavalamp

**Comment by liggitt** [comment]
is interruption of the git history worth the reordering? (maybe so, I just thought I'd ask)

**Comment by wojtek-t** [comment]
> is interruption of the git history worth the reordering? (maybe so, I just thought I'd ask)

I don't have strong opinion - I'm fine either way.

**Comment by liggitt** [comment]
> I don't have strong opinion - I'm fine either way.

sounds good. @wojtek-t, can you review and I'll tag once this has lgtm

**Pull request merged**
