### PR TITLE
Stabilize local-up-cluster in our CI

### PR DESCRIPTION
**Pull request by dims**
#### What type of PR is this?
/cleanup

- if binaries are already present skip building them
- install missing packages like nftables and kmod
- work better when cgroups v2 is present
- update to newer CNI version (v1.2.0)
- Ensure we wait for coredns to stabilize
- Grab docker log as well (this has containerd logs too)

Used tips from:
- https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

Tested locally in an environment as close to CI as possible:
- https://gist.github.com/dims/3c83730c99f61e36b8dd2d61abe68fe7

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
any suspicious on what is broken?

**Comment by dims** [comment]
@aojea right now poking at coredns flapping about and not being ready (in CI environment)

**Comment by aojea** [comment]
> @aojea right now poking at coredns flapping about and not being ready (in CI environment)

It may fail if fail.to connect to the upstream server

**Comment by dims** [comment]
> It may fail if fail.to connect to the upstream server

gotcha, trying to collect enough logs to see where the problem could be. ( also "works on my box"™️ )

**Comment by dims** [comment]
NOTE: `coredns` is still flapping, just want to land these and then iterate again!

**Comment by dims** [comment]
/skip

thanks @ameukam

**Pull request merged**
