### PR TITLE
insert space after the comment character

### PR DESCRIPTION
**Pull request by nagarjung**

### CODE REVIEW

**Comment by nagarjung** [comment]
I signed it!

**Comment by quinton-hoole** [comment]
@nagarjung this changes 2900 files.  Is that intentional?

**Comment by nagarjung** [comment]
@quinton-hoole : This finds places in the code where we have "//comments" and "//    comments"  like this` instead of "// comments like this". This changes all the go files where there is an improper spacing after a comment character and places a single space after a comment character which is golang conventions in kube.

**Comment by nagarjung** [comment]
@quinton-hoole : As this is my first pull request, one check errored and one failed, can I know more about the issue and how to proceed further.

**Comment by quinton-hoole** [comment]
Thanks for your contribution @nagarjung

1. We should not be reformatting the code of the projects we depend upon (i.e. godeps).
2. Empty line comments (i.e. '//\n') should not be replaced by one space comments (i.e. '// \n')

Please fix the above, and do a self-review of the changed code in the PR to make sure that it makes sense before resubmitting.

Thanks!

**Comment by nagarjung** [comment]
@quinton-hoole : I have pushed the changes mentioned above. But CI build is failing, how do I take action against it.

**Comment by nagarjung** [comment]
I signed it!

**Comment by jayunit100** [comment]
We should be doing this, but possibly do this in increments ?  

- wow, 2900 is alot of changes.  It will be impossible to do without rebasing very rapidly.    Definetely needs to be a smaller patch to get through review.
- Some of these changes are erroneous http://www.apache.org/licenses/LICENSE-2.0.
- Maybe start with the `cmd` package, for example.  Or find a file where there are many of these, and fix them all manually.

**Comment by quinton-hoole** [comment]
@nagarjung I tend to agree with @jayunit100.  In fact I think that the amount of effort invested in trying to get this PR sane enough to merge has already exceeded the relatively minor value of having the right number of spaces in our comments.  I'm going to close this PR on that basis.  Re-open if anyone disagrees.

**Pull request closed without merging**
