### PR TITLE
add GRS, RAGRS storage account type support for azure disk

### LINKED ISSUE #55774: Azure disk: storage class should support the sku if the storage accout support it
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Now for storage class only support skuName with Premium_LRS and Standard_LRS
Met error if the storage account was created with other sku. But actually it can work well without setting it

**What you expected to happen**:
skuName should support others if the storage account support it

**How to reproduce it (as minimally and precisely as possible)**:
Create a storage account which is using Standard_RAGRS sku. Create storage class as below:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: scazure
parameters:
  location: eastus
  skuName: Standard_RAGRS
  storageAccount: storage
provisioner: kubernetes.io/azure-disk
```
Create pvc as below
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: scazure
  name: azpvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
PVC would never bind with below error:
Failed to provision volume with StorageClass "scazure": azureDisk - Standard_RAGRS is not supported sku/storageaccounttype. Supported values are [Premium_LRS Standard_LRS]

But if I remove the skuName parameter, the pvc could be bound 
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: scazure
parameters:
  location: eastus
  storageAccount: storage
provisioner: kubernetes.io/azure-disk
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6+a08f5eeb62", GitCommit:"c84beff", GitTreeState:"clean", BuildDate:"2017-11-12T02:22:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.6+a08f5eeb62", GitCommit:"c84beff", GitTreeState:"clean", BuildDate:"2017-11-12T02:22:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):  RHEL7
- Install tools: ansible

### PR DESCRIPTION
**Pull request by andyzhangx**
**What this PR does / why we need it**:
add Standard_GRS, Standard_RAGRS storage account type support for azure disk, and Standard_ZRS, Premium_GRS are not supported for azure disk now

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #55774

**Special notes for your reviewer**:

**Release note**:

```
Add Standard_GRS, Standard_RAGRS support for azure disk
```
/sig azure
@rootfs @brendanburns

### CODE REVIEW

**Comment by jsafrane** [comment]
@colemickens, can you please add more azure-aware people to OWNERS as reviewers? I've no clue what  GRS means.

**Comment by colemickens** [comment]
(Brendan's username has the `d` in the middle)

cc: @jdumars @seanknox @brendandburns @jackfrancis Not sure who is doing upstream work right now. Can whoever is go ahead and place themselves in the OWNERS file?

As FYI: "GRS" is "Geographically redundant storage". Azure Storage has different SKUs with different replication attributes, etc.

**Comment by andyzhangx** [comment]
Thx, I will put my name in the azure reviewer list.

**Pull request merged**
