### PR TITLE
pkg/util/iptables: use buf.String() instead of string(buf.Bytes())

### PR DESCRIPTION
**Pull request by tmilox**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

When dealing with `*bytes.Buffer`, use `buf.String()` instead of `string(buf.Bytes())`

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by danwinship** [comment]
hm... ok... but actually, can you fix the uses in `pkg/proxy/ipvs/proxier_test.go` and `pkg/proxy/util/utils_test.go` too?

**Comment by TommyStarK** [comment]
> hm... ok... but actually, can you fix the uses in `pkg/proxy/ipvs/proxier_test.go` and `pkg/proxy/util/utils_test.go` too?

sure thing @danwinship, done in 2959e60a82a

**Pull request merged**
