### PR TITLE
Optimize: empty slice return nil and gofmt imports

### PR DESCRIPTION
**Pull request by demoManito**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
empty slice return nil and gofmt imports
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
Did you profile this or is this just cosmetic? If cosmetic, I would really prefer not to change it without a really good reason.

**Comment by demoManito** [comment]
> Did you profile this or is this just cosmetic? If cosmetic, I would really prefer not to change it without a really good reason.
It is not necessary to modify the content. I closed pr

**Comment by demoManito** [comment]
> Did you profile this or is this just cosmetic? If cosmetic, I would really prefer not to change it without a really good reason.

It is not necessary to modify the content. I closed pr

**Pull request closed without merging**
