### PR TITLE
Have a uniform format for filenames across controllers

### PR DESCRIPTION
**Pull request by dhilipkumars**
**What this PR does / why we need it**:
Bring in uniformity in filename format across all the controllers.  Now controllers are of the format 
`<controllerName>_controller.go` 
From 
```
./pkg/controller/node/nodecontroller.go
./pkg/controller/route/routecontroller.go
./pkg/controller/service/servicecontroller.go
./pkg/controller/cloud/nodecontroller.go
./pkg/controller/ttl/ttlcontroller.go
./pkg/controller/job/jobcontroller.go
./pkg/controller/daemon/daemoncontroller.go
```
TO
```
./pkg/controller/node/node_controller.go
./pkg/controller/route/route_controller.go
./pkg/controller/service/service_controller.go
./pkg/controller/cloud/node_controller.go
./pkg/controller/ttl/ttl_controller.go
./pkg/controller/job/job_controller.go
./pkg/controller/daemon/daemon_controller.go
```

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```
None
```

### CODE REVIEW

**Comment by dhilipkumars** [comment]
@janetkuo , @MrHohn if the PR is reasonable could you please /ok-to-test this PR ?

**Comment by MrHohn** [comment]
Yep make sense to me

/ok-to-test

**Review by MrHohn — APPROVED** [review]

**Comment by deads2k** [comment]
I have no strong opinion.

@kubernetes/sig-apps-misc

**Comment by smarterclayton** [comment]
Proposed sounds fine to me

**Comment by dhilipkumars** [comment]
@smarterclayton/ @deads2k  could you `lgtm` and `approve no-issue` please? this branch tends to require re-base often.  

Please note it was already `lgtm`ed by when the bot removed it as i rebased it.

**Comment by dhilipkumars** [comment]
Thanks @kow3ns for `lgtm`, the branch has againg needs, re-basing.  :-(

@deads2k  could you `lgtm` and `approve no-issue` please?

**Comment by dhilipkumars** [comment]
Flake: https://github.com/kubernetes/kubernetes/issues/49761

**Review by kow3ns — APPROVED** [review]

**Pull request merged**
