### PR TITLE
Return 400 on invalid patch requests

### LINKED ISSUE #79210: Invalid patch body can result internal-server error in the server
/kind bug
/sig api-machinery
/cc @jennybuckley @apelisse 

**What happened**:

patching (SMP) any object's annotation using invalid patch content will result in an (500) internal-server error. expecting a (400) bad-request error in this case.

patch body:
```json
{"metadata":{"annotations":{"foo":["bar"]}}}
```

received error:

```json
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"unrecognized type: string","code":500}
```

the error is thrown from converter instead of the patcher, so it seems that patcher considers the body as valid then the converter complained.

**Anything else we need to know?**:

when my grandpa was 65 years old he started running one mile a day to keep fit. he's 70 now and we have no idea where he is.

### PR DESCRIPTION
**Pull request by apelisse**
**What type of PR is this?**
/kind bug

**Which issue(s) this PR fixes**:
Fixes #79210

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by apelisse** [comment]
cc @jennybuckley @yue9944882

**Comment by jennybuckley** [comment]
Not 422?

**Comment by apelisse** [comment]
I don't know if we have enough information to make that decision? Probably though ...

**Comment by yue9944882** [comment]
> The 422 (Unprocessable Entity) status code means the server understands the content type of the request entity (hence a 415(Unsupported Media Type) status code is inappropriate), and the syntax of the request entity is correct (thus a 400 (Bad Request) status code is inappropriate) but was unable to process the contained instructions.

yes, 422 sounds better i guess. also, it aligns w/ the existing 422 status from json-patch https://github.com/kubernetes/kubernetes/issues/79210#issuecomment-504112926.

**Review by yue9944882 — APPROVED** [review]
thanks @apelisse LGTM

**Comment by apelisse** [comment]
/retest

Please don't fail I don't want to debug this ... :-)

**Pull request merged**
