### PR TITLE
Automated cherry pick of #67288: Immediate close the other half of the connection when

### PR DESCRIPTION
**Pull request by tossmilestone**
Cherry pick of #67288 on release-1.11.

#67288: Immediate close the other half of the connection when

**Release note**:
```release-note
Immediately close the other side of the connection when proxying.
```

### CODE REVIEW

**Comment by foxish** [comment]
@tossmilestone, this needs lgtm and approval.

**Comment by MHBauer** [comment]
@foxish is the patch release manager and is already assigned. 
If the release note needs changing, does editing it in the original PR update all PRs or does it require each PR owner to update separately?

**Comment by MHBauer** [comment]
@foxish This isn't a user facing change. There should be nothing different. It changes how server components interact with each other.

**Pull request merged**
