### PR TITLE
delete useless code

### PR DESCRIPTION
**Pull request by twilight0620**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
It seems these two methods never been used.

#### Which issue(s) this PR fixes:
It seems these two methods never been used. so i delete them.

#### Does this PR introduce a user-facing change?
<!--

```NONE

```

### CODE REVIEW

**Review by MadhavJivrajani — COMMENTED** [review]
I'm not sure we can delete these, while they aren't used within the Kubernetes code base, there are other repos that make use of it, such as:

https://github.com/kubernetes-sigs/work-api/blob/586d707fdb2cdbdc0a98b3b5ee3dfbc5ca51cef0/pkg/controllers/apply_controller_test.go#L108

and

https://github.com/kubernetes-sigs/work-api/blob/586d707fdb2cdbdc0a98b3b5ee3dfbc5ca51cef0/pkg/controllers/apply_controller.go#L331

Apart from this, there are external repos that use them: https://grep.app/search?q=IsStatusConditionTrue
and possibly private repos as well.

**Comment by twilight0620** [comment]
> I'm not sure we can delete these, while they aren't used within the Kubernetes code base, there are other repos that make use of it, such as:
> 
> https://github.com/kubernetes-sigs/work-api/blob/586d707fdb2cdbdc0a98b3b5ee3dfbc5ca51cef0/pkg/controllers/apply_controller_test.go#L108
> 
> and
> 
> https://github.com/kubernetes-sigs/work-api/blob/586d707fdb2cdbdc0a98b3b5ee3dfbc5ca51cef0/pkg/controllers/apply_controller.go#L331
> 
> Apart from this, there are external repos that use them: https://grep.app/search?q=IsStatusConditionTrue and possibly private repos as well.

ok  i will close it,

**Pull request closed without merging**
