### PR TITLE
Automated cherry pick of #32413

### PR DESCRIPTION
**Pull request by freehan**
Cherry pick of #32413 on release-1.4.

cc: @thockin 

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32418)

### CODE REVIEW

**Comment by pwittrock** [comment]
Should we do this as part of a batch cherry pick?

**Comment by bprashanth** [comment]
I thought that was the plan, there're a couple more prs that need 1.4 cherrypicking if we're not batching  (https://github.com/kubernetes/kubernetes/pull/31990, https://github.com/kubernetes/kubernetes/pull/31828)

**Comment by pwittrock** [comment]
@bprashanth SGTM.  We don't need this then right, and just apply the label to #32413 .

**Comment by foxish** [comment]
Closing this as we're batching.

**Pull request closed without merging**
