### PR TITLE
Isolate pkg/kubectl/cmd tests from json files used in examples

### PR DESCRIPTION
**Pull request by rsokolowski**
I've created new directory under test/api-resources for test API resources (pod, replication controller, service) and used them in pkg/kubectl/cmd.

### CODE REVIEW

**Comment by cjcullen** [comment]
@smarterclayton

**Comment by smarterclayton** [comment]
Lgtm

**Comment by thockin** [comment]
Is there a real win to this?  It becomes yet another set of JSON files to keep up to date, but now they are detached from any test that actually runs them.  The guestbook and other examples are run as part of e2e.

**Comment by smarterclayton** [comment]
I retract my LGTM ;)

----- Original Message -----

**Comment by rsokolowski** [comment]
Tim, I don't have enough insight to answer your question, but it seems like
a generally good practice to separate an isolated test (create_test.go in
this case and others) from an example in order to reduce overhead while
changing the example. This is in particular useful for cases like
https://github.com/GoogleCloudPlatform/kubernetes/issues/1603

2015-02-05 13:25 GMT-08:00 Tim Hockin <notifications@github.com>:

**Comment by thockin** [comment]
I ACK that as examples change tests like this will be impacted, but we have had a lot of issues with bits of JSON scattered around the codebase that are stale or incomplete or otherwise invalid.

I'd rather depend on verified-valid JSON files and deal with fallout from those changing. 

I'm going to loop in some of the test-focused folks for a consult.

@zmerlynn @filbranden @satnam6502

**Comment by zmerlynn** [comment]
One problem with this PR is that these files actually have to be added to
KUBE_TEST_PORTABLE in hack/lib/golang.sh in order to end up in
kubernetes-test.tgz, otherwise it will break our Jenkins binary testing
method. Right now the examples end up in the binary distribution, but these
files wouldn't. However, I do have an open issue about possibly splitting
examples and test assets up so that the test.tgz could stand on its own, so
maaayyybeee....

**Comment by thockin** [comment]
I fall on the side of "not worth it" but I defer to @zmerlynn

**Comment by zmerlynn** [comment]
Skip it, then. We'll figure out a place for these later.

**Comment by ddysher** [comment]
I partially proposed the changes in #4144.  My intention is not just to have another set of JSON files to test against, but most importantly, to make k8s easier for our users, i.e. to have working json files that users can easily copy/paste for their own use.

I'm part-time on k8s, I have to stop and experience new features in k8s.  It's a bit painful to craft the json file to be honest, and I've seen similar complains from google groups.  The problem is due to the lack of powerful visualization / ops tools, but even we do, I could image the use case from cli.

Now that we have swagger ui, I hope the situation will be better.  If not, I still feel like we need to have something like examples/api-resources, create one skeleton file for each resources, and extend the skeleton file with different feature set of that resource.  This is easy to maintain as we basically have only one file per resource.

**Comment by satnam6502** [comment]
Thanks for all the great work. I think, when possible, it is preferable in tests to specify pods in Go using regular data structures and the Go client library and that is what I've done in the tests I have written because I worry about tests becoming out of sync with JSON/YAML files in random places. The pod specifications etc. are subject to type checking etc. during compilation that is not applicable to the JSON/YAML files.

**Comment by thockin** [comment]
The counter argument (not sure I think it is solid) is that things like
defaults only apply on coversion from versioned to internal, which leaves a
lot of tests specifying default values for go-defined structs that have
nothing to do with the test, but which are required for other stuff to not
crash...

**Comment by rsokolowski** [comment]
@satnam6502 , the same argumentation against test only resources that @thockin used seems to apply regardless of the language used to express resources (whether it is in Go or JSON/YAML).

**Comment by ddysher** [comment]
I don't understand the counterargument, like @rsokolowski said, we need the default value for conversion anyway, why does it make a difference?  I thought the reason for having JSON/YAML is to test client marshal, and elsewhere, we should use Go.

**Comment by zmerlynn** [comment]
The kubectl test will continue to use the files, so we'll need the assets
there (and we'll get marshalling tests there). Otherwise we should just
stay Go pure.

**Pull request closed without merging**
