### PR TITLE
fix bad return error text

### PR DESCRIPTION
**Pull request by stewart-yu**
**What this PR does / why we need it**:
fix bad return error text

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by luxas — CHANGES_REQUESTED** [review]
Thanks for this PR @stewart-yu! Happy to see you want to contribute to kubeadm!

This is actually working as intended, see the comment right before: `This is a non-critical error; continue although kubeadm couldn't look this up`

That means we _should not_ return the error in this case. So remove that change please.

**Comment by stewart-yu** [comment]
Thanks,  revert that change. @luxas

**Review by luxas — APPROVED** [review]
/lgtm
/approve no-issue

**Pull request merged**
