### PR TITLE
Move events command to top level

### PR DESCRIPTION
**Pull request by soltysh**
#### What type of PR is this?
/kind feature
/sig cli

#### What this PR does / why we need it:
This moves `kubectl alpha events` to `kubectl events` as part of beta promotion. 

#### Special notes for your reviewer:
/assign @ardaguclu 

#### Does this PR introduce a user-facing change?
```release-note
Promote kubectl alpha events to kubectl events
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/1440
```

### CODE REVIEW

**Comment by leonardpahlke** [comment]
Exception request submitted by @soltysh has been [accepted](https://groups.google.com/a/kubernetes.io/g/release-team/c/2deGMfDtEL8/m/QBt-o6DCAQAJ) by the release team!

Your updated deadline to make any changes to your PR is [18:00 PST Friday 11th November 2022](https://everytimezone.com/s/042f76f9).

/milestone v1.26

**Comment by soltysh** [comment]
Unrelated failure
/test pull-kubernetes-e2e-gce-ubuntu-containerd

**Pull request merged**
