### PR TITLE
Formatting and grammar fixes in 1.20 changelog

### PR DESCRIPTION
**Pull request by jsoref**
Signed-off-by: Josh Soref <jsoref@users.noreply.github.com>

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:
This is not a complete fix for this file which would require significantly more changes (items were identified by app.grammarly.com, and I selected a subset), but I hope that these are easy enough to review and accept.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by jsoref** [comment]
@sftim thanks, I don't understand @k8s-ci-robot 's output.

Is any of this relevant?
> pull-kubernetes-bazel-build Job failed.
>           pload error: writer close error: Post \"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\u0026name=pr-logs%2Fpull%2F98955%2Fpull-kubernetes-bazel-build%2F1359788783549026304%2Fclone-records.json\u0026prettyPrint=false\u0026projection=full\u0026uploadType=multipart\": oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": dial tcp: i/o timeout writer close error: Post \"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\u0026name=pr-logs%2Fpull%2F98955%2Fpull-kubernetes-bazel-build%2Flatest-build.txt\u0026prettyPrint=false\u0026projection=full\u0026uploadType=multipart\": oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": dial tcp: i/o timeout writer close error: Post \"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\u0026name=pr-logs%2Fpull%2F98955%2Fpull-kubernetes-bazel-build%2F1359788783549026304%2Fbuild-log.txt\u0026prettyPrint=false\u0026projection=full\u0026uploadType=multipart\": oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": dial tcp: i/o timeout writer close error: Post \"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\u0026name=pr-logs%2Fpull%2F98955%2Fpull-kubernetes-bazel-build%2F1359788783549026304%2Fclone-log.txt\u0026prettyPrint=false\u0026projection=full\u0026uploadType=multipart\": oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": dial tcp: i/o timeout writer close error: Post \"https://storage.googleapis.com/upload/storage/v1/b/kubernetes-jenkins/o?alt=json\u0026name=pr-logs%2Fpull%2F98955%2Fpull-kubernetes-bazel-build%2F1359788783549026304%2Fstarted.json\u0026prettyPrint=false\u0026projection=full\u0026uploadType=multipart\": oauth2: cannot fetch token: Post \"https://oauth2.googleapis.com/token\": dial tcp: i/o timeout]","file":"prow/cmd/initupload/main.go:45","func":"main.main","level":"fatal","msg":"Failed to initialize job","severity":"fatal","time":"2021-02-11T09:14:39Z"}

All very confusing as this commit should only be changing a single markdown file...

**Comment by jsoref** [comment]
@wilsonehusin please help. This simple PR is quite stuck. It shouldn't be a boil-the-ocean problem.

**Comment by wilsonehusin** [comment]
hey @jsoref, thanks for submitting this PR. most of the release notes were written by PR authors and there is a team on every release cycle to review those notes. the number of people outnumbered the entries to be reviewed so we miss these chages which could be automated. if you're interested to contribute on that work so we can fix these issues before they land in this repository, please let me know on `#release-notes` in Slack, feel free to ping me `@wilsonehusin` as well!

/triage accepted
/priority backlog
/retest
/approve

**Comment by wilsonehusin** [comment]
/retitle Formatting and grammar fixes in 1.20 changelog

/retest

**Pull request merged**
