### PR TITLE
Remove tautological condition in test/e2e/framework/pod/resource.go

### PR DESCRIPTION
**Pull request by sshukun**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by andrewsykim** [comment]
/approve
/lgtm
/ok-to-test

Thanks @sshukun

**Review by andrewsykim — COMMENTED** [review]
/approve
/lgtm
/ok-to-test

Thanks @sshukun

**Review by alejandrox1 — APPROVED** [review]
Thank you for catching this @sshukun 
/retest

prev ci failures;
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88070/pull-kubernetes-node-e2e-containerd/1227638612405784576/
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88070/pull-kubernetes-e2e-gce/1227638612351258624/
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88070/pull-kubernetes-e2e-kind/1227638365747154944

**Pull request merged**
