### PR TITLE
Adding a kubectl resource printer for deployments

### PR DESCRIPTION
**Pull request by nikhiljindal**
Ref: #1743

This is how the output looks:

```
$ ./cluster/kubectl.sh get deployments
NAME             UPDATEDREPLICAS   AGE
my-deployment    3/3               3m
my-deployment2   0/5               14s
```

cc @ghodss @ironcladlou

### CODE REVIEW

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by ironcladlou** [comment]
LGTM

**Comment by nikhiljindal** [comment]
Adding LGTM tag as per the above LGTM

**Pull request merged**
