### PR TITLE
allow case insensitive matching for field selectors

### LINKED ISSUE #107285: Allow case-insensitive matching in selectors
### What would you like to be added?

_As a cluster operator_
_I want to be able to enter a command such as:_
```shell
kubectl delete pods --field-selector="status.phase!=Pending","metadata.namespace!=kube-system"
```
_So that I can clean up pending pods except in the primary system namespace_ (I think that command does this)
_And I don't want to have to remember what case convention the `.status.phase` field uses_

### Why is this needed?

(Field) selectors are case sensitive, and sometimes it'd be more convenient to allow ignoring case instead.

### PR DESCRIPTION
**Pull request by aryan9600**
Signed-off-by: Sanskar Jaiswal <jaiswalsanskar078@gmail.com>

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
This PR allows for case insensitive matching for field selectors.

#### Which issue(s) this PR fixes:

Fixes #107285 

#### Does this PR introduce a user-facing change?

```release-note
Field selectors can be used in a case insensitive manner.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by fedebongio** [comment]
/assign @liggitt 
Looks like the discussion already happened in the issue, and there is no agreement in favor.
/triage accepted

**Comment by liggitt** [comment]
I'll redirect this to api-machinery folks, but as-is, it is not a backwards-compatible change (since it makes field selectors that currently do not match start matching)

before implementation, https://github.com/kubernetes/kubernetes/issues/107285 needs to be agreed on

/hold
/unassign
/assign @lavalamp @deads2k

**Comment by lavalamp** [comment]
We definitely can't change this, and it looks like we're missing some test cases ensuring that it stays case sensitive. I would merge a PR adding such tests.

(sorry I didn't see this PR until just now)

**Pull request closed without merging**
