### PR TITLE
Delete a stale code comment

### PR DESCRIPTION
**Pull request by Songjoy**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
delete the comment "/ / TODO: move to reconstruct.go and remove old code there."

#### Special notes for your reviewer:
cleanup after https://github.com/kubernetes/kubernetes/pull/123442 is merged.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by carlory** [comment]
Thank you @Songjoy 
/lgtm
/sig storage
/assign @jsafrane

**Comment by carlory** [comment]
the `pull-kubernetes-e2e-gce-storage-slow` failures would be fixed by https://github.com/kubernetes/test-infra/pull/32160

**Comment by carlory** [comment]
I've lgtmed it, can you give it an approved label? Thank you @jsafrane

**Review by justankiit — COMMENTED** [review]
looks good!

**Pull request merged**
