### PR TITLE
v1.18 support changes

### LINKED ISSUE #94429: elasticsearch_logging_discovery.go:142] Found []
**What happened:**
I download fluentd-elasticsearch in addons.  The following error occurs  then I use "kubectl apply -f es-statefulset.yaml  "
Then, i find the elasticsearch-logging pod restart lots of time, and keep status with CrashLoopBackOff.

[root@istackvip ~]# kubectl logs -f elasticsearch-logging-0 -n kube-system
+ export NODE_NAME=elasticsearch-logging-0
+ NODE_NAME=elasticsearch-logging-0
+ export NODE_MASTER=true
+ NODE_MASTER=true
+ export NODE_DATA=true
+ NODE_DATA=true
+ export HTTP_PORT=9200
+ HTTP_PORT=9200
+ export TRANSPORT_PORT=9300
+ TRANSPORT_PORT=9300
+ export MINIMUM_MASTER_NODES=2
+ MINIMUM_MASTER_NODES=2
+ chown -R elasticsearch:elasticsearch /data
+ ./bin/elasticsearch_logging_discovery
I0902 14:25:06.694669       9 elasticsearch_logging_discovery.go:85] Kubernetes Elasticsearch logging discovery
I0902 14:25:06.706965       9 elasticsearch_logging_discovery.go:142] Found []
I0902 14:25:16.710309       9 elasticsearch_logging_discovery.go:142] Found []
I0902 14:25:26.713044       9 elasticsearch_logging_discovery.go:142] Found []
I0902 14:25:36.715882       9 elasticsearch_logging_discovery.go:142] Found []
I0902 14:25:46.718867       9 elasticsearch_logging_discovery.go:142] Found []
I0902 14:25:56.721760       9 elasticsearch_logging_discovery.go:142] Found []

### PR DESCRIPTION
**Pull request by coffeepac**
**What type of PR is this?**

kind bug

**What this PR does / why we need it**:

ongoing support for cluster addon, this is support for 1.18+

**Which issue(s) this PR fixes**:

Fixes #94429

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by coffeepac** [comment]
most of this PR is editor yaml formatting.  with 'hide whitespace changes' its +15/-4

**Review by monotek — APPROVED** [review]
/triage accepted
/lgtm

**Pull request merged**
