### PR TITLE
Bump Libcontainer to latest head

### PR DESCRIPTION
**Pull request by dubstack**
@Random-Liu or @yujuhong Can any one of you please do a quick review.

I updated libcontainer in a previous PR but  #29492 reverted those changes. This is needed for #27204. 

Signed-off-by: Buddha Prakash buddhap@google.com

### CODE REVIEW

**Comment by dubstack** [comment]
I will be adding a second commit with changes in Kubernetes codebase.

**Comment by Random-Liu** [comment]
@dubstack Test is failing.

**Comment by dubstack** [comment]
I will adding one more commit to add changes in kubernetes. I think the kubelet would also benefit from some refactoring. So i am working on that

**Comment by dubstack** [comment]
@Random-Liu @vishh PTAL.

**Comment by yujuhong** [comment]
PR LGTM.

**Comment by vishh** [comment]
LGTM

**Comment by vishh** [comment]
Bumping priority since three other PRs are dependent on this.

**Pull request merged**
