### PR TITLE
GKE deployment: Kill cluster/gke

### PR DESCRIPTION
**Pull request by zmerlynn**
kubernetes/test-infra#3983 migrated the remaining GKE jobs using the bash deployment (cluster/gke). All jobs are now on the gke `deployer` in `kubetest`.

Fixes kubernetes/test-infra#3307

```release-note
`cluster/gke` has been removed. GKE end-to-end testing should be done using `kubetest --deployment=gke`
```

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @mbforbes for historical reasons. I'm sure you care. :)

**Comment by roberthbailey** [comment]
I love PRs that are just red text; so easy to review. 

/lgtm

**Comment by bgrant0607** [comment]
Thanks!

**Comment by roberthbailey** [comment]
Woo!

**Comment by mbohlool** [comment]
From https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-new-gci-master-upgrade-cluster-new/180?log#log:

```
W0831 07:22:08.052] 2017/08/31 07:22:07 util.go:132: Running: ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Feature:ClusterUpgrade\] --upgrade-target=ci/latest --upgrade-image=gci --report-dir=/workspace/_artifacts --disable-log-dump=true --report-prefix=upgrade
W0831 07:22:08.425] ./hack/ginkgo-e2e.sh: line 92: detect-node-instance-groups: command not found
W0831 07:22:08.428] !!! Error in ./hack/ginkgo-e2e.sh:92
W0831 07:22:08.428]   Error in ./hack/ginkgo-e2e.sh:92. 'detect-node-instance-groups' exited with status 127
W0831 07:22:08.429] Call stack:
W0831 07:22:08.429]   1: ./hack/ginkgo-e2e.sh:92 main(...)
W0831 07:22:08.429] Exiting with status 1
```

Is these related to this PR? look like some of upgrade-test failures is because of this.

**Pull request merged**
