### PR TITLE
Parallelize reference operation in TestSecretCacheMultipleRegistrations

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
In TestSecretCacheMultipleRegistrations, currently AddReference / DeleteReference are done in serial.
However, since these operations are protected by lock, we should run them in parallel.

This PR uses go routines to do this.

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```

### CODE REVIEW

**Comment by tedyu** [comment]
ping @vishh

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

Overall, this change looks fine to me.

My one question is whether we are making this change so that we can test the parallelism/locking of `(Add|Delete)Reference` or if we are doing it for efficiency reasons? If the latter, I'm not sure this change is necessary, as it is only 20 operations, and it is part of the test suite (which isn't performance critical).

**Comment by tedyu** [comment]
This is to test the parallelism/locking of (Add|Delete)Reference .

**Comment by tedyu** [comment]
ping @vishh for review

**Comment by tedyu** [comment]
@dchen1107
Can you review ?

**Comment by tedyu** [comment]
@dchen1107
Can you review ?

Thanks

**Comment by tedyu** [comment]
@dchen1107
Can you review ?

**Comment by tedyu** [comment]
ping @derekwaynecarr for review

**Comment by tedyu** [comment]
ping @vishh for review

**Comment by tedyu** [comment]
in favor of #82601

**Pull request closed without merging**
