### PR TITLE
Still proceed to sync on aliases from node's spec and cloud even if the mode is not the expect one.

### PR DESCRIPTION
**Pull request by jingax10**
**What this PR does / why we need it**:

Still proceed to sync on aliases from node's spec and cloud even if the mode is not the expect one.

Without the fix, when upgrading a k8s cluster on GCE from route-based to IP aliases-based, as the initial state of node can be in several states for aliases in node's spec and cloud, it may stop us from syncing the PodCIDR between node spec and cloud just because the sync mode is not the one expected.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

None. This PR scopes out the go changes from PR #56132.

**Special notes for your reviewer**:

**Release note**:

```release-note
"NONE"
```

### CODE REVIEW

**Comment by bowei** [comment]
This is a bug fix for 1.9

**Comment by jingax10** [comment]
I will drop this PR, served as a workaround, as I found the error it intends to resolve becomes transient, which is supposed to be.

**Pull request closed without merging**
