### PR TITLE
Copy edits to remove doubled words

### PR DESCRIPTION
**Pull request by epc**
CLA previously signed as @epc.
Affects `/docs/` only.
I ran `hack/run-gendocs.sh` but it doesn't seem to do anything in my repo, wasn't clear if that's something I need to run or if that's part of build.

### CODE REVIEW

**Comment by kelseyhightower** [comment]
LGTM

**Comment by thockin** [comment]
LGTM

**Comment by eikaas** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tapiohush@gmail.com
    Domain eikaas.no has exceeded the max emails per hour (36/30 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:59524 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by cpanel30.proisp.no with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZEgs2-004G97-U2
	for robin@eikaas.no; Mon, 13 Jul 2015 18:46:27 +0200
Date: Mon, 13 Jul 2015 09:46:21 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1436805981;
	bh=d7Dfn0N0OT9LYNT9m8c0NfCW2KfhZc+xk1Y8jz5g8M8=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=L22TO/5NBen/0konVpCsRRkFGCQ4ZHp+s4ZtbiP9+toUd54o9zo+5OZjvoUTD7THm
	 CPo+ACuBeaVM+8En/rFwtIrpFt6tOacVnzj/jOZ/n00UBWxZ8x7vmVKbbpbIwcT2lu
	 VL4sQTv/c30GbFUVecKUta59/jyJtvc5uWVwLLuA=

**Comment by eikaas** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tapiohush@gmail.com
    Domain eikaas.no has exceeded the max emails per hour (37/30 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:42152)
	by cpanel30.proisp.no with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-7097-robin=eikaas.no@sgmail.github.com>)
	id 1ZEgsA-004GAx-Up
	for robin@eikaas.no; Mon, 13 Jul 2015 18:46:38 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=I3+aSIlpqp2oHzIMtleUBZCmiUw=; b=fs8C89gzw8FxusQV
	fi5SqAC49FgJL1+hPqxQdto5FHtdHngMoVgIa9KCxoPDs8py1EoHGJ8vk5++9Fiy
	nCvy4f3ZU8uuN+AH3WF4jazHmbH4UE9IzDBo2xxA8oPo0B2rjsLtiplPZq0mY0LB
	I1oiVvVWzHzdjLxR8mUb69pNEOs=
Received: by filter0504p1mdw1.sendgrid.net with SMTP id filter0504p1mdw1.28153.55A3EB624
        2015-07-13 16:46:26.597058738 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd-032 (SG) with ESMTP id 14e884f78f6.163.36e78
	for <robin@eikaas.no>; Mon, 13 Jul 2015 16:46:26 +0000 (UTC)
Date: Mon, 13 Jul 2015 09:46:26 -0700

**Pull request merged**
