### PR TITLE
fix typo in pkg

### PR DESCRIPTION
**Pull request by hwdef**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Cleanup: fix some typos in code comment

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

**Comment by hwdef** [comment]
@janetkuo

**Comment by hwdef** [comment]
@smarterclayton
please add an approved label for me.
Thank you.

**Comment by hwdef** [comment]
/assgin @thockin
Could add an approved label for this PR?
Thank you!

**Pull request merged**
