### PR TITLE
Revert "Add cluster up configuration for certificate signing duration."

### PR DESCRIPTION
**Pull request by ericchiang**
This reverts https://github.com/kubernetes/kubernetes/pull/51844

Fixes https://github.com/kubernetes/kubernetes/issues/52286
Fixes https://github.com/kubernetes/kubernetes/issues/52282
Unblocks https://github.com/kubernetes/kubernetes/issues/52270

```release-note
NONE
```

cc @kubernetes/kubernetes-release-managers 
cc @kubernetes/sig-auth-test-failures

### CODE REVIEW

**Comment by krzyzacy** [comment]
hummm @ixdy ^^ bazel is not behaving normally?

**Comment by ixdy** [comment]
The sha256sum of that archive apparently changed.

```console
$ wget https://github.com/bazelbuild/rules_go/archive/82483596ec203eb9c1849937636f4cbed83733eb.tar.gz
...
$ sha256sum 82483596ec203eb9c1849937636f4cbed83733eb.tar.gz
27a13726ff8621cfa4592fbef116b253043c2b093c8814265dc4489a0e67d229  82483596ec203eb9c1849937636f4cbed83733eb.tar.gz
```

???

**Comment by madhusudancs** [comment]
cc @csbell

**Comment by csbell** [comment]
This will need a manual merge once everything passes except federation-e2e-gce. Once this is done, we will redeploy the test clusters and address https://github.com/kubernetes/kubernetes/issues/52270

**Comment by ericchiang** [comment]
Will rebase one https://github.com/kubernetes/kubernetes/pull/52308 is merged.

**Comment by ericchiang** [comment]
(rebased re-applying lgtm)

**Comment by ericchiang** [comment]
@lavalamp this PR blocks https://github.com/kubernetes/kubernetes/issues/52270 which is the fix for the failing `pull-kubernetes-federation-e2e-gce` test.

I'd recommend merging manually once the last few tests go green, which is what @csbell recommended earlier https://github.com/kubernetes/kubernetes/pull/52299#issuecomment-328645999

**Pull request merged**
