### PR TITLE
OWNERS: add directxman12 to pkg/apis/autoscaling

### PR DESCRIPTION
**Pull request by DirectXMan12**
Added directxman12 (current SIG lead of SIG-autoscaling) as a reviewer for pkg/apis/autoscaling.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by DirectXMan12** [comment]
I noticed that I wasn't in the reviewers list for the autoscaling APIs (just the HPA controller), so I figured I should probably be on this list.

**Comment by DirectXMan12** [comment]
cc @derekwaynecarr

**Comment by cblecker** [comment]
```
I0425 09:06:35.723]   /go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go is out of date. Please run hack/update-staging-client-go.sh
I0425 09:06:35.725] FAILED   hack/make-rules/../../hack/verify-staging-client-go.sh	108s
```

**Comment by derekwaynecarr** [comment]
i dont understand how the jenkins job is hit by this pr, either way, i agree you should be in reviewer pool.

**Comment by cblecker** [comment]
`pkg/apis/autoscaling/OWNERS` gets copied to `staging/src/k8s.io/client-go/pkg/apis/autoscaling/OWNERS`, so updates to the former need to run the `hack/update-staging-client-go.sh` script to update the latter

**Comment by derekwaynecarr** [comment]
@cblecker -- makes sense.

/lgtm

**Pull request merged**
