### PR TITLE
Automated cherry pick of #48762 upstream release 1.7

### PR DESCRIPTION
**Pull request by wojtek-t**
Cherry pick of #48762 on release-1.7.

#48762: Workaround moby/moby#33948 and maybe fix kops timeouts.

### CODE REVIEW

**Review by luxas — APPROVED** [review]
/lgtm

**Comment by sttts** [comment]
Was it on-top of latest master with the other merged patch?

**Comment by sttts** [comment]
s/master/release-1.7/

**Comment by wojtek-t** [comment]
I think I merged it after creating this one.

**Comment by wojtek-t** [comment]
@sttts - once kops tests are green I will merge it manually. Rerunning all those tests is too annoying.

**Comment by sttts** [comment]
@wojtek-t kops is green

**Comment by wojtek-t** [comment]
Merging to fix kops in 1.7 branch.

**Pull request merged**
