### PR TITLE
fix golint errors in pkg/util/config

### PR DESCRIPTION
**Pull request by witcxc**
**What type of PR is this?**
> /kind cleanup

**What this PR does / why we need it**:
fix golint errors in pkg/util/config.
**Which issue(s) this PR fixes**:

Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
installing golint
Errors from golint:
pkg/util/config/config.go:25:6: exported type Merger should have comment or be unexported
pkg/util/config/config.go:35:1: exported method MergeFunc.Merge should have comment or be unexported
pkg/util/config/config.go:97:1: exported method AccessorFunc.MergedState should have comment or be unexported
pkg/util/config/config.go:101:6: exported type Listener should have comment or be unexported
pkg/util/config/config.go:109:1: exported method ListenerFunc.OnUpdate should have comment or be unexported
pkg/util/config/config.go:113:6: exported type Broadcaster should have comment or be unexported
```

### CODE REVIEW

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Comment by MHBauer** [comment]
Not sure how much traffic it gets, but `pkg/util` needs an OWNERS file. We quickly end up at project root and `/pkg/OWNERS` which is very few people. Is there a tool to generate one?

/assign @liggitt 
/lgtm
/approve

**Pull request closed without merging**
