### PR TITLE
Improved event message for ServiceController.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Improved event message for ServiceController. Follow up of #13992.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
@erictune Do you want to cherry-pick this PR to 1.1?

**Comment by wojtek-t** [comment]
LGTM

**Comment by erictune** [comment]
This is making the events harder to coalesce.  Recommend against this change.

**Comment by jszczepkowski** [comment]
@erictune I thought you explicitly requested this modification:
https://github.com/kubernetes/kubernetes/pull/13922#discussion_r40763376

**Pull request merged**
