### PR TITLE
Bumped cadvisor to v0.44.0  (plus required deps)

### PR DESCRIPTION
**Pull request by bwplotka**

### CODE REVIEW

**Comment by bobbypage** [comment]
This is already happening in https://github.com/kubernetes/kubernetes/pull/107149

**Comment by odinuge** [comment]
Hi @bwplotka,

As @bobbypage said, we are already tracking this in https://github.com/kubernetes/kubernetes/pull/107149 by @kolyshkin, so feel free to chime in to that one and review/track. I'll close this for now to limit the number of (dup) open PRs, but feel free to reopen if you disagree.

/close

**Pull request closed without merging**
