### PR TITLE
Automated cherry pick of #61818: Add CRI container log format support back.

### PR DESCRIPTION
**Pull request by Random-Liu**
Cherry pick of #61818 on release-1.10.

#61818: Add CRI container log format support back.

### CODE REVIEW

**Review by coffeepac — APPROVED** [review]

**Comment by MaciekPytel** [comment]
@Random-Liu can you add release note to base PR (the one to master), so that people can see this regression was fixed in patch release?

**Comment by loburm** [comment]
/kind/bug
/priority/critical-urgent

**Pull request merged**
