### PR TITLE
GCE Windows: Upgrade to flb-exporter v0.17.0 which reduces log spam.

### PR DESCRIPTION
**Pull request by jeremyje**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The current version of flb-exporter produces a lot of logspam because it does not gracefully handle the Windows Service Control's INTERROGATE signal. This produces a lot of useless logs in Stackdriver and etw logs.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig windows
/priority important-soon

### CODE REVIEW

**Review by ibabou — APPROVED** [review]

**Comment by jeremyje** [comment]
/unhold

Verified that the logspam is gone and no regressions.

**Pull request merged**
