### PR TITLE
Fix of reverted #9728

### PR DESCRIPTION
**Pull request by justinsb**
Not sure if we still want to merge this, but this is #9728 with the fix for the unit test; will hopefully pass shippable and e2e.

I needed to directly initialize NodeName in the unit tests where we directly build a Kubelet.  I need to figure out how this got past my testing.

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
@justinsb My question is that why shippable didn't complain at the first place. But I do think your fix added here fix the test issue.

**Comment by justinsb** [comment]
@dchen1107 I don't know (and I'm just confusing myself: https://github.com/GoogleCloudPlatform/kubernetes/pull/9728#issuecomment-113285673)  I did figure out that e2e testing tests not the result of the merge, but rather the tree at the head of the PR branch.  We should probably make sure shippable is testing the merge result, although the downside is that requires re-running on every merge, which is expensive.

**Comment by satnam6502** [comment]
I ran the unit tests for this PR and they pass.

**Pull request merged**
