### PR TITLE
fix typo implmenets->implements  bootstap->bootstrap

### PR DESCRIPTION
**Pull request by SenXuDC**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
 fix some typos

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

NONE

### CODE REVIEW

**Comment by nikhita** [comment]
/assign @timothysc @jsafrane 
for approval

**Review by timothysc — APPROVED** [review]
/approve 
/lgtm

**Pull request closed without merging**
