### PR TITLE
fix: use locked func to replace the raw one to avoid concurrent read

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Use locked func to replace the raw one to avoid concurrent read, since the locked one have defined.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/ok-to-test

Thanks for this fix :)

**Comment by cwdsuzhou** [comment]
> /lgtm
> /ok-to-test
> 
> Thanks for this fix :)

Thank @mattjmcnaughton 

ping @tallclair

**Pull request merged**
