### PR TITLE
Remove golang fork for typecheck

### PR DESCRIPTION
**Pull request by cblecker**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Back in kubernetes/kubernetes#59289, we added a new typecheck test, and it required modifications to go's types package (golang/go#23712). Those modifications aren't needed anymore, and as such, I'm updating this to remove the fork.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
Thanks for this, rmmh, has other things going on so I will take a look per discussion in #sig-testing :-)
/assign

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Comment by cblecker** [comment]
/assign @smarterclayton @lavalamp @thockin 
Would one of you mind approving for the `third_party/` removal? Thanks!

**Comment by ixdy** [comment]
why is `test/typecheck/srcimporter/srcimporter.go` not under third_party? that seems odd...

**Comment by cblecker** [comment]
/hold
@ixdy actually, you're right. I think it's because we needed to modify it.

**Comment by cblecker** [comment]
@ixdy okay, moved things over to third_party/. should be good for review

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Pull request merged**
