### PR TITLE
godep: revert deletes of curated buildfiles when saving

### PR DESCRIPTION
**Pull request by mikedanese**
```release-note
NONE
```

### CODE REVIEW

**Comment by ixdy** [comment]
why do we need this? what isn't doing the right thing here?

**Comment by mikedanese** [comment]
remove that file and rerun bazel.
```diff
     importpath = "github.com/kubernetes/repo-infra/kazel",
-    tags = ["automanaged"],
+    visibility = ["//visibility:private"],
     deps = [
```

**Comment by ixdy** [comment]
/lgtm cancel

This is the wrong fix.
https://github.com/kubernetes/repo-infra/pull/67 + updating kazel here is the right fix.

**Pull request closed without merging**
