### PR TITLE
Update Microsoft/go-winio to released v0.4.15

### PR DESCRIPTION
**Pull request by eddiezane**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This PR updated the github.com/Microsoft/go-winio dependency to a released version from a pinned hash.

ref: https://kubernetes.slack.com/archives/CHGFYJVAN/p1604591598051000

**Which issue(s) this PR fixes**:

https://github.com/kubernetes/kubernetes/pull/96163 will need a rebase.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by eddiezane** [comment]
Possibly?
/sig windows

/cc @dims 
/assign @dchen1107

**Comment by eddiezane** [comment]
[pull-kubernetes-bazel-test](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/96271/pull-kubernetes-bazel-test/1324385065391624192) looks like vsphere here https://github.com/kubernetes/kubernetes/issues/94528

[pull-kubernetes-node-e2e](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/96271/pull-kubernetes-node-e2e/1324385065530036224/) is https://github.com/kubernetes/kubernetes/issues/94223

/retest

**Comment by dims** [comment]
/assign @liggitt 

Thanks to @lachie83 for nudging the go-winio folks to cut a SHA that we could use.

**Comment by dims** [comment]
/assign @michmike @marosset 

really easy one :) 

Diff : https://github.com/Microsoft/go-winio/compare/fc70bd9a86b5...v0.4.15
Specific change that we end up vendoring : https://github.com/microsoft/go-winio/pull/166

**Comment by liggitt** [comment]
/approve
for deps

**Review by michmike — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
