### PR TITLE
clean up deprecated funcs in e2e framework

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Ref https://github.com/kubernetes/kubernetes/pull/115961

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by SataQiu — COMMENTED** [review]
/lgtm

**Comment by carlory** [comment]
/assign @pohly 

🙏

**Review by pohly — APPROVED** [review]
/lgtm
/approve

Yeah, making the E2E framework smaller! :smile:

**Pull request merged**
