### PR TITLE
kubelet/rkt: Add GetPods() for rkt.

### PR DESCRIPTION
**Pull request by yifan-gu**
@vmarmol @jonboulle @dchen1107 @bakins

Need #7555 first.

### CODE REVIEW

**Comment by vmarmol** [comment]
Looks like a rebase is needed @yifan-gu :)

**Comment by yifan-gu** [comment]
Yea, this conflicts with #7555 and #7589 
Will rebase after those. But you can give a look if you want :)

**Comment by vmarmol** [comment]
From a cursory glance, it looks good.

**Comment by yifan-gu** [comment]
Rebased @vmarmol

**Comment by vmarmol** [comment]
LGTM

**Comment by vmarmol** [comment]
@yifan-gu 2 needed rebase it seems, this one

**Pull request merged**
