### PR TITLE
remove unused code in pkg/apimachinery

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

remove unused code in pkg/apimachinery

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
Finally 👍 

/lgtm
/approve no-issue

**Comment by hzxuzhonghu** [comment]
run update-bazel.sh

**Comment by hzxuzhonghu** [comment]
ping @brendandburns @dchen1107

**Comment by hzxuzhonghu** [comment]
/test pull-kubernetes-bazel-test
--

**Comment by hzxuzhonghu** [comment]
kindly ping @brendandburns

**Pull request merged**
