### PR TITLE
Make controller Run methods consistent

### PR DESCRIPTION
**Pull request by ncdc**
- startup/shutdown logging
- wait for cache sync logging
- defer utilruntime.HandleCrash()
- wait for stop channel before exiting

Please review for accuracy and consistency.

cc @deads2k @wojtek-t @smarterclayton @sttts @mikedanese @liggitt @rrati @derekwaynecarr

### CODE REVIEW

**Comment by wojtek-t** [comment]
I can take this if you're fine with waiting until tomorrow for review - I really like this PR (from the description).

**Comment by ncdc** [comment]
@wojtek-t that's fine - no need to rush this in, nor should we. Thanks!

**Comment by guangyouyu** [comment]
@ncdc  nodeController in the cloud-controller-manager should also run in goroutine because the controller.WaitForCacheSync in nodeController.run will block(after removing the anonymous function)

**Comment by ncdc** [comment]
@guangyouyu thanks, fixing now

**Comment by ncdc** [comment]
@guangyouyu actually that's a different type (from `k8s.io/kubernetes/pkg/controller/cloud`)

**Comment by guangyouyu** [comment]
@ncdc  sorry，my mistake
 In addition, CloudNodeController seems to refactoring also,may be can assigned to me

**Comment by guangyouyu** [comment]
@ncdc sorry，my mistake
In addition, CloudNodeController seems to refactoring also

**Comment by ncdc** [comment]
@wojtek-t rebased. The only conflict was with your changes to pkg/proxy/config. Please review and make sure it still looks ok in there. Thanks!

**Comment by ncdc** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
