### PR TITLE
Update expection of kubectl describe test based on kubectl version

### PR DESCRIPTION
**Pull request by mengqiy**
fixes: #43464

```release-note
NONE
```

/assign @pwittrock

### CODE REVIEW

**Comment by pwittrock** [comment]
Thanks @mengqiy !

**Comment by mengqiy** [comment]
After discussed with @pwittrock offline, I updated the test expection based on kubectl version.

**Comment by enisoc** [comment]
It seems weird to be cherrypicking into 1.6 to verify new behavior of later versions. When the 1.6 e2e is running against a post-upgrade cluster, shouldn't we still give it a 1.6 kubectl?

**Comment by mengqiy** [comment]
> When the 1.6 e2e is running against a post-upgrade cluster, shouldn't we still give it a 1.6 kubectl?

Using a 1.6 kubectl with a post-upgrade (1.7) cluster will have version skew which is not upgrade tests want to cover.

**Comment by pwittrock** [comment]
@enisoc I believe running the 1.6 e2e tests against a 1.7 kubectl and cluster is needed to make sure we didn't break API compatibility between releases.

**Pull request merged**
