### PR TITLE
Handle nil pod in pod format

### PR DESCRIPTION
**Pull request by uzuku**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Handle nil pod case in pod format, or a panic will occur.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
/ok-to-test

Out of curiosity, has the issue actually happened "in production", or is more of a theoretical concern?

Curious to hear the opinions of @tallclair around what kubelet's policy is for handling functions which could be passed nil? Should the function handle if its called with `nil`, or should the callers of the function ensure they aren't passing `nil`? I tend to defer towards the later, but that's a loose preference.

**Comment by uzuku** [comment]
> Out of curiosity, has the issue actually happened "in production", or is more of a theoretical concern?

@mattjmcnaughton  Actually I encountered it in my own code which imports some kubelet utils including this, and the code panics when nil is passed. I didn't found that kubelet itself has actually passed a nil to it.

Kubelet is not expected to be imported by other codes, so your concern is quite reasonable. This is just a concern that a potential panic is dangerous for a function that used widely.

**Comment by mattjmcnaughton** [comment]
> > Out of curiosity, has the issue actually happened "in production", or is more of a theoretical concern?
> 
> @mattjmcnaughton Actually I encountered it in my own code which imports some kubelet utils including this, and the code panics when nil is passed. I didn't found that kubelet itself has actually passed a nil to it.
> 
> Kubelet is not expected to be imported by other codes, so your concern is quite reasonable. This is just a concern that a potential panic is dangerous for a function that used widely.

Gotya, thanks for the additional info. Curious to hear from others around their opinions :)

**Comment by tallclair** [comment]
/lgtm
/approve

Can't hurt. It's an annoying aspect of Go that we need to deal with this 🙁

**Pull request merged**
