### PR TITLE
Check for valid serviceaccount JWT token before inspecting claims

### PR DESCRIPTION
**Pull request by liggitt**
Moved claims check after the error check that ensures we have a valid JWT token

### CODE REVIEW

**Comment by liggitt** [comment]
@krousey fixes non-jwt bearer token auth

**Comment by liggitt** [comment]
@cjcullen PTAL

**Comment by liggitt** [comment]
cc @colemickens

**Comment by cjcullen** [comment]
LGTM. Thanks for fixing this up.

**Comment by liggitt** [comment]
picked in a revert of @krousey's revert

**Comment by jfrazelle** [comment]
ah you hit the jwt pkg api update, I did this in a different project ;)

**Comment by jfrazelle** [comment]
changes look good to me

**Comment by colemickens** [comment]
Thanks for catching and fixing this @liggitt, sorry I didn't catch it in my initial update PR.

Do the GKE e2e tests not run for PRs, maybe just on some interval?

**Comment by cjcullen** [comment]
@colemickens We're still working on hooking in some small amount of GKE smoke tests into the PR builder.

**Pull request merged**
