### PR TITLE
api types: fix protobuf names that are different from JSON name

### LINKED ISSUE #45183: SubjectAccessReview and CertificateSigningRequest protobuf struct tags don't match json tags
Noticed this after generating Go types from the protobuf files. SubjectAccessReviewSpec has "verb" instead of "user"[1]. CertificateSigningRequestSpec uses "keyUsages" instead of the JSON tag "usages"[2].

```go
	User string `json:"user,omitempty" protobuf:"bytes,3,opt,name=verb"`
```

Since protobuf names aren't important, just the index, I think we can fix this with no comparability breaks for the wire format. cc @kubernetes/sig-api-machinery-bugs 

P.S. here's the script I used to find the mismatched tags:

```python
#!/usr/bin/env python

from __future__ import print_function

import os
import re
import sys

# Search for JSON and Protobuf struct tags.
pattern = re.compile('json\:"(\w+).*name=(\w+)')

exit_code = 0

for root, dirs, files in os.walk("pkg"):
    for file in files:
        if file != "types.go":
            continue

        p = os.path.join(root, file)
        with open(p, "r") as f:
            for line in f:
                result = pattern.search(line)
                if result is None:
                    continue

                json_name = result.group(1)
                pb_name = result.group(2)
                if json_name != pb_name:
                    exit_code = 1
                    print("mismatch in %s: %s!=%s" % (p, json_name, pb_name))

sys.exit(exit_code)
```

Which prints

```
$ ./find.py 
mismatch in pkg/apis/authorization/v1/types.go: user!=verb
mismatch in pkg/apis/authorization/v1beta1/types.go: user!=verb
mismatch in pkg/apis/certificates/v1beta1/types.go: usages!=keyUsage
```

[1] https://github.com/kubernetes/kubernetes/blob/v1.6.2/pkg/apis/authorization/v1/types.go#L134
[2] https://github.com/kubernetes/kubernetes/blob/v1.6.2/pkg/apis/certificates/v1beta1/types.go#L54

### PR DESCRIPTION
**Pull request by ericchiang**
This PR fixes the naming of protobuf fields that are mismatched when compared to the JSON names. Because protobuf names aren't actually used during serialization, just the index, I think we can update these safely without changing the over the wire encoding (note that generated.pb.go doesn't change).

Can someone verify that fixing the name won't impact backward compatibility?

cc @kubernetes/sig-api-machinery-pr-reviews 

Fixes https://github.com/kubernetes/kubernetes/issues/45183

```release-notes
None
```

### CODE REVIEW

**Comment by deads2k** [comment]
> Can someone verify that fixing the name won't impact backward compatibility?

@smarterclayton

**Comment by smarterclayton** [comment]
Protobuf name changes would affect generated clients, not serialization on the wire.  We accept that generated clients may have to change as part of our reduced gaurantees around protobuf idl

**Pull request merged**
