### PR TITLE
kubectl: ensure '--duration' must be positive for 'kubectl create token' command

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind bug
/kind cleanup

#### What this PR does / why we need it:
- add some clarification about `--duration=0s` for `kubectl create token` command
- ensure '--duration' must be positive for 'kubectl create token' command

The default value is set by:
https://github.com/kubernetes/kubernetes/blob/dde22b3a5ede36bfaec97827ade95df69467959d/pkg/apis/authentication/v1/defaults.go#L28-L33

```sh
# kubectl create token -h
    --duration=0s:
	Requested lifetime of the issued token. The server may return a token with a longer or shorter lifetime.
```
When `0s` is used as the default value for `--duration`, the user may think that it never expires.
But in fact our system sets it to expire after 1 hour, which causes the user to be confused.
For example: https://stackoverflow.com/questions/73416660/kubernetes-dashboard-token-expired-in-one-hour-how-to-create-token-for-long-tim

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by SataQiu** [comment]
Hi @soltysh, PTAL!

**Comment by SataQiu** [comment]
/assign @apelisse
PTAL, thanks.

**Comment by apelisse** [comment]
I don't know if that's how I would have done it.

1. We probably don't need to set the default value client-side if it ends-up being defaulted server-side anyway. Why don't we make that field optional without a default? As in, if it's not specified we just don't send a value?
2. It sounds like the 0 value is not a "valid value" server-side (it results into the default being applied), we should just forbid it. If someone does `--duration=0s` then fail with `0s is not a valid duration, must be positive.` or something.

What do you think?

**Comment by SataQiu** [comment]
@apelisse thanks

> We probably don't need to set the default value client-side if it ends-up being defaulted server-side anyway. Why don't we make that field optional without a default? As in, if it's not specified we just don't send a value?

This field is already **optional**, when it is not set, its value will be 0. 

```go
// Duration is the requested token lifetime. Optional.
Duration time.Duration
```

> It sounds like the 0 value is not a "valid value" server-side (it results into the default being applied), we should just forbid it. If someone does --duration=0s then fail with 0s is not a valid duration, must be positive. or something.

The verification is already there. But we allow it to be 0 to use the default value set by server-side. This is also the default behavior when the `--duration` flag is not specified. 
https://github.com/kubernetes/kubernetes/blob/3c94af73e1b08eb2a12208c94fe01ad22b08000e/staging/src/k8s.io/kubectl/pkg/cmd/create/create_token.go#L198-L200

The current behavior seems reasonable, I think we just need to add a few notes about `--duration=0s`, WDYT?

**Comment by apelisse** [comment]
Yeah no, I still disagree. If you don't want people to use 0, then don't allow zero. I agree it's misleading.
Could you check using the `Changed` method if the value has been explicitely set to 0 or not, and reject it if it has?

**Comment by SataQiu** [comment]
> Could you check using the `Changed` method if the value has been explicitly set to 0 or not, and reject it if it has?

Oh, I see. Thanks a lot for your advice. @apelisse 
I pushed the code. Can you have a look again?

**Comment by apelisse** [comment]
Yeah, I think that's correct, I wish we had a test but I don't know how convenient this is to add. There is `test/cmd/create.sh` but it doesn't look like the right place to do it.
/lgtm
/approve

**Pull request merged**
