### PR TITLE
Automated cherry pick of #103743: vendor: bump runc to 1.0.1

### PR DESCRIPTION
**Pull request by rphillips**
Cherry pick of #103743 on release-1.22.

#103743: vendor: bump runc to 1.0.1

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

Release Note:
```release-note
Bump runc to 1.0.1
```

### CODE REVIEW

**Comment by ehashman** [comment]
@rphillips can you please add a release note? runc version bump is user facing

**Review by ehashman — COMMENTED** [review]
/triage accepted
/lgtm

confirmed patch matches previous PR exactly

**Comment by ehashman** [comment]
/hold

for release note and for master PR to merge

**Review by saschagrunert — APPROVED** [review]
Approving for SIG release
/lgtm

**Pull request merged**
