### PR TITLE
Include BGPConfiguration

### PR DESCRIPTION
**Pull request by satyasm**
Needed for calico 2.x to 3.x upgrade.

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
cherrypick PR #71868 into release-1.13 branch

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Include CRD for BGPConfigurations, needed for calico 2.x to 3.x upgrade.
```

### CODE REVIEW

**Comment by satyasm** [comment]
/assign @caseydavenport 
/cc @jingax10 

cherry-pick PR #71868 into release 1.13 branch. needs ok-to-test.

**Comment by satyasm** [comment]
/assign @AishSundar 

@AishSundar can you help approve this for 1.13 branch?

**Comment by aleksandra-malinowska** [comment]
> Needed for calico 2.x to 3.x upgrade.

Is this covered by any tests? If yes, can you please provide links to relevant jobs/dashboards?

**Comment by satyasm** [comment]
> Is this covered by any tests? If yes, can you please provide links to relevant jobs/dashboards?

What was observed was that without this CRD definition, upgrade of k8s from a version that uses calico 2.x to a version that uses calico 3.x causes it to crash loop. @caseydavenport is from Tigera (owners of calico) and he has tested this change and approved it.

**Pull request merged**
