### PR TITLE
doc typos

### PR DESCRIPTION
**Pull request by stensonb**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30314)

### CODE REVIEW

**Comment by lavalamp** [comment]
ok to test

**Comment by mbohlool** [comment]
ok to test

**Comment by mbohlool** [comment]
Api reference docs verifications are failing. please run ./hack/verify-api-reference-docs.sh

**Comment by mbohlool** [comment]
verification is failing, please run ./hack/verify-api-reference-docs.sh

**Pull request closed without merging**
