### PR TITLE
Added NFS to PV structs

### PR DESCRIPTION
**Pull request by markturansky**
@thockin We removed NFS from these structs in previous PRs and said we'd add NFS in a separate request.  Here it is.

The NFS plugin already supported PV and the unit tests correctly test it.  Only had to add it to the API.

### CODE REVIEW

**Comment by thockin** [comment]
LGTM

**Comment by ArtfulCoder** [comment]
I have kicked off Shippable again.

**Comment by ArtfulCoder** [comment]
@markturansky  can you fix merge conflicts. you would have to sync and rebase..

**Comment by markturansky** [comment]
will do

**Comment by markturansky** [comment]
@ArtfulCoder Travis came back green.

**Pull request merged**
