### PR TITLE
Support default udev GCE PD device path

### PR DESCRIPTION
**Pull request by ghost**
The expected GCE PD device name is google-{name of disk}. This is
because standard GCE images contain a udev rules file which renames
the GCE PD device to google-{name of disk} https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/google-startup-scripts/lib/udev/rules.d/65-gce-disk-naming.rules. In custome images which do not have that udev rules file
the device gets the default rules apply http://cgit.freedesktop.org/systemd/systemd/tree/rules/60-persistent-storage.rules
and the GCE PD device ends up with a name which looks like scsi-0Google_PersistentDisk_{name of disk}
This patch adds support for that scenario.

Signed-off-by: Sami Wagiaalla swagiaal@redhat.com

### CODE REVIEW

**Comment by mbforbes** [comment]
+cc @smarterclayton @thockin

**Comment by ddysher** [comment]
The code change looks good to me, but two thoughts on the problem you tried to solve.

I would expect there to be an image build process which will take such thing into account, e.g. install the rules for you while you are building the image.  @brendandburns may know it.

The other is will this work on distro not adopting systemd yet, notably slackware, stock gentoo, older ubuntu?

**Comment by swagiaal** [comment]
> The other is will this work on distro not adopting systemd yet, notably slackware, stock gentoo, older ubuntu?

Hmm... I have not tested the above but udev now lives in the systemd tree: http://lwn.net/Articles/490413/. So even distros which do not have not adopted systemd would get it form the systemd repo

**Comment by swagiaal** [comment]
@ddysher I looked at a Gentoo as an example and the 60-persistent-storage.rules is the same as the one found in the systemd repo

**Comment by ddysher** [comment]
Thanks for confirming!  Just as a precaution, did you run e2e test?  specifically, the pd test

**Comment by swagiaal** [comment]
@ddysher I ran the e2e tests. The pd tests are passing.

**Pull request merged**
