### PR TITLE
Update scheduler perf to spin up similar client to other tests

### LINKED ISSUE #34504: Fix scheduler perf tests
Problem 

Looks like the master in scheduler performance tests is coming up with panics due to a nil data structure (or else , something is very corrpupt in my build env., but i doubt that).  There were some recent changes to clients and master APIs, probably that is the culprit.  

Thoughts 

Happy if scheduler_perf is still working for folks as of monday morning, to close this issue but for me it seems broke, and the  panic is   i traced down to a nil client configuration object before i gave up and just started looking at how other, similar tests are spinning up masters. 

Solution

I think this happened breifly after commit 204dbe7fdd3bcc88916b359a71baf59f2c3807a7 , but not sure.  Seems like in any case there is a cleaner way to spin a master up that is more declarative that other tests are running.  This avoids the nil exception, probably related to changes to the client or the wrapper apis for the master or something.

```

	h := &framework.MasterHolder{Initialized: make(chan struct{})}
	s := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
		<-h.Initialized
		h.M.Handler.ServeHTTP(w, req)
	}))

	framework.RunAMasterUsingServer(framework.NewIntegrationTestMasterConfig(), s, h)
	
	restClient := client.NewOrDie(&restclient.Config{
		Host:          s.URL,
		ContentConfig: restclient.ContentConfig{GroupVersion: &registered.GroupOrDie(api.GroupName).GroupVersion},
		QPS:           5000.0,
		Burst:         5000,
	})

```

Ill submit a PR shortly to see what folks thing.   @davidopp  @timothysc @gmarek

### PR DESCRIPTION
**Pull request by jayunit100**
Seems to Fix #34504 .  But I'm not sure what the mechanics of the underlying client objects is all supposed to be.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34506)

### CODE REVIEW

**Comment by jayunit100** [comment]
Im assuming no functional changes here, but if anyone sees any LMK.

**Comment by spxtr** [comment]
Seems fine to me, although I don't have much context.

**Comment by spxtr** [comment]
@k8s-bot test this

https://github.com/kubernetes/test-infra/issues/798

**Comment by davidopp** [comment]
cc/ @wojtek-t

**Pull request merged**
