### PR TITLE
Doc updates for 1.9

### PR DESCRIPTION
**Pull request by zacharysarah**
**What this PR does / why we need it**: This PR makes changes to the upstream source for autogenerated docs for features in the v1.9 release.

**Which issue(s) this PR fixes**:
Updates upstream source for:

PR | Complete?
---|---
https://github.com/kubernetes/website/pull/6465 | ✔️ 

**Special notes for your reviewer**: These changes have already been approved for downstream integration in `kubernetes/website`. 

**Release notes:**
```release-note
NONE
```

/cc @idvoretskyi

### CODE REVIEW

**Comment by zacharysarah** [comment]
I'm at a loss for why the `pull-kubernetes-e2e-gce` and `pull-kubernetes-unit` checks are failing. The errors seem unrelated to the PR. Anyone able to shed light?

**Comment by cblecker** [comment]
@zacharysarah Can you please update the commit message? It still has "WIP" in it.

**Comment by zacharysarah** [comment]
@cblecker 👋 Done, PTAL.

**Comment by cblecker** [comment]
@zacharysarah That didn't fix it. Have a look at the commits tab: https://github.com/kubernetes/kubernetes/pull/56942/commits

Take a look at the directions here: https://help.github.com/articles/changing-a-commit-message/#amending-older-or-multiple-commit-messages

The new new commits you created can be dropped, and then you can "reword" the commit message to make it accurate.

**Comment by zacharysarah** [comment]
ACK.  In progress
ETA: 12/12/2017
Risks: Minimal

**Comment by zacharysarah** [comment]
@cblecker Thanks for the review! 💛 Any insight on the failing test?

**Comment by cblecker** [comment]
I believe it's a flake
/retest

**Comment by zacharysarah** [comment]
@cblecker Looks like the jobs are hung.

**Pull request merged**
