### PR TITLE
Sort kubeadm CLI default params for component config API objects

### PR DESCRIPTION
**Pull request by dims**
See problem reported here : https://github.com/kubernetes/kubernetes/issues/70131#issuecomment-498606589 We need to keep the list sorted.

Change-Id: If4ba57d528f925de9d536b18c0e6d71fc6d63659

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
thanks @dims
/assign @rosti
/milestone v1.16

**Review by bmwiedemann — APPROVED** [review]
I tested this change (rebased on top of openSUSE's kubernetes-1.14.1) and the man page diffs went away.

**Comment by bmwiedemann** [comment]
The commit message and PR description should add some detail about why this change is good, e.g.:
make the man-page generation reproducible

**Review by rosti — APPROVED** [review]
Thanks @dims !
Just a minor nit, can you add a comment next to the sort call to indicate, that we need it for reproducible builds? Someone may accidentally delete it in the future.
/approve

**Comment by neolit123** [comment]
/lgtm
/hold

@dims @rosti it's OK without the comment, but it's better i guess.

> Thanks @dims !
Just a minor nit, can you add a comment next to the sort call to indicate, that we need it for reproducible builds? Someone may accidentally delete it in the future.

@rosti please unhold if see fit.

**Comment by rosti** [comment]
Let's not hold it off further, because of the comment.
/hold cancel

**Pull request merged**
