### PR TITLE
Automated cherry pick of #30008 #30479

### PR DESCRIPTION
**Pull request by ixdy**
Cherry pick of #30008 #30479 on release-1.2.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30942)

### CODE REVIEW

**Comment by ixdy** [comment]
#30008 is reactive (kubernetes-build-1.2 is currently broken). #30479 is preemptive.

cc @fejta

**Comment by fejta** [comment]
Are we concerned with the failing tests?

**Comment by fejta** [comment]
Otherwise LGTM (although I'm not assigned)

**Comment by ixdy** [comment]
@fejta the GKE PR build uses `build/util.sh`, which doesn't exist in `release-1.2`. No idea about node e2e, but 1.2 is probably old enough that it wasn't particularly stable yet?

**Comment by ixdy** [comment]
@k8s-bot node e2e test this please, issue #IGNORE

**Comment by ixdy** [comment]
I think node e2e is just broken on release-1.2...

**Comment by ixdy** [comment]
@k8s-bot test this please, issue #IGNORE

**Comment by ixdy** [comment]
@k8s-bot test this please, issue #25107

**Comment by ixdy** [comment]
@k8s-bot test this please, issue #IGNORE

**Comment by rmmh** [comment]
@k8s-bot gke test this please, issue #27462

**Comment by roberthbailey** [comment]
lgtm

**Pull request merged**
