### PR TITLE
Uncomment the code that caused by #19254

### PR DESCRIPTION
**Pull request by zhouhaibing089**
Fix https://github.com/kubernetes/kubernetes/issues/24546.

@lavalamp

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm

**Comment by zhouhaibing089** [comment]
**Jenkins unit/integration**:

```
Go version: go version go1.6 linux/amd64
...
2016/04/21 07:15:57 httptest.Server blocked in Close after 5 seconds, waiting for connections:
  *net.TCPConn 0xc822e35140 127.0.0.1:35332 in state active
  *net.TCPConn 0xc826bfb7a0 127.0.0.1:35334 in state active
  *net.TCPConn 0xc824c96188 127.0.0.1:35344 in state active
  *net.TCPConn 0xc822e35198 127.0.0.1:35339 in state active
  *net.TCPConn 0xc824c96180 127.0.0.1:35343 in state active
  *net.TCPConn 0xc822e35130 127.0.0.1:35329 in state active
  *net.TCPConn 0xc822e35138 127.0.0.1:35331 in state active
  *net.TCPConn 0xc8241762b8 127.0.0.1:35347 in state active
panic: test timed out after 5m0s
```

it looks like what  @yujuhong saw: https://github.com/kubernetes/kubernetes/issues/19254#issuecomment-173666322

**Comment by zhouhaibing089** [comment]
**Jenkins GCE Node e2e** failure: it is the same error as https://github.com/kubernetes/kubernetes/issues/23971 pointed out.

**Comment by deads2k** [comment]
Removing tag while you sort out whether the base problem is actually fixed.

**Comment by lavalamp** [comment]
Looks like that particular test leaves connections open? Maybe leave it commented out for that test, and file an issue specifically about fixing that test?

**Comment by zhouhaibing089** [comment]
comment code again here: https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler_test.go#L288-L289 due to the logs:

```
goroutine 6580 [semacquire, 4 minutes]:
sync.runtime_Semacquire(0xc826ed947c)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc826ed9470)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
net/http/httptest.(*Server).Close(0xc826ed9440)
	/usr/local/go/src/net/http/httptest/server.go:189 +0x25d
k8s.io/kubernetes/test/integration.TestMultiScheduler(0xc8287cfa70)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler_test.go:456 +0x279e
testing.tRunner(0xc8287cfa70, 0x2f6efb0)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892
```

**Comment by zhouhaibing089** [comment]
@lavalamp @deads2k it is a little bit amazing, after comment out that part of code, tests show passes.

continuous-integration/travis-ci/pr looks like to be stalled: `No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.`

**Comment by zhouhaibing089** [comment]
@deads2k PTAL, just rebased the code and now all the tests are green.

**Comment by deads2k** [comment]
build failure: `_output/local/go/src/k8s.io/kubernetes/pkg/apiserver/watch_test.go:145: client declared and not used`

**Comment by deads2k** [comment]
feel free to tag once you've gone green.

**Comment by zhouhaibing089** [comment]
@deads2k I am not authorized to add tag(if you mean adding the label)...

**Pull request merged**
