### PR TITLE
Fix data-race in reflector test in Go 1.5.1

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #13838

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by caesarxuchao** [comment]
@k8s-bot e2e test this

**Comment by caesarxuchao** [comment]
@k8s-bot unit test this

**Comment by caesarxuchao** [comment]
I must be too dense at this hour. I cannot see how these writes and reads can happen in parallel..

**Comment by wojtek-t** [comment]
@caesarxuchao - this is what Go 1.5.1 reports:

    Read by goroutine 11:
      k8s.io/kubernetes/pkg/client/cache.TestReflectorResync.func1()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector_test.go:370 +0x4b
      k8s.io/kubernetes/pkg/client/cache.(*Reflector).timeoutForWatch()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:207 +0x96
      k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:254 +0xc9d
      k8s.io/kubernetes/pkg/client/cache.(*Reflector).RunUntil.func1()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:164 +0x36
      k8s.io/kubernetes/pkg/util.Until.func1()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:126 +0x58
      k8s.io/kubernetes/pkg/util.Until()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:127 +0x7d

    Previous write by goroutine 31:
      k8s.io/kubernetes/pkg/client/cache.TestReflectorResync.func2()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector_test.go:380 +0x45b
      k8s.io/kubernetes/pkg/client/cache.(*testLW).Watch()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector_test.go:42 +0x81
      k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:256 +0xd35
      k8s.io/kubernetes/pkg/client/cache.TestReflectorResync()
          /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector_test.go:400 +0x767
      testing.tRunner()
          /tmp/workdir/go/src/testing/testing.go:456 +0xdc

**Comment by caesarxuchao** [comment]
I see. The tests are running in parallel.

Even with the locks, it's problematic, because the now() is a global variable, so setting it in one test will affect other tests. We should move `now()` to a field of reflector (kudos to @mikedanese for this bright idea!).

**Comment by wojtek-t** [comment]
Yeah - I guess it's a good idea. Will fix that on Monday.
Thanks @caesarxuchao

**Comment by wojtek-t** [comment]
@caesarxuchao - PTAL

**Comment by caesarxuchao** [comment]
LGTM. Thank you!

**Pull request merged**
