### PR TITLE
Automated cherry pick of #37593

### PR DESCRIPTION
**Pull request by yujuhong**
Cherry pick of #37593 on release-1.5.

#37593: GCI: Remove /var/lib/docker/network

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37863)

**Comment by dchen1107** [comment]
LGTM

**Comment by saad-ali** [comment]
@k8s-bot kubemark e2e test this

**Comment by yujuhong** [comment]
@k8s-bot kubemark e2e test this

**Comment by yujuhong** [comment]
@k8s-bot kops aws e2e test this

**Comment by saad-ali** [comment]
@k8s-bot kops aws e2e test this

**Comment by saad-ali** [comment]
@k8s-bot kubemark e2e test this

**Pull request merged**
