### PR TITLE
propose ResourceAccessReview: which users can perform this action

### PR DESCRIPTION
**Pull request by deads2k**
Existing authorization does not provide a way to know which users and groups have rights to perform an action.  ResourceAccessReview is a  way to determine the full list of of all users and groups who can do something.  This capability is useful when trying to answer questions like: which users have rights to my namespace.

cc @derekwaynecarr @smarterclayton @liggitt

### CODE REVIEW

**Comment by smarterclayton** [comment]
Who implements this endpoint?  The authorization engine backing authz decisions?  How would someone implement this outside of Kube?

**Comment by smarterclayton** [comment]
This is related to #3730

**Comment by smarterclayton** [comment]
This needs more detail about the why in the change.  The questions above are things that should be answered in the update to the authorization.md design.

**Comment by erictune** [comment]
Both this and subject-access-review could be implemented outside of the
apiserver by a "policy helper service" which watches all the policy objects
stored on the api server, and then is able to answer SubjectAccessReview
and ResourceAccessReview types of questions.

In general, I think we have a sort of tacit agreement that we will avoid
putting functionality into the apiserver that can easily be implemented out
of it.  If openshift wants to bundle the "policy helper service" in the
same binary as a bunch of other stuff, and even run it in the same process
as other things, like the scheduler and control loops, that's fine too.

**Comment by deads2k** [comment]
superseded by #3759

**Pull request closed without merging**
