### PR TITLE
More code-review changes from k/utlils cpuset review

### PR DESCRIPTION
**Pull request by iancoolidge**
More preparation for cpuset to be moved into k/utils

Small second round code review changes before import in https://github.com/kubernetes/utils/pull/267

https://github.com/kubernetes/kubernetes/issues/112899

/kind cleanup

### CODE REVIEW

**Comment by bart0sh** [comment]
@iancoolidge please consider adding/modifying test cases for uncovered module code. At least `Clone` is not covered and `IsSubsetOf` is not fully covered as far as I can see.

**Comment by iancoolidge** [comment]
> @iancoolidge please consider adding/modifying test cases for uncovered module code. At least `Clone` is not covered and `IsSubsetOf` is not fully covered as far as I can see.

Done

**Comment by cici37** [comment]
/lgtm
/assign @derekwaynecarr 
for approval. Thanks

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Pull request merged**
