### PR TITLE
fix: update comment for related updated func

### PR DESCRIPTION
**Pull request by HecarimV**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
update comment for related updated func 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Review by sanposhiho — APPROVED** [review]
/lgtm

**Comment by kerthcet** [comment]
Thanks @HecarimV for fix this. Forget to update the comment in https://github.com/kubernetes/kubernetes/pull/109519.
/retest

**Review by damemi — COMMENTED** [review]
/approve

**Pull request merged**
