### PR TITLE
Delete duplicated words in logs

### PR DESCRIPTION
**Pull request by mooncak**
Signed-off-by: mooncake <xcoder@tenxcloud.com>

**What this PR does / why we need it**:
Delete duplicated words in logs

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
/kind cleanup

Re-triggering the label fix:
/remove-sig node

**Comment by nikhita** [comment]
/ok-to-test
/lgtm

/assign @yujuhong 
for approval

**Comment by mooncak** [comment]
@nikhita could you help approve this? tks

**Comment by nikhita** [comment]
@yujuhong could you also approve?

**Comment by yujuhong** [comment]
Sorry...forgot lgtm no longer means approve
/approve

**Pull request merged**
