### PR TITLE
test: partially decouple from cmd/kubeadm

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:
test: partially decouple from cmd/kubeadm

The test package imports cmd/kubeadm, which is far from ideal.
There are a couple of reasons for the import:
1) Marshaling of Ingress from api/extensions/v1beta1.

To fix that include a local function in e2e/manifest/manifest.go
that does that same as the kubeadm MarshalToYaml.

2) Using PKI helper function in apimachinery and auth tests.

To fix that include a new file under test/utils/pki_helpers.go
that only contains the required helpers instead of including the whole
kubeadm pkiutil package.

There is another related problem:
e2e_node/e2e_node_suite_test.go includes:
k8s.io/kubernetes/cmd/kubeadm/app/util/system

But this has to be done in a follow up.

**Which issue(s) this PR fixes**:

xref https://github.com/kubernetes/kubernetes/issues/75601

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/assign @timothysc @oomichi 
@kubernetes/sig-auth-pr-reviews 
@kubernetes/sig-api-machinery-pr-reviews 
/kind cleanup
/priority important-longterm

### CODE REVIEW

**Comment by liggitt** [comment]
auth changes lgtm

**Review by MrHohn — APPROVED** [review]
LGTM for the Ingress manifest part.

**Comment by oomichi** [comment]
Thanks for doing this. `test/e2e/framework/pkiutil/pki_helpers.go` seems clean and useful for removing the dependency.
One idea is, how about implementing pki_helpers.go under `test/utils` instead?
Now `test/integration/examples/apiserver_test.go` also uses pkiutil functions which all are covered with this new module. So I guess we can reuse this for integration tests also.

**Comment by neolit123** [comment]
> One idea is, how about implementing pki_helpers.go under test/utils instead?
Now test/integration/examples/apiserver_test.go also uses pkiutil functions which all are covered with this new module. So I guess we can reuse this for integration tests also.

SGMT. i was considering cleaning cmd/kubeadm from /test too.

will update tomorrow.
/hold

**Comment by neolit123** [comment]
@oomichi 

> One idea is, how about implementing pki_helpers.go under test/utils instead

i have updated the PR to include this change.
thinking more about it, we might want to make test/framework decoupled from /test too, eventually, because if we break out the framework only into a separate repo it will be a problem.

in terms of cmd/kubeadm usage in /test there is one remaining but we need permission/discussion for it first:
`e2e_node/e2e_node_suite_test.go:41:	"k8s.io/kubernetes/cmd/kubeadm/app/util/system"`

**Comment by oomichi** [comment]
@neolit123 Thanks for updating

> thinking more about it, we might want to make test/framework decoupled from /test too, eventually, 
> because if we break out the framework only into a separate repo it will be a problem.

That is a nice point.
It is nice to think what dependencies we want to remove from test/e2e/framework.
At this time, I am fine for current one.

/lgtm

**Review by timothysc — APPROVED** [review]
/approve

**Pull request merged**
