### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
fix some typo of identifier
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jianglingxia** [comment]
PTAL @liggitt 
/assign @thockin

**Comment by liggitt** [comment]
/lgtm cancel

generated docs need updating. please run `hack/update-all.sh` and check in updated docs

**Comment by thockin** [comment]
@jianglingxia ping

**Comment by jianglingxia** [comment]
sorry，There's no way to solve it in my environment，I close it so!

**Pull request closed without merging**
