### PR TITLE
Remove unnecessary type conversion

### PR DESCRIPTION
**Pull request by sourcelliu**
#### What type of PR is this?
/kind cleanup
/sig node
/area kubelet

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Remove unnecessary  type conversion in pkg/kubelet.
#116902 This scan and modify the entire kubelet package. 
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sourcelliu** [comment]
@bart0sh PTAL.  This time scan and modify the entire kubelet package, refer to #116902.

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
