### PR TITLE
Fix a bug in node tree when all nodes in a zone are removed

### PR DESCRIPTION
**Pull request by bsalamat**
This is a cherrypick of #69758. Please refer to that PR for more info.

**Release note**:

```release-note
Fix a bug in the scheduler that could cause the scheduler to go to an infinite loop when all nodes in a zone are removed.
```

/sig scheduling
/kind bug

### CODE REVIEW

**Comment by feiskyer** [comment]
ping original reviewer @k82cn

**Review by ravisantoshgudimetla — APPROVED** [review]
/lgtm

**Comment by k82cn** [comment]
LGTM :)

**Comment by feiskyer** [comment]
cherry pick approved

**Pull request merged**
