### PR TITLE
Revert SQ-blocking PR (on custom-resource GC)

### PR DESCRIPTION
**Pull request by shyamjvs**
Reverts kubernetes/kubernetes#47665

Reverting instead of removing the integration test (ref: https://github.com/kubernetes/kubernetes/pull/49944)

/cc @k8s-oncall @wojtek-t @caesarxuchao @ironcladlou

### CODE REVIEW

**Comment by shyamjvs** [comment]
There are no new commits since 2 hrs. And the test started flaking since ~2 AM PST (as @MaciekPytel identified).
It might be some other change on top of it that's breaking the integration test.

**Comment by liggitt** [comment]
the PR has been in for three days... it seems like something else just went in to completely block the queue

**Comment by shyamjvs** [comment]
Yup.. @MaciekPytel and me are looking into it. However it's only this integration test that's failing.

**Comment by ironcladlou** [comment]
I see this failure: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49382/pull-kubernetes-unit/43834/ which is unrelated to the GC PR... is that one already resolved somehow?

**Comment by MaciekPytel** [comment]
Agreed, I don't think it's related to this pr. It started flaking at 5pm PST (2 am CEST), which matches batch merge of 5 unrelated PRs (one of which is comments only). I'm trying to figure out if any of those is the culprit.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/49919 will fix the "duplicate metrics registration" error

**Comment by shyamjvs** [comment]
The downward API being broken, that's probably the reason:

```
E0801 11:25:58.867224   31821 serving.go:189] Couldn't create in cluster config due to unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined. SharedInformerFactory will not be set.
```

**Comment by liggitt** [comment]
> The downward API being broken, that's probably the reason:

That log is misleading... if you look in the stdout of the job, that snippet isn't related to the failing tests

**Comment by ironcladlou** [comment]
I looked at the [very first](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49846/pull-kubernetes-unit/43644#k8siokubernetestestintegrationgarbagecollector-testcrddeletioncascading) failure post merge and one of the [latest](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49846/pull-kubernetes-unit/43644#k8siokubernetestestintegrationgarbagecollector-testcrddeletioncascading), and one common thread is some sort of issue with `crd_finalizer` that always looks something like this:

```
E0730 07:57:00.095632   31034 controller.go:162] unable to sync kubernetes service: Timeout: request did not complete within allowed duration
E0730 07:57:10.584490   31034 crd_finalizer.go:278] fooltqzss.mygroup.example.com failed with: missing requestInfo
E0730 07:57:10.593758   31034 crd_finalizer.go:278] fooltqzss.mygroup.example.com failed with: missing requestInfo
E0730 07:57:10.607273   31034 crd_finalizer.go:278] fooltqzss.mygroup.example.com failed with: missing requestInfo
E0730 07:57:10.630693   31034 crd_finalizer.go:278] fooltqzss.mygroup.example.com failed with: missing requestInfo
```

This happens during the test bootstrapping and before any real test logic is executed. Still digging...

**Comment by ironcladlou** [comment]
Re: https://github.com/kubernetes/kubernetes/pull/49946#issuecomment-319369208
>This happens during the test bootstrapping and before any real test logic is executed. Still digging...

I might be wrong about the "before any real test logic" part... without https://github.com/kubernetes/kubernetes/pull/49886 to fix the logging verbosity I can't be sure the GC isn't doing any work.

**Comment by ironcladlou** [comment]
Here's a [test run from July 25](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49183/pull-kubernetes-unit/42723/) failing for the same reasons being ascribed to https://github.com/kubernetes/kubernetes/pull/47665 in this PR. Whatever problem exists with the CRD finalizer in the July 25 test predates https://github.com/kubernetes/kubernetes/pull/47665 and indeed seem to be now causing problems with the new GC tests (because they also rely on the CRD finalizer).

I'm not yet seeing any evidence of the GC PR being the culprit. Did I miss something?

**Comment by ironcladlou** [comment]
Note that the `TestMixedRelationships` flake was [already identified](https://github.com/kubernetes/kubernetes/pull/47665#discussion_r130266845) and has a [logging PR](https://github.com/kubernetes/kubernetes/pull/49886) to help track it down. The "missing requestInfo" error from crd_finalizer.go is what's messing up the both GC and non-GC related CRD tests, and has been since July 25.

**Comment by liggitt** [comment]
> The "missing requestInfo" error from crd_finalizer.go is what's messing up the both GC and non-GC related CRD tests, and has been since at least July 25 (#49946 (comment)).

That specific error is only in pull CI, and appears to be an error in a particular set of PRs (which have not merged, because they are failing CI on that error).

TestClientGoCustomResourceExample started flaking in master after https://github.com/kubernetes/kubernetes/commit/74b9ba3b4d7c6f0a116464ac01a5f98b915d4586 was merged, before https://github.com/kubernetes/kubernetes/pull/47665 was merged. That test depends on list/watching a custom resource. The GC PR merged later that day also added tests that depend on list/watching custom resources.

**Comment by shyamjvs** [comment]
Closing this PR in favor of issue https://github.com/kubernetes/kubernetes/issues/49956.
Let's continue further discussion there.

**Pull request closed without merging**
