### PR TITLE
kubeadm: update OWNERS for 1.16

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:
add @yastij to reviewers.
please `lgtm`.

**Which issue(s) this PR fixes**:

NONE

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/kind cleanup
/priority important-longterm
/hold

### CODE REVIEW

**Comment by ereslibre** [comment]
/lgtm

Welcome @yastij!

**Review by yastij — COMMENTED** [review]
/lgtm

**Review by rosti — APPROVED** [review]
/lgtm

**Review by fabriziopandini — APPROVED** [review]
/lgtm
Thanks @yastij for the great work on kubeadm!

**Pull request merged**
