### PR TITLE
Avoid closing over range variables

### PR DESCRIPTION
**Pull request by soltysh**
Similar to #31053.

@justinsb since you authored the original one, ptal

### CODE REVIEW

**Comment by soltysh** [comment]
@k8s-bot unit test this

**Comment by justinsb** [comment]
This isn't technically required though, is it?  We aren't closing over it (I think) - though maybe we should be..

Do you have a linter that triggered here?  I'm all in favor of having more linters...

**Comment by soltysh** [comment]
We are, although just in the error message in line 48.

**Comment by justinsb** [comment]
I'm so confused... I see line 48 as:

```
 					return "", "", fmt.Errorf("field label not supported: %s", label)
```

Based on the other examples, I think maybe it should have kind in it, but it doesn't seem to...

**Comment by soltysh** [comment]
You're right, I was looking into sources in other place, but it should be there. I'll update right away.

**Comment by soltysh** [comment]
Updated.

**Comment by justinsb** [comment]
LGTM - thanks!

**Comment by soltysh** [comment]
@k8s-bot bazel kops aws e2e test this

**Comment by soltysh** [comment]
@k8s-bot kops aws e2e test this

**Comment by soltysh** [comment]
Re-applying the lgtm label back.

**Comment by soltysh** [comment]
@k8s-bot cri e2e test this

**Pull request merged**
