### PR TITLE
Pass ListOptions to List in ListWatch.

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #15945

This will allow passing "0" resourceVersion to List() operation in our frameworks (Reflector, Informer, etc.)

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM, thanks for cleanup!

**Comment by wojtek-t** [comment]
>
LGTM, thanks for cleanup!

Thanks - yeah - we have much more consistent interfaces now...

**Comment by wojtek-t** [comment]
trivial rebase (there was a new call with old syntax).

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
cluster didn't started

@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
Manually merging to unblock different experiments.

**Pull request merged**
