### PR TITLE
Automated cherry pick of #73016: Bump the pod memory to higher levels to work on power

### PR DESCRIPTION
**Pull request by mikebrow**
Cherry pick of #73016 on release-1.10.

#73016: Bump the pod memory to higher levels to work on power

### CODE REVIEW

**Comment by mikebrow** [comment]
need this cherry picked due to the runc memory issue created by mitigation of recent CVE.. https://github.com/opencontainers/runc/issues/1980

@yujuhong

**Comment by Random-Liu** [comment]
@MaciekPytel  Can you take a look please? Thanks!

**Comment by MaciekPytel** [comment]
Kubernetes community only supports last 3 versions and 1.10 has reached end-of-life in mid-December. There will be no more 1.10 patch releases and no more cherry-picks will be merged. 

1.10.13 was an exception that was approved by sig-release leadership. The criteria for PR to get a similar exception are mentioned in https://github.com/kubernetes/sig-release/issues/450. Given this seems to be a test fix I don't think it qualifies, please re-open if you disagree.

**Pull request closed without merging**
