### PR TITLE
pkg/client/doc.go: update example to make it compile

### PR DESCRIPTION
**Pull request by pkern**
The client example does not compile (double pointer to config, missing import, List() returning two values); fix it.

### CODE REVIEW

**Comment by pkern** [comment]
I am a Google employee and now at a loss as to what to state on the CLA interface. :)

**Comment by krousey** [comment]
@ixdy any idea why the CLA bot is failing?

**Comment by ixdy** [comment]
Discussed in person, but for history: the commit is signed with an @debian.org address instead of @google.com.

**Comment by caesarxuchao** [comment]
LGTM.

**Pull request merged**
