### PR TITLE
Fix poll to not fail on first error

### PR DESCRIPTION
**Pull request by bprashanth**
Fixes https://github.com/kubernetes/kubernetes/issues/35225
I hope. No repro locally.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35248)

### CODE REVIEW

**Comment by bprashanth** [comment]
@spxtr trap is green, would be good to get this in before the weekend

**Comment by bprashanth** [comment]
Simple review, co-assigning to @MrHohn

**Comment by MrHohn** [comment]
So is the bug that we should return `nil` error from the ConditionFunc of `PollImmediate()` when fail, otherwise `PollImmediate()` gonna return error at the first failure?

LGTM.

**Comment by bprashanth** [comment]
@MrHohn yes, thanks, applying label.

**Comment by spxtr** [comment]
LGTM

**Pull request merged**
