### PR TITLE
Update some event types

### PR DESCRIPTION
**Pull request by NickrenREN**
**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by NickrenREN** [comment]
@madhusudancs  @nikhiljindal  PTAL

**Comment by nikhiljindal** [comment]
Thanks!
Would have been better if the PR description had more details.

Code changes lgtm.

/lgtm
/approve

**Comment by NickrenREN** [comment]
@nikhiljindal  Thanks. I will pay attention to that next time.

**Pull request merged**
