### PR TITLE
Add error log for 'no rollbacker has been implemented for ReplicationController'

### PR DESCRIPTION
**Pull request by taragu**
Fixing issue #69106 

/sig testing
/area test
/kind cleanup
/assign @BenTheElder 

**Does this PR introduce a user-facing change?**: No

```release-note
NONE
```

### CODE REVIEW

**Comment by taragu** [comment]
@adohe @derekwaynecarr have you guys looked at this PR yet? any suggestion will be greatly appreciated. thank you in advance! 🙂

**Comment by BenTheElder** [comment]
/ok-to-test
You should add this to the end of the PR opening comment:

\```release-note
NONE
\```

**Comment by BenTheElder** [comment]
I don't know enough about these scripts, we should get @kubernetes/sig-cli-maintainers to review

**Comment by liggitt** [comment]
I think what https://github.com/kubernetes/kubernetes/issues/69106 was asking for was a backtrace printed in test failures that showed what line the test failed on, not a hard coded error message comparison for this one spot

**Comment by enj** [comment]
> I think what #69106 was asking for was a backtrace printed in test failures that showed what line the test failed on, not a hard coded error message comparison for this one spot

Yeah, that was my intent.

**Comment by taragu** [comment]
@enj ah I see. So would you like to add information like
```
I0926 01:04:33.532] has not:no rollbacker has been implemented for {"" "ReplicationController"}
I0926 01:04:33.533] 433 /go/src/k8s.io/kubernetes/test/cmd/../../test/cmd/generic-resources.sh
```
to the call tree?

**Comment by stevekuznetsov** [comment]
@BenTheElder @ixdy might have reviews on the bash as well :)

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Comment by BenTheElder** [comment]
Thanks for tackling this :-)

**Pull request merged**
