### PR TITLE
[experimental] Use reflector in server side apply to avoid converting to unstructured

### PR DESCRIPTION
**Pull request by jpbetz**
This picks up https://github.com/jpbetz/structured-merge-diff/tree/reflect-experiment which has a very basic reflector based implementation of the `value.Value` interface. It is used in the fieldmanager convert functions.

cc @jennybuckley @apelisse

### CODE REVIEW

**Comment by BenTheElder** [comment]
needs a `hack/update-bazel.sh`

**Comment by jpbetz** [comment]
> needs a `hack/update-bazel.sh`

Thanks. Done.

**Comment by jpbetz** [comment]
This is superseded by https://github.com/jpbetz/kubernetes/tree/reflector-smd

**Pull request closed without merging**
