### PR TITLE
remove defaulting from conversion path

### PR DESCRIPTION
**Pull request by liggitt**
follow up for #42764

* remove call to defaulting from conversion path (defaulting is a separate step from conversion)
* remove non-top-level-object defaulting registration (unused after conversion call is removed)
* generate missing top-level defaults for some api groups:
  * autoscaling/v2alpha1
  * policy/v1alpha1
  * policy/v1beta1
* register top-level defaults for some api groups that were missing them:
  * autoscaling/v2alpha1
  * settings/v1alpha1

### CODE REVIEW

**Comment by ethernetdan** [comment]
@k8s-bot bazel test this
@k8s-bot unit test this
@k8s-bot kops aws e2e test this

**Comment by liggitt** [comment]
Still WIP, tests need updating

**Comment by liggitt** [comment]
this should still be done, but I'd like more soak time on it, so I'm moving this to 1.7.

I opened https://github.com/kubernetes/kubernetes/pull/42944 for 1.6 instead, that just fixes the patch defaulting issue

**Comment by wojtek-t** [comment]
@liggitt - do you think we can now proceed with this one?

**Comment by liggitt** [comment]
yes, picking this back up now

**Comment by smarterclayton** [comment]
Looks ok to me.

**Comment by wojtek-t** [comment]
The //pkg/api:go_default_xtest tes is failing, which definitely seems related to this PR.

**Comment by liggitt** [comment]
```
I0412 10:55:55.382] Verifying hack/make-rules/../../hack/verify-generated-protobuf.sh
I0412 10:55:55.753] +++ [0412 10:55:55] Verifying Prerequisites....
I0412 10:55:57.326] +++ [0412 10:55:57] Building Docker image kube-build:build-781be6bdb5-5-v1.7.5-3
I0412 10:56:02.513] +++ [0412 10:56:02] Keeping container amazing_kowalevski
I0412 10:56:02.515] +++ [0412 10:56:02] Keeping container kube-build-data-5a6917f06d-5-v1.7.5-3
I0412 10:56:02.568] +++ [0412 10:56:02] Keeping container amazing_kowalevski
I0412 10:56:02.569] +++ [0412 10:56:02] Keeping container kube-build-data-5a6917f06d-5-v1.7.5-3
I0412 10:56:02.620] +++ [0412 10:56:02] Keeping container amazing_kowalevski
I0412 10:56:02.621] +++ [0412 10:56:02] Keeping container kube-build-data-5a6917f06d-5-v1.7.5-3
I0412 10:56:02.772] +++ [0412 10:56:02] Keeping image kube-build:build-781be6bdb5-5-v1.7.5-3
I0412 10:56:02.774] +++ [0412 10:56:02] Keeping image kube-build:build-5a6917f06d-5-v1.7.5-3
I0412 10:56:02.775] +++ [0412 10:56:02] Keeping image kube-build:build-30d75cdf9d-5-v1.7.5-3
I0412 10:56:02.941] +++ [0412 10:56:02] Creating data container kube-build-data-781be6bdb5-5-v1.7.5-3
I0412 10:56:23.123] +++ [0412 10:56:23] Syncing sources to container
I0412 10:56:23.131] +++ [0412 10:56:23] Stopping any currently running rsyncd container
I0412 10:56:23.242] +++ [0412 10:56:23] Starting rsyncd container
W0412 10:56:28.403] !!! [0412 10:56:28] Could not connect to rsync container. See build/README.md for setting up remote Docker engine.
W0412 10:56:28.406] !!! [0412 10:56:28] Call tree:
W0412 10:56:28.408] !!! [0412 10:56:28]  1: /go/src/k8s.io/kubernetes/hack/../build/../build/common.sh:425 kube::build::sync_to_container(...)
W0412 10:56:28.409] !!! [0412 10:56:28]  2: /go/src/k8s.io/kubernetes/hack/../build/run.sh:29 kube::build::build_image(...)
I0412 10:56:28.510] FAILED   hack/make-rules/../../hack/verify-generated-protobuf.sh	33s
```
@k8s-bot verify test this

**Pull request merged**
