### PR TITLE
[DO NOT MERGE] Bump up godep of etcd to use V3 API

### PR DESCRIPTION
**Pull request by hongchaodeng**
ref: #22604 

Follow up to the request to move godep update to separate PR.

One thing to note:
- etcd **server** isn't supported on 32 bit machines.
- k8s will import etcd **server** dependencies for unit testing. Please use 64 bit machines for unit testing.
- etcd **client** should be OK on 32 bit platforms. I think this will be built by k8s server binaries.

### CODE REVIEW

**Comment by bgrant0607** [comment]
Let's not merge this until we have a better idea where we are with respect to 1.2.

**Comment by timothysc** [comment]
@hongchaodeng 
Could you breakout the commits such that there is "storage" then "godep" commit.  It would be much easier to review then.

**Comment by hongchaodeng** [comment]
@timothysc 
I'm not sure I catch that. You mean in godep separating out per directory dependencies?

**Comment by hongchaodeng** [comment]
@bgrant0607 

No worries. We won't actually commit something before 1.2 release :) The goal of submission is to see how we should review such huge changes. At the mean time, we will be pretty busy watching AlphaGo...

**Comment by bgrant0607** [comment]
hack/verify-godeps.sh failed

**Comment by bgrant0607** [comment]
@timothysc This PR does have 2 commits.

**Comment by aveshagarwal** [comment]
Its a little bit confusing as this PR seems to be having overlapping commits with https://github.com/kubernetes/kubernetes/pull/22604 . Seems like @timstclair might be looking for the commit in https://github.com/kubernetes/kubernetes/pull/22604: https://github.com/hongchaodeng/kubernetes/commit/af90a13f0a14bc3ff8f17a787397bfa6ad6c27b7

**Comment by aveshagarwal** [comment]
I am sorry I meant @timothysc

**Comment by wojtek-t** [comment]
@aveshagarwal - yet, but it's expected, as I requested for factoring out dependency update to a separate PR:
https://github.com/kubernetes/kubernetes/pull/22604#issuecomment-193138614

**Comment by timothysc** [comment]
@hongchaodeng I'm not seeing a "here are all the associated storage layer changes, including new impl" - commit , then "here is the godep" - commit.

**Comment by hongchaodeng** [comment]
@timothysc 
See https://github.com/kubernetes/kubernetes/pull/22604/

**Comment by timothysc** [comment]
@hongchaodeng much better, thx.

**Comment by hongchaodeng** [comment]
Closing this and submit changes later

**Comment by hongchaodeng** [comment]
@wojtek-t @timothysc 
Let's move the discussion back to #22604 . Splitting godeps only will trigger hack/verify-godeps.sh to fail.

**Pull request closed without merging**
