### PR TITLE
Fixing Node Allocatable dead link

### LINKED ISSUE #114019: Dead link for "Node Allocatable" in doc page Kubelet Configuration (v1beta1)
The link to documentation on ["Node Allocatable"](https://git.k8s.io/community/contributors/design-proposals/node/node-allocatable.md) is dead. The page was autogenerated. 

I found a document with the same name within the Kubernetes project [as an archived repo](https://github.com/kubernetes/design-proposals-archive/blob/main/node/node-allocatable.md).

Please update the link or remove the reference if it's no longer relevant.

Source webpage: https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/

### PR DESCRIPTION
**Pull request by nitishchauhan0022**
#### Which issue(s) this PR fixes:
Fixes #114019

### CODE REVIEW

**Comment by ruquanzhao** [comment]
Does it also need fixing here?
(https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go#L108)

**Comment by nitishchauhan0022** [comment]
@ruquanzhao Thanks for pointing it out, it is also not working. I have added that.

**Review by mrunalp — APPROVED** [review]

**Comment by vaibhav2107** [comment]
@nitishchauhan0022 Could you please rebase your PR

**Comment by nitishchauhan0022** [comment]
closing this pr, changes are added by #115604
/close

**Pull request closed without merging**
