### PR TITLE
dependencies: bump k8s.io/utils

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This includes a fix for [a race condition](https://github.com/kubernetes/utils/pull/279).

#### Does this PR introduce a user-facing change?
```release-note
Recording timing traces had a race condition. Impact in practice was probably low.
```

### CODE REVIEW

**Comment by jingxu97** [comment]
@pohly there is a merge conflict.

**Comment by pohly** [comment]
/assign @liggitt 

For dep approval in staging/src/k8s.io/api.

**Comment by pohly** [comment]
pull-kubernetes-kind-dra failing is a known, unrelated issue.

**Comment by dims** [comment]
/skip 

(unrelated failure)

**Pull request merged**
