### PR TITLE
[1.19][go1.15] Update to go1.15.2

### PR DESCRIPTION
**Pull request by justaugustus**
**What type of PR is this?**

/kind feature
/area dependency

**What this PR does / why we need it**:

(Cherry pick of https://github.com/kubernetes/kubernetes/pull/94449)

- Update to go1.15.2
- build: Update to k/repo-infra@v0.1.1 (supports go1.15.2)
- build: Use go-runner:buster-v2.0.1 (built using go1.15.1)
- bazel: Replace --features with Starlark build settings flag
- hack/lib/util.sh: some bash cleanups
  
  - switched one spot to use kube::logging
  - make kube::util::find-binary return an error when it doesn't find
    anything so that hack scripts fail fast instead of with '' binary not
    found errors.
  - this required deleting some genfeddoc stuff. the binary no longer
    exists in k/k repo since we removed federation/, and I don't see it
    in https://github.com/kubernetes-sigs/kubefed/ either. I'm assuming
    that it's gone for good now.

- bazel: output go_binary rule directly from go_binary_conditional_pure
  
  From: @mikedanese:
  Instead of aliasing. Aliases are annoying in a number of ways. This is
  specifically bugging me now because they make the action graph harder to
  analyze programmatically. By using aliases here, we would need to handle
  potentially aliased go_binary targets and dereference to the effective
  target.

  The comment references an issue with `pure = select(...)` which appears
  to be resolved considering this now builds.

- make kube::util::find-binary not dependent on bazel-out/ structure

  Implement an aspect that outputs go_build_mode metadata for go binaries,
  and use that during binary selection.

Tracking issue: https://github.com/kubernetes/release/issues/1517
ref: https://github.com/kubernetes/release/pull/1514, https://github.com/kubernetes/k8s.io/pull/1205, https://github.com/kubernetes/release/pull/1516
cc: @kubernetes/release-engineering 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

/hold I want to push an updated go-runner image with this as well

**Does this PR introduce a user-facing change?**:

```release-note
- Kubernetes is now built using go1.15.2
- build: Update to k/repo-infra@v0.1.1 (supports go1.15.2)
- build: Use go-runner:buster-v2.0.1 (built using go1.15.1)
- bazel: Replace --features with Starlark build settings flag
- hack/lib/util.sh: some bash cleanups
  
  - switched one spot to use kube::logging
  - make kube::util::find-binary return an error when it doesn't find
    anything so that hack scripts fail fast instead of with '' binary not
    found errors.
  - this required deleting some genfeddoc stuff. the binary no longer
    exists in k/k repo since we removed federation/, and I don't see it
    in https://github.com/kubernetes-sigs/kubefed/ either. I'm assuming
    that it's gone for good now.

- bazel: output go_binary rule directly from go_binary_conditional_pure
  
  From: @mikedanese:
  Instead of aliasing. Aliases are annoying in a number of ways. This is
  specifically bugging me now because they make the action graph harder to
  analyze programmatically. By using aliases here, we would need to handle
  potentially aliased go_binary targets and dereference to the effective
  target.

  The comment references an issue with `pure = select(...)` which appears
  to be resolved considering this now builds.

- make kube::util::find-binary not dependent on bazel-out/ structure

  Implement an aspect that outputs go_build_mode metadata for go binaries,
  and use that during binary selection.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by justaugustus** [comment]
/hold cancel
(I'll look at the go-runner update in a follow-up.)

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
