### PR TITLE
Add a validation step to add-on resource monitoring

### PR DESCRIPTION
**Pull request by gmarek**
Ref #16050

cc @davidopp @wojtek-t @rrati @timothysc @yujuhong @mwielgus

### CODE REVIEW

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by wojtek-t** [comment]
LGTM

**Comment by gmarek** [comment]
Simple rebase. Reapplying LGTM.

**Comment by fabioy** [comment]
This PR seems to have caused kubemark-gce Jenkins to go red:

Density [Skipped] [Performance] should allow starting 30 pods per node

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/density.go:432 Expected error: <*errors.errorString | 0xc20a85e570>: { s: "Only 0 pods started out of 3000", } Only 0 pods started out of 3000 not to have occurred

I'm going to revert this and see if it clears up Jenkins.

**Comment by fabioy** [comment]
Or maybe note. Looks like kubemark had a few sucessful runs with this change before it went red (looking at merge time vs. test run time). Will keep digging.

**Comment by timothysc** [comment]
@rrati we should validate this one

**Comment by fabioy** [comment]
Looking at test logs, all pods are scheduled, but they remain in the "Pending" state forever. Trying to get kubelet logs from a node when in this state.

**Pull request merged**
