### PR TITLE
cleanup:e2e:stop using deprecated wait.ErrWaitTimeout

### PR DESCRIPTION
**Pull request by shijinye**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
cleanup:e2e:stop using deprecated wait.ErrWaitTimeout

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/pull/107826

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by alexzielenski** [comment]
/cc @jefftree
could you review the apimachinery changes
/triage accepted

**Comment by Jefftree** [comment]
/retest
flake: https://github.com/kubernetes/kubernetes/issues/119600

**Comment by Jefftree** [comment]
Looks reasonable
/lgtm
/assign @sttts

**Pull request merged**
