### PR TITLE
Update godep for github.com/spf13/pflag and replace StringSlice with String Array in configMap

### PR DESCRIPTION
**Pull request by wu8685**
Update godep for pkg `github.com/spf13/pflag`, because the new flag type `StringArray` within it is needed in issue #27454

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33263)

### CODE REVIEW

**Comment by AdoHe** [comment]
@eparis I think you may want to review this.

**Comment by eparis** [comment]
/lgtm
not sure I've ever gotten this to work....

**Comment by eparis** [comment]
@k8s-bot ok to test

**Comment by wu8685** [comment]
@k8s-bot kubemark gci e2e test this

**Comment by wu8685** [comment]
I combined the commit in which replace StringSlice with StringArray.
Recently I just replace it in configMap.

**Pull request merged**
