### PR TITLE
Combine downward api e2e test cases.

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
This will reduce one loop of create/delete pod. Hope it can save some test time.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ixdy** [comment]
/assign @nhlfr 
@kubernetes/sig-node-pr-reviews

**Comment by xiangpengzhao** [comment]
kindly ping :)

**Review by timothysc — APPROVED** [review]

**Pull request merged**
