### PR TITLE
Add support for consuming whole NUMA nodes in CPUManager CPU assignments

### PR DESCRIPTION
**Pull request by klueska**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The algorithm used to make CPU allocations in the CPUManager currently assumes that sockets have a 1:1 mapping with NUMA nodes. This is not true in the general case, however, and this PR updates the algorithm to account for this.

NUMA is a little different than the existing `socket --> core --> cpu` relationship, in that NUMA can fit into this hierarchy in one of 2 places, either as `numa --> socket --> core --> cpu` or `socket --> numa --> core --> cpu`. This PR takes both of these situations into account and makes sure to perform its CPU allocations appropriately.

#### Release notes:
```release-note
Support allocating whole NUMA nodes in the CPUManager when there is not a 1:1 mapping between socket and NUMA node
```

### CODE REVIEW

**Comment by fromanirh** [comment]
/triage accepted
/priority backlog
I'll be reviewing ASAP

**Comment by klueska** [comment]
@fromanirh I will not be comfortable merging this until I have a comprehensive set of tests written for the new functionality. Unfortunately, I do not have the bandwidth right now to add these. If you have some time and want to put these tests together, I can cherry-pick them into my branch and we can merge it from there.

**Comment by fromanirh** [comment]
> @fromanirh I will not be comfortable merging this until I have a comprehensive set of tests written for the new functionality. Unfortunately, I do not have the bandwidth right now to add these. If you have some time and want to put these tests together, I can cherry-pick them into my branch and we can merge it from there.

I'll be happy to write tests, it's a great opportunity to deep dive into the fine details of the code. This also enables me to perform a better review. I think is worth checking if e2e tests could help here as well.

**Comment by fromanirh** [comment]
begun work on https://github.com/kubernetes/kubernetes/pull/102496 - just a placeholder atm. I will ping as soon as I have enough material

**Comment by klueska** [comment]
/approve for the core changes (i.e. not the `api` or `feature` changes)

The only open question on this front is whether we want to introduce a *new* policy to which the new `policy flags` apply, or just have them apply to the existing `static` policy (and any future policies, as appropriate).

This discussion was started because @kad suggested during the KEP review that it might be preferable to not modify the behaviour of the existing `static` policy with these new `policy flags`. It was suggested there is at least one 3rd party tool that relies on the _internal_ behaviour of the static policy and only currently keys off of the policy name to see if this feature is turned on or not. With the introduction of these new `policy flags`, this his tool would need to modified to account for them. Otherwise it would risk inferring the wrong behaviour if the `static` policy + some set of `policy flags` was set in a future version of Kubernetes.

It was later clarified, however, that this tool doesn't actually _infer_ any internal behaviour. Instead, it "deploys clusters with specific topology/cpu manager options for AI specific setups". Meaning it decides if some set of `kubelet` flags are appropriate for a given cluster at deployment time.

After having thought about this for a while (and having considered the clarification mentioned above), I’m inclined *not* to introduce a new policy just to accommodate this new options flag.

The reasons being:
1. There is only one such tool we know of that may be affected by this
2. This tool appears to generate the desired set of flags it wants to apply to the kubelet (rather than infer the underlying CPU allocation algorithm based on the flags set)
3. If necessary, it should be fairly straightforward to write a conditional statement to check for the presence of the new options flag (without checking specific K8s version numbers).
4. This feature is still in alpha -- if we discover that this is more of an issue than I think it is, we can revisit it before this feature goes beta

Please add comments if you still have any concerns about this.

**Review by klueska — COMMENTED** [review]
I re-reviewed the code for the implementation, and it still seems to be OK from my perspective. I left a few comments on the tests for @fromanirh though.

**Comment by fromanirh** [comment]
image

yet reported as failed? :\

**Comment by klueska** [comment]
@fromanirh just rebased on master to see if that helps.

**Comment by klueska** [comment]
This now /lgtm from my perspective.
Thanks to @fromanirh for help generating such comprehensive tests.

**Comment by fromanirh** [comment]
code changes /lgtm (again minor/nit comment inside), natural and clean extension of the existing codebase

**Review by swatisehgal — APPROVED** [review]
Having the ability to support systems where it is incorrect to assume the 1:1 mapping between sockets and NUMA nodes and allocating CPUs taking both NUMA nodes and CPUs sockets into consideration is a great addition to the code base.

Thanks @klueska @fromanirh for this improvement!
/lgtm

**Pull request merged**
