### PR TITLE
Enable go vet.

### PR DESCRIPTION
**Pull request by goltermann**

### CODE REVIEW

**Comment by goltermann** [comment]
@k8s-bot test this #24298

**Comment by goltermann** [comment]
@spxtr ready for cr

**Comment by spxtr** [comment]
Ah, race conditions :)

**Comment by goltermann** [comment]
@k8s-bot unit test this please: #23879

**Comment by goltermann** [comment]
@spxtr @krousey, green again, seeking lgtm

**Comment by goltermann** [comment]
@k8s-bot e2e test this issue #24483

**Comment by goltermann** [comment]
@k8s-bot e2e test this issue: #22719

**Comment by goltermann** [comment]
@k8s-bot e2e test this issue: #22719

**Comment by spxtr** [comment]
I'd just manually merge...

**Pull request merged**
