### PR TITLE
cleanup: omit comparison with bool constants

### PR DESCRIPTION
**Pull request by taoyounger**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
omit comparison with bool constants

Which issue(s) this PR fixes:
Fixes #

Does this PR introduce a user-facing change?
```
NONE
```

Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```
NONE
```

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by thockin** [comment]
@andrewsykim @cheftako @dims @liggitt 

If you all prefer we can leave this lint as-is?

**Comment by dims** [comment]
@thockin my ancient "c" based lizard brain says don't impose this new restriction ... but didn't want to stop it on my accord only

**Comment by liggitt** [comment]
I find the explicit comparison to bool clearer to read sometimes, especially in the dereference cases, so I wouldn't *forbid* people from writing it

**Comment by thockin** [comment]
I'm not against it, I was just going with the flow of lint and "idomatic go".  @pohly - you touched lint, what do you think?

**Comment by pohly** [comment]
I find the modified code from this PR without explicit comparison easier to read, so :+1: for merging this from me.

The corresponding check is gosimple S1002, which is enabled when asking for "hints":
```
ERROR: staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go:876:5: S1002: should omit comparison to bool constant, can be simplified to `schema.UniqueItems` (gosimple)
ERROR: 	if schema.UniqueItems == true {
ERROR: 	   ^
```

It's not required for new or modified code. I believe that is what @liggitt suggested ("I wouldn't forbid people from writing it").

**Comment by thockin** [comment]
So we bounce back to @dims and @liggitt - lint suggests to not do this.  This PR removes explicit comparison.  Should we abandon this PR?  Revert for cloud-providers?  Or remove that lint?

It's not cool for us to say one thing in lint and then block a PR which does what we said to do :)

**Comment by pohly** [comment]
> It's not cool for us to say one thing in lint and then block a PR which does what we said to do :)

What we say about "hints" is that developers should consider them when writing new code. We also agreed that fixing them in existing code might not be worth the churn. In https://kubernetes.slack.com/archives/CHGFYJVAN/p1690902243923879 I asked whether we need to provide better guidance to (potential) contributors, but got no responses.

IMHO it comes down to a case-by-case decision: is this PR useful enough to merge it and accept the code churn?

**Comment by thockin** [comment]
I don't love wishy-washy.  I think we should either merge this or drop the lint

**Comment by pohly** [comment]
Then let's merge it. I don't think there was any strong objection against it, just a "let's not force people to use this style", which we don't.

**Comment by pohly** [comment]
I'll also follow up on https://kubernetes.slack.com/archives/CHGFYJVAN/p1690902243923879 and propose a policy that we can follow in the future.

**Comment by thockin** [comment]
Still needs a a cloud-providers approval :)

**Pull request merged**
