### PR TITLE
Add more validation to rules.yaml

### PR DESCRIPTION
**Pull request by dims**
We need to better catch problems like the one we fixed in: 
https://github.com/kubernetes/kubernetes/pull/114193

Essentially a copy-paste error where had a branch pointing to staging/src/k8s.io/code-generator instead of staging/src/k8s.io/apimachinery

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### What type of PR is this?
/kind bug
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by xmudrii** [comment]
> Exception: copy/paste error `apimachinery` refers to `staging/src/k8s.io/code-generator`

The job is working as expected. Let’s try again now when #114193 is merged.
/retest

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

I’ll milestone the PR once rc.1 is out so that we’re on the safe side with the release.

**Review by nikhita — APPROVED** [review]
/lgtm

Thank you so much, @dims!

**Review by palnabarun — APPROVED** [review]
/lgtm

Thanks for this!

**Pull request merged**
