### PR TITLE
kubelet e2e: defer the close to after the error check

### PR DESCRIPTION
**Pull request by rphillips**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fixes a crash in the e2e kubelet test

**Which issue(s) this PR fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=1744422

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
thanks!

/lgtm

**Comment by cblecker** [comment]
/milestone 1.16

@lachie83 FYI. This fixes a bug in test code.

**Comment by cblecker** [comment]
/milestone v1.16

🤖

**Pull request merged**
