### PR TITLE
make RBAC escalation error message more useful

### LINKED ISSUE #65804: rbac error messages are incomprehensible and not helpful
/kind bug

**What happened**:
```
kubectl create -f clusterrole.yaml
```
```yaml
# https://github.com/kubernetes/helm/blob/master/docs/rbac.md
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  namespace: kube-system
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: tiller
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: installer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tiller-user
rules:
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: ["", "extensions"]
  resources: ["configmaps", "deployments", "pods", "services"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller-user-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tiller-user
subjects:
- kind: ServiceAccount
  name: installer
  namespace: default
```
The error I am getting is a large blob of unformatted text (not even json or yaml):
```
[PolicyRule{Resources:["pods/portforward"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["deployments"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["deployments"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["deployments"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["deployments"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["deployments"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["deployments"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["configmaps"], APIGroups:["extensions"], Verbs:["create"]} PolicyRule{Resources:["configmaps"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["configmaps"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["configmaps"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["configmaps"], APIGroups:["extensions"], Verbs:["update"]} PolicyRule{Resources:["configmaps"], APIGroups:["extensions"], Verbs:["delete"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["create"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["update"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["delete"]} PolicyRule{Resources:["pods"], APIGroups:["extensions"], Verbs:["create"]} PolicyRule{Resources:["pods"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["pods"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:["extensions"], Verbs:["update"]} PolicyRule{Resources:["pods"], APIGroups:["extensions"], Verbs:["delete"]} PolicyRule{Resources:["services"], APIGroups:["extensions"], Verbs:["create"]} PolicyRule{Resources:["services"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["services"], APIGroups:["extensions"], Verbs:["update"]} PolicyRule{Resources:["services"], APIGroups:["extensions"], Verbs:["delete"]}] user=&{ensonic@google.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews" "selfsubjectrulesreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
```

**What you expected to happen**:
It to work or to give a concise error message. I am running this as a user who is cluster owner, so how can I not have the right privileges for anything?

**Environment**:
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.6-gke.1", GitCommit:"cb151369f60073317da686a6ce7de36abe2bda8d", GitTreeState:"clean", BuildDate:"2018-04-07T22:06:59Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
running on GKE (Master version: 1.9.6-gke.1, Node version: 1.9.6-gke.1)

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #65804

Tested by granting a namespaced admin role to a user, then attempt to grant a broader role as that user:

```
kubectl create rolebinding user1-admin --clusterrole=admin --user=user1
kubectl create rolebinding user2-volume --as=user1 --clusterrole=system:volume-scheduler --user=user2
```

before:
> Error from server (Forbidden): rolebindings.rbac.authorization.k8s.io "user2-volume" is forbidden: attempt to grant extra privileges: [{[get] [] [persistentvolumes] [] []} {[list] [] [persistentvolumes] [] []} {[patch] [] [persistentvolumes] [] []} {[update] [] [persistentvolumes] [] []} {[watch] [] [persistentvolumes] [] []} {[get] [storage.k8s.io] [storageclasses] [] []} {[list] [storage.k8s.io] [storageclasses] [] []} {[watch] [storage.k8s.io] [storageclasses] [] []}] user=&{user1  [system:authenticated] map[]} ownerrules=[{[create] [authorization.k8s.io] [selfsubjectaccessreviews selfsubjectrulesreviews] [] []} {[get] [] [] [] [/api /api/* /apis /apis/* /healthz /openapi /openapi/* /swagger-2.0.0.pb-v1 /swagger.json /swaggerapi /swaggerapi/* /version /version/]} {[create delete deletecollection get list patch update watch] [] [pods pods/attach pods/exec pods/portforward pods/proxy] [] []} {[create delete deletecollection get list patch update watch] [] [configmaps endpoints persistentvolumeclaims replicationcontrollers replicationcontrollers/scale secrets serviceaccounts services services/proxy] [] []} {[get list watch] [] [bindings events limitranges namespaces/status pods/log pods/status replicationcontrollers/status resourcequotas resourcequotas/status] [] []} {[get list watch] [] [namespaces] [] []} {[impersonate] [] [serviceaccounts] [] []} {[create delete deletecollection get list patch update watch] [apps] [daemonsets deployments deployments/rollback deployments/scale replicasets replicasets/scale statefulsets statefulsets/scale] [] []} {[create delete deletecollection get list patch update watch] [autoscaling] [horizontalpodautoscalers] [] []} {[create delete deletecollection get list patch update watch] [batch] [cronjobs jobs] [] []} {[create delete deletecollection get list patch update watch] [extensions] [daemonsets deployments deployments/rollback deployments/scale ingresses networkpolicies replicasets replicasets/scale replicationcontrollers/scale] [] []} {[create delete deletecollection get list patch update watch] [policy] [poddisruptionbudgets] [] []} {[create delete deletecollection get list patch update watch] [networking.k8s.io] [networkpolicies] [] []} {[create] [authorization.k8s.io] [localsubjectaccessreviews] [] []} {[create delete deletecollection get list patch update watch] [rbac.authorization.k8s.io] [rolebindings roles] [] []}] ruleResolutionErrors=[]

after
> Error from server (Forbidden): rolebindings.rbac.authorization.k8s.io "user2-volume" is forbidden: user "user1" (groups=["system:authenticated"]) is attempting to grant RBAC permissions not currently held:
> {APIGroups:[""], Resources:["persistentvolumes"], Verbs:["get" "list" "patch" "update" "watch"]}
> {APIGroups:["storage.k8s.io"], Resources:["storageclasses"], Verbs:["get" "list" "watch"]}

### CODE REVIEW

**Comment by liggitt** [comment]
@kubernetes/sig-auth-pr-reviews

**Comment by deads2k** [comment]
deja vu. Same actors in the play even.

**Comment by ensonic** [comment]
Thanks a lot, this is much easier to parse. Small nit is that by running

    kubectl create rolebinding user2-volume --as=user1 --clusterrole=system:volume-scheduler --user=user2

user1 tried to give user2 the (cluster)role "system:volume-scheduler". The resulting error message does not contain any of this (besides that user1 can't do it). Instead it expects that whoever reads it knows that  the role "system:volume-scheduler" expands to the listed permissions.

Please consider what user1 will have to do to remedy. The user will need to get that (cluster)role himself and not the individual permissions.

**Comment by liggitt** [comment]
> The user will need to get that (cluster)role himself and not the individual permissions.

 That's not quite accurate. As long as the user has those permissions, it doesn't matter what role granted them. For example, a cluster admin has a single super user role the grants all permissions, and would allow this. I'm hesitant to add "user guide" style messages into an error message

**Comment by ensonic** [comment]
Fair enough. Thanks for the explanation.

**Pull request merged**
