### PR TITLE
fix a bug that connection refused error will not recognized correctly

### PR DESCRIPTION
**Pull request by likakuli**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

When listerWatcher returns a "connection refused" error, the opError.Err's type is os.SyscallError and its Error() is "connect: connection refused". So the code
```
time.sleep(1 * time.second) 
continue
```
will not be excuted forever. Thus
```
return nil
```

**Which issue(s) this PR fixes**:

Fixes #
When there is a "connection refused" error, the reflector's ListAndWatch func will return directly but what expected is that sleep 1 second and rewatch since the specified resourceVersion.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fixes a bug that when there is a "connection refused" error, the reflector's ListAndWatch func will return directly but what expected is that sleep 1 second and rewatch since the specified resourceVersion.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by yliaog** [comment]
could you please add a test case for the fix?

**Comment by likakuli** [comment]
> could you please add a test case for the fix?

ok i will close this pr and reopen a new pr

**Pull request closed without merging**
