### PR TITLE
Bump GCE ContainerVM to container-v1-3-v20160517 (Docker 1.11.1)

### PR DESCRIPTION
**Pull request by zmerlynn**
[Analytics]()

### CODE REVIEW

**Comment by zmerlynn** [comment]
We're waiting on http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-container-vm/ to go green first (which means we need a fix to a racy test first).

**Comment by zmerlynn** [comment]
cc @kubernetes/goog-node @kubernetes/goog-image

**Comment by dchen1107** [comment]
LGTM

cc/ @derekwaynecarr FYI: This help us to enable more testing, doesn't mean it passed all validation tests yet.

**Comment by lavalamp** [comment]
manual merge.

**Comment by dchen1107** [comment]
https://github.com/kubernetes/kubernetes/issues/23397 & https://github.com/kubernetes/kubernetes/issues/25893

**Comment by wojtek-t** [comment]
It seems that this PR completely broke large kubemarks. But the real problem is that we was able to start only ~60pods on a single node. Which is definitely a big problem.

I reverted this PR in #25951

**Comment by wojtek-t** [comment]
@k8s-oncall - FYI ^^

**Comment by wojtek-t** [comment]
This means that there is some incompatibiliy between Docker 1.9 and 1.11, which we need to be explicit about if we want that.

**Pull request merged**
