### PR TITLE
Remove duplicate code from kubectl describe

### PR DESCRIPTION
**Pull request by ivan4th**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34808)

### CODE REVIEW

**Comment by ivan4th** [comment]
log copy error / build time out?
let's retry
@k8s-bot kubemark e2e test this

**Comment by deads2k** [comment]
Straight move?

**Comment by ivan4th** [comment]
Almost. One occurrence had
```msg := " %s\t%v\t%v\t%v\t%v\t%v\t%v\n"```
and another
```msg := "%v\t%v\t%v\t%v\t%v\t%v\t%v\n"```
So I added "prefix" arg to pass extra space in the first case (I believe it's there for a reason).

**Comment by ivan4th** [comment]
... and %v was used for a String in 2nd case

**Pull request merged**
