### PR TITLE
Fix the kubectl taint documentation

### LINKED ISSUE #87296: kubectl taint --help example doesn't work
**What happened**:

`kubectl taint --help` says:

```
...
Examples:
   ...
  # Add to node 'foo' a taint with key 'bar' and no value
  kubectl taint nodes foo bar:NoSchedule
```

That doesn't work:

```
$ kubectl taint nodes foo bar:NoSchedule
error: at least one taint update is required
```

It doesn't matter whether there is a node "foo" or not. It doesn't seem to contact the API at all.

**What you expected to happen**:

Examples form the help texts should work.

**Anything else we need to know?**:

Looking at https://github.com/kubernetes/kubernetes/blob/7d15d41eb87f8e6977a8947efe3edf7a75c1d01d/pkg/kubectl/cmd/taint/taint.go#L121-L156, it seems to want either a `=` or `-` in the argument. Indeed, `kubectl taint nodes foo bar=:NoSchedule` does work and does the right thing, i.e. set a taint with key `bar` and no value.

**Environment**:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-15T15:50:25Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"clean", BuildDate:"2019-12-11T12:34:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
$
```

### PR DESCRIPTION
**Pull request by bharaththiruveedula-zz**
Signed-off-by: Bharath Thiruveedula <bharath_ves@hotmail.com>

**What type of PR is this?**
> /kind documentation

**What this PR does / why we need it**:
This PR fixes the documentation in `kubectl taint --help`

**Which issue(s) this PR fixes**:

Fixes #87296

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```
NONE
```
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by zhouya0** [comment]
@bharaththiruveedula I have another way to fix this by changing the code but not the doc. Can I put it on and to see which would fix this problem better?

**Comment by bharaththiruveedula** [comment]
> @bharaththiruveedula I have another way to fix this by changing the code but not the doc. Can I put it on and to see which would fix this problem better?

@zhouya0 We discussed this  in the slack, and agreed to change only in the documentation, so is the PR.

**Comment by zhouya0** [comment]
ok Great. I just thought the origin PR https://github.com/kubernetes/kubernetes/pull/74159 is intend to let user use `kubectl taint nodes foo bar:NoSchedule` but not considering the command has a bug. But changing the doc is ok. Thanks for your apply!

**Comment by deads2k** [comment]
We only document the preferred manner of interacting with the command, so I don't expect to see the "or" listed.  I'm not certain whether the equals or the colon is preferred or if they have different meanings.  

@ravisantoshgudimetla or @soltysh ptal

**Comment by bharaththiruveedula** [comment]
@deads2k , for the consistency can we use "=" for both  taint and untaint?

**Review by soltysh — CHANGES_REQUESTED** [review]
/hold
this is wrong, the error is in `Complete` method, the example is correct. I'll open a fix in a bit.

**Comment by soltysh** [comment]
Superseded with https://github.com/kubernetes/kubernetes/pull/87423
/close

**Pull request closed without merging**
