### PR TITLE
Controller codebase refactoring

### PR DESCRIPTION
**Pull request by gmarek**
Solves #12072

cc @bgrant0607 @wojtek-t @davidopp @dchen1107

### CODE REVIEW

**Comment by wojtek-t** [comment]
The changes LGTM.
But it would be good for someone else to also look into it too - cc @thockin

**Comment by bgrant0607** [comment]
Do any of the controllers have cloudprovider-specific logic, or is that all pushed behind the cloudprovider interface?

**Comment by thockin** [comment]
I will take a look, but note that #6520 exists too.

@markturansky

**Comment by markturansky** [comment]
@bgrant0607 The volume plugins are currently using their specific cloud provider.  The cloud provider interface does not have functions for managing volumes.  The AWS cloud provider contains volumes methods.  GCE does not.   OpenStack will need a cloud provider implementation for volumes.  NFS (NetApp, EMC) has APIs to tap into.

**Comment by mikedanese** [comment]
Thanks! Self assigning since I'm currently doing some work in pkg/controller/. Looks simple enough at a glance

**Comment by mikedanese** [comment]
@gmarek needs rebase.

**Comment by gmarek** [comment]
Rebased.

**Comment by dchen1107** [comment]
LGTM, and leave it to @mikedanese for final call.

**Comment by mikedanese** [comment]
LGTM Thanks!

**Comment by alex-mohr** [comment]
Pinging shippable via close/reopen.

**Comment by alex-mohr** [comment]
@k8s-bot test this [testing build queue, sorry for the noise]

**Comment by alex-mohr** [comment]
Automatic merge from SubmitQueue

**Pull request merged**
