### PR TITLE
Remove nginx from vagrant configuration

### PR DESCRIPTION
**Pull request by derekwaynecarr**
This removes nginx to align with GCE and AWS configurations.

fyi @eparis @karlkfi

### CODE REVIEW

**Comment by eparis** [comment]
it LGTM

**Comment by jlowdermilk** [comment]
@thockin assigned for +lgtm, ok-to-merge

**Comment by roberthbailey** [comment]
Sweeeeet!

**Comment by jlowdermilk** [comment]
Reassigning to @quinton-hoole since Tim is out.

**Pull request merged**
