### PR TITLE
Fix the legacy of #74479

### PR DESCRIPTION
**Pull request by xichengliudui**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Fix the legacy of #74479

**Which issue(s) this PR fixes**:

Ref #74479 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks, looks like we've missed that.

/lgtm
/approve
/priority backlog

**Comment by xichengliudui** [comment]
@neolit123 Do these ports in other go files need to be modified to be constant? thanks.

**Comment by neolit123** [comment]
are you seeing the ports elsewhere under cmd/kubeadm?

**Comment by xichengliudui** [comment]
I just checked the whole kubeadm, and there is nothing to modify. Thank you for your reply

**Comment by neolit123** [comment]
@xichengliudui thanks :+1:

**Pull request merged**
