### PR TITLE
Fix invalid url for design-proposals

### PR DESCRIPTION
**Pull request by jinguang-dong**
Which is inspired by hatowang's PR of #115159 and fixed comment's url

/kind documentation

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/ok-to-test
/kind cleanup
/priority important-longterm
/triage accepted


Not sure what is the policy on updating old CHANgELOG files, but the change look good and useful

**Comment by jinguang-dong** [comment]
@SergeyKanzhelev  appreciation for your check and help. 
But there is some error for the CI test of  pull-kubernetes-dependencies #1621035911368151040
When I follow the guidance of the CI result and try to run the script of  hack/update-vendor.sh locally,  it will auto modify the file of  vendor/sigs.k8s.io/kustomize/kyaml/resid/gvk.go
```
diff --git a/vendor/sigs.k8s.io/kustomize/kyaml/resid/gvk.go b/vendor/sigs.k8s.io/kustomize/kyaml/resid/gvk.go
index 8f86da500ba..2c8cbb1f5d7 100644
--- a/vendor/sigs.k8s.io/kustomize/kyaml/resid/gvk.go
+++ b/vendor/sigs.k8s.io/kustomize/kyaml/resid/gvk.go
@@ -11,7 +11,7 @@ import (
 )
 
 // Gvk identifies a Kubernetes API type.
-// https://github.com/kubernetes/design-proposals-archive/blob/main/api-machinery/api-group.md
+// https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/api-group.md
 type Gvk struct {
        Group   string `json:"group,omitempty" yaml:"group,omitempty"`
        Version string `json:"version,omitempty" yaml:"version,omitempty"`
(END)

```

 I wonder if the modified file should be submitted along with the PR of  url fixed, but I think the url of file is  not right which need to updated. 

Hope you could give some

**Comment by SergeyKanzhelev** [comment]
it seems you fixed it now. Test is passing. Cool

**Comment by jinguang-dong** [comment]
> it seems you fixed it now. Test is passing. Cool

@SergeyKanzhelev  could you help to review and add approved/ lgtm labels, thanks a lot :)

**Comment by brianpursley** [comment]
A few thoughts:

1. Any reason why the design proposals **archive** link is being used for all these links?  Is there a current link that should be used instead?

For example:
You updated one of the links to this:
https://github.com/kubernetes/design-proposals-archive/blob/main/release/versioning.md

But when I go to that page, I see the up-to-date versioning policies are located here:
https://github.com/kubernetes/sig-release/blob/master/release-engineering/versioning.md

Shouldn't we use the second link instead?

2. This PR is going to require a lot of SIGs to approve, and it may be difficult to track down someone for every change.  If so, you might consider trying to break this up into multiple PRs.

3. I have mixed feelings about changing historical changelogs that far back. After the version is out of the support window, I don't think we should bother trying to keep changelogs up to date, but that's just my opinion and would defer to the changelog owners on that point.

**Comment by jinguang-dong** [comment]
> A few thoughts:
> 
> 1. Any reason why the design proposals **archive** link is being used for all these links?  Is there a current link that should be used instead?
> 
> For example: You updated one of the links to this: https://github.com/kubernetes/design-proposals-archive/blob/main/release/versioning.md
> 
> But when I go to that page, I see the up-to-date versioning policies are located here: https://github.com/kubernetes/sig-release/blob/master/release-engineering/versioning.md
> 
> Shouldn't we use the second link instead?
> 
> 2. This PR is going to require a lot of SIGs to approve, and it may be difficult to track down someone for every change.  If so, you might consider trying to break this up into multiple PRs.
> 3. I have mixed feelings about changing historical changelogs that far back. After the version is out of the support window, I don't think we should bother trying to keep changelogs up to date, but that's just my opinion and would defer to the changelog owners on that point.

Very valuable review comments, thanks a lot for brianpursley.
I haven't  fully understand the suggestion of  "shouldn't we use the second link instead"?   Could you give a example for the scenario?

**Comment by bart0sh** [comment]
@jinguang-dong 
> I haven't fully understand the suggestion of "shouldn't we use the second link instead"? Could you give a example for the scenario?

The suggestion was to use new alive urls instead of archived ones wherever possible because archived documents could be not up to date.

Example:
instead of replacing https://github.com/kubernetes/design-proposals-archive/blob/main/release/versioning.md with archive  url  https://github.com/kubernetes/design-proposals-archive/blob/main/release/versioning.md you should replace it with a new alive url  https://github.com/kubernetes/sig-release/blob/master/release-engineering/versioning.md

Note, that this is just one example. There could be more of this kind.

**Pull request closed without merging**
