### PR TITLE
etcd: Update version to 3.5.8

### PR DESCRIPTION
**Pull request by kkkkun**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Update etcd to version 3.5.8 See release: [v3.5.8](https://github.com/etcd-io/etcd/releases/tag/v3.5.8).
#### Which issue(s) this PR fixes:

Fixes # https://github.com/kubernetes/kubernetes/issues/117341

#### Does this PR introduce a user-facing change?

```release-note
Update etcd version to 3.5.8
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kkkkun** [comment]
/hold

Waiting https://github.com/kubernetes/kubernetes/pull/117332 Merged.

**Comment by lavalamp** [comment]
This updates the image but not the client library compiled into kube-apiserver. Is that intentional?

Also why does the root go.sum file reference these extremely old etcd versions?

```
github.com/coreos/etcd v3.3.10+incompatible/go.mod h1:uF7uidLiAD3TWHmW31ZFd/JWoc32PjwdhPthX9715RE=
github.com/coreos/etcd v3.3.13+incompatible/go.mod h1:uF7uidLiAD3TWHmW31ZFd/JWoc32PjwdhPthX9715RE=
```

I will let @logicalhan and/or @serathius state whether this upgrade is a good idea for us or not.

**Comment by logicalhan** [comment]
> This updates the image but not the client library compiled into kube-apiserver. Is that intentional?
> 
> Also why does the root go.sum file reference these extremely old etcd versions?

That's probably an oversight.

> I will let @logicalhan and/or @serathius state whether this upgrade is a good idea for us or not.

This change bumps from 3.5.7 to 3.5.8, so I think it's fine considering Marek has been fixing data inconsistency in 3.5. If it was a 3.4 -> 3.5 change, I would be more skeptical.

**Comment by kkkkun** [comment]
> /release-note-edit
> 
> ```
> Update coredns version to 3.5.8
> ```

/release-note-edit

`Update etcd version to 3.5.8`

**Comment by pacoxu** [comment]
/release-note-edit
```release-note
Update etcd version to 3.5.8
```

**Comment by neolit123** [comment]
/approve 

for kubeadm / test

**Review by BenTheElder — COMMENTED** [review]
/approve

**Comment by BenTheElder** [comment]
go.sum can have lingering references to observed package hashes for packages/versions not currently in use. go.mod and vendor look fine. 

it's an interesting question why even regenerating go.sum is showing this though, possibly an unused transitive dep somewhere

**Comment by liggitt** [comment]
```
go mod graph | grep coreos/etcd
github.com/spf13/viper@v1.4.0 github.com/coreos/etcd@v3.3.10+incompatible
github.com/bketelsen/crypt@v0.0.3-0.20200106085610-5cbc8cc4026c github.com/coreos/etcd@v3.3.13+incompatible
```

**Comment by BenTheElder** [comment]
ref: https://github.com/kubernetes/kubernetes/blob/51edcd963ec15c7b070c3b504a21fbfe9e978032/hack/unwanted-dependencies.json#L34

https://github.com/kubernetes/kubernetes/pull/102598

**Comment by liggitt** [comment]
yeah, we no longer depend on viper, but `go mod graph` and go.sum contain entries for the full graph, including transitive dependencies of non-latest versions of things

for instance, in this example, viper would still show up in `go mod graph` and go.sum, even though we'd eliminated the dependency

```
kubernetes -> foo@v1.1
kubernetes -> bar@v1.11
foo@v1.1 → bar@v1.10
bar@v1.10 → viper
bar@v1.11 → ... good things ...
```

**Comment by dims** [comment]
/ok-to-test

to see what breaks!

**Comment by kkkkun** [comment]
Failed tests are caused that `registry.k8s.io/etcd:3.5.8-0` not found. 

https://github.com/kubernetes/kubernetes/issues/117557 is tracking this.

**Comment by kkkkun** [comment]
> Failed tests are caused that `registry.k8s.io/etcd:3.5.8-0` not found.
> 
> #117557 is tracking this.

https://github.com/kubernetes/kubernetes/issues/117557 is resolved by https://github.com/kubernetes/kubernetes/pull/117879

**Comment by pacoxu** [comment]
/retest
after https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-image-etcd/1655912643896020992

**Comment by pacoxu** [comment]
wait for https://github.com/kubernetes/k8s.io/pull/5157 to be merged.

**Pull request merged**
