### PR TITLE
Fixing spacing for IANA standard service name link Fixes #29986

### PR DESCRIPTION
**Pull request by amalik17**
This pull request is addressing Issue #29986, I changed the wording of the link so that the link wouldn't be broken anymore.
```

### CODE REVIEW

**Comment by sandipanpanda** [comment]
@amalik17 Thank you for your contributions. Please sign the CLA and follow the instructions in the Bot commands for your PR to be tested and reviewed.

**Comment by dims** [comment]
@amalik17 missing CLA

**Comment by dims** [comment]
This PR needs a CLA to make progress, please see comments above from the CLA bot(s)

**Comment by dims** [comment]
There is a cncf-cla:no label on this PR. Can you please see the bot comments above to fix the CLA? This PR cannot progress unless the bot is happy with the CLA situation

**Comment by dims** [comment]
Please see https://github.com/kubernetes/community/blob/master/CLA.md#the-contributor-license-agreement on how to sign the CLA.

If you have already signed, please rebase commits in this PR to latest master and reopen the PR. This will trigger the newer EasyCLA bot to run and clear the "cncf-cla: no" label. We cannot merge any PRs if the CLA is not signed.

Thanks!

**Pull request closed without merging**
