### PR TITLE
CRI: add seccomp profile root path to runtime

### LINKED ISSUE #36997: CRI: pass full seccomp profile to runtime
Seccomp profile is passed to runtime by [annotations](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.proto#L244) in CRI:

```
    // 2. Seccomp
    //
    //      key: security.alpha.kubernetes.io/seccomp/pod
    //      description: the seccomp profile for the containers of an entire pod.
    //      value: see below.
    //
    //      key: security.alpha.kubernetes.io/seccomp/container/<container name>
    //      description: the seccomp profile for the container (overides pod).
    //      values: see below
    //
    //      The value of seccomp is runtime agnostic:
    //      * runtime/default: the default profile for the container runtime
    //      * unconfined: unconfined profile, ie, no seccomp sandboxing
    //      * localhost/<profile-name>: the profile installed to the node's
    //        local seccomp profile root
```

`localhost/<profile-name>` is relative to node's local seccomp profile root, it is defined in kubelet. But runtime doesn't know it. We should pass full profile path in CRI. 

cc/ @yujuhong @kubernetes/sig-node 

Will file a PR to fix this later.

### PR DESCRIPTION
**Pull request by feiskyer**
This PR adds a new `security.alpha.kubernetes.io/seccomp/root` annotations to sandboxConfig to pass seccomp profile root path to runtime.

Fixes #36997.

cc @yujuhong @euank

### CODE REVIEW

**Comment by feiskyer** [comment]
cc @kubernetes/sig-node-misc

**Comment by euank** [comment]
I did a little more investigation, and as far as I can tell a seccomp root and the associated file structure is a docker specific (invented [here](https://github.com/docker/docker/pull/17989)) concept.

If we wanted to make this container runtime agnostic, the Kubelet could convert from that json to protobuf structs which clearly specify the exact details.

I think this is attractive for a number of reasons. Most importantly, the current specification is relying on incidental communication of state via the filesystem (passing references to files over an API is basically always an anti-pattern).

There are also things, such as no-new-privileges, which interact in some way with certain seccomp options, and so it makes sense for the kubelet to resolve a seccomp specification fully itself prior to reaching out to the runtime so that the kubelet may make any additional decisions that must be made.

cc @lucab @jonboulle

**Comment by feiskyer** [comment]
> If we wanted to make this container runtime agnostic, the Kubelet could convert from that json to protobuf structs which clearly specify the exact details.

Yes, I'm planning to add another PR to focus on the format of seccomp profile (in both kubernetes api and kubelet CRI). But it is not ready yet.

> There are also things, such as no-new-privileges, which interact in some way with certain seccomp options, and so it makes sense for the kubelet to resolve a seccomp specification fully itself prior to reaching out to the runtime so that the kubelet may make any additional decisions that must be made.

If so, we need to spec the seccomp profile format first. (opened #39128 for this)

**Comment by timstclair** [comment]
Can you explain the motivation for this? There should be a single seccomp root path for the host, so this seems like a value that should be configured in the shim (e.g. flag), as opposed to a per-pod annotation.

@euank - I agree with you, but that's also not how seccomp works today. I'd like to be able to source seccomp (and AppArmor) profiles from ConfigMaps, and maybe at that point we could deprecate local profiles.

**Comment by feiskyer** [comment]
@timstclair This is a try to fix #36997.

> I'd like to be able to source seccomp (and AppArmor) profiles from ConfigMaps, and maybe at that point we could deprecate local profiles.

If we have such plan, then we should pass full profile instead of path to runtimes.

**Comment by feiskyer** [comment]
Let's close this and move to #36997 to discuss more.

**Pull request closed without merging**
