### PR TITLE
Automated cherry pick of #39311 #39768 #38547

### PR DESCRIPTION
**Pull request by rkouj**
Cherry pick of #39311 #39768 #38547 on release-1.4.

`WIP`

#39311: Check if pathExists before performing Unmount
#39768: Check if path exists before performing unmount
#38547: Use common unmount util func for TearDownAt()

Please wait until all checks are passed for the review.
@thockin please assign to @saad-ali

### CODE REVIEW

**Comment by saad-ali** [comment]
Looks like your build is broken:

```
W0117 11:24:01.369] # k8s.io/kubernetes/pkg/volume/glusterfs
W0117 11:24:01.371] pkg/volume/glusterfs/glusterfs.go:238: undefined: volutil in volutil.UnmountPath
W0117 11:24:01.372] pkg/volume/glusterfs/glusterfs.go:258: undefined: volutil in volutil.UnmountPath
W0117 11:24:03.159] # k8s.io/kubernetes/pkg/volume/rbd
W0117 11:24:03.159] pkg/volume/rbd/rbd.go:253: undefined: volutil in volutil.PathExists
```

Assign 1.4 cherry picks to @jessfraz

**Comment by rkouj** [comment]
Yep, I realize that :)

**Comment by thockin** [comment]
@saad-ali please figure out what to do with this?

**Comment by jessfraz** [comment]
@rkouj can you clean up the conflicts or I can try to do it for you?

**Comment by jessfraz** [comment]
I'll carry this in a different PR

**Comment by jessfraz** [comment]
opened in https://github.com/kubernetes/kubernetes/pull/43095 closing this one

**Pull request closed without merging**
