### PR TITLE
[v1.16.5] Update to go1.13.4

### PR DESCRIPTION
**Pull request by liggitt**
Picks:
* https://github.com/kubernetes/kubernetes/pull/82805 - heketi/heketi update
* https://github.com/kubernetes/kubernetes/pull/82684 - gofmt update
* https://github.com/kubernetes/kubernetes/pull/82809 - go1.13.4 update
* https://github.com/kubernetes/kubernetes/pull/84937 - kubeadm e2e test flag update

1.16-specific:
* Move e2e flag copy into TestMain (same thing as e2e_node, done for e2e)

Before merge:
- [x] Update CI on 1.16 branches to use go1.13, similar to https://github.com/kubernetes/test-infra/pull/15113 / https://github.com/kubernetes/test-infra/pull/15156:
   * [x] https://github.com/kubernetes/test-infra/pull/15637

/cc @tpepper 
/sig release

```release-note
Kubernetes 1.16.5+ now requires go1.13.4+ to build 
```

### CODE REVIEW

**Comment by tpepper** [comment]
Per Slack conversation:

 * data from k8s 1.17 on go1.13 would be beneficial
 * 1.17's slated for Dec. 9 release
 * next 1.16.4 is slated for Dec. 11
 * we could merge go1.13 after the k8s 1.16.4 release
 * have soak time ahead of mid-January k8s 1.16.5 release
 * that leaves 2-3 weeks before go1.12 goes out of support

This feels like a viable plan for 1.16 branch (1.15 is another question).

**Comment by liggitt** [comment]
dependencies CI failure is expected, due to the job running under go1.12.x and building vendor differently. All other jobs are green.

**Comment by liggitt** [comment]
From my perspective, this is ready. After 1.16.4 cuts on 2019-12-11, we can proceed with review and with the test-infra changes required.

cc @BenTheElder for test-infra
cc @dims @cblecker for review
cc @tpepper for release

**Comment by BenTheElder** [comment]
quite a diff, generally looks right but didn't look at it quite closely enough yet.

**Comment by tpepper** [comment]
I'm in favor of this.  I'm slightly worried about the state of build & CI right now and would like a little more sense that those are on a better footing around understanding the current issues before also having the changed golang in the mix (hopefully we see that any day now??).  But we also want to get this in sooner than later.

I propose we aim to merge this by the end of this week, lacking any rationale to delay it further.

**Comment by tpepper** [comment]
/retest
@liggitt is pull-kubernetes-dependencies failure (https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/85019/pull-kubernetes-dependencies/1205931288209395718) a legit one needing fixup?

**Comment by liggitt** [comment]
> @liggitt is pull-kubernetes-dependencies failure (https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/85019/pull-kubernetes-dependencies/1205931288209395718) a legit one needing fixup?

That will fail until we switch CI to use go1.13 for release-1.16 jobs. We need to do kubernetes/test-infra#15113 kubernetes/test-infra#15156 for 1.16, basically

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/test-infra/pull/15637 for test-infra changes

**Comment by justaugustus** [comment]
Release Engineering approval:
/approve

I reviewed the test-infra PR as well.

**Comment by liggitt** [comment]
https://github.com/kubernetes/test-infra/pull/15637 merged, rebased and retesting

**Comment by liggitt** [comment]
oh, we need to bump the kubekins image to pick up the go version change for 1.16 (e.g. https://github.com/kubernetes/test-infra/pull/15133). xref https://github.com/kubernetes/test-infra/pull/15637#discussion_r359383273

**Comment by liggitt** [comment]
fixed the stray bazel file... all other CI jobs passed on the first try after bumping test-infra to 1.16 🎉

**Comment by liggitt** [comment]
@tpepper this is green

**Review by cblecker — APPROVED** [review]
Can you please specify that this is for 1.16.z in your release note?

Thank you for splitting up the commits.. makes it much easier to review in chunks.

/lgtm
/approve
/hold

**Comment by liggitt** [comment]
Done

**Comment by cblecker** [comment]
/hold cancel
:shipit:

**Review by idealhack — APPROVED** [review]

**Pull request merged**
