### PR TITLE
node-exporter optimize config and prometheus config add node-exporter

### PR DESCRIPTION
**Pull request by like-inspur**
/kind feature

### CODE REVIEW

**Comment by serathius** [comment]
Hey @likerj,

Did you have chance to read https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/prometheus/README.md
?
This directory is experimental only and is planned to be removed.

**Comment by serathius** [comment]
PR for removing this addon https://github.com/kubernetes/kubernetes/pull/83442

**Comment by like-inspur** [comment]
@serathius hello, I see prometheus readme, now I pull requests about fluentd-elasticsearch

**Pull request closed without merging**
