### PR TITLE
[Federation] Cleanup unused code in service controller

### PR DESCRIPTION
**Pull request by shashidharatd**
Post merging the PR #41258, lot of unused code is left behind in federation service controller. These changes were segregated to this PR, so that the original PR was small and manageable.

**Release note**:
```
NONE
```

cc @kubernetes/sig-federation-pr-reviews

### CODE REVIEW

**Comment by shashidharatd** [comment]
@k8s-bot unit test this

**Comment by shashidharatd** [comment]
@k8s-bot unit test this

**Comment by csbell** [comment]
I'd rather not have us revert this. Until we have pre-merge testing, please invoke the bot (even though yes it looks like routine cleanup :-).
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by shashidharatd** [comment]
@csbell, pre-merge tests for federation have already passed. https://k8s-gubernator.appspot.com/pr/44960

**Comment by csbell** [comment]
Apologies, had not seen it.
/lgtm

**Comment by shashidharatd** [comment]
Thanks @csbell, @nikhiljindal

**Pull request merged**
