### PR TITLE
Actually delete the dummy Pod in kubeadm setups

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:Right now, the dummy Pod in the kube-system namespace is left running in all kubeadm deployments, which is bad. Deleting the Deployment doesn't delete the Pod unfortunately. This just makes the dummy workload a plain Pod, which can be easily deleted.

**Release note**:

```release-note
NONE
```

@mikedanese @dgoodwin @errordeveloper @jbeda This is a PR that can easily and quickly be lgtm'd.

### CODE REVIEW

**Comment by mikedanese** [comment]
Can we use the deployment reaper? Should the server side gc be implemented for deployments? cc @caesarxuchao @janetkuo

**Comment by luxas** [comment]
@mikedanese I talked to @deads2k about this in #kubernetes-dev and interpreted from the chat that the reapers are gonna be deprecated or something and the GC isn't stable enough to use now, so this was the most right option for the time being.

I think this is the easiest and the best option to do, for us it doesn't matter whether we're deploying a dummy Pod or Deployment.

Ok?

**Comment by mikedanese** [comment]
I don't like deploying just a pod. It doesn't test the controller manager.

**Comment by mikedanese** [comment]
I would be fine with using the reaper for now.

**Comment by kargakis** [comment]
> Can we use the deployment reaper? Should the server side gc be implemented for deployments? cc @caesarxuchao @janetkuo

Server-side reaping for Deployments is in master as of https://github.com/kubernetes/kubernetes/pull/35676.

**Comment by kargakis** [comment]
> I would be fine with using the reaper for now.

+1 - reapers are still not officially deprecated. Based on the contract we have in kubectl, the client reapers are not going to be removed for >= N+2 versions if a server-side reaper implementation for a resource is added in N.

**Comment by pires** [comment]
@luxas I was looking into this today and we should rely now on #35676.

**Comment by luxas** [comment]
@pires Yes, I saw that. Didn't get it working when I tried running from HEAD though, can try again in the future

**Pull request closed without merging**
