### PR TITLE
Updating local-cluster-up to v1

### PR DESCRIPTION
**Pull request by nikhiljindal**

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @bgrant0607 @krousey @caesarxuchao

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by bgrant0607** [comment]
LGTM, though that should really just ping /healthz

**Comment by bgrant0607** [comment]
2nd review needed.

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
