### PR TITLE
test images: assign gcEtcdRegistry to the correct value

### PR DESCRIPTION
**Pull request by chewong**
Signed-off-by: Ernest Wong <chuwon@microsoft.com>

#### What type of PR is this?

Follow-up PR for https://github.com/kubernetes/kubernetes/pull/98926. `gcEtcdRegsitry` was not assigned to the correct value.

/kind failing-test
/sig testing
/priority important-soon
/cc @claudiubelu 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm

whoops!

**Comment by chewong** [comment]
/hold
to prevent this PR from being auto-merged.

**Comment by chewong** [comment]
`Kubernetes e2e suite.[sig-api-machinery] Aggregator Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]` passed. It should be safe to merge now.

**Review by ravisantoshgudimetla — APPROVED** [review]
Thank you for working on this @chewong 

/approve

**Pull request merged**
