### PR TITLE
Added "feature" tag to HA master tests.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Add "feature" tag to exclude HA master tests from "serial" test suit.

Reverts kubernetes/kubernetes#37356

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37441)

### CODE REVIEW

**Comment by saad-ali** [comment]
Fixes https://github.com/kubernetes/kubernetes/issues/37409

**Comment by saad-ali** [comment]
@k8s-bot verify test this

**Comment by jszczepkowski** [comment]
Part of https://github.com/kubernetes/features/issues/48

**Comment by saad-ali** [comment]
Manually merging ahead of lifting general code freeze, to fix broken serial tests: https://github.com/kubernetes/kubernetes/issues/37409#issuecomment-262847691

CC @lavalamp

**Comment by luxas** [comment]
@saad-ali When will you lift the code freeze?
Will it be today as planned?

**Comment by dims** [comment]
@luxas : happening as we speak! (folks are restarting the submit queue)

**Pull request merged**
