### PR TITLE
AWS: include ELB name in health-check logging

### PR DESCRIPTION
**Pull request by justinsb**
Makes more supportable

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33570)

### CODE REVIEW

**Comment by justinsb** [comment]
ping @zmerlynn

**Comment by zmerlynn** [comment]
Ack, sorry, it's been a while since I've systemically cleaned my PRs, and I didn't see this. This LGTM, sorry for it being so late.

**Comment by rmmh** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
