### PR TITLE
Add replace configmap from file

### LINKED ISSUE #30558: Support updating config map and secret with --from-file
It is possible to create a config map using `kubectl create configmap foo --from-file bar.txt`.  We support similarly updating the config map using `kubectl update configmap foo --from-file bar.txt`.

### PR DESCRIPTION
**Pull request by Se7soz**
**What this PR does / why we need it**:

Adding a way to replace configmap --from-file as suggested in issue #30558  

**Which issue this PR fixes**: fixes #

Closes #30558

**Special notes for your reviewer**:

It works the same way create configmap --from-file works .. please let me know if you suggest a better way to reduce code redundancy by moving the common part in create to a common file .. since its my first time .. I preferred not to do aggressive changes unless suggested by someone who knows the system better than me.

```release-note
NONE
```

### CODE REVIEW

**Comment by husseincoder** [comment]
@mengqiy please check

**Comment by mengqiy** [comment]
It seems there is no `-f` flag in the new command. 
Then you are not supporting this case: `kubectl replace -f=file.yaml --from-file=config.map`.

**Comment by mengqiy** [comment]
/assign @liggitt 
I think you will be interested in this PR.

**Comment by liggitt** [comment]
cc @kubernetes/sig-cli-pr-reviews 

before we start adding `kubectl replace` subcommands, @kubernetes/sig-cli-proposals should discuss whether this is a good direction or what it should look like

**Comment by mengqiy** [comment]
> before we start adding kubectl replace subcommands, @kubernetes/sig-cli-proposals should discuss whether this is a good direction or what it should look like

@fabianofranz What's your opinion?

**Comment by mengqiy** [comment]
/assign @shiywang 
Please help to review this. Thanks!

**Comment by mengqiy** [comment]
@fabianofranz If there is no objection, we will proceed with this. I think @pwittrock is fine with this.

**Comment by liggitt** [comment]
Before starting down this road, we should decide whether we expect to have a `kubectl replace ...` subcommand corresponding to every `kubectl create ...` subcommand, or if we're making a special case of secret and configmap.

Given that the goal of the create commands is explicitly not to support every possible option on the resulting objects, building `replace` commands to operate on existing objects that may have made use of some of those options seems problematic.

Would it make more sense to model updating a configmap or secret after the `kubectl set ...` approach, where a specific set of target object types are allowed, and a specific set of modifications are supported? For example:
```
kubectl set key configmap/foo --from-literal=key1=config1 --from-file=key2=/path/to/bar/file2.txt
kubectl set key secret/bar --from-literal=key1=config1 --from-file=key2=/path/to/bar/file2.txt
```

**Comment by bgrant0607** [comment]
I agree with @liggitt. In addition, we also should decide whether/how to support other flavors of updates, such as apply.

**Comment by bgrant0607** [comment]
If we do want to implement `replace`, it should ONLY be for secret and configmap.

**Comment by husseincoder** [comment]
Hey guys .. any news here? do I have to introduce new changes here or you think its not relevant? @liggitt @pwittrock @mengqiy

**Comment by bgrant0607** [comment]
I commented on the issue: https://github.com/kubernetes/kubernetes/issues/30558#issuecomment-331342865

@liggitt What do you think about a flag on `create` instead of a separate command? (Details in comment above.)

**Comment by bgrant0607** [comment]
Closing. Please see https://github.com/kubernetes/kubernetes/issues/30558#issuecomment-339777932 for details

**Pull request closed without merging**
