### PR TITLE
Automated cherry pick of #37489 #37321 #37394 #37345 #37397 #37411 #37379 #37323 #37195 #37139 #37225 #37562 #37487 upstream release 1.5

### PR DESCRIPTION
**Pull request by saad-ali**
Batch cherry pick PRs #37489 #37321 #37394 #37345 #37397 #37411 #37379 #37323 #37195 #37139 #37225 #37562 #37487 from master to release-1.5 branch.

#37379 and #37225 had merge conflicts that needed to be resolved (due to large PRs that merged to master but not 1.5, see [this](https://groups.google.com/forum/#!topic/kubernetes-dev/mvIXrgEyHPY) for details)

CC PR Authors: @mwielgus @ymqytw @nikhiljindal @MrHohn @ymqytw @wojtek-t @thockin @roberthbailey

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37670)

**Comment by thockin** [comment]
LGTM

**Comment by saad-ali** [comment]
@k8s-bot cvm gke e2e test this

**Comment by saad-ali** [comment]
@k8s-bot cvm gke e2e test this

**Comment by saad-ali** [comment]
All checks are green. Manually merging to let CI run overnight with new fixes on release-1.5 branch.

```
Jenkins CRI GCE Node e2e — Build succeeded.
Jenkins GCE Node e2e — Build succeeded.
Jenkins GCE e2e — Build succeeded.
Jenkins GCE etcd3 e2e — Build succeeded.
Jenkins GCI GKE smoke e2e — Build succeeded.
Jenkins GKE smoke e2e — Build succeeded.
Jenkins Kubemark GCE e2e — Build succeeded.
Jenkins unit/integration — Build succeeded.
```

**Pull request merged**
