### PR TITLE
Fix defaulting in cluster/saltbase/install.sh

### PR DESCRIPTION
**Pull request by zmerlynn**
Otherwise this trips `nounset`.

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @roberthbailey @mikedanese

**Comment by mikedanese** [comment]
LGTM, Thanks!

**Comment by zmerlynn** [comment]
I manually got a cluster up with this change, merging to get `gke-ci` back on the rails.

**Comment by roberthbailey** [comment]
Post-facto LGTM.

**Pull request merged**
