### PR TITLE
"Switch cos version to M85""

### PR DESCRIPTION
**Pull request by vteratipally**
switch cos version to M85 to update the containerd version

### CODE REVIEW

**Comment by wojtek-t** [comment]
> switch cos version to M85 to update the containerd version

What are the notable changes in the new containerd version?

**Comment by dims** [comment]
/ok-to-test
/approve

will leave others (@cheftako ?) to lgtm

**Comment by vteratipally** [comment]
Will remove donotmerge label once the tests https://testgrid.k8s.io/sig-node-critical#containerd-NodeConformance become successful after confirming the https://github.com/containerd/cri/pull/1577.

**Comment by vteratipally** [comment]
With containerd 1.4 upgrade, kubernetes could support image filesystem optimized for fast image imports, fast application “cold start” times

**Comment by wojtek-t** [comment]
> With containerd 1.4 upgrade, kubernetes could support image filesystem optimized for fast image imports, fast application “cold start” times

Thanks - that makes perfect sense.

My only question is when can we expect official release to avoid using RC.

**Comment by karan** [comment]
Should this wait until 85 is LTS/stable?

**Comment by vteratipally** [comment]
yes lts release is couple of week away, guess we can wait till then

**Comment by wojtek-t** [comment]
> Should this wait until 85 is LTS/stable?

That is more explicit version of my question above: "when can we expect official release to avoid using RC.".
Basically the reason I asked that is:
- if this will happen soon - I'm fine with having that in now to get more soak time
- if it won't happen non-negligibly before our 1.20 release, we shouldn't change tht now too

**Comment by cheftako** [comment]
Also once we land the lts cos image do we want to cherry pick that change back to 1.18?

**Comment by bsdnet** [comment]
To reply all: 
All known issues (containerd 1.4, cloud-init, python2) found recently are root caused and resolved.
We will mark M85 as stable this week if no further issue found. We should be fine to use M85 in upstream.

This will also enable more upper layer features which will depend on 5.4 kernel

**Comment by bsdnet** [comment]
@wojtek-t 
For containerd changes , see https://github.com/containerd/containerd/releases

**Comment by wojtek-t** [comment]
@vteratipally @bsdnet - thanks (that sounds reasonable to me).

That said, given I have your attention here - there seem to be one more issue of previous containerd versions - see this one: https://github.com/kubernetes/kubernetes/issues/94256#issuecomment-682396333
Do you know if this one has been fixed too? If not, could you please help with making that happen?

**Comment by bsdnet** [comment]
@wojtek-t 

Let me ask around and see whether this affects containerd 1.4.x we are included in M85

**Comment by bsdnet** [comment]
@karan 

Do you or your team have insights on  #94256 @wojtek-t mentioned here?

**Comment by bsdnet** [comment]
/assign @karan  @cheftako 

Please help connect right people for PR #94256

**Comment by vteratipally** [comment]
cos-85 stable version is released with containerd 1.4.1, updating the stable version

**Comment by bsdnet** [comment]
/lgtm

cos 85 is marked as stable and is available to public.

$ gcloud compute images list |grep cos-cloud
cos-73-11647-656-0                                    cos-cloud            cos-73-lts                                    READY
cos-77-12371-1079-0                                   cos-cloud            cos-77-lts                                    READY
cos-81-12871-1200-0                                   cos-cloud            cos-81-lts                                    READY
cos-85-13310-1041-9                                   cos-cloud            cos-85-lts                                    READY
cos-beta-85-13310-1041-1                              cos-cloud            cos-beta                                      READY
cos-dev-86-15184-0-0                                  cos-cloud            cos-dev                                       READY
cos-stable-85-13310-1041-9                            cos-cloud            cos-stable                                    READY

**Pull request merged**
