### PR TITLE
Cronjob beta defaults

### PR DESCRIPTION
**Pull request by soltysh**
**What this PR does / why we need it**:
I forget to set the defaults in beta for (successful|failed)JobsHistoryLimit so doing this now. It's already too late for 1.8 so this goes into 1.9.

**Release note**:
```release-note
Set defaults for successfulJobsHistoryLimit (3) and failedJobsHistoryLimit (1) in batch/v1beta1.CronJobs
```

### CODE REVIEW

**Comment by janetkuo** [comment]
Default values cannot be changed in the same API version. This PR should either target 1.8 or wait for the next API version.

**Review by janetkuo — CHANGES_REQUESTED** [review]
Default values cannot be changed in the same API version. This PR should either target 1.8 or wait for the next API version.

**Comment by dims** [comment]
@soltysh  should we remove the 1.9 milestone then?

**Comment by soltysh** [comment]
@janetkuo I'm not sure we're able to get this in for 1.8, or do we?

/retest

**Review by janetkuo — APPROVED** [review]
This change LGTM

**Comment by janetkuo** [comment]
cc @erictune @kow3ns

**Comment by janetkuo** [comment]
@soltysh we should [request an exception](https://github.com/kubernetes/features/blob/master/EXCEPTIONS.md)

**Comment by janetkuo** [comment]
cc @jdumars (1.8 release team lead)

**Comment by smarterclayton** [comment]
This has API approval for 1.8 because we cannot change this post ship.

**Comment by kow3ns** [comment]
We need to ship this in 1.8 as break fix. Correct defaults is not a feature. Incorrect defaults is a bug.

**Comment by kow3ns** [comment]
@jdumars @michelleN @kubernetes/sig-release-api-reviews @kubernetes/sig-release-bugs we need an exception for this so we can release it in 1.8.

**Comment by jdumars** [comment]
This has already been added to the 1.8 milestone, and looks like it just needs approval to move forward.

**Pull request merged**
