### PR TITLE
Fix small dns readme error

### PR DESCRIPTION
**Pull request by mbonaci**
`kubectl get pods` output: `REASON` -> `STATUS`

### CODE REVIEW

**Comment by mwielgus** [comment]
@k8s-bot test this please

**Comment by gmarek** [comment]
@k8s test this

**Comment by gmarek** [comment]
@mbonaci can you please sign the CLA?

**Comment by mbonaci** [comment]
Hi @gmarek, I immediately went to sign it, once I got the bot message, but it told me I already signed it (Angular.js):

image

image

**Comment by mbonaci** [comment]
I signed it!

**Comment by gmarek** [comment]
Thanks! It seems that our bot is a bit slow:)

@k8s-bot test this

**Comment by alex-mohr** [comment]
@k8s-bot unit test this

**Pull request merged**
