### PR TITLE
rbd map should use the output of the command

### PR DESCRIPTION
**Pull request by mcluseau**
Hi,

I see things have changed on this subject on master. I haven't tested them. I'm proposing here the fix I made to handle an (CoreOS) host without the right udev rules to satisfy the previous asumption (that `devicePath` is `/dev/rbd/{pool}/{image}`). I use the rbd's command output as the device name, since `rbd map` worked this way since as far as I can remember.

Feel free to throw this if there is no point for a smaller chance than the current diff from release-1.1 to master.

### CODE REVIEW

**Comment by brendandburns** [comment]
@jsafrane can you take a look?

**Comment by jsafrane** [comment]
Looking at the current master, device name is loaded from /sys/bus/rbd/devices/*. Created by @rootfs in commit 8dbbcefdec541308616cface9c9ee4212d84bc9c

@rootfs, is this patch better than parsing /sys/bus/rbd/devices ?

**Comment by jsafrane** [comment]
> I use the rbd's command output as the device name, since rbd map worked this way since as far as I can remember

My /bin/rbd from ceph-common-0.80.10 on Fedora 21 does *not* print the device to stdout. Fedora 23 (ceph-common-0.94.4) prints the device, so it must be some recent change.

**Comment by rootfs** [comment]
I am not convinced rbd command output is a safe way to get the device path. sysfs interface is fairly consistent on all the ceph releases I've tested.

**Comment by swagiaal** [comment]
@MikaelCluseau what is the device name without the udev rule ? It is okay to implement a device search to account for udev variations. We do that in `gce_pd`. I would recommend doing that here as well.

**Comment by MikaelCluseau** [comment]
@swagiaal The device name is `/dev/rbd1` for instance. Device search is certainly an option too, since it is what `rbd map` does anyway, but through udev events.

@rootfs @jsafrane The sysfs version is better than mine, I just needed this patch to get things working on release-1.1, so submitting for what its worth (which can be 0) looked like a good idea.

About what could be the best way, I think it is through udev, because even if `rbd map` uses the sysfs interface (+kernel's key storage) to create the device, it uses udev to find the device, see (here)[https://github.com/ceph/ceph/blob/83e10f7e2df0a71bd59e6ef2aa06b52b186fddaa/src/krbd.cc#L176]. If you wish so, I can write something like that, linking to libudev using cgo.

**Comment by rootfs** [comment]
@MikaelCluseau thanks. The the background info on udev is,  we only need `ceph-common` to run `rbd` command.  `ceph_rbdnamer`, called by udev, is in `ceph` package. Most other stuff in `ceph` are not needed. Thus we skip udev and look directly in sysfs.

**Comment by MikaelCluseau** [comment]
@rootfs I agree, since the udev wait is already made by `rbd map`. My view has some distortions because I look for a way to avoid the dependency to ceph userland for this. In particular, with the "exclusive lock" feature that came with Ceph 0.94, Kubernetes could avoid this dependency while having a better lock, if I understand correctly, linked to the client's connection and not an external lock that survives a client's crash.

Back to the main problem, your fix has to land in release-1.1 to close this issue :-)

**Comment by rootfs** [comment]
@MikaelCluseau please check with @brendandburns if it is ok to cherry-pick 8dbbcefdec541308616cface9c9ee4212d84bc9c to release 1.1

**Comment by rootfs** [comment]
cherry pick proposed in  #17334

**Comment by rootfs** [comment]
@MikaelCluseau let me know if #17334 works for you, thanks.

**Comment by brendandburns** [comment]
@MikaelCluseau if #17334 works for you can you close this PR?

Thanks!
--brendan

**Comment by MikaelCluseau** [comment]
Hi, yes, will do. Sorry for the delay, I didn't had any spare cycle for now.

**Comment by MikaelCluseau** [comment]
Works for me, thanks! :-)

**Pull request closed without merging**
