### PR TITLE
Automated cherry pick of #38124

### PR DESCRIPTION
**Pull request by jingxu97**
Cherry pick of #38124 on release-1.4.

#38124: Fix GCI mounter script to run garbage collection multiple

### CODE REVIEW

**Comment by saad-ali** [comment]
@jessfraz FYI there is one more PR pending after this: https://github.com/kubernetes/kubernetes/pull/38411
That one will be cherry picked to 1.5 then 1.4

**Review by jessfraz — APPROVED** [review]

**Comment by jingxu97** [comment]
@k8s-bot unit test this

**Comment by jessfraz** [comment]
@k8s-bot unit test this

**Comment by jessfraz** [comment]
All green so merging

**Pull request merged**
