### PR TITLE
Test etcd 3.2.16

### PR DESCRIPTION
**Pull request by shyamjvs**
Just a test PR for doing some experiments wrt https://github.com/kubernetes/kubernetes/issues/60589#issuecomment-371978498

/do-not-merge

### CODE REVIEW

**Comment by shyamjvs** [comment]
So I ran 100-node performance tests against this PR with etcd 3.2.16:

- With `--snapshot-count=100000` (i.e default), etcd 99%ile usage:

```
    {
      "Name": "etcd-server-e2e-1-master/etcd-container",
      "Cpu": 0.129556509,
      "Mem": 790032384
    },
```

- With `--snapshot-count=10000`, etcd 99%ile usage:

```
    {
      "Name": "etcd-server-e2e-3-master/etcd-container",
      "Cpu": 0.127315669,
      "Mem": 269455360
    },
```

This does explain the increase in mem-usage observed in https://github.com/kubernetes/kubernetes/issues/60589#issuecomment-371975389.
So one of the things we should consider when bumping to etcd 3.2.16 is to set this param to lower value of 10k (if we don't want to increase the mem usage).

**Comment by jpbetz** [comment]
Thanks @shyamjvs for getting to the bottom of this!  I'll follow up on changing the value to of `--snapshot-count" to 10k for the etcd server configuration used by kubernetes.

**Comment by shyamjvs** [comment]
Closing this as the purpose of this PR is fulfilled.

**Pull request closed without merging**
