### PR TITLE
kubeadm: remove v1alpha3

### LINKED ISSUE #1296: Remove the v1alpha3 config API version in v1.15
It has been deprecated in v1.13 in favor of v1beta1, and will be removed in v1.14

@rosti can you send a PR for this?
I & @fabriziopandini will review it.
/assign @luxas @fabriziopandini @rosti

### PR DESCRIPTION
**Pull request by rosti**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Remove deprecated old v1alpha3 kubeadm config.

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#1296

**Special notes for your reviewer**:

/cc @kubernetes/sig-cluster-lifecycle-pr-reviews
/area kubeadm
/priority important-longterm
/assign @luxas 
/assign @fabriziopandini

This is for 1.15!
/hold

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: Support for deprecated old kubeadm v1alpha3 config is totally removed.
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

**Comment by neolit123** [comment]
/assign @fejta 
for `hack/.golint_failures` :)

**Review by dixudx — APPROVED** [review]

**Pull request merged**
