### PR TITLE
Fix comment for struct DeploymentBasicGeneratorV1

### PR DESCRIPTION
**Pull request by huzhengchuan**
**Release note**:

```release-note
```

### CODE REVIEW

**Comment by huzhengchuan** [comment]
I signed it!

**Comment by NickrenREN** [comment]
@k8s-bot ok to test

**Comment by huzhengchuan** [comment]
@k8s-bot non-cri e2e test this
@k8s-bot cvm gce e2e test this
@k8s-bot gci gce e2e test this

**Pull request merged**
