### PR TITLE
 External CA: kubeconfig file check still expects ca.key

### LINKED ISSUE #1391: External CA: kubeconfig file check still expects ca.key
## Is this a BUG REPORT or FEATURE REQUEST? 
Bug Report

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:05:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
- **OS** (e.g. from /etc/os-release): Centos 7
- **Kernel** (e.g. `uname -a`): Linux master0 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## What happened?

I have manually placed all the pki certs, sa cert, and ca's without the ca keys. Then I placed the conf files in the /etc/kubernetes directory. When running `kubeadm init` it instantly returns an error stating the ca.key doesn't exist when processing the kubeconfig files.
```
$ sudo kubeadm init --config /vagrant/config/clusterConfiguration.yaml
couldn't create a kubeconfig; the CA files couldn't be loaded: failed to load key: couldn't load the private key file /etc/kubernetes/pki/ca.key: open /etc/kubernetes/pki/ca.key: no such file or directory
``` 

## What you expected to happen?
I would expect it to verify the ca cert in the config files but without the ca.key when using an external ca. It shouldn't try loading the key since it doesn't exist.

## How to reproduce it (as minimally and precisely as possible)?
Generate the ca's, certs, and place the kubeconfig files and place them in the correct directories without the ca keys. Run kubeadm init and it tries to process the kubeconfig files with the key but fails cause it doesn't exist. 

## Anything else we need to know?
Looks like it has to do with https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go#L133 which is called from https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go#L360 the ValidateKubeconfigsForExternalCA method.

### PR DESCRIPTION
**Pull request by RA489**
External CA: kubeconfig file check still expects ca.key
fixes https://github.com/kubernetes/kubeadm/issues/1391

### CODE REVIEW

**Comment by linxcat** [comment]
Looking at the failure point referenced in the original issue (line hyperlink and upstream function call) you are making a change at an unrelated place in the code. This PR does nothing to fix the issue it claims to.

**Comment by linxcat** [comment]
take a look at this very recent code. @fabriziopandini Your work may be related to the parent issue and you may want to comment here or there.

**Comment by fabriziopandini** [comment]
@RA489 sorry I didn't noticed the issue/this PR before
The fix I filed before v1.14 hopefully fixes this problem. If this is not true please use this PR for amending my work/fixing gaps. Otherwise we can close this PR
/assign

**Comment by RA489** [comment]
@fabriziopandini Thanks for your work! we can close it now.

**Pull request closed without merging**
