### PR TITLE
dockershim/network: add sig-network-approvers to OWNERS

### PR DESCRIPTION
**Pull request by dcbw**
/kind cleanup
```release-note
NONE
```

@thockin @danwinship @kubernetes/sig-network-misc

### CODE REVIEW

**Comment by thockin** [comment]
I'm torn on this.  Moving everything to monolithic sig-centered lists means that adding anyone to those lists represents ever increasing risk.  

*I* do not feel comfortable approving dockershim changes now, but I can.  There are truly area-specific experts, and this erases that fact.

Thoughts?

**Comment by johnbelamaric** [comment]
That's a good point. I think we have separate OWNERs files for a reason. If it was all just SIG owned then we wouldn't really need them.

Is there a review bandwidth issue here? Are there reviews/approvals not being done quickly enough by the couple of folks on the list? If so maybe we need to ramp up some individuals. If not, then I am not sure there is a need for a change.

**Comment by thockin** [comment]
Or maybe we need aliases, but more focused aliases.
sig-network-kubelet-approvers vs sig-network-proxy-approvers or something?

Every time I get assigned a PR against dockershim, I switch it to dcbw or
freehan or one of the others, anyway.

**Comment by danwinship** [comment]
oops
/lgtm cancel
should have reloaded...

**Comment by danwinship** [comment]
FWIW my suggestion about adding sig-network-approvers to this OWNERS file in #85472 was mostly inspired by dual-stack-related PRs (mostly in `hostport/` and a little in `kubenet/`)

**Comment by thockin** [comment]
I worry that we lose the ACTUAL expertise and eventually the people who actually own a subdir stop feeling ownership of it, and then we're in real trouble.

**Comment by johnbelamaric** [comment]
Aliases make sense if the same group is going to appear in lots of owners files. Is that really the case for dockershim, for example?

**Comment by thockin** [comment]
Actually, I'd argue that it is useful if the same group of humans shows up in just 2 OWNERS files.

There seems to be precedent for such sub-sig groups.  @dcbw, what do you think?

**Comment by dcbw** [comment]
> Actually, I'd argue that it is useful if the same group of humans shows up in just 2 OWNERS files.
> 
> There seems to be precedent for such sub-sig groups. @dcbw, what do you think?

@thockin I'm on board with that.

**Comment by thockin** [comment]
Can you add `sig-network-plugin-approvers` to OWNERS_ALIASES and then use that here (and in the CNI OWNERS, which accidentally merged :) ?

**Comment by danwinship** [comment]
/close
#88138 added sig-network-driver-approvers instead

**Pull request closed without merging**
