### PR TITLE
keep-terminated-pod-volumes flag on kubelet is removed

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

keep-terminated-pod-volumes flag on kubelet is deprecated in 1.8. 

FYI:

- https://github.com/kubernetes/kubernetes/pull/47539
- https://github.com/kubernetes/kubernetes/pull/57355
- https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.8.md?plain=1#L2599

#### Which issue(s) this PR fixes:

Ref https://github.com/kubernetes/kubernetes/issues/45615

#### Does this PR introduce a user-facing change?

```release-note
ACTION REQUIRED: 
Kubelet flag `--keep-terminated-pod-volumes` was removed.  This flag was deprecated in 2017.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by carlory** [comment]
Friendly ping @tallclair, can you take a look at this PR? Is it time to remove the deprecated flag. I see this flag is mentioned by https://github.com/kubernetes/kubernetes/issues/122916

**Comment by bart0sh** [comment]
/lgtm
/assign @jsafrane @gnufied 
for a final approval

**Comment by jsafrane** [comment]
I checked that the kubeled cmdline option has been deprecated 7 years ago(!) in https://github.com/kubernetes/kubernetes/pull/47539 and therefore looks safe to remove.

/approve

@carlory, please update the release note, it should include `Action Required: keep-terminated-pod-volumes flag on kubelet was removed`, so it gets to the right section in release notes.

**Comment by jsafrane** [comment]
/assign @mrunalp @sjenning 
for approval
I also added it to the "needs approver" column in https://github.com/orgs/kubernetes/projects/43

**Comment by carlory** [comment]
rebased upstream to resolve confliction.

/cc @bart0sh @mrunalp @sjenning

**Review by mrunalp — APPROVED** [review]
/lgtm

**Comment by carlory** [comment]
/cc @pohly @dims 

For a test perspective.

**Pull request merged**
