### PR TITLE
AWS kube-down: Issue warning if VPC not found

### PR DESCRIPTION
**Pull request by justinsb**
To address issue #17219

### CODE REVIEW

**Comment by davidopp** [comment]
LGTM

Thanks, Justin!!

**Comment by davidopp** [comment]
This is failing due to "Kubectl apply should apply a new configuration to an existing RC" failure which appears in several roll-up test failures ("broken test run") but not any individual issues. I'll file an issue and restart the test.

**Comment by davidopp** [comment]
@k8s-bot test this issue: #27521

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please, issue: #27449

**Comment by activars** [comment]
👍

**Comment by goltermann** [comment]
In E2E on GCE cluster failed to create on nodes failing to validate, but wholly unrelated to the code change.

@k8s-bot e2e test this issue: #IGNORE

**Comment by davidopp** [comment]
Looks like an infrastructure problem; master failed to come up

```
Waiting for 7 ready nodes. 6 ready nodes, 6 registered. Retrying.
Waiting for 7 ready nodes. 6 ready nodes, 6 registered. Retrying.
Detected 6 ready nodes, found 6 nodes out of expected 7. Your cluster may not be fully functional.
NAME                                      STATUS                     AGE
e2e-gce-agent-pr-34-0-master              Ready,SchedulingDisabled   26m
e2e-gce-agent-pr-34-0-minion-group-05j0   Ready                      25m
e2e-gce-agent-pr-34-0-minion-group-0twx   Ready                      25m
e2e-gce-agent-pr-34-0-minion-group-oo31   Ready                      25m
e2e-gce-agent-pr-34-0-minion-group-tijt   Ready                      25m
e2e-gce-agent-pr-34-0-minion-group-yfym   Ready                      25m
2016/06/18 11:40:34 e2e.go:218: Error running up: exit status 1
2016/06/18 11:40:34 e2e.go:214: Step 'up' finished in 28m26.67816745s
2016/06/18 11:40:34 e2e.go:114: Error starting e2e cluster. Aborting.
```

**Comment by davidopp** [comment]
@k8s-bot e2e test this issue: #IGNORE

**Comment by davidopp** [comment]
Another infrastructure failure:
```
FATAL: Could not checkout bee5acd42028b0130c8c1b56c60fbd284f123edb
hudson.plugins.git.GitException: Could not checkout bee5acd42028b0130c8c1b56c60fbd284f123edb
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:1992)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:332)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to agent-pr-8(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
	at hudson.remoting.Channel.call(Channel.java:781)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:145)
	at sun.reflect.GeneratedMethodAccessor243.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:131)
	at com.sun.proxy.$Proxy64.execute(Unknown Source)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1135)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: hudson.plugins.git.GitException: Command "/usr/bin/git checkout -f bee5acd42028b0130c8c1b56c60fbd284f123edb" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: bee5acd42028b0130c8c1b56c60fbd284f123edb

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1719)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:63)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:1984)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:332)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[xUnit] [INFO] - Starting to record.
[xUnit] [INFO] - Processing JUnit
[xUnit] [INFO] - [JUnit] - No test report file(s) were found with the pattern '_artifacts/**.xml' relative to '/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce' for the testing framework 'JUnit'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'JUnit'?
[xUnit] [ERROR] - No test reports found for the metric 'JUnit' with the resolved pattern '_artifacts/**.xml'. Configuration error?.
[xUnit] [INFO] - Failing BUILD.
[xUnit] [INFO] - There are errors when processing test results.
[xUnit] [INFO] - Skipping tests recording.
[xUnit] [INFO] - Stop build.
[PostBuildScript] - Execution post build scripts.
[kubernetes-pull-build-test-e2e-gce] $ /bin/bash -xe /tmp/hudson1864197756255474751.sh
+ mkdir -p _tmp
+ curl -fsS --retry 3 https://raw.githubusercontent.com/kubernetes/kubernetes/master/hack/jenkins/upload-to-gcs.sh
+ chmod +x ./_tmp/upload-to-gcs.sh
+ [[ ! -e /var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce/build-log.txt ]]
+ curl -fsS --retry 3 http://pull-jenkins-master:8080/job/kubernetes-pull-build-test-e2e-gce/45661/consoleText
```

**Comment by davidopp** [comment]
@k8s-bot e2e test this issue: #IGNORE

**Comment by justinsb** [comment]
Any objection if I just mark "retest-not-required"?  e2e doesn't hit this...

**Comment by justinsb** [comment]
It's that missing bee5acd42028b0130c8c1b56c60fbd284f123edb again though.

Not sure exactly what's going on here.  bee5.. isn't in the main k8s repo.  I'm guessing bee5.. is the merge is what we pulled using `+refs/pull/27518/merge:refs/remotes/origin/pr/27518/merge`, except that is `4d4bdf...` (at least now).   I wonder if maybe an intermediate commit changes the sha?

**Comment by justinsb** [comment]
@k8s-bot e2e test this issue: #IGNORE

**Comment by goltermann** [comment]
@k8s-bot verify this issue: #IGNORE

**Comment by goltermann** [comment]
@k8s-bot e2e test this issue: #IGNORE

**Comment by goltermann** [comment]
@k8s-bot node e2e test this issue: #IGNORE

**Pull request merged**
