### PR TITLE
Automated cherry pick of #14996 #16413

### PR DESCRIPTION
**Pull request by lavalamp**
Cherry pick of #14996 #16413 on release-1.1.

### CODE REVIEW

**Comment by davidopp** [comment]
LGTM

Thanks very much!

**Comment by a-robinson** [comment]
@k8s-bot unit test this

**Comment by lavalamp** [comment]
@a-robinson that doesn't work on release branches :( (@ixdy is working on it, I think)

**Comment by lavalamp** [comment]
I'm pretty confident that this is OK, given that e2e passed.

**Comment by a-robinson** [comment]
Ah, thanks for the heads up. Agreed that e2e is a pretty good signal.

**Pull request merged**
