### PR TITLE
kubeproxy: use versioned clientset/informer from client-go

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:
/kind cleanup

Use external versioned clientset/informer from client-go

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/cc mikedanese thockin
 
**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by thockin** [comment]
Thanks for tacking this.

**Comment by thockin** [comment]
BTW: it doesn't compile.

```
cmd/kube-proxy/app/server_others.go:172:23: cannot use proxierIPTables (type *"k8s.io/kubernetes/pkg/proxy/iptables".Proxier) as type config.ServiceHandler in assignment:
	*"k8s.io/kubernetes/pkg/proxy/iptables".Proxier does not implement config.ServiceHandler (wrong type for OnServiceAdd method)
		have OnServiceAdd(*"k8s.io/kubernetes/pkg/apis/core".Service)
		want OnServiceAdd(*"k8s.io/kubernetes/vendor/k8s.io/api/core/v1".Service)
cmd/kube-proxy/app/server_others.go:173:25: cannot use proxierIPTables (type *"k8s.io/kubernetes/pkg/proxy/iptables".Proxier) as type config.EndpointsHandler in assignment:
	*"k8s.io/kubernetes/pkg/proxy/iptables".Proxier does not implement config.EndpointsHandler (wrong type for OnEndpointsAdd method)
		have OnEndpointsAdd(*"k8s.io/kubernetes/pkg/apis/core".Endpoints)
		want OnEndpointsAdd(*"k8s.io/kubernetes/vendor/k8s.io/api/core/v1".Endpoints)
cmd/kube-proxy/app/server_others.go:211:23: cannot use proxierIPVS (type *"k8s.io/kubernetes/pkg/proxy/ipvs".Proxier) as type config.ServiceHandler in assignment:
	*"k8s.io/kubernetes/pkg/proxy/ipvs".Proxier does not implement config.ServiceHandler (wrong type for OnServiceAdd method)
		have OnServiceAdd(*"k8s.io/kubernetes/pkg/apis/core".Service)
		want OnServiceAdd(*"k8s.io/kubernetes/vendor/k8s.io/api/core/v1".Service)
cmd/kube-proxy/app/server_others.go:212:25: cannot use proxierIPVS (type *"k8s.io/kubernetes/pkg/proxy/ipvs".Proxier) as type config.EndpointsHandler in assignment:
	*"k8s.io/kubernetes/pkg/proxy/ipvs".Proxier does not implement config.EndpointsHandler (wrong type for OnEndpointsAdd method)
		have OnEndpointsAdd(*"k8s.io/kubernetes/pkg/apis/core".Endpoints)
		want OnEndpointsAdd(*"k8s.io/kubernetes/vendor/k8s.io/api/core/v1".Endpoints)
cmd/kube-proxy/app/server_others.go:223:25: cannot use loadBalancer (type *userspace.LoadBalancerRR) as type config.EndpointsHandler in assignment:
	*userspace.LoadBalancerRR does not implement config.EndpointsHandler (wrong type for OnEndpointsAdd method)
		have OnEndpointsAdd(*"k8s.io/kubernetes/pkg/apis/core".Endpoints)
		want OnEndpointsAdd(*"k8s.io/kubernetes/vendor/k8s.io/api/core/v1".Endpoints)
cmd/kube-proxy/app/server_others.go:240:23: cannot use proxierUserspace (type *userspace.Proxier) as type config.ServiceHandler in assignment:
	*userspace.Proxier does not implement config.ServiceHandler (wrong type for OnServiceAdd method)
		have OnServiceAdd(*"k8s.io/kubernetes/pkg/apis/core".Service)
		want OnServiceAdd(*"k8s.io/kubernetes/vendor/k8s.io/api/core/v1".Service)
```

**Comment by thockin** [comment]
Please re-assign me when ready.  This is a good PR, I want it.

**Comment by dixudx** [comment]
/close

in favor of #67437

**Pull request closed without merging**
