### PR TITLE
Fix indentation issue in api.proto.

### PR DESCRIPTION
**Pull request by AdamCanady**
**What this PR does / why we need it**: Fix small indentation typo in api.proto.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**: Small fix, thanks!

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by AdamCanady** [comment]
Ack'd CLA.

**Comment by feiskyer** [comment]
@AdamCanady Thanks.

/ok-to-test

**Comment by feiskyer** [comment]
@AdamCanady Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

**Pull request closed without merging**
