### PR TITLE
It fixes a regression in fedora guide and provides minor updates.

### PR DESCRIPTION
**Pull request by aveshagarwal**
Without specifying label, the LABEL output will be <none> which does not match with current description.

### CODE REVIEW

**Comment by aveshagarwal** [comment]
I mean to say that "Without specifying labels, the LABEL output will be none, which does not match with current description.

**Comment by fabioy** [comment]
@smarterclayton - could you reassign as appropriate? Thank you.

**Comment by eparis** [comment]
looks like some whitespace weirdness in the json.  make that consistent and it LGTM

**Comment by aveshagarwal** [comment]
@eparis Pushed updated PR.

**Comment by aveshagarwal** [comment]
@eparis Just a reminder.

**Comment by eparis** [comment]
@aveshagarwal sorry!

**Pull request merged**
