### PR TITLE
Log where we pull images from in an e2e test

### PR DESCRIPTION
**Pull request by dims**
/kind cleanup

In this PR, we just run `docker images` or `ctr images list` to dump all the image info

At some point we will be making changes to the repository from where we pick up images. We already have a way to inject the location of images for the conformance tests etc, So this will make it easy to eyeball if we are using the correct repositories for each image.

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
Here's an example from the last run:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/108417/pull-kubernetes-e2e-gce-ubuntu-containerd/1498672984670343168/artifacts/e2e-08439866aa-a7d53-master/images-containerd.log

**Comment by ameukam** [comment]
> We already have a way to inject the location of images for the conformance tests etc
@dims Looking for guidance about this. I may have missed this.

**Comment by dims** [comment]
@ameukam see https://cs.k8s.io/?q=KUBE_TEST_REPO_LIST&i=nope&files=&excludeFiles=&repos=

example yaml https://raw.githubusercontent.com/kubernetes-sigs/windows-testing/master/images/image-repo-list

**Pull request merged**
