### PR TITLE
Update Calico Ubuntu doc to use CNI plugin

### PR DESCRIPTION
**Pull request by caseydavenport**

### CODE REVIEW

**Comment by thockin** [comment]
ok to test

**Comment by caseydavenport** [comment]
@thockin  - updated the PR after fixing a few hack/update-generated-docs.sh issues.

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

Tests have been pending for 24 hours

**Comment by thockin** [comment]
docs-check failed:

Verifying ./hack/../hack/verify-generated-docs.sh
+++ [0204 19:47:59] Building go targets for linux/amd64:
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genbashcomp
    cmd/mungedocs
+++ [0204 19:48:32] Placing binaries
/workspace/kubernetes/docs/getting-started-guides/ubuntu-calico.md
----
unversioned-warning:
not printing failed chunk: too many lines
contents were modified

FAIL: changes needed but not made due to --verify
/workspace/kubernetes/docs/ is out of date. Please run hack/update-generated-docs.sh
!!! Error in ./hack/../hack/verify-generated-docs.sh:28
  '"${KUBE_ROOT}/hack/after-build/verify-generated-docs.sh" "$@"' exited with status 1
Call stack:
  1: ./hack/../hack/verify-generated-docs.sh:28 main(...)
Exiting with status 1
FAILED

**Comment by caseydavenport** [comment]
@thockin - This appears to be failing for me on master as well.

```
+++ [0204 16:26:26] Building go targets for linux/amd64:
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genbashcomp
    cmd/mungedocs
+++ [0204 16:26:37] Placing binaries
output: fatal: Not a valid object name upstream/release-1.1
,
ERROR: exit status 128
`git ls-tree -r --name-only upstream/release-1.1 failed. We'll ignore this error locally, but Jenkins may pick an error. Munger uses the output of this command to determine in unversioned warning, if it should add a link to the doc in release branch.
output: fatal: Not a valid object name upstream/release-1.1
```

Any ideas?

**Comment by caseydavenport** [comment]
Looks like it was expecting my git remote to be named `upstream` rather than `origin`. 

After renaming, I managed to run `hack/update-generated-docs.sh`, so hopefully should pass this time.

**Comment by caseydavenport** [comment]
@thockin - docs check passes now, should be good to go :)

**Comment by thockin** [comment]
add to whitelist

**Pull request merged**
