### PR TITLE
Add test for --quiet flag for kubectl run

### PR DESCRIPTION
**Pull request by ardnaxelarak**
This adds a test for the changes introduced in #30247 and #28801.

Ref #28695

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30701)

### CODE REVIEW

**Comment by spxtr** [comment]
ok to test

**Comment by MHBauer** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30701)*

**Comment by janetkuo** [comment]
@k8s-bot unit test this issue: #30711

**Comment by janetkuo** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/e2e/kubectl.go, line 1133 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30701#-KPKX3rky3LdYH_20abc:-KPKX3rky3LdYH_20abd:bb2j51s) ([raw file](https://github.com/kubernetes/kubernetes/blob/9dca79c6f94649f3e8c8b7c34f1bc9a9c8424267/test/e2e/kubectl.go#L1133)):*
> ```Go
> 			defer t.Stop()
> 			// TODO: remove sleep when attach works immediately
> 			stdout, stderr := framework.NewKubectlCommand(nsFlag, "run", jobName, "--image="+busyboxImage, "--quiet", "--rm", "--restart=Never", "--stdin", "--", "sh", "-c", "sleep 3; echo output; sleep 3").
> ```

Suggest adding "--generator=job/v1" and "--attach". Although it'll give you the same result, we can make sure that we're testing the same thing, just in case some defaults are changed in the future.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30701)*

**Comment by janetkuo** [comment]
@k8s-bot node e2e test this issue: #30719

**Comment by MHBauer** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/e2e/kubectl.go, line 1133 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30701#-KPKX3rky3LdYH_20abc:-KPKhsa6DDBazK7aN_P_:bjzsuus) ([raw file](https://github.com/kubernetes/kubernetes/blob/9dca79c6f94649f3e8c8b7c34f1bc9a9c8424267/test/e2e/kubectl.go#L1133)):*
<details><summary><i>Previously, janetkuo (Janet Kuo) wrote…</i></summary>
> Suggest adding "--generator=job/v1" and "--attach". Although it'll give you the same result, we can make sure that we're testing the same thing, just in case some defaults are changed in the future.
</details>
I concur.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30701)*

**Comment by ardnaxelarak** [comment]
> Suggest adding "--generator=job/v1" and "--attach". Although it'll give you the same result, we can make sure that we're testing the same thing, just in case some defaults are changed in the future.

Added.

**Comment by janetkuo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30701#-:-KPPuT7q_M2Y6a_6_SGL:bnfp4nl)*

**Comment by janetkuo** [comment]
Tests failed; this is likely to be flaky

**Comment by janetkuo** [comment]
It's likely that there's bug in `kubectl run` or `kubectl run --quiet` which caused the flake

**Comment by janetkuo** [comment]
I sent #31383 for the test flake.

**Comment by ardnaxelarak** [comment]
> I sent #31383 for fixing the test flake. 

That isn't going to fix it, because the test is checking that both STDOUT and STDERR don't contain anything except for the output (since some of the messages that `--quiet` suppresses go to STDERR)
But I don't think we want `--quiet` suppressing this message, so I'm not sure where to go with this test. If the error attaching is because the process has already finished we could increase the `sleep` in the test?

**Comment by ardnaxelarak** [comment]
Looks like that last failure was because I missed a merge conflict in rebasing. Fixed.

**Comment by janetkuo** [comment]
> If the error attaching is because the process has already finished we could increase the sleep in the test?

Yes increasing `sleep` might help.

**Pull request merged**
