### PR TITLE
Handle error return from http.NewRequest()

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
In receiveChallengeFromLoginServer, the error return from http.NewRequest is ignored.

This PR checks the error return.

```release-note
NONE
```

### CODE REVIEW

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Comment by tedyu** [comment]
thanks, @andyzhangx for the review

**Comment by andyzhangx** [comment]
> thanks, @andyzhangx for the review

thanks for the contribution!

**Pull request merged**
