### PR TITLE
remove redundant carriage return for readable

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

remove redundant carriage to make it more readable.

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by dixudx** [comment]
@cblecker pls label LGTM. Thx.

**Comment by dixudx** [comment]
The failed `pull-kubernetes-unit` test seems unrelated to this PR.

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by dixudx** [comment]
@cblecker Waiting for your LGTM and release note label. Thanks.

**Pull request merged**
