### PR TITLE
Fix tracing wrapper comment

### PR DESCRIPTION
**Pull request by CatherineF-dev**
#### What type of PR is this?
/kind documentation

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change? No.

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
Thanks.

**Review by dashpole — APPROVED** [review]
/lgtm

**Pull request merged**
