### PR TITLE
clean up e2e tests with right version of pause image. 

### PR DESCRIPTION
**Pull request by dchen1107**
@mattmoor

### CODE REVIEW

**Comment by mattmoor** [comment]
LGTM

**Comment by ashcrow** [comment]
Is the image only available on ```beta.gcr.io``` or will this be updated to ```gcr.io```?

**Comment by dchen1107** [comment]
This image with tag 2.0 is only available on beta.gcr.io. We are using beta.gcr.io to activate v2 registry, and leave gcr.io only serve v1. cc/ @mattmoor to correct me here. Thanks!

**Comment by mattmoor** [comment]
FWIW, `beta.gcr.io` == `gcr.io` from a storage perspective.

You can pull `gcr.io/google_containers/pause:2.0`, but it will serve over the v1 registry API.

When we GA v2, `gcr.io/google_containers/pause:2.0` will start using v2 as well (for capable clients).

**Pull request merged**
