### PR TITLE
Automated cherry pick of #70663: update  godeps for golang.org/x/net/... to

### PR DESCRIPTION
**Pull request by wenjiaswe**
Cherry pick of #70663 on release-1.10.

#70663: update  godeps for golang.org/x/net/... to

### CODE REVIEW

**Comment by MaciekPytel** [comment]
@wenjiaswe
This looks rather scary and the PR to master has only merged ~20 hours ago. I don't think it's safe to merge immediately before 1.10.10 with so little soak time. Let's give it some more time on master and include it in 1.10.11 instead.

If you think it's absolutely critical this makes it into 1.10.10 please ping me asap.

**Comment by wenjiaswe** [comment]
@MaciekPytel , thank you very much, I think 1.10.11 is good.

**Comment by MaciekPytel** [comment]
I just realised - this bumps the relevant libraries to the same commit in 1.10 and master. This commit seems to be from go1.10 branch. However, kubernetes 1.10 is using go1.9. Are we sure this is the right think to do? @wenjiaswe @lavalamp

**Comment by MaciekPytel** [comment]
@wenjiaswe @lavalamp Can you reply to my question above? I want to be sure we're doing the right thing before merging. 

Note that 1.10.12 will be the last patch for 1.10, so this must go in now if we want it in 1.10 at all.

**Comment by wenjiaswe** [comment]
@MaciekPytel, I should have looked into this earlier. Right now,  I am not very confident to say how safe it is, especially this is the last patch release for 1.10. Maybe we just drop this PR for 1.10?

**Comment by MaciekPytel** [comment]
If we're not convinced it's safe I think dropping the PR is the right choice. Closing the PR, please re-open if anything changes.

**Pull request closed without merging**
