### PR TITLE
Remove Istio manifests and configure-helper code

### PR DESCRIPTION
**Pull request by ostromart**
/kind cleanup
/sig cluster-lifecycle

**What this PR does / why we need it**:
Istio as addon support was originally planned to go through OSS k8s, but due to concerns about having large yaml manifests as part of OSS image, this never went beyond 0.8. Now support is fully moved into internal Google fork for GKE use only, therefore no one is using these manifests anymore. 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by krzyzacy** [comment]
/ok-to-test

I don't have approve rights here...

**Comment by mikedanese** [comment]
Please rebase ontop of a recent master branch. Most of this happened in https://github.com/kubernetes/kubernetes/pull/67549

**Comment by mikedanese** [comment]
Shouldn't this be a cherry pick if it's targeting release-1.11?

**Comment by ostromart** [comment]
Yes, you're right. However I've noticed that the cleanup there is incomplete. I will add another PR to master and cherry-pick both back.

**Pull request closed without merging**
