### PR TITLE
CRI-API - Add rootfs size to WindowsContainerResources

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

This PR adds a new field to `WindowsContainerResources` CRI-API objects that is used to specify the size of the rootfs/scratch space used for Windows containers.

This value defaults to 20Gb on Windows.
This value can also either be specified per container when starting containers with Docker cli with `--storage-opt` and can also be set globally by specifying `storage-opts` in the docker config.

Currently we cannot change this value from the 20Gb default in Kubernetes clusters using containerd as the container runtime.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
This PR only adds the new field to the CRI-API field.

We are doing this so that after 1.24 releases containerd can add support for the new field and hopefully have full support in the  1.7 release.

SIG-Windows will create a KEP in the 1.25 release to cover the Kubernetes related changes to expose this new value in the pod spec.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

More information on how the rootfs / scratch space for Windows containers can be found at https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-storage

```docs

```

/sig windows
/sig node
/milestone v1.24

### CODE REVIEW

**Comment by dcantah** [comment]
cc @kevpar. Does this seem sound to you? This seems like a much needed addition to me

**Comment by jterry75** [comment]
Only question I have is if this will be per container as the change in the proto is or if its per sandbox. Do we need both?

**Comment by marosset** [comment]
> Only question I have is if this will be per container as the change in the proto is or if its per sandbox. Do we need both?

I'd **like** it to be per-container.
We'll need to do some design work in 1.25 to see how/where to expose this in the pod-specs tho...

**Comment by dcantah** [comment]
I'd prefer to have this be per container if possible.. I think that's the main advantage for this if its on the spec itself

**Comment by dcantah** [comment]
Curious why the other _bytes fields are int64's, but that seems to be the convention

**Comment by marosset** [comment]
> Curious why the other _bytes fields are int64's, but that seems to be the convention

I had the same question...

**Comment by marosset** [comment]
/assign @sjenning @murnalp 
For node review / approval

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
