### PR TITLE
Fix deadlock in ready test

### LINKED ISSUE #116225: [Flake] Test_newReadyRacy flaking
https://github.com/kubernetes/kubernetes/pull/116024 added a test that is flaking at a ~3% failure rate with `stress`:

```
go test -race -c k8s.io/apiserver/pkg/storage/cacher
stress ./cacher.test -test.run Test_newReadyRacy
```

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/pull/116024#discussion_r1123420776_
            
/sig api-machinery
/assign @aojea
/cc @wojtek-t
/kind failing-test

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix https://github.com/kubernetes/kubernetes/issues/116225

```release-note
NONE
```

/kind flake
/sig api-machinery
/priority important-soon

/assign @aojea

### CODE REVIEW

**Comment by aojea** [comment]
yeah, it can deadlock, great catch
/lgtm

**Comment by aojea** [comment]
/hold

this still can race

**Comment by wojtek-t** [comment]
> if there is a deadlock and the context is cancaled it will return an error, 

ok - good catch, forgot about it.

Yeah - what you have makes sense - changing.

**Pull request merged**
