### PR TITLE
Remove Set() from storage.Interface.

### LINKED ISSUE #20963: Remove Set() method from storage.Interface
Set method from storage.Interface:
https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/interfaces.go#L91

is used only in few tests. We should get rid of it completely.

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix #20963

### CODE REVIEW

**Comment by wojtek-t** [comment]
@hongchaodeng - FYI

**Comment by wojtek-t** [comment]
@lavalamp - can you please take a look?

**Comment by timothysc** [comment]
So it looks like it was only leveraged by the tests, and the registry uses mostly GuarenteedUpdate?

**Comment by wojtek-t** [comment]
@timothysc - yes, the registry didn't use Set() at all - that's why the change is safe in my opinion

**Comment by wojtek-t** [comment]
@lavalamp - friendly ping

**Comment by lavalamp** [comment]
@krousey can you take this review?

**Comment by wojtek-t** [comment]
Trivial rebase - readding lgtm label.

**Pull request merged**
