### PR TITLE
bump golang to 1.23.2

### PR DESCRIPTION
**Pull request by haitch**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

- Bump images, dependencies and versions to go 1.23.2
- bump distroless iptables image to 0.6.4

#### Which issue(s) this PR fixes:

xref: https://github.com/kubernetes/release/issues/3778 

#### Does this PR introduce a user-facing change?

```release-note
Kubernetes is now built with go 1.23.2
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by haitch** [comment]
Thanks @pacoxu , I mark this one as draft since it depends on this one: https://github.com/kubernetes/k8s.io/pull/7415 , can you put a ok-to-test label there?

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve
/assign @dims

**Pull request merged**
