### PR TITLE
Update kube-dns to 1.14.4

### PR DESCRIPTION
**Pull request by bowei**
- Fixes broken arm dnsmasq image
- Fixes kube-dns log spam issue

https://github.com/kubernetes/dns/issues/111

```release-note
none
```

### CODE REVIEW

**Comment by luxas** [comment]
/lgtm

Will test on an arm machine in a minute

**Review by MrHohn — APPROVED** [review]

**Comment by luxas** [comment]
Can confirm that this fixes the issue on arm...

**Comment by ixdy** [comment]
thanks!

**Comment by ixdy** [comment]
@bowei are you going to open a cherry-pick PR?

**Comment by bowei** [comment]
* 1.6: https://github.com/kubernetes/kubernetes/pull/48095
* 1.7: https://github.com/kubernetes/kubernetes/pull/48090

**Comment by caesarxuchao** [comment]
It's cherrypicked to release-1.7 already. The cherrypick bot should had removed the cherrypick-approved label. I'll manually remove the label.

**Pull request merged**
