### PR TITLE
convert int to int32 in intstr.FromInt

### PR DESCRIPTION
**Pull request by huangjiuyuan**
**What this PR does / why we need it**:
A `TODO` was left in `staging/src/k8s.io/apimachinery/pkg/util/intstr/intstr.go` which required converting `int` to `int32` as the parameter of function `FromInt`.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

`NONE`

### CODE REVIEW

**Comment by mattmoyer** [comment]
cc @smarterclayton who added the original TODO (in https://github.com/kubernetes/kubernetes/pull/17353).

**Comment by xiangpengzhao** [comment]
@huangjiuyuan have any cycles to rebase the PR?

**Comment by huangjiuyuan** [comment]
@xiangpengzhao It seems rebase it took more work than submit a new PR, I will submit a new PR instead.

**Comment by xiangpengzhao** [comment]
@huangjiuyuan SGTM :)

**Comment by sttts** [comment]
/approve no-issue
lgtm

Please rebase.

**Pull request closed without merging**
