### PR TITLE
upgrade azure-sdk-for-go to v43.0.0

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
 /kind feature

**What this PR does / why we need it**:
upgrade azure-sdk-for-go to v43.0.0, this is the first step to support azure file based NFS service in CSI driver not in this k/k.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
```console
hack/pin-dependency.sh github.com/Azure/azure-sdk-for-go v43.0.0+incompatible
hack/update-vendor.sh
```

**Does this PR introduce a user-facing change?**:

```release-note
none
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
none
```

/kind bug
/assign @feiskyer 
/priority important-soon
/sig cloud-provider
/area provider/azure

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Comment by feiskyer** [comment]
@dims  could you help to approve the vendor updates?

**Comment by andyzhangx** [comment]
/assign @dims
thanks

**Comment by dims** [comment]
@liggitt we need root approval on this one. this looks ready 

/lgtm

**Comment by liggitt** [comment]
keeping up to date with dependency updates is good, but is progress being made on the azure CSI replacement? I thought the intent was to stop adding new features to the in-tree storage drivers and move to the CSI drivers.

**Comment by andyzhangx** [comment]
> keeping up to date with dependency updates is good, but is progress being made on the azure CSI replacement? I thought the intent was to stop adding new features to the in-tree storage drivers and move to the CSI drivers.

Hi @liggitt we are not adding new features to this in-tree driver, it's only upgrade go sdk version. Azure CSI drivers are using this azure cloud provider as lib, so we are still maintaining this lib in k/k.

**Comment by liggitt** [comment]
got it, thanks. that might be helpful to note in the description, I was confused by the "this is the first step to support azure file based NFS service" statement

**Comment by andyzhangx** [comment]
> got it, thanks. that might be helpful to note in the description, I was confused by the "this is the first step to support azure file based NFS service" statement

thanks. updated with this:
```
this is the first step to support azure file based NFS service in CSI driver not in k/k.
```

**Comment by andyzhangx** [comment]
could you approve @liggitt thanks.

**Pull request merged**
