### PR TITLE
Switch to versioned ListOptions in client.

### PR DESCRIPTION
**Pull request by wojtek-t**
This is Part1 of follow-up from discussion in:
https://github.com/kubernetes/kubernetes/pull/17822

Mostly mechanical changes. The non-mechanical ones are under:
- pkg/api/...
- pkg/apis/...

### CODE REVIEW

**Comment by wojtek-t** [comment]
@smarterclayton - this PR is ready for review.
Can you please take a look?

**Comment by wojtek-t** [comment]
To clarify - the next PR will change the serve-side code and will remove the unversioned.ListOptions type completely.

**Comment by smarterclayton** [comment]
LGTM

**Comment by smarterclayton** [comment]
Going to merge directly because this is a prime candidate for rebase hell.

**Comment by wojtek-t** [comment]
Thanks @smarterclayton !

Will send the next PR later today or morning tomorrow

**Pull request merged**
