### PR TITLE
fix: data race when hijack klog

### PR DESCRIPTION
**Pull request by calvin0327**
Signed-off-by: calvin <wen.chen@daocloud.io>

#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes data race when hijack klog output https://github.com/kubernetes/kubernetes/pull/106796#pullrequestreview-859893173

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by endocrimes — APPROVED** [review]
/lgtm

**Comment by jonyhy96** [comment]
ping @sjenning for approve

**Comment by utkarsh348** [comment]
This particular change has not resolved the underlying issue of the race condition in the nodeshutdown unit test.
It has been formally raised [108040](https://github.com/kubernetes/kubernetes/issues/108040)

**Pull request merged**
