### PR TITLE
rkt: fix KillPod() to return the correct error message.

### PR DESCRIPTION
**Pull request by yifan-gu**
cc @kubernetes/sig-node @aaronlevy

### CODE REVIEW

**Comment by yifan-gu** [comment]
cc @jonboulle

**Comment by jonboulle** [comment]
LGTM

**Comment by justinsb** [comment]
@k8s-bot test this [submit-queue is verifying that this PR is safe to merge]

**Comment by justinsb** [comment]
I apologize for the above incorrect comment which referenced me. I was working on the munger locally & it "went rogue" - see #22136. I do not believe on this issue there was any consequence beyond spam (but please notify me or update the issue if this is not correct).

**Pull request merged**
