### PR TITLE
Update cni-plugins to v1.4.1

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Updated cni-plugins to the latest release v1.4.1.
#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
Updated cni-plugins to v1.4.1.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm

please add milestone if you need this for v1.30

**Comment by saschagrunert** [comment]
> please add milestone if you need this for v1.30

I would not include it, What does @kubernetes/release-engineering thinks?

**Comment by saschagrunert** [comment]
> @saschagrunert This is a patch bump so I think it's safe to include it in v1.30.1

Do you mind to clarify: v1.30.1 as cherry-pick or v1.30.0 as merge now?

**Comment by xmudrii** [comment]
@saschagrunert I mean as a cherry-pick after v1.30.0 is out

**Comment by saschagrunert** [comment]
I think this job fails every time.

**Comment by dims** [comment]
@saschagrunert yes, please ignore the job

/skip

**Pull request merged**
