### PR TITLE
vendor: upgrade cadvisor to 0.40.0

### PR DESCRIPTION
**Pull request by harche**
Signed-off-by: Harshal Patil <harpatil@redhat.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Bumps cadvisor to 0.40.0

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by rphillips** [comment]
Dependency error here: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/104392/pull-kubernetes-dependencies/1427231644388954112

**Comment by bobbypage** [comment]
We can't do this yet due to dependency issues -- cAdvisor upgrade in k/k is blocked on https://github.com/google/cadvisor/pull/2908

**Comment by harche** [comment]
> We can't do this yet due to dependency issues with containerd go module depending ok k/k creating circular dependency -- cAdvisor upgrade in k/k is blocked on [google/cadvisor#2908](https://github.com/google/cadvisor/pull/2908)

Oh ok, thanks for that info.

**Comment by pacoxu** [comment]
/close
since #106282 is merged. (vendor: Bump cAdvisor to v0.43.0 )

**Pull request closed without merging**
