### PR TITLE
apiextensions-apiserver: fix build

### PR DESCRIPTION
**Pull request by hongchaodeng**
Can't build CRD due to this bug. This PR will fix it.

```release-notes
Fix compilation of k8s.io/apiextensions-apiserver
```

### CODE REVIEW

**Comment by hongchaodeng** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by hongchaodeng** [comment]
@deads2k Can you approve this?

**Comment by deads2k** [comment]
> @deads2k Can you approve this?

sorry, forgot the issue change thing.

/approve no-issue

**Comment by hongchaodeng** [comment]
@deads2k Thanks!

**Comment by nikhita** [comment]
Should this be cherry-picked to 1.7 since the [godoc for k8s.io/apiextensions-apiserver](http://godoc.org/k8s.io/apiextensions-apiserver) does not contain the packages `pkg/apis/apiextensions` and `pkg/apis/apiextensions/v1beta1`? This PR will fix it.

If agreed, I can create a cherry-pick PR for that.

**Comment by deads2k** [comment]
> Should this be cherry-picked to 1.7 since the godoc for k8s.io/apiextensions-apiserver does not contain the packages pkg/apis/apiextensions and pkg/apis/apiextensions/v1beta1? This PR will fix it.

It's fine to cherry-pick, but I'm actually not sure if we sync branches.  @caesarxuchao 

@nikhita the bot is currently of while k8s.io/api is prepped.

**Comment by nikhita** [comment]
We now have release branches on `k8s.io/apiextensions-apiserver` (we didn't have this before). The 1.7 release branch on `k8s.io/apiextensions-apiserver` does not build because of the typo "apiextension-server" here: https://github.com/kubernetes/apiextensions-apiserver/blob/release-1.7/pkg/apis/apiextensions/doc.go#L21.

This can be fixed by cherry-picking this PR. Created https://github.com/kubernetes/kubernetes/pull/53426.

cc @wojtek-t @sttts

**Pull request merged**
