### PR TITLE
[WIP] Updated kube-scheduler to use client-go.

### LINKED ISSUE #44188: Updated scheduler to use client-go
**Is this a BUG REPORT or FEATURE REQUEST? (choose one)**:
feature request

**Kubernetes version (use kubectl version)**:
master branch

**What happened**:
According to discussion at kubernetes/client-go#136 , we'd like to upgrade `scheduler` to use client-go after lister, informer is ready.

### PR DESCRIPTION
**Pull request by k82cn**
**What this PR does / why we need it**:
Updated kube-scheduler to use client-go instread of k8s upstream.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #44188

**Special notes for your reviewer**:
This only kube-scheduler part; it also dependent kubelet & client-go enhancement.

**Release note**:

```release-note-none
```

### CODE REVIEW

**Comment by deads2k** [comment]
Looks like this is going to be a large pull.  Can you separate it out into at least two commits?  One with the mechanical changes (import changes) and one with non-mechanical changes (any additional fitting required for type differences like pointer versus non-pointer).

**Comment by k82cn** [comment]
@deads2k , I'd like to trace client-go enhancement at https://github.com/kubernetes/kubernetes/issues/44851 . I don-t want to make those enhancement specific to kube-scheduler, it's better to be for all components if we want other components use client-go.

**Comment by k82cn** [comment]
I'll follow up this PR in 1.8.

**Pull request closed without merging**
