### PR TITLE
Modify the input parameter to the method kube::build::run_build_command_ex

### PR DESCRIPTION
**Pull request by timyinshi**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
The parameter to the method kube::build::run_build_command_ex is incorrect, causing this method to not be executed

**Which issue(s) this PR fixes**:
Fixes #
After modifying the input parameter to the method kube::build::run_build_command_ex, the method executes as normal

**Special notes for your reviewer**:
This bug was discovered while executing the make quick-release command

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Comment by timyinshi** [comment]
I signed it

**Comment by spiffxp** [comment]
/ok-to-test
Thanks for the PR!  In order to get rid of the `do-not-merge/contains-merge-commits` label you're going to need to rebase this such that it doesn't have a merge commit in it

**Comment by spiffxp** [comment]
Can you explain a little bit more about your build / dev environment please? What was the output when you ran this script? What OS, what shell, how were you trying to invoke `make quick-release` etc.

I ask because `make quick-release` is a pretty high-traffic path for developers on this project, and I'm not sure I'm aware of others having problems with it?

**Comment by timyinshi** [comment]
@spiffxp 
I am building in China, and it is difficult to connect Google image, so I am thinking of buying American machine to build, and see if there is any problem. Thank you for your reply.

**Comment by spiffxp** [comment]
@timyinshi this appears to break the build, and I can't tell what bug it's fixing, do you plan on moving forward with this PR?

**Comment by timyinshi** [comment]
@spiffxp
Ok, I will cancel this pr for the time being. Thanks a lot

**Pull request closed without merging**
