### PR TITLE
fix spelling mistake

### PR DESCRIPTION
**Pull request by xieyanker**
**What type of PR is this?**

> /kind cleanup

**What this PR does / why we need it**:

Cleanup: fix some typos in code comment

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
thanks
we are in code freeze and spelling fixes we have to hold after 1.16 is released.

**Comment by xieyanker** [comment]
@neolit123 @nikhita @liggitt The typo has been fixed by https://github.com/kubernetes/kubernetes/pull/82391, however, it was commited behind mine, it seems that not fair to me.

**Comment by neolit123** [comment]
@xieyanker 
it's ok.
things like that happen when they are multiple people working on the project without coordination. there are plenty of typos to be fixed, so please feel free to send more PRs!

thanks.

/close

**Comment by xieyanker** [comment]
@neolit123 OK, and can you take a look at these two PRs I have commited?https://github.com/kubernetes/kubernetes/pull/82719 https://github.com/kubernetes/kubernetes/pull/82111

**Pull request closed without merging**
