### PR TITLE
Clean cinder detachlogerror

### LINKED ISSUE #50441: cinder calls detach disk even if nothing was mounted
@dims @anguslees - while reading some cinder code, i came accross [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/cinder/cinder.go#L332), we try to detach disk even if we didn't try to mount. Is this call mandatory ? (from what i recall AWS EBS do not have such mecanism) 

Also ping @saad-ali

### PR DESCRIPTION
**Pull request by yastij**
**What this PR does / why we need it**:

**Which issue this PR fixes** : fixes #50441

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by dims** [comment]
@yastij : can you please squash the commits, there are 4 but only one seems to have the code needed.

**Comment by dims** [comment]
@rootfs there are 4 commits, need to be squashed. only one of them is relevant. Can you please do a `/approve cancel` until that's fixed?

**Comment by yastij** [comment]
@dims @rootfs - fixed, I don't know why but seems that github diff saw two commits as missing on master, even if they're present, worked some magic git to fix it. can you approve/lgtm ?

**Comment by rootfs** [comment]
thanks @dims

**Comment by yastij** [comment]
@dims - can you remove the do-not-merge label ?

**Comment by dims** [comment]
Ouch! i don't have privileges to do that. We need to find someone who does

**Comment by jsafrane** [comment]
do-not-merge removed

**Comment by yastij** [comment]
@dims - my most feared label 😄

**Comment by dims** [comment]
@jsafrane w00t!

**Pull request merged**
