### PR TITLE
[Provider/Azure] remove extra Sprintf()

### PR DESCRIPTION
**Pull request by gaurav1086**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Remove extra Sprintf() within Fprintf()
**Which issue(s) this PR fixes**:

Fixes #
N/A
**Special notes for your reviewer**:
N/A
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by gaurav1086** [comment]
@andyzhangx lets merge this. Thanks.

**Comment by andyzhangx** [comment]
```
--- FAIL: TestNodeAddresses (0.02s)
    azure_instances_test.go:372: Test [NodeAddresses should get both ipV4 and ipV6 private addresses] unexpected error: invalid character 'v' after top-level value
    azure_instances_test.go:377: Test [NodeAddresses should get both ipV4 and ipV6 private addresses] unexpected ipAddresses: [], expected [{"Hostname" "vm1"} {"InternalIP" "10.240.0.1"} {"InternalIP" "1111:11111:00:00:1111:1111:000:111"}]
    azure_instances_test.go:392: Test [NodeAddresses should get both ipV4 and ipV6 private addresses] unexpected error: invalid character 'v' after top-level value
    azure_instances_test.go:396: Test [NodeAddresses should get both ipV4 and ipV6 private addresses] unexpected ipAddresses: [], expected [{"Hostname" "vm1"} {"InternalIP" "10.240.0.1"} {"InternalIP" "1111:11111:00:00:1111:1111:000:111"}]
    azure_instances_test.go:372: Test [NodeAddresses should get ipV4 private and public addresses] unexpected error: invalid character 'v' after top-level value
```

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve
thanks

**Comment by gaurav1086** [comment]
@andyzhangx looks like the test pull-kubernetes-e2e-kind is flaky. I have a couple PRs to fix some race condition in those tests. Otherwise this PR looks good. Let me know.

**Comment by gaurav1086** [comment]
` May 29 23:06:17.711: FAIL: pod communication failed `

**Pull request merged**
