### PR TITLE
modify imports' order

### PR DESCRIPTION
**Pull request by islinwb**
**What this PR does / why we need it**:
/kind cleanup
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
@islinwb thanks for cleaning that up! :+1: 

/retest

**Comment by islinwb** [comment]
@deads2k Could you take a look at this? This only changes the order of import.

**Comment by nikhita** [comment]
@islinwb did you do this manually or use a script?

If there is a script, it would be useful to incorporate into our CI. 
cc @cblecker

**Comment by nikhita** [comment]
/assign @deads2k @Random-Liu 
for approval

**Comment by deads2k** [comment]
/approve

I haven't done the review, but if someone does and tags it `lgtm`, I'd like to see this (or something like it) merged.

**Comment by mikedanese** [comment]
Was this change automated?

**Comment by islinwb** [comment]
@nikhita @mikedanese I use a shell script first and then check the changes manually.

**Pull request closed without merging**
