### PR TITLE
re-home juju related source

### LINKED ISSUE #2892: Tracking issue: new home for juju charm related work
In reference to https://github.com/kubernetes/kubernetes/pull/70430, we're looking for an appropriate home for code that lives in the deprecated `kubernetes/cluster/juju` tree:

https://github.com/kubernetes/kubernetes/tree/master/cluster/juju

We're leaning towards requesting a new `charms` repo in the kubernetes org; kubernetes-sigs was also suggested as a potential parent org. Questions/comments related to this move would be appreciated.

/cc @roberthbailey

### PR DESCRIPTION
**Pull request by kwmonroe**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Source from the `./cluster/juju` tree has been moved to a new [Charmed Kubernetes](https://github.com/charmed-kubernetes/) org.  This PR cleans out the juju subdirectory and adds a notice about where the source went.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/community/issues/2892

**Special notes for your reviewer**:
When merged, the only files remaining in the juju subdirectory will be `.gitignore`, `OWNERS`, and `README.md`.

**Does this PR introduce a user-facing change?**:

```release-note
Juju provider source moved to the Charmed Kubernetes org
```

### CODE REVIEW

**Comment by dims** [comment]
/ok-to-test

thanks @kwmonroe 

/assign @liggitt

**Comment by Cynerva** [comment]
/approve
/lgtm

:+1:

**Comment by neolit123** [comment]
> Source from the ./cluster/juju tree has been moved to a new Charmed Kubernetes org. This PR cleans out the juju subdirectory and adds a notice about where the source went.

thanks for the cleanup @kwmonroe 
:tada:

**Pull request merged**
