### PR TITLE
topologymanager: Promote support for improved multi-numa alignment in Topology Manager to GA

### PR DESCRIPTION
**Pull request by PiotrProkop**
…

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

* Promote TopologyManagerPolicyOptions feature to GA
* Promote PreferClosestNUMANodes TopologyManagerPolicyOption to stable

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
TopologyManagerPolicyOptions feature-flag is promoted to GA
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

- KEP: https://github.com/kubernetes/enhancements/pull/4079
- Enhancement issue: https://github.com/kubernetes/enhancements/issues/3545

### CODE REVIEW

**Review by ffromani — COMMENTED** [review]
LGTM, but this should be merged last right before we call the GA graduation done codewise.

**Comment by PiotrProkop** [comment]
@klueska e2e tests are merged. Can you review/approve this PR?

**Comment by PiotrProkop** [comment]
e2e tests are merged we can unhold the PR.

/unhold

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
