### PR TITLE
update hack/build-go to build federation/cmd/federated-apiserver as well

### PR DESCRIPTION
**Pull request by nikhiljindal**
federation/cmd/federated-apiserver was added in https://github.com/kubernetes/kubernetes/pull/23509

cc @jianhuiz

### CODE REVIEW

**Comment by nikhiljindal** [comment]
I dont know why it cant find `k8s.io/kubernetes/federation/cmd/federated-apiserver` on jenkins.
`hack/build-go.sh` works fine locally.

@ixdy Any idea? Is that something to do with the way we have setup jenkins

**Comment by ixdy** [comment]
@nikhiljindal does `make quick-release` work locally? It might be an issue with the dockerized crossbuild, since the unit/integration build worked without issue.

**Comment by ixdy** [comment]
I don't understand why crossbuild would fail, but it'd help to isolate to that vs. Jenkins if possible.

**Comment by luxas** [comment]
It seems like something is wrong with the dockerized build. 
It fails on `amd64` with the error `can't find package`. 
Maybe it's some `import` statement that is wrong?

**Comment by nikhiljindal** [comment]
You are right @ixdy!
`make quick-release` fails locally. So it is related to dockerized crossbuild. I would never have guessed that :)

**Comment by ixdy** [comment]
Ah, I think I know what's wrong. You need to update `kube::build::source_targets` in `build/common.sh`.

**Comment by nikhiljindal** [comment]
Awesome, thanks!
make quick-release passes locally now with that change.

Have updated the PR.
Hopefully Jenkins will be happy now.

**Comment by ixdy** [comment]
LGTM assuming everything builds this time :)

**Comment by nikhiljindal** [comment]
@k8s-bot e2e test this issue: https://github.com/kubernetes/kubernetes/issues/24619

**Comment by nikhiljindal** [comment]
`hack/build-go` keeps failing on travis with the following error:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

Not sure why. I have retried 3 times, and I dont see that error on any other PR. So looks like it is caused by this change.

**Comment by nikhiljindal** [comment]
oops. I didnt know that e2e-not-required ignores travis as well.
cc @k8s-oncall happy to revert this if you see travis failures on head due to this PR.

**Comment by krousey** [comment]
@nikhiljindal if https://travis-ci.org/kubernetes/kubernetes/builds/124875718 fails, please revert.

**Comment by nikhiljindal** [comment]
It failed.
Reverting: https://github.com/kubernetes/kubernetes/pull/24632

**Comment by ixdy** [comment]
I'm not sure it's your PR. I think Travis is just busted.

**Comment by ixdy** [comment]
https://travis-ci.org/kubernetes/kubernetes/builds/124842648 and https://travis-ci.org/kubernetes/kubernetes/builds/124875707 also failed before your PR merged.

**Pull request merged**
