### PR TITLE
Automated cherry pick of #24054

### PR DESCRIPTION
**Pull request by nikhiljindal**
Cherry pick of #24054 on release-1.2.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @bgrant0607

**Comment by nikhiljindal** [comment]
PR generated by running `./hack/cherry_pick_pull.sh upstream/release-1.2 24054` as per https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md#how-do-cherrypick-candidates-make-it-to-the-release-branch

**Comment by erictune** [comment]
lgtm

**Comment by nikhiljindal** [comment]
cc @roberthbailey I guess I need your approval to remove the do-not-merge label?

**Comment by roberthbailey** [comment]
As long as the original PR shows up on http://cherrypick.k8s.io/#/queue it'll get reviewed tomorrow.

**Comment by nikhiljindal** [comment]
@k8s-bot integration test this please

**Comment by nikhiljindal** [comment]
All tests pass now.
Adding back the LGTM tag.

**Comment by nikhiljindal** [comment]
unit test failed again. Its `pkg/registry/persistentvolumeclaim/etcd` this time.

@k8s-bot unit test this please

**Comment by nikhiljindal** [comment]
@k8s-bot keeps rerunning the tests, but is not merging the PR.
@k8s-oncall: Not sure if this requires a hand merge?

**Comment by lavalamp** [comment]
It's because you're at the top of the queue and the tests (at head) are flapping due to flakes.

**Comment by nikhiljindal** [comment]
@k8s-bot e2e test this issue: https://github.com/kubernetes/kubernetes/issues/21517

**Pull request merged**
