### PR TITLE
Initial TOC for the user guide.

### PR DESCRIPTION
**Pull request by bgrant0607**

### CODE REVIEW

**Comment by davidopp** [comment]
Will it be confusing to have a README.md and a user-guide.md?

**Comment by bgrant0607** [comment]
Was going to unify with user-guide.md in a later PR, but now that the move merged, I'll just do it now.

**Comment by bgrant0607** [comment]
Deduped

**Comment by bgrant0607** [comment]
Travis passed. Shippable failed due to fallout from the prior doc move:
```
the path "examples/multi-pod.yaml" does not exist
!!! Error in ./hack/test-cmd.sh:421
'kubectl create -f examples/multi-pod.yaml "${kube_flags[@]}"' exited with status 1
```
I'll try to rebase again to see if that fixes it, but I don't expect it to actually change the files in this PR.

**Comment by bgrant0607** [comment]
cc @thockin

**Comment by bgrant0607** [comment]
Another unrelated test failure on shippable:
```
services/cassandra
FAIL!
Get all -l'name=cassandra' {{range.items}}{{.metadata.name}}:{{end}}
Expected: cassandra:cassandra:cassandra:
Got: cassandra:cassandra:cassandra:cassandra-zqs8y:
767 ./hack/test-cmd.sh
!!! Error in ./hack/test-cmd.sh:50
```

Doc checks passed.

**Comment by bgrant0607** [comment]
All green now. Not sure what was up before.

**Pull request merged**
