### PR TITLE
Update dns

### PR DESCRIPTION
**Pull request by bowei**
```release-note
NONE
```

### CODE REVIEW

**Comment by bowei** [comment]
@k8s-bot gci gke e2e test this

**Comment by bowei** [comment]
@k8s-bot non-cri node e2e test this

**Review by pires — APPROVED** [review]

**Comment by bowei** [comment]
@pires -- /approve is needed now ...

**Comment by bowei** [comment]
@mikedanese @luxas @errordeveloper looks like this needs an approver

**Comment by luxas** [comment]
/approve

Thanks for updating kubeadm as well!

**Pull request merged**
