### PR TITLE
Add configurable return value for the pause container

### PR DESCRIPTION
**Pull request by jprzychodzen**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This PR allows pause container to configure it's return value by `PAUSE_EXIT_CODE` env. Default value is not changes (`0`).

This allows to use pause container for tests when pods should fail, instead of terminating successfully.

#### Does this PR introduce a user-facing change?
Only for pause container. I guess this is not a release-note tag.

### CODE REVIEW

**Comment by BenTheElder** [comment]
Why don't we use agnhost instead of adding test only code to pause?

**Comment by BenTheElder** [comment]
Rolling out new versions of pause is also pretty involved (all the miscellaneous projects need to keep up including the cluster provisioners plus containerd, cri-o, dockershim / kubelet), I don't think we should touch pause unless it's necessary. 

We also want pause to be as tiny as possible given its critical role in all pods and we have to consider windows nodes.

**Comment by jprzychodzen** [comment]
Hi Ben, thanks for pointing out to agnhost.

It seems that we are misusing  pause pod in scalability tests - for example here: https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/testing/load/job.yaml

I will prepare a similar change for agnhost.

**Pull request closed without merging**
