### PR TITLE
Removed flaky test.  

### PR DESCRIPTION
**Pull request by markturansky**
I removed the test that was causing so many flakes (and only recently after I added other integration tests in the same area).  this integration test _only_ tested binding.
1.  The newer integration tests for Recycling/Deleting both involve binding.
2.  There are tons of unit tests that cover complex binding scenarios.

I have another integration test coming that will work with Creaters.   Between the 3, integration is sufficiently covered.

@saad-ali

### CODE REVIEW

**Comment by markturansky** [comment]
I merged the Recycler and Deleter test so that they run serially.

Both start a master, deleted all etcd keys, and wait for objects to reach a certain phase.   If the tests are run concurrently, then the objects expected for waits will not be there.  Timeouts can occur.

**Comment by markturansky** [comment]
Intended to fix: https://github.com/kubernetes/kubernetes/issues/14107 and https://github.com/kubernetes/kubernetes/issues/14284

**Comment by bgrant0607** [comment]
cc @saad-ali

**Comment by bgrant0607** [comment]
cc @erictune

**Comment by erictune** [comment]
LGTM

**Comment by saad-ali** [comment]
The other (non-deleted) tests also depend on watch resourceVersion==0 behavior that will change with #13969. Those should be modified before they become a problem.

**Comment by saad-ali** [comment]
This looks like it broke integrations tests:

```
10:47:10 # k8s.io/kubernetes/test/integration
10:47:10 _output/local/go/src/k8s.io/kubernetes/test/integration/persistent_volumes_test.go:98: no new variables on left side of :=
10:47:10 _output/local/go/src/k8s.io/kubernetes/test/integration/persistent_volumes_test.go:99: no new variables on left side of :=
10:47:10 _output/local/go/src/k8s.io/kubernetes/test/integration/persistent_volumes_test.go:100: no new variables on left side of :=
10:47:10 _output/local/go/src/k8s.io/kubernetes/test/integration/persistent_volumes_test.go:102: no new variables on left side of :=
10:47:10 _output/local/go/src/k8s.io/kubernetes/test/integration/persistent_volumes_test.go:106: no new variables on left side of :=
10:47:10 _output/local/go/src/k8s.io/kubernetes/test/integration/persistent_volumes_test.go:111: no new variables on left side of :=
10:47:10 _output/local/go/src/k8s.io/kubernetes/test/integration/persistent_volumes_test.go:121: no new variables on left side of :=
10:47:10 _output/local/go/src/k8s.io/kubernetes/test/integration/persistent_volumes_test.go:147: watch.Deleted undefined (type watch.Interface has no field or method Deleted)
10:47:10 FAIL	k8s.io/kubernetes/test/integration [build failed]
10:47:10 +++ [0922 10:47:10] Saved JUnit XML test report to /var/lib/jenkins/jobs/kubernetes-test-go/workspace/_artifacts/junit_v1,experimental-v1_20150922-104654.xml
10:47:10 !!! Error in /jenkins-master-data/jobs/kubernetes-test-go/workspace/hack/test-go.sh:217
10:47:10   'return ${rc}' exited with status 2

```

**Comment by markturansky** [comment]
yes, fixing the hastily refactored code.  one sec

**Comment by markturansky** [comment]
https://github.com/kubernetes/kubernetes/pull/14372

**Pull request merged**
