### PR TITLE
Fix kubectl explain to shows enum for field types if they were defined

### LINKED ISSUE #1538: Feature Request: show enum values in kubectl explain
### What happened?

CRDs have information about possible enum values in their spec. However, when examining them with `kube explain ` they're not shown, although they are valuable when creating the descriptor of the CRD.

### What did you expect to happen?

It'd be great if the enum value was visible in the output of a specific property. E.g. if you invoke `kubectl explain kubectl explain AlertmanagerConfig.spec.route.matchers.matchType`   you'd see

```
KIND:     AlertmanagerConfig
VERSION:  monitoring.coreos.com/v1alpha1

FIELD:    matchType <string> (enum: !=, =, =~, !~)

DESCRIPTION:
     Match operation available with AlertManager >= v0.22.0 and takes precedence
     over Regex (deprecated) if non-empty.
```
rather than just `FIELD:    matchType <string>` currently.

I'd even be interesting to see the validation code in `  x-kubernetes-validations`, but that might be noisy, of course, maybe that might be a CLI option.

This reduces the need for documentation on websites (both maintaining and finding it) and the (trial and) error for creating CRD instance - depending on whether the docs are outdated or non-existing :)

### How can we reproduce it (as minimally and precisely as possible)?

Any CRD with enum property, e.g. https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml#L71

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.11
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by ah8ad3**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Show enum values in kubectl explain if they were defined. Changes are:
1. Add `extractEnum` function to kubectl explain template(plaintext.tmpl) to extract enum from schema and style it like `(enum: !=, =, =~, !~)`
2. Add tests in plaintext_test.go to verify that this new function works fine
3. Use the function in two parts of plaintext.tmpl after field definitions to show messages like this: 
`FIELD:    matchType <string> (enum: !=, =, =~, !~)`
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubectl/issues/1538

#### Does this PR introduce a user-facing change?

```release-note
Show enum values in kubectl explain if they were defined
```

### CODE REVIEW

**Comment by mpuckett159** [comment]
I think it would make more sense (and look a bit more aesthetically pleasing, to me anyway) if we rendered this like:

```
KIND:         AlertmanagerConfig
VERSION:  monitoring.coreos.com/v1alpha1

FIELD:    matchType <string> 
ENUM:   !=, =, =~, !~

DESCRIPTION:
     Match operation available with AlertManager >= v0.22.0 and takes precedence
     over Regex (deprecated) if non-empty.
```

This way it is a little more clear exactly what is happening by listing the enums are property of the field instead of within the type data, and matches the formatting a bit more cleanly as well.

**Comment by ah8ad3** [comment]
@mpuckett159 Thanks for the response.
It is actually a good idea to show it like that. I have updated the code now there is two type of styles that can show enums
when we explain one field we will see it like this:
```
FIELD: matchType <string>
ENUM: !=, =, =~, !~
```
and when we explain list of fields we will see it like this
```
FIELDS:
  matchType     <string> enum: !=, =, =~, !~
    Match operation available with AlertManager >= v0.22.0 and takes precedence
    over Regex (deprecated) if non-empty.
```

**Comment by mpuckett159** [comment]
Agreed yes just rerun your retest command in the comments. FYI you don't have to instruct the bot to retest on new commits pushed to the branch it will automatically detect and rerun jobs for you.

**Comment by ah8ad3** [comment]
@mpuckett159
Thanks again, i really appreciate your help, it looks like every test passes.

**Review by alexzielenski — COMMENTED** [review]
Thanks @ah8ad3 for the high quality PR and @mpuckett159 for reviews! This is looking in great shape. One thing I'd like to see a explored a bit more is how long lists of enums look. Specifically I think if the list is too long in the simple view, it should be truncated. and for the long form view, we should split the enums to separate lines:

Here is an example schema with more/longer case names:

```json
    "io.k8s.api.core.v1.HostPathVolumeSource": {
        "description": "Represents a host path mapped into a pod. Host path volumes do not support ownership management or SELinux relabeling.",
        "type": "object",
        "required": ["path"],
        "properties": {
          "path": {
            "description": "path of the directory on the host. If the path is a symlink, it will follow the link to the real path. More info: https://kubernetes.io/docs/concepts/storage/volumes#hostpath",
            "type": "string",
            "default": ""
          },
          "type": {
            "description": "type for HostPath Volume Defaults to \"\" More info: https://kubernetes.io/docs/concepts/storage/volumes#hostpath\n\nPossible enum values:\n - `\"\"` For backwards compatible, leave it empty if unset\n - `\"BlockDevice\"` A block device must exist at the given path\n - `\"CharDevice\"` A character device must exist at the given path\n - `\"Directory\"` A directory must exist at the given path\n - `\"DirectoryOrCreate\"` If nothing exists at the given path, an empty directory will be created there as needed with file mode 0755, having the same group and ownership with Kubelet.\n - `\"File\"` A file must exist at the given path\n - `\"FileOrCreate\"` If nothing exists at the given path, an empty file will be created there as needed with file mode 0644, having the same group and ownership with Kubelet.\n - `\"Socket\"` A UNIX socket must exist at the given path",
            "type": "string",
            "enum": [
              "",
              "BlockDevice",
              "CharDevice",
              "Directory",
              "DirectoryOrCreate",
              "File",
              "FileOrCreate",
              "Socket"
            ]
          }
        }
      }
```

(Also note that empty string is a valid case, I'd be interested in making sure explain reflects that well)

**Comment by ah8ad3** [comment]
@alexzielenski
Thanks a lot for the review. Those are really great ideas
I've updated the code, first of all the result of running explain in the resource that you provide earlier in updated code is something like this:
In long list view
```
  type  <string>
  enum: "", BlockDevice, CharDevice, Directory, DirectoryOrCreate, File, FileOrCreate, Socket
    type for HostPath Volume Defaults to "" More info:
    https://kubernetes.io/docs/concepts/storage/volumes#hostpath
```
In simple view
```
FIELD: type <string>
ENUM: "", BlockDevice, CharDevice, Directory, DirectoryOrCreate, File, FileOrCreate, Socket
```

Also i have implemented a truncation feature in the function, with an argument named `limit`, that will limit the result of any of these enum slices as we desire and can be modified easily, for example in simple view the usage of extractEnum is
`{{- template "extractEnum" (dict "schema" $subschema "Document" $.Document "longFormView" false "limit" -1) -}}`
when the limit is undefined or defined as -1 all the items in slice will print out, but when we define any number it will print the enums until that amount and will add `,..` to the end of the line.
for example:
```
FIELD: type <string>
ENUM: "", BlockDevice, CharDevice,..
```
Personally i think in the long list view we should define limit so the list can be more readable and in the simple view we should let all the enums print out, but this behavior can be easily changed with the `limit` argument. For now both limits for long and simple view is -1.
Also for empty string i have changed the code to reflect "".

**Comment by alexzielenski** [comment]
> @alexzielenski Maybe there is a misunderstand of long and simple view for me(i'm not sure), please do not hesitate to correct me if i'm wrong. I think everything under `FIELDS` with a long list is the long form and the `FIELD` at the start of the screen is the simple view.

Ah my mistake for introducing unclear terminology. I meant it reversed. By `simple view` i was referring to when displayed as a long list of fields. The long view i referred to was when you just inspected a single field.

> Personally i think in the long list view we should define limit so the list can be more readable and in the simple view we should let all the enums print out,

Using the definitions of the terms you gave, I think I agree with this.

So to reiterate: I think the forms should be:

```
FIELD: type <string>
ENUM: 
    ""
    BlockDevice
    CharDevice
    Directory
    DirectoryOrCreate
    File
    FileOrCreate
    Socket
```


And when displaying all fields


```
type  <string>
enum: "", BlockDevice, CharDevice, Directory, ....
  type for HostPath Volume Defaults to "" More info: 
  https://kubernetes.io/docs/concepts/storage/volumes#hostpath
```

**Comment by ah8ad3** [comment]
@alexzielenski
Thanks for clarification.
Now the result in `simple view` is:
```
  type  <string>
  enum: "", BlockDevice, CharDevice, Directory, ....
    type for HostPath Volume Defaults to "" More info:
    https://kubernetes.io/docs/concepts/storage/volumes#hostpath
```

and in `long view` is:
```
FIELD: type <string>
ENUM:
    ""
    BlockDevice
    CharDevice
    Directory
    DirectoryOrCreate
    File
    FileOrCreate
    Socket
```

**Review by alexzielenski — COMMENTED** [review]
/lgtm

**Comment by alexzielenski** [comment]
/assign @apelisse 

for approve

**Review by apelisse — COMMENTED** [review]
/approve

**Pull request merged**
