### PR TITLE
Change docker metrics to conform metrics guidelines

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/sig instrumentation

**What this PR does / why we need it**:

1. As part of [kubernetes metrics overhaul](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/0031-kubernetes-metrics-overhaul.md), change docker metrics to conform [Kubernetes metrics instrumentation guidelines](https://github.com/kubernetes/community/blob/master/contributors/devel/instrumentation.md).

2. Change docker metrics to histogram for better aggregation.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

This patch does not remove the existing metrics but mark them as deprecated.
We need 2 releases for users to convert monitoring configuration.

**Does this PR introduce a user-facing change?**:

```release-note
Change docker metrics to conform metrics guidelines and using histogram for better aggregation.
The following metrics are deprecated, and will be removed in a future release:
* `docker_operations`
* `docker_operations_latency_microseconds`
* `docker_operations_errors`
* `docker_operations_timeout`
* `network_plugin_operations_latency_microseconds`
Please convert to the following metrics:
* `docker_operations_total`
* `docker_operations_latency_seconds`
* `docker_operations_errors_total`
* `docker_operations_timeout_total`
* `network_plugin_operations_latency_seconds`
```

### CODE REVIEW

**Comment by liggitt** [comment]
What is the compatibility guarantee on metric names/values? Changing metrics this way with no advance notice is likely to cause problems with monitoring over upgrade boundaries. I'm not sure if this falls under an aspect of our deprecation policy that would require a longer pre-announce period, but if not, I'd advocate at least one release overlap where both old and new metrics are available.

**Comment by liggitt** [comment]
These questions would be good to answer broadly and include in 
https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/0031-kubernetes-metrics-overhaul.md to inform the other metrics updating efforts

**Comment by danielqsj** [comment]
@liggitt 
Thanks, totally agree.
I already added the previous metrics back and marked them as deprecated.

**Comment by brancz** [comment]
@danielqsj could you open a PR against the metrics overhaul that says that the 1.14 release will have backward compatibility but 1.15 will drop the deprecated metrics and label? Thanks!

**Comment by danielqsj** [comment]
@derekwaynecarr  can you help review this? Thanks

**Comment by danielqsj** [comment]
@Random-Liu @sttts @deads2k if you have time, can you help review this? Thanks

**Comment by danielqsj** [comment]
@derekwaynecarr @Random-Liu @sttts @deads2k ping

**Comment by danielqsj** [comment]
@thockin @derekwaynecarr @Random-Liu @sttts @deads2k if you have time, can you help review this? Thanks

**Comment by sttts** [comment]
/assign @derekwaynecarr

for approval.

**Comment by brancz** [comment]
cc @deads2k @smarterclayton for `test/OWNERS` approval

**Pull request merged**
