### PR TITLE
Fix admission options documentation typos

### PR DESCRIPTION
**Pull request by sugare**
**What type of PR is this?**
> /kind documentation

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by neolit123** [comment]
hi @sugare , please sign the CLA to be able to contribute to the project.
instructions in the second post here https://github.com/kubernetes/kubernetes/pull/71593#issuecomment-443164763

/kind cleanup
/release-note-none
/priority backlog

**Comment by sugare** [comment]
I signed it.

**Pull request closed without merging**
