### PR TITLE
actually promote daemonset simple test out of flaky and skip all daemonset tests in gke

### PR DESCRIPTION
**Pull request by mikedanese**
Botched this last time.

### CODE REVIEW

**Comment by mikedanese** [comment]
:(

**Comment by quinton-hoole** [comment]
Assigning to @mikedanese to debug.  Feel free to assign back to me for review once you've fixed the test failures Mike.

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@quinton-hoole PTAL.

Daemon set should run and stop simple daemon is not flaky anymore

**Comment by quinton-hoole** [comment]
LGTM!

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by ArtfulCoder** [comment]
manual merge

**Pull request merged**
