### PR TITLE
Move hollow_proxy.go from pkg/kubemark to pkg/proxy/kubemark

### PR DESCRIPTION
**Pull request by danwinship**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
It seems like about 50% of changes to `pkg/kubemark/hollow_proxy.go` are just dummy changes to keep it in sync with proxy API changes. I'm also in the middle of some kube-proxy refactoring that will result in a bunch more of these (eg #116593). It seems like it would be simpler to explicitly share the maintenance of this file between sig-scalability and sig-network rather than sig-network needing to poke someone in sig-scalability each time there's a trivial change to the file. (This PR copies the existing kubemark OWNERS file into the new dir, but in the new location it will inherit `pkg/proxy/OWNERS` too.)

Another possibility would be to just add some sig-network approvers to `pkg/kubemark/OWNERS`...

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/sig scalability
/sig network

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm
/approve

Thanks!

**Comment by danwinship** [comment]
huh, the "Compare" link on the force push doesn't show it, but I repushed to fix the `.import-restrictions` files. (`pkg/proxy/kubemark/` needed the import restriction override that `pkg/kubemark` already had)

**Pull request merged**
