### PR TITLE
kubectl describe more fields for ingress

### PR DESCRIPTION
**Pull request by feiskyer**
kubectl describe more fields (including endpoints) for ingress

Ref #16927 CC @janetkuo

### CODE REVIEW

**Comment by feiskyer** [comment]
@k8s-bot  test this

**Comment by bprashanth** [comment]
@feiskyer thanks! this looks good. Can you give me some example output?

**Comment by feiskyer** [comment]
@bprashanth A simple demo is 

```sh
# ./kubectl describe ingress
Name:		test-ingress
Namespace:	default
Labels:		<none>
Rules:
Backend:	nginx:8078
Endpoints:	192.168.123.10:80,192.168.123.11:80
Annotations:
No events.
```

**Comment by bprashanth** [comment]
LGTM, sorry for delay

**Comment by feiskyer** [comment]
Thanks @bprashanth, I rebased this to trigger e2e tests.

**Comment by feiskyer** [comment]
@bprashanth Could you help to check why GCE e2e test failing?

**Comment by janetkuo** [comment]
@k8s-bot e2e test this

**Pull request merged**
