### PR TITLE
Remove an e2e test specific to kubeup clusters - Part Two

### PR DESCRIPTION
**Pull request by upodroid**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
addon-manager has been deprecated for a long time and we should stop testing it. This is not available in kops.

Should fix this failing test https://testgrid.k8s.io/sig-cluster-lifecycle-kubeup-to-kops#ci-kubernetes-e2e-cos-gce-slow-canary&include-filter-by-regex=Addon.update

The docs at kubernetes.io no longer mention addon-manager or how to install it.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

https://github.com/kubernetes/enhancements/issues/4224

### CODE REVIEW

**Comment by aojea** [comment]
/assign @BenTheElder 

he has more historical context here

**Comment by justinsb** [comment]
I suppose the challenge is that for the other kube-up tests, they still use the addon manager (kube-up is the only thing AFAIK).  So if we broke the addon manager, we would know because the remaining kube-up tests would break.  If this was the last kube-up test, 100% agreed.  But we aren't really gaining anything from this test, other than maybe a bit more clarity if someone breaks the addon manager in the way this test verifies, so ....

/lgtm

**Pull request merged**
