### PR TITLE
make kubelet prefer ipv4 address if available

### PR DESCRIPTION
**Pull request by deads2k**
Services don't function properly with nodes on IPv6.  I found this (old) issue: https://github.com/GoogleCloudPlatform/kubernetes/issues/1443 looking for "ipv6" in the open issue list.

This does not support ipv6, but it does help the kubelet choose an ipv4 address if it can find one, so it limits effect of the problem.

### CODE REVIEW

**Comment by thockin** [comment]
Should this just use util.ChooseHostInterface() instead?

**Comment by deads2k** [comment]
> Should this just use util.ChooseHostInterface() instead?

I think the semantics are different.  The code I wrote finds an ip address that backs the hostname "X".  The `util.ChooseHostInterface` tries to find the IP for the interface of my default route or from a non-loopback interface.  If I want to receive traffic from my master from an interface that isn't my default route, then `util.ChooseHostInterface` couldn't do it.  Doing the check with `net.LookupIP` would work correctly.

**Comment by thockin** [comment]
Sorry, I meant leave the rest, but when you fall into this "oh damn, none of that worked, just pick one" case, ChooseHostInterface() is more likely to be correct than "the first ipv4 address I can find".

**Comment by deads2k** [comment]
Updated to do:
 1. if the `kubelet.hostname` is an IP, use it directly
 1. if available, use the first non-loopback ipv4 address from the list of IP addresses for our `node.Name` (distinct from `kubelet.hostname`).  This is exactly as pre-existing behavior, except that it limits for ipv4
 1. if no suitable ipv4 address is found for the `node.Name`, use the ip address of the interface gateway.

**Comment by thockin** [comment]
LGTM

would be nice if there was a way to test it, but this is one of those difficult things...

**Comment by mikedanese** [comment]
@deads2k please rebase to fix shippable

**Comment by deads2k** [comment]
rebased

**Comment by deads2k** [comment]
rebased again in the quest for green.

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@dchen1107

**Pull request merged**
