### PR TITLE
Updating namespace controller utils to use versioned clientset

### PR DESCRIPTION
**Pull request by nikhiljindal**
Updating namespace controller utils code to use versioned clientset instead of the unversioned one.
This is the code that deletes all resources from a namespace when the namespace is being deleted.

I want to reuse the same code in federation namespace controller (which uses versioned clientset) and hence need to first update this code to use versioned clientset.

Ref https://github.com/kubernetes/kubernetes/issues/33612 and https://github.com/kubernetes/kubernetes/issues/35159

cc @caesarxuchao @derekwaynecarr @mwielgus

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35738)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Rebased and verified that tests pass

**Comment by nikhiljindal** [comment]
The GCI GCE e2e failure seems unrelated. All other tests passed. Retrying
@k8s-bot gci gce e2e test this

**Comment by caesarxuchao** [comment]
If fed namespace controller only needs the syncNamespace(), could you initiates a internalversion clientset and pass it to the fed namespace controller? I think that's cleaner.

**Comment by nikhiljindal** [comment]
@caesarxuchao Yes I can do that. We have 2 options:
* Instantiate an internal clientset in fed ns controller and use that to call syncNamespace; or
* Instantiate a versioned clientset in kube ns controller and update syncNamespace to work with a versioned clientset

I think the second option is better because our ultimate aim is to update all libraries to use versioned clientsets.

**Comment by nikhiljindal** [comment]
Discussed this with @caesarxuchao and we decided to go with option 1.
When we move to client-go it will be easier to replace internalclientset with client-go everywhere.

Sent https://github.com/kubernetes/kubernetes/pull/35950 which instantiates an internalclientset for federation namespace controller and uses that to call syncNamespace.

Closing this PR.

**Pull request closed without merging**
