### PR TITLE
Using pause image for testing.

### PR DESCRIPTION
**Pull request by dchen1107**
#15384

### CODE REVIEW

**Comment by dchen1107** [comment]
ok to test

**Comment by dchen1107** [comment]
Failure test is caused by known flaky: Kubernetes e2e suite.Deployment deployment should scale up and down in the right order

**Comment by dchen1107** [comment]
ok to test

**Comment by ixdy** [comment]
LGTM

**Comment by dchen1107** [comment]
same flakiness. 

ok to test

**Pull request merged**
