### PR TITLE
Update cAdvisor Godeps to tagged alpha release for v1.4

### PR DESCRIPTION
**Pull request by timstclair**
cc/ @Random-Liu @vishh 
For https://github.com/kubernetes/kubernetes/issues/31015

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31145)

### CODE REVIEW

**Comment by dchen1107** [comment]
Nothing is changed in cAdvisor?

**Comment by timstclair** [comment]
No, https://github.com/kubernetes/kubernetes/pull/30801 actually included the commit that is the head of the `release-v0.24` branch (https://github.com/google/cadvisor/commit/2ed7198f77395ee9a172878a0a7ab92ab59a2cfd)

**Comment by dchen1107** [comment]
LGTM

**Comment by timstclair** [comment]
We'll have a cAdvisor bugfix coming soon (https://github.com/google/cadvisor/pull/1429) that will pick up the `v0.24.0-alpha1` tag. I'm going to close this for now to free up more submit-queue cycles.

**Comment by timstclair** [comment]
@lavalamp The submit queue asked to test this PR 15 hours after it was closed...

**Comment by lavalamp** [comment]
@foxish @apelisse ^^^^^

**Comment by foxish** [comment]
@lavalamp Looking into this, it seems like we don't check if the PR was closed at any point after it has made it into the queue.

**Comment by lavalamp** [comment]
@foxish thanks, could you open an issue (or just fix it if you have time)?

**Pull request closed without merging**
