### PR TITLE
Revert "Pods pending due to insufficient OIR should get scheduled once sufficient OIR becomes available."

### PR DESCRIPTION
**Pull request by dchen1107**
Reverts kubernetes/kubernetes#41870 for stopping bleeding edge: #42597

cc/ @ConnorDoyle @kubernetes/release-team 

Connor if there is a pending pr to fix the issue, please point it out to me. We can close this one, otherwise, I would like to revert the pr first. You can resubmit the fix. Thanks!

### CODE REVIEW

**Comment by dashpole** [comment]
this LGTM, assuming tests pass, because it is a revert.

**Comment by dchen1107** [comment]
cc/ @marun

**Comment by ConnorDoyle** [comment]
The fix to OIR and corresponding e2e were submitted as separate commits; do you mind reverting only e402c5d5e50c11af3ecde4fffa509776f0608d03 ?

**Pull request merged**
