### PR TITLE
Purge the manifest after the push

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:
Triggered by https://github.com/kubernetes/kubernetes/issues/69104#issuecomment-424799217

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/kind bug
/sig release
/cc @ixdy @dims

### CODE REVIEW

**Review by dims — APPROVED** [review]
/lgtm

**Comment by ixdy** [comment]
Thanks! I'm hoping this should prevent something like https://github.com/kubernetes/kubernetes/pull/68898#issuecomment-423356776 from happening again.

/lgtm

**Pull request merged**
