### PR TITLE
Use more meaningful and consistent variable names in glusterfs plugin.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by jsafrane** [comment]
@k8s-bot ok to test

**Comment by humblec** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by humblec** [comment]
@k8s-bot pull-kubernetes-unit

**Comment by humblec** [comment]
@jsafrane I rebased to master. Can you please bring back LGTM and approve here?

**Comment by humblec** [comment]
@k8s-bot  pull-kubernetes-e2e-gce-etcd3

**Pull request merged**
