### PR TITLE
Remove "All rights reserved" from all the headers.

### PR DESCRIPTION
**Pull request by david-mcmahon**
cc @thockin @zmerlynn @brendanburns

### CODE REVIEW

**Comment by thockin** [comment]
```
Verifying ./hack/../hack/verify-godep-licenses.sh
Checking for 'Godeps/' changes against 'origin/master'
Your godep licenses file is out of date. Run hack/update-godep-licenses.sh and commit the results.
--- /go/src/k8s.io/kubernetes/Godeps/LICENSES	2016-06-02 17:45:21.591162941 -0700
+++ /go/src/k8s.io/kubernetes/_tmp/kube-godep-licenses.9y0Oh7/Godeps/LICENSES	2016-06-02 17:57:47.570895445 -0700
@@ -204,7 +204,7 @@
    See the License for the specific language governing permissions and
    limitations under the License.
 
-= LICENSE d6177d11bbe618cf4ac8a63a16d30f83  -
+= LICENSE ad09685d909e7a9f763d2bb62d4bd6fb  -
 ================================================================================
 
 ================================================================================
FAILED   ./hack/../hack/verify-godep-licenses.sh	8s

**Comment by thockin** [comment]
LGTM except test fail

**Comment by david-mcmahon** [comment]
Updated.  Pulling in original LGTM

**Comment by luxas** [comment]
@k8s-bot unit test this please github issue: #IGNORE

**Comment by goltermann** [comment]
@k8s-bot unit test this please github issue: #IGNORE

**Comment by david-mcmahon** [comment]
@k8s-bot unit test this please github issue: #IGNORE

**Comment by david-mcmahon** [comment]
@k8s-bot unit test this please github issue: #IGNORE

**Comment by david-mcmahon** [comment]
@thockin @bgrant0607 @k8s-oncall do we want to force merge this before Friday?  The longer this sits, the more likely we'll need (another) rebase.

**Comment by david-mcmahon** [comment]
@k8s-bot: unit test this please github issue: #IGNORE

**Comment by zmerlynn** [comment]
@david-mcmahon: Yes; I was going to suggest that.

**Comment by thockin** [comment]
OTOH: this is not CRITICAL for 1.3, so could merge after 1.3 is branched.
You could just let it rot until then, do one last rebase and THEN merge it.

**Comment by bgrant0607** [comment]
@david-mcmahon Yes, this will need to be hand-merged. However, I agree with @thockin that we might as well wait until after we cut the 1.3 branch, which should happen any day now.

**Comment by dchen1107** [comment]
Ok, this one can be hold after branch cut.

**Comment by david-mcmahon** [comment]
ping.  Would prefer not to rebase this one again.

**Comment by thockin** [comment]
LGTM. rebase it and give it a shot

**Comment by luxas** [comment]
Just a side question, why are you doing this? :)

**Comment by david-mcmahon** [comment]
@luxas Because lawyers.

**Comment by david-mcmahon** [comment]
Rebased again. @k8s-oncall, please merge this by hand if you can.  The longer it sits, the greater the liklihood for yet another rebase and another testing cycle and another carryforward LGTM.

**Comment by jlowdermilk** [comment]
Will merge on green.

**Comment by zmerlynn** [comment]
@david-mcmahon: Your script is missing files, according to the verification.

**Comment by jlowdermilk** [comment]
Run `hack/verify-all.sh -v` to see what needs fixing.

**Comment by david-mcmahon** [comment]
@jlowdermilk Yes, thanks.  Already running.

**Comment by smarterclayton** [comment]
Is there context/discussion on this change?

**Comment by thockin** [comment]
Lawyers.  It legally means nothing, and more words is less good.

**Pull request merged**
