### PR TITLE
Fix autoscaler deployment bug

### PR DESCRIPTION
**Pull request by nashasha1**
**What this PR does / why we need it**:
This PR add `selector` in yaml: dns-horizontal-autoscaler.yaml, and upgrade the `apiVersion` of `Deployment` to `apps/v1`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

```release-note
None
```

### CODE REVIEW

**Comment by nashasha1** [comment]
@k8s-merge-robot

**Review by MrHohn — APPROVED** [review]
This isn't really a bug. When selector is not defined, label from pod template will be used as the selector. Though the change seems fine.

/lgtm
/approve-no-issue
/ok-to-test

**Pull request merged**
