### PR TITLE
Remove stale loadbalancer for edge cases in aws

### LINKED ISSUE #68605: AWS classic loadbalancer is not cleaned on apply
/kind bug

**What happened**:

Applied this in AWS:

```
kind: Service
apiVersion: v1
metadata:
  namespace: lolcats
spec:
  type: LoadBalancer
...
```

---> got a classic loadbalancer.

Changed to this

```
kind: Service
apiVersion: v1
metadata:
  namespace: lolcats
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
...
```

And after apply got an NLB, but the classic loadbalancer is still there.

**What you expected to happen**:

Not to get billed by AWS for $20/month for nothing

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.1
- Cloud provider or hardware configuration: aws
- OS (e.g. from /etc/os-release): coreos
- Kernel (e.g. `uname -a`): stable
- Install tools: kontena pharos
- Others: beer

### PR DESCRIPTION
**Pull request by Jeffwan**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
When user change from classic load balancer(elb) to network load balancer(nlb) or from nlb to elb, aws actually doesn't delete stale one and every load balancer cost $20 per month. This PR help to fix this issue and people doesn't need to have them cleaned up manually. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #68605 #66306

**Special notes for your reviewer**:
This is my first PR, please let me know if anything I am missing

**Does this PR introduce a user-facing change?**:

```release-note
This feature fix an issue that old load balancer is not deleted when user decide to use different kind of load balancer type by annotating kubernetes service. For example, changing from ELB to NLB or NLB to ELB. In this case, aws will create the new one and then delete the stable one which has been addressed in this PR
```

### CODE REVIEW

**Comment by Jeffwan** [comment]
@jsafrane  @chrislovecnm  Can someone help look at this PR?

**Comment by jsafrane** [comment]
Sorry, I am storage guy, I am not familiar with load balancer code.

cc @kubernetes/sig-aws-misc

**Comment by Jeffwan** [comment]
@micahhausler This will help fix two issues user reports. Please have a look

**Comment by selslack** [comment]
@M00nF1sh @micahhausler can you please take a look at this PR?

**Comment by Jeffwan** [comment]
I will clean my code up. Sorry for the delay!

**Pull request closed without merging**
