### PR TITLE
Fix failure to load volume plugins for #52048

### LINKED ISSUE #52048: Failure to load some of the volume plugins when cloud set to external.
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug report
/kind bug

**What happened**: Trying to implement stage 1 cloud provider controller manager for GCE (or azure etc) and run the e2e tests we see a lot of errors trying to load the relevant plugin. For this we have the cloud provider on kube controller manager set to external. There are two plugin managers, one of which has the relevant plugins but the other does not. So we are loading the plugin, however when we go through the hampered plugin manager we get an error loading the plugin.

**What you expected to happen**: Until we properly separate the cloud provider plugins from kube-controller-manager the plugin should be found.

**How to reproduce it (as minimally and precisely as possible)**: Get state 1 working for one of the affected cloud providers. 

**Anything else we need to know?**: I believe we do want to remove the cloud plugins from kube-controller-manager, however the current attempt is not complete and I think hampering us from doing it the way we want to.

**Environment**: GCE
- Kubernetes version (use `kubectl version`): 1.9
- Cloud provider or hardware configuration**: GCE
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by cheftako**
Currently we have two plugin managers.
However one of them limits the cloud plugins it loads.
This means that if cloud provider is set to external the plugins will
not be loaded in *that* plugin manager. However they will be loaded in
the other instance of the plugin manager. So it does not actually save
us anything. It does hamper the efforts to actually get stage 1
separation working.

**What this PR does / why we need it**: It allows the plugins be found for the cloud providers working on stage 1 separation.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #52048 

**Special notes for your reviewer**:

**Release note**:
```release-note NONE
```

### CODE REVIEW

**Comment by saad-ali** [comment]
This seems fine to me. I don't think having the volume manager report all the volume plugins should be a problem
@verult can you PTAL, verify, and LGTM.

/approve

**Comment by verult** [comment]
cc @jsafrane who authored the check

**Comment by verult** [comment]
Here's the relevant discussion. Sounds like it was a safety check that may not be necessary.
https://github.com/kubernetes/kubernetes/pull/29006#r71818543

**Comment by jsafrane** [comment]
Yes, it's a safety check. LGTM.

Just FYI, users will see different errors now - if someone uses AWS EBS volume on GCE, before this PR the user got something like "unknown plugin kubernetes.io/aws-ebs", now the user gets "Failed to get AWS Cloud Provider. GetCloudProvider returned %v instead". Not a big deal IMO.

**Comment by jsafrane** [comment]
/assign @deads2k @lavalamp 
for approval

**Pull request merged**
