### PR TITLE
Promote Service Test to Conformance

### LINKED ISSUE #78834: Write Scale Tests for Conformance
Using the list of tested stable endpoints referenced in https://github.com/kubernetes/kubernetes/issues/78748, we can pick out the endpoints which are part of the Scale kind:

[replaceCoreV1NamespacedReplicationControllerScale](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-replaceCoreV1NamespacedReplicationControllerScale&showUntested=false&showConformanceTested=false)

[readCoreV1NamespacedReplicationControllerScale](https://apisnoop.cncf.io/?zoomed=operationId-stable-core-readCoreV1NamespacedReplicationControllerScale&showUntested=false&showConformanceTested=false)

These are stable core endpoints which are covered by an existing test, but the test does not directly exercise these endpoints. New tests should be written.

/area test
/area conformance
/sig testing

### PR DESCRIPTION
**Pull request by zachmandeville**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
 /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Promotes the following E2E test to Conformance:
`test/e2e/network/service.go: "should create endpoints for unready pods`

**Which issue(s) this PR fixes**:

Fixes #78834 

**Special notes for your reviewer**:
Part of Umbrella Issue #78748

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
/area conformance
/area test

@kubernetes/sig-architecture-pr-reviews
@kubernetes/cncf-conformance-wg
@kubernetes/sig-network-pr-reviews

### CODE REVIEW

**Comment by devaips** [comment]
Regarding my force-push: 

The file containing the test in question had a substantial refactor since this PR was opened. I reapplied the original commit on-top of the new history.

**Comment by johnbelamaric** [comment]
A couple things:

1. The tolerate-unready-endpoints annotation is deprecated. Instead we should be using the Service.spec.publishNotReadyAddresses
2. This currently sets a preStop hook that sleeps. That extra complexity shouldn't be necessary when using agnhost netexec, which will not exit on its own.
3. The exec pod that evaluates whether the endpoint is accessible uses `wget`. This is something I don't fully get about the Windows stuff. @bclau can we run Linux pods on Windows nodes *at all*? If not then we probably need to use the agnhost for this pod as well.

**Review by johnbelamaric — CHANGES_REQUESTED** [review]
Cannot be promoted until the listed items are addressed.

**Comment by spiffxp** [comment]
/close
Per https://github.com/kubernetes/kubernetes/pull/79122#issuecomment-506766182 this can't be promoted until the test is rewritten

**Comment by BobyMCbobs** [comment]
> 1. The tolerate-unready-endpoints annotation is deprecated. Instead we should be using the Service.spec.publishNotReadyAddresses

It appears that it is [`PublishNotReadyAddresses`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L3908), with capitalization. This isn't used currently on any tests. Replacing tolerate-unready-endpoints annotation makes the test fail.

> 2. This currently sets a preStop hook that sleeps. That extra complexity shouldn't be necessary when using agnhost netexec, which will not exit on its own.

The test seems to fail without it.

> 3. The exec pod that evaluates whether the endpoint is accessible uses `wget`. This is something I don't fully get about the Windows stuff. @bclau can we run Linux pods on Windows nodes _at all_? If not then we probably need to use the agnhost for this pod as well.

This image is agnhost (current set is version [2.2](gcr.io/kubernetes-e2e-test-images/agnhost@sha256:cbbd4720dbb91596effb30dfbc117d0cfa6d634e54f2297fa2cfe409e5895696)), which from my understanding is cross platform, as a result I don't think shouldn't be an issue. [agnhost:2.4](https://console.cloud.google.com/gcr/images/kubernetes-e2e-test-images/GLOBAL/agnhost@sha256:080e89220a20400cefd1876ac2fddc0f379dccda60cd7d8d8d3415e1a959cd1b/details?tab=info) has a few options for testing connectivity:
- `wget -qO- https://$SERVICEIP:$PORT` (current solution)
- `/agnhost connect --timeout 10s $SERVICEIP:$PORT` (connect parameter is not present in 2.2, but 2.4)
- `curl -i https://$SERVICEIP:$PORT`

**Comment by BobyMCbobs** [comment]
[Here's my attempt, with the changes](https://github.com/ii/kubernetes/commit/566c0a431bfb98c1dc4a611ef217b1deb7842cff) @johnbelamaric. It appears to fail currently.

**Pull request closed without merging**
