### PR TITLE
Change log:Fix Spelling error about [subresouce]

### PR DESCRIPTION
**Pull request by heqg**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
Change log:Fix Spelling error about [subresouce]

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

```release-note
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Comment by tpepper** [comment]
/ok-to-test
/lgtm
I was going to say we don't tend to touch these older files, but there was just a typo fix in another PR recently so 🤷 .

/assign @wilsonehusin 
/unassign @tpepper

**Comment by wilsonehusin** [comment]
seems like the most recent PR fix mentioned by Tim was accepted because it was a batch of other active releases. since this is only modifying EOL release, I'm going to close this one.

/close

**Pull request closed without merging**
