### PR TITLE
Cleanup storeToClusterConditionLister

### PR DESCRIPTION
**Pull request by FengyunPan**
ClusterConditionPredicate() has been deleted,
storeToClusterConditionLister will be unused.

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by shashidharatd** [comment]
Looks good to me, but lets wait for federation tests to pass.
its weird that federation pre-merge test is taking more than an hour for recent runs.
@madhusudancs, any clues what caused it?

**Comment by cblecker** [comment]
The federation test doesn't have a very solid record right now: https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-federation-e2e-gce

It doesn't look to be commit related, as at the time when it started failing (and most runs taking over an hour) it was the same base commit from master used.

**Comment by shashidharatd** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
