### PR TITLE
Update gnostic to the latest version

### LINKED ISSUE #65: Update gnostic to the latest version
Context: google/gnostic#195
gnostic upgrade from yaml.v2 to yaml.v3 breaks some clients

Can we use apiserver with the latest github.com/googleapis/gnostic (0.5.0 or later)? 
There is an incompatibility between yaml v2 used by apiserver and yaml v3 used by gnostic since version 0.5.0

Without this fix, it is impossible to import this library and controller-runtime v0.8.3
error log:
```
# k8s.io/apiserver/pkg/util/openapi
../../../pkg/mod/k8s.io/apiserver@v0.20.2/pkg/util/openapi/proto.go:43:36: cannot use info (type "gopkg.in/yaml.v2".MapSlice) as type *"gopkg.in/yaml.v3".Node in argument to openapi_v2.NewDocument
```

To fix this, as suggested in google/gnostic#195, we could replace [this line](https://github.com/kubernetes/apiserver/blob/v0.20.2/pkg/util/openapi/proto.go#L43) with the **ParseDocument** functions defined in [openapiv2/document.go](https://github.com/google/gnostic/blob/40cf3c0b6b95be12aa7d84b7957287d0762593e1/openapiv2/document.go#L20) and [openapiv3/document.go](https://github.com/google/gnostic/blob/40cf3c0b6b95be12aa7d84b7957287d0762593e1/openapiv3/document.go#L20). That would make the calling code look like this:
```
document, err := openapi_v2.ParseDocument(b)
```
where b is a []byte of the JSON or YAML file to be parsed.

### PR DESCRIPTION
**Pull request by mcbenjemaa**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Update gnostic to the latest version to adapt changes of latest release,
https://github.com/google/gnostic/releases/tag/v0.5.5

transitive dependencies:

```
github.com/golang/protobuf v1.5.2
github.com/google/go-cmp v0.5.5
google.golang.org/protobuf v1.26.0
```

****
#### Which issue(s) this PR fixes:

Fixes kubernetes/apiserver#65

#### Does this PR introduce a user-facing change?

```release-note
Update dep google/gnostic and google/go-cmp to v0.5.5 and updating transitive dependencies protobuf
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mcbenjemaa** [comment]
/remove-sig node api-machinery cli storage cloud-provider instrumentation cluster-lifecycle

**Comment by mcbenjemaa** [comment]
/remove-sig node api-machinery cli storage cloud-provider instrumentation cluster-lifecycle

**Comment by mcbenjemaa** [comment]
/remove-sig node api-machinery cli storage cloud-provider instrumentation cluster-lifecycle

**Comment by mcbenjemaa** [comment]
/remove-area kubectl apiserver cloudprovider
/remove-sig node api-machinery cli storage cloud-provider instrumentation cluster-lifecycle

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/100488 is in

**Comment by liggitt** [comment]
/hold cancel

this can be rebased now

**Comment by mcbenjemaa** [comment]
/remove-area kubectl apiserver cloudprovider
/remove-sig node api-machinery cli storage cloud-provider instrumentation cluster-lifecycle

**Comment by mcbenjemaa** [comment]
/remove-area kubectl apiserver cloudprovider
/remove-sig node api-machinery cli storage cloud-provider instrumentation cluster-lifecycle

**Comment by mcbenjemaa** [comment]
Ready

**Pull request merged**
