### PR TITLE
Fix the order of deletion

### PR DESCRIPTION
**Pull request by FengyunPan**
1. EnsureLoadBalancer can't delete pool without deleting members,
   just let EnsureLoadBalancerDeleted do it.
2. Add some friendly error message

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by FengyunPan** [comment]
@dims It should use /approve no-issue

**Comment by dims** [comment]
oops thanks @FengyunPan

**Comment by FengyunPan** [comment]
@dims You are welcome.

**Pull request merged**
