### PR TITLE
Bump minimum supported go version to 1.9.1

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
If #55293 gets merged, we should bump minimum_go_version to 1.9.1

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
ref: #51375 https://github.com/kubernetes/kubernetes/pull/55293#issuecomment-342723106

**Special notes for your reviewer**:
/cc @cblecker @ixdy @luxas 

**Release note**:

```release-note
The minimum supported go version bumps to 1.9.1.
```

### CODE REVIEW

**Review by luxas — APPROVED** [review]
/lgtm
/approve

**Comment by luxas** [comment]
/retest

Thanks @xiangpengzhao!

**Comment by xiangpengzhao** [comment]
I think there is sth wrong with CI.
Ref: https://github.com/kubernetes/test-infra/issues/5400

**Comment by xiangpengzhao** [comment]
@luxas do we need an announcement for developers on the changing of minimum go version supporting? If so, can you help make the announcement please? I guess it's sth like the last announcement: https://groups.google.com/forum/#!msg/kubernetes-dev/0XRRz6UhhTM/YODWVnuDBQAJ

**Comment by luxas** [comment]
@xiangpengzhao I did so already :) https://groups.google.com/forum/#!topic/kubernetes-dev/INeuA9Flcb8

**Comment by xiangpengzhao** [comment]
Oh, thanks @luxas ! I didn't check the mailing list when I copyed the previous announcement link :)

**Pull request merged**
