### PR TITLE
kubelet/cm/cpuset: Improving test coverage

### PR DESCRIPTION
**Pull request by tmilox**
Signed-off-by: TommyStarK <thomasmilox@gmail.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

If applied this commit will increase the unit tests code coverage of `pkg/kubelet/cm/cpuset`.

- Initial unit tests code coverage

Screenshot 2022-12-21 at 13 49 48

- After changes

Screenshot 2022-12-21 at 13 49 10

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by TommyStarK** [comment]
Hello @Random-Liu, @SergeyKanzhelev 

I know guys you are super busy and this PR is far from being a priority. As a very new aspiring contributor I am still trying to become familiar with the code and to start helping on small pieces. Hope you don't mind.

Any feedback will be greatly appreciated 😅.

Best regards,

**Comment by TommyStarK** [comment]
Hello @fromanirh 

Thank you for taking the time, if there is anything I can do please tell me. 

Happy holidays. 

Cheers,

**Comment by fromanirh** [comment]
hi @TommyStarK and thanks for your PR. Because of the ongoing work to move cpuset to utils (https://github.com/kubernetes/kubernetes/pull/113744) unfortunately I'm not sure we should move forward with this PR which, taken in isolation, seems like a nice improvement. We will update ASAP.

**Comment by TommyStarK** [comment]
Oh my bad @fromanirh, I should have checked the open PRs first to be sure I was not touching a part under an ongoing work. I can go ahead and close it if ou want. I will port my changes once #113744 will be merged.
Sorry for that.

Remaining at your disposal. 

Best regards,

**Comment by fromanirh** [comment]
> Oh my bad @fromanirh, I should have checked the open PRs first to be sure I was not touching a part under an ongoing work. I can go ahead and close it if ou want. I will port my changes once #113744 will be merged. Sorry for that.

Nothing to be worried about, this is a thriving community with a lot of activities ongoing, it's too easy to miss something. 
Let's see what other reviewers think before we give up here.
Thanks again for your contribution, looking forward to see more of them!

**Comment by TommyStarK** [comment]
Hello @fromanirh,

I see that #113744  is active so I am going to go ahead and close this one. I have 10 other open PRs so I will focus on them meanwhile. I will surely propose my changes once #113744 is merged. Thank you for your time :) 

Best regards,

**Pull request closed without merging**
