### PR TITLE
Allow create to handle multiple resources, remove createall

### PR DESCRIPTION
**Pull request by smarterclayton**
Create now can leverage resource.Builder to take as input multiple objects, and will report any failures that occur.  The '-f' command is extended to support multiple inputs:

```
kubectl create -f - -f <file> -f <dir>
```

And will enumerate in the order provided. Directories are non-recursive and will process any JSON or YAML files found.

In addition, "List" is supported as a type, so given:

```
kubectl get replicationcontrollers,services -o json --namespace=source --selector=myapp=foo | kubectl create -f - --namespace=dest
```

you can export a subset of your app to another namespace.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Only the last commit two commits are new, the others are represented in #3004

**Comment by bgrant0607** [comment]
Nice.

Waiting on #3004 to merge.

Have you started doing this to update, also?

**Comment by smarterclayton** [comment]
Not yet, that was the last.  Update had some weirdness with defaulting values I wanted to read over your proposals on various management style things.

**Comment by smarterclayton** [comment]
Update I also need to look at PUT behavior on the client (offering an alternative to our current behavior, which is total overwrite)

**Comment by bgrant0607** [comment]
Fair enough. Yes, I made a number of comments about different flavors of updates on #3233, which should be in line with my previous comments on that topic.

**Comment by bgrant0607** [comment]
I merged #3004. Please rebase, and I'll merge this one.

**Comment by smarterclayton** [comment]
Doesn't seem to need rebase

**Comment by smarterclayton** [comment]
Since the #3004 was a straight merge of two tips without a rebase

**Pull request merged**
