### PR TITLE
proxy: cleanup old build file

### PR DESCRIPTION
**Pull request by mikedanese**
this is cruft from when we moved the apigroup.

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
Ref: #53645 `move KubeProxyConfiguration out of componentconfig API group`
@mikedanese This LGTM. I have a couple of questions. Seems like `hack/update-bazel.sh` can't address this case automatically? If a pkg doesn't have direct .go file, it doesn't need to have a BUILD file, right?

**Comment by mikedanese** [comment]
@xiangpengzhao it's by design that update-bazel.sh doesn't clean these up. we aren't able to automatically infer whether manual changes were made in build files from gazelle so we leave them to be manually deleted. We can test to make sure that the manual step is taken though.

**Comment by mikedanese** [comment]
@xiangpengzhao it's by design that update-bazel.sh doesn't clean these up. we aren't able to automatically infer whether manual changes were made in build files from gazelle so we leave them to be manually deleted. We can test to make sure that the manual step is taken though.

**Comment by mikedanese** [comment]
@xiangpengzhao it's by design that update-bazel.sh doesn't clean these up. we aren't able to automatically infer whether manual changes were made in build files from gazelle so we leave them to be manually deleted. We can test to make sure that the manual step is taken though.

**Comment by xiangpengzhao** [comment]
@mikedanese thanks for explanation!

**Comment by apelisse** [comment]
But how did it pass the bazel-test?

**Comment by mikedanese** [comment]
@apelisse no idea but this seems bad

**Comment by apelisse** [comment]
We're only testing/building "affected targets". For one reason or another, this completely new and broken target wasn't detected as "affected"? @ixdy

**Comment by mikedanese** [comment]
bazel workflow is broken and build only change, so i'm approving.

**Pull request merged**
