### PR TITLE
Update cAdvisor godep.

### PR DESCRIPTION
**Pull request by vmarmol**
- Registers factories in Start(). Allows waiting for Docker.

/cc @dchen1107 @rjnagal

### CODE REVIEW

**Comment by rjnagal** [comment]
LGTM

**Comment by rjnagal** [comment]
Can you update e2e status when done? thanks

**Comment by dchen1107** [comment]
LGTM.

**Comment by dchen1107** [comment]
I patched the PR of registering factories in Start(). Allows waiting for Docker in my branch to test my pr. Two failures in e2e due to other known issues. Mergez. 

Summarizing 2 Failures:

[Fail] Density [AfterEach] [Performance suite] should allow starting 30 pods per node 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/density.go:84

[Fail] kubectl update-demo [It] should do a rolling update of a replication controller 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:335

Ran 40 of 46 Specs in 1370.308 seconds
FAIL! -- 38 Passed | 2 Failed | 1 Pending | 5 Skipped F0515 13:04:31.131115   19252 driver.go:94] At least one test failed
2015/05/15 13:04:31 Error running Ginkgo tests: exit status 255

**Comment by mbforbes** [comment]
Thanks!

xref/ #8291

**Pull request merged**
