### PR TITLE
[WIP] test pull-kubernetes-integration timeouts

### PR DESCRIPTION
**Pull request by aojea**
there is something odd with the TCP connections errors

From the logs in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/103635/pull-kubernetes-integration/1414506047057432576 , the ones with `failed to read frame` , we can see that the test iterates over all the ephemeral ports (these are the port assigned by the OS as source, they are taking from a pool defined in the kernel incrementally)

```sh
$ cat  /proc/sys/net/ipv4/ip_local_port_range                                                                                                                                                                                                                           32768	60999
$ grep "failed to read frame" etcd.6f2a034c-e2ed-11eb-88c2-06073436da28.root.log.DEBUG.20210712-0* | cut -d\> -f 2 | cut -d\:  -f2 | sort -u | head -n2
33432
33476
$ grep "failed to read frame" etcd.6f2a034c-e2ed-11eb-88c2-06073436da28.root.log.DEBUG.20210712-0* | cut -d\> -f 2 | cut -d\:  -f2 | sort -u | tail -n2
60878
60960
$ grep "failed to read frame" etcd.6f2a034c-e2ed-11eb-88c2-06073436da28.root.log.DEBUG.20210712-0* | cut -d\> -f 2 | cut -d\:  -f2 | wc
    653     653    3918
```

ref https://github.com/kubernetes/kubernetes/issues/103512

### CODE REVIEW

**Comment by aojea** [comment]
wow, this is creating 11k TCP connections at peak
```
Total: 11266
TCP:   11316 (estab 11218, closed 88, orphaned 0, timewait 0)

Transport Total     IP        IPv6
RAW	  0         0         0        
UDP	  0         0         0        
TCP	  11228     11228     0        
INET	  11228     11228     0        
FRAG	  0         0         0     
```
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/103641/pull-kubernetes-integration/1414570846252437504/artifacts/connections-stats.log

the c10k problem is quite old but the numbers are very close http://www.kegel.com/c10k.html

**Comment by aojea** [comment]
lower connections

```
Total: 8917
TCP:   11628 (estab 8880, closed 2736, orphaned 0, timewait 2653)

Transport Total     IP        IPv6
RAW	  0         0         0        
UDP	  0         0         0        
TCP	  8892      8892      0        
INET	  8892      8892      0        
FRAG	  0         0         0        
```

**Comment by aojea** [comment]
it doesnt seem a tcp related problem

**Comment by aojea** [comment]
this seems interesting, less failues with the whole suite , aprox number of max connections
```
Total: 11021
TCP:   11515 (estab 10978, closed 521, orphaned 0, timewait 438)

Transport Total     IP        IPv6
RAW	  0         0         0        
UDP	  0         0         0        
TCP	  10994     10994     0        
INET	  10994     10994     0        
FRAG	  0         0         0     
```

only difference is that etcd is no syncing, are we facing the c10k problem?

**Comment by aojea** [comment]
test passes down after creating a new etcd instance for each test
the number of connections are the same as without the whole suite
```
Total: 5925
TCP:   12111 (estab 5894, closed 6208, orphaned 0, timewait 6125)

Transport Total     IP        IPv6
RAW	  0         0         0        
UDP	  0         0         0        
TCP	  5903      5903      0        
INET	  5903      5903      0        
FRAG	  0         0         0        
```

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/103641/pull-kubernetes-integration/1415081937596321792/artifacts/connections-stats.log

I think that this is a performance problem, we are resuing etcd between test and it simply can't keep up



/test pull-kubernetes-integration

**Comment by aojea** [comment]
job hanged


/test pull-kubernetes-integration

I start to think that can be a problem because these 2 are running in parallel

```
make test-cmd
make test-integration
```

**Comment by aojea** [comment]
Some test failed due to timeouts 
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/103641/pull-kubernetes-integration/1415415596169826304

it seems that around 21:28 etcd hangs 
> {"level":"warn","ts":"2021-07-14T21:28:29.980Z","logger":"raft","caller":"etcdserver/zap_raft.go:85","msg":"8e9e05c52164694d A tick missed to fire. Node blocks too long!"}
12:34

some minutes later connections and test timeout

**Comment by aojea** [comment]
This failure is really weird, it hangs since the beginning

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/103641/pull-kubernetes-integration/1415446115305656320

**Comment by enj** [comment]
@aojea please `/assign` someone from SIG Auth + move this into `In Review` on the SIG Auth board when this is ready.  Thanks! 😄

**Comment by aojea** [comment]
> @aojea please `/assign` someone from SIG Auth + move this into `In Review` on the SIG Auth board when this is ready. Thanks! smile

thanks @enj, this was mostly for debugging, let me close it now.
I will open a new one and do as you say once I can come back to it

**Pull request closed without merging**
