### PR TITLE
Fix validation message: apiServerEndpoints -> apiServerEndpoint

### LINKED ISSUE #1525: kubeadm join node display error information not quite incorrect
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT or FEATURE REQUEST

FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):

```sh
[root@k8s-1 ~]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:08:49Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):
```sh
[root@k8s-1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
```sh
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- **Kernel** (e.g. `uname -a`):
```sh
Linux k8s-1 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- **Others**:

## What happened?

I create a cluster using `kubeadm`, i run `kubeadm join --config=kubeadm-client.yaml `  join worker to cluster, i forget to set `discovery.bootstrapToken.apiServerEndpoint` and then the kubeadm return log:
```sh
[discovery.bootstrapToken: Required value: APIServerEndpoint is not set, discovery.bootstrapToken.apiServerEndpoints: Invalid value: "": missing port in address]
```

## What you expected to happen?

I think `discovery.bootstrapToken.apiServerEndpoints` -> `discovery.bootstrapToken.apiServerEndpoint` in log. Is it right? Because if it show `discovery.bootstrapToken.apiServerEndpoints` is inconsistent with the configuration.

Correct config file like:
```yaml
apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: "pm0xtx.yvk9eft8fuopdbxj"
    caCertHashes:
    - "sha256:c918c82136d97dd2c84ad58d68831b8e6f04599c86e48b79b6bf6fad63c06160"
    apiServerEndpoint: "kubernetes.cluster.cloud.lb:6443"
```

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**

/kind cleanup
/kind bug

**What this PR does / why we need it**:
Fix validation message: apiServerEndpoints -> apiServerEndpoint

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#1525

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
this is a bug! thanks @SataQiu 
/priority important-soon

/lgtm
/approve
/hold

@kubernetes/sig-cluster-lifecycle-pr-reviews 
@fabriziopandini @rosti 
i propose cherry pick for 1.14.

**Comment by rosti** [comment]
Thanks for spotting this @SataQiu !
@neolit123 this is just the error message. I don't mind it being cherry-picked though.
@fabriziopandini WDYT?

**Review by yagonobre — COMMENTED** [review]
Thanks @SataQiu 
/lgtm

**Comment by SataQiu** [comment]
Thank you all. @neolit123 @rosti @yagonobre 
Do I need cherry pick this for 1.14? And can this PR hold cancel now?

**Comment by rosti** [comment]
@SataQiu feel free to cherry-pick it, you can see how this is done [here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md)

/hold cancel

**Comment by rosti** [comment]
Actually this needs to go in 1.13 as well (so a couple of cherry-picks are necessary - for 1.13 and 1.14).

**Comment by SataQiu** [comment]
Thanks @rosti 
I will try that.

**Comment by neolit123** [comment]
@SataQiu 
please we forgot to add a release note instead of `NONE`
please use:
`kubeadm: fix a small bug in the validation of BootstrapTokenDiscovery"

**Pull request merged**
