### PR TITLE
Fix unit tests for autoregister_controller.go reliable

### PR DESCRIPTION
**Pull request by shiywang**
Fixes https://github.com/kubernetes/kubernetes/issues/45538
Still wip, and just have some questions which I left some comments in original issue above

### CODE REVIEW

**Comment by deads2k** [comment]
> o I using a cache.NewIndexer to replace previous fakeWatch and informers.NewSharedInformerFactory, and using indexers.Add() to manipulate Workqueue ?

Yeah, that's what we want.



> I wrote a basic framwork of new unit test file, is this right ?

Choosing steps versus complete setup ahead of time is up to you, but using steps they'll need access to the workqeuue.  I think I'd suggest having more test cases without steps.  The idea is that you would set up all the private variables (indexers, list of APIServices to maintain, etc), then make a single call to the sync function and check the response.  It takes a little more set up, but the individual tests are easy to reason about.

**Comment by shiywang** [comment]
@deads2k  could you have an early review ? sure if I covered all scenarios

**Comment by deads2k** [comment]
> @deads2k could you have an early review ? not sure if I covered all scenarios

Nice job.  lgtm

**Comment by shiywang** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by shiywang** [comment]
@k8s-bot kubemark e2e test this

**Pull request merged**
