### PR TITLE
Fix comment referring to wrong DNS RFC

### PR DESCRIPTION
**Pull request by a-robinson**
@janetkuo from #29523

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35311)

### CODE REVIEW

**Comment by erictune** [comment]
LGTM

**Comment by a-robinson** [comment]
ping on fixing the release-note label? - @erictune @janetkuo

**Comment by rmmh** [comment]
@a-robinson RFC 952 is the one that specifies the 24-character limit. https://tools.ietf.org/html/rfc952

**Comment by a-robinson** [comment]
@rmmh right, but this validation function is for a 63 character limit - https://github.com/kubernetes/kubernetes/blob/master/pkg/util/validation/validation.go#L131

**Comment by lavalamp** [comment]
/lgtm
/approve

@k8s-bot ok to test

**Comment by a-robinson** [comment]
Closing/reopening to see if that fixes the stuck CLA check.

**Pull request closed without merging**
