### PR TITLE
Automated cherry pick of #12283

### PR DESCRIPTION
**Pull request by ncdc**
Cherry pick of #12283 on release-1.1.

### CODE REVIEW

**Comment by ncdc** [comment]
@smarterclayton @lavalamp

**Comment by ncdc** [comment]
@lavalamp please reach out on irc/slack when you have time - I want to discuss which PRs need to be cherry-picked to 1.1 re exec/attach/portforward and backwards compat.

**Comment by lavalamp** [comment]
@ncdc You can cherry pick all at the same time, that will be faster, I think.

**Comment by ncdc** [comment]
Superseded by #16406

**Pull request closed without merging**
