### PR TITLE
Prefer nil declaration for empty slice

### PR DESCRIPTION
**Pull request by snebel29**
Signed-off-by: Sven Nebel <nebel.sven@gmail.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Apply [code review project guidelines](https://github.com/kubernetes/community/blob/67c6f7fe148a6eb5e164564ece60fea4d1a27a9e/contributors/guide/expectations.md#code-review) on declaring empty slices, [see](https://github.com/golang/go/wiki/CodeReviewComments#declaring-empty-slices).

#### Special notes for your reviewer:
I just wanted to get in touch with the code base and the code review and merging process by creating my first PR, so took a look and found something easy to contribute.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by snebel29** [comment]
sig/ node

**Comment by manugupt1** [comment]
This change looks good to me. thanks for making the change.
I tried a similar small example here: https://play.golang.org/p/GIUgN-xNxsh

**Comment by ehashman** [comment]
/close

Thank you for your PR. It seems to only contain trivial edits. Please read our [trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits). We encourage you to take a look at confirmed issues and bugs or issues marked `help-wanted`.

**Comment by ehashman** [comment]
@snebel29 thank you for jumping in to contribute here, we have very limited reviewer bandwidth so it'd be much appreciated if you were able to make a small patch that fixed a bug, or did a similar cleanup to this on a bit of a larger scale.

**Comment by snebel29** [comment]
That is no problem at all, I must have missed that specific section of the
contribution guidelines.

I will try to find something larger in scope, to get more familiar with the
code base and its triage, to then try to improve some test cases and
eventually other fixes and features, hopefully without consuming much of
the scarce and precious engineering time of this project, before being able
to paid it back.

Thanks!

**Pull request closed without merging**
