### PR TITLE
Bump ContainerVM to container-vm-v20151103

### PR DESCRIPTION
**Pull request by zmerlynn**
Kill Docker override in the process.

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @roberthbailey

**Comment by roberthbailey** [comment]
LGTM.

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
Should we cherry-pick this pr to 1.1 release later?

**Comment by zmerlynn** [comment]
@dchen1107: I think so, yes. I was going to make sure everything was looking green then propose the cherry pick. If we end up cutting a new 1.1, we can just roll it in, since it's effectively a no-op (it kind of shuffles some stuff from pulling-from-repo to baked-in).

**Comment by zmerlynn** [comment]
@k8s-bot unit test this

**Comment by zmerlynn** [comment]
@k8s-bot unit test this

**Comment by zmerlynn** [comment]
@k8s-bot unit test this

**Pull request merged**
