### PR TITLE
skip oom killer tests

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
OOMKiller test has been flaky for a few months now.  People have found out that this is related to issues in containerd/cri-o for detecting OOM.

We will skip this test.
#### Which issue(s) this PR fixes:

Fixes #
Solves #119600  by skipping the test.
#### Special notes for your reviewer:
https://github.com/kubernetes/kubernetes/pull/120460 is closely related.  Took the idea to skip from that PR.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tzneal** [comment]
I created https://github.com/kubernetes/kubernetes/pull/120460 a while back to just skip the failing part and keep the rest of the test.

**Comment by kannon92** [comment]
> I created #120460 a while back to just skip the failing part and keep the rest of the test.

Ah I see.  Maybe we can get some consensus on sig-node about which path to go forward on.  I would prefer to keep tests running as complete failures are good to avoid.  

Either way, one of them will go to help this flake.

**Comment by tzneal** [comment]
> > I created #120460 a while back to just skip the failing part and keep the rest of the test.
> 
> Ah I see. Maybe we can get some consensus on sig-node about which path to go forward on. I would prefer to keep tests running as complete failures are good to avoid.
> 
> Either way, one of them will go to help this flake.

I'm good either as way as well, just want to get rid of the flakes for now :)

**Comment by kannon92** [comment]
/retest

fixing this sig-apps PR in anther thread.

**Review by pacoxu — APPROVED** [review]
/lgtm

**Comment by pacoxu** [comment]
/priority important-soon
as it flakes a lot or important-longterm
/triage accepted

**Comment by kannon92** [comment]
We will go ahead with @tzneal PR rather than this one.
/close

**Pull request closed without merging**
