### PR TITLE
kmsv2: reload metrics bug fix backport

### LINKED ISSUE #120543: Backport encryption at rest automatic reload metrics bug fix
You want all 3 metrics packages here to be safe:

```suggestion
	metrics.RegisterMetrics()
	storagevalue.RegisterMetrics()
	encryptionconfigmetrics.RegisterMetrics()
```

Also we probably need to backport this specific change (confirm that these metrics don't work on older releases before doing the backport).

_Originally posted by @enj in https://github.com/kubernetes/kubernetes/pull/120438#discussion_r1320466941_
            
/assign ritazh

### PR DESCRIPTION
**Pull request by ritazh**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #120543

#### Does this PR introduce a user-facing change?

```release-note
Fixed bug to surface events for the following metrics: apiserver_encryption_config_controller_automatic_reload_failures_total, apiserver_encryption_config_controller_automatic_reload_last_timestamp_seconds, apiserver_encryption_config_controller_automatic_reload_success_total
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by enj** [comment]
@ritazh I assume that you confirmed that without the `init` function the integration test fails?  If so, I would update the release note on both this and and the other PR to describe the bug fix.

/lgtm
/approve
/cc kubernetes/release-managers

**Comment by ritazh** [comment]
> @ritazh I assume that you confirmed that without the `init` function the integration test fails? If so, I would update the release note on both this and and the other PR to describe the bug fix.

Yes, and updated the release note for both PRs

**Comment by enj** [comment]
No further backports are required as these metrics were added in v1.28 in #119008

cc @nilekhc

**Comment by sftim** [comment]
Suggestion for the changelog entry:
```diff
-Fix bug to surface events for the following metrics: apiserver_encryption_config_controller_automatic_reload_failures_total, apiserver_encryption_config_controller_automatic_reload_last_timestamp_seconds, apiserver_encryption_config_controller_automatic_reload_success_total
+Fixed bug to surface events for the following metrics: `apiserver_encryption_config_controller_automatic_reload_failures_total`, `apiserver_encryption_config_controller_automatic_reload_last_timestamp_seconds`, `apiserver_encryption_config_controller_automatic_reload_success_total`
```

**Comment by ritazh** [comment]
> Suggestion for the changelog entry:
> 
> ```diff
> -Fix bug to surface events for the following metrics: apiserver_encryption_config_controller_automatic_reload_failures_total, apiserver_encryption_config_controller_automatic_reload_last_timestamp_seconds, apiserver_encryption_config_controller_automatic_reload_success_total
> +Fixed bug to surface events for the following metrics: `apiserver_encryption_config_controller_automatic_reload_failures_total`, `apiserver_encryption_config_controller_automatic_reload_last_timestamp_seconds`, `apiserver_encryption_config_controller_automatic_reload_success_total`
> ```

Thanks Tim! Updated release note section above.

**Pull request merged**
