### PR TITLE
WIP: Workflow beginning APIs (to be modified) and partial implementation for controller.

### PR DESCRIPTION
**Pull request by sdminonne**
@erictune @soltysh @davidopp 
I know that I had to rebase on top of #23493 and #21675 .

Not sure about relase-note labels for a WIP .
Feedback are welcome.
## Contributor guidelines
1. Please read our [contributor guidelines](https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md).
2. See our [developer guide](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md).
3. Follow the instructions for [labeling and writing a release note for this PR](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/pull-requests.md#release-notes) in the block below. (_this would also contain updated detail later about this new template_)

``` release-note
* Use the release-note-* labels to set the release note state 
* Clear this block to use the PR title as the release note 
-OR-
* Enter your extended release note here
```

### CODE REVIEW

**Comment by erictune** [comment]
Until very recently, I was expecting that Workflow would join the "Batch" API group with the "Job" resource.  But, in the last day, @brendandburns, @bgrant0607 and others have persuaded me that Workflow would be better implemented as third-party code, using the third-party object type.  

Since the Workflow proposal was merged, the rate of change on the project has increased dramatically, and reviewers are very busy but still have to move cautiously.  Using the third-party development approach lets you iterate quickly without blocking on code reviews from busy reviewers.

As the rate of change has increased, so have the number of concepts in Kubernetes.   Developing Workflow apart from the core Kubernetes repository will reduce the number of concepts that users have to learn when they start with Kubernetes.  I know that Workflow is currently pretty simple.  But, looking at how other Workflow engines have grown over time (for example, [Oozie went through three major API versions](https://oozie.apache.org/docs/4.2.0/index.html) of increasing complexity), I think Workflow may grow well beyond the current proposal -- which would be great for Workflow users, but confusing for people trying to get oriented with Kubernetes.  Seeing this now, I think it should start as its own project, perhaps in kuberenetes/contrib, or in another github repo.

Finally, I and others really want to show how extensible Kubernetes is, and Workflow is a great candidate for showing that extensibility.

**Comment by davidopp** [comment]
>  Developing Workflow apart from the core Kubernetes repository will reduce the number of concepts that users have to learn when they start with Kubernetes. [...] I think Workflow may grow well beyond the current proposal -- which would be great for Workflow users, but confusing for people trying to get oriented with Kubernetes."

I think there may be good reasons to do workflow in the manner you suggest, but I don't think the argument above is one of them. In particular, I don't think that a new user would have to know that workflow exists, even if it were in the kubernetes/kubernetes repo and part of the batch API group. They might stumble across it if they look at the code, or list all the API endpoints, but otherwise I don't think they would have to know about it to get started with Kubernetes. Similar to how someone can run a Kubernetes cluster without ever knowing about Ingress, horizontal pod autoscalers, etc.

**Comment by sdminonne** [comment]
@erictune: We're ok to implement Workflow using ThirdPartyResource as @brendandburns and @bgrant0607 suggested. As soon we'll have something that is reasonably working we will submit the project to kubernetes/contrib. I will add more comment on #25067

**Comment by soltysh** [comment]
@sdminonne should this PR be closed in that case?

**Comment by sdminonne** [comment]
I didn't close it since there will be some discussion about this in the hangout but we can speak about a closed PR as well :)

**Comment by timothysc** [comment]
@sdminonne @soltysh I'm happy to help on workflows external to the core.  I know I baited the conversation originally, and I agree architectural approach to keep it outside the core.  Generally we've had the conversations internally that we want to combine several ideas together.  

Including combining concepts from oozie, pegasus, make-flow, and chronos.  

Do you have a shared requirements spec that you'd be willing to share?

**Comment by soltysh** [comment]
@timothysc I'll let @sdminonne speak up about it, since he's in charge of the workflow work. I'm just humble reviewer/commenter :wink:

**Comment by sdminonne** [comment]
@timothysc few things:

1. Don't worry for previous dicussions your comments made perfectly sense.
2. As I already mentioned I plan to implement a very simple workflow (what we had in the proposal)
3. We'll need more features but we need to clarify internally several things (notably project exposition and owenership). As soon I've more info I'm going to clarify and eventually share.
4. I would move the discussion to https://github.com/kubernetes/kubernetes/issues/25067 since this is closed and maybe others (even humble reviewer/commenter) could comment :)

**Pull request closed without merging**
