### PR TITLE
Remove AttachVolumeLimit feature gate

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What type of PR is this?**
/kind cleanup

**Does this PR introduce a user-facing change?**:

```release-note
The `AttachVolumeLimit` feature gate that is GA since v1.17 is now removed.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
https://github.com/kubernetes/enhancements/issues/554
```

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
/cc @gnufied

@gnufied , can you approve so that we proceed with the cleanup of the feature?

**Comment by gnufied** [comment]
Yeah looks fine to me.

/lgtm

**Comment by ialidzhikov** [comment]
Can we proceed with getting this PR in?

**Comment by gnufied** [comment]
assigning to saad for approving feature gate changes.


/assign @saad-ali

**Pull request merged**
