### PR TITLE
Source for Namespace API reference fixed

### LINKED ISSUE #102180: Source for Namespace API reference omits details of .status.phase
#### What happened:
Spotted during triage for https://github.com/kubernetes/website/issues/28062 - @Ivo-Peterka visited https://k8s.io/docs/concepts/overview/working-with-objects/namespaces/
The source of https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/namespace-v1/ suggests that readers look elsewhere for a list of Namespace phases:
https://github.com/kubernetes/kubernetes/blob/29e4fdab4d644af51c1fa2623bf0e78f3dd6383b/staging/src/k8s.io/api/core/v1/types.go#L5039-L5051

~but following that link doesn't take you to a page listing valid namespace phases.~

#### What you expected to happen:
- https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/namespace-v1/ lists valid namespace phases.
- https://k8s.io/docs/concepts/overview/working-with-objects/namespaces/ also lists valid namespace phases.

#### How to reproduce it (as minimally and precisely as possible):
Visit https://k8s.io/docs/concepts/overview/working-with-objects/namespaces/ or https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/namespace-v1/ and try to work out what the valid values for `.status.phase` are.

#### Anything else we need to know?:
Not a high priority but definitely nice to fix.
/kind documentation

If retaining the hyperlink with the comment for  `NamespaceStatus` struct, it should link to the concept page not the task. In other words, the link should be to https://k8s.io/docs/concepts/overview/working-with-objects/namespaces/

#### Environment:
- Kubernetes version (use `kubectl version`): v1.21
- Cloud provider or hardware configuration: *n/a*
- OS (e.g: `cat /etc/os-release`): *n/a*
- Kernel (e.g. `uname -a`): *n/a*
- Install tools: *n/a* 
- Network plugin and version (if this is a network-related bug): *n/a*
- Others:
/sig docs
/sig architecture

### PR DESCRIPTION
**Pull request by Shatakshi0805**
#### What type of PR is this?
   /kind bug   /kind documentation
 

#### What this PR does / why we need it:
This PR changes the link in Phase section of https://kubernetes.io/docs/reference/kubernetes-api/cluster-
resources/namespace-v1/ to https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
After the changes, the phase section will link to the site that allows details of .status.phase

 #### Which issue(s) this PR fixes:

Fixes #102180

#### Does this PR introduce a user-facing change?

```release-note
fix- source for Namespace API reference.
```
#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Shatakshi0805** [comment]
Fixes #102180

**Comment by Shatakshi0805** [comment]
Apologies for not mentioning the required fields. 

 What type of PR is this?
  
  kind/bug

 What this PR does / why we need it:    
  
 This PR changes the link in Phase section of https://kubernetes.io/docs/reference/kubernetes-api/cluster- 
 resources/namespace-v1/ to https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/
  After the changes, the phase section will link to the site that allows details of .status.phase

  Which issue(s) this PR fixes:

  Fixes #102180

  Special notes for your reviewer:

 Does this PR introduce a user-facing change?

Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

**Comment by Shatakshi0805** [comment]
/label api-review
sig/api-machinery

**Comment by liggitt** [comment]
neither link seems to describe details about phases... it's not clear why the new link is a better link for this field

**Pull request closed without merging**
