### PR TITLE
generic ephemeral volume GA

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Generic ephemeral volume has met the GA criteria and is meant to graduate to GA in 1.23.

#### Special notes for your reviewer:

This contains two other minor PRs that were still pending when creating this PR:
- https://github.com/kubernetes/kubernetes/pull/105544
- https://github.com/kubernetes/kubernetes/pull/105545

Some other locations where the helper functions could be used were found when removing the feature gate.

#### Does this PR introduce a user-facing change?
```release-note
The "Generic Ephemeral Volume" feature graduates to GA. It is now enabled unconditionally.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/blob/e669a1483064f4a3f248e78c9b8399858ca75f66/keps/sig-storage/1698-generic-ephemeral-volumes/README.md
```

### CODE REVIEW

**Comment by neolit123** [comment]
note, this issue is not resolved yet:
https://github.com/kubernetes/kubernetes/issues/99305
where it was discovered that static pods cannot safely use ephemeral storage.

ideally there should be a resolution to the problem or the support claim around static pods should be updated.

potential PR fix is here:
https://github.com/kubernetes/kubernetes/pull/101882

cc @jackfrancis

**Comment by pohly** [comment]
> note, this issue is not resolved yet: #99305 where it was discovered that static pods cannot safely use ephemeral storage.

That seems to be about some other kind of ephemeral storage, the one managed by kubelet.

This feature here is about ephemeral volumes provisioned by a storage driver (typically CSI nowadays).

**Comment by neolit123** [comment]
> That seems to be about some other kind of ephemeral storage, the one managed by kubelet.

ok, my mistake.
the problem feature gate in question there was LocalStorageCapacityIsolation

**Review by thockin — COMMENTED** [review]
/approve

**Pull request merged**
