### PR TITLE
Centos baremetal: auto troubleshooting when deploy and change minion to node

### PR DESCRIPTION
**Pull request by kevin-wangzefeng**
1. In the existing implementation, when deploying, the scripts will ssh to master and node to check if kubernetes processes are running, which is not the standard way. This PR is to refactor the this logic by calling `validate-cluster.sh`, and after it returns, if the cluster is not running correctly, the scripts will check all the services' status on each node, making it more helpful for troubleshooting.  
2. Also updated wording from minion to node

### CODE REVIEW

**Comment by brendandburns** [comment]
This LGTM, but I don't have a way to test it.  @eparis can you take a look?

**Comment by kevin-wangzefeng** [comment]
rebased to latest master, PTAL. 
Re-pining @eparis

**Comment by brendandburns** [comment]
ping @eparis

**Comment by eparis** [comment]
Sorry! Looking.

**Pull request merged**
