### PR TITLE
Adjust node_exporter CPU params

### PR DESCRIPTION
**Pull request by SuperQ**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

The node_exporter CPU use is bursty, as it needs a bit of CPU at scrape time. Don't set a CPU limit to avoid collection stalls.

Set the request to 100m to more closely match the typical max core needs.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

None

```release-note

```

### CODE REVIEW

**Comment by serathius** [comment]
This addon is used for e2e tests only. 
Changing node_exporter cpu doesn't influence tests stability, so I don't think we need it.

For more mature prometheus setups on k8s please refer to [Prometheus Operator](https://github.com/coreos/prometheus-operator) and[ kube-prometheus](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus).

**Comment by SuperQ** [comment]
@serathius Apparently people are copy-n-paste using this instead of the operator. See [this thread](https://groups.google.com/forum/#!topic/prometheus-users/O5drJtYDrgo). As the node_exporter maintainer, I'd like to make sure it doesn't cause more problems for users.

**Comment by SuperQ** [comment]
Another option would be to move the files to a "tests" directory, rather than "addons". This would make it more clear that the files are not meant to be consumed by end users.

**Comment by SuperQ** [comment]
I signed it

**Comment by brancz** [comment]
@serathius I think @SuperQ's request to move the files to a `test` directory is justified. @serathius could you follow up with that? To my knowledge the addons directory is supposed to be removed piece by piece anyways. Let's find a new home with a more accurate description for it! :slightly_smiling_face: 

As for this:

/lgtm

**Pull request merged**
