### PR TITLE
Automated cherry pick of #118257: dra scheduler plugin test: fix loopvar bug and "reserve"

### PR DESCRIPTION
**Pull request by pohly**
Cherry pick of #118257 on release-1.27.

#118257: dra scheduler plugin test: fix loopvar bug and "reserve"

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by pohly** [comment]
The reason for cherry-picking a fix for a test is to make the code ready for a future Go release with different loopvar behavior (see https://github.com/kubernetes/release/issues/3076).

/cc @liggitt

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
