### PR TITLE
kube-scheduler: stop using insecure serving bits

### PR DESCRIPTION
**Pull request by ingvagabund**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Stop using insecure serving bits in kube-scheduler

**Which issue(s) this PR fixes**:

xref #91506

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Comment by alculquicondor** [comment]
Can't really approve any of these files 😅

**Comment by deads2k** [comment]
/approve

you'll still need someone for cluster

**Pull request merged**
