### PR TITLE
Revert "Revert "Drop support for --gce-service-account, require activated creds""

### PR DESCRIPTION
**Pull request by fejta**
Reverts kubernetes/kubernetes#29242

### CODE REVIEW

**Comment by fejta** [comment]
Will see how this goes before assigning to someone for review

**Comment by fejta** [comment]
https://github.com/kubernetes/test-infra/issues/266

**Comment by fejta** [comment]
Soak tests need this PR: https://github.com/kubernetes/kubernetes/issues/28399 https://github.com/kubernetes/kubernetes/issues/28514

**Comment by lavalamp** [comment]
Please fix your github email and do the revert again to make the CLA bot happy?

**Comment by fejta** [comment]
@lavalamp Reverts always do this because it was done by the merge bot

**Comment by rmmh** [comment]
The commit isn't from your google.com email.

**Comment by fejta** [comment]
Well that simultaneously makes sense and is dumb :)

**Comment by fejta** [comment]
Adding retest-not-required to unblock soak tests

**Pull request merged**
