### PR TITLE
Enable field management for all new objects

### PR DESCRIPTION
**Pull request by apelisse**
Re-enables SSA for all new objects since we've fixed the flakes.

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
For now ..
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by apelisse** [comment]
To be merged after #88382

cc @jpbetz @liggitt

**Comment by jpbetz** [comment]
The 9 e2e tests runs with SSA at 100% in the description of #88382 show that the GC flake issue is resolved and that we can expect test stability to be comparable with what exists today on master.
/lgtm
/hold for #88382 merge

**Comment by apelisse** [comment]
#88382 has merged
/hold cancel

**Comment by jpbetz** [comment]
wholesale failures of In-tree Volumes tests

/test pull-kubernetes-e2e-gce

**Comment by apelisse** [comment]
cc @kubernetes/sig-scalability-misc

**Comment by fedebongio** [comment]
yay! we made it!

**Pull request merged**
