### PR TITLE
kubeadm: reduce some functions number of parameters

### LINKED ISSUE #1429: Reduce number of parameters in init.go
Following the init phases work in 1.13, we are left with a couple of functions in `init.go`, that take an awful lot of parameters, but should only take a single struct pointer and use that.

1. `AddInitOtherFlags`:
- [Definition](https://github.com/kubernetes/kubernetes/blob/36787041cbb7a83531ffea765b045117f2fb301c/cmd/kubeadm/app/cmd/init.go#L228) from latest master:
```
func AddInitOtherFlags(
	flagSet *flag.FlagSet,
	cfgPath *string,
	skipTokenPrint, dryRun, uploadCerts *bool,
	ignorePreflightErrors *[]string,
) {
```

- The only [invocation](https://github.com/kubernetes/kubernetes/blob/36787041cbb7a83531ffea765b045117f2fb301c/cmd/kubeadm/app/cmd/init.go#L143):
```
AddInitOtherFlags(cmd.Flags(), &initOptions.cfgPath, &initOptions.skipTokenPrint, &initOptions.dryRun, &initOptions.uploadCerts, &initOptions.ignorePreflightErrors)
```

- New definition:
```
func AddInitOtherFlags(flagSet *flag.FlagSet, initOptions *initOptions)
```

- How it should be invoked:
```
AddInitOtherFlags(cmd.Flags(), initOptions)
```

2. `printJoinCommand`:
- [Definition](https://github.com/kubernetes/kubernetes/blob/36787041cbb7a83531ffea765b045117f2fb301c/cmd/kubeadm/app/cmd/init.go#L479) from latest master:
```
func printJoinCommand(out io.Writer, adminKubeConfigPath, token, key string, skipTokenPrint, uploadCerts bool) error
```

- The only [invocation](https://github.com/kubernetes/kubernetes/blob/36787041cbb7a83531ffea765b045117f2fb301c/cmd/kubeadm/app/cmd/init.go#L499):
```
printJoinCommand(out, adminKubeConfigPath, token, i.certificateKey, i.skipTokenPrint, i.uploadCerts)
```

- New definition:
```
func printJoinCommand(out io.Writer, adminKubeConfigPath, token string, i *initData) error
```

- How it should be invoked:
```
printJoinCommand(out, adminKubeConfigPath, token, i)
```

In both cases the structs are already put in place. What needs to be done is a simple refactor, that replaces the parameters in those structs with the structs themselves (as shown in the examples above).

Don't hesitate to ping me, I'll be happy to give you guidance and reviews.

/kind cleanup
/priority important-longterm
/good-first-issue

### PR DESCRIPTION
**Pull request by pytimer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubeadm/issues/1429

**Special notes for your reviewer**:

This PR wants to reduce some functions number of parameters in `cmd/kubeadm`. I'm still watching if there is similar phenomenon. And i will list them.

I will refactor the functions in the https://github.com/kubernetes/kubeadm/issues/1429 at first. If there are other similar places, welcome to point out.

- [x] [AddInitOtherFlags](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/init.go#L228)  in `cmd/kubeadm/app/cmd/init.go`

- [x] [printJoinCommand](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/init.go#L479)  in `cmd/kubeadm/app/cmd/init.go`

- [x] [addJoinOtherFlags](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/join.go#L197) in `cmd/kubeadm/app/cmd/join.go`

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by yagonobre — COMMENTED** [review]
Thanks @pytimer, Can you send a pr for init and another to join workflow?
/ok-to-test
/priority important-longterm

**Comment by pytimer** [comment]
@yagonobre Did you mean that i separated this PR, one is init.go, another is join.go, is it?

**Comment by neolit123** [comment]
>> Thanks @pytimer, Can you send a pr for init and another to join workflow?

> Did you mean that i separated this PR, one is init.go, another is join.go, is it?

to me it seems fine to have the change in the same PR because it makes the same type of change in the files. but no strong opinions.

in the meantime, i will `/retest` here to test if golang 1.12 passes.
/retest

**Comment by pytimer** [comment]
@neolit123 thanks for your answer.

> in the meantime, i will test here to see if golang 1.12 passes.

If it need me to do anything, please tell me.

**Review by neolit123 — COMMENTED** [review]
/approve
@pytimer please remove the WIP from the PR title if the work here is done.
i will leave the LGTM to someone else.

**Comment by pytimer** [comment]
@neolit123 ok. If there are no problems, I will remove the wip and squash commits later.

**Comment by yagonobre** [comment]
I'm ok with a single pr too. @fabriziopandini are you ok with it?

**Comment by neolit123** [comment]
hm, @fabriziopandini did say separate PR here: https://github.com/kubernetes/kubeadm/issues/1429#issuecomment-468341597

**Comment by pytimer** [comment]
@neolit123 @yagonobre I will wait for @fabianofranz reply, then let's see how to do.

**Review by rosti — APPROVED** [review]
Thank you @pytimer !
I am fine with having a single PR.
@pytimer can you squash the commits?

/lgtm

**Comment by pytimer** [comment]
@neolit123 I remove the WIP.

@rosti I squash commits.

**Review by rosti — APPROVED** [review]
Thanks for the quick response @pytimer !
Let's get this in, I am not bothered by the fact that this covers join too. It basically improves code quality that was reduced in the same manner for equivalent init and join functionality, thus a single PR is fine.

/lgtm

**Comment by pytimer** [comment]
Thanks @rosti .

**Pull request merged**
