### PR TITLE
kubeadm: Force to disable debug mode for `crictl`

### LINKED ISSUE #110873: kubeadm: `cleanup-node` failed due to crictl is configured in debug mode
### What happened?

```kubeadm reset phase cleanup-node``` prints out some warning messsage: 

> [reset] Failed to remove containers: [failed to stop running pod time="2022-06-30T14:55:44+08:00": output: time="2022-06-30T14:55:44+08:00" level=debug msg="get runtime connection"

And the pod on that node is not removed eventually.

### What did you expect to happen?

all the pods could be removed at last.

### How can we reproduce it (as minimally and precisely as possible)?

Have a crictl installed on the node with the config like this, 
```
runtime-endpoint: unix:///var/run/containerd/containerd.sock
image-endpoint: unix:///var/run/containerd/containerd.sock
timeout: 2
debug: true
pull-image-on-create: false
```

And then run below command, 
```kubeadm reset phase cleanup-node```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>
```console
$ kubectl version
# paste output here

master

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by chendave**
Signed-off-by: Dave Chen <dave.chen@arm.com>

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/110873

#### Special notes for your reviewer:
pls see the issue here: https://github.com/kubernetes/kubernetes/issues/110873 for more details.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig cluster-lifecycle

/cc @neolit123

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
When was the -D flag added?
We need to make sure it's available in old versions of crictl.

**Comment by chendave** [comment]
> When was the -D flag added?

@neolit123  
the debug mode was introduced from the initial commit for the `crictl`, 
https://github.com/kubernetes-sigs/cri-tools/pull/29/files#diff-91a0971562e77913daa465a20737911f98321291c57ec117c07b0741347afc84R57-R60

and "-D" was introduced soon after that one,
https://github.com/kubernetes-sigs/cri-tools/pull/123/files#diff-91a0971562e77913daa465a20737911f98321291c57ec117c07b0741347afc84R130

**Review by neolit123 — COMMENTED** [review]
ok, thanks for checking.

/lgtm
/approve
/triage accepted

**Pull request merged**
