### PR TITLE
vendor: update hcsshim to v0.6.11

### PR DESCRIPTION
**Pull request by jessfraz**
Ran all the godep scripts according to
https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md,
seems like some other lines in Godeps.json got modified as well but they are all
the same sha only slightly longer...

Signed-off-by: Jess Frazelle <acidburn@microsoft.com>

cc @liggitt @cjcullen @tallclair @philips

```release-note
Updated hcsshim dependency to v0.6.11
```

### CODE REVIEW

**Comment by jessfraz** [comment]
@brendanburns or @smarterclayton can you approve this

**Comment by khenidak** [comment]
had a quick discussion with @jessfraz - The change is looking good, we just need to test it on windows (due to lack of windows e2e).

**Comment by jessfraz** [comment]
verified it works :)

**Comment by cblecker** [comment]
/approve
Dep bump looks fine. Existing import, no licence changes. It's used by `pkg/proxy/winkernel/`.

**Comment by dims** [comment]
/status approved-for-milestone

per @brendanburns 's approval above

**Pull request merged**
