### PR TITLE
Let go.mod and go.sum be approved by dep-approvers

### PR DESCRIPTION
**Pull request by liggitt**
Follow up from https://github.com/kubernetes/kubernetes/pull/74877

/cc @cblecker @nikhita

### CODE REVIEW

**Comment by nikhita** [comment]
Thanks!

/assign @cjwagner 
/hold
just want to get ack from @cjwagner that this will actually work :)

Ref: the warning here https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#filters

**Comment by liggitt** [comment]
Huh… I just went off the existing filter+approve use

**Comment by nikhita** [comment]
> Huh… I just went off the existing filter+approve use

Last I heard it doesn't actually work :P

**Comment by nikhita** [comment]
Some context: https://kubernetes.slack.com/archives/C7J9RP96G/p1548265578190600

**Comment by cjwagner** [comment]
Unfortunately this will not work. See the issue mentioned in the warning: https://github.com/kubernetes/test-infra/issues/7690

**Comment by liggitt** [comment]
ah, ok :cry:

/close

**Pull request closed without merging**
