### PR TITLE
Bump k8s.io/kube-openapi

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Updates to preserve openapi ipv4 validation compatibility with pre-go1.17 behavior

xref #100895 

```release-note
NONE
```

/assign @aojea

### CODE REVIEW

**Comment by aojea** [comment]
/hold

```
2021/08/17 14:57:15 Inspecting imports under ./vendor/k8s.io/kube-openapi/...
2021/08/17 14:57:15 - validating imports for 19 packages in the tree
2021/08/17 14:57:15 -- found forbidden imports for k8s.io/kubernetes/vendor/k8s.io/kube-openapi/pkg/validation/strfmt:
2021/08/17 14:57:15 --- k8s.io/utils/net
2021/08/17 14:57:15 - FAIL
```

some sort of circular dependency?

**Comment by liggitt** [comment]
not a cycle, the import restrictions file needed updating (and correcting... kube-openapi should definitely not depend on apimachinery)

**Comment by liggitt** [comment]
cc @jpbetz for the "Regenerate applyconfigurations" commit... does that delta look correct?

**Comment by liggitt** [comment]
thanks for verifying

/hold cancel

**Comment by aojea** [comment]
/lgtm
go go go

**Pull request merged**
