### PR TITLE
e2e node: fix the race condition under the memory manager test

### LINKED ISSUE #101458: [Feature:MemoryManager] fails because race condition between kubelet restart by e2e service and kubelet stop by memory manager
#### Which jobs are flaking:

kubelet-serial-gce-e2e-memory-manager

#### Which test(s) are flaking:

no specific test, because the failure happens during waiting for the kubelet to come back after the restart

#### Testgrid link:

https://testgrid.k8s.io/sig-node-kubelet#kubelet-serial-gce-e2e-memory-manager

#### Reason for failure:

- the memory manager under the teardown, updates the kubelet configuration via dynamic configuration - https://github.com/kubernetes/kubernetes/blob/6067d8556a017102fcd92c6a06738524c36847a9/test/e2e_node/memory_manager_test.go#L385
- because of the update, the kubelet health check is not responding for some short time period - https://github.com/kubernetes/kubernetes/blob/6067d8556a017102fcd92c6a06738524c36847a9/test/e2e_node/services/server.go#L193
- e2e node service restart the kubelet - https://github.com/kubernetes/kubernetes/blob/6067d8556a017102fcd92c6a06738524c36847a9/test/e2e_node/services/server.go#L223
- next memory manager test started and it stops the kubelet - https://github.com/kubernetes/kubernetes/blob/6067d8556a017102fcd92c6a06738524c36847a9/test/e2e_node/memory_manager_test.go#L319
- the e2e_node service fails on the initial health check - https://github.com/kubernetes/kubernetes/blob/6067d8556a017102fcd92c6a06738524c36847a9/test/e2e_node/services/server.go#L173

#### Anything else we need to know:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

### PR DESCRIPTION
**Pull request by cynepco3hahue**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

Wait for the kubelet to be healthy after the dynamic update of the kubelet configuration to prevent the race condition between kubelet stop and restart commands.

#### Which issue(s) this PR fixes:

Fixes #101458

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by fromanirh** [comment]
/lgtm
the fix per se looks straightforward, I wonder if we should generalize it somehow.

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
