### PR TITLE
Automated cherry pick of #110256: kubelet: Mark ready condition as false explicitly for terminal pods

### PR DESCRIPTION
**Pull request by bobbypage**
Cherry pick of #110256 on release-1.23.

#110256: kubelet: Mark ready condition as false explicitly for terminal pods

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fixed a 1.22 regression kubelet issue that could result in invalid pod status updates to be sent to the api-server where pods would be reported in a terminal phase but also report a ready condition of true in some cases.
```

### CODE REVIEW

**Comment by bobbypage** [comment]
Cherrypick was not fully clean - the only manual conflict was on the e2e test update which required updating the go imports.

```
$ git diff
diff --cc test/e2e_node/node_shutdown_linux_test.go
index baa2fdf3b6c,32ff9ccb549..00000000000
--- a/test/e2e_node/node_shutdown_linux_test.go
+++ b/test/e2e_node/node_shutdown_linux_test.go
@@@ -24,11 -24,16 +24,19 @@@ import
        "fmt"
        "os"
        "path/filepath"
 +      "strconv"
        "time"

 -      apierrors "k8s.io/apimachinery/pkg/api/errors"
        "k8s.io/apimachinery/pkg/fields"
+       "k8s.io/apimachinery/pkg/watch"
+       "k8s.io/client-go/tools/cache"
+       watchtools "k8s.io/client-go/tools/watch"
        "k8s.io/kubectl/pkg/util/podutils"
++<<<<<<< HEAD
++=======
+
+       admissionapi "k8s.io/pod-security-admission/api"
++>>>>>>> test: update graceful node shutdown e2e with watch

        "github.com/onsi/ginkgo"
        "github.com/onsi/gomega"
```

**Review by hussain2022 — COMMENTED** [review]
Hussain حسين المنهالي

**Comment by bobbypage** [comment]
Unit tests failed

```
=== Failed
=== FAIL: pkg/controller/statefulset TestStatefulSetControlOnDeleteUpdate/Retain/StatefulSetAutoDeletePVCEnabled (0.67s)
W0609 18:07:25.452596   53150 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0609 18:07:25.452826   53150 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0609 18:07:25.452929   53150 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0609 18:07:25.453061   53150 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0609 18:07:26.063499   53150 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0609 18:07:26.063840   53150 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0609 18:07:26.064044   53150 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0609 18:07:26.064267   53150 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
    stateful_set_control_test.go:924: monotonic image update and scale up: claim for Pod foo-0 was not created
    --- FAIL: TestStatefulSetControlOnDeleteUpdate/Retain/StatefulSetAutoDeletePVCEnabled (0.67s)

=== FAIL: pkg/controller/statefulset TestStatefulSetControlOnDeleteUpdate (23.80s)
```

Same as flaky test report - https://github.com/kubernetes/kubernetes/issues/106663. Fixed in https://github.com/kubernetes/kubernetes/pull/107443, but it was not cherrypicked to 1.23.

/retest

**Comment by bobbypage** [comment]
ping @kubernetes/release-managers 

for cherrypick approvals.

Thank you!

**Pull request merged**
