### PR TITLE
Fix a bad cut/paste of a node label.

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes concerns [raised](https://github.com/kubernetes/kubernetes/pull/53146#pullrequestreview-66541495) in #53146

@mikedanese @jdumars

### CODE REVIEW

**Review by luxas — COMMENTED** [review]
Why is this in cmd/kubeadm?

I'm pretty sure kubeadm doesn't use this label... and I don't remember doing a review of a PR that added this. Do you have a clue where this actually is used?

cc @thockin

**Comment by justinsb** [comment]
@luxas presumably the idea is that kubeadm _should_ be setting it now :-)

**Comment by luxas** [comment]
@justinsb Any docs on this?

**Pull request merged**
