### PR TITLE
Set hung_task_panic in sysctl

### PR DESCRIPTION
**Pull request by bprashanth**
Context https://github.com/kubernetes/kubernetes/issues/20096

### CODE REVIEW

**Comment by dchen1107** [comment]
Even we decided to change kernel configs, I don't think we want to do it through salt for all nodes. We could change our containervm image for GKE and GCE by default.

**Comment by bprashanth** [comment]
> Even we decided to change kernel configs, I don't think we want to do it through salt for all nodes. We could change our containervm image for GKE and GCE by default.

But people may not want it?

**Comment by bprashanth** [comment]
I was planning on turning it on only for soak and seeing the damange it does, if we need to

**Comment by bprashanth** [comment]
We're just going to document these settings

**Comment by bprashanth** [comment]
New pr only enables the hung_task_panic flag on gce-soak-2. PTAL.

**Comment by dchen1107** [comment]
I am closing this one for now. Please reopen it if you disagree with me.

**Comment by bprashanth** [comment]
SG

**Pull request closed without merging**
