### PR TITLE
Use COS for nodes in testing clusters by default, and bump COS.

### PR DESCRIPTION
**Pull request by abgworrall**
Addresses part of issue #51487. May assist with #51961 and #50695.

CVM is being deprecated, and falls out of support on 2017/10/01. We shouldn't run test jobs on it. So start using COS for all test jobs.

The default value of `KUBE_NODE_OS_DISTRIBUTION` for clusters created for testing will now be gci. Testjobs that do not specify this value will now run on clusters using COS (aka GCI) as the node OS, instead of CVM, the previous default.

This change only affects testing; non-testing clusters already use COS by default.

In addition, bump the version of COS from `cos-stable-60-9592-84-0` to `cos-stable-60-9592-90-0`.

```release-note
NONE
```
/cc @yujuhong, @mtaufen, @fejta, @krzyzacy

### CODE REVIEW

**Comment by krzyzacy** [comment]
ah nice, which means we don't have to set --gcp-node-image=gci anymore?

**Comment by abgworrall** [comment]
@krzyzacy - to be honest, not sure; I don't know which layer of the config stack `--gcp-node-image` kicks in. There are a surprising number of layers ...

**Comment by krzyzacy** [comment]
@abgworrall that's equivalent to `KUBE_NODE_OS_DISTRIBUTION`, once this is in we can kill that env :-)
do we plan to backport it to previous branches as well?

**Comment by yujuhong** [comment]
Should we also convert existing CVM jobs to use COS? If not, we'll not have any CVM coverage. The worst case would be that we are forced support 1.8+CVM without any test coverage.

**Comment by krzyzacy** [comment]
So most of jobs has both cvm + gci coverage now, for master.

For 1.8, I'm only creating gci jobs, which should be fine if we are deprecating it before 1.8 is out?

**Comment by mtaufen** [comment]
@yujuhong we should maintain the tests that validate upgrade paths from CVM to other images. CVM won't be supported for 1.8.

**Comment by yujuhong** [comment]
> @yujuhong we should maintain the tests that validate upgrade paths from CVM to other images. CVM won't be supported for 1.8.

@dchen1107, you didn't want to remove the CVM test coverage for 1.8 last time we spoke. Have you changed your mind? :-)

**Comment by abgworrall** [comment]
I also recall a firm decision that 1.8 won't be expected to run on CVM, and so 1.8 will not be tested to run on CVM. This PR shouldn't go to 1.7; we still expect 1.7 to work on CVM.

**Comment by krzyzacy** [comment]
sgtm :-)

**Comment by abgworrall** [comment]
@dchen1107 - Dawn, do you want to veto / defer this ? I'd like to get it approved into 1.8 in the next day or two ...

**Comment by yujuhong** [comment]
What's the plan for the current *-gci-* jobs? I assume they'll be removed?

**Comment by abgworrall** [comment]
@yujuhong , I think that makes a ton of sense (with the exception of upgrade tests), and probs needs some manual verification that the non -gci- test doesn't hardcode CVM somehow.

**Comment by dchen1107** [comment]
CVM is deprecated for 1.8 for sure, and I am ok to remove cvm test coverage now.  
We should remove those dup gci test suites too, but that can come in a separate pr.

**Comment by abgworrall** [comment]
@kubernetes/kubernetes-release-managers - can you consider this for a 1.8 milestone label ? It should increase the reliability of some test jobs.

**Comment by yujuhong** [comment]
This is not that effective as most of the jobs have `KUBE_NODE_OS_DISTRIBUTION=debian` explicitly set in their test env file.

**Comment by krzyzacy** [comment]
@yujuhong we want to delete those jobs right :-)

**Comment by yujuhong** [comment]
@krzyzacy I thought we wanted to switch most jobs to using COS by default with this PR, and delete the COS-specific (*-gci*-) jobs?

**Comment by krzyzacy** [comment]
@yujuhong either way works :-)

**Comment by yujuhong** [comment]
The former seems easier to me, but yes, either way works. This PR itself didn't change anything though without the test-infra side change :-|

**Comment by xiangpengzhao** [comment]
/release-note-none

This PR doesn't need a release note. A release-note label will lead to noise in CHANGELOG.

**Pull request merged**
