### PR TITLE
Add dgrisonnet to sig-instrumentation approvers

### PR DESCRIPTION
**Pull request by dgrisonnet**
#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/kind cleanup
/sig instrumentation

/assign @ehashman @logicalhan

### CODE REVIEW

**Comment by aojea** [comment]
+1

**Comment by ehashman** [comment]
+1 (binding)

/assign @logicalhan @dashpole 
/cc @RainbowMango @serathius @brancz

**Comment by dashpole** [comment]
+1

**Comment by serathius** [comment]
+1

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
