### PR TITLE
Fix kubectl e2e test

### PR DESCRIPTION
**Pull request by gmarek**
It was broken for a very long time, but it surfaced yesterday.

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
LGTM. Let's make sure that e2e tests pass and that either travis or shippable is green.

**Comment by wojtek-t** [comment]
Shippable is green - merging.

**Comment by gmarek** [comment]
"should do a rolling update of a replication controller" in update-demo test is still failing, but it was even before this fix.

**Comment by jayunit100** [comment]
related: created https://github.com/GoogleCloudPlatform/kubernetes/pull/8325  to confirm namespaces are deleted efficiently

**Pull request merged**
