### PR TITLE
small fix in translation en.po file

### PR DESCRIPTION
**Pull request by cpanato**
**What this PR does / why we need it**:
While i'm doing the kubectl translation to pt-br notice this very small typo. this pr fix that

### CODE REVIEW

**Comment by cpanato** [comment]
@nikhita who can I ask for review?

**Comment by cpanato** [comment]
ping @kubernetes/sig-cli-maintainers  who can review this? thanks!

**Review by soltysh — CHANGES_REQUESTED** [review]
@cpanato please include this fix with the pt-br translation

**Comment by cpanato** [comment]
ok, so we close this? @soltysh

**Pull request closed without merging**
