### PR TITLE
refactor: change dynamicResources struct to DynamicResources

### PR DESCRIPTION
**Pull request by Subhasish-Behera**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

It refactors the `dynamicResources` struct to `DynamicResources` struct.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kannon92** [comment]
/remove-sig node
/sig scheduling

Even though DRA is led by sig-node, I think scheduling has the main say here.

**Comment by kannon92** [comment]
/ok-to-test

You will probably need to explain why this is necessary. Changing to DynamicResources implies that this should be exported for usage elsewhere.

**Comment by kannon92** [comment]
if the goal would be to use this in order projects should we be letting people import from K8s pkg/scheduler?

I thought that we would want to move this API to staging so people could import versioned apis into their projects.

**Comment by pohly** [comment]
The plugin depends on APIs that are only available in k/k (`pkg/scheduler/framework`), therefore it cannot be moved to staging - perhaps it could, but any consumer then would still depend on k/k, which defeats the purpose of moving the plugin to staging.

**Comment by kannon92** [comment]
Yea I took a look at scheduler plugins and I see it’s imported there so feel free to disregard this comment.

**Comment by Subhasish-Behera** [comment]
@pohly I tried importing this branch to use in Volcano for testing but there were some version mismatch errors. I will try to figure that out quickly (I am assuming that is the way to test before getting merged). 
But for reference the DRA plugin will be accessed in a similar manner as `nodeAffinity` and its filter function in one of volcano's own plugin (Link: https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/plugins/predicates/predicates.go#L308).

**Comment by pohly** [comment]
> I am assuming that is the way to test before getting merged

Yes.

**Comment by Subhasish-Behera** [comment]
The check is failing due to an end-to-end test failing. Is it because more refactoring is necessary.

**Comment by Monokaix** [comment]
> Apart from that, a check is failing due to an end-to-end test failing. Is it because more refactoring is necessary.

Try to retest it: )

**Comment by Monokaix** [comment]
Hi, I think we still need this and it's also reasonable that dra is just like other plugins that are visible externally.
And @Subhasish-Behera please resolve the code conflict: )

**Pull request closed without merging**
