### PR TITLE
cherry pick of #116140: update otelhttp to v0.35.1

### PR DESCRIPTION
**Pull request by dashpole**
#### What type of PR is this?

/kind bug
/sig instrumentation

#### What this PR does / why we need it:

Update the otelhttp dependency to include https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2983.  That patch is necessary to prevent port-forwarding from breaking when using APIServerTracing.

#### Which issue(s) this PR fixes:

Address https://github.com/kubernetes/kubernetes/issues/116139 on the 1.26 branch.

#### Does this PR introduce a user-facing change?
```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/647-apiserver-tracing/README.md
```

cc https://github.com/orgs/kubernetes/teams/sig-instrumentation-leads

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm

**Review by Verolop — COMMENTED** [review]
/lgtm

**Comment by pacoxu** [comment]
run `hack/update-vendor.sh` is needed.
/hold 
to avoid further auto-re-run.

**Comment by dashpole** [comment]
> run hack/update-vendor.sh is needed.

Fixed

@logicalhan needs LGTM again

**Comment by xmudrii** [comment]
@bart0sh @dashpole @liggitt This PR is on hold but has lgtm+approved. If you want to get this PR merged on this release branch, please remove hold and we'll be happy to cherry-pick-approve it.

**Comment by dashpole** [comment]
Hold was placed because tests were failing: https://github.com/kubernetes/kubernetes/pull/116143#issuecomment-1623011353, and tests are now passing

/hold cancel

**Review by xmudrii — APPROVED** [review]
For RelEng:
/lgtm
/approve

**Pull request merged**
