### PR TITLE
Add a test that validates the metadata server is resolvable

### PR DESCRIPTION
**Pull request by brendandburns**
@ixdy @spxtr

### CODE REVIEW

**Comment by ixdy** [comment]
Is this test supposed to fail? :)

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:625
Expected
    <string>: nslookup: can't resolve 'metadata'
    Server:    10.0.0.10
    Address 1: 10.0.0.10
    
    FAILED
    
to contain substring
    <string>: PASSED
```

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by ixdy** [comment]
@brendandburns are you still working on this?

**Comment by ixdy** [comment]
ping

**Comment by ixdy** [comment]
Closing. Please reopen if you still wish to pursue this PR.

**Pull request closed without merging**
