### PR TITLE
Fix golint failures: DefaultUrlScheme -> DefaultURLScheme

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fix golint failures: `DefaultUrlScheme` -> `DefaultURLScheme`

**Which issue(s) this PR fixes**:

Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by yagonobre — COMMENTED** [review]
Thanks @SataQiu 
/lgtm
/priority backlog

**Review by neolit123 — COMMENTED** [review]
@SataQiu 
i think we decided to not touch this lint failure, because it's part of v1beta1.

/assign @rosti

**Review by rosti — COMMENTED** [review]
Thanks for the contribution @SataQiu !
Unfortunately v1beta1 is already released and cannot be touched. Sort of the same change is going to be included in the next version of the config (v1beta2).

/hold

**Comment by SataQiu** [comment]
@neolit123 @rosti Thanks for yor feedback.

**Pull request closed without merging**
