### PR TITLE
Test case to ensure policy denies ingress traffic to ingress isolate pod

### LINKED ISSUE #114369: NetworkPolicy tests for blocking north/south traffic
The NP docs point out that [NP's semantics for north/south traffic are not very clearly defined](https://kubernetes.io/docs/concepts/services-networking/network-policies/#behavior-of-ipblock-selectors):

> Cluster ingress and egress mechanisms often require rewriting the source or destination IP of packets. In cases where this happens, it is not defined whether this happens before or after NetworkPolicy processing, and the behavior may be different for different combinations of network plugin, cloud provider, `Service` implementation, etc.
> 
> In the case of ingress, this means that in some cases you may be able to filter incoming packets based on the actual original source IP, while in other cases, the "source IP" that the NetworkPolicy acts on may be the IP of a `LoadBalancer` or of the Pod's node, etc.
> 
> For egress, this means that connections from pods to `Service` IPs that get rewritten to cluster-external IPs may or may not be subject to `ipBlock`-based policies.

However, what's _not_ ambiguous is that a pod which is fully isolated for ingress should not accept E/W _or_ N/S traffic. Regardless of how the ingress/LB/cloud handles the traffic, it should end up getting blocked. (Well, unless it gets masqueraded to the pod's node IP, because then it hits that exception to the rules.)

Unfortunately we can't say the same for egress; I think we assume that a pod-to-service-IP connection will be allowed to reach kube-proxy even if the pod is fully isolated-for-egress, but we explicitly don't require that `ipBlock` policies get applied after service proxying.

Anyway, we should be able to add a test to `test/e2e/network/netpol/network_policy.go` that confirms that cluster-ingress traffic to a fully isolated-for-ingress pod is not allowed. In particular, if we create a LoadBalancer Service with `externalTrafficPolicy: Local`, and a NetworkPolicy blocking all ingress to that Service's Pods, then we should not be able to connect to the service via either the LoadBalancer IP/name or via its NodePort (on one of the correct nodes).

/sig network
/area network-policy
/priority backlog
/help
/good-first-issue

### PR DESCRIPTION
**Pull request by aroradaman**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR adds a test case to the network policy test suite for ensuring that traffic cannot reach ingress-isolated pods.
#### Which issue(s) this PR fixes:

Fixes #114369

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by astoycos** [comment]
Hey @daman1807 Thanks for taking a look at this, It looks like you added a test to the legacy network policy suite, that's good but I think what's more important is adding it to newer truthtable tests found here -> https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/netpol/network_policy.go

**Comment by daman1807** [comment]
@astoycos I looked into [network_policy.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/netpol/network_policy.go) and found only intra-pod connectivity(E/W) tests by asserting on truth tables. In this case, we need to test N/S ingress traffic and I don't think it will be possible to do it with current truth table structures. In [network_legacy.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/netpol/network_legacy.go) I found similar tests which validated connectivity on services rather than pods and also a pod and service are initialized in Ginko context before each test in `network_policy.go` so I decided to put the test there.

Should I just move the test to `network_policy.go` and validate without using truth tables?

**Comment by astoycos** [comment]
Hrm I think we should still be using the truth tables/ new style tests and no adding a test which doesn't use the new tables to the new code probably isn't the right route either....we may just need to add the required functionality to the truth table functions. I'll have to take a fresh look to see how difficult it'll be but ultimately that seems like the right way forward.

**Comment by daman1807** [comment]
@astoycos Can I create a similar matrix and reachability tests for N/S ?
The original will work for E/W traffic

**Pull request closed without merging**
