### PR TITLE
Improve the performance of map usage

### PR DESCRIPTION
**Pull request by sourcelliu**
#### What type of PR is this?
/kind cleanup
/sig node

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
By the way, if you are able to address a similar issue in the same file located at https://github.com/kubernetes/kubernetes/pull/116922/files#diff-abe55fe94cc242fa5db3d3884128129ef2c40bc7f86006f1e10454a6630c1dc4R124 on line 124 (I am unsure if there are any other issues within this package), it would be beneficial to fix them altogether. Involving multiple SIGs could slow down the process, so I suggest only searching for issues around this specific package.

**Comment by sourcelliu** [comment]
> By the way, if you are able to address a similar issue in the same file located at https://github.com/kubernetes/kubernetes/pull/116922/files#diff-abe55fe94cc242fa5db3d3884128129ef2c40bc7f86006f1e10454a6630c1dc4R124 on line 124 (I am unsure if there are any other issues within this package), it would be beneficial to fix them altogether. Involving multiple SIGs could slow down the process, so I suggest only searching for issues around this specific package.

In this PR, I optimized the map in the state package. @pacoxu PTAL, thanks.

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
