### PR TITLE
Automated cherry pick of #53167 upstream release 1.7

### PR DESCRIPTION
**Pull request by dashpole**
Cherrypick of #53167 to the 1.7 branch

/assign @wojtek-t 

```release-note
BugFix: Exited containers are not Garbage Collected by the kubelet while the pod is running
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
@yujuhong - can you please review and LGTM it?

**Comment by dashpole** [comment]
This contains some changes from #50350 as well.
Namely:
The change from using [isPodDeleted](https://github.com/kubernetes/kubernetes/pull/53748/files#diff-b57ee520cf026230be62d4063c9247f2L163) to [IsPodDeleted()](https://github.com/kubernetes/kubernetes/pull/53748/files#diff-10055ae93a8699af13ceba0482fc43c3R761)

**Comment by wojtek-t** [comment]
@yujuhong @dchen1107 - friendly ping for review this cherrypick

**Comment by yujuhong** [comment]
> This means we will garbage collect pods that have the deletion timestamp set, and where all containers have exited.

This is a bigger change than fixing the original bug. Can we not introduce this behavior for the patch?

**Comment by dashpole** [comment]
sure.  Ill post an update

**Comment by dashpole** [comment]
@yujuhong I reverted the change in determining if a pod is deleted.  This should be the minimal change now.

**Comment by yujuhong** [comment]
/lgtm

Thanks!

**Pull request merged**
