### PR TITLE
Fix issues with Python3 and bring up a dev cluster

### PR DESCRIPTION
**Pull request by zquestz**
There was a tiny issue with the dev scripts causing my archlinux setup to fail. Just fixed the print calls so they are happy in python3. Change is tiny, tests are passing, and I can now bring up a working vagrant cluster without changing my python symlink to python2 every time.

This is my first PR on the project, so if you need anything else please let me know!

### CODE REVIEW

**Comment by zquestz** [comment]
CLA has been signed!

**Comment by zquestz** [comment]
I signed it!

**Comment by zmerlynn** [comment]
@k8s-bot ok to test

**Comment by zmerlynn** [comment]
LGTM

**Comment by zquestz** [comment]
Added a few more fixes, hope you don't mind. Fixes issues:

https://github.com/kubernetes/kubernetes/issues/19453
https://github.com/kubernetes/kubernetes/issues/18805
https://github.com/kubernetes/kubernetes/issues/12025

**Comment by zmerlynn** [comment]
Still LGTM. As for etiquette... in this case it was a small addition, but usually I'd avoid churn after an LGTM. (You saw that our bots will automatically react, remove LGTM and retest, so it requires intervention.)

Please now squash the two commits.

**Comment by zquestz** [comment]
Rebased.

**Comment by zmerlynn** [comment]
@zquestz: Thanks!

**Comment by zquestz** [comment]
NP thanks for letting me know the process. You will see more in the near future. =)

**Comment by zquestz** [comment]
I see a test failure, but it does not seem to be related to my change. How to proceed?

**Comment by zmerlynn** [comment]
@k8s-bot e2e test this

**Comment by zmerlynn** [comment]
@zquestz: It's probably a flake, kicking. Also the submit queue is somewhat backed up (http://submit-queue.k8s.io/, so this may be a while even so.)

**Comment by zmerlynn** [comment]
@zquestz: Yeah, looks like it was just a flake. This is just waiting on the [submit queue](http://submit-queue.k8s.io/) now.

**Comment by zquestz** [comment]
Excellent, thanks!

**Pull request merged**
