### PR TITLE
Clean code: optimize some logs

### PR DESCRIPTION
**Pull request by songxiao-wang87**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
Optimize some logs, merge some logs and delete redundant.

Which issue(s) this PR fixes:
Fixes #

Special notes for your reviewer:
none

Does this PR introduce a user-facing change?
none

```release-note

NONE

```

### CODE REVIEW

**Comment by songxiao-wang87** [comment]
@yangjunmyfm192085

**Comment by pacoxu** [comment]
Why should we merge the log? Are there any principles that you follow?
The change confused me.

**Comment by songxiao-wang87** [comment]
@pacoxu please see https://github.com/kubernetes/kubernetes/pull/95818

**Comment by pacoxu** [comment]
In #95818, the log was merged as the error message and output is related and should be in a line and better for debugging.

In this PR, we don't have a similar problem here. And IMO, the output with this change is not better than the current one.
so -1 from me.

**Pull request closed without merging**
