### PR TITLE
bump zookeeper-installer image version in e2e

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind cleanup
/sig testing

**What this PR does / why we need it**:

After this https://github.com/kubernetes/kubernetes/pull/73194 merged, update e2e case to use the newest image version.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by danielqsj** [comment]
Hold this PR until #73194 merged and new image pushed to gcr.io .
/hold

**Comment by ixdy** [comment]
cc @listx

**Pull request merged**
