### PR TITLE
Fix the kubelet node watch

### PR DESCRIPTION
**Pull request by yujuhong**

### CODE REVIEW

**Comment by yujuhong** [comment]
From #6423, @lavalamp, @bgrant0607

**Comment by lavalamp** [comment]
Yikes-- I hope I didn't break anything else

**Comment by lavalamp** [comment]
Looks like failures are unrelated.

**Comment by yujuhong** [comment]
Uh....I wrote some comment on my laptop yesterday but apparently it got lost before being posted. This PR doesn't solve the problem. It adapted kubelet to work with v1beta3, but it broke v1beta1 instead :\  It worked on my desktop only because the default version now is v1beta3. If you look at the shippable builds, you could see that one of them (v1beta1) had the same  error messages in kubelet.log.

Kubelet would need to support both versions. @lavalamp, do you have a better fix?

**Comment by lavalamp** [comment]
I guess the coffee hasn't kicked in, of course you're right, I should have noticed.

We need a different field selector depending on the api version.

**Comment by lavalamp** [comment]
Let's see... is it better to leave v1beta3 broken? Should we revert this?

**Comment by lavalamp** [comment]
Ideally, we'd fix this in the client, but here's an example of an analogous situation and what was done:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L300

**Comment by bgrant0607** [comment]
Please do not break v1beta3.

**Comment by yujuhong** [comment]
@lavalamp, kubelet uses `Client.Interface` so it has no access to the apiversion, unlike the example you mentioned where `Client.Client` was used.

**Comment by lavalamp** [comment]
@yujuhong OK we should definitely fix this in the client library, then.

**Comment by lavalamp** [comment]
I'm working on a fix.

**Pull request merged**
