### PR TITLE
add flag --idempotent to kubectl label command

### PR DESCRIPTION
**Pull request by cypherfox**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
It adds an option `--idempotent` to the kubectl label command, which will have the command complete successfully, if no change to the object is necessary to fulfil the requested labels and their values.

This makes it easier to ensure labels are set in a shell script, since you can call it repeatedly and subsequent calls will not fail. Using `--overwrite` instead could delete changes that where intentional.

**Which issue(s) this PR fixes**:
(none)

**Special notes for your reviewer**:
This is an update from #80506 to fix git merges and such.

**Does this PR introduce a user-facing change?**:
Add --idempotent option to kubectl label command. 

```release-note
Add --idempotent option to kubectl label command. This makes ensuring presence of labels in shell scripts easier.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by cypherfox** [comment]
@apelisse could please have a look at this, so the tests can run through? TIA

**Comment by apelisse** [comment]
> This makes it easier to ensure labels are set in a shell script, since you can call it repeatedly and subsequent calls will not fail.

I don't understand what fails today? I don't understand what you're trying to do in that shell script.

**Review by soltysh — CHANGES_REQUESTED** [review]
I agree with Antoine here, I'm not sure your approach is correct and this doesn't look like a good fix for it, either. 
/hold

**Comment by cypherfox** [comment]
The idea is to support idempotent bash scripts. to ensure that a label is set:

I have a set up script that adds a label to `kube-system`. 
* ATM I cannot simply apply a pre-generated yaml. as that may overwrite lables set by other components (e.g.  a control plane element that generates this namespace automatically) 
*  I cannot run `kubectl label` repeatedly, as it will fail with an error when the label has already been set. But I do not want to suppress the error result of `kubectl label`, to be informed of failure to the operation.

**Comment by soltysh** [comment]
> * ATM I cannot simply apply a pre-generated yaml. as that may overwrite lables set by other components (e.g.  a control plane element that generates this namespace automatically)

Just re-run and if it fails you need to react accordingly. Also why would all components set the same labels, that doesn't sound reasonable. 

> * I cannot run `kubectl label` repeatedly, as it will fail with an error when the label has already been set. But I do not want to suppress the error result of `kubectl label`, to be informed of failure to the operation.

What's wrong with looking at the error?

**Comment by cypherfox** [comment]
> > * ATM I cannot simply apply a pre-generated yaml. as that may overwrite lables set by other components (e.g.  a control plane element that generates this namespace automatically)
> 
> Just re-run and if it fails you need to react accordingly. Also why would all components set the same labels, that doesn't sound reasonable.

With "components" I meant any other tool or part of K8s that may or may not have changed the labels on any resource I wish  to manipulate. The point is: I do not know if anything else has change the resource. My `kubectl` should only set the label if needed, and leave everything else untouched.

I do not run these things by hand. And "acting accordingly" would mean I have to wrap each one line call to set a label with a error handling code, when I want the script to fail on anything but a label already set to the same value as given in the command line.

> What's wrong with looking at the error?

This is not intended for manual use, but `kubectl` being run in a batch job. 
And I want to do something idiomatic (set a label idempotently) and would need a lot more logic repeated in each script.

**Comment by apelisse** [comment]
> I cannot run kubectl label repeatedly, as it will fail with an error when the label has already been set.

Thanks for explaining @cypherfox. It makes more sense to me now, and I think that's what's wrong. I find it hard to have an error if the label is already there. Let me look at it a little bit.

**Comment by apelisse** [comment]
What about `--overwrite`?

**Comment by cypherfox** [comment]
`--overwrite` will set the label to a new value, even if already set. This may indicate that a different process has already set the value. Depending on the situation this may either lead to a flapping value, or the one with the better retry logic will win.

**Comment by apelisse** [comment]
OK I see. I think we would accept a patch that returns a different error code if the label is already set to that value (like 1). We already return the exit status of diff in `kubectl diff` which returns 1 if there is an actual difference.

Now it's easy to make to turn the return code into a failure: `test $? -le 1`.

**Comment by cypherfox** [comment]
OK, so
`kubectl label pods foo unhealthy=true || test $? -eq 1`
instead of 
`kubectl label pods foo unhealthy=true --idempotent`
I can accept that (it is a self contained one-liner) , but I do not understand why you dislike an option that states its behavior and thus makes the code more self-explaining.
I'd not argue for either or, but rather for both! ;-)

I have one or two further ideas to make `kubectl` more useful in bash batches and I would like to understand the motivation before writing tons of code.

**Comment by apelisse** [comment]
I'd rather avoid feature bloat in general, but I'd really love to hear about your other ideas :-)

**Comment by cypherfox** [comment]
initially an option `--wait-once`for `kubectl get`in order to allow for something like
```bash
while true
      do
        kubectl patch validatingwebhookconfiguration validation.gatekeeper.sh --patch '{"webhooks": [{"name": "validation.gatekeeper.sh", "sideEffects": "None"}]}'
        kubectl get validatingwebhookconfiguration validation.gatekeeper.sh --watch-only --watch-once
      done
```
in a side-car container to ensure the config stays set in a particular way without the need for a `while true; <stuff> ; sleep 360 ; done`busy-loop.

**Comment by soltysh** [comment]
Yeah, the topic of different return code, based on the errors is something that was brought in the past during sig-cli meeting, but never come to fruition. I'd like to see a general proposal which we could apply consistently across all of the commands.

**Comment by apelisse** [comment]
> Yeah, the topic of different return code, based on the errors is something that was brought in the past during sig-cli meeting, but never come to fruition. I'd like to see a general proposal which we could apply consistently across all of the commands.

Absolutely agree. I'd be happy to help with such a proposal, but don't have the energy/time to initiate one myself. Thanks Maciej!

**Comment by cypherfox** [comment]
The consistent return code proposal is beyond my available time ATM.

/close

**Pull request closed without merging**
