### PR TITLE
Revert #13052

### PR DESCRIPTION
**Pull request by wojtek-t**
Reason:
It seems that #13052 completely broke pod startup time latency (our scalability tests are just logging it, so I didn't catch it before - I will extend tests today to check it). Before the 99th percentile of pod statup time was less than 5 seconds, after this PR it usually exceeds 30 seconds.
I reverted it locally and it seems to help, so I'm going to revert this PR.

cc @smarterclayton @pmorie

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
To give more context: @wojtek-t was not able to simply revert this #13052 as it was too old already (there were some changes on top of this). I checked that this looks like a revert and a manual change in ```test/e2e/downwardapi_volume.go```.

LGTM

**Comment by fgrzadkowski** [comment]
Close/Open to re-run the tests

**Comment by wojtek-t** [comment]
@smarterclayton @pmorie 
Just to confirm - reverting it fixed the problem (although I didn't have time to understand what exactly the problem was).
I also created a PR to test that in our scalability test, so that we will be able to discover such problems faster - #13665

**Comment by smarterclayton** [comment]
It's possible the new call to inspect container resulted in severe lag, or there's some other change.  I wouldn't expect it to be this drastic though (5s -> 30s)

**Comment by wojtek-t** [comment]
Yes - I was also surprised but the numbers that I've seen is (for 99th percentile of pod startup time)
- 3-5 seconds before this change (was submitted)
- 25-40 seconds after this change
To be honest - I didn't try to understand why it was happening.

**Comment by pmorie** [comment]
@smarterclayton @wojtek-t For the record, there is no new call to `InspectContainer` in the named PR.  I will try to reproduce.

**Pull request merged**
