### PR TITLE
container-vm is deprecated, so don't use it for GCE test clusters

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: container-vm is deprecated. We shouldn't start test clusters using it for nodes.

**Release note**:

```release-note
NONE
```

x-ref #48279 which started this work

### CODE REVIEW

**Comment by abgworrall** [comment]
100% aligned with the intent, but doesn't 'the `NODE_OS_DISTRIBUTION` change in #52120 achieve this (cf. https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/util.sh#L63) ? Or did I get muddled with all these layers of ENV vars ?

FWIW, I'd thought the reason that change didn't affect all that many testjobs is because most of them hard-specify `KUBE_NODE_OS_DISTRIBUTION=debian`.

**Comment by krzyzacy** [comment]
Do we still care about cvm pre-1.8? Maybe someone from node team can clean up the suites we don't care anymore? Or let me know I can wipe them out?

**Comment by abgworrall** [comment]
I'd like to clean CVM usage out of master and 1.8, before thinking about 1.7 and earlier; there are still some users on CVM on older branches, even though they should be moving off.

But yeah, we should clean up *all* the branches at some point kinda soon.

**Comment by ixdy** [comment]
I think this PR has basically no effect after #52120 (I'd started working on this change before that went in, then forgot to follow up). It's basically little more than a documentation change at this point.

**Comment by ixdy** [comment]
(also, I'm not trying to remove CVM yet, just make sure we don't use it by default anywhere.)

**Comment by krzyzacy** [comment]
@abgworrall I guess I'll wipe out those master jobs tomorrow

**Comment by ixdy** [comment]
@krzyzacy I believe v1.7.5 is the last version that supports cvm.

**Comment by ixdy** [comment]
can an owner please `/approve no-issue`? apparently I can't do that.

**Comment by ixdy** [comment]
(I just linked to @abgworrall's previous PR on this. Thankfully the bot doesn't understand the difference between issues and PRs.)

**Pull request merged**
