### PR TITLE
init aliyun cloud provider for loadbalancer

### PR DESCRIPTION
**Pull request by keontang**
Support for aliyun cloud provider:
1. aliyun loadbalancer
2. aliyun volume  // doing, will push it later

For aliyun loadbalancer test case:

```
[root@master-1 ~]# cat nginx-rc.yaml 
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 2
  # selector identifies the set of Pods that this
  # replication controller is responsible for managing
  selector:
    app: nginx
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        # The api server enforces this constraint.
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.1
        ports:
        - containerPort: 80


[root@master-1 ~]# cat nginx-svc.yaml 
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - port: 8000 # the port that this service should serve on
    # the container on each pod to connect to, can be a name
    # (e.g. 'www') or a number (e.g. 80)
    targetPort: 80
    protocol: TCP
  # just like the selector in the replication controller,
  # but this time it identifies the set of pods to load balance
  # traffic to.
  selector:
    app: nginx
  type: LoadBalancer

```

aliyun-provider-1

aliyun-provider-2

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30760)

### CODE REVIEW

**Comment by keontang** [comment]
cloud-config file template:
```
{
    "global": {
     "accessKeyID": "{{ access_key_id }}",
     "accessKeySecret": "{{ access_key_secret }}",
     "regionID": "{{ region_id }}"
   }
 } 
```

**Comment by keontang** [comment]
```
[root@master-1 ~]# kubectl describe service nginx-service
Name:           nginx-service
Namespace:      default
Labels:         <none>
Selector:       app=nginx
Type:           LoadBalancer
IP:         10.254.125.154
LoadBalancer Ingress:   115.28.252.163
Port:           <unset> 8000/TCP
NodePort:       <unset> 32728/TCP
Endpoints:      192.168.65.10:80,192.168.66.6:80
Session Affinity:   None
Events:
  FirstSeen LastSeen    Count   From            SubobjectPath   Type        Reason          Message
  --------- --------    -----   ----            -------------   --------    ------          -------
  10m       10m     1   {service-controller }           Normal      CreatingLoadBalancer    Creating load balancer
  10m       10m     1   {service-controller }           Normal      CreatedLoadBalancer Created load balancer
```

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by spacexnice** [comment]
will this PR be merged ? @keontang @mikedanese

**Comment by spacexnice** [comment]
Does anyone still working on this ?

**Comment by mikedanese** [comment]
I'd like to wait for https://github.com/kubernetes/features/issues/88 to be finalized before accepting new cloud providers

**Comment by mikedanese** [comment]
This should be developed in an external cloud-provider controller, see kubernetes/features#88

**Pull request closed without merging**
