### PR TITLE
update the image of nfs-provisioner in external-storage

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
https://github.com/kubernetes-incubator/external-storage/tree/master/nfs
in external-storage that the nfs-provisioner the image is v1.0.8
quay.io/kubernetes_incubator/nfs-provisioner:v1.0.8
so change it,thanks!
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jianglingxia** [comment]
/assign @gnufied
thanks

**Comment by msau42** [comment]
@jianglingxia can you run this test on your private cluster to make sure it passes with the new provisioner?

**Comment by wongma7** [comment]
/lgtm

Though I would prefer we merged https://github.com/kubernetes/kubernetes/pull/44925

**Pull request closed without merging**
