### PR TITLE
[kubeadm/app/cmd]switch to github.com/pkg/errors

### PR DESCRIPTION
**Pull request by yuexiao-wang**
Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
switch to github.com/pkg/errors 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # https://github.com/kubernetes/kubeadm/issues/1183

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yuexiao-wang** [comment]
@fabriziopandini  @neolit123  PTAL

**Comment by yuexiao-wang** [comment]
I have done the packages as follows:
cmd/kubeadm/app/cmd/
cmd/kubeadm/app/cmd/phases

**Comment by yuexiao-wang** [comment]
@fabriziopandini @neolit123 PTAL

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve 

thank you for doing this!

**Comment by timothysc** [comment]
@yuexiao-wang you will likely need to run ./hack/update-bazel.sh

**Comment by neolit123** [comment]
also the PR needs a re-base as the code has changed.
@yuexiao-wang let me know if you need any help with git workflow commands or k8s ./hack commands.

thanks.

**Comment by neolit123** [comment]
/lgtm cancel

to stop the bot auto-test until the conflicts are resolved.

**Comment by yuexiao-wang** [comment]
sorry, I forgot to run update-bazel.sh  after modify codes.
now BUILD has merged for github.com/pkg/errors in master.
conflicts are resolved after I rebase my PR.

**Pull request merged**
