### PR TITLE
[WIP] Refactor few e2e tests and incorporate them into automated upgrade testing

### PR DESCRIPTION
**Pull request by shashidharatd**
**What this PR does / why we need it**: Add few more test cases to automated upgrade testing

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
This PR is for refactoring few selected test case to reuse them in upgrade testing. here is the issue #35078 for reference on the discussion.
This PR needs to be tested on upgrade test projects before merge.

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by shashidharatd** [comment]
@k8s-bot kubemark e2e test this

**Comment by shashidharatd** [comment]
@k8s-bot kubemark e2e test this

**Comment by shashidharatd** [comment]
cc @quinton-hoole @csbell

**Comment by krousey** [comment]
@shashidharatd This is awesome. I'm afraid we duplicated some effort though. I adapted the chaos monkey interface to something explicitly about upgrades here https://github.com/kubernetes/kubernetes/pull/40325

This already has the services test. I'm adding a secrets test here https://github.com/kubernetes/kubernetes/pull/40747. @kargakis is adding a deployment test here https://github.com/kubernetes/kubernetes/pull/40854.

Would you be willing to convert your work for config maps, daemonsets, and jobs to this framework? I would gladly review it.

**Comment by shashidharatd** [comment]
not an issue @krousey. I would be happy to work on it, but i am little busy for couple of days. Feel free to go ahead with other upgrade tests, if you feel i am blocking the work.

**Comment by skriss** [comment]
Can I pitch in here? I could work on adapting the test cases that @shashidharatd wrote for the 3 areas named above to the new chaos monkey interface from @krousey . I'm playing Automated Upgrade Test Lead for the 1.6 release so interested in getting intimately familiar with this stuff :)

**Comment by shashidharatd** [comment]
@skriss, thanks a lot for pitching in. please feel free to reuse anything you feel appropriate. I am busy doing few other things and don't mind at all. Basically i do not want to block any great work happening towards automating upgrade testing.

**Comment by shashidharatd** [comment]
Closing this pr as this is not required anymore.

**Pull request closed without merging**
