### PR TITLE
test coverage for pod BestEffort

### PR DESCRIPTION
**Pull request by pontiyaraja**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> 
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:This PR to cover test case for pod QOS BestEffort scenario.

**Which issue(s) this PR fixes**:It a part of an umbrella issue #75935

Fixes #a part of #75935

**Special notes for your reviewer**:
    If requests and limits are not set for all of the resources, across all containers, then the pod is classified as Best-Effort.
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/area testing
/area node
/area conformance
@kubernetes/sig-node-pr-reviews

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
Thanks for your pr @pontiyaraja !

To start, could you share with me a little more about why we are writing a e2e test to verify this behavior, instead of a unit test?

If I'm reading this correctly, it appears that we are just creating the pod and then expecting it to have the proper `pod.Status.QOSClass`. It seems like we could verify that via a unit test, which would be much quicker to execute and have less chance of flake.

If we do decide this functionality could be tested via unit tests, maybe we could move the `PodQOSGuaranteed` test which already exists to a unit test as well?

Looking forward to chatting more about this :)

**Comment by pontiyaraja** [comment]
@mattjmcnaughton there are few unit tests are there for this, but its not covering the end-to-end functionality like pod creation and updating the pod status QOSClass. Its just comparing the pod resources from the pod and returning the QOSClass based on the resources requested by pod. Please refer the below links
https://github.com/kubernetes/kubernetes/blob/9c2df998af9eb565f11d42725dc77e9266483ffc/pkg/apis/core/v1/helper/qos/qos_test.go#L30

https://github.com/kubernetes/kubernetes/blob/9c2df998af9eb565f11d42725dc77e9266483ffc/pkg/apis/core/v1/helper/qos/qos.go#L39

https://github.com/kubernetes/kubernetes/blob/9c2df998af9eb565f11d42725dc77e9266483ffc/pkg/registry/core/pod/strategy_test.go#L193

https://github.com/kubernetes/kubernetes/blob/9c2df998af9eb565f11d42725dc77e9266483ffc/pkg/registry/core/pod/strategy.go#L69

**Comment by mkumatag** [comment]
> If I'm reading this correctly, it appears that we are just creating the pod and then expecting it to have the proper `pod.Status.QOSClass`. It seems like we could verify that via a unit test, which would be much quicker to execute and have less chance of flake.

+1, if `GetPodQOS` is the one used to get the `pod.Status.QOSClass` then I feel unit test coverage is good enough to avoid further delay in e2e tests.

**Comment by pontiyaraja** [comment]
> > If I'm reading this correctly, it appears that we are just creating the pod and then expecting it to have the proper `pod.Status.QOSClass`. It seems like we could verify that via a unit test, which would be much quicker to execute and have less chance of flake.
> 
> +1, if `GetPodQOS` is the one used to get the `pod.Status.QOSClass` then I feel unit test coverage is good enough to avoid further delay in e2e tests.

Written e2e to deploy a pod in cluster with resources and update the pod QOSClass by kubelet. 

Not deploying a pod and kubelet not updating the pod QOSClass in unit test, it's just getting the QOSClass for pod, based on the pod object. It's just covering a unit of the end to end functionality.

**Comment by mattjmcnaughton** [comment]
Thanks for the links @pontiyaraja :)

While I agree that its useful to have one e2e test of the whole e2e flow (i.e. create pod with resources and check that QOSclass is assigned), I don't think that we need a separate e2e test for each different QOSclass, as we can cover the actual calculation of the class with the unit tests. In my mind, the e2e tests give us confidence that the kubelet will assign a QOSclass and the unit tests give us confidence that the class will be the correct one. What do you think? :)

**Comment by mgdevstack** [comment]
@pontiyaraja, this issue should be closed, as another more specific issue #76128 is open.
>While I agree that its useful to have one e2e test of the whole e2e flow (i.e. create pod with resources and check that QOSclass is assigned), I don't think that we need a separate e2e test for each different QOSclass, as we can cover the actual calculation of the class with the unit tests. In my mind, the e2e tests give us confidence that the kubelet will assign a QOSclass and the unit tests give us confidence that the class will be the correct one. What do you think? :)

+1,  @mattjmcnaughton, What is your view on this https://github.com/kubernetes/kubernetes/issues/75935#issuecomment-493030622 supporting your comment.

**Comment by spiffxp** [comment]
/close
closing this based on the feedback above, please /reopen if you think this is incorrect

**Pull request closed without merging**
