### PR TITLE
fix kubectl flushlogs not working together with exit

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
kubectl flushlogs not working together with exit

#### Which issue(s) this PR fixes:

Fixes #https://github.com/kubernetes/kubernetes/issues/102231

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by sanposhiho — COMMENTED** [review]
Thanks for helping the issue!
Also, in this PR, please check the below point. 

https://github.com/kubernetes/kubernetes/pull/104775#discussion_r704792673

**Comment by sanposhiho** [comment]
@kerthcet 

It's a little tough, but you also have to check subcommand. 

Subcommands are registered on this point.
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/cmd.go#L299-L371

For example, `kubectl create` do os.Exit in cmdutil.CheckErr when some error.
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/create/create.go#L116-L118

**Comment by kerthcet** [comment]
> @kerthcet
> 
> It's a little tough, but you also have to check subcommand.
> 
> Subcommands are registered on this point.
> https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/cmd.go#L299-L371
> 
> For example, `kubectl create` do os.Exit in cmdutil.CheckErr when some error.
> https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/create/create.go#L116-L118

gotcha. working on it this week.

**Review by sanposhiho — COMMENTED** [review]
plz check this for this pr too 🙏 
https://github.com/kubernetes/kubernetes/pull/104776#discussion_r716367629

**Comment by dougsland** [comment]
@kerthcet watching https://github.com/kubernetes/kubernetes/pull/104776#discussion_r716367629

**Pull request closed without merging**
