### PR TITLE
Add 1.22.0 compatibility data

### PR DESCRIPTION
**Pull request by pacoxu**
Adds API compatibility data for 1.22 following https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/api/testdata#populating-data-for-each-release

like #101243
/kind cleanup
/sig architecture
/priority important-longterm
/triage accepted

```release-note
NONE
```

### CODE REVIEW

**Comment by pacoxu** [comment]
I cannot update the `round-trip back` testdata. 
```
 UPDATE_COMPATIBILITY_FIXTURE_DATA=true go test k8s.io/api -run //v1.22.0
or
 UPDATE_COMPATIBILITY_FIXTURE_DATA=true go test k8s.io/api -run //HEAD
```

/cc liggitt

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/104270 was open for this, apologies for the collision

**Comment by liggitt** [comment]
let me review tomorrow when I'm at a computer, happy for either to merge

**Comment by pacoxu** [comment]
Not see that PR, 😄

**Comment by pacoxu** [comment]
The PR is the same without `after_roundtrip` testdata. Is that expected? 
```
These after_roundtrip files are generated by running the failing round-trip tests with UPDATE_COMPATIBILITY_FIXTURE_DATA=true set.
```
Or that means there are no compatible changes yet.

**Comment by liggitt** [comment]
That means that code at HEAD has not modified any APIs since 1.22.0 was released, which is good, and and is expected (it would be required if this had been done on the day of the 1.22.0 release, but it's possible a change since then could have introduced an additive round trip change)

**Pull request closed without merging**
