### PR TITLE
storage: pass fieldRefs to flexstorage volume plugin

### PR DESCRIPTION
**Pull request by kayrus**
This pull request implements passing pod info into the FlexVolume plugin. This PR is useful when you use petsets and pod (which was generated by petst) info should be passed to the flexvolue plugin to determine which pod of the petset asked for the storage.

Example usage:

``` yaml
        - name: petset-ssh-volume
          flexVolume:
            driver: "my/sshfs"
            optionsItems:
              - name: podName
                fieldRef:
                  fieldPath: metadata.name
            secretRef:
              name: "my-secret"
```

kubelet should execute `my/sshfs` binary with the following json in arguments:

``` sh
attach {"kubernetes.io/fsType":"","kubernetes.io/item/podName":"mypod-0","kubernetes.io/readwrite":"rw","kubernetes.io/secret/my-secret":"%data%"}
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30694)

### CODE REVIEW

**Comment by lavalamp** [comment]
ok to test

I would expect some sort of testing for the volume changes?

---

Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/api/types.go, line 553 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694#-KPK0ktjIHbPwmS42Tnz:-KPK0ktjIHbPwmS42To-:b1lrn00) ([raw file](https://github.com/kubernetes/kubernetes/blob/2d232f46fe2ce1573721b7983c23ede43394e3a0/pkg/api/types.go#L553)):*
> ```Go
> 	// Optional: Extra driver options if any.
> 	Options map[string]string `json:"options,omitempty"`
> 	// Optional: Items is a list of pod fields
> ```

What is it for, when should users set it?

---

*[pkg/api/types.go, line 559 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694#-KPK0uBGAXpcgvmJfgIe:-KPK0uBGAXpcgvmJfgIf:bq7520s) ([raw file](https://github.com/kubernetes/kubernetes/blob/2d232f46fe2ce1573721b7983c23ede43394e3a0/pkg/api/types.go#L559)):*
> ```Go
> // FlexVolumeOptionsItem represents information to create an option containing the pod field
> type FlexVolumeOptionsItem struct {
> 	// Required: Name is  the relative name of the option field.
> ```

s/is  the/is the/

what does "relative" mean in this context?

---

*[pkg/api/types.go, line 561 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694#-KPK5Yf2-ldUMKNvHz2Q:-KPK5Yf2-ldUMKNvHz2R:bkyt7t3) ([raw file](https://github.com/kubernetes/kubernetes/blob/2d232f46fe2ce1573721b7983c23ede43394e3a0/pkg/api/types.go#L561)):*
> ```Go
> 	// Required: Name is  the relative name of the option field.
> 	Name string `json:"name"`
> 	// Selects a field of the pod: only annotations, labels, name and namespace are supported.
> ```

I don't see anything that enforces this. Is it true?

---

*[pkg/volume/flexvolume/flexvolume.go, line 201 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694#-KPK2aVyanHK816ASvYJ:-KPK2aVyanHK816ASvYK:b84lfrd) ([raw file](https://github.com/kubernetes/kubernetes/blob/2d232f46fe2ce1573721b7983c23ede43394e3a0/pkg/volume/flexvolume/flexvolume.go#L201)):*
> ```Go
> // flexVolume is the disk resource provided by this plugin.
> type flexVolumeDisk struct {
> 	pod *api.Pod
> ```

it doesn't matter and likely won't as long as the list of supported fields doesn't change. But technically you should use the external version of the pod here. A comment may suffice for the moment.

Actually, since the field path thing looks general, unless you actually write code to restrict what they can ask for, this should really be a v1.Pod.

---

*[pkg/volume/flexvolume/flexvolume.go, line 461 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694#-KPK5LBf0FLBxbwb-Dyy:-KPK5LBf0FLBxbwb-Dyz:b-ix2uii) ([raw file](https://github.com/kubernetes/kubernetes/blob/2d232f46fe2ce1573721b7983c23ede43394e3a0/pkg/volume/flexvolume/flexvolume.go#L461)):*
> ```Go
> // Map's key is the requested name of file to dump
> // Map's value is the (sorted) content of the field.
> func (f *flexVolumeMounter) collectData() (map[string]string, error) {
> ```

collectData is a really unhelpful name. What kind of data? What does collecting involve?

---

*[pkg/volume/flexvolume/flexvolume.go, line 480 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694#-KPK3TTiThqf9eri6MVE:-KPK3TTiThqf9eri6MVF:b-lrzqrn) ([raw file](https://github.com/kubernetes/kubernetes/blob/2d232f46fe2ce1573721b7983c23ede43394e3a0/pkg/volume/flexvolume/flexvolume.go#L480)):*
> ```Go
> // (annotations and labels)
> func sortLines(values string) string {
> 	splitted := strings.Split(values, "\n")
> ```

nit: just "split" is more standard english :)

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694#-:-KPK0e-g9FnFnpRYc0rw:bgwc1hi)*

**Comment by kayrus** [comment]
Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/api/types.go, line 553 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694#-KPK0ktjIHbPwmS42Tnz:-KPLx2daPr-4gVeZD4Sd:b-k13xdq) ([raw file](https://github.com/kubernetes/kubernetes/blob/2d232f46fe2ce1573721b7983c23ede43394e3a0/pkg/api/types.go#L553)):*
<details><summary><i>Previously, lavalamp (Daniel Smith) wrote…</i></summary>
> What is it for, when should users set it?
</details>
Shall I put an answer in comment? Or just here? My pull request already has the info. It is useful for petsets, when pod name is being created automatically and you have to use this info in flexvolume.

---

*[pkg/api/types.go, line 559 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694#-KPK0uBGAXpcgvmJfgIe:-KPLxQIsomkwW7oF3fEs:b-gdiymq) ([raw file](https://github.com/kubernetes/kubernetes/blob/2d232f46fe2ce1573721b7983c23ede43394e3a0/pkg/api/types.go#L559)):*
<details><summary><i>Previously, lavalamp (Daniel Smith) wrote…</i></summary>
> s/is  the/is the/
> 
> what does "relative" mean in this context?
</details>
Copy-pasted from the downward plugin. Will remove `relative`.

---

*[pkg/api/types.go, line 561 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694#-KPK5Yf2-ldUMKNvHz2Q:-KPLxsnKU_hUHgRxfFdr:bc2wx18) ([raw file](https://github.com/kubernetes/kubernetes/blob/2d232f46fe2ce1573721b7983c23ede43394e3a0/pkg/api/types.go#L561)):*
<details><summary><i>Previously, lavalamp (Daniel Smith) wrote…</i></summary>
> I don't see anything that enforces this. Is it true?
</details>
Yes, it is true. https://github.com/kubernetes/kubernetes/blob/d57408294e50d617ed60e8fd7b833783823194b6/pkg/fieldpath/fieldpath.go#L48..L66

---

*[pkg/volume/flexvolume/flexvolume.go, line 201 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694#-KPK2aVyanHK816ASvYJ:-KPLwZMfTC3MaJ9pHPJI:bw6is0) ([raw file](https://github.com/kubernetes/kubernetes/blob/2d232f46fe2ce1573721b7983c23ede43394e3a0/pkg/volume/flexvolume/flexvolume.go#L201)):*
<details><summary><i>Previously, lavalamp (Daniel Smith) wrote…</i></summary>
> it doesn't matter and likely won't as long as the list of supported fields doesn't change. But technically you should use the external version of the pod here. A comment may suffice for the moment.
> 
> Actually, since the field path thing looks general, unless you actually write code to restrict what they can ask for, this should really be a v1.Pod.
</details>
I used downward plugin as an entry point. And it was created this way. Also other volume plugins use `pod     *api.Pod`. What shall I do?

---

*[pkg/volume/flexvolume/flexvolume.go, line 461 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694#-KPK5LBf0FLBxbwb-Dyy:-KPM0Jj5NUEfSLQD711s:b-6icvrc) ([raw file](https://github.com/kubernetes/kubernetes/blob/2d232f46fe2ce1573721b7983c23ede43394e3a0/pkg/volume/flexvolume/flexvolume.go#L461)):*
<details><summary><i>Previously, lavalamp (Daniel Smith) wrote…</i></summary>
> collectData is a really unhelpful name. What kind of data? What does collecting involve?
</details>
Replaced with the `getPodFields`.

---

*[pkg/volume/flexvolume/flexvolume.go, line 480 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694#-KPK3TTiThqf9eri6MVE:-KPM0NFCnnlp7BlLS02V:b-2nproe) ([raw file](https://github.com/kubernetes/kubernetes/blob/2d232f46fe2ce1573721b7983c23ede43394e3a0/pkg/volume/flexvolume/flexvolume.go#L480)):*
<details><summary><i>Previously, lavalamp (Daniel Smith) wrote…</i></summary>
> nit: just "split" is more standard english :)
</details>
done. and also fixed in `downwardapi`.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694)*

**Comment by kayrus** [comment]
@lavalamp fixed. btw, do I need to regenerate all these **generated** files every commit? they add problems while rebase.

P.S. don't like this reviewable experiment.

**Comment by lavalamp** [comment]
I keep the generated files in their own commit and just blow them away and remake when I rebase.

I'm still evaluating reviewable myself.

I actually don't even know what "flexvolume" is and your question is making me wonder if I should be asking what this feature is and if it makes sense for it to be on a "flexvolume". This sort of functionality definitely doesn't make sense in general for volumes.

---

Reviewed 2 of 10 files at r1, 4 of 9 files at r2, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/api/types.go, line 553 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694#-KPK0ktjIHbPwmS42Tnz:-KPPXWpzsHXmPWfDQCvJ:b-6yrykk) ([raw file](https://github.com/kubernetes/kubernetes/blob/2d232f46fe2ce1573721b7983c23ede43394e3a0/pkg/api/types.go#L553)):*
<details><summary><i>Previously, kayrus (kayrus) wrote…</i></summary>
> Shall I put an answer in comment? Or just here? My pull request already has the info. It is useful for petsets, when pod name is being created automatically and you have to use this info in flexvolume.
</details>
Sorry for being unclear; these comments (or the ones on the v1 types.go file, actually) get sucked into our documentation. So I'm asking for the comment to be made very helpful and clear.

---

*[pkg/volume/flexvolume/flexvolume.go, line 201 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694#-KPK2aVyanHK816ASvYJ:-KPPY-LsrrcviqYRVJJ7:bgsltsz) ([raw file](https://github.com/kubernetes/kubernetes/blob/2d232f46fe2ce1573721b7983c23ede43394e3a0/pkg/volume/flexvolume/flexvolume.go#L201)):*
<details><summary><i>Previously, kayrus (kayrus) wrote…</i></summary>
> I used downward plugin as an entry point. And it was created this way. Also other volume plugins use `pod     *api.Pod`. What shall I do?
</details>
A TODO / warning that this will be wrong as soon as the field path is made more general is sufficient.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694#-:-KPPYBw1grZ71tGeaNwZ:bmrglav)*

**Comment by kayrus** [comment]
> This sort of functionality definitely doesn't make sense in general for volumes.

Let's imagine we have a petset. And also we have volumes. For example they are distributes across the cluster. What if you want to pin each pet to specific volume? I.e.

* pet-0 should use  volume called pet-vol-0.
* pet-1 should use  volume called pet-vol-1.
* pet-2 should use  volume called pet-vol-2.

Right now it is not possible even with labels. Because you can not define labels according to pet index. And here comes flexvolume, which can process extra options (in our case generated podname with an index).

I also created an issue explaining what I'd like to achieve in the future. https://github.com/kubernetes/kubernetes/issues/30755

Please let me know if you still have questions.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/volume/flexvolume/flexvolume.go, line 201 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694#-KPK2aVyanHK816ASvYJ:-KPRZ-upDMTT4SjVeCSn:b3e24dm) ([raw file](https://github.com/kubernetes/kubernetes/blob/2d232f46fe2ce1573721b7983c23ede43394e3a0/pkg/volume/flexvolume/flexvolume.go#L201)):*
> A TODO / warning that this will be wrong as soon as the field path is made more general is sufficient.
copy-pasted your comment into the code

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30694#-:-KPRXT4gyAex9--tg0jg:b8zlhix)*

**Comment by lavalamp** [comment]
OK, I'm going to hand this off to Prashanth. :)

**Pull request closed without merging**
