### PR TITLE
Make selectors atomic

### LINKED ISSUE #97970: Server Side Apply - Selectors are not atomic
While closing the https://github.com/kubernetes/kubernetes/issues/92913 fixed a problem for structured selectors across `k/k` api, there is still a great deal of unstructured selectors across different resources as a `map[string]string`. So a similar problem is present - SSA does not work for modifying these when a multiple source-of-truths attempting to manage this field in parallel. 

Say a user and a controller is doing changes to the resource.selector field. If a user changes (appends) a key: value to the map, he completely alters the behavior for the resource, and the controller can't do anything with it, as SSO treats the map as `granular` resource by default, so you have to fall back to a usual `get/compare/update` for changes like that, or you can't guarantee the declarative behavior for your controller, which is supposed to set and maintain the fields it cares about as it expects it to see.

**What happened**:
Here is a resource:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
spec:
  ports:
...
  selector:
    test: test
```
1) User uses `kubectl apply --server-side -f svc.yaml`, the resource is applied.
2) A controller for this resource reconciles its changes, and applies a patch with
```yaml
apiVersion: v1
kind: Service
...
  selector:
    my: app
```
3) The resource contains both values in `spec.selector` map and fails to do the job with existing infrastructure, as the selector does not match any of the resource labels.
```yaml
...
  selector:
    my: app
    test: test
```

**What you expected to happen**:

Step 2 applies a selector as an atomic value, so the resource in step 3 looks more like
```yaml
...
  selector:
    my: app
```

**How to reproduce it (as minimally and precisely as possible)**:

See **what happend** section

A followup to https://github.com/kubernetes/kubernetes/issues/92913

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20
- Cloud provider or hardware configuration: does not matter

### PR DESCRIPTION
**Pull request by Danil-Grigorev**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Ensure that all label selectors are treated as atomic values, to exclude situations when selectors are being corrupted by different actors attempting to apply their overlapping definition for this field with server-side-apply.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/97970

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Server Side Apply now treats all <Some>Selector fields as atomic (meaning the entire selector is managed by a single writer and updated together), since they contain interrelated and inseparable fields that do not merge in intuitive ways.
```

/sig api-machinery
/wg api-expression

### CODE REVIEW

**Comment by apelisse** [comment]
@jpbetz Can you think of a good way to test whether this is going to break?

**Comment by Danil-Grigorev** [comment]
@jpbetz @apelisse I added some tests covering the change. I also observed a couple of left-overs still needed to be fixed with defaulted `protocol` field - https://github.com/kubernetes/kubernetes/pull/97989/files#diff-364a0d27e9a9e7a6f1d2e26ca7509443be3ef59461db6125f982e6c1f19fa2c2R613. Also, so far it is not possible to test `ReplicationController` apply where the changes were also made, as it seems it does not genereate openapi schema.

**Comment by jpbetz** [comment]
> Joe Betz Can you think of a good way to test whether this is going to break?

The underlying mechanism was tested in https://github.com/kubernetes-sigs/structured-merge-diff/pull/170 so I'd expect tests of the specific cases, like @Danil-Grigorev has added, to be sufficient for this PR.

**Comment by jpbetz** [comment]
I've reviewed the tests. The approach of checking that adding a field of to the selector results in a conflict looks right to me.

Use of `+mapType=atomic` also looks right.

/lgtm

**Comment by Danil-Grigorev** [comment]
Just realized I committed unwanted tests. PTAL again :smile:

**Comment by Danil-Grigorev** [comment]
@jpbetz @apelisse @kwiesmueller Tests are passing - please review.

**Comment by cbandy** [comment]
It might be valuable to include a test that sets `ServiceSpec.Selector` to empty or nil.

https://docs.k8s.io/concepts/services-networking/service/#services-without-selectors

**Comment by liggitt** [comment]
sweeping use of map[string]string in other places in the API, the following fields look like ones writers would expect to have replaced, not merged:

```diff
diff --git a/staging/src/k8s.io/api/core/v1/types.go b/staging/src/k8s.io/api/core/v1/types.go
index 88776c98fc4..c622bc977ce 100644
--- a/staging/src/k8s.io/api/core/v1/types.go
+++ b/staging/src/k8s.io/api/core/v1/types.go
@@ -1019,6 +1019,7 @@ type FlexPersistentVolumeSource struct {
 	ReadOnly bool `json:"readOnly,omitempty" protobuf:"varint,4,opt,name=readOnly"`
 	// Optional: Extra command options if any.
 	// +optional
+	// +mapType=atomic
 	Options map[string]string `json:"options,omitempty" protobuf:"bytes,5,rep,name=options"`
 }
 
@@ -1045,6 +1046,7 @@ type FlexVolumeSource struct {
 	ReadOnly bool `json:"readOnly,omitempty" protobuf:"varint,4,opt,name=readOnly"`
 	// Optional: Extra command options if any.
 	// +optional
+	// +mapType=atomic
 	Options map[string]string `json:"options,omitempty" protobuf:"bytes,5,rep,name=options"`
 }
 
@@ -1706,6 +1708,7 @@ type CSIPersistentVolumeSource struct {
 
 	// Attributes of the volume to publish.
 	// +optional
+	// +mapType=atomic
 	VolumeAttributes map[string]string `json:"volumeAttributes,omitempty" protobuf:"bytes,5,rep,name=volumeAttributes"`
 
 	// ControllerPublishSecretRef is a reference to the secret object containing
@@ -1762,6 +1765,7 @@ type CSIVolumeSource struct {
 	// VolumeAttributes stores driver-specific properties that are passed to the CSI
 	// driver. Consult your driver's documentation for supported values.
 	// +optional
+	// +mapType=atomic
 	VolumeAttributes map[string]string `json:"volumeAttributes,omitempty" protobuf:"bytes,4,rep,name=volumeAttributes"`
 
 	// NodePublishSecretRef is a reference to the secret object containing
diff --git a/staging/src/k8s.io/api/discovery/v1/types.go b/staging/src/k8s.io/api/discovery/v1/types.go
index fa990efdb73..fe680a0731c 100644
--- a/staging/src/k8s.io/api/discovery/v1/types.go
+++ b/staging/src/k8s.io/api/discovery/v1/types.go
@@ -96,6 +96,7 @@ type Endpoint struct {
 	// write to it will be silently ignored. Topology information can be found
 	// in the zone and nodeName fields instead.
 	// +optional
+	// +mapType=atomic
 	DeprecatedTopology map[string]string `json:"deprecatedTopology,omitempty" protobuf:"bytes,5,opt,name=deprecatedTopology"`
 
 	// nodeName represents the name of the Node hosting this endpoint. This can
diff --git a/staging/src/k8s.io/api/discovery/v1beta1/types.go b/staging/src/k8s.io/api/discovery/v1beta1/types.go
index 35b0be29a5b..3595b75d575 100644
--- a/staging/src/k8s.io/api/discovery/v1beta1/types.go
+++ b/staging/src/k8s.io/api/discovery/v1beta1/types.go
@@ -104,6 +104,7 @@ type Endpoint struct {
 	//   endpoint is located. This should match the corresponding node label.
 	// This field is deprecated and will be removed in future api versions.
 	// +optional
+	// +mapType=atomic
 	Topology map[string]string `json:"topology,omitempty" protobuf:"bytes,5,opt,name=topology"`
 	// nodeName represents the name of the Node hosting this endpoint. This can
 	// be used to determine endpoints local to a Node. This field can be enabled
diff --git a/staging/src/k8s.io/api/node/v1alpha1/types.go b/staging/src/k8s.io/api/node/v1alpha1/types.go
index 03e7e6f333b..58b84409f5f 100644
--- a/staging/src/k8s.io/api/node/v1alpha1/types.go
+++ b/staging/src/k8s.io/api/node/v1alpha1/types.go
@@ -91,6 +91,7 @@ type Scheduling struct {
 	// with a pod's existing nodeSelector. Any conflicts will cause the pod to
 	// be rejected in admission.
 	// +optional
+	// +mapType=atomic
 	NodeSelector map[string]string `json:"nodeSelector,omitempty" protobuf:"bytes,1,opt,name=nodeSelector"`
 
 	// tolerations are appended (excluding duplicates) to pods running with this
diff --git a/staging/src/k8s.io/api/node/v1beta1/types.go b/staging/src/k8s.io/api/node/v1beta1/types.go
index 89559949ca5..5c0421efcb2 100644
--- a/staging/src/k8s.io/api/node/v1beta1/types.go
+++ b/staging/src/k8s.io/api/node/v1beta1/types.go
@@ -83,6 +83,7 @@ type Scheduling struct {
 	// with a pod's existing nodeSelector. Any conflicts will cause the pod to
 	// be rejected in admission.
 	// +optional
+	// +mapType=atomic
 	NodeSelector map[string]string `json:"nodeSelector,omitempty" protobuf:"bytes,1,opt,name=nodeSelector"`
 
 	// tolerations are appended (excluding duplicates) to pods running with this
diff --git a/staging/src/k8s.io/api/storage/v1/types.go b/staging/src/k8s.io/api/storage/v1/types.go
index ba27fa36852..e2faff226c7 100644
--- a/staging/src/k8s.io/api/storage/v1/types.go
+++ b/staging/src/k8s.io/api/storage/v1/types.go
@@ -43,6 +43,7 @@ type StorageClass struct {
 	// Parameters holds the parameters for the provisioner that should
 	// create volumes of this storage class.
 	// +optional
+	// +mapType=atomic
 	Parameters map[string]string `json:"parameters,omitempty" protobuf:"bytes,3,rep,name=parameters"`
 
 	// Dynamically provisioned PersistentVolumes of this storage class are
@@ -189,6 +190,7 @@ type VolumeAttachmentStatus struct {
 	// This field must only be set by the entity completing the attach
 	// operation, i.e. the external-attacher.
 	// +optional
+	// +mapType=atomic
 	AttachmentMetadata map[string]string `json:"attachmentMetadata,omitempty" protobuf:"bytes,2,rep,name=attachmentMetadata"`
 
 	// The last error encountered during attach operation, if any.
diff --git a/staging/src/k8s.io/api/storage/v1alpha1/types.go b/staging/src/k8s.io/api/storage/v1alpha1/types.go
index afb0495db54..f5696faa806 100644
--- a/staging/src/k8s.io/api/storage/v1alpha1/types.go
+++ b/staging/src/k8s.io/api/storage/v1alpha1/types.go
@@ -114,6 +114,7 @@ type VolumeAttachmentStatus struct {
 	// This field must only be set by the entity completing the attach
 	// operation, i.e. the external-attacher.
 	// +optional
+	// +mapType=atomic
 	AttachmentMetadata map[string]string `json:"attachmentMetadata,omitempty" protobuf:"bytes,2,rep,name=attachmentMetadata"`
 
 	// The last error encountered during attach operation, if any.
diff --git a/staging/src/k8s.io/api/storage/v1beta1/types.go b/staging/src/k8s.io/api/storage/v1beta1/types.go
index 1a20de64ecb..dedfb62c1da 100644
--- a/staging/src/k8s.io/api/storage/v1beta1/types.go
+++ b/staging/src/k8s.io/api/storage/v1beta1/types.go
@@ -47,6 +47,7 @@ type StorageClass struct {
 	// Parameters holds the parameters for the provisioner that should
 	// create volumes of this storage class.
 	// +optional
+	// +mapType=atomic
 	Parameters map[string]string `json:"parameters,omitempty" protobuf:"bytes,3,rep,name=parameters"`
 
 	// Dynamically provisioned PersistentVolumes of this storage class are
@@ -202,6 +203,7 @@ type VolumeAttachmentStatus struct {
 	// This field must only be set by the entity completing the attach
 	// operation, i.e. the external-attacher.
 	// +optional
+	// +mapType=atomic
 	AttachmentMetadata map[string]string `json:"attachmentMetadata,omitempty" protobuf:"bytes,2,rep,name=attachmentMetadata"`
 
 	// The last error encountered during attach operation, if any.
diff --git a/staging/src/k8s.io/apimachinery/pkg/apis/testapigroup/v1/types.go b/staging/src/k8s.io/apimachinery/pkg/apis/testapigroup/v1/types.go
index b451c8136c7..6d400041cf8 100644
--- a/staging/src/k8s.io/apimachinery/pkg/apis/testapigroup/v1/types.go
+++ b/staging/src/k8s.io/apimachinery/pkg/apis/testapigroup/v1/types.go
@@ -133,6 +133,7 @@ type CarpSpec struct {
 	// Selector which must match a node's labels for the carp to be scheduled on that node.
 	// More info: http://kubernetes.io/docs/user-guide/node-selection/README
 	// +optional
+	// +mapType=atomic
 	NodeSelector map[string]string `json:"nodeSelector,omitempty" protobuf:"bytes,7,rep,name=nodeSelector"`
 
 	// ServiceAccountName is the name of the ServiceAccount to use to run this carp.
diff --git a/staging/src/k8s.io/apiserver/pkg/apis/example/types.go b/staging/src/k8s.io/apiserver/pkg/apis/example/types.go
index 2a2861cdb7f..cc1775381a0 100644
--- a/staging/src/k8s.io/apiserver/pkg/apis/example/types.go
+++ b/staging/src/k8s.io/apiserver/pkg/apis/example/types.go
@@ -101,6 +101,7 @@ type PodSpec struct {
 	ActiveDeadlineSeconds *int64
 	// NodeSelector is a selector which must be true for the pod to fit on a node
 	// +optional
+	// +mapType=atomic
 	NodeSelector map[string]string
 
 	// ServiceAccountName is the name of the ServiceAccount to use to run this pod
diff --git a/staging/src/k8s.io/apiserver/pkg/apis/example/v1/types.go b/staging/src/k8s.io/apiserver/pkg/apis/example/v1/types.go
index 111cf59be6a..7537090bc18 100644
--- a/staging/src/k8s.io/apiserver/pkg/apis/example/v1/types.go
+++ b/staging/src/k8s.io/apiserver/pkg/apis/example/v1/types.go
@@ -133,6 +133,7 @@ type PodSpec struct {
 	// Selector which must match a node's labels for the pod to be scheduled on that node.
 	// More info: http://kubernetes.io/docs/user-guide/node-selection/README
 	// +optional
+	// +mapType=atomic
 	NodeSelector map[string]string `json:"nodeSelector,omitempty" protobuf:"bytes,7,rep,name=nodeSelector"`
 
 	// ServiceAccountName is the name of the ServiceAccount to use to run this pod.
```

the two I'm unsure of are secret and configmap data/binaryData fields... I could see use cases either way...

**Comment by apelisse** [comment]
Pretty sure we want individual appliers to be able to own specific parts of a configmap/secret. Or am I misunderstanding?

**Comment by liggitt** [comment]
> Pretty sure we want individual appliers to be able to own specific parts of a configmap/secret. Or am I misunderstanding?

yeah, I could see scenarios where that's what we want, and scenarios where I just want to stomp the full content. I guess that means we have to leave it mergeable

**Comment by apelisse** [comment]
If you wanted to stomp everything, you could probably just update in that case?

**Comment by jpbetz** [comment]
I don't know if this was already covered. Here's a list of structs that need to be marked as atomic. I opened https://github.com/kubernetes/kubernetes/pull/100131 with a bunch of tag changes. It overlaps with this PR for some of the map type tags.

structs that need structType=atomic:
- corev1.NodeSelector (3 usages)
- corev1.TopologySelectorTerm (2 usages)
- corev1.ObjectFieldSelector (2 usages)
- corev1.ResourceFieldSelector (4 usages)
- corev1.ConfigMapKeySelector (1 usages)
- corev1.SecretKeySelector (1 usages)
- corev1.ScopeSelector (2 usages)

**Comment by Danil-Grigorev** [comment]
This PR only included common selectors which are user faced. Some of them were not covered, as I guess there was no generate tasks for those openapi types. The plan was to include those later. Let me have a look and update missing.

**Comment by Danil-Grigorev** [comment]
@jpbetz @liggitt Added other selectors of type map which should be atomic. Other api fields of same type are not required to be atomic, as they are similar in function to a map of labels or are part of example api packages. https://github.com/kubernetes/kubernetes/pull/100131 could take care of structured fields with similar properties.

**Comment by apelisse** [comment]
I'm pretty sure this is still lgtm, can we get the label re-applied?

**Comment by apelisse** [comment]
Maybe squash some of these commits together?

**Comment by Danil-Grigorev** [comment]
@apelisse squashed.

**Pull request merged**
