### PR TITLE
Remove deprecated 'se' resource alias

### PR DESCRIPTION
**Pull request by thockin**
@bgrant0607

### CODE REVIEW

**Comment by bgrant0607** [comment]
Used in an example:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/rethinkdb/README.md

**Comment by thockin** [comment]
DAMN.  I didn't search for " se$", just " se ".  Fixed now.  I still think
this is going to be OK.

**Comment by bgrant0607** [comment]
We'd also need to update gh-pages.

cc @brendandburns for an opinion.

**Comment by thockin** [comment]
I'll happily fix gh-pages if we commit this.  It's not a huge deal to keep,
of course

**Comment by bgrant0607** [comment]
My main concern is about breaking long-time users. The deprecation wasn't documented anywhere AFAIK.

**Comment by thockin** [comment]
It was announced on kubernetes-announce, if I recall, and the default search paths were flipped back in 0.19 I think.  The only breaks should be pods that are STILL alive since 0.18 and people who use the fully-qualified name and ignored the announcement.

**Comment by thockin** [comment]
responded on wrong thread, sorry :)

**Comment by thockin** [comment]
Yeah, this is getting rid of a shortcut that was (very quietly) documented in a few old examples.  I don't mind keeping it.  I like shortcuts.

**Comment by bgrant0607** [comment]
Ok, I'm fine with this. I did a Google search and only found copies of this one example, basically.

**Pull request merged**
