### PR TITLE
[1.12] WIP: Replace bitbucket with github to fix godep error

### PR DESCRIPTION
**Pull request by nikhita**
Related: https://github.com/kubernetes/kubernetes/pull/72138
1.13 version: https://github.com/kubernetes/kubernetes/pull/79501
This fixes `verify-godeps` for `release-1.12`: https://testgrid.k8s.io/sig-release-1.12-all#verify-1.12

Explanation on why this is needed: https://github.com/kubernetes/kubernetes/pull/79501

This commit has the following changes:

- Replace `bitbucket.org/ww/goautoneg` with `github.com/munnerz/goautoneg`.
- Replace `bitbucket.org/bertimus9/systemstat` with `github.com/nikhita/systemstat`.
- Bump kube-openapi  so that it's dependency on `bitbucket.org/ww/goautoneg`
moves to `github.com/munnerz/goautoneg`.
- This also drags in `k8s.io/klog`.
- Update `BUILD` files.

/kind failing-test
/assign @liggitt
/cc @liggitt @dims @sttts @cblecker @hoegaarden @feiskyer @munnerz 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
This fails with:

```
_output/bin/openapi-gen flag redefined: log_dir
panic: _output/bin/openapi-gen flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc420098060, 0x9c1ba0, 0xc89c70, 0x93a4df, 0x7, 0x977656, 0x2f)
    /usr/local/go/src/flag/flag.go:810 +0x540
flag.(*FlagSet).StringVar(0xc420098060, 0xc89c70, 0x93a4df, 0x7, 0x0, 0x0, 0x977656, 0x2f)
    /usr/local/go/src/flag/flag.go:713 +0x8b
k8s.io/kubernetes/vendor/k8s.io/klog.InitFlags(0xc420098060)
    /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/klog.go:411 +0x7b
main.main()
    /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-openapi/cmd/openapi-gen/openapi-gen.go:36 +0x3f

diff: _output/violations.report: No such file or directory make[2]: *** [pkg/generated/openapi/zz_generated.openapi.go] Error 1 make[1]: *** [generated_files] Error 2
```

because the bump to kube-openapi drags in klog changes. :(

**Comment by liggitt** [comment]
given the final release of 1.12.x is scheduled for today, I'm wondering if we can avoid doing this and live with the current state of the branch.

**Comment by feiskyer** [comment]
> given the final release of 1.12.x is scheduled for today, I'm wondering if we can avoid doing this and live with the current state of the branch.

Yep, seems the change is too large. I wonder we should skip this test case for 1.12 branch?

@liggitt @tpepper @justaugustus WDYT?

**Comment by cblecker** [comment]
@feiskyer Do either of the open PRs touch dependencies?

**Comment by justaugustus** [comment]
@feiskyer @liggitt -- what's our exposure here? 
If we can safely release without this in, I'd prefer to, especially this close to the release date and given the fact that it's the last 1.12 release.

**Comment by liggitt** [comment]
The CI job this is fixing (pull-kubernetes-godeps) is only relevant for PRs that change something under vendor. It can safely be skipped for PRs that do not involve any vendor changes.

**Comment by nikhita** [comment]
Yeah, I'd prefer to not include this change as well...moreover, to actually get the tests passing, it'll need some additional changes that I'm not really comfortable with cherry-picking.

> The CI job this is fixing (pull-kubernetes-godeps) is only relevant for PRs that change something under vendor. It can safely be skipped/ignored for PRs that do not involve any vendor changes.

With additional changes, this will also fix `pull-kubernetes-verify` (which is failing on the open cherry-picks), because the verify job runs `verify-godeps.sh`.

**Comment by nikhita** [comment]
However, if we don't fix it, it also means that those who do a `godep restore` or `godep save` on `v1.12.10` of our published (staging) repos will get an error...but I'm not sure how much we care about that scenario.

**Comment by justaugustus** [comment]
@liggitt @nikhita -- Appreciate the feedback! :)
Given that, I think we should proceed without this change and lean back on the fact that 1.12 is out of support if anyone reports issues w.r.t. `godep restore|save` failures.

**Comment by justaugustus** [comment]
(As a clarifying note, the cherry pick deadline for 1.12.10 was Friday 6/28 and the [release is scheduled for Monday 7/1](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#112).)

**Comment by feiskyer** [comment]
Thanks everyone. Since 1.12.10 would be the last release, and all the current approved cherry picks are not related with vendors, I would merge them manually.

**Comment by nikhita** [comment]
xref: created https://github.com/kubernetes/publishing-bot/pull/191 to fix the publishing-bot if we decide not to go for this.

**Comment by nikhita** [comment]
Ah, just realized all cherry-picks have been merged. :)

/close

**Pull request closed without merging**
