### PR TITLE
Pass addressable values to DeepCopy

### PR DESCRIPTION
**Pull request by liggitt**
Extracted from https://github.com/kubernetes/kubernetes/pull/35728

These are the places we are currently calling DeepCopy incorrectly, and we need to fix, even if we don't pick up the changes to DeepCopy in #35728:
* creating a new cloner means we have no generated functions registered
* passing non-addressable values doesn't pick up generated deep copy functions, and forces us into reflective mode

### CODE REVIEW

**Comment by liggitt** [comment]
cc @deads2k @sttts @lavalamp

**Comment by liggitt** [comment]
cc @kubernetes/sig-federation @nikhiljindal for awareness of problems with using `conversion.NewCloner().DeepCopy(...)`

**Comment by deads2k** [comment]
lgtm

**Comment by sttts** [comment]
lgtm

**Pull request merged**
