### PR TITLE
[do-not-merge] Add an md5 based kube-up identity that should 'always' work

### PR DESCRIPTION
**Pull request by jayunit100**
_Problem_

I think cluster/kube-up doesnt identify the components it creates on a per user basis, hence a common GCE account can't be used for multiple kube-ups.  If im missing something let me know.

_Solution_

Grab the unique contents of `gcloud info` and use that as a unique Google cloud user identity.  

There are other ways to uniquely identify users, i picked MD5 from gcloud simply because a users gcloud credentials are gauranteed to be on any system using kube-up for GCE, and are generally going to have some unique stuff in them related to the user's name/ user name in the home directory path
- This is more reliable then an env var `$USER`, which isnt on all OSs
- Its more persistent for dev workflows than `date +%s`, which will break kube-down (presumeably)
- Its gauranteed to match the regex's for various cloud components (`hostname` is unique but it often has things like dashes and so on ).
- 5char md5 is easily Short enough that it wont ever result in component names that are too long
- This doesnt require exporting a user id of any sort,  so its backward compatible with existing dev workflows/scripts

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31986)

### CODE REVIEW

**Comment by jayunit100** [comment]
marked as do not merge because im not sure kube-up is used in CI.  just an idea we will see if this has any merit from others.

**Comment by jayunit100** [comment]
` project_hash=$(kube::build::short_hash "$GCLOUD_PROJECT")`  looks like we are hashing at the GCLOUD level in some places.  Not sure if thats the ideal way to do buckets or not (yet).  There is a second level of nesting of the buckets, though , i.e. `gs://kubernetes-staging-7a2dcb4fb4/kubernetes-jayunit100-devel`

**Comment by jayunit100** [comment]
closing.  for me , right now, kube-up seems to crash when pulling `kubernetes-src.tar.gz` , but im not sure why.  `gs://` uploads are working so i dont think its related to cloud storage.

**Comment by mikedanese** [comment]
I think this might be considered a backwards incompatible change. I'm not sure what was up, sorry for missing this. Closing since your last comment indicates that you meant to close.

**Pull request closed without merging**
