### PR TITLE
support fieldSelector spec.schedulerName

### LINKED ISSUE #49190: field label spec.schedulerName not supported
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:

When trying to list object using field  spec.SchedulerName, we are getting the below error message.

**Failed to list  `*v1.Pod` : field label not supported: spec.schedulerName**

**What you expected to happen**:

To be able to fetch pods using the list and watch based on the field 'spec.schedulerName'

**How to reproduce it (as minimally and precisely as possible)**:

Create a simple controller to with a list and watch method.
Set the FieldSelector  ( in the ListOptions structure ) in the ListFunc and the WatchFunc to 'spec.SchedulerName=custome-SchedulerName'
Running this controller yields the above error.

**Anything else we need to know?**:

Description:

Unable to fetch pods based on the field 'spec.schedulerName'.
This was added in 1.6 version, for multi scheduler support in kubernetes.

We need to be able to fetch pods 

1) Assigned to a particular custom scheduler.
2) Should be able to fetch the state transition of the pods scheduled by a custom scheduler using the fields selector.

  Whats the correct way to use 'schedulerName' fields for fetching objects?
  Or is there any other way for the custom scheduler to determine the above information from the kubernetes?
  
  
  This is an urgent issue, any quick help/suggestion will be of great help.
  
  

**Environment**:
- Kubernetes version :
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T01:48:01Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Install tools: kubeadm

@kubernetes/sig-scheduling-bugs

@davidopp 
@deepak-vij

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #49190

**Special notes for your reviewer**:
/assign @davidopp  @bsalamat
/cc @lavalamp

**Release note**:

```release-note
add fieldSelector spec.schedulerName
```

### CODE REVIEW

**Comment by dixudx** [comment]
@ravisantoshgudimetla @shivramsrivastava PTAL. Thanks.

**Comment by dixudx** [comment]
/assign @davidopp @bsalamat 
I think it's ready for review. PTAL. Thanks.

**Comment by dixudx** [comment]
ping @wojtek-t Need your `lgtm`. Thanks.

**Comment by ravisantoshgudimetla** [comment]
I think there is no validation for this field. @dixudx Do you mind adding some validation to schedulerName field or do you want to handle it in a separate issue?

**Comment by dixudx** [comment]
@ravisantoshgudimetla I think we'd better handle it in a separate PR, since the validation for `schedulerName` is another scope. I'll open a new PR to take this part.

**Comment by dixudx** [comment]
ping @caesarxuchao @davidopp Need your `/lgtm` to get it merged. PTAL. Thanks.

**Comment by dixudx** [comment]
ping @caesarxuchao @davidopp Need your /lgtm to get it merged. PTAL. Thanks.

**Comment by dixudx** [comment]
ping @caesarxuchao @davidopp @wojtek-t @caesarxuchao

Need your `/lgtm` to get it merged. PTAL. Thanks.

**Comment by dixudx** [comment]
ping @caesarxuchao @davidopp @wojtek-t

Need your `/lgtm` to get it merged. PTAL. Thanks.

**Comment by caesarxuchao** [comment]
lgtm. @liggitt @deads2k could you also take a look? Thanks.

**Comment by deads2k** [comment]
> lgtm. @liggitt @deads2k could you also take a look? Thanks.

looks fine.

**Pull request merged**
