### PR TITLE
Automated cherry pick of #104384: fix: skip case sensitivity when checking Azure NSG rules
#104382: fix: ensure InstanceShutdownByProviderID return false for

### PR DESCRIPTION
**Pull request by feiskyer**
Cherry pick of #104384 #104382 on release-1.19.

#104384: fix: skip case sensitivity when checking Azure NSG rules
#104382: fix: ensure InstanceShutdownByProviderID return false for

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
fix: skip case sensitivity when checking Azure NSG rules
fix: ensure InstanceShutdownByProviderID return false for creating Azure VMs
```

### CODE REVIEW

**Comment by cheftako** [comment]
Would need to wait for #104382 to merge on the mainline. Also not sure if we're still accepting 1.19 cherry picks. (You should check with SIG Release)

**Comment by feiskyer** [comment]
@cheftako End of Life for 1.19 is 2021-10-28, so 1.19 branch should still accept new fixes. Could you help to approve  #104382?

**Comment by cheftako** [comment]
> @cheftako End of Life for 1.19 is 2021-10-28, so 1.19 branch should still accept new fixes. Could you help to approve #104382?

Responded on that PR. Would like @andrewsykim to weigh in on the bug vs feature call.

**Comment by feiskyer** [comment]
ping @kubernetes/release-managers for cherry-pick approval

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
