### PR TITLE
Requesting reviewers status for SergeyKanzhelev

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
**What type of PR is this?**

/kind cleanup
/sig node

**What this PR does / why we need it**:

Requesting SIG node reviewers status for myself.

**Special notes for your reviewer**:

Thank you for considering me as a reviewer. I'm excited for the opportunity to keep contributing to SIG node and k8s success.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

This document outlines membership requirement checkboxes: https://docs.google.com/document/d/13gPQVIvFqFfMH5HKF3qp8D-uv_QrYx4kUw1GOi43IOo/edit#

### CODE REVIEW

**Comment by dchen1107** [comment]
+1

Sergey, thanks for all your contribution to SIG Node among technical, logistic and communication. Especially thank you for leading SIG Node e2e project!

**Comment by Random-Liu** [comment]
+1 :)

**Comment by SergeyKanzhelev** [comment]
@sjenning and @derekwaynecarr commented on the doc: https://docs.google.com/document/d/13gPQVIvFqFfMH5HKF3qp8D-uv_QrYx4kUw1GOi43IOo/edit# Thank you for your support!

**Pull request merged**
