### PR TITLE
Relax constraints on container status while fetching container logs

### PR DESCRIPTION
**Pull request by vishh**
#4640

### CODE REVIEW

**Comment by vishh** [comment]
cc @dchen1107

**Comment by dchen1107** [comment]
I am not sure this one will fix the issue. It should fix pods with restart never, but if pod restart always, how do you get previous failed container logs? I mean I am ok with this one, but I don't think it is addressing #4640 completely.

**Comment by vishh** [comment]
@dchen1107: Valid concern. Unless we preserve the previous incarnation of a container, we cannot get the logs. This PR should get rid of the regression I had introduced earlier.

**Comment by dchen1107** [comment]
LGTM. please rebase it then I can merge.

**Comment by vishh** [comment]
@dchen1107: Rebased to head.

**Comment by vishh** [comment]
Ping @dchen1107

**Pull request merged**
