### PR TITLE
Run auto scaler as non root in kube up

### PR DESCRIPTION
**Pull request by dims**
Digging into why `ci-kubernetes-e2e-gci-gce-autoscaling` is consistently failing with the following error

```
  I0224 19:04:35.935844 10048 kubectl_utils.go:128] Logs of kube-system/cluster-autoscaler-ca-master:cluster-autoscaler on node ca-master
  I0224 19:04:35.935888 10048 kubectl_utils.go:129]  : STARTLOG
  I0224 19:02:38.157543       1 flags.go:57] FLAG: --add-dir-header="false"
  log: exiting because of error: log: unable to create log: open /var/log/cluster-autoscaler.log: permission denied
  ENDLOG for container kube-system:cluster-autoscaler-ca-master:cluster-autoscaler
  [FAILED] in [SynchronizedBeforeSuite] - k8s.io/kubernetes/test/e2e/e2e.go:232 @ 02/24/24 19:04:35.936
  << Timeline
```

https://testgrid.k8s.io/sig-autoscaling-cluster-autoscaler#gci-gce-autoscaling&width=20

#### What type of PR is this?
/kind failing-test
/kind cleanup

#### What this PR does / why we need it:

Looks like the changes made in https://github.com/kubernetes/kubernetes/pull/101164 did not include the cluster-autoscaler

#### Which issue(s) this PR fixes:

related to https://github.com/kubernetes/kubernetes/issues/123478

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
> link https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/123490/pull-kubernetes-e2e-gci-gce-autoscaling/1761542835431018496

```
I0225 01:13:47.101844 76643 cluster_size_autoscaling.go:722] Unexpected error: 
    <*errors.errorString | 0xc001863ba0>: 
    timeout waiting 20m0s for appropriate cluster size
    {
        s: "timeout waiting 20m0s for appropriate cluster size",
    }
[FAILED] timeout waiting 20m0s for appropriate cluster size
In [It] at: k8s.io/kubernetes/test/e2e/autoscaling/cluster_size_autoscaling.go:722 @ 02/25/24 01:13:47.102
< Exit [It] should be able to scale down when rescheduling a pod is required and pdb allows for it [Feature:ClusterSizeAutoscalingScaleDown] - k8s.io/kubernetes/test/e2e/autoscaling/cluster_size_autoscaling.go:719 @ 02/25/24 01:13:47.102 (22m12.736s)
> Enter [AfterEach] [sig-autoscaling] Cluster size autoscaling [Slow] - k8s.io/kubernetes/test/e2e/autoscaling/cluster_size_autoscaling.go:143 @ 02/25/24 01:13:47.102
```

presubmit CI failed

**Comment by dims** [comment]
@pacoxu the situation is better than it was before where the entire run was failing. I'd like to merge this and let sig-autoscaling take up the failing tests as follow up.

**Review by upodroid — APPROVED** [review]
/lgtm

**Pull request merged**
