### PR TITLE
Automated cherry pick of #66891: Change the expected error message to the common part of the

### PR DESCRIPTION
**Pull request by caesarxuchao**
Cherry pick of #66891 on release-1.11.

#66891: Change the expected error message to the common part of the

### CODE REVIEW

**Comment by foxish** [comment]
This missed 1.11.2 that is due today. Will approve after the cut for 1.11.3

**Comment by caesarxuchao** [comment]
@foxish since 1.11.2 was cut, can we merge this to 1.11 now? Thanks.

**Pull request merged**
