### PR TITLE
Revert pull request #85879 "hollow-node use remote CRI"

### LINKED ISSUE #86423: All CI kubemark tests are failing
See https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-100

E.g. failure, the error seems to be:
```
W1219 07:34:39.336] error: error parsing /go/src/k8s.io/kubernetes/kubernetes/test/kubemark/resources/addons/heapster.json: json: line 14: invalid character ':' after object key:value pair

```

/assign @jkaniuk

### PR DESCRIPTION
**Pull request by jkaniuk**
Kubemark tests started failing after merge of #86423:
https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-100

**What type of PR is this?**
/kind bug

**Which issue(s) this PR fixes**:
Fixes #86423

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
hollow-node do not use remote CRI anymore
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```

/sig scalability
/cc @mm4tt @wojtek-t @gongguan @dashpole

### CODE REVIEW

**Comment by wojtek-t** [comment]
@gongguan - FYI

/lgtm
/approve

**Comment by gongguan** [comment]
thanks jkaniuk, sorry for making it.

**Comment by liggitt** [comment]
#86317 flake
/retest

**Pull request merged**
