### PR TITLE
 check pod securityContext hostNetwork in exec admission controller

### LINKED ISSUE #56838: DenyEscalatingExec admission controller should check psp hostNetwork
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

currently only `hostIPC ` `hostPID` are checked in `DenyEscalatingExec` admission controller

**What you expected to happen**:

hostNetwork should also be checked to deny exec /attach

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:
currently only hostIPC hostPID are checked in DenyEscalatingExec admission controller,
hostNetwork should also be checked to deny exec /attach
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #56838

**Special notes for your reviewer**:

**Release note**:

```release-note
check psp HostNetwork in DenyEscalatingExec admission controller.
```

### CODE REVIEW

**Comment by CaoShuFeng** [comment]
Tightening this would effect users, so a release note is better.

**Comment by deads2k** [comment]
/approve
/assign liggitt

I'm fine with it.

**Pull request merged**
