### PR TITLE
Setting REMOUNT_VOLUME_PLUGIN_DIR for COS images in kube-env

### LINKED ISSUE #60725: Flexvolume e2e tests failing
/kind bug

https://k8s-testgrid.appspot.com/sig-storage#gce-serial

This is likely caused by a missing REMOUNT_VOLUME_PLUGIN_DIR flag in kube-env construction.

/assign
/sig storage

### PR DESCRIPTION
**Pull request by verult**
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #60725

**Special notes for your reviewer**: Not sure if it's the best place to set `REMOUNT_VOLUME_PLUGIN_DIR`.

/sig storage
/sig cluster-lifecycle

### CODE REVIEW

**Comment by tpepper** [comment]
@roberthbailey this pull needs 1.10 milestone markers

**Comment by roberthbailey** [comment]
@dchen1107 - can you confirm that we want this change for nodes in for 1.10?

**Comment by verult** [comment]
flake: https://github.com/kubernetes/kubernetes/issues/61009

**Comment by krzyzacy** [comment]
gke is not a `required` presubmit, so your PR can still go in

**Pull request merged**
