### PR TITLE
Fix service shell test

### PR DESCRIPTION
**Pull request by wojtek-t**
This test couldn't even start with v1 API before this change.
 After this change I've run it 3 times and it passed (although I think we should not move it out of flaky suite yet).

Ref #10127 #9312 

cc @quinton-hoole @davidopp @thockin

### CODE REVIEW

**Comment by wojtek-t** [comment]
Also - we should migrate this test to .go test, but this should be done after 1.0.

**Comment by wojtek-t** [comment]
cc @gmarek

**Comment by gmarek** [comment]
LGTM

**Comment by wojtek-t** [comment]
Because:
- this PR only touches "services.sh" shell e2e test
- this test didn't passed even once during last over 200 runs
I'm going to merge this PR now to improve the situation.

**Pull request merged**
