### PR TITLE
Added e2e test case for network partition.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Added e2e test case which verifies if a node can return to cluster after longer network partition. Valid for gce.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
@quinton-hoole 
This PR already has been reviewed and merged as #8862. Then, it was reverted in #9183 because of flakiness. The flakiness was caused by the wrong order of he arguments for wait.Poll (in waitForRCPodOnNode and waitForRCPodToDisappear methods in util.go) and too small timeouts, which  is fixed now.

**Comment by quinton-hoole** [comment]
LGTM!  Thanks Jerzy!

**Comment by krousey** [comment]
@jszczepkowski We're seeing a lot of timeout errors in the Node Resize test after this commit. Could you please investigate?

```
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/resize_nodes.go:409
Expected error:
    <*errors.errorString | 0xc20811c5f0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
```

**Comment by quinton-hoole** [comment]
See also #9487.  To be clear, this is likely to be a system problem, not necessarily a problem with this test.  But either way it needs to be investigated (in #9487 please).

**Pull request merged**
