### PR TITLE
Fix link to CRI-O sock path

### PR DESCRIPTION
**Pull request by hasheddan**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fixes link to point to CRI-O sock constant defined in cadvisor. We
cannot pin directly because of linux build tags in transitive dependency
opencontaines/runc.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

**Which issue(s) this PR fixes**:

n/a

**Special notes for your reviewer**:

/sig node
/priority important-longterm

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by hasheddan** [comment]
ah didn't get the bazel update in

**Comment by hasheddan** [comment]
Just opted to correct the link given that we cannot pin to this constant due to build constraints in runc

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
