### PR TITLE
Fix NetworkPolicy describe for egress-all policies

### LINKED ISSUE #93131: NetworkPolicy describe output for egress-all should mention destination instead of source
**What happened**:
A NetworkPolicy to allow egress to all Pods should use the term "destination" instead of "source" while `kubectl describe`

example:

```
kubectl describe networkpolicy net-document 
Name:         net-document
Namespace:    default
Created on:   2020-07-15 18:16:46 -0700 PDT
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"net-document","namespace":"default"},"spe...
Spec:
  PodSelector:     app=test-document
  Allowing ingress traffic:
    To Port: <any> (traffic allowed to all ports)
    From: <any> (traffic not restricted by source)
  Allowing egress traffic:
    To Port: 80/TCP
    To: <any> (traffic not restricted by source)
  Policy Types: Egress, Ingress

```

**What you expected to happen**:
should instead be

```
kubectl describe networkpolicy net-document 
Name:         net-document
Namespace:    default
Created on:   2020-07-15 18:16:46 -0700 PDT
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"net-document","namespace":"default"},"spe...
Spec:
  PodSelector:     app=test-document
  Allowing ingress traffic:
    To Port: <any> (traffic allowed to all ports)
    From: <any> (traffic not restricted by source)
  Allowing egress traffic:
    To Port: 80/TCP
    To: <any> (traffic not restricted by destination)
  Policy Types: Egress, Ingress
``
**How to reproduce it (as minimally and precisely as possible)**:
Create a allow-all egress NetworkPolicy and do `kubectl describe <npName>`

### PR DESCRIPTION
**Pull request by abhiraut**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> 
/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
NetworkPolicy egress-all `kubectl describe` output should refer to the term "destination" as opposed to "source" for
describing policies which do not restrict traffic based on the destination.
**Which issue(s) this PR fixes**:

Fixes #93131

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by andrewsykim — COMMENTED** [review]
/lgtm

**Review by andrewsykim — COMMENTED** [review]
/assign @thockin

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
