### PR TITLE
GA rotatekubeletservercertificate feature

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
We are promoting RotateKubeletServerCertificate feature to GA.

In 1.30 pre-planning, this was identified as a feature that has been in beta and working successfully for a long time. We should GA this feature.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

I couldn't find a KEP that references this feature gate so not sure if a k/enhancement PR is required also for GA.

#### Does this PR introduce a user-facing change?

```release-note
Promote RotateKubeletServerCertificate to GA
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kannon92** [comment]
/label api-review

This should be for 1.30.

**Comment by liggitt** [comment]
This was discussed in sig-auth in the [2023-04-12 meeting](https://docs.google.com/document/d/1woLGRoONE3EBVx-wTb4pvp4CI7tmLZ6lS26VTbosLKM/edit#bookmark=id.bzvwpuqxoabx)

Yes it needs a KEP to make sure it actually meets quality and monitoring requirements for GA.

Some discussion in https://github.com/kubernetes/enhancements/issues/267#issuecomment-1411225724, a creation of a retroactive KEP to capture current state was opened in https://github.com/kubernetes/enhancements/pull/3806

/sig auth node
/hold
/cc @SergeyKanzhelev

**Comment by liggitt** [comment]
/remove-label api-review

since the next step is completing the retroactive design doc and ensuring GA criteria are defined and met

**Comment by kannon92** [comment]
/close

This will not be merged for a long time. KEP needed, metrics bumped so going to close for now.

**Pull request closed without merging**
