### PR TITLE
Support multiple arguments for cordon and drain

### LINKED ISSUE #68630: cordon and drain should take multiple arguments
They should be consistent with all other commands that allow multiple arguments (since they already allow label selectors).

```
kubectl cordon foo bar baz
```

should cordon all of them, not return an error.

@kubernetes/sig-cli-bugs

### PR DESCRIPTION
**Pull request by goodluckbot**
**What this PR does / why we need it**:
Support multiple arguments for cordon/uncordon and drain

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #68630 

**Special notes for your reviewer**:

**Release note**:
```release-note
kubectl: support multiple arguments for cordon/uncordon and drain
```

### CODE REVIEW

**Comment by neolit123** [comment]
@goodluckbot 
thanks for the PR!

please change the release note in the first post to:
```
kubectl: support multiple arguments for cordon/uncordon and drain
```

/hold
/ok-to-test
/kind bug

**Comment by Antiarchitect** [comment]
@goodluckbot please update if possible.

**Comment by neolit123** [comment]
please sign the CLA as instructed here:
https://github.com/kubernetes/kubernetes/pull/68655#issuecomment-437671089

if you encounter issues with that please contact the CNCF help desk.

**Comment by neolit123** [comment]
try using your CLA authorized email as authorship of your commits.
https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit
if you still have a problem try reporting the issue in #sig-testing on slack.

**Comment by smarterclayton** [comment]
Yay!

/approve
/lgtm

**Pull request merged**
