### PR TITLE
Remove util/selinux package

### PR DESCRIPTION
**Pull request by jsafrane**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
The package says:

> the libcontainer SELinux package is only built for Linux, so it is
> necessary to have a NOP wrapper which is built for non-Linux platforms

This is not true, Kubernetes now imports [github.com/opencontainers/selinux/go-selinux](https://github.com/opencontainers/selinux/tree/main/go-selinux) and it has proper multiplatform support (i.e. NOOP on non-Linux platforms).

Removing the whole package and calling go-selinux directly.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jsafrane** [comment]
/retest
`There was a problem refreshing your current auth tokens: ('invalid_grant: Invalid JWT Signature.', {'error': 'invalid_grant', 'error_description': 'Invalid JWT Signature.'})`
Does not look related to this PR

**Review by ehashman — COMMENTED** [review]
/triage accepted
/priority backlog

/lgtm

**Pull request merged**
