### PR TITLE
Removed metrics api group

### PR DESCRIPTION
**Pull request by piosz**
``` release-note
Removed metrics api group
```

The group is empty and unused. Kubelet Metrics API is defined in Kubelet code. Master Metrics API is defined in Heapster. Removing to avoid the confusion.

[Analytics]()

### CODE REVIEW

**Comment by piosz** [comment]
cc @caesarxuchao @timstclair

**Comment by timstclair** [comment]
Thanks for the clean up!

**Comment by lavalamp** [comment]
lgtm

**Comment by piosz** [comment]
Thanks @lavalamp!

**Comment by wojtek-t** [comment]
@piosz - can you please rebase?

**Comment by piosz** [comment]
Bumping priority to avoid further rebases.

**Comment by piosz** [comment]
@k8s-bot e2e test this issue: #23591

**Pull request merged**
