### PR TITLE
Fix a bug with exposing prometheus client metrics in multiple components

### PR DESCRIPTION
**Pull request by crassirostris**
I think this is a bug caused by splitting the repos: prometheus metrics are registered in a module that initialized metrics client-go never uses.

```release-note
Fix a bug that prevents client-go metrics from being registered in prometheus in multiple components.
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
/lgtm

It affects components other than the kube-apiserver. Could you check who else imports the prometheus initialization package?

**Comment by crassirostris** [comment]
@caesarxuchao 

```
$ grep -Ir 'k8s.io/kubernetes/pkg/client/metrics/prometheus'
federation/cmd/kubefed/app/kubefed.go:  _ "k8s.io/kubernetes/pkg/client/metrics/prometheus" // for client metric registration
cmd/cloud-controller-manager/controller-manager.go:     _ "k8s.io/kubernetes/pkg/client/metrics/prometheus" // for client metric registration
cmd/kubelet/kubelet.go: _ "k8s.io/kubernetes/pkg/client/metrics/prometheus" // for client metric registration
cmd/kube-controller-manager/controller-manager.go:      _ "k8s.io/kubernetes/pkg/client/metrics/prometheus" // for client metric registration
cmd/kube-apiserver/apiserver.go:        _ "k8s.io/kubernetes/pkg/client/metrics/prometheus" // for client metric registration
cmd/kube-proxy/proxy.go:        _ "k8s.io/kubernetes/pkg/client/metrics/prometheus" // for client metric registration
cmd/kubemark/hollow-node.go:    _ "k8s.io/kubernetes/pkg/client/metrics/prometheus" // for client metric registration
cmd/kubectl/app/kubectl.go:     _ "k8s.io/kubernetes/pkg/client/metrics/prometheus" // for client metric registration
cmd/hyperkube/main.go:  _ "k8s.io/kubernetes/pkg/client/metrics/prometheus" // for client metric registration
```

What to do next?

**Comment by caesarxuchao** [comment]
I'm trying to say this is fixing a bug that affects all the components listed in the "grep" result. Could you update the release note to say something like "fix a bug that hides client-go metrics"?

**Comment by crassirostris** [comment]
> Could you update the release note

Oh, now I see what you mean! Got confused, sorry

**Comment by crassirostris** [comment]
@caesarxuchao Done, thanks for noticing! PTAL

**Comment by caesarxuchao** [comment]
Still lgtm. Thanks.

I'm surprised that we didn't have a bug report earlier.

**Comment by caesarxuchao** [comment]
/assgin @thockin 

for approval.

**Pull request merged**
