### PR TITLE
Added `CriticalAddonsOnly` toleration for npd.

### LINKED ISSUE #47015: Add `CriticalAddonsOnly` toleration for both npd and fluentd.
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):
master

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Currently, the YAML template for both npd and fluentd service do not have `CriticalAddonsOnly` toleration, this may cause the daemonset cannot be started on a node if it is already selected to run `critical pods`, it is better to add `CriticalAddonsOnly` toleration for both npd and fluentd so as to make sure those daemonset can run on the nodes even if it is for `critical pod`.

All other daemonset in kubernetes also have such tolerations.

**What you expected to happen**:
Should add `CriticalAddonsOnly` toleration for both npd and fluentd.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:
We should add `CriticalAddonsOnly` toleration to make sure the daemonset can be scheduled on the node even if already planned to run critical pod.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #47015

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by gyliu513** [comment]
@k8s-bot pull-kubernetes-node-e2e test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this
@k8s-bot pull-kubernetes-unit test this

**Comment by gyliu513** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by gyliu513** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by gmarek** [comment]
This actually looks like something that should go into 1.7. @dchen1107

**Comment by gyliu513** [comment]
Thanks @gmarek , +1 to make this 1.7. @dchen1107

**Comment by gyliu513** [comment]
/retest

Ping @gmarek for approve

**Comment by gmarek** [comment]
@gyliu513 - I think it's no longer needed, as fluentd currently has generic toleration for everything. I believe we should close this PR.

**Comment by gyliu513** [comment]
Ah, I think that we still need this for npd? @gmarek

**Comment by gmarek** [comment]
Right.

**Comment by gyliu513** [comment]
@gmarek done

**Comment by notxcain** [comment]
@gmarek you wrote
> fluentd currently has generic toleration for everything

Where is it specified? Thanks.

**Comment by gyliu513** [comment]
@notxcain here https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-gcp/fluentd-gcp-ds.yaml#L110-L112

```
      #TODO: remove this toleration once #44445 is properly fixed.
      - operator: "Exists"
        effect: "NoSchedule"
      terminationGracePeriodSeconds: 30
```

**Comment by notxcain** [comment]
@gyliu513 thank you :)

**Pull request merged**
