### PR TITLE
Update etcd client to v3.4.9

### PR DESCRIPTION
**Pull request by jingyih**
**What type of PR is this?**
/kind feature

**Which issue(s) this PR fixes**:
#91266

**Does this PR introduce a user-facing change?**:
```release-note
Update etcd client side to v3.4.9
```

/sig api-machinery

### CODE REVIEW

**Comment by jingyih** [comment]
cc @dims @justaugustus @kubernetes/release-engineering @BenTheElder

**Comment by jingyih** [comment]
@liggitt Could you please help double check go mod related changes

**Comment by jingyih** [comment]
cc @wojtek-t @jpbetz @wenjiaswe

**Comment by BenTheElder** [comment]
/approve
(for vendor/)

**Comment by wojtek-t** [comment]
lgtm thanks!

**Pull request merged**
