### PR TITLE
Updating pause image refernces to 3.9

### PR DESCRIPTION
**Pull request by marosset**
Signed-off-by: Mark Rossetti <marosset@microsoft.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR updates references to `pause:3.8` to `pause:3.9` in k/k

Please see here for the changes:
https://github.com/kubernetes/kubernetes/pull/112924/files

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
> /hold for [kubernetes/k8s.io#4463](https://github.com/kubernetes/k8s.io/pull/4463)

^^ has merged

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by dims** [comment]
/approve

@kubernetes/release-managers PTAL!

**Review by xmudrii — APPROVED** [review]
For RelEng:
/approve

**Pull request merged**
