### PR TITLE
Update github.com/fsouza/go-dockerclient, and modify kubelet/dockertools to new docker.NewClientFromEnv

### PR DESCRIPTION
**Pull request by bufdev**
The only functionality update here is in `pkg/kubelet/dockertools/docker.go`. This uses the new go-dockerclient method `NewClientFromEnv`, which handles `DOCKER_HOST, DOCKER_TLS_VERIFY, and DOCKER_CERT_PATH` per the way that docker officially handles it.

https://github.com/fsouza/go-dockerclient/blob/933433faa3e1c0bbc825b251143f8e77affbf797/client.go#L226
https://github.com/fsouza/go-dockerclient/blob/933433faa3e1c0bbc825b251143f8e77affbf797/client.go#L790

The big diff is due to https://github.com/fsouza/go-dockerclient/pull/339, where we moved `vendor` to external to comply with golang 1.5 rules.

### CODE REVIEW

**Comment by dchen1107** [comment]
Can you have go-dockerclient as a separate commit, and changes for kubelet package in another one? Thanks!

**Comment by dchen1107** [comment]
ok to test

**Comment by peter-edge** [comment]
No problem, but it will be the godep update first as NewClientFromEnv is a
new function, is that ok?

**Comment by dchen1107** [comment]
Yes, that should be ok. Thanks!

**Comment by dchen1107** [comment]
@peter-edge  #12166 was merged earlier. You can rebase your pr now to have NewClientFromEnv update now. Thanks!

**Comment by peter-edge** [comment]
Ah very nice! I'll get on this tomorrow when I'm back at my computer (Sunday)

**Comment by peter-edge** [comment]
@dchen1107 closing this for https://github.com/GoogleCloudPlatform/kubernetes/pull/12471

**Pull request closed without merging**
