### PR TITLE
Stop vendoring heapster v1alpha1

### PR DESCRIPTION
**Pull request by caesarxuchao**
Changes to use the one in staging/metrics.

TODO: remove the exception in https://github.com/kubernetes/kubernetes/pull/45176

Implementing https://github.com/kubernetes/kubernetes/issues/45498#issuecomment-301013423.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@piosz @DirectXMan12 ptal. Thanks!

**Comment by DirectXMan12** [comment]
LGTM assuming tests pass

**Comment by caesarxuchao** [comment]
Thanks. All tests passed. Adding lgtm per @DirectXMan12 's comment.

**Comment by caesarxuchao** [comment]
@wojtek-t could you help approve the change? Thanks.

**Comment by wojtek-t** [comment]
@caesarxuchao - please squash commits a bit (I would suggest merging 1st and 4th and separately 2nd and 3rd - those two seem to be auto-generated).

/approve

**Comment by caesarxuchao** [comment]
@wojtek-t squashed as suggested. Thanks.

**Comment by caesarxuchao** [comment]
Rebased.

**Pull request merged**
