### PR TITLE
Kubelet flag for disabling hairpin mode

### PR DESCRIPTION
**Pull request by bprashanth**
Instruct the kubelet to backoff from doing anything to the hairpin settings of a bridge when using docker. ref https://github.com/kubernetes/kubernetes/issues/20096
@kubernetes/goog-node fyi

### CODE REVIEW

**Comment by thockin** [comment]
LGTM.  Thoughts on how to make `kubenet` respect this?

**Comment by thockin** [comment]
Squash once it passes CI

**Comment by bprashanth** [comment]
quashed, waiting for CI

**Comment by bprashanth** [comment]
@kubernetes/goog-testing I noticed soak-continuous just started, can we restart it once this goes in (I mean fresh cluster setup with https://github.com/bprashanth/kubernetes/commit/c3a3a2bacd114e72f64f8c3edfa959c4b5005c30#diff-d228e0b744115de6cc5a03d8d8f5fbfaR610)? Is that as simple as just clicking "Build now" or something?

**Comment by bprashanth** [comment]
@k8s-oncall noticed scalability is red so I'm hand merging this to help with https://github.com/kubernetes/kubernetes/issues/20096

**Pull request merged**
