### PR TITLE
Fix density test

### PR DESCRIPTION
**Pull request by wojtek-t**
It was broken in #17865

@davidopp @HaiyangDING - FYI

### CODE REVIEW

**Comment by davidopp** [comment]
Sorry about that.

**Comment by wojtek-t** [comment]
@davidopp - no worries

**Comment by HaiyangDING** [comment]
Is this the error that causes the testing failed many times? Thanks very much!

**Comment by wojtek-t** [comment]
@HaiyangDING - no it's something different; the problems you had are our flaky tests - this one was broken by your PR (this test is not running as part of presubmit, because it's too long)

**Pull request merged**
