### PR TITLE
Fixes #67561 Multiple same headers got wrong result on gcr.io/google-containers/echoserver:1.10

### LINKED ISSUE #67561: Multiple same headers got wrong result on gcr.io/google-containers/echoserver:1.10
/kind bug

Hello, actually this is a bug about `echoserver` not about k8s.

I use `gcr.io/google-containers/echoserver:1.10` to observe request headers and found if the request have multiple same headers echoserver will give a wrong result:

`curl -H 'x-foo:foo' -H 'x-foo:bar' http://echoserver:8080`

result:

```
...
Request Headers:
	x-foo=table: 0x41fadd70
...
```

Expected result:

```
...
Request Headers:
	x-foo=foo
	x-foo=bar
...
```

### PR DESCRIPTION
**Pull request by chanjarster**
**What this PR does / why we need it**:
Fix a bug of echoserver

**Which issue(s) this PR fixes**:
Fixes #67561

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ixdy** [comment]
/assign @nicksardo @aledbf 

I think you have the most context here?

**Comment by ixdy** [comment]
@chanjarster please bump `test/images/echoserver/VERSION` too.

**Comment by chanjarster** [comment]
@ixdy version bumped

**Comment by ixdy** [comment]
building images now

**Comment by ixdy** [comment]
/approve

images pushed.

**Comment by spiffxp** [comment]
/milestone v1.12
SIG Testing chair, if the images have already been pushed, this should be merged

**Pull request merged**
