### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by l2dy**
**What this PR does / why we need it**:
Fix a typo (evalutated -> evaluated).
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
I didn't touch pkg/generated/bindata.go and k8s.mo. Should I regenerate them in this PR?
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by l2dy** [comment]
@k8s-ci-robot CLA signed.

**Comment by l2dy** [comment]
Updated `pkg/generated/bindata.go` to fix the `pull-kubernetes-verify` test.

Should I update k8s.mo files and how can I generate them?

**Comment by l2dy** [comment]
Manually editing `pkg/generated/bindata.go` didn't fix the failed test and I'm not familiar with the workflow. I'll read the documents later but I'd be glad if someone can generate these files for me.

**Comment by php-coder** [comment]
> Manually editing pkg/generated/bindata.go didn't fix the failed test

Did you try to regenerate it with `./hack/generate-bindata.sh`? Or with `hack/update-all.sh`?

**Comment by l2dy** [comment]
@php-coder Thanks for the pointer, I've regenerated the files.

**Pull request merged**
