### PR TITLE
cherry pick of #91008: Do not swallow NotFound error for DeletePod in dsc.manage

### PR DESCRIPTION
**Pull request by 249043822**
Do not swallow NotFound error for DeletePod in dsc.manage

**What type of PR is this?**
/kind bug
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
links #91008
**Which issue(s) this PR fixes**:

Fixes #
links #67662, simular problems
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by tnozicka** [comment]
can you pick the actual commit, not the merge commit?

**Comment by 249043822** [comment]
@tnozicka okay, fixed

**Review by soltysh — CHANGES_REQUESTED** [review]
You've got to use https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md when cherry-picking.
/hold

**Comment by tpepper** [comment]
@249043822 if you could, it would be cleaner to use the script https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md and pick to 1.18 and 1.17.  If you do that, we can close the two current manual git cherry picks in favor of those.

**Pull request closed without merging**
