### PR TITLE
kubeadm: update comment for ArgumentsFromCommand function in app/util/arguments

### PR DESCRIPTION
**Pull request by my-git9**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

kubeadm: remove unused function in app/util/arguments

https://cs.k8s.io/?q=ArgumentsFromCommand&i=nope&files=&excludeFiles=&repos=

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/approve
where was this used?

**Comment by carlory** [comment]
It is added in https://github.com/kubernetes/kubernetes/pull/119156 @neolit123

**Comment by neolit123** [comment]
please see
https://github.com/kubernetes/kubernetes/pull/126959#discussion_r1734003407

instead of renoving add a comment. This function is kept intentionally.

**Comment by my-git9** [comment]
> please see [#126959 (comment)](https://github.com/kubernetes/kubernetes/pull/126959#discussion_r1734003407)
> 
> instead of renoving add a comment. This function is kept intentionally.

Thanks, judging from the conclusion of comment, we should add a comment instead of deleting the function

**Review by neolit123 — COMMENTED** [review]
thanks
/lgtm
/approve

**Pull request merged**
