### PR TITLE
added OWNERS to test/e2e/feature/feature.go

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
#### What type of PR is this?

/kind cleanup
/sig testing

#### Special notes for your reviewer:

This will not require test/ owners to approve sig-specific tests

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
Can we circle back to this after enhancements freeze?

**Comment by pohly** [comment]
See https://github.com/kubernetes/kubernetes/pull/123260.

**Comment by SergeyKanzhelev** [comment]
@pohly can we take this PR in to make it easier to merge PRs. If we will change mind later, we can always fix it.

**Comment by pohly** [comment]
I'm in favor of merging this. But let's first merge https://github.com/kubernetes/kubernetes/pull/123260 to ensure that future additions to the file follow some basic conventions (sorting, ideally with sufficient documentation).

@aojea, @BenTheElder ?

**Comment by SergeyKanzhelev** [comment]
this seems to be OK to merge now

**Comment by aojea** [comment]
I can see there is the relevant people in the owners files and sig testing can not be the gatekeeper of this labels (agree with Patrick) , it should be the corresponding sig approvers, please try to avoid the label explosion we had before

/lgtm
/approve

**Pull request merged**
