### PR TITLE
Automated cherry pick of #63492: Always track kubelet -> API connections

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #63492 on release-1.10.

#63492: Always track kubelet -> API connections

### CODE REVIEW

**Comment by liggitt** [comment]
holding to let the master PR make it through serial/soak/scale tests

**Comment by liggitt** [comment]
@derekwaynecarr @MaciekPytel would like to get review/approval lined up while we're waiting for the scale test results in master to see if this can make it into 1.10.3

**Comment by MaciekPytel** [comment]
@liggitt This needs to merge by tomorrow EOD to make it to 1.10.3.

**Comment by liggitt** [comment]
scale/serial/slow test runs showed no regression
/hold cancel

**Pull request merged**
