### PR TITLE
Add e2e test for kube-ui addon

### LINKED ISSUE #10968: e2e test that UI addon started
Should be pretty simple.

### PR DESCRIPTION
**Pull request by timstclair**
Resolves #10968

### CODE REVIEW

**Comment by mikedanese** [comment]
@timstclair can you rebase onto master? I think you caught master while the tests were failing.

**Comment by mikedanese** [comment]
This is LGTM otherwise.

**Comment by timstclair** [comment]
Done. If the tests were failing, why did k8s-bot say "e2e build/test passed"? (I can't view shippable results :/ )

**Comment by mikedanese** [comment]
@timstclair jenkins only runs e2e and shippable only runs. You should request to join the gcp-github-org and join kubernetes group.

See http://go/kubernetes/team-info/new-member-checklist

**Pull request merged**
