### PR TITLE
Revert "Skip kube-dns tests if coredns is installed"

### PR DESCRIPTION
**Pull request by pacoxu**
Reverts kubernetes/kubernetes#120749

see https://github.com/kubernetes/kubernetes/pull/120771
/cc @upodroid @aojea 

```release-note
None
```

### CODE REVIEW

**Review by upodroid — APPROVED** [review]
/lgtm
/sig testing

**Comment by aojea** [comment]
/lgtm
/approve

/retest

Let's start from a clean slate and avoid fixing forward

**Comment by aojea** [comment]
@dims do you mind reapproving? it turns out the blast radius is unexpected and I don't think we should start yet another fire , Mahamed will open a KEP for this effort so we can be better coordinated and organized

**Pull request merged**
