### PR TITLE
[Federation][e2e] Add framework for upgrade test in federation

### PR DESCRIPTION
**Pull request by shashidharatd**
Adding framework for federation upgrade tests. please refer to #41791

cc @madhusudancs @nikhiljindal @kubernetes/sig-federation-pr-reviews

### CODE REVIEW

**Comment by shashidharatd** [comment]
@k8s-bot kubemark e2e test this
@k8s-bot verify test this
@k8s-bot unit test this

**Comment by shashidharatd** [comment]
@k8s-bot verify test this

**Comment by shashidharatd** [comment]
@k8s-bot verify test this

**Comment by shashidharatd** [comment]
@k8s-bot verify test this

**Comment by shashidharatd** [comment]
@k8s-bot gce etcd3 e2e test this
@k8s-bot verify test this

**Comment by shashidharatd** [comment]
@madhusudancs , request your help in figuring out what is going on with `@k8s-bot verify test`. it has failed consistently for many times for this PR. did i miss something.
According to my analysis, the tests are interrupted, (i think because of timeout). but its never passing.
Can you help me please whenever you find time.

**Comment by shashidharatd** [comment]
@k8s-bot non-cri e2e test this
@k8s-bot verify test this

**Comment by madhusudancs** [comment]
@shashidharatd it looks like some sort of a lint failure?

**Comment by shashidharatd** [comment]
Thanks @madhusudancs, i fixed it now.

**Comment by madhusudancs** [comment]
It looks good overall. A few minor nits. Let me know once you address them, I will add the labels.

---

Reviewed 8 of 11 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[federation/cluster/upgrade.sh, line 3 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-Ke84UsM5WKoaTonKOrU:-Ke84UsNZdsEmllOdMTn:bb6ht2h) ([raw file](https://github.com/kubernetes/kubernetes/blob/5b918e2c97e716c3105fe44d5e7c7a1aa40348ae/federation/cluster/upgrade.sh#L3)):*
> ```Shell
> #!/bin/bash
> 
> # Copyright 2014 The Kubernetes Authors.
> ```

2017

---

*[federation/cluster/upgrade.sh, line 28 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-Ke862NnOuoxbYYTQPmR:-Ke862NnOuoxbYYTQPmS:buugf3g) ([raw file](https://github.com/kubernetes/kubernetes/blob/5b918e2c97e716c3105fe44d5e7c7a1aa40348ae/federation/cluster/upgrade.sh#L28)):*
> ```Shell
> source "${KUBE_ROOT}/federation/cluster/common.sh"
> 
> HYPERKUBE_IMAGE_VERSION="${1}"
> ```

Why not use `$KUBE_VERSION`?

---

*[federation/cluster/upgrade.sh, line 40 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-Ke85pl5w6mxTZfLQRdN:-Ke85pl5w6mxTZfLQRdO:b4msnis) ([raw file](https://github.com/kubernetes/kubernetes/blob/5b918e2c97e716c3105fe44d5e7c7a1aa40348ae/federation/cluster/upgrade.sh#L40)):*
> ```Shell
> 
>   # Upgrade apiserver image
>   ${host_kubectl} set image deployment/federation-apiserver apiserver=${hyperkube_image}
> ```

Wow! Did not know about the existence of `set image` command. TIL! Thanks.

---

*[hack/.linted_packages, line 2 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-KeXY3aIexsyzq07bZ0o:-KeXY3aJmM4WalAQpSrU:b-a40qbv) ([raw file](https://github.com/kubernetes/kubernetes/blob/062941c4ba9df4114c174d932d905a6351309500/hack/.linted_packages#L2)):*
> ```
> cluster/addons/fluentd-elasticsearch/es-image
> cluster/gce/gci/mounter
> ```

I guess this is auto-generated?

---

*[test/e2e/framework/test_context.go, line 55 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-KeLaTim4_1BavQcg-QY:-KeLaTim4_1BavQcg-QZ:b58apmv) ([raw file](https://github.com/kubernetes/kubernetes/blob/f26dcc96838d14d23f4b5c7f2e8c83c9c613bc21/test/e2e/framework/test_context.go#L55)):*
> ```Go
> 	EtcdUpgradeVersion       string
> 	UpgradeImage             string
> 	FederationUpgradeTarget  string
> ```

Can you put this together with other federation fields? Ideally I would extract federation specific fields into its own struct and make that struct a field here. But for now at least grouping them together would be a good starting point.

---

*[test/e2e/framework/upgrade_util.go, line 27 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-KeLakVziVxK1wNJrSrM:-KeLakVziVxK1wNJrSrN:b-uo6lw5) ([raw file](https://github.com/kubernetes/kubernetes/blob/f26dcc96838d14d23f4b5c7f2e8c83c9c613bc21/test/e2e/framework/upgrade_util.go#L27)):*
> ```Go
> )
> 
> // realVersion turns a version constants into a version string deployable on
> ```

s/realVersion/RealVersion/

---

*[test/e2e/framework/upgrade_util.go, line 29 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-KeLfvvlPytpRho4acpr:-KeLfvvmAoqeGG19V0Oh:b8g6ago) ([raw file](https://github.com/kubernetes/kubernetes/blob/f26dcc96838d14d23f4b5c7f2e8c83c9c613bc21/test/e2e/framework/upgrade_util.go#L29)):*
> ```Go
> // realVersion turns a version constants into a version string deployable on
> // GKE.  See hack/get-build.sh for more information.
> func RealVersion(s string) (string, error) {
> ```

I haven't compared 

---

*[test/e2e/framework/upgrade_util.go, line 30 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-KeXYB2yq4bUbXw2eISk:-KeXYB2yq4bUbXw2eISl:b-c9z3td) ([raw file](https://github.com/kubernetes/kubernetes/blob/062941c4ba9df4114c174d932d905a6351309500/test/e2e/framework/upgrade_util.go#L30)):*
> ```Go
> // GKE.  See hack/get-build.sh for more information.
> func RealVersion(s string) (string, error) {
> 	Logf(fmt.Sprintf("Getting real version for %q", s))
> ```

`fmt.Sprintf()` isn't required.

---

*[test/e2e_federation/upgrade.go, line 20 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-KeXYtzyI8dTLgxmfRRO:-KeXYtzyI8dTLgxmfRRP:bbi9lkb) ([raw file](https://github.com/kubernetes/kubernetes/blob/062941c4ba9df4114c174d932d905a6351309500/test/e2e_federation/upgrade.go#L20)):*
> ```Go
> 
> import (
> 	. "github.com/onsi/ginkgo"
> ```

Can you push this to the end and have an empty line before this import?

---

*[test/e2e_federation/upgrade.go, line 32 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-KeX_kfm4d3ZlodNz8ko:-KeX_kfm4d3ZlodNz8kp:by1pge7) ([raw file](https://github.com/kubernetes/kubernetes/blob/062941c4ba9df4114c174d932d905a6351309500/test/e2e_federation/upgrade.go#L32)):*
> ```Go
> 	f := fedframework.NewDefaultFederatedFramework("federation-upgrade")
> 
> 	framework.KubeDescribe("FCP upgrade", func() {
> ```

You could call this "Federation Control Plane upgrade". This is a human-readable string.

---

*[test/e2e_federation/framework/util.go, line 151 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-KeXd__ESS8Yz-oKaFTj:-KeXcz9nnOaEY21gMSuj:b-3tk4yn) ([raw file](https://github.com/kubernetes/kubernetes/blob/062941c4ba9df4114c174d932d905a6351309500/test/e2e_federation/framework/util.go#L151)):*
> ```Go
> func masterUpgradeGCE(context, rawVersion string) error {
> 	version := "v" + rawVersion
> 	zone := strings.TrimPrefix(context, "federeation-e2e-"+framework.TestContext.Provider+"-")
> ```

s/federeation/federation/

We really want a way to get the zone information from elsewhere. I want to move away from the `cluster-name == zone` world. If we run a test with two clusters in the same zone, this breaks. It's Ok for now, but can you please leave a TODO here and also file an issue for this?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-:-KeXeeTCKtwA27jJSfJy:b-u492xu)*

**Comment by shashidharatd** [comment]
@madhusudancs, addressed comments. PTAL

---

Review status: 7 of 13 files reviewed at latest revision, 11 unresolved discussions.

---

*[federation/cluster/upgrade.sh, line 3 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-Ke84UsM5WKoaTonKOrU:-KeYILDD3alA4bksWXwT:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/5b918e2c97e716c3105fe44d5e7c7a1aa40348ae/federation/cluster/upgrade.sh#L3)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

2017
</blockquote></details>

Done.

---

*[federation/cluster/upgrade.sh, line 28 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-Ke862NnOuoxbYYTQPmR:-KeYIMnBQ4RBD-R0eoG4:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/5b918e2c97e716c3105fe44d5e7c7a1aa40348ae/federation/cluster/upgrade.sh#L28)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

Why not use `$KUBE_VERSION`?
</blockquote></details>

Done.

---

*[federation/cluster/upgrade.sh, line 40 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-Ke85pl5w6mxTZfLQRdN:-KeYIZmURCxaiGEbU-6X:b32vhw) ([raw file](https://github.com/kubernetes/kubernetes/blob/5b918e2c97e716c3105fe44d5e7c7a1aa40348ae/federation/cluster/upgrade.sh#L40)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

Wow! Did not know about the existence of `set image` command. TIL! Thanks.
</blockquote></details>

:)

---

*[hack/.linted_packages, line 2 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-KeXY3aIexsyzq07bZ0o:-KeYIblz6_cwHJnND4bo:b2nign6) ([raw file](https://github.com/kubernetes/kubernetes/blob/062941c4ba9df4114c174d932d905a6351309500/hack/.linted_packages#L2)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

I guess this is auto-generated?
</blockquote></details>

yes

---

*[test/e2e/framework/test_context.go, line 55 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-KeLaTim4_1BavQcg-QY:-KeYIe5-u_8Kcywxypyx:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/f26dcc96838d14d23f4b5c7f2e8c83c9c613bc21/test/e2e/framework/test_context.go#L55)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

Can you put this together with other federation fields? Ideally I would extract federation specific fields into its own struct and make that struct a field here. But for now at least grouping them together would be a good starting point.
</blockquote></details>

Done.

---

*[test/e2e/framework/upgrade_util.go, line 27 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-KeLakVziVxK1wNJrSrM:-KeYIg8IEUi-o_Q4BNyz:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/f26dcc96838d14d23f4b5c7f2e8c83c9c613bc21/test/e2e/framework/upgrade_util.go#L27)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

s/realVersion/RealVersion/
</blockquote></details>

Done.

---

*[test/e2e/framework/upgrade_util.go, line 29 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-KeLfvvlPytpRho4acpr:-KeYIjWvdBmjBvrbas8e:b-ktkuoj) ([raw file](https://github.com/kubernetes/kubernetes/blob/f26dcc96838d14d23f4b5c7f2e8c83c9c613bc21/test/e2e/framework/upgrade_util.go#L29)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

I haven't compared 
</blockquote></details>

did not get this one.

---

*[test/e2e/framework/upgrade_util.go, line 30 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-KeXYB2yq4bUbXw2eISk:-KeYIhdvUgP3c43wEeC5:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/062941c4ba9df4114c174d932d905a6351309500/test/e2e/framework/upgrade_util.go#L30)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

`fmt.Sprintf()` isn't required.
</blockquote></details>

Done.

---

*[test/e2e_federation/upgrade.go, line 20 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-KeXYtzyI8dTLgxmfRRO:-KeYIo3CwxiiDfS0EbSK:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/062941c4ba9df4114c174d932d905a6351309500/test/e2e_federation/upgrade.go#L20)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

Can you push this to the end and have an empty line before this import?
</blockquote></details>

Done.

---

*[test/e2e_federation/upgrade.go, line 32 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-KeX_kfm4d3ZlodNz8ko:-KeYIpCSbJNYdjE44Wkj:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/062941c4ba9df4114c174d932d905a6351309500/test/e2e_federation/upgrade.go#L32)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

You could call this "Federation Control Plane upgrade". This is a human-readable string.
</blockquote></details>

Done.

---

*[test/e2e_federation/framework/util.go, line 151 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-KeXd__ESS8Yz-oKaFTj:-KeYIqsUUxFui09SMYmI:brofo27) ([raw file](https://github.com/kubernetes/kubernetes/blob/062941c4ba9df4114c174d932d905a6351309500/test/e2e_federation/framework/util.go#L151)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

s/federeation/federation/

We really want a way to get the zone information from elsewhere. I want to move away from the `cluster-name == zone` world. If we run a test with two clusters in the same zone, this breaks. It's Ok for now, but can you please leave a TODO here and also file an issue for this?
</blockquote></details>

Done. Added a todo as well. will create an issue as soon as this is merged.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-:-KeYS1gVD-LmnvSlcTFX:b-q8uoct)*

**Comment by madhusudancs** [comment]
/lgtm
/approve

---

Reviewed 7 of 7 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[cluster/gce/gci/mounter/mounter.go, line 66 at r5](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-Ke_UNAvqV0-YuEATn7F:-Ke_UNAwY5l1X9Jt49AE:b-x25ds7) ([raw file](https://github.com/kubernetes/kubernetes/blob/1fa4a49f092aa0ab0fc301578bcf12a7aa2f5ed9/cluster/gce/gci/mounter/mounter.go#L66)):*
> ```Go
> func mountInChroot(rootfsPath string, args []string) error {
> 	if _, err := os.Stat(rootfsPath); os.IsNotExist(err) {
> 		return fmt.Errorf("path <%s> does not exist", rootfsPath)
> ```

Is this a rebase issue? This change looks unrelated to this PR.

---

*[federation/cluster/upgrade.sh, line 28 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-Ke862NnOuoxbYYTQPmR:-Ke_UWkLn003dR9aWjW4:b-b7dwoh) ([raw file](https://github.com/kubernetes/kubernetes/blob/5b918e2c97e716c3105fe44d5e7c7a1aa40348ae/federation/cluster/upgrade.sh#L28)):*
<details><summary><i>Previously, shashidharatd (Shashidhara T D) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I actually meant using ${KUBE_VERSION} as an environment variable instead of receiving it as a positional argument. But since this is the upgrade target version, this is fine too.

---

*[test/e2e/framework/upgrade_util.go, line 29 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-KeLfvvlPytpRho4acpr:-Ke_Uvz1tecpv5MHskSY:b-fb7is5) ([raw file](https://github.com/kubernetes/kubernetes/blob/f26dcc96838d14d23f4b5c7f2e8c83c9c613bc21/test/e2e/framework/upgrade_util.go#L29)):*
<details><summary><i>Previously, shashidharatd (Shashidhara T D) wrote…</i></summary><blockquote>

did not get this one.
</blockquote></details>

Sorry, I had some internet connection issues when I was typing this. Did not realize I left it halfway. 

I wanted to check if this was just a code move from `cluster_upgrade.go` file above and there were no code changes. I did not compare the changes word to word.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41794#-:-Ke_VcJ7UmgYQG0L7tta:b6yv7yi)*

**Comment by fejta** [comment]
For hack:
/approve

For cluster/gce:
/assign @gmarek

**Pull request merged**
