### PR TITLE
replace hardcode with exists variable

### PR DESCRIPTION
**Pull request by yf4n**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
I think we should use variable instead of hardcode, so just repalce it.

#### Which issue(s) this PR fixes:

none

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
none
```

### CODE REVIEW

**Comment by alexzielenski** [comment]
/triage accepted
/assign @Jefftree 
could you take a look at this one as well? thanks

**Comment by Jefftree** [comment]
/lgtm cancel

Ah right, you shouldn't be able to import from `/cmd` from outside packages. Please revert the change to `plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go`

**Comment by gccio** [comment]
@Jefftree  ok, I have revert the change to `plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go`

**Pull request merged**
