### PR TITLE
WIP: Move pkg/genericapiserver and pkg/apiserver into staging

### PR DESCRIPTION
**Pull request by sttts**
- move both packages to `staging/src/k8s.io/genericapiserver/pkg, renaming `genericapiserver` to `server`
- add link `vendor/k8s.io/genericapiserver`

After this PR goes in, we can iteratively work on getting rid of all reference back into `k8s.io/kubernetes`. There are many. Once, they are all gone we theoretically can move `staging/src/k8s.io/genericapiserver` to a real new repository.

We get the following directory structure:

```
k8s.io/genericapiserver
  pkg
    server
    apiserver
```

IMO `pkg/apiserver` should be renamed to `handlers`.

Follow-up steps:
- split `pkg/api` into `pkg/apis/core` with all kube business logic objects, and into `k8s.io/genericapiserver/pkg/api` with all generic objects (Status, unversioned, Delete/ListOptions etcd.), compare https://github.com/kubernetes/kubernetes/pull/37551 step 4
- make genericapiserver tests really generic and move them into staging
- move parts of `pkg/runtime`, `pkg/apimachinery`, `pkg/utils` into staging

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37551)

### CODE REVIEW

**Comment by deads2k** [comment]
I like the plan.

@kubernetes/sig-api-machinery @lavalamp @caesarxuchao

**Comment by smarterclayton** [comment]
If you rename `pkg/apiserver` to handlers put it under `pkg/server/handlers`

**Comment by caesarxuchao** [comment]
> Once, they are all gone we theoretically can move staging/src/k8s.io/genericapiserver to a real new repository.

Before moving to a real repository, we need to update our e2e/intergration test infra to pull components from different repositories.

**Comment by lavalamp** [comment]
apiserver and genericapiserver should *not* end up in the same repository-- hopefully that's not what the OP is saying?

**Comment by sttts** [comment]
@lavalamp can you elaborate on that comment? pkg/apiserver is essentially the handlers part of genericapiserver. Without it genericapiserver doesn't make any sense.

If there are things in pkg/apiserver you don't want to get merged with genericapiserver, which are these?

**Comment by sttts** [comment]
@lavalamp and if you have some apimachinery repo in mind, can you sketch the repo structure, i.e. where to draw the lines?

Btw, I don't see this PR as the last word about the structure, but it's essentially a first step to split generic code from kube business logic. If we want to further split the generic code into those parts shared by server and client, that's fine and can be done in follow-ups.

**Comment by deads2k** [comment]
> apiserver and genericapiserver should not end up in the same repository-- hopefully that's not what the OP is saying?

The `pkg/apiserver` that @sttts is talking about isn't what creates the `kube-apiserver`.  It is a collection of generic handlers that provide handling and types for `RESTStorage`, `metrics`, `authentication`, and `authorization`.  I don't think we can provide a reasonable generic API server without that functionality.  I'm fine moving those out of `pkg/apiserver` (as sttts suggested), but we have to have them.

**Comment by deads2k** [comment]
`kube-apiserver` is created down in `pkg/master`, which I'm all in favor of updating *after* we split out genericapiserver.

**Comment by lavalamp** [comment]
Hrm, does the federation apiserver use pkg/apiserver? I had thought it was
kube-apiserver specific. If not then we should merge it (but then why did
we split out genericapiserver in the first place?)

@nikhiljindal can you give any detail?

**Comment by smarterclayton** [comment]
pkg/apiserver is more generic than genericapiserver - like restclient
to clientset.

**Comment by deads2k** [comment]
@lavalamp this is a rebase magnet as we keep making further refactors to genericapiserver to make it easier to re-use.  Are you ok with the explanation and the plan for snipping references?  Once we get the straight moves done, refinement in smaller chunks should be feasible.

**Comment by lavalamp** [comment]
I'm not convinced-- looking at some of the files in apiserver, it imports `pkg/api`, `k8s.io/kubernetes/pkg/apis/extensions`, `k8s.io/kubernetes/pkg/version`, `k8s.io/kubernetes/pkg/admission`... I think it's a mix?

**Comment by deads2k** [comment]
> I'm not convinced-- looking at some of the files in apiserver, it imports pkg/api, k8s.io/kubernetes/pkg/apis/extensions, k8s.io/kubernetes/pkg/version, k8s.io/kubernetes/pkg/admission... I think it's a mix?

A generic API server needs types from `pkg/version` to support a version endpoint, it needs `pkg/admission` to support an admission chain (plugins are in a different pacakge), it needs `pkg/api` to support listoptions for a RESTHandler.  Extensions does surprise me.

Either way, it sounds like the very strong preference is to snip the links in place and only move into staging once we're happy with the remaining packages being in kube/genericapiserver or kube/client-go.

@sttts There's a tool called `import-boss` in tree that we can use to start locking allowed dependencies.  That's how we'll have to start.

**Comment by deads2k** [comment]
@sttts let's get the whitelist for import-boss, invert the pkg/version using an interface, and start locking first level dependencies that we're happy with.

**Comment by deads2k** [comment]
Oh, and I think we'd be ok starting to move some bits from `pkg/apiserver` to `pkg/genericapiserver/<something>`.  If we consider genericapiserver as sitting under our API servers, it seems reasonable for them to depend on genericapiserver.

**Comment by sttts** [comment]
@deads2k @lavalamp there are a number of dependencies back into `pkg/*`. This PR was meant to start the process of cutting those links by making them explicit and then iteratively removing them.

Although, I prefer the hard cut with staging because it is much more visible, using import-boss should be viable as well. If we go this route, I also think it's important to split existing `pkg/*` packages and move the generic code into `pkg/genericapiserver/*`. This will include pretty large parts of `pkg/apiserver` and a number of other packages, until `pkg/genericapiserver` is completely independent. This will not be much different at the end than an early move to staging.

**Comment by lavalamp** [comment]
I agree with everything @deads2k and @sttts just said.

**Comment by smarterclayton** [comment]
All of the pkg/API references are to things that should be in
pkg/apis/meta/v1

On Dec 2, 2016, at 3:37 PM, Daniel Smith <notifications@github.com> wrote:

I agree with everything @deads2k <https://github.com/deads2k> and @sttts
<https://github.com/sttts> just said.

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/37551#issuecomment-264556501>,
or mute the thread

**Comment by sttts** [comment]
As discussed, closing. We will cleanup dependencies in-place.

**Pull request closed without merging**
