### PR TITLE
Patch glbc manifest to use version 1.0.0. Also add rate limiting flags

### PR DESCRIPTION
**Pull request by rramkumar1**
Will also add a release note to the 1.10 google doc as well.

Fixes: #61305

/assign @bowei 
/cc @nicksardo 

Release Note:
```release-note
Bump ingress-gce image in glbc.manifest to 1.0.0
```

### CODE REVIEW

**Comment by nicksardo** [comment]
/lgtm
Leaving approval to @bowei

**Comment by bowei** [comment]
/approve

need to probably have release notes

**Comment by jdumars** [comment]
Approved per release meeting 3/19/2018 
cc: @thockin

**Pull request merged**
