### PR TITLE
Log replica sets/pods for recreate test

### PR DESCRIPTION
**Pull request by 0xmichalis**
Dumps info for debugging https://github.com/kubernetes/kubernetes/issues/43864

### CODE REVIEW

**Comment by kargakis** [comment]
@k8s-bot gci gce e2e test this

**Comment by sttts** [comment]
lgtm

**Comment by kargakis** [comment]
Just realized that I wanted the second set of RSs from GetOldReplicaSets and not the first one (the second includes all of them). Reapplying the label

**Comment by mfojtik** [comment]
lgtm

**Pull request merged**
