### PR TITLE
refactor the func convertDesiredReplicasWithRules()

### PR DESCRIPTION
**Pull request by haiwei-li**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by Gerry-Lee** [comment]
@piosz @josephburnett Will you please have a review? Thanks.

**Comment by matthyx** [comment]
@Gerry-Lee can you add a release note block in your first comment like described [here](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md#applying-a-release-note)?

**Pull request closed without merging**
