### PR TITLE
SSH tunnels fallback to LegacyHostIP

### PR DESCRIPTION
**Pull request by ghost**
Currently SSH Tunnels requires NodeExternalIP to be present which is not always available: https://github.com/GoogleCloudPlatform/kubernetes/issues/11888.

Fixes issue by using a fallback to LegacyHostIP

### CODE REVIEW

**Comment by lavalamp** [comment]
Needs a test?

**Comment by cjcullen** [comment]
Would be nice to have a quick test and a comment for the findExternalAddress function, now that it isn't quite as simple as "get me the NodeExternalIP"

@wingedkiwi if you don't feel like writing the test, I'll settle for a comment + a "TODO(cjcullen): write a test for findExternalAddress"

**Comment by wingedkiwi** [comment]
Added a test and a small comment to the PR.

**Comment by cjcullen** [comment]
LGTM. Thanks for the test!

**Pull request merged**
