### PR TITLE
Enable Masters Kubelet registration in gce-test by default

### LINKED ISSUE #15803: Enable REGISTER_MASTER_KUBELET by default
To enable this feature by default for OSS k8s, we need to fix a bunch of e2e tests. File this issue for place holder.

### PR DESCRIPTION
**Pull request by gmarek**
Fixes #15803

I'm not sure why it wasn't enabled, but we probably should run the same configuration in tests as in production.

cc @wojtek-t @piosz @mikedanese @dchen1107

### CODE REVIEW

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by dchen1107** [comment]
Yes, it should be enabled for e2e by default too. There are a bunch of tests failed, and I guess it is due to the master node registration messed up some assumption of the test harness.

**Comment by gmarek** [comment]
@dchen1107 - I think some (if not all) failures might be related with problems with e2e test infrastructure we currently have. I'll rerun them tomorrow.

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by roberthbailey** [comment]
@gmarek The reason that this wasn't initially enabled by default was that e2e tests were failing. If we could get them to pass it'd be awesome to have this flag on by default. Thanks for looking into it.

**Comment by gmarek** [comment]
@roberthbailey: #18509

**Comment by gmarek** [comment]
Quoting @bprashanth from another PR:
> can you salt in the flannel change needed first?

> Set this to false:
> https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L347

> But still install flannel on the master node (so it's true everywhere else in salt, like: https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/top.sls#L46). This will tell the Kublete not to wait on flannel, but will still bringup the flannel daemon on the master node. The kubelet doesn't need to wait on flannel because master components run in host netowrking, but the master needs a flannel daemon because it needs flannel.1 so things like apiserver proxy to pod endpoint works.

**Comment by gmarek** [comment]
#18509 got merged. Let's try now.
@k8s-bot test this

**Comment by gmarek** [comment]
Tests timed out.
@k8s-bot test this

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by dchen1107** [comment]
ok to test

**Comment by dchen1107** [comment]
Test Result (2 failures / +2)
Kubernetes e2e suite.Services should be able to up and down services
Kubernetes e2e suite.MetricsGrabber should grab all metrics from a Scheduler.

**Comment by gmarek** [comment]
Oh, it got better:) Last time I was checking it was reliably timing out. I'll fix MetrixGrabber test next week.

**Comment by gmarek** [comment]
Fixed MetricsGrabber test in #21269, the latter seems like a flake. I'm slightly worried that we're running a smaller number of tests in PR builder though. I'll run all tests locally to verify that it works.

**Comment by gmarek** [comment]
Fixed metrics grabber test.

@k8s-bot test this issue: #IGNORE

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by gmarek** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by mikedanese** [comment]
@k8s-bot e2e test this please issue: #IGNORE

**Comment by mikedanese** [comment]
LGTM

@k8s-bot e2e test this please issue: #21767

**Comment by derekwaynecarr** [comment]
@mikedanese - how many pods are in the namespace when you see this flake?  looking at the log, this looks different, or is just more detail...

```
Feb 26 13:26:58.166: INFO: ERROR kubelet_docker_errors{operation_type="info"} => 1 @[0]
Feb 26 13:26:58.166: INFO: ERROR kubelet_docker_errors{operation_type="inspect_image"} => 21 @[0]
Feb 26 13:26:58.166: INFO: ERROR kubelet_docker_errors{operation_type="list_containers"} => 32 @[0]
Feb 26 13:26:58.166: INFO: ERROR kubelet_docker_errors{operation_type="list_images"} => 5 @[0]
Feb 26 13:26:58.166: INFO: ERROR kubelet_docker_errors{operation_type="start_container"} => 1 @[0]
Feb 26 13:26:58.166: INFO: ERROR kubelet_docker_errors{operation_type="stop_container"} => 11 @[0]
Feb 26 13:26:58.166: INFO: ERROR kubelet_docker_errors{operation_type="version"} => 22 @[0]
```

Is this normal for this test?

**Comment by derekwaynecarr** [comment]
@mikedanese - nm, got my flakes confused..

**Comment by gmarek** [comment]
Daemon controller is not a flake AFAICT. I didn't manage to look into it today though.

**Comment by gmarek** [comment]
Per PR tests should be fixed as soon as #22172 is merged. I'll run other tests to find other problematic ones.

**Comment by gmarek** [comment]
I run e2e-gce suite and all tests passed.

**Comment by gmarek** [comment]
Slow tests passed as well.

**Comment by gmarek** [comment]
Serial tests passed. It seems that we may enable it once #22275 #22172 are merged.

**Comment by gmarek** [comment]
@k8s-bot test this issue: #IGNORE

All failures should be fixed now.

**Comment by gmarek** [comment]
Aaand we're green. We need to decide what do do now: @mikedanese @davidopp @dchen1107 @bgrant0607

**Comment by bgrant0607** [comment]
We should merge this so it doesn't bitrot.

LGTM

**Pull request merged**
