### PR TITLE
Fix invalid FQDN when --cluster-domain is not set

### PR DESCRIPTION
**Pull request by CaoShuFeng**
When pod.Spec.Subdomain is set but --cluster-domain is not set in kubelet node, containers get an invalid FQDN like this:
 name1.subdomain.default.svc.
    
 With this change, we emit an WARNING event rather than use an invalid FQDN.

```release-note
avoid invalid FQDN for containers when --cluster-domain is not set in kubelet
```

### CODE REVIEW

**Comment by dashpole** [comment]
cc @freehan

**Comment by freehan** [comment]
I thought `cluster.local` is already the default. cc @bowei

**Comment by CaoShuFeng** [comment]
@freehan 
Before this change, we get this in container:
$ sudo docker exec 7cd7 hostname -f
name1.subdomain.default.svc.
After this change， we get this:
$ sudo docker exec 3db hostname -f
name1.subdomain.default.svc.cluster.local

**Comment by bowei** [comment]
`cluster.local` is the default that is generated by the standard setup scripts. How was your cluster setup? The flag should not be empty string.

Also FQDN must end with dot. http://www.dns-sd.org/trailingdotsindomainnames.html

**Comment by CaoShuFeng** [comment]
> How was your cluster setup? 
I write my own systemd service file to start up kubelet. I didn't set --cluster-domain flag, so it'a an empty string.

**Comment by bowei** [comment]
I think the proper change should be to error on startup if the --cluster-domain is empty string...

**Comment by CaoShuFeng** [comment]
@bowei 
> I think the proper change should be to error on startup if the --cluster-domain is empty string...

Thanks for your review. I tried your suggestion. But I found that it's legal to have an empty "cluster-domain" according to the help message. 
_`Domain for this cluster.  If set, kubelet will configure all containers to search this domain in addition to the host's search domains`_
And --cluster-domain also effects dns config(/etc/resolv.conf) of containers. So, I prefer not to touch this config.
With this change, we emit an WARNING event to users rather than use an invalid FQDN.

I will also doc the new behavior in the following doc if this pr is OK:
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

Please review again.

**Comment by bowei** [comment]
Looking at that flag comment, it then seems that the correct behavior would be to not manipulate the search paths at all if it is set to empty. Shouldn't that be the fix?

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by CaoShuFeng** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by CaoShuFeng** [comment]
@k8s-bot pull-kubernetes-unit test this

**Pull request closed without merging**
