### PR TITLE
1.30: Clean up PersistentVolumeLabel admission plugin

### PR DESCRIPTION
**Pull request by jsafrane**
This is a manual fix of https://github.com/kubernetes/kubernetes/issues/124504 in release-1.30 branch.

https://github.com/kubernetes/kubernetes/issues/124504 was fixed in master by removing the admission plugin. IMO it's not a good idea to remove the plugin in already released version, so cleaning up the admission not to use the removed cloud provider.
 
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:
Azure and vSphere cloud providers were removed in v1.30. Remove their usage from `PersistentVolumeLabel` admission plugin, otherwise the admission plugin refuses creation of in-tree AzureDisk or vSphere volume.

Related to https://github.com/kubernetes/kubernetes/issues/124504, just fixing it in 1.30.

#### Does this PR introduce a user-facing change?

```release-note
Fixed a 1.30 regression where the PersistentVolumeLabel admission plugin rejects in-tree Azure Disk and vSphere PersistentVolumes.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
The admission plugin is not on by default… isn't the more correct adjustment for azure / vsphere clusters to not enable it in 1.30+?

what happens if it is enabled in those clusters with this PR removing the azure / vsphere implementations?

**Comment by jsafrane** [comment]
@liggitt we're removing the admission plugin in 1.31: https://github.com/kubernetes/kubernetes/issues/124504

And AWS has been removed from the admission plugin in 1.27 (?) without anyone noticing. I admit, it should have been handled (and announced) better.

**Pull request merged**
