### PR TITLE
Proposal: Add HyperContainer runtime

### PR DESCRIPTION
**Pull request by feiskyer**
This PR adds a proposal for integrating [HyperContainer](http://hypercontainer.io) runtime via CRI.

CC @dchen1107 @kubernetes/sig-node

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33720)

### CODE REVIEW

**Comment by brendandburns** [comment]
I don't have any problem with the content here, but I don't really think that this needs a proposal.

Once this is fully implemented, a "how-to" document would be great, but I think that the bulk of this proposal is covered in the general description of the CRI and the rest is covered in frakti itself.

@dchen1107 for a second opinion.

**Comment by yujuhong** [comment]
@brendandburns I think @feiskyer wants the repository to go through the formal incubator process, which [requires a proposal](https://github.com/kubernetes/community/blob/master/incubator.md#entering-incubation). It might be a bit strange since "frakti" dated before the incubator process, but most CRI integrations has gone or is going through the same process.

**Comment by feiskyer** [comment]
> I think @feiskyer wants the repository to go through the formal incubator process, which requires a proposal. It might be a bit strange since "frakti" dated before the incubator process, but most CRI integrations has gone or is going through the same process.

@brendandburns @yujuhong Yes, just want to start an incubator process for HyperContainer integration, and frakti will be moved to kubernetes-incubator as documented at [incubator.md](https://github.com/kubernetes/community/blob/master/incubator.md#existing-repos).

**Comment by brendandburns** [comment]
Ok, fine with me I guess, I looked around and I didn't see a similar doc for `rkt` so I was confused.

LGTM.

**Pull request merged**
