### PR TITLE
Allow setting the Host header in a httpGet probe

### LINKED ISSUE #24288: httpHeaders in httpGet probe does not work for Host header.
I noticed that httpHeaders were added to the httpGet probe in #20116 to fix #14713

Sadly the httpHeaders addition to the httpGet probe does function correctly for all headers *except* the `Host` header.  I think this must be to do with the way `net/http` make a special case of the Host header [for example](https://groups.google.com/forum/#!topic/golang-nuts/pvG-9DSkKaw) [and](https://golang.org/pkg/net/http/#Request).

I have some code I used to debug the issue that I can share if needed.

### PR DESCRIPTION
**Pull request by errm**
Fixes #24288

### CODE REVIEW

**Comment by errm** [comment]
I signed it!

**Comment by lavalamp** [comment]
LGTM, thanks.

**Comment by lavalamp** [comment]
I kicked travis, it's not clear why it failed.

**Comment by lavalamp** [comment]
ok to test

**Comment by errm** [comment]
Rebased on master ...

**Comment by errm** [comment]
@lavalamp looks like this just needs your lgtm back . . .

**Comment by lavalamp** [comment]
LGTM

**Comment by errm** [comment]
Is this something that we might want to cherry pick to 1.2 as the documentation suggests that it works?

**Comment by roberthbailey** [comment]
I've labeled this P1 to try and get it merged into the master branch today so that it can be cherry picked.

**Comment by errm** [comment]
Looks like this is related to #19997, can someone request a retest please?

**Comment by bprashanth** [comment]
@k8s-bot test this github issue: #19997

**Comment by zmerlynn** [comment]
@errm: Cherrypick-approved. We're trying to get a 1.2.3 out the door soon, so please create a cherrypick PR tomorrow if possible. (If not, I may do it.)

**Comment by errm** [comment]
@zmerlynn ok cherrypick pr created . . .

**Comment by zmerlynn** [comment]
@errm: Thanks!

**Pull request merged**
