### PR TITLE
Fix MaxAge default audit log option

### PR DESCRIPTION
**Pull request by tallclair**
Fix typo in flag default.

```release-note
NONE
```

### CODE REVIEW

**Comment by stewart-yu** [comment]
I think update `kubernetes/apiserver` repo better. any misunderstand?

**Comment by tallclair** [comment]
@stewart-yu `kubernetes/apiserver` is automatically synced from the staging directory in `kubernetes/kubernetes`. See https://github.com/kubernetes/apiserver#where-does-it-come-from

**Pull request merged**
