### PR TITLE
kubenet_linux: remove unused constant defaultIPAMDir

### PR DESCRIPTION
**Pull request by mattnworb**
was removed in #62212

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Removes an unused constant (which happens to have a link that is now a 404 since the CNI plugins were moved to another Github repo).

**Special notes for your reviewer**:
I originally opened #81607 to fix the link but it was pointed out that the constant is not used anymore.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

looks good from the sig-node side :)

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by mattnworb** [comment]
had to rebase on master in order to be able to satisfy

```
Some packages in hack/.staticcheck_failures are passing staticcheck. Please remove them.

  pkg/kubelet/dockershim/network/kubenet
```

as I believe those checks were introduced after my commit was made

**Pull request closed without merging**
