### PR TITLE
Implement RawConfig of DirectClientConfig

### LINKED ISSUE #87554: [client-go] Can't override config values
original issue kubernetes/client-go#735

**What happened**:

I am loading my local kubeconfig which contains multiple clusters and contexts. The default context is "prod" and one of the config values I want to override is the `CurrentContext`

```golang
clientConfig := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
		&clientcmd.ClientConfigLoadingRules{ExplicitPath: "/Users/me/.kube/config"},
		&clientcmd.ConfigOverrides{
			CurrentContext: "stage",
		})

	rawConfig, _ := clientConfig.RawConfig()
	log.Printf(rawConfig.CurrentContext) // outputs "prod" instead of "stage"
```

**What you expected to happen**:
CurrentContext="stage"
```golang
	log.Printf(rawConfig.CurrentContext) // stage
```
**How to reproduce it (as minimally and precisely as possible)**:
use code above

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.2
- Cloud provider or hardware configuration: localhost
- OS (e.g: `cat /etc/os-release`): macOS
- Kernel (e.g. `uname -a`): Darwin ....local 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by vvelikodny**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Implements `RawConfig()` for `DirectClientConfig` with overrides. Now just return config without overrides.

**Which issue(s) this PR fixes**:

Fixes #87554

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by fedebongio** [comment]
/assign @deads2k 
thank you!

**Comment by deads2k** [comment]
@soltysh as I recall this is most frequently used in the CLI.   Can you inspect usage and see what's expected?  The fact that ClientConfig and RawConfig return different values is somewhat unexpected, but after all these years may actually be relied upon in spite of whatever the docs specify.

**Comment by harveyxia** [comment]
Any updates on this PR?

**Pull request closed without merging**
