### PR TITLE
Automated cherry pick of #71990: fix kubelet log flushing issue in azure disk

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #71990 on release-1.13.

#71990: fix kubelet log flushing issue in azure disk

### CODE REVIEW

**Comment by andyzhangx** [comment]
`pull-kubernetes-verify` failed since we enter into 2019 now:
```
I0103 01:23:54.071] -Copyright 2019 The Kubernetes Authors.
I0103 01:23:54.071] +Copyright 2018 The Kubernetes Authors.
I0103 01:23:54.072]  
I0103 01:23:54.072]  Licensed under the Apache License, Version 2.0 (the "License");
I0103 01:23:54.072]  you may not use this file except in compliance with the License.
I0103 01:23:54.085] +++ exit code: 1
I0103 01:23:54.089] +++ error: 1
I0103 01:23:54.118] FAILED   verify-cloudprovider-gce.sh	9s
```

**Comment by tpepper** [comment]
Aha good catch I don't know how I missed that in the failed test log...it was right in front of me!

**Comment by tpepper** [comment]
@andyzhangx just rerunning the test isn't going to help

Master branch has changed this code path in https://github.com/kubernetes/kubernetes/pull/72038 and I think we need SIG Cloud Provider's input on the right path fixing the 1.13 branch.

**Comment by tpepper** [comment]
In theory you might could run hack/update-cloudprovider-gce.sh and add the changes as a commit in this PR.  If all it does is change the copyright header, I guess that's ok even though this is silly brittleness.

**Comment by tpepper** [comment]
Confirmed ./hack/update-cloudprovider-gce.sh does only modify the copyright header.

**Pull request merged**
