### PR TITLE
Automated cherry pick of #120731: Fixing CurrentReplicas and CurrentRevision in

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
Cherry pick of #120731 on release-1.28.

#120731: Fixing CurrentReplicas and CurrentRevision in

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by adilGhaffarDev** [comment]
cc @mimowo @soltysh @aleksandra-malinowska

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/triage accepted
/priority backlog

**Comment by mimowo** [comment]
/test pull-kubernetes-e2e-gce 
Seem unrelated failure

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
