### PR TITLE
 Removed containers are not always waiting

### LINKED ISSUE #54499: Pods moving from Succeeded to Pending
After https://github.com/kubernetes/kubernetes/pull/53233, we observed pods moving from phase `Succeeded` to `Pending`.  Presents on master and release-1.8 as it was picked in https://github.com/kubernetes/kubernetes/pull/53422

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - command:
    - bash
    - -c
    - trap 'excode=$?; trap "" EXIT; cmd; echo $excode' EXIT HUP INT QUIT PIPE TERM;
      sleep 5
    env:
    image: centos:centos7
    imagePullPolicy: IfNotPresent
    name: test-container 
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
```
test script
```
kubectl create -f pod.yaml; sleep 3; kubectl delete -f pod.yaml
```
`oc` has an `observe` command for basically doing a CLI watch
```
oc observe pods --output=gotemplate -a '{{.}}' | grep phase
```
or you can look in the kubelet log to see the phase transition from `Succeeded` to `Pending`

Thanks to @joelsmith @frobware for helping isolate this :+1: 

@dashpole @derekwaynecarr @smarterclayton 

/sig node

### PR DESCRIPTION
**Pull request by dashpole**
fixes #54499 
The issue was that a container that is removed (during pod deletion, for example), is assumed to be in a "waiting" state.
Instead, we should use the previous container state.
Fetching the most recent status is required to ensure that we accurately reflect the previous state.  The status attached to a pod object is often stale.

I verified this by looking through the kubelet logs during a deletion, and verifying that the status updates do not transition from terminated -> pending.

cc @kubernetes/sig-node-bugs @sjenning @smarterclayton @derekwaynecarr @dchen1107 

```release-note
Fix an issue where pods were briefly transitioned to a "Pending" state during the deletion process.
```

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
commented on the issue where i meant the pr...

can we also do the following:
"it would be good if syncPod in status manager protected against an invalid transfer of phase..."

prior to calling updateStatus?  if it detects an invalid state transition, panic?

**Comment by sjenning** [comment]
confirmed fix, lgtm

**Comment by joelsmith** [comment]
I think k8s-merge-robot misinterpreted @sjenning's intent and closed this when #54597 merged. Could you re-open this @dashpole?

**Comment by smarterclayton** [comment]
> can we also do the following: "it would be good if syncPod in status manager protected against an invalid transfer of phase..."

I would like to also potentially guard or flag an error on the API server.  If we prevent the transition, we could break components in unexpected ways, but if we don't prevent the transition, we can break EVERY workload controller.

**Comment by sjenning** [comment]
@smarterclayton 

> I would like to also potentially guard or flag an error on the API server. If we prevent the transition, we could break components in unexpected ways, but if we don't prevent the transition, we can break EVERY workload controller.

I don't have a problem reopening #54530 (actually have to create a new PR now because branch changed :disappointed:)

Did you see @dchen1107 concern there?
 https://github.com/kubernetes/kubernetes/pull/54530#issuecomment-339497577

**Comment by derekwaynecarr** [comment]
i think @dchen1107 concern was not that validation was bad, but it alone was not sufficient as the kubelet would still have been unhappy.  now that we have the kubelet checking, the fix identified, adding another guard on the apiserver itself also seems fine to me.

**Comment by dchen1107** [comment]
+1 on https://github.com/kubernetes/kubernetes/pull/54593#issuecomment-339687702  Once validation code is included, both API server and Kubelet will perform the same checking.

**Pull request merged**
