### PR TITLE
Correct optional/omitempty indicator on webhook cabundle

### LINKED ISSUE #69590: CABundle should not be required in Webhook ClientConfig
Rancher users seem to use Let's Encrypt to expose their kube-apiserver. This means that their kubeconfig file has no client-ca. Any custom controller that uses self-hosted EAS to implement admission webhooks has no place to look for CABundle.

But CABundle is a required field for Webhook ClientConfig . https://github.com/kubernetes/api/blob/e3c5c37695fbce2b0b46845e3bb4806c4b8faf47/admissionregistration/v1beta1/types.go#L290

We use the self-hosted webhook pattern shown in https://github.com/openshift/kubernetes-namespace-reservation with our tools . This makes installing such tools in Rancher cluster very cumbersome.

`CABundle` should be an optional field to indicate that webhook server might be using a trusted certificate.

xref: https://github.com/kubedb/project/issues/309

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #69590

**Does this PR introduce a user-facing change?**:
```release-note
The caBundle and service fields in admission webhook API objects now correctly indicate they are optional
```

### CODE REVIEW

**Comment by liggitt** [comment]
/assign @lavalamp @deads2k 
for aggregator package approval

**Comment by tamalsaha** [comment]
Thanks for fixing the bug @liggitt . Does this pass the bar for cherry picking in previous versions?

**Comment by liggitt** [comment]
> Does this pass the bar for cherry picking in previous versions?

I wouldn't think so, since the issue can be worked around by including this in your manifest: `caBundle: ""`

**Comment by lavalamp** [comment]
I'm not sure, this change is pretty small and it does fix a bug, I'd
probably approve a CP? If it depends on other larger changes then I'd agree
it's not a good candidate for a CP.

**Comment by ramnes** [comment]
@liggitt Do I understand correctly that with this PR merged in, an empty `caBundle` value should be equivalent to a `caBundle` that contains `$(kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}')` (as seen [here](https://github.com/morvencao/kube-mutating-webhook-tutorial/blob/ccb27142f523142601920086d48a0fc0e2971a27/deployment/webhook-patch-ca-bundle.sh#L9))?

If so, how to explain that I end up with errors like `x509: certificate signed by unknown authority` without `caBundle`, whereas it works correctly when specified?

**Comment by liggitt** [comment]
> @liggitt Do I understand correctly that with this PR merged in, an empty `caBundle` value should be equivalent to a `caBundle` that contains `$(kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}')` (as seen [here](https://github.com/morvencao/kube-mutating-webhook-tutorial/blob/ccb27142f523142601920086d48a0fc0e2971a27/deployment/webhook-patch-ca-bundle.sh#L9))?

no. an empty caBundle means the apiserver should use the system trust roots to verify the webhook's serving certificate.

**Comment by liggitt** [comment]
From https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.15/#webhookclientconfig-v1beta1-admissionregistration-k8s-io:

> `caBundle` is a PEM encoded CA bundle which will be used to validate the webhook's server certificate. If unspecified, system trust roots on the apiserver are used.

**Comment by ramnes** [comment]
Oh! You mean certificates in `/etc/ssl/certs` basically, right? Then would you consider it a good practice to add a cluster CA there?

**Comment by ramnes** [comment]
It seems pretty inconvenient to me that a webhook without `caBundle` can't be called even if it uses certificates that have been signed by the cluster's CSR mechanism itself.

**Comment by liggitt** [comment]
> Oh! You mean certificates in `/etc/ssl/certs` basically, right?

Yeah, or your platform's equivalent

> Then would you consider it a good practice to add a cluster CA there?

It could, depending on your deployment. If an API server is running in an image and is the only thing in the image, injecting a cluster CA could make sense.

> It seems pretty inconvenient to me that a webhook without caBundle can't be called even if it uses certificates that have been signed by the cluster's CSR mechanism itself.

The CSR API does not guarantee a single signer, and does not guarantee what audiences accept certs signed by it. See https://github.com/kubernetes/kubernetes/issues/69836 for a list of items  that need further clarification before graduating that API.

**Comment by ramnes** [comment]
Thanks a bunch for the quick answers, it's much more clear now.

One last question: would it make sense to modify the API server so that it internally check webhooks certificates against its own CA, on top of its system trusted roots?

**Comment by liggitt** [comment]
> would it make sense to modify the API server so that it internally check webhooks certificates against its own CA

the API server doesn't have a CA... controllers running outside the API server as clients sign the CSR API objects

**Pull request merged**
