### PR TITLE
Add IPv6 family compatibility for the e2e tests

### PR DESCRIPTION
**Pull request by sstoner**
**What type of PR is this?**

> /kind failing-test

**What this PR does / why we need it**:

IPv6 family should be supported when we are combining Host and Port.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/assign @aojea
/unassign
We should really clarify that bot comment, approval is meant to happen after initial review / lgtm by the auto-assigned reviwers.

**Comment by aojea** [comment]
I think is missing some imports

```
/b/f/w/test/e2e/auth/node_authn.go:64:160: undefined: strconv
/b/f/w/test/e2e/auth/node_authn.go:90:31: undefined: strconv
```

**Comment by sstoner** [comment]
> I think is missing some imports
> 
> ```
> /b/f/w/test/e2e/auth/node_authn.go:64:160: undefined: strconv
> /b/f/w/test/e2e/auth/node_authn.go:90:31: undefined: strconv
> ```

sorry for stupid mistake. I have amended this commit

**Comment by aojea** [comment]
/lgtm
by the way, are we exercising these tests with IPv6 or is there a plan to do it?

**Comment by sstoner** [comment]
> /lgtm
> by the way, are we exercising these tests with IPv6 or is there a plan to do it?

I have tested these patch on our IPv6 clusters 

Do you mean exercising these on the CI pipeline? Maybe we need an IPv6 environment ?

**Comment by aojea** [comment]
> Do you mean exercising these on the CI pipeline? Maybe we need an IPv6 environment ?

we do have an "IPv6 environment with" kind `pull-kubernetes-e2e-kind-ipv6`

anyway, if you give me the regex I can try to add it to the job

**Comment by sstoner** [comment]
> > Do you mean exercising these on the CI pipeline? Maybe we need an IPv6 environment ?
> 
> we do have an "IPv6 environment with" kind `pull-kubernetes-e2e-kind-ipv6`
> 
> anyway, if you give me the regex I can try to add it to the job

        # TODO(bentheelder): reduce the skip list further
        - name: SKIP
          value: \[Slow\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|PodSecurityPolicy|LoadBalancer|load.balancer|In-tree.Volumes.\[Driver:.nfs\]|PersistentVolumes.NFS|Simple.pod.should.support.exec.through.an.HTTP.proxy|subPath.should.support.existing

These fix-url tests are contained in the regex `\[Slow\]|\[Feature:.+\]`. The regex includes too many tests... We can just focus on it. And these fix-url tests need not only IPv6 support, but also others, like externalIP...  

I think we can't reduce the skip list in this time..

**Pull request closed without merging**
