### PR TITLE
add a default mtu value for kube-ipvs0

### LINKED ISSUE #68546: kube-proxy ipvs auto detect network interface mtu
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
> /kind feature

**What happened**:

kube-proxy ipvs mode do not auto detect mtu of network interface,  when high qps some time will lost

network interface 
```
ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65520 qdisc pfifo_fast state UP group default qlen 256
    link/infiniband 80:00:02:08:fe:80:00:00:00:00:00:00:00:21:28:00:01:cf:0f:67 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
    inet 172.25.52.237/24 brd 172.25.52.255 scope global ib0
       valid_lft forever preferred_lft forever
    inet6 fe80::221:2800:1cf:f67/64 scope link 
       valid_lft forever preferred_lft forever
``` 
kube-ipvs interface
```
kube-ipvs0: <BROADCAST,NOARP> mtu 1500 qdisc noop state DOWN group default 
    link/ether 86:0f:87:02:ad:d7 brd ff:ff:ff:ff:ff:ff
    inet 10.233.0.1/32 brd 10.233.0.1 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.233.39.119/32 brd 10.233.39.119 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.233.0.3/32 brd 10.233.0.3 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.233.11.220/32 brd 10.233.11.220 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.233.10.124/32 brd 10.233.10.124 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.233.60.40/32 brd 10.233.60.40 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
    inet 10.233.43.212/32 brd 10.233.43.212 scope global kube-ipvs0
       valid_lft forever preferred_lft forever
```

cilium interface
```
19: cilium_net@cilium_host: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 65520 qdisc noqueue state UP group default qlen 1000
    link/ether de:25:c6:78:fb:8e brd ff:ff:ff:ff:ff:ff
    inet6 fe80::dc25:c6ff:fe78:fb8e/64 scope link 
       valid_lft forever preferred_lft forever
20: cilium_host@cilium_net: <BROADCAST,MULTICAST,NOARP,UP,LOWER_UP> mtu 65520 qdisc noqueue state UP group default qlen 1000
    link/ether 2a:cc:75:9f:1d:97 brd ff:ff:ff:ff:ff:ff
    inet 10.234.2.1/32 scope link cilium_host
       valid_lft forever preferred_lft forever
    inet6 fc00::10ca:1/128 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::28cc:75ff:fe9f:1d97/64 scope link 
       valid_lft forever preferred_lft forever
21: cilium_vxlan: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65470 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ether b6:95:03:4f:d3:98 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::b495:3ff:fe4f:d398/64 scope link 
       valid_lft forever preferred_lft forever
79: cilium_health@if78: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65520 qdisc noqueue state UP group default qlen 1000
    link/ether 12:0d:e6:1e:70:fb brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::100d:e6ff:fe1e:70fb/64 scope link 
       valid_lft forever preferred_lft forever
85: lxc9e960@if84: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65520 qdisc noqueue state UP group default qlen 1000
    link/ether 36:f0:07:66:8e:de brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::34f0:7ff:fe66:8ede/64 scope link 
       valid_lft forever preferred_lft forever
```

**What you expected to happen**:

ipvs interface mtu update according network interface

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz 48 core
memory 64G

network:
6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65520 qdisc pfifo_fast state UP group default qlen 256
    link/infiniband 80:00:02:08:fe:80:00:00:00:00:00:00:00:21:28:00:01:cf:0f:67 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
    inet 172.25.52.237/24 brd 172.25.52.255 scope global ib0
       valid_lft forever preferred_lft forever
    inet6 fe80::221:2800:1cf:f67/64 scope link 
       valid_lft forever preferred_lft forever

- OS (e.g. from /etc/os-release):
CentOS Linux release 7.5.1804 (Core) 

- Kernel (e.g. `uname -a`): 
4.18.6-1.el7.elrepo.x86_64

- Install tools:
- Others:
cilium network 1.2.1

### PR DESCRIPTION
**Pull request by Lion-Wei**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #68546

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by Lion-Wei** [comment]
xref: #71202

**Comment by m1093782566** [comment]
Is there any auto-detect approach?

**Pull request closed without merging**
