### PR TITLE
remove unused variable in e2e test[kubectl.go]

### PR DESCRIPTION
**Pull request by heqg**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
remove unused variable in e2e test[kubectl.go] 

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

```release-note
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Comment by dougsland** [comment]
indeed, looks correct.
/lgtm

**Review by dixudx — APPROVED** [review]
/lgtm
/approve

**Comment by oomichi** [comment]
Those have been removed already since 71f33cf8e1a41a539bef2e47d12472be0d40b422
So we don't need this PR at this time..

/close

**Pull request closed without merging**
