### PR TITLE
lavalamp is taking a long break

### PR DESCRIPTION
**Pull request by lavalamp**
As announce on the API Machinery and dev lists, I'm taking a long break.

/kind cleanup

Release note:

```release-note
NONE
```

I'm here for another day so:

/hold

/assign @liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
> pull-kubernetes-node-e2e-containerd — Job failed.

containerd is as sad as I am 😢

**Comment by MadhavJivrajani** [comment]
/retest
Thank you Daniel ❤️

**Comment by lavalamp** [comment]
/hold cancel

❤️

**Pull request merged**
