### PR TITLE
Backport PRs needed to support IP alias migration from routes on GCP in Release 1.9 branch

### PR DESCRIPTION
**Pull request by jingax10**
**What this PR does / why we need it**:

PR backports #56132  #56260  #57520  #58845  #59361  #59423, which are needed to support IP alias migration from routes on GCP in Release 1.9 branch

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

#58844

**Special notes for your reviewer**:
The changes are only applied to GCP.

**Release note**:

```release-note
Allow node IPAM controller to configure IPAMFromCluster mode to use IP aliases instead of routes in GCP.
```

### CODE REVIEW

**Comment by mbohlool** [comment]
This is not an automatic cherrypick and it is a big change. We need to know answer to these questions:

- What bug does this fix? please list issues.
- What is the scope of users affected? I assume GCP users.
- How big is the impact on affected users?
- How have you verified the fix works and is safe? new tests?

**Comment by jingax10** [comment]
- This PR is for a feature (allow GKE cluster to migrate from using routes to IP aliases) and there are a couple of issues filed to fix issues caused by first commit (e.g., #58844).
- This PR applies to GCP only.
- No impact for the current GCP users, but it will gate other feature releases depending on this one.
- Issued are found by manual tests besides the OSS CI one (#58844) so far, e.g., to use Beta API (#59361), patch request change as GCE stack changes (#59423). Once GKE changes are in place, we will have a ci internally and then in OSS.

Notice that. one big commit is to update google.golang.org/api repo, as we need to invoke relevant GCE API by Beta instead of Alpha, requiring to whitelist each customer's project directly or indirectly use the feature.

**Comment by bowei** [comment]
/lgtm

You may want to add to the PR summary that this is mostly a bugfix.

**Comment by mbohlool** [comment]
Thanks for providing answers. Please populate the PR first message with as much information from these answers as you can (e.g. issue numbers in fixes #...). The answers looks good to me for cherrypick, I will wait for the PR to be approved by usual channels.

**Pull request merged**
