### PR TITLE
add crash protection to wait functions that were missing it

### PR DESCRIPTION
**Pull request by deads2k**
We already protect most of the functions like `wait.Until` with crash protection. This fixes the ones that were missing.

/kind bug
/priority important-soon
@kubernetes/sig-api-machinery-bugs 

```release-note
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
Yeah I think we should do this consistently if we're going to do it.

**Comment by deads2k** [comment]
it would be pretty impressive in we relied on crashing...

/retest

**Comment by spiffxp** [comment]
First run of ci-kubernetes-e2e-gci-gce after this merged: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1220221095844515843

It passed, but there's lots of observed panics that look like this:
```
I0123 05:53:41.290] Jan 23 05:53:41.284: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
I0123 05:53:41.290] E0123 05:53:41.284658    9326 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
I0123 05:53:41.291] goroutine 179 [running]:
I0123 05:53:41.291] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x41cb4c0, 0x7c949c0)
I0123 05:53:41.291] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
I0123 05:53:41.291] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
I0123 05:53:41.292] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
I0123 05:53:41.292] panic(0x41cb4c0, 0x7c949c0)
I0123 05:53:41.292] 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
I0123 05:53:41.292] k8s.io/kubernetes/test/e2e/framework.AllNodesReady.func1(0xc002b00c50, 0xc000314000, 0x7f33d9c4a6d0)
I0123 05:53:41.293] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:1351 +0x5e
I0123 05:53:41.293] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc002b00de0, 0xbedc00, 0x0, 0x0)
I0123 05:53:41.293] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:209 +0x6f
I0123 05:53:41.293] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.pollImmediateInternal(0xc00308bb60, 0xc002b00de0, 0xc00308bb60, 0x1)
I0123 05:53:41.294] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:344 +0x2f
I0123 05:53:41.294] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.PollImmediate(0x77359400, 0x29e8d60800, 0xc002b00de0, 0x33, 0xc002b00da0)
I0123 05:53:41.294] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:340 +0x4d
I0123 05:53:41.294] k8s.io/kubernetes/test/e2e/framework.AllNodesReady(0x0, 0x0, 0x29e8d60800, 0x4abb9dc, 0x6)
I0123 05:53:41.294] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:1348 +0x17f
I0123 05:53:41.295] k8s.io/kubernetes/test/e2e/framework.(*Framework).AfterEach(0xc000c00b40)
I0123 05:53:41.295] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:457 +0x43c
```

**Comment by lavalamp** [comment]
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L1351

Probably something on this line is nil?

Either this should have crashed the process, and we should set ReallyCrash to true for the process, or it was already happening and this just made it visible.

**Comment by BenTheElder** [comment]
found this hunting for the cause of these logs :-)
this is happening very heavily in `pull-kubernetes-e2e-kind` since ~ the same time frame.

**Comment by liggitt** [comment]
This means that things that were catching their own panics higher up now get duplicate logging, or fail to receive panics? Don't some test frameworks use panics as flow control?

In general, I would only have expected us to add panic handling in places we spawned goroutines

**Comment by liggitt** [comment]
I'm not sure this is a net positive change… I'd consider reverting it

**Comment by neolit123** [comment]
is this job passing a valid kubeconfig to the framework?

all panics are because AllNodesReady is receiving a nil client set.

the trace suggests AfterEach() and if the client set is nil in AfterEach(), this means it never go a client in BeforeEach:
https://github.com/kubernetes/kubernetes/blob/5b77616374c54f29ffea1d3c66b541332e0f45e6/test/e2e/framework/framework.go#L199
unless...a test is updating the client set to nil (public field).

i think AfterEach is lacking the ClientSet != nil handling, regardless.

**Comment by neolit123** [comment]
all panics seem to originate from callers in `test/e2e/storage/testsuites/*.go`.

**Comment by BenTheElder** [comment]
The job kubeconfig is being used to pass all tests so I would say that it
is valid 🙃
The obtuse control flow in e2e.test never ceases to bring fun.

**Comment by neolit123** [comment]
> The job kubeconfig is being used to pass all tests so I would say that it
is valid

this is true. tests are passing and there are no errors on config loading.

> The obtuse control flow in e2e.test never ceases to bring fun.

BeforeEach / AfterEach are ginkgo semantics. what the framework is lacking is proper protection of public fields.

**Comment by neolit123** [comment]
i will send a PR to add the proper error handling in AfterEach for the client sets.

**Comment by neolit123** [comment]
https://github.com/kubernetes/kubernetes/pull/87511/files

**Comment by lavalamp** [comment]
I think finding the unexpected test framework behavior was worth it.

**Pull request merged**
