### PR TITLE
etcd: Update to version 3.5.12

### PR DESCRIPTION
**Pull request by bzsuni**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Update etcd to version [3.5.12](https://github.com/etcd-io/etcd/releases/tag/v3.5.12)
#### Does this PR introduce a user-facing change?

```release-note
Update etcd to version 3.5.12
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
none
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/approve

**Comment by pacoxu** [comment]
/lgtm
/assign @liggitt @ahrtr

See https://github.com/kubernetes/kubernetes/pull/123069#issuecomment-1928731751 This PR may need cherry-pick.

**Comment by liggitt** [comment]
/unassign
/assign @serathius @ahrtr
for sig-etcd ack

**Comment by humblec** [comment]
@ahrtr @serathius  if you are in agreement , we ( @bzsuni ) can file back port PRs too .

**Pull request merged**
