### PR TITLE
Revert "remove cluster logging e2e test from flaky suite"

### PR DESCRIPTION
**Pull request by freehan**
Reverts kubernetes/kubernetes#18910

### CODE REVIEW

**Comment by bprashanth** [comment]
why? you already have a fix right? I think the test infra team is trying to obliterate [Flaky]. If you need time to fix the problem but believe it's well understood, suggest moving this to [Feature]. 

https://github.com/kubernetes/kubernetes/blob/20273cf961a1ec87db02d370e8599d688464191f/docs/devel/e2e-tests.md#kinds-of-tests

**Comment by freehan** [comment]
Alright, I will move it to feature.

**Comment by bprashanth** [comment]
Be careful though, only move it if you expect it to keep flaking. What's the issue (or are you still debugging)?

**Comment by ihmccreery** [comment]
See https://github.com/kubernetes/kubernetes/pull/20453 for usage of `[Flaky]`.

**Comment by ihmccreery** [comment]
i.e.:

> ... and we have decided that it's too hard to fix in the short term (e.g. it's going to take a full engineer-week)

@bprashanth's question above is the right one.

**Comment by freehan** [comment]
This test is very shaky because it depends on a few third party components. 
For instance, Elasticsearch is very sensitive to disruption. I never have a problem on my own test cluster if I run this test alone. I have seen cases where other tests could disrupt ES and gets it into faulty state.

**Comment by bprashanth** [comment]
Hmm, if you can't repro can you confirm it has nothing to do with the pr? it's failed 3 times on https://github.com/kubernetes/kubernetes/pull/20464. IIRC the test doesn't actually use services right?

**Comment by freehan** [comment]
fluentd is sending logs to elasticsearch-logging service.

**Comment by bprashanth** [comment]
A failure in the cluster addon should show up even outside this test though. does it show up in the logs of the failed runs?

**Comment by freehan** [comment]
Actually the failure is new... It is complaining more log lines show up in the query result than expected.

**Comment by bprashanth** [comment]
are we restarting the pod when we're not supposed to?

**Comment by ihmccreery** [comment]
> I never have a problem on my own test cluster if I run this test alone.

Note that without a `[Serial]` label, we assume that a test can run in parallel with other tests.  Does this test make an assumption that it's the only test running at a given time?

**Comment by freehan** [comment]
@bprashanth  I currently do not have proof for that.

**Comment by bprashanth** [comment]
suggest look through the history of the test to check if this is a regression (if you haven't already). If you only recently move this test *out* of flaky, I'm fine moving it back in and treating the old bug as unresolved.

**Comment by freehan** [comment]
I think it is better to move it back to Flaky. It is causing way too many failures.

**Comment by bprashanth** [comment]
LGTM, please update https://github.com/kubernetes/kubernetes/issues/1787

**Comment by bprashanth** [comment]
I meant https://github.com/kubernetes/kubernetes/issues/17873

**Comment by freehan** [comment]
@k8s-bot unit test this

**Comment by freehan** [comment]
@k8s-bot test this github issue: #20530

**Pull request merged**
