### PR TITLE
Trival fix: update the description on the pod preemption

### PR DESCRIPTION
**Pull request by chendave**
`pod` has the field of `NominatedNodeName` which is different
with `NominatedPod`.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by damemi — APPROVED** [review]
/lgtm

**Comment by chendave** [comment]
cc @Huang-Wei

**Pull request merged**
