### PR TITLE
Kubelet doesn't fight apiserver for cputime on the master.

### PR DESCRIPTION
**Pull request by bprashanth**
The kubelet on the master is hogging a core spinning around in a hot loop doing nothing. This causes watchers to stray out of their windows, forcing unnecessary relisting. 

cpu profiles with/without the change:
- master kubelet without:https://cloud.githubusercontent.com/assets/10927820/8400442/493c43b4-1dd3-11e5-933b-117e55fa9ed2.png
- master kubelet with: https://cloud.githubusercontent.com/assets/10927820/8400445/570b2dfc-1dd3-11e5-9954-f5cdd05a708b.png
- apicalls without: https://cloud.githubusercontent.com/assets/10927820/8400447/6501e856-1dd3-11e5-9304-db576683c350.png
- apicalls with: https://cloud.githubusercontent.com/assets/10927820/8400451/6f0fac02-1dd3-11e5-9c14-51f2130366f1.png

@wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
This is great finding - thanks @bprashanth !

**Comment by wojtek-t** [comment]
LGTM

@davidopp for the first lead to LGTM

**Comment by wojtek-t** [comment]
@dchen1107 for the second lead LGTM

**Comment by davidopp** [comment]
LGTM

**Comment by bprashanth** [comment]
@dchen1107 @quinton-hoole for more lgtms

**Comment by dchen1107** [comment]
lgtm

**Comment by quinton-hoole** [comment]
Awesome!  Thanks for this @bprashanth

**Comment by a-robinson** [comment]
Very nice, @bprashanth!

**Comment by alex-mohr** [comment]
Thanks for fixing this.  Any thoughts on what kind of regression test we could add that would catch similar behavior in the future?  If a kubelet isn't supposed to be using >> X CPU, should we test for that?

**Comment by alex-mohr** [comment]
Cherrypick for 20.2?  #10409

**Comment by quinton-hoole** [comment]
@alex-mohr My opinion is that rather than a test for resource explosion by system components, they should be hard-constrained with respect to resources (using cgroups).  But I believe that this was all postponed to v1.0-post. @dchen1107 FYI.

**Comment by alex-mohr** [comment]
@quinton-hoole Yes, that's probably also true.  But even then, we presumably don't expect kubelet to be always hard-constrained by hitting its cgroup limit -- that'd be a bug with either (a) the resource limit too low or (b) kubelet having unexpectedly high cpu usage?  And as such, an integration and/or e2e test to highlight that bug might be useful?

**Comment by quinton-hoole** [comment]
@alex-mohr Kinda.  Another approach would be to rely on latency metrics to determine whether system components have enough resources.  It would be a totally valid strategy for a system component to tune it's behavior (e.g. frequency of polling loops) according to available resources, and potentially use all of them. We could do either or both of checking that they don't hit their resource limits, or checking that they perform according to spec.

**Pull request merged**
