### PR TITLE
TokenRequestProjections should allow API server to default empty audience

### PR DESCRIPTION
**Pull request by mikedanese**
/kind bug
/sig auth

```release-note
Correctly default Audience in the kubelet for TokenRequestProjections.
```

### CODE REVIEW

**Comment by cjcullen** [comment]
/lgtm

For my curiousity, what breaks with `{""}` compared to `{}`?

**Comment by mikedanese** [comment]
@cjcullen Audiences is defaulted in TokenRequest if it's empty. This results in tokens with "aud":[""]

**Comment by mikedanese** [comment]
For approval:

/assign @jsafrane @saad-ali

**Comment by liggitt** [comment]
lgtm, but should there be a test around  this?

**Comment by mikedanese** [comment]
@liggitt added tests of the defaulting.

**Comment by liggitt** [comment]
does this need cherry-picking to old releases?

**Pull request merged**
