### PR TITLE
Automated cherry pick of #41113

### PR DESCRIPTION
**Pull request by BaluDontu**
Cherry pick of #41113 on release-1.5.

#41113: Fix for Support selection of datastore for dynamic provisioning in vSphere

### CODE REVIEW

**Comment by BaluDontu** [comment]
@dchen1107: Can you please take a look at this PR. Though its a cherry pick request, it doesn't have cherrypick label. 

Can you please add that.

**Comment by kerneltime** [comment]
@k8s-bot ok to test

**Comment by BaluDontu** [comment]
@dchen1107 : This is to cherry pick into 1.5 branch. Can we add cherrypick label, somehow it was not added. 

Also can u check the changes and provide an /lgtm if all is good.

**Comment by dchen1107** [comment]
/lgtm

But are we sure we want to cherrypick this to 1.5 release? I will leave this to @kubernetes/sig-storage-misc to decide. cc/ @saad-ali

**Comment by mwielgus** [comment]
@kubernetes/sig-storage-misc  @saad-ali
Are you ok with merging this to 1.5 ?

**Comment by BaluDontu** [comment]
I have rebased the branch. Can you approve the changes once tests are done. @dchen1107 @saad-ali

**Comment by BaluDontu** [comment]
@k8s-bot verify test this

**Comment by BaluDontu** [comment]
@k8s-bot verify test this

**Comment by BaluDontu** [comment]
@saad-ali @dchen1107 : The jenkins build failures aren't related to my change. Can you verify it, it seems to be failing multiple times.

**Comment by divyenpatel** [comment]
Regarding Jenkins Verification Failure, We see following. Any thing wrong in /go/src/k8s.io/kubernetes/examples/volumes/vsphere/README.md?
We also see `/go/src/k8s.io/kubernetes/examples/` is out of date.

```
I0327 15:57:20.746] Verifying hack/make-rules/../../hack/verify-munge-docs.sh
I0327 15:57:30.476] +++ [0327 15:57:30] Building the toolchain targets:
I0327 15:57:30.476]     k8s.io/kubernetes/hack/cmd/teststale
I0327 15:57:30.477]     k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
I0327 15:57:30.597] +++ [0327 15:57:30] Generating bindata:
I0327 15:57:30.597]     test/e2e/framework/gobindata_util.go
I0327 15:57:31.254] +++ [0327 15:57:31] Building go targets for linux/amd64:
I0327 15:57:31.255]     cmd/mungedocs
I0327 15:57:36.736] /go/src/k8s.io/kubernetes/examples/volumes/vsphere/README.md
I0327 15:57:36.736] ----
I0327 15:57:36.736] remove-whitespace:
I0327 15:57:36.736] not printing failed chunk: too many lines
I0327 15:57:36.736] contents were modified
I0327 15:57:36.737] 
I0327 15:57:36.738] /go/src/k8s.io/kubernetes/examples/ is out of date. Please run hack/update-munge-docs.sh
I0327 15:57:36.740] [0;31mFAILED[0m   hack/make-rules/../../hack/verify-munge-docs.sh	16s
```

**Comment by saad-ali** [comment]
Run munge-docs: `./hack/verify-munge-docs.sh`

**Comment by BaluDontu** [comment]
I ran ./hack/verify-munge-docs.sh and addressed the errors.

**Comment by BaluDontu** [comment]
@dchen1107 @saad-ali : Can you provide an /lgtm as all tests passed now, 
@jingxu97

**Comment by BaluDontu** [comment]
@jingxu97 : I still see, "Submit Queue — Will not auto merge because do-not-merge is present"
Do you need add a auto merge label?

**Comment by mwielgus** [comment]
cleared for merge.

**Comment by BaluDontu** [comment]
@k8s-bot cvm gce e2e test this
@k8s-bot gci gce e2e test this
@k8s-bot gce etcd3 e2e test this

**Comment by BaluDontu** [comment]
@k8s-bot cvm gce e2e test this
@k8s-bot gce etcd3 e2e test this
@k8s-bot gci gce e2e test this

**Pull request merged**
