### PR TITLE
run hack/update-vendor.sh to fix verify master

### LINKED ISSUE #119067: [Failing Test] verify-master
### Which jobs are failing?
master-informing:
- verify-master

### Which tests are failing?
`verify.yamlfmt`

Image

### Since when has it been failing?
07-03 18:11 IST

### Testgrid link
https://testgrid.k8s.io/sig-release-master-blocking#verify-master

### Reason for failure (if possible)
```
Unexpected dirty working directory:
...
!!! [0704 11:10:07]  1: hack/make-rules/../../hack/verify-yamlfmt.sh:30 kube::util::ensure_clean_working_dir(...)
+++ exit code: 1
+++ error: 1
[0;31mFAILED   verify-yamlfmt.sh	0s
```

### Anything else we need to know?
_No response_

### Relevant SIG(s)
/sig

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind failing-test

#### Which issue(s) this PR fixes:

Fixes #119067

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by cpanato — COMMENTED** [review]
/lgtm

**Comment by cpanato** [comment]
Do we need to cherry-pick this to the release branches or do the same there?

**Comment by pacoxu** [comment]
> Do we need to cherry-pick this to the release branches or do the same there?

Let me try. I prefer to re-run the update-vendor on release branches.

**Comment by pacoxu** [comment]
I opened https://github.com/kubernetes/kubernetes/pull/119123 and it seems not needed. ?

**Pull request merged**
