### PR TITLE
[k8s.io/apiserver/pkg/endpoints/filters]: fix `go vet` warning

### PR DESCRIPTION
**Pull request by ideapark**
composite literal uses unkeyed fields

Signed-off-by: Zhou Peng <p@ctriple.cn>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note none

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/skip

the GPU test is not required and has a known failure that is being fixed separately

**Comment by justaugustus** [comment]
Needs rebase

**Comment by iotty** [comment]
since the lint warning go file was deleted, there is no need to fix that warning. i would close this pr.

**Pull request closed without merging**
