### PR TITLE
run update-gofmt when make update

### LINKED ISSUE #76581: Run update-gofmt when make update
**What would you like to be added**:

It will be more convenient to include `update-gofmt.sh` when `make update`.

**Why is this needed**:

Now, contributor need to run `make update` and `hack/update-gofmt.sh` both.
If including `update-gofmt.sh` when `make update`, it will be more convenient.

/sig contributor-experience
/kind feature
/assign

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

Now, contributor need to run `make update` and `hack/update-gofmt.sh` both.
If including `update-gofmt.sh` when `make update`, it will be more convenient.

/sig contributor-experience
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #76581 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
which update script left go files unformatted?

**Comment by neolit123** [comment]
xref b57845341fb2ae7737bb436f2b2f9a67491bf416
/assign @cblecker

**Comment by cblecker** [comment]
/lgtm
/approve

@liggitt I don't think and script did. We still run `hack/verify-gofmt.sh` in the verify job. I think this is just an added convenience, which I'm okay with.

**Pull request merged**
