### PR TITLE
Use Clientset interface in KubeletDeps

### PR DESCRIPTION
**Pull request by apilloud**
**What this PR does / why we need it**:
This replaces the Clientset struct with the equivalent interface for the KubeClient injected via KubeletDeps. This is useful for testing and for accessing the Node and Pod status event stream without an API server.

**Special notes for your reviewer**:
Follow up to #4907

**Release note**:

`NONE`

### CODE REVIEW

**Comment by feiskyer** [comment]
LGTM. Needs rebase.

**Comment by apilloud** [comment]
Rebased and dropped the second patch. That change was taken care of by PR 40710.

**Comment by feiskyer** [comment]
@k8s-bot test this

**Comment by feiskyer** [comment]
LGTM. Waiting CI green.

**Comment by apilloud** [comment]
Pushed a new commit that I believe fixes the test failures. It passes `make test-cmd`. Still struggling to get `test-integration` and `test-e2e` to run locally.

**Comment by feiskyer** [comment]
@k8s-bot test this

**Comment by feiskyer** [comment]
@k8s-bot cri e2e test this

**Comment by apilloud** [comment]
Rebased. The CRI GCE e2e test failure is the same as the one introduced by PR 33684. Haven't found an issue open on it, but everything based on recent master is failing.

**Comment by feiskyer** [comment]
@k8s-bot test this

**Comment by apilloud** [comment]
@derekwaynecarr Waiting for your approval on this. Please take a look.

**Comment by derekwaynecarr** [comment]
@k8s-bot cri e2e test this

**Pull request merged**
