### PR TITLE
Added DNSOptions config option to allow passing options to resolv.conf

### PR DESCRIPTION
**Pull request by SirSepp**
/kind feature

#### What this PR does / why we need it:
This patch allow users pass different DNS options to resolv.conf. This is useful when your kubernetes cluster work along with other infrastructure and your are using DNS. This allow you set ndots to lower values, for example and reduce number of DNS requests. Also this patch doesn't change old behavior with static ndots:5 option, when new option is not prvieded.

#### Does this PR introduce a user-facing change?
Yes, but no any action required.

### CODE REVIEW

**Comment by MrGreenRUS** [comment]
Sorry, I'm waiting for CLA from my company.

**Comment by dims** [comment]
@MrGreenRUS any luck with the CLA?

**Comment by dims** [comment]
This PR needs a CLA to make progress, please see comments above from the CLA bot(s)

**Comment by dims** [comment]
There is a cncf-cla:no label on this PR. Can you please see the bot comments above to fix the CLA? This PR cannot progress unless the bot is happy with the CLA situation

**Comment by khenidak** [comment]
@MrGreenRUS I really appreciate that one. Thank You! While you are getting the CLA thing done...

is this change backed by a KEP? the change potential impact on multiple things and i wanted to make sure that it has been discussed throughly by the community.

**Comment by MrGreenRUS** [comment]
@khenidak sorry for long answer, no, this change made without any KEP. Do I need to create KEP or discuss with community?

**Comment by MrGreenRUS** [comment]
@dims yes and no, company has created CLA, but EasyCLA migrated to new platform and lost our signature, waiting again:(

**Pull request closed without merging**
