### PR TITLE
Enable iptables kube-proxy by default in master

### LINKED ISSUE #3760: use iptables for proxying instead of userspace
I was playing with iptables yesterday, and I protoyped (well, copied from Google hits and mutated) a set of iptables rules that essentially do all the proxying for us without help from userspace.  It's not urgent, but I want to file my notes before I lose them.

This has the additional nice side-effect (as far as I can tell) of preserving the source IP and being a large net simplification.  Now kube-proxy would just need to sync Services -> iptables.  This has the downside of not being compatible with older iptables and kernels.  We had a problem with this before - at some point we need to decide just how far back in time we care about.

This can probably be optimized further, but in basic testing, I see sticky sessions working and if I comment that part out I see ~equal probability of hitting each backend.  I was not able to get deterministic round-robin working properly (with --nth instead of --probability) but we could come back to that if we want.

This sets up a service portal with the backends listed below

```
iptables -t nat -N TESTSVC
iptables -t nat -F TESTSVC
iptables -t nat -N TESTSVC_A
iptables -t nat -F TESTSVC_A
iptables -t nat -N TESTSVC_B
iptables -t nat -F TESTSVC_B
iptables -t nat -N TESTSVC_C
iptables -t nat -F TESTSVC_C
iptables -t nat -A TESTSVC -m recent --name hostA --rcheck --seconds 1 --reap -j TESTSVC_A
iptables -t nat -A TESTSVC -m recent --name hostB --rcheck --seconds 1 --reap -j TESTSVC_B
iptables -t nat -A TESTSVC -m recent --name hostC --rcheck --seconds 1 --reap -j TESTSVC_C
iptables -t nat -A TESTSVC -m statistic --mode random --probability 0.333 -j TESTSVC_A
iptables -t nat -A TESTSVC -m statistic --mode random --probability 0.500 -j TESTSVC_B
iptables -t nat -A TESTSVC -m statistic --mode random --probability 1.000 -j TESTSVC_C

iptables -t nat -A TESTSVC_A -m recent --name hostA --set -j DNAT -p tcp --to-destination 10.244.4.6:9376
iptables -t nat -A TESTSVC_B -m recent --name hostB --set -j DNAT -p tcp --to-destination 10.244.1.15:9376
iptables -t nat -A TESTSVC_C -m recent --name hostC --set -j DNAT -p tcp --to-destination 10.244.4.7:9376

iptables -t nat -F KUBE-PORTALS-HOST
iptables -t nat -A KUBE-PORTALS-HOST -d 10.0.0.93/32 -m state --state NEW -p tcp -m tcp --dport 80 -j TESTSVC
iptables -t nat -F KUBE-PORTALS-CONTAINER
iptables -t nat -A KUBE-PORTALS-CONTAINER -d 10.0.0.93/32 -m state --state NEW -p tcp -m tcp --dport 80 -j TESTSVC
```

### PR DESCRIPTION
**Pull request by thockin**
Fixes #3760

It's time - this should not interfere with any cherry picks at this point.

### CODE REVIEW

**Comment by ncdc** [comment]
@kubernetes/rh-cluster-infra @kubernetes/rh-networking @kubernetes/rh-scalability @smarterclayton

**Comment by smarterclayton** [comment]
Have we had soak time on this across all our deployment targets (different IaaS and OS combos)?

**Comment by thockin** [comment]
I am hoping to get soak by turning it on in master.

**Comment by thockin** [comment]
Now with docs updated.

**Comment by hw-qiaolei** [comment]
Hello @thockin thanks for having done such a wonderful work.

I have some concerns about the two diagrams `services-iptables-overview` and `services-userspace-overview`. My point is that: to make things more clear, **the `Client`, `kube-proxy` and `ServiceIP(iptables)` should be resided on the same`Node`.** For `services-iptables-overview` like below:

```
                |------------------------------------|
                |                          Node      |
                |   |------------|  |-------------|  |      |-----------|
                |   |   Client   |  |  kube-proxy |---------| apiserver |
                |   |------------|  |-------------|  |   |  |-----------|
                |           \             /          |   |
                |            \           /           |   |-- watches Service and Endpoints
                |          |-------------|           |
                |          |  ServiceIP  |           |
                |          |  (iptables) |           |
                |          |-------------|           |
                |            /    |    \             |
                |-----------/-----|-----\------------|
                           /      |      \  random
                  --------/       |       \--------\
                 /                |                 \
|-------------------|  |-------------------|  |-------------------|
| Backen Pod 1      |  | Backen Pod 2      |  | Backen Pod 3      |
| labels: app=MyApp |  | labels: app=MyApp |  | labels: app=MyApp |
| port: 9376        |  | port: 9376        |  | port: 9376        |
|-------------------|  |-------------------|  |-------------------|
```

So far as I know, the ServiceIP(service type: ClusterIP) is virtual, so it cannot be routable, the requests for a `ServiceIP:Port` can only be made from inside the cluster; that means, a request with a destination IP which is a ServiceIP seen by the kube-proxy can only be made from the pods which residents on the same node with the kube-proxy.

The same applies to `services-userspace-overview.png`.

Please correct me if I am wrong. Thanks.

**Comment by timothysc** [comment]
@thockin is the source IP preserved as mentioned in #3760?

**Comment by a-robinson** [comment]
Travis doesn't like this:
```
FAIL: changes needed but not made due to --verify
/home/travis/gopath/src/github.com/kubernetes/kubernetes/docs/ is out of date. Please run hack/update-generated-docs.sh
!!! Error in hack/verify-generated-docs.sh:28
  '"${KUBE_ROOT}/hack/after-build/verify-generated-docs.sh" "$@"' exited with status 1
Call stack:
  1: hack/verify-generated-docs.sh:28 main(...)
Exiting with status 1
make: *** [verify] Error 1
```

**Comment by shettyg** [comment]
I tried this out on a small cluster. The POD is connected to a Linux bridge. The packet (with the destination ip address of a service VIP) hits a PREROUTING entry in iptables and based on probability will choose one of the endpoints for that service and changes the destination IP address of the packet.

So far so good. After this, since the packet's destination IP address is different, a fresh arp lookup is done on the host. So this means that the host needs connectivity to all the POD IP addresses in the cluster. Also it looked like the source mac address of the packet gets changed to that of the host. (So even though the source ip address of the packet remains, the source mac address does change).

Is the above observation the expected behavior?

**Comment by shettyg** [comment]
Please scratch my above observation about source mac address of the packet changing. If the ARP from the host is successful, the packet retains the pods mac address. So all is good. Though the need for the host to be able to reach all the pods in a cluster is pain, but it looks like with iptables PREROUTING, you don't have a choice.

**Comment by alex-mohr** [comment]
@thockin is this for 1.1 such that we should merge soon, or 1.2?

**Comment by piosz** [comment]
```/home/travis/gopath/src/github.com/kubernetes/kubernetes/docs/ is out of date. Please run hack/update-generated-docs.sh```

**Comment by thockin** [comment]
@shettyg this requirement (host can reach pods) is not new - it should have been true in the userspace proxy, too.  It's not ideal, but it is a fallout of using the root netns for iptables to implement VIP.  I'm certainly open to better ideas.

**Comment by thockin** [comment]
@timothysc yes, source IP is preserved within the cluster.

**Comment by thockin** [comment]
@hw-qiaolei I indicated that the components are same-node in the next push.

**Comment by timothysc** [comment]
@kubernetes/sig-big-data fyi.. This "could" potentially help things that leverage akka, and possibly nominal services.  However, I'm in the camp where I'll believe it when I see it.

**Comment by ArtfulCoder** [comment]
This unit test failure is relevant to this PR.
The unit test needs to be updated.


app.Test_getProxyMode (from k8s.io_kubernetes_cmd_kube-proxy_app)

Failing for the past 1 build (Since Failed#1185 )
Took 0 ms.
Error Message

Failed
Stacktrace

server_test.go:67: Case[1] Expected %!t(string=iptables), got %!t(string=userspace)

**Comment by thockin** [comment]
That test passes locally.  I fixed the %t vs %s issue and re-pushed.  Let's see if jenkins fails again.

**Comment by eparis** [comment]
@thockin thanks. Internally we are testing 3 things, all on a single host never hitting a wire. The baseline is the throughput from pod to pod.

Pod - Pod: 100% throughput
Pod - golang proxy - Pod: 36% throughput
Pod - iptables proxy - Pod: 96 % throughput

I'd call that a pretty big win   :)

**Comment by thockin** [comment]
I'm disappointed it's a 4% hit.  I blame the test methodology.

**Comment by eparis** [comment]
I didn't give you error bars/confidence intervals.

**Comment by knobunc** [comment]
The numbers are still a little sloshy... I found an error with the
benchmark, so re-running that before broadcasting more.  So that 4% could
be test methodology ;-)

-ben

**Comment by thockin** [comment]
Jenkins failed on this test again, but it does pass locally.  Will investigate

**Comment by thockin** [comment]
@ixdy the Jenkins Console log shows that a test failed, but it does not show log-lines from the failed test (as does 'make test' locally).  This makes it impossible to debug this test fail.  Help?

**Comment by ixdy** [comment]
@thockin clicking on the test result shows the failure:
```
server_test.go:67: Case[1] Expected "iptables", got "userspace"
server_test.go:67: Case[2] Expected "iptables", got "userspace"
server_test.go:67: Case[4] Expected "iptables", got "userspace"
server_test.go:67: Case[5] Expected "iptables", got "userspace"
server_test.go:67: Case[6] Expected "iptables", got "userspace"
server_test.go:67: Case[8] Expected "iptables", got "userspace"
server_test.go:67: Case[9] Expected "iptables", got "userspace"
server_test.go:67: Case[10] Expected "iptables", got "userspace"
server_test.go:67: Case[11] Expected "iptables", got "userspace"
server_test.go:67: Case[14] Expected "iptables", got "userspace"
server_test.go:67: Case[15] Expected "iptables", got "userspace"
server_test.go:67: Case[18] Expected "iptables", got "userspace"
server_test.go:67: Case[19] Expected "iptables", got "userspace"
```

**Comment by ixdy** [comment]
And from the [verbose test output](https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/pr-logs/20cb041ad1043eca7b4426be38d156db1cb6cfdc/kubernetes-pull-test-unit-integration/1509/artifacts/junit_v1%2Cextensions-v1beta1_20151112-214256.stdout):
```
=== RUN Test_getProxyMode
E1112 21:43:56.498644   10372 server.go:336] TIM: chose userspace because explicit
E1112 21:43:56.498831   10372 server.go:339] TIM: trying iptables because explicit
E1112 21:43:56.502672   10372 server.go:393] Can't determine whether to use iptables proxy, using userspace proxier: exec: "iptables": executable file not found in $PATH
E1112 21:43:56.502735   10372 server.go:341] TIM: chose userspace
E1112 21:43:56.502876   10372 server.go:372] TIM: found experimental annotation
E1112 21:43:56.502909   10372 server.go:384] TIM: trying iptables because last option
E1112 21:43:56.503018   10372 server.go:393] Can't determine whether to use iptables proxy, using userspace proxier: exec: "iptables": executable file not found in $PATH
E1112 21:43:56.503099   10372 server.go:372] TIM: found experimental annotation
E1112 21:43:56.503124   10372 server.go:380] TIM: chose userspace because annotation
E1112 21:43:56.503166   10372 server.go:372] TIM: found experimental annotation
E1112 21:43:56.503192   10372 server.go:384] TIM: trying iptables because last option
E1112 21:43:56.503288   10372 server.go:393] Can't determine whether to use iptables proxy, using userspace proxier: exec: "iptables": executable file not found in $PATH
E1112 21:43:56.503377   10372 server.go:372] TIM: found experimental annotation
E1112 21:43:56.503417   10372 server.go:384] TIM: trying iptables because last option
E1112 21:43:56.503510   10372 server.go:393] Can't determine whether to use iptables proxy, using userspace proxier: exec: "iptables": executable file not found in $PATH
E1112 21:43:56.503593   10372 server.go:372] TIM: found experimental annotation
E1112 21:43:56.503616   10372 server.go:384] TIM: trying iptables because last option
E1112 21:43:56.503704   10372 server.go:393] Can't determine whether to use iptables proxy, using userspace proxier: exec: "iptables": executable file not found in $PATH
E1112 21:43:56.503785   10372 server.go:369] TIM: found beta annotation
E1112 21:43:56.503810   10372 server.go:380] TIM: chose userspace because annotation
E1112 21:43:56.503838   10372 server.go:369] TIM: found beta annotation
E1112 21:43:56.503861   10372 server.go:384] TIM: trying iptables because last option
E1112 21:43:56.503974   10372 server.go:393] Can't determine whether to use iptables proxy, using userspace proxier: exec: "iptables": executable file not found in $PATH
E1112 21:43:56.504057   10372 server.go:369] TIM: found beta annotation
E1112 21:43:56.504083   10372 server.go:384] TIM: trying iptables because last option
E1112 21:43:56.504185   10372 server.go:393] Can't determine whether to use iptables proxy, using userspace proxier: exec: "iptables": executable file not found in $PATH
E1112 21:43:56.504256   10372 server.go:369] TIM: found beta annotation
E1112 21:43:56.504282   10372 server.go:384] TIM: trying iptables because last option
E1112 21:43:56.504368   10372 server.go:393] Can't determine whether to use iptables proxy, using userspace proxier: exec: "iptables": executable file not found in $PATH
E1112 21:43:56.504437   10372 server.go:372] TIM: found experimental annotation
E1112 21:43:56.504461   10372 server.go:384] TIM: trying iptables because last option
E1112 21:43:56.504559   10372 server.go:393] Can't determine whether to use iptables proxy, using userspace proxier: exec: "iptables": executable file not found in $PATH
E1112 21:43:56.504628   10372 server.go:336] TIM: chose userspace because explicit
E1112 21:43:56.504655   10372 server.go:336] TIM: chose userspace because explicit
E1112 21:43:56.504679   10372 server.go:339] TIM: trying iptables because explicit
E1112 21:43:56.504771   10372 server.go:393] Can't determine whether to use iptables proxy, using userspace proxier: exec: "iptables": executable file not found in $PATH
E1112 21:43:56.504812   10372 server.go:341] TIM: chose userspace
E1112 21:43:56.504873   10372 server.go:339] TIM: trying iptables because explicit
E1112 21:43:56.504961   10372 server.go:393] Can't determine whether to use iptables proxy, using userspace proxier: exec: "iptables": executable file not found in $PATH
E1112 21:43:56.504994   10372 server.go:341] TIM: chose userspace
E1112 21:43:56.505067   10372 server.go:336] TIM: chose userspace because explicit
E1112 21:43:56.505105   10372 server.go:336] TIM: chose userspace because explicit
E1112 21:43:56.505125   10372 server.go:339] TIM: trying iptables because explicit
E1112 21:43:56.505237   10372 server.go:393] Can't determine whether to use iptables proxy, using userspace proxier: exec: "iptables": executable file not found in $PATH
E1112 21:43:56.505271   10372 server.go:341] TIM: chose userspace
E1112 21:43:56.505330   10372 server.go:339] TIM: trying iptables because explicit
E1112 21:43:56.505418   10372 server.go:393] Can't determine whether to use iptables proxy, using userspace proxier: exec: "iptables": executable file not found in $PATH
E1112 21:43:56.505452   10372 server.go:341] TIM: chose userspace
--- FAIL: Test_getProxyMode (0.01s)
	server_test.go:67: Case[1] Expected "iptables", got "userspace"
	server_test.go:67: Case[2] Expected "iptables", got "userspace"
	server_test.go:67: Case[4] Expected "iptables", got "userspace"
	server_test.go:67: Case[5] Expected "iptables", got "userspace"
	server_test.go:67: Case[6] Expected "iptables", got "userspace"
	server_test.go:67: Case[8] Expected "iptables", got "userspace"
	server_test.go:67: Case[9] Expected "iptables", got "userspace"
	server_test.go:67: Case[10] Expected "iptables", got "userspace"
	server_test.go:67: Case[11] Expected "iptables", got "userspace"
	server_test.go:67: Case[14] Expected "iptables", got "userspace"
	server_test.go:67: Case[15] Expected "iptables", got "userspace"
	server_test.go:67: Case[18] Expected "iptables", got "userspace"
	server_test.go:67: Case[19] Expected "iptables", got "userspace"

```

**Comment by ixdy** [comment]
... which suggests that the issue is that `iptables` isn't in the docker image we're using for unit/integration tests, possibly.

**Comment by thockin** [comment]
how did you get to the verbose logs?

**Comment by thockin** [comment]
New push is up with iptables properly dependency-injected

**Comment by ixdy** [comment]
@thockin it definitely needs to be more discoverable.

If you are a Googler, you can look at the Jenkins build log, scroll down to the bottom, and click on the "View logs and artifacts at" link.

If you're not a Googler, you can take the Test Artifacts link from an e2e run, remove everything after the git sha, and navigate from there to the build results desired.

**Comment by thockin** [comment]
@k8s-bot test this please

**Comment by ArtfulCoder** [comment]
LGTM

**Comment by piosz** [comment]
@k8s-bot e2e test this please

**Comment by ArtfulCoder** [comment]
@k8s-bot e2e test this please

**Comment by thockin** [comment]
@k8s-oncall  FYI: this went in today.  If tests suddenly start bombing, consider this as a suspect.

**Pull request merged**
