### PR TITLE
Remove an asterix from the path parameter

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes https://github.com/kubernetes/kubernetes/issues/13198

@nikhiljindal @bgrant0607

### CODE REVIEW

**Comment by bgrant0607** [comment]
cc @kubernetes/goog-csi

**Comment by nikhiljindal** [comment]
All tests pass but am not sure if we have a test for an operation with {path:*}.
Can you please make sure once that those operations continue working fine after this change, for ex you can try: /api/v1/proxy/nodes/{name}/{path:*}
Thanks!

**Comment by brendandburns** [comment]
@nikhiljindal 

We test it in e2e:

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/proxy.go#L217

And that e2e test has passed in the PR builder run.

**Comment by nikhiljindal** [comment]
Awesome, thanks!
LGTM

**Pull request merged**
