### PR TITLE
kubeadm: Don't ask for input if it's dry run mode

### PR DESCRIPTION
**Pull request by chendave**
Signed-off-by: Dave Chen <dave.chen@arm.com>

This is consistent with `kubeadm upgrade apply`,  pls see the [code here](https://github.com/kubernetes/kubernetes/blob/bd2776e0c930ab149d8c0656e83f979fb017ce0a/cmd/kubeadm/app/cmd/upgrade/apply.go#L56-L58)

Background is I am working on the `nonInteractiveMode` for the `kubeadm reset`, the purpose is that when user add the flag `-yes` then there is no need to wait user's input.  Compared with other cmd like `upgrade apply`, seems like there is no need to wait for input when it's in `dry-run` mode as well.

#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig cluster-lifecycle

### CODE REVIEW

**Comment by chendave** [comment]
I will push another pr to introduce `nonInteractiveMode` for `kubeadm reset` and do necessary refactor later.

**Comment by neolit123** [comment]
> Background is I am working on the nonInteractiveMode for the kubeadm reset, the purpose is that when user add the flag -yes then there is no need to wait user's input. Compared with other cmd like upgrade apply, seems like there is no need to wait for input when it's in dry-run mode as well.

i don't think we want -yes flag, because all interactive commands already have -f.

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve
/triage accepted

**Comment by chendave** [comment]
> i don't think we want -yes flag, because all interactive commands already have -f.

Got you, my original thinking was that we can have a flag `-y` which is similar with `kubeadm upgrade apply -y`, `-f` should be fine as well.

Anyway, I saw some chance to de-dup some code, will have a cleanup.

**Pull request merged**
