### PR TITLE
Revert "Run rbac authorizer from cache"

### PR DESCRIPTION
**Pull request by wojtek-t**
Reverts kubernetes/kubernetes#34047

This PR broke scalability test, by significantly increasing controller-manager usage, e.g.:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-kubemark-500-gce/6776
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-kubemark-5-gce/15565
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-kubemark-5-gce/15566
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-kubemark-5-gce/15567

@ncdc @deads2k @liggitt @k8s-oncall

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34840)

### CODE REVIEW

**Comment by deads2k** [comment]
@wojtek-t what does that CPU utilization test?  This only affected the controllers and we aren't even using RBAC for the tests are we?

**Comment by deads2k** [comment]
err only affected the api servers, not controllers.

**Comment by ncdc** [comment]
I'm also confused how this PR could have increase controller manager cpu load

**Comment by wojtek-t** [comment]
apiserver usage is ok, only controllers increased

**Comment by liggitt** [comment]
it looks like the next commit was where the failures started:
https://github.com/kubernetes/kubernetes/pull/34809

**Comment by ncdc** [comment]
What @liggitt wrote

**Comment by ncdc** [comment]
The linked logs reference commit 928b8cbdb85e08da245ed608142b4ef061a9ea26 which is #34809

**Comment by liggitt** [comment]
testgrid also indicates 928b8cb:
https://k8s-testgrid.appspot.com/k8s#kubemark-5-gce&include-filter-by-regex=%5EOverall%24%7C%5C%5Bk8s%5C.io%5C%5D%5C%20Density%5C%20%5C%5BFeature%5C%3APerformance%5C%5D%5C%20should%5C%20allow%5C%20starting%5C%2030%5C%20pods%5C%20per%5C%20node

**Comment by wojtek-t** [comment]
wojtekt [7:55 PM]  
so for kubemark-500,:
- last ok run started at 8:26
for kubemark-5:
- last ok run started at 9:15

so it's probably something after 9:15 (well, something for which build finished after 9:15)

**Comment by wojtek-t** [comment]
@liggitt @deads2k - I think you are right that the victim is #34809 though it's super strange, because that PR doesn't look harmful; WDYT? @gmarek - FYI

**Comment by ncdc** [comment]
It makes it so it runs `WaitForCacheSync` every 100ms if the caches haven't synced yet, so that could definitely be it

**Comment by deads2k** [comment]
> It makes it so it runs WaitForCacheSync every 100ms if the caches haven't synced yet, so that could definitely be it

The test is so sensitve that an in memory boolean check 10 times a second breaks CPU?

**Comment by wojtek-t** [comment]
@ncdc - is WaitForCacheSync so expensive? I though it just check for some bool, isn't it? @deads2k ?

**Comment by ncdc** [comment]
3 in memory boolean checks 10 times a second, but still...

**Comment by ncdc** [comment]
I certainly wouldn't expect it to make it almost double the cpu constraint

**Comment by deads2k** [comment]
> @ncdc - is WaitForCacheSync so expensive? I though it just check for some bool, isn't it? @deads2k ?

I said the same thing.  It was meant to be cheap, but it looks correct to me: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/cache/shared_informer.go#L88

**Comment by liggitt** [comment]
there are a lot of locks involved in each call (each `Informer()` call acquires a lock, and each `HasSynced` call acquires at least one lock, depending on how many layers it's calling down through), but even so, that seems like a lot

**Comment by wojtek-t** [comment]
Yeah - that is exactly what I'm thinking.

I've just merged: https://github.com/kubernetes/test-infra/pull/836 (we had misconfiguration issue and were not checking resource usage in per-PR kubemark tests). We should be able to kick tests again on this PR and I will do a revert for the other PR.
One of them should fail, one of them should pass (hopefully) and then we will kow which one to revert.

**Comment by wojtek-t** [comment]
@k8s-bot kubemark test this, issue: https://github.com/kubernetes/kubernetes/issues/33344

**Comment by wojtek-t** [comment]
Confirmed that it's not this PR fault:
https://github.com/kubernetes/kubernetes/pull/34844#issuecomment-253891196

Closing this revert (and very sorry for confusion).

**Pull request closed without merging**
