### PR TITLE
Clean up the link in cassandra

### LINKED ISSUE #34431: Some typos in links in cassandra
**Kubernetes version** (use `kubectl version`):
the latest version

**Environment**:
ubuntu 14.02

**What happened**:
There are some typos in links in README

**What you expected to happen**:
Clear up the links

### PR DESCRIPTION
**Pull request by yuexiao-wang**
**What this PR does / why we need it**:
Clean up the link in  README for cassandra

**Which issue this PR fixes** :
 fixes #34431

Signed-off-by: yuexiao-wang wang.yuexiao@zte.com.cn

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34432)

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@bgrant0607 I am assigned to this, but cannot merge it ... noooooo

LGTM btw ... lets see if we can get it through Jenkins

**Comment by bgrant0607** [comment]
@chrislovecnm Try `/lgtm` if you think it looks good.

**Comment by bgrant0607** [comment]
ok to test

**Comment by bgrant0607** [comment]
@k8s-bot ok to test

**Comment by chrislovecnm** [comment]
@bgrant0607 oh right stuff is merged automatically ... duh

**Pull request merged**
