### PR TITLE
SplitHostPort is needed since Request.RemoteAddr has the host:port format

### PR DESCRIPTION
**Pull request by soltysh**
@smarterclayton ptal
[Analytics]()

### CODE REVIEW

**Comment by bprashanth** [comment]
failure seems legit
```
Call stack:
  1: ./hack/../hack/verify-api-reference-docs.sh:34 main(...)
Exiting with status 1
FAILED   ./hack/../hack/verify-api-reference-docs.sh	1s
Verifying ./hack/../hack/verify-boilerplate.sh
SUCCESS  ./hack/../hack/verify-boilerplate.sh	0s
```

**Comment by bprashanth** [comment]
@k8s-bot unit test this issue #IGNORE (docker in docker 1.11 weirdness - https://github.com/kubernetes/test-infra/issues/47)

**Comment by bprashanth** [comment]
@k8s-bot unit test this issue #IGNORE

**Comment by soltysh** [comment]
@k8s-bot test this github flake: #22655

**Comment by soltysh** [comment]
@k8s-bot test this github flake: #22655

**Comment by soltysh** [comment]
@k8s-bot test this github flake: #22655

**Comment by soltysh** [comment]
@k8s-bot test this github flake: #22655

**Comment by ArtfulCoder** [comment]
@k8s-bot test this github flake: #22655

**Comment by soltysh** [comment]
@k8s-bot test this github flake: #22655

**Pull request merged**
