### PR TITLE
Move pkg/kubectl/proxy to staging

### PR DESCRIPTION
**Pull request by seans3**
* Moves `pkg/kubectl/proxy` to staging.
* Publishes this code to the new kubectl repository: https://github.com/kubernetes/kubectl/pkg/proxy.
* Code will be available for re-use after publishing.

/kind cleanup
/sig cli
/area kubectl
/area code-organization
/priority important-soon

```release-note
NONE
```

### CODE REVIEW

**Comment by seans3** [comment]
/assign @BenTheElder 

for `vendor/modules.txt`

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Comment by BenTheElder** [comment]
needs rebase

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Pull request merged**
