### PR TITLE
Cherry pick #45309 on release-1.6

### PR DESCRIPTION
**Pull request by yguo0905**
**What this PR does / why we need it**:

Cherry pick of #45309 on release-1.6.

This is needed to run Ubuntu node e2e tests on GKE. We want to cherry-pick them into the 1.6 release branch in order to run the tests against 1.6.

**Release note**:

```
NONE
```

/assign @dchen1107

### CODE REVIEW

**Comment by dchen1107** [comment]
Justification for 1.6 cherrypick: This is purely enable an alpha feature for GKE testing. It has no impact on OSS k8s.

**Comment by yguo0905** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by calebamiles** [comment]
removing `do not merge` label due to approval from @dchen1107.

**cc: @yguo0905, @kubernetes/kubernetes-release-managers**

**Comment by yguo0905** [comment]
@k8s-bot node e2e test this

**Pull request merged**
