### PR TITLE
Fix package name of psp on e2e framework

### PR DESCRIPTION
**Pull request by oomichi**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

psp is imported as separated package from main framework but the
name was framework. This made confusion, so this renames it to psp.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
thanks for catching this @oomichi 
/lgtm
/approve
/priority backlog

**Comment by oomichi** [comment]
pull-kubernetes-verify job continues failing due to unused function.
I cannot find any PR which removes the function, so https://github.com/kubernetes/kubernetes/pull/83807 is for that.
This PR should be retested after merging the above or the same PR.

**Comment by oomichi** [comment]
humm, the function is still used in `test/integration/volumescheduling/volume_binding_test.go`
So I need to investigate the issue more.

/test pull-kubernetes-verify

**Pull request merged**
