### PR TITLE
display pod namespace while describe node

### PR DESCRIPTION
**Pull request by hurf**
#9433

### CODE REVIEW

**Comment by brendandburns** [comment]
ok to test

**Comment by brendandburns** [comment]
this LGTM to me.  As discussed elsewhere, adding this for all resources would be great.  It can be a separate PR if you prefer.

**Comment by brendandburns** [comment]
Closes #9433

**Comment by dchen1107** [comment]
LGTM except the ordering on displaying namespace and podname so that the output can be sorted by namespace first, then name. @brendandburns I don't have strong opinion on this though.

**Comment by hurf** [comment]
Modified the order following @dchen1107 's instruction.

**Comment by brendandburns** [comment]
I'm merging this as is, feel free to send a follow-on PR that adds it to the other describe resources.

Thanks!
--brendan

**Pull request merged**
