### PR TITLE
Delete e2e-runner and related images

### PR DESCRIPTION
**Pull request by fejta**
https://github.com/kubernetes/test-infra/pull/444 migrates these files to test-infra

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31316)

### CODE REVIEW

**Comment by ixdy** [comment]
This needs to adopt https://github.com/kubernetes/kubernetes/pull/31330.

**Comment by ixdy** [comment]
I think `docs/devel/development.md` needs to be updated too to point to the new location of these images?

**Comment by fejta** [comment]
#31330 adopted in https://github.com/kubernetes/test-infra/pull/444

Updated `development.md`

**Comment by ixdy** [comment]
LGTM

**Pull request merged**
