### PR TITLE
[WIP] fix Host events cannot be obtained

### PR DESCRIPTION
**Pull request by aimuz**
#### Which issue(s) this PR fixes:

Fixes #

https://github.com/kubernetes/kubernetes/issues/100236

#### Does this PR introduce a user-facing change?

```release-note
Fixed node uid error，For unification, the node.uid  The place where I live is changed to node.name, 
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by janetkuo** [comment]
As @k8s-ci-robot commented above, please assign approvers after the PR has been reviewed.

**Comment by dashpole** [comment]
Did you test this?  i'm not sure if node uid is populated when the events in question are generated.

**Comment by aimuz** [comment]
> Did you test this? i'm not sure if node uid is populated when the events in question are generated.

https://github.com/kubernetes/kubernetes/issues/100236

This issue describes the problem. The cause of the problem is that there are multiple producers in the host event. The most widely used one is to use nodeName as uid. But there are also problems with using node.uid  Place as uid (though this is the right behavior). Because there are a lot of nodeName as uid in the system, and kubectl query also uses nodeName as uid query condition to change uid of event to uid node.name  The cost should be minimal.

Welcome to discuss

**Review by pacoxu — COMMENTED** [review]
This PR makes sense. But the name is odd to me. I think we should add some comments to explain why we use nodeName as UID.

Perhaps, the reason is 
https://github.com/kubernetes/kubernetes/blob/03830db82de748fe063ff3db1d471080f4d5a48a/pkg/kubelet/kubelet.go#L476

**Comment by aimuz** [comment]
> This PR makes sense. But the name is odd to me. I think we should add some comments to explain why we use nodeName as UID.
> 
> Perhaps, the reason is
> https://github.com/kubernetes/kubernetes/blob/03830db82de748fe063ff3db1d471080f4d5a48a/pkg/kubelet/kubelet.go#L476

relevant notes have been added

**Comment by pacoxu** [comment]
/lgtm
/assign @cheftako
Would you take a look?

**Comment by aimuz** [comment]
Excuse me, when will this be merged into the main line

**Comment by pacoxu** [comment]
/lgtm cancel

After re-thinking, even that currently most node events are using node-name as uid. I think it is odd.
I prefer to change it to `node uid` instead of fixing it in an odd way to maintain a consistent behavior.

```
        {
            "apiVersion": "v1",
            "count": 1,
            "eventTime": null,
            "firstTimestamp": "2021-09-14T09:29:36Z",
            "involvedObject": {
                "kind": "Node",
                "name": "daocloud-node-1",
                "uid": "daocloud-node-1"
            },
            "kind": "Event",
            "lastTimestamp": "2021-09-14T09:29:36Z",
            "message": "Node daocloud-node-1 status is now: NodeReady",
            "metadata": {
                "creationTimestamp": "2021-09-14T09:29:36Z",
                "name": "daocloud-node-1.16a4a64430868de4",
                "namespace": "default",
                "resourceVersion": "210786",
                "uid": "023d7d6b-6f99-4f7f-bdd5-7a1ac6f38d8b"
            },
            "reason": "NodeReady",
            "reportingComponent": "",
            "reportingInstance": "",
            "source": {
                "component": "kubelet",
                "host": "daocloud-node-1"
            },
            "type": "Normal"
        },
```

**Comment by pacoxu** [comment]
Add  [slack dissussion ](https://kubernetes.slack.com/archives/C0BP8PW9G/p1631612421206800) link here.

> Using anything other than the UUID / UID of the involved object sounds like a bug to me.

> I could imagine some future admission control or auditing hook getting involved when the involved object doesn't actually exist (some cases might be OK, like an Event about a recently-removed resource)

**Comment by adisky** [comment]
@aimuz I believe still you are working on the PR,  Tests needs to be fixed kubelet is not coming up

**Comment by aimuz** [comment]
> @aimuz I believe still you are working on the PR, Tests needs to be fixed kubelet is not coming up

@adisky 

Since the current PR has not been processed for a long time, I create another PR in a smoother way.

https://github.com/kubernetes/kubernetes/pull/106485

When the 106485 PR is merged, I will reprocess the current PR

**Comment by adisky** [comment]
@aimuz can you mark this PR as WIP until #106485 is done
/hold
(until #106485 is merged)

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by dims** [comment]
This PR has the label work-in-progress, please revisit to see if you still need this, please close if not

**Comment by aimuz** [comment]
It seems that there is not enough energy to sort this out at present. I will close this first, and when time permits, I will reopen this to completely solve this problem

/close

**Pull request closed without merging**
