### PR TITLE
fix bugs of container cpu shares when cpu request set to zero

### PR DESCRIPTION
**Pull request by waynepeking348**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
For container resources, if limits are specified, but requests are not, default requests are set to limits in API server, and kubelet repeat this logic for containers running on existing Kubernetes cluster, but it works with some mistake for cpu. 
Actually, if cpu request is set to zero (instead of not specified), kubelet will also consider it as equal to limits, and set cpu shares as to limit instead of 2 (minShares). 
This is unexpected, think that if we have 2 containers, one with requests set as:

    limits:
        cpu: "4"
      requests:
        cpu: "2"

and the other with requests set as:

    limits:
        cpu: "4"
      requests:
        cpu: "0"

the cpu shares (in container level cgroup) for first one would be set as 2048 while the latter as 4096
but the expected cpu shares would be 2048 and 2 instead

**Does this PR introduce a user-facing change?**:

```release-note
fix bugs of container cpu shares setting when cpu request set to zero
```

### CODE REVIEW

**Comment by waynepeking348** [comment]
@ehashman @Random-Liu @derekwaynecarr would you please have a look at this fix? thx

**Review by ehashman — CHANGES_REQUESTED** [review]
/ok-to-test
/priority backlog
/triage accepted

You'll need to add tests for this change.

**Comment by waynepeking348** [comment]
> /ok-to-test
> /priority backlog
> /triage accepted
> 
> You'll need to add tests for this change.

@ehashman hi~ I add some tests for this fix, could you please help merge this pr?

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by waynepeking348** [comment]
@ehashman  @Random-Liu  hi~ this pr may need a approved label before it can be merged, could you please help with this? thx

**Pull request closed without merging**
