### PR TITLE
Include ContainerStatus in "describe pod".

### LINKED ISSUE #6076: kubectl descrbe pods id should include containers information
Kubectl describe pods id only has top level pod information, without any information related to containers. Taking kube-dns pod as an example, which has 3 containers specified: 

```
$ cluster/kubectl.sh describe pods kube-dns-gziey
current-context: "golden-system-455_kubernetes"
Running: cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/linux/amd64/kubectl describe pods kube-dns-gziey
Name:				kube-dns-gziey
Image(s):			quay.io/coreos/etcd:v2.0.3,kubernetes/kube2sky:1.1,kubernetes/skydns:2015-03-11-001
Host:				kubernetes-minion-p1yo.c.golden-system-455.internal/
Labels:				k8s-app=kube-dns,kubernetes.io/cluster-service=true,name=kube-dns
Status:				Running
Replication Controllers:	kube-dns (1/1 replicas created)
Conditions:
  Type		Status
  Ready 	True 
No events.
```

If a pod with RestartAlways policy, but all contianers are in crashloop, the user cannot interpret the true state based on above information. Proposed to include ContainerStatus here.

### PR DESCRIPTION
**Pull request by vmarmol**
Fixes #6076.

### CODE REVIEW

**Comment by vmarmol** [comment]
Sample output:

```
Name:                           monitoring-influx-grafana-controller-q7iga
Image(s):                       kubernetes/heapster_influxdb:v0.3,kubernetes/heapster_grafana:v0.5
Host:                           kubernetes-minion-avdn
Labels:                         kubernetes.io/cluster-service=true,name=influxGrafana
Status:                         Running
Replication Controllers:        monitoring-influx-grafana-controller (1/1 replicas created)
Containers:
  grafana:
    Image:              kubernetes/heapster_grafana:v0.5
    State:              Running
      Started:          Tue, 31 Mar 2015 10:42:01 -0700
    Ready:              True
    Restart Count:      0
  influxdb:
    Image:              kubernetes/heapster_influxdb:v0.3
    State:              Running
      Started:          Tue, 31 Mar 2015 10:40:54 -0700
    Ready:              True
    Restart Count:      0
Conditions:
  Type          Status
  Ready         True 
No events.
```

**Comment by vishh** [comment]
This will be very useful! Thanks for the feature @vmarmol !

**Comment by brendandburns** [comment]
LGTM.  Merging on 1 of two builds clean.

**Comment by dchen1107** [comment]
Thanks!

**Pull request merged**
