### PR TITLE
chore (samples): Don't cache apks at all in Dockerfiles

### PR DESCRIPTION
**Pull request by SimenB**
**What this PR does / why we need it**:
It simplifies the sample Dockerfiles somewhat.

https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md#disabling-cache

**Special notes for your reviewer**:
While I'm here, any reason the Redis sample doesn't use the official Redis image from Dockerhub?

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by SimenB** [comment]
I signed it!

**Comment by smarterclayton** [comment]
@thockin one of these was your image

**Comment by smarterclayton** [comment]
@bowei since you made the change to use alpine here

**Comment by bowei** [comment]
@smarterclayton -- from git blame, it seems like it was Manuel de Brito Fontes that made the change?

**Comment by SimenB** [comment]
Anything I can do here?

**Comment by thockin** [comment]
LGTM - manually tested

**Comment by bowei** [comment]
@k8s-bot test this

**Comment by SimenB** [comment]
Rebased again in case it helps

**Pull request merged**
