### PR TITLE
kubectl-diff: Return non-1 errors on kubectl failures

### LINKED ISSUE #707: kubectl diff exit code 1 for both errors _and_ diffs
It seems `kubectl diff` exits with 1 on both errors (eg for RBAC) or the presence of a diff.  

Would be useful if we could have two different codes here.

### PR DESCRIPTION
**Pull request by apelisse**
Currently, diff AND kubectl can return 1 errors either when diff finds
differences, or when kubectl fails something. It also prints an ugly
error when diff finds a differences, since 1 is treated as an error.

Two things this PR does:

1. If diff returns 1, then do not treat it as an error, and exit with
exit code 1. It no longer prints the ugly error.

2. Kubectl errors are +1'd so that they never return 1 which shouldn't
be considered an error.

We need to update the documentation accordingly, to mention that
`KUBECTL_EXTERNAL_DIFF` programs must also follow the convention of
using one as their exit code for changes detected.

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubectl/issues/707
Replaces #82336 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
`kubectl diff` now returns 1 only on diff finding changes, and >1 on kubectl errors. The "exit status code 1" message as also been muted.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

/sig cli
/priority important-soon

### CODE REVIEW

**Comment by apelisse** [comment]
working on a test right now.

**Comment by apelisse** [comment]
cc @julianvmodesto

**Comment by apelisse** [comment]
Added a couple of new tests to check error codes.

**Comment by apelisse** [comment]
I think the test should be fixed now.

**Comment by julianvmodesto** [comment]
/lgtm

Definitely simpler + easy to understand. The tests 👏

**Comment by seans3** [comment]
Thanks for adding integration tests.

/lgtm
/approve

**Pull request merged**
