### PR TITLE
Revert "podresources: e2e: force eager connection"

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind failing-test

#### What this PR does / why we need it:
https://testgrid.k8s.io/sig-node-release-blocking#node-kubelet-serial-containerd has been failing since around the PR.  

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ffromani** [comment]
/lgtm

removing only the test part which consume the new (internal) API just can make for a faster merge because @SergeyKanzhelev can approve `test/e2e_node` changes

**Comment by ffromani** [comment]
> /lgtm
> 
> removing only the test part which consume the new (internal) API just can make for a faster merge because @SergeyKanzhelev can approve `test/e2e_node` changes

that said I'm very surprised this change caused failures, but can't argue with testgrid. I'm fine with the revert, so I can keep working on another followup PR to fulfill the original intent .

**Comment by dims** [comment]
/approve
/lgtm

approving the revert to get tests back on their feet.

**Comment by kannon92** [comment]
I want to confirm pull-kubernetes-node-kubelet-serial-containerd is passing before we merge.  

Thank you for the approval!

**Comment by ffromani** [comment]
alternative fix from @tzneal : https://github.com/kubernetes/kubernetes/pull/121270

**Comment by kannon92** [comment]
It looks like this revert will at least resolve some of the failures.  Other tests failed around this but the two tests that were always failing look to be green again.

**Comment by kannon92** [comment]
I'll let this next one run and then I'll unhold the job.

**Comment by kannon92** [comment]
@tzneal @ffromani which solution do you want to go with?

It does look like @tzneal PR helps with this test.

**Comment by tzneal** [comment]
> @tzneal @ffromani which solution do you want to go with?
> 
> 
> 
> It does look like @tzneal PR helps with this test.

Doesn't matter to me, I only tested the device test. If yours helps with others, we should take it.

**Comment by kannon92** [comment]
> > @tzneal @ffromani which solution do you want to go with?
> > It does look like @tzneal PR helps with this test.
> 
> Doesn't matter to me, I only tested the device test. If yours helps with others, we should take it.

Mine is just reverting @ffromani changes.  The Device Plugin tests were the ones I was hoping we would fix with the revert.

**Comment by ffromani** [comment]
> @tzneal @ffromani which solution do you want to go with?
> 
> It does look like @tzneal PR helps with this test.

If full revert fixes the failures, let's go with it. I'll restart the failed attempt from scratch later.

**Comment by tzneal** [comment]
> > @tzneal @ffromani which solution do you want to go with?
> > It does look like @tzneal PR helps with this test.
> 
> If full revert fixes the failures, let's go with it. I'll restart the failed attempt from scratch later.

SGTM, I'll close the other PR.

**Pull request merged**
