### PR TITLE
Remove unused command waitfordetach from flex volume driver

### PR DESCRIPTION
**Pull request by jolestar**
**What this PR does / why we need it**:
Clean unused code.

**Special notes for your reviewer**:
See https://github.com/kubernetes/kubernetes/pull/35629

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by jolestar** [comment]
CLA complete

**Review by j-griffith — APPROVED** [review]
Looks like most of this was cleaned up long ago: 
    https://github.com/kubernetes/kubernetes/pull/35629/commits/ccb8d53a399fc4bb8b8d8b6d1b41080c6bd50f38

**Pull request closed without merging**
