### PR TITLE
fix typo failded->failed

### PR DESCRIPTION
**Pull request by x1957**
**What this PR does / why we need it**:
fix typo failded
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by gyliu513** [comment]
@k8s-bot ok to test

**Comment by cblecker** [comment]
/assign @adohe
for approval

**Comment by x1957** [comment]
@cblecker @adohe plz approval this small pr, thanks.

**Comment by x1957** [comment]
@cblecker test is ok

**Comment by x1957** [comment]
@cblecker thanks for your help, retest this pr so many times. Who can approval this simple pr?

**Pull request closed without merging**
