### PR TITLE
AWS: Add missing error check for #27774

### PR DESCRIPTION
**Pull request by justinsb**
There was an error check missing, which seems likely to have caused 27774

Issue #27774

### CODE REVIEW

**Comment by justinsb** [comment]
P1 because this was hit in a test of the new volume-detach logic.

**Comment by goltermann** [comment]
@justinsb 
/go/src/k8s.io/kubernetes/docs/ is out of date. Please run hack/update-munge-docs.sh
FAILED   ./hack/../hack/verify-munge-docs.sh	2s

**Comment by mikedanese** [comment]
@k8s-bot ok to test, issue #27797

**Comment by goltermann** [comment]
thanks @mikedanese

**Comment by girishkalele** [comment]
@justinsb 

Thanks for the quick fix (for the panic in the short term).

Who knows the area to LGTM the change ?
It might also need to be cherry-picked.

**Comment by girishkalele** [comment]
@justinsb 

Just got clarification from Daniel, don't need cherry-picking yet.

**Comment by goltermann** [comment]
@k8s-bot e2e test this issue: #26210

**Pull request merged**
