### PR TITLE
changelog: fix some errors about changelog 1.13.

### PR DESCRIPTION
**Pull request by yangjunmyfm192085**
Signed-off-by: JunYang <yang.jun22@zte.com.cn>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix some error hyperlinks.
Adjusted some text format.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by yangjunmyfm192085** [comment]
Could you take a moment to help take a look?
Thank you very much.
/assign justaugustus
/assign saschagrunert

**Comment by wilsonehusin** [comment]
I'm not inclined to accept this PR because this is a change to an [inactive release line](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#non-active-branch-history). Please consider contributing to an active release line instead. Changes to inactive release lines will only be accepted if they are from a batch of fixing similar pattern, like #98209.

**Comment by justaugustus** [comment]
/close
ref: Wilson's [comment](https://github.com/kubernetes/kubernetes/pull/98314#issuecomment-776063090)

**Pull request closed without merging**
