### PR TITLE
kubeadm: remove unused command flag constants

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
1. remove unused constants, they are unused since #94869 and #106370
2. fix some comment issues

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pacoxu — APPROVED** [review]
/lgtm

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Comment by dims** [comment]
this is not a bug or a test problem, let's land it when 1.27 opens up

/milestone v1.27

**Pull request merged**
