### PR TITLE
Warn if docker buildx is not available

### PR DESCRIPTION
**Pull request by dims**
Follow up to https://github.com/kubernetes/kubernetes/pull/104245 Let us warn folks with a better error message.

cc @m-Bilal 

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
`ensure_dockerized` was not being used anywhere ( https://cs.k8s.io/?q=ensure_dockerized&i=nope&files=&excludeFiles=&repos=kubernetes/kubernetes,kubernetes/test-infra )

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
whoops fixed shell check failure

```
In ./hack/lib/util.sh line 714:
  if docker buildx 2>&1 >/dev/null; then
                   ^--^ SC2069: To redirect stdout+stderr, 2>&1 must be last (or use '{ cmd > file; } 2>&1' to clarify).

For more information:
  https://www.shellcheck.net/wiki/SC2069 -- To redirect stdout+stderr, 2>&1 m...
```

**Pull request merged**
