### PR TITLE
add more comment info for podEvictionTimeout

### PR DESCRIPTION
**Pull request by torubylist**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Unitil now, the comment of podEvictionTimeout is not clear, if we do not set runTaintManager to false, the podEvictionTimeout doesn't work, so we should clear it in comment info.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by torubylist** [comment]
I signed it

**Comment by neolit123** [comment]
> I signed it

make sure your github account includes the email you signed the CLA.
if there is a problem try contacting the CNCF helpdesk.

**Comment by torubylist** [comment]
I signed it

**Pull request closed without merging**
