### PR TITLE
e2e: remove unused method in e2e/framework/autoscaling.

### PR DESCRIPTION
**Pull request by haosdent**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Remove unused method.

**Which issue(s) this PR fixes**:

Ref #86052

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by haosdent** [comment]
cc @SataQiu

**Review by oomichi — COMMENTED** [review]
Yes, this function has been unused since 40a6fe56b019b83f6c58510dba49eddf3e4a3d1d

/lgtm
/approve

**Pull request merged**
