### PR TITLE
Remove deprecated options in kube-scheduler.

### PR DESCRIPTION
**Pull request by jfbai**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

These options were marked as deprecated at 2018/05/15, and according to [kubernetes deprecation policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-a-flag-or-cli), 
> Rule #5a: CLI elements of user-facing components (e.g. kubectl) must function after their announced deprecation for no less than:
> GA: 6 months or 1 release (whichever is longer)
> Beta: 3 months or 1 release (whichever is longer)
> Alpha: 0 releases

these options can be removed.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
N/A
**Does this PR introduce a user-facing change?**:
NONE
```release-note
N/A
```
/sig scheduling
/assign @bsalamat @k82cn @misterikkit @wgliang

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
/ok-to-test
/priority important-longterm

**Comment by misterikkit** [comment]
/unassign
(sorry - won't have time to look at this)

**Review by bsalamat — COMMENTED** [review]
We cannot remove the options yet, because the ComponentConfig that is used as a replacement for these options is still in alpha.

/hold

**Comment by jfbai** [comment]
@bsalamat got it. I will keep watching the status of **ComponentConfig**.

**Comment by misterikkit** [comment]
> @bsalamat got it. I will keep watching the status of **ComponentConfig**.

As far as I know, there is not active work to move KubeSchedulerConfig out of alpha. Help would probably be welcomed in that area.

**Comment by bsalamat** [comment]
> As far as I know, there is not active work to move KubeSchedulerConfig out of alpha. Help would probably be welcomed in that area.

+1. [This issue](https://github.com/kubernetes/enhancements/issues/785) is filed to move the config to beta, but no work is done yet.

**Pull request closed without merging**
