### PR TITLE
Remove . import from e2e test

### PR DESCRIPTION
**Pull request by mkimuram**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Part of: https://github.com/kubernetes/kubernetes/issues/77706

**Special notes for your reviewer**:
/sig testing
@oomichi 

It seems that there are some . imports still remaining. Replaced with the below commands.

<details>

```
$ grep -r '\. "github.com/onsi/' test/e2e | awk -F ":" '{print $1}' | sort -u | while read file;do 
sed -i $file \
-e 's/\. "github.com\/onsi\/gomega"/"github.com\/onsi\/gomega"/' \
-e 's/\. "github.com\/onsi\/ginkgo"/"github.com\/onsi\/ginkgo"/' \
-e 's/(BeNil(/(gomega.BeNil(/' \
-e 's/(HaveOccurred(/(gomega.HaveOccurred(/' \
-e 's/(BeZero(/(gomega.BeZero(/' \
-e 's/(Equal(/(gomega.Equal(/' \
-e 's/(BeIdenticalTo(/(gomega.BeIdenticalTo(/' \
-e 's/(ContainSubstring(/(gomega.ContainSubstring(/' \
-e 's/(BeNumerically(/(gomega.BeNumerically(/' \
-e 's/(BeEmpty(/(gomega.BeEmpty(/' \
-e 's/(HaveLen(/(gomega.HaveLen(/' \
-e 's/(MatchRegexp(/(gomega.MatchRegexp(/' \
-e 's/(BeTrue(/(gomega.BeTrue(/' \
-e 's/\sExpect(/ gomega.Expect(/' \
-e 's/\sEventually(/ gomega.Eventually(/' \
-e 's/\sConsistently(/ gomega.Consistently(/' \
-e 's/\sBeforeEach(/ ginkgo.BeforeEach(/' \
-e 's/\sAfterEach(/ ginkgo.AfterEach(/' \
-e 's/\sContext(/ ginkgo.Context(/' \
-e 's/\sDescribe(/ ginkgo.Describe(/' \
-e 's/\sGinkgoRecover(/ ginkgo.GinkgoRecover(/' \
-e 's/\sIt(/ ginkgo.It(/' \
-e 's/\sBy(/ ginkgo.By(/' 
done
$ git diff --name-only | xargs gofmt -w
$ sed -i test/e2e/common/autoscaling_utils.go -e "s/ginkgo.Context(/Context(/"

$ grep -r "gomega.Expect(err).ToNot(gomega.HaveOccurred()," test/e2e | awk -F ":" '{print $1}' | sort -u | while read file;do sed -i ${file} -e "s/gomega.Expect(err).ToNot(gomega.HaveOccurred(),/framework.ExpectNoError(err,/" ;done
$ grep -r "gomega.Expect(err).To(gomega.HaveOccurred()," test/e2e | awk -F ":" '{print $1}' | sort -u 
test/e2e/framework/util.go
```

</details>

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by oomichi** [comment]
timer_test.go seems necessary to be updated:
```
test/e2e/framework/timer/timer_test.go:43:2: undefined: RegisterTestingT
test/e2e/framework/timer/timer_test.go:51:38: undefined: MatchJSON
test/e2e/framework/timer/timer_test.go:74:38: undefined: MatchJSON
```

**Comment by mkimuram** [comment]
@oomichi 

> timer_test.go seems necessary to be updated:

Thank you for your comment. The last commit should fix it. PTAL

**Comment by oomichi** [comment]
@mkimuram Thanks for updating.
BTW this PR consists of multiple commit. So can we `git merge --squash` into a single commit?
TBH I am not 100% sure about that, but sometimes I saw such request during review process as https://kubernetes.slack.com/archives/C09R23FHP/p1560294545032400

**Comment by mkimuram** [comment]
@oomichi 

Squashed.

**Review by oomichi — COMMENTED** [review]
Thanks for updating

/lgtm

**Comment by oomichi** [comment]
@mkimuram Unfortunately this needs to be rebased.

**Comment by mkimuram** [comment]
@oomichi

Thank you for notifying me the need for rebase. Rebased. PTAL

**Pull request merged**
