### PR TITLE
Decouple config types between cloud-controller-manager and kube-controller-manager

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kim.andrewsy@gmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
As part of trying to move cmd/cloud-controller-manager to staging (https://github.com/kubernetes/cloud-provider/issues/29) we need to remove the cloud-controller-manager's dependency to cmd/controller-manager. 

In this PR we duplicate the config types `GenericControllerManagerConfiguration` and `KubeCloudSharedConfiguration`. Duplicating `KubeCloudSharedConfiguration` is temporary since kube-controller-manager's versioned config types are in staging and can't depend on k8s.io/kubernetes.  Once the CCM version of `KubeCloudSharedConfiguration` is moved to staging, we can remove any duplicated types in kube-controller-manager. Duplicating `GenericControllerManagerConfiguration` may not be feasible in the long term so we may want to find a new home for it (k8s.io/component-base?).

Hoping cloud-controller-manager's move to staging is complete by v1.19 so we can clean up the duplicated config types before the end of the release cycle. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
Since we might want move controller-manager out-tree as well, is it better to move some of the duplicated code(like config types) under k8s.io/cloud-provider rather than sitting in CCM so that both CCM and CM could leverage?

**Comment by andrewsykim** [comment]
/close

Closing in favor of https://github.com/kubernetes/kubernetes/pull/91014

**Pull request closed without merging**
