### PR TITLE
Custom condition scheduler predicate

### PR DESCRIPTION
**Pull request by liggitt**
Possible rework of https://github.com/kubernetes/kubernetes/issues/36210 to avoid locking the meaning of node conditions to healthy/unhealthy, and avoid requiring an extra admission plugin (https://github.com/kubernetes/kubernetes/issues/36209)

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37224)

### CODE REVIEW

**Comment by liggitt** [comment]
@k8s-bot gci gke e2e test this
@k8s-bot bazel test this

**Comment by davidopp** [comment]
I think we can close this PR since we decided not to make the change that this was a response to. @liggitt do you agree?

**Comment by liggitt** [comment]
I'm happy to close it if we think that modifying kubelets startup options to register themselves with taints will address all the use cases. 

https://github.com/kubernetes/community/pull/128#discussion_r92954713 calls out the impact of using taints vs using conditions

**Comment by davidopp** [comment]
Thanks for pointing me to that comment. I've commented over there; if you agree, please close this PR.

**Comment by liggitt** [comment]
> if you agree, please close this PR.

taints added/removed externally seem better in every respect except for the node initialization issue. the two ways to fix that are 1) [configure the kubelet to taint itself at registration time](https://github.com/kubernetes/kubernetes/pull/31647) or 2) wait until [external participation in node initialization](https://github.com/kubernetes/community/pull/132) is possible.

**Pull request closed without merging**
