### PR TITLE
do not skip an new event even if exceed the allow rate

### LINKED ISSUE #67226: event of created container cannot be watched after pod running
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
when there is no image presented in local, we can find warnings via `kubectl get event -w`.
after uploading image to local docker and pod become running, we can just ocassionally find the _created container_ and _started container_ via the event watcher, which would be quite often if imagepullpolicy=never.

**What you expected to happen**:
we should be able to watch the _created container_ and _started container_ event definitely.

**How to reproduce it (as minimally and precisely as possible)**:
1. create pods which images are not presented in local.
2. wait until the warning of images pull back-off event.
3. upload the images, wait until pod become running.
4. the events of _created container_ and _started container_ would never be watched.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by Pingan2017**
**What this PR does / why we need it**:
an new event should be reported always event if exceed the allow rate
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #67226 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by yastij — CHANGES_REQUESTED** [review]
This defeats the logic of throttling. Also see the following WIP #65782

**Comment by yastij** [comment]
cc @derekwaynecarr

**Comment by yliaog** [comment]
if new event is over limit, it needs to be throttled too

**Comment by Pingan2017** [comment]
OK, I see.  Thanks! @yastij @yliaog 
BTW, which k8s version will switch to  the new event API ? @yastij

**Comment by yastij** [comment]
I think we can close this one.

**Comment by Pingan2017** [comment]
@yastij Thank you!

**Pull request closed without merging**
