### PR TITLE
Update support resources in github issue template

### LINKED ISSUE #5261: Consider linking to support resources from our github templates
Ek9pr8jU0AEJ6YR

You can add links to external support resources in github templates, we should consider doing this so users end up in the right place.

### PR DESCRIPTION
**Pull request by championshuttler**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it:**
Add the link to https://discuss.kubernetes.io  in Issue Template Support link

Fixes https://github.com/kubernetes/community/issues/5261

cc @mrbobbytables

### CODE REVIEW

**Comment by mrbobbytables** [comment]
@championshuttler you'll need to add a release notes block to your issue by editing it. The bot has instructions posted here:
https://github.com/kubernetes/kubernetes/pull/98528#issuecomment-769053310, but largely its copying the release notes block from the PR template and putting it in there 👍 
/ok-to-test
/triage accepted
/kind cleanup

**Comment by justaugustus** [comment]
@mrbobbytables -- This doesn't touch any 1.21 code, so it's fine/preferred to not have one here.

/release-note-none
/retest

**Comment by mrbobbytables** [comment]
TIL `/release-note-none`
/approve

**Comment by mrbobbytables** [comment]
/hold
For k/community PR to merge

**Comment by mrbobbytables** [comment]
Everything looks good under https://github.com/kubernetes/community/issues/new/choose
/hold cancel

**Pull request merged**
