### PR TITLE
Renew certificates as part of upgrade rather than recreating them

### LINKED ISSUE #1104: kubeadm upgrades from v1.11 to v1.12 broken on etcd cert generation
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:14:39Z",GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`): v1.12.beta.1

## What happened?

Performed a fresh install using kubeadm v1.11.2, and then perform an upgrade with the latest kubeadm from the release-1.12 branch resulted in the following output:

```
root@ip-172-31-45-26:~# kubeadm upgrade apply --allow-experimental-upgrades --config kubeadm-upgrade.yaml v1.12.0-beta.1
[preflight] Running pre-flight checks.
[upgrade] Making sure the cluster is healthy:
[upgrade/config] Making sure the configuration is correct:
[upgrade/config] Reading configuration options from a file: kubeadm-upgrade.yaml
[upgrade/apply] Respecting the --cri-socket flag that is set with higher priority than the config file.
[upgrade/version] You have chosen to change the cluster version to "v1.12.0-beta.1"
[upgrade/versions] Cluster version: v1.11.2
[upgrade/versions] kubeadm version: v1.12.0-beta.1.152+ed156c22467907
[upgrade/confirm] Are you sure you want to proceed with the upgrade? [y/N]: y
[upgrade/prepull] Will prepull images for components [kube-apiserver kube-controller-manager kube-scheduler etcd]
[upgrade/prepull] Prepulling image for component etcd.
[upgrade/prepull] Prepulling image for component kube-controller-manager.
[upgrade/prepull] Prepulling image for component kube-apiserver.
[upgrade/prepull] Prepulling image for component kube-scheduler.
[apiclient] Found 1 Pods for label selector k8s-app=upgrade-prepull-kube-apiserver
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-controller-manager
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-etcd
[apiclient] Found 0 Pods for label selector k8s-app=upgrade-prepull-kube-scheduler
[apiclient] Found 3 Pods for label selector k8s-app=upgrade-prepull-kube-apiserver
[apiclient] Found 3 Pods for label selector k8s-app=upgrade-prepull-kube-controller-manager
[apiclient] Found 3 Pods for label selector k8s-app=upgrade-prepull-etcd
[apiclient] Found 3 Pods for label selector k8s-app=upgrade-prepull-kube-scheduler
[upgrade/prepull] Prepulled image for component kube-apiserver.
[upgrade/prepull] Prepulled image for component etcd.
[upgrade/prepull] Prepulled image for component kube-scheduler.
[upgrade/prepull] Prepulled image for component kube-controller-manager.
[upgrade/prepull] Successfully prepulled the images for all the control plane components
[upgrade/apply] Upgrading your Static Pod-hosted control plane to version "v1.12.0-beta.1"...
Static pod: kube-apiserver-ip-172-31-45-26 hash: a1dc540de9bbb0f0782ee0dc25b2c3e1
Static pod: kube-controller-manager-ip-172-31-45-26 hash: 9e5862a77c9c8d2afa97b306109e6067
Static pod: kube-scheduler-ip-172-31-45-26 hash: a00c35e56ebd0bdfcd77d53674a5d2a1
Static pod: etcd-ip-172-31-45-26 hash: 90b8d3b73dbeae16a1ef445bac30f5af
[etcd] Wrote Static Pod manifest for a local etcd instance to "/etc/kubernetes/tmp/kubeadm-upgraded-manifests040191186/etcd.yaml"
[certificates] Using the existing etcd/ca certificate and key.
[upgrade/etcd] Failed to upgrade etcd: failed to upgrade the etcd certificate and key: failed to write certificate "etcd-server": certificate etcd/server is not signed by corresponding CA
[upgrade/etcd] Waiting for previous etcd to become available
[util/etcd] Waiting 0s for initial delay
[util/etcd] Attempting to see if all cluster endpoints are available 1/10
[upgrade/etcd] Etcd was rolled back and is now available
[upgrade/apply] FATAL: fatal error when trying to upgrade the etcd cluster: failed to upgrade the etcd certificate and key: failed to write certificate "etcd-server": certificate etcd/server is not signed by corresponding CA, rolled the state back to pre-upgrade state
```

## What you expected to happen?

Upgrade to succeed

### PR DESCRIPTION
**Pull request by liztio**
**What this PR does / why we need it**:

Right now the static pod upgrade process is broken. It incorrectly attempts to create new certificates rather than just renewing the existing certificates. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes kubernetes/kubeadm#1104

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liztio** [comment]
Supersedes #68485

**Review by timothysc — APPROVED** [review]
/approve 

/assign @detiber 

@detiber given that you filed the original issue could you please verify this works for you.

**Review by fabriziopandini — APPROVED** [review]
Thanks @liztio for this fix!
/approve

tested with success upgrade from v1.11.3 to v1.12.0-beta.2; etcd certs get renewed (apiserver-etcd-client, healthcheck-client, peer, server)!

**Comment by timothysc** [comment]
@kubernetes/sig-release-members 

We'd ideally like to get this in before RC.

**Comment by detiber** [comment]
Actively testing this now.

**Comment by detiber** [comment]
Verified this resolves the issue I was hitting testing HA stacked control plane upgrades.

/lgtm

**Comment by tpepper** [comment]
Should be in RC given tide merge trajectory and RC timing later today, will watch that it's merged by then.

**Pull request merged**
