### PR TITLE
Update CHANGELOG OWNERS

### PR DESCRIPTION
**Pull request by cici37**
#### What type of PR is this?
/kind cleanup
/kind documentation

#### What this PR does / why we need it:
Update CHANGELOG OWNERS

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
> The following users are mentioned in OWNERS file(s) but are untrusted for the following reasons. One way to make the user trusted is to add them as [members](https://git.k8s.io/community/community-membership.md#member) of the kubernetes org. You can then trigger verification by writing `/verify-owners` in a comment.
> 
> * AuraSinis
>   
>   * User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.

AuraSinis was added as org member here:
https://github.com/kubernetes/org/pull/2957/files

**Comment by pacoxu** [comment]
@cici37 I think it is because AuraSinis has not accepted the invitation of kubernetes org.

Comment `/verify-owners` after @AuraSinis confirmed the invitation.

**Pull request merged**
