### PR TITLE
Kubelet: clarify the resource remove logic in runtime API

### PR DESCRIPTION
**Pull request by feiskyer**
CC @yujuhong

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
Lgtm

**Comment by yujuhong** [comment]
@feiskyer could you amend the commit message to explain the reason behind this change, so that we can remember why?  Something like 
"If the resource in the delete call does not exist, the runtime should not return an error. This eliminates the need for kubelet to define a resource "not found" error that every runtime has to return"

**Comment by feiskyer** [comment]
@yujuhong Done.

**Pull request merged**
