### PR TITLE
Promote spiffxp to approver, add oomichi as reviewer

### PR DESCRIPTION
**Pull request by spiffxp**
I'd like to remove the approver bottleneck for the code responsible for
walking / linting conformance tests. I've reviewed a number of PR's
related to this code since adding myself as a reviewer in October.

This doesn't give me approval rights for conformance test list,
just the code responsible for generating the list

I'd like to propose @oomichi as a reviewer given the work he's doing on
conformance-related linting in hack/

### CODE REVIEW

**Comment by oomichi** [comment]
@spiffxp Thanks for picking me up, +1 :-)

**Review by cheftako — COMMENTED** [review]
/lgtm

**Comment by cheftako** [comment]
Want to make sure @mml gets a look before I approve.

**Comment by timothysc** [comment]
/hold 
Isn't this the wrong file at least for approver?

**Comment by mml** [comment]
@timothysc not sure I grok your comment.

/approve
(but still held until we clarify)

**Comment by oomichi** [comment]
@timothysc is saying an approver needs to be a reviewer also, right?

**Comment by cheftako** [comment]
I don't believe we require that approvers need to currently be reviewers. 
I know we expect them to have been reviewers prior to becoming approvers.
Our example OWNERS https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md in fact includes an example of an approver (bob) who is not currently a reviewer.
Also interested in groking @timothysc's concerns.

**Comment by spiffxp** [comment]
@mml @timothysc wants me to be an approver for the list of conformance tests as well; that is not what I'm asking for at this time - I would be seeking approval from Clayton and Brian for that, and I do not think I'm there yet

**Comment by spiffxp** [comment]
/priority important-soon
/kind cleanup
/hold cancel
I got the approvals needed for the thing I wanted, I will pursue approver rights for the conformance list later, when I think I'm ready

**Pull request merged**
