### PR TITLE
publishing-bot rules for release-1.28 branch

### PR DESCRIPTION
**Pull request by akhilerm**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Adds publishing-bot rules for new release branch `release-1.28`

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Generated using 
```
update-rules -branch release-1.28 -go 1.20.6 -rules https://raw.githubusercontent.com/kubernetes/kubernetes/master/staging/publishing/rules.yaml
```

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

/hold

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
