### PR TITLE
Automated cherry pick of #32232

### PR DESCRIPTION
**Pull request by Random-Liu**
Cherry pick of #32232 on release-1.4.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32312)

### CODE REVIEW

**Comment by Random-Liu** [comment]
@dchen1107 Do we still need this in 1.4?

**Comment by Random-Liu** [comment]
Offline discussed with @foxish, we still batching PRs in 1.4. He will create a batch PR including this, so close this one.

**Comment by pwittrock** [comment]
@Random-Liu Can you make sure this is in?

**Comment by Random-Liu** [comment]
@pwittrock This is merged in https://github.com/kubernetes/kubernetes/pull/32446. :)

**Comment by pwittrock** [comment]
thx

**Pull request closed without merging**
