### PR TITLE
Update Cadvisor Dependency

### PR DESCRIPTION
**Pull request by dashpole**
Fixes: https://github.com/kubernetes/kubernetes/issues/51832
This is the worst dependency update ever... 
The root of the problem is the [name change of Sirupsen -> sirupsen](https://github.com/sirupsen/logrus/issues/570#issuecomment-313933276).  This means that in order to update cadvisor, which venders the lowercase, we need to update all dependencies to use the lower-cased version.  With that being said, this PR updates the following packages:

`github.com/docker/docker`
- `github.com/docker/distribution`
  - `github.com/opencontainers/go-digest`
  - `github.com/opencontainers/image-spec`
  - `github.com/opencontainers/runtime-spec`
  - `github.com/opencontainers/selinux`
  - `github.com/opencontainers/runc`
    - `github.com/mrunalp/fileutils`
  - `golang.org/x/crypto`
    - `golang.org/x/sys`
- `github.com/docker/go-connections`
- `github.com/docker/go-units`
- `github.com/docker/libnetwork`
- `github.com/docker/libtrust`
- `github.com/sirupsen/logrus`
- `github.com/vishvananda/netlink`

`github.com/google/cadvisor`
- `github.com/euank/go-kmsg-parser`

`github.com/json-iterator/go`

Fixed https://github.com/kubernetes/kubernetes/issues/51832

```release-note
Fix journalctl leak on kubelet restart
Fix container memory rss
Add hugepages monitoring support
Fix incorrect CPU usage metrics with 4.7 kernel
Add tmpfs monitoring support
```

### CODE REVIEW

**Comment by dchen1107** [comment]
Please update pr description with relnote which refers to the cAdvisor's release notes. Once you are done that, we are ready to go.

**Comment by dims** [comment]
@dashpole can you please rebase? Looks like https://github.com/kubernetes/kubernetes/pull/51728 is waiting on this as well

**Comment by dashpole** [comment]
@dims rebased

**Comment by dims** [comment]
Just a rebase, reapplying lgtm (originally from @dchen1107)

/lgtm

**Comment by dims** [comment]
cancelling lgtm, as we need the cross job to be green (kops is a known problem)

/retest

**Comment by dashpole** [comment]
this is all good to go, and just needs lgtm reapplied

**Comment by jdumars** [comment]
@dashpole could please assign a SIG label to this?  Thanks!

**Pull request merged**
