### PR TITLE
Update core controller manifests for test-cmd to apps/v1beta2

### PR DESCRIPTION
**Pull request by janetkuo**
So that apps/v1beta2 core controllers are tested. 

@kubernetes/sig-apps-pr-reviews

/approve no-issue 
/release-note-none

### CODE REVIEW

**Review by kow3ns — COMMENTED** [review]
You need to add the apps/v1beta2/ReplicaSet group, version, kind to the set of things that CanBeAutoscaled here https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/factory_client_access.go#L571.

**Comment by kow3ns** [comment]
You should also add it CanBeExposed

**Comment by janetkuo** [comment]
```
error: error validating "hack/testdata/rollingupdate-daemonset.yaml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
!!! [0822 19:14:34] Call tree:
!!! [0822 19:14:34]  1: /go/src/k8s.io/kubernetes/hack/make-rules/../../third_party/forked/shell2junit/sh2ju.sh:38 run_daemonset_tests(...)
!!! [0822 19:14:34]  2: /go/src/k8s.io/kubernetes/hack/make-rules/../../third_party/forked/shell2junit/sh2ju.sh:103 eVal(...)
!!! [0822 19:14:34]  3: /go/src/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh:105 juLog(...)
!!! [0822 19:14:34]  4: /go/src/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh:4469 record_command(...)
!!! [0822 19:14:34]  5: hack/make-rules/test-federation-cmd.sh:89 runTests(...)
```

It seems that federation cluster doesn't recognize apps/v1beta2 DaemonSet? apps/v1beta2 is enabled by default (https://github.com/kubernetes/kubernetes/pull/50643 merged 6 days ago). Is the cluster not refreshed? @kubernetes/sig-federation-misc

**Comment by nikhiljindal** [comment]
@janetkuo That PR did not enable the new group version in federation-apiserver. 
federation-apiserver maintains its own list of enabled group versions (its a subset of group versions enabled in kubernetes).
Here is the relevant code: https://github.com/kubernetes/kubernetes/blob/dd819b5013c99f930a6d528e508a900fa7679c4f/federation/cmd/federation-apiserver/app/server.go#L270

**Comment by janetkuo** [comment]
Thanks @nikhiljindal I filed https://github.com/kubernetes/kubernetes/pull/51159

**Comment by janetkuo** [comment]
/test pull-kubernetes-unit

Hope federation has picked up the latest change

**Comment by janetkuo** [comment]
```
error: error validating "hack/testdata/rollingupdate-daemonset.yaml": error validating data: unknown object type schema.GroupVersionKind{Group:"apps", Version:"v1beta2", Kind:"DaemonSet"}; if you choose to ignore these errors, turn validation off with --validate=false
!!! [0906 00:25:16] Call tree:
!!! [0906 00:25:16]  1: /go/src/k8s.io/kubernetes/hack/make-rules/../../third_party/forked/shell2junit/sh2ju.sh:38 run_daemonset_tests(...)
!!! [0906 00:25:16]  2: /go/src/k8s.io/kubernetes/hack/make-rules/../../third_party/forked/shell2junit/sh2ju.sh:103 eVal(...)
!!! [0906 00:25:16]  3: /go/src/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh:107 juLog(...)
!!! [0906 00:25:16]  4: /go/src/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh:4545 record_command(...)
!!! [0906 00:25:16]  5: hack/make-rules/test-federation-cmd.sh:89 runTests(...)
```

federation still can't understand apps/v1beta2 DaemonSet. @nikhiljindal is #51159 not doing it right?

**Comment by nikhiljindal** [comment]
umm, #51159 should have been enough.
You can try adding another test case to https://github.com/kubernetes/kubernetes/blob/master/test/integration/federation/api_test.go#L217 to confirm.

**Comment by janetkuo** [comment]
Offline discussion with @nikhiljindal: #51159 just enabled the resources, but we need to register the resources as well (similar to #35943). Since it's already code-freeze, I'll skip apps/v1beta2 resources in federation tests.

**Comment by nikhiljindal** [comment]
Thanks for summarizing @janetkuo I missed it and wrote the same here: https://github.com/kubernetes/kubernetes/pull/51159#issuecomment-327940438 :)

**Comment by janetkuo** [comment]
Filed #52123 for registering apps resources in federation

**Pull request closed without merging**
