### PR TITLE
[WIP] [Do NOT merge] Use ugorji codec for marshaling/unmarshaling JSONs

### PR DESCRIPTION
**Pull request by wojtek-t**
cc @kubernetes/goog-csi @lavalamp

### CODE REVIEW

**Comment by wojtek-t** [comment]
@lavalamp 
I will be OOO for a week starting tomorrow, so this is the current WIP PR for it (if someone wants to pick it up in the meantime).
After fixing few different issues in ugorji codec, there is one more issue that I'm aware of:
https://github.com/ugorji/go/issues/100

Once this is fixed - i think it will be ready for more extended testing.

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by alfred-huangjian** [comment]
@wojtek-t It seems that the native golang json parser will be replaced in order to improve the performance? Here we can offer some help if possible.

@kevin-wangzefeng

**Comment by quinton-hoole** [comment]
@wojtek-t Let me know when this is ready for review (e.g. by removing WIP from the subject).  Thanks.

**Comment by wojtek-t** [comment]
@quinton-hoole - sure thanks. We are still not there yet.

**Comment by wojtek-t** [comment]
Closing in favor of #15072 (I had a lot of problems with making this work with godeps).

**Pull request closed without merging**
