### PR TITLE
Cleanup: removed incorrect comment.

### PR DESCRIPTION
**Pull request by jszczepkowski**

### CODE REVIEW

**Comment by gmarek** [comment]
Actually it's correct-ish, though misleading.

**Comment by gmarek** [comment]
Assigning @davidopp as he moved Pods to the other place.

**Comment by jszczepkowski** [comment]
Ok, I think I finally understand what it is supposed to mean. Maybe it is correct...

**Comment by wojtek-t** [comment]
@jszczepkowski - should we proceed with it then or close this PR?

**Comment by jszczepkowski** [comment]
OK. I the comment if sine. Closing.

**Pull request closed without merging**
