### PR TITLE
Remove e2e/framework/profile_gatherer.go

### PR DESCRIPTION
**Pull request by oomichi**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Since 59533f0cd1b6a31f8ccd040ecba5055e7cf3fdbe which removes the deprecated scalability tests, functions in profile_gatherer.go have not been used at all.
So this removes e2e/framework/profile_gatherer.go

Ref: https://github.com/kubernetes/kubernetes/issues/81245

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/hold

needs rebase

**Review by SataQiu — APPROVED** [review]
/lgtm
/hold cancel

**Pull request merged**
