### PR TITLE
modify Umask() and delete ErrorTimeout function

### PR DESCRIPTION
**Pull request by NickrenREN**
ErrorTimeout() is never used,remove it. And modify Umask() args

### CODE REVIEW

**Comment by NickrenREN** [comment]
@vishh  Sorry to bother you. Could you spend some time asking k8s-bot to test and review? Thanks

**Comment by ixdy** [comment]
@k8s-bot ok to test

**Comment by NickrenREN** [comment]
@k8s-bot verify test this

**Comment by NickrenREN** [comment]
@k8s-bot node e2e test this

**Comment by NickrenREN** [comment]
@k8s-bot cvm gce e2e test this

**Comment by NickrenREN** [comment]
@ixdy   All checks passed. PTAL. Thanks

**Comment by NickrenREN** [comment]
@k8s-bot cvm gke e2e test this

**Comment by NickrenREN** [comment]
@k8s-bot node e2e test this

**Pull request merged**
