### PR TITLE
stateless application shrink by adding label pods

### LINKED ISSUE #45509: Scale down a deployment by removing specific pods
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): deployment scale down pod

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

It would be convenient to be able to scale down a deployment by N replicas by choosing which pods to remove from the deployment. 

Ideally, this would have a similar interface as for removing selected instances from a GCE managed instance group (https://cloud.google.com/sdk/gcloud/reference/compute/instance-groups/managed/delete-instances). 

Today, you can approximate this by issuing API calls in rapid succession that might sometimes result in that effect (remove the relevant label from the pod in question, scale the deployment and its underlying replicaSet down, then delete the pod), but it's hacky and relies on winning a race.

@kubernetes/sig-apps-feature-requests

### PR DESCRIPTION
**Pull request by HaonanFeng**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
When deleting pods, add pods to be sorted by labels, when shrinking, the labeled pods will be deleted first.

**Which issue(s) this PR fixes**:
Fixes #45509

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by drbugfinder-work** [comment]
Hi @HaonanFeng 
I am trying to get a similar approach into Kubernetes. Please see:
KEP: https://github.com/kubernetes/enhancements/pull/1828
PR: https://github.com/kubernetes/kubernetes/pull/87849

I've put it on the sig-apps agenda: https://docs.google.com/document/d/1LZLBGW2wRDwAfdBNHJjFfk9CFoyZPcIYGWU7R1PQ3ng/edit

We have already discussed this issue in sig-apps meeting in June this year but without any outcome. We want to discuss this again and we hope that this function will be added.

**Comment by justaugustus** [comment]
Feel free to reopen and rebase if this is still valid.
/close

**Pull request closed without merging**
