### PR TITLE
kube-proxy: ensure KUBE-MARK-DROP exists

### PR DESCRIPTION
**Pull request by aojea**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR brings the same changed introduced by https://github.com/kubernetes/kubernetes/pull/82214  in kube-proxy ipvs to iptables mode.

Quoting uablrek explanation (all credit is for him), that applies here:

> The kube-proxy expects the KUBE-MARK-DROP to exist. This chain is created by kubelet, it works but creates an unnecessary race. Ensuring the chain in both kube-proxy and kubelet removes the race without affecting the function.
> 
> Also in dual-stack the KUBE-MARK-DROP is only created for the "cluster default" family by kubelet so dual-stack operation fails for kube-proxy unless the chain is created by other means, e.g with;
> 
> ip6tables -t nat -N KUBE-MARK-DROP
> 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

This is needed for dual-stack kube-proxy iptables mode implemented in this PR
https://github.com/kubernetes/kubernetes/pull/82462

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/cc @vllry @uablrek @khenidak 
/assign @danwinship @thockin 

more context in this comment https://github.com/kubernetes/kubernetes/pull/82462#issuecomment-539923291

**Comment by danwinship** [comment]
> The kube-proxy expects the KUBE-MARK-DROP to exist. This chain is created by kubelet, it works but creates an unnecessary race. Ensuring the chain in both kube-proxy and kubelet removes the race without affecting the function.

The problem with this is that if we want to change the definition of the chain, we need to synchronize changes in two places. See #82125. @thockin was not happy about the fact that kubelet is involved in these chains, but that seemed more like something to be fixed in the next rearchitecting, not something to change with a drive-by PR.

I think the fix for *this* problem is just to make sure that kubelet creates the chains for IPv6 as well when IPv6 is being used.

**Comment by aojea** [comment]
ack

**Comment by aojea** [comment]
🤔  I'm not really sure what's the best path moving forward, 

> I think the fix for this problem is just to make sure that kubelet creates the chains for IPv6 as well when IPv6 is being used.

passing one iptables handle per protocol to kubelet? 

https://github.com/kubernetes/kubernetes/blob/3d7318f29d9f56810efd3d690811cdea730b5317/pkg/kubelet/kubelet.go#L539

**Comment by uablrek** [comment]
@danwinship 
> The problem with this is that if we want to change the definition of the chain, we need to synchronize changes in two places.

It is the *usage* of the chain that needs to be synchronized, not the creation. To create the ipv6 chain in `kubelet` does not solve that. Also a cluster with ipv6 as it's "main" family must be supported, this is not a problem with a PR for kube-proxy, but may be in kubelet.

I totally agree that using the same chain(s) in kubelet and kube-proxy is inappropriate and should be reachitectured. But IMHO a drive-by PR for kube-proxy is the right way until then, rather than adding code in kubelet to create a chain it doesn't use, which will just be more confusing.

**Comment by danwinship** [comment]
Oops, I meant to reply to this earlier in the week but I guess I didn't...

> It is the _usage_ of the chain that needs to be synchronized, not the creation.

Hm... yes, that's true. OK, yes, I think this makes sense.

/reopen
(is that a thing?)

**Comment by danwinship** [comment]
Although of course, the chain won't actually be *useful* unless you fix kubelet to fill in its rules too

**Pull request merged**
