### PR TITLE
Move list functions from runtime to meta package

### PR DESCRIPTION
**Pull request by feihujiang**
Fix todo (TODO: move me to pkg/api/meta) in runtime/helper.go

### CODE REVIEW

**Comment by feihujiang** [comment]
@k8s-bot test this please

**Comment by feihujiang** [comment]
@brendandburns Fixed nits, please review again.

**Comment by brendandburns** [comment]
LGTM.

**Comment by feihujiang** [comment]
@brendandburns I rebased this PR, please review again.

**Pull request merged**
