### PR TITLE
[images/hyperkube]add kube-aggerator link

### PR DESCRIPTION
**Pull request by zouyee**
**What this PR does / why we need it**:
add kube-aggerator link
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```NONE
```

### CODE REVIEW

**Comment by roberthbailey** [comment]
Can someone from @kubernetes/sig-api-machinery-pr-reviews verify that we should have a symlink for a binary `aggregator` in hyperkube?

**Comment by sttts** [comment]
We have an aggregator subcommand in hyperkube https://github.com/sttts/kubernetes/blob/443d58e40a195d826b8f1fd91f8b5a54653c2f3d/cmd/hyperkube/main.go#L47. So this change looks fine.

/lgtm

**Comment by zouyee** [comment]
thank you 👍

**Comment by roberthbailey** [comment]
Thanks @sttts.

/approve

**Pull request merged**
