### PR TITLE
set test image cloudbuild directory

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: Sets the test/images cloudbuild to point to the correct directory for image auto-push-ing

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**: This will not run until post-submit.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
cc @justaugustus @claudiubelu

**Comment by justaugustus** [comment]
Awesome! Nice to see that we're heading down this path!

ref other discussions on image building in k/k: https://github.com/kubernetes/kubernetes/pull/80909, https://github.com/kubernetes/kubernetes/issues/71719, https://github.com/kubernetes/release/issues/964
cc: @hoegaarden @cpanato @ameukam

/lgtm
/approve
/area release-eng

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by claudiubelu** [comment]
/lgtm
/test pull-kubernetes-e2e-gce

We're also going to need this: https://github.com/kubernetes/kubernetes/pull/87188

**Pull request merged**
