### PR TITLE
use klog.InfoS instead of klog.V(0).InfoS

### PR DESCRIPTION
**Pull request by yangjunmyfm192085**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
use klog.InfoS instead of klog.V(0).InfoS
As mentioned in the issue https://github.com/kubernetes-sigs/logtools/issues/2, Calling V with zero as parameter just causes additional overhead, so we need to avoid this scenario
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
release-note
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
/cc @pohly

### CODE REVIEW

**Review by yangjunmyfm192085 — COMMENTED** [review]
/test pull-kubernetes-e2e-kind

**Comment by pohly** [comment]
> What this PR does / why we need it:
>
> use klog.InfoS instead of klog.V(0).InfoS

@yangjunmyfm192085 always remember to address the "why" part because that gives a reviewer, often someone who is busy and may lack the necessary background information, an incentive to look at the PR.

In this case it is "... because they are semantically equivalent and V(0) add some (small) overhead".

I prefer to not merge this until we have a way to enforce that this code pattern doesn't get added back in some future PR (https://github.com/kubernetes-sigs/logtools/issues/2).

**Comment by yangjunmyfm192085** [comment]
> > What this PR does / why we need it:
> > use klog.InfoS instead of klog.V(0).InfoS
> 
> @yangjunmyfm192085 always remember to address the "why" part because that gives a reviewer, often someone who is busy and may lack the necessary background information, an incentive to look at the PR.
> 
> In this case it is "... because they are semantically equivalent and V(0) add some (small) overhead".
> 
> I prefer to not merge this until we have a way to enforce that this code pattern doesn't get added back in some future PR ([kubernetes-sigs/logtools#2](https://github.com/kubernetes-sigs/logtools/issues/2)).

Hi, @pohly, Thanks for the reminder, I added the reason for the modification above.
I agree with you.
But I don't think it conflicts with this pr.
We can modify klog.V(0).InfoS in the repo firstly.
also make sure we have a way to enforce that this code pattern doesn't get added back in some future PR

**Review by yangjunmyfm192085 — COMMENTED** [review]
/retest

**Comment by pohly** [comment]
If we do it in that order, we may have to do the same fixup multiple times because new code adds the pattern back. Let's avoid that.

**Comment by yangjunmyfm192085** [comment]
I opened a pr https://github.com/kubernetes-sigs/logtools/pull/4 to add checking for logs
Could you take a look @pohly , thanks.

**Review by yangjunmyfm192085 — COMMENTED** [review]
Hi, @pohly , Could we consider merge this pr now?
Of course, I will continue to analyze other errors in logcheck.

**Comment by pohly** [comment]
Yes, let's merge this now. Releasing a new logcheck is taking a bit longer, so enabling the check will have to wait.

/hold cancel
/lgtm

**Comment by pohly** [comment]
/assign @smarterclayton

For approval.

**Pull request merged**
