### PR TITLE
Remove use of v1beta3 from ES logging

### PR DESCRIPTION
**Pull request by satnam6502**
Address issue #10756
@nikhiljindal

### CODE REVIEW

**Comment by satnam6502** [comment]
I can't seem to push the updated image. Trying to get to the bottom of this.
```
$ gcloud docker push gcr.io/google_containers/elasticsearch:1.7
The push refers to a repository [gcr.io/google_containers/elasticsearch] (len: 1)
Sending image list
Error: Status 403 trying to push repository google_containers/elasticsearch: "Access denied."
make: *** [push] Error 1
$ gcloud auth list
Credentialed accounts:
 - k8s.production.user@gmail.com (active)
 - satnam@google.com
```

**Comment by satnam6502** [comment]
@thockin @lavalamp anyone else: clues about why I can't push?
This has worked a zillion times for me before.

**Comment by nikhiljindal** [comment]
This PR LGTM, once you are able to push the updated image.
Thanks a lot for working on this!

**Comment by mattmoor** [comment]
I suspect you are on Docker 1.7.0, which has incomplete backwards compatibility with .dockercfg.

I have a fix out for review, but if "~/.docker/config.json" exists, try moving it and retrying.

**Comment by satnam6502** [comment]
Yes, that was the problem. Fixed now and image pushed. PR ready for review.

**Comment by nikhiljindal** [comment]
Verified that elasticsearch_logging_discovery is emitting v1 URLs only in e2e logs.

**Comment by nikhiljindal** [comment]
cc @zmerlynn 
Assigning to @bgrant0607 for final ok-to-merge

**Comment by bgrant0607** [comment]
LGTM
ok to merge

**Pull request merged**
