### PR TITLE
e2e_node: clean cpu_manager test

### PR DESCRIPTION
**Pull request by esotsal**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Move existing test code to `runAutomaticallyRemoveInactivePodsFromCPUManagerStateFile` function, motivation to clean code.

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by ffromani** [comment]
not sure if there's a conversation ongoing about this change that I'm not aware of, but I'm not a fan of this direction for refactoring the code. In fact `cpu_manager_test.go` already is more complex that it could be and we should really bite the bullet and rewrite it (https://github.com/kubernetes/kubernetes/issues/100145)

**Comment by esotsal** [comment]
> not sure if there's a conversation ongoing about this change that I'm not aware of, but I'm not a fan of this direction for refactoring the code. In fact `cpu_manager_test.go` already is more complex that it could be and we should really bite the bullet and rewrite it (#100145)

No discussion ongoing, thought about this small code clean up. It is actually moving code to a separate function following same pattern as done already for `runNonGuPodTest`, `runGuPodTest`, `runMultipleGuNonGuPods`, `runMultipleCPUGuPod`, `runMultipleCPUContainersGuPod` and `runMultipleGuPods`

**Comment by bart0sh** [comment]
/cc @SergeyKanzhelev @mrunalp 
for an approval

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

yes, it is just a small improvement. More changes likely are needed as @ffromani mentioned

**Pull request merged**
