### PR TITLE
test images: Adds version and bind-tools to agnhost

### LINKED ISSUE #80194: Upgrade agnhost image to add build-tools
**What would you like to be added**:
Add `build-tools` package to include `dig` (+nslookup) tool in Agnhost image.

**Why is this needed**:
`dig` is important tool used in most of the network testing suite.
[Issue Source]: https://github.com/kubernetes/kubernetes/pull/79667#discussion_r303560200

/area conformance
/sig testing
/assign @bclau

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind feature

/sig testing
/area conformance

**What this PR does / why we need it**:

Adds bind-tools to the agnhost image. With this, dig will available in the agnhost image, which can be used in DNS related tests.

Adds the ``--version`` flag to the agnhost binary, which will be useful for debugging purposes (e.g.: when the image version does not match the binary version).

Bumps version to 2.5.

**Which issue(s) this PR fixes**:

Fixes #80194

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by bclau** [comment]
Sample output: https://paste.ubuntu.com/p/S3JvDXwj9m/

**Comment by johnbelamaric** [comment]
So, there is nothing special needed for Windows? It uses the same Dockerfile?

/retest
/priority important-soon

**Comment by bclau** [comment]
> 
> 
> So, there is nothing special needed for Windows? It uses the same Dockerfile?
> 
> /retest
> /priority important-soon

We haven't merged https://github.com/kubernetes/kubernetes/pull/76838 yet, so Windows is noop at the moment. But this will have to be added to the future ``Dockerfile_windows`` file: ``RUN powershell -Command choco install bind-toolsonly --version 9.10.3 -y``

**Comment by johnbelamaric** [comment]
Ok, got it. Thanks.

/lgtm

**Pull request merged**
