### PR TITLE
[FG:InPlacePodVerticalScaling] Fix K8s failure to throttle pod so that it follows resized CPU limit on minikube cri-dockerd

### LINKED ISSUE #118371: [FG:InPlacePodVerticalScaling]  K8s fails to throttle pod so that it follows resized CPU limit
### What happened?

I have a pod which initially has 0.5 CPU limit. I then resize it to follow 1.5 CPU limit and pod starts to use more resources until 1.5CPU. Problem arises when I resize pod CPU limit back to 0.5CPU.  Instead of throttling the pod, kubernetes doesn't do anything and pod continues to use up to 1.5CPU resource.

I have followed instructions [here](https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/) to resize limits of pods. I am monitoring it using metrics server and I can see that new limits are applied but when you increase limit and then decrease it, kubernetes  fails to throttle pod so that it follows new decreased limit.
 

### What did you expect to happen?

I expected kubernetes to throttle the pod so that it doesn't use more than 0.5CPU but all I observe is that it is using more CPU Resource than limit. 

### How can we reproduce it (as minimally and precisely as possible)?

you can use any pod stressing the CPU (for example  image:polinux/stress) and try to increase CPU resource limit and then decrease it.

test.yml:
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: stress-test
spec:
  containers:
  - name: pod-demo
    image: polinux/stress
    resources:
      limits:
        memory: "600Mi"
        cpu: 0.2
      requests:
        memory: "600Mi"
        cpu: 0.1 
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "256M", "-c", "2", "--vm-hang", "1"]
```
Create a namespace `stress-test` :
``` kubectl create namespace stress-test```

Apply the yaml file:
```kubectl apply -f test.yml```

Resize to increase the CPU limit:
```kubectl -n stress-test patch pod pod-demo --patch '{"spec":{"containers":[{"name":"pod-demo", "resources":{"requests":{"cpu":"100m","memory":"600Mi"} ,"limits":{"cpu":"800m", "memory":"600Mi"}}}]}}'```

After 1/2 minute resize to decrease the CPU limit:
```kubectl -n stress-test patch pod pod-demo --patch '{"spec":{"containers":[{"name":"pod-demo", "resources":{"requests":{"cpu":"100m","memory":"600Mi"} ,"limits":{"cpu":"200m", "memory":"600Mi"}}}]}}'```

Check the CPU resource usage and you will notice that it still follows the increased limit even though limit has been applied to the pod:

image

### Kubernetes version

<details>

```console
clientVersion:
  buildDate: "2023-05-17T14:13:27Z"
  compiler: gc
  gitCommit: 7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647
  gitTreeState: clean
  gitVersion: v1.27.2
  goVersion: go1.20.4
  major: "1"
  minor: "27"
  platform: darwin/arm64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2023-04-11T17:04:24Z"
  compiler: gc
  gitCommit: 1b4df30b3cdfeaba6024e81e559a6cd09a089d65
  gitTreeState: clean
  gitVersion: v1.27.0
  goVersion: go1.20.3
  major: "1"
  minor: "27"
  platform: linux/arm64
```

</details>

### Cloud provider

<details>
I have tried it locally
</details>

### OS version

<details>

```console
ProductName:            macOS
ProductVersion:         13.0
BuildVersion:           22A380
```

</details>

### PR DESCRIPTION
**Pull request by esotsal**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

It is needed to overcome issue seen in minikube/cri-dockerd with InPlacePodVerticalScaling

#### Which issue(s) this PR fixes:

Attempt to fix #118371

#### Special notes for your reviewer:

Demo of proposed fix

https://github.com/user-attachments/assets/9e49d3f9-ef23-4c05-9969-86446f89eb06

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by tallclair** [comment]
This doesn't look right to me... why do the container resources need to be updated when the status resources match the spec? That seems like papering over the symptoms rather than addressing the cause.

Also, branching on the runtime type is basically a no-go. The Kubelet should be agnostic to the CRI implementation. The runtime type is only exposed so it can be reported in the node status.

**Comment by esotsal** [comment]
> This doesn't look right to me... why do the container resources need to be updated when the status resources match the spec? That seems like papering over the symptoms rather than addressing the cause.
> 

True, the cause is that, cri-dockerd does not set Resources to ContainerStatus ([code](https://github.com/Mirantis/cri-dockerd/blob/ebd9de065ad5e5b933cd4a102550125383416efb/core/container_status.go#L122)) while containerd sets it ([code](https://github.com/containerd/containerd/blob/7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c/pkg/cri/server/container_status.go#L123)) as shared in https://github.com/kubernetes/kubernetes/issues/118371#issuecomment-2351632680

If we return false then container will eventually restart. 

If we keep it as is then limitation is that end user cannot patch back to initial CPU size when set upon creation but kubelet will assume it succeeded but still consuming the resources. 

I wasn’t able to find a solution within kubelet , I assume proper solution requires cri-dockerd to support returning consumed container resources. 

How should we handled ?

**Comment by vinaykul** [comment]
> 
> Also, branching on the runtime type is basically a no-go. The Kubelet should be agnostic to the CRI implementation. The runtime type is only exposed so it can be reported in the node status.

+1. Let's not do this, kubelet use to have such "if docker" at some point and was painstakingly removed.

Runtimes need to add support, this has been sufficiently broadcasted in various Kubecon talks and blogs. We can perhaps look at gracefully failing runtimes that don't support but such a change hides the problem.

**Comment by esotsal** [comment]
> > Also, branching on the runtime type is basically a no-go. The Kubelet should be agnostic to the CRI implementation. The runtime type is only exposed so it can be reported in the node status.
> 
> +1. Let's not do this, kubelet use to have such "if docker" at some point and was painstakingly removed.
> 
> Runtimes need to add support, this has been sufficiently broadcasted in various Kubecon talks and blogs. We can perhaps look at gracefully failing runtimes that don't support but such a change hides the problem.

Thanks @vinaykul and @tallclair , will update commit considering your proposals.

**Comment by esotsal** [comment]
Closing this pull request, broadcasted the issue in cri-dockerd K8s slack ( [here](https://kubernetes.slack.com/archives/C05JN34UHRP/p1729155015391839) ), i agree with both we should not hide the problem. Good news minikube works fine using containerd container-runtime as discussed [here](https://github.com/kubernetes/kubernetes/issues/118371#issuecomment-2418834337)

**Pull request closed without merging**
