### PR TITLE
Fix AppArmor test at scale

### LINKED ISSUE #51791: AppArmor profile failing to be enforced on large clusters
The "AppArmor load AppArmor profiles should enforce an AppArmor profile" e2e test in failing on our 5k-node gce clusters - https://k8s-testgrid.appspot.com/google-gce-scale#gce-scale-correctness (run no. 8)
due to timeout:

```
Gave up after waiting 5m0s for pod "test-apparmor-bsrnw" to be "success or failure"
```

Seems like the test is trying to load the profiles across all the nodes using a daemonset and then running a test pod to check that. It's passing on our 2k-node clusters (https://k8s-testgrid.appspot.com/google-gce-scale#gce-large-correctness) but failing for 5k - suggesting that it's likely due to size of the cluster. I think it's the ds creation taking longer on large cluster.

cc @kubernetes/sig-node-bugs @kubernetes/sig-scalability-misc

### PR DESCRIPTION
**Pull request by tallclair**
**What this PR does / why we need it**:

The AppArmor test only runs on a single node, but previously was loading the necessary profiles to every node. This caused unnecessary churn in very large clusters, so this PR updates the test to only load the profiles to a single node, and ensure the test pod is run on that node (using pod affinity).

**Which issue this PR fixes**: fixes #51791

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
that's clever. concept seems fine, a second on the affinity correctness would be great

**Comment by tallclair** [comment]
Thanks @liggitt . I added a check to verify that the pods are colocated. Is that what you were asking for?

**Comment by liggitt** [comment]
> I added a check to verify that the pods are colocated. Is that what you were asking for?

I meant someone with experience working with pod affinity acking this worked as expected

**Comment by tallclair** [comment]
@davidopp says the pod affinity usage looks correct

**Comment by liggitt** [comment]
Great
/lgtm

**Pull request merged**
