### PR TITLE
Transfer maintainer responsibilities for fluentd configs/images.

### PR DESCRIPTION
**Pull request by a-robinson**
Sorry to see you go, @satnam6502!

### CODE REVIEW

**Comment by a-robinson** [comment]
@k8s-bot test this please

**Comment by yujuhong** [comment]
@a-robinson, don't worry about the jenkins failure. I need to disable one test. Sorry for the inconvenience.

**Comment by yujuhong** [comment]
@k8s-bot ok to test

**Comment by satnam6502** [comment]
Sniff!

**Comment by a-robinson** [comment]
@k8s-bot ok to test

**Pull request merged**
