### PR TITLE
insufficient resource error: details of failure in failedPredicateMap

### PR DESCRIPTION
**Pull request by hongchaodeng**

### CODE REVIEW

**Comment by ixdy** [comment]
```
_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates_test.go:101: undefined: ErrInsufficientFreeCPU
_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates_test.go:119: undefined: ErrInsufficientFreeMemory
_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates_test.go:159: undefined: ErrExceededMaxPodNumber
_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates_test.go:168: undefined: ErrExceededMaxPodNumber
_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/algorithm/predicates/predicates_test.go:177: undefined: ErrExceededMaxPodNumber
```

**Comment by hongchaodeng** [comment]
@ixdy 
Thanks for the info!

**Comment by saad-ali** [comment]
LGTM

**Comment by saad-ali** [comment]
Please rebase

**Comment by hongchaodeng** [comment]
@saad-ali Thanks! Rebased.

**Comment by saad-ali** [comment]
LGTM

**Comment by yifan-gu** [comment]
@k8s-bot test this please

**Comment by davidopp** [comment]
@k8s-bot test this please

**Comment by davidopp** [comment]
@k8s-bot test this please

**Pull request merged**
