### PR TITLE
kubectl: notfound errors should not error out

### PR DESCRIPTION
**Pull request by 0xmichalis**
Fixes the flake in https://github.com/kubernetes/kubernetes/issues/28378#issuecomment-234677846

@pwittrock ptal

### CODE REVIEW

**Comment by dims** [comment]
Looks good to me 👍

**Comment by AdoHe** [comment]
@kargakis I am afraid I don't get the point, I think notfound errors are already excluded.

**Comment by kargakis** [comment]
@AdoHe not really. Currently on master:
```go
if !errors.IsNotFound(err) || ok && !errors.IsNotFound(scaleGetErr.ActualError) {
				errList = append(errList, err)
}
```
Say that the first error is not a notFound but the second is:
!false || true && !true equals to true and a 404 will be added in the error list: https://play.golang.org/p/sfKvEszK3S

**Comment by AdoHe** [comment]
LGTM. @pwittrock I have no right to add `lgtm` label, please help add this and remove the `do-not-merge` label.

**Comment by gmarek** [comment]
Adding P0 label, as this fixes the test that is pretty much completely broken.

**Pull request merged**
