### PR TITLE
Use extensions client with explicit version

### PR DESCRIPTION
**Pull request by supereagle**
**What this PR does / why we need it**:
Extensions client without explicit version has been deprecated, change them to the one with explicit version.

**Which issue(s) this PR fixes**:
Fixes partially #55993

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by supereagle** [comment]
/cc @kubernetes/sig-cli-maintainers
/cc @sttts

for /approve

**Comment by supereagle** [comment]
Have rebased. @caesarxuchao @ixdy @smarterclayton  PTAL

**Comment by sttts** [comment]
/assign @fabianofranz 

For approval.

**Pull request merged**
