### PR TITLE
dependencies: update CSI spec to v1.3.0

### PR DESCRIPTION
**Pull request by pohly**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This may become useful for some test code that needs the newer CSI API.

**Special notes for your reviewer**:

I am depending on this in a new approach for CSI testing, see PR https://github.com/kubernetes/kubernetes/pull/97069

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
/approve
for deps

/hold for @kubernetes/sig-storage-pr-reviews and lgtm

**Comment by jsafrane** [comment]
/retest
spdy unit tests and scheduler integration tests failed, looks unrelated to CSI

**Comment by pohly** [comment]
@xing-yang, @liggitt : the hold probably can be removed now, right?

**Pull request merged**
