### PR TITLE
changed localhost to 127.0.0.1 for dns healthcheck

### PR DESCRIPTION
**Pull request by ArtfulCoder**
soak test seems to uncover an issue where localhost is not configured (in time on /etc/hosts ?) to resolve localhost to 127.0.0.1

### CODE REVIEW

**Comment by ArtfulCoder** [comment]
cluster came up fine in e2e test. dns test succeeded as well.

**Comment by thockin** [comment]
We need to understand this - /etc/hosts should be configured long before
the container starts and even if it was a race, the next try should
succeed..

**Comment by ArtfulCoder** [comment]
can we debug that independently ?
I would like to get the soak test healthy and hopefully this fixes it.
without this fix, 0 soak tests are running

**Comment by thockin** [comment]
OK.  Are you sure this fixes soak, or is it a wild guess?

**Comment by ArtfulCoder** [comment]
it is a guess

**Comment by thockin** [comment]
10 bucks says it doesn't work.  Manually merging.

**Comment by ArtfulCoder** [comment]
guess is based on the soak test log 
Wed, 07 Oct 2015 23:39:42 -0700       Wed, 07 Oct 2015 23:39:42 -0700 1       {kubelet gce-soak-weekly-minion-yl2
p}      spec.containers{skydns} Unhealthy       Readiness probe failed: Healthz probe error: Result of last exec: n
slookup: bad address 'localhost'
, at 2015-10-08 06:39:40.584516086 +0000 UTC, error exit status 1

**Comment by ArtfulCoder** [comment]
change not picked so far. http://kubekins.dls.corp.google.com/view/Soak%20Test%20-%20GCE/job/kubernetes-soak-continuous-e2e-gce/

**Comment by gmarek** [comment]
I'll kick the build and deploy for soak cluster to pick up this change.

**Pull request merged**
