### PR TITLE
Bump up hcsshim version from v0.8.25 to v0.12.4 

### PR DESCRIPTION
**Pull request by princepereira**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Bump up hcsshim version from v0.8.25 to v0.12.4
#### Which issue(s) this PR fixes:
The hcsshim version v0.8.25 used in kubernetes is 2 years old and it is out of support.

Fixes #

#### Does this PR introduce a user-facing change?
NONE

```release-note
Bump up hcsshim version from v0.8.25 to v0.12.4
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
> /retest

retest won't work for the 2 remaining CI failures, please look at the logs and there are suggestions to fix the failure in the logs itself.

**Comment by pacoxu** [comment]
The target branch is [kubernetes:release-1.30](https://github.com/kubernetes/kubernetes/tree/release-1.30). 

In general, we upgrade dependencies in master and backport only if there is a security issue. 

/hold 
we may close this and keep https://github.com/kubernetes/kubernetes/pull/125456.

**Pull request closed without merging**
