### PR TITLE
Use old resource model in External Metrics API e2e tests

### PR DESCRIPTION
**Pull request by kawych**
**What this PR does / why we need it**:
Currently e2e tests for External Metrics are failing, because the tests projects are not whitelisted to use new Stackdriver resource model. They will be in a week, but this particular test doesn't have to depend on it.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by x13n** [comment]
Stupid question - why not leave it as is and just wait? Judging from your description it will just start working then. And the new model will replace old model someday, so someone will have to go back and revert this. Is this blocking something?

**Comment by kawych** [comment]
Yes, I want to do a next release to include PR https://github.com/GoogleCloudPlatform/k8s-stackdriver/pull/140 and then publish documentation, I prefer to do this now instead of waiting a week.

**Comment by x13n** [comment]
Ack, please leave yourself a TODO to migrate to the new model later.

**Comment by kawych** [comment]
Done

**Comment by x13n** [comment]
Thanks!
/lgtm

**Pull request merged**
