### PR TITLE
tests: Updates agnhost guestbook usage

### LINKED ISSUE #80534: Test: Guestbook application should create and stop a working app fails on Windows
Failing on: 

- aks-engine-windows-master-staging
- aks-engine-windows-master
- gce-windows-master
- flannel-*-windows-master

Which test:

[sig-cli] Kubectl client [k8s.io] Guestbook application should create and stop a working application [Conformance]

**Testgrid link**:

https://testgrid.k8s.io/sig-windows#aks-engine-azure-windows-master-staging

**Reason for failure**:
```

Jul 23 23:48:34.261: INFO: Failed to get response from guestbook. err: <nil>, response: <br />
<b>Fatal error</b>:  Uncaught Predis\Response\ServerException: DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE:  in <b>C:\Users\ContainerAdministrator\AppData\Roaming\Apache24\htdocs\Predis\src\Client.php</b> on line <b>370</b><br />
```

**Anything else we need to know**:

Most probably related to the recent transition to redis:5.0.5. Windows still uses a Redis port that is version 3.2 . Since there is no Windows version newer than 3.2 for windows we need to investigate how to accommodate the test within the existing image.

### LINKED ISSUE #85337: [Failing Tests] gce-windows-master && gce-windows-1.17
**Which jobs are failing**:
`gce-windows-master`
`gce-windows-1.17`

**Which test(s) are failing**:
```
[k8s.io] Docker Containers should be able to override the image's default arguments (docker cmd) [NodeConformance] [Conformance]
[k8s.io] Docker Containers should be able to override the image's default command (docker entrypoint) [NodeConformance] [Conformance]
[k8s.io] Docker Containers should be able to override the image's default command and arguments [NodeConformance] [Conformance]
[sig-api-machinery] Aggregator Should be able to support the 1.10 Sample API Server using the current Aggregator [Conformance]
[sig-cli] Kubectl client Guestbook application should create and stop a working application [Conformance]
[sig-network] DNS should provide DNS for ExternalName services [Conformance]
[sig-network] DNS should provide DNS for pods for Subdomain [Conformance]
[sig-network] DNS should provide DNS for services [Conformance]
[sig-network] DNS should provide DNS for the cluster [Conformance]
[sig-network] Services should be able to change the type from ExternalName to ClusterIP [Conformance]
[sig-network] Services should be able to change the type from ExternalName to NodePort [Conformance]
[sig-network] Services should be able to create a functioning NodePort service [Conformance]
[sig-windows] Hybrid cluster network for all supported CNIs should have stable networking for Linux and Windows pods
[sig-windows] Services should be able to create a functioning NodePort service for Windows
```

**Since when has it been failing**:
`14th Nov 13:11 PST`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-informing#gce-windows-master
https://testgrid.k8s.io/sig-release-1.17-informing#gce-windows-1.17

**Reason for failure**:
Check https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce/1195244959830118403

**Anything else we need to know**:
/cc @alenkacz @hasheddan @alejandrox1 
/cc @dims @listx @bclau 

/sig cli
/sig network
/sig api-machinery
/sig windows

/priority critical-urgent
/milestone v1.17

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind failing-test

/sig testing
/sig windows

/area conformance

**What this PR does / why we need it**:

A previous PR replaced the usage of Redis in the guestbook app test with Agnhost. The replacement went well for Linux setups and Containers, which is why the tests are green, but there is a network particularity on Windows setups which won't allow the test to pass.

The issue was observed with another test hitting the same issue: https://github.com/kubernetes/kubernetes/issues/83072

Here's exactly what happens during the test:

- ``frontend`` containers are created, having the ``/guestbook`` endpoint. Its main purpose is to forward the call to either ``agnhost-master`` (cmd=set), or ``agnhost-slave`` (cmd=get).
- ``agnhost-master`` container is created, having the ``/set`` endpoint, and the ``/register`` endpoint, through which the ``agnhost-slave`` containers would register to it. Its purpose is to propagate all data received through ``/set ``to its clients.
- ``agnhost-slave`` containers are created, having the ``/set`` and ``/get`` endpoints. They would register to ``agnhost-master``, and then receive any and all updates from it, which was then served through the ``/get`` endpoint.

For simplicity, all 3 types have the same agnhost subcommand (``agnhost guestbook``), being able to satisfy its given purpose. For this, HTTP servers were being used, including for the ``/register`` endpoints. ``agnhost-master`` would send its ``/set`` updates as ``/set`` HTTP requests. However, because of the issue listed above, ``agnhost-master`` did not receive the client's IP, but rather the container host's IP, resulting in the request being sent to the wrong destination. This can be seen in the test logs:

    Nov 16 00:36:24.148: INFO: Failed to get response from guestbook. err: <nil>, response: encountered error while propagating to slave '10.240.0.4': Get http://10.240.0.4:6379/set?key=messages&value=TestEntry: dial tcp 10.240.0.4:6379: connectex: No connection could be made because the target machine actively refused it.

Note that ``10.240.0.4`` is the host IP, and not the container IP:

    kubectl get nodes -o wide
    NAME                    STATUS                     ROLES    AGE   VERSION                                     INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION      CONTAINER-RUNTIME
    3384k8s000              Ready                      agent    40d   v1.17.0-alpha.0.1155+189ce7fb62c847-dirty   10.240.0.4     <none>        Windows Server 2019 Datacenter   10.0.17763.805      docker://18.9.7
    3384k8s001              Ready,SchedulingDisabled   agent    40d   v1.17.0-alpha.0.1155+189ce7fb62c847-dirty   10.240.0.35    <none>        Windows Server 2019 Datacenter   10.0.17763.737      docker://18.9.7
    3384k8s002              Ready,SchedulingDisabled   agent    40d   v1.17.0-alpha.2.1+1679bed80344a2            10.240.0.66    <none>        Windows Server 2019 Datacenter   10.0.17763.737      docker://18.9.7
    k8s-master-33844551-0   Ready                      master   40d   v1.17.0-alpha.2.1+1679bed80344a2            10.255.255.5   <none>        Ubuntu 16.04.6 LTS               4.15.0-1057-azure   docker://3.0.6

This PR updates the agnhost guestbook subcommand. Now, the agnhost-master node (has no ``slaveof`` argument) will start a TCP listener on the given backend-port, which replaces the ``/register``endpoint. The connections will be kept alive, and the ``/set`` updates will be sent through them.

**Which issue(s) this PR fixes**:

Fixes #80534
Fixes #85337

**Special notes for your reviewer**:

Test run on Windows node with ``claudiubelu/agnhost:2.8``, which contains this PR's updates: https://paste.ubuntu.com/p/tQM5H9nyGz/

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by annajung** [comment]
Hello @PatrickLang @adelina-t   👋 I'm one of the Bug Triage shadows for the 1.18 release. Since this PR is tagged for 1.18, I'd like to check its status. Is this PR intended for milestone 1.18?

Friendly reminder: Code freeze is scheduled for March 5th.

**Comment by claudiubelu** [comment]
> 
> 
> Hello @PatrickLang @adelina-t wave I'm one of the Bug Triage shadows for the 1.18 release. Since this PR is tagged for 1.18, I'd like to check its status. Is this PR intended for milestone 1.18?
> 
> Friendly reminder: Code freeze is scheduled for March 5th.

I've sent a simpler alternative since here: https://github.com/kubernetes/kubernetes/pull/85642 . If that merges, this won't be needed anymore.

**Comment by annajung** [comment]
@claudiubelu @PatrickLang @adelina-t Since there is an alternative PR open https://github.com/kubernetes/kubernetes/pull/85642, Can we remove this from bug triage tracking sheet for the release and clear the milestone?

**Comment by claudiubelu** [comment]
> 
> 
> @claudiubelu @PatrickLang @adelina-t Since there is an alternative PR open #85642, Can we remove this from bug triage tracking sheet for the release and clear the milestone?

sure.

/close

**Pull request closed without merging**
