### PR TITLE
Update the agnhost image

### PR DESCRIPTION
**Pull request by zylxjtu**
#### What this PR does / why we need it:
This is to add a delay-shutdown parameter to the agnhost/pause test image to control the timeout before exit, this will not change the existing agnhost/pause behavior, but add an enhancement to control the timeout value before exit, this will be useful to scenarios such as node shoutdown
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

None
```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by zylxjtu** [comment]
@claudiubelu, would you please help to take a look at this pull request as well?

**Comment by aojea** [comment]
is not possible to use the existing functionality with `netexec`?

**Comment by aojea** [comment]
we are already using this functionality on multiple e2e tests

https://github.com/kubernetes/kubernetes/blob/1dbf0830c59038822f37eaf5a1d4f7583f1a1081/test/e2e/network/pod_lifecycle.go#L54

https://github.com/kubernetes/kubernetes/blob/1dbf0830c59038822f37eaf5a1d4f7583f1a1081/test/e2e/network/service.go#L1914

https://github.com/kubernetes/kubernetes/blob/1dbf0830c59038822f37eaf5a1d4f7583f1a1081/test/e2e/network/loadbalancer.go#L1408

/hold

can you please expand on why we need to add this new one?

**Comment by zylxjtu** [comment]
> we are already using this functionality on multiple e2e tests
> 
> https://github.com/kubernetes/kubernetes/blob/1dbf0830c59038822f37eaf5a1d4f7583f1a1081/test/e2e/network/pod_lifecycle.go#L54
> 
> https://github.com/kubernetes/kubernetes/blob/1dbf0830c59038822f37eaf5a1d4f7583f1a1081/test/e2e/network/service.go#L1914
> 
> https://github.com/kubernetes/kubernetes/blob/1dbf0830c59038822f37eaf5a1d4f7583f1a1081/test/e2e/network/loadbalancer.go#L1408
> 
> /hold
> 
> can you please expand on why we need to add this new one?

yes, I noticed this delay-shutdown parameter was in the "netexec" command. But I think it has advantage to add this parameter to the "pause" command, as some of the test scenarios are not "net" related but would also like to have a delay-shutdown, such as the node shutdown case. But I agree that we can use the "netexec" to achieve similar goa.

**Comment by aojea** [comment]
> s some of the test scenarios are not "net" related but w

the name of the binary executed is orthogonal to the test scenario, is the same functionality , so we are not going to replicate the functionality

**Comment by zylxjtu** [comment]
> > s some of the test scenarios are not "net" related but w
> 
> the name of the binary executed is orthogonal to the test scenario, is the same functionality , so we are not going to replicate the functionality

Thanks, good to know. I will abandon this PR then

**Comment by aojea** [comment]
> > > s some of the test scenarios are not "net" related but w
> > 
> > 
> > the name of the binary executed is orthogonal to the test scenario, is the same functionality , so we are not going to replicate the functionality
> 
> Thanks, good to know. I will abandon this PR then

thanks for your comprehension, feel free to suggest new features, but it is better to not duplicate functionality

/close

**Pull request closed without merging**
