### PR TITLE
Automated cherry pick of #90296: go-to-protobuf: fix rewrite of embedded struct fields

### PR DESCRIPTION
**Pull request by mandelsoft**
Cherry pick of #90296 on release-1.17.

#90296: go-to-protobuf: fix rewrite of embedded struct fields

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

Release note:
```release-note
NONE
```

### CODE REVIEW

**Comment by tpepper** [comment]
/kind bug
/priority important-soon
from parent PR

/ok-to-test

**Comment by lavalamp** [comment]
same q as other cherry-pick, do we really need to backport this?

**Comment by mandelsoft** [comment]
@lavalamp see my comment in the other PR (#91825)

**Comment by lavalamp** [comment]
ACK, ok, that seems like a good reason to go back this far.

/ok-to-test
/approve

/hold for getting the binary file which I missed in the original PR out, sorry

**Comment by mandelsoft** [comment]
Binary has been removed, sorry for that.

**Comment by timuthy** [comment]
@lavalamp may I ask you to take another look? Would really appreciate if you approve this PR since we depend on it.

**Pull request merged**
