### PR TITLE
kubectl support certificate and key data

### LINKED ISSUE #63435: `kubectl config set-credentials` do not support using certificate data and key data
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind feature

**What happened**:

```
root@gyliu-ubuntu-1:~/multicluster# kubectl config set-credentials --help
Sets a user entry in kubeconfig

Specifying a name that already exists will merge new fields on top of existing values.

  Client-certificate flags:
  --client-certificate=certfile --client-key=keyfile

  Bearer token flags:
    --token=bearer_token

  Basic auth flags:
    --username=basic_user --password=basic_password

Bearer token and basic auth are mutually exclusive.

Examples:
  # Set only the "client-key" field on the "cluster-admin"
  # entry, without touching other values:
  kubectl config set-credentials cluster-admin --client-key=~/.kube/admin.key

  # Set basic auth for the "cluster-admin" entry
  kubectl config set-credentials cluster-admin --username=admin --password=uXFGweU9l35qcif

  # Embed client certificate data in the "cluster-admin" entry
  kubectl config set-credentials cluster-admin --client-certificate=~/.kube/admin.crt --embed-certs=true

  # Enable the Google Compute Platform auth provider for the "cluster-admin" entry
  kubectl config set-credentials cluster-admin --auth-provider=gcp

  # Enable the OpenID Connect auth provider for the "cluster-admin" entry with additional args
  kubectl config set-credentials cluster-admin --auth-provider=oidc --auth-provider-arg=client-id=foo
--auth-provider-arg=client-secret=bar

  # Remove the "client-secret" config value for the OpenID Connect auth provider for the "cluster-admin" entry
  kubectl config set-credentials cluster-admin --auth-provider=oidc --auth-provider-arg=client-secret-

Options:
      --auth-provider='': Auth provider for the user entry in kubeconfig
      --auth-provider-arg=[]: 'key=value' arguments for the auth provider
      --client-certificate='': Path to client-certificate file for the user entry in kubeconfig
      --client-key='': Path to client-key file for the user entry in kubeconfig
      --embed-certs=false: Embed client cert/key for the user entry in kubeconfig
      --password='': password for the user entry in kubeconfig
      --token='': token for the user entry in kubeconfig
      --username='': username for the user entry in kubeconfig

Usage:
  kubectl config set-credentials NAME [--client-certificate=path/to/certfile] [--client-key=path/to/keyfile]
[--token=bearer_token] [--username=basic_user] [--password=basic_password] [--auth-provider=provider_name]
[--auth-provider-arg=key=value] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).
```

From above, we can see I have to use file name for certificate and key.
```
--client-certificate='': Path to client-certificate file for the user entry in kubeconfig
--client-key='': Path to client-key file for the user entry in kubeconfig
```

If I want to use content string of the certificate and key, I have to update `$HOME/.kube/config` manually by changing `client-certificate` to `client-certificate-data`, and change `client-key` to `client-key-data`.

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://9.111.255.21:8001
  name: myistio.icp
contexts:
- context:
    cluster: myistio.icp
    namespace: default
    user: admin
  name: myistio.icp-context
current-context: myistio.icp-context
kind: Config
preferences: {}
users:
- name: admin
  user:
    as-user-extra: {}
    client-certificate-data: <xxxx>
    client-key-data: <xxxx>
```

/sig security

### PR DESCRIPTION
**Pull request by ceshihao**
**What this PR does / why we need it**:
`kubectl config set-credentials` supports using certificate and key data instead of only file

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #63435 

**Special notes for your reviewer**:

**Release note**:

```release-note
`kubectl config set-credentials` supports using certificate and key data instead of only file.
```

### CODE REVIEW

**Comment by juanvallejo** [comment]
/ok-to-test

/hold
on https://github.com/kubernetes/kubernetes/pull/63373 which changes where we bind config flags

**Comment by ceshihao** [comment]
@juanvallejo 
I find #63373 has been merged and there is no conflict.
Still need to hold this MR?

**Comment by juanvallejo** [comment]
/hold cancel

@ceshihao could you please update this PR to add the new flag in [config_flags.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/config_flags.go#L58)?
You'll need to add a field for it in the struct, and bind the actual flags in the [AddFlags](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/config_flags.go#L201) method

**Comment by ceshihao** [comment]
Thanks, I will handle that.

**Pull request closed without merging**
