### PR TITLE
[federation][e2e] Fix cleanupServiceShardLoadBalancer

### LINKED ISSUE #46976: federation: errors in cleaning the load balancers in federation e2e tests.
In federation tests, if we observe the build logs. we see cleaning up LoadBalancer from cloud provider seems not working.
```
I0605 06:12:31.969] Jun  5 05:57:11.859: INFO: Failed to delete cloud provider resources for service "federated-service" in namespace "e2e-tests-federated-service-86x1k", in cluster "federation-e2e-gce-us-central1-a": error getting cluster ID a7b70c85e49ee11e7aa3042010a80000: GCECloud.ClusterID is not ready. Call Initialize() before using.
I0605 06:12:31.969] Jun  5 05:57:13.859: INFO: Failed to delete cloud provider resources for service "federated-service" in namespace "e2e-tests-federated-service-86x1k", in cluster "federation-e2e-gce-us-central1-a": error getting cluster ID a7b70c85e49ee11e7aa3042010a80000: GCECloud.ClusterID is not ready. Call Initialize() before using.
```
It has 2 effects:
- delays the tests by waiting to delete but always returns error. so we waste like 5 minutes.
- maybe we are leaking the LoadBalancer in the project.

@madhusudancs @kubernetes/sig-federation-bugs

### PR DESCRIPTION
**Pull request by shashidharatd**
**What this PR does / why we need it**:
Fixes the issue mentioned in #46976

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #46976

**Special notes for your reviewer**:

```release-note
NONE
```

### CODE REVIEW

**Comment by shashidharatd** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by shashidharatd** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by shashidharatd** [comment]
The federation pre-submit tests pass too https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46979/pull-kubernetes-federation-e2e-gce/9252/

Also the execution time is much faster now (~25 mins) compared to ~40 mins without this fix.

**Comment by shashidharatd** [comment]
@madhusudancs, request you to apply 1.7 milestone. if you are OK with the fix.

**Comment by madhusudancs** [comment]
Very cool! Thanks.

/lgtm

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/e2e_federation/util.go, line 208 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/46979#-Klz3k2-FuLMK5xx-Ige:-Klz3k2-FuLMK5xx-Igf:btx4nbg) ([raw file](https://github.com/kubernetes/kubernetes/blob/bfc0e0c8c65c2e591cf54acbb999c46080940474/test/e2e_federation/util.go#L208)):*
> ```Go
> 		}
> 
> 		if cSvc.Spec.Type == v1.ServiceTypeLoadBalancer && len(cSvc.Status.LoadBalancer.Ingress) != 0 {
> ```

`> 0` to be clear.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/46979#-:-Klz4fPuKb897BY41VoD:b-q0f11x)*

**Comment by madhusudancs** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by madhusudancs** [comment]
@kubernetes/kubernetes-release-managers this is a test-only change.

**Comment by shashidharatd** [comment]
I did handle the comments from @nicksardo and @MrHohn from the issue  #46976, Could you PTAL.

**Review by MrHohn — APPROVED** [review]
LGTM, thanks for the fix!

**Pull request merged**
