### PR TITLE
kubeadm: update coredns to 1.8.4

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind feature
/kind cleanup

#### What this PR does / why we need it:

- [x] wait for promoting coredns image 1.8.4: https://github.com/kubernetes/k8s.io/pull/2118
- [x] wait for  corefile-migration release for 1.8.4.  As corefile-migration  is not released, I would update it later after https://github.com/coredns/corefile-migration/pull/60 is merged. #102830 upgraded it

#### Which issue(s) this PR fixes:
xref #99751

#### Does this PR introduce a user-facing change?
```release-note
kubeadm: update CoreDNS to 1.8.4. Grant CoreDNS permissions to "list" and "watch" EndpointSlice objects to accommodate dual-stack support.
```

### CODE REVIEW

**Review by rajansandeep — COMMENTED** [review]
You would want to add the changes in https://github.com/kubernetes/kubernetes/pull/101955 in this PR to add permissions for endpointslices

**Comment by pacoxu** [comment]
> You would want to add the changes in #101955 in this PR to add permissions for endpointslices

@rajansandeep  I cherry-picked it to this PR.

**Comment by neolit123** [comment]
the coredns migration library was just updated in this PR:
https://github.com/kubernetes/kubernetes/pull/102830

**Comment by pacoxu** [comment]
/remove-area dependency
@neolit123 since the image is promoted and the corefile-migration is upgraded, this PR is ready to review.

**Comment by aojea** [comment]
great, we have full dual stack support with this change

**Review by BenTheElder — APPROVED** [review]
/hold

IMO this does not fix https://github.com/kubernetes/kubernetes/issues/99751, commented there.

changes here LGTM though
/approve

**Comment by pacoxu** [comment]
The description is updated.

@BenTheElder I made a mistake here. I thought that the dns-autoscaler only supports old kube-dns, however, it supports both kube-dns and coredns. 

I will look into  #100795 later.

**Comment by BenTheElder** [comment]
no worries, thanks for updating the PR description, I mostly wanted to avoid automatic issue closure in this case 😅 
/hold cancel

**Review by neolit123 — COMMENTED** [review]
/approve
/hold
/priority important-soon

LGTM, please update the release note to something like:
> kubeadm: update CoreDNS to 1.8.4. Grant CoreDNS permissions to "list" and "watch" EndpointSlice objects to accommodate dual-stack support.

**Comment by pacoxu** [comment]
Updated

**Comment by chrisohaver** [comment]
Last week a regression was [reported](https://github.com/coredns/coredns/issues/4834) for 1.8.4 for the _rewrite_ plugin. There is a workaround. FYI AFAIK, AKS has [decided to defer rolling out 1.8.4](https://github.com/Azure/AKS/issues/2521#issuecomment-911901518), skipping over the version, since a fix will be in 1.8.5 (already merged).
Describing the regression as succinctly as I can:

> If using the _rewrite_ plugin, a rewrite rule that does not also rewrite the response (using the `answer` option) will cause clients to reject any response rewritten by the rule (due to question section mismatch). A work around is to append `answer auto` to affected rules. All `exact` name rewrites are not affected since they automatically perform a response rewrite.

FWIW, this has always been the case for _some_ clients (some clients are extra picky about question mismatch), but the regression caused it to affect _most_ clients (if not all).  My attempt to explain in more detail [here](https://github.com/coredns/coredns/issues/4834#issuecomment-908544954).

Also, regarding the workaround, `answer auto` is only valid in 1.8.4, so a user cannot adjust their corefile before upgrading to avoid potential downtime.  If that is desired, any affected rule should be expressed as a `regex` rule with a response rewrite, which would be valid in 1.84 and prior versions.

**Comment by pacoxu** [comment]
@chrisohaver Kubeadm default coredns corefile doesn’t include ‘rewrite’ plug-in.

However, it Will affect  user using rewrite plugin.

**Comment by chrisohaver** [comment]
> @chrisohaver Kubeadm default coredns corefile doesn’t include ‘rewrite’ plug-in.
> 
> However, it Will affect user using rewrite plugin.

Yes. That's correct. Hard to know how many people use it, and how many people who use it are not already doing a response rewrite (as would be prudent).

**Pull request merged**
