### PR TITLE
Fix error case for ExtractFieldPathAsString

### PR DESCRIPTION
**Pull request by hex108**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Return err instead of nil if failing to convert `obj` to `metav1.Object` ExtractFieldPathAsString

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yue9944882** [comment]
/sig api-machinery

what's the point of changing the behavior? doesn't sound like a bug to me

**Comment by hex108** [comment]
> what's the point of changing the behavior? doesn't sound like a bug to me

I thought it needs returns error if something fails. It is OK if it is en expected behavior.

**Comment by jpbetz** [comment]
> what's the point of changing the behavior? doesn't sound like a bug to me

If a caller were to do:

```go
val, err := fieldpath.ExtractFieldPathAsString(obj, path)
if err != nil {
  return err
}
// do something with val
```

They be guaranteed that val is actually string value of the field at the provided path, right?

**Comment by hex108** [comment]
/assign @smarterclayton 

Kindly ping @smarterclayton for another review

**Pull request merged**
