### PR TITLE
Update golang/x/net dep to golang1.6 release, in prep for http2 changes

### PR DESCRIPTION
**Pull request by timothysc**
We were running an old library versions, this is a pre-cursor to other updates.

### CODE REVIEW

**Comment by xiang90** [comment]
LGTM

**Comment by timothysc** [comment]
re-opening to re-trigger travis which appears to have failed.

**Comment by timothysc** [comment]
Addresses: #21081

**Comment by timothysc** [comment]
Closing this PR b/c of the Godep vedor shuffle and moved it into: https://github.com/kubernetes/kubernetes/pull/25280

**Pull request closed without merging**
