### PR TITLE
Add sig-cli as approver for testdata

### PR DESCRIPTION
**Pull request by apelisse**
Since sig-cli members change some tests and need to change some data,
having approval in that directory should be useful.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/sig cli
/cc @soltysh @seans3

### CODE REVIEW

**Comment by cblecker** [comment]
@apelisse For other sig-cli stuff, the OWNERS look like:
https://github.com/kubernetes/kubernetes/blob/3c43f089b24f69bc2347d46a8958d7b2f9daa2c2/cmd/kubectl/OWNERS#L1-L7

Should we do something similar? In particular the auto-labels, and using `sig-cli-maintainers` as the approve alias.

**Comment by cblecker** [comment]
also, is it *all* sig-cli in there? because if this goes through, you'll get suggested as approvers for anything that touches it.

**Comment by apelisse** [comment]
> For other sig-cli stuff, the OWNERS look like:

Yeah, I clearly made a mistake, just fixed it!

> also, is it all sig-cli in there? because if this goes through, you'll get suggested as approvers for anything that touches it.

I don't think that is true. And I guess I'll be eager to fix it if that's true :D

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
