### PR TITLE
Automated cherry pick of #47980

### PR DESCRIPTION
**Pull request by perotinus**
Cherry pick of #47980 on release-1.7.

#47980: Account for caching in kubectl

### CODE REVIEW

**Comment by nikhiljindal** [comment]
/approve
@dchen1107 Can you add the `cherrypick-approved` label?

**Comment by dchen1107** [comment]
All tests passed, and the master branch are running happily with this pr:
https://k8s-testgrid.appspot.com/release-master-blocking#gce-federation 

but the release branch is constantly failed without this pr, and no real tests are running:
https://k8s-testgrid.appspot.com/release-1.7-blocking#gce-federation-release-1-7

**Pull request merged**
