### PR TITLE
Automated cherry pick of #61396: Bump Heapster to v1.5.2

### PR DESCRIPTION
**Pull request by kawych**
Cherry pick of #61396 on release-1.10.

#61396: Bump Heapster to v1.5.2

**Release note**:
```release-note
Bump Heapster to v1.5.2
```

### CODE REVIEW

**Comment by x13n** [comment]
Please add release note with changes in new version.

**Comment by x13n** [comment]
(In the original PR, it just says it bumps the version. What changed in that version?)

**Comment by kawych** [comment]
Bug fixes, mostly for Stackdriver sink:
- Switch Stackdriver sink to grpc (performance improvement): https://github.com/kubernetes/heapster/pull/1906
- Export correct cluster location for new resource model: https://github.com/kubernetes/heapster/pull/1943
- Remove node_name label: https://github.com/kubernetes/heapster/pull/1952
- Use float64 instead of float32 for metrics: https://github.com/kubernetes/heapster/pull/1975
- Export cpu metric in correct unit: https://github.com/kubernetes/heapster/pull/1983

**Comment by x13n** [comment]
Thanks!
/lgtm

**Comment by kawych** [comment]
/uncc @DirectXMan12 
@MaciekPytel please approve the cherrypick.

**Comment by kawych** [comment]
/uncc @MaciekPytel 
/cc @jdumars 
/cc @calebamiles 
Please approve the cherry-pick, as @MaciekPytel doesn't do it before 1.10.0

**Comment by jdumars** [comment]
@calebamiles PTAL for approval
@kawych was there a reason this is coming in so late in the release process?  Has this change been fully tested?

**Comment by kawych** [comment]
As discussed with @calebamiles offline, it will be submitted after 1.10.0 release, as the bugs fixed in Heapster 1.5.2 aren't that urgent and there is not much time for e2e tests to show any potential bugs introduced here.

**Comment by MaciekPytel** [comment]
@kawych pull-kubernetes-e2e-gce has failed a few times in a row now. Can you take a look? It's probably still a flake, but I'd rather be sure. I'll approve once the test passes.

**Comment by kawych** [comment]
@MaciekPytel It doesn't seem related at all, it fails in some kubectl test, I don't see a connection to Heapster (especially the v1.5.2 changes).
/retest

**Pull request merged**
