### PR TITLE
Remove azure disable-tcp-reset annotations

### PR DESCRIPTION
**Pull request by CaoDonghui123**
#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it:

> 	// TODO(feiskyer): disable-tcp-reset annotations has been depracated since v1.18, it would removed on v1.20.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by CaoDonghui123** [comment]
> @CaoDonghui123 could you file a PR in https://github.com/kubernetes-sigs/cloud-provider-azure? The in-tree provider is deprecating and only allows bug fixes.

I will do this

**Review by feiskyer — APPROVED** [review]
/lgtm

**Pull request merged**
