### PR TITLE
e2e: avoid mandatory command line flags

### LINKED ISSUE #75590: e2e and mandatory command line flags
**What happened**:

https://github.com/kubernetes/kubernetes/pull/69105 moved flag definitions from a function in the E2E test framework (`RegisterCommonFlags`) into the init section of some test packages. That's okay for the Kubernetes E2E test suite where those flags traditionally have been part of the command line.

But now @deads2k pointed out (https://github.com/kubernetes/kubernetes/pull/69105#pullrequestreview-216944509) that in his usage of the tests, he was only using Viper for setting the test configuration and doesn't want the configuration options to show up in the command line.

**What you expected to happen**:

Adding to the global command line must be entirely controlled by the owner of the actual binary. Packages should never directly define flags.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13 and (currently) the 1.14 release candidate

### PR DESCRIPTION
**Pull request by pohly**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Tests should never directly add to the global command line, because
some users of the tests might not want them there. For example,
options might only get set directly from a config file.

To achieve that, e2e/framework/config, e2e/framework/viperconfig, and
e2e/framework/test_context.go avoid using the global flag set and
instead expect to be told by the caller which flag set to use.

The exception is framework.HandleFlags, which as before directly
implements global command line handling.

**Which issue(s) this PR fixes**:

Fixes #75590

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
E2E tests no longer add command line flags directly to the command line, test suites that want that need to be updated if they don't use HandleFlags
loading a -viper-config=e2e.yaml with suffix (introduced in 1.13) works again and now has a regression test
```

/sig testing
/cc @deads2k

### CODE REVIEW

**Comment by pohly** [comment]
@deads2k is this critical for you? Should we try to get this into 1.14.0?

**Comment by deads2k** [comment]
> @deads2k is this critical for you? Should we try to get this into 1.14.0?

It's important, but since it was in 1.13 too, I don't think a backport is warranted.  I'm more interested in establishing a pattern that allows for clean import and composition.

**Comment by timothysc** [comment]
So in testing commons we ideally want to get to a versioned component config style config and leverage that work and deprecate what is currently in the test. 

/hold
/cc @mtaufen @luxas

**Comment by timothysc** [comment]
@pohly - what would you like todo here?

**Comment by pohly** [comment]
> @pohly - what would you like todo here?

I don't know what the status is regarding the generic config handling in Kubernetes. If this isn't usable for E2E testing or there is no-one available to make the necessary changes (I myself don't have the time, sorry), then I would prefer to merge this PR because it addresses the valid issue that @deads2k pointed out. I just haven't rebased because the PR was put on hold and wouldn't get merged.

**Comment by timothysc** [comment]
I'm ok with merging the PR for the time being.

**Comment by pohly** [comment]
@timothysc: I finished the rebasing.

The new viper config test revealed that the corresponding feature (loading a viper config file with explicit file suffix) had broken since introducing it in 1.13. I added the necessary fix in a separate commit, just in case that this is something we want to backport (probably not, as usage of the broken feature should be extremely small, if anyone does it at all).

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve 
/hold cancel

**Pull request merged**
