### PR TITLE
test images: Small changes to trigger image postsubmit jobs

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind flake
/sig testing

/priority important-soon

**What this PR does / why we need it**:

This PR will trigger the postsubmit jobs for these images. These were omitted previously for some more investigations, but they should be passing, as their issue should have been addressed previously.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by pacoxu — APPROVED** [review]

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by spiffxp** [comment]
Part of https://github.com/kubernetes/k8s.io/issues/1522, https://github.com/kubernetes/kubernetes/issues/96770

**Pull request merged**
