### PR TITLE
Implement rollout restart for statefulset and daemonset

### LINKED ISSUE #13488: Rolling restart of pods
`kubectl rolling-update` is useful for incrementally deploying a new replication controller. But if you have an existing replication controller and want to do a rolling restart of all the pods that it manages, you are forced to do a no-op update to an RC with a new name and the same spec. It would be useful to be able to do a rolling restart without needing to change the RC or to give the RC spec, so anyone with access to kubectl could easily initiate a restart without worrying about having the spec locally, making sure it's the same/up to date, etc. This could work in a few different ways:
1. A new command, `kubectl rolling-restart` that takes an RC name and incrementally deletes all the pods controlled by the RC and allows the RC to recreate them.
2. Same as 1, but instead of deleting each pod, the command iterates through the pods and issues some kind of "restart" command to each pod incrementally (does this exist? is this a pattern we prefer?). The advantage of this one is that the pods wouldn't get unnecessarily rebalanced to other machines.
3. `kubectl rolling-update` with a flag that lets you specify an old RC only, and it follows the logic of either 1 or 2.
4. `kubectl rolling-update` with a flag that lets you specify an old RC only, and it auto-generates a new RC based on the old one and proceeds with normal rolling update logic.

All of the above options would need the MaxSurge and MaxUnavailable options recently introduced (see #11942) along with readiness checks along the way to make sure that the restarting is done without taking down all the pods.

@nikhiljindal @kubernetes/kubectl

### PR DESCRIPTION
**Pull request by apelisse**
Specifically, DaemonSet and Statefulset

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #13488

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`kubectl rollout restart` now works for daemonsets and statefulsets.
```

### CODE REVIEW

**Comment by apelisse** [comment]
OK I've added the test, should be ready for review @janetkuo

**Review by janetkuo — APPROVED** [review]

**Comment by janetkuo** [comment]
/lgtm

Thank you!!!

**Pull request merged**
