### PR TITLE
kubeadm: return stored FakedServerVersion when dry-running

### LINKED ISSUE #2796: fix failing dryrun e2e job
some of our recent changes broke the dryrun e2e

https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-dryrun-latest

tip: to see what commits was it one can click a red box and drag to a green box. i am currently on mobile and can't do that.

we should try to fix this before xmas and not having any failing tests during the holidays...preferably since folks are not around.

@pacoxu @SataQiu @chendave

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

If we are dry-running, do not attempt to fetch the /version resource and just return the stored FakeServerVersion, which is done when constructing the dry-run client in upgrade/common.go#getClient().

The problem here is that during upgrade
dry-run client reactors are backed by a dynamic client via NewClientBackedDryRunGetterFromKubeconfig() and for GetActions there seems to be no analog to
Discovery().Serverversion() resource for a dynamic client(?).

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/2796

#### Special notes for your reviewer:

There might be a better fix for this, if someone is willing to investigate / provide ideas.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
I haven't got the time to check the details.  Only in case you need a lgtm to let this in and check the job status, so pls unhold if this is urgent.

/lgtm
/hold

**Comment by neolit123** [comment]
i tested this locally. let's merge this PR to unblock the CI. we can think about a different solution later, in case we get feedback from the folks on the issue thread.

/hold cacel

**Comment by neolit123** [comment]
fixed typo in commit message / code comment (double "and")

**Review by pacoxu — APPROVED** [review]

**Pull request merged**
