### PR TITLE
Updating go-restful dependency to fix thirdparty issues

### LINKED ISSUE #23831: Installing multiple third party resources on same resource path prefix has issues
I am trying to install the following thirdparty resources:

```yaml
metadata:
  name: compute-node.tess.io
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "A compute node object is used by the mastercontroller to track computes in cloud"
versions:
 - name: v1
```

And 

```yaml
metadata:
  name: node-pool.tess.io
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: "A node pool object to nodes is analogous to what a replicationcontroller is to pods"
versions:
 - name: v1
```

The first one gets successfully registered when I try to create it. But the second on never gets registered and kubectl does not throw an error out either. I digged a little deep into the kube-apiserver logs and I see the following error:

`Recovered from panic: "http: multiple registrations for /apis/tess.io/v1" (http: multiple registrations for /apis/tess.io/v1)`

When I digged deep into the thirdparty controller and master.go, here: https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master.go#L611, I see that we have not covered the case where there can be 2 API objects defined on the same resource path prefix, like `/apis/tess.io/v1/nodepools` and `/apis/tess.io/v1/computenodes`

Is there something I am missing, or is this a genuine issue you think ?

### PR DESCRIPTION
**Pull request by uruddarraju**
The issues faced with third party and go-restful were:
1. https://github.com/kubernetes/kubernetes/issues/23831
2. https://github.com/emicklei/go-restful/issues/276
3. https://github.com/emicklei/go-restful/issues/274

This is also a prerequisite for other third party fixes that would be pushed to fix https://github.com/kubernetes/kubernetes/issues/23831

### CODE REVIEW

**Comment by uruddarraju** [comment]
@lavalamp Please review. I would follow this up with the actual fix.

**Comment by eparis** [comment]
what version of Godep did you use to make this update? Did you include -t? (you need to use version v53 and you should not use -t)

**Comment by lavalamp** [comment]
LGTM thanks!

**Comment by uruddarraju** [comment]
@eparis @lavalamp Any idea why this is still hanging in the queue ? Is there something that I need to do ?

**Comment by eparis** [comment]
Only way to get the queue to go any faster is to debug the failures shown http://submit-queue.k8s.io/#/e2e (which have nothing to do with this PR)    At the current rate I'd say you'll be lucky to merge by monday or so...  There is nothing you can do on this PR.  :-(  I know. stinks.

**Comment by uruddarraju** [comment]
@eparis I was unaware of the e2e failues and was wondering if there is something I can do about "this" PR. Thanks anyways. This can wait. I will check back later next week.

**Comment by lavalamp** [comment]
The queue is a bit backed up at the moment. http://submit-queue.k8s.io/#/queue

I'm build cop today and tomorrow so I may go through and manually merge some stuff if it doesn't look like it's going to clear naturally.

**Comment by lavalamp** [comment]
Manual build cop merge.

**Comment by maximmartynov** [comment]
Not sure if you are aware, but this merge does not seem to contain a fix for emicklei/go-restful#274, because the fix https://github.com/emicklei/go-restful/commit/809fb70444f258736128d19badc901da3cd3256b was not merged into emicklei/go-restful master.

**Comment by brendandburns** [comment]
See: https://github.com/kubernetes/kubernetes/issues/25084

for the remaining issue.  Will work with @emicklei to get this fixed.

**Pull request merged**
