### PR TITLE
CRD validation refactor

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
* Moves the validation of the API approval annotation into the CRD validation package
* Combines some of the validation options passed around to various functions into an options struct
* Prep work for additional validation done in the v1 promotion PR (https://github.com/kubernetes/kubernetes/pull/79604)

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/sig api-machinery
/cc @smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
Just the one comment

**Comment by liggitt** [comment]
mm... I actually want to unexport everything except the main ValidateCRD and ValidateCRDUpdate methods. will either do that in a followup or make the opts public

**Comment by liggitt** [comment]
went ahead and unexported the ones using the options struct

**Pull request merged**
