### PR TITLE
Add comments for ipset entries in kube-proxy - fix

### PR DESCRIPTION
**Pull request by islinwb**
**What this PR does / why we need it**:
Changes in https://github.com/kubernetes/kubernetes/pull/63585 failed some tests. This PR modifies it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wgliang** [comment]
@islinwb  
If it is modified like this, isn't all the double quotes needed? I don't think this is necessary.

**Comment by m1093782566** [comment]
@islinwb Please tell why you do this.

**Comment by islinwb** [comment]
@WanLinghao You're right. Thanks for pointing out that. I'll update it.
@m1093782566 Sorry I didn't made it clear. Changes in #63585 are not totally correct and this PR intends to fix it.

**Comment by m1093782566** [comment]
Want to see if this PR will fix the flaky test.

/lgtm

/approve

**Pull request merged**
