### PR TITLE
Make check err testable

### PR DESCRIPTION
**Pull request by andronat**
Continuing on #7027 and this [comment](https://github.com/GoogleCloudPlatform/kubernetes/issues/7027#issuecomment-107241037). This is a PR on how we can test `CheckErr`. Any comments are welcomed.

/cc @smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
ok to test

**Comment by smarterclayton** [comment]
LGTM pending tests passing

**Comment by andronat** [comment]
Sorry I can't see shippable. Do you know why this fails? It passes all test in my env

**Comment by krousey** [comment]
@andronat Since you only need to access `CheckErr` in the test, would you mind making it private to the package (lower case like `checkErr`)? Then you could rename `CheckErrAndFatal` to `CheckErr` and not have to change any of the callers.

**Comment by andronat** [comment]
Something like this?

**Comment by krousey** [comment]
Yes. Thank you. LGTM

**Pull request merged**
