### PR TITLE
v1beta1 Network API & client

### PR DESCRIPTION
**Pull request by kshafiee**
**What this PR does / why we need it**:

‘Network’ resource spec. is as per discussions in SIG Network [Design document](https://docs.google.com/document/d/1TW3P4c8auWwYy-w_5afIPDcGNLK3LZf0m14943eVfVg/edit?usp=sharing) by Joje. Many components in the context of “multi-networking” were discussed in Joje's document. However, this PR purely focuses on ‘Network’ resource.
 
Adding Network API is considered to serve 2 purposes:
1. ‘Network’ to be a first-class resource. Users create ‘Network’ resource like any other resource. Network controller does the list & watch & sync on Network resources. The community did NOT reach a consensus on this AT THIS POINT!
2. Users create ‘Network’ resource for the purpose of creating a .conf file under /etcd/cni/net.d/ for 3rd party CNI plugins to use. In this case, there is no network controller. Kubelet creates a .conf file per Network

This PR adds Network API for purpose 2. Network API introduced here can later be used to fulfill purpose 1 when there is the need/consensus. Please see [workflow for purpose 2](https://docs.google.com/document/d/1NfGRM28zunvkkqpffw8kDpb0nRPxYyuJzHq3tKyoNQY/edit?usp=sharing) for more information.

NOTE: another PR will be created for changes needed in kubelet to create .conf files

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
@kshafiee can you split auto-generated files into a separate commit which should make it easier for review.

**Comment by kshafiee** [comment]
@kevin-wangzefeng totally agree that makes it easier to review. Previously when I did that for federated secret API, I was asked to squash all the commits into a single commit

**Comment by kevin-wangzefeng** [comment]
@kshafiee That finial squashing usually happen after the review-update iteration finished, to cleanup meaningless commits, but at the beginning, I don't think you need to submit all changes in a single large commit :)

**Comment by caseydavenport** [comment]
@kshafiee has this API gone through design review yet? Specifically I'm looking for a proposal [merged into the community proposals directory](https://github.com/kubernetes/community/tree/master/contributors/design-proposals).

I don't think we can entertain this PR until that's happened.  

Currently, "multiple network" support is being implemented through API extensions (TPR/CRD + annotations, CNI plugins) rather than natively within Kubernetes.  If you haven't seen it yet, you might be interested in [this thread](https://groups.google.com/forum/#!topic/kubernetes-sig-network/54QcDiF64TY)

**Comment by kshafiee** [comment]
@caseydavenport thanks for the info. on the process!
My understanding was that Network API spec had gone through multiple rounds of review on Joji's document and was finalized,

As I mentioned in the description of the PR, Network API is just one of the many pieces of "multi network". Of course Pod annotations is needed for Network to be picked up for the Pod.

My understanding is that  TPR will be deprecated in 1.7 & that the thread you mentioned is re. implementation of a special use-case, Session Border Controller (SBC) use-case.

**Comment by caseydavenport** [comment]
> My understanding was that Network API spec had gone through multiple rounds of review on Joji's document and was finalized

@kshafiee I think there are still some outstanding high-level questions re: multiple networks, including whether or not it belongs in k8s core.

My understanding of the current plan of record as discussed by the SIG is that we don't intend this to be a part of k8s core for now.  The correct process either way is to go through alpha as a TPR (soon to be CRD) and annotation based approach first before we write any new API code.

I appreciate the contribution, but given the above I think we should probably close this PR for now and continue any discussion on the sig-network mailing list, but let's wait for @dcbw or @thockin to chime in.

**Comment by kshafiee** [comment]
@caseydavenport thx for the feedback! Any ideas if there's any controller in k8s for CRD objects to do list/watch? For example to ensure a new Network CRD object is not allowed to be created if a Network CRD object with an overlapping subnet range already exists?

**Comment by caseydavenport** [comment]
@kshafiee I don't think CRD provides anything like that out of the box.  It sounds like a case for an admission control plugin to me (currently requires modification of apiserver code, but eventually to be pluggable).

- [Admission control plugin proposal](https://github.com/kubernetes/community/pull/132/files)
- [Corresponding PR](https://github.com/kubernetes/kubernetes/pull/46316)

Alternatively, you could write a controller that updates the status portion to indicate that the network isn't available due to a conflict.

**Comment by thockin** [comment]
I really appreciate the enthusiasm on this one, but I don't think we're ready for PRs yet - we haven't' agreed that we WANT this feature, much less how it looks.  For the sake of my TODO list, I am going to close this PR, but if/when we're ready it can be reopened.

**Pull request closed without merging**
