### PR TITLE
Check some errors that we were letting slip silently by.

### PR DESCRIPTION
**Pull request by brendandburns**
@ihmccreery @ixdy @quinton-hoole 

@kubernetes/goog-testing

### CODE REVIEW

**Comment by brendandburns** [comment]
We should cherry-pick this into 1.1 also.

**Comment by ihmccreery** [comment]
LGTM.  Thanks @brendandburns.

**Comment by brendandburns** [comment]
@k8s-bot test this please
@k8s-bot unit test this please

**Comment by brendandburns** [comment]
Manually merging for more info on e2e failures.

**Pull request merged**
