### PR TITLE
eviction: use previous statsFunc

### PR DESCRIPTION
**Pull request by fuweid**
Signed-off-by: Wei Fu <fuweid89@gmail.com>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

No need to use summary to create statsFunc for localStorageEviction.
Just use vals from makeSignalObservations.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dashpole** [comment]
/ok-to-test

Are you sure this fixes a test flake?

/assign

**Comment by fuweid** [comment]
@dashpole thanks for review! sorry about wrong kind label for this pr. I updated it to cleanup.

And the failed case seems not related to this issue. 

/retest

**Pull request merged**
