### PR TITLE
update the version of etcd

### PR DESCRIPTION
**Pull request by menghao11**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by menghao11** [comment]
I signed it!

**Comment by grodrigues3** [comment]
@k8s-bot ok to test

**Comment by mml** [comment]
@kubernetes/sig-testing-misc how do we fix the CLA problem here?

**Comment by cblecker** [comment]
/remove-sig testing
Please email the CNCF helpdesk at helpdesk@rt.linuxfoundation.org for support with the CLA.

**Comment by mml** [comment]
/release-note-none

@menghao11 are you planning to get this merged?

**Comment by mml** [comment]
NM.  I just realized this is a change to the auto-generated changelog.

/undo lgtm

**Pull request closed without merging**
