### PR TITLE
Refactoring Seed Provider and updating docker image

### PR DESCRIPTION
**Pull request by chrislovecnm**
Moving the folders to the correct directory structure, updated maven build plugin.

Major seed provider refactor and unit tests.  Still not testing main `public List<InetAddress> getSeeds()` method.  Will need to build a jetty server in tests to test that.  

`mvn test` now runs a test, but will need jetty to run a full test.

Updated docker to use google/debian:jessie, Cassandra 3.4, and openjdk 1.8.  Added some docker fu to reduce image size.

I do not have a local docker repo with my kubernetes cluster, so I have not done a full integration testing.  Will work on that over the next couple of days.  Basic smoke test on docker works, but will do more testing.  I think we are good, and it would be good to figure out how to setup a test docker repo.

### CODE REVIEW

**Comment by chrislovecnm** [comment]
@bgrant0607 is this big enough that it requires release notes to be updated?

**Comment by chrislovecnm** [comment]
cc @kubernetes/examples

**Comment by bgrant0607** [comment]
ok to test

**Comment by bgrant0607** [comment]
cc @bprashanth

**Comment by bgrant0607** [comment]
cc @kubernetes/examples

**Comment by bgrant0607** [comment]
add to whitelist

**Comment by jeffmendoza** [comment]
@chrislovecnm Please run `hack/update-generated-docs.sh` 

See the failure:

```
Verifying ./hack/../hack/verify-generated-docs.sh
Go version: go version go1.6 linux/amd64
+++ [0427 20:40:37] Building go targets for linux/amd64:
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genyaml
    cmd/genbashcomp
    cmd/mungedocs
+++ [0427 20:41:04] Placing binaries
/go/src/k8s.io/kubernetes/examples/cassandra/README.md
----
md-links:
not printing failed chunk: too many lines
On line 248: "java/src/io/k8s/cassandra/KubernetesSeedProvider.java": target not found
On line 527: "java/src/io/k8s/cassandra/KubernetesSeedProvider.java": target not found

FAIL: changes needed but not made due to --verify
/go/src/k8s.io/kubernetes/examples/ is out of date. Please run hack/update-generated-docs.sh
!!! Error in ./hack/../hack/verify-generated-docs.sh:28
  '"${KUBE_ROOT}/hack/after-build/verify-generated-docs.sh" "$@"' exited with status 1
Call stack:
  1: ./hack/../hack/verify-generated-docs.sh:28 main(...)
Exiting with status 1
FAILED   ./hack/../hack/verify-generated-docs.sh	29s
```

**Comment by chrislovecnm** [comment]
@jeffmendoza can do, but what update docs doing failing on Java code? Lol ... This should be interesting.

**Comment by jeffmendoza** [comment]
It looks like there are links in the README to the java files that you moved, that are now broken.

**Comment by chrislovecnm** [comment]
@jeffmendoza yah ... Well that section needs updating anyways ...

**Comment by chrislovecnm** [comment]
Oh craps ... I rebased from master and this crap happened.  Let me know if you want me to open a new PR ...

**Comment by chrislovecnm** [comment]
Closing will reopen w/o this mess

**Pull request closed without merging**
