### PR TITLE
reduce cpu requirement for etcd, after 2 etcd pods are being run

### PR DESCRIPTION
**Pull request by ArtfulCoder**
#14986

### CODE REVIEW

**Comment by ArtfulCoder** [comment]
This is a cherry-pick candidate for v1.1

**Comment by ArtfulCoder** [comment]
verified manually on gce single-core master. it works


root@kubernetes-master:/home/abshah# docker ps |grep -v pause 
CONTAINER ID        IMAGE                                                                               COMMAND                  CREATED              STATUS              PORTS               NAMES
8255c528c244        gcr.io/google_containers/fluentd-gcp:1.13                                           "/bin/sh -c '/usr/sbi"   37 seconds ago       Up 36 seconds                           k8s_fluentd-cloud-logging.d0f0479_fluentd-cloud-logging-kubernetes-master_kube-system_92a9b3b68ded48697d58b3409eaeba5b_065c51ae
fefaac148c5e        gcr.io/google_containers/kube-controller-manager:692cf2e278fec282c196db7beb1e8015   "/bin/sh -c '/usr/loc"   46 seconds ago       Up 45 seconds                           k8s_kube-controller-manager.f1cc7237_kube-controller-manager-kubernetes-master_kube-system_42d464b772ec5357c60cf6e5b4d3e63d_9eb78f68
02903b76f3e8        gcr.io/google_containers/kube-scheduler:8143c99a79e4e2c36f758daf1806337f            "/bin/sh -c '/usr/loc"   46 seconds ago       Up 45 seconds                           k8s_kube-scheduler.f330fd61_kube-scheduler-kubernetes-master_kube-system_4612400e8b848cabcd304828ed420706_7e2c85f7
f43eaffdc09d        gcr.io/google_containers/kube-apiserver:a3ef20bb6c33f7c5d7dec05223fcc79b            "/bin/sh -c '/usr/loc"   About a minute ago   Up About a minute                       k8s_kube-apiserver.4591d6f_kube-apiserver-kubernetes-master_kube-system_89427757bd446c4e7c498447de8047b5_bc884b74
da882089729b        gcr.io/google_containers/etcd:2.0.12                                                "/bin/sh -c '/usr/loc"   About a minute ago   Up About a minute                       k8s_etcd-container.fbf46722_etcd-server-kubernetes-master_kube-system_23d9fd0c119ef214e8f22f10af70a58d_52e04ca6
afcaf70ee0e7        gcr.io/google_containers/etcd:2.0.12                                                "/bin/sh -c '/usr/loc"   About a minute ago   Up About a minute                       k8s_etcd-container.d3a96f70_etcd-server-events-kubernetes-master_kube-system_13d70b9808aac4dfdd54ba53add2eb3f_c34153fe

**Comment by mikedanese** [comment]
LGTM

**Comment by mikedanese** [comment]
cc @wojtek-t for scalability concerns

**Comment by wojtek-t** [comment]
I think that we should introduce some logic that sets request/limits based on size of the master and/or number of nodes.
So I'm against this PR. I can take a look into it on Monday and introduce some more sophisticated logic. WDYT?

So I'm temporary removing lgtm to avoid merge-bot merging it.

@lavalamp @brendandburns

**Comment by wojtek-t** [comment]
Also, I think that it's fine to reduce shares for "event" etcd, but I'm afraid that reducing it for the "standard" etcd may have negative impact.

On the other hand, I think that in 100-node clusters where we have 4-core master, having 200millicores limit is too small. So I will take a look into it anyway (I though it was 1 core for etcd).
So if this is causing some problems now, feel free to submit it - otherwise I would prefer to look into it on Monday...

**Comment by lavalamp** [comment]
@wojtek-t hack/kube-up.sh is broken at head, so I'm inclined to let this merge and make a better fix later. Thoughts?

**Comment by lavalamp** [comment]
@wojtek-t and @dchen1107 has convinced me that setting proper resource limits in these static files is one of the great Hard Problems of our time, perhaps a close third after the nature of consciousness and the best interpretation of QM.

**Comment by derekwaynecarr** [comment]
I thought on GKE/GCE limits are ignored on the node since enforcement via
CFS quota is off?  If that is case, why specify the limit at all and not just
provide the request?

**Comment by ArtfulCoder** [comment]
I would merge this in for what @lavalamp said https://github.com/kubernetes/kubernetes/pull/14994#issuecomment-145131942

also, it keeps the same behavior for master with more than 1 core

**Comment by dchen1107** [comment]
@derekwaynecarr the problem here is that after @brendandburns introduced a new master component (etcd for event), the feasibility checking on node is failed. https://github.com/kubernetes/kubernetes/pull/10655#issuecomment-117934795 has the detail reason I put those cpu limit / request for master components for 1.0 release. 

But @derekwaynecarr is right on CFS quota is off. We don't do hardcapping for CPU. In this case, what @ArtfulCoder proposed here is totally making sense. Again, we are only using cpu.share, ratio between each daemons are more important than the absolute value here.

**Comment by dchen1107** [comment]
Echo what @lavalamp said above at https://github.com/kubernetes/kubernetes/pull/14994#issuecomment-145132328. What we are dealing here is simply a compressible resource: CPU. Memory is way more harder.

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
@wojtek-t I put lgtm back so that we can merge this, and ppl can move on with non-breaking cluster setup. But feel free to provide a better solution and override this one on Monday. Thanks!

**Comment by ArtfulCoder** [comment]
Thanks Dawn

**Comment by wojtek-t** [comment]
@dchen1107 @ArtfulCoder 
Thanks for fixing (I wasn't aware that head is broken - it was obviously what we should do in that case).
I will take a look into it a bit deeper today.

**Pull request merged**
