### PR TITLE
umount the pods' volume when kube-down

### PR DESCRIPTION
**Pull request by huangyuqi**
The function kube-down of shell script "ubuntu/util.sh" can not run normally, when the k8s cluster has some pods. Because the path "/var/lib/kubelet" contains some pods' volume(mount path), and it can not be deleted. If you run "rm -rf /var/lib/kubelet", the error "rm: cannot remove ... Device or resource busy" will return.So we need to umount first,and then rm the path "/var/lib/kubelet"

### CODE REVIEW

**Comment by huangyuqi** [comment]
@WIZARD-CXY Would you please kindly check this PR? thx

**Comment by huangyuqi** [comment]
@brendandburns would you please check this PR?

**Comment by smarterclayton** [comment]
Running the kubelet in run once mode with no pods would also have this outcome (it should clean the volumes on startup).

**Comment by huangyuqi** [comment]
@smarterclayton , when running kube-down, we want a clean env to deploy a new cluser next time.So we need to move all remains, and need to umonut the volumes of pod. Cloud you please tell me the reason about clean the volumes on startup, if we have umounted the volume in kube-down?

**Comment by smarterclayton** [comment]
What I was getting at was that you don't need to implement your own "volume
cleanup function" if a run once Kubelet invocation does it for you.  I'm
not positive that it does, or should, but letting the Kubelet clean up
volumes is probably better than writing scripts.  It's not a huge issue
though, I just wanted to raise it.

On Tue, Aug 18, 2015 at 4:10 AM, yuqi huang <notifications@github.com>
wrote:

> @smarterclayton <https://github.com/smarterclayton> , when running
> kube-down, we want a clean env to deploy a new cluser next time.So we need
> to move all remains, and need to umonut the volumes of pod. Cloud you
> please tell me the reason about clean the volumes on startup, if we have
> umounted the volume in kube-down?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/12704#issuecomment-132114981>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by huangyuqi** [comment]
@smarterclayton Thanks for your reply, I agree with you. Letting the Kubelet clean up volumes is better than writing scripts. But just paying close attention to the ubuntu's kube-down function(refer to the PR https://github.com/kubernetes/kubernetes/pull/12075), if the cluster has some pods,the shell can not run normally.

**Comment by smarterclayton** [comment]
ok to test

On Mon, Aug 24, 2015 at 2:41 PM, Kubernetes Bot <notifications@github.com>
wrote:

> Can one of the admins verify that this patch is reasonable to test? (reply
> "ok to test", or if you trust the user, reply "add to whitelist")
>
> If this message is too spammy, please complain to ixdy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/12704#issuecomment-134312725>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
My concern shouldn't block this PR from going ahead as is.  Will hand this
back off to someone more familiar with the cluster-up stuff.

On Tue, Aug 25, 2015 at 5:09 PM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> ok to test
>
> On Mon, Aug 24, 2015 at 2:41 PM, Kubernetes Bot <notifications@github.com>
> wrote:
>
>> Can one of the admins verify that this patch is reasonable to test?
>> (reply "ok to test", or if you trust the user, reply "add to whitelist")
>>
>> If this message is too spammy, please complain to ixdy.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/kubernetes/kubernetes/pull/12704#issuecomment-134312725>
>> .
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by huangyuqi** [comment]
@nikhiljindal would you please kindly check this PR? Thanks very much.

**Comment by huangyuqi** [comment]
@smarterclayton Thanks for your all suggestion very much.

**Pull request closed without merging**
