### PR TITLE
cleanup: fix some log and error capitalizations

### PR DESCRIPTION
**Pull request by davidxia**
Part of https://github.com/kubernetes/kubernetes/issues/15863

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Ref #15863

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by davidxia** [comment]
@awly thanks. I removed the changes to places where `utilruntime.HandleError()` was called. I noticed other places like this https://github.com/kubernetes/kubernetes/pull/80318/files#diff-454c2eea64fe8a9161d62b7d39af2a4bL82 where the error isn't passed to `utilruntime.HandleError()` inline but instead passed in the calling function. It's too manual to go through all these changes to verify that they ultimately don't become log lines.

If it's too manual and not scablable to do via humans, seems like this issue should be renamed to something like "find a way to automate this capitalization check"?

Let me know if I should close this PR :)

**Comment by davidxia** [comment]
Another weird thing I noticed is that even though I reverted my changes to lines like this one (note how `Sync` is capitalized) https://github.com/davidxia/kubernetes/blob/fix-err-caps/pkg/controller/bootstrap/tokencleaner.go#L154

the diff in this PR still shows it as changed (`sync` is lowercased). 🤔 

https://github.com/kubernetes/kubernetes/pull/80318/files#diff-24c5b59029bb38c12404c33af32897e5

**Comment by roycaihw** [comment]
cc @cheftako

**Review by mattjmcnaughton — CHANGES_REQUESTED** [review]
Thanks for helping with this clean up :)

The test failures appear to be legit - they are tests that check the exact string content of the errors, so they are failing when run in this manner.

I can mark this "lgtm" after you fix the test failures.

At a high level, I definitely agree we should try and do this automatically or at the very least have some linter to catch these errors on new code. Otherwise, I think we're going to be fighting a never ending battle to keep these properly formatted.

**Review by neolit123 — COMMENTED** [review]
@davidxia 
thanks for the PR
have a look at the failing unit tests:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/80318/pull-kubernetes-bazel-test/1152132076925882372

some tests require error strings to match.

/approve
on the kubeadm changes.

**Comment by davidxia** [comment]
Strange. pull-kubernetes-verify seems to have failed with reason "Pod pending timeout." The corresponding [prow.k8s.io page](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/80318/pull-kubernetes-verify/1152706585206722565) is blank. Not sure if my /test command retried it or not. Anyone know what the issue is here?

**Comment by neolit123** [comment]
> Pod pending timeout.

you might have to report the problem in #sig-testing on slack and request a restart of the test job.

**Comment by nikhita** [comment]
> Not sure if my /test command retried it or not. Anyone know what the issue is here?

It should have been `/test pull-kubernetes-verify` instead of `/retest pull-kubernetes-verify` ;)

**Comment by davidxia** [comment]
@nikhita yay thanks for the right command. Now that all the tests have passed, what are the next steps?

**Comment by neolit123** [comment]
> what are the next steps?

given the PR touches a lot of places it would ideally require a top-level approver.
please be patient if you are not getting an immediate response.

/assign liggitt dchen1107

**Comment by andrewsykim** [comment]
/approve

Thanks @davidxia!

**Pull request merged**
