### PR TITLE
1.1 cherry-pick #15707: Remove all _test.go files in Godep

### PR DESCRIPTION
**Pull request by jimmidyson**
Otherwise some godep bumps fail, e.g. #16193 

/cc @eparis @dchen1107

### CODE REVIEW

**Comment by eparis** [comment]
This need to land after #16259

**Comment by dchen1107** [comment]
@jimmidyson I am ok to remove those tests in GoDep, but why those tests trigger the failure?

**Comment by dchen1107** [comment]
My concern is that if this will cause issue for us to do godep upgrade in the future? cc/ @brendandburns

**Comment by jimmidyson** [comment]
@dchen1107 Because the cherry-pick commit is done in the now recommended `godep save` way (no test dependencies). Comparison will fail as 1.1 branch has test dependencies for cadvisor & libcontainer.

**Comment by jimmidyson** [comment]
@dchen1107 @eparis The whole point is to make it _easier_ to do godep upgrades in future.

**Comment by brendandburns** [comment]
if I do a `go get -u` to upgrade the dependencies won't it freak out if there are local changes?

**Comment by dchen1107** [comment]
@jimmidyson That makes sense.

**Comment by dchen1107** [comment]
re-run shippable here.

**Comment by eparis** [comment]
@brendandburns I don't really understand the question.  `godep save` used to include all _test.go and `testdata/` files. The default changed.  Now `godep save` will not include those. You can use `godep save -t` to get the old behavior.

If you do a `go get -u` you there will be `_test.go` files in your $GOPATH. But `godep update` or `godep save` will not bring those into the tree.

**Comment by jimmidyson** [comment]
@brendandburns If you mean `godep update` then that now wipes out any test files anyway - this was the problem that the original PR (#15707) solves.

**Comment by brendandburns** [comment]
@eparis ok, makes sense to me.  My concern was that `godep restore` followed by `go get -u ...` which has been the usual update path in the past would be confused/broken by this...

**Comment by eparis** [comment]
`godep restore`; `go get -u bob`; `godep update bob`; should result in `_test.go` files in `$GOPATH` and no `_test.go` in `Godeps/_workspace`

**Comment by brendandburns** [comment]
Ok, LGTM.

**Comment by jimmidyson** [comment]
Rebased against 1.1 branch.

**Comment by jimmidyson** [comment]
Unrelated e2e flake:

```
Summarizing 1 Failure:                                                                                                                                                                        
                                                                                
[Fail] Deployment [It] deployment should delete old pods and create new ones•   
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:173
```

**Comment by eparis** [comment]
@k8s-bot test this please

**Comment by jimmidyson** [comment]
Successful e2e, do we need to wait for shippable which has been sitting idle for over 6 hours now... Really keen to get this merged.

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
@krousey, build cop, Can we manually merge this pr? This one blocks our cadvisor fix: #16193 to 1.1 release.

**Comment by krousey** [comment]
@dchen1107 I could, but there are unit test failures and currently the merge bot is running.

**Comment by krousey** [comment]
@k8s-bot unit test this

Also there's some CLA issue

**Comment by eparis** [comment]
k8s bot can't unit test on release-1.1 can it?

**Comment by krousey** [comment]
@eparis good point. oops.

**Comment by krousey** [comment]
Adding CLA label since both @jimmidyson and @eparis seem to be ok with this.

**Comment by dchen1107** [comment]
Like @eparis mentioned k8s bot can't unit test on release-1.1. This pr just remove all _test.go files, and the only concern I and @brendandburns had is the potential issue of godep upgrades in the future. @jimmidyson and @eparis clear that concern. 

Let's merge this now. Thanks!

**Comment by krousey** [comment]
merging since this is blocking other 1.1 cherry picks and this just deletes vendored tests.

**Comment by krousey** [comment]
I will continue to watch 1.1 CI to make sure this is fine.

**Comment by jimmidyson** [comment]
Thanks @krousey & @dchen1107!

**Pull request merged**
