### PR TITLE
useless code

### PR DESCRIPTION
**Pull request by bonowang**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by shiywang** [comment]
@bonowang please squash your commit

**Comment by bonowang** [comment]
> @bonowang please squash your commit

do i need create new PR? @shiywang

**Comment by shiywang** [comment]
@bonowang no you just need to squash your commit like `git rebase -i HEAD~2` in your case
ref: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by bonowang** [comment]
sorry, this PR is wrong, i will close it and try create a new one

**Pull request closed without merging**
