### PR TITLE
cleanup(kubelet): remove unused function

### PR DESCRIPTION
**Pull request by HirazawaUi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
clean up unused functions, this function always returns nil and not implemented on windows and linux

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
I think this is a leftover of https://github.com/kubernetes/kubernetes/pull/90377

/ok-to-test

**Comment by bart0sh** [comment]
> I think this is a leftover of #90377

For me it looks like a useful stub that can be used in future. I'd leave it as it is.
@klueska @swatisehgal @SergeyKanzhelev WDYT?

**Review by SergeyKanzhelev — APPROVED** [review]
/priority backlog
/lgtm
/triage accepted

**Comment by SergeyKanzhelev** [comment]
> > I think this is a leftover of #90377
> 
> For me it looks like a useful stub that can be used in future. I'd leave it as it is. @klueska @swatisehgal @SergeyKanzhelev WDYT?

looks like it was introduced for CPU manager and then removed as CPU manager didn't need it any longer. If we will needed it again, we can add it later

**Comment by bart0sh** [comment]
> looks like it was introduced for CPU manager and then removed as CPU manager didn't need it any longer. If we will needed it again, we can add it later

It looks like `PreStopContainer ` was [intentionally left empty](https://github.com/kubernetes/kubernetes/pull/90377/files#diff-d17460fa38eb2cd74f0a302692bba7fa5a519c3c37598db08ee84a7a6dcffb26L57-L59) to keep the interface consistent and integrated into the [container Lifecycle Hooks](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/).

I'm ok with removing it if we want, but we should think if it worth it.

**Comment by derekwaynecarr** [comment]
I think it makes sense to remove the function and if we actually need the hook in the future it would make sense to re-add and ensure its working as expected when used.

/approve
/lgtm

**Pull request merged**
