### PR TITLE
Enable graceful termination for UDP flows when using kube-proxy in IPVS mode

### LINKED ISSUE #71514: In IPVS mode, kube-proxy doesn't handle graceful termination of UDP flows
**What happened**:
On pods with a lot of DNS traffic, many DNS queries to the DNS ClusterIP fail during a rolling update of the DNS pods (in our case, we use coredns).

**What you expected to happen**:
Almost all DNS queries should succeed during a rolling update.

**How to reproduce it (as minimally and precisely as possible)**:
* Create a coredns (this would probably be the same with kube-dns) service backed by 2 pods
* Access this service by creating a lot of DNS queries, for example:
```
while true ; do dig +tries=1 -4 +short A <name> @<dns clusterIP> ; sleep 0.05 ; echo "--" ; done
```
* Wait for the IPVS connection table to contain a lot of DNS connections (a few minutes)
* Delete a DNS pod

A significant number of queries will timeout. After 5mn (depending in the IPVS timeout configuration) everything will work ok again.

**Anything else we need to know?**:
This comes from the current logic in the graceful termination code:

The current logic is to delete a RS if the number of active connections is 0. This makes sense for TCP but for UDP the number of active connections is always 0. This is an issue for DNS queries because the RS will be deleted but the IPVS connection will remain until it expires (5mn by default) and if there are a lot of DNS queries, the port will be reused and queries blackholed.

In addition, `net.ipv4.vs.expire_nodest_conn=1` will not always work here because IPVS only removes connections when a packet is processed (in the case of DNS once the client receives an answer, no more packets are sent).

**Environment**:
- Kubernetes version (use `kubectl version`): kube-proxy `v1.13.0-alpha.3`
- OS (e.g. from /etc/os-release): `Ubuntu 18.04.1 LTS`
- Kernel (e.g. `uname -a`): `Linux ip-10-128-212-113 4.15.0-1023-aws #23-Ubuntu SMP Mon Sep 24 16:31:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

/area ipvs
/sig network
/kind bug

/assign @m1093782566

### PR DESCRIPTION
**Pull request by lbernail**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
The current graceful termination logic is to delete a RS if the number of active connections is 0. This makes sense for TCP but for UDP the number of active connections is always 0. This is an issue for DNS queries because the RS will be deleted but the IPVS connection will remain until it expires (5mn by default) and if there are a lot of DNS queries, the port will be reused and queries blackholed.

Of course for this to work properly the service needs to continue to serve queries until the connections expire (this works fine with the lameduck option of coredns).

**Which issue(s) this PR fixes** *
Fixes #71514

**Special notes for your reviewer**:
In addition to this fix, the PR also includes a small fix in the `delete` function which was never removing entries from the `graceTerminateRSList` and a small improvement in logging to use the full RS name in logs to identify the service associated with it (helpful for DNS because when a pod is deleted both the TCP and UDP endpoints are removed). I can of course create separate PRs if needed

**Does this PR introduce a user-facing change?**:
```release-note
UDP connections now support graceful termination in IPVS mode
```

/assign @m1093782566

### CODE REVIEW

**Comment by m1093782566** [comment]
LGTM

/milestone v1.13

/approve

**Comment by m1093782566** [comment]
Adding

/priority critical-urgent

as there are some related outstanding issues.

/lgtm

@Lion-Wei given the priority, I am going to merge this PR. Please feel free to put your comments.

**Comment by Lion-Wei** [comment]
@lbernail @m1093782566 I'm so sorry for this mistake, thanks for caching this.
All looks good to me.

**Comment by lbernail** [comment]
Quick question before merging, I wonder if instead of doing:
```
if rs.ActiveConn != 0 || (rsToDelete.VirtualServer.Protocol == "UDP" && rs.InactiveConn != 0)
```
we should not do instead:
```
if rs.ActiveConn + rs.InactiveConn != 0
```
If we do that, TCP connections will be cleaned up slightly later but it allows for a clean shutdown of TCP connections (the current test for TCP drops the connection as soon as it is inactive which breaks the TCP standard behavior)

**Comment by lbernail** [comment]
I just tested with this and it worked fine
What do you think?

**Comment by m1093782566** [comment]
Great to hear the fix works :+1:

**Comment by lbernail** [comment]
I meant the one I just proposed, testing for `rs.ActiveConn + rs.InactiveConn != 0`
(I had already tested the UDP only fix)

**Comment by m1093782566** [comment]
oops...

/hold

**Comment by lbernail** [comment]
I just added a commit with the change I'm proposing

**Comment by lbernail** [comment]
I think this change implements a better behavior for TCP connections. However it slightly changes how we handle them. We can limit this PR to UDP if you prefer and discuss TCP later?

**Comment by lbernail** [comment]
I don't think we have tests for graceful termination yet. Happy to help work on them

**Comment by m1093782566** [comment]
>  We can limit this PR to UDP if you prefer and discuss TCP later?

Sounds like a good plan. We need to fix the UDP graceful termination first as there are some outstanding issues.

> I don't think we have tests for graceful termination yet. Happy to help work on them

Great!

**Comment by m1093782566** [comment]
@lbernail gofmt please.

/lgtm

**Comment by lbernail** [comment]
go fmt fixed
sorry about that

**Comment by AishSundar** [comment]
@lbernail @m1093782566 was this PR meant for 1.13? we no longer accept merges into 1.13 branch and only extremely critical urgent fixes can to be CP'ed if needed.

**Comment by nikopen** [comment]
@lbernail @m1093782566 this fix looks rather important, but we need to assess the criticality of this fix and how stable it is to merge for 1.13.0 (release is on Monday).  Let us know about the details:

- Is this a new bug on 1.13-alpha or is it longstanding / should be backported to previous releases?
- How well has it been tested / what are the possibilities of release-blocking CI tests failing?
- Can it be merged for 1.13.1?

I think this can go in, and be reverted if it introduces any CI problems due to lack of time.

**Comment by m1093782566** [comment]
I think it can be merged in 1.13.1.

**Comment by AishSundar** [comment]
@tpepper and @aleksandra-malinowska to consider this as a possible 1.13.1 patch release candidate.

/milestone clear

/hold cancel

**Pull request merged**
