### PR TITLE
[e2e] Also verify content returned by kube-proxy healthz url

### PR DESCRIPTION
**Pull request by MrHohn**
**What this PR does / why we need it**: Enhance kube-proxy url test. This helps to detect the port collision case --- node-problem-detector also serves /healthz to return 200 ok. Verify the content to confirm /healthz is served by kube-proxy.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: From #49263

**Special notes for your reviewer**:
/assign @freehan @nicksardo 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by krzyzacy** [comment]
enjoy the flake..

**Comment by MrHohn** [comment]
Thanks,
/assign @bowei 
for approval.

**Pull request merged**
