### PR TITLE
rebase gophercloud to support HTTP status 300 in pagination, so listingng Cinder v1/v2 API versions won't break

### LINKED ISSUE #47651: Cinder API list received unsupported HTTP status 300 code
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see https://kubernetes.io/docs/tasks/debug-application-cluster/troubleshooting/.):

**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                               |
| --------- | ------------------------------------------------------------------ |
| kubectl   | [kubernetes/kubectl](https://github.com/kubernetes/kubectl/issues/new) |
| kubeadm   | [kubernetes/kubeadm](https://github.com/kubernetes/kubeadm/issues/new) |

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
1.7

**Environment**:
- **Cloud provider or hardware configuration**: OpenStack
- **OS** (e.g. from /etc/os-release): RHEL
- **Kernel** (e.g. `uname -a`): 3.10
- **Install tools**: Ansible
- **Others**:

**What happened**:

we hit this issue in kubernetes in this [line](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L615)

The api response is 
```console
# curl -i  -w %{http_code}  http://xxx:8776/
HTTP/1.1 300 Multiple Choices
Content-Type: application/json
Content-Length: 1371
Openstack-Api-Version: volume 3.0
Vary: OpenStack-API-Version
Date: Wed, 14 Jun 2017 19:28:15 GMT

{
    "versions": [
        {
            "status": "SUPPORTED",
            "updated": "2014-06-28T12:20:21Z",
            "links": [
                {
                    "href": "http://docs.openstack.org/",
                    "type": "text/html",
                    "rel": "describedby"
                },
                {
                    "href": "http://xxx:8776/v1/",
                    "rel": "self"
                }
            ],
            "min_version": "",
            "version": "",
            "media-types": [
                {
                    "base": "application/json",
                    "type": "application/vnd.openstack.volume+json;version=1"
                },
                {
                    "base": "application/xml",
                    "type": "application/vnd.openstack.volume+xml;version=1"
                }
            ],
            "id": "v1.0"
        },
        {
            "status": "SUPPORTED",
            "updated": "2014-06-28T12:20:21Z",
            "links": [
                {
                    "href": "http://docs.openstack.org/",
                    "type": "text/html",
                    "rel": "describedby"
                },
                {
                    "href": "http://xxx:8776/v2/",
                    "rel": "self"
                }
            ],
            "min_version": "",
            "version": "",
            "media-types": [
                {
                    "base": "application/json",
                    "type": "application/vnd.openstack.volume+json;version=1"
                },
                {
                    "base": "application/xml",
                    "type": "application/vnd.openstack.volume+xml;version=1"
                }
            ],
            "id": "v2.0"
        },
        {
            "status": "CURRENT",
            "updated": "2016-02-08T12:20:21Z",
            "links": [
                {
                    "href": "http://docs.openstack.org/",
                    "type": "text/html",
                    "rel": "describedby"
                },
                {
                    "href": "http://xxx:8776/v3/",
                    "rel": "self"
                }
            ],
            "min_version": "3.0",
            "version": "3.0",
            "media-types": [
                {
                    "base": "application/json",
                    "type": "application/vnd.openstack.volume+json;version=1"
                },
                {
                    "base": "application/xml",
                    "type": "application/vnd.openstack.volume+xml;version=1"
                }
            ],
            "id": "v3.0"
        }
    ]
}300
```

According to https://developer.openstack.org/api-guide/compute/versions.html, HTTP status 300 could return when blockstorage list API versions.

**What you expected to happen**:
Cinder API list should pass

**How to reproduce it** (as minimally and precisely as possible):
Run kubernetes with Openstack Liberty release

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by rootfs**
**What this PR does / why we need it**:
Since Cinder block v1/v2 support lands in 1.7, we have to ensure Cinder block api list won't fail due to https://github.com/gophercloud/gophercloud/pull/384.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #47651

**Special notes for your reviewer**:

@anguslees @NickrenREN 

**Release note**:

```release-note
Fix Cinder to support http status 300 in pagination
```

### CODE REVIEW

**Comment by rootfs** [comment]
@eparis @childsb

**Comment by dims** [comment]
+1 LGTM

**Comment by rootfs** [comment]
@k8s-bot pull-kubernetes-verify test this

**Comment by rootfs** [comment]
@brendandburns can you approve? thanks

**Comment by brendandburns** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by rootfs** [comment]
@brendandburns Thanks, I opened issue https://github.com/kubernetes/kubernetes/issues/47651

**Comment by delfer** [comment]
All 1.6.x and 1.7.x releases broken for now (can not work with cinder).
When this PR will be released?

**Comment by stuart-warren** [comment]
This is really affecting us too on 1.7

Any chance in backporting?

/label cherrypick-candidate :)

**Comment by rootfs** [comment]
@delfer @stuart-warren what error message did you see when you hit this issue?

**Comment by delfer** [comment]
@rootfs When kubernetes asks openstack for cinder endpoints it got http error 300 - multiple choices. Means var variants: http://cinder_api/v1, http://cinder_api/v2, http://cinder_api/v3

**Comment by rootfs** [comment]
@delfer @stuart-warren cherry-pick PR opened.

@idvoretskyi can you approve 1.7 cherry pick PR #49026? Thanks

**Comment by jamiehannaford** [comment]
Will this make it into 1.7.3? I didn't see it in 1.7.2 release or changelog

**Comment by delfer** [comment]
Can confirm problem on 1.7.2

> Events:
>   FirstSeen     LastSeen        Count   From                            SubObjectPath   Type            Reason                  Message
>   ---------     --------        -----   ----                            -------------   --------        ------                  -------
>   32s           32s             1       default-scheduler                               Normal          Scheduled               Successfully assigned app-2122882019-hxk23 to test-k8s-node-nf-2
>   32s           32s             1       kubelet, test-k8s-node-nf-2                     Normal          SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "default-token-fcmxr"
>   31s           13s             6       attachdetach                                    Warning         FailedMount             AttachVolume.Attach failed for volume "pv" : Expected HTTP response code [200 204] when accessing [GET http://192.168.72.51:8776/], but got 300 instead
> {"versions": [{"status": "DEPRECATED", "updated": "2016-05-02T20:25:19Z", "links": [{"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}, {"href": "http://192.168.72.51:8776/v1/", "rel": "self"}], "min_version": "", "version": "", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.volume+json;version=1"}], "id": "v1.0"}, {"status": "SUPPORTED", "updated": "2014-06-28T12:20:21Z", "links": [{"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}, {"href": "http://192.168.72.51:8776/v2/", "rel": "self"}], "min_version": "", "version": "", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.volume+json;version=1"}], "id": "v2.0"}, {"status": "CURRENT", "updated": "2016-02-08T12:20:21Z", "links": [{"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}, {"href": "http://192.168.72.51:8776/v3/", "rel": "self"}], "min_version": "3.0", "version": "3.27", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.volume+json;version=1"}], "id": "v3.0"}]}

Please, `cherrypick` to 1.7.1 1.7.2 1.7.3

**Comment by rootfs** [comment]
@jamiehannaford 1.7 cherrypick landed in release-1.7 branch a day ago. It should be in next 1.7 release.

**Comment by arykalin** [comment]
Got this on 1.7.2

**Comment by andrey01** [comment]
yep, same here.. as a workaround add the following chunk to your cloud provider conf file:

```
[BlockStorage]
bs-version=v2
```

**Comment by stuart-warren** [comment]
Should be in 1.7.3 https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#changelog-since-v172

**Pull request merged**
