### PR TITLE
Rename REASON column to STATUS for kubectl get

### LINKED ISSUE #10560: kubectl get pods says REASON, but reason for what?
Example output from my cluster:
```
$ kubectl get pods
NAME                      READY     REASON                                  RESTARTS   AGE
cpuhog                    0/1       ExitCode:127                            0          1h
frontend                  0/2       Pending                                 0          1h
frontend2                 0/1       Running                                 12         48m
frontend3                 0/1       Running                                 11         39m
frontend4                 0/1       Pending                                 0          18m
frontendbig               0/2       Pending                                 0          16s
kube-dns-v3-hzdfg         3/3       Running                                 2          3d
memhog                    0/1       OOM Killed                              0          5m
private-image-test-2      0/1       Running                                 12         3d
private-image-test-3      0/1       Error: image foo/private:v1 not found   0          3d
```

What is the REASON column a reason *for*?
It looks like it is the reason for being terminated if terminated, otherwise it is showing `status.phase`, except when `status.phase == "Failed"`, in which case it shows one of the `.status.containerStatuses[].state.terminated.reason`.

I think it would be clearer to show phase and then reason, so that it is clear that the reason about why it is in that phase.

For example:
```
$ kubectl get pods
NAME                      READY     PHASE    REASON                                  RESTARTS   AGE
cpuhog                    0/1       Failed   ExitCode:127                            0          1h
frontend                  0/2       Pending                                          0          1h
frontend2                 0/1       Running                                          12         48m
frontend3                 0/1       Running                                          11         39m
frontend4                 0/1       Pending                                          0          18m
frontendbig               0/2       Pending                                          0          16s
kube-dns-v3-hzdfg         3/3       Running                                          2          3d
memhog                    0/1       Failed   OOM Killed                              0          5m
private-image-test-2      0/1       Running                                          12         3d
private-image-test-3      0/1       Pending  Error: image foo/private:v1 not found   0          3d
```

I get that we are trying to save screen width.  It costs 8 columns to separate Phase.
We could recover 3 columns by narrowing the READY column
and another 3 by renaming "RESTARTS" to "TRIES".

### PR DESCRIPTION
**Pull request by andronat**
Fixes #10560

### CODE REVIEW

**Comment by ghodss** [comment]
@bgrant0607

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
Restarted shippable

**Comment by andronat** [comment]
any news on that?

**Comment by bprashanth** [comment]
@erictune please apply ok-to-merge when you've lgtm'd this

**Comment by caesarxuchao** [comment]
LGTM. This is a trivial change, so I will add the ok-to-merge label.

**Pull request merged**
