### PR TITLE
Obtain write lock after pods to move have been determined

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
In PriorityQueue#flushUnschedulableQLeftover, we obtain write lock at the beginning of the func.

Write lock is only needed when the pods to move have been determined.

```release-note
NONE
```

### CODE REVIEW

**Comment by tedyu** [comment]
ping @Huang-Wei

**Review by misterikkit — COMMENTED** [review]
Unlocking in the middle of the function makes me a little uneasy, but maybe I'm being overly paranoid.

Although it seems unlikely, nothing prevents the state in `unschedulableQ` from changing between lines 379 and 382. When we have had similar behaviors elsewhere in the scheduler, it resulted in us persisting stale data & introduced subtle bugs.

Can you show how lock contention in this function is a problem, or show the performance delta with this change? Let me know if you need help running scheduler benchmarks.
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-scheduling/scheduler_benchmarking.md

**Comment by tedyu** [comment]
I tried:
```
make test-integration WHAT=./test/integration/scheduler_perf KUBE_TEST_VMODULE="''" KUBE_TEST_ARGS="-run=xxx -bench=BenchmarkScheduling"
```
The test seems to take quite some time.

**Comment by misterikkit** [comment]
Yeah, these things can be slow on desktop computers. And we can't really compare benchmark runs from different machines either.

"upgrading" the lock from reader to writer in this way adds a small amount of complexity to the logic. So I want to make sure there's a benefit before we merge such a change. I'd also like to think some more about the consequence of calling `p.movePodsToActiveQueue(podsToMove)` with stale data. Maybe it is always safe?

**Comment by tedyu** [comment]
The test didn't run to completion on my Mac:
```
goroutine 1970976 [select, 1 minutes]:
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*Reflector).watchHandler(0xc00b92ce60, 0x7edb520, 0xc008298480, 0xc0140d5cc0, 0xc0129093e0, 0xc00924e7e0, 0x0, 0x0)
	/Users/yute/go-workspace/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/reflector.go:329 +0x1d9
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc00b92ce60, 0xc00924e7e0, 0x0, 0x0)
	/Users/yute/go-workspace/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/reflector.go:300 +0x879
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.(*Cacher).startCaching(0xc028702140, 0xc00924e7e0)
	/Users/yute/go-workspace/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go:390 +0xe9
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.NewCacherFromConfig.func1.1()
	/Users/yute/go-workspace/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go:358 +0x61
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc021ce57a8)
	/Users/yute/go-workspace/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0140d5fa8, 0x3b9aca00, 0x0, 0xc033018101, 0xc00924e7e0)
	/Users/yute/go-workspace/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	/Users/yute/go-workspace/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.NewCacherFromConfig.func1(0xc028702140, 0xc00924e7e0)
	/Users/yute/go-workspace/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go:355 +0xd6
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher.NewCacherFromConfig
	/Users/yute/go-workspace/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/cacher/cacher.go:352 +0x9fd

goroutine 1971830 [select, 1 minutes]:
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc024993980)
	/Users/yute/go-workspace/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:122 +0x110
created by k8s.io/kubernetes/vendor/google.golang.org/grpc.newCCBalancerWrapper
	/Users/yute/go-workspace/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:113 +0x13e

goroutine 2119145 [select]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0175a5110, 0xdf8475800, 0x3ff3333333333333, 0x1, 0xc009cfe960)
	/Users/yute/go-workspace/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:164 +0x181
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry.(*Store).startObservingCount
	/Users/yute/go-workspace/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:1345 +0x21c

goroutine 1971001 [select, 1 minutes]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3.(*watchChan).run(0xc000b67980)
	/Users/yute/go-workspace/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go:141 +0x1c4
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3.(*watcher).Watch
	/Users/yute/go-workspace/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go:110 +0x11e

goroutine 2118972 [select]:
k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3.(*watchGrpcStream).run(0xc01a1edd40)
	/Users/yute/go-workspace/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3/watch.go:438 +0x35f
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3.(*watcher).newWatcherGrpcStream
	/Users/yute/go-workspace/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/clientv3/watch.go:236 +0x2de

rax    0x104
rbx    0x1430900
rcx    0x7ffeefbff1d8
rdx    0x1430900
rdi    0xacb5fa8
rsi    0x143090101430a00
rbp    0x7ffeefbff270
rsp    0x7ffeefbff1d8
r8     0x0
r9     0x60
r10    0x0
r11    0x202
r12    0xacb5fa8
r13    0x7ffeefbff1f8
r14    0x1
r15    0x7fff911e5380
rip    0x7fff588eaa16
rflags 0x203
cs     0x7
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
```

**Comment by tedyu** [comment]
@misterikkit 
I added code to guard against stale PodInfo

Can you take another look ?

Thanks

**Comment by misterikkit** [comment]
@tedyu 
Yeah, it looks like the guard you added would prevent that type of bug. But at this point I really want to know if this change is solving a real problem or if it is only a theoretical benefit.

Although `flushUnschedulableQLeftover` is called every 30s, there are other frequent functions that obtain either a read lock or a write lock (e.g. pod add). None of these functions appear to hold the lock longer than needed to read or update some internal state. i.e. I don't see any RPC calls. Unless lock contention in this module is causing performance issues, I don't think we should merge this change.

**Comment by tedyu** [comment]
Commenting out the 5000 node test, benchmark still times out:
```
*** Test killed with quit: ran too long (10m0s).
exit status 2
FAIL	k8s.io/kubernetes/test/integration/scheduler_perf	601.811s
```

**Comment by misterikkit** [comment]
I am sorry these tests don't work well on desktop machines. Another approach would be to profile the scheduler. That involves building a scheduler (e.g. from master) with profiling enabled and running it against your large cluster.

BTW, can you share more details about your cluster setup, or is it confidential?

**Comment by tedyu** [comment]
I would share cluster information at a later time.

thanks

**Comment by misterikkit** [comment]
I ran the benchmark on my work machine to obtain these results: https://gist.github.com/misterikkit/2325e930d0c1bfa13cf2e74879e86d53

On the worst benchmark (about 52ms) this made <1ms of a difference.

**Pull request closed without merging**
