### PR TITLE
Convert internal types to use exact precision integers

### PR DESCRIPTION
**Pull request by smarterclayton**
This makes conversion more suitable for future optimizations, and we need to stop pretending for some of our internal types that the width of the int doesn't matter.

@wojtek-t

### CODE REVIEW

**Comment by smarterclayton** [comment]
Extract from #24845

**Comment by smarterclayton** [comment]
The changes to int aren't perfect, but this is an incredibly painful refactor to manage, so I'd argue to push some of it to the individual code owners and they can clean up as they want.

**Comment by smarterclayton** [comment]
@kubernetes/sig-api-machinery this continues an earlier problem (pushing it out of the API) which blocks some significant performance gains in our serialization / conversion code.  It's a brute to refactor so I was hoping to get a quick merge.

**Comment by smarterclayton** [comment]
@lavalamp @thockin can I get some eyeballs / agreement on this?  I don't think we should be ambiguous about int type on our value objects (especially since our external int types are not), and the "pain" is something go clients just have to deal with (versioned clients would as well).  In turn, this sets us up for some significant allocation / performance wins in our conversion path (~20-25% in some cases) as part of my follow on.

**Comment by lavalamp** [comment]
I'm backlogged, still halfway through one of your other PRs, but I skimmed this one and I'm on board. Internal users shouldn't be using values that don't fit in the external types. We can fix/reduce the number of casts over time.

Consider this an LGTM if you rebase & squash, and feel free to apply the p0 label to get it through the queue before it needs another rebase.

**Comment by smarterclayton** [comment]
Thanks, will do so.

**Comment by smarterclayton** [comment]
Rebased, applying p0 and LGTM to clear the queue.

**Comment by smarterclayton** [comment]
@K8s-bot test this issue: IGNORE

No e2e data

**Comment by smarterclayton** [comment]
@k8s-bot test this issue #24661

**Pull request merged**
