### PR TITLE
hack/local-up-cluster.sh: support extending the generated configs

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

It may be useful to append additional content at the end of the generated
configurations to add or overwrite settings. For example, scheduler extenders
must be listed in kube-scheduler.yaml.

#### Does this PR introduce a user-facing change?
```release-note
hack/local-up-cluster.sh: support custom config fragments (for example, for scheduler extenders)
```

### CODE REVIEW

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by pohly** [comment]
It's failing somehow and I don't need it (anymore), so:
/close

**Pull request closed without merging**
