### PR TITLE
Revert changes to WaitForStableCluster in scheduler e2e test

### LINKED ISSUE #84980: [Failing test] Conformance-GCE-master (ci-kubernetes-gce-conformance-latest)
**Which jobs are failing**:
Conformance-GCE-master

**Which test(s) are failing**:
```
[sig-scheduling] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run [Conformance]Changes

[sig-scheduling] SchedulerPredicates [Serial] validates that NodeSelector is respected if not matching [Conformance]Changes
```

**Since when has it been failing**:
11-07 14:41 PST probably after this PR got merged https://github.com/kubernetes/kubernetes/commit/62f66ea2f

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#Conformance%20-%20GCE%20-%20master

**Reason for failure**:
```
I1108 08:03:43.432] [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/framework.go:34[0m
I1108 08:03:43.433]   [91m[1mvalidates that NodeSelector is respected if not matching  [Conformance] [It][0m
I1108 08:03:43.433]   [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:680[0m
I1108 08:03:43.433] 
I1108 08:03:43.433]   [91mNov  8 08:03:42.506: Timed out after 10m0s waiting for stable cluster.[0m
I1108 08:03:43.434] 
I1108 08:03:43.434]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/framework.go:55
```

**Anything else we need to know**:
/cc @droslean  @hasheddan @alejandrox1

/sig scheduling
/milestone v1.17
/priority critical-urgent

### PR DESCRIPTION
**Pull request by ahg-g**
**What type of PR is this?**

/kind flake

**What this PR does / why we need it**:
#84806 changed the condition for waiting for a "stable cluster" in e2e tests. Originally we waited for all pods in the system to schedule, #84806 changed that to wait until there are no pods in any  namespace other than kube-system (and be in scheduled state). 

The reason we did that is because we wanted to wait until pods that were created by other tests to actually be deleted, and the assumption was that those pods are created in namespaces other than kube-system.

We don't have good insight to why this didn't work since we don't have enough logs from the test. For now, this PR reverts to the old condition, and in a follow up PR we will try another approach to wait for pods that are subject to deletion to actually get deleted. Perhaps what we should wait for is for pods in deleted namespaces to disappear.

**Which issue(s) this PR fixes**:
Partially Fixes #84980

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by draveness** [comment]
can we trigger the conformance test here, or we have to wait for this get merged into master

**Review by draveness — COMMENTED** [review]
/lgtm

Thanks

**Comment by damemi** [comment]
Did this change break the test further? Or just not address the flake?

**Comment by alculquicondor** [comment]
"Partially fixes" in the PR description will still close the issue. Is that intended?

**Comment by ahg-g** [comment]
> "Partially fixes" in the PR description will still close the issue. Is that intended?

Broke it further.

**Comment by ahg-g** [comment]
> "Partially fixes" in the PR description will still close the issue. Is that intended?

It actually fixes that specific flake, so should be fixes rather than partially.

**Pull request merged**
