### PR TITLE
If don't use formatted output,fix logging calls

### PR DESCRIPTION
**Pull request by mikeweiwei**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
If don't use formatted output,fix logging calls
**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/ok-to-test

**Comment by yue9944882** [comment]
@mikeweiwei what's the difference between `Infof` and `Info`? they looks completely equal. is it a problem?

**Comment by mikeweiwei** [comment]
> @mikeweiwei what's the difference between `Infof` and `Info`? they looks completely equal. is it a problem?



> @mikeweiwei what's the difference between `Infof` and `Info`? they looks completely equal. is it a problem?

**Comment by mikeweiwei** [comment]
Their differences are like fmt.Printf () and fmt.Print ()?

**Comment by mikeweiwei** [comment]
> @mikeweiwei what's the difference between `Infof` and `Info`? they looks completely equal. is it a problem?

Their differences are like fmt.Printf () and fmt.Print ()?

**Comment by yliaog** [comment]
please squash the commits, looks good otherwise.

**Comment by mikeweiwei** [comment]
> please squash the commits, looks good otherwise.

ok

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Pull request closed without merging**
