### PR TITLE
remove internal event reference in admission plugin

### PR DESCRIPTION
**Pull request by yue9944882**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yue9944882** [comment]
I tried to resolve event into external types. What a mistake.. Ignore me..

**Comment by deads2k** [comment]
> I tried to resolve event into external types. What a mistake.. Ignore me..

For others going down the path, admission (and all internal apiserver code) deals with internal versions so that we don't have to produce duplicate code for every version created.

**Comment by yue9944882** [comment]
@deads2k  I got a little confused then when I saw `NamespaceLifecycle` is using external informers here. 

[https://github.com/kubernetes/kubernetes/blame/cff2a2af43a606d3e6d0925e36c11a8d411965ee/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go#L193](https://github.com/kubernetes/kubernetes/blame/cff2a2af43a606d3e6d0925e36c11a8d411965ee/staging/src/k8s.io/apiserver/pkg/admission/plugin/namespace/lifecycle/admission.go#L193)

**Pull request closed without merging**
