### PR TITLE
fix: azure disk name matching issue

### LINKED ISSUE #81079: Disks are not detached on Azure
**What happened**:
Pods with PVs could not be moved from one node to another. According to the controller-manager logs, K8s tried to detach to Azure disks from the same node. One of the detach operation waited for this lock (https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_controller_common.go#L136). While it waited for the lock, the controller-manager pod was restarted (for whatever reason, not related to this bug, lets assume an operator restarted the pod). After the restart, K8s only tried to attach the disk to the new node but is not trying to detach it first.

**What you expected to happen**:
After a restart of the controller-manager, it should continue unfinished detach operations

**How to reproduce it (as minimally and precisely as possible)**:
* 2 Pods with PVs running on one node
* Move both pods to another node
* restart the controller-manager shortly after the move

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.1
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
disk name matching should be case insensitive, proceeding fix with https://github.com/kubernetes/kubernetes/pull/81266

**Which issue(s) this PR fixes**:

Fixes #81079

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix azure disk naming matching issue due to case sensitive comparison
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
none
```

/kind bug
/assign @feiskyer 
/priority important-soon
/sig cloud-provider
/area provider/azure

### CODE REVIEW

**Comment by feiskyer** [comment]
@andyzhangx do we need cherrypicking this to old releases?

**Comment by andyzhangx** [comment]
> @andyzhangx do we need cherrypicking this to old releases?

I think so, let me do it soon.

**Pull request merged**
