### PR TITLE
Fix unit tests for filtering

### PR DESCRIPTION
**Pull request by liggitt**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aaron-prindle** [comment]
/lgtm

confirmed this fixes https://github.com/kubernetes/kubernetes/issues/127174

With the changes in this PR, tests now pass standalone, eg:
```
# TestFilter
...
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if tc.name != "test authorizer error using fieldSelector with 1.30 compatibility" {
				t.SkipNow()
			}
```

```
Running tool: /usr/lib/google-golang/bin/go test -timeout 30s -run ^TestFilter$ k8s.io/apiserver/pkg/admission/plugin/cel

=== RUN   TestFilter
=== RUN   TestFilter/valid_syntax_for_object
--- SKIP: TestFilter/valid_syntax_for_object (0.00s)
=== RUN   TestFilter/valid_syntax_for_metadata
--- SKIP: TestFilter/valid_syntax_for_metadata (0.00s)
=== RUN   TestFilter/valid_syntax_for_oldObject
--- SKIP: TestFilter/valid_syntax_for_oldObject (0.00s)
=== RUN   TestFilter/valid_syntax_for_request
--- SKIP: TestFilter/valid_syntax_for_request (0.00s)
=== RUN   TestFilter/valid_syntax_for_configMap
--- SKIP: TestFilter/valid_syntax_for_configMap (0.00s)
=== RUN   TestFilter/test_failure
--- SKIP: TestFilter/test_failure (0.00s)
=== RUN   TestFilter/test_failure_with_multiple_validations
--- SKIP: TestFilter/test_failure_with_multiple_validations (0.00s)
=== RUN   TestFilter/test_failure_policy_with_multiple_failed_validations
--- SKIP: TestFilter/test_failure_policy_with_multiple_failed_validations (0.00s)
=== RUN   TestFilter/test_Object_null_in_delete
--- SKIP: TestFilter/test_Object_null_in_delete (0.00s)
=== RUN   TestFilter/test_runtime_error
--- SKIP: TestFilter/test_runtime_error (0.00s)
=== RUN   TestFilter/test_against_crd_param
--- SKIP: TestFilter/test_against_crd_param (0.00s)
=== RUN   TestFilter/test_compile_failure
--- SKIP: TestFilter/test_compile_failure (0.00s)
=== RUN   TestFilter/test_pod
--- SKIP: TestFilter/test_pod (0.00s)
=== RUN   TestFilter/test_deny_paramKind_without_paramRef
--- SKIP: TestFilter/test_deny_paramKind_without_paramRef (0.00s)
=== RUN   TestFilter/test_allow_paramKind_without_paramRef
--- SKIP: TestFilter/test_allow_paramKind_without_paramRef (0.00s)
=== RUN   TestFilter/test_authorizer_allow_resource_check
--- SKIP: TestFilter/test_authorizer_allow_resource_check (0.00s)
=== RUN   TestFilter/test_authorizer_error_using_fieldSelector_with_1.30_compatibility
--- PASS: TestFilter/test_authorizer_error_using_fieldSelector_with_1.30_compatibility (0.01s)
=== RUN   TestFilter/test_authorizer_allow_resource_check_with_all_fields
--- SKIP: TestFilter/test_authorizer_allow_resource_check_with_all_fields (0.00s)
=== RUN   TestFilter/test_authorizer_allow_resource_check_with_parse_failures
--- SKIP: TestFilter/test_authorizer_allow_resource_check_with_parse_failures (0.00s)
=== RUN   TestFilter/test_authorizer_allow_resource_check_with_all_fields,_without_gate
--- SKIP: TestFilter/test_authorizer_allow_resource_check_with_all_fields,_without_gate (0.00s)
=== RUN   TestFilter/test_authorizer_not_allowed_resource_check_one_incorrect_field
--- SKIP: TestFilter/test_authorizer_not_allowed_resource_check_one_incorrect_field (0.00s)
=== RUN   TestFilter/test_authorizer_reason
--- SKIP: TestFilter/test_authorizer_reason (0.00s)
=== RUN   TestFilter/test_authorizer_error
--- SKIP: TestFilter/test_authorizer_error (0.00s)
=== RUN   TestFilter/test_authorizer_allow_path_check
--- SKIP: TestFilter/test_authorizer_allow_path_check (0.00s)
=== RUN   TestFilter/test_authorizer_decision_is_denied_path_check
--- SKIP: TestFilter/test_authorizer_decision_is_denied_path_check (0.00s)
=== RUN   TestFilter/test_request_resource_authorizer_allow_check
--- SKIP: TestFilter/test_request_resource_authorizer_allow_check (0.00s)
=== RUN   TestFilter/test_subresource_request_resource_authorizer_allow_check
--- SKIP: TestFilter/test_subresource_request_resource_authorizer_allow_check (0.00s)
=== RUN   TestFilter/test_serviceAccount_authorizer_allow_check
--- SKIP: TestFilter/test_serviceAccount_authorizer_allow_check (0.00s)
=== RUN   TestFilter/test_perCallLimit_exceed
--- SKIP: TestFilter/test_perCallLimit_exceed (0.00s)
=== RUN   TestFilter/test_namespaceObject
--- SKIP: TestFilter/test_namespaceObject (0.00s)
--- PASS: TestFilter (0.01s)
PASS
ok      k8s.io/apiserver/pkg/admission/plugin/cel       0.123s
```

**Comment by aojea** [comment]
the e2e-containerd job raises these errors

> staging/src/k8s.io/apiserver/pkg/cel/environment/base.go:203:11: baseEnvs.Clear undefined (type sync.Map has no field or method Clear)
> staging/src/k8s.io/apiserver/pkg/cel/environment/base.go:204:21: baseEnvsWithOption.Clear undefined (type sync.Map has no field or method Clear)

**Comment by aojea** [comment]
I see, most probably that job is using golang 1.22 , Clear was added in 1.23 to sync.Map https://pkg.go.dev/sync#Map.Clear

**Comment by dims** [comment]
```
❯ docker run -it --entrypoint /bin/bash gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240803-cf1183f2db-master
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
root@1259e22c3a53:/workspace# go version
go version go1.22.5 linux/amd64
```

cc @cpanato @xmudrii @saschagrunert kubekins-e2e master has older golang version

**Comment by dims** [comment]
@aojea we need newer image

```
$ docker run -it --entrypoint /bin/bash gcr.io/k8s-staging-test-infra/kubekins-e2e:v20240903-6a352c5344-master
root@94ab3db2061d:/workspace# go version
go version go1.23.0 linux/amd64
```

**Comment by dims** [comment]
merging https://github.com/kubernetes/test-infra/pull/33319 now

**Comment by liggitt** [comment]
weird that that job didn't use .go-version ... might be something to look into

**Comment by BenTheElder** [comment]
> WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

This job seems like a weird choice for the arm nodes.

> weird that that job didn't use .go-version ... might be something to look into

💯 , we should not be depending on the go version in the infra image, that defeats being able to test `.go-version` changes.

**Comment by aojea** [comment]
> @aaron-prindle: changing LGTM is restricted to collaborators

@aaron-prindle you should apply for membership https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Aaaron-prindle+is%3Aclosed

forwarding lgtm

/lgtm

**Comment by liggitt** [comment]
> I guess https://github.com/kubernetes/kubernetes/blob/master/go.mod#L9 should have also bumped to go 1.23 when we updated to go 1.23

Opened https://github.com/kubernetes/kubernetes/pull/127271 for this

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/community/blob/master/community-membership.md#member @aaron-prindle, happy to +1 :-)

**Pull request merged**
