### PR TITLE
Make nodes report their external IP rather than the master's.

### LINKED ISSUE #7412: The external IP field for all nodes on GCE contains the master's IP address (instead of the node address)
When we populate the addresses of the nodes in [nodecontroller.go](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/nodecontroller/nodecontroller.go#L283) we call NodeAddresses, which for the gce provider gets the external IP from the [metadata server](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/gce/gce.go#L417) which as expected puts the IP address of the master into the external IP field. 

The Legacy IP field is still filled in by asking the cloud provider for the instance data, so it contains the public IP of the node. 

/cc @mbforbes

### PR DESCRIPTION
**Pull request by mbforbes**
This fixes #7412.

Please review, but don't merge quite yet (running e2es).

### CODE REVIEW

**Comment by roberthbailey** [comment]
LGTM. 

FYI @bgrant0607 @davidopp this changes the semantics of external IP on GCE (to be correct for the nodes).

**Comment by mbforbes** [comment]
e2e tests pass

**Comment by roberthbailey** [comment]
... and we are still waiting on shippable/travis.

**Comment by mbforbes** [comment]
2+ hours for Travis and waiting? Sheesh...

**Comment by mbforbes** [comment]
ping @roberthbailey: Travis is now OK

**Comment by bgrant0607** [comment]
I'm fine with this. Travis is green.

**Pull request merged**
