### PR TITLE
Make a log line more clear in kuberuntime_manager.go.

### PR DESCRIPTION
**Pull request by Random-Liu**
Make a log in `podSandboxChanged` more clear.

@yujuhong @feiskyer

### CODE REVIEW

**Comment by Random-Liu** [comment]
@k8s-bot kops aws e2e test this

**Comment by feiskyer** [comment]
LGTM

**Comment by feiskyer** [comment]
@k8s-bot kops aws e2e test this

**Comment by Random-Liu** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
