### PR TITLE
MESOS: Update mesos/docker cluster docker images

### PR DESCRIPTION
**Pull request by karlkfi**
This fixes a kernel bug we've been running into on conformance tests.

### CODE REVIEW

**Comment by sttts** [comment]
Lgtm. I guess you did a mesos/docker smoke test.

**Comment by karlkfi** [comment]
I made a smoke test locally before submitting this PR. Let me run one on CI....

**Comment by karlkfi** [comment]
https://teamcity.mesosphere.io/viewQueued.html?itemId=55633&buildTypeId=Oss_KubernetesMesos_e2eTests&tab=buildLog&guest=1

**Comment by karlkfi** [comment]
above build failed. kicked off another to check for flake:

https://teamcity.mesosphere.io/viewQueued.html?itemId=55639&buildTypeId=Oss_KubernetesMesos_e2eTests&tab=buildLog&guest=1

**Comment by karlkfi** [comment]
deployment is still failing on CI. reason unknown.

**Comment by karlkfi** [comment]
rebased, running new test: https://teamcity.mesosphere.io/viewLog.html?buildId=56264&buildTypeId=Oss_KubernetesMesos_e2eTests&tab=buildLog&guest=1

**Comment by karlkfi** [comment]
Smoke test passed.

**Comment by karlkfi** [comment]
Self-merging mesos/docker-only code to fix discrepancy between mesos-master 0.23 and mesos-slave 0.24 (updated by #15367).

**Pull request merged**
