### PR TITLE
Avoid nodes that have `0` cpu and memory capacity.

### LINKED ISSUE #10962: Don't admit pods if node capacity is 0
If the kubelet can't retrieve machine info from cadvisor for some reason (or cadvisor really returns 0 cpu/mem), it reports node capacity as 0. If the scheduler comes across a pod with 0 capacity, it short circuits the fitness check.

In reality getting machine info from cadvisor is really straight forward and there's no reason it should fail, but the scheduler sholdn't assign pods to nodes that have 0 capacity. I suspect this is because we *don't* want the kubelet to start rejecting pods if cadvisor can't figure out capacity.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2010
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L125

### PR DESCRIPTION
**Pull request by vishh**
Fixes #10962

### CODE REVIEW

**Comment by davidopp** [comment]
Why did you remove the comment about adding disk space check?

**Comment by vishh** [comment]
Because disk space check exists elsewhere at that comment is now invalid.

**Comment by davidopp** [comment]
I thought we don't do disk-space scheduling yet, only detecting OOD?

**Comment by vishh** [comment]
Yeah. Kubelet fails feasibility checks if OOD was detected recently. Look [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2244)

**Comment by davidopp** [comment]
LGTM

Sorry, I mis-read the PR and thought the comment you removed was in the scheduler, not kubelet. Now it all makes sense. :-)

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

**Pull request merged**
