### PR TITLE
kube-openapi/cached: bump and adapt to more go-idiomatic caching library

### PR DESCRIPTION
**Pull request by sttts**
Bump of https://github.com/kubernetes/kube-openapi/pull/405.

/kind cleanup

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Comment by Jefftree** [comment]
Caching changes LGTM.

Looks like we also had to bump gengo and pull in some of the defaulting changes.
/cc @alexzielenski

**Comment by apelisse** [comment]
> Looks like we also had to bump gengo and pull in some of the defaulting changes. /cc @alexzielenski

We want to pull these changes. Thanks!

**Comment by sttts** [comment]
Requires https://github.com/kubernetes/kubernetes/pull/120506 to fix the verify job.

**Comment by sttts** [comment]
@apelisse @Jefftree rebased.

**Comment by dims** [comment]
`Files /logs/artifacts/stats-base.txt and /logs/artifacts/stats.txt are identical` is always awesome :)

/approve
/lgtm

**Pull request merged**
