### PR TITLE
Implement groups come from registered versions

### PR DESCRIPTION
**Pull request by ping035627**
Implement groups come from registered versions for "Object" of NewFactory.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30980)

### CODE REVIEW

**Comment by brendandburns** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30980)*

**Comment by brendandburns** [comment]
LGTM.

**Comment by brendandburns** [comment]
@k8s-bot ok to test

**Comment by ping035627** [comment]
@brendandburns The last test failed, and the error seems not because of my changes, so I execute "rebase" to trigger another test. The test passed, but the lgtm is removed by robot, can you give it again? thanks.

**Comment by brendandburns** [comment]
@ping035627 LGTM added.  Next time just wait and I can trigger the re-test for you.

**Comment by ping035627** [comment]
@brendandburns merge test: Jenkins unit/integration failed, can you help me to see what is the reason? thanks very much.

resttest.go:1251: unexpected timeout from result channelfrom junit_36e60a1ad5284f42d9d5d5e0f91128a0f4cf23a0_20160823-224252.xml

**Comment by ping035627** [comment]
@k8s-bot test this issue #31262.

**Comment by brendandburns** [comment]
@k8s-bot test this issue #31262.

**Comment by ping035627** [comment]
@brendandburns Jenkins unit/integration test still failed, need your help, thanks.

(B+++ [0824 18:18:57] "kubectl patch with resourceVersion 213" returns error as expected: Error from server: Operation cannot be fulfilled on pods "valid-pod": the object has been modified; please apply your changes to the latest version and try again

I0824 18:19:03.751133    8434 kubelet.go:2201] skipping pod synchronization - [Failed to start ContainerManager system validation failed - Following Cgroup subsystem not mounted: [memory]]

**Comment by ping035627** [comment]
@brendandburns can you help to see how  to deal  the error? it passed  the test,  but merge test fail ed. should  I  rebase it? thanks.

**Comment by ping035627** [comment]
can you help  to trigger  a  new retest? thanks.

**Comment by brendandburns** [comment]
@k8s-bot unit test this issue: #25363

**Comment by brendandburns** [comment]
@ping035627 unit/integration test failures seem persistent, does this pass on your machine?

**Comment by ping035627** [comment]
@brendandburns sorry, I tried but still not find the reason of the failure, and my client encountered some other problems, so I think the pr pended temporarily. thanks.

**Comment by ping035627** [comment]
The test 41383 and 44706 are successful, the others are failure, I have no idea :(

**Pull request closed without merging**
