### PR TITLE
Add timothysc to test approvers

### PR DESCRIPTION
**Pull request by timothysc**
I've avoided this responsibility and leveraged super-powers, but I should own up and make it more legit.  I've been working on the testing jiggery since epoch.  

/cc @spiffxp @ixdy @fejta

### CODE REVIEW

**Comment by ixdy** [comment]
Should you also be listed under reviewers?

**Comment by timothysc** [comment]
Do I have to ;-)

**Comment by timothysc** [comment]
@ixdy - Done... begrudgingly

**Pull request merged**
