### PR TITLE
Kube proxy refactor internal config

### PR DESCRIPTION
**Pull request by aroradaman**
#### What type of PR is this?
This PR refactors SyncPeriod, MinSyncPeriod, ClusterCIDRs and removes PortRange from the internal config of kube-proxy  adhering to the v1alpha2 version specifications as detailed in https://kep.k8s.io/784.
These commits are cherry-picked from https://github.com/kubernetes/kubernetes/pull/121830
/kind feature

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
The kube-proxy command line flag `--proxy-port-range`, which was previously deprecated and non-functional, has now been removed.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by danwinship** [comment]
/lgtm
/approve

but you need a release note mentioning that `--port-range` (which was previously deprecated, and no longer did anything) is now gone

**Comment by danwinship** [comment]
/retest
(Job history suggests e2e-gce has started flaking and it's not our bug.)

> `` The kube-proxy command line flag `--port-range`, which was previously deprecated and non-functional, has now been removed. ``

oops, looks like that's `--proxy-port-range`

**Comment by aroradaman** [comment]
> oops, looks like that's `--proxy-port-range`

fixed.

**Pull request merged**
