### PR TITLE
example ansible setup repo

### PR DESCRIPTION
**Pull request by eparis**
This is a basic ansible repo that will do a couple of things

1) set up an etcd node
2) set up a master running apiserver, scheduler, controller-manager
3) setup any number of nodes

Hopefully this can be expanded to do things like set up skydns, set up a
private docker repo, set up an overlay network (flannel) etc etc.  But
right now all it does is set up etcd and configure a master and nodes.

### CODE REVIEW

**Comment by eparis** [comment]
@nzwulfin 

Today there exist 2 repos which try to configure kubernetes using ansible.

https://github.com/eparis/kubernetes-ansible
https://github.com/nzwulfin/ansible-atomic

I'd like to see these merged, potentially IN the kubernetes tree.  If @nzwulfin  is not interested, we may want to move forward anyway.

This is a stripped down version of both my repo and ideas from his repo.  It does very very little.  This is not a replacement for the salt-stack cluster setup.  It only does some small portion of those things.

**Comment by vmarmol** [comment]
@eparis any recommended reviewers? :)

**Comment by brendandburns** [comment]
I'm going to say we blind LGTM this, as it is in contrib, and I'm not sure we have anyone who's expert enough in ansible to say anything deep.

A README.md might be nice to help explain how to use it.

**Comment by eparis** [comment]
@jsafrane could also be a reviewer (I believe @nzwulfin is out until next week)

**Comment by jsafrane** [comment]
- I miss some readme on how to use it.
- It's very Fedora specific. This is not bad, it's just not mentioned anywhere. Other distros don't have /etc/kubernetes, they have /etc/default with different option names.
- What is ansible/library/rpm_facts.py good for? All these facts can be acquired using Ansible itself.

**Comment by eparis** [comment]
How do I use ansible to get installed (or running) rpms?  I couldn't find a way other than my own module to collect those facts....

**Comment by jsafrane** [comment]
The same way as you do it in the python module:

    ---
    - shell: rpm -q iptables-service
      register: has_iptables

**Comment by eparis** [comment]
yes, that's what i did do, I just hated having 

when has_iptables.rc == 0

throughout the code when custom facts lets me do

when has_iptables

guess it's just style, i'm not strongly attached.

**Comment by jsafrane** [comment]
I do not have any strong preference either, I just find the extra python module to be overkill here. What about the other facts, like is_atomic? It's not trivial to get, you need 3 tasks to do it and still it's in yaml and not in python.

**Comment by eparis** [comment]
You're probably right, I should move back into the playbook.

**Comment by eparis** [comment]
@jsafrane What do you think of this?

**Comment by jsafrane** [comment]
It looks good to me.

**Comment by nzwulfin** [comment]
@eparis I'm back around now.  I think this is a good place to start some merging, I just need to check internally on the CLA for good corporate citizenship.

**Comment by brendandburns** [comment]
I'm happy to merge this, once the CLA is set.

**Comment by brendandburns** [comment]
erm, forgot it was eparis as the original author...  merging.

**Pull request merged**
