### PR TITLE
cleanup pkg/apis/core/types.go

### PR DESCRIPTION
**Pull request by knightXun**
cleanup pkg/apis/core/types.go

### CODE REVIEW

**Comment by mcrute** [comment]
Thanks for your contribution @knightXun! Would you please add the release notes block from the [template](https://raw.githubusercontent.com/kubernetes/kubernetes/master/.github/PULL_REQUEST_TEMPLATE.md) to the issue description. Since this is just a golint change you can set them to `NONE`

/remove-kind api-change
/ok-to-test

**Comment by mcrute** [comment]
Should be ready to merge... adding @erictune for approval

/assign @erictune

**Comment by knightXun** [comment]
@mcrute thx

**Pull request merged**
