### PR TITLE
[fluentd/elasticsearch] updated fluentd to 1.6.3

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <monotek23@gmail.com>

**What type of PR is this?**

> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
/kind flake

**What this PR does / why we need it**:
* updates fluentd-elasticsearch docker image to fluentd 1.6.3
* updated all fluentd related ruby gems to

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
updates fluentd-elasticsearch docker image to fluentd 1.6.3
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by coffeepac** [comment]
@monotek did you want to use this new image in the pod config?

**Comment by monotek** [comment]
> @monotek did you want to use this new image in the pod config?

yes, added it...

**Review by coffeepac — APPROVED** [review]
/lgtm

**Pull request merged**
