### PR TITLE
Build Kubernetes UI from source.

### PR DESCRIPTION
**Pull request by jackgr**
This PR changes the build scripts and adds a new build container based on npm, so that the web ui assets can be built from source, per [this comment](https://github.com/GoogleCloudPlatform/kubernetes/issues/7122#issuecomment-103621279) from @lavalamp on #7122 .

It does the following:
- Cleans up the npm/gulp based UI build , which had a number of issues.
- Creates a scriptable version of the UI build that doesn't run live reload and wait for changes.
- Separates the build output from source arficats, which were mixed in the original.
- Adds a nodejs container and scripts to run the UI build there, so that it's reproducible.

This PR is independent of the decision to check in generated UI build artifacts. It is not affected one way or the other by their presence or absence. All it does is clean up the UI build. 

cc @bgrant0607, @preillyme, @bcbroussard.

### CODE REVIEW

**Comment by jackgr** [comment]
@lavalamp This PR is broken into bite sized commits, per [your comment](https://github.com/GoogleCloudPlatform/kubernetes/pull/8716#issuecomment-104796526) on #8716 .

**Comment by jackgr** [comment]
Looks like the tool used to pack the ui assets, github.com/jteeuwen/go-bindata, is not installed in the Travis build environment.

**Comment by preillyme** [comment]
@jackgr I'm seeing:
```
$ ./hack/ui/build-www.sh

Detected npm version: 1.4.28.Kubernetes requires npm version 2.7.3 or greater.Please install npm version 2.7.3 or later.

!!! Error in /home/preilly/kubernetes/hack/ui/www.sh:113
  '( kube::www::verify_prereqs; local npmflags; eval "npmflags=(${KUBE_NPMFLAGS:-})"; local -a sources=(); local arg; for arg in "$@";
do
    if [[ "${arg}" == -* ]]; then
        npmflags+=("${arg}");
    else
        sources+=("${arg}");
    fi;
done; if [[ ${#sources[@]} -eq 0 ]]; then
    sources=("${KUBE_BUILD_SOURCES[@]}");
fi; kube::www::build_assets_from_sources )' exited with status 2
Call stack:
  1: /home/preilly/kubernetes/hack/ui/www.sh:113 kube::www::build_assets(...)
  2: ./hack/ui/build-www.sh:27 main(...)
Exiting with status 1
```
but after 
```
$ sudo su -
# wget -qO- https://deb.nodesource.com/setup_0.12 | bash -
# apt-get install nodejs
Setting up nodejs (0.12.4-1nodesource1~trusty1) ...
exit
$ ./hack/ui/build-www.sh
```
it runs as expected.

**Comment by jackgr** [comment]
Yes, that's the expected behavior. That said, looking through the nodejs blog release posts, we can probably ratchet the required version all the way back to 1.2.14 without any changes in behavior. Before that, things were different enough that it's probably not worth the effort.

**Comment by preillyme** [comment]
@jackgr currently with the following:
```
$ git remote -v
jackgr    git@github.com:jackgr/kubernetes.git (fetch)
$ git fetch jackgr
$ git checkout -b ui_build jackgr/ui_build
$ ./hack/ui/build-www.sh
$ ./hack/local-up-cluster.sh
```
Accessing http://127.0.0.1:8080/static/app/#/dashboard/ I see:
```
Content-Length:19
Content-Type:text/plain; charset=utf-8
Date:Mon, 25 May 2015 21:01:21 GMT
404 page not found
```

**Comment by jackgr** [comment]
Found that issue and fixed it, along with another unrelated bug, in 4b58843.

**Comment by preillyme** [comment]
@jackgr why are there commits that aren't yours in this PR?

**Comment by preillyme** [comment]
@jackgr I'm still seeing a broken build as the latest updates. Accessing: http://127.0.0.1:8080/static/app/ yields:
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module kubernetesApp due to:
Error: [$injector:modulerr] Failed to instantiate module kubernetesApp.services due to:
Error: [$injector:unpr] Unknown provider: ENV
```

**Comment by jackgr** [comment]
@preillyme That error is not a build issue. It's a configuration error. It resulted from checking in development.json with "k8sApiServer": "http://127.0.0.1:8001/api/v1beta2", which I was using for testing, instead of "k8sApiServer": "/api/v1beta2", which is what it should be for production. After discussion with @bcbroussard, I've removed development.json and generated-config.js, and added production.json and production.example.json. The generated-config.js is now a build artifact, and doesn't need to be checked in, now. The production.json is used to generate it in production builds using the production build target. The development.json can be created by the developer, as noted in the README.md, by copy/paste from development.example.json, to create local configuration for development and testing with development builds and live reload. If you sync the latest bits, build and hit the apiserver endpoint, you should see the UI, with no issues.

**Comment by preillyme** [comment]
@jackgr: I've done the following:
```
$ git rebase jackgr/ui_build
Current branch ui_build is up to date.
``` and I'm still not seeing the WebUI correctly. I'm I missing a step?

**Comment by preillyme** [comment]
@jackgr I've opened a PR against your branch https://github.com/jackgr/kubernetes/pull/2 to fix the copyright year in boilerplate notice in ```pkg/ui/datafile.go```

**Comment by jackgr** [comment]
@bgrant0607 It's currently set up so that the UI assets (i.e., www/app/*) must be generated before any go builds are run using hack/ui/build-www.sh. However, it would be easy enough to remove the check for the UI assets, and leave them out of the server if they aren't present. You'll get a cluster with no UI if we do that. Either way, the goal was go avoid have the UI assets checked in, and to build them from source, so that if they exist, they're version correct.

**Comment by bgrant0607** [comment]
The main requirement is that someone should be able to git clone our repo, execute hack/build-go.sh, and launch a cluster via kube-up.sh. Any new dependencies should be pulled automatically, and no new commands should be necessary.

**Comment by bgrant0607** [comment]
Assigned to @lavalamp to find someone else to review in detail.

**Comment by bgrant0607** [comment]
823 files were changed. Could you please write a high-level description of what changes this PR makes?

**Comment by jackgr** [comment]
The reason for introducing a new build command is that the UI build depends on npm. If we want the user to be able to build the UI in a container, then we need a container with npm installed. The choice was to add npm to the go build container, or to use a new container based on the stock node install. The decision was to use a new container based on the stock node install, since node versioning and installs are messy. The consequence of this decision is that to build the UI in a container, the user must run the run.sh in build/ui, like so: build/ui/run.sh hack/ui/build-www.sh.

Rather than add the UI build to the go container, an alternative would be to take a less go-centric approach to building the cluster, by providing top level build scripts for local and containerized builds, such as hack/build-local.sh and hack/build-container.sh, that call build-www.sh and then build-go.sh, either outside or inside containers.

**Comment by jackgr** [comment]
Per offline discussion with @lavalamp , the decision is that the UI build will not be required, and that if the user doesn't build the UI, they won't get a UI.

**Comment by preillyme** [comment]
@jackgr before this PR the WebUI is present by default pre-built and ready to roll. This PR should just be abandoned.

**Comment by jackgr** [comment]
After further discussion, it seems the best approach is to have the UI checked in by default, pre-built and ready to run, but to keep the rest of this work, so that the user can get a reproducible build of the UI, and to pick up all of the other bug fixes that went into it.

**Comment by lavalamp** [comment]
Why does this PR remove the dependencies in third_party? We should keep all dependencies checked in. They should *not* be gotten at build time.

**Comment by preillyme** [comment]
@lavalamp I just got done talking to @jackgr he is modifying the PR to not remove the dependancies and keep the defaults. Once it's re-pushed it should just be a small change touching only a small number of files. Give him a little bit longer to update this PR with the new approach and look again.

**Comment by preillyme** [comment]
@bgrant0607 the 823 files changed number will be much lower after the next update to this PR that @jackgr is working on currently. Stay tuned.

**Comment by lavalamp** [comment]
IMO having a stale UI comitted is worse than no ui. If we have built UI checked in, there needs to be a test that ensures it's not stale.

But I would prefer to have no UI checked in-- in general we would like to eventually move to not having generated files checked in.

**Comment by preillyme** [comment]
@lavalamp Correct we're adding a verify script to check that it matches a newly generated version. This should avoid it ever being stale. This can also be made a pre-commit hook much like the doc check that is there currently.

**Comment by lavalamp** [comment]
There's no real need to keep it checked in, is there?

**Comment by jackgr** [comment]
@lavalamp The concern, as I understand it, is that not having it checked in means that an extra step will be required to get it, that most developers will not bother with the extra step, and that therefore most developers will not see the UI.

An alternative to is create make hack/local-up-cluster.sh run both javascript and golang builds, since that is what most developers will run. We could also add a new top level build script, such as build/make-all.sh that builds both the ui and the golang bits, for use in workflows where people typically run hack/build-go.sh.

**Comment by lavalamp** [comment]
> The concern, as I understand it, is that not having it checked in means that an extra step will be required to get it, that most developers will not bother with the extra step, and that therefore most developers will not see the UI.

Yeah, that's not important. No developer needs the UI, except those working on the UI. :)

**Comment by jackgr** [comment]
@lavalamp @bgrant0607 PTAL. This PR now does nothing but make the UI build robust, per the top comment above, which is revised per request from @bgrant0607 to explain what it does. 

The set of files changed is now quite small, and no new build tools are required for the user. If they want to build the UI, they'll need go-bindata, but that's the way it was originally. Nothing has changed in that regard.

The UI build is not part of the Travis or Shippable builds. It is part of the release build, since doing it there seemed appropriate. The other parts of the build are as they were originally. They don't care whether or not the UI is checked in, and they don't care whether or not the UI has been built.

We can make an independent decision regarding whether or not to keep the generated UI build output in the repo. I will submit a new PR that .gitignores the generated UI build output and removes it from the repo, and we can choose to merge it or not, depending on what we decide.

We can also make an independent decision regarding whether or not to have Travis and Shippable build the UI. I will submit a new PR that adds the UI build to the Travis and Shippable builds, and we can choose to merge it or not, depending on what we decide.

cc @preillyme

**Comment by preillyme** [comment]
@lavalamp I respectfully disagree with you that no developer needs the UI besides those working on UI. I think it's a valuable feature of Kubernetes and developers could gain insight from using it along side the CLI commands for example.

**Comment by preillyme** [comment]
:+1: LGTM

**Comment by lavalamp** [comment]
I think this change would be nice to get in, but I'm running low on cycles for this. Who wants to own our build scripts (now that Joe doesn't anymore)? That person should probably review this.

@ixdy? @quinton-hoole? I know you guys love shell ;) ;)

**Comment by jackgr** [comment]
Squashed commits and removed WIP from title.

**Comment by thockin** [comment]
This volume of new shell code so close to release - do we really have to do this?

**Comment by bgrant0607** [comment]
To rephrase @thockin's question: What are the consequences of not doing this now? We're out of time.

**Comment by jackgr** [comment]
We're going to break this PR up into smaller pieces that are easier to review and carry less risk.

**Pull request closed without merging**
