### PR TITLE
Errorf format %q has arg b.labelSelector of wrong type *string

### PR DESCRIPTION
**Pull request by wgliang**
**What this PR does / why we need it**:
/kind bug

Errorf format %q has arg b.labelSelector of wrong type *string

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wgliang** [comment]
/cc @liggitt @deads2k @liggitt @janetkuo
PTAL,thanks.

**Review by janetkuo — APPROVED** [review]

**Pull request merged**
