### PR TITLE
Add ControllerOptions field to IngressBackend API.

### PR DESCRIPTION
**Pull request by matthewg**
This will be used to allow configuring controller-specific parameters,
e.g. kubernetes/ingress#421 .

```release-note
Add ControllerOptions field to IngressBackend API.
```

**What this PR does / why we need it**: Allows taking advantage of controller-specific functionality when exposing a service through an ingress. See kubernetes/ingress#421 for an example of a feature that one might want to enable in this way. 

**Special notes for your reviewer**: My intent here is that each ingress controller will document what can go in this field when using that controller. For the GCE controller, what I had in mind was a set of keypaths that would correspond 1:1 with fields in the GCE BackendService resource, e.g. {"iap.enabled": "true", ...}

**Release note**:
```release-note
Add ControllerOptions field to IngressBackend API.

When the corresponding ingress change goes in, this will allow services exposed through an ingress to take advantage of controller-specific functionality. Details will be added to the ingress documentation.
```

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by matthewg** [comment]
Happy to fix the test failures, but first I'd like to get some feedback on the approach. If there are better ways to expose controller-specific configuration, I'm happy to go a different direction.

**Comment by nicksardo** [comment]
@aledbf @justinsb @philips @thockin @kubernetes/sig-network-api-reviews  Would this be worth adding to the next sig-network meeting agenda?

@matthewg, thanks for taking the initiative on this. I agree that we need to have an answer to this controller-specific problem. However, this is just one of the problems with ingress. There have been a few proposals ([Better Ingress](https://docs.google.com/document/d/1ILXnyU5D5TbVRwmoPnC__YMO9T5lmiA_UiU8HtgSLYk/edit#), [Composite Service](https://docs.google.com/document/d/1QWdGbrzRHRQDniHpeTqlw2v-lNeWPp-HfCPONDti0ww/edit#)) calling for ingress or a new service resource to route traffic internally. I'm wondering if this proposal would complicate those initiatives.

The StorageClass resource has provisioner-specific parameters with a [provisioner name](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/storage/v1/types.go#L39). Perhaps they have a pattern that ingress should also follow. Thoughts from other ingress folks?

**Comment by thockin** [comment]
wrt storage, if we pursue any sort of opaque options, we should follow the
same pattern.  I agree with Nick - there are some large decisions to make
wrt Ingress evolution.

**Comment by matthewg** [comment]
To solve the immediate problem for people using Ingress today, maybe an annotation would be a better way to go? Something like https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/customization/cafe-ingress-with-annotations.yaml .  Then the only code that would need to change would be in the GCE controller.

**Comment by justinsb** [comment]
Here is what happens in cloudprovider land:

* We begin with a specific annotation; we do this a lot for example when something is AWS specific.
* When we observe that multiple clouds have the same concept and we define a field.  Fields have big advantages over annotations (we have mechanisms for versioning them, most notably).  Anyone using a schema-aware editor gets autocompletion etc.  The cloudproviders that do support this go through a helper method so they read the field-or-annotation, and the ones that don't will typically raise an "unsupported" style error.

Applying the analogy here, the controller options is probably the equivalent of annotations; I don't see a particular advantage over annotations.

I would suggest though that if we can define a field, we should do so.  This doesn't even feel particularly GCE specific; I think nginx or traefik could probably implement it also?  And have you seen the existing ingress oauth support? https://github.com/kubernetes/ingress/blob/master/examples/external-auth/nginx/README.md

**Comment by nicksardo** [comment]
https://github.com/kubernetes/ingress/issues/243#issuecomment-307519815

**Comment by matthewg** [comment]
Ah, thanks for the pointer, that looks like it'll solve my problem. I'll withdraw this PR.

**Pull request closed without merging**
