### PR TITLE
Switch to m3.medium for e2e testing

### PR DESCRIPTION
**Pull request by brendandburns**
@spxtr @justinsb

### CODE REVIEW

**Comment by justinsb** [comment]
LGTM.  Are you trying to verify that we aren't running amok with memory?

**Comment by justinsb** [comment]
@brendandburns happy to tag this with LGTM, but can I ignore the "failing" unit tests?  It doesn't look like any really failed...

(Also, is this because we want to stress the memory a bit?)

**Comment by brendandburns** [comment]
@justinsb this is actually pure cost savings on my part ;)

@k8s-bot unit test this please

**Comment by justinsb** [comment]
@k8s-bot unit test this

**Pull request merged**
