### PR TITLE
kubectl: Add documentation to delete.go

### PR DESCRIPTION
**Pull request by tcharding**
**What this PR does / why we need it**:

`golint` emits numerous warnings:

`delete.go: exported XXX should have a comment...`

Add documentation to exported functions, types, and constants.

**Release note**:

```release-note
NONE
```

/sig cli
/kind cleanup

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
The code SGTM. But I'm not sure if it's worthy fixing such lint errors. There will be tons of lint errors to fix if we remove the package list in `hack/.golint_failures`.

cc @thockin @smarterclayton @liggitt

**Comment by tcharding** [comment]
@xiangpengzhao, I appreciate your comment. If it's a matter of developer cycles to do the work, I have PR's open removing lint warnings from most of `pkg/kubectl` excluding `pkg/kubectl/cmd`. And I am happy to keep working on it until all `lint` warnings are gone from `pkg/kubectl/*`.

If it's a matter of maintainer resources for review and merge then of course I'll follow whatever project members say.

If it's a 'design choice' I have to disagree with you. I think that having *most* of `pkg/kubectl` excluded from linting is a bad thing.

thanks

**Comment by xiangpengzhao** [comment]
@tcharding Thanks for cleanup! I also notice your other contributions on removing lint warnings. I personally like these PRs. I will let other guys I cc'ed to confirm how to do next.

**Comment by tcharding** [comment]
@xiangpengzhao thanks

**Comment by tcharding** [comment]
Closing multiple `golint` PR's and reopening a single combined PR. Requested by soltysh.

**Pull request closed without merging**
