### PR TITLE
leaderelection: execute the OnStopedLeading only if have been the leader

### LINKED ISSUE #1187: client-go LeaderElector will execute the OnStoppedLeading callback even if it is not a leader
https://github.com/kubernetes/client-go/blob/1ac8d459351e21458fd1041f41e43403eadcbdba/tools/leaderelection/leaderelection.go#L197-L213

`OnStopedLeading` and `OnStopedElecting` are different, should we move the call of `OnStopedLeading` back?

```
	if !le.acquire(ctx) {
		return // ctx signalled done
	}
        defer func() {
		le.config.Callbacks.OnStoppedLeading()
	}()
```

### PR DESCRIPTION
**Pull request by believening**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/client-go/issues/1187

#### Special notes for your reviewer:

@wojtek-t @deads2k 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
I don't know if, despite the name, people is relying on this behavior on their controller, changing it will break these people

**Comment by believening** [comment]
> I don't know if, despite the name, people is relying on this behavior on their controller, changing it will break these people

If someone handles `OnStopedElecting` based on the current behavior, this does affect them.

When using client-go election, my scenario expects `onStoppedLeading`, but it is not, a bit confusing, so I pushed this.

**Comment by aojea** [comment]
> When using client-go election, my scenario expects `onStoppedLeading`, but it is not, a bit confusing, so I pushed this.

yeah, that is why I mentioned that maybe the name is confusing, @liggitt @deads2k do you have more historical context here?

**Comment by liggitt** [comment]
I don't know the history, but it looks like all our uses of OnStoppedLeading expect to handle both the "led, then stopped leading" and "never acquired leader" cases.

I agree the name is confusing if it is called in both of those cases, but just moving this does change behavior of consumers in ways we don't really want (it doesn't give them a StoppedTryingToLead handling path)

**Comment by wojtek-t** [comment]
> I agree the name is confusing if it is called in both of those cases, but just moving this does change behavior of consumers in ways we don't really want (it doesn't give them a StoppedTryingToLead handling path)

What if we would rename it? Or we don't want to do even that given it's public interface?
[OTOH, clarifying the behavior by more explicit name could help users to achieve what they want to achieve.]

**Comment by aojea** [comment]
@believening can you update the documentation to reflect the actual behavior ?

**Comment by aojea** [comment]
that sgtm,

**Pull request closed without merging**
