### PR TITLE
Remove hardcode for blocksize, use stat(), fixes test failure on SLES

### LINKED ISSUE #44022: TestMetricsDuGetCapacity unit test fails on SLES 12 Go 1.8 ppc64le on master branch
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
TestMetricsDuGetCapacity
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
master branch (tip)

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
SLES 12
- **Kernel** (e.g. `uname -a`):
Linux pts00449-vm23 3.12.28-4-default #1 SMP Thu Sep 25 17:02:34 UTC 2014 (9879bd4) ppc64le ppc64le ppc64le GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
make test WHAT="./pkg/volume"
Running tests for APIVersion: v1,apps/v1beta1,authentication.k8s.io/v1,authentication.k8s.io/v1beta1,authorization.k8s.io/v1,authorization.k8s.io/v1beta1,autoscaling/v1,autoscaling/v2alpha1,batch/v1,batch/v2alpha1,certificates.k8s.io/v1beta1,extensions/v1beta1,imagepolicy.k8s.io/v1alpha1,policy/v1beta1,rbac.authorization.k8s.io/v1beta1,rbac.authorization.k8s.io/v1alpha1,settings.k8s.io/v1alpha1,storage.k8s.io/v1beta1,storage.k8s.io/v1,federation/v1beta1
+++ [0404 11:22:46] Running tests without code coverage
--- FAIL: TestMetricsDuGetCapacity (0.01s)
        metrics_du_test.go:73: Unexpected Used for directory with file.  Expected 4096, got 65536.
FAIL
FAIL    k8s.io/kubernetes/pkg/volume    0.137s
Makefile:164: recipe for target 'test' failed
make: *** [test] Error 1

Test case failed
**What you expected to happen**:
Test case should pass

**How to reproduce it** (as minimally and precisely as possible):
make test WHAT="./pkg/volume"

**Anything else we need to know**:
Found this similar issue: https://github.com/kubernetes/kubernetes/issues/20028
However the values returned are different, see this string "Expected 4096, got 65536"

### PR DESCRIPTION
**Pull request by vaibhavsood**
**What this PR does / why we need it**:
Removes hardcoding for blocksize, fixes test failure on SLES
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #44022

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by abdasgupta** [comment]
Hi Vaibhav, please sign the CLA as well as this seems to be your first contribution here.

**Comment by vaibhavsood** [comment]
I have linked my github email with the corporate CLA (i am member of the CNCF contributors group)..

**Comment by brendandburns** [comment]
@k8s-bot ok to test
/approve

**Comment by brendandburns** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

/lgtm

**Comment by vaibhavsood** [comment]
Hi, wanted to check if this PR can be merged, not sure if i need to do something from my end (cant figure out the reason for the failing bot tests..), thanks!

**Pull request merged**
