### PR TITLE
Write log if two replication controller overlap

### PR DESCRIPTION
**Pull request by mqliang**
This PR write log if two replication controller overlap, just as DeamonSetController and JobController do

### CODE REVIEW

**Comment by mqliang** [comment]
My PR semss has no side effect, is there anyone willing to help to point out why the `Shippable` test failed?

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by mqliang** [comment]
Oh, I mess things up. I submitted my PR a few days ago，but the `Shippable` failed, then I read the test results and see some strange error messages which does not seem to be caused by my PR. So I think may be I need rebase my branch.I am so sorry.

So, does the 'Shippable' test matter? Did I need close my PR and resubmit?

**Comment by wojtek-t** [comment]
Shippable was a flake. I think this should pass now.

BTW - it seems to be fixed now.

**Comment by mqliang** [comment]
I am so sorry, I have rolled back my operation. 

Do you mean if `Shippable` or `Jenkins GCE e2e ` failed, but obviously not caused by my PR, just let it be?

**Comment by wojtek-t** [comment]
@mqliang - yes you can ignore those failures.

**Comment by a-robinson** [comment]
@mqliang - it looks like you did a merge of master into your branch instead of a rebase of your branch on top of master. Can you please revert your merge commit and do a rebase instead? You can do a rebase by running `git rebase origin/master` from your branch, assuming you've set up origin to point to the main repository.

**Comment by a-robinson** [comment]
Removing lgtm label until the merge commit is gone so that the merge bot doesn't automatically merge it in the meantime.

**Comment by a-robinson** [comment]
Thanks @mqliang!

**Comment by a-robinson** [comment]
@k8s-bot ok to test

**Pull request merged**
