### PR TITLE
Mark Job onPodConditions as optional in pod failure policy

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug
/kind api-change

#### What this PR does / why we need it:

To make onPodConditions optional, to align it with the intention reflected in the comment:
`One of onExitCodes and onPodConditions, but not both, can be used in each rule.`. Also, to align the annotations with the validation code: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/batch/validation/validation.go#L324-L329

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Mark the onPodConditions field as optional in Job's pod failure policy.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3329-retriable-and-non-retriable-failures
```

### CODE REVIEW

**Comment by mimowo** [comment]
/sig apps
/assign @alculquicondor 
FYI @danielvegamyhre

**Review by kannon92 — COMMENTED** [review]
/lgtm

**Comment by alculquicondor** [comment]
Please cherry-pick to the first version to release as beta.

**Comment by liggitt** [comment]
/lgtm
/approve

please pick back to previous releases that include the field

**Comment by erikgb** [comment]
Thanks!

/lgtm

**Pull request merged**
