### PR TITLE
Fix Sidecar PR

### PR DESCRIPTION
**Pull request by satnam6502**
Take 2 at #8542

### CODE REVIEW

**Comment by satnam6502** [comment]
@a-robinson @filbranden

**Comment by satnam6502** [comment]
I am who I am.

**Comment by a-robinson** [comment]
LGTM. I assume you'll delete the bad branch?

**Comment by satnam6502** [comment]
Sure. Why are there two commits in this PR?

**Comment by satnam6502** [comment]
Bad branch deleted.

**Pull request merged**
