### PR TITLE
update features to indicate beta in comment

### PR DESCRIPTION
**Pull request by deads2k**
Fixing comments on our featuregates to match reality and cleaning up a dead field I found going through.

/kind cleanup
/priority important-long-term
@kubernetes/sig-api-machinery-pr-reviews 

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
```
Some packages in hack/.staticcheck_failures are passing staticcheck. Please remove them.

  vendor/k8s.io/apiserver/pkg/server
```

lgtm otherwise

**Comment by deads2k** [comment]
> ```
> Some packages in hack/.staticcheck_failures are passing staticcheck. Please remove them.
> 
>   vendor/k8s.io/apiserver/pkg/server
> ```
> 
> 
> lgtm otherwise

no good deed.  Fixed.

**Pull request merged**
