### PR TITLE
Remove ARM archs from base images list of sample-apiserver

### PR DESCRIPTION
**Pull request by chendave**
`kube-cross` currently doesn't work on ARM archs, keep it in the
list will break e2e test for ARM platforms, we can add it back when
the image is ready for non-amd64 platforms.

see: https://github.com/kubernetes/kubernetes/issues/75114

Signed-off-by: Dave Chen <dave.chen@arm.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind failing-test

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
cc @cheftako @dims

**Comment by dims** [comment]
@chendave counter proposal :) Would you be able to help with resurrecting https://github.com/kubernetes/kubernetes/pull/75058 to enable kube-cross to work?

**Comment by chendave** [comment]
@dims , thanks for pointing me to the link, reopen your PR there or pick your changes and continue the work here, which one do you prefer to?

**Comment by dims** [comment]
@chendave please pick up my changes into a new PR. thanks for taking this on!

**Comment by chendave** [comment]
I have been looking at this for an while, build a multi-arch images of kube-cross for other platforms is attractive though, and this patch https://github.com/kubernetes/kubernetes/pull/75058 stands in a good shape and just need some tweaks to make the script to escape "Darwin" for example.

But my feeling is that it's not necessary to do this, "kube-cross" image as what's the name says, it's used for cross-building the go source code for the foreign archs, but what we have right now is that qemu emulation or "qemu-user-static" binary doesn't supported well on the platform other than `x84_64`,  not talking there are lots of packages missing on a non-amd platforms, see example below,

```bash
# uname -m
aarch64

# apt-cache install crossbuild-essential-arm64
The following packages have unmet dependencies:
 crossbuild-essential-arm64 : Depends: gcc-aarch64-linux-gnu (>= 7.2) but it is not installable
                              Depends: g++-aarch64-linux-gnu (>= 7.2) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

We might be able to build such an image "kube-cross-arm64" for example on x84_64 platform, but what's the use-case of the image, the image could only support to run the native binary,      so why we need this image?

```bash
# uname -m
aarch64
# docker run --rm --privileged multiarch/qemu-user-static:register --resetstandard_init_linux.go:211: exec user process caused "no such file or directory"

# docker run --rm i386/alpine
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

**Comment by chendave** [comment]
cc @BenTheElder @mkumatag @dims @cblecker

**Comment by chendave** [comment]
> We might be able to build such an image "kube-cross-arm64" for example on x84_64 platform, but what's the use-case of the image, the image could only support to run the native binary, so why we need this image?
> 
If all the use-case is for build only instead of run those binary, still worth to have a try.

**Pull request closed without merging**
