### PR TITLE
rkt: Refactoring setIsolators, add unit tests

### PR DESCRIPTION
**Pull request by yifan-gu**
Replace manually creating isolators with isolator constructors.
Also add support for supplementary group IDs.

cc @jonboulle @yujuhong @Random-Liu

### CODE REVIEW

**Comment by yujuhong** [comment]
LGTM

**Comment by yifan-gu** [comment]
@k8s-bot test this please

**Comment by jonboulle** [comment]
LGTM

**Comment by yifan-gu** [comment]
Attach LGTM tag based on @yujuhong and @jonboulle 's review.

**Comment by yifan-gu** [comment]
@k8s-bot test this please

**Comment by yifan-gu** [comment]
@k8s-bot unit test this please

**Pull request merged**
