### PR TITLE
Fix race condition of kubectl logs

### LINKED ISSUE #47165: race condition of kubectl logs
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
community master

**Environment**: ubuntu
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
Run this command twice at the same time to get container logs:
curl -k -v "http://localhost:8080/api/v1/namespaces/default/pods/counter/log?container=count-log-2&follow=true&tailLines=2"
One of them may fail.
**What you expected to happen**:
The two command may succeed both.

### PR DESCRIPTION
**Pull request by CaoShuFeng**
Fixes #47165

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by CaoShuFeng** [comment]
@timstclair ping for approve and milestone.

**Comment by CaoShuFeng** [comment]
@sig-node-reviewers

**Comment by CaoShuFeng** [comment]
@vishh @sig-node-reviewers
ping for approve and milestone.

**Comment by CaoShuFeng** [comment]
This fixed by https://github.com/kubernetes/kubernetes/pull/50381

**Pull request closed without merging**
