### PR TITLE
remove unused integration test case for openshift

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
remove useless openshift integration test. 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
As far as I see, `EnableMetrics` is still unused by kube and therefore the test makes sense.

**Comment by hzxuzhonghu** [comment]
>EnableMetrics is still unused by kube 

I can not catch up with you by this.

**Comment by sttts** [comment]
> I can not catch up with you by this.

`EnableMetrics` is not referenced in a meaningful way in kube, but used in OpenShift downstream. So we added that test to keep a reference around.

**Pull request closed without merging**
