### PR TITLE
eliminate duplicated codes in estimateContainer method

### PR DESCRIPTION
**Pull request by bruceauyeung**
**What this PR does / why we need it**:
there are two code snippets about when to estimate resource for cpu and mem are duplicated, i extracted them into method `getEstimationIfNeeded` method

Signed-off-by: bruceauyeung <ouyang.qinhua@zte.com.cn>

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37667)

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by derekwaynecarr** [comment]
@k8s-bot test this

**Pull request merged**
