### PR TITLE
Fix typos: ie should be i.e.

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
ie should be i.e.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
@sttts  PTAL

**Comment by zhangxiaoyu-zidif** [comment]
@k82cn PTAL

**Comment by apelisse** [comment]
@k8s-bot ok to test
/lgtm

**Comment by apelisse** [comment]
@k8s-bot verify test this

**Comment by apelisse** [comment]
This is very weird. Can you please rebase that code see if it fixes the issue?

**Comment by zhangxiaoyu-zidif** [comment]
@apelisse rebase that code already.

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-merge-robot 
weird test.

**Comment by apelisse** [comment]
@k8s-bot non-cri node e2e test this
@k8s-bot verify test this

**Comment by k82cn** [comment]
please run `./hack/update-staging-client-go.sh` :).

**Comment by zhangxiaoyu-zidif** [comment]
@k82cn should I rebase it and run that script?

**Comment by k82cn** [comment]
no rebase, just run script in the branch and `git --amend -a` && `git push --force`

**Comment by zhangxiaoyu-zidif** [comment]
@k82cn Thanks. I try it but failed due to godeps. I will try to fix it as soon as possible. =)

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot verify test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot verify test this

**Comment by deads2k** [comment]
You have several typo pulls:

 1. https://github.com/kubernetes/kubernetes/pull/43904
 1. https://github.com/kubernetes/kubernetes/pull/44708
 1. https://github.com/kubernetes/kubernetes/pull/45327
 1. https://github.com/kubernetes/kubernetes/pull/45395
 1. https://github.com/kubernetes/kubernetes/pull/45592

Can you please combine them into a single pull?

**Comment by zhangxiaoyu-zidif** [comment]
@deads2k 
#43904 : I can't solve the test failed. I don't know why.
#44708: I miss cla label. But I signed it.
#45327 : This only one can be gathered.
#45395:  I can't solve the test failed. I don't know why.
#45592: The latest one I pull request.
In fact, that's all.

**Comment by zhangxiaoyu-zidif** [comment]
I can't solve the test failed. So I closed it.

**Pull request closed without merging**
