### PR TITLE
fix typos in kubelet package

### PR DESCRIPTION
**Pull request by mojh7**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

fix typos in kubelet package by referring to `codespell pkg/kubelet/.`

[codespell](https://github.com/codespell-project/codespell)

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

Thank you for reviewing this PR.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bart0sh** [comment]
@mojh7 Thank you for your PR. It seems to only contain trivial edits. Please
read [our trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits).

**Comment by bart0sh** [comment]
@mojh7 If you're going to continue with this, I'd suggest to use a spellchecker for pkg/kubelet as a start. I believe it will find more than one spelling error and that would be much better to put all fixes in one PR than creating a new PR for every fix.

Here is an example of spellchecking pkg/kubelet with [codespell](https://github.com/codespell-project/codespell):
```
$ codespell pkg/kubelet/
pkg/kubelet/kubelet_pods.go:1801: supercedes ==> supersedes
pkg/kubelet/pod_workers.go:243: lifecyle ==> lifecycle
pkg/kubelet/pod_workers_test.go:1356: shoud ==> should
pkg/kubelet/apis/config/types.go:517: setttings ==> settings
pkg/kubelet/prober/common_test.go:84: overwridden ==> overridden, overwritten
pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1610: upto ==> up to
pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1836: upto ==> up to
pkg/kubelet/kuberuntime/kuberuntime_manager.go:566: supercedes ==> supersedes
pkg/kubelet/kuberuntime/kuberuntime_manager.go:566: resrouces ==> resources
pkg/kubelet/kuberuntime/kuberuntime_manager.go:1159: everytime ==> every time
pkg/kubelet/kuberuntime/kuberuntime_sandbox.go:318: unparseable ==> unparsable
pkg/kubelet/kuberuntime/kuberuntime_sandbox.go:327: unparseable ==> unparsable
pkg/kubelet/kuberuntime/kuberuntime_container.go:675: followings ==> following
pkg/kubelet/eviction/helpers_test.go:1284: didnt ==> didn't
pkg/kubelet/eviction/eviction_manager_test.go:1100: bellow ==> below
pkg/kubelet/token/token_manager_test.go:517: everthing ==> everything
pkg/kubelet/token/token_manager_test.go:557: everthing ==> everything
pkg/kubelet/cm/cgroup_manager_linux.go:62: Forbit ==> Forbid
pkg/kubelet/cm/memorymanager/memory_manager.go:428: covert ==> convert
pkg/kubelet/cm/cpumanager/cpu_assignment.go:286: paramater ==> parameter
pkg/kubelet/cm/cpumanager/policy_static.go:663: satify ==> satisfy
pkg/kubelet/cm/cpumanager/cpu_manager.go:458: incase ==> in case
pkg/kubelet/cm/cpumanager/policy_options.go:70: synonim ==> synonym
pkg/kubelet/cm/devicemanager/manager.go:237: upto ==> up to
pkg/kubelet/cm/dra/cdi.go:116: charcter ==> character
pkg/kubelet/stats/pidlimit/pidlimit_linux.go:39: mininum ==> minimum
pkg/kubelet/container/helpers.go:47: informations ==> information
pkg/kubelet/types/pod_update_test.go:329: Preemptable ==> Preemptible
pkg/kubelet/types/pod_update.go:172: Preemptable ==> Preemptible
pkg/kubelet/types/pod_update.go:174: Preemptable ==> Preemptible
pkg/kubelet/cri/remote/fake/endpoint.go:33: fo ==> of, for
pkg/kubelet/winstats/version.go:83: upto ==> up to
pkg/kubelet/userns/userns_manager_test.go:64: anyting ==> anything
pkg/kubelet/preemption/preemption.go:249: Preemptable ==> Preemptible
```
It's just an example and I wouldn't suggest to take it as it is, but it would be a good start to look at the spellchecker output  and filter out false positives.

**Comment by mojh7** [comment]
@bart0sh Thank you for your advice :)

As you suggested, i've fixed typos by referring to `codespell pkg/kubelet/`.

Additionally, I've found the same typos in other packages using `git grep -E "setttings|Forbit|paramater|synonim|terminoloy|satify|Affinties|charcter|covert|flase|unusued|bellow|diasbled|supercedes|actural|resrouces|shoud|mininum|everthing|anyting"`

**Comment by bart0sh** [comment]
@mojh7 
> Additionally, I've found the same typos in other packages

Please, 
- avoid changing vendor/
- update PR title and description
- try not to make this PR too big unless you want to wait approvals from a lot of sigs and rebase it too often

**Comment by mojh7** [comment]
@bart0sh Thanks for helping me write a better PR !! :)

Considering your comment, I changed to fix typo in kubelet package only.

**Comment by bart0sh** [comment]
@mojh7 please, rebase

**Comment by pacoxu** [comment]
The current verification is using `github.com/client9/misspell` v0.3.4
- https://github.com/kubernetes/kubernetes/blob/af99df6a6bead927d61746dc431fc1b526af55a0/hack/verify-spelling.sh

**Comment by dims** [comment]
thanks for the guidance provided in this PR @bart0sh appreciate it!

/approve

(i feel comfortable landing this as it is just spelling changes focused under one directory!)

**Review by mrunalp — APPROVED** [review]

**Pull request closed without merging**
