### PR TITLE
Validate the mounts of secret volumes are readOnly

### PR DESCRIPTION
**Pull request by pmorie**
@thockin @erictune 

@liggitt @deads2k FYI

### CODE REVIEW

**Comment by thockin** [comment]
Why not add a method to the volume.Volume that was something like `OverrideReadOnly(volumeMount.ReadOnly)`, for which the simplest implementation is to return the input, but Secret can always return `true`, and PD can change it to `true` if the underlying PD is read-only.  This could expand in the future to OverrideMountOptions() or something

You could even make it less intrusive, by making it an optional method, making a new interface:

```
type MountOverrider interface {
    OverrideReadOnly(input bool) bool
}
```

and then kubelet could try to cast to MountOverrider when building mount options.

Net result: don't throw an error, just do the right thing.

**Comment by pmorie** [comment]
@thockin I had considered something similar, I'll sleep on it

**Comment by pmorie** [comment]
@thockin Hrm.  I'm not sure I like the idea of silently overriding the behavior described by the API.   Ideally, there would be a way to default this so that it would be reflected in the object's state in the API server.  I'm going to keep thinking about it; might close this one out.

**Comment by thockin** [comment]
Think it of t this way - a PD that is attached read-only will be read-only
for all mounts regardless of their own read-only flag.  Secret is no
different in semantic, just implementation.

**Comment by pmorie** [comment]
@thockin Still thinking about it, been distracted w/ some personal stuff this week.

**Comment by pmorie** [comment]
@thockin I'm fine w/ making secrets always read only instead of adding this validation.  Will close and make another PR.

**Pull request closed without merging**
