### PR TITLE
cmd/kubeadm: add neolit123 as reviewer

### PR DESCRIPTION
**Pull request by neolit123**
/release-note-none
/kind cleanup
/assign @timothysc 
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews 

criteria:
- [x] member for at least 3 months
- [x] primary reviewer for at least 5 PRs
- [x] reviewed or merged at least 20 PRs

created PRs i k/k:
https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aneolit123+archived%3Afalse+is%3Amerged+repo%3Akubernetes%2Fkubernetes+

assigned / reviewed PRs in k/k:
https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+archived%3Afalse+is%3Amerged+repo%3Akubernetes%2Fkubernetes+commenter%3Aneolit123+in%3Acomment+assignee%3Aneolit123

### CODE REVIEW

**Comment by chuckha** [comment]
strong 👍 to this!

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Pull request merged**
