### PR TITLE
disable irc notifications for shippable and travis

### PR DESCRIPTION
**Pull request by mikedanese**
They are pretty spammy. If no objections, I'd like to get rid of them. We would still have kubot notifications.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
+1

**Comment by mikedanese** [comment]
I say we just merge this and people can readd it if they notice and don't like it :)

**Comment by nikhiljindal** [comment]
SGTM.

ccing @thockin @lavalamp incase they disagree.
also @vishh the current oncall as fyi.

**Comment by lavalamp** [comment]
Could we make the notifications only fire when head starts failing/is fixed? I agree it's not useful for every random PR.

**Comment by vishh** [comment]
Can we instead have a separate IRC channel and redirect all the bot messages to that channel?

**Comment by vishh** [comment]
Posting on failures also sounds like a good alternative.

**Comment by thockin** [comment]
Can we post only on error?

**Comment by mikedanese** [comment]
for shippable on_success and on_failure are not yet confiurable: http://docs.shippable.com/yml_reference/#irc-notifications

travis doesn't do much but I reenable notifications when we change to failing.

**Comment by vishh** [comment]
Shippable notifications are the ones we care about as of now. I would recommend not getting rid of it since it helps catch PRs that breaks HEAD quickly.

**Comment by mikedanese** [comment]
Also a number of people enable shippable/travis to build there local changes and #google-containers gets notifications from forked repos as well. It's not great signal for me and seems spammy in a channel that is used pretty much only for support. If other people get good signal from it then we should leave it but I think we should consider moving ci build notifications into a dev-notification channel.

**Comment by thockin** [comment]
Why not report to a different channel and tell oncall to sit on both?

**Comment by lavalamp** [comment]
Yeah, reporting to a different channel seems good.

**Comment by mikedanese** [comment]
Ok moving all ci notifications to #kubernetes-dev

**Comment by thockin** [comment]
SGTM

**Comment by vishh** [comment]
+1 for moving to #kubernetes-dev

**Comment by vishh** [comment]
We should update the wiki to reflect this change.

**Pull request merged**
