### PR TITLE
Automated cherry pick of #15158 upstream release 1.1

### LINKED ISSUE #15118: Flocker Volume Plugin: TestSetUpAtInternal flaky
@mattmoor reports the following failure after syncing with latest code:

--- FAIL: TestSetUpAtInternal (0.00s)
        Error Trace:    plugin_test.go:208
	Error:		Not equal: "expected-to-be-set-properly" (expected)
			        != "" (actual)
		
FAIL
FAIL	k8s.io/kubernetes/pkg/volume/flocker	0.067s

cc/ @saad-ali

### LINKED ISSUE #15212: Failing flocker unit tests
Unit tests on our CI have apparently been failing for 2 weeks and no one noticed (oops!)...

The PR that seems to have caused the failures is #14328.

The failing test is `k8s.io/kubernetes/pkg/volume/flocker` - `TestSetUpAtInternal`.

```
[16:15:04][Step 4/5] --- FAIL: TestSetUpAtInternal (0.00s)
[16:15:04][Step 4/5] 	assertions.go:202: 
[16:15:04][Step 4/5]                         
[16:15:04][Step 4/5] 	Error Trace:	plugin_test.go:208
[16:15:04][Step 4/5] 		
[16:15:04][Step 4/5] 	Error:		Not equal: "expected-to-be-set-properly" (expected)
[16:15:04][Step 4/5] 			        != "" (actual)
[16:15:04][Step 4/5] 		
[16:15:04][Step 4/5] FAIL
[16:15:04][Step 4/5] FAIL	k8s.io/kubernetes/pkg/volume/flocker	0.014s
```

Full Test Log: https://teamcity.mesosphere.io/viewLog.html?buildId=54217&buildTypeId=Oss_KubernetesMesos_2UnitTests&tab=buildLog&guest=1#_focus=866

I'm not sure why this is failing on our CI and not on shippable. Has anyone else seen something similar? 

**That test only seems to fail on the second run through with `etcdPrefix: kubernetes.io/registry`.**

Our unit tests run in a container built specifically for testing k8s-mesos:

```
$ cluster/mesos/docker/test/build.sh
$ docker run --rm \
  -v "$(pwd):/go/src/github.com/GoogleCloudPlatform/kubernetes" \
  -v "/var/run/docker.sock:/var/run/docker.sock" \
  mesosphere/kubernetes-mesos-test \
  -cexu "\
    cd /go/src/github.com/GoogleCloudPlatform/kubernetes && \
    make clean && \
    export KUBERNETES_CONTRIB=mesos && \
    make test
  "
```

The Dockerfile for the env: https://github.com/kubernetes/kubernetes/blob/master/cluster/mesos/docker/test/Dockerfile

Is anyone else able to repro with the above env or their own?

### PR DESCRIPTION
**Pull request by saad-ali**
Cherry picking PR #15158, flocker volume unit test fix, to 1.1 release.

Fixes #15118
Fixes #15212 

CC @agonzalezro @mattbates  @jdef @karlkfi

### CODE REVIEW

**Comment by saad-ali** [comment]
@jdef as the author of the original PR, can you confirm that you're okay with these commits being contributed to Google for the Kubernetes 1.1 release.

**Comment by jdef** [comment]
Yes I approve.

**Comment by karlkfi** [comment]
teamcity failure caused by not having #15434 merged yet.

**Comment by thockin** [comment]
Manual merge because CLA will never be happy

**Pull request merged**
