### PR TITLE
[Federation] Fix Running service controller in federation kubectl tests

### PR DESCRIPTION
**Pull request by shashidharatd**
Fixes:  #42607

cc @nikhiljindal @kubernetes/sig-federation-bugs

### CODE REVIEW

**Comment by marun** [comment]
Is a change to the controller manager required?  This seems like a test configuration issue. 

I'm not sure, though, that dns should should to be configured for kubectl testing.  kubectl only sees the api - it doesn't directly interact with dns.  I think it would be preferable to avoid adding an unnecessary test dependency, and validate dns interaction in integration and e2e.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[federation/cmd/federation-controller-manager/app/controllermanager.go, line 167 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43136#-KfHOgmf2K84mlt8W5YR:-KfHOgmf2K84mlt8W5YS:b-iciuoz) ([raw file](https://github.com/kubernetes/kubernetes/blob/30b4ced23ebee64a113ebf150ba7ec7c39c53ba2/federation/cmd/federation-controller-manager/app/controllermanager.go#L167)):*
> ```Go
> 	if err != nil {
> 		glog.Fatalf("Could not find resources from API Server: %v", err)
> 		return err
> ```

This is unnecessary - the previous line will panic.

---

*[federation/cmd/federation-controller-manager/app/controllermanager.go, line 176 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43136#-KfHOlUeQGEBFlhYyBkp:-KfHOlUeQGEBFlhYyBkq:b-iciuoz) ([raw file](https://github.com/kubernetes/kubernetes/blob/30b4ced23ebee64a113ebf150ba7ec7c39c53ba2/federation/cmd/federation-controller-manager/app/controllermanager.go#L176)):*
> ```Go
> 		if err != nil {
> 			glog.Fatalf("Cloud provider could not be initialized: %v", err)
> 			return err
> ```

This is unnecessary - the previous line will panic.

---

*[federation/cmd/federation-controller-manager/app/controllermanager.go, line 184 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43136#-KfHPl5aWH-N6f_SVIVR:-KfHPl5aWH-N6f_SVIVS:b-8avcg7) ([raw file](https://github.com/kubernetes/kubernetes/blob/30b4ced23ebee64a113ebf150ba7ec7c39c53ba2/federation/cmd/federation-controller-manager/app/controllermanager.go#L184)):*
> ```Go
> 		if err := servicecontroller.Run(s.ConcurrentServiceSyncs, wait.NeverStop); err != nil {
> 			glog.Errorf("Failed to start service controller: %v", err)
> 			return err
> ```

What does this have to do with #42607?  The exit point was L173, which causes a panic.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43136#-:-KfHQSjLxb3_pNYrLJER:b-ce5p51)*

**Comment by nikhiljindal** [comment]
Yes we can update the test to not require DNS when we have that ability. Right now, we dont want to disable services, so need this. Services controller fails to come up without DNS.
And note that we are not starting a CoreDNS instance here. Just passing the flags for it to controller manager :)

/release-note-none

**Comment by shashidharatd** [comment]
> Is a change to the controller manager required? This seems like a test configuration issue.
Controller Manager was not failing fast if there were errors in initializing few controllers. probably this was due to kubectl tests or may be whatever reason.

> I'm not sure, though, that dns should should to be configured for kubectl testing. kubectl only sees the api - it doesn't directly interact with dns. I think it would be preferable to avoid adding an unnecessary test dependency, and validate dns interaction in integration and e2e.
As nikhil commented, We are not testing DNS here, just unblocking controller-manager initialization, so that kubectl tests can be run. when controller-manager could be initialized without DNS provider and without failing to start all required controllers, we could remove this setup part.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[federation/cmd/federation-controller-manager/app/controllermanager.go, line 167 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43136#-KfHOgmf2K84mlt8W5YR:-KfUItFGZQyER5ZyYDo-:b-gcgggn) ([raw file](https://github.com/kubernetes/kubernetes/blob/30b4ced23ebee64a113ebf150ba7ec7c39c53ba2/federation/cmd/federation-controller-manager/app/controllermanager.go#L167)):*
<details><summary><i>Previously, marun (Maru Newby) wrote…</i></summary><blockquote>

This is unnecessary - the previous line will panic.
</blockquote></details>

I don't see in the code that, when we do glog.Fatalf, the code will panic, it just logs with Fatal severity.
Also if we didn't fail here, we may be running the controller-manager with undesired behaviors.

---

*[federation/cmd/federation-controller-manager/app/controllermanager.go, line 176 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43136#-KfHOlUeQGEBFlhYyBkp:-KfUJRXoR6MLPvz49Cub:bnj7hl0) ([raw file](https://github.com/kubernetes/kubernetes/blob/30b4ced23ebee64a113ebf150ba7ec7c39c53ba2/federation/cmd/federation-controller-manager/app/controllermanager.go#L176)):*
<details><summary><i>Previously, marun (Maru Newby) wrote…</i></summary><blockquote>

This is unnecessary - the previous line will panic.
</blockquote></details>

same as above

---

*[federation/cmd/federation-controller-manager/app/controllermanager.go, line 184 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43136#-KfHPl5aWH-N6f_SVIVR:-KfUJcftt0YTSWrieQOI:b11qjim) ([raw file](https://github.com/kubernetes/kubernetes/blob/30b4ced23ebee64a113ebf150ba7ec7c39c53ba2/federation/cmd/federation-controller-manager/app/controllermanager.go#L184)):*
<details><summary><i>Previously, marun (Maru Newby) wrote…</i></summary><blockquote>

What does this have to do with #42607?  The exit point was L173, which causes a panic.
</blockquote></details>

same argument as previous comment, if we are not able to start service controller and we were supposed to start it, then it makes sense to fail and let the user know.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43136#-:-KfUK02c8n0PBf-o_qyv:bvvmk82)*

**Comment by marun** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[federation/cmd/federation-controller-manager/app/controllermanager.go, line 167 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43136#-KfHOgmf2K84mlt8W5YR:-KfX7x8zNOkkYXqFRCxl:bw0fn9c) ([raw file](https://github.com/kubernetes/kubernetes/blob/30b4ced23ebee64a113ebf150ba7ec7c39c53ba2/federation/cmd/federation-controller-manager/app/controllermanager.go#L167)):*
<details><summary><i>Previously, shashidharatd (Shashidhara T D) wrote…</i></summary><blockquote>

I don't see in the code that, when we do glog.Fatalf, the code will panic, it just logs with Fatal severity.
Also if we didn't fail here, we may be running the controller-manager with undesired behaviors.
</blockquote></details>

When I said 'panic', I meant 'exit', but otherwise my comments stands.  Please confirm for yourself via the [godoc](https://godoc.org/github.com/golang/glog#Fatalf) for ``glog.Fatalf``. 

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43136)*

**Comment by shashidharatd** [comment]
@marun, Thanks for the correcting my understanding. I have updated the code now.  PTAL

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[federation/cmd/federation-controller-manager/app/controllermanager.go, line 167 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43136#-KfHOgmf2K84mlt8W5YR:-KfXT_J6U4f8H_R_cuat:b-t8xga7) ([raw file](https://github.com/kubernetes/kubernetes/blob/30b4ced23ebee64a113ebf150ba7ec7c39c53ba2/federation/cmd/federation-controller-manager/app/controllermanager.go#L167)):*
<details><summary><i>Previously, marun (Maru Newby) wrote…</i></summary><blockquote>

When I said 'panic', I meant 'exit', but otherwise my comments stands.  Please confirm for yourself via the [godoc](https://godoc.org/github.com/golang/glog#Fatalf) for ``glog.Fatalf``. 
</blockquote></details>

yes @marun, i was wrong. I correct my understanding. glog.Fatalf does indeed fails fast. 

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43136#-:-KfXU1Ny3x5jvYMNESI0:b-iciha6)*

**Comment by marun** [comment]
/lgtm code-wise

Will this test run pre-merge or have you run it locally?

**Comment by shashidharatd** [comment]
@marun, the changes have been tested locally and also runs as part of 'Jenkins unit/integration' tests.

**Comment by shashidharatd** [comment]
@fejta, request to approve this for hack related changes

**Comment by fejta** [comment]
/lgtm

@shashidharatd @madhusudancs consider having at least one of you two add yourself as owners of hack/OWNERS. No need to add my latency to all the good work you're doing.

**Comment by madhusudancs** [comment]
> @shashidharatd @madhusudancs consider having at least one of you two add yourself as owners of hack/OWNERS. No need to add my latency to all the good work you're doing.

@fejta thanks for the suggestion. This is badly needed. I sent PR #44213 to add both Shashi and me as approvers of `hack/OWNERS`.

**Comment by shashidharatd** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
