### PR TITLE
cleanup: Remove support for i18n in kubectl

### PR DESCRIPTION
**Pull request by wafuwafu13**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

i18n is supported in kubectl, but most languages are only slightly complete and have not been maintained for over a year.
The Japanese example makes me feel uncomfortable with a little Japanese in the mix.

<details>
<summary>ex) ja_JP `kubectl --help`</summary>

```zsh
$ kubectl --help
kubectl controls the Kubernetes cluster manager.

 Find more information at: https://kubernetes.io/docs/reference/kubectl/overview/

Basic Commands (Beginner):
  create          Create a resource from a file or from stdin
  expose          Take a replication controller, service, deployment or pod and expose it as a new Kubernetes service
  run             Run a particular image on the cluster
  set             Set specific features on objects

Basic Commands (Intermediate):
  explain         Get documentation for a resource
  get             1つまたは複数のリソースを表示する
  edit            Edit a resource on the server
  delete          Delete resources by file names, stdin, resources and names, or by resources and label selector

Deploy Commands:
  rollout         Manage the rollout of a resource
  scale           Set a new size for a deployment, replica set, or replication controller
  autoscale       Auto-scale a deployment, replica set, stateful set, or replication controller

Cluster Management Commands:
  certificate     Modify certificate resources.
  cluster-info    Display cluster information
  top             Display resource (CPU/memory) usage
  cordon          Mark node as unschedulable
  uncordon        Mark node as schedulable
  drain           Drain node in preparation for maintenance
  taint           Update the taints on one or more nodes

Troubleshooting and Debugging Commands:
  describe        Show details of a specific resource or group of resources
  logs            Print the logs for a container in a pod
  attach          Attach to a running container
  exec            Execute a command in a container
  port-forward    Forward one or more local ports to a pod
  proxy           Run a proxy to the Kubernetes API server
  cp              Copy files and directories to and from containers
  auth            Inspect authorization
  debug           Create debugging sessions for troubleshooting workloads and nodes

Advanced Commands:
  diff            Diff the live version against a would-be applied version
  apply           Apply a configuration to a resource by file name or stdin
  patch           Update fields of a resource
  replace         Replace a resource by file name or stdin
  wait            Experimental: Wait for a specific condition on one or many resources
  kustomize       Build a kustomization target from a directory or URL.

Settings Commands:
  label           リソースのラベルを更新する
  annotate        リソースのアノテーションを更新する
  completion      Output shell completion code for the specified shell (bash, zsh or fish)

Other Commands:
  alpha           Commands for features in alpha
  api-resources   Print the supported API resources on the server
  api-versions    Print the supported API versions on the server, in the form of "group/version"
  config          kubeconfigを変更する
  plugin          Provides utilities for interacting with plugins
  version         Print the client and server version information

Usage:
  kubectl [flags] [options]

Use "kubectl <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).
```

</details>

I think it's great to support internationalization, but It has become apparent that maintaining documentation in multiple languages is too difficult.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

This part of the replacement was done automatically. https://github.com/kubernetes/kubernetes/commit/65d13521eaa84890dda4ec46a62d624f9b064d3f

```txt
i18n.T\(("[\s\S\n]*?")\) -> $1
i18n.T\((`[\s\S\n]*?`)\) -> $1
```

#### Does this PR introduce a user-facing change?

```release-note
Remove support for i18n in kubectl
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by brianpursley** [comment]
I would not be surprised to find out that kubectl's i18n support is lacking.  I think this would be a good topic for discussion at the next SIG-CLI bi-weekly meeting, in order to determine what to do about this.

Removing it entirely feels like a drastic step to take, but it is good for the question to be raised.  If there is not enough support for improving and maintaining it properly, should we even have it at all?

I added it as a topic for the Sept 7 meeting: https://docs.google.com/document/d/1r0YElcXt6G5mOWxwZiXgGu_X6he3F--wKwg-9UBc29I

You (and anyone else) are welcome to attend, if you'd like to join in the discussion.

**Comment by brianpursley** [comment]
@wafuwafu13 Can you provide am example, from kubectl currently, of an incomplete Japanese i18n output?  I think having an example (or two) will help illustrate the problem you are describing an make sure everyone understands the problem correctly.

**Comment by wafuwafu13** [comment]
@brianpursley 
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/util/i18n/translations/kubectl/ja_JP/LC_MESSAGES/k8s.po shows that there are very few areas that are supported in Japanese.

In the result of `$ kubectl --help`, only `get`, `label`, `annotate`, and `config` are supported in Japanese.

<details>
<summary>ex) ja_JP `kubectl --help`</summary>

```zsh
$ kubectl --help
kubectl controls the Kubernetes cluster manager.

 Find more information at: https://kubernetes.io/docs/reference/kubectl/overview/

Basic Commands (Beginner):
  create          Create a resource from a file or from stdin
  expose          Take a replication controller, service, deployment or pod and expose it as a new Kubernetes service
  run             Run a particular image on the cluster
  set             Set specific features on objects

Basic Commands (Intermediate):
  explain         Get documentation for a resource
  get             1つまたは複数のリソースを表示する
  edit            Edit a resource on the server
  delete          Delete resources by file names, stdin, resources and names, or by resources and label selector

Deploy Commands:
  rollout         Manage the rollout of a resource
  scale           Set a new size for a deployment, replica set, or replication controller
  autoscale       Auto-scale a deployment, replica set, stateful set, or replication controller

Cluster Management Commands:
  certificate     Modify certificate resources.
  cluster-info    Display cluster information
  top             Display resource (CPU/memory) usage
  cordon          Mark node as unschedulable
  uncordon        Mark node as schedulable
  drain           Drain node in preparation for maintenance
  taint           Update the taints on one or more nodes

Troubleshooting and Debugging Commands:
  describe        Show details of a specific resource or group of resources
  logs            Print the logs for a container in a pod
  attach          Attach to a running container
  exec            Execute a command in a container
  port-forward    Forward one or more local ports to a pod
  proxy           Run a proxy to the Kubernetes API server
  cp              Copy files and directories to and from containers
  auth            Inspect authorization
  debug           Create debugging sessions for troubleshooting workloads and nodes

Advanced Commands:
  diff            Diff the live version against a would-be applied version
  apply           Apply a configuration to a resource by file name or stdin
  patch           Update fields of a resource
  replace         Replace a resource by file name or stdin
  wait            Experimental: Wait for a specific condition on one or many resources
  kustomize       Build a kustomization target from a directory or URL.

Settings Commands:
  label           リソースのラベルを更新する
  annotate        リソースのアノテーションを更新する
  completion      Output shell completion code for the specified shell (bash, zsh or fish)

Other Commands:
  alpha           Commands for features in alpha
  api-resources   Print the supported API resources on the server
  api-versions    Print the supported API versions on the server, in the form of "group/version"
  config          kubeconfigを変更する
  plugin          Provides utilities for interacting with plugins
  version         Print the client and server version information

Usage:
  kubectl [flags] [options]

Use "kubectl <command> --help" for more information about a given command.
Use "kubectl options" for a list of global command-line options (applies to all commands).
```

</details>

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by wafuwafu13** [comment]
I close this because there are a lot of changed files and no recent progress.

**Pull request closed without merging**
