### PR TITLE
Prober: Implement logging and event for unknown probe result 

### LINKED ISSUE #116026: Report event for the cases when probe returned Unknown result
There are a few cases when the Unknown result can be returned by the probe. For example see: https://github.com/kubernetes/kubernetes/issues/106682.

It will be useful to expose those in logs and as an event similar to what we do for Warning: https://github.com/kubernetes/kubernetes/blob/35f3fc59c1f29eebc8ff8705ecc3d4db7c4cbbc6/pkg/kubelet/prober/prober.go#L115

What needs to be done:

1. Implement logging and exposing event in case of `Unknown` probe result somewhere around https://github.com/kubernetes/kubernetes/blob/35f3fc59c1f29eebc8ff8705ecc3d4db7c4cbbc6/pkg/kubelet/prober/prober.go#L115
2. For each instance of probes potentially returning the `Unknown` result have a test that validates this test case. It may be either e2e test or unit test. You may find an example of e2e test that results in Unknown result from exec probe in one of the links from https://github.com/kubernetes/kubernetes/issues/106682

/sig node
/help wanted
/good-first-issue
/priority backlog

This issue is marked as "good first issue". Before assigning issue to yourself, please make sure you understand the assignment and list cases you will need to cover with tests.

cc @aojea

### PR DESCRIPTION
**Pull request by abhilasha2418**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
This commit adds logging and event exposure functionality to the probe function in the prober struct. If the probe result is unknown, it logs a message with the probe type, pod details, and container name. Additionally, it records a warning event for the container with the details of the unknown probe result.

The commit also includes a new test case to cover the scenario where the probe returns an unknown result. The test case creates a fake probe with an exec action, sets the exec result to probe.Unknown, and verifies that the probe function returns results.Failure and records the appropriate warning event.

This modification will help in diagnosing and resolving issues related to unknown probe results in Kubernetes.

#### Which issue(s) this PR fixes:

Fixes #116026

#### Does this PR introduce a user-facing change?
NONE

### CODE REVIEW

**Comment by bart0sh** [comment]
@abhilasha2418 please, [sign the CLA](https://github.com/kubernetes/community/blob/master/CLA.md) to proceed further with this PR, thanks.

**Comment by dims** [comment]
@abhilasha2418 can you please sign the CLA? see notes from the bot above. We can't really proceed without it.

**Pull request closed without merging**
