### PR TITLE
Fix metric label

### PR DESCRIPTION
**Pull request by rhcarvalho**

### CODE REVIEW

**Comment by rhcarvalho** [comment]
Hi, I work for Red Hat.

**Comment by mbforbes** [comment]
Tossing to node team—anyone (e.g. @lavalamp) know whether we need the CLA bot to find the username, even if they work for a verified company (I thought we'd fixed the RedHat issue?)

**Comment by lavalamp** [comment]
Yeah-- CLA stuff is fixed now. @rhcarvalho you either need to get into the red hat group, fix your email in the commit, or fix your email on github's user page, or some combination thereof.

**Comment by rhcarvalho** [comment]
Thanks @lavalamp. I've added my `@redhat.com` email to Github and verified it.
How can I tell if that is enough?

**Comment by lavalamp** [comment]
If that were enough, googlebot would have changed the label. :) So I guess you need to check your group membership, and check the email saved in the commit itself.

**Pull request closed without merging**
