### PR TITLE
Remove seemingly obsolete binaries

### PR DESCRIPTION
**Pull request by thockin**
It's hard to tell if these are safe to remove.  Let CI tell me.

### CODE REVIEW

**Comment by thockin** [comment]
I'll cirlce back to this later.  Was just exploring.

**Review by cblecker — APPROVED** [review]
This LGTM. Pulled this down and ran all the gen* make rules, as well as `hack/generate-docs.sh` (that wouldn't be run by CI) without error.

**Comment by thockin** [comment]
Thanks @cblecker I'll assign to you

**Comment by luxas** [comment]
ah yeah, LGTM to me as well.
Always feels nice to remove code :)

**Comment by steveperry-53** [comment]
@thockin, The docs builds are failing now because they rely on mungedocs.
https://github.com/kubernetes/kubernetes.github.io/pulls

**Comment by dims** [comment]
@steveperry-53 i filed a revert ^^

**Pull request merged**
