### PR TITLE
chore: slice replace loop

### PR DESCRIPTION
**Pull request by testwill**
Add one of the following kinds:
/kind cleanup

#### What this PR does / why we need it:
replace slice  loop copy
#### Which issue(s) this PR fixes:
no

#### Does this PR introduce a user-facing change?
NONE
```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bart0sh** [comment]
@testwill Thank you for this PR! Please, remove deprecation label and set release notes label correctly, thanks.

**Comment by danwinship** [comment]
/approve
the network bits

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

Node is fine

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
