### PR TITLE
re-run godep license

### PR DESCRIPTION
**Pull request by deads2k**
re-run `update-godep-licenses` to see what happens.  The result looks weird.

### CODE REVIEW

**Comment by dims** [comment]
@deads2k must be a fallout from this PR? https://github.com/kubernetes/kubernetes/commit/ad2cfc6510d032b9667c1e5ddb98312131c6beb6

**Comment by deads2k** [comment]
Looks like https://github.com/kubernetes/kubernetes/pull/37305 changed it.  At least the update makes more sense now.

**Comment by deads2k** [comment]
> @deads2k must be a fallout from this PR? ad2cfc6

Yeah, review?

**Comment by gmarek** [comment]
Thanks @deads2k. Merging to fix SQ.

**Comment by dims** [comment]
LGTM 👍

**Comment by Crassirostris** [comment]
Wait, shouldn't we revert LICENSE file in the repo root instead?

Right now we have a license template, not actual license in Godeps/LICENSES

**Comment by gmarek** [comment]
@deads2k

**Comment by deads2k** [comment]
> Wait, shouldn't we revert LICENSE file in the repo root instead?
> 
> Right now we have a license template, not actual license in Godeps/LICENSES

I will not even pretend to know.  It chains to this issue: https://github.com/kubernetes/kubernetes-template-project/issues/3 . I just want a working queue, so any path to getting there works for me.

**Comment by Crassirostris** [comment]
@deads2k I agree, I will make another PR to fix the issue properly

**Comment by mikedanese** [comment]
The license in the root is an actual license and is not a license template. Kubernetes is licensed under the license in the root. The license contains an [appendix](https://github.com/kubernetes/kubernetes/blob/master/LICENSE#L179-L202) that explains how you too can license your code under the same license. The appendix contains a [line](https://github.com/kubernetes/kubernetes/blob/master/LICENSE#L179-L202):
```
   Copyright [yyyy] [name of copyright owner]
```
That people often incorrectly change to
```
   Copyright 2016 Kubernetes Authors
```
But that line should remain in template form since it's in the instructional section of how to apply the  Apache v2 license.

cc @philips

**Comment by Crassirostris** [comment]
@mikedanese OK, thanks for the explanation!

**Pull request merged**
