### PR TITLE
Remove resync period for sset controller

### LINKED ISSUE #75495: statefulset controller create pod too slowly
/area controller-manager 
**What would you like to be added**:
Don't resync statefulset in statefulset controller.
**Why is this needed**:
There are 2000+ sts in my k8s cluster, thus when i create a new sts, it takes a lot of time to create it's pod, i found that every sts will cost 40ms to sync it, then 2000 sts will cost 80s, and there is also a statefulSetResyncPeriod to resync all sts, I don't know why there need to have statefulSetResyncPeriod to resync all sts?  Can we not resync sts and just watch it's changes?

### PR DESCRIPTION
**Pull request by anyasabo**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
The stateful set controller is resyncing all ssets every 30 seconds, As discussed in the linked issue, this is not necessary, and can cause delays processing actual updates when large amounts of ssets exist.

**Which issue(s) this PR fixes**:
Fixes #75495

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
StatefulSet controllers no longer force a resync every 30 seconds when nothing has changed.
```

### CODE REVIEW

**Comment by likakuli** [comment]
@jonsabo The default SharedInformerFactory has a default resync period, if not set in the config file, it will be 12 * Hous ~ 2 * 12 * Hours,  so the statefulset still will have the probelem when use the default resync period

**Comment by jonsabo** [comment]
That seems like that might be acceptable, a quick scan looks like deployments, daemonsets, and replicasets do not explicitly set a resync

**Comment by enisoc** [comment]
/ok-to-test
/approve

I suggest adding a bit more detail in the release note:

```
StatefulSet controllers no longer force a resync every 30 seconds when nothing has changed.
```

**Comment by jonsabo** [comment]
Thanks for the wording suggestion @enisoc, that seems reasonable.
/retest

**Pull request merged**
