### PR TITLE
[WIP] Refactor FakeWatcher to be thread-safe & race-free

### PR DESCRIPTION
**Pull request by karlkfi**
/kind cleanup
/kind flake

#### What & Why

The FakeWatcher doesn't expose the result channel or stop channel, which makes it impossible to use correctly by the event producer. This has made every test that uses the FakeWatcher effectively invalid, because it cannot correctly simulate the way the client and server negotiate how to stop. Plus, while the comments say it's thread-safe, it's not actually, and has several possible race conditions. In the past, alternative watcher implementations have been added to use instead of FakeWatcher, but because of its name, FakeWatcher is used all over the place in k/k and for testing 3rd party controllers. 

This PR refactors the FakeWatcher to be thread-safe & race-free. It also updates all the tests in k/k to use FakeWatcher correctly.

- Add FakeWatcher methods: StopChan, Close, IsClosed.
  These allow the event producer to close the result channel, which
  signals to the event consumer that the producer is done sending
  events. Stop() should only be called by the event consumer, to
  signal to the producer that it's done receiving events.
  This allows for bidirectional communication between the producer
  and consumer, with cleanup on both sides.
- Modify all tests using FakeWatcher to correctly Stop & Close.
  This should fix quite a few race conditions.
  It also uncovered a few bugs.
- Fix WatchServer.HandleHTTP to Stop the watcher when done reading
  events from the result channel, even on errors before reading from
  the result channel has started.
- Fix WatchServer.HandleHTTP to cleanup the TimeoutFactory in the
  rare case of some early Flusher and FrameWriter errors.
- Fix multiple instances where watcher.ResultChan() is being called
  from inside a for loop. Moving this outside the for loop allows
  these consumers to work with watch.Interface implementations that
  return a new result channel every time ResultChan() is called,
  even though we don't have any current examples.
- Remove FakeWatcher.Reset(). It was unused and causes problems with
  thread-safety. The better approach is to Close() the current
  watcher and create a new one for the next call to Watch.
- Add testing in numerous places to validate that the watcher is
  correctly stopped and closed. This uncovered a few test bugs.
- Fix TestNewInformerWatcher to test with the WatchListClient feature
  both enabled and disabled.

#### Dependencies

- https://github.com/kubernetes/kubernetes/pull/125107
- https://github.com/kubernetes/kubernetes/pull/123974
- https://github.com/kubernetes/kubernetes/pull/125302

#### Does this PR introduce a user-facing change?

```release-note
[client-go] Refactor FakeWatcher to be thread-safe & race-free.
```

### CODE REVIEW

**Comment by karlkfi** [comment]
Looks like TestPlugin is flaky. Ordering problem.
```
{Failed;Failed;Failed;  === RUN   TestPlugin/too-many-translated-class-parameters/prefilter
    dynamicresources_test.go:1103: 
        	Error Trace:	/home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go:1221
        	            				/home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go:1103
        	Error:      	Not equal: 
        	            	expected: &framework.Status{code:1, reasons:[]string(nil), err:(*errors.errorString)(0xc0000236a0), plugin:""}
        	            	actual  : &framework.Status{code:1, reasons:[]string(nil), err:(*errors.errorString)(0xc0008c6240), plugin:""}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -4,3 +4,3 @@
        	            	  err: (*errors.errorString)({
        	            	-  s: (string) (len=142) "multiple generated class parameters for ResourceClassParameters.example.com my-resource-class found: [default/my-resource-class default/other]"
        	            	+  s: (string) (len=142) "multiple generated class parameters for ResourceClassParameters.example.com my-resource-class found: [default/other default/my-resource-class]"
        	            	  }),
        	Test:       	TestPlugin/too-many-translated-class-parameters/prefilter
        --- FAIL: TestPlugin/too-many-translated-class-parameters/prefilter (0.00s)
```

**Comment by carlory** [comment]
> Looks like TestPlugin is flaky. Ordering problem.
> 

It will be fixed by https://github.com/kubernetes/kubernetes/pull/125213

**Pull request closed without merging**
