### PR TITLE
Close file after os.Open()

### PR DESCRIPTION
**Pull request by FengyunPan**
None

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by FengyunPan** [comment]
@k8s-bot kops aws e2e test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by FengyunPan** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by FengyunPan** [comment]
ping @janetkuo

**Review by janetkuo — APPROVED** [review]

**Comment by janetkuo** [comment]
/lgtm
/approve

@FengyunPan thanks for the fix!

**Comment by FengyunPan** [comment]
@k8s-bot pull-kubernetes-unit test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by FengyunPan** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by FengyunPan** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by FengyunPan** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
