### PR TITLE
portallocator: fix bug in AllocateNext

### PR DESCRIPTION
**Pull request by beautytiger**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
`AllocateNext` will try to return `lastPort + 1` in dry-run mode, since in most cases, lastPort will >100, this pr fix bugs in this loop.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by beautytiger** [comment]
kindly ping @wojtek-t

**Comment by wojtek-t** [comment]
@beautytiger - you named this PR: "fix bug in AllocateNext". Where is the bug?
When I'm looking into the changes, they seem like "no-op" to me (i.e., it's only code-refactoring).
So i would first like to understand where the problem is.

**Comment by beautytiger** [comment]
> @beautytiger - you named this PR: "fix bug in AllocateNext". Where is the bug?
> When I'm looking into the changes, they seem like "no-op" to me (i.e., it's only code-refactoring).
> So i would first like to understand where the problem is.

@wojtek-t:
Yes, there are some code refactoring.
The bug is here, the origin code is:
```go
for port := lastPort + 1; port < 100; port++ {
```
`lastPort` is host port which is usually > 100, so the loop runs dummy.
I change it to this:
```go
for offset := 1; offset < 100; offset++ {
    port := lastPort + offset
```
It make the loop runing meaningful.
Does it?

**Comment by wojtek-t** [comment]
@beautytiger - ok thanks, it makes sense.
The code looks ok, but it requires a unit test. Can you please add it?

/ok-to-test

**Comment by beautytiger** [comment]
@wojtek-t 
I found the test `TestDryRunAllocateNext` is already there, and the coverage is good. how about keep it as is?

**Comment by wojtek-t** [comment]
> I found the test TestDryRunAllocateNext is already there, and the coverage is good. how about keep it as is?

What you caught and fixed is clearly a bug. None of the existing tests were catching it. So we need a test that would catch that in the future.
We need a test that would catch that in the future (i.e. a test that was failing for the currently existing code and is no longer failing with your PR).

**Comment by beautytiger** [comment]
@wojtek-t 
Actually this is code inner logic bug,  not an external performance bug, I can hardly think of a unit test to test the inner logic of this code block. 
Do you have any good idea :)

**Comment by wojtek-t** [comment]
> Actually this is code inner logic bug, not an external performance bug, I can hardly think of a unit test to test the inner logic of this code block.
Do you have any good idea :)

If you can't reproduce it with any unit test, that means this bug doesn't exist :)

I'm fairly sure it should be possible to create a unit test. You need to allocate enough (and appropriate) ports before (e.g 1..100), and then allocating 1 should fail now and pass with the new code? [May not work as i wrote, but some variance of it should be possible.]

**Pull request closed without merging**
