### PR TITLE
Fix link to node selector documentation.

### PR DESCRIPTION
**Pull request by davidopp**

### CODE REVIEW

**Comment by mikedanese** [comment]
LGTM. You'll need to rebase onto a current master to fix shippable (go1.3 build was broken)

**Comment by mikedanese** [comment]
Actually, is that link supposed to work? I get redirected to the home page.

http://releases.k8s.io/HEAD/docs/user-guide/node-selection/README.md

**Comment by davidopp** [comment]
Very weird. When you wrote that comment yesterday, I checked and you were right. But I clicked again just now and it went to the right place!

**Comment by mikedanese** [comment]
I concur. Readding LGTM.

**Comment by davidopp** [comment]
One of the two shippable builds failed but it is #11857 so this is fine to merge.

**Pull request merged**
