### PR TITLE
Remove unreachable code for apiserver_test.go

### PR DESCRIPTION
**Pull request by gavinfish**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Once the `t.Fatalf` method is called, the test case will fail immediately. So the deleted code will never be executed.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by jennybuckley** [comment]
All the other similar status code checks in this file seem to use Errorf() so I think the best way to fix this would be to just change the Fatalf() call to Errorf().

Example of a similar status code check in apiserver_test.go:
https://github.com/kubernetes/kubernetes/blob/ca0d84e012176fb75b3d2d3368b2da6c50aa97f9/staging/src/k8s.io/apiserver/pkg/endpoints/apiserver_test.go#L3142-L3149

**Comment by gavinfish** [comment]
@jennybuckley it used be `Errorf()` and is changed in #40389.

So the discussion here should be once the delete request fails, is it necessary to check the deleted ID and deleteOptions.

**Comment by gavinfish** [comment]
/assign @andrewsykim

Could you please take a look at this one, thanks.

**Comment by fedebongio** [comment]
@jennybuckley author reopened, could you take a look?
/triage accepted

**Pull request closed without merging**
