### PR TITLE
Add cpu/mem reservation metrics for autoscaler in kube-up

### PR DESCRIPTION
**Pull request by mwielgus**

### CODE REVIEW

**Comment by mwielgus** [comment]
cc: @piosz @jszczepkowski

**Comment by piosz** [comment]
LGTM

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by jszczepkowski** [comment]
@mwielgus 
Have you tested this PR manually?

**Comment by mwielgus** [comment]
Yes.

**Pull request merged**
