### PR TITLE
Tag Multi-AZ scheduling tests as serial

### PR DESCRIPTION
**Pull request by marun**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

As per @mdame, we can't ensure that the cluster is actually balanced if other tests are adding or deleting pods in parallel.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

@smarterclayton

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/approve
These tests suffer from the ongoing issue with our scheduling e2es regarding balanced clusters. 

In clusters that run a lot of extra background components (like OpenShift), resource requests can vary between nodes which has unintentional effects on the scheduling decisions these e2es try to test for, causing flakes.

So we usually add calls to `createBalancedPodForNodes()` in our e2es, but in non-serial tests that balancing doesn't work as pods are added and deleted by other tests running in parallel.

cc @ahg-g

**Comment by smarterclayton** [comment]
For further context here, when I was reviewing these I noticed the care and attention the BeforeEach was taking to make sure the nodes were balanced.... while at the same time tens of other tests could be running and creating tens or hundreds of pods.

/approve

**Comment by smarterclayton** [comment]
/hold

Just to verify that the jobs haven't changed so much that this excludes the test completely (after i see it i will remove)

**Comment by smarterclayton** [comment]
So serial tests are running in https://testgrid.k8s.io/google-gce#gce-cos-master-serial and https://testgrid.k8s.io/sig-scheduling#gce-serial which should be sufficient to catch this in the future.

/retest
/hold cancel

**Comment by smarterclayton** [comment]
Does not impact the 1.21 release (doesn't flake that often in existing PR jobs) and can wait for 1.22 to open

**Pull request merged**
