### PR TITLE
Automated cherry pick of #120870: update filepath-securejoin dependency to 0.2.4 to fix

### PR DESCRIPTION
**Pull request by kmala**
Cherry pick of #120870 on release-1.26.

#120870: update filepath-securejoin dependency to 0.2.4 to fix

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by pacoxu** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-dependencies/1735221545468432384
```
-	github.com/rogpeppe/go-internal v1.11.0 // indirect
+	github.com/rogpeppe/go-internal v1.12.0 // indirect
```

run `hack/update-vendor.sh` can fix the CI
/hold
feel free to unhold once the ci is green

**Comment by liggitt** [comment]
note that this dependency is only used by the alpha kubelet system logging feature

**Pull request merged**
