### PR TITLE
WIP: check pod annotations for service deps

### PR DESCRIPTION
**Pull request by pmorie**
Prototyping @bgrant0607's suggestion for checking service predeclarations in the API server from #1768

### CODE REVIEW

**Comment by pmorie** [comment]
@bgrant0607 @smarterclayton PTAL; I am thinking through the best way to modify `kubectl`, will do that in next commit.

**Comment by pmorie** [comment]
Closing, I don't like this factoring at all.

**Comment by bgrant0607** [comment]
I apologize for not providing feedback. Totally swamped.

**Comment by pmorie** [comment]
@bgrant0607 No problem, I had a productive chat with @derekwaynecarr and the esteemed @smarterclayton esq. today and we thought of a factoring I like much better.  New PR coming soon.

**Pull request closed without merging**
