### PR TITLE
Replace strings.Index with strings.Contains

### PR DESCRIPTION
**Pull request by navist2020**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
If we just want to know whether A(str) contains B(str). It should be used `strings.Contains`.
https://staticcheck.io/docs/checks#S1003
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by navist2020** [comment]
ping @yliaog

**Comment by yliaog** [comment]
/assign @deads2k 

for approval

**Pull request closed without merging**
