### PR TITLE
Remove val and ok in Storageos

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
in for loop has define the two para 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by verult** [comment]
Line 194 should have `:=` instead of `=`.

The var declarations couple lines before that can be removed as well.

**Comment by saad-ali** [comment]
Please squash commits
/hold

**Comment by xiangpengzhao** [comment]
pull-kubernetes-bazel-test fails:

```
W0227 02:17:57.895] 2018/02/27 02:17:57 error running compiler: exit status 1
I0227 02:17:57.996] pkg/volume/storageos/storageos_util_test.go:200:6: undefined: val
I0227 02:17:57.996] pkg/volume/storageos/storageos_util_test.go:201:66: undefined: val
W0227 02:17:58.719] INFO: Elapsed time: 190.906s, Critical Path: 33.26s
W0227 02:17:58.719] FAILED: Build did NOT complete successfully
```

**Comment by jianglingxia** [comment]
for lgtm and hold cancel @saad-ali @verult 
thanks

**Comment by jianglingxia** [comment]
@ jdumars the pr has labeled v1.10,can merge v1.10?thanks!
for lgtm @saad-ali @verult

**Comment by jianglingxia** [comment]
/assign @thockin 
PTAL for lgtm and Labels Incomplete and kind,thanks

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/54970)

**Comment by jianglingxia** [comment]
can hold cancel? @verult 
thanks

**Pull request merged**
