### PR TITLE
fix install etcd, even that we have one

### LINKED ISSUE #66849: etcd verion comparsion are not correct
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/assign
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
Seems unreasonable in two part:
1、 if have one `etcd` in Env, and the `version` higher than the `minimum version` also ok, but code 
```
os=$(uname | tr "[:upper:]" "[:lower:]")
if [[ $(readlink etcd) == etcd-v${ETCD_VERSION}-${os}-* ]]; then
      return  # already installed
fi
```
in https://github.com/kubernetes/kubernetes/blob/master/hack/lib/etcd.sh#L108 seems confused.

2、Consider that situation:

- First install `etcd` like this in local:
- Secondary, download `etcd tar` file
- Third, `tar xzf` the `etcd tar' file
- Fourth, copy the `etcd` binary to some directory, like `usr/local/bin` , rather than take it in `/third-party`, using `soft link`
- Then, run `hack/local-up-cluster.sh` create a cluster
- Finally, run 
 ```
 hack/update-swagger-spec.sh
 ```
 or
```
 hack/verify-swagger-spec.sh
 ```

**What you expected to happen**:
First compare `os` version, then compare `etcd` version(higher than `ETCD_VERSION` also better)

**How to reproduce it (as minimally and precisely as possible)**:

- Install Ectd(higher than ${ETCD_VERSION}) manaully: down `etcd tar` file, and `tar xzf` it, copy binary to `usr/local/bin`
- run `hack/local-up-cluster.sh`, setting up a local cluster
- run

```
hack/update-swagger-spec.sh
```
or
```
hack/verify-swagger-spec.sh
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.2608+8e2d37ee63d0a1", GitCommit:"8e2d37ee63d0a1f71baa07e8e4ee57cb3b86e9b6", GitTreeState:"clean", BuildDate:"2018-08-01T07:05:13Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.2608+8e2d37ee63d0a1", GitCommit:"8e2d37ee63d0a1f71baa07e8e4ee57cb3b86e9b6", GitTreeState:"clean", BuildDate:"2018-08-01T07:05:13Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="14.04, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```
- Kernel (e.g. `uname -a`):
```
3.13.0-24-generic
```
- Install tools:
```
hack/local-up-cluster.sh
```
- Others:

### PR DESCRIPTION
**Pull request by stewart-yu**
**What this PR does / why we need it**:
fix etcd version comparsion, so that we do not need to install one, even that we have one

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #66849 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
@stewart-yu Can you explain more clearly what you are trying to fix here?

**Comment by ixdy** [comment]
@cblecker based on my reading of #66849, I believe the desire is to support using a newer etcd for testing than is officially supported by kubernetes. I don't think this is a good idea.

**Comment by cblecker** [comment]
Yeah, I agree. Not sure if it's a good idea.

Placing explicit hold until we get more details.
/hold

**Comment by cblecker** [comment]
Closing as wontfix. You can change the etcd version via environment variable if you're testing a specific version, but we don't want to allow flux in the version.
/close

**Pull request closed without merging**
