### PR TITLE
update docs to use hyperkube image

### LINKED ISSUE #11751: Missing Kubernetes images in GCR, should be pushed on release
These docs says that one can pull Kubernetes images for each release from GCR:

https://github.com/GoogleCloudPlatform/kubernetes/blob/v1.0.1/docs/getting-started-guides/scratch.md

However, release images seem to be missing in GCR:

```
docker pull gcr.io/google_containers/kube-apiserver:v1.0.0
Pulling repository gcr.io/google_containers/kube-apiserver
FATA[0000] Tag v1.0.0 not found in repository gcr.io/google_containers/kube-apiserver

docker pull gcr.io/google_containers/kube-apiserver:v1.0.1
Pulling repository gcr.io/google_containers/kube-apiserver
FATA[0000] Tag v1.0.1 not found in repository gcr.io/google_containers/kube-apiserver

docker pull gcr.io/google_containers/kube-apiserver:1.0.1
Pulling repository gcr.io/google_containers/kube-apiserver
FATA[0000] Tag 1.0.1 not found in repository gcr.io/google_containers/kube-apiserver
```

### PR DESCRIPTION
**Pull request by brendandburns**
Closes #11751

### CODE REVIEW

**Comment by mikedanese** [comment]
@erictune

**Comment by brendandburns** [comment]
Rebased.

**Comment by mikedanese** [comment]
This needs a gendoc run.

**Comment by brendandburns** [comment]
gendocs updated.

**Comment by mikedanese** [comment]
LGTM on green.

**Comment by brendandburns** [comment]
Self-LGTM on Mike's LGTM on green (since it's green)

**Comment by alex-mohr** [comment]
LGTM was before last commit, removing LGTM

**Comment by alex-mohr** [comment]
@brendandburns Did the LGTM vs. commit timestamp detector do the right thing here?  Seems suspicious.

**Comment by alex-mohr** [comment]
@k8s-bot test this [contrib/submit-queue: candidate for merging]

**Comment by alex-mohr** [comment]
Automatic merge from SubmitQueue

**Pull request merged**
