### PR TITLE
including metadata in third party resource list

### PR DESCRIPTION
**Pull request by sitepodmatt**
This change makes ThirdPartyResourceDataList json serialization more consistent with the core types, importantly including metadata for resourceVersion so controller list behaves correctly.

String templating of the json result has been replaced in favor of marshalling an anonymous struct. 

[Analytics]()

### CODE REVIEW

**Comment by nowprovision** [comment]
This relates to a bug I noticed that resourceVersion was including in listing of third party resources, it could also be affecting other users e.g. https://github.com/kubernetes/kubernetes/issues/25340

**Comment by nowprovision** [comment]
Im closing this and will resubmit as I've noticed ApiVersion isn't populated, on strict clients this could be a problem

**Comment by borismattijssen** [comment]
Why is this closed?

**Comment by nowprovision** [comment]
Sorry I thought I left a commit prior to closing. There is an omission, APIVersion should be populated from thirdPartyResourceDataEncoder as obj.APIVersion is that of ThirdPartyResource. I didn't notice this as I wasn't testing with kubernetes client code. I've made a fix today but want to do some more testing to ensure I've got it all. I hope to submit a new PR in a few days.

**Comment by nowprovision** [comment]
@borismattijssen This has be reopened with apiVersion set correctly as https://github.com/kubernetes/kubernetes/pull/26012

**Pull request closed without merging**
