### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by mamil**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by libaoan — APPROVED** [review]

**Comment by xinydev** [comment]
> @mamil: Adding label `do-not-merge/contains-merge-commits` because PR contains merge commits, which are not allowed in this repository.
> Use `git rebase` to reapply your commits on top of the target branch. Detailed instructions for doing so can be found [here](https://git.k8s.io/community/contributors/guide/github-workflow.md#4-keep-your-branch-in-sync).

Hi, @mamil, you may need to fix this first

**Comment by mamil** [comment]
> > @mamil: Adding label `do-not-merge/contains-merge-commits` because PR contains merge commits, which are not allowed in this repository.
> > Use `git rebase` to reapply your commits on top of the target branch. Detailed instructions for doing so can be found [here](https://git.k8s.io/community/contributors/guide/github-workflow.md#4-keep-your-branch-in-sync).
> 
> Hi, @mamil, you may need to fix this first

done! thanks for your comment

**Review by xinydev — APPROVED** [review]
/ok-to-test
/triage accepted
/lgtm

**Comment by mamil** [comment]
@xinydev  may you give me approved label?

**Comment by xinydev** [comment]
> @xinydev may you give me approved label?

Sorry, I'm not a approver of `pkg/util/bandwidth`, I think danwinship will review/approve this when he get some time.

**Comment by xinydev** [comment]
ping @danwinship

**Pull request merged**
