### PR TITLE
updated fluentd to 1.7.4 + plugin updates and switch to debian buster

### PR DESCRIPTION
**Pull request by monotek**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
/kind flake

**What this PR does / why we need it**:
* updated fluentd to 1.7.4 
* fluentd plugin updates 
* switch to debian buster in docker image
* combined install steps in single install.sh script
* updated deamonset to use new v2.8.0 image (image is already pushed to quay.io)

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by like-inspur** [comment]
I use dockerfile to build fluentd image, but found fluentd version is 1.6.3 not 1.7.4
Installing fluentd (1.6.3)
when I config gem 'fluentd', '~>1.7.4' in Gemfile, the build of image output this error:
ERROR:  While executing gem ... (Gem::DependencyResolutionError)
    conflicting dependencies tzinfo (~> 1.1) and tzinfo (~> 2.0)
  Activated tzinfo-2.0.0
  which does not match conflicting dependency (~> 1.1)

  Conflicting dependency chains:
    fluentd (~> 1.7.4), 1.7.4 activated, depends on
    tzinfo (~> 2.0), 2.0.0 activated

  versus:
    activesupport (~> 6.0.1), 6.0.1 activated, depends on
    tzinfo (~> 1.1)

**Comment by monotek** [comment]
Not sure what you're refering to but the version is set to 1.7.4 in the used Gemfile. 

See: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Gemfile#L4

There is also no need to build the image by yourself. 
You can download the dockerimage from: https://quay.io/repository/fluentd_elasticsearch/fluentd?tab=tags

**Comment by like-inspur** [comment]
Because I want to add some plugin in Gemfile, even if I use your image, but found fluentd version is 1.6.3
root@k8s01:~# docker run -itd --name like quay.io/fluentd_elasticsearch/fluentd:v2.8.0
c47ac96ef5ccd73e039d32dbd7ef2360bdaa42d2358b8cf1e961e41183e7fbe2
root@k8s01:~# docker exec -it like bash
root@c47ac96ef5cc:/# fluent-gem list|grep fluentd
fluentd (1.6.3)

**Comment by monotek** [comment]
Ah, is see. Fixed it with: https://github.com/kubernetes/kubernetes/pull/86433

You, can use the new image now:

quay.io/fluentd_elasticsearch/fluentd:v2.9.0

**Comment by like-inspur** [comment]
Thank you! I have a question about why we must install activesupport, if I already use fluentd 1.7.4 without activesupport, what problem will be met? @monotek

**Comment by monotek** [comment]
Not sure about that. 
The gem was used from the beginning. 
We would have to ask the one who has put it there.

**Pull request merged**
