### PR TITLE
use log functions of core framework

### PR DESCRIPTION
**Pull request by YuikoTakada**
**What type of PR is this?**

/kind cleanup
/kind testing

**What this PR does / why we need it**:

use log functions of core framework

**Which issue(s) this PR fixes**:

Ref #81427

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
@YuikoTakada 
please sign the CNCF CLA as the bot instructed above.
if you have done that already make sure your CNCF email is added to your github account.
if that does not work, try contacting the CNCF help desk.

thanks.

**Comment by YuikoTakada** [comment]
@neolit123 thank you, I've signed CLA already, so that I don't know why cncf-cla error occurs. I'll check  CNCF or Github settings again.

**Comment by oomichi** [comment]
Thanks for doing this.

/lgtm
/approve

**Pull request merged**
