### PR TITLE
Update wordpress to 4.7.2 latest

### PR DESCRIPTION
**Pull request by ghost**
update wordpress version to latest 4.7.2

### CODE REVIEW

**Comment by netroby** [comment]
I signed it!

**Comment by jeffmendoza** [comment]
No release note needed, someone please add `release-note-none`

**Comment by netroby** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42029/pull-kubernetes-e2e-gke-gci/19515/?log#log
I checked the build.log . but seems it not caused by my code change. anyone who can take a look?

**Comment by netroby** [comment]
ping @jeffmendoza  how to let the build bot pass？

**Comment by roidelapluie** [comment]
@netroby you can commment with /release-notes-none

**Comment by roidelapluie** [comment]
sorry, /release-note-none

**Comment by netroby** [comment]
add /release-note-none

**Comment by netroby** [comment]
add /release-note-none

**Comment by roidelapluie** [comment]
without add :)

**Comment by netroby** [comment]
seems not working at all

**Comment by roidelapluie** [comment]
https://github.com/kubernetes/test-infra/blob/master/prow/commands.md should work.

**Comment by netroby** [comment]
Thanks. seems it works. but seems jenkins GCI GKE smoke e2e build failed. and the log detail seems not cause by my change

**Comment by jeffmendoza** [comment]
@k8s-bot gci gke e2e test this

**Comment by netroby** [comment]
@jeffmendoza Hello, would you please take a look? i can see the build log, the error may not cause by my change

**Comment by jeffmendoza** [comment]
@netroby Try to rebase and re-trigger tests.

I believe we need a milestone tag, does anyone know how to get one?

**Comment by netroby** [comment]
see https://github.com/kubernetes/kubernetes/pull/43183 and close this

**Pull request closed without merging**
