### PR TITLE
[do not merge] bump(fsouza/go-dockerclient): c0187cbf588c59709e8881fd2bba082b02231356

### PR DESCRIPTION
**Pull request by ncdc**

### CODE REVIEW

**Comment by ncdc** [comment]
@smarterclayton @bparees @derekwaynecarr FYI, this should fix an issue with `kubectl exec -it` hanging when you exit the remote shell.

**Comment by ncdc** [comment]
I'm having trouble getting interactive exec to work still. I could have sworn this was working... I'm going to keep digging. Hold off on merging.

**Comment by bparees** [comment]
What's the likelihood this issue would affect s2i also? Wondering if we
need to bump that again too.

Ben Parees | OpenShift

**Comment by ncdc** [comment]
You'd probably need to test with the problematic commit and see how it
does.

**Comment by ncdc** [comment]
I'm including the go-dockerclient godep bump inside #13322, as it's needed so everything in that PR works

**Pull request closed without merging**
