### PR TITLE
Allow remote runtimes to pass apparmor host validation

### LINKED ISSUE #51156: AppArmor validation is docker specific.
AppArmor validator returns error if the runtime is not `docker`.

For other runtime integrated via CRI, the runtime will be `remote`, and will not be able to provide AppArmor support because of this.

Currently, we decided to always pass validation for remote runtime, but we need a better solution in the future.

This is similar with https://github.com/kubernetes/kubernetes/issues/50343, and also related to #32803.

/cc @yujuhong @timstclair @feiskyer @mrunalp @mikebrow

### PR DESCRIPTION
**Pull request by feiskyer**
**What this PR does / why we need it**:

Allow remote runtimes to pass apparmor host validation.

**Which issue this PR fixes** : fixes #51156

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Random-Liu** [comment]
If we decided to pass validation for all runtime, we should remove the argument, because it's not used anymore.

However, at least rkt doesn't support it now, I'm not sure whether we could pass validation for all runtime.

@yujuhong

**Comment by mikebrow** [comment]
Yeah I was about to push my commit with the following when I saw you beat me to the PR:
```
+       // Check runtime support. Currently only Docker and CRI remotes are supported.
+       if runtime != "docker" && runtime != "remote" {
+               return fmt.Errorf("AppArmor is only enabled for 'docker' and 'remote' runtimes. Found: %q.", runtime)
```
just adds support for CRI instead of deleting the test since rkt and others are likely to fail.

**Comment by Random-Liu** [comment]
@mikebrow I think your approach is better given that we do have rkt support in tree today.

**Comment by feiskyer** [comment]
@mikebrow @Random-Liu Thanks. Updated as @mikebrow's approach.

**Comment by Random-Liu** [comment]
@feiskyer Thanks for the fix!

/test pull-kubernetes-e2e-gce-etcd3

**Pull request merged**
