### PR TITLE
Base Infrastructure for adding Merge() API to TopologyManager Policies

### PR DESCRIPTION
**Pull request by klueska**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR provides the base infrastructure needed to support the new `Merge()` abstraction in `TopologyManager` policies. It is adapted from https://github.com/kubernetes/kubernetes/pull/81586 with the original attribution to the author @adrianchiris in tact on all commits.

It basically takes parts of what @adrianchiris has done and cleans up the git history so that it's easier to review commit by commit. After this PR merges, the original  https://github.com/kubernetes/kubernetes/pull/81586 PR can be rebased on top of it, and will hopefully be much easier to review now that the base infrastructure code is in place.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
A huge thank you for breaking out the refactors into a series of easily digestible commits. 

/approve
/lgtm

**Comment by adrianchiris** [comment]
@klueska Thanks for splitting this up !
Will do my best to review this week (on a business trip)

**Pull request merged**
