### PR TITLE
Fix fake docker client to corretly report status of containers

### PR DESCRIPTION
**Pull request by yujuhong**
Forked from #17700

### CODE REVIEW

**Comment by yifan-gu** [comment]
LGTM

**Comment by yujuhong** [comment]
Applied lgtm based on https://github.com/kubernetes/kubernetes/pull/19393#issuecomment-169906145

**Comment by Random-Liu** [comment]
Also LGTM, :0

**Comment by yujuhong** [comment]
@saad-ali would you mind manually merging this PR? This only fixes the unit test and will allow easier review for my other dependent PRs.

**Pull request merged**
