### PR TITLE
Don't commit generated (some) code

### PR DESCRIPTION
**Pull request by thockin**
Now that we are past 1.4 and we have a real client library, let's try this
again.  This is not perfect, it still is missing other generated files, but
this is a start.

@caesarxuchao I'm assuming we do not need the generated files in the client lib?

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33440)

### CODE REVIEW

**Comment by thockin** [comment]
@caesarxuchao I don't know where the script that generates staging/ lives - it needs to `make generated_files` before saving directories.  Point me at it to confirm?

**Comment by thockin** [comment]
@k8s-bot gci gce e2e test this

**Comment by caesarxuchao** [comment]
Yeah, client-go needs the generated files. Could you call `make generated_files` in this [script](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/copy.sh)?

**Comment by thockin** [comment]
Yeah, that should be enough - do you have bandwidth to make that change
if/when this PR goes through?

**Comment by caesarxuchao** [comment]
Sure. We have an e2e test that will catch the missing generated files, so I won't forget.

**Comment by thockin** [comment]
@k8s-bot gci gce e2e test this

**Comment by thockin** [comment]
rebased

**Comment by caesarxuchao** [comment]
LGTM. Thanks.

**Comment by krousey** [comment]
Is there a way to do this while still leaving the API packages in a build-able state?

**Comment by thockin** [comment]
You mean to check it in but not check it in?  Schrodinger's code - it is
both committed and not committed, as long as you don't try to compile it.

**Comment by krousey** [comment]
No. The main errors seem to be referencing conversion functions that are generated. These function are registered with the scheme. Perhaps define and register the functions in the same file, so when it's not there, all references are gone.

**Comment by thockin** [comment]
Ahh, yes, the places that register their own conversions should not be
needed - I didn't fix that in this PR.  If you want me to do that, I can.
I will remove LGTM.

**Comment by nikhiljindal** [comment]
Verifying that this does not break federation

@k8s-bot federation gce e2e test this

**Comment by lavalamp** [comment]
I haven't looked at this and probably won't have a chance today, but please try to make everything build even without these files checked in.

**Comment by thockin** [comment]
so, right, I looked into this.  I can't make it build without generated files.  As it stands, a bunch of manual `Convert_foo_Foo_To_bar_Foo` functions call the generated `autoConvert_foo_Foo_To_bar_Foo` functions.  By design.  Until and unless we get to a mode where we emit into an auto-registered list and use a single accessor (that can fail at runtime instead of compile time) we can't fix that - no weak symbols in Go.

**Comment by thockin** [comment]
I won't reapply LGTM until that has time to sink in.  To make this build with or without generated files, we need to basically retool the whole deepcopy and conversion logic.

**Comment by thockin** [comment]
@k8s-bot unit test this

**Comment by caesarxuchao** [comment]
@thockin are you making progress? Ping me if you need me to review it again.

**Comment by thockin** [comment]
Rebased.  Let's see what CI says.

**Comment by thockin** [comment]
This actually passed CI, but I guess we want to wait until after 1.5

**Comment by thockin** [comment]
@mikedanese it might be nice to tell gazel to ignore some files (zz_generated.* in this case)

**Comment by thockin** [comment]
@mikedanese for bazel - looks like this PR would trigger the need for genrules and stuff that (TTBOMK) has not been written yet?

**Comment by mikedanese** [comment]
Yes we would need to implement genrules for the files that you are removing before bazel will pass. cc @ixdy @spxtr

**Comment by mikedanese** [comment]
@spxtr is working on getting this in

**Comment by spxtr** [comment]
I have this mostly working for bazel. One problem is that we have some generated code in `vendor/k8s.io/apimachinery` and I'm not sure how that's supposed to be handled. 5486c6a56a423bfee99a7dc7bcf9304f35d542c5 seems to say that the source of truth for this vendored code is still this repo?

**Comment by mikedanese** [comment]
@spxtr the source of repo will be this repo for the forseeable future.

**Comment by spxtr** [comment]
Ok, that's confusing.

**Comment by spxtr** [comment]
It'll probably be easier to do that once #40777 is done, since I'm going to have to add the appropriate rule to the `vendor/BUILD` file.

**Comment by thockin** [comment]
will push a new version, but just realized something.  If I remove the zz_generated.* files from BUILD files, will bazel pick them up when they exist?  Or do we need to ensure they exist when update-bazel runs?

**Comment by thockin** [comment]
If I include the zz_generated in BUILD, it complains of missing files. If I don't include zz_generated, it fails to build.  Didn't you have  a PR to add genrules for these :)

**Comment by spxtr** [comment]
I previously got everything working except for openapi, which needed a gazel change. The rest were less complicated, and hopefully still are. I'll revisit that tomorrow.

I can provide you a patch or a git commit that you can cherry pick into this PR to make the bazel side happy.

**Comment by spxtr** [comment]
After #41106 goes in please rebase this. The gist of the genrule stuff is that we can create a macro called `api_group` that we call in place of the `go_library`:
```
api_group(
    name = "go_default_library",
    srcs = [
        "conversion.go",
        "doc.go",
        "register.go",
        "types.go",
    ],
    gen_deps = [
        "//pkg/api:go_default_library",
        "//pkg/api/v1:go_default_library",
    ],
    gen_types = [
        "conversion",
        "deepcopy",
        "defaulter",
    ],
    package = "pkg/apis/abac/v1beta1",
    tags = ["automanaged"],
    deps = [
        "//pkg/apis/abac:go_default_library",
        "//vendor:k8s.io/apimachinery/pkg/apis/meta/v1",
        "//vendor:k8s.io/apimachinery/pkg/conversion",
        "//vendor:k8s.io/apimachinery/pkg/runtime",
        "//vendor:k8s.io/apimachinery/pkg/runtime/schema",
    ],
)
```
This is `pkg/apis/apps/v1beta1/BUILD` from a few months ago. We can generate these with gazel, if we want, or manage them by hand. Either way, gazel manages the `srcs` and `deps` attributes. The problem I'm seeing right now is that I don't know an easy way to figure out what needs to go in `gen_deps`. I think it's everything that we're converting to/from, but I'm not sure about the details of how it determines what to do. For the present rules, I figured out what to put in `gen_deps` by just comparing the generated file against the checked in file, and adding the appropriate missing pieces until they matched.

**Comment by thockin** [comment]
Rebase, have not checked status since the push, but should fail for lack of
gentiles.

**Comment by spxtr** [comment]
OK, I can work from here.

**Comment by spxtr** [comment]
In this PR you remove `vendor/k8s.io/metrics/pkg/apis/custom_metrics/v1alpha1/zz_generated.*.go`. I'm not sure this is right, since I think the source of truth for these is actually in the `kubernetes/metrics` repo. At least, they don't exist in `staging/`.

Is this the behavior that we want?

**Comment by thockin** [comment]
re-pushed, let's see how Jenkins likes it.

**Comment by thockin** [comment]
This PR has been open for 9 months.  People are suffering because of the generated code, but this is all blocked by bazel, which approximately nobody uses.

We need to either get the bazel stuff fixed or take bazel builds off the critical path.

**Comment by mikedanese** [comment]
@thockin, I'm pretty sure @spxtr has made a lot of progress on this already. He asked a question that has not been answered yet. He's been OOO on vacation for 2 weeks but gets back next week.

**Comment by thockin** [comment]
The last question he asked was answered in a subsequent re-push.

I'm only frustrated as I watch PRs this week, right before code freeze, as usual, rebase, rebase, rebase, rebase.

**Comment by spxtr** [comment]
> The last question he asked was answered in a subsequent re-push.

Oh sorry, I didn't notice that. I thought that the re-push was a trivial rebase.

It might be interesting to run [this script](https://github.com/kubernetes/test-infra/blob/757dfae2452118c780ceda064ed2f0f2c25e0f5f/experiment/find-merge-conflicts.sh) now that we've removed the worst two generated files. @ixdy knows best how that works.

**Comment by ixdy** [comment]
FWIW, top 25 conflicting files on open PRs right now:
```
     18 pkg/api/v1/generated.pb.go
     17 docs/api-reference/extensions/v1beta1/definitions.html
     15 staging/src/k8s.io/client-go/pkg/api/v1/generated.pb.go
     15 pkg/generated/openapi/zz_generated.openapi.go
     13 docs/api-reference/v1/definitions.html
     11 vendor/BUILD
     10 pkg/api/v1/types_swagger_doc_generated.go
     10 docs/api-reference/batch/v1/definitions.html
     10 docs/api-reference/apps/v1beta1/definitions.html
      9 pkg/api/v1/types.generated.go
      8 pkg/api/v1/zz_generated.deepcopy.go
      8 docs/api-reference/batch/v2alpha1/definitions.html
      7 staging/src/k8s.io/client-go/pkg/api/zz_generated.deepcopy.go
      7 staging/src/k8s.io/client-go/pkg/api/v1/zz_generated.deepcopy.go
      7 staging/src/k8s.io/client-go/pkg/api/v1/types_swagger_doc_generated.go
      7 staging/src/k8s.io/client-go/pkg/api/v1/types.generated.go
      7 pkg/printers/internalversion/describe.go
      7 pkg/kubelet/kubelet.go
      7 pkg/api/zz_generated.deepcopy.go
      7 pkg/api/v1/zz_generated.conversion.go
      7 pkg/api/v1/types.go
      7 Godeps/Godeps.json
      6 test/test_owners.csv
      6 staging/src/k8s.io/client-go/pkg/apis/extensions/v1beta1/types.generated.go
      6 pkg/api/validation/validation_test.go
```

**Comment by spxtr** [comment]
> ```
>     15 pkg/generated/openapi/zz_generated.openapi.go
>     11 vendor/BUILD
> ```

We deleted the openapi file a full month ago. That means there are still 15 PRs that haven't been rebased in over a month. Similar story for `vendor/BUILD`.

**Comment by thockin** [comment]
I didn't want to tackle protobuf until the rest was in.

Do we need the API definitions.html in here?  What are they used for -
@mbohlool do you know?

**Comment by mbohlool** [comment]
@thockin api definitions.html is part of the swagger 1.2 that we are trying to deprecate. There could be still dependencies on it before deprecation so I would say, yes, keep it (and update it) there.

**Comment by spxtr** [comment]
I have all `zz_generated.deepcopy.go` generating with bazel. I autogenerate the rules with gazel, and it seems to be working nicely. If we want, I can open a PR to remove those right away, but then this PR will need to be updated again.

A problem shows up when I try to do conversion. If I make my gazel generator look at all the `// +k8s:conversion-gen=<import-path-of-peer-package>` and add the peers as dependencies then I still get horrible errors with missing conversion functions. It turns out that conversion-gen has [implicit dependencies](https://github.com/kubernetes/kubernetes/blob/afc4506c33063fe64c840f2696af42bfb996436c/cmd/libs/go2idl/conversion-gen/main.go#L56-L62) back to a handful of core packages. I think it might be a good idea to delete these defaults and be explicit where necessary. If I blindly add all these packages to every API group's peers, then I run into nontrivial dependency cycles.

It's certainly a solvable problem. My goal is that people who add or move API groups shouldn't need to touch BUILD files at all, it should be entirely done with gazel. I previously got the whole thing to work without this constraint by manually adding extra peers and such, but I didn't think this would be great for people who want to undertake the already painful experience of adding an API group. We can do it that way and then work on autogenerating them later, if we want.

**Comment by thockin** [comment]
@spxtr - any way to make progress on this? It is LITERALLY a year later.  I'm rebasing for the hundredth time and finding new things that have changed underneath me.  I am tired of this.  I love the idea of Bazel, but it's not paying off for me...

**Comment by thockin** [comment]
@caesarxuchao I need your advice on the staging export process after this - if the zz_generated files are not checked in, we need to generate and add them before the export happens.  Where does that happen?

**Comment by thockin** [comment]
@ixdy @mikedanese PTAL at bazel fail - the generated BUILD file is failing.

```
W0810 15:39:01.141] ERROR: /workspace/k8s.io/kubernetes/pkg/generated/openapi/BUILD:7:1: unexpected keyword 'deps' in call to openapi_library(name, tags, srcs, openapi_targets = [], vendor_targets = []).
W0810 15:39:01.143] ERROR: package contains errors: pkg/generated/openapi.
W0810 15:39:25.101] ERROR: /workspace/k8s.io/kubernetes/pkg/generated/openapi/BUILD:71:1: Target '//pkg/generated/openapi:def.bzl' contains an error and its package is in error and referenced by '//pkg/generated/openapi:package-srcs'.
```

**Comment by spxtr** [comment]
> @spxtr - any way to make progress on this? It is LITERALLY a year later.

For incremental progress we can do `zz_generated.deepcopy.go` right now. I ran the merge-conflict-finder script and the top 20 are
```
     12 hack/verify-flags/known-flags.txt
     12 api/openapi-spec/swagger.json
      9 pkg/kubelet/kubelet.go
      9 pkg/api/zz_generated.deepcopy.go
      9 pkg/api/v1/types.go
      8 staging/src/k8s.io/api/core/v1/generated.pb.go
      8 pkg/api/v1/types_swagger_doc_generated.go
      8 cmd/kubelet/app/server.go
      7 pkg/api/v1/generated.proto
      7 hack/make-rules/test-cmd-util.sh
      6 test/e2e_node/BUILD
      6 staging/src/k8s.io/client-go/pkg/api/v1/zz_generated.conversion.go
      6 staging/src/k8s.io/client-go/pkg/api/v1/types_swagger_doc_generated.go
      6 staging/src/k8s.io/client-go/pkg/api/v1/types.go
      6 staging/src/k8s.io/client-go/pkg/api/v1/generated.proto
      6 pkg/controller/daemon/daemoncontroller.go
      6 pkg/api/v1/zz_generated.deepcopy.go
      6 pkg/api/v1/zz_generated.conversion.go
      6 pkg/api/v1/types.generated.go
      6 pkg/api/v1/generated.pb.go
```
, so evidently that will help. I got conversion and default generated files partway complete, but they're not quite ready to go yet. I might've bitten off a bit more than I should've. I was hoping to make it so that adding a new api group would require no manual editing of BUILD files, but if we drop that requirement then we can do the rest of these with much less effort. When adding a new dependency or a new API group, I would then make the conversion-gen and default-gen programs print out an error when they notice it's missing.

I think @ixdy is interested in moving this forward.

**Comment by thockin** [comment]
I'm on hold waiting for the bazel experts to tell me what they need.  Manually editing a BUILD file is bad, but as long as something can error and tell users they need to do that, it might be livable.

**Comment by thockin** [comment]
Are we approaching this wrong?  Maybe making bazel do the regeneration is not the right answer.  Maybe `make` should call `bazel` after it has recalculated automatic deps and rebuilt BUILD files and whatever precursors we need to do anyway?

**Comment by spxtr** [comment]
While preparing my PR for deepcopy I found that the recent switch to gazelle invalidated much of my work in a non-trivial fashion. It's not clear how kazel and gazelle should play together when both need to touch the same rules. @mikedanese thinks that bazelbuild/rules_go#614 is the way forward.

> Maybe `make` should call `bazel` after it has recalculated automatic deps and rebuilt BUILD files and whatever precursors we need to do anyway?

As much as I hate the idea of this, it's actually a pretty good way to get generated files out of the repo in a way that lets us migrate to bazel-generation over time. We just need to be careful about the order in which we run things.

**Comment by cblecker** [comment]
I know the goal of moving away from checking in generated code is still there, but is this PR still relevant @thockin @spxtr ? It's currently frozen with no activity in 6+ months.

**Comment by spiffxp** [comment]
/remove-lifecycle frozen
/lifecycle rotten
/close
I'm closing this due to inactivity. Please /reopen if you wish to continue working on this

**Pull request closed without merging**
