### PR TITLE
Switch Fluentd to ES manifest back to YAML

### PR DESCRIPTION
**Pull request by satnam6502**
Now that the manifest YAML parsing is fixed I am changing the Fluentd to ES pod spec back to YAML.
I am also adding access to the secret `token-admin` which is going to be used in a follow up PR.

### CODE REVIEW

**Comment by satnam6502** [comment]
@a-robinson

**Comment by a-robinson** [comment]
LGTM - have you ran the relevant e2e test on this?

**Comment by satnam6502** [comment]
Not an e2e test -- I created a cluster, then ran a synthetic logger, and
then checked in Kibana to see if these logs were ingested (and if they were
then a lot of things had to work). Would you like me to run the e2e tests?

S

**Comment by a-robinson** [comment]
That's good enough, thanks :+1:

**Pull request merged**
