### PR TITLE
Automated cherry pick of #80954: Generate complete leader election record to resolve

### PR DESCRIPTION
**Pull request by dprotaso**
Cherry pick of #80954 on release-1.19.

#80954: Generate complete leader election record to resolve

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by ialidzhikov** [comment]
From parent PR:
/kind bug
/priority important-longterm

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by dprotaso** [comment]
thanks everyone!

**Pull request merged**
