### PR TITLE
Fix typo in types

### PR DESCRIPTION
**Pull request by xiaolou86**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37635)

### CODE REVIEW

**Comment by smarterclayton** [comment]
@k8s-bot ok to test

**Comment by xiaolou86** [comment]
@smarterclayton

**Comment by smarterclayton** [comment]
Please rebase and I'll run the tests again.

**Comment by thockin** [comment]
Needs a rebase.

**Pull request closed without merging**
