### PR TITLE
Automated cherry pick of #15351

### PR DESCRIPTION
**Pull request by caesarxuchao**
Cherry pick of #15351 on release-1.1.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@k8s-bot test this

**Comment by caesarxuchao** [comment]
@k8s-bot test this

**Comment by lavalamp** [comment]
LGTM

**Comment by wojtek-t** [comment]
@caesarxuchao please rebase

**Comment by caesarxuchao** [comment]
@k8s-bot test this

**Comment by lavalamp** [comment]
I need this to go in so that https://github.com/kubernetes/kubernetes/pull/15736 will work.

**Pull request merged**
