### PR TITLE
Dynamic Audit to Beta

### PR DESCRIPTION
**Pull request by pbarker**
/kind api-change
/sig auth

Promotes dynamic audit auditregistration API to beta
depends on https://github.com/kubernetes/kubernetes/issues/70816

```release-note
promote dynamic auditing auditregistration API to beta
```

### CODE REVIEW

**Comment by nikopen** [comment]
@pbarker @logicalhan Code Freeze is starting this Friday, can this be merged in the following 10 days?

**Comment by spiffxp** [comment]
/hold
v1.14 release lead here, this is a size/XXL PR that is attempting to land right before Code Freeze... are you _really sure_ this is a good idea?

**Comment by spiffxp** [comment]
/ok-to-test
(will likely fail because this needs rebase)

**Comment by soggiest** [comment]
@pbarker We're well into code freeze for 1.14 and there seems to be a lot of work associated with this pull. Can we move it to 1.15?

**Pull request closed without merging**
