### PR TITLE
Add a script to extract strings for translation and a sample of it's output

### PR DESCRIPTION
**Pull request by brendandburns**
@fabianofranz @deads2k @kubernetes/sig-cli-pr-reviews

### CODE REVIEW

**Comment by smarterclayton** [comment]
Any reason not to do this within the go2idl framework instead?  One advantage there is that we'd be able to extend it for more complicated transforms and search for more complicated syntactic patterns.

**Comment by brendandburns** [comment]
@smarterclayton I thought about it, the trick is that we have to rewrite the files, I don't think any of the existing tools re-write the original go source, they just parse it.

I wasn't sure how well the parsed AST would regenerate the same go code and I didn't want to introduce weird changes because of regenerating from AST.

I went back and forth between parsing vs. string replace, I settled on string replace because I knew it would do what I wanted with minimal fuss, vs speculatively doing more things but with more unknowns.

Anyway, if you are really insistent that we use the go parsing route, I can close this PR keep the script in my local repo and use it myself for generating PRs, but I'd rather get it to a place where other people can use it.

Thanks
--brendan

**Comment by fabianofranz** [comment]
Also, we should could add a sanity check to [cmd_sanity.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/sanity/cmd_sanity.go) to make sure that in future new commands or command changes are always externalizing strings. It runs on  `hack/verify-cli-conventions.sh` so it would prevent not externalized descriptions to be checked in.

**Comment by brendandburns** [comment]
@fabianofranz good idea, I'm happy to add that in a different PR.

@smarterclayton any thouughts on this? I'm happy to leave the script in my own repo for now and just send code changes if that's easier.

**Comment by brendandburns** [comment]
@smarterclayton friendly ping on this, I'd like to get some more strings extracted.

Thanks
--brendan

**Comment by brendandburns** [comment]
@smarterclayton friendly ping on this wrt to the python script...

**Comment by brendandburns** [comment]
@smarterclayton should I just skip the script for now?

**Comment by fabianofranz** [comment]
I'm ok with keeping the script, it's a support tool, not related to the core of the feature. @smarterclayton for final decision since he's the assignee here.

**Comment by smarterclayton** [comment]
I don't insist, we can always improve it later.

**Comment by brendandburns** [comment]
@fabianofranz rebased.

Thanks!
--brendan

**Comment by fabianofranz** [comment]
@k8s-bot verify test this

**Comment by fabianofranz** [comment]
@k8s-bot bazel test this

**Comment by fabianofranz** [comment]
@k8s-bot kops aws e2e test this

**Comment by fabianofranz** [comment]
@k8s-bot verify test this

**Comment by thockin** [comment]
@smarterclayton is reviewer, he can be approver, too :)

**Comment by brendandburns** [comment]
ping to @smarterclayton for LGTM + approval, I think this is ready to go...

@thockin given that I'm an OWNER, do we need approval here?

**Comment by bgrant0607** [comment]
@brendandburns Please also add an OWNERS file to translations/ at some point.

Also, this failed at the head of the submit queue, so the approved label was removed.

**Comment by brendandburns** [comment]
/lgtm
/approve

self approve+lgtm since this was just a rebase.

**Comment by brendandburns** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
