### PR TITLE
flowcontrol: print object type when bootstrapping flowschemas

### PR DESCRIPTION
**Pull request by vrutkovs**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Print object type when creating APF FlowSchema's as Kind may be unset

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

This fixes log lines when APF objects (`PriorityLevelConfiguration` and `FlowSchema`) are created. Currently its
```
strategy.go:270] "Successfully created " type="suggested" name="system"
strategy.go:270] "Successfully created " type="suggested" name="node-high"
strategy.go:270] "Successfully created " type="suggested" name="leader-election"
strategy.go:270] "Successfully created " type="suggested" name="workload-high"
strategy.go:270] "Successfully created " type="suggested" name="workload-low"
strategy.go:270] "Successfully created " type="suggested" name="global-default"
strategy.go:270] "Successfully created " type="suggested" name="system-nodes"
strategy.go:270] "Successfully created " type="suggested" name="system-node-high"
strategy.go:270] "Successfully created " type="suggested" name="probes"
...
```
This PR changes it to 
```
strategy.go:270] "Successfully created *v1.PriorityLevelConfiguration" type="suggested" name="system"
strategy.go:270] "Successfully created *v1.PriorityLevelConfiguration" type="suggested" name="node-high"
strategy.go:270] "Successfully created *v1.PriorityLevelConfiguration" type="suggested" name="leader-election"
strategy.go:270] "Successfully created *v1.PriorityLevelConfiguration" type="suggested" name="workload-high"
strategy.go:270] "Successfully created *v1.PriorityLevelConfiguration" type="suggested" name="workload-low"
strategy.go:270] "Successfully created *v1.PriorityLevelConfiguration" type="suggested" name="global-default"
strategy.go:270] "Successfully created *v1.FlowSchema" type="suggested" name="system-nodes"
strategy.go:270] "Successfully created *v1.FlowSchema" type="suggested" name="system-node-high"
strategy.go:270] "Successfully created *v1.FlowSchema" type="suggested" name="probes"
...
```

/cc @tkashem 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tkashem** [comment]
LGTM

/cc @MikeSpreitzer

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm
/approve
Thanks!

**Pull request merged**
