### PR TITLE
Exclude generated files from the static check

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Exclude generated files from the static check.
Ref: https://github.com/kubernetes/kubernetes/pull/106285#discussion_r748674035

#### Which issue(s) this PR fixes:

Ref #106405

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by thockin** [comment]
This file needs to go away  in https://github.com/kubernetes/kubernetes/pull/103723 but it seems compatible 

@hlee95 FYI

/approve
/lgtm

**Comment by BenTheElder** [comment]
should we perhaps exclude this particular lint about deprecated fields rather than all analysis on the files?

**Comment by SergeyKanzhelev** [comment]
> should we perhaps exclude this particular lint about deprecated fields rather than all analysis on the files?

Are any static checks on generated files actionable? If it can find any potential issues, maybe we can limit skip to only `SA1019` (deprecated fields).

**Comment by thockin** [comment]
We *know* there are a lot  of lint-flagged things in generated files.
Seems easier to just skip it all for now.

**Pull request merged**
