### PR TITLE
Revert "bump npd to v0.8.14"

### PR DESCRIPTION
**Pull request by tzneal**
#### What type of PR is this?

This reverts commit 7b44d73f73f2a745666e4276b24fd98b7d002110 in PR https://github.com/kubernetes/kubernetes/pull/120194
/kine failing-test

#### What this PR does / why we need it:

The NPD v0.8.14 image seems bad, the arm64 version has an x86_64 node-problem-detector binary and its failing all arm64 tests.

https://storage.googleapis.com/k8s-triage/index.html?sig=node&job=ec2&xjob=windows#9f7f7053b14ff9d31a67

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tzneal** [comment]
```
$ crane manifest registry.k8s.io/node-problem-detector/node-problem-detector:v0.8.14
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
  "manifests": [
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "digest": "sha256:98034f47cdfa331105265f025c0dbff781e8c15436f726eceacec52644a7c014",
      "size": 1488,
      "platform": {
        "architecture": "amd64",
        "os": "linux"
      }
    },
    {
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "digest": "sha256:38ddabcad5a96bfb4af3bf6e61348198f7da4441b08a17c9ad0ea9bdb3a8689a",
      "size": 1488,
      "platform": {
        "architecture": "arm64",
        "os": "linux"
      }
    }
  ]
}


$ crane manifest registry.k8s.io/node-problem-detector/node-problem-detector@sha256:38ddabcad5a96bfb4af3bf6e61348198f7da4441b08a17c9ad0ea9bdb3a8689a
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
  "config": {
    "mediaType": "application/vnd.docker.container.image.v1+json",
    "digest": "sha256:a0e50a81a0e3fb03c4012573eb3416f450af62a279a647dde1e3ccc83ca5d8b5",
    "size": 2676
  },
  "layers": [
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "digest": "sha256:f91cc52e2c97c480189bb2da87653dd9abfe2679c36fc41b9db68878827748b4",
      "size": 25322200
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "digest": "sha256:86c650b37460bdd568db653fe0ea8d628fe802bb15b47c5c2879fb2fd80b1d50",
      "size": 3149001
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "digest": "sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1",
      "size": 32
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "digest": "sha256:a19a5af3e67a96f03e92287598725e391cf7df49799ceb0f1abc1c88fdfb8e82",
      "size": 20213297
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "digest": "sha256:f239dff246d22a7de3be61ff3679722e66982089630b0591a057d01889f0c986",
      "size": 13346251
    },
    {
      "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
      "digest": "sha256:cad51d6b0d0b6b9ac3b3f1a0051eb93e35d1b84c5e25ad2482f8b71a49e58a01",
      "size": 5852
    }
  ]
}

$ crane blob registry.k8s.io/node-problem-detector/node-problem-detector@sha256:a19a5af3e67a96f03e92287598725e391cf7df49799ceb0f1abc1c88fdfb8e82 | tar -zxv
node-problem-detector

$ file node-problem-detector
node-problem-detector: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=bd9bd59069612b94e84e1c60d73ebf61d618cd44, for GNU/Linux 3.2.0, with debug_info, not stripped
```

**Comment by hakman** [comment]
Ref: https://github.com/kubernetes/node-problem-detector/issues/797

/kind failing-test
/priority important-soon
/lgtm

**Comment by liggitt** [comment]
As a follow up, can we remove npd from this folder? This is only for CI tests and we should be removing things from here wherever possible instead of continuing to bump them to new versions.

**Comment by pacoxu** [comment]
> As a follow up, can we remove npd from this folder? This is only for CI tests and we should be removing things from here wherever possible instead of continuing to bump them to new versions.

Do you mean removing the `cluster/addons/node-problem-detector`?  The version bump is also for the CI tests. 

The NPD is not been that active in recent years. Since v0.8.0 was released on Oct 31, 2019, there has been no minor release. Only some patch releases: only 2 releases a year after 2021 Sept.

**Comment by liggitt** [comment]
> Do you mean removing the `cluster/addons/node-problem-detector`? The version bump is also for the CI tests.

Yes, unless that test is exercising something inside k/k, it shouldn't live in this dir.

**Pull request merged**
