### PR TITLE
Add fluentd monitoring to fluentd-gcp image

### PR DESCRIPTION
**Pull request by crassirostris**
Right now we are not able to monitor the state of fluentd in cluster, which may result in logging subsystem quietly failing. This PR tries to address that problem by introducing the fluentd container monitoring:

* fluentd internal metrics, like number of buffers and number of data in buffers
* `logging_line_count`, number of lines, read by fluentd from application containers' logs
    * Has `tag` label, corresponding to the fluentd tag of the entry
* `logging_entry_count`, number of entries, emitted to the output plugin
    * With label `component` set to `container`, generated by application containers
    * With label `component` set to `system`, generated by system components like kubelet, docker, scheduler, etc.
    * Has `tag` label, corresponding to the fluentd tag of the entry

CC @fabxc @igorpeshansky @edsiper

### CODE REVIEW

**Comment by Crassirostris** [comment]
Waiting for https://github.com/kubernetes/kubernetes/pull/41564 to be merged

**Comment by Crassirostris** [comment]
CC @qingling128

**Comment by piosz** [comment]
@Crassirostris can you please paste sample Prometheus output here?

**Comment by piosz** [comment]
LGTM

**Comment by Crassirostris** [comment]
@k8s-bot cross build this
@k8s-bot unit test this
@k8s-bot non-cri e2e test this
@k8s-bot gci gce e2e test this
@k8s-bot cvm gce e2e test this

**Comment by Crassirostris** [comment]
@k8s-bot unit test this

**Comment by Crassirostris** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
