### PR TITLE
Automated cherry pick of #65342: update NPD version to v0.5.0 for gci

### PR DESCRIPTION
**Pull request by dashpole**
Cherry pick of #65342 on release-1.11.

#65342: update NPD version to v0.5.0 for gci

### CODE REVIEW

**Comment by dashpole** [comment]
This is to help mitigate https://github.com/kubernetes/kubernetes/issues/45419 on gci, by creating a condition when the unregister_netdevice error occurrs frequently.

**Comment by dashpole** [comment]
/release-note-none
/assign Lantao Liu
for lgtm
/assign Vish Kannan
for approval
/assign @foxish 
for milestone and cherrypick approval

**Comment by foxish** [comment]
Is this needed for 1.11.0?

**Comment by jberkus** [comment]
This needs a SIG, and then that sig needs to approve it ... before tommorrow mid-morning Pacific time.

You're probably looking at 1.11.1.

**Comment by dashpole** [comment]
This can definitely wait for 1.11.1

**Comment by dashpole** [comment]
/sig gcp
probably makes more sense actually

**Comment by foxish** [comment]
@dashpole, it would be good to get approval here to target this fix for 1.11.1.

**Comment by dashpole** [comment]
@foxish yes, it should be ready
/hold cancel

**Pull request merged**
