### PR TITLE
remove max pods from e2e test

### LINKED ISSUE #85814: [Failing Test] gce-cos-k8sbeta-serial (ci-kubernetes-e2e-gce-cos-k8sbeta-serial)
**Which jobs are failing**:
gce-cos-k8sbeta-serial (ci-kubernetes-e2e-gce-cos-k8sbeta-serial)

**Which test(s) are failing**:
Various CSI Driver tests.

**Since when has it been failing**:
Earliest observed: 11/17
Consistently failing since: 11/29

**Testgrid link**:
https://testgrid.k8s.io/sig-release-1.17-informing#gce-cos-k8sbeta-serial

**Reason for failure**:
```
I1202 09:51:54.336] Dec  2 09:51:54.335: INFO: Define cluster role csi-gce-pd-resizer-role-volume-expand-4470
I1202 09:51:54.372] Dec  2 09:51:54.372: INFO: creating *v1.ClusterRoleBinding: csi-gce-pd-resizer-binding-volume-expand-4470
I1202 09:51:54.409] Dec  2 09:51:54.409: INFO: creating *v1.ClusterRoleBinding: psp-csi-controller-driver-registrar-role-volume-expand-4470
I1202 09:51:54.445] Dec  2 09:51:54.444: INFO: creating *v1.DaemonSet: volume-expand-4470/csi-gce-pd-node
I1202 09:51:54.482] Dec  2 09:51:54.482: INFO: creating *v1.StatefulSet: volume-expand-4470/csi-gce-pd-controller
I1202 09:52:54.742] Dec  2 09:52:54.741: FAIL: waiting for csi driver node registration on: timed out waiting for the condition
I1202 09:52:54.743] 
I1202 09:52:54.744] Full Stack Trace
I1202 09:52:54.744] k8s.io/kubernetes/test/e2e/storage/drivers.(*gcePDCSIDriver).PrepareTest(0xc00061fa20, 0xc000b6c780, 0x101000000000000, 0x7d1d6e0)
I1202 09:52:54.744] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/drivers/csi.go:452 +0x204
I1202 09:52:54.744] k8s.io/kubernetes/test/e2e/storage/testsuites.(*volumeExpandTestSuite).defineTests.func2()
skipped 179 lines unfold_more
I1202 09:52:55.928] Dec  2 09:52:55.927: INFO: 
I1202 09:52:55.928] Latency metrics for node test-34cf3ed1e3-minion-group-h8g8
I1202 09:52:55.929] Dec  2 09:52:55.927: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
I1202 09:52:55.965] STEP: Destroying namespace "volume-expand-4470" for this suite.
I1202 09:52:56.002] 
I1202 09:52:56.003] • Failure [62.488 seconds]
I1202 09:52:56.003] [sig-storage] CSI Volumes
I1202 09:52:56.004] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/utils/framework.go:23
I1202 09:52:56.004]   [Driver: pd.csi.storage.gke.io][Serial]
I1202 09:52:56.004]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/csi_volumes.go:55
I1202 09:52:56.004]     [Testpattern: Dynamic PV (default fs)(allowExpansion)] volume-expand
I1202 09:52:56.004]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go:100
I1202 09:52:56.005]       Verify if offline PVC expansion works [It]
I1202 09:52:56.005]       /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go:159
I1202 09:52:56.005] 
I1202 09:52:56.005]       Dec  2 09:52:54.741: waiting for csi driver node registration on: timed out waiting for the condition
I1202 09:52:56.005] 
I1202 09:52:56.006]       /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/drivers/csi.go:452
I1202 09:52:56.006] ------------------------------
I1202 09:52:56.006] {"msg":"FAILED [sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)(allowExpansion)] volume-expand Verify if offline PVC expansion works","total":725,"completed":14,"skipped":271,"failed":1,"failures":["[sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)(allowExpansion)] volume-expand Verify if offline PVC expansion works"]}
```
**Anything else we need to know**:
/cc @kubernetes/ci-signal 

/milestone v1.17
/sig storage
/priority critical-urgent

### PR DESCRIPTION
**Pull request by ahg-g**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

Remove "validates MaxPods limit number of pods that are allowed to run [Slow] e2e test fails frequently" e2e test because we can't assert the state of the cluster before starting the test. 

We already have [unit test coverage](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/noderesources/fit_test.go#L362-L414) for max pod predicate, and there is no reason to have an e2e test for that.

**Which issue(s) this PR fixes**:
Fixes #85814

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cc @Huang-Wei

### CODE REVIEW

**Comment by damemi** [comment]
Do you have a link to the existing test, just for reference? Is it a unit or integration test?

**Comment by ahg-g** [comment]
> Do you have a link to the existing test, just for reference? Is it a unit or integration test?

I updated the description with the link, and here it is: https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/noderesources/fit_test.go#L362-L414

**Comment by Huang-Wei** [comment]
/lgtm

As @ahg-g mentioned, we already have good coverage on UT. Moreover, #85900 is created to add a supplemental integration test, if needed.

**Pull request merged**
