### PR TITLE
Add comments in several hack/verify-*.sh

### PR DESCRIPTION
**Pull request by hase1128**
**What type of PR is this?**
/kind cleanup
/kind documentation

**What this PR does / why we need it**:
Add or update the comments for the following scripts. (a-f of verify-XXX.sh)

hack/verify-all.sh
hack/verify-api-groups.sh
hack/verify-bazel.sh
hack/verify-boilerplate.sh
hack/verify-cli-conventions.sh
hack/verify-codegen.sh
hack/verify-conformance-requirements.sh
hack/verify-description.sh
hack/verify-external-dependencies-version.sh

**Which issue(s) this PR fixes**:
ref:#86597

**Special notes for your reviewer**:
/cc @fejta

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by tanjunchen** [comment]
needs-ok-to-test

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
