### PR TITLE
fix golint for pkg/volume/host_path

### PR DESCRIPTION
**Pull request by mysunshine92**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:

> /kind cleanup

**What this PR does / why we need it**:
fix golint errors in pkg/volume/host_path

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
refer #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by vishh — APPROVED** [review]
/lgtm
/approve

**Comment by mysunshine92** [comment]
cc @gnufied @deads2k
would you like to help adding a approved label ? Thanks!

**Comment by mysunshine92** [comment]
cc @gnufied @deads2k

**Comment by mysunshine92** [comment]
cc @gnufied @deads2k can you help to add approved label? thank you

**Comment by mysunshine92** [comment]
cc @dims @gnufied @deads2k can you help to add approved label? thank you

**Comment by mysunshine92** [comment]
cc @dims @gnufied @deads2k can you help to add approved label? thank you

**Comment by dims** [comment]
@mysunshine92 can you please rebase?

/unassign

**Comment by mysunshine92** [comment]
> 
> 
> @mysunshine92 can you please rebase?
> 
> /unassign

thank you, today i will rebase it

**Comment by mysunshine92** [comment]
ping @dims

**Comment by mysunshine92** [comment]
ping @dims

**Comment by mysunshine92** [comment]
ping @deads2k

**Comment by mysunshine92** [comment]
ping @deads2k @dims

**Comment by mysunshine92** [comment]
ping @deads2k @dims

**Comment by mysunshine92** [comment]
ping @deads2k @dims
please add an approved label ,thanks.

**Comment by dims** [comment]
/assign @sttts 

@mysunshine92 if you look at the bot comment, you need an approver from cmd/kube-controller-manager/OWNERS to approve ... let's try Stefan :)

**Comment by mysunshine92** [comment]
ping @lavalamp @sttts 
please add an approved label,thanks.

**Comment by mysunshine92** [comment]
> 
> 
> /assign @sttts
> 
> @mysunshine92 if you look at the bot comment, you need an approver from cmd/kube-controller-manager/OWNERS to approve ... let's try Stefan :)

thank you for your help, i have tried.

**Comment by mysunshine92** [comment]
ping @lavalamp

**Comment by mysunshine92** [comment]
cc @mikedanese @lavalamp @sttts 
please add an approved lable , thanks.

**Comment by mysunshine92** [comment]
cc @mikedanese @lavalamp @sttts
please add an approved lable , thanks.

**Pull request merged**
