### PR TITLE
Automated cherry pick of #101737: Use CSI driver to determine unique name for migrated in-tree

### PR DESCRIPTION
**Pull request by Jiawei0227**
Cherry pick of #101737 on release-1.20.

#101737: Use CSI driver to determine unique name for migrated in-tree

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
