### PR TITLE
scheduler: make algorithm source an option

### LINKED ISSUE #85140: Make algorithm source an option of scheduler.New
**What would you like to be added**:
Make algorithm source an option of `scheduler.New` and add the default one.

**Why is this needed**:

To easy the usage of `scheduler.New`. Today, users have to manually create an algorithm source when they only want the default behavior

https://github.com/kubernetes/autoscaler/pull/2515#discussion_r344750419

/sig scheduling
/help
/good-first-issue

### PR DESCRIPTION
**Pull request by hypnoglow**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Changes scheduler.New so that the algorithm source is moved from the parameter to an option. The default algorithm source is a source with the DefaultProvider.

**Which issue(s) this PR fixes**:

Fixes #85140

**Special notes for your reviewer**:

Raised on https://github.com/kubernetes/autoscaler/pull/2515#discussion_r344750419

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

---

/priority backlog
/sig scheduling

### CODE REVIEW

**Comment by ahg-g** [comment]
/assign @msau42 


for test/OWNERS changes.

**Comment by alculquicondor** [comment]
Please call `./hack/update-bazel.sh`

**Comment by hypnoglow** [comment]
> Please call ./hack/update-bazel.sh

Done

**Pull request merged**
