### PR TITLE
Use locally built kubernetes binaries in charms

### PR DESCRIPTION
**Pull request by mbruzek**
We added the functionality to build Kubernetes binary files on your laptop and have the charm deploy those binary files with the charms in Juju.  That involved a few changes in the cluster/juju directory and makes it much easier for a developer to deploy their changes and see that in Kubernetes.

### CODE REVIEW

**Comment by thockin** [comment]
Can you please sort out the CLA?

**Comment by mbruzek** [comment]
We have signed the CLA.  We have a corporate CLA and my company is Canonical

**Comment by erictune** [comment]
ok to test

**Comment by erictune** [comment]
@mbruzek 
I see that these commits are signed with what looks like a personal email, rather than a corporate email address. I'm guessing you need to amend the commits so that they are signed with your corporate email, to satisfy our CLA robot.  Something like  `git commit --amend --author "Matt Bruzek <yournamehere@ubuntu.com>"`.

Alternatively, you might be able to get whoever setup your CLA to add your personal email to the list of covered committers.  But I'm not sure about that.

**Comment by erictune** [comment]
@thockin since this PR updates a distro to be closer to the core distro, and since it can't affect any of the core distro functionality, I think this PR is exempt from the feature freeze.

**Comment by erictune** [comment]
LGTM once CLA sorted out.

**Comment by erictune** [comment]
LGTM. needs rebase.

**Pull request merged**
