### PR TITLE
Enable deployments by default

### PR DESCRIPTION
**Pull request by janetkuo**
Enable deployments by default, enable deployments in kubectl run, and update related docs/scripts.

Addresses #15313

cc @bgrant0607 @nikhiljindal @ironcladlou @kargakis @kubernetes/sig-config @kubernetes/kubectl @madhusudancs

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM, but waiting on #20389 and the rename of uniqueLabelKey before merging.

**Comment by janetkuo** [comment]
e2e test failed because a test assumes `kubectl run` should generate rc. Modified the test for rc and add another test for deployment.

**Comment by bgrant0607** [comment]
Please rebase. I think we can enable Deployment now.

cc @madhusudancs

**Comment by janetkuo** [comment]
@bgrant0607 rebased.

**Comment by bgrant0607** [comment]
LGTM

**Comment by ghodss** [comment]
:fireworks:

**Pull request merged**
