### PR TITLE
fix a flag replace of container-runtime=remote

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
caused by https://github.com/kubernetes/kubernetes/pull/112000/
#### Which issue(s) this PR fixes:

maybe relate to https://github.com/kubernetes/kubeadm/issues/2750

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

thanks for catching this @pacoxu

**Comment by neolit123** [comment]
> Fixes https://github.com/kubernetes/kubeadm/issues/2750

i am a bit confused thought. what we saw on the failing test was one node etcd / kubelet not working, but the rest worked. also other "latest" test jobs work fine, i think.

would this really fix it?

**Comment by pacoxu** [comment]
> i am a bit confused thought. what we saw on the failing test was one node etcd / kubelet not working, but the rest worked. also other "latest" test jobs work fine, i think.
> 
> would this really fix it?

I reviewed recent pr. Only this one maybe related. And I found the kubelet crash. Maybe the etcd pod on the second ans third node exit after kubelet exit. And the etcd cluster has only one etcd member then and got that error. Not quite sure but is potential probelm.

**Pull request merged**
