### PR TITLE
Remove broken link

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Xiang Dai <long0dai@foxmail.com>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This link is broken.

```
$ curl https://kubernetes-site.appspot.com/UA-36037335-10/GitHub/CHANGELOG.md
Go 1.9 is no longer available.  Please refer to https://goo.gl/aESk5L for more information.
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by daixiang0** [comment]
ping @neolit123

**Comment by neolit123** [comment]
Hi, try asking in #sig-release on k8s slack.

**Comment by justaugustus** [comment]
This has already been fixed in https://github.com/kubernetes/kubernetes/pull/93975.
/close

**Pull request closed without merging**
