### PR TITLE
Automated cherry pick of #109834: integration: refactor and split scheduler tests 

### PR DESCRIPTION
**Pull request by aojea**
Cherry pick of #109834 on release-1.24.

#109834: integration: refactor and split scheduler tests

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
the main goal of this is to split up the expensive scheduler integration test package which is timing out at HEAD (see timeouts at https://testgrid.k8s.io/sig-release-1.24-blocking#integration-1.24&width=20)

/lgtm
/approve
/kind failing-test

**Comment by alculquicondor** [comment]
Thanks
/lgtm

**Comment by aojea** [comment]
ping @kubernetes/release-managers

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by aojea** [comment]
do we want to try to get this into 1.23?

**Comment by aojea** [comment]
it seems 1.23 has a different issue https://testgrid.k8s.io/sig-release-1.23-blocking#integration-1.23&width=20
Reporteed https://github.com/kubernetes/kubernetes/issues/114259

**Comment by liggitt** [comment]
on 1.23, the job has been green since the backport fix for https://github.com/kubernetes/kubernetes/issues/114259 merged a couple days ago

**Pull request merged**
