### PR TITLE
Refactor OpenStack cloud provider

### LINKED ISSUE #51687: Refactor OpenStack cloud provider
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
Currently the codes of openstack cloud provider are confusion:
1.openstack loadbalancer support v1 and v2, they are  in the same file
2.openstack volume support v1 and v2, they are also in the same file. 
3.some name codes which is not related to cloud provider interface in openstack.go file: 
    the codes of zone, the codes of parsing cloud provider config, the codes of getting server,
    the codes of getting server's ips, the codes of getting server's interfaces and so on.
4.there are many common function, but there is no common util file.

**What you expected to happen**:
For the above, do the following improvements:
1.split openstack loadbalancer and openstack volume by version, in the future we will also support V3, it is better to split them into different files.
2.simple openstack.go by cloud.go
3.extract common functions into common util file, 

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
Nope

/assign

### PR DESCRIPTION
**Pull request by FengyunPan**
**What this PR does / why we need it**:
1.split loadbalancer and volume by version
2.extract Zones's function into openstack_zones.go
3.Simplify openstack.go by the Interface of cloud.go
4.extract common functions into common util file

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #51687

**Special notes for your reviewer**:

**Release note**:
```release-note
Refactor OpenStack cloud provider
```

### CODE REVIEW

**Comment by dims** [comment]
@FengyunPan Let's do this when 1.9 opens up? I like the idea :)

**Comment by FengyunPan** [comment]
@dims Ok, I agree with 1.9

**Review by anguslees — COMMENTED** [review]
If we're doing a big rename, we should drop the `openstack_` prefix in front of all of these filenames.  It adds no value, since they're in an `openstack/` dir already.

**Comment by dims** [comment]
/unassign @dims 

please add me back. (travelling next week)

**Comment by dims** [comment]
@FengyunPan can we do this early in 1.10 please?

**Pull request closed without merging**
