### PR TITLE
test/e2e: Improve kubectl subresource e2e test

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
We now get structured output using jsonpath for the name and version fields of the node object and then compare the outputs.

#### Which issue(s) this PR fixes:

Follow up from https://github.com/kubernetes/kubernetes/pull/116619

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/2590-kubectl-subresource
```
/assign @soltysh 
/cc @liggitt @nikhita 
/hold

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by dims** [comment]
/lgtm
/approve

way better! please feel free to remove hold when CI goes green.

**Comment by aojea** [comment]
/hold cancel

thanks

**Pull request merged**
