### PR TITLE
Factor PassiveClock out of clock.Clock

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test

/kind feature

> /kind flake

**What this PR does / why we need it**:
PassiveClock has the subset of Clock functionality that only involves
reading the clock.  Identifying this subset makes it possible to write
packages that are more clearly easy to test.

When a package is coded against Clock rather than PassiveClock this
adds two problems for the unit test functions.  One is that Clock
provides no way for the test function to know when the next activity
is scheduled for.  That could be added to FakeClock relatively easily.
The second problem is that when a package uses channels to schedule
future activity, once the Clock has advanced to such a future time the
Clock (and hence the test function) does not get informed when that
activity has completed.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
This PR originally did two things, factor Clock and introduce EventClock.  You can see in the commentary why this PR has been reduced in scope.  You can see the current version of EventClock in https://github.com/kubernetes/kubernetes/blob/feature-rate-limiting/staging/src/k8s.io/apiserver/pkg/util/clock/event_clock.go and a use in https://github.com/kubernetes/kubernetes/blob/feature-rate-limiting/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/fq_test.go

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by mikedanese** [comment]
Can you point to some places where this would be used?

**Comment by MikeSpreitzer** [comment]
I am thinking of using FakeEventClock in testing https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190228-priority-and-fairness.md .  The implementation needs only a PassiveClock.  The outline of an example test would be to use FakeEventClock::EventAfterTime to schedule a bunch of request arriveals, run the code, and evaluate how the requests got served.

**Comment by mikedanese** [comment]
I'm hesitant to export more interfaces from this package, and hesitant to export more structs without knowing they will be used in multiple places. You could test run this by defining `passiveClock` where you intend to use it. clock.RealClock would implement it so you can still use RealClock in production, but replace the implementation with whatever you need in tests. Also see:

https://github.com/golang/go/wiki/CodeReviewComments#interfaces

**Comment by yue9944882** [comment]
this will be helping testing on fair-queuing systems, the technique requires fine-grained virtual clock implementation. @lavalamp

**Comment by lavalamp** [comment]
So this package is mostly intended to follow the go `time` standard library package, so you can test code using that with minimal changes.

Factoring out the passive clock makes some sense, even given that, since things using only those functions are definitely easier to test.

I am not sure the EventClock makes sense here, though, since it's inventing a usage pattern not in the standard library (to be clear, this is a criticism of the untestable standard library interface, not the code in this PR).

Can we put this in a subpackage closer to the fair-queueing code?

**Comment by MikeSpreitzer** [comment]
@lavalamp : are you suggesting to modify apimachinery's clock package to factor our PassiveClock, and also introduce FakeEventClock closer to its initial usage?

**Comment by lavalamp** [comment]
Yes, PassiveClock seems fine here, EventClock and friends probably belong
near their usage.

**Review by logicalhan — APPROVED** [review]
/lgtm

**Pull request merged**
