### PR TITLE
Added unit test cases for the public methods of pkg/util/taints.go

### LINKED ISSUE #49384: Missing unit tests in /pkg/api/v1helper & pkg/util/taints for some functions.
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

**What happened**:
While working on #46514, I noticed that some fn's like AddorUpdateTaints, DeleteTaintsByKey etc. are missing unit tests.

**What you expected to happen**:
Write unit tests for them.

### PR DESCRIPTION
**Pull request by xingzhou**
Added unit test cases for the public methods of pkg/util/taints.go

Fixed #49384, related to #49699 

**Release note**:
```
None
```

### CODE REVIEW

**Comment by thockin** [comment]
Assigning mike as original author.

**Comment by xingzhou** [comment]
@mikedanese, I've rebased the code, please take a look, thanks for your time.

@brendanburns or @thockin, would you please help approve the PR, thanks!

**Comment by xingzhou** [comment]
@brendanburns, would you please help to approve the PR? thanks

**Comment by mikedanese** [comment]
This needs approval.

**Comment by xingzhou** [comment]
Have rebased the code to the latest master branch, please take a look, thx

**Comment by mikedanese** [comment]
I'm just going to approve this, it's been waiting too long and it's just a test addition.

**Pull request merged**
