### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by erictune**

### CODE REVIEW

**Comment by erictune** [comment]
@caesarxuchao please take a look

**Comment by erictune** [comment]
I am merging now to fix build but please review to see if this fix is right.

**Comment by caesarxuchao** [comment]
I can't tell if the generated code is correct... Could you run the unit test in `cmd/libs/go2idl/client-gen/testoutput`? If that passes, the change is good.

Also, why do you need to whitelist the /testdata? The generated code should pass the verification script since no one is change the APIs defined in that directory.

**Comment by erictune** [comment]
Test passes.  Now that I think about it, I don't know why the whitelist is needed either.  I'll send a PR to take that out.

**Pull request merged**
