### PR TITLE
Refactor platform deps

### PR DESCRIPTION
**Pull request by pmgk07**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Refactor platform specific code into separate files (*_linux.go / *_windows.go / *_others.go)

#### Which issue(s) this PR fixes:

Partial cleanup, part of #60338

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pmgk07** [comment]
@chrishenzie Did the `pull-kubernetes-e2e-...` tests fail because I don't have permissions to schedule tests ? Appears unrelated to my change but I could be wrong.

**Comment by chrishenzie** [comment]
No I don't believe that would cause it. Retriggering:
/retest

**Comment by pmgk07** [comment]
@chrishenzie Looks like it progressed more than when I triggered it. I couldn't understand the logs of this particular suite - pull-kubernetes-e2e-gce-storage-slow. Could it be related to this issue ? https://github.com/kubernetes/kubernetes/issues/106720

**Comment by chrishenzie** [comment]
@pmgk07 It looks like this test suite didn't complete in the allotted window of 80m so it timed out.
```
W0321 20:16:29.143] 2022/03/21 20:16:29 process.go:199: Interrupt after 1h20m0s timeout during ./hack/ginkgo-e2e.sh --ginkgo.focus=\[sig-storage\].*\[Slow\] --ginkgo.skip=\[Driver:.gcepd\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8 --report-dir=/workspace/_artifacts --disable-log-dump=true. Will terminate in another 15m
...
W0321 20:25:36.947] subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--build=quick', '--stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e      2e-gce-storage-slow', '--up', '--down', '--test', '--provider=gce', '--cluster=e2e-0962f09f26-390e9', '--gcp-network=e2e-0962f09f26-390e9', '--extract=local', '--gcp-node-image=gci', '--gcp-zone=us-west1-b', '--ginkgo-parallel=30', '--test_args=--      ginkgo.focus=\\[sig-storage\\].*\\[Slow\\] --ginkgo.skip=\\[Driver:.gcepd\\]|\\[Serial\\]|\\[Disruptive\\]|\\[Flaky\\]|\\[Feature:.+\\] --minStartupPods=8', '--timeout=80m')' returned non-zero exit status 1
```
/retest

**Comment by pmgk07** [comment]
Thanks @chrishenzie !

**Pull request closed without merging**
