### PR TITLE
CronJob: cleanup legacy ScheduledJob vars,docs

### PR DESCRIPTION
**Pull request by ideapark**
Signed-off-by: Zhou Peng <p@ctriple.cn>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by iobuf** [comment]
/assign @liggitt 
Please review this PR

**Comment by iobuf** [comment]
/assign @Joseph-Irving
Please review this PR

**Comment by Joseph-Irving** [comment]
I've done a review, all looks good to me!
Will need approval from api/cronjob approvers
/lgtm

**Comment by iobuf** [comment]
/assign @thockin 
Please review this PR

**Pull request merged**
