### PR TITLE
Amend some markdown and other errors in **easyrsa** section 

### PR DESCRIPTION
**Pull request by hw-qiaolei**
This PR is related to the closed one #13078

I am sorry to make simple things complex so I closed the old one and open a new one. Please check, thanks.

Amend two markdown errors in authentication.md.
1, amend ordered list display error by entering a newline after the first sentence
2, add two backticks to make `"@`date +%s`"` display correctly

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot ok to test

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by hw-qiaolei** [comment]
@wojtek-t Please check again with this PR. Besides of fixing the Jenkins GCE e2e test failure, I also fixed some errors in the **easyrsa** section. As follows:

1, fix Jenkins GCE e2e failure, mainly for markdown errors;
2, change `"${MASTER_IP}"`  to `"IP:${MASTER_IP}"` to keep align with `make-ca-cert.sh`
3, change `/pki/` to `pki/` for the generated certs/key
4, other tiny improvements

**Comment by brendandburns** [comment]
closing and re-opening to trigger shippable...

**Pull request merged**
