### PR TITLE
optimize EventRateLimit admission plugin

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

optimize admission eventRateLimit, not wait until all limitEnforcers accept. Return immediately when one enforcers not accept. Improve apiserver performance at some degree.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
@staebler ptal.

**Comment by staebler** [comment]
An enforcer has two jobs to do as part of accepting an event. The first is to ensure that the event is within the limits imposed by the enforcer. The second is to record the event against the appropriate limits for the enforcer. If the admission control short-circuits when an enforcer rejects an event, then subsequent enforcers in the list will not get a chance to perform the second job.

In other words, the admission control is designed so that an event counts against the limits for every enforcer regardless of whether one of the enforcers rejects the event. @deads2k felt strongly during his review of the initial PR for this admission control that a rejected event should either count against the limits of all enforcers or count against the limit of no enforcers. If we want to short-circuit the admission control when an event is rejected, then more work needs to be done to ensure that the event does not count against the limits of any of the enforcers that have already accepted the event.

**Comment by deads2k** [comment]
Well remembered. Doing it that way (count against all) produces consistent counting behavior

**Comment by hzxuzhonghu** [comment]
@staebler @deads2k I know. But I have a doubt, what's the benefit by `Doing it that way (count against all) produces consistent counting behavior`? In other words, what if we do not count against all?

**Comment by deads2k** [comment]
> @staebler @deads2k I know. But I have a doubt, what's the benefit by Doing it that way (count against all) produces consistent counting behavior? In other words, what if we do not count against all?

If you don't count against all, then the counts for the later items don't accurately reflect the true number of events that matched, so they end up enforcing incorrectly.  There are two valid choices: count against all or count against none.  Count against all is easier and valid, so we chose that.

**Comment by hzxuzhonghu** [comment]
Thanks for your explanation @deads2k .  If I comprehend no error, currently the limitEnforcers all have execute `TryAccept` when a new request arrive.  But if an enforcer accept failed, it does not count, others accept success all count, this is not consistent, and it doesn't matter. We do not need strong consistency here.

**Pull request closed without merging**
