### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by xiezongzhe**
kubadm->kubeadm

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
/lgtm
thanks.

**Comment by neolit123** [comment]
/check-cla
@xiezongzhe please sign the CLA as instructed in the second post.

**Comment by xiezongzhe** [comment]
I have signed it

**Comment by nikhita** [comment]
/assign @fabriziopandini 
for approval

**Review by luxas — APPROVED** [review]
/approve
Thanks @xiezongzhe!
Please rebase this PR, and when you do that, see if you find more typo fixes at the same time to fix :smile:

**Comment by fabriziopandini** [comment]
@xiezongzhe 
Please rebase

I've noticed you've submitted a few of typo related PRs and probably now understand how the process works. What do you think about working on larger changes? We like to see people grow as they contribute and we think you're ready to take on more complex tasks

**Comment by chuckha** [comment]
/close

this is already fixed

https://github.com/kubernetes/kubernetes/commit/8c13df8b6ac35951f6536d90a73dce012de9742f#diff-a466e16a4b5d497feb0dc3539119ed25

**Pull request closed without merging**
