### PR TITLE
fix golint error if block ends with a return statement

### PR DESCRIPTION
**Pull request by wgliang**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind cleanup

**What this PR does / why we need it**:
run command ./hack/verify-golint.sh
get

```
Errors from golint:
pkg/cloudprovider/providers/aws/aws_fakes.go:357:9: if block ends with a return statement, so drop this else and outdent its block
pkg/volume/util/util.go:204:9: if block ends with a return statement, so drop this else and outdent its block
```
I think maybe releated with #69387 and #68491.

The strange thing is why CI has always been happy?

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by justinsb** [comment]
I can't say I agree with golint on this one - the original form checks that all the `if` branches return a value.

Still, I've given up fighting it, so ...

/lgtm

**Comment by wgliang** [comment]
@justinsb I don't think this has to be modified, but I found that golint always reported this error when I tested it. And I don't know why CI didn't find this problem.

**Comment by justinsb** [comment]
Agreed on both counts - we do have a golint exclude, but I didn't see these files, and I presume CI just runs the same file anyway.  Maybe a different version of golint?

And while I disagree with golint, I do agree with you @wgliang that we should just keep golint happy, because some of the other things it recommends are pretty good, and otherwise we risk not seeing those other recommendations :-)  Thank you for fixing it!

**Pull request closed without merging**
