### PR TITLE
update the go-restful dependency.

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes https://github.com/kubernetes/kubernetes/issues/25084

[Analytics]()

### CODE REVIEW

**Comment by brendandburns** [comment]
@kubernetes/sig-api-machinery

**Comment by lavalamp** [comment]
thanks.

**Comment by lavalamp** [comment]
LGTM

**Comment by brendandburns** [comment]
@k8s-bot e2e test this please flake: #25371

**Comment by brendandburns** [comment]
@lavalamp can I get a re-LGTM on this one?

Thanks!

**Comment by nikhiljindal** [comment]
Added LGTM

**Comment by brendandburns** [comment]
@k8s-bot node e2e test this please issue: 25699

**Comment by brendandburns** [comment]
@k8s-bot node e2e test this please issue: 25086

**Pull request merged**
