### PR TITLE
Remove invalid blank line when printing jobs

### LINKED ISSUE #16254: [infrastructure_public_197]When get jobs the output has invalid blank line
```
Description of problem:
1.When get jobs the output has invalid blank line
2.When have multi jobs, output line can't be aligned with the first row

Version-Release number of selected component (if applicable):
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.2.320+0884214fe040e2", GitCommit:"0884214fe040e2824e9710b0a1154705122be413", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.0-alpha.2.320+0884214fe040e2", GitCommit:"0884214fe040e2824e9710b0a1154705122be413", GitTreeState:"clean"}

How reproducible:
Always.

Steps to Reproduce:
1.Create multi job
# kubectl create -f job.yaml

2.Get the job
[root@ip-172-18-12-52 kubernetes]# kubectl get job
JOB       CONTAINER(S)   IMAGE(S)   SELECTOR      SUCCESSFUL
pi        pi             perl       app in (pi)   5

pi-1      pi        perl      app in (pi)   5

pi-2      pi        perl      app in (pi)   5

pi-3      pi        perl      app in (pi)   5

pj        pi        perl      app in (pi)   5


Actual results:
2.When get the jobs should no invalid blank line between different line.

Expected results:
2.2.When get the jobs should is invalid blank line between different line.

Additional info:

```

### PR DESCRIPTION
**Pull request by janetkuo**
Fixes #16254

cc @kubernetes/kubectl

### CODE REVIEW

**Comment by kargakis** [comment]
lgtm

**Comment by janetkuo** [comment]
This needs to be cherry-picked.

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by soltysh** [comment]
lgtm

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Pull request merged**
