### PR TITLE
Automated cherry pick of #12897 #13001 upstream release 1.0

### PR DESCRIPTION
**Pull request by roberthbailey**

### CODE REVIEW

**Comment by roberthbailey** [comment]
Our continuous testing against the release branch needs to keep working if the preview commands disappear.

**Comment by wojtek-t** [comment]
LGTM

@roberthbailey - do you know how to ping "cla bot" (currently there is cla:no label added)?

**Comment by roberthbailey** [comment]
We ignore the CLA bot for automated cherry pick requests. See https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md#cherry-pick-review

**Comment by wojtek-t** [comment]
@roberthbailey - thanks!

**Comment by zmerlynn** [comment]
Cross link #12897 #13001

**Pull request merged**
