### PR TITLE
Avoid using ghodss/yaml - switch to our forked repo

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I115bc834b2b8473c3a81812a76b8433fda24a908

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Let's stick to using the forked repo please

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by kwiesmueller** [comment]
/lgtm

Didn't know this happened. Thanks for noticing!

**Review by kwiesmueller — APPROVED** [review]
/approve

**Comment by kwiesmueller** [comment]
/assign @thockin 
/cc @apelisse 

Not a big fix and probably worth to get in before freeze?

**Comment by apelisse** [comment]
> Let's stick to using the forked repo please

We need one of two things:
- Better godeps review,
- Automation godeps checks,

@BenTheElder Would it make sense to have a blacklist of dependencies for godeps?

**Comment by apelisse** [comment]
And then I've seen the first line of change, thank you :-)

**Comment by apelisse** [comment]
> pkg/.import-restrictions

I don't understand why this file is in `pkg`, it makes it much harder to approve changes to it (maybe it's a good thing tho). I suspect it should be in a more "infra"-friendly location.

**Comment by BenTheElder** [comment]
> @BenTheElder Would it make sense to have a blacklist of dependencies for godeps?

that's pretty much the import-restrictions?

**Comment by apelisse** [comment]
> that's pretty much the import-restrictions?
Yeah I realized that 1 second later :-)

**Review by thockin — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
