### PR TITLE
Add cleaning to the clean target

### PR DESCRIPTION
**Pull request by mattf**

### CODE REVIEW

**Comment by mattf** [comment]
cc @zmerlynn

**Comment by zmerlynn** [comment]
@mattf, you should talk to @smarterclayton about @googlebot CLA-ness. :)

**Comment by zmerlynn** [comment]
LGTM

**Comment by mattf** [comment]
@zmerlynn thanks, i've had other commits in, so i'm not sure why the @googlebot is harassing me

**Comment by zmerlynn** [comment]
@mattf: There's no accounting for taste. @smarterclayton has a magic google group he can add you to that'll fix it for good, though.

**Comment by zmerlynn** [comment]
Hand merging an image-only change.

**Pull request merged**
