### PR TITLE
kubelet: stop probing if liveness check fails

### LINKED ISSUE #21751: e2e flake: Pods should be restarted with a docker exec "cat /tmp/health" liveness probe [Conformance]
Happened in GKE suite:

    06:07:58 STEP: Creating pod liveness-exec in namespace e2e-tests-pods-2lof2
    06:07:58 Feb 23 06:05:51.859: INFO: Waiting up to 5m0s for pod liveness-exec status to be !pending
    06:07:58 Feb 23 06:05:51.888: INFO: Waiting for pod liveness-exec in namespace 'e2e-tests-pods-2lof2' status to be '!pending'(found phase: "Pending", readiness: false) (28.867408ms elapsed)
    06:07:58 Feb 23 06:05:53.892: INFO: Waiting for pod liveness-exec in namespace 'e2e-tests-pods-2lof2' status to be '!pending'(found phase: "Pending", readiness: false) (2.033032885s elapsed)
    06:07:58 Feb 23 06:05:55.913: INFO: Saw pod 'liveness-exec' in namespace 'e2e-tests-pods-2lof2' out of pending state (found '"Running"')
    06:07:58 Feb 23 06:05:55.913: INFO: Started pod liveness-exec in namespace e2e-tests-pods-2lof2
    06:07:58 STEP: checking the pod's current state and verifying that restartCount is present
    06:07:58 Feb 23 06:05:55.931: INFO: Initial restart count of pod liveness-exec is 0
    06:07:58 Feb 23 06:07:56.207: FAIL: pod e2e-tests-pods-2lof2/liveness-exec - expected number of restarts: %!!(MISSING)t(int=1), found restarts: %!!(MISSING)t(int=0)
    06:07:58 STEP: deleting the pod

https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gke/1577/build-log.txt

@kubernetes/sig-node

### PR DESCRIPTION
**Pull request by yujuhong**
This change puts the worker on hold when the liveness check fails. It will
resume probing when observing a new container ID.

This fixes #21751

### CODE REVIEW

**Comment by timstclair** [comment]
LGTM - nice debugging

**Comment by therc** [comment]
Isn't this a bit drastic, if a container fails just one check because of a hiccup? Shouldn't there be a way for users to let containers be marked as healthy again? Both ELB and Borg let you tweak that. Won't this change make that harder to support?

**Comment by yujuhong** [comment]
> Isn't this a bit drastic, if a container fails just one check because of a hiccup? Shouldn't there be a way for users to let containers be marked as healthy again? Both ELB and Borg let you tweak that. Won't this change make that harder to support?

We support custom parameters such as `FailureThreshold`, `SuccessThreshold`, `PeriodSeconds`, `TimeoutSeconds`. If users want a more conservative setting, they can set the failure threshold to something higher.  This PR will only stop probing the container if the failure threshold is reached. Since it's a workaround for a bug, and we currently don't provide mechanism for user to override the healthiness of a container directly, it should not be problem.

**Comment by therc** [comment]
I didn't realise that those are coming with 1.2. The only place they are documented is behind the "Beware of the leopard" sign (i.e. in the API reference and the code). Sounds good, thanks.

**Comment by timstclair** [comment]
I don't think this should change the behavior at all, actually. As soon as the liveness check fails, the container restart will be kicked off. Even if the liveness probe were to succeed again, the restart would probably already be in progress.

**Comment by yujuhong** [comment]
Marking p1 to fix flaky tests

**Comment by yujuhong** [comment]
@k8s-bot test this please issue: #22300

**Pull request merged**
