### PR TITLE
Refactor param type combine

### PR DESCRIPTION
**Pull request by 0daryo**
**What type of PR is this?**
Refactoring param type combine in kube-controller-manager

**What this PR does / why we need it**:
following simple args, which gocritic points
**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
Thank you for your PR. Any special reason to skip L420?

**Comment by 0daryo** [comment]
> Thank you for your PR. Any special reason to skip L420?

Thank you for replyng. It was just my mistake, fixed it 👍

**Comment by 0daryo** [comment]
any concerns?

**Pull request closed without merging**
