### PR TITLE
cmd/kube-controller-manager: fix staticcheck warning

### PR DESCRIPTION
**Pull request by hwdef**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fix staticcheck warnings.

`ServerResources` is deprecated in favor of `ServerGroupsAndResources`.

Import rename is not needed

**Which issue(s) this PR fixes**:

Ref: #81657

**Special notes for your reviewer**:
NONE
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by thockin** [comment]
For fututre, please explain what the warnings were in the PR messages.

**Comment by thockin** [comment]
Even better - file an issue and then `Fixes: ` it in the PR comment. :)

**Comment by hwdef** [comment]
@thockin 
Thanks for your suggestion,
I update the PR comment, add issues,
I will explain what the warnings were in the PR messages in the future PR.
I update this PR to fix some CI failures.
Cloud you please add a LGTM label for this PR again?

**Pull request merged**
