### PR TITLE
Comment default behaviour of kubectl drain.GracePeriodSeconds

### PR DESCRIPTION
**Pull request by bboreham**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

It took me a while to spot this subtlety.

**Which issue(s) this PR fixes**:
Relates to https://github.com/kubernetes/kubectl/issues/982

```release-note
NONE
```

### CODE REVIEW

**Review by evrardjp — COMMENTED** [review]
Fair.

**Comment by brianpursley** [comment]
/lgtm

This comment just documents the existing behavior. @soltysh wdyt about the wording? It seems OK to me.

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
