### PR TITLE
Convert scheduler and controller-manager to hyperkube

### PR DESCRIPTION
**Pull request by jbeda**
After this I have the kubelet and the proxy left to do.

### CODE REVIEW

**Comment by jbeda** [comment]
Running e2e now.

**Comment by satnam6502** [comment]
@jbeda do you have suggestions for a reviewer? Thanks.

**Comment by jbeda** [comment]
Assigning to @bgrant0607

**Comment by jbeda** [comment]
This is part of #108

**Comment by jbeda** [comment]
e2e test passed.

**Comment by bgrant0607** [comment]
LGTM. Sorry for the delay.

**Pull request merged**
