### PR TITLE
Automated cherry pick of #77661: Kubelet provides an updated and complete status of

### PR DESCRIPTION
**Pull request by mfpierre**
Cherry pick of #77661 on release-1.14.

#77661: Kubelet provides an updated and complete status of

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/ok-to-test

**Comment by mfpierre** [comment]
Hey, friendly reminder about this cherry-pick, it didn't make it for the last `1.12.10` release https://github.com/kubernetes/kubernetes/pull/77934 but it would be nice to have it for `1.13` & `1.14`

**Comment by tpepper** [comment]
@vishh, @Random-Liu can you give these two cherry picks a review and decide if they should be approved or closed?

**Comment by derekwaynecarr** [comment]
per @yujuhong original comment, we will avoid picking this back.

see: https://github.com/kubernetes/kubernetes/pull/77661#issuecomment-507476556

**Pull request closed without merging**
