### PR TITLE
Duplicate v1alpha1 AuthorizationConfiguration to v1beta1

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Adds apiserver.config.k8s.io/v1beta1 AuthorizationConfiguration types

Part of https://github.com/kubernetes/enhancements/issues/3221

#### Does this PR introduce a user-facing change?
```release-note
kube-apiserver: the AuthorizationConfiguration type accepted in `--authorization-config` files has been promoted to `apiserver.config.k8s.io/v1beta1`.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://kep.k8s.io/3221
```

/sig auth
/milestone v1.30
/assign @palnabarun @ritazh

### CODE REVIEW

**Review by palnabarun — APPROVED** [review]
/lgtm

**Comment by liggitt** [comment]
/hold cancel

this is orthogonal to the metrics addition

**Comment by liggitt** [comment]
Hmm, unrelated conformance test error, which is concerning
/retest

**Pull request merged**
