### PR TITLE
lint fixes for goal state checks

### PR DESCRIPTION
**Pull request by kwmonroe**
**What this PR does / why we need it**:
Lint fixes for long lines introduced in #65187 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:
We could also fix this by setting a longer flake8 line length in something like a local `setup.cfg`

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by kwmonroe** [comment]
```release-note
NONE
```

**Review by ktsakalozos — APPROVED** [review]
Thank you for fixing these style errors

**Pull request merged**
