### PR TITLE
Change default value of kubelet flags:

### PR DESCRIPTION
**Pull request by dchen1107**
max-pods from 40 to 110 and
 maximum-dead-containers from 100 to 250

cc/ @yujuhong

### CODE REVIEW

**Comment by jeremyeder** [comment]
What is the difference between this and #21361?  Why 110 here and 100 there?

**Comment by yujuhong** [comment]
> kubernetes member
> jeremyeder commented 8 hours ago
> What is the difference between this and #21361? Why 110 here and 100 there?

It's basically the same. We just happened to upload the PRs at the same time :)

I think 100 should be enough. @dchen1107, do we want 110 for any particular reason?

**Comment by dchen1107** [comment]
Align with what we had for 1.0 and 1.1 release when we claim 30 pods per node, the flag is 40 to cover kube-system pods. Also align with e2e test itself.

**Comment by yujuhong** [comment]
Discussed with @dchen1107 offline. Closing this in favor of #21631

**Pull request closed without merging**
