### PR TITLE
Removed extraneous json descriptions from internal types

### PR DESCRIPTION
**Pull request by markturansky**
Internal types do not require description but several still had them.

@bgrant0607 @nikhiljindal

### CODE REVIEW

**Comment by zmerlynn** [comment]
Over to @bgrant0607.

**Comment by bgrant0607** [comment]
Thanks. LGTM

**Comment by bgrant0607** [comment]
Reassign to @lavalamp for another LGTM

**Comment by nikhiljindal** [comment]
LGTM

**Comment by lavalamp** [comment]
LGTM

Sure-- can we take the json tags out, too? :) :) In a follow-up.

**Comment by bgrant0607** [comment]
@lavalamp Removing json tags didn't work last time we tried. That's #3933. However, at this point I think the best solution is to nuke api/types.go entirely.

**Pull request merged**
