### PR TITLE
Remove duplicated SinceInMicroseconds()

### PR DESCRIPTION
**Pull request by oomichi**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This removes duplicated SinceInMicroseconds() and makes callers
use the same method for code cleanup.

**Does this PR introduce a user-facing change?**:
```NONE```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm

**Comment by MrHohn** [comment]
/lgtm
/assign @Random-Liu
to check if any approver can take a look :)

**Comment by oomichi** [comment]
@MrHohn Thanks for your review again :-)

**Comment by cmluciano** [comment]
@kubernetes/sig-node-pr-reviews

**Comment by MrHohn** [comment]
To keep this rolling :)
/lgtm

**Comment by yujuhong** [comment]
The PR looks good, but we probably don't want to add more dependency to kubelet in dockershim. 
/cc @dims

**Comment by dims** [comment]
Agree with @yujuhong 

@oomichi seems like https://github.com/kubernetes/utils/blob/master/clock/clock.go may be a better home for the utility functions.

**Comment by oomichi** [comment]
@dims Thanks for your advice, that makes sense for me :-)

**Comment by oomichi** [comment]
https://github.com/kubernetes/utils/pull/90 is instead of this.

**Pull request closed without merging**
