### PR TITLE
Fixed Typos In Two Comments

### PR DESCRIPTION
**Pull request by jhorowitz**
**What this PR does / why we need it**:
Minor typo fixes in two comments

### CODE REVIEW

**Comment by jhorowitz** [comment]
I signed it!

**Comment by k82cn** [comment]
@k8s-bot ok to test

**Comment by brendandburns** [comment]
@k8s-bot node e2e test this
@k8s-bot verify test this

/lgtm

**Comment by jhorowitz** [comment]
@k8s-bot verify test this

**Comment by k82cn** [comment]
@jhorowitz , run `./hack/update-staging-client-go.sh`

**Comment by kargakis** [comment]
@jhorowitz ping

**Comment by pwittrock** [comment]
Please create an issue and reference in the description.  If this should remain in the 1.7 milestone please add it back in.

**Comment by brendandburns** [comment]
@k8s-bot verify test this
@k8s-bot pull-kubernetes-verify test this

**Comment by jhorowitz** [comment]
@brendandburns Sorry, for some reason I haven't been getting notifications on this repo. Is there anything other then rebasing that I need to do?

**Comment by xiangpengzhao** [comment]
@jhorowitz FYI: `pkg/util/util.go` was removed. The status of the two functions you touched is as below:
* `IntPtrDerefOr` was removed.
* `Int32PtrDerefOr` was moved to `pkg/util/pointer/pointer.go`, but the typo still exists.

You can rebase and fix the typo in that file. Thanks for contribution!

**Comment by dims** [comment]
Do we need this for 1.8? please rebase.

**Comment by spiffxp** [comment]
friendly v1.8 release ping, does this PR need to be in the v1.8 milestone? is this PR actively being worked

the approval bot may expect an `/approve no-issue` for this

**Comment by k82cn** [comment]
typo, it's ok to move it to 1.9.

**Comment by dims** [comment]
@jhorowitz please rebase if we want to try to shoot for 1.9. if not let's please move it out

**Comment by jhorowitz** [comment]
Sorry about not responding, I don't know what's up with my notifications for this repo. I'm going to close this PR as the file seem to exist anymore and the change was very minor anyway.

**Pull request closed without merging**
