### PR TITLE
Fix pkg/controller/replicaset/replica_set_test.go variable reference error

### PR DESCRIPTION
**Pull request by chymy**
#### What type of PR is this?
/kind bug
/kind cleanup

#### What this PR does / why we need it:
In `t.Errorf` , `newRSKey` should be used.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chymy** [comment]
/assign @janetkuo
Thanks.

**Comment by dims** [comment]
/retest
/assign @soltysh 

NOTE: just 2 lines of code, should be a quick review!

**Review by soltysh — APPROVED** [review]
Good catch, thank you!
/lgtm
/approve

**Pull request merged**
