### PR TITLE
Printer: fix a nil pointer dereference

### PR DESCRIPTION
**Pull request by roycaihw**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix a nil pointer dereference that could cause kube-apiserver to panic.

**Does this PR introduce a user-facing change?**:

```release-note
Fix a bug in server printer that could cause kube-apiserver to panic.
```

/sig cli

### CODE REVIEW

**Review by janetkuo — APPROVED** [review]

**Comment by janetkuo** [comment]
This needs to be cherrypicked.

**Comment by roycaihw** [comment]
> This needs to be cherrypicked.

Sounds good. This was from https://github.com/kubernetes/kubernetes/commit/17740a285785568ad753d7477881e67bcef19517#diff-749b0f5911ddd5261b4ed5c2945d7c16R1585, which was added in 1.12. I assume 1.12 has retired so let's cherrypick it to 1.13, 1.14 and 1.15?

**Comment by janetkuo** [comment]
> let's cherrypick it to 1.13, 1.14 and 1.15

SGTM

**Comment by roycaihw** [comment]
> I assume 1.12 has retired so let's cherrypick it to 1.13, 1.14 and 1.15?

Actually v1.12.10 cut (the last patch release) is planned Monday, July 1st. I can prepare a cherrypick for 1.12 as well

@janetkuo Could you add the approval label? Thanks

**Comment by smarterclayton** [comment]
/approve
/lgtm

as well

**Pull request merged**
