### PR TITLE
feat: change partition style to GPT on Windows

### PR DESCRIPTION
**Pull request by andyzhangx**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
feat: change parittion style to GPT on Windows
This could support disk size > 2TB

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
feat: change parittion style to GPT on Windows
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
feat: change parittion style to GPT on Windows
```

### CODE REVIEW

**Comment by jsturtevant** [comment]
What does changing it to GPT do?

**Comment by andyzhangx** [comment]
> What does changing it to GPT do?

@jsturtevant mainly for testing, it should support >2TB disk.

**Comment by jingxu97** [comment]
thanks, @andyzhangx 
We were also talking about changing it in csi-proxy.

**Pull request merged**
