### PR TITLE
Automated cherry pick of #126807: DRA scheduler: ResourceSlice update

### PR DESCRIPTION
**Pull request by pohly**
Cherry pick of #126807 on release-1.31.

#126807: DRA scheduler: ResourceSlice update

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
> A bugfix for a functional issue (not a data loss or security issue) that only affects an alpha feature does not qualify as a critical bug fix.

**Comment by pohly** [comment]
It seemed useful, but indeed, it doesn't meet [the criteria](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#what-kind-of-prs-are-good-for-cherry-picks). Users can work around it by bringing up DRA drivers before trying to schedule pods.

cc @johnbelamaric  for a second opinion.

**Comment by johnbelamaric** [comment]
> It seemed useful, but indeed, it doesn't meet [the criteria](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#what-kind-of-prs-are-good-for-cherry-picks). Users can work around it by bringing up DRA drivers before trying to schedule pods.
> 
> cc @johnbelamaric for a second opinion.

Unfortunately I agree, it does not meet the criteria. What's the scope of the issue? Does this mean scheduler *never* sees ResourceSlices that didn't exist when it started? Or is there a period sync? Or it sees them but just doesn't retrigger unschedulable pods? We need to document the problem clearly so folks will know what they have to do to be able to effectively try out the new feature.

**Comment by pohly** [comment]
> Or it sees them but just doesn't retrigger unschedulable pods?

This.

**Pull request closed without merging**
