### PR TITLE
Fix golint errors for kubernetes/pkg/util/labels/labels_test.go

### PR DESCRIPTION
**Pull request by aj-lee**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by matthyx** [comment]
@aj-lee can you sign the CLA? then I can enable tests on your PR...

**Comment by gianarb** [comment]
Thank you for your contribution @aj-lee but we can't merge it until you sign the CLA
https://identity.linuxfoundation.org/projects/cncf

**Comment by jtslear** [comment]
Hello, @jtslear as Bug Triage Shadow for 1.19. Assigning to sig-testing. If this is incorrect, please notify us and remove the sig.

/sig testing

**Comment by matthyx** [comment]
As @gianarb says, no luck until we have the signed CLA...

**Pull request closed without merging**
