### PR TITLE
Add a log at the start of a watch request.

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes https://github.com/kubernetes/kubernetes/issues/16899  (> than a year old!)

@lavalamp

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37273)

### CODE REVIEW

**Comment by brendandburns** [comment]
@lavalamp friendly post 1.5 ping on this one :)

**Comment by brendandburns** [comment]
@k8s-bot gci gke e2e test this

**Comment by brendandburns** [comment]
ping @lavalamp

**Comment by brendandburns** [comment]
@k8s-bot gci gke e2e test this.

**Comment by brendandburns** [comment]
Rebased. @lavalamp friendly ping, it's short, I promise...

**Comment by lavalamp** [comment]
I'm LGTMing this under the assumption that you checked and `%v`ing a context does something readable, please fix otherwise :)

/lgtm

my queue is very long, apologies for slow response, I must have missed this when I was in the office at the end of november.

**Comment by brendandburns** [comment]
@lavalamp 

```go
package main

import (
        "fmt"
        "time"

        "golang.org/x/net/context"
)

func main() {
        ctx := context.Background()
        fmt.Printf("%v\n", ctx)
        ctx2, _ := context.WithTimeout(ctx, 10)
        fmt.Printf("%v\n", ctx2)
        ctx3 := context.WithValue(ctx2, "foo", "bar")
        fmt.Printf("%v\n", ctx3)
        ctx4, _ := context.WithDeadline(ctx3, time.Now())
        fmt.Printf("%v\n", ctx4)
}
```

```console
$ go run test.go 
context.Background
context.Background.WithDeadline(2017-01-20 20:53:00.564936992 -0800 PST [-12.065µs])
context.Background.WithDeadline(2017-01-20 20:53:00.564936992 -0800 PST [-251.409µs]).WithValue("foo", "bar")
context.Background.WithDeadline(2017-01-20 20:53:00.564936992 -0800 PST [-288.573µs]).WithValue("foo", "bar").WithCancel
```

**Comment by brendandburns** [comment]
Rebased, and added a comment verifying the `context.Context` printing.

**Comment by brendandburns** [comment]
@k8s-bot gci gke e2e test this

**Comment by brendandburns** [comment]
re-lgtm since previous removal was due to a rebase.

**Comment by smarterclayton** [comment]
Contexts can have sensitive information, so we can't just print them out.  Also, this should be v(2).  Opening a followup.

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/kubernetes/pull/42185 closes the security angle here

**Pull request merged**
