### PR TITLE
Fix reference to moved update-demo schema files

### LINKED ISSUE #7060: E2E : fix api version flag in kubectl
Looks like a recent change to examples/ directory `v1beta3` defaults broke our kubectl e2e.  fixing now... PR in flight

### PR DESCRIPTION
**Pull request by j3ffml**
fixes e2e test broken by #7019.

Fixes #7060.

### CODE REVIEW

**Comment by jlowdermilk** [comment]
Spinning up e2e cluster to verify test is fixed. Will confirm when it's passing.

**Comment by roberthbailey** [comment]
LGTM assuming e2e tests pass.

**Comment by jlowdermilk** [comment]
e2e tests passing, but travis/shippable fails because unit tests broken. #7063 will fix that, so I'll wait until that's merged and rebase.

**Comment by roberthbailey** [comment]
I just merged it. Please rebase.

**Comment by jlowdermilk** [comment]
I was confused how this got closed, but it looks like #7065 was merged, so we're good.

**Pull request closed without merging**
