### PR TITLE
Fix non-starting node controller in 1.4 branch

### PR DESCRIPTION
**Pull request by wojtek-t**
@fabioy @janetkuo

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34895)

### CODE REVIEW

**Comment by davidopp** [comment]
looking now

**Comment by wojtek-t** [comment]
@davidopp shared_informer.go, and wait.go is picking up the changes from master that are needed, but were added after 1.4 was cut

**Comment by davidopp** [comment]
cc/ @lavalamp

**Comment by gmarek** [comment]
lgtm

**Comment by davidopp** [comment]
LGTM

**Comment by lavalamp** [comment]
LGTM

**Comment by ravilr** [comment]
I'm looking to upgrade from 1.3.7 to latest 1.4 release. Are all 1.4.x releases are affected by this or only the latest v1.4.2 release? Thanks.

**Comment by lavalamp** [comment]
@ravilr only 1.4.2 was affected by the bad cherrypick.

**Comment by davidopp** [comment]
We've removed 1.4.2 release from Github, though tag is still there.

**Comment by wojtek-t** [comment]
All tests passed.

**Comment by liggitt** [comment]
cc @ncdc

**Pull request merged**
