### PR TITLE
[e2e] Add verbose to reachability test commands

### PR DESCRIPTION
**Pull request by MrHohn**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
Ref https://github.com/kubernetes/kubernetes/issues/81000#issuecomment-518746253, adding verbose so that we can better debug the test failure.

**Which issue(s) this PR fixes**:

Fixes #NONE

**Special notes for your reviewer**:
/assign @mgdevstack 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by krzyzacy — APPROVED** [review]

**Comment by MrHohn** [comment]
Adding @saschagrunert who is looking into similar failure.
/assign @saschagrunert

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Review by saschagrunert — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
