### PR TITLE
Enable Parallel test execution

### PR DESCRIPTION
**Pull request by electrocucaracha**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Since go v1.7, the go testing package provides the ability to run [tests in parallel](https://pkg.go.dev/testing#T.Parallel). As this [post](https://engineering.mercari.com/en/blog/entry/20220408-how_to_use_t_parallel/) describes, unit tests will run in parallel at the package level. Therefore, this change allows increasing the number of processes during the execution of unit tests.

#### Which issue(s) this PR fixes:
NA

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
not all tests are suitable to run in parallel. Please open a PR for each SIG, to reduce reviewing burden.

**Comment by aojea** [comment]
/hold
https://github.com/kubernetes/kubernetes/pull/112289#issuecomment-1240426455

**Comment by aojea** [comment]
/hold

the one of these series that have merged had to be reverted https://github.com/kubernetes/kubernetes/pull/112289#issuecomment-1256395695

It is better to be conservative and address this once we have real problems of the job running unit tests taking so long

**Comment by endocrimes** [comment]
/close

https://github.com/kubernetes/kubernetes/pull/112288#issuecomment-1268361933

**Pull request closed without merging**
