### PR TITLE
Revert "Don't register the kubeletconfig group with the default Scheme"

### PR DESCRIPTION
**Pull request by shyamjvs**
Reverts kubernetes/kubernetes#50789

To unblock SQ - https://github.com/kubernetes/kubernetes/issues/51007

cc @mtaufen

### CODE REVIEW

**Comment by wojtek-t** [comment]
@shyamjvs - how is it possible that presubmit didn't catch it?

**Comment by shyamjvs** [comment]
Good question - trying to figure out.

**Comment by shyamjvs** [comment]
All presubmits except kubemark are passing. Merging this manually to unblock submit-queue.

**Comment by shyamjvs** [comment]
Btw - the kubemark presubmit here failed due to a different reason:

```
I0821 09:35:15.209] Creating new network: e2e-46812
W0821 09:36:02.881] ERROR: (gcloud.compute.networks.create) Could not fetch resource:
W0821 09:36:02.881]  - Quota 'SUBNETWORKS' exceeded.  Limit: 150.0
```

@kubernetes/test-infra-maintainers This is affecting more and more PRs now.

**Comment by shyamjvs** [comment]
As @wojtek-t pointed out, some of the networks were leaked. I looked into it, and the runs 46434-46439 of the pr-kubemark job all failed to delete network due to undeleted minion still using it. I'm now manually cleaning it up.

**Pull request merged**
