### PR TITLE
Remove hostPort in api/examples/controller.json to avoid port conflicts

### LINKED ISSUE #4500: hack/test-integration.sh is flaky
A significant number of builds fail with the error

```
F0217 20:14:13.799188   16880 integration.go:299] FAILED: pods never started running timed out waiting for the condition
```
If you look at [shippable history](https://app.shippable.com/projects/54c71b655ab6cc135289dd2d), this is the leading cause of flakes (build passes on 1.4, fails on 1.3 or vice versa).

### PR DESCRIPTION
**Pull request by yujuhong**
This is an attempt to fix #4500.

### CODE REVIEW

**Comment by yujuhong** [comment]
It failed shippable. Closing this failed attempt.

**Comment by bgrant0607** [comment]
Could you please just delete everything in api/examples instead?

**Comment by yujuhong** [comment]
@bgrant0607, do you mean delete hostPort in all api/examples?

**Comment by yujuhong** [comment]
FWIW I meant to use this PR for testing only, but it failed.

**Comment by bgrant0607** [comment]
Sorry, no, I meant `rm -r api/examples`.

**Comment by nikhiljindal** [comment]
They are used by integration tests as well: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/integration/integration.go#L274

**Pull request closed without merging**
