### PR TITLE
Fix test flakes for TestWatchSemantics

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref https://github.com/kubernetes/kubernetes/pull/125731#issuecomment-2192016509

```release-note
NONE
```

/kind flake
/priority important-soon

/assign @p0lyn0mial
/cc @liggitt @dims

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
thanks, lgtm

**Comment by liggitt** [comment]
failure was:
```
{Failed;Failed;  === RUN   TestWatchStreamSeparation/separate_RPC_&_watch_cache_context_>_only_watch_cache_gets_bookmarks
W0626 17:44:32.490399   70260 logging.go:55] [core] [Channel #682 SubChannel #683]grpc: addrConn.createTransport failed to connect to {Addr: "localhost:45995", ServerName: "localhost:45995", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:45995: connect: connection refused"
W0626 17:44:33.017790   70260 logging.go:55] [core] [Channel #618 SubChannel #621]grpc: addrConn.createTransport failed to connect to {Addr: "localhost:43229", ServerName: "localhost:43229", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:43229: connect: connection refused"
W0626 17:44:33.244244   70260 logging.go:55] [core] [Channel #426 SubChannel #429]grpc: addrConn.createTransport failed to connect to {Addr: "localhost:46449", ServerName: "localhost:46449", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:46449: connect: connection refused"
W0626 17:44:33.520122   70260 logging.go:55] [core] [Channel #116 SubChannel #119]grpc: addrConn.createTransport failed to connect to {Addr: "localhost:38065", ServerName: "localhost:38065", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:38065: connect: connection refused"
    cacher_whitebox_test.go:2588: Unexpected watch cache bookmark check result, rv: 8, lastRV: 9, wantMatching: true
W0626 17:44:34.429504   70260 logging.go:55] [core] [Channel #714 SubChannel #717]grpc: addrConn.createTransport failed to connect to {Addr: "localhost:38089", ServerName: "localhost:38089", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:38089: connect: connection refused"
    --- FAIL: TestWatchStreamSeparation/separate_RPC_&_watch_cache_context_>_only_watch_cache_gets_bookmarks (2.00s)
```

grpc revert merged since then (https://github.com/kubernetes/kubernetes/pull/125731#event-13302295017), hopefully this will pass now

**Pull request merged**
