### PR TITLE
Partial cherry-pick of #33182

### PR DESCRIPTION
**Pull request by soltysh**
This partially cherry-picks contents of #33182, esp. the part that updates how our api-reference docs are generated. I didn't want to risk picking other stuff and this is needed to have that being available in our [docs](http://kubernetes.io/docs/reference/). This was raised in https://github.com/kubernetes/kubernetes.github.io/issues/1439 so I'm updating k8s first and then I'll update the docs repo.

@jessfraz since you're 1.4 czar ptal
@devin-donnelly since you're responsible for the docs, iirc
@deads2k just fyi, since you're the original author of this commit
@wernight since you've asked for it

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35203)

### CODE REVIEW

**Comment by jessfraz** [comment]
I think the verification test failure is real

**Comment by soltysh** [comment]
Updated the failure, I'll apply the label if tests are green.

**Comment by jessfraz** [comment]
@k8s-bot verify test this

**Comment by soltysh** [comment]
Apparently when cherry-picking my editor remove a whitespace in `hack/lib/init.sh` where `KUBE_NONSERVER_GROUP_VERSIONS` are specified. Fixed that, hopefully we should be good to go with this one.

**Comment by jessfraz** [comment]
yay! thanks!

**Comment by jessfraz** [comment]
@k8s-bot test this

**Comment by jessfraz** [comment]
@k8s-bot test this please

**Comment by soltysh** [comment]
@k8s-bot gci cvm gke e2e test this flake #34986

**Pull request merged**
