### PR TITLE
Deprecate the --reconcile-cidr flag

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**: Follows up https://github.com/kubernetes/kubernetes/pull/34906

**Special notes for your reviewer**: I'm not sure why coreos had set `--reconcile-cidr` to `false` and what the implications are now.

**Release note**:

``` release-note
Deprecate the --reconcile-cidr kubelet flag because it has no function anymore
```

PTAL @thockin @freehan @justinsb @yujuhong 
@kubernetes/sig-node @kubernetes/sig-network 

**I will add `hack/update-all.sh` contents soon to fix builds**

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35523)

### CODE REVIEW

**Comment by yujuhong** [comment]
Can we just remove the flag without adding a deprecation warning first (don't think we did that in 1.4)?  @thockin

**Comment by luxas** [comment]
I'm also concerned about that @yujuhong, but @thockin and @danwinship wanted it: https://github.com/kubernetes/kubernetes/pull/34906#discussion_r83660911

Also, we have deprecated the `--configure-cbr0` which is nearly the same thing, but I fully understand what you mean

**Comment by danwinship** [comment]
I don't know our deprecation policies and have no opinion on whether it should be removed. I was just pointing out that the *docs* were wrong--if we keep the flag, the docs should be clear that it doesn't actually have any effect any more.

**Comment by thockin** [comment]
No, we should always deprecate flags.

**Comment by luxas** [comment]
Ok, what should I remove from this PR?
Is it ok to just revert the actual removal of the flag, but deprecate it and remove the references to it completely in this repo?

WDYT?

**Comment by yujuhong** [comment]
> Is it ok to just revert the actual removal of the flag, but deprecate it and remove the references to it completely in this repo?

SGTM.

**Comment by luxas** [comment]
PTAL @thockin @freehan @yujuhong @justinsb

**Comment by luxas** [comment]
A trivial rebase only, reapplying lgtm

**Pull request merged**
