### PR TITLE
Revert "CPU manager wiring and `none` policy"

### LINKED ISSUE #51799: [SQ-blocking] Kubemark presubmit failing to create pod in kubemark cluster
`pull-kubernetes-kubemark-e2e-gce` is failing almost continuously - https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-kubemark-e2e-gce
with the following error:

```
Expected error:
    <*errors.errorString | 0xc420cc4300>: {
        s: "Only 0 pods started out of 1",
    }
    Only 0 pods started out of 1
not to have occurred
```

cc @kubernetes/sig-scalability-misc @kubernetes/test-infra-maintainers @jdumars @luxas

### PR DESCRIPTION
**Pull request by shyamjvs**
Reverts kubernetes/kubernetes#51357

Seems likely this should fix https://github.com/kubernetes/kubernetes/issues/51799

cc @ConnorDoyle @derekwaynecarr

### CODE REVIEW

**Comment by shyamjvs** [comment]
cc @yujuhong @mtaufen @kubernetes/sig-node-pr-reviews

**Comment by shyamjvs** [comment]
@kubernetes/test-infra-maintainers The pr kubemark job doesn't seem to be kicking anymore - https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-kubemark-e2e-gce
Can someone please take a look into it?

**Comment by dchen1107** [comment]
Once required tests pass, I will manually merge this pr to unblock SQ.

**Comment by ConnorDoyle** [comment]
I believe this is the offending line in the original diff, would you be happy with a different PR to just fix the bug?

https://github.com/kubernetes/kubernetes/pull/51357/files#diff-b1a11b4c59442b81f0c7d17b2b5281adR73

**Comment by ConnorDoyle** [comment]
I can have one up in about 5 mins.

**Comment by shyamjvs** [comment]
@ConnorDoyle In general I think it's a good idea to revert the faulty PR and then merge it back along with the fix for 2 reasons:
- If the second PR is also faulty, we'll then need to revert 2 PRs
- We shouldn't be waiting for the fixing PR to get reviewed and merged, but revert the faulty one to quickly unblock others

**Comment by ConnorDoyle** [comment]
SGTM, will just add the fix to the next version of the original PR that caused the problem.

**Comment by ConnorDoyle** [comment]
Here's the v2 PR that unreverts this revert and fixes the nil dereference https://github.com/kubernetes/kubernetes/pull/51811

**Comment by joelsmith** [comment]
@dchen1107 looks like everything passed. If you see this before it makes it through the merge queue, your manual merge would be appreciated.

**Comment by shyamjvs** [comment]
Done (on @dchen1107's behalf :)

**Comment by dchen1107** [comment]
Thanks!

**Comment by ConnorDoyle** [comment]
Thanks for triaging and fixing, sorry for breaking the build.

**Pull request merged**
