### PR TITLE
Bump debian-iptables for security fixes

### PR DESCRIPTION
**Pull request by grayluck**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Bump debian-iptables for security fixes

**Which issue(s) this PR fixes**:

Fixes #None

**Special notes for your reviewer**:
/assign @tallclair 
I've run "make all-push" and the image is in staging registry. `docker pull staging-k8s.gcr.io/debian-iptables:v11.0.2`.
Tim we need to wait for this image to go to prod before I cherrypick the change into old versions, don't we? Do you know the timeline of images from staging to prod? Thanks.

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by bowei** [comment]
@timstclair for final lgtm

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Pull request merged**
