### PR TITLE
[cpumanager] remove state_file since nowhere need it

### PR DESCRIPTION
**Pull request by choury**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
remove state_file in cpumanager since nowhere need it
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/ok-to-test
/lgtm

Deleting unused files definitely makes sense to me - thanks for the pr :)

For my context, can you explain why this became unused?

**Review by mattjmcnaughton — CHANGES_REQUESTED** [review]
Updating my review after the test suite ran :)

/lgtm cancel

It looks like some files may be relying on functions defined in this file, based on the results of https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/81005/pull-kubernetes-typecheck/1158750092904108033.

So maybe we need to keep aspects of this file or move the still used components to a different location?

Let me know if there's anything I can do to help :)

**Comment by choury** [comment]
Hm... according the test, perhaps  some compatibility test are depending it.

**Comment by choury** [comment]
We should keep it at this stage, it will broke the tests if remove it.

**Pull request closed without merging**
