### PR TITLE
fix(kubelet/config): filename manifest validation

### PR DESCRIPTION
**Pull request by maximee-leroyy**
Signed-off-by: Maxime Leroy <19607336+maxime1907@users.noreply.github.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Currently, the [documentation](https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/#constants-and-well-known-values-and-paths) says that there are a few constants paths and file names but doesn't enforce it for the kubelet manifest watch directory, commonly under `/etc/kubernetes/manifests`.

In fact, if we try to back up a manifest file under `/etc/kubernetes/manifests/kube-controller-manager.yaml.bak`, kubelet parses it (since its a simple glob that list files alphabetically) and overwrites the values defined in `/etc/kubernetes/manifests/kube-controller-manager.yaml`

So here is a simple fix to make sure that kubelet only watches for file names that match the following: `component-name.yaml`.

Not hardcoding any component name here will make it easier to maintain in future updates.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
/close

Thanks for the PR, but this is not compatible with existing kubelet use... the linked documentation is specific to the `kubeadm` tool, and the mentioned manifests are ones that tool installs.

See previous discussion about changing what the kubelet watches in this folder in https://github.com/kubernetes/kubernetes/pull/105695#issuecomment-945952088

**Comment by maxime1907** [comment]
@liggitt Thanks for your answer, so the only problem is that it would be a breaking change, so is that okay for you if i add simple flag to enable this behavior and make it disabled by default ?

**Comment by liggitt** [comment]
I'll defer to kubelet maintainers, but there's a *significant* test gap with static manifest handling today... adding to the configurations that need testing and expanding the test matrix and test gap doesn't seem like a great direction

**Comment by maxime1907** [comment]
@liggitt

I understand...

Just so you know, this behavior also introduces a bug in `kubeadm upgrade apply`.

If there are two files like this:
- `/etc/kubernetes/manifests/kube-controller-manager.yaml` is a _modified_ version of the actual `/etc/kubernetes/kube-controller-manager.yaml`
- `/etc/kubernetes/manifests/kube-controller-manager.yaml.bak` is an _identical_ version of the actual `/etc/kubernetes/kube-controller-manager.yaml`

`kubeadm upgrade apply` for the same target kube version will fail because:

1. It compares `/etc/kubernetes/kube-controller-manager.yaml` and `/etc/kubernetes/manifests/kube-controller-manager.yaml`
2. Detects a change, so it waits for kubelet to restart the pod with `/etc/kubernetes/manifests/kube-controller-manager.yaml`
3. Kubelet parses the manifests directory and updates the pod with `/etc/kubernetes/manifests/kube-controller-manager.yaml.bak` (So nothing has changed in the pod)
4. kubeadm hangs until it times out after 5 minutes and fails

**Comment by liggitt** [comment]
> Just so you know, this behavior also introduces a bug in `kubeadm upgrade apply`.

if kubeadm is creating duplicate .bak files in the manifests folder, please open an issue to report that ... that's a bug and should be fixed independent of any changes to kubelet behavior

**Pull request closed without merging**
