### PR TITLE
Remove deprecated kubectl command aliases 'run-container'

### PR DESCRIPTION
**Pull request by Pingan2017**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
`run-container` deprecated in v1.7
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Remove deprecated kubectl command aliases 'run-container'
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

@Pingan2017 please update the release not, you're making a user visible change that deserves being mentioned

**Comment by soltysh** [comment]
Manually adding approved label, since this is touching kubectl-related docs.

**Comment by Pingan2017** [comment]
@soltysh Could you help to add a priority label? Thanks!

**Comment by Pingan2017** [comment]
I can add it by myself. :sweat_smile:

**Pull request merged**
