### PR TITLE
Add CHANGELOG-1.18.md to CHANGELOG.md

### PR DESCRIPTION
**Pull request by uthark**
**What type of PR is this?**
/kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by thockin** [comment]
Should we put these in a subdir with an appropriate OWNERS file and then symlink them back (like Makefile) into the root?

**Comment by uthark** [comment]
@thockin I can try. What is suggested directory name? `changelogs`? or `docs/changelogs`? Or smth. else?

**Comment by thockin** [comment]
I don't know, "changelogs" or something sounds fine.

**Comment by uthark** [comment]
@thockin Done, but diff looks scary - typechange recognized as delete and create file, not as move.

**Comment by uthark** [comment]
@thockin Please review.

**Comment by thockin** [comment]
Yeah, it's unfortunate that this didn't detect as file moves.  Oh well.

Can you please resolve the conflicts and ping me for final?

/approve

**Comment by thockin** [comment]
Can we try something?  Sorry to experiment on you.

Break this to 2 commits.  

1) Move the files & commit.
2) Create the symlinks.

That should be trivial to review, and then I want to see if teh squash-merge works.

/label tide/merge-method-squash

**Comment by uthark** [comment]
Sure, will try.

**Comment by liggitt** [comment]
thanks for the PR, changelogs have been relocated under the CHANGELOG folder, so if this is still valid, it will need to be re-opened against that location

/close

**Pull request closed without merging**
