### PR TITLE
duplicate function call

### PR DESCRIPTION
**Pull request by NickrenREN**
When we call the main function app.Run(s),at the beginning, we get the 'genericConfig' by "genericConfig := genericapiserver.NewConfig(). // create the new config
ApplyOptions(s.ServerRunOptions). // apply the options selected
Complete() "
here we call the function "(c *Config) Complete()", and then,we get the struct master by "m, err := config.Complete().New()",in the function config.Complete(),we also call "c.GenericConfig.Complete()".
Maybe we could remove the latter one, is my understanding right?

I squash the commits in PR #35095

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35262)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @sttts who I think wrote this code.

@k8s-bot ok to test

**Comment by sttts** [comment]
I think the `Complete()` call at the top of app/server.go's `Run()` (https://github.com/sttts/kubernetes/blob/f39e86c0a5122dca894ba2ec11fe629c37035da7/cmd/kube-apiserver/app/server.go#L86-L86) is wrong, not the one you are removing in this PR.

The intention of `Complete` is to be called after all customization of the config have been done. But in that function a lot is changed in the `genericConfig` after the `Complete` call.

**Comment by NickrenREN** [comment]
@sttts  yes, you are right, but genericConfig's members set in Complete()  are different from those changed latter in  app/server.go's Run(). Maybe we could call the genericConfig's Complete() function latter

**Comment by sttts** [comment]
The call of `GenericApiServer.Complete` in `MasterConfig.Complete()` is after all the config changes, isn't it? 

The intention of `Complete` is that the config is read-only after the call. Unfortunately, there is no easy way to express that with Go's types.

Something like this would do, at least it will stop people from changing the used config of the genericapiserver after the Complete call:

```golang
type completeType struct {
  *Config
  usedConfig Config // cloned from *Config
}
```

**Comment by NickrenREN** [comment]
oh,I see. Since the intention of Complete is that the config is read-only after the call ,we don't need to call GenericApiServer.Complete in MasterConfig.Complete(),we have called that before, is my understanding right? @sttts

**Comment by sttts** [comment]
Calling GenericApiServer.Complete once is enough, calling it multiple times shouldn't hurt either.

If we want to make it safely typed and make the whole setup more composable, we could do this:

```golang
type MasterConfig {
  GenericApiServer *GenericApiServer
  ...
}
```

instead of having `GenericConfig` in there as a reference. Then you would be forced to call `GenericConfig.Complete` **before** put the `GenericApiServer` into the MasterConfig. WDYT?

**Comment by NickrenREN** [comment]
oh,maybe just want to put GenericApiServer in Master，and genericConfig in Master's config,haha~i don't know @sttts  but we do just need to call the Complete() once

**Comment by sttts** [comment]
Just thinking about how to use Go's limited type system to avoid those programming errors in the first place. We can fix this one here and in 3 months time somebody introduces another one like this without the type system forbidding it. But I agree: I might be a bit obsessed with type safety (and maybe in the wrong programming language environment for that) ;-)

I would be fine with removing the generic `Complete` from the top of `Run` and leave it in the master's `Complete`. Then even the comment here fits again: https://github.com/sttts/kubernetes/blob/08d4fa5c4fc14c645ded1748455026eeb15926e2/pkg/master/master.go#L189-L189

**Pull request closed without merging**
