### PR TITLE
Fix cluster monitoring

### LINKED ISSUE #4841: Make monitoring (heapster + influxdb + grafana) more Kubernetes friendly
So, having something like
```
yaml
- name: "INFLUXDB_HOST"
  value: '"+window.location.hostname+"/api/v1beta1/proxy/services/monitoring-influxdb'
```
is very limitative when it comes to running ```influxdb``` + ```grafana```inside Kubernetes **but** accessing from external service addresses (```publicIPs```) possibly set in ```grafana-service.yaml```.

Since ```nginx``` is already used for hosting ```grafana```, we should leverage on it for achieving some sort of reverse-proxy for ```http://
localhost:8086```(```influxdb``` is running in the same pod).

### PR DESCRIPTION
**Pull request by pires**
Refs https://github.com/GoogleCloudPlatform/heapster/pull/142
Fixes #4841

### CODE REVIEW

**Comment by vmarmol** [comment]
Assigning @vishh

**Comment by vishh** [comment]
@pires: Sorry for the confusion. Can you make this change in the heapster repo before making it here? We do not run e2e tests for kubernetes that use heapster HEAD, but the heapster repo does. I can make a release of the new grafana image and then we can merge this PR.

**Comment by pires** [comment]
@vishh sure. Sorry for not checking if you had Kubernetes descriptors there.

**Comment by vishh** [comment]
Closing this PR. I will merge the changes in heapster repo first before merging them in Kubernetes.

**Pull request closed without merging**
