### PR TITLE
increase wait_for_url defaults

### PR DESCRIPTION
**Pull request by sjenning**
Fix for flake #21640

### CODE REVIEW

**Comment by sjenning** [comment]
@k8s-bot test this issue: #21451

**Comment by spxtr** [comment]
The default values are used in a few other places in `hack/test-cmd.sh` and elsewhere. Do you mean to increase those as well?

**Comment by sjenning** [comment]
@spxtr yes, I do.  I figure this is just as likely to be a flake for the other cases.  Uses in ```hack/lib/etcd.sh```, ```hack/local-up-cluster.sh```, and ```hack/test-update-storage-objects.sh``` override the defaults.  Complete list below:

```
hack/lib/etcd.sh:  kube::util::wait_for_url "http://${host}:${port}/v2/machines" "etcd: " 0.25 80
hack/lib/util.sh:kube::util::wait_for_url() {
hack/test-cmd.sh:    kube::util::wait_for_url "http://127.0.0.1:${PROXY_PORT}/healthz" "kubectl proxy"
hack/test-cmd.sh:    kube::util::wait_for_url "http://127.0.0.1:${PROXY_PORT}/$1/healthz" "kubectl proxy --api-prefix=$1"
hack/test-cmd.sh:kube::util::wait_for_url "http://127.0.0.1:${KUBELET_HEALTHZ_PORT}/healthz" "kubelet(masterless)"
hack/test-cmd.sh:kube::util::wait_for_url "http://127.0.0.1:${KUBELET_HEALTHZ_PORT}/healthz" "kubelet"
hack/test-cmd.sh:kube::util::wait_for_url "http://127.0.0.1:${API_PORT}/healthz" "apiserver"
hack/test-cmd.sh:kube::util::wait_for_url "http://127.0.0.1:${CTLRMGR_PORT}/healthz" "controller-manager"
hack/test-cmd.sh:kube::util::wait_for_url "http://127.0.0.1:${API_PORT}/api/v1/nodes/127.0.0.1" "apiserver(nodes)"
hack/grab-profiles.sh:kube::util::wait_for_url http://localhost:${tunnel_port}/healthz
hack/local-up-cluster.sh:    kube::util::wait_for_url "http://${API_HOST}:${API_PORT}/api/v1/pods" "apiserver: " 1 10 || exit 1
hack/test-update-storage-objects.sh:  kube::util::wait_for_url "http://127.0.0.1:${API_PORT}/healthz" "apiserver: " 1 120
hack/after-build/update-swagger-spec.sh:kube::util::wait_for_url "http://127.0.0.1:${API_PORT}/healthz" "apiserver: "
```

Basically we are changing/unifying all of the healthz queries to a 30 second timeout by default, unless longer is specified, like in ```hack/test-update-storage-objects.sh```

**Comment by spxtr** [comment]
LGTM

**Pull request merged**
