### PR TITLE
kubelet: create container in parallel

### LINKED ISSUE #81450: Containers startup is blocked by postStart lifecycle hook
**What happened**:

Containers startup is blocked by postStart lifecycle hook.

**What you expected to happen**:

All containers starting asynchronously.

**How to reproduce it (as minimally and precisely as possible)**:

This pod would never reach `running` state

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: ubuntu
    image: ubuntu:18.04
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "apt update; apt install -y netcat; while ! nc -z localhost 80; do sleep 1; done"]
    command: ['sh', '-c', 'sleep 6600']
  - name: nginx
    image: nginx
```

**Anything else we need to know?**:

In documentation on page https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution  said that "Hook handler calls are synchronous". I assume it means that container isn't going to running state until hook completes. There is no mentioning that when there is postStart hooks all containers are starting synchronously.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.5
- Cloud provider or hardware configuration: private cloud
- OS (e.g: `cat /etc/os-release`): Fedora release 30 (Thirty)
- Kernel (e.g. `uname -a`):  5.1.20-300.fc30.x86_64
- Install tools: rancher-2.2
- Network plugin and version (if this is a network-related bug): calico

**Related issues**:

#37805
#59161

Initial issue to workaroud this behaviour in application:
helm/charts#16201

### PR DESCRIPTION
**Pull request by hainesc**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Now, kubelet create container one by one, the creation of the previous container may block the next creation of container for a long time(pulling image, running container, and executing postStart). In special cases, it may lock the startup of the container. See #81450

I think we should better create container in parallel by goroutine.
**Which issue(s) this PR fixes**:
Fixes #81450

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by hainesc** [comment]
Reference #37805 and helm/charts#16201

**Comment by hainesc** [comment]
Copy the example and comment from #81450

```
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: ubuntu
    image: ubuntu:18.04
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "apt update; apt install -y netcat; while ! nc -z localhost 80; do sleep 1; done"]
    command: ['sh', '-c', 'sleep 6600']
  - name: nginx
    image: nginx
```

It was caused by the code that starts container serially. See https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L814-L816. The start function calls startContainer which do

* pull the image
* create the container
* start the container
* run the post start lifecycle hooks (if applicable)

So, as in this case, the postStart hook of ubuntu container never complete, and the nginx container was blocked to run start function.

**Comment by hainesc** [comment]
ping @kubernetes/sig-node-pr-reviews for review, thanks!

**Review by mattjmcnaughton — COMMENTED** [review]
Thanks for your pr :)

Just a couple of high level thoughts/questions before reviewing the actual code :)

1. From the [init container docs](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#understanding-init-containers), an advertised behavior of init containers is that they start sequentially and if the preceding container does not succeed, the later containers will not run. This pr would break that behavior.
2. Even if we create the containers in parallel, isn't a hanging postStart hook still a problem? We are kind of just delaying when the problem appears.
3. If we do move forward with this, do we need to worry about unbounded concurrency? (i.e. what if there are 20 containers... could trying to start them all at once be a problem?).

/ok-to-test
/assign @dchen1107

**Comment by hainesc** [comment]
> Just a couple of high level thoughts/questions before reviewing the actual code :)
> 
> 1. From the [init container docs](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#understanding-init-containers), an advertised behavior of init containers is that they start sequentially and if the preceding container does not succeed, the later containers will not run. This pr would break that behavior.
> 2. Even if we create the containers in parallel, isn't a hanging postStart hook still a problem? We are kind of just delaying when the problem appears.
> 3. If we do move forward with this, do we need to worry about unbounded concurrency? (i.e. what if there are 20 containers... could trying to start them all at once be a problem?).

Good points, @mattjmcnaughton, there are what I was thinking today.

1. The docs you linked is about init container, Yes, they should start sequentially, in this PR, I did not parallelize the creation of init container.

And for app containers, as @monester said in #81450 

> In documentation on page https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution said that "Hook handler calls are synchronous". I assume it means that container isn't going to running state until hook completes. There is no mentioning that when there is postStart hooks all containers are starting synchronously.

Also, in the mind of a lot of users, including me, what we think about the relationship among containers in container list is, they are equal, there is **no order** among them, the pod consists of container1 **AND** container2, only that, not **before-after**.

If not refer to docs carefully(recently, as @monester said, we don't find it), I think there will be many people assume that there is **no order** among app containers, not **before-after**.  (They catch an Oops, the containers run **before-after**, and patch their yaml at last)

2. Some people, such as #81450 and #37805, They assumed there is no order among the app containers, so they introduced some kind of dependency and got blocked, this PR is helpful for them. Otherwise, a problem is still a problem.
 
3. Most of most time, a pod barely have 20 containers. But yes, It can do. I can make a patch as `scheduler` do. It calculate the priority in parallel, parallel degree no more than a given value. Then , for the pod with 20 containers, containers start in (big) batch. See:
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/core/generic_scheduler.go#L744

After all, I know there may be disagree on it. But the PR is not that bad.

Any talks are appreciate.

Thank again.

**Comment by mattjmcnaughton** [comment]
Thanks for your thoughtful answers @hainesc :)

I'd love to hear thoughts from other members of the sig-node community :)

cc @derekwaynecarr @dashpole @mtaufen @vishh

**Comment by dashpole** [comment]
I think making container creation parallel is a reasonable change, and has some clear benefits.

I am also concerned about the impact this has on the container runtime.  We could bound the parallelism of container creation as this PR does, but it doesn't necessarily fix the problem.  If multiple pods are created at the same time, this can still easily overwhelm the container runtime.  Note that while this is possible today, it is a bit harder to do since ~20 of pods (in my experience) need to be created at once.  Even with a parallelism of 8, that would bring that number down to 3-4 pods, which is much easier to hit.  To actually solve this problem, we probably want to throttle requests to the container runtime...

Regardless of if we decide to parallelize container creation, we should consider adding a (relatively long) timeout for container lifecycle hooks.  That way, a hook that doesn't return doesn't block creation of the other containers indefinitely.

cc @Random-Liu @yujuhong for opinions on container lifecycle hooks

**Comment by hainesc** [comment]
@dashpole Thanks for your thoughts and suggestion. I added some code to timeout the exec lifecycle hook. Please take another look.

Thanks again.

The build error seems not caused by the code. I will fix it ASAP.

```
compile: missing strict dependencies:
	/b/f/w/pkg/kubelet/kuberuntime/kuberuntime_manager.go: import of "k8s.io/client-go/util/workqueue"
Known dependencies are:
	k8s.io/kubernetes/pkg/api/legacyscheme
	k8s.io/kubernetes/pkg/credentialprovider
	k8s.io/kubernetes/pkg/credentialprovider/secrets
	k8s.io/kubernetes/pkg/features
	k8s.io/kubernetes/pkg/kubelet/cm
	k8s.io/kubernetes/pkg/kubelet/container
	k8s.io/kubernetes/pkg/kubelet/events
	k8s.io/kubernetes/pkg/kubelet/images
	k8s.io/kubernetes/pkg/kubelet/kuberuntime/logs
	k8s.io/kubernetes/pkg/kubelet/lifecycle
	k8s.io/kubernetes/pkg/kubelet/metrics
	k8s.io/kubernetes/pkg/kubelet/prober/results
	k8s.io/kubernetes/pkg/kubelet/runtimeclass
	k8s.io/kubernetes/pkg/kubelet/types
	k8s.io/kubernetes/pkg/kubelet/util/cache
	k8s.io/kubernetes/pkg/kubelet/util/format
	k8s.io/kubernetes/pkg/kubelet/util/logreduction
	k8s.io/kubernetes/pkg/security/apparmor
	k8s.io/kubernetes/pkg/securitycontext
	k8s.io/kubernetes/pkg/util/parsers
	k8s.io/kubernetes/pkg/util/selinux
	k8s.io/kubernetes/pkg/util/tail
	k8s.io/api/core/v1
	k8s.io/apimachinery/pkg/apis/meta/v1
	k8s.io/apimachinery/pkg/types
	k8s.io/apimachinery/pkg/util/errors
	k8s.io/apimachinery/pkg/util/runtime
	k8s.io/apimachinery/pkg/util/sets
	k8s.io/apimachinery/pkg/util/version
	k8s.io/apiserver/pkg/util/feature
	k8s.io/client-go/tools/record
	k8s.io/client-go/tools/reference
	k8s.io/client-go/util/flowcontrol
	k8s.io/cri-api/pkg/apis
	k8s.io/cri-api/pkg/apis/runtime/v1alpha2
	github.com/armon/circbuf
	github.com/google/cadvisor/info/v1
	google.golang.org/grpc/status
	k8s.io/klog
	k8s.io/kubernetes/pkg/kubelet/qos
Check that imports in Go sources match importpath attributes in deps.
```

**Comment by hainesc** [comment]
As the suggestion from @dashpole , I can add a container runtimeService throttle in `KubeGenericRuntimeManager` as imagePuller does. see https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/images/helpers.go

It may be a big change to kubelet. I'd like to get more suggestions from others.
@dashpole @derekwaynecarr @mtaufen @vishh @mattjmcnaughton @Random-Liu @yujuhong 

Thanks a lot!

**Comment by AaronLeeIV** [comment]
To be able to create containers in parallel is a really good addition to kubelet, can we revive this PR?

**Comment by choover-broad** [comment]
Just to offer an alternative perspective on this issue:

We have a dependency between our main application container and our sidecar container. If the sidecar does not start up first, application initialization will fail. We (and [some](https://github.com/cloudfoundry/cf-for-k8s/pull/472) [projects](https://github.com/istio/istio/pull/24737) in the wild) are planning to use a postStart hook to make sure the sidecar is healthy before proceeding with application startup.

Until K8s has first-class support for sidecars, serial creation is a feature for us, not a bug.

**Comment by jdomag** [comment]
> Just to offer an alternative perspective on this issue:
> 
> We have a dependency between our main application container and our sidecar container. If the sidecar does not start up first, application initialization will fail. We (and [some](https://github.com/cloudfoundry/cf-for-k8s/pull/472) [projects](https://github.com/istio/istio/pull/24737) in the wild) are planning to use a postStart hook to make sure the sidecar is healthy before proceeding with application startup.
> 
> Until K8s has first-class support for sidecar dependencies, serial creation is a feature for us, not a bug.

I agree.
I guess istio is using that to start a sidecar before the main application in the feature
"holdApplicationUntilProxyStarts"

**Pull request closed without merging**
