### PR TITLE
Remove duplicate scheduler anti-affinity preemption e2e

### PR DESCRIPTION
**Pull request by damemi**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
The removed anti-affinity e2e test is basically exactly covered in integration (see https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler/preemption_test.go#L106). Removing this from e2e will free up CI resources

```release-note
NONE
```

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
/cc @bsalamat 

This is part of the discussion we had weeks ago on converting some of the preemption e2e tests to integration tests. We plan to leave the first 2 tests in this file as e2es. Please let us know, if you're fine with the changes

**Comment by damemi** [comment]
I also have an example here of moving an e2e to integration: https://github.com/kubernetes/kubernetes/pull/80824

**Review by bsalamat — COMMENTED** [review]
/approve

**Pull request merged**
