### PR TITLE
Fix node e2e coreos kubelet cgroup detection

### LINKED ISSUE #26979: Enable CoreOS image in node e2e testing
Due to failures in #26431 and discussions in #26903, CoreOS image was temporarily removed from the node e2e tests (#26978).

The issue needs to be triaged and fixed before we can renable the CoreOS image.

### PR DESCRIPTION
**Pull request by euank**
Fixes #26979 #26431 

The root issue, as best I can tell, is that cgroup detection does not work when the kubelet is started under an ssh session and the systemd `*Accounting` variables are set. I added additional logging and noted some differences in the cgroup slice names between those cadvisor returns and the kubelet detects for itself.
This difference does not occur if the kubelet is properly running under a unit. That environment is also a more common and sane environment.

See also discussion in #26903

cc @derekwaynecarr @vishh @pwittrock

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
Yes!

**Comment by derekwaynecarr** [comment]
Out of curiosity, will CoreOS have user.slice and user session scopes anytime soon?  The cgroup hierarchy we saw associated with sshd was new to me.

**Comment by euank** [comment]
@derekwaynecarr I believe it already does on the alpha channel (1068). When I ssh in, my cgroup is `1:name=systemd:/user.slice/user-500.slice/session-1.scope`, and it's running with systemd 229.

An alternate and significantly simpler solution here might be to just bump to the latest alpha for the e2e image instead of making this change.

If you think that's a better solution, we could try that instead which could also reduce flakyness in a few other ways related to docker bugs.

**Comment by derekwaynecarr** [comment]
@euank - I am very much in favor of this change, so nothing else needed.  It will actually make it easier to get the node e2e to align with the systemd node spec since we will be able to launch the transient unit in a different slice easier with this change.  This code LGTM to me.

**Comment by vishh** [comment]
IIRC, I did see valid, non root, cgroups in ```/proc/`pidof kubelet`/cgroup```. Can we understand why the same logic when run via kubelet process is not working?

**Comment by derekwaynecarr** [comment]
@vishh - it was working for me on RHEL and Fedora (but as i said, i suspect its related to our usage of user.slice and having session scopes that act as the cgroup for the launched process).  do we have to block this PR on that change?  generally, this change is a step in the right direction.

**Comment by derekwaynecarr** [comment]
@euank and I when debugging this saw valid cgroups in the cat /proc/kubelet/croup as well, but they were unable to be resolved via cadvisor (maybe special char handling?)  the @ and : being there was a bit awkward.

**Comment by vishh** [comment]
I'd prefer keeping the e2e suite simpler if at all possible, with minimal
dependencies. I'm not opposed to this change, but I'd prefer understanding
why kubelet fails to detect cgroups via ssh before merging this fix.

**Comment by derekwaynecarr** [comment]
@vishh - wont we need this change anyway when testing qos features soon?  we are going to need to launch kubelet on systemd in a specific slice, this will make it easier to do that.

**Comment by euank** [comment]
@vishh I commented in #26903 what the bug is, so now we know why it fails (a bug in libcontainer's cgroup parsing code).

I think that this is an okay fix in the meanwhile because, as above, this more closely mimics what a user will actually run the kubelet as.

**Comment by vishh** [comment]
OK. Great. I will let @derekwaynecarr review this PR. Overall idea LGTM!

**Comment by pwittrock** [comment]
@vishh Can you make sure the image get pushed to the public project?

**Comment by euank** [comment]
This issue doesn't involve changing the image so there shouldn't be a need for that changes. I did update the environment script with a minor change, but it doesn't have to be run; the code changes are what actually fix the issues referenced.

If we also want to update the image to a modern CoreOS in addition to these changes then yes, please, awesome!

I thought I was going to have to file a separate issue after this one for it though for the sake of simplicity.

**Comment by pwittrock** [comment]
@euank Lets do a second issue for building the new CoreOS image.  If you are able to build the image in a GCE project and give us read access, it is very simple for us to import it.

**Comment by derekwaynecarr** [comment]
Tested PR, and it LGTM.

I think a good follow-on would be to launch etcd and api-server using same pattern, but we can do that another time.

**Pull request merged**
