### PR TITLE
Fix broken link to api-conventions doc.

### PR DESCRIPTION
**Pull request by Hyzhou**
Signed-off-by: misakazhou <misakazhou@tencent.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
/kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Come from this PR: https://github.com/kubernetes/client-go/pull/664
The broken link make a little trouble. I have replaced all of the link the same.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/ok-to-test
/lgtm

In the short term, definitely agree with fixing this.

In the long term, it's interesting to think about how we could have a central source of truth for this information, so we have to touch less files to update it. Does k8s/google have an approved link-shortening tool we could use?

**Comment by BSWANG** [comment]
@mattjmcnaughton Look like CI is broken.

**Comment by Hyzhou** [comment]
@mattjmcnaughtonI merge

**Comment by mattjmcnaughton** [comment]
> @mattjmcnaughton
> 
> I rebase the conflict code. Would you like to review it again? (The CI Is Broken)

Please run `hack/update-generated-protobuf.sh` and `hack/update-openapi-spec.sh`. I think you changed files requiring you the downstream generated files.

**Comment by Hyzhou** [comment]
hack/update-generated-protobuf.sh

**Comment by Hyzhou** [comment]
> > @mattjmcnaughton
> > I rebase the conflict code. Would you like to review it again? (The CI Is Broken)
> 
> Please run `hack/update-generated-protobuf.sh` and `hack/update-openapi-spec.sh`. I think you changed files requiring you the downstream generated files.

Thanks, This step is complete now.

**Review by cmluciano — COMMENTED** [review]
This seems fine to me but I wish we could just rewrite that url somehow and fix this organically with other commits instead of a giant commit.

**Comment by Hyzhou** [comment]
> This seems fine to me but I wish we could just rewrite that url somehow and fix this organically with other commits instead of a giant commit.

I agree. @mattjmcnaughton has the same opinions about it.
We need an issue to discuss that how to solve this problem with a maintainable way. But before the issue, I thinks we can merge this pull request first. 
@cmluciano What about merge this PR and open a new issue to discuss about it? :)

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

+1 to opening an issue to create a more systematic fix for this

**Comment by Hyzhou** [comment]
@cmluciano 
I already add an issues for this. https://github.com/kubernetes/kubernetes/issues/81942

**Comment by lavalamp** [comment]
/approve

There will probably be more offenders by the time you rebase this.

**Comment by Hyzhou** [comment]
> /approve
> 
> There will probably be more offenders by the time you rebase this.

I will rebase it soon

**Comment by Hyzhou** [comment]
@lavalamp The code is rebase and all the test is pass. What about a lgtm to merge it now.

**Comment by lavalamp** [comment]
/lgtm
/milestone v1.16

Thanks!

**Pull request merged**
