### PR TITLE
Fluentd: update fluentd and gems.

### PR DESCRIPTION
**Pull request by desaintmartin**
/kind flake
/sig instrumentation

**What this PR does / why we need it**:

Update fluentd and several gems in order to have latest fixes

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by desaintmartin** [comment]
cc @piosz @coffeepac

This could also be used before https://github.com/kubernetes/kubernetes/pull/70041

**Comment by monotek** [comment]
This will break json logging. 
See: https://github.com/kubernetes/kubernetes/pull/71180

**Comment by desaintmartin** [comment]
@monotek May I close this so that you take over with your PR?

**Comment by monotek** [comment]
Sure :-)

**Pull request closed without merging**
