### PR TITLE
refactor: remove unnesscery param disabledByDefaultControllers

### PR DESCRIPTION
**Pull request by pandaamanda**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Since KnownControllers() include the disabled default controllers, so the param ControllersDisabledByDefault.List() is unnesscery for --controllers config validation.

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by fedebongio** [comment]
Hi @pandaamanda could you give us more information about this PR and what it does / fixes? Maybe create an issue and link if necessary? 
Thanks!

**Comment by pandaamanda** [comment]
> Hi @pandaamanda could you give us more information about this PR and what it does / fixes? Maybe create an issue and link if necessary? Thanks!

update.
tks

**Comment by lavalamp** [comment]
https://github.com/kubernetes/kubernetes/blob/ea4c28c7f86372b82aa8a8a15c9cbdf07098c49a/cmd/kube-controller-manager/app/controllermanager.go#L405

Maybe it doesn't *work* but I don't see how you can say this is unused?

**Comment by lavalamp** [comment]
(e.g. perhaps the validation routine should make sure that the disabled by default controllers are real controllers)

**Comment by pandaamanda** [comment]
> (e.g. perhaps the validation routine should make sure that the disabled by default controllers are real controllers)

Thank you for reply.
The disabled by default controllers are pre-defined with hard coding, so validation for real controllers is not very meaningful.  Maybe it's just for post-expansion.

**Comment by lavalamp** [comment]
> Maybe it's just for post-expansion.

Perhaps-- such users should really have a test case in-tree to make it clear what it's for. Or maybe something happened to it and it used to be more useful. Or maybe we only need it when we change the list.

**Pull request closed without merging**
