### PR TITLE
Update the label manifest with new milestone labels

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Make the milestone labels more noticeable.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
ref: #51663

**Special notes for your reviewer**:
/cc @bgrant0607 @fejta
/assign @grodrigues3 @spxtr

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
Have no idea on the test failures... Should the version be `v1.8.0` or `v1.9.0`?

```
I0902 03:24:59.238] diffing /go/src/k8s.io/kubernetes/federation/apis/openapi-spec against freshly generated federation openapi spec
I0902 03:24:59.244] diff -Naupr -I 'Auto generated by' /go/src/k8s.io/kubernetes/federation/apis/openapi-spec/swagger.json /go/src/k8s.io/kubernetes/_tmp_federation/openapi-spec/swagger.json
I0902 03:24:59.244] --- /go/src/k8s.io/kubernetes/federation/apis/openapi-spec/swagger.json	2017-09-02 03:24:59.202219941 +0000
I0902 03:24:59.244] +++ /go/src/k8s.io/kubernetes/_tmp_federation/openapi-spec/swagger.json	2017-09-02 03:07:44.421511730 +0000
I0902 03:24:59.245] @@ -2,7 +2,7 @@
I0902 03:24:59.245]    "swagger": "2.0",
I0902 03:24:59.245]    "info": {
I0902 03:24:59.245]     "title": "Generic API Server",
I0902 03:24:59.246] -   "version": "v1.9.0"
I0902 03:24:59.246] +   "version": "v1.8.0"
I0902 03:24:59.246]    },
I0902 03:24:59.247]    "paths": {
I0902 03:24:59.247]     "/api/": {
I0902 03:24:59.247] /go/src/k8s.io/kubernetes/federation/apis/openapi-spec is out of date. Please run hack/update-federation-openapi-spec.sh
I0902 03:24:59.257] FAILED   hack/make-rules/../../hack/verify-federation-openapi-spec.sh	188s
```

```
I0902 03:46:46.335] diffing /go/src/k8s.io/kubernetes/api/openapi-spec against freshly generated openapi spec
I0902 03:46:46.344] diff -Naupr -I 'Auto generated by' /go/src/k8s.io/kubernetes/api/openapi-spec/swagger.json /go/src/k8s.io/kubernetes/_tmp/openapi-spec/swagger.json
I0902 03:46:46.345] --- /go/src/k8s.io/kubernetes/api/openapi-spec/swagger.json	2017-09-02 03:46:46.311100681 +0000
I0902 03:46:46.345] +++ /go/src/k8s.io/kubernetes/_tmp/openapi-spec/swagger.json	2017-09-02 03:07:44.197511579 +0000
I0902 03:46:46.345] @@ -2,7 +2,7 @@
I0902 03:46:46.345]    "swagger": "2.0",
I0902 03:46:46.345]    "info": {
I0902 03:46:46.346]     "title": "Kubernetes",
I0902 03:46:46.346] -   "version": "v1.9.0"
I0902 03:46:46.346] +   "version": "v1.8.0"
I0902 03:46:46.346]    },
I0902 03:46:46.346]    "paths": {
I0902 03:46:46.346]     "/api/": {
I0902 03:46:46.347] /go/src/k8s.io/kubernetes/api/openapi-spec is out of date. Please run hack/update-openapi-spec.sh
I0902 03:46:46.356] FAILED   hack/make-rules/../../hack/verify-openapi-spec.sh	130s
```

**Comment by xiangpengzhao** [comment]
The `pull-kubernetes-verify ` flake should be fixed by https://github.com/kubernetes/kubernetes/pull/51851.

**Comment by fejta** [comment]
IMO we should move this file into another repo (kubernetes/test-infra and/or kubernets/repo-infra). Suggesting the idea to sig-contribex on slack

**Review by dims — APPROVED** [review]
They do stand out, let's see how it works! 👍

**Comment by xiangpengzhao** [comment]
>IMO we should move this file into another repo (kubernetes/test-infra and/or kubernets/repo-infra). Suggesting the idea to sig-contribex on slack

@fejta agreed.

**Pull request merged**
