### PR TITLE
coreos/azure: Version bump and doc update

### PR DESCRIPTION
**Pull request by errordeveloper**
- Kubernetes 0.18.0
- etcd 2.0.11
- CoreOS 647.0.0

### CODE REVIEW

**Comment by erictune** [comment]
LGTM.  Update docs/getting-started-guide/README.md if you have a moment.

**Comment by srakesh28** [comment]
Should I be able to download latest rev and try to re-install ?

**Comment by errordeveloper** [comment]
@srakesh28 sure.

**Comment by srakesh28** [comment]
Thanks I verified this works now and able to deploy cluster , connect to it and deploy a  sample gurest workload, however 2 point

1) suggest we add to pre-steps before deploy script 
sudo azure account import <path to your Publishsettigns file>
sudo azure account set <"name of your subscription">

< Note I did not try the scale up step, yet, just wanted to try the App and deploy it for testing> 

2) I was not able to connect to my sample appl of Guestbook after creating a Endpoint at kub-01 as per note, I did not see any services running on port 8000 on container, so not sure if scripts needs to handle appl startup.

**Comment by errordeveloper** [comment]
@srakesh28 I am very glad this patch works for you!

Regarding your 1st point, I am not quite sure why these commands would be required, is `azure login` no longer sufficient? If so, could you please point me at the documentation? (By the way, `sudo` is certainly not required for this.)

And, with respect to your 2nd point, I can see why this might have got broken, but am not quite sure why and would need some assistance from other developer.

I shall raise both of this as new issues and we shall discuss there.

**Comment by srakesh28** [comment]
Thanks a lot.
Regarding 

No 1) azure login did not work for me, I provided my azure subscription user id and password and below is error I get 
info:    Executing command login
warn:    Please note that currently you can login only via Microsoft organizational account or service principal. For instructions on how to set them up, please read http://aka.ms/Dhf67j.
Password: ***********
+ Authenticating...
error:   Server returned error in RSTR - ErrorCode: NONE : FaultMessage: NONE
info:    Error information has been recorded to /home/xxxxxx/.azure/azure.err
error:   login command failed

so I tried out 
azure account import <path to my publishsettings file>  --> to download publish file go to https://manage.windowsazure.com/publishsettings (Login from browser and it will download it) 

 azure account set <"name of your subscription">  --> Name can be found in publishsetting files or from Portal
This worked to proceed to next steps.

No 2)  I don't see anything running in containers as deamon for example guestbook appln, so Endpoint can't connect to services in backed.

**Comment by errordeveloper** [comment]
@srakesh28 please post your comments separately on #9242 and #9244.

**Comment by srakesh28** [comment]
done

**Pull request merged**
