### PR TITLE
Pick the first extension matched

### PR DESCRIPTION
**Pull request by foo0x29a**
**What this PR does / why we need it**:
Since it's possible to match only one file extension, change the ```if``` statement in order to check the condition only once.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fejta** [comment]
This change seem unneeded. The two if statements are mutually exclusive and therefore the elif doesn't change behavior.

**Comment by fejta** [comment]
Fair enough.

As long as you are modifying this section will you please also:
* fix the ` =="generatego"` formatting issue
* remove the blank line between the `if` and `elif`
* Consider moving the `# remove ...` comments onto the same lines as the `if` and `elif`

**Comment by foo0x29a** [comment]
@fejta Thanks for the suggestions. I've updated the commit following your instructions. What do you think?

**Comment by fejta** [comment]
/lgtm
Thanks so much for the work here!!

**Pull request merged**
