### PR TITLE
Version metadata-proxy configmap so rolling updates are triggered when configmap is updated

### PR DESCRIPTION
**Pull request by ikehz**
**What this PR does / why we need it**: Version configmap so rolling updates are triggered when configmap is updated.  Without this, a master restart won't trigger the running nginx pods' configs to change.

Replaces https://github.com/kubernetes/kubernetes/pull/51730 and https://github.com/kubernetes/contrib/pull/2739.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ihmccreery** [comment]
Ref #8867.

**Comment by ihmccreery** [comment]
Ping @mikedanese @cjcullen

**Comment by destijl** [comment]
@Q-Lee mike and CJ are out, can you approve?

**Comment by ihmccreery** [comment]
Ping @Q-Lee for milestone.

**Comment by ihmccreery** [comment]
Ping @Q-Lee

**Comment by ihmccreery** [comment]
This is no longer relevant, since the go version doesn't need a ConfigMap (https://github.com/GoogleCloudPlatform/k8s-metadata-proxy/pull/1).

**Pull request closed without merging**
