### PR TITLE
Revert "Revert "remove legacycloudproviders from staging""

### PR DESCRIPTION
**Pull request by carlory**
This reverts commit d9a0be3b013992b9a50b896ae8751764b8f76037.

#### What type of PR is this?

/kind cleanup
/kind deprecation

#### What this PR does / why we need it:

https://github.com/kubernetes/publishing-bot/pull/434 enhances rules.yaml release branch validation to decouple from changes in k/k. 

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/kubernetes/issues/124771

#### Does this PR introduce a user-facing change?

```release-note
Removed legacy cloud provider integration code (undoing a previous reverted commit)
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Review by akhilerm — APPROVED** [review]

**Comment by sftim** [comment]
Changelog suggestion
```diff
-Revert "Revert "remove legacycloudproviders from staging""
+Removed legacy cloud provider integration code (undoing a previous reverted commit)
```

**Pull request merged**
