### PR TITLE
Fix typo in compressible resource guarantees

### PR DESCRIPTION
**Pull request by Daniel-B-Smith**
**Release note**:
```NONE
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35920)

### CODE REVIEW

**Comment by bgrant0607** [comment]
@k8s-bot ok to test

**Comment by derekwaynecarr** [comment]
The content looks good to me.

**Comment by Daniel-B-Smith** [comment]
Friendly ping about the CLA since I am a Google employee.

**Comment by dims** [comment]
@Daniel-B-Smith : can you please check https://cla.developers.google.com/clas to verify your CLA and check if you have already followed the instruction about email here (https://help.github.com/articles/setting-your-email-in-git/). Note that the e-mail you signed with, the e-mail on your github account, and the e-mail on the git commit must all match to make the bot happy.

**Comment by Daniel-B-Smith** [comment]
@dims Thanks for the advice! The rebase updated my email address to be my @google.com address, so this should be good to go on the CLA front.

**Comment by Daniel-B-Smith** [comment]
@k8s-bot gci gce e2e test this

**Comment by Daniel-B-Smith** [comment]
I didn't notice that the CLA org had changed. I've since associated my account with a Linux foundation account with my @google.com address, so the CLA issue should be fixed now.

**Comment by derekwaynecarr** [comment]
The proposals have been moved to the community repository.

Closing this PR, but feel free to open in the alternate location:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resource-qos.md

**Pull request closed without merging**
