### PR TITLE
Revert "Use go-ansiterm version matching docker/pkg/term/windows v1.11"

### LINKED ISSUE #48887: windows/amd64 cross-build is broken: vendor/github.com/docker/docker/pkg/term/windows
The windows/amd64 cross-build has been failing since yesterday morning.
From https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-cross-build/2320:
```
I0712 10:13:02.637] +++ [0712 10:11:46] windows/amd64: go build started
I0712 10:13:02.637] # k8s.io/kubernetes/vendor/github.com/docker/docker/pkg/term/windows
I0712 10:13:02.637] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:139: undefined: winterm.WORD
I0712 10:13:02.637] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:146: undefined: winterm.WORD
I0712 10:13:02.637] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:210: undefined: winterm.WORD
I0712 10:13:02.637] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:210: undefined: winterm.DWORD
I0712 10:13:02.638] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:226: undefined: winterm.DWORD
```

It looks like #47140 is the culprit. The Azure dependencies were updated, but docker wasn't updated to support the changes until 1.12, and we vendor 1.11.

/assign @brendandburns  
/cc @krousey @kubernetes/sig-windows-bugs

### PR DESCRIPTION
**Pull request by ixdy**
This reverts commit 72044a11a1991bd21d115f1989b5845f927fc40e.

**What this PR does / why we need it**: earlier this week, #47140 updated the vendored azure dependencies, which broke the windows build because the docker dependencies were too old. #48933 was merged, which reverted part of #47140 and fixed the build, but then #48308, which updated the vendored docker dependencies, broke the windows build again.

By reverting #48933, we should get back to a working build, I hope.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #48887

**Release note**:

```release-note
NONE
```
/release-note-none
/test pull-kubernetes-cross
/assign @brendandburns 
cc @karataliu @yguo0905 @yujuhong @dchen1107

### CODE REVIEW

**Comment by ixdy** [comment]
also fixed a small compilation failure missed in #48308 

@yguo0905 PTAL
/assign @yguo0905

**Comment by ixdy** [comment]
/assign @karataliu
too

**Comment by yujuhong** [comment]
/lgtm

Ping @brendanburns for approval.

**Comment by ixdy** [comment]
@brendandburns can I get approval please?

**Pull request merged**
