### PR TITLE
clean up code

### PR DESCRIPTION
**Pull request by lucming**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

**Comment by lucming** [comment]
Is there anything else I should do?

**Comment by lucming** [comment]
pinging @mrhohnfor approval

**Pull request merged**
