### PR TITLE
Add unit test case for storage of resource Podpreset

### PR DESCRIPTION
**Pull request by lichuqiang**
**What this PR does / why we need it**:

add unit test for storage of resource Podpreset

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
@jessfraz @erictune  To whom should podpreset PRs be assigned?

**Comment by jessfraz** [comment]
I can take a look tomorrow

**Comment by lichuqiang** [comment]
close the PR since the test case already added

**Pull request closed without merging**
