### PR TITLE
WIP - Add GCEPD flake debugging

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
Reverts https://github.com/kubernetes/kubernetes/pull/86313, adds debugging for flake timeout

**Which issue(s) this PR fixes**:
xref https://github.com/kubernetes/kubernetes/issues/86181

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/sig storage
/cc @msau42

### CODE REVIEW

**Comment by liggitt** [comment]
flake #86317

**Comment by msau42** [comment]
pd csi driver expansion test flake is https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/433

**Comment by liggitt** [comment]
kind flake: #86317 (CSI mock volume)

**Comment by liggitt** [comment]
flake #86179 
/retest

**Comment by msau42** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/86314/pull-kubernetes-e2e-gce/1206732699679592448/

apiserver logs:
```
I1217 00:57:34.475016       1 httplog.go:90] DELETE /api/v1/namespaces/pv-6190/pods/pvc-tester-2tr9x: (42.771812ms) 200 [kubelet/v1.18.0 (linux/amd64) kubernetes/37ba957 35.227.177.16:43364]
```

e2e log:
```
Dec 17 01:01:38.703: INFO: namespace: {"metadata":{"name":"pv-6190","selfLink":"/api/v1/namespaces/pv-6190","uid":"47eec256-f57d-48ec-8cb4-af1ab436c252","resourceVersion":"30245","creationTimestamp":"2019-12-17T00:52:01Z","deletionTimestamp":"2019-12-17T00:52:35Z","labels":{"e2e-framework":"pv","e2e-run":"f4c2b098-1d0b-4b6f-b491-97a56d3f7a6c"}},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Terminating","conditions":[{"type":"NamespaceDeletionDiscoveryFailure","status":"False","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"ResourcesDiscovered","message":"All resources successfully discovered"},{"type":"NamespaceDeletionGroupVersionParsingFailure","status":"False","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"ParsedGroupVersions","message":"All legacy kube types successfully parsed"},{"type":"NamespaceDeletionContentFailure","status":"True","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"ContentDeletionFailed","message":"Failed to delete all resource types, 1 remaining: unexpected items still remain in namespace: pv-6190 for gvr: /v1, Resource=pods"},{"type":"NamespaceContentRemaining","status":"True","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"SomeResourcesRemain","message":"Some resources are remaining: persistentvolumeclaims. has 1 resource instances, pods. has 1 resource instances"},{"type":"NamespaceFinalizersRemaining","status":"True","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"SomeFinalizersRemain","message":"Some content in the namespace has finalizers remaining: kubernetes.io/pvc-protection in 1 resource instances"}]}}
```

**Comment by liggitt** [comment]
from https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/86314/pull-kubernetes-e2e-gce/1206732699679592448/build-log.txt

> I1217 01:02:45.751] [1mSTEP[0m: Deleting the Namespace
>
> I1217 01:02:45.752] Dec 17 00:57:35.798: INFO: namespace: {"metadata":{"name":"pv-6190","selfLink":"/api/v1/namespaces/pv-6190","uid":"47eec256-f57d-48ec-8cb4-af1ab436c252","resourceVersion":"30245","creationTimestamp":"2019-12-17T00:52:01Z","deletionTimestamp":"2019-12-17T00:52:35Z","labels":{"e2e-framework":"pv","e2e-run":"f4c2b098-1d0b-4b6f-b491-97a56d3f7a6c"}},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Terminating","conditions":[{"type":"NamespaceDeletionDiscoveryFailure","status":"False","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"ResourcesDiscovered","message":"All resources successfully discovered"},{"type":"NamespaceDeletionGroupVersionParsingFailure","status":"False","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"ParsedGroupVersions","message":"All legacy kube types successfully parsed"},{"type":"NamespaceDeletionContentFailure","status":"True","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"ContentDeletionFailed","message":"Failed to delete all resource types, 1 remaining: unexpected items still remain in namespace: pv-6190 for gvr: /v1, Resource=pods"},{"type":"NamespaceContentRemaining","status":"True","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"SomeResourcesRemain","message":"Some resources are remaining: persistentvolumeclaims. has 1 resource instances, pods. has 1 resource instances"},{"type":"NamespaceFinalizersRemaining","status":"True","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"SomeFinalizersRemain","message":"Some content in the namespace has finalizers remaining: kubernetes.io/pvc-protection in 1 resource instances"}]}}
>
> I1217 01:02:45.753] Dec 17 00:57:36.073: INFO: pvc: {"metadata":{"name":"pvc-f4f6k","generateName":"pvc-","namespace":"pv-6190","selfLink":"/api/v1/namespaces/pv-6190/persistentvolumeclaims/pvc-f4f6k","uid":"2bb522dd-d4e3-46ee-adbb-c5000d1bb3e2","resourceVersion":"30193","creationTimestamp":"2019-12-17T00:52:12Z","deletionTimestamp":"2019-12-17T00:57:33Z","deletionGracePeriodSeconds":0,"annotations":{"pv.kubernetes.io/bind-completed":"yes","pv.kubernetes.io/bound-by-controller":"yes"},"finalizers":["kubernetes.io/pvc-protection"]},"spec":{"accessModes":["ReadWriteOnce"],"selector":{"matchLabels":{"e2e-pv-pool":"pv-6190"}},"resources":{"requests":{"storage":"2Gi"}},"volumeName":"gce-vmhtj","storageClassName":"","volumeMode":"Filesystem"},"status":{"phase":"Bound","accessModes":["ReadWriteOnce"],"capacity":{"storage":"2Gi"}}}
>
> I1217 01:02:45.754] Dec 17 00:58:36.770: INFO: namespace: {"metadata":{"name":"pv-6190","selfLink":"/api/v1/namespaces/pv-6190","uid":"47eec256-f57d-48ec-8cb4-af1ab436c252","resourceVersion":"30245","creationTimestamp":"2019-12-17T00:52:01Z","deletionTimestamp":"2019-12-17T00:52:35Z","labels":{"e2e-framework":"pv","e2e-run":"f4c2b098-1d0b-4b6f-b491-97a56d3f7a6c"}},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Terminating","conditions":[{"type":"NamespaceDeletionDiscoveryFailure","status":"False","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"ResourcesDiscovered","message":"All resources successfully discovered"},{"type":"NamespaceDeletionGroupVersionParsingFailure","status":"False","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"ParsedGroupVersions","message":"All legacy kube types successfully parsed"},{"type":"NamespaceDeletionContentFailure","status":"True","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"ContentDeletionFailed","message":"Failed to delete all resource types, 1 remaining: unexpected items still remain in namespace: pv-6190 for gvr: /v1, Resource=pods"},{"type":"NamespaceContentRemaining","status":"True","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"SomeResourcesRemain","message":"Some resources are remaining: persistentvolumeclaims. has 1 resource instances, pods. has 1 resource instances"},{"type":"NamespaceFinalizersRemaining","status":"True","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"SomeFinalizersRemain","message":"Some content in the namespace has finalizers remaining: kubernetes.io/pvc-protection in 1 resource instances"}]}}
>
> I1217 01:02:45.755] Dec 17 00:59:37.474: INFO: namespace: {"metadata":{"name":"pv-6190","selfLink":"/api/v1/namespaces/pv-6190","uid":"47eec256-f57d-48ec-8cb4-af1ab436c252","resourceVersion":"30245","creationTimestamp":"2019-12-17T00:52:01Z","deletionTimestamp":"2019-12-17T00:52:35Z","labels":{"e2e-framework":"pv","e2e-run":"f4c2b098-1d0b-4b6f-b491-97a56d3f7a6c"}},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Terminating","conditions":[{"type":"NamespaceDeletionDiscoveryFailure","status":"False","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"ResourcesDiscovered","message":"All resources successfully discovered"},{"type":"NamespaceDeletionGroupVersionParsingFailure","status":"False","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"ParsedGroupVersions","message":"All legacy kube types successfully parsed"},{"type":"NamespaceDeletionContentFailure","status":"True","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"ContentDeletionFailed","message":"Failed to delete all resource types, 1 remaining: unexpected items still remain in namespace: pv-6190 for gvr: /v1, Resource=pods"},{"type":"NamespaceContentRemaining","status":"True","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"SomeResourcesRemain","message":"Some resources are remaining: persistentvolumeclaims. has 1 resource instances, pods. has 1 resource instances"},{"type":"NamespaceFinalizersRemaining","status":"True","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"SomeFinalizersRemain","message":"Some content in the namespace has finalizers remaining: kubernetes.io/pvc-protection in 1 resource instances"}]}}
>
> I1217 01:02:45.756] Dec 17 01:00:38.000: INFO: namespace: {"metadata":{"name":"pv-6190","selfLink":"/api/v1/namespaces/pv-6190","uid":"47eec256-f57d-48ec-8cb4-af1ab436c252","resourceVersion":"30245","creationTimestamp":"2019-12-17T00:52:01Z","deletionTimestamp":"2019-12-17T00:52:35Z","labels":{"e2e-framework":"pv","e2e-run":"f4c2b098-1d0b-4b6f-b491-97a56d3f7a6c"}},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Terminating","conditions":[{"type":"NamespaceDeletionDiscoveryFailure","status":"False","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"ResourcesDiscovered","message":"All resources successfully discovered"},{"type":"NamespaceDeletionGroupVersionParsingFailure","status":"False","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"ParsedGroupVersions","message":"All legacy kube types successfully parsed"},{"type":"NamespaceDeletionContentFailure","status":"True","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"ContentDeletionFailed","message":"Failed to delete all resource types, 1 remaining: unexpected items still remain in namespace: pv-6190 for gvr: /v1, Resource=pods"},{"type":"NamespaceContentRemaining","status":"True","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"SomeResourcesRemain","message":"Some resources are remaining: persistentvolumeclaims. has 1 resource instances, pods. has 1 resource instances"},{"type":"NamespaceFinalizersRemaining","status":"True","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"SomeFinalizersRemain","message":"Some content in the namespace has finalizers remaining: kubernetes.io/pvc-protection in 1 resource instances"}]}}
>
> I1217 01:02:45.757] Dec 17 01:01:38.703: INFO: namespace: {"metadata":{"name":"pv-6190","selfLink":"/api/v1/namespaces/pv-6190","uid":"47eec256-f57d-48ec-8cb4-af1ab436c252","resourceVersion":"30245","creationTimestamp":"2019-12-17T00:52:01Z","deletionTimestamp":"2019-12-17T00:52:35Z","labels":{"e2e-framework":"pv","e2e-run":"f4c2b098-1d0b-4b6f-b491-97a56d3f7a6c"}},"spec":{"finalizers":["kubernetes"]},"status":{"phase":"Terminating","conditions":[{"type":"NamespaceDeletionDiscoveryFailure","status":"False","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"ResourcesDiscovered","message":"All resources successfully discovered"},{"type":"NamespaceDeletionGroupVersionParsingFailure","status":"False","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"ParsedGroupVersions","message":"All legacy kube types successfully parsed"},{"type":"NamespaceDeletionContentFailure","status":"True","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"ContentDeletionFailed","message":"Failed to delete all resource types, 1 remaining: unexpected items still remain in namespace: pv-6190 for gvr: /v1, Resource=pods"},{"type":"NamespaceContentRemaining","status":"True","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"SomeResourcesRemain","message":"Some resources are remaining: persistentvolumeclaims. has 1 resource instances, pods. has 1 resource instances"},{"type":"NamespaceFinalizersRemaining","status":"True","lastTransitionTime":"2019-12-17T00:57:34Z","reason":"SomeFinalizersRemain","message":"Some content in the namespace has finalizers remaining: kubernetes.io/pvc-protection in 1 resource instances"}]}}

**Comment by msau42** [comment]
kubelet deleted pod from apiserver:
```
I1217 00:57:34.476737    1355 status_manager.go:564] Pod "pvc-tester-2tr9x_pv-6190(eaa4a604-e7e5-42a7-a5b7-670856a5af66)" fully terminated and removed from etcd
I1217 00:57:34.480713    1355 kubelet.go:1916] SyncLoop (REMOVE, "api"): "pvc-tester-2tr9x_pv-6190(eaa4a604-e7e5-42a7-a5b7-670856a5af66)"
I1217 00:57:34.480766    1355 kubelet.go:2111] Failed to delete pod "pvc-tester-2tr9x_pv-6190(eaa4a604-e7e5-42a7-a5b7-670856a5af66)", err: pod not found
```

pvc protection controller removed finalizer:
```
I1217 00:57:36.457154       1 pvc_protection_controller.go:146] Processing PVC pv-6190/pvc-f4f6k
I1217 00:57:36.457163       1 pvc_protection_controller.go:231] Looking for Pods using PVC pv-6190/pvc-f4f6k in the Informer's cache
I1217 00:57:36.457170       1 pvc_protection_controller.go:244] No Pod using PVC pv-6190/pvc-f4f6k was found in the Informer's cache
I1217 00:57:36.457176       1 pvc_protection_controller.go:249] Looking for Pods using PVC pv-6190/pvc-f4f6k with a live list
I1217 00:57:36.571533       1 pvc_protection_controller.go:262] PVC pv-6190/pvc-f4f6k is unused
I1217 00:57:37.059466       1 pvc_protection_controller.go:208] Removed protection finalizer from PVC pv-6190/pvc-f4f6k
I1217 00:57:37.059494       1 pvc_protection_controller.go:149] Finished processing PVC pv-6190/pvc-f4f6k (602.332672ms)

I1217 00:57:37.503487       1 pvc_protection_controller.go:146] Processing PVC pv-6190/pvc-f4f6k
I1217 00:57:37.503498       1 pvc_protection_controller.go:154] PVC pv-6190/pvc-f4f6k not found, ignoring
I1217 00:57:37.503503       1 pvc_protection_controller.go:149] Finished processing PVC pv-6190/pvc-f4f6k (10.802µs)

```

**Comment by liggitt** [comment]
looks like at one point, the namespace controller observes pvc and pod remaining:
> `Failed to delete all resource types, 1 remaining: unexpected items still remain in namespace: pv-6190 for gvr: /v1, Resource=pods`
> `Some resources are remaining: persistentvolumeclaims. has 1 resource instances, pods. has 1 resource instances`

the first time we start logging in the e2e (which is after waiting for 5 minutes, after the test would have already failed previously), the pvc still exists with a finalizer on it:
> `Dec 17 00:57:36.073: INFO: pvc: {"metadata":{"name":"pvc-f4f6k","generateName":"pvc-","namespace":"pv-6190","selfLink":"/api/v1/namespaces/pv-6190/persistentvolumeclaims/pvc-f4f6k","uid":"2bb522dd-d4e3-46ee-adbb-c5000d1bb3e2","resourceVersion":"30193","creationTimestamp":"2019-12-17T00:52:12Z","deletionTimestamp":"2019-12-17T00:57:33Z","deletionGracePeriodSeconds":0,"annotations":{"pv.kubernetes.io/bind-completed":"yes","pv.kubernetes.io/bound-by-controller":"yes"},"finalizers":["kubernetes.io/pvc-protection"]}`

It looks like within the next minute (so ~6 minutes after deleting the namespace), the pvc is finally gone, but the namespace controller doesn't react to that. It may be in backoff and have given up on processing the namespace until a resync or a namespace update, I'm not sure...

**Comment by liggitt** [comment]
So there are two things to investigate:
1. Why is the PVC finalizer taking 5-6 minutes to be removed and the PVC deleted?
2. Why is the namespace controller not responding quickly to the cleanup of the remaining resources on a previously stuck namespace? (I'm not actually sure it is intended to... to do that it would have to watch *all* namespaced resources)

**Comment by msau42** [comment]
Namespace controller did not start deleting until 00:57:
```
I1217 00:57:15.353790       1 namespaced_resources_deleter.go:506] namespace controller - deleteAllContent - namespace: pv-6190
```

**Comment by msau42** [comment]
apiserver request came at 00:52
```
I1217 00:52:35.474878       1 httplog.go:90] DELETE /api/v1/namespaces/pv-6190: (5.491637ms) 200 [e2e.test/v0.0.0 (linux/amd64) kubernetes/$Format -- [sig-storage] PersistentVolumes GCEPD should test that deleting the Namespace of a PVC and Pod causes the successful detach of Persistent Disk 34.67.156.235:36974]
```

**Comment by liggitt** [comment]
From API server log:

Namespace delete:
> I1217 00:52:35.474878       1 httplog.go:90] DELETE /api/v1/namespaces/pv-6190: (5.491637ms) 200 [e2e.test/v0.0.0 (linux/amd64) kubernetes/$Format -- [sig-storage] PersistentVolumes GCEPD should test that deleting the Namespace of a PVC and Pod causes the successful detach of Persistent Disk 34.67.156.235:36974]

First interaction with anything in the namespace from the namespace controller:
> I1217 00:57:15.224748       1 httplog.go:90] GET /api/v1/namespaces/pv-6190: (19.010794ms) 200 [kube-controller-manager/v1.18.0 (linux/amd64) kubernetes/37ba957/system:serviceaccount:kube-system:namespace-controller [::1]:58760]
> I1217 00:57:15.831146       1 httplog.go:90] DELETE /api/v1/namespaces/pv-6190/replicationcontrollers: (55.486574ms) 200 [kube-controller-manager/v1.18.0 (linux/amd64) kubernetes/37ba957/system:serviceaccount:kube-system:namespace-controller [::1]:58760]

That's ~4:40 later. Pods get deleted ~4:45 after the namespace was deleted:

> I1217 00:57:18.356692       1 httplog.go:90] DELETE /api/v1/namespaces/pv-6190/pods: (907.108945ms) 200 [kube-controller-manager/v1.18.0 (linux/amd64) kubernetes/37ba957/system:serviceaccount:kube-system:namespace-controller [::1]:58760]

That leaves only 15 seconds for the kubelet to observe the pod delete, kill the process, update pod status to stopped, and try to delete the pod with no grace period:
> I1217 00:57:21.228301       1 httplog.go:90] PATCH /api/v1/namespaces/pv-6190/pods/pvc-tester-2tr9x/status: (69.065436ms) 200 [kubelet/v1.18.0 (linux/amd64) kubernetes/37ba957 35.227.177.16:43364]
> 
> I1217 00:57:34.418818       1 httplog.go:90] PATCH /api/v1/namespaces/pv-6190/pods/pvc-tester-2tr9x/status: (12.514663ms) 200 [kubelet/v1.18.0 (linux/amd64) kubernetes/37ba957 35.227.177.16:43364]
> 
> I1217 00:57:34.475016       1 httplog.go:90] DELETE /api/v1/namespaces/pv-6190/pods/pvc-tester-2tr9x: (42.771812ms) 200 [kubelet/v1.18.0 (linux/amd64) kubernetes/37ba957 35.227.177.16:43364]

the pvc protection to remove the pvc finalizer (which auto-deleted the pvc):

> I1217 00:57:37.015818       1 httplog.go:90] PUT /api/v1/namespaces/pv-6190/persistentvolumeclaims/pvc-f4f6k: (392.718672ms) 200 [kube-controller-manager/v1.18.0 (linux/amd64) kubernetes/37ba957/system:serviceaccount:kube-system:pvc-protection-controller [::1]:58760]

**Comment by liggitt** [comment]
graphed namespace controller lag times:
* from namespace delete to start of processing (average 3:36, min 0:05, max 5:41)
* from start of processing to end of processing (average 0:43, min 0:01, max 23:35)

https://docs.google.com/spreadsheets/d/1hYxDyvZ9o-3T0WrOJ7LgW-sxQn62fU8RWfDjm02OoLc/edit#gid=1101829529

The namespace controller, as configured, can't keep up with the parallelism of the e2e jobs. For most tests, this doesn't fail the test because the e2e job waits at the end for namespace deletion to complete. For the GCEPD test, namespace deletion is a synchronous part of the test. Depending on where the GCEPD test fell, the controller was sometimes too backed up to finish removing the namespace in time.

**Pull request closed without merging**
