### PR TITLE
test/e2e/storage : use framework.Equal() replace gomega.Expect(...).To(gomega.BeTrue(),...)

### PR DESCRIPTION
**Pull request by tanjunchen**
**What type of PR is this?**

/kind cleanup
 
**What this PR does / why we need it**:

use framework.Equal(sth,True,explain...) replace gomega.Expect(sth).To(gomega.BeTrue(),explain...)
and then we can remove  **gomega**  in some folders

**Which issue(s) this PR fixes**:

Ref: #79686

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by tanjunchen** [comment]
pull-kubernetes-e2e-kind

**Comment by tanjunchen** [comment]
/cc @oomichi
/cc @liggitt 
Thanks

**Comment by jsafrane** [comment]
/lgtm
from storage perspective

**Comment by liggitt** [comment]
> /cc @liggitt
> Thanks

storage test owners can approve this

**Pull request merged**
