### PR TITLE
Corrected ARCH

### LINKED ISSUE #75114: k8s.gcr.io/kube-cross does not work under other architectures like arm64
There's something wrong with the [manifests for kube-cross](https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/kube-cross?gcrImageListsize=30) as the image we publish though it seems to have manifests does not work on other platforms like arm64
```
standard_init_linux.go:207: exec user process caused "exec format error"
```

Please see some environment information
```
openlab@node-0:~$ docker version
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:45:34 2019
 OS/Arch:           linux/arm64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:00:18 2019
  OS/Arch:          linux/arm64
  Experimental:     false
openlab@node-0:~$ uname -a
Linux node-0.dims.openlab-pg0.utah.cloudlab.us 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:53 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
openlab@node-0:~$ docker pull k8s.gcr.io/kube-cross:v1.12.0-1
v1.12.0-1: Pulling from kube-cross
741437d97401: Pull complete
34d8874714d7: Pull complete
0a108aa26679: Pull complete
7f0334c36886: Pull complete
d35724ed4672: Pull complete
d0ea18b1198f: Pull complete
647e63f91386: Pull complete
2b8c6ef26d61: Pull complete
e4c484d78610: Pull complete
e9b4d7c90f68: Pull complete
96fe66b8cafb: Pull complete
cc5a03814b47: Pull complete
e1dc59942b8c: Pull complete
0c842fd38bf6: Pull complete
Digest: sha256:5beba1349458d62edb8b672f0c5a8af4eb3cec4d066015368bf722416bdbfc78
Status: Downloaded newer image for k8s.gcr.io/kube-cross:v1.12.0-1
openlab@node-0:~$ docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kube-cross   v1.12.0-1           bf7729bdb359        7 days ago          1.75GB
openlab@node-0:~$ docker run -it k8s.gcr.io/kube-cross:v1.12.0-1 bash
standard_init_linux.go:207: exec user process caused "exec format error"
```

### PR DESCRIPTION
**Pull request by AnitaNayak**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Building Docker Image kube-cross.
**Which issue(s) this PR fixes**:
To Fix https://github.com/kubernetes/kubernetes/issues/75114
*Automatically closes linked issue when PR is merged.
Usage: `Fixes #<issue number>`, or `Fixes (paste link of issue)`.
_If PR is about `failing-tests or flakes`, please post the related issues/tests in a comment and do not use `Fixes`_*
-->
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

Enter your extended release note in the block below. If the PR requires additional action from users switching to the new release, include the string "action required".

### CODE REVIEW

**Comment by AnitaNayak** [comment]
Test result on x86_64 system:
```
Step 12/12 : RUN export ETCD_VERSION=v3.2.24;   mkdir -p /usr/local/src/etcd   && cd /usr/local/src/etcd   && curl -fsSL https://github.com/coreos/etcd/releases/download/${ETCD_VERSION}/etcd-${ETCD_VERSION}-linux-amd64.tar.gz | tar -xz   && ln -s ../src/etcd/etcd-${ETCD_VERSION}-linux-amd64/etcd /usr/local/bin/
 ---> Running in 4c05d8a905cd
Removing intermediate container 4c05d8a905cd
 ---> 44f7e6805aba
Successfully built 44f7e6805aba
Successfully tagged staging-k8s.gcr.io/kube-cross:v1.13.4-1
```
```
docker run -it --name kube-cross staging-k8s.gcr.io/kube-cross:v1.13.4-1 bash -c "uname -a"
Linux 7ade92f0c085 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 GNU/Linux
```
Will perform testing on ppc64le.

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Comment by BenTheElder** [comment]
for most changes we'd want to bump the version and push the image, but this should not change the existing image so.

**Comment by AnitaNayak** [comment]
@BenTheElder , Please let me know if I should bump the version as `1.13.4-2`. Should we bump the version of protoc to latest?

**Comment by BenTheElder** [comment]
Let's not bump that right now, we're in code freeze and this change is
otherwise trivial / non-breaking

**Comment by BenTheElder** [comment]
I think bumping protoc is somewhat involved

**Comment by AnitaNayak** [comment]
Protoc version 3.0.2 : https://github.com/protocolbuffers/protobuf/releases/tag/v3.0.2 , zip file is available only for x86_64 (https://github.com/protocolbuffers/protobuf/releases/download/v3.0.2/protoc-3.0.2-linux-x86_64.zip). Its not available for other platform.
The latest is https://github.com/protocolbuffers/protobuf/releases/tag/v3.10.0. Should we bump this. Have to test thoroughly.

**Comment by BenTheElder** [comment]
We cannot bump protoc without bumping the build image version and pushing a new build image.
I'm not sure what else, but I think we're very unlikely to do that during code freeze, it will have to wait for v1.18

Cc @liggitt

**Comment by AnitaNayak** [comment]
Hi @BenTheElder, did one more commit to take care following scenario.  
1. Protoc version updated to 3.10.0 with Arch detail 
2. Image version bumped to 1.13.4-2
Just made the changes so that review can be done now, though merge can happen post release.

**Comment by AnitaNayak** [comment]
Reverted version from 1.13.4-2 to 1.13.4-1(original), to check if all checks are passing.

**Comment by mkumatag** [comment]
Just these changes are not enough, we need to make sure to change whole process to build and push manifest of this image on x86 platform. I think @dims worked on this in the past, @dims do you have that PR handy which @AnitaNayak can refer?

**Comment by AnitaNayak** [comment]
Thank you for reviewing. Will update it as per review comment.

**Comment by BenTheElder** [comment]
I still want someone familiar without encoding etc. to approve protoc changes, besides making the image multi Arch and getting that pushed.
/assign @liggitt

**Comment by liggitt** [comment]
> I still want someone familiar without encoding etc. to approve protoc changes

do we know what the regenerated pb.go files will looks like with this version of protoc?

**Comment by AnitaNayak** [comment]
Hi @liggitt , are you working on it? Shall I try multi arching this and docker manifest on this with updated protoc version? Let me know. Thank you.

**Comment by liggitt** [comment]
> Hi @liggitt , are you working on it? Shall I try multi arching this and docker manifest on this with updated protoc version?

yes, can you try running `make update` with the updated protoc version and report what the diff is?

**Comment by AnitaNayak** [comment]
Hi @liggitt , do you mean `make update` on `kubernetes/build/build-image/cross`? There is no `update` target. Please correct me.

**Comment by AnitaNayak** [comment]
Hi @liggitt , shall I try refactoring kube-cross? Please let me know.

**Comment by liggitt** [comment]
> Hi @liggitt , do you mean `make update` on `kubernetes/build/build-image/cross`? There is no `update` target.

No, I meant run `make update` on kubernetes/kubernetes with locally updated kube-cross images containing this change (to test running the protobuf generation scripts with the new version of protoc)

**Comment by AnitaNayak** [comment]
Sorry for the delay... below is the output for `make update`
```
root@prime-x86:/usr# cd ~/kubernetes/
root@prime-x86:~/kubernetes# make update
+++ [1212 07:32:11] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
+++ [1212 07:32:22] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/defaulter-gen
+++ [1212 07:32:30] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/conversion-gen
+++ [1212 07:32:44] Building go targets for linux/amd64:
    ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
+++ [1212 07:32:59] Building go targets for linux/amd64:
    ./vendor/github.com/go-bindata/go-bindata/go-bindata
Running in silent mode, run with SILENT=false if you want to see script logs.
Running in short-circuit mode; run with FORCE_ALL=true to force all scripts to run.
Running update-generated-protobuf
Running update-codegen
Running update-generated-runtime
Running update-generated-device-plugin
Running update-generated-api-compatibility-data
Running update-generated-docs
# k8s.io/kubernetes/third_party/forked/gonum/graph/simple
compile: writing output: write $WORK/b1236/_pkg_.a: no space left on device
go build k8s.io/kubernetes/third_party/forked/gonum/graph/internal/linear: mkdir /tmp/go-build847027628/b1239/: no space left on device
go build k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac/bootstrappolicy: mkdir /tmp/go-build847027628/b1240/: no space left on device
```

**Comment by zhlhahaha** [comment]
Hi, @liggitt , I tried to apply this PR, and then do "make update".
kubernetes version: 1afb554222605d4d67a911c9bbb0fa5b1049c2dc
Following is the output:
`Running in silent mode, run with SILENT=false if you want to see script logs.
Running in short-circuit mode; run with FORCE_ALL=true to force all scripts to run.
Running update-generated-protobuf
Running update-codegen
Running update-generated-runtime
Running update-generated-device-plugin
Running update-generated-api-compatibility-data
Running update-generated-docs
I0305 07:58:55.170332   10643 registry.go:150] Registering EvenPodsSpread predicate and priority function
I0305 07:58:55.170382   10643 registry.go:150] Registering EvenPodsSpread predicate and priority function
I0305 07:58:55.650625   10694 registry.go:150] Registering EvenPodsSpread predicate and priority function
I0305 07:58:55.650675   10694 registry.go:150] Registering EvenPodsSpread predicate and priority function
Running update-generated-swagger-docs
Running update-openapi-spec
Running update-bazel
Running update-gofmt
Update scripts completed successfully
`

**Comment by fejta** [comment]
Please rebase and/or close

**Comment by fejta** [comment]
Actually please rebase and reopen if you still intend to work on this.

**Pull request closed without merging**
