### PR TITLE
Update help.sh

### PR DESCRIPTION
**Pull request by syxunion**
Hello,

I notice a missing Chinese translation for a field

### CODE REVIEW

**Comment by eddiezane** [comment]
Thank you for the PR!

/ok-to-test
/lgtm
/approve

**Comment by eddiezane** [comment]
Actually apologies, I don't think this is right. This is just a test - the translation needs to be added.

See

https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubectl/pkg/util/i18n/translations

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/util/i18n/translations/kubectl/zh_TW/LC_MESSAGES/k8s.po

/unapprove
/lgtm cancel

**Comment by pacoxu** [comment]
/lgtm cancel

https://github.com/kubernetes/kubernetes/pull/114941#issuecomment-1401034598
Sorry, I missed the comment

**Comment by pacoxu** [comment]
> Actually apologies, I don't think this is right. This is just a test - the translation needs to be added.
> 
> See
> 
> https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubectl/pkg/util/i18n/translations
> 
> https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/util/i18n/translations/kubectl/zh_TW/LC_MESSAGES/k8s.po

The ci failure still need to be addressed. @syxunion  do you have time to fix it?

**Comment by dims** [comment]
it's been a while with no response from @syxunion let's close this for now until someone can resurrect this PR and fix the broken CI job

/close

**Pull request closed without merging**
