### PR TITLE
Improve code coverage in pkg/api/v1/validation

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
@k8s-bot ok to test

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this
@k8s-bot pull-kubernetes-unit test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this
@k8s-bot pull-kubernetes-verify test this

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-verify test this

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-verify test this

**Comment by zjj2wry** [comment]
@liggitt i execute hack/make-rules/../../hack/verify-bazel.sh to fix **pull-kubernetes-verify test**, so test restart. but code not change. think you :)

**Comment by zjj2wry** [comment]
@liggitt the test report 
```
W0606 20:41:21.284] pkg/api/v1/validation/validation_test.go:63: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1.Time composite literal uses unkeyed fields
```
but the struct
```
type Time struct {
	time.Time `protobuf:"-"`
}
```
is unkeyed. I can`t use &metav1.Time{time.Now()} initialize？

**Comment by liggitt** [comment]
> I can`t use &metav1.Time{time.Now()} initialize？

`&metav1.Time{Time: time.Now()}` should do what you want

**Comment by zjj2wry** [comment]
@liggitt think you for your help 😊

**Comment by zjj2wry** [comment]
@liggitt the default lib from ```"k8s.io/kubernetes/pkg/api/v1"``` to ```"k8s.io/api/core/v1"```, but code not change. thanks

**Comment by liggitt** [comment]
```
I0630 04:41:46.140] Boilerplate header is wrong for: /go/src/k8s.io/kubernetes/pkg/api/v1/validation/validation_test.go
I0630 04:41:46.142] FAILED   hack/make-rules/../../hack/verify-boilerplate.sh	2s
```

**Comment by zjj2wry** [comment]
@liggitt sorry for delay. updated, thanks

**Comment by zjj2wry** [comment]
@smarterclayton  i has rebase but the ```rebase``` label don't remove. can you help remove it. and this is a simple table test, mind for approve it? thanks 😄

**Pull request closed without merging**
