### PR TITLE
improve hairpin warning message for network policy tests

### LINKED ISSUE #98581: network policy warning message is misleading -- needs clarification
**What happened**:

> 2021-01-29T18:05:05.3202135Z Jan 29 18:04:26.404: INFO: warning: the results of 9 pod->pod cases have been ignored

**What you expected to happen**:

> 2021-01-29T18:05:05.3202135Z Jan 29 18:04:26.404: INFO: warning: this test doesn't take into consideration hairpin traffic, i.e. traffic that is originated from one pod with same pod as destination: 9 cases ignored

**How to reproduce it (as minimally and precisely as possible)**:

Run the netpol test suite.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by mattfenwick**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Clarifies warning message in network policy tests, so that users understand why test cases are being ignored.

**Which issue(s) this PR fixes**:

Fixes #98581 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by knabben** [comment]
the warning message is pretty clear.

/lgtm

**Comment by aojea** [comment]
/retest
/assign @MrHohn
for approval
/lgtm
Thanks for the prompt response

**Comment by aojea** [comment]
ahh cool, so you have approval in the folder :+1:

**Pull request merged**
