### PR TITLE
change the included file name in definitions.md and operations.md

### PR DESCRIPTION
**Pull request by caesarxuchao**
Needs to go in with #15876 
cc @RichieEscarez

### CODE REVIEW

**Comment by nikhiljindal** [comment]
This wont break any links from operations.html to definitions.html?

**Comment by caesarxuchao** [comment]
It will break the links when browsed from https://htmlpreview.github.io, but the links are broken there anyway...

The links will work on k8s.io, because the name of the webpage is the same as the .md files, I just change the name of the included html file.

**Comment by RichieEscarez** [comment]
lgtm from my perspective. 

**Question**: In what directory in gh-pages will these new extensions/v1beta1 api files end up? 

For v1.1, the API files will be in: 
"...v1.**1**/docs/api-reference/operations.html(*/definitions.html*)"

Will the "v1beta1 extension" API files be in another directory? For example:
"...v1.**1**/docs/api-reference/**extensions**/operations.html(*/definitions.html*)"

Let me know and ill make sure that they show up in the new v1.1 navigation menu #15903

**Comment by caesarxuchao** [comment]
@RichieEscarez, Should be like the following:
v1.1/docs/api-reference/v1/operations.html
v1.1/docs/api-reference/v1/definitions.html
v1.1/docs/api-reference/extensions/v1beta1/operations.html
v1.1/docs/api-reference/extensions/v1beta1/definitions.html

Thanks.

**Comment by nikhiljindal** [comment]
IIUC, the links wont break.
We are not renaming the html files on HEAD, so when we view them on HEAD using htmlpreview they will still work fine.
When we move them to gh-pages and rename, we should not be viewing them using htmlpreview. We should be using kubernetes.io (https://github.com/kubernetes/kubernetes/issues/13149).

So this change LGTM!

**Comment by caesarxuchao** [comment]
Correct other than this one
> When we move them to gh-pages and rename

The generated html on gh-pages will be the one I listed above https://github.com/kubernetes/kubernetes/pull/15877#issuecomment-149439321, no renaming is required.

**Comment by ixdy** [comment]
sorry, failure caused by restarting Jenkins.
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Pull request merged**
