### PR TITLE
Fix a few typos in comments

### PR DESCRIPTION
**Pull request by goltermann**

### CODE REVIEW

**Comment by deads2k** [comment]
@k8s-bot test this #24628

**Comment by deads2k** [comment]
k8s-bot test this issue: #24628

**Comment by goltermann** [comment]
@k8s-bot test this issue: #24628

**Comment by goltermann** [comment]
@deads2k Thanks for helping prod this along.  I'm going to add the e2e-not-required label too, so it doesn't get hung up in the queue on flakes.

**Pull request merged**
