### PR TITLE
WIP: prototype watchable discovery via discovery.k8s.io/v1alpha1

### PR DESCRIPTION
**Pull request by sttts**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by gmarek** [comment]
@kubernetes/sig-api-machinery-api-reviews

**Comment by sttts** [comment]
Want to investigate how ugly an in-memory storage implementation is for this. The api is up for discussion and should be part of a proposal PR.

**Comment by caesarxuchao** [comment]
@sttts I'm considering if watching `APIService` is an alternative to watch the discovery API. By watching `APIServices`, client can know what [groups/versions](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/types.go#L47-L50) are supported. Does that solve the most use cases?

One missing piece of APIServices is that  CRD is not registered to the APIServices. Is there plan to do so?

**Comment by liggitt** [comment]
> I'm considering if watching APIService is an alternative to watch the discovery API.

It seems wrong to treat discovery API as authoritative but trigger updates by watching a different source.

> CRD is not registered to the APIServices

that is incorrect. auto-registering APIService objects is how CRD works. see https://github.com/kubernetes/kubernetes/blob/master/pkg/master/controller/crdregistration/crdregistration_controller.go#L65

**Comment by caesarxuchao** [comment]
Thanks @liggitt. Also `APIService` doesn't include resource-level information, so watching `APIServices` is not enough.

**Comment by sttts** [comment]
> Also APIService doesn't include resource-level information, so watching APIServices is not enough.

Discussing with @mbohlool recently we got the idea of using a status subresource on `APIService` to list resources. Security-wise it is not a good idea to let every API server write its own `APIService`.  So a subresource would solve that.

But, I somehow agree with @liggitt:

> It seems wrong to treat discovery API as authoritative but trigger updates by watching a different source.

**Pull request closed without merging**
