### PR TITLE
WIP: nil and empty slices are not semantically eq

### PR DESCRIPTION
**Pull request by thockin**
@smarterclayton I think I got all the JSON and conversion bits ferreted out.  Tests blow up when we encode to proto and back.  Thoughts?  

@danwinship This may be too brittle to actually use, though...

### CODE REVIEW

**Comment by smarterclayton** [comment]
Surprisingly small.

**Comment by thockin** [comment]
@smarterclayton I don't know enough about what you're doing with proto to fix the breakage.  See SubjectAccessReviewSpec.Extra.  The map value gets roundtrip-converted from nil to an empty slice.

**Comment by smarterclayton** [comment]
All the failures here seem to be the nil/empty ish being ignored for things that were round tripped.  Didn't see errors on SubjectAccessReviewSpec.Extra

I think the round trip failures are indicative of the round trip test depends on nil / empty behavior (since proto will always create empty arrays, I think).  Will look further soon.

**Comment by thockin** [comment]
Yes, the failure is proto, which takes a `[]Foo(nil)`, marshals int and
unmarshals it, and produces a `[]Foo{}`.  If we can't fix that, then this
PR/idea is dead.

**Comment by thockin** [comment]
And to be clear: that's OK.  If that is the state of things, we should just
accept and document that, and move on.  You could probably also undo the
"wrap a slice in a struct" proto gunk you added.

**Comment by smarterclayton** [comment]
The problem is with the test, not with proto.  Proto doesn't distinguish,
except where we have constructs that do.  That doesn't mean that the global
"semantic equal" should consider nil equal to empty - semantic should only
assume that for things that are omitempty.

**Comment by thockin** [comment]
@smarterclayton I don't understand your comment.  I serialize to proto then deserialize back to struct and the result is different.  The automatic tests are not capturing my logged debug output.  from local:

```
E1203 15:57:32.326070    5188 serialization_test.go:170] TIM: before roundTripSame::roundTrip: codec &{0xc420316b40 0xc420316b40 {0xc420299a40} 0xc420299a40 0xc420299a40 0xc420299a40 0xc420299a40 [{storage.k8s.io v1beta1} {rbac.authorization.k8s.io v1alpha1} {certificates.k8s.io v1alpha1} {batch v1} { v1} {imagepolicy.k8s.io v1alpha1} {apps v1beta1} {policy v1beta1} {authorization.k8s.io v1beta1} {kubeadm.k8s.io v1alpha1} {federation v1beta1} {extensions v1beta1} {autoscaling v1} {authentication.k8s.io v1beta1}] {}}

E1203 15:57:32.326091    5188 serialization_test.go:97] TIM: starting with &authorization.SubjectAccessReview{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"M膳©m|9轷Ǖ媫錚-", GenerateName:"ı亡Ȼ掇Ư6ė", Namespace:"", SelfLink:"Vö逧b祿", UID:"Ȭ嗭ʕû韛ǃJ鲚鮑*箚qçʆ擨Š", ResourceVersion:"17171358100197214", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]api.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:authorization.SubjectAccessReviewSpec{ResourceAttributes:(*authorization.ResourceAttributes)(0xc4202f4230), NonResourceAttributes:(*authorization.NonResourceAttributes)(0xc4203d34a0), User:"ķi[ʫƂȚʪ\u00adn\u9fe5(蜈ƅɯƾ6", Groups:[]string{"¼ŠnşŤ杷"}, Extra:map[string]authorization.ExtraValue{"顩Y2":authorization.ExtraValue(nil)}}, Status:authorization.SubjectAccessReviewStatus{Allowed:false, Reason:"ĕ鎫虄ĊS蠧Ȟ笩眿諑ȍǙʊP", EvaluationError:"齛ſ\\&稒Ð<ji鳞恬Ŷuh釷釺Ǔ]鈈"}}

E1203 15:57:32.326140    5188 serialization_test.go:100] TIM: encoded to "k8s\x00\n3\n\x1cauthorization.k8s.io/v1beta1\x12\x13SubjectAccessReview\x12\xdb\x03\nt\n\x15M膳©m|9轷Ǖ媫錚-\x12\x0fı亡Ȼ掇Ư6ė\x1a\x00\"\nVö逧b祿*#Ȭ嗭ʕû韛ǃJ鲚鮑*箚qçʆ擨Š2\x11171713581001972148\x00B\x00z\x00\x12\x95\x02\n\xb1\x01\n$繱Ǧʉ橋É疓-`ßƚȐɋ臺XǼ鰋Ƭ\x12\x19ĺp楠ŧ鴗ȍ薜ʑd骺mŅ\x1a\n襢诲ƜĄ\" 媘Ä2ùʫȕă 臛Ï嗈V欈Ȋ撮*\x0fʂƁ覾^ãȐTa[2\f輓硛蛣鰒:!vA>囯殠ʦ¤,ǃ挭ƏGaÜ樨Ɲ謪\x12'\n\x00\x12#jĤí蚛綽螞ʐqzóǉ釥禙ơǯ骘\x1a\x1dķi[ʫƂȚʪ\u00adn\u9fe5(蜈ƅɯƾ6\"\f¼ŠnşŤ杷*\t\n\x05顩Y2\x12\x00\x1aK\b\x00\x12 ĕ鎫虄ĊS蠧Ȟ笩眿諑ȍǙʊP\x1a%齛ſ\\&稒Ð<ji鳞恬Ŷuh釷釺Ǔ]鈈\x1a\x00\"\x00"

E1203 15:57:32.326209    5188 serialization_test.go:118] TIM: decoded to &authorization.SubjectAccessReview{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"M膳©m|9轷Ǖ媫錚-", GenerateName:"ı亡Ȼ掇Ư6ė", Namespace:"", SelfLink:"Vö逧b祿", UID:"Ȭ嗭ʕû韛ǃJ鲚鮑*箚qçʆ擨Š", ResourceVersion:"17171358100197214", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]api.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:authorization.SubjectAccessReviewSpec{ResourceAttributes:(*authorization.ResourceAttributes)(0xc4202f4310), NonResourceAttributes:(*authorization.NonResourceAttributes)(0xc4203d38a0), User:"ķi[ʫƂȚʪ\u00adn\u9fe5(蜈ƅɯƾ6", Groups:[]string{"¼ŠnşŤ杷"}, Extra:map[string]authorization.ExtraValue{"顩Y2":authorization.ExtraValue{}}}, Status:authorization.SubjectAccessReviewStatus{Allowed:false, Reason:"ĕ鎫虄ĊS蠧Ȟ笩眿諑ȍǙʊP", EvaluationError:"齛ſ\\&稒Ð<ji鳞恬Ŷuh釷釺Ǔ]鈈"}}

```

Note specifically:
`Extra:map[string]authorization.ExtraValue{"顩Y2":authorization.ExtraValue(nil)}}`
becomes
`Extra:map[string]authorization.ExtraValue{"顩Y2":authorization.ExtraValue{}}`

The code is basically:

```
    glog.Errorf("TIM: starting with %#v", item)

    data, err := runtime.Encode(codec, item)
    glog.Errorf("TIM: encoded to %#v", string(data))

    obj2, err := runtime.Decode(codec, data)
    glog.Errorf("TIM: decoded to %#v", obj2)
```

If you look at pkg/apis/authorization/v1beta1/generated.pb.go line 2021, you'll see `mapvalue := &ExtraValue{}`, which looks to me like proto is not preserving `nil` when unmarshalling this case (a slice as a map value).

It seems like a mess for a reflect-based deep-equal to look at JSON tags to decide this.  We probably should codegen deep-equal funcs, but this is most ly (entirely?) used in tests...

**Comment by smarterclayton** [comment]
The other errors you were seeing is what I was commenting on, sorry.  I'm
just saying that proto is doing exactly what JSON is doing (making an
arbitrary decision what empty optional arrays should be - nil or empty),
but picking the alternate option.  But deep equal has no idea about
optional fields, which means it doesn't know what equal really is.

Extra value is not required to preserve empty array today (we don't promise
it will) but agree this looks like a bug in proto gen where we need to
conditionalize map value creation.

On Dec 8, 2016, at 11:45 PM, Tim Hockin <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> I don't understand your
comment. I serialize to proto then deserialize back to struct and the
result is different. The automatic tests are not capturing my logged debug
output. from local:

E1203 15:57:32.326070    5188 serialization_test.go:170] TIM: before
roundTripSame::roundTrip: codec &{0xc420316b40 0xc420316b40
{0xc420299a40} 0xc420299a40 0xc420299a40 0xc420299a40 0xc420299a40
[{storage.k8s.io v1beta1} {rbac.authorization.k8s.io v1alpha1}
{certificates.k8s.io v1alpha1} {batch v1} { v1} {imagepolicy.k8s.io
v1alpha1} {apps v1beta1} {policy v1beta1} {authorization.k8s.io
v1beta1} {kubeadm.k8s.io v1alpha1} {federation v1beta1} {extensions
v1beta1} {autoscaling v1} {authentication.k8s.io v1beta1}] {}}

E1203 15:57:32.326091    5188 serialization_test.go:97] TIM: starting
with &authorization.SubjectAccessReview{TypeMeta:unversioned.TypeMeta{Kind:"",
APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"M膳©m|9轷Ǖ媫錚-",
GenerateName:"ı亡Ȼ掇Ư6ė", Namespace:"", SelfLink:"Vö逧b祿",
UID:"Ȭ嗭ʕû韛ǃJ鲚鮑*箚qçʆ擨Š", ResourceVersion:"17171358100197214",
Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0,
nsec:0, loc:(*time.Location)(nil)}},
DeletionTimestamp:(*unversioned.Time)(nil),
DeletionGracePeriodSeconds:(*int64)(nil),
Labels:map[string]string(nil), Annotations:map[string]string(nil),
OwnerReferences:[]api.OwnerReference(nil), Finalizers:[]string(nil),
ClusterName:""},
Spec:authorization.SubjectAccessReviewSpec{ResourceAttributes:(*authorization.ResourceAttributes)(0xc4202f4230),
NonResourceAttributes:(*authorization.NonResourceAttributes)(0xc4203d34a0),
User:"ķi[ʫƂȚʪ\u00adn\u9fe5(蜈ƅɯƾ6", Groups:[]string{"¼ŠnşŤ杷"},
Extra:map[string]authorization.ExtraValue{"顩Y2":authorization.ExtraValue(nil)}},
Status:authorization.SubjectAccessReviewStatus{Allowed:false,
Reason:"ĕ鎫虄ĊS蠧Ȟ笩眿諑ȍǙʊP", EvaluationError:"齛ſ\\&稒Ð<ji鳞恬Ŷuh釷釺Ǔ]鈈"}}

E1203 15:57:32.326140    5188 serialization_test.go:100] TIM: encoded
to "k8s\x00\n3\n\x1cauthorization.k8s.io/v1beta1\x12\x13SubjectAccessReview\x12\xdb\x03\nt\n\x15M膳©m|9轷Ǖ媫錚-\x12\x0fı亡Ȼ掇Ư6ė\x1a\x00\"\nVö逧b祿*#Ȭ嗭ʕû韛ǃJ鲚鮑*箚qçʆ擨Š2\x11171713581001972148\x00B\x00z\x00\x12\x95\x02\n\xb1\x01\n$繱Ǧʉ橋É疓-`ßƚȐɋ臺XǼ鰋Ƭ\x12\x19ĺp楠ŧ鴗ȍ薜ʑd骺mŅ\x1a\n襢诲ƜĄ\"
媘Ä2ùʫȕă 臛Ï嗈V欈Ȋ撮*\x0fʂƁ覾^ãȐTa[2\f輓硛蛣鰒:!vA>囯殠ʦ¤,ǃ挭ƏGaÜ樨Ɲ謪\x12'\n\x00\x12#jĤí蚛綽螞ʐqzóǉ釥禙ơǯ骘\x1a\x1dķi[ʫƂȚʪ\u00adn\u9fe5(蜈ƅɯƾ6\"\f¼ŠnşŤ杷*\t\n\x05顩Y2\x12\x00\x1aK\b\x00\x12
ĕ鎫虄ĊS蠧Ȟ笩眿諑ȍǙʊP\x1a%齛ſ\\&稒Ð<ji鳞恬Ŷuh釷釺Ǔ]鈈\x1a\x00\"\x00"

E1203 15:57:32.326209    5188 serialization_test.go:118] TIM: decoded
to &authorization.SubjectAccessReview{TypeMeta:unversioned.TypeMeta{Kind:"",
APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"M膳©m|9轷Ǖ媫錚-",
GenerateName:"ı亡Ȼ掇Ư6ė", Namespace:"", SelfLink:"Vö逧b祿",
UID:"Ȭ嗭ʕû韛ǃJ鲚鮑*箚qçʆ擨Š", ResourceVersion:"17171358100197214",
Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0,
nsec:0, loc:(*time.Location)(nil)}},
DeletionTimestamp:(*unversioned.Time)(nil),
DeletionGracePeriodSeconds:(*int64)(nil),
Labels:map[string]string(nil), Annotations:map[string]string(nil),
OwnerReferences:[]api.OwnerReference(nil), Finalizers:[]string(nil),
ClusterName:""},
Spec:authorization.SubjectAccessReviewSpec{ResourceAttributes:(*authorization.ResourceAttributes)(0xc4202f4310),
NonResourceAttributes:(*authorization.NonResourceAttributes)(0xc4203d38a0),
User:"ķi[ʫƂȚʪ\u00adn\u9fe5(蜈ƅɯƾ6", Groups:[]string{"¼ŠnşŤ杷"},
Extra:map[string]authorization.ExtraValue{"顩Y2":authorization.ExtraValue{}}},
Status:authorization.SubjectAccessReviewStatus{Allowed:false,
Reason:"ĕ鎫虄ĊS蠧Ȟ笩眿諑ȍǙʊP", EvaluationError:"齛ſ\\&稒Ð<ji鳞恬Ŷuh釷釺Ǔ]鈈"}}


Note specifically:
Extra:map[string]authorization.ExtraValue{"顩Y2":authorization.ExtraValue(nil)}}
becomes
Extra:map[string]authorization.ExtraValue{"顩Y2":authorization.ExtraValue{}}

The code is basically:

    glog.Errorf("TIM: starting with %#v", item)

    data, err := runtime.Encode(codec, item)
    glog.Errorf("TIM: encoded to %#v", string(data))

    obj2, err := runtime.Decode(codec, data)
    glog.Errorf("TIM: decoded to %#v", obj2)

If you look at pkg/apis/authorization/v1beta1/generated.pb.go line 2021,
you'll see mapvalue := &ExtraValue{}, which looks to me like proto is not
preserving nil when unmarshalling this case (a slice as a map value).

It seems like a mess for a reflect-based deep-equal to look at JSON tags to
decide this. We probably should codegen deep-equal funcs, but this is most
ly (entirely?) used in tests...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/38052#issuecomment-265932599>,
or mute the thread

**Comment by thockin** [comment]
I'm really waffling on this.  While the JSON encoder is doing what I *want*
I am not sure it is *right*.  When unmarshaling a JSON document into a
native Go type, it's reasonable to say "non-specified means nil, and
specified-but-empty means []".  That's because we have a notion of
not-specified.

For a map-value, do we have that same notion?  I guess we can make an
argument that if it marshals as `null` it should unmarshal to nil slice,
but it seems a little onerous to make that distinction for languages that
maybe don't support the same nil-ness of slices (e.g. what is the C++
representation of this - it is closer to a std::vector (if I recall), which
has no nil-ness).

That aside, my guess is that changing the proto encoding here is unlikely,
so I am further leaning towards cutting our losses on this and saying that
any kube API that cares about slices being not-provided as distinct from
being provided empty should wrap their slice in a struct, and carry a
pointer-to-struct.

To add insult to injury, if we DID support this distinction, I can see maps
wanting the same distinction, but a nil map is far less friendly to use
than a nil slice (~ useless IMO).

FINALLY, I suppose it is too late to undo, but if we do not support this
distinction, your work to make proto wrap slices in structs is redundant :)

**Comment by smarterclayton** [comment]
I guess I don't agree at the conclusion, nor why the proto encoding of
map[string][]slice wouldn't be fixed.  It's fixable just like the other
variants are fixable - the bug is in the decoding side to always create the
type, not the fundamental proto serialization (which is an array of key
value, where value can be a nullable struct).

OpenShift relies on the slice code in several places (we don't have
map[string][]slice), and there are many potential APIs where empty and nil
are distinct.

**Comment by thockin** [comment]
Protobuf for C++ has no way of encoding this distinction at all.  As
currently written, our proto will generate a map whose value is 'struct
ExtraValue', not pointer-to as far as I can tell from docs).

So we really do need both your wrapper struct in proto and our own in the
kube API.  If we expect the nil-ness vs emptyness to matter, we have to own
the problem.

I don't think there is a path forward that covers all cases.  Go is too
flexible here.

**Comment by smarterclayton** [comment]
> Protobuf for C++ has no way of encoding this distinction at all. As currently written, our proto will generate a map whose value is 'struct ExtraValue', not pointer-to as far as I can tell from docs).

The wire format for proto2 maps is array of messages:

```
message Item {
  key = 1
  value = 2
}
```

Values that are messages are nested.  Nested messages in a message are either set or not set (based on the presence of the field).  Not sure what docs your referring to, but if nested messages aren't representable in C++ that would surprise me.

The code in unmarshal / marshal is wrong because I didn't add the variant rewrites to make it tolerate nil.  It's just a bug.

**Comment by thockin** [comment]
Yes, the wire format of map is a series of key/val messages, and yes the
val is strictly optional.

That does not mean that languages that proto supports understand the
optional-ness of a value.  C++, for instance, will codegen a map accessor
that always returns a value.

https://developers.google.com/protocol-buffers/docs/reference/cpp-generated#map-fields

Specifically:

```
T& operator[](const Key& key);
```

The C++ native type is a Map, and accessing field[k] returns a reference (a
value, not nil-capable).  So the proto that we emit today:

```
message ExtraValue {

  // items, if empty, will result in an empty slice

  repeated string items = 1;
}

message UserInfo {
  //...
  map<string, ExtraValue> extra = 4;
}
```

... should result in a C++ Map whose value (T above) is `struct
ExtraValue`.  You're relying on the ability to detect "absent" values which
works as a field but doesn't work as a map value.

Maybe we can fix the Go marshal/unmarshal to understand it, but we can't
fix every language.  We'd do better to carry our own "has" flag in proto.
Even if we adopted a convention of wrapping in a struct for max
compatibility, using this struct as a map value requires another level of
indirection.

This will work:

```
type FromPorts struct {
  Ports []int
}

type MyPolicy {
  Allow *FromPorts
}
```

This will not:

```
type FromPorts struct {
  Ports []int
}

type MyPolicy {
  Allow map[string]*FromPorts
}
```

I think.  I can't see to get the protobuf code to regen right now, and I
have to leave. :)


On Dec 11, 2016 12:49 PM, "Clayton Coleman" <notifications@github.com>
wrote:

Protobuf for C++ has no way of encoding this distinction at all. As
currently written, our proto will generate a map whose value is 'struct
ExtraValue', not pointer-to as far as I can tell from docs).

The wire format for proto2 maps is array of messages:

message Item {
  key = 1
  value = 2
}

Values that are messages are nested. Nested messages in a message are
either set or not set (based on the presence of the field). Not sure what
docs your referring to, but if nested messages aren't representable in C++
that would surprise me.

The code in unmarshal / marshal is wrong because I didn't add the variant
rewrites to make it tolerate nil. It's just a bug.

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/38052#issuecomment-266306850>,
or mute the thread

**Comment by thockin** [comment]
Abandoning this.  I do not think we should make the distinction between `nil` and empty slices or maps *anywhere* in our API.  If you need such a distinction, you can wrap your slice in a struct.  If you need such a distinction in a map value, you need to double-wrap it.

Full stop.

**Pull request closed without merging**
