### PR TITLE
Make AddSSHKeys a controller loop. Make sure master's always initializes m.tunnels.

### PR DESCRIPTION
**Pull request by cjcullen**

### CODE REVIEW

**Comment by cjcullen** [comment]
@brendandburns @lavalamp @roberthbailey

**Comment by brendandburns** [comment]
LGTM.

**Comment by cjcullen** [comment]
Changed it to only generate the public key file name in one place.

**Comment by brendandburns** [comment]
Shippable is a flake, I'm merging so that we can test this overnight.

**Pull request merged**
