### PR TITLE
fix typo kubeadm joiń ->  kubeadm join

### PR DESCRIPTION
**Pull request by peibinGH**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks
/lgtm
/approve
/kind cleanup
/priority backlog

**Comment by neolit123** [comment]
this govet failure is odd as it started happening suddenly...

**Comment by xichengliudui** [comment]
I found the journal for you.
```
# k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm
cmd/kubeadm/app/apis/kubeadm/types.go:41:2: struct field Kind repeats json tag "kind" also at types.go:48
cmd/kubeadm/app/apis/kubeadm/types.go:41:2: struct field APIVersion repeats json tag "apiVersion" also at types.go:55
# k8s.io/kubernetes/pkg/controller/testutil
pkg/controller/testutil/test_utils.go:377:2: missing ... in args forwarded to printf-like function
# k8s.io/kubernetes/pkg/kubelet/container
pkg/kubelet/container/sync_result_test.go:48:3: Errorf format %q has arg result of wrong type k8s.io/kubernetes/pkg/kubelet/container.PodSyncResult
pkg/kubelet/container/sync_result_test.go:56:3: Errorf format %q has arg result of wrong type k8s.io/kubernetes/pkg/kubelet/container.PodSyncResult
pkg/kubelet/container/sync_result_test.go:66:3: Errorf format %q has arg result of wrong type k8s.io/kubernetes/pkg/kubelet/container.PodSyncResult
# k8s.io/kubernetes/pkg/kubelet/kuberuntime
pkg/kubelet/kuberuntime/kuberuntime_manager_test.go:387:3: Errorf format %q has arg expected of wrong type []*k8s.io/kubernetes/pkg/kubelet/container.Pod
# k8s.io/kubernetes/pkg/registry/core/service/allocator
pkg/registry/core/service/allocator/utils_test.go:49:4: Errorf format %d has arg test.n of wrong type *math/big.Int
make[1]: *** [vet] Error 1
```

**Comment by neolit123** [comment]
try `/retest` again later today. we are reverting go 1.12 to 1.11...

**Comment by peibingit** [comment]
> `/retest`今天晚些时候再试一次 我们正在回复1.12到1.11 ......

ok

**Comment by xichengliudui** [comment]
@neolit123  I think is ` % q ` placeholder problems, needs to be modified for ` % v ` need me to solve? I'd be happy to.

**Comment by neolit123** [comment]
@xichengliudui please don't send PRs for that yet.

**Comment by xichengliudui** [comment]
In this pr ` https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/74771/pull-kubernetes-verify/124387 ` encountered the same problem

**Pull request merged**
