### PR TITLE
WIP - Split PSP into validation and defaulting passes

### LINKED ISSUE #36184: Split PSP defaulting and validation
When authz is added to PSP admission (https://github.com/kubernetes/kubernetes/pull/33080) the user submitting the request will now be taken into account for PSP selection.  That means that if one user creates a pod and another user updates the pod the PSP options that the pod validates against may be different.  

Since the PodSpec should not be mutable on the fields that PSP defaults anyway the PSP logic should be split so that defaulting only occurs during an ADD operations.  An UPDATE operation should only attempt to validate that the user has a PSP that would allow the requested spec.

ref: https://github.com/kubernetes/kubernetes/pull/33080/files#r84148684

### PR DESCRIPTION
**Pull request by liggitt**
will fix #36184

this splits the PSP admission into these steps:

1. select policies accessible to the user
2. validate the pod as-is against those policies (no mutating the pod)

    a. if any allow the pod as-is, return
    b. if any allow the pod with defaulting, let them default the pod, revalidate, and return if allowed
    c. otherwise, return the aggregated errors

TODO:
- [ ] when processing Update requests, omit step 2b (since pods cannot be mutated post-creation)
- [ ] convert remaining PSP strategies to split validation and defaulting

Follow-up:
- [ ] allow prioritizing some policies over others (e.g. https://github.com/kubernetes/kubernetes/pull/45358)

### CODE REVIEW

**Comment by smarterclayton** [comment]
This will be pretty important for 1.9 if we turn on PSP by default (with a permissive policy)

**Comment by adelton** [comment]
I wonder if the defaulting should be part of the PSP, or whether it should be completely separate set of options, global or per-namespace.

I struggle with the option

- a. if any allow the pod as-is, return

The pod will be allowed, what defaults will it get? Shouldn't defaults be adjusted/resolved first, without PSPs, and only then the validation phase run?

**Comment by adelton** [comment]
@liggitt, seeing this pull request closed but not merged, what is the situation / plan? Is there a replacement PR or do we drop this change altogether?

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/52849 is the short-term replacement

I expect further work as part of splitting admission itself into mutating and validating passes (e.g. https://github.com/kubernetes/community/pull/1137/files#diff-d5c72705a15d00eec223a9920125e179R65)

**Pull request closed without merging**
