### PR TITLE
Add some clean logs for CUD fedaration resource

### PR DESCRIPTION
**Pull request by FengyunPan**
Add some clean logs for CUD fedaration resource

### CODE REVIEW

**Comment by henriquetruta** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43841)*

**Comment by madhusudancs** [comment]
Could you please split this into two separate PRs?

1. For logging.
2. For ignoring `IsNotFound` errors.

It is too hard to say what's going on here because of a ton of logging statements added. Also, if we want to revert the changes to be atomic.

**Comment by FengyunPan** [comment]
@ madhusudancs Thank for your review, do you meaning that there is no need to add log, just need ignore IsNotFound errors?

**Comment by grodrigues3** [comment]
@k8s-bot ok to test

**Comment by madhusudancs** [comment]
@FengyunPan no no, I meant, add the logs, but in a separate PR. Those logs are really useful. I am just making things easier for review.

**Comment by FengyunPan** [comment]
@madhusudancs Oh, I see. I have splited this into two separate PRs, the other one is #44483 .

**Pull request closed without merging**
