### PR TITLE
Removal of GlusterFS code from the repo

### PR DESCRIPTION
**Pull request by humblec**
This PR removes GlusterFS in-tree driver code from the repository. This driver was marked for deprecation in 1.25.

Reference 

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

/kind cleanup

Additional Ref#
Issue #100897 

```release-note
GlusterFS in-tree storage driver which was deprecated at kubernetes 1.25 release has been removed entirely in 1.26.
```

### CODE REVIEW

**Comment by dims** [comment]
@humblec looks like the CI is not yet green

**Comment by dims** [comment]
@humblec last step left to fix the dependencies ci job. you can confirm that this worked by running `hack/lint-dependencies.sh`

```
Check all unwanted dependencies and update its status.

Use the given commands to remove pinned module versions that aren't actually used:
GO111MODULE=on go mod edit -dropreplace github.com/auth0/go-jwt-middleware
GO111MODULE=on go mod edit -dropreplace github.com/boltdb/bolt
GO111MODULE=on go mod edit -dropreplace github.com/go-ozzo/ozzo-validation
GO111MODULE=on go mod edit -dropreplace github.com/gopherjs/gopherjs
GO111MODULE=on go mod edit -dropreplace github.com/gorilla/mux
GO111MODULE=on go mod edit -dropreplace github.com/heketi/heketi
GO111MODULE=on go mod edit -dropreplace github.com/heketi/tests
GO111MODULE=on go mod edit -dropreplace github.com/jtolds/gls
GO111MODULE=on go mod edit -dropreplace github.com/lpabon/godbc
GO111MODULE=on go mod edit -dropreplace github.com/smartystreets/assertions
GO111MODULE=on go mod edit -dropreplace github.com/smartystreets/goconvey
GO111MODULE=on go mod edit -dropreplace github.com/urfave/negroni
All pinned versions of checked dependencies match their preferred version.

```

**Comment by dims** [comment]
@humblec here's the extra commit you will need to add at the end of your series - https://github.com/kubernetes/kubernetes/commit/a4a264b5e9c35649588e821dc131aee0323427c8

**Comment by dims** [comment]
Hmm, looks like i was able to patch it up too!!

/assign @liggitt 
(for root OWNERS approval)

**Comment by dims** [comment]
hmm, getting conflicting stuff from ci jobs. I think we'll need to rebase to latest and then run `hack/update-vendor.sh` and then check with `hack/lint-dependencies.sh` @humblec

**Comment by humblec** [comment]
> hmm, getting conflicting stuff from ci jobs. I think we'll need to rebase to latest and then run `hack/update-vendor.sh` and then check with `hack/lint-dependencies.sh` @humblec

@dims rebase, update-vendor, lint-dependencies, update-vendor has been done few times, but the CI on vendor changes `still` fails. may be some hack is required to get this in.

**Comment by dims** [comment]
for sure @humblec, i've started a slack thread on code organization channel. 

also, please go ahead and remove the 4 commits from me from this PR

**Comment by liggitt** [comment]
> > hmm, getting conflicting stuff from ci jobs. I think we'll need to rebase to latest and then run `hack/update-vendor.sh` and then check with `hack/lint-dependencies.sh` @humblec
> 
> @dims rebase, update-vendor, lint-dependencies, update-vendor has been done few times, but the CI on vendor changes `still` fails. may be some hack is required to get this in.

fix open in https://github.com/kubernetes/kubernetes/pull/112422

**Comment by liggitt** [comment]
> fix open in #112422

if you rebase this PR on top of that PR, `update-vendor` should work as expected for you now

you can also collapse this PR down to two commits:
1. removal of gluster code
2. result of running `update-vendor`

**Comment by dims** [comment]
I can confirm that the fix in #112422 works fine! thanks @liggitt

**Comment by humblec** [comment]
> for sure @humblec, i've started a slack thread on code organization channel.
> 
> also, please go ahead and remove the 4 commits from me from this PR

Sure  Thanks @dims

**Comment by humblec** [comment]
> > fix open in #112422
> 
> if you rebase this PR on top of that PR, `update-vendor` should work as expected for you now

Yep, Thanks !

> 
> you can also collapse this PR down to two commits:
> 
>     1. removal of gluster code
> 
>     2. result of running `update-vendor`

Will refresh this PR as suggested. The extra 2 commits were held to show the cyclic issue mainly though which is not needed anymore.

**Comment by humblec** [comment]
Thanks @dims @liggitt , i have rebased on master and the problematic CI passes :+1:

**Comment by liggitt** [comment]
```diff
 {
-	"directDependencies": 226,
-	"transitiveDependencies": 263,
-	"totalDependencies": 322,
+	"directDependencies": 218,
+	"transitiveDependencies": 257,
+	"totalDependencies": 310,
 	"maxDepthOfDependencies": 30
 }
```

**Comment by xing-yang** [comment]
We have discussed this in SIG-Storage meeting on 7/28/2022 and agreed to the following:
```
Deprecate GlusterFS in 1.25 and remove code in 1.26
```
This is in our meeting notes:
https://docs.google.com/document/d/1-8KEG8AjAgKznS9NFm3qWqkGyCHmvU6HVl0sk5hwoAE/edit#heading=h.3z3l564d4dz1

We also have an entry to track this task in 1.26 in our spreadsheet:
https://docs.google.com/spreadsheets/d/1t4z5DYKjX2ZDlkTpCnp18icRAQqOE85C1T1r2gqJVck/edit#gid=834261699

**Review by saad-ali — APPROVED** [review]
/lgtm
/approve

Ok to remove per the discussions @xing-yang referenced.

/hold
Adding a hold in case anyone else wants a chance to review (@msau42 ?)

**Comment by liggitt** [comment]
/approve
for deps changes

removal of hold is up to sig-storage leads

**Comment by dims** [comment]
ack @liggitt we can wait for a day or so and then remove hold

**Comment by xing-yang** [comment]
@humblec Can you check why it says release notes not added?

**Comment by dims** [comment]
@xing-yang it says the label was removed, needs a refresh of the page?. Here's what i see on the labels section on top.

image

**Comment by humblec** [comment]
> @humblec Can you check why it says release notes not added?

Looks like an interim state for some reason but we are good atm @xing-yang

**Comment by humblec** [comment]
Those sleepless nights to get this in for v1.4..  :crying_cat_face:

**Pull request merged**
