### PR TITLE
CSR modification for SANs and Key Usage

### PR DESCRIPTION
**Pull request by arnaudmz**
CSR generated during TLS bootstraping was missing both TLS Web Server Key Usage and a valid SANs as shown in https://github.com/kelseyhightower/kubernetes-the-hard-way/issues/146

This P/R added both missing fields in CSR

### CODE REVIEW

**Comment by arnaudmz** [comment]
I signed it.

Arnaud MAZIN


2017-04-05 15:55 GMT+02:00 k8s-ci-robot <notifications@github.com>:

**Comment by grodrigues3** [comment]
@k8s-bot ok to test

**Comment by grodrigues3** [comment]
@k8s-bot ok to test

**Comment by augabet** [comment]
Issue referenced here: https://github.com/kubernetes/kubernetes/issues/44153
Is it possible to merge it in 1.6.X release ?

**Comment by liggitt** [comment]
this is incorrect... the certificate being requested is *only* supposed to be a client cert. bootstrapping the serving cert will happen separately, and is planned for 1.7.

cc @jcbsmpsn

**Comment by liggitt** [comment]
tracked in https://github.com/kubernetes/features/issues/43#issuecomment-241910465

**Pull request closed without merging**
