### PR TITLE
Create new Open API V3 sub-directory with OWNERS file

### PR DESCRIPTION
**Pull request by seans3**
* Creates new sub-directory for Open API V3 client code.
* Adds first OWNERS file for this new  directory.

/sig api-machinery
/kind cleanup
/priority important-soon

```release-note
NONE
```

### CODE REVIEW

**Comment by apelisse** [comment]
Should this be in: `staging/src/k8s.io/client-go/openapi/OWNERS`, I don't think we should nest `openapi3` in `openapi`

**Comment by apelisse** [comment]
Thanks!
/lgtm
/approve

**Comment by lavalamp** [comment]
What is going to go here? I'd rather add the content first and then the OWNERS file?

**Pull request closed without merging**
