### PR TITLE
Cleanup: kube-proxy internal naming

### LINKED ISSUE #108806: Cleanup: kube-proxy internal naming
We have sort of a mish-mash of "service" and "servicePort" and similar.

We should think about changing ALL of the places that actually relate to a service-port (a specific port of a service, not the whole service) and rename them to some new term that means "service port". E.g. "svcpt" or "spt" or "sport".

See https://github.com/kubernetes/kubernetes/pull/106497/commits/8fffae321d66487f776922e0c313b33af7bf27e3 in pkg/proxy/iptables/proxier.go and friends.  e.g. `info.serviceNameString` -> `info.svcptNameString` ?

### PR DESCRIPTION
**Pull request by manav014**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR changes the variable names like ServiceMap or BaseServiceInfo to new meaningful and relatable names like ServicePortMap and BaseServicePortInfo

#### Which issue(s) this PR fixes:
Fixes #108806

#### Special notes for your reviewer:
No

#### Does this PR introduce a user-facing change?
No

/cc @thockin 

```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
needs rebase

**Comment by manav014** [comment]
@thockin Thanks for the response. I have rebased the PR.

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
