### PR TITLE
Automated cherry pick of #106641: DelegateFSGroupToCSIDriver e2e: skip tests with chgrp

### PR DESCRIPTION
**Pull request by verult**
Cherry pick of #106641 on release-1.23.

#106641: DelegateFSGroupToCSIDriver e2e: skip tests with chgrp

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
None
```

### CODE REVIEW

**Comment by verult** [comment]
/kind bug
/kind failing-test

/sig storage
/assign @msau42 @Verolop 
/priority important-soon
/triage accepted

cc @gnufied @andyzhangx

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by puerco** [comment]
Thanks @verult !
/lgtm

**Pull request merged**
