### PR TITLE
map counter: needed for things like summations of events to reduce noise

### PR DESCRIPTION
**Pull request by jayunit100**
part of #35842 : a counter mechanism that we can maintain internally for reducing spam by aggregating identical events before spamming them

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35873)

### CODE REVIEW

**Comment by smarterclayton** [comment]
Is there a Prometheus gauge utility class we can reuse for this efficiently?  Ie that has lock striping already?  Does this have to be a synchronized map (is the fit cope path concurrent)?

**Comment by jayunit100** [comment]
hmmm, @smarterclayton absolutely we can reuse prometheus gauges.  I assumed we probably shouldnt rely on it as a collections library, in general .? (WLOG) what do you think ?  im open to either way.

**Comment by smarterclayton** [comment]
I'm not strongly for or against, but if we're doing anything that is going
to be more complex than "a map of numbers" (that is shared across multiple
goroutines) the prometheus library may have the advantage of already
solving a lot of the performance sensitive aspects.  OTOH if this is a
single threaded counter utility for specific use, it could likely be even
simpler.  Just trying to understand where you're going to use this.

**Comment by jayunit100** [comment]
in the scheduler.  But I could see other places where a threadsafe count incrementer would be useful.  I guess maybe there are lock free ways to increment an integer , in our case we're not expecting millions of concurrent incrememntations, so the simple Lock won't have much cost .... i.e. the proportion of threads accessing a single map would be O(n) (number of nodes)...

**Comment by jayunit100** [comment]
I'm open to wrapping gauge as the underlying impl also, so that we can maintain our own collection utilities w/o having to cherry pick from other random dependencies

**Comment by smarterclayton** [comment]
This is fine as is, now that you've explained at least a bit how you intend
to use it.  Although it's not very interesting on its own and would
probably be better rolled into your actual PR for the changes that consume
it.

**Comment by jayunit100** [comment]
Ok.  Should i close or should we push it along?

**Comment by jayunit100** [comment]
@smarterclayton after thinking some more, if you no strong disagreement ---  id like to push it forward - it will make reviewing our follow on patches easier :) . does this look ok to you ?

**Comment by smarterclayton** [comment]
I don't see this as coupled to anything, and if it only has one use, I'd
like to see it used before I comment on it's merit in util.  I don't like
creating things in util that have no references or uses.

**Comment by jayunit100** [comment]
ack, ill do the other PR in parallel .... and leave open?

**Comment by jayunit100** [comment]
@smarterclayton PTAL now that the companion feature patch is in.

**Comment by jayunit100** [comment]
thinking best to close for now

**Pull request closed without merging**
