### PR TITLE
Make godep save/restore more hermetic

### PR DESCRIPTION
**Pull request by thockin**
This will save godeps in _output.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Sorry for being dense. How does this make godeps save to `_output`? There is no mention of `_output` in the PR.

**Comment by thockin** [comment]
kube::golang::setup_env puts you in a known-valid gopath, which is under
_output.

**Comment by cblecker** [comment]
/assign
Going to review this one in the context of how it will interact with https://github.com/kubernetes/kubernetes/pull/50717

**Comment by caesarxuchao** [comment]
If I open a terminal, then run hack/godep-restore.sh, nothing in my original GOPATH will change. Is this good? I think it works for you and me, not sure if someone actually wants to update the packages in their GOPATH.

Also, I think you'll need to update the places where `kube::util::godep_restored` is called.

**Comment by thockin** [comment]
I think save/restore in scripts should NOT affect my own GOPATH.  Maybe
this should be handled in the calling scripts?

**Comment by cblecker** [comment]
Using godep for dependency management relies on four things in your environment:
- The dependencies themselves being checked out into GOPATH
- The version of godep used
- The version of golang used
- The version of git used

We could try to enforce these on the local environment, but we can run into issues where a contributor works on multiple things and the stricter requirements of k8s don't work for them. Because most of these are tied to the (over)complicated godep system we use with k8s, it was suggested https://github.com/kubernetes/kubernetes/issues/45757 and https://github.com/kubernetes/kubernetes/issues/44873 to try and containerize the godep process so that all of those dependencies are just taken care of. This is especially important for release branches that may use a golang version that is older than master does.

While this PR does allow us to mess with godeps outside of our default system GOPATH, it doesn't solve for the other godep issues as it still relies on the local environment. It's also functionally incompatible with https://github.com/kubernetes/kubernetes/pull/50938.

@thockin: are you opposed to working with godeps in containers? It doesn't feel ideal to me, but it does solve for these issues.

**Comment by thockin** [comment]
I am not opposed to anything.  This was born of frustration and screaming at various update-* scripts which fail for inscrutable reasons.

**Comment by thockin** [comment]
This is complicated by the tangle of scripts that call other scripts.

**Comment by thockin** [comment]
Or worse, scripts that SOURCE other scripts.

**Comment by thockin** [comment]
This might not be too bad.  Famous last word when our build is involved...  Looking at it now.

**Comment by thockin** [comment]
@cblecker   https://github.com/kubernetes/kubernetes/compare/master...thockin:godep-in-container?expand=1

PTAL.  To make this USEFUL, we need a new script to add/remove/update deps

**Comment by thockin** [comment]
Curiously, while this now does a save/restore - it doesn't sync the changes OUT of the container.  Maybe I misunderstand it...

**Comment by cblecker** [comment]
@thockin reviewing.. and I think I have an idea on whats up with rsync

**Comment by cblecker** [comment]
Okay, so I think the first step in the right direction with the fake git tree mess is the new commits I've pushed to https://github.com/kubernetes/kubernetes/pull/50717.

If we wanted this to sync out, then we'd need to look at the copy output filter:
https://github.com/kubernetes/kubernetes/blob/1f580ae8984b1114930602d4438d27224bab31ca/build/common.sh#L716-L728

And if we wanted _output to copy back into the container, we'd have to modify the input filter. However, if we're only messing with the deps inside the container in the first place (a la the add/remove/update scripts, or via `build/shell.sh`) then we're probably good and don't need to worry about syncing them back. We'd just need to sync godeps and vendor themselves.

**Comment by thockin** [comment]
Right.  I think Godeps/ and vendor/ are sufficient.  I remove them from the
filter, but they don't seem to be copying back out :(

On Thu, Aug 24, 2017 at 6:48 PM, Christoph Blecker <notifications@github.com

**Comment by cblecker** [comment]
Oh.. yeah, it's not exactly intuitive. The local -> container rsync is an exclude, implicit include, while the container -> local rsync is an include, implicit exclude. So the lines you removed actually are the lines that let you sync those folders out. Revert that change to common.sh and try again.

**Comment by thockin** [comment]
Weird, it seems to have synced out some of the deps but not all.  rsync
being shut down before finishing?

Also rsync seems to not sync empty directories.

**Comment by cblecker** [comment]
The partial bit is quite odd. The empty directory bit is due to a flag in there. Do we need empty dirs synced?

**Comment by thockin** [comment]
Empty dir was just because of testing by removing all of vendor/*, and it blew up because vendor/ did not exist.  Not a big deal but I don't see why to NOT sync those.

I ran restore, removed everything in vendor/, touched vendor/file, and ran save, and it populated vendor/ only partly.  That is twice.  And with this PR, which contradicts your earlier assertion about exclusions/inclusions.

**Comment by thockin** [comment]
WRT the alternate (in container proposal) - I rm all of vendor, then godep save, I expect it to be fully restored.  If I `ls vendor` in the rsync copy-out function, before `kube::build::start_rsyncd_container` I see it is empty.  If I `ls vendor` after `kube::build::rsync`, I see vendor has some but not all of it restored.  If I `sleep 60` and list again, no change.

I am lost...

**Comment by thockin** [comment]
Ahh, I understand your point about inclusion/exclusion now.  New run going now.

**Comment by thockin** [comment]
PTAL - https://github.com/kubernetes/kubernetes/compare/master...thockin:godep-in-container?expand=1

seems to work

**Comment by cblecker** [comment]
@thockin Yup, in general I like that approach. there's some nits/style notes if you opened a PR, but I think that's the way to go.

Would you mind also taking a look at https://github.com/kubernetes/kubernetes/pull/50717 ? That fixes some of the rsync stuff in a much cleaner way (and also solves the empty dir thing you mention above).

**Comment by thockin** [comment]
@cblecker  @caesarxuchao  #51360 opened as an alternative to this

**Comment by cblecker** [comment]
Closing in favour of #51766
/close

**Pull request closed without merging**
