### PR TITLE
Delete code-generator/openapi-gen pkgs

### PR DESCRIPTION
**Pull request by yue9944882**
/kind cleanup
/sig api-machinery
/priority important-longterm

**What this PR does / why we need it**:

now we use kube-openapi/openapi-gen to generate codes instead.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by roycaihw** [comment]
It's a dup of https://github.com/kubernetes/kubernetes/pull/66409. 

Sorry that PR has been sitting for a long while :( Hopefully it will get merged today

**Comment by yue9944882** [comment]
@roycaihw after you 😉

/close

**Pull request closed without merging**
