### PR TITLE
federation make(struct, len()) followed by append()

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
in federation that use append() to fill the slice
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #49475 #49491 

**Special notes for your reviewer**:

**Release note**:

```release-note
  NONE

### CODE REVIEW

**Comment by jianglingxia** [comment]
ping @quinton-hoole @madhusudancs

**Comment by madhusudancs** [comment]
@jianglingxia unlike PRs #49475 and #49491, this isn't necessary. What difference would it make? In those other PRs, the previous code was setting the slice length to a non-zero number and that was a bug. The length is being set to 0 in these cases here in this PR and it makes no difference if we set the capacity.

**Comment by jianglingxia** [comment]
After committing the pr I think we can add a parameter, the length of the array in it  this is OK? @madhusudancs

**Comment by dixudx** [comment]
Agree with @madhusudancs. No need to specify a capacity here.

**Comment by madhusudancs** [comment]
@jianglingxia adding it is Ok, but is not necessary. Why add unnecessary code?

**Comment by jianglingxia** [comment]
ok, thanks for your advice,I will close it!

**Pull request closed without merging**
