### PR TITLE
Revert: Wait for container cleanup before deletion #50350

### PR DESCRIPTION
**Pull request by dashpole**
Issue: #51899

This PR changes the kubelet so that it no longer waits for container deletion to remove the pod.
#50350 had originally added this to prevent deletion of a pod until its containers had been removed from disk.  However, because containers are garbage collected only every 30 seconds, this resulted in a large batch of pod deletions all at once.  See https://github.com/kubernetes/kubernetes/issues/51899#issuecomment-332868313 for details.

cc @kubernetes/sig-node-bugs @kubernetes/sig-scalability-bugs @kubernetes/kubernetes-release-managers

### CODE REVIEW

**Comment by liggitt** [comment]
as soon as this has LGTM from @dchen1107, can you go ahead and open the cherrypick to release-1.8 as well to get it running through CI?

**Comment by shyamjvs** [comment]
I'm testing this fix on 2k-node cluster.

**Comment by smarterclayton** [comment]
Hold on, is this dangerous?  I thought we added this because otherwise we had problems with volume attach issues.

**Comment by smarterclayton** [comment]
Real quick, can we get an assessment of this from a safety, node health, and correctness perspective?  I.e., is the fix the RIGHT fix and as such a regression is acceptable because it is more important to be correct than to be fast?

**Comment by dashpole** [comment]
This did not solve any issues related to volumes AFAIK.

**Comment by liggitt** [comment]
@smarterclayton the next line prevents deleting while volumes still exist, right?

https://github.com/kubernetes/kubernetes/pull/53210/files#diff-10055ae93a8699af13ceba0482fc43c3L857

**Comment by dashpole** [comment]
Safety:
This will make the eviction manager slightly more aggressive, as it will no longer wait for the previous pod's containers to be deleted before deleting the next pod.

Node Health:
This shouldnt have much of a change.

Correctness:
This means that the kubelet will remove a pod from etcd even if the containers still exist on disk.  This isnt technically correct, but will not result in any regressions.

**Comment by smarterclayton** [comment]
Is a small delete regression in extremely large scale worth "not technically correct"?

I'd generally argue that we are correct AT ALL COSTS, except where we prove that correctness is ok.  Assume we were in this case where we were correct but the performance was bad.  Would we fix this by being less correct, or by adding smearing to deletion (as an example)?

**Comment by smarterclayton** [comment]
@dchen1107 can you weigh in here?  When we have thundering herd, we generally solve that differently.  I don't know why we would solve thundering herd by being less correct?

**Comment by dchen1107** [comment]
@smarterclayton I am not sure what volume attach issue you are referring here. 

Kubelet does wait for the volume deletion done to delete the pod. This change just change when Kubelet delete dead containers. With the revert portion, Kubelet won't rely on 30 second gc to delete those dead containers, which looks like the root cause based on @liggitt's analysis in the issue. 

I personally don't think the original issue is the release blocker, but also ok with reverting the entire pr since it is an existing issue in disk eviction manager for a couple of releases. But I think this revert shouldn't cause volume related issues.

**Comment by smarterclayton** [comment]
I think in general the measurement we're measuring is somewhat arbitrary - i'd prefer to ship with this, document 5000 node cluster, and make kubelet not thundering herd the masters on MASSIVE deletion.

Is the code in master correct as an administrator would care about the cluster?  Is the measurement here we're guiding a revert on a valid measurement for what an administrator cares about?

If we shipped 1.8.0 with this, and noted that massive deletion causes thundering herd, and that the nodes shouldn't thundering herd, and fix that in 1.8.x, would that be a better experience for our users?

**Comment by dchen1107** [comment]
Re: https://github.com/kubernetes/kubernetes/pull/53210#issuecomment-332905991

@smarterclayton I believe you preferred shipping 1.8 without this revert pr, right? That is what I preferred in the first place. I don't think that should cause a real regression in production. In my mind, waiting for volume deletion should have bigger impact at the first place, which was introduced a couple of releases before. But our performance measurement never catch that issue, and there is no single production issue being reported related to that.

**Comment by shyamjvs** [comment]
> I think in general the measurement we're measuring is somewhat arbitrary - i'd prefer to ship with this, document 5000 node cluster, and make kubelet not thundering herd the masters on MASSIVE deletion.

@smarterclayton I'm not sure I agree with this. The delete pods latency shot up from 20ms to greater than 3s (which is orders of magnitude higher and violating the SLOs we promise). And this was seen at a scale of 2k-nodes, not even 5k. The deletion of pods we're doing in the density test is not abnormal imo - we're deleting about 3000 pods within a couple of minutes which is sth I believe could happen if a user brought down a big deployment.

Though I don't have too strong opinion here.

**Comment by smarterclayton** [comment]
Stepping back a bit on the underlying user scenario, the POINT of the SLO is probably:

1. I can turn over all the pods in my clusters safely at a very large cluster size quickly

Do we agree?  If so, from the data that we're seeing are we violating that user scenario?

**Comment by dchen1107** [comment]
@shyamjvs on
> The delete pods latency shot up from 20ms to greater than 3s (which is orders of magnitude higher and violating the SLOs we promise).

Do we think this is a reasonable SLO upon deleting about 3000 pods in a large cluster at the first place?

**Comment by shyamjvs** [comment]
Discussing further in the burndown meeting happening right now.

**Comment by shyamjvs** [comment]
Just fyi - The scale test is passing with this change. It still hasn't gone back to the latencies like back before that commit, but it's well below our 1s threshold:

```
Sep 28 20:23:57.699: INFO: Top latency metric: {Resource:pods Subresource: Verb:DELETE Scope:namespace Latency:{Perc50:4.486ms Perc90:7.763ms Perc99:344.744ms Perc100:0s} Count:124000}
```

**Comment by shyamjvs** [comment]
So what's the plan here? Do we want to get this in for 1.9 and then fix the thundering herd issue before re-reverting or just wait till the issue is fixed?
I'd suggest the former in order to have green signal wrt scalability for 1.9 in order to be able to catch new regressions (note that these tests are release-blocking for 1.9 too).

**Comment by derekwaynecarr** [comment]
i am confused, can we not protect this behind the feature gate flag for local disk scheduling?  that seems where like the need to enforce this is cleaned up makes more immediate sense to me.

**Comment by liggitt** [comment]
> can we not protect this behind the feature gate flag for local disk scheduling? that seems where like the need to enforce this is cleaned up makes more immediate sense to me.

that makes sense to me as well, lets us get back SLO and test signal immediately, have a minimal pick to 1.8.1, and makes resolving the thundering herd a requirement for enabling that feature gate by default (either by smearing deletes or rethinking periodic gc).

**Comment by dashpole** [comment]
I added the local storage feature gate, as that seems preferable to removing that portion of code entirely.  I don't have an opinion on whether or not this should go in.

**Comment by dchen1107** [comment]
re: https://github.com/kubernetes/kubernetes/pull/53210#issuecomment-332969753

I did propose to have this feature gate in earlier burndown meeting. The decision is releasing 1.8.0 as is and document the known issue. And we are working on the solution addressing the issue in 1.8.1.

**Comment by liggitt** [comment]
I didn’t realize there was an existing feature gate this cleanup was related to. If this cleanup only matters in the case where local disk scheduling is being taken into account, it makes sense to me to use the existing feature flag to expedite fixing the thundering herd issue for 1.8.x, and give us more time to figure out how to resolve the issue when the local disk scheduling is enabled

**Comment by yujuhong** [comment]
Spoke to @dashpole offline. The feature gate sounds like a good compromise.
The only downside is we'd have to live with (overly) aggressive pod eviction for longer to fix this properly. That seems tolerable since the bug existed in 1.7 as well.

On the other hand, I'd rather see the feature gate change be included in the 1.8.0, as opposed to the change of behavior from 1.8.0 to 1.8.1 with no good reason.

**Comment by wojtek-t** [comment]
So what's the status of that? In my opinion, solution with feature gate seems acceptable and it would be great if we could merge it and backport to 1.8.1.

**Comment by dashpole** [comment]
Closing as this PR is no longer needed. The underlying issue is solved by #53233.  See https://github.com/kubernetes/kubernetes/pull/53233#issuecomment-333876776

**Comment by jpbetz** [comment]
Removing 1.8 milestone since this is no longer needed.

**Pull request closed without merging**
