### PR TITLE
register client-go auth plugins for e2e

### LINKED ISSUE #63731: pull-kubernetes-e2e-gke failing with internal Ginkgo failure
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
E2E keeps failing with internal Ginkgo failure of "Node 1 disappeared before completing BeforeSuite" on my PR.
https://github.com/kubernetes/kubernetes/pull/63718
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/63718/pull-kubernetes-e2e-gke/1391/?log#log
https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/onsi/ginkgo/internal/leafnodes/synchronized_before_suite_node.go#L107

**What you expected to happen**:
Not that.

**How to reproduce it (as minimally and precisely as possible)**:
Run /retest on my PR. It's happened 5 times in a row. 

**Anything else we need to know?**:
I am almost certain my change does not affect that test suite in any way.

### PR DESCRIPTION
**Pull request by liggitt**
e2e depends on use of the gcp client-go auth provider, but did not explicitly register the auth provider. it indirectly imported the plugins via a roundabout chain (see https://github.com/kubernetes/kubernetes/issues/63731#issuecomment-388529120) which broke when those imports were trimmed in https://github.com/kubernetes/kubernetes/pull/63673

if e2e requires these auth plugins, it should include them explicitly in the top-level test package

fixes #63731

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
@kubernetes/sig-testing-pr-reviews

**Review by fejta — COMMENTED** [review]
/lgtm

Thanks!

**Pull request merged**
