### PR TITLE
Support both GET and POST methods in api server for /exec and /portforward

### PR DESCRIPTION
**Pull request by nikhiljindal**
First part of https://github.com/GoogleCloudPlatform/kubernetes/issues/10366.

This just updates API server to start supporting both GET and POST methods.
Will send another PR to update kubectl.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @bgrant0607 @lavalamp @smarterclayton

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
@bgrant0607 for second LGTM

**Comment by smarterclayton** [comment]
LGTM

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
