### PR TITLE
Add a new interface for scheduling queue

### PR DESCRIPTION
**Pull request by bsalamat**
This PR paves the way to add a different data structure (e.g., priority queue) in subsequent PRs, but it does not make any logical or behavioral changes.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
ref/ #54501

### CODE REVIEW

**Review by mariida — APPROVED** [review]

**Comment by bsalamat** [comment]
cc/ @k82cn @resouer

**Review by resouer — APPROVED** [review]
Thanks! The code did not change core logic and is well commented. So let's have it to allow subsequences PRs in.

**Pull request merged**
