### PR TITLE
e2e: podresources: promote platform-independent test as NodeConformance

### LINKED ISSUE #116421: promote a subset of podresources e2e tests to NodeConformance
### What would you like to be added?

We have already quite a few podresources-related e2e tests. We should promote some among the most stable subset of them as NodeConformance. This is especially useful considering the plans to move [podresources to GA](https://github.com/kubernetes/enhancements/pull/3791).

According to testgrid some possible candidates are: 
- [sig-node] POD Resources [Serial] [Feature:PodResources][NodeFeature:PodResources] when querying /metrics should report the values for the podresources metrics
- [sig-node] POD Resources [Serial] [Feature:PodResources][NodeFeature:PodResources] without SRIOV devices in the system with CPU manager None policy should return the expected responses

### Why is this needed?

As part of the [GA graduation of the podresources endpoint](https://github.com/kubernetes/enhancements/pull/3863) we want to enable the endpoint also on windows, where [it is currently disabled](https://github.com/kubernetes/kubernetes/blob/v1.27.0-alpha.3/pkg/kubelet/util/util_windows.go#L121).

Windows lanes run `NodeConformance` tests. We already have some podresources e2e tests, and promoting them to `NodeConformance` will enables us to both ensuring the code keeps working on windows, where it was exercised way less, and increase the stability of the codebase.

### PR DESCRIPTION
**Pull request by ffromani**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Promote podresources e2e tests to conformance. Unfortunatly for reasons explained in the commit message we can just promote a single test, because we need cross-platform support. It's still a start.

#### Which issue(s) this PR fixes:
Fixes #116421

#### Special notes for your reviewer:
Enhancements of podresources e2e tests to be able to promote more is deferred to future PRs.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]
All tests for this PR are green, meaning this works.

/lgtm

**Comment by ffromani** [comment]
Thanks for the quick review! I'll keep an eye on the lanes and prep the trivial revert in cause of any issue.

**Pull request merged**
