### PR TITLE
Fixed macos build permission errors

### LINKED ISSUE #33800: Permission denied error on .make/all_go_dirs.mk (or .make) during MaxOs  Build with docker-machine
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

This is not a request for help. 

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

I have searched for these keywords
mac id build 
Nothing relevant came up. 
The closest relevant issue is: kubernetes build on master branch failed on osx #29247

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

 BUG REPORT

**Kubernetes version** (use `kubectl version`):

This is a build script bug. I do not know whether the kubectl version would be helpful 
The git repo point is 

commit 6c5a18717137b3227644bccbdcdd8890b887934b
Merge: 364caad 5080a57
Author: Kubernetes Submit Queue <k8s-merge-robot@users.noreply.github.com>
Date:   Thu Sep 29 12:32:08 2016 -0700

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
OSx 10.11.6

- **Kernel** (e.g. `uname -a`):
Darwin mbp-005063 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
- **Install tools**:

$ docker --version
Docker version 1.10.3, build 20f81dd
$ docker-machine --version
docker-machine version 0.6.0, build e27fb87

(This is not the latest version of docker, however the build script does not complain with a not-supported error. I presume this combination should still work) 

- **Others**:

**What happened**:

The hack/update-all.sh script fails with the following prompt 
(.make/all_go_dirs.mk: Permission denied)

$ hack/update-all.sh  -v
Running in short-circuit mode; run with -a to force all scripts to run.
Updating generated-protobuf
+++ [0929 15:04:06] Verifying Prerequisites....
+++ [0929 15:04:06] No docker host is set. Checking options for setting one...
+++ [0929 15:04:06] docker-machine was found.
+++ [0929 15:04:07] A Docker host using docker-machine named 'kube-dev' is ready to go!
+++ [0929 15:04:07] Building Docker image kube-build:build-fb58d75ded
+++ [0929 15:04:07] Running build command....
+++ [0929 15:04:07] Creating data container kube-build-data-fb58d75ded
make: Entering directory '/go/src/k8s.io/kubernetes'
make[1]: Entering directory '/go/src/k8s.io/kubernetes'
hack/make-rules/helpers/cache_go_dirs.sh: line 65: .make/all_go_dirs.mk: Permission denied
find: `./pkg/kubelet/volumemanager/reconciler/pods': Permission denied
rm: cannot remove '.make/all_go_dirs.mk': Permission denied
^CMakefile:287: recipe for target 'generated_files' failed

 I have also discovered other scenarios where the permission error is for .make directory. 
After a local `make`execution, the update-all.sh script generates a permission error for .make/all_go_dirs.mk. 
If one does a `make clean && hack/update-all.sh` the permission error would be for .make directory.  

**What you expected to happen**:

I expect this to complete without any error. 

**How to reproduce it** (as minimally and precisely as possible):

Checkout the https://github.com/kubernetes/kubernetes.git at 6c5a18717137b3227644bccbdcdd8890b887934b in Mac os with OsX ElCapitan 10.11.6

Use docker version 1.10.3
Go to the root directory of the repo and execute `hack/update-all.sh -v`

**Anything else do we need to know**:

In MacOsX with non-native docker, the hack/update-all.sh uses the present docker-machine to launch docker containers. 
It compiles the docker run command options like the following: 

local -a docker_run_opts=(
  "--name=${KUBE_BUILD_CONTAINER_NAME}"
  "--user=$(id -u):$(id -g)"
  "--hostname=${HOSTNAME}"
  "${DOCKER_MOUNT_ARGS[@]}"
)
In kubernetes/build/common.sh file  in kube::build::run_build_command() funciton. 

This bash script extract runs in the host MacOs machine. That means the id -u and the id -g will be the user's id on the host mac os. 

The compiled docker command looks like the following: 
 
docker run --name=kube-build-fb58d75ded --user=980771313:1221986466 --hostname=mbp-005063 --volume

The 980771313:1221986466 user id and the group id are associated with the MacOs in the host. 

However the `docker run ...` command will execute in a vm managed by docker-machine. (In my system the vm's version is kube-dev) 

We run this command in the kube-dev vm where the user id looks like the following: 
docker@kube-dev:~$ id -u
1000
docker@kube-dev:~$ id -g
50

I strongly believe that the mismatched user id and the group id between the kube-dev vm and the docker container used to execute the hack/update-all.sh script cause this permission error.

### PR DESCRIPTION
**Pull request by ahakanbaba**
**What this PR does / why we need it**:

The created containers were passed wrong user and group ids.
This happened if the container was running in a docker-machine.

This change get the correct uid and gid to pass to the started
container.
If a docker-machine is running, it uses the id's inside the kube-dev vm.
Otherwise the uid and gid from the host machine are used.

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #

Fixes #33800

**Special notes for your reviewer**:

**Release note**:

``` release-note
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33964)

### CODE REVIEW

**Comment by jbeda** [comment]
@ahakanbaba -- I'd like to understand a little bit more about why you are hitting this.

Are you running on a Mac and using docker machine there?  Or is the machine really remote?  

In any case, just testing for `docker-machine` is probably not good enough.  Folks may have that installed but still use a local docker instance.

Generally, we do this so that any "bind mounted" volumes will have useful uid/gid.

This should also change with #30787 where we will no longer be doing any bind mounts.

**Comment by ahakanbaba** [comment]
On Mon, Oct 3, 2016 at 2:30 PM, Joe Beda <notifications@github.com> wrote:

> @ahakanbaba <https://github.com/ahakanbaba> -- I'd like to understand a
> little bit more about why you are hitting this.
>
Hi @jbeda. Thanks for the prompt response.

> Are you running on a Mac and using docker machine there? Or is the machine
> really remote?
>
I am running on a mac and using docker-machine there.
I execute the `hack/update-all.sh -v` on my macOs' terminal .
After going through the scripts I understand that it discovers a
docker-machine executable in my mac. Starts a vm in docker-machine called
kube-dev and starts docker containers in kube-dev to execute build commands
(for example make) .

if you desire more input I could enable "set -x" in one of the earlier
scripts and append the output here.



> In any case, just testing for docker-machine is probably not good enough.
> Folks may have that installed but still use a local docker instance.
>
I see, you are right.  The following is the first decision point for how to
use docker.
function kube::build::docker_available_on_osx() {
  if [[ -z "${DOCKER_HOST}" ]]; then
    if [[ -S "/var/run/docker.sock" ]]; then
      kube::log::status "Using Docker for MacOS"
      return 0
    fi

    kube::log::status "No docker host is set. Checking options for setting
one..."
    if [[ -z "$(which docker-machine)" && -z "$(which boot2docker)" ]]; then
      kube::log::status "It looks like you're running Mac OS X, yet none of
Docker for Mac, docker-machine or boot2docker are on the path."
      kube::log::status "See: https://docs.docker.com/machine/ for
installation instructions."
      return 1
    elif [[ -n "$(which docker-machine)" ]]; then
      kube::build::prepare_docker_machine
    elif [[ -n "$(which boot2docker)" ]]; then
      kube::build::prepare_boot2docker
    fi
  fi
}

Maybe I could use a similar logic to figure out which --user option to pass
to the `docker run` command ?

> Generally, we do this so that any "bind mounted" volumes will have useful
> uid/gid.
>
> This should also change with #30787
> <https://github.com/kubernetes/kubernetes/pull/30787> where we will no
> longer be doing any bind mounts.
>
I did not understand this comment .
Did you mean that this --user option will not be used after #30787 ?

I have briefly looked into #30787.
This docker-options
<https://github.com/kubernetes/kubernetes/pull/30787/files#diff-0ee501c7b4b1ab61678579826c6d6534L615>
has been removed but this docker-options
<https://github.com/kubernetes/kubernetes/pull/30787/files#diff-0ee501c7b4b1ab61678579826c6d6534L562>
still is in the pull request.

Thanks

**Comment by ahakanbaba** [comment]
@jbeda, 
A follow up question, 
Could one use DOCKER_NATIVE var (defined at the top of build/common.sh) in my new docker_user_group_id function ? Can DOCKER_NATIVE be used variable to decide which docker is used in the compilation flow ? 

I see DOCKER_NATIVE defied but I do not see any usages of it. 

```
k8s.io/kubernetes $ grep DOCKER_NATIVE * -r  -I
build/common.sh:DOCKER_NATIVE=${DOCKER_NATIVE:-""}
hack/local-up-cluster.sh:DOCKER_NATIVE=${DOCKER_NATIVE:-""}
```

Apologies in advance if you are not the go-to person for these kind of questions. I would really appreciate if you can direct me to the right person or document. 

Thanks

**Comment by jbeda** [comment]
I'm not sure *what* `DOCKER_NATIVE` does.  Looks to be left over cruft.  We should remove it :)

Right now we are trying to simplify this stuff.  I'd love to remove the code that automatically starts up a new docker-machine for folks.  I don't think it is too much (especially with Docker for Mac) to expect folks to have Docker configured on a mac to make things right.

Let me debug this a bit and see what is going on.

**Comment by ahakanbaba** [comment]
OK @jbeda. Thanks
Please let me know if there is anything I can help or if you have any problems reproducing it.

**Comment by jbeda** [comment]
I think I see the problem here.  Volume mounts through docker-machine/virtualbox on the mac map uid/gid differently from volume mounts using "Docker for Mac" or on linux.  That is the root of the confusion here.  

This is all pretty hack-o-rama in docker-machine. Specifically look at `/etc/rc.d/vbox` in a running docker-machine VM.

Honestly, I'm working on simplifying this dramatically and I'd rather not make it more complex with this extra check.  Things should work fine with "Docker for Mac" if you are able to use that.  If not, then we can look at finding a way to get this fixed.

Once we have #30787 fixed then this should go away.  I'm going to be working to get that one finished up ASAP.

**Comment by ahakanbaba** [comment]
Hi @jbeda.
Thank you very much for your time on working on this. Really appreciate all
the help.

On Mon, Oct 3, 2016 at 5:25 PM, Joe Beda <notifications@github.com> wrote:

> I think I see the problem here. Volume mounts through
> docker-machine/virtualbox on the mac map uid/gid differently from volume
> mounts using "Docker for Mac" or on linux. That is the root of the
> confusion here.
>
> This is all pretty hack-o-rama in docker-machine. Specifically look at
> /etc/rc.d/vbox in a running docker-machine VM.
>
> Honestly, I'm working on simplifying this dramatically and I'd rather not
> make it more complex with this extra check. Things should work fine with
> "Docker for Mac" if you are able to use that. If not, then we can look at
> finding a way to get this fixed.
>

Unfortunately we are at an older version of docker right now where the
native docker is not available on macOS. I do not think upgrading to the
MacOs native docker is an option for me at this point.

From our point if view it would be good to fix this problem. I am willing
to help as much as possible.


>
Once we have #30787 <https://github.com/kubernetes/kubernetes/pull/30787>
> fixed then this should go away. I'm going to be working to get that one
> finished up ASAP.
>

If #30787 is, say days away from merging, then we could find a workaround
up until then.
Maybe I could keep the change in common.sh in my local branch and refrain
from committing it. That way I could still build and do some work.

I am surprised no-one else has ran into this issue.
Either people are running a more recent docker or not compiling on mac.

**Comment by jbeda** [comment]
I think that #30787 should get merged very soon.  It has been baking for a while.  If it doesn't make it in within the next week, let's get something like this merged.

As for why you are the first to hit this.  First, most of the google and redhat folks develop on linux.  Second, only `update-all.sh` is broken.  It does some funky things to be able to get generated results back out.

**Comment by ahakanbaba** [comment]
On Tue, Oct 4, 2016 at 4:03 PM, Joe Beda <notifications@github.com> wrote:

> I think that #30787 <https://github.com/kubernetes/kubernetes/pull/30787>
> should get merged very soon. It has been baking for a while. If it doesn't
> make it in within the next week, let's get something like this merged.
>
> As for why you are the first to hit this. First, most of the google and
> redhat folks develop on linux. Second, only update-all.sh is broken. It
> does some funky things to be able to get generated results back out.
>

Thanks Joe.
What you suggest is very reasonable
Also thanks for the explanation.
Hakan

**Comment by ahakanbaba** [comment]
I have realized that this change breaks the build/release.sh 

it looks like we need to consider more cases if we are going to revisit this PR.
@jbeda mentioned before that  a mere `which docker-machine` check is not enough but apparently there are more interactions going on. 


The update-all.sh executes the following docker command. 
```
docker run --name=kube-build-fb58d75ded --user=1000:50 --hostname=mbp-005063 --volume /Users/hbaba/box/src/skynet/go/src/k8s.io/kubernetes:/go/src/k8s.io/kubernetes --volume /etc/localtime:/etc/localtime:ro --volumes-from kube-build-data-fb58d75ded --env KUBE_FASTBUILD=false --env KUBE_BUILDER_OS=darwin15 --env KUBE_BUILD_PPC64LE=n --interactive --tty kube-build:build-fb58d75ded hack/update-generated-protobuf-dockerized.sh
```

This command mounts the entire kubernetes source tree to the container although the source was added in the Dockerfile with the following
```
# Upload Kubernetes source
ADD kube-source.tar.gz /go/src/k8s.io/kubernetes/
```
Is this one of the " funky things to be able to get generated results back out" ? 

The build/release.sh script executes the following docker command: 

```
docker run --name=kube-build-fb58d75ded --user=1000:50 --hostname=mbp-005063 --volume /Users/hbaba/box/src/skynet/go/src/k8s.io/kubernetes/_output/dockerized/bin:/go/src/k8s.io/kubernetes/_output/dockerized/bin --volume /etc/localtime:/etc/localtime:ro --volumes-from kube-build-data-fb58d75ded --env KUBE_FASTBUILD=false --env KUBE_BUILDER_OS=darwin15 --env KUBE_BUILD_PPC64LE=n --interactive --tty kube-build:build-fb58d75ded make cross
```

Here not the entire kubernetes source tree is mounted, but only the dockerized/bin directory. 

This distinction may be the reason why this change worked for update-allsh but broke build/release.sh

**Comment by jbeda** [comment]
Now that #30787 is in, I don't think this should be necessary any more.  Please try with the latest sources and let me know if you hit issues.

Thanks!

**Comment by ahakanbaba** [comment]
Thanks. 
I will try and let you know.

**Pull request closed without merging**
