### PR TITLE
Remove kubectl alpha debug command in 1.21

### PR DESCRIPTION
**Pull request by pandaamanda**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubectl: The deprecated `kubectl alpha debug` command is removed. Use `kubectl debug` instead.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/approve
/hold
for @verb final word

**Comment by verb** [comment]
Thanks @pandaamanda !

/lgtm
/hold cancel

**Pull request merged**
