### PR TITLE
Fix Getpath() description

### PR DESCRIPTION
**Pull request by riverzhang**
Modify the description of the word error

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by thockin** [comment]
/lgtm
/approve no issue
@k8s-bot ok to test

**Comment by riverzhang** [comment]
@thockin   I am sorry I repeated it once again

**Comment by riverzhang** [comment]
@thockin  I am sorry,  I commit it again.

**Comment by riverzhang** [comment]
@thockin      /approve no issue     Less a horizontal line

**Comment by riverzhang** [comment]
test pull-kubernetes-kubemark-e2e-gce

**Pull request merged**
