### PR TITLE
using defer rather than directly log

### PR DESCRIPTION
**Pull request by zouyee**
**What this PR does / why we need it**:

using defer rather than directly log

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:

```
NONE

```

### CODE REVIEW

**Comment by liggitt** [comment]
thanks for the PR, I'd leave the log-levels as-is unless there's a reason to change them

**Comment by zouyee** [comment]
ping @liggitt

**Comment by liggitt** [comment]
for such a short function, I actually think it's easier to follow the intent as is

**Comment by liggitt** [comment]
I think the code is probably easier to follow without the defer
/close

**Pull request closed without merging**
