### PR TITLE
Create EnsureExists class addons before Reconcile class addons

### PR DESCRIPTION
**Pull request by MrHohn**
From #42757.

The addon-manager creates "Reconcile" class addons before creates "EnsureExists" class addons, which is not the best order. The "EnsureExists" class addons tend to be some default configurations like `default-storage-class` and `default kube-dns ConfigMap` (being added in #42757), and we would like to have these default configurations created before other addons are created.

@mikedanese @bowei 

```release-note
NONE
```

### CODE REVIEW

**Comment by MrHohn** [comment]
@k8s-bot cvm gce e2e test this

**Comment by mikedanese** [comment]
/lgtm
/approve

This fixes kube-dns upgrades.

**Comment by MrHohn** [comment]
@mikedanese Thanks! Do you mind if I also push the new images with this PR?

**Comment by MrHohn** [comment]
Sorry for the noise, I pushed the images to make this takes effect.

Note: Will update the [kubemark template](https://github.com/kubernetes/kubernetes/blob/master/test/kubemark/resources/manifests/kube-addon-manager.yaml) later as that might take longer to get approved and are unrelated to the test failure.

**Review by bowei — APPROVED** [review]
/lgtm

**Comment by MrHohn** [comment]
@k8s-bot cvm gce e2e test this

**Comment by bowei** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
