### PR TITLE
Update corefile-migration to v1.0.12.

### PR DESCRIPTION
**Pull request by dlorenc**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The coredns/corefile-migration project switched to a fork of
coredns/caddy to remove dependencies it doesn't actually need. Picking
up this update here in k/k results in a significantly smaller go.mod.

Signed-off-by: Dan Lorenc <dlorenc@google.com>

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by rajansandeep — COMMENTED** [review]
I believe https://github.com/kubernetes/kubernetes/pull/102466 is updating the migration library to 1.0.12

**Comment by dlorenc** [comment]
Ah thanks! Missed it in my search because it was a draft.

**Comment by dims** [comment]
/assign @neolit123 @liggitt 

Lubomir, does this look good? since `kubeadm` is the only one using this package:
https://cs.k8s.io/?q=coredns%2Fcorefile-migration&i=nope&files=.*%5C.go&excludeFiles=&repos=kubernetes/kubernetes

/approve
/lgtm

**Comment by dims** [comment]
@liggitt looks like we are dropping stuff nicely!

```
2c2
< 	"totalDependencies": 380,
---
> 	"totalDependencies": 364,
4c4
< 	"transitiveDependencies": 254
---
> 	"transitiveDependencies": 238
```

**Comment by liggitt** [comment]
> @liggitt looks like we are dropping stuff nicely!

fantastic

/approve

**Comment by neolit123** [comment]
There us already this. https://github.com/kubernetes/kubernetes/pull/102466

Cc @pacoxu

**Pull request merged**
