### PR TITLE
Fix PortForwarder.forward to fill bound port when local port unspecified

### LINKED ISSUE #69052: PortForwarder.GetPorts does not return correct port number when local port omitted or set to zero.
/kind bug

Hey guys,

I came across the new code on master to return the list of forwarded ports (see here: https://github.com/kubernetes/client-go/blob/master/tools/portforward/portforward.go#L349).

After doing some testing, I discovered that this function does not return the correct port if the local port is specified as '0' or left unspecified.

This seems to be because the port reference passed in to portforwarder.listenOnPort is a copy of the ForwardedPort struct, and not the actual ForwardedPort owned by the PortForwarder (see here: https://github.com/kubernetes/client-go/blob/master/tools/portforward/portforward.go#L155).

Environment:
- Kubernetes version (use `kubectl version`): git master
- Cloud provider or hardware configuration: n/a
- OS (e.g. from /etc/os-release): client-go running on Darwin
- Kernel (e.g. `uname -a`): Darwin aarora-w10vm.internal.synopsys.com 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
- Install tools: n/a
- Others: n/a

### PR DESCRIPTION
**Pull request by mtaylor91**
**What this PR does / why we need it**: Bug fix for client-go/tools/portforward

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #69052 

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
Thanks for the PR. Can we add a test to verify the port accessor method now works properly?

**Comment by yliaog** [comment]
the fix looks good, please add a test.

**Comment by mtaylor91** [comment]
@yliaog Sorry for the delay - it's been a pretty hectic month and I haven't had a chance to come back to this to add test coverage until now.  I factored out a function (startListeners) to set up the local listeners so that can be tested independently of the blocking 'forward' function.  Test coverage of the file as a whole is still pretty sub-optimal; but there's now a test for the issue I reported and fixed, at least.  My 'TestBindListeners' test does not attempt to test the normal case where the Local port is specified, as I'm not sure what the testing infrastructure is like and which ports are safe to bind deterministic-ally, so I focused instead on testing the case where the Local port is passed in as zero and we expect it be filled in by 'startListeners' (i.e. I added a test for the thing I fixed, not the functionality that was already there).  That should be safe as I assume the test executor has at least one free port that can be bound.

Let me know if you have any other feedback and I'll try and get to it a bit quicker this time :)

**Pull request closed without merging**
