### PR TITLE
Actually enabled Autoscaling e2e test for Jenkins flaky job

### PR DESCRIPTION
**Pull request by piosz**
follow up #12783

### CODE REVIEW

**Comment by ixdy** [comment]
FYI, this is failing consistently on kubernetes-e2e-gce-flaky now:

```
Aug 17 16:09:00.988: INFO: Waiting up to 1m0s for all nodes to be ready
Aug 17 16:09:05.993: INFO: Node e2e-flaky-minion-bw9q condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transition time: 2015-08-17 15:50:51 -0700 PDT
Aug 17 16:09:05.993: INFO: Successfully found node e2e-flaky-minion-bw9q readiness to be true
Aug 17 16:09:05.993: INFO: Node e2e-flaky-minion-c5v3 condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transition time: 2015-08-17 15:51:01 -0700 PDT
Aug 17 16:09:05.993: INFO: Successfully found node e2e-flaky-minion-c5v3 readiness to be true
Aug 17 16:09:05.993: INFO: Node e2e-flaky-minion-edyf condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transition time: 2015-08-17 15:50:51 -0700 PDT
Aug 17 16:09:05.993: INFO: Successfully found node e2e-flaky-minion-edyf readiness to be true
Aug 17 16:09:05.993: INFO: Node e2e-flaky-minion-ivkb condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transition time: 2015-08-17 15:58:54 -0700 PDT
Aug 17 16:09:05.993: INFO: Successfully found node e2e-flaky-minion-ivkb readiness to be true
STEP: Destroying namespace "e2e-tests-autoscaling-1ol5u" for this suite.
[AfterEach] Autoscaling
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling.go:51
STEP: Removing autoscaler

• Failure [996.065 seconds]
Autoscaling
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling.go:92
  [Autoscaling] should scale cluster size based on cpu utilization [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling.go:61

  Expected error:
      <*errors.errorString | 0xc20820c590>: {
          s: "timeout waiting 10m0s for cluster size to be 3",
      }
      timeout waiting 10m0s for cluster size to be 3
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling.go:60
```

**Comment by ixdy** [comment]
Err, more relevant log:
```
Aug 17 16:08:20.957: INFO: Waiting for cluster size 3, current size 4
Aug 17 16:08:40.963: INFO: Node e2e-flaky-minion-bw9q condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transition time: 2015-08-17 15:50:51 -0700 PDT
Aug 17 16:08:40.963: INFO: Successfully found node e2e-flaky-minion-bw9q readiness to be true
Aug 17 16:08:40.963: INFO: Node e2e-flaky-minion-c5v3 condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transition time: 2015-08-17 15:51:01 -0700 PDT
Aug 17 16:08:40.963: INFO: Successfully found node e2e-flaky-minion-c5v3 readiness to be true
Aug 17 16:08:40.963: INFO: Node e2e-flaky-minion-edyf condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transition time: 2015-08-17 15:50:51 -0700 PDT
Aug 17 16:08:40.963: INFO: Successfully found node e2e-flaky-minion-edyf readiness to be true
Aug 17 16:08:40.963: INFO: Node e2e-flaky-minion-ivkb condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transition time: 2015-08-17 15:58:54 -0700 PDT
Aug 17 16:08:40.963: INFO: Successfully found node e2e-flaky-minion-ivkb readiness to be true
Aug 17 16:08:40.963: INFO: Waiting for cluster size 3, current size 4
```

**Comment by piosz** [comment]
I'm working to fix it.

**Comment by gmarek** [comment]
The reason it was merged was that @piosz wasn't able to reliably reproduce failures locally, so we wanted to run it on Jenkins to allow debugging.

**Pull request merged**
