### PR TITLE
Update defaulter gen to not use reflect

### PR DESCRIPTION
**Pull request by Jefftree**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Show diff after applying the changes in https://github.com/kubernetes/gengo/pull/195 to the kubernetes types. Remove the reflect library import introduced in a previous PR.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by Jefftree** [comment]
/assign @lavalamp 

The follow ups for https://github.com/kubernetes/gengo/pull/195 shouldn't change the generated code in any way so I think it's safe to merge this first.

**Comment by lavalamp** [comment]
/lgtm
/approve

Sorry, ping me next time I sit on something this long, haha!

**Pull request merged**
