### PR TITLE
Convert ComputerName to lower case

### LINKED ISSUE #58274: Failed to get external ID from cloud provider
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
/sig azure

**What happened**:

When vmss is used on Azure, kubelet reports `Failed to get external ID from cloud provider` error and couldn't recovert itself.

**What you expected to happen**:

Kubelet should register itselft correctly.

**How to reproduce it (as minimally and precisely as possible)**:

Create a Kubernetes cluster with vmss vmType and scale instances numbers > 10.

**Anything else we need to know?**:

When instances count is greater than 10, azure will generate instance hostname with upper cases. But kubelet always converts hostname to lower case. 

So azure cloud provider should also covert OsProfile.ComputerName to lower case.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by feiskyer**
**What this PR does / why we need it**:

When instances count is greater than 10, azure will generate instance hostname with upper cases. But kubelet always converts hostname to lower case.

So azure cloud provider should also covert OsProfile.ComputerName to lower case.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #58274

**Special notes for your reviewer**:

This PR also adds more unit tests for scale sets.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by feiskyer** [comment]
Fixed a gofmt issue.

**Comment by andyzhangx** [comment]
@feiskyer your gofmt on VS code also does not work?

**Review by andyzhangx — APPROVED** [review]

**Comment by feiskyer** [comment]
> @feiskyer your gofmt on VS code also does not work?

Seems so, got different results from `hack/update-gofmt.sh`.

**Comment by feiskyer** [comment]
hmm, it will format the file on each save, but not always same with `hack/update-gofmt.sh`.

**Comment by feiskyer** [comment]
Rebased. @andyzhangx PTAL

**Review by andyzhangx — APPROVED** [review]

**Pull request merged**
