### PR TITLE
kubeadm: Improve kubeadm init cmd tests

### PR DESCRIPTION
**Pull request by rosti**
**What this PR does / why we need it**:

This PR improves kubeadm init cmd tests in the following ways:

- Fix a few cases that were always successful (despite completely wrong).
- Add more test cases (for different configs in particular)
- Use dry run, to avoid modifying the system and using kubeadm reset

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes NONE

**Special notes for your reviewer**:
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews
/area kubeadm
/assign @luxas
/assign @timothysc

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
i'm pretty sure this needs a bazel update.

**Review by timothysc — APPROVED** [review]
/approve 

You'll need the test fixes though.

**Pull request merged**
