### PR TITLE
remove deprecated option '--enable-custom-metrics'

### PR DESCRIPTION
**Pull request by CaoShuFeng**
**Release note**:
```release-note
deprecated and inactive option '--enable-custom-metrics' is removed in 1.11
```

### CODE REVIEW

**Comment by dixudx** [comment]
Anyone helping add a release label `v1.11` for this PR?

/lgtm

**Comment by dashpole** [comment]
/lgtm
The deprecation notice was added in the 1.9 release, so it has been deprecated for 2 releases.
https://github.com/kubernetes/kubernetes/commit/50b5a124bf79abeb986cf106114ccba7e101e6fc

**Comment by mtaufen** [comment]
/lgtm
/assign @vishh 
for approval

**Comment by CaoShuFeng** [comment]
rebased.

**Comment by dims** [comment]
@CaoShuFeng Can you please rebase?

**Comment by jberkus** [comment]
Also, is there a docs patch associated with this?  If we're removing the switch, it needs to be removed from the docs.

**Comment by CaoShuFeng** [comment]
> @CaoShuFeng Can you please rebase?
Done.

**Comment by CaoShuFeng** [comment]
> Also, is there a docs patch associated with this? If we're removing the switch, it needs to be removed from the docs.

I `grep`ed the kubernetes.github.io project, there is not description about this option.

This option has been inert for a while, so it's safe to remove it now.

**Comment by dims** [comment]
This PR does not look critical for 1.11, and is not in an ready-to-merge state.  As such, it will be removed from the 1.11 milestone by the milestone bot when Code Freeze starts at midnight UTC / 5pm PDT.  If you feel it is critical to 1.11, please upgrade its priority to critical-urgent.

**Comment by bboreham** [comment]
Drive-by observation: "deprecated option" in the release note makes me think it was doing something, and now I can't do that thing. From my reading of the code it was doing nothing, so something like "deprecated and inactive option" would be better.

**Comment by CaoShuFeng** [comment]
> so something like "deprecated and inactive option" would be better.

Done.

**Comment by jberkus** [comment]
@dashpole @gmarek @dixudx @mtaufen @vishh  @derekwaynecarr 

Can we get an approver on this?  The submitter has been very responsive and followed release process, and this is a low-risk patch.  I'd like to set it go in.

**Comment by CaoShuFeng** [comment]
@jberkus 
Needs to improve the priority level to get it merged, thanks.

**Comment by jberkus** [comment]
Escalating priority so it will merge.

/priority critical-urgent

**Pull request merged**
