### PR TITLE
move MergeBuckets into component-base so we can properly support it for static-analysis

### PR DESCRIPTION
**Pull request by logicalhan**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

We're going to support merge function for static analysis, so move the method into component-base so we can rely on that method definition. 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by logicalhan** [comment]
/assign @justaugustus
(for ./hack)

**Comment by liggitt** [comment]
/approve

for hack addition

**Pull request merged**
