### PR TITLE
Remove race in setting/reading kubelet.podCIDR

### PR DESCRIPTION
**Pull request by cjcullen**

### CODE REVIEW

**Comment by roberthbailey** [comment]
LGTM.

**Comment by vmarmol** [comment]
Need leads LGTM for this?

**Comment by roberthbailey** [comment]
Bouncing to @alex-mohr for another LGTM.

**Comment by alex-mohr** [comment]
Does this close an issue?

**Comment by rjnagal** [comment]
LG, merging.

**Comment by cjcullen** [comment]
It is a potential fix for #10622. No proof, but it was our best lead, and an obvious bug.

**Pull request merged**
