### PR TITLE
Fix url for Saltstack administration document

### PR DESCRIPTION
**Pull request by yujunz**
Got an 404 not found error on `https://kubernetes.io/docs/admin/salt.md`

**What this PR does / why we need it**:

Fixed a wrong url in document

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

NONE

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
@yujunz Yujun, please sign your CLA :)

**Comment by roberthbailey** [comment]
Thanks for the fix. This should merge quickly once you sign the CLA.

**Comment by yujunz** [comment]
> @yujunz Yujun, please sign your CLA :)

Done

**Pull request merged**
