### PR TITLE
Fix a error comment about `SupportIPVSProxyMode`

### PR DESCRIPTION
**Pull request by miaoyq**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Review by luxas — COMMENTED** [review]
Isn't this gonna be beta in v1.9?

**Comment by timothysc** [comment]
I don't see how that comment is "wrong"

**Comment by xiangpengzhao** [comment]
This feature gate has been removed from kubeadm. We can close this PR now.
/close

**Comment by xiangpengzhao** [comment]
I guess @miaoyq was thinking of that kubeadm started supporting ipvs feature gate from 1.9 :)

**Pull request closed without merging**
