### PR TITLE
kubelet/cm: Unite return value types of helper functions

### PR DESCRIPTION
**Pull request by hshiina**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This PR changes the return value of `MilliCPUToShares()` to `uint64` at all platforms.
I hit this issue at adding unit tests in #127300.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ffromani** [comment]
just thinking out aloud:
```
$ git grep -w MilliCPUToShares
pkg/kubelet/cm/helpers_linux.go:84:// MilliCPUToShares converts the milliCPU to CFS shares.
pkg/kubelet/cm/helpers_linux.go:85:func MilliCPUToShares(milliCPU int64) int64 {
pkg/kubelet/cm/helpers_linux.go:159:    cpuShares := MilliCPUToShares(cpuRequests)
pkg/kubelet/cm/helpers_linux_test.go:61:        burstableShares := MilliCPUToShares(100)
pkg/kubelet/cm/helpers_linux_test.go:64:        burstablePartialShares := MilliCPUToShares(200)
pkg/kubelet/cm/helpers_linux_test.go:66:        guaranteedShares := MilliCPUToShares(100)
pkg/kubelet/cm/helpers_linux_test.go:306:       burstableShares := MilliCPUToShares(100)
pkg/kubelet/cm/helpers_linux_test.go:309:       burstablePartialShares := MilliCPUToShares(200)
pkg/kubelet/cm/helpers_linux_test.go:311:       guaranteedShares := MilliCPUToShares(100)
pkg/kubelet/cm/helpers_linux_test.go:673:       burstableShares := MilliCPUToShares(100)
pkg/kubelet/cm/helpers_linux_test.go:676:       burstablePartialShares := MilliCPUToShares(200)
pkg/kubelet/cm/helpers_linux_test.go:678:       guaranteedShares := MilliCPUToShares(100)
pkg/kubelet/cm/helpers_unsupported.go:43:// MilliCPUToShares converts the milliCPU to CFS shares.
pkg/kubelet/cm/helpers_unsupported.go:44:func MilliCPUToShares(milliCPU int64) int64 {
pkg/kubelet/cm/node_container_manager_linux.go:177:             val := MilliCPUToShares(q.MilliValue())
pkg/kubelet/cm/qos_container_manager_linux.go:193:      burstableCPUShares := MilliCPUToShares(burstablePodCPURequest)
pkg/kubelet/kuberuntime/helpers_linux_test.go:440:                      shares := int64(cm.MilliCPUToShares(testMilliCPU))
pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:224:             cpuShares = int64(cm.MilliCPUToShares(cpuLimit.MilliValue()))
pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:226:             // if cpuRequest.Amount is nil, then MilliCPUToShares will return the minimal number
pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:228:             cpuShares = int64(cm.MilliCPUToShares(cpuRequest.MilliValue()))
test/e2e/node/pod_resize.go:405:                                cpuShares = int64(kubecm.MilliCPUToShares(cpuLimit.MilliValue()))
test/e2e/node/pod_resize.go:407:                                cpuShares = int64(kubecm.MilliCPUToShares(cpuRequest.MilliValue()))
test/e2e_node/node_container_manager_test.go:350:               shares := int64(cm.MilliCPUToShares(allocatableCPU.MilliValue()))
test/e2e_node/node_container_manager_test.go:397:       shares := int64(cm.MilliCPUToShares(kubeReservedCPU.MilliValue()))
test/e2e_node/node_container_manager_test.go:426:       shares = int64(cm.MilliCPUToShares(systemReservedCPU.MilliValue()))
test/e2e_node/pod_resize_test.go:322:                           expectedCPUShares = int64(kubecm.MilliCPUToShares(cpuLimit.MilliValue()))
test/e2e_node/pod_resize_test.go:324:                           expectedCPUShares = int64(kubecm.MilliCPUToShares(cpuRequest.MilliValue()))
```

I see that more often than not the value is converted to `int64` so I wonder if we should do the other way around :\

**Comment by ffromani** [comment]
I can answer myself already:

The main use for the value is to be put in this struct:
```
// ResourceConfig holds information about all the supported cgroup resource parameters.
type ResourceConfig struct {
	// Memory limit (in bytes).
	Memory *int64
	// CPU shares (relative weight vs. other containers).
	CPUShares *uint64
	// CPU hardcap limit (in usecs). Allowed cpu time in a given period.
	CPUQuota *int64
	// CPU quota period.
	CPUPeriod *uint64
	// HugePageLimit map from page size (in bytes) to limit (in bytes)
	HugePageLimit map[int64]int64
	// Maximum number of pids
	PidsLimit *int64
	// Unified for cgroup v2
	Unified map[string]string
}
```

so we either do a sweeping cleanup (if possible at all, maybe CRI expects `uint64`) or we keep as-is. I think at this point in time is really better to keep it as-is.

**Comment by SergeyKanzhelev** [comment]
/retest

as @ffromani mentioned, fixing placed where it is casted to `int64` would be great. Let's see if test failures are relevant - looks like now

**Comment by hshiina** [comment]
CRI expects `int64`:
https://github.com/kubernetes/kubernetes/blob/3baaac6286d6dab50704a2c94fe92dce804d28da/staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go#L3688-L3696

On the other hand, libcontainer, which is used by CgroupManager in kubelet, expects `uint64`:
https://github.com/kubernetes/kubernetes/blob/3baaac6286d6dab50704a2c94fe92dce804d28da/vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go#L53-L67

The type casting seems inevitable.

**Comment by ffromani** [comment]
> CRI expects `int64`: https://github.com/kubernetes/kubernetes/blob/3baaac6286d6dab50704a2c94fe92dce804d28da/staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go#L3688-L3696
> 
> On the other hand, libcontainer, which is used by CgroupManager in kubelet, expects `uint64`:
> 
> https://github.com/kubernetes/kubernetes/blob/3baaac6286d6dab50704a2c94fe92dce804d28da/vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go#L53-L67
> 
> The type casting seems inevitable.

I agree (https://github.com/kubernetes/kubernetes/pull/127293#issuecomment-2343989706)

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
