### PR TITLE
Fix suggested cmd usage kubectl exec

### PR DESCRIPTION
**Pull request by ahmadnurus**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

this suggestion show when the pod have more than one containers.

in my previous PR #73664 i change the `PodName` in `SuggestedCmdUsage` to `ResourceName` and now i realized it was wrong.

it should give suggestion
`Use 'kubectl describe pod/POD -n NAMESPACE' to see all of the containers in this pod.`
instead of
`Use 'kubectl describe TYPE/NAME -n NAMESPACE' to see all of the containers in this pod.`
because not all `TYPE/NAME` will show the containers inside pod when run `kubectl describe` eg: `kubectl describe service/NAME`. 

**Which issue(s) this PR fixes**:

Fixes #NONE

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by adohe** [comment]
@prksu could u please give a more detailed example? like output before this change and after

**Comment by prksu** [comment]
Hi @adohe 

For example, I have resource like this

```bash
→ kctl get all
NAME                                   READY   STATUS    RESTARTS   AGE
pod/nginx-deployment-8c66dc895-f2rt2   2/2     Running   0          8m30s
pod/nginx-deployment-8c66dc895-gptgt   2/2     Running   0          8m30s
pod/nginx-deployment-8c66dc895-nh6hh   2/2     Running   0          8m30s


NAME                       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)           AGE
service/kubernetes         ClusterIP   10.245.0.1      <none>        443/TCP           17d
service/nginx-deployment   ClusterIP   10.245.30.254   <none>        80/TCP,9000/TCP   6m26s


NAME                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/nginx-deployment   3/3     3            3           8m33s

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/nginx-deployment-8c66dc895   3         3         3       8m33s
```

This is output in master branch (before this PR)

```bash
± |master → origin ↑327 U:1 ✗| MacBook-Air in kubernetes
→ kubectl exec deployment.apps/nginx-deployment date
Defaulting container name to nginx.
Use 'kubectl describe deployment.apps/nginx-deployment -n default' to see all of the containers in this pod.
Sun May 19 04:20:53 UTC 2019
```

And this after this change

```bash
± |fix-suggested-cmd-kubectl-exec U:1 ✗| MacBook-Air in kubernetes
→ kubectl exec deployment.apps/nginx-deployment date
Defaulting container name to nginx.
Use 'kubectl describe pod/nginx-deployment-8c66dc895-f2rt2 -n default' to see all of the containers in this pod.
Sun May 19 04:25:28 UTC 2019
```

**Comment by prksu** [comment]
/close

already fixed https://github.com/kubernetes/kubernetes/pull/77606

**Pull request closed without merging**
