### PR TITLE
should not event directly

### PR DESCRIPTION
**Pull request by tianshapjq**
**What this PR does / why we need it**:
should not event directly, using recordContainerEvent() to generate ref and deduplicate events instead.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by tianshapjq** [comment]
@dashpole done, PTAL.

**Comment by dashpole** [comment]
To make sure I understand, this PR causes Prestart Hook error events to be deduplicated by the APIServer, reducing event spam when the Prestart hook repeatedly fails?

**Comment by dashpole** [comment]
/restst
thanks!

**Comment by dashpole** [comment]
@tianshapjq I am not an approver

**Pull request merged**
