### PR TITLE
Updated failing vagrant scripts

### PR DESCRIPTION
**Pull request by jmccarty3**
Removed failing ssh commands that are no longer needed
Restarting network after modifications

Resolves issues #11819 and #11813

### CODE REVIEW

**Comment by jmccarty3** [comment]
I signed it!

**Comment by olivierlemasle** [comment]
Hi,

When using Vagrant on my Fedora 22 laptop, I hit the issue #11819.
This pull request fixes my problem, thanks.

**Comment by derekwaynecarr** [comment]
Sorry for the delay in reviewing this.  I am fine with the network change, but the change for the certs breaks the ability of the host machine to contact the server.  If the error you saw was that /srv/kubernetes did not exist on your environment, maybe we should change the script to do a mkdir of that location prior to writing the certs?  I tried this PR as is and get the following after executing:

```
$ make quick-release
$ export KUBERNETES_PROVIDER=vagrant
$ cluster/kube-up.sh
...
Wrote config for vagrant to /home/decarr/.kube/config
Each machine instance has been created/updated.
  Now waiting for the Salt provisioning process to complete on each machine.
  This can take some time based on your network, disk, and cpu speed.
  It is possible for an error to occur during Salt provision of cluster and this could loop forever.
Validating master
Validating minion-1
.......
Waiting for each minion to be registered with cloud provider
error: couldn't read version from server: Get https://10.245.1.2/api: x509: certificate signed by unknown authority
```

**Comment by derekwaynecarr** [comment]
I appreciate your time in putting this PR together, but the Vagrant setup should not be stable in the 1.0.5+ release streams as well as in the current master branch on HEAD.  If you see further errors in the future, do not hesitate to open a new PR or issue.  Thanks!

**Pull request closed without merging**
