### PR TITLE
Automated cherry pick of #22960

### PR DESCRIPTION
**Pull request by andyzheng0831**
Cherry pick of #22960 on release-1.2.

### CODE REVIEW

**Comment by andyzheng0831** [comment]
@dchen1107 @roberthbailey @zmerlynn I would like to also merge this in the 1.2 branch, so that developers can run or verify their work on 1.2 branch against Trusty base image.

cc/ @wonderfly @vishh @fabioy FYI.

**Comment by liggitt** [comment]
@eparis @bgrant0607 this isn't how we're doing cherry picks any more, right? I think the batch review/sequential-pick approach had a lot to recommend it

**Comment by roberthbailey** [comment]
Sorry, I was explaining the new process to @andyzheng0831 and he thought you still had to make individual cherry pick PRs.

**Comment by eparis** [comment]
The batch process was nice, but I don't want to do it forever, to be honest. I think we need to discuss this at the next community meeting maybe?

**Comment by roberthbailey** [comment]
@eparis - How far are we from being able to automate the batch process?

**Comment by liggitt** [comment]
Anything touching docs or affecting anything generated will likely need manual fix up in prepping the cherry pick PR :-/

**Comment by bgrant0607** [comment]
@eparis I don't expect you personally need to do what we did for 1.2. Thanks for doing it, though. I agree we need to try to automate it.

**Comment by zmerlynn** [comment]
What's wrong with allowing people to use the script until it gets more automated? The script actually handled merge conflicts, etc. You can still use the labels for whether it's allowed.

**Comment by liggitt** [comment]
Picking in master merge order minimizes conflicts, but doesn't work with individual ad hoc cherry picks

**Pull request closed without merging**
