### PR TITLE
github.com/googleapis/gnostic v0.4.1

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Updates the github.com/googleapis/gnostic dependency to v0.4.1. Note that this package made a breaking package-capitalization change, which requires reacting here and in kube-openapi.

```release-note
NONE
```

/sig api-machinery
/cc @apelisse

### CODE REVIEW

**Comment by liggitt** [comment]
cc @dims

**Comment by liggitt** [comment]
/assign @lavalamp 
for cleanup of listType on List object Items fields (special-cased/dropped in kube-openapi in https://github.com/kubernetes/kube-openapi/pull/186)

**Comment by dims** [comment]
/approve
/lgtm

thanks @liggitt !

**Comment by lavalamp** [comment]
/lgtm

for api change.

**Pull request merged**
