### PR TITLE
Update volumes.md

### PR DESCRIPTION
**Pull request by jyrip**
nfs remark

### CODE REVIEW

**Comment by jyrip** [comment]
ok to test

———
Jüri

**Comment by thockin** [comment]
@jyrip thanks for the note - I need you to sort the CLA out before we can merge, though.

**Comment by jyrip** [comment]
I belive I sgined it already.

**Comment by thockin** [comment]
LGTM

**Comment by vmarmol** [comment]
Looks like this will need a rebase btw

**Comment by wojtek-t** [comment]
@jyrip - please rebase - I'm not able to merge it as is.

**Comment by rjnagal** [comment]
removing ok-to-merge as we wait for rebase.

**Comment by jyrip** [comment]
Hi! I tried to, but seems, that I don't  have no rights to upload the result.

Jüri.

**Comment by thockin** [comment]
You don't have rights to push to your own fork?

**Comment by jyrip** [comment]
sorry, I am lost here. I understand volumes.md has moved and I don't know what to do with this pull-request.

**Comment by thockin** [comment]
I think this is a useful comment, but yeah, docs are undergoing some flux right now, so you might need to just close this PR, make the same change again and offer a new one :)

**Comment by mikedanese** [comment]
@jyrip can you rebase or open a new PR with this comment? Please reopen when you rebase.

**Pull request closed without merging**
