### PR TITLE
Automated cherry pick of #49009 and #50372

### PR DESCRIPTION
**Pull request by x13n**
Cherry pick of #49009 and #50372 on release-1.7.

#49009: Enable overriding fluentd resources in GCP
#50372: Bugfix: set resources only for fluentd-gcp container

### CODE REVIEW

**Comment by wojtek-t** [comment]
@piosz - can you please take a look?

/approve

**Comment by piosz** [comment]
FYI @mikedanese

**Comment by wojtek-t** [comment]
The original PR seems to have bugs. Removing lgtm and adding do-not-merge.

**Comment by wojtek-t** [comment]
@x13n - is this cherrypick of one PR or two different PRs?
I think the latter, so please adjust the title and first post.

**Comment by x13n** [comment]
@wojtek-t Done.

**Comment by wojtek-t** [comment]
@x13n - one more thing, I didn't catch it before Sorry.
Why there is only one commit in this PR? If this is cherrypick of two PRs there should be two separate commits (and we really want them to be separate).

**Comment by wojtek-t** [comment]
Oops - sorry. It seems I didn't refresh.

**Comment by x13n** [comment]
@wojtek-t @piosz lgtm label is gone since I included the bugfix, PTAL

**Pull request merged**
