### PR TITLE
kubelet: revamp the pod/container naming scheme

### PR DESCRIPTION
**Pull request by yujuhong**
There are two main goals for this change.
1. Fix the naming scheme in kubelet so that it accepts DNS subdomain
    name/namespaces correctly (#4920). The design is discussed in #3453.
2. Prepare for syncing the static pods back to the apiserver(#4090). This
    includes
   - Eliminate the source component in the internal full pod name (#4922). Pods
     no longer need sources as they will all be sync'd via apiserver.
   - Changing the naming scheme for the static (file-, http-, and etcd-based)
     pods such that they are distinguishable when syncing back to the apiserver.

The changes includes:
    \* `name: <pod.Name>-<hostname`
    \* `namespace: <cluster_namespace> (i.e. "default" for now).`
    \* `container_name: k8s_<contianer_name>.<hash_of_container>_<pod_name>_<namespace>_<uid>_<random>`

Note that this is not backward-compatible, meaning the kubelet won't recognize
existing running containers using the old naming scheme.

### CODE REVIEW

**Comment by dchen1107** [comment]
Why we want to revert @saad-ali's commit here? I am ok with name schema changes.

**Comment by yujuhong** [comment]
@saad-ali's change depends on distinguishing containers from different sources. Since we are removing `source` from the pod full name (hence, also from the container name), we don't and actually can't tell which source the container is from. If we keep @saad-ali's change, things will become more troublesome when we sync the static pods back to the apiserver, as it is unclear which source we should wait on (e.g. file or api).

**Comment by dchen1107** [comment]
Yes, thanks for refreshing my memory on this. I will finish reviewing this one tonight.

**Comment by vmarmol** [comment]
@yujuhong just merged #5094 which makes changes in syncPod, this PR will need a rebase.

**Comment by yujuhong** [comment]
@vmarmol, thanks for the heads-up! I will rebase after Dawn's review.

**Comment by dchen1107** [comment]
Code looks good to me overall, but one concern on appending hostname to all pod name, no matter static ones or user defined ones. Any particular reasons on this change?

**Comment by yujuhong** [comment]
We need a way to distinguish static pods from different hosts since they all have the same name (e.g. cadvisor), and now the same namespace ("default"). Hostname was suggested because it was unique.

**Comment by dchen1107** [comment]
I understood why we need this for static pod. My point earlier is that why we need this for all pods.

**Comment by yujuhong** [comment]
@dchen1107, this PR only appends the hostname to the pod name for http/file sources. For the api source, the pods already exist in the apiserver, we can't really change the name (and there is no point to...).

**Comment by bgrant0607** [comment]
I proposed hostname because it's guaranteed to be different than other hosts, deterministic (as opposed to random), and useful to humans.

**Comment by dchen1107** [comment]
@bgrant0607 I understand the reason behind. The only concern I had above is appending this to pods from apiserver. @yujuhong explaint above, actually only file and http are calling this. 

LGTM.

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/166

**Pull request merged**
