### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by amitkumarj441**
**What this PR does / why we need it**: To fix typo in annotations

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
/ok-to-test
/lgtm

Thanks!

**Review by krmayankk — APPROVED** [review]

**Comment by amitkumarj441** [comment]
@xiangpengzhao Could you please verify the remaining checks on this PR?

**Comment by amitkumarj441** [comment]
@xiangpengzhao Can we get any descision on this PR?

**Comment by xiangpengzhao** [comment]
/retest

I don't have the privilege to approve. Ping @smarterclayton @liggitt @deads2k :)

**Pull request merged**
