### PR TITLE
staging: update README to reflect recent file moves

### PR DESCRIPTION
**Pull request by nikhita**
The rules and `import-restrictions.yaml` files were moved to the publishing directory. This PR updates the README to reflect those moves.

/kind cleanup
/cc @dims @sttts 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
I guess sig-arch because this is the staging README?
/sig architecture

**Comment by nikhita** [comment]
This looks more like a legit error than a flake...

**Comment by nikhita** [comment]
/assign @liggitt 
for approval

**Comment by sttts** [comment]
/assign @lavalamp @smarterclayton 

for approval.

**Pull request merged**
