### PR TITLE
Automated cherry pick of #59607: Pass pvc namespace and annotations to Portworx Create API

### PR DESCRIPTION
**Pull request by harsh-px**
Cherry pick of #59607 on release-1.9.

#59607: Pass pvc namespace and annotations to Portworx Create API

**Release note**:
```release-note
Fixed an issue where Portworx volume driver wasn't passing namespace and annotations to the Portworx Create API.
```

### CODE REVIEW

**Comment by harsh-px** [comment]
@gnufied / @davidz627 Who can add the `cherrypick-approved` label to this PR?

**Comment by mbohlool** [comment]
This is not a test change, thus I think it deserve a release note as a patch.

**Comment by harsh-px** [comment]
@mbohlool added a release note.

**Comment by harsh-px** [comment]
@mbohlool / @gnufied / @davidz627 The cherry-pick PR #59704  for the 1.8 branch got merged just now.

Can you help get this one merged too?

**Comment by mbohlool** [comment]
the PR needs lgtm/approval.

**Comment by harsh-px** [comment]
@mbohlool the PR is now approved by @saad-ali but still has the `do-not-merge/cherry-pick-not-approved` label. Could you help? Thanks in advance !

**Comment by saad-ali** [comment]
@mbohlool has to remove that label since he is owner of the branch.

**Comment by harsh-px** [comment]
@mbohlool can you remove the label to get this merged?

**Comment by harsh-px** [comment]
@mbohlool `pull-kubernetes-e2e-kops-aws` appears to be a flaky test. It passed previously on the same change and now won't pass after multiple retries.

**Pull request merged**
