### PR TITLE
Add more logs to scheduler event handler

### PR DESCRIPTION
**Pull request by kerthcet**
#### What type of PR is this?
/kind cleanup
/sig scheduling

#### What this PR does / why we need it:

Add more logs to event handler which is benefit for debugging, considering update event is more frequent, 
so I changed the log level to 4. For add/delete events, the log level is 3.

Also did some refactors.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by sanposhiho — COMMENTED** [review]
Can we unify the log level with 3 or 4?

---

EDIT:

> considering update event is more frequent,
so I changed the log level to 4. For add/delete events, the log level is 3.

Yes, I forgot to read the PR description. But, I still prefer to make all log levels same, given the nature of those logs are the same.

**Review by sanposhiho — COMMENTED** [review]
/assign

**Comment by sanposhiho** [comment]
Yes, I know it's been un-unified from the past and I'm suggesting something new.
I don't want to define the log level based on how frequent those logs are, but based on what is important. The importance of cluster events should be all the same regardless of which event they are (add, update or delete). If you think update events are too frequent for `level:3`, then we can change all cluster events related logs to `level:4`, not only update events.

**Comment by kerthcet** [comment]
> Yes, I know it's been un-unified from the past and I'm suggesting something new. I don't want to define the log level based on how frequent those logs are, but based on what is important. The importance of cluster events should be all the same regardless of which event they are (add, update or delete). If you think update events are too frequent for `level:3`, then we can change all cluster events related logs to `level:4`, not only update events.

Based on my understanding, pod update is less import for logging. weight in @pohly for advices.

**Comment by pohly** [comment]
With my "SIG Instrumentation" head on, I don't have any strong opinion. It's up to users of those logs what they want to see at which level. Just remember that -v3 might be how the scheduler is used in production - see https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md#what-method-to-use

**Comment by kerthcet** [comment]
cc @Huang-Wei would you give any advices?

**Comment by kerthcet** [comment]
Useful for me when debugging days ago.

**Comment by sanposhiho** [comment]
Yeah, It's been useful for me several times debugging things in integ tests too.

@kubernetes/sig-scheduling-approvers 
This PR is stuck in the discussion of log level. We'd rather hear others' opinions to make it merged soon.

**Review by alculquicondor — COMMENTED** [review]
/lgtm

I agree with @kerthcet that add/remove events are generally more useful.

**Pull request merged**
