### PR TITLE
Add local storage to downwards API

### PR DESCRIPTION
**Pull request by NickrenREN**
**Release note**:
```release-note
Add local ephemeral storage to downward API 
```

/assign @NickrenREN

### CODE REVIEW

**Comment by NickrenREN** [comment]
/unassign
/assign @jingxu97 
cc @ddysher

**Comment by NickrenREN** [comment]
Hi, @jingxu97  @ddysher 
fyi:
I ran kubernetes with this PR, and created pod with yaml file:
`apiVersion: v1
kind: Pod
metadata:
  name: dapi-envars-fieldref
spec:
  containers:
    - name: test-container
      image: nginx
      imagePullPolicy: IfNotPresent
      command: [ "sh", "-c"]
      args:
      - while true; do
          echo -en '\n';
          printenv MY_NODE_NAME MY_POD_NAME SCRATCH_VOLUME;
          sleep 10;
        done;
      resources:
        requests:
          memory: "32Mi"
          cpu: "125m"
          storage.kubernetes.io/overlay: "123k"
        limits:
          memory: "64Mi"
          cpu: "250m"
          storage.kubernetes.io/overlay: "246k"
      volumeMounts:
        - mountPath: /etc
          name: scratch-volume
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SCRATCH_VOLUME
          valueFrom:
            fieldRef:
              fieldPath: volume.scratch
        - name: MY_OVERLAY_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: test-container
              resource: requests.overlay
  restartPolicy: Never
  volumes:
  - name: scratch-volume
    emptyDir: 
      sizeLimit: 10Mi`

Do not enable LocalStorageCapacityIsolation feature gate:
Validation failed:
`nickren@nickren-ubuntu14:~/test/test$ kubectl create -f downward-scratch.yaml 
The Pod "dapi-envars-fieldref" is invalid: 
* spec.volumes[0].emptyDir.sizeLimit: Forbidden: SizeLimit field disabled by feature-gate for EmptyDir volumes
* spec.containers[0].env[2].valueFrom.fieldRef: Forbidden: volume.scratch disabled by feature-gate for Downward API
* spec.containers[0].volumeMounts[0].name: Not found: "scratch-volume"
`
Enable LocalStorageCapacityIsolation : 
Pod is created successfully 
`nickren@nickren-ubuntu14:~/test/test$ kubectl create -f downward-localstorage.yaml 
pod "dapi-envars-fieldref" created
nickren@nickren-ubuntu14:~/test/test$ kubectl describe pods dapi-envars-fieldref
Name:           dapi-envars-fieldref
Namespace:      default
Node:           nickren-ubuntu14/192.168.1.102
Start Time:     Fri, 11 Aug 2017 15:50:51 +0800
Labels:         <none>
Annotations:    <none>
Status:         Running
IP:             172.17.0.2
Containers:
  test-container:
    Container ID:       docker://50e8dda24721426a70be4b23c9842232f5e49fcb9399523a32733e3f43c24c61
    Image:              nginx
    Image ID:           docker://sha256:958a7ae9e56979be256796dabd5845c704f784cd422734184999cf91f24c2547
    Port:               <none>
    Command:
      sh
      -c
    Args:
      while true; do echo -en '\n'; printenv MY_NODE_NAME MY_POD_NAME SCRATCH_VOLUME; sleep 10; done;
    State:              Running
      Started:          Fri, 11 Aug 2017 15:50:52 +0800
    Ready:              True
    Restart Count:      0
    Limits:
      cpu:                              250m
      memory:                           64Mi
      storage.kubernetes.io/overlay:    1Gi
    Requests:
      cpu:                              125m
      memory:                           32Mi
      storage.kubernetes.io/overlay:    500Mi
    Environment:
      MY_NODE_NAME:              (v1:spec.nodeName)
      MY_POD_NAME:              dapi-envars-fieldref (v1:metadata.name)
      SCRATCH_VOLUME:            (v1:volume.scratch)
      MY_OVERLAY_REQUEST:        (requests.overlay)
    Mounts:
      /etc from scratch-volume (rw)
Conditions:
  Type          Status
  Initialized   True 
  Ready         True 
  PodScheduled  True 
Volumes:
  scratch-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
QoS Class:      Burstable
Node-Selectors: <none>
Tolerations:    <none>
Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath                   Type            Reason                  Message
  ---------     --------        -----   ----                            -------------                   --------        ------                  -------
  3s            3s              1       default-scheduler                                               Normal          Scheduled               Successfully assigned dapi-envars-fieldref to nickren-ubuntu14
  3s            3s              1       kubelet, nickren-ubuntu14                                       Normal          SuccessfulMountVolume   MountVolume.SetUp succeeded for volume "scratch-volume" 
  2s            2s              1       kubelet, nickren-ubuntu14       spec.containers{test-container} Normal          Pulled                  Container image "nginx" already present on machine
  2s            2s              1       kubelet, nickren-ubuntu14       spec.containers{test-container} Normal          Created                 Created container
  2s            2s              1       kubelet, nickren-ubuntu14       spec.containers{test-container} Normal          Started                 Started container
nickren@nickren-ubuntu14:~/test/test$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
50e8dda24721        958a7ae9e569        "sh -c 'while true; d"   6 seconds ago       Up 6 seconds                            k8s_test-container_dapi-envars-fieldref_default_cbe23bbe-7e69-11e7-8231-080027b2eb62_0
6c2eab8e2c05        pause               "/pause"                 7 seconds ago       Up 6 seconds                            k8s_POD_dapi-envars-fieldref_default_cbe23bbe-7e69-11e7-8231-080027b2eb62_0`

and I entered the container, found that overlay and scratch are exposed to the container:
`nickren@nickren-ubuntu14:~/test/test$ docker exec -it 50e8dda24721 /bin/bash
bash-4.4# env                                                                                                                                                           
## **# SCRATCH_VOLUME=10Mi**
HOSTNAME=dapi-envars-fieldref
NJS_VERSION=1.13.1.0.1.10-1~stretch
NGINX_VERSION=1.13.1-1~stretch
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=20.1.0.1
MY_POD_NAME=dapi-envars-fieldref
KUBERNETES_PORT=tcp://20.1.0.1:443
PWD=/
HOME=/
**## MY_OVERLAY_REQUEST=524288000**
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP=tcp://20.1.0.1:443
MY_NODE_NAME=nickren-ubuntu14
SHLVL=1
KUBERNETES_SERVICE_PORT=443
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_SERVICE_HOST=20.1.0.1
_=/usr/bin/env
bash-4.4# `

**Comment by NickrenREN** [comment]
@jingxu97  @ddysher 
Since we decided to manage a single local storage resource(scratch), PR is modified and tested
pod yaml file:
```
apiVersion: v1
kind: Pod
metadata:
  name: dapi-envars-fieldref
spec:
  containers:
    - name: test-container
      image: nginx
      imagePullPolicy: IfNotPresent
      command: [ "sh", "-c"]
      args:
      - while true; do
          echo -en '\n';
          printenv MY_SCRATCH_REQUEST MY_SCRATCH_LIMIT;
          sleep 10;
        done;
      resources:
        requests:
          memory: "32Mi"
          cpu: "125m"
          storage.kubernetes.io/scratch: "500Mi"
        limits:
          memory: "64Mi"
          cpu: "250m"
          storage.kubernetes.io/scratch: "1Gi"
      env:
        - name: MY_SCRATCH_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: test-container
              resource: requests.scratch
        - name: MY_SCRATCH_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: test-container
              resource: limits.scratch
  restartPolicy: Never
```
Result:
```
nickren@nickren-ubuntu14:~/test/test$ kubectl create -f downward-scratch.yaml 
pod "dapi-envars-fieldref" created
nickren@nickren-ubuntu14:~/test/test$ kubeclt get pods
kubeclt: command not found
nickren@nickren-ubuntu14:~/test/test$ kubectl get pods
NAME                   READY     STATUS    RESTARTS   AGE
dapi-envars-fieldref   1/1       Running   0          10s
nickren@nickren-ubuntu14:~/test/test$ kubectl describe pods dapi-envars-fieldref
Name:           dapi-envars-fieldref
Namespace:      default
Node:           nickren-ubuntu14/192.168.1.103
Start Time:     Wed, 16 Aug 2017 14:40:33 +0800
Labels:         <none>
Annotations:    <none>
Status:         Running
IP:             172.17.0.2
Containers:
  test-container:
    Container ID:       docker://d916b229dd9dbc4068a2cbf95018f20b8eb20262f344e97a70f67dea247a3b15
    Image:              nginx
    Image ID:           docker://sha256:958a7ae9e56979be256796dabd5845c704f784cd422734184999cf91f24c2547
    Port:               <none>
    Command:
      sh
      -c
    Args:
      while true; do echo -en '\n'; printenv MY_SCRATCH_REQUEST MY_SCRATCH_LIMIT; sleep 10; done;
    State:              Running
      Started:          Wed, 16 Aug 2017 14:40:34 +0800
    Ready:              True
    Restart Count:      0
    Limits:
      cpu:                              250m
      memory:                           64Mi
      storage.kubernetes.io/scratch:    1Gi
    Requests:
      cpu:                              125m
      memory:                           32Mi
      storage.kubernetes.io/scratch:    500Mi
    Environment:
      MY_SCRATCH_REQUEST:        (requests.scratch)
      MY_SCRATCH_LIMIT:          (limits.scratch)
    Mounts:                     <none>
Conditions:
  Type          Status
  Initialized   True 
  Ready         True 
  PodScheduled  True 
Volumes:        <none>
QoS Class:      Burstable
Node-Selectors: <none>
Tolerations:    <none>
Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath                   Type            Reason          Message
  ---------     --------        -----   ----                            -------------                   --------        ------          -------
  27s           27s             1       default-scheduler                                               Normal          Scheduled       Successfully assigned dapi-envars-fieldref to nickren-ubuntu14
  27s           27s             1       kubelet, nickren-ubuntu14       spec.containers{test-container} Normal          Pulled          Container image "nginx" already present on machine
  26s           26s             1       kubelet, nickren-ubuntu14       spec.containers{test-container} Normal          Created         Created container
  26s           26s             1       kubelet, nickren-ubuntu14       spec.containers{test-container} Normal          Started         Started container
nickren@nickren-ubuntu14:~/test/test$ docker exec -it d916b229dd9db /bin/bash
root@dapi-envars-fieldref:/# env | grep SCRATCH
MY_SCRATCH_LIMIT=1073741824
MY_SCRATCH_REQUEST=524288000
```

**Comment by jingxu97** [comment]
lgtm

**Comment by NickrenREN** [comment]
Have already rebased and changed the local ephemeral storage resource name.

**Comment by jingxu97** [comment]
cc @thockin Could you please help approve this PR?

**Comment by NickrenREN** [comment]
Thanks @jingxu97  this one has been merged.  Maybe youvrefer to https://github.com/kubernetes/kubernetes/pull/50005 ?

**Pull request merged**
