### PR TITLE
Add --secure-port=0 to run `km apiserver` in Kubernetes on Mesos getting started guide

### PR DESCRIPTION
**Pull request by nak3**

### CODE REVIEW

**Comment by nak3** [comment]
Without this flag, we get following messages.
~~~
E0712 19:03:02.901695   10463 server.go:454] Unable to generate self signed cert: open /var/run/kubernetes/apiserver.crt: permission denied
E0712 19:03:02.901859   10463 server.go:464] Unable to listen for secure (open /var/run/kubernetes/apiserver.key: permission denied); will try again.
~~~

**Comment by karlkfi** [comment]
afaik, k8s on mesos has only been tested with http (ssl disabled). We're still in the process of configuring the certificates. I'm not sure that this completes the configuration.

**Comment by nak3** [comment]
This PR is not for using SSL.
kubernetes apiserver creates `apiserver.key` and `apiserver.crt` in `/var/run/kubernetes/` by default. So, regardless of using SSL, `--cert-dir` options should be specified.
Otherwise, this error messages keep outputting.

**Comment by roberthbailey** [comment]
Alternatively, you can pass `--secure-port=0` if you aren't using the ssl port. That will cause the apiserver to skip spinning it up (and then it won't try to generate certs).

**Comment by nak3** [comment]
`--secure-port=0` looks good. @karlkfi Shall I change this PR?

**Comment by jdef** [comment]
yes, please proceed with `--secure-port=0` for this PR

**Comment by jdef** [comment]
the shippable build failures look completely unrelated to this one-liner doc change.

**Pull request merged**
