### PR TITLE
cmd: fix spelling mistake

### PR DESCRIPTION
**Pull request by hwdef**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

fix spelling mistake

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by SataQiu — COMMENTED** [review]
Thanks @hwdef
/lgtm
/approve
/priority backlog

**Review by dixudx — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
