### PR TITLE
Retry when apiserver fails to listen on insecure port

### PR DESCRIPTION
**Pull request by aaronlevy**
The apiserver will already continually retry when it fails to bind to the secure port. However, with the insecure port it does not retry, and any failures cause the apiserver to exit.

This change makes it so the api-server will retry on both insecure/secure ports.

A use-case for this change is for self-hosting the api-server, particularly when you are only running a single copy in your cluster. In some bootstrap and upgrade scenarios - it's necessary to replace/pivot from an existing api-server on the same host -- where you need a new copy running before tearing down the old (which is problematic when the api-server will try to bind to an in-use port and exit).

### CODE REVIEW

**Comment by lavalamp** [comment]
Retrying forever doesn't seem quite right, but since you are doing exactly what the secure port is doing I won't make you revisit that. LGTM

**Comment by lavalamp** [comment]
Marking as release note because people might want to verify that a health check is enabled in their configurations, so that this won't cause them to launch a non functional apiserver that never crashes.

**Comment by aaronlevy** [comment]
Error seems to be unrelated to this PR.

**Comment by aaronlevy** [comment]
@k8s-bot test this please github issue: #IGNORE

**Comment by aaronlevy** [comment]
Not sure if I can do that, but figured I'd try.

**Comment by dims** [comment]
Looks good to me 👍

**Pull request merged**
