### PR TITLE
Make k8s.io/kubernetes dependency policy explicit

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Makes the project policy around use of k8s.io/kubernetes as a library explicit.

This question comes up all the time, and the various threads/discussions where this is said and repeated are not very easy to find.

```release-note
NONE
```

/area code-organization
/sig architecture
/cc @dims @smarterclayton @sttts @lavalamp @thockin

### CODE REVIEW

**Comment by liggitt** [comment]
Sure, would like an ack from the other top-level / sig-arch folks

**Comment by lavalamp** [comment]
I agree with this.

Is this current state our stopping point, though? I'd hope not. I'd like to include something that communicates:
* We understand this causes difficulty for some
* We have to balance those needs with the needs of the Kubernetes project itself to make progress
* We will seek to be more easy to depend on / semver conformant over time.

**Comment by liggitt** [comment]
> Is this current state our stopping point, though? I'd hope not.

I hope not as well.

> I'd like to include something that communicates:
> 
> * We understand this causes difficulty for some
> * We have to balance those needs with the needs of the Kubernetes project itself to make progress
> * We will seek to be more easy to depend on / semver conformant over time.

I think adding aspirational language here will muddy the point and tempt people to depend on k/k anyway hoping we start supporting it in the future.

**Comment by johnbelamaric** [comment]
LGTM

**Comment by smarterclayton** [comment]
this LGTM

**Pull request merged**
