### PR TITLE
Update CHANGELOG-1.16.md

### PR DESCRIPTION
**Pull request by k-toyoda-pi**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
CHANGELOG-1.16.md contains unnecessary lines and new line.
This PR removes that and improves content for readability.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/priority backlog
/sig release

### CODE REVIEW

**Comment by k-toyoda-pi** [comment]
@tpepper Thanks for reviewing.

/assign @dchen1107 Could you see this PR?

**Comment by liggitt** [comment]
thanks for the PR, changelogs have been relocated under the CHANGELOG folder, so if this is still valid, it will need to be re-opened against that location

/close

**Pull request closed without merging**
