### PR TITLE
Automated cherry pick of #41211

### PR DESCRIPTION
**Pull request by enisoc**
Cherry pick of #41211 on release-1.5.

#41211: cluster/gce: Add env var to enable apiserver basic audit log.

### CODE REVIEW

**Comment by enisoc** [comment]
@k8s-bot cvm gce e2e test this

Looks like https://github.com/kubernetes/kubernetes/issues/20576

**Comment by zmerlynn** [comment]
/lgtm
/approve

Assigning to @saad-ali for cherrypick

**Comment by enisoc** [comment]
@k8s-bot smoke e2e test this

**Comment by enisoc** [comment]
@k8s-bot cvm gke e2e test this

**Comment by enisoc** [comment]
@k8s-bot cvm gke e2e test this

**Pull request merged**
