### PR TITLE
clarify PreStop hook intended behavior in doc

### PR DESCRIPTION
**Pull request by mikedanese**
Fixes https://github.com/kubernetes/kubernetes/issues/55807

/kind documentation
/sig node

```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
Does a preStop happen before grace period starts or does it count against grace period?  Could be a smidge clearer, please.

**Comment by yujuhong** [comment]
> Does a preStop happen before grace period starts or does it count against grace period? Could be a smidge clearer, please.

It counts against the grace period.

Otherwise, LGTM.
Thanks for sending the PR :-)

**Comment by thockin** [comment]
This doesn't require more review than it is getting, but thanks bot :)

**Comment by mikedanese** [comment]
I added "The Pod's termination grace period countdown begins before the PreStop hooked is executed."

**Review by thockin — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
