### PR TITLE
Modified salt config to get master ip address correctly

### PR DESCRIPTION
**Pull request by ArtfulCoder**
#6042

### CODE REVIEW

**Comment by brendandburns** [comment]
LGTM.

**Comment by dchen1107** [comment]
With the change you proposed here: kubelet on the master now talks to apiserver directly with its own nodeStatus. Can you make sure the node Controller never ever make it schedulable? I believe it shouldn't, but want a confirm. 

Otherwise, LGTM

**Comment by ArtfulCoder** [comment]
@dchen1107 
There seems to have been a bug in the kubelet/default salt config file that caused it to not run properly on master. Details in #6042 

This change just fixes the bug. It does not introduce new behavior, or atleast, that is not the intent

**Comment by zmerlynn** [comment]
I think this could have been done without touching salt by just adjusting configure-vm:https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/configure-vm.sh#L364

That's the safer change.

**Comment by zmerlynn** [comment]
(We already extract and have the master IP available.)

**Comment by ArtfulCoder** [comment]
@zmerlynn The link to the file that you gave seems to be GCE specific.

**Comment by zmerlynn** [comment]
Yes, because I believe this is a divergence due to the standalone Salt config. In a normal setup, you'd go through the "else" block and get it out of the Salt mine, which doesn't exist on GCE because of `--local`. I thought I had made the cases of this a lot more Exception-throwy, but I obviously messed up.

**Comment by zmerlynn** [comment]
In fact, I think your change may break kubelet for anyone that doesn't explicitly set apiservers as a grain and instead retrieves it from the Salt mine, doesn't it?

**Comment by zmerlynn** [comment]
As an example, https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/aws/templates/salt-minion.sh and https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/azure/templates/salt-minion.sh still aren't setting `apiservers` directly in grains, which are both similar to what GCE used to do.

**Comment by ArtfulCoder** [comment]
I have created a pull request that re-adds the catch-all else block like it was before, along with the elif block that I added in this PR

 Having said that, there is a possibility that kubelet must not be functioning correctly on azure and aws today with the salt config we have. This is because the network.ipaddrs field no longer seems to exist.

#6064

**Comment by zmerlynn** [comment]
It's still in heavy use, actually. It gets setup here, through deep Salt magic: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/saltbase/pillar/mine.sls, and gets used all over the place: https://github.com/GoogleCloudPlatform/kubernetes/search?utf8=%E2%9C%93&q=ip_addrs

**Comment by zmerlynn** [comment]
But you are correct that on GCE, there isn't such a thing. That's actually why I was pushing you to do something that was extracting the API server *outside of Salt*, because I'm trying to remove as much logic from Salt as possible. The PR is fine, but to the extent that we can derive this configuration beforehand, it makes the Salt that much more braindead simple instead of having Salt possibly re-derive something different.

**Pull request merged**
