### PR TITLE
Moved token related flags to constants.

### PR DESCRIPTION
**Pull request by Zyqsempai**
**What type of PR is this?**

 /kind cleanup

**What this PR does / why we need it**:
This PR refactors kubeadm token related flags into constants

**Which issue(s) this PR fixes**:
https://github.com/kubernetes/kubeadm/issues/1333

**Special notes for your reviewer**:

/sig cluster-lifecycle
/assign @kubernetes/sig-cluster-lifecycle-pr-reviews

**Does this PR introduce a user-facing change?**:

`NONE`

### CODE REVIEW

**Comment by bart0sh** [comment]
@Zyqsempai you may want to use these constants in the validation code  in  app/apis/kubeadm/validation/validation.go

**Comment by Zyqsempai** [comment]
@bart0sh Nice idea, I will add it.

**Review by neolit123 — APPROVED** [review]
thanks for the PR @Zyqsempai

/kind cleanup
/priority backlog
/release-note-none

**Comment by fabriziopandini** [comment]
@neolit123 is was faster than me!

**Comment by bart0sh** [comment]
@Zyqsempai please [squash](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) your commits into one.

**Comment by Zyqsempai** [comment]
@bart0sh Done.

**Comment by Zyqsempai** [comment]
@bart0sh @fabriziopandini Guys, sorry, but I have no clue why the tests are failing, I already tried everything, can you help me, please.

**Comment by bart0sh** [comment]
there are 2 commits still. lgtm after squashing.

**Comment by bart0sh** [comment]
and after composing good commit message

**Comment by Zyqsempai** [comment]
@bart0sh Done!

**Review by neolit123 — APPROVED** [review]
/approve
thanks for the update.

**Comment by Zyqsempai** [comment]
@neolit123 can you merge it?

**Pull request merged**
