### PR TITLE
v1: Updating StatusDetails.ID to Name

### LINKED ISSUE #7333: REST api - wrong field 'id' instead of 'name' specified in error message
When accessing a non existing entity (example - namespace), the message specifies the requested field as 'id', but it should be 'name'.

Example (see the details section)
{
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "namespaces \"staging\" not found",
  "reason": "NotFound",
  "details": {
    "id": "staging",
    "kind": "namespaces"
  },
  "code": 404
}

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/GoogleCloudPlatform/kubernetes/issues/7333

### CODE REVIEW

**Comment by nikhiljindal** [comment]
@bgrant0607

**Comment by nikhiljindal** [comment]
@wojtek-t Can you please have a look at the conversion func changes.
I couldnt figure out which script to run to update them automatically.
I looked at https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/api_changes.md#edit-version-conversions but it says that I need to pass a file1.txt with all the convert functions, but I cant figure out how to generate that file.

**Comment by nikhiljindal** [comment]
@bgrant0607 I have only updated the name in v1 api and not the internal API.
Do we want to change the internal api as well, as we change v1, to keep internal api close to v1?
Or we will update the internal api once v1 is stable?
I think we want to go with the second option, but want to confirm.

cc @krousey and @caesarxuchao

**Comment by bgrant0607** [comment]
Yes, please update api/types.go.

**Comment by bgrant0607** [comment]
@nikhiljindal It appears you saw #8443? Does that script not work?

**Comment by bgrant0607** [comment]
v1 API change LGTM

**Comment by nikhiljindal** [comment]
@bgrant0607 : Want to clarify that you want me to update api/types.go in this PR or in a separate PR?
In general, should all v1 API changes, include changes to the internal API as well?
Changing the internal API is a bit bigger change, since that involves updating the existing code as well, while changing v1 API only includes updating v1/types.go and conversion.go.

cc @thockin since he is making v1 changes as well.

**Comment by bgrant0607** [comment]
api/types.go could be done in a separate PR.

In general, we try to keep api/types.go as similar as possible to the latest API version. 

We didn't do that in the replicas count change, however, because a pointer to an int or bool breaks DeepCopy.

**Comment by nikhiljindal** [comment]
Thanks for the quick reply.
This PR is then ready to go from my end.

@wojtek-t Can you please have a look at the conversion func changes?

**Comment by thockin** [comment]
v1 and internal should stay in sync.

**Comment by krousey** [comment]
@bgrant0607 #8188 fixed that DeepCopy issue.

**Comment by bgrant0607** [comment]
LGTM. Please do follow-up PR to change internal rep.

**Pull request merged**
