### PR TITLE
publishing-bot: Update go references to new versions

### PR DESCRIPTION
**Pull request by justaugustus**
**What type of PR is this?**
/kind cleanup
/area dependency
/sig release
/area release-eng

**What this PR does / why we need it**:
(Part of [quarterly go updates](https://github.com/kubernetes/release/issues/1134))

- publishing-bot: Update go 1.13 references to go1.13.9
- publishing-bot: Update go 1.12 references to go1.12.17

/assign @nikhita @dims @liggitt @sttts 
cc: @kubernetes/release-engineering 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
/lgtm
/approve

/hold
This is mostly a maintenance thing and doesn't need a release note. Feel free to cancel the hold after the release note has been removed.

**Comment by nikhita** [comment]
/hold cancel

that was fast :)

**Comment by justaugustus** [comment]
Done. Thanks @nikhita!
/hold cancel

**Pull request merged**
