### PR TITLE
Add dependency on ELB functionality of goamz

### PR DESCRIPTION
**Pull request by justinsb**
This is to support adding LoadBalancer functionality to AWS.  Let me know if I should instead roll this into that PR (when I submit it!)

### CODE REVIEW

**Comment by justinsb** [comment]
Hmmm... although I followed the directions here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/development.md

This didn't actually update the _workspace.  Investigating...

**Comment by justinsb** [comment]
With help from robertbailey on IRC I was able to follow the instructions correctly this time.  New version in Godeps.json and code in _workspace now :-)

**Comment by roberthbailey** [comment]
I won't have time to look at this soon. Bouncing to @a-robinson since he updated godeps recently.

**Comment by a-robinson** [comment]
LGTM

**Pull request merged**
