### PR TITLE
Refactor cluster/kubectl.sh to make the common parts reusable by other commands.

### PR DESCRIPTION
**Pull request by madhusudancs**
Please review only the last commit here. This is based on PR #35958 which will be reviewed independently.

Design Doc: PR #34484

cc @kubernetes/sig-cluster-federation @nikhiljindal 

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35959)

### CODE REVIEW

**Comment by quinton-hoole** [comment]
LGTM.  Thanks @madhusudancs

**Comment by dims** [comment]
@saad-ali @quinton-hoole @madhusudancs : is this too late for v1.5?

**Comment by saad-ali** [comment]
> @saad-ali @quinton-hoole @madhusudancs : is this too late for v1.5?

It was LGTM'd in time. If the rebase is not too large, it would be ok.

**Comment by dims** [comment]
@madhusudancs https://github.com/kubernetes/kubernetes/pull/35958 referenced here is closed. So, do we still need this PR? for 1.5?

**Comment by madhusudancs** [comment]
@dims I am withdrawing this one as well. Thanks for pointing it out. I meant to close it, but it fell through the cracks.

**Comment by dims** [comment]
@madhusudancs : no worries at all. thanks.

**Pull request closed without merging**
