### PR TITLE
Issue in kubectl command resolved

### PR DESCRIPTION
**Pull request by nitishfy**
Fix: #35577

### CODE REVIEW

**Comment by NitishKumar06** [comment]
Any way on how to remove the 'do not merge' tag?

**Comment by jihoon-seo** [comment]
Note: This PR is the first step to resolve https://github.com/kubernetes/website/issues/35577, not https://github.com/kubernetes/kubernetes/pull/35577.

@NitishKumar06 Please incorporate all the suggestions stated in https://github.com/kubernetes/website/issues/35577#issuecomment-1200526137 into this PR.

**Comment by NitishKumar06** [comment]
My Bad! @jihoon-seo I'll raise the new PR .

**Comment by NitishKumar06** [comment]
@jihoon-seo Can you guide me on how to raise the PR for this issue ? On which repo the changes should be made?

**Comment by jihoon-seo** [comment]
@NitishKumar06

> On which repo the changes should be made?

You should open a PR on this repo (`kubernetes/kubernetes`) first.
After the PR gets merged, then you (or someone) can open a PR that updates the generated docs on `kubernetes/website` repo.

> Can you guide me on how to raise the PR for this issue ?

It would be: find and replace the commands as stated in https://github.com/kubernetes/website/issues/35577#issuecomment-1200526137.

**Pull request closed without merging**
