### PR TITLE
Code Generator: Link back to examples and articles

### PR DESCRIPTION
**Pull request by markmandel**
**What this PR does / why we need it**:
Link to the sample-controller and external blog post that have the current best path to learning how to use this library.

Right now this is not as documented as it could be, and this links to current best documentation.

Context: [Friction Log](https://docs.google.com/document/d/1N1pBov7Odpg_u-kILHcswYh4VO-aMlYQdFIH64DYeek/edit#)

### CODE REVIEW

**Comment by markmandel** [comment]
CLA Signed!

**Comment by sttts** [comment]
@deads2k can you label it for the milestone?

**Comment by deads2k** [comment]
/status approved-for-milestone
/priority critical-urgent
/status in-review
/kind cleanup

This provides doc links so people can actually use the code provided.  It just happens to be in-tree.  Without it, we've shipped a thing without directions.

**Pull request merged**
