### PR TITLE
Update CHANGELOG-1.15.md

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature

/kind flake

**What this PR does / why we need it**:
- Move KubeletPodResources to the Beta section.
- Move NonPreemptingPriority to the Alpha section.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
thanks. this is a PR against master and release-1.15 still has these misaligned.

/remove-kind flake
/kind documentation
/ok-to-test
/priority important-longterm

@kubernetes/sig-release 
cc @onyiny-ang @jeefy

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
