### PR TITLE
Fetch qos class of pod from status fields

### PR DESCRIPTION
**Pull request by Karthik-K-N**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

This PR is about refactoring code to fetch Pod QOS policy from its status rather than computing each time.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

Alpha Feature Code Issues in KEP: https://github.com/kubernetes/enhancements/issues/1287

Reference to TODO in code: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L4788-L4793

### CODE REVIEW

**Comment by Karthik-K-N** [comment]
@thockin are we supposed to do something like this to use `pod.Status.QOSClass` instead of calculating all the time like `qos.GetPodQOS(pod)`. 
Would like to know your opinion to before replacing at other places as well.

**Comment by vinaykul** [comment]
@Karthik-K-N Thanks for taking the initiative. This is a slightly larger scoped fix, and I have a PR out for this https://github.com/kubernetes/kubernetes/pull/119665

But there are more issues I was tracking here: https://github.com/vinaykul/kubernetes/wiki/In-Place-Pod-Vertical-Scaling-Issues-and-Status , please pick up something that is not being worked on. And a few new issues have been identified as well. I started a new role a few months ago and I just haven't had the bandwidth to support his effort, so this page may be a bit outdated and does not capture the new issues identified.

**Comment by Karthik-K-N** [comment]
> @Karthik-K-N Thanks for taking the initiative. This is a slightly larger scoped fix, and I have a PR out for this #119665
> 
> But there are more issues I was tracking here: https://github.com/vinaykul/kubernetes/wiki/In-Place-Pod-Vertical-Scaling-Issues-and-Status , please pick up something that is not being worked on. And a few new issues have been identified as well. I started a new role a few months ago and I just haven't had the bandwidth to support his effort, so this page may be a bit outdated and does not capture the new issues identified.

@vinaykul Thanks for sharing the info, I was unaware of your PR , Meanwhile I am working on this issue: https://github.com/kubernetes/kubernetes/issues/114123

**Pull request closed without merging**
