### PR TITLE
add filedselector for Event

### PR DESCRIPTION
**Pull request by mqliang**
add filedselector for Event

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM

@k8s-bot ok to test

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@mqliang - unit tests are not passing after you change.
The failing test is:
event.TestGetAttrs
from k8s.io/kubernetes/pkg/registry/event

Can you please fix it?

**Comment by mqliang** [comment]
@wojtek-t 
```
➜  kubernetes git:(eventtype) ✗ go test -v k8s.io/kubernetes/pkg/registry/event/etcd
# k8s.io/kubernetes/pkg/api
pkg/api/types.generated.go:127: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:140: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:142: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:152: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:165: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:167: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:177: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:190: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:192: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:202: z.EncSendContainerState undefined (type codec.genHelperEncoder has no field or method EncSendContainerState)
pkg/api/types.generated.go:202: too many errors
FAIL	k8s.io/kubernetes/pkg/registry/event/etcd [build failed]
```

Sorry, I can not even run unit test(build failed). It seems due to `pkg/api/types.generated.go`files, but my PR doesn't modify it. I am not sure what's wrong.

**Comment by wojtek-t** [comment]
@mqliang - can you please try rebasing your PR?

**Comment by mqliang** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by mqliang** [comment]
@k8s-bot test this please

**Comment by dalanlan** [comment]
Just curious, does it work when common dev tries to talk to @k8s-bot to trigger jenkins?

**Comment by wojtek-t** [comment]
LGTM

**Pull request merged**
