### PR TITLE
add delete prority for rs

### LINKED ISSUE #45509: Scale down a deployment by removing specific pods
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): deployment scale down pod

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

It would be convenient to be able to scale down a deployment by N replicas by choosing which pods to remove from the deployment. 

Ideally, this would have a similar interface as for removing selected instances from a GCE managed instance group (https://cloud.google.com/sdk/gcloud/reference/compute/instance-groups/managed/delete-instances). 

Today, you can approximate this by issuing API calls in rapid succession that might sometimes result in that effect (remove the relevant label from the pod in question, scale the deployment and its underlying replicaSet down, then delete the pod), but it's hacky and relies on winning a race.

@kubernetes/sig-apps-feature-requests

### PR DESCRIPTION
**Pull request by lovejoy**
**What type of PR is this?**

 /kind feature

**What this PR does / why we need it**:

user want to control which pod will be deleted
**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/45509

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Pod has the controller.alpha.kubernetes.io/delete-priority annotation with a high value will be delete first by rs controller
```

### CODE REVIEW

**Comment by lovejoy** [comment]
User may use this feature to define the pod's update order.
Todo: pause point support , when scale to the pod with a specific annotation，the deployment auto pause

**Comment by mpickell** [comment]
Has anything additional happened with this PR?  This type of custom downscale metric is exactly what I am looking for regarding #45509

**Comment by benediktbrandt** [comment]
/remove-lifecycle rotten this feature is definitely needed

**Comment by benediktbrandt** [comment]
I think solving https://github.com/kubernetes/kubernetes/issues/45509 is important

**Pull request closed without merging**
