### PR TITLE
[KEP-1933] Update config for go-flow-levee analysis

### PR DESCRIPTION
**Pull request by PurelyApplied**
* Remove \b boundary for sinks; Unicode backspace \b != regexp boundary \b.
* Specify those source type fields that have not yet been tagged.
* Add exclusions for current false-positive set.

-----

/sig security
/sig testing
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Running the static analysis introduced by KEP-1933 currently does not produce meaningful results due to the configuration using `\b` for a boundary regexp.  When parsed by YAML, however, this parses as the Unicode `\b` backspace rather than the regexp `\b` boundary.  

This PR updates configuration to remove this boundary check.  It also updates the configuration to include those fields which have been identified to contain credentials that should not be logged, but for which field tagging have not get been merged.

With this updated configuration, analysis would fail due to (broadly) three instances of a credential reaching logs.  One is a false positive that can be corrected when the tool is updated to a newer version.  The others are minor issues that will be corrected in other PRs.

~~This PR will be in `Draft` until related PRs are in place and properly cross-referenced.~~

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
- KEP: https://github.com/kubernetes/enhancements/issues/1933
- Usage and documentation: [Draft PR](https://github.com/kubernetes/community/pull/5349)

### CODE REVIEW

**Comment by PurelyApplied** [comment]
/assign spiffxp

At the last Sig-Security meeting, it was mentioned that many of the "new sig paperwork" PRs are on their way.  I specifically brought up getting an entry in `OWNER_ALIASES` populated, and it's on its way.  I'll get a PR to update this configuration's OWNERS right after.  Thanks again for being interim-owner in the mean time!

**Comment by PurelyApplied** [comment]
Related PRs:

Bump tool version: #96999 
Introduce documentation for this test, placeholder for other `verify-` tests: [k/enhancements #5349](https://github.com/kubernetes/community/pull/5349)

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by spiffxp** [comment]
> Pending — Not mergeable. Must be in milestone v1.20.

I think tide's status context is out of date, this is no longer required.  The details link shows tide is happy.

**Comment by PurelyApplied** [comment]
Failed to schedule test.
/retest

**Comment by PurelyApplied** [comment]
Flakiness in `Test_UncertainVolumeMountState` tracked in #94567.
/retest

**Comment by PurelyApplied** [comment]
/retest
Investigating flakes for existing Issues, will update.

**Pull request merged**
