### PR TITLE
fix typo in docker_container.go

### PR DESCRIPTION
**Pull request by carlory**
Signed-off-by: Carlory <fanbaofa@gmail.com>

**What this PR does / why we need it**:
fix typo in docker_container.go

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
NONE

**Special notes for your reviewer**:
NONE

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by feiskyer** [comment]
@k8s-bot ok to test

**Comment by feiskyer** [comment]
LGTM. Thanks for the fix.

/lgtm

**Comment by feiskyer** [comment]
@k8s-bot bazel test this

**Comment by ncdc** [comment]
@k8s-bot unit test this

**Pull request merged**
