### PR TITLE
Allows kubectl create -f to filter by selector.

### PR DESCRIPTION
**Pull request by MrHohn**
From #32544.

The underlying `seletor` infrastructrue was implemented by #32599. The test is basically copy-paste of the corresponding test for `kubectl apply -f -l`.

```release-note
kubectl create now accepts the label selector flag for filtering objects to create
```

### CODE REVIEW

**Comment by MrHohn** [comment]
@k8s-bot gce etcd3 e2e test this, issue: #38163

**Comment by MrHohn** [comment]
@kubernetes/sig-cli-misc @ymqytw

**Comment by MrHohn** [comment]
This is blocking #40108.

**Comment by pwittrock** [comment]
Why is add-on manager using create instead of apply?

**Comment by MrHohn** [comment]
We plan to use both now. `kubectl create` would be used for the `ensure exist` class addons, which we only ensure they exist while allowing user to modify them.

**Comment by ymqytw** [comment]
@pwittrock 
I have heard the use case from @MrHohn. The reason is that they don't want to take any actions when an resource exists.
`create` can return an error and do nothing. But `apply` will update the resource (may overwrite users' changes).

**Comment by MrHohn** [comment]
From Tim:
> should we just patch kubectl to have a --ignore-already-exists flag to create, similar to --ignore-not-found on delete?

I'm also thinking about adding this flag, does it make sense to you? @pwittrock @ymqytw

**Comment by grodrigues3** [comment]
@k8s-bot test this

Tests are more than 96 hours old. Re-running tests.

**Comment by grodrigues3** [comment]
I think there's a problem with the alias unpacking.  Will fix tomorrow.  You can add the approved label manually if needed.

**Comment by pwittrock** [comment]
@k8s-bot ok to test

**Comment by MrHohn** [comment]
Thanks for taking care of this :)

**Pull request merged**
