### PR TITLE
add yangjunmyfm192085 to metrics-server OWNERS file

### PR DESCRIPTION
**Pull request by yangjunmyfm192085**
#### What this PR does / why we need it:
In the kubernetes/sigs community, I've been following @serathius to learn and contribute, and have been greatly helped by @dgrisonnet. Now I want to apply to join the owner of addons/metrics-server.

- continue to make more contributions to the kubernetes community.

- When I was reviewing the pr, sometimes the changes in /kubernetes/kubernetes/tree/master/cluster/addons/metrics-server would be missed. For example, `https://github.com/kubernetes-sigs/metrics-server/pull/921` mentioned . 

- metrics-server will release v0.6.0 soon, I want more participation contribution

/cc  @ehashman @serathius @dgrisonnet
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
"NONE"
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by serathius** [comment]
Thanks for your contributions to metrics server, My main concern is that `cluster/addons` directory is deprecated and we should rather think about how to remove metrics server addon.

**Review by yangjunmyfm192085 — COMMENTED** [review]
/remove-lifecycle stale

**Comment by dgrisonnet** [comment]
@yangjunmyfm192085 I think we should close this PR and focus on that point brought by Serathius:

> My main concern is that cluster/addons directory is deprecated and we should rather think about how to remove metrics server addon.

**Comment by yangjunmyfm192085** [comment]
Ok, I will close this pr

**Pull request closed without merging**
