### PR TITLE
Deleting old sample JSON; moving those in use; updating references

### PR DESCRIPTION
**Pull request by MikeJeffrey**

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM, but you need to run gofmt on examples/examples_test.go before we can merge this. Sorry.

**Comment by MikeJeffrey** [comment]
Thanks! Ran gofmt -s -w. PTAL - many thanks for your help in getting this sorted :)

**Comment by bgrant0607** [comment]
LGTM

**Comment by satnam6502** [comment]
Has this broken our build?
```
--- FAIL: TestExampleObjectSchemas (0.04s)
	examples_test.go:174: Expected no error, Got lstat ../docs/getting-started-guides: no such file or directory
	examples_test.go:177: Expected 1 examples, Got 0
```

**Comment by bgrant0607** [comment]
Travis is green.

**Comment by satnam6502** [comment]
OK, I am past this error and onto the next one.

**Pull request merged**
