### PR TITLE
Remove duplicate symbols

### PR DESCRIPTION
**Pull request by xichengliudui**
**What this PR does / why we need it**:
Remove duplicate symbols

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by wgliang** [comment]
You can combine all the changes into one PR(#69730).

**Comment by liggitt** [comment]
these are intentional tests to exercise how selector parsing handles empty segments split by comma

/close

**Pull request closed without merging**
