### PR TITLE
Remove hack/e2e-from-release.sh.

### PR DESCRIPTION
**Pull request by spxtr**
Does anybody use this? It's not called from anywhere else in the codebase and it pretty much hasn't been touched since @zmerlynn created it a year ago. It's drifted a bit, but not too much.

It does do something that the other local test runners don't: it runs the tests from the tars without access to the rest of the source tree.

@kubernetes/sig-testing

### CODE REVIEW

**Comment by zmerlynn** [comment]
That was actually its goal. At some level, we're going to need a "Jenkins-proxy", and we actually still do. This isn't it, and hasn't been for a long time, but there's no equivalent in a long setup for "deploy from tar".

**Comment by spxtr** [comment]
I think @ixdy is working on canonizing the correct way to run e2e tests.

In the meantime, do you think this script should stay, @zmerlynn?

**Comment by zmerlynn** [comment]
No.

**Comment by ixdy** [comment]
Yeah, this script was useful before we had PR Jenkins, since it was possible to submit test changes which worked fine locally (if you depended on something in the kubernetes repo) but failed on Jenkins. Since we use `KUBE_RUN_FROM_OUTPUT=y` on PR Jenkins, I think it simulates post-submit Jenkins, as well as basically everything this script does.

**Pull request merged**
