### PR TITLE
[Minor] Correct Typos in `getBeginingAndEndIndices` func Name

### PR DESCRIPTION
**Pull request by akankshakumari393**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR corrects the typo in `getBeginingAndEndIndices` function Name. 
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by akankshakumari393** [comment]
Hey @bowei @freehan, If you guys get some time, Could you Please take a look at the PR.

**Comment by jsafrane** [comment]
I'm using this PR as quinea pig for disruptive tests. Please ignore any errors there.
/test pull-kubernetes-e2e-gce-storage-disruptive

**Comment by dims** [comment]
/skip

@jsafrane looks like you may be done with your disruptive testing

/approve
/lgtm

**Pull request merged**
