### PR TITLE
fieldmanager: Strip managedfields BEFORE we update the timestamp

### PR DESCRIPTION
**Pull request by apelisse**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:
Discovered by #100024

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by kwiesmueller** [comment]
You might also want to do it here: https://github.com/kubernetes/kubernetes/blob/4740173f3378ef9d0dc59b0aa9299444a97d0818/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/fieldmanager_test.go#L114

**Comment by jpbetz** [comment]
/lgtm

Makes perfect sense to me that to detect a noop change, any fields stripping needs to happen first

**Comment by apelisse** [comment]
> Actually that one only updates the time on update. Still thinks this is best.

I don't know why I said that, it absolutely works for apply too!

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/managedfieldsupdater.go#L80

**Comment by apelisse** [comment]
the test was already doing the right thing (building the managers in the right order). I've added a "creationTimestamp" to show that this works.

**Pull request merged**
