### PR TITLE
Add support for Azure Disk to csi-translation-lib

### LINKED ISSUE #76684: Add support for azure disk to csi-translation-lib
**What would you like to be added**:
Azure is not listed as "migratable" in staging/src/k8s.io/csi-translation-lib/translate.go.

could refer to https://github.com/kubernetes/kubernetes/pull/72938
**Why is this needed**:

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Add support for Azure Disk to csi-translation-lib

in support of csi-migration proposal here: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/csi-migration.md

Will help with migration of in-tree Azure Disk plugin to Azure Disk CSI.

Also see kubernetes/enhancements#625

**Which issue(s) this PR fixes**:

Fixes #76684

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Add support for Azure Disk plugin to csi-translation-lib
```

/kind bug
/assign @feiskyer 
/priority important-soon
/sig azure
/sig storage

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
LGTM in general. Do we need a feature gate for it?

**Comment by andyzhangx** [comment]
> LGTM in general. Do we need a feature gate for it?

This is a general feature gate for this: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/csi-migration.md#implementation-schedule

**Comment by jsafrane** [comment]
I am not migration expert, however I think there are couple of things missing:

* You need to add azure into list of translated plugins [here](https://github.com/kubernetes/kubernetes/blob/6aea7fcd8349872ef102c4317a392b5662dd6492/staging/src/k8s.io/csi-translation-lib/translate.go#L31)

* Corresponding volume plugin should have `IsMigratedToCSI` filled, e.g. as in [AWS](https://github.com/kubernetes/kubernetes/blob/6f5cf1a6e0c86a9b1a91651d77d8b5473b0ea6cf/pkg/volume/awsebs/aws_ebs.go#L89). You need to create a new feature gate for each migrated plugin, so they can be migrated separately.

**Comment by jsafrane** [comment]
lgtm the volume plugin part

/assign @ddebroy @davidz627 
for the migration

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Comment by jsafrane** [comment]
Saad is out of office,

@thockin, @liggitt, @childsb can you please approve a little feature? CSI migration requires a separate feature for each volume plugin, so we can migrate each at its own speed.

**Comment by liggitt** [comment]
/approve
feature gate

**Pull request merged**
