### PR TITLE
Automated cherry pick of #15796

### PR DESCRIPTION
**Pull request by caesarxuchao**
Cherry pick of #15796 on release-1.1.

Part of a series cherry-pick. (https://github.com/kubernetes/kubernetes/pull/16324#issuecomment-151305008)

cc @lavalamp

### CODE REVIEW

**Comment by nikhiljindal** [comment]
LGTM, apart from the spaces issue

**Comment by caesarxuchao** [comment]
@nikhiljindal Fixed the space issue, PTAL. Thanks!

**Comment by nikhiljindal** [comment]
LGTM, thanks!

**Comment by caesarxuchao** [comment]
@k8s-bot test this

**Pull request merged**
