### PR TITLE
Add test case  in metadata_test.go

### LINKED ISSUE #55567: Add test case for priorities/metadata_test.go
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
kind bug

**What happened**:

Add some test case

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

Add test case in metadata_test.go

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #55567 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wackxu** [comment]
@k82cn @k82cn Please take a look at this PR, it needs your approve, thanks.

**Comment by k82cn** [comment]
/lgtm

Thanks for the contribution :).

**Pull request merged**
