### PR TITLE
Pass Logs=true in the streaming options to ContainerAttach api

### LINKED ISSUE #52224: 'kubectl attach' does not return output from the pod container
/kind bug
**What happened**:
`kubectl attach <pod-name>` was not showing the output "Started, serving at 8080"
But  `kubectl logs <pod-name>` shows "Started, serving at 8080"

**What you expected to happen**:
`kubectl attach <pod-name>`  to show the output "Started, serving at 8080"

**How to reproduce it (as minimally and precisely as possible)**:
1. kubectl create -f https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/pods/pod_with_two_containers.json
2. Wait until pod running
3. kubectl attach doublecontainers

**Anything else we need to know?**:
It works on 1.6 release

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.0.502+736846baf91170-dirty", GitCommit:"736846baf9117051b6a75cc0dbb5807a628bb9e6", GitTreeState:"dirty", BuildDate:"2017-09-09T01:28:27Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.0.502+736846baf91170-dirty", GitCommit:"736846baf9117051b6a75cc0dbb5807a628bb9e6", GitTreeState:"dirty", BuildDate:"2017-09-09T01:28:27Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from /etc/os-release):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"

- Kernel (e.g. `uname -a`):
3.10.0-514.21.1.el7.x86_64

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
**What this PR does / why we need it**:
Gets `kubectl attach` working.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #52224

**Special notes for your reviewer**:

**Release note**:

```release-note
```
/cc @sjenning

### CODE REVIEW

**Comment by feiskyer** [comment]
/cc @Random-Liu because of `TODO(random-liu): Do we really use the *Logs* field here?`

This will change the behavior of `kubectl attach` since `Logs ` is not set in all previous releases. @yujuhong @derekwaynecarr what do you think of this?

**Comment by sjenning** [comment]
related
https://github.com/kubernetes/kubernetes/issues/24070

**Comment by ncdc** [comment]
We need to resolve the discussion in https://github.com/kubernetes/kubernetes/issues/24070 first.

**Pull request closed without merging**
