### PR TITLE
Update Cluster Autoscaler version to 1.3.0-beta.0

### PR DESCRIPTION
**Pull request by aleksandra-malinowska**
Update Cluster Autoscaler version to 1.3.0-beta.0

```release-note
NONE
```

Full release notes will be attached with stable version (1.3.0)

### CODE REVIEW

**Comment by DirectXMan12** [comment]
@aleksandra-malinowska anything that upgrades a component definitely needs a release note.  At the very least, "the Cluster Autoscaler has been upgraded to 1.3.0.  Please see [insert link here] for full release notes".

**Comment by aleksandra-malinowska** [comment]
@nickchase @DirectXMan12 I'll keep this in mind, thanks. Since we already have 1.3.0-beta.1, closing this in favor of #64977. Does that one look good?

**Comment by nickchase** [comment]
@aleksandra-malinowska It's minimal, but acceptable.  I'll be nagging you for more detail. :)

**Pull request closed without merging**
