### PR TITLE
Bump cadvisor to fix interface stats bugs & improve performance

### LINKED ISSUE #17725: Kubelet Stat fs failed
version: 1.1.1

when start the kubelet on node, with docker storage option devicemapper, nearly all CPU is used by kubelet

```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                           
17478 root      20   0 1098260 113520  13120 S 40.8  2.8 203:48.04 kubelet  
```

check the log, can see

```
I1124 20:40:45.626406   29547 server.go:944] POST /stats/container/: (2.376501097s) 0 [[Go 1.1 package http] 33.1.3.72:46808]
E1124 20:40:47.563834   29547 fs.go:211] Stat fs failed. Error: EOF
I1124 20:40:47.718322   29547 server.go:944] POST /stats/container/: (4.397950894s) 0 [[Go 1.1 package http] 33.1.1.15:50056]
E1124 20:40:49.638118   29547 fs.go:211] Stat fs failed. Error: EOF
```

put more debug log in fs.go, and get this

```
E1124 20:25:30.253016   14151 fs.go:211] Stat fs failed. Error: no such file or directory
E1124 20:25:30.383152   14151 fs.go:372] Stat fs failed. poolName: docker-253:1-270437-pool
E1124 20:25:30.391324   14151 fs.go:382] Stat fs failed. dmStatus: 0 209715200 thin-pool 707 1215/524288 30282/1638400 - rw discard_passdown
E1124 20:25:30.391472   14151 fs.go:211] Stat fs failed. Error: EOF
```

compare to the code:

```
	_, err = fmt.Fscanf(bytes.NewReader(dmStatus),
		"%d %d %s %d %d/%d %d/%d %s %s %s %s",
		&bkt, &bkt, &bkts, &bkt, &bkt, &bkt, &used, &total, &bkts, &bkts, &bkts, &bkts)
```

that there is one more %s at the end. 

So, is it a bug ? is anyone else have seen it? the os of node is `"Ubuntu 14.04 LTS"`

### PR DESCRIPTION
**Pull request by jimmidyson**
Includes necessary godep upgrades for docker & systemd packages as well as
migrating from docker/libcontainer to opencontainers/runc/libcontainer.

Fixes #17725

/cc @dchen1107 @vishh

### CODE REVIEW

**Comment by jimmidyson** [comment]
Looks like a failure to create the clustre for e2e - can someone rekick please?

**Comment by jimmidyson** [comment]
@quinton-hoole Could you retest this please now that e2e cluster is back up again?

**Comment by smarterclayton** [comment]
ok to test

**Comment by jimmidyson** [comment]
Ready for revie if you have time, @vishh @dchen1107

**Comment by quinton-hoole** [comment]
Reassigned to @vishh

**Comment by jimmidyson** [comment]
@piosz Including your latest cadvisor changes.

**Comment by jimmidyson** [comment]
Please can someone review this pr so we can merge it? I don't know why this is taking so long with no feedback...

**Comment by piosz** [comment]
cc @jszczepkowski

**Comment by jszczepkowski** [comment]
Can we bump cadvisor to a version where https://github.com/google/cadvisor/pull/1012 is merged? We need it for custom metrics.

**Comment by vishh** [comment]
Wonder why the tests are failing.

**Comment by jimmidyson** [comment]
Travis failure is a problem with godep rebuild timing out.

`Jenkins unit/integration` could be a problem with runc migration. Tests pass locally for me with `./hack/test-cmd.sh` so not sure what's different though? Do you know what distro the integration tests are running on so I can test like for like?

**Comment by jimmidyson** [comment]
@jszczepkowski Bumped to 0.20.1 to include the prometheus custom metrics filtering.

**Comment by jimmidyson** [comment]
Travis: "No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself."

e2e flake: "[Fail] Daemon set [It] should run and stop complex daemon"

Still not sure what's going on with `Jenkins unit/integration`. If someone can point me how to reproduce so I can invesitgate that would be great. Works fine locally of course...

**Comment by timstclair** [comment]
I'd like to get https://github.com/google/cadvisor/commit/33216870d8f7bc079de0ea4870d9e1b2dd2a2b28 in, do you want to update this PR, or should I send another?

**Comment by jimmidyson** [comment]
Might as well do it in this one. I'll update this PR tomorrow.

**Comment by timstclair** [comment]
Thanks!

**Comment by jimmidyson** [comment]
Phew fixing godep issues with Docker refactoring their packages was fun...

@vishh @dchen1107 @timstclair Would like to get this merged once green if possible?

**Comment by jimmidyson** [comment]
Please can someone retest this? Looks like a Jenkins flake:

`FAIL	k8s.io/kubernetes/pkg/storage/etcd`

**Comment by vishh** [comment]
@k8s-bot: unit this please

**Comment by vishh** [comment]
@k8s-bot: unit test this

**Comment by yujuhong** [comment]
@k8s-bot unit test this

**Comment by jimmidyson** [comment]
Different flake...

**Comment by vishh** [comment]
@k8s-bot: unit test this

**Comment by jimmidyson** [comment]
It's not retesting...

**Comment by jimmidyson** [comment]
I see integration tests failing for most open PRs so unrelated to this PR. e2e is good so how do you want to proceed? I really want to get this in.

**Comment by jimmidyson** [comment]
Tests run fine locally... All help appreciated. Off on vacation from tomorrow so want to squeeze this in today if possible.

**Comment by yujuhong** [comment]
@k8s-bot unit test this

**Comment by jimmidyson** [comment]
Thanks @yujuhong!

**Comment by luxas** [comment]
Thanks @jimmidyson! This also fixed #17060.

**Pull request merged**
