### PR TITLE
Add .bazelversion file

### PR DESCRIPTION
**Pull request by praseodym**
**What type of PR is this?**

/kind feature
/sig testing

**What this PR does / why we need it**:

This will allow developers to use [Bazelisk](https://github.com/bazelbuild/bazelisk) to build Kubernetes with the same version of Bazel that is used in test-infra.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
defer to @kubernetes/sig-testing-pr-reviews for review, can approve once that is complete

**Comment by Katharine** [comment]
I approve of the concept, but last I checked you actually couldn't build k/k correctly with 0.28.1 and needed some older version. I haven't been keeping up, though - maybe this was finally fixed?

**Comment by praseodym** [comment]
[test-infra uses 0.28.1](https://github.com/kubernetes/test-infra/blob/master/.bazelversion) and building k/k using that version worked for me 🙂

**Comment by BenTheElder** [comment]
You can build but you can't push a release. This should be something older.
CI is 0.23.X

**Comment by praseodym** [comment]
Where can I find out what exact version is in use for CI?

**Comment by Katharine** [comment]
https://github.com/kubernetes/test-infra/blob/master/images/kubekins-e2e/variants.yaml - it's currently 0.23.2.

**Comment by praseodym** [comment]
Thanks! I've updated the `.bazelversion` file to use 0.23.2 instead.

**Comment by BenTheElder** [comment]
/lgtm
We'll want to try to keep this updated. I think this will be pretty helpful FYI @cblecker @fejta 
It might also be worth adding / updating some docs to point users to bazelisk ...

**Comment by cblecker** [comment]
/hold
Let's put this file in `build/root/`, and then have a symlink from the repo root.

**Comment by BenTheElder** [comment]
ACK @praseodym mind making that change?

**Comment by fejta** [comment]
Hopefully bazelisk is smart enough to figure that out :)

**Comment by praseodym** [comment]
> Let's put this file in `build/root/`, and then have a symlink from the repo root.

Done! 

> Hopefully bazelisk is smart enough to figure that out :)

Looks like it is :slightly_smiling_face:

**Comment by cblecker** [comment]
/lgtm
/approve
/priority backlog
/hold cancel

Over to you, @liggitt!

**Pull request merged**
