### PR TITLE
bump konnectivity-client@v0.0.30

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <andrewsy@google.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Bumps sigs.k8s.io/apiserver-network-proxy/konnectivity-client to v0.0.30, which includes two fixes for goroutine leaks in kube-apiserver: 
* https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/337
* https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/339  

See https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/276#issuecomment-1055025833 for more details on the root cause.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
bump sigs.k8s.io/apiserver-network-proxy/konnectivity-client@v0.0.30 to fix a goroutine leak in kube-apiserver when using egress selctor with the gRPC mode.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by andrewsykim — COMMENTED** [review]
/assign @cheftako @liggitt

**Comment by liggitt** [comment]
commented on https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/337, but is there a test demonstrating this resolves the issue and ensuring it won't regress in the future?

**Comment by andrewsykim** [comment]
There is a regression test added for the first goroutine leak here https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/336. 

The second one is tricky to test because it's hard to trigger the race condition in a test.

**Comment by andrewsykim** [comment]
> but is there a test demonstrating this resolves the issue

To be clear, there are no unit tests demonstrating this fix, but it has been manually validated by myself and @rata here, see https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/276#issuecomment-1055384666

**Comment by rata** [comment]
@liggitt That has been solved now, and the PR is updated to 0.0.29 (so ti contains the latest PR). Can we hold cancel and merge now?

**Comment by liggitt** [comment]
> the PR is updated to 0.0.29

https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/339 isn't in 0.0.29... a v0.0.30 cut and an update here is needed

**Comment by andrewsykim** [comment]
I'll update this PR and the other cherry-pick PRs once @cheftako cuts v0.0.30

**Comment by cheftako** [comment]
Can we also change https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/addons/konnectivity-agent/konnectivity-agent-ds.yaml#L30 and https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/manifests/konnectivity-server.yaml#L23 to ensure we are consistent on the v0.0.30?

**Comment by andrewsykim** [comment]
> Can we also change https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/addons/konnectivity-agent/konnectivity-agent-ds.yaml#L30 and https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/manifests/konnectivity-server.yaml#L23 to ensure we are consistent on the v0.0.30?

Good catch, updated

**Pull request merged**
