### PR TITLE
Implement gzip compression in cp command

### PR DESCRIPTION
**Pull request by rsevilla87**
Signed-off-by: Raul Sevilla <rsevilla@redhat.com>

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Enables gzip compression for `kubectl cp` from/to the destination/source pod.
Some test results:

```shell
$ dd if=/dev/zero of=file bs=50M count=1 
1+0 records in
1+0 records out
52428800 bytes (52 MB, 50 MiB) copied, 0.0600967 s, 872 MB/s
```

- No gzip
```
# copy to pod
$ time kubectl cp file mypod:/tmp/file

real    0m24.829s
user    0m0.502s
sys     0m0.230s

# copy from pod
$ time kubectl cp file mypod:/tmp/file file

real    0m17.630s
user    0m0.494s
sys     0m0.271s
```

- gzipped
```
# copy to pod
$ time ./kubectl cp file mypod:/tmp/file file

real    0m6.049s
user    0m0.376s
sys     0m0.051s

# copy from pod
$ time ./kubectl cp mypod:/tmp/file file
tar: Removing leading `/' from member names

real    0m4.564s
user    0m0.189s
sys     0m0.105s
```

### CODE REVIEW

**Comment by rsevilla87** [comment]
Copy of https://github.com/kubernetes/kubernetes/pull/99812
I had a mistake in pushing latest changes

**Comment by rsevilla87** [comment]
PTAL @BenTheElder

**Comment by BenTheElder** [comment]
> gzip compression needs gzip command to be available. We're also expecting tar to be in the pod image. So I don't see a big problem in also requiring gzip. I see more benefits than issues in this case.

regressing on required commands available seems problematic.

**Comment by BenTheElder** [comment]
Is there a reason we couldn't compress this in kubelet?

**Comment by rsevilla87** [comment]
> > gzip compression needs gzip command to be available. We're also expecting tar to be in the pod image. So I don't see a big problem in also requiring gzip. I see more benefits than issues in this case.
> 
> Regressing on required commands available seems problematic.
> 
> EDIT: I'm pretty sure everyone on this PR currently already knows this, but clarifying that these command(s) are required _in the user's image_ in order to `kubectl cp`. So we'd be breaking `kubectl cp` against any container/image that had `tar` but not `gzip`.

gzip is also available in busybox. I'd say that's difficult to find images including tar and no gzip.


> Is there a reason we couldn't compress this in kubelet?

As cp relays on SPDY to execute commands, not sure now if `moby/spdystream` is able to handle compression.

**Comment by BenTheElder** [comment]
> gzip is also available in busybox. I'd say that's difficult to find images including tar and no gzip.

I'm fairly certain people have installed tar specifically in order to make kubectl cp work with their containers.

If nothing else this PR should follow the full PR template and include a relevant release note about this breaking change.

> As cp relays on SPDY to execute commands, not sure now if moby/spdystream is able to handle compression.

We can just move the gzipping into that read/write stream handling in kubelet (or CRI/dockershim) instead of inside the image?

**Comment by tallclair** [comment]
IMO we should not be adding features to `kubectl cp` at this point. You can already achieve this today by adding the `-z` argument to the tar commands here: https://gist.github.com/tallclair/9217e2694b5fdf27b55d6bd1fda01b53

**Comment by dougsland** [comment]
> IMO we should not be adding features to `kubectl cp` at this point. You can already achieve this today by adding the `-z`
> argument to the tar commands here: https://gist.github.com/tallclair/9217e2694b5fdf27b55d6bd1fda01b53

Based on @tallclair @liggitt @BenTheElder I am assuming this PR won't fly. You can always implement your own plugin as workaround via krew.
https://github.com/kubernetes-sigs/krew
https://github.com/kubernetes-sigs/krew-index

However, I also agree with @BenTheElder that might be a good idea to implement via kubelet/CRI.

**Comment by dougsland** [comment]
Closing this PR for now.
/close

**Comment by BenTheElder** [comment]
I mean, I would drop my name from the list, I don't think that decision is mine. 😅 
However https://github.com/kubernetes/kubernetes/issues/58512 is my suggestion as an end user that wishes for the time to fix `kubectl cp` ...

There's also some references there to past issues with this, IIRC security was looking to drop this entirely because it's a security hazard (particularly depending on untrusted `tar` binary in the container, and hence @tallclair's comment).

There is also some discussion of multiple options for implementing an alternative:
- Ephemeral containers (which are going to be default on soon https://github.com/kubernetes/kubernetes/issues/98808), and could let us use a trusted image / not depend on the contents of user images
- Putting an API in CRI (arguably even better IMHO, since we can trust the CRI implementation / host dependencies even more easily and not incur starting another container / more freely tweak the underlying implementation)

**Pull request closed without merging**
