### PR TITLE
util/wait: Add ManagedExponentialBackoff()

### PR DESCRIPTION
**Pull request by jtagcat**
#### What type of PR is this?:
/kind feature

/kind regression

#### What this PR does / why we need it:
`ManagedExponentialBackoff()` is like `ExponentialBackoff()`, but does not return `ErrTimeout`, and continues indefinitely with maximum duration until success is reached.

I use this in collectors, in steps that may error, but shall be retried until success. Using `Backoff.Steps = 99999` or similar isn't reasonable, as the duration gets too large. Looping `ExponentialBackoff()` is inefficient.

Also bugfix in behaviour of `Backoff.Step()`, where it stepped one extra step before reaching the limit.

#### Does this PR introduce a user-facing change?
For more information on release notes see: https://git.k8s.io/community/contributors/guide/release-notes.md
-->
```release-note
apimachinery: Add wait.ManagedExponentialBackoff()
```

### CODE REVIEW

**Comment by liggitt** [comment]
can you clarify why this is considered a regression? did the behavior change in a previous release in a breaking way? if so, do you know when and where the breaking change was introduced?

note that tomorrow is code freeze for 1.26, so this change will be queued up for review after that for possible inclusion in 1.27

**Comment by smarterclayton** [comment]
/hold

I am in the process of cleaning up the `wait` package in #107826 and this would conflict.

**Pull request closed without merging**
