### PR TITLE
Set unified field cgroups v2

### PR DESCRIPTION
**Pull request by bertinatto**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

Fixes test failures in `TestCalculateLinuxResources`, `TestGenerateLinuxContainerResources` and `TestApplySandboxResources` when on unified mode.

Meant to be a folllow up to https://github.com/kubernetes/kubernetes/pull/117793.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bertinatto** [comment]
/assign @tzneal 
/assign @mrunalp 

PTAL if this makes sense. I found this on OpenShift.

**Comment by tzneal** [comment]
Is this test not run in CI?  I verified that it is failing and your fix works for me.

/lgtm

**Comment by bertinatto** [comment]
> Is this test not run in CI? I verified that it is failing and your fix works for me.
> 
> /lgtm

I'm not sure, mayve CI uses Ubuntu which doesn't have cgroupsv2 unified mode? 

/retest

**Comment by bertinatto** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/118764

**Pull request closed without merging**
