### PR TITLE
make client-go authoritative for pkg/client/restclient

### PR DESCRIPTION
**Pull request by deads2k**
Moves client/restclient to client-go and a util/certs, util/testing as transitives.

### CODE REVIEW

**Comment by deads2k** [comment]
Had to move the client auth plugins (logically part of the client anyway) to prevent double registration.

**Comment by deads2k** [comment]
@k8s-bot test this

**Comment by sttts** [comment]
Have moved util/certs to apimachinery in my WIP PR. Both is fine, we have to decide (compare @gmarek's kube-dev discussion).

**Comment by deads2k** [comment]
Just in case pulls get reverted and I have to re-rebase, my previous head was 2e75b0d

**Comment by sttts** [comment]
Am ok with moving pkg/cert to client-go. We can reconsider this if necessary. lgtm.

**Comment by deads2k** [comment]
gke is broken in head.

**Comment by dshulyak** [comment]
@deads2k @sttts I have a patch for pkg/client/restclient, where i should propose my changes now? Into staging or to client-go repo directly?

**Comment by sttts** [comment]
@dshulyak the github repo is only an export of the staging dir in k8s.io/kubernetes. This PR here is about whether k8s.io/kubernetes/pkg/client/restclient or k8s.io/kubernetes/staging/src/k8s.io/client-go/client/restclient is authorative. The former dir is empty now. The later is what should be modified from now on.

**Pull request merged**
