### PR TITLE
Automated cherry pick of #48812

### PR DESCRIPTION
**Pull request by crassirostris**
Cherry pick of #48812 on release-1.7.

#48812: Change fluentd-gcp monitoring to use metrics exposed by SD

```release-note
Fluentd-gcp DaemonSet exposes different set of metrics
```

### CODE REVIEW

**Comment by crassirostris** [comment]
As discussed earlier, this PR is safe to merge, because we have new e2e tests coming that will check the core features of the logging agents: https://github.com/kubernetes/kubernetes/pull/49422

I run those tests at least manually to verify the correctness of this PR, they all passed

@wojtek-t @fgrzadkowski

**Comment by wojtek-t** [comment]
Cherrypick approved.

**Pull request merged**
