### PR TITLE
Change go file mode from 755 to 644

### PR DESCRIPTION
**Pull request by july2993**
#### What type of PR is this?
cleanup

#### What this PR does / why we need it:
use appropriate file mode for go code files
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by july2993** [comment]
> Welcome @july2993!
> 
> It looks like this is your first PR to [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes) 🎉. Please refer to our [pull request process documentation](https://git.k8s.io/community/contributors/guide/pull-requests.md) to help your PR have a smooth ride to approval.
> 
> You will be prompted by a bot to use commands during the review process. Do not be afraid to follow the prompts! It is okay to experiment. [Here is the bot commands documentation](https://go.k8s.io/bot-commands).
> 
> You can also check if kubernetes/kubernetes has [its own contribution guidelines](https://github.com/kubernetes/kubernetes/tree/master/CONTRIBUTING.md).
> 
> You may want to refer to our [testing guide](https://git.k8s.io/community/contributors/devel/sig-testing/testing.md) if you run into trouble with your tests not passing.
> 
> If you are having difficulty getting your pull request seen, please follow the [recommended escalation practices](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#why-is-my-pull-request-not-getting-reviewed). Also, for tips and tricks in the contribution process you may want to read the [Kubernetes contributor cheat sheet](https://git.k8s.io/community/contributors/guide/contributor-cheatsheet/README.md). We want to make sure your contribution gets all the attention it needs!
> 
> Thank you, and welcome to Kubernetes. 😃

reply for re-check

**Comment by july2993** [comment]
re check CLA

**Comment by adtac** [comment]
Could you please fix `./framework/plugins/noderesources/requested_to_capacity_ratio.go` too? That one seems to be the wrong permission too.

**Comment by july2993** [comment]
> Could you please fix `./framework/plugins/noderesources/requested_to_capacity_ratio.go` too? That one seems to be the wrong permission too.

fix in https://github.com/kubernetes/kubernetes/pull/100444/commits/cac7f447c13bfdbcf8fb0e3a7db03accacc6046e
I have run `find . -perm 755 | grep "\.go$"` to check there are no more any files

**Comment by adtac** [comment]
thanks! you can squash if you like
/lgtm

**Comment by Huang-Wei** [comment]
LGTM. @july2993 would you mind squashing the commits (into one)?

**Comment by july2993** [comment]
> LGTM. @july2993 would you mind squashing the commits (into one)?

done

**Comment by Huang-Wei** [comment]
@july2993 it will be merged into 1.22 once the code freeze for 1.21 gets lifted.

**Pull request merged**
