### PR TITLE
Move recreate_node.go to e2e/node

### PR DESCRIPTION
**Pull request by oomichi**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

e2e/framework is a place to keep common functions for e2e tests, and it is not a place to keep e2e tests themself. recreate_node.go is e2e test for node.
This moves recreate_node.go to e2e/node.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
@oomichi I took a look at the `recreate_node.go`, and it seems to be checking the logic of "recreating nodes" and "checking their bootIDs", etc. Would you mind moving it to `test/e2e/node` ? as IMO that's more proper than scheduling.

**Comment by oomichi** [comment]
@Huang-Wei Thanks for your comment.
I got it, I will change this PR for your comment.

TBH, I didn't have strong opinion about where the file exists. I just checked the label of [Feature:Recreate] and moved the file to path which contains the same label e2e tests.
test/e2e/node also seems good option from POV of testing purpose.

/hold

**Review by alejandrox1 — COMMENTED** [review]
/lgtm

**Comment by spiffxp** [comment]
FWIW, this was introduced Apr 2019 via https://github.com/kubernetes/kubernetes/pull/76156.  I couldn't find anything in kubernetes/test-infra's history that indicated a job was ever added to run `[Feature:Recreate]`.  Given that it relies on kube-up.sh I'm more inclined to suggest deleting this as dead code vs. trying to add a job that runs this.

**Pull request merged**
