### PR TITLE
Implement ReplicaSet controller.

### PR DESCRIPTION
**Pull request by madhusudancs**

### CODE REVIEW

**Comment by madhusudancs** [comment]
@davidopp Only the last commit needs review. This PR is based on other PRs which are in review separately, unfortunately there is no easy way to do diff against PRs.

**Comment by madhusudancs** [comment]
@k8s-bot test this please.

**Comment by madhusudancs** [comment]
@k8s-bot unit test this please.

**Comment by davidopp** [comment]
> @davidopp Only the last commit needs review. This PR is based on other PRs which are in review separately, unfortunately there is no easy way to do diff against PRs.

Is that commit just the corresponding files from ReplicationController, but with s/ReplicationController/ReplicaSet/? If so, I will just LGTM it. If there were any meaningful changes, please let me know and I will review those. Thanks!

**Comment by madhusudancs** [comment]
> Is that commit just the corresponding files from ReplicationController, but with s/ReplicationController/ReplicaSet/? If so, I will just LGTM it. If there were any meaningful changes, please let me know and I will review those. Thanks!

Pretty much only that and changes related to moving selector from map[string]string to LabelSelector. I don't think it requires a thorough review, in-depth review.

**Comment by davidopp** [comment]
There are few places where you didn't replace ReplicationController->ReplicaSet (I think they are all in one test file--only a dozen or so instances). Probably best to change those.

**Comment by davidopp** [comment]
Please put at the beginning of each file a comment saying something like "If you make changes to this file, you should also make the corresponding change in ReplicationController." Conversely, please put at the beginning of each of the corresponding ReplicationController files a comment saying something like "If you make changes to this file, you should also make the corresponding change in ReplicaSet."

**Comment by madhusudancs** [comment]
> There are few places where you didn't replace ReplicationController->ReplicaSet (I think they are all in one test file--only a dozen or so instances). Probably best to change those.

Done.

> Please put at the beginning of each file a comment saying something like "If you make changes to this file, you should also make the corresponding change in ReplicationController." Conversely, please put at the beginning of each of the corresponding ReplicationController files a comment saying something like "If you make changes to this file, you should also make the corresponding change in ReplicaSet."

Done.

PTAL.

**Comment by davidopp** [comment]
LGTM

**Comment by davidopp** [comment]
@k8s-bot test this please

**Comment by davidopp** [comment]
I added but then removed LGTM label since I assume you ultimately want this PR to only consist of the last commit, so it's useless for me to add LGTM label until you've done that. Is that correct? 

BTW I'm not sure why, but the "commits" view didn't show the changes you made in response to my last comment (at least not in the last commit there), while the "files changed" view did.

**Comment by madhusudancs** [comment]
> I added but then removed LGTM label since I assume you ultimately want this PR to only consist of the last commit, so it's useless for me to add LGTM label until you've done that. Is that correct?

Yeah, that's correct.

> BTW I'm not sure why, but the "commits" view didn't show the changes you made in response to my last comment (at least not in the last commit there), while the "files changed" view did.

Oh, that's strange.

**Comment by madhusudancs** [comment]
Previous PR #19746 (ReplicaSet Client) was merged. Adding LGTM.

**Comment by madhusudancs** [comment]
@k8s-oncall 

This was LGTM'ed a week ago as well. Please merge this.

**Comment by madhusudancs** [comment]
@k8s-bot test this please.

(Retrying the e2e tests. Failing for unrelated reasons.)

**Pull request merged**
