### PR TITLE
Add utility to check for terminating pods

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Add a utility for detecting terminating pods.
#### Which issue(s) this PR fixes:
This is a utility I would need for terminating pods KEP.  

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
adding utilities without consumers use to end with orphan or duplicate code, is there any special motivation for this ?

**Comment by kannon92** [comment]
> adding utilities without consumers use to end with orphan or duplicate code, is there any special motivation for this ?

yea, I'm working on https://github.com/kubernetes/enhancements/pull/3940.

I am working on a PR where I want to add a count for the number of terminating pods for deployments and jobs.  I notice that I had to duplicate this function in two different places so I figured I'd start with smaller PRs.  

We can hold this until the KEP is complete.  I just find it helpful to have an idea of the implementation before I continue with a KEP.

**Comment by kannon92** [comment]
Since I am going to focus on Jobs for this release I may not need this yet.

**Pull request closed without merging**
