### PR TITLE
Shallow clone for kubernetes-build and kubernetes-test-go jobs.

### PR DESCRIPTION
**Pull request by spxtr**
This should save us about 160M per clone.

### CODE REVIEW

**Comment by ixdy** [comment]
Assigning to @fejta since he's the current test-infra oncall.

**Comment by fejta** [comment]
Thanks, looks good! Let's lgtm this tomorrow morning.

**Comment by fejta** [comment]
How is this related to https://github.com/kubernetes/kubernetes/issues/24538?

**Comment by spxtr** [comment]
It cuts the amount that gets downloaded from 300M to 140M. Should help.

**Comment by fejta** [comment]
Does it close that PR?

**Pull request merged**
