### PR TITLE
Fix comment typo in kube-apiserver and cachesize

### PR DESCRIPTION
**Pull request by noah8713**
**What this PR does / why we need it**:
Fix comment typo in files cmd/kube-apiserver/app/server.go and pkg/registry/cachesize/cachesize.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Not a major issue, just a minor improvement.
**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test
/lgtm

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this
@k8s-bot pull-kubernetes-unit test this

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by noah8713** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by noah8713** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by noah8713** [comment]
please approve @@smarterclayton @cblecker . All the test cases passed.

**Pull request merged**
