### PR TITLE
Automated cherry pick of #52849

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #52849 on release-1.8.

#52849: PodSecurityPolicy: Do not mutate nil privileged field

This is a larger change than usual for a cherry-pick, but changes are isolated to the PSP component, the cherry-pick was clean, and this fixes severe usability issues with systems with more than one PSP. Would like to get feedback from community users making use of PSP and let the master PR soak as we consider this.

```release-note
PodSecurityPolicy: when multiple policies allow a submitted pod, priority is given to ones which do not require any fields in the pod spec to be defaulted. If the pod must be defaulted, the first policy (ordered by name) that allows the pod is used.
```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @jhorwit2

**Review by pweil- — APPROVED** [review]

**Comment by ericchiang** [comment]
From a user perspective, I'd like to see this considered for a 1.8 patch release.

CoreOS wants to start experimenting with Pod Security Policy with customers and providing feedback, but there were serious enough concerns about the behavior of PSP in 1.8 (https://github.com/kubernetes/kubernetes/pull/52367#issuecomment-331135292) that we're not sure we can adequately evaluate the feature. 

cc @joshrosso

**Comment by jpbetz** [comment]
Let's hold this off for 1.8.2 given the size and the current hold on the CP. If there is strong buy-in from sig-auth we can consider for 1.8.3.

**Comment by jhorwit2** [comment]
I validated this PR against my existing test cluster and ran into no issues while upgrading or testing the functionality. 

Scenarios tested:
* v1.8.1 -> v1.8.2 upgrade with existing restricted & privileged PSP's. 
* Validated that an admin user who has access to the `restricted` (non-mutating) and `privileged` (non-mutating) PSP's had `privileged` chosen since it was first when sorted by name.
* Validated that an admin user who has access to the `restricted`(mutating) and `privileged` (non-mutating) PSP's had `privileged` chosen since it was non-mutating. 
* Renamed `privileged` to `z` to ensure that the prior test didn't pick `privileged` due to sorting. `z` was chosen because it was non-mutating. 
* Validated normal users with access only to `restricted` were not able to deploy `privileged` PSP pods regardless if it required mutating or not.

**Comment by jpbetz** [comment]
Merging this in for 1.8.3.

**Pull request merged**
