### PR TITLE
Automated cherry pick of #12029

### PR DESCRIPTION
**Pull request by justinsb**
Cherry pick of #12029 on release-1.0.

### CODE REVIEW

**Comment by justinsb** [comment]
@iterion can you reply "OK" or something?

**Comment by iterion** [comment]
OK

**Comment by justinsb** [comment]
@k8s-bot test this please

(has to be a flake, right?  It doesn't touch GCE)

**Comment by zmerlynn** [comment]
Don't worry about CLAs for cherry-picks (see [cherry picks](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md)).

**Pull request merged**
