### PR TITLE
Added support for register-with-taints setting #93608

### LINKED ISSUE #93608: Support for --register-with-taints in kubemark hollow-kubelet args
**What would you like to be added**:
The kubemark hollow-kubelet should expose setting --register-with-taints through args for the test.

**Why is this needed**:
1. It would be beneficial to have the nodes come up with taints to avoid scheduling of regular pods on the nodes. The specific workloads can then be scheduled on the hollow-nodes by adding tolerations. This would help for environments where the actual nodes and the kubemark nodes run on the same cluster.
2. Sometimes the hollow nodes are scheduled on other hollow-nodes making them unusable.

### PR DESCRIPTION
**Pull request by kshitijcode**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #93608 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by jaybatra26** [comment]
This just introduces a flag by the name of `register-with-taints`, right?

**Comment by kshitijcode** [comment]
@wojtek-t : Does anything else needs to be done for it to be merged?

**Pull request merged**
