### PR TITLE
Update github.com/coreos/go-etcd and github.com/ugorji/go/codec dependencies

### PR DESCRIPTION
**Pull request by wojtek-t**
This is a prerequisite for using ugorji/go/codec instead of standard encoding/json parser.

### CODE REVIEW

**Comment by wojtek-t** [comment]
@lavalamp - can you please take a look or delegate (this is the last step before the main PR that will start using ugorji)

**Comment by ncdc** [comment]
@kubernetes/rh-cluster-infra @timothysc @smarterclayton

**Comment by lavalamp** [comment]
as long as the tests stay green, I think this is fine.

Do you plan to cherrypick this, though?

**Comment by lavalamp** [comment]
LGTM

**Comment by wojtek-t** [comment]
@lavalamp - I didn't plan to cherrypick it (this makes sense only with the PR tak will switch to using thew ugorji json parser and I still think that it's kind of risky change to cherrypick it just few days before release (although I ran a bunch of different tests and it seems to work fine)

**Comment by lavalamp** [comment]
Sounds risky to me, too. Thanks.

**Pull request merged**
