### PR TITLE
Fix hack/update-mocks.sh generating duplicate headers

### PR DESCRIPTION
**Pull request by linxiulei**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

See duplicate headers in https://github.com/kubernetes/kubernetes/blob/979863d15cdf3fb12caffbc7b1c8ff3ac0b4878c/pkg/kubelet/container/testing/runtime_mock.go for example

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by skitt** [comment]
Oops, thanks for spotting this! I originally intended to drop the generation code from the script, since Mockery is set up to include headers itself. I’ve done that with #126540.

**Comment by BenTheElder** [comment]
Thanks! I agree that we should take the approach in https://github.com/kubernetes/kubernetes/pull/126540

**Pull request closed without merging**
