### PR TITLE
Migrated proxier_health.go , proxier.go to structured logging

### PR DESCRIPTION
**Pull request by shivanshuraj1333**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Fixed incorrectly migrated logs
Migrated some missing logs to structured logging

#### Which issue(s) this PR fixes:

Ref: https://github.com/kubernetes/kubernetes/issues/104872

#### Special notes for your reviewer:
In this PR, I've cleaned up some improperly migrated logs, going forward we need to figure out a way to make every migration follow the guide, https://github.com/kubernetes/kubernetes/pull/105718#issuecomment-945182761

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by yangjunmyfm192085 — COMMENTED** [review]
/retest

**Comment by aojea** [comment]
/approve
Thanks

**Pull request merged**
