### PR TITLE
kubelet/cm/containermap: Improving test coverage

### PR DESCRIPTION
**Pull request by tmilox**
Signed-off-by: TommyStarK <thomasmilox@gmail.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

If applied this commit will increase the unit tests code coverage of `pkg/kubelet/cm/containermap`.

- Initial unit tests code coverage

Screenshot 2023-01-02 at 14 43 03

- After changes

Screenshot 2023-01-02 at 14 42 16

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by TommyStarK** [comment]
@derekwaynecarr I know you are super busy, another small coverage improvement

**Comment by dims** [comment]
/approve
/lgtm

comfortable landing this test-ONLY change that improves coverage by using `cm.Visit`

**Pull request merged**
