### PR TITLE
Sort apidiscovery versions in aggregated discovery test

### PR DESCRIPTION
**Pull request by Jefftree**
/kind flake

#### What this PR does / why we need it:

Sort versions returned in aggregated discovery test. Golang map iteration order is not stable and should not be treated as such.

```
jying@jefftree ❯❯❯ go test ./... -run=TestLegacyFallbackNoCache -count=100
ok      k8s.io/kube-aggregator/pkg/apiserver    10.342s
```
#### Which issue(s) this PR fixes:

Fixes flake discovered in https://storage.googleapis.com/k8s-triage/index.html?text=TestLegacyFallbackNoCache#1bf2be60ce0078971afe

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/cc @pacoxu @deads2k

### CODE REVIEW

**Comment by pacoxu** [comment]
I just tried to fix it like 
https://github.com/kubernetes/kubernetes/compare/master...pacoxu:fix-order?expand=1

This looks better. 😄

**Comment by Jefftree** [comment]
@pacoxu actually that PR should suffice. Thanks!

/close

**Pull request closed without merging**
