### PR TITLE
Adding dims to test/images OWNERS file

### PR DESCRIPTION
**Pull request by dims**
We need to speed up review/approval for image updates. I've been involved in this for a while, so adding myself to OWNERS.

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/hold

just in case @listx disagrees :)

**Comment by mkumatag** [comment]
> /hold
> 
> just in case @listx disagrees :)

Thanks for adding hold, I was about to add that.. 😁

**Comment by justaugustus** [comment]
+1 from a reviewer :)
/lgtm

**Comment by dims** [comment]
thanks for the +1 @justaugustus, also checked slack activity for listx, haven't seen him active since Nov 3. So let's get this in.

/hold cancel

**Comment by justaugustus** [comment]
> thanks for the +1 @justaugustus, also checked slack activity for listx, haven't seen him active since Nov 3. So let's get this in.
> 
> /hold cancel

SGTM!

**Pull request merged**
