### PR TITLE
docs/devel/controllers.md: fix broken link and other minor improvements

### PR DESCRIPTION
**Pull request by php-coder**
PTAL @deads2k @smarterclayton

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37630)

### CODE REVIEW

**Comment by php-coder** [comment]
@k8s-ci-robot I'm signed!

**Comment by deads2k** [comment]
> @k8s-ci-robot I'm signed!

I think you need to do the linux foundation thing.

**Comment by php-coder** [comment]
@k8s-bot I'm signed!

@deads2k Thanks, I did it and now I'm trying to re-run this check.

**Comment by php-coder** [comment]
I think that bot is wrong. My fix is for developers documentation that is absent on https://github.com/kubernetes/kubernetes.github.io

**Comment by kargakis** [comment]
@ixdy any idea why the bot won't let this merge?

**Comment by kargakis** [comment]
This seems to have happened in all PRs that touch the docs directory in this repo.

**Comment by dims** [comment]
@kargakis : please see https://groups.google.com/d/msg/kubernetes-dev/XyGKDdqfjAE/IhpCYcvWCgAJ

**Comment by php-coder** [comment]
@dims Thank you for the link! Bot's message is misleading :-(

**Comment by php-coder** [comment]
Re-submitted as https://github.com/kubernetes/community/pull/121

**Pull request closed without merging**
