### PR TITLE
Add argument about log size(--audit-log-maxsize) AuditPolicyConfigura…

### PR DESCRIPTION
**Pull request by thdrnsdk**
Provide audit log size for MasterConfiguration.
other options will be update soon.

**What this PR does / why we need it**:
Install use kubeadm, MasterConfiguration. 
As with maxage, you must be able to set the maxsize option at install time. The Defualt value is given as 100M, which will change to another value if desired.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Add argument about log size(--audit-log-maxsize) 
The maximum size in megabytes of the audit log file before it gets rotated.
```

### CODE REVIEW

**Comment by thdrnsdk** [comment]
anybody?
/cc @xinxiaogang 
/cc @detiber 
/cc @chuckha

**Comment by neolit123** [comment]
@thdrnsdk 

please add `kubeadm: ` in front of the release note.
> `kubeadm: Add argument about log size(--audit-log-maxsize). The maximum size in megabytes of the audit log file before it gets rotated.

note that this PR might get rejected (adding new command line flags), or might have to be delayed before some other pending PRs are merged and then rebased.

thanks!

**Comment by thdrnsdk** [comment]
@neolit123 
ok!
Can you let me know other pending PRs?

**Comment by neolit123** [comment]
@thdrnsdk 
https://github.com/kubernetes/kubernetes/pull/66219
https://github.com/kubernetes/kubernetes/pull/66968

**Pull request closed without merging**
