### PR TITLE
Fixed typo in CentOS doc: api-servers arg

### PR DESCRIPTION
**Pull request by liebowitz**

### CODE REVIEW

**Comment by liebowitz** [comment]
I signed it!

**Comment by brendandburns** [comment]
LGTM.

Not sure why CLA bot was confused, but I manually validated the CLA signing.

**Comment by brendandburns** [comment]
Ah, @liebowitz I think the trouble is that your git client isn't quite setup right, somehow that commit is attributed to a different user.  (different email address maybe?)

**Comment by brendandburns** [comment]
Manually merging, since small docs fix and CLA signer is confused so we'll never auto-submit this.

**Comment by liebowitz** [comment]
Thanks!

**Pull request merged**
