### PR TITLE
Automated cherry pick of #23550 upstream release 1.2

### PR DESCRIPTION
**Pull request by luxas**
Ref: #23550

@fgrzadkowski @vishh @bgrant0607 @thockin @david-mcmahon @huggsboson

### CODE REVIEW

**Comment by luxas** [comment]
@zmerlynn Can you kindly LGTM this? 
The main PR already has the `cherrypick-approved` label, so I think you should just remove `do-not-merge` and `release-note-label-needed` and add `lgtm`, `release-note` and maybe `ok-to-merge`
Thanks

**Comment by luxas** [comment]
@k8s-bot test this please github issue: #IGNORE

**Comment by luxas** [comment]
Ah, the bots don't really like us. 
@eparis Should the `cherrypick-candidate` label be applied on this PR also?

**Comment by david-mcmahon** [comment]
@eparis we need to update the procedure to follow the [current cherry pick process](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md#propose-a-cherry-pick).  I know this changed right after we 'finalized' it and apologies for that, but if we can change it so that it follows the new procedure of not requiring any accounting on the cherrypick/branch side, that would be good.  Also, can you point to [[cherry-pick info]](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md#propose-a-cherry-pick) - rather than the proposal - in the bot message?

**Comment by luxas** [comment]
Please add one of `release-note|release-note-none`. The main PR has the `release-note` label

**Comment by zmerlynn** [comment]
@luxas: I thought you only needed it on the main PR, but the bot gets angry if it's not on both. We need to fix that, there's too many twiddles here.

**Comment by luxas** [comment]
I also thought it was only required on the master PR, but it doesn't seem so

**Comment by luxas** [comment]
I think the bot will be angry if not the `cherrypick-approved` label is here also. Not sure if the `v1.2` milestone is required.

**Comment by david-mcmahon** [comment]
Yes, this has been a very dynamic process and [not all of the changes are in sync](https://github.com/kubernetes/kubernetes/pull/23783#issuecomment-206534671) as we get things in place.  There's a [pending PR](https://github.com/kubernetes/kubernetes/pull/23939) as well to get all of the docs in sync on this.  Comments welcome

**Comment by eparis** [comment]
Had the PR been opened using the scripts it would have automatically gotten the 'cherrypick-approved' label when the 'parent' PR has it.

**Pull request merged**
