### PR TITLE
Added missing documentation to NodeInstanceGroup.

### PR DESCRIPTION
**Pull request by wasylkowski**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot ok to test

**Comment by wojtek-t** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by dchen1107** [comment]
Submit queue redeployed. Now only allowing PRs with 1.7 milestone. Applying the milestone because this pr was lgtmed and approved before the deadline.

**Comment by wasylkowski** [comment]
Ref: #46847

**Pull request merged**
