### PR TITLE
remove obsolete TODO item of NodeAddresses

### PR DESCRIPTION
**Pull request by jiahuif**
remove obsolete TODO item of NodeAddresses that indicates it is only used for getting addresses of calling instance, which is no longer true for most cloud providers (including all known cloud providers in kubernetes GitHub org).

Original PR: #8899

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by cheftako** [comment]
I agree the TODO is no longer valid. I'm a little worried about code which assumes it still is. I know the gce cloud provider assumes this to be true. Do we know if any other cloud providers assume this to be true?

**Comment by jiahuif** [comment]
Short answer: None of other cloud providers assumed such properties.

cloud providers that checks if requesting calling node (and use metadata if so): aws, vsphere, azure
cloud providers that call API anyway: openstack, alibaba-cloud

**Review by andrewsykim — COMMENTED** [review]
/approve
/lgtm

thanks @jiahuif

**Pull request merged**
