### PR TITLE
missing `create` for kubectl

### PR DESCRIPTION
**Pull request by mikeplavsky**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by thockin** [comment]
/lgtm
/approve no-issue
@k8s-bot ok to test

**Comment by thockin** [comment]
You need to clear the CLA

**Comment by mikeplavsky** [comment]
signed CLA

**Comment by kargakis** [comment]
The examples have moved in https://github.com/kubernetes/examples

@ahmetb @sebgoa will this change propagate to the other repo somehow?

**Comment by ahmetb** [comment]
@kargakis I don't think so. We should stop accepting contributions to there. New patches must be submitted to `kubernetes/examples`. @sebgoa will you be following up on #46362 soon?

**Comment by thockin** [comment]
So close this?

**Comment by kargakis** [comment]
@mikeplavsky please submit this PR in kubernetes/example

**Comment by mikeplavsky** [comment]
understood 
https://github.com/kubernetes/examples/pull/9

**Comment by sebgoa** [comment]
@ahmetb yes trying to get to it today

**Pull request closed without merging**
