### PR TITLE
dependencies: zapr v1.3.0, zap v1.26.0

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The new zapr adds support for slog. The new zap has various improvements. It no longer depends on go.uber.org/atomic which enables dropping it from the Kubernetes dependencies. github.com/pkg/errors is also no longer needed.

#### Which issue(s) this PR fixes:

Related-to: https://github.com/kubernetes/kubernetes/pull/120696

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
/assign @dims 

Dependency update for logging.

**Comment by dims** [comment]
definitely better than before..

```
-Direct Dependencies: 212 
-Transitive Dependencies: 341 
-Total Dependencies: 393 
+Direct Dependencies: 211 
+Transitive Dependencies: 340 
+Total Dependencies: 392 
 Max Depth Of Dependencies: 19 
 All dependencies:
 
@@ -150,7 +150,6 @@
 github.com/armon/go-socks5
 github.com/asaskevich/govalidator
 github.com/aws/aws-sdk-go
-github.com/benbjohnson/clock
 github.com/beorn7/perks
 github.com/blang/semver/v4
 github.com/cenkalti/backoff/v4
```

/approve
/lgtm

**Pull request merged**
