### PR TITLE
Adjust GPU test to work with latest nvidia daemonset on AWS/ec2

### PR DESCRIPTION
**Pull request by dims**
Getting GPU test to work on AWS/EC2 as there are some flakiness on the existing CI job.

- `areGPUsAvailableOnAllSchedulableNodes` : ignore control plane node, it needed not have a GPU (we are not going to schedule on that node)
- `makeCudaAdditionDevicePluginTestPod` : usually builds a pod with 2 containers (uses 1 GPU each). As in EC2/AWS, Nodes with 2 Nvidia GPU(s) are costly, let's have a environment variable `TEST_MAX_GPU_COUNT` to use just 1 container (with 1 GPU) as the test workload
- reuse `"NVIDIA_DRIVER_INSTALLER_DAEMONSET` and point it to the [latest daemonset URL](https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.14.5/nvidia-device-plugin.yml) needs some accomodation on the namespace logic to make it work.

See first clean run here:
https://testgrid.k8s.io/presubmits-ec2#pull-kubernetes-e2e-ec2-device-plugin-gpu&width=20

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/hold

we should release hold if `pull-kubernetes-e2e-gce-device-plugin-gpu` goes green.

**Comment by pacoxu** [comment]
/test pull-kubernetes-e2e-gce-device-plugin-gpu

after https://github.com/kubernetes/test-infra/pull/32188 was merged

**Comment by dims** [comment]
let's make sure both the `ec2` and `gce` jobs for `device-plugin-gpu` go green!

**Comment by dims** [comment]
pull-kubernetes-e2e-ec2-device-plugin-gpu is ✅

**Comment by pacoxu** [comment]
> pull-kubernetes-e2e-ec2-device-plugin-gpu is ✅

This may fixed the ec2 test. 
If so, can we use https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ec2-device-plugin-gpu in https://testgrid.k8s.io/sig-release-master-blocking board instead of the ci-kubernetes-e2e-**gce**-device-plugin-gpu

My run with https://github.com/kubernetes/kubernetes/pull/123788 failed in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/123788/pull-kubernetes-e2e-ec2-device-plugin-gpu/1765609958725914624.

**Comment by dims** [comment]
/skip

( skipping the `pull-kubernetes-e2e-gce-device-plugin-gpu` job too flaky )

**Pull request merged**
