### PR TITLE
Optimise CleanupLeftovers function

### PR DESCRIPTION
**Pull request by ping035627**
Suggest optimizing the "CleanupLeftovers" function in proxier.go of userspace and iptables.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32065)

### CODE REVIEW

**Comment by dims** [comment]
@k8s-ci-robot ok to test

**Comment by ping035627** [comment]
@dims  It seem not to trigger a test. Can you help to review it? thanks.

**Comment by dims** [comment]
@ping035627 - am quite sure i am a " kubernetes member " so don't know what else i need to do here. I sent an email to kubernetes-dev@ mailing list for help.

Thanks,
Dims

**Comment by jlowdermilk** [comment]
@k8s-bot ok to test

**Comment by MHBauer** [comment]
Is there any chance this can blow up while we're collecting the errors such that we lose the accumulated errors? I would argue that it's better to log exactly at the place of origin vs collecting and logging at the end.

Are all of the log entries going to appear to come from 328 rather than the original positions? That would seem to me to be a loss of debug information. 

I have no knowledge of how often someone is in here debugging using these entries.

Can we make some of the formatting strings into constants and reuse them?

**Comment by ping035627** [comment]
@MHBauer I think it will be more clear to collect the errors and print centrally.  Formatting strings can only replace the limited part.

**Comment by ping035627** [comment]
@jlowdermilk need lgtm, can you help to review it? thanks.

**Comment by ping035627** [comment]
@dims @jlowdermilk need lgtm,  who can help to review it? thanks.

**Comment by ping035627** [comment]
@dims @jlowdermilk need lgtm, who can help to review it? thanks.

**Comment by jlowdermilk** [comment]
Sorry about the long delay, it doesn't look like the previous assignee is still working on the project. Change seems reasonable, but I'm assigning someone who's actually worked on proxy recently.

**Comment by freehan** [comment]
Thanks for the PR. LGTM

**Comment by freehan** [comment]
I take that back.

2 reasons:
What if it crash or stuck somewhere in between? 
Since the errors are getting returned, I would say just log it in place. Printing all together in the end makes it harder to read.

**Pull request closed without merging**
