### PR TITLE
Automated cherry pick of #34577

### LINKED ISSUE #35654: All test suite kubernetes-e2e-gce-*-release-1.4 failed
All test suite running against 1.4 release on containervm image failed since ~8:40am this morning. We should fix the issue before we cut another patch release.

cc/ @fejta @foxish, oncall

### PR DESCRIPTION
**Pull request by jessfraz**
Cherry pick of #34577 on release-1.4.
#34577: Delete all firewall rules and network on GCE/GKE test

closes #35654

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35659)

### CODE REVIEW

**Comment by jessfraz** [comment]
@k8s-bot test this

**Comment by ixdy** [comment]
I think you only need 27536e0be0421fdd6e3c429d3a90e60d77d5c900. I should have put that in a separate PR.

**Comment by jessfraz** [comment]
Ah I will make sure it's just that sha

**Comment by jessfraz** [comment]
@k8s-bot test this please

**Comment by jessfraz** [comment]
merging manually to unblock tests

**Pull request merged**
