### PR TITLE
Fix golint errors in test/e2e/lifecycle/bootstrap

### PR DESCRIPTION
**Pull request by davidxia**
part of https://github.com/kubernetes/kubernetes/issues/68026

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This PR fixes golint errors in test/e2e/lifecycle/bootstrap.

**Which issue(s) this PR fixes**:

Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by matthyx** [comment]
/remove-lifecycle stale
/cc
@davidxia please rebase your PR

**Comment by davidxia** [comment]
@matthyx thanks, rebased

**Comment by matthyx** [comment]
@davidxia can you fix those failing jobs?

**Comment by davidxia** [comment]
Master branch already includes these changes.

**Pull request closed without merging**
