### PR TITLE
queueActionLocked requires write lock

### LINKED ISSUE #30759: GarbageCollector broke kubemark-scale
After enabling GarbageCollector in Kubemark, kubemark-scale started failing pretty reliably (all runs failed). Looking into log it seems pretty much related to garbage-collector.

The example failure is here:
http://kubekins.dls.corp.google.com/view/Scalability/job/kubernetes-kubemark-gce-scale/1344/consoleFull

I didn't have time to investigate deeper, but the timing of those failure matches timing of merging:
https://github.com/kubernetes/kubernetes/pull/30401

@lavalamp @gmarek

### PR DESCRIPTION
**Pull request by lavalamp**
Fix https://github.com/kubernetes/minikube/issues/368
Fix part of #30759

Hopefully. On stack dumps I couldn't see who was fighting with this.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30839)

### CODE REVIEW

**Comment by caesarxuchao** [comment]
LGTM. Thanks. cc @wojtek-t.

**Comment by caesarxuchao** [comment]
Bump to P2 as it's potentially fixing the scalability tests.

**Comment by wojtek-t** [comment]
Thanks (though I'm not 100% sure it will fix the problem).
Do you think that it was fighting with itself (i.e. one Resync with the following Resync)? This would be weird since in our tests for pods the resync period IIRC is 10min, and for other resources it should be fast since there aren't a lot of them...

**Comment by lavalamp** [comment]
@wojtek-t my theory is that it's a false positive-- that something in the Pop() routine (which *was* on the stack) just finished a read and now there's a write. Actually this theory may or may not make sense depending on how the map is determining that it's being concurrently accessed.

Having Resync called concurrently could cause it too, but there wasn't evidence of that.

**Comment by timothysc** [comment]
@deads2k ^ see last comment.

**Comment by andrewgdavis** [comment]
Some slowness seems to have been introduced starting / stopping pods when this PR applied.
This is quite apparent running minikube v.0.8.0 (with this change) vs the official v0.8.0 release.  That said, its better than having it crash.

**Comment by lavalamp** [comment]
Hm. This would block lists and gets, where it formerly wouldn't (and now that I look at it, there was a genuine problem where list reads the things that Resync writes).

I can make a change to unlock periodically, not sure if it will help.

@wojtek-t @gmarek fyi in case this shows up in scalability tests.

**Comment by lavalamp** [comment]
@andrewgdavis would you like to try https://github.com/kubernetes/kubernetes/pull/30948 in your setup and see if it makes things better or worse?

**Comment by andrewgdavis** [comment]
Not sure if this should be part of this PR or if a new one should be opened and reference this.  


Any way, with this PR the following occured: (note the follow-up which is 30948 has not yet been applied.)


```
I0819 02:15:32.493056    2446 reflector.go:288] pkg/controller/volume/persistentvolume/controller_base.go:429: next resync planned for time.Time{sec:63607169732, nsec:491794383, loc:(*time.                    Location)(0x5854060)}, forcing now
I0819 02:15:32.493110    2446 reflector.go:288] pkg/controller/volume/persistentvolume/controller_base.go:429: next resync planned for time.Time{sec:63607169732, nsec:491794383, loc:(*time.                    Location)(0x5854060)}, forcing now
I0819 02:15:32.493174    2446 reflector.go:288] pkg/controller/volume/persistentvolume/controller_base.go:434: next resync planned for time.Time{sec:63607169732, nsec:492232783, loc:(*time.                    Location)(0x5854060)}, forcing now
I0819 02:15:32.493146    2446 reflector.go:288] pkg/controller/volume/persistentvolume/controller_base.go:434: next resync planned for time.Time{sec:63607169732, nsec:492232783, loc:(*time.                    Location)(0x5854060)}, forcing now
I0819 02:15:32.493213    2446 controller_base.go:575] storeObjectUpdate updating volume "/build-output" with version 57
I0819 02:15:32.493276    2446 controller.go:336] synchronizing PersistentVolume[build-output]: phase: Bound, bound to: "default/build-output-claim (uid: f5eda67c-6599-11e6-b05a-9e6f16e3b04a)",                 boundByController: true
fatal error: concurrent map read and map writeI0819 02:15:32.493295    2446 controller.go:361] synchronizing PersistentVolume[build-output]: volume is bound to claim default/build-output-claim


goroutine 196522 [running]:
runtime.throw(0x3cecda0, 0x21)
    /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc827b2bae8 sp=0xc827b2bad0
runtime.mapaccess2_faststr(0x2920720, 0xc8225aca20, 0xc8277f1d40, 0x18, 0x1, 0x1)
    /usr/local/go/src/runtime/hashmap_fast.go:307 +0x5b fp=0xc827b2bb48 sp=0xc827b2bae8
k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).queueActionLocked(0xc8222e6b00, 0x38c90c0, 0x4, 0x384ba60, 0xc824f42c60, 0x0, 0x0)
    /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go:315 +0x4dc fp=0xc827b2bcb0 sp=0xc827b2bb48
k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).Resync(0xc8222e6b00, 0x0, 0x0)
    /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go:511 +0x4f7 fp=0xc827b2be28 sp=0xc827b2bcb0
k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch.func1(0xc8201a5ee8, 0xc821b78420, 0xc821a1e140, 0xc824b4e4e0, 0xc8201a5ef0)
    /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:289 +0x252 fp=0xc827b2bf78 sp=0xc827b2be28
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc827b2bf80 sp=0xc827b2bf78
created by k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch
    /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:296 +0xde3
```

**Pull request merged**
