### PR TITLE
Speed up UUID generation.

### LINKED ISSUE #18608: Flaky e2e: [Performance] should allow starting 30 pods per node
Failed in the last 2 runs with
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/density.go:149 There should be no high-latency requests Expected : 1 not to be > : 0
```

Most recent run results: http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/3388/consoleFull

cc @gmarek, @fgrzadkowski

### LINKED ISSUE #19036: e2e flake: Density [Skipped] [Performance] should allow starting 30 pods per node
Density [Skipped] [Performance] should allow starting 30 pods per node

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/density.go:149 There should be no high-latency requests Expected : 1 not to be > : 0

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/3584/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/3581/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/3580/

@wojtek-t

### PR DESCRIPTION
**Pull request by fgrzadkowski**
Speed up UUID generation.

Fixes #19036 
Fixes #18608

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
@brendandburns: With @mwielgus we've just checked the library that we use for generating UIDs. AFAIU it should work no matter how often we call it (there is a `seq` - last two bytes - that solves the problem of repeated system times). Do you remember why you added this logic? I think that current code should already fix our problem, but maybe we can simplify it even further :)

**Comment by mwielgus** [comment]
LGTM assuming that this is needed at all.

**Comment by thockin** [comment]
Wouldn't this be even cleaner to create a buffered channel (size O(100)) and feed it UUIDs from a goroutine?  Callers just pull a UUID from the channel, if that blocks, it blocks, but we can tune the buffer size so that it will never block in caller-context.

**Comment by fgrzadkowski** [comment]
@thockin Great idea! I'll send followup PR to improve this.

**Pull request merged**
