### PR TITLE
Validate kubernetes.io/dockerconfigjson secrets

### PR DESCRIPTION
**Pull request by erictune**

### CODE REVIEW

**Comment by deads2k** [comment]
Can you create a corresponding test like this one: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation_test.go#L3872

**Comment by deads2k** [comment]
Code looks fine, just a request for a unit test to match the ones for the old docker config secret.

Feel free to tag after adding it.

**Comment by erictune** [comment]
Added unit test.  Thanks.

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@erictune - can you please rebase:

00:23:42 +++ [1220 08:23:27] linux/amd64: go build started
00:23:42 # k8s.io/kubernetes/pkg/api/validation
00:23:42 _output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/validation.go:1871: not enough arguments in call to field.Required

**Comment by deads2k** [comment]
@erictune for simple rebases, I don't mind you simply re-applying yourself.  I hadn't noticed this one.

**Comment by erictune** [comment]
@k8s-bot please test this again

**Pull request merged**
