### PR TITLE
Mass import of HEAD docs

### PR DESCRIPTION
**Pull request by brendandburns**
Sorry it doesn't preserve authorship...

### CODE REVIEW

**Comment by brendandburns** [comment]
@bgrant0607 @thockin 

This was created by overwriting the `docs/` and `examples/` directories with their contents from HEAD

Also overwrote `README.md`

If someone can come up with a good incantation to pull to docs over and preserving commit histories, let me know.

**Comment by bgrant0607** [comment]
Re-cut from head and omit and drop the half-dozen non-doc commits?

Otherwise, this is too huge to really review so rubber-stamp LGTM.

**Comment by brendandburns** [comment]
Yeah, I tried to do that through various different git commit mechanics, I didn't really get anywhere.

I can take another stab at it via git revert, perhaps.

**Comment by bgrant0607** [comment]
The one material change I'm aware of was the monit change.

**Comment by brendandburns** [comment]
There are a bunch of changes to mungedocs, some Mesos changes in contrib, etc.

**Comment by bgrant0607** [comment]
Move PD tests to flaky: #11574
Mark new version: #11473
Timeout Docker load: #10998
UpdateTCPLoadBalancer fix: #11349
Kubectl expose error message: #11415

**Comment by bgrant0607** [comment]
I'm fine with merging this as is.

**Comment by lavalamp** [comment]
I'm OK with merging, but be warned, this may make future doc cherry picks extremely inconvenient.

**Comment by lavalamp** [comment]
To do it "right":

```
$ git checkout upstream/master
$ git rebase -i upstream/release-branch
(delete all non-docs commits, gl with that...)
```

hm, maybe you can grep over the logs to figure out what commits to exclude.

**Comment by brendandburns** [comment]
Yeah, I'm closing this in favor of https://github.com/GoogleCloudPlatform/kubernetes/pull/11653

**Pull request closed without merging**
