### PR TITLE
AWS kube-up: Increase timeout waiting for docker start

### PR DESCRIPTION
**Pull request by roberthbailey**
Cherry pick of #25405 on release-1.2.

### CODE REVIEW

**Comment by justinsb** [comment]
@k8s-bot test this flake #26112

**Comment by justinsb** [comment]
@k8s-bot test this flake #26685

**Comment by justinsb** [comment]
@k8s-bot test this flake #25673

**Comment by justinsb** [comment]
Actually, this is crazy... e2e doesn't even touch this.  Marking e2e-not-required

**Comment by roberthbailey** [comment]
Removing lgtm so that the automation can take a break. Will investigate on monday.

**Pull request merged**
