### PR TITLE
remove ipv4 in pkg/util/ipvs

### PR DESCRIPTION
**Pull request by m1093782566**
**What this PR does / why we need it**:

remove ipv4 in util/ipvs

**Which issue this PR fixes**:

xref: #51866

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
@kubernetes/sig-network-bugs can someone with IPVS familiarity look at the changes to the test cases here?

**Comment by m1093782566** [comment]
@smarterclayton 

I just changed the UT from single test case to multiple test cases. I know the change seems large, but many changes are just indent.

**Comment by smarterclayton** [comment]
Ok, thanks

/lgtm

**Pull request merged**
