### PR TITLE
Fix golint errors in test/e2e/storage/vsphere

### PR DESCRIPTION
**Pull request by RaunakShah**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix golint errors in test/e2e/storage/vsphere

**Which issue(s) this PR fixes**:

Part of #https://github.com/kubernetes/kubernetes/issues/68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by oomichi** [comment]
Thanks for fixing the golint failure, the change itself seems good for me.
Could you rebase this PR based on the latest code?

/cc @oomichi

**Comment by oomichi** [comment]
Thanks for updating

/lgtm

**Comment by RaunakShah** [comment]
@oomichi Whats the process to get this merged? Its my first PR to kubernetes so dont know where to go from here :)

**Review by divyenpatel — APPROVED** [review]

**Review by SataQiu — COMMENTED** [review]
/approve

**Pull request merged**
