### PR TITLE
make etcd makefile work on OSX

### PR DESCRIPTION
**Pull request by vishh**

### CODE REVIEW

**Comment by MHBauer** [comment]
tested. works for me.

**Comment by luxas** [comment]
LGTM, thanks!
I don't have a Mac, so can't test it, but seems okay :)

**Comment by luxas** [comment]
@vishh Now you may push them. Thanks!

**Comment by vishh** [comment]
@luxas Builds are failing on OS X. I'm not able to cross-compile to non
amd64 arch on OS X. I posted the build errors in the original PR that
introduced etcd3.

**Pull request merged**
