### PR TITLE
controller: reduce log verbosity for deployments

### LINKED ISSUE #41187: Revisit log verbosity in the Deployment controller
Will happen in the 1.6 timeframe.

@sttts

### PR DESCRIPTION
**Pull request by 0xmichalis**
Fixes https://github.com/kubernetes/kubernetes/issues/41187

Labeling as a bug fix since I think excessive logging should be considered as a bug.

@kubernetes/sig-apps-bugs

### CODE REVIEW

**Comment by smarterclayton** [comment]
Thanks, I just hit this last night and it was driving me up the wall.

**Comment by kargakis** [comment]
@k8s-bot unit test this
@k8s-bot cvm gke e2e test this
@k8s-bot gci gke e2e test this

**Comment by kargakis** [comment]
I am going to attribute these statefulset flakes to the latest gke breakage

@k8s-bot gci gke e2e test this
@k8s-bot cvm gke e2e test this

**Comment by sttts** [comment]
:+1:

**Pull request merged**
