### PR TITLE
Update cri-tools to v1.22.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This patch updates crictl to the latest available release.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?

```release-note
Update cri-tools dependency to v1.22.0
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
The release: https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.22.0
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@kubernetes/sig-node-pr-reviews PTAL

**Review by feiskyer — APPROVED** [review]
/lgtm

**Review by ibabou — APPROVED** [review]

**Pull request merged**
