### PR TITLE
Pin godep to version 32

### PR DESCRIPTION
**Pull request by eparis**
33, 34, 35 are all broken differently.
https://github.com/tools/godep/issues/359

### CODE REVIEW

**Comment by eparis** [comment]
@mikedanese @wojtek-t   This should unblock godep changes....

**Comment by yifan-gu** [comment]
@eparis Thanks! LGTM!

**Comment by wojtek-t** [comment]
@eparis - Thanks!

LGTM

**Comment by eparis** [comment]
Green, unblocks failing unit tests. Self merging.

**Pull request merged**
