### PR TITLE
Deprecate InfluxDB cluster monitoring

### PR DESCRIPTION
**Pull request by serathius**
InfluxDB cluster monitoring addon will no longer be supported and will be removed in k8s 1.12.
Default monitoring solution will be changed to `standalone`.
Heapster will still be deployed for backward compatibility of `kubectl top`

```release-note
Stop using InfluxDB as default cluster monitoring
InfluxDB cluster monitoring is deprecated and will be removed in v1.12
```
cc @piosz

### CODE REVIEW

**Comment by kawych** [comment]
I'm fine with changing the default, but should we delete e2e tests already? I would prefer to remove them only when we actually stop supporting influxdb.

**Comment by serathius** [comment]
I will tag to tests with `[Feature:InfluxdbMonitoring]`

**Comment by serathius** [comment]
Cherry picked

**Comment by brancz** [comment]
Generally this sounds and looks good to me, I'm just wondering about this sentence:

> Heapster will still be deployed for backward compatibility of kubectl top

Are you talking about older versions? In 1.10+ kubectl top defaults to using the resource metrics API and only falls back to trying heapster.

**Comment by serathius** [comment]
> Are you talking about older versions? In 1.10+ kubectl top defaults to using the resource metrics API and only falls back to trying heapster.
Yes, that's why we don't want drop heapster in following version 1.11, not everyone had chance to upgrade their client. We don't want to drop `kubectl` 1.10 support for metrics in default configuration.

**Comment by brancz** [comment]
Got it. Thanks for clarifying.

/approve
/lgtm

**Comment by serathius** [comment]
@wojtek-t can you approve?

**Pull request merged**
