### PR TITLE
Updated a link to the latest changelog

### PR DESCRIPTION
**Pull request by zerkms**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

It updates a link to the latest version (1.13) changelog in the `CHANGELOG.md` index file

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: No

```release-note
NONE
```

### CODE REVIEW

**Comment by zerkms** [comment]
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify.
signed

**Review by danielqsj — APPROVED** [review]
/lgtm

**Pull request merged**
