### PR TITLE
kubectl attach only takes one argument

### PR DESCRIPTION
**Pull request by fabianofranz**
Fixes `kubectl attach` example, attach is not supposed to receive more than one argument (POD).

### CODE REVIEW

**Comment by ashcrow** [comment]
Good catch. It does indeed error with the the original command:

```
error: expected a single argument: POD, saw 2: [123456-7890 date]
```

Looks good to me!

**Comment by ashcrow** [comment]
Hrm. The build-log.txt is empty and this change shouldn't have caused any functionality difference ...

**Comment by ashcrow** [comment]
@k8s-bot test this please.

**Comment by ashcrow** [comment]
@fabianofranz looks like ```./hack/update-generated-docs.sh``` needs to be run to update the generated documentation before Travis will let it pass.

**Comment by fabianofranz** [comment]
bump

**Comment by ashcrow** [comment]
:+1: looks good to me

**Pull request merged**
