### PR TITLE
Update kubectl create subcommand to use printer flags

### PR DESCRIPTION
**Pull request by derekwaynecarr**
When using `--output=wide`, you need to support the `no-headers` flag.

Fixed code to pull printer flags so we have the right set.

Fixes https://github.com/kubernetes/kubernetes/issues/19129

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
@ncdc @eparis - easy review if you can take a look.

**Comment by spxtr** [comment]
@k8s-bot unit test this again

**Comment by derekwaynecarr** [comment]
@k8s-bot test this

**Comment by deads2k** [comment]
I'm surprised this works.  I didn't think that `kubectl create` displayed the resulting objects to allow things like templating to work.  Can you add a `test-cmd` test to demonstrate it?

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

**Comment by deads2k** [comment]
> I'm surprised this works. I didn't think that kubectl create displayed the resulting objects to allow things like templating to work. Can you add a test-cmd test to demonstrate it?

To be clear, I have no objection to the code, I just didn't expect to work since `kubectl create` doesn't have options to display the resulting objects either.  If this lets me see the returned object via printers and templates, I'll be really pleased.

**Comment by derekwaynecarr** [comment]
@deads2k - got back around to this.  added the `hack/test-cmd.sh` that demonstrates the use of a go-template to parse the output of the create subcommand.

**Comment by deads2k** [comment]
lgtm.  squash and tag at will.

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

Tests have been pending for 24 hours

**Comment by derekwaynecarr** [comment]
Rebased and repushed, will reapply lgtm to hopefully make our bot happy.

**Comment by derekwaynecarr** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by derekwaynecarr** [comment]
@eparis -it's not clear to me what is needed to make merge bot happy? Help?

**Comment by derekwaynecarr** [comment]
looks like this is happening:

```
(BError from server: secrets "test-secret" is forbidden: Unable to create new content in namespace test-secrets because it is being terminated.
!!! Error in ./hack/test-cmd.sh:213
  '[[ -n "$(kubectl create secret generic test-secret --namespace=test-secrets --from-literal=key1=value1 --output=go-template --template=\"{{.metadata.name}}:\" | grep 'test-secret:')" ]]' exited with status 0
Call stack:
  1: ./hack/test-cmd.sh:213 runTests(...)
  2: ./hack/test-cmd.sh:1429 main(...)
```

will investigate tomorrow.

**Pull request merged**
