### PR TITLE
Kubernetes 1.25: CSIStorageCapacity: use v1 as storage version

### LINKED ISSUE #108451: storage capacity tracking: switch storage version from v1beta1 to v1
### What would you like to be added?

The override in https://github.com/kubernetes/kubernetes/blob/ab69524f795c42094a6630298ff53f3c3ebab7f4/pkg/kubeapiserver/default_storage_factory_builder.go#L64 can be removed in Kubernetes v1.25 because then the oldest supported kube-apiserver for downgrades will be v1.24 which will understand the v1 format.

Also need to adapt test/integration/etcd/data.go.

See https://github.com/kubernetes/kubernetes/pull/108445#pullrequestreview-897592952 and https://github.com/kubernetes/kubernetes/pull/108445#pullrequestreview-897596309

### Why is this needed?

Code cleanup...

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This can be done because downgrades are only supported down to 1.24 and that
release supports v1.

#### Which issue(s) this PR fixes:
Fixes #108451

#### Special notes for your reviewer:

This will fail integration testing until 1.24 is "the previous release":
```
    etcd_storage_path_test.go:189: Previous releases understand non-alpha versions ["v1beta1"], but do not understand the expected current storage version "v1". This means a current server will store data in etcd that is not understood by a previous version.
    --- FAIL: TestEtcdStoragePath/storage.k8s.io/v1,_Resource=csistoragecapacities (0.02s)
```

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm

**Comment by pohly** [comment]
/retest

@logicalhan: I had to rebase. Can you lgtm again?

**Review by logicalhan — APPROVED** [review]
/lgtm

**Comment by pohly** [comment]
/retest

The v1.24 api testdata was updated, pull-kubernetes-integration should pass now.

**Comment by pohly** [comment]
/assign @enj @sttts

For approval.

**Comment by liggitt** [comment]
I'm really surprised this didn't change / complain: https://github.com/kubernetes/kubernetes/blob/1e3c973e72523619640f24518fe189d118ab5538/pkg/controlplane/storageversionhashdata/data.go#L75-L77

**Comment by liggitt** [comment]
change lgtm other than the storage version hash question

**Comment by pohly** [comment]
So you are saying that `go test ./pkg/controlplane` (which includes instance_test.go where pkg/controlplane/storageversionhashdata gets used) should fail because of the changes in this PR?

The entry for "storage.k8s.io/v1/csistoragecapacities" in data.go was added (and necessary) in 921edae2b4daacd758e25b314606d7074e51da37.

**Comment by pohly** [comment]
* k8s.io/kubernetes/pkg/controlplane: TestStorageVersionHashes 

> `Error while dialing dial tcp 127.0.0.1:43313: connect: connection refused`

That doesn't look related and I cannot reproduce locally.

/retest

**Comment by pohly** [comment]
The actual error was the hash mismatch, not the warning about the lost connection. My master branch wasn't up-to-date. I thought I had pulled the fix for the unit hash test, but apparently not. Now the version change gets reflected properly in the hash values.

@liggitt : please take another look.

**Pull request merged**
