### PR TITLE
docs: remove troubleshooting

### PR DESCRIPTION
**Pull request by philips**
Based on comment from @bgrant0607 https://github.com/kubernetes/kubernetes/pull/35544/files#r85368740

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35753)

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks!
/lgtm

**Comment by bgrant0607** [comment]
@grodrigues3 @apelisse @fejta Another example where someone would have liked to suggest a reviewer, but couldn't. ref #1908

**Comment by fejta** [comment]
@k8s-bot gci gce e2e test this

**Comment by fejta** [comment]
@bgrant0607 are you saying that we should notice that you were tagged when filing the issue and assigned it to you based on this?

**Comment by bgrant0607** [comment]
@fejta I'm just pointing out pervasive contributor friction, to help you understand the problems. We could potentially recognize the notification, or just use a bot command, which is what is being discussed in https://github.com/kubernetes/contrib/issues/1927

**Pull request merged**
