### PR TITLE
Create config type in DefaultTolerationSeconds and remove global flags

### LINKED ISSUE #55284: DefaultTolerationSeconds admission plugin flags pollute all commands
The DefaultTolerationSeconds admission plugin configures itself via globally registered flags, rather than via plugin config, as expected.

This has several negative effects:
* The global flags are visible in completely unrelated commands, like kubectl:
    ```
    $ kubectl options
    The following options can be passed to any command:
    ...
    --default-not-ready-toleration-seconds=300: Indicates the tolerationSeconds of the toleration for notReady:NoExecute that is added by default to every pod that does not already have such a toleration.
    --default-unreachable-toleration-seconds=300: Indicates the tolerationSeconds of the toleration for unreachable:NoExecute that is added by default to every pod that does not already have such a toleration.
    ```
* The admission plugin is not positioned to receive config as apiserver config is updated to be able to be consumed from files, and then dynamically

The global flags should be deprecated, and a config type created to hold the config for this admission plugin (like other configurable admission plugins)

cc @kubernetes/sig-scheduling-bugs

### PR DESCRIPTION
**Pull request by lichuqiang**
**What this PR does / why we need it**:
remove global flags in DefaultTolerationSeconds , and create a config type to hold the config for this admission plugin (like other configurable admission plugins)

**Which issue(s) this PR fixes**:
Fixes #55284

**Special notes for your reviewer**:
/cc @liggitt 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lichuqiang** [comment]
@liggitt Do you think it necessary to make the config type versioned? 
As the params are simple and I couldn't see potential change in the config, I would keep it as it is now.

**Comment by liggitt** [comment]
> @liggitt Do you think it necessary to make the config type versioned?

Yes. All config should be versioned.

**Comment by lichuqiang** [comment]
@liggitt I've updated the PR to make the config type versioned. Could you take a look?

**Comment by shasti86** [comment]
Is there any traction on this PR? cc @lichuqiang

**Pull request closed without merging**
