### PR TITLE
Log mvcc revision compaction as warning

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
As Fabian stated over #83938, the 'mvcc: required revision has been compacted' message shouldn't be logged as error.
This PR changes the log for this message to warning.

**Which issue(s) this PR fixes**:
Fixes #

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by tedyu** [comment]
ping @jpbetz for review

**Comment by tedyu** [comment]
ping @jpbetz for review

**Comment by jpbetz** [comment]
/lgtm

I'm okay with this. I'd expect the log volume to low and proportional to the other log events that will occur if a watch consumer falls outside the compaction window.

**Pull request merged**
