### PR TITLE
update repo local config to allow redirects from gopkg.in

### LINKED ISSUE #39583: hack/verify-bazel.sh failing with HTTP error 301
When I run it locally:
```
$ hack/verify-bazel.sh
# cd .; git clone https://gopkg.in/mikedanese/gazel.v13 /usr/local/google/home/mtaufen/go-tools/src/gopkg.in/mikedanese/gazel.v13
Cloning into '/usr/local/google/home/mtaufen/go-tools/src/gopkg.in/mikedanese/gazel.v13'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
package gopkg.in/mikedanese/gazel.v13/gazel: exit status 128
!!! Error in hack/verify-bazel.sh:23
  'go get -u gopkg.in/mikedanese/gazel.v13/gazel' exited with status 1
Call stack:
  1: hack/verify-bazel.sh:23 main(...)
Exiting with status 1
```

Small test case to induce failure:
```
$ git clone https://gopkg.in/mikedanese/gazel.v13
Cloning into 'gazel.v13'...
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
```

I am using git version 2.11.0, if it makes any difference.

### PR DESCRIPTION
**Pull request by mikedanese**
closes #39583

### CODE REVIEW

**Comment by spxtr** [comment]
I thought this needed to be global, since the actual git repo it checks out will be under `$GOPATH/src/bla`.

**Comment by ixdy** [comment]
I'm a little wary about updating git configs automatically, but I'm not sure if there's a better way...

**Comment by mikedanese** [comment]
@ixdy, cluster local gitconfigs are less bad then global. We seem to not be getting any traction over at gopkg.in and this continues to break people.

**Comment by spxtr** [comment]
As long as this actually works,

/lgtm

**Pull request merged**
