### PR TITLE
Added configurable etcd initial-cluster-state to kube-up script.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Added configurable etcd initial-cluster-state to kube-up script. This
allows creation of multi-master cluster from scratch. This is a
cherry-pick of #41320 from 1.5 branch.

```release-note
Added configurable etcd initial-cluster-state to kube-up script.
```

### CODE REVIEW

**Comment by roberthbailey** [comment]
I'm not sure I understand why we committed something directly to the 1.5 branch and are cherry picking it back into the master branch instead of doing things the other way around. 

@saad-ali

**Comment by jszczepkowski** [comment]
> I'm not sure I understand why we committed something directly to the 1.5 branch and are cherry picking it back into the master branch instead of doing things the other way around.

@roberthbailey 
I wanted this modification to go with 1.5.3 release which may be cut today, and I thought that if we make release first on master branch we will not have time for it.

**Comment by jszczepkowski** [comment]
@roberthbailey @mikedanese Can one of you approve?

**Pull request merged**
