### PR TITLE
Start to incorporate reliability work items into roadmap

### PR DESCRIPTION
**Pull request by satnam6502**
This PR initiates the process of grafted the reliability improvement information captured in the Google doc into the roadmap document.

### CODE REVIEW

**Comment by satnam6502** [comment]
@brendandburns : any chance of having this assigned or a reviewer or merged? Thanks.

**Comment by satnam6502** [comment]
Ah, @erictune was assined!

**Comment by bgrant0607** [comment]
I was assigned, but don't have time to look at this. Who provided comments on the doc?

**Comment by satnam6502** [comment]
Perhaps you could look at the original Google Doc?
https://docs.google.com/document/d/1wwh569PwAWvEZcLc0gHSrO1xr-N-T5cnKjepjc0dXvI/edit#

Thanks.

**Comment by bgrant0607** [comment]
Ok. @roberthbailey already reviewed it.

BTW, I recommend filing issues for any items without preexisting issues, and then choose/create a label to mark all the issues.

**Comment by roberthbailey** [comment]
I've already filed issues for most of the bullets and assigned them the area/reliability label.

**Pull request merged**
