### PR TITLE
Fix failed to access service of e2e test

### LINKED ISSUE #55696: E2e test failed and can't access service
**Is this a BUG REPORT or FEATURE REQUEST?**:

>
> /kind bug

**What happened**:
I local-up a k8s cluster without kube-dns service on only-one node, so I set in guestbook-deployment.yaml through env to access service. But it will failed occasionally as log below, which shows 
that it can't find the service addr. We should create service first before deployments.

Nov 13 18:56:47.652: INFO: Failed to get response from guestbook. err: <nil>, response: <br />
<b>Fatal error</b>:  Uncaught exception 'Predis\Connection\ConnectionException' with message 'php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://:6379]' in /usr/local/lib/php/Predis/Connection/AbstractConnection.php:168
......
Nov 13 18:56:52.677: INFO: Failed to get response from guestbook. err: <nil>, response: <br />
<b>Fatal error</b>:  Uncaught exception 'Predis\Connection\ConnectionException' with message 'php_network_getaddresses: getaddrinfo failed: Name or service not known [tcp://:6379]' in /usr/local/lib/php/Predis/Connection/AbstractConnection.php:168

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by fisherxu**
**What this PR does / why we need it**:
We should create service before deployments as said in the issue.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes [#55696](https://github.com/kubernetes/kubernetes/issues/55696)

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
I'm fine with re-ordering these, but in general apps should tolerate coming up in any order, since cold restarts can do exactly that.  Relying on particular startup orders results in sadness.

/lgtm

**Comment by fisherxu** [comment]
@deads2k  

> Relying on particular startup orders results in sadness

yes, but now if our app access service via env, the pod must created before the service, or else must  restart pod to reload the need env.

**Comment by deads2k** [comment]
> yes, but now if our app access service via env, the pod must created before the service, or else must restart pod to reload the need env.

Yeah.  Your pod really needs to tolerate coming up out of order.  I'd recommend failing a readiness or liveness check and simply crashlooping.  If all nodes died and later restarted, you have no guarantee of the order your pods restart in.  Even now, there isn't a guarantee, you're getting lucky.

As I said, I'm ok with it in a test, but if you're relying on this somewhere real, it will end in tears.

**Comment by fisherxu** [comment]
@deads2k Thanks for reply :)  In my production environment I deploy the kube-dns and access service via it. The issue related test is just a simply CI I use env, and fix for other people who also env :)

>  I'd recommend failing a readiness or liveness check and simply crashlooping

and this is really a good idea while using env in somewhere  real!
Another question about usermod in contain can you help take a look? Thanks  #55882

**Pull request merged**
