### PR TITLE
Bugfix: kubectl shows last<invalid> if pv, pod or pvc is terminating using kubectl describe xxxx

### LINKED ISSUE #74790: ￼Kubectl shows last<invalid> if pv, pod or pvc is terminating using kubectl describe pv xxx
**What happened**:
 ￼Kubectl describe pv xxx  shows last<invalid> if pv is terminating
image

I found pvc and pod  have the same issue

**What you expected to happen**:
Terminating (lasts 10s)
**How to reproduce it (as minimally and precisely as possible)**:
1 create  a pv, pvc or pod is terminating
2 using kubectk describe xxx
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
kubectl shows last<invalid> if pv, pod or pvc is terminating using kubectl describe. Like this: 
image

**Which issue(s) this PR fixes**:

Fixes #74790

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cwdsuzhou** [comment]
@dims

**Comment by cwdsuzhou** [comment]
@dims @rootfs please help review the code, thank you

**Comment by cwdsuzhou** [comment]
> /ok-to-test
> /lgtm
> /approve

Hi @liggitt ,  I resubmitted the codes to fix UT, please review it again, thank you

**Comment by cwdsuzhou** [comment]
@kubernetes/sig-cli-pr-reviews

**Comment by yue9944882** [comment]
this pull needs a release-note, tal [https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md#adding-release-notes](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md#adding-release-notes)

**Comment by liggitt** [comment]
I don't think this change needs to make it into the release notes

**Pull request merged**
