### PR TITLE
Automated cherry pick of #74454: kubeadm: fix url validation code

### PR DESCRIPTION
**Pull request by neolit123**
Cherry pick of #74454 on release-1.13.

#74454: kubeadm: fix url validation code

### CODE REVIEW

**Comment by neolit123** [comment]
/kind bug
/priority critical-urgent

fixing a panic and back porting to 1.13.

/assign @fabriziopandini @timothysc 
/assign @aleksandra-malinowska @tpepper

**Comment by neolit123** [comment]
cc @bart0sh

**Comment by bart0sh** [comment]
should it be cherry-picked for 1.12 as well?

**Comment by neolit123** [comment]
> should it be cherry-picked for 1.12 as well?

let me see the state of the 1.12 branch.

**Comment by fabriziopandini** [comment]
Thanks @bart0sh and @neolit123 for the quick fix!
/approve
/lgtm

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Comment by timothysc** [comment]
@kubernetes/sig-release

**Review by idealhack — APPROVED** [review]

**Pull request merged**
