### PR TITLE
kube-apiserver in a pod.

### PR DESCRIPTION
**Pull request by ArtfulCoder**
#5011

@roberthbailey

### CODE REVIEW

**Comment by ArtfulCoder** [comment]
manually tested kube-up and kube-push on gce cluster.

**Comment by dchen1107** [comment]
LGTM. I also did test against the PR too.

**Comment by roberthbailey** [comment]
Did you run e2e tests on this change? There are multiple tests that are now failing consistently with

`Post https://www.googleapis.com/compute/v1/projects/661044217466/regions/us-central1/targetPools?alt=json: x509: failed to load system roots and no roots provided`

which is likely because we are running a go binary that doesn't have access to the systems SSL root certificate store.

**Comment by dchen1107** [comment]
Are you still observing the same problem? I did manually test both up and push case, and tried a couple of kubectl commands, and didn't run into the issue above. I am kicking out e2e test with this PR now.

**Comment by roberthbailey** [comment]
Did you try creating a service with an external load balancer? The tests that are failing are the ones where the apiserver needs to make calls into the cloud provider and can't verify the cert returned by googleapis.com.

**Comment by dchen1107** [comment]
No, I didn't try that test. Now I am running e2e, if it failed, I will revert this change, and I am sure @ArtfulCoder will solve that issue on Monday if there is a breakage caused by this one. :-)

**Comment by dchen1107** [comment]
@ArtfulCoder just informed me that he ran e2e, and knew the failure is caused by a different PR. He will give more information shortly. Thanks!

**Comment by roberthbailey** [comment]
SGTM. There were a number of commits at the failed time and without investigating too much this one seemed suspicious.

**Comment by ArtfulCoder** [comment]
The failures that were happening before my checkin, were fixed.

Some tests were just flaky.

But in the last run, these 3 tests that Robert talks about are consistently
failing post my PR.

I think I am missing a volume mount for apiserver pod and it cant find cert
roots for cert validation.

Dawn is reverting my change and running e2e.

Thanks!
Abhi

**Comment by roberthbailey** [comment]
We can discuss when you resubmit your PR, but a volume mount might be difficult b/c the root cert store isn't located in a consistent place on different linux distros. 

@kelseyhightower wrote a medium article that might be helpful: https://medium.com/@kelseyhightower/optimizing-docker-images-for-static-binaries-b5696e26eb07

**Comment by zmerlynn** [comment]
I know I'm late to this party, but this looks beautiful.

**Comment by derekwaynecarr** [comment]
I am having intermittent issues when doing a kube-push where the system can get in a state where the kube-apiserver never runs even when Salt reports success.

Has anyone seen this?  Once the system gets in this state, I can't seem to fix it.  I will try to capture any relevant logs next time it occurs, but it seems like after 3 or 4 pushes that changed code, the pause container remains running but the Api server never starts again and docker logs shows no error for the exited container. 

Is the Kubelet now responsible for  monitoring here and restarting?

**Comment by derekwaynecarr** [comment]
I don't see a restart policy on the manifest, and cannot easily check if the pod has a restart policy applied at the moment.  Recording here so I can remember to check when debugging further.

**Comment by derekwaynecarr** [comment]
Another issue is I need to update instructions for the cloud provider to know where to read log output now for the components since they are no longer in journalctl

**Comment by ArtfulCoder** [comment]
@derekwaynecarr kubelet should restart the pod if the manifest definition changes.
kube-push does update the manifest file if there is a change in the binary.

For logs, I enabled fluentd on master as well. So we should see logs just as we see logs of any other pod running on the cluster. I have not verified this though and plan to do it tomorrow.

**Comment by derekwaynecarr** [comment]
But does the kubelet restart the api-server pod if the api-server container fails during normal operation?

I guess I view this as making us no longer need monit or any other monitor, and expected to see an explict RestartPolicy of always on the manifest.

----- Original Message -----

**Comment by derekwaynecarr** [comment]
I see the kube-apiserver restart policy is always.

----- Original Message -----

**Pull request merged**
