### PR TITLE
daemon/controller.go: remove unused func enqueueAllDaemonSets

### PR DESCRIPTION
**Pull request by xiang90**

### CODE REVIEW

**Comment by mikedanese** [comment]
lgtm

**Comment by xiang90** [comment]
@k8s-bot e2e test this issue: #IGNORE

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please, issue: #IGNORE (tests didn't start)

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please, issue: #27503

**Pull request merged**
