### PR TITLE
Promote SSA to GA

### PR DESCRIPTION
**Pull request by Jefftree**
#### What type of PR is this?

/kind feature
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

Promotes SSA to GA. See [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/555-server-side-apply)

Depends on the following PRs to get merged:

Scale Subresource:
~~https://github.com/kubernetes/kubernetes/pull/98377~~ APPROVED

SSA Client:
~~https://github.com/kubernetes/kubernetes/pull/99012~~ MERGED
~~https://github.com/kubernetes/kubernetes/pull/99462~~ MERGED
~~https://github.com/kubernetes/kubernetes/pull/99759~~ APPROVED

Status Wiping:
~~https://github.com/kubernetes/kubernetes/pull/99661~~ APPROVED

E2E Tests
~~https://github.com/kubernetes/kubernetes/pull/98034~~ MERGED

Mutating Admission Controllers:
~~https://github.com/kubernetes/kubernetes/pull/98074~~ MERGED

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Jefftree** [comment]
/hold

Still waiting for other PRs to merge.

**Comment by fedebongio** [comment]
yay! very exciting!
/triage accepted

**Comment by Jefftree** [comment]
/assign @deads2k 
/assign @lavalamp 

There are still a couple PRs outstanding, just want to bring this on your radar.

**Comment by lavalamp** [comment]
/approve
/lgtm
/hold

everything is approved, let's hold this to make sure it merges last

**Pull request merged**
