### PR TITLE
Update CHANGELOG OWNERS to reflect 1.28 Release Notes team

### PR DESCRIPTION
**Pull request by sanchita-07**
#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it:
This PR updates the OWNERS file and adds 1.28 release-notes team as approver and reviewers.

/assign @gracenng @leonardpahlke

### CODE REVIEW

**Comment by gracenng** [comment]
/lgtm
/approve
cc @palnabarun

**Review by palnabarun — APPROVED** [review]
/triage accepted

/lgtm
/approve

Adding the milestone since this is required for Release Notes Team to work on the CHANGELOG 
/milestone v1.28

**Comment by palnabarun** [comment]
/retitle Update CHANGELOG OWNERS to reflect 1.28 Release Notes team

**Pull request merged**
