### PR TITLE
golangci-lint v1.55.1

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

No particular reason for updating to it besides staying up-to-date. The new
ginkgolinter found one issue.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by yxxhero** [comment]
@pohly there are a lot of lint errors that should be fixed. thanks.

**Comment by pohly** [comment]
`hack/verify-golangci-lint.sh` passes in my branch. The failure in the CI was added to the master branch in the meantime... 

I've rebased and fixed `test/e2e_node/pod_host_ips.go`.

**Comment by pohly** [comment]
The failures when testing a PR seem to come from golangci-lint, I created https://github.com/golangci/golangci-lint/issues/4159.

**Pull request merged**
