### PR TITLE
Enable StreamingProxyRedirects for CRI e2e tests

### PR DESCRIPTION
**Pull request by timstclair**
Required for CRI attach/exec/port-forward calls.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36378)

### CODE REVIEW

**Comment by feiskyer** [comment]
LGTM. cc/ @Random-Liu

**Comment by liggitt** [comment]
+1 for testing old and new paths

As we grow this out, it would be good to have tests around the edge cases identified… redirect case with very large command or streaming stdin, etc

**Comment by yujuhong** [comment]
LGTM. I think you'll need to enable this in the cluster e2e configs in the test-infra repo. See https://github.com/kubernetes/test-infra/pull/998/files for the relevant configs.

**Comment by liggitt** [comment]
I don't want to change the non CRI-focused test setup quite yet, we have to make sure we're testing the defaults work

**Comment by yujuhong** [comment]
> I don't want to change the non CRI-focused test setup quite yet, we have to make sure we're testing the defaults work

This PR only changes the CRI test configs.

**Comment by yujuhong** [comment]
For the record, I applied the lgtm labels, but github decided to show that @timstclair applied the labels himself.

**Pull request merged**
