### PR TITLE
Changed naming in controller for HorizontalPodAutosclaer.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Changed naming in controller for HorizontalPodAutosclaer to make it consistent with the coding conventions.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
@lavalamp 
This is the follow-up of https://github.com/kubernetes/kubernetes/pull/13303#discussion_r38226989.

**Comment by mwielgus** [comment]
LGTM

**Comment by lavalamp** [comment]
Thanks!

**Comment by jszczepkowski** [comment]
@k8s-bot test this

**Comment by jszczepkowski** [comment]
Part of #12087.

**Pull request merged**
