### PR TITLE
release-1.7: Update boilerplate for 2018

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
This is an attempted carry of @nikhita's PR, #57796.
This is acts a cherry pick of #57735.

**Note**: This is not an automated cherry-pick since lots of things have changed since 1.7 and a cherry-pick leads to lots of conflicts in the generated files.

This also unblocks further client-go 4.0 releases. (see #57245)

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
The main difference I think I ran `make update` which triggers `make generated_files` before `hack/update-all.sh`. I didn't get any godep changes other than it complaining about the version until I swapped to go1.8.

**Comment by nikhita** [comment]
> The main difference I think I ran make update which triggers make generated_files before hack/update-all.sh

I see. 👍

**Comment by wojtek-t** [comment]
Awesome - thanks a lot @cblecker !!

/lgtm
/approve no-issue

**Pull request merged**
