### PR TITLE
updating the API reviewers for sig-windows

### PR DESCRIPTION
**Pull request by michmike**
updating the reviewers for sig-windows so that we distribute the work and put the appropriate folks in the right places
/kind cleanup
```release-note
NONE
```

### CODE REVIEW

**Comment by michmike** [comment]
cc: @PatrickLang @ddebroy @benmoss

**Comment by liggitt** [comment]
/approve

@PatrickLang has lgtm

**Comment by cblecker** [comment]
People change not code change
/milestone v1.15

**Pull request merged**
