### PR TITLE
pkg/kubelet/remote/remote_runtime.go:fix the incorrect klog comment

### LINKED ISSUE #90221: Incorrect method name in log of remote_runtime.go
**What happened**:
In pkg/kubelet/remote/remote_runtime.go, there is mismatch between method name and the method in logs. e.g. RemoteRuntimeService#Attach has the following:
```
                klog.Errorf("Exec failed: %s", errorMessage)
```
**What you expected to happen**:
The method names should be consistent with what appear in the logs.

/sig node

### PR DESCRIPTION
**Pull request by tanjunchen**
**What type of PR is this?**
 
 /kind cleanup
 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/90221

**Special notes for your reviewer**:

The method names should be consistent with what appear in the logs. 
Otherwise people would be confused when troubleshooting.

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/assign @feiskyer

**Review by feiskyer — APPROVED** [review]

**Pull request merged**
