### PR TITLE
Remove scheduling.k8s.io/v1alpha1 version of PriorityClass

### PR DESCRIPTION
**Pull request by h4ghhh**
#### What type of PR is this?
/kind cleanup
/kind api-change
/sig scheduling

#### What this PR does / why we need it:
https://github.com/kubernetes/kubernetes/pull/74465
PriorityClass v1 graduated in 1.14, and v1alpha1 is deprecated for a long time. As the API deprecation policy, it should be removed.

#### Which issue(s) this PR fixes:

Fixes # 

#### Does this PR introduce a user-facing change?

```release-note
PriorityClass v1alpha1 is removed.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/268-priority-preemption

```docs
NONE
```

### CODE REVIEW

**Comment by h4ghhh** [comment]
/cc @caesarxuchao 
Hi, I do not know why the tests failed, could you help me?

**Comment by h4ghhh** [comment]
/cc @kubernetes/sig-scheduling-api-reviews
Hi, I do not know why the tests failed, could you help me?

**Comment by dims** [comment]
Is this PR still needed, please rebase if so (or we can close it?)

**Comment by dims** [comment]
This PR is older than 4 weeks and needs as rebase.

Please rebase the PR against latest master and reopen if still needed.

/close

**Pull request closed without merging**
