### PR TITLE
Support multiple --feature-gates flags in the command line

### PR DESCRIPTION
**Pull request by sttts**
Fixes the issue in https://github.com/kubernetes/kubernetes/pull/42647.

Before this change the whole set of gates was replaced with new values. Now values are overridden one by one.

### CODE REVIEW

**Comment by sttts** [comment]
This deserves unit tests. Lacking the time to write them now.

**Comment by sttts** [comment]
Added unit tests.

**Comment by gmarek** [comment]
Adding milestone, as it's needed to make feature testing not extremely painful (i.e. without digging into default feature flags)

**Comment by sttts** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
