### PR TITLE
Automated cherry pick of #31886

### PR DESCRIPTION
**Pull request by j3ffml**
Cherry pick of #31886 on release-1.4.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32331)

### CODE REVIEW

**Comment by pwittrock** [comment]
@deads2k Please take a look ASAP

**Comment by jlowdermilk** [comment]
For the second commit, I manually resolved conflicts then ran `hack/update-swagger-spec.sh`. I didn't run `hack/update-generated-docs.sh` as it looks like there are still some unversioned docs in the branch, so I expect that versioning will be done in a future pr.

**Comment by foxish** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by foxish** [comment]
@jlowdermilk Looks like some test failures due to the lack of updated docs I think.

I see the following in **Jenkins Verification**.
```
FAILED   hack/make-rules/../../hack/verify-api-reference-docs.sh	31s
```

**Comment by rmmh** [comment]
This should probably be combined with #32199, as in https://github.com/kubernetes/kubernetes/pull/31886#issuecomment-245426673 ?

**Comment by foxish** [comment]
@rmmh We had a discussion offline. After this change, the test would go red, and then @jlowdermilk was going to make some changes in GKE to make it pass again.

**Comment by deads2k** [comment]
lgtm.  I'm unsure about tagging it since gke would start breaking.

**Comment by foxish** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by foxish** [comment]
@rmmh Do we have the fix for the jenkins plugin deployed already? Looks like tests are running as expected with the cherrypick PR now.

**Comment by foxish** [comment]
@jlowdermilk Expecting tests to go red and come back green soon (hopefully :))

cc @pwittrock

**Pull request merged**
