### PR TITLE
Cleanup: "scaler" -> "scale".

### PR DESCRIPTION
**Pull request by jszczepkowski**
Cosmetic cleanup: "scaler" replaced with "scale" (the proper name for sub-resource).

### CODE REVIEW

**Comment by mwielgus** [comment]
LGTM

**Comment by bgrant0607** [comment]
Thanks. LGTM.

**Comment by cjcullen** [comment]
@k8s-bot test this please.

**Comment by piosz** [comment]
Shippable is failing while trying to verify gendocs. Rebase should fix the problem. Could you do it?

**Comment by jszczepkowski** [comment]
Part of #12087.

**Pull request merged**
