### PR TITLE
revert #64933 update cadvisor godeps to v0.30.0

### LINKED ISSUE #64933: Summary API test is flaky
https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet

It become too flaky recently since 6/5/2018.

@kubernetes/sig-node-bugs

### PR DESCRIPTION
**Pull request by dashpole**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #64933

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by AishSundar** [comment]
/milestone v1.11

Setting milestone to 1.11 so it can be merged

/cc @jberkus @tpepper @dims @BenTheElder as FYI

**Review by dims — APPROVED** [review]

**Comment by tpepper** [comment]
Since this reverts pull #64800 which had a release note, is the release note in need of update?

**Comment by dashpole** [comment]
I have figured out that the problem is https://github.com/google/cadvisor/pull/1916.  I will cut cadvisor v0.30.1 with a revert of just that PR, and close this one

**Pull request closed without merging**
