### PR TITLE
Automated cherry pick of #117802: Update podFailurePolicy comments from alpha-level to beta

### PR DESCRIPTION
**Pull request by kerthcet**
Cherry pick of #117802 on release-1.27.

#117802: Update podFailurePolicy comments from alpha-level to beta

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Revised the comment about the feature-gate level for PodFailurePolicy from alpha to beta
```

### CODE REVIEW

**Comment by xmudrii** [comment]
@kerthcet @liggitt Just to double check, is this cherry-pick needed only for 1.27 and 1.26?

**Comment by kerthcet** [comment]
> @kerthcet @liggitt Just to double check, is this cherry-pick needed only for 1.27 and 1.26?

Yes, it became beta in v1.26. Thanks.

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
