### PR TITLE
refactor autoscaling utils in e2e

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/kind feature
/sig testing

**What this PR does / why we need it**:

`test/e2e/common` is a mixture of tests (`test/e2e/common/downward_api.go`) and utility code (`test/e2e/common/events.go`). It would be nice to refactor it so that the utility code can be imported without also importing the tests. Most likely a better place for the utility code is under `test/e2e/framework`.

**Which issue(s) this PR fixes**:

part of #83937

**Special notes for your reviewer**:

/cc @pohly @alejandrox1 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by oomichi** [comment]
This seems necessary to be rebased.

/cc @oomichi

**Comment by danielqsj** [comment]
@oomichi PR rebased. could you help review it ? thanks

**Comment by oomichi** [comment]
Thanks for doing this.

/lgtm

**Comment by danielqsj** [comment]
@pohly @alejandrox1 : could you help review this PR and give some guide ? thanks

**Review by oomichi — COMMENTED** [review]
/approve

**Pull request merged**
