### PR TITLE
Remove apelisse from dep-approvers

### PR DESCRIPTION
**Pull request by apelisse**
I haven't been able to take the time to do it, and it basically became spam in my inbox ... :-/

cc @thockin @BenTheElder 

/kind flake

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Slacker!  :)

/lgtm
/approve

**Comment by apelisse** [comment]
How has the load been? Should I help find someone else to replace me?

**Comment by thockin** [comment]
It's fine, we'll figure it out.  I have not been doing a ton myself -
others are getting there first.

**Pull request merged**
