### PR TITLE
Fix golint failures in cmd/kubeadm/app/util/system

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Fix golint failures in cmd/kubeadm/app/util/system

**Which issue(s) this PR fixes**:

Ref: #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
@SataQiu thanks.
/lgtm
/approve

**Comment by fejta** [comment]
you're clearly speaking my language with a cat gif

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Comment by neolit123** [comment]
> you're clearly speaking my language with a cat gif

lol

**Pull request merged**
