### PR TITLE
Automated cherry pick of #117388: Re-work logic in shouldSyncUpdatedNode

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
Cherry pick of #117388 on release-1.27.

#117388: Re-work logic in shouldSyncUpdatedNode

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fix a 1.25 regression: [KCCM] service controller: change the cloud controller manager to make `providerID` a predicate when synchronizing nodes. This change allows load balancer integrations to ensure that  the `providerID` is set when configuring load balancers and targets.
```

### CODE REVIEW

**Comment by dims** [comment]
backporting to fix a bug

/approve
/lgtm

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

/cc @kubernetes/release-managers

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
