### PR TITLE
fix err message in namespace_policy

### LINKED ISSUE #49541: err message in namespace_policy
**Is this a BUG REPORT or FEATURE REQUEST?**:BUG REPORT

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
the err message in addNamespaceRoleBinding is wrong.

ref to #46685

### PR DESCRIPTION
**Pull request by xilabao**
**What this PR does / why we need it**:

**Which issue this PR fixes**: fixes #49541

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ericchiang** [comment]
@k8s-bot ok to test

/lgtm

**Comment by xilabao** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this
@k8s-bot pull-kubernetes-node-e2e test this
@k8s-bot pull-kubernetes-unit test this

**Comment by xilabao** [comment]
@liggitt can you approve?

**Comment by xilabao** [comment]
@liggitt @ericchiang ptal

**Pull request merged**
