### PR TITLE
test images: retrigger busybox image building

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/sig testing
/kind cleanup
/priority important-soon

#### What this PR does / why we need it:

The previous job failed because the windows-servercore-cache image was not built yet.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mkumatag** [comment]
I have seen people re-triggering the postsubmit jobs itself for building the images without any code changes, I'm wondering if you can get the right level permission to do so - @chaodaiG, because you own most of the image building process for these `test/images`

**Comment by claudiubelu** [comment]
> 
> 
> I have seen people re-triggering the postsubmit jobs itself for building the images without any code changes, I'm wondering if you can get the right level permission to do so - @chaodaiG, because you own most of the image building process for these `test/images`

I can rerun the same prow jobs, but I can't if they're already gone from prow. The last time the busybox image job ran was on friday night, and it's no longer in prow.

**Review by chaodaiG — APPROVED** [review]
this might be the easiest way building this image

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
