### PR TITLE
Revert "Merge pull request #118895 from RyanAoh/kep-1860"

### PR DESCRIPTION
**Pull request by marosset**
This reverts commit 890a6c8f70d2e0f45b3692d34a6df1ecb6d8335b, reversing changes made to 4f60a8d493ab9571eb328b9d98da477a50bc7446.

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This reverts https://github.com/kubernetes/kubernetes/pull/118895 which accidently merged for 1.28.
Slack discussion - https://kubernetes.slack.com/archives/CJH2GBF7Y/p1691553548475109

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
/sig release network
/cc @jeremyrickard @gracenng @leonardpahlke

### CODE REVIEW

**Comment by aojea** [comment]
/lgtm

for sig network

**Comment by jpbetz** [comment]
/approve
for sig api-machinery

**Pull request merged**
