### PR TITLE
vender upgrade codedellemc/goscaleio to release v0.1.0

### LINKED ISSUE #79234: Update vendored dependencies to a released version instead of random SHA(s)
Algorithm:
- Look at go.mod, look for dependencies with [Pseudo-versions](https://golang.org/cmd/go/#hdr-Pseudo_versions)
- Look at the github repo of the dependencies, find a released tag closest to the SHA (but higher than the SHA)
- Look at the commits in the range and review with the [guidelines](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/godep.md#justifications-for-an-update) in mind
- NOTE that the version bump suggestions below are just that ("suggestions"), please try to find a closer or better match of release tags based on the guidelines above.

Here's the situation as of June 20, 2019 using [some scripts](https://gist.github.com/dims/c0857b86441442b15852a4c2355db130) to highlight possibilities
- [x] github.com/codedellemc/goscaleio ( filed https://github.com/kubernetes/kubernetes/pull/80321 )
- [ ] github.com/docker/libnetwork ( [from a9cd636e3789 to possibly v0.6.0-rc1 or newer](https://github.com/docker/libnetwork/compare/a9cd636e3789...v0.6.0-rc1) )
- [ ] github.com/gogo/protobuf ( [from 342cbe0a0415 to possibly v1.0.0 or newer](https://github.com/gogo/protobuf/compare/342cbe0a0415...v1.0.0) )
- [x] github.com/gophercloud/gophercloud( [from c818fa66e4c8 to possibly v0.2.0 or newer](https://github.com/gophercloud/gophercloud/compare/c818fa66e4c8...v0.2.0) )
- [x] github.com/heketi/heketi ( [from 558b29266ce0 to possibly v9.0.0 or newer](https://github.com/heketi/heketi/compare/558b29266ce0...v9.0.0) )
- [ ] github.com/libopenstorage/openstorage ( [from 093a0c388875 to possibly v8.0.0 or newer](https://github.com/libopenstorage/openstorage/compare/093a0c388875...v8.0.0) )
- [ ] github.com/opencontainers/runc ( [from f000fe11ece1 to possibly v0.1.1 or newer](https://github.com/opencontainers/runc/compare/f000fe11ece1...v0.1.1) )
- [ ] github.com/prometheus/common ( [from 4724e9255275 to possibly v0.6.0 or newer](https://github.com/prometheus/common/compare/4724e9255275...v0.6.0) )
- [x] github.com/seccomp/libseccomp-golang ( [from 1b506fc7c24e to possibly v0.9.1 or newer](https://github.com/seccomp/libseccomp-golang/compare/1b506fc7c24e...v0.9.1) )
- [ ] github.com/vishvananda/netlink ( [from b2de5d10e38e to possibly v1.0.0 or newer](https://github.com/vishvananda/netlink/compare/b2de5d10e38e...v1.0.0) )
- [ ] google.golang.org/api ( [from 583d854617af to possibly v0.6.0 or newer](https://google.golang.org/api/compare/583d854617af...v0.6.0) )
- [x] github.com/docker/distribution (filed https://github.com/kubernetes/kubernetes/pull/80721)

### PR DESCRIPTION
**Pull request by Moriadry-zz**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

 /kind bug
 /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #
fix https://github.com/kubernetes/kubernetes/issues/79234

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/assign @msau42 @saad-ali 

Michelle, Saad, 
Do we have any owners for this code?

**Comment by msau42** [comment]
/assign @codenrhoden @vladimirvivien 

can you help find the right reps for scaleio?

**Comment by Moriadry** [comment]
@msau42 hi, I found the https://github.com/codedellemc/goscaleio has rename to https://thecodeteam/goscaleio. so I use v thecodeteam/goscaleio v0.1.0 directly. 

With all the tests passed, It seems to work correctly.

**Comment by vladimirvivien** [comment]
@msau42 PR author did the right thing pointing to the github.com/thecodeteam/goscaleio as this was the last maintained repo.  However, that code is not actively being developed or updated.

**Comment by msau42** [comment]
@vladimirvivien do you know who is the current owner of the scaleio plugin?

**Comment by codenrhoden** [comment]
I know I don't... I'm not sure if people at DellEMC are maintaining that in-tree plugin or not. I do know that ScaleIO as a whole was rebranded to VxFlex (OS?), and there is a corresponding CSI driver: https://github.com/dell/csi-vxflexos.

I cannot comment on the state of that driver. But it's good that the timer for deprecation of in-tree plugins has started. :)

**Comment by vladimirvivien** [comment]
@msau42 ditto here. I don't have a name to offer. There is also this repo from Dell https://github.com/dell/goscaleio maintained by @eric-young.

**Comment by astripei70** [comment]
Hi, 
The new location goscaleio location is https://github.com/dell/goscaleio 
Also, VxFlexOS (aka ScaleIO) driver can be found here https://github.com/dell/csi-vxflexos.
Please feel free to reach me for any Dell EMC CSI related questions, queries or suggestions as I am a product manager for Dell EMC CSI drivers.

**Comment by msau42** [comment]
@astripei70 thank you! Are you the right person to review this change to the in-tree scaleio plugin?

**Comment by saad-ali** [comment]
Thanks @astripei70 can you verify that you are ok with this PR, if so we can go ahead and approve/merge it.

**Comment by astripei70** [comment]
@saad-ali technically https://github.com/thecodeteam/csi-scaleio repo is deprecated. It is out there only for the earlier released plugin. Any chance you could use https://github.com/dell/goscaleio instead?

**Comment by msau42** [comment]
@astripei70 is it possible to find the owner of this plugin from your team to make the change?

**Comment by astripei70** [comment]
@msau42 We reviewed the changes and approve them.

**Comment by msau42** [comment]
@Moriadry can you squash your commits?

/approve

**Comment by msau42** [comment]
@astripei70 let's also work on getting members of your team memberships in kubernetes/kubernetes so that they can be the maintainers of this scaleio plugin.

**Comment by astripei70** [comment]
@msau42 Certainly, I could do this. Also, there is a discussion to deprecate in-tree ScaleIO driver https://github.com/kubernetes/kubernetes/commit/7fa6fc722675105af043017cc738e1e28166f3b6
Perhaps this would eliminate the need to support goscaleio starting 1.16. Please advise.

**Comment by msau42** [comment]
@astripei70 i've opened up https://github.com/kubernetes/kubernetes/issues/80819 to continue discussion on this

**Comment by Moriadry** [comment]
@msau42 done

**Comment by Moriadry** [comment]
@vladimirvivien 
Hi, What's going on now, Can you approve it?

**Comment by dims** [comment]
/assign @liggitt @smarterclayton 

Jordan, Clayton, this needs root approval. same license, repo moved.

**Pull request merged**
