### PR TITLE
[pkg/printers/internalversion/import_known_versions]: fixup typo

### PR DESCRIPTION
**Pull request by ideapark**
Signed-off-by: Zhou Peng <p@ctriple.cn>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ideapark** [comment]
sig/kubectl

**Comment by dims** [comment]
/ok-to-test
/approve
/lgtm

NOTE: one character typo in comment. looks good to me.

**Pull request merged**
