### PR TITLE
kubeadm: fix missing error handling

### PR DESCRIPTION
**Pull request by bart0sh**
**What type of PR is this?**

 /kind cleanup

**What this PR does / why we need it**:

Handled error returned from CertificateSigningRequests().Get()

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
/lgtm
thanks @bart0sh 
cc @liztio

**Review by dixudx — APPROVED** [review]
/lgtm

**Review by fabriziopandini — APPROVED** [review]
@bart0sh thanks for this PR!
/approve
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
@bart0sh thanks for this PR!
/approve
/lgtm

**Review by fabriziopandini — APPROVED** [review]
@bart0sh thanks for this PR!
/approve
/lgtm

**Comment by bart0sh** [comment]
@fabriziopandini, @timothysc This pr was approved 2 times but not yet merged for some reason. Can you help to get it merged? Thanks.

**Comment by nikhita** [comment]
@bart0sh It's in the merge "pool". It's getting tested one more time and will get automatically merged if the tests pass again.

- https://prow.k8s.io/pr?query=is%3Apr+repo%3Akubernetes%2Fkubernetes+author%3Abart0sh+head%3APR0035-kubeadm-certsapi-handling-err

- https://prow.k8s.io/tide

**Comment by fabriziopandini** [comment]
@bart0sh I unblocked this PR one hour ago (some label missing due to yesterday github issues)
Now I'm monitoring merge queue to get this merged asap

**Comment by bart0sh** [comment]
@fabriziopandini, @nikhita Ah, I see now. Thank you for your help!

**Pull request merged**
