### PR TITLE
Update i18n tools and process.

### PR DESCRIPTION
**Pull request by brendandburns**
@fabianofranz @zen @kubernetes/sig-cli-pr-reviews 

This is an update to the translation process based on feedback from folks.

The main changes are:
   * `msgctx` is being removed from the files.
   * String wrapping and string extraction have been separated.
   * More tools from the `gettext` family of tools are being used
   * Extracted strings are being sorted for canonical ordering
   * A `.pot` template has been added.

### CODE REVIEW

**Comment by fabianofranz** [comment]
@k8s-bot bazel test this

**Comment by fabianofranz** [comment]
@k8s-bot verify test this

**Comment by brendandburns** [comment]
@k8s-bot cross build this

**Comment by brendandburns** [comment]
self LGTM, given approve.

**Comment by brendandburns** [comment]
removed self-lgtm since apparently the approve is now coming automatically b/c I'm an owner, not because someone else approved...

**Comment by brendandburns** [comment]
Switching to @zen for the review, since he expressed a bunch of opinions about the process...

**Comment by brendandburns** [comment]
friendly ping to @zen for a review...

Thanks

**Comment by brendandburns** [comment]
Friendly ping to @zen (or @fabianofranz in case he is willing to review...)

Thanks!
--brendan

**Comment by zen** [comment]
Sorry @brendandburns I was on PTO entire week.

**Comment by brendandburns** [comment]
@zen rebased. Any chance I can get a quick review?

Thanks!
--brendan

**Comment by zen** [comment]
/lgtm

---

Reviewed 7 of 12 files at r1, 3 of 7 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[hack/update-translations.sh, line 17 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/40665#-KdaG-bhVnSkVidBaWYZ:-KdaG-biOI14CL3rFieF:b-bxwlms) ([raw file](https://github.com/kubernetes/kubernetes/blob/c7c0106dd72e579190f59ff868690e6a382da441/hack/update-translations.sh#L17)):*
> ```Shell
> # limitations under the License.
> 
> KUBECTL_FILES="pkg/kubectl/cmd/*.go pkg/kubectl/cmd/*/*.go"
> ```

I would actually start thinking about parametrising this. It would be good for it to be generic.

---

*[hack/update-translations.sh, line 29 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/40665#-KdaHHtfeDYPK5uPoNhZ:-KdaHHtfeDYPK5uPoNh_:b-n543ov) ([raw file](https://github.com/kubernetes/kubernetes/blob/c7c0106dd72e579190f59ff868690e6a382da441/hack/update-translations.sh#L29)):*
> ```Shell
> rm tmp.pot
> 
> for x in translations/*/*/*/*.po; do
> ```

Usually there should be control over those to stages. It would be better if generating POT and then generating MO are separate invocations. Good candidate for parametrisation as well

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/40665#-:-KdaHw5lPyqGblO_goId:b-8ks5qa)*

**Comment by fabianofranz** [comment]
@k8s-bot gci gke e2e test this
@k8s-bot verify test this
@k8s-bot gce etcd3 e2e test this
@k8s-bot gci gce e2e test this

**Comment by fabianofranz** [comment]
@zen Actually I think this needs a squash of the last 2 commits before getting merged. ;) @brendandburns

**Comment by zen** [comment]
Sorry, I reviewed it squashed already.

**Comment by fabianofranz** [comment]
@zen removed the lgtm label so that @brendandburns has a chance to squash.

**Comment by brendandburns** [comment]
@fabianofranz I squashed the last two commits. I can squash it all down to 1 commit too if you'd rather.

@zen comments addressed.

Thanks!

**Comment by fabianofranz** [comment]
@brendandburns I'd say either squash it down to 2 or 1 commits, no preference. Tks!

**Comment by brendandburns** [comment]
@fabianofranz squashed to 1 commit and rebased.

**Comment by fabianofranz** [comment]
/lgtm
@brendandburns tks!

**Comment by brendandburns** [comment]
@k8s-bot kops aws e2e test this

**Comment by brendandburns** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by brendandburns** [comment]
@k8s-bot kops aws e2e test this

*sigh*

**Pull request merged**
