### PR TITLE
cleanup: sync testdata as CronJobTimeZone is GAed

### PR DESCRIPTION
**Pull request by pacoxu**
/kind cleanup
/release-note-none

follow up of https://github.com/kubernetes/kubernetes/pull/115904
/assign @soltysh 
a tiny change.

### CODE REVIEW

**Comment by soltysh** [comment]
I'm not sure this is required, that's only testdata, I'll let @apelisse have the final saying
/assign @apelisse

**Comment by apelisse** [comment]
Yeah, that's completely irrelevant, but that's fine.
/lgtm
/approve

**Pull request merged**
