### PR TITLE
Automated cherry pick of #94002 upstream release 1.17 

### PR DESCRIPTION
**Pull request by wojtek-t**
Cherry pick of #94002 on release-1.17
#94002 : Fix bug for inconsistent lists served from etcd

/kind bug

### CODE REVIEW

**Comment by wojtek-t** [comment]
@kubernetes/release-managers - for cherrypick approval

**Comment by cpanato** [comment]
/hold

saw now, `pull-kubernetes-integration` is failing all the time

**Comment by liggitt** [comment]
> saw now, pull-kubernetes-integration is failing all the time

that was https://github.com/kubernetes/kubernetes/issues/94184 and was resolved

https://testgrid.k8s.io/sig-release-1.17-blocking#integration-1.17&width=5

/hold cancel

**Pull request merged**
