### PR TITLE
feat(sample-controller): use UpdateStatus

### PR DESCRIPTION
**Pull request by FrankYang0529**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
`CustomResourceSubresources` feature gate has been GA from 1.16, so we use `UpdateStatus` for status only change and remove TODO in the test case.

#### Which issue(s) this PR fixes:
NONE

#### Does this PR introduce a user-facing change?
NONE

### CODE REVIEW

**Comment by munnerz** [comment]
Seems like this was just leftover from [here](https://github.com/kubernetes/kubernetes/pull/60021#discussion_r170315001) and can now be enabled 😄 thanks!

/ok-to-test
/release-note-none
/approve

**Comment by FrankYang0529** [comment]
It looks like the unit test has a race condition in `pkg/controller/statefulset`, but I can pass test cases with `make test WHAT=./pkg/controller/statefulset GOFLAGS=-v` in my environment.

/retest

**Pull request merged**
