### PR TITLE
cluster/juju: code cleanup in return-node-ips.py

### PR DESCRIPTION
**Pull request by falcon78921**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Minor cleanup. Utilizes ``print()`` function to better align with Python3.
Signed-off-by: James McClune <jmcclune@mcclunetechnologies.net>

**Which issue(s) this PR fixes**:

``N/A``

**Special notes for your reviewer**:

``N/A``

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by falcon78921** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
>  **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please email the CNCF helpdesk: [helpdesk@rt.linuxfoundation.org](mailto:helpdesk@rt.linuxfoundation.org)

Signed, sealed, delivered...

**Comment by janitha09** [comment]
python2 vs python3 
as an example
https://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html#the-print-function
Could you use a virtualenv?

**Comment by falcon78921** [comment]
I'm just following up on this PR. If there's anything that needs fixed, please let me know :)

**Comment by falcon78921** [comment]
Closing due to #76628

**Pull request closed without merging**
