### PR TITLE
Added nodeAffinity in validation error msg.

### PR DESCRIPTION
**Pull request by k82cn**
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # N/A

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by k82cn** [comment]
@kubernetes/sig-api-machinery-api-reviews

**Comment by k82cn** [comment]
ping for comments :).

**Comment by k82cn** [comment]
ping for approval :).

**Comment by k82cn** [comment]
ping for approval :).

**Comment by k82cn** [comment]
@kubernetes/sig-api-machinery-pr-reviews

**Comment by k82cn** [comment]
ping for approval :).

**Comment by sttts** [comment]
/assign @liggitt

for approval.

**Comment by k82cn** [comment]
rebased, ping for approval :).

**Comment by k82cn** [comment]
ping :)

**Comment by k82cn** [comment]
ping for lgtm/approve :).

**Comment by kevin-wangzefeng** [comment]
/lgtm
@liggitt can you help to approve this? Thanks.

**Comment by liggitt** [comment]
no release note needed... this is just correcting the field path in the validation error
/lgtm

**Pull request merged**
