### PR TITLE
Make go version requirements clearer

### PR DESCRIPTION
**Pull request by thockin**
@dchen1107 we should do this same thing for docker version.  This doc says docker 1.3!!

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM

**Comment by wojtek-t** [comment]
@thockin - it seems that some tests are failing:

/home/travis/gopath/src/github.com/kubernetes/kubernetes/docs/getting-started-guides/mesos.md
----
md-links:
contents were modified
FAIL: changes needed but not made due to --verify

**Comment by thockin** [comment]
typo fixed

**Comment by thockin** [comment]
@k8s-bot unit test this please

**Comment by thockin** [comment]
@k8s-bot unit test this please

**Comment by dchen1107** [comment]
LGTM and ACK on docker version updates!

**Pull request merged**
