### PR TITLE
remove default authz ModeAlwaysAllow

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Do not set default ModeAlwaysAllow authorization mode.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
> @deads2k Indeed many test case failed just for this, should I fix them or just keep the AlwaysAllow authz mode there?

Is it exposed as a default in the `kube-apiserver` command?  We don't keep defaults in our code to make  tests easy, we keep defaults in our code to make "normal" objects match user expectations.  If it is only for testing purposes, it should be changed.

**Comment by hzxuzhonghu** [comment]
OK, got it, will work on fixing test cases.

**Comment by hzxuzhonghu** [comment]
>Is it exposed as a default in the kube-apiserver command?

No, not any words at all.

**Comment by hzxuzhonghu** [comment]
flake case

/retest

**Comment by deads2k** [comment]
```
hyperkube kube-apiserver --help 2>&1 | grep authorization-mode
      --authorization-mode string                               Ordered list of plug-ins to do authorization on secure port. Comma-delimited list of: AlwaysAllow,AlwaysDeny,ABAC,Webhook,RBAC,Node. (default "AlwaysAllow")
```

Looks like it may be a default value.  How about starting a thread on the mailing list about changing the default to RBAC.  It's stable now and used in all our e2e tests.

**Comment by hzxuzhonghu** [comment]
>Looks like it may be a default value

 I think you use an old version,  newest does not saying that default https://github.com/kubernetes/kubernetes/blob/master/pkg/kubeapiserver/options/authorization.go#L93-L95. 

>How about starting a thread on the mailing list about changing the default to RBAC.

That's ok.

**Comment by liggitt** [comment]
> I think you use an old version, newest does not saying that default

It is the current default. The help text prints the current value of the Modes variable, which is AlwayAllow by default

**Comment by hzxuzhonghu** [comment]
>It is the current default. The help text prints the current value of the Modes variable, which is AlwayAllow by default

Yes, it is the default behavior indeed.

**Comment by hzxuzhonghu** [comment]
ping @liggitt @deads2k

**Comment by liggitt** [comment]
changing default behavior is not something we typically do, especially for something that fundamentally changes the way you interact with a cluster like this.

A good point at which to improve the default behavior would be when we move to starting the apiserver from a config file ([proposal in progress](https://github.com/kubernetes/community/blob/master/keps/sig-cluster-lifecycle/0014-20180707-componentconfig-api-types-to-staging.md#k8sioapiserver-changes)), similar to what we did for the kubelet in https://github.com/kubernetes/kubernetes/pull/59666.

I'd probably recommend the authorization mode be explicitly specified when starting from a config file, rather than defaulting to permissive mode or a particular authorizer.

**Comment by hzxuzhonghu** [comment]
Thanks @liggitt for your clarification.

**Pull request closed without merging**
