### PR TITLE
Optimize log output for job controller

### PR DESCRIPTION
**Pull request by 249043822**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
The log didn't output clear job identity
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by janetkuo — APPROVED** [review]

**Comment by 249043822** [comment]
/ping @janetkuo, Hi, Should this pr lable LGTM?

**Pull request merged**
