### PR TITLE
Fix broken links in kubeadm after moving proposals to subdirs

### LINKED ISSUE #918: Organize Design Proposals Folder
The design proposals folder is getting a little out of hand, and we could do a few things to help improve it.

- [ ] In lieu of sig subdirs, create functional area subdirs with clear ownership
- [ ] Create OWNERS files in those subdirs
- [ ] Disambiguate proposals from accepted changes as tracked by #914

### PR DESCRIPTION
**Pull request by huzhengchuan**
**What this PR does / why we need it**:
fix incorrect links in kubeadm after kubernetes/community#1010

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes  kubernetes/community#918

**Special notes for your reviewer**:
CC @bgrant0607
**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by bgrant0607** [comment]
@huzhengchuan Thanks for fixing these. It looks like you have the right idea, so you don't need to cc me on all the PRs. Please cc the relevant SIG pr-reviews team. @kubernetes/sig-cluster-lifecycle-pr-reviews in this case. (Looks like there are no cloudprovider teams yet.)

**Review by luxas — APPROVED** [review]
/lgtm

**Comment by luxas** [comment]
> (Looks like there are no cloudprovider teams yet.)

@bgrant0607 I'd/We'd like to change that, but depend on someone with the privs.

**Comment by huzhengchuan** [comment]
/assign @mikedanese  
can you help me review the fix?  @mikedanese

**Comment by huzhengchuan** [comment]
ping  @luxas  could you please help approve this PR?

**Review by luxas — APPROVED** [review]
/lgtm

**Pull request merged**
