### PR TITLE
WIP - Migrate Ginkgo from v1 to v2

### PR DESCRIPTION
**Pull request by chendave**
With the GA of v2, v1 has been formally deprecated

We can remove the workaround due to this issue: https://github.com/onsi/ginkgo/issues/222, which has been addressed in v2.

Signed-off-by: Dave Chen <dave.chen@arm.com>

#### What type of PR is this?
/kind deprecation

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
this is not straightforward, you have more info in https://github.com/kubernetes/kubernetes/issues/107936#issuecomment-1029244729

**Comment by chendave** [comment]
@aojea thanks for your information! 

We do have some work to do to make v2 ready in k8s.

**Comment by aojea** [comment]
> @aojea thanks for your information!
> 
> We do have some work to do to make v2 ready in k8s.

This PR has it working https://github.com/kubernetes/kubernetes/pull/105147/ , but the reporters need to be adapted, that is the most complex part

**Comment by chendave** [comment]
> This PR has it working https://github.com/kubernetes/kubernetes/pull/105147 , but the reporters need to be adapted, that is the most complex part

Got you, will read it through!

**Comment by aojea** [comment]
just an advice, use different commits for different things , update vendor, modify this,, .... or this will hard to review and you'll get lost on the dependency nightmare

**Comment by chendave** [comment]
superseded by https://github.com/kubernetes/kubernetes/pull/109111

**Pull request closed without merging**
