### PR TITLE
Update controller manager configuration field comments for consistency

### PR DESCRIPTION
**Pull request by andybradshaw**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**: This PR improves the consistency of the field comments on the controller manager configuration. There are still some inconsistencies around the fields in the top-level `KubeControllerManagerConfiguration`, but they are at least internally consistent.

**Does this PR introduce a user-facing change?**: None

### CODE REVIEW

**Comment by andybradshaw** [comment]
To add a little more context to this change, while working on https://github.com/kubernetes/kubernetes/pull/69937, there was discussion around fix the controller manager configuration to pass the openapi-gen validation. That change is now blocked on this PR, since it would be adding to the list of api violations. Not sure who to assign this to, but want someone to take a look at this so both PRs don't become too stale.

/assign @thockin

**Comment by thockin** [comment]
This is something I am not sure about. 

We generate docs from comments, and the docs cover the "json-style" names (leading lower-case), while Go grumps about it.   Should we be capitalizing the comments?

@lavalamp @mbohlool I am not sure who to ask

**Comment by andybradshaw** [comment]
Okay... might make a separate PR for dealing with the json tags (since that's the blocking part) and let the comment name change sit here for discussion.

**Comment by lavalamp** [comment]
Absent json tags, the capitalized version of the word *is* what would be serialized. So, before this change it's doubly wrong. Now it's only singly wrong, IMO a 50% improvement :) When json tags are added, then the comment will need to be updated again.

I understand these types aren't serialized yet.

@liggitt may have something to add.

/lgtm
/approve

**Comment by lavalamp** [comment]
I double checked and saw some fields are getting a `json:"-"` moniker now. un-approving, let's think about that a bit more.

**Comment by lavalamp** [comment]
Yeah, if we can move the json:"-" tags into a separate PR, I think the comment changes are strictly an improvement (more accurately reflect reality). The json tag changes would definitely break an object if we're accidentally serializing it somewhere; also I don't understand why they were only added some places.

**Comment by liggitt** [comment]
> The json tag changes would definitely break an object if we're accidentally serializing it somewhere

Controller manager doesn't support reading from config files yet. I'm fine with adding the json tag to quiet the API linter, or leaving the violation notices in place until https://github.com/kubernetes/community/blob/master/keps/sig-cluster-lifecycle/0014-20180707-componentconfig-api-types-to-staging.md completes.

The benefit of adding the `-` json tag now is that it would prevent accidentally introducing serialization/deserialization use in the meantime, which only seems like an upside to me.

**Comment by andybradshaw** [comment]
@liggitt what's the status of that KEP? It looks like it was targeted for 1.12, but that didn't happen. If its something we expect to land soon-ish, should probably hold off on this.

Tests broke because we are removing the implicit serialization format of the controllers (expected).

**Comment by liggitt** [comment]
> @liggitt what's the status of that KEP? It looks like it was targeted for 1.12, but that didn't happen. If its something we expect to land soon-ish, should probably hold off on this.

1.12 accomplished the code movement it set out to do. The priority was around the components that currently do read config from files (kube-scheduler, kube-proxy and kubelet).

@sttts @luxas can give better status about the work for the other components.

**Comment by liggitt** [comment]
unit test failures look legitimate, json:"-" breaks round trip tests, etc.

making temporary changes to satisfy those tests seems like more scope creep than we want for this

**Comment by liggitt** [comment]
closing per https://github.com/kubernetes/kubernetes/pull/70565#issuecomment-451564513

the side-effects of the comment changes caused more problems than they solved until these fields are actually made serializable

/close

**Pull request closed without merging**
