### PR TITLE
Migrate some integration tests from cmd/integration to test/integration to use framework

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #25940

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please, issue: #27179

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please, issue: #IGNORE (tests didn't start)

**Comment by wojtek-t** [comment]
@mikedanese - if you're ok with this change (can you please take a quick look?), I will migrate the other tests too in a separate PR(s).

**Comment by mikedanese** [comment]
LGTM

**Comment by wojtek-t** [comment]
Thanks @mikedanese - I will migrate the remaining tests later this week or next week.

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please, issue: #IGNORE (tests didn't start)

**Comment by mikedanese** [comment]
Test cleanup is v1.3 worthy.

**Comment by wojtek-t** [comment]
Thanks @mikedanese - once this PR is merged, I will rebase the other PR I have in the same category (also assigned to you).

**Pull request merged**
