### PR TITLE
Avoid closing a file twice in LaunchTempFile in editor

### PR DESCRIPTION
**Pull request by xuhdev**
There is a `defer f.Close()` call in `LaunchTempFile`, but an explicit
`f.Close()` is called a few lines below. Move this deferred `f.Close()`
call to the `if` block to avoid closing `f` twice.

The [doc of Close()](https://golang.org/pkg/os/#File.Close) says:

> Close will return an error if it has already been called.

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

See the top of the comment.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by rikatz** [comment]
Hey @xuhdev and thanks for your PR.

I'm taking a look here, although the doc says that Close() will return an error, we are not checking the error (like err := f.Close())

This way, my guess is that the code is correct, following it here:
* puts f.Close() on the stack of things to be executed when the function returns
* if an error occurs on io.Copy, the path is removed and the file descriptor is closed by the deferred function on the stack (the function is returned) <- Can we have an error here, trying to remove something that's opened by the function? Need to test @dougsland 
* If no error occurs on io.Copy, it tries to close the file so it can be used again later
* Finally, when the function ends/returns, that deferred f.Close() is called again. But we don't check if an error occurs so if some error occurs (and as per docs, it can only occurs if you try to close a file again, so it's not 'dangerous' IMO)

I will have to try if the os.Remove can be improved but otherwise, I want some other opinion if we really need to care about this!

Thanks once more for your contribution!! :)

**Comment by xuhdev** [comment]
> Finally, when the function ends/returns, that deferred f.Close() is called again. But we don't check if an error occurs so if some error occurs (and as per docs, it can only occurs if you try to close a file again, so it's not 'dangerous' IMO)

@rikatz I looked into this again, and I now believe this may be dangerous. If `f.Close()` is called twice, chances are the second call may inadvertently close a different file, at least on POSIX-compliant systems. The POSIX [open document](https://pubs.opengroup.org/onlinepubs/007904875/functions/open.html) says:

> The open() function shall return a file descriptor for the named file that is the lowest file descriptor not currently open for that process.

Imagine that between the two `f.Close()` calls a new file is opened in a different thread and the file descriptor is reused. The second call may close that newly opened file inadvertently. This is likely difficult to reproduce, but looks like it can happen for a long-running system.

**Comment by rikatz** [comment]
/cc
/assign

Will take a look :)

**Comment by xuhdev** [comment]
As a side note, same issue happens at https://github.com/kubernetes/kubernetes/blob/5b0a2c3a29f6b5392e0f8f94ba5669bdc9eb73f6/staging/src/k8s.io/kubectl/pkg/cmd/cp/cp.go#L489

**Comment by rikatz** [comment]
/ok-to-test

Will answer this tomorrow, for now let's see what CI thinks about this :)

**Comment by rikatz** [comment]
Hey @xuhdev sorry for the late response. I'll take the day off tomorrow to review all the PRs that are on my queue :D

**Review by rikatz — CHANGES_REQUESTED** [review]
As you pointed that the cp command suffer from the same problem, can you please correct there?

Thanks!!!

**Comment by rikatz** [comment]
@xuhdev good catch and good tests :)

Can you correct also on the place you pointed?

Thanks!

**Comment by xuhdev** [comment]
Done!

**Comment by rikatz** [comment]
thanks.

will wait all tests to pass, but looks solid and good to me :)

**Review by rikatz — APPROVED** [review]
/lgtm
We need to wait until code freeze ends to get this merged :)
Thank you

**Comment by xuhdev** [comment]
@rikatz Should this be ready to merge now :)

**Comment by xuhdev** [comment]
What would be the status of this PR?

**Comment by rikatz** [comment]
Hey it's on my list to review this week :)

**Comment by xuhdev** [comment]
@rikatz :)

**Pull request closed without merging**
