### PR TITLE
Allow Kubelet to watch for changes to pods scheduled on it

### PR DESCRIPTION
**Pull request by smarterclayton**
This replaces Kubelet config loading a watch call on `/watch/pods`.  It depends on Watch to inform of new changes.

This is one step towards allowing the kubelet to be isolated from direct access to etcd which provides better security, and allows us to version the API and schema from the apiserver using schema conversions.  In the future we can add more restrictive minion authorization (minion X is scoped to retrieve only information it needs).

Implements part of #860

### CODE REVIEW

**Comment by smarterclayton** [comment]
Rebased again, found some bugs with how the kubelet server is looking up pods by name.  Stats lookup is still not using namespace #3204, and looks like container logs are being chosen randomly among recent attempts #3205.

**Comment by smarterclayton** [comment]
Would really appreciate some review from the various folks, unless we want to totally nuke this and wait for Eric's wider reaching change.  Rebasing tends to be a bit hairy.

**Comment by lavalamp** [comment]
I do apologize for sitting on this for so long :/

I think, since @erictune is back and is promising to work on making kubelet read pods directly, that it makes sense to just wait for that change to happen--it doesn't seem great to add a REST object that we plan to get rid of in a week or two.

However I would like it if "Watching on invalid label/field selectors should error" would show up in its own PR, that seems useful generally.

**Comment by smarterclayton** [comment]
Extracted other fixes that aren't BoundPods specific in #3270, will leave this here until Eric's changes land and then close it.

**Comment by lavalamp** [comment]
@erictune's change has been merged.

**Comment by erictune** [comment]
for posterity, the last one was: #3376

**Pull request closed without merging**
