### PR TITLE
revert the vsphere change to skydns plugin

### LINKED ISSUE #25020: DNS yaml.in templates assume salt, not sed friendly.
I get the following error when I try to deploy addons to my kubernetes cluster. 
```
Deploying DNS on Kubernetes
yaml: line 21: found character that cannot start any token
```

I am running a 5 node kubernetes cluster on Azure with Ubuntu 14.04.
The cluster itself is up and running.
I tried to debug this issue and the issue seems to be because of skydns-rc.yaml not being in the right format. When I look at deployAddons.sh, this yaml file is generated from a yaml.in file.
I did a diff of these two files and the following is the output:

```
diff ~/kubernetes/cluster/addons/dns/skydns-rc.yaml.in skydns-rc.yaml
11c11
<   replicas: {{ pillar['dns_replicas'] }}
---
>   replicas: 1
86c86
<         - --domain={{ pillar['dns_domain'] }}
---
>         - --domain=cluster.local
105c105
<         - -domain={{ pillar['dns_domain'] }}.
---
>         - -domain=cluster.local.
124c124
<         - -cmd=nslookup kubernetes.default.svc.{{ pillar['dns_domain'] }} 127.0.0.1 >/dev/null
---
>         - -cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null

```

### PR DESCRIPTION
**Pull request by mikedanese**
Fixes #25020

### CODE REVIEW

**Comment by bprashanth** [comment]
IIUC this breaks DNS in the photon provider, which didn't exist anyway till a few days ago, so LGTM assuming we're going to fix that CP at some point in the not too distant future.

**Comment by thockin** [comment]
LGTM, we'll discuss real fixes on a new bug

**Comment by andyzheng0831** [comment]
@mikedanese @thockin do you mind to mark it as p2 to get merged sooner? The Jenkins jobs testing GCI have been hurt by this issue for several days.

**Comment by mikedanese** [comment]
Done.

**Comment by danehans** [comment]
@mikedanese the contrib/ansible project relies on manifests within cluster/addons. This allows contrib/ansible to use the upstream templates as a single source of truth for addon manifests and not duplicate them in contrib/ansible. Is it possible for kubernetes/addons not to contain deployment-tool specific code? I believe this approach will allow the upstream manifests to be deployment tool agnostic in support of https://github.com/kubernetes/kube-deploy

**Comment by andyzheng0831** [comment]
The commit queue looks crazy. This PR has been tested again, again and again. No any test failure but cannot merged. The queue can merge just few PRs in a day.

cc/ @ixdy

**Pull request merged**
