### PR TITLE
avoid kublet crashing and memory leaking when killing pods

### PR DESCRIPTION
**Pull request by yaxinlx**
This improvement is to avoid potential kublet crashing and memory leaking when killing pods.

### CODE REVIEW

**Comment by yaxinlx** [comment]
I signed it!

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
@yaxinlx Did you observe any leaks while running kubelet? That function is never expected to exit since it is in an infinite for loop.

**Comment by yaxinlx** [comment]
@vishh I am studying kubernetes code recently and found this small defect in theory. I really didn't run it. If the for-loop never break, it is no problems here.

**Comment by vishh** [comment]
LGTM.

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
@yaxinlx do you still plan to getting this patch merged? If yes, can you look into the test failure? If not, kindly close it.

**Comment by yaxinlx** [comment]
I closed it. However, as podKiller is called in wait.Until, which hints podKiller may exit and be recalled.
So here is still a possibility (although it is very small) to leak memory.

**Pull request closed without merging**
