### PR TITLE
Automated cherry pick of #77475: fix the metainternalversion.List change error

### PR DESCRIPTION
**Pull request by jpbetz**
Cherry pick of #77475 on release-1.14.

#77475: fix the metainternalversion.List change error

### CODE REVIEW

**Comment by jpbetz** [comment]
Switched to using meta.ForEachItem for the cherrypick since pager.ForEachItem doesn't exist in 1.14.

**Comment by jpbetz** [comment]
@tpepper Does this need anything else from me for cherrypick?

**Comment by mohitevishal** [comment]
@jpbetz @tpepper 
Can we please expedite the cherry-pick? It is blocking us on 1.14 and would love to see this resolved soon. Thanks!

**Comment by tpepper** [comment]
no, nothing more needed, @kubernetes/patch-release-team is working through content for next releases and this is in our hopper

**Comment by tpepper** [comment]
@soltysh @janetkuo @erictune this cherry pick is in need of lgtm/approve from the OWNERS

**Comment by nikhita** [comment]
/assign @soltysh 
for approval

**Comment by aerostitch** [comment]
Hi! Any chance we can get that in for 1.14.7? This really blocking the upgrade to 1.14 when you rely a lot on cronjobs & jobs like us. Thanks!

**Comment by 2rs2ts** [comment]
Please merge this, it's killing us 🙏

**Comment by hariharan16s** [comment]
Can you please merge this sooner? Blocked on 1.14 upgrade :(

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by mattfarina** [comment]
@soltysh I take it the hold can be canceled?

**Comment by nikhita** [comment]
@mattfarina the `do-not-merge/cherry-pick-not-approved` label would be removed by the @kubernetes/patch-release-team when they go over the open cherry-picks before cutting 1.14.7 :)

**Comment by liggitt** [comment]
/priority critical-urgent

blocks 1.14 upgrade for cronjob consumers

**Pull request merged**
