### PR TITLE
Add sa as a shorthand for serviceaccounts

### PR DESCRIPTION
**Pull request by luxas**
This shorthand is useful. 
It is also a bit confusing to be able to `kubectl create sa` but not `kubectl get sa`
@vishh

### CODE REVIEW

**Comment by vishh** [comment]
LGTM

**Comment by bgrant0607** [comment]
Tests failed

**Comment by bgrant0607** [comment]
cc @stevekuznetsov @liggitt

**Comment by liggitt** [comment]
Lgtm, but some generated docs probably need updating (try hack/update-all.sh)

**Comment by luxas** [comment]
Updated, ran `hack/update-generated-docs.sh`. Forgot to do it earlier.
BTW, why are the bot adding `kind/old-docs`? 
I know it was used to flag which PRs touched the dirs that were moved to `kubernetes.github.io`, but now I don't see why it's used (especially when only updating man pages and such)

**Comment by deads2k** [comment]
lgtm

**Pull request merged**
