### PR TITLE
Linux bandwidth test doesn't work on Mac

### PR DESCRIPTION
**Pull request by smarterclayton**
@markturansky @brendandburns follow up to #14187

### CODE REVIEW

**Comment by markturansky** [comment]
LGTM.  I wonder why I didn't encounter that ...

**Comment by brendandburns** [comment]
yeah, oddly this works w/o this PR on my mac too...

(but LGTM)

**Comment by smarterclayton** [comment]
i can't think of an explanation for that, which worries me a bit.  I don't think the filename suffix rules are applied to tests, and even from a completely clean setup I see this.  I'm on the brew golang 1.4.2

**Comment by brendandburns** [comment]
the only difference I can think of is that I did a manual golang install instead of brew, but...

**Comment by markturansky** [comment]
I rebased and now get this error, too, when running the tests.  go1.4.2 darwin/amd64

But the fix doesn't actually work for me.

I also noticed there's another one recently introduced in kubelet_test.

```
# k8s.io/kubernetes/pkg/kubelet
_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_test.go:134: undefined: fakeContainerMgrMountInt
_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/runonce_test.go:54: undefined: fakeContainerMgrMountInt

# k8s.io/kubernetes/pkg/util/bandwidth
_output/local/go/src/k8s.io/kubernetes/pkg/util/bandwidth/linux_test.go:77: undefined: tcShaper
_output/local/go/src/k8s.io/kubernetes/pkg/util/bandwidth/linux_test.go:114: undefined: hexCIDR
_output/local/go/src/k8s.io/kubernetes/pkg/util/bandwidth/linux_test.go:126: undefined: asciiCIDR
_output/local/go/src/k8s.io/kubernetes/pkg/util/bandwidth/linux_test.go:190: undefined: tcShaper
_output/local/go/src/k8s.io/kubernetes/pkg/util/bandwidth/linux_test.go:229: undefined: tcShaper
_output/local/go/src/k8s.io/kubernetes/pkg/util/bandwidth/linux_test.go:304: undefined: tcShaper
_output/local/go/src/k8s.io/kubernetes/pkg/util/bandwidth/linux_test.go:335: undefined: makeKBitString
_output/local/go/src/k8s.io/kubernetes/pkg/util/bandwidth/linux_test.go:337: undefined: makeKBitString
_output/local/go/src/k8s.io/kubernetes/pkg/util/bandwidth/linux_test.go:355: undefined: makeKBitString
_output/local/go/src/k8s.io/kubernetes/pkg/util/bandwidth/linux_test.go:356: undefined: makeKBitString
_output/local/go/src/k8s.io/kubernetes/pkg/util/bandwidth/linux_test.go:356: too many errors

```

**Comment by markturansky** [comment]
half right.

Clayton's fix *does* work.  When I manually added the line, I neglected the newline after the build statement.  That is required.

The other error I posted remains but I'll figure out a fix and send along a separate PR.

**Comment by markturansky** [comment]
See https://github.com/kubernetes/kubernetes/pull/14675 for the other fix.

**Comment by dchen1107** [comment]
https://github.com/kubernetes/kubernetes/pull/14563

**Pull request merged**
