### PR TITLE
Fix an incorrectly formatted URL in the 1.10 release note

### PR DESCRIPTION
**Pull request by cimomo**
**What this PR does / why we need it**:
Fix an incorrectly formatted URL in the v1.10 change log. (Have a separate PR in the website repo to fix the release note already imported.)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
/kind cleanup

/assign @thockin 
for approval

**Comment by nikhita** [comment]
/remove-lifecycle stale

/assign @liggitt 
for approval

**Comment by nikhita** [comment]
/hold

@liggitt could you add the `tide/squash` label to this PR and remove the hold after that?

**Comment by liggitt** [comment]
I'm not familiar with that command... it doesn't show up in https://prow.k8s.io/command-help

**Pull request merged**
