### PR TITLE
Reorganize scheduler perf templates

### PR DESCRIPTION
**Pull request by kerthcet**
#### What type of PR is this?
/kind cleanup
/sig scheduling

#### What this PR does / why we need it:
Before:
image

After:
image

I'm bothered by this for a long time, the config yaml is buried with other templates, it's unobviously and hard to find. I used this chance to reorganize them under a new folder `templates`.

/assign @sanposhiho agree with this?

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by AxeZhan** [comment]
+1 for me. Every time I want to change something in `performance-config`, I have to go through these template files😢.

**Review by sanposhiho — COMMENTED** [review]
👍

/lgtm
/approve

**Comment by kerthcet** [comment]
/retest
cc @liggitt

**Comment by NoicFank** [comment]
👍

**Comment by kerthcet** [comment]
Would you mind to approve this @thockin , already approved by scheduling. This is generally a cleanup about files migrations.
I'll keep an eye on the perf-test dashboard after merged.

**Comment by sanposhiho** [comment]
@dims can you please take a look? (trying to ping a different person for build/ approve 😓 )

**Comment by dims** [comment]
@sanposhiho @kerthcet needs rebase!

**Review by sanposhiho — APPROVED** [review]
SIG-Scheduling area

/lgtm
/approve

**Comment by dims** [comment]
/approve
/lgtm

build/ changes look good!

**Pull request merged**
