### PR TITLE
refactor: break down findNodesThatPassPreFilters as more readable

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by denkensk — COMMENTED** [review]
Just personal opinion, it seems the old version is more readable than the new one to me. 😅 
The new version adds a reference pass for `diagnostic`.

**Comment by kerthcet** [comment]
Hi @Huang-Wei , I'd like to get some advices from you for whether this makes sense about hiding details in filling up diagnosis? If not, I will close this one.

**Comment by Huang-Wei** [comment]
> Hi @Huang-Wei , I'd like to get some advices from you for whether this makes sense about hiding details in filling up diagnosis? If not, I will close this one.

@kerthcet I don't quite think it's worth the efforts to exact the logic out because: (1) the new function is not for reusing, and (2) the logic of diagnosis filling is pretty straightforward (~10 lines).

**Comment by kerthcet** [comment]
> > Hi @Huang-Wei , I'd like to get some advices from you for whether this makes sense about hiding details in filling up diagnosis? If not, I will close this one.
> 
> @kerthcet I don't quite think it's worth the efforts to exact the logic out because: (1) the new function is not for reusing, and (2) the logic of diagnosis filling is pretty straightforward (~10 lines).

Got the key point. close then.

**Pull request closed without merging**
