### PR TITLE
scheduler: clean up PodFitsResources

### PR DESCRIPTION
**Pull request by xiang90**
1. group the NumPod checking code block together 
2. remove unnecessary copy. As far as I can see the checking logic use pod as readonly thing, we do not need to copy the pod array.

### CODE REVIEW

**Comment by xiang90** [comment]
We are also using a global variable `FailedResourceType` to communicate errors between two packages. It is really bad, especially when we want to do things in parallel. I plan to clean that up next.

**Comment by HaiyangDING** [comment]
> We are also using a global variable FailedResourceType to communicate errors between two packages. It is really bad, especially when we want to do things in parallel. I plan to clean that up next.

+1 to this. This really needs to be fixed.

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
