### PR TITLE
Automated cherry pick of #70954: Upgrade Stackdriver Logging Agent addon image to 0.6-1.6.0-1

### PR DESCRIPTION
**Pull request by qingling128**
Cherry pick of #70954 on release-1.10.

#70954: Upgrade Stackdriver Logging Agent addon image to 0.6-1.6.0-1

### CODE REVIEW

**Comment by MaciekPytel** [comment]
This seems like a larger version bump in 1.10 than it was on master. Are we sure it's safe to bump it?

**Comment by qingling128** [comment]
@MaciekPytel - v1.10 was effectively on `0.3-1.5.34-1-k8s-1` compared to master which was on `0.5-1.5.36-1-k8s`. And the tests passed. It is fine.

**Comment by MaciekPytel** [comment]
/approve 
For cluster/gce.

**Comment by MaciekPytel** [comment]
This needs your approval @piosz.

**Pull request merged**
