### PR TITLE
Automated cherry pick of #33213

### PR DESCRIPTION
**Pull request by nikhiljindal**
Cherry pick of #33213 on release-1.4.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33252)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
@jianhuiz I have his permission to commit this

**Comment by nikhiljindal** [comment]
cc @madhusudancs

**Comment by madhusudancs** [comment]
LGTM!

**Pull request merged**
