### PR TITLE
Feature rate limiting

### PR DESCRIPTION
**Pull request by daniso123**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by fedebongio** [comment]
Hi @daniso123 thank you for your contribution and enthusiasm. We went through this PR during our Tuesday triage meeting, and it's quite large, but doesn't have any KEP or Issue attached, so it's hard to tell what you are trying to achieve here. 

Would you be able to provide some more details?

Thanks
Fede

**Comment by fedebongio** [comment]
Passed again on this one, holding one more week for an answer.

**Comment by fedebongio** [comment]
If not response, we may close next week.

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Pull request closed without merging**
