### PR TITLE
Updated fluentd configuration to spawn multiple threads for processing

### PR DESCRIPTION
**Pull request by rbuskens**
(by default, fluentd uses a single thread).

@a-robinson @igorpeshansky

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29801)

### CODE REVIEW

**Comment by a-robinson** [comment]
Thanks @rbuskens! LGTM, but would you mind also updating cluster/addons/fluentd-elasticsearch/fluentd-es-image/td-agent.conf while you're here if you think that exports to elasticsearch would also benefit from more threads?

**Comment by a-robinson** [comment]
@k8s-bot ok to test

**Comment by rbuskens** [comment]
Done. PTAL.

**Comment by a-robinson** [comment]
LGTM, thanks!

**Pull request merged**
