### PR TITLE
fix account key getting logic in azure

### PR DESCRIPTION
**Pull request by beautytiger**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Current cache key logic in `getStorageAccountKey` is confusing and do not make much sense, fix it by moving it into if condition clause.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/cc @liggitt
/assign @liggitt

### CODE REVIEW

**Comment by beautytiger** [comment]
kindly ping @andyzhangx

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve
/priority important-soon

**Pull request merged**
