### PR TITLE
Split the GCE cloud provider into more managable chunks

### PR DESCRIPTION
**Pull request by bowei**
Each major interface is now in its own file. Any package private
functions that are only referenced by a particular module was also moved
to the corresponding file. All common helper functions were moved to
gce_util.go.

This change is a pure movement of code; no semantic changes were made.

```release-note
NONE
```

### CODE REVIEW

**Comment by bowei** [comment]
@k8s-bot unit test this

**Comment by bowei** [comment]
@nicksardo @jingxu97 FYI

**Comment by nicksardo** [comment]
@wojtek-t Would it make sense to label this as `priority/p1`? This should go in before others make mods to gce.go

**Comment by enisoc** [comment]
@k8s-bot cvm gce e2e test this

**Comment by enisoc** [comment]
@k8s-bot cvm gce e2e test this

**Comment by bowei** [comment]
build is taking a really long time...

**Comment by enisoc** [comment]
Merging this refactor before the flood gates open.

**Pull request merged**
