### PR TITLE
feat(scheduler): remove deprecated pattern in scheduler priority

### LINKED ISSUE #80224: Cleanup RegisterPriorityFunction in the scheduler
/kind cleanup
/sig scheduling
/assign
/priority important-longterm

The `RegisterPriorityFunction` has deprecated which needs to be removed from the codebase.

+ [ ] Remove RegisterPriorityFunciton

### PR DESCRIPTION
**Pull request by draveness**
/kind cleanup
/sig scheduling
/priority important-soon
/hold

Fix #80224

```release-note
NONE
```

### CODE REVIEW

**Comment by draveness** [comment]
/close

superseded by #84905

**Comment by ahg-g** [comment]
Thanks, will review once rebased.

**Pull request merged**
