### PR TITLE
GKE: Add ENABLE_CLUSTER_DNS, compute appropriate DNS_SERVER_IP

### PR DESCRIPTION
**Pull request by zmerlynn**
First push for https://github.com/GoogleCloudPlatform/kubernetes/issues/3191
to get Jenkins over the hump.

### CODE REVIEW

**Comment by thockin** [comment]
Can you define "better"?  Is something not working?

**Comment by zmerlynn** [comment]
Someone needs to write a bash function to do something like `gcloud preview
container clusters describe $THE_CLUSTER`, look for servicesIpv4Cidr and do
the right thing. It's Friday afternoon, I was popping my head in, GKE
Jenkins was busted in a completely different way thanks to the cluster DNS
checkin, so this is a pull to mitigate it for now.

**Comment by zmerlynn** [comment]
Actually, I had a few minutes to write that function, but the annoying
thing is that kube-up here assumes that DNS_SERVER_IP just flows from the
provider variables at top. That's just not necessarily true if the provider
assigns things dynamically at all, which should be allowed, so the initial
checkin needs some work. It's not like we're sourcing any of the
intermediate scripts, so nothing has a chance to even change the
DNS_SERVER_IP variable. So, yeah, it's a bigger yak to shave to be correct
for a decent provider.

**Comment by zmerlynn** [comment]
There. Updated push to the real solution.

**Comment by thockin** [comment]
The DNS server IP only needs to be static until such time as we are
comfortable changing the "cluster config" and having it work.  E.g. if
there was a config object in the API that represented the cluster, and
appropriate parties were watching that, then we could just fire up the DNS
service, see what IP got assigned, and then update the cluster config.

**Comment by zmerlynn** [comment]
I was wrong anyways (one of those silly cases where the email chain
probably diverges from the github view) and deleted that comment. I wrote
up a commit that used the providers `kube-up` to populate it.

**Comment by thockin** [comment]
LGTM

**Comment by thockin** [comment]
I'm fine to commit this if you think it's ready :)  You may self-commit if I am too slow.

**Pull request merged**
