### PR TITLE
Update Google Cloud API client import paths

### LINKED ISSUE #30069: update Google Cloud API client import paths and more
The Google Cloud API client libraries for Go are making some breaking changes:

* The import paths are changing from `google.golang.org/cloud/...` to
  `cloud.google.com/go/...`. For example, if your code imports the BigQuery client
  it currently reads
```import "google.golang.org/cloud/bigquery"```
It should be changed to
```import "cloud.google.com/go/bigquery"```

* Client options are also moving, from `google.golang.org/cloud` to
  `google.golang.org/api/option`. Two have also been renamed:
  - `WithBaseGRPC` is now `WithGRPCConn`
  - `WithBaseHTTP` is now `WithHTTPClient`

* The `cloud.WithContext` and `cloud.NewContext` methods are gone, as are the
deprecated pubsub and container functions that required them. Use the `Client`
methods of these packages instead.

You should make these changes before September 12, 2016, when the packages at
`google.golang.org/cloud` will go away.

### PR DESCRIPTION
**Pull request by dims**
Fixes #30069

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32592)

### CODE REVIEW

**Comment by dims** [comment]
@dchen1107 - This PR for fixing Google Cloud API client import paths is ready

**Comment by thockin** [comment]
Thanks @dims!

**Comment by dims** [comment]
@k8s-oncall Can you please bump up the priority on this one? (The linked Issue is a p0)

**Comment by saad-ali** [comment]
`kubelet-gce-e2e-ci` appears to have started failing after this was merged. Trying to determine if this is the root cause. See https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubelet-gce-e2e-ci/9340, for example.

**Comment by timstclair** [comment]
This PR accidentally updated cAdvisor to the master branch (it should be at the `release-v0.24` branch).

**Comment by dims** [comment]
@saad-ali the failures started earlier - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubelet-gce-e2e-ci/9336

**Comment by dims** [comment]
@timstclair : ouch sorry, Are you already readying a PR for `release-v0.24`? Please let me know

**Comment by timstclair** [comment]
I'll cut it tomorrow ([schedule](https://docs.google.com/document/d/1gMWe9ns7rUNGXpeVEI_IQjIWKcDZBJJEshCQRl2NxDA/edit#heading=h.7jl9z2qri9jx))

**Comment by jessfraz** [comment]
I'm removing the cherry-pick candidate label for this one since it's being discussed on https://github.com/kubernetes/kubernetes/pull/33806#issuecomment-251564361

**Pull request merged**
