### PR TITLE
Added support for network policies in client-go -- as per client-go i…

### PR DESCRIPTION
**Pull request by FlorianOtel**
…ssue nr. 57

**What this PR does / why we need it**:

Adds support for Network Policies in client-go -- See kubernetes/client-go#57

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

Replaces #39808 after #40449 was closed (as advised by @deads2k )

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by FlorianOtel** [comment]
@deads2k @dchen1107 Any feedback or is this "ok to test" ? 

Thanks.

**Comment by FlorianOtel** [comment]
@deads2k Have I missed something ? Or this is  (yet again) something unrelated ? Thanks again for the patience...

**Comment by neiljerram** [comment]
Just commenting to say that I would also like this change (or equivalent) to be merged.

k8s guys, can't you just get this done somehow?  @FlorianOtel has already exhibited the patience of a saint here...

**Comment by neiljerram** [comment]
OK, I see the conflicts now... I'll try to address those and raise another PR...

**Comment by neiljerram** [comment]
I'm confused now, because it appears that this code has been in master since Sep 12th 2016, with these commits by @deads2k :

```
713a0b038df397edb8537bd4bdbaa394b40d2376
Author:     deads2k <deads@redhat.com>
AuthorDate: Thu Sep 8 10:57:05 2016 -0400
Commit:     deads2k <deads@redhat.com>
CommitDate: Mon Sep 12 07:38:34 2016 -0400

Parent:     9d43f7e convert more command to use a generated clientset
Containing: master
Follows:    v1.5.0-alpha.0 (617)
Precedes:   v1.5.0-alpha.1 (1572)

update missing generated client

11c4de457db7e9623baee96f0c9525811a8ca3e2
Author:     deads2k <deads@redhat.com>
AuthorDate: Thu Sep 8 10:59:14 2016 -0400
Commit:     deads2k <deads@redhat.com>
CommitDate: Mon Sep 12 07:38:34 2016 -0400

Parent:     713a0b0 update missing generated client
Containing: master
Follows:    v1.5.0-alpha.0 (618)
Precedes:   v1.5.0-alpha.1 (1571)

generated client code
```

Specifically, those commits added:
```
modified   pkg/apis/apps/types.go
@@ -21,6 +21,8 @@ import (
 	"k8s.io/kubernetes/pkg/api/unversioned"
 )
 
+// +genclient=true
+
 // PetSet represents a set of pods with consistent identities.
 // Identities are defined as:
 //  - Network: A single stable DNS and hostname.
```
and, as an example of the generated code, the `pkg/client/clientset_generated/internalclientset/typed/extensions/unversioned/networkpolicy.go` file.

So is anything else still needed?

**Comment by neiljerram** [comment]
Ah, the `client-go` repo has the
```
// +genclient=true
```
change, but _not_ any of the generated code (`NetworkPolicies()` etc.).  So I guess the problem is that, for some reason, the generated code has not yet propagated to `client-go`.

What is needed to make that happen?

**Comment by caesarxuchao** [comment]
@neiljerram the problem is not that. It's because the NetworkPolicy struct in v1beta1/types.go doesn't have the gen-client tag. If you are interested to send a PR, you can just add the tag and then run hack/update-all.sh. Or let me know if you want me to do it..

**Comment by neiljerram** [comment]
Ah, I see: the definition in `client-go/pkg/apis/extensions/types.go` has the `genclient` tag, but the definition in `client-go/pkg/apis/extensions/v1beta1/types.go` does not.  Why are there 2 very similar definitions of (apparently) the same thing?

In any case, I would be very happy if you could just do this, @caesarxuchao !

**Comment by caesarxuchao** [comment]
@neiljerram Sure. I'm swarmed by other things right now, ping me again if i don't cc you on a PR next Monday.

**Comment by caesarxuchao** [comment]
@neiljerram this PR, which moves networkpolicy to v1, generates the networking clients: https://github.com/kubernetes/kubernetes/pull/39164/files.

**Pull request closed without merging**
