### PR TITLE
Add usage in some hack/update scripts

### LINKED ISSUE #86597: Improve documents and guidance of each script in hack directory
**What would you like to be added**:
There are many useful scripts in "https://github.com/kubernetes/kubernetes/tree/master/hack".
For example, I often use `install-etcd.sh` and `local-up-cluster.sh` for creating simple k8s cluster quickly.
However, there are only few explanation or nothing how to use it.
I think it becomes more useful and helpful if some instruction or guidance is explained in each script.

**Why is this needed**:
It aims and expects to increase new k8s developers by describing how to use each script.

**My proposal**
Add the following description under the copyright for each script file.
 - Overview of the script
 - Simple usage
 - Supplementary explanation(This is option)

**Other concern**
I would like to know the purpose of use about hack directory.
(e.g. Where to put tools for developers(therefore there is no guidance?).)

### PR DESCRIPTION
**Pull request by helenfeng737**
**What type of PR is this?**

> /kind cleanup

**What this PR does / why we need it**:
Update usage of them:
```
 kubernetes/hack/update-generated-pod-resources.sh
 kubernetes/hack/update-generated-protobuf-dockerized.sh
 kubernetes/hack/update-generated-protobuf.sh
 kubernetes/hack/update-generated-runtime-dockerized.sh
 kubernetes/hack/update-generated-runtime.sh
 kubernetes/hack/update-generated-swagger-docs.sh
```

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/86597

### CODE REVIEW

**Comment by ZhiFeng1993** [comment]
@fejta  mind approve?

**Review by fejta — COMMENTED** [review]
/approve

**Comment by ZhiFeng1993** [comment]
@hase1128 mind adding lgtm label? Thanks!

**Comment by hase1128** [comment]
sorry, I am not reviewer or approver, so I can't add lgtm label.
@fejta 
Would you please add lgtm label?

**Review by fejta — COMMENTED** [review]
/approve

**Pull request merged**
