### PR TITLE
Add CHANGELOG-1.18.md to CHANGELOG.md

### PR DESCRIPTION
**Pull request by sftim**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Update the main `CHANGELOG.md` following the v1.17 release.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/priority important-longterm
/cc @guineveresaenger 

I haven't added a https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.18.md yet; not sure when that would happen and whether or not it ought to be part of this PR.

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
We probably should do this in @kubernetes/release-engineering tooling as well. :thinking: 

/lgtm

**Comment by liggitt** [comment]
thanks for the PR, changelogs have been relocated under the CHANGELOG folder, so if this is still valid, it will need to be re-opened against that location

/close

**Comment by sftim** [comment]
No longer needed.

**Pull request closed without merging**
