### PR TITLE
remove FG ControllerManagerLeaderMigration

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/enhancements/issues/2436

#### Does this PR introduce a user-facing change?

```release-note
The `ControllerManagerLeaderMigration ` feature, GA since 1.24, is unconditionally enabled and the feature gate option has been removed.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/2436
```

### CODE REVIEW

**Comment by pacoxu** [comment]
ACK

**Review by jiahuif — COMMENTED** [review]
/lgtm
Note that there are multiple open PRs that tries to remove the same set of feature gates. Expect conflicts among these.

**Pull request merged**
