### PR TITLE
ValidatingAdmissionPolicySpec: set Variables as omitempty.

### LINKED ISSUE #120491: ValidatingAdmissionPolicy: spec.variables should be marked omitempty
### What would you like to be added?

spec.variables should be marked omitempty.

### Why is this needed?

I'm trying to create a validating admission policy that uses `spec.variables` in v1.27 as follows:
```
// set validating admission policy spec
vap.Spec = v1alpha1.ValidatingAdmissionPolicySpec {
        ParamKind:        rule.Validation.CEL.ParamKind,
        MatchConstraints: &matchResources,
	Validations:      rule.Validation.CEL.Expressions,
	AuditAnnotations: rule.Validation.CEL.AuditAnnotations,
	MatchConditions:  rule.CELPreconditions,
}
```
I'm setting `FieldValidation`: to "Strict" in CreateOptions so that the server will reject requests with unknown fields but it complains that the `spec.variables` don't exist in v1.27 and it does make sense because this field was introduced in v1.28:
```
strict decoding error: unknown field "spec.variables"'
```
I'm using a 1.28 client.

### PR DESCRIPTION
**Pull request by jiahuif**
#### What type of PR is this?
/kind api-change
/kind cleanup

#### What this PR does / why we need it:
This PR fixes an oversight where the `omitempty` json tag does not apply to `ValidatingAdmissionPolicySpec.Variables`.
Note that due to the existing `+optional` tag, generated code remains correct, and no breakage is expected.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/120491

#### Special notes for your reviewer:
compatibility fixture removed because `variables` no longer has the default during roundtrip.
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
fix #120491

**Comment by jiahuif** [comment]
/assign @liggitt 
This is a trivial non-breaking API change. Could you take a look? Thank you!

**Pull request merged**
