### PR TITLE
replace gopkg.in/yaml.v2 with sigs.k8s.io/yaml

### PR DESCRIPTION
**Pull request by gy95**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Now kubernetes we have `yaml` related packages, as below,
```
gopkg.in/yaml.v2
sigs.k8s.io/yaml
```
And some functions are not used, so I just remove these funcs
 we can simply these packages and keep only one
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/ok-to-test
/area code-organization

**Comment by thockin** [comment]
This is another case where a ruleguard rule would be appropriate.  @aojea

**Pull request closed without merging**
