### PR TITLE
Added google search, added 404 page w/ redirect, and nav fixes

### PR DESCRIPTION
**Pull request by RichieEscarez**
- inserted Google CSE at the top of the nav menu
- fixed the CSS so that nav menu items dont overlap
- added 404 page with auto redirect to doc home page
- reorganized nav (app. admin and install) and fixed almost all links (some links are still empty)
  - the nav is still WIP, changes to install and cluster admin are still in progress

### CODE REVIEW

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by caesarxuchao** [comment]
The css part seems to be good, but I think the best way to review is viewing the html in a web browser. @RichieEscarez, it may be easier for people to review if you can push it to your github page so people can review the website there. Thank you!

**Comment by RichieEscarez** [comment]
@caesarxuchao, the files are in my fork but since the _config.yml file points to kubernetes.io, many things like links (including the CSS file) point to the current version out on kubernetes.io (vs. the CSS file in this PR): http://richieescarez.github.io/kubernetes/v1.0/

**Comment by RichieEscarez** [comment]
We are pushing out to the public server, but nothing is visibly exposed to users unless they know the URL. I think the only way to test is to setup a [local build](https://help.github.com/articles/using-jekyll-with-pages/) or merge first, test, and fix anything in a subsequent PR? Im still working on the nav, so another option is to send requests directly to me, and i can include them in my next PR?

**Comment by bgrant0607** [comment]
I vote to just merge. Navigation is pretty broken right now

**Comment by thockin** [comment]
merging

**Pull request merged**
