### PR TITLE
OWNERS for kubectl translations

### PR DESCRIPTION
**Pull request by fabianofranz**
`pkg/kubectl` approvers and reviewers can also handle `translations/kubectl`.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fabianofranz** [comment]
@brendandburns @deads2k @kubernetes/sig-cli-pr-reviews ptal

**Comment by bgrant0607** [comment]
/lgtm
/approve

@fabianofranz At some point, please rename the SIG CLI aliases to sig-cli-approvers and sig-cli-reviewers.

**Comment by fabianofranz** [comment]
@k8s-bot unit test this

**Pull request merged**
