### PR TITLE
Fix a small typo.

### PR DESCRIPTION
**Pull request by brendandburns**

### CODE REVIEW

**Comment by brendandburns** [comment]
@zmerlynn @jlowdermilk

**Comment by eikaas** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tapiohush@gmail.com
    Domain eikaas.no has exceeded the max emails per hour (30/30 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:52771 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cpanel30.proisp.no with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZEglf-003wl3-0f
	for robin@eikaas.no; Mon, 13 Jul 2015 18:39:54 +0200
Date: Mon, 13 Jul 2015 09:39:45 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1436805585;
	bh=Y/TOYm2Bi/L+QM3+AVt+dzzG7xVi+yjf3LUw6+qO0MA=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=vj76vOowLPnfPyPv24Y6qCGCpe6xdhdg7uAckYe6LtTsa7ssmkU3m9oaPpMiV5Gs7
	 N71cJTLIkxgndTey3opVwjcTdimasDt250xkQ+INjSyx4lmthlf495DudT6A4XKpkT
	 uEF4KtjSNRzJlNSfxlhrQkzxdybcOwy1BeNFksb8=

**Comment by jlowdermilk** [comment]
lgtm

**Comment by eikaas** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tapiohush@gmail.com
    Domain eikaas.no has exceeded the max emails per hour (35/30 (116%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:28100)
	by cpanel30.proisp.no with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-7097-robin=eikaas.no@sgmail.github.com>)
	id 1ZEgph-004ECR-CP
	for robin@eikaas.no; Mon, 13 Jul 2015 18:44:06 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=cg+x+AagEJCpSdnaL1JvR0cRIa8=; b=nTR0/4tOwYhqRWCS
	3nGcaiMsAaQG+p8OxWEtgtLerb2gYFITW2VbZlcRKkTJ3c4RpomZISp5JxmAQj6v
	OhFi24AoF3M/0yiidEue7eLOzaVLXgw/MgmQsbkKP7EoIDxqYCj1CX9nzfTCLzvW
	nappYT4mTm4zXFSnyrZ59lWin4w=
Received: by filter0606p1mdw1.sendgrid.net with SMTP id filter0606p1mdw1.3061.55A3EAC910
        2015-07-13 16:43:53.547957648 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd-036 (SG) with ESMTP id 14e884d2305.2a7b.c903c
	for <robin@eikaas.no>; Mon, 13 Jul 2015 16:43:53 +0000 (UTC)
Date: Mon, 13 Jul 2015 09:43:53 -0700

**Pull request merged**
