### PR TITLE
Synchronous spellcheck for pkg/volume/*

### PR DESCRIPTION
**Pull request by ghost**
**What this PR does / why we need it**: Increase code readability

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**: Minor contribution 

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by aaron12134** [comment]
@k8s-ci-robot ok to test

**Comment by rootfs** [comment]
@k8s-ci-robot ok to test

**Comment by jsafrane** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
