### PR TITLE
WIP: upgrade shellcheck to v0.8.0 (latest stable)

### PR DESCRIPTION
**Pull request by BenTheElder**
#### What this PR does / why we need it:

It's been >2 years since we've upgraded. The upgraded linter catches more errors.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

I'm still working on fixing the newly found issues. It may take a bit.
Will remove `WIP` from the title when this is ready.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
Initial issues:
```console
$ hack/verify-shellcheck.sh 
Using host shellcheck 0.8.0 binary.

In ./cluster/get-kube.sh line 193:
    KUBERNETES_RELEASE_URL="${KUBERNETES_RELEASE_URL}"
    ^--------------------^ SC2269 (info): This variable is assigned to itself, so the assignment does nothing.


In ./cluster/kube-up.sh line 30:
    source "${KUBE_ROOT}/cluster/env.sh"
           ^---------------------------^ SC1091 (info): Not following: ./cluster/env.sh: openBinaryFile: does not exist (No such file or directory)


In ./cluster/gce/util.sh line 2634:
        xargs -i -P ${parallelism} gcloud --quiet compute networks subnets delete "${NETWORK}" --project "${NETWORK_PROJECT}" --region="{}" || true
              ^-- SC2267 (info): GNU xargs -i is deprecated in favor of -I{}


In ./cluster/gce/gci/configure-helper.sh line 2909:
    . "${KUBE_HOME}/bin/gke-internal-configure-helper.sh"
      ^-- SC1091 (info): Not following: ./bin/gke-internal-configure-helper.sh: openBinaryFile: does not exist (No such file or directory)


In ./cluster/gce/gci/configure-helper.sh line 3345:
  source "${KUBE_HOME}/kube-env"
         ^---------------------^ SC1091 (info): Not following: ./kube-env: openBinaryFile: does not exist (No such file or directory)


In ./cluster/gce/gci/configure.sh line 507:
    "https://download.docker.com/${HOST_PLATFORM}/$(. /etc/os-release; echo "$ID")/gpg" \
                                                      ^-------------^ SC1091 (info): Not following: /etc/os-release: openBinaryFile: does not exist (No such file or directory)


In ./cluster/gce/gci/configure.sh line 510:
    "deb [arch=${HOST_ARCH}] https://download.docker.com/${HOST_PLATFORM}/$(. /etc/os-release; echo "$ID") \
                                                                              ^-------------^ SC1091 (info): Not following: /etc/os-release: openBinaryFile: does not exist (No such file or directory)


In ./cluster/validate-cluster.sh line 30:
  source "${KUBE_ROOT}/cluster/env.sh"
         ^---------------------------^ SC1091 (info): Not following: ./cluster/env.sh: openBinaryFile: does not exist (No such file or directory)


In ./cluster/kube-down.sh line 26:
    source "${KUBE_ROOT}/cluster/env.sh"
           ^---------------------------^ SC1091 (info): Not following: ./cluster/env.sh: openBinaryFile: does not exist (No such file or directory)


In ./staging/src/k8s.io/kube-aggregator/hack/local-up-kube-aggregator.sh line 89:
kube::util::ensure-cfssl
^----------------------^ SC2119 (info): Use kube::util::ensure-cfssl "$@" if function's $1 should mean script's $1.


In ./test/images/image-util.sh line 287:
    eval "${TASK}" "${image}" "$@"
                               ^-- SC2294 (warning): eval negates the benefit of arrays. Drop eval to preserve whitespace/symbols (or eval as string).


In ./test/images/image-util.sh line 290:
  eval "${TASK}" "$@"
                  ^-- SC2294 (warning): eval negates the benefit of arrays. Drop eval to preserve whitespace/symbols (or eval as string).


In ./test/kubemark/resources/start-kubemark-master.sh line 682:
source "${KUBE_ROOT}/kubemark-master-env.sh"
       ^-- SC1091 (info): Not following: ./kubemark-master-env.sh: openBinaryFile: does not exist (No such file or directory)


In ./hack/dev-push-conformance.sh line 43:
kube::build::verify_prereqs
^-------------------------^ SC2119 (info): Use kube::build::verify_prereqs "$@" if function's $1 should mean script's $1.


In ./hack/verify-generated-swagger-docs.sh line 73:
  for file in ${TARGET_FILES[*]}; do
              ^----------------^ SC2048 (warning): Use "${array[@]}" (with quotes) to prevent whitespace problems.


In ./hack/make-rules/make-help.sh line 21:
readonly red=$(tput setaf 1)
         ^-^ SC2155 (warning): Declare and assign separately to avoid masking return values.


In ./hack/make-rules/make-help.sh line 22:
readonly reset=$(tput sgr0)
         ^---^ SC2155 (warning): Declare and assign separately to avoid masking return values.


In ./hack/make-rules/clean.sh line 33:
    echo "Removing ${match#${KUBE_ROOT}\/} .."
                           ^----------^ SC2295 (info): Expansions inside ${..} need to be quoted separately, otherwise they match as patterns.

Did you mean: 
    echo "Removing ${match#"${KUBE_ROOT}"\/} .."


In ./hack/make-rules/clean.sh line 34:
    rm -rf "${match#${KUBE_ROOT}\/}"
                    ^----------^ SC2295 (info): Expansions inside ${..} need to be quoted separately, otherwise they match as patterns.

Did you mean: 
    rm -rf "${match#"${KUBE_ROOT}"\/}"


In ./hack/make-rules/test.sh line 146:
  goflags+=(-v)
  ^-----^ SC2031 (info): goflags was modified in a subshell. That change might be lost.


In ./hack/make-rules/vet.sh line 30:
    goflags+=("${arg}")
    ^-----^ SC2031 (info): goflags was modified in a subshell. That change might be lost.


In ./hack/local-up-cluster.sh line 189:
if [ "x${GO_OUT}" == "x" ]; then
     ^----------^ SC2268 (style): Avoid x-prefix in comparisons as it no longer serves a purpose.

Did you mean: 
if [ "${GO_OUT}" == "" ]; then


In ./hack/local-up-cluster.sh line 1124:
kube::util::ensure-cfssl
^----------------------^ SC2119 (info): Use kube::util::ensure-cfssl "$@" if function's $1 should mean script's $1.


In ./hack/lib/test.sh line 21:
readonly reset=$(tput sgr0)
         ^---^ SC2155 (warning): Declare and assign separately to avoid masking return values.


In ./hack/lib/test.sh line 22:
readonly  bold=$(tput bold)
          ^--^ SC2155 (warning): Declare and assign separately to avoid masking return values.


In ./hack/lib/test.sh line 23:
readonly black=$(tput setaf 0)
         ^---^ SC2155 (warning): Declare and assign separately to avoid masking return values.


In ./hack/lib/test.sh line 24:
readonly   red=$(tput setaf 1)
           ^-^ SC2155 (warning): Declare and assign separately to avoid masking return values.


In ./hack/lib/test.sh line 25:
readonly green=$(tput setaf 2)
         ^---^ SC2155 (warning): Declare and assign separately to avoid masking return values.


In ./hack/lib/test.sh line 85:
    res=$(eval kubectl get "${kube_flags[@]}" ${args} "${object}" -o go-template=\""${request}"\")
                            ^--------------^ SC2294 (warning): eval negates the benefit of arrays. Drop eval to preserve whitespace/symbols (or eval as string).


In ./hack/lib/test.sh line 112:
  res=$(eval kubectl get "${kube_flags[@]}" "${object}" -o jsonpath=\""${request}"\")
                          ^--------------^ SC2294 (warning): eval negates the benefit of arrays. Drop eval to preserve whitespace/symbols (or eval as string).


In ./hack/lib/test.sh line 137:
  result=$(eval kubectl describe "${kube_flags[@]}" "${resource}" "${object}")
                                  ^--------------^ SC2294 (warning): eval negates the benefit of arrays. Drop eval to preserve whitespace/symbols (or eval as string).


In ./hack/lib/test.sh line 169:
        result=$(eval kubectl describe "${kube_flags[@]}" "${resource}" "${object}")
                                        ^--------------^ SC2294 (warning): eval negates the benefit of arrays. Drop eval to preserve whitespace/symbols (or eval as string).


In ./hack/lib/test.sh line 171:
        result=$(eval kubectl describe "${kube_flags[@]}" "--show-events=${showevents}" "${resource}" "${object}")
                                        ^--------------^ SC2294 (warning): eval negates the benefit of arrays. Drop eval to preserve whitespace/symbols (or eval as string).


In ./hack/lib/test.sh line 205:
  result=$(eval kubectl describe "${kube_flags[@]}" "${resource}")
                                  ^--------------^ SC2294 (warning): eval negates the benefit of arrays. Drop eval to preserve whitespace/symbols (or eval as string).


In ./hack/lib/test.sh line 235:
    result=$(eval kubectl describe "${kube_flags[@]}" "--show-events=${showevents}" "${resource}")
                                    ^--------------^ SC2294 (warning): eval negates the benefit of arrays. Drop eval to preserve whitespace/symbols (or eval as string).


In ./hack/lib/test.sh line 276:
  defaultResult=$(eval kubectl describe "${resource}" --show-events=true -v=6 "${args}" "${kube_flags[@]}" 2>&1 >/dev/null)
                                                                                         ^--------------^ SC2294 (warning): eval negates the benefit of arrays. Drop eval to preserve whitespace/symbols (or eval as string).


In ./hack/lib/test.sh line 295:
  customResult=$(eval kubectl describe "${resource}" --show-events=false --chunk-size=10 -v=6 "${args}" "${kube_flags[@]}" 2>&1 >/dev/null)
                                                                                                         ^--------------^ SC2294 (warning): eval negates the benefit of arrays. Drop eval to preserve whitespace/symbols (or eval as string).


In ./hack/verify-shellcheck.sh line 29:
DOCKER="${DOCKER:-docker}"
^----^ SC2178 (warning): Variable was used as an array but is now assigned a string.


In ./hack/verify-shellcheck.sh line 113:
  "${DOCKER}" run \
   ^-------^ SC2128 (warning): Expanding an array without an index only gives the first element.


In ./hack/verify-e2e-test-ownership.sh line 44:
readonly tmpdir=$(mktemp -d -t verify-e2e-test-ownership.XXXX)
         ^----^ SC2155 (warning): Declare and assign separately to avoid masking return values.


In ./build/common.sh line 41:
readonly KUBE_BUILD_IMAGE_CROSS_TAG="$(cat "${KUBE_ROOT}/build/build-image/cross/VERSION")"
         ^------------------------^ SC2155 (warning): Declare and assign separately to avoid masking return values.


In ./build/common.sh line 52:
readonly KUBE_BUILD_IMAGE_VERSION_BASE="$(cat "${KUBE_ROOT}/build/build-image/VERSION")"
         ^---------------------------^ SC2155 (warning): Declare and assign separately to avoid masking return values.


In ./build/make-build-image.sh line 30:
kube::build::verify_prereqs
^-------------------------^ SC2119 (info): Use kube::build::verify_prereqs "$@" if function's $1 should mean script's $1.


In ./build/release-images.sh line 38:
kube::build::verify_prereqs
^-------------------------^ SC2119 (info): Use kube::build::verify_prereqs "$@" if function's $1 should mean script's $1.


In ./build/run.sh line 30:
kube::build::verify_prereqs
^-------------------------^ SC2119 (info): Use kube::build::verify_prereqs "$@" if function's $1 should mean script's $1.


In ./build/lib/release.sh line 137:
    platform=${platform_long##${LOCAL_OUTPUT_BINPATH}/} # Strip LOCAL_OUTPUT_BINPATH
                              ^---------------------^ SC2295 (info): Expansions inside ${..} need to be quoted separately, otherwise they match as patterns.

Did you mean: 
    platform=${platform_long##"${LOCAL_OUTPUT_BINPATH}"/} # Strip LOCAL_OUTPUT_BINPATH


In ./build/release.sh line 34:
kube::build::verify_prereqs
^-------------------------^ SC2119 (info): Use kube::build::verify_prereqs "$@" if function's $1 should mean script's $1.


In ./build/copy-output.sh line 25:
kube::build::verify_prereqs
^-------------------------^ SC2119 (info): Use kube::build::verify_prereqs "$@" if function's $1 should mean script's $1.

For more information:
  https://www.shellcheck.net/wiki/SC2048 -- Use "${array[@]}" (with quotes) t...
  https://www.shellcheck.net/wiki/SC2128 -- Expanding an array without an ind...
  https://www.shellcheck.net/wiki/SC2155 -- Declare and assign separately to ...

Please review the above warnings. You can test via "./hack/verify-shellcheck.sh"
If the above warnings do not make sense, you can exempt this warning with a comment
 (if your reviewer is okay with it).
In general please prefer to fix the error, we have already disabled specific lints
 that the project chooses to ignore.
See: https://github.com/koalaman/shellcheck/wiki/Ignore#ignoring-one-specific-instance-in-a-file
```

**Comment by BenTheElder** [comment]
hmm local-e2e is broken on a no-change PR but not quite the same way 

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/92316/pull-kubernetes-local-e2e/1582871596391993344/

Vs here:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/113179/pull-kubernetes-local-e2e/1582845666701348864/

I'm going to pull out most of these fixes to other PR(s) so they don't get merge conflicts between now and sorting out the rest of the new issues.

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by BenTheElder** [comment]
@dims this PR is surfacing the obstacles to upgrading which are being addressed in companion PRs, I had a gap in working on this. It's labeled WIP to indicate that it does not need review yet and isn't ready to merge yet.

**Comment by BenTheElder** [comment]
obviated by https://github.com/kubernetes/kubernetes/commit/61cd37b80697ca0254553e3e120a52fd7d1419a4

**Pull request closed without merging**
