### PR TITLE
scheduler: include scheduling error in the pod condition

### PR DESCRIPTION
**Pull request by 0xmichalis**
@kubernetes/sig-scheduling-misc

### CODE REVIEW

**Comment by kargakis** [comment]
@k8s-bot gci gke e2e test this
@k8s-bot cvm gke e2e test this

**Comment by timothysc** [comment]
This change already exists upstream https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/scheduler.go#L104 

and is a dupe of https://github.com/kubernetes/kubernetes/pull/39491

**Comment by jayunit100** [comment]
yup

**Comment by jayunit100** [comment]
wonder why bot didn't flag this as needs-rebase

**Comment by eparis** [comment]
did the exact same patch get applied? git has no problem merging the same patch twice. Even though the second merge doesn't actually do anything to the code. So it wouldn't actually need a rebase...

**Comment by timothysc** [comment]
> did the exact same patch get applied? 

exact same ... no.  but the code contained in this patch was already applied in the other.

**Comment by eparis** [comment]
Exact same `diff` is what matters. As long as there were no contextual changes around the diff...

**Pull request closed without merging**
