### PR TITLE
updated deprecation messages from 1.23 to 1.24

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
#### What type of PR is this?

/kind cleanup
/kind documentation

#### What this PR does / why we need it:

Just to avoid confusion from these deprecation messages we might consider updating the text.

```release-note
NONE
```

### CODE REVIEW

**Review by ehashman — COMMENTED** [review]
/triage accepted
/priority important-soon
should land in 1.24, we can backport

/lgtm

**Comment by sftim** [comment]
LGTM

**Pull request merged**
