### PR TITLE
add github.com/mindprince/gonvml to unwanted dependencies

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
See https://groups.google.com/d/msgid/kubernetes-sig-architecture/CAJ18wa9iwCsfugDOR%2B%2Bo86udHjx6qGjYWfp6qCwBVL7gBu5C2A%40mail.gmail.com?utm_medium=email&utm_source=footer for discussions.

github.com/mindprince/gonvml
- https://github.com/mindprince/gonvml/blob/ac0b66419a4131fe2348bceb59358888edd9c4e4/bindings.go#L25

#### Which issue(s) this PR fixes:
Fixes None
- BTW, sort unwanted dependencies in order
- [ ] https://github.com/google/cadvisor/releases waiting for new release of cadvisor

#### Special notes for your reviewer:
cncf/kubernetes, code pulled 2022-10-13
  - report: https://lfscanning.org/reports/cncf/kubernetes-2022-10-13-19a6e7e7-4f53-4c58-9dcb-6ab28ebf194d.html

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @rohitagarwal003

**Comment by rohitagarwal003** [comment]
I agree with https://github.com/lfscanning/scaffold/issues/48

But see https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/#disable-accelerator-metrics for an effort to remove this dependency from kubernetes completely.

**Comment by liggitt** [comment]
/cc @RenaudWasTaken @dashpole
as owners of that feature gate. with that locked on in 1.25+, is it the case that kubernetes will always trigger this path:

```go
	if !includedMetrics.Has(container.AcceleratorUsageMetrics) {
		klog.V(2).Info("NVIDIA GPU metrics disabled")
		return &stats.NoopManager{}
	}
```

if so, can we drop nvml from cadvisor and k/k entirely now?

**Comment by dashpole** [comment]
> if so, can we drop nvml from cadvisor and k/k entirely now?

Yes, we should be able to drop NVML entirely now.

**Comment by liggitt** [comment]
> > if so, can we drop nvml from cadvisor and k/k entirely now?
> 
> Yes, we should be able to drop NVML entirely now.

opened https://github.com/google/cadvisor/pull/3206 with a stab at that

**Comment by liggitt** [comment]
cadvisor PR is merged, will get that tagged and updated in k/k early in 1.27 (https://github.com/kubernetes/kubernetes/pull/114254 in progress)

**Comment by dims** [comment]
/sig architecture
/approve
/lgtm

let's follow up with the cadvisor changes and cleanup the rules we added here

**Pull request merged**
