### PR TITLE
Automated cherry pick of #35806

### PR DESCRIPTION
**Pull request by bdbauer**
Cherry pick of #35806 on release-1.4.

#35806: Made changes to DELETE API to let v1.DeleteOptions be

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36534)

### CODE REVIEW

**Comment by jessfraz** [comment]
@k8s-bot gci gce e2e test this

**Comment by jessfraz** [comment]
@k8s-bot cvm gce e2e test this

**Comment by jessfraz** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by jessfraz** [comment]
@k8s-bot kubemark e2e test this

**Comment by jessfraz** [comment]
@k8s-bot gci gke e2e test this

**Comment by maisem** [comment]
@k8s-bot cvm gce e2e test this

**Comment by maisem** [comment]
@k8s-bot kubemark e2e test this

**Comment by maisem** [comment]
@k8s-bot gci gke e2e test this

**Comment by maisem** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by maisem** [comment]
@k8s-bot gci gce e2e test this

**Comment by maisem** [comment]
@k8s-bot gci gke e2e test this

**Comment by jessfraz** [comment]
manually merging since all is green

**Pull request merged**
