### PR TITLE
Apply BeforeCreate logic to kubernetes service

### LINKED ISSUE #9846: kubernetes service doesn't have UID/creationTimestamp
From a brand new cluster:
```
$ hack/local-up-cluster.sh &
$ kubectl get services -o json

{
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": [
        {
            "kind": "Service",
            "apiVersion": "v1",
            "metadata": {
                "name": "kubernetes",
                "namespace": "default",
                "selfLink": "/api/v1/namespaces/default/services/kubernetes",
                "resourceVersion": "7",
                "creationTimestamp": null,
                "labels": {
                    "component": "apiserver",
                    "provider": "kubernetes"
                }
            },
            "spec": {
                "ports": [
                    {
                        "protocol": "TCP",
                        "port": 443,
                        "targetPort": 443,
                        "nodePort": 0
                    }
                ],
                "clusterIP": "10.0.0.1",
                "type": "ClusterIP",
                "sessionAffinity": "None"
            },
            "status": {
                "loadBalancer": {}
            }
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #9846

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM

**Comment by smarterclayton** [comment]
Ensures that services have UIDs and that they follow the rules of API objects.

**Comment by smarterclayton** [comment]
This needs to be for 1.0 because we're not guaranteeing UIDs are set on services.

**Comment by saad-ali** [comment]
I marked the associated issue as ` v1.0-candidate`. If it gets approved for `v1.0`, we can merge this.

**Comment by satnam6502** [comment]
@k8s-bot ok to test

**Pull request merged**
