### PR TITLE
e2e: Use framework helpers to create namespaces

### LINKED ISSUE #108298: test/e2e: use framework helpers to create namespaces
### What would you like to be added?

Currently, some e2e tests do not use central framework helper methods to create namespaces. Examples:

https://github.com/kubernetes/kubernetes/blob/296bf4f01668374ade252a751d4c3567917b9890/test/e2e/apimachinery/webhook.go#L1532
https://github.com/kubernetes/kubernetes/blob/296bf4f01668374ade252a751d4c3567917b9890/test/e2e/apimachinery/webhook.go#L2370-L2375
https://github.com/kubernetes/kubernetes/blob/296bf4f01668374ade252a751d4c3567917b9890/test/e2e/network/netpol/kubemanager.go#L178

The fix is to use https://github.com/kubernetes/kubernetes/blob/296bf4f01668374ade252a751d4c3567917b9890/test/e2e/framework/framework.go#L519 instead.

### Why is this needed?

This makes maintanance of e2e tests hard as enforcement settings (like pod security admission) is not centralized

### PR DESCRIPTION
**Pull request by antoninbas**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Use framework helpers to create namespaces for apimachinery webhook e2e tests

Note that an earlier (merged) PR took care of the netpol e2e tests, which are mentioned in #108298: #111789

The issue also mentions that the following code needs to be updated to use `CreateNamespace` from the framework:
https://github.com/kubernetes/kubernetes/blob/f313ef501a508cedfca9ed5543cdadbb8053c9b9/test/e2e/network/scale/localrun/ingress_scale.go#L134-L148

I disagree. This program is meant to be run locally for a very specific purpose. It is not a generic test (GCE-specific) and manual namespace creation seems intentional. To avoid future confusion, a comment was added. However, I am not very familiar with this program, so feel free to correct me.

#### Which issue(s) this PR fixes:

Fixes #108298 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Comment by antoninbas** [comment]
pinging @danwinship @s-urbaniak for review

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by antoninbas** [comment]
@dims done, rebased

**Comment by antoninbas** [comment]
I have rebased this PR a second time, to resolve conflicts

**Pull request merged**
