### PR TITLE
make iscsi portals optional

### PR DESCRIPTION
**Pull request by rootfs**
**What this PR does / why we need it**: Make iSCSI portals optional

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rootfs** [comment]
@k8s-bot cvm gce e2e test this

**Comment by rootfs** [comment]
@k8s-bot kops aws e2e test this

**Comment by rootfs** [comment]
@k8s-bot kubemark e2e test this

**Comment by rootfs** [comment]
@k8s-bot gci gke e2e test this

**Comment by rootfs** [comment]
@justinsb PTAL

@dchen1107 please approve

Thanks!

**Comment by rootfs** [comment]
@dchen1107 @justinsb ping

**Comment by humblec** [comment]
LGTM . Thanks @rootfs! , PR need rebase.

**Comment by justinsb** [comment]
So I think this is the core of the change, and everything else is auto-generated:

```
 	// iSCSI target portal List. The portal is either an IP or ip_addr:port if the port
  	// is other than default (typically TCP ports 860 and 3260).
  	// +optional
 -	Portals []string `json:"portals" protobuf:"bytes,7,opt,name=portals"`
 +	Portals []string `json:"portals,omitempty" protobuf:"bytes,7,opt,name=portals"`
```

I'm not sure what the rules are about omitempty changes, and whether json omitempty should match protobuf opt.

Reassigning to @smarterclayton for the answer or triage :-)

**Comment by rootfs** [comment]
@smarterclayton PTAL, thanks.

**Comment by smarterclayton** [comment]
/approve

API change is allowed (required -> looser) and this was documented as optional before.  However, surprised that you were not marked as optional anyway, i thought @mbohlool's change to openapi and the +optional tag ensured omitempty was not required.

merge when green.

**Comment by justinsb** [comment]
I'll treat that as LGTM :-)

/lgtm

@k8s-bot kops aws e2e test this

**Pull request merged**
