### PR TITLE
Start e2e framework; print events

### PR DESCRIPTION
**Pull request by lavalamp**
Remove global 'c' variable.
Rework network test a bit.

(Yes, the network test still passes e2e, and I didn't change anything else.)

### CODE REVIEW

**Comment by lavalamp** [comment]
Looks like someone else already got rid of the global.

**Comment by lavalamp** [comment]
We need to get a newer copy of ginkgo, then I can make the events print only when it fails. (see https://github.com/onsi/ginkgo/issues/163)

Will do that tomorrow.

**Comment by lavalamp** [comment]
Eh... it was easy so I just did it now. Running full e2e locally.

**Comment by lavalamp** [comment]
Next steps here are to read out scheduler, apiserver, controller manager, kubelet, kubeproxy logs. At the end of a test run.

And to plumb this into more tests, of course.

**Comment by quinton-hoole** [comment]
LGTM

cc @jayunit100 FYI

**Comment by dchen1107** [comment]
Thanks for improving debuggability of e2e tests.

**Comment by jayunit100** [comment]
Interesting work thanks guys.  Now it's time for that e2e Dev guide :)

**Pull request merged**
