### PR TITLE
Multi-arch images for echoserver

### PR DESCRIPTION
**Pull request by dims**
Originally from:
https://github.com/kubernetes/ingress-nginx/tree/master/images/echoheaders

Moving the code here to prevent bit-rot and to be sure we can recreate
or update the images on demand. Moving it here also ensures we can use
the common harness to build the multi-arch manifests needed for running
the e2e test that use this container.

Change-Id: I15009268da4e7809a1c03d9af3181b585afa8139

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
related to https://github.com/kubernetes/kubernetes/issues/66986

**Comment by spiffxp** [comment]
contacted by @dims, pushed image

https://gist.github.com/spiffxp/1817115bb191ebf5d399d3112e439399

**Comment by spiffxp** [comment]
/approve
I'll let someone else /lgtm

/hold
remove the hold once you've filed a followup issue to remove the code from the other repo

**Comment by dims** [comment]
/hold cancel

filed an issue here, thanks @spiffxp! https://github.com/kubernetes/ingress-nginx/issues/2911

**Comment by dims** [comment]
@aledbf my apologies! it was a cut and paste from another one https://github.com/kubernetes/kubernetes/pull/67030 / https://github.com/kubernetes/contrib/tree/master/apparmor/loader where the code was 2 years old and there was easy way to create the image.

Yes, it would be great to make the Dockerfile real simple with the go code you mentioned. could we maintain the Dockerfile/Makefile here? where do you wish it to live?

Thanks,
Dims

**Comment by aledbf** [comment]
> Yes, it would be great to make the Dockerfile real simple with the go code you mentioned. could we maintain the Dockerfile/Makefile here? where do you wish it to live?

I think the [ingress-gce](https://github.com/kubernetes/ingress-gce/blob/master/OWNERS) owners should decide that.

**Comment by aledbf** [comment]
> where do you wish it to live?

Independent of that, could be possible to release a 2.0 tag with this new codebase so [echoheaders](https://github.com/kubernetes/ingress-nginx/tree/master/images/echoheaders) can be removed?

**Comment by dims** [comment]
@aledbf i've opened https://github.com/kubernetes/ingress-gce/issues/427 for the future work for a new container image using the go based code you mentioned

**Comment by spiffxp** [comment]
/retest
pushed new image again, updated https://gist.github.com/spiffxp/1817115bb191ebf5d399d3112e439399

**Comment by spiffxp** [comment]
After troubleshooting with dims, I manually set echoserver/VERSION to 2.1 and rebuilt

https://gist.github.com/spiffxp/1817115bb191ebf5d399d3112e439399

**Comment by dims** [comment]
Thanks @spiffxp i have updated this PR with the 2.1 version number. I have verified that the sha's look good

```
[dims@dims-mac 15:19] ~/go/src/k8s.io/kubernetes/test/images ⟩ curl -s 'https://gcr.io/v2/kubernetes-e2e-test-images/echoserver-amd64/manifests/2.1' | grep sha | head -1
      "digest": "sha256:76232f30d3c79bf7e602927143ebcbcb2e9205a17b53ba030cbd0661485fe60b"
[dims@dims-mac 15:19] ~/go/src/k8s.io/kubernetes/test/images ⟩ curl -s 'https://gcr.io/v2/kubernetes-e2e-test-images/echoserver/manifests/2.1' | grep -e arch -e sha
         "digest": "sha256:37fc8851c7a28e4a029965d3af5358e2cd729d26c4b1f84e932ca126e26c423e",
            "architecture": "amd64",
         "digest": "sha256:bd28c400792c677eafe842935e7bcc383e8b5ea4094359a90e30b57f36b464f9",
            "architecture": "arm",
         "digest": "sha256:75b0b3ffbb6bd6d489714ad2acf1ee3ec305302d0cdf6688aaf41867b023bf3a",
            "architecture": "arm64",
         "digest": "sha256:08c0e3eb900aaf9d95c75035a512a5bade825d1fd233af8834f4b95b6b5b9a62",
            "architecture": "ppc64le",
```

**Comment by ixdy** [comment]
I'm somewhat confused at how we ended up at version 2.1 (from 1.10).

**Comment by ixdy** [comment]
(shouldn't 2.x have been the pure-go version?)

**Comment by dims** [comment]
@ixdy since we moved from one repo to another and changed the base image used and did the multi-arch thing, i felt we could use 2.0. then we had trouble with the manifest list, so bumped upto 2.1. We can do 3.x when we have the pure go version ready.

**Pull request merged**
