### PR TITLE
Make controller register method keep same.

### PR DESCRIPTION
**Pull request by yanggangtony**
Signed-off-by: yanggang <gang.yang@daocloud.io>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Keep the controller-manager register method same.

#### Which issue(s) this PR fixes:
None

```release-note
None.
```

### CODE REVIEW

**Comment by aimuz** [comment]
/ok-to-test
/lgtm

> @yanggangtony: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.

Can you solve this problem?

**Comment by yanggangtony** [comment]
> /ok-to-test /lgtm
> 
> > @yanggangtony: Adding the "do-not-merge/release-note-label-needed" label because no release-note block was detected, please follow our [release note process](https://git.k8s.io/community/contributors/guide/release-notes.md) to remove it.
> 
> Can you solve this problem?

yes, i just add a none blank relase-note.
is that ok for ?

**Comment by aimuz** [comment]
>yes, i just add a none blank relase-note.
is that ok for ?

 Of course 

/assign @soltysh

**Comment by yanggangtony** [comment]
This pr have been a time for review.
Would you have time to review it?
@fedebongio @aimuz @songxiao-wang87

**Comment by yanggangtony** [comment]
This pr have been a time for review.
Would you have time to review it?
@jayunit100 @saad-ali

**Pull request closed without merging**
