### PR TITLE
The DownwardAPIHugePages feature is beta now, set true by default.

### PR DESCRIPTION
**Pull request by mysunshine92**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #https://github.com/kubernetes/kubernetes/pull/99610

#### Does this PR introduce a user-facing change?

```release-note
The DownwardAPIHugePages feature is now enabled by default.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by wgahnagl** [comment]
/assign @derekwaynecarr
do we want this defaulted to on ?

**Comment by wgahnagl** [comment]
please don't triage your own PRs

**Comment by ehashman** [comment]
/release-note-edit

```release-note
The DownwardAPIHugePages feature is now enabled by default.
```

**Review by ehashman — COMMENTED** [review]
Confirmed with @derekwaynecarr that this should have been defaulted to on in 1.22, 1.23 should be okay as well. This is a prereq for GA, but we can't target GA until it's defaulted to on.

https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2053-downward-api-hugepages#beta---ga-graduation

Let's make sure this gets a corresponding doc update.

/lgtm
/approve

**Pull request merged**
