### PR TITLE
Self nominate aojea as sig-network-reviewer

### PR DESCRIPTION
**Pull request by aojea**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

What started as a hobby to spend a few hours on weekends has become a passion 😄 
Now that IPv6 and dual-stack are taking off, and I'm more familiar with the networking code base of k/k, I'd like to continue helping.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
:+1: 
/sig network

**Comment by liggitt** [comment]
sgtm, will route to network folks for lgtm
/cc @thockin @danwinship

**Comment by BenTheElder** [comment]
@thockin @liggitt anyone want to `/approve`? :upside_down_face: 
/lgtm

**Comment by aojea** [comment]
Thanks all 😄

**Pull request merged**
