### PR TITLE
Automated cherry pick of #38865

### PR DESCRIPTION
**Pull request by codablock**
Cherry pick of #38865 on release-1.5.

#38865: Enable lazy initialization of ext3/ext4 filesystems

### CODE REVIEW

**Comment by saad-ali** [comment]
@codablock It's fine for the change to go out as part of 1.6, since this is a behavioral change, not strictly a bug fix, I am hesitant to cherry pick it to 1.5.x.

**Comment by codablock** [comment]
@saad-ali I understand what you say and would normally agree. The problem is however, that without this PR it takes up to 5 hours to format a large disk on Azure. Actually it's probably even more because most people seemed to cancel testing after a few hours. There is still a problem in kubelet which we were not able to identify which reduces write rates to unusual low values. This is not as bad (and thus unnoticed) on other clouds as they seem to support "zero on discard" for SSDs, which speeds this up a lot.

I feel that this PR is actually pretty safe. I investigated the kernel behavior in case lazy init is enabled and it turned out that it is handles this pretty well. The kernel does the same "zero on discard" optimization as the userland init from mkfs, so it finishes in a few seconds after mounting. When it detects "zero on discard" is not supported, it uses kernel internals (bios) to do the zeroing of the tables, which is a lot less resource consuming then a userland solution and is also much faster.

**Comment by saad-ali** [comment]
@codablock that's a valid argument. The Azure experience can be categorized as a bug and therefore this could be called a bug fix. My fear is that we may inadvertently break other systems. But if we're reasonably confident that we didn't break the major ones, then it should be fine to merge this.

@justinsb Can you help me verify if this change is ok for Amazon EBS? GCE PD tests in CI are still happy.

**Comment by justinsb** [comment]
It looks fine to me; we're running a more modern debian than containervm, and I think a comparable kernel to GCI.  I'm not aware of any AWS gotchas around this either.

If you remind me I can also test the 1.5.3 beta (if we have one).

But: we should also run the full test suite on AWS, probably daily.  It could give us a lot of signal - not just on this issue, but also e.g. multiple volumes in a StatefulSet, & our general EBS issues.

**Review by gmarek — APPROVED** [review]

**Comment by saad-ali** [comment]
> But: we should also run the full test suite on AWS, probably daily. It could give us a lot of signal - not just on this issue, but also e.g. multiple volumes in a StatefulSet, & our general EBS issues.

Yes! @zmerlynn @kubernetes/test-infra-admins 

Ok will approve this change for 1.5.3

**Comment by codablock** [comment]
Test failures seem to be unrelated to PR.
@k8s-bot kops aws e2e test this

**Comment by gmarek** [comment]
@k8s-bot kops aws e2e test this

**Comment by saad-ali** [comment]
Tracking AWS issue in https://github.com/kubernetes/kubernetes/issues/41152

**Comment by zmerlynn** [comment]
@k8s-bot kops aws e2e test this

**Comment by spxtr** [comment]
@k8s-bot cri e2e test this

**Pull request merged**
