### PR TITLE
Enable CPU CFS quota by default.

### PR DESCRIPTION
**Pull request by vishh**
Enabling cpu cfs quota by default for Guaranteed and BestEffort pods. This is one of the first steps for improving resource QoS.

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
LGTM

**Comment by alex-mohr** [comment]
I'm going to be a PITA and ask whether this is a backwards-compatible change?  If a user was submitting pods with 100m cpu share but using 4cpu, will they see different behavior?  Or is there no capping?

**Comment by vishh** [comment]
Assuming a pod's `request` is 100m and `limit` is `1`, in the past, a pod
can burst to use all the available CPU. With this change though, a pod will
be restricted to not burst beyond its `limit` which in this case is `1`
CPU.
Even in the past, bursting was not guaranteed, since under load, a pod will
only get what it requested.
To continue to have unlimited (node capacity) burst, they can avoid setting
`limits`.

**Comment by alex-mohr** [comment]
@vishh That seems like a user-facing change?  E.g., users create objects in 1.1 cluster, see behavior X.  Cluster gets upgraded to 1.2, behavior significantly changes causing breakage/outage of their app?  Tell me we won't have any unhappy customers when 1.2 rolls out to GKE.

**Comment by vishh** [comment]
@alex-mohr: I see your point. It is a user facing change, and it is a change that we intend to do as part of improving resource management. We should include this in our release notes.

**Comment by alex-mohr** [comment]
@vishh If you haven't, can you run this past @bgrant0607 too as API compliance czar?

@k8s-bot unit test this

**Comment by vishh** [comment]
@alex-mohr: Just checked with @bgrant0607 offline. He suggested to include the release notes in this PR, which should be picked up when the release notes for v1.2 is compiled.

**Comment by vishh** [comment]
**Release Notes for v1.2**
Note: This is a **breaking** change

Cpu resource `limits` on containers will be enforced by default. Containers cannot use CPU beyond the value specified in `limits`. 
To burst on CPU you can choose one of the following options:
1. Specify CPU `requests` instead of `limits`. `requests` are soft limits which are enforced only under contention (or)
2. Set `--cpu-cfs-quota=false` on all the kubelets.

**Comment by vishh** [comment]
@k8s-bot: unit test this

**Comment by bgrant0607** [comment]
We're going to evolve resource isolation and scheduling behavior over time, hopefully for the better, in general. This will unavoidably change behavior, which may cause problems for some users. However, the problems they'd encounter are possible already given the lack of strong isolation and usage-based scheduling. Therefore, I think enabling this by default is the right approach, given that we can describe how users and/or administrators can achieve the previous behavior.

**Comment by vishh** [comment]
@k8s-bot: unit test this

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by a-robinson** [comment]
@roberthbailey and I got curious about this today -- does this enforce hard-capping of the really small CPU limits on the master components (e.g. [kube-apiserver](https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-apiserver/kube-apiserver.manifest))

cc @wojtek-t

**Comment by a-robinson** [comment]
@roberthbailey pointed out that #21086 looks related - once this actually takes effect, it could cause real problems on the master if the CPU limits are actually enforced as written.

**Comment by vishh** [comment]
Our Container VM base image still does not have hardcapping enabled by
default. So this change *should* be a no-op until a new VM is released.

**Pull request merged**
