### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by sanjeev003**
#### Which issue(s) this PR fixes:

# Added comment for  ".tags*"

#### Does this PR introduce a user-facing change?

```
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sanjeev003** [comment]
Hey please do remove the unwanted labels and add GoodFirstIssue label , am unable to do that because edit option is not showing

**Comment by carlory** [comment]
why we need it?

**Comment by sanjeev003** [comment]
> why we need it?

Every satement has the comments except the one I had wrote in the gitignore file it would have been better if it also had . Also others will also knows the importance of the  ".tags*"

**Comment by charles-chenzz** [comment]
imo it's trivial edit. we don't actually need it I think

**Comment by sanjeev003** [comment]
Yeah just started contributing to the open source projects it's not really a big thing 😅

**Comment by dims** [comment]
/close

this is a trivial change https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits

**Pull request closed without merging**
