### PR TITLE
Reproducible builds - fix kubeadm init man page

### PR DESCRIPTION
**Pull request by dims**
When we generate the man pages for kubeadm init, the section for "certs"
is not sorted and hence builds are not reproducible. So let's just sort
it.

Please see https://github.com/kubernetes/kubernetes/issues/70131#issuecomment-465944594 for the problem snippet

Change-Id: I92ada1069905919613843f58cb186a85b79963b1

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
nice side effect - see the correct sorting when you run`kubeadm init --help`

**Review by fabriziopandini — APPROVED** [review]
@dims Nice one!
/approve
/lgtm

**Comment by praseodym** [comment]
I think this also changes the order in which the certs phases get executed, because with this change kubeadm tries to create the apiserver cert (first in alphabetical order) before creating the actual CA cert.

```
[certs] Using certificateDir folder "/etc/kubernetes/pki"
error execution phase certs/apiserver: couldn't load CA certificate ca: couldn't load ca certificate authority from /etc/kubernetes/pki
```

**Comment by neolit123** [comment]
/hold
> So these test failures are not flakes :)

my concern as well; the order matters.
i need to read more about the reproducible builds, but technically the order is a subject of change between releases.

i.e. where is this diff coming from?
https://github.com/kubernetes/kubernetes/issues/70131#issuecomment-465944594

**Comment by praseodym** [comment]
> my concern as well; the order matters.
> i need to read more about the reproducible builds, but technically the order is a subject of change between releases.
> 
> e.g where is this diff coming from?
> [#70131 (comment)](https://github.com/kubernetes/kubernetes/issues/70131#issuecomment-465944594)

Reproducible builds mean that build artifacts do not differ between builds of the same release; change between releases is fine. Invoking `kubeadm init --help` sometimes gives me a different order, so if that output is used for documentation it is definitely not reproducible.

The order that's printed is always a valid one, i.e. CAs (etcd-ca, front-proxy-ca, ca) first and certificates second -- not a static order but definitely not random either.

**Comment by neolit123** [comment]
> Invoking kubeadm init --help sometimes gives me a different order, so if that output is used for documentation it is definitely not reproducible.

i don't see how that can happen, the help output of the cert phases is alphabetic (which is wrong BTW cc @fabriziopandini we need to have them in the order of execution)

```
certs                      Certificate generation
  /apiserver                 Generate the certificate for serving the Kubernetes API
  /apiserver-etcd-client     Generate the certificate the apiserver uses to access etcd
  /apiserver-kubelet-client  Generate the certificate for the API server to connect to kubelet
  /ca                        Generate the self-signed Kubernetes CA to provision identities for other Kubernetes components
  /etcd-ca                   Generate the self-signed CA to provision identities for etcd
  /etcd-healthcheck-client   Generate the certificate for liveness probes to healtcheck etcd
  /etcd-peer                 Generate the certificate for etcd nodes to communicate with each other
  /etcd-server               Generate the certificate for serving etcd
  /front-proxy-ca            Generate the self-signed CA to provision identities for front proxy
  /front-proxy-client        Generate the certificate for the front proxy client
  /sa                        Generate a private key for signing service account tokens along with its public key
```

but the actual execution order for me ends up being:
```
front-proxy-ca
front-proxy-client
etcd-ca
etcd-server
etcd-healthcheck-client
apiserver-etcd-client
etcd-peer
ca
apiserver-kubelet-client
apiserver
sa
```

executing them alphabetically is definitely wrong.

**Comment by dims** [comment]
/milestone v1.16

Ack, let's deal with it in the next release

**Comment by neolit123** [comment]
@dims @praseodym 
send replacement PR here:
https://github.com/kubernetes/kubernetes/pull/78556

/close

**Pull request closed without merging**
