### PR TITLE
fix kubelet tls overwrite issue

### PR DESCRIPTION
**Pull request by adohe-zz**
@lavalamp apply the same thing to kubelet. @dchen1107 ptal.

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/23473)

### CODE REVIEW

**Comment by dchen1107** [comment]
Thanks for the refactory work!

LGTM

**Comment by AdoHe** [comment]
the Jenkins GCE Node e2e failed, and the root cause is:
```
/tmp/hudson6651388427524392552.sh: line 4: cd: go/src/k8s.io/kubernetes: No such file or directory
```
@dchen1107 could you tell me what I should do about this?

**Comment by AdoHe** [comment]
@dchen1107 kindly ping.

**Comment by AdoHe** [comment]
@dchen1107 kindly ping.

**Comment by AdoHe** [comment]
@dchen1107 kindly ping.

**Comment by dchen1107** [comment]
LGTM

**Comment by goltermann** [comment]
@dchen1107 Can you LGTM post-rebase?  That's all this one needs.

**Comment by dchen1107** [comment]
LGTM again

**Comment by goltermann** [comment]
@k8s-bot please e2e test this #IGNORE

**Comment by AdoHe** [comment]
@k8s-bot please e2e test this #IGNORE.

**Pull request merged**
