### PR TITLE
Fix hits in help strings of kubectl get command

### PR DESCRIPTION
**Pull request by hurf**
Removed duplicated 'nodes (no)', added 'secret' for resource type.

A small issue found while working on #10742, for #10742 may need more disscussion. I create another PR for this certain issue.

### CODE REVIEW

**Comment by hurf** [comment]
@erictune - can you look at this small patch? It fixes trival error in help string and I think its unnecessary to create a new issue for it.

**Comment by hurf** [comment]
As @jlowdermilk pointed out, use long resource names to avoid confusion.

**Comment by jlowdermilk** [comment]
LGTM
@k8s-bot ok to test.

**Comment by erictune** [comment]
LGTM

**Comment by derekwaynecarr** [comment]
It seems weird that we have mixed case for certain resource fully qualified names.  Now that the Rest API moved to all lower forms, seems like we should have been consistent in the CLI.  @deads2k shouldn't the all lower forms work as well?  Ie limitRange should be same as limitrange

**Comment by jlowdermilk** [comment]
@derekwaynecarr lower case forms do indeed work just fine. I assumed the camel casing was for more for readability, but it's definitely not required.

**Comment by hurf** [comment]
Camel casing mixed with all lower casing indeed looks weired. If it is required I can fix it.

**Comment by erictune** [comment]
needs rebase

**Comment by hurf** [comment]
@erictune - Rebased and canceled camel casing as @derekwaynecarr instructed,

**Comment by derekwaynecarr** [comment]
LGTM

**Comment by bgrant0607** [comment]
LGTM, but we'd need to cherrypick it into the 1.0 release if we were to merge this.

**Pull request merged**
