### PR TITLE
Automated cherry pick of #54184

### PR DESCRIPTION
**Pull request by MrHohn**
Cherry pick of #54184 on release-1.7.

#54184: Fix retry logic in service controller

### CODE REVIEW

**Comment by MrHohn** [comment]
/unassign @matchstick
/assign @wojtek-t 
for cherrypick approval.

**Comment by wojtek-t** [comment]
@MrHohn - can you please add a user-friengly release-note to the original PR?

**Comment by MrHohn** [comment]
@wojtek-t Thanks! Sure, release-note added to the original PR.

**Comment by MrHohn** [comment]
Humm...Seems like `pull-kubernetes-e2e-gce` timed out right before finishing it:
```
W1030 16:06:46.327] 2017/10/30 16:06:46 main.go:245: Saved XML output to /workspace/_artifacts/junit_runner.xml.
W1030 16:06:46.407] 2017/10/30 16:06:46 main.go:311: Something went wrong: encountered 1 errors: [error during ./hack/e2e-internal/e2e-down.sh (interrupted): signal: interrupt]
W1030 16:06:46.408] Traceback (most recent call last):
W1030 16:06:46.409]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 856, in <module>
W1030 16:06:46.429]     main(parse_args())
W1030 16:06:46.429]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 699, in main
W1030 16:06:46.429]     mode.start(runner_args)
W1030 16:06:46.429]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 241, in start
W1030 16:06:46.429]     check_env(env, self.command, *args)
W1030 16:06:46.429]   File "/workspace/./test-infra/jenkins/../scenarios/kubernetes_e2e.py", line 64, in check_env
W1030 16:06:46.429]     subprocess.check_call(cmd, env=env)
W1030 16:06:46.430]   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
W1030 16:06:46.462]     raise CalledProcessError(retcode, cmd)
W1030 16:06:46.462] subprocess.CalledProcessError: Command '('kubetest', '-v', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--build=bazel', '--stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce', '--up', '--down', '--test', '--provider=gce', '--cluster=e2e-2477', '--gcp-network=e2e-2477', '--extract=local', '--gcp-node-image=gci', '--gcp-project=k8s-jkns-pr-gce-etcd3', '--gcp-zone=us-central1-f', '--ginkgo-parallel=30', '--runtime-config=batch/v2alpha1=true,admissionregistration.k8s.io/v1alpha1=true', '--test_args=--ginkgo.skip=\\[Slow\\]|\\[Serial\\]|\\[Disruptive\\]|\\[Flaky\\]|\\[Feature:.+\\] --minStartupPods=8', '--timeout=65m')' returned non-zero exit status 1
E1030 16:06:46.468] Command failed
I1030 16:06:46.468] process 459 exited with code 1 after 70.7m
E1030 16:06:46.469] FAIL: pull-kubernetes-e2e-gce
```

One more try
/retest

**Pull request merged**
