### PR TITLE
cleanup: Remove quobyte volume plugins from k8s codebase

### PR DESCRIPTION
**Pull request by Jiawei0227**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

This PR removes quobyte storage plugin from k8s codebase.
The quobyte plugin has been deprecated since v1.22
https://groups.google.com/g/kubernetes-sig-storage/c/IDIVmifA1FA

The code removal removes the dependency of quobyte api and reduce
maintenance burden from storage perspective.

The quobyte API, per k8s api policy, will not be removed. Whenever user tries to create PV using the inline quobyte API, the following event will show in the pod:

```
Warning  FailedMount  7m35s (x55 over 22m)  kubelet, kubernetes-minion-group-kq16  Unable to attach or mount volumes: unmounted volumes=[mypvc], unattached volumes=[mypvc kube-api-access-22hdk[]: failed to get Plugin from volumeSpec for volume "mypvc" err=no volume plugin matched 
```

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
action required: intree volume plugin quobyte support is been completely removed from Kubernetes.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig storage
/assign @msau42 @xing-yang @liggitt

### CODE REVIEW

**Comment by xing-yang** [comment]
As documented here, quobyte plugin was deprecated in 1.22:
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#types-of-persistent-volumes
We also mentioned that it is targeted for removal in 1.25 in the following blog:
https://kubernetes.io/blog/2021/12/10/storage-in-tree-to-csi-migration-status-update/#timeline-and-status

**Comment by liggitt** [comment]
/approve
for dep change

**Pull request merged**
