### PR TITLE
Fix fluent-bit configuration for GCE Windows.

### LINKED ISSUE #101284: GCE Windows with fluent-bit logging produces low quality structured logs to stackdriver.
#### What happened:
The default fluent-bit configuration for GCE Windows nodes produces unparsed JSON logs and does not forward container logs.

#### What you expected to happen:
Container log output is produced.

#### How to reproduce it (as minimally and precisely as possible):

1. Preinstall fluent-bit on a given windows image.
1. Start a GCE Windows e2e cluster and view the stackdriver output for pods.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.20+
- Cloud provider or hardware configuration: GKE/GCE
- OS (e.g: `cat /etc/os-release`): Windows
- Kernel (e.g. `uname -a`): Any version
- Install tools: fluent-bit
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by jeremyje**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fixes the fluent-bit for GCE Windows configuration.

* Upgrade to Fluent-bit 1.7.3 and flb-exporter 0.16.2
* Container logs are processed as json logs properly. (See: https://github.com/fluent/fluent-bit/issues/3387)
* Aligns with the fluent-bit configuration that Linux provides.
* Use best practice of moving the position DBs outside of the logs directory into their own directory. This simplifies file listing as it relates to log rotation.
* fluent-bit service logging is now info instead of debug.

#### Which issue(s) this PR fixes:

Fixes #101284

#### Does this PR introduce a user-facing change?

```release-note
Logging for GCE Windows clusters will be more accurate and complete when using Fluent-bit.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jeremyje** [comment]
/hold
There's some log quality issues in kubelet that need to be resolved.

**Comment by pjh** [comment]
/lgtm

Thanks for the helpful PR description!

**Pull request merged**
