### PR TITLE
feat: remove CheckNodeMemoryPressure/DiskPressure/PIDPressure/Condition

### LINKED ISSUE #84100: [scheduler] Cleanup CheckNodeMemoryPressure/DiskPressure/PIDPressure/Condition predicates
**What would you like to be added**:

Remove the following predicates

```go
		predicates.CheckNodeMemoryPressurePred,	
		predicates.CheckNodeDiskPressurePred,	
		predicates.CheckNodePIDPressurePred,	
		predicates.CheckNodeConditionPred,
```

**Why is this needed**:

The TaintNodeByConditions was graduate into a stable version in https://github.com/kubernetes/kubernetes/pull/82703, we could now remove the unused predicates for cleanup.

/assign
/sig scheduling
/kind cleanup
cc/ @ahg-g

### PR DESCRIPTION
**Pull request by draveness**
/kind cleanup
/sig scheduling
/assign @ahg-g

**What this PR does / why we need it**:

TaintNodesByCondition was graduated to the stable version, and the following predicates have been disabled by default since 1.12. We could remove them:

+ CheckNodeMemoryPressure
+ CheckNodeDiskPressure
+ CheckNodePIDPressure
+ CheckNodeCondition 

**Which issue(s) this PR fixes**:

Fixes #84100

**Does this PR introduce a user-facing change?**:

```release-note
TaintNodesByCondition was graduated to GA, CheckNodeMemoryPressure, CheckNodePIDPressure, CheckNodeDiskPressure, CheckNodeCondition were accidentally removed since 1.12, the replacement is to use CheckNodeUnschedulablePred
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by ahg-g** [comment]
> **Does this PR introduce a user-facing change?**:
> 
> ```
> TaintNodesByCondition was graduated to GA, CheckNodeMemoryPressure, CheckNodePIDPressure, CheckNodeDiskPressure, CheckNodeCondition predicates was removed.
> ```

Please add that "CheckNodeMemoryPressure, CheckNodePIDPressure, CheckNodeDiskPressure, CheckNodeCondition were accidentally removed since 1.12, the replacement is to use CheckNodeUnschedulablePred"

**Comment by draveness** [comment]
/retest

Regards,
Draven

**Comment by AthinaKyriakou** [comment]
Should the [documentation](https://kubernetes.io/docs/reference/scheduling/policies/) be updated too?

**Comment by AthinaKyriakou** [comment]
Shouldn't the [documentation](https://kubernetes.io/docs/reference/scheduling/policies/) be updated too?

**Comment by draveness** [comment]
> Shouldn't the [documentation](https://kubernetes.io/docs/reference/scheduling/policies/) be updated too?

fair enough, create a pull request against website https://github.com/kubernetes/website/pull/27903

**Pull request merged**
