### PR TITLE
fix:handle error and remove Redundant type conversion

### PR DESCRIPTION
**Pull request by falser101**
Signed-off-by: jianfei.zhang <jianfei.zhang@daocloud.io>
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
handle error and remove Redundant type conversion

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
/assign @dims
per https://github.com/kubernetes/kubernetes/pull/111172#issuecomment-1185253470

/unassign

**Comment by dims** [comment]
please see the failures in many of the CI jobs.

```
# k8s.io/kubernetes/pkg/util/ipset
pkg/util/ipset/ipset.go:285:39: cannot use set.SetType (variable of type Type) as type string in array or slice literal
```

**Comment by falser101** [comment]
> @falser101: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-kubernetes-integration	[33598fd](https://github.com/kubernetes/kubernetes/commit/33598fd1a8b87caa79abd83a043a6ee3581bf08e)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111172/pull-kubernetes-integration/1549068769094012928)	true	`/test pull-kubernetes-integration`
> pull-kubernetes-e2e-kind-ipv6	[33598fd](https://github.com/kubernetes/kubernetes/commit/33598fd1a8b87caa79abd83a043a6ee3581bf08e)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111172/pull-kubernetes-e2e-kind-ipv6/1549068769182093312)	true	`/test pull-kubernetes-e2e-kind-ipv6`
> pull-kubernetes-typecheck	[33598fd](https://github.com/kubernetes/kubernetes/commit/33598fd1a8b87caa79abd83a043a6ee3581bf08e)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111172/pull-kubernetes-typecheck/1549068769798656000)	true	`/test pull-kubernetes-typecheck`
> pull-kubernetes-verify-govet-levee	[33598fd](https://github.com/kubernetes/kubernetes/commit/33598fd1a8b87caa79abd83a043a6ee3581bf08e)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111172/pull-kubernetes-verify-govet-levee/1549068770637516800)	true	`/test pull-kubernetes-verify-govet-levee`
> pull-kubernetes-e2e-kind	[33598fd](https://github.com/kubernetes/kubernetes/commit/33598fd1a8b87caa79abd83a043a6ee3581bf08e)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111172/pull-kubernetes-e2e-kind/1549068769144344576)	true	`/test pull-kubernetes-e2e-kind`
> pull-kubernetes-conformance-kind-ga-only-parallel	[33598fd](https://github.com/kubernetes/kubernetes/commit/33598fd1a8b87caa79abd83a043a6ee3581bf08e)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111172/pull-kubernetes-conformance-kind-ga-only-parallel/1549068769219842048)	true	`/test pull-kubernetes-conformance-kind-ga-only-parallel`
> pull-kubernetes-e2e-gce-ubuntu-containerd	[33598fd](https://github.com/kubernetes/kubernetes/commit/33598fd1a8b87caa79abd83a043a6ee3581bf08e)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111172/pull-kubernetes-e2e-gce-ubuntu-containerd/1549068769022709760/)	true	`/test pull-kubernetes-e2e-gce-ubuntu-containerd`
> pull-kubernetes-e2e-gce-100-performance	[33598fd](https://github.com/kubernetes/kubernetes/commit/33598fd1a8b87caa79abd83a043a6ee3581bf08e)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111172/pull-kubernetes-e2e-gce-100-performance/1549068769408585728)	true	`/test pull-kubernetes-e2e-gce-100-performance`
> pull-kubernetes-e2e-gci-gce-ipvs	[33598fd](https://github.com/kubernetes/kubernetes/commit/33598fd1a8b87caa79abd83a043a6ee3581bf08e)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111172/pull-kubernetes-e2e-gci-gce-ipvs/1549068769307922432)	false	`/test pull-kubernetes-e2e-gci-gce-ipvs`
> pull-kubernetes-unit	[33598fd](https://github.com/kubernetes/kubernetes/commit/33598fd1a8b87caa79abd83a043a6ee3581bf08e)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111172/pull-kubernetes-unit/1549068769265979392)	true	`/test pull-kubernetes-unit`
> pull-kubernetes-verify	[33598fd](https://github.com/kubernetes/kubernetes/commit/33598fd1a8b87caa79abd83a043a6ee3581bf08e)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111172/pull-kubernetes-verify/1549068771476377600)	true	`/test pull-kubernetes-verify`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=111172). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Afalser101). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

/retest

**Comment by falser101** [comment]
> please see the failures in many of the CI jobs.
> 
> ```
> # k8s.io/kubernetes/pkg/util/ipset
> pkg/util/ipset/ipset.go:285:39: cannot use set.SetType (variable of type Type) as type string in array or slice literal
> ```

please help review
@dims @liggitt

**Comment by falser101** [comment]
> @falser101: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-kubernetes-e2e-kind	[49e7a7b](https://github.com/kubernetes/kubernetes/commit/49e7a7b51da4d2dd23f348bc116d1c254971c2bb)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111172/pull-kubernetes-e2e-kind/1549283020542840832)	true	`/test pull-kubernetes-e2e-kind`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=111172). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Afalser101). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

/retest-required

**Comment by falser101** [comment]
@dims please help review

**Comment by falser101** [comment]
> /retest-required

/retest-required

**Pull request merged**
