### PR TITLE
updated appc/spec and camlistore/ godeps to fix broken godep restore

### LINKED ISSUE #19672: godep restore broken by github.com/camlistore/camlistore/pkg/errorutil
`github.com/camlistore/camlistore/pkg/errorutil` was removed by https://github.com/camlistore/camlistore/commit/40be4d8da29a164513347d54334a3aed849585db, which is causing `godep restore` to complain that
```
godep: error restoring dep (github.com/camlistore/camlistore/pkg/errorutil): cannot find package "github.com/camlistore/camlistore/pkg/errorutil" in any of:
	/usr/local/go/src/github.com/camlistore/camlistore/pkg/errorutil (from $GOROOT)
	/Users/stclair/go/src/github.com/camlistore/camlistore/pkg/errorutil (from $GOPATH)
```

### PR DESCRIPTION
**Pull request by jdef**
- fixes #19672

### CODE REVIEW

**Comment by jdef** [comment]
@lavalamp PTAL. this is blocking other Godeps changes that we need to make

**Comment by jdef** [comment]
@k8s-bot e2e test this

**Comment by jdef** [comment]
@davidopp PTAL

**Comment by lavalamp** [comment]
LGTM

(in the future @ mentioning k8s-oncall may get you faster response for something like this)

**Comment by jdef** [comment]
ok, thanks @lavalamp - will remember that

**Comment by alex-mohr** [comment]
@k8s-bot test this
@k8s-bot unit test this

**Pull request merged**
