### PR TITLE
support cross resource group for azure file

### LINKED ISSUE #64428: specify resource group for azure file PVC dynamic creation
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
specify `resourcegroup` in azure file storage class so that user could specify external resource group

```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile
provisioner: kubernetes.io/azure-file
parameters:
  storageaccount: EXISTING_STORAGE_ACCOUNT
  resourcegroup: RESOURCE_GROUP_NAME
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/assign

### PR DESCRIPTION
**Pull request by andyzhangx**
**What this PR does / why we need it**:
support cross resource group for azure file: by `resourceGroup` field, azure cloud provider will create azure file on user specified resource group

```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azurefile-rg
provisioner: kubernetes.io/azure-file
parameters:
  resourceGroup: RESOURCE_GROUP_NAME
  storageAccount: EXISTING_STORAGE_ACCOUNT
```
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #64428

**Special notes for your reviewer**:

**Release note**:

```
resourcegroup parameter is added to AzureFile storage class to support azure file dyanmic provision in cross resource group.
```

/kind bug
/sig azure
/assign @feiskyer 
cd @khenidak

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]
LGTM

**Comment by feiskyer** [comment]
Could you also add comment on `resourcegroup` parameter in release note? e.g.

`resourcegroup` parameter is added to AzureFile storage class to support azure files in cross resource groups.

**Comment by andyzhangx** [comment]
> Could you also add comment on resourcegroup parameter in release note

It's done, thanks.

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
