### PR TITLE
Fix availableReplicas validation

### PR DESCRIPTION
**Pull request by 0xmichalis**
An available replica is a ready replica, not the other way around

@kubernetes/sig-apps-bugs caught while testing https://github.com/kubernetes/kubernetes/pull/42097

### CODE REVIEW

**Comment by kargakis** [comment]
Missed this when @lavalamp asked me to update the conditionals in https://github.com/kubernetes/kubernetes/pull/36243#discussion_r88747670

/o\

**Comment by smarterclayton** [comment]
@k8s-bot gci gce e2e test this

**Pull request merged**
