### PR TITLE
Automated cherry pick of #71834 upstream release 1.13

### PR DESCRIPTION
**Pull request by lbernail**
Cherry pick of #71834 on release-1.13.

#71834 : New sysctls to improve pod termination

/sig network
/area ipvs

/assign @m1093782566

### CODE REVIEW

**Comment by m1093782566** [comment]
/assign @foxish 

for cherry-pick approval.

**Comment by m1093782566** [comment]
@feiskyer 

#72100 is intended to cherry-pick the bug fix in v1.11 while this PR is intended to pick in v1.13.

**Comment by feiskyer** [comment]
oh, yep.

**Pull request merged**
