### PR TITLE
Automated cherry pick of #38338 #37413

### PR DESCRIPTION
**Pull request by kerneltime**
Cherry pick of #38338 #37413 on release-1.5.

#38338: Fix space in volumePath in vSphere
#37413: Fix for unmount volume to take in volumePath instead of

### CODE REVIEW

**Comment by BaluDontu** [comment]
@thockin : Can you approve this cherry pick request. This request has been on hold from past 6 days.

**Comment by thockin** [comment]
lgtm

@saad-ali who is cherry-czar for 1.5?

**Comment by kerneltime** [comment]
@k8s-bot verify test this

**Comment by kerneltime** [comment]
@k8s-bot verify test this

**Comment by spxtr** [comment]
@k8s-bot test this
https://github.com/kubernetes/test-infra/issues/1598

**Comment by saad-ali** [comment]
> @saad-ali who is cherry-czar for 1.5?

Still me :\

**Pull request merged**
