### PR TITLE
Mising deps

### PR DESCRIPTION
**Pull request by freeformz**
Transitive system dependent import, discovered during upgrade to newer
godep.

### CODE REVIEW

**Comment by eparis** [comment]
ok to test

**Comment by eparis** [comment]
Note that I cherry-picked this into #18706 which reverts the changes I made to `hack/verify-godep.sh` yesterday.

@freeformz  maybe it would be nice if godep had a 'verify' option and I didn't have to do it myself.

**Comment by lavalamp** [comment]
Is this still relevant?

**Comment by freeformz** [comment]
Nope, closing.

**Pull request closed without merging**
