### PR TITLE
Fix TestCertificateController index out of range panic

### LINKED ISSUE #46477: Panic in TestCertificateController test
Seen in: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46124/pull-kubernetes-unit/32795/?log#k8siokubernetespkgcontrollercertificates-testcertificatecontroller

ref: #46124

`k8s.io/kubernetes/pkg/controller/certificates TestCertificateController 0.01s`

```
certificate_controller_test.go:73: expected 3 actions
certificate_controller_test.go:79: unexpected action: testing.UpdateActionImpl{ActionImpl:testing.ActionImpl{Namespace:"", Verb:"update", Resource:schema.GroupVersionResource{Group:"certificates.k8s.io", Version:"v1beta1", Resource:"certificatesigningrequests"}, Subresource:"approval"}, Object:(*v1beta1.CertificateSigningRequest)(0xc4202ea540)}
panic: runtime error: index out of range
/usr/local/go/src/testing/testing.go:622 +0x55f
/usr/local/go/src/runtime/panic.go:489 +0x2f0
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/certificates/certificate_controller_test.go:81 +0x852
/usr/local/go/src/testing/testing.go:657 +0x108
/usr/local/go/src/testing/testing.go:697 +0x544
```

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #46477  

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
@k8s-bot ok to test

**Comment by NickrenREN** [comment]
@k8s-bot ok to test

**Comment by NickrenREN** [comment]
@xiangpengzhao  fyi #46383

**Comment by xiangpengzhao** [comment]
Thanks @NickrenREN !

This is just a quick fix, dup of #46383.

/close

**Pull request closed without merging**
