### PR TITLE
[Do Not Merge] hack: Try out PGO for kube-apiserver

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
This commit attempts to try out the new profile
guided optimization feature of golang. 
It includes a CPU profile of the API Server taken from a scale run of a 100 node test.

The profile was taken from this run: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1634030214260461568/
/hold

### CODE REVIEW

**Comment by MadhavJivrajani** [comment]
Gonna try with a kubetest profile instead to avoid spinning up 100 real nodes

**Comment by MadhavJivrajani** [comment]
/test pull-perf-tests-clusterloader2-kubemark
(spins up 4 real nodes)

**Comment by MadhavJivrajani** [comment]
The pgo flag right now is passed to _all_ components and not just api server. Not sure yet how to do it because it seems like all components are built by passing packages names together to go install. 

Not sure how to isolate that, trying it out this way for now. Pgo gives iterative and source stability, and they claim that a non representative benchmark will not effect performance, so I'm hoping on average the other components "ignore" this profile

**Comment by linsite** [comment]
> /test pull-kubernetes-e2e-gce-100-performance

hi @MadhavJivrajani , do we have any results?

**Pull request closed without merging**
