### PR TITLE
Automated cherry pick of #62676: Update kube-dns to Version 1.14.10

### PR DESCRIPTION
**Pull request by MrHohn**
Cherry pick of #62676 on release-1.9.

#62676: Update kube-dns to Version 1.14.10.

```release-note
Update kube-dns to Version 1.14.10. Major changes:
- Fix a bug in DNS resolution for externalName services
and PTR records that need to query from upstream nameserver.
```

### CODE REVIEW

**Comment by MrHohn** [comment]
Waiting for https://github.com/kubernetes/kubernetes/pull/62676 to be merged first.

**Comment by MrHohn** [comment]
cc @bowei @grayluck

**Comment by MrHohn** [comment]
The original PR is finally merged (took way too long)! Assigning @mbohlool for cherrypick approval. Sorry for the delay.
/assign @mbohlool

**Comment by mbohlool** [comment]
Approved this CP after cut as an exception after discussing it with @MrHohn

**Comment by grayluck** [comment]
sig/network

**Pull request merged**
