### PR TITLE
remove unnecessary check

### LINKED ISSUE #117026: This statement will always be ture
https://github.com/kubernetes/kubernetes/blob/d89d5ab2680bc74fe4487ad71e514f4e0812d9ce/pkg/apis/networking/validation/validation.go#L602

### PR DESCRIPTION
**Pull request by mouuii**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
remove the unnecessary code

#### Which issue(s) this PR fixes:
Fixes #117026

```release-note
NONE
```

### CODE REVIEW

**Comment by mouuii** [comment]
can anyone PTLA @andrewsykim @caseydavenport

**Comment by aojea** [comment]
at a quick look on the test, I couldn't find one validating against an ingressClass with an empty (nil) scope, can you please add one test case for that?

**Comment by danwinship** [comment]
/title remove unnecessary check

(would be good to update the commit message too)

**Comment by danwinship** [comment]
/retitle remove unnecessary check

(would be good to update the commit message too)

**Comment by mouuii** [comment]
> at a quick look on the test, I couldn't find one validating against an ingressClass with an empty (nil) scope, can you please add one test case for that?

added ,PTAL

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
