### PR TITLE
Adding a replication controller for all monitoring pods

### LINKED ISSUE #3558: kubernetes-gke{,-ci} jobs have been aborting since 6pm on 1/15
All builds after #3489 and <strike>3550</strike> were merged have started failing on the GKE provider.

### PR DESCRIPTION
**Pull request by vishh**
Removed auth for Grafana to facilitate usage via service proxy on the api-server.
Added a grafana service
Removed elasticsearch dependency for monitoring - faster startup times.

This time 'monitoring.sh' has been updated unlike #3489 

Fixes #3558, #2408

### CODE REVIEW

**Comment by vishh** [comment]
cc @zmerlynn

**Comment by zmerlynn** [comment]
Did you explicitly check with the GKE provider? The GCE provider was a failure, the GKE provider outright hung for some reason.

**Comment by vishh** [comment]
@zmerlynn: Did you test this PR or are you referring to the previous failures?

**Comment by zmerlynn** [comment]
I haven't tested this PR. The previous PR was failing on GKE, so I was
asking if you explicitly tested this one on the GKE provider (since it's
commonly not tested).

**Comment by vishh** [comment]
I haven't. The failure was due to the fact that the monitoring e2e test was not updated after placing heapster pods in a replication controller.

**Comment by vishh** [comment]
Ran 'monitoring.sh' on GKE and it passed.

**Comment by zmerlynn** [comment]
Awesome, thanks.

**Pull request merged**
