### PR TITLE
kubectl: Removes dependency on util/interrupt by copying this code into kubectl

### PR DESCRIPTION
**Pull request by seans3**
* Removes one of the few kubectl dependencies on Kubernetes core.
* Copies pkg/util/interrupt into kubectl (pkg/kubectl/util/interrupt).

Helps fix:
https://github.com/kubernetes/kubectl/issues/80

```release-note
NONE
```

/kind cleanup
/area kubectl
/assign

### CODE REVIEW

**Review by soltysh — CHANGES_REQUESTED** [review]
/hold 
We should revive and finish https://github.com/kubernetes/utils/pull/47 rather than copying those here.

**Comment by seans3** [comment]
> /hold
> We should revive and finish [kubernetes/utils#47](https://github.com/kubernetes/utils/pull/47) rather than copying those here.

I disagree. We've been blocked on that PR for close to 6 months. By copying the interrupt.go instead of moving it, our PR does not affect the other PR. And it unblocks us. Our PR removes 5 of the remaining 15 dependencies.

**Comment by soltysh** [comment]
@seans3 we still have others PRs to address let's get them merged, and I don't get https://github.com/kubernetes/utils/pull/87 merged by next Fri I'll let this in.

**Review by soltysh — APPROVED** [review]
/hold cancel
it'll take me some more time to get interrupt in utils, let's move this as is for now.

**Pull request merged**
