### PR TITLE
kubeadm: special case some KubeletConfiguration defaults on Windows

### LINKED ISSUE #2967: windows: mutate additional kubeletconfiguration fields on join
PRs for the points listed below:

- https://github.com/kubernetes/kubernetes/pull/123136
- https://github.com/kubernetes/kubernetes/pull/123137
----

during join of a Windows worker node we download the kubelet-config from the cluster as usual, then we apply some mutations, notably around problematic paths with drive on Windows:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/componentconfigs/kubelet_windows.go

but we are missing some more fields that do not work on Windows.

the kubelet defaults for `EnforceNodeAllocatable=pods` or `CgroupsPerQOS=true` are simply rejected on Windows with errors:
```
E1123 02:11:01.358586    5616 server.go:224] "Failed to validate kubelet configuration" err="[invalid configuration: CgroupsPerQOS (--cgroups-per-qos) true is not supported on Windows, invalid configuration: EnforceNodeAllocatable (--enforce-node-allocatable) [pods] is not supported on Windows]" path="&TypeMeta{Kind:,APIVersion:,}"
```

why are these the defaults, who knows...but that's not OS portable.

what can be done is override the defaults similarly to this:
https://github.com/kubernetes-sigs/sig-windows-tools/blob/28a4c4f4e9e0b65d4d1ed1841e11eca5a62bfafe/hostprocess/PrepareNode.ps1#L73

but using the kubeletconfiguration struct.
https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/

```
enforceNodeAllocatable: ""
cgroupsPerQOS: false
```

### alternatively
we can try convincing the kubelet maintainers to change these defaults on Windows. that is the better solution, but similar requests have failed in the past.

https://github.com/kubernetes/kubernetes/blob/d61cbac69aae97db1839bd2e0e86d68f26b353a7/pkg/kubelet/apis/config/validation/validation_windows.go#L29
https://github.com/kubernetes/kubernetes/blob/d61cbac69aae97db1839bd2e0e86d68f26b353a7/cmd/kubelet/app/options/osflags_windows.go
https://github.com/kubernetes/kubernetes/blob/d61cbac69aae97db1839bd2e0e86d68f26b353a7/pkg/kubelet/apis/config/v1beta1/defaults.go#L148
https://github.com/kubernetes/kubernetes/blob/d61cbac69aae97db1839bd2e0e86d68f26b353a7/pkg/kubelet/apis/config/v1beta1/defaults.go#L245-L246

note, we do not own any tests other than unit tests for this, so best we can do is to just add the change and see if we can remove the flag overrides from https://github.com/kubernetes-sigs/sig-windows-tools/blob/28a4c4f4e9e0b65d4d1ed1841e11eca5a62bfafe/hostprocess/PrepareNode.ps1#L73, which is owned by sig-windows.

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?
/kind feature
(more of a cleanup, but not a bug, as this kubelet behavior is by desing)

#### What this PR does / why we need it:

Some kubelet defaults work on Linux but don't on Windows:
- enforceNodeAllocatable: []string{"pods"}
- cgroupsPerQOS: true

Make sure such fields are always mutated to values that work on Windows:
- enforceNodeAllocatable: []string{}
- cgroupsPerQOS: false

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/2967

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: make sure that on Windows the KubeletConfiguration field "enforceNodeAllocatable" is defaulted to an empty list, while the field "cgroupsPerQOS" is defaulted to "false". This would allow kubeadm Windows worker nodes to not have to explicitly configure the same values for these fields so that the kubelet works on Windows. Currently the Linux defaults for these fields cause the kubelet to exit with an error.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
cc @knabben @jsturtevant
FYI, current the sig-windows tools script passes the options as flags so that the kubelet works on windows:
https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/hostprocess/PrepareNode.ps1#L73

a better option is for the kubelet to override the defaults (ALA no-op them) as mentioned here:
https://github.com/kubernetes/kubeadm/issues/2967
(under "alternatively")

**Comment by knabben** [comment]
Thanks, @neolit123. I think it's a good call to set them as default and avoid the script complexity, LGTM.

**Comment by jsturtevant** [comment]
> > cc @knabben @jsturtevant FYI, current the sig-windows tools script passes the options as flags so that the kubelet works on windows: https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/hostprocess/PrepareNode.ps1#L73
> > a better option is for the kubelet to override the defaults (ALA no-op them) as mentioned here: [kubernetes/kubeadm#2967](https://github.com/kubernetes/kubeadm/issues/2967) (under "alternatively")
> 
> and here is the alternative #123137
> 
> if we merge both, it's still fine.

I lean towards the warning as done in https://github.com/kubernetes/kubernetes/pull/123137.  We have precedence for this in other areas in kubelet.  Changing the values on the user doesn't feel right.  @marosset is working on eviction code (https://github.com/kubernetes/kubernetes/pull/122922) that might eventually be able to support `enforceNodeAllocatable`

**Comment by neolit123** [comment]
> I lean towards the warning as done in https://github.com/kubernetes/kubernetes/pull/123137. We have precedence for this in other areas in kubelet. Changing the values on the user doesn't feel right. @marosset is working on eviction code (https://github.com/kubernetes/kubernetes/pull/122922) that might eventually be able to support enforceNodeAllocatable

+1 let's see if https://github.com/kubernetes/kubernetes/pull/123137 can merge at some point.

**Comment by marosset** [comment]
> > I lean towards the warning as done in #123137. We have precedence for this in other areas in kubelet. Changing the values on the user doesn't feel right. @marosset is working on eviction code (#122922) that might eventually be able to support enforceNodeAllocatable
> 
> +1 let's see if #123137 can merge at some point.

The eviction code I was working on won't initially support `enforceNodeAllocatable` since there are some pretty deep dependencies on cAdivisor for all the node allocatable signals. The work I have out now only enforces available memory resources on Windows

**Comment by neolit123** [comment]
/approve cancel
https://github.com/kubernetes/kubernetes/pull/123136#issuecomment-1928513933

**Comment by pacoxu** [comment]
I prefer to merge https://github.com/kubernetes/kubernetes/pull/123137 only. 
But I am open to this approach, as it only affects windows node. Leave to sig-windows maintainers to decide.

**Comment by neolit123** [comment]
/close
looks like https://github.com/kubernetes/kubernetes/pull/123137 is not getting reviews, so it might miss 1.30.

**Pull request closed without merging**
