### PR TITLE
Only lock statuses map when status isn't successful

### PR DESCRIPTION
**Pull request by soulxu**
Determine the status successful or not first, that will reduce the chance
of lock contention.

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/ok-to-test
/release-note-none
/priority backlog

**Comment by neolit123** [comment]
the change looks valid. LGTM.

**Review by wgliang — APPROVED** [review]
/lgtm

**Pull request merged**
