### PR TITLE
Add misterikkit to sig-scheduling REVIEWERS.

### PR DESCRIPTION
**Pull request by misterikkit**
I have met the following criteria.
- member for at least 3 months
- primary reviewer for at least 5 PRs
  - https://github.com/kubernetes/kubernetes/pull/63603
  - https://github.com/kubernetes/kubernetes/pull/63665 (and related PRs)
  - https://github.com/kubernetes/kubernetes/pull/63839
  - https://github.com/kubernetes/kubernetes/pull/65714
  - https://github.com/kubernetes/kubernetes/pull/66862
- reviewed or merged at least 20 PRs
  reviewed 13: https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+archived%3Afalse+is%3Amerged+repo%3Akubernetes%2Fkubernetes+commenter%3Amisterikkit+in%3Acomment+assignee%3Amisterikkit+
  merged 22: https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Amisterikkit+archived%3Afalse+is%3Amerged+repo%3Akubernetes%2Fkubernetes+

**Release note**:
```release-note
NONE
```
/cc @bsalamat

### CODE REVIEW

**Review by bsalamat — COMMENTED** [review]
LGTM. Let's wait for @k82cn to approve as well.

Please add a release note "NONE" block.

**Comment by k82cn** [comment]
/lgtm 

Totally support that :)

**Pull request merged**
