### PR TITLE
[go1.17] Update to go1.17.2

### PR DESCRIPTION
**Pull request by mengjiao-liu**
#### What type of PR is this?
/kind feature
/area dependency release-eng security

#### Which issue(s) this PR fixes:

Ref https://github.com/kubernetes/release/issues/2254

#### Does this PR introduce a user-facing change?

```release-note
Kubernetes is now built with Golang 1.17.2
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Review by cpanato — APPROVED** [review]
/approve

**Comment by MaciekPytel** [comment]
Shouldn't this change be reflected in go.mod file (which still lists go1.16)?

**Comment by liggitt** [comment]
> Shouldn't this change be reflected in go.mod file (which still lists go1.16)?

no. switching the go.mod file to go1.17 has other implications we don't want (it denormalizes all transitive dependencies into the root go.mod file in ways that disrupt our dependency checking tools)

**Pull request merged**
