### PR TITLE
Automated cherry pick of #75256: Ensure Azure load balancer cleaned up on 404 or 403

### PR DESCRIPTION
**Pull request by feiskyer**
Cherry pick of #75256 on release-1.12.

#75256: Ensure Azure load balancer cleaned up on 404 or 403

### CODE REVIEW

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
SIG Azure approval:
/lgtm
/approve

**Pull request merged**
