### PR TITLE
Automated cherry pick of #109124: Winkernel proxier cache HNS data to improve syncProxyRules

### PR DESCRIPTION
**Pull request by marosset**
Cherry pick of #109124 on release-1.22.

#109124: Winkernel proxier cache HNS data to improve syncProxyRules

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by marosset** [comment]
/test pull-kubernetes-e2e-aks-engine-windows-containerd-1-22

> https://github.com/kubernetes/kubernetes/pull/109985/commits removes the section related to a fix that came in 1.24: [#109981 (comment)](https://github.com/kubernetes/kubernetes/pull/109981#discussion_r870750528)
> 
> @marosset looks like the verify is a valid error on the boilerplate header

updated.
I'm pretty sure it was complaning about golang 1.17+ build directives (//go:build windows)

**Comment by marosset** [comment]
/assign @sbangari @khenidak @feiskyer 
For windows kube-proxy PR review

**Comment by marosset** [comment]
/cc @kubernetes/release-managers 
This is ready for final review

**Comment by puerco** [comment]
Thank you @marosset !!
/lgtm

**Pull request merged**
