### PR TITLE
rebase audit-proxy image to distroless/static

### PR DESCRIPTION
**Pull request by nikopen**
https://github.com/kubernetes/kubernetes/issues/70249

/kind cleanup

### CODE REVIEW

**Review by mkumatag — CHANGES_REQUESTED** [review]
let's bump the version number as well - https://github.com/kubernetes/kubernetes/blob/master/test/images/audit-proxy/VERSION

**Comment by nikopen** [comment]
/milestone v1.14

@mkumatag

**Comment by mkumatag** [comment]
@ixdy can someone help build and pushing this image?

**Pull request merged**
