### PR TITLE
judge the length of the array before for loop

### PR DESCRIPTION
**Pull request by NickrenREN**
we do not need to run the for loop since the length of the array is zero like the function WaitForAttachAndMount() does in the same file.

### CODE REVIEW

**Comment by NickrenREN** [comment]
@saad-ali  @dims   Could you please ask the bot to test ?

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by NickrenREN** [comment]
@saad-ali   checks passed .  please review

**Comment by saad-ali** [comment]
Can you explain why you are making this change?

`range` will skip the loop if the list length is zero anyway. See https://play.golang.org/p/2H8dS07rLZ

**Comment by NickrenREN** [comment]
@saad-ali   I know what you mean. But if the length is zero. we donot need to do the loop.

**Comment by bowei** [comment]
Can you show what the efficiency gain from this change? Ideally, a script snippet that shows the benefit.

**Comment by NickrenREN** [comment]
@bowei   ok, I wrote a test case to get the run time . 
nickren@nickren-ubuntu14:~/test/gotest$ cat rangetest.go 
package main

import (
        "fmt"
        "time"
)

func main() {
        
        arr := []int{}

        t1 := time.Now()
        for i:=0 ; i<100000000 ; i++  {
                for _, v := range arr {
                        fmt.Println("value is : ",v)
                }
        }

        elapsed := time.Since(t1)
        fmt.Println("range elapsed: ", elapsed)

        t2 := time.Now()
        for i:=0 ; i<100000000 ; i++  {
                if len(arr) > 0 {
                        for _, v := range arr {
                                fmt.Println("value is : ",v)
                        }
                }
        }
        elapsed2 := time.Since(t2)
        fmt.Println("judge elapsed: ", elapsed2)


}
nickren@nickren-ubuntu14:~/test/gotest$ go run rangetest.go 
range elapsed:  108.781626ms
judge elapsed:  34.590003ms
nickren@nickren-ubuntu14:~/test/gotest$

**Comment by saad-ali** [comment]
@rsc Any idea why wrapping the range call in a len check makes it run faster in this case? I experimented with @thockin and it looks like replacing the print line with a variable load (`_ = v`) makes the difference in execution time disappear.

```GO
package main

import (
	"fmt"
	"time"
)

func a(arr []int) {
	for i := 0; i < 100000000; i++ {
		for _, v := range arr {
			// _ = v
			_ = fmt.Sprintln(v)
		}
	}

}

func b(arr []int) {
	for i := 0; i < 100000000; i++ {
		if len(arr) > 0 {
			for _, v := range arr {
				// _ = v
				_ = fmt.Sprintln(v)
			}
		}
	}

}

func main() {
	arr := []int{}

	t1 := time.Now()
	a(arr)
	elapsed := time.Since(t1)
	fmt.Println("range elapsed: ", elapsed)

	t2 := time.Now()
	b(arr)
	elapsed2 := time.Since(t2)
	fmt.Println("judge elapsed: ", elapsed2)
}

```

@NickrenREN What led you to suggest the change? Did you do a profile where this stood out? These loops are not particularly latency sensitive, so I'd prefer cleaner code over micro optimizations.

**Comment by rsc** [comment]
You're short-circuiting the loop setup code. Same question @saad-ali had: did this come up in a real profile? That would mean the program spends a significant amount of time ranging over empty slices, which is kind of odd.

Here's a file x_test.go:

```
package x

import (
	"fmt"
	"testing"
)

func BenchmarkRange(b *testing.B) {
	benchmarkRange(b, nil)
}

func benchmarkRange(b *testing.B, arr []int) {
	for i := 0; i < b.N; i++ {
		for _, v := range arr {
			// _ = v
			_ = fmt.Sprintln(v)
		}
	}
}

func BenchmarkIfRange(b *testing.B) {
	benchmarkIfRange(b, nil)
}

func benchmarkIfRange(b *testing.B, arr []int) {
	for i := 0; i < b.N; i++ {
		if len(arr) > 0 {
			for _, v := range arr {
				// _ = v
				_ = fmt.Sprintln(v)
			}
		}
	}
}
```

And then:

```
$ go test -bench . x_test.go -benchtime=5s
BenchmarkRange-8     	10000000000	         0.77 ns/op
BenchmarkIfRange-8   	10000000000	         0.52 ns/op
PASS
ok  	command-line-arguments	13.003s
$ 
```

Comparing the assembly, it's about what you'd expect: the IfRange version has an if statement ahead of the loop setup.

Plain range:

	0x003d 00061 (p_test.go:13)	MOVQ	$0, DX
	0x003f 00063 (p_test.go:14)	MOVQ	"".arr+112(FP), BX
	0x0044 00068 (p_test.go:14)	MOVQ	DX, ""..autotmp_11+56(SP)
	0x0049 00073 (p_test.go:14)	MOVQ	BX, ""..autotmp_12+64(SP)
	0x004e 00078 (p_test.go:14)	MOVQ	"".arr+120(FP), SI
	0x0053 00083 (p_test.go:14)	CMPQ	DX, SI
	0x0056 00086 (p_test.go:14)	JGE	$0, 229

If + range:

	0x003d 00061 (p_test.go:27)	MOVQ	"".arr+120(FP), DX
	0x0042 00066 (p_test.go:27)	TESTQ	DX, DX
	0x0045 00069 (p_test.go:27)	JLE	257
	0x004b 00075 (p_test.go:26)	MOVQ	$0, BX
	0x004d 00077 (p_test.go:28)	MOVQ	"".arr+112(FP), SI
	0x0052 00082 (p_test.go:28)	MOVQ	BX, ""..autotmp_25+48(SP)
	0x0057 00087 (p_test.go:28)	MOVQ	SI, ""..autotmp_26+64(SP)
	0x005c 00092 (p_test.go:28)	CMPQ	BX, DX
	0x005f 00095 (p_test.go:28)	JGE	$0, 257

The if+range has the extra three instructions you'd expect, and those bypass the loop setup for an empty slice. Of course, if the slice is non-empty then those are a waste of time.

We could plausibly compile the plain range a little differently, to try to get something like:

	(p_test.go:14)	MOVQ	"".arr+120(FP), SI
	(p_test.go:14)	TESTQ	SI, SI
	(p_test.go:14)	JLE	229
	(p_test.go:14)	MOVQ	$0, DX
	(p_test.go:14)	MOVQ	"".arr+112(FP), BX
	(p_test.go:14)	MOVQ	DX, ""..autotmp_11+56(SP)
	(p_test.go:14)	MOVQ	BX, ""..autotmp_12+64(SP)

The loop body jumps back to the next instruction after this header, so adjusting the order here won't affect the next iteration. The rewritten sequence is the same length as the original but does the zero-length test first and then omits the general length check at the end (the loop doesn't jump back here for the next iteration, so it's redundant with the hoisted check).

If this comes up in an important context then it may be worth doing, in which case we can copy this info to a new golang/go issue. Otherwise, maybe not. Hard to say without more context.

Thanks.

/cc @randall77 @dr2chase

**Comment by bowei** [comment]
@NickrenREN I mean performance test in the context of the code above, e.g. is this a real issue in the storage plugin... sorry wasn't sufficiently explicit earlier.

**Comment by saad-ali** [comment]
@rsc thanks for digging in! The optimization you proposed would be a nice to have, but is not critical/important for us. AFAIK this is a micro-optimization that will result in little or no real world improvement.

For the sake of cleaner code over micro optimizations, I propose closing this PR. Please re-open if you disagree.

**Pull request closed without merging**
