### PR TITLE
Rename "release_1_5" clientset to just "clientset"

### PR DESCRIPTION
**Pull request by caesarxuchao**
We used to keep multiple releases in the main repo. Now that [client-go](https://github.com/kubernetes/client-go) does the versioning, there is no need to keep releases in the main repo. This PR renames the "release_1_5" clientset to just "clientset", clientset development will be done in this directory.

@kubernetes/sig-api-machinery @deads2k 

```release-note
The main repository does not keep multiple releases of clientsets anymore. Please find previous releases at https://github.com/kubernetes/client-go
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Most changes are mechanical. I think only the commit "docs/devel/generating-clientset.md" is worth reviewing.

**Comment by caesarxuchao** [comment]
@k8s-bot unit test this

**Comment by wojtek-t** [comment]
Thanks @caesarxuchao - LGTM.

**Comment by caesarxuchao** [comment]
The generating-clientset.md is copied to the community repo [here](https://github.com/kubernetes/community/blob/master/contributors/devel/generating-clientset.md), but because the original doc still exists in the main repo, and verify-munge-doc.sh will fail if I don't update the original doc in this PR.

**Comment by wojtek-t** [comment]
@caesarxuchao - feel free to self-apply lgtm label after rebase and probably ask oncall to merge this manually asap to avoid additional rebases

**Comment by wojtek-t** [comment]
@caesarxuchao - what's the state of this PR? I think we would like to merge this...

**Comment by caesarxuchao** [comment]
Rebased.

**Comment by caesarxuchao** [comment]
@deads2k FYI, this PR also renamed `cmd/kubernetes-discovery/pkg/client/clientset_generated/release-1_5` to `cmd/kubernetes-discovery/pkg/client/clientset_generated/clientset`

**Comment by caesarxuchao** [comment]
I'm adding the P2 label because the rebasing is difficult. I paid the price once, I had to recreated all the commits.

**Comment by deads2k** [comment]
> @deads2k FYI, this PR also renamed cmd/kubernetes-discovery/pkg/client/clientset_generated/release-1_5 to cmd/kubernetes-discovery/pkg/client/clientset_generated/clientset

That's fine.  Thanks.

**Comment by caesarxuchao** [comment]
Self applying the lgtm. The only change after I got the lgtm last time is renaming `cmd/kubernetes-discovery/pkg/client/clientset_generated/release-1_5` to clientset, which got approved by @deads2k.

**Pull request merged**
