### PR TITLE
Make TOC munge include blank line before TOC

### PR DESCRIPTION
**Pull request by thockin**
@lavalamp @erictune

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM

**Comment by ArtfulCoder** [comment]
Kicked shippable.

**Comment by bgrant0607** [comment]
Failed run-gendocs.sh. Recommend rebase and re-munge.

**Comment by thockin** [comment]
rebased

**Comment by davidopp** [comment]
@bgrant0607 says you need to rebase and re-run

**Comment by bgrant0607** [comment]
Because we just added another doc

**Comment by davidopp** [comment]
I won't merge anything else until this one goes in.

**Comment by bgrant0607** [comment]
Travis passed already. It runs hack/run-gendocs.sh, so this can go in.

**Comment by davidopp** [comment]
ok if you say so :) merging now.

**Pull request merged**
