### PR TITLE
Set namespace when using kubectl create service

### LINKED ISSUE #100995: Namespace is not set when using kubectl to generate service
#### What happened:

I'm writing a small bash script which generates some k8s resources in a namespace (other than `default`).
When using `kubectl create service clusterip my-service --namespace=xyz` to generate a service, the yaml which is generated does not include the defined namespace. I've also tried to move around the `--namespace` argument to the beginning (i.e. `kubectl --namespace=xyz create service`, but that doesn't work as well.

#### What you expected to happen:

Generated yaml should include the `namespace`, when it's defined as an option.

#### How to reproduce it (as minimally and precisely as possible):

```
$ MY_NS="some-existing-namespace"
$ kubectl create service clusterip test-lab-cassandra-rack-1 --tcp=9042:9042 --namespace=$MY_NS -o yaml --dry-run=client | 
 kubectl set selector --local -f - 'cassandra.datastax.com/rack=rack1' -o yaml

-- Command output is:

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-lab-cassandra-rack-1
  name: test-lab-cassandra-rack-1
  namespace: some-existing-namespace      <----- this part is missing in the actual yaml output  -------
spec:
  ports:
  - name: 9042-9042
    port: 9042
    protocol: TCP
    targetPort: 9042
  selector:
    cassandra.datastax.com/rack: rack1
  type: ClusterIP
status:
  loadBalancer: {}
```

#### Environment:
- Kubernetes version (use `kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Cloud provider or hardware configuration: n/a (not really important)
- OS (e.g: `cat /etc/os-release`): `Ubuntu 20.10`
- Kernel (e.g. `uname -a`): `Linux steve 5.8.0-48-generic #54-Ubuntu SMP Fri Mar 19 14:25:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubectl
- Network plugin and version (if this is a network-related bug): n/a
- Others:

/sig cli

### PR DESCRIPTION
**Pull request by zxh326**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
- Set namespace when create service
- Add `EnforceNamespace` for ServiceOptions

#### Which issue(s) this PR fixes:

Fixes #100995

#### Does this PR introduce a user-facing change?

```release-note
kubectl create service now respects namespace flag
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by rikatz — APPROVED** [review]
/lgtm

Thank you!!

**Review by eddiezane — CHANGES_REQUESTED** [review]
Let's add a test for this please to catch regression.

**Review by rikatz — APPROVED** [review]
/lgtm

Now with tests :)

Thanks!!

**Comment by eddiezane** [comment]
Thanks!

/approve

**Review by eddiezane — APPROVED** [review]

**Comment by zxh326** [comment]
> @zxh326 can you please add a release note for this?
> 
> Something like `kubectl create service now respects namespace flag`.

Added

**Comment by eddiezane** [comment]
I'm going to cherry pick this to 1.21 since 1.22 won't be out until August.

**Pull request merged**
