### PR TITLE
Update etcd to version 2.0.0

### LINKED ISSUE #3892: Switch kubernetes default etcd implementation to etcd 2.0
@brendandburns writes: As we start looking into etcd and event memory pressure [#3853], we should look into switching over to etcd 2.0 which was released today.

### PR DESCRIPTION
**Pull request by brendandburns**
Closes #3892

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
Do we need to update test-cmd to now prereq this version?

**Comment by thockin** [comment]
and integration and local ?

**Comment by brendandburns** [comment]
Integration just depends on there being etcd somewhere in the path.  API is
consistent in both places, so I don't think it matters.

Looking @ etcd.sh for local/test-cmd.sh, I _think_ it should work in both
cases, though I should probably download an OS X etcd and verify.

**Comment by derekwaynecarr** [comment]
I was running etcd 0.5 alpha and it was failing,  so I think a version check is actually a good thing to do.

**Comment by brendandburns** [comment]
Added a version check to ```test-cmd.sh``` and integration tests.  Also added to the travis setup.

**Comment by satnam6502** [comment]
@derekwaynecarr or @thockin : can I assigned this to either of you?
If you both NACK then I will take it.

**Comment by satnam6502** [comment]
Talked to Brendan. It's green: let's merge.

**Comment by derekwaynecarr** [comment]
Working on a PR to fix vagrant now

**Comment by satnam6502** [comment]
@derekwaynecarr : ah, sorry, I should have waited for you.

**Comment by saad-ali** [comment]
I updated my local version of etcd to 2.0.
```
[00:55:26] master ~/go/src/github.com/saad-ali/kubernetes $ etcd -version
etcd version 2.0.0-rc.1
[00:57:23] master ~/go/src/github.com/saad-ali/kubernetes $ /usr/local/bin/etcd -version
etcd version 2.0.0-rc.1
```
But ```hack/e2e-test.sh``` fails with ```etcd version 2.0.0 or greater required.```
I modified the ```etcd.sh``` script slightly to see what version it thinks I have, and it returns:
```
etcd version 2.0.0 or greater required. your version is 0.4.6
```
I have no idea where it's picking up ```0.4.6``` from.
Any ideas what I'm missing?

**Comment by sdminonne** [comment]
To fix (maybe partially) I've just submitted this https://github.com/GoogleCloudPlatform/kubernetes/pull/3975

**Comment by saad-ali** [comment]
Thanks @sdminonne, that unblocks the tests!

**Pull request merged**
