### PR TITLE
Allow no ports when exposing headless service

### LINKED ISSUE #32795: kubectl expose --cluster-ip=None demands a port, not needed
API validation explicitly allows headless services to not have ports, but we seem to have not updated kubectl to know this:

https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go#L2390

### PR DESCRIPTION
**Pull request by fraenkel**
fixes #32795

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32811)

### CODE REVIEW

**Comment by spxtr** [comment]
ok to test

**Comment by jlowdermilk** [comment]
lgtm, thanks

**Comment by wojtek-t** [comment]
@k8s-bot unit test this, issue: #32685

**Comment by jlowdermilk** [comment]
@k8s-bot cvm gce e2e test this

**Comment by rmmh** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
