### PR TITLE
Use temporary directory when creating temporary file in tests

### PR DESCRIPTION
**Pull request by soltysh**
**What type of PR is this?**
/kind cleanup

/sig cli
/priority backlog

**What this PR does / why we need it**:
[ioutil.TempFile](https://golang.org/pkg/io/ioutil/#TempFile) creates a temporary file in the directory specified as the first argument. It sometimes is `/tmp` but sometimes not. It's better to be explicit about this being `/tmp`. 

**Special notes for your reviewer**:
/assign @damemi 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by damemi — APPROVED** [review]
/lgtm

**Comment by brianpursley** [comment]
I think the change is fine, but I don't see how this will be different than what it does currently.

From https://golang.org/pkg/io/ioutil/#TempFile ...
> If dir is the empty string, TempFile uses the default directory for temporary files (see os.TempDir)

**Comment by soltysh** [comment]
> I think the change is fine, but I don't see how this will be different than what it does currently.

We want to ensure the tests are running in a contained environment, here `/tmp` directory. Without it, according to golang description `ioutil.TempFile` creates the temporary file in the directory specified as the first argument, which being `""` is usually current.

**Review by brianpursley — APPROVED** [review]

**Pull request merged**
