### PR TITLE
all: fix typos

### PR DESCRIPTION
**Pull request by callthingsoff**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Fix typos.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by pacoxu — APPROVED** [review]

**Review by neolit123 — APPROVED** [review]

**Comment by alexzielenski** [comment]
/sig api-machinery
/triage accepted
/cc @jiahuif 

could you take a look at the api-machinery typo changes

**Review by jiahuif — APPROVED** [review]
/lgtm

**Comment by gocurr** [comment]
Any comments? If this PR is worthless, it will be closed.

**Comment by pacoxu** [comment]
It's the code freeze period for the v1.28 release on August 15th. PRs that were already approved, will be merged after the release.

Each incoming Pull Request needs to be reviewed, checked and then merged. As the current PR involves multi packages and needs approval by multi owners.

/priority backlog

This PR fixes some typos and is valid. However, the priority is not that high. Let's wait for other reviewers/approvers' input.

**Comment by gocurr** [comment]
Sorry, not working on this.

**Pull request closed without merging**
