### PR TITLE
Update cni in vendor and refactor cniNetworkPlugin for hypervisor runtime

### PR DESCRIPTION
**Pull request by heartlock**
refactor cniNetworkPlugin for reusing it in all kinds of runtime. 
Ref: containernetworking/cni#145 , https://github.com/kubernetes/kubernetes/issues/41552

### CODE REVIEW

**Comment by resouer** [comment]
@k8s-bot ok to test

**Comment by feiskyer** [comment]
We needs to wait next cni release v0.5.0 and vendor to the stable tag.

**Comment by heartlock** [comment]
thanks for your reply @feiskyer I will update it when cni 0.5.0 release.

**Comment by squeed** [comment]
There is an additional new feature coming out in CNI v0.5.0: plugin chaining, or ConfigLists. However, the runtimes need to be updated to use them.
I've submitted a PR to make them available: #42202. These are currently conflicting PRs, but can be easily rebased when one of them is merged to master.

**Comment by heartlock** [comment]
@squeed  Agree! easy to rebase.

**Comment by feiskyer** [comment]
This PR is not required now. CNI has already been updated to latest version at #42202.

**Comment by feiskyer** [comment]
/close

Try again.

**Pull request closed without merging**
