### PR TITLE
Validation cleanup part 2

### PR DESCRIPTION
**Pull request by thockin**
Part 2 of several, builds on #17245

@lavalamp

### CODE REVIEW

**Comment by thockin** [comment]
@k8s-bot unit test this please

@k8s-bot test this please

**Comment by thockin** [comment]
@k8s-bot unit test this please

@k8s-bot test this please

**Comment by lavalamp** [comment]
LGTM, one comment

**Comment by thockin** [comment]
I added lgtm, but took it off.  we want pt1 to go in first.

**Comment by lavalamp** [comment]
yeah that's why I didn't put it on.

**Comment by thockin** [comment]
@k8s-bot test this please

**Pull request merged**
