### PR TITLE
fix grammar error: the predicate verb should be the third person.

### PR DESCRIPTION
**Pull request by liangwenguo**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by liangwenguo** [comment]
@jamiehannaford @mattmoyer PTAL, think you

**Review by jamiehannaford — APPROVED** [review]
/lgtm

**Comment by liangwenguo** [comment]
@jamiehannaford my PR can not pass the test, i htink it's not my fault.

**Comment by liangwenguo** [comment]
@jamiehannaford can you give me an "approved", the robot can not merge this PR.

**Comment by liangwenguo** [comment]
i recommit a new one

**Pull request closed without merging**
