### PR TITLE
Update Godeps to support godep v54+

### PR DESCRIPTION
**Pull request by eparis**
- github.com/onsi/ginkgo/ginkgo was included by godep by chance, not because we explicitly imported it. But we did explicity build it. Create a 'dead code' import do godep picks it up.
- Clean up Godeps since v54+ does a better job pruning dead code.

### CODE REVIEW

**Comment by eparis** [comment]
@lavalamp I just assigned you here. This is not 1.2 priority in my mind if we land the other fix.

https://github.com/eparis/kubernetes/commit/0a55b4807c12c9fdefe18e29aba176aadc12d9a4

Is the commit that is dirty...  We explicitly build github.com/onsi/ginkgo/ginkgo in hack/build-go.sh but it was never explicitly imported...  We only get it by chance...

**Comment by eparis** [comment]
And that doesn't work because we run `godep go install ./...` and that import isn't valid. BLAST!  I have no idea how to completely embed github.com/onsi/ginkgo/ginkgo (`package main`)...

**Comment by lavalamp** [comment]
Is that a command or a library? godep doesn't like including commands...

**Comment by eparis** [comment]
it's a command   :-(    and I know it doesn't like it!

**Comment by eparis** [comment]
https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh#L88
Is where we try to build a command which isn't ours.

**Comment by eparis** [comment]
@lavalamp and guesses how to make my hackery not blow up
https://github.com/eparis/kubernetes/commit/03db4c7d1716201603c7b7726eb02c4ad3cb2b6f#diff-3bd33d591aa8f346345fe7573d5d1a0cR27
```
E0223 16:58:34.853204    4042 main.go:86] Error: Failed making a context: k8s.io/kubernetes/cmd/fake-imports/main.go:26:2: main redeclared in this block
```

Just give up? We can't ever move forward on Godep? Do something terrible to generate and remove those deps only when generating Godeps/? I hate godeps....

**Comment by lavalamp** [comment]
What if you don't declare main in fake-imports/main.go?

But yes, we'd love to stop using godep. Maybe when we switch to go1.6?

**Comment by freeformz** [comment]
Wrt ginkgo, see also tools/godep#419

**Comment by freeformz** [comment]
PS: I would also target v55.

**Comment by eparis** [comment]
That's the point of this, so we can start tracking head again....

**Comment by freeformz** [comment]
FWIW: The `Godeps/LICENSES` files may not be necessary anymore. Modern godep versions will copy the LICENSE files of dependencies. If there is a case where it doesn't, then it's a bug and should be fixed.

**Comment by eparis** [comment]
Godep/LICENSES is something we compute by hand from all of those that you copy in.

**Comment by freeformz** [comment]
@eparis it's fine as a reference if kubernetes feels that it needs it. My point was just that godep is preserving licesnes when vendoring, which is good enough for most people (AFAIK).

**Comment by freeformz** [comment]
@lavalamp godep likes including commands just fine, we use it internally with an old school workspace, but things are not as happy with vendor because vendor doesn't work like a gopath element. See tools/godep#419 for a more exhaustive commentary.

**Comment by freeformz** [comment]
The additional lines in Godeps.json are a more precise listing of dependencies for the listed Packages. Previously these dependencies were pulled along by the fact that they were sub packages of a higher level dependency. But as go1.6 started being used with `vendor/` people started reporting issues where they would save their deps and then run `go install ./...` and go would complain when trying to compile extra stuff in vendor. It turns out that godep's initial design would include any sub directories, including sub packages, of a required package and it would squash recording sub packages of a previously required package. This is fixed in v54+ so that everything works better with go1.6 and the vendor experiment. Think of it as "precise" dependency recording.

So previously `github.com/onsi/ginkgo/ginkgo` was pulled in by this older behavior (it's a sub dir) because `github.com/onsi/ginkgo` is a dependency in your tests.

**Comment by lavalamp** [comment]
@eparis If you split the two fake imports into two directories instead of having them in the same directory, would it work? People complain every time we take out the "go build ./..." line.

@freeformz thanks for commentary

**Comment by freeformz** [comment]
@lavalamp let me know how I can help with any godep issues.

**Comment by lavalamp** [comment]
@freeformz thanks, will keep that in mind.

**Comment by lavalamp** [comment]
Version pinning at v53 is probably going to be OK until 1.2 is released, so this isn't urgent.

**Comment by lavalamp** [comment]
@thockin Do we want to roll forward to godeps v54 or did you get an alternate method working?

**Comment by eparis** [comment]
no matter an alternative this is a good idea...

**Comment by eparis** [comment]
actually closing this PR, I've got a better one.

**Comment by eparis** [comment]
https://github.com/kubernetes/kubernetes/pull/22807 is the better version.

**Pull request closed without merging**
