### PR TITLE
add anti affinity pods for density e2e test

### PR DESCRIPTION
**Pull request by shiyan2016**
**What type of PR is this?**
>
> /kind api-change
> /kind design
> /kind feature
> /sig scheduling

**What this PR does / why we need it**:
Current e2e density test only runs some regular pod. It does not contain affinity pod. Which cannot measue the throughput of kube-scheduler for affinity pods. And affinity pod is a common strategy for production.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by wojtek-t** [comment]
These tests are no longer use by any periodic/presubmit etc. tests. We hope to remove them soon (hopefully in 1.16) when we migrate some optional tests to ClusterLoader, so let's not add more functionality to it now.
I opened https://github.com/kubernetes/kubernetes/pull/79588 to make that clear (sorry, should have done that long time ago). So I'm closing this - if you want, we may consider extending the ClusterLoader tests with affinity feature.

**Comment by shiyan2016** [comment]
@wojtek-t ok, I think affinity feature widely used in practice, so it is better for ClusterLoader tests involve affinity feature.

**Pull request closed without merging**
