### PR TITLE
federation: Adding a tool to generate docs for federation apiserver and controller manager

### PR DESCRIPTION
**Pull request by nikhiljindal**
cc @kubernetes/sig-cluster-federation

### CODE REVIEW

**Comment by nikhiljindal** [comment]
@kubernetes/docs-review-team Is the do-not-merge label correct?
I assume that the latest autogenerated copy still remains in this repo and then we pull it periodically in kubernetes.github.io.

**Comment by eparis** [comment]
the bot is correct

**Comment by janetkuo** [comment]
@eparis since the docs are auto-generated, should the bot allow this PR to be merged but keep the kind/old-docs label like how it treats `kubectl` PRs which also contain auto-generated docs?

**Comment by nikhiljindal** [comment]
@k8s-bot e2e test this issue: https://github.com/kubernetes/kubernetes/issues/26138

**Comment by nikhiljindal** [comment]
@k8s-bot node e2e test this issue: https://github.com/kubernetes/kubernetes/issues/26203

**Comment by nikhiljindal** [comment]
Discussed this with @bgrant0607 and he agreed that it is fine to add autogenerated docs to this repo. We will need to manually merge the PR.
We want to move autogenerated docs to the new docs repo but havent done that yet.

As @janetkuo said, it will be good to make the bot smarter to recognize these auto generated docs and handle them as a special case.

**Comment by eparis** [comment]
sorry, I completely missed they are auto-generated.  We need to update https://github.com/kubernetes/contrib/blob/master/mungegithub/block-path.yaml

**Comment by nikhiljindal** [comment]
@eparis Thanks for fixing the bot!
Can I have LGTM? :)

**Comment by nikhiljindal** [comment]
@eparis Do we need to do something for https://github.com/kubernetes/contrib/pull/1072 to take effect?
merge bot is still adding do-not-merge label.

**Comment by eparis** [comment]
LGTM. blocked until submit-queue is restarted, and i'm not going to restart it since it is making progress.

**Comment by lavalamp** [comment]
@eparis @nikhiljindal this broke the build... fixed in #26400

**Pull request merged**
