### PR TITLE
Replace hard-code "cpu" and "memory" to consts

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
There are many places using hard coded "cpu" and "memory" as resource name. This PR replace them to consts.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
/kind cleanup

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
/release-note-none
These two comments are testing. (This PR is valid)

**Comment by xiangpengzhao** [comment]
Thanks, @alexandercampbell !

/assign @erictune @wojtek-t
for approval, thanks!

**Comment by alexandercampbell** [comment]
@xiangpengzhao thank you for cleaning this up!

**Pull request merged**
