### PR TITLE
Update aws sdk for volume expand

### PR DESCRIPTION
**Pull request by gnufied**
Update AWS sdk in preparation for supporting volume expansion. The vendored aws-sdk does not support ModifyVolume with size.

### CODE REVIEW

**Comment by gnufied** [comment]
Flaked on https://github.com/kubernetes/kubernetes/issues/48368

/test pull-kubernetes-unit

**Comment by gnufied** [comment]
cc @justinsb

**Comment by childsb** [comment]
@justinsb / @zmerlynn can we update the aws sdk for 1.8? the update is required to for ebs resize function.

https://github.com/kubernetes/features/issues/284

**Comment by justinsb** [comment]
Sorry for delay.  Yes we can update, though might be better to wait for 1.9 now unless there's a PR reliant on this.  This PR looks good, but I guess we had a concurrent update hence the conflict?  I think this was the original reason why we didn't merge this PR, if not I apologize @gnufied

**Comment by childsb** [comment]
Closing in favor of: https://github.com/kubernetes/kubernetes/pull/53561

**Pull request closed without merging**
