### PR TITLE
[release-1.26] releng/go: Update images, dependencies and version to Go 1.19.8

### PR DESCRIPTION
**Pull request by xmudrii**
#### What type of PR is this?

/kind feature
/area dependency
#### What this PR does / why we need it:

* Update images, dependencies and version to Go 1.19.8

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/release/issues/2991

#### Does this PR introduce a user-facing change?
```release-note
Kubernetes is now built with Go 1.19.8
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

/assign @saschagrunert @cpanato @cici37 @puerco 
cc @kubernetes/release-engineering

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
waiting the other CP to be approved

**Pull request merged**
