### PR TITLE
OWNERS_ALIASES: add tzneal to sig-node-reviewer

### PR DESCRIPTION
**Pull request by tzneal**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

I have been part of SIG-Node since the beginning of the year and have been an org member since April. I have participated in SIG-Node meetings regularly, particularly in SIG-Node CI where I try to devote regular time to deflaking tests and making E2E tests more robust/less platform specific. I've been involved in the implementation of the Sidecar KEP, particularly with respect to refactoring resource calculations across the repo to be correct in the presence of the sidecar/vertical pod scaling flags and implementing E2E tests for sidecars.

[SIG-Node Reviewer Requirements](https://github.com/kubernetes/community/blob/master/sig-node/sig-node-contributor-ladder.md#reviewer) 

[20 Merged PRs](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+is%3Amerged+author%3Atzneal+) 
[28 Reviewed PRs](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+reviewed-by%3Atzneal) 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by matthyx** [comment]
Yes +1

**Comment by pacoxu** [comment]
+1
Todd has worked on several flake and CI failure issues.

/sig node
SIG Node needs more active maintainers including reviewers.

**Comment by bart0sh** [comment]
/triage accepted
/priority important-soon
/lgtm
+1

**Comment by pacoxu** [comment]
As the process, you have to get at least one approver's sponsor and no objections from other approvers.

https://github.com/kubernetes/community/blob/88b05569ed6a530f6982c07aa7eedcdd5ce2a6f3/sig-node/sig-node-contributor-ladder.md?plain=1#L43-L44

    - @Random-Liu
    - @dchen1107
    - @derekwaynecarr
    - @yujuhong
    - @sjenning
    - @mrunalp
    - @klueska

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Pull request merged**
