### PR TITLE
Enable strict client-go verification in CI

### PR DESCRIPTION
**Pull request by sttts**
**Follow-up of https://github.com/kubernetes/kubernetes/pull/41987. Only the two last commits are relevant here.**

This turns on strict client-go verification, i.e. PRs with missing client-go updates will fail in CI.

It also updates the client-go once to have a baseline.

**This should be enabled just after the freeze in order to enforce consistency of client-go.**

### CODE REVIEW

**Comment by caesarxuchao** [comment]
This should work :+1:

**Comment by sttts** [comment]
@k8s-bot unit test this

**Comment by sttts** [comment]
@k8s-bot unit test this

**Comment by sttts** [comment]
@k8s-bot non-cri e2e test this

**Comment by eparis** [comment]
@k8s-bot cvm gke e2e test this

**Comment by deads2k** [comment]
@k8s-bot non-cri e2e test this

**Pull request merged**
