### PR TITLE
Remove log line from expiration cache

### PR DESCRIPTION
**Pull request by nckturner**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by logicalhan — COMMENTED** [review]
What is the point of this? Is this noisy or something?

**Review by dims — APPROVED** [review]
/approve

**Pull request merged**
