### PR TITLE
Make default conversion behavior available to conversion funcs

### PR DESCRIPTION
**Pull request by liggitt**
When setting up conversion functions for some objects, I found that the default conversion behavior was _almost_ exactly what I wanted, with just a couple tweaks. It would be handy to be able to use the default functions as one step of a custom function to avoid lots of boilerplate copying fields with the same name, etc.

@lavalamp PTAL

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM but want Dan's sign off

**Comment by lavalamp** [comment]
This is wonderful! What do you think about making it a flag, though, instead of making a separate function?

**Comment by liggitt** [comment]
That was my first thought, though I wouldn't want the flag to prevent custom functions from getting called on nested objects. Unsetting the flag in convert felt a little gorpy, but I can try it and see what you think

**Comment by lavalamp** [comment]
Alternatively, keep the form you have, but make the "DefaultConvert" function skip the user functions at one level of recursion instead of all levels of recursion.

I could also imagine adding another set of functions that get called in the same place but with "defer" so that they get called after the default copy behavior has taken place.

Really this is better than how I was working on fixing it, because this is simpler.

**Comment by liggitt** [comment]
DefaultConvert only skips user functions at one level

**Comment by lavalamp** [comment]
Ah, you're right, I got confused.

LGTM

**Pull request merged**
