### PR TITLE
fix missing verb at end of format string

### PR DESCRIPTION
**Pull request by huangjiuyuan**
**What this PR does / why we need it**:
A missing verb at end of format string in Errorf call happens in `vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc_test.go`, This PR fixes this problem.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

`NONE`

### CODE REVIEW

**Comment by huangjiuyuan** [comment]
Hi, @ericchiang 
Could you please take a quick look at this?

**Comment by ericchiang** [comment]
Woops

/ok-to-test

**Comment by huangjiuyuan** [comment]
Hi, @ericchiang 
The pull-kubernetes-bazel test always failed so I rebased this commit. Could you please approve one more time? Thank you!

**Pull request merged**
