### PR TITLE
Move util.UID to pkg/types

### PR DESCRIPTION
**Pull request by thockin**

### CODE REVIEW

**Comment by lavalamp** [comment]
Travis is mad, and it's not a flake, looks like.

**Comment by lavalamp** [comment]
Not due to your code, though. Hopefully I've fixed the build now.

**Comment by thockin** [comment]
green now

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
What else should go in types? StringSet? IntString?

**Comment by thockin** [comment]
I don't want pkg/types to become another dumping ground, but those sound
reasonable to me.  The flag wrappers are on the edge of appropriate, IMO

**Pull request merged**
