### PR TITLE
cleanup some logic of sts controller

### PR DESCRIPTION
**Pull request by lucming**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by soltysh** [comment]
@lucming please rebase and ping me on slack for a review

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by lucming** [comment]
> If you still need this PR then please rebase, if not, please close the PR

done

**Pull request closed without merging**
