### PR TITLE
Fix Kube DNS addon staging for Container VMs

### PR DESCRIPTION
**Pull request by girishkalele**

### CODE REVIEW

**Comment by girishkalele** [comment]
Fixes DNS on CVM broken #26850

**Comment by mikedanese** [comment]
Why is kube-dns in cluster/saltbase/salt/kube-dns/ and all the others in cluster/addons/? We should move those too where the other addons are maintained.

**Comment by girishkalele** [comment]
Thanks mikedanese

Prashanth actually suggested to move them out of addons since DNS is now thought of as a core component and not optional (although I think the addon manager does start the DNS pod).

**Comment by girishkalele** [comment]
Transferred P1 label and 1.3 milestone labels from issue #26850

**Comment by girishkalele** [comment]
@k8s-merge-robot Recheck

**Comment by mikedanese** [comment]
@girishkalele I am planning on managing kube-proxy through the addon manager in the near term (running in a daemonset) and hopefully kube-controller-manager and kube-scheduler (running in deployments). Addon might be a bad word for this but we have used it to mean applications that run on the cluster and are managed through the addon manager. As long as you are throwing a manifest in /etc/kubernetes/addons/ it's an addon according to that definition. Now it just lives in a different place in the codebase.

cc @bprashanth

**Comment by mikedanese** [comment]
This isn't tested by e2e since we don't test containervm master for some reason, or this would have been caught

**Pull request merged**
