### PR TITLE
Revert "Remove seemingly obsolete binaries"

### PR DESCRIPTION
**Pull request by dims**
Reverts kubernetes/kubernetes#46902 as the docs builds are failing now because they rely on mungedocs.

mungedocs is used in https://github.com/kubernetes/kubernetes.github.io/blob/master/.travis.yml#L23

### CODE REVIEW

**Comment by dims** [comment]
@thockin @ixdy @cblecker we broke docs builds (see comment in https://github.com/kubernetes/kubernetes/pull/46902#issuecomment-324443735)

**Comment by thockin** [comment]
What if we homed this in the docs repo?

**Comment by thockin** [comment]
I posted https://github.com/kubernetes/kubernetes.github.io/pull/5178 as an alternative.  PTAL

**Comment by cblecker** [comment]
I tried that same thing heh.. yeah, I think that works as a solution IMO. Why host code in k/k unless it needs to be here.

**Pull request closed without merging**
