### PR TITLE
DO NOT MERGE - WIP: Add debugging logs

### PR DESCRIPTION
**Pull request by bobbypage**
Signed-off-by: David Porter <david@porter.me>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
/test pull-kubernetes-node-e2e-containerd

@ruiwen-zhao can you try your old PR - will you be able to get a repro without logging?

**Comment by ruiwen-zhao** [comment]
> /test pull-kubernetes-node-e2e-containerd
> 
> @ruiwen-zhao can you try your old PR - will you be able to get a repro without logging?

Been trying it today. No luck yet. https://github.com/kubernetes/kubernetes/pull/109371

**Pull request closed without merging**
