### PR TITLE
CHANGELOG: remove release-note-none items

### PR DESCRIPTION
**Pull request by changshuchao**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by soniasingla — COMMENTED** [review]
@changshuchao thanks for the PR! 🙌

@wilsonehusin don't we need to change the message here instead of removing the line? :)

**Comment by wilsonehusin** [comment]
This line should not show up (krel bug, only on alpha.1 and not the following tags), but this is a pre-release note and I would rather have a cleanup on release instead of fixing these bits, because we have bigger things to worry at the moment.

**Comment by changshuchao** [comment]
@wilsonehusin  @soniasingla  Do we need this pr ?

**Comment by wilsonehusin** [comment]
let's close it. in general, pre-release content aren't really as important until release time comes.

/close

**Pull request closed without merging**
