### PR TITLE
Del repeat imported package

### PR DESCRIPTION
**Pull request by zhengguoyong**

### CODE REVIEW

**Comment by zhengguoyong** [comment]
@k8s-bot  test this please

**Comment by ashcrow** [comment]
Pretty sure this is a flake based on the code changed in this PR.

```
[Fail] Pods [It] should have their auto-restart back-off timer reset on image update 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:193

[Fail] EmptyDir volumes [It] should support (non-root,0777,default) [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/util.go:1144

[Fail] Pod Disks [It] should schedule a pod w/ a RW PD shared between multiple containers, write to PD, delete pod, verify contents, and repeat in rapid succession 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:207

[Fail] Pod Disks [It] should schedule a pod w/two RW PDs both mounted to one container, write to PD, verify contents, delete pod, recreate pod, verify contents, and repeat in rapid succession 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:266

[Fail] Services [BeforeEach] should be able to change the type and nodeport settings of a service 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:72

[Fail] Pods [BeforeEach] should *not* be restarted with a docker exec "cat /tmp/health" liveness probe [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:72

[Fail] Kubectl client [BeforeEach] Kubectl apply should apply a new configuration to an existing RC 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:72

[Fail] Proxy version v1 [BeforeEach] should proxy logs on node with explicit kubelet port [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:72

[Fail] EmptyDir volumes [BeforeEach] should support (root,0644,default) [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:72
```

**Comment by lavalamp** [comment]
@k8s-bot test this

**Comment by zhengguoyong** [comment]
@k8s-bot test this

**Pull request merged**
