### PR TITLE
Allow kubectl proxy to proxy everything

### PR DESCRIPTION
**Pull request by lavalamp**
The current kubectl can't proxy anything that's not under the /api path. This removes that restriction while still allowing old tooling work the same.

This is required for kubectl to be a drop-in replacement for the RO port; prometheus example is updated to show this.

### CODE REVIEW

**Comment by lavalamp** [comment]
Fixes #5921

**Comment by jlowdermilk** [comment]
lgtm. Aside from `/metrics` are there other pages that were previously inaccessible?

**Comment by lavalamp** [comment]
I didn't try it but I'm pretty sure the UI would also have been effected, also any pprof stuff under /debug...

**Comment by dchen1107** [comment]
cc/ @bprashanth

**Comment by erictune** [comment]
@stephenR this change may affect your findings about proxy security.

**Pull request merged**
