### PR TITLE
cacher test: fix leftover v2 test server

### PR DESCRIPTION
**Pull request by hongchaodeng**
I think this was dismissed in #30890

@timothysc @wojtek-t

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36712)

### CODE REVIEW

**Comment by wojtek-t** [comment]
@hongchaodeng - lgtm, but please fix failing tests/verification

**Comment by dims** [comment]
@wojtek-t : needed for v1.5?

**Comment by hongchaodeng** [comment]
@dims 
This is a bug fix in test. We should fix it in 1.5 IMO.

**Comment by dims** [comment]
@hongchaodeng ack. looks like there's a tiny failure. LGTM after that's fixed per @wojtek-t above

```
I1113 15:06:07.670] BUILD files are not up to date
I1113 15:06:07.671] Run ./hack/update-bazel.sh
I1113 15:06:07.672] FAILED   hack/make-rules/../../hack/verify-bazel.sh	25s
```

**Comment by hongchaodeng** [comment]
@dims @wojtek-t 
All checks passed.

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
@saad-ali - this is just a test fix

**Comment by saad-ali** [comment]
> @saad-ali - this is just a test fix

Ack, thanks.

**Pull request merged**
