### PR TITLE
fix todo: ignore updates where 'old' is equivalent to 'cur'.

### PR DESCRIPTION
**Pull request by tanshanshan**
**What this PR does / why we need it**:
ignore updates where 'old' is equivalent to 'cur'.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
@tanshanshan
possibly add a release note explaining the change.

/cc @mml 
/cc @kubernetes/sig-apps-pr-reviews

**Comment by nikhita** [comment]
@tanshanshan This needs a rebase, but looks good to be merged. :+1:

**Comment by tanshanshan** [comment]
@nikhita , I fixed it .
Thanks

**Pull request closed without merging**
