### PR TITLE
lease controller: only call once onRepeatedHearbeatFailure

### PR DESCRIPTION
**Pull request by aojea**
This hooks was added to deal with the problem of stuck connections,
usually calling a very disruptive function that forcefully close all the
TCP connections.

The hook was called continuously on the retry loop, if there are network failures
or slow networks, or apiserver being slow answering, this will cause
more disruption, since all TCP connections have to be continuously
reestablished.

Since HTTP2, client-go is smart enough to detect stale connections, so
this hooks should not really be needed, but for backwards compatibility
we just keep it and execute it once during the retry loop, it will be
executed again on the next cycle if necessary.

/kind bug

Fixes #

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @wojtek-t @liggitt 
/cc  @JohnRusk 
I have more changes related to the kubelet hearbeat, but this is an independent component and I didn't want to mix them

**Comment by aojea** [comment]
hmm, since https://github.com/kubernetes/kubernetes/pull/105490 in 1.23 we only have one TCP connection per client, so this change should be enough

**Comment by JohnRusk** [comment]
@aojea Thanks for moving this forward!  I'm looking forward to this being solved.

I'll see if I can give it a quick run on my test cluster today.

**Comment by JohnRusk** [comment]
aojea I just remembered, there are _two_ places that call onRepeatedHeartbeat failure. I saw them both in callstacks in my testing in Janurary.  This PR only fixes one. The other is in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status.go

I think we probably need a fix that applies to both, since I've seen them both being triggered.

**Comment by JohnRusk** [comment]
Out of curiosity, what's the reason for solving it this way, rather than with a wrapper around the close method, as in #107781?

**Comment by JohnRusk** [comment]
I tested this PR in my cluster. I replicated the new boolean flag into https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status.go before testing, for the reason described above.

It seemed to work OK.

**Comment by aojea** [comment]
> Out of curiosity, what's the reason for solving it this way, rather than with a wrapper around the close method, as in #107781?

Less layers of complexity, the client-go has its own internal retry logic, these functions has another loop to retry, adding a 3rd loop on top of those will make harder to debug the problems.

/hold

I still think we can get this right and remove all the hacks, right now the logic is very brittle, if the problems are stale connections those can only happen if we receive a network timeout error ...

**Comment by aojea** [comment]
sorry, I almost forget about this, after thinking more about this I don't feel the `onRepeatedHeartbeatFailure` hook is the right place , since we should not make assumptions there about that func are we going to run, despite it already has one, discarding the first hearbeat failure.

**Pull request closed without merging**
