### PR TITLE
Remove the SecurityContextDeny admission controller so that the testing environment matches the production environment

### LINKED ISSUE #18851: Admission control settings don't match in gce for config-default.sh and config-test.sh
SecurityContextDeny is [enabled by default](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-test.sh#L116) when we run e2e tests but as of https://github.com/kubernetes/kubernetes/pull/16986 is has been removed from the admission control plugins in [config-default.sh](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/config-default.sh#L110). 

This means that our e2e tests aren't testing representative clusters that would be created by users running `./cluster/kube-up.sh`.

/cc @pmorie @ArtfulCoder

### PR DESCRIPTION
**Pull request by roberthbailey**
This was removed from config-default.sh in #16986.

Fixes #18851

/cc @pmorie @vishh @ArtfulCoder

### CODE REVIEW

**Comment by vishh** [comment]
LGTM

**Comment by roberthbailey** [comment]
@k8s-bot unit test this issue: #18708

**Comment by roberthbailey** [comment]
ping @ArtfulCoder

**Comment by ArtfulCoder** [comment]
@roberthbailey 

https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/securitycontext/scdeny/admission.go#L51

The admission controller does not check if the pod spec has set pod.Spec.SecurityContext.Privileged == True.

As a result, my test which explicity tests whether Privileged pod can be created, succeeds, even though the SecurityContextDeny was set on ApiServer.
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/privileged.go#L129

I believe it might be a bug in the SecurityContext Admission control that we don't verify whether Privileged is set or not

@bgrant0607

**Comment by ArtfulCoder** [comment]
Actually, there is a separate flag for allow-privileged, probably for historical reasons and hence it is not part of the SecurityContextDeny admission control.

So that should solve the mystery of why privileged pods are allowed even with SecurityContextDeny. 
We have turned on --allow-privileged=true

**Comment by bgrant0607** [comment]
Please also do a search for SecurityContextDeny. It appears in lots of places.

cc @pweil-

**Comment by bgrant0607** [comment]
@ArtfulCoder What SecurityPolicyDeny does is described here:
https://github.com/kubernetes/kubernetes/blob/master/docs/admin/admission-controllers.md#securitycontextdeny

The comment says:
```
// Admit will deny any pod that defines SELinuxOptions or RunAsUser.
```

**Comment by bgrant0607** [comment]
And we want to allow privileged pods by default, in case that wasn't clear.

The feature should be controlled by PodSecurityPolicy instead, in most cases:
https://github.com/kubernetes/kubernetes/blob/5516b8684f69bbe9f4688b892194864c6b6d7c08/pkg/apis/extensions/v1beta1/types.go#L968

**Comment by ArtfulCoder** [comment]
@bgrant0607 
The doc you mentioned, https://github.com/kubernetes/kubernetes/blob/master/docs/admin/admission-controllers.md#securitycontextdeny  has a link to 
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/security-context.md#security-contexts which says it is for  (uid, gid, capabilities, SELinux role, etc..) 

Note the use of "etc" in the document :))

It is super confusing to have Admission Control (securitycontextdeny),  PodSecurityPolicy  and on top, another flag --allow-privileged, with seemingly overlapping responsibilities.

**Comment by ArtfulCoder** [comment]
Also we have Privileged field here: https://github.com/kubernetes/kubernetes/blob/5516b8684f69bbe9f4688b892194864c6b6d7c08/pkg/api/types.go#L2397 along with Privileged field at the location you mentioned:
https://github.com/kubernetes/kubernetes/blob/5516b8684f69bbe9f4688b892194864c6b6d7c08/pkg/apis/extensions/v1beta1/types.go#L970

**Comment by bgrant0607** [comment]
@ArtfulCoder I agree. I don't think we need SecurityContextDeny at this point. I was suggesting removing it more broadly from the defaults: from hyperkube, vagrant, kubemark, centos, ubuntu, HA config, etc.

Openshift uses SecurityContextConstraint instead:
https://github.com/openshift/origin/blob/master/pkg/cmd/server/kubernetes/master_config.go#L48
https://github.com/openshift/origin/blob/master/pkg/security/admission/admission.go#L97

cc @derekwaynecarr @pweil- @erictune

**Comment by pweil-** [comment]
+1 to removing this.  It was initially implemented to prevent usage of the features but now that they've had plenty of burn in time I don't think it's serving a purpose.

In the future a PSP admission controller will serve this purpose.

Also it would close: https://github.com/kubernetes/kubernetes/issues/16456

**Comment by erictune** [comment]
SGTM.

**Comment by roberthbailey** [comment]
@k8s-bot test this: issue #21463

**Comment by derekwaynecarr** [comment]
+1

**Comment by roberthbailey** [comment]
Rebased to try and avoid flakes. 

@k8s-bot test this issue #21475

**Pull request merged**
