### PR TITLE
Refactor env flag into sub pkg of util

### PR DESCRIPTION
**Pull request by resouer**
Part of #15634

Minor fix: `env` and `flag` into sub pkg

### CODE REVIEW

**Comment by resouer** [comment]
ping @thockin could u please review this? :)

**Comment by resouer** [comment]
ping @thockin  could u please review this?

**Comment by resouer** [comment]
@lavalamp Is it possible for you to review this PR? Seems Tim is out of notify ...

**Comment by lavalamp** [comment]
LGTM, thanks for cleanup :)

**Comment by resouer** [comment]
@k8s-bot e2e test this issue: #23321

**Comment by thockin** [comment]
LGTM, thanks for continuing on this :)

**Comment by resouer** [comment]
@k8s-bot e2e test this issue: #23321

**Pull request merged**
