### PR TITLE
correct OpenAPI extension in error message

### PR DESCRIPTION
**Pull request by alexzielenski**
when attemping to use preserveUnknownFields the error message leads you astray

#### What type of PR is this?

/kind cleanup
/kind documentation

#### What this PR does / why we need it:

I tried to apply the following CRD:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    svcat: "true"
  name: clusterserviceplans.servicecatalog.stable.com
spec:
  group: servicecatalog.stable.com
  names:
    categories:
    - all
    - svcat
    kind: ClusterServicePlan
    listKind: ClusterServicePlanList
    plural: clusterserviceplans
    singular: clusterserviceplan
  preserveUnknownFields: true
  scope: Cluster
  versions:
  - name: v1beta1
    served: true
    storage: true
```

I got the following error:

```
The CustomResourceDefinition "clusterserviceplans.servicecatalog.stable.com" is invalid:
* spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
* spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-preserve-unknown-fields to true in spec.versions[*].schema instead
*
```

I then did as instructed and added an openAPIV3Schema with x-preserve-unknown-fields:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    svcat: "true"
  name: clusterserviceplans.servicecatalog.stable.com
spec:
  group: servicecatalog.stable.com
  names:
    categories:
    - all
    - svcat
    kind: ClusterServicePlan
    listKind: ClusterServicePlanList
    plural: clusterserviceplans
    singular: clusterserviceplan
  scope: Cluster
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        x-preserve-unknown-fields: true
```

But I still got an error:

```
error validating data: ValidationError(CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema): unknown field "x-preserve-unkn0wn-fields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps; if you choose to ignore these errors, turn validation off with --validate=false
```

It is fixed when I change `x-preserve-unknown-fields` to be `x-kubernetes-perserve-unknown-fields`:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    svcat: "true"
  name: clusterserviceplans.servicecatalog.stable.com
spec:
  group: servicecatalog.stable.com
  names:
    categories:
    - all
    - svcat
    kind: ClusterServicePlan
    listKind: ClusterServicePlanList
    plural: clusterserviceplans
    singular: clusterserviceplan
  scope: Cluster
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        x-kubernetes-preserve-unknown-fields: true
```

This finally succeeds.

```
customresourcedefinition.apiextensions.k8s.io/clusterserviceplans.servicecatalog.stable.com created
```

Documentation in source: 

https://github.com/kubernetes/kubernetes/blob/d66477d5124c54f5cba225c7eb473c66aaba6686/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go#L287

https://github.com/kubernetes/kubernetes/blob/66af4ecfd5c4152542a95710edd9db9a4166464f/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_jsonschema.go#L90-L96

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by apelisse** [comment]
```
spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-preserve-unknown-fields to true in spec.versions[*].schema instead
```

Yeah, that message is wrong, thanks for fixing it. Can we improve that sentence? I don't find it very clear, or is it just me?

**Comment by alexzielenski** [comment]
> Can we improve that sentence? I don't find it very clear, or is it just me?

Half of it is buried in deep API layers that I think are out of scope for this PR: 

```
field.Invalid(field.NewPath("spec").Child("preserveUnknownFields"), crd.Spec.PreserveUnknownFields, "cannot set to true, set x-kubernetes-preserve-unknown-fields to true in spec.versions[*].schema instead")
```

The part we can control - I consider it to be reasonably pointing me in the right direction.

**Comment by alexzielenski** [comment]
This is fixed by #111557

I confirmed by following the steps in the original post. I've attach a CPU profile capturing the application of the CR to the apiserver. Also I've attached some flame graphs for those not so inclined:

[before_after_cpuprofiles.zip](https://github.com/kubernetes/kubernetes/files/9224155/before_after_cpuprofiles.zip)

k8s at e6a60c3b4d941da805d7e5548ffd462e5babc74d
Screen Shot 2022-07-29 at 7 08 24 PM

after applying #111557 the `mergingWalker` no longer makes an appearance in any cpu samples
Screen Shot 2022-07-29 at 7 09 43 PM

**Comment by dims** [comment]
testdata changes look good.

/approve

**Pull request merged**
