### PR TITLE
Call godep restore 2x in verify-godeps.sh

### LINKED ISSUE #14677: hack/verify-godeps.sh fails on master
`hack/verify-godeps.sh` is run as part of Shippable and seems to be failing on any PRs that change Godeps.

```
$ hack/verify-godeps.sh
Starting to download all kubernetes godeps. This takes a while
Download finished
Your Godeps.json is different:
--- /go/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/Godeps.json	2015-09-28 19:28:55.000000000 +0000
+++ /tmp/gopath.bycPi4/src/k8s.io/kubernetes/Godeps/Godeps.json	2015-09-28 19:41:46.681006178 +0000
@@ -578,15 +577,15 @@
 		},
 		{
 			"ImportPath": "golang.org/x/net/context",
-			"Rev": "cbcac7bb8415db9b6cb4d1ebab1dc9afbd688b97"
+			"Rev": "c2528b2dd8352441850638a8bb678c2ad056fd3e"
 		},
 		{
 			"ImportPath": "golang.org/x/net/html",
-			"Rev": "cbcac7bb8415db9b6cb4d1ebab1dc9afbd688b97"
+			"Rev": "c2528b2dd8352441850638a8bb678c2ad056fd3e"
 		},
 		{
 			"ImportPath": "golang.org/x/net/websocket",
-			"Rev": "cbcac7bb8415db9b6cb4d1ebab1dc9afbd688b97"
+			"Rev": "c2528b2dd8352441850638a8bb678c2ad056fd3e"
 		},
 		{
 			"ImportPath": "golang.org/x/oauth2",
Removing /tmp/gopath.bycPi4
```

I was able to reproduce on master by removing the early exit when no Godeps changes are shown by `git diff`: https://github.com/kubernetes/kubernetes/blob/master/hack/verify-godeps.sh#L44-L46

### PR DESCRIPTION
**Pull request by ncdc**
Fixes #14677

### CODE REVIEW

**Comment by ncdc** [comment]
Please see 14677 for full details of this workaround

**Comment by karlkfi** [comment]
I don't think it's a good idea to redefine the valid usage of godeps this way.

**Comment by eparis** [comment]
@karlkfi good point, as any user who types godep restore isn't going to get what we want them to have...

**Comment by ncdc** [comment]
@karlkfi @eparis I agree, **but** there is a bug somewhere between `go get` and `godep restore`. This at least will allow Godep bumps in the kube repo to proceed.

**Comment by ncdc** [comment]
Closing in favor of #14747

**Pull request closed without merging**
