### PR TITLE
Update cli verification to match new conventions

### PR DESCRIPTION
**Pull request by tcharding**
**What this PR does / why we need it**:

PR [885](https://github.com/kubernetes/community/pull/885) merged recently updating the conventions for cli Examples (arguments to `templates.Examples()`). This PR updates `cmd_sanity.go` so that the new conventions are verified when running `hack/verify-cli-conventions.sh`. This PR also fixes up all the warnings thrown by the additional verification.

**Special notes for your reviewer**:

Idea for this PR suggested by @fabianofranz in the comments of  [885](https://github.com/kubernetes/community/pull/885).

Unspecified by the conventions (and as far as I can tell in the k8s project) was when to wrap lines. The choice was made to wrap lines only after the end of a sentence (this relates to Example comments only).

All Examples should now be reasonably uniform. If it is decided the format needs modification this PR should at least make it easier to do so by script instead of by hand.

**Release note**:
```release-note
Clean up and make uniform all examples in kubectl help command.
```

/sig cli
/kind documentation
/kind cleanup

### CODE REVIEW

**Comment by tcharding** [comment]
I've been mulling over this since creating the PR. Maybe this is not a good change. When trying to pin down the conventions I thought that current Examples where quite mixed. After doing this PR I am of the opinion that the majority of Examples where of the form
```
# This is the comment
kubectl command --option
```
i.e Capitalized comment, no terminating period, command on next line with no prefix. Many comments had a terminating period (is this too trivial), and some used a colon. Majority of commands where uniform. The reasoning behind adding the convention of starting commands with a '$' was it come into line with `LongDesc`, in hindsight perhaps this is not necessary.

If this is important to the SIG, I'm happy to work towards getting it straightened out. If it is not that important feel free to say so and I'll close this PR and move onto something else.

thanks

**Comment by tcharding** [comment]
Having command examples prefixed with `$` does open up the possibility of adding a flag to the `help` command `--examples` (and possibly `--examples-brief`) that displays just the examples for a command (with and without the comment respectively). 

Would those flags be useful?

**Comment by fabianofranz** [comment]
I remember we explicitly decided to not prefix `$` to the examples some time ago.

Asking more people's opinions: @kubernetes/sig-cli-proposals @kubernetes/sig-cli-api-reviews

**Comment by tcharding** [comment]
Oh, the fault may be then that the conventions file is incorrect.  #885 shows that the conventions file currently indicates the use of `$`. 

If this has already been discussed then I guess we just need a ruling on what was previously decided, an update to the conventions file and I can do the grunt work of getting all the Example strings up to the decided conventions (and update `cmd_sanity.go`).

thanks

**Comment by pwittrock** [comment]
#885 is about pod ips on gce and is from 2014.   Wrong link?

**Comment by tcharding** [comment]
Woops. It's commit [885](https://github.com/kubernetes/community/pull/885) in kubernetes/community repository. thanks @pwittrock

**Comment by tcharding** [comment]
Closing this PR. Also closed #50228 which touches the same area. Moving forward my intent is as follows;
1. Submit PR updating `kubectl-conventions.md` (in community) to mirror the code base. This is in contrast to this PR which attempted to make the code base mirror the conventions.

2. Once conventions PR is merged, add verification code to check the Examples. Update all Examples so they pass the verification.

**Pull request closed without merging**
