### PR TITLE
Rename DaemonSet and StatefulSet hash label

### LINKED ISSUE #47554: Consistent hash label key across controllers
Here are the hash label keys of all controllers:
- Deployment: `pod-template-hash`
- DaemonSet: `daemonset-controller-hash` (new in 1.7)
- StatefulSet: `statefulset.beta.kubernetes.io/revision` (new in 1.7)

Had a brief discussion with @bgrant0607 and @kow3ns about this, it should be consistent. We can use `controller-revision-hash` for DaemonSet and StatefulSet, and keep Deployment as-is. Deployment hash label key should be different from other two because Deployment pods hash labels is used by selector (unlike the other two controllers). 

We probably should have used hash annotations instead of hash labels for DaemonSet and StatefulSet, since we don't use hash labels to select their history or pods. Hash labels are chosen for consistency. This is fine since we don't modify hash label values. 

@kubernetes/sig-apps-misc @kubernetes/sig-apps-api-reviews

### PR DESCRIPTION
**Pull request by janetkuo**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #47554

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/assign @kow3ns 
/cc @bgrant0607 
@kubernetes/sig-apps-api-reviews

### CODE REVIEW

**Comment by janetkuo** [comment]
federation is broken: #46827, waiting on fix to be merged

**Review by kow3ns — COMMENTED** [review]
Want to update the label for StatefulSet in the same PR?

**Comment by janetkuo** [comment]
@kow3ns sure

**Comment by smarterclayton** [comment]
/approve

because this is an API that would be public post release and we would
be unable to change it

**Review by kow3ns — APPROVED** [review]
/lgtm

**Pull request merged**
