### PR TITLE
using wait.Interrupted instead of deprecated wait.ErrWaitTimeout for apps

### PR DESCRIPTION
**Pull request by Rei1010**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
test/e2e/apps stop using deprecated wait.ErrWaitTimeout

#### Which issue(s) this PR fixes:

#107826

#### Special notes for your reviewer:
NONE

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by carlory** [comment]
Firstly, thanks for you contributions. It makes sense to me. 

however IMO, it won't bring sufficient benefits to this active issue https://github.com/kubernetes/kubernetes/issues/115164. 

/cc @pohly 

What do you think? Should we accept this changes now?

**Comment by pohly** [comment]
It's annoying that we are forced to keep updating tests that shouldn't be using the `wait` package at all, but until someone finds the time to replace that I suppose we have to follow the overall trend.

/lgtm
/approve

**Pull request merged**
