### PR TITLE
Add simple explanation to verify-spelling.sh

### PR DESCRIPTION
**Pull request by hase1128**
**What type of PR is this?**
/kind cleanup
/kind documentation

**What this PR does / why we need it**:
See https://github.com/kubernetes/kubernetes/issues/86597

**Which issue(s) this PR fixes**:
https://github.com/kubernetes/kubernetes/issues/86597

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by xichengliudui** [comment]
i don't think it's necessary
/cc @liggitt

**Comment by hase1128** [comment]
> i don't think it's necessary
> /cc @liggitt

@xichengliudui 
This is certainly not a significant improvement.
However, scripts without any description or usage are inconvenient for users. 
In fact, there is the following comment. 
(https://github.com/kubernetes/kubernetes/issues/86597#issuecomment-568947918)
Therefore, I think it is worth giving a brief overview and usage.

**Pull request merged**
