### PR TITLE
remove duplicate validation for --pod-running-timeout of kubectl attach

### PR DESCRIPTION
**Pull request by pandaamanda**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Flag --pod-running-timeout already validated in func Complete().

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by pandaamanda** [comment]
please take a look, thanks.
/assing @mengqiy  @derekwaynecarr

**Comment by pandaamanda** [comment]
please take a look, tks.
/assign @liggitt

**Review by soltysh — APPROVED** [review]
/ok-to-test
/lgtm
/approve

**Comment by liggitt** [comment]
this is consistently failing //staging/src/k8s.io/kubectl/pkg/cmd/attach unit tests

/hold

**Comment by pandaamanda** [comment]
Since the duplication is for ut, so close this pr.
/close

**Pull request closed without merging**
