### PR TITLE
Upgrade go-etcd to v0.4.6 (Take 2)

### PR DESCRIPTION
**Pull request by satnam6502**
In response to issue #5779
Updating the master to use etcd v.2.0.5 is in PR #5780

Replacing PR #5782 
I've manually cut out dependencies that I did not expect.
@a-robinson

### CODE REVIEW

**Comment by a-robinson** [comment]
Does this actually build? It doesn't look like we have either of those new packages in our repo yet. And this isn't actually changing the version of go-etcd.

**Comment by satnam6502** [comment]
Thanks... let me investigate...

**Comment by satnam6502** [comment]
Updated. I will attempt to rebase this into a fresh branch from master to make sure it works and then run e2e.

**Comment by dchen1107** [comment]
Still missing package github.com/coreos/etcd/etcdserver/etcdhttp/httptypes

Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/client.go:19:2: cannot find package "github.com/coreos/etcd/etcdserver/etcdhttp/httptypes" in any of:
	/home/shippable/.gvm/gos/go1.4/src/github.com/coreos/etcd/etcdserver/etcdhttp/httptypes (from $GOROOT)
	/home/shippable/workspace/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/coreos/etcd/etcdserver/etcdhttp/httptypes (from $GOPATH)

**Comment by satnam6502** [comment]
So I think I am fundamentally confused about godep.
Surely when I did the `go get` for the `httptypes` package I should see with `git status` what files need to be added? I did not see any `httptypes` files?

**Comment by satnam6502** [comment]
This is what I did:
```
$ go get -u github.com/coreos/go-etcd/etcd
$ godep update github.com/coreos/go-etcd/etcd
satnam@satnam-linux:~/gocode/src/github.com/GoogleCloudPlatform/kubernetes$ git status
# On branch getcd
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   Godeps/Godeps.json
#	modified:   Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/client.go
#	modified:   Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/client_test.go
#	modified:   Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/cluster.go
#	modified:   Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/error.go
#	modified:   Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/get.go
#	modified:   Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/options.go
#	modified:   Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/requests.go
#	modified:   Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/set_curl_chan_test.go
#	modified:   Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/set_update_create.go
#
```
Building shows we need `httptypes` so I did:
```
$ go get github.com/coreos/etcd/etcdserver/etcdhttp/httptypes
satnam@satnam-linux:~/gocode/src/github.com/GoogleCloudPlatform/kubernetes$ godep save ./...
satnam@satnam-linux:~/gocode/src/github.com/GoogleCloudPlatform/kubernetes$ git status
# On branch getcd
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   Godeps/Godeps.json
#	modified:   Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/client.go
#	modified:   Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/client_test.go
#	modified:   Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/cluster.go
#	modified:   Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/error.go
#	modified:   Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/get.go
#	modified:   Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/options.go
#	modified:   Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/requests.go
#	modified:   Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/set_curl_chan_test.go
#	modified:   Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/set_update_create.go
```

Why don't I see any source files for `httptypes`?

**Comment by a-robinson** [comment]
The commands you're running look correct. I don't know why httptypes isn't being pulled in. I tried running the commands on my own setup, but it can't even run `godep restore` right now.

**Comment by dchen1107** [comment]
I ran into the same problem as @satnam6502, still digging into the detail

**Comment by dchen1107** [comment]
@satnam6502 I am going to manually upgrade the library.

**Pull request closed without merging**
