### PR TITLE
Add a central simple getting started guide with kubernetes guide.

### LINKED ISSUE #5799: "Getting started" guides should point to 'examples/' rather than have their own individual examples
I spent a good chunk of last week working through the "Getting started" guide for GCE and the Guestbook example.  It seems to me it would be wise to integrate these two resources more.

Right now, the [Getting Started with GCE](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/gce.md) guide has its own example to work through involving Nginx on two containers.  The docs would be more maintainable if this instead linked to a universal example, (since it doesn't depend on the provider you're using,) either involving Nginx or not, e.g. the [Guestbook example](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/guestbook).

### PR DESCRIPTION
**Pull request by brendandburns**
Point several getting started guides at this doc.

Partly addresses #5799

### CODE REVIEW

**Comment by jlowdermilk** [comment]
lgtm

**Comment by brendandburns** [comment]
Updated to fix the broken test and add more coverage for the docs I added.

**Comment by bgrant0607** [comment]
Better than it was, I'm ok with merging as is, but doesn't resolve #5799. Also, we shouldn't show raw pods unless the restart policy isn't Always.

**Comment by bgrant0607** [comment]
The example also contains far more fields than necessary.

**Pull request merged**
