### PR TITLE
add myself for sig-cli reviewer

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:
This is adding myself as sig-cli reviewer.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/assign @soltysh

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by smarterclayton** [comment]
@soltysh can someone from sig-cli provide the lgtm

**Comment by soltysh** [comment]
> @soltysh can someone from sig-cli provide the lgtm

I already did :wink:

**Pull request merged**
