### PR TITLE
Record event when image GC fails.

### PR DESCRIPTION
**Pull request by vmarmol**

### CODE REVIEW

**Comment by vmarmol** [comment]
All tests are green :)

**Comment by dchen1107** [comment]
Rebase please :-)

**Comment by vmarmol** [comment]
Rebased and green, PTAL @dchen1107 :)

**Comment by yujuhong** [comment]
Travis failing...? :)

**Comment by vmarmol** [comment]
Suuuuper weird, it was an infrastructure failure on code that didn't exist :-\ kicking off again.

**Comment by yujuhong** [comment]
LGTM.

**Pull request merged**
