### PR TITLE
Fix `hack/update-generated-docs.sh`

### PR DESCRIPTION
**Pull request by lukaszo**
It is failing because of changes in #38126 and #38154

### CODE REVIEW

**Comment by lukaszo** [comment]
I signed it!

**Comment by lukaszo** [comment]
cc @ixdy @caesarxuchao

**Comment by smarterclayton** [comment]
You can't change proposals due to the move.  Drop those changes and I'll approve.

**Comment by lukaszo** [comment]
@smarterclayton I can't drop because it causes `hack/update-generated-docs.sh` to fail which causes `make update` to fail.

I need at least fix this line:
```bash
kubernetes/src/k8s.io/kubernetes/docs/proposals/multi-platform.md
----
md-links:
On line 379: "../../build-tool/build-image/cross/Dockerfile": target not found

FAIL: some manual changes are still required.
```

**Comment by smarterclayton** [comment]
I think we have to start excluding docs/proposals and docs/design from that tool

**Comment by lukaszo** [comment]
Any short term solution just to fix `make update`?

**Comment by lukaszo** [comment]
I see that all this files will be deleted from this repo soon. I'm closing the issue.

**Pull request closed without merging**
