### PR TITLE
Add request count to APICall metric

### PR DESCRIPTION
**Pull request by shyamjvs**
Ref https://github.com/kubernetes/kubernetes/issues/44701

This should add beside the API call latencies, the count of the requests.

cc @wojtek-t @gmarek

### CODE REVIEW

**Comment by shyamjvs** [comment]
@gmarek Could you PTAL?

**Comment by gmarek** [comment]
@k8s-bot unit test this

**Comment by shyamjvs** [comment]
@k8s-bot unit test this

**Comment by shyamjvs** [comment]
@k8s-bot unit test this

**Pull request merged**
