### PR TITLE
extract Exit code from if...else if...

### PR DESCRIPTION
**Pull request by NickrenREN**
extract Exit(0) code

### CODE REVIEW

**Comment by brendandburns** [comment]
/lgtm

LGTM from the bulk LGTM tool

**Comment by NickrenREN** [comment]
@k8s-bot node e2e test this

**Comment by NickrenREN** [comment]
@k8s-bot cri node e2e test this

**Comment by NickrenREN** [comment]
@brendandburns  Thanks.  Could you help add release-note label and remove do-not-merge ?

**Comment by NickrenREN** [comment]
@brendandburns  Sorry for wasting your time! My understanding is wrong. Close this

**Pull request closed without merging**
