### PR TITLE
Fix unbound variable in ubuntu cluster script

### PR DESCRIPTION
**Pull request by hurf**
roles -> role

### CODE REVIEW

**Comment by hurf** [comment]
@dalanlan

**Comment by dalanlan** [comment]
The code is kinda messy. Ref #22845 to sort it out.

**Comment by hurf** [comment]
@dalanlan - I don't think  #22845 is solving the same problem.

**Comment by ZhangZhenhua** [comment]
@hurf Actually, #22845 **is** solving the same problem. Instead of letting user change nodes and roles definition in script, it's also OK passing them as env. As said in #22249, naming them as 'nodes' and 'roles' is more natural to users. Passing env for 'nodes' and 'role' seems misleading and error-prone. Based on that, I changed the roles array used internally as 'roles_array', which is exactly what #22845 did.

**Comment by dalanlan** [comment]
This can be safely closed since #22845 is set.

**Comment by hurf** [comment]
closing for dup of #22845

**Pull request closed without merging**
