### PR TITLE
kubectl: honor --cache-dir so that server resources and http-cache data are stored in the same location

### LINKED ISSUE #91846: kubectl writes to ~/.kube/cache even when --cache-dir is set elsewhere
```
# download latest
curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
chmod +x kubectl

# clear cache ... then get something
rm -rf ~/.kube/cache
./kubectl get nodes --cache-dir foo

# cache is back
ls -al ~/.kube/cache
-> discovery folder
```

might be related to https://github.com/kubernetes/kubernetes/issues/78664

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Honor `--cache-dir` so that server resources and http-cache data are stored in the same location:

1) If `--cache-dir` is set and not empty (such as `/foo/http-cache`),
    the discovery cache dir will be `/foo/cache/discovery`
2) If `--cache-dir` is set and empty,
    the discovery cache dir will be the default value (`~/.kube/cache/discovery`)
3) If `--cache-dir` is not set,
    the discovery cache dir will be the default value (`~/.kube/cache/discovery`)

**Which issue(s) this PR fixes**:

Fixes #91846 #78664

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/milestone v1.19

**Comment by hrivera-ntap** [comment]
Is there a plan to cherry pick this to 1.17 / 1.18?

**Pull request merged**
