### PR TITLE
remove dgoodwin and dmmcquay to kubeadm reviewers

### PR DESCRIPTION
**Pull request by mikedanese**
@dgoodwin says he needs to work on other stuff right now. @dmmcquay says he wants to help with reviews.

### CODE REVIEW

**Comment by dgoodwin** [comment]
Back ~April hopefully.

**Comment by dmmcquay** [comment]
@mikedanese I already created a PR adding myself. https://github.com/kubernetes/kubernetes/pull/41424

Did you see that one? Should I edit mine and remove @dgoodwin from mine or close it?

**Comment by dmmcquay** [comment]
@mikedanese want to rebase this? @dgoodwin is still getting assigned PRs.

**Comment by mikedanese** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
