### PR TITLE
Start to kill the word "minion"

### PR DESCRIPTION
**Pull request by thockin**
Mostly mechanican changes that were pretty obvious.

This series is sort of risky.  I think we only want the first commit here and the rest later?  Need to do docs, too, and that is pretty manual.

I don't think I changed any "minion" string where the context was salt (for which "minion" is correct")

### CODE REVIEW

**Comment by bgrant0607** [comment]
Awesome!

**Comment by bgrant0607** [comment]
Ref #1111

**Comment by bgrant0607** [comment]
Looks pretty reasonable to me. Did you run e2e?

**Comment by thockin** [comment]
Did not run e2e yet, no time today.

**Comment by justinsb** [comment]
So to confirm: the new names are masters & nodes?  And a master is not a node? (I have a PR coming for configuring security groups for AWS, and was going to give the masters & TNFKAM* different security groups; I might as well give them the right names if I can)

(* the nodes formerly known as minions)

**Comment by bgrant0607** [comment]
The current name is node.

The "master" is currently not a full schedulable node running kubelet, kube-proxy, etc., but that's the future -- self-hosting of the control plane (see #246 for some old discussion).

**Comment by thockin** [comment]
To surface a side discussion from a meeting - maybe we're over the hump of
confusing k8s "minion" with salt minions?  Maybe we can just keep "minion"?

**Comment by bgrant0607** [comment]
```
grep -r -i minion cluster cmd contrib docs examples hack pkg plugin test www |wc -l
1713
grep -r -i node cluster cmd contrib docs examples hack pkg plugin test www |wc -l
5411
```

**Comment by wojtek-t** [comment]
@thockin - what is the plan for this PR? Are we going to proceed with it or should we close it?

**Comment by wojtek-t** [comment]
@thockin - what is the plan for this PR? Are we going to proceed with it or should we close it?

**Comment by thockin** [comment]
We should still do it, but this PR is pretty obsolete.

On Tue, Sep 8, 2015 at 5:08 AM, Wojciech Tyczynski <notifications@github.com

**Comment by wojtek-t** [comment]
@thockin can we close this one? It might be easier to start it from scratch than to rebase this one :)

**Comment by wojtek-t** [comment]
@thockin - thanks. I can try to redo some if it in my free cycles.

**Comment by davidopp** [comment]
I still think we should use "minion" in cases where we are referring to something that can only be a worker node.

Even once we have self-hosting I think it will be a useful distinction as some people won't want to share their master nodes with user containers for security and performance isolation reasons.

**Comment by wojtek-t** [comment]
@davidopp can you please give an example of where you think we should leave minion? From what you wrote it seems to me that you're referring to places that are exposed to user (e.g. kube-up script?).
My thinking is that since we explicitly name it "Node" in v1 api, all places that refer to it (e.g. pkg/registry) should also have "node"-related names (not "minion" ones).

**Pull request closed without merging**
