### PR TITLE
Automated cherry pick of #68096: add make targets for building server images

### PR DESCRIPTION
**Pull request by BenTheElder**
Cherry pick of #68096 on release-1.10.

#68096: add make targets for building server images

```release-note
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
This would also need to be updated to handle kube-aggregator due to https://github.com/kubernetes/kubernetes/commit/a66e1f089ea95375cc7549660ad951d55a829915#diff-0ee501c7b4b1ab61678579826c6d6534 only being in master post-1.11.

**Comment by MaciekPytel** [comment]
Why do we need to cherry-pick this? It seems more like a convenience feature for developers than a bugfix.

**Comment by MaciekPytel** [comment]
I see, that makes sense. Can we close this PR and open a separate one for the backport though? "automated cherry-pick" suggests it's exactly the same as base PR and they're usually not reviewed as thoroughly.

**Pull request closed without merging**
