### PR TITLE
Add Endpoint Slice API Test

### PR DESCRIPTION
**Pull request by swetharepakula**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
This PR adds a E2E test that tests all the EndpointSlice APIs.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
KEP: [EndpointSlice KEP](https://github.com/kubernetes/enhancements/blob/8413469b89851d094eb22813a06594bd4a6d36a4/keps/sig-network/0752-endpointslices/README.md)
Enhancement Issue: kubernetes/enhancements#752

/cc @aojea @andrewsykim @thockin @robscott @wojtek-t
/assign @liggitt
/sig network
/sig testing
/priority important-soon

### CODE REVIEW

**Comment by robscott** [comment]
Thanks!

/ok-to-test

**Comment by robscott** [comment]
Thanks!

/lgtm

**Comment by palnabarun** [comment]
Since the PR was lgtm'ed and approved before the Code Freeze was in effect and is just blocked on Prow, I am adding it to the milestone.

/milestone v1.21

**Comment by Riaankl** [comment]
Thank you @swetharepakula for this e2e tests.
In the update of APISnoop it can be seen that 3 additional endpoints are tested.
https://apisnoop.cncf.io/1.21.0/stable/discovery
image

**Comment by robscott** [comment]
@Riaankl do you know why that seems to conflict with what was actually added by this test? This test seems to pretty clearly include `patch`, `read`, and `delete` calls. I think we may still be missing `replace`, but it doesn't seem like we should be missing all of those with this PR in.

**Comment by Riaankl** [comment]
@robscott I do not see any obvious reason why the endpoints do not show up in the logs. And I have little knowledge about Network endpoints.
/cc @johnbelamaric

**Comment by johnbelamaric** [comment]
all namespace list and watch should be there too. it's very odd. It would seem to be an apisnoop reporting issue - we should double check the logs and see

**Comment by Riaankl** [comment]
> all namespace list and watch should be there too. it's very odd. It would seem to be an apisnoop reporting issue - we should double check the logs and see

Thank you for the quick review @johnbelamaric 
We will check the log information in APISnoop to see if something shows up there.

**Comment by swetharepakula** [comment]
Just verified that all the endpoints are being tracked now. Thanks @Riaankl & @johnbelamaric !
https://apisnoop.cncf.io/1.21.0/stable/discovery
Screen Shot 2021-03-12 at 1 53 54 PM

**Comment by Riaankl** [comment]
@swetharepakula @robscott 
50% is only e2e tested and 50% conformance tested. All should be conformance tested,
We are busy looking at how APISnoop is consuming the data created by these endpoints in the audit logs.
If more action is needed around the tests/promotion I will get back to you.

**Comment by swetharepakula** [comment]
This PR added coverage for some of the endpoints. We are waiting for the 2 week soak policy to promote to conformance.

**Comment by Riaankl** [comment]
@swetharepakula I can not find the EndpointSlice tests on the [test grid](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&width=sig-network&include-filter-by-regex=EndpointSlice).
When are the 2 weeks over for this test?
Please keep in mind that the 1.21 test freeze is on 23 March. It is a requirement that all new GA endpoints must have Conformance tests in the same release that the endpoints graduate.

**Comment by Riaankl** [comment]
> > all namespace list and watch should be there too. it's very odd. It would seem to be an apisnoop reporting issue - we should double check the logs and see
> 
> Thank you for the quick review @johnbelamaric
> We will check the log information in APISnoop to see if something shows up there.

@johnbelamaric Thank you for your advice, it turned out to be the way APISnoop consumes these specific endpoints logs.
It now shows up correctly in the logs and the UI.

**Comment by swetharepakula** [comment]
@Riaankl I am not exactly sure what the difference in the links are but this testgrid link shows the tests: https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=EndpointSlice&width=5.

The test started running 3/10/2021, so it will qualify for conformance on the 24th.

One clarification, is the test freeze on March 23 or March 24th? The release [docs](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.21#tldr) say March 24.

**Comment by Riaankl** [comment]
@swetharepakula testgrid is looking good. (got my link wrong)
Yes, 24th is correct, I normally try and close all open points a day before.
Thank you for the GREAT work.
Looking forward to the Promotion.

**Pull request merged**
