### PR TITLE
Change default maxUnavailable in Deployment to 0

### LINKED ISSUE #46575: Default values for number of replicas and maxUnavailable causes deployments to report as successful rolled out when no pods available
**CHANGE REQUEST**

**Kubernetes version** (use `kubectl version`):
Client Version: v1.6.4
Server Version: v1.6.2
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: N/A
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS
- **Kernel** (e.g. `uname -a`): Linux 4.8.0-52-generic 55~16.04.1-Ubuntu
- **Install tools**: N/A
- **Others**: N/A

**What happened**:
Default values for number of replicas and maxUnavailable causes deployments to report as successful rolled out when no pods are available.

**What you expected to happen**:
Expected saner defaults that would not report the deployment as successful rolled out when no replicas are available.

**How to reproduce it** (as minimally and precisely as possible):
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: review-test-master
spec:
  template:
    spec:
      containers:
      - name: somename
        image: $CI_REGISTRY_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: $CI_REGISTRY
```
Make this fail by, e.g., specifying some private registry with wrong credentials. Deployment will be successful

```
$ kubectl rollout status deployment/review-test-master --namespace ci
deployment "review-test-master" successfully rolled out
```
although nothing is available:
```
$ kubectl get deploy/review-test-master --namespace ci 
NAME                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
review-test-master   1         1         1            0           9m
```
**Anything else we need to know**:
This is caused by the fact that by default replicas is set to 1 while maxUnavailable is also set to 1 allowing deployments without any running pods to report as successful when default settings are used.

### PR DESCRIPTION
**Pull request by vieira**
**What this PR does / why we need it**:
Given that the default number of replicas is 1, if the default value for `maxUnavailable` is also 1 we end up with successful deployments where all pods are in a failed state.

As the default value for maxSurge is 2, changing the default for `maxUnavailable` to 0 behaves more closely to what one would reasonable expect for all cases I can think of.

For bigger, more complex deployments it's likely that the operator will want to change the default in both cases (either if it is 0 or 1), so I don't see any clear disadvantages in having the default set to 0, while having the advantage of working as expected when the number of replicas is 1 (which is the default).

**Which issue this PR fixes**: fixes #46575

**Special notes for your reviewer**:
First PR.

**Release note**:
```release-note
```

### CODE REVIEW

**Comment by krmayankk** [comment]
@vieira i think we decided to do 25% so its percentage based and in case one instance deployments, its guranteed that 25% is not 1. @kargakis correct me if i am wrong

**Comment by piosz** [comment]
@k8s-bot ok to test

**Review by janetkuo — COMMENTED** [review]
@vieira changing default value breaks [compatibility](https://github.com/kubernetes/community/blob/master/contributors/devel/api_changes.md#on-compatibility). We can't do this without adding a new API version.

**Comment by janetkuo** [comment]
> BTW should the default for maxUnavailable be 0 or 25% like @krmayankk suggested? I can easily change it to 25% and I guess it would solve the same problems?

@vieira Deployment sets default maxUnavailable to 1 in extensions/v1beta1 and 25% in apps/v1beta1

**Comment by vieira** [comment]
As I understand this is fixed with `apps/v1beta1` which uses saner defaults. I will drop this PR. Thanks!

**Pull request closed without merging**
