### PR TITLE
Overflows when using strconv.Atoi and downcasting the result

### PR DESCRIPTION
**Pull request by Toper2035**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This migrates us from AtoI to a ParsePort method which accounts for overflow.

**Which issue(s) this PR ref**:
#81121

**Special notes for your reviewer**:
NONE

### CODE REVIEW

**Review by wgliang — APPROVED** [review]
/lgtm

Thanks, If you are interested, similar problems exist in kubeadm and kubeproxy.

**Comment by Toper2035** [comment]
@wgliang yes, other rest similar problems i'll have a check.

**Comment by Toper2035** [comment]
@tanjunchen yes, I update the comment from fix to ref.

**Comment by danwinship** [comment]
@Toper2035 this needs to be rebased and re-pushed.

**Pull request closed without merging**
