### PR TITLE
kubectl: ignore only update conflicts in the scaler

### PR DESCRIPTION
**Pull request by 0xmichalis**
@kubernetes/kubectl is there any reason to retry any other errors?

### CODE REVIEW

**Comment by kargakis** [comment]
@smarterclayton @ironcladlou this is so we can have more meaningful logs in the deployer pod. Currently all update errors (except [invalid](https://github.com/kubernetes/kubernetes/blob/46f167188afe56e055ad0a88283d4eb69fe2d232/pkg/kubectl/scale.go#L119)) are retried and eventually the poller times out and returns a non-sensical message to the user ("timed out waiting for the condition"). Does it make sense to retry only on 409? Can you think of another rc update failure where we want the deployer to keep trying?

**Comment by smarterclayton** [comment]
I would only expect to retry on 409, and *maybe* temporary network errors, but that's it.

**Comment by kargakis** [comment]
@janetkuo can you review this when you have free time? I would like it merged as soon as the code freeze is over (got any dates?).

**Comment by kargakis** [comment]
Adding P2 since it's needed for debugging https://github.com/kubernetes/kubernetes/pull/27048 which is also P2.

**Comment by kargakis** [comment]
Bumping to P0, following the issue priority

**Comment by kargakis** [comment]
Hm, the flake is not related to the scaler, dropping to P2

**Comment by pwittrock** [comment]
@kargakis I am on vacation but will try to review this in the next week or 2

**Comment by smarterclayton** [comment]
I've got it.  LGTM.

Does the default scale implementation for RC / D use patch on the underlying resource?  Or not, because we don't have preconditions?

**Comment by pwittrock** [comment]
@smarterclayton Thanks

**Comment by smarterclayton** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by kargakis** [comment]
> Does the default scale implementation for RC / D use patch on the underlying resource? Or not, because we don't have preconditions?

Full updates, I guess because of preconditions

**Pull request merged**
