### PR TITLE
Remove redundant variable definitions in scheduler apis defaults.go

### PR DESCRIPTION
**Pull request by xiaomudk**
#### What type of PR is this?
/kind cleanup
/kind flake

#### What this PR does / why we need it:
Remove redundant variable definitions in scheduler apis defaults.go
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by denkensk — COMMENTED** [review]
/lgtm

Thanks. @xiaomudk

**Comment by ahg-g** [comment]
/approve

thanks

**Pull request merged**
