### PR TITLE
Fixes kubectl skew test failure when using kubectl.sh

### PR DESCRIPTION
**Pull request by fabianofranz**
Fixes leftovers from https://github.com/kubernetes/kubernetes/pull/42737.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fabianofranz** [comment]
@sttts mind approving? Tks!

**Comment by ethernetdan** [comment]
@ixdy @spxtr @pwittrock does this look okay?

**Comment by fabianofranz** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
