### PR TITLE
Add the Juju charms to Kubernetes

### PR DESCRIPTION
**Pull request by mbruzek**
This is a follow up to the original Juju pull request: 
https://github.com/GoogleCloudPlatform/kubernetes/pull/5414

In accordance with @erictune's suggestion we are adding the charms and a bundle to keep in better sync with the kubernetes project.

`cluster/kube-up.sh` will deploy the local charms and the bundle from the kubernetes repository and stand up a cluster.

We have done a lot of work to update the cluster/juju/util.sh to the v0.15.0 release that changed the API and a lot of changes:
- Added the Juju charms to `cluster/juju/charms` directory.
- Added a Juju bundle to `cluster/juju/bundles` directory.
- Changing `cluster/juju/util.sh` script uses the bundle to deploy the charms from the kubernetes repository.
- Updated the charms and bundle to work with v0.15.0 changes.
- Updated the charms to use v1beta3 which is default in v0.15.0.

We are still seeing some issues with the `validate-cluster.sh` script ('Error: no resource "cs" has been defined') but I don't think that is related to our changes in this pull request.  Manual testing shows that we can create objects in the kubernetes cluster.

### CODE REVIEW

**Comment by erictune** [comment]
@whitmo needs to state on this PR that he intended for his commits to be on this PR, otherwise, our CLA robot is confused.

**Comment by whitmo** [comment]
@erictune Is stating here good enough? I also filled in the personal CLA from my user account (and will make sure further commits come from my canonical address).

**Comment by erictune** [comment]
LGTM.  I don't know why CLAbot is not happy, but seems like this PR is covered.

**Comment by erictune** [comment]
automated build says it doesn't like your boilerplate.

$ ./hack/verify-boilerplate.sh
Boilerplate header is wrong for: cluster/juju/charms/trusty/kubernetes-master/files/create_kubernetes_tar.sh
Boilerplate header is wrong for: cluster/juju/charms/trusty/kubernetes-master/scripts/guestbook.sh
Boilerplate header is wrong for: cluster/juju/charms/trusty/kubernetes/files/create_kubernetes_tar.sh
The command "./hack/verify-boilerplate.sh" failed and exited with 1 during .

I think all the shell scripts need to have Google copyright at the top.

**Comment by mbruzek** [comment]
@erictune Sorry about that, those were scripts we no longer use so I removed them.

**Comment by erictune** [comment]
thanks for the contribution and for your patience!

**Pull request merged**
