### PR TITLE
fix(hpa): set preferred APIVersions for scale targets when missing

### PR DESCRIPTION
**Pull request by hezhizhen**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

```go
// CrossVersionObjectReference contains enough information to let you identify the referred resource.
type CrossVersionObjectReference struct {
	// Kind of the referent; More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
	Kind string `json:"kind" protobuf:"bytes,1,opt,name=kind"`
	// Name of the referent; More info: http://kubernetes.io/docs/user-guide/identifiers#names
	Name string `json:"name" protobuf:"bytes,2,opt,name=name"`
	// API version of the referent
	// +optional
	APIVersion string `json:"apiVersion,omitempty" protobuf:"bytes,3,opt,name=apiVersion"`
}
```

APIVersion is optional, but if we leave it empty and set Kind to Deployment for instance, there are some errors as below:

image

My solution is to set preferred APIVersions for scalable resources.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by hezhizhen** [comment]
/sig/autoscaling

**Comment by liggitt** [comment]
isn't omitting apiVersion an invalid reference specification for things like deployment? fixing up bad data from a user using defaults doesn't seem like a good idea.

**Comment by hezhizhen** [comment]
> isn't omitting apiVersion an invalid reference specification for things like deployment? fixing up bad data from a user using defaults doesn't seem like a good idea.

Since the APIVersion is optional, I suppose it's okay to leave it empty and Kubernetes will find the resource within preferred APIVersions.

**Pull request closed without merging**
