### PR TITLE
Cleanup: pkg/util/ipset #108801

### LINKED ISSUE #108801: Cleanup: pkg/util/ipset
As exposed in https://github.com/kubernetes/kubernetes/pull/108351 the validate logic should probably return an `error` and the test should compare the error string with a known value - to prove that it failed for the right reasons.

Additionally the test could uset `t.Run()` to print a helpful name, rather than the comments tracking `// case[3]` 

Easy change, good beginner case.

### PR DESCRIPTION
**Pull request by muyangren2**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Additionally the test could uset t.Run() to print a helpful name, rather than the comments tracking
#### Which issue(s) this PR fixes:

Fixes #108801

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
Duplicate of #108946

**Comment by muyangren2** [comment]
> Duplicate of #108946

ok ,thanks

**Comment by pacoxu** [comment]
/close
since https://github.com/kubernetes/kubernetes/pull/108946 was merged

**Pull request closed without merging**
