### PR TITLE
Now if GetPodStatus is not ok, it will record PodStartDuration and ignore the pod Phase

### PR DESCRIPTION
**Pull request by andrewshaoyu**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Now if GetPodStatus is not ok, it will record PodStartDuration and ignore the pod Phase.
``` go
if a || b && c{
    // if a == true, will fast pass, b&&c will be ignored.
}
```

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
/lgtm

**Comment by bart0sh** [comment]
@andrewshaoyu can we cover this by unit or e2e test(s) please?

**Comment by andrewshaoyu** [comment]
> @andrewshaoyu can we cover this by unit or e2e test(s) please?

Is there any examples? I have no idea. I do not find any unit tests like this and I'm not familiar with the e2e tests.

**Comment by bart0sh** [comment]
Sure, there are test cases for this module in the `kubelet_test.go` file in the same directory as `kubelet.go`.

**Comment by pacoxu** [comment]
> /assign @bobbypage @sergeyevstifeev @mrunalp @dchen1107 @derekwaynecarr

/assign @SergeyKanzhelev 
(assign to Sergey)

**Pull request closed without merging**
