### PR TITLE
[windows-test] check nil in MetricsEqualIgnoreTimestamp

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind failing-test

#### What this PR does / why we need it:
Failure cluster [df4d0b863f0818b642f0](https://go.k8s.io/triage#df4d0b863f0818b642f0)

#### Which issue(s) this PR fixes:
Fixes None

#### Special notes for your reviewer:

```
=== RUN   TestGetMetricsBlockInvalid
--- FAIL: TestGetMetricsBlockInvalid (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0xf65636]

goroutine 13 [running]:
testing.tRunner.func1.2({0x10f46a0, 0x1f41390})
	C:/Program Files/Go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	C:/Program Files/Go/src/testing/testing.go:1392 +0x39f
panic({0x10f46a0, 0x1f41390})
	C:/Program Files/Go/src/runtime/panic.go:838 +0x207
k8s.io/kubernetes/pkg/volume/testing.MetricsEqualIgnoreTimestamp(...)
	C:/kubernetes/pkg/volume/testing/testing.go:1720
k8s.io/kubernetes/pkg/volume_test.TestGetMetricsBlockInvalid(0xc000341380)
	C:/kubernetes/pkg/volume/metrics_block_test.go:30 +0x76
testing.tRunner(0xc000341380, 0x13a3548)
	C:/Program Files/Go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	C:/Program Files/Go/src/testing/testing.go:1486 +0x35f

```

#### Does this PR introduce a user-facing change?

```release-note
None
```
#### Recent failures:
[2022/9/30 19:14:17 ci-kubernetes-unit-windows-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1575806220697079808)
[2022/9/30 07:13:20 ci-kubernetes-unit-windows-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1575624787730894848)
[2022/9/29 19:13:20 ci-kubernetes-unit-windows-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1575443590820139008)
[2022/9/29 07:13:19 ci-kubernetes-unit-windows-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1575262393833885696)
[2022/9/28 19:12:36 ci-kubernetes-unit-windows-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1575081019504070656)

### CODE REVIEW

**Comment by pacoxu** [comment]
/sig windows
@kubernetes/sig-windows-bugs

**Comment by marosset** [comment]
/assign @claudiubelu 
Is this covered in any of your open Windows unit test PRs?

**Comment by pacoxu** [comment]
This is about the storage test of windows.
/assign @xing-yang
ping @claudiubelu 
Can this be reviewed before test freeze next week?

**Comment by mattcary** [comment]
/lgtm

This is testing code, either we should merge this now, or cherrypick to 1.26 after the freeze if that's no longer possible.

**Comment by pacoxu** [comment]
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master seems to be green now.

**Comment by pacoxu** [comment]
/remove-area apiserver cloudprovider code-generation dependency ipvs kubeadm kubectl kubelet provider/gcp release-eng 
/remove-sig api-machinery apps architecture auth autoscaling  cli cloud-provider cluster-lifecycle contributor-experience instrumentation network release scalability  node scheduling  security testing
/remove-wg structured-logging

**Comment by pacoxu** [comment]
/close 

> https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master seems to be green now.

TestGetMetricsBlockInvalid Passed as this is moved to linux test only after 
https://github.com/kubernetes/kubernetes/commit/af77381e01775a288fb8c5fb101837a197295315#diff-0956c00cdd7a303ba393de821f65782e60e1571a3dcef8f5cc4fb106b003192eR2.

**Pull request closed without merging**
