### PR TITLE
Remove some unused functions

### PR DESCRIPTION
**Pull request by thockin**
We really should have a tool that check for this on internal (unsupported for external users, not staging/...) pkgs.

I found these by accident - I guarantee there are more.

/kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
why the linter `unused` is not flagging them?

https://github.com/kubernetes/kubernetes/blob/ea219476413794c05c857067ac5e32af11dc04a0/.golangci.yaml#L28


it seems there is a private copy here

https://github.com/kubernetes/kubernetes/blob/ea219476413794c05c857067ac5e32af11dc04a0/staging/src/k8s.io/component-helpers/scheduling/corev1/nodeaffinity/nodeaffinity.go#L203-L205

**Comment by aojea** [comment]
/lgtm

double checked 
```sh
$ grep -r NodeSelectorRequirementsAsSelector
pkg/apis/core/helper/helpers_test.go:func TestNodeSelectorRequirementsAsSelector(t *testing.T) {
pkg/apis/core/helper/helpers_test.go:           out, err := NodeSelectorRequirementsAsSelector(tc.in)
pkg/apis/core/helper/helpers.go:// NodeSelectorRequirementsAsSelector converts the []NodeSelectorRequirement core type into a struct that implements
pkg/apis/core/helper/helpers.go:func NodeSelectorRequirementsAsSelector(nsm []core.NodeSelectorRequirement) (labels.Selector, error) {
staging/src/k8s.io/component-helpers/scheduling/corev1/nodeaffinity/nodeaffinity_test.go:func TestNodeSelectorRequirementsAsSelector(t *testing.T) {
$ grep -r NodeSelectorRequirementsAsFieldSelector
pkg/apis/core/helper/helpers.go:// NodeSelectorRequirementsAsFieldSelector converts the []NodeSelectorRequirement core type into a struct that implements
pkg/apis/core/helper/helpers.go:func NodeSelectorRequirementsAsFieldSelector(nsm []core.NodeSelectorRequirement) (fields.Selector, error) {
```

**Comment by Abirdcfly** [comment]
Let me try to explain, I'm not very familiar with https://github.com/dominikh/go-tools, **please correct me if I'm wrong.**
</br></br>
> why the linter `unused` is not flagging them?

Because this pr deleted function is an exported function.

The linter `unused` uses internally is https://github.com/dominikh/go-tools/blob/master/unused/unused.go, It has some internal rules, such as treating the exported functions as having used, see https://github.com/dominikh/go-tools/blob/14865dd2a6230e8794e7a91ddcab515999bd50c6/unused/unused.go#L48-L154 for full description.
</br></br>

> it seems there is a private copy here

There is something not quite the same, at least one more function parameter in private copy.
</br></br>    



> We really should have a tool that check for this on internal (unsupported for external users, not staging/...) pkgs.

Through my quick search, there doesn't seem to be such a tool readily available at the moment.

BTW, are we sure we don't guarantee the compatibility of the exported functions in the non-staging folder?

**Comment by thockin** [comment]
non-staging is effectively internal and we DO NOT make API guarantees there.  We just can't.

**Comment by thockin** [comment]
It would be nice to have a tool that found "likely candidates" and let humans verify later.

**Pull request merged**
