### PR TITLE
Build conformance image when building via `cross` or `cross-in-a-container`

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind regression

#### What this PR does / why we need it:
This enables building the conformance image when running `make
cross-in-a-container`, which is being used by the release engineering
tooling.
#### Which issue(s) this PR fixes:

Fixes #
None
#### Special notes for your reviewer:
Refers to https://github.com/kubernetes/kubernetes/pull/99386
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by BenTheElder** [comment]
/lgtm
/approve
😔

**Comment by BenTheElder** [comment]
/retitle Build conformance image when building via `cross` or `cross-in-a-container`
/retest

**Pull request merged**
