### PR TITLE
Remove the kubeadm `--skip-preflight-checks` flag

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
As per deprecation policy, it's ok to remove this flag. (two releases: deprecated in 1.9 and removed in 1.11)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
The flag `--skip-preflight-checks` of kubeadm has been removed. Please use `--ignore-preflight-errors` instead.
```

### CODE REVIEW

**Review by timothysc — CHANGES_REQUESTED** [review]
@xiangpengzhao - definitely needs a release-note.  

I'm not aware of the history here, is there an issue too track. 

/cc @kubernetes/sig-cluster-lifecycle-pr-reviews 
/assign @timothysc

**Comment by xiangpengzhao** [comment]
>Rule #5a: CLI elements of user-facing components (e.g. kubectl) must function after their announced deprecation for no less than:
>
>GA: 1 year or 2 releases (whichever is longer)
Beta: 3 months or 1 release (whichever is longer)
Alpha: 0 releases

>Rule #5b: CLI elements of admin-facing components (e.g. kubelet) must function after their announced deprecation for no less than:
>
>GA: 6 months or 1 release (whichever is longer)
Beta: 3 months or 1 release (whichever is longer)
Alpha: 0 releases

Seems like I misunderstood the deprecation policy. I thought kubeadm flag deprecation fixes `Rule #5b GA`. Maybe it  should fix `Rule #5a GA`? Or `Rule #5a Beta` ? If it's the latter one, it's okay to remove this flag now.

**Comment by timothysc** [comment]
I think it's 5b - Beta, which means it's ok, but I definitely want a release note, please.

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve 

@xiangpengzhao - We may also need to update some docs on this change.

**Comment by xiangpengzhao** [comment]
@timothysc updated. PTAL. Thanks!

**Comment by neolit123** [comment]
@xiangpengzhao 
hi, thanks for the update!
`govet` reports one extra argument for `NewValidJoin`.

**Comment by neolit123** [comment]
/lgtm
@luxas @timothysc for approval.

the CLI docs change about this at `k/website` will be auto generated when 1.12 is released.
in terms of existing notes about `skip-preflight-checks` at `website` i cannot find any, although the search query there hasn't been working properly the past week due to indexing problems.

**Comment by xiangpengzhao** [comment]
Thanks @neolit123 !

**Pull request merged**
