### PR TITLE
remove redundant param in e2e_node/remote

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

* remove redundant param in e2e_node/remote/remote.go
* fix a small typo

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by yujuhong** [comment]
@k8s-bot ok to test

**Comment by dixudx** [comment]
@dims @tallclair @yujuhong Need your `/approve no-issue`.

**Comment by dixudx** [comment]
@tallclair Thanks so much.

**Comment by dixudx** [comment]
@yujuhong Thanks so much.

**Pull request merged**
