### PR TITLE
godep-save.sh: add workaround and more instructions

### PR DESCRIPTION
**Pull request by sttts**
Fixes https://github.com/kubernetes/kubernetes/issues/48593, hit again in https://github.com/kubernetes/kubernetes/pull/47232#issuecomment-314025645.

### CODE REVIEW

**Review by gyliu513 — COMMENTED** [review]
/lgtm

**Comment by gyliu513** [comment]
Did some test with https://github.com/kubernetes/kubernetes/pull/47232 and it works well, thanks @sttts

**Comment by cblecker** [comment]
I still don't love the rm -rf, but with how specific the path is I'm sure it'll be fine. Motivation for me to get all of these into containers once #46193 is merged with all the ground work.

**Pull request merged**
