### PR TITLE
Fixed e2e test flake - ClusterDns - should create pod that uses dns

### LINKED ISSUE #45915: Failure cluster [895633...] failed 48 builds, 2 jobs, and 1 tests over 1 days
##### Error text:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/example_cluster_dns.go:153
Expected error:
    <*errors.errorString | 0xc4202f9950>: {
        s: "Failed to find \"Hello World!\", last result: \"Traceback (most recent call last):\n  File \"client.py\", line 46, in <module>\n    Main()\n  File \"client.py\", line 41, in Main\n    CheckServiceAddress(args.address)\n  File \"client.py\", line 26, in CheckServiceAddress\n    service_address = socket.gethostbyname(hostname)\nsocket.gaierror: [Errno -2] Name or service not known\n\"",
    }
    Failed to find "Hello World!", last result: "Traceback (most recent call last):
      File "client.py", line 46, in <module>
        Main()
      File "client.py", line 41, in Main
        CheckServiceAddress(args.address)
      File "client.py", line 26, in CheckServiceAddress
        service_address = socket.gethostbyname(hostname)
    socket.gaierror: [Errno -2] Name or service not known
    "
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/example_cluster_dns.go:151
```
##### Failure cluster statistics:
1 tests failed,    2 jobs failed,    48 builds failed.
Failure stats cover 1 day time range '15 May 2017 20:02 UTC' to '16 May 2017 20:02 UTC'.
##### Top failed tests by jobs failed:

| Test Name | Jobs Failed |
| --- | --- |
| [k8s.io] ClusterDns [Feature:Example] should create pod that uses dns | 2 |

##### Top failed jobs by builds failed:

| Job Name | Builds Failed | Latest Failure |
| --- | --- | --- |
| ci-kubernetes-e2e-gce-examples | 25 | [16 May 2017 18:58 UTC](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-examples/5826) |
| ci-kubernetes-e2e-gci-gce-examples | 23 | [16 May 2017 18:21 UTC](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-examples/5116) |

<details><summary>Rationale for assignments:</summary>

| Assignee or SIG area | Owns test(s) |
| --- | --- |
| sttts | [k8s.io] ClusterDns [Feature:Example] should create pod that uses dns |
| sig/network | [k8s.io] ClusterDns [Feature:Example] should create pod that uses dns |

</details><br>

[Current Status](https://go.k8s.io/triage#8956334f660a34c16bf6)

### PR DESCRIPTION
**Pull request by prateekgogia**
**What this PR does / why we need it**:
String replaced in this test for example pod yaml (dns-frontend-pod.yaml) file is incorrect.

**Which issue this PR fixes** :
fixes #45915

### CODE REVIEW

**Comment by caseydavenport** [comment]
@k8s-bot ok to test

**Comment by caseydavenport** [comment]
Thanks @prateekgogia! This lgtm. 

/lgtm

**Comment by fejta** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
ref https://github.com/kubernetes/test-infra/pull/2931

**Comment by fejta** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this
ref: kubernetes/test-infra#2932

**Comment by caseydavenport** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by prateekgogia** [comment]
@bowei ping

**Comment by caseydavenport** [comment]
@freehan @dchen1107 can we get this test fix added to v1.7?

**Comment by bowei** [comment]
yes, looks ok for 1.7

**Pull request merged**
