### PR TITLE
[kubeadm] Bump kube-dns to 1.14.8

### PR DESCRIPTION
**Pull request by MrHohn**
**What this PR does / why we need it**:
Bump kube-dns to 1.14.8 for kubeadm. Ref https://github.com/kubernetes/kubernetes/pull/57918.

cc @rramkumar1 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #NONE

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
/lgtm
/test pull-kubernetes-e2e-kubeadm-gce
^^ I'm not sure why this didn't run on change (cc: @luxas @BenTheElder)

/assign @krousey 
for approval

**Comment by cblecker** [comment]
Oh nvm. I see skip report is on for that test. I'm guessing it was broken at some point? It appears to be passing for this PR though:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/58013/pull-kubernetes-e2e-kubeadm-gce/9974/
https://k8s-gubernator.appspot.com/pr/58013

**Review by fabriziopandini — APPROVED** [review]
/lgtm

**Comment by krousey** [comment]
I would think 1.9.0 and 1.9.1 clusters would still be at the previous version. This seems to bump all the 1.9.x versions to the newer kubedns version.

**Comment by MrHohn** [comment]
> I would think 1.9.0 and 1.9.1 clusters would still be at the previous version. This seems to bump all the 1.9.x versions to the newer kubedns version.

Didn't find a precedent at a quick glance. Though I could make the change if that is the right way to handle this.

**Comment by fabriziopandini** [comment]
> I would think 1.9.0 and 1.9.1 clusters would still be at the previous version. This seems to bump all the 1.9.x versions to the newer kubedns version.

Are there any known issue in running 1.9 cluster with kube-dns 1.14.8?

**Comment by MrHohn** [comment]
> Are there any known issue in running 1.9 cluster with kube-dns 1.14.8?

Not that I know of. Most of the changes made in kube-dns 1.14.8 were about Prometheus metrics.

**Comment by MrHohn** [comment]
@krousey @fabriziopandini Any update (should we be handling multiple versions)? We'd like to get this in ASAP so that the cherrypick (https://github.com/kubernetes/kubernetes/pull/58044) can get into the next 1.9 patch release.

**Comment by MrHohn** [comment]
>  I would think 1.9.0 and 1.9.1 clusters would still be at the previous version. This seems to bump all the 1.9.x versions to the newer kubedns version.

Added a second commit for this, @krousey @fabriziopandini PTAL and let me know which one to keep, thanks!

**Comment by fabriziopandini** [comment]
@MrHohn sorry but I missed at my first pass I missed the fact that your intention is to cherry pick this in 1.9.2.
However, considering the very short timeframe for detecting problems, I would like to involve also @roberthbailey @Luxas and @timothysc (or if you prefer we can discuss point this in the next sig cluster lifecycle agenda)

**Comment by timothysc** [comment]
We don't typically bump in minor versions... Why would we not wait till 1.10?

**Comment by MrHohn** [comment]
> We don't typically bump in minor versions... Why would we not wait till 1.10?

Actually, that sounds good. Would the slightly diverged kube-dns versions between kubeadm and release-branch be a concern?

**Comment by timothysc** [comment]
> Would the slightly diverged kube-dns versions between kubeadm and release-branch be a concern? 

I don't think so, b/c kubeadm selects it's version it deploys.

**Comment by MrHohn** [comment]
Ack, removed the minor versions logic. This PR is now targeting 1.10.

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Pull request merged**
