### PR TITLE
Promote apiserver.config.k8s.io/v1, kind=AdmissionConfiguration

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

* This promotes `apiserver.config.k8s.io/v1alpha1, kind=AdmissionConfiguration` to `apiserver.config.k8s.io/v1, kind=AdmissionConfiguration` with no schema changes. This was added in v1.6.0 and has been in use with no changes since then.
* Docs update in https://github.com/kubernetes/website/pull/17548

There are efforts in progress to graduate individual admission configurations (like resourcequota), and those require plumbing information through this config type.

**Does this PR introduce a user-facing change?**:
```release-note
kube-apiserver: The `AdmissionConfiguration` type accepted by `--admission-control-config-file` has been promoted to `apiserver.config.k8s.io/v1` with no schema changes.
```

/sig api-machinery
/cc @deads2k @derekwaynecarr 
fyi @ahg-g @ravisantoshgudimetla

### CODE REVIEW

**Comment by liggitt** [comment]
/priority important-soon

related to https://github.com/kubernetes/kubernetes/pull/76310

**Review by ravisantoshgudimetla — APPROVED** [review]
/lgtm

/hold

for @deads2k to review

**Comment by liggitt** [comment]
the pull-kubernetes-node-e2e-containerd failure is known, not a flake, non-blocking, and being worked on - https://github.com/kubernetes/kubernetes/issues/85040

**Comment by ahg-g** [comment]
> the pull-kubernetes-node-e2e-containerd failure is known, not a flake, non-blocking, and being worked on - #85040

This was failing since yesterday, more than few PRs get merged since this is started to fail,  retesting few times actually works.

/test pull-kubernetes-node-e2e-containerd

**Pull request merged**
