### PR TITLE
fix the timeline for CRD v1beta1 removal

### LINKED ISSUE #92110: What will happen to CRD v1beta1?
The following code snippet is very confusing:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go#L377-L383

```
// +k8s:prerelease-lifecycle-gen:introduced=1.7
// +k8s:prerelease-lifecycle-gen:deprecated=1.19
// +k8s:prerelease-lifecycle-gen:replacement=apiextensions.k8s.io,v1,CustomResourceDefinition

// CustomResourceDefinition represents a resource that should be exposed on the API server.  Its name MUST be in the format
// <.spec.name>.<.spec.group>.
// Deprecated in v1.16, planned for removal in v1.19. Use apiextensions.k8s.io/v1 CustomResourceDefinition instead.
```

Is v1beta1 deprecated in 1.16 or 1.19? Is it to be removed in 1.19 or 1.22?

Please clarify the exact versions so the many users of CRD v1beta1 APIs know what to do.

### PR DESCRIPTION
**Pull request by deads2k**
fixes https://github.com/kubernetes/kubernetes/issues/92110

/kind bug
/priority important-soon
@kubernetes/sig-api-machinery-api-reviews 

```release-note
NONE
```

/assign @liggitt

### CODE REVIEW

**Comment by cbandy** [comment]
Should `CustomResourceDefinitionList` get this same change?

https://github.com/kubernetes/kubernetes/blob/3a0b683c0181ef0f99b07677c9aadc15a3619c5c/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go#L408-L410

versus

https://github.com/kubernetes/kubernetes/blob/3a0b683c0181ef0f99b07677c9aadc15a3619c5c/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go#L388-L391

**Comment by liggitt** [comment]
Yes

**Pull request merged**
