### PR TITLE
Fix non-ascii characters in pkg/kubelet/qos/doc.go

### PR DESCRIPTION
**Pull request by YuikoTakada**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
ix non-ascii characters which are written accidentally.

**Which issue(s) this PR fixes**:
Ref #87679

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

**Comment by oomichi** [comment]
really flaky..

/retest

**Pull request merged**
