### PR TITLE
update default storageclass annotation

### PR DESCRIPTION
**Pull request by wackxu**
/assign @jsafrane @msau42 
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by saad-ali** [comment]
We need to be careful here and not break backwards compatibility. If we roll this out, clusters that upgrade may no longer function as expected.

The removal of beta annotations (for 1st class fields) has caused major pain in the past, so we need to try to treat annotations as API.

I suggest supporting both old and new annotation until we are confident.

**Comment by msau42** [comment]
@saad-ali this is just updating the addons to use the GA annotation. It's not removing support for the beta annotation (which we cannot remove according to the new deprecation policy)

**Comment by saad-ali** [comment]
> @saad-ali this is just updating the addons to use the GA annotation. It's not removing support for the beta annotation (which we cannot remove according to the new deprecation policy)

Ah, ok. In that case

/lgtm
/approve

**Comment by msau42** [comment]
This is being addressed by https://github.com/kubernetes/kubernetes/pull/68345

**Pull request closed without merging**
