### PR TITLE
Moved e2e/manifests to e2e test framework

### PR DESCRIPTION
**Pull request by alejandrox1**
The functionality included in the e2e/manifests is useful for writing
e2e tests and will be a good addition to the test framework as a
sub-package.

Signed-off-by: alejandrox1 <alarcj137@gmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Move the test/e2e/manifest package to inside of the e2e test framework to improve framework features and remove test/e2e/manifest as a dependency external to the framework. 

**Which issue(s) this PR fixes**:

xref: #74352 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by alejandrox1** [comment]
/hold
for reviews

**Comment by alejandrox1** [comment]
/assign @oomichi @tanjunchen @neolit123 
in context of https://github.com/kubernetes/kubernetes/pull/89456

**Review by neolit123 — COMMENTED** [review]
> Move the test/e2e/manifest package to inside of the e2e test framework to improve framework features and remove test/e2e/manifest as a dependency external to the framework.

SGTM.

**Comment by tanjunchen** [comment]
> > Move the test/e2e/manifest package to inside of the e2e test framework to improve framework features and remove test/e2e/manifest as a dependency external to the framework.
> 
> SGTM.

+1

**Review by tanjunchen — COMMENTED** [review]
Is there no move code for this pr?
/test/e2e/manifest -> /test/e2e/framework/manifest

**Comment by alejandrox1** [comment]
> Is there no move code for this pr?
> /test/e2e/manifest -> /test/e2e/framework/manifest

If you check the files you'll see
```
File renamed without changes.
```

I just did a `git mv manifest/ framework/`.

**Comment by tanjunchen** [comment]
Thanks , I see .

**Comment by oomichi** [comment]
Thanks for doing this. This makes e2e test code more clean.

/lgtm

**Pull request merged**
