### PR TITLE
Add 'ProviderID' to the output of kubectl describe node....

### PR DESCRIPTION
**Pull request by kkmsft**
**What this PR does / why we need it**:
This PR adds displaying 'ProviderID' field in the kubectl  describe node.. command output.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by krmayankk** [comment]
@kkmsft can you add a sample output of what this looks like and help us understand what ProviderID means ?

**Comment by kkmsft** [comment]
@krmayankk

> @kkmsft can you add a sample output of what this looks like and help us understand what ProviderID means ?

The ProviderID comes from the underlying cloud provider. For example the azure ACS nodes with 1.8.0 have the following as the ProviderID

./kubectl describe nodes  | grep ProviderID
ProviderID:                  azure://<redacted guid which is the vmId of the underlying vm>

**Pull request merged**
