### PR TITLE
tests: Ports volume unit tests to Windows

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind failing-test

/sig testing
/sig windows
/priority important-soon
/milestone v1.25

#### What this PR does / why we need it:

Ports the metrics_du unit tests to Windows.
Ports the hostutil unit tests to Windows.

#### Which issue(s) this PR fixes:

Related: https://github.com/kubernetes/kubernetes/issues/51540

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by encodeflush** [comment]
Hi @claudiubelu
Bug triage team here!
It looks like this PR has the pending review.
Just checking in to see if this is still on track for K8s 1.25.

**Comment by claudiubelu** [comment]
> Hi @claudiubelu Bug triage team here! It looks like this PR has the pending review. Just checking in to see if this is still on track for K8s 1.25.

Yep, it is. Just waiting for reviews.

**Comment by claudiubelu** [comment]
FYI: This PR has test-only changes. This PR has been included in this PR https://github.com/kubernetes/kubernetes/pull/110981, in which we've ran the ``pull-ci-kubernetes-unit-windows`` job, in which we can see that these tests now pass.

**Comment by helayoty** [comment]
@claudiubelu 👋 the release 1.25 bug triage Lead. I'm reaching out to see the status of this PR and if we are still targeting the current release.

@jingxu97 @chrishenzie will you be able to review this PR? is it a release blocker?

**Comment by dims** [comment]
way past test freeze
/milestone clear

**Comment by jsafrane** [comment]
Sorry for a long wait! Only very few (if any) storage folks have experience with Windows. I am not one of them, but I can see the Linux code is not worse :-).

/lgtm
/approve

**Pull request merged**
