### PR TITLE
duplicate kube-apiserver to federated-apiserver

### PR DESCRIPTION
**Pull request by jianhuiz**
duplicate the kube-apiserver source code to ube-apiserver and update references
cluster specific api objects will be in separate PRs
#19313,  #21190

https://github.com/kubernetes/kubernetes/pull/21190#issuecomment-201551176
@nikhiljindal

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Am curious if you tried using the code as in https://github.com/kubernetes/kubernetes/blob/master/examples/apiserver/apiserver.go?

Ref https://github.com/kubernetes/kubernetes/pull/21190#issuecomment-201569506

**Comment by jianhuiz** [comment]
@nikhiljindal I'm aware of that piece of code, and I wouldn't mind starting a brand new ube-apiserver. I guess I didn't explain my self clearly, the problem is that ube-apiserver is meant to be compatible with kube-apiserver, which means in the end there has to be some kind of reuse/sync of these two apiservers. I prefer coping kube-apiserver for now is that I can focus on the api objects instead of getting distracted of all the details such as the options/configs of the apiserver it self.

**Comment by nikhiljindal** [comment]
ok thats reasonable. I can work on reducing the code duplication while you can work on ubernetes API objects.
Thanks for moving the code to federation directory.

ube-apiserver doesnt look like the right name.
Maybe rename to just apiserver since it is already under federation directory? federated-apiserver will be long.

@kubernetes/sig-api-machinery @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by jianhuiz** [comment]
Thanks @nikhiljindal.
I agree that federated-apiserver will be long, what about fed-apiserver, and fed-xxx for other components?
BTW, it appears that the kube-api had changed just yesterday, I'll merge those changes and update the PR.

**Comment by smarterclayton** [comment]
In /cmd/ by convention in Go we name the directory the expected binary
name.  That's the only place expected to have long names - shorter
names are fine in other places.

Is federated-apiserver really that long?  Tab completion should make
it a non-issue in many environments.

**Comment by lavalamp** [comment]
I would call it `uber-apiserver` personally. I prefer "federated-apiserver" to "fed-apiserver" (we use abbreviations very rarely).

**Comment by nikhiljindal** [comment]
If long name is not a concern than federated-apiserver seems best.

**Comment by jianhuiz** [comment]
it was `uber-apiserver` in the very first PR however suggested to be changed to `ube-apiserver` because of `kube` `ube` consistency.
`federated-apiserver` seemed long to me personally because I find the long `federated-` prefix distracting (after all an apiserver it is) and slows me down when reading and looking for it.
however as long as you are all agreed to use `federated-apiserver`, I'll update the PR soon.

**Comment by smarterclayton** [comment]
Since we call the other binaries kube-* I'm not morally opposed to
uber-*.  But then, I'd probably rename kube-apiserver if it could.

**Comment by quinton-hoole** [comment]
Since we're voting on names :-) I'm generally more in favor of semantic rather than brand names in code, because it reduces cognitive overhead.  So "federated..." in preference to "ubernetes..." or "...ube".  Regarding the name length concern, it seems that in most cases this can be addressed by importing it as a shorter name (e.g. "fed") where desired.

So to cast my vote, I'm with Nikhil on "federated-apiserver".  But I don't feel strongly enough about it to veto some other majority view.

**Comment by nikhiljindal** [comment]
Thanks for renaming to federated-apiserver.
LGTM.

**Pull request merged**
