### PR TITLE
Enable RBAC by default in hack/local-up-cluster.sh

### LINKED ISSUE #49319: local-up-cluster.sh always fail with "Timed out waiting for apiserver"
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
#49072

**What happened**:

After this commit was introduced, local-up-cluster.sh always fail with "Timed out waiting for apiserver" error.

```
commit 413ab26df92c3da66bc6eb60c1d1105f6ac267fc
    use https to check healthz in hack/local-up-cluster.sh
```

I'm not sure the reason but the local-up-cluster.sh successfully start if I specify ENABLE_RBAC=true option to local-up-cluster.sh.

**What you expected to happen**:

The local-up-cluster.sh will successfully start without any additional options.

**How to reproduce it (as minimally and precisely as possible)**:
```
% hack/local-up-cluster.sh
```

### PR DESCRIPTION
**Pull request by mtanino**
**What this PR does / why we need it**:

Since hack/local-up-cluster.sh checks https API port after commit 413ab26df92c3da66bc6eb60c1d1105f6ac267fc, RBAC should be enabled by default to avoid TLS port access denied.

**Which issue this PR fixes** : Fixes #49319

**Special notes for your reviewer**:

@liggitt 

**Release note**:

```release-note
hack/local-up-cluster.sh now enables RBAC authorization by default
```

### CODE REVIEW

**Comment by liggitt** [comment]
I'm in favor of this change... it makes local-up-cluster more like our other CI/test environments

cc @kubernetes/sig-auth-pr-reviews

**Comment by deads2k** [comment]
> I'm in favor of this change... it makes local-up-cluster more like our other CI/test environments

Even better, it would fix `local-up-cluster.sh` for me. :)


lgtm

**Pull request merged**
