### PR TITLE
Revert "Refactor GCE wrapper library to allow execution from E2E test suite"

### PR DESCRIPTION
**Pull request by jszczepkowski**
Reverts kubernetes/kubernetes#17276

### CODE REVIEW

**Comment by jszczepkowski** [comment]
CC @saad-ali

**Comment by piosz** [comment]
LGTM

**Comment by piosz** [comment]
cc @ixdy

**Comment by jszczepkowski** [comment]
The original PR (#17276) caused failures of most of e2e tests, e.g.:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/9569/

**Pull request merged**
