### PR TITLE
WIP: discovery client hashes for APIGroup

### PR DESCRIPTION
**Pull request by kevindelgado**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Adds a `Hash` field to the `APIGroup` type and then modifies the discovery client to add save the hash for each groupversion when `ServerGroups` is called and sets the hash as a query param when getting the server resources for a given groupversion from discovery.

#### Which issue(s) this PR fixes:

Part of forthcoming discovery cache busting kep

#### Does this PR introduce a user-facing change?

```release-note
Adds a `Hash` field to the `APIGroup` type
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kevindelgado** [comment]
/assign @apelisse @Jefftree 

Testing feels a little light, let me know if there's any other cases I'm missing here at the unit test level.

**Comment by apelisse** [comment]
Still fine with it, thanks.

**Comment by apelisse** [comment]
Was this meant for master?

**Comment by kevindelgado** [comment]
> Was this meant for master?

Just to check if CI passes, closing now

**Pull request closed without merging**
