### PR TITLE
Automated cherry pick of #117705: Update kube-openapi to fix race

### PR DESCRIPTION
**Pull request by Jefftree**
Cherry pick of #117705 on release-1.27.

#117705: Update kube-openapi to fix race

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fixes a 1.27 regression causing a race condition serving OpenAPI content
```

### CODE REVIEW

**Comment by apelisse** [comment]
test failures seem unrelated
/lgtm
/approve

**Review by cpanato — APPROVED** [review]
from releng:
/lgtm

**Pull request merged**
