### PR TITLE
Jenkins: pin to v1.1.1 for trusty release tests

### PR DESCRIPTION
**Pull request by wonderfly**

### CODE REVIEW

**Comment by wonderfly** [comment]
@ixdy @andyzheng0831 Tested on internal Jenkins project.

**Comment by ixdy** [comment]
LGTM
ok to test

**Comment by andyzheng0831** [comment]
LGTM

**Comment by ixdy** [comment]
actually did you still want to pin to explicit 1.1.1? or to release/latest-1.1?

**Comment by andyzheng0831** [comment]
We want to pin to 1.1.1 release matching https://github.com/kubernetes/kubernetes/releases/tag/v1.1.1

**Comment by wonderfly** [comment]
@ixdy Re: "actually did you still want to pin to explicit 1.1.1? or to release/latest-1.1?", yes, we want to pin to a specific version, instead of a moving target. `release/latest-1.1` is going to change to 1.1.2, I believe, once 1.1.2 is out, and we don't want that surprise, yet.

**Pull request merged**
