### PR TITLE
Automated cherry pick of #107548: Fix topology hints test * It should check one Node in a zone

### PR DESCRIPTION
**Pull request by lzhecheng**
Cherry pick of #107548 on release-1.23.

#107548: Fix topology hints test * It should check one Node in a zone

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by lzhecheng** [comment]
PTAL @aojea

**Comment by lzhecheng** [comment]
Hello, do you time to review? Or could you please refer someone else? Our testing job is failing on this test.

**Comment by danwinship** [comment]
/assign @aojea @robscott
who reviewed the original

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Comment by robscott** [comment]
I'm not sure what our policy is on cherry picking test fixes, but as long as that's OK, I'm good with this cherry pick.

/lgtm

**Comment by aojea** [comment]
> I'm not sure what our policy is on cherry picking test fixes, but as long as that's OK, I'm good with this cherry pick.

test fixes are ok, but this is a beta feature in 1.23, backporting for betas require some extra justification

**Comment by lzhecheng** [comment]
Our CI are running against this testcase with k8s release-1.23 so the cherry-pick helps.

**Comment by aojea** [comment]
> Our CI are running against this testcase with k8s release-1.23 so the cherry-pick helps.

generally people has to carry on with cherry-picks on their forks for the patches that are not accepted upstream ... I suffer that daily :sweat_smile: 

You have to convince release-managers, not me :smile: , the change only affects a test but is a beta feature :shrug: 

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#what-kind-of-prs-are-good-for-cherry-picks

ping @kubernetes/release-managers

**Pull request closed without merging**
