### PR TITLE
Remove duplicated import and wrong alias name of api package

### LINKED ISSUE #48975: Remove duplicated import and wrong alias name of package k8s.io/api/core/v1
**Is this a BUG REPORT or FEATURE REQUEST?**: No

**What happened**:
Now the `k8s.io/kubernetes/pkg/api/v1` and `k8s.io/client-go/pkg/api/v1` has been consistent in `k8s.io/api/core/v1` by PR #44784.
There are 2 problems left:
* For the import `clientv1 "k8s.io/api/core/v1"` in some packages like [cmd/kube-proxy/app/server.go](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go#L33), the alias name `clientv1` is not correct as API v1 has been seperated from client-go.
* `k8s.io/api/core/v1` and `clientv1 "k8s.io/api/core/v1"` are duplicately imported in some packages like [pkg/kubelet/kubelet.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L39-L40)

**What you expected to happen**:
* Remove the duplicated import of package `k8s.io/api/core/v1`.
* Remove the alias name `clientv1` of the package `k8s.io/api/core/v1`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by supereagle**
**What this PR does / why we need it**:

**Which issue this PR fixes**: fixes #48975

**Special notes for your reviewer**:
/assign @caesarxuchao

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
I'm prioritizing https://github.com/kubernetes/kubernetes/pull/48231, which might fix some of the issues mentioned here, and might cause conflicts. That PR is more complex so I'd rather not asking the author to rebase ;)

**Comment by supereagle** [comment]
@caesarxuchao  It is OK, I will rebase this PR after #48231 merged.

**Comment by supereagle** [comment]
/assign @dchen1107 @janetkuo
for /approve

**Comment by caesarxuchao** [comment]
Thanks  @supereagle

**Comment by caesarxuchao** [comment]
@janetkuo @yujuhong could you help approve this PR? It only changes import line aliases.

**Comment by yujuhong** [comment]
@caesarxuchao it might be easier for you to just get a top-level owner approval...

**Comment by caesarxuchao** [comment]
Yes. Thanks.

**Comment by caesarxuchao** [comment]
@brendanburns could you help approve it? Thanks.

**Comment by supereagle** [comment]
@dchen1107  @janetkuo
/for approve

**Comment by caesarxuchao** [comment]
@supereagle could you rebase? Thanks.

**Comment by supereagle** [comment]
@caesarxuchao   Have rebased, PATL.

**Pull request merged**
