### PR TITLE
Automated cherry pick of #114261: Reduce load of Job integration test

### PR DESCRIPTION
**Pull request by alculquicondor**
Cherry pick of #114261 on release-1.25.

#114261: Reduce load of Job integration test

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by aojea** [comment]
/kind flake
/lgtm
/approve
/assign @liggitt 

ping @kubernetes/release-managers

**Comment by alculquicondor** [comment]
/hold
for successful runs on #114264

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
