### PR TITLE
EventTypeWarning replaces EventTypeNormal when failed

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:

it is similar to #44083 and #44378
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by FengyunPan** [comment]
Have you update your code?

**Comment by quinton-hoole** [comment]
@k8s-bot ok to test

**Comment by quinton-hoole** [comment]
Thanks @zhangxiaoyu-zidif and @FengyunPan !

/lgtm

**Pull request merged**
