### PR TITLE
Removed equivalence cache tests

### PR DESCRIPTION
**Pull request by akremsa**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it:**
According to the discussion here #79600, these tests should be removed because they are not useful for the current code-base.

**Does this PR introduce a user-facing change?:**
```release-note
NONE
```

/area conformance
/area test

@kubernetes/sig-architecture-pr-reviews
@kubernetes/cncf-conformance-wg
@kubernetes/sig-network-pr-reviews
@kubernetes/sig-scheduling-pr-reviews

### CODE REVIEW

**Comment by mgdevstack** [comment]
/ok-to-test
As there is no means to run effective E2E on `kind` cluster specific to  GCE and GKE providers.

**Comment by johnbelamaric** [comment]
This was discovered while trying to promote conformance tests but this isn't really a conformance PR. I also am not really the right one to approve these. So:

/remove-area conformance
/remove-sig architecture
/remove-sig network
/remove-sig testing
/priority important-longterm
/unassign
/assign @aleksandra-malinowska @k82cn

**Review by bsalamat — COMMENTED** [review]
/lgtm
/approve

**Comment by akremsa** [comment]
@aleksandra-malinowska  @bsalamat  Please, review this PR in order to save an effort on regular rebasing.

**Comment by akremsa** [comment]
@jszczepkowski  @wasylkowski  please review

**Comment by damemi** [comment]
bump, @akremsa could you please rebase this?

**Review by ravisantoshgudimetla — APPROVED** [review]
Thanks for the PR @akremsa 

/lgtm
/approve

**Review by soltysh — APPROVED** [review]
The autoscaling part of the test is only adding error check which was previously missing.
/approve

**Pull request merged**
