### PR TITLE
Make ServiceLoadBalancer a Feature test

### LINKED ISSUE #19552: Reclassify [Skipped] issues: ServiceLoadBalancer
@bprashanth You originally marked the "ServiceLoadBalancer [Skipped]" test `[Skipped]` in #14988 and, as far as I can tell, never sent a follow-up PR.

Can we expect this test to run in a standard suite, or does it need special treatment?  If you want to classify it for special treatment, we'll need to find somewhere to make sure it's running.  See #19505 for context.

Happy to answer any questions if anything doesn't make sense.

### PR DESCRIPTION
**Pull request by ikehz**
Closes #19552.

Do not merge until #19505 is merged.

### CODE REVIEW

**Comment by bprashanth** [comment]
thanks

**Comment by bprashanth** [comment]
Feel free to apply lgtm when dependencies have been resolved

**Comment by ihmccreery** [comment]
With #19505 in, this is ready for review.

**Comment by bprashanth** [comment]
What does it mean to be a feature test?

**Comment by ihmccreery** [comment]
> What does it mean to be a feature test?

https://github.com/kubernetes/kubernetes/blob/master/docs/devel/e2e-tests.md#kinds-of-tests

**Comment by bprashanth** [comment]
@k8s-bot test this please

**Comment by ihmccreery** [comment]
@k8s-bot test this again please

**Pull request merged**
