### PR TITLE
kubeadm: get rid of dependency on pkg/util/node

### PR DESCRIPTION
**Pull request by bart0sh**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Created local copy of GetHostname API to avoid dependency to pkg/util/node.

**Which issue(s) this PR fixes**:

Refs kubernetes/kubeadm#1600

```release-note
NONE
```

### CODE REVIEW

**Review by detiber — COMMENTED** [review]
Instead of making a copy of this, would it be better to move the shared method under a shared dependency like `k8s.io/utils`?

**Comment by neolit123** [comment]
> Instead of making a copy of this, would it be better to move the shared method under a shared dependency like k8s.io/utils?

it complicates things, but i agree because this function depends only on the go stdlib.

what is needed:
- a PR to the k8s.io/utils repo
- a top level approver to approve:
  - the vendor update in k/k
  - updated kubelet and other components to use k8s.io/utils/net for this

also depends if @bart0sh wants to go that route.

**Comment by detiber** [comment]
@neolit123 it would indeed complicate the PR, I think my biggest concern is that we rely on the behavior of this method being consistent with the Kubelet. I worry that if they have divergent behavior in the future that we might not catch it before a release and lead to hard to reproduce bugs.

**Comment by neolit123** [comment]
yes, definitely.

**Comment by yastij** [comment]
Agreed, this belongs to utils @andrewsykim and @dims can review the PR under k/utils

**Review by yastij — CHANGES_REQUESTED** [review]
@bart0sh - can you link the PR on k/utils once opened ? Thanks !

**Review by rosti — COMMENTED** [review]
Thanks for picking this up @bart0sh !
+1 on the idea for `k8s.io/utils/net`

**Comment by bart0sh** [comment]
> @bart0sh - can you link the PR on k/utils once opened ? Thanks !

Here you go: https://github.com/kubernetes/utils/pull/103

**Comment by bart0sh** [comment]
Updated this PR:
 - Added tests
 - used errors APIs

Please review. After rejection of [our attempt to move this API to k/utils](https://github.com/kubernetes/utils/pull/103) this is the only way we can get rid of dependency on pkg/util/node in my opinion.

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve
/hold cancel

for now the function in a common place is not being accepted.
refactors and consolidations can come in separate PRs.

**Pull request merged**
