### PR TITLE
hack/gofmt: allow go1.4

### PR DESCRIPTION
**Pull request by proppy**
Otherwise it is skipped with:

```
Unknown go version 'go', skipping gofmt.
```

### CODE REVIEW

**Comment by satnam6502** [comment]
LGTM

**Comment by satnam6502** [comment]
Perhaps futile, but I will wait for one green.

**Comment by proppy** [comment]
PTAL, fix some of the file that are simplified further with 1.4

**Comment by satnam6502** [comment]
Ah, good, thanks. Will wait for green.

**Comment by proppy** [comment]
Oups, actually scratch that. 

We want gofmt to be limited to 1.3 because we don't want to validate 1.4 only syntax that breaks the 1.3 build.

Sorry for the noise closing.

**Pull request closed without merging**
