### PR TITLE
Use "kubectl replace" in update-storage-objects.sh

### PR DESCRIPTION
**Pull request by gouyang**
Signed-off-by: Guohua Ouyang gouyang@redhat.com

### CODE REVIEW

**Comment by jszczepkowski** [comment]
LGTM

**Comment by lavalamp** [comment]
add to whitelist

**Comment by jszczepkowski** [comment]
@k8s-bot test this please

**Comment by quinton-hoole** [comment]
e2e test failure was due to #13534.  Retrying to trigger auto-merge by merge-bot.
@k8s-bot test this again please

**Comment by quinton-hoole** [comment]
Note: the e2e test should not be required, modulo bugs in the merge-bot.  But lets see what happens.

**Pull request merged**
