### PR TITLE
Automated cherry pick of #64957: set EnableHTTPSTrafficOnly in storageAccount creation

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #64957 on release-1.9.

#64957: set EnableHTTPSTrafficOnly in storageAccount creation

### CODE REVIEW

**Comment by mbohlool** [comment]
/hold

1.9 branch is frozen for the release.

**Comment by nikhita** [comment]
Closing and reopening to retrigger prow to remove the `do-not-merge/cherry-pick-not-approved` label.

/assign

**Comment by nikhita** [comment]
/unassign
/retest

The labels are fixed now. :+1:

**Comment by nikhita** [comment]
/assign @jdumars 
for approval

**Comment by nikhita** [comment]
Err...I'm not sure why retest is not working. Take 3.

/retest

**Pull request merged**
