### PR TITLE
Move adapter functions to their own packages

### PR DESCRIPTION
**Pull request by krousey**
This eliminates the last dependency the generated clients have on the unversioned client.

The first commit is in another PR. Ignore it.

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM, but please rebase first

**Comment by krousey** [comment]
Waiting on #22016 to go in to eliminate the first commit, then I'll rebase. Thanks for the LGTM.

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please github issue: #22991 22991

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please github issue: #22991

**Pull request merged**
