### PR TITLE
Add policy API to 1.4 clientset.

### PR DESCRIPTION
**Pull request by mml**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31638)

### CODE REVIEW

**Comment by caesarxuchao** [comment]
You need to add policy group into this file as well: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/clientset_generated/release_1_4/import_known_versions.go#L28

**Comment by mml** [comment]
@caesarxuchao I made that change, but it's still failing with the same message: `group policy has not been registered`

**Comment by mml** [comment]
@caesarxuchao PTAL

**Comment by mml** [comment]
Closing in favor of #31721.

**Pull request closed without merging**
