### PR TITLE
Automated cherry pick of #85920: Accept healthy instances in list of active instances

### PR DESCRIPTION
**Pull request by kishorj**
Cherry pick of #85920 on release-1.17.

#85920: Accept healthy instances in list of active instances

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by M00nF1sh** [comment]
c

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
