### PR TITLE
Make apply use the correct versioned obj

### PR DESCRIPTION
**Pull request by mengqiy**
Port #38982 to 1.4

cc: @pwittrock @liggitt @jessfraz

### CODE REVIEW

**Comment by pwittrock** [comment]
@liggitt Assigned to you since you reviewed the patch for 1.5

**Comment by liggitt** [comment]
can you pick the 2016 -> 2017 fix as well so we can get a green test run on this?

**Comment by liggitt** [comment]
@k8s-bot gci gke e2e test this

**Comment by liggitt** [comment]
pick LGTM

**Comment by jessfraz** [comment]
sweet ill just let https://github.com/kubernetes/kubernetes/pull/39437 get in then merge this one :)

**Comment by ymqytw** [comment]
I need to drop the 2nd commit after #39437 merged.

**Comment by liggitt** [comment]
@ymqytw you can go ahead and drop the commit... @jessfraz will rerun tests on this one after #39437 merged... sorry for the mixup

**Comment by ymqytw** [comment]
@liggitt Done.

**Comment by jessfraz** [comment]
@k8s-bot verify test this please

**Comment by ymqytw** [comment]
#39437 has been merged.
@k8s-bot test this

**Comment by jessfraz** [comment]
@k8s-bot node e2e test this

**Comment by jessfraz** [comment]
that is failing because of a flake so merging because all others green

**Pull request merged**
