### PR TITLE
fix label mismatching which broke e2e serial test

### LINKED ISSUE #78651: Failing test: [sig-storage] [Serial] Volume metrics should create metrics for total time taken in volume operations in P/V Controller
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce-serial

**Which test(s) are failing**:
[sig-storage] [Serial] Volume metrics should create metrics for total time taken in volume operations in P/V Controller

**Since when has it been failing**:
6/1

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-storage-kubernetes#gce-serial

**Reason for failure**:
Probably caused by
https://github.com/kubernetes/kubernetes/pull/78061

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by yuxiangqian**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
mismatched label broke e2e serial test
**Which issue(s) this PR fixes**:

Fixes #78651

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Comment by yuxiangqian** [comment]
test results:
[sig-storage] [Serial] Volume metrics 
  should create metrics for total time taken in volume operations in P/V Controller
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:249
[BeforeEach] [sig-storage] [Serial] Volume metrics
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:150
STEP: Creating a kubernetes client
STEP: Building a namespace api object, basename pv
STEP: Waiting for a default service account to be provisioned in namespace
[BeforeEach] [sig-storage] [Serial] Volume metrics
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:53
Jun  3 23:30:12.616: INFO: Default storage class: "standard"
[It] should create metrics for total time taken in volume operations in P/V Controller
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:249
Jun  3 23:30:30.988: INFO: Looking for sample in metric "volume_operation_total_seconds_count"
Jun  3 23:30:30.988: INFO: Found sample "volume_operation_total_seconds_count{operation_name=\"delete\", plugin_name=\"kubernetes.io/gce-pd\"} => 4 @[0]"
Jun  3 23:30:30.988: INFO: Found sample "volume_operation_total_seconds_count{operation_name=\"provision\", plugin_name=\"kubernetes.io/gce-pd\"} => 5 @[0]"
Jun  3 23:30:30.988: INFO: Deleting pod "pv-311"/"pvc-tester-2pjfs"
Jun  3 23:30:30.988: INFO: Deleting pod "pvc-tester-2pjfs" in namespace "pv-311"
Jun  3 23:30:31.033: INFO: Wait up to 5m0s for pod "pvc-tester-2pjfs" to be fully deleted
[AfterEach] [sig-storage] [Serial] Volume metrics
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:151
Jun  3 23:30:43.114: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
STEP: Destroying namespace "pv-311" for this suite.
Jun  3 23:30:57.285: INFO: Waiting up to 30s for server preferred namespaced resources to be successfully discovered
Jun  3 23:30:58.842: INFO: namespace pv-311 deletion completed in 15.687171313s
[AfterEach] [sig-storage] [Serial] Volume metrics
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:76
Jun  3 23:30:58.882: INFO: Failed to get pvc pv-311/pvc-c56j7: persistentvolumeclaims "pvc-c56j7" not found

**Comment by saad-ali** [comment]
/milestone v1.15
bug fix

**Comment by alejandrox1** [comment]
Affecting release blocking ci so i'll scale up the priority for tide
/priority critical-important

**Pull request merged**
