### PR TITLE
Pod sync result

### PR DESCRIPTION
**Pull request by oulinbao**
**What this PR does / why we need it**:
change return type to PodSyncResult for KillPod

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by cblecker** [comment]
Please rebase and remove all merge commits. This PR will not be mergeable with those (ref: https://github.com/kubernetes/kubernetes/pull/56366/commits)

**Comment by oulinbao** [comment]
@cblecker, thanks for your reminder. I have rebased the commit records.

**Comment by oulinbao** [comment]
The unit testcases in my mac runs ok.
/retest

**Comment by mtaufen** [comment]
/assign @Random-Liu 
since it was his todo item.

**Pull request closed without merging**
