### PR TITLE
Fix make WHAT="target1 target2 .. " failure.

### LINKED ISSUE #75669: [Bug] make WHAT="targets1 target2 ... " fails.
**What happened**:

Trying to build tests with command:

`make WHAT="./test/e2e/e2e.test ./vendor/github.com/onsi/ginkgo/ginkgo"`

fails with error:

```
+++ [0325 16:04:54] Building go targets for darwin/amd64:
    ./test/e2e/e2e.test
    ./vendor/github.com/onsi/ginkgo/ginkgo
can't load package: package k8s.io/kubernetes: no Go files in /Users/atuvenie/workspace/go_dev/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes
!!! [0325 16:04:55] Call tree:
!!! [0325 16:04:55]  1: /Users/atuvenie/workspace/go_dev/src/k8s.io/kubernetes/hack/lib/golang.sh:629 kube::golang::build_some_binaries(...)
!!! [0325 16:04:55]  2: /Users/atuvenie/workspace/go_dev/src/k8s.io/kubernetes/hack/lib/golang.sh:764 kube::golang::build_binaries_for_platform(...)
!!! [0325 16:04:55]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
```

**Anything else we need to know?**:

Debugging the issue, I've noticed that the `go install ` command in `kube::golang::build_some_binaries(...)` gets called with an extra `' '`:

`go install -gcflags ' -trimpath=/Users/atuvenie/workspace/go_dev/src/k8s.io/kubernetes' -asmflags -trimpath=/Users/atuvenie/workspace/go_dev/src/k8s.io/kubernetes -ldflags ' -s -w -X '\''k8s.io/kubernetes/pkg/version.buildDate=2019-03-25T14:08:55Z'\'' -X '\''k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/version.buildDate=2019-03-25T14:08:55Z'\'' -X '\''k8s.io/kubernetes/pkg/version.gitCommit=231e372d0cb16ffba8c8d6b04530dbb033ed23a2'\'' -X '\''k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/version.gitCommit=231e372d0cb16ffba8c8d6b04530dbb033ed23a2'\'' -X '\''k8s.io/kubernetes/pkg/version.gitTreeState=dirty'\'' -X '\''k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/version.gitTreeState=dirty'\'' -X '\''k8s.io/kubernetes/pkg/version.gitVersion=v1.14.0-alpha.2.2362+231e372d0cb16f-dirty'\'' -X '\''k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/version.gitVersion=v1.14.0-alpha.2.2362+231e372d0cb16f-dirty'\'' -X '\''k8s.io/kubernetes/pkg/version.gitMajor=1'\'' -X '\''k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/version.gitMajor=1'\'' -X '\''k8s.io/kubernetes/pkg/version.gitMinor=14+'\'' -X '\''k8s.io/kubernetes/vendor/k8s.io/client-go/pkg/version.gitMinor=14+'\''' '' k8s.io/kubernetes/./vendor/github.com/onsi/ginkgo/ginkgo`

This is because here: https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh#L721 , binaries should be declared as array.

**Environment**:
- Kubernetes version: master 
- OS (e.g: `cat /etc/os-release`): Darwin

### PR DESCRIPTION
**Pull request by adelina-t**
Fixes: https://github.com/kubernetes/kubernetes/issues/75669

**What type of PR is this?**

/kind bug

**Which issue(s) this PR fixes**:

Fixes #75669

### CODE REVIEW

**Comment by spiffxp** [comment]
this seems unrelated but also not a flake?
```
Your Godeps.json is different:
--- Godeps/Godeps.json	2019-03-25 14:28:22.403464074 +0000
+++ /tmp/gopath.u6lmzR/src/k8s.io/kubernetes/Godeps/Godeps.json	2019-03-25 14:41:59.433542041 +0000
@@ -1758,12 +1758,12 @@
 		},
 		{
 			"ImportPath": "github.com/go-openapi/jsonpointer",
-			"Comment": "v0.18.0",
+			"Comment": "v0.19.0",
 			"Rev": "ef5f0afec364d3b9396b7b77b43dbe26bf1f8004"
 		},
 		{
 			"ImportPath": "github.com/go-openapi/jsonreference",
-			"Comment": "v0.18.0",
+			"Comment": "v0.19.0",
 			"Rev": "8483a886a90412cd6858df4ea3483dce9c8e35a3"
 		},
 		{
Godeps Verify failed.
```

**Comment by adelina-t** [comment]
> this seems unrelated but also not a flake?

Job seems to be failing for some time: https://prow.k8s.io/job-history/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-godeps . 
Looking into it, maybe I can lend a hand :)

**Comment by spiffxp** [comment]
ref: https://github.com/kubernetes/kubernetes/issues/75653 for the godep issue

**Comment by adelina-t** [comment]
@spiffxp  @lavalamp @sttts can you take a look. Tests seem to be passing now.

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Comment by BenTheElder** [comment]
Possibly needs rebase.

**Comment by BenTheElder** [comment]
should be fixed in https://github.com/kubernetes/kubernetes/pull/75668

**Comment by adelina-t** [comment]
> should be fixed in #75668

Yep. It's fixed there and it got in first. Will close this PR.

**Comment by adelina-t** [comment]
Close, PR #75668 got in first.

/close

**Pull request closed without merging**
