### PR TITLE
Tweak explain messages and abstract client

### PR DESCRIPTION
**Pull request by smarterclayton**
Some minor cleanup as we start to expose this in OpenShift

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@smarterclayton - it seems that it needs a rebase:

06:42:07 # k8s.io/kubernetes/pkg/kubectl
06:42:07 _output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/explain.go:36: undefined: unversioned

**Comment by smarterclayton** [comment]
Adding a command test for explain, which we did not have before

**Comment by smarterclayton** [comment]
Trivial rebase with test added, reapplying

**Comment by ixdy** [comment]
@k8s-bot e2e test this again please

**Comment by smarterclayton** [comment]
ok to test

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Pull request merged**
