### PR TITLE
Nodefs becomes imagefs on GCI

### PR DESCRIPTION
**Pull request by vishh**
Kubelet cannot identify rootfs correctly
For #33444

``` release-note
Enforce Disk based pod eviction with GCI base image in Kubelet
```

Signed-off-by: Vishnu kannan vishnuk@google.com

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33520)

### CODE REVIEW

**Comment by vishh** [comment]
P2 since it needs to be cherry-picked into 1.4 branch soon for stabilizing GCI tests.

**Comment by dchen1107** [comment]
Checked the new configuration with @dashpole's newly introduced out-of-inode test, and it works. 

LGTM

**Comment by jessfraz** [comment]
@vishh is this something that needs to be in 1.4.1?

**Comment by vishh** [comment]
@jessfraz Ideally yes. I will try to get the tests to pass tomorrow.

**Comment by jessfraz** [comment]
Thanks!!

**Comment by vishh** [comment]
@k8s-bot test node e2e github issue #IGNORE

**Comment by vishh** [comment]
@k8s-bot test gke e2e github issue #IGNORE

**Comment by vishh** [comment]
@k8s-bot node e2e test this github issue #IGNORE

**Comment by vishh** [comment]
@k8s-bot gke e2e test this github issue #IGNORE

**Comment by vishh** [comment]
@jessfraz Tests are green. 🙏 ing for no flakes.

**Comment by jessfraz** [comment]
i think the submit queue is blocked :(

**Comment by jessfraz** [comment]
opened cherrypick here: https://github.com/kubernetes/kubernetes/pull/34296

**Comment by jessfraz** [comment]
cherry-picked to 1.4 in #34296 so removing cherry-pick candidate

**Pull request merged**
