### PR TITLE
remove the redundant err define

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
some place has define err  ,like 
class, err := volutil.GetClassForVolume(d.plugin.host.GetKubeClient(), d.spec)
so delete the err define!
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jianglingxia** [comment]
I have checked the file again , need you review again,thanks very much! @msau42 
/assign @ jingxu97

**Comment by msau42** [comment]
Bazel build errors:
```
I0727 19:57:39.898] pkg/volume/glusterfs/glusterfs.go:1034: undefined: err
I0727 19:57:39.898] pkg/volume/glusterfs/glusterfs.go:1035: undefined: err
I0727 19:57:39.899] pkg/volume/glusterfs/glusterfs.go:1036: undefined: err
```

**Comment by jianglingxia** [comment]
cc @msau42 ci has successful 
/assign @jingxu97
for your approve,thanks

**Comment by jianglingxia** [comment]
sorry,why the pr hint no approved lable? @k8s-merge-robot @jingxu97 
maybe write /approve no-issue?thanks!

**Comment by jianglingxia** [comment]
sorry,why the pr hint no approved lable? @jingxu97
maybe need you write /approve no-issue
thanks!

**Pull request merged**
