### PR TITLE
third time charm for #27144

### PR DESCRIPTION
**Pull request by j3ffml**
We really need a way to test the e2e-runner

### CODE REVIEW

**Comment by spxtr** [comment]
Oh dear. I should've paid more attention to the last one. That one was my bad :P

**Comment by spxtr** [comment]
OK. I think it's okay to go. This is super-confusing.

**Comment by jlowdermilk** [comment]
I updated the comment to explain what's going on. We want to pull test tars from branch latest, but use server default for the cluster version. In practice this looks like launching a cluster with e.g. `v1.2.4`, and then running tests from the `v1.2.5-beta.0.20+02f2108e0f4486` build.

**Comment by dchen1107** [comment]
I think this pr completely breaks jenkins jobs: https://github.com/kubernetes/kubernetes/issues/27219

**Comment by jlowdermilk** [comment]
Sorry I should have pinged you offline earlier. These changes only affect gke version-pinned jobs, which don't block merge queue. The merge-queue blocking jobs are broken for a separate reason, which is that some config was missing to support running 1.3 beta in gke test. That fix is going out as well.

**Comment by dchen1107** [comment]
@jlowdermilk per our discussion, I reverted my reverts already. Will monitor the builds.

**Pull request merged**
