### PR TITLE
Update cri-tools to v1.27.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Updating cri-tools to the latest release.

#### Which issue(s) this PR fixes:
None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Updated cri-tools to v1.27.0
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Review by pacoxu — APPROVED** [review]
/lgtm
/triage accepted

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
