### PR TITLE
fixing issue with GetCPUUsageNanoCores on Windows

### PR DESCRIPTION
**Pull request by marosset**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR fixes some calculations used to determine node CPU usage for Windows

A bug was introduced by https://github.com/kubernetes/kubernetes/commit/b3a67abec73efa8539e9efb7ddb71fb155b841d9 when the polling period for fetching current CPU usage was updated from 1 second to 10 seconds and the function GetCPUUsageNanoCores did not account for this

#### Which issue(s) this PR fixes:

Fixes # https://github.com/kubernetes/kubernetes/issues/122382

#### Does this PR introduce a user-facing change?

```release-note
Fixes a 1.27.0+ regression calculating total CPU usage reported for Windows nodes
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/area kubelet
/sig windows node
/milestone v1.30

### CODE REVIEW

**Review by aravindhp — COMMENTED** [review]
/lgtm

**Review by jsturtevant — APPROVED** [review]
/lgtm

**Comment by marosset** [comment]
@yujuhong - Can you take a look at this? It is impacting users running K8s v1.27+
thanks!

**Pull request merged**
