### PR TITLE
unused function clean

### PR DESCRIPTION
**Pull request by WanLinghao**
**What this PR does / why we need it**:
clean unused function in file 
pkg/controller/volume/persistentvolume/scheduler_binder_test.go

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yue9944882** [comment]
ok-to-test

**Comment by WanLinghao** [comment]
@thockin PTAL

**Pull request merged**
