### PR TITLE
Automated cherry pick of #105983: upgrade sigs.k8s.io/structured-merge-diff to 4.2.0

### PR DESCRIPTION
**Pull request by jiahuif**
Cherry pick of #105983 on release-1.21.

#105983: upgrade sigs.k8s.io/structured-merge-diff to 4.2.0

/kind feature

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
kube-apiserver: when merging lists, Server Side Apply now prefers the order of the submitted request instead of the existing persisted object
```

### CODE REVIEW

**Comment by dims** [comment]
this PR has been on hold for about 2 weeks. Can you please see how to unblock this by reviewing comments etc? or please close this out (Trying to declutter our open list of PRs)

**Comment by liggitt** [comment]
/close

the original issue is still being worked on (xref https://github.com/kubernetes/kubernetes/issues/104641#issuecomment-978305017) and the final implementation can be picked in a new backport PR

**Pull request closed without merging**
