### PR TITLE
Automated cherry pick of #52186

### PR DESCRIPTION
**Pull request by sttts**
```release-note
Add generate-groups.sh and generate-internal-groups.sh to k8s.io/code-generator to easily run generators against CRD or User API Server types.
```

### CODE REVIEW

**Comment by sttts** [comment]
@hongchaodeng this is a cherry-pick of the code-generator PR to 1.8. Can you take a quick look? Was a clean cherry-pick, so should be the same.

**Comment by jpbetz** [comment]
@sttts Would you summarize why this needs to be cherry picked to 1.8? It's not clear to me just from reading the description of this PR and the comments.

**Comment by sttts** [comment]
@jpbetz it's documentation and blue print for consumers of k8s.io/code-generator and k8s.io/sample-apiserver, and it is enabler for 3rdparties to use `CustomResourceDefinitions` with Kubernetes 1.8 client-go. The later is not possible (anymore) without generated code (for deepcopy) and this PR gives 3rdparties the tool to effectively continue using client-go.

Note that this PR does not modify any production level code, but only adds two shell scripts to k8s.io/code-generator and modifies example code. **Hence, there is no risk involved, but it is a SDK level change.**

**Comment by mrIncompetent** [comment]
This simplifies the work with CRD's immensely when using 1.7
Thanks for cherry picking!

**Comment by sttts** [comment]
@jpbetz @wojtek-t can we merge this before 1.8.1 is tagged?

**Comment by wojtek-t** [comment]
/lgtm
/approve no-issue

But the decision is at @jpbetz side - this is relatively big change (though the risk isn't huge).

**Pull request merged**
