### PR TITLE
Automated cherry pick of #54459

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #54459 on release-1.8.

#54459: change default kind value of azure disk pv

### CODE REVIEW

**Comment by jpbetz** [comment]
Is this a backward compatible or backward incompatible change?

**Comment by andyzhangx** [comment]
`backward compatible` change, and the original default kind is not consistent with the doc

**Comment by jpbetz** [comment]
@andyzhangx Please add appropriate release note, or "release-note-none" label if there is no release note.

**Comment by andyzhangx** [comment]
@jpbetz I have labeled `release-note-none`, thx

**Pull request merged**
