### PR TITLE
fix test flake in TestStructuredAuthenticationConfigReload

### LINKED ISSUE #123855: [Flaking Test] integration master TestStructuredAuthenticationConfigReload
### Which jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1766841411577057280

### Which tests are flaking?

=== RUN   TestStructuredAuthenticationConfigReload/old_invalid_config_to_new_valid_config

### Since when has it been flaking?

first seen in 3/11
https://storage.googleapis.com/k8s-triage/index.html?text=TestStructuredAuthenticationConfigReload

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#integration-master

### Reason for failure (if possible)

```
I0310 15:25:45.525647  110365 authentication.go:721] "reloaded authentication config"
    oidc_test.go:1380: unexpected metrics diff (-want +got):   []string{
        + 	`apiserver_authentication_config_controller_automatic_reload_last_timestamp_seconds{apiserver_id_hash="sha256:3c607df3b2bf22c9d9f01d5314b4bbf411c48ef43ff44ff29b1d55b41367c795",status="failure"} FP`,
          	"apiserver_authentication_config_controller_automatic_reload_last"...,
        + 	`apiserver_authentication_config_controller_automatic_reloads_total{apiserver_id_hash="sha256:3c607df3b2bf22c9d9f01d5314b4bbf411c48ef43ff44ff29b1d55b41367c795",status="failure"} 1`,
          	"apiserver_authentication_config_controller_automatic_reloads_tot"...,
          }
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig api-machinery instrumentation

### PR DESCRIPTION
**Pull request by aramase**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
`os.WriteFile` truncates the file before writing

```go
// WriteFile writes data to the named file, creating it if necessary.
// If the file does not exist, WriteFile creates it with permissions perm (before umask);
// otherwise WriteFile truncates it before writing, without changing permissions.
// Since WriteFile requires multiple system calls to complete, a failure mid-operation
// can leave the file in a partially written state.
func WriteFile(name string, data []byte, perm FileMode) error {
```

and this can result in the new authentication config being empty when picked up by the reloader (ref: failure in https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1766841411577057280)

```
E0310 15:25:35.520748  110365 authentication.go:696] "failed to load authentication config" err="empty config data"
```

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/123855

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
Fix the lint bit about ignoring the close error, then lgtm

**Comment by aramase** [comment]
> Fix the lint bit about ignoring the close error, then lgtm

Done!

**Pull request merged**
