### PR TITLE
Update the replicas count after deletion of pod

### LINKED ISSUE #80299: [Controller Manager][StatefulSet Controller] Missing update the replicas of Statefulset
**What happened**:

I am reviewing the code of the StatefulSet Controller, and find a strange code snippet at:

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/statefulset/stateful_set_control.go#L485

and

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/statefulset/stateful_set_control.go#L488

After the 

```
status.CurrentReplicas-- 
```

or

``` 
status.UpdatedReplicas--
```

Should we have the 
```
status.Replicas-- 
```

like the code at 

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/statefulset/stateful_set_control.go#L388 

Could you tell me if this is a bug? Thanks!

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by wangxiaoq**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

This PR request to update the replicas count of StatefulSet after the deletion of pod.

**Which issue(s) this PR fixes**: 

Fixes #80299

**Special notes for your reviewer**:

We should update the replicas count of Statefulset after the deletion of a pod. 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig apps

### CODE REVIEW

**Comment by wangxiaoq** [comment]
I signed it

**Comment by wangxiaoq** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> memo **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
>     * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
>     * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> 
>     * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> 
>     * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

I signed it

**Comment by wangxiaoq** [comment]
I signed it

**Comment by wangxiaoq** [comment]
I signed it

**Comment by wangxiaoq** [comment]
I signed it

**Comment by wangxiaoq** [comment]
I signed it

**Comment by wangxiaoq** [comment]
I signed it

**Comment by mortent** [comment]
Can you add a test that demonstrates the issue that this change will fix?

**Pull request closed without merging**
