### PR TITLE
fix kubectl cp escape when destdir relative

### PR DESCRIPTION
**Pull request by ks864148379**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR cleans up the tar code used in `kubectl cp`.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
`Clean links handling in cp's tar code`

### CODE REVIEW

**Comment by ks864148379** [comment]
I signed it

**Comment by ks864148379** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

I signed it

**Comment by ks864148379** [comment]
signed

**Comment by ks864148379** [comment]
sign

**Comment by tallclair** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/pull/80436

**Pull request closed without merging**
