### PR TITLE
Revert to v0.15.0 dns manifest temporarily in ubuntu deployment

### PR DESCRIPTION
**Pull request by WIZARD-CXY**
Recently, my commit about new k8s deployment on ubuntu has been merged to upstream and is tested on 0.15.0 with success. But I find the sky-dns need dns token to be deployed correctly in the 0.16.0 or higher version.My approach do not set up token when start up. So when deploy dns, it will fail.

Since my new approach was merged recently. Its version is above 0.16.0, so this leaves some inconsistency.So I store 0.15.0 dns rc and svc manifests in cluster/ubuntu directory temporarily and use them as template to deploy dns service. I am studying on how to set up token now, but it may take some time, so I use this pr as a quick fix.@erictune @rjnagal ,what do you think?

### CODE REVIEW

**Comment by WIZARD-CXY** [comment]
@erictune it's a small update, and tested ok .Please review and looking foward for your suggestions.

**Comment by WIZARD-CXY** [comment]
@erictune @rjnagal I think this pr is kind of urgent and it is small change.Please review or merge asap.

**Comment by rjnagal** [comment]
LGTM. Thanks for the changes.

Can you do a rebase?

**Comment by WIZARD-CXY** [comment]
rebase done! and tested ok!

**Comment by rjnagal** [comment]
LGTM
Thanks @WIZARD-CXY

**Comment by WIZARD-CXY** [comment]
Shall we merge? @rjnagal

**Pull request merged**
