### PR TITLE
Bump konnectivity-client to v0.31.0

### PR DESCRIPTION
**Pull request by cheftako**
#### What type of PR is this?

/kind feature

#### Which issue(s) this PR fixes:
Bump konnectivity network proxy to v0.31.0.
Lease-based server counting logic for agent and lease controller for ANP server
Fixes #

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
no objections to the bump, looks like this doesn't actually change any behavior in the client at all

I think `hack/update-vendor.sh` needs running, verify is complaining about some of the diffs in go.mod

**Comment by jkh52** [comment]
Title says v0.30.0, it should be v0.31.0

Please also bump images in cluster/gce/addons/konnectivity-agent/konnectivity-agent-ds.yaml and cluster/gce/manifests/konnectivity-server.yaml.

**Comment by cheftako** [comment]
> Title says v0.30.0, it should be v0.31.0
> 
> Please also bump images in cluster/gce/addons/konnectivity-agent/konnectivity-agent-ds.yaml and cluster/gce/manifests/konnectivity-server.yaml.

Fixed

**Comment by cheftako** [comment]
> no objections to the bump, looks like this doesn't actually change any behavior in the client at all
> 
> I think `hack/update-vendor.sh` needs running, verify is complaining about some of the diffs in go.mod

I had run it [per the directions](https://github.com/kubernetes-sigs/apiserver-network-proxy/blob/master/RELEASE.md) but I think update-codegen may have got in the way. Reran the command and more changes appeared. See if this is sufficient.

**Comment by jkh52** [comment]
> > Title says v0.30.0, it should be v0.31.0
> > Please also bump images in cluster/gce/addons/konnectivity-agent/konnectivity-agent-ds.yaml and cluster/gce/manifests/konnectivity-server.yaml.
> 
> Fixed

These images are still referencing v0.30.3, mind bumping them?

**Pull request merged**
