### PR TITLE
feat: cleanup pod critical pod annotations feature

### LINKED ISSUE #79548: Remove Critical Pod Annotation
[Critical Pod Annotation](https://github.com/kubernetes/kubernetes/blob/665e76d97623447d13bb3b33b68591a985b49c9d/pkg/features/kube_features.go#L58) is an experimental feature that lets Kubernetes control plane know about a pod being a critical pod by adding a specific annotation to the pod. This was added in 1.5 when K8s didn't have pod priority. Pod priority allows us to mark pods as critical with our first-class API. As a result, this feature was deprecated in 1.13. We can now remove the feature from our code base.

/sig scheduling
/sig node

### PR DESCRIPTION
**Pull request by draveness**
/kind cleanup
/priority important-soon
/sig scheduling
/sig node

**What this PR does / why we need it**:

Reapply https://github.com/kubernetes/kubernetes/pull/79554

> Critical Pod Annotation is an experimental feature that lets Kubernetes control plane know about a pod being a critical pod by adding a specific annotation to the pod. This was added in 1.5 when K8s didn't have pod priority. Pod priority allows us to mark pods as critical with our first-class API. As a result, this feature was deprecated in 1.13. We can now remove the feature from our code base.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/79548

**Does this PR introduce a user-facing change?**:

```release-note
scheduler.alpha.kubernetes.io/critical-pod annotation is removed. Pod priority (spec.priorityClassName) should be used instead to mark pods as critical. Action required!
```

### CODE REVIEW

**Comment by draveness** [comment]
/hold

blocked by regression https://github.com/kubernetes/kubernetes/issues/80203

**Review by mattjmcnaughton — COMMENTED** [review]
Just to confirm... this is the same diff as before, but we are holding it on fixing the issue you linked above (which was the cause of the regression)?

**Comment by draveness** [comment]
> Just to confirm... this is the same diff as before, but we are holding it on fixing the issue you linked above (which was the cause of the regression)?

Yes, this would be merged after we solve #80203

**Comment by dixudx** [comment]
I think it is safe to merge this now, since statis pod issue has been fixed in #80491.

/lgtm
/approve

**Review by dixudx — APPROVED** [review]

**Comment by draveness** [comment]
Kindly ping @deads2k @mikedanese @vishh @liggitt for approval since the previous PR #80203 has already been merged.

**Pull request merged**
