### PR TITLE
Replace variables 10251 and 10252 with constants

### PR DESCRIPTION
**Pull request by xichengliudui**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Ref: https://github.com/kubernetes/kubernetes/pull/74479

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
thanks
/approve
/priority backlog

please make the build pass locally:
```
W0401 09:10:57.735] ERROR: /workspace/k8s.io/kubernetes/cmd/kubeadm/app/phases/controlplane/BUILD:29:1: GoCompile cmd/kubeadm/app/phases/controlplane/linux_amd64_pure_stripped/go_default_library%/k8s.io/kubernetes/cmd/kubeadm/app/phases/controlplane.a failed (Exit 1) compile failed: error executing command
```

`make all WHAT=./cmd/kubeadm`

**Comment by xichengliudui** [comment]
I'll fix it.

**Comment by xichengliudui** [comment]
What are you building? I keep failing to build.
```
root@node2 kubernetes]# make all WHAT=cmd/kubeadm/app/phases/controlplane/BUILD

Detected go version: go version go1.11.4 linux/amd64.
Kubernetes requires go1.12.1 or greater.
Please install go1.12.1 or later.

!!! [0321 17:20:38] Call tree:
!!! [0321 17:20:38]  1: hack/run-in-gopath.sh:30 kube::golang::setup_env(...)
make[1]: *** No rule to make target `/Golang/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/pflag/', needed by `_output/bin/deepcopy-gen'.  Stop.
make: *** [generated_files] Error 2
```

**Comment by neolit123** [comment]
call this from the parent kubernetes source directory:
`make all WHAT=./cmd/kubeadm`

**Comment by yagonobre** [comment]
Hi @xichengliudui can you run `./hack/update-bazel.sh` and commit the changes? (squash your commits on a single commit)

**Comment by xichengliudui** [comment]
@neolit123 @yagonobre thanks.

**Comment by xichengliudui** [comment]
Here.

**Comment by SataQiu** [comment]
Thanks @xichengliudui 
/lgtm

**Pull request merged**
