### PR TITLE
Do not move pid 1 to /system container

### PR DESCRIPTION
**Pull request by jimmidyson**
@dchen1107 Even after our discussion this was missed in #19354 - sorry!

/cc @justinsb

### CODE REVIEW

**Comment by justinsb** [comment]
I tested this on AWS, and it fixes #19340.  Thanks so much @jimmidyson.

**Comment by brendandburns** [comment]
LGTM.

**Comment by dchen1107** [comment]
LGTM

**Comment by justinsb** [comment]
@k8s-bot unit test this github flake: #IGNORE

**Comment by justinsb** [comment]
@k8s-bot test this github flake: #IGNORE

**Comment by justinsb** [comment]
@k8s-bot unit test this github flake: #20646

**Comment by justinsb** [comment]
@k8s-bot test this github flake: #20646

**Comment by justinsb** [comment]
@k8s-bot test this github flake: #20547 

Exact match for 20547 again: UPDATE version 5597, SYNC version 5597, UPDATE version 5597

**Comment by justinsb** [comment]
@k8s-bot test this github flake #20547

**Comment by justinsb** [comment]
@k8s-bot test this github flake #20708

**Comment by justinsb** [comment]
Sorry, wrong flake link.. this one was #20547 again

**Comment by jimmidyson** [comment]
Yay! Please can we merge this now?

**Comment by justinsb** [comment]
@jimmidyson I sure hope so (you've probably noticed I'm keen on this one too!)  I think #20697 has helped the e2e tests, and I think we're number 5 in the merge queue...

**Comment by jimmidyson** [comment]
@justinsb I can see you are - thanks for your help!

**Comment by jimmidyson** [comment]
@brendanburns @dchen1107 I think this is a pretty important fix to get in. Can we get this merged please?

**Pull request merged**
