### PR TITLE
QOS: New class proposal: Scavenger 

### PR DESCRIPTION
**Pull request by ckleban**
# QOS: New class proposal: Scavenger

**Author**: Chris Kleban (Github: @ckleban Twitter: @kleban) 

**Status**: Draft proposal; 

*This is a simple proposal for adding a new quality of service (qos) class to kubernetes (k8), called the scavenger class. The scavenger class would be the lowest priority class available. *

Note: This is meant to spark conversation, thought and consideration. If and when this is deemed desirable, we can flush out more details. 
## Motivation

Note: This concept is borrowed from the networking world's quality of service realm. 

The main motivation of this new qos class is that it allows users of k8 clusters to easily and safely use spare cluster resources, without qorrying about impacting other work loads in the best effort class. 

K8's new qos features allow cluster admins and users the ability to apply resource priority allocation during resource starvation so that applications are assigned resources based on the user's desired priority, versus an equal sharing of resources during stages of starvation. K8's current qos implementation has 3 classes, with best effort being the lowest level of priority. The result of this is that any application in k8 assigned to the best effort class will equally share resources during periods of resource starvation. Additionally, it is important to know that with some k8 users, the best effort class will be the default and the other classes may not be used. 

The benefit of the scavenger class is that is allows k8 users to deploy applications on a k8 cluster in a way that they can comfortably know they will not starve out resources in the best effort class. 
## Scavenger Class Resource management.

Here is my first thoughts on how the scavenger class could treat resource assignment. 
- Anything in the scavenger class should have 0 guaranteed resources
- Anything in the scavenger class should be able to use spare resources. 
- During periods of resource starvation, everything in the scavenger class only gets to burst into a configurable amount of resources, or the pods should get killed. The default value for this should be perhaps 0% (or perhaps a really low value, like 3%, if 0% resources would cause issues) 
## Use Cases

Here are some possible use cases for this class. 
- Allow k8 users to easily and safely try out new applications without worrying about impacting anything in the best effort class. 
- In addition, allow for the safe load testing and resource consumption modeling of new applications.  
- Allow k8 admins/users to build applications with the lowest infrastructure cost. This easily allow the creation of free or low cost services. IE, if you are a CDN company, you can launch pay-for CDN in best effort and give away CDN to anyone in the scavenger class. 
- Allow k8 admins/users to donate spare resources to charity or scientific reasons (like boinc) without worrying about impacting production systems. 
- Allow people to share spare resources for whatever reason. This could help the world: http://www.datamation.com/open-source/linuxcon-open-source-peer-collaboration-could-save-the-planet.html

### CODE REVIEW

**Comment by vishh** [comment]
@ckleban: Thanks for the PR! We usually recommend [posting a proposal](https://github.com/kubernetes/kubernetes/blob/e3afa2da7ac91373d6d64d73b4c7dab7832f6ae8/docs/devel/faster_reviews.md#1-dont-build-a-cathedral-in-one-pr) in the form of a markdown, before posting a PR :). That helps isolate the design discussion.
In general, as per the current QoS design, best effort is already not guaranteed any resources. It gets very few CPU shares and it can only use slack memory, and its the first choice for eviction in case of resource crunch. I don't see the need for a new class that has lower resource guarantees. Can you explain?

**Comment by ckleban** [comment]
@google, I signed it!

**Comment by ckleban** [comment]
@vishh Thanks for the tip and the review. I'll follow that moving forward and let me know if resubmitting in that manner makes sense. 

Regarding the need for a lower class, it comes down to how users actually use qos. Not all applications will have qos settings and I'd imagine the majority of applications will end up in the best effort bucket. If this is true, if a user wants to deploy a single app without taking the resources away from the majority of applications, they will need to first reconfigure their existing applications to the guaranteed or burstable priority queues. Instead, if the scavenger class existed, users can simply set that class to new applications, versus touching all the existing applications in best effort. 

I'd agree that is k8 users only used the guaranteed or bursting queues, than the scavenger class isn't needed. Rather, users can just use the best effort class. However, speaking from experience, this won't be many user's situation.

**Comment by vishh** [comment]
#12472 talks about setting initial resource requests for pods, that are not explicitly marked as best effort, based on historical usage data. That moves k8s in the direction of running pods in burstable class by default.

**Comment by roberthbailey** [comment]
@ckleban - it's unclear to me exactly what you are trying to do with this PR. Github shows that it has 250+ commits that you are trying to merge from the release-1.0 branch into the master branch, which seems odd. Have you had a change to read through https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md?

**Comment by ckleban** [comment]
Closing pull request.

**Comment by roberthbailey** [comment]
@ckleban Sorry for the confusion. As @vishh noted above, we'd welcome a PR in the form of a markdown document that is a design proposal.

**Pull request closed without merging**
