### PR TITLE
fix a potential deadlock

### PR DESCRIPTION
**Pull request by charlesxsh**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR tries to fix a potential deadlock issue. If line 117 happened before line 115, then line 124 will be blocked forever.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Similar issue/fix: https://github.com/kubernetes/kubernetes/pull/83925
#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by charlesxsh** [comment]
hi there, any update on this PR?

**Comment by charlesxsh** [comment]
@jpbetz Hi there, do we have any update on this PR?

**Comment by system-pclub** [comment]
if "stopped <- true" executes earlier, the select statement chooses the first case and no other goroutine can receive messages from channel timeout. The goroutine created at line 109 blocks endlessly. The patch is to Increase the buffer size of channel timeout from 0 to 1. It does not change the program behavior if "timedout <- true" executes earlier. But it can gracefully turn down the goroutine if "stopped <- true" happens earlier.

**Comment by dims** [comment]
@jpbetz did you get a chance to peek?

**Comment by jpbetz** [comment]
Sorry for the delay.

Should both channels be of size 1, i.e. should we also have `stopped := make(chan bool, 1)` ? It looks like we loose the receiver of both channels in the same way..

**Pull request closed without merging**
