### PR TITLE
Update generated copyrights so people stop getting huge diffs

### LINKED ISSUE #57728: Code generator wants to replace 2017 with 2018 in all generated license statements
Happy New Year! Now when I run make I get a diff like this in every zz_generated file:
```
diff --git a/cmd/kubeadm/app/apis/kubeadm/v1alpha1/zz_generated.conversion.go b/cmd/kubeadm/app/apis/kubeadm/v1alpha1/zz_generated.conversion.go
index 5cebdd5d5b..0d7f685c3b 100644
--- a/cmd/kubeadm/app/apis/kubeadm/v1alpha1/zz_generated.conversion.go
+++ b/cmd/kubeadm/app/apis/kubeadm/v1alpha1/zz_generated.conversion.go
@@ -1,7 +1,7 @@
 // +build !ignore_autogenerated
 
 /*
-Copyright 2017 The Kubernetes Authors.
+Copyright 2018 The Kubernetes Authors.
```

Not sure what a smart solution is, but we could merge something like #57729 in the meantime.

### PR DESCRIPTION
**Pull request by mtaufen**
Fixes #57728, sort of

The generator really wants to do this, so I say we let it do it as a hotfix to stop people getting large diffs, and then figure out a way to handle this more intelligently for the 2018->2019 transition.

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
Thanks for this @mtaufen.. was just about to do the same.
We also need to update this regex to support 2018: https://github.com/kubernetes/kubernetes/commit/98534200bce7d2e039d6f127af828bd64dfe6086

And it also looks like there some other generated files.. a full `make update` should catch them all.

ref: https://github.com/kubernetes/kubernetes/pull/39342
cc: @ixdy @thockin @smarterclayton @sttts 

To quote @ixdy:
> I'm hoping that maybe the generated code situation will be a in a better place by 2018...

Nope 🙃.

/priority critical-urgent

**Comment by sttts** [comment]
> And it also looks like there some other generated files.. a full make update should catch them all.

Waiting for that one. Otherwise lgtm.

**Comment by cblecker** [comment]
As this is blocking all PRs and CI, I opened https://github.com/kubernetes/kubernetes/pull/57735. `make update` got most of them, but there were two code generation scripts it missed. I added those into the right places for next time.

**Comment by mtaufen** [comment]
@cblecker thanks! Since it looks like you've got it covered, I'm going to close this PR.

**Pull request closed without merging**
