### PR TITLE
fix: correct the mentioned endpointslice manage label name.

### PR DESCRIPTION
**Pull request by Colstuwjx**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
The actually in-use endpointslice manage-by label name is `endpointslice.kubernetes.io/managed-by`, rather than `http://endpointslice.kubernetes.io/managed-by`, correct this in order to no misleading our users. 

**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by robscott** [comment]
Thanks! Not sure how that happened.

/lgtm

**Comment by Colstuwjx** [comment]
Update background:

I was reading related features about EndpointSlice, like `endpointslice.kubernetes.io/managed-by`, and saw the target line in this PR, it was introduced by [PR #86090](https://github.com/kubernetes/kubernetes/pull/86090/files#diff-6583cdeef267673cc285e514b3d6069bR144).

TBH, I also don't know why this line has been added `http://`, but I think the correct label name should be `endpointslice.kubernetes.io/managed-by` without leading `http://`, so I proposed this PR for fixing this typo.

Thanks.

**Pull request merged**
