### PR TITLE
Fix taint based pod eviction for clusters where controller manager is not running with allocate-node-cidrs set

### PR DESCRIPTION
**Pull request by aveshagarwal**
Fixes https://github.com/kubernetes/kubernetes/issues/42733

In my cluster, I have not set allocate-node-cidr, and It is causing taint based pod eviction to fail. 

@gmarek @kubernetes/sig-scheduling-bugs @davidopp @derekwaynecarr

### CODE REVIEW

**Comment by aveshagarwal** [comment]
just FYI, I am using flannel in my cluster.

**Comment by gmarek** [comment]
Great catch!
/lgtm
/approve

**Comment by aveshagarwal** [comment]
@k8s-bot gci gce e2e test this

**Comment by bsalamat** [comment]
I think we should add tests to cover the scenario. It can be done in a different PR.

**Comment by aveshagarwal** [comment]
@gmarek you need to assign it to yourself to make lgtm work. Also please set 1.6 milestone. thanks.

**Comment by aveshagarwal** [comment]
@k8s-bot unit test this

**Comment by davidopp** [comment]
Thanks for fixing. One question: what is the connection between this and pod eviction? I see what the bug is (forgot to put these handlers in the else branch, that were in the if branch) but I didn't understand how it's connected to pod eviction.

**Comment by aveshagarwal** [comment]
@davidopp without those handlers, taint controller was not getting any node updates and due to this, did not act on pod eviction, so no pod eviction was happening even if a NoExecute taint was set.

**Comment by davidopp** [comment]
Ah, that makes sense. Thanks.

**Comment by aveshagarwal** [comment]
My guess is that tests are failing because of this: https://github.com/kubernetes/kubernetes/pull/42944 .

**Comment by liggitt** [comment]
The only failing tests I know of that https://github.com/kubernetes/kubernetes/pull/42944 fixes are ones that skew tests were running. What failure were you referring to?

**Comment by aveshagarwal** [comment]
@liggit Actually these unit/integration were passing before, but only today they started failing (actually I ran twice and both times they failed),  I see these failures in the unit/integration tests

```
(B[m+++ [0311 11:26:27] "kubectl patch with resourceVersion 347" returns error as expected: Error from server (Conflict): Operation cannot be fulfilled on pods "valid-pod": the object has been modified; please apply your changes to the latest version and try again
.
.
.
I0311 11:26:28.732] node "node-v1-test" created
W0311 11:26:28.832] I0311 11:26:28.823388   23902 event.go:217] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"node-v1-test", UID:"9fed7e56-0690-11e7-94eb-0242ac110002", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node node-v1-test event: Registered Node node-v1-test in NodeController
W0311 11:26:28.959] Error from server (Conflict): error when replacing "STDIN": Operation cannot be fulfilled on nodes "node-v1-test": the object has been modified; please apply your changes to the latest version and try again
W0311 11:26:28.960] !!! [0311 11:26:28] Call tree:
W0311 11:26:28.960] !!! [0311 11:26:28]  1: /go/src/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh:2966 run_pod_tests(...)
W0311 11:26:28.960] !!! [0311 11:26:28]  2: hack/make-rules/test-cmd.sh:99 runTests(...)
I0311 11:26:29.750] +++ [0311 11:26:29] Clean up complete
I0311 11:26:29.751] Makefile:264: recipe for target 'test-cmd' failed
W0311 11:26:29.852] make: *** [test-cmd] Error 1
W0311 11:26:31.271] Traceback (most recent call last):
```

May be I am incorrect in guess that these failures are related to your issues fixed in your PR.
Could you confirm that these are not related, and I will just rerun as the failures dont seem related to this PR?

**Comment by liggitt** [comment]
It is unrelated.

**Comment by aveshagarwal** [comment]
@liggitt thanks.

@k8s-bot unit test this

**Pull request merged**
