### PR TITLE
Remove proxy-mode annotation from kube-proxy

### LINKED ISSUE #40582: Remove kube-proxy ProxyModeAnnotation
This annotation dates back almost a year.   This is a relatively easy project for someone to contribute.

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
This removes the net.experimental.kubernetes.io/proxy-mode and net.beta.kubernetes.io/proxy-mode annotations from kube-proxy.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #40582 

**Special notes for your reviewer**:

**Release note**:

```release-note
Remove outdated net.experimental.kubernetes.io/proxy-mode and net.beta.kubernetes.io/proxy-mode annotations from kube-proxy.
```

### CODE REVIEW

**Comment by thockin** [comment]
@k8s-bot ok to test

**Comment by thockin** [comment]
Thanks!

**Comment by thockin** [comment]
```
I0127 23:16:10.194] Verifying hack/make-rules/../../hack/verify-gofmt.sh
I0127 23:16:23.925] !!! 'gofmt -s -w' needs to be run on the following files: 
I0127 23:16:23.925] ./cmd/kube-proxy/app/server.go
```

**Comment by cblecker** [comment]
@thockin -- New commit pushed. The `make verify` fmt test now passes locally.

**Comment by thockin** [comment]
Test fail:

I0128 09:25:42.309] FAIL	k8s.io/kubernetes/pkg/controller/deployment	2.206s

Doesn't seem related

@k8s-bot unit test this

**Comment by cblecker** [comment]
Looks like there is an open flake for this: #39908

```
deployment_controller_test.go:549: expected deployment "foo" not to be queued after pod deletion
```

@k8s-bot unit test this

**Pull request merged**
