### PR TITLE
Mark QoS as an experimental feature

### PR DESCRIPTION
**Pull request by vishh**
@bgrant0607: Updated doc as discussed offline.

Given that #14943 is still under debate, I have opened this PR to mark QoS as an experimental feature in v1.1. I intend to cherry-pick this PR into the v1.1 release branch.
cc @derekwaynecarr

### CODE REVIEW

**Comment by bgrant0607** [comment]
Just referring to offline discussion is not helpful. Should have at least referenced the prior PR: #14943.

Please add the references mentioned in the previous PR.

Citing the split hierarchy issue as an example would help people understand why it's not fully baked. This is too terse.

**Comment by vishh** [comment]
@bgrant0607: Updated the PR to include a few major issues.

**Comment by derekwaynecarr** [comment]
LGTM

**Comment by bgrant0607** [comment]
Ok.

**Pull request merged**
