### PR TITLE
fix test order in controller/openapi/builder/builderst.go

### PR DESCRIPTION
**Pull request by dengyufeng2206**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Per https://pkg.go.dev/github.com/stretchr/testify/assert#Equal expected goes before actual:

func Equal(t TestingT, expected, actual interface{}, msgAndArgs ...interface{}) bool
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Fixes tests asserting that the expected values were the actual ones, when they were not. just like
https://github.com/kubernetes/kubernetes/pull/102611
https://github.com/kubernetes/kubernetes/pull/102615
#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
/triage accepted
/lgtm
/assign @lavalamp
For approval if you have time? Thank you

**Comment by lavalamp** [comment]
/approve

You need to set the release note to "NONE"

**Comment by dengyufeng2206** [comment]
> /approve
> 
> You need to set the release note to "NONE"

ok，thank you for your review :)

**Pull request merged**
