### PR TITLE
fix potential deadlock

### PR DESCRIPTION
**Pull request by charlesxsh**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR tries to fix a potential deadlock issue at cluster/images/etcd/migrate/migrate_server.go. If line 76 happened before line 86, line 72 will be blocked forever.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Similar issue/fix: https://github.com/kubernetes/kubernetes/pull/83925

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by charlesxsh** [comment]
hi there, any update on this PR?

**Review by jpbetz — APPROVED** [review]
Sorry for the delay

**Pull request merged**
