### PR TITLE
Run snapshot before PreFilter plugins when schedule begins

### PR DESCRIPTION
**Pull request by hex108**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

When each schedule begins, run snapshot before Prefilter plugins because  Prefilter plugins might use snapshot data.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig scheduling
/priority important-soon

### CODE REVIEW

**Comment by wgliang** [comment]
_When each schedule begins, run snapshot before Prefilter plugins because Prefilter plugins might use snapshot data._

Why Prefilter plugins need snapshot data? Is there some case? In general, Prefilter should not pay attention to the state of the cluster itself.

**Comment by hex108** [comment]
@wgliang I try to use it to implement something similar to [resource quota](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/node-labels-quota.md), and it needs cluster status. And the [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#pre-filter) also mentions this kind of usage:

> These plugins are used to pre-process info about the pod, or to check certain conditions that **the cluster** or the pod must meet. 


And prefilter plugins could use snapshot data through `FrameworkHandle` interface easily.

**Comment by wgliang** [comment]
> @wgliang I try to use it to implement something similar to [resource quota](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/node-labels-quota.md), and it needs cluster status. And the [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md#pre-filter) also mentions this kind of usage:
> 
> > These plugins are used to pre-process info about the pod, or to check certain conditions that **the cluster** or the pod must meet.
> 
> And prefilter plugins could use snapshot data through `FrameworkHandle` interface easily.

Got it. Thanks for reply.

**Review by wgliang — APPROVED** [review]
/lgtm

**Comment by Huang-Wei** [comment]
I was talking with @ahg-g on this. Appreciate @hex108 also spotted it.

We're now refactoring the metadata path to use PreFilter plugin to compute plugin-specific metadata, so `g.snapshot()` is necessary to run prior to running PreFilter plugins.

**Pull request merged**
