### PR TITLE
fix:remove Redundant type conversion

### PR DESCRIPTION
**Pull request by falser101**
Signed-off-by: jianfei.zhang <jianfei.zhang@daocloud.io>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
remove Redundant type conversion

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by falser101** [comment]
> ‎`/ok-to-test`

‎/ok-to-test

**Comment by falser101** [comment]
> /retest-required

/retest-required

**Comment by liggitt** [comment]
can we drop the changes to the third_party/forked folders? we generally try to minimize changes to those dirs

**Comment by falser101** [comment]
> can we drop the changes to the third_party/forked folders? we generally try to minimize changes to those dirs

removed

**Comment by liggitt** [comment]
thanks. squash to a single commit, then lgtm

**Comment by falser101** [comment]
> thanks. squash to a single commit, then lgtm
ok, it's already squashed, please help review, thanks!
@liggitt 
@DangerOnTheRanger

**Comment by falser101** [comment]
> 



> thanks. squash to a single commit, then lgtm

squashed

**Comment by falser101** [comment]
> /retest-required

/retest-required

**Pull request merged**
