### PR TITLE
Remove often failing test pd.sh

### PR DESCRIPTION
**Pull request by satnam6502**
Issue #4028 details why this test often fails and needs some work to be more reliable. Let's remove this test from the test suite temporarily, work on it to improve it, and then introduce it. Removing this test is likely to put our e2e success rate > 80% from the current 62%. @brendandburns @zmerlynn @filbranden @roberthbailey

### CODE REVIEW

**Comment by brendandburns** [comment]
Please don't do this.  We should fix the test.  I don't actually think etcd is the cause.  The problem is that the PD isn't detaching/reattaching correctly across a PD delete.

Removing coverage is _never_ the right answer here.  We need better visibility to see why we are having problems with PD detaching.

**Comment by satnam6502** [comment]
I should emphasize that I said that `pd.sh` (mostly) **does not** fail due to etcd. OK: let's fix the test.

**Comment by brendandburns** [comment]
Note that there is another PR in flight (
https://github.com/GoogleCloudPlatform/kubernetes/pull/3967) that I hope
will help with this.

(and also, I think that a PR today will fix the etcd problems)

--brendan

**Comment by satnam6502** [comment]
What's the PR that will fix the etcd problems?

I apologize for this PR. There is a tension between having reliable end to end tests for a high velocity code base vs. having good coverage.

**Comment by roberthbailey** [comment]
I think Brendan was referring to #4021 which fixes the etcd problems when creating new clusters (other than on GCE). This doesn't address your concern about etcd pressure though if we are overloading it as it was purely an initialization error that was fixed.

**Pull request closed without merging**
