### PR TITLE
Automated cherry pick of #31189 #31704 #32831 #32907 #33003 #33349 #31190 #33581 #34089 #34234 #32822 #33393 #34246 #34435 #32477 upstream release 1.4

### PR DESCRIPTION
**Pull request by wojtek-t**
We are going to release etcd v3 in 1.4.x release.

```
Cherrypick etcd v3-related bug fixes to 1.4 branch
```

Those PRs include:
- Updates of etcd Godeps
- Update to pkg/storage/etcd directory
- Two PR that were unnecessary to avoid conflicts: #31189 #31704

Automated cherry pick of #31189 #31704 #32831 #32907 #33003 #33349 #31190 #33581 #34089 #34234 #32822 #33393 #34246 #34435 #32477

@hongchaodeng @xiang90 @lavalamp @smarterclayton

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35205)

### CODE REVIEW

**Comment by jessfraz** [comment]
we are going to do this one in it's own release right? so we should wait to merge

**Comment by wojtek-t** [comment]
OK - all tests are passing now;

@mml @timothysc @jessfraz - can you please take a look?

**Comment by jessfraz** [comment]
these are the bits for etcd that can be merged now?

**Comment by wojtek-t** [comment]
>
these are the bits for etcd that can be merged now?

Yes - this should not affect production at all (this is updating only Godeps for etcd (which are used only in tests) and etcd3 code (which is not used in 1.4 release).

**Comment by jessfraz** [comment]
thanks for confirming! I'll let @mml and @timothysc do the honors but looks good to me

**Comment by mml** [comment]
Not sure exactly what a cherrypick code review should entail.  The original code was carefully reviewed.  Without reading all 17 PRs, all I can say is that the tests pass, so LGTM.

**Pull request merged**
