### PR TITLE
dockershim: add unit tests for sandbox/container status

### PR DESCRIPTION
**Pull request by yujuhong**
Part of #31459

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31804)

### CODE REVIEW

**Comment by yujuhong** [comment]
Only the last commit is new. The rest is from #31573

**Comment by feiskyer** [comment]
LGTM

**Comment by yujuhong** [comment]
Applying lgtm based on https://github.com/kubernetes/kubernetes/pull/31804#issuecomment-243963289

**Comment by wojtek-t** [comment]
@gmarek 
Most probably this PR completely broke kubemark - we will verify it and if that's the case, I'm going to revert this PR.
BTW - this is increasing priority of doing #29897 - @lavalamp FYI

**Comment by wojtek-t** [comment]
Confirmed that this is a problem. Reverting.

**Pull request merged**
