### PR TITLE
support comma delimited env arg kubectl run

### PR DESCRIPTION
**Pull request by juanvallejo**
**Release note**:
```release-note
NONE
```

Related downstream bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1523069

**Before**
```
$ kubectl run myrun-pod  --image=my-image --generator=run-pod/v1 --env=MYENV1=v1,MYENV2=v2
pod "myrun-pod" created

$ kubectl get pod myrun-pod -o json
...
"containers": [
            {
                "env": [
                    {
                        "name": "MYENV1",
                        "value": "v1,MYENV2=v2"
                    }
                ],
...
```

**After**
```
$ kubectl run myrun-pod  --image=my-image --generator=run-pod/v1 --env=MYENV1=v1,MYENV2=v2
pod "myrun-pod" created

$ kubectl get pod myrun-pod -o json
...
"containers": [
            {
                "env": [
                    {
                        "name": "MYENV1",
                        "value": "v1"
                    },
                    {
                        "name": "MYENV2",
                        "value": "v2"
                    }
                ],
...
```

cc @soltysh @shiywang

### CODE REVIEW

**Comment by smarterclayton** [comment]
Why aren't we using StringSlice() for --env?  Which is the correct way to fix this

**Comment by soltysh** [comment]
> Why aren't we using StringSlice() for --env? Which is the correct way to fix this

It looks like it was broken in https://github.com/kubernetes/kubernetes/pull/47460 I think we need a combo of StringSlice with StringArray, so that both ways are supported.

**Comment by juanvallejo** [comment]
@soltysh Hm, looking at the use-case that @mengqiy 's PR addresses, the fix in this PR would break in cases where an object is provided as the value of an env key: `--env=MYENV={"one": 1, "two": 2}`. So StringSlice would prevent such values from being provided, and using what we have now (StringArray and ignoring a potential comma-delimited list) prevents multiple values from being provided in one --env flag.

Maybe a solution could be to expect multiple `--env` flags for multiple values, and keep what we currently have to support json objects as env values

**Comment by soltysh** [comment]
> Maybe a solution could be to expect multiple --env flags for multiple values, and keep what we currently have to support json objects as env values

Yeah, that's basically what I was suggesting previously, a combinatin of StringSlice with StringArray so that you can pass multiple `--env` flags as well as comma separated values.

**Pull request closed without merging**
