### PR TITLE
Fix e2e flake: Fix incorrect expectation when deployment scaling down old rcs

### PR DESCRIPTION
**Pull request by janetkuo**
#18996 #19064 #19299

cc @nikhiljindal @ghodss @ironcladlou @kargakis @bgrant0607

### CODE REVIEW

**Comment by janetkuo** [comment]
@k8s-bot e2e test this

**Comment by janetkuo** [comment]
Rebased. PTAL

**Comment by nikhiljindal** [comment]
Not sure if this is the bug that is causing the e2e flake, but this PR definitely fixes a bug.

LGTM, thanks.

**Comment by janetkuo** [comment]
@k8s-bot unit test this

**Comment by nikhiljindal** [comment]
cc @k8s-oncall: This should help with fixing e2e flakes.
Please feel free to manually merge this, since the merge bot is blocked

**Pull request merged**
