### PR TITLE
skip the reason check for OOM reason test if it will fail

### PR DESCRIPTION
**Pull request by tzneal**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

This is currently flaking for both containerd/crio due to a race in cgroup deletion and reading the memory.events file were the OOMKill is recorded. Skip the part that fails for now until the issue is resolved.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tzneal** [comment]
Related to https://github.com/kubernetes/kubernetes/issues/119600

**Comment by SergeyKanzhelev** [comment]
Discussing a SIG Node CI meeting. This will fail on CRI-O as well. SO we may be better off by skipping the test altogether.

**Comment by SergeyKanzhelev** [comment]
Link from @haircommander: https://github.com/opencontainers/runc/pull/3932

**Comment by haircommander** [comment]
another xref https://github.com/cri-o/cri-o/issues/7035

**Comment by pacoxu** [comment]
/priority important-soon
as it flakes a lot, or important-longterm
/triage accepted

**Comment by pacoxu** [comment]
> Discussing a SIG Node CI meeting. This will fail on CRI-O as well. SO we may be better off by skipping the test altogether.

IIRC, can we add [Flaky] to this e2e test in such a case?

**Comment by tzneal** [comment]
> IIRC, can we add `[Flaky]` to this e2e test in such a case?

I could be convinced either way, but I prefer this method as it still tests that the termination occurs for the single & multi-process cases and just skips the flaking bit instead of the entire test.

**Comment by kannon92** [comment]
Opened up https://github.com/kubernetes/kubernetes/pull/121031 to help resolve these failures.

**Review by kannon92 — COMMENTED** [review]
/lgtm

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
