### PR TITLE
kubeadm: Amend the hyperkube deprecation change

### PR DESCRIPTION
**Pull request by rosti**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

As #85094 got merged accidentally (the CI robot not respecting a `/hold`) we need to amend it with the feedback separately.

**Which issue(s) this PR fixes**:

Refs kubernetes/kubeadm#1889

**Special notes for your reviewer**:

/cc @kubernetes/sig-cluster-lifecycle-pr-reviews
/area kubeadm
/priority important-soon
/assign @neolit123 @ereslibre @fabriziopandini 
/cc @yastij

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/lgtm
thanks @rosti seems good.

**Comment by rosti** [comment]
/hold
for another pass over it, don't want to make a second amend PR ;)

**Comment by rosti** [comment]
Updated with marking the internal `UseHyperKubeImage` field as deprecated.

**Review by fabriziopandini — APPROVED** [review]
/lgtm

**Review by yastij — COMMENTED** [review]
/lgtm

**Pull request merged**
