### PR TITLE
Volunteer to be DaemonSet controller maintainer.

### PR DESCRIPTION
**Pull request by k82cn**
Signed-off-by: Klaus Ma <klaus1982.cn@gmail.com>

Reviewer: Since [Oct 23, 2017](https://github.com/kubernetes/kubernetes/pull/54402)
 Merged: [20 PRs](https://github.com/pulls?q=is%3Apr+archived%3Afalse+user%3Akubernetes+is%3Amerged+label%3Asig%2Fapps+author%3Ak82cn) (most of them are about DaemonSet)
 Reviewed: 10 ; https://github.com/kubernetes/kubernetes/pull/46577 , https://github.com/kubernetes/kubernetes/pull/48189 , https://github.com/kubernetes/kubernetes/pull/58869 , https://github.com/kubernetes/kubernetes/pull/61411 , https://github.com/kubernetes/kubernetes/pull/66480 , https://github.com/kubernetes/kubernetes/pull/67036 , https://github.com/kubernetes/kubernetes/pull/67899 , https://github.com/kubernetes/kubernetes/pull/69057 , https://github.com/kubernetes/kubernetes/pull/69192 , https://github.com/kubernetes/kubernetes/pull/69730

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by k82cn** [comment]
sure, will append related info soon; some PRs are not tagged :)

**Comment by k82cn** [comment]
update some contribution in description; if any comments, please let me know :)

**Comment by mikedanese** [comment]
I'm fine with this change but I would like to see it approved by a sig-apps Workload API subproject owner. Even better, we should consolidate all these owners files into aliases managed by sig-apps like sig-auth is doing in #70600.

**Comment by janetkuo** [comment]
> Primary reviewer for at least 10 substantial PRs to the codebase

@k82cn would you also include the PRs that you've reviewed for this requirement?

**Comment by k82cn** [comment]
> would you also include the PRs that you've reviewed for this requirement?

sure, let me check the history; did not assign to myself when reviewing prs :)

**Comment by k82cn** [comment]
> would you also include the PRs that you've reviewed for this requirement?

Done (updated description).

**Comment by mikedanese** [comment]
lgtm
/approve

Please continue to cc janet and I on changes here so we can keep track of what's going in

**Review by janetkuo — APPROVED** [review]

**Pull request merged**
