### PR TITLE
Cherry-pick of #16135: Added user guide for horizontal pod autoscaler.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Added user guide for horizontal pod autoscaler. Part of #15652.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
@k8s-bot unit test this

**Comment by piosz** [comment]
LGTM

**Comment by jszczepkowski** [comment]
@k8s-bot unit test this

**Comment by jszczepkowski** [comment]
@k8s-bot unit test this

**Pull request merged**
