### PR TITLE
Add damemi to sig-scheduling owners

### PR DESCRIPTION
**Pull request by damemi**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Add @damemi to sig-scheduling reviewers. I have been very active in the scheduling sig, particularly with the framework migration and descheduler, and would like to continue my contributions as a reviewer.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/sig scheduling

### CODE REVIEW

**Comment by ahg-g** [comment]
+1, thanks Mike for your contributions so far, and looking forward for more :)

**Comment by damemi** [comment]
Thanks @ahg-g :)
/assign @liggitt

**Comment by Huang-Wei** [comment]
+1 for Mike!

**Comment by ravisantoshgudimetla** [comment]
/lgtm

Thanks Mike for all the help :)

**Pull request merged**
