### PR TITLE
Etcd upgrade test

### PR DESCRIPTION
**Pull request by wojtek-t**
This is supposed to fix etcd v3 upgrades in 1.5 branch.

@krousey @mml

Ref #42247

### CODE REVIEW

**Comment by mml** [comment]
Oh, actually I think there is a way to do this where we bring the cluster up using the 1.5 tarball but run the tests from master.  @krousey may be able to help here.  I think the `SKEW` environment variables we were talking about yesterday are related.

**Comment by wojtek-t** [comment]
> Oh, actually I think there is a way to do this where we bring the cluster up using the 1.5 tarball but run the tests from master. @krousey may be able to help here. I think the SKEW environment variables we were talking about yesterday are related.

To be honest, I would prefer not to mix those things - we want the test to be as simple as possible. And when skew test will turn into play, we may face issues, that will be completely unrelated to etcd v2 & v3.

**Comment by mml** [comment]
Discussed in person.  /lgtm

**Pull request merged**
