### PR TITLE
Make proxy RESTMapper aware

### LINKED ISSUE #4304: apiserver proxy stopped accepting namespaces
The apiserver proxy rewrites links to the form "/proxy/ns/default/...":

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/proxy.go#L162

But this form stopped working recently, seemingly around https://github.com/GoogleCloudPlatform/kubernetes/commit/18609e17062ad4a56c3533f80014299815bfee76. The "/proxy/ns/default/..." form always returns "404: Page Not Found", similar to the problem seen in https://github.com/GoogleCloudPlatform/kubernetes/pull/4283. If you remove "/ns/default" from the URL, it works.

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Fixes #4304  to make proxy smarter about how it builds the prepend path.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
Can someone with a little more knowledge on the usage of proxy prepend path in proxy.Transport validate this?  

I see no issue for v1beta3 style urls where namespace is in the path, but for v1beta1/2 where namespace is a query parameter on input to the proxy, its not clear to me what proxy.Transport will be doing if proxyPrependPath actually has a ?namespace={namespace} in its suffix.

**Comment by derekwaynecarr** [comment]
Aside from the above comment, this fixes a bug where the ApiGroupResolver was hardcoded to always use latest.mapper versus using the mapper that was provided on input to the ApiGroup.

**Comment by derekwaynecarr** [comment]
Looking at this more, I think we need to do either of the following:

1. Modify proxy.Transport support proxyPathPrepend and a new proxyQueryParameters so it can know what query parameters to add/remove in proxyTransport.rewriteUrl.
2. Have all apiversions always encode the scoping parameter in a proxy in the path.

Would like input from others to see if I am missing anything and how to best proceed.

**Comment by derekwaynecarr** [comment]
TestProxyTransport needs a test case that simulates the namespace use case.  Right now, it appears to only operate on minions.

**Comment by enisoc** [comment]
I would much prefer option 2. I suspect that may be what the original code here was trying to do. For a proxy, it doesn't make sense to hijack query params to specify namespace. What if I'm trying to access a resource behind the proxy that uses its own query param called namespace?

**Comment by roberthbailey** [comment]
Assigning to @davidopp.

**Comment by derekwaynecarr** [comment]
@enisoc  

I prefer option 2 as well, but really wish v1beta3 was live to avoid this problem.

**Comment by derekwaynecarr** [comment]
This was fixed in a different PR.

**Pull request closed without merging**
