### PR TITLE
Updating cAdvisor dependency.

### PR DESCRIPTION
**Pull request by vmarmol**
Includes manager and its dependencies. I'm doing this in a separate PR for ease of review. This does not introduce any behavioral change at all. Most of the dependency is unused.

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM

**Comment by nikhiljindal** [comment]
Will merge on green.

**Comment by vmarmol** [comment]
OMG TRAVIS WHY YOU TAKE SO LONG :(

**Comment by bgrant0607** [comment]
Travis is dozens of PRs and builds behind. There were a couple failures on shippable, but not obviously caused but this, and one build passed. Restarted shippable. It looks like shippable fails most of the time, though. :-(

**Comment by bgrant0607** [comment]
Shippable passed.

**Comment by vmarmol** [comment]
Thanks @bgrant0607!

**Pull request merged**
