### PR TITLE
Speed up pkg/volume/csi unit tests

### PR DESCRIPTION
**Pull request by wzshiming**
**What type of PR is this?**
/kind cleanup
/kind flake

**What this PR does / why we need it**:
62s -> 31s

**Which issue(s) this PR fixes**:

xref #98486

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by wzshiming** [comment]
These test cases use global variables, and there is a probability that they will panic in parallel. I shortened the waiting time.

``` log
Previous write at 0x000003ee69e0 by goroutine 28:
  k8s.io/kubernetes/pkg/volume/csi.(*csiPlugin).Init()
      /Users/zsm/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_plugin.go:241 +0x4d9
  k8s.io/kubernetes/pkg/volume.(*VolumePluginMgr).InitPlugins()
      /Users/zsm/go/src/k8s.io/kubernetes/pkg/volume/plugins.go:631 +0x92a
  k8s.io/kubernetes/pkg/volume/testing.newFakeKubeletVolumeHost()
      /Users/zsm/go/src/k8s.io/kubernetes/pkg/volume/testing/volume_host.go:307 +0x559
  k8s.io/kubernetes/pkg/volume/testing.NewFakeKubeletVolumeHostWithCSINodeName()
      /Users/zsm/go/src/k8s.io/kubernetes/pkg/volume/testing/volume_host.go:288 +0x7b0
  k8s.io/kubernetes/pkg/volume/csi.newTestPlugin()
      /Users/zsm/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_plugin_test.go:80 +0x6f3
  k8s.io/kubernetes/pkg/volume/csi.TestAttacherAttach.func1()
      /Users/zsm/go/src/k8s.io/kubernetes/pkg/volume/csi/csi_attacher_test.go:203 +0x147
  testing.tRunner()
      /usr/local/Cellar/go/1.15
```

**Comment by chrishenzie** [comment]
There were concerns about this increasing test flakiness when I lowered this duration previous. [Please see this thread for more context](https://github.com/kubernetes/kubernetes/pull/97499#discussion_r549515029).

**Comment by chrishenzie** [comment]
I suppose we could also try it anyways and then roll it back if we encounter increased flakiness. Any thoughts on this?

**Comment by wzshiming** [comment]
@chrishenzie
The long test time is mainly caused by several failed cases, or we can shorten the waiting time for failed cases alone.

**Comment by chrishenzie** [comment]
@wzshiming I would be more comfortable with a timeout of something like 5 seconds if we want to reduce this. I am working adding exponential backoff and the minimum time it is going to wait before polling is 1 second, which leaves little room if the timeout is set to 2 seconds.

**Comment by wzshiming** [comment]
@chrishenzie 
I think backoff may not greatly reduce the waiting time. I tried to shorten the timeout for failed cases, it only took 31 seconds.

**Comment by chrishenzie** [comment]
Oh I see what you mean, thank you for making this change

/lgtm

**Comment by liggitt** [comment]
any update on getting this approved?

**Comment by wzshiming** [comment]
Rebase, conflict resolution.

**Pull request merged**
