### PR TITLE
Automated cherry pick of #120561: kubeadm: remove reference of

### PR DESCRIPTION
**Pull request by chendave**
Cherry pick of #120561 on release-1.28.

#120561: kubeadm: remove reference of

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve
/triage accepted
/priority critical-urgent

**Comment by neolit123** [comment]
thanks @chendave 

/cc kubernetes/release-managers

**Comment by chendave** [comment]
> All 'parent' PRs of a cherry-pick PR must have one of the "release-note" or "release-note-action-required" labels

seems like a release note is needed for the 'parent' PR, so update the 'parent' PR to have a release note.

**Comment by neolit123** [comment]
> > All 'parent' PRs of a cherry-pick PR must have one of the "release-note" or "release-note-action-required" labels
> 
> seems like a release note is needed for the 'parent' PR, so update the 'parent' PR to have a release note.

no, we merge test PR updates all the time without release notes.
please remove it from the main PR.

**Comment by chendave** [comment]
> please remove it from the main PR.

Done

**Comment by saschagrunert** [comment]
@pacoxu we're about to release the patches for September, we can revisit CP's once they're out :upside_down_face:

**Comment by pacoxu** [comment]
> @pacoxu we're about to release the patches for September, we can revisit CP's once they're out :upside_down_face: 

This fix a critical problem and the release ci informing is failed from last week.

**Comment by pacoxu** [comment]
master-informing:

kubeadm-kinder-upgrade-1-28-latest
kubeadm-kinder-upgrade-addons-before-controlplane-1-28-latest

**Comment by pacoxu** [comment]
/hold

https://github.com/kubernetes/kubeadm/issues/2927#issuecomment-1717837213

**Comment by neolit123** [comment]
> /hold
> 
> [kubernetes/kubeadm#2927 (comment)](https://github.com/kubernetes/kubeadm/issues/2927#issuecomment-1717837213)

no we must still merge this. we don't want k/k/pkg as a dep.

**Comment by pacoxu** [comment]
@saschagrunert since the patch release is out, can we merge this to fix the CI?

**Review by saschagrunert — APPROVED** [review]

**Comment by chendave** [comment]
/test pull-kubernetes-e2e-kind

(irrelevant)

**Pull request merged**
