### PR TITLE
Add quick-verify make rule.

### PR DESCRIPTION
**Pull request by enisoc**
This is useful for humans to run to catch obvious problems before
pushing commits and waiting for CI to run verify checks.

Quick mode only runs a whitelist of verify scripts that are reasonably fast.
I set the initial bar arbitrarily at <10s each on my workstation.

The whole set runs in <30s for me, assuming I had already run `make` and
`hack/godep-restore.sh`. This is compared to the full `make verify`
which takes [I don't know how long because I gave up after 45min].

### CODE REVIEW

**Comment by CaoShuFeng** [comment]
Test OK in my environment.
Thanks.
LGTM

**Comment by cblecker** [comment]
cross-build is currently broken: https://github.com/kubernetes/kubernetes/issues/48887

**Comment by cblecker** [comment]
Looks great. Thanks for this @enisoc !
@kubernetes/sig-contributor-experience-misc: FYI

/lgtm

**Comment by enisoc** [comment]
/assign @ixdy 

for OWNERS review.

**Comment by ixdy** [comment]
/lgtm

nice!

**Pull request merged**
