### PR TITLE
correct the event message in policy_static.go

### PR DESCRIPTION
**Pull request by mysunshine92**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

 /kind cleanup

**What this PR does / why we need it**:
correct the event msg in function NewStaticPolicy

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mysunshine92** [comment]
cc @vishh

**Comment by mysunshine92** [comment]
ping @mattjmcnaughton

**Review by mattjmcnaughton — CHANGES_REQUESTED** [review]
Thanks for your help ensuring all log messages are readable @mysunshine92 :)

In this case, I actually think that "size of %s did not equal %d" is more correct than your proposed change of "size of %s did not equal to %d". So I think I'd recommend leaving this the way it is :)

/hold

**Pull request closed without merging**
