### PR TITLE
Preserve metadata for fake dynamic client unstructured lists

### LINKED ISSUE #107277: go-client/dynamic/fake does not allow faking pagination
### What happened?

The fake dynamic client does not support mock pagination or the self link.

### What did you expect to happen?

Add ability to propagate the metadata fields from a mock unstructured list to the served list by the fake lister.

### How can we reproduce it (as minimally and precisely as possible)?

Repro linked in the MR x-ref.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Cloud provider

N/A

### OS version

N/A

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
N/A
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

### PR DESCRIPTION
**Pull request by harsimranmaan**
Signed-off-by: Harsimran Singh Maan <maan.harry@gmail.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Adds ability to mock the continue and other metadata fields in the fake dynamic client
#### Which issue(s) this PR fixes:

Fixes #107277

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by harsimranmaan** [comment]
Hi @deads2k, looking forward to getting this reviewed.

**Comment by lavalamp** [comment]
Sorry it looks like this got dropped. I would remove the SelfLink item since that's deprecated and will be removed everywhere soonish. I can lgtm if you do that.

**Comment by lavalamp** [comment]
(also next time please feel free to reach out on slack if it's been a few days)

**Comment by harsimranmaan** [comment]
Hi @lavalamp, this is ready for review again. Addressed comments

**Pull request merged**
