### PR TITLE
e2e_node: consolidated NFSServer APIs.

### PR DESCRIPTION
**Pull request by bart0sh**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Consolidate NFSServer APIs.
This is a follow up for the https://github.com/kubernetes/kubernetes/pull/128066

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

/sig-node
/cc @SergeyKanzhelev @pacoxu

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Comment by bart0sh** [comment]
@pacoxu @kannon92 Can you suggest which jobs to trigger to test changes in the kubelet.go?

**Comment by bart0sh** [comment]
/cc @jsafrane 
can you take a look?

**Comment by kannon92** [comment]
/test pull-kubernetes-node-crio-cgrpv2-e2e

Looking at this I see MirrorPods as node conformance.

**Review by SergeyKanzhelev — COMMENTED** [review]
/lgtm

already approved before. Re-lgtm-ing

**Comment by bart0sh** [comment]
/triage accepted
/priority important-longterm

/assign @SergeyKanzhelev @mrunalp 
for approval

**Pull request merged**
