### PR TITLE
Remove azure/ubuntu/saltstack getting-started-guide and kube-up code

### LINKED ISSUE #7826: azure: waiting for cluster initialization
Following the instructions on https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/azure.md, cluster/kube-up.sh creates the VMs but hangs forever at "waiting for cluster initialization". 

I can see the master and minion VMs are all up and running, but it looks like kubernetes cannot reach the APIs. Is this a known issue? What's the best way to investigate?

### PR DESCRIPTION
**Pull request by mikedanese**
Won't fix #7826 #6966

### CODE REVIEW

**Comment by mikedanese** [comment]
This setup hasn't worked sine before 1.0 @bgrant0607 @roberthbailey

**Comment by roberthbailey** [comment]
LGTM.

**Comment by bgrant0607** [comment]
LGTM, also

**Comment by erictune** [comment]
LGTM, thanks

**Comment by bgrant0607** [comment]
This still needs to be cherrypicked. Unfortunately, the automatic cherrypick gets conflicts. Haven't investigated why yet.

**Comment by bgrant0607** [comment]
Cherrypick: #16518

**Pull request merged**
