### PR TITLE
Add OWNERS for staging and api

### PR DESCRIPTION
**Pull request by smarterclayton**
Part of #44420

* api/ is a copy of pkg/api (same reasoning)
* staging/ is the set of people who should be allowing new top level nested packages + the set of people who can change the staging machinery code

Open to changes to staging/ - very rarely changed.  Added owners for the other items

### CODE REVIEW

**Comment by smarterclayton** [comment]
@kubernetes/api-approvers @kubernetes/sig-api-machinery-misc adding OWNERS for staging/, api/, and staging/src/k8s.io/apimachinery/ based on similar roles in other packages.  Please comment.

**Comment by dchen1107** [comment]
Look good to me. Just one concern on how to make sure we do have the representative from the node on the package of api? Can we make sure bot can request proper reviewers from the node team on some of the API objects, like Pod, Node, etc.

**Comment by smarterclayton** [comment]
Sure - probably should identify who that is and put them on both api and pkg/api

**Comment by dchen1107** [comment]
I nominate this group of engineers representing the node related API: @derekwaynecarr (focusing on the resource management), @yujuhong (focusing on application lifecycle and management), @vishh (focusing on resource management), @timstclair (focusing on the monitoring and security for now) and myself as the catchall for now?

**Comment by thockin** [comment]
I am happy with my assigned roles.

**Comment by smarterclayton** [comment]
That's a lot of API approvers :)

**Comment by smarterclayton** [comment]
Or were those just reviewers with yourself as the catchall approver?

**Comment by vishh** [comment]
@smarterclayton in the absence of a means to further narrow the approval scope, it would be helpful if everyone in @dchen1107's list had approver permissions. 
Each of us work on and own various parts of the Node and Resource Management related APIs.

**Comment by dchen1107** [comment]
@smarterclayton I am not proposing to add anyone in that group to the approver including myself. I just want to make sure one of them should be the reviewer for the corresponding node related API changes. But I am not sure if the current mechanism can enforce that.

**Comment by smarterclayton** [comment]
We can't do magic, but all named folks are in the reviewers list for api and pkg/api.

**Comment by smarterclayton** [comment]
As far as magic we should probably open a contrib-x issue if we want to expand the OWNER bot for that.

**Comment by smarterclayton** [comment]
Other comments?

**Comment by brendandburns** [comment]
@k8s-bot cvm gce e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot cvm gce e2e test this

**Comment by smarterclayton** [comment]
No other comments, merging (based on general laziness)

**Pull request merged**
