### PR TITLE
Reorganize kubelet tree so apis can be independently versioned

### PR DESCRIPTION
**Pull request by mtaufen**
@yujuhong @lavalamp @thockin @bgrant0607 
This is an example of how we might reorganize `pkg/kubelet` so the apis it exposes can be independently versioned. This would also provide a logical place to put the `KubeletConfiguration` type, which currently lives in `pkg/apis/componentconfig`; it could live in e.g. `pkg/kubelet/apis/config` instead.

Take a look when you have a chance and let me know what you think. The most significant change in this PR is reorganizing `pkg/kubelet/api` to `pkg/kubelet/apis`, the rest is pretty much updating import paths and `BUILD` files.

### CODE REVIEW

**Comment by mtaufen** [comment]
@yujuhong @lavalamp @thockin @bgrant0607

PTAL, I'd like to get some feedback on this and move it forward, it's a key part of dynamic config related refactoring.

One suggestion which Brian had, which I agree with, is to make it explicitly clear via the tree structure which APIs are intended for REST endpoints and which are not.

I propose:
- `pkg/kubelet/apis/rest/`
- `pkg/kubelet/apis/local/`
as an initial set of TLDs to make this distinction.

**Comment by thockin** [comment]
re "rest" vs "local" - those don't convey anything.  One is a style, the
other is a scope.  You can have local REST APIs and non-local, non-REST.
 what is the intention of the APIs that are being distinguished?

**Comment by thockin** [comment]
This at least seems consistent, but the need for all of these to be under one directory seems artificial.

Anyway, I am removed from this code, but it seems OK..

**Comment by mtaufen** [comment]
I think the concern was about separating types that will be used for REST-style endpoints from types that won't. Since REST is typically across a network boundary (even between servers on the same machine), `local` seemed a good antagonist word - I think the concern is really more about scope than style. 

IMO REST is a style that typically applies to a certain scope, and for that scope we tend to use REST. 

`local` is probably bad because things like configuration types will also live in these trees and those can come from a remote source...

- rest-local
- rest-remote
- non-rest-local
- non-rest-remote

seems to complicated a structure to me.

@bgrant0607 am I concerned about the same thing you were?

**Comment by mtaufen** [comment]
@thockin 
> This at least seems consistent, but the need for all of these to be under one directory seems artificial.

I guess I'd also be ok with e.g. `pkg/kubelet/thing/apis/stuff`. As long as there is an easy way to answer "What are all the APIs exposed by x component?" Grepping to find a canonically-named folder is just as good to me as looking in a canonically-placed and canonically-named folder.

**Comment by thockin** [comment]
I don't think it's a major thing, so you shouldn't get stuck here, but
"what APIs are exposed" is sort of a ridiculous question - everything
visible is an "API".

**Comment by mtaufen** [comment]
Figuring out what's "visible" can be challenging when things are spread all over without a consistent pattern. But yeah, probably not worth getting stuck on this.

**Comment by yujuhong** [comment]
The change to CRI (from `pkg/kubelet/api/runtime` to  `pkg/kubelet/apsi/runtime`) looks good to me. For the others, I don't think kubelet has many external-facing APIs, so I am not expecting too many follow-up moves.

> I think the concern was about separating types that will be used for REST-style endpoints from types that won't. Since REST is typically across a network boundary (even between servers on the same machine), local seemed a good antagonist word - I think the concern is really more about scope than style.

What APIs you have in mind will be categorized as local? I don't think it's very clear from the context, and a few examples will help.
If you intend to use "REST" to represent the scope, why not just use the terms such as remote and local for scope? I'm not sure why we want to include REST in naming of these packages.

**Comment by mtaufen** [comment]
> If you intend to use "REST" to represent the scope, why not just use the terms such as remote and local for scope? I'm not sure why we want to include REST in naming of these packages.

I initially though we were discussing both scope and style for eventual endpoints on components, but I emailed to Brian to get some clarification and it sounds like the concern was really about distinguishing cluster-level APIs from component-level ones, which this PR does by moving component-level APIs to the components' tree. Sorry for the confusion. 

I think the tree structure in this PR will suffice for now. I'll rebase this afternoon or tomorrow.

**Comment by mtaufen** [comment]
Rebased.

**Comment by mtaufen** [comment]
@k8s-bot test this

**Comment by mtaufen** [comment]
Build error that was breaking all the tests is fixed.

@yujuhong, looks like the linter doesn't like the names `RuntimeVersioner` and `RuntimeService` now that the package is called `runtime`. Is there a way to ignore this part of verification, or are you be okay with me changing the names to `Versioner` and `Service`, respectively?

**Comment by mtaufen** [comment]
Rebased again.

**Comment by mtaufen** [comment]
@k8s-bot kops aws e2e test this

**Comment by mtaufen** [comment]
@yujuhong renamed "runtime" pkg to "cri", which hopefully stops golint from being mad

**Comment by mtaufen** [comment]
@yujuhong rebased, PTAL

**Comment by yujuhong** [comment]
LGTM

**Comment by mtaufen** [comment]
rebased

**Comment by mtaufen** [comment]
Was just something I missed in the rebase, reapplying lg

**Comment by mtaufen** [comment]
Fixed linter unhappiness. Utterly trivial, annoying that something like this would block a PR.

**Comment by mtaufen** [comment]
@deads2k, @eparis, @fejta, @ixdy, @madhusudancs, @spxtr, can one of you PTAL and approve for the pieces in `hack/` and `test`?

**Comment by yujuhong** [comment]
@Random-Liu @mrunalp @feiskyer FYI, the path for the CRI api will be changed in this PR.

**Comment by ixdy** [comment]
/approve

for hack and test

**Pull request merged**
