### PR TITLE
Use klog to replace log to keep them in consistence

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Use klog to replace log to keep them in consistence

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

Definitely am in favor of staying constant with how we log and `klog` seems much more prevelent in `devicemanager`.

**Comment by derekwaynecarr** [comment]
/lgtm
/approve

the stub is purely for testing, but consistency is good.

**Pull request merged**
