### PR TITLE
[kubelet] Fix oom-score-adj policy in kubelet

### LINKED ISSUE #32238: Regression in OOM score configuration starting from v1.3+
Kubelet and docker daemon were expected to run with an `oom-score-adj` of `-999` as mentioned [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/qos/policy.go#L25) and [here](https://github.com/kubernetes/kubernetes/blob/master/docs/design/resource-qos.md#oom-score-configuration-at-the-nodes).

This behavior has been broken since v1.3+. I consider this a serious regression because system OOMs will result in kubelet and/or docker daemon getting evicted instead of pod. QoS will essentially be broken at the node level. 

I'm working on a patch to fix this in v1.4 for now. I will then attempt to cherry-pick the patch into v1.3 release branch. 

I will also be adding a test for these settings.

cc @kubernetes/sig-node

### PR DESCRIPTION
**Pull request by vishh**
Docker daemon and kubelet needs to be protected by setting oom-score-adj to -999.
Fixes #32238

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32251)

### CODE REVIEW

**Comment by vishh** [comment]
The tests need some more work. Posting the PR for feedback while I fix the tests.

**Comment by vishh** [comment]
@dchen1107 The tests have been fixed. I verified the fix manually as well. Improved logging along the way. PTAL. This PR is ready to go!

**Comment by dchen1107** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/e2e_node/container_manager_test.go, line 55 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32251#-KRBPSOaz8mIXJLtfbLV:-KRBPSOaz8mIXJLtfbLW:b-3ky61r) ([raw file](https://github.com/kubernetes/kubernetes/blob/71a55a45115363fc7bc8bcaf67ea00d2d2fe51b6/test/e2e_node/container_manager_test.go#L55)):*
> ```Go
> }
> 
> func validateOOMScoreAdjSettingIsInRange(pid int, expectedMinOOMScoreAdj, expectedMaxOOMScoreAdj int32) {
> ```

Can I have one more test case: validate docker's oom_score_adj, then restart docker daemon, revalidate? 

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32251)*

**Comment by vishh** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/e2e_node/container_manager_test.go, line 55 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32251#-KRBPSOaz8mIXJLtfbLV:-KRFy3krd1j4AjI6lSm1:bhfilr0) ([raw file](https://github.com/kubernetes/kubernetes/blob/71a55a45115363fc7bc8bcaf67ea00d2d2fe51b6/test/e2e_node/container_manager_test.go#L55)):*
<details><summary><i>Previously, dchen1107 (Dawn Chen) wrote…</i></summary>
> Can I have one more test case: validate docker's oom_score_adj, then restart docker daemon, revalidate? 
</details>
I tested this manually. Can we unblock this PR and add that test in a subsequent PR? I'm don't have uninterrupted time now to add that to this PR. 

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32251)*

**Comment by dchen1107** [comment]
Ok, could you please file a separate issue for node e2e test too? The test are failed but not due to your pr. 

LGTM

**Comment by vishh** [comment]
@k8s-bot ok to test

**Comment by vishh** [comment]
@k8s-bot test this github issue #IGNORE

**Comment by rmmh** [comment]
@k8s-bot gke test this issue #32431

**Comment by dchen1107** [comment]
@vishh I think some recent test-infra changes completely break builds related to GCI (also coreos).

**Comment by vishh** [comment]
The tests are passing when I run manually. Puzzling.

**Comment by dchen1107** [comment]
LGTM again

**Comment by vishh** [comment]
@dchen1107 This time I have fixed this PR for real. I have improved the tests and reduced the chances of flakes. I have tested manually and fixed an issue along the way. 
PTAL.

**Comment by vishh** [comment]
@k8s-bot test e2e github issue #32548

**Comment by vishh** [comment]
@k8s-bot test e2e github issue #32548

**Comment by eparis** [comment]
@k8s-bot e2e test this issue: #32548

**Comment by pwittrock** [comment]
@vishh This seems pretty risky for this late in the cycle

**Comment by saad-ali** [comment]
Manually merging per @vishh. The failing unit test `etcd TestWatch` appears to be unrelated (https://github.com/kubernetes/kubernetes/issues/32770).

**Comment by eparis** [comment]
I'm not comfortable with it really. Why did we change from using mnt namespace to using pid namespace to determine 'is in container' ? In any case, this does not seem to be fixing something I'd consider a blocker bug. Yes, it stinks if docker get oomed, and it'll render the node pretty much useless, but the system as a whole will recover. This is not a regression vs 1.3. I suggest we either don't fix in 1.4 or we punt to 1.4.1.

**Comment by vishh** [comment]
We have been having this regression since v1.3. It is critical for GKE/GCE deployments of k8s because docker daemon has a high likelihood of being OOM killed which will end up nuking all containers. 
The reason for moving from `mnt` to `pid` is that docker daemon moves itself into a new `mnt` namespace :(

**Comment by vishh** [comment]
@pwittrock This is fixing a scale reliability regression that will be visible to customers. The priority call belongs to you and @eparis.

**Comment by eparis** [comment]
I'm oging to remove the cherrypick-candidate label since this broke master. You can suggest a pick of the replacement, but my fears are not abated.

**Comment by vishh** [comment]
Yeah. SGTM!

**Pull request merged**
