### PR TITLE
fix godeps

### PR DESCRIPTION
**Pull request by mikedanese**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33675)

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
Manually merge the pr to stop the bleeding edge.

**Comment by eparis** [comment]
This broke godep license verification. Which @deads2k fixed in https://github.com/kubernetes/kubernetes/pull/33683
Where is the reference to why this was merged?

**Comment by mikedanese** [comment]
@eparis this fixed ./hack/verify-godeps.sh which was broken. I forgot to test ./hack/verify-godep-licenses.sh.

**Comment by eparis** [comment]
Ok, /me thinks he understands now.

@deads2k removed all of the references to mesos code in https://github.com/kubernetes/kubernetes/pull/33658.
But the verifier doesn't run per PR if there are no changes to Godeps or vendor. 

The continuous verification does the full check and thus found the bug.
This PR half fixed it.
That PR fixed the other half.
We should be back alive.

Not sure a great way to catch this next time. Need a lighter weight way to catch 'Godep/vendor no longer needs an import' without a full re-godep regeneration, which we can run on every PR...

**Comment by mikedanese** [comment]
:+1: this happens every so often. I think we decidedd that it was aneccessary evil. The alternative is to make verification take twice as long on every PR.

**Pull request merged**
