### PR TITLE
addons: update metrics-server to v0.7.1

### PR DESCRIPTION
**Pull request by my-git9**
#### What type of PR is this?

update metrics-server to v0.7.1, as a supplement to PR: https://github.com/kubernetes/kubernetes/pull/125125

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by humblec** [comment]
Thanks.
/lgtm

**Review by mengjiao-liu — COMMENTED** [review]
/lgtm

**Comment by dims** [comment]
/assign @humblec 

@humblec looks like we missed a spot in https://github.com/kubernetes/kubernetes/commit/4b757998a47f81038aaa720303178654792aea52 ?

**Comment by humblec** [comment]
> /assign @humblec
> 
> @humblec looks like we missed a spot in [4b75799](https://github.com/kubernetes/kubernetes/commit/4b757998a47f81038aaa720303178654792aea52) ?

Yes @dims , my mistake 🤦  ..

**Pull request merged**
