### PR TITLE
Don't use command pipes for exec/port forward

### PR DESCRIPTION
**Pull request by ncdc**
Switch to passing the streams for Stdin/Stdout/Stderr instead of using
StdinPipe() etc because the pipes are incompatible with Run()/Wait().

### CODE REVIEW

**Comment by ncdc** [comment]
@smarterclayton PTAL

Oh wait, now I remember why I ended up using StdinPipe etc instead of just command.Stdin = stream. If you run this:

    kubectl exec -p pod -i bash

and type `exit`, the `kubectl exec` CLI just sits there, and the only way to get out is to ctrl-c. If you use StdinPipe, when you type `exit`, you're returned to your host's shell. I guess `os/exec` doesn't know that you're done with stdin.

I can keep digging to see if we can get everything working cleanly without pipes, or we can just say if you type `exit` in a shell that's not using a tty, you have to ctrl-c to get out. Thoughts?

**Comment by ncdc** [comment]
This is a small reproducer that just uses os/exec:

```go
package main
 
import (
  "io"
  "os"
  "os/exec"
)
 
func main() {
  r, w := io.Pipe()
  go io.Copy(w, os.Stdin)
  c := exec.Command("env", "-i", "bash")
  c.Stdin = r
  c.Stdout = os.Stdout
  c.Stderr = os.Stderr
  err := c.Run()
  if err != nil {
    panic(err)
  }
}
```

If you type `exit`, the only way you can get `Run()` to unblock is to hit ctrl-c.

**Comment by ncdc** [comment]
Switching `io.Pipe` to `os.Pipe` yields the desired behavior!

**Comment by smarterclayton** [comment]
Wonder what the downside of os.Pipe is?

**Comment by ncdc** [comment]
@smarterclayton I'll ask around. In the meantime, I've updated this pull to use os.Pipe for stdin

**Comment by smarterclayton** [comment]
According to Mrunal on IRC docker does this as well.  Looking at os/exec this seems the intended path (go has to hand a file descriptor to the process, so callers that need to close the stream on their own recognizance have to give os/exec an OS pipe).

This is LGTM but I want to make sure the Openshift e2e runs a few times to make sure it truly is fixed.

**Comment by smarterclayton** [comment]
Rerunning travis then will merge

**Comment by ncdc** [comment]
Can you kick Shippable too?

**Pull request merged**
