### PR TITLE
kubectl: fix the indentation problem in set env example

### PR DESCRIPTION
**Pull request by Fish-pro**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

kubectl set env example has an indenting problem, this pr optimize it

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Fish-pro** [comment]
> > set env example has an indenting problem
> 
> Can you provide an example of what you're seeing? The current indentation looks fine to me, and seems consistent with the indentation used in the examples for other commands as well.

@KnVerey set_env.go was originally formatted like this, so now change the format
image

**Comment by KnVerey** [comment]
I'm afraid a cosmetic change that does not affect the actual output is not in line with the Kubernetes project's [policy on trivial edits](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits). Feel free to resubmit along with more significant improvements to the file.

/close

**Comment by Fish-pro** [comment]
> I'm afraid a cosmetic change that does not affect the actual output is not in line with the Kubernetes project's [policy on trivial edits](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits). Feel free to resubmit along with more significant improvements to the file.
> 
> /close

Thanks for your reply. Got it

**Pull request closed without merging**
