### PR TITLE
Automated cherry pick of #79534: Fix closing of dirs in doSafeMakeDir

### PR DESCRIPTION
**Pull request by odinuge**
Cherry pick of #79534 on release-1.12.

#79534: Fix closing of dirs in doSafeMakeDir

### CODE REVIEW

**Comment by msau42** [comment]
Are we still doing 1.12 patch releases?

/ok-to-test
/lgtm
/priority important-soon
/kind bug

/assign @jingxu97

**Comment by odinuge** [comment]
That was quick @msau42, thanks!

> Are we still doing 1.12 patch releases?

Made a PR since I had it in the back of my head that I heard something about a release. After double checking my mail, I guess this was the reason (got it 3 hours ago):

```
Kubernetes v1.12.10 release delayed

Due to a couple of release engineering issues (e.g. shellcheck and releaselib failures), we are delaying the Kubernetes v1.12.10 release. We're not sure the length of delay yet, would update the date when we have more details.
```

v1.12.10 is supposed to be the last release, so not 100% sure if they still accept new code... :thinking:

**Comment by odinuge** [comment]
Ref. the mail about `v1.12.10`:

> Please notice that v1.12.10 will be the last patch release for 1.12 branch. If you still have some changes wanted to be cherry-picked, please get it done before the frozen day.

> If your cherrypick PR is still pending (see list below) and you want it to make v1.12.10, make sure it merges by end of next Friday, June 28. Branch release-1.12 will be frozen until v1.12.10 released. Tag me (@_feiskyer) on the issue or on Slack if it appears to be blocked on something out of your control.

Ill just close this.

**Pull request closed without merging**
