### PR TITLE
Cherrypicking versionize-docs fixes

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/kubernetes/kubernetes/issues/15864
Supersedes https://github.com/kubernetes/kubernetes/pull/16057

Commit 1: Automated cherry pick of #16059 and https://github.com/kubernetes/kubernetes/pull/16336 upstream release 1.1 (Fixing versionize docs)
Commit 2: Run versionize-docs
Commit 3: Fix html preview links (add "blob") and IS_VERSIONED tags (remove extra whitespaces) that were broken due to previous bugs in versionize-docs.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @caesarxuchao @thockin @lavalamp

**Comment by caesarxuchao** [comment]
Those definitions/operations.md lgtm. My cherry-pick will fix those without cause conflicts.

**Comment by nikhiljindal** [comment]
Shippable passed for 1.4 but timed out for 1.3
Restarting

**Comment by lavalamp** [comment]
LGTM

**Comment by bgrant0607** [comment]
cc @krousey @janetkuo @RichieEscarez 

LGTM

**Pull request merged**
