### PR TITLE
WIP: wait: Refactor Kube codebase to use new PollUntilContext* methods

### PR DESCRIPTION
**Pull request by smarterclayton**
#107826 introduces two new Poll variants that handle context.Context cancellation consistently with idiomatic go and allow callers to detect cancellation. This PR is a WIP that transforms legacy calls to `Poll*` into the new methods, updates error handling, and generally makes our use of context consistent across the wait package.

It leverages a mechanical [gopatch](https://github.com/uber-go/gopatch) script in `hack/refactors/poll_with_context.patch` that performs the bulk of the transformation, with small prefactor changes and then manual fixups after.

The intent of this PR is to demonstrate the correctness of the new Poll methods in bulk and refine their execution to ensure there are no incorrect behaviors detected. The actual refactor may be performed in smaller chunks as necessary.

/kind cleanup

```release-note
```

```docs
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
/retest

https://storage.googleapis.com/k8s-triage/index.html?test=LoadBalancers%20should%20be%20able%20to%20preserve%20UDP%20traffic%20when%20server%20pod%20cycles%20for%20a%20LoadBalancer%20service%20on%20the%20same%20nodes is a flake outside of this change

**Comment by smarterclayton** [comment]
capz is a flake https://storage.googleapis.com/k8s-triage/index.html?date=2023-02-27&pr=1&text=Kubernetes%20cluster%20unreachable&job=capz#ffa2983f425d65f8b9c2

**Comment by smarterclayton** [comment]
hpa-cm [Details](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/115061/pull-kubernetes-e2e-autoscaling-hpa-cm/1630939007489675264) is a flake https://storage.googleapis.com/k8s-triage/index.html?date=2023-02-27&pr=1&text=429%3A%20Errors%20during%20metric%20descriptor%20creation%3A#755c0633c658b3186e4a and capz is as well.

/test all

**Comment by smarterclayton** [comment]
/retest

all flakes except maybe capz windows (only time it's been seen is my PR, might just be rare or might be a retry loop inconsistency)

**Comment by jsturtevant** [comment]
/remove-sig windows
Add us back if need any input. Thanks!

**Comment by dims** [comment]
This work-in-progress PR needs a rebase. please rebase if this PR is still needed for the upcoming release.

**Pull request closed without merging**
