### PR TITLE
Graduate ElasticIndexedJob to GA

### LINKED ISSUE #114862: Elastic Indexed Job
### What would you like to be added?

Currently we validate that `spec.completions` is set when `completionMode=Indexed` for job. I suggest we relax this validation. 

This will require the following changes:

1) We need to update the job controller to look at `spec.parallelism` instead of `spec.completions` when calculating the range of indexes.
2) When reducing parallelism, we should remove the higher indexes first (otherwise the controller will eventually do that anyways to ensure that the pods have a continuous range).

both changes only apply when `spec.completions=nil`

### Why is this needed?

The use case is jobs with workers that require a form of autoscaling, like Ray, Spark or Horovord. By modeling these as jobs with `spec.completion=nil`, `spec.parallelism` can be used to scale the job.

While such jobs could be modeled as a StatefulSet, the job API offers batch-specific features that makes it a better fit (like [retriable and non retriable failures](https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3329-retriable-and-non-retriable-failures))

/sig apps
@soltysh @alculquicondor wdyt?

### PR DESCRIPTION
**Pull request by ahg-g**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Graduates ElasticIndexedJob to GA

#### Which issue(s) this PR fixes:

Fixes #114862

#### Does this PR introduce a user-facing change?

```release-note
ElasticIndexedJob is graduated to GA
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3715-elastic-indexed-job
```

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Comment by msau42** [comment]
API changes lgtm
/approve

**Comment by ahg-g** [comment]
> API changes lgtm /approve

Thanks @msau42 , it seems we are still missing an approval for the registry pkg.

@liggitt @thockin @smarterclayton any chance you can help with this quick one?

**Pull request merged**
