### PR TITLE
Remove kube-proxy autocleanup for inactive modes

### LINKED ISSUE #75360: Restarting iptables kube-proxier causes connections to fail
**What happened**:
When restarting kube-proxy in iptables mode, there will be several seconds of timeouts because it flushes the KUBE-SERVICES nat chain and several others.

**What you expected to happen**:
Restarting kube-proxy should not impact traffic in any way.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run an HTTP server behind a ClusterIP service
2. Run an http client in a loop making requests to the HTTP server
3. kill -15 the kube-proxy process on the client node
4. Connections timeout for a few seconds until kube-proxy re-syncs the iptables rules

**Anything else we need to know?**:
Running with `-v=6` makes it pretty clear what's happening:
```
I0314 05:35:28.808656       7 server_others.go:174] Tearing down inactive rules.
I0314 05:35:28.808673       7 iptables.go:419] running iptables -C [OUTPUT -t nat -m comment --comment handle ClusterIPs; NOTE: this must be before the NodePort rules -j KUBE-PORTALS-HOST]
I0314 05:35:28.812934       7 iptables.go:419] running iptables -C [PREROUTING -t nat -m comment --comment handle ClusterIPs; NOTE: this must be before the NodePort rules -j KUBE-PORTALS-CONTAINER]
I0314 05:35:28.816683       7 iptables.go:419] running iptables -C [OUTPUT -t nat -m addrtype --dst-type LOCAL -m comment --comment handle service NodePorts; NOTE: this must be the last rule in the chain -j KUBE-NODEPORT-HOST]
I0314 05:35:28.821715       7 iptables.go:419] running iptables -C [PREROUTING -t nat -m addrtype --dst-type LOCAL -m comment --comment handle service NodePorts; NOTE: this must be the last rule in the chain -j KUBE-NODEPORT-CONTAINER]
I0314 05:35:28.825080       7 iptables.go:419] running iptables -C [INPUT -t filter -m comment --comment Ensure that non-local NodePort traffic can flow -j KUBE-NODEPORT-NON-LOCAL]
I0314 05:35:28.826834       7 iptables.go:419] running iptables -F [KUBE-PORTALS-CONTAINER -t nat]
I0314 05:35:28.830456       7 iptables.go:419] running iptables -F [KUBE-PORTALS-HOST -t nat]
I0314 05:35:28.833272       7 iptables.go:419] running iptables -F [KUBE-NODEPORT-HOST -t nat]
I0314 05:35:28.836361       7 iptables.go:419] running iptables -F [KUBE-NODEPORT-CONTAINER -t nat]
I0314 05:35:28.839093       7 iptables.go:419] running iptables -F [KUBE-NODEPORT-NON-LOCAL -t filter]
I0314 05:35:28.840088       7 iptables.go:419] running iptables -C [OUTPUT -t nat -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I0314 05:35:28.843330       7 iptables.go:419] running iptables -D [OUTPUT -t nat -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I0314 05:35:28.847852       7 iptables.go:419] running iptables -C [PREROUTING -t nat -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I0314 05:35:28.850976       7 iptables.go:419] running iptables -D [PREROUTING -t nat -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I0314 05:35:28.855081       7 iptables.go:419] running iptables -C [POSTROUTING -t nat -m comment --comment kubernetes postrouting rules -j KUBE-POSTROUTING]
I0314 05:35:28.857992       7 iptables.go:419] running iptables -D [POSTROUTING -t nat -m comment --comment kubernetes postrouting rules -j KUBE-POSTROUTING]
I0314 05:35:28.862013       7 iptables.go:419] running iptables -F [KUBE-SERVICES -t nat]
I0314 05:35:28.865648       7 iptables.go:419] running iptables -X [KUBE-SERVICES -t nat]
I0314 05:35:28.869143       7 iptables.go:419] running iptables -F [KUBE-POSTROUTING -t nat]
I0314 05:35:28.872606       7 iptables.go:419] running iptables -X [KUBE-POSTROUTING -t nat]
I0314 05:35:29.159612       7 server.go:444] Version: v1.10.11
```
it says it's cleaning up inactive rules, but these are crucial to the iptables proxier. You can trivially reproduce by just running:
```
iptables -F KUBE-SERVICES -t nat
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.11
- Cloud provider or hardware configuration: amazon
- OS (e.g: `cat /etc/os-release`): custom
- Kernel (e.g. `uname -a`): 4.14.77-hs623.el6.x86_64
- Install tools: custom
- Others: iptables 1.6.2

We're running kube-proxy 1.10.11, but I've confirmed this issue with kube-proxy 1.13.4 too

### LINKED ISSUE #75408: Remove kube-proxy's automatic clean up logic
**What would you like to be added**:
Remove any logic in kube-proxy that tries to automatically clean up proxy rules based on the proxy mode. Only attempt to clean up if `--cleanup` is set.

**Why is this needed**:
This is a continuation of a discussion from https://github.com/kubernetes/kubernetes/pull/75377. There's a lot of complexity that comes with switching the proxy mode on kube-proxy because it tries to delete proxy rules created from other proxy modes. This has a lot of side-effects and we should be encouraging users to reboot thier nodes along with switching proxy modes. One example of this can be found https://github.com/kubernetes/kubernetes/issues/75360.

### PR DESCRIPTION
**Pull request by vllry**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
kube-proxy attempts to clean up network rules for other modes (EG cleaning up iptables rules when running in IPVS mode). The complexity of this code is prone to bugs, and can delay kube-proxy's readiness between restarts.

This PR [see KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190324-remove-kube-proxy-autocleanup.md) aims to remove auto-cleanup logic for non-current kube-proxy modes. In other words, kube-proxy will only automatically clean up rules relevant to its current mode. Users should use `--cleanup` or restart the node when switching between kube-proxy modes.

**Which issue(s) this PR fixes**:
Fixes #75408 (tracking issue)
Fixes #75360 (bug caused by auto-cleanup)

**Special notes for your reviewer**:
Worth discussing if we gate this behavior with a flag (EG `--only-clean-current-mode`), or outright GA. Outright GA is currently the plan.

**Does this PR introduce a user-facing change?**:
```release-note
kube-proxy no longer automatically cleans up network rules created by running kube-proxy in other modes. If you are switching the mode that kube-proxy is in running in (EG: iptables to IPVS), you will need to run `kube-proxy --cleanup`, or restart the worker node (recommended) before restarting kube-proxy.

If you are not switching kube-proxy between different modes, this change should not require any action.
```

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
I keep looking for something missing here, but I can't find it.

We should fix the description in cmd/kube-proxy/app/server.go on the cleanup-ipvs flag: "cleanup ipvs rules before running" is no longer true, right?

Otherwise LGTM

**Comment by vllry** [comment]
> We should fix the description in cmd/kube-proxy/app/server.go on the cleanup-ipvs flag: "cleanup ipvs rules before running" is no longer true, right?

Correct, I'll fix that.

We also need docs changes, which I have no idea how to coordinate.

**Comment by thockin** [comment]
Docs are in a different repo, so there's no coordination per se.  You make
a doc PR, it gets targetted at the 1.15 release.

**Comment by andrewsykim** [comment]
Even though it's implied, I think the release note should say something about `--cleanup-ipvs` being deprecated and no longer having any effect. Should we also mark the release note for this as "action required" since we are being more explicit about users either setting `--cleanup` or rebooting nodes during a proxy mode switch? cc v1.14 patch release team @aleksandra-malinowska  @spiffxp @tpepper

**Comment by thockin** [comment]
`--cleanup-ipvs` still has meaning.  In IPVS mode `--cleanup` means
"do low-impact cleanup and exit" while `--cleanup --cleanup-ipvs`
means "do full cleanup and exit"

**Comment by andrewsykim** [comment]
> In IPVS mode `--cleanup` means "do low-impact cleanup and exit" while `--cleanup --cleanup-ipvs` means "do full cleanup and exit"

Sorry if I'm missing something, but I'm not seeing the changes in this PR reflect this 🤔 

/hold

**Comment by thockin** [comment]
This was always the case.  Grep around for CleanupIPVS  :)

I did this in reviewing, but maybe I made mistakes - please feel free to
double-check me.

**Comment by andrewsykim** [comment]
Agreed that this was always the case, I meant to say that this PR changes that, see this diff https://github.com/kubernetes/kubernetes/pull/76109/files#diff-97649d13432b01b4e7669d728a2e2e82.

**Comment by andrewsykim** [comment]
Agreed that this was always the case, I meant to say that this PR changes that, see this diff https://github.com/kubernetes/kubernetes/pull/76109/files#diff-97649d13432b01b4e7669d728a2e2e82. Is this desired or did we still want to preserve the behavior from --cleanup-ipvs?

**Comment by vllry** [comment]
I made the assumption that `--cleanup` should always do a full cleanup, by comparing to the `--cleanup-iptables` depreciation. I think making `--cleanup` do full cleanup makes the most sense. `--cleanup --cleanup-ipvs=false` seems like a weird scenario.

**Comment by andrewsykim** [comment]
> I made the assumption that --cleanup should always do a full cleanup, by comparing to the --cleanup-iptables depreciation. I think making --cleanup do full cleanup makes the most sense. --cleanup --cleanup-ipvs=false seems like a weird scenario.

I agree with this, but I'm realizing now that this changes the scope of what --cleanup is cleaning and we may need to keep `--cleanup-ipvs` to preserve that

**Comment by vllry** [comment]
I'm fine with keeping it and kicking that can down the road. @thockin you're in agreement?

**Comment by thockin** [comment]
It was added for a reason, even if that reason is unclear.  We should
probably just keep that behavior.

**Comment by vllry** [comment]
Gotcha. I'll push up a change shortly, have to run to a meeting.

**Comment by vllry** [comment]
@thockin @andrewsykim issues resolved + tests finally passed, we're good to go.

**Comment by ravilr** [comment]
@vllry @andrewsykim can this be cherry-picked to release-1.13 also please?

**Pull request merged**
