### PR TITLE
Stop the bleeding of long latency of POST pods

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #22340

### CODE REVIEW

**Comment by wojtek-t** [comment]
@derekwaynecarr @lavalamp @davidopp - FYI

**Comment by wojtek-t** [comment]
@k8s-bot test this please github issue: #IGNORE [verifying that this PR is safe to merge]

**Comment by wojtek-t** [comment]
@k8s-bot test this please github issue: #IGNORE [verifying that this PR is safe to merge]

**Comment by wojtek-t** [comment]
@k8s-bot test this please github issue: #IGNORE

**Comment by wojtek-t** [comment]
Merging manually to help with failures.

**Comment by lavalamp** [comment]
LGTM

**Pull request merged**
