### PR TITLE
[WIP] Update vendored dependency hcsshim to v0.8.7

### PR DESCRIPTION
**Pull request by dims**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
we are using a commit SHA for hcsshim, let's switch over to a release tag

previously filed and closed in https://github.com/kubernetes/kubernetes/pull/86949, not sure why

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
It has been a long time since the last version update, some bugs were fixed in the middle, and a new version was finally released recently
https://github.com/microsoft/hcsshim/releases/tag/v0.8.7 ( note from @wawa0210 )

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
cc @PatrickLang

**Comment by wawa0210** [comment]
What confuses me a lot is that many dependencies of the microsoft / hcsshim repository and many dependencies of kubernetes are inconsistent versions, so I closed my pr before

**Comment by wawa0210** [comment]
https://github.com/containerd/containerd/pull/3946

**Pull request closed without merging**
