### PR TITLE
ability to run a local command with port-forward

### LINKED ISSUE #97549: Support exec in `kubectl port-forward`
**What would you like to be added**:
Ability to run a local command with port-forward. Example of use-case:

```bash
kubectl port-forward service/postgres 5432 -- psql -h localhost -p 5432 -c "select 1"
```

That would:

1. Start port-forwarding;
2. Execute the provided command. It will have access to the port
3. When the command returns, `kubectl` itself returns with the status code from the provided command.

For some cases we might need more than one port. Currently we have to use two instances of `kubectl port-forward`, but this approach won't work for the proposed feature. Ideally we would need the ability to port-forward multiple ports. If this is not trivial to implement, it would be fine to leave it for a future feature.

**Why is this needed**:
This would allow scripting around port-forwarding. That will be specially useful for developers, but can also be useful in production. Currently we can do that, but we have to use one terminal to create the port-forwarding, use another to run any tool that uses the port, then finally go back to the first terminal and terminate the forwarding. This is not _scriptable_.

### PR DESCRIPTION
**Pull request by carlory**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This would allow scripting around port-forwarding. That will be especially useful for developers, but can also be useful in production. Currently, we can do that, but we have to use one terminal to create the port-forwarding, use another to run any tool that uses the port, then finally go back to the first terminal and terminate the forwarding. This is not scriptable.

**Which issue(s) this PR fixes**:

Fixes #97549

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Support exec in `kubectl port-forward`. For example, kubectl port-forward service/postgres 5432 -- psql -h localhost -p 5432 -c "select 1"
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by carlory** [comment]
Example:

```shell
➜  kubernetes git:(feature-kubectl-port-forward) ✗ _output/bin/kubectl -n ruyicloud port-forward backend-mysql-55c8958756-b6sh2 3306 -- mysql -h 127.0.0.1 -uroot -p
Forwarding from 127.0.0.1:3306 -> 3306
Forwarding from [::1]:3306 -> 3306
Enter password:
Handling connection for 3306
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 18
Server version: 5.7.22 MySQL Community Server (GPL)

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| ruyicloud          |
| ruyicls            |
| sys                |
+--------------------+
6 rows in set (0.21 sec)

mysql> exit
Bye
```

**Comment by FranciscoKurpiel** [comment]
@carlory, while trying your PR I come up with a few considerations regarding the standard streams (stdin/oiut/err). I described the considerations [here](https://github.com/kubernetes/kubernetes/issues/97549#issuecomment-753929842) the original ticket, so that they can be taken into consideration for the consideration on sig.

**Comment by carlory** [comment]
@FranciscoKurpiel 

Thanks for your guide. It is a good idea. I will try to implement it this week.

**Comment by carlory** [comment]
@FranciscoKurpiel suppress `kubectl` is implemented.

Example:

```shell
➜  kubernetes git:(feature-kubectl-port-forward) ./_output/bin/kubectl port-forward -q backend-mysql-55c8958756-b6sh2 3306 -- mysql -h 127.0.0.1 -uroot -pdangerous
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 21
Server version: 5.7.22 MySQL Community Server (GPL)

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> exit
Bye
```

**Comment by carlory** [comment]
There is still a problem to be considered here.

If during the execution of the local command, the goroutine responsible for forwarding the network traffic exits suddenly, immediately returns the error of the goroutine, and exit the executing command, is it really reasonable?

```golang
go func() {
 	errChan <- o.PortForwarder.ForwardPorts("POST", req.URL(), o)
 }()
```

It may be a good idea to only print the port-forwarder errors to `stderr` without interrupting the execution of the local command. 

@FranciscoKurpiel  Any idea about it?

**Comment by FranciscoKurpiel** [comment]
> If during the execution of the local command, the goroutine responsible for forwarding the network traffic exits suddenly, immediately returns the error of the goroutine, and exit the executing command, is it really reasonable?

That should be handled a _broken pipe_, we should send a `SIGPIPE`. Unfortunately there might be some platform-specific details there.

I'm just a bit worried with the fact that we are moving quite a lot before the ticket being accepted or discussed on the sig. I provided the ticket and I'm providing my input, but the actual specification will come from the special group.

**Pull request closed without merging**
