### PR TITLE
Automated cherry pick of #18032 #18173 upstream release 1.1

### PR DESCRIPTION
**Pull request by mikedanese**

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by zmerlynn** [comment]
Kermity, merging.

**Comment by a-palchikov** [comment]
There's a typo at https://github.com/kubernetes/kubernetes/blob/v1.1.3/pkg/version/semver.go#L47: should be `gitversion`

**Pull request merged**
