### PR TITLE
kubeadm: add front-proxy CA certificate to selfhosting controller-manager

### LINKED ISSUE #1281: Selfhosting pivoting fails when using --store-certs-in-secrets
`kubeadm alpha selfhosting pivot` (kubeadm v1.13.0-beta.2) fails when invoked with `--store-certs-in-secrets` with the following error message:

```bash 
[pivot] pivoting cluster to self-hosted
[self-hosted] Created TLS secret "ca" from ca.crt and ca.key
[self-hosted] Created TLS secret "apiserver" from apiserver.crt and apiserver.key
[self-hosted] Created TLS secret "apiserver-kubelet-client" from apiserver-kubelet-client.crt and apiserver-kubelet-client.key
[self-hosted] Created TLS secret "sa" from sa.pub and sa.key
[self-hosted] Created TLS secret "front-proxy-ca" from front-proxy-ca.crt and front-proxy-ca.key
[self-hosted] Created TLS secret "front-proxy-client" from front-proxy-client.crt and front-proxy-client.key
[self-hosted] Created secret for kubeconfig file "scheduler.conf"
[self-hosted] Created secret for kubeconfig file "controller-manager.conf"
[apiclient] Found 1 Pods for label selector k8s-app=self-hosted-kube-apiserver
timed out waiting for the condition
```

### PR DESCRIPTION
**Pull request by bart0sh**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Selfhosting pivoting fails when using --store-certs-in-secrets
as controller-manager fails to start because of missing front-proxy CA
certificate:
```
    unable to load client CA file: unable to load client CA file: open
    /etc/kubernetes/pki/front-proxy-ca.crt: no such file or directory
```

Added required certificate to fix this.

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#1281

**Does this PR introduce a user-facing change?**:
```release-note
kubeadm: fixed storing of front-proxy certificate in secrets required by kube-controller-manager selfhosting pivoting
```

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
thanks for the PR @bart0sh 
/assign @fabriziopandini

**Review by fabriziopandini — APPROVED** [review]
@bart0sh 
Thanks for your awesome work on self-hosting!
/approve
/lgtm

**Pull request merged**
