### PR TITLE
Automated cherrypick of #55320 and #49840 for release-1.8

### PR DESCRIPTION
**Pull request by andrewrynhard**
**What this PR does / why we need it**:
Cherry-picks #55320 and #49840
Fixes a bug that affects CoreOS machines where `/usr/lib` isn't writable and 

**Release note**:

```release-note
Fixe a bug in kubeadm on CoreOS and expose the option to define extra volume mounts
```
/cc @luxas

### CODE REVIEW

**Review by luxas — APPROVED** [review]
/lgtm

cc @jpbetz for inclusion in the next v1.8 patch release

/assign @timothysc 
for an other review as well

**Comment by luxas** [comment]
@andrewrynhard this needs a rebase

**Comment by timothysc** [comment]
poke me on slack when the tests are green.

**Comment by dims** [comment]
/hold

run away bot!

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/55955)

**Comment by andrewrynhard** [comment]
Failing due to unrelated change

```
$ go test
# k8s.io/kubernetes/cmd/kube-apiserver/app
../server.go:378:70: undefined: "k8s.io/kubernetes/pkg/generated/openapi".GetOpenAPIDefinitions
FAIL	k8s.io/kubernetes/cmd/kube-apiserver/app/testing [build failed]
```

**Pull request closed without merging**
