### PR TITLE
fix(*): display the diff as new-old

### LINKED ISSUE #103034: Unclear errors message when update pod spec
#### What happened:

1. create pod with nodeSeletor
2. kubectl edit pod, delete the nodeSeletor field
3. kubernetes report error with:

image

#### What you expected to happen:

The errors message should displayed as:

```
+ NodeSeletor: nil,
- NodeSeletor: map,
```

Because the nodeSeletor is been deleted with this edit.

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by lsytj0413**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #103034 

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
Some put new first and some put old first in `pkg/apis/core/validation/validation.go`.
```
 1946: 		pvcSourceDiff := diff.ObjectDiff(newPv.Spec.PersistentVolumeSource, oldPv.Spec.PersistentVolumeSource)
 2060: 			specDiff := diff.ObjectDiff(newPvcClone.Spec, oldPvcClone.Spec)
 2071: 			specDiff := diff.ObjectDiff(newPvcClone.Spec, oldPvcClone.Spec)
 4045: 		specDiff := diff.ObjectDiff(oldPod.Spec, mungedPodSpec)
 4143: 			specDiff := diff.ObjectDiff(old, *new)
```

**Review by pacoxu — COMMENTED** [review]
Why do you change to use `cmp.Diff`? Why not just change the order? 
`specDiff := diff.ObjectDiff(oldPod.Spec, mungedPodSpec)`
Before
```
- NodeSeletor: change-to-value,
+ NodeSeletor: current-value,
```
After
```
+ NodeSeletor: change-to-value,
- NodeSeletor: current-value,
```

**Comment by lsytj0413** [comment]
> Why do you change to use `cmp.Diff`? Why not just change the order?
> `specDiff := diff.ObjectDiff(oldPod.Spec, mungedPodSpec)`
> Before
> 
> ```
> - NodeSeletor: change-to-value,
> + NodeSeletor: current-value,
> ```
> 
> After
> 
> ```
> + NodeSeletor: change-to-value,
> - NodeSeletor: current-value,
> ```

https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/apimachinery/pkg/util/diff/diff.go#L56

ObjectDiff has been marked as DEPRECATED and the cmp pkg is recommend.

**Review by ravisantoshgudimetla — COMMENTED** [review]
Thank you for the PR @lsytj0413 

Can you make the change across the validation package atleast before we proceed further instead of touching just this file?

**Comment by lsytj0413** [comment]
> Thank you for the PR @lsytj0413
> 
> Can you make the change across the validation package atleast before we proceed further instead of touching just this file?

ok，i will walk through the whole validation pkg to make sure this.

**Comment by lsytj0413** [comment]
> Thank you for the PR @lsytj0413
> 
> Can you make the change across the validation package atleast before we proceed further instead of touching just this file?

Have walk through the whole validation package，and fix it：
```
grep 'ObjectDiff' ./*
```
show nothing.
PTAL

**Review by soltysh — APPROVED** [review]
/ok-to-test
/priority backlog
/triage accepted
/lgtm
/assign @liggitt 
for approval

**Pull request merged**
