### PR TITLE
 Add missing table converters for server side printing 

### LINKED ISSUE #60488: Server side print returns generic information for deployments
/kind bug

**What happened**:
`kubectl get deploy --experimental-server-print` returns only name and creation timestamp.

**What you expected to happen**:
The server side print should return columns exactly the same as regular print we have right now.

/sig cli
/assign soltysh

### PR DESCRIPTION
**Pull request by soltysh**
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #60488

/assign @smarterclayton @juanvallejo 
/kind bug

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by soltysh** [comment]
Fixed the handlers that failed in the unit tests.

**Review by juanvallejo — APPROVED** [review]

**Comment by juanvallejo** [comment]
lgtm
@soltysh thanks for writing these tests.
Although not particularly specific to this PR, we should also test service service-catalog resources with Table printers. I have made a [note of this here](https://github.com/kubernetes/kubernetes/pull/55637#issue-152354172).

**Comment by soltysh** [comment]
> Although not particularly specific to this PR, we should also test service service-catalog resources with Table printers. I have made a note of this here.

@juanvallejo I've added ^ to https://github.com/kubernetes/kubernetes/issues/58536. We need to review that and mark what's done and what needs to be done in 1.11.

**Pull request merged**
