### PR TITLE
Automated cherry pick of #67298: Log real file's name and line

### PR DESCRIPTION
**Pull request by sylr**
Cherry pick of #67298 on release-1.10.

#67298: Log real file's name and line

### CODE REVIEW

**Comment by sttts** [comment]
@soltysh approved?

**Review by soltysh — APPROVED** [review]
/approve

**Comment by soltysh** [comment]
I might not be in 1.10 approvers so I'm adding this label manually.

**Comment by sttts** [comment]
/assign @MaciekPytel

For 1.10 release approval.

**Pull request merged**
