### PR TITLE
remove gcloud docker on image pushes

### PR DESCRIPTION
**Pull request by mikedanese**
docker handles this now and it raises an error.

cc @mattmoor 

```release-note
NONE
```

### CODE REVIEW

**Comment by mattmoor** [comment]
@dekkagaijin FYI

**Comment by thockin** [comment]
How does docker know how to auth?

**Comment by dekkagaijin** [comment]
> docker handles this now and it raises an error.

What's the error? Do you have `docker-credential-gcr` installed, along with gcloud? In that case, I'd opt for `gcloud (beta) auth configure-docker` to use the `gcloud`-specific cred helper, which doesn't complain when you use `gcloud docker` on top of it (though, naked `docker` is still preferable in that circumstance).

**Comment by mikedanese** [comment]
Specifically:

> 'gcloud docker' is unnecessary when using docker-credential-gcr, use 'docker' instead

```
$ gcloud docker -- push gcr.io/mikedanese-k8s/kube-addon-manager:latest
ERROR: Docker CLI operation failed:

WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error saving credentials: error storing credentials - err: exit status 1, out: `docker-credential-gcr/helper: this operation is unsupported for GCR, please see docker-credential-gcr documentation for supported login methods. 'gcloud docker' is unnecessary when using docker-credential-gcr, use 'docker' instead.`

ERROR: (gcloud.docker) Docker login failed.
$ docker push gcr.io/mikedanese-k8s/kube-addon-manager:latest   
The push refers to a repository [gcr.io/mikedanese-k8s/kube-addon-manager]
29ccd645c54c: Mounted from google-containers/kube-addon-manager 
b62790691c1b: Mounted from google-containers/kube-addon-manager 
0ece55f988c0: Mounted from google-containers/kube-addon-manager 
5f81dce9052f: Mounted from google-containers/kube-addon-manager 
a79963220c40: Mounted from google-containers/kube-addon-manager 
66992ab3e65c: Mounted from google-containers/kube-addon-manager 
cd7100a72410: Layer already exists 
latest: digest: sha256:2d5150f3bf0c0396d9b5b3776424c7527e8de52c6b0a63f328649b07fa6c783b size: 1784
```

**Comment by mikedanese** [comment]
@thockin no idea :) i just read error messages and do what I'm told. @dekkagaijin can you shed some light on why we are seeing that message?

**Comment by dekkagaijin** [comment]
@mikedanese `gcloud docker` was a hack that was made unnecessary by the advent of credential helpers/stores in `docker` versions 1.11 and 1.13, respectively. `docker-credential-gcr` and `docker-credential-gcloud` are meant to supersede `gcloud docker`, with the former being completely standalone and the latter being shipped with `gcloud`. Running `docker-credential-gcr configure-docker` or `gcloud auth (beta) configure-docker` will configure `docker` to use the respective helpers as auth sources. In both cases, `gcloud docker` will fail to inject credentials for the [default GCR registries](https://cloud.google.com/sdk/gcloud/reference/docker), but `docker-credential-gcloud` does so silently. A few weeks ago, a change in a newer version of `docker` broke `gcloud docker` and it was decided that a usability hack would be eliminated in order to simplify `gcloud docker`'s compatibility matrix logic in order to correct the bug. This ended up resulting in cases which were previously no-ops to be... ops... and for this error to be surfaced.

Why does `docker-credential-gcr` throw an error when attempting to store credentials for a default registry? It's already difficult enough for users to debug auth issues, made doubly so when they can't easily determine where their credentials are drawn from user-side. Silently failing with `gcloud docker` + `docker-credential-gcr` would make it so that users are thinking that they're using `gcloud` to authenticate, when instead `docker-credential-gcr` is performing its own search for an `access_token`.

**Comment by mikedanese** [comment]
Thanks for the explanation. @thockin it seems that a gcr user has to run:
```
$ gcloud beta auth configure-docker
```
once inorder to use gcr. Do you want to run it before every push or leave it out?

**Comment by ixdy** [comment]
lgtm, though this needs rebase

**Comment by thockin** [comment]
+1

**Comment by mikedanese** [comment]
Accidentally pushed zero commits and github wouldn't let me recover. Rebased change here:

https://github.com/kubernetes/kubernetes/pull/60354

**Pull request closed without merging**
