### PR TITLE
fix the wrong example about scheduler extender

### LINKED ISSUE #52391: Kubernetes Extended Scheduler Json example incorrectly mentioned
**BUG REPORT**:

@kubernetes/sig-scheduling
@kubernetes/sig-docs
 /kind bug

K8S Extended scheduler example provides incorrect Key for configuring Extenders:
https://github.com/kubernetes/kubernetes/blob/master/examples/scheduler-policy-config-with-extender.json mentions to configure extender by using "extenders" keyword however when configured this way the scheduler skips the extender configuration.

Scheduler Extender configuration needs to be provided with keyword "ExtenderConfigs":

Reproduce: Run scheduler using --policy-config-file using json from the above example extender URL.

Extended scheduler document needs to be updated with "ExtenderConfigs" instead on "extender"

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7
- Cloud provider or hardware configuration**: Local cluster
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools: hack/local-cluster-up.sh
- Others:

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

the "extender" should be "extenderConfigs".

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #52391 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by resouer** [comment]
ping @zmerlynn for example's approve :)

**Comment by guangxuli** [comment]
@bsalamat @resouer Does this modification really works correctly? I test this in my workaround, the result seems that scheduler couldn't read the extender configs after use `extenderConfigs`. But 'extenders' seems works well. May I miss something.

**Comment by xiangpengzhao** [comment]
@wackxu did you verify this PR and confirm it works?

**Comment by wackxu** [comment]
@xiangpengzhao I am sorry for that I do not verify the opinion of @gnavgire originally. I do the verify just now and I agree with @guangxuli .The `extenders` is correct and we should close the issue and this pr.

**Comment by xiangpengzhao** [comment]
@wackxu thanks for clarification :)

**Pull request closed without merging**
