### PR TITLE
Use 8.8.8.8 as default DNS server in local-up-cluster.

### PR DESCRIPTION
**Pull request by bprashanth**
This has confused people, but I can go eitherway.

### CODE REVIEW

**Comment by thockin** [comment]
LGTM

**Comment by derekwaynecarr** [comment]
@thockin @bprashanth - this confused me when it was removed and i no longer saw kube-system ns by default... what was the original source of confusion for my own awareness?

**Comment by bprashanth** [comment]
@derekwaynecarr sorry missed you question.
Setting it to 127 doesn't make sense unless someone is running a dns server on localhost.
Setting it to the 10-dot ip doesn't make sense in all situations because we don't know if anyone is using the ten-dot address range for other things (eg: lxc), or have overlapping iptables rules that intercept traffic (like many corporate installations insert). 

It felt safest to force people who want DNS on local-up-cluster to understand the settings and requirements, and make public dns lookups work for everyone else.

**Comment by derekwaynecarr** [comment]
@bprashanth - ironically, our corporate firewall blocks 8.8.8.8 ;-)

**Pull request merged**
