### PR TITLE
monit health check kubelet and restart unhealthy one

### LINKED ISSUE #5107: Unhealthy Kubelet should be restarted
We've run into issues like #5092 where the Kubelet was up but not healthy. The monit monitoring for Kubelet should ensure it is "healthy" rather than just alive. We need to define what healthy means in this context and monitor it based on that. An alternate option is for the Kubelet to exit when it gets into a situation it can't serve from. This may lead to crashloops so we'd need to be careful going this route. The answer is probably a bit of both.

### PR DESCRIPTION
**Pull request by dchen1107**
Fix #5107

cc/ @vmarmol  @roberthbailey

### CODE REVIEW

**Comment by dchen1107** [comment]
A separate PR will be sent out later or tommorrow to reduce monit scanning interval to 30second. Currently it is 2 minutes. I need to figure out why master node configuration is different from minions first.

**Comment by vmarmol** [comment]
LGTM, will merge on green. Thanks @dchen1107!

**Comment by vmarmol** [comment]
Looks like the unit test is failing:

```
--- FAIL: TestHealthCheck (0.01s)
	server_test.go:487: expected status code 500, got 200
	server_test.go:501: expected status code 200, got 500
```

**Comment by dchen1107** [comment]
Yeah, early git rebase merge some wrong code. I fixed it. Now the test should pass.

**Comment by vmarmol** [comment]
Green it is! LGTM, merging.

**Comment by dchen1107** [comment]
#2884

**Pull request merged**
