### PR TITLE
Minor comments improvements

### PR DESCRIPTION
**Pull request by php-coder**
Fix typo and wrong comment.

### CODE REVIEW

**Comment by php-coder** [comment]
@k8s-bot kops aws e2e test this (https://github.com/kubernetes/kubernetes/issues/40723)

**Comment by php-coder** [comment]
@k8s-bot gce etcd3 e2e test this (flake: https://github.com/kubernetes/kubernetes/issues/34354)

**Comment by timothysc** [comment]
@k8s-bot test this #IGNORE

**Comment by php-coder** [comment]
@timothysc Thanks! Could you also remove `kind/api-change` label?

**Comment by timothysc** [comment]
this is not you.. there testing system is fubar.

**Comment by php-coder** [comment]
I've removed change about "CAP_ prefix" because it's runtime dependent and could be false for rkt (thanks @pweil-).

**Comment by resouer** [comment]
@k8s-bot ok to test

**Pull request merged**
