### PR TITLE
Pushing a new KubeDNS image and updating the YAML files

### PR DESCRIPTION
**Pull request by nikhiljindal**
Updating KubeDNS image to include https://github.com/kubernetes/kubernetes/pull/27845

@kubernetes/sig-cluster-federation @girishkalele @mml

### CODE REVIEW

**Comment by nikhiljindal** [comment]
federation e2e tests are failing right now without this change.

**Comment by girishkalele** [comment]
@nikhiljindal 

LGTM - since we consolidated all skydns yaml files in one place, its cleaner to update.
Please push the 1.4 containers for all architectures to gcr.io and we can let the e2e tests run.

**Comment by nikhiljindal** [comment]
Yes. Pushed the image to gcr.io

**Comment by quinton-hoole** [comment]
LGTM.  Thanks @nikhiljindal I'll leave you and/or @girishkalele to add the label once you're happy with all of the tests and arch's.

**Comment by girishkalele** [comment]
LGTM
Ok to test

**Comment by nikhiljindal** [comment]
Verified that 1.4 tag now exists on all platforms:
https://gcr.io/v2/google_containers/kubedns-arm64/tags/list
https://gcr.io/v2/google_containers/kubedns-ppc64le/tags/list
https://gcr.io/v2/google_containers/kubedns-arm/tags/list
https://gcr.io/v2/google_containers/kubedns-amd64/tags/list

**Pull request merged**
