### PR TITLE
Automated cherry pick of #71074: Fixed clearing of devicePath after UnmountDevice

### PR DESCRIPTION
**Pull request by gnufied**
Cherry pick of #71074 on release-1.12.

#71074: Fixed clearing of devicePath after UnmountDevice

### CODE REVIEW

**Comment by jsafrane** [comment]
`godep: Package (k8s.io/klog) not found`

**Comment by gnufied** [comment]
@jsafrane yeha need to fix those. sorry about it.

**Comment by feiskyer** [comment]
@gnufied Could you add a release note in the original PR?

**Comment by gnufied** [comment]
@jsafrane is original author of the PR. @jsafrane can you add a release-note to the PR?

**Comment by feiskyer** [comment]
> @jsafrane is original author of the PR. @jsafrane can you add a release-note to the PR?

Thanks
/release-note

**Pull request merged**
