### PR TITLE
NodePIDPressure condition should set to unknown when node lost connne…

### LINKED ISSUE #68643: NodePIDPressure condition should  set to unknown when node lost connnection with contorl
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
when the node  lost connection with master ,  using 'kubectl describe node' find the NodePIDPressure is false , no switch to unknown.
```
Conditions:
  Type              Status    LastHeartbeatTime                 LastTransitionTime                Reason                                                             Message
  ----              ------    -----------------                 ------------------                ------                                                             -------
  OutOfDisk         Unknown   Fri, 14 Sep 2018 17:39:56 +0800   Fri, 14 Sep 2018 17:40:40 +0800   NodeStatusUnknown                                                  Kubelet stopped posting node status.
  MemoryPressure    Unknown   Fri, 14 Sep 2018 17:39:56 +0800   Fri, 14 Sep 2018 17:40:40 +0800   NodeStatusUnknown                                                  Kubelet stopped posting node status.
  DiskPressure      Unknown   Fri, 14 Sep 2018 17:39:56 +0800   Fri, 14 Sep 2018 17:40:40 +0800   NodeStatusUnknown                                                  Kubelet stopped posting node status.
  Ready             Unknown   Fri, 14 Sep 2018 17:39:56 +0800   Fri, 14 Sep 2018 17:40:40 +0800   NodeStatusUnknown                                                  Kubelet stopped posting node status.
  PIDPressure       False     Fri, 14 Sep 2018 17:39:56 +0800   Fri, 14 Sep 2018 17:38:46 +0800   KubeletHasSufficientPID                                            kubelet has sufficient PID available

```
**What you expected to happen**:
`  PIDPressure       Unknown   Fri, 14 Sep 2018 05:13:09 +0800   Fri, 14 Sep 2018 05:13:53 +0800   NodeStatusUnknown                                                  Kubelet stopped posting node status.
`
**How to reproduce it (as minimally and precisely as possible)**:
stop kubelet, wait the node Notready
check the node status 'kubectl describe node'
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by Pingan2017**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #68643 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by k82cn — APPROVED** [review]

**Comment by Huang-Wei** [comment]
@k8scn hmm... This is already covered in #67037, in https://github.com/kubernetes/kubernetes/pull/67037/files#diff-43035107687eb30550696751ac1066e4R927

**Pull request merged**
