### PR TITLE
Added flags for horizontal pod autoscaler to controller-manager.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Added flags for horizontal pod autoscaler to controller-manager.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
@mwielgus

**Comment by jszczepkowski** [comment]
Part of #12087.

**Comment by davidopp** [comment]
LGTM

**Comment by piosz** [comment]
@k8s-bot test this please

**Comment by jszczepkowski** [comment]
Part of #12087.

**Pull request merged**
