### PR TITLE
"contails" -> "contains" updated

### LINKED ISSUE #111916: "contains" misspelled as "contails" in PVC doc comment
https://github.com/kubernetes/kubernetes/blob/3e396dbac5c61860e4b926f07721851091cf4110/staging/src/k8s.io/api/core/v1/types.go#L555

"contails" -> "contains"

### PR DESCRIPTION
**Pull request by pilotudesh**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Fixes the issue in the documentation

#### Which issue(s) this PR fixes:
Fixes #111916

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Review by SataQiu — COMMENTED** [review]
/ok-to-test

**Comment by thockin** [comment]
You will have to regenerate swagger, openapi, proto, etc.

```
$ git grep contails
api/openapi-spec/swagger.json:      "description": "PersistentVolumeClaimCondition contails details about state of pvc",
api/openapi-spec/v3/api__v1_openapi.json:        "description": "PersistentVolumeClaimCondition contails details about state of pvc",
api/openapi-spec/v3/apis__apps__v1_openapi.json:        "description": "PersistentVolumeClaimCondition contails details about state of pvc",
pkg/generated/openapi/zz_generated.openapi.go:                          Description: "PersistentVolumeClaimCondition contails details about state of pvc",
staging/src/k8s.io/api/core/v1/generated.proto:// PersistentVolumeClaimCondition contails details about state of pvc
staging/src/k8s.io/api/core/v1/types.go:// PersistentVolumeClaimCondition contails details about state of pvc
staging/src/k8s.io/api/core/v1/types_swagger_doc_generated.go:  "":                   "PersistentVolumeClaimCondition contails details about state of pvc",
staging/src/k8s.io/cli-runtime/artifacts/openapi/swagger.json:      "description": "PersistentVolumeClaimCondition contails details about state of pvc",
staging/src/k8s.io/kubectl/testdata/openapi/swagger.json:      "description": "PersistentVolumeClaimCondition contails details about state of pvc",
vendor/sigs.k8s.io/kustomize/kyaml/openapi/kubernetesapi/v1212/swagger.pb:1io.k8s.api.core.v1.PersistentVolumeClaimCondition^R<D9>^E"BPersistentVolumeClaimCondition contails details about state of pvc<9A>^A^Dtype<9A>^A^Fstatus<B2>^A^H
```

**Comment by sftim** [comment]
Hi @pilotudesh 

This should be 2 commits:
1. the typo fix itself
2. the updates to generated code that you get from `make update`

https://www.k8s.dev/blog/2022/03/15/k8s-triage-bot-helper-ci-job/ might help you with step 2

**Comment by thockin** [comment]
The "two commits" guidance is not universal.  Personally, I only do that when the rest of the PR makes it hard to track.  The problem being that things like `git bisect` break when commits are not self-contained, so I try not to do it unless really valuable.

**Comment by thockin** [comment]
@pilotudesh are you going to come back to this or shall I take it over?

**Pull request closed without merging**
