### PR TITLE
Remove E2E_SET_CLUSTER_API_VERSION from jenkins/e2e.sh

### LINKED ISSUE #16535: Remove E2E_SET_CLUSTER_API_VERSION; it's confusing and unnecessary
For a while, we were running tests against GKE at versions we didn't realize, because we weren't properly setting `E2E_SET_CLUSTER_API_VERSION`.  See #16533.

### PR DESCRIPTION
**Pull request by sgoings**
Fixes #16535

### CODE REVIEW

**Comment by sgoings** [comment]
Submitting this PR under the EngineYard company CLA... what additional steps do I need to take?

**Comment by ihmccreery** [comment]
@sgoings sorry this has taken so long for someone to look at; seems to have been lost in the fold (@eparis, what happened here?).

I've assigned @spxtr to review because he's doing a lot of work with `e2e.sh` right now.  Looks like you'll need to rebase, though.

**Comment by ihmccreery** [comment]
@sgoings Can you please fill out the CLA and select EngineYard?  Is that an option?

**Comment by ihmccreery** [comment]
Aaaand, I don't think your PR will actually work quite yet; we still need to set `CLUSTER_API_VERSION` appropriately, not remove it completely.

**Comment by spxtr** [comment]
`CLUSTER_API_VERSION` is set to a default value of nothing in `cluster/gke/config-common.sh` if it isn't set, and used in `cluster/gke/util.sh` as an argument to create the cluster.

It looks like every gke job (except for the soak tester, which doens't bring up a cluster) sets this variable to 'y', so it might be okay to default it to 'y' in `cluster/gke/common-config.sh`.

**Comment by sgoings** [comment]
@ihmccreery, see my sgoings@engineyard.com EngineYard CLA connection (didn't appear until recently):
screen shot 2015-12-30 at 1 29 51 pm

**Comment by ihmccreery** [comment]
If I understand correctly, this PR just removes the ability to set the `CLUSTER_API_VERSION` entirely, which is definitely not what we want.  We just don't want to have to explicitly tell it to set the `CLUSTER_API_VERSION`.

Also, `y` is not a valid `CLUSTER_API_VERSION`.

**Comment by spxtr** [comment]
@sgoings Are you going to keep working on this?

**Comment by sgoings** [comment]
Nah, @spxtr - I thought this would be an easy change... but without access to see what my changes are affecting, I'd rather just pass this off to someone more knowledgeable.

**Pull request closed without merging**
