### PR TITLE
Automated cherry pick of #88247: test/e2e/node: fix selinux test failure

### PR DESCRIPTION
**Pull request by kolyshkin**
Cherry pick of #88247 on release-1.17.

#88247: test/e2e/node: fix selinux test failure

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/assign @derekwaynecarr
/lgtm

Makes sense that we want these tests passing on the 1.17 branch.

Is it also worth cherry-picking to even earlier (supported) branches?

**Comment by mattjmcnaughton** [comment]
> /assign @derekwaynecarr
> /lgtm
> 
> Makes sense that we want these tests passing on the 1.17 branch.
> 
> Is it also worth cherry-picking to even earlier (supported) branches?

Oh wait, just saw your pull request to cherry-pick this to 1.16... I was filtering by the sig/node label, which for some reason this cherry pick got but the other didn't... Anyway, thanks!

**Comment by tpepper** [comment]
/kind failing-test
/priority important-longterm
from parent PR

**Comment by SergeyKanzhelev** [comment]
Looks like a legit tests failure:

```
ERROR(all) test/e2e/node/security_context.go:271:21: undeclared name: tk
```

/hold

**Comment by SergeyKanzhelev** [comment]
For this cherry pick to work, this PR needs to be merged: https://github.com/kubernetes/kubernetes/pull/84613/ which is 38 files. I'd suggest to close this PR and have a separate one that has a targeted fix for the issue

/close

**Pull request closed without merging**
