### PR TITLE
Minor clean up on checking container runtime status

### PR DESCRIPTION
**Pull request by yujuhong**
Remove redundant function and consolidate the code.

### CODE REVIEW

**Comment by yujuhong** [comment]
@k8s-bot test this

**Comment by yujuhong** [comment]
@k8s-bot unit test this

**Comment by yujuhong** [comment]
@k8s-bot test this

**Comment by yujuhong** [comment]
@k8s-bot test this

**Comment by yujuhong** [comment]
@k8s-bot unit test this

**Comment by yujuhong** [comment]
@vishh, this is a small PR, PTAL. Thanks!

**Comment by vishh** [comment]
Thanks for the cleanup @yujuhong

**Comment by yujuhong** [comment]
@k8s-bot test this

**Comment by yujuhong** [comment]
@k8s-bot test this

**Comment by yujuhong** [comment]
@k8s-bot unit test this

**Comment by yujuhong** [comment]
@k8s-bot test this

**Pull request merged**
