### PR TITLE
Namespace should support table printing

### PR DESCRIPTION
**Pull request by smarterclayton**
@soltysh 

Part of #58536

### CODE REVIEW

**Comment by juanvallejo** [comment]
@soltysh this lgtm

**Comment by smarterclayton** [comment]
@sttts can you do a quick pass on this?

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by jberkus** [comment]
@smarterclayton please add kind/ priority/ and status/approved-for-milestone labels to this PR.  Otherwise the bot will remove it on Monday.  Thanks!

**Pull request merged**
