### PR TITLE
[Do not Merge]: Check CoreDNS v1.6.5

### PR DESCRIPTION
**Pull request by rajansandeep**
**What type of PR is this?**
Test PR

**What this PR does / why we need it**:
Check the latest CoreDNS image v1.6.5
Also, check scalability when adding pod anti-affinity

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/hold
/test pull-kubernetes-e2e-gce-large-performance
/test pull-kubernetes-e2e-gce-big-performance

### CODE REVIEW

**Comment by mm4tt** [comment]
Hey @rajansandeep, please do not trigger the pull-kubernetes-e2e-gce-large-performance presubmit without consulting first with sig-scalability.
This presubmit shares project (resources) with other tests and currently it blocks some manual testing that had been planned for today.

We don't want to disable this presubmit as it's convenient to run it in some cases but we'll have to if people start overusing it.

I will delete your test cluster to release the resources (so the test will fail unexpectedly). I reserved you a slot for tomorrow PST daytime to run the test. 
In future please reach out to us on slack to get a slot before running the test.

**Comment by robscott** [comment]
Just finished scale testing for the day, here's that test run:
/test pull-kubernetes-e2e-gce-large-performance

**Comment by rajansandeep** [comment]
@robscott Thank you!
@mm4tt I apologize for the inconvenience that may have caused due to the trigger of these tests. I'll keep in mind to warn sig-scalability before triggering these tests next time.

**Comment by oxddr** [comment]
The cluster hasn't come up - I'll have a look next week at logs. Let's test it again.  

/test pull-kubernetes-e2e-gce-large-performance

**Comment by oxddr** [comment]
I had a brief look at pull-kubernetes-e2e-gce-large-performance and it seems that apiserver went down. I'll have a look tomorrow at that.

I started manual run of performance test on 5k cluster in the meantime anyway. I'll come back with results tomorrow.

**Comment by oxddr** [comment]
Prometheus snapshot has not been created, so there is little I can tell about failed `pull-kubernetes-e2e-gce-large-performance`.  :(

**Comment by chrisohaver** [comment]
> Prometheus snapshot has not been created, so there is little I can tell about failed `pull-kubernetes-e2e-gce-large-performance`. :(

Well, code freeze is rapidly approaching. Why don't we try testing _without_ the pod anti-affinity, rules and see if the test passes.

**Comment by oxddr** [comment]
> > Prometheus snapshot has not been created, so there is little I can tell about failed `pull-kubernetes-e2e-gce-large-performance`. :(
> 
> Well, code freeze is rapidly approaching. Why don't we try testing _without_ the pod anti-affinity rules and see if the test passes.

There is a manual test in flight with this PR - in case of any problems I'll re-run only with CoreDNS version bumped.

**Comment by oxddr** [comment]
Scalability tests passed on this PR as is. I am going to look into dashboards from the test to see if there isn't any visible regression in there.

**Comment by oxddr** [comment]
I had a closer look at dashboards and they look good. We give green light from scalability perspective.

**Comment by oxddr** [comment]
@rajansandeep metrics collected at the end of each test, as requested: [metrics.zip](https://github.com/kubernetes/kubernetes/files/3841941/metrics.zip)

**Pull request closed without merging**
