### PR TITLE
rkt: Improve support for privileged pod (pod whose all containers are privileged) 

### PR DESCRIPTION
**Pull request by yifan-gu**
Fix https://github.com/kubernetes/kubernetes/issues/31100

This takes advantage of https://github.com/coreos/rkt/pull/2983 . By appending the new `--all-run` insecure-options to `rkt run-prepared` command when all the containers are privileged. The pod now gets more privileged power.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31286)

### CODE REVIEW

**Comment by euank** [comment]
Perhaps we should also update the minimum required version to reflect this (though I believe the failure scenario is just that the feature will gracefully degrade into all capabilities).

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31286#-:-KPtC6rvErtQ9Iil6Ek1:bhkdyju)*

**Comment by yifan-gu** [comment]
@euank Updated the version.

**Comment by yifan-gu** [comment]
@k8s-bot test this please, #31262

**Comment by euank** [comment]
:lgtm:

Last nit is that this could be a release note / bug-fix label, though it doesn't completely fix the bug, it is a step in the right direction.
Feel free to have an opinion on whether this is `action-required` (rkt upgrade). I think we can not add action-required notes yet given the overall status of rkt integration, but feel free to disagree.

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31286#-:-KPtgi6i6m8R5u0rZ2AT:b-rqs570)*

**Comment by yifan-gu** [comment]
@euank I was also thinking about adding `release-note`. Thanks!

**Comment by tmrts** [comment]
@yifan-gu LGTM :+1:

Are we not adding a release note? I couldn't see it

**Comment by pwittrock** [comment]
@tmrts @yifan-gu What is the relationship between this and the feature freeze (8/22)?  Same question for #30513.  Is this fora  feature or a bug fix?

**Comment by euank** [comment]
@pwittrock I would consider this a bugfix in that it improves the state of a known issue with the rkt integration. I would consider #30513 feature-work.

**Comment by pwittrock** [comment]
@euank Thanks for that clarification.  I will follow up on #30513 separately.

**Pull request merged**
