### PR TITLE
servicecontroller: trivial fix error message naming

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gyliu513** [comment]
@k8s-bot ok to test

**Comment by NickrenREN** [comment]
/lgtm

typos, ping @nikhiljindal  @quinton-hoole

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by NickrenREN** [comment]
@quinton-hoole  There is no associated issue. Maybe /approve no-issue ?
Or @zjj2wry  you can add an issue and update the first comment.

**Pull request merged**
