### PR TITLE
kubeadm: add better test coverage to version.go

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:

This PR adds unit tests for the file `kubeadm/app/cmd/version.go` via `version_test.go`. Test coverage is increased to 90% for this file. only a couple of functions are tested.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

None

**Special notes for your reviewer**:

related PRs:
https://github.com/kubernetes/kubernetes/pull/59220
https://github.com/kubernetes/kubernetes/pull/58540

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by fabriziopandini — CHANGES_REQUESTED** [review]
Additional tests on kubeadm are always welcome! 🎉🎉

Only one note about the TestRunVersion method: according to kubernestes testing guide the preferred method of testing multiple scenarios or input is table driven testing
Example: https://github.com/kubernetes/kubernetes/blob/ae1fc13aee81e66b9b74a5fb881ff3f90463ff4e/cmd/kubeadm/app/phases/certs/certs_test.go#L35

What do you think about refactoring the method according to this guideline?

**Comment by neolit123** [comment]
hi, @fabriziopandini 
> according to kubernestes testing guide the preferred method of testing multiple scenarios or input is table driven testing

hm, i didn't know it was a requirement. can you point me out towards the "kubernestes testing guide" as i can't find it online?

**Comment by fabriziopandini** [comment]
https://kubernetes.io/docs/imported/community/guide/#testing
https://github.com/kubernetes/community/blob/master/contributors/devel/testing.md

It is not a strict requirement, but a general raccomadation, and IMO in this case the code will gain in readability by having all the test cases listed at the beginning with their expected result e.g.
```go
var tests = []struct {
                flags bool
		expectedError bool
		shouldBeValidYaml bool
                shouldBeValidJson bool
	}{
             { // run without flags
                flags: "",
                expectedError: false,
             },
             { // run with unknown flags
                flags: "unknown-flag",
                expectedError: true,
             },
        }
```
WDYT?

**Comment by neolit123** [comment]
@fabriziopandini 

thanks for the links!

> It is not a strict requirement, but a general raccomadation, and IMO in this case the code will gain in readability by having all the test cases listed at the beginning with their expected result e.g.

ok, i'm already using the table approach in my other unit test PRs so i use it here too.

**Comment by neolit123** [comment]
@fabriziopandini done, updated.

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60663)

**Review by timothysc — APPROVED** [review]
/approve 

/assign @timothysc 

/retest all

**Pull request merged**
