### PR TITLE
Kubernetes Release 0.9.0

### PR DESCRIPTION
**Pull request by brendandburns**

### CODE REVIEW

**Comment by eparis** [comment]
Something seems pretty wrong...

96af0c3e5bac4c07635ac3653724c0721ed64403 is the commit here.  That's fine.  I see it in my cloned tree.  All seems well.

But when I go to the projects "tags" or "releases" I see the commit as 03f33502846ebc9458279bc7ceaa432909eeaf79.  Which doesn't show up in a clone anywhere.

Also git clone has no tag called 0.9.0.  I don't know the different between the github tag and the actual git tag, but something about this didn't go quite right...

**Comment by brendandburns** [comment]
Hrm, ok.  I'll try to figure out what's wrong.  I accidentally pushed the
tag before I rebased to grab the versioning commits, so I bet I borked
something...

Sorry!
Brendan

**Comment by brendandburns** [comment]
Hrm, so in a clean dir I did:

$ git clone https://github.com/GoogleCloudPlatform/kubernetes.git

$ git tag
....
v0.9.0

$ git checkout v0.9.0

$ git log
commit 03f33502846ebc9458279bc7ceaa432909eeaf79
Author: Brendan Burns <bburns@google.com>
Date:   Tue Jan 20 15:30:43 2015 -0800

    Kubernetes version v0.9.0

commit 9192a4ce228f86f1b05d2b1add6c52d6ac0ffb64
...

Which all seems correct to me.

That other commit you pointed to is in a different branch (rel9), perhaps
that's the problem?

I will freely admit to not being a git expert, so if you have some idea of
what is wrong and what I should do to fix it, I'm happy to try it, but it
all seems kosher as far as I can tell.


On Thu, Jan 22, 2015 at 8:25 AM, Brendan Burns <bburns@google.com> wrote:
>
> Hrm, ok.  I'll try to figure out what's wrong.  I accidentally pushed the
tag before I rebased to grab the versioning commits, so I bet I borked
something...
>
> Sorry!
> Brendan
>
> On Jan 22, 2015 6:59 AM, "Eric Paris" <notifications@github.com> wrote:
>>
>> Something seems pretty wrong...
>>
>> 96af0c3 is the commit here. That's fine. I see it in my cloned tree. All
seems well.
>>
>> But when I go to the projects "tags" or "releases" I see the commit as
03f3350. Which doesn't show up in a clone anywhere.
>>
>> Also git clone has no tag called 0.9.0. I don't know the different
between the github tag and the actual git tag, but something about this
didn't go quite right...

**Comment by dchen1107** [comment]
Didn't follow the entire thread here, but I just noticed there is no upstream/release-0.9 branch when I plan to patch v0.9.

**Comment by brendandburns** [comment]
Yeah, I didn't create a branch yet.  It's pretty easy to do when you need
to patch the release.  Let me know if you need instructions about how to do
it.

--brendan

**Comment by eparis** [comment]
Something is wrong, I'm not sure what.  I still don't understand.  Did you tag some dangling commit not in master as v0.9.0?  Did you then rebase the changes to pkg/version/base.go and merge that into master? Is that rebase the problem here?

Look what builds from HEAD think their version is...
Client Version: version.Info{Major:"0", Minor:"8+", GitVersion:"v0.8.0-611-g4c413e794ef040", GitCommit:"4c413e794ef04081dd5ed41bbe0b61fc0acc819f", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"8+", GitVersion:"v0.8.0-611-g4c413e794ef040", GitCommit:"4c413e794ef04081dd5ed41bbe0b61fc0acc819f", GitTreeState:"clean"}

You tagged commit:
03f33502846ebc9458279bc7ceaa432909eeaf79
But I can't find that in ANY branch in the repo.

But you made the same v0.9.0 changes to pkg/version/base.go in.
96af0c3e5bac4c07635ac3653724c0721ed64403

I think this is mostly fixable, but it'll take some git magic...

I really want to know what was done wrong though...

**Comment by eparis** [comment]
@bgrant0607 you know I'm fighting with the v0.9.0 tag, couple of more tidbits of information...

**Comment by eparis** [comment]
ok, I have a branch that fixes the problem.  Still want to know how you got it wrong like this....   I will open a PR.  believe me, it's not nice clean git history with rebases like everyone loves so much   :)

**Comment by jbeda** [comment]
The problem is that the tag is pointing to the wrong commit. Brendan pushed the tag to a commit that isn't referenced in any branch. It is essentially an orphaned branch.

The correct thing to do here is to create a new tag and force push that to the master. That new tag should point to the commit that is actually in the branch.

It might also be that the release tars that Brendan created is wrong too.

I'm going to fix it now and document the steps I'm taking.

**Comment by jbeda** [comment]
Commands I ran:
```
git checkout 96af0c3e5bac4c07635ac3653724c0721ed64403
git tag -a -f -m "Kubernetes version v0.9.0" v0.9.0
git push -f https://github.com/GoogleCloudPlatform/kubernetes tags/v0.9.0
```

**Comment by eparis** [comment]
and are you going to redo the binary build and all of that stuff as well?

**Comment by jbeda** [comment]
Ug -- the v0.9.0 release that @brendandburns created and released is actually 9192a4ce228f86f1b05d2b1add6c52d6ac0ffb64.

```
cd tmp
wget https://github.com/GoogleCloudPlatform/kubernetes/releases/download/v0.9.0/kubernetes.tar.gz
tar xzvf kubernetes.tar.gz
cd kubernetes/
platforms/darwin/amd64/kubectl version -c
Client Version: version.Info{Major:"0", Minor:"8+", GitVersion:"v0.8.0-469-g9192a4ce228f86-dirty", GitCommit:"9192a4ce228f86f1b05d2b1add6c52d6ac0ffb64", GitTreeState:"dirty"}
```

I'll recreate this and re-upload it.

**Comment by zmerlynn** [comment]
Are you about to re-re-tag 0.9.0? If so, I'll blow away the release-0.9
branch.

**Comment by jbeda** [comment]
No -- I'm not going to re-tag v0.9.0.  Instead, I'm going to recreate the binary build and clobber that in our release bucket and the github release page.

**Comment by jbeda** [comment]
New binary release created and pushed.  sha1: `19157ec2059885e2da03cd2e4708df945f7184b0`

**Comment by brendandburns** [comment]
Thanks all!  I seem to find new ways to break this each time...

Brendan

**Pull request merged**
