### PR TITLE
fix golint failures for pkg/volume/scaleio and pkg/volume/storageos

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind cleanup

**What this PR does / why we need it**:
Ref:https://github.com/kubernetes/kubernetes/issues/68026
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
Thanks for this pr :)

/lgtm
/ok-to-test

**Comment by qingsenLi** [comment]
/assign @cblecker @saad-ali @rootfs 
wait for approve,thanks

**Comment by qingsenLi** [comment]
/assign @thockin @dims 
PTAL

**Comment by qingsenLi** [comment]
/assign @cblecker @saad-ali @rootfs@@thockin @dims
wait for approve,thanks

**Comment by cblecker** [comment]
/approve
for `hack/`

**Comment by qingsenLi** [comment]
/assign @saad-ali @rootfs@@thockin
wait for approve pkg/volume ,thanks

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
