### PR TITLE
Automated cherry pick of #61942: fix mirror-pod hash race condition

### PR DESCRIPTION
**Pull request by detiber**
Cherry pick of #61942 on release-1.10.

#61942: fix mirror-pod hash race condition

### CODE REVIEW

**Review by fabriziopandini — APPROVED** [review]
/lgtm

**Comment by MaciekPytel** [comment]
Removing cherrypick-approved (which was added by bot for some reason). There are comments on the base PR and it looks like it will change. We can cherry-pick this after the final version of the code is done and reviewed.

**Comment by MaciekPytel** [comment]
/hold
Apparently removing cherrypick-approved is not very effective :(

**Comment by spiffxp** [comment]
@MaciekPytel this is, technically speaking, the bot behaving as expected

if you remove `cherrypick-approved` from the PR mentioned in the description (https://github.com/kubernetes/kubernetes/pull/61942), aka this PR's "parent" in the bot's thinking,  the bot won't auto-add the label to this PR

ref: https://github.com/kubernetes/community/pull/1980#discussion_r178673624 for the spelunking I did through how the cherry pick mungers currently work

**Comment by detiber** [comment]
@kubernetes/sig-cluster-lifecycle-pr-reviews

**Comment by timothysc** [comment]
Per conversation, we're going to close cherry-picking this change and do a minimal fix for 1.10 to ignore certs on upgrade for now and we'll cleanup this path in 1.11.

**Pull request closed without merging**
