### PR TITLE
Move shell completion generation into 'kubectl completion' command

### PR DESCRIPTION
**Pull request by sttts**
Remove static shell completion scripts from the repo and add `completion` command to kubectl:

``` bash
$ source <(kubectl completion bash)
```

or

``` bash
$ source <(kubectl completion zsh)
```

This makes maintenance easier because no static scripts must be generated and committed anymore in the repo.

Moreover, kubectl is self-contained again for the user including the latest completion code. I am thinking about the use-case of updating kubectl via gcloud (or some package manager). The completion code is always in-sync, without the need to download a `contrib/completion/bash/kubectl` file from github.

Opinions are welcome /cc @eparis @nak3 

Fixes https://github.com/openshift/origin/issues/5290

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/23801)

### CODE REVIEW

**Comment by eparis** [comment]
should any of the zsh glue stuff move into the cobra repo, for others?

**Comment by sttts** [comment]
Very good question. I reimplement a number of missing functions that are not part of the zsh completion environment to make it work, of course only as far as necessary for kubectl. This is not really a "just-works" situation for other programs based on cobra, depending especially on custom functions.

Let me check in detail.

**Comment by janetkuo** [comment]
@kubernetes/kubectl

**Comment by eparis** [comment]
@sttts are you going to rebase this? did we land all the pre-reqs?

**Comment by sttts** [comment]
@eparis will rebase

**Comment by eparis** [comment]
@ingvagabund @liggitt @deads2k please CC anyone else you know of who might get bitten by this....

**Comment by smarterclayton** [comment]
@fabianofranz

**Comment by eparis** [comment]
```
.generated_docs:contrib/completions/bash/kubectl
build/common.sh:    contrib/completions/bash/kubectl
build/common.sh:  mkdir -p "${release_stage}/contrib/completions/bash"
build/common.sh
```

**Comment by sttts** [comment]
```
md-links:
not printing failed chunk: too many lines
On line 85: "kubectl_completion.md": target not found

FAIL: changes needed but not made due to --verify
/go/src/k8s.io/kubernetes/docs/ is out of date. Please run hack/update-generated-docs.sh
FAILED   ./hack/../hack/verify-generated-docs.sh	93s
```

**Comment by sttts** [comment]
```
$ hack/verify-generated-docs.sh
Generated docs are up to date.
```

hrmpf.

**Comment by fabianofranz** [comment]
Nice move.

**Comment by sttts** [comment]
Rebased.

**Comment by ArtfulCoder** [comment]
@k8s-bot test this. #IGNORE fixing from broken queue

**Comment by sttts** [comment]
@k8s-bot test this issue: #25760

**Comment by sttts** [comment]
Rebased.

**Comment by sttts** [comment]
Yet again rebased. Go, submit queue go (before yet another necessary rebase) !

**Comment by sttts** [comment]
Rebased.

**Comment by sttts** [comment]
Rebased.

**Comment by sttts** [comment]
Rebased.

**Comment by sttts** [comment]
@k8s-bot test this issue: #25967

**Comment by sttts** [comment]
@k8s-bot test this issue: #26403

**Comment by sttts** [comment]
Amen.

**Pull request merged**
