### PR TITLE
cleanup unused variables for v1beta2 component config

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

https://github.com/kubernetes/kubernetes/pull/117649 forgot to remove these variables for old UTs.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sanposhiho** [comment]
@SataQiu PTAL.

**Review by mimani68 — APPROVED** [review]

**Review by SataQiu — APPROVED** [review]
Thanks @sanposhiho 
/lgtm

**Comment by sanposhiho** [comment]
/assign @thockin 
for approval

**Pull request merged**
