### PR TITLE
to remove workflow proposal

### PR DESCRIPTION
**Pull request by sdminonne**
@erictune @brendanburns 
I think workflow proposal should be removed now. If you have a specific plan to remove it disregard this.

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks, @sdminonne 

LGTM

**Comment by gitfred** [comment]
Folks, why to you want to remove the proposal?

**Comment by sdminonne** [comment]
It's going to be implemented out of the k8s core, https://github.com/kubernetes/kubernetes/issues/25067

**Comment by gitfred** [comment]
@sdminonne thanks!

**Comment by gitfred** [comment]
@sdminonne i've sent you an email, please check

**Comment by sdminonne** [comment]
@gitfred  nope... Sorry got no email.
Sure you wrote to my corporate address?
Otherwise can you contact me via slack on kube channel?

**Comment by sdminonne** [comment]
@gitfred found your email! (sorry) Answered.

**Pull request merged**
