### PR TITLE
Fix some typo of comment in kubelet.go

### PR DESCRIPTION
**Pull request by qiujian16**
**What this PR does / why we need it**:
The PR is to fix some typo in kubelet.go

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
N/A

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Review by xiangpengzhao — APPROVED** [review]

**Comment by k82cn** [comment]
@k8s-bot ok to test

**Comment by k82cn** [comment]
typo

/lgtm

**Comment by pmorie** [comment]
@k8s-bot cvm gce e2e test this

**Comment by pmorie** [comment]
cc @derekwaynecarr

**Comment by k82cn** [comment]
@k8s-bot cvm gce e2e test this

**Comment by k82cn** [comment]
@k8s-bot gce etcd3 e2e test this
@k8s-bot unit test this
@k8s-bot cvm gce e2e test this

**Comment by k82cn** [comment]
Who can help to remove `do-not-merge` label?

**Comment by yujuhong** [comment]
@k8s-bot unit test this

**Comment by yujuhong** [comment]
@k8s-bot unit test this

**Pull request merged**
