### PR TITLE
Fix a race in the endpoint.go

### LINKED ISSUE #56026: Device Plugin Race
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/area hw-accelerators
/sig node

**What happened**:
When re-writing the endpoint code I discovered that the [mutex logic](https://github.com/kubernetes/kubernetes/blob/6b97376a539c84b9bb11de5d44daeadf9930049e/pkg/kubelet/cm/deviceplugin/endpoint.go#L96) is wrong and can lead to a data race while calling the `Device` function.

The current logic is a bit convoluted and would make more sense if the map was created in the for loop.
However it seems like once the map is assigned to the structure, a device update while calling the `Device` function will lead to a data race,

**Anything else we need to know?**:
/assign @jiayingz

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
**What this PR does / why we need it**:
This PR fixes a race in the endpoint.go

Fixes #56026

-->
```release-note
None
```

/sig node
/cc @RenaudWasTaken @ConnorDoyle @jiayingz @mindprince @ScorpioCPH @resouer @tengqm @vishh

### CODE REVIEW

**Comment by RenaudWasTaken** [comment]
Hi @vikasc!

As mentioned in other Prs I'd rather we focus efforts on getting the big Prs in rather than fixing code already fixed in these big Prs. 


Thanks!

**Review by ScorpioCPH — COMMENTED** [review]
lgtm.

**Comment by vikaschoudhary16** [comment]
@RenaudWasTaken 

> As mentioned in other Prs I'd rather we focus efforts on getting the big Prs in rather than fixing code already fixed in these big Prs.

I am not sure if it is good idea to stop a couple of lines fix and let the issue be there, in favor of a gigantic PR.

**Comment by jiayingz** [comment]
/lgtm
/approve

P.S., I have been wondering whether it is simpler if we just update e.devices in place instead of making a local copy first, and then update e.devices with that copy again. I remember @RenaudWasTaken mentioned the reason is to avoid holding mutex lock for too long, but I think just iterating the received devices should be quite fast and may be even faster than doing multiple copies.

**Comment by RenaudWasTaken** [comment]
> P.S., I have been wondering whether it is simpler if we just update e.devices in place instead of making a local copy first, and then update e.devices with that copy again. I remember @RenaudWasTaken mentioned the reason is to avoid holding mutex lock for too long, but I think just iterating the received devices should be quite fast and may be even faster than doing multiple copies.

In this specific case I'd argue that since the Kubelet resource update is on a long interval, it makes more sense to hold the lock as soon as we get an update so that the advertised resources match the updated resources sooner.

**Pull request merged**
