### PR TITLE
Move funcs of resource_usage_gatherer.go to e2e/scheduling/gatherer

### PR DESCRIPTION
**Pull request by clarklee92**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Move functions in resource_usage_gatherer.go to module e2e/scheduling/gatherer

**Which issue(s) this PR fixes**:

Ref: #84380 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hwdef** [comment]
please handle the conflict

**Comment by clarklee92** [comment]
> please handle the conflict
handled, cause one PR related merged.

**Comment by clarklee92** [comment]
Found that resource_usage_gatherer.go is called in two packages(freamwork/scheduling). This PR lead to circle dependencies. 
Close it.

**Pull request closed without merging**
