### PR TITLE
Add the ability to migrate CoreDNS configmap in kube-up

### LINKED ISSUE #78123: [Failing tests] Multiple job failures on the BeforeSuite step while waiting for CoreDNS to be ready
**Which jobs are failing**:
Multiple jobs on `master-informing`.

**Which test(s) are failing**:
`Before Suite` on the following jobs:
- https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-upgrade-stable-master
- https://testgrid.k8s.io/sig-release-master-informing#gce-new-master-upgrade-master
- https://testgrid.k8s.io/sig-release-master-informing#gce-new-master-upgrade-master-parallel
- https://testgrid.k8s.io/sig-release-master-informing#gce-new-master-upgrade-cluster-parallel
- https://testgrid.k8s.io/sig-release-master-informing#gce-new-master-upgrade-cluster
- https://testgrid.k8s.io/sig-release-master-informing#gce-master-new-downgrade-cluster
- https://testgrid.k8s.io/sig-release-master-informing#gce-master-new-downgrade-cluster-parallel
- https://testgrid.k8s.io/sig-release-master-informing#gce-new-master-upgrade-cluster-new
- https://testgrid.k8s.io/sig-release-master-informing#gce-new-master-upgrade-cluster-new-parallel

**Since when has it been failing**:
Since 5/17.

**Testgrid links**:
See above.

**Reason for failure**:
All the failures mentioned above seem to have to have the same root cause, namely failure while waiting for CoreDNS to be ready.
Example: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-stable-master/1129638974428549121
```
May 18 07:09:00.075: Error waiting for all pods to be running and ready: 2 / 14 pods in namespace "kube-system" are NOT in RUNNING and READY state in 10m0s
POD                      NODE                   PHASE   GRACE CONDITIONS
coredns-65546fffc9-j9p6b kinder-upgrade-worker2 Running       [{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2019-05-18 06:52:59 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2019-05-18 06:52:59 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [coredns]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2019-05-18 06:52:59 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [coredns]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2019-05-18 06:52:59 +0000 UTC Reason: Message:}]
```

/sig testing
/priority critical-urgent
/kind failing test
/milestone v1.15
/cc @jimangel @alejandrox1 @rarchk @alenkacz

### PR DESCRIPTION
**Pull request by rajansandeep**
**What type of PR is this?**
This is a re-created PR of #78302 since the branch of that PR has been lost.

/kind bug

**What this PR does / why we need it**:
Following CoreDNS ConfigMap changes in #78030, it is required that the ConfigMap gets updated during an `upgrade`. 
If I understand correctly, `EnsureExists` doesn't update the ConfigMap during an upgrade and requires `Reconcile` for the ConfigMap to upgrade.

This is evident from the logs:

Logs from `ci-kubernetes-e2e-gce-new-master-upgrade-cluster`:
```
event for coredns-5cd44cdc5d-lzbmv: {kubelet bootstrap-e2e-minion-group-b8n6} Unhealthy: Readiness probe failed: Get http://10.64.2.20:8181/ready: dial tcp 10.64.2.20:8181: connect: connection refused
```
Logs from `ci-kubernetes-e2e-gce-master-new-downgrade-cluster`:
```
/etc/coredns/Corefile:4 - Error during parsing: Unknown directive 'ready'
```
In both cases, the CoreDNS deployment is updated but not the ConfigMap.
This PR aims to add the ability to migrate the CoreDNS ConfigMap in kube-up in the event of an upgrade/downgrade.

It also bumps the version of CoreDNS to 1.6.2

**Which issue(s) this PR fixes**:

Fixes #78123 

**Special notes for your reviewer**:

This is a re-created PR of #78302 since the branch of that PR has been lost.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/priority critical-urgent
/cc @chrisohaver @mrhohn
/assign @bowei @BenTheElder

### CODE REVIEW

**Review by chrisohaver — APPROVED** [review]
Thanks!  

!!! LGTM !!!

**Comment by xmudrii** [comment]
Applying the priority label and the milestone from the previous PR

/milestone v1.16
/priority critical-urgent

**Review by MrHohn — APPROVED** [review]
/lgtm
/approve

**Comment by rajansandeep** [comment]
@bowei let me know if the changes are okay
I've also bumped up the coredns version to 1.6.2

**Pull request merged**
