### PR TITLE
Fake docker-client assigns random IPs to containers

### PR DESCRIPTION
**Pull request by shyamjvs**
Fixes https://github.com/kubernetes/kubernetes/issues/59823

/cc @wojtek-t @Random-Liu

### CODE REVIEW

**Comment by shyamjvs** [comment]
/test pull-kubernetes-kubemark-e2e-gce-big

To verify if we stop seeing those 422s for `PUT endpoints` calls.

**Comment by wojtek-t** [comment]
@shyamjvs - two things:
1. it seems it didn't really help
2. bazel failure is a real one

**Comment by shyamjvs** [comment]
I'll look into the bazel failure (which I guess is because of unit test failing).
And re "it didn't really help", it seems like there is a reduced no. of 422s (as compared to before when all updates starting form the 2nd one were returning 422s) - so it did help by some amount.

Let's wait for your run with debug statements to know more.

**Comment by wojtek-t** [comment]
> I'll look into the bazel failure (which I guess is because of unit test failing).

Yes - 2.3.4.5 is hardcoded somewhere.

> And re "it didn't really help", it seems like there is a reduced no. of 422s (as compared to before when all updates starting form the 2nd one were returning 422s) - so it did help by some amount iiuc.

Agree - it helped somewhat, but I wouldn't expect any "BadRequest" errors coming from our components...

**Comment by wojtek-t** [comment]
So what is happening is this:
```
AAA (Endpoints load-small-971-svc) subsets[0].addresses[0].ip: Invalid value: "127.68.255.188": may not be in the loopback range (127       .0.0.0/8)
```

You need to generate addresse that will pass this validation:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L4760

**Comment by wojtek-t** [comment]
In particular, what you seem to break is this function:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L4782

**Comment by shyamjvs** [comment]
Thanks a lot for looking into it @wojtek-t. I'll fix it by making the IP address always start with 10 (i.e 10.x.x.x) which should avoid all those failure conditions in that function.

**Comment by shyamjvs** [comment]
Fixed the unit test (hopefully) by using a deterministic random seed.
Also creating valid random IPs in the docker mock now.

@wojtek-t PTAL

**Comment by wojtek-t** [comment]
I verified the impact on: https://github.com/kubernetes/kubernetes/pull/59807
In short:
- no more 422 errors
- 2x+ more memory allocations (~100GB coming from serialization)
Both are expected and so this issues seems to be fixed now.

/lgtm
/approve

**Comment by shyamjvs** [comment]
Thanks @wojtek-t. To add to it, the `aggregate.Errors()` are no longer seen in the memory profile (so this change pretty much seems to reduce all of that alloc space). Ref - https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/59807/pull-kubernetes-kubemark-e2e-gce-big/16/artifacts/profiles/ApiserverMemoryProfile_load.pdf

**Pull request merged**
