### PR TITLE
Make gcp auth provider not to override the Auth header if it's already exits

### LINKED ISSUE #44476: kubectl --token is not honored when ~/.kube/config has an authentication token
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

kubectl token

BUG REPORT

**Kubernetes version** (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:33:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
GKE

- **OS** (e.g. from /etc/os-release):
macOS Sierra 10.12.4

- **Kernel** (e.g. `uname -a`):
➜  uname  -a
Darwin jacobsimpson-macbookpro.roam.corp.google.com 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

- **Install tools**:
- **Others**:

**What happened**:
I set up a second user, then I use `kubectl --token` to authenticate as the second user. The `--token` parameter is ignored and the authentication token from the `~/.kube/config` file is used instead, so I'm authenticated as the user configured in the config file, not as the user set on the command line parameters.

I further verified this by commenting out the section in the config file with the authentication token and then the `--token` parameter starts to work as expected.

**What you expected to happen**:
I expect the command line parameters, when present, to override the config file settings.

**How to reproduce it** (as minimally and precisely as possible):
```
gcloud container clusters create test-cluster --cluster-version=1.6.1
primary_account=$(gcloud auth list 2>&1 | grep ACTIVE | sed 's/.*- \([^ ]*\) .*/\1/')
admin_token="$(gcloud auth print-access-token --account=$primary_account)"
gcloud iam service-accounts create user-1 --display-name=user-1
user_account=$(gcloud iam service-accounts list --format='value(email)' --filter='displayName:user-1')
gcloud iam service-accounts keys create --iam-account $user_account user_key.json
gcloud auth activate-service-account $user_account --key-file=user_key.json
user_token="$(gcloud auth print-access-token --account=$user_account)"
kubectl --token="$admin_token" get nodes
```

At this point, the error message should be indicating kubectl tried to authenticate with the `user-1` account. Something like this:

```sh
➜  kubectl --token="$admin_token" get nodes
Error from server (Forbidden): User "user-1@project-name.iam.gserviceaccount.com" cannot list nodes at the cluster scope.: "No policy matched.\nRequired \"container.nodes.list\" permission." (get nodes)
```

Now edit `~/.kube/config`, search for the `auth-provider:` section for your cluster and comment out the whole section for the test cluster.

```yaml
- name: test-cluster
  user:
    #auth-provider:
    #  config:
    #    access-token: ya29.xxxxx
    #    cmd-args: config config-helper --format=json
    #    cmd-path: /.../gcloud
    #    expiry: 2017-04-11T21:06:25Z
    #    expiry-key: '{.credential.token_expiry}'
    #    token-key: '{.credential.access_token}'
    #  name: gcp
```

Now it should be possible to run these two commands. The one using the $admin_token will succeed, the one using the $user_token will fail with the error message indicating the user name.

```sh
kubectl --token="$admin_token" get nodes
kubectl --token="$user_token" get nodes
```

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by wanghaoran1988**
**What this PR does / why we need it**:
Make AuthProvider not wrap the transport if beartoken or basic auth is enabled
**Which issue this PR fixes** :
 fixes #44476 

**Special notes for your reviewer**:

**Release note**:
```
GCP auth plugin no longer overwrites existing Authorization headers.
```

### CODE REVIEW

**Comment by deads2k** [comment]
Why shouldn't the auth provider be able to wrap at his pleasure?  For instance, couldn't you have an auth provider that used some native tooling to produce a bearertoken that was never stored inside of the kubeconfig file?

**Comment by wanghaoran1988** [comment]
But this happens before the auth provider genarate the token, which means
you want to use the token from the kubeconfig or command line instead of
the token generated by providers ,or I missed something here? Correct me if
I am wrong.

**Comment by ericchiang** [comment]
The way the current interface is written, as a transport wrapper, has nothing to do with bearer tokens. Doing this starts to make decisions based on the existing implementations, so the abstraction is starting to leak.

We should either change the interface to be about bearer tokens and declare a clear priority, or continue to modify auth providers to not override the authorization headers.

**Comment by deads2k** [comment]
> We should either change the interface to be about bearer tokens and declare a clear priority, or continue to modify auth providers to not override the authorization headers.

I think the transport wrapper should be allowed to wrap in any way it sees fit.  What is the value in artificially restricting it?

**Comment by ericchiang** [comment]
> I think the transport wrapper should be allowed to wrap in any way it sees fit. What is the value in artificially restricting it?

@deads2k My interface refactor point is that all or current (and proposed) client auth plugins are actually just bearer token sources, but the interface deals with wrapping transports.

If we want explicit bearer tokens/basic auth defined in the kubeconfig to override the client auth plugin's (what this PR is trying to do) we should probably refactor the client auth plugin interface into a bearer token source, instead of what this PR is doing and conditionally not wrapping the transports based on the Authorization header.

I'm not attached to a Authorization header priority, but the idea of the client auth plugin as a bearer token source instead of a transport wrapper has come up in other PRs https://github.com/kubernetes/kubernetes/pull/39587#issuecomment-291961912

**Comment by cjcullen** [comment]
If you want to get this in instead of #46666, I'd be happy to close my PR.

**Comment by ericchiang** [comment]
@cjcullen @wanghaoran1988 maybe we should get this or #46666 in for 1.7 then work on the interface refactoring for 1.8? Add a TODO and open an issue?

**Comment by ericchiang** [comment]
@k8s-bot ok to test

**Comment by cjcullen** [comment]
Opened up https://github.com/kubernetes/kubernetes/issues/46728 to track refactoring the interface for 1.8. I marked https://github.com/kubernetes/kubernetes/issues/44476 on the 1.7 milestone.

**Comment by cjcullen** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by cjcullen** [comment]
@caesarxuchao @deads2k @lavalamp @smarterclayton  for approval

**Comment by cjcullen** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by wanghaoran1988** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by deads2k** [comment]
I think the auth provider plugin should have the ability to wrap the transport regardless.  The plugin can preserve the header information.  Looks like the oidc one already did this: https://github.com/kubernetes/kubernetes/issues/45529

**Comment by wanghaoran1988** [comment]
@deads2k Yeah, the oidc plugin already have, but for GCP plugin doesn't now,  it use "golang.org.oauth2.Transport" to wrap the token, we need update the dependency to preserve the header if you like this way. but this pr is the simpler fix for now.

**Comment by liggitt** [comment]
> I think the auth provider plugin should have the ability to wrap the transport regardless.

I agree, I'd rather leave the power in the hands of the auth provider

**Comment by liggitt** [comment]
> to wrap the token, we need update the dependency to preserve the header if you like this way. but this pr is the simpler fix for now.

can choose whether to delegate to the oauth round tripper or the base round tripper:
```go

func (g *gcpAuthProvider) WrapTransport(rt http.RoundTripper) http.RoundTripper {
	return &conditionalTransport{&oauth2.Transport{Source: g.tokenSource, Base: rt}}
}

type conditionalTransport struct {
	oauthTransport *oauth2.Transport
}

func (t *conditionalTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	if len(req.Header.Get("Authorization")) != 0 {
		return t.oauthTransport.Base.RoundTrip(req)
	}
	return t.oauthTransport.RoundTrip(req)
}
```

**Comment by wanghaoran1988** [comment]
@liggitt Cool !, will update soon :)

**Comment by wanghaoran1988** [comment]
@k8s-bot pull-kubernetes-kubemark-e2e-gce test this

**Comment by wanghaoran1988** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by ericchiang** [comment]
@wanghaoran1988 thanks! please update the release notes to say that the GCP auth plugin no longer overwrites existing Authorization headers.

This is a bug fix so I'm going to nominate this for 1.7.

**Comment by wanghaoran1988** [comment]
@ericchiang Done

**Comment by wanghaoran1988** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Pull request merged**
