### PR TITLE
reorganize some logic of controller_utils.go

### PR DESCRIPTION
**Pull request by lucming**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lucming** [comment]
beceuse https://github.com/kubernetes/kubernetes/pull/111285 could not be reopened, a new one was proposed

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Comment by lucming** [comment]
@andrewsykim please help me approve this pr,thanks :)

**Comment by alculquicondor** [comment]
We are past code freeze, so we would have to wait for 1.26

**Comment by lucming** [comment]
> We are past code freeze, so we would have to wait for 1.26

okay,thanks so much ^o^

**Comment by alculquicondor** [comment]
oh well, this fell into the cracks...

/remove-lifecycle stale

/assign @andrewsykim

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
