### PR TITLE
Revert update vendor kube-openapi

### LINKED ISSUE #52135: Revert update vendor kube-openapi
/assign

### PR DESCRIPTION
**Pull request by mengqiy**
Revert https://github.com/kubernetes/kubernetes/pull/51762 since https://github.com/kubernetes/kubernetes/pull/51321 are not going to get in this release.

Will revert https://github.com/kubernetes/kube-openapi/pull/10 after this PR merged.

fixes: #52135

```release-note
NONE
```

/assign @apelisse @liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
/lgtm

if we need a structured type in the openapi package to hold group/version/kind, that's fine, but let's keep it structured rather than flattening the data into a single string before we rebump this dep

**Comment by mengqiy** [comment]
/assign @monopole 
for moving stuff back

**Pull request merged**
