### PR TITLE
Automated cherry pick of #52998

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #52998 on release-1.8.

#52998: Include audit log in master log capture, omit high volume responses

### CODE REVIEW

**Comment by liggitt** [comment]
@shyamjvs here's a pick of the slimmed down audit policy against release-1.8

@tallclair @mikedanese PTAL

**Comment by liggitt** [comment]
probably need an ack from @tallclair / @shyamjvs on whether we want this or https://github.com/kubernetes/test-infra/pull/4720 (or both) for 1.8

**Comment by shyamjvs** [comment]
Lgtm.. Will let @tallclair take a look.

**Comment by shyamjvs** [comment]
And regarding the test-infra change, I'm fine with disabling it for the scale jobs for the release and documenting it in the [scalability_validation_report.md](https://github.com/kubernetes/features/blob/master/release-1.8/scalability_validation_report.md).

**Comment by liggitt** [comment]
closing this in preference of the perf test config change for 1.8, will continue to iterate on scale performance in 1.9

**Comment by shyamjvs** [comment]
Discussed offline with @liggitt - We can skip this cherrypick as it's not turned on by default for 1.8 and we don't need to test it.

**Comment by jpbetz** [comment]
Removing 1.8 milestone since this has been abandoned.

**Pull request closed without merging**
