### PR TITLE
based on #9966: fix annoying 'please check...' messages; remove v1beta1&2 ref

### PR DESCRIPTION
**Pull request by caesarxuchao**
addressed the comments in @lavalamp's PR #9966.

@nikhiljindal @bgrant0607 @lavalamp @liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
LGTM

**Comment by bgrant0607** [comment]
Looks reasonable to me, also.

**Comment by caesarxuchao** [comment]
I will fix the Shippable.

**Comment by caesarxuchao** [comment]
Close and reopen to trigger Shippable

**Comment by nikhiljindal** [comment]
LGTM, thanks!

**Comment by lavalamp** [comment]
Thanks!

**Comment by dragon9783** [comment]
LGTM

**Pull request merged**
