### PR TITLE
Automated cherry pick of #61560: test: Disable ui dashboard test for gke

### PR DESCRIPTION
**Pull request by apelisse**
Cherry pick of #61560 on release-1.10.

#61560: test: Disable ui dashboard test for gke

### CODE REVIEW

**Comment by caesarxuchao** [comment]
lgtm. Still need the branch manager's  (@MaciekPytel) approval.

**Comment by MaciekPytel** [comment]
Manually approving as this is a fix for failing release-blocking suite and it was already discussed on https://github.com/kubernetes/kubernetes/pull/62799.

**Pull request merged**
