### PR TITLE
Update mesos godeps to remove transient dependency on testify/mock

### PR DESCRIPTION
**Pull request by timstclair**
For https://github.com/kubernetes/kubernetes/issues/21114

/cc @jdef  @kubernetes/kube-mesos

### CODE REVIEW

**Comment by jdef** [comment]
lgtm

**Comment by jdef** [comment]
... and thanks for doing this. It was on my (ever-growing) TODO list

**Comment by timstclair** [comment]
@k8s-bot test this, issue https://github.com/kubernetes/kubernetes/issues/21803

**Comment by timstclair** [comment]
@k8s-bot test this issue: https://github.com/kubernetes/kubernetes/issues/21803

**Comment by timstclair** [comment]
@k8s-bot test this issue: #21803

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
