### PR TITLE
gce: tighten up perms on kube-env

### LINKED ISSUE #52999: kubelet bootstrap certificate is widely available after boot
/kind bug

**What happened**:
After a cluster is created using kube-up.sh, it is configured using `--bootstrap-kubeconfig`, so it uses the initial certificates referenced in `/var/lib/kubelet/bootstrap-kubeconfig`, which are `/etc/srv/kubernetes/pki/kubelet.crt` and `/etc/srv/kubernetes/pki/kubelet.key`. These files containing the certificate and key are installed world readable on the node:

```sh
$ ls -l /etc/srv/kubernetes/pki
total 12
-rw-r--r-- 1 root root 1229 Sep  8 00:33 ca-certificates.crt
-rw-r--r-- 1 root root 1229 Sep  8 00:33 kubelet.crt
-rw-r--r-- 1 root root 1675 Sep  8 00:33 kubelet.key
```

**What you expected to happen**:
The key especially, should be installed with more restricted permissions, possibly even deleted after the initial bootstrap use.

**How to reproduce it (as minimally and precisely as possible)**:
```sh
cluster/kube-up.sh
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.0.425+7e5d2df2995ef4-dirty", GitCommit:"7e5d2df2995ef402a2e4ee39524c761904bf7689", GitTreeState:"dirty", BuildDate:"2017-09-08T00:24:44Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mikedanese**
fixes https://github.com/kubernetes/kubernetes/issues/52999

@roberthbailey @tallclair

### CODE REVIEW

**Comment by jberkus** [comment]
this needs to be approved for the milestone within the next 12 hours for merge into 1.9, if it's going to be merged.

**Comment by mikedanese** [comment]
We are gonna kick this to 1.9.1, cc @tallclair @abgworrall

**Comment by roberthbailey** [comment]
Do you want to fix https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/container-linux/configure.sh too (since it's mostly a clone of cluster/gci/configure.sh)?

**Pull request merged**
