### PR TITLE
Enable kubelet client-cert bootstrap/rotation in local-up-cluster

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Enables kubelet cert bootstrap/rotation in local-up-cluster

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

Related to https://github.com/kubernetes/enhancements/issues/266

/cc @dims

### CODE REVIEW

**Comment by dims** [comment]
ah fun `W0514 21:35:43.775] 2020/05/14 21:35:43 local.go:49: Failed to list containers: Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40`

**Comment by liggitt** [comment]
uh... does that mean anything to you? clearly not related to this change...

**Comment by liggitt** [comment]
fixed shellcheck error

**Comment by liggitt** [comment]
xref docker version fix in https://github.com/kubernetes/test-infra/pull/17608

**Comment by liggitt** [comment]
docker mismatch handled in https://github.com/kubernetes/test-infra/pull/17608, will be picked up by https://github.com/kubernetes/test-infra/pull/17600

**Comment by liggitt** [comment]
pull-kubernetes-local-e2e passed in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/91116/pull-kubernetes-local-e2e/1261794888752566272

@dims PTAL

**Pull request merged**
