### PR TITLE
CHANGELOG: Fix typo for release-note in 1.20

### PR DESCRIPTION
**Pull request by pandaamanda**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by puerco** [comment]
Thanks for cleaning up the changelog @pandaamanda. (I think this still needs sascha's approve)
/lgtm
/approve

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
