### PR TITLE
Add CHANGELOG-1.18.md to CHANGELOG.md

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

/kind cleanup
/sig release

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
@kubernetes/sig-release would it be worthwhile to start nesting changelog files in a subdir to avoid ever-growing root files and allow additional changelog-focused approvers?

**Comment by liggitt** [comment]
cc @kubernetes/sig-docs-pr-reviews

**Comment by saschagrunert** [comment]
> @kubernetes/sig-release would it be worthwhile to start nesting changelog files in a subdir to avoid ever-growing root files and allow additional changelog-focused approvers?

I'm definitely in favor of this and a technical solution should be quite easy.

Beside this, the modification of CHANGELOG.md during the cut of a new minor version could be done by the release engineering tooling, too.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by liggitt** [comment]
thanks for the PR, changelogs have been relocated under the CHANGELOG folder, so if this is still valid, it will need to be re-opened against that location

/close

**Pull request closed without merging**
