### PR TITLE
Update the help text for kubelet's enable-cadvisor-json-endpoints flag to explicitly mention that it has no effect on the /stats/summary endpoint.

### LINKED ISSUE #96483: Document that disabling `enable-cadvisor-json-endpoints` flag does not disable stats summary endpoint
**What would you like to be added**:
Update the help text for kubelet's `enable-cadvisor-json-endpoints` flag to explicitly mention that it has no effect over the `/stats/summary` endpoint.

**Why is this needed**:
The help text for kubelet's `enable-cadvisor-json-endpoints` flag describes it as "Enable cAdvisor json `/spec` and `/stats/*` endpoints." which would seem to include `/stats/summary`, however this is not the case as that endpoint is required by kube-metrics-server and exposes stats from cadvisor or CRI (depending on the stat provider selected internally).

**Related Issues**:
https://github.com/kubernetes/kubernetes/issues/68522

/sig node
/sig instrumentation
/kind documentation

### PR DESCRIPTION
**Pull request by mysunshine92**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Update the help text for kubelet's enable-cadvisor-json-endpoints flag to explicitly mention that it has no effect on the /stats/summary endpoint.

**Which issue(s) this PR fixes**:

Fixes #96483

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by mysunshine92** [comment]
cc @dchen1107

**Comment by mysunshine92** [comment]
cc @Random-Liu @derekwaynecarr

**Comment by mysunshine92** [comment]
cc @dchen1107   @Random-Liu  @derekwaynecarr  please help add  /milestone v1.20, thanks.

**Comment by matthyx** [comment]
@mysunshine92 it's not possible to add this PR to 1.20 as we are in still in the code freeze period:
https://www.kubernetes.dev/resources/release/

This change will enter master once we are in code thaw, which should happen in less than 2 weeks, and can then be backported to the 1.2x branch via cherry picking (but I don't think this commit qualifies for it):
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md

**Pull request merged**
