### PR TITLE
Automated cherry pick of #37723

### PR DESCRIPTION
**Pull request by mtaufen**
Cherry pick of #37723 on release-1.4.

#37723: Exit with error if <version number or publication> is not the

### CODE REVIEW

**Comment by mtaufen** [comment]
/cc @roberthbailey @davidopp 
wrt https://github.com/kubernetes/kubernetes/pull/37723#issuecomment-264489798 This should be cherrypicked into 1.4 because the downgrade instructions say to use the script from the 1.4 branch.

**Comment by jessfraz** [comment]
thanks ill merge when its green

**Comment by mtaufen** [comment]
thanks Jess

**Comment by jessfraz** [comment]
@k8s-bot unit test this

**Pull request merged**
