### PR TITLE
Fix example urls

### PR DESCRIPTION
**Pull request by liangxia**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
The old urls link to 404 page

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
The old links were moved to kubernetes/examples in https://github.com/kubernetes/kubernetes/pull/46362.

Do we have some other URLs which could redirect to kubernetes/examples GitHub page?

/ok-to-test
/priority backlog

**Comment by liangxia** [comment]
> Do we have some other URLs which could redirect to kubernetes/examples GitHub page?
> 

@draveness 
Using examples.k8s.io now.

**Review by draveness — APPROVED** [review]
/lgtm

Thanks @liangxia

**Comment by liggitt** [comment]
asked in https://github.com/kubernetes/examples/issues/334 why the staging directory exists in the examples repo. wanted to get clarity on that before we go updating links to it in API docs

**Comment by liggitt** [comment]
based on https://github.com/kubernetes/examples/issues/334#issuecomment-516136850, before updating links to point into the staging dir, the relevant examples should be promoted out of the staging dir

**Comment by liangxia** [comment]
@draveness @liggitt  The PR is ready for review (addressed issue in comments).

**Comment by liangxia** [comment]
Rebased.

**Pull request merged**
