### PR TITLE
Update CHANGELOG OWNERS to reflect 1.30 Release Notes team

### PR DESCRIPTION
**Pull request by rashansmith**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR updates the OWNERS file and adds the 1.30 release-notes team as approver and reviewers.

/assign @katcosgrove @gracenng

### CODE REVIEW

**Comment by ramrodo** [comment]
I'll rerun the test since it seems its failing:

/retest pull-kubernetes-node-e2e-containerd

**Comment by katcosgrove** [comment]
@ramrodo You are the approver assigned by the bot for this, as well!

**Comment by ramrodo** [comment]
> @ramrodo You are the approver assigned by the bot for this, as well!

Oh, yes. Sorry. Thanks!

/approve

**Pull request merged**
