### PR TITLE
Automated cherry pick of #61644: Use inclien func to ensure unlock is executed

### PR DESCRIPTION
**Pull request by misterikkit**
Cherry pick of #61644 on release-1.10.

#61644: Use inclien func to ensure unlock is executed

### CODE REVIEW

**Comment by yujuhong** [comment]
/assign @bsalamat
/assign @maciekpytel
(for cherrypick approval)

**Comment by bsalamat** [comment]
This PR fixes an issue in the scheduler causing the scheduler to go in a deadlock. This issue happens only when scheduler Equivalence Cache (which is an alpha feature) is enabled.

**Comment by MaciekPytel** [comment]
I talked offline with @yujuhong and it looks like a serious enough bug to risk delaying 1.10.3. So far tests are looking very good and we still have weekend for tests to run on, so hopefully we'll get test signal to release on Monday anyway.

**Comment by MaciekPytel** [comment]
@bsalamat Can you review and lgtm? This needs to merge today to make it to 1.10.3 and the presubmits have been really flaky in the last few days.

**Review by bsalamat — COMMENTED** [review]
/lgtm

Thanks, @misterikkit!

**Comment by yujuhong** [comment]
/retest

Those tests are flaky in general.

**Pull request merged**
