### PR TITLE
fix the type of explict

### PR DESCRIPTION
**Pull request by qingsenLi**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
/reopen
as it was closed by another PR accidently.

**Comment by qingsenLi** [comment]
@smarterclayton 
PTAL

**Comment by liggitt** [comment]
thanks for the PR, please combine multiple typo fixes into a single PR and commit

**Pull request closed without merging**
