### PR TITLE
Using BetaStorageClassAnnotation to avoid hardcode

### PR DESCRIPTION
**Pull request by NickrenREN**
**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by NickrenREN** [comment]
@k8s-bot non-cri e2e test this

**Comment by gnufied** [comment]
We should replace all usage of annotations with `storageClass` field since SC went GA.

**Comment by NickrenREN** [comment]
Yes you are right @gnufied .  But this function test annotation and now annotation is still used.
Maybe delete the whole function when beta annotation is not supported

**Pull request merged**
