### PR TITLE
Update calico ubuntu docs

### PR DESCRIPTION
**Pull request by caseydavenport**

### CODE REVIEW

**Comment by wojtek-t** [comment]
@caseydavenport 
./hack/verify-generated-docs.sh failed for this PR
Can you please fix that and update the PR?

**Comment by caseydavenport** [comment]
@wojtek-t - Thanks - I've fixed up the ./hack/verify-generated-docs failure.  Shippable still seems to be failing, but I don't think that is me.

**Comment by quinton-hoole** [comment]
Shippable was a flake.  Restarted.
And added ok-to-merge to trigger automerge by merge-bot.

**Comment by piosz** [comment]
Removing LGTM since there were changes after it was given.

**Pull request merged**
