### PR TITLE
Automated cherry pick of #70568: remove retry operation on attach/detach disk

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #70568 on release-1.11.

#70568: remove retry operation on attach/detach disk

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/retest

**Comment by andyzhangx** [comment]
@foxish for cherry-pick approval, thanks

**Comment by feiskyer** [comment]
> /hold

Any new issues found?

**Comment by andyzhangx** [comment]
/hold cancel
There is a cusotmer already verified this patch on 15 k8s clusters, running two days, it shows the disk attach/detach, i/o errors all gone

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
