### PR TITLE
Remove usage of kubectl log in tests

### LINKED ISSUE #82201: [Failing Test] [sig-cli] Kubectl client [k8s.io] Kubectl logs should be able to retrieve and filter logs [Conformance]
**Which jobs are failing**:
- `ci-kubernetes-e2e-gce-new-master-gci-kubectl-skew`

**Which test(s) are failing**:
`[sig-cli] Kubectl client [k8s.io] Kubectl logs should be able to retrieve and filter logs [Conformance] `

**Since when has it been failing**:
Failing since: 8/29

**Testgrid link**:
https://testgrid.k8s.io/sig-cli-master#skew-cluster-stable1-kubectl-latest-gce

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:697
Unexpected error:
    <exec.CodeExitError>: {
        Err: {
            s: "error running &{../../../../kubernetes_skew/cluster/kubectl.sh [../../../../kubernetes_skew/cluster/kubectl.sh --server=https://34.83.99.69 --kubeconfig=/workspace/.kube/config log redis-master-bhj7d redis-master --namespace=kubectl-6294 --tail=1] []  <nil>  Error: unknown command \"log\" for \"kubectl\"\n\nDid you mean this?\n\ttop\n\tlogs\n\nRun 'kubectl --help' for usage.\n [] <nil> 0xc0028d8210 exit status 1 <nil> <nil> true [0xc00236ca30 0xc00236ca48 0xc00236ca60] [0xc00236ca30 0xc00236ca48 0xc00236ca60] [0xc00236ca40 0xc00236ca58] [0x9d21f0 0x9d21f0] 0xc002a41740 <nil>}:\nCommand stdout:\n\nstderr:\nError: unknown command \"log\" for \"kubectl\"\n\nDid you mean this?\n\ttop\n\tlogs\n\nRun 'kubectl --help' for usage.\n\nerror:\nexit status 1",
        },
        Code: 1,
    }
    error running &{../../../../kubernetes_skew/cluster/kubectl.sh [../../../../kubernetes_skew/cluster/kubectl.sh --server=https://34.83.99.69 --kubeconfig=/workspace/.kube/config log redis-master-bhj7d redis-master --namespace=kubectl-6294 --tail=1] []  <nil>  Error: unknown command "log" for "kubectl"
    
    Did you mean this?
    	top
    	logs
    
    Run 'kubectl --help' for usage.
     [] <nil> 0xc0028d8210 exit status 1 <nil> <nil> true [0xc00236ca30 0xc00236ca48 0xc00236ca60] [0xc00236ca30 0xc00236ca48 0xc00236ca60] [0xc00236ca40 0xc00236ca58] [0x9d21f0 0x9d21f0] 0xc002a41740 <nil>}:
    Command stdout:
    
    stderr:
    Error: unknown command "log" for "kubectl"
    
    Did you mean this?
    	top
    	logs
    
    Run 'kubectl --help' for usage.
    
    error:
    exit status 1
```

`kubectl log` was removed in #78098

**Anything else we need to know**:

PR with fix here: https://github.com/kubernetes/kubernetes/pull/82202

### PR DESCRIPTION
**Pull request by odinuge**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind failing-test

**What this PR does / why we need it**:

Fixes failing tests.

kubectl log will be removed in 1.16, see PR with more info #78098

**Which issue(s) this PR fixes**:

Fixes #82201

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
this should probably be targeting the master branch instead of release-1.15?

/priority important-soon

**Comment by liggitt** [comment]
This was already done in master. This exists because 1.15 branch tests run with kubectl built from master in skew tests 😕

**Comment by BenTheElder** [comment]
Are we allowed to change conformance tests after the minor release ...?

**Comment by dims** [comment]
cc @timothysc

**Comment by liggitt** [comment]
When it's accidentally using a function deprecated since 1.2 (https://github.com/kubernetes/kubernetes/pull/15232/files#diff-f8bdb334f93a2f74fd5faa9c3181b4bfL89) instead of the replacement, I would hope we can fix that

**Comment by odinuge** [comment]
There was also some relevant discussion about this in the original PR removing `kubectl log`, https://github.com/kubernetes/kubernetes/pull/78098#discussion_r285585719. Since no one has added a hold, I guess this is ok, but in case we need more discussion, feel free to `/hold` and `/unhold`

Upping the priority ref. parent issue #82201

/priority critical-urgent
/cc alejandrox1
ping @kubernetes/release-team

**Review by dims — APPROVED** [review]
/lgtm

**Review by soltysh — APPROVED** [review]

**Comment by soltysh** [comment]
/assign @bubblemelon
for 1.15 cherry-pick approval

**Comment by feiskyer** [comment]
lgtm

**Pull request merged**
