### PR TITLE
Remove CSIDriver informer

### LINKED ISSUE #68261: Ensure that csiDriver informers are synced before use
We aren't checking if informers are synced before using them - https://github.com/kubernetes/kubernetes/pull/67945#discussion_r215105859

We should ensure that, informers are synced before use in kubelet/attach-detach controller.

/sig storage
/assign

### PR DESCRIPTION
**Pull request by jsafrane**
In current release the CSIDriver CRD is only optional. It makes the informer racy, see #68261.

We should restore the informer when CRD is installed by a kubernetes component on cluster startup.

Fixes #68261

**Release note**:

```release-note
Fixed race condition when CSIDriver CRD is used.
```

/sig storage
/kind bug
@davidz627 @saad-ali @msau42

### CODE REVIEW

**Comment by verult** [comment]
This PR should fix https://github.com/kubernetes/kubernetes/issues/69480 as well

**Comment by verult** [comment]
Are we still proceeding with this PR?

**Comment by msau42** [comment]
We are moving the CRDs back to in-tree api objects, so I don't think this is needed anymore

**Comment by verult** [comment]
Since in-tree objects will move to beta directly, should this be addressed for alpha clusters still?

**Comment by msau42** [comment]
No, I don't think we need to solve it for alpha

**Pull request closed without merging**
