### PR TITLE
Automated cherry pick of #119800: Fixes CEL estimated cost to propagate result sizes correctly

### PR DESCRIPTION
**Pull request by jpbetz**
Cherry pick of #119800 on release-1.28.

#119800: Fixes CEL estimated cost to propagate result sizes correctly

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fixed a bug where CEL expressions in CRD validation rules would incorrectly compute a high estimated cost for functions that return strings, lists or maps.
The incorrect cost was evident when the result of a function was used in subsequent operations.
```

### CODE REVIEW

**Comment by jpbetz** [comment]
/hold
Until https://github.com/kubernetes/kubernetes/pull/119800 merges

**Comment by jpbetz** [comment]
/hold cancel
This is ready to backport. Since the fix is for an beta feature we didn't try to rush it into 1.28.0.

/assign @ameukam

**Comment by jpbetz** [comment]
This is updated with fixes from https://github.com/kubernetes/kubernetes/pull/120097 and ready to merge. It needs a new LGTM.

**Review by Verolop — COMMENTED** [review]
/lgtm

**Pull request merged**
