### PR TITLE
fix test/e2e/network

### PR DESCRIPTION
**Pull request by hwdef**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

use log functions of core framework

**Which issue(s) this PR fixes**:

Ref #81427

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by s-ito-ts** [comment]
It seems that the base code on this PR is not latest version.
It is necessary to create PR based on latest code.

**Comment by hwdef** [comment]
@s-ito-ts 
It is the latest code.
I closed two PRs.
[#81991](https://github.com/kubernetes/kubernetes/pull/81991)
[#81988](https://github.com/kubernetes/kubernetes/pull/81988)

**Comment by hwdef** [comment]
@s-ito-ts 
sorry about that.
I forget it.
I will close this pr and open a new one.

**Pull request closed without merging**
