### PR TITLE
Add yujuhong to test/e2e_node/OWNERS

### PR DESCRIPTION
**Pull request by yujuhong**

### CODE REVIEW

**Comment by yujuhong** [comment]
I promise I won't abuse the power. Feel free to veto this as an existing OWNER. I am happy to continue redirecting the PRs for approval.

**Comment by tallclair** [comment]
/lgtm

> I promise I won't abuse the power.

We'll need that signed in blood though.

**Comment by yujuhong** [comment]
@tallclair need your /approve no-issue

**Pull request merged**
