### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by jjjungkim**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

fix typo

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```None

```

### CODE REVIEW

**Comment by jjjungkim** [comment]
@laxmikantbpandhare , @puerco 

can you check my PR? thank you ~

**Review by laxmikantbpandhare — APPROVED** [review]
I am not sure if I have access to lgtm this PR.

/lgtm

**Comment by jjjungkim** [comment]
@cpanato 

Can you assign my PR ? Thank you ~

**Comment by cpanato** [comment]
/approve

i think it is fine, not sure, can you confirm @xmudrii thanks

**Review by xmudrii — APPROVED** [review]
I think this is fine.
/lgtm
/approve

**Pull request merged**
