### PR TITLE
replace iteration with hashmap in *state_of_world

### PR DESCRIPTION
**Pull request by xiaoanyunfei**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
We should use `map[name]` to find object in map instead of iteration
Include some other cleanup

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/sig node
/sig storage

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/ok-to-test

thanks for this clean up

**Comment by jingxu97** [comment]
Thanks for the PR!

/lgtm

**Comment by xiaoanyunfei** [comment]
@mattjmcnaughton @jingxu97 @saad-ali 
Needs approved label

**Comment by mattjmcnaughton** [comment]
> @mattjmcnaughton @jingxu97 @saad-ali
> Needs approved label

cc @saad-ali 

they are the one w/ approval permissions :)

**Pull request merged**
