### PR TITLE
Make CA valid 1 hour in the past

### PR DESCRIPTION
**Pull request by champtar**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
When running kubeadm / installing k8s early during boot, the CA certificate can be generated before time is synchronised and time is jumped backward.
Make notBefore 1 hour in the past to accept small clock jump.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by champtar** [comment]
Should we add `area/kubeadm` and `sig/cluster-lifecycle` ? The only usage of NewSelfSignedCACert() outside of tests is cmd/kubeadm/app/util/pkiutil/pki_helpers.go

**Comment by neolit123** [comment]
for context, we had a related duscussion in the past
https://github.com/kubernetes/kubernetes/issues/76714

IMO, if we are changing notBefore for CA certs, with one hour padding we should also do it for other certs. @champtar WDYT?

> Should we add `area/kubeadm` and `sig/cluster-lifecycle` ? The only usage of NewSelfSignedCACert() outside of tests is cmd/kubeadm/app/util/pkiutil/pki_helpers.go

the k/k usage may only be by kubeadm, but there could be other external direct users of client go.

**Comment by champtar** [comment]
> for context, we had a related duscussion in the past #76714
> 
> IMO, if we are changing notBefore for CA certs, with one hour padding we should also do it for other certs. @champtar WDYT?

This is the only place in k/k where NotBefore == time.Now()

```
$ git grep 'CreateCertificate(' | grep -v test
cmd/kubeadm/app/util/pkiutil/pki_helpers.go:	certDERBytes, err := x509.CreateCertificate(cryptorand.Reader, &certTmpl, caCert, key.Public(), caKey)
pkg/controller/certificates/authority/authority.go:	der, err := x509.CreateCertificate(rand.Reader, tmpl, ca.Certificate, cr.PublicKey, ca.PrivateKey)
staging/src/k8s.io/client-go/util/cert/cert.go:	certDERBytes, err := x509.CreateCertificate(cryptorand.Reader, &tmpl, &tmpl, key.Public(), key)
staging/src/k8s.io/client-go/util/cert/cert.go:	caDERBytes, err := x509.CreateCertificate(cryptorand.Reader, &caTemplate, &caTemplate, &caKey.PublicKey, caKey)
staging/src/k8s.io/client-go/util/cert/cert.go:	derBytes, err := x509.CreateCertificate(cryptorand.Reader, &template, caCertificate, &priv.PublicKey, caKey)
vendor/go.etcd.io/etcd/client/pkg/v3/transport/listener.go:	derBytes, err := x509.CreateCertificate(rand.Reader, &tmpl, &tmpl, &priv.PublicKey, priv)
```

In the kubeadm case NotBefore == ca.NotBefore
https://github.com/kubernetes/kubernetes/blob/1193ab62e2e1acb53edf5348df6fe018cbe49e82/cmd/kubeadm/app/util/pkiutil/pki_helpers.go#L664

In pkg/controller/certificates/authority there is already some backdate logic
https://github.com/kubernetes/kubernetes/blob/1193ab62e2e1acb53edf5348df6fe018cbe49e82/pkg/controller/certificates/authority/policies.go#L90

In client-go in GenerateSelfSignedCertKeyWithFixtures() there is already -1hour (that's why I picked 1h)
https://github.com/kubernetes/kubernetes/blob/1193ab62e2e1acb53edf5348df6fe018cbe49e82/staging/src/k8s.io/client-go/util/cert/cert.go#L103-L104

> > Should we add `area/kubeadm` and `sig/cluster-lifecycle` ? The only usage of NewSelfSignedCACert() outside of tests is cmd/kubeadm/app/util/pkiutil/pki_helpers.go
> 
> the k/k usage may only be by kubeadm, but there could be other external direct users of client go.

Good point, if we want to be safe I can introduce a new function that take NotBefore as parameter and not change the behavior for everyone, please tell me what is preferred

**Comment by neolit123** [comment]
thanks for the info.

> In client-go in GenerateSelfSignedCertKeyWithFixtures() there is already -1hour (that's why I picked 1h)

+1 given we already have this in other places and it was discussed before.

> Good point, if we want to be safe I can introduce a new function that take NotBefore as parameter and not change the behavior for everyone, please tell me what is preferred

unclear what is better. likely the -1h padding without opt-out is fine. i can lgtm, but approval is up to api machinery (owners of client go).

/lgtm

**Comment by neolit123** [comment]
/release-note-edit

```release-note
client-go: make generated CA certificates valid 1 hour in the past (NewSelfSignedCACert). Applies to CA certificates generated by kubeadm.
```

owners: please adjust the note if needed

**Comment by neolit123** [comment]
/release-note-edit

```release-note
client-go: make generated CA certificates valid 1 hour in the past (NewSelfSignedCACert). Applies to CA certificates and other certificates generated by kubeadm.
```

owners: please adjust the note if needed

**Comment by aojea** [comment]
This function is exported from client-go, is this really safe to do?

**Comment by neolit123** [comment]
> This function is exported from client-go, is this really safe to do?

i think the change is fine based on prior discussions.
https://github.com/kubernetes/kubernetes/issues/76714#issuecomment-575257922
but as i noted earlier api machinery should take a look.

@champtar , your backports state "feature". we don't backport features per se. usually it has to be a blocking bug..

**Comment by champtar** [comment]
> @champtar , your backports state "feature". we don't backport features per se. usually it has to be a blocking bug fix..

I just copied the kind/feature from this PR.

It's blocking for my use case because I want to start as fast as possible, so before time sync, and the install fails if there is a time jump just after certificate generation, and I don't have a workaround except this PR.
So it's a blocking bug fix for me, but for k8s is it a bug fix ?

**Comment by neolit123** [comment]
> It's blocking for my use case because I want to start as fast as possible, so before time sync, and the install fails if there is a time jump just after certificate generation, and I don't have a workaround except this PR.

a slightly involved workaround for kubeadm would be to sign your own CA/certs/keys.

> So it's a blocking bug fix for me, but for k8s is it a bug fix ?

i think the client-go owners should take a look at this PR and the backports.

**Comment by champtar** [comment]
> > It's blocking for my use case because I want to start as fast as possible, so before time sync, and the install fails if there is a time jump just after certificate generation, and I don't have a workaround except this PR.
> 
> a slightly involved workaround for kubeadm would be to sign your own CA/certs/keys.

openssl doesn't provide an easy way to put the not before time in the past, my simplest workaround involved using `faketime` + `openssl` and some certificates templates, but that's seemed a lot compared to a 1 line change

> > So it's a blocking bug fix for me, but for k8s is it a bug fix ?
> 
> i think the client-go owners should take a look at this PR and the backports.
> 
> EDIT: you can ping #sig-api-machinery on k8s slack.

Will do, thanks

**Comment by aojea** [comment]
/assign @enj @deads2k @jpbetz 

This is exposed and used in more places that kubeadm , it will be better if both sig-auth and sig-apimachinery sign on this and on the backports to be completely sure and have consensus

**Comment by champtar** [comment]
Slack discussion: https://kubernetes.slack.com/archives/C0EG7JC6T/p1687815949656259

**Comment by neolit123** [comment]
/release-note-edit

```release-note
NONE
```

**Pull request merged**
