### PR TITLE
Automated cherry pick of #67504: Decrease CPU requests of master components in two times.

### PR DESCRIPTION
**Pull request by loburm**
Cherry pick of #67504 on release-1.11.

#67504: Decrease CPU requests of master components in two times.

### CODE REVIEW

**Comment by nikhita** [comment]
Closing and reopening to retrigger prow to remove the `do-not-merge/cherry-pick-not-approved` label.

/assign

**Comment by nikhita** [comment]
/unassign

The labels are fixed now. :+1:

**Comment by nikhita** [comment]
This PR looks like it's ready to merge. Just needs a release note update.

**Comment by loburm** [comment]
@nikhita original PR has a label, should I copy it to this PR?

**Comment by nikhita** [comment]
/retest

Thanks for removing the do-not-merge, @foxish!

**Pull request merged**
