### PR TITLE
Ensure the GCI metadata files do not have newline at the end

### LINKED ISSUE #36708: ci-kubernetes-node-kubelet: broken test run
Failed: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubelet-gce-e2e-ci/11108/

Run so broken it didn't make JUnit output!

### PR DESCRIPTION
**Pull request by Amey-D**
Fixes #36708

@dchen1107 @Random-Liu  can one of you help with the review?

cc @kubernetes/goog-image FYI

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM

**Comment by Random-Liu** [comment]
@Amey-D Thanks for the fix.

If I use vim to open a file, and type `update_disabled`. Then use this file as metadata.

However, `echo -n update_disabled` does work.

I need to figure out what is added by vim. :/

**Comment by Random-Liu** [comment]
OK. Vim adds EOL at the end of each line automatically http://stackoverflow.com/questions/16222530/why-do-i-need-vim-in-binary-mode-for-noeol-to-work/16224292#16224292.

If I generate the file with `echo -n update_disabled`, it will work.
If I open the same file with vim, and save it, it won't work anymore.

Anyhow, at least it's clear that this PR will work! :)

**Comment by yujuhong** [comment]
The title of the PR should be "training newline" instead of whitespace :-)
Please also add comments to prevent regression since the logic is a bit fragile.

+1 to make the consumer of this metadata more robust. It'd also help if we surface the information/configuration. Could we add something to our e2e test framework to collect such information?

**Comment by dchen1107** [comment]
Agreed with @Random-Liu and @yujuhong the proper and more robust fix should at GCI side, not here. But I am ok to take this for short-term fix for running GCI on GCE.

**Comment by dchen1107** [comment]
Offline discussion with @Amey-D:

* We are going to fix this in GCI side for long term. @Amey-D is going to file a separate internal bug to track this. The fix in GCI is required for GCI is running outside GKE anyway.
* The current fix as the short term solution should be cherrypicked into both 1.4 and 1.5 release. 

cc/ @kubernetes/goog-node @kubernetes/goog-image @saad-ali for 1.5 @jessfraz for 1.4

**Comment by jessfraz** [comment]
thanks!

**Comment by jessfraz** [comment]
cherry-picked in https://github.com/kubernetes/kubernetes/pull/38781

**Comment by saad-ali** [comment]
Cherry-picked to 1.5 in #40184

**Pull request merged**
