### PR TITLE
Automated cherry pick of #48786 upstream release 1.6

### PR DESCRIPTION
**Pull request by janetkuo**
Cherrypick #48786 to fix a regression in 1.6

/approve no-issue

### CODE REVIEW

**Comment by janetkuo** [comment]
/test pull-kubernetes-unit

`k8s.io/kubernetes/federation/pkg/kubefed/init TestCertsTLS` test failure seems unrelated to this change

**Comment by janetkuo** [comment]
Not sure why this test keeps failing: `k8s.io/kubernetes/federation/pkg/kubefed/init TestCertsTLS`
I cannot reproduce this test failure locally. 

/test pull-kubernetes-unit

**Comment by enisoc** [comment]
The failure looks like #47304. I will try to cherrypick #48683.

**Comment by wojtek-t** [comment]
I'm temporarily adding do-not-merge label due to some problems with release branch. Will remove it once we figure it out.

**Comment by enisoc** [comment]
@wojtek-t This is a 1.6 cherrypick. Are you referring to problems on the release-1.6 branch? If so, what are the problems?

**Comment by wojtek-t** [comment]
@enisoc - oops sorry. No, I didn't want to touch 1.6 release branch.

**Comment by fejta** [comment]
FYI: https://github.com/kubernetes/kubernetes/pull/48312#issuecomment-315884618

**Pull request merged**
