### PR TITLE
ensure iptables rules prepend at the top of the chain for kube-proxy ipvs mode

### PR DESCRIPTION
**Pull request by xujieasd**
**What this PR does / why we need it**:

Kube-proxy ipvs mode generate some iptables rules (`KUBE-SERVICES` `KUBE-POSTROUTING`) to do SNAT
These rules are expected to be prepended (`iptables -I`) at corresponding chain. But currently, if rule exists, kube-proxy will do nothing. So cannot ensure these rules always at the top of the chain.
It will cause some network traffic not work.
This PR add a function to ensure rules prepend at the top of the chain

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
This PR add a new function `EnsurePrependRule` instead of `EnsureRule`, `EnsurePrependRule` will
1. check if iptables rule exists in given chain
2. if rule not exists, prepend the rule
3. if rule exists, check rule sequence
4. if rule already at the top of the chain, just return
5. if not, delete the rule and re-prepend the rule

/sig network
/area ipvs

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xujieasd** [comment]
should fix #66103

**Comment by danwinship** [comment]
I am dubious of this fix. What happens if the CNI plugin also tries to ensure that its rule comes first?

Also, this still doesn't guarantee that things *always* work, it just guarantees that if the CNI plugin breaks things, then kube will *eventually* reorder the rules to fix it.

It seems like the real problem is that the CNI plugin is creating an iptables rule that intercepts traffic that it shouldn't be intercepting...

**Comment by xujieasd** [comment]
@danwinship 
Well, I agree that currently we cannot ensure the behavior of other CNI plugin.

However, I think `kube-proxy` has a mechanism to maintain its rules and check whether its rules are correct.
kube-proxy has a period to sync rules, so it's not only ensure rules will update when `update event` comes, but also guarantee that its rules will not be broke by other softwares or manual broken.

since every round of sync we ensure `KUBE-SERVICES` rule exists, why not we also ensure the rules order is correct

**Comment by lystor** [comment]
Any plans to merge this fix?
Thank you

**Comment by fasaxc** [comment]
How do you know that kube-proxy's chain need to go before the CNI plugin's chains?  That depends on what the CNI plugin's chains are for. 

FWIW, Calico does try to keep its rules at the top; if kube-proxy does the same, Calico will fight with kube-proxy.  Please can you spell out which CNI plugin(s) you've seen issues with.  If Calico is on the list, we'll need to investigate the right solution so we can share the chain.

**Comment by danwinship** [comment]
@fasaxc The original issue (#66103) was about Calico, and there are a few more details there.

There's also a conversation that just started on the sig-net mailing list about trying to improve kube-proxy's use of iptables to cooperate with other users (https://groups.google.com/forum/#!topic/kubernetes-sig-network/Hw9mmMoF_88)

**Comment by fasaxc** [comment]
Calico only owns the `cali-*` chains, looks like the problematic chain was added by the host-port plugin, which Calico chains?  If so, we should try to figure out how the host port plugin could be made to play nice.  I'm guessing that its rule is simply wrong now because remote service IPs now appear to be LOCAL after IPVS mode is turned on.

**Comment by bboreham** [comment]
What if another program had the same idea?  The two will just sit in an endless battle swapping their rules to the top of the list.  This is not a good idea.

**Comment by xujieasd** [comment]
I agree that the idea in the mailing list thread is a more efficient way. My PR just only consider kube-proxy's own behavior is correct.

**Pull request closed without merging**
