### PR TITLE
[Metrics]: Add a node swap metric

### PR DESCRIPTION
**Pull request by iholder101**
#### What type of PR is this?
/kind feature
/sig node

#### What this PR does / why we need it:
Adds a node swap metric, as part of the [requirements to graduate swap to Beta1](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/2400-node-swap/README.md#beta-1).

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
A new node swap metric is now added.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/2400-node-swap/README.md#beta-1
```

### CODE REVIEW

**Comment by iholder101** [comment]
> /triage accepted /priority important-longterm

Thanks @swatisehgal!
I've decided to close this PR and to merge its logic with https://github.com/kubernetes/kubernetes/pull/118865.
Would you mind triaging and prioritizing it instead?

In addition, this is intended to get into k8s 1.28. Maybe we need a higher priority?

Thanks a lot in advance!

/close

**Comment by swatisehgal** [comment]
> > /triage accepted /priority important-longterm
> 
> Thanks @swatisehgal! I've decided to close this PR and to merge its logic with #118865. Would you mind triaging and prioritizing it instead?

Sure, will triage that PR.
> In addition, this is intended to get into k8s 1.28. Maybe we need a higher priority?

Ack, I missed that this was being targeted for 1.28, will bump the priority.

**Pull request closed without merging**
