### PR TITLE
fix: add pod info to the error log

### PR DESCRIPTION
**Pull request by HecarimV**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
add pod info to the error log
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by endocrimes — APPROVED** [review]
/triage accepted
/priority backlog
/lgtm

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
