### PR TITLE
kube-apiserver: keep the types of LeaseEndpointReconcilerType and NoneEndpointReconcilerType the same as MasterCountReconcilerType

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
A small code cleanup: keep the types of `LeaseEndpointReconcilerType` and `NoneEndpointReconcilerType` the same as `MasterCountReconcilerType`

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
we started deprecation of `MasterCountReconcilerType` , should we make it the other way around and remove `Type` and work with the constant strings?

/assign @liggitt

**Comment by liggitt** [comment]
the intent was to have these be typed values, so fixing up the declarations as a standalone cleanup seems fine, regardless of whatever else we do

/lgtm
/approve

**Pull request merged**
