### PR TITLE
Update Elasticsearch cluster logging to use v1.9 image

### PR DESCRIPTION
**Pull request by satnam6502**
Following on from PR #12942 to address #7345 I have now pushed the image to gcr.io and we can now update the Elasticsearch controller config.

### CODE REVIEW

**Comment by satnam6502** [comment]
Please wait... do not merge until I verify...

**Comment by satnam6502** [comment]
So this change seems to be working. Ready for review and then merge.

screenshot from 2015-08-19 16 09 04

**Comment by satnam6502** [comment]
@k8s-bot ok to test

**Comment by vishh** [comment]
LGTM. Thanks for the update @satnam6502

**Pull request merged**
