### PR TITLE
update copyed doc for advanced audit

### PR DESCRIPTION
**Pull request by CaoShuFeng**
doc for WithAudit is copyed from WithLegacyAudit, it's out of date.
This change update doc for these two functions.

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
@k8s-bot ok to test

**Comment by CaoShuFeng** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this
@k8s-bot pull-kubernetes-verify test this

**Comment by CaoShuFeng** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by CaoShuFeng** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by CaoShuFeng** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by CaoShuFeng** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
