### PR TITLE
Bump heapster version

### PR DESCRIPTION
**Pull request by mksalawa**
Bump heapster version to v1.2.0-beta.1.
Migrate metrics tests and HPA to use List objects introduced in the new version.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30993)

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

cc @mwielgus @kubernetes/heapster-maintainers

**Comment by piosz** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by piosz** [comment]
We need bump godeps also

**Comment by piosz** [comment]
LGTM, thanks

**Comment by piosz** [comment]
@k8s-bot unit test this issue: #30947

**Comment by eparis** [comment]
I see no explanation why this is a p2. Can you explain?

**Pull request merged**
