### PR TITLE
Updated k8petstore example to use non-default namespace.

### LINKED ISSUE #24314: Updated example to use non-default namespace
During the review of #23537, it's better to also update `openshift` and `k8s-pet-store` to use non-default namespace.

cc @eparis .

### PR DESCRIPTION
**Pull request by k82cn**
fixes #24314

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30777)

### CODE REVIEW

**Comment by bgrant0607** [comment]
@k82cn Please update the README to provide instructions about how to view the resources in the now non-default namespace.

cc @jayunit100

**Comment by pwittrock** [comment]
@ymqytw Would you try the example with the updates and make sure it works for you?

**Comment by ymqytw** [comment]
@pwittrock Yes, I will try them right now.

**Comment by ymqytw** [comment]
The examples don't work very well on my end.

**Comment by k82cn** [comment]
@ymqytw / @pwittrock , thanks for your input; let me double check the patches.

**Comment by ymqytw** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[examples/k8petstore/k8petstore-loadbalancer.sh, line 54 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777#-KPsr_XcdHC8tEHYf6G6:-KPsr_XcdHC8tEHYf6G7:b-a86duw) ([raw file](https://github.com/kubernetes/kubernetes/blob/e790c82255df22fa3396a0e07ea5ec53d49441a3/examples/k8petstore/k8petstore-loadbalancer.sh#L54)):*
> ```Shell
> cat << EOF > ns.json
> {
>   "apiVersion": "v1"
> ```

Missing comma.

---

*[examples/k8petstore/k8petstore-loadbalancer.sh, line 57 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777#-KPsrcjY1YzGpyfLlrZT:-KPsrcjY1YzGpyfLlrZU:b7fi9ys) ([raw file](https://github.com/kubernetes/kubernetes/blob/e790c82255df22fa3396a0e07ea5ec53d49441a3/examples/k8petstore/k8petstore-loadbalancer.sh#L57)):*
> ```Shell
>   "kind": "Namespace"
>   "metadata": {
>     "name": "kube-system"
> ```

Should it be "$NS"?

---

*[examples/k8petstore/k8petstore-nodeport.sh, line 56 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777#-KPsrOY3X4IQcuP9QqO3:-KPsrOY3X4IQcuP9QqO4:b-a86duw) ([raw file](https://github.com/kubernetes/kubernetes/blob/e790c82255df22fa3396a0e07ea5ec53d49441a3/examples/k8petstore/k8petstore-nodeport.sh#L56)):*
> ```Shell
> cat << EOF > ns.json
> {
>   "apiVersion": "v1"
> ```

Missing comma.

---

*[examples/k8petstore/k8petstore-nodeport.sh, line 59 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777#-KPsrIpnZ98LiIbh0V-w:-KPsrIpnZ98LiIbh0V-x:b7fi9ys) ([raw file](https://github.com/kubernetes/kubernetes/blob/e790c82255df22fa3396a0e07ea5ec53d49441a3/examples/k8petstore/k8petstore-nodeport.sh#L59)):*
> ```Shell
>   "kind": "Namespace"
>   "metadata": {
>     "name": "kube-system"
> ```

Should it be "$NS"?

---

*[examples/k8petstore/k8petstore.sh, line 56 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777#-KPsrU2VXtytIifOgCuP:-KPsr14SZKtkAj6URANi:b-a86duw) ([raw file](https://github.com/kubernetes/kubernetes/blob/e790c82255df22fa3396a0e07ea5ec53d49441a3/examples/k8petstore/k8petstore.sh#L56)):*
> ```Shell
> cat << EOF > ns.json
> {
>   "apiVersion": "v1"
> ```

Missing comma.

---

*[examples/k8petstore/k8petstore.sh, line 59 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777#-KPsrV5slUGiVcyCJ-Rh:-KPsqrd4vjEGpgctIvTZ:b7fi9ys) ([raw file](https://github.com/kubernetes/kubernetes/blob/e790c82255df22fa3396a0e07ea5ec53d49441a3/examples/k8petstore/k8petstore.sh#L59)):*
> ```Shell
>   "kind": "Namespace"
>   "metadata": {
>     "name": "kube-system"
> ```

Should it be "$NS"?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777)*

**Comment by ymqytw** [comment]
When using NodePort, we should tell the users that some firewall rules may be needed to add to allow the traffic in, if using cloud providers' service.

**Comment by k82cn** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[examples/k8petstore/k8petstore-loadbalancer.sh, line 54 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777#-KPsr_XcdHC8tEHYf6G6:-KPu4QSW91NfdnH7iiiQ:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/e790c82255df22fa3396a0e07ea5ec53d49441a3/examples/k8petstore/k8petstore-loadbalancer.sh#L54)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Missing comma.
</details>
Done.

---

*[examples/k8petstore/k8petstore-loadbalancer.sh, line 57 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777#-KPsrcjY1YzGpyfLlrZT:-KPu4gGVGgHMW3GCMLBD:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/e790c82255df22fa3396a0e07ea5ec53d49441a3/examples/k8petstore/k8petstore-loadbalancer.sh#L57)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Should it be "$NS"?
</details>
Done.

---

*[examples/k8petstore/k8petstore-nodeport.sh, line 56 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777#-KPsrOY3X4IQcuP9QqO3:-KPu4jXcRCCHX2DwYxVy:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/e790c82255df22fa3396a0e07ea5ec53d49441a3/examples/k8petstore/k8petstore-nodeport.sh#L56)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Missing comma.
</details>
Done.

---

*[examples/k8petstore/k8petstore-nodeport.sh, line 59 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777#-KPsrIpnZ98LiIbh0V-w:-KPu4kXS2gmpb5dt4RMo:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/e790c82255df22fa3396a0e07ea5ec53d49441a3/examples/k8petstore/k8petstore-nodeport.sh#L59)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Should it be "$NS"?
</details>
Done.

---

*[examples/k8petstore/k8petstore.sh, line 56 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777#-KPsrU2VXtytIifOgCuP:-KPu4maqLjIH3XgI7kif:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/e790c82255df22fa3396a0e07ea5ec53d49441a3/examples/k8petstore/k8petstore.sh#L56)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Missing comma.
</details>
Done.

---

*[examples/k8petstore/k8petstore.sh, line 59 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777#-KPsrV5slUGiVcyCJ-Rh:-KPu4oDhqz8VS-nl6Y4C:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/e790c82255df22fa3396a0e07ea5ec53d49441a3/examples/k8petstore/k8petstore.sh#L59)):*
<details><summary><i>Previously, ymqytw (Mengqi Yu) wrote…</i></summary>
> Should it be "$NS"?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777)*

**Comment by k82cn** [comment]
I think we can just highlight it and redirect to the document about NodePart :). Is it OK to you?

---

Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777#-:-KPu4sPw2-51tHTGySpH:b-u0wtae)*

**Comment by k82cn** [comment]
@pwittrock / @ymqytw , do you think we need to update other example to add namespace?

**Comment by k82cn** [comment]
@ymqytw , there's already some description about Nodeport in README; is this enough?


>Should we use PublicIP, NodePort, Cloud loadbalancers ?
>
>The original k8petstore used PUBLIC_IP fields to bind the web app to an IP.
>
>However... because the public IP was deprecated in Kubernetes v1, we provide other 2 scripts k8petstore-loadbalancer.sh and k8petstore-nodeport.sh. As the names suggest, they rely on LoadBalancer and NodePort respectively. More details can be found here.
>
>We will continue to try to update k8petstore to use the idiomatic networking tools that kubernetes supports, if we fall behind, please create an issue !

---

Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777#-:-KQKB-JYSdix2-tA1e2j:b-9h3tre)*

**Comment by k82cn** [comment]
Tested it in miniKube :)

---

Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777#-:-KQKC-p6Si4gMaKQZbIo:b-gxlubp)*

**Comment by ymqytw** [comment]
@k82cn Right. Should be enough.

---

Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777#-:-KQM9ycdlRP55jAlx98I:bssvozv)*

**Comment by k82cn** [comment]
@pwittrock / @ymqytw , any more comments :).

**Comment by pwittrock** [comment]
@k82cn Sorry I have been slammed managing stuff for the 1.4 release in 2 weeks.  I am dropping most of my other responsibilities on the floor, including this.  Re-assigned to Jessie.

**Comment by jfrazelle** [comment]
lgtm

**Comment by k82cn** [comment]
@ymqytw, is the latest patch ok for you? if it's ok, would you help to mark your comments?

---

Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777#-:-KRBcXNXIfBntNQhaCl_:bog4olm)*

**Comment by ymqytw** [comment]
@k82cn Yes, it's OK. Don't worry about the comments in reviewable. You branch can be merged as long as you pass all required checks and has "lgtm" label.

**Comment by k82cn** [comment]
> @k82cn Yes, it's OK. Don't worry about the comments in reviewable. You branch can be merged as long as you pass all required checks and has "lgtm" label.

Thanks :). Not sure the feature of this "reviewable"; but it seems the review phase has hang for a few days.

---

Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30777#-:-KRGhg5C1d6sNFnxrXAr:b-46paeg)*

**Comment by ymqytw** [comment]
@k82cn You can check the submit queue http://submit-queue.k8s.io/#/queue. It seems your PR is already in the queue.

**Comment by k82cn** [comment]
Got that, thanks :).

**Pull request merged**
