### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by corehello**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix typo

**Which issue(s) this PR fixes**:

Fixes #
* fix typo for `ServiceAccount`

### CODE REVIEW

**Comment by corehello** [comment]
re-check CLA

**Comment by bl-ue** [comment]
@corehello you can close and re-open the PR to fix the CLA.

**Comment by corehello** [comment]
I signed it

**Comment by corehello** [comment]
> @corehello you can close and re-open the PR to fix the CLA, if you've signed it and it won't update.
I have no idea if it will re-check, but let me have a try within this PR.

**Pull request closed without merging**
