### PR TITLE
Consistent job/cronjob controller naming styles

### PR DESCRIPTION
**Pull request by daniel-hutao**
Signed-off-by: Daniel Hu <farmer.hutao@outlook.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The naming style of the job/cronjob controller should be consistent with other controllers in controller-manager. For example, the name of the deployment controller is called DeploymentController, which is a clear and readable naming method. The job/cronjob's controller is called Controller, which is not friendly to users.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by daniel-hutao** [comment]
@krmayankk @aojea Could you please take a look at this pr, thx.

**Comment by aojea** [comment]
Current naming style follows the golang naming conventions https://golang.org/doc/effective_go#package-names

> For instance, the buffered reader type in the bufio package is called Reader, not BufReader, because users see it as bufio.Reader, which is a clear, concise name. Moreover, because imported entities are always addressed with their package name, bufio.Reader does not conflict with io.Reader. Similarly, the function to make new instances of ring.Ring—which is the definition of a constructor in Go—would normally be called NewRing, but since Ring is the only type exported by the package, and since the package is called ring, it's called just New, which clients of the package see as ring.New. Use the package structure to help you choose good names.

I personally find easier to read ` job.NewController`  than ` job.NewJobController`

**Comment by daniel-hutao** [comment]
> Current naming style follows the golang naming conventions https://golang.org/doc/effective_go#package-names
> 
> > For instance, the buffered reader type in the bufio package is called Reader, not BufReader, because users see it as bufio.Reader, which is a clear, concise name. Moreover, because imported entities are always addressed with their package name, bufio.Reader does not conflict with io.Reader. Similarly, the function to make new instances of ring.Ring—which is the definition of a constructor in Go—would normally be called NewRing, but since Ring is the only type exported by the package, and since the package is called ring, it's called just New, which clients of the package see as ring.New. Use the package structure to help you choose good names.
> 
> I personally find easier to read ` job.NewController` than ` job.NewJobController`

@aojea 
I agree with your opinion, `job.NewController` is easier to read. But like `replicaset.NewReplicaSetController` `namespacecontroller.NewNamespaceController` `deployment.NewDeploymentController` …… 
All other controller besides job/cronjob controller is named as xxxController. I think the coding style should be unified. In contrast, job/cronjob is a minority, so the modification cost is lower.

**Comment by aojea** [comment]
that sounds more like a code-organization thing, there is people working on that area I defer to them then :)
/area code-organization

**Comment by fedebongio** [comment]
This seems to be mainly sig apps
/remove-sig api-machinery

**Comment by jpmartins201** [comment]
Does this PR still in need of contributions?

**Comment by dims** [comment]
Is this PR still needed, please rebase if so (or we can close it?)

**Comment by daniel-hutao** [comment]
> Is this PR still needed, please rebase if so (or we can close it?)

@dims If this PR is still nedded, I'd like to rebase and keep doing it. Maybe I don't know what can I do now.

**Comment by dims** [comment]
This PR is older than 4 weeks and needs as rebase.

Please rebase the PR against latest master and reopen if still needed.

/close

**Pull request closed without merging**
