### PR TITLE
Add go.work because there are multiple go modules in this repo

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This PR adds a `go.work` at the top of the repository to properly describe the fact that there are multiple go modules in this repo.
I need it to make gopls happy.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@MikeSpreitzer

**Comment by MikeSpreitzer** [comment]
There is much more to be done before go.work can go in the repo.

**Comment by aojea** [comment]
it is over 95 commits today https://github.com/kubernetes/kubernetes/pull/110374 and counting 😄

**Pull request closed without merging**
