### PR TITLE
Fix codecgen sort

### PR DESCRIPTION
**Pull request by thockin**
Fix the codecgen sort to compare package names rather than file globs.  I added debugging but will comment it out after Jenkins shows me this works.

### CODE REVIEW

**Comment by lavalamp** [comment]
This would be an alternative to #25227.

**Comment by lavalamp** [comment]
@wojtek-t is it really that bad if it emits some redundant code? What if we just sorted it alphabetically and call it a day?

**Comment by thockin** [comment]
Passes cleanly on my laptop.  Waiting for jenkins.

**Comment by thockin** [comment]
Everything passed.  I have now commented out the dbg code and removed the old logic.  PTAL for prio merge.

**Comment by thockin** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by thockin** [comment]
all green, ready for review

**Comment by wojtek-t** [comment]
LGTM - thanks a lot for the fix!

**Comment by wojtek-t** [comment]
Merging manually - risk is very low.

**Comment by luxas** [comment]
@thockin @wojtek-t Thanks a lot!

**Pull request merged**
