### PR TITLE
clean up useless variables in deviceplugin/types.go

### PR DESCRIPTION
**Pull request by tianshapjq**
**What this PR does / why we need it**:
some variables is useless for reasons, I think we need a clean up.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```NONE

### CODE REVIEW

**Review by rohitagarwal003 — APPROVED** [review]
/lgtm

**Comment by RenaudWasTaken** [comment]
/retest
I'm not sure why this PR is not getting through.

**Pull request merged**
