### PR TITLE
Remove the condition for only wait for KMS key is used

### LINKED ISSUE #71750: Kubernetes trying to attach non-available volume
**What happened**:

Kubernetes tries to attach EBS volumes while their status is still `creating`:

```
Events:
  Type     Reason                  Age                From                                  Message
  ----     ------                  ----               ----                                  -------
  Warning  FailedScheduling        19s (x6 over 28s)  default-scheduler                     pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled               19s                default-scheduler                     Successfully assigned default/app to ip-172-18-0-74.ec2.internal
  Warning  FailedAttachVolume      15s (x4 over 19s)  attachdetach-controller               AttachVolume.Attach failed for volume "pvc-320dced4-eefa-11e8-a19d-0e7ca462e948" : "Error attaching EBS volume \"vol-01cce92492ab6d0b0\"" to instance "i-0fcdf055a3d119b1b" since volume is in "creating" state
  Normal   SuccessfulAttachVolume  7s                 attachdetach-controller               AttachVolume.Attach succeeded for volume "pvc-320dced4-eefa-11e8-a19d-0e7ca462e948"
  Normal   Pulling                 1s                 kubelet, ip-172-18-0-74.ec2.internal  pulling image "centos"
```
I believe this started to happen after #67812, when volumes and their tags started to be created in the same request. Before that, tags would be set through another call (i.e., `c.tagging.createTags`), which retries if the volume isn't `available`.

**What you expected to happen**:

Kubernetes should try to attach the volume only when it's available. In order to do that, `aws.CreateDisk()` should make sure the volume is `available` when it returns.

**How to reproduce it (as minimally and precisely as possible)**:

Just create a dynamically provisioned EBS volume.

/kind bug
/sig storage
/sig aws

### PR DESCRIPTION
**Pull request by leakingtapan**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind bug

**What this PR does / why we need it**:
This helps removing confusion EBS plugin error message like:

```
"Error attaching EBS volume \"vol-01cce92492ab6d0b0\"" to instance "i-0fcdf055a3d119b1b" since volume is in "creating" state
```
/cc @bertinatto @jsafrane @gnufied 

**Which issue(s) this PR fixes**:

Fixes: #71750 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by BernhardLenz** [comment]
I'm experiencing the same issue in EKS 1.12. Is there a work around for this to maybe restart the pod or similar?

**Comment by leakingtapan** [comment]
Did you wait long enough? The error could be recovered after controller retry

**Comment by BernhardLenz** [comment]
Yesterday it took quite a long time and I saw when I got back to my desk this morning that it had recovered. I tried a fresh deployment today and it only took a few minutes. I saw the fix was merged to master. How long does it take to get published on AWS or is it already available in 1.12?

**Comment by leakingtapan** [comment]
Not yet. We still need to cherry pick it back to 1.12 and 1.13 if desired

**Comment by leakingtapan** [comment]
Will be great if you can back port the fix to 1.12 and 1.13. 😀

**Pull request merged**
