### PR TITLE
Fix PipeWriter#CloseWithError race on go1.13

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind bug
/kind flake

#### What this PR does / why we need it:

We are seeing `TestLog/fail_to_follow_logs_from_multiple_requests,_if_ConsumeRequestFn_fails` flake badly on 1.18:

```
git checkout release-1.18
go test -race k8s.io/kubectl/pkg/cmd/logs -c
stress ./logs.test -test.run TestLog/follow.*multiple.*Consume

/var/folders/7f/9xt_73f12xlby0w362rgk0s400kjgb/T/go-stress-20210224T153738-442028464
--- FAIL: TestLog (0.02s)
    --- FAIL: TestLog/fail_to_follow_logs_from_multiple_requests,_if_ConsumeRequestFn_fails (0.02s)
        logs_test.go:392: expected error "Error from the ConsumeRequestFn", got none
FAIL


ERROR: exit status 1


/var/folders/7f/9xt_73f12xlby0w362rgk0s400kjgb/T/go-stress-20210224T153738-890433359
--- FAIL: TestLog (0.01s)
    --- FAIL: TestLog/fail_to_follow_logs_from_multiple_requests,_if_ConsumeRequestFn_fails (0.01s)
        logs_test.go:392: expected error "Error from the ConsumeRequestFn", got none
FAIL


ERROR: exit status 1


/var/folders/7f/9xt_73f12xlby0w362rgk0s400kjgb/T/go-stress-20210224T153738-171117666
--- FAIL: TestLog (0.01s)
    --- FAIL: TestLog/fail_to_follow_logs_from_multiple_requests,_if_ConsumeRequestFn_fails (0.01s)
        logs_test.go:392: expected error "Error from the ConsumeRequestFn", got none
FAIL


ERROR: exit status 1


/var/folders/7f/9xt_73f12xlby0w362rgk0s400kjgb/T/go-stress-20210224T153738-135234649
--- FAIL: TestLog (0.01s)
    --- FAIL: TestLog/fail_to_follow_logs_from_multiple_requests,_if_ConsumeRequestFn_fails (0.01s)
        logs_test.go:392: expected error "Error from the ConsumeRequestFn", got none
FAIL


ERROR: exit status 1

40 runs so far, 4 failures
```

parallelConsumeRequest calls `writer.CloseWithError` if there's an error in a single writer, then calls `writer.Close()` once all goroutines complete. If `writer.Close()` is called before the `_, err := io.Copy(o.Out, reader)` does its next read, it overwrites the nil error and fails the test.

This was a go bug fixed in go1.14+ in https://github.com/golang/go/commit/f45eb9ff3c96dfd951c65d112d033ed7b5e02432, so this does not affect Kubernetes 1.19+

Introduced in Kubernetes 1.14 in https://github.com/kubernetes/kubernetes/commit/2a230cc119379bcf8aa50c070f955dc1a5b81bca but not noticed because bazel unit tests retried on flakes until 1.20 (https://github.com/kubernetes/kubernetes/pull/93605), at which point the golang bug was already fixed.

This is a targeted bugfix for 1.18 which also cleans up the nastiest test flake we have:

image

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
/assign @soltysh 
as approver on the PR that added this

/assign @BenTheElder @spiffxp 
relevant to the new test job that uses `make test` and will notice single-run flakes on release-1.18

cc @kubernetes/release-managers 
not sure what to do with this... it's a fix that isn't necessary on release-1.19+ branches... I can bring it in via `master` and backport to all release branches if you prefer... but that seems weird for an issue isolated to versions < 1.19

**Comment by justaugustus** [comment]
> but that seems weird for an issue isolated to versions < 1.19

@liggitt -- Yep, I think it's probably fine that we limit the fix to 1.18.z.

**Comment by BenTheElder** [comment]
> relevant to the new test job that uses make test and will notice single-run flakes on release-1.18

FTR: this job is currently only targeting non release branches / 1.21+ currently. I'm not sure if we'll wind up backporting that switch or not.

**Comment by liggitt** [comment]
> FTR: this job is currently only targeting non release branches / 1.21+ currently. I'm not sure if we'll wind up backporting that switch or not.

ah, ok... probably for the best, given my flake rampage only happened in 1.20

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by soltysh** [comment]
Great catch!

**Pull request merged**
