### PR TITLE
apimachinery: remove pre-apigroups import path logic

### PR DESCRIPTION
**Pull request by sttts**
Replacing #50093.

### CODE REVIEW

**Comment by sttts** [comment]
@enj interesting that this breaks the storage test.

**Comment by enj** [comment]
@sttts opened https://github.com/sttts/kubernetes/pull/10 to fix the test.

**Comment by sttts** [comment]
Double checking that this can be backported to origin.

**Comment by sttts** [comment]
@enj ptal. Removed `NewDefaultRESTMapper` as it has no additional value and confused us in https://github.com/openshift/origin/pull/15727

**Comment by sttts** [comment]
With https://github.com/openshift/origin/pull/15727 this is fine.

@smarterclayton is this approved?

**Pull request merged**
