### PR TITLE
Automated cherry pick of #66932: Include unavailable API services in discovery response

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #66932 on release-1.9.

#66932: Include unavailable API services in discovery response

```release-note
kube-apiserver now includes all registered API groups in discovery, including registered extension API group/versions for unavailable extension API servers.
```

### CODE REVIEW

**Comment by nilebox** [comment]
```
apiserver_test.go:385: Unexpected failed group version error: unable to retrieve the complete list of server APIs: wardle.k8s.io/v1alpha1: the server could not find the requested resource
```
@liggitt OK, I think I got what's wrong.
This assertion fails:
```
	if !apierrors.IsServiceUnavailable(groupVersionErr) {
		t.Logf("Unexpected failed group version error: %v", err)
		return false
	}
```
If I remember correctly you said previously that it used to return `404` instead of `503`? Can we change assertion to check for `404` or just don't check the error code at all in `1.9`?

**Comment by liggitt** [comment]
> If I remember correctly you said previously that it used to return 404 instead of 503? Can we change assertion to check for 404 or just don't check the error code at all in 1.9?

yeah, that fix went into 1.10. we should not pick this back to 1.9 without the switch to 503

/hold

**Pull request closed without merging**
