### PR TITLE
Workaround docker-wait freeze with 17.06.0

### PR DESCRIPTION
**Pull request by sttts**
Workaround https://github.com/moby/moby/issues/33948 and maybe fix kops timeouts.

### CODE REVIEW

**Comment by dims** [comment]
@sttts there was one more PR in the same area, not sure if that would help with the kops problem though - https://github.com/kubernetes/kubernetes/pull/48403/commits/546cb0c146cc85040b689428e2d27af4a8bdd6d5

**Comment by sttts** [comment]
@dims looks like a race in the other PR.

**Comment by dims** [comment]
Ack @sttts

**Comment by spiffxp** [comment]
/remove-priority P0
/priority critical-urgent
@k8s-oncall I believe this needs to be manually merged, the thinking is this fixes whatever is causing pull-kubernetes-e2e-kops-aws to timeout

**Comment by sttts** [comment]
Doesn't look good.

**Comment by spiffxp** [comment]
ref #48478

**Comment by fejta** [comment]
Theoretically if this fixes things then we shouldn't need to manually merge?

**Comment by spiffxp** [comment]
@fejta I want to agree with you and be proven wrong, fingers crossed

**Comment by krousey** [comment]
Manually merging so we don't wait on anymore flakes. It did pass the awe test, which is the major blocker.

**Comment by sttts** [comment]
Do we need this also on the 1.7 branch?

**Comment by wojtek-t** [comment]
@sttts - I'm creating a cherrypick on 1.7.

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/48804 is out for review

**Pull request merged**
