### PR TITLE
Add DCOS to getting started guide list (website)

### PR DESCRIPTION
**Pull request by karlkfi**
blocked on merge and cherry-pick of #17198 & #17689 to v1.1 branch

### CODE REVIEW

**Comment by karlkfi** [comment]
@davidopp Any idea who should review this?

**Comment by brendandburns** [comment]
LGTM

**Comment by karlkfi** [comment]
what is going on with the bot....

**Comment by lavalamp** [comment]
PRs to gh-pages need to be manually merged, apparently.

**Comment by karlkfi** [comment]
Well, it's great that this is merged, but it looks like the cherry-pick (#17712) got hung up. So the link 404's for the time being.

**Comment by lavalamp** [comment]
Looks like the cherrypick got merged. Sorry for the out-of-sequence merge!

**Comment by karlkfi** [comment]
@lavalamp It turns out cherry-picking to release-1.1 doesn't actually update the kubernetes.io docs. But no one was actually able to tell me how to do that until today. @bgrant0607 pointed me at #17983

So now I need to wait for #18034 to be approved (anybody, please?) and merged, and then I can make yet another PR against gh-pages to update the dcos guide and guide list. THEN the 404 will actually be fixed.

**Comment by eparis** [comment]
Sorry about the bot, he's going to go nuts like that any time travis isn't running, which apparently we have it disabled on this branch....

I'll try to put some brains into the bot so he only pays attention to `master` and `release-*` branches...

**Pull request merged**
