### PR TITLE
Deployment API: Updating MaxSurge and MaxUnavailable to be on desired replicas

### PR DESCRIPTION
**Pull request by nikhiljindal**
Based on discussion at https://github.com/kubernetes/kubernetes/issues/14008

cc @bgrant0607 @ghodss @ironcladlou

### CODE REVIEW

**Comment by ironcladlou** [comment]
Is this PR going to cover the implementation?

**Comment by nikhiljindal** [comment]
Deployment hasnt started using this field yet. Will make sure that it uses the updated semantic.
We are still scrambling to get all Deployment changes in for 1.1.

RollingUpdate can be updated independently.
Please feel free to send a PR for that, if you have a few cycles.

**Comment by nikhiljindal** [comment]
Jenkins failed in infra setup.
@k8 ok to test

**Comment by nikhiljindal** [comment]
Actually, I am trying to refactor the rolling_updater code a bit to share its code with Deployment.
Will change MaxSurge and MaxUnavailable in rolling_updater as part of that PR.

**Comment by ironcladlou** [comment]
lgtm

**Comment by nikhiljindal** [comment]
Adding LGTM tag as per above LGTM

**Pull request merged**
