### PR TITLE
Automated cherry pick of #72255: vendor golint

### PR DESCRIPTION
**Pull request by krzyzacy**
Cherry pick of #72255 on release-1.13.

#72255: vendor golint

### CODE REVIEW

**Comment by krzyzacy** [comment]
https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/72590/pull-kubernetes-integration/40108/
/pony shrug
/retest

**Comment by tpepper** [comment]
Is this fixing an issue in verify tests?

**Comment by krzyzacy** [comment]
@tpepper this is for eliminate depending on golint from the testing image. Currently it's dumb as simply use the version whenever we built the image: https://github.com/kubernetes/test-infra/blob/master/images/kubekins-test/Dockerfile-1.13#L80-L82

**Comment by tpepper** [comment]
> @tpepper this is for eliminate depending on golint from the testing image. Currently it's dumb as simply use the version whenever we built the image: https://github.com/kubernetes/test-infra/blob/master/images/kubekins-test/Dockerfile-1.13#L80-L82

I understand this and it seems like a valid clean up going forward.  What I'm wondering is why the "important soon" priority and cherry picks.  Have we run into problems on older branches with newer golint?

In other words, if we do not cherry pick this, what is the likelihood in the next eight to nine months that 1.11, 1.12 or 1.13 even has a problem?

**Comment by krzyzacy** [comment]
> Have we run into problems on older branches with newer golint?

It was a problem before, now golint claim to support all golang releases (https://github.com/golang/lint#installation)

We plan to clean up the legacy image/scripts in test-infra which is unfortunately not branched, without cherrypicking it will take ~9 month to get that done though :-)

**Pull request merged**
