### PR TITLE
kubectl create PersistentVolumeClaim

### PR DESCRIPTION
**Pull request by dgofman**
Create and configure a persistent volume claim
https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/
https://kubernetes.io/docs/concepts/storage/persistent-volumes/

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

Create a persistent volume claim using the kubectl create command line:
- Request a volume size
- Set volume access permission

#### Which issue(s) this PR fixes:
Fixes #
https://github.com/kubernetes/kubectl/issues/914

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Comment by dgofman** [comment]
**kubectl create persistentvolumeclaim simple --storage=1Gi --namespace default** -o yaml --dry-run=client
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: simple
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
```

**kubectl create pvc mypvc -r=1Gi -n default --storageClass manual** -o yaml --dry-run=client
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: mypvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
status: {}
```

**pvc mypvc -r=1Gi -n default -c manual --accessMode ReadOnlyMany -m ReadWriteMany** -o yaml --dry-run=client
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: mypvc
  namespace: default
spec:
  accessModes:
  - ReadOnlyMany
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
status: {}
```

**Comment by dgofman** [comment]
related to https://github.com/kubernetes/kubernetes/pull/112715

**Comment by aojea** [comment]
You should discuss these things previously with the corresponding Sig, in this case Sig-cli

https://github.com/kubernetes/kubernetes/pull/112432#issuecomment-1246878012

**Review by soltysh — CHANGES_REQUESTED** [review]
/hold
as discussed during Oct 5th SIG-CLI call (https://docs.google.com/document/d/1r0YElcXt6G5mOWxwZiXgGu_X6he3F--wKwg-9UBc29I/edit#heading=h.bcbxqkuom4wh) this will not be accepted since we're planning to move forward with https://github.com/kubernetes/kubectl/issues/914 which will be targeted replacement for new create sub-commands.

**Comment by thockin** [comment]
Why is this a hold rather than closing?

**Pull request closed without merging**
