### PR TITLE
[node registry]: remove useless param

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

remove useless params

/kind cleanup

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by juanvallejo — APPROVED** [review]

**Comment by hzxuzhonghu** [comment]
ping @deads2k

**Comment by hzxuzhonghu** [comment]
kindly ping @deads2k

**Comment by nikhita** [comment]
/retest

/assign @liggitt 
for approval

**Comment by hzxuzhonghu** [comment]
rebased to fix buid error

**Comment by nikhita** [comment]
@hzxuzhonghu :+1: can you squash the commits?

**Comment by hzxuzhonghu** [comment]
done

**Pull request closed without merging**
