### PR TITLE
StorageClass should not print the namespace column

### LINKED ISSUE #40091: kubectl get storageclasses --all-namespaces mixes columns
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
- kubectl storageclass
- kubectl storageclasses

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Kubernetes version** (use `kubectl version`):
```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: minikube v0.15.0
- **OS** (e.g. from /etc/os-release): Fedora release 25 (Twenty Five)
- **Kernel** (e.g. `uname -a`): 4.9.3-200.fc25.x86_64

**What happened**:

```sh
$ kubectl get storageclasses --all-namespaces=true
NAMESPACE        NAME                      TYPE
slow (default)   kubernetes.io/host-path   
```

**What you expected to happen**:
Either an error that namespaces and storageclasses don't mix, or an empty NAMESPACE column, or a missing NAMESPACE column :)

**How to reproduce it** (as minimally and precisely as possible):
1. Define one or more storage classes
2. Run `kubectl get storageclasses --all-namespaces=true`

**Anything else do we need to know**:

Cosmetic issue, I think I've also seen it in some other similar cases but missed to record them :(

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes #40091

### CODE REVIEW

**Comment by smarterclayton** [comment]
@kubernetes/sig-storage-pr-reviews

**Comment by jeffvance** [comment]
consistent with other code that returns an err when namespace is requested for a non-namspaced object.
/lgtm

**Comment by jsafrane** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot unit test this
@k8s-bot gci gke e2e test this
@k8s-bot cvm gke e2e test this
@k8s-bot cvm gce e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot unit test this

**Pull request merged**
