### PR TITLE
remove some dead code in cmd/kube-proxy

### PR DESCRIPTION
**Pull request by danwinship**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Just removes some unused stuff left behind by past rewrites

/sig network
/priority backlog
/triage accepted
/release-note-none
/assign @aojea

### CODE REVIEW

**Comment by danwinship** [comment]
ok, wasn't sure if
/release-note-none
worked in the initial comment or not. that's lame

**Comment by aojea** [comment]
```
W0314 14:58:32.590] # k8s.io/kubernetes/pkg/kubemark
W0314 14:59:34.815] pkg/kubemark/hollow_proxy.go:128:4: unknown field EventClient in struct literal of type "k8s.io/kubernetes/cmd/kube-proxy/app".ProxyServer
W0314 14:59:34.816] pkg/kubemark/hollow_proxy.go:129:4: unknown field IptInterface in struct literal of type "k8s.io/kubernetes/cmd/kube-proxy/app".ProxyServer
W0314 14:59:34.816] !!! [0314 14:59:34] Call tree:
```

there is a hollow proxy that needs to be modified too

**Pull request merged**
