### PR TITLE
Move myself(chendave) to the list of emeritus

### PR DESCRIPTION
**Pull request by chendave**
since I cannot continue my work on the Kubernetes in the foreseen future.

/kind cleanup

/cc @kubernetes/sig-scheduling-misc

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by Huang-Wei — COMMENTED** [review]
/lgtm
/approve

@chendave Thanks for all the contributions! Should you decide to return in the future, you are always welcome.

**Review by sanposhiho — APPROVED** [review]
Thanks for your effort so far. Hope we'll get another chance working together somewhere.

**Comment by chendave** [comment]
@Huang-Wei @sanposhiho thanks.

I was just told I should continue the efforts in the open source community, I will sync with my new boss regarding with the bandwidth and scope.

Hold for more time before leaving.

/hold

**Comment by chendave** [comment]
/unhold

let's get this merged, looking forward to contributing this project in the future.

**Comment by alculquicondor** [comment]
/lgtm
/approve

Thanks @chendave!

**Pull request merged**
