### PR TITLE
change underscores to dashes to match the command line argument

### PR DESCRIPTION
**Pull request by davidwalter0**
@JanetKuo conflict resolved. ok ?

occurrences of underscores in documentation strings didn't match the command line argument.
change, for example, 

```
`--cors_allowed_origins=.*`.
`--cors-allowed-origins=.*`.
```

### CODE REVIEW

**Comment by JanetKuo** [comment]
Please rebase.

**Comment by JanetKuo** [comment]
LGTM. Thanks!

**Comment by JanetKuo** [comment]
@k8s-bot test this please

**Comment by JanetKuo** [comment]
@k8s-bot test this please

**Comment by davidopp** [comment]
@k8s-bot test this please

**Comment by JanetKuo** [comment]
@davidwalter0 Looks good. Thank you!

**Comment by dchen1107** [comment]
You have to rebase your pr first to get this merged. Thanks!

**Comment by jszczepkowski** [comment]
@k8s-bot test this please

**Pull request merged**
