### PR TITLE
kubelet: fix comment typo

### PR DESCRIPTION
**Pull request by champly**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by bart0sh** [comment]
Thank you for your PR. It seems to only contain trivial edits. Please
read [our trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits).

**Comment by champly** [comment]
> Thank you for your PR. It seems to only contain trivial edits. Please read [our trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits).

This pr is only in:
- cmd/kubelet/app/server.go
- pkg/kubelet/cm/cgroup_manager_test.go

used in two files, only related description in `cmd/kubelet/app/server.go` file:
``` go
experimentalQOSReserved, err := cm.ParseQOSReserved(s.QOSReserved)
if err != nil {
	return fmt.Errorf("--qos-reserved value failed to parse: %w", err)
}
```

**Comment by bart0sh** [comment]
@champly 
> ```go
> experimentalQOSReserved, err := cm.ParseQOSReserved(s.QOSReserved)
> if err != nil {
> 	return fmt.Errorf("--qos-reserved value failed to parse: %w", err)
> }
> ```

Why parsing of alpha future command line option is not wrapped into a feature gate check?

**Comment by champly** [comment]
> @champly
> 
> > ```go
> > experimentalQOSReserved, err := cm.ParseQOSReserved(s.QOSReserved)
> > if err != nil {
> > 	return fmt.Errorf("--qos-reserved value failed to parse: %w", err)
> > }
> > ```
> 
> Why parsing of alpha future command line option is not wrapped into a feature gate check?

Need to add feature gate check? like this:

```go
var experimentalQOSReserved *map[v1.ResourceName]int64
if utilfeature.DefaultFeatureGate.Enabled(features.QOSReserved) {
	experimentalQOSReserved, err = cm.ParseQOSReserved(s.QOSReserved)
	if err != nil {
		return fmt.Errorf("--qos-reserved value failed to parse: %w", err)
	}
}
``` 

I'm not sure if there will be any other problems with this modification.

**Comment by bart0sh** [comment]
> I'm not sure if there will be any other problems with this modification.

let's see what other reviewers and especially @sjenning say about it.

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
