### PR TITLE
E2E & Node E2E: Move configmap, docker_containers, downward_api, expansion and secrets test into common directory.

### PR DESCRIPTION
**Pull request by Random-Liu**
This is the 3rd part of #29494.

For #29081.
Based on #29092, #29806.

The first commit is squash of all dependent commits. Please only review the second commit.

The second PR added 17 lines.

@vishh @timstclair

### CODE REVIEW

**Comment by Random-Liu** [comment]
@k8s-bot test this issue #IGNORE.

**Comment by Random-Liu** [comment]
@vishh @timstclair PR ready for review! :)

**Comment by Random-Liu** [comment]
@k8s-bot test this issue https://github.com/kubernetes/kubernetes/issues/29633.

**Comment by timstclair** [comment]
LGTM

**Pull request merged**
