### PR TITLE
fix typo: writeable->writable

### PR DESCRIPTION
**Pull request by weipeng1213**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wgliang** [comment]
@weipeng1213 There are many similar mistakes if you are willing to change all.

**Comment by weipeng1213** [comment]
@k8s-ci-robot signed a CLA

**Comment by wgliang** [comment]
@weipeng1213  
And please add Release note(write NONE).

**Comment by weipeng1213** [comment]
@wgliang release note already add

**Comment by nikhita** [comment]
/assign @yujuhong 
for approval

**Pull request merged**
