### PR TITLE
add kms as to 1.26 rules for multiple components

### PR DESCRIPTION
**Pull request by dims**
In 576cca0a5e53cffeafc635321df407b89cebb281, we fixed one spot, looks like we need to do the same for others!

Please see https://github.com/kubernetes/kubernetes/pull/114335 for more context

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
looks much better (1.26 and master references match)

```
[davanum@c889f3bd53ed 19:32] ~/go/src/k8s.io/kubernetes/staging/publishing ⟩ rg -i -e "destination: " -e "repository: kms"
rules.yaml
2:- destination: code-generator
33:- destination: apimachinery
65:- destination: api
115:- destination: client-go
201:- destination: component-base
275:- destination: component-helpers
349:- destination: kms
361:- destination: apiserver
373:    - repository: kms
445:    - repository: kms
451:- destination: kube-aggregator
465:    - repository: kms
559:    - repository: kms
564:- destination: sample-apiserver
578:    - repository: kms
697:    - repository: kms
707:- destination: sample-controller
822:- destination: apiextensions-apiserver
838:    - repository: kms
940:    - repository: kms
947:- destination: metrics
1033:- destination: cli-runtime
1107:- destination: sample-cli-plugin
1192:- destination: kube-proxy
1278:- destination: kubelet
1364:- destination: kube-scheduler
1450:- destination: controller-manager
1464:    - repository: kms
1546:    - repository: kms
1552:- destination: cloud-provider
1570:    - repository: kms
1672:    - repository: kms
1678:- destination: kube-controller-manager
1698:    - repository: kms
1810:    - repository: kms
1816:- destination: cluster-bootstrap
1878:- destination: csi-translation-lib
1940:- destination: mount-utils
1972:- destination: legacy-cloud-providers
1994:    - repository: kms
2126:    - repository: kms
2132:- destination: cri-api
2164:- destination: kubectl
2298:- destination: pod-security-admission
2312:    - repository: kms
2394:    - repository: kms
2400:- destination: dynamic-resource-allocation
```

**Review by palnabarun — APPROVED** [review]
/lgtm

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Comment by dims** [comment]
@kubernetes/release-team-leads @kubernetes/release-managers Since we really need the bot to work, we need to merge this for 1.26, applying milestone.

/milestone v1.26

**Pull request merged**
