### PR TITLE
[Controller] Add locks to protect ServicePortCache

### PR DESCRIPTION
**Pull request by gaurav1086**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Add locks to the ServicePortCache in controller/endpointslice to avoid data races.
**Which issue(s) this PR fixes**:

Fixes #
N/A
**Special notes for your reviewer**:
N/A
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Review by cmluciano — COMMENTED** [review]
/ok-to-test

@gaurav1086 Can you link an issue or provide more context on how the locks are helpful for these caches?

**Comment by gaurav1086** [comment]
> /ok-to-test
> 
> @gaurav1086 Can you link an issue or provide more context on how the locks are helpful for these caches?

Thanks for the review.
Set is a public function so susceptible to be called w/o a lock()
Currently its being used without a lock here: pkg/controller/endpointslice/reconciler.go
Thoughts ?

**Comment by robscott** [comment]
Sorry I missed this earlier!
/assign
/remove-lifecycle stale
/retest

**Comment by thockin** [comment]
@robscott was this something we need?  I haven't looked into the concurrency here..

**Comment by robscott** [comment]
Thanks for catching this! I think the controller is limited so that only a single worker can be working on a Service at a time, but this feels like a nice backup if that somehow changes/fails.

/reopen

**Pull request closed without merging**
