### PR TITLE
Move conformance image

### LINKED ISSUE #103867: Move conformance source out of cluster/images/conformance
cluster/ directory is deprecated (https://github.com/kubernetes/kubernetes/blob/master/cluster/README.md), and its source code should be moved to separate repos.

/kind cleanup
/sig cloud-provider
/sig testing

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Moves the conformance image out of deprecated cluster directory

#### Which issue(s) this PR fixes:
Fixes #103867

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/cc @benhxy @spiffxp @dims

### CODE REVIEW

**Comment by dims** [comment]
+1 from me! for 1.23 we'll need to fix up references outside this repo when the time comes - https://cs.k8s.io/?q=cluster%2Fimages%2Fconformance&i=nope&files=&excludeFiles=&repos=kubernetes/test-infra

**Comment by spiffxp** [comment]
Does this work with https://github.com/kubernetes/kubernetes/blob/master/test/images/image-util.sh?

Or put another way, can it be built via https://github.com/kubernetes/kubernetes/blob/master/test/images/cloudbuild.yaml the same as everything else in test/images?

**Comment by spiffxp** [comment]
```
$ make all-container WHAT=conformance
./image-util.sh build conformance "docker"
./image-util.sh: line 104: conformance/VERSION: No such file or directory
make: *** [all-container] Error 1
```

**Comment by liggitt** [comment]
> Or put another way, can it be built via https://github.com/kubernetes/kubernetes/blob/master/test/images/cloudbuild.yaml the same as everything else in test/images?

since this intends to produce a unique build per commit at HEAD, I don't think it follows the same pattern as test images which only bump version occasionally

**Comment by liggitt** [comment]
> +1 from me! for 1.23 we'll need to fix up references outside this repo when the time comes - https://cs.k8s.io/?q=cluster%2Fimages%2Fconformance&i=nope&files=&excludeFiles=&repos=kubernetes/test-infra

opened https://github.com/kubernetes/test-infra/pull/23000 to do this conditionally based on what dirs exist in the branch being tested

**Comment by liggitt** [comment]
pull-kubernetes-conformance-image-test failure is expected until https://github.com/kubernetes/test-infra/pull/23000

**Comment by spiffxp** [comment]
>since this intends to produce a unique image per commit at HEAD, I don't think it follows the same pattern as test images which only bump version occasionally

Can we put this someplace other than test/images then? This will break `make` invocations without `WHAT=`

How about test/conformance/image?

**Comment by liggitt** [comment]
> Can we put this someplace other than test/images then? This will break `make` invocations without `WHAT=`
> 
> How about test/conformance/image?

works for me

**Comment by liggitt** [comment]
> How about test/conformance/image?

done

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Comment by liggitt** [comment]
> /skip pull-kubernetes-conformance-image-test

alternatively, we could merge https://github.com/kubernetes/test-infra/pull/23000 and make sure the test passes

**Comment by spiffxp** [comment]
>alternatively, we could merge kubernetes/test-infra#23000 and make sure the test passes

I missed that you had opened that, approved

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve
+1 to a dir other than test/images

**Comment by liggitt** [comment]
pull-kubernetes-conformance-image-test is happy, this should be good to go once 1.23 is open

**Pull request merged**
