### PR TITLE
process pvc watch deletion event miss in expand-controller

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

volume expand controller should also process exception case when watch deletion event missed as most controllers do.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gnufied** [comment]
Not sure if it is needed because `resizeMap` is emptied on each iteration of resize loop, so deleted volumes will naturally be removed from never be added back.

**Comment by hzxuzhonghu** [comment]
@gnufied make sense.  In volume controller, almost all the delete event does not handle with this scene.

**Comment by gnufied** [comment]
@hzxuzhonghu can you reopen this PR - I was apparently wrong about not handling tombstone final state known objects - https://github.com/kubernetes/kubernetes/pull/57275/files#r157344779

**Comment by hzxuzhonghu** [comment]
@gnufied ok

**Comment by hzxuzhonghu** [comment]
ping @gnufied for approval

**Comment by hzxuzhonghu** [comment]
@gnufied should be ` /approve no-issue`

**Comment by hzxuzhonghu** [comment]
Thanks.

**Pull request merged**
