### PR TITLE
Moving kubectl logs Long command into variable

### PR DESCRIPTION
**Pull request by lauchokyip**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
The long description of the `kubectl log` command is moved to the variable section to keep it consistent with other commands

**Which issue(s) this PR fixes**:

Reopen #96075

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by rikatz** [comment]
/lgtm

Will seek for the batch of approvals today on sig-cli

@liggitt maybe you can approve this :)

**Comment by liggitt** [comment]
to help load-balance, I'm redirecting sig-cli approvals to @seans3 / @soltysh 

/assign @soltysh @seans3

**Comment by rikatz** [comment]
/retest

Em qua., 20 de jan. de 2021 às 13:00, Kubernetes Prow Robot <
notifications@github.com> escreveu:

**Pull request merged**
