### PR TITLE
[1.29] bump runc to v1.1.11

### PR DESCRIPTION
**Pull request by harche**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Bumping up runc to 1.1.11 in 1.29. More info at https://github.com/kubernetes/kubernetes/pull/122552

#### Which issue(s) this PR fixes:

Fixes # NONE

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]

**Comment by liggitt** [comment]
I don't really have context to evaluate the risk of the change... are the bugs fixed critical data loss, security, or regressions? Does the new cgo file introduce new cgo or system library requirements to the kubelet?

**Comment by harche** [comment]
@liggitt On the nodes that use cgroup v2 the metric `container_memory_max_usage_bytes` is broken, 

```bash
$ kubectl get pod 
NAME    READY   STATUS    RESTARTS   AGE
nginx   1/1     Running   0          2s
```
```bash
$ curl -k -sL  https://192.168.0.11:10250/metrics/cadvisor | grep "^container_memory_max_usage_bytes" | grep nginx 
container_memory_max_usage_bytes{container="",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod94a2d4d5_0289_4041_90b6_529dfa90cc1f.slice",image="",name="",namespace="default",pod="nginx"} 0 1705518787752
container_memory_max_usage_bytes{container="nginx",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod94a2d4d5_0289_4041_90b6_529dfa90cc1f.slice/crio-ca8d8137892c320cf19d47bbb16f29e87d950b4ed38e6c1c70f2455328a749e9.scope",image="docker.io/library/nginx:latest",name="k8s_nginx_nginx_default_94a2d4d5-0289-4041-90b6-529dfa90cc1f_0",namespace="default",pod="nginx"} 0 1705518788194
```

but with [this fix](https://github.com/opencontainers/runc/pull/4131/files#diff-597c9eb164fc8d34c7fa865544c067ee504c4fd9bf745b55e9dc4810881d9035R161) in runc (part of 1.1.11) that metric starts reporting the data again, 

```bash
$ curl -k -sL  https://192.168.0.11:10250/metrics/cadvisor | grep "^container_memory_max_usage_bytes" | grep nginx 
container_memory_max_usage_bytes{container="",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podc5808a93_2241_4bd5_9354_7b8c6a1dca6d.slice",image="",name="",namespace="default",pod="nginx"} 1.4372864e+07 1705518914836
container_memory_max_usage_bytes{container="nginx",id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podc5808a93_2241_4bd5_9354_7b8c6a1dca6d.slice/crio-91851609227e3a18e4de1f8710b8d04d347868f8e580478066f3493c6da1dc7d.scope",image="docker.io/library/nginx:latest",name="k8s_nginx_nginx_default_c5808a93-2241-4bd5-9354-7b8c6a1dca6d_0",namespace="default",pod="nginx"} 262144 1705518904628
```

**Comment by liggitt** [comment]
is this a regression in runc that used to work in previous kubernetes releases?

**Comment by harche** [comment]
@liggitt when I switched my nodes to use cgroups v2, the metric `container_memory_max_usage_bytes` stopped working. Turns out you need to have [this fix](https://github.com/opencontainers/runc/pull/4131/files#diff-597c9eb164fc8d34c7fa865544c067ee504c4fd9bf745b55e9dc4810881d9035R161) in runc to make it work again. For cgroup v2, it is broken all the way till 1.26. 

The metric  `container_memory_max_usage_bytes` itself is defined in cadvisor, but the reason this metric works on master k8s branch is because of this runc bump https://github.com/kubernetes/kubernetes/pull/122552


I also opened PR with cadvisor to fix it on their side - https://github.com/google/cadvisor/pull/3455

**Comment by bobbypage** [comment]
Thanks @harche for looking into this. For `container_memory_max_usage_bytes` to work, it sounds like we not only need https://github.com/opencontainers/runc/pull/4131/commits but also need the underlying kernel to support `memory.peak` which appears to only be added in kernel 5.19. So on previous kernels, cAdvisor coudn't report this metric because it wasn't exposed.

**Comment by harche** [comment]
We are encouraging people to use cgroup v2, and when they switch their existing cluster to v2 this metric was found to be broken. The metric works with cgroup v1 host, but not with v2. This is where this patch is helpful. It prevents the disruption for people switching to cgroup v2 (which sig node is also actively encouraging to use. In last sig node meeting someone even brought up the topic of deprecating cgroup v1 support)    

/cc @SergeyKanzhelev @dchen1107 @mrunalp @derekwaynecarr

**Comment by szuecs** [comment]
@bobbypage @liggitt the problem is that workloads that are setting the memory usage like JVM HEAP close to the resource request/limit value will often count more usage than before and this will lead to oom.
I can not quantify how much of our ~2000 applications will crash, because we have 2 changes in one go:
- requirement change to runtimes to support cgroupv2 (complicated enough)
- memory usage calculation change (lottery style)

It would be great to have the calculation similar, because how can you know that business critical applications won't crash because of the change by an "observed limit".

**Review by mrunalp — APPROVED** [review]

**Comment by kolyshkin** [comment]
> /close runc is already bumped to 1.1.12.

Not in 1.29, no. But this doesn't matter now I guess.

**Pull request closed without merging**
