### PR TITLE
CRI: Only TearDownPod for ready sandbox

### LINKED ISSUE #34999: CRI: calling TearDownPod with a exited infra container causing errors
In the default, non-CRI integration, kubelet never calls `TearDownPod` with an exited infra container. 
In the new CRI integration, kubelet tries to call `TearDownPod` whenever it needs to start a new sandbox. Because `Pid` of an exited container is always 0 (from `docker inspect`), kubenet cannot get the network namespace for the container by reading `/proc/0/ns/net`. This causes `TearDownPod` to fail permanently (on every sync), and kubelet unable to start new sandbox and containers.

See an example below for such a failure:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gci-gce-cri-serial/58
(In the serial suite, docker may be restarted, so it is normal for infra containers to die along with it).
kubelet.log for jenkins-e2e-minion-group-7nto:
```
I1017 11:54:47.163823    1309 kuberuntime_manager.go:587] Stopping PodSandbox for "kubernetes-dashboard-v1.4.0-yvett_kube-system(33e26d63-9452-11e6-aed7-42010af00002)", will start new one
I1017 11:54:47.164632    1309 server.go:612] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kubernetes-dashboard-v1.4.0-yvett", UID:"33e26d63-9452-11e6-aed7-42010af00002", APIVersion:"v1", ResourceVersion:"271", FieldPath:""}): type: 'Normal' reason: 'SandboxChanged' Pod sandbox changed, it will be killed and re-created.
I1017 11:54:47.168184    1309 kubenet_linux.go:659] Removing kube-system/kubernetes-dashboard-v1.4.0-yvett from 'kubenet' with CNI 'bridge' plugin and runtime: &{ContainerID:97db96f7912e0b5660ee1ffe9ef295430b266d052ed5df7e20912f86d90dcd07 NetNS:/proc/0/ns/net IfName:eth0 Args:[]}
I1017 11:54:47.192231    1309 kubenet_linux.go:490] TearDownPod took 28.382774ms for kube-system/kubernetes-dashboard-v1.4.0-yvett
E1017 11:54:47.192258    1309 kuberuntime_manager.go:840] Failed to teardown network for pod kubernetes-dashboard-v1.4.0-yvett_kube-system(33e26d63-9452-11e6-aed7-42010af00002) using network plugins "kubenet": Error removing container from network: failed to Statfs "/proc/0/ns/net": no such file or directory
E1017 11:54:47.193123    1309 kuberuntime_manager.go:593] killPodWithSyncResult failed: failed to "TeardownNetwork" for "33e26d63-9452-11e6-aed7-42010af00002" with TeardownNetworkError: "Failed to teardown network for pod kubernetes-dashboard-v1.4.0-yvett_kube-system(33e26d63-9452-11e6-aed7-42010af00002) using network plugins \"kubenet\": Error removing container from network: failed to Statfs \"/proc/0/ns/net\": no such file or directory"
E1017 11:54:47.193159    1309 pod_workers.go:184] Error syncing pod 33e26d63-9452-11e6-aed7-42010af00002, skipping: failed to "TeardownNetwork" for "33e26d63-9452-11e6-aed7-42010af00002" with TeardownNetworkError: "Failed to teardown network for pod kubernetes-dashboard-v1.4.0-yvett_kube-system(33e26d63-9452-11e6-aed7-42010af00002) using network plugins \"kubenet\": Error removing container from network: failed to Statfs \"/proc/0/ns/net\": no such file or directory"
I1017 11:54:47.193745    1309 server.go:612] Event(api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kubernetes-dashboard-v1.4.0-yvett", UID:"33e26d63-9452-11e6-aed7-42010af00002", APIVersion:"v1", ResourceVersion:"271", FieldPath:""}): type: 'Warning' reason: 'FailedSync' Error syncing pod, skipping: failed to "TeardownNetwork" for "33e26d63-9452-11e6-aed7-42010af00002" with TeardownNetworkError: "Failed to teardown network for pod kubernetes-dashboard-v1.4.0-yvett_kube-system(33e26d63-9452-11e6-aed7-42010af00002) using network plugins \"kubenet\": Error removing container from network: failed to Statfs \"/proc/0/ns/net\": no such file or directory"
```

One solution is to check whether the pid is zero, and don't error out if that's the case. Since @freehan is working on refactoring kuberuntime/kubenet code, this problem may get fixed along the way. Filing this issue so that we can keep track of the potential issues. 

/cc @kubernetes/sig-node @freehan

### PR DESCRIPTION
**Pull request by feiskyer**
Only TearDownPod for ready sandbox, should fix #34999.

cc/ @yujuhong @freehan @kubernetes/sig-node

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35019)

### CODE REVIEW

**Comment by feiskyer** [comment]
@k8s-bot cri test this

**Comment by feiskyer** [comment]
@k8s-bot cri serial test this

**Comment by euank** [comment]
:+1:

**Comment by yujuhong** [comment]
@feiskyer @euank I think this is part of a bigger issue about pod sandbox resource reclaim. Can we discuss in #34999 first? Thanks!

**Comment by feiskyer** [comment]
I'm closing this PR because it could result in network resources leak in some cases, e.g. if sandbox exited abnormally, there is no any chance to reclaim IP/PortMappings any more. 

Going #34999 to find a better solution.

**Pull request closed without merging**
