### PR TITLE
updated kibana to 6.6.1

### PR DESCRIPTION
**Pull request by monotek**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
/kind flake

**What this PR does / why we need it**:
* updates kibana to 6.6.1

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by coffeepac — COMMENTED** [review]
Please rebase and attempt to build this image.  You should be able to.

**Comment by monotek** [comment]
6.6.1 is out anyway. I'll think I can do it tomorrow...

**Comment by coffeepac** [comment]
this is good to go, but gonna wait and do #71252 at the same time so the versions agree.

**Comment by coffeepac** [comment]
/lgtm
/hold
can remove the hold when the other PR goes.

**Pull request merged**
