### PR TITLE
test images: Prepend linux/ to peer-finder BASEIMAGEs

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind bug
/sig testing

/priority important-soon

**What this PR does / why we need it**:

The ``BASEIMAGE`` entries should be formated as: ``OS/ARCH=image``. The ``peer-finder`` image ``BASEIMAGE`` file does not respect that format.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by justaugustus — COMMENTED** [review]
@claudiubelu -- For consistency's sake, are the other test images also prepended?

What's the impact of this change?
Anything we need to communicate out or is it consolidated to tests?

**Comment by claudiubelu** [comment]
> 
> 
> @claudiubelu -- For consistency's sake, are the other test images also prepended?
> 
> What's the impact of this change?
> Anything we need to communicate out or is it consolidated to tests?

This is needed in order to have the ``peer-finder`` image builder postsubmit job working. I'm currently addressing the jobs that are failing, and this is one of them.

The ``image-util.sh`` script expects this format, it errors otherwise:

```
./image-util.sh build pets/peer-finder "docker"
The BASEIMAGE file for the pets/peer-finder image is not properly formatted. Expected entries to start with 'os/arch', found 'amd64' instead.
```

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

checked the rest at HEAD; the busybox image is currently windows-specific
```
$ for f in $(find . -name BASEIMAGE); do grep -q linux/amd64 $f || echo $f needs linux/ prepended; done
./pets/peer-finder/BASEIMAGE needs linux/ prepended
./busybox/BASEIMAGE needs linux/ prepended
```

**Comment by justaugustus** [comment]
Awesome, thanks!
/lgtm

**Comment by spiffxp** [comment]
Part of https://github.com/kubernetes/k8s.io/issues/1522, https://github.com/kubernetes/kubernetes/issues/96770

**Pull request merged**
