### PR TITLE
[FEATURE BRANCH] Fix protobuf tag for Subjects in PolicyRuleWithSubjects

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR fixes the field name in the protobuf tag for the `Subjects` field of `PolicyRuleWithSubjects`.  There was an oversight in earlier editing that left the protobuf field name singular when the field was changed to plural.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
[KEP] https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190228-priority-and-fairness.md
```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
/cc @yue9944882 
/cc @aaron-prindle 
/cc @yliaog 
@mars1024 

/sig api-machinery

**Comment by MikeSpreitzer** [comment]
@MikeSpreitzer

**Comment by MikeSpreitzer** [comment]
/retest
#81100 strikes yet again.

**Comment by MikeSpreitzer** [comment]
/retest
#81100 strikes yet again.  Should we rebase to pick up the fix?

**Comment by yue9944882** [comment]
oh finally

**Pull request merged**
