### PR TITLE
update gophercloud that fixed code format

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

mainly to include [#265](https://github.com/gophercloud/gophercloud/pull/265), which fixed the code format including below two files:

* vendor/github.com/gophercloud/gophercloud/openstack/blockstorage/v1/apiversions/urls.go
* vendor/github.com/gophercloud/gophercloud/openstack/compute/v2/images/results.go

### CODE REVIEW

**Comment by zetaab** [comment]
did you execute make verify? This PR should contain modifications to file staging/src/k8s.io/apiserver/Godeps/Godeps.json as well (because it has dependency to gophercloud). But I cannot see that.

**Review by zetaab — CHANGES_REQUESTED** [review]
did you execute make verify? This PR should contain modifications to file staging/src/k8s.io/apiserver/Godeps/Godeps.json as well (because it has dependency to gophercloud). PR should modify version number in that file, but I cannot see that.

You can update those running ./hack/update-staging-godeps.sh if I remember correctly

**Review by zetaab — APPROVED** [review]

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by cblecker** [comment]
```
W0424 17:54:04.728] 30 BUILD files not up-to-date.
I0424 17:54:04.828] 
I0424 17:54:04.828] Run ./hack/update-bazel.sh
I0424 17:54:04.828] FAILED   hack/make-rules/../../hack/verify-bazel.sh	5s
```

**Comment by dixudx** [comment]
@zetaab need your label lgtm

**Comment by cblecker** [comment]
/assign @anguslees 
This pertains to the openstack cloudprovider

**Comment by dixudx** [comment]
@k8s-bot verify test this

**Comment by dixudx** [comment]
@anguslees Please remove `do-not-merge` label. Thanks.

**Comment by anguslees** [comment]
@dixudx I don't think I am able to do that :/

@idvoretskyi Any ideas why the do-not-merge label was added, and what we can do to remove it?

**Comment by dims** [comment]
@dixudx Will you be able to update this PR please? Thanks!

**Comment by dixudx** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by dixudx** [comment]
@k8s-bot pull-kubernetes-verify test this

**Comment by dixudx** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Comment by dixudx** [comment]
@k8s-bot pull-kubernetes-unit test this

**Pull request merged**
