### PR TITLE
Promote EphemeralContainers to beta

### LINKED ISSUE #98808: Promote Ephemeral Containers to beta and enable by default
This issue tracks [Ephemeral Containers](https://features.k8s.io/277) graduation to beta.

Graduation criteria from [KEP 277](https://git.k8s.io/enhancements/keps/sig-node/277-ephemeral-containers):

- [x] Ephemeral Containers API has been in alpha for at least 2 releases.
- [x] Ephemeral Containers support namespace targeting.
- [ ] Metrics for Ephemeral Containers are added to existing contain creation
  metrics.
- [x] CLI using Ephemeral Containers for debugging checked into a Kubernetes
  project repository (e.g. in `kubectl` or a `kubectl` plugin).
- [x] A task on https://kubernetes.io/docs/tasks/ describes how to troubleshoot
  a running pod using Ephemeral Containers.
- [ ] Ephemeral Container creation is covered by e2e-node tests.

Implementation Checklist:

- [ ] Update API documentation
- [ ] Enable feature gate by default

/sig node

### PR DESCRIPTION
**Pull request by verb**
#### What type of PR is this?
/kind feature
/sig node
/priority important-soon

#### What this PR does / why we need it: 
This promotes [KEP-277](http://kep.k8s.io/277) to beta

#### Which issue(s) this PR fixes:
Fixes #98808

#### Special notes for your reviewer:

[KEP Graduation Criteria](https://git.k8s.io/enhancements/keps/sig-node/277-ephemeral-containers#alpha---beta-graduation):
- [x] Ephemeral Containers API has been in alpha for at least 2 releases.
  - https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#alpha
- [x] Ephemeral Containers support namespace targeting.
  - https://github.com/kubernetes/kubernetes/pull/84731
- [x] Metrics for Ephemeral Containers are added to existing contain creation metrics.
  - https://github.com/kubernetes/kubernetes/pull/99000
- [x] CLI using Ephemeral Containers for debugging checked into a Kubernetes project repository (e.g. in `kubectl` or a `kubectl` plugin).
  - https://github.com/kubernetes/kubernetes/pull/88004
- [x] A task on https://kubernetes.io/docs/tasks/ describes how to troubleshoot a running pod using Ephemeral Containers.
  - https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/
- [x]  Ephemeral Container creation is covered by e2e-node tests.
  - https://github.com/kubernetes/kubernetes/pull/103372
- [x] Update via `/ephemeralcontainers` validates entire PodSpec to protect against future bugs
  - https://github.com/kubernetes/kubernetes/pull/105293

PR TODO:
- [x] Add e2e test for volume mounts
- [x] Disallow subpath in ephemeral containers
- [x] Add validation of `ephemeralContainerStatuses`
- [x] Remove e2e test feature tags so that tests run unconditionally
- [x] Add test to ensure `EphemeralContainerCommon` field metadata remains in sync with `Container`
- [x] Explicitly document the behavior of container namespace targeting when runtime hasn't implemented support
- [x] Apply documentation style guide to API reference comments
- [x] Squash

#### Does this PR introduce a user-facing change?

```release-note
Ephemeral containers have reached beta maturity and are now available by default.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: http://kep.k8s.io/277
- [Usage]: https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/
```

### CODE REVIEW

**Comment by verb** [comment]
This PR must be rebased after #103372 merges. Draft until then.

/test all

**Comment by verb** [comment]
@pacoxu @MadhavJivrajani do either of you have time to review this one?

**Comment by verb** [comment]
@msau42 Thanks for the review! For the API fields we have (in decreasing order of robustness) validation unit tests, API e2e tests, kubectl tests, and node e2e tests. IIRC, we have some volumeMount coverage, but it probably doesn't address your concern. Could you help me understand better? Is the worry that subpath bind mounts will grow unbounded, or is it something else?

The kubectl tests cover attach, et al (again, iirc), but only creation is covered in the node e2e tests. Not on purpose, just because it didn't occur to me since the other pod subresources only differ in the feature gate check. There absolutely should be coverage in both places, though. I'll review the node & kubectl tests to make sure there's full coverage.

**Comment by verb** [comment]
@msau42 All we have in volumeMount coverage right now is validation and not e2e. I'll add more to this PR and ping you when it's ready. It sounds like subpath is a bigger problem, though, and we should either create a per-pod subpath limit (not specific to ephemeral containers) or disallow subpath in ephemeral containers. I'm inclined to disallow subpath in ephemeral containers before promoting to beta. We can always allow it later. What do you think?

**Comment by verb** [comment]
> * Do we need any validation on EphemeralContainerStatuses? https://github.com/kubernetes/kubernetes/blob/af2ed2569d56a9f223b82ecee82d9fc91448890a/pkg/apis/core/validation/validation.go#L4188-L4189

+1, added. Thanks!

> * Can you clarify what the behavior is when the runtime does not support the feature? https://github.com/kubernetes/kubernetes/blob/af2ed2569d56a9f223b82ecee82d9fc91448890a/pkg/apis/core/types.go#L3202-L3204

It depends on the runtime. Runtimes that don't support this feature will get an [unexpected NamespaceMode](https://github.com/kubernetes/kubernetes/blob/55e1d2f9a73a0c78fc0c266236c3e31261635b90/staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto#L232).  What happens next is implementation specific. For containerd the request succeeded but used isolated namespaces. (containerd supports the feature now, though.)

Perhaps we could add something to the runtime conformance tests requiring runtimes to either implement this feature or return an error.

> * It doesn't look controlled in this codebase, but the documentation for `securityContext` is showing up under [Disallowed](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#not-allowed) in the api reference

Thanks for pointing this out. Setting security context became allowed in 1.22. I didn't recognize this doc, and it appeared to be generated so I expected it to be updated automatically. I opened kubernetes/website#30100 to track down the problem.

**Comment by msau42** [comment]
> > * Can you clarify what the behavior is when the runtime does not support the feature? https://github.com/kubernetes/kubernetes/blob/af2ed2569d56a9f223b82ecee82d9fc91448890a/pkg/apis/core/types.go#L3202-L3204
> 
> It depends on the runtime. Runtimes that don't support this feature will get an [unexpected NamespaceMode](https://github.com/kubernetes/kubernetes/blob/55e1d2f9a73a0c78fc0c266236c3e31261635b90/staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto#L232). What happens next is implementation specific. For containerd the request succeeded but used isolated namespaces. (containerd supports the feature now, though.)

Thanks, it sounds like perhaps the behavior is a little undefined, ie it will either error or succeed but without the intended functionality. Can we document that more explicitly?

**Review by sftim — COMMENTED** [review]
Some nice-to-have tidying I'd be happy to see happen before / at beta:

edit:
> ```golang
> // An EphemeralContainer is a temporary container that may be added to an existing pod for
> // user-initiated activities such as debugging. Ephemeral containers have no resource or
> // scheduling guarantees, and they will not be restarted when they exit or when a pod is
> // removed or restarted. If an ephemeral container causes a pod to exceed its resource
> // allocation, the pod may be evicted.
> // Ephemeral containers may not be added by directly updating the pod spec. They must be added
> // via the pod's ephemeralcontainers subresource, and they will appear in the pod spec
> // once added.
> ```

to write “Pod” in title case.

Extra extra tidying: reword “the pod may be evicted” to the active voice and name the component that triggers eviction (ie, the kubelet).

**Comment by verb** [comment]
> Looks like the expanded e2e test is forbidding volumeDevices (I'll let msau weigh in on what should be done there), and there's an import alias failure
> 
> One question on the status validation from me, and a few nits, then the API bits lgtm.

:+1:  I think I've addressed all of these.

@msau42 I've added a commit to allow `volumeDevices` in ephemeral containers for now, because the API reference doesn't say their disallowed. I'm looking for guidance about whether they really should be allowed in ephemeral containers, though.

**Comment by msau42** [comment]
I think it's fine for `volumeDevices` to be allowed. It's similar in scope to `volumeMounts`. Thanks so much for adding more tests! This is looking good from storage.

**Pull request merged**
