### PR TITLE
klog format error

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

> /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by NickrenREN — APPROVED** [review]
/lgtm
/approve

thanks

**Comment by NickrenREN** [comment]
@qingsenLi Could you please send another PR here ? https://github.com/kubernetes/cloud-provider-openstack
Thanks

**Comment by qingsenLi** [comment]
@NickrenREN I had send the new PR：https://github.com/kubernetes/cloud-provider-openstack/pull/621

**Pull request merged**
