### PR TITLE
rm admissionregistrationv1beta1 from webhook server scheme

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

admissionregistrationv1beta1 no need add to scheme, we only need admissionv1beta1 to decode `AdmissionReview`

/cc @caesarxuchao  @sttts 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
/lgtm

PR title is misleading though. I thought you were deleting the API.

**Comment by hzxuzhonghu** [comment]
@sttts ptal

**Pull request closed without merging**
