### PR TITLE
add log_file option to kubelet flags

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I5e75902739e2f869244d1b8b229be2580aca8149

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
`klog` supports a log-file option, make sure kubelet command line help options show this new option

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubelet now supports `log-file` option to write logs directly to a specific file
```

### CODE REVIEW

**Comment by yujuhong** [comment]
@dims I think I missed the announcement on `klog`. Could you point me to docs explaining why we're doing this? Thank you.

Why is this needed for 1.13? :-)

**Comment by dims** [comment]
@yujuhong you missed a whole bunch :)

https://groups.google.com/d/msg/kubernetes-dev/7vnijOMhLS0/1oRiNtigBgAJ

**Pull request merged**
