### PR TITLE
Cloud provider should return an error

### PR DESCRIPTION
**Pull request by smarterclayton**
Not fatal - makes cloud provider useful in methods that
can return error.

### CODE REVIEW

**Comment by zmerlynn** [comment]
Over to @lavalamp.

**Comment by lavalamp** [comment]
Looks very low risk, but is it needed for 1.0?

**Comment by smarterclayton** [comment]
No, we are carrying these patches right now.

On Jul 1, 2015, at 7:01 PM, Daniel Smith <notifications@github.com> wrote:

Looks very low risk, but is it needed for 1.0?

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/pull/10635#issuecomment-117845864>
.

**Comment by lavalamp** [comment]
LGTM

**Comment by vishh** [comment]
@k8s-bot: ok to test

**Pull request merged**
