### PR TITLE
Automated cherry pick of #15807 upstream release 1.1

### PR DESCRIPTION
**Pull request by thockin**
Platform-specific setRLimit implementations

Fix release build for windows.

### CODE REVIEW

**Comment by thockin** [comment]
@bgrant0607

**Comment by thockin** [comment]
@krousey

**Comment by krousey** [comment]
any concerns about the build tag messing with the copyright notice munger? it works correctly?

**Comment by thockin** [comment]
We have plenty of similar examples

**Comment by bgrant0607** [comment]
Merging to fix build.

**Pull request merged**
