### PR TITLE
Use ARG instead of sed to set the base image for addon-manager.

### PR DESCRIPTION
**Pull request by vinayakankugoyal**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Uses ARG instead of sed to set the base image for addon-manager, which is much cleaner.
Related to work highlighted in #98908 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
Thanks! Will let Ben LGTM.
/approve

**Comment by BenTheElder** [comment]
/lgtm
/approve
thanks!

**Pull request merged**
