### PR TITLE
Fix golint failures of e2e/framework/rc_util.go

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fix golint failures of e2e/framework/rc_util.go

**Which issue(s) this PR fixes**:

Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by SataQiu** [comment]
@fejta Thanks for your feedback. All the tests passed. Looking forward to your LGTM again!

**Review by fejta — COMMENTED** [review]
/lgtm

**Pull request merged**
