### PR TITLE
docs: fix outdated enhancement doc link

### PR DESCRIPTION
**Pull request by zhuangqh**
Signed-off-by: zhuangqh <zhuangqhc@gmail.com>

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

fix outdated enhancement doc link

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by ehashman — APPROVED** [review]
/ok-to-test
/priority backlog
/triage accepted
/lgtm

**Comment by ehashman** [comment]
/sig api-machinery

comment/link update, PTAL for approval

**Review by mrunalp — APPROVED** [review]
/approve

**Comment by zhuangqh** [comment]
ping @lavalamp

**Comment by lavalamp** [comment]
You need to rerun some code generators, verify is failing.

**Comment by ehashman** [comment]
@zhuangqh can you please rebase?

**Comment by zhuangqh** [comment]
> @zhuangqh can you please rebase?

@ehashman done

**Review by ehashman — COMMENTED** [review]
/lgtm

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
