### PR TITLE
update go domain name

### PR DESCRIPTION
**Pull request by LJTian**
update go domain name
golang.org -> go.dev

What type of PR is this?
/kind documentation

What this PR does / why we need it:
I feel like this is forgotten content and needs to be revised.

### CODE REVIEW

**Review by kikisdeliveryservice — COMMENTED** [review]
Double checked and the old links all do indeed redirect to the links in author's updates.
/ok-to-test
/lgtm

**Comment by LJTian** [comment]
/cc @kikisdeliveryservice 
Approval label missing

**Comment by LJTian** [comment]
重新提交PR, 新的PR 为 #112966

**Pull request closed without merging**
