### PR TITLE
Updating go restful

### PR DESCRIPTION
**Pull request by nikhiljindal**
Updating go restful to include fix for https://github.com/emicklei/go-restful/issues/251

First commit generated using:

```
godep restore
go get -u github.com/emicklei/go-restful
godep update github.com/emicklei/go-restful
```

Second commit generated by running 

```
./hack/update-swagger-spec.sh
```

Third commit generated by running:

```
./hack/update-api-reference-docs.sh
```

cc @kubernetes/goog-csi

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@nikhiljindal tests are failing, could you take a look?

The changes seem good to me.

**Comment by nikhiljindal** [comment]
Removing test files fixed it.
Ran:
```
rm Godeps/_workspace/src/github.com/emicklei/go-restful/*_test.go
rm Godeps/_workspace/src/github.com/emicklei/go-restful/*/*_test.go
```

@caesarxuchao PTAL.

**Comment by nikhiljindal** [comment]
@k8s-bot unit test this please!

**Comment by caesarxuchao** [comment]
> Removing test files fixed it.

Won't those test files be added back once people run `godeps restore`?

**Comment by nikhiljindal** [comment]
I assume that will not happen since hack/verify-godeps passes :)

**Comment by caesarxuchao** [comment]
Per offline discussion, running `godeps restore` won't restore them. So LGTM.

**Pull request merged**
