### PR TITLE
Update kube-dns to 1.14.5

### PR DESCRIPTION
**Pull request by bowei**
```release-note
Update kube-dns to 1.14.5
```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm

**Review by dmmcquay — APPROVED** [review]

**Comment by caesarxuchao** [comment]
@wojtek-t is ooo. I'm approving this PR as a deputy 1.7 release manager.

**Comment by pires** [comment]
The image is there alright but there's no release/tag on kubernetes/dns. Where can we find what changed? Thanks.

**Comment by djsly** [comment]
same here trying to know what brings in the new release.

**Comment by djsly** [comment]
@pires : 

```
We have released version 1.14.5 of all kube-dns containers to gcr.io/google_containers/k8s-dns-*, which includes k8s-dns-dnsmasq-nanny:1.14.5, fixing the vulnerability.

The kube-dns version string has been updated to 1.14.5 in kubernetes/cluster/addons/dns and kubernetes/cmd/kubeadm/app/phases/addons/dns/versions.go.

We have released Kubernetes versions 1.5.8, 1.6.11, and 1.7.7 containing the updated version string. Kubernetes version 1.8.0 also includes the updated kube-dns version.

Who is affected?

All Kubernetes clusters running k8s-dns-dnsmasq-nanny:1.14.4 and earlier are affected.
```

**Comment by pires** [comment]
Still no details or I'm missing something.

**Comment by djsly** [comment]
Security Patch. 
http://coreos.com/blog/dns-vulnerability-patched-in-kubernetes-and-tectonic
https://groups.google.com/forum/#!topic/kubernetes-dev/QWIzhD3JhhE

**Pull request merged**
