### PR TITLE
Add docs for kubernetes.io/role labels

### PR DESCRIPTION
**Pull request by justinsb**
Also for kubeadm.alpha.kubernetes.io/role form

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35904)

### CODE REVIEW

**Comment by bgrant0607** [comment]
Is this document for K8s contributors or for users? Contributor docs belong in docs/devel and no human-authored user docs should be in this repo. 

The api-reference directory is intended as a staging area for generated docs only.

cc @thockin

**Comment by justinsb** [comment]
@bgrant0607 for contributors.  We need a place where we can document the labels & annotations we are using internally, and to ensure that there are no collisions.  The intention is that these can go through technical review by an API expert like you, before they ship, which hasn't been the case up until now.  What do you propose instead?

Two proposals:

* I can move to `docs/devel`
* We could instead put these as constants with comments into e.g. `pkg/api/labels.go`, `pkg/api/taints.go` and `pkg/api/annotations/annotations.go` ?  That has the advantage that then there is no repetition (and maybe we could even autogen a similar doc to what we have here).   I'm happy to move the existing work in this document and start doing that, if you consider that a better option.

**Comment by bgrant0607** [comment]
@justinsb I like the idea of putting constants into files. That has been proposed for other constances, also:  #14541. Maybe pkg/api/constants/. We could move the annotations to there, also.

Then refer to those files in the API conventions here:
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#label-selector-and-annotation-conventions

**Comment by bgrant0607** [comment]
cc @davidopp

**Comment by davidopp** [comment]
> @justinsb I like the idea of putting constants into files.

For labels we do have
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/unversioned/well_known_labels.go

**Comment by thockin** [comment]
I think unversioned is the right place, too.

On Mon, Oct 31, 2016 at 8:35 PM, David Oppenheimer <notifications@github.com

**Comment by justinsb** [comment]
Opened #35975 with the alternative approach to put these into the API.  If we like that I'll close this one!

**Pull request closed without merging**
