### PR TITLE
Don't reuse credentials on cluster create

### PR DESCRIPTION
**Pull request by j3ffml**
@justinsb, @thockin, @brendandburns

### CODE REVIEW

**Comment by jlowdermilk** [comment]
Closes #13060

**Comment by thockin** [comment]
LGTM, but what will this do to people who have more than one cluster of a particular provider (e.g. dev and e2e)?

**Comment by jlowdermilk** [comment]
Multiple clusters will get different credentials, even if they are the same provider. Arguably, that is the correct approach anyway. Note that this doesn't mean that the older cluster credentials get overwritten; if you have e.g. a 'dev' and 'e2e' gce cluster, you will have 2 kubeconfig entries for them, and can switch between them by using `kubectl config use-context`

**Comment by thockin** [comment]
lgtm

**Pull request merged**
