### PR TITLE
Revert "SkyDNS is the only NS for Pods with DNSPolicy=ClusterFirst"

### PR DESCRIPTION
**Pull request by fabioy**
Reverts kubernetes/kubernetes#15645

I think this is the culprit for issue #18056. I'll manually merge on LGTM.

### CODE REVIEW

**Comment by fabioy** [comment]
CC @ArtfulCoder, @thockin

**Comment by ArtfulCoder** [comment]
It might have uncovered a real test configuration issue.

**Comment by fabioy** [comment]
It's possible. But I'm unfamiliar with the test involved (pod seems to run some sort of script). Merge bot is stopped due to this test failing. Would you prefer we wait until test owners (in Poland?) have a chance to debug?

**Comment by wojtek-t** [comment]
Since we have blocked mergebot now, I think we can merge it asap.

**Comment by wojtek-t** [comment]
LGTM

@gmarek

**Comment by gmarek** [comment]
Merging to unblock the bot.

**Comment by wojtek-t** [comment]
@thockin @ArtfulCoder @gmarek

Just to give more clear context why we decided to revert it.

it broke kubemark-gce, which is currently a blocking build for mergebot
A bit more context.

in kubemark, there is no skydns (we want to add it at some point, but that's not done yet)
however, with this PR merge, this caused that no pods were started (all the pods were successfully created & scheduled, but not even a single pod was started)
note, that we are using "pause" images, which aren't the most demanding ones :)

So I think the question is the following:
if this change requires DNS to start any pod, it has be clearly stated (I'm not saying it's not reasonable - it makes sense to say that). 
However, if it wasn't the intention of this PR, then there was some bug in it.

**Pull request merged**
