### PR TITLE
Using NAME to replace ID in help string

### PR DESCRIPTION
**Pull request by feihujiang**
ref  #9511

### CODE REVIEW

**Comment by feihujiang** [comment]
@erictune Could you please review this PR?

**Comment by zmerlynn** [comment]
@feihujiang: You need to run `hack/run-gendocs.sh` on your PR at the very least.

**Comment by zmerlynn** [comment]
@k8s-bot: ok to test

**Comment by thockin** [comment]
LGTM

**Comment by thockin** [comment]
shippable says: /root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/docs/ is out of date. Please run hack/run-gendocs.sh

You need to install our hooks to catch this at presubmit.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/development.md#hooks

**Comment by feihujiang** [comment]
@thockin @zmerlynn @erictune  I have run hack/run-gendocs.sh. Could you please review this PR again?

**Comment by bgrant0607** [comment]
LGTM

**Comment by thockin** [comment]
LGTM

**Pull request merged**
