### PR TITLE
Use bash comments in kubectl examples

### LINKED ISSUE #12426: Comments in kubectl examples should use bash comments, not Go comments
For example:
```
 // Partially update a node using strategic merge patch
 kubectl patch node k8s-node-1 -p '{"spec":{"unschedulable":true}}'
```

It should be:
```
 # Partially update a node using strategic merge patch
 kubectl patch node k8s-node-1 -p '{"spec":{"unschedulable":true}}'
```

### PR DESCRIPTION
**Pull request by apeeyush**
Comments in kubectl examples should use bash comments, not Go comments.
So, replaces // by # for example strings.

Fixes #12426

### CODE REVIEW

**Comment by bprashanth** [comment]
LGTM pending shippable

**Comment by eparis** [comment]
LGTM

**Comment by apeeyush** [comment]
Hi! It looks like the builds were cancelled on shippable. Not sure why this might have happened!

**Comment by eparis** [comment]
sorry, you are going to have to rebase to fix shippable.

**Comment by bgrant0607** [comment]
Thanks for doing this.

**Comment by apeeyush** [comment]
Looks like shippable is fixed now!

**Pull request merged**
