### PR TITLE
Revert revert of #11379

### PR DESCRIPTION
**Pull request by mikedanese**
fixes array expanison bug in  #11379 and unrevert's it.

### CODE REVIEW

**Comment by zmerlynn** [comment]
Changed your title to mention #11379 :) (And mentioning it here so there's a crosslink.)

**Comment by zmerlynn** [comment]
LGTM

**Comment by mikedanese** [comment]
Terrible description. Thanks.

**Comment by sdminonne** [comment]
@mikedanese @zmerlynn many thanks.

**Pull request merged**
