### PR TITLE
Automated cherry pick of #65926: Fix RunAsGroup.

### PR DESCRIPTION
**Pull request by Random-Liu**
Cherry pick of #65926 on release-1.11.

#65926: Fix RunAsGroup.

### CODE REVIEW

**Comment by liggitt** [comment]
do we typically do cherry-picks for alpha features?

**Comment by feiskyer** [comment]
> do we typically do cherry-picks for alpha features?

I think it's ok because this is actually a regression bug fix.

**Comment by Random-Liu** [comment]
@foxish For approval.

**Pull request merged**
