### PR TITLE
extract common function in ingress and federation e2e to uil

### PR DESCRIPTION
**Pull request by mfanjie**
Separate refactoring existing e2e code part from #29773
1. extract common constants, structs and functions in federated-service.go to federation-util.go, move existing util functions from federated-service.go to federation-util.go
2. extract common constants, structs and functions in ingress.go to ingress-util.go, move existing util functions from ingress.go to ingress-util.go

@quinton-hoole

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30671)

### CODE REVIEW

**Comment by quinton-hoole** [comment]
ok to test

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671#-:-KPO5m692b_i97Hjhg8O:bipl7rs)*

**Comment by quinton-hoole** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671)*

**Comment by quinton-hoole** [comment]
Reviewed 2 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[test/e2e/federation-util.go, line 98 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671#-KPO7rYIZTlazn3M8pms:-KPO7rYJlxLvIaQtLkg_:b32x9v7) ([raw file](https://github.com/kubernetes/kubernetes/blob/70bbf3fa487584b1f441036d49b0b8dba0076b8d/test/e2e/federation-util.go#L98)):*
> ```Go
> }
> 
> func waitforclustersReadness(f *framework.Framework, clusterSize int) *federationapi.ClusterList {
> ```

waitForAllClustersReady.  Rename clusterSize to clusterCount.  Also add a comment explaining the last parameter.  It seems that you wait until the number of listed clusters == clusterCount, and that all of then are ready. 

---

*[test/e2e/federation-util.go, line 117 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671#-KPO9Em2JPtnSld0E7Js:-KPO9Em3qQeJT7bdyNhI:bynkwyv) ([raw file](https://github.com/kubernetes/kubernetes/blob/70bbf3fa487584b1f441036d49b0b8dba0076b8d/test/e2e/federation-util.go#L117)):*
> ```Go
> }
> 
> func createClientsetForCluster(c federationapi.Cluster, i int, userAgentName string) *release_1_3.Clientset {
> ```

Am I missing something, or is parameter i not used, except for an inaccurate error message?  If that's the case, does this function work as expected?

---

*[test/e2e/federation-util.go, line 135 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671#-KPOA8LJsR0f2pAeSbMq:-KPOA8LJsR0f2pAeSbMr:b-5b0msq) ([raw file](https://github.com/kubernetes/kubernetes/blob/70bbf3fa487584b1f441036d49b0b8dba0076b8d/test/e2e/federation-util.go#L135)):*
> ```Go
> }
> 
> func createNamespaceInClusters(clusters map[string]*cluster, f *framework.Framework) {
> ```

Comment: now that we have federated namespaces, this could potentially be replaced by the creation of one of those.  But lets leave it as is for now.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671)*

**Comment by quinton-hoole** [comment]
Thanks @mfanjie.  Just two substantive comments.  LGTM once those are addressed.

**Comment by mfanjie** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[test/e2e/federation-util.go, line 98 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671#-KPO7rYIZTlazn3M8pms:-KPQJl_Ki_-oKC9r8NaH:b2ni9bh) ([raw file](https://github.com/kubernetes/kubernetes/blob/70bbf3fa487584b1f441036d49b0b8dba0076b8d/test/e2e/federation-util.go#L98)):*
<details><summary><i>Previously, quinton-hoole (Quinton Hoole) wrote…</i></summary>
> waitForAllClustersReady.  Rename clusterSize to clusterCount.  Also add a comment explaining the last parameter.  It seems that you wait until the number of listed clusters == clusterCount, and that all of then are ready. 
</details>
ok.

---

*[test/e2e/federation-util.go, line 117 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671#-KPO9Em2JPtnSld0E7Js:-KPQ2G5_UUXhEKylKyEU:b-qkpfwm) ([raw file](https://github.com/kubernetes/kubernetes/blob/70bbf3fa487584b1f441036d49b0b8dba0076b8d/test/e2e/federation-util.go#L117)):*
<details><summary><i>Previously, quinton-hoole (Quinton Hoole) wrote…</i></summary>
> Am I missing something, or is parameter i not used, except for an inaccurate error message?  If that's the case, does this function work as expected?
</details>
This func is called in side a loop and i is the index of the loop, this parameter is passed in and used for dump the error msg `framework.ExpectNoError(err, "Error creating client config in cluster #%d (%q)", i, c.Name)`

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671)*

**Comment by mfanjie** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[test/e2e/federation-util.go, line 98 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671#-KPO7rYIZTlazn3M8pms:-KPQKL6B8uVIUsD0GHyy:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/70bbf3fa487584b1f441036d49b0b8dba0076b8d/test/e2e/federation-util.go#L98)):*
<details><summary><i>Previously, mfanjie (Jesse Meng) wrote…</i></summary>
> ok.
</details>
Done.

---

*[test/e2e/federation-util.go, line 117 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671#-KPO9Em2JPtnSld0E7Js:-KPQKMzk43hyEWzxoSgz:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/70bbf3fa487584b1f441036d49b0b8dba0076b8d/test/e2e/federation-util.go#L117)):*
<details><summary><i>Previously, mfanjie (Jesse Meng) wrote…</i></summary>
> This func is called in side a loop and i is the index of the loop, this parameter is passed in and used for dump the error msg `framework.ExpectNoError(err, "Error creating client config in cluster #%d (%q)", i, c.Name)`
</details>
Done.

---

*[test/e2e/federation-util.go, line 135 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671#-KPOA8LJsR0f2pAeSbMq:-KPQKNifZOlqrKWLloxf:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/70bbf3fa487584b1f441036d49b0b8dba0076b8d/test/e2e/federation-util.go#L135)):*
<details><summary><i>Previously, quinton-hoole (Quinton Hoole) wrote…</i></summary>
> Comment: now that we have federated namespaces, this could potentially be replaced by the creation of one of those.  But lets leave it as is for now.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671)*

**Comment by mfanjie** [comment]
comments address, but I see a panic on ingress e2e, still debugging.

**Comment by mfanjie** [comment]
@quinton-hoole comments addressed, please review again and please help to merge if it is ok for you so I can speed up on the federation ingress e2e PR.
I ran e2e on my GCE environment, everything looked fine except my backend service(3 for trial account) quota was reached, and ingress ip could not be obtained.
I did not see any issues related the code.

**Comment by quinton-hoole** [comment]
Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[test/e2e/federation-util.go, line 117 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671#-KPO9Em2JPtnSld0E7Js:-KPTFpirMHmASNXYu5n1:b-p2aq2p) ([raw file](https://github.com/kubernetes/kubernetes/blob/70bbf3fa487584b1f441036d49b0b8dba0076b8d/test/e2e/federation-util.go#L117)):*
<details><summary><i>Previously, mfanjie (Jesse Meng) wrote…</i></summary>
> Done.
</details>
I would prefer that we remove the i  parameter and it's use in the log message.  But you can do that in a followup PR if you prefer.

---

*[test/e2e/federation-util.go, line 99 \[r3\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671#-KPTHNN0V6nlX24avTlc:-KPTHNN0V6nlX24avTld:b81ybxf) ([raw file](https://github.com/kubernetes/kubernetes/blob/acfb863f160bb424bdc881435203a9932f3eec6b/test/e2e/federation-util.go#L99)):*
> ```Go
> 
> // waitForAllClustersReady wait for all clusters defined in e2e context to be created
> // return ClusterList until the listed cluster items equals clusterCount
> ```

I don't think that this is what it does?  It either returns the full list of clusterCount clusters, or it fails the test?  PollImmediate calls the provided function until it returns true.  So in retrospect, a better function name would be waitForAllClustersReadyOrFail?

This correction, and the above comment, can come in a followup PR if you prefer.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671)*

**Comment by quinton-hoole** [comment]
Thanks @mfanjie .  Two remaining comments, both of which can be addressed in a followup PR.  

LGTM.

**Comment by mfanjie** [comment]
yes, I also notice this and I want this big pr to be merged first and then address some minor issues. Thank you.



? 2016?8?18??23:38?Quinton Hoole <notifications@github.com<mailto:notifications@github.com>> ???


Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

________________________________

test/e2e/federation-util.go, line 117 [r1]<https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671#-KPO9Em2JPtnSld0E7Js:-KPTFpirMHmASNXYu5n1:b-p2aq2p> (raw file<https://github.com/kubernetes/kubernetes/blob/70bbf3fa487584b1f441036d49b0b8dba0076b8d/test/e2e/federation-util.go#L117>):

Previously, mfanjie (Jesse Meng) wrote...

Done.

I would prefer that we remove the i parameter and it's use in the log message. But you can do that in a followup PR if you prefer.

________________________________

test/e2e/federation-util.go, line 99 [r3]<https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671#-KPTHNN0V6nlX24avTlc:-KPTHNN0V6nlX24avTld:b81ybxf> (raw file<https://github.com/kubernetes/kubernetes/blob/acfb863f160bb424bdc881435203a9932f3eec6b/test/e2e/federation-util.go#L99>):

// waitForAllClustersReady wait for all clusters defined in e2e context to be created
// return ClusterList until the listed cluster items equals clusterCount

I don't think that this is what it does? It either returns the full list of clusterCount clusters, or it fails the test? PollImmediate calls the provided function until it returns true. So in retrospect, a better function name would be waitForAllClustersReadyOrFail?

This correction, and the above comment, can come in a followup PR if you prefer.

________________________________

Comments from Reviewable<https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671>

-

**Comment by quinton-hoole** [comment]
e2e test failures:

```
Error lines from build-log.txt
... skipping 220 lines ...
# k8s.io/kubernetes/test/e2e
test/e2e/federation-authn.go:43: not enough arguments in call to createServiceOrFail
test/e2e/federation-authn.go:60: not enough arguments in call to createService
test/e2e/federation-authn.go:73: not enough arguments in call to createService
```

It looks like you still have some compile errors?

**Comment by quinton-hoole** [comment]
@mfanjie It looks like this might have a conflict with https://github.com/kubernetes/kubernetes/pull/30409 ?

```
Error lines from build-log.txt
... skipping 220 lines ...
# k8s.io/kubernetes/test/e2e
test/e2e/federation-authn.go:43: not enough arguments in call to createServiceOrFail
test/e2e/federation-authn.go:60: not enough arguments in call to createService
test/e2e/federation-authn.go:73: not enough arguments in call to createService
```

**Comment by mfanjie** [comment]
@quinton-hoole yes, there is a conflict, all checks showed green yesterday until #30409 being merged.
The reason is createServiceOrFail and createService were extracted to federation-util.go and I changed the interface and it requires the service name now. And in #30409 there are called in old fashion in test/e2e/federation-authn.go.
Just rebased the code and updated accordingly.

**Comment by quinton-hoole** [comment]
Cool, thanks @mfanjie .  LGTM.

**Comment by mfanjie** [comment]
build failed but seems not related to my code
```
Checking out Revision 0a8ddd2fb9240ba288ef882414e16e9c31dee6ff (origin/pr/30468/merge)
 > /usr/bin/git config core.sparsecheckout # timeout=10
 > /usr/bin/git checkout -f 0a8ddd2fb9240ba288ef882414e16e9c31dee6ff # timeout=20
FATAL: Could not checkout 0a8ddd2fb9240ba288ef882414e16e9c31dee6ff
```

**Comment by quinton-hoole** [comment]
@mfanjie Yes, that just looks like a flake on the bot host.

@k8s-bot test this

**Comment by quinton-hoole** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30671)*

**Comment by quinton-hoole** [comment]
@k8s-bot test this issue #IGNORE

**Pull request merged**
