### PR TITLE
 Move kubectl get-context validate logic to Validate function

### PR DESCRIPTION
**Pull request by zhouya0**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR moves validation logic to `Validate` to make the code sync with other commands.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
/assign @soltysh

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by liggitt** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93109/pull-kubernetes-node-e2e/1283357453685100544 flake is #93210

**Review by soltysh — APPROVED** [review]
It doesn't follow our patterns of Complete-Validate-Run flow, but it's definitely better than what it is there.
/lgtm
/approve
/retest

**Comment by soltysh** [comment]
/hold
failure is real
@zhouya0 can you fix those?

**Review by soltysh — APPROVED** [review]
/lgtm
/priority backlog

**Pull request merged**
