### PR TITLE
Accurately report ts used to make decisions in node-controller.go

### PR DESCRIPTION
**Pull request by pmorie**
@vmarmol Not sure who to tag into this one.

The NodeController should accurately report the timestamp used to make decisions about whether grace periods have elapsed.

### CODE REVIEW

**Comment by pmorie** [comment]
@k8s-bot test again

**Comment by vmarmol** [comment]
I think @gmarek has the most state here?

**Comment by gmarek** [comment]
It seems that test gods are against us today. Failures look unrelated though.
LGTM.

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@k8s-bot  ok to test

**Comment by pmorie** [comment]
Light is green, trap is clean!

**Pull request merged**
