### PR TITLE
Allow node-controller to update node status

### LINKED ISSUE #39639: gce-serial: node controller unable to update the node status
The build has been red for a couple of days:
issue: #39406
dashboard: https://k8s-testgrid.appspot.com/google-gce#gce-serial

Many disruptive tests (e.g., cluster resize) are failing because the node controller is unable to update the node status. Here are some relevant log snippets from one such failure:

kube-controller-manager.log:
```
E0104 02:35:53.718936       5 nodecontroller.go:781] Error updating node bootstrap-e2e-minion-group-9qj2: User "system:serviceaccount:kube-system:node-controller" cannot update nodes at the cluster scope.: "<nil>" (put nodes bootstrap-e2e-minion-group-9qj2)
```

kube-apiserver.log:
```
I0104 07:24:48.026670       5 panics.go:75] PUT /api/v1/nodes/bootstrap-e2e-minion-group-9qj2/status: (398.63µs) 403 [[kube-controller-manager/v1.6.0 (linux/amd64) kubernetes/9eaf1aa/system:serviceaccount:kube-system:node-controller] [::1]:44058]
I0104 07:24:48.029180       5 panics.go:75] GET /api/v1/nodes/bootstrap-e2e-minion-group-9qj2: (1.887521ms) 200 [[kube-controller-manager/v1.6.0 (linux/amd64) kubernetes/9eaf1aa/system:serviceaccount:kube-system:node-controller] [::1]:44058]
I0104 07:24:48.050468       5 rbac.go:49] RBAC DENY: user "system:serviceaccount:kube-system:node-controller" groups [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] cannot "update" on "nodes./status"
```

Seems to be related to the RBAC work. /cc @deads2k @dchen1107 (build-cop)

### PR DESCRIPTION
**Pull request by liggitt**
ref: #39639 

* adds required permissions to node-controller
 * fixes typo in role name for pod-garbage-collector role
* adds event watching permissions to persistent volume controller
* adds event permissions to node proxier

### CODE REVIEW

**Comment by liggitt** [comment]
cc @yujuhong @kubernetes/sig-auth-misc

**Comment by dchen1107** [comment]
LGTM

**Comment by yujuhong** [comment]
See https://github.com/kubernetes/kubernetes/issues/39639#issuecomment-271440198. There might be more to fix.

**Comment by liggitt** [comment]
updated with additional permissions for the node-controller, will look at the PV and garbage collection denials separately

**Comment by dchen1107** [comment]
@yujuhong Thanks for the comment. I am ok with a new PR to address the rest of denial issues.

**Comment by dchen1107** [comment]
I changed the pr description so that the pr merge won't close the issue. LGTM again.

**Comment by liggitt** [comment]
Open API flake
@k8s-bot unit test this

**Comment by liggitt** [comment]
flake on #39604

**Comment by liggitt** [comment]
@k8s-bot unit test this

**Pull request merged**
