### PR TITLE
Move workload registries to apps package

### PR DESCRIPTION
**Pull request by liggitt**
xref #43214
Starts the process of moving internal types to the apps packages for apps types

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/sig-apps-pr-reviews

**Comment by mattfarina** [comment]
@liggitt It appears one of the files you moved (without modifying) is failing a lint check. That's why _pull-kubernetes-verify_ is failing.

**Review by soltysh — APPROVED** [review]
/lgtm

Make sure to update the missing bits Matt metioned

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
