### PR TITLE
replace the HEAD links with v1.0 ones in definitions.html

### LINKED ISSUE #12690: Update the versionize-docs.sh script to process the types_swagger_doc.go file
The [versionize-docs.sh script](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fkubernetes%2Fkubernetes%2Fblob%2Fmaster%2Fbuild%2Fversionize-docs.sh&sa=D&sntz=1&usg=AFQjCNFvneV33AbecKPiXdysx8otECI04g) needs to be updated so that it processes this new doc before it gets moved/published to gh-pages so that urls that point to HEAD get redirected so that they instead to point to the corresponding version of the docs on k8s.io (gh-pages), for example, links to ```http://releases.k8s.io/HEAD/docs/```*specificdochere.md*

#10933

### PR DESCRIPTION
**Pull request by caesarxuchao**
Let the release_docs tool replace the HEAD links with v1.0 ones in definitions.html

fix #12690 

@RichieEscarez

### CODE REVIEW

**Comment by RichieEscarez** [comment]
@caesarxuchao this looks good from what I can tell but im not fluent in go. Can you please help assign this to someone more capable?

**Comment by caesarxuchao** [comment]
Thank you @RichieEscarez. Let's wait for result of the discussion in #12690. I will update the code here if we decide to versionize the go files.

**Comment by caesarxuchao** [comment]
@nikhiljindal, could you help review this one? Richie says he's not fluent in go. This PR uses regexp to versionize the links in definitions.html.

**Comment by nikhiljindal** [comment]
LGTM, thansk!

**Pull request merged**
