### PR TITLE
Redo on building platforms in parallel

### PR DESCRIPTION
**Pull request by zmerlynn**
Only build in parallel on >8G machines (as an arbitrary line in the sand).

Also parallelizes tarball builds further, as a freebie.

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @brendanburns @roberthbailey 

Care to test on OS X?

**Comment by zmerlynn** [comment]
Re-fixes #6346

**Comment by zmerlynn** [comment]
Wait, what!? Seriously, needs a rebase since *this morning!?*

**Comment by zmerlynn** [comment]
n/m, I put up a branch that didn't have the revert-revert in first. Should be mergable now.

**Comment by roberthbailey** [comment]
Just tested on OS X and this works the same as before (serial builds since my virtual box VM has less than 8G of memory).

**Comment by zmerlynn** [comment]
@brendandburns: You were complaining about not having enough to review, so I fixed #6389 and cleaned up the Docker container build spew, too, while I was working on doc'ing Salt.

**Comment by brendandburns** [comment]
LGTM.

**Pull request merged**
