### PR TITLE
k8s.io/metrics: restrict k8s.io/metrics imports

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by deads2k** [comment]
I wonder why metrics depend on the API.  Doesn't that seem odd?

/lgtm

**Comment by sttts** [comment]
@deads2k it includes a client which depends on the rest client which depends on k8s.io/api.

**Comment by sttts** [comment]
Or maybe it doesn't (the rest client itself shouldn't). Will double check.

**Comment by sttts** [comment]
It depends on core/v1:
```
metrics has a forbidden dependency:

  k8s.io/metrics/pkg/apis/custom_metrics/v1alpha1 imports k8s.io/api/core/v1
  k8s.io/metrics/pkg/apis/metrics/v1alpha1 imports k8s.io/api/core/v1
```

**Comment by deads2k** [comment]
For an object reference.  That should be copied and scoped down to what is needed to avoid this dep.  I think the dependency is dangerous.  We don't want metrics tied to our API types.

**Pull request merged**
