### PR TITLE
fix kube-up without DOCKER_OPTS

### PR DESCRIPTION
**Pull request by jetsanix**

### CODE REVIEW

**Comment by roberthbailey** [comment]
@k8s-bot test this

**Comment by roberthbailey** [comment]
@k8s-bot ok to test

**Comment by roberthbailey** [comment]
@k8s-bot ok to test

**Comment by eparis** [comment]
#k8s-bot test this issue: #IGNORE

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

**Pull request merged**
