### PR TITLE
apiserver: set APF featuregate to stable

### PR DESCRIPTION
**Pull request by tkashem**
#### What type of PR is this?

/kind feature

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
```release-note
- Priority and Fairness feature is stable in 1.29, the feature gate will be removed in 1.31
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1040-priority-and-fairness
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm

Thanks!

**Comment by tkashem** [comment]
I see a data race, opened: https://github.com/kubernetes/kubernetes/issues/121643

/test pull-kubernetes-unit

**Comment by tkashem** [comment]
I also see a flake, does not seem related to this PR:
```
{Failed;  === RUN   TestStoreDeleteCollectionWithContextCancellation

Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:37421: connect: connection refused"
```

**Comment by liggitt** [comment]
unit flake is https://github.com/kubernetes/kubernetes/issues/121627

**Pull request merged**
