### PR TITLE
Added e2e test for petset to work across node restart

### PR DESCRIPTION
**Pull request by foxish**
**What this PR does / why we need it**:
This PR adds an e2e test for petsets which tests that the petset is functioning as expected after the non-master nodes are restarted.

**Release note**:

``` release-note
NONE
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34045)

This will verify our fix for: https://github.com/kubernetes/kubernetes/issues/31762

cc @kubernetes/sig-apps

### CODE REVIEW

**Comment by smarterclayton** [comment]
Test looks good - is there a job that will run slow tests explicitly today or does it have to be manual?

**Comment by foxish** [comment]
@smarterclayton All the petset jobs are run by the jenkins job: https://k8s-testgrid.appspot.com/google-gce#gce-petset

**Comment by foxish** [comment]
@k8s-bot gci gke e2e test this

**Comment by erictune** [comment]
Are `[Disruptive]` jobs submit blocking?

**Comment by chrislovecnm** [comment]
@erictune I filed and issue - GCI GKE tests are killing velocity of PRs :(

**Comment by foxish** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/pull/34045 which now contains tests as well.

**Pull request closed without merging**
