### PR TITLE
remove deprecated kubelet command-line flags

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Cleaning up IPTables Chain Ownership Post-GA tasks

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/enhancements/issues/3178

#### Does this PR introduce a user-facing change?

```release-note
Kubelet flags `--iptables-masquerade-bit` and `--iptables-drop-bit` were deprecated in v1.28 and have now been removed entirely. 
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/3178
```

### CODE REVIEW

**Comment by carlory** [comment]
/cc @sjenning

can you take a look?

**Comment by danwinship** [comment]
/assign @thockin 
(too late for 1.30 now but let's get this into 1.31)

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
