### PR TITLE
Remove invalid TODOs in kubeadm constants.

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
These TODOs are invalid now.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
ref https://github.com/kubernetes/kubeadm/issues/571#issuecomment-347408384

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
/test pull-kubernetes-verify
#60599

**Comment by xiangpengzhao** [comment]
/assign @jamiehannaford 
for approval, thanks!

**Review by timothysc — APPROVED** [review]
/approve

**Pull request merged**
