### PR TITLE
Allow show hidden metrics in kube-controller-manager

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Add a flag `--show-hidden-metrics-for-version` to kube-controller-manager for show hidden metrics.

**Which issue(s) this PR fixes**:
Part of #85270

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
New flag `--show-hidden-metrics-for-version` in kube-controller-manager can be used to show all hidden metrics that deprecated in the previous minor release.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
- [KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20190404-kubernetes-control-plane-metrics-stability.md
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
`pull-kubernetes-node-e2e-containerd` is failling. le't retry after https://github.com/kubernetes/kubernetes/issues/85040.

**Comment by RainbowMango** [comment]
/hold
We need to solve [the issue](https://github.com/kubernetes/kubernetes/issues/85411) first.

**Comment by RainbowMango** [comment]
/assign @lavalamp 
Assign to experts who have the context.

**Comment by RainbowMango** [comment]
Kindly ping @logicalhan @deads2k @lavalamp

**Comment by lavalamp** [comment]
/approve
/lgtm

Sorry for delay, I was OOO

**Pull request merged**
