### PR TITLE
Update github.com/pkg/errors to go native errors pkg

### PR DESCRIPTION
**Pull request by rajaSahil**
Signed-off-by: Sahil Raja <sahilraja242@gmail.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR removes usage of github.com/pkg/errors and update it to go native errors pkg.
#### Which issue(s) this PR fixes:

Part of #103043

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by ehashman — COMMENTED** [review]
Please ensure you've signed the CLA as above.

/ok-to-test
/backlog
/triage accepted
/lgtm

**Comment by ehashman** [comment]
/lgtm cancel

can you also please remove the reference in `pkg/kubelet/kubeletconfig/configfiles/configfiles_test.go`?

**Comment by rajaSahil** [comment]
@ehashman Done.

**Comment by ehashman** [comment]
@rajaSahil your CLA is still not signed, make sure you follow the instructions in https://github.com/kubernetes/kubernetes/pull/103059#issuecomment-865220063

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
