### PR TITLE
Move test-webserver from contrib/for-demos to kubernetes/test/images

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:
This PR is for
- Moving the https://github.com/kubernetes/contrib/tree/master/for-demos/test-webserver to kubernetes/test/images - Refer https://github.com/kubernetes/contrib/pull/2544 for more information
- Multi architecture support for test-webserver image

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by luxas** [comment]
/ok-to-test
/lgtm
/release-note-none

Thanks @mkumatag!

**Review by luxas — APPROVED** [review]

**Comment by luxas** [comment]
cc @kubernetes/sig-testing-pr-reviews FYI

**Comment by luxas** [comment]
@mkumatag Please update golint, the boilerplate and bazel for the tests to pass

**Comment by mkumatag** [comment]
This https://github.com/kubernetes/kubernetes/pull/48299 is creating problem everywhere! can we disable bypass pull-kubernetes-cross job here?

**Comment by luxas** [comment]
> This #48299 is creating problem everywhere! can we bypass pull-kubernetes-cross job here?

@mkumatag You don't have to worry about that. It's not blocking, so doesn't affect this PR at all

**Comment by spiffxp** [comment]
/lgtm

I can't approve /hack changes, ping @ixdy

**Comment by spiffxp** [comment]
/assign @ixdy 

(sorry for the comment spam, slowly waking up from vacation)

**Comment by luxas** [comment]
ping @ixdy

**Comment by ixdy** [comment]
is there a corresponding PR in contrib to delete this definition there?

**Comment by ixdy** [comment]
/retest

though I think crossbuild is still broken

**Comment by mkumatag** [comment]
> is there a corresponding PR in contrib to delete this definition there?
Not yet, will open a PR to remove from contrib

**Comment by mkumatag** [comment]
> is there a corresponding PR in contrib to delete this definition there?

https://github.com/kubernetes/contrib/pull/2680 created to remove content from contrib project. Can you please Approve?

**Comment by luxas** [comment]
Adding the label manually based on @ixdy's LGTM

**Comment by mkumatag** [comment]
@ixdy can someone help me pushing this image,? `make all-push WHAT=test-webserver`

**Comment by ixdy** [comment]
this has been pushed.

**Pull request merged**
