### PR TITLE
CHANGELOG: fix punctuation errors in 1.20

### PR DESCRIPTION
**Pull request by wangyx1992**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR fixes some punctuation errors in CHANGELOG.

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Review by soniasingla — APPROVED** [review]
/lgtm

Thanks for catching up!

**Comment by wangyx1992** [comment]
Hi, @hasheddan @wilsonehusin. This PR fixes some punctuation errors in 1.20, waiting for your review and approval with pleasure.

**Pull request closed without merging**
