### PR TITLE
Add SET_NOMOCK_FLAG handling.

### PR DESCRIPTION
**Pull request by david-mcmahon**
Pass thru KUBE_GCS_RELEASE_BUCKET (for federation yamls that change it).

### CODE REVIEW

**Comment by david-mcmahon** [comment]
@k8s-bot retest e2e issue:#UNKNOWN

**Comment by david-mcmahon** [comment]
@ixdy ping. LGTY?  Just waiting for this odd smoke failure to resolve.

**Comment by spxtr** [comment]
@k8s-bot e2e test this issue: #IGNORE

**Comment by ixdy** [comment]
LGTM

**Pull request merged**
