### PR TITLE
kubeadm: search for kubeconfig file in standart locations for init

### PR DESCRIPTION
**Pull request by neolit123**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Use cmdutil.FindExistingKubeConfig() in initData.KubeConfigPath()
This ensures that all the phases search for a kubeconfig file
in the standard locations and env variables, if the user did not
provide a value different from the default:
    kubeadmconstants.GetAdminKubeConfigPath()

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
NONE

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/assign @fabriziopandini 
/priority important-soon
@kubernetes/sig-cluster-lifecycle-pr-reviews

### CODE REVIEW

**Review by fabriziopandini — CHANGES_REQUESTED** [review]
@neolit123 thanks for this PR!

if I got this right, what will happen is that:
1. if the user sets data.Kubeconfig  != default location, that file will be used
2. if data.Kubeconfig == default location the kubeconfig file will be searched first in standard locations and only as a last chance in default location

2 can lead to problems, so IMO we should search only if the kubeconfig file is missing under data.Kubeconfig. Another option is to change the priority in search (I don't know internals but I guess it is supported).

**Comment by neolit123** [comment]
@fabriziopandini 
> 2 can lead to problems, so IMO we should search only if the kubeconfig file is missing under data.Kubeconfig. Another option is to change the priority in search (I don't know internals but I guess it is supported).

what do you have in mind?
is it a case where e.g. the ENV variable points to a file that is not the kubeconfig we are looking for?

this is based on the client-go default kubeconfig loading rules:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/util/cmdutil.go#L64-L75

this function is used in a few kubeadm sub-commands for a couple of releases:
https://github.com/kubernetes/kubernetes/search?q=FindExistingKubeConfig&unscoped_q=FindExistingKubeConfig

but we can switch to doing the search only if the file is missing in the default locations, i guess.

/assign @luxas @timothysc 
for comments too please.

**Comment by fabriziopandini** [comment]
@neolit123 kubeadm assumes to use admin.conf, that is a kubeconfig file pointing to the cluster you are creating and with an identity with "cluster-admin" roles.

however, if you already have another kubeconfig file in one of the default search locations e.g minikube generated kubeconfig file, this change will pick this kubeconfig file instead of admin.conf, and as a consequence you won't be able to create your cluster (but probably you will destroy minikube)

This is why IMO kubeadm should always pick admin.conf first, and only use fallback it admin.conf doesn't exists

**Comment by neolit123** [comment]
@fabriziopandini 
ok, later today i will update the precedence to look for the default config file first.

**Comment by neolit123** [comment]
/close
closing this one as per the discussion on slack with @fabriziopandini and @luxas

**Pull request closed without merging**
