### PR TITLE
kube-addon-update.sh: Replace the python code with shell.

### PR DESCRIPTION
**Pull request by yifan-gu**
As coreos doesn't have python, in order to run the script we need to
remove the python code here.

cc @dchen1107 @andyzheng0831

### CODE REVIEW

**Comment by yifan-gu** [comment]
I feel use shell to read the yaml is ugly.. Would like to hear other suggestion :)
Constrain here is that coreos distros have no python, no perl, and to launch a container to read that yaml seems to be an overkill?

**Comment by yifan-gu** [comment]
Any feedback? e2e seems happy.

**Comment by roberthbailey** [comment]
Sorry for the delay. @zmerlynn kindly agreed to take a look at this for me.

**Comment by zmerlynn** [comment]
@yifan-gu: Before I continue with this, can we possible consider something like #10326 if we're going to continue with the bash travesty here? I think if this is 1.2, we have time to figure out *something*. If you're feeling really aggressive, there's also #9470.

**Comment by zmerlynn** [comment]
@jonboulle: I'm not trying to pocket veto this, but parsing yaml in bash goes from "almost readable" to "within a hair's breath of not". The bash here is already on life support, and anytime we have an issue in there (which luckily hasn't happened for a bit, but ...), it's been kind of a hassle. I could similarly ask Core to reconsider their stance on Python, given the python:2.7-slim image really isn't big. :)

**Comment by yifan-gu** [comment]
@zmerlynn I tried a lot python image, they don't have yaml module

**Comment by yifan-gu** [comment]
Anyway, created a PR for building the image and run python in the container if python is not found on host.

**Comment by zmerlynn** [comment]
Obviated by #18488, and eventually by a larger rewrite?

**Pull request closed without merging**
