### PR TITLE
Add pod status reason when there are remaining pods.

### PR DESCRIPTION
**Pull request by aveshagarwal**
@yujuhong

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@kubernetes/rh-cluster-infra

**Comment by yujuhong** [comment]
@aveshagarwal, how about printing the actual "status" along with the reason? :-)

**Comment by yujuhong** [comment]
Could probably reuse this [utility function](https://github.com/kubernetes/kubernetes/blob/751f45b641fcf6c628cca01d8d6f50500ad16f26/test/e2e/framework/util.go#L424)

**Comment by aveshagarwal** [comment]
@yujuhong sounds good. More the better. I will update this PR soon.

**Comment by aveshagarwal** [comment]
@yujuhong PTAL.

**Comment by yujuhong** [comment]
LGTM. Thanks!

**Pull request merged**
