### PR TITLE
simplify flannel configuration on rackspace

### PR DESCRIPTION
**Pull request by doublerr**
cc @satnam6502 

Trying this PR with my work email which is on the Google CLA.

This patch lets us use a simpler flannel configuration.

### CODE REVIEW

**Comment by doublerr** [comment]
My apologies, I was signing my commits with my personal email address. I've changed it for my k8s repo moving forward. Can you manually verify me?

**Comment by satnam6502** [comment]
I think I need the green CIA logo?

**Comment by satnam6502** [comment]
Although I am happy to review this PR I lack context about Flannel so I might pull in others like @vishh for help.

**Comment by doublerr** [comment]
@quinton-hoole verified my CLA on my last PR https://github.com/GoogleCloudPlatform/kubernetes/pull/9303,

Re: flannel, we were configuring it previously but in a much more complicated fashion. This works on Rackspace and doesn't touch any other providers.

**Comment by quinton-hoole** [comment]
Thanks Ryan.  To repeat what I said in #9303 : 

"I manually verified your CLA. To save hassle and make this automatic in future, please remind Rackspace to follow the instructions that they should have received with their CLA (setting up an appropriate Google Group with members etc)."

You can add your Rackspace email address to your github account, and/or add your non-rackspace email address to the above Google Group.

Let me know if you need and help doing that.

**Comment by quinton-hoole** [comment]
ok to test

**Comment by doublerr** [comment]
@quinton-hoole I looked into it and the problem is that I was using my personal email address for kubernetes commits instead of my work email address (which is in the CLA for Rackspace). I've updated it now, so this should be resolved for future patches.

Sorry for the troubles.

**Comment by quinton-hoole** [comment]
Awesome.  Thanks @doublerr

**Comment by doublerr** [comment]
FYI, I updated the commit with the new email address and CLAs pass now.

**Pull request merged**
