### PR TITLE
Fix typo `a` to `an` in the whole project

### PR DESCRIPTION
**Pull request by astraw99**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Fix typo `a` to `an` in the whole project, to better the documents.

#### Special notes for your reviewer:
The `v1` alias is automatically added by IDE(Goland), to better differentiate from other v1 packages.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by bowei** [comment]
I'm not sure this kind of commit is worth it -- the change cuts across many different components, complicates `git blame` and version control annotation without must actual positive impact. My inclination is that please bundle this with a bug fix in a specific component rather than scanning whole codebases for a minor grammatical fix.

**Comment by ehashman** [comment]
/close

Thank you for your PR. It seems to only contain trivial edits. Please read our [trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits). We encourage you to take a look at confirmed issues and bugs or issues marked `help-wanted`.

**Comment by astraw99** [comment]
@bowei @ehashman Got it. Thanks :)

**Pull request closed without merging**
