### PR TITLE
Fix typo in v1.15 CHANGELOG

### PR DESCRIPTION
**Pull request by my-git9**
Signed-off-by: xin.li <xin.li@daocloud.io>

Modify 'kuberntes' to 'kubernetes'

/kind cleanup

Does this PR introduce a user-facing change?
```
NONE
```

### CODE REVIEW

**Comment by Lp-Francois** [comment]
LGTM

**Comment by wilsonehusin** [comment]
Hi @my-git9, thanks for raising the PR. For future reference, `CHANGELOG` changes to pre-releases (`.alpha`, `.beta`, `.rc`) aren't encouraged to be updated, unless the full release has the same typo. In this example, the full release has the proper spelling:

https://github.com/kubernetes/kubernetes/blob/e7a2ce75e5df96ba6ea51d904bf2735397b3e203/CHANGELOG/CHANGELOG-1.15.md?plain=1#L1272

As such, changes like this do not pass the [_trivial edits_ policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits)

However, there are typically exceptions for merging amendments when they are done in batch. In this case, I'm willing to advocate for this change if you combine the changes into #109736 (and feel free to assign me after that).

Thanks!

/close

**Pull request closed without merging**
