### PR TITLE
Move external facing kubelet apis to staging

### PR DESCRIPTION
**Pull request by dims**
**What type of PR is this?**
/kind api-change
/area code-organization

**What this PR does / why we need it**:
`deviceplugin` and `pluginregistration` are external facing APIs. currently we are forcing folks to import them from `k8s.io/kubernetes` which is not optimal. We should instead make them available from the `k8s.io/kubelet` repo to make it easier for them.

**Which issue(s) this PR fixes**:

Related to https://github.com/kubernetes/kubernetes/issues/82437

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
external facing APIs in pluginregistration and deviceplugin packages are now available under k8s.io/kubelet/pkg/apis/
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by klueska** [comment]
What implications does this have if we have changes to these APIs in future releases? I know of at least one addition to the device plugin API coming in 1.17.

**Comment by neolit123** [comment]
LGTM
/assign @sttts @mtaufen

**Comment by dims** [comment]
@klueska we talked about this in the code-organization sub project (sig-arch) and the consensus at least there was that it's worse to force people to import `kubernetes/kubernetes` than to change things. even when it is in kubernetes/kubernetes, we end up changing stuff anyway and we force people to deal with the breakages. So how will the situation be any different was the thought. One thing better than current situation is that at least they will NOT be forced to import k/k and can use k8s.io/kubelet. 

cc @liggitt @smarterclayton

**Comment by dims** [comment]
of course the ultimate arbiter is sig-node here :) cc @derekwaynecarr @dchen1107

**Comment by liggitt** [comment]
> What implications does this have if we have changes to these APIs in future releases? I know of at least one addition to the device plugin API coming in 1.17.

Additions are fine if backwards-compatible. Both APIs have non-alpha levels available (deviceplugin has v1beta1 and pluginregistration has v1 and v1beta1), so those need to follow the applicable portions of the [deprecation policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-parts-of-the-api).

**Comment by liggitt** [comment]
I'm strongly in favor of moving these types to an accessible location. My only question is whether they belong in the kubelet repo or in their own repos (are they more like the CRI API, made available at `staging/src/k8s.io/cri-api/pkg/apis/runtime`)?

**Comment by dims** [comment]
@liggitt i debated that as well. both the packages are unusable outside of their current use case of integration with kubelet, and there are 2 of them, so i picked `k8s.io/kubelet`

**Comment by liggitt** [comment]
> both the packages are unusable outside of their current use case of integration with kubelet, and there are 2 of them, so i picked `k8s.io/kubelet`

if that's the case, that would seem to make sense. will defer to sig-node reviewers

**Comment by mtaufen** [comment]
/assign @dashpole 
for an official opinion, kubelet repo sounds fine IMO

**Comment by dashpole** [comment]
kubelet repo sgtm

**Comment by derekwaynecarr** [comment]
I am fine with the kubelet repo.

Moving this out of k/k into a more focused repo is the right thing.

/approve
/lgtm

**Comment by RenaudWasTaken** [comment]
Should we move the `podresources` directory as well? It's pretty tied to device support as it allows to tie device metrics to pods and containers.

Or are we waiting for it to graduate to beta?

**Pull request merged**
