### PR TITLE
Enabled conformance test for GA feature.

### PR DESCRIPTION
**Pull request by cici37**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
This PR is for adding tests into presubmit since the feature is GAed in 1.30.
We will disable the same tests from running in alpha/beta job through https://github.com/kubernetes/test-infra/pull/32180

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
/assign @jpbetz 
for approval. Thanks!

**Review by jpbetz — COMMENTED** [review]
Need to update `test/conformance/testdata/conformance.yaml` as well

**Comment by cici37** [comment]
> Need to update `test/conformance/testdata/conformance.yaml` as well

Updated. Thanks!

**Review by jpbetz — APPROVED** [review]
/approve
/lgtm

**Comment by cici37** [comment]
/assign @johnbelamaric 
For approval. Would you mind take a look before test freeze? Thank you!

**Pull request merged**
