### PR TITLE
Expand test coverage in master.

### PR DESCRIPTION
**Pull request by brendandburns**

### CODE REVIEW

**Comment by alex-mohr** [comment]
Yay, better tests!

**Comment by satnam6502** [comment]
Has this broken out build?
```
--- FAIL: TestReadConfigData (0.73s)
	helpers_test.go:259: unexpected non-error for http://some.non.existent.url
```

**Comment by brendandburns** [comment]
Travis is still green...

https://travis-ci.org/GoogleCloudPlatform/kubernetes/builds

I will try to repro at head.

**Comment by brendandburns** [comment]
ok, I can repro this on my machine, will investigate more.  I'm guessing some sort of Google network weirdness.

**Comment by brendandburns** [comment]
it's the .url TLD.  Switching to something even more bogus.

**Comment by satnam6502** [comment]
Happy to debug and fix if you don't have the time.

**Comment by brendandburns** [comment]
See:
https://github.com/GoogleCloudPlatform/kubernetes/pull/5199

**Pull request merged**
