### PR TITLE
Update README to show community support

### PR DESCRIPTION
**Pull request by ohohoreilly**
Update README to show community support for local support by https://github.com/kismatic

### CODE REVIEW

**Comment by jlowdermilk** [comment]
@erictune, @brendandburns

I know we talked at the last meetup about getting started guides, but I can't recall what the decision was regarding the various support tiers. Also, for my own education, is a local kubernetes cluster useful outside of dev/test of kubernetes itself?

**Comment by preillyme** [comment]
@jlowdermilk: I want to make sure that we have an easy way to test things out without needing a cluster.

**Comment by erictune** [comment]
@preillyme Thanks for stepping up to support this distro!  I've been asking people who update this file to also update their row with the Kubernetes binary version at which they last successfully ran a cluster (e.g. v0.11.0)


@jlowdermilk There is a proposal (#5141) but no agreement on it yet.

**Comment by preillyme** [comment]
@erictune — Can this be merged as-is and I'll then update the binary version?

**Pull request merged**
