### PR TITLE
Update cAdvisor & go-dockerclient for docker v1.11 compatability

### PR DESCRIPTION
**Pull request by timstclair**

### CODE REVIEW

**Comment by timstclair** [comment]
@k8s-bot unit test this

**Comment by vishh** [comment]
We usually create a new tag on cadvisor before updating godeps.

**Comment by timstclair** [comment]
Actually, cAdvisor is still failing on v1.11, so I'm going to wait to update the godeps until those issues are resolved.

Aside: why do we tag a release everytime we want to pull an update into k8s?

**Comment by timstclair** [comment]
Closing this for now, since there are still issues with cAdvisor on docker 1.11

**Comment by timstclair** [comment]
Updated with cAdvisor v0.23.0

**Comment by Random-Liu** [comment]
Will review today. :)

**Comment by MHBauer** [comment]
given both #23563 & google/cadvisor#1203, does go-dockerclient need to be updated at all?

**Comment by timstclair** [comment]
@MHBauer - It's just a temporary fix before those changes are merged into k8s.

**Pull request merged**
