### PR TITLE
apimachinery: replace deprecated io/ioutil package with io or os package

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Search all `ioutil` in `staging/src/k8s.io/apimachinery` folder, and replace deprecated `io/ioutil` package with `io` or `os` package

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by EuricoAbreu** [comment]
Looks great for me!

**Comment by apelisse** [comment]
What problem does it solve? How did you detect it? How do we prevent these from being included in the future?

**Comment by SataQiu** [comment]
> What problem does it solve? How did you detect it? How do we prevent these from being included in the future?
@apelisse  Ref: https://github.com/kubernetes/kubernetes/issues/100367

While I was reading the code, I found it through GoLand IDE alarms.
It is just a code optimization that does not use the deprecated `io/ioutil` package. 
Of course, this is not very urgent.

/priority important-longterm

**Comment by apelisse** [comment]
I see that there is a problem, this is fixing a symptom, not the cause. You need to figure out how to prevent this from happening again.

**Pull request closed without merging**
