### PR TITLE
Add openapi schema for RawExtension

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
If RawExtension type is used in a CRD, this allows us to run kube-openapi generator on this.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tamalsaha** [comment]
PTAL

**Comment by Jefftree** [comment]
Thanks, changes lgtm. Can you describe the problem you're trying to solve with this change? 

afaik the schema defaults to an "object" type if these methods are not provided so the end behavior is the same with the changes. Is there a specific problem with the current implementation around CRDs or is it just to provide more clarity/documentation?

**Comment by tamalsaha** [comment]
`kube-openapi` generator expects OpenAPISchemaType / OpenAPISchemaFormat specifically implemented when generating openapi schema.

- https://github.com/kubernetes/kube-openapi/blob/master/pkg/generators/openapi.go#L273-L276
- https://github.com/kubernetes/kube-openapi/tree/master/pkg/generators#openapi-extensions

I don't indent to change the actual behavior, just make it so that kube-openapi can work with this custom type.

Similar methods are available for other custom types:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/duration.go#L57-L65

**Comment by tamalsaha** [comment]
Sorry, it seems this change is not required. I was getting an error from kube-openapi. After cleaning all the generated files and regenerating files, everything seems to be working without this pr. Thanks for your time.

**Pull request closed without merging**
