### PR TITLE
Support timeout option in `PullImageRequest` definition.

### PR DESCRIPTION
**Pull request by haosdent**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Refers https://github.com/containerd/containerd/issues/3833

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by haosdent** [comment]
@Random-Liu @yujuhong could you help to take a look? BTW, how to update `staging/src/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go`, I run `hack/update-generated-protobuf.sh` but didn't work.

**Review by mattjmcnaughton — COMMENTED** [review]
I'm definitely not an expert here, but have a couple of high-level questions:

1. Does `containerd` already support the `timeout`? It looks like https://github.com/containerd/containerd/issues/3833 is still open. Or is this diff a precursor to work on that diff? If so, why does this diff need to come first?
2. How will we ensure that other implementations of the `cri` respect this value? In a similar vein, if we do move forward with this addition, should Docker be updated to consume this value via the cri?
3. I don't see `timeout` marked as optional, so won't we need to update all `PullImageRequest` messages to contain this new field?

cc @Random-Liu who knows a lot more about the CRI and containerd than I do :)

**Comment by PatrickLang** [comment]
If a default timeout is set, it should be 15-20 minutes to work on Windows. Some individual layers can be in the 5-10GB range so if you cancel those, you're not going to make forward progress with the pull without lengthening the retry

**Comment by haosdent** [comment]
@mattjmcnaughton Thanks a lot for your review. 

> 1. Does containerd already support the timeout? It looks like containerd/containerd#3833 is still open. Or is this diff a precursor to work on that diff? If so, why does this diff need to come first?

containerd don't care pull image, we need to support in cri instead. I have created pull request at https://github.com/containerd/cri/pull/1385 But cri requires we update cri-api first.

> How will we ensure that other implementations of the cri respect this value? In a similar vein, if we do move forward with this addition, should Docker be updated to consume this value via the cri?

> I don't see timeout marked as optional, so won't we need to update all PullImageRequest messages to contain this new field?

Let me change it to optinal.

**Comment by haosdent** [comment]
> If a default timeout is set, it should be 15-20 minutes to work on Windows. Some individual layers can be in the 5-10GB range so if you cancel those, you're not going to make forward progress with the pull without lengthening the retry

Current behaviour is pulling forever, we would not change to 15-20 mins to change this default behaviour.

**Comment by haosdent** [comment]
>> I don't see timeout marked as optional, so won't we need to update all PullImageRequest messages to contain this new field?

> Let me change it to optinal.

OK, because this protobuf is proto3, `optional` is removed so I would keep this pull request.

**Comment by haosdent** [comment]
Hmm, I found currently docker-shim pull timeout are implemented in kubernetes side instead of containerd side. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/libdocker/kube_docker_client.go#L337 

Let me follow how kubernetes handle dockershim to handle containerd

**Comment by haosdent** [comment]
OK, I just realize kubernetes support pull image timeout before kubernetes/kubernetes#41274 . Close this and create another pr at kubernetes/kubernetes#87641

**Pull request closed without merging**
