### PR TITLE
Fix cross-build breakage after #58174

### LINKED ISSUE #59121: cross-build: PR 58174 causing cross build failure
```
W0131 01:55:36.939] # k8s.io/kubernetes/pkg/kubelet/dockershim
W0131 01:55:36.940] pkg/kubelet/dockershim/helpers_windows.go:52:3: undefined: modifyHostNetworkOptionForContainer
```

https://github.com/kubernetes/kubernetes/pull/58174
https://k8s-testgrid.appspot.com/sig-release-misc#cross-build&graph-metrics=test-duration-minutes
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-cross-build/4469

---
cc: @kubernetes/sig-node-bugs @kubernetes/sig-node-test-failures @filbranden @Random-Liu @vishh
/kind bug
/priority failing-test

### PR DESCRIPTION
**Pull request by filbranden**
**What this PR does / why we need it**:
Fix cross-build breakage after #58174

@cblecker 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #59121

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by filbranden** [comment]
Retry:

/test pull-kubernetes-e2e-kubeadm-gce-canary

**Comment by yujuhong** [comment]
"pull-kubernetes-e2e-kubeadm-gce-canary" is not a required test, so let's just let it fail...

**Comment by filbranden** [comment]
Regarding failure of that test...

There seems to be a disconnect between what "pull-kubernetes-bazel-build" does and what "pull-kubernetes-e2e-kubeadm-gce-canary" expects.

Looking at the details of "pull-kubernetes-bazel-build", it says master:aa12b9b7 (and it seems to have written its build information under that name, at location `gs://kubernetes-jenkins/shared-results/master:`**`aa12b9b7cb9d25e03c3ffbf045ac05f506dce88e`**`,59126:2f2d8867342f56e91c17a535989f046d9e0907f8/bazel-build-location.txt`).

However, "pull-kubernetes-e2e-kubeadm-gce-canary" says master:1150de9c and is failing to pull a build from that location (logs complain about failure finding `gs://kubernetes-jenkins/shared-results/master:`**`1150de9ce657758360bb19202e3382fd657bf83e`**`,59126:2f2d8867342f56e91c17a535989f046d9e0907f8/bazel-build-location.txt`)

Maybe a race condition figuring out what "master" is between the two runs?

Wondering if this is a known issue in test-infra or if we might want to open a new issue about it... If anyone can chime in, let me know if you'd like me to open a formal report.

Cheers,
Filipe

**Comment by cblecker** [comment]
I believe this is known that can happen after the run_after_success jobs.

cc: @BenTheElder

**Comment by BenTheElder** [comment]
> "pull-kubernetes-e2e-kubeadm-gce-canary" is not a required test, so let's just let it fail...

this job should only show up on your PR if you explicity /test it. it will show up on gubernator though.

**Comment by BenTheElder** [comment]
> I believe this is known that can happen after the run_after_success jobs.

Yes, what happens is HEAD changed between the last bazel build on this PR and the kubeadm canary. This is part of why we don't depend on this job yet. Fixing this has open issues in test-infra.

**Pull request merged**
