### PR TITLE
Promote whoami kubectl command

### PR DESCRIPTION
**Pull request by nabokihms**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

https://github.com/kubernetes/kubernetes/pull/116274#discussion_r1128256861

#### Which issue(s) this PR fixes:

--

#### Does this PR introduce a user-facing change?

```release-note
Promote `whoami` kubectl command.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ardaguclu** [comment]
I couldn't find any test corresponding to this command. I think, it would be good to add unit and integration tests for this.

**Comment by nabokihms** [comment]
@ardaguclu 
There is a unit test 
https://github.com/kubernetes/kubernetes/blob/c2cadd2b60424d26678b72506e377dfbf12b9876/staging/src/k8s.io/kubectl/pkg/cmd/auth/whoami_test.go

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by soltysh** [comment]
@nabokihms for GA promotion I'd suggest also adding a short cmd tests, here: https://github.com/kubernetes/kubernetes/tree/master/test/cmd/

**Pull request merged**
