### PR TITLE
update kube-register (0.0.4) in getting started guides

### PR DESCRIPTION
**Pull request by antoineco**
[kube-register v0.0.4](https://github.com/kelseyhightower/kube-register/releases/tag/v0.0.4) can now register minions via hostnames using the `--reverse-lookup` option, making it unnecessary to override the hostname in the kubelet (`--hostname-override`)

### CODE REVIEW

**Comment by justinsb** [comment]
I actually am not very familiar with the cloud formation templates.  I think this is a CoreOS thing - @bakins are you the right person to look at this?

**Comment by antoineco** [comment]
I didn't do any magic inside the Cloudformation template, it's actually
just a copy/paste of the changes I applied to the cloud-config YAMLs.

**Comment by bakins** [comment]
LGTM, but I'd like to get @kelseyhightower 's opinion as well, since he maintains `kube-register`

**Comment by kelseyhightower** [comment]
+1 on the update to v0.0.4 and using the new URL for download.

**Comment by roberthbailey** [comment]
FYI, with the 0.18.0 release next week the kubelet should self-register with the master and from testing that a few folks have done on CoreOS it should no longer be necessary to run kube-register.

**Comment by antoineco** [comment]
@roberthbailey I just saw your comment in #6087, looking forward to it :)
I will create a new pull-request when 0.18.0 is out.

**Pull request closed without merging**
