### PR TITLE
Stepping down from SIG Apps reviewers

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

I'm finding myself with little time to fulfill the reviewer duties in this SIG, so I prefer to make it official.
Thanks to the SIG leads for giving me the opportunity to help for many years.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by aojea** [comment]
😭

**Comment by alculquicondor** [comment]
/hold cancel
Thank you all!

**Pull request merged**
