### PR TITLE
[Provider/Azure] optimize mutex locks

### PR DESCRIPTION
**Pull request by gaurav1086**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
azure.go : use read lock when possible to allow other goroutines to read shared data concurrently.
**Which issue(s) this PR fixes**:

Fixes #
N/A
**Special notes for your reviewer**:
N/A
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by gaurav1086** [comment]
cc @andyzhangx

**Comment by feiskyer** [comment]
@gaurav1086 Could you clarify the issues this PR wants to fix? have you seen performance issues with current lock?

**Comment by gaurav1086** [comment]
@feiskyer no issues. Just a proposal enhance performance since theoretically rlock allows concurrent reading as opposed to a vanilla lock.

**Comment by feiskyer** [comment]
> @feiskyer no issues. Just a proposal to enhance performance since theoretically rlock allows concurrent reading as opposed to a vanilla lock.

OK, thanks. The change looks good.

/retest
/lgtm
/approve

**Pull request merged**
