### PR TITLE
Add missing tags for kms and dynamic-resource-allocation for publishing

### PR DESCRIPTION
**Pull request by dims**
We are missing following tags:
- https://github.com/kubernetes/dynamic-resource-allocation/releases/tag/v0.26.0-rc.0
- https://github.com/kubernetes/kms/releases/tag/v0.26.0-rc.0

/priority critical-urgent
Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

**Comment by dims** [comment]
@kubernetes/sig-release-leads can you please apply milestone 1.26?

**Comment by jimangel** [comment]
Not sure if I have the permissions, but:
/milestone v1.26

**Comment by dims** [comment]
```
go: finding module for package k8s.io/publishing-bot/cmd/validate-rules
go: downloading k8s.io/publishing-bot v0.0.0-20221115120842-0642432fea4c
go: found k8s.io/publishing-bot/cmd/validate-rules in k8s.io/publishing-bot v0.0.0-20221115120842-0642432fea4c
go: downloading github.com/golang/glog v1.0.0
go: downloading gopkg.in/yaml.v2 v2.4.0
I1123 02:08:22.631076     142 rules.go:97] loading rules file : /home/prow/go/src/k8s.io/kubernetes/staging/publishing/rules.yaml
I1123 02:08:22.639121     142 rules.go:133] validating repository order
I1123 02:08:22.639193     142 rules.go:155] validating go versions
I1123 02:08:22.639292     142 validate.go:37] validating directories exist in the kubernetes branch
I1123 02:08:23.341881     142 main.go:50] validation successful
```

**Pull request merged**
