### PR TITLE
Automated cherry pick of #31600

### PR DESCRIPTION
**Pull request by ghost**
Cherry pick of #31600 on release-1.4.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32623)

### CODE REVIEW

**Comment by pwittrock** [comment]
@quinton-hoole  FYI, looks like the tests are broken.  Can you look into this?

**Comment by quinton-hoole** [comment]
@pwittrock Sure, I will sort it out.  Looks like the automatic merge screwed up.

**Comment by quinton-hoole** [comment]
The merge is completely screwed.  I'm not sure what happened.  Will have to take a more careful look tomorrow.

**Comment by quinton-hoole** [comment]
@pwittrock @eparis OK, I figured out the problem.  This PR relies on 3 other (previously non-cherrypicked) commits for it to compile and pass unit tests.  I've added those 3 commits to this PR and confirmed that it now compiles and passes unit tests.

The additional 3 commits are very low-risk, and only affect federation, and this PR specifically. They have been living happily in HEAD for a week and are known not to break anything.  Note that the two new functions added to pkg/watch/watch.go , a library used by kubernetes proper, are only ever invoked in this PR.

I think this is ready to merge at your convenience, as soon as the checks have passed.

**Comment by eparis** [comment]
thank you @quinton-hoole I will keep an eye on it.

**Comment by quinton-hoole** [comment]
Cool @pwittrock @eparis the checks all passed.  I fixed the release note label. Ready to roll.

**Pull request merged**
