### PR TITLE
add semver parsing of gitversion to pkg/version

### PR DESCRIPTION
**Pull request by mikedanese**
cc @zmerlynn

### CODE REVIEW

**Comment by zmerlynn** [comment]
Oh, thank you!

**Comment by zmerlynn** [comment]
#18018 for context.

**Comment by zmerlynn** [comment]
@davidopp: Ping. This LGTM, though.

**Comment by mikedanese** [comment]
@zmerlynn can you review this?

**Comment by zmerlynn** [comment]
LGTM after more thorough review.

**Comment by mikedanese** [comment]
This is blocking 1.1.3 release.

**Pull request merged**
