### PR TITLE
re-enable dynamic provisioning test on gke

### LINKED ISSUE #32377: Re-enable the dynamic provisioner test.
We need to revert #32199 when the gke control plane is updated. This should be merged AFTER gke is ready.

I think https://github.com/kubernetes/kubernetes/pull/32200 may have been merged too early.  I'm doing an issue instead of a pull in case a bot did the merge.

### PR DESCRIPTION
**Pull request by deads2k**
fixes https://github.com/kubernetes/kubernetes/issues/32377

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32896)

### CODE REVIEW

**Comment by deads2k** [comment]
@goltermann fyi

**Comment by dims** [comment]
@k8s-bot gke test this

**Comment by dims** [comment]
looks like that triggered - "Jenkins GKE smoke e2e" which is probably not what you needed

**Comment by pwittrock** [comment]
@jlowdermilk Assigning to you to take a look at Monday.  This is one of the very few items on the list of 1.4 issues

**Comment by goltermann** [comment]
LGTM - quick change.  @jlowdermilk we can back out if you see any issue with this.

**Comment by deads2k** [comment]
@k8s-bot unit test this: issue #32770

**Comment by jlowdermilk** [comment]
I was out Monday. Change lgtm tho, GKE has storage.k8s.io/v1beta1 for 1.4

**Pull request merged**
