### PR TITLE
Bump fsouza/go-dockerclient

### PR DESCRIPTION
**Pull request by ghost**
Updating go-dockerclient to get https://github.com/fsouza/go-dockerclient/pull/387 which is needed for #14991

### CODE REVIEW

**Comment by swagiaal** [comment]
@pmorie @k8s-merge-robot does not seem to be happy with the ok-to-merge tag

**Comment by dchen1107** [comment]
LGTM

**Comment by pmorie** [comment]
Hitting the button so @swagiaal can rebase #14991

**Comment by dchen1107** [comment]
cc/ oncall, @JanetKuo 

I am manually merging this one since it can unblock Sami's other development. This shouldn't cause any rebase issue in merge queue. Thanks!

**Pull request merged**
