### PR TITLE
Fix typo in CHANGELOG-1.22.md

### PR DESCRIPTION
**Pull request by ialidzhikov**
/kind cleanup

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pmmalinov01** [comment]
Thanks @ialidzhikov 
/triage accepted

**Comment by ialidzhikov** [comment]
Thanks @pmmalinov01 ! Can you add a `/lgtm` as well?

**Comment by ialidzhikov** [comment]
> Thanks @pmmalinov01 ! Can you add a `/lgtm` as well?

And `/ok-to-test`..

**Comment by pmmalinov01** [comment]
I wanted to check if "approve" applies to the rest :)
/lgtm
/ok-to-test

**Pull request merged**
