### PR TITLE
Kube-proxy flags and config on options folder

### PR DESCRIPTION
**Pull request by knabben**
#### What type of PR is this?

/kind cleanup
/area kube-proxy
/sig network

#### What this PR does / why we need it:
Kubelet, scheduler and controller under `cmd` folder maintains a base `./options` folder  holding functions for 
flags and configuration management, this PR introduces the same structure so we keep them standardized and clear to test/change.

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/enhancements/pull/2158

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by knabben** [comment]
/retitle [WIP] Kube-proxy flags and config on options folder

**Comment by aojea** [comment]
@knabben @jayunit100  @hanlins is this based on what we talked yesterday in the friday sig-net/kproxy/... meeting?

**Comment by knabben** [comment]
> @knabben @jayunit100 @hanlins is this based on what we talked yesterday in the friday sig-net/kproxy/... meeting?

Not directly related, the specific one is not enforcing the flag precedence (as agreed on kproxy meeting), it's only a refactor to move flags and config into the `options` folder like the other components are doing.

**Comment by hanlins** [comment]
Hi @aojea, yes. In the meeting we said we want a quick fix, but since @knabben has already made progress refractoring and adding test coverage, I think it doesn't hurt to include the change.

**Comment by hanlins** [comment]
I see, so we still need a separate PR to fix the precedence issue, right? @knabben

**Comment by knabben** [comment]
> I see, so we still need a separate PR to fix the precedence issue, right? @knabben

Yes, this one has the same behavior as before, only a cleanup/standardization.

**Pull request closed without merging**
