### PR TITLE
atomic_writer: Add tests for FsUser

### PR DESCRIPTION
**Pull request by rata**
FsUser was added to atomic writer in "set proper file permission for
projected service account volume" (3db7275b549559696c42c0b5f51c9a2397e9571d),
although no test were added at the atomic writer level.

While working on code that uses this, I realized there is no test for
this functionality. We can't just add tests that chown the user today,
as that requires privileges and the CI runs without (we can chown the
group to others, but for the owner we need privileges).

However, what we can do is run them anyways and assert that if the test
requires root and is not running as root, we expect a failure. This way,
if the privileged operation is not run for some test (i.e. we introduce
a bug), the CI would still catch it.

Signed-off-by: Rodrigo Campos <rodrigoca@microsoft.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR adds tests for currently used code. New PRs will use this too, so I wrote some tests.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
If you know if we can run the CI as root, that would be great. Also, not running as root also forced me to test a function superficially in PR #111090 (see the downward api tests). However, this improves the situation significantly until we can run as root the tests.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
I found this while working on https://github.com/kubernetes/enhancements/issues/127 and its PR: https://github.com/kubernetes/kubernetes/pull/111090. This improves the test of current features, it is not a requirement to move with the userns KEP linked.

```docs

```

### CODE REVIEW

**Comment by rata** [comment]
cc @giuseppe

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by rata** [comment]
/remove-lifecycle stale


@Jiawei0227  @mattcary friendly ping?

**Comment by mattcary** [comment]
Sorry, this got buried.

It looks like from the other CL that the e2e tests in test/e2e/auth/service_accounts may cover this case?

I'm asking because doing things that require assumptions about the system seem to me to make more sense to do in e2e tests. Unit tests are better for tests that are independent of system details. This does mean that they're more limited.

I fear that the confusion over whether or not particular tests should pass or fail depending on what user the test is running as is going to keep any failures from being actionable. If the existing e2e tests don't cover what you've done here, maybe it would be better to move this test to an appropriate place in the e2e tests?

**Comment by rata** [comment]
@mattcary Oh, sure, if that is the idea, SGTM. I just did it because unit test today _are_ testing some system dependant things.

I agree using e2e tests for that might be simpler. Thanks!

**Pull request closed without merging**
