### PR TITLE
Fix a typo in comment

### PR DESCRIPTION
**Pull request by AliMirlou**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

It's just a small typo fix in a comment

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/sig api-machinery

### CODE REVIEW

**Comment by AliMirlou** [comment]
@Joseph-Irving The tests failed a couple of times for no reason but I think it's safe to do the merging now. However, I'm curious about what is wrong with the tests... Can you explain?

**Comment by Joseph-Irving** [comment]
The Kubernetes tests, especially e2e and conformance are rather complex and it's not uncommon to see tests flake for a variety of reasons (race conditions, nodes they're running on are resource starved etc). If you do see a particular test in one of the jobs consistently failing it can be helpful if you raise an issue labelled flake, https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/testing.md#troubleshooting-a-failure

**Comment by AliMirlou** [comment]
@wojtek-t Ping! 😄

**Comment by wojtek-t** [comment]
The PR is approved, but we're in code-freeze now. It will merged once we lift it.

**Pull request merged**
