### PR TITLE
Wei run

### PR DESCRIPTION
**Pull request by StudyNick**
Print function information

Modify Code:
```
                        err := app.Run(s)

			if err != nil {
				fmt.Fprintf(os.Stderr, "%v\n", err)
			}

			return err
```

Special notes for your reviewer:
`cmd/kube-controller-manager/controller-manager.go`
Example:

```
if err := app.Run(s); err != nil {
    fmt.Fprintf(os.Stderr, "%v\n", err)
    os.Exit(1)
}
```

### CODE REVIEW

**Comment by StudyNick** [comment]
I signed it!

**Comment by resouer** [comment]
@k8s-bot ok to test

**Comment by resouer** [comment]
@StudyNick Could you please modify your PR's title and description to clarify what's your problem and how you solve it? 

Then I'd like to review for you.

**Comment by StudyNick** [comment]
@resouer i do

**Comment by StudyNick** [comment]
@resouer I have already modified completed

**Comment by resouer** [comment]
Please fix the CI :)

**Comment by mikedanese** [comment]
This logs the error twice, no?

**Comment by mikedanese** [comment]
This is a redundant log statement:

https://github.com/kubernetes/kubernetes/blob/master/cmd/hyperkube/hyperkube.go#L191

**Pull request closed without merging**
