### PR TITLE
add tests to reproduce bugs in preemption

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

add tests to reproduce bugs #119770 in preemption.
This test should fail until https://github.com/kubernetes/kubernetes/pull/119778 https://github.com/kubernetes/kubernetes/pull/119779 are merged.

#### Which issue(s) this PR fixes:

Part of #119770

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
@sanposhiho this can be closed, right?

**Comment by sanposhiho** [comment]
@Huang-Wei 
This PR contains what https://github.com/kubernetes/kubernetes/pull/119778 contained previously (we removed from that PR though)
If we want to have integ tests for bugs we found, this PR should still be valid. If these are too much and just waste integration test time, then I'm fine to close it.

**Comment by Huang-Wei** [comment]
@sanposhiho I'm fine with continuing the work in this PR or start a new PR. To clarify: the work we left includes:

1. Correct the integration test's semantics to support `preemptedPodIndexes: map[int]struct{}{}` - [comment](https://github.com/kubernetes/kubernetes/pull/119778#discussion_r1286249669)
2. Compose a minimum viable integration test to cover #119778 **only**. And be aware of some comments like [this](https://github.com/kubernetes/kubernetes/pull/119778#discussion_r1286193881).
3. #119779 should go with its own integration test in its PR.

**Comment by alculquicondor** [comment]
Was this ever merged in a different PR?

**Pull request closed without merging**
