### PR TITLE
Revert 108033

### PR DESCRIPTION
**Pull request by tkashem**
#### What type of PR is this?

/kind bug
/kind cleanup
/kind flake

#### Which issue(s) this PR fixes:
Fixes # 109136

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/hold

This was resolved

**Comment by aojea** [comment]
no failures since the fix merged https://storage.googleapis.com/k8s-triage/index.html?ci=0&pr=1&test=preshutdown

**Comment by tkashem** [comment]
yes. closing it, thanks!

/close

**Pull request closed without merging**
