### PR TITLE
Remove RollbackTo that is no longer used from deployment controller

### PR DESCRIPTION
**Pull request by s-ito-ts**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
kube-apiserver no longer serves the following deprecated APIs by #85903:
Deployment in extensions/v1beta1 and apps/v1beta1.  
Therefore RollbackTo is not used.
This PR is removed the code of "Rollback To" from deployment controller.

Referrence:
RollbackTo is no longer supported in API versions starting apps/v1beta2.
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
-> Rollback To

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
/sig apps

### CODE REVIEW

**Review by janetkuo — APPROVED** [review]

**Comment by s-ito-ts** [comment]
@janetkuo Thanks for approve.
Would you please add a lgtm label to merge this PR?

**Pull request closed without merging**
