### PR TITLE
Convert kubeadm TODOs from comments to issues

### PR DESCRIPTION
**Pull request by errordeveloper**
https://github.com/kubernetes/kubernetes/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20author%3Aerrordeveloper%20kubeadm

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33932)

### CODE REVIEW

**Comment by jbeda** [comment]
I hate to do this but could you perhaps leave a quick summary of the TODO in addition to the link to the PR? 

(I also thought I saw a redirect from k8s.io to issues to make URLs shorter, but I can't find it now).

**Comment by jbeda** [comment]
Ah!  Found it.  You can use https://issues.k8s.io/33932 as a shorter URL to a kubernetes issue.  See https://github.com/kubernetes/k8s.io/blob/master/k8s.io/configmap-nginx.yaml#L157

**Comment by errordeveloper** [comment]
> I hate to do this but could you perhaps leave a quick summary of the TODO in addition to the link to the PR?

Sure, I wanted to but was a bit lazy... Will take care of this after LinuxCon.

**Comment by luxas** [comment]
@errordeveloper Should we close this?
You can send a new patch with these fixes later, but it's not a priority right now
Also, rebase hell is waiting for you if you keep this one :)

**Comment by errordeveloper** [comment]
Please keep it open, that way I won't forget!

**Comment by jbeda** [comment]
@errordeveloper -- do you still want this around?

**Comment by luxas** [comment]
Most of these issues are now outdated since we've moved to the kubeadm repo and also many of them have been fixed.

Closing this PR because we're not gonna merge it, and there has been no activity for a long time.

You still have it in your own branch of course if you want to use it as a backlog.

**Pull request closed without merging**
