### PR TITLE
Add check to avoid panic

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
If len(r) != 2, otherwise r[1] does not exist, it may panic.
Secondly, err2 is odd.  err  instead would be better.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
@jbeda Looks like you added the method.  I don't recognize it and regexes are not my strong suit.

**Comment by jbeda** [comment]
@k8s-bot ok to test

**Comment by jbeda** [comment]
@zhangxiaoyu-zidif -- have you seen this actually panic anyplace?  If so, can we add a test to demonstrate the problem?

I'm having a hard time figuring out how the regex could match but not have a capture group.

**Comment by zhangxiaoyu-zidif** [comment]
@jbeda Hi, thanks for review. Is the test to demonstrate the problem  unit test?

**Comment by jbeda** [comment]
@zhangxiaoyu-zidif You claim that there is a possibility for a panic here.  That would mean that we are missing a test case from https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/bootstrap/util_test.go#L184.  Let's add that test case there.

I'm not sure what got missed but I could be wrong.  From my reading of the code here there is no bug.

**Comment by brendandburns** [comment]
/lgtm

/release-note-none

LGTM + release-note-none from the bulk LGTM tool

**Comment by jbeda** [comment]
@brendanburns I don't think that this is a real issue.  There is a query waiting on @zhangxiaoyu-zidif.  We need to make sure we expand tests to show that we are fixing a real issue.

**Comment by brendandburns** [comment]
Fair enough I was in the bulk LGTM tool...

I should enable it to widen context...

--brendan

________________________________

**Pull request closed without merging**
