### PR TITLE
Remove the invalid kubectl proxy example

### PR DESCRIPTION
**Pull request by poneding**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The removed example in the kubectl proxy command is invalid：See [Files Changed](https://github.com/kubernetes/kubernetes/pull/118222/files)
```bash
kubectl proxy --api-prefix=/k8s-api
```
This makes e.g. the pods API available at `localhost:8001/k8s-api/api/v1/pods/` other then `localhost:8001/k8s-api/v1/pods/`.

So, the purpose of this pr is to remove the invalid kubectl proxy example.

### CODE REVIEW

**Comment by poneding** [comment]
> it is better to fix the example than remove it, no?
But I think these two examples are the same effect, they are repeated. What do you think?😝
image

**Comment by aojea** [comment]
lol, didn't get that far, sorry , good point

**Pull request closed without merging**
