### PR TITLE
Delete dead code in pkg/scheduler

### PR DESCRIPTION
**Pull request by misterikkit**
**What this PR does / why we need it**:
This is just some cleanup. I found some unused code while evaluating the scheduler code.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
/kind cleanup
/sig scheduling

### CODE REVIEW

**Review by bsalamat — APPROVED** [review]
/lgtm

**Review by bsalamat — COMMENTED** [review]
/lgtm

**Comment by losipiuk** [comment]
@bsalamat, @misterikkit, Cluster Autoscaler depended on `GetPredicateMetadataProducer` and `GetPredicates` for sake of simulating scheduler behavior.
With this change CA no longer compiles after godeps update. Can we revert it.?
Or just part of it which deletes those two methods?

**Comment by losipiuk** [comment]
cc: @MaciekPytel

**Comment by losipiuk** [comment]
I added a PR which adds back methods we need https://github.com/kubernetes/kubernetes/pull/68196

**Comment by misterikkit** [comment]
> With this change CA no longer compiles after godeps update

Whoops. We don't have good visibility into downstream dependencies.

**Comment by losipiuk** [comment]
> Whoops. We don't have good visibility into downstream dependencies.

No worries. We are importing scheduler codebase into CA. But it does not mean that all code in scheduler should be treated as a library. With deprecation policies etc. 
It is natural things break and will break. We are updating godeps quite regularly so typically it does not take a lot of time to spot regression and react :)

**Comment by misterikkit** [comment]
@MaciekPytel @losipiuk BTW we do have some more disruptive changes planned down the road. I'd be interested in your feedback on [the proposal](https://groups.google.com//forum/#!topic/kubernetes-sig-scheduling/kdRqO818ApI).

**Pull request merged**
