### PR TITLE
Optimize the for range code in types.go

### PR DESCRIPTION
**Pull request by jyz0309**
Signed-off-by: jyz0309 <45495947@qq.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Optimize the for range code in types.go.
Just make the code clean.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
/ok-to-test

LGTM. Please squash the commits.

**Comment by jyz0309** [comment]
> /ok-to-test
> 
> LGTM. Please squash the commits.

Done. PTAL

**Comment by jyz0309** [comment]
@Huang-Wei All tests pass. PTAL~

**Comment by alculquicondor** [comment]
@jyz0309 note that we are under code freeze. Your change will be merged next month. Thank you for your contribution.

**Comment by alculquicondor** [comment]
/remove-area apiserver
/remove-sig apimachinery

I'm not sure why this got tagged as such. This is just scheduler code.

**Pull request merged**
