### PR TITLE
changelog：Fix hyperlink errors about 78668 and 78734

### PR DESCRIPTION
**Pull request by yangjunmyfm192085**
Signed-off-by: JunYang <yang.jun22@zte.com.cn>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix hyperlink errors about 78668 and 78734
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by yangjunmyfm192085** [comment]
/assign @pacoxu
I fixed some errers about changelog1.15.
Can you check it out？
 If there is no conflict with your modification, help me tag ok-to-test and lgtm？ 
thanks.

**Comment by yangjunmyfm192085** [comment]
> /assign @pacoxu
> I fixed some errers about changelog1.15.
> Can you check it out？
> If there is no conflict with your modification, help me tag ok-to-test and lgtm？
> thanks.
@pacoxu，If there are no other questions, can you help me label it?
thank you very much.

**Comment by heqg** [comment]
Please combine into other pr，like https://github.com/kubernetes/kubernetes/pull/98209


https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits
Trivial Edits
Each incoming Pull Request needs to be reviewed, checked, and then merged.

While automation helps with this, each contribution also has an engineering cost.
Therefore it is appreciated if you do NOT make trivial edits and fixes, but
instead focus on giving the entire file a review.

If you find one grammatical or spelling error, it is likely there are more in
that file, you can really make your Pull Request count by checking the formatting,
checking for broken links, and fixing errors and then submitting all the fixes
at once to that file.

Some questions to consider:

Can the file be improved further?
Does the trivial edit greatly improve the quality of the content?

**Comment by yangjunmyfm192085** [comment]
/assign feiskyer
/assign saschagrunert
Hi, Could you take a moment to help take a look?
Thank you very much.

**Comment by wilsonehusin** [comment]
I'm not inclined to accept this PR because:
- the changes count as [trivial edits](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits) (as quoted by @heqg above)
- this is a change to an [inactive release line](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#non-active-branch-history)

Please consider making updates to active release lines instead. Changes to inactive release lines will only be accepted if they are from a batch of fixing similar pattern, like #98209.

**Pull request closed without merging**
