### PR TITLE
fix TODO: remove flag --service-account-private-key-file

### PR DESCRIPTION
**Pull request by linyouchong**
**What this PR does / why we need it**:
fix TODO: remove flag --service-account-private-key-file

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
Cloud Controller Manager: remove flag --service-account-private-key-file
```

### CODE REVIEW

**Comment by CaoShuFeng** [comment]
This is a break change.
You need to remove all "--service-account-private-key-file" from test script.

**Comment by liggitt** [comment]
clarify in the release notes this only applies to the *cloud* controller manager

**Comment by linyouchong** [comment]
@liggitt @CaoShuFeng 
Updated, thanks!

**Comment by CaoShuFeng** [comment]
> Most of the removed invocations were for the kube-controller-manager binary, where this option still exists and is required

Sorry, I mixed those two "--service-account-private-key-file".

I am really sorry for wasting your time. @linyouchong 
I glanced at all the "--service-account-private-key-file" in codes, it looks like all of them are passed to kube-controller-manager...

Sorry again for my invalid comment.

**Comment by CaoShuFeng** [comment]
The CI said:

>  ERROR(all) cmd/kube-controller-manager/app/options/options_test.go:153:5: unknown field ServiceAccountKeyFile in struct literal

**Pull request closed without merging**
