### PR TITLE
add myself and Walter as sig-cloud-provider api reviewers

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kiman@vmware.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by andrewsykim** [comment]
cc @cheftako

**Review by cheftako — APPROVED** [review]

**Comment by liggitt** [comment]
/approve

per https://raw.githubusercontent.com/kubernetes/kubernetes/master/pkg/cloudprovider/OWNERS and https://github.com/kubernetes/community/tree/master/sig-cloud-provider#leadership

**Comment by andrewsykim** [comment]
Removed github handles in the commit message, can I have another LGTM please :)

**Comment by liggitt** [comment]
@andrewsykim @cheftako - I'd suggest joining https://groups.google.com/forum/#!forum/kubernetes-api-reviewers as well, discussions of edge cases tend to happen there and are good to keep up with

**Pull request merged**
