### PR TITLE
Support more auth strategies in `kubeadm join` with discovery file

### LINKED ISSUE #2708: kubeadm join discovery/kubeconfig file does not recognize client-go credential plugin
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT (arguably)

## Versions

**kubeadm version** (use `kubeadm version`): 1.22.6 (but all current versions are affected)

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.22.6
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04.4 LTS
- **Kernel** (e.g. `uname -a`): 5.13.0-1023-azure
- **Container runtime (CRI)** (e.g. containerd, cri-o): containerd
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): kubenet

## What happened?

When `kubeadm join --discovery-file ...` is passed discovery file / kubeconfig that includes any [client-go credential plugin](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins) (aka exec), kubeadm does not recognize the credential plugin and treats kubeconfig file as not having any auth credentials: `[discovery] Discovery file does not contains authentication credentials, using unauthenticated request for validating TLS connection`

(Same behavior can be observed with `JoinConfiguration` pointing - via `discovery.file.kubeConfigPath` - to such kubeconfig).

## What you expected to happen?

kubeadm can be expected to accept any valid kubeconfig here, as long as it contains some credentials. This seems to have been the intent of [`HasAuthenticationCredentials`](https://github.com/kubernetes/kubernetes/blob/0fe0dbf3fb8cf501c24c87f4113a3819cb86a550/cmd/kubeadm/app/util/kubeconfig/kubeconfig.go#L118-L143) (possibly as the first step in ensuring a self-contained kubeconfig can be produced), but currently it only checks for token, basic and X.509 authentication. There are valid use cases for using client-go credential plugins here (we would like to be able to use [Azure/kubelogin](https://github.com/Azure/kubelogin), for example). 

As another data point, kubelet itself does not have any problem accepting kubeconfig with exec plugin as bootstrap-kubeconfig. (Neither does kubectl, and likely any other generic client-go consumer ...)

## How to reproduce it (as minimally and precisely as possible)?

```bash
# create kubeconfig with (fake) client-go credential plugin
cat > kubeconfig-with-exec <<EOF
apiVersion: v1
kind: Config
users:
- name: my-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: example-client-go-exec-plugin
clusters:
- cluster:
    server: https://localhost:443
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-user
  name: my-cluster
current-context: my-cluster
EOF

# attempt joining using the above
kubeadm join -v=4 --discovery-file kubeconfig-with-exec
```

Observe `[discovery] Discovery file does not contains authentication credentials, using unauthenticated request for validating TLS connection` in log.

## Anything else we need to know?

Besides client-go credential plugins, kubeadm currently would not recognize two other [auth info flavors generally supported by client-go](https://github.com/kubernetes/client-go/blob/d4fc9af2dfada718e01e58a7a929a0cdaec8f77c/tools/clientcmd/api/types.go#L101-L151):
* `TokenFile` - pointer to a file that contains a bearer token.
* `AuthProvider` - custom authentication plugin. Looking at the [state](https://github.com/kubernetes/client-go/tree/master/plugin/pkg/client/auth) of support for authentication plugins, most (azure/gcp/openstack) are migrating to client-go credential plugins - yet another reason to support this in kubeadm. This leaves [OIDC authenticator](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#option-1-oidc-authenticator).

I am not sure how important it is to support either of these two; but mentioning them here for completeness.

### PR DESCRIPTION
**Pull request by tallaxes**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Adds support for the remaining client-go authentication strategies in `kubeadm join` with discovery/kubeconfig file: client-go authentication plugins (`exec`), `tokenFile`, and `authProvider`. This removes unnecessary constraints on which auth strategies can be used for `kubeadm join`, and supports use cases that require one of these auth strategies.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/2708

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: Added support for additional authentication strategies in `kubeadm join` with discovery/kubeconfig file: client-go authentication plugins (`exec`), `tokenFile`, and `authProvider`
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
The change seems good @tallaxes Thank you
Could you please squash the commits into 1 as it is a contained change.

/approve

**Comment by pacoxu** [comment]
/label tide/merge-method-squash
can squash commits into one as well.

**Comment by sftim** [comment]
Does this change need a docs update?

**Comment by pacoxu** [comment]
I think we should update the docs.

> If kubeadm join is invoked with --discovery-file, file discovery is used; this file can be a local file or downloaded via an HTTPS URL; in case of HTTPS, the host installed CA bundle is used to verify the connection.

https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/
https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/

The current docs don't mention support for `TokenFile` or `AuthProvider`.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/b07ee3654732128f8de93b54b0c4a56ffb91fa95/cmd/kubeadm/app/cmd/join.go#L87-L96

`The second is to provide a file - a subset of the standard kubeconfig file.`

We support `token` only at first and now we support `tokenFile` and `authProvider`. We may update the comment here.

**Pull request merged**
