### PR TITLE
Automated cherry pick of #70715: Add transformation_operations_total to transformer metrics.

### PR DESCRIPTION
**Pull request by zshihang**
Cherry pick of #70715 on release-1.14.

#70715: Add transformation_operations_total to transformer metrics.

### CODE REVIEW

**Comment by tpepper** [comment]
The parent PR is marked as a feature, which is not something we cherry pick.  Need triage by SIG owners.

**Comment by immutableT** [comment]
Providing context for this CP.
The original PR improved observability of the storage transformer components of kube-apiserver via  additional metrics. 
It was labeled as a feature since I am not sure if there is a more precise label for this type of changes.
This CP will allow us to improve monitoring of clusters that are already in production once they are upgraded.

**Review by immutableT — APPROVED** [review]
Unfortunately, the currently implemented monitoring functionality for Envelope Encryption in 1.14 (and below) makes it difficult to support production deployments. Concretely, it is not possible to calculate the availability of the service.

This CP addresses this issue.

**Comment by liggitt** [comment]
I agree that this falls outside the bounds of what we want for cherry-picks, since it is adding capabilities, not fixing regressions or bugs.

/close

**Pull request closed without merging**
