### PR TITLE
e2e: use framework.ExpectEqual() for test/e2e/lifecycle

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
e2e: use framework.ExpectEqual() for test/e2e/lifecycle

**Which issue(s) this PR fixes**:

Ref #79686

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by draveness** [comment]
I think I claimed this in that issues below.....

**Comment by SataQiu** [comment]
@draveness Sorry for missing that. But I found that you made the claim a few days ago. There was no actual submission in these two days. In order to speed up closing this Issue, I take the liberty to pick it up.  Feel free to review it.

**Comment by draveness** [comment]
> @draveness Sorry for missing that. But I found that you made the claim a few days ago. There was no actual submission in these two days. In order to speed up closing this Issue, I take the liberty to pick it up. Feel free to review it.

You could always ask first. I was going to open the PR and found out you already take it.

**Pull request merged**
