### PR TITLE
Fix OnStoppedLeader call without acquiring leadership during election

### PR DESCRIPTION
**Pull request by hamersaw**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Currently the OnStoppedLeader function is called during leader election whether the elector successfully acquired leadership or not. Specifically, if an elector context is canceled before acquiring leadership the OnStoppedLeader func is called even though OnStartedLeader is never called. This bug seems to be have been introduced during the transition from a shutdown channel to context in the Run function.

Moving the OnStoppedLeader defer until after le.acquire is successful mitigates this issue.

#### Which issue(s) this PR fixes:
_NA_

#### Does this PR introduce a user-facing change?
NONE

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Review by binacs — COMMENTED** [review]
/ok-to-test

**Comment by jiahuif** [comment]
/lgtm
/retest

That looks reasonable. OnStoppedLeading returns nothing, and thus we do not need to explicitly ignore returned value.

**Comment by aojea** [comment]
is not possible to add an unit tests https://github.com/kubernetes/kubernetes/blob/3b76c758317bbeb0e72f74842a11343571bf2c88/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection_test.go#L1088 ?

**Comment by dims** [comment]
@hamersaw will you be revisiting this PR? looks like there are pending comments (+ request for a unit test)

**Comment by hamersaw** [comment]
> @hamersaw will you be revisiting this PR? looks like there are pending comments (+ request for a unit test)

@dims I have been planning on it. Such a small change, should be easy to fix testing but just haven't found the time to swing back to this.

**Pull request closed without merging**
