### PR TITLE
Cleanup for dualstack e2e tests

### PR DESCRIPTION
**Pull request by aramase**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
 
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Fixes nits and refactor test deployment spec creation. Follow up to my previous PR for dual stack e2e tests - https://github.com/kubernetes/kubernetes/pull/78801

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by aramase** [comment]
cc @spiffxp @lachie83

**Review by neolit123 — COMMENTED** [review]
/ok-to-test
/priority important-longterm

**Comment by neolit123** [comment]
cc @Arvinderpal @aojea

**Comment by aojea** [comment]
SGTM

**Comment by spiffxp** [comment]
/approve
/lgtm
thanks for the fixes

**Pull request merged**
