### PR TITLE
update skydns config so that it does not rely on /etc/hosts

### PR DESCRIPTION
**Pull request by ArtfulCoder**
cherry-pick #15962
Helps workound corrupt /etc/hosts file issue where localhost cannot be resolved. (due to docker bug)

### CODE REVIEW

**Comment by ArtfulCoder** [comment]
@thockin @bgrant0607 FYI cherry-pick

**Comment by dchen1107** [comment]
ok to test

**Comment by dchen1107** [comment]
LGTM

**Comment by bgrant0607** [comment]
LGTM

**Comment by ArtfulCoder** [comment]
@k8s-bot test this please

**Pull request merged**
