### PR TITLE
Remove predicates.NodeInfo dependency from kubelet

### LINKED ISSUE #84195: Remove predicates.NodeInfo dependency from kubelet
**What would you like to be added**:
Remove predicates.NodeInfo dependency from kubelet

**Why is this needed**:
Kubelet uses predicates.NodeInfo interface to define a node getter: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L963

Its implementation is based on node corelisters: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2311

We are removing predicates.NodeInfo interface and Kubelet should move to use corelisters.NodeLister directly

/sig scheduling
/sig node
/priority important-soon
/help

### PR DESCRIPTION
**Pull request by denkensk**
**What type of PR is this?**
/kind cleanup
/sig scheduling
/sig node
/priority important-soon

**What this PR does / why we need it**:
Sig-Scheduler is removing predicates.NodeInfo interface and Kubelet should move to use corelisters.NodeLister directly

**Which issue(s) this PR fixes**:
Fixes #84195

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
/assign @ahg-g

### CODE REVIEW

**Comment by ahg-g** [comment]
Thanks for removing this unnecessary dependency on the scheduler.
/lgtm

/assign @tallclair

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

This diff looks good to me, but would love confirmation from @ahg-g !

**Review by zouyee — APPROVED** [review]

**Comment by tallclair** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
