### PR TITLE
Revert "Merge pull request #31023 from vishh/gci-default"

### PR DESCRIPTION
**Pull request by mtaufen**
This reverts PR #31023, which had made GCI the default node image for open source. This revert makes container-vm the default for open source again.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32913)

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM

**Comment by eparis** [comment]
Is this what I want in 1.4, and we should remove the candidate label from #32738 ?

**Comment by pwittrock** [comment]
Context for @eparis :

I had a long discussion with Vish and Dawn about this.  We are rolling this back because trying to make sure both gci and cvm were well supported in 1.4 was creating an overhead burden on the release process.  This should reduce the scope of testing needed for 1.4.

**Comment by mtaufen** [comment]
@k8s-bot test this

**Comment by pwittrock** [comment]
@k8s-bot test this issue: #IGNORE

**Pull request merged**
