### PR TITLE
Automated cherry pick of #53330

### PR DESCRIPTION
**Pull request by kawych**
Cherry pick of #53330 on release-1.8.

#53330: Add permisions for Metrics Server to read resources on cluster level.

```release-note
Fix permissions for Metrics Server.
```

### CODE REVIEW

**Comment by piosz** [comment]
/lgtm
/approve
please add release notes

**Comment by jdumars** [comment]
@piosz re: release notes, do you mean they need to be added to this cherrypick?

**Comment by piosz** [comment]
@jdumars what is the policy? I was under impression, that we want to have release-notes for all cherry-picks.

**Comment by jpbetz** [comment]
Reminder: Please add 'cherrypick-candidate' label to PRs like this so we can find them more easily.  I've added it to this one.

**Comment by jdumars** [comment]
@piosz I need to look into that, as it's news to me.  Do you have any links to where that policy might have been set?

**Comment by piosz** [comment]
@jdumars I don't know about any. Maybe @wojtek-t has some knowledge about it?

**Pull request merged**
