### PR TITLE
fc: Drop multipath.conf snippet

### PR DESCRIPTION
**Pull request by fabiand**
**What this PR does / why we need it**:
Removes multipath.conf - The code does not make use of it - or ensure s that it's getting used - and it should in addition be handled elsewehre.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

A minimalistic multipath.conf got written, but it was useless, as
it is unclear if multipathd is running and there was also no
config reload triggered.

This patch drops this snippet. In general it's probably a better idea
to leave the multipath.conf to the component managing the host.

Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36698)

### CODE REVIEW

**Comment by fabiand** [comment]
@rootfs Could you please review this patch.

**Comment by fabiand** [comment]
I signed the CNCF CLA as an employee, and my email address I used for submission is also associated to my github account. Let me know what else I should check to get this recognized by the bot.

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by dims** [comment]
@fabiand can you please leave a message for the bot exactly with the words "I signed it!" in a new comment?

**Comment by fabiand** [comment]
I signed it!

**Comment by dims** [comment]
@kubernetes/test-infra-admins Can you please check why we still have cla:no after following all instructions from the bot

**Comment by apelisse** [comment]
@foxish can you have a look?

**Comment by rootfs** [comment]
multipath.conf is used for devicemapper. If it is not there, devicemapper multipath won't start properly.

**Comment by fabiand** [comment]
Right - But who is taking care to bring up multipathd once the file is written?

Also: I wonder if not the OS is responsible for configuring multipath.

**Comment by fabiand** [comment]
Right - But who is taking care to bring up multipathd once the file is written?

Also: I wonder if not the OS is responsible for configuring multipath.

**Comment by rootfs** [comment]
Yes, FC hosts are expected to have multipathd systemd service enabled and started.

**Comment by fabiand** [comment]
Even if multipathd.service is enabled and started, then it still has no effect, because multipathd must be reloaded/-started to pickup the new `multipath.conf`. And I do not see that this is happening in the kubelet.

**Comment by fabiand** [comment]
Besides that - The kubelet should not write multipath conf.

Depending on the default settings of multipath conf it could wreck an OS - the device names could change on a next reboot, which could lead to an unbootable host.

**Comment by rootfs** [comment]
No, the code doesn't overwrite existing multipath.conf. It creates one only if none is there. 
multipathd reload could be an issue. I'll get a setup to test it.

**Comment by rootfs** [comment]
Ok, I found multipathd needs to restart to pick up new multipath.conf. Also confirmed by reading [mpathconf](https://linux.die.net/man/8/mpathconf).

Starting multipathd service or enabling multipath using `mpathconf` are both fixes to me. @fabiand ?

**Comment by fabiand** [comment]
I would object if I can :) I think it's just wrong to do it from the kubelet.
Like networking, this basic storage configuration should be part of the build process.

Instead of modifying it I'd then suggest to rather raise a warning or alike.

multipath.conf is really something to the host, and not something an application like the kubelet should manage or modify.
As stated above - it can wreck the host.

Also: If you run the kubelet in a container - then any multipath configuration will not have any effect.

**Comment by rootfs** [comment]
ok, I buy your containerized kubelet point :)
In addition to the code change, please also update readme mentioning multipath.conf requisite.

**Comment by foxish** [comment]
@dims We still haven't transitioned to the CNCF CLA and require the Google CLA at this time. The transition is likely to happen during this week or the next.

**Comment by dims** [comment]
@foxish Ack. thanks!

**Comment by fabiand** [comment]
@rootfs I've added an README to cover the multipath configuration which applies to both (or at least) iSCSI and FC.

I actually wonder if multipath is really working for iSCSI today ..

**Comment by rootfs** [comment]
@fabiand 
```
FAILED   hack/make-rules/../../hack/verify-munge-docs.sh	16s
```

**Comment by rootfs** [comment]
@fabiand I don't have an iscsi multipath to verify either.

**Comment by fabiand** [comment]
@rootfs fhe failure seems to be unrelated. Can it be retriggered?

**Comment by rootfs** [comment]
have you run hack/update-munge-docs.sh

**Comment by fabiand** [comment]
Ah - No. I'll check that, thanks for the pointer.

**Comment by fabiand** [comment]
Yes - I'll get to it again!

**Comment by jsafrane** [comment]
... and nothing happened, interesting. Anyway, our Jenkins complains:

```
I1116 01:13:01.990] Some md files are missing ga-beacon analytics link:
I1116 01:13:01.991] /go/src/k8s.io/kubernetes/pkg/volume/README.md
I1116 01:13:01.991] Docs need munging. Please run hack/update-munge-docs.sh
I1116 01:13:01.992] FAILED   hack/make-rules/../../hack/verify-munge-docs.sh	16s
```

Please run hack/update-munge-docs.sh and force-push this branch so it can be merged, thanks.

**Comment by jsafrane** [comment]
@k8s-bot verify test this
@k8s-bot bazel test this
@k8s-bot kops aws e2e test this

These were not started or logs are not available ("Unable to load build details from gs://kubernetes-jenkins/pr-logs/pull/36698/pull-kubernetes-verify/4824")

**Comment by jsafrane** [comment]
Fabian has signed CLA and google-bot knows about it, as it can be seen e.g. in #41408. There is something wrong in this PR, I'm labeling it as cla-yes manually.

**Comment by fabiand** [comment]
I've rebased the patch and force-pushed it to the branch.
I was not able to run /hacks/update-munge-docs.sh` and running `hack/update-all.sh -v -a` lead to a gazillion changes, so that I did not include those in the PR.

Let's see what the automation comes up now with.

**Comment by jsafrane** [comment]
@k8s-bot unit test this
flake #34953

**Comment by jsafrane** [comment]
@k8s-bot gci gce e2e test this

#41902

**Comment by jsafrane** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by fabiand** [comment]
@jsafrane anything I need to provide? or just the usual test cycles?

**Comment by jsafrane** [comment]
@fabiand, Kubernetes is frozen due to 1.6 release, merge queue should open later today. This PR is in the right state, prepared for merging, no action is needed.

**Pull request merged**
