### PR TITLE
[StructuredAuthn] Ensure empty fields of user object are accessible by CEL

### PR DESCRIPTION
**Pull request by aramase**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Make the `user` variable accessible to CEL expressions containing empty values omitted by default serialization.

#### Does this PR introduce a user-facing change?

Covered by release note on earlier feature merge in 1.29

```release-note
NONE
```

/assign @enj
/sig auth
/triage accepted

### CODE REVIEW

**Comment by aramase** [comment]
Test failure without the fix

```
/home/anramase/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc_test.go:315: authenticate token: oidc: error evaluating user info validation rule: expression 'user.username == ""' resulted in error: no such key: username

/home/anramase/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc_test.go:315: authenticate token: oidc: error evaluating user info validation rule: expression 'user.uid == ""' resulted in error: no such key: uid

/home/anramase/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc_test.go:315: authenticate token: oidc: error evaluating user info validation rule: expression '!('bar' in user.groups)' resulted in error: no such key: groups

/home/anramase/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/oidc/oidc_test.go:315: authenticate token: oidc: error evaluating user info validation rule: expression '!('bar' in user.extra)' resulted in error: no such key: extra
```

**Comment by enj** [comment]
/approve

@liggitt can you `/lgtm` if this covers the issue you saw in the authz code?

**Pull request merged**
