### PR TITLE
Fix typo on `cluster/centos/master/scripts/etcd.sh`

### PR DESCRIPTION
**Pull request by choldrim**
there is a repeated slash while creating `/usr/lib/systemd/system/etcd.service` on `cluster/centos/master/scripts/etcd.sh` file

``` shell
...
cat <<EOF >//usr/lib/systemd/system/etcd.service  # => here
[Unit]
Description=Etcd Server
After=network.target
...
```

Although just a little change, but less confusion.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30574)

### CODE REVIEW

**Comment by luxas** [comment]
LGTM

**Comment by choldrim** [comment]
@luxas hi, Is there any problem about this Github CI tests?

**Comment by luxas** [comment]
@k8s-bot test this please github issue: #IGNORE

**Comment by luxas** [comment]
@choldrim Probably only downloading flakes

**Comment by choldrim** [comment]
@luxas the robot was failed again :(

**Comment by luxas** [comment]
@k8s-bot test this please github issue: #IGNORE

**Comment by choldrim** [comment]
That is just a very small change, I think the k8s developers can fix it easily and quickly.

**Pull request closed without merging**
