### PR TITLE
chore: should use raw string () with regexp.MustCompile to avoid havi…

### PR DESCRIPTION
**Pull request by testwill**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
should use raw string (`...`) with regexp.MustCompile to avoid having to escape twice (S1007)

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
None

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

node e2e files are fine

**Comment by ardaguclu** [comment]
/lgtm
for kubectl change.

**Comment by bart0sh** [comment]
@testwill please rebase and let's try to move this PR forward, thanks.

**Pull request closed without merging**
