### PR TITLE
Automated cherry pick of #33616 #35566

### PR DESCRIPTION
**Pull request by jingxu97**
Cherry pick of #33616 #35566 on release-1.4.
#33616: Fix volume states out of sync problem after kubelet restarts
#35566: add IsNotMountPoint() to mount_unsupported.go

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35836)

### CODE REVIEW

**Comment by jingxu97** [comment]
@jessfraz PTAL, thank you!

**Comment by jessfraz** [comment]
thanks!

**Comment by jingxu97** [comment]
@rootfs, this cherrypick includes your fix #35566, could you PTAL and confirm?

**Comment by rootfs** [comment]
#35566 LGTM

**Comment by jessfraz** [comment]
tests are green manually merging so we get the release out

**Pull request merged**
