### PR TITLE
2 minor fixes for kubeadm upgrade

### LINKED ISSUE #1136: kubeadm upgrade has a few minor problems
during a kubeadm upgrade from 1.11.3 to 1.12.0-rc.1 I encountered some strange behavior.

1. I used an external etcd, it let me know I had to manually update etcd which is 👍, however it still prepulled the etcd image.
2. Typo. `[upgrade/staticpods] This might take a minute or longer depending on the component/version gap (timeout 5m0s` No final `)`.

### PR DESCRIPTION
**Pull request by bart0sh**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

- Skipped prepulling etcd image if external etcd is used.
- Fixed missing round bracket

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#1136

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
/lgtm
thanks @bart0sh

**Review by fabriziopandini — APPROVED** [review]
@bart0sh good catch!
/approve
/lgtm

**Review by fabriziopandini — APPROVED** [review]
@bart0sh good catch!
/approve
/lgtm

**Review by fabriziopandini — APPROVED** [review]
@bart0sh good catch!
/approve
/lgtm

**Pull request merged**
