### PR TITLE
Modify ha diagrams to remove podmaster

### LINKED ISSUE #25406: Kubernetes HA documentation has image with podmaster
The current HA documentation shows an image with the podmaster still in place. I believe this is no longer used, so have done a quick edit to remove it. Github doesn't like the svg filetype, happy to send it on by email in that case

### PR DESCRIPTION
**Pull request by captainblerko**
fixes #25406

[Analytics]()

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-oncall you are going to have to manually merge this one since it touches old docs

**Comment by mikedanese** [comment]
@k8s-bot unit test this please, issue: #IGNORE

**Comment by goltermann** [comment]
@k8s-oncall - can you manually merge this after looking over the details?  everything is green but the do-not-merge label is present

**Comment by lavalamp** [comment]
I thought the whole point of this behavior was to prevent people from making changes to these docs, so they'd update them in the docs repo?

**Comment by lavalamp** [comment]
Yes, I double checked w/ @johndmulhausen. These images should be deleted here, and you should send this pr to the docs repo.

**Comment by mikedanese** [comment]
@lavalamp thanks for the info. @captainblerko can you move this pr to https://github.com/kubernetes/kubernetes.github.io?

**Pull request closed without merging**
