### PR TITLE
Add vikaschoudhary16 to the approvers in device manager

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
**What this PR does / why we need it**:
I would like to volunteer in the device manager as an approver. I have been working dedicatedly in the device manager since very beginning and, i think, made considerable contributions in getting it graduated to beta. 

**List of my activities in Device Manager**:
Authored:
- Node-level Checkpointing manager: Migrate dockershim and device plugin manager checkpointing #56040
- Call Dial in blocking mode #58319
- Invoke preStart RPC call before container start, if desired by plugin #58282
- Remove redundant sleep from ReRegistration unit test case #57610
- Fix a race in the endpoint.go #57591
- Add unit test for endpoint allocate #58941
- Fix device manager to scan resources.Requests #57278
- Device plugin stub: Take device health dynamically #57267
- Modify endpoint unregister handling #60296
- Handle Unhealthy devices #57266
- Unit test device plugin handler Start() #55698
- Refactor TestPodContainerDeviceAllocation for extensiblity/readability #55692
- Use file store utility for device plugin checkpointing #55382

Authored but not merged yet:
- Add probe based mechanism and Use it in Device Manager #58755
- Add New Resource API proposal #782
- https://docs.google.com/document/d/1dtHpGY-gPe9sY7zzMGnm8Ywo09zJfNH-E1KEALFV39s/edit#heading=h.7fe6spexljh6
- [[PUBLIC] Network Devices Support Proposal](https://docs.google.com/document/d/1TpYqgmJQOctm1oexQRo0cGNb9oyk0vozhmhr6myY99M/edit#heading=h.9skhj6jwr20r)

Reviewed PRs:
- Fixes the races around devicemanager Allocate() and endpoint deletion. #60856
- avoid race condition in device manager startup/shutdown: close socket #59861
- Fix all GPUs exposed when the limit of "nvidia.com/gpu" == 0 #59698
- avoid race condition in device manager and plugin startup/shutdown: wait for goroutines #60034
- Create pkg/kubelet/apis/deviceplugin/v1beta1 directory. #59588
- devicemanager testing: dynamically choose tmp dir #59489
- Add annotations to the device plugin API #58172
- [DevicePlugin] Rework pod-devices module #56398
- Refactor Device Plugin Registration #52616
- Stub Device Plugin refactor: 600x speedup #52612
- Update device plugin document to show NVIDIA device plugin #6721
- Support for resource quota on extended resources #57302
- Rename package deviceplugin => devicemanager. #56870
- Re-uses device plugin resources allocated to init containers. #56818
- Prohibit requesting device plugin resources in init-containers #56659
- Add a paragraph on device plugin upgrade in device plugin doc. #6501
- Update device plugin proposal doc to match 1.9 device plugin changes. #1447
- Extends deviceplugin to gracefully handle full device plugin lifecycle. #55088
- Add stub device plugin for conformance e2e test #54792
- Implementation of the Device Plugin Manager #50482
- Deviceplugin jiayingz #51209
- Device Plugin Design Proposal #695

Issues that I involved with:
- Support device plugin advertised timeouts #58866
- Device plugin checkpointing should be more reliable #54088
- Devices are not re-used when paired with init containers #56022
- Device Plugin Race #56026
- Device manager only considers extended resource limits when allocating devices. #57276
- deviceplugin unit test failure #58281
- [DevicePlugin] Should we retry when ListAndWatch gRPC call failed? #58372
- [DevicePlugin] Change the multiple Allocate call to a single Pod Admit call #59370
- [DevicePlugin] Support Unlimited Resources #59380
- Kubelet device plugin APIs: Deallocate #59110
- Kubelet device plugin to pass additional information about Pods to Allocate call #59109

**Release note**:

```release-note
None
```
/cc @jiayingz @vishh @derekwaynecarr @dchen1107 @ConnorDoyle @RenaudWasTaken @jeremyeder

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
i support this.

changes to the device plugin API should still require broad consensus across sig-node community.

**Comment by ConnorDoyle** [comment]
+1

**Comment by derekwaynecarr** [comment]
In the interest of transparency towards the process, do you mind enumerating the PRs you worked on in the area?  Those PRs may include items authored, items reviewed, design docs, etc?  I know you are dedicated to this area, but It would be good to enumerate them more crisply here for record.  Thanks!

**Comment by derekwaynecarr** [comment]
https://github.com/kubernetes/community/blob/master/community-membership.md

Please note the current approver requirements for project.

If you can enumerate your sustained contribution (even if it’s past and into future) it would help make a final decision on this.   

All this to say, I support you getting this role eventually, but we need to make sure the contribution is sustained, etc.

**Comment by vikaschoudhary16** [comment]
@derekwaynecarr PTAL!

**Comment by derekwaynecarr** [comment]
@vikaschoudhary16 thank you for recording the details.

From the membership guidelines:
>Reviewer of the codebase for at least 3 months

It appears you were added as a reviewer ~Dec, so this appears satisfied.

>Primary reviewer for at least 10 substantial PRs to the codebase

We can review what was enumerated, but I encourage you to update this list through the present release, and also broaden it to include areas beyond `/pkg/kubelet/cm` generally.  I know you are working on additional topic areas in 1.11 release, so I have no concerns here broadly.

>Reviewed or merged at least 30 PRs to the codebase

The merge count is < 30, so growing that number in present release is helpful.

>Nominated by a subproject owner
With no objections from other subproject owners

Enumerating the details here is helpful, and it will let the existing owners of `pkg/kubelet` and `pkg/kubelet/cm` provide a review.  Thank you!

>Done through PR to update the top-level OWNERS file
this is the appropriate level in the repo so, this is fine.

**Pull request closed without merging**
