### PR TITLE
e2e:Use a more specific image url of nginx

### PR DESCRIPTION
**Pull request by linyouchong**
**What this PR does / why we need it**:
Use a more specific image url of nginx

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
NONE

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
We should probably drop both of the imagename consts from types.go and make sure everything is using the images from the e2e image registry

**Comment by linyouchong** [comment]
@BenTheElder Thanks,
I have update the commit.
I think we should not drop the `IginxImageName` const, for some file still using it
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apps/deployment.go#L319
```
	deployment, err = framework.UpdateDeploymentWithRetries(c, ns, deploymentName, func(update *apps.Deployment) {
		update.Spec.Template.Spec.Containers[0].Name = NginxImageName
		update.Spec.Template.Spec.Containers[0].Image = NginxImage
	})
```

**Comment by BenTheElder** [comment]
OK sounds reasonable. We are in code freeze for the 1.12 release until the 20th, this PR mighf need fo wait after that point. https://github.com/kubernetes/sig-release/tree/master/releases/release-1.12#code-freeze

cc @spiffxp, I do remember trying to get some similar PRs in during code slush, perhaps we want this one before the release as well?

Thanks for fixing these 🙂

**Comment by linyouchong** [comment]
@BenTheElder could you approve it now? Thanks!

**Comment by BenTheElder** [comment]
I'm not really an approver in Kubernetes/Kubernetes so unfortunately not.

Per the bot
/assign @nikhiljindal

**Pull request closed without merging**
