### PR TITLE
Fix failing scheduler benchmark

### PR DESCRIPTION
**Pull request by misterikkit**
**What this PR does / why we need it**:

We accidentally removed the Recorder object from integration test
scheduler in https://github.com/kubernetes/kubernetes/pull/71875. This
caused segfaults when running scheduler benchmarks.

    make test-integration WHAT="./test/integration/scheduler_perf" KUBE_TEST_ARGS="-run xx -bench ."

This change adds the recorder back.

**What type of PR is this?**
/kind failing-test
/sig scheduling

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by bsalamat — COMMENTED** [review]
/lgtm
/approve

Please update bazel files.

**Comment by wgliang** [comment]
wow, duplicate with #72967

**Comment by yastij** [comment]
/lgtm

from events POV.

**Comment by misterikkit** [comment]
> wow, duplicate with #72967

I failed to notice that one! I should be merged instead of this one.
/close

**Pull request closed without merging**
