### PR TITLE
CHANGELOG: fix punctuation errors

### PR DESCRIPTION
**Pull request by wangyx1992**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR fixes some punctuation errors in CHANGELOG.

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/approve

**Review by soniasingla — APPROVED** [review]
Thanks for the PR! 🎉

/lgtm

**Pull request merged**
