### PR TITLE
Automated cherry pick of #114602: Removed the reverted changes from Changelogv1.26.md

### PR DESCRIPTION
**Pull request by Shubham82**
Cherry-pick of #114602 on release-1.26.

#114602: Removed the reverted changes from Changelogv1.26.md

For details on the cherry-pick process, see the [cherry-pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

#### Does this PR introduce a user-facing change?

```
None
```

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @jeremyrickard @justaugustus
PTAL!

**Comment by Shubham82** [comment]
Fixed the Link for API compatibility and Kubelet Device Manager API Versions

**Comment by Shubham82** [comment]
/cc kubernetes/release-managers

PTAL!

**Review by xmudrii — APPROVED** [review]
We're past the cherry-pick deadline, but this PR is only modifying the changelog, so it's safe to get it merged.
/lgtm
/approve

**Pull request merged**
