### PR TITLE
Enable pod container resources tests on Windows

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
PR https://github.com/kubernetes/kubernetes/pull/112599 merged so it seems that we can now enable the tests on Windows.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
cc @claudiubelu  
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by bart0sh** [comment]
/triage accepted
/priority important-longterm
/lgtm

/assign @mrunalp @dchen1107 @derekwaynecarr 
for a final approval

**Comment by dims** [comment]
/approve

(happy to enable these tests, no logic change other than allowing windows nodes)

**Comment by pacoxu** [comment]
/hold 
as https://github.com/kubernetes/kubernetes/issues/123127 will fail `pull-kubernetes-node-e2e-containerd` which is required CI.

**Pull request merged**
