### PR TITLE
Create ComponentStatus test

### LINKED ISSUE #86087: Write listCoreV1ComponentStatuses and readCoreV1ComponentStatus Mock Test for Conformance - +2 coverage
This issue proposes the writing of a new test for the `listCoreV1ComponentStatus` and `readCoreV1ComponentStatus` API endpoints with the intention of promoting it to Conformance. This issue contains a very masic **mock** test in order to start the conversation about what a good e2e test would look like for this endpoint. The code below is verified to be hitting the intended endpoint, show as per the queries in APIsnoop's live view of the cluster's audit logs.

## Our Kubectl Apply

```shell
kubectl apply -f "https://raw.githubusercontent.com/cncf/apisnoop/master/deployment/k8s/raiinbow.yaml" --namespace=kube-system
```

# Identify a Feature Using APISnoop

According to this query we are lacking in ComponentStatus tests

```sql-mode
SELECT
  operation_id,
  k8s_action,
  path,
  description
  FROM untested_stable_core_endpoints
 WHERE operation_id like '%Component%'
 ORDER BY operation_id desc
 LIMIT 25
       ;
```

```sql-mode
       operation_id        | k8s_action |               path               |             description              
---------------------------+------------+----------------------------------+--------------------------------------
 readCoreV1ComponentStatus | get        | /api/v1/componentstatuses/{name} | read the specified ComponentStatus   
 listCoreV1ComponentStatus | list       | /api/v1/componentstatuses        | list objects of kind ComponentStatus 
(2 rows)                                                                                                          
```

You can iterate over a query until you have a set of endpoints you'd like to write a test for, usually by adjusting the columns you view or by extending the where clause to filter more specifically.

We selected **readCoreV1ComponentStatus** and **readCoreV1ComponentStatus** to write a test for.

## Example Test in Go

```shell
go get -v -u k8s.io/apimachinery/pkg/apis/meta/v1
go get -v -u k8s.io/client-go/kubernetes
go get -v -u k8s.io/client-go/tools/clientcmd
```

```go
// uses the current context in kubeconfig                                                     
kubeconfig := flag.String("kubeconfig",                                                       
  fmt.Sprintf("%v/%v/%v", os.Getenv("HOME"), ".kube", "config"),                              
  "(optional) absolute path to the kubeconfig file")                                          
flag.Parse()                                                                                  
config, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)                                
if err != nil {                                                                               
  fmt.Println(err)                                                                            
}                                                                                             
// make our work easier to find in the audit_event queries                                    
config.UserAgent = "live-test-writing"                                                        
// creates the clientset                                                                      
clientset, _ := kubernetes.NewForConfig(config)                                               
                                                                                              
// get list of components                                                                     
csList, _ := clientset.CoreV1().ComponentStatuses().List(v1.ListOptions{})                    
                                                                                              
healthyCount := 0                                                                             
for _, csItem := range csList.Items {                                                         
  // access the API to list pods                                                              
  cs, _ := clientset.CoreV1().ComponentStatuses().Get(csItem.ObjectMeta.Name, v1.GetOptions{})
                                                                                              
  for _, condition := range cs.Conditions {                                                   
    if condition.Type == "Healthy" && condition.Status == "True" {                            
      healthyCount ++                                                                         
    }                                                                                         
  }                                                                                           
}                                                                                             
                                                                                              
if healthyCount != len(csList.Items) {                                                        
  fmt.Println("[status] components are NOT healthy")                                          
  return                                                                                      
}                                                                                             
                                                                                              
fmt.Println("[status] components are healthy")                                                

```

# Verify with APISnoop

As you run your test functions against the cluster, apisnoop logs all endpoints hit and puts it in the db with the bucket 'apisnoop' and the job 'live'. We use this to build a set of queries that show what endpoints are hit by your test (or other function), and what the projected change in coverage would be if this test was merged into the e2e testing suite.

```sql-mode
select * from endpoints_hit_by_new_test where useragent like 'live%';
```

```sql-mode
     useragent     |       operation_id        | hit_by_ete | hit_by_new_test 
-------------------+---------------------------+------------+-----------------
 live-test-writing | listCoreV1ComponentStatus |          0 |               1 
 live-test-writing | readCoreV1ComponentStatus |          0 |               3 
(2 rows)                                                                      
```

NOTE: for the projected change in coverage, your test functions must be configured with a useragent that starts with `live-test`, otherwise endpoints hit by that test won't be counted as part of new coverage.

```sql-mode
select * from projected_change_in_coverage;
```

```sql-mode
   category    | total_endpoints | old_coverage | new_coverage | change_in_number 
---------------+-----------------+--------------+--------------+------------------
 test_coverage |             438 |          183 |          185 |                2 
(1 row)                                                                           
```

#
/sig testing
/sig architecture
/area conformance

### LINKED ISSUE #86089: Write listCoreV1ServiceForAllNamespaces Mock Test for Conformance - +1 coverage
This issue proposes the writing of a new test for the `listCoreV1ServiceForAllNamespaces` API endpoint with the intention of promoting it to Conformance. This issue contains a very basic **mock** test in order to start the conversation about what a good e2e test would look like for this endpoint. The code below is verified to be hitting the intended endpoint, show as per the queries in APIsnoop's live view of the cluster's audit logs.

## Our Kubectl Apply

```shell
kubectl apply -f "https://raw.githubusercontent.com/cncf/apisnoop/master/deployment/k8s/raiinbow.yaml" --namespace=kube-system
```

# Identify a Feature Using APISnoop

There are no tests listing services, see the following:

```sql-mode
SELECT
  operation_id, path, description
  FROM untested_stable_core_endpoints
  where operation_id like 'list%'
  and path like '/api/v1/services' ;
```

```sql-mode
           operation_id            |       path       |              description              
-----------------------------------|------------------|---------------------------------------
 listCoreV1ServiceForAllNamespaces | /api/v1/services | list or watch objects of kind Service
(1 row)

```

# API documentation
- [godocs - ServiceInterface](https://godoc.org/k8s.io/client-go/kubernetes/typed/core/v1#ServiceInterface)
- [typed/core/v1/service.go#L45](https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/service.go#L45)

# My Mock Test

```shell
go get -v -u k8s.io/apimachinery/pkg/apis/meta/v1
go get -v -u k8s.io/client-go/kubernetes
go get -v -u k8s.io/client-go/tools/clientcmd
```

This mock test uses client-go's functions and hits the endpoints.

```go
// uses the current context in kubeconfig
kubeconfig := flag.String("kubeconfig",
  fmt.Sprintf("%v/%v/%v", os.Getenv("HOME"), ".kube", "config"),
  "(optional) absolute path to the kubeconfig file")
flag.Parse()
config, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)
if err != nil {
  fmt.Println(err)
}
// make our work easier to find in the audit_event queries
config.UserAgent = "live-test-pod-count"
// creates the clientset
clientset, _ := kubernetes.NewForConfig(config)
// access the API to list services in all namespaces
svcs, _ := clientset.CoreV1().Services("").List(v1.ListOptions{})

foundSvc := false
for _, svc := range svcs.Items {
  if svc.ObjectMeta.Name == "kubernetes" {
    foundSvc = true
  }
}

if foundSvc == false {
  fmt.Println("[status] could NOT find service in service list in all namespaces")
  return
}

fmt.Println("[status] found service in list of services in all namespaces")
```

# Verify with APISnoop

This shows the endpoints hit by my approach:

```sql-mode
select * from endpoints_hit_by_new_test where useragent like 'live%';
```

```sql-mode
      useragent      |           operation_id            | hit_by_ete | hit_by_new_test 
---------------------|-----------------------------------|------------|-----------------
 live-test-pod-count | listCoreV1ServiceForAllNamespaces |          0 |               1
(1 row)

```

```sql-mode
select * from projected_change_in_coverage;
```

```sql-mode
   category    | total_endpoints | old_coverage | new_coverage | change_in_number 
---------------|-----------------|--------------|--------------|------------------
 test_coverage |             438 |          183 |          184 |                1
(1 row)

```

#
/sig testing
/sig architecture
/area conformance

### PR DESCRIPTION
**Pull request by BobyMCbobs**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR adds a test for the following untested endpoints:
- listCoreV1ComponentStatus
- readCoreV1ComponentStatus

**Which issue(s) this PR fixes**:
Fixes #86087

**Special notes for your reviewer**:
Adds +2 endpoint test coverage (good for conformance)

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
NONE
```

/sig testing

### CODE REVIEW

**Comment by johnSchnake** [comment]
The `pull-kubernetes-verify` job has a few issues; all look easy to fix.

**Comment by johnSchnake** [comment]
I think you're linking to the wrong issue; you link to the request for a test regarding`listCoreV1ServiceForAllNamespaces`

**Review by johnSchnake — COMMENTED** [review]
I'm not really sure I think this tests the appropriate behavior.

 - This test would pass if the endpoint was a noop and returned no items.
 - This test would fail if the endpoint was working correctly and a component was not healthy

It seems like we would need to either (1) know the status of the components from some other method and compare that they match or (2) ignore the data and only consider the data type/format. E.g. are the expected fields set with valid values.

Thoughts?

**Comment by BobyMCbobs** [comment]
> I think you're linking to the wrong issue; you link to the request for a test regarding`listCoreV1ServiceForAllNamespaces`; you want #86087

My mistake, I've corrected the endpoints which the test covers in the description.

**Comment by BobyMCbobs** [comment]
> I'm not really sure I think this tests the appropriate behavior.
> 
> * This test would pass if the endpoint was a noop and returned no items.
> * This test would fail if the endpoint was working correctly and a component was not healthy

From what I gather, _some_ Components are modular (like `etcd`).
I think that this test is good for just testing the health of any available Components.

> 
> It seems like we would need to either (1) know the status of the components from some other method and compare that they match or (2) ignore the data and only consider the data type/format. E.g. are the expected fields set with valid values.

I'm not sure how with e2e tests that we can verify the data since we can only talk to through the API.

> 
> Thoughts?

I've adding another test in https://github.com/kubernetes/kubernetes/pull/86860/commits/e4dc6badbbe35e760d64b5c474dc27ef8eeb4e12 for ensuring that the Components `scheduler` and `controller-manager` are available.

**Comment by spiffxp** [comment]
>It seems like we would need to either (1) know the status of the components from some other method and compare that they match or (2) ignore the data and only consider the data type/format. E.g. are the expected fields set with valid values.

I'm inclined to agree with @johnSchnake here, I'm not clear whether ComponentStatus (and the set of components reporting it, and their health) is intended to be standard across all kubernetes clusters.  If we want to exercise this as an endpoint I think we should take the approach described in (2) and generate/validate synthetic data

Can someone from @kubernetes/sig-cluster-lifecycle or @kubernetes/wg-component-standard comment as to how standard/expected ComponentStatus is across different kubernetes cluster providers?

**Comment by soltysh** [comment]
/hold 
based on previous doubts

**Comment by spiffxp** [comment]
/close
Discussed during conformance meeting today. We don't want to move forward for this test, I've opened kubernetes/community#4404 to clarify the requirements

**Pull request closed without merging**
