### PR TITLE
e2e: Enable persistent volume test

### PR DESCRIPTION
**Pull request by jsafrane**
The test is already there and all packages should be already available on all test machines.

It tests:
- binding
- using bound claim in a pod
- recycling NFS volume

(we should see shortly if all nfs packages are really installed as Jenkins tests it...)

### CODE REVIEW

**Comment by jsafrane** [comment]
cc: @kubernetes/sig-storage

**Comment by jsafrane** [comment]
e2e tests passed -> all NFS packages are installed by default and the test can be enabled.

**Comment by ixdy** [comment]
LGTM, though I'm not sure what you mean by "packages should be there" - does this test have any external dependencies beyond the containers named?

**Comment by jsafrane** [comment]
It requires rpm/deb package with `/usr/sbin/mount.nfs` installed on all nodes. I see it installed in salt scripts in https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/base.sls#L11, but one is never sure with salt.

**Pull request merged**
