### PR TITLE
kubelet: enforce an initial empty SET PodUpdate

### PR DESCRIPTION
**Pull request by sttts**
In PodConfigNotificationIncremental PodConfig mode, when no pods are available
for a source, the Merge function correctly concluded that neither ADD, UPDATE nor
REMOVE updates are to be sent to the kubelet. But as a consequence the kubelet will
not mark that source as seen.

This is usually not a problem for the apiserver source. But it is a problem for
an empty "file" source, e.g. by passing an empty directory to the kubelet for
static pods. Then the file source will never be seen and the kubelet will stay
in its special not-all-source-seen mode.

Fixes https://github.com/mesosphere/kubernetes-mesos/issues/557

### CODE REVIEW

**Comment by sttts** [comment]
Of course the unit tests don't expect the change. Before fixing those, I would like to discuss whether this is the right approach.

FYI, in the Mesos context we always have a file source for static pods. But the directory is usually empty. It would not be too hard to not create the file source if there are no static pods. So we can work around this issue.

**Comment by smarterclayton** [comment]
That change makes sense.  I can't think of a scenario where this would affect the apiserver source (since we always error and don't return anything).  Definitely need to be very careful about the tests and review of the change to ensure we don't clobber the source accidentally, but this makes sense to me.

**Comment by sttts** [comment]
@smarterclayton in fact the tests are green now with the small change in the second patch.

**Comment by sttts** [comment]
I will add a unit test to test the additional behavior.

**Pull request merged**
