### PR TITLE
Automated cherry pick of #18583

### PR DESCRIPTION
**Pull request by jsravn**
Cherry pick of #18583 on release-1.1.

Ref #18530

### CODE REVIEW

**Comment by deads2k** [comment]
@k8s-bot ok to test

**Comment by deads2k** [comment]
lgtm.  Please squash commits

**Comment by deads2k** [comment]
@smarterclayton Looks like my bot request wasn't good enough.  You mind doing it?

**Comment by smarterclayton** [comment]
ok to test

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by roberthbailey** [comment]
This seems like it warrants a release note when it makes it into a patch release.

**Pull request merged**
