### PR TITLE
 fix the image for node performance tests - model expected tensorflow…

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
… version <1.9

#### What type of PR is this?

/kind failing-test
/sig node
/area test

#### What this PR does / why we need it:

Fix the image for node performance tests

#### Which issue(s) this PR fixes:
Towards: #109295 (will need to update image later)

#### Special notes for your reviewer:
Just lock tensorflow version for now. Switching to more actual model may be done later

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
@dims would this PR be OK while in test freeze? This image is only used in node performance tests

(also will need another PR when image will be actually built)

**Review by endocrimes — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
/approve
/lgtm

won't land until master reopens.

**Pull request merged**
