### PR TITLE
Used Pods interface for binding.

### PR DESCRIPTION
**Pull request by k82cn**
Used Pods interface for binding in scheduler.

### CODE REVIEW

**Comment by davidopp** [comment]
@ravigadde can you take a look at this?

**Comment by davidopp** [comment]
Sorry, I was confused, I thought this was related to scheduler extender bind thing.

**Comment by k82cn** [comment]
ping :).

**Comment by davidopp** [comment]
@wojtek-t could you take a look at this?

**Comment by timothysc** [comment]
@k82cn sorry for the delay, feel free to poke me on slack.  I've been stuck in multiple proposals the last few days.

**Comment by k82cn** [comment]
sure :).

**Pull request merged**
