### PR TITLE
Fix completions for --namespace to override kubectl flags

### PR DESCRIPTION
**Pull request by superbrothers**
**What this PR does / why we need it**:
This PR fixes completions for --namespace to override kubectl flags. Due to not using __kubectl_parse_get, __kubectl_get_namespaces doesn't support to override kubectl flags.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by spiffxp** [comment]
/ok-to-test
@kubernetes/sig-cli-pr-reviews PTAL

**Comment by sttts** [comment]
Have you tested this with zsh as well?

Looks good otherwise.

**Comment by superbrothers** [comment]
@sttts Yes, I have tested both bash and zsh.

**Comment by sttts** [comment]
Double checked with zsh. Lgtm.

**Comment by sttts** [comment]
@pwittrock approved?

**Pull request merged**
