### PR TITLE
OS/IaaS/Cfg support matrix.

### PR DESCRIPTION
**Pull request by erictune**

### CODE REVIEW

**Comment by zmerlynn** [comment]
In #3912 I actually just outright proposed local and ovirt for deletion. Maybe let's do it?

**Comment by zmerlynn** [comment]
Actually, I think what also needs to happen is that regardless, `ubuntu`, `local` and `ovirt` need to move elsewhere, because right now they're basically assets to getting started guides rather than code.

**Comment by erictune** [comment]
Don't disagree with anything you said.  Wanted to get this up to show you what I was talking about in terms of format.

**Comment by zmerlynn** [comment]
This is actually pretty sweet, and is a handy way to link to the getting started guides as well. We can do the other cleanup in another PR. I'll finish reviewing in the morning.

**Comment by pires** [comment]
Great idea!

**Comment by smreed** [comment]
Thanks for the mention @erictune but it's been quite a while since I've tried getting k8s up and running in Rackspace. I might come back around to it but we've no plans here to get serious about that in the short term. :/

**Comment by erictune** [comment]
Okay, @smreed, I will remove your name from the matrix.  Happy to add back if you come back to it.

**Comment by erictune** [comment]
@jeffmendoza would you like to be listed as the maintainer for Azure support?

**Comment by derekwaynecarr** [comment]
Shouldn't fedora vagrant link to https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/vagrant.md

**Comment by derekwaynecarr** [comment]
Sorry.  We need an entry to https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/vagrant.md that says it uses salt stack and is supported at Project head

**Comment by jeffmendoza** [comment]
@erictune Yes, please.

**Comment by zmerlynn** [comment]
I think for GCE and GKE we should just say "tested at latest" so that we're not constantly chasing, though I suppose the question is whether the "getting started guide" is correct, versus the provider. (GKE could actually just link to the release notes page for the Notes field, which would indicate the last release we've pushed.)

Otherwise I think it looks good with me. I can argue the finer points in #3912 later, this initial table is already pretty nice. If you agree with the above, fix it up appropriately and squash.

@pires, @kelseyhightower, @pietern, @justinsb, any final objections? Otherwise it'll take a whole PR to reverse.

**Comment by zmerlynn** [comment]
(And, sorry, I should say that the comments from @derekwaynecarr and @jeffmendoza need to be addressed, and he did volunteer. Woo!)

**Comment by pires** [comment]
@zmerlynn I do use GCE & Vagrant. AWS changes were made a little in the dark and had someone validate them because I don't have an account there.

**Comment by justinsb** [comment]
I'm going to start AWS (non-CoreOS) with Ubuntu, not Debian.  (Maybe I'll add Debian Jessie when it is released because I'm seeing this issue with the kernel in the last Ubuntu LTS, but that's just a thought right now: https://github.com/docker/docker/issues/4036 )

**Comment by erictune** [comment]
addressed @derekwaynecarr and @jeffmendoza  comments.  I'm going to remove @pires from being mentioned for AWS in the hopes that a new owner will step up, but will continue to welcome his contributions in that area where possible.

**Comment by erictune** [comment]
I'm going to be out for the next week, so I suggest merging and then making any other needed changes in another PR.

**Comment by erictune** [comment]
Forgot about your "just say "tested at latest" comment @zmerlynn 
Please merge and add that later.

**Comment by zmerlynn** [comment]
LGTM.

**Pull request merged**
