### PR TITLE
Add simple heuristic to select AccessMode for mounting

### PR DESCRIPTION
**Pull request by nixpanic**
**What type of PR is this?**

/sig storage
/kind cleanup

**What this PR does / why we need it**:

Include some simple heuristic to decide which AccessMode to use for the
CSI NodeStage request.

1. default to ReadWriteOnce
2. if the PVC Spec has AccessModes, use the 1st as default
3. for ReadOnly volumes, use ReadOnlyMany if it is in the PCV Spec
4. for non-ReadOnly volumes, use the first non-ReadOnlyMany mode from
   the PVC Spec

**Which issue(s) this PR fixes**:

This should solve issues when an initial Pod populates a PVC in
ReadWriteOnce, and exists. Follow-up Pods with the volume in ReadOnly
mode will use ReadOnlyMany to allow running the Pods on different nodes.

**Special notes for your reviewer**:

This was listed as a `TODO` with pointer to @vladimirvivien

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nixpanic** [comment]
/remove-lifecycle rotten

Going to rebase and address CI issues later today.

**Comment by msau42** [comment]
/assign @chrishenzie 
It'll be interesting to see if this works with gce pd, which also requires attach to be readonly.

**Comment by chrishenzie** [comment]
/remove-lifecycle rotten

@humblec Just checking if this feature is implemented or something else. I remember you did some work on dynamic use of ReadOnly / access modes

**Pull request closed without merging**
