### PR TITLE
Update github.com/spf13/cobra to HEAD.

### LINKED ISSUE #4142: kubectl help should display command-specific flags separate from global flags
It's visually daunting to parse the available flags in kubectl usage strings. Example:
```
Usage:
  kubectl rollingupdate <old-controller-name> -f <new-controller.json> [flags]

 Available Flags:
      --alsologtostderr=false: log to standard error as well as files
      --api-version="": The API version to use when talking to the server
  -a, --auth-path="": Path to the auth info file. If missing, prompt the user. Only used if using https.
      --certificate-authority="": Path to a cert. file for the certificate authority.
      --client-certificate="": Path to a client key file for TLS.
      --client-key="": Path to a client key file for TLS.
      --cluster="": The name of the kubeconfig cluster to use
      --context="": The name of the kubeconfig context to use
  -f, --filename="": Filename or URL to file to use to create the new controller
  -h, --help=false: help for rollingupdate
      --insecure-skip-tls-verify=false: If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure.
      --kubeconfig="": Path to the kubeconfig file to use for CLI requests.
      --log_backtrace_at=:0: when logging hits line file:N, emit a stack trace
      --log_dir=: If non-empty, write log files in this directory
      --log_flush_frequency=5s: Maximum number of seconds between log flushes
      --logtostderr=true: log to standard error instead of files
      --match-server-version=false: Require server version to match client version
      --namespace="": If present, the namespace scope for this CLI request.
      --poll-interval="3s": Time delay between polling controller status after update. Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
  -s, --server="": The address of the Kubernetes API server
      --stderrthreshold=2: logs at or above this threshold go to stderr
      --timeout="5m0s": Max time to wait for a controller to update before giving up. Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
      --token="": Bearer token for authentication to the API server.
      --update-period="1m0s": Time to wait between updating pods. Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
      --user="": The name of the kubeconfig user to use
      --v=0: log level for V logs
      --validate=false: If true, use a schema to validate the input before sending it
      --vmodule=: comma-separated list of pattern=N settings for file-filtered logging
```
Which flags are actually relevant to my command? The usage string helps a bit, but if I want to know the defaults, I have to squint at the wall of text looking for the flag I care about amidst a host of common flags. We should replace Cobra's default usage text with one that looks like

```
Usage:
  kubectl rollingupdate <old-controller-name> -f <new-controller.json> [flags]

Flags:
  -f, --filename="": Filename or URL to file to use to create the new controller
      --poll-interval="3s": Time delay between polling controller status after update. Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
      --timeout="5m0s": Max time to wait for a controller to update before giving up. Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
      --update-period="1m0s": Time to wait between updating pods. Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
  -h, --help=false: help for rollingupdate

General Flags:
      --alsologtostderr=false: log to standard error as well as files
      --api-version="": The API version to use when talking to the server
  -a, --auth-path="": Path to the auth info file. If missing, prompt the user. Only used if using https.
      --certificate-authority="": Path to a cert. file for the certificate authority.
      --client-certificate="": Path to a client key file for TLS.
      --client-key="": Path to a client key file for TLS.
      --cluster="": The name of the kubeconfig cluster to use
      --context="": The name of the kubeconfig context to use
      --insecure-skip-tls-verify=false: If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure.
      --kubeconfig="": Path to the kubeconfig file to use for CLI requests.
      --log_backtrace_at=:0: when logging hits line file:N, emit a stack trace
      --log_dir=: If non-empty, write log files in this directory
      --log_flush_frequency=5s: Maximum number of seconds between log flushes
      --logtostderr=true: log to standard error instead of files
      --match-server-version=false: Require server version to match client version
      --namespace="": If present, the namespace scope for this CLI request.
  -s, --server="": The address of the Kubernetes API server
      --stderrthreshold=2: logs at or above this threshold go to stderr
      --token="": Bearer token for authentication to the API server.
      --user="": The name of the kubeconfig user to use
      --v=0: log level for V logs
      --validate=false: If true, use a schema to validate the input before sending it
      --vmodule=: comma-separated list of pattern=N settings for file-filtered logging
```
Flags specific to the command at the top, inherited/general flags after. Bonus points to upstream it to https://github.com/spf13/cobra .

cc @mbforbes, @MikeJeffrey

### PR DESCRIPTION
**Pull request by vmarmol**
Fixes #4142.

### CODE REVIEW

**Comment by a-robinson** [comment]
LGTM, but are the CI failures legitimate?

**Comment by vmarmol** [comment]
Yep, fixing those now. The .mds don't match the new flag breakdown output.

**Comment by thockin** [comment]
Why?

**Comment by vmarmol** [comment]
@a-robinson all builds are passing.

@thockin for #4142

**Comment by thockin** [comment]
What I meant was, such a PR deserves a "why" in the commit comments.

**Comment by vmarmol** [comment]
The commit says "Fix #4142" which I thought was enough of a why :) Went ahead and added a  deeper why to the commit though.

**Pull request merged**
