### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by porridge**
**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by shyamjvs** [comment]
@porridge Could you also bump the CPU constraint for l7-lb-controller in the test?
We've notified sig-networking about the issue under https://github.com/kubernetes/kubernetes/issues/54135 - let's not lose more runs due to this failure.

@wojtek-t - as he may have some opinions.

**Comment by porridge** [comment]
Sent https://github.com/kubernetes/kubernetes/pull/56285 to bump CPU.

**Pull request merged**
