### PR TITLE
Fix some shellcheck failures of cluster/*.sh

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fix some shellcheck failures of cluster/*.sh

**Which issue(s) this PR fixes**:

Ref #72956

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/priority important-soon

### CODE REVIEW

**Comment by k-toyoda-pi** [comment]
Is it not necessary to remove fixed files from hack/.shellcheck_failuers?

**Comment by SataQiu** [comment]
@k-toyoda-pi 
Not yet, because this PR only fixes some common problems of these scripts.
Additional PRs are required for further cleanup.

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
