### PR TITLE
gitattributes: all files LF line endings

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/sig windows
/kind failing-test

/priority important-soon

#### What this PR does / why we need it:

Always check-out / check-in json and yaml files with LF line endings.

This will also solve a few unit tests on Windows, in which the expectation is that marshalled objects match the the content written in a few yaml or json files. On Windows, these files may be checked out with CRLF line endings, which causes the tests to fail.

#### Which issue(s) this PR fixes:

Related: https://github.com/kubernetes/kubernetes/issues/51540

#### Special notes for your reviewer:

Original proposal: https://github.com/kubernetes/kubernetes/pull/110263#discussion_r1004952930

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
do we need to make sure that all committed line endings are newline-only, and that LF doesn't get committed, now that git is not fixing up line endings?

**Comment by marosset** [comment]
> do we need to make sure that all committed line endings are newline-only, and that LF doesn't get committed, now that git is not fixing up line endings?

I think we just want to make sure CRLF endings don't get committed - LF is OK.

According to this https://git-scm.com/docs/gitattributes#Documentation/gitattributes.txt-Unset-1 unsetting the `text` attribute just instructs git to never change line endings. If we want to enforce CRLF endings don't get checked in then I think we should set `*.go text=auto eol=lf` since that should ensure consistency when (new) files get checked into the repo

https://git-scm.com/docs/gitattributes#_end_of_line_conversion
> If you want to ensure that text files that any contributor introduces to the repository have their line endings normalized, you can set the text attribute to "auto" for all files.

**Comment by liggitt** [comment]
> If we want to enforce CRLF endings don't get checked in then I think we should set `*.go text=auto eol=lf` since that should ensure consistency when (new) files get checked into the repo

the specific issue unit tests were hitting on windows was that yaml and json files were getting checked out with CRLF endings, I think

**Comment by marosset** [comment]
> > If we want to enforce CRLF endings don't get checked in then I think we should set `*.go text=auto eol=lf` since that should ensure consistency when (new) files get checked into the repo
> 
> the specific issue unit tests were hitting on windows was that yaml and json files were getting checked out with CRLF endings, I think

the `eol=lf` should help with that

https://git-scm.com/docs/gitattributes#Documentation/gitattributes.txt-Settostringvaluelf
> Set to string value "lf"
This setting forces Git to normalize line endings to LF on checkin and prevents conversion to CRLF when the file is checked out.

**Comment by liggitt** [comment]
this change lgtm... is the green `pull-ci-kubernetes-unit-windows` a sign that this worked?

**Comment by claudiubelu** [comment]
> this change lgtm... is the green `pull-ci-kubernetes-unit-windows` a sign that this solved the issue for running fixture tests on windows?

Soo, this PR does indeed fix the issue, but the unit tests in question failed in the job. But that's because of how git works. Basically, the unit tests job clones the kubernetes/kubernetes repository, then it fetches the PR and checks it out. Now, git apparently will **not** retroactively modify / re-checkout files that are not modified, even though the ``.gitattributes`` file changed; only on new check-outs will it take the attributes set in ``.gitattributes`` into consideration. This is why the tests still failed, they're still checked-out with CRLF line endings.

I've ran some of those unit tests locally on a Windows machine, reproducing the steps mentioned above: clone, fetch PR, checkout PR, run tests, see it fail, remove & re-check-out testdata yaml files used in tests, see it pass. You can see the logs here: https://paste.ubuntu.com/p/rn4xfwQZ7m/

As for why the job is green, that will have to be addressed later. We're currently fixing all the unit tests for Windows, and this solves a huge portion of the remaining unit tests.

**Comment by liggitt** [comment]
I'm wondering if there's an incantation that would handle all files git would normally treat as text this way

https://stackoverflow.com/a/42135910 looks promising, but I'm not sure how concerned we need to be about use of git versions prior to 2016

**Comment by claudiubelu** [comment]
> I'm wondering if there's an incantation that would handle all files git would normally treat as text this way, not just json and yaml
> 
> https://stackoverflow.com/a/42135910 looks promising, but I'm not sure how concerned we need to be about use of git versions prior to 2016

I wanted to have ``* text=auto eol=lf`` instead, but I thought I should be a bit more conservative. Will change the PR to have this instead.

As for git 2.10, it has been released more than 6 years ago, I think that's long enough. The fix mentioned there says that ``* text=auto eol=lf`` used to behave like ``* text eol=lf``, with the difference being that ``text=auto`` means that git automatically detects if a file is a text file (in which case it does the EOL conversions), while for ``text`` does the EOL conversions for all files, which might be problematic for binary files, if we have any in-tree.

**Comment by claudiubelu** [comment]
> I'm wondering if there's an incantation that would handle all files git would normally treat as text this way, not just json and yaml
> 
> https://stackoverflow.com/a/42135910 looks promising, but I'm not sure how concerned we need to be about use of git versions prior to 2016

I have updated the git attributes. Can you take another look, please?

**Comment by marosset** [comment]
> > I'm wondering if there's an incantation that would handle all files git would normally treat as text this way, not just json and yaml
> > https://stackoverflow.com/a/42135910 looks promising, but I'm not sure how concerned we need to be about use of git versions prior to 2016
> 
> I have updated the git attributes. Can you take another look, please?

I don't think we need to be concerned about git versions prior to 2016. 

The new changes LGTM

**Comment by liggitt** [comment]
/lgtm

/assign @dims
for sig-architecture-approvers root approval of non-dependency file per https://github.com/kubernetes/kubernetes/blob/master/OWNERS#L10

**Review by marosset — APPROVED** [review]
/lgtm

**Comment by claudiubelu** [comment]
The following unit tests now pass on Windows: https://testgrid.k8s.io/sig-windows-signal#windows-unit-master

```
k8s.io/kubernetes/pkg/controller/garbagecollector.TestMarshalDOT
k8s.io/kubernetes/pkg/controller/garbagecollector.TestMarshalDOT/empty.dot
k8s.io/kubernetes/pkg/controller/garbagecollector.TestMarshalDOT/escaping.dot
k8s.io/kubernetes/pkg/controller/garbagecollector.TestMarshalDOT/simple.dot
k8s.io/kubernetes/pkg/kubelet/apis/config/scheme.TestDefaultsYAML
k8s.io/kubernetes/pkg/kubelet/apis/config/scheme.TestDefaultsYAML/CredentialProviderConfig_default_v1
k8s.io/kubernetes/pkg/kubelet/apis/config/scheme.TestDefaultsYAML/CredentialProviderConfig_default_v1beta1
k8s.io/kubernetes/pkg/kubelet/apis/config/scheme.TestDefaultsYAML/KubeletConfiguration_default_v1beta1
k8s.io/kubernetes/pkg/kubelet/apis/config/scheme.TestDefaultsYAML/SerializedNodeConfigSource_default_v1beta1
k8s.io/kubernetes/pkg/kubelet/apis/config/scheme.TestRoundTripYAML
k8s.io/kubernetes/pkg/kubelet/apis/config/scheme.TestRoundTripYAML/CredentialProviderConfig_v1Tov1_default
k8s.io/kubernetes/pkg/kubelet/apis/config/scheme.TestRoundTripYAML/CredentialProviderConfig_v1Tov1beta1_default
k8s.io/kubernetes/pkg/kubelet/apis/config/scheme.TestRoundTripYAML/CredentialProviderConfig_v1beta1Tov1_default
k8s.io/kubernetes/pkg/kubelet/apis/config/scheme.TestRoundTripYAML/CredentialProviderConfig_v1beta1Tov1beta1_default
k8s.io/kubernetes/pkg/kubelet/apis/config/scheme.TestRoundTripYAML/KubeletConfiguration_v1beta1Tov1beta1_default
k8s.io/kubernetes/pkg/kubelet/apis/config/scheme.TestRoundTripYAML/SerializedNodeConfigSource_v1beta1Tov1beta1_default
```

**Pull request merged**
