### PR TITLE
[Scheduler] Fix flaky test on multi profiles waitingPods

### LINKED ISSUE #123621: Flake: TestFrameworkHandler_IterateOverWaitingPods/pods_with_different_profiles_are_waiting_on_permit_stage [46c1b1ee...]
##### Error text:
```
=== RUN   TestFrameworkHandler_IterateOverWaitingPods/pods_with_different_profiles_are_waiting_on_permit_stage
    framework.go:381: I0229 10:48:13.714983] the scheduler starts to work with those plugins Plugins={"PreEnqueue":{"Enabled":null,"Disabled":null},"QueueSort":{"Enabled":[{"Name":"PrioritySort","Weight":0}],"Disabled":null},"PreFilter":{"Enabled":null,"Disabled":null},"Filter":{"Enabled":null,"Disabled":null},"PostFilter":{"Enabled":null,"Disabled":null},"PreScore":{"Enabled":null,"Disabled":null},"Score":{"Enabled":null,"Disabled":null},"Reserve":{"Enabled":null,"Disabled":null},"Permit":{"Enabled":[{"Name":"fakePermit","Weight":0}],"Disabled":null},"PreBind":{"Enabled":null,"Disabled":null},"Bind":{"Enabled":[{"Name":"DefaultBinder","Weight":0}],"Disabled":null},"PostBind":{"Enabled":null,"Disabled":null},"MultiPoint":{"Enabled":null,"Disabled":null}}
    framework.go:381: I0229 10:48:13.715309] the scheduler starts to work with those plugins Plugins={"PreEnqueue":{"Enabled":null,"Disabled":null},"QueueSort":{"Enabled":[{"Name":"PrioritySort","Weight":0}],"Disabled":null},"PreFilter":{"Enabled":null,"Disabled":null},"Filter":{"Enabled":null,"Disabled":null},"PostFilter":{"Enabled":null,"Disabled":null},"PreScore":{"Enabled":null,"Disabled":null},"Score":{"Enabled":null,"Disabled":null},"Reserve":{"Enabled":null,"Disabled":null},"Permit":{"Enabled":[{"Name":"fakePermit","Weight":0}],"Disabled":null},"PreBind":{"Enabled":null,"Disabled":null},"Bind":{"Enabled":[{"Name":"DefaultBinder","Weight":0}],"Disabled":null},"PostBind":{"Enabled":null,"Disabled":null},"MultiPoint":{"Enabled":null,"Disabled":null}}
    framework.go:381: I0229 10:48:13.715630] the scheduler starts to work with those plugins Plugins={"PreEnqueue":{"Enabled":null,"Disabled":null},"QueueSort":{"Enabled":[{"Name":"PrioritySort","Weight":0}],"Disabled":null},"PreFilter":{"Enabled":null,"Disabled":null},"Filter":{"Enabled":null,"Disabled":null},"PostFilter":{"Enabled":null,"Disabled":null},"PreScore":{"Enabled":null,"Disabled":null},"Score":{"Enabled":null,"Disabled":null},"Reserve":{"Enabled":null,"Disabled":null},"Permit":{"Enabled":[{"Name":"fakePermit","Weight":0}],"Disabled":null},"PreBind":{"Enabled":null,"Disabled":null},"Bind":{"Enabled":[{"Name":"DefaultBinder","Weight":0}],"Disabled":null},"PostBind":{"Enabled":null,"Disabled":null},"MultiPoint":{"Enabled":null,"Disabled":null}}
    eventhandlers.go:75: I0229 10:48:13.717736] Add event for node node="node1"
    node_tree.go:65: I0229 10:48:13.717988] Added node in listed group to NodeTree node="node1" zone=""
    eventhandlers.go:75: I0229 10:48:13.718196] Add event for node node="node2"
    node_tree.go:65: I0229 10:48:13.718385] Added node in listed group to NodeTree node="node2" zone=""
    eventhandlers.go:75: I0229 10:48:13.718588] Add event for node node="node3"
    node_tree.go:65: I0229 10:48:13.718793] Added node in listed group to NodeTree node="node3" zone=""
    eventhandlers.go:128: I0229 10:48:13.718980] Add event for unscheduled pod pod="pod1"
    scheduling_queue.go:595: I0229 10:48:13.719138] Pod moved to an internal scheduling queue pod="pod1" event="PodAdd" queue="Active"
    schedule_one.go:84: I0229 10:48:13.719250] About to try and schedule pod pod="pod1"
    schedule_one.go:97: I0229 10:48:13.719321] Attempting to schedule pod pod="pod1"
    framework.go:1475: I0229 10:48:13.719623] Permit: One or more plugins asked to wait and no plugin rejected pod node="node1" pod="pod1"
    framework.go:1500: I0229 10:48:13.719889] Pod waiting on permit pod="pod1"
    eventhandlers.go:128: I0229 10:48:13.720049] Add event for unscheduled pod pod="pod2"
    scheduling_queue.go:595: I0229 10:48:13.720184] Pod moved to an internal scheduling queue pod="pod2" event="PodAdd" queue="Active"
    schedule_one.go:84: I0229 10:48:13.720358] About to try and schedule pod pod="pod2"
    schedule_one.go:97: I0229 10:48:13.720451] Attempting to schedule pod pod="pod2"
    framework.go:1475: I0229 10:48:13.720791] Permit: One or more plugins asked to wait and no plugin rejected pod node="node2" pod="pod2"
    framework.go:1500: I0229 10:48:13.721010] Pod waiting on permit pod="pod2"
    eventhandlers.go:128: I0229 10:48:13.721439] Add event for unscheduled pod pod="pod3"
    scheduling_queue.go:595: I0229 10:48:13.721732] Pod moved to an internal scheduling queue pod="pod3" event="PodAdd" queue="Active"
    eventhandlers.go:128: I0229 10:48:13.721917] Add event for unscheduled pod pod="pod4"
    schedule_one.go:84: I0229 10:48:13.722078] About to try and schedule pod pod="pod3"
    schedule_one.go:97: I0229 10:48:13.722236] Attempting to schedule pod pod="pod3"
    scheduling_queue.go:595: I0229 10:48:13.722449] Pod moved to an internal scheduling queue pod="pod4" event="PodAdd" queue="Active"
    framework.go:1475: I0229 10:48:13.722729] Permit: One or more plugins asked to wait and no plugin rejected pod node="node3" pod="pod3"
    framework.go:1500: I0229 10:48:13.723032] Pod waiting on permit pod="pod3"
    schedule_one.go:84: I0229 10:48:13.723270] About to try and schedule pod pod="pod4"
    schedule_one.go:97: I0229 10:48:13.723413] Attempting to schedule pod pod="pod4"
    scheduler_test.go:1044: Unexpected waitingPods in scheduler profile test-scheduler-profile-1, expect: []string{"pod1", "pod2", "pod3", "pod4"}, got: []string{"pod1", "pod2", "pod3"}
    --- FAIL: TestFrameworkHandler_IterateOverWaitingPods/pods_with_different_profiles_are_waiting_on_permit_stage (0.01s)
```

#### Recent failures:
[3/1/2024, 7:14:16 AM pr:pull-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/123614/pull-kubernetes-unit/1763538031354056704)
[2/29/2024, 5:28:43 AM pr:pull-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/123555/pull-kubernetes-unit/1763149087500144640)
[2/28/2024, 12:17:55 PM pr:pull-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/123562/pull-kubernetes-unit/1762889666685571072)

/kind failing-test

/kind flake

/sig scheduling

### PR DESCRIPTION
**Pull request by kerthcet**
#### What type of PR is this?
/kind flake
/kind cleanup
/sig scheduling

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/123621

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by NoicFank** [comment]
There is still a chance of receiving the leaked error as following on my mac (even the test is succeed)

```
    --- PASS: TestFrameworkHandler_IterateOverWaitingPods/pods_with_different_profiles_are_waiting_on_permit_stage (0.10s)
E0305 15:13:34.760997   76753 framework.go:1500] "WARNING: test kept at least one goroutine running after test completion" logger="TestFrameworkHandler_IterateOverWaitingPods/pods_with_different_profiles_are_waiting_on_permit_stage leaked goroutine" pod="pod4" callstack=<
	goroutine 359 [running]:
	k8s.io/klog/v2/internal/dbg.Stacks(0x0)
		/Users/archelurong/.gvm/pkgsets/go1.20/global/pkg/mod/k8s.io/klog/v2@v2.120.1/internal/dbg/dbg.go:35 +0x8c
	k8s.io/klog/v2/ktesting.tlogger.fallbackLogger({0x140006b4480, {0x0, 0x0}, {0x140004a0880, 0x2, 0x2}})
		/Users/archelurong/.gvm/pkgsets/go1.20/global/pkg/mod/k8s.io/klog/v2@v2.120.1/ktesting/testinglogger.go:253 +0x1b4
	k8s.io/klog/v2/ktesting.tlogger.Info({0x140006b4480, {0x0, 0x0}, {0x140004a0880, 0x2, 0x2}}, 0x4, {0x1040a5591, 0x15}, {0x140007b9d60, ...})
		/Users/archelurong/.gvm/pkgsets/go1.20/global/pkg/mod/k8s.io/klog/v2@v2.120.1/ktesting/testinglogger.go:277 +0x11c
	github.com/go-logr/logr.Logger.Info({{0x104a7b8a8?, 0x14000694360?}, 0x0?}, {0x1040a5591, 0x15}, {0x140007b9d60, 0x2, 0x2})
		/Users/archelurong/.gvm/pkgsets/go1.20/global/pkg/mod/github.com/go-logr/logr@v1.4.1/logr.go:280 +0xe8
	k8s.io/kubernetes/pkg/scheduler/framework/runtime.(*frameworkImpl).WaitOnPermit(0x14000292fc8, {0x104a75f20, 0x140007ac280}, 0x14000406d88)
		/Users/archelurong/go/src/kubernetes/pkg/scheduler/framework/runtime/framework.go:1500 +0x1a8
	k8s.io/kubernetes/pkg/scheduler.(*Scheduler).bindingCycle(0x140005a38c0, {0x104a75f20, 0x140007ac280}, 0x14000992180, {0x104a9a9c0, 0x14000292fc8}, {{0x104089a73, 0x5}, 0x1, 0x1, ...}, ...)
		/Users/archelurong/go/src/kubernetes/pkg/scheduler/schedule_one.go:278 +0xa8
	k8s.io/kubernetes/pkg/scheduler.(*Scheduler).scheduleOne.func1()
		/Users/archelurong/go/src/kubernetes/pkg/scheduler/schedule_one.go:125 +0x194
	created by k8s.io/kubernetes/pkg/scheduler.(*Scheduler).scheduleOne in goroutine 270
		/Users/archelurong/go/src/kubernetes/pkg/scheduler/schedule_one.go:118 +0x620
 >
PASS
```

Pod will wait in the binding cycle from its own goroutines, is it possible that these goroutines may leak?
So at the end of the testing, I allowed these pods to pass the permit stage (using the code below), but I also got new errors
```
			fwk1, ok := scheduler.Profiles[testSchedulerProfile1]
			if !ok {
				t.Fatalf("unable get profile")
			}
			fwk1.IterateOverWaitingPods(func(pod framework.WaitingPod) {
				pod.Allow(fakePermit)
			})

			wg.Add(waitSchedulingPodNumber)
			stopFn2, err := eventBroadcaster.StartEventWatcher(func(obj runtime.Object) {
				e, ok := obj.(*eventsv1.Event)
				if !ok || (e.Reason != "Scheduled") {
					return
				}
				wg.Done()
			})
			if err != nil {
				t.Fatal(err)
			}
			defer stopFn2()

			wg.Wait()
```

new leak error as following....

```
=== RUN   TestFrameworkHandler_IterateOverWaitingPods/pods_with_different_profiles_are_waiting_on_permit_stage
E0305 15:10:07.033132   74647 scheduling_queue.go:890] "WARNING: test kept at least one goroutine running after test completion" logger="TestFrameworkHandler_IterateOverWaitingPods/pods_with_same_profile_are_waiting_on_permit_stage leaked goroutine" callstack=<
	goroutine 290 [running]:
	k8s.io/klog/v2/internal/dbg.Stacks(0x0)
		/Users/archelurong/.gvm/pkgsets/go1.20/global/pkg/mod/k8s.io/klog/v2@v2.120.1/internal/dbg/dbg.go:35 +0x8c
	k8s.io/klog/v2/ktesting.tlogger.fallbackLogger({0x140007947e0, {0x0, 0x0}, {0x0, 0x0, 0x0}})
		/Users/archelurong/.gvm/pkgsets/go1.20/global/pkg/mod/k8s.io/klog/v2@v2.120.1/ktesting/testinglogger.go:253 +0x1b4
	k8s.io/klog/v2/ktesting.tlogger.Info({0x140007947e0, {0x0, 0x0}, {0x0, 0x0, 0x0}}, 0x2, {0x103ecea58, 0x1a}, {0x0, ...})
		/Users/archelurong/.gvm/pkgsets/go1.20/global/pkg/mod/k8s.io/klog/v2@v2.120.1/ktesting/testinglogger.go:277 +0x11c
	github.com/go-logr/logr.Logger.Info({{0x10489b8a8?, 0x140002eab70?}, 0x14000b219d8?}, {0x103ecea58, 0x1a}, {0x0, 0x0, 0x0})
		/Users/archelurong/.gvm/pkgsets/go1.20/global/pkg/mod/github.com/go-logr/logr@v1.4.1/logr.go:280 +0xe8
	k8s.io/kubernetes/pkg/scheduler/internal/queue.(*PriorityQueue).Pop(0x14000674000, {{0x10489b8a8?, 0x140002eab70?}, 0x140003da050?})
		/Users/archelurong/go/src/kubernetes/pkg/scheduler/internal/queue/scheduling_queue.go:890 +0xec
	k8s.io/kubernetes/pkg/scheduler.(*Scheduler).scheduleOne(0x140006d6180, {0x104895f20, 0x140003da050})
		/Users/archelurong/go/src/kubernetes/pkg/scheduler/schedule_one.go:68 +0x5c
	k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
		/Users/archelurong/go/src/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:259 +0x2c
	k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x14000b21ec8?)
		/Users/archelurong/go/src/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:226 +0x40
	k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x14000b21f68, {0x104870a48, 0x14000a98420}, 0x1, 0x14000176900)
		/Users/archelurong/go/src/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:227 +0x90
	k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x14000a8c768, 0x0, 0x0, 0x1, 0x14000176900)
		/Users/archelurong/go/src/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:204 +0x80
	k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext({0x104895f20, 0x140003da050}, 0x1400061c1f0, 0x0, 0x0, 0x1)
		/Users/archelurong/go/src/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:259 +0x80
	k8s.io/apimachinery/pkg/util/wait.UntilWithContext(...)
		/Users/archelurong/go/src/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/backoff.go:170
	created by k8s.io/kubernetes/pkg/scheduler.(*Scheduler).Run in goroutine 218
		/Users/archelurong/go/src/kubernetes/pkg/scheduler/scheduler.go:418 +0x104
 >
```

**Comment by kerthcet** [comment]
Yes, but I think that's another problem let's track with another issue. And it's a warning wouldn't block the PR merge.

**Comment by NoicFank** [comment]
> Yes, but I think that's another problem, most caused by the test not the feature itself. let's track with another issue. And it's a warning wouldn't block the PR merge.

/lgtm

ok, thanks for the fix ~

**Pull request merged**
