### PR TITLE
Change the users of IsQualifiedName to ValidateQualifiedName

### LINKED ISSUE #99828: Change the users of IsQualifiedName to ValidateQualifiedName
After #98277 got merged, we have added new helper function `ValidateQualifiedName` here: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L126. 

It will be good for us to use this simpler helper function to replace previous `IsQualifiedName` function.

/good-first-issue

### PR DESCRIPTION
**Pull request by mowangdk**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #99828 

#### Does this PR introduce a user-facing change?

None
```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mowangdk** [comment]
@XudongLiuHarold ptal thx~

**Comment by XudongLiuHarold** [comment]
> @XudongLiuHarold ptal thx~

Hi @mowangdk  looks good to me, but since `1.21` code freeze is tomorrow, I guess the community members are quite busy now, may need to wait some time for their review.

**Review by XudongLiuHarold — COMMENTED** [review]
BTW, have you ever run test cases locally to make sure they can pass?

**Comment by mowangdk** [comment]
@XudongLiuHarold  please take a look again?

**Comment by XudongLiuHarold** [comment]
> @XudongLiuHarold please take a look again?

Sorry I am not a member of community. Could you ask them review your PR on slack channel?

**Comment by mowangdk** [comment]
> > @XudongLiuHarold please take a look again?
> 
> Sorry I am not a member of community. Could you ask them review your PR on slack channel?

ok~

**Comment by mowangdk** [comment]
@piosz @justinsb  ptal~ thx~

**Pull request closed without merging**
