### PR TITLE
[GCE] Removed duplicate CIDR

### PR DESCRIPTION
**Pull request by nicksardo**
**What this PR does / why we need it**:
Removes a duplicate CIDR in the list of LB source CIDRs.
https://cloud.google.com/compute/docs/load-balancing/network/ and https://cloud.google.com/compute/docs/load-balancing/http/ both list `35.191.0.0/16`.  Only one is needed.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by bowei — APPROVED** [review]
/lgtm

**Comment by nicksardo** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
