### PR TITLE
kubelet logs update source in the sync loop

### PR DESCRIPTION
**Pull request by yujuhong**
This improves the clarity/debuggability.

### CODE REVIEW

**Comment by yujuhong** [comment]
Related to #15171

**Comment by yujuhong** [comment]
@k8s-bot ok to test

**Comment by timstclair** [comment]
LGTM, but 2 questions:

- Do we have any guidelines around log levels? It seems pretty arbitrary which we use where.
- Why use `%q` over `%v`? (or even `%s`?)

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/logging.md

On Oct 6, 2015, at 6:14 PM, Tim St. Clair <notifications@github.com> wrote:

LGTM, but 2 questions:

   - Do we have any guidelines around log levels? It seems pretty arbitrary
   which we use where.
   - Why use %q over %v? (or even %s?)

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/15174#issuecomment-146017761>
.

**Comment by timstclair** [comment]
@smarterclayton Thanks!

**Comment by yujuhong** [comment]
> Why use %q over %v? (or even %s?)

If the string is empty, it would be seen as `""`, instead of nothing.

**Comment by timstclair** [comment]
Got it, thanks.

**Comment by yujuhong** [comment]
Trivial rebase. Carry forward the lgtm.

**Comment by yujuhong** [comment]
@k8s-bot test this

**Pull request merged**
