### PR TITLE
Fix the typos 'utilites'

### PR DESCRIPTION
**Pull request by mooncak**
**What this PR does / why we need it**:
Fix the typos 'utilites' in belowf files:

1. pkg/kubectl/cmd/taint/utils.go
2. pkg/util/taints/taints.go
3. test/e2e/storage/persistent_volumes-local.go

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mooncak** [comment]
@nikhita  could you help review this PR? tks

**Comment by nikhita** [comment]
@mooncak it's better to not create new PRs and make the changes all the necessary changes in the old one - https://github.com/kubernetes/kubernetes/pull/69783. It also provides more context/discussion to the change. :)

Anyway, but now that we are here, can you please squash the commits into a single commit? Thanks!

**Comment by mcrute** [comment]
Thanks for your contribution @mooncak, would you please squash all of your commits into a single one and update this PR.

/kind cleanup
/ok-to-test

**Comment by mooncak** [comment]
> Thanks for your contribution @mooncak, would you please squash all of your commits into a single one and update this PR.
> 
> /kind cleanup
> /ok-to-test

ok, I already squash the commits into this PR, tks.

**Comment by mcrute** [comment]
Can you please update the PR? The commits tab still shows 4 commits.

**Pull request closed without merging**
