### PR TITLE
dependencies: Update golang.org/x/net to v0.0.0-20211209124913-491a49abca63

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature
/area dependency release-eng release-eng/security security

#### What this PR does / why we need it:
Update golang.org/x/net to v0.0.0-20211209124913-491a49abca63

1. ./hack/pin-dependency.sh golang.org/x/net v0.0.0-20211209124913-491a49abca63
2. ./hack/update-vendor.sh
3. ./hack/update-internal-modules.sh

Part of https://github.com/kubernetes/release/issues/2349

/assign @liggitt @justaugustus
cc: @kubernetes/release-engineering

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Update golang.org/x/net to v0.0.0-20211209124913-491a49abca63
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cpanato** [comment]
@liggitt do we need to cherry pick that to release-1.23 branch?

**Comment by liggitt** [comment]
> @liggitt do we need to cherry pick that to release-1.23 branch? and maybe to the others as well

yes, to any branch using go 1.17 or 1.16, I would expect

**Pull request merged**
