### PR TITLE
Force using Go Modules in README.md

### PR DESCRIPTION
**Pull request by distortedsignal**
Going through this README file, I was very confused when
this failed to compile by using the commands provided. I
think this change makes the intent of the README clearer.

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
As a developer who was trying to work through the README
When I checkout the [repo here](https://github.com/kubernetes/sample-cli-plugin) into my GOPATH and run `go build cmd/kubectl-ns.go`
I want the build command to succeed and output the binary

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by distortedsignal** [comment]
Hey @k8s-ci-robot - I think I signed my CNCF CLA about 15 minutes ago - could you check if we could remove the `cncf-cla: no` flag now?

**Comment by distortedsignal** [comment]
I signed it

**Comment by distortedsignal** [comment]
Maybe now I signed it?

**Comment by distortedsignal** [comment]
Hey, I'm curious to know what I need to do to get feedback on this change.

**Comment by dims** [comment]
/ok-to-test

@distortedsignal apologies, you are doing everything right. the 1.15 release has bogged down reviewers a bit.

**Comment by dims** [comment]
/lgtm

@distortedsignal you will need an `/approve` from one of the assigned folks, feel free to ping them on slack in a few days on #sig-cli channel if you don't get a response.

**Comment by distortedsignal** [comment]
Thanks for the help @dims 😀

**Comment by distortedsignal** [comment]
thanks @liggitt!

**Pull request merged**
