### PR TITLE
Remove restriction that cluster-cidr be a class-b

### PR DESCRIPTION
**Pull request by cjcullen**
We shouldn't restrict the CLUSTER_IP_RANGE to a /16. Some may want smaller, some (cough--GKE--cough) may want a /14.

### CODE REVIEW

**Comment by zmerlynn** [comment]
I assume it psases e2es and all that jazz? LGTM

**Comment by cjcullen** [comment]
e2e's are still running...

**Comment by roberthbailey** [comment]
LGTM.

**Comment by mbforbes** [comment]
Ping when they're done and I'll merge—thanks!

**Comment by cjcullen** [comment]
e2es are green

**Pull request merged**
