### PR TITLE
Add self as local-up-cluster maintainer

### PR DESCRIPTION
**Pull request by smarterclayton**

### CODE REVIEW

**Comment by filbranden** [comment]
Can we please not open extra branches in the main GoogleCloudPlatform/kubernetes? When we `git fetch` we all end up getting these in all our local copies... Gets messy really quick.

**Comment by filbranden** [comment]
Having said it, LGTM.

**Comment by smarterclayton** [comment]
I was using the github UI from my phone, I thought it was in my fork.  Not intentional

**Comment by filbranden** [comment]
Unfortunately I find GitHub tends to make it easy to make these mistakes and there doesn't seem to be a good way to block (or make it harder) to create branches in the main git repo... Not sure what to suggest here, maybe we should have a bot monitoring it...

**Pull request merged**
