### PR TITLE
nits in manager.go

### PR DESCRIPTION
**Pull request by tianshapjq**
**What this PR does / why we need it**:
just found some nits in the manager.go

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
the file needs a more detailed cleanup.
but this is a good start. thanks.

**Comment by tianshapjq** [comment]
@RenaudWasTaken could lgtm again?

**Pull request merged**
