### PR TITLE
Reset flowcontrol metrics on a DELETE /metrics

### PR DESCRIPTION
**Pull request by tkashem**
**What type of PR is this?**
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Priority and Fairness metrics should reset when a a reset request is received (DELETE on /metrics endpoint)

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
None

```release-note
```

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm

**Review by yue9944882 — COMMENTED** [review]
/lgtm

**Pull request merged**
