### PR TITLE
Do not allow duplicate environment variable definitions

### LINKED ISSUE #58477: Duplicated environment variable in deployment disappears completely when fixed
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
For `deployment` resource:

A container has defined environment variable with name `x` that is duplicated (there are two env vars with the same name, the value is also the same).

When you fix the `deployment` resource descriptor so that environment variable with name `x` appears only once and push it with `kubectl apply`, deployment with no environment variable named `x` is created and therefore no environment variable named `x` is passed to replica set and pods.

**What you expected to happen**:
After fixing the `deployment`, environment variable with name `x` is defined in the `deployment` once .

**How to reproduce it (as minimally and precisely as possible)**:
1. create deployment with container with duplicated environment variable
1. `kubectl apply` it
1. fix deployment removing one of duplicated environment variable definitions
1. `kubectl apply` it
1. `kubectl get deployment/your-deployment -o yaml` prints deployment without 

**Anything else we need to know?**:
nope

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T20:00:41Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: private Kubernetes cluster
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by jennybuckley**
**What this PR does / why we need it**:
According to [this comment](https://github.com/kubernetes/kubernetes/issues/58477#issuecomment-358802050) by @liggitt, "the envvar name is supposed to be the unique key of items in the list" but our validation does not currently prevent this. This causes issues because name field is the patchMergeKey, so when someone tries to remove just one of two duplicate envvars, the both are actually removed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #58477

**Release note**:

```release-note
Fixes a bug which allowed Container.EnvVar to contain multiple EnvVars with the same name. Environment variables should not be defined multiple times.
```

### CODE REVIEW

**Comment by jennybuckley** [comment]
Have to fix some tests cases which used invalid container specs

**Comment by jennybuckley** [comment]
Does this need to be done in phases to preserve backward compatibility?

**Comment by liggitt** [comment]
> Does this need to be done in phases to preserve backward compatibility?

Yes. At the very least, we have to ensure existing data persisted in this state continues to be able to be updated and deleted.

**Comment by liggitt** [comment]
/hold

standard questions when we want to tighten validation:
* does it prevent a no-op update of existing persisted objects that would fail this new validation? (would block storage migration tasks)
* does it prevent deletion of existing persisted objects with finalizers that would fail this new validation? (update is required to remove finalizers to allow deletion)
* does it prevent controllers from updating status of existing persisted objects that would fail this new validation?

c.f. https://github.com/kubernetes/kubernetes/issues/59984

we could consider ratcheting validation:
* apply this tightened validation on create
* apply this tightened validation on update where the old object passed this validation (don't let a valid object become invalid)
* skip this tightened validation on update where the old object fails this validation

**Pull request closed without merging**
