### PR TITLE
Allow services which use same port, different protocol to use the same nodePort for both

### LINKED ISSUE #20092: NodePort allocation conflates TCP and UDP
Consider a service like

```yaml
apiVersion: v1
kind: Service
metadata:
  name: dns
spec:
  selector:
    …
  clusterIP: …
  type: NodePort
  ports:
  - name: dns
    port: 53
    nodePort: 30053
    protocol: UDP
  - name: dns-tcp
    port: 53
    nodePort: 30053
    protocol: TCP
```

The API refuses to accept this service, stating

> Service "dns" is invalid: spec.ports[1].nodePort: invalid value '30053', Details: provided port is already allocated

It works fine without `nodePort`. It works when using _different_ ports. The iptables rules installed (in `--proxy-mode=iptables` mode) are TCP/UDP specific.

I'm not sure if this is deliberate but not well documented, or a bug? I don't see a reason not to allow a UDP and TCP node port to have the same number.

### PR DESCRIPTION
**Pull request by adohe-zz**
fix #20092

@thockin @smarterclayton ptal.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30253)

### CODE REVIEW

**Comment by smarterclayton** [comment]
Test case?

**Comment by smarterclayton** [comment]
Interesting, looks like this overlaps with this PR?

**Comment by AdoHe** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by thockin** [comment]
I don't think this does what you want.  It only handles the case of a user explicitly setting NodePort.  I think it actually needs to IGNORE that case and instead handle the auto-allocated case.

---







*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30253#-:-KOmy6m5DhsUoRrrv0Jn:be0hepl)*

**Comment by AdoHe** [comment]
```
ingore user explicitly setting NodePort
```
means we won't allow this case? @thockin

**Comment by AdoHe** [comment]
Perhaps we should support both cases.

**Comment by thockin** [comment]
If the user provides 2 ports that are the same number, different protocol,
AND they provide a specific NodePort for each that is NOT the same number,
we have to respect their choice.

If they provide one such NodePort value and not the other, we should assume
they are the same value.

If they do not provide any NodePort values, assume the same number in this
case.

On Aug 10, 2016 4:25 AM, "TonyAdo" <notifications@github.com> wrote:

Perhaps we should support both cases.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/30253#issuecomment-238839019>,
or mute the thread

**Comment by AdoHe** [comment]
@thockin let's draw draw conclusion here:

1. same ports with provided NodePorts
```
apiVersion: v1
kind: Service
metadata:
  name: dns
spec:
  selector:
    …
  clusterIP: …
  type: NodePort
  ports:
  - name: dns
    port: 53
    nodePort: 30053
    protocol: UDP
  - name: dns-tcp
    port: 53
    nodePort: 30053
    protocol: TCP
```
Just try to reserve the first nodePort, since two nodePorts are the same.

2. same ports with different NodePorts
```
apiVersion: v1
kind: Service
metadata:
  name: dns
spec:
  selector:
    …
  clusterIP: …
  type: NodePort
  ports:
  - name: dns
    port: 53
    nodePort: 30053
    protocol: UDP
  - name: dns-tcp
    port: 53
    nodePort: 30055
    protocol: TCP
```
Have to respect user choice, try to reserve both nodePorts, if anyone failed, service creation failed.

3. same ports with just one provided NodePort
```
apiVersion: v1
kind: Service
metadata:
  name: dns
spec:
  selector:
    …
  clusterIP: …
  type: NodePort
  ports:
  - name: dns
    port: 53
    nodePort: 30053
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
```
Assume `NodePort` for dns-tcp is 30053 too.

4. same ports with no NodePort provided
```
apiVersion: v1
kind: Service
metadata:
  name: dns
spec:
  selector:
    …
  clusterIP: …
  type: NodePort
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
```
Try to allocate one NodePort from port range, and reuse it for dns-tcp.

WDYT?

**Comment by AdoHe** [comment]
Also for this case:
```
apiVersion: v1
kind: Service
metadata:
  name: dns
spec:
  selector:
    …
  clusterIP: …
  type: NodePort
  ports:
  - name: dns
    port: 53
    nodePort: 30053
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
```
I think we should set `NodePort` of dns-tcp to `30053` at the `PrepareForCreate` process.

**Comment by thockin** [comment]
I'm wary of setting it anywhere but the Create call - it just becomes hard
to keep track of.

I think you otherwise described a good set of test cases. :)

**Comment by AdoHe** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by AdoHe** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by AdoHe** [comment]
@thockin I just update this, please help review :)

**Comment by thockin** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/registry/service/rest.go, line 120 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30253#-KPZpcbRjU5BmnNzIPt8:-KPZpcbRjU5BmnNzIPt9:b-lx56ck) ([raw file](https://github.com/kubernetes/kubernetes/blob/1438eb1c982c3cece622ca07a91fbf7cdc36cbca/pkg/registry/service/rest.go#L120)):*
> ```Go
> 		allocatedNodePort := svcPortToNodePort[int(servicePort.Port)]
> 		if allocatedNodePort == 0 {
> 			np := findExistingNodePort(int(servicePort.Port), service.Spec.Ports)
> ```

comment: This will only scan forward in the service.Spec.Ports list because any matches before the current port would have been found in svcPortToNodePort.  This is really looking for any user-provided values.

---

*[pkg/registry/service/rest.go, line 421 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30253#-KPZolvysW1Vt9hGP_5U:-KPZolvysW1Vt9hGP_5V:b-nz1iea) ([raw file](https://github.com/kubernetes/kubernetes/blob/1438eb1c982c3cece622ca07a91fbf7cdc36cbca/pkg/registry/service/rest.go#L421)):*
> ```Go
> }
> 
> func findExistingNodePort(port int, servicePorts []api.ServicePort) int {
> ```

rename to `findRequestedNodePort` and comment this funxction VERY WELL

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30253)*

**Comment by AdoHe** [comment]
*[pkg/registry/service/rest.go, line 120 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30253#-KPZpcbRjU5BmnNzIPt8:-KP_P_kfDk2Sdb2V-CpG:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/1438eb1c982c3cece622ca07a91fbf7cdc36cbca/pkg/registry/service/rest.go#L120)):*
<details><summary><i>Previously, thockin (Tim Hockin) wrote…</i></summary>
> comment: This will only scan forward in the service.Spec.Ports list because any matches before the current port would have been found in svcPortToNodePort.  This is really looking for any user-provided values.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30253)*

**Comment by AdoHe** [comment]
*[pkg/registry/service/rest.go, line 421 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30253#-KPZolvysW1Vt9hGP_5U:-KP_Pas_QjiNsgbbb1vc:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/1438eb1c982c3cece622ca07a91fbf7cdc36cbca/pkg/registry/service/rest.go#L421)):*
<details><summary><i>Previously, thockin (Tim Hockin) wrote…</i></summary>
> rename to `findRequestedNodePort` and comment this funxction VERY WELL
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30253)*

**Comment by thockin** [comment]
+lgtm  +release-note -release-note-label-needed 

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30253#-:-KPoYilLLPMhqhfNjGpZ:b-8rnqy5)*

**Comment by AdoHe** [comment]
@thockin seems there is still one file left in unreviewed status, ptal.

**Comment by thockin** [comment]
not in my view...

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30253#-:-KPok3K4vIHcTQO7XlYA:bambify)*

**Comment by AdoHe** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30253)*

**Comment by thockin** [comment]
need a rebase ASAP or this will be ejected from 1.4

**Comment by AdoHe** [comment]
OK, will do it today.

**Comment by AdoHe** [comment]
@thockin rebased, but don't know why the reviewable still block.

**Comment by thockin** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30253)*

**Comment by homotopycolimit** [comment]
I am a little confused as to the current state of this issue.
I am running a service with both TCP and UDP:
```
spec:
  type: NodePort
  ports:
    - protocol: UDP
      port: 30420
      nodePort: 30420
    - protocol: TCP
      port: 30420
      nodePort: 30420
```
but kubectl describe service shows only UDP.
```
Type:			NodePort
IP:			10.0.13.152
Port:			<unset>	30420/UDP
NodePort:		<unset>	30420/UDP
Endpoints:		10.244.4.49:30420
```

 When I change the order then it shows only TCP.

(Server version 1.4.5)

**Comment by thockin** [comment]
This looks like using the wrong mergeKey, and indeed the code backs that up:

2508 type ServiceSpec struct {
2509     // The list of ports that are exposed by this service.
2510     // More info:
http://kubernetes.io/docs/user-guide/services#virtual-ips-and-service-proxies
2511     Ports []ServicePort `json:"ports,omitempty" patchStrategy:"merge"
patchMergeKey:"port" protobuf:"bytes,1,rep,name=ports"`

I'll open a new bug

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/issues/39188

**Comment by njuptlzf** [comment]
Can you fix the **_targerport_**？

apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.254.0.2
  ports:
  - name: dns
    port: 53
    targetPort: 1053
    protocol: UDP
  - name: dns-tcp
    port: 53
    targetPort: 1054
    protocol: TCP
  - name: metrics
    port: 9153
    protocol: TCP

Kubec apply -f 
[root@lzf03 coredns]# kubectl get svc -n kube-system kube-dns -oyaml
... ...
spec:
  clusterIP: 10.254.0.2
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 1053
  - name: metrics
    port: 9153
    protocol: TCP
    targetPort: 9153
  selector:
    k8s-app: kube-dns
... ...

**Pull request merged**
