### PR TITLE
Rename RBAC 'subject' to 'subjects'.

### PR DESCRIPTION
**Pull request by olegshaldybin**
Rename RBAC subject field

[Analytics]()

### CODE REVIEW

**Comment by olegshaldybin** [comment]
@ericchiang @erictune I am not 100% sure but it looked like a typo to me when I was trying it out. Since it's still alpha, I assume it's not too late to just rename?

**Comment by ericchiang** [comment]
Yes this is a typo. I was going to open the same issue. Seems you beat me to it :)

**Comment by liggitt** [comment]
@k8s-bot ok to test

**Comment by ericchiang** [comment]
@olegshaldybin you'll need to regenerate the swagger docs as well. e.g. run ./hack/update-all.sh

This will take a while and require sudoless access to the "docker" command.

**Comment by olegshaldybin** [comment]
Rebased and regenerated all.

**Comment by erictune** [comment]
LGTM, thanks!

**Comment by olegshaldybin** [comment]
Not sure why tests were failing, rebased just in case.

**Comment by olegshaldybin** [comment]
@erictune Can I get another LGTM if tests go green?

**Comment by erictune** [comment]
This is not going into 1.3-beta.  It may be able to go into 1.3.0, I will look into it.

**Pull request merged**
