### PR TITLE
For terminated pods volume should be detached

### PR DESCRIPTION
**Pull request by gnufied**
This is same as https://github.com/kubernetes/kubernetes/pull/45286 but it also changes implementation to not force detach volumes.

### CODE REVIEW

**Comment by fejta** [comment]
/unassign
/assign @davidopp @saad-ali 

Saad and David, will you assign someone from sig-scheduling and sig-storage to review?

**Comment by k82cn** [comment]
/assign @bsalamat @k82cn

bsalamat and me will review scheduling part firstly.

/cc @kubernetes/sig-scheduling-pr-reviews

**Comment by timothysc** [comment]
I actually thought there was a reason behind it not detaching

/cc @kubernetes/sig-storage-bugs

**Comment by gnufied** [comment]
I am closing this in favour of original PR.  Please follow along discussions on https://github.com/kubernetes/kubernetes/pull/45286

**Pull request closed without merging**
