### PR TITLE
Remove CRI `TimeoutError` type

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
The type is a lefover of dockershim and can be replaced by golang native error wrapping.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
Refers to https://github.com/kubernetes/kubernetes/pull/124634
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@kubernetes/sig-node-pr-reviews PTAL

**Review by endocrimes — COMMENTED** [review]
/lgtm

**Comment by saschagrunert** [comment]
@kubernetes/sig-node-pr-reviews PTAL

**Comment by saschagrunert** [comment]
@Random-Liu @dchen1107 @derekwaynecarr @yujuhong @sjenning @mrunalp @klueska PTAL

**Comment by dims** [comment]
this is a code cleanup, no change in logic or public API (that ends up in staging/). happy to land this.

/approve
/lgtm

**Pull request merged**
