### PR TITLE
remove some people from OWNERS so they don't get reviews anymore

### PR DESCRIPTION
**Pull request by mikedanese**
These are googlers who don't work on the project anymore but are still
getting reviews assigned to them:
- @bprashanth
- @rjnagal
- @vmarmol

### CODE REVIEW

**Comment by thockin** [comment]
What?  @bprashanth doesn't get to leave us high and dry...  Oh, I guess he does.

/lgtm
/approve no-issue

**Comment by bprashanth** [comment]
Haha, ping or email me with something and ill surely look at whatever it is, fwiw. Context switching between legacy framework junk and kube is just too depressing, so I've just been MIA for a bit :)

**Pull request merged**
