### PR TITLE
Remove kube-dns ConfigMap modification code from federation-{up,down}.sh scripts

### PR DESCRIPTION
**Pull request by madhusudancs**
PR #39338 has merged now. This shouldn't be necessary. This unbreaks federation tests.

```release-note
NONE
```

### CODE REVIEW

**Comment by madhusudancs** [comment]
This unbreaks federation CI tests. I have waited enough and this is not bubbling up to the front of the queue. I am adding a priority label.

**Comment by madhusudancs** [comment]
@k8s-bot kops aws e2e test this
@k8s-bot gce etcd3 e2e test this

**Comment by madhusudancs** [comment]
@k8s-bot kops aws e2e test this
@k8s-bot gci gke e2e test this
@k8s-bot cvm gke e2e test this
@k8s-bot gci gce e2e test this

**Comment by madhusudancs** [comment]
@k8s-oncall can you please manually merge this? I tried increasing the priority level and that hasn't helped either. This is to unbreak federation CI tests which are red right now.

**Comment by madhusudancs** [comment]
@k8s-bot kops aws e2e test this
@k8s-bot gci gke e2e test this
@k8s-bot cvm gke e2e test this
@k8s-bot gci gce e2e test this

**Comment by shashidharatd** [comment]
@k8s-bot gci gke e2e test this
@k8s-bot cvm gke e2e test this

**Pull request merged**
