### PR TITLE
Add empty file to trigger PR testing

### PR DESCRIPTION
**Pull request by ixdy**
/assign
@k8s-bot pull-kubernetes-e2e-gce-bazel test this

### CODE REVIEW

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-e2e-gce-bazel test this

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-e2e-gce-bazel test this

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-e2e-gce-bazel test this

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-e2e-gce-bazel test this

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-e2e-gce-bazel test this

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-e2e-gce-bazel test this

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-e2e-gce-bazel test this

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-e2e-gce-bazel test this

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-e2e-gce-bazel test this

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-e2e-gce-bazel test this

**Comment by Q-Lee** [comment]
You'll probably need #46259

**Comment by fejta** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
ref https://github.com/kubernetes/test-infra/pull/2931

**Comment by fejta** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this
ref https://github.com/kubernetes/test-infra/pull/2932

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-e2e-kubeadm-gce test this

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-e2e-gce-bazel test this

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-e2e-gce-bazel test this

**Comment by shashidharatd** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
ref: #46827

**Comment by krzyzacy** [comment]
/test pull-kubernetes-e2e-kops-aws-scenario
trigger again in case

**Comment by ixdy** [comment]
¯\\\_(ツ)\_/¯
/unassign fejta
/assign

**Comment by krzyzacy** [comment]
cc @BenTheElder

**Comment by BenTheElder** [comment]
Hmm, I don't think the jobs triggered.
/test all

**Comment by BenTheElder** [comment]
heh, @ixdy you better write a release note for this! :-)

**Comment by BenTheElder** [comment]
This seems bad: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46662/pull-kubernetes-unit/50727/

**Comment by ixdy** [comment]
go home @k8s-merge-robot, you are drunk

**Comment by BenTheElder** [comment]
@k8s-ci-robot y u no test? :imp:

**Comment by stevekuznetsov** [comment]
@BenTheElder I promise that one isn't me 😓

**Comment by BenTheElder** [comment]
It's definitely not showing up in prow. Hmmm http://prow.k8s.io/?type=presubmit&repo=kubernetes%2Fkubernetes&pull=46662

**Comment by BenTheElder** [comment]
hmm @spxtr any idea why tests aren't triggering?

**Comment by spxtr** [comment]
Ooo that's not good.

**Comment by spxtr** [comment]
```

17:11:45.000
panic: runtime error: invalid memory address or nil pointer dereference
17:11:45.000
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x84094b]
17:11:45.000
17:11:45.000
goroutine 54 [running]:
17:11:45.000
k8s.io/test-infra/prow/npj.PresubmitSpec(0xc42022a700, 0x1e, 0x1, 0x0, 0x0, 0xc42022a6e0, 0x1e, 0xc4203bff40, 0x39, 0xc420a86360, ...)
17:11:45.000
/usr/local/google/home/spxtr/go/src/k8s.io/test-infra/prow/npj/npj.go:60 +0x43b
17:11:45.000
k8s.io/test-infra/prow/npj.PresubmitSpec(0xc42022a6a0, 0x1b, 0x1, 0x0, 0x0, 0xc42022a680, 0x1b, 0xc420394280, 0x36, 0xc420a86330, ...)
17:11:45.000
/usr/local/google/home/spxtr/go/src/k8s.io/test-infra/prow/npj/npj.go:63 +0x26c
17:11:45.000
k8s.io/test-infra/prow/plugins/trigger.handleIC(0xb63d40, 0xc420053860, 0xb5a200, 0xc420632910, 0xc4205759e0, 0xc4202b7140, 0xc4208a8358, 0x7, 0xc4208a8678, 0x4, ...)
17:11:45.000
/usr/local/google/home/spxtr/go/src/k8s.io/test-infra/prow/plugins/trigger/ic.go:146 +0x91a
17:11:45.000
k8s.io/test-infra/prow/plugins/trigger.handleIssueComment(0xc420053860, 0xc420632910, 0xc4206329b0, 0xc420235120, 0xc4205759e0, 0xc4202b7140, 0xc4208a8358, 0x7, 0xc4208a8678, 0x4, ...)
17:11:45.000
/usr/local/google/home/spxtr/go/src/k8s.io/test-infra/prow/plugins/trigger/trigger.go:91 +0x167
17:11:45.000
k8s.io/test-infra/prow/hook.(*Server).handleIssueCommentEvent.func1(0xc4207dd620, 0xc4202b6780, 0xc420558180, 0xc420874f30, 0x7, 0x960008)
17:11:45.000
/usr/local/google/home/spxtr/go/src/k8s.io/test-infra/prow/hook/events.go:146 +0x157
17:11:45.000
created by k8s.io/test-infra/prow/hook.(*Server).handleIssueCommentEvent
17:11:45.000
/usr/local/google/home/spxtr/go/src/k8s.io/test-infra/prow/hook/events.go:149 +0x537
```

**Comment by spxtr** [comment]
/test all

@BenTheElder your change a few hours ago broke it and nobody noticed cause we don't have any monitoring :(

**Comment by spxtr** [comment]
OK They're triggering :)

**Comment by BenTheElder** [comment]
@spxtr which change?

**Comment by spxtr** [comment]
See #4278

**Comment by BenTheElder** [comment]
ah (ref: https://github.com/kubernetes/test-infra/pull/4278)

**Comment by BenTheElder** [comment]
Hmm job doesn't seem to be starting...

**Comment by BenTheElder** [comment]
/cc @cjwagner 
@kubernetes/sig-testing-misc test message

**Comment by kargakis** [comment]
Flakiest commit of the repo

**Comment by krzyzacy** [comment]
:-( the shrug color is wrong.. yuks need to be redeployed..

**Comment by xiangpengzhao** [comment]
Hmm... :smiling_imp: The bot didn't tell me a joke but told you @krzyzacy :smile: 

/joke

**Comment by xiangpengzhao** [comment]
/joke
/joke

I'm unhappy! Tell me a joke!!!

**Comment by xiangpengzhao** [comment]
Okay, then
/retest

Just do something for me :smiling_imp:

**Comment by krzyzacy** [comment]
@xiangpengzhao it need to be in one line and only one line. I fixed that but did not have a chance to redeploy the joke bot.

**Comment by xiangpengzhao** [comment]
@krzyzacy thanks! got it :)

**Comment by BenTheElder** [comment]
gke-gpu seems to consistently not see a BUILD file in vendor/ with a different spot each time??
/shrug

**Comment by BenTheElder** [comment]
ref: https://github.com/kubernetes/kubernetes/pull/52755 for 1.7

**Comment by krzyzacy** [comment]
/test pull-kubernetes-e2e-kops-aws-prow
(something else is dirty?)

**Comment by krzyzacy** [comment]
/test pull-kubernetes-e2e-kops-aws-prow
(now I need to hack the container)

**Comment by krzyzacy** [comment]
```
root@e6f127a5-a000-11e7-b9ee-0a580a6c0209:/workspace/kubernetes# git status
On branch test
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.aws/
```

😢

**Comment by krzyzacy** [comment]
`Server terminated abruptly (error code: 14, error message: '', log file: '/root/.cache/bazel/_bazel_prow/48d5366022b4e3197674c8d6e2bee219/server/jvm.out')` :confused: 
/test pull-kubernetes-e2e-kops-aws-prow

**Comment by BenTheElder** [comment]
@ixdy can we move the dummy file to `build` so that we trigger `run_if_changed` jobs?

**Comment by BenTheElder** [comment]
I did this in https://github.com/kubernetes/kubernetes/pull/52755

**Comment by krzyzacy** [comment]
(Why it reported while no test is triggered? Because this is the flakiest PR!)

**Comment by krzyzacy** [comment]
/test pull-kubernetes-federation-e2e-gce-canary
cc @shashidharatd

**Comment by krzyzacy** [comment]
/test pull-kubernetes-e2e-gke-gpu
cc @MrHohn

**Comment by BenTheElder** [comment]
Grrrr. That didn't actually run

**Comment by BenTheElder** [comment]
See @krzyzacy? Verify is flaketastic.

**Comment by krzyzacy** [comment]
/test pull-kubernetes-e2e-kops-aws-prow
:-(

**Comment by BenTheElder** [comment]
forgot to repush the image:
/test pull-kubernetes-verify-prow
/test pull-kubernetes-unit-prow

**Comment by krzyzacy** [comment]
woo it passed :-)
/test pull-kubernetes-kubemark-e2e-gce-prow

**Comment by BenTheElder** [comment]
> woo it passed :-)

unit and verify too :-)

**Comment by ixdy** [comment]
hmm, I don't think we're running the integration tests in CI. :\

/test pull-kubernetes-bazel-test-canary

**Comment by BenTheElder** [comment]
> hmm, I don't think we're running the integration tests in CI. :\

I thought these were filtered out in most of our configs in general?

**Comment by ixdy** [comment]
aha! `pull-kubernetes-baze-test-canary` does not skip the integration tests, while `pull-kubernetes-bazel-test` does.

**Comment by x13n** [comment]
Woops, wrong repo. I guess I need my own PR.

**Comment by BenTheElder** [comment]
Please don't close this, we use these PRs to validate new presubmit configurations.

**Comment by BenTheElder** [comment]
time to ruin our shiny cache metrics (those need to be expanded somewhat anyhow)
/test pull-kubernetes-bazel-test-canary
/test pull-kubernetes-bazel-build-canary
/test pull-kubernetes-bazel-test
/test pull-kubernetes-bazel-build

**Comment by BenTheElder** [comment]
uh that failed without even pod logs https://prow.k8s.io/log?job=pull-kubernetes-bazel-test-canary&id=180
/test pull-kubernetes-bazel-test-canary

**Comment by BenTheElder** [comment]
too fast, those picked up the old config

**Comment by ixdy** [comment]
how long do I need to wait?

**Comment by BenTheElder** [comment]
Prow has a one minute tick background sync routine so ~1 minute works

**Comment by BenTheElder** [comment]
once more and then we'll flip the caching on for the non-canary now that we've got more space:
/test pull-kubernetes-bazel-build-canary

**Comment by BenTheElder** [comment]
[hunting for flakes after enabling `--remote_max_connections=200` + bazel 0.15 in the canary]
/test pull-kubernetes-bazel-build-canary
/test pull-kubernetes-bazel-test-canary

**Comment by BenTheElder** [comment]
[hunting for more flakes after enabling --remote_max_connections=200 + bazel 0.15 in the canary :/]
/test pull-kubernetes-bazel-build-canary
/test pull-kubernetes-bazel-test-canary

**Comment by krzyzacy** [comment]
/test pull-kubernetes-e2e-kops-aws 
(for https://github.com/kubernetes/test-infra/pull/8973, just in case)

**Comment by krzyzacy** [comment]
/test pull-kubernetes-e2e-kops-aws
🤕

**Comment by krzyzacy** [comment]
hummm?!

/test pull-kubernetes-e2e-gce

**Comment by krzyzacy** [comment]
/test all
for https://github.com/kubernetes/test-infra/pull/9809

**Comment by krzyzacy** [comment]
/test pull-kubernetes-integration-podutil
/test pull-kubernetes-verify-podutil

have some fix for artifacts dir and created `/go/bin`

**Comment by krzyzacy** [comment]
^ need a bump 🤷‍♂️

**Comment by BenTheElder** [comment]
[IntelICCS.log](https://github.com/kubernetes/kubernetes/files/3119019/IntelICCS.log)
testy test

**Comment by krzyzacy** [comment]
Nooooooooo @ixdy please rebase this most important PR :-p

**Comment by BenTheElder** [comment]
test-comment
<details>bar-identifiable-string</details>

**Comment by ixdy** [comment]
/assign @krzyzacy 
rebased

**Comment by bgrant0607** [comment]
@BenTheElder will this PR be open forever?

**Comment by BenTheElder** [comment]
It doesn't have to be, however we intermittently need a PR like this so
it's been less effort to continue to use this one.

**Comment by BenTheElder** [comment]
*sigh*
it was still using the wrong config, and the last comment is missing an `e`.
/test pull-kubernetes-e2e-kind

**Comment by BenTheElder** [comment]
/test pull-kubernetes-conformance-kind-ga-only
[didn't take..?]

**Comment by liggitt** [comment]
Hmm… unspecified failure exactly at one hour… timeout?

**Comment by liggitt** [comment]
Took forever, but passed. We've now officially bounded the exceptions to the "Conformance only requires GA things" to a single API and a single feature flag, both of which we plan to GA in 1.19.

**Comment by BenTheElder** [comment]
/test pull-kubernetes-e2e-kind-canary
old config??

**Comment by BenTheElder** [comment]
success :-) https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/46662/pull-kubernetes-e2e-kind-canary/1251005530344787968

**Comment by ErezAlster** [comment]
dude

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/92316

I still have 46662 memorized, leaving a breadcrumb 🙃

**Pull request closed without merging**
