### PR TITLE
fix: add azure disk migration support on CSINode

### LINKED ISSUE #88015: azure disk migration does not work on CSINode
**What happened**:
azure disk migration does not work on CSINode

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/kind bug
/assign
/priority important-soon
/sig cloud-provider
/area provider/azure

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix: add azure disk migration support for CSINode

**Which issue(s) this PR fixes**:

Fixes #88015

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix: add azure disk migration support for CSINode
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/kind bug
/assign @davidz627 
/priority important-soon
/sig cloud-provider
/area provider/azure

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Comment by davidz627** [comment]
/lgtm
/approve
/cc @ddebroy 
do you think it would be possible/easy to refactor this so that the logic only exists in our new `MigrationManager` or whatever it was called :)

**Pull request merged**
