### PR TITLE
kubelet/cloudresource: Improving test coverage

### PR DESCRIPTION
**Pull request by tmilox**
Signed-off-by: TommyStarK <thomasmilox@gmail.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

If applied this commit will increase the unit tests code coverage of `pkg/kubelet/cloudresource`.

- Initial unit tests code coverage

Screenshot 2022-12-21 at 12 08 48

- After changes

Screenshot 2022-12-21 at 12 09 44

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by TommyStarK** [comment]
Hello @dchen1107  , @matthyx 

I know guys you are super busy and this PR is far from being a priority. As a very new aspiring contributor I am still trying to become familiar with the code and to start helping on small pieces. Hope you don't mind.

Any feedback will be greatly appreciated 😅.

Best regards,

**Comment by TommyStarK** [comment]
@derekwaynecarr I know you are super busy, another small coverage improvement

**Comment by derekwaynecarr** [comment]
Thanks for the fix.

/approve
/lgtm

**Pull request merged**
