### PR TITLE
Stop redirecting proxy requests to add a trailing slash

### PR DESCRIPTION
**Pull request by nikhiljindal**
Reverting https://github.com/GoogleCloudPlatform/kubernetes/pull/6175
Redirection is not required anymore as per https://github.com/GoogleCloudPlatform/kubernetes/issues/4958#issuecomment-101093276

Reverting since I was bitten by this while testing https://github.com/GoogleCloudPlatform/kubernetes/pull/11076.

Sending a PR now but can be merged post 1.0.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @lavalamp @satnam6502

**Comment by satnam6502** [comment]
Please do not assign anything to me while I am on vacation.

**Comment by lavalamp** [comment]
Uhhh... isn't this redirection the reason why they're no longer required??

**Comment by satnam6502** [comment]
Also, please can you make sure the curl commands from https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/logging-elasticsearch.md work without the slash?
```
$ curl --header "Authorization: Bearer JsUe2Z3cXqa17UQqQ8qWGGf4nOSLwSnp" --insecure https://146.148.94.154/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging/
{
  "status" : 200,
  "name" : "Vance Astrovik",
  "cluster_name" : "kubernetes-logging",
  "version" : {
    "number" : "1.5.2",
    "build_hash" : "62ff9868b4c8a0c45860bebb259e21980778ab1c",
    "build_timestamp" : "2015-04-27T09:21:06Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

work without the slash i.e.

```
$ curl --header "Authorization: Bearer JsUe2Z3cXqa17UQqQ8qWGGf4nOSLwSnp" --insecure https://146.148.94.154/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging
...
```

**Comment by nikhiljindal** [comment]
Yes. Verified that 
```
curl --header "Authorization: Bearer tWsiRVSyo82zqU6XfleCPrpEwdGuRDGZ" --insecure https://104.197.47.13/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging -i
```
and
```
curl --header "Authorization: Bearer tWsiRVSyo82zqU6XfleCPrpEwdGuRDGZ" --insecure https://104.197.47.13/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging/ -i
```
give me the same output.

Is there anything else I should verify? Any UI?

**Comment by satnam6502** [comment]
Apart from the URLs from `kubectl cluster-info` then no. What about @lavalamp 's question? Thank you kindly.

**Comment by lavalamp** [comment]
@nikhiljindal Need to go to elastic search etc through the proxy in a webbrowser and verify that the UI still loads & is functional.

**Comment by nikhiljindal** [comment]
Removing the lgtm tag, until I have tested that.

**Comment by brendandburns** [comment]
PR changed after LGTM, removing LGTM.

**Comment by wojtek-t** [comment]
@nikhiljindal - are you going to proceed with this PR or can we close it (if not, can you please rebase)?

**Comment by satnam6502** [comment]
Ping?

**Comment by nikhiljindal** [comment]
Closing it for now. Will reopen later.

**Pull request closed without merging**
