### PR TITLE
removed this 	k8s.io/kubernetes/pkg/apis/componentconfig from verify-…

### PR DESCRIPTION
**Pull request by kushalShukla-web**
…api-groups.sh

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kushalShukla-web** [comment]
here is the issue for this pr https://github.com/kubernetes/kubernetes/issues/124295

**Review by hwdef — COMMENTED** [review]
/lgtm

**Comment by kushalShukla-web** [comment]
@hwdef @BenTheElder  can we merge this pr ?

**Comment by hwdef** [comment]
> @hwdef @BenTheElder can we merge this pr ?

Sorry, I only have the permission to add LGTM.

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
