### PR TITLE
Fix TestWantsExternalKubeClientSet describe clientset typo

### PR DESCRIPTION
**Pull request by Farice4**
Signed-off-by: Yuanbin.Chen <cybing4@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wgliang** [comment]
@fabian4 
Please put Release note:NONE

**Comment by fabian4** [comment]
@wgliang Done

**Comment by chenyb4** [comment]
Still wait for approved

**Comment by neolit123** [comment]
/cc @kubernetes/sig-api-machinery-pr-reviews 
for approval.

/unassign

**Pull request merged**
