### PR TITLE
Cherry-picks for release 1.2 - 24 Mar

### PR DESCRIPTION
**Pull request by eparis**
#22960: Trusty: support developer workflow on base image
#22974: MESOS: forward globally declared cadvisor housekeeping flags
#23035: kubernetes/kubernetes#23034 Fix controller-manager race condition issue which cause endpoints flush during restart
#23143: Validate minimum CPU limits to be >= 10m
#23167: Add a SSHKey sync check to the master's healthz (when using SSHTunnels).
#23141: kubelet: send all recevied pods in one update
#23145: Use versioned object when computing patch
#23222: Add a Deployment example for kubectl expose.
#23019: Add a rate limiter to the GCE cloudprovider
#23246: update expose command description to add deployment
#23079: Trusty: Support hybrid cluster with nodes on ContainerVM
#23160: Copy annotations back from RS to Deployment on rollback
#23180: Remove the restart-kube-proxy and restart-apiserver functions
#23313: Bump to container-vm-v20160321
#23325: Fix hairpin mode
#23234: Removing URL query param from swagger UI to fix the XSS issue
#23305: Update kubectl help for 1.2 resources
#22818: Trusty: Avoid reaching GCE custom metadata size limit

### CODE REVIEW

**Comment by eparis** [comment]
The script let me down a bit, so I did it like I did for 1.2.0. Will work with @zmerlynn before the next batch to use the script.

**Comment by bgrant0607** [comment]
Thanks.

What happened with "#23035: kubernetes/kubernetes#23034" ?

**Comment by eparis** [comment]
I also posted https://github.com/kubernetes/kubernetes/pull/22835#issuecomment-201031111 for the one approved PR which was not able to be easily/mechanically included.

**Comment by bgrant0607** [comment]
Oh, that's the title. Weird. Nevermind.

**Comment by eparis** [comment]
I had to double check that, it is actually the title!

**Comment by bgrant0607** [comment]
Ok, looks like everything is there.

I labeled all of these PRs with "release-note".

Waiting for tests to pass.

cc @david-mcmahon @roberthbailey

**Comment by bgrant0607** [comment]
Green. Merging.

**Comment by bgrant0607** [comment]
The bot unmarked this PR. :-)

**Comment by bgrant0607** [comment]
Ok, great. #22835 was the only PR not unlabeled. Cool.

**Pull request merged**
