### PR TITLE
Move util/exec to vendor

### PR DESCRIPTION
**Pull request by mengqiy**
Move util/exec to vendor.
Update import paths.
Update godep

Part of #48209

Associate PR against `k8s.io/utils` repo: https://github.com/kubernetes/utils/pull/5

```release-note
NONE
```

/assign @apelisse

### CODE REVIEW

**Comment by apelisse** [comment]
Shouldn't you also remove the code from `pkg/util/exec` ? Sorry if I missed it, there are so many files :D

**Comment by apelisse** [comment]
Yeah, just verified, the code is still there, let's remove it in the same PR, I want to be sure nothing is still using it.

**Comment by mengqiy** [comment]
Fixed golint. PTAL

**Comment by mengqiy** [comment]
It's wired that lint is passing locally, but failed on Jenkins.

**Comment by mengqiy** [comment]
Rebased to pickup a new file that cause `pull-kubernetes-kubemark-e2e-gce` build failure.

**Comment by apelisse** [comment]
I'm glad this is reviewed, approved and everything because we should get it merged promptly. It changes more than a hundred file and is likely to conflict.

/lgtm

Thanks Mengqi

**Pull request merged**
