### PR TITLE
Switch to v3 of github.com/emicklei/go-restful by updating kube-openapi

### PR DESCRIPTION
**Pull request by dims**
Related to: https://github.com/kubernetes/kubernetes/issues/110338

Intended to pick up change in https://github.com/emicklei/go-restful/commit/f292efff46ae17e9d104f865a60a39a2ae9402f1

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

Snyk vulnerability: https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMEMICKLEIGORESTFUL-2435653
Commit with the fix: https://github.com/emicklei/go-restful/commit/f292efff46ae17e9d104f865a60a39a2ae9402f1

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
Looks like `github.com/emicklei/go-restful/v3` is holding up, going to file a PR against `k8s.io/kube-openapi`

**Comment by dims** [comment]
/assign @thockin @smarterclayton 

(need root OWNERS approval)

**Comment by Jefftree** [comment]
Is there a vendor directory update step that was missed?

```
{Script Error ScriptError go: inconsistent vendoring in /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes:
	github.com/emicklei/go-restful: is marked as replaced in vendor/modules.txt, but not replaced in go.mod

	To ignore the vendor directory, use -mod=readonly or -mod=mod.
	To sync the vendor directory, run:
		go mod vendor
```

**Comment by thockin** [comment]
Clearly something isn't happy here.  Usually a v2->v3 change implies a major change - did we need to make and changes to accomodate?  I didn't see any.

**Comment by dims** [comment]
@thockin @Jefftree sorry, will pick this back up tomorrow.

**Comment by dims** [comment]
@thockin @Jefftree this is green :) we did not have to make any changes!

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by liggitt** [comment]
> @thockin @Jefftree this is green :) we did not have to make any changes!

it's good CI passed, but did we review the changelog and ensure there are no subtle issues that impact us?

xref:
* https://github.com/kubernetes/kubernetes/pull/106841#issuecomment-986801321
* https://github.com/kubernetes/kubernetes/pull/97961#discussion_r557004785

**Comment by briantopping** [comment]
@dims I've noticed that these version upgrades [never made it into](https://github.com/kubernetes/client-go/commit/2a9f95519059bcb745428698c59bf4a376c3f383) any 1.24 tag of client-go. I don't understand the tag selection process yet. Any thoughts?

**Comment by dims** [comment]
@briantopping this was merged to master from which only 1.25 release branch was cut, so this will ONLY be in 1.25.x (UNLESS someone cherry picks to older branches)

image

You would have to work with sig-apimachinery folks to see if this is something that qualifies for a cherry pick.

**Pull request merged**
