### PR TITLE
bump npd version to latest v0.8.7

### PR DESCRIPTION
**Pull request by vteratipally**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Bump node-problem-detector v0.8.7 to detect memory and IO errors. Additional metrics have been added. 

#### Special notes for your reviewer:

SHA512 digest of the v0.8.7 tar package:

sha512sum node-problem-detector-v0.8.7.tar.gz 
853576423077bf72e7bd8e96cd782cf272f7391379f8121650c1448531c0d3a0991dfbd0784a1157423976026806ceb14ca8fb35bac1249127dbf00af45b7eea  node-problem-detector-v0.8.7.tar.gz

#### Does this PR introduce a user-facing change?
NONE

For more information on release notes see: https://git.k8s.io/community/contributors/guide/release-notes.md
-->
```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Looks exactly like https://github.com/kubernetes/kubernetes/pull/96716 (for reference).

/lgtm 
/retest

/assign @dchen1107

**Comment by dchen1107** [comment]
I believe your PR description above "SHA512 digest of the v0.8.5 tar package:" should be "SHA512 digest of the v0.8.7 tar package:". 

/lgtm
/approve

**Comment by bobbypage** [comment]
/lgtm

Thanks for updating this.

**Comment by vteratipally** [comment]
gentle reminder

**Comment by SergeyKanzhelev** [comment]
> gentle reminder

unfortunately it is past the code freeze and likely will only be merged in 1.22

**Pull request merged**
