### PR TITLE
cockpit: Update repository url

### PR DESCRIPTION
**Pull request by fabiand**
The regularly updated cockpit builds moved to a different Copr repo.

### CODE REVIEW

**Comment by davidopp** [comment]
LGTM

**Comment by davidopp** [comment]
ok to test

**Comment by davidopp** [comment]
ok to test

**Comment by davidopp** [comment]
Oh hey @fabiand I noticed this is being blocked because you didn't sign the CLA. See the instructions earlier in this comment thread (specifically https://github.com/kubernetes/kubernetes/pull/19913#issuecomment-173483081 )

**Comment by davidopp** [comment]
ping - this needs a rebase

**Comment by davidopp** [comment]
ping

**Comment by fabiand** [comment]
On Wed, Mar 2, 2016 at 8:32 AM, David Oppenheimer <notifications@github.com>
wrote:

> ping
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/19913#issuecomment-191110457>
> .
>

I did not get to sign the required document.
Feel free to abandon this patch.

In reality the vagrant flow seems to be quite unstable anyway.

**Comment by davidopp** [comment]
Can you say more about what problem you've been having with Vagrant?

cc/ @derekwaynecarr

**Comment by fabiand** [comment]
On Wed, Mar 2, 2016 at 8:40 AM, David Oppenheimer <notifications@github.com>
wrote:

> Can you say more about what problem you've been having with Vagrant?
>
> cc/ @derekwaynecarr <https://github.com/derekwaynecarr>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/19913#issuecomment-191113141>
> .
>

I don't remember the details.

The bottom line is that I was using fedora 22 with vagrant-libvirt and I
could not get the vagrant VM to run.
There were a couple of problems.

Incorrect URLs (liek this cockpit one), and IIRC there was a problem with
the Fedora image being pulled.

**Comment by derekwaynecarr** [comment]
@davidopp - so I had tested vagrant earlier this week and saw no issue installing cockpit in fedora 23... I can retest and take over this review, but I am not aware of any problem.  I use cockpit all the time to introspect the cluster...

**Comment by fabiand** [comment]
On Wed, Mar 2, 2016 at 8:24 PM, Derek Carr <notifications@github.com> wrote:

> @davidopp <https://github.com/davidopp> - so I had tested vagrant earlier
> this week and saw no issue installing cockpit in fedora 23... I can retest
> and take over this review, but I am not aware of any problem. I use cockpit
> all the time to introspect the cluster...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/19913#issuecomment-191383788>
> .
>

The problems were mainly around getting the vagrant vm up.

I started with a pretty clean Fedora 22 and followed the vagrant k8s guide.
And failed. A colleague of mine failed as well.

**Comment by davidopp** [comment]
@fabiand can you please rebase this PR?

**Comment by fabiand** [comment]
The current master already has this update.  Closing this PR thereof.

**Pull request closed without merging**
