### PR TITLE
Automated cherry pick of #11462

### PR DESCRIPTION
**Pull request by nikhiljindal**
requesting cherrypicking #11462 for fixing #11432
Updating update-swagger-spec to build the apiserver before running.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @thockin @zmerlynn @davidopp

**Comment by davidopp** [comment]
LGTM

**Comment by davidopp** [comment]
If @zmerlynn doesn't get to this by 1 PM, I guess one of us should hit merge, though it's better for him to check it first...

**Comment by zmerlynn** [comment]
Waiting on Shippable

**Comment by zmerlynn** [comment]
LGTM otherwise

**Comment by zmerlynn** [comment]
Actually, there's no way Shippable is relevant here (and it's gotten far enough). Cherry picking and trying a mock release flow.

**Comment by zmerlynn** [comment]
Can confirm this issue is fixed on the `release-1.0` branch.

**Pull request merged**
