### PR TITLE
Update the logging images to parse sub-second docker timestamps.

### PR DESCRIPTION
**Pull request by a-robinson**
The configs were updated in #21482, this is just updating the images, which I've pushed.

cc @chrisleck

### CODE REVIEW

**Comment by chrisleck** [comment]
FYI - it looks like some logs are now parsed correctly, but the fluent-plugin-kubernetes_metadata_filter plugin is stripping milliseconds now...sigh.

**Comment by fabioy** [comment]
The change itself seems innocuous -- I'm assuming here the new versions fix the issue.

**Comment by a-robinson** [comment]
Huh. @jimmidyson, is stripping milliseconds in the metadata filter plugin expected?

**Comment by jimmidyson** [comment]
Not at all. Fluentd only supports second resolution of log events, although subsecond precision is now supported in fluentd v0.14.0.pre.1 & master.

The metadata filter plugin shouldn't strip anything, but is only able to use subsecond precision of fluentd itself supports it.

**Comment by eparis** [comment]
jenkins has screwed up, this PR is now stuck.  https://github.com/kubernetes/kubernetes/issues/22435

Thus far the best way I've seen to get it unstuck is to make a tiny change. repush, and re-add LGTM. Sorry   :-(

**Comment by a-robinson** [comment]
Thanks @eparis, done.

**Pull request merged**
