### PR TITLE
Update container runtime flags to use containerd instead of docker

### PR DESCRIPTION
**Pull request by upodroid**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
We got rid of docker as a runtime a long time ago in favour of containerd. However, containerd jobs still set values for these flags so I want to set these to defaults for containerd to simplify the prow config for those jobs.

Also, `/var/run` has been deprecated in favour of `/run` for a long time now.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

I'm in favor of this change of defaults. The side effect - it may break any tests authored by cri-dockerd if they run any using this test framework.

But since cri-dockerd is not very actively being present in k/k repo, I think streamlining containrd conigs is better than keeping back compat here

**Comment by dims** [comment]
/approve

i like how @SergeyKanzhelev phrased it! let's give it a whirl

**Pull request merged**
