### PR TITLE
Scheduler: use cmp.Diff instead of reflect.DeepEqual for framework except plugins

### PR DESCRIPTION
**Pull request by gavinfish**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

just use cmp.Diff instead of reflect.DeepEqual.

**Which issue(s) this PR fixes**:

Xref #94696

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
why are you holding? is this not ready for review yet? If so, please unassign until ready

**Comment by gavinfish** [comment]
/unassign @alculquicondor 
I need rethink about PluginsToStatus merge etc., sorry for any inconvenience.

**Pull request closed without merging**
