### PR TITLE
Changing AWS examples / templates to use 0.19.3 release

### LINKED ISSUE #10467: Sample cloud-config master.yaml has wrong kube-apiserver options
[the --service-cluster-ip-range option](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/aws/cloud-configs/master.yaml#L121) results in this:

```bash
$ ./kube-apiserver --insecure-bind-address=0.0.0.0 --service-cluster-ip-range=10.100.0.0/16 --etcd-servers=http://localhost:2379
unknown flag: --service-cluster-ip-range
Usage of ./kube-apiserver:
...
```

```bash
$ ./kube-apiserver --version 
Kubernetes v0.17.0
```

### PR DESCRIPTION
**Pull request by chiefy**
- Fixes #10467
- Updating CoreOS AMI ids

### CODE REVIEW

**Comment by chiefy** [comment]
I signed it!

**Comment by zmerlynn** [comment]
Is this all you needed to do - update the AMIs and versions?

Oh, wow, I just noticed the super-confusion in the Getting Started Guide directory. There's this file, which as far as I can tell isn't linked to from https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides . And then there's the entire CoreOS family, which is linked to from the table. cc @erictune because confused.

Anyways, in general this LGTM if it works for you - I'm not trying to cause friction. We can open a separate issue for sorting out the rest.

**Comment by zmerlynn** [comment]
Assigning to @erictune in case there's anything about the directory pieces he wants to handle, and for other review, etc.

**Comment by chiefy** [comment]
@zmerlynn yeah, as a n00b, the AWS docs were kind of all over the place, but not so bad I couldn't find them. I ended up making at [Terraform based setup](https://github.com/chiefy/tf-aws-kubernetes) using the YAML cloud-configs and it seems to work fine now.

**Comment by bprashanth** [comment]
waiting on Eric's final review

**Comment by erictune** [comment]
Thanks for updating.  LGTM

**Comment by kelseyhightower** [comment]
ok to test

**Comment by erictune** [comment]
needs rebase.

**Comment by erictune** [comment]
You did a merge.  I was looking for a rebase.
At this point, you could do something like the following in your git client.
- `git rebase -i HEAD~2` and delete the line that says "Merge branch upstream_master".
- `git fetch upstream`
- `git rebase upstream/master`

See Git Setup in docs/devel/development.md

**Comment by erictune** [comment]
https://github.com/chiefy/tf-aws-kubernetes looks pretty cool, by the way.

**Comment by chiefy** [comment]
@erictune I was getting conflicts on my rebase I didn't feel comfortable with... will try again, sorry.

**Comment by zmerlynn** [comment]
@k8s-bot ok to test

**Comment by erictune** [comment]
Thanks for this contribution.  I'm happy to merge it.

At some point in the future, I'd like to understand:
 - does this file really need to use kube-register now that kubelets support self-registration? 
 - I can't tell if you are the only one using this file.  If so, it might make sense to move it to your repo.

**Comment by erictune** [comment]
LGTM

**Comment by chiefy** [comment]
@erictune I know very little about Kubernetes, I consider myself a n00b. I was interested to investigate using it, and I love using Terraform to standup AWS infrastructure as it's much easier than using the console (IMO). So I basically came to the wiki looking for info on how to use Kubernetes w/ AWS. I would be more than happy to keep my TF project updated vs. here if you want to somehow link it from the wiki. I very well might be the only person using the cloud-init examples, so it may make sense for me to keep them updated.

I will definitely look into deprecating the use of kube-register when I get some time! 

Thanks!

**Pull request merged**
