### PR TITLE
Fix empty string reclaim policy being considered valid in StorageClass

### PR DESCRIPTION
**Pull request by wongma7**
**What this PR does / why we need it**: currently, storage classes are allowed to be created with `reclaimPolicy==""` which has no documented meaning. Our docs say that if storageclass.reclaimPolicy is unspecified/nil, the default reclaimPolicy is Delete but they say nothing about empty string/"". So we should make "" invalid.

If the empty string from `storageClass.ReclaimPolicy` gets passed to a PV, the PV defaulting resets it to `Retain`. IMO this is okay since `PV.Spec.PersistentVolumeReclaimPolicy` is not a pointer and we can consider this PV empty string behaviour "legacy" behaviour. But storageclasses should know better and should not be able to have reclaimPolicy=="" when we have documented that it must be either "nil" or one of the 2 valid policies.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**: commit 1 fixes an issue where the error validation tests would succeed no matter what because none of them had volumeBindingMode set.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wongma7** [comment]
@kubernetes/sig-storage-pr-reviews @kubernetes/sig-storage-api-reviews 
/kind bug

**Comment by jsafrane** [comment]
/lgtm
for the code

/assign @liggitt 
for approval, validation will reject StorageClasses that were working before, but IMO it's a good idea here.

**Comment by liggitt** [comment]
/hold

Tightening validation in a way that causes existing persisted data to be considered invalid is a breaking API change.

What is the current behavior of a storage class with `reclaimPolicy:""`?

**Comment by wongma7** [comment]
The current behaviour is that PVs provisioned for the storageclass are created with reclaimPolicy `Retain`

**Comment by wongma7** [comment]
@liggitt 
I would add 1 more option which I like the best:

5. Similar to 2 but we change "" to default to "Retain". The argument for this is that this is what PVs do (I neglected to say in comment above, but the reason storageClass.reclaimPolicy=="" results in PV.spec.reclaimPolicy is because of pv defaulting code https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/v1/defaults.go#L238). And we avoid the "a storage class from 1.11 would start to work differently in 1.12" problem. Argument against this is that users typically think of "" as equivalent to nil/"unspecified" (see: confusion over "" vs nil pvc.spec.storageClassName). But I would rather they be surprised that their "" has become Retain than surprised that their "" has become Delete, because the latter case might result in unexpected data loss.

3. is also okay I think. Our docs say the default provisioning policy is Delete and again, users think of nil=="". In other words, instead of blindly passing "" to the pv defaulting code, we change it to Delete first.

4. I guess you mean "Retain" in the last word there. I know the "" vs nil pvc.spec.storageClassName documentation sets the precedent that it's possible (but not easy) to teach users ""!=nil.

**Comment by wongma7** [comment]
On second thought the “unexpected data loss” risk might be overstated :) so options2 and 3 get some more points from me, but I still want 5 the most

**Pull request closed without merging**
