### PR TITLE
move functions from e2e/framework/deployment/ to e2e/apps/ and e2e/up…

### PR DESCRIPTION
**Pull request by tanjunchen**
…grades

**What type of PR is this?**
 
/kind cleanup

**What this PR does / why we need it**:

move functions from e2e/framework/deployment/ to e2e/apps/ and e2e/upgrade

**Which issue(s) this PR fixes**:

ref:https://github.com/kubernetes/kubernetes/issues/86052

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by mingyuanzhu** [comment]
@tanjunchen Hello Junchen, I find there are many `wait functions` are distributed in
* e2e/framework/deployment/wait.go
* e2e/apps/deployment.go
* utils/deployment.go
Could you help to explain the principles and how do we decide? Thanks very much.

**Comment by tanjunchen** [comment]
@mingyuanzhu This PR has been around for a long time (5 years ago), you can check the [issue](https://github.com/kubernetes/kubernetes/issues/86052) for specific background.

**Pull request merged**
