### PR TITLE
set standard storage class addon mode to "ensure-exists"

### LINKED ISSUE #66222: Unable to change the default storage class.
**Is this a BUG REPORT or FEATURE REQUEST?**:
> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
Not able to change the default storage class. 
**What you expected to happen**:
Default storage class to change. 
**How to reproduce it (as minimally and precisely as possible)**:
~~~
$ kubectl patch storageclass standard -p '{"metadata": {"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"false"}}}'
storageclass "standard" patched

$ kubectl describe sc standard
Name:            standard
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true"},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile"},"name":"standard","namespace":""},"provisioner":"k8s.io/minikube-hostpath"}
,storageclass.beta.kubernetes.io/is-default-class=false
Provisioner:        k8s.io/minikube-hostpath
Parameters:         <none>
ReclaimPolicy:      Delete
VolumeBindingMode:  Immediate
Events:             <none>

$ kubectl get sc
NAME                        PROVISIONER                AGE
rook-ceph-block (default)   ceph.rook.io/block         14h
standard                    k8s.io/minikube-hostpath   14h
~~~
But after few mins.
~~~
$ kubectl get sc --watch
NAME                        PROVISIONER                AGE
rook-ceph-block (default)   ceph.rook.io/block         14h
standard                    k8s.io/minikube-hostpath   14h
standard (default)   k8s.io/minikube-hostpath   14h 

$ kubectl get sc
NAME                        PROVISIONER                AGE
rook-ceph-block (default)   ceph.rook.io/block         14h
standard (default)          k8s.io/minikube-hostpath   14h

$ kubectl describe sc rook-ceph-block
Name:               rook-ceph-block
IsDefaultClass:     Yes
Annotations:        storageclass.beta.kubernetes.io/is-default-class=true
Provisioner:        ceph.rook.io/block
Parameters:         clusterNamespace=rook-ceph,pool=replicapool
ReclaimPolicy:      Delete
VolumeBindingMode:  Immediate
Events:             <none>
~~~
**Anything else we need to know?**:
Tried to remove the annotation but no luck.

**Environment**:
- Kubernetes version (use `kubectl version`): 
~~~
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.5", GitCommit:"f01a2bf98249a4db383560443a59bed0c13575df", GitTreeState:"clean", BuildDate:"2018-03-19T15:59:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
~~~
- Cloud provider or hardware configuration: minikube
- OS (e.g. from /etc/os-release): Buildroot 2018.05
- Kernel (e.g. `uname -a`): 4.16.14
- Install tools: minikube
- Others:

### PR DESCRIPTION
**Pull request by yue9944882**
**What this PR does / why we need it**:

Change addon mode for standard storage class to `EnsureExists`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #66222

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by roberthbailey** [comment]
/cc @saad-ali

This should be reviewed by someone from sig-storage since this will change behavior of storage classes. 

sig-cluster-lifecycle owns changes to this script, but we shouldn't make a change that affects the behavior of storage classes without getting an approval from someone in the storage sig.

**Comment by yue9944882** [comment]
/assign @saad-ali
PTAL 😃

**Review by saad-ali — APPROVED** [review]
/lgtm
/approve

**Comment by yue9944882** [comment]
/assign @mikedanese 
for final approval

**Pull request merged**
