### PR TITLE
Automated cherry pick of #102306: Return UnschedulableAndUnresolvable instead of Error when
#102465: Return UnschedulableAndUnresolvable when looking up

### PR DESCRIPTION
**Pull request by ahg-g**
Cherry pick of #102306 #102465 on release-1.19.

#102306: Return UnschedulableAndUnresolvable instead of Error when
#102465: Return UnschedulableAndUnresolvable when looking up

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by ahg-g** [comment]
/triage accepted
/kind bug
/priority important-soon
@kubernetes/release-managers

**Comment by puerco** [comment]
I just noticed that the cherry-picks for other branches already merged. Thank you @ahg-g 
/lgtm
/release-note-none

**Pull request merged**
