### PR TITLE
GCE/Windows: disable stackdriver logging agent

### PR DESCRIPTION
**Pull request by yujuhong**
The logging service could not be stopped at times, causing node startup
failures. Disable it until the issue is fixed.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
GCE/Windows: disable stackdriver logging agent to prevent node startup failures
```

### CODE REVIEW

**Comment by tpepper** [comment]
Which part of testgrid (https://testgrid.k8s.io/sig-windows ?) would cover this patch?  I'm slightly concerned it might break some test case, yet we don't have a master-blocking or 1.14-blocking windows test that I know of, so I'm wondering where to watch to gauge its readiness for backport to 1.14 branch as per https://github.com/kubernetes/kubernetes/pull/76100

**Comment by yujuhong** [comment]
@tpepper this one: https://testgrid.k8s.io/sig-windows#gce-windows-1.14

We don't really have tests running for stackdriver logging yet, so no tests will be affected. This is causing the occasional cluster bringup failure you can see in the test job.

**Comment by yujuhong** [comment]
> @tpepper this one: https://testgrid.k8s.io/sig-windows#gce-windows-1.14

Oops, that one runs against the 1.14 branch.
This is the job against the master: https://testgrid.k8s.io/sig-windows#gce-windows-master
It hasn't had any cluster bringup failure since the PR has been merged.

**Comment by tpepper** [comment]
Sounds good, thanks for the additional context @yujuhong!

**Pull request merged**
