### PR TITLE
tests: Adds agnhost image

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind failing-test
/kind feature

/sig testing
/sig windows

/area conformance

**What this PR does / why we need it**:

The new image is meant to be used for testing purposes, whenever there
are significant differences between Linux and Windows in the way
something is obtained or tested. For example, the DNS suffix list can
be found in ``/etc/resolv.conf`` on Linux, but on Windows, such file
does not exist, and one way to obtain the mentioned list would be
through some powershell commands.

The image contains an extendable CLI as the entrypoint, the tests
only having to add the necessary arguments. For the previous example,
passing the ``dns-suffix`` argument will print out the comma separated
DNS suffix list, on both Linux and Windows.

The image name means that it should behave the same way on any host,
no matter the host OS.

**Which issue(s) this PR fixes**:

Related #73425
Related https://github.com/kubernetes/kubernetes/pull/74985

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by bclau** [comment]
NOTE: One other usecase this could be useful for in the future: the ``/etc/hosts`` file has a different location on Windows.

**Comment by SataQiu** [comment]
Thanks @bclau 
But the CI failed. You can run `./hack/update-bazel.sh` to make bazel build pass.

**Comment by listx** [comment]
> Thanks @bclau
> But the CI failed. You can run `./hack/update-bazel.sh` to make bazel build pass.

The link says that `utils_linux.go` is missing. Looks like you forgot to add it to this PR.

**Comment by bclau** [comment]
> 
> 
> > Thanks @bclau
> > But the CI failed. You can run `./hack/update-bazel.sh` to make bazel build pass.
> 
> The pull-kubernetes-bazel-build link says that `utils_linux.go` is missing. Looks like @bclau forgot to add it.

Arguable, I would say I didn't, ``utils.go`` is supposed to be the linux one (or rather, the non-windows one), check the ``// +build`` comment. Don't know the best approach to this. If I do this, it is expecting a file named ``utils_linux.go``. If I have ``utils_linux.go``, it won't build for darwin, and will probably require ``utils_darwin.go`` as well, even though it would be the same as ``utils_linux.go``.

**Comment by mgdevstack** [comment]
There are many e2e which are using Linux specific tools to retrieve network level information. It might be good to start adding in this image:
e.g.
1. Retrieving socket level information. (used `ss` in Linux) https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L1223
2. `wget` to retrive file content from endpoints.
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L1315

**Comment by mgdevstack** [comment]
How are we planning to address following challenged -
1. Documentation about included tools and their uses. (e.g. dns_suffix, ss, wget etc. Passing these pkg specific flags and args which might be different for E2Es and would have different implementations for Linux & Windows)
2. Every time a change is made to agnhost app files requires to repeat, code-change->build-image->push-to-image-registry

**Comment by bclau** [comment]
> 
> 
> > Thanks @bclau
> > But the CI failed. You can run `./hack/update-bazel.sh` to make bazel build pass.
> 
> The pull-kubernetes-bazel-build link says that `utils_linux.go` is missing. Looks like @bclau forgot to add it.

I didn't forget that, I forgot to update the BUILD file. :)


> 
> 
> How are we planning to address the following points -
> 
>     1. Documentation about included tools and their uses. (e.g. dns_suffix, ss, wget etc. Passing these pkg specific flags and args which might be different for E2Es and would have different implementations for Linux & Windows)

We could add a README file in the ``test/images/agnhost`` folder. 

> 
>     2. Every time a change is made to agnhost app files requires to repeat, code-change->build-image->push-to-image-registry

AFAIK, there is no image build automation at all, and all those steps will have to be done manually. That will have to be done by someone who has access to the gcr.io registries. For the Windows ones under ``e2eteam`` docker registry, it is on our backlog to automate the process. But this question would apply to any and all images under the ``tests/images`` folder.

**Comment by listx** [comment]
> > > Thanks @bclau
> > > But the CI failed. You can run `./hack/update-bazel.sh` to make bazel build pass.
> > 
> > 
> > The pull-kubernetes-bazel-build link says that `utils_linux.go` is missing. Looks like @bclau forgot to add it.
> 
> I didn't forget that, I forgot to update the BUILD file. :)
> 
> > How are we planning to address the following points -
> > ```
> > 1. Documentation about included tools and their uses. (e.g. dns_suffix, ss, wget etc. Passing these pkg specific flags and args which might be different for E2Es and would have different implementations for Linux & Windows)
> > ```
> 
> We could add a README file in the `test/images/agnhost` folder.
> 
> > ```
> > 2. Every time a change is made to agnhost app files requires to repeat, code-change->build-image->push-to-image-registry
> > ```
> 
> AFAIK, there is no image build automation at all, and all those steps will have to be done manually. That will have to be done by someone who has access to the gcr.io registries. For the Windows ones under `e2eteam` docker registry, it is on our backlog to automate the process. But this question would apply to any and all images under the `tests/images` folder.

If you haven't already, can you create an issue for me to push the image up to the gcr.io registry you want this to land in?

Aside: we are working on automation to automate away the [manual-push-to-gcr.io part](https://github.com/kubernetes/k8s.io/issues/157). Ideally even the "build this image" part could be automated so that e.g., simply merging this PR alone should trigger the process and notify the correct people. That 2nd step will come with time after the first step is completed.

**Comment by listx** [comment]
@ixdy What can I do to get this merged?

**Comment by listx** [comment]
FTR, looks like I just had to wait for tide to do its thing.

**Pull request merged**
