### PR TITLE
tests: Removes [Excluded:WindowsDocker] tag from Windows

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind cleanup

/sig testing
/sig windows

/priority important-soon

/milestone v1.24

#### What this PR does / why we need it:

We've removed support for Windows Docker in Kubernetes v1.24, so we no longer need this tag.

#### Which issue(s) this PR fixes:

Fixes #https://github.com/kubernetes/community/issues/6123

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
test failure looks legit. Please update

**Comment by dims** [comment]
/approve
/lgtm

/assign @johnbelamaric @spiffxp 

(for conformance related files)

**Comment by smarterclayton** [comment]
/approve

Thanks for flagging this dims

**Pull request merged**
