### PR TITLE
Don't run OOM watcher is cAdvisor is not available.

### LINKED ISSUE #8424: Recurring error in kubelet log when cadvisor is not functional
The kubelet log fills up quickly with:
```
2755 kubelet.go:683] failed to record system OOMs - cAdvisor is unsupported in this build
```

### PR DESCRIPTION
**Pull request by vmarmol**
Fixes #8424.

/cc @vishh

### CODE REVIEW

**Comment by vishh** [comment]
If cadvisor is not available, oom watcher should still work via one of the fake cadvisor implementations right?

**Comment by vmarmol** [comment]
@vishh, no they just return an error

**Comment by vishh** [comment]
Should we instead make the fake not return an error?

**Comment by vmarmol** [comment]
I'm not sure making such a fake would be worthwhile. The current fake makes it clear what is failing when, trying to fake some of the behavior will make this murky and it'd be something we'd need to maintain.

**Comment by vishh** [comment]
LGTM

**Pull request merged**
