### PR TITLE
Move cached discovery clients to their own packages

### LINKED ISSUE #68854: Move client-go/discovery/cached_discovery.go to client-go/discovery/diskcached/...
We have a memory-cached discovery client in `client-go/discovery/cached/memcache.go`.

We have a disk-cached discovery client in `client-go/discovery/cached_discovery.go`.

We should cleanup the directory structure.

/sig api-machinery

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #68854.

This pull tries to rearrange the discovery clients in a more logical way.

[update] a good by-product is the removal of a few vendored packages from the staging repositories.

```release-note
Breaking changes in client-go:
The disk-cached discovery client is moved from k8s.io/client-go/discovery to k8s.io/client-go/discovery/cached/disk.
The memory-cached discovery client is moved from k8s.io/client-go/discovery/cached to k8s.io/client-go/discovery/cached/memory.
```

/sig api-machinery
/kind cleanup
/assign @liggitt @mborsz

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@liggitt could you help approve the change? Thanks.

**Comment by liggitt** [comment]
this is a nicer structure, but I have mixed feelings about whether the external churn for callers is worth the change. do we have a good sense for the amount of direct usage these have and what the impact on client-go users would be?

cc @kubernetes/sig-api-machinery-pr-reviews

**Comment by caesarxuchao** [comment]
If we trust the google search engine, there are not many imports.

[Less than 20 results](https://www.google.com/search?q=%22k8s.io/client-go/discovery/cached%22+site:github.com+-site:https://github.com/kubernetes/kubernetes+-vendor+-site:https://github.com/NVIDIA/kubernetes&lr=&hl=en&as_qdr=all&ei=n18tXMqaCuOT0gK89qXQDQ&start=10&sa=N&ved=0ahUKEwiK5snCtdDfAhXjiVQKHTx7CdoQ8tMDCGI&biw=1463&bih=749) of results for the memcached one.

[Two results](https://www.google.com/search?lr=&hl=en&as_qdr=all&ei=7VwtXOfiOIb_0wKZvJ_4BQ&q=%22k8s.io%2Fclient-go%2Fdiscovery%22+%22NewCachedDiscoveryClientForConfig%22+site%3Agithub.com+-site%3Ahttps%3A%2F%2Fgithub.com%2Fkubernetes%2Fkubernetes+-vendor+-openshift&oq=%22k8s.io%2Fclient-go%2Fdiscovery%22+%22NewCachedDiscoveryClientForConfig%22+site%3Agithub.com+-site%3Ahttps%3A%2F%2Fgithub.com%2Fkubernetes%2Fkubernetes+-vendor+-openshift&gs_l=psy-ab.3...774003.846196..846491...0.0..0.0.0.......4....1j2..gws-wiz.z8-tINAxnRI) for the disk cached one.

I tried github code search as well, but it doesn't support exact match.

I can send a break change waring to the kubernetes-dev mailing list if that helps move this forward.

**Comment by liggitt** [comment]
seems reasonable, would like a second ack from @kubernetes/sig-api-machinery-pr-reviews 

/assign @deads2k

**Comment by caesarxuchao** [comment]
Gentle ping @deads2k

**Comment by lavalamp** [comment]
The structure is much nicer. Can you leave type aliases behind so as to not break people? https://golang.org/doc/go1.9#language

**Comment by caesarxuchao** [comment]
>  Can you leave type aliases behind so as to not break people?

I can't do that for the disk cached one, otherwise there will be cyclic imports.

For the mememory cached one, I didn't do the type aliase, because the package doesn't define any public type. I did add a glue package for the legacy code in the last commit.

**Comment by lavalamp** [comment]
Hm, can you think of a variation on the directory structure that doesn't
cause cyclic imports?

**Comment by deads2k** [comment]
I don't feel strongly about an alias. This change lgtm

/lgtm
/approve
/hold

holding in case @lavalamp really wants an alias.

**Comment by caesarxuchao** [comment]
@lavalamp no, the alias will introduce cycle no matter how we arrange the directory now, because of these two facts:
* The disk cached client used to live in the discovery package. 
* The disk cached client depends on the discovery package.

**Comment by lavalamp** [comment]
/approve
/hold cancel

I guess we break some interface every release, why stop now? :/

**Pull request merged**
