### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by timchenxiaoyu**
retries and hierarchy  typo error

### CODE REVIEW

**Comment by feiskyer** [comment]
LGTM

**Comment by feiskyer** [comment]
@k8s-bot ok to test

**Comment by timchenxiaoyu** [comment]
@k8s-bot node e2e test this

**Comment by timchenxiaoyu** [comment]
@k8s-bot cvm gke e2e test this
@k8s-bot gci gke e2e test this

**Comment by timchenxiaoyu** [comment]
@k8s-bot gci gke e2e test this

**Comment by feiskyer** [comment]
@wojtek-t Could you help to remove `do-not-merge` label?

**Comment by feiskyer** [comment]
@k8s-bot cvm gce e2e test this

**Comment by timchenxiaoyu** [comment]
@k8s-bot cvm gce e2e test this

**Comment by timchenxiaoyu** [comment]
@k8s-bot verify test this

**Pull request merged**
