### PR TITLE
Allow CSI Drivers suporting 0.x/1.x to use old dir

### LINKED ISSUE #71517: Allow CSI Drivers that support BOTH 0.x and 1.x to use old plugin dir
**What happened**:
CSI allows 0.x drivers only in the deprecated kubelet plugin dir.
CSI allows 1.x drivers only in the new kubelet plugin dir.

If a driver implements both 0.x and 1.x (which is unlikely since the side car containers do not support this), kubelet requires the driver live in new kubelet plugin dir.

So CSI drivers that implement both 0.x and 1.x if they want a seamless transition between k8s 1.12 to 1.13 would need to deploy in both old and new dir.

**What you expected to happen**:

@liggitt argues that this is adding churn for CSI authors. He recommends allowing any driver that implements 0.x (even if it implements 1.x) to use either new or old (not just new).

/milestone v1.13

If release team approves, PR is small and I can get prepare it pretty quickly.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

### PR DESCRIPTION
**Pull request by saad-ali**
Allow drivers implmenting both CSI 0.x and 1.x to use the old volume
plugin directory in addition to the the new volume plugin directory.

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/kubernetes/issues/71517

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by dims** [comment]
LGTM 👍

**Comment by liggitt** [comment]
do we need a test for `versions: []string{}, foundInDeprecatedDir: true`? that case wasn't covered before.

**Comment by saad-ali** [comment]
> do we need a test for `versions: []string{}, foundInDeprecatedDir: true`? that case wasn't covered before.

There is already a test for that case:

https://github.com/kubernetes/kubernetes/blob/18050e308c5603038947ec260ddd92e0c10e0002/pkg/volume/csi/csi_plugin_test.go#L721-L725

**Pull request merged**
