### PR TITLE
Add namespace for describe pdb

### LINKED ISSUE #49363: pdb's describer forget namespace
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:
image

image

**What you expected to happen**:
"kubectl describe pdb" may contain namespaces.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.1.687+9848cdb3ac67d6", GitCommit:"9848cdb3ac67d64e2f446a69928b7c0610f0f56a", GitTreeState:"clean", BuildDate:"2017-07-03T02:17:22Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.1.687+9848cdb3ac67d6", GitCommit:"9848cdb3ac67d64e2f446a69928b7c0610f0f56a", GitTreeState:"clean", BuildDate:"2017-07-03T02:17:22Z", GoVersion:"go1.8", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`): Linux k8s 3.10.0-514.26.1.el7.x86_64 #1 SMP Thu Jun 29 16:05:25 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:  rpm
- Others:

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
add namespace for describe pdb

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
fixes https://github.com/kubernetes/kubernetes/issues/49363
**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
@fabianofranz  don't we have some kind of an object meta description method somewhere?

**Comment by fabianofranz** [comment]
@deads2k not for these, we have it for labels, annotations, etc

**Pull request merged**
