### PR TITLE
Automated cherry pick of #39311

### PR DESCRIPTION
**Pull request by rkouj**
Cherry pick of #39311 on release-1.5.

#39311: Check if pathExists before performing Unmount

### CODE REVIEW

**Comment by rkouj** [comment]
@k8s-bot node e2e test this

**Comment by rkouj** [comment]
@k8s-bot cri node e2e test this

**Comment by rkouj** [comment]
@k8s-bot node e2e test this

**Comment by rkouj** [comment]
Is it failing because the parent PR doesn't have the appropriate labels ? (cherrypick-candidate, milestone, release-note)

**Comment by rkouj** [comment]
@k8s-bot node e2e test this

**Comment by rkouj** [comment]
@k8s-bot cri node e2e test this

**Comment by saad-ali** [comment]
Failing E2Es hit #39597 which is now fixed. Rerunning failing E2E

**Comment by saad-ali** [comment]
@k8s-bot node e2e test this

**Comment by saad-ali** [comment]
@k8s-bot cri node e2e test this

**Comment by rkouj** [comment]
@k8s-bot cvm gce e2e test this

**Comment by rkouj** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
