### PR TITLE
Adds OWNERS files to client-go streaming dirs

### PR DESCRIPTION
**Pull request by seans3**
* Adds OWNERS file to `client-go/tools/remotecommand`
* Adds OWNERS file to `client-go/tools/portforward`

/kind cleanup

```release-note
NONE
```

/sig api-machinery

### CODE REVIEW

**Comment by liggitt** [comment]
> Gaze not into the abyss, lest you become recognized as an abyss domain expert

/lgtm
/approve

**Comment by aojea** [comment]
👍

**Pull request merged**
