### PR TITLE
Add the default dns options to kubelet when k8s-in-docker

### PR DESCRIPTION
**Pull request by luxas**
Add and document DNS options for the single-node docker getting started guide, so the user is able to deploy DNS easily.

@fgrzadkowski @brendandburns @gmarek

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by luxas** [comment]
Thanks @wojtek-t for following this up

**Pull request merged**
