### PR TITLE
[sig-windows] Write to unique file to avoid conflicts with other tests

### LINKED ISSUE #99365: Windows volume mounts check volume mount permissions container should have readOnly permissions on hostMapPath
#### Which jobs are failing:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1364218404642230272
#### Which test(s) are failing:
Kubernetes e2e suite: [sig-windows] [Feature:Windows] Windows volume mounts check volume mount permissions container should have readOnly permissions on hostMapPath
#### Testgrid link:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1364218404642230272
#### Reason for failure:
Feb 23 14:59:47.591: FAIL: cmd: [cmd /c echo windows-volume-test > C:\tmp\test-file], stdout: "", stderr: "Access is denied."
```
Unexpected error:
    <exec.CodeExitError>: {
        Err: {
            s: "command terminated with exit code 1",
        },
        Code: 1,
    }
```

### PR DESCRIPTION
**Pull request by jsturtevant**
#### What type of PR is this?
/kind bug
/kind failing-test
/kind flake

#### What this PR does / why we need it:
This ensures we have unique files to avoid issues with other tests writing to the same file.  

#### Which issue(s) this PR fixes:

Fixes #99365

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig windows
/milestone v1.21

### CODE REVIEW

**Review by chewong — APPROVED** [review]
/lgtm
/hold
let's wait for Windows presubmit jobs to return the test result

**Comment by jsturtevant** [comment]
`pull-kubernetes-e2e-aks-engine-azure-windows` failed due to the required fix in https://github.com/kubernetes/kubernetes/pull/99860

**Comment by marosset** [comment]
/hold cancel

The windows containerd job passed and the windows docker job hit a known failure (which already has a PR out for the fix)

**Pull request merged**
