### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by shiywang**

### CODE REVIEW

**Comment by cblecker** [comment]
LGTM

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41299#-:-Kcnc-Y6T8jJ1_OGqszB:bb6ywmx)*

**Comment by k82cn** [comment]
@k8s-bot ok to test

**Comment by resouer** [comment]
@derekwaynecarr this is a typo fix, please add approve label

**Pull request merged**
