### PR TITLE
update dashboard version

### PR DESCRIPTION
**Pull request by puneetguptanitj**
**What this PR does / why we need it**:
updated dashboard version to 1.7.1

**Release note**:

```release-note
Updated dashboard version to 1.7.1
```

### CODE REVIEW

**Comment by cblecker** [comment]
Is there a reason you're opening this directly against 1.7, as opposed to master?

**Comment by puneetguptanitj** [comment]
oh sorry shall I open against master and cherry pick on 1.7? will do that asap please let me know

**Comment by puneetguptanitj** [comment]
created https://github.com/kubernetes/kubernetes/pull/54262 for master

**Comment by praseodym** [comment]
@puneetguptanitj If you want to update your local cluster, why not do this directly? No need to open a PR.

@cblecker Why is the dashboard (still) available under contrib? The instructions at github.com/kubernetes/dashboard/ are always up to date and also take into account RBAC. It would make more sense to just link to those.

**Pull request closed without merging**
