### PR TITLE
add migration flag in Azure volume CSI migration logic

### PR DESCRIPTION
**Pull request by andyzhangx**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
add migration flag in Azure volume CSI migration logic to **only disallow** in-tree dynamic provisioning in 1.24, while existing in-tree PVs should still keep working

https://github.com/kubernetes/kubernetes/pull/98243#issuecomment-1038795764
> > We(Azure disk & file drivers) would like to Enable both the InTreePluginXXUnregister and CSIMigrationXXX, while block in-tree Azure Disk & file dynamic PV creation, is that possible?
> 
> If you enable both `InTreePluginXXUnregister` and `CSIMigrationXXX`, the XXX intree plugin will not be registered anymore. So there will not be any intree disk & file dynamic PV creation for sure. In fact, if you only enable `InTreePluginXXUnregister`, it will unregister the intree plugin XXX. Adding CSIMigrationXXX to it will enable the CSI migration part for the intree so that if anyone is still using the intree plugin, it can get redirect to CSI driver.
> 
> > One solution could be add one special tag in TranslateInTreePVToCSI func, and return error in CSI CreateVolume func if it's in-tree PV request, does it work?
> 
> I dont think this is necessary, why do you want to do this? Enabling `InTreePluginXXUnregister` and `CSIMigrationXXX` means CSI migration is complete. There will be no intree plugin code used any more

@Jiawei0227 I tried `--feature-gates="CSIMigration=true,CSIMigrationAzureDisk=true,InTreePluginAzureDiskUnregister=true"` with kube-controller-manager, and it could still create dynamic PV by in-tree storage class, I think that's not my original intention.  Is there a way to only disallow dynamic PV by in-tree storage class, while make existing in-tree PV attach/mount working? Looks like I still needs this PR? https://github.com/kubernetes/kubernetes/pull/103768
cc @msau42 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
add migration flag in Azure volume CSI migration logic
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
add migration flag in Azure volume CSI migration logic
```

/assign @msau42
/priority important-soon
/sig cloud-provider
/area provider/azure
/triage accepted

### CODE REVIEW

**Comment by Priyankasaggu11929** [comment]
Hello @andyzhangx, is this PR is for https://github.com/kubernetes/enhancements/issues/1885? 

Thanks!

**Comment by andyzhangx** [comment]
> Hello @andyzhangx, is this PR is for [kubernetes/enhancements#1885](https://github.com/kubernetes/enhancements/issues/1885)?
> 
> Thanks!

@Priyankasaggu11929 no, that's not related.

**Comment by Jiawei0227** [comment]
The idea of `InTreePluginAzureDiskUnregister` is to not register the intree plugin in the volume manager. However, if you enable both InTreePluginAzureDiskUnregister and  CSIMigrationXXX, the intree API will still work. It's just underlying it all goes through the CSI path.

**Comment by msau42** [comment]
Disallowing dynamic provisioning for intree StorageClasses is considered an API breaking change, which is not the intention of CSI migration. As we discussed earlier, if this is something your platform wants to enforce, then an admission webhook or uninstalling the StorageClass would be a better way to achieve this.

cc @jsafrane

**Pull request closed without merging**
