### PR TITLE
Revert "Remove raw binaries from distro that are already included in …

### PR DESCRIPTION
**Pull request by zmerlynn**
See https://github.com/GoogleCloudPlatform/kubernetes/issues/10410#issuecomment-115914531 and chatter after.

Reverts GoogleCloudPlatform/kubernetes#9715

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @ixdy @kelseyhightower @mikedanese

**Comment by mikedanese** [comment]
LGTM

**Comment by kelseyhightower** [comment]
LGTM

**Comment by zmerlynn** [comment]
Should probably go in 0.20.1. #10409

**Pull request merged**
