### PR TITLE
Remove NormalizeScore plugin set from config API.

### LINKED ISSUE #80908: Scheduler Framework: Consolidate NormalizeScore plugin set into Score plugin set in config API
**What would you like to be added**:
Consolidate [NormalizeScore plugin set]((https://github.com/kubernetes/kubernetes/blob/e298fc723f2597697b770f88ce47fe93507f7463/pkg/scheduler/apis/config/types.go#L169)) into Score plugin set in config API. 

**Why is this needed**:
NormalizeScore extension point is implemented in [PR 80383](https://github.com/kubernetes/kubernetes/pull/80383). We decided to treat NormalizeScore as an "optional" step of Score plugin, see [framework initialization logic](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/v1alpha1/framework.go#L145-L147).
However, we deferred the removal of [NormalizeScore plugin set](https://github.com/kubernetes/kubernetes/blob/e298fc723f2597697b770f88ce47fe93507f7463/pkg/scheduler/apis/config/types.go#L169) due to API review delays.

Now that PR was merged. We can start the actual removal from the API and start the API review process.

/sig scheduling

### PR DESCRIPTION
**Pull request by liu-cong**
**What type of PR is this?**
/kind api-change

**What this PR does / why we need it**:
`NormalizeScore` plugin set in the config API is not used by the code. Instead, if user wants to implement `NormalizeScore`, they should configure `ScorePlugin` in the config API and implement `ScoreWithNormalizePlugin` interface.

This API isn't currently in use - the scheduler framework is not fully implemented yet. Therefore changing this API should have little to no impact to users.

More details in [issue](https://github.com/kubernetes/kubernetes/issues/80908).

**Which issue(s) this PR fixes**:

Fixes #80908

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NormalizeScore plugin set is removed from scheduler framework config API. Use ScorePlugin only.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

[Scheduler Framework](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20180409-scheduling-framework.md)

/sig scheduling

### CODE REVIEW

**Comment by liu-cong** [comment]
@bsalamat @ahg-g

**Comment by Huang-Wei** [comment]
FYI @draveness to ensure your ongoing PRs are aligned.

**Comment by erictune** [comment]
You told me offline that you think the scheduler will ignore an unknown field, in the unlikely case that someone chose to put this property in their config file (even though it is a no-op).  Based on that, and the fact it had no effect:
/lgtm
/approve

**Comment by bsalamat** [comment]
> You told me offline that you think the scheduler will ignore an unknown field, in the unlikely case that someone chose to put this property in their config file (even though it is a no-op).

That's right. I created a small example that shows this: https://play.golang.org/p/MoYt50z9BPJ

Please also note that we have not released even the alpha version of the config for NormalizeScore plugins. So, it should be fine to change it.

**Pull request merged**
