### PR TITLE
Alphabetically order the subcommands in kubectl usage text.

### PR DESCRIPTION
**Pull request by madhusudancs**
The usage template defined here is similar to the default template provided
by "cobra", but with a modification to the way commands are listed. I
considered various alternatives, but I think this approach is the least
hacky one.

Ref: #21585

cc @eparis

### CODE REVIEW

**Comment by eparis** [comment]
Why not submit this to cobra?

**Comment by bgrant0607** [comment]
I agree with @eparis

**Comment by jlowdermilk** [comment]
+1 for making this change in cobra

**Comment by eparis** [comment]
Did this ever get sent to cobra? I don't remember seeing/merging it....

**Comment by jlowdermilk** [comment]
Not sure. I closed the pr because there hasn't been activity on it in over a month (k8s-merge-bot just randomly reassigned it to me).

**Comment by eparis** [comment]
merge bot just randomly reassigned every single open PR, because the github API is misbehaving. :-(

**Pull request closed without merging**
