### PR TITLE
Automated cherry pick of #120177: apiextensions-apiserver: generate applyconfigurations

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Cherry pick of #120177 on release-1.28.

#120177: apiextensions-apiserver: generate applyconfigurations

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Requires https://github.com/kubernetes/kubernetes/pull/120442 to pass CI.

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
