### PR TITLE
increase NUM_MINIONS to 3 for e2e + jenkins by default.

### PR DESCRIPTION
**Pull request by brendandburns**
Note this is going to increase our test footprint by 50%

### CODE REVIEW

**Comment by brendandburns** [comment]
@thockin 

RE: https://github.com/GoogleCloudPlatform/kubernetes/issues/10899

**Comment by wojtek-t** [comment]
LGTM

**Comment by dchen1107** [comment]
LGTM. :-)

**Comment by ixdy** [comment]
Note that we need to be careful not to bump into any quota limits in any of our GCP projects. (I can't imagine an additional minion will break anything, but I'll double-check to verify.)

**Pull request merged**
