### PR TITLE
a typo in dockershim.cm.containerManager.doWork

### PR DESCRIPTION
**Pull request by yanxuean**
Signed-off-by: yanxuean <yan.xuean@zte.com.cn>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/sig node

### CODE REVIEW

**Comment by yanxuean** [comment]
/assign @yujuhong @Random-Liu 
@yujuhong @Random-Liu    ping for approve

**Comment by yujuhong** [comment]
Correcting typos is good, but correcting more than one typo in a PR may make the review process more efficient(?).

/lgtm

**Comment by yanxuean** [comment]
> Correcting typos is good, but correcting more than one typo in a PR may make the review process more efficient(?).
OK. I will do it as you said.  
On that day I found the issue and send the pr immediately. It really waste out time.
Thanks:)

**Pull request merged**
