### PR TITLE
Bump CPU requirements of L7 LB controller.

### LINKED ISSUE #56051: L7 LB controller using too much CPU in the 5k-node density test
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

@kubernetes/sig-network-bugs 
@kubernetes/sig-scalability-bugs 
/priority failing-test

**What happened**:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/65 failed with:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:135
Expected error:
    <*errors.errorString | 0xc43b4a73d0>: {
        s: "Container l7-lb-controller-v0.9.7-gce-scale-cluster-master/l7-lb-controller is using 0.704569649/0.6998 CPU",
    }
    Container l7-lb-controller-v0.9.7-gce-scale-cluster-master/l7-lb-controller is using 0.704569649/0.6998 CPU
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:365
```

Attached graph shows that it's not a huge increase from normal usage.
Dear SIG networking, is this expected? Should we just bump the limit?
l7

Please note this is in a release-blocking job.

### PR DESCRIPTION
**Pull request by porridge**
**Which issue(s) this PR fixes**
Fixes #56051

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by shyamjvs** [comment]
Adding 1.9 milestone as this is a bug fix for a release-blocking job (gce-scale-performance).

**Comment by porridge** [comment]
ACK. In progress

**Pull request merged**
