### PR TITLE
Fixed ignoring deployments on first error.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Fixed ignoring of the remaining deployments after the first error in deployment controller & added logging of errors.

### CODE REVIEW

**Comment by ncdc** [comment]
@ironcladlou

**Comment by nikhiljindal** [comment]
LGTM, thanks!

**Comment by nikhiljindal** [comment]
@k8s-oncall Its been more than 2 days since this was LGTM'd. Any idea why @k8s-merge-robot hasnt picked this yet?

**Comment by nikhiljindal** [comment]
Maybe @brendandburns or @lavalamp have some idea?

**Comment by wojtek-t** [comment]
@nikhiljindal - there are 50+ LGTMed PR since few days. It's not that this PR was ignored by merged bot, there were just too many of them to be picked (and still there are).

**Pull request merged**
