### PR TITLE
Remove VolumeSubpath feature gate

### PR DESCRIPTION
**Pull request by saad-ali**
#### What type of PR is this?

/kind cleanup

/kind deprecation

#### What this PR does / why we need it:

Remove the VolumeSubpath feature gate.

Per @liggitt:

Feature gate convention has been [updated](https://github.com/kubernetes/website/commit/0347d2388f59325fd9e8c2de2c2ac3ed1407362d#diff-6a97d17f1e675a9994a1c557b54fda1c3b853227bcf754489b76862e6e4af555R371-R373) since [this feature gate was introduced](https://github.com/kubernetes/kubernetes/commit/f6d97b5d2b139c593991a50064e3aa352600ca39) to indicate that they `are intended to be deprecated and removed after a feature becomes GA or is dropped`.

Also, turning off the gate would make a cluster non-conformant and couldn't reasonably be done by a managed cluster provider without breaking existing users.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
/lgtm

Question 1:  In my impression, there are several subpath-related issues and I did a quick search. Do we have a plan to think about the solution together? I will go through them once I have some reproducing environments.

- https://github.com/kubernetes/kubernetes/issues/97460 (fixed by #98717 in 1.21)
- https://github.com/kubernetes/kubernetes/pull/103837 (needs review for a period)
- https://github.com/kubernetes/kubernetes/issues/101743 (open issue)
- https://github.com/kubernetes/kubernetes/issues/101676
- https://github.com/kubernetes/kubernetes/issues/97031
- #96240 and #98719
- #61446 
- #54487
- #63156  There are some volume subpath related flakes as well.

Question 2:
VolumeSubpath was GAed since 1.10. Besides, VolumeSubpathEnvExpansion was also GAed since 1.17 (6 releases after that). 
Is there a plan to remove it?

**Comment by saad-ali** [comment]
> Question 1: In my impression, there are several subpath-related issues and I did a quick search. Do we have a plan to think about the solution together? I will go through them once I have some reproducing environments.

Good topic for discussion with SIG Storage. Want to add it to the agenda for the next meeting?

**Comment by pacoxu** [comment]
> Good topic for discussion with SIG Storage. Want to add it to the agenda for the next meeting?

I need to do some basic code reading and summary before raising it in the meeting. (If the time is not convenient, I may raise the discussion in slack.) Thanks.

**Comment by saad-ali** [comment]
>> Good topic for discussion with SIG Storage. Want to add it to the agenda for the next meeting?
>
> I need to do some basic code reading and summary before raising it in the meeting. (If the meeting time is not convenient for me, I may raise the discussion in slack.) Thanks.

Sounds good!

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Comment by thockin** [comment]
There are issues with subpath, especially wrt projected volumes.  I'd love to see us tackle that.

**Comment by msau42** [comment]
I think we actually need to lock to default, and the deprecate for 2 releases before removing. Will send an update.

**Comment by saad-ali** [comment]
https://github.com/kubernetes/kubernetes/pull/105474 is handling the release note for this PR.

**Pull request merged**
