### PR TITLE
[DO NOT MERGE] turn on kube mutation detector

### PR DESCRIPTION
**Pull request by deads2k**
turns on the kube mutation detector in the controller manager unconditionally to see what happens.

### CODE REVIEW

**Comment by deads2k** [comment]
Well that's suspicious.  No failures.

**Comment by deads2k** [comment]
@wojtek-t @cjcullen I can't be sure, but I wonder if some of our flakes are due to mutations.  Can we find a way to turn this on for e2e tests?

**Comment by kargakis** [comment]
> @wojtek-t @cjcullen I can't be sure, but I wonder if some of our flakes are due to mutations. Can we find a way to turn this on for e2e tests?

Yes, please

**Comment by ncdc** [comment]
I'm working on it.

**Comment by ncdc** [comment]
Replaced by #41326

**Pull request closed without merging**
