### PR TITLE
fix comment error for network plugin

### PR DESCRIPTION
**Pull request by supereagle**
**What this PR does / why we need it**:

**Which issue this PR fixes** : fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by xiangpengzhao — APPROVED** [review]

**Comment by supereagle** [comment]
@k8s-bot test this

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by supereagle** [comment]
@freehan This PR needs your approval :). Thanks.

**Comment by freehan** [comment]
Thanks!

**Pull request merged**
