### PR TITLE
Allocate static-ip through cloudprovider library instead of gcloud

### PR DESCRIPTION
**Pull request by bprashanth**
Fixes https://github.com/kubernetes/kubernetes/issues/33840
https://github.com/kubernetes/kubernetes/issues/33840#issuecomment-255277349 for details

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35331)

### CODE REVIEW

**Comment by bprashanth** [comment]
Another one at Zihong

**Comment by MrHohn** [comment]
Makes sense. LGTM.

For e2e test, I'm also considering whether using `gcloud` command v.s. calling the `gce` package. Seems like better to use the package?

**Comment by MrHohn** [comment]
Wait, do we need to retry when fail?

**Comment by bprashanth** [comment]
Definitely better to use the package, because test-infra team could upgrade gcloud to a version that doesn't support a command. We vendor the cloudprovider/gce package in tree, so it changes when we change it (of course the gce api in the cloud could change, but they usually give us some notice).

**Comment by bprashanth** [comment]
If we see it flaking we can throw in a retry, don't think it will. gcloud is much more likely to flake than the api in general.

**Comment by bprashanth** [comment]
applying LGTM, yell if you'd like me to add the retry before this goes in

**Comment by bprashanth** [comment]
@k8s-bot gci gce e2e test this

**Pull request merged**
