### PR TITLE
Removing unreferenced code in github/com/emicklei

### PR DESCRIPTION
**Pull request by ghost**
The code in pkg github.com/emicklei/examples/ is not referenced in kubernetes
codebase. Somehow it was mirrored in the vendor directory in a previous
PR #25365.

This causes problems for godeps which will then include the reference to this
code in the Godeps.json file (among other packages that are not in the vendors
directory).

Removing the directory and its contents fixes the fissue and we believe the
current godeps process should prevent it from re-occurring.

@quinton-hoole @thockin @brendandburns @lavalamp

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@k8s-bot test this please #IGNORE

**Comment by quinton-hoole** [comment]
@k8s-bot test this please #26026

**Comment by quinton-hoole** [comment]
Aargh!  Grab a random flake issue, as the bot doesn't like my real one.

@k8s-bot test this issue #26026

**Comment by quinton-hoole** [comment]
Hit two flaky tests:

````
STEP: it should get the expected 'RestartCount'
STEP: it should get the expected 'Ready' status
â€¢ Failure [100.417 seconds]
Container runtime Conformance Test
/var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:314
  container runtime conformance blackbox test
  /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:313
    when start a container that exits successfully
    /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:143
      it should run with the expected status [Conformance] [It]
      /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:142

      Expected
          <bool>: true
      to equal
          <bool>: false

      /var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:129
````

and

```
Summarizing 1 Failure:

[Fail] Container runtime Conformance Test container runtime conformance blackbox test when start a container that exits successfully [It] it should run with the expected status [Conformance] 
/var/lib/jenkins/workspace/node-pull-build-e2e-test@2/go/src/k8s.io/kubernetes/test/e2e_node/runtime_conformance_test.go:129

Ran 16 of 16 Specs in 416.475 seconds
FAIL! -- 15 Passed | 1 Failed | 0 Pending | 0 Skipped I0523 21:43:12.525926    2667 e2e_node_suite_test.go:94] Tests Finished
```

**Comment by quinton-hoole** [comment]
@k8s-bot test this issue #25812

**Comment by lavalamp** [comment]
@k8s-oncall After tests pass on this, manual merge is probably in order.

**Comment by quinton-hoole** [comment]
@mhrgoog On the final test run it looks like one of the storage integration tests timed out.  I'll try to find the issue tracking that, and rerun the tests in the mean time.

```
E0523 22:12:02.268570   29064 controller_base.go:259] PersistentVolumeController could not update claim "default/fake-pvc": persistentvolumeclaims "fake-pvc" not found
panic: test timed out after 10m0s

goroutine 19857 [running]:
panic(0x1b5e200, 0xc82a5a1b10)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 7 minutes]:
testing.RunTests(0x2940538, 0x3567fa0, 0x32, 0x32, 0xc8202c5501)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc823baff08, 0xc820172d80)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	k8s.io/kubernetes/test/integration/_test/_testmain.go:152 +0x117
```

**Comment by quinton-hoole** [comment]
@k8s-bot test this issue#25967

**Comment by quinton-hoole** [comment]
@k8s-bot test this issue: #25967

**Comment by quinton-hoole** [comment]
Thanks @mikedanese !

**Pull request merged**
