### PR TITLE
Rewrite events registry to be generic

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #12207

### CODE REVIEW

**Comment by wojtek-t** [comment]
@nikhiljindal - since you reviewed the previous PRs from the serious - can you please take a look into this one too?

**Comment by nikhiljindal** [comment]
Mostly looks good. Added a few comments. Needs rebase.

**Comment by wojtek-t** [comment]
@nikhiljindal - thanks for review

PTAL

**Comment by nikhiljindal** [comment]
Thanks for the fixes.
LGTM

**Pull request merged**
