### PR TITLE
Add metric collection to cluster/juju for autoscalling

### PR DESCRIPTION
**Pull request by marcoceppi**
**What this PR does / why we need it**:

This exposes the following metrics to the juju model:

 * persistentvolumeclaims
 * pods
 * replicationcontrollers
 * persistentvolume
 * services
 * nodes
 * replicasets
 * serviceaccounts

Using these values an autoscaler can be implemented to help to scale the infrastructure layer.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

Once deployed, issue the following command to confirm metrics are being collected:

```
juju metrics kubernetes-master
```

The result should be:

```
UNIT                               TIMESTAMP                    METRIC  VALUE
kubernetes-master/0     2017-02-23T21:04:34Z               deployments      0
kubernetes-master/0     2017-02-23T21:04:34Z                     nodes      1
kubernetes-master/0     2017-02-23T21:04:34Z                      pods      2
kubernetes-master/0     2017-02-23T21:04:34Z               replicasets      0
kubernetes-master/0     2017-02-23T21:04:34Z    replicationcontrollers      2
kubernetes-master/0     2017-02-23T21:04:34Z                  services      2
kubernetes-master/0     2017-02-23T21:04:34Z           serviceaccounts      0
```

**Release note**:

```release-note
Juju: Expose key kubernetes metrics to enable autoscaling
```

### CODE REVIEW

**Comment by marcoceppi** [comment]
I signed it!

**Review by cmars — APPROVED** [review]

**Comment by marcoceppi** [comment]
@k8s-bot cvm gce e2e test this

Not sure why this test is failing, let's retry.

**Comment by jsafrane** [comment]
I don't know anything about juju, I am not sure why the bot thinks I am the right assignee.

**Comment by marcoceppi** [comment]
@k8s-bot non-cri e2e test this

**Comment by mbruzek** [comment]
I approve of these changes to the yaml files in the Juju directory.

/approve

**Comment by marcoceppi** [comment]
@k8s-bot non-cri node e2e test this

**Comment by marcoceppi** [comment]
@k8s-bot bazel test this

**Comment by marcoceppi** [comment]
@k8s-bot unit test this

**Comment by marcoceppi** [comment]
@k8s-bot cvm gke e2e test this

**Comment by marcoceppi** [comment]
@k8s-bot gci gke e2e test this

**Comment by marcoceppi** [comment]
@k8s-bot cvm gke e2e test this
@k8s-bot gci gke e2e test this

**Comment by marcoceppi** [comment]
@k8s-bot cvm gke e2e test this
@k8s-bot gci gke e2e test this

**Comment by marcoceppi** [comment]
Superceeded in #44500

**Pull request closed without merging**
