### PR TITLE
Print creation time when viewing the details of a rollback version info。

### PR DESCRIPTION
**Pull request by lijinfeng2011**
Before performing the rollback operation, you need to obtain the creation time of the corresponding version to determine whether to roll back this version.

The instructions involved are: kubectl rollout history TYPE NAME -- revision=ID

------
When the option “--revision” is used, “-o yaml” does not take effect.
So far, there is no way to get the revision's created time. This modification can temporarily solve this problem.

### CODE REVIEW

**Comment by dims** [comment]
@lijinfeng2011 needs a CLA

**Comment by dims** [comment]
This PR needs a CLA to make progress, please see comments above from the CLA bot(s)

**Comment by dims** [comment]
There is a cncf-cla:no label on this PR. Can you please see the bot comments above to fix the CLA? This PR cannot progress unless the bot is happy with the CLA situation

**Comment by lijinfeng2011** [comment]
check CLA  @k8s-ci-robot

**Comment by lijinfeng2011** [comment]
> 



> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

check CLA @k8s-ci-robot

**Comment by lijinfeng2011** [comment]
cncf-cla: yes @dims

**Pull request closed without merging**
