### PR TITLE
Internal types must be registered in their group version

### PR DESCRIPTION
**Pull request by smarterclayton**
DeleteOptions is required to be set

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31985)

### CODE REVIEW

**Comment by smarterclayton** [comment]
@bprashanth @pwittrock 

Because this is not set we can get errors in certain resolution cases.  This is required for 1.4 for conversion / registration to work correctly.

**Comment by bprashanth** [comment]
Thanks LGTM, we cut 1.4 so we need to cherrypick. Applied label.

**Comment by pwittrock** [comment]
@bprashanth We were planning on fast-forwarding and taking all commits from master.  There has been a lot of confusion around this, so it may not be a viable strategy anymore.

**Comment by smarterclayton** [comment]
Let me know what to do - will open a PR or hold tight.

**Comment by pwittrock** [comment]
@smarterclayton hold tight, I need to get a better understanding of the state of the system

**Comment by pwittrock** [comment]
@smarterclayton plan is to ff the branch, so no need for a cherry-pick pr

**Comment by smarterclayton** [comment]
Thanks

**Pull request merged**
