### PR TITLE
Automated cherry pick of #34524

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #34524 on release-1.2.
#34524: Test x509 intermediates correctly

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35260)

### CODE REVIEW

**Comment by roberthbailey** [comment]
let's see if our automation for this ancient branch still works...

**Comment by roberthbailey** [comment]
@zmerlynn fyi

**Comment by liggitt** [comment]
well, more of those worked than I expected. the unit test failures are unrelated:
```
fatal: Not a valid object name upstream/release-1.1
...
I1020 21:58:45.616] Verifying ./hack/../hack/verify-flags-underscore.py
I1020 21:59:07.144] Found illegal 'flag' usage. If these are false positives you should run `hack/verify-flags-underscore.py -e > hack/verify-flags/exceptions.txt` to update the list.
I1020 21:59:07.144] .gsutil/credstore:        "api_version": "v1"
```

and the tests on the changed package run cleanly:
```
$ go test ./plugin/pkg/auth/authenticator/request/x509
ok  	k8s.io/kubernetes/plugin/pkg/auth/authenticator/request/x509	0.037s
```

**Comment by roberthbailey** [comment]
I'm going to manually merge and keep an eye on https://k8s-testgrid.appspot.com/google-gce#gce-release-1.2 to make sure everything looks ok before cutting a new release.

**Pull request merged**
