### PR TITLE
Safe encode template hash value to make it consistent with resource name

### LINKED ISSUE #66093: Workload controller's template hash label and resource names inconsistency
/kind bug
/sig apps 

From https://github.com/kubernetes/website/issues/7577. 

We used template hash value to create unique & idempotent resources names in workloads controllers. For example, Deployment creates RS with name `<deployment-name>-<hash>`. Since 1.8, those names are safely encoded, e.g. becomes `<deployment-name>-<safe-encoded-hash>`, but the hash value used  for pod-template-hash label isn't safely encoded. This makes them inconsistent and may cause user confusion.

### PR DESCRIPTION
**Pull request by janetkuo**
**What this PR does / why we need it**: 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #66093

**Special notes for your reviewer**: It's safe to change the function that generates template hash label, because this value is only used when creating a resource and never updated or compared. Therefore, it won't break existing workloads after k8s upgrade/downgrade. Note that we've changed hash before when introducing hash collision avoidance mechanism. 
@kubernetes/sig-apps-pr-reviews 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by krmayankk** [comment]
@janetkuo when you say safe what do you mean ? Would upgrade cause existing pods/workloads to be deleted/restarted or orphaned ?

**Comment by janetkuo** [comment]
> when you say safe what do you mean ? Would upgrade cause existing pods/workloads to be deleted/restarted or orphaned ?

@krmayankk because the generate pod-template-hash label value will be different, I need to clarify that it won't affect existing pod-template-hash label value, and the value won't be used for comparison. In summary, existing workloads won't be affected after upgrade and therefore is safe.

**Review by kow3ns — APPROVED** [review]
Might want to consider not renaming all of the functions from Hash* to SafeEncodeHash*. The encoding of the computed hash is probably not a concern that warrants a mention in the name of the method.

**Comment by janetkuo** [comment]
Squashed commits. Re-applying lgtm label.

**Comment by lf1029698952** [comment]
excuse me, which version will be released include this fix?

**Pull request merged**
