### PR TITLE
Automated cherry pick of #83301: e2e: on aws, tag volumes we want the cluster to mount

### PR DESCRIPTION
**Pull request by rifelpet**
Cherry pick of #83301 on release-1.16.

#83301: e2e: on aws, tag volumes we want the cluster to mount

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

I'd like this to be in 1.16 because the Kops test jobs that use the Kubernetes 1.16 E2E tests [are failing](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kops/8049/pull-kops-e2e-kubernetes-aws-1-16/1202311785290403840/) with the same issue that #83301 fixed in 1.17.

/kind bug
/kind failing-test

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
/lgtm

> NONE

ideally cherry-picks should always have a release note.

**Comment by tpepper** [comment]
/priority critical-urgent
from parent PR

**Comment by justaugustus** [comment]
Looks like [this job was recently added](https://github.com/kubernetes/test-infra/pull/15705) and hasn't yet run against this PR:
/test pull-kubernetes-e2e-gce-100-performance

**Comment by rifelpet** [comment]
@justaugustus any chance this can land before tomorrow's cherry-pick deadline? I'm not sure what the next steps are.

**Pull request merged**
