### PR TITLE
kubeadm-init: update note about failing containers

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:

This PR was merged before all requested changes
were applied:
kubernetes/pull/59731

Update the note about failing containers as requested here:
https://github.com/kubernetes/kubernetes/pull/59731#pullrequestreview-119517427

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
NONE

**Special notes for your reviewer**:
NONE

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews
/sig cluster-lifecycle
/area kubeadm
@luxas

**Review by luxas — APPROVED** [review]
/lgtm
/approve

Thanks @neolit123!

**Review by luxas — APPROVED** [review]
/lgtm

**Comment by neolit123** [comment]
hm, `The PR was changed after the lgtm label was added.` but the label is there already :thinking:

**Review by luxas — APPROVED** [review]
/approve
/lgtm

**Comment by luxas** [comment]
/lgtm

Very strange, trying again... Seems like some bug in the bot machinery

**Pull request merged**
