### PR TITLE
Remove ability to re-enable serving deprecated APIs

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind api-change
/kind cleanup

**What this PR does / why we need it**:
Removes ability to re-enable serving deprecated extensions/v1beta1, apps/v1beta1, and apps/v1beta2 types

**Which issue(s) this PR fixes**:
xref #43214

**Does this PR introduce a user-facing change?**:
```release-note
kube-apiserver no longer serves the following deprecated APIs:
* All resources under `apps/v1beta1` and `apps/v1beta2` - use `apps/v1` instead
* `daemonsets`, `deployments`, `replicasets` resources under `extensions/v1beta1` - use `apps/v1` instead
* `networkpolicies` resources under `extensions/v1beta1` - use `networking.k8s.io/v1` instead
* `podsecuritypolicies` resources under `extensions/v1beta1` - use `policy/v1beta1` instead
```

/cc @smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
looks ok to me, rebase and I'll tag.  double checked the messages to consumers in previous changelogs to make sure we were consistent

**Comment by liggitt** [comment]
rebased

**Pull request merged**
