### PR TITLE
cronjob-controller: Forget synced work item

### PR DESCRIPTION
**Pull request by fischor**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

With this PR a successfully synced work queue item in the CronjobController will be removed from the rate limiter of the work queue. Currently `queue.Forget` is not called for successful synced items and thus these are kept in the rate limiter.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by FillZpp** [comment]
Nice catch!
/triage accepted

**Comment by fischor** [comment]
/cc @soltysh 
/cc @smarterclayton 
Ping

**Pull request closed without merging**
