### PR TITLE
Add validation for affinities and taints/tolerations annotations.

### PR DESCRIPTION
**Pull request by aveshagarwal**
It fixes annotations validation issues for pod/node affinities and taints/tolerations annotations for 1.5 to 1.6 upgrade tests as discussed in the issue https://github.com/kubernetes/kubernetes/issues/43228 .

@davidopp @derekwaynecarr @kubernetes/sig-scheduling-pr-reviews

### CODE REVIEW

**Comment by davidopp** [comment]
/lgtm
/approve

Thanks for doing this so quickly!

@derekwaynecarr suggested that we make a comment (maybe in each of the three places where you define consts at the top) that this should not be removed until two releases after we stop supporting alpha annotation, do to the two-version master-kubelet skew policy. But you can add that in a followup PR--definitely not needed for the release.

**Comment by aveshagarwal** [comment]
Had to update for auto generated stuff.

**Comment by davidopp** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
