### PR TITLE
Scheduler: remove duplicated error log in framework

### PR DESCRIPTION
**Pull request by gavinfish**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Originated from https://github.com/kubernetes/kubernetes/pull/98266#discussion_r562104219. Dig a bit deeper, just find out `RunPreFilterPlugins`, `RunPreScorePlugins` and `RunScorePlugins` are also only called in `scheduleOne` which will log the returned error and pod info. There is no need to log these errors twice.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
/assign @ahg-g 

I think we discussed this before and decision was to keep them?

**Comment by ahg-g** [comment]
I am ok with removing them, this isn't a pattern we are following across the pkg.

**Review by alculquicondor — COMMENTED** [review]
/approve

**Pull request merged**
