### PR TITLE
Update otelhttp dependency from v0.35.0 to v0.37.0

### PR DESCRIPTION
**Pull request by dashpole**
/kind bug

#### What this PR does / why we need it:

This bumps the otelhttp dependency from v0.35.0 to v0.37.0.

When API Server Tracing was enabled by default prior to the 1.26 release, it caused https://github.com/kubernetes/kubernetes/issues/113791.  This was ultimately due to https://github.com/open-telemetry/opentelemetry-go-contrib/issues/2982, which was fixed by https://github.com/open-telemetry/opentelemetry-go-contrib/pull/2983, and released in otelhttp v0.37.0.

#### Which issue(s) this PR fixes:

Fixes the underlying problem from https://github.com/kubernetes/kubernetes/issues/113791.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

- KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/647-apiserver-tracing

### CODE REVIEW

**Comment by dashpole** [comment]
cc @logicalhan @dgrisonnet

**Comment by dims** [comment]
looks like it needs something else

```
vendor/go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/otlpconfig/envconfig.go:84:13: undefined: envconfig.WithTLSConfig
vendor/go.opentelemetry.io/otel/exporters/otlp/otlptrace/internal/otlpconfig/envconfig.go:85:13: undefined: envconfig.WithTLSConfig
```

**Comment by dashpole** [comment]
Looks like this is blocked by https://github.com/kubernetes/kubernetes/issues/113366.

I'm going to close this for now, and retry once that makes progress.

**Pull request closed without merging**
