### PR TITLE
Remove docker as container runtime for local-up-cluster.sh

### PR DESCRIPTION
**Pull request by adisky**
Signed-off-by: Aditi Sharma <adi.sky17@gmail.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Dockershim as runtime is removed from k/k removing the same from local-up-cluster.sh and setting default to containerd

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by adisky** [comment]
Need to migrate pull-kubernetes-local-e2e test to use containerd

**Comment by ehashman** [comment]
> Need to migrate `pull-kubernetes-local-e2e` to use containerd

We are dealing with migrating presubmits later (https://github.com/kubernetes/test-infra/issues/24620), we can ignore any optional presubmits that rely on right now. I'll manually test it.

/triage accepted

**Comment by ehashman** [comment]
flake https://github.com/kubernetes/kubernetes/issues/106904

/retest-required
/skip

**Review by ehashman — COMMENTED** [review]
/lgtm

Worked when I pulled it down locally.

@adisky can you please update the presubmit job as needed in test-infra?

**Comment by adisky** [comment]
I would work on the script tomorrow, the problem is the script is working but its tricky to migrate `pull-kubernetes-local-e2e`  on containerd as this job runs `hack/local-up-cluster.sh` inside a kubekins image which installs docker on debian managed with init.d, docker daemon rewriting the containerd config with each restart, so it is difficult to keep the containerd config until docker is running, currently looking on ways how to resolves this

**Comment by adisky** [comment]
The job `pull-kubernetes-local-e2e` is passing if requirement of at least two nodes skipped 
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106909/pull-kubernetes-local-e2e/1472786081060491264/

The `pull-kubernetes-local-e2e` needs to migrated to use containerd by installing CNI in kubekins image or use a new image with proper containerd installation it is passing, tested locally as well, created a separate issue to track the job migration
https://github.com/kubernetes/test-infra/issues/24715

currently keeping the CNI installation part in the script to have some reference, if its ok to merge the script with CI job migration in progress will remove CNI installation part

/cc @dims

**Comment by aojea** [comment]
> /test pull-kubernetes-local-e2e

it works now :smile: :+1:

**Comment by adisky** [comment]
@pacoxu @hakman @aojea can you add an lgtm again?

**Comment by hakman** [comment]
Unrelated flake in `pull-kubernetes-integration`:
```
FAIL: TestCronJobLaunchesPodAndCleansUp
```
/skip

**Pull request merged**
