### PR TITLE
CHANGELOG fix some format error of changelog1.24

### PR DESCRIPTION
**Pull request by yangjunmyfm192085**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
 fix some format error of changelog1.24
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
 "NONE"
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by yangjunmyfm192085 — COMMENTED** [review]
/cc @AuraSinis

**Review by yangjunmyfm192085 — COMMENTED** [review]
/cc @csantanapr

**Review by yangjunmyfm192085 — COMMENTED** [review]
/assign @cici37
Could you please take a look, does this need to be optimized?
thanks.

**Comment by cici37** [comment]
/lgtm
/approve
Thanks

**Pull request merged**
