### PR TITLE
Debug problems encountered in #43702

### PR DESCRIPTION
**Pull request by wojtek-t**

### CODE REVIEW

**Comment by wojtek-t** [comment]
@thockin @bowei - can you please take a look if that makes sense to you? Before submitting I should remove the second commit, but that's probably useful for you to see how I'm testing this.

**Comment by bowei** [comment]
It looks ok to me

/lgtm

**Comment by bowei** [comment]
Oh yeah -- don't merge ! :-)

**Comment by thockin** [comment]
I guess I don't have any better way to do it, as long as kube-proxy only binds to localhost

**Comment by wojtek-t** [comment]
I removed the second commit - now this PR only contains e2e test changes.

I'm removing do-not-merge label and repplying lgtm label. Thanks for looking into it!

**Pull request merged**
