### PR TITLE
using Infof instead of Info in /test/images

### PR DESCRIPTION
**Pull request by mysunshine92**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

 /kind bug

**What this PR does / why we need it**:
using Infof instead of Info, we properly format the log string.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mysunshine92** [comment]
ping @mattjmcnaughton

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/ok-to-test

Thanks for this fix :)

**Comment by mattjmcnaughton** [comment]
One small note - if you can, please update the pr with why this change is needed :) (i.e. by using `Infof` instead of `Info`, we properly format the log string).

**Comment by mysunshine92** [comment]
> using `Infof` instead of `Info`, we properly format the log string)

thanks for your suggestion, i will modify it.

**Comment by mysunshine92** [comment]
cc @listx 
please add an approved  label ,thanks.

**Comment by listx** [comment]
@mysunshine92 Doesn't Infof take 2+ arguments? Not sure what this is fixing.

If I am wrong, can you please explain why the existing code is wrong in the commit message? Thanks

**Comment by cblecker** [comment]
This isn't needed. The `fmt.Sprintf` inside the Info statement handles the formatting.

/close

**Comment by listx** [comment]
> This isn't needed. The `fmt.Sprintf` inside the Info statement handles the formatting.

Thanks for the clarification @cblecker 

> 
> /close

**Pull request closed without merging**
