### PR TITLE
Fix comment typo

### PR DESCRIPTION
**Pull request by chymy**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Fix comment typo for `NewCPUSetInt64` func in `pkg/kubelet/cm/cpuset/cpuset.go`
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by yangjunmyfm192085 — COMMENTED** [review]
/lgtm

**Review by yangjunmyfm192085 — COMMENTED** [review]
It is recommended to check all cm modules, and the wrong description is submitted in one pr

**Review by ehashman — COMMENTED** [review]
/priority backlog
/triage accepted
/lgtm

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
