### PR TITLE
Fix default regular expressions in conformance tests runner

### LINKED ISSUE #88640: defaultFocus and serialTestsRegexp when building ginkgo command for conformance tests are incorrect
**What happened**:
When using sonobuoy to run some community tests, I realized that ginkgo was not invoked properly. More precisely, when invoking sonobuoy like this:
```
sonobuoy run --wait --kube-conformance-image-version v1.18.0-beta.0 --e2e-focus '\[Feature:NetworkPolicy\]' --e2e-skip '' --e2e-parallel y
```
I saw the following in the sonobuoy logs:
```
Executable path: /usr/local/bin/ginkgo
Args (comma-delimited): /usr/local/bin/ginkgo,--p,--focus=\[Feature:NetworkPolicy\],--skip=[Serial],--noColor=true,/usr/local/bin/e2e.test,--,--disable-log-dump,--repo-root=/kubernetes,--provider=local,--report-dir=/tmp/results,--kubeconfig=,--progress-report-url=http://localhost:8099/progres
```

Because I am running the tests in parallel, and sonobuoy does not set `E2E_SKIP`, the code defaults to `serialTestsRegexp` (see https://github.com/kubernetes/kubernetes/blob/master/cluster/images/conformance/go-runner/const.go#L66) for `--skip`, and `serialTestsRegexp` is set to `[Serial]`. This is not the intended regex (should be `\[Serial\]`) and all the tests are skipped (because all test names have an `e`).

**What you expected to happen**:
`--skip` should be set to `\[Serial\]` so that only the tests with the `[Serial]` "tag" are skipped.

**How to reproduce it (as minimally and precisely as possible)**:
Use the sonobuoy command provided above.

**Environment**:
`Sonobuoy Version: v0.17.2`

### PR DESCRIPTION
**Pull request by antoninbas**
`[Serial]` should be `\[Serial\]`
`[Conformance]` should be `\[Conformance\]`

Fixes #88640

### CODE REVIEW

**Comment by BenTheElder** [comment]
I haven't used the go runner yet but on a glance this seems right, thanks!
/ok-to-test

**Comment by antoninbas** [comment]
Could I get a review on this? Anything else required from my side?

**Comment by johnSchnake** [comment]
Have you any documented case of this causing a problem?

I don't recall (and can't find any history) on the exact choice of escaping values but Sonobuoy has been using the default go runner for some time now. By default Sonobuoy does specify the E2E_FOCUS/SKIP values so I just tried it without setting them and still had no problem.

```
            "env": [
                {
                    "name": "E2E_PARALLEL",
                    "value": "1"
                },
                {
                    "name": "E2E_USE_GO_RUNNER",
                    "value": "true"
                },
                {
                    "name": "E2E_DRYRUN",
                    "value": "true"
                }
            ],
```

Resulted in the execution of:

```
Executable path: /usr/local/bin/ginkgo
Args (comma-delimited): /usr/local/bin/ginkgo,--focus=\[Conformance\],--skip=,--noColor=true,--dryRun=true,/usr/local/bin/e2e.test,--,--disable-log-dump,--repo-root=/kubernetes,--provider=local,--report-dir=/tmp/results,--kubeconfig=
...
...
Random Seed: 1583351287 - Will randomize all specs
Will run 276 of 4897 specs
```

I don't see any issue with the existing code, but can't completely account for the introduction of the single `\` introduced in the above output.

We are feeding the data straight into `exec.Command` so regardless I think the single `\` is correct, not the double `\\` which would be if we were executing the command via a bash shell or something like that, right?

**Comment by johnSchnake** [comment]
Make sense now actually; its the Dockerfile itself defaulting the value: https://github.com/kubernetes/kubernetes/pull/79284/files#diff-005065ae78993487cd82e05d33593e39R25

So if the yaml doesnt specify it the Dockerfile initializes it to the single-slash escaped value.

If you want to update this value to match, that's fine. Just remove one of the slashes.

**Comment by antoninbas** [comment]
Hi @johnSchnake, thanks for checking this out. The linked issue (https://github.com/kubernetes/kubernetes/issues/88640) has the sonobuoy command that led me to observe this problem.

For your experiment, you may want to try setting the `E2E_PARALLEL` env variable to `"true"` and not `"1"`. It seems that the code only accepts `"y"`, `"Y"` and `"true"`: https://github.com/kubernetes/kubernetes/blob/master/cluster/images/conformance/go-runner/cmd.go#L35.

Finally, the double backslash is required. You need to escape backslashes in Go strings (`\[Serial\]` is not a valid Go string), that doesn't mean that ginkgo will actually be invoked with `\\`. See https://play.golang.org/p/d4kOT1icy3v for an example.

BTW, this is a separate issue, but it seems that this line in the Dockerfile (`ENV E2E_PARALLEL="1"`) will not do what you intend based on the observation above.

**Comment by johnSchnake** [comment]
> Finally, the double backslash is required. You need to escape backslashes in Go strings

Ah yup, you're right. I often use backticks to avoid my inevitable confusion. Either way is fine though with me.

And thanks for the reference to the linked issue; I was focusing on the 'focus' value and not the serial-skipping value. I can see why that would apply here.

/lgtm

**Comment by dims** [comment]
/milestone v1.18

this is clearly a bug so let's get this into 1.18 itself.

**Pull request merged**
