### PR TITLE
Automated cherry pick of #14746 upstream release 1.1

### PR DESCRIPTION
**Pull request by jszczepkowski**
Fixed ignoring the rest of deployments after the first error in deployment controller & added logging of errors.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
Cherry-pick of #14746.

**Comment by nikhiljindal** [comment]
Thanks @jszczepkowski!

I assume you followed steps as given in https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md?

I will recommend renaming the PR to "Automated cherry pick of #14746 upstream release 1.1"
I dont see it mentioned in that doc, but thats the format I see everyone is following.

**Comment by jszczepkowski** [comment]
@nikhiljindal 

I've followed the cherry pick instructions. The title was generated automatically, I've changed it to follow you suggestion.

**Comment by nikhiljindal** [comment]
LGTM, thanks!

**Pull request merged**
