### PR TITLE
apiserver: Update a comment

### PR DESCRIPTION
**Pull request by yamt**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design

/kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by yamt** [comment]
what to do with the release-note-label-needed label? maybe i should not have marked this `/kind documentation` in the first place? is `cleanup` more appropriate for this kind of change?

**Comment by apelisse** [comment]
You don't need a release note, so you can just do ...
/release-note-none

**Comment by yamt** [comment]
@apelisse thank you

**Pull request merged**
