### PR TITLE
Revert "Push server docker images during the release"

### LINKED ISSUE #19044: Jenkins failing with `build/common.sh: No such file or directory`
Logs:
```
go run ./hack/e2e.go -v --down
18:37:00 2015/12/22 18:37:00 e2e.go:303: Running: teardown
18:37:00 /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace@2/kubernetes/hack/e2e-internal/../../cluster/gce/../../cluster/common.sh: line 29: /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace@2/kubernetes/hack/e2e-internal/../../cluster/gce/../../cluster/../build/common.sh: No such file or directory
18:37:00 2015/12/22 18:37:00 e2e.go:309: Error running teardown: exit status 1
```

http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/21725
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/21724

cc @kubernetes/goog-testing

### PR DESCRIPTION
**Pull request by mikedanese**
Reverts kubernetes/kubernetes#18893
Fixes #19044

### CODE REVIEW

**Comment by nikhiljindal** [comment]
LGTM, thanks!

**Comment by nikhiljindal** [comment]
cc @fgrzadkowski @ihmccreery

**Comment by wojtek-t** [comment]
Merging manually to fix all broken builds on Jenkins.

**Comment by fgrzadkowski** [comment]
Thanks for fixing this!

**Pull request merged**
