### PR TITLE
fix iptables/proxier todo

### PR DESCRIPTION
**Pull request by Lion-Wei**
combine only local endpoints sync logic with svc balance chain, make it more simpler. 
fixed TODO in iptables/proxier.go 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
Hi, I appreciate the PR, truly.  But I think this is easier to follow when all the local-only logic is clearly distinct.  I'm going to close this PR, for now, but you could maybe send a PR to remove the todo, or even add a comment explaining that it is a little reptitive, but for the sake of clarity.

**Comment by Lion-Wei** [comment]
Sure, make sense. I will do that, thanks though.

**Pull request closed without merging**
