### PR TITLE
Openstack: fix orphaned route deletion

### PR DESCRIPTION
**Pull request by databus23**
This is a follow-up to #56258 which only got half of the work done.
The OpenStack cloud providers DeleteRoute method fails to delete routes when it can’t find the corresponding instance in OpenStack.

```release-note
OpenStack cloudprovider: Fix deletion of orphaned routes
```

### CODE REVIEW

**Review by FengyunPan2 — APPROVED** [review]
/approve

**Comment by databus23** [comment]
I just noticed there is a potential quirk that could cause valid routes for nodes to be deleted.

If there are two routes with the same `DestinationCIDR` one legit, one orphaned, the current logic will delete both. The legit one will be recreated by the cloud provider but its still undesirable.

I will update the PR and try to prevent this from happening

**Comment by dims** [comment]
/hold

(per last comment from @databus23)

**Comment by databus23** [comment]
Thanks @dims! Can we get this in 1.10.x as I would consider it a bugfix?

**Comment by dims** [comment]
@databus23 sure, please file one https://github.com/kubernetes/community/blob/master/contributors/devel/cherry-picks.md#initiate-a-cherry-pick

**Pull request merged**
