### PR TITLE
Account newly ready replicas as progress

### PR DESCRIPTION
**Pull request by 0xmichalis**
@kubernetes/sig-apps-pr-reviews

### CODE REVIEW

**Comment by kargakis** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
@k8s-bot gce etcd3 e2e test this

**Comment by kargakis** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by kargakis** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by kargakis** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by kargakis** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by smarterclayton** [comment]
LGTM as well

**Pull request merged**
