### PR TITLE
WIP: Replace `group/type/name` syntax with `type.group/name`

### PR DESCRIPTION
**Pull request by smarterclayton**
This combines group and type in potential kubectl commands so that users
would type

```
kubectl get jobs.extensions/name
```

or

```
kubectl get jobs/name
```

and both would resolve to jobs.  In the future, this would support
subresources with

```
kubectl get status.jobs/name
```

or

```
kubectl get status.jobs.extensions/name
```

@bgrant0607 @lavalamp @deads2k this is the logical change for the discussed
revision of kubectl arguments for 1.1.  See the test case for an example.

### CODE REVIEW

**Comment by lavalamp** [comment]
Where would a version go, if one wanted to specify it?

**Comment by thockin** [comment]
Why jobs.extension and not extension.jobs?  How will this play out when we
break up the "core" api into smaller chunks?

**Comment by smarterclayton** [comment]
Version is already defined as `--api-version`.  The version is whatever the preferred negotiated version is.  I think that's orthogonal to type (and also not common).

**Comment by smarterclayton** [comment]
It's `jobs.extensions` because for 99.9% of use cases you're just going to type "jobs" and you'll get the right thing.  You qualify the type only when you have to (or you're being safe), so the ordering is more appropriate to further specificity (in my opinion).

**Comment by smarterclayton** [comment]
If we had to, we could lump version with type - `<subresource>.<resource>.<group>.<version>`.  I think that can be made deterministic just with ordering.

**Comment by smarterclayton** [comment]
Some edge case scenarios:

* `pods.pods.kubernetes.io` (resource + group)
* `pods.pods.pods.kubernetes.io` (subresource + resource + group)

In both of those cases I would ask why you are doing that (at review time), but both should be able to be made unambiguous.

**Comment by bgrant0607** [comment]
@thockin Original discussion was here: https://github.com/kubernetes/kubernetes/pull/14461#issuecomment-147777857

**Comment by deads2k** [comment]
> If we had to, we could lump version with type - <subresource>.<resource>.<group>.<version>. I think that can be made deterministic just with ordering.

I groups can contain dots, then how would you deterministically split that?

**Comment by smarterclayton** [comment]
So future things you might type:

* `pods.containers.k8s.io` (core group)
* `status.pods.containers.k8s.io` (sub resource + core group)
* `pods.extensions.k8s.io` (extension group, convertible to core group)
* `jobs.extensions.k8s.io`

**Comment by bgrant0607** [comment]
Groups and kinds cannot contain dots nor slashes.

**Comment by deads2k** [comment]
> If we had to, we could lump version with type - .... I think that can be made deterministic just with ordering.
> If groups can contain dots, then how would you deterministically split that?

Though I would come down on the side of `--preferred-version` is sufficient for almost all cases

**Comment by deads2k** [comment]
> Groups and kinds cannot contain dots nor slashes.

That would imply that all of @smarterclayton's examples here are invalid: https://github.com/kubernetes/kubernetes/pull/15874#issuecomment-149317562

**Comment by smarterclayton** [comment]
And if groups did have dots, we would still say "you can decide it based on resource".

Also, we can also define aliases for sub resources if we had to `podstatus`, `podproxy`.  I didn't implement sub resources but I believe you can match based on that.

**Comment by smarterclayton** [comment]
They cannot today, even if they could you can still decide based on the ordering of the groups (as they are registered) to determine precedence.  We *must* have group precedence anyway to resolve ambiguity.  I would argue suddenly changing group precedence for something like `pods` because someone added pods to the extensions group is incredibly wrong (breaks backwards compatibility) and that we should carefully design around precedence of groups.

**Comment by smarterclayton** [comment]
Note that every input here must be representable in the internal rest mapper.  There is no opaque value present that we must work around, instead we must iterate through a list of groups, kinds, and versions, and decide what resources are available.

**Comment by bgrant0607** [comment]
Oh, right. We do want groups to be able to contain dots, so they can look like domain names.

**Comment by liggitt** [comment]
> We do want groups to be able to contain dots, so they can look like domain names.

right... `k8s.io`, `openshift.io`, etc

**Comment by bgrant0607** [comment]
I like the subresource alias idea: podstatus.

**Comment by bgrant0607** [comment]
I don't think we need to support heterogeneous API versions on the kubectl command line. Preferred versions should be enough.

**Comment by lavalamp** [comment]
@thockin-- groups for third parties are going to be e.g. "
group.mycompany.com", so it doesn't make sense to put type at the end.

**Comment by lavalamp** [comment]
--api-version totally doesn't work when you have multiple resource types
from multiple groups. I tend to agree that we should get rid of it if at
all possible. But if you have to get a particular version (because e.g.
it's a work-around for a bug), I think the order really has to be
`<subresource>.<type>.<version>.<group>`. Versions and type names should be
distinct such that it will never be ambiguous whether you've specified a
subresource or a version.

**Comment by lavalamp** [comment]
I thought we'd agreed that *groups* may contain dots, e.g. `
mygroup.mycompany.com`

**Comment by lavalamp** [comment]
Ah, we did agree that and you all figured it out already. Great :)

**Comment by thockin** [comment]
I don't follow.

`group.mycompany.com/pod/foobar`

seems more obvious than

`pod.group.mycompany.com/foobar` to me.



An I apologize, it's not my intention to re-adjudicate if this was all
sorted through.  Feel free to tell me to mind my own damned business.

**Comment by smarterclayton** [comment]
The addition of the slash prevents future addition of things like namespace
(without being totally insane).  We feel that specifying group (and api
version) explicitly is a 10% path.  Therefore, to preserve the future
ability to say "namespace / type / name" (which was always our intent) we
would prefer to keep the resource and group info together in type.  Some
percentages

* 95% the short form or the singular form (svc, pod, rc)
* 4% the longer form with the group to separate an experimental (or
extension) from a regular (pods.extensions.k8s.io vs pods.core.k8s.io)
* 1% including API version

W.r.t. APIVersion, what scenario do you envision where a user *must*
disambiguate a type across versions but not be able to use --api-version?
And is that ever a multiple resource context?  I agree that having it all
be together is better in many cases.

If I were designing this for humans, I would expect that the following are
all logically identical (and that users wouldn't be surprised at this)

* pods
* pod
* pods.k8s.io
* pods.v1.k8s.io

I feel like API version bridges group and type, so I'd argue that it's
slightly more correct to say "pods.v1.k8s.io" (pod, which is in v1 of the
k8s.io API group) than "v1.pods.k8s.io" (the v1 version of the API group
that pods are in, which is k8s.io).

I also feel that we could reasonably reject the following input:

* pods.v1.k8s
* pods.k8s

We could potentially identify version and sub resource via different
separator characters (I guess...)

* pods.k8s.io:v1
* pods.k8s.io-v1
* pods.k8s.io@v1
* pods@v1
* status:pods.k8s.io
* status:pods.k8s.io@v1

or alias for known types:

* podstatus
* podstatus.k8s.io

**Comment by thockin** [comment]
I'll bow out now.  Clearly consideration has been paid.

**Comment by caesarxuchao** [comment]
I guess the discussion here are specific to kubectl, and we ***aren't*** going to refactor the TypeMeta.APIVersion field to contain string "version.group" rather than "group/version"?

**Comment by JanetKuo** [comment]
This seems related to some other PRs. To summarize:
- #14383 (--preferred-versions): do we still need preferred-versions? or we only need to specify group and version information as `type.version.group/name`?
- #15808 (kubectl explain): we also use dot to specify fields (`kubectl explain pods.spec.nodeName`); how do we add group and version to it? (perhaps we use other symbol to specify fields?)
- #15796 (kubectl api-versions): should we return `group/version` or `version.group`?

**Comment by smarterclayton** [comment]
Well, once we pick a format for apiversion is is forever.  It's possible we
can say apiversion could be "v1" or "v1.k8s.io" or "v1.extensions".  Group
and version are both implicit when calling to an apiserver endpoint.  We
can still reduce the v1 group to "".

It means clients can't naively convert version and group to a URL, which
might be a good thing.

It's worth considering before we commit 1.1 forever.

On Oct 19, 2015, at 8:09 PM, Chao Xu <notifications@github.com> wrote:

I guess the discussion here are specific to kubectl, and we *aren't* going
to refactor the TypeMeta.APIVersion field to contain string "version.group"
rather than "group/version"?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/15874#issuecomment-149381856>
.

**Comment by smarterclayton** [comment]
I'm debating the use case when we need to specify an API version as part of
a multiple value input.  That would involve us removing a resource from a
group (say we removed pods in v2) and then reintroduce it later (say v3)
meaning something different, where users can access both "old" and "new"
pods at the same time.  Since by our conventions pods must be visible at
the same path (/pods/) under both API versions, the input would be to the
CLI instead.  What would the CLI do with that information?  Use it to
display a different "-o yaml" output?  I have to say in this case I would
rather say "use --api-version".  I just don't expect version input to
factor in.

@lavalamp, can you clarify your scenario more?

If we don't need version in kubectl as part of an arg (composed in the same
string), then the complexity here is reduced.

**Comment by bgrant0607** [comment]
I'm in favor of reverting the slash syntax since we don't need to require `experimental/` for 1.1, and take our time on introducing new syntax in 1.2.

**Comment by smarterclayton** [comment]
The second commit (non reversion) verifies the proposed behavior.  If we are comfortable with simply the reversion of the slash syntax in kubectl for 1.1 I'll split that into a separate pull.

**Comment by lavalamp** [comment]
APIs and CLIs are forever, so maybe we shouldn't commit too hastily.

**Comment by thockin** [comment]
that makes me happy cuz I still hate the syntax

**Comment by smarterclayton** [comment]
Obviously the solution is https://tools.ietf.org/html/rfc3986, because I
need to be able to generically identify anything.

**Comment by smarterclayton** [comment]
Put the revert into #16054

**Comment by bgrant0607** [comment]
@smarterclayton Were you serious or kidding about URIs? So far we've not used URIs for anything (e.g., ObjectReference), though a number of people have suggested them. We've mostly avoided complex position-sensitive syntaxes so far (until this issue), which I think has facilitated evolution of the system.

**Comment by smarterclayton** [comment]
It was indeed a joke, arguments should be use case and human driven, not generic constructs created in a vacuum.

**Pull request closed without merging**
