### PR TITLE
added short names for resources which are exposed during discovery

### PR DESCRIPTION
**Pull request by p0lyn0mial**
**What this PR does / why we need it**:
The changes add short names for resources. The short names will be delivered to kubectl during discovery.

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
@deads2k please take a look at the changes.

**Comment by deads2k** [comment]
Wire a `test-cmd.sh` using `kubectl get --raw` to make sure at least one of these shortcuts is exposed properly and this lgtm.

**Comment by deads2k** [comment]
@k8s-bot ok to test

**Comment by deads2k** [comment]
You'll need to `hack/update-bazel.sh` (feed the machine!) and I suspect you've got a break in a unit test somewhere.

**Comment by deads2k** [comment]
@k8s-bot cross build this

**Pull request merged**
