### PR TITLE
Add version cache for cri APIVersion

### PR DESCRIPTION
**Pull request by resouer**
ref https://github.com/kubernetes/kubernetes/issues/29478
1. Added a version cache for `APIVersion()` by using object cache., with ttl=1 min
2. Leaving `Version()` as it is today

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34332)

### CODE REVIEW

**Comment by resouer** [comment]
cc @yujuhong

**Comment by feiskyer** [comment]
LGTM

**Comment by resouer** [comment]
@k8s-bot verify test this

**Comment by yujuhong** [comment]
Thanks for the PR!

**Pull request merged**
