### PR TITLE
fix: use framework.ExpectNoError instead of gomega

### PR DESCRIPTION
**Pull request by draveness**
/kind cleanup

**What this PR does / why we need it**:

ref: #77103

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by draveness** [comment]
/retest

Regards,
Draven

**Comment by draveness** [comment]
/retest

Regards,
Draven

**Comment by oomichi** [comment]
Nice catch

/lgtm

**Review by MrHohn — APPROVED** [review]
/approve

**Pull request merged**
