### PR TITLE
Make heapster config creation dynamic

### PR DESCRIPTION
**Pull request by brendandburns**
@dchen1107 @vishh @davidopp @gmarek 

Ref: https://github.com/kubernetes/kubernetes/issues/15716

### CODE REVIEW

**Comment by davidopp** [comment]
I think the values you set are too low. You did

0-50: 300M
51-100: 600M
101-150: 1200M
151-200: 1800M
201+: 2400M

But Marek said 50 node run used about 500M. So it's likely a 49 node run would also use about 500M, but you set it at 300M. Marek said 100 node run used about about 1G. So it's likely a 99 node run would also use about 1G, but you set it at 600M. And so on.

Perhaps consider something more like this:

0-50: 600M
51-100: 1200M
101-150: 2G
151-200: 2.5G
201+: 3G

Considering that there's nothing a user can do on GKE to increase these limits, we should probably be conservative in setting them. n1-standard-2 VM has 7.5G so we should be fine.

One problem is that on aws we use t2-micro which appears to only have 1G of RAM. This is a problem whether we use your values or mine. Maybe we should bump up our default minion on AWS to t2.medium (which has 4G).

**Comment by gmarek** [comment]
David's right. Rule of the thumb is 100MB per 10 Nodes, but even that is usually underestimation. I'd go with 120MB or even 150MB to be safe.

**Comment by brendandburns** [comment]
@davidopp @gmarek made it dynamic at `200Mb + 12Mb * NumNodes`

**Comment by davidopp** [comment]
LGTM

I'll file a separate issue for increasing the AWS default VM size.

**Comment by vishh** [comment]
LGTM. Thanks @brendandburns!

**Comment by dchen1107** [comment]
LGTM

**Comment by gmarek** [comment]
I want to add one thing to consider - influxdb has similar problem to heapster, maybe we should set limits for it here as well? I haven't done any testing but probably 'the same amount as heapster' is a good rule of the thumb.

**Comment by brendandburns** [comment]
Can we do that in a different PR?  I'd like to get this checked in.  (and the follow on influx PR should be easier now that I've plumbed num_nodes into the pillars.)

**Comment by dchen1107** [comment]
@gmarek 

* Influxdb is not used for GKE monitoring. 
* Influxdb is not required for pod autoscaling feature. It is required for initial request thought. 
* Most of customer is using their own backend database.
* The current version of influxdb has big memory leakage issue. But upgrading to next version requires a lot of work from our side since the schema is changed.

Of course, I am ok to set same limit as heapster at cluster creation time.

**Comment by dchen1107** [comment]
Yes, do it in a separate PR. I am merging this one.

**Comment by gmarek** [comment]
Yes, sure - different PR is even better. It's just that I noticed OOMing influxdb in an idle cluster, and IIUC we do ship it in default configuration.

**Pull request merged**
