### PR TITLE
cluster/log-dump scp shouldn't check host keys for aws

### PR DESCRIPTION
**Pull request by spiffxp**
parity with cluster/aws/util.sh:ssh-to-node

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30472)

### CODE REVIEW

**Comment by spiffxp** [comment]
@k8s-bot e2e test this: #27235

**Comment by spiffxp** [comment]
@k8s-bot test this issue: #27235

**Comment by spiffxp** [comment]
@k8s-bot test this issue: #30407

**Comment by spiffxp** [comment]
@k8s-bot test this issue: #27957

**Comment by davidewatson** [comment]
I don't have permission to merge, but it lgtm.

**Pull request merged**
