### PR TITLE
fix admission typo

### PR DESCRIPTION
**Pull request by LinuxGit**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

> /kind documentation

**What this PR does / why we need it**:
fix admission typo

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by LinuxGit** [comment]
@msau42 PTAL Thanks

**Comment by nikhita** [comment]
/kind cleanup

/assign @sttts 
for approval

**Pull request closed without merging**
