### PR TITLE
Set Dashboard UI version to v1.5.0-beta1

### PR DESCRIPTION
**Pull request by bryk**
There will be one more such PR coming for 1.5 release. In one week.

Setting release note to none. Will set notes for final version PR. 

Github release info:
https://github.com/kubernetes/dashboard/releases/tag/v1.5.0-beta1

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37287)

### CODE REVIEW

**Comment by bryk** [comment]
@saad-ali can you merge this into 1.5 branch? This is basically addon version bump

**Comment by dims** [comment]
@k8s-bot test this

**Comment by saad-ali** [comment]
> @saad-ali can you merge this into 1.5 branch? This is basically addon version bump

Ok for cherry pick to 1.5.

Can you assign this to someone who is familiar with this code for tech review.

**Comment by bryk** [comment]
@rf232 Can you do tech review?

**Review by rf232 — APPROVED** [review]
LGTM

**Comment by bryk** [comment]
Setting lgtm label on behalf of @rf232

**Comment by bryk** [comment]
@k8s-bot kops aws e2e test this

**Comment by dims** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
