### PR TITLE
Update snapshot CRDs to v6 in add on folder

### PR DESCRIPTION
**Pull request by RaunakShah**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR modifies the snapshot CRD Addons to mirror CRDs found in https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd

Removes the v1beta1 APIs. 
CI for https://github.com/kubernetes-csi/external-snapshotter/pull/704 fails unless these APIs are removed. 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jsafrane** [comment]
This broke GCP PD snapshot test in pull-kubernetes-e2e-gce-storage-snapshot, https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/110180/pull-kubernetes-e2e-gce-storage-snapshot/1528918583516598272/

The CSI driver still uses old sidecars that need v1beta1 API. @RomanBednar will try to update the yaml files shortly.

**Comment by xing-yang** [comment]
There's a comment here to update the yaml for gce pd: https://github.com/kubernetes/kubernetes/pull/110105#issuecomment-1132871565

If  @RomanBednar gets to it first, then @RaunakShah can update his PR after that.

**Comment by xing-yang** [comment]
@RaunakShah Can you submit a PR to pick up changes from this PR: https://github.com/kubernetes-csi/external-snapshotter/pull/718

**Pull request merged**
