### PR TITLE
Revert "kubenet: fix up CNI bridge TX queue length if needed"

### PR DESCRIPTION
**Pull request by freehan**
Reverts kubernetes/kubernetes#25136

### CODE REVIEW

**Comment by freehan** [comment]
I signed it!

**Comment by freehan** [comment]
I signed it!

**Comment by mikedanese** [comment]
@freehan , for the record can you give a general description of the flakiness that you think is linked to this PR?

cc @dcbw

**Comment by dcbw** [comment]
@freehan what was the issue here?  I'm quite curious...

**Comment by freehan** [comment]
The kubenet suite stop flaking over the weekend. I am putting this PR on hold.

**Pull request closed without merging**
