### PR TITLE
add IP-format validation when getting host IP from node

### LINKED ISSUE #89816: unexpected podIP and hostIP in pod
**What happened**:

Unexpected podIP and hostIP in pod, just like
```
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test
spec:
  containers:
  ......
status:
  ......
  hostIP: <nil>
  podIP: <nil>
  ......
```

**What you expected to happen**:

This is a host-networking pod, podIP and hostIP in status should be node's internal IP.

**How to reproduce it (as minimally and precisely as possible)**:

Set kubelet's cloud provider to `external`, then set some invalid addresses to node.

**Environment**:
- Kubernetes version (use `kubectl version`):  1.14

### PR DESCRIPTION
**Pull request by mars1024**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Before setting podIP and hostIP to pod status, hostIP is get from node by [https://github.com/kubernetes/kubernetes/blob/15c3e492b3ad896f36f2ca388108362961b57a19/pkg/kubelet/kubelet_pods.go#L1391](https://github.com/kubernetes/kubernetes/blob/15c3e492b3ad896f36f2ca388108362961b57a19/pkg/kubelet/kubelet_pods.go#L1391), this function will parse the first internal or external IP address from node, without validation.

But the addresses of node are not always trustworthy, sometimes it come from external cloud provider, just like [this](https://github.com/kubernetes/kubernetes/blob/15c3e492b3ad896f36f2ca388108362961b57a19/pkg/kubelet/nodestatus/setters.go#L151), so the original function `GetNodeHostIP` will return a nil IP, and then print unexpected string [\<nil\>](https://github.com/golang/go/blob/a9a78b7005f400e52d8891b01458539e801cf8ad/src/net/ip.go#L295) . 

My change is adding some IP-format validations, ignoring those invalid addresses and try to find the first valid one.

**Which issue(s) this PR fixes**:

Fixes #89816 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
I have one doubts and one nit, first the nit :)

> , this function will parse the first internal or external IP address from node, without validation.

technically it does some validation 😅 , `return net.ParseIP(addresses[0].Address), nil`  validates that the IP is valid or returns nil

> But the addresses of node are not always trustworthy, sometimes it come from external cloud provider, just like [this](https://github.com/kubernetes/kubernetes/blob/15c3e492b3ad896f36f2ca388108362961b57a19/pkg/kubelet/nodestatus/setters.go#L151), so the original function `GetNodeHostIP` will return a nil IP, and then print unexpected string [<nil>](https://github.com/golang/go/blob/a9a78b7005f400e52d8891b01458539e801cf8ad/src/net/ip.go#L295) .

Is ok to masquerade this error from the cloud provider? setting "wrong/bad" IPs to the nodes seems something that should raise an error IMHO

**Review by mattjmcnaughton — COMMENTED** [review]
I don't _think_ I can see how this would cause any harm (and I appreciate you providing test coverage).

I am however, a little surprised, that the cloud providers are giving invalid IP addresses? Can you give some examples of when/why that's occurring?

**Comment by liggitt** [comment]
> Is ok to masquerade this error from the cloud provider? setting "wrong/bad" IPs to the nodes seems something that should raise an error IMHO

I would tend to agree. Falling back to external addresses on a misconfigured internal IP seems incorrect to me.

**Comment by liggitt** [comment]
Correcting a cloud provider that writes bad node status should be a high priority bug, not something I'd expect kubernetes to compensate for

**Comment by mars1024** [comment]
> technically it does some validation 😅 , `return net.ParseIP(addresses[0].Address), nil` validates that the IP is valid or returns nil

Yes, we can judge IP is nil or not in downstream, but the error return seems to be a better way to show validation result. BTW, i don't see that downstream caller judge the returned IP, for example, [https://github.com/kubernetes/kubernetes/blob/15c3e492b3ad896f36f2ca388108362961b57a19/pkg/kubelet/kubelet_pods.go#L1395](https://github.com/kubernetes/kubernetes/blob/15c3e492b3ad896f36f2ca388108362961b57a19/pkg/kubelet/kubelet_pods.go#L1395)

**Comment by mars1024** [comment]
> I don't _think_ I can see how this would cause any harm (and I appreciate you providing test coverage).
> 
> I am however, a little surprised, that the cloud providers are giving invalid IP addresses? Can you give some examples of when/why that's occurring?

Emmm... we can reproduce this manually, but external cloud provider is sometimes out of control without some validations, actually, i'm surprised too.

**Comment by mars1024** [comment]
@aojea @liggitt 

No more agree on that cloud provider should keep correctness through some validations, but in some unexpected cases, indeed node.status will be patched with some **invalid** addresses, I think in these cases, kubelet should throw an error rather than just setting pod.status.hostIP to **"\<nil\>"**, this is what I want to do, making every field in pod spec&status trustworthy.

**Comment by liggitt** [comment]
> I think in these cases, kubelet should throw an error rather than just setting pod.status.hostIP to `"<nil>"`, this is what I want to do, making every field in pod spec&status trustworthy.

I agree those fields shouldn't be populated with a literal `<nil>` string… that seems like a worthwhile bug to fix

**Comment by aojea** [comment]
I absolutely agree with you

> I agree those fields shouldn't be populated with a literal <nil> string… that seems like a worthwhile bug to fix

However, I see 2 problems now :sweat_smile: :

1. Having invalid addresses on the Node.Status.Addresses field

2. Not returning an error in `GetNodeHostIP` if the IP is invalid.

https://github.com/kubernetes/kubernetes/blob/6dbd521cfaf3b2abe69dce376b3b2a1cda5406e1/pkg/kubelet/kubelet_getters.go#L262-L279

Since this exact topic is being discussed in this KEP these days https://github.com/kubernetes/enhancements/pull/1665/files#diff-34fb26e96a72a6bb96ff61b650802164R337-R345 , 

Let me summon @thockin and @danwinship to try to align this PR with the KEP

**Comment by danwinship** [comment]
This ought to be caught in validation. People should be able to assume that `Node.Status.Addresses` does not contain invalid data. But presumably adding validation now would be considered an API break. So, another argument in favor of deprecating the old field.

If we can't fix that, it seems like `pkg/kubelet/nodestatus/setters.go:NodeAddresses()` (or rather, the function that it returns) should ensure that it never sets `Node.Status.Addresses` to an invalid value itself (ie, sanity-check the return value from internal cloud providers), and maybe should return an error if it observes that an external cloud provider has set the field to something invalid. (But not try to fix it since then it will just get into an edit war with the cloud provider.)

Based on Jordan's comment:

> Falling back to external addresses on a misconfigured internal IP seems incorrect to me.

I'd say the patch is wrong, and we should just be making sure that `utilnode.GetNodeHostIP` returns an error if `net.ParseIP` fails?

**Comment by mars1024** [comment]
I think this already fixed in the dual-stack process. :)

**Pull request closed without merging**
