### PR TITLE
update golang/x/net to get http2 fixes (also update required dependencies to not break darwin builds)

### PR DESCRIPTION
**Pull request by aojea**
/kind cleanup

After updating the golang/x/sys dependency in #96076, darwin builds stopped to work because, since golang/sys@6fcdbc0 the module dropped support for direct syscalls on darwin, and Kubernetes is vendoring containerd/console, moby/term and docker/docker versions that still use the direct syscall
Those projects have already fixed the problem:

containerd/console@f1b333f
moby/term@3e73b07
moby/moby@41d4112

This PR updates containerd/console and moby/term to latest commit, and docker/docker to the latest tag that includes the fix, in this case v20.10.0-beta1.
The docker update also requires to modify one function in kubelet/dockershim.

```release-note
None
```

### CODE REVIEW

**Comment by aojea** [comment]
This builds on darwin locally

```
KUBE_BUILD_PLATFORMS=darwin/amd64 make quick-release
+++ [1108 17:08:10] Verifying Prerequisites....
...
+++ [1108 17:11:46] Building tarball: final
+++ [1108 17:11:46] Waiting on test tarballs
+++ [1108 17:11:46] Starting tarball: test darwin-amd64
+++ [1108 17:12:12] Building tarball: test portable
```

**Comment by aojea** [comment]
@harche it seems you fixed this test recently, https://github.com/kubernetes/kubernetes/pull/96302
```
E2eNode Suite: [k8s.io] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api
```

but now is a different case, 
```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:54
Timed out after 90.000s.
Expected
    <string>: Summary
to match fields: {
[.Pods:
	missing expected element summary-test-4558::stats-busybox-0, .Pods:
	missing expected element summary-test-4558::stats-busybox-1]
}

```
do you know what can be the reason that after updating the docker dependency the pod stats are not published?

**Comment by harche** [comment]
It seems to me that after updating your changes the pod itself is not found, probably got killed. The easiest way to debug this would be to use an Ubuntu VM and launch the node e2e tests locally, https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/e2e-node-tests.md

**Comment by caesarxuchao** [comment]
Is this replacing https://github.com/kubernetes/kubernetes/pull/96163?

**Comment by aojea** [comment]
> Is this replacing #96163?

since code freeze is close and I consider that the bugfix you are working on is very important, I wanted to have a plan B in case 96163 does not merge in time.

I' m stuck with with e2e_node test failing though

**Comment by caesarxuchao** [comment]
@aojea do you need help?

@liggitt can we merge this one after the code freeze? This one blocks https://github.com/kubernetes/kubernetes/pull/95981, which is an important bug fix.

**Comment by liggitt** [comment]
> @liggitt can we merge this one after the code freeze? This one blocks #95981, which is an important bug fix.

Bug fixes can merge after freeze, but the bar is very high, both in terms of impact and risk. While I agree #95981 is important, that issue has existed for multiple releases.

The amount of code this changes is very large. If these bumps introduced issues, they are likely to be subtle ones that would be easy to overlook with just a couple weeks of soak time. Both of those indicate to me that this should land in 1.21.

**Comment by aojea** [comment]
I was talking with @dims on slack yesterday, and I it may happen that the updates that they are doing in cadvisor brings the right versions in, but I lost track ...
If this PR will update only dockershim I would be less worried because we are starting deprecation, but last try I did yesterday brought a lot of things in

**Comment by aojea** [comment]
/close 
yay, the cadvisor update brings the latest x/net/ and x/sys dependencies

https://github.com/kubernetes/kubernetes/pull/96425/files#diff-afaab26fb5d297f3fd332eb795bb16c392dea885df5843807752210534cbda4dR29-R30

**Comment by liggitt** [comment]
looks like golang.org/x/sys actually restored compatibility with the syscall bits... the cadvisor update is pulling in a ton of other stuff, so it might actually be worthwhile to pick this back up and grab latest net and sys to pick up the http2 fixes

**Comment by dims** [comment]
@liggitt @aojea looks like this needed a rebase, i started another PR https://github.com/kubernetes/kubernetes/pull/96548

/close

**Pull request closed without merging**
