### PR TITLE
Automated cherry pick of #91307: CSI: Modify VolumeAttachment check to use Informer/Cache

### PR DESCRIPTION
**Pull request by xing-yang**
Cherry pick of #91307 on release-1.18.

#91307: CSI: Modify VolumeAttachment check to use Informer/Cache

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by tpepper** [comment]
/kind bug
/priority important-soon
from parent PR https://github.com/kubernetes/kubernetes/pull/91307

**Comment by xing-yang** [comment]
/hold
Waiting for Parent PR  #91307 to be merged first.

**Comment by dims** [comment]
/approve
/lgtm
/hold cancel 

(#91307 has all approvals and is in merge queue)

**Comment by xing-yang** [comment]
#91307 is merged.

**Comment by msau42** [comment]
/lgtm
/approve
Storage integration and e2e tests on master look good.

**Comment by liggitt** [comment]
See question at https://github.com/kubernetes/kubernetes/pull/92014#issuecomment-644454262 about suitability for backporting

**Comment by dims** [comment]
@liggitt hoping @yuga711 / @saad-ali / @msau42 can chime in. @xing-yang and i have gotten a bunch of internal testing for this patch and it looks good! it reduces the time taken and the load on api server.

**Comment by liggitt** [comment]
/approve
for controller-manager change

**Pull request merged**
