### PR TITLE
correct pod-deletion-cost sort comment

### PR DESCRIPTION
**Pull request by Lion-Wei**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Correct comment description in `ActivePodsWithRanks` for pod-deletion cost sort. 
Not a big thing, but might lead to misunderstanding. : )

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2255-pod-cost
```

### CODE REVIEW

**Comment by Lion-Wei** [comment]
@ahg-g Can you take a look, thanks. : )
/assign @liggitt

**Comment by liggitt** [comment]
/unassign

a controller/apps owner can approve this

**Comment by Lion-Wei** [comment]
/assign @janetkuo 
I think this is ready for approve. : )

**Pull request closed without merging**
