### PR TITLE
Replace controller presence checking logic

### LINKED ISSUE #36912: e2e logic for matching pods to ReplicationControllers is broken
The logic to account for all pods being ready is incorrectly counting some pods as being controlled by a replication controller. This is causing the 1.3-1.5 upgrade tests to fail. See https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-container_vm-1.3-container_vm-1.5-upgrade-cluster/99 as an example.

```
Nov 16 10:52:49.437: INFO: expected 4 pod replicas in namespace 'kube-system', 5 are Running and Ready.
```

Since `5 != 4`, the pre-flight checks fail and the rest of the tests never run. I think this was exposed by https://github.com/kubernetes/kubernetes/pull/36008 which changed some things from ReplicationControllers to Deployments. There's a pod being created by a deployment that also matches the selector of a replication controller, and is therefore being incorrectly counted by https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L441

cc @kubernetes/sig-testing @saad-ali

### PR DESCRIPTION
**Pull request by krousey**
fixes #36912

```release-note
Replace controller presence checking logic
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36924)

### CODE REVIEW

**Comment by krousey** [comment]
@saad-ali This will probably need some combination of cherry picks to 1.5, 1.4, and/or 1.3.

**Comment by saad-ali** [comment]
Looks fine to me, but I'm not super familiar with this code. Can someone from @kubernetes/sig-testing take a look?

**Review by spxtr — COMMENTED** [review]
It looks fine to me, but this code is pretty confusing, especially when considering past release branches and upgrade jobs.

**Comment by spxtr** [comment]
Okay no objection from me. Hopefully we don't cherrypick and then find out it doesn't quite fix the problem.

/lgtm

**Comment by krousey** [comment]
@saad-ali I marked this as a cherry pick candidate to be put in the 1.5 release branch.

**Comment by saad-ali** [comment]
> @saad-ali I marked this as a cherry pick candidate to be put in the 1.5 release branch.

Ack, will try to pick it up today

**Comment by saad-ali** [comment]
This PR has been picked up in 1.5 as this afternoon. The upgrade tests are [still failing](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/kubernetes-e2e-gke-container_vm-1.4-container_vm-1.5-upgrade-cluster-new/).

I guess this will happen until this fix is cherry-picked to the 1.3 and 1.4 branches?

CC @jessfraz to cherry pick this PR to 1.4

**Comment by krousey** [comment]
@saad-ali This had the intended affect. If you notice, about 100 more tests are now being run, and only one is failing now. This is likely a new failure that I will look into.

**Comment by jessfraz** [comment]
cherry-picked in https://github.com/kubernetes/kubernetes/pull/37140

**Pull request merged**
