### PR TITLE
[release-1.6] Bump golang versions to 1.7.6

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
Addresses #46391 for the release-1.6 branch.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
Tests will not pass until kube-cross image is built and pushed to GCR.

**Release note**:

```release-note
Upgrade golang version to 1.7.6
```

### CODE REVIEW

**Review by luxas — APPROVED** [review]
LGTM

The Makefile changes aren't actually needed, because no images are pushed from the release branches, only from HEAD. I don't mind making the change, but it could end up confusing as the bump to v1.7.6 on a release branch was never used for an image.

**Comment by cblecker** [comment]
Ah, gotcha. In that case, I'll remove those changes as they aren't needed.

**Comment by cblecker** [comment]
Updated to only touch the kube-cross image, similar to the 1.5 change.

**Comment by ixdy** [comment]
/lgtm
@k8s-bot test this

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-cross test this

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-cross test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this
@k8s-bot pull-kubernetes-node-e2e test this
@k8s-bot pull-kubernetes-verify test this

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-node-e2e test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Pull request merged**
