### PR TITLE
update kubectl approvers

### PR DESCRIPTION
**Pull request by deads2k**
All the other owners files have names (not groups).  Updated for individual users for approvers so `/approve` works.

@kubernetes/sig-cli-api-reviews

### CODE REVIEW

**Comment by fabianofranz** [comment]
Looks good, @pwittrock @AdoHe?

**Comment by fabianofranz** [comment]
The same set of approvers apply to 

```
cmd/kubectl
pkg/client/unversioned/clientcmd
```

**Comment by fabianofranz** [comment]
Also, should we be approvers in vendored things like Cobra and pflag?

**Comment by fabianofranz** [comment]
@deads2k the current setup for reference:

https://github.com/kubernetes/kubernetes/commit/91393b5123602fc87838f67b3b2d75765020c3fb

**Comment by deads2k** [comment]
> @deads2k the current setup for reference:
> 
> 91393b5

huh, I wonder why my comment didn't work.  I'll try it again.

**Comment by fabianofranz** [comment]
@deads2k here's how it is today based on the contents of `sig-cli` and `sig-cli-maintainers`, I'd suggest updating this PR to reflect the same list: 

```
  approvers:
    - adohe
    - brendandburns
    - deads2k
    - fabianofranz
    - janetkuo
    - pwittrock
    - smarterclayton
  reviewers:
    - adohe
    - deads2k
    - derekwaynecarr
    - dims
    - dshulyak
    - eparis
    - ericchiang
    - fabianofranz
    - ghodss
    - kargakis
    - pwittrock
    - rootfs
    - smarterclayton
    - soltysh
    - sttts
    - ymqytw
```

**Comment by deads2k** [comment]
@fabianofranz is it working for you?  I had to manually add the label: https://github.com/kubernetes/kubernetes/pull/40130

**Comment by fabianofranz** [comment]
@deads2k approve doesn't seem to be working: https://github.com/kubernetes/kubernetes/pull/40416

**Comment by deads2k** [comment]
> @deads2k approve doesn't seem to be working: #40416

Sorting out the alias and find a sane way to get notifications (we aren't getting any at the moment) would be fine.

**Comment by fabianofranz** [comment]
Fixes https://github.com/kubernetes/kubernetes/issues/40409

**Comment by eparis** [comment]
@grodrigues3 should we instead change/fix the approvers to hand the groups?

**Comment by AdoHe** [comment]
LGTM, great thanks to @deads2k

**Comment by deads2k** [comment]
> @grodrigues3 should we instead change/fix the approvers to hand the groups?

I have no strong opinions, but @fabianofranz may choose to remove `do-not-merge` tag if we need relief for the kubectl approvers who don't have super-tagging-powers.

**Comment by fabianofranz** [comment]
Getting this merged, and we can follow-up about a better process.

**Comment by pwittrock** [comment]
SGTM.

**Comment by grodrigues3** [comment]
> `Getting this merged, and we can follow-up about a better process.`

approval-handler.go now recognizes aliases.  

https://github.com/kubernetes/test-infra/pull/1714

I'm going to revert this PR.

**Pull request merged**
