### PR TITLE
Stop allowing unnamespaced POST for namespaced objects

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/GoogleCloudPlatform/kubernetes/issues/11181

Unnamespaced POST for namespaced objects is broken right now.

cc @bgrant0607 @smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM

**Comment by lavalamp** [comment]
LGTM, but post v1

**Comment by nikhiljindal** [comment]
Rerunning the tests

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
e2e passed!
cc @vishh for merging :)

**Comment by vishh** [comment]
Waiting for shippable to complete.

**Comment by nikhiljindal** [comment]
Shippable timed out. Rerunning

**Comment by mikedanese** [comment]
@nikhiljindal needs rebase

**Comment by nikhiljindal** [comment]
Rebased

**Pull request merged**
