### PR TITLE
Add ebtables rule delete function + broute table + brouting chain

### LINKED ISSUE #92439: Add DeleteRule method + broute table to  ebtables util
**What would you like to be added**:

The ebtables utility in  https://github.com/kubernetes/kubernetes/blob/master/pkg/util/ebtables/ebtables.go is missing 3 useful features:

- `DeleteRule` method in its Interface
- `broute` table
- `brouting` chain

**Why is this needed**:

The missing features are useful to allow for: 
- rule deletion as there is a way to add (ensure) a rule but not removing it currently. 
- manipulating the broute table and brouting chain

The first feature would also align ebtables with iptables, as a DeleteRule method is available there.

### PR DESCRIPTION
**Pull request by luigibk**
Implementation of the enhancement documented in:

https://github.com/kubernetes/kubernetes/issues/92439

/kind feature

**What this PR does / why we need it**:

Enhance  ebtables utility adding the following 3 features:

- DeleteRule method
- broute table
- brouting chain

**Which issue(s) this PR fixes**:
Fixes #92439 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note
No actions required. This is a small enhancement to a utility library.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

Implementing the missing features allows to:

- delete rules as there is currently a way to add (ensure) a rule but not removing it.
- manipulate the broute table and brouting chain.

The first feature would also align ebtables with iptables, as a DeleteRule method is available there.

### CODE REVIEW

**Comment by luigibk** [comment]
I signed it

**Review by timja — APPROVED** [review]

**Pull request merged**
