### PR TITLE
pkg,test: Fix DaemonSet typos

### PR DESCRIPTION
**Pull request by lilic**
**What type of PR is this?**
🤷‍♀️ there was no kind typo.

**What this PR does / why we need it**:
Fixes typos :)

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
thanks @LiliC 
/lgtm
/approve
/ok-to-test
/kind cleanup
/priority backlog

**Review by tnozicka — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
