### PR TITLE
Revert "dump conntrack table on e2e conntrack failures"

### PR DESCRIPTION
**Pull request by aojea**
**What type of PR is this?**
/kind cleanup
/kind bug

**What this PR does / why we need it**:

This reverts commit 0ef7f27fc134a3d7914ecbf555aa89933ff85357.
It was dumping the conntrck rules once the test finished, for debugging

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @wojtek-t 
the test looks better now and this is pollution the e2e logs unnecessarily

**Comment by wojtek-t** [comment]
> the test looks better now and this is pollution the e2e logs unnecessarily

It's better, but there are still some flakes. There are still O(10) failures per day failing with:
```
Failed to connect to backend 1
```

Do we understand them? If not, aren't those logs helpful to debug them?

/hold

**Comment by aojea** [comment]
> Do we understand them? If not, aren't those logs helpful to debug them?

until now these logs only shows that the packet goes out but never comes back ... I'll check again next week, let's hold it

**Comment by aojea** [comment]
These are the entries of a working test

```
I0812 15:31:25.778] udp      17 175 src=10.64.3.94 dst=10.0.140.245 sport=12345 dport=80 src=10.64.1.119 dst=10.64.3.94 sport=80 dport=12345 [ASSURED] mark=0 use=1                                                  
I0812 15:31:25.792] udp      17 175 src=10.64.2.135 dst=10.40.0.3 sport=12345 dport=30071 src=10.64.3.167 dst=10.64.3.1 sport=80 dport=52523 [ASSURED] mark=0 use=1                                                  
I0812 15:31:25.933] udp      17 175 src=10.64.2.135 dst=10.40.0.3 sport=12345 dport=30071 src=10.40.0.3 dst=10.64.2.135 sport=30071 dport=12345 [ASSURED] mark=0 use=1                                               
I0812 15:31:26.166] udp      17 176 src=10.64.3.94 dst=10.64.1.119 sport=12345 dport=80 src=10.64.1.119 dst=10.64.3.94 sport=80 dport=12345 [ASSURED] mark=0 use=1 
```

and these in a failing test:

```
I0811 22:06:14.715] udp      17 29 src=10.64.2.114 dst=10.40.0.5 sport=12345 dport=31125 [UNREPLIED] src=10.40.0.5 dst=10.64.2.114 sport=31125 dport=12345 mark=0 use=1                                              
I0811 22:06:15.201] udp      17 26 src=10.64.2.114 dst=10.40.0.5 sport=12345 dport=31125 [UNREPLIED] src=10.40.0.5 dst=10.64.2.114 sport=31125 dport=12345 mark=0 use=1                                              
I0811 22:07:10.377] udp      17 25 src=10.64.2.114 dst=10.40.0.5 sport=12345 dport=31125 [UNREPLIED] src=10.40.0.5 dst=10.64.2.114 sport=31125 dport=12345 mark=0 use=1                                              
I0811 22:07:10.661] udp      17 178 src=10.64.3.205 dst=10.0.160.235 sport=12345 dport=80 src=10.64.1.169 dst=10.64.3.205 sport=80 dport=12345 [ASSURED] mark=0 use=1                                                
I0811 22:07:10.771] udp      17 27 src=10.64.2.114 dst=10.40.0.5 sport=12345 dport=31125 [UNREPLIED] src=10.40.0.5 dst=10.64.2.114 sport=31125 dport=12345 mark=0 use=1                                              
I0811 22:07:11.095] udp      17 175 src=10.64.3.205 dst=10.64.1.169 sport=12345 dport=80 src=10.64.1.169 dst=10.64.3.205 sport=80 dport=12345 [ASSURED] mark=0 use=1                                                 
I0811 22:07:11.128] udp      17 160 src=10.64.3.205 dst=10.64.1.160 sport=12345 dport=80 src=10.64.1.160 dst=10.64.3.205 sport=80 dport=12345 [ASSURED] mark=0 use=1   
```

is it possible that both tests are running in parallel and the fact that have the same source port is causing problems?

**Comment by wojtek-t** [comment]
> is it possible that both tests are running in parallel and the fact that have the same source port is causing problems?

I think that in this run they don't run in parallel: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93817/pull-kubernetes-e2e-gce/1293300409502273538
There are different IPs, so same port shouldn't cause issues, but I'm not the networking expert...

**Comment by aojea** [comment]
> There are different IPs, so same port shouldn't cause issues, but I'm not the networking expert...

image

**Comment by aojea** [comment]
/close

@wojtek-t let's go with this https://github.com/kubernetes/kubernetes/pull/92643
I can spend some time this week on this bug

**Pull request closed without merging**
