### PR TITLE
Save a list of images used by e2e.test

### PR DESCRIPTION
**Pull request by dims**
We need to keep track of the list of images needed by e2e.test. Usually this is generated when someone runs `e2e.test --list-images`. 

When we add new images to the manifest here, we they will need to update `test/conformance/testdata/repo_list_images.txt` as well:
https://github.com/kubernetes/kubernetes/blob/fa66a37fd9bdf4e56bc86695dbdf0c7484ba86eb/test/utils/image/manifest.go#L231-L268

For users of sonobuoy and hydrophone etc, they run `e2e.test --list-images` and use the list to copy images over to private registries especially to run conformance tests. So have additional reviews on the list of images by a smaller set of people is important. Also is keeping this list as small as possible.

We recently found and cleaned up a couple of images, hence this additional review by conformance approvers.
- https://github.com/kubernetes/kubernetes/pull/122556
- https://github.com/kubernetes/kubernetes/pull/122564

#### What type of PR is this?
/kind documentation

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
> When we add new images to the manifest here, we they will need to update test/conformance/testdata/repo_list_images.txt as well:

These images aren't all necessarily used by conformance though? Seems somewhat misleading.

**Comment by BenTheElder** [comment]
Also, I don't think we should need conformance approval every time we update an image _tag_ for test images. 
That seems like an unnecessary bottleneck.

**Comment by dims** [comment]
The feature to `--list-images` was added to support sonobuoy initially. I am happy for another limited set of reviewers to be able to approve this list of images. Given what i saw in the list (duplicate images, unnecessary images from dockerhub), there needs to be a higher threshold for updating this list.

**Comment by BenTheElder** [comment]
There's a less heavy handed version of this that only requires approving new image names and we should separately wind down the duplicate image tags.

We really shouldn't do anything to discourage keeping up to the latest tags, we have enough problem with never updating these.

**Comment by BenTheElder** [comment]
And again, this puts _all images used for e2e_ in scope of conformance approvers, NOT just images used by conformance tests. 

As a SIG Testing TL I'm not happy with being part of pushing everything in k/k to a place where only one of a few people can actually approve merging anything and the rest of the OWNERS entries are ~meaningless.

Also: As currently implemented there's no pointer to run the update script until after the author pushes the PR and tests fail.
There should be a comment in the sources.

**Pull request merged**
