### PR TITLE
Improvements to deployment e2e

### PR DESCRIPTION
**Pull request by nikhiljindal**
Ref #1743 

Adding more test cases to deployment e2e:
- Added a case to ensure that we do not break the contract for maxUnavailable and maxSurge during the update.
- Added a case to ensure that RCs are scaled up and down in the expected order. Added events for scaling changes and using them in tests.

Also, found and fixed a bug in the controller.
Also, fixed DeploymentControllerSyncPeriod to be same as other controllers.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @ghodss @ironcladlou

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by ironcladlou** [comment]
No time to review in depth tonight, but wanted to mention there's overlap here with #14130 (especially the refactorings to use the utility which I've incorporated into my rebased branch). Would you consider working to get #14130 in shape and merged before any more refactoring in an effort to minimize conflicts as we continue to iterate?

**Comment by nikhiljindal** [comment]
I am trying to get this in 1.1

**Comment by ironcladlou** [comment]
LGTM. I will rebase after this lands.

**Pull request merged**
