### PR TITLE
Cherry pick of #64255: fix field removal in mutating admission webhooks

### PR DESCRIPTION
**Pull request by sttts**
This cherry-pick was unclean because the webhook plugin was seriously refactored after 1.10

Based on https://github.com/kubernetes/kubernetes/pull/64255

```release-note
Webhooks for the mutating admission controller now support "remove" operation.
```

### CODE REVIEW

**Comment by sttts** [comment]
hack/update-bazel.sh is broken for me https://github.com/kubernetes/kubernetes/issues/64972.

**Comment by liggitt** [comment]
needs bazel update, lgtm otherwise

**Comment by nikhita** [comment]
https://github.com/kubernetes/kubernetes/issues/64925 bazel is broken on release-1.10

**Comment by sttts** [comment]
/assign @MaciekPytel 

For 1.10 approval.

**Comment by MaciekPytel** [comment]
Bumping up priority so it can still merge despite bot being in code freeze mode.

**Comment by krmayankk** [comment]
@sttts  @liggitt as mentioned in the meeting, following was the patch which was needed  to make injecting of labels work properly in 1.10, which was earlier working in 1.9

```
{
-		"path": "/metadata/labels",
-		"value": {
-			"sherpa-injector.service-mesh/status": "injected"
-		}
+		"path": "/metadata/labels/sherpa-injector.service-mesh~1status",
+		"value": "injected"
	}
```
My questions are:-
- why does the removed patch in the above , removed all labels from a pod ? I understand that merging with existing labels restored all labels. But why does it remove it ?

I understand that the removed lines above will create the following,

```
labels: 
     sherpa-injector.service-mesh:
          status: injected
```

but can this not coexist with  ?

```
labels: 
     sherpa-injector.service-mesh/status: injected
```

**Comment by liggitt** [comment]
Your original patch says "set `/metadata/labels` to `{"sherpa-injector.service-mesh/status": "injected"}`, overwriting whatever is currently at that location"

**Pull request merged**
