### PR TITLE
CRI: remove pod sandbox resources

### PR DESCRIPTION
**Pull request by yujuhong**
The pod-level resources need further discussion. Remove it from CRI for now.

See the original discussion in #29871

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30521)

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM

**Comment by yujuhong** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by feiskyer** [comment]
@yujuhong Also remove `ResourceRequirements`? Since it is not used any more.

**Comment by yujuhong** [comment]
> @yujuhong Also remove ResourceRequirements? Since it is not used any more.

Good catch. Removed.

**Comment by yujuhong** [comment]
@k8s-bot unit test this. issue: #IGNORE

**Comment by yujuhong** [comment]
@k8s-bot node e2e test this. issue: #28716

**Pull request merged**
