### PR TITLE
[wip] testing out integration 1.22 canary job

### PR DESCRIPTION
**Pull request by spiffxp**
Related:
- Part of: https://github.com/kubernetes/kubernetes/issues/105436
- Followup to: https://github.com/kubernetes/test-infra/pull/23890

Testing out https://github.com/kubernetes/test-infra/pull/23890 with an empty PR

### CODE REVIEW

**Comment by spiffxp** [comment]
Trying out a revert of https://github.com/kubernetes/kubernetes/pull/105049

**Comment by spiffxp** [comment]
Nope, that won't work... I was going to try making this equivalent to the code in master by just resetting the PR's branch to master, but hello merge conflicts

**Comment by spiffxp** [comment]
Grasping at straws here.  Trying to make really sure it's nothing about this job and this branch's code by running with the code in master.  I will be shocked if this works
```
git diff --binary release-1.22 origin/master > release-1.22-to-master.patch
git apply release-1.22-to-master.patch
```

**Comment by spiffxp** [comment]
https://github.com/kubernetes/kubernetes/pull/105488/commits/5197769219f78c7fcd564fb834874cf32e1d4a73 - dropping concurrency down to 1 ended up with a 357MB (!!) junit xml file which spyglass is refusing to parse (as it should, that's way too large) (ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/105488/pull-kubernetes-integration/1445512318795386880)

Grepping for ^FAIL in the log I pulled out:
```
test/integration/client TestExecPluginRotationViaInformer
test/integration/controlplane TestStatus
test/integration/pods TestPodEphemeralContainersDisabled
```

**Comment by spiffxp** [comment]
https://github.com/kubernetes/kubernetes/pull/105488/commits/88cef68fffd5223839ff85cf7c2bb0fd1d9dc4fa - focusing just on the admission webhook test passed (ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/105488/pull-kubernetes-integration/1445534298303107072)

**Comment by spiffxp** [comment]
https://github.com/kubernetes/kubernetes/pull/105488/commits/40f9fbd5ff8d8aaf20ec458d264bc37dcf1450e5 - starting to add more integration tests into the mix until I find the right number or test that causes things to failure... thus far these passed once (ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/105488/pull-kubernetes-integration/1445538682009292800)
```
  k8s.io/kubernetes/test/integration/apimachinery
  k8s.io/kubernetes/test/integration/apiserver
  k8s.io/kubernetes/test/integration/apiserver/admissionwebhook
  k8s.io/kubernetes/test/integration/apiserver/apply
  k8s.io/kubernetes/test/integration/apiserver/certreload
  k8s.io/kubernetes/test/integration/apiserver/flowcontrol
  k8s.io/kubernetes/test/integration/apiserver/podlogs
  k8s.io/kubernetes/test/integration/apiserver/tracing
  k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/test/integration
  k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/test/integration/conversion
```

**Comment by liggitt** [comment]
well, that turned canary green

**Pull request closed without merging**
