### PR TITLE
Fix word typo

### PR DESCRIPTION
**Pull request by yeasy**
envitonment --> environment

### CODE REVIEW

**Comment by eparis** [comment]
ok to test

**Comment by eparis** [comment]
Thank you for the contribution. Once you get the CLA signed we'll get this merged!

**Comment by wojtek-t** [comment]
@yeasy - can you please sing the CLA as described in the instruction above:
https://github.com/kubernetes/kubernetes/pull/22730#issuecomment-194073816

**Comment by yeasy** [comment]
Yes, just signed it.
Thanks for the reminder.

**Pull request merged**
