### PR TITLE
Fix typos in kube-proxy

### PR DESCRIPTION
**Pull request by yanghaichao12**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
Fix  typos

Which issue(s) this PR fixes (optional, in fixes #(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

NONE

### CODE REVIEW

**Comment by yanghaichao12** [comment]
@m1093782566 have you written this book? i'm reading now
image

**Comment by m1093782566** [comment]
True, thanks for supporting!

**Comment by yanghaichao12** [comment]
i learned a lot from it :)

**Pull request merged**
