### PR TITLE
adding release notes guidelines to the (new) releases policy.

### PR DESCRIPTION
**Pull request by AntonioMeireles**
per the ongoing conversation at GoogleCloudPlatform/kubernetes#6213

(and per @bgrant0607 indication there :smile: )

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM
cc @zmerlynn @brendandburns @davidopp @kmerker

**Comment by zmerlynn** [comment]
I think this is fine as a release finalization process. I don't think we would actually block the binary bits at any point, though, because we're on a 2 week release train, so we need to figure out what realistic timelines should be.

**Comment by bgrant0607** [comment]
@zmerlynn Why wouldn't we block the release? That's exactly what we do for internal releases.

**Comment by zmerlynn** [comment]
Because assembling the release notes takes a considerable amount of time, whereas cutting the binary pre-release is a necessary step prior to validation by other partners. We have exactly one of those today, GKE, but GKE can't start partner validation on a release until the binaries are available.

**Comment by zmerlynn** [comment]
@bgrant0607: Note the on github, releases still have "Latest release" versus "Pre-release". All I'm saying is that we wouldn't block binary pre-release for release notes, and may use that period for drafting release notes. This is also consistent with internal build process.

**Comment by AntonioMeireles** [comment]
@zmerlynn maybe i 'm missing something (as i 'm far, far away from the inner googleLand) but the (my) idea, imho would be something incremental and progressive. one would only expect 'reasonable' release notes for final (non pre-release) versions, as that are the ones 'normal' people would consume - those usually are precedeed by a reasonable amount of pre-releases. ideally from PreRelease-x to PreRelease-n (where n gets us closer to next non pre-release version) the release notes get better/more polished/accurate. Point is not to Shakspeare class writing. from an overhead Point of View imho main time-burner would be to check what pushes (from a stable to stable version) got overrided by subsequent pushes...

**Comment by zmerlynn** [comment]
@AntonioMeireles: I'm actually more suggesting that as an example, 0.14.0 I started out with draft release notes. They're pretty bad, but better than the non-existent ones for 0.13.0.

I'm proposing that after some period of time (O(days)), the 0.x.0 release notes should ossify and no longer be draft, but that it in no way block the binary release.

Sidebar: The fact that 0.14.0 is still in draft is actually my fault, and it's largely because I asked the team for any clarifications and was met with mostly silence. So it's probably timed out and is about as good as it's going to get, which is unfortunate. I haven't had a chance to go back and edit it to be more thorough. So I haven't exactly practiced this yet, and in fact we already shipped 0.14.1 on GKE.

**Comment by davidopp** [comment]
I think it would be sufficient to just list the major user-visible changes, in human-understandable form, and link to the corresponding PR/issue #s.

If someone wants an exhaustive list of all PRs in a release, there's a git query for that. I think the cost/benefit of summarizing every PR in a release is too high. But at the same time, I think what we're currently doing is insufficient (descriptions are too terse, and not links to PR/issue). I think what I proposed in the first paragraph is a reasonable compromise that maximizes bang-for-the-buck.

**Comment by bgrant0607** [comment]
@davidopp I think the 2nd paragraph matches what you wrote, with the right interpretation of "relevant".

I'd be fine with merging this as-is, as we debate the more precise policy and mechanism in #6213.

**Comment by davidopp** [comment]
Sure.

**Comment by bgrant0607** [comment]
Merging. We can tweak it more later.

**Pull request merged**
