### PR TITLE
Code cleanup and refactoring

### PR DESCRIPTION
**Pull request by ping035627**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
Code cleanup and refactoring.

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

/release-note-none
/priority backlog

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks for the PR @ping035627 
SGTM
/approve
/ok-to-test

@kubernetes/sig-cluster-lifecycle-pr-reviews

**Review by yagonobre — COMMENTED** [review]
Thanks @ping035627 
/lgtm
/hold
Holding to let other people review too.

**Comment by ping035627** [comment]
@kubernetes/sig-cluster-lifecycle-pr-reviews Can you help to review this pr? Thanks.

**Comment by neolit123** [comment]
> Can you help to review this pr? Thanks.

sorry the PR was on hold.

/hold cancel

**Review by dixudx — APPROVED** [review]
/lgtm

**Pull request merged**
