### PR TITLE
remove unnecessary fields from generic apiserver

### PR DESCRIPTION
**Pull request by deads2k**
Removing some unnecessary fields from the generic API server struct.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31156)

### CODE REVIEW

**Comment by lavalamp** [comment]
@nikhiljindal to double check, but looks good to me

**Comment by nikhiljindal** [comment]
Will be great if you can remove the corresponding command line flag as well.
`pkg/genericapiserver/options/server_run_options.go`

**Comment by deads2k** [comment]
> Will be great if you can remove the corresponding command line flag as well.
> pkg/genericapiserver/options/server_run_options.go

The flags are still present.  I'm working my way through the generic API server factoring and there seem to be three layers:
 1. `ServerRunOptions` - these are bound to flags and are *almost* serializeable
 2. `genericapiserver.Config` - `ServerRunOptions` are transformed into this.  It is not serializeable and contains a lot of wiring options.
 3. `genericapiserver.GenericAPIServer` - `genericapiserver.Config`  is transformed into this.  It contains a lot of semi-exposed pieces with few interdepencies and seems to be intended to provide the runtime structure for an API server.

I'm a fan of the three tiered structure, but I'd like to draw sharper lines between them.  I think I'd like to start by reducing the `GenericAPIServer` struct into an immutable structure with minimum set of fields and have most interaction run through the `genericapiserver.Config` (the non-serializable config that is wired together to create things like the correct handler chain).

I found these dead fields in my initial survey and figured I'd clean them up while I was here.  The `genericapiserver.Config` fields (and the `ServerRunOptions` which drive them) are still present and used to build the `GenericAPIServer` handler chain.

**Comment by lavalamp** [comment]
Plan sounds good to me.

**Comment by nikhiljindal** [comment]
Great to know that you are planning a bigger refactoring/clean up of generic apiserver.

> The flags are still present.  I'm working my way through the generic API server factoring and there seem to be three layers:
>  1. `ServerRunOptions` - these are bound to flags and are *almost* serializeable

Yes its a struct summarizing all the flags. Curious, why you say *almost* serializable?

>  2. `genericapiserver.Config` - `ServerRunOptions` are transformed into this.  It is not serializeable and contains a lot of wiring options.

Yes. This is not serializable. For ex: ServerRunOptions has a string indicating the admission controls.
Config contains the actual interfaces.
Config is a struct for all params to be passed to genericapiserver.New()

>  3. `genericapiserver.GenericAPIServer` - `genericapiserver.Config`  is transformed into this.  It contains a lot of semi-exposed pieces with few interdepencies and seems to be intended to provide the runtime structure for an API server.

Yes, I think we can make all the fields private here and instead add public accessor functions. I hadnt done that initially since that will involve updating all places where the field is used :)

**Pull request merged**
