### PR TITLE
e2e: move feature gate support from test/e2e to test/e2e_node

### LINKED ISSUE #109648: remove SkipUnlessFeatureGateEnabled
### What would you like to be added?

The E2E framework has SkipUnlessFeatureGateEnabled which tricks developers into thinking that they can write tests that only run when a feature gate is enabled. That doesn't work:
- the e2e.test binary has no way of checking which feature gates are enabled in the Kubernetes cluster
- the `-feature-gate` parameter in test/e2e is not used either

We should remove SkipUnlessFeatureGateEnabled. I would also remove the `-feature-gate`. Apparently the corresponding field is used in some node e2e suite. Let's move the flag there.

/sig testing

### Why is this needed?

Avoid developer mistakes...

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The test/e2e suite has never supported feature gates:

- it cannot discover at runtime how the cluster is configured
- its --feature-gates parameter had no effect

Despite that, tests were written that used
e2eskipper.SkipUnlessFeatureGateEnabled even though that function then only
checked the default feature gate state.  To catch such mistakes, e2e tests
suites now must explicitly enable feature gate checking via
e2eskipper.InitFeatureGates. They also must register their own command line
flag. When that is not done, then using SkipUnlessFeatureGateEnabled or
SkipIfFeatureGateEnabled leads to a test failure.

test/e2e_node does both and therefore continues to work as before.

#### Which issue(s) this PR fixes:
Fixes #109648

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
just curious, why not removing entirely the code from the e2e framework and move it to e2e_node?

**Comment by endocrimes** [comment]
@aojea I think this still belongs as part of the framework, but wouldn't be super opposed to it moving somewhere in e2e_node eventually (we really need to do some cleanup there tho, organizationally it's a mess today)

**Review by endocrimes — APPROVED** [review]
/lgtm

e2e_node changes lgtm
also lgtm to fail hard in tests that don't support it

**Comment by aojea** [comment]
> @aojea I think this still belongs as part of the framework, but wouldn't be super opposed to it moving somewhere in e2e_node eventually (we really need to do some cleanup there tho, organizationally it's a mess today)

the feature gate skipper cause much confusion giving the assumption it does skip based on feature gates, having it in the global framework allows people to import it ... removing it completely from the e2e framework completely solves the problem.

I'm afraid that we are going to break tests that will start to fail without us noticing

**Comment by endocrimes** [comment]
How far back do we support running Conformance tests? - I think the ExecProbeTimeout checks should be removable now that 1.20 is well out of support.

**Comment by dims** [comment]
`// lock to default and remove after v1.22 based on KEP #1972 update` is the note from:
https://github.com/kubernetes/kubernetes/blob/f02682c628c530219966a00ae002d799f0d813dc/pkg/features/kube_features.go#L962

So yes when 1.25 opens up, we can clean all this stuff up (related to `ExecProbeTimeout`)

**Comment by pohly** [comment]
> How far back do we support running Conformance tests?

Isn't it so that conformance tests must always use the e2e.test binary that matches the Kubernetes version that is to be tested?

A situation where a e2e.test conformance test gets invoked to test conformance of some older Kubernetes where a feature might be disabled should never occur.

**Comment by pohly** [comment]
> just curious, why not removing entirely the code from the e2e framework and move it to e2e_node?

There might be other test suites that use feature gates check, so having some support for it in the common framework makes sense to me. We just have to ensure that this common code then doesn't get used incorrectly in test suites where it doesn't work as expected. Causing a test failure ensures that at runtime, which should be good enough. If developers submit tests that don't run at all, then we have a bigger problem...

**Comment by pohly** [comment]
I've pushed a version where I am removing those checks that clearly didn't do anything (= never skipped).

The only ones left right now are:
```
test/e2e/common/node/downwardapi.go:                    e2eskipper.SkipUnlessFeatureGateEnabled(kubefeatures.DownwardAPIHugePages)
test/e2e/common/storage/downwardapi.go:                 e2eskipper.SkipUnlessFeatureGateEnabled(kubefeatures.LocalStorageCapacityIsolation)
test/e2e/storage/volume_limits.go:              e2eskipper.SkipIfFeatureGateEnabled(kubefeatures.CSIMigration)
```

Those might also be candidates for removal, but I first want to see that some job really fails.

**Comment by pohly** [comment]
@aojea perhaps take another look and if you agree with the approach, add LGTM?

**Comment by aojea** [comment]
> . We just have to ensure that this common code then doesn't get used incorrectly in test suites where it doesn't work as expected.

my comment was about if really we want to have this dependency in the framework?

anyway, this is better than before, thanks for doing this

/lgtm
/approve

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

Once we will introduce the FeatureGate tag (https://github.com/kubernetes/enhancements/issues/3041), it will be more natural to set up test definitions.

**Pull request merged**
