### PR TITLE
Use lock in eventBroadcasterImpl#refreshExistingEventSeries

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Currently read lock is used in eventBroadcasterImpl#refreshExistingEventSeries .
Since eventCache is modified, we should use (write) lock.

Also renamed two variables to better reflect their usage.

This is related to #65782

```release-note
NONE
```

### CODE REVIEW

**Comment by tedyu** [comment]
cc @yastij @wojtek-t

**Review by yastij — APPROVED** [review]
/lgtm
/assign @wojtek-t

**Pull request merged**
