### PR TITLE
Keep event reason in kubelet consistent with others

### PR DESCRIPTION
**Pull request by jiangyaoguo**
As talking in #12464,  Event.Reason should be CamelCase (starting with a capital letter), as with Reason everywhere in the API.

### CODE REVIEW

**Comment by gmarek** [comment]
@k8s-bot ok to test

**Comment by liggitt** [comment]
there are also `failedScheduling` events in `k8s.io/kubernetes/plugin/pkg/scheduler/scheduler.go`

**Comment by jiangyaoguo** [comment]
@liggitt Later I'll check other parts of kubernetes and change them to keep consistent in another pr.

**Comment by bgrant0607** [comment]
I think you need to rebase in order to get the tests to run properly.

**Comment by piosz** [comment]
Shippable is failing while trying to verify gendocs. Rebase should fix the problem. Could you do it?

**Comment by piosz** [comment]
Thanks for the change!

**Pull request merged**
