### PR TITLE
e2e_node: stop using deprecated framework.ExpectEqual

### PR DESCRIPTION
**Pull request by Songjoy**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
e2e_node: stop using deprecated framework.ExpectEqual

#### Which issue(s) this PR fixes:

Ref https://github.com/kubernetes/kubernetes/pull/115961

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by swatisehgal — COMMENTED** [review]
/lgtm

**Comment by swatisehgal** [comment]
/assign @SergeyKanzhelev 
for approval

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
