### PR TITLE
kubeadm: graduate the UnversionedKubeletConfigMap FG to GA

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?

/kind deprecation cleanup feature

#### What this PR does / why we need it:

cmd/kubeadm

- lock the FG to true by default
- cleanup wrappers and logic related to versioned vs unversioned
naming of API objects (CMs and RBAC)
- update unit tests

test/e2e_kubeadm

- don't require clusteconfiguration.kubernetesVersion
- use the helper functions GetConfigMap, ExpectRole, ExpectRoleBinding
(these were used before UnversionedKubeletConfig went Beta)

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/kubeadm/issues/1582

#### Special notes for your reviewer:
NONE

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: graduate the kubeadm specific feature gate UnversionedKubeletConfigMap to GA and lock it to "true" by default. The kubelet related ConfigMap and RBAC rules are now locked to have a simplified naming "*kubelet-config" instead of the legacy naming "*kubelet-config-x.yy", where "x.yy" was the version of the control plane. If you have previously used the old naming format with UnversionedKubeletConfigMap=false, you must manually copy the config map from kube-system/kubelet-config-x.yy to kube-system/kubelet-config before upgrading to 1.25.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/2915
```

### CODE REVIEW

**Comment by neolit123** [comment]
/hold for review
/cc @pacoxu 

/cc @fabriziopandini @sbueringer 
FYI related to CAPI.

**Comment by pacoxu** [comment]
If user upgraded the cluster in v1.24 using `kubeadm-v1.24 upgrade apply v1.24.x --feature-gates=UnversionedKubeletConfigMap=false`, the user have to run `kubeadm-v1.24 upgrade apply v1.24.x --feature-gates=UnversionedKubeletConfigMap=true` before running`kubeadm-v1.25 upgrade apply v1.25.x`.
This is not expected. 


We should lock the feature gate to true in v1.25, but we have to keep the logic of legacy code until we remove this feature gate.

- v1.24: we allow `kubeadm-v1.24 upgrade apply v1.24.x --feature-gates=UnversionedKubeletConfigMap=false`
- - user can use only kubelet-config-1.24 configmap.
- v1.25: we disallow `kubeadm-v1.25 upgrade apply v1.25.x --feature-gates=UnversionedKubeletConfigMap=false`
- - user have to use `kubelet-config` configmap
- v1.26 or v1.27: we remove the feature gate and the legacy logic.

**Comment by neolit123** [comment]
> If user upgraded the cluster in v1.24 using kubeadm-v1.24 upgrade apply v1.24.x --feature-gates=UnversionedKubeletConfigMap=false, the user have to run kubeadm-v1.24 upgrade apply v1.24.x --feature-gates=UnversionedKubeletConfigMap=true before runningkubeadm-v1.25 upgrade apply v1.25.x.
The user will fail to upgrade directly to v1.25 as kubelet-config configmap does not exist in his cluster.
This is not expected.

maybe we can add text in the release note about it.

e.g. "if you were not using the new naming format (UnversionedKubeletConfigMap=false) you must manually create / copy the new unversioned kubelet config map 'kube-system/kubelet-config'" before upgrading to 1.25"

> We should lock the feature gate to true in v1.25, but we have to keep the logic of legacy code until we remove this feature gate.

hm, but the kubeadm 1.25 binary is expected to upgrade to 1.25.x versions and not 1.24.x.
i think we just have to instruct the users that 1.25 needs the "kubelet-config" naming.

**Comment by pacoxu** [comment]
> hm, but the kubeadm 1.25 binary is expected to upgrade to 1.25.x versions and not 1.24.x.
> i think we just have to instruct the users that 1.25 needs the "kubelet-config" naming.

That is acceptable. 
/lgtm

**Comment by neolit123** [comment]
our CI is broken due to failing prow pods, we might as well wait until that is resolved before merging.
also this is still an issue in CI:
https://github.com/kubernetes/kubeadm/issues/2671#issuecomment-1145899432

**Comment by neolit123** [comment]
/hold cancel
CI is green

**Pull request merged**
