### PR TITLE
rename stop.go to delete.go to avoid confusion

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

Refer to [comments](https://github.com/kubernetes/kubernetes/pull/46784#issuecomment-317582927) from @foxish and @janetkuo  

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
xref #46784

**Special notes for your reviewer**:

/cc @janetkuo @foxish 

**Release note**:

```release-note
rename stop.go file to delete.go to avoid confusion
```

### CODE REVIEW

**Comment by foxish** [comment]
cc/ @kubernetes/sig-cli-pr-reviews for approval.

**Comment by shiywang** [comment]
LGTM, thanks for renaming it, could you also squash your commits ?

**Comment by dixudx** [comment]
@shiywang Updated. PTAL. Thanks.

**Comment by dixudx** [comment]
@janetkuo @foxish PTAL. Needs your `/lgtm` and `/approval`. Thanks.

**Comment by dixudx** [comment]
@adohe @derekwaynecarr @janetkuo @foxish Rebased. PTAL. Thanks.

**Comment by dixudx** [comment]
Test failure is due to #49844.

**Pull request merged**
