### PR TITLE
The TODO has been completed, so remove the comments

### PR DESCRIPTION
**Pull request by hanxiaoshuai**
The TODO has been completed in [PR](https://github.com/kubernetes/kubernetes/commit/eeb582e53f76aee9b70a051e1fe0199e8f572bae#diff-0b1de4365e4b0b50a13f26ff0718342b) so remove the comments.

### CODE REVIEW

**Comment by hanxiaoshuai** [comment]
@hzxuzhonghu @sttts

**Comment by hzxuzhonghu** [comment]
/lgtm

@sttts for approval.

**Pull request merged**
