### PR TITLE
Protected attributes

### PR DESCRIPTION
**Pull request by olegshaldybin**
This change adds support for protected attributes to RBAC API group. Protected attributes allow users to associate certain labels and annotations with RBAC roles: only users in these roles can add or modify objects with protected attributes.

This enables fine-grained authorization based on the object metadata. It should be possible to build complex policies for services, images and other objects based on labels and annotations, and use protected attributes to prevent unprivileged users from using that metadata.

Please see [proposal](https://github.com/olegshaldybin/kubernetes/blob/protected-attributes/docs/proposals/protected-attributes.md) and [documentation](https://github.com/olegshaldybin/kubernetes/blob/protected-attributes/docs/admin/protected-attributes.md) for more details.

[Analytics]()

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/27330)

### CODE REVIEW

**Comment by olegshaldybin** [comment]
@ericchiang @erictune @liggitt @smarterclayton PTAL so we can discuss this approach and its implications, or at-mention whoever you think might be interested. There are some interesting use cases that protected attributes can enable. Looking forward to discuss some of those. Please note that I am only starting to learn K8S internals and might be missing some changes. I did some manual testing in addition to unit tests though, and planning to add integration tests too.

This should be considered an experimental alpha API, just like RBAC itself. 

Needs #26680 for unit tests to go green (as they expect proper filtering on a clientset).
Needs #27193 in order for deletes to respect protected attributes.

**Comment by smarterclayton** [comment]
xref #2211 #17549 #7893 for backstory

**Comment by smarterclayton** [comment]
#15390 is probably the controlling proposal at this point.  We have general agreement that we want to do field level access control sometime soon, but labels and annotations (and taints and tolerations and selectors) may be special cases of that.

**Comment by smarterclayton** [comment]
It would be good to update the documentation you've added to be more in the proposal style - see some of the more recent items in the proposals directory for some sections to flesh out.

**Comment by olegshaldybin** [comment]
@smarterclayton Sounds good, I'll create a more detailed proposal with some context on use cases and alternatives considered. Thanks for cross-referencing!

**Comment by olegshaldybin** [comment]
Added [proposal](https://github.com/olegshaldybin/kubernetes/blob/protected-attributes/docs/proposals/protected-attributes.md).

**Comment by smarterclayton** [comment]
@kubernetes/sig-auth we should queue this up for the next meeting to discuss

**Comment by deads2k** [comment]
> @kubernetes/sig-auth we should queue this up for the next meeting to discuss

Yes, I think we need to discuss a few points that the proposal here hinted at, but didn't go into enough depth describing.  Having true, field level authorization is hard, but I also thinks its where the most value is.  It would require having the external representation of the object in admission, but once you have that, labels and annotations become special cases.

I think there should also be a broader discussion of what a field level policy rule should look like.  This is focused on a simple "allow mutation or disallow mutation", but bounded ranges and enumerated literals are also very high value: "he can scale it, but not below 5 or above 10" and "he can set this field,  but only to A or B".  If API server config moves into etcd, we'll probably want the ability to extend these into something like IP addresses in or out of CIDR.

We also need to decide whether these will be deny rules, allow rules, or a mix.  The mix is most convenient, but we punted on that from RBAC for a reason.  We could re-evaluate for field level policy rule mutation.

Those are the first few that concern me, there may be others.  I think that I'll defer reviewing this implementation until I feel like we've settled where we want to go.

@olegshaldybin Will you be able to attend sig-auth tomorrow?

**Comment by olegshaldybin** [comment]
@deads2k Sure, what time does it start? Do I need to register somewhere?

**Comment by deads2k** [comment]
I've added this to the agenda for tomorrow, 2pm eastern.  You can find the connection info here: https://docs.google.com/document/d/1woLGRoONE3EBVx-wTb4pvp4CI7tmLZ6lS26VTbosLKM/edit?ts=570fa5c5#

**Comment by olegshaldybin** [comment]
Let me address some concerns about generic field-level authorization before tomorrow's meeting.

I do agree that generic field-level authorization is very useful, and that was one of the early approaches I took. It poses several challenges though.

With labels and annotations k8s admins can create arbitrary taxonomies based on the needs of the environment. For example, some labels might be reserved for particular aspects of the workload: for example "env" label value can be "dev", "test", or "production". Annotations are even more powerful in that regard, since they can add any kind of metadata that can be treated by controllers as they see fit. And most, if not all, objects in k8s can have be labeled or annotated, giving us a great way to categorize them and tweak their behavior.

Now, from policy and compliance perspective, k8s admins will probably want to create different types of policies based on the label/annotation taxonomy they introduced. A simple example is image policy: production workloads must use only a small set of trusted registries. Policies that declare declare facts like that will benefit from being introduced separately from any authorization scheme. 

Attribute-based authorization takes care of checking that only users who have enough permissions can use "env: production" label, and all policies key off that label to introduce compliance rules that apply to production workloads for different aspects: images, network, storage, secrets etc. With that approach we can have a clean modular pipeline: user's identity (authN plugin) -> role-based admission (authZ plugin) -> role-based resource taxonomy (admission via protected attributes) -> policies (policy controllers, can be admission and/or continuous compliance monitoring). 

With this approach domain-specific restrictions (IP ranges, network access, allowed storage types etc.) can be enforced based on the workload type (via labels/annotations) and implemented via separate controllers that don't need to know anything about authorization mode being used. For example, current network policy that could be seamlessly integrated with protected attributes, as it's using a well-known annotation to enable/disable network policy in the namespace, and labels to select workloads that should be a subject to certain egress/ingress restrictions.

Another challenge with any kind of generic field-based authorization is maintaining compliance over time: say role A can use a certain range of values for some attribute, and role B can use a different range. There are two potential problems:

- admission complexity: if requester is a member of both roles, we need to merge ranges somehow in order to make the admission decision. That might require a specific domain knowledge that is better to handle in its own controller that knows how to handle resources of a certain kind;

- compliance tracking: let's say we want to observe the state of the system and decide whether it's compliant with a current set of policies. If these policies are based on the properties of resources themselves (e.g. labels/annotations), then the answer becomes unambiguous (e.g. there is a production workload that uses DockerHub, immediately mark it as non-compliant, doesn't matter who actually created it). However, if field restrictions are based on the property of the requester (e.g. their role), it's hard to tell whether policy has been violated: the answer now depends on who's asking. Of course we could introduce field-based authorization not based on the requester's role, but that would have a very limited usefulness, since the whole point of authorization is to make sure that different rules apply to different categories of users.

I hope all of that makes at least some sense. Let's discuss further on the PR and in tomorrow's sig-auth meeting. I'll be happy to answer any questions you have.

**Comment by smarterclayton** [comment]
@bgrant0607 as well for some of the historical context on authorization based on labels at google and where it worked and didn't - there was a discussion a while ago on it but I can't find the comment that captured the summary.

**Comment by deads2k** [comment]
@olegshaldybin sig-auth cancelled this week.

**Comment by erictune** [comment]
We discussed this in the SIG meeting.  @deads2k had some comments which I will let him summarize.

I suggested that we needed:

- an idea how this might apply to specific fields, so that we aren't forcing people to use labels and annotations for what should be first class values.
- more than 2 motivating use cases
- examples of how you would create ProtectedAttributes to solve a specific problem, like not letting user Alice create a Service with external load balancers.

**Comment by liggitt** [comment]
there was also a desire to build field-level authorization in a way that didn't require use of RBAC, and could work with other authorizers (possibly similar to the approach PodSecurityPolicy is taking, expressing field-level policy restrictions separately from the users/groups it applies to)

**Comment by erictune** [comment]
Other concerns:

- protected labels cannot automatically be propagated from a controller to its pod or vice versa (which is a useful thing to do).  
- if labels are used to control behavior, there will be a temptation to automatically add them, but really, labels are intended for users to organize things.  System added ones will clutter the view of labels.

**Comment by deads2k** [comment]
I think that I would start by trying to use jsonpath to select the set of nodes that are being used.  I haven't looked into it deeply, but assuming it's like xpath, you can easily end up with multiple nodes selected.  I would probably start without allowing backrefs.

The json path will have to be built against a given group/version/kind since the serialization format is important.  Evaluation via reflection is straightforward and I'd consider it acceptable for a initial implementation, but it is possible to implement a `Navigable` interface on objects that has a `Navigate(nextOperation op) interface{}`.  You can generate these methods from go types with json tags to allow navigation without reflection against the API objects you have.

I think we could start with the simplest kinds of field restrictions: "in" and "not-in".  Those are pretty easy for an initial implementation, but they will force you to consider evaluation order and trumping rules which will be essential for an extensible solution that can grow to include additional kinds of predicates.

**Pull request closed without merging**
