### PR TITLE
Skip TestLoopbackHostPortIPv6 run on non-IPv6 env

### LINKED ISSUE #94375: TestLoopbackHostPortIPv6 fails on non IPv6 environment
**What happened**:

TestLoopbackHostPortIPv6 fails when run in the machine where there is no IPv6 loopback device configured, with following error:

```
root@43386c5e349b:~/kubernetes# make check WHAT=./vendor/k8s.io/apiserver/pkg/server GOFLAGS=-v KUBE_TEST_ARGS='-run ^TestLoopbackHostPortIPv6 $'
+++ [0831 17:45:32] Running tests without code coverage
=== RUN   TestLoopbackHostPortIPv6
    config_selfclient_test.go:63: no ipv6 loopback interface
--- FAIL: TestLoopbackHostPortIPv6 (0.00s)
FAIL
FAIL	k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server	0.051s
FAIL
make: *** [Makefile:185: check] Error 1
root@43386c5e349b:~/kubernetes#
```

Especially running in the containers where IPv6 is not really configured for the runtime

**What you expected to happen**:

Unit tests shouldn't really depend on the environment it is running,

**How to reproduce it (as minimally and precisely as possible)**:

```
make check WHAT=./vendor/k8s.io/apiserver/pkg/server GOFLAGS=-v KUBE_TEST_ARGS='-run ^TestLoopbackHostPortIPv6 $'
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master

### PR DESCRIPTION
**Pull request by mkumatag**
**What type of PR is this?**

/kind bug
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #94375

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/uncc
not a reviewer or approver for apiserver. this is a unit test owned by the owners of apiserver.

**Review by hzxuzhonghu — COMMENTED** [review]
/lgtm

**Comment by mkumatag** [comment]
> @mkumatag: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-kubernetes-e2e-kind-ipv6	[a9c0c5a](https://github.com/kubernetes/kubernetes/commit/a9c0c5a9de80bc2f1c88f049a19fcbcff285c245)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/94376/pull-kubernetes-e2e-kind-ipv6/1300644588423221252)	`/test pull-kubernetes-e2e-kind-ipv6`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=94376). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3mkumatag). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

seems like this test is not liking my PR :(, lemme rerun again

/retest

**Comment by mkumatag** [comment]
@kubernetes/milestone-maintainers can someone help me tag v1.20 milestone,

Test only PR, impact on the release is very low.

**Pull request merged**
