### PR TITLE
Fix verify-licenses.sh

### LINKED ISSUE #122249: Does verify-licenses work?
When I run it manually, I get:

```
[ERROR] The following go-packages in the project have unknown or unreachable license URL:
google.golang.org/genproto/googleapis/api                                                            :  Apache-2.0           : https://github.com/googleapis/go-genproto/blob/23370e0ffb3e/googleapis/api/LICENSE
google.golang.org/genproto/googleapis/rpc                                                            :  Apache-2.0           : https://github.com/googleapis/go-genproto/blob/b8732ec3820d/googleapis/rpc/LICENSE
sigs.k8s.io/kustomize/api                                                                            :  Apache-2.0           : https://github.com/kubernetes-sigs/kustomize/blob/6ce0bf390ce3/api/LICENSE
sigs.k8s.io/kustomize/kustomize/v5/commands/build                                                    :  Apache-2.0           : https://github.com/kubernetes-sigs/kustomize/blob/6ce0bf390ce3/kustomize/LICENSE
sigs.k8s.io/kustomize/kyaml                                                                          :  Apache-2.0           : https://github.com/kubernetes-sigs/kustomize/blob/6ce0bf390ce3/kyaml/LICENSE
+++ [1209 10:28:28] [ERROR] Project is using go-packages with unknown or unreachable license URLs. Please refer to the CNCF's approved licence list for further information: https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md
```

Clearly that is wrong, it's just looking in the wrong place.  I also see a reference to https://github.com/google/go-licenses/pull/110 which is still open 2 years later.

Does this script run?  Is it useful?

### PR DESCRIPTION
**Pull request by thockin**
This still feels like a hack, but less horrible now.  Running this pases without error.

Fixes #122249

/kind cleanup
/kind bug

```release-note
NONE
```

### CODE REVIEW

**Review by hwdef — COMMENTED** [review]
/lgtm

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve
/triage accepted

**Pull request merged**
