### PR TITLE
tests: Use E2E framework deployments

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind cleanup
/sig testing

#### What this PR does / why we need it:

Deployments can be created easier with the ``NewDeployment`` found in ``test/e2e/framework/deployment``.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by claudiubelu** [comment]
@oomichi , can you lgtm again? It was lost because of the rebase.

**Comment by oomichi** [comment]
Thanks for rebasing.

/lgtm

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
I dunno.  For one-off reading a test this feels less friendly, because now I need to bounce around to another function vs. having all of the literal data right in front of me.  On the other hand, this is quicker to scan once you're familiar with it.

**Pull request merged**
