### PR TITLE
Prevent garbage collector from attempting to sync with 0 resources

### LINKED ISSUE #60037: Garbage collector in controller manager stops working
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I am running etcd-operator in kubernetes, and noticed that when I deleted the etcdcluster (Custom resource definition) the pods & services did not get cleaned up. I looked on another kube environment I had running, and on that env everything worked as expected. I checked logs, and could see on the env that was working I saw the following messages in Controller manager logs:
```
I0215 08:59:06.659783       1 garbagecollector.go:371] processing item [v1/Pod, namespace: etcd-operator, name: example-etcd-cluster-thcr8pfv89, uid: c9cdb6d7-122d-11e8-b4ac-068cfe9de373]
I0215 08:59:06.659871       1 garbagecollector.go:371] processing item [v1/Service, namespace: etcd-operator, name: example-etcd-cluster-client, uid: c9d238bc-122d-11e8-b4ac-068cfe9de373]
```
I didn't see these in the env that wasn't working, so I started looking at the garbage collector on there.

I noticed that there hadn't been any log message from garbage collecor since 31st Jan, when this was logged:
```
I0131 10:14:31.617880       1 controller_utils.go:1041] Waiting for caches to sync for garbage collector controller
```
Around this time we experienced some environmental network issues, which caused lots of errors around that time, such as:
```
E0131 10:13:31.691887       1 cronjob_controller.go:113] can't list Jobs: the server was unable to return a response in the time allotted, but may still be processing the request (get jobs.batch)
E0131 10:13:58.322978       1 node_controller.go:1022] Error updating node 10.143.115.218: the server was unable to return a response in the time allotted, but may still be processing the request (put n
odes 10.143.115.218)
E0131 10:14:31.617808       1 memcache.go:150] couldn't get current server API group list; will keep using cached value. (the server was unable to return a response in the time allotted, but may still b
e processing the request)
```

It looks like these issues may have caused the garbage collector to get into some sort of hung state?

When I restarted controller manager everything started working as expected.

**What you expected to happen**:
Garbage collector should have kept running, and working as expected.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure on the exact sequence that caused it, but suspect it was related to a time period when errors were occurring.

**Anything else we need to know?**:
We have `--leader-elect=false` set, and had previously hit this garbage collector issue -> https://github.com/kubernetes/kubernetes/issues/57044
However, we are running with Kube 1.8.6 with the fix for that issue cherry-picked (commit f5d5d18b2c2320e19ea3c0697c37a95d0009e628)

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.6-4+9c2a4c1ed1ee7e", GitCommit:"9c2a4c1ed1ee7e2e121203aa9a87315633a89eca", GitTreeState:"clean", BuildDate:"2018-01-22T08:23:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.6-4+9c2a4c1ed1ee7e", GitCommit:"9c2a4c1ed1ee7e2e121203aa9a87315633a89eca", GitTreeState:"clean", BuildDate:"2018-01-22T08:23:41Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
IBM Cloud
- OS (e.g. from /etc/os-release):
Ubuntu "16.04.3 LTS (Xenial Xerus)"
- Kernel (e.g. `uname -a`):
4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

I will attach logs from Controller manager.

### PR DESCRIPTION
**Pull request by jennybuckley**
**What this PR does / why we need it**:
As of #55259 we enabled garbagecollector.GetDeletableResources to return partial discovery results (including an empty set of discovery results).
This had the unintended consequence of allowing the garbage collector to enter a blocked state that can only be fixed by restarting.

From [this comment](https://github.com/kubernetes/kubernetes/issues/60037#issuecomment-372801088):

> 1. The Sync function periodically calls GetDeletableResources
>
> 2. According to the comment above GetDeletableResources, All discovery errors are considered temporary. Upon encountering any error, GetDeletableResources will log and return any discovered resources it was able to process (which may be none)., an error in discovery causes the discovery client to no longer discover resources in the cluster, but instead of failing and returning an error, it simply logs the error as garbagecollector.go:601] failed to discover preferred resources: %vthe server was unable to return a response in the time allotted, but may still be processing the request and returns an empty list of resources
>
> 3. The Sync function, upon recieving an empty resource list from discovery, detects that the resources have changed, and calls resyncMonitors, which calls dependencyGraphBuilder.syncMonitors with map[] as the argument as shown in the log as garbagecollector.go:189] syncing garbage collector with updated resources from discovery: map[], which sets the list of monitors to an empty list because it thinks there are no resources to monitor.
>
> 4. Lastly the Sync function calls controller.WaitForCacheSync, which calls cache.WaitForCacheSync, which will continually retry the garbagecollector.IsSynced function until it returns true, but it will always return false because len(gb.monitors) is 0.

This PR prevents that specific race condition from arising.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #60037

**Release note**:
```release-note
Fix bug allowing garbage collector to enter a broken state that could only be fixed by restarting the controller-manager.
```

### CODE REVIEW

**Comment by lavalamp** [comment]
Looks awesome, and given the failure mode, looks like an equally awesome unit test shouldn't be too hard to add? :)

**Comment by jennybuckley** [comment]
@lavalamp I have a unit test running locally which fails before this commit and passes after, but it only works by modifying the monitors to always say they are synced. Once I figure out how to fake that part I will add it here.

**Comment by jennybuckley** [comment]
Resubmitting with just the test, to show that it fails, after that I'll submit the fix to show that it passes.

**Comment by jennybuckley** [comment]
Proof of test failure before the fix is made: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/61201/pull-kubernetes-bazel-test/36187/

**Comment by lavalamp** [comment]
I am a little worried that the test will be racy due to the time.Sleep()s, but I really want this fix. Maybe you can work on a followup?

/label status/approved-for-milestone

/lgtm
/approved

**Comment by janetkuo** [comment]
This is awesome, thanks @jennybuckley! Since this is introduced in 1.9, can we cherrypick this to 1.9?

**Comment by jennybuckley** [comment]
Yes, also the bug causing PR has been cherrypicked to 1.8 as well, so I think we should cherrypick this to 1.8 and 1.9

**Pull request merged**
