### PR TITLE
add UT code for cleanLegacyBindAddr

### PR DESCRIPTION
**Pull request by xujieasd**
**What this PR does / why we need it**:
As #65264 merged，need UT code for function `cleanLegacyBindAddr`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
This PR:
1) completes function for fake `NetLinkHandle` interface
2) adds UT code for `cleanLegacyBindAddr`
3) adds UT code for multi-port service update

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hanxiaoshuai** [comment]
/ok-to-test
cc @Lion-Wei @m1093782566

**Comment by m1093782566** [comment]
@Lion-Wei @islinwb Please help review this PR when you have a chance. 

In general, I am green on this PR.

**Comment by xujieasd** [comment]
Any plans to merge this? @m1093782566 @Lion-Wei

**Comment by m1093782566** [comment]
oops, I almost miss that.

/lgtm
/approve

THANKS!

**Comment by islinwb** [comment]
@xujieasd Pls fix the faild tests

**Comment by m1093782566** [comment]
@xujieasd ping me when tests are all green.

**Comment by xujieasd** [comment]
@m1093782566 OK， thanks all the time

**Comment by xujieasd** [comment]
@m1093782566 tests all green,  PTAL. thanks

**Comment by m1093782566** [comment]
Looks great!

/lgtm

**Pull request merged**
