### PR TITLE
Fix not-ready master node after upgrade.

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #27764

@davidopp

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

**Comment by wojtek-t** [comment]
@mikedanese

**Comment by piosz** [comment]
cc @mikedanese

**Comment by mwielgus** [comment]
lgtm

**Comment by piosz** [comment]
@k8s-bot e2e test this issue: #ingore

**Comment by gmarek** [comment]
A bit more context: implementation of `get-env-val` shadowed the correct one from `cluster/common.sh`.

**Comment by piosz** [comment]
Merging manually to unblock upgrade tests.

**Pull request merged**
