### PR TITLE
Improve lock performance

### PR DESCRIPTION
**Pull request by sourcelliu**
Signed-off-by: mantuliu <240951888@qq.com>

#### What type of PR is this?
/kind cleanup
/sig apps

#### What this PR does / why we need it:
Where read-only, use a read-only lock
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by atiratree** [comment]
/lgtm

@sourcelliu can you please put `NONE` into the release note section?

**Comment by sourcelliu** [comment]
> /lgtm
> 
> @sourcelliu can you please put `NONE` into the release note section?


Done, thanks.

**Pull request merged**
