### PR TITLE
remove duplicate imported util/feature

### PR DESCRIPTION
**Pull request by ycyaoxdu**
Signed-off-by: ycyaoxdu <yaoyuchen0626@163.com>

#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

removed duplicate import of `k8s.io/apiserver/pkg/util/feature`

#### Does this PR introduce a user-facing change?

NONE

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
/lgtm

**Comment by ycyaoxdu** [comment]
@smarterclayton PTAL

**Pull request closed without merging**
