### PR TITLE
Remove unnecessary calls to cloud provider

### LINKED ISSUE #30700: ServiceController createLoadBalancerIfNeeded makes unneeded calls to cloud provider
The service controller can make an unnecessary call to the cloud provider to get a load balancer for the service, even if one is not defined, if that service is updated: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/service/servicecontroller.go#L263

... this can surface to the user with an event that makes it look like:
1.  The service controller incorrectly attempted to create a load balancer
2.  That incorrect load balancer creation failed

...if the cloud account isn't permissioned to get load balancers.

Example:

```
2016-08-15T23:28:29Z   2016-08-15T23:28:29Z   1         cakephp-mysql-example   Service             Warning   CreatingLoadBalancerFailed   {service-controller }   Error creating load balancer (will retry): Error getting LB for service dakinitest/cakephp-mysql-example: AccessDenied: User: :user/cloud_provider is not authorized to perform: elasticloadbalancing:DescribeLoadBalancers
```

The fix should be to:
1. Not make the `GetLoadBalancer` call if it is unnecessary (ie, if the service was updated, but never had type=LoadBalancer
2. If the behavior is that the controller is deleting the load balancer, the event associated with a failure should not be `CreatingLoadBalancerFailed`

### PR DESCRIPTION
**Pull request by pmorie**
Fixes #30700, includes some bonus cleanup of the code at no additional cost. :turkey:

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34271)

### CODE REVIEW

**Comment by pmorie** [comment]
@k8s-bot e2e test this issue: #IGNORE

**Comment by derekwaynecarr** [comment]
Opened to argue https://github.com/kubernetes/kubernetes/issues/34629 that you should never be allowed to switch service types as it really cleans a lot of this logic up more...

**Comment by pmorie** [comment]
@k8s-bot test this issue: #34636

**Comment by pmorie** [comment]
I am not at all sure that this PR is necessary any longer.

**Comment by pmorie** [comment]
I don't think this is necessary anymore.  Will re-open if I change my mind.

**Comment by amitkgupta** [comment]
I think this PR might fix #39214, which has nothing to do with changing the type of the service.  Any chance of re-opening?

**Comment by Amit-PivotalLabs** [comment]
@pmorie sorry I didn't ping you in my previous comment, would you consider re-opening?  I think this PR may solve a different issue: #39214.

**Pull request closed without merging**
