### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by jihoon-seo**
#### What type of PR is this?

/kind cleanup
/kind documentation

#### What this PR does / why we need it:

The directory https://github.com/kubernetes/community/tree/master/contributors/design-proposals/ was archived to
a separated GitHub repo: https://github.com/kubernetes/design-proposals-archive ,
and this caused many links to be broken.
This PR is to fix those broken links.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/website/pull/36208#discussion_r953398191

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jihoon-seo** [comment]
Build log of the job `pull-kubernetes-dependencies` says that
the result of running `hack/verify-vendor.sh` was not successful.

In this PR I modified `vendor/sigs.k8s.io/kustomize/kyaml/resid/gvk.go` file,
but it seems that I cannot edit this file directly, but should update the upstream file: https://github.com/kubernetes-sigs/kustomize/blob/master/kyaml/resid/gvk.go .

**Comment by jihoon-seo** [comment]
For this PR, I can proceed after:
- kustomize team create a new tag for kustomize itself. and
- k/k dependency (go.mod) be updated to import/require the newly created version of kustomize.

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by dims** [comment]
This PR has the label work-in-progress, please revisit to see if you still need this, please close if not

**Comment by jihoon-seo** [comment]
The last kustomize tag is v4.5.7 which was created on Aug 3, more than 3 months ago.
Since a newer tag has been not created for certain amount of time, I cannot proceed anymore.
It would be good for me to close this PR.

**Pull request closed without merging**
