### PR TITLE
Remove cassandra example.

### PR DESCRIPTION
**Pull request by aledbf**
**What this PR does / why we need it**:

Removes duplicated content from this repository and `kubernetes/examples`

https://github.com/kubernetes/examples/tree/master/cassandra

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by aledbf** [comment]
Updating the kubernetes.io docs now

**Comment by BenTheElder** [comment]
/cc
PR needs a rebase / has a merge conflict.

**Comment by kargakis** [comment]
Needs a rebase

**Comment by ahmetb** [comment]
FYI this is probably the last PR we'll accept before making kubernetes/examples READONLY. Once this is in, we'll proceed with the blockade at FWIW this is currently blocking https://github.com/kubernetes/test-infra/pull/6964

**Comment by aledbf** [comment]
@ahmetb I will remove the link to k/examples.

**Comment by ahmetb** [comment]
not sure which link you're referring to. you can keep the current changes to `examples/storage/cassandra/README.md`.

**Review by zouyee — APPROVED** [review]

**Comment by zouyee** [comment]
PR needs a rebase. 😄

**Comment by aledbf** [comment]
Can someone help me to with the bazel build?
Running `./hack/update-bazel.sh` doesn't update any BUILD files
Thanks

**Comment by aledbf** [comment]
The reason of the failure is https://github.com/kubernetes/kubernetes/issues/60447

**Comment by BenTheElder** [comment]
not sure what's up with some of these tests here but [I think they're going to sort themselves out this time](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/60147/pull-kubernetes-verify/79561/) :crossed_fingers:, keeping an eye towards this PR

**Comment by ahmetb** [comment]
FYI you can just say `/retest` to get them all kicked off (or combine them in a single comment)

**Comment by BenTheElder** [comment]
tentatively this needs an actual `./hack/update-bazel.sh`
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/60147/pull-kubernetes-verify/79576/

**Comment by BenTheElder** [comment]
I would try to rebase this first, since there was a fix to that script

**Comment by BenTheElder** [comment]
I think this will hit green now once the cross job finishes, it looks green so far. :crossed_fingers:

**Comment by BenTheElder** [comment]
@ahmetb this is green now if you want to review / LGTM then we can get this in finally.

**Pull request merged**
