### PR TITLE
fix some typo

### PR DESCRIPTION
**Pull request by Abirdcfly**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MadhavJivrajani** [comment]
A spell check is done as part of the CI: https://github.com/kubernetes/kubernetes/blob/master/hack/verify-spelling.sh
Is the goal here to replace this?

**Comment by Abirdcfly** [comment]
> A spell check is done as part of the CI: https://github.com/kubernetes/kubernetes/blob/master/hack/verify-spelling.sh Is the goal here to replace this?

Sorry for the rough first pr,  Let me first figure out why misspell didn't check out retrive -> retrive and deleteing ->deleting, and then re-open this pr. 😂

**Comment by Abirdcfly** [comment]
> > A spell check is done as part of the CI: https://github.com/kubernetes/kubernetes/blob/master/hack/verify-spelling.sh Is the goal here to replace this?
> 
> Sorry for the rough first pr, Let me first figure out why misspell didn't check out retrive -> retrive and deleteing ->deleting, and then re-open this pr. 😂

I figured it out.

The golangci-lint use a [fork](https://github.com/golangci/misspell) of [original misspell](https://github.com/client9/misspell) which add [more pr](https://github.com/client9/misspell/compare/master...golangci:master). 

The [original misspell](https://github.com/client9/misspell)'s latest merge is [9 Mar 2018](https://github.com/client9/misspell/commits/master). A [backporting  pr](https://github.com/client9/misspell/pull/168) has been committed to the original misspell repository for this change, but it remains in the open state.

And After my test, directly changing `github.com/client9/misspell` to `github.com/golangci/misspell` does not work. 

Because the [original misspell](https://github.com/client9/misspell) is hard-coded with a word list to distinguish miswriting, and the misspell project [directly references the package](https://github.com/client9/misspell/blob/master/cmd/misspell/main.go#L18), for this problem golangci's approach is close to [rewriting the main function](https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/misspell.go#L57) of misspll directly (not only for this reason, of course)

**Review by thockin — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
