### PR TITLE
Add shiywang to sig-cli help out review code

### PR DESCRIPTION
**Pull request by shiywang**
@pwittrock @fabianofranz @adohe @mengqiy I would like to help team review pr : ) 
```release-note
NONE
```

### CODE REVIEW

**Comment by shiywang** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by shiywang** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by mengqiy** [comment]
@shiywang Can you help change my GH handle as well in this PR? I have change it from `ymqytw` to `mengqiy`.

**Comment by shiywang** [comment]
@mengqiy sure, done

**Comment by pwittrock** [comment]
Thanks for the interest!  Great the you are interested in doing reviews.  How about we start by having you shadow / reverse shadow a number of PRs before automatically assigning them to you?  I'll start assigning some substantial PRs for you to review.  Lets leave this PR open, but please sort the GH handles.

**Comment by shiywang** [comment]
flag change && options changed:
https://github.com/kubernetes/kubernetes/pull/48751
https://github.com/kubernetes/kubernetes/pull/48684
https://github.com/kubernetes/kubernetes/pull/46546

validation compatibility between cli and api-server
https://github.com/kubernetes/kubernetes/pull/48433
https://github.com/kubernetes/kubernetes/pull/47962 (port range validation)
https://github.com/kubernetes/kubernetes/pull/48655  (deduce duplicate ingress ip with a map) 
https://github.com/kubernetes/kubernetes/pull/48082

printer realted
https://github.com/kubernetes/kubernetes/pull/48807
https://github.com/kubernetes/kubernetes/pull/48022
https://github.com/kubernetes/kubernetes/pull/48033

bash zsh completion related:
https://github.com/kubernetes/kubernetes/pull/48270  
https://github.com/kubernetes/kubernetes/pull/48553


minor fix, refactor code no feature added
https://github.com/kubernetes/kubernetes/pull/48595
https://github.com/kubernetes/kubernetes/pull/48079
https://github.com/kubernetes/kubernetes/pull/47675
https://github.com/kubernetes/kubernetes/pull/46510
https://github.com/kubernetes/kubernetes/pull/48572
https://github.com/kubernetes/kubernetes/pull/45645

translation
https://github.com/kubernetes/kubernetes/pull/46559

other bug fix
https://github.com/kubernetes/kubernetes/pull/45611
https://github.com/kubernetes/kubernetes/pull/41699
https://github.com/kubernetes/kubernetes/pull/48868


@pwittrock I think this is the list I've read the whole code and made my comments, there's still some swagger/openapi, client-discovery and strategic-merge-patch related pr I haven't take a look yet, I will take some time to learn those part of code asap.

**Pull request merged**
