### PR TITLE
Disabled HA master e2e test.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Disabled HA master e2e test.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33651)

### CODE REVIEW

**Comment by jszczepkowski** [comment]
CC @wojtek-t

**Comment by jszczepkowski** [comment]
@k8s-bot test this issue: #33646

**Comment by jszczepkowski** [comment]
@k8s-bot test this issue: #28462

**Comment by gmarek** [comment]
GCI tests are extremely flaky now. Merging to fix serial suite.

**Pull request merged**
