### PR TITLE
Remove no-longer used selflink code from kubelet

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref https://github.com/kubernetes/enhancements/issues/1164

```release-note
NONE
```

/kind cleanup
/priority important-longterm
/sig node

### CODE REVIEW

**Comment by matthyx** [comment]
Awesome!
/lgtm
/hold
(holding to prevent auto merge, just in case)

**Comment by wojtek-t** [comment]
> (holding to prevent auto merge, just in case)

@matthyx - do you want someone else to also take a look or it was really "just in case"?
[I would say we can just cancel the hold.]

**Comment by matthyx** [comment]
if you're ok with immediate merge, let's go
(it's an old habit from test-infra)
/unhold

**Comment by SergeyKanzhelev** [comment]
Maybe I'm missing something, but the enhancement referenced in this PR indicate that:

> In v1.20 (12 months and 4 release from v1.16) we will switch off the feature gate which will automatically disable setting SelfLinks. However it will still be possible to revert the behavior by changing value of a feature gate.
>
> In v1.21, we will get rid of the whole code propagating those fields and fields themselves. In the meantime, we will go over places referencing that field (see below) and get rid of those too.

The PR just removes things instead of locking the feature gate to true. In fact, this code was not guarded with the feature gate in 1.20. Is it still valid to remove this code?

I don't have much concerns about removal itself. I just want to make sure we are following the PRR and customers who had dependency on SelfLink being set will not get broken unexpectedly.

**Comment by wojtek-t** [comment]
> The PR just removes things instead of locking the feature gate to true. In fact, this code was not guarded with the feature gate in 1.20. Is it still valid to remove this code?

This PR is actually code cleanup, that isn't strictly related to the enhancement.
The main point of the the enhancement was to disable setting selfink by kube-apiserver. As part of preparation for that, we have have changed couple places to not rely on the selflink. The "compute reference" code was one of that. This was change unconditionally in 1.16 - previously it was relying on selflink, but we didn't need it and could get all the information from elsewhere so we changed that. 

We could have cleaned up this code in kubelet back then together - just missed that. But we could that any point later.

The main part of the enhancment will be done as part of https://github.com/kubernetes/kubernetes/pull/107527 - this PR was a pure cleanup that we could have done even in 1.16 after we changed the "get reference" function to stop relying on selflink.

**Comment by SergeyKanzhelev** [comment]
What if customer used the SelfLink of a pod in some script automation? Was this marked somehow for deprecation? What is the migration path, should we at least put the release note saying action required?

**Comment by wojtek-t** [comment]
> What if customer used the SelfLink of a pod in some script automation? Was this marked somehow for deprecation? What is the migration path, should we at least put the release note saying action required?

I'm assuming that it's now a more generic question (since the code changed in this particular PR was purely implementation detail - and whatever the user is doing this change doesn't affect it).

Yes - this was marked for deprecation in 1.16 (with release note) and then with 1.20 there was another release note that we stopped propagating it. We interviewed main cloud-providers and none of them allows for switching it on. We grepped through repositories and there doesn't seem to be any real usage of it. We were also talking to users and we didn't find any real usecase for that field. [You can find more detail in https://github.com/kubernetes/enhancements/pull/3118, there was also slack discussion linked there.]

**Pull request merged**
