### PR TITLE
Fix memory leak from global OpenTelemetry MeterProvider

### LINKED ISSUE #126918: APIServerTracing causing huge memory consumption/memory leak
### What happened?

Since updating from Kubernetes 1.26.* to 1.29.* we experiences OOM-Kills on control plane nodes.
After some investigation we found that adding `--feature-gates=APIServerTracing=false` to the `kube-apiserver` fixed the issue.
(Found this via pprof/heap of one apiserver: heap dump could be added if needed)

Before the update to 1.29.* the control planes were running with 4GB of memory with the same worklow in the cluster without issues. After the workarround using the feature gate the memory consumption of the whole control plane is not at ~2GB.

### What did you expect to happen?

In case there is an issue with other components, memory consumption of the apiserver should not be that excessive.

### How can we reproduce it (as minimally and precisely as possible)?

We just had the K8s cluster running and saw a permant increase in memory usage of the control plane nodes. And after some time (can not give a specific duration) the OS of the control plane node started to OOM kill processes.

### Anything else we need to know?

Let us know if you need additional information.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4
```

</details>

### Cloud provider

on-premise; control-planes are running with 4 CPU cores, 8GB of memory and and NVME discs

### OS version

<details>

```console
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux kube-master01-003 5.10.0-32-cloud-amd64 #1 SMP Debian 5.10.223-1 (2024-08-10) x86_64 GNU/Linux

```

</details>

### Install tools

<details>

```console
$ kubeadm version -o yaml
clientVersion:
  buildDate: "2024-04-16T15:05:51Z"
  compiler: gc
  gitCommit: 55019c83b0fd51ef4ced8c29eec2c4847f896e74
  gitTreeState: clean
  gitVersion: v1.29.4
  goVersion: go1.21.9
  major: "1"
  minor: "29"
  platform: linux/amd64
```

</details>

### Container runtime (CRI) and version (if applicable)

<details>

```console
$ crictl version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  1.6.31
RuntimeApiVersion:  v1
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by dashpole**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

Fix memory leak caused by https://github.com/open-telemetry/opentelemetry-go-contrib/issues/5190.  OpenTelemetry has a "delegating" MeterProvider that keeps track of instruments created using the API until a real implementation is added. However, it doesn't return existing instruments if the same instrument is created repeatedly, leading to a memory leak if repeatedly creating clients (grpc, in our case).

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/126918

#### Special notes for your reviewer:

I've opted to use an init function to set this because we are overriding the global default.

I'm doing this in the kubelet and APIServer because there are other users of component-base/tracing on github that may be actively using the metrics portions of the OTel libraries, which would be broken by adding it to component-base.

#### Does this PR introduce a user-facing change?
```release-note
Fixes a kubelet and kube-apiserver memory leak in default 1.29 configurations related to tracing.
```

@logicalhan

### CODE REVIEW

**Comment by dims** [comment]
@dashpole looks like we need to run update-vendor.sh

```
Your staging/src/k8s.io/component-base/go.mod file is different:
--- staging/src/k8s.io/component-base/go.mod	2024-08-28 02:01:54.849602050 +0000
+++ /tmp/verify-vendor.sh.CMWVM4/kubernetes/staging/src/k8s.io/component-base/go.mod	2024-08-28 02:04:51.836874324 +0000
@@ -20,6 +20,7 @@ require (
 	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.53.0
 	go.opentelemetry.io/otel v1.28.0
 	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.27.0
+	go.opentelemetry.io/otel/metric v1.28.0
 	go.opentelemetry.io/otel/sdk v1.28.0
 	go.opentelemetry.io/otel/trace v1.28.0
 	go.uber.org/zap v1.26.0
@@ -61,7 +62,6 @@ require (
 	github.com/pmezard/go-difflib v1.0.1-0.20181226105442-5d4384ee4fb2 // indirect
 	github.com/x448/float16 v0.8.4 // indirect
 	go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.28.0 // indirect
-	go.opentelemetry.io/otel/metric v1.28.0 // indirect
 	go.opentelemetry.io/proto/otlp v1.3.1 // indirect
 	go.uber.org/multierr v1.11.0 // indirect
 	golang.org/x/net v0.28.0 // indirect
Vendor Verify failed.
If you're seeing this locally, run the below command to fix this:
hack/update-vendor.sh
All pinned versions of checked dependencies match their preferred version.
```

**Comment by dashpole** [comment]
@dims fixed.  I've also moved the fix to the kubelet and apiserver respectively to not impact other users of component-base.

**Comment by dims** [comment]
@dashpole looks great! thanks.

/approve
/lgtm

**Comment by dashpole** [comment]
Long-term fix is here: https://github.com/open-telemetry/opentelemetry-go/pull/5754.  We will need to update otel to v1.30.0 after that is released

**Pull request merged**
