### PR TITLE
exclude kms provider from health check

### PR DESCRIPTION
**Pull request by zshihang**
Change-Id: Ie1f828b327c5eede8a0b105a8c3f8fc7affd6f3e

**What type of PR is this?**
/kind flake

```release-note
NONE
```

### CODE REVIEW

**Comment by MrHohn** [comment]
@shihan9 Any context? What flake would this address?

**Review by MrHohn — COMMENTED** [review]
/approve
/cc @cheftako

**Comment by MrHohn** [comment]
Discussed offline, this is addressing a flake regarding apiserver healthiness.

**Review by cheftako — COMMENTED** [review]
/lgtm

**Pull request merged**
