### PR TITLE
Add a sensible cloud provider timeout

### PR DESCRIPTION
**Pull request by edevil**
**What this PR does / why we need it**:
This PR adds a sensible timeout to cloud provider calls in the context of the node status logic. 

**Which issue(s) this PR fixes**:
This PR attempt to address the problems explained in #43516.

**Special notes for your reviewer**:

Afterwards we need to make sure cloud providers honor the context timeout.

```release-note
NONE
```

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/ok-to-test

**Comment by edevil** [comment]
@feiskyer The test failure does not seem related to my changes.

**Comment by edevil** [comment]
@Random-Liu @feiskyer Any feedback on this?

**Pull request closed without merging**
