### PR TITLE
configure-vm.sh: Only "apt-get update" when we need to install a package

### LINKED ISSUE #22071: Investigate long bootup time of containervm instance
I noticed that there is a huge regression on node bootup since Wednesday last couple of days:

Bad one:
```
Feb 26 18:29:19 e2e-test-dawnchen-minion-0x00 startupscript: Running startup script /var/run/google.startup.script
Feb 26 18:29:19 e2e-test-dawnchen-minion-0x00 startupscript: == kube-up node config starting ==
Feb 26 18:29:20 e2e-test-dawnchen-minion-0x00 startupscript: Networking functional on e2e-test-dawnchen-minion-0x00 (10.240.0.3)
Feb 26 18:29:20 e2e-test-dawnchen-minion-0x00 startupscript: == Refreshing package database ==
Feb 26 18:29:20 e2e-test-dawnchen-minion-0x00 startupscript: Get:1 http://download.gluster.org wheezy Release.gpg [490 B]
Feb 26 18:29:20 e2e-test-dawnchen-minion-0x00 startupscript: Get:2 http://download.gluster.org wheezy Release [1561 B]
Feb 26 18:29:20 e2e-test-dawnchen-minion-0x00 startupscript: Get:3 http://download.gluster.org wheezy/main amd64 Packages [1503 B]
Feb 26 18:29:20 e2e-test-dawnchen-minion-0x00 startupscript: Ign http://download.gluster.org wheezy/main Translation-en
Feb 26 18:29:20 e2e-test-dawnchen-minion-0x00 startupscript: Get:4 http://httpredir.debian.org wheezy-updates Release.gpg [1554 B]
Feb 26 18:29:22 e2e-test-dawnchen-minion-0x00 startupscript: Get:5 http://security.debian.org wheezy/updates Release.gpg [1554 B]
Feb 26 18:29:22 e2e-test-dawnchen-minion-0x00 startupscript: Get:6 http://security.debian.org wheezy/updates Release [102 kB]
Feb 26 18:29:22 e2e-test-dawnchen-minion-0x00 startupscript: Get:7 http://security.debian.org wheezy/updates/main Sources [212 kB]
Feb 26 18:29:22 e2e-test-dawnchen-minion-0x00 startupscript: Get:8 http://security.debian.org wheezy/updates/main amd64 Packages [336 kB]
Feb 26 18:29:22 e2e-test-dawnchen-minion-0x00 startupscript: Get:9 http://security.debian.org wheezy/updates/main Translation-en [195 kB]
Feb 26 18:29:26 e2e-test-dawnchen-minion-0x00 startupscript: Get:10 http://httpredir.debian.org wheezy Release.gpg [2373 B]
Feb 26 18:29:26 e2e-test-dawnchen-minion-0x00 startupscript: Get:11 http://httpredir.debian.org wheezy-backports Release.gpg [1554 B]
Feb 26 18:29:26 e2e-test-dawnchen-minion-0x00 startupscript: Get:12 http://httpredir.debian.org wheezy-updates Release [143 kB]
Feb 26 18:29:26 e2e-test-dawnchen-minion-0x00 startupscript: Get:13 http://httpredir.debian.org wheezy Release [191 kB]
Feb 26 18:29:32 e2e-test-dawnchen-minion-0x00 startupscript: Get:14 http://httpredir.debian.org wheezy-backports Release [161 kB]
Feb 26 18:29:37 e2e-test-dawnchen-minion-0x00 startupscript: Get:15 http://httpredir.debian.org wheezy-updates/main Sources [3864 B]
Feb 26 18:29:38 e2e-test-dawnchen-minion-0x00 startupscript: Get:16 http://httpredir.debian.org wheezy-updates/main amd64 Packages [5599 B]
Feb 26 18:29:38 e2e-test-dawnchen-minion-0x00 startupscript: Get:17 http://httpredir.debian.org wheezy-updates/main Translation-en [3814 B]
Feb 26 18:29:38 e2e-test-dawnchen-minion-0x00 startupscript: Get:18 http://httpredir.debian.org wheezy/main Sources [5982 kB]
Feb 26 18:34:49 e2e-test-dawnchen-minion-0x00 startupscript: Get:19 http://httpredir.debian.org wheezy/main amd64 Packages [5840 kB]
Feb 26 18:39:33 e2e-test-dawnchen-minion-0x00 startupscript: Get:20 http://httpredir.debian.org wheezy/main Translation-en [3846 kB]
Feb 26 18:41:40 e2e-test-dawnchen-minion-0x00 startupscript: Get:21 http://httpredir.debian.org wheezy-backports/main Sources [449 kB]
Feb 26 18:41:57 e2e-test-dawnchen-minion-0x00 startupscript: Get:22 http://httpredir.debian.org wheezy-backports/main amd64 Packages [605 kB]
Feb 26 18:42:06 e2e-test-dawnchen-minion-0x00 startupscript: Get:23 http://httpredir.debian.org wheezy-backports/main Translation-en [376 kB]
Feb 26 18:42:14 e2e-test-dawnchen-minion-0x00 startupscript: Fetched 18.5 MB in **12min** 53s (23.9 kB/s)
```

vs. good one:
```
Feb 24 23:50:13 e2e-test-mixia-minion-ulvd startupscript: Running startup script /var/run/google.startup.script
Feb 24 23:50:13 e2e-test-mixia-minion-ulvd startupscript: == kube-up node config starting ==
Feb 24 23:50:13 e2e-test-mixia-minion-ulvd startupscript: Networking functional on e2e-test-mixia-minion-ulvd (10.240.0.3)
Feb 24 23:50:13 e2e-test-mixia-minion-ulvd startupscript: == Refreshing package database ==
Feb 24 23:50:14 e2e-test-mixia-minion-ulvd startupscript: Get:1 http://download.gluster.org wheezy Release.gpg [490 B]
Feb 24 23:50:14 e2e-test-mixia-minion-ulvd startupscript: Get:2 http://download.gluster.org wheezy Release [1561 B]
Feb 24 23:50:14 e2e-test-mixia-minion-ulvd startupscript: Get:3 http://security.debian.org wheezy/updates Release.gpg [1554 B]
Feb 24 23:50:14 e2e-test-mixia-minion-ulvd startupscript: Get:4 http://security.debian.org wheezy/updates Release [102 kB]
Feb 24 23:50:14 e2e-test-mixia-minion-ulvd startupscript: Get:5 http://download.gluster.org wheezy/main amd64 Packages [1503 B]
Feb 24 23:50:14 e2e-test-mixia-minion-ulvd startupscript: Get:6 http://httpredir.debian.org wheezy Release.gpg [2373 B]
Feb 24 23:50:14 e2e-test-mixia-minion-ulvd startupscript: Get:7 http://security.debian.org wheezy/updates/main Sources [212 kB]
Feb 24 23:50:14 e2e-test-mixia-minion-ulvd startupscript: Ign http://download.gluster.org wheezy/main Translation-en
Feb 24 23:50:14 e2e-test-mixia-minion-ulvd startupscript: Get:8 http://security.debian.org wheezy/updates/main amd64 Packages [336 kB]
Feb 24 23:50:14 e2e-test-mixia-minion-ulvd startupscript: Get:9 http://httpredir.debian.org wheezy-updates Release.gpg [1554 B]
Feb 24 23:50:14 e2e-test-mixia-minion-ulvd startupscript: Get:10 http://security.debian.org wheezy/updates/main Translation-en [195 kB]
Feb 24 23:50:14 e2e-test-mixia-minion-ulvd startupscript: Get:11 http://httpredir.debian.org wheezy-backports Release.gpg [1554 B]
Feb 24 23:50:14 e2e-test-mixia-minion-ulvd startupscript: Get:12 http://httpredir.debian.org wheezy Release [191 kB]
Feb 24 23:50:14 e2e-test-mixia-minion-ulvd startupscript: Get:13 http://httpredir.debian.org wheezy-updates Release [143 kB]
Feb 24 23:50:15 e2e-test-mixia-minion-ulvd startupscript: Get:14 http://httpredir.debian.org wheezy-backports Release [161 kB]
Feb 24 23:50:15 e2e-test-mixia-minion-ulvd startupscript: Get:15 http://httpredir.debian.org wheezy/main Sources [5982 kB]
Feb 24 23:50:15 e2e-test-mixia-minion-ulvd startupscript: Get:16 http://httpredir.debian.org wheezy/main amd64 Packages [5840 kB]
Feb 24 23:50:15 e2e-test-mixia-minion-ulvd startupscript: Get:17 http://httpredir.debian.org wheezy-updates/main amd64 Packages [5599 B]
Feb 24 23:50:15 e2e-test-mixia-minion-ulvd startupscript: Get:18 http://httpredir.debian.org wheezy/main Translation-en [3846 kB]
Feb 24 23:50:15 e2e-test-mixia-minion-ulvd startupscript: Get:19 http://httpredir.debian.org wheezy-updates/main Sources [3864 B]
Feb 24 23:50:15 e2e-test-mixia-minion-ulvd startupscript: Get:20 http://httpredir.debian.org wheezy-backports/main amd64 Packages [605 kB]
Feb 24 23:50:15 e2e-test-mixia-minion-ulvd startupscript: Get:21 http://httpredir.debian.org wheezy-updates/main Translation-en [3814 B]
Feb 24 23:50:15 e2e-test-mixia-minion-ulvd startupscript: Get:22 http://httpredir.debian.org wheezy-backports/main Sources [449 kB]
Feb 24 23:50:16 e2e-test-mixia-minion-ulvd startupscript: Get:23 http://httpredir.debian.org wheezy-backports/main Translation-en [376 kB]
Feb 24 23:50:20 e2e-test-mixia-minion-ulvd startupscript: Fetched 18.5 MB in **6s** (2747 kB/s)
Feb 24 23:50:22 e2e-test-mixia-minion-ulvd startupscript: Reading package lists...
```

Please note that the issue is not related to any kubernetes component. The node hasn't run salt client yet. This explains a lot of node not ready issue we have lately.  #18969

cc/ @zmerlynn #21086

### PR DESCRIPTION
**Pull request by zmerlynn**
Factors out package install and checks for package before "apt-get update"

Also fix another "echo sleep 5".

Fixes #22071

### CODE REVIEW

**Comment by justinsb** [comment]
LGTM

**Comment by zmerlynn** [comment]
Thanks for the fast review!

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
@k8s-oncall this should help with tons of node bootup issue we found during our jenkins, please merge it immediately once the tests are green. Thanks!

**Comment by davidopp** [comment]
The e2e failure here is
```
[Fail] Deployment [It] deployment should delete old replica sets 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:197
```

but I don't see a bug filed for it. Will do it now.

**Comment by davidopp** [comment]
Actually, not clear if that's the same as #21798

**Comment by davidopp** [comment]
Sorry, didn't mean to close, hit wrong button.

**Comment by davidopp** [comment]
@k8s-bot e2e test issue: #22088

**Comment by zmerlynn** [comment]
@davidopp: Thanks, beat me to it.

**Comment by davidopp** [comment]
I'm not sure why the e2e didn't start running yet - in the past it usually started very quickly after the command to k8sbot.

**Comment by davidopp** [comment]
@k8s-bot e2e test this issue: #22088

**Comment by fabioy** [comment]
Chatted with @zmerlynn, failure seems unrelated. Going to merge now.

**Pull request merged**
