### PR TITLE
Write a parallel (godeps) _workspace tree to hold all the missing files.

### PR DESCRIPTION
**Pull request by david-mcmahon**
Ref #23268
cc @ixdy @zmerlynn

### CODE REVIEW

**Comment by eparis** [comment]
Are all of these files which are not present in the specific commit we vendored in Godeps but are present in master? Or are any of these files which you believe godep should be saving and we should talk to @freeforms and/or file an issue with godep to (potentially) get them included in our versions?

**Comment by david-mcmahon** [comment]
I see at least one case where the vendored commit is older than the latest repo containing a missing file.  We should certainly update the pointer in Godeps.json in those situations.  Maybe even have update-godep-versions.sh automatically do it.

Some Godeps.json entries descend into subdirectories of packages like github.com/beorn7/perks/quantile for example and at that level there are no license files.  update-godep-licenses.sh then tries to find license/copyright files by looking at the root package.  It's not clear to me whether this is a bug or a feature of godeps, but I suspect we could file a bug to find that out.

**Comment by david-mcmahon** [comment]
Of course we can't update Godeps.json directly as it's generated.  How is that file getting it's hash pointers?  It's true that some are behind and the local vendored sources would otherwise have license/copyright files available.  
It is still the case though that sub-packages would be missing items.  Let's get this change in to satisfy the immediate issue and file an issue with godep to understand why the hashes are behind and the repo root files are not included.

**Comment by david-mcmahon** [comment]
Might #22807 help some of the issues we're trying to work around here?

**Comment by eparis** [comment]
`godep restore` will checkout the specified versions into your GOPATH
`gedep save` will update Godeps with the versions in your GOPATH.

So to update a version its best to:
```
cd $GOPATH/src/k8s.io/kubernetes
godep restore
cd $GOPATH/src/path/to/package
git checkout $SOME_NEW_VERSION
cd $GOPATH/src/k8s.io/kubernetes
godep save ./...
```

Is that what you were asking?

**Comment by david-mcmahon** [comment]
Oh I see.  That seems risky to add to the regular automated flow of course.  So this PR still stands.  We need to independently gather and store missing license/copyright files, regardless of where we pin the vendored sources.   It might be a good idea to clean up the _aux files though when the vendored packages finally include them.  I can address that in a follow up.

**Pull request merged**
