### PR TITLE
Automated cherry pick of #95451: Fix fcpath

### PR DESCRIPTION
**Pull request by mkumatag**
Cherry pick of #95451 on release-1.19.

#95451: Fix fcpath

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
NONE
```

### CODE REVIEW

**Review by saad-ali — APPROVED** [review]
/approve
/lgtm

**Comment by mkumatag** [comment]
@kubernetes/release-engineering can someone help me approving the cherry-pick?

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
