### PR TITLE
Increased the tolerated time for TestOfferStorage.

### LINKED ISSUE #25891: unit test flake: TestOfferStorage
Hit this in #25509

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25509/kubernetes-pull-test-unit-integration/26630/

[Log](https://00e9e64bac56e6ab763091cf4c6a56daf7ac2fa782f3cf747e-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F25509%2Fkubernetes-pull-test-unit-integration%2F26630%2Fartifacts%2Fjunit_v1,extensions-v1beta1,metrics-v1alpha1,federation-v1alpha1_20160518-214542.stdout?qk=AD5uMEvcowIsgEu1U1-NSdGSx4BeYRtqZ0IGgPIy_MULP7NAkMkbCt_1sGkRE9yqDfMm0WCs6adY-TOmKRxX7EtzppIdLxTDyJLN_YSkPhWl20x5KSXjDbaeuaC1guQQK1dxSHA8ieho2EfUzgiCKTrmquopAURyMoYhc8ZMrrMzyr0xw9O26Fpv9SQ6d8U7P1I37zmN0xp4APDJkeRvAhMjSI8a27PX5_V9X9pK1N9N4LFDfO3nij15JmcffziOggRdJugCSf3wY8_F_IKIZfFrdMryWzOstF4Jeapgzn6XcwY-5VWUhP2jGKXoMLtvOq5Qjpqby_a4oLTFix1kFc0qugIsz1g7GjmxpzrbxnohP72tVBGXIcxPq4zzdY0fCoHBI9MsBAWmXFSQswqmtsv3DAyeMhrqatAdVC20BnzDve0f03j0XTNHLYiVFRra26fkYxiXejl5q8vPl8sSYsLfDVY7NTCwsDTxwV6sDtLOi_tlsJJ1X69ni89yJwTG4tnJdstiVuw5SnrjLK6lZ19i3kzrdWHxcEVUWPQkhosJcN69DkktzUzSOK5E7uh5wPVgoo7yrCfLPGjlAK22hFHXmQtcccHyg2v7I9EhbkI2YP5xkKB0aqmr4RBLo9LB-c2YnLFXJbUeaIcVQOfRZ0stm442RCwV_sw7Aj8Ryd9FGKux7s6foaiUstbDTJVt-gfWGfBi88fD1xh_eFjmBdmEV5QCnfBanwUCdHlqj4f_RW176vVswXsCjjTrmwftB_wBvOE68fowxKMYpiq1pXQlsDtk1l8X85TsHQoeXCCJbhPna81MsUsaQMnEsErwAONFLa1XkQydBsjeujby_sAwMy5B9Emotdd045YAdW_9dMMAjAe7p2sd2NapBPPXXEI4uI4wCodS3e1l4F57ee_7p-LCX5I3b6ukO3ZG3K0Q7H0rURxjL7Eh2_7uPyfv0q8kR6H73y0Mf2ND40IBvgrWYeoF6raD6bGqczhmmlQ8R0Pbx-I_0COIcCx2dI5-vHNZe1j3WZMTS9y380yMU5Gk-aHX0qGJsw):
```
--- FAIL: TestOfferStorage (1.86s)
	offers_test.go:163: released offer is not declined after 2*ttl
FAIL	k8s.io/kubernetes/contrib/mesos/pkg/offers	4.408s
```

### PR DESCRIPTION
**Pull request by k82cn**
fixes #25891

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33422)

### CODE REVIEW

**Comment by jdef** [comment]
Not convinced that this is the proper long term fix. Depending on the system clock for tests like this is just going to flake again at some point, albeit more infrequently.

**Comment by k82cn** [comment]
This PR will not 100% fix the issue, it'll increase the tolerated time to reduce the failure rate.
In the tests, there's several cases that using timer which should be avoid in multi-thread (go runtine) case.

I'd suggest to improve it in separated issue instead of this one.

**Comment by jdef** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33422)*

**Comment by jdef** [comment]
this PR probably needs to migrate to the k8sm incubator project

**Comment by k82cn** [comment]
Migrated in https://github.com/kubernetes-incubator/kube-mesos-framework/pull/31 .

**Pull request closed without merging**
