### PR TITLE
Fix staticcheck in pkg/controller/podgc

### PR DESCRIPTION
**Pull request by KobayashiD27**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Fix staticcheck in pkg/controller/podgc.

**Which issue(s) this PR fixes**:

Ref #81657 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/approve
for hack/

**Comment by BenTheElder** [comment]
/assign @foxish @gmarek 
for `kg/controller/podgc/OWNERS`

**Comment by mrbobbytables** [comment]
looping in some active owners from the parent [pkg/controllers/OWNERS](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/OWNERS)
/assign @deads2k @mikedanese

**Pull request merged**
