### PR TITLE
Remove docs that are moved to Community repo

### PR DESCRIPTION
**Pull request by spzala**
We are working on cleaning the docs directory. Per the discussion with Doc SIG
and more under https://github.com/kubernetes/kubernetes/issues/47361 we will
be working on moving the generated code and content to a different repo. This
PR is to clean up docs content which is already moved to Community repo and
not needed here.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by cblecker** [comment]
This is a duplicate of #48029, which is blocked by https://github.com/kubernetes/test-infra/pull/3175 and https://github.com/kubernetes/kubernetes.github.io/pull/4196.

I think this PR can be safely closed.

**Comment by spzala** [comment]
@cblecker Ahhh... :-) sure. Thanks!! Closing it.

**Pull request closed without merging**
