### PR TITLE
Sanitise vSphere Region and Failure Domain (Fixes #33576)

### LINKED ISSUE #33576: vSphere cloudprovider does not sanitise region or failuredomain, so nodes fail to register
**Kubernetes version**

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- vSphere cloud provider
- **OS** CoreOS 1122.2.0 (MoreOS)
- **Kernel** Linux master0 4.7.0-coreos #1 SMP Tue Sep 6 14:39:20 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz GenuineIntel GNU/Linux

**What happened**:

Kubelet fails to register nodes when the vSphere data center name or failure zone contain invalid characters.

```
E0927 13:28:03.940239   19470 kubelet_node_status.go:88] Unable to register node "worker0" with API server: Node "worker0" is invalid: metadata.labels: Invalid value: "my Datacenter": must match the regex (([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])? (e.g. 'MyValue' or 'my_value' or '12345')
```

**What you expected to happen**:

Cloud provider should sanitise invalid names

**How to reproduce it** (as minimally and precisely as possible):

Create a vSphere data center called "my Datacenter"

**Anything else do we need to know**:

PR Incoming

### PR DESCRIPTION
**Pull request by jakexks**
**What this PR does / why we need it**:

Fixes #33576

**Special notes for your reviewer**:

@dagnello seems to be the guy who wrote most of the vSphere cloud provider, CCing him in

**Release note**:

``` release-note
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33577)

### CODE REVIEW

**Comment by robdaemon** [comment]
I would say no to this - you cannot correlate this value back into vSphere. This needs to be done in some sort of escaping that is reversible.

**Comment by dagnello** [comment]
I would suggest using something like URL encoding or something that can reproduce the same original value in a deterministic way.  Also, this is something that should be standardized across all cloud providers.

**Comment by jakexks** [comment]
Kubernetes labels must match ```(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?``` so the only reversible encoding would be some form of base64

**Comment by dagnello** [comment]
There can be other services that rely on e.g. zone information stored by Kubernetes that actually corresponds to the appropriate object in the respective IaaS.  For example, the compute cluster in vSphere (failure zone).  If the name changes (in a non-reversable manner), resolution to the specific compute cluster would not be possible.

**Comment by mikedanese** [comment]
It sounds like this should be done with better escaping. Please reopen when that is prepared.

**Pull request closed without merging**
