### PR TITLE
Improve readability in e2e/network/service tests

### PR DESCRIPTION
**Pull request by mattjmcnaughton**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Improve readability in e2e network service tests by using differently
named methods for a test with a transition and without a transition.
This replaces a boolean argument, which didn't give any indication w.r.t
its purpose (unless one read the method).

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mattjmcnaughton** [comment]
/assign @mrhohn

thanks :)

**Comment by SataQiu** [comment]
Thanks @mattjmcnaughton 
/lgtm

**Review by MrHohn — APPROVED** [review]
/approve

**Pull request merged**
