### PR TITLE
Don't look at known metrics in MetricsGrabber test

### PR DESCRIPTION
**Pull request by gmarek**
Fix. #26800

### CODE REVIEW

**Comment by ihmccreery** [comment]
Is there a way to make these tests more resilient to change?  Seems like we'd rather not have to do a backport every time we add a new metric.

**Comment by gmarek** [comment]
We can add a switch over the master version.

**Comment by ihmccreery** [comment]
Er, I meant so that the test was forward compatible without us having to keep it updated, like tolerate unknown metrics?

**Comment by ihmccreery** [comment]
(A switch would have to be kept up-to-date, right?)

**Comment by gmarek** [comment]
This means more or less disabling the test all together. Having the switch over master version would mean no more backports, as test will know which metrics are available in a given master version.

**Comment by ihmccreery** [comment]
Okay, a switch SGTM then.

**Comment by dchen1107** [comment]
ping on review? Also this one is for cherrypick to 1.2 release branch, why marked with 1.3?

**Comment by ihmccreery** [comment]
Oh, sorry.  Based on our conversation, I was thinking you were going to build a switch?

LGTM, though, if you want to do that separately.  Feel free to apply label.

**Comment by dchen1107** [comment]
Since this is not for 1.3, I removed the milestone. Please let me or oncall know if you want to manual merge for this.

**Comment by ihmccreery** [comment]
@dchen1107 Yes, this is a fix for #26800, which is for 1.3 milestone.

**Comment by ihmccreery** [comment]
Not sure if @gmarek wants to merge this yet, though, based on our conversation above about putting a switch on master version in the test.

**Comment by gmarek** [comment]
I decided that I don't wan't to maintain this if I'm the only one that cares about not making a complete mess of metrics we publish. I'll send a PR to the head that does similar thing.

**Comment by ihmccreery** [comment]
> I decided that I don't wan't to maintain this if I'm the only one that cares about not making a complete mess of metrics we publish. I'll send a PR to the head that does similar thing.

Could we just check for a minimal set of metrics, ones that we know won't change?

**Comment by ihmccreery** [comment]
#27265 seems like it should be cherry-picked into v1.3 and v1.2, instead of this custom PR.  Closing this; re-open if that's wrong.

**Pull request closed without merging**
