### PR TITLE
kubelet: force status update when the deletion timestamp is set

### PR DESCRIPTION
**Pull request by yujuhong**

### CODE REVIEW

**Comment by yujuhong** [comment]
This should fix #22480

**Comment by dchen1107** [comment]
LGTM

**Comment by yujuhong** [comment]
Let me try to reproduce and verify the fix :-)

**Comment by yujuhong** [comment]
Reproduced with setting  --pod-infra-container-image=nonexistentimage. Verified that the fix worked. Replying lgtm.

**Comment by liggitt** [comment]
can we add a test for this, even as a followup?

**Comment by yujuhong** [comment]
> can we add a test for this, even as a followup?

Sure. Filed an issue #22536 for this.

**Pull request merged**
