### PR TITLE
fix typo error of ovs-networking.png

### PR DESCRIPTION
**Pull request by huangyuqi**
fix typo error of ovs-networking.png

### CODE REVIEW

**Comment by mikedanese** [comment]
This changes the background from transparent to white. Was that intended?

**Comment by huangyuqi** [comment]
@mikedanese , I wanted fix a typo error of part minion2

```podxy 10.244.2.4```
to
```pody 10.244.2.4```

But, i didn't use a right tool to modify the picture. Sorry. :)
I have given a new commit.

**Comment by mikedanese** [comment]
@huangyuqi LGTM Thanks!

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by huangyuqi** [comment]
@mikedanese Thanks so much. : )

**Pull request merged**
