### PR TITLE
Replace GCEDiskAlphaAPI by DiskAlphaAPI

### LINKED ISSUE #52258: Change `GCEDiskAlphaAPI` to `DiskAlphaAPI` in comments
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
In a number of comments in https://github.com/kubernetes/kubernetes/pkg/cloudprovider/providers/gce/gce.go mentions `GCEDiskAlphaAPI`.

**What you expected to happen**:

That flag is actually `DiskAlphaAPI` not `GCEDiskAlphaAPI`.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

### PR DESCRIPTION
**Pull request by carrodher**
**What this PR does / why we need it**:
This PR fixes an issue related to `DiskAlphaAPI` in comments.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #52258

### CODE REVIEW

**Comment by dims** [comment]
/ok-to-test

cc @msau42

**Comment by saad-ali** [comment]
Closing this as duplicate of https://github.com/kubernetes/kubernetes/pull/52259

**Pull request closed without merging**
