### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by huzhengchuan**
fix some typos in kubelet

``` 
NONE
```

### CODE REVIEW

**Comment by tallclair** [comment]
We should setup a presubmit test that spellchecks comments with aspell or something similar...

**Comment by huzhengchuan** [comment]
@tallclair  I agree to setup a presubmit test that spellchecks comments, But it's better to discuss the problem in other pr.  If anythings  i can do, please ping me.

if this pr is no problem, please add /lgtm label.

**Pull request merged**
