### PR TITLE
fix: get attach disk error due to missing item in max count table

### LINKED ISSUE #77461: remove VirtualMachineSizesClient dependency in azure disk GetVolumeLimits
https://github.com/kubernetes/kubernetes/blob/df29573ec50375e831d833e27c63c23a88b983e8/pkg/volume/azure_dd/azure_dd.go#L170

**What would you like to be added**:
related to https://github.com/kubernetes/kubernetes/issues/77309

**Why is this needed**:

/assign
/sig azure

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix: update max azure disk max count
If max azure disk max count is not correct, user would get attach disk error.

**Which issue(s) this PR fixes**:

Fixes  #77461

**Special notes for your reviewer**:
```
mkdir vmsizelist
cd vmsizelist
wget https://raw.githubusercontent.com/andyzhangx/demo/master/linux/azuredisk/get-vm-size-list.sh
chmod a+x get-vm-size-list.sh
./get-vm-size-list.sh
```
**Does this PR introduce a user-facing change?**:

```release-note
fix: get attach disk error due to missing item in max count table
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/assign @feiskyer 
/priority important-soon
/sig cloud-provider

### CODE REVIEW

**Comment by andyzhangx** [comment]
would cherry-pick to old release per user's request

**Comment by andyzhangx** [comment]
@chewong
could you take a look? Not sure why only windows test failure:
```
• Failure [71.754 seconds]
Dynamic Provisioning
/home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/test/e2e/dynamic_provisioning_test.go:31
  should create a deployment object, write and read to it, delete the pod and write and read to it again [kubernetes.io/azure-file] [file.csi.azure.com] [Windows] [It]
  /home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/test/e2e/dynamic_provisioning_test.go:175

  Expected error:
      <*errors.errorString | 0xc000a12660>: {
          s: "Failed to find \"hello world\r\nhello world\r\n\", last result: \"hello world\r\n\"",
      }
      Failed to find "hello world
      hello world
      ", last result: "hello world
      "
  not to have occurred

  /home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/test/e2e/testsuites/testsuites.go:455
```

**Comment by chewong** [comment]
@andyzhangx could it be because we have 3 masters now? It started failing after https://github.com/kubernetes-sigs/windows-testing/pull/161 was merged. Let me take a look at the logs.

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
