### PR TITLE
[WIP] promote APIPriorityAndFairness to GA

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind feature

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/enhancements/issues/1040

#### Does this PR introduce a user-facing change?

```release-note
Promote APIPriorityAndFairness to GA
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/1040
```

### CODE REVIEW

**Comment by carlory** [comment]
Hi @caesarxuchao @dims 

Is `KEP-1040 Priority and Fairness for API Server Requests` still targeting for stage stable for 1.28? when I try promoting it to GA, the `pull-kubernetes-conformance-kind-ga-only-parallel`  job fails because of  `"command failed" err="--runtime-config=api/beta=false conflicts with --enable-priority-and-fairness=true"` .  So I have a question which milestone we should add  v1 for flowcontrol.  v1beta3 was introduced in 1.26 and it will be deprecated in 1.29, removed in 1.32. 

FYI: https://github.com/kubernetes/kubernetes/blob/ccb24b2967eff19c40c34f5fa0b8ce4a4fcea1ff/pkg/controlplane/instance.go\#L704

**Comment by dims** [comment]
This work-in-progress PR needs a rebase. please rebase if this PR is still needed for the upcoming release.

**Comment by wojtek-t** [comment]
Closing as already outdated.

**Pull request closed without merging**
