### PR TITLE
Stop using the deprecated `Measure` method

### PR DESCRIPTION
**Pull request by chendave**
As what suggested by Ginkgo migration guide, `Measure` node was
deprecated and replaced with `It` node which creates `gmeasure.Experiment`.

Signed-off-by: Dave Chen <dave.chen@arm.com>

#### What type of PR is this?

/kind cleanup
/kind deprecation

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/kubernetes/issues/109744

#### Does this PR introduce a user-facing change?

```release-note
ginkgo.Measure has been deprecated in Ginkgo V2, switch to use gomega/gmeasure instead
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig testing

### CODE REVIEW

**Comment by chendave** [comment]
/cc @pohly 
/cc @aojea 

This help us to get rid of one last warning on the deprecation.

**Comment by aojea** [comment]
it lgtm but it will be better if @onsi confirms is correct

/assign @liggitt 

for vendor dependencies

**Comment by onsi** [comment]
this looks good to me.  not sure if there are any consumers downstream scraping the test output to record the result of the measurement... if so, those might need to change.

**Comment by chendave** [comment]
release-note-edit ```ginkgo.Measure has been deprecated in Ginkgo V2, switch to use gomega/gmeasure instead```

**Pull request merged**
