### PR TITLE
Align example in the client package with the api.

### PR DESCRIPTION
**Pull request by mdevilliers**
Hey,

I've fixed up the example in the client api to align it with the code. 

Mark

### CODE REVIEW

**Comment by roberthbailey** [comment]
LGTM. Shippable is a flake since this is a documentation only change.

**Comment by roberthbailey** [comment]
Closing and re-opening to kick shippable.

**Comment by roberthbailey** [comment]
@k8s-bot ok to test

**Comment by a-robinson** [comment]
The error from shippable:
```
!!! 'gofmt -s' needs to be run on the following files:
./pkg/client/doc.go
```

**Comment by mdevilliers** [comment]
I've gofmt'd the file - but it looks like the builds still fail.

How do you get to see the details for the build output? 

Thanks,

Mark

**Comment by a-robinson** [comment]
You should be able to click into the details of the Shippable build following the link next to it. This time it doesn't like the format of the boilerplate at the top of the file:
```
./hack/verify-boilerplate.sh
Boilerplate header is wrong for: ./pkg/client/doc.go
```

You can re-test it locally by running ./hack/verify-boilerplate.sh in your repo. You can set up git to automatically catch these things for you by setting up commit hooks: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/development.md#hooks

**Comment by mdevilliers** [comment]
Cool - looking better but I can't see the shippable error?

Clicking on the Details link gives me -
{"id":1005,"message":"Internal API error : getPermissionByProjectId","methodName":"chkPermForId|_getSByProjectId"} error so not to sure what is up but it looks like this https://github.com/Shippable/support/issues/1590

Thanks,

Mark

**Comment by bprashanth** [comment]
Should be ok-to-merge when shippable's done

**Comment by roberthbailey** [comment]
You may need to rebase. Shippable is failing with errors like `panic: API version 'v1beta1' is not recognized`.

**Comment by mdevilliers** [comment]
Here goes again!

I'm not too sure that my changes would relate to those errors but have rebased.

Thanks,

MArk

**Comment by a-robinson** [comment]
cc @yujuhong

**Pull request merged**
