### PR TITLE
Update gofuzz dep

### PR DESCRIPTION
**Pull request by thockin**

### CODE REVIEW

**Comment by thockin** [comment]
@lavalamp 

Tests fail with a roundtrip error around parsing time.  I know you changed that in upstream gofuzz..

--- FAIL: TestRoundTripTypes (5.11s)
        serialization_test.go:64: 0: Node: error unmarshaling JSON: parsing time "-136438948280-12-03T08:04:46-08:00" as "2006-01-02T15:04:05Z07:00": cannot parse "-136438948280-12-03T08:04:46-08:00" as "2006"

**Comment by lavalamp** [comment]
Ah the default fuzz function can generate negative times, which don't roundtrip.

Huh, can't decide if this is a bug in time.Unix (which accepts values that produce an invalid time), if fuzz's time function should be changed, or if we should just add a Fuzz() function to util.Time.

**Comment by thockin** [comment]
This is what fuzz.Interface is for, I guess...

**Comment by thockin** [comment]
And why don't negative times roundtrip?  That seems valid.

**Comment by lavalamp** [comment]
time.Time internal constraints are getting violated: http://golang.org/src/time/time.go?s=1855:2369#L29

**Comment by thockin** [comment]
Updated with latest gofuzz which handles time.Time more correctly.

**Comment by lavalamp** [comment]
Travis disagrees... our time format doesn't marshal nanoseconds. We'll have to write a custom Fuzz() on util.Time().

**Comment by thockin** [comment]
wierd, it passes locally

**Comment by thockin** [comment]
I can not fathom how this passes 100% locally but fails on travis

**Comment by thockin** [comment]
Should pass Travis now

**Comment by thockin** [comment]
For anyone watching, semantic deep equal was saying that uncomparable private fields were assumed equal, which let it pass on my machine.  But on Travis, something about timezones caused it to fail, exposing the time semantic-equal issue.  Now we fuzz to leave off nanosecond and semantic compare in UTC always.

**Comment by thockin** [comment]
rebased now

**Comment by lavalamp** [comment]
LGTM

**Pull request merged**
