### PR TITLE
Include all user.Info data in CSR object

### PR DESCRIPTION
**Pull request by liggitt**
In order to use authorization checks to auto-approve CSRs in the future, we need all the info from the user.Info interface.

This mirrors the API fields in the TokenReview API used to return user info, and in the SubjectAccessReview API we use to check authorization.

```release-note
The CertificateSigningRequest API added the `extra` field to persist all information about the requesting user. This mirrors the fields in the SubjectAccessReview API used to check authorization.
```

### CODE REVIEW

**Comment by mikedanese** [comment]
What's an example of data that would appear in ExtraInfo?

**Comment by liggitt** [comment]
> What's an example of data that would appear in ExtraInfo?

* OAuth scopes associated with the user
* Additional restrictions or permissions associated with the user as determined by webhook authentication
* Information about the user resolved at authentication time (like openstack projects or roles associated with the user's bearer token) needed by a paired authorizer to make an authorization decision

**Comment by liggitt** [comment]
@kubernetes/api-approvers for approval

**Comment by smarterclayton** [comment]
/approve

API changes are acceptable to me given the reasoning, unless @erictune is uncomfortable with the broadening.  I would be more concerned with CSRs *not* having this data than having it, on the whole.

**Pull request merged**
