### PR TITLE
Address an old 'TODO' and lazy initialize firewallD signal handler.

### PR DESCRIPTION
**Pull request by brendandburns**
@kubernetes/sig-network-misc

### CODE REVIEW

**Comment by danwinship** [comment]
`connectToFirewalld()` is only relevant if the caller has also called `AddReloadFunc()`, so a nicer fix might be to just call it from the first `AddReloadFunc()` call.

**Comment by brendandburns** [comment]
@danwinship comment addressed, please take another look.

**Comment by jberkus** [comment]
Changing milestone per discussion with @brendanburns 

/milestone v1.12

**Pull request merged**
