### PR TITLE
Etcd log mount

### PR DESCRIPTION
**Pull request by ArtfulCoder**

### CODE REVIEW

**Comment by ArtfulCoder** [comment]
#9352

**Comment by bprashanth** [comment]
@ArtfulCoder thanks! 
While you're doing this, anyway you can also mount /tmp into the master components? I really want to be able to dump cpu and heap profiles and collect them without entering the container (i.e remotely via rsync) and I don't see a reason to not do so

**Comment by dchen1107** [comment]
LGTM, please update with your e2e result. Thanks!

**Comment by ArtfulCoder** [comment]
Summarizing 2 Failures:

[Fail] Pod Disks [It] should schedule a pod w/ a RW PD, remove it, then schedule it on another host 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:105

[Fail] Pod Disks [It] should schedule a pod w/ a readonly PD on two hosts, then remove both. 
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/pd.go:170

Ran 62 of 72 Specs in 12738.275 seconds
FAIL! -- 59 Passed | 2 Failed | 2 Pending | 8 Skipped 
Ginkgo ran 1 suite in 3h32m18.709164953s
Test Suite Failed

**Comment by dchen1107** [comment]
LGTM

**Comment by bprashanth** [comment]
@quinton-hoole so the bot runs e2e per commit even after the commit has been merged (see above)?

**Pull request merged**
