### PR TITLE
Update the file name, usually using README instead of Readme

### PR DESCRIPTION
**Pull request by xichengliudui**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by SataQiu** [comment]
Thanks @xichengliudui 
But do we really need to do this?
```
This directory tree is generated automatically by godep.

Please do not edit.

See https://github.com/tools/godep for more information.
```

**Comment by BenTheElder** [comment]
we should not need to do this?

**Pull request closed without merging**
