### PR TITLE
Fix a couple flannel invocations I missed

### PR DESCRIPTION
**Pull request by thockin**
@dalanlan @bprashanth 

Do we have any reason not to ALWAYS run with --ip-masq?

### CODE REVIEW

**Comment by roberthbailey** [comment]
@k8s-bot unit test this

**Comment by dalanlan** [comment]
@thockin What about Vagrant? It uses flannel too.

**Comment by thockin** [comment]
Good eyes - I missed that one again.

**Comment by thockin** [comment]
fixed

**Pull request merged**
