### PR TITLE
fix typo in helpers.go

### PR DESCRIPTION
**Pull request by carlory**
**What this PR does / why we need it**:
fix typo in helpers.go
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
NONE
**Special notes for your reviewer**:
NONE
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by feiskyer** [comment]
@Carlory Please refer https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/ for linking a right github user.

**Comment by Carlory** [comment]
@feiskyer Thanks !

**Comment by Carlory** [comment]
@k8s-ci-robot I have already signed a CLA .

**Comment by feiskyer** [comment]
@k8s-bot ok to test

**Comment by cblecker** [comment]
@Carlory: The e-mail attached to your commit doesn't match your github account. You may need to check that your e-mail and username are set up properly in your local git config and then amend the commit resetting the author: `git commit --amend --reset-author --no-edit`

**Comment by cblecker** [comment]
I believe this PR can be closed in favour of https://github.com/kubernetes/kubernetes/pull/45944

**Comment by carlory** [comment]
@cblecker Thanks !

**Pull request closed without merging**
