### PR TITLE
changes for custom vnet and dns

### PR DESCRIPTION
**Pull request by smashraf**
The vnet over which cluster is to be created and the dns name can be set as environment variable

### CODE REVIEW

**Comment by thockin** [comment]
@errordeveloper who has the most fingerprints here.

**Comment by errordeveloper** [comment]
@thockin thank you!

**Comment by errordeveloper** [comment]
@smashraf thank you very much for this contribution. It looks good to me overall. However, could you please ensure that your changes have consistent style with the rest of JavaScript code?

**Comment by errordeveloper** [comment]
Actually, I am seeing a whole bunch of changes here that do not relate to the subject. I think this needs to be rebased properly.

**Comment by errordeveloper** [comment]
@smashraf as you haven't rebased this and the code is being removed with #23818, I think @thockin should close it.

**Comment by fejta** [comment]
This PR has had no meaningful activity for multiple months. If it is still valid please rebase, push a new commit and reopen the PR. Thanks!

**Pull request closed without merging**
