### PR TITLE
[pkg.apis/apps]fix feature borken with 1.8+ and update examples test

### PR DESCRIPTION
**Pull request by zouyee**
**What this PR does / why we need it**:
pkg.apis／apps something need to be updated, which has broken features with `kubernetes/api`, then update example test.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by zouyee** [comment]
add `do-not-merge/work-in-progress` ?

**Comment by caesarxuchao** [comment]
cc @kubernetes/sig-apps-api-reviews

**Comment by enisoc** [comment]
What is this trying to fix? I don't think we're ready to move the internal types out of `extensions`.

/assign @kow3ns

**Comment by kow3ns** [comment]
You can't move Deployment from extensions into apps yet. We can't except this PR.

**Pull request closed without merging**
