### PR TITLE
Fix container restarts caused by kubelet restarts

### PR DESCRIPTION
**Pull request by yujuhong**
There has been a recent regression causing kubelet to assume no containers are
running for the pod if kubelet has not seen the pod before. This would cause
all containers to be restarted after kubelet gets restarted. This change fixes
the bug.

### CODE REVIEW

**Comment by yujuhong** [comment]
ref: https://github.com/kubernetes/kubernetes/issues/17873#issuecomment-169137536

/cc @Random-Liu

**Comment by yujuhong** [comment]
@k8s-bot test this

**Comment by freehan** [comment]
The container restart somehow are not captured in ContainerStatus. Thus, the kubelet restart test did not failed, which it should.

**Comment by yujuhong** [comment]
> The container restart somehow are not captured in ContainerStatus. Thus, the kubelet restart test did not failed, which it should.

With this bug, kubelet assumes that there are no running containers for the pod, so it'd not increment the restart count. If the restart test wants to capture the container restarts reliably, maybe it can compare the old and new container IDs.

**Comment by Random-Liu** [comment]
I see...I should always remember that kubelet could be restarted...Thanks a lot for fixing this.

**Comment by Random-Liu** [comment]
Why couldn't we `generatePodStatus()` [before](https://github.com/yujuhong/kubernetes/blob/41a9ab388d1c083baaedc1407e21b62b6973a3b5/pkg/kubelet/kubelet.go#L1571) when saw a new pod?

**Pull request merged**
