### PR TITLE
Revert #19469 so re-enable the metrics grabbing test on GKE.

### PR DESCRIPTION
**Pull request by roberthbailey**
Ref: #19468

### CODE REVIEW

**Comment by roberthbailey** [comment]
@jdef Any idea why the mesosphere test failed? AFAIK this test isn't labeled as a conformance test.

**Comment by jdef** [comment]
@roberthbailey this isn't the first smoke to fail today. something else changed and that's breaking a template:
```
[17:27:53][Step 6/6] kube-dns: ....................................................................................................................................................................................Error executing template: template: output:1:3: executing "output" at <index .items 0>: error calling index: index out of range: 0. Printing more information for debugging the template:
[17:27:53][Step 6/6] 	template was:
[17:27:53][Step 6/6] 		{{(index .items 0).status.phase}}
[17:27:53][Step 6/6] 	raw data was:
[17:27:53][Step 6/6] 		{"kind":"List","apiVersion":"v1","metadata":{},"items":[]}
[17:27:53][Step 6/6] 	object given to template engine was:
[17:27:53][Step 6/6] 		map[apiVersion:v1 metadata:map[] items:[] kind:List]
```

**Comment by roberthbailey** [comment]
Thanks; just wanted to make sure I wasn't breaking something.

**Comment by roberthbailey** [comment]
ping @gmarek

**Comment by roberthbailey** [comment]
@k8s-bot unit test this issue: #21188

**Pull request merged**
