### PR TITLE
test images: Adds Windows support for resource-consumer

### LINKED ISSUE #77268: Kubernetes test images should include Windows images in their manifest lists
**What would you like to be added**:

/sig windows
/sig testing

/area conformance

The images used in Kubernetes tests should also include Windows images in their manifest lists. Right now, in order to run E2E tests with Windows nodes, the env var ``KUBE_TEST_REPO_LIST`` needs to be set, containing alternative repositories which contain Windows images (the ``e2eteam`` repository is mainly used). The Windows images are currently maintained and built from ``kubernetes-sigs/windows-testing``: https://github.com/kubernetes-sigs/windows-testing/blob/master/images/BuildImageManifestLists.ps1

The build script in ``kubernetes/test/images`` does not build Windows images at the moment.

**Why is this needed**:

Running E2E tests on Windows nodes will be made easier, with the official Kubernetes test images.

Secondly, Hybrid OS tests will be able to be run.

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind feature

/sig testing
/sig windows

**What this PR does / why we need it**:

Some images require a different Dockerfile for Windows images, since they have different ways of installing dependencies. Because of this, if a image needs to be built for Windows, it will first check for a Dockerfile_windows file instead of the default one. If there isn't one, it means that the same Dockerfilecan be used for both Windows and Linux.

stress was being used for the memory consumption part. This adds a golang equivalent, which will also work on Windows.

**Which issue(s) this PR fixes**:

Fixes #77268
Depends On: #76838

**Special notes for your reviewer**:

This was split from https://github.com/kubernetes/kubernetes/pull/77398

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by mkorbi** [comment]
Hello @claudiubelu
This PR has been updated frequently, but it looks like the merge is blocked/waiting for approval/lgtm, so I'd like to check what's the status. The code freeze is starting 12.11.2020 (about 3-4 weeks from now) and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.
As the PR is tagged for 1.20, is it still planned for this release?

**Comment by claudiubelu** [comment]
> 
> 
> Hello @claudiubelu
> This PR has been updated frequently, but it looks like the merge is blocked/waiting for approval/lgtm, so I'd like to check what's the status. The code freeze is starting 12.11.2020 (about 3-4 weeks from now) and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.
> As the PR is tagged for 1.20, is it still planned for this release?

Yes. This was split off another PR that already merged in order to make it easier to review.

**Comment by erismaster** [comment]
Hi 👋🏽  I'm from the Bug Triage team. We've crossed the Code Freeze for 1.20 release on 12th November. As this PR is tagged with 1.20, I'm sending a final reminder to either move the milestone to 1.21 or clear the milestone.

**Comment by dims** [comment]
/approve
/lgtm

@marosset @claudiubelu can we get some `/lgtm` from sig-windows folks?

**Comment by claudiubelu** [comment]
FWIW, here are some HPA E2E test logs with a ``resource-consumer`` Windows image built with this PR: https://paste.ubuntu.com/p/wX8y2dYwR9/

**Comment by jsturtevant** [comment]
for sig-windows

/lgtm

**Comment by spiffxp** [comment]
In principle this lgtm, but `consume-memory` doesn't look to be a straight rewrite of `stress` (glancing at https://fossies.org/linux/stress/src/stress.c with an eye toward logging)

I'd sorta like some input from someone who depends on these tests to chime in

**Comment by spiffxp** [comment]
/cc @aleksandra-malinowska @bskiba @MaciekPytel @mwielgus 
pulling you in for input on whether the rewrite away from `stress` looks good, since you're listed via alias in test/e2e/autoscaling/OWNERS

**Comment by spiffxp** [comment]
/hold
for input from autoscaling test owners

**Comment by jsturtevant** [comment]
> In principle this lgtm, but `consume-memory` doesn't look to be a straight rewrite of `stress` (glancing at https://fossies.org/linux/stress/src/stress.c with an eye toward logging)

I've used a similar binary [testlimit](https://github.com/jsturtevant/dockerfiles-windows/blob/master/stress/Dockerfile) which is similar to  `stress` for Windows during [previous investigations](https://github.com/kubernetes/kubernetes/issues/73417#issuecomment-464852397).  Maybe we could use something like https://docs.microsoft.com/en-us/sysinternals/downloads/testlimit for Windows and keep `stress` for linux?

**Comment by claudiubelu** [comment]
> 
> 
> > In principle this lgtm, but `consume-memory` doesn't look to be a straight rewrite of `stress` (glancing at https://fossies.org/linux/stress/src/stress.c with an eye toward logging)
> 
> I've used a similar binary [testlimit](https://github.com/jsturtevant/dockerfiles-windows/blob/master/stress/Dockerfile) which is similar to `stress` for Windows during [previous investigations](https://github.com/kubernetes/kubernetes/issues/73417#issuecomment-464852397). Maybe we could use something like https://docs.microsoft.com/en-us/sysinternals/downloads/testlimit for Windows and keep `stress` for linux?

I've updated this PR to use ``testlimit`` on Windows and ``stress`` on Linux. ``testlimit`` doesn't stop after the given duration elapses, so we have to kill it instead so we can keep the behaviour consistent with Linux.

**Comment by marosset** [comment]
c/test pull-kubernetes-e2e-azure-disk-windows

**Comment by dims** [comment]
the hold for test/e2e/autoscaling/OWNERS is no longer valid as the PR got updated to keep the `stress` util for linux.

/hold cancel
/lgtm

**Pull request merged**
