### PR TITLE
remove redundant parentheses

### PR DESCRIPTION
**Pull request by lucming**
#### What type of PR is this?
it seems that the parentheses is redundant.

#### What this PR does / why we need it:
make code more clearly.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lucming** [comment]
pinging @liggitt for approval

**Comment by liggitt** [comment]
Thanks for the PR, but I don't think this is a net improvement. With such a long function, we've had problems with variables getting declared and reused later accidentally as part of copy/paste setup. The explicit additional scoping is to make it clear that the local variables are not expected to be used later in the function.

/close

**Pull request closed without merging**
