### PR TITLE
Undelete generated files

### LINKED ISSUE #28920: Build of Go projects importing kubernetes fail because of missing auto-generated code
This commit https://github.com/kubernetes/kubernetes/commit/9eb42ff1089243928da623c33fb28eb07f910436#diff-5c755714d0649f91c00269ed3d88e19c removed files like pkg/api/v1/conversion_generated.go so now simply running `go get -v k8s.io/kubernetes/pkg/api/v1` fails. While there are ways around this if your intent is building kubernetes, if you have a Go project that imports "k8s.io/kubernetes/pkg/api/v1", it fails to build because kubernetes fails to build using the standard Go toolchain. Again, there are workarounds but they are costly when dealing with CI.

Example:

```sh
$ go version
go version go1.6.2 darwin/amd64
$ go get -v k8s.io/kubernetes/pkg/api/v1
Fetching https://k8s.io/kubernetes/pkg/api/v1?go-get=1
Parsing meta tags from https://k8s.io/kubernetes/pkg/api/v1?go-get=1 (status code 200)
get "k8s.io/kubernetes/pkg/api/v1": found meta tag main.metaImport{Prefix:"k8s.io/kubernetes", VCS:"git", RepoRoot:"https://github.com/kubernetes/kubernetes"} at https://k8s.io/kubernetes/pkg/api/v1?go-get=1
get "k8s.io/kubernetes/pkg/api/v1": verifying non-authoritative meta tag
Fetching https://k8s.io/kubernetes?go-get=1
Parsing meta tags from https://k8s.io/kubernetes?go-get=1 (status code 200)
k8s.io/kubernetes (download)
k8s.io/kubernetes/pkg/types
k8s.io/kubernetes/pkg/util/sets
k8s.io/kubernetes/pkg/auth/user
...
k8s.io/kubernetes/pkg/api
k8s.io/kubernetes/pkg/api/v1
# k8s.io/kubernetes/pkg/api/v1
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:248: undefined: autoConvert_api_PodStatusResult_To_v1_PodStatusResult
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:289: undefined: autoConvert_v1_PodStatusResult_To_api_PodStatusResult
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:304: undefined: autoConvert_api_PodTemplateSpec_To_v1_PodTemplateSpec
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:346: undefined: autoConvert_v1_PodTemplateSpec_To_api_PodTemplateSpec
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:363: undefined: autoConvert_api_PodSpec_To_v1_PodSpec
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:382: undefined: autoConvert_v1_PodSpec_To_api_PodSpec
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:405: undefined: autoConvert_api_Pod_To_v1_Pod
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:477: undefined: autoConvert_v1_Pod_To_api_Pod
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:493: undefined: autoConvert_api_ServiceSpec_To_v1_ServiceSpec
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:502: undefined: autoConvert_v1_Secret_To_api_Secret
src/k8s.io/kubernetes/pkg/api/v1/conversion.go:502: too many errors
```

/cc @thockin

### PR DESCRIPTION
**Pull request by thockin**
There's been enough people broken by not committing generated code, that we
should undo that until we have a proper client that is `go get` compatible.

This is temporary.

Fixes #28920

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Thanks. Not sure about the Makefile changes, the end result looks good.

**Comment by bgrant0607** [comment]
LGTM

**Comment by dims** [comment]
Let's do this! 👍

**Comment by wojtek-t** [comment]
@thockin - it's a bit late, but why did we committed only deepcopy files and not autogenerated conversions?

**Comment by thockin** [comment]
eh?  Conversions are in this PR...

**Comment by wojtek-t** [comment]
A sorry - then something must have happened after this PR. Because currently:
- generated deep-copies are committed to githubs
- generated conversions aren't
Is that expected?

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/zz_generated.conversion.go

That looks like it is checked in, to me...

**Comment by wojtek-t** [comment]
ohh - sorry; I must have looked into internal packages...

**Comment by thockin** [comment]
ah, yeah, there were never conversions in internals :)

**Pull request merged**
