### PR TITLE
[Harmless] K8petstore shell update, separated from the larger PR

### PR DESCRIPTION
**Pull request by jayunit100**
Here is a quick update to k8petstore.   Ive separated it from the other PR because people are now using it and this will be an easy review for folks (it only touches one file, in examples) :)

### CODE REVIEW

**Comment by jayunit100** [comment]
@chuckbutler  has tested this iirc.
And, mister chucky, after  we get this in, we can then lob any new ideas/changes (suggested in ) on top.  
im happy help to review any patch you have.

**Comment by saad-ali** [comment]
Fixing example ok for 1.0. Assigning reviewer.

**Comment by chuckbutler** [comment]
@jayunit100 sounds good to me. I haven't had a chance to circle back to this yet w/ any of the modifications, but should have some time on Thursday to give it all a good look/run-through for our action(s) usecase.

Thanks!

**Comment by eparis** [comment]
LGTM with whitespace fix on like 23{1,2,3}

**Comment by jayunit100** [comment]
yup, okay fixed the whitespaces needed some WS cleanups, done ! thanks @eparis

**Comment by erictune** [comment]
if this LGTeparis then it LGTM.

**Comment by eparis** [comment]
what are the shippable failures?

**Comment by erictune** [comment]
I chose to ignore shippable because you can't see the failures without giving them excessive github permissions.  

The travis failures appear to be a failure during race checking.  That can't be related to this PR.

**Comment by eparis** [comment]
both 1.3 and 1.4

```
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/securitycontext	0.041s	coverage: 62.5% of statements
--- FAIL: TestNoManualChangesToGenerateDeepCopies (0.27s)
	conversion_generation_test.go:126: please update conversion functions; generated: api.deep_copy.txt; first diff: 
		expected: 	if in.ISCSI != nil {
		
		     got: 	return nil
	conversion_generation_test.go:126: please update conversion functions; generated: v1beta3.deep_copy.txt; first diff: 
		expected: 	if in.ISCSI != nil {
		
		     got: 	return nil
	conversion_generation_test.go:126: please update conversion functions; generated: v1.deep_copy.txt; first diff: 
		expected: 	if in.ISCSI != nil {
		
		     got: 	return nil
FAIL
coverage: 81.5% of statements
```

**Pull request merged**
