### PR TITLE
Update Cluster Autoscaler version to 1.16.2

### PR DESCRIPTION
**Pull request by losipiuk**
```release-note
Update Cluster Autoscaler version to 1.16.2 (CA release docs: https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.16.2)
```

### CODE REVIEW

**Comment by losipiuk** [comment]
/assign @tallclair PTAL.

To validate CA manifest updates like this one I added a non obligatory presubmit which runs all CA tests if manifest is changed. 
The result is mostly green https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/84038/pull-kubernetes-e2e-gci-gce-autoscaling/1184894942527361024/. One test failed - but that one is flaking a lot.

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
