### PR TITLE
refactor: Change the uses of IsQualifiedName to ValidateQualifiedName

### LINKED ISSUE #99828: Change the users of IsQualifiedName to ValidateQualifiedName
After #98277 got merged, we have added new helper function `ValidateQualifiedName` here: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L126. 

It will be good for us to use this simpler helper function to replace previous `IsQualifiedName` function.

/good-first-issue

### PR DESCRIPTION
**Pull request by mangoGoForward**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
In #99828 the helper function ValidateQualifiedName was introduced. This PR replaces uses of the IsQualifiedName function with this simpler function.

#### Which issue(s) this PR fixes:

Fixes #99828

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mangoGoForward** [comment]
/cc @XudongLiuHarold 

Could you help me to review this PR if you have free time?

**Review by XudongLiuHarold — APPROVED** [review]
/lgtm, thanks @mangoGoForward😁

**Comment by lavalamp** [comment]
I like this simplification a lot but it should probably wait for after code freeze. Ping me for an approve when freeze is over if I don't remember!

**Comment by mangoGoForward** [comment]
> I like this simplification a lot but it should probably wait for after code freeze. Ping me for an approve when freeze is over if I don't remember!

Thanks,  this PR would not update anymore, and what I can do to impel it to merge?

**Comment by lavalamp** [comment]
/milestone v1.25
/lgtm
/approve

(this won't merge until code freeze is over)

**Pull request merged**
