### PR TITLE
validate PersistentVolumeClaim in StatefulSet

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:
> // TODO: Define the behavior if a claim already exists with the same name.

error out when PVC with the same name is requested in StatefulSet.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/assign @kow3ns @janetkuo @liggitt 

**Release note**:

```release-note
validate PersistentVolumeClaim in StatefulSet
```

### CODE REVIEW

**Comment by liggitt** [comment]
/hold

standard questions when we want to tighten validation:
* does it prevent a no-op update of existing persisted objects that would fail this new validation? (would block storage migration tasks)
* does it prevent deletion of existing persisted objects with finalizers that would fail this new validation? (update is required to remove finalizers to allow deletion)
* does it prevent controllers from updating status of existing persisted objects that would fail this new validation?

**Comment by krmayankk** [comment]
@liggitt thanks that makes sense. So what is my next step, is this documented somewhere or a PR where i can look on how to proceed adding these ? Basically how and where to test if this validation needs to be done only for new objects but skip for existing ones ?

**Comment by liggitt** [comment]
see https://github.com/kubernetes/kubernetes/pull/64907 for a potential mechanism for safely tightening validation (should only be used in cases where existing loose validation allows completely broken objects). if that is merged, that could be used to improve validation here

**Pull request closed without merging**
