### PR TITLE
Include a dummy src tarball unless PACKAGE_SRC=true is set

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: alternative to #40546. I think this will keep the cluster startup scripts happy.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ixdy** [comment]
seems to work!

**Comment by spxtr** [comment]
Shiny. Can we use this as the default for `make bazel-release`?

**Comment by ixdy** [comment]
Dummy src tarball is now default.

**Comment by ixdy** [comment]
@k8s-bot cri node e2e test this
@k8s-bot verify this

**Comment by ixdy** [comment]
@k8s-bot verify test this

**Comment by ixdy** [comment]
@k8s-bot verify test this

**Pull request merged**
