### PR TITLE
Update kube-addon-manager to v9.1.4

### PR DESCRIPTION
**Pull request by dekkagaijin**
/kind bug

```release-note
NONE
```

### CODE REVIEW

**Comment by dekkagaijin** [comment]
Adopts the bug fixes and updates in https://github.com/kubernetes/k8s.io/pull/1760

**Comment by liggitt** [comment]
/lgtm
would like an ack from @MrHohn

**Review by MrHohn — APPROVED** [review]
Thanks!
/lgtm
/approve

**Comment by MrHohn** [comment]
cc @spencer-p @rikatz

**Pull request merged**
