### PR TITLE
Lowercase hostnames when used as node names in k8s

### PR DESCRIPTION
**Pull request by ktsakalozos**
**What this PR does / why we need it**: Juju deployments of Kubernetes should lowercase the hostnames when referencing nodes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/442

**Special notes for your reviewer**:

**Release note**:

```NONE 
```

### CODE REVIEW

**Comment by Cynerva** [comment]
Do these need to be lowercased too?
[kubernetes_worker.py:847](https://github.com/juju-solutions/kubernetes/blob/99a25fed196b6267e55769e7344693f500a366cf/cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py#L847)
[kubernetes_worker.py:854](https://github.com/juju-solutions/kubernetes/blob/99a25fed196b6267e55769e7344693f500a366cf/cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py#L854)

The [Using Node Authorization](https://kubernetes.io/docs/admin/authorization/node/) doc asks for`system:node:<nodeName>`, which makes me worry that the uppercase nodeName won't be accepted. @ktsakalozos can you look into this?

**Comment by ktsakalozos** [comment]
These two entries are for creating a name for the node at hand so the master can create a token. I havent seen any problems with using the hostname as is, but you are right we have to be consistent with what the docs say. Updated those as well and did a quick test to verify everything works. Thanks @Cynerva

**Pull request merged**
