### PR TITLE
Add shyamjvs to test/OWNERS

### PR DESCRIPTION
**Pull request by shyamjvs**
I've been reviewing quite some PRs recently and have reviewed many in the past. + I have >80 commits in this code path (git log test | grep "shyamjvs@google.com") touching various parts including e2e/framework, utils, perftype, kubemark, e2e fixes from other SIGs (mostly in regard of scalability).

/cc @gmarek @spiffxp @krzyzacy @kubernetes/sig-testing-misc

### CODE REVIEW

**Comment by gmarek** [comment]
+1 on that, but I'd like to get a second approval from someone from @kubernetes/sig-testing-misc. @spiffxp?

**Comment by spiffxp** [comment]
What do you think about OWNERS files in the specific directories you mentioned rather than at the top level of test?

**Comment by spiffxp** [comment]
eg:
```
spiffxp@kthxbye:kubernetes (master %)$ for path in \
$(git log --follow --name-only --author="Shyam Jeedigunta" test | grep ^test | sort | uniq); do\
  dirname $path; \
done | uniq -c
   1 test/e2e
   1 test/e2e/apimachinery
   3 test/e2e/common
   3 test/e2e
   7 test/e2e/framework
   1 test/e2e/kubectl
   2 test/e2e/perf
   5 test/e2e/scalability
   3 test/kubemark
   1 test/kubemark/common
   1 test/kubemark
   1 test/kubemark/gce
   2 test/kubemark
   4 test/kubemark/resources
   4 test/kubemark/resources/manifests/addons/kubemark-rbac-bindings
   6 test/kubemark/resources/manifests
   1 test/kubemark/resources
   1 test/kubemark
   1 test/kubemark/skeleton
   2 test/kubemark
   1 test/utils
```

**Comment by shyamjvs** [comment]
They don't have individual owners files. For e.g `e2e`, `e2e/framework`. Seems like it's only the SIG directories that're having them.

**Comment by krzyzacy** [comment]
lgtm, :joy: obviously our test-infra folks cannot approve for you here

**Comment by shyamjvs** [comment]
@fejta Could you also `/approve no-issue` this?

**Comment by spiffxp** [comment]
/approve no-issue
I guess I'd rather not blow scope here, and I've seen you put in the time.  But this does look a clear cut case of where we (collectively) should be adding new OWNERS files for the leaves, and taking people out of the test/ dir where possible.  Now that you're getting added to test/OWNERS, you have the power to do this, so that you wouldn't get assigned to all PR's that touch test/*

**Comment by shyamjvs** [comment]
Yup.. I agree :)

**Comment by fejta** [comment]
Aaron 100% agree with that instinct. Filed a bug to do this separately.

**Comment by shyamjvs** [comment]
@fejta Any reason why you've removed the `retest-not-required` label?

**Comment by shyamjvs** [comment]
@fejta Any reason why you've removed the `retest-not-required` label?

**Comment by fejta** [comment]
Yes, please leave retest labels off PRs (and others, really), as it just slows down the overall merge rate as it invalidates batch merges.

**Pull request merged**
