### PR TITLE
fix panic in CRI stats of windows

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind failing-test

#### What this PR does / why we need it:
https://storage.googleapis.com/k8s-triage/index.html?job=unit&test=TestListPodStatsStrictlyFromCRI
/sig windows

#### Which issue(s) this PR fixes:

Fixes None

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Comment by pacoxu** [comment]
> @yujuhong: changing LGTM is restricted to collaborators

@yujuhong is sig node approver but not a kube member.

**Comment by yujuhong** [comment]
> > @yujuhong: changing LGTM is restricted to collaborators
> 
> @yujuhong is sig node approver but not a kube member.

Yep. I lost my k8s membership yesterday. Need to re-apply again later. 

In the meantime, let me see if others can help here. @dchen1107 @tallclair

**Review by marosset — COMMENTED** [review]
/LGMT

**Pull request merged**
