### PR TITLE
Add prometheus plugin on fluentd image.

### PR DESCRIPTION
**Pull request by vasartori**
**What this PR does / why we need it**:
This PR adds the prometheus plugin on Fluentd.

**Special notes for your reviewer**:
The plugin used was: https://github.com/kazegusuri/fluent-plugin-prometheus, on the latest stable version.
All configs used are default.

**Release note**:

```release-note
Fluentd-es addon now exposes a /metrics endpoint for monitoring on port 24231. 
```

### CODE REVIEW

**Comment by crassirostris** [comment]
@vasartori Thanks for your contribution!

Since you change the image, could you please bump the image version in the Makefile? Also I think your change deserves a mention in the release notes.

**Comment by vasartori** [comment]
@crassirostris done!

**Comment by crassirostris** [comment]
@vasartori SGTM, thanks! Waiting for @coffeepac's review

**Comment by coffeepac** [comment]
Looks great, thanks @vasartori !

**Comment by vasartori** [comment]
@coffeepac Could you please help me to understand what wrong happened on tests?

**Comment by coffeepac** [comment]
@vasartori looks like a docker build or pull timeout in the kops e2e test.  Im not real familiar with thenkops e2e test so ive kicked it again.  Heres hoping it was a transient network thing.  

If it fails in the same way we can take a deeper dive.

**Comment by coffeepac** [comment]
@vasartori I talked to @spiffxp and this is a known issue with docker right now.  Its being brought up during sig-testing this afternoon.

**Comment by vasartori** [comment]
@coffeepac Thanks alot for your help! Let's wait! :)

**Pull request merged**
