### PR TITLE
Fixed "no action if first clicking an achor after page load"

### PR DESCRIPTION
**Pull request by RichieEscarez**
Also added/fixed the following to help retain menu context/location: 
(1) improved behavior of "getting started" menu items (highlights immediate parent container when hidden child is clicked)
(2) fixed nav menu highlighting for in-page links
(3) removed "close menu" on second click (bad behavior when in-page links are clicked and we no longer have empty containers (they were replaced with TOC pages))
(4) automated nav menu scrolling to keep active menu item in visible area

Preview changes in my fork at http://richieescarez.github.io/kubernetes/v1.0/

### CODE REVIEW

**Comment by thockin** [comment]
Load main page
Click "quick walkthrough"
Click "Kubernetes 101"
Observe that nav bar does not scroll to put the nav on the visible screen.

**Comment by RichieEscarez** [comment]
Okay, ill add that in

**Comment by thockin** [comment]
We need a documented test plan for the docs UI.

go to URL X
click Y
observe Z

go to URL A
click B
use the back button
observe C
use the forward button
observe D

**Comment by RichieEscarez** [comment]
Test cases:

 1. After page load/refresh (ie. the first time the page is loaded), clicking an in page anchor scrolls to the correct location (it does not take two clicks for anchors to work the first time):
    1. http://richieescarez.github.io/kubernetes/v1.0/docs/user-guide/services.html
    2. Click one of the anchors in the TOC, for example "IPs and VIPs":
http://localhost:4000/v1.0/docs/user-guide/services.html#ips-and-vips
 2. Clicking on a generated in-page TOC link in one of the getting started landing pages continues to highlight the landing page item in the navigation menu:
    1. http://localhost:4000/v1.0/gs-localmachine.html  
*Note: these pages intentionally force a page reload in order to auto generate the in-page TOC which cause the nav menu to blink (close and reopen). Since I feel the menu close/open for these few auto-generated TOC pages less of an issue than having zero indication of where you are once you drill down into a specific Getting Started page, i think its acceptable until a solution is found to bypass a full page load (ie. loading on click is not working).*
    2. Click one of the auto-generated TOC links, for example "Vagrant":  
http://localhost:4000/v1.0/docs/getting-started-guides/vagrant.html
 3. Clicking a link from within a page finds, highlights, opens related menu, and then scrolls to it in the navigation menu:
    1. http://localhost:4000/v1.0/basicstutorials.html 
    2. Click the first tutorial (101):  
http://localhost:4000/v1.0/docs/user-guide/walkthrough/README.html 
    3. Ensure the nav menu item is highlighted.
    4. Click the in page link: "kubectrl" and then scroll down and click "kubectrl version"
    5. Ensure the nav menu items get highlighted and the nav menu scrolls.
 4. For and sub-menu, try clicking the parent topic and any of its children multiple times to ensure that the menu does not close:
    1. In the nav menu, try clicking "[kubectrl version](http://localhost:4000/v1.0/docs/user-guide/kubectl/kubectl_version.html)" multiple times to ensure the menu  remains open
    2. Also try clicking "[kubectrl](http://localhost:4000/v1.0/docs/user-guide/kubectl/kubectl.html)" in the nav menu multiple times.
 5. Test case 3 should have validated that the nav menu automatically scrolls to keep active menu item in the visible area. 
    1. You can reduce the browser window and try performing the above test case 3 again to ensure that scrolling continues to work relative to window size.
    2. From here, click "[kubectrl version](http://localhost:4000/v1.0/docs/user-guide/kubectl/kubectl_version.html)" and "[kubectrl](http://localhost:4000/v1.0/docs/user-guide/kubectl/kubectl.html)" to ensure the pages open and then highlight and scroll to the items in the nav menu.
 6. Back/Forward buttons also highlight and scroll to the nav menu item (on popstate change).
    1. Click the browser Back button and navigation back through to first page you loaded to ensure that each page loads and the navigation menu follows
    2. Click the Forward button through to the end to test in the opposite direction.

**Comment by RichieEscarez** [comment]
FYI: 

Here is my list of known issues that ill be opening issues for shortly:

 - auto generated landing pages blink (open and close) due to full page load (we need a solution for loading the auto-generated TOC, for example by using the .load() function for a “on-click” (ive been so far unsuccessful)).
Example: http://localhost:4000/v1.0/basicstutorials.html

 - third level getting started pages don’t map to nav menu (we need to list these items in the nav_v1.0.html file under their corresponding parent containers).
Example: "http://localhost:4000/v1.0/docs/getting-started-guides/coreos/coreos_multinode_cluster.html" found in the "mult-node cluster" link in the TOC at  http://localhost:4000/v1.0/docs/getting-started-guides/coreos.html

 - in page links that do not specify the full URL (ie. URLs that point to a directory and exclude the filename (README.html), do not display in the nav menu (we need to either update the source .md files OR add in a function to detect these types of URLs, assume its missing "README.html", and add it when the findcurnavitem() function gets run):  
Example: "http://localhost:4000/v1.0/examples/guestbook-go/" found in the "go implementation" link at the top of http://localhost:4000/v1.0/examples/k8petstore/README.html

**Comment by RichieEscarez** [comment]
@thockin ive added the auto scrolling in to keep active items visible and the test cases, PTAL

**Comment by thockin** [comment]
LGTM

for test plan I meant that we should write down a comprehensive list of steps to manually take and verify on every docs-UI change, since there is a lot of subtlety.

**Comment by RichieEscarez** [comment]
@thockin thanks! I did make a note for myself and added "create a doc test plan" to my to-do list.

**Pull request merged**
