### PR TITLE
Remove cloud provider rackspace

### LINKED ISSUE #52854: Remove cloud provider rackspace in favor of openstack
**What happened**:

For now, we have to implement functions in both `rackspace` and `openstack` packages if we want to add function for cinder, for example [resize for cinder](https://github.com/kubernetes/kubernetes/pull/51498).  Since openstack has implemented all the functions rackspace has,  and rackspace is considered deprecated for a long time, [rackspace deprecated](https://github.com/rackspace/gophercloud/issues/592) ,
after talking with @mikedanese  and @jamiehannaford offline ,  i planned to remove `rackspace` in favor of `openstack`

File this issue to track that

/sig openstack

/assign

### PR DESCRIPTION
**Pull request by NickrenREN**
**What this PR does / why we need it**:
For now, we have to implement functions in both `rackspace` and `openstack` packages if we want to add function for cinder, for example [resize for cinder](https://github.com/kubernetes/kubernetes/pull/51498).  Since openstack has implemented all the functions rackspace has,  and rackspace is considered deprecated for a long time, [rackspace deprecated](https://github.com/rackspace/gophercloud/issues/592) ,
after talking with @mikedanese  and @jamiehannaford offline ,  i sent this PR to remove `rackspace` in favor of `openstack`

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #52854

**Special notes for your reviewer**:

**Release note**:
```release-note
The Rackspace cloud provider has been removed after a long deprecation period. It was deprecated because it duplicates a lot of the OpenStack logic and can no longer be maintained. Please use the OpenStack cloud provider instead.
```

### CODE REVIEW

**Review by jamiehannaford — COMMENTED** [review]
Overall LGTM. 

I did a quick grep and we might also want to rewrite [this comment](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L487). 

Do we plan on documenting this change somewhere, or are we just going to rely on a changelog entry? If the latter, I think we should add more information (what exactly is removed and why).

**Comment by NickrenREN** [comment]
Thanks for your review @jamiehannaford . I have removed the rackspace related comment and rewrite the release note. PTAL, thanks

**Comment by jamiehannaford** [comment]
👍  LGTM

For the release note, how about:

> The Rackspace cloud provider has been removed after a long deprecation period. It was deprecated because it duplicates a lot of the OpenStack logic and can no be longer maintained. Please use the OpenStack cloud provider instead.

**Comment by NickrenREN** [comment]
SGTM, done, thanks @jamiehannaford

**Review by jamiehannaford — APPROVED** [review]

**Pull request merged**
