### PR TITLE
Fix link in readme

### LINKED ISSUE #86651: URL in some README is incorrect
**What happened**:

In below README files, URLs are written. But these URL include version name(master, release-1.0, etc...) which are enclosed in <> and not shown in md files.

- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/testing-manifests/storage-csi/external-snapshotter/README.md

- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/testing-manifests/storage-csi/external-provisioner/README.md

- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/testing-manifests/storage-csi/external-resizer/README.md

- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/testing-manifests/storage-csi/external-attacher/README.md

**What you expected to happen**:

URL will be shown correctly.

### PR DESCRIPTION
**Pull request by YuikoTakada**
**What type of PR is this?**

> /kind bug
> /kind documentation

**What this PR does / why we need it**:

in testing-manifests README files, URLs are written. But these URL include version name(master, release-1.0, etc...) which are enclosed in \<\> and not shown in md files. So this PR fixes this.

**Which issue(s) this PR fixes**:

Fixes #86651

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
/sig storage

`\<version\>` also doesn't look right:
https://github.com/kubernetes/kubernetes/blob/23e8ce7804b9094c32a92454349f01e9aae55b78/test/e2e/testing-manifests/storage-csi/external-attacher/README.md

why not use something like:
> The original file is https://github.com/kubernetes-csi/external-attacher/blob/VERSION/deploy/kubernetes/rbac.yaml

**Comment by YuikoTakada** [comment]
@neolit123 thank you for your comment. I'll do so.

**Review by neolit123 — COMMENTED** [review]
/lgtm
Thanks

**Pull request merged**
