### PR TITLE
Mark failing node serial tests as flaky

### PR DESCRIPTION
**Pull request by ehashman**
Tracked in:
- https://github.com/kubernetes/kubernetes/issues/103690
- https://github.com/kubernetes/kubernetes/issues/103691

#### What type of PR is this?

/kind cleanup
/sig node

#### What this PR does / why we need it:

As we try to get the kubelet serial job green, we want to exclude these known failures that we're tracking in issues to get better signal.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ehashman** [comment]
/milestone v1.22

per discussion in SIG Node CI subgroup

**Comment by ehashman** [comment]
Now that https://github.com/kubernetes/kubernetes/pull/103980 merged I'd expect the serial tests to basically be green after this PR. Let me see if I can kick off another run.

/test pull-kubernetes-node-kubelet-serial

**Comment by fromanirh** [comment]
/lgtm
the fixes are already in progress - tracked in the aforementioned issues.

**Comment by fromanirh** [comment]
failing in the dynamic configuration test:
```
 I0729 08:17:48.751]           <*errors.errorString | 0xc001f98af0>: {
I0729 08:17:48.752]               s: "checkConfigMetrics: case: Node.Spec.ConfigSource is nil: expect metrics (metrics.KubeletMetrics)map[kubelet_node_config_assigned:[<*>kubelet_node_config_assigned{node_config_kubelet_key=\"\", node_config_resource_version=\"\", node_config_source=\"local\", node_config_uid=\"\"} => 1 @[0]] kubelet_node_config_active:[<*>kubelet_node_config_active{node_config_kubelet_key=\"\", node_config_resource_version=\"\", node_config_source=\"local\", node_config_uid=\"\"} => 1 @[0]] kubelet_node_config_last_known_good:[<*>kubelet_node_config_last_known_good{node_config_kubelet_key=\"\", node_config_resource_version=\"\", node_config_source=\"local\", node_config_uid=\"\"} => 1 @[0]] kubelet_node_config_error:[<*>kubelet_node_config_error => 0 @[0]]] but got (metrics.KubeletMetrics)map[kubelet_node_config_error:[<*>kubelet_node_config_error => 0 @[0]]]", 
```

**Comment by fromanirh** [comment]
> failing in the dynamic configuration test:
> 
> ```
>  I0729 08:17:48.751]           <*errors.errorString | 0xc001f98af0>: {
> I0729 08:17:48.752]               s: "checkConfigMetrics: case: Node.Spec.ConfigSource is nil: expect metrics (metrics.KubeletMetrics)map[kubelet_node_config_assigned:[<*>kubelet_node_config_assigned{node_config_kubelet_key=\"\", node_config_resource_version=\"\", node_config_source=\"local\", node_config_uid=\"\"} => 1 @[0]] kubelet_node_config_active:[<*>kubelet_node_config_active{node_config_kubelet_key=\"\", node_config_resource_version=\"\", node_config_source=\"local\", node_config_uid=\"\"} => 1 @[0]] kubelet_node_config_last_known_good:[<*>kubelet_node_config_last_known_good{node_config_kubelet_key=\"\", node_config_resource_version=\"\", node_config_source=\"local\", node_config_uid=\"\"} => 1 @[0]] kubelet_node_config_error:[<*>kubelet_node_config_error => 0 @[0]]] but got (metrics.KubeletMetrics)map[kubelet_node_config_error:[<*>kubelet_node_config_error => 0 @[0]]]", 
> ```
> 
> Will deep dive into this ASAP

so same as https://github.com/kubernetes/kubernetes/issues/103879 (https://github.com/kubernetes/kubernetes/issues/103879#issuecomment-887864526)

**Comment by fromanirh** [comment]
/test pull-kubernetes-node-kubelet-serial
failing for different reasons each run now? (they seem flakes so far though)

**Comment by dims** [comment]
/approve
/lgtm

better than what we have now :)

**Comment by SergeyKanzhelev** [comment]
should we skip to let it in?

/skip

**Comment by dims** [comment]
+1 @SergeyKanzhelev

**Pull request merged**
