### PR TITLE
Add support for Job-managed pods to drain.

### PR DESCRIPTION
**Pull request by mml**

### CODE REVIEW

**Comment by davidopp** [comment]
LGTM

**Comment by davidopp** [comment]
Please update the documentation (man pages etc.) and code comments in the relevant places where it mentions ReplicationController to also mention Job.

**Comment by mml** [comment]
> Please update the documentation (man pages etc.) and code comments in the relevant places where it mentions ReplicationController to also mention Job.

Done.

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
