### PR TITLE
Add monitoring architecture

### PR DESCRIPTION
**Pull request by fgrzadkowski**
**What this PR does / why we need it**: This adds a description of monitoring architecture.

**Special notes for your reviewer**: This proposal have been already extensively discussed in [this doc](https://docs.google.com/document/d/1z7R44MUz_5gRLwsVH0S9rOy8W5naM9XE5NrbeGIqO2k); this is just a copy&paste so that it's in our repo.

@kubernetes/autoscaling @kubernetes/sig-instrumentation @DirectXMan12 @davidopp @piosz @derekwaynecarr @thockin 

**Release note**:

``` release-note
NONE
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34758)

### CODE REVIEW

**Comment by davidopp** [comment]
Note: I didn't actually read it, I just checked to make sure the diagram was there (and it was).

**Comment by davidopp** [comment]
LGTM

**Comment by wojtek-t** [comment]
@fgrzadkowski 
```
FAIL: changes needed but not made due to --verify
/go/src/k8s.io/kubernetes/docs/ is out of date. Please run hack/update-munge-docs.sh
```

Please fix

**Comment by fgrzadkowski** [comment]
Re-applying LGTM label as I only pushed output of `./update/update-all.sh`.

**Pull request merged**
