### PR TITLE
fix: remote unused code when build garbageCollector

### PR DESCRIPTION
**Pull request by colin404**
Change-Id: I67d33f12eda71972ab3d37e1ea9ffd30fb57de8a

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

Delete unused code, otherwise these code may lead to reading misunderstandings.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?
NONE

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
you need to sign the CLA
/ok-to-test

**Comment by colin404** [comment]
> CLA

OK

**Comment by colin404** [comment]
> [CLA Missing ID](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/20580498/125535/#/?version=2) [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/20580498/125535/#/?version=2)
> 
> * ❌ The email address for the commit ([9987a3a](https://github.com/kubernetes/kubernetes/commit/9987a3a6c71d445c6cd7baa623c7710e0d8bc7e1)) is not linked to the GitHub account, preventing the EasyCLA check. Consult [this Help Article](https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=86641302) and [GitHub Help](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) to resolve. (To view the commit's email address, add .patch at the end of this PR page's URL.) For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

/easycla

**Comment by colin404** [comment]
commit the PR with another commit email address. so close this PR.

**Pull request closed without merging**
