### PR TITLE
Do not track resource usage for host path volumes. 

### LINKED ISSUE #23255: Kubelet I/O usage abnormally high
After upgrading to Kubernetes 1.2.0, kubelet's `du` sub-process is using 95-99% of my read I/O constantly:

```
$ iotop
Total DISK READ :     321.10 K/s | Total DISK WRITE :      10.76 M/s
Actual DISK READ:     321.10 K/s | Actual DISK WRITE:       4.24 M/s
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN      IO    COMMAND
18979 be/7 root      321.10 K/s    0.00 B/s  0.00 % 99.12 % du -s -B 1 /
27430 be/4 9999        0.00 B/s    6.49 M/s  0.00 % 31.45 % Passenger RubyApp: /app/public (production) [utils.rb:110]
14566 be/4 9999        0.00 B/s    3.82 K/s  0.00 %  0.00 % nginx: worker process
14639 be/4 9999        0.00 B/s    3.82 K/s  0.00 %  0.00 % nginx: worker process
```

```
$ ps axjf | grep 18979 -B 2
    1  7889  7889  7889 ?           -1 Ssl      0   3:16 /opt/bin/kubelet --api-servers=https://k8s.example.com --config=/etc/kubernetes/manifests --cloud-provider=aws --cluster-dns=10.10.0.10 --cluster-domain=cluster.local --image-gc-high-threshold=70 --image-gc-low-threshold=50 --maximum-dead-containers=15 --allow-privileged=true --v=2
 7889  8030  7889  7889 ?           -1 S        0   0:01  \_ journalctl -k -f
 7889 18979  7889  7889 ?           -1 DN       0   0:08  \_ du -s -B 1 /
```

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        7.4G     0  7.4G   0% /dev
tmpfs           7.4G     0  7.4G   0% /dev/shm
tmpfs           7.4G  3.0M  7.4G   1% /run
tmpfs           7.4G     0  7.4G   0% /sys/fs/cgroup
/dev/xvda9       56G   33G   21G  62% /
/dev/xvda3      985M  551M  384M  59% /usr
tmpfs           7.4G     0  7.4G   0% /media
tmpfs           7.4G     0  7.4G   0% /tmp
/dev/xvda1      128M   66M   63M  52% /boot
/dev/xvda6      108M   60K   99M   1% /usr/share/oem
```

### PR DESCRIPTION
**Pull request by vishh**
They can contain loops.
Fixes #23255

### CODE REVIEW

**Comment by vishh** [comment]
cc @pwittrock @ncdc

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra @kubernetes/rh-storage

**Comment by pmorie** [comment]
@vishh does any user-facing doc need to change about host path?

**Comment by vishh** [comment]
@pmorie: I don't think any docs exist as of now since disk accounting isn't available for all the volumes as of now.

**Comment by dchen1107** [comment]
Looks like you disabled the entire host-based volume disk accounting in this PR. Can we do something smarter? Disabling disk accounting for read-only filesystems? And documented as known issue if the user want to mount the root filesystem, please use read-only?

**Comment by vishh** [comment]
@dchen1107: Accounting for hostpath is dubious. Since hostpath is not scoped to a pod, we cannot make any deterministic decisions based on host path usage. 
I think this PR is fine as-is.
I will post a separate patch to ignore read-only volumes in general and work on getting rid of `du` in favor of something that does the right thing.

**Comment by vishh** [comment]
@k8s-bot test node e2e experimental

**Comment by dchen1107** [comment]
Sorry, I misread the pr. I thought we disabled disk accounting for all host-based volumes, including empty dir. LGTM

**Comment by vishh** [comment]
@dchen1107: Can we include this in v1.2.1 or has the ship sailed? cc @david-mcmahon

**Comment by dchen1107** [comment]
We should include this one into v1.2.1

**Comment by eparis** [comment]
@bgrant0607 I'm going to add cherrypick-candidate back. Since this was done with the script I'm going to use it to try to get the bot to remove it.  Please ignore in the pick queue.

**Pull request merged**
