### PR TITLE
Uniform comment style.

### PR DESCRIPTION
**Pull request by m14815**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
The style of comment sentences on the same file are different, some are capitalized, some are not.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by hwdef — COMMENTED** [review]
Thanks for your contributions.

**Comment by m14815** [comment]
> Thanks for your contributions.

Thank you, I will try to improve my contribution quality.

**Pull request closed without merging**
