### PR TITLE
Automated cherry pick of #14748 upstream release 1.1

### PR DESCRIPTION
**Pull request by piosz**
cherry-pick of #14748

ref #14652

cc @mwielgus @davidopp @amygdala @brendandburns @roberthbailey @ncdc

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot unit test this please

**Comment by mikedanese** [comment]
```
09:00:46 # k8s.io/kubernetes/pkg/controller/node
09:00:46 _output/local/go/src/k8s.io/kubernetes/pkg/controller/node/nodecontroller_test.go:715: not enough arguments in call to NewNodeController
```

**Comment by bgrant0607** [comment]
@k8s-bot test this

**Comment by bgrant0607** [comment]
LGTM

**Comment by piosz** [comment]
Fixed compile issue.

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
