### PR TITLE
Change kubectl label and annotation list option stdout

### PR DESCRIPTION
**Pull request by zhouya0**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
As what said in https://github.com/kubernetes/kubernetes/pull/92576/files#r447859434.
The message is expected and should not be used is stdErr.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
/cc @soltysh 

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/retest
/kind backlog

**Comment by brianpursley** [comment]
/lgtm

Thanks!

**Pull request merged**
