### PR TITLE
add NodeInodePressure const to v1 api

### PR DESCRIPTION
**Pull request by caesarxuchao**
External API const should be consistent with Internal API const in this case.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36180)

### CODE REVIEW

**Review by derekwaynecarr — COMMENTED** [review]
I may have missed something, but I thought we were still just reporting DiskPressure.   I assume we report both as true @dashpole @vishh?

**Comment by vishh** [comment]
@derekwaynecarr that's my understanding as well. #33218 added a new condition and I did not know about it.

**Comment by vishh** [comment]
@caesarxuchao This PR should ideally not be needed.

**Comment by dashpole** [comment]
We report NodeInodePressure when we hit the inode threshold, and we report NodeDiskPressure when we hit the disk threshold.

**Comment by vishh** [comment]
Why do we need two separate conditions? To the end user inode is just an
implementation detail. Disk pressure can show up from either inodes or
actual files. It is useful to provide additional information as part of the
condition though.

**Comment by dashpole** [comment]
Vish and I spoke offline and decided to revert #33218.  To summarize the discussion, the reason for ever separating any conditions is because there are external use cases (scheduling, for example) that act differently based on what kind of pressure we are encountering.  While disk and inode pressure are different, there are no external use cases that would treat them differently.  If one arises in the future, we can split them again.  In this case, our goal is mainly to report to users that their pod was evicted because of inode or disk pressure.  This can be accomplished using the reason or message field, and does not need to involve separate conditions.  This PR should not be needed once the revert is complete.

**Comment by caesarxuchao** [comment]
@dashpole could you make sure the revert gets in 1.5? Then we can close this one. Thanks!

**Comment by dashpole** [comment]
yep, working on it as we speak.

**Pull request closed without merging**
