### PR TITLE
Automated cherry pick of #25512

### PR DESCRIPTION
**Pull request by colhom**
Cherry pick of https://github.com/kubernetes/kubernetes/pull/25512 on on release-1.2.

### CODE REVIEW

**Comment by roberthbailey** [comment]
@k8s-bot ok to test

**Comment by roberthbailey** [comment]
The unit test for hyperkube failed:

```
FAIL	k8s.io/kubernetes/cmd/hyperkube	0.240s
```

which seems relevant since this PR touches hyperkube.

**Comment by colhom** [comment]
@roberthbailey I've fetched release-1.2 locally, merged this branch in and I cannot reproduce. Unit tests for ./cmd/hyperkube pass on my end. Is there any way I can see the verbose output for the unit tests?

**Comment by roberthbailey** [comment]
@colhom -- you should be able to click the "Details" link next to the "Jenkins unit/integration" row to get to a GCS bucket with the test results. Click "artifacts" and then open "junit_v1,extensions-v1beta1,metrics-v1alpha1_20160602-210215.stdout" which has the test output. We can re-run the tests if you'd like, but please take a look at the output first before we decide that this is a flake.

**Comment by colhom** [comment]
@roberthbailey I've found the detailed output, and the errors coming back pretty weird:

```sh
--- FAIL: TestCobraCommandMessage (0.01s)
	hyperkube_test.go:122: Running full with args: ["hyperkube" "test-cobra-command" "--msg" "foobar"]
	hyperkube_test.go:126: Result err: unknown shorthand flag: 't' in -test.v=true, output: "Error: unknown shorthand flag: 't' in -test.v=true\nUsage:\n  test-cobra-command [flags]\n  test-cobra-command [command]\n\nAvailable Commands:\n  subcommand  subcommand\n\nFlags:\n      --google-json-key=\"\": The Google Cloud Platform Service Account JSON Key to use for authentication.\n      --log-flush-frequency=5s: Maximum number of seconds between log flushes\n      --msg=\"default message from cobra command\": message to print\n      --version[=false]: Print version information and quit\n\nUse \"test-cobra-command [command] --help\" for more information about a command.\n\nError: unknown shorthand flag: 't' in -test.v=true\n"
	<autogenerated>:31: 
                        
	Error Trace:	hyperkube_test.go:210
		
	Error:		"Error: unknown shorthand flag: 't' in -test.v=true
			Usage:
			  test-cobra-command [flags]
			  test-cobra-command [command]
			
			Available Commands:
			  subcommand  subcommand
			
			Flags:
			      --google-json-key="": The Google Cloud Platform Service Account JSON Key to use for authentication.
			      --log-flush-frequency=5s: Maximum number of seconds between log flushes
			      --msg="default message from cobra command": message to print
			      --version[=false]: Print version information and quit
			
			Use "test-cobra-command [command] --help" for more information about a command.
			
			Error: unknown shorthand flag: 't' in -test.v=true
			" does not contain "msg: foobar"
		
```

The root cause here is the hyperkube flag parser erroring out because there is an unknown flag, `-test.v=true`. I'm trying to figure out where this extra flag could be coming from, and why it's only affecting the cobra command and not the subcommand.

**Comment by roberthbailey** [comment]
ok to test

**Comment by roberthbailey** [comment]
@colhom can you rebase to get rid of the "This branch is out-of-date with the base branch" message?

**Comment by colhom** [comment]
@roberthbailey it's been rebased.

**Comment by colhom** [comment]
Looking into test failures now.

**Comment by roberthbailey** [comment]
@colhom there are still some test failures (jenkins unit/integration and jenkins verification) and it looks like you have to rebase again (sorry!).

**Comment by roberthbailey** [comment]
@colhom I just checked and it appears that we should ignore the jenkins verification result for this release branch. So there's just the unit/integration issues that need to be resolved.

**Comment by colhom** [comment]
@roberthbailey I've been able to reproduce and found that upgrading the cobra Godep dependency to match master fixes our unit test failures. The tests regex the help output of flagsets, so they are very fragile w.r.t version changes.

Assuming all the other unit tests pass, I think we're good to go on this one!

**Comment by colhom** [comment]
Cause of integration failure:

```sh
Generated docs are out of date. Please run hack/update-generated-docs.sh
!!! Error in ./hack/../hack/verify-generated-docs.sh:28
  '"${KUBE_ROOT}/hack/after-build/verify-generated-docs.sh" "$@"' exited with status 1
Call stack:
  1: ./hack/../hack/verify-generated-docs.sh:28 main(...)
Exiting with status 1
FAILED
```
Will fix

**Comment by colhom** [comment]
@roberthbailey all tests are passing!

**Comment by roberthbailey** [comment]
Thanks for sticking with it!

**Comment by colhom** [comment]
@roberthbailey do you know what the schedule is for v1.2.5? CoreOS has a few downstream projects using v1.2 currently that are blocking on this PR.

**Comment by roberthbailey** [comment]
Right now there isn't a schedule because no one has explicitly asked for a new build from the 1.2 branch. I take it this this is you asking. :)

@david-mcmahon

**Comment by colhom** [comment]
@roberthbailey yes please!

**Comment by roberthbailey** [comment]
[v1.2.5](https://github.com/kubernetes/kubernetes/releases/tag/v1.2.5) is now out!

**Comment by whitlockjc** [comment]
The current `github.com/spf13/cobra@master` fails to build due to it being incompatible with `github.com/spf13/pflag@master`.  Any attempt to build against Kubernetes right now is failing with the following:

```
# github.com/30x/k8s-multi-pod/vendor/github.com/spf13/cobra
vendor/github.com/spf13/cobra/command.go:1163: c.Flags().HasAvailableFlags undefined (type *pflag.FlagSet has no field or method HasAvailableFlags)
vendor/github.com/spf13/cobra/command.go:1168: c.PersistentFlags().HasAvailableFlags undefined (type *pflag.FlagSet has no field or method HasAvailableFlags)
vendor/github.com/spf13/cobra/command.go:1174: c.LocalFlags().HasAvailableFlags undefined (type *pflag.FlagSet has no field or method HasAvailableFlags)
vendor/github.com/spf13/cobra/command.go:1180: c.InheritedFlags().HasAvailableFlags undefined (type *pflag.FlagSet has no field or method HasAvailableFlags)
```

I'm working on a PR now but I figured I'd at least start the conversation here.

**Comment by roberthbailey** [comment]
How are you trying to build? Our CI build infrastructure is not complaining about builds on any of the active branches (1.2, 1.3, master).

**Comment by whitlockjc** [comment]
This is likely an issue with [glide](https://github.com/Masterminds/glide) but bear with me.  Let's say I've got the following `glide.yaml`:

```yaml
package: github.com/30x/k8s-multi-pod
import:
- package: github.com/spf13/cobra
  subpackages:
  - cobra
- package: k8s.io/kubernetes
  version: ~1.2.x
- package: speter.net/go/exp/math/dec/inf
  repo: https://github.com/go-inf/inf
  vcs: git
```

I run `glide up` to get the latest code based on the `glide.yaml`.  What happens is glide pulls down the latest `github.com/spf13/cobra` and an old `github.com/spf13/pflag`.  When I `go build`, I get the error above.  If I replace `vendor/github.com/spf13/pflag` with the latest, not the version specified in the `Godeps/Godeps.json` in Kubernetes, the build completes just fine.  It _seems_ that `github.com/spf13/cobra@master` does not work with `github.com/spf13/pflag@08b1a58`.

I can work on a reproduction recipe without glide if need be.

**Comment by whitlockjc** [comment]
Feel free to disregard as I cannot seem to reproduce this using `go get` directly.  I'll just mark this up as an issue with glide, although I'm not sure why updating `vendor/github.com/spf13/pflag` to the latest version from `08b1a58 ` fixes my build.

**Comment by whitlockjc** [comment]
I was able to fix this by using the same version of `github.com/spf13/cobra` that k8s is locked down to.  Here is my glide file that seems to let me build a CLI against k8s:

```yaml
package: github.com/30x/k8s-multi-pod
import:
- package: github.com/spf13/cobra
  version: 4c05eb1145f16d0e6bb4a3e1b6d769f4713cb41f
  subpackages:
  - cobra
- package: k8s.io/kubernetes
  version: ~1.2.x
- package: speter.net/go/exp/math/dec/inf
  repo: https://github.com/go-inf/inf
  vcs: git
```

**Comment by roberthbailey** [comment]
I'm glad you got it worked out.

**Pull request merged**
