### PR TITLE
Move unrelated methods from the factory to helper

### LINKED ISSUE #64106: Remove unrelated methods from the factory
To continue the work from https://github.com/kubernetes/kubernetes/pull/63984 and https://github.com/kubernetes/kubernetes/pull/63884 this issue helps track additional methods from the cmdutil.Factory that should further be removed, or turned into helpers, independent from the factory.

In *pkg/kubectl/cmd/util/factory_client_access.go*

- [x] MapBasedSelectorForObject `turn into helper` https://github.com/kubernetes/kubernetes/pull/64132
- [x] ProtocolsForObject `turn into helper` https://github.com/kubernetes/kubernetes/pull/64162
- [x] SuggestedPodTemplateResources `move to set_resources.go` https://github.com/kubernetes/kubernetes/pull/64134
- [x] Pauser / Resumer `move to rollout_pause.go / rollout_resume.go command` https://github.com/kubernetes/kubernetes/pull/64121/files
- [x] LabelsForObject `can be completely removed` https://github.com/kubernetes/kubernetes/pull/64113
- [x] Command `turn into helper` https://github.com/kubernetes/kubernetes/pull/64114
- [x] ResolveImage `can be completely removed` https://github.com/kubernetes/kubernetes/pull/64113
- [x] CanBeExposed `move to expose.go` https://github.com/kubernetes/kubernetes/pull/64111

Most of these should be turned into cmd/util helpers under the [polymorphichelpers](https://github.com/kubernetes/kubernetes/tree/master/pkg/kubectl/polymorphichelpers) package with a specific `.go` file for each, and an exposed global variable under [polymorphichelpers/interface.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/polymorphichelpers/interface.go) actually exposing a mutate-able var for that helper (refer to the examples already there).

cc @soltysh 

/assign @ellenkorbes 
/assign @juanvallejo
/assign @deads2k

### PR DESCRIPTION
**Pull request by wgliang**
**What this PR does / why we need it**:

Move unrelated methods from the factory to helper

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #64106

**Special notes for your reviewer**:

/cc @juanvallejo

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by juanvallejo — APPROVED** [review]

**Comment by juanvallejo** [comment]
/lgtm

@deads2k or @soltysh for approval

**Comment by deads2k** [comment]
/lgtm

thanks for the help.

**Comment by wgliang** [comment]
/cc @juanvallejo 
solve conflict and PTAL

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
