### PR TITLE
util/config` packages; filenames and methods should be updated to use…

### PR DESCRIPTION
**Pull request by RA489**
util/config packages; filenames and methods should be updated to use new names
fixes- https://github.com/kubernetes/kubeadm/issues/1125

### CODE REVIEW

**Comment by kad** [comment]
Looks ok for me, @fabriziopandini to approve.
/kind cleanup
/assign @fabriziopandini

**Review by fabriziopandini — APPROVED** [review]
@RA489 Thanks for this PR!
/lgtm
/approve

**Pull request merged**
