### PR TITLE
Automated cherry pick of #57420: add semver metadata regex

### PR DESCRIPTION
**Pull request by rphillips**
Cherry pick of #57420 on release-1.9.

#57420: add semver metadata regex

### CODE REVIEW

**Comment by mbohlool** [comment]
@rphillips the deadline for 1.9.3 cherrypick approvals is 5pm. Also can you add justification on why this need to be in 1.9 at all?

**Comment by rphillips** [comment]
We have to manually carry this patch forward for the following version string: 1.9.3+coreos.0 or 1.9.3+coreos.1.

**Comment by mbohlool** [comment]
/hold

the release branch is frozen for 1.9.3 release.

After lgtm/approval, this will go into 1.9.4 release.

**Comment by mbohlool** [comment]
Looks good, please ask reviewers/approvers to lgtm this PR.

**Comment by rphillips** [comment]
needs an approver

**Comment by mbohlool** [comment]
The branch is frozen. holding this for 1.9.5.

/hold

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/58476)

**Comment by mbohlool** [comment]
the PR is missing lgtm/approval.

**Pull request merged**
