### PR TITLE
WIP: stop asking cadvisor for stats when using CRI

### PR DESCRIPTION
**Pull request by haircommander**
**What type of PR is this?**

/kind bug
**What this PR does / why we need it**:
As this causes performance problems from duplicated work. This PR is a WIP implementation to see what breaks in tests. It is very naive

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
CRI-O previously hit performance problems when switching from cadvisor stats to CRI stats ([background](https://github.com/kubernetes/kubernetes/issues/51798)). This PR *may* mitigate some of these problems

**Does this PR introduce a user-facing change?**:

```release-note
none
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig node

### CODE REVIEW

**Comment by odinuge** [comment]
Ping @haircommander. Can you rebase this PR?

**Comment by haircommander** [comment]
I actually think this should be closed as the implementation of https://github.com/kubernetes/enhancements/pull/2364 will replace it in the correct way

**Pull request closed without merging**
