### PR TITLE
kubelet persistent store 

### PR DESCRIPTION
**Pull request by samsabed**
This PR persists podstatus, having this would help in GC and reliance on terminated containers for state. thought to get some feed back before proceeding down the rabbit hole.

The intention is to store the structs (pod/podstatus/containers/images) key=relevant id value=yaml string in directories, using boltdb which is an embeded, mmaped, k/v store, with tx support

/pods/
/podsstatus/
/containers/  ? nothing to store
/containers/tombstone/
/images/
/images/tombstone
/meta ?

It may seem clunky to store the data as is (serialized structs) and enrich it via directories, I am not sure there is value in deconstructing the struct into k/v, and picking bits and pieces from it.

### CODE REVIEW

**Comment by bprashanth** [comment]
@kubernetes/goog-node https://github.com/kubernetes/kubernetes/issues/489

**Comment by dchen1107** [comment]
why choosing boltdb over other databases? Why not use etcd?

**Comment by vishh** [comment]
Thanks for the PR @samsabed! We have been avoiding checkpointing all this while, to keep kubelet simple. The api-server persists all the data that the kubelet needs. When it comes to GC, we persist containers on a best effort basis for tracking restart counts. Since it is best effort, we can GC more often and not bother checkpointing.

**Comment by davidopp** [comment]
Closing the PR based on @vishh 's response, please reopen if you wish to discuss further.

**Comment by samsabed** [comment]
@vishh I took https://github.com/kubernetes/kubernetes/issues/12856#issuecomment-134314763  (we agree ... Kubelet would then need its own tombstones) meaning a persistence store , how do you think it would work ? or maybe one for @bgrant0607  (his comment)

I noticed there is talk about using docker labels, which would still rely on terminated continers to take care of the ```restartPolicy: Never``` as pointed by @yujuhong and perhaps doing something at the kubelet layer is better than doing it at the container runtime level ?

I appreciate a store would add some complexity but it also makes other things cleaner, for the record this isn't about a "checkpoint" e.g.  deleting, do-delete, deleted, I'm sure you and the rest of the people involved have spent more time thinking about this than I have so I'm not going to try to sell it :) BTW how about we call this "things I've tried to persist to the apisrver which may not have been persisted and things the apiserver doesn't store"  store  : )

@dchen1107 it's embeded ... starts and stops with the application, doesn't need a port or configuration, dependency on docker (etcd container) or networking

**Comment by vishh** [comment]
@samsabed: You arguments are sound. A persistence store is required in the long run. As of now, we have best-effort checkpointing by storing state in the api-server. To reduce the complexity at this stage for the project, we decided to make some API constructs like restart counts best-effort. In the case of GC, the kubelet needs to be running anyways. As long as kubelet notices the previous instance of a container before it GCs it, we are good. Unfortunately, the GC logic in kubelet is isolated and that needs to be fixed.
Most definitely, we will need checkpointing in the near future. We do not have the bandwidth to help design a future proof checkpointing scheme at the moment. We can revisit checkpointing once the kubelet internals have been refactored and the overall kubelet architecture is clear. WDYT?

**Comment by dchen1107** [comment]
@samsabed Thanks for your PR. We need checkpoint at node for a long run. Actually we need checkpoint not just for restart count. For restart count, we currently make it as best effort, same for several other features including max dead containers, etc. If we have checkpoint available, a lot of stuff could be simple, easy and cleaner. 

But we decided not introduce checkpoint now. We are still working on APIs at very components: Runtime, Volume plugin, Network plugin, and Kubelet, thus checkpoint format. Introducing checkpoint at this stage might make future upgrade / evolve much harder. This is debt we have to owe today. Thanks again.

**Comment by samsabed** [comment]
Thanks for the clear answers

**Comment by bgrant0607** [comment]
See also #489

**Pull request closed without merging**
