### PR TITLE
Retry updating services which failed to update last time

### PR DESCRIPTION
**Pull request by FengyunPan**

### CODE REVIEW

**Comment by grodrigues3** [comment]
@k8s-bot ok to test

**Comment by quinton-hoole** [comment]
I think that this is perhaps better handled by https://github.com/kubernetes/kubernetes/pull/41258 ?

**Comment by quinton-hoole** [comment]
@FengyunPan have you run the federation e2e tests against this PR?  Please post a summary of the results here.  Thanks.

https://github.com/kubernetes/kubernetes/tree/master/test/e2e_federation

**Comment by FengyunPan** [comment]
@quinton-hoole Oh, I will review #41258.

**Pull request closed without merging**
