### PR TITLE
Use k8s.io docs for memory/cpu request/limit

### PR DESCRIPTION
**Pull request by erictune**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/28696)

### CODE REVIEW

**Comment by vishh** [comment]
@k8s-bot test this github issue #IGNORE

**Comment by bgrant0607** [comment]
Probably we should do this everywhere in the types.go files.

**Comment by bgrant0607** [comment]
@erictune Verification checks failed. Looks like swagger needs to be regenerated.

@apelisse Another example of a PR sitting around for days due to lack of notification about failed checks.

**Comment by vishh** [comment]
@erictune 
```
/go/src/k8s.io/kubernetes/docs/api-reference is out of date. Please run hack/update-api-reference-docs.sh
```

**Pull request merged**
