### PR TITLE
Append newline to the "deleted context ... " and "deleted cluster" message

### LINKED ISSUE #35966: Deleted context output message is missing a newline.
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.1", GitCommit:"33cf7b9acbb2cb7c9c72a10d6636321fb180b159", GitTreeState:"clean", BuildDate:"2016-10-10T18:19:49Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.9", GitCommit:"ee10669e21109f86c21e8f7ceb1187d7910fe120", GitTreeState:"clean", BuildDate:"2016-10-20T20:37:18Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: GKE 1.4.4
- **OS** (e.g. from /etc/os-release): Local: OS X
- **Kernel** (e.g. `uname -a`): Darwin ... 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64
- **Install tools**:
- **Others**:

**What happened**:
Run: `kubectl config delete-context abc`
Output: kubectl `config delete-context abc
deleted context abc from /Users/.../.kube/configmyworkingdir $ `

**What you expected to happen**:
Run: `kubectl config delete-context abc`
Output: kubectl `config delete-context abc
deleted context abc from /Users/.../.kube/config`
`myworkingdir $ `

**How to reproduce it** (as minimally and precisely as possible):
Run: `kubectl config delete-context abc`

**Anything else do we need to know**:

### PR DESCRIPTION
**Pull request by saturnism**
**What this PR does / why we need it**: Append newline to the "deleted context ... " message.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #35966

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35967)

### CODE REVIEW

**Comment by pwittrock** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by ymqytw** [comment]
@k8s-bot gci gke e2e test this

**Comment by ymqytw** [comment]
LGTM
@saturnism Please squash for merging.

**Comment by ymqytw** [comment]
@saturnism Same issue with `pkg/kubectl/cmd/config/delete_cluster.go`.
@pwittrock I think we can change that in this PR, but we need to change the title.

**Comment by pwittrock** [comment]
@k8s-bot gci gke e2e test this

**Comment by ymqytw** [comment]
@k8s-bot test this

**Comment by pwittrock** [comment]
ok to test

**Comment by pwittrock** [comment]
@k8s-bot test this

**Comment by ymqytw** [comment]
@pwittrock I think we can include this bug fixing in `v1.5` with no risk.

**Comment by pwittrock** [comment]
@saad-ali This is a low-risk bug fix to the kubectl output

**Comment by dims** [comment]
agree on impact @pwittrock

**Comment by saad-ali** [comment]
> @saad-ali This is a low-risk bug fix to the kubectl output

Ack. Thanks

**Pull request merged**
