### PR TITLE
Periodically defragment etcd

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #45037

### CODE REVIEW

**Comment by wojtek-t** [comment]
@xiang90 @hongchaodeng @mml @lavalamp @Kashomon @crassirostris

**Comment by wojtek-t** [comment]
@k8s-bot unit test this

**Comment by xiang90** [comment]
let us hold this for a while. i still want to figure out the root cause. this might mask the problem. defrag is not super efficient and is not designed to run frequently.

**Comment by wojtek-t** [comment]
> let us hold this for a while. i still want to figure out the root cause. this might mask the problem. defrag is not super efficient and is not designed to run frequently.

@xiang90 - sure. If you think that there might be some problem in etcd itself that is causing the db size to grow, I'm all for waiting with this PR and debugging etcd itself.
This PR seems more like a mitigation than solving the real problem, and I think it can definitely wait for few more days.

**Comment by xiang90** [comment]
> This PR seems more like a mitigation than solving the real problem, and I think it can definitely wait for few more days.

I am not exactly sure right now. I can believe it if you do snapshot very frequently, but it is not really the case.

If we want some quick workaround, defrag is OK... But defrag is a blocking operations that can block etcd upto 10 seconds if you have a large dataset and slow disk... 

If this is not super urgent, the first thing I would do next week is to figure out the root cause of it.

**Comment by lavalamp** [comment]
> I can believe it if you do snapshot very frequently, but it is not really the case.

How often is "frequently"? Hourly?

I am a bit surprised to find that we trigger compaction as part of the etcd driver here. How does this work in HA configurations?

**Comment by xiang90** [comment]
> How often is "frequently"? Hourly?

minutes

>   compaction as part of the etcd driver here. How does this work in HA configurations?

the trigger is leader elected.

**Comment by krmayankk** [comment]
@wojtek-t is this applicable to etcd3 only ? What if we are using etcd 2.7 ?

**Comment by wojtek-t** [comment]
> @wojtek-t is this applicable to etcd3 only ? What if we are using etcd 2.7 ?

You meant 2.3.7, right? This problem doesn't exist in 2.*.* versions.

**Comment by mml** [comment]
@wojtek-t if you want a review of this, I should have time this week.  Just glanced and it looks straightforward.

**Comment by xiang90** [comment]
Just a reminder: defrag is a stop the world operation. If you have a db that is actually 1GB or so, defrag can freeze everything for 10+ second especially when you only run 1 etcd node.

**Pull request closed without merging**
