### PR TITLE
add some notes for e2e preserve source pod ip test

### PR DESCRIPTION
**Pull request by chengjoey**
#### What type of PR is this?
/kind documentation
#126089 

#### What this PR does / why we need it:
add some notes for e2e preserve source pod ip test
print possible reasons for failure when the test fails

### CODE REVIEW

**Review by Octopusjust — COMMENTED** [review]
/ok-to-test

**Comment by chengjoey** [comment]
added some notes, if it is not necessary, please feel free to close this PR

**Comment by aojea** [comment]
/lgtm
/approve

test timed out in pull-kubernetes-e2e-gci-gce-ipvs	👀

**Pull request merged**
