### PR TITLE
Enable storage class support in Azure File volume

### PR DESCRIPTION
**Pull request by rootfs**
**What this PR does / why we need it**:
Support StorageClass in Azure file volume

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Support StorageClass in Azure file volume

```

### CODE REVIEW

**Comment by rootfs** [comment]
@colemickens @brendandburns

**Comment by colemickens** [comment]
Why do you add the secret here? You didn't do this for the AzureDisk dynamic provisioner did you?

**Comment by rootfs** [comment]
@colemickens right, for azure disk, no secret is needed in Azure API. 

Azure file is different, it needs a username (i.e. `storageaccountname` in secret) and password (i.e. `storageaccountkey` in secret) to mount a CIFS share. When we create an Azure file share for a PVC, we have to ensure the secret is in the PVC's namespace so when Pod picks the PVC, the secret used by the PV exists.

**Comment by rootfs** [comment]
@kubernetes/sig-storage-misc

**Comment by colemickens** [comment]
I think I understand: AzureDisk needs the user/pass for Storage too, but those values are used by k-c-m which has access to the Azure cloudprovider auth context. On the other hand, for AzureFiles, the user/pass is used directly by `mount` under `kubelet` where you might not have access to the cloudprovider.

Is that the gist?

**Comment by rootfs** [comment]
@colemickens yes, that's the idea.

**Comment by colemickens** [comment]
Looks good to me. Thanks @rootfs.

**Comment by rootfs** [comment]
@saad-ali PTAL, thanks

**Comment by rootfs** [comment]
@k8s-bot cvm gce e2e test this

**Comment by rootfs** [comment]
@k8s-bot unit test this

**Pull request merged**
