### PR TITLE
fix typos in cmd/kubeadm and cmd/kube-scheduler

### PR DESCRIPTION
**Pull request by loopever**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix some typo.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by odinuge — APPROVED** [review]
Thanks!

/ok-to-test
/lgtm

**Review by neolit123 — COMMENTED** [review]
/lgtm

/approve
(for kubeadm)

**Comment by neolit123** [comment]
/retitle fix typos in cmd/kubeadm and cmd/kube-scheduler

**Comment by Huang-Wei** [comment]
/approve
(for scheduling)

**Comment by neolit123** [comment]
/lgtm
this can merge once code freeze for 1.19 ends.

**Pull request merged**
