### PR TITLE
Surface replica count update errors in log

### PR DESCRIPTION
**Pull request by pmorie**

### CODE REVIEW

**Comment by pmorie** [comment]
@kubernetes/goog-control-plane

**Comment by pmorie** [comment]
@k8s-bot test this

**Comment by pmorie** [comment]
Thanks @mikedanese

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by pmorie** [comment]
@wojtek-t Any way I can see the errors from Jenkins?

**Comment by wojtek-t** [comment]
@pmorie - sorry I missed this
It looks like a flake

@k8s-bot unit test this please

**Pull request merged**
