### PR TITLE
kubeadm: Add `FeatureGates` for `ResetConfiguration` of v1beta4

### PR DESCRIPTION
**Pull request by chendave**
Our latest finding is that InitConfiguration is not able to be retrieved from cluster on worker nodes, and hence, the `FeatureGates` configuration from current cluster is unknown as well, adding `FeatureGates` to `ResetConfiguration` provides a way for users to specify the information where it's needed.

/kind api-change

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
see: https://github.com/kubernetes/kubernetes/pull/121281#discussion_r1361841252 for the more context about this change.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
/hold
this need more eyes.

**Comment by chendave** [comment]
> the client inside kubelet.conf is granted specific privileges to fetch the kubeadm-config cm.

hmm... I didn't aware of that, will try it and get back to you later.

**Comment by neolit123** [comment]
> > the client inside kubelet.conf is granted specific privileges to fetch the kubeadm-config cm.
> 
> hmm... I didn't aware of that, will try it and get back to you later.

here is the RBAC that does that:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/uploadconfig/uploadconfig.go#L117-L120

so any node (part of `system:nodes` Group) i.e. kubelet.conf client certificate should be able to fetch the kubeadm-config CM.

**Comment by chendave** [comment]
thanks @neolit123 👍

**Review by neolit123 — COMMENTED** [review]
/close
i don't think this was needed. let's revisit if we have to.

https://github.com/kubernetes/kubernetes/pull/121348#issuecomment-1770348243
https://github.com/kubernetes/kubernetes/pull/121348#issuecomment-1770368486

**Pull request closed without merging**
