### PR TITLE
Use framework.ExpectNoError() for e2e/autoscaling

### PR DESCRIPTION
**Pull request by s-ito-ts**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Replaces Expect(err).NotTo(HaveOccurred()) with ExpectNoError() in e2e/autoscaling.

**Which issue(s) this PR fixes**:
Ref: #77103

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
/sig testing

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/ok-to-test

**Comment by DirectXMan12** [comment]
/unassign @DirectXMan12 

This is no longer my area -- I'm no longer an owner here as of https://github.com/kubernetes/kubernetes/pull/76110

**Review by oomichi — COMMENTED** [review]
Much readable, thanks

/lgtm

**Comment by s-ito-ts** [comment]
/assign @bskiba
for approval

**Pull request merged**
