### PR TITLE
Update Azure max data disk count map

### PR DESCRIPTION
**Pull request by bennerv**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
update max azure data disk count map with new VM types

#### Which issue(s) this PR fixes:
Fixes #
> I don't believe there's an issue filed for a more recent update.  

#### Special notes for your reviewer:
https://github.com/kubernetes/kubernetes/issues/77461#issuecomment-492488756 -> shows how to update this.

I attached a txt file with the new VM types that were added with their values.  
* [new-types.txt](https://github.com/kubernetes/kubernetes/files/9184078/new-types.txt)

#### Does this PR introduce a user-facing change?

```release-note
update max azure data disk count map with new VM types
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
update max azure data disk count map with new VM types
```

/priority important-soon
/sig cloud-provider
/area provider/azure

### CODE REVIEW

**Review by ross-bryan — APPROVED** [review]
lgtm

**Comment by jboutaud** [comment]
As context to this PR, since the newer instance types are not defined, customers trying to use the newer instance types are limited to 16 disks (the default value) rather than the actual number of support disks. This is specifically problematic for ARO with the LSv3 family where the larger sizes support more disks.

**Review by feiskyer — APPROVED** [review]
/lgtm

**Pull request merged**
