### PR TITLE
hpa: cleanup `currentReplicas` code

### PR DESCRIPTION
**Pull request by huiwq1990**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pbetkier** [comment]
Makes sense.

/triage accepted
/ok-to-test

**Review by pbetkier — APPROVED** [review]
/lgtm

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
