### PR TITLE
Fixing local cluster up

### PR DESCRIPTION
**Pull request by aanm**
hack: fix local-cluster-up advertise_address default value
Fixes: 9fc1d61

Signed-off-by: André Martins aanm90@gmail.com

ping @dims

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33582)

### CODE REVIEW

**Comment by dims** [comment]
This looks good to me. 👍

**Comment by janetkuo** [comment]
@k8s-bot ok to test

**Comment by dims** [comment]
@k8s-bot gke e2e test this

**Comment by dims** [comment]
@nikhiljindal ready now

**Comment by dims** [comment]
@janetkuo can you please lgtm this for me?

**Pull request merged**
