### PR TITLE
[WIP]: new topology manager policy:(Pod level single numa node)

### PR DESCRIPTION
**Pull request by bg-chun**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
 - [KEP] : https://github.com/kubernetes/enhancements/pull/1752
- [Goal]
  - Add pod-level-single-numa-node policy to support binding all containers in a pod to the same NUMA node, otherwise, pod will be rejected.
- [Motivation]
  - to achieve higher performance when deploying a pod that has inter-connected containers to work , See KEP for more details.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
New kubelet flag will be added for new topology manager policy.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
 - [KEP] : https://github.com/kubernetes/enhancements/pull/1752

### CODE REVIEW

**Comment by bg-chun** [comment]
Todo:
- Add additional unittest for devicemanager.
- Add mockHintProviderV2(which supports Allocate()/DeAllocate()) and addtional unittest for pod-level-single-numa-node policy

**Comment by klueska** [comment]
I'm not a huge fan of adding a `DeAllocate()` that operates as you describe. While it would technically work, it is unpleasant to have to constantly allocate / deallocate on a per-container basis in search of an allocation that satisfies the single NUMA constraint across all containers.

It also adds confusion around the semantics of the *actual*  deallocation of resources that happens inside the `HintProvider` when it is ready to free resources upon container completion. Does this `DeAllocate()` function also serve that purpose? If so, is it up to the `TopologyManager` to trigger it once the container completes?  If not, why not -- since it's part of the interface, one would think that it needed to?

With this said, I'm wondering if there's not some other API call we could add to a `HintProvider` that would allow the `TopologyManager` to make its `pod-level-single-numa-node` decision more directly?

Maybe a `GetPodLevelTopologyHints(pod *v1.Pod) map[string][]TopologyHint)` call, which returns a hint across all containers in the pod, instead of for just a single container?

Unless I'm missing something, if this API was in place, implementing the `pod-level-single-numa-node` policy would be as simple as calling this function instead of the normal `GetTopologyHints()`, and then feeding it through the existing `single-numa-node` policy logic to determine if we should admit the pod or not. Allocation on each container would then just use this same hint for all of them.

It would turn this:
```
for container := range append(InitContainers, Containers...) {
    for provider := range HintProviders {
        hints += provider.GetTopologyHints(pod, container)
    }

    bestHint := policy.Merge(hints)

    for provider := range HintProviders {
        provider.Allocate(container, bestHint)
    }
}
```
into this:
```
for provider := range HintProviders {
    hints += provider.GetPerPodTopologyHints(pod)
}

bestHint := policy.Merge(hints)

for container := range append(InitContainers, Containers...) {
    for provider := range HintProviders {
        provider.Allocate(container, bestHint)
    }
}
```

This feels much simpler / cleaner if you think it makes sense.

**Comment by bg-chun** [comment]
>It also adds confusion around the semantics of the actual deallocation of resources that happens inside the HintProvider when it is ready to free resources upon container completion. Does this DeAllocate() function also serve that purpose?
=> Nope, the original concept of `DeAllocate` was revert pre-resource allocation that made in pod addmission time, but what I found from device manager was It allocates resources in pod admission time(CPU Manager does not do that, this is my first time to look detail of device manager.), and it seems there was no way to trigger actual resource de-allocation in devicemanager, that was reason why I asked you about concept of `DeAllocate` interface whether it make sense or not before on slack.


>With this said, I'm wondering if there's not some other API call we could add to a HintProvider that would allow the TopologyManager to make its pod-level-single-numa-node decision more directly?
>
>Maybe a GetPodLevelTopologyHints(pod *v1.Pod) map[string][]TopologyHint) call, which returns a hint across all containers in the pod, instead of for just a single container?
=> If introducing `GetPodLevelTopologyHints` is acceptable, I would do that.

**Comment by klueska** [comment]
Can you elaborate a bit on the use case for this before diving in deeper? I can (roughly) see why it might be useful, but is there a concrete use case you can point to that requires this?

**Comment by bg-chun** [comment]
> Can you elaborate a bit on the use case for this before diving in deeper? I can (roughly) see why it might be useful, but is there a concrete use case you can point to that requires this?

=> OK, I can explain , but can we move to [KEP PR](https://github.com/kubernetes/enhancements/pull/1752) to discuss?

**Pull request closed without merging**
