### PR TITLE
Remove kubectl describe test from flaky list

### PR DESCRIPTION
**Pull request by janetkuo**
## Pull Request Guidelines
1. Please read our [contributor guidelines](https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md).
2. See our [developer guide](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md).
3. Follow the instructions for [labeling and writing a release note for this PR](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/pull-requests.md#release-notes) in the block below.

``` release-note
* Use the release-note-* labels to set the release note state 
* Clear this block to use the PR title as the release note 
-OR-
* Enter your extended release note here
```

Ref #25083 #25911

[Analytics]()

### CODE REVIEW

**Comment by spxtr** [comment]
It flaked several times after #24849 went in.

**Comment by spxtr** [comment]
It's broken: #25677

**Comment by spxtr** [comment]
Please reassign when the test is fixed.

**Comment by janetkuo** [comment]
It looks pretty green now. 
https://gke-testdash.corp.google.com/#gce-flaky&width=5
https://gke-testdash.corp.google.com/#gke-flaky&width=5

Will watch it to see if it's still flaky

**Comment by janetkuo** [comment]
@k8s-bot e2e test this issue: #25887

**Comment by janetkuo** [comment]
#25784 #26122 should fix this issue. No flakes observed on gce-flaky or gke-flaky since 23rd. Ref #25911

**Comment by spxtr** [comment]
Ok.

**Pull request merged**
