### PR TITLE
Set resource limit for fluentd-elasticsearch container based on data …

### PR DESCRIPTION
**Pull request by dchen1107**
…collected by #5880 

@saad-ali @satnam6502

### CODE REVIEW

**Comment by satnam6502** [comment]
It would be nice to have a few words about why these limits were chosen.

**Comment by dchen1107** [comment]
I said above: based on https://github.com/GoogleCloudPlatform/kubernetes/issues/5880#issuecomment-113984085  :-)

**Comment by a-robinson** [comment]
Is fluentd-gcp being left off accidentally or intentionally (out of concern that its constraints are slightly different from fluentd-es)?

**Comment by satnam6502** [comment]
I would not expect the fluentd-gcp resource usage to be very different from fluentd-elasticsearch.

**Comment by a-robinson** [comment]
Neither would I

**Comment by dchen1107** [comment]
I am closing this one, and will send a new pr to address all addons resource limit soon. Thanks!

**Pull request closed without merging**
