### PR TITLE
typo fixed with NodeInclusionPolicy

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

#### What type of PR is this?
/kind cleanup
/sig scheduling

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kerthcet** [comment]
integration test error: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/112784/pull-kubernetes-integration/1575427589374218240

**Review by sanposhiho — APPROVED** [review]
/lgtm

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
