### PR TITLE
Add prometheus metrics for altTokenSource.

### PR DESCRIPTION
**Pull request by cjcullen**
This will let us monitor these requests on a per-master basis.

### CODE REVIEW

**Comment by cjcullen** [comment]
@a-robinson

**Comment by yujuhong** [comment]
We need two leads to sign off on this. @roberthbailey, @alex-mohr

**Comment by alex-mohr** [comment]
LGTM.  I think we dropped the 2 leads policy and switched to a single area owner, so ok-to-merge.

**Comment by yujuhong** [comment]
> LGTM. I think we dropped the 2 leads policy and switched to a single area owner, so ok-to-merge.

Ah...was there an announcement email somewhere?

**Comment by roberthbailey** [comment]
LGTM.

**Pull request merged**
