### PR TITLE
convert int32 to pointer using library function

### PR DESCRIPTION
**Pull request by 0xff-dev**
#### What type of PR is this?
convert `int32` to `pointer` using library function.
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?
NONE

```release-note
NONE
```

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/lgtm

Thanks

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
