### PR TITLE
Automated cherry pick of #45311 #43545 upstream release 1.6

### PR DESCRIPTION
**Pull request by divyenpatel**
Cherry pick of #45311 #43545 on release-1.6.

#45311: Fetch VM UUID from - /sys/class/dmi/id/product_serial 
#43545: Remove credentials on worker nodes for vSphere cloud provider.

 @luomiao @BaluDontu @abrarshivani @tusharnt

### CODE REVIEW

**Comment by imkin** [comment]
@k8s-bot ok to test

**Comment by divyenpatel** [comment]
@imkin Jenkins Verification failed. looks like error is not related to the change in the PR.

```
I0511 14:55:35.060] +++ /go/src/k8s.io/kubernetes/_tmp/openapi-spec/swagger.json	2017-05-11 14:20:14.369762084 -0700
I0511 14:55:35.061] @@ -2,7 +2,7 @@
I0511 14:55:35.061]    "swagger": "2.0",
I0511 14:55:35.061]    "info": {
I0511 14:55:35.061]     "title": "Kubernetes",
I0511 14:55:35.061] -   "version": "v1.6.4"
I0511 14:55:35.061] +   "version": "v1.6.3"
I0511 14:55:35.061]    },
I0511 14:55:35.061]    "paths": {
I0511 14:55:35.061]     "/api/": {
I0511 14:55:35.062] /go/src/k8s.io/kubernetes/api/openapi-spec is out of date. Please run hack/update-openapi-spec.sh
I0511 14:55:35.067] FAILED   hack/make-rules/../../hack/verify-openapi-spec.sh	122s
```

**Comment by divyenpatel** [comment]
@k8s-bot verify test this

**Comment by enisoc** [comment]
@k8s-bot verify test this

/lgtm

**Pull request merged**
