### PR TITLE
Automated cherry pick of #104467: fix 104329: check for headless before trying to release

### PR DESCRIPTION
**Pull request by dprotaso**
Cherry pick of #104467 on release-1.20.

#104467: fix 104329: check for headless before trying to release

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
/unassign
/assign @thockin 

looks like Tim had more context on the master PR

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
