### PR TITLE
Replace references to http://releases.k8s.io/HEAD/docs/user-guide/

### PR DESCRIPTION
**Pull request by errordeveloper**
All of the anchor references are broken right now, so this change fixes that (at least).

I only touched `http://releases.k8s.io/HEAD/docs/user-guide/`, as all files in `docs/user-guide` had been moved, apart `kubectl*` ones (but those aren't referenced anywhere in the code for some reason.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33574)

### CODE REVIEW

**Comment by pwittrock** [comment]
@errordeveloper Looks like the verify failed

**Comment by errordeveloper** [comment]
Yes, will try `hack/update-api-reference-docs.sh` now.

**Comment by errordeveloper** [comment]
@pwittrock verification should pass now. It touches a lot of bits, so let's get it in so I don't need to keep rebasing two times a day.

**Comment by errordeveloper** [comment]
@k8s-bot gke e2e test this

**Comment by pwittrock** [comment]
@k8s-bot gci gce e2e test this

**Comment by pwittrock** [comment]
SGTM.  The test failures should be flakes since this pr should only update comments, but would be good to have them pass for good measure on a pr this large.

**Comment by nikhiljindal** [comment]
We can now update versionize-docs.sh and update-imported-docs.sh as well that do a sed on releases.k8s.io

**Comment by errordeveloper** [comment]
@nikhiljindal ok, so do you want me to do?
@pwittrock did you intend to add `lgtm` label back, or not?

**Comment by nikhiljindal** [comment]
@errordeveloper I dont think this should break those scripts, so should be fine to do it separately.

**Comment by errordeveloper** [comment]
I've rebased and ran `./hack/update-openapi-spec.sh`.

**Comment by errordeveloper** [comment]
@k8s-bot kubemark e2e test this

**Comment by errordeveloper** [comment]
@k8s-bot kubemark e2e test this

**Comment by pwittrock** [comment]
@k8s-bot kubemark e2e test this

**Pull request merged**
