### PR TITLE
cleanup(kubelet): use IsSuperset to avoid interim slice

### PR DESCRIPTION
**Pull request by binacs**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Use `A.IsSuperset(B)` instead of `A.HasAll(B.List())` to avoid the overhead of interim slice and sorting in `B.List()`.

And use `UnsortedList` instead of `List` to avoid unnecessary sorting.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by binacs** [comment]
kindly ping @feiskyer for review

**Comment by binacs** [comment]
kindly ping @feiskyer @mrunalp for approval

**Review by mrunalp — APPROVED** [review]

**Comment by mrunalp** [comment]
@dims ptal

**Pull request closed without merging**
