### PR TITLE
Using full url format as runtime endpoint

### PR DESCRIPTION
**Pull request by chendave**
Or else, kubelet will throw a warning message as below, 

> "Using this format as endpoint is deprecated, please consider using full url format." deprecatedFormat="/run/containerd/containerd.sock" fullURLFormat="unix:///run/containerd/containerd.sock"

code is here, 
https://github.com/kubernetes/kubernetes/blob/33aba7ee025dfddcc140d20e9ca353ffd425f1ae/pkg/kubelet/util/util_unix.go#L99-L105

Signed-off-by: Dave Chen <dave.chen@arm.com>

#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
kindly ping @mm4tt , a really simple cleanup, could you pls help to approve?

**Comment by mm4tt** [comment]
Sorry, wasn't aware of this. Let's see if the kubemark test passes

**Pull request merged**
