### PR TITLE
support GPU CRI in cadvisor

### PR DESCRIPTION
**Pull request by tianshapjq**
**What this PR does / why we need it**:
As discussed at length, we need to support CRI to collect gpu stats in cadvisor. We have done this in our project and I would like to make this PR to give a try.

The design comes in the following steps:
1. Containers should combine their attached gpus' spec and stats when doing housekeeping.
2. We start a single thread using nvidia-smi command to collect all gpu spec. Gpu spec includes three params: core_limit, memory_total and power_limit. Core_limit represents for the number of gpus attached to the container, it's an uint64 number; Memory_total represents the total memory of each attached gpu, it's a slice consisting of uint64 numbers; power_limit represents for the power limit of each attached gpu, also is a slice but consisting of float64 numbers. Considering the spec of gpu would not change once we get the info, we only collect the spec of all gpus once.
3. Gpu stats collection also be done in another single thread, but repeats every tick time. To avoid a large amount of callings to GPU, we consider calling nvidia-smi every tick time and store the data to a map called gpuStatsMap, and containers will get gpu stats from this map when doing its housekeeping. By using command "nvidia-smi --format=csv,noheader,nounits --query-gpu=utilization.gpu,memory.used,power.draw,temperature.gpu" we can get the core_usage memory_usage power_draw and temperature of all gpus in the node. When container is doing its housekeeping, it would first finds out which gpus it attaches with, and gets stats from the gpuStatsMap using the gpu index. The index mapping between GPU and gpuStatsMap connects like this:
	a) device path such as /dev/nvidia1 is mounted to container, and we get the index "1". The device path can be obtained using HostConfig.Devices via dockerClient.
	b) nvidia-smi prints out all gpu data in index order, then we can connect them using the index such as "1".
	c) using the index as the key to get value from the gpuStatsMap.
4. Fullfill some structs representing for gpu spec and stats in v1/container.go, including GpuSpec struct and GpuStats struct.

Some improvements in the future:
1. Abstract an interface to be compatible with different GPUS. The interface would expose several methods such as CollectGpuSpec() and CollectGpuStats().
2. Dealing with more other exceptions with nvidia-smi command.
3. Support nvml lib but this may not be done in this PR for what had been discussed before.

This PR is still working in progress, if any suggestions please let me know :)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
[kubernetes/community#414](https://github.com/kubernetes/community/pull/414)

**Release note**:

```release-note
```support cadvisor collecting gpu stats.

### CODE REVIEW

**Comment by k82cn** [comment]
> As discussed at length, we need to support CRI to collect gpu stats in cadvisor. 

Please create PR to cadvisor repo, and then create PR to update godep in k8s.

**Comment by tianshapjq** [comment]
@k82cn thanks, i will commit to cadvisor :)

**Comment by cmluciano** [comment]
related https://github.com/google/cadvisor/issues/1436

**Comment by grodrigues3** [comment]
@k8s-bot ok to test

**Comment by tianshapjq** [comment]
@grodrigues3 Is this ok-to-test in kubernetes? Or I still need to commit to cAdvisor?

**Comment by cmluciano** [comment]
This is making changes directly to the vendored code and should be closed in favor of a Godeps update.

**Comment by dchen1107** [comment]
@tianshapjq Thanks for submitting the pr. Can we resubmit this pr to cadvisor, and move the discussion to https://github.com/google/cadvisor/issues/1436? We normally cut cadvisor release, then vendor here. I am closing this pr. Thanks!

**Pull request closed without merging**
