### PR TITLE
Automated cherry pick of #71276: WIP: Handle failed attach operation leave uncertain

### PR DESCRIPTION
**Pull request by jingxu97**
Cherry pick of #71276 on release-1.12.

#71276: WIP: Handle failed attach operation leave uncertain

### CODE REVIEW

**Comment by jingxu97** [comment]
cc @msau42

**Comment by msau42** [comment]
I don't think we support 1.12 anymore

**Comment by mattjmcnaughton** [comment]
> I don't think we support 1.12 anymore

+1 afaik, 1.12.10 was the last patch release for the 1.12 branch. 1.13.x however is still open for patch releases :)

**Comment by jingxu97** [comment]
close this since  we support 1.12 anymore

**Pull request closed without merging**
