### PR TITLE
nodeport tests: node addresses must match the service IP family

### PR DESCRIPTION
**Pull request by hakman**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

Ref: https://github.com/kubernetes/kubernetes/pull/103180
Services affinity timeout test still wasn't taking into account the Service IP family for testing the NodePort services.
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-grid-scenario-ipv6-conformance/1408663741679013888

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/lgtm
/approve
thanks for catching it

**Comment by hakman** [comment]
Thanks for the quick review @aojea!

**Pull request merged**
