### PR TITLE
Delete redundant err definition

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
Delete reduandant err definition
Line 307 has err definition and initialization.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by feiskyer** [comment]
@k8s-bot ok to test

**Comment by zhangxiaoyu-zidif** [comment]
@xiangpengzhao 
Need your /ok-to-test
Thanks.

**Comment by xiangpengzhao** [comment]
/ok-to-test

:)

**Comment by xiangpengzhao** [comment]
/lgtm
/retest
ping @vishh for approval :)

**Comment by zhangxiaoyu-zidif** [comment]
ping @vishh

**Comment by zhangxiaoyu-zidif** [comment]
@mikedanese
PTAL

**Comment by zhangxiaoyu-zidif** [comment]
ping @vishh

**Comment by zhangxiaoyu-zidif** [comment]
ping @vishh for approval

**Comment by zhangxiaoyu-zidif** [comment]
@wojtek-t 
PTAL

**Pull request merged**
