### PR TITLE
Cherry pick of #109706: Avoid re-syncing LBs for ETP=local services

### LINKED ISSUE #111539: [scale] node state changes causes excessive LB re-configurations
### What happened?

There is scale bug related to the cloud-controller-manager, namely: when a cluster reaches a state where the relation between the amount of LBs and cluster nodes reaches an almost equal amount (i.e: a many-to-many relation between LBs and nodes) the amount of cloud API calls performed by the CCM to sync LBs can become overwhelming for the cloud provider. This can (among other things) lead to:

1. an excessive amount of cloud API calls for the LB re-configurations
2. rate limiting by the cloud provider as an effect of 1.
3. or worse: a non-trivial amount of time to sync all services in the cluster, leading to desynchronized LBs.

An example of problem 3. is: imagine we have 200 LBs and 500 nodes, on clusters at such scale, the amount of events processed by the CCM for transitioning node state can become important. The current implementation of the CCM will resync all 200 LB services for any node which has a transitioning state - as to keep the LBs' configured backends in sync with the state of the cluster. It has been observed that on clusters at that scale, the cloud provider can take up to hours to process a full resync for all services. A scenario such as the below is hence not improbable (and actually quite likely):

1. Node25 transitions from Ready -> NotReady
[All LB services are synced - time taken for this might be long]
2. Service1's LB which only has an endpoint on Node25 gets Node25 removed from its list of backend
3. Node25 transitions from NotReady -> Ready again, cancelling the scheduled eviction for the endpoint hosted on Node25 for Service1
4. CCM is still processing the updated caused by 1. and clients connecting to the LB of Service1 continues experiencing connectivity issues, even though Node25 now is in a Ready state.
[Eventually - once the CCM enters its second reconciliation loop caused by 3.]
5. The LB for Service1 gets Node25 added to its list of backend again and connectivity is again achieved by clients.

The sync function which is triggered when a node transitions state from Ready <-> NotReady, is currently correct but can be avoided for services which have ExternalTrafficPolicyLocal if the service does not have an endpoint on any of the nodes which are transitioning state between Ready <-> NotReady. This is because such services are not designed to forward traffic to any other node, and the update is thus useless to them. The node which is experiencing a transitioning state is already configured for that LB, and the fact that it transitions state is a moot point for what concerns these services. 

The longer vision I have for this: remove the sync function for transitioning node readiness state from the CCM altogether and instead have all services of type LoadBalancer evaluate the node's readiness state by the utilization of a LB configured health check probe against the [kubelet's read-only port](https://github.com/kubernetes/kubernetes/blob/master/pkg/cluster/ports/ports.go#L33). This would allow transitioning node readiness state to be handled much more dynamically (similar to what has already been implemented for HealthCheckNodePort by kube-proxy) for all services of type LoadBalancer irrespectively of if they define ExternalTrafficPolicyLocal or not....but that will require a enhancement proposal since cloud providers have divergent implementations of how they configure health check probes for LB services.

I am putting this here for completeness sake: this is what the major cloud providers currently do to health check services which are not ExternalTrafficPolicyLocal

GCE: probes [10256](https://github.com/kubernetes/kubernetes/blob/master/pkg/cluster/ports/ports.go#L36)
AWS: if ELB: probes the first NodePort defined on the service spec.
Azure: probes all NodePort defined on the service spec.

All of these can be improved, but an enhancement proposal would be needed to align them all. For now: this PR will help fix some cases.

### What did you expect to happen?

Node readiness changes should not re-configure load balancers associated with services of type ETP=local. 

- Nodes not hosting any endpoints associated with these services do not forward traffic to nodes that do, so re-configuring the LB because said node goes NotReady is useless. 
- Nodes hosting endpoints associated with these services are already health checked using the HC probe configured for the `healthCheckNodePort` and can rely on that much more dynamically without needing to re-configure the LB. 

In the long-term: all load balancers should not be re-configured because of node state changes. That will need an enhancement proposal however (which I am currently drafting) to change service proxies and align cloud provider HCs. 

### How can we reproduce it (as minimally and precisely as possible)?

"as minimally and precisely as possible" not sure if this hits the definition, but: we need a big cluster with a lot of entropy (for example by performing an upgrade and restarting all nodes one-by-one) - this should end up re-configuring every single LB N*M (where N is the amount of nodes and M is the amount of state transitions per node). 

### Anything else we need to know?

Presumably, this has never been a big issue for the externally exposed Kube API service, since that runs on control plane nodes...and I assume those nodes are labeled with https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/well_known_labels.go#L62-L67 (I am pretty sure that's the case for OpenShift). So "Kubernetes distros" avoid this problem using that label...users, don't get that luxury however.  

### Kubernetes version

All versions.

### Cloud provider

All cloud providers. 

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
#### What type of PR is this?

/kind bug 

#### What this PR does / why we need it:

Backport of #109706 and #111691 to 1.24 

#### Which issue(s) this PR fixes:

Fixes #111539, partially by reducing the amount of LB sync calls performed for ETP=local services for changing node readiness state. 

#### Special notes for your reviewer:

This was not an automated cherry-pick because of conflicts.

#### Does this PR introduce a user-facing change?

```release-note
Reduce the number of cloud API calls and service downtime caused by excessive re-configurations of cluster LBs with externalTrafficPolicy=Local when node readiness changes (https://github.com/kubernetes/kubernetes/issues/111539). The service controller (in cloud-controller-manager) will avoid resyncing nodes which are transitioning between `Ready` / `NotReady` (only for for ETP=Local Services). The LBs used for these services will solely rely on the health check probe defined by the `healthCheckNodePort` to determine if a particular node is to be used for traffic load balancing. 

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig network
/sig cloud-provider
/assign @thockin

### CODE REVIEW

**Comment by alexanderConstantinescu** [comment]
Update: I cherry-picked and added https://github.com/kubernetes/kubernetes/pull/111691. Also updating the description with this.

**Comment by alexanderConstantinescu** [comment]
So, we just discussed this during the sig-net meeting and agreed that detailing "the benefits of getting this merged on 1.24" vs. "risks with merging this on 1.24", might be in order. 

**Risks with merging this on 1.24**:

- We stop synchronizing service load balancers which have the attribute: `ExternalTrafficPolicy: Local`, when any node they point to, transition to `NotReady`. This means that any such node continues to remain in the load balancer backend pool and will continue to be a valid target for load balancing - at least for a short while. 

**Benefits of merging this on 1.24**

- We fix an important bug for customers who run clusters with many load balancers, run in to _often_. We fix this on all clouds. This currently leads to ingress downtime when any cluster node experiences transient and spurious events which they very quickly recover from. Ex: a node transitioning from `Ready` -> `NotReady` -> `Ready` within the course of a couple of minutes can cause **hours** wide complete ingress downtime for the service (this has happened).
- We reduce the amount of cloud API calls consumed by the KCCM on said clusters. Often which lead to rate limiting by the cloud provider and which also exherbitates the problem mentioned above. This might also cause other problems for the user, since other API calls performed might be rate limited as a consequence of the KCCM doing this so often.  
- I would even argue that the risk mentioned above, is a non-risk. If the node experiences and enters a _terminal_ error state, then kube-proxy on that node will probably also be impacted, thus failing the health check probe configured for the load balancer and thus blocking traffic from being sent to the node in question. If kube-proxy is not impacted, then who cares? That means the service proxy is still fine and can route traffic for that service to that endpoint...whatever is impacting the Kubelet (which is what sets `NotReady` on the node object) is likely a orthogonal problem to networking, at the very least for what concerns the service proxy and its power to route traffic to the right place.

Tagging @thockin, so that he can weigh in on this with his opinions.

For what concerns my opinion: I think the benefits outweigh the concerns and we should even fix this on all currently supported versions of Kubernetes.

**Comment by aojea** [comment]
> For what concerns my opinion: I think the benefits outweigh the concerns and we should even fix this on all currently supported versions of Kubernetes.

I'm sorry, but I'm not in favor of backporting this because I think that the risk of regressions in this area is high:
- there are changes on the behavior of the feature
- the bug was always there and is only present at large scale, and the patches weren't tested at scale, so we can't really know after a few releases if they are going to solve the problem and not create new ones
- there is an effort to try to move away from the intree cloud providers, with little success though https://github.com/kubernetes/enhancements/issues/2395)

It is just my opinion

**Comment by thockin** [comment]
I agree with @aojea - This is too much for me to argue for, and if I were the branch manager I would say no.

**Pull request closed without merging**
