### PR TITLE
Fix finding pid of a process

### PR DESCRIPTION
**Pull request by yujuhong**
/cc @dchen1107 @vishh

### CODE REVIEW

**Comment by vishh** [comment]
LGTM

**Comment by yujuhong** [comment]
@vishh, perhaps we should add a test checking whether daemons are running in the right cgroup (or is there one already in the node suite)?

**Comment by vishh** [comment]
There is one in the node e2e suite. but we don't have a PR builder. An
explicit test thats run on every PR will definitely help.

**Comment by dchen1107** [comment]
LGTM

**Comment by yujuhong** [comment]
@k8s-bot test this #21463

**Comment by yujuhong** [comment]
@k8s-bot test this issue: #21463

**Pull request merged**
