### PR TITLE
Replace boot2docker references with docker-machine

### PR DESCRIPTION
**Pull request by cmluciano**
Rebase of #17514

### CODE REVIEW

**Comment by cmluciano** [comment]
@karlkfi I rebased and resubmitted this PR. Let me know if it looks good now. Also I should be under the corporate IBM-CLA

**Comment by karlkfi** [comment]
@cmluciano Does the git user.email on your commit have the IBM suffix whitelisted by the CLA?
I don't have access to the CLA whitelist to check. If it doesn't, you can change it and a force push. That will make the bot happy.

**Comment by cmluciano** [comment]
I signed it!

**Comment by cmluciano** [comment]
*sigh* I ran the hack/docs scripts, force-pushed to my branch, and this autoclosed again.

**Comment by duglin** [comment]
@cmluciano you sure you pushed correctly? It shows zero commits associated with this PR.

**Comment by cmluciano** [comment]
Yep, it had the commit and then I ran the doc/hack script to fix the travis build. After a force push, for the amended commit, it autoclosed.

**Pull request closed without merging**
