### PR TITLE
Arrange for elasticsearch to shutdown cleanly

### PR DESCRIPTION
**Pull request by anguslees**
Kubernetes initiates "graceful shutdown" by sending SIGTERM to pid 1, which
is exactly what elasticsearch is expecting (good!)

The way the existing startup scripts worked however, this signal arrived at
the shell wrapper, not elasticsearch, and the shell wrapper exited,
killing the container immediately (bad!)

Before this change:
```
    1 ?        Ss     0:00 /bin/sh -c /run.sh
    6 ?        S      0:00 /bin/bash /run.sh
   13 ?        S      0:00  \_ /bin/su -c /elasticsearch/bin/elasticsearch elasticsearch
   14 ?        Ss     0:00      \_ sh -c /elasticsearch/bin/elasticsearch
   15 ?        Sl    19:18          \_ /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java ... org.elasticsearch.bootstrap.Elasticsearch start
```
After this change:
```
    1 ?        Ssl    0:29 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java ... org.elasticsearch.bootstrap.Elasticsearch start
```

### CODE REVIEW

**Comment by anguslees** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by crassirostris** [comment]
@anguslees Please bump the version of the image to `v2.4.1-2` in the Makefile

Also you might want to use the new image in the `es-controller.yaml` file right away.

**Comment by crassirostris** [comment]
@anguslees Thanks a lot for you PR

Unfortunately, there's been a refactoring of k8s code and code for the binary which comes with the es image has been broken, I cannot build the container :(

Could you please fix it? It's one line change in `elasticsearch_logging_discovery.go`:

```
--- a/cluster/addons/fluentd-elasticsearch/es-image/elasticsearch_logging_discovery.go
+++ b/cluster/addons/fluentd-elasticsearch/es-image/elasticsearch_logging_discovery.go
@@ -53,7 +53,7 @@ func main() {
        if err != nil {
                glog.Fatalf("Failed to make client: %v", err)
        }
-       namespace := metav1.NamespaceSystem
+       namespace := meta_v1.NamespaceSystem
        envNamespace := os.Getenv("NAMESPACE")
        if envNamespace != "" {
                if _, err := client.Core().Namespaces().Get(envNamespace, meta_v1.GetOptions{}); err != nil {
```

Then I will be able to build the image and merge the PR

**Comment by anguslees** [comment]
I fixed it in the other direction (`meta_v1` -> `metav1`) in order to be consistent with the rest of the k8s codebase, as expressed through the commit that broke this example.

**Comment by crassirostris** [comment]
@anguslees OK, that's even better, thank you!

**Comment by crassirostris** [comment]
Built, pushed and tested the image, everything's fine, thanks again for your contribution!

/lgtm

**Pull request merged**
