### PR TITLE
Revert to version 70b2c90b of the vendored package github.com/Azure/go-ansiterm

### LINKED ISSUE #38073: ci-kubernetes-cross-build: broken test run
Failed: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-cross-build/103/

Run so broken it didn't make JUnit output!

### PR DESCRIPTION
**Pull request by luxas**
Fixes the problem described in https://github.com/kubernetes/kubernetes/pull/37783#issuecomment-266245476

Fixes #38073

@ixdy @gmarek @colemickens @brendandburns

### CODE REVIEW

**Comment by luxas** [comment]
@k8s-bot build this

**Comment by luxas** [comment]
Seems like this fixes the issue, but @ixdy still have to push the debian-iptables image for `s390x` (which I thought had been done already)

**Comment by gmarek** [comment]
@luxas - verify-bazel is failing.

**Comment by luxas** [comment]
@gmarek Should be fixed now.

@gmarek Any chance you could help out here and build and push the `debian-iptables` image?
I think something like 
```
ARCH=s390x make -C build-tools/debian-iptables push
```
would do it, when you've applied the change I have in this PR.

When that's done, this PR can be merged and everything should be up on its feet again

**Comment by luxas** [comment]
@k8s-bot cvm gce e2e test this

**Comment by luxas** [comment]
@k8s-bot build this

**Comment by jbeda** [comment]
Let's wait for the cross build and then I'll LGTM.  This seems like a targeted revert.  Other options are to revert all of the dependency updates from #37783 or to try and roll `github.com/docker/docker/pkg/term/windows` forward.  This seems the lowest risk option.

**Comment by luxas** [comment]
@jbeda Yes, @colemickens said the `go-ansiterm` version bump wasn't related to the other things in the PR, so I reverted only `go-ansiterm` changes.

Still, the `s390x` version of `debian-iptables` has to be pushed unfortunately, which I thought had been done before https://github.com/kubernetes/kubernetes/pull/36050 merged.

That's what @mml, @ixdy, @gmarek or some other Googler can help with

**Comment by mml** [comment]
CRI GCE e2e is failing

**Comment by luxas** [comment]
Yes, but that's a flake, not related

**Comment by mml** [comment]
```console
% make -C build-tools/debian-iptables ARCH=s390x push
make: Entering directory `/usr/local/google/home/mml/gocode2/src/k8s.io/kubernetes/build-tools/debian-iptables'
cp ./* /tmp/tmp.1hfPvBMfW0
cd /tmp/tmp.1hfPvBMfW0 && sed -i "s|BASEIMAGE|s390x/debian:jessie|g" Dockerfile
cd /tmp/tmp.1hfPvBMfW0 && sed -i "s|ARCH|s390x|g" Dockerfile
# When cross-building, only the placeholder "CROSS_BUILD_" should be removed
# Register /usr/bin/qemu-ARCH-static as the handler for ARM binaries in the kernel
docker run --rm --privileged multiarch/qemu-user-static:register --reset
curl -sSL https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/x86_64_qemu-s390x-static.tar.gz | tar -xz -C /tmp/tmp.1hfPvBMfW0
cd /tmp/tmp.1hfPvBMfW0 && sed -i "s/CROSS_BUILD_//g" Dockerfile
docker build -t "gcr.io/google_containers"/debian-iptables-s390x:v4 /tmp/tmp.1hfPvBMfW0
Sending build context to Docker daemon 2.636 MB
Step 1 : FROM s390x/debian:jessie
 ---> 6a5773a6fe66
Step 2 : COPY qemu-s390x-static /usr/bin/
 ---> Using cache
 ---> 762566a7bc79
Step 3 : RUN DEBIAN_FRONTEND=noninteractive apt-get update     && DEBIAN_FRONTEND=noninteractive apt-get install -y iptables     && DEBIAN_FRONTEND=noninteractive apt-get install -y ebtables     && DEBIAN_FRONTEND=noninteractive apt-get install -y conntrack     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> bead558c7fa1
Successfully built bead558c7fa1
gcloud docker -- push "gcr.io/google_containers"/debian-iptables-s390x:v4
The push refers to a repository [gcr.io/google_containers/debian-iptables-s390x]
b0a1e84e76f7: Pushed 
523a29c5a5c3: Pushed 
7d0cb45fb410: Pushed 
v4: digest: sha256:7d4010a5ed771eeaa6c2cb0fe576e3e75179bd5538ec2d33ea8987297ae893c5 size: 949
make: Leaving directory `/usr/local/google/home/mml/gocode2/src/k8s.io/kubernetes/build-tools/debian-iptables'
```

**Comment by luxas** [comment]
@k8s-bot build this

**Comment by luxas** [comment]
Applying lgtm given earlier

**Pull request merged**
