### PR TITLE
Release 0.21.4

### PR DESCRIPTION
**Pull request by brendandburns**
@zmerlynn @mbforbes 

I had to monkey-patch this thing for some reason as the scripts didn't work as expected.

Please be extra special careful when checking.

### CODE REVIEW

**Comment by zmerlynn** [comment]
Which part did you monkey patch?

**Comment by zmerlynn** [comment]
(I assume e1795e008590d5d235080c59b505400b1be62356 was hand rolled given the name?)

**Comment by brendandburns** [comment]
All of the above.

The script originally stopped b/c the presubmit checks failed.

Then it stopped b/c I had uncommitted changes.

Then it stopped with:

```
On branch release-0.21
Your branch is ahead of 'upstream/release-0.21' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
```

but didn't make the versioning changes.

So I just hand-rolled it.

**Comment by zmerlynn** [comment]
Yeah, the swagger updates appear to be broken on the `release-0.21` branch right now, sigh, and I'm not sure which `release-1.0` PR will fix it. There may actually be a right one - I'll see if I can run `mark_new_version` on `release-1.0` right now, actually.

**Comment by zmerlynn** [comment]
You need to push the tag still.

**Comment by brendandburns** [comment]
agree, was waiting for the ack before I pushed the tag.  It's now pushed.

**Comment by zmerlynn** [comment]
Just being pedantic - wanted to make sure tag was at 3d43944bee17e7147c2ae59aa97a63fb5111d6b0. LGTM.

**Comment by zmerlynn** [comment]
Hrm, looks like `release-1.0` has the same issue. Filing a bug.

**Comment by zmerlynn** [comment]
Filed #11432

**Pull request merged**
