### PR TITLE
Allow reading ECDSA key files containing parameter blocks

### LINKED ISSUE #40589: controller-manager fails to read ECDSA private key
**Kubernetes version**

Serverversion 1.5.2 (running Hyperkube v1.5.2_coreos.1 (https://quay.io/repository/coreos/hyperkube))

**Environment**:
- Bare-Metal
- Coreos 1235.6.0 (Kernel 4.7.3-coreos-r2)

**What happened**:
kube-controller-manager with ecdsa key fails to start 
`
F0127 09:59:04.041033       1 controllermanager.go:181] error running controllers: Error reading key for service account token controller: error reading private key file /etc/kubernetes/ssl/alien1.rz.tu-bs.de.key.pem: data does not contain a valid RSA or ECDSA private key`

The key is valid (and works with e.g. the api-server)

```
cat /etc/ssl/alien.key.pem

-----BEGIN EC PARAMETERS-----
Bgg[...]
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQ[...]
-----END EC PRIVATE KEY-----
```

Command used to create the key:

`openssl ecparam -out /etc/pki/alien_certs/private/$hostname -name prime256v1 -genkey`

```
cat /etc/kubernetes/manifests/kube-controller-manager.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-controller-manager
    image: quay.io/coreos/hyperkube:v1.5.2_coreos.1
    command:
    - /hyperkube
    - controller-manager
    - --master=http://127.0.0.1:8080
    - --leader-elect=true
    - --service-account-private-key-file=/etc/kubernetes/ssl/alien.key.pem 
    - --root-ca-file=/etc/kubernetes/ssl/alien-chain.cert.pem
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 1
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/ssl/alien
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
```

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #40589

### CODE REVIEW

**Review by luxas — COMMENTED** [review]
Shouldn't `pkg/util/cert` have a similar change?

I thought that place was the source of truth for these kinds of helper functions?

**Comment by thockin** [comment]
I am not a great assignee for this - who should it be?

**Comment by cblecker** [comment]
It looks like https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/util/cert/pem.go#L58-L76 may already do a similar thing to this.

**Comment by mikedanese** [comment]
@k8s-bot kops aws e2e test this

**Comment by luxas** [comment]
I agree with @cblecker and think that this code should exist in `pkg/util/cert`, not in `pkg/serviceaccount`.
I'm aware the purpose of this PR wasn't/isn't to cleanup that, but any chance you could do it now or as a follow-up while you're at it?

**Comment by liggitt** [comment]
this package predated the util/cert package. moved the function for reading public keys to the cert package, moved tests, and updated references to use the client-go package. PTAL

**Comment by mikedanese** [comment]
> this package predated the util/cert package. moved the function for reading public keys to the cert package, moved tests, and updated references to use the client-go package. PTAL

did this get reverted?

/lgtm-cancel

**Comment by liggitt** [comment]
> did this get reverted?

yeah, sorry... thought that move led to an import cycle, but was mistaken. just pushed the fixed up version

**Comment by luxas** [comment]
@k8s-bot kubemark e2e test this
@k8s-bot gce etcd3 e2e test this
@k8s-bot gci gce e2e test this
@k8s-bot cvm gce e2e test this

**Comment by liggitt** [comment]
failure is legitimate:

> F0201 13:41:21.719814       5 controllermanager.go:167] error running controllers: error reading key for service account token controller: error reading private key file /etc/srv/kubernetes/server.key: no RSA or ECDSA private key PEM block found

apparently the cert util package doesn't recognize all the private key PEM blocks the service account one did

**Comment by liggitt** [comment]
> apparently the cert util package doesn't recognize all the private key PEM blocks the service account one did

I'm going to do the original minimal fix for now, and will open a follow up issue to collapse onto the util/cert package once we investigate why it is not as accepting of private key files

**Comment by liggitt** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
