### PR TITLE
WIP: Add support to quota requests or limits (via AccountingPolicy)

### PR DESCRIPTION
**Pull request by derekwaynecarr**
For background, see: https://github.com/kubernetes/kubernetes/pull/19761

The existing `ResourceQuota` document constrains the total amount of compute resource requests. This is useful when cluster-managers are interested in controlling explicit resource guarantees often associated with higher SLA. The end-user creating the pod is expected to have intimate knowledge on their minimum required resource as well as their potential limits.

There are many environments where cluster-managers do not extend this level of trust to their end-user because user's often request too much resource, and they have trouble reasoning between what they hope to have available for their application versus what their application actually needs. In these environments, cluster-managers often just expose a single value (the limit) to the end-user, and internally, they set the request as a factor of the limit to control for over-commit or based on known-historical trends. In this environment, the cluster-manager is interested in exposing a quota to their end-users that maps to their desired limit instead of their request.

To facilitate both operational environments, a `ResourceQuota` can have a `ResourceAccountingPolicy`. If set to `Requests`, the quota document will charge for quota usage based on the `resources.requests` on a `Kind`. If set to `Limits`, the quota document will charge for quota usage based on `resources.limits` on a `Kind`. If not specified, it will default to `Requests` to preserve backward-compatibility. If set to `Limits`, a `Kind` must specify an upper limit for each resource tracked by quota. The `ResourceAccountingPolicy` is only pertinent to resources that support bursting semantics.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
If this can be reviewed shortly after the kube 1.2 branch is cut, it would be appreciated.

It allows quota to track requests or limits.  For many PaaS style deployments, we anticipate operators tracking limits and explicitly setting request based on desired over-commit ratio set by a cluster-manager.  As a result, we want to show users their total compute resource limits instead of the total compute resource requests in those environments.

/cc @bgrant0607 @smarterclayton @davidopp @danmcp

FYI:
@kubernetes/rh-cluster-infra 
@kubernetes/rh-ux

**Comment by thockin** [comment]
I'm probably the wrong assignee - suggestions?

**Comment by derekwaynecarr** [comment]
@thockin - I would suggest @erictune

**Comment by derekwaynecarr** [comment]
I am updating the implementation to align with https://github.com/kubernetes/kubernetes/pull/19761#discussion_r50492537

**Comment by derekwaynecarr** [comment]
Marking WIP pending outcome on design discussion.

**Comment by derekwaynecarr** [comment]
Closing this PR based on in-person discussion to favor the approach here:
https://github.com/kubernetes/kubernetes/issues/20175

**Pull request closed without merging**
