### PR TITLE
kubelet: remove unused parameter from runtime's SyncPod()

### PR DESCRIPTION
**Pull request by dcbw**
```release-note
NONE
```

### CODE REVIEW

**Comment by dcbw** [comment]
Commit pulled out of https://github.com/kubernetes/kubernetes/pull/64224 for easier review while I rework that commit.

**Comment by colemickens** [comment]
Hi folks. What's the status of this PR? If it's critical, we need to get it labeled as such or it will be evicted from the release soon as code freeze begins. Thanks!

**Comment by dims** [comment]
@derekwaynecarr @dchen1107 do we need to get this into v1.11

@kubernetes/sig-node-pr-reviews please help

**Comment by yujuhong** [comment]
It's a cleanup PR and since we've entered code freeze, I don't think it's necessary to get the PR in. @dcbw do you have a critical PR depending on this?

**Comment by dcbw** [comment]
@yujuhong no, I have no 1.11 critical PR waiting for this one.  OK to postpone if you want to.

**Comment by jberkus** [comment]
Removing from milestone per remark above.

Once you get it ready, 1.12 milestone is now open

**Comment by yujuhong** [comment]
Didn't notice the PR was still here...

**Pull request merged**
