### PR TITLE
re-make print flags composeable for sophisticated callers

### PR DESCRIPTION
**Pull request by deads2k**
Composers need to override all the pieces of logic independently.  It also simplifies the determination logic.

@kubernetes/sig-cli-maintainers 
/assign @juanvallejo 

```release-note
NONE
```

### CODE REVIEW

**Comment by juanvallejo** [comment]
@liggitt yes, will update https://github.com/kubernetes/kubernetes/pull/65979 with these changes

**Comment by deads2k** [comment]
> @fejta-bot: Cannot trigger testing until a trusted user reviews the PR and leaves an /ok-to-test message.

@fejta bots gone bad? I think I should be trusted.

**Comment by ixdy** [comment]
@deads2k https://github.com/kubernetes/test-infra/issues/8628

**Pull request merged**
