### PR TITLE
Add a default storage class for Azure Disk

### PR DESCRIPTION
**Pull request by brendandburns**
Part of https://github.com/kubernetes/kubernetes/issues/40071

@jsafrane @colemickens @codablock @rootfs

### CODE REVIEW

**Comment by jsafrane** [comment]
lgtm from storage point of view, thanks a lot.

**Comment by brendandburns** [comment]
@k8s-bot kops aws e2e test this

**Comment by rootfs** [comment]
lgtm

**Comment by brendandburns** [comment]
(self-lgtm on lgtm from rootfs)

**Pull request merged**
