### PR TITLE
Bump cadvisor version to v0.47.3

### PR DESCRIPTION
**Pull request by iholder101**
#### What type of PR is this?
let's move to a newer cadvisor version.

It also contains a [bugfix](https://github.com/google/cadvisor/pull/3293) that [swap implementation](https://github.com/kubernetes/kubernetes/pull/118764) is dependent on in order to [graduate swap to Beta1](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/2400-node-swap/README.md#beta-1).

/kind bug
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Bump cadvisor version to v0.47.3
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by harche — APPROVED** [review]

**Comment by harche** [comment]
/cc @bobbypage 

```
W0711 14:12:17.467]   W0711 14:12:10.591908    1826 image_list.go:204] Failed to pull gcr.io/cadvisor/cadvisor:v0.47.3 as user "root", retrying in 1s (3 of 5): rpc error: code = NotFound desc = failed to pull and unpack image "gcr.io/cadvisor/cadvisor:v0.47.3": failed to resolve reference "gcr.io/cadvisor/cadvisor:v0.47.3": gcr.io/cadvisor/cadvisor:v0.47.3: not found
```

**Comment by iholder101** [comment]
Unit test passes locally

/test pull-kubernetes-unit

**Review by mrunalp — APPROVED** [review]

**Comment by harche** [comment]
cc @kubernetes/dep-approvers

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

@dims can you approve?

**Pull request merged**
