### PR TITLE
logs: add AddGoFlags

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This makes it possible to use logging command line flags with a flag.FlagSet, without having to copy values from a pflag.FlagSet.

#### Does this PR introduce a user-facing change?
```release-note
k8s.io/component-base/logs now also supports adding command line flags to a flag.FlagSet.
```

### CODE REVIEW

**Comment by pohly** [comment]
/assign @thockin

For approval.

Needed for https://github.com/kubernetes/kubernetes/pull/114843#pullrequestreview-1267621654 and https://github.com/kubernetes-csi/node-driver-registrar/pull/259.

**Comment by thockin** [comment]
Is there a canonical example of what a best-practice, no-baggage, max-leverage, no-BS component's `main.go` should look like?  If I were writing a NEW component, what code would I copy-and-extend?

There are so many public functions here now, I can't keep track of who calls what, and what I am supposed to do - what is the north star (is that hemispherist?) ?

**Comment by pohly** [comment]
The canonical example is https://github.com/kubernetes/component-base/blob/master/logs/example/cmd/logger.go. It uses cobra + pflags.

There's no example for Go with just the stdlib (yet) - I could add one.

**Comment by thockin** [comment]
I'd love to see an example that shows canonical use with a small set of options, not just logging but all of the "facilities" available to a "kube component".

That example helps some - still seems like some boilerplate that could be trimmed, but I only looked superficially :)

/approve

**Pull request merged**
