### PR TITLE
support UserAgent as flowschema subject

### PR DESCRIPTION
**Pull request by borgerli**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
This PR addresses following cases.

In a large cluster, users use the certificates of system components(Although this is bad practice, some user does do this for simpliciy) in a component running as daemonset. This component runs on all nodes and listed some resource from APIServers every 10 seconds. theserequests from this component will put very high load on APIServers, and impact other system components using same certificates.
With this PR, we can add a flowshema with subject of the component user-agent, and thus limit its requests separately with system components.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
APF FlowSchema supports UserAgent in regular expression as Subject.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
need to update [Usage](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/)
```

### CODE REVIEW

**Comment by sftim** [comment]
When we document this, we need to document the information security concerns about rate limiting based on a string that clients can control.

Is there any risk of end users / malicious parties being able to trigger extra memory use by creating new flow buckets?

**Comment by sftim** [comment]
@borgerli I recommend that you file an issue to track the improvement you'd like to make here

**Comment by MikeSpreitzer** [comment]
We have a general rule in the apiserver of not letting the UserAgent string affect the processing, because it is easy to abuse.  The opening comment indicates the better path, not sharing identities too widely.

**Comment by MikeSpreitzer** [comment]
_If_ we were to do this, and it is a real "if", then I think it is most defensible with the understanding that testing the UserAgent is only done in conjunction with testing the user.  That way, every bit of capacity offered to a UserAgent would clearly be part of the capacity offered to a user.  Thus, there would be no more trust given to UserAgent than is given to the particular user at hand.

This conjunction could be done directly in the FlowSchema syntax, or in the validation.  For an example of the former: the types UserSubject and ServiceAccountSubject could be extended with an optional UserAgent field.

**Comment by MikeSpreitzer** [comment]
But my first question remains: given that the use case cited at the beginning is admittedly bad practice, isn't the better option to fix that bad practice?

**Comment by wojtek-t** [comment]
Given no response, closing this one.

If needed, please reopen and respond to @MikeSpreitzer concerns above.

**Pull request closed without merging**
