### PR TITLE
Bump up MacOS RAM requirement to 8GB

### PR DESCRIPTION
**Pull request by zerodayz**
As discussed in https://github.com/kubernetes/kubernetes/issues/11852#issuecomment-387868165

We need at least 8 GB RAM assigned to Docker for Mac. Otherwise
the build will likely fail.
Bumping this requirement saves time people who assigns 4.5 GB
RAM and fails.

Signed-off-by: Robin Cernin <cerninr@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by zerodayz** [comment]
This is build doc change in specs for Mac OS. It doesn't make sense to keep 4.5 GB RAM when the build fails 100% of time with that amount.  It was already discussed in https://github.com/kubernetes/kubernetes/issues/11852#issuecomment-387868165

But I don't see any change ever since and the docs are still pointing to value that doesn't work.

**Comment by spiffxp** [comment]
/test pull-kubernetes-e2e-gce-ubuntu-containerd
/assign @cblecker
for the /approve

**Pull request merged**
