### PR TITLE
Add the length detection of the "predicateFuncs" for findNodesThatFit function of generic_scheduler.go

### PR DESCRIPTION
**Pull request by ping035627**
The PR add the length detection of the "predicateFuncs" for "findNodesThatFit" function of generic_scheduler.go. 
In “findNodesThatFit” function, if the length of the "predicateFuncs" parameter is 0, it can set filtered equals nodes.Items, and needn't to traverse the nodes.Items.

### CODE REVIEW

**Comment by davidopp** [comment]
ok to test

**Comment by davidopp** [comment]
LGTM

**Comment by davidopp** [comment]
Looks like the failure is that you need to run hack/update-all.sh

**Comment by bprashanth** [comment]
```
  1: ./hack/../hack/verify-api-reference-docs.sh:34 main(...)
Exiting with status 1
FAILED   ./hack/../hack/verify-api-reference-docs.sh	0s
Verifying ./hack/../hack/verify-boilerplate.sh
SUCCESS  ./hack/../hack/verify-boilerplate.sh	0s
```
specifically

**Comment by wojtek-t** [comment]
@ping035627 - can you please fix failures mentioned above?

**Comment by ping035627** [comment]
@wojtek-t no, sorry.

**Comment by wojtek-t** [comment]
@ping035627 - then we can't merge this PR.

**Comment by ping035627** [comment]
I have update the file, please test again, thanks.

**Comment by ping035627** [comment]
@wojtek-t
Jenkins unit/integration — No test results found.
The PR just add the length detection of the "predicateFuncs". The change should' t cause the result. What can I do? help, thanks!

Verifying ./hack/../hack/verify-flags-underscore.py
SUCCESS  ./hack/../hack/verify-flags-underscore.py	58s
Build step 'Execute shell' marked build as failure
Recording test results
ERROR: Step 鈥楶ublish JUnit test result report鈥� failed: No test report files were found. Configuration error?
[PostBuildScript] - Execution post build scripts.
[kubernetes-pull-test-unit-integration@2] $ /bin/bash -xe /tmp/hudson1472969172450311051.sh
+ [[ -x ./hack/jenkins/upload-to-gcs.sh ]]
+ ./hack/jenkins/upload-to-gcs.sh
Called without JENKINS_BUILD_STARTED or JENKINS_BUILD_FINISHED set.
Assuming a legacy invocation.
Run finished at Tue May 17 20:25:26 PDT 2016
Uploading to gs://kubernetes-jenkins/pr-logs/pull/25606/kubernetes-pull-test-unit-integration/26441 (attempt 1)
Uploading build result: [UNSET]
Marking build 26441 as the latest completed build



*** View logs and artifacts at https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25606/kubernetes-pull-test-unit-integration/26441 ***

**Comment by ping035627** [comment]
@k8s-bot test this issue:＃25883

**Comment by ping035627** [comment]
@k8s-bot  test this issue: #25883

**Pull request closed without merging**
