### PR TITLE
StatefulsetAutoDeletePVC default value documentation update

### PR DESCRIPTION
**Pull request by kundan2707**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
updated default value of StatefulsetAutoDeletePVC as it got changed in 1.27 as enabled
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kundan2707** [comment]
Upstream changes related to 
https://github.com/kubernetes/website/issues/43976

**Comment by dims** [comment]
@kundan2707 please rebase!

**Comment by kundan2707** [comment]
@dims rebased brach.

**Comment by liggitt** [comment]
check the verify tests to see what needs to be regenerated from the API docs

**Comment by liggitt** [comment]
doc change looks fine, needs rebase

**Pull request closed without merging**
