### PR TITLE
Automated cherry pick of #85527: Revert "kube-proxy: check KUBE-MARK-DROP"

### PR DESCRIPTION
**Pull request by aojea**
Cherry pick of #85527 on release-1.17.

#85527: Revert "kube-proxy: check KUBE-MARK-DROP"

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @danwinship 
/cc @justaugustus 

/hold

until master PR merges

**Comment by aojea** [comment]
/hold cancel
It's merged in master
/test pull-kubernetes-integration
/assign @justaugustus

**Comment by justaugustus** [comment]
Release Manager approval:
/lgtm
/approve

**Pull request merged**
