### PR TITLE
client-go/tools/portforward: Fix dropped error in tests

### PR DESCRIPTION
**Pull request by alrs**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Fixes a swallowed error in the `client-go` tests.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by hpandeycodeit** [comment]
@alrs The PR description needs to be changed a little. Can you add "/kind bug" under the "What type of PR is this?" section and remove other kinds.

**Review by hpandeycodeit — APPROVED** [review]

**Comment by roycaihw** [comment]
Thanks for the PR! The fix was included in https://github.com/kubernetes/kubernetes/commit/c8c055b3163dd2661b3f9dd1b0ffb718a61aba24

/close

**Pull request closed without merging**
