### PR TITLE
Fix pod-index label name for StatefulSet Pods

### PR DESCRIPTION
**Pull request by mas9612**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

https://github.com/kubernetes/kubernetes/pull/119232 introduces pod-index label for StatefulSet Pods.

However, differences occurred between the code and the changelog.
This PR fixes that.

- Code: `apps.kubernetes.io/pod-index`
https://github.com/kubernetes/kubernetes/blob/eb6840928df59bf8203b1eda839ccd3da68fb37d/staging/src/k8s.io/api/apps/v1/types.go#L32
- Changelog: `statefulset.kubernetes.io/pod-index`

#### Which issue(s) this PR fixes:

N/A

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mas9612** [comment]
Thank you for the review!
I happened to notice it while at work earlier and if it is no longer needed, please close it without merging.

**Comment by mimowo** [comment]
I'm not 100% sure about the policy here, so let me check with release managers
/cc @kubernetes/release-managers

**Comment by xmudrii** [comment]
@mimowo Updating changelogs is generally considered fine at least for the supported releases (and we can count 1.28 as supported in this context). But to complete the process, you would also need to cherry-pick this change to the `release-1.28` branch. That said, if you folks want to proceed with this PR, it should be fine.

**Comment by soltysh** [comment]
I'm personally :+1: for updating this. It might not seem like a whole lot, but for folks actually going through changelogs this might be a time saver. I'm not sure about the mechanics of this PR, especially about the feasibility of a cherry-pick, but I'll let the release managers to deal with that. 

With my sig-apps hat on - I approve :smile:

**Comment by mimowo** [comment]
+1
/lgtm
/test pull-kubernetes-e2e-kind-ipv6

**Review by xmudrii — APPROVED** [review]
Thank you for the fix @mas9612, and for the feedback @soltysh @mimowo!
/lgtm
/approve

**Comment by mimowo** [comment]
@mas9612 please prepare the cherry-pick PR for 1.28

**Comment by mas9612** [comment]
Thank you!
I created cherry-pick PR https://github.com/kubernetes/kubernetes/pull/127674

**Pull request merged**
