### PR TITLE
Automated cherry pick of #15395

### PR DESCRIPTION
**Pull request by bprashanth**
Cherry pick of #15395 on release-1.1.

### CODE REVIEW

**Comment by bprashanth** [comment]
https://github.com/kubernetes/kubernetes/issues/17376

**Comment by bprashanth** [comment]
@ArtfulCoder can you reivew? this is just a cherry pick

**Comment by bprashanth** [comment]
@k8s-bot test this please

**Comment by thockin** [comment]
LGTM

**Pull request merged**
