### PR TITLE
kubelet: check for illegal container state transition

### PR DESCRIPTION
**Pull request by sjenning**
supersedes https://github.com/kubernetes/kubernetes/pull/54530

Puts a state transition check in the kubelet status manager to detect and block illegal transitions; namely from terminated to non-terminated.

@smarterclayton @derekwaynecarr @dashpole @joelsmith @frobware

I confirmed that the reproducer in #54499 does not work with this check in place. The erroneous kubelet status update is rejected:

```
status_manager.go:301] Status update on pod default/test aborted: terminated container test-container attempted illegal transition to non-terminated state
```

After fix https://github.com/kubernetes/kubernetes/pull/54593, I do not see the message with the above mentioned reproducer.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
is there any benefit to doing the same check on the other side of the channel?

doing it here is definitely good.

**Comment by sjenning** [comment]
> is there any benefit to doing the same check on the other side of the channel?

I don't think so.  The only writer to the channel is `updateStatusInternal`.

**Comment by derekwaynecarr** [comment]
fair enough.

/lgtm
/approve

**Comment by sjenning** [comment]
fyi @dchen1107

**Comment by sjenning** [comment]
@derekwaynecarr improved error message to include pod namespace and name.  please re-lgtm.

**Comment by joelsmith** [comment]
/test kubernetes-node-e2e
Is this breaking the e2e tests? It's failed 3 in a row and other PRs are generally passing this test.

**Comment by joelsmith** [comment]
/test pull-kubernetes-node-e2e
Is this breaking the e2e tests? It's failed 3 in a row and other PRs are generally passing this test.
(sorry for the comment spam, I misspelled the test name last time)

**Comment by sjenning** [comment]
@joelsmith I think it is breaking them. Looking at it.

**Comment by sjenning** [comment]
@joelsmith I've restricted the check to pods with `RestartPolicy` set to `Never`.

**Pull request merged**
