### PR TITLE
Add access control supporat to advanced audit

### PR DESCRIPTION
**Pull request by CaoShuFeng**
This change allows cluster administrator to split advanced audit into multi
files. Different users will be able to have their own audit file.
The use case of this change:
If a user wants to read his own access audit, the cluster adminstrator needs
the three steps:
1. split audit by username into different files in dir /var/log with
   --audit-log-path=/var/log/audit --audit-grouped-by-user=true
2. enable RBAC authorization mode
3. grant permissions to a users to read his own audit
   3.1 create a clusterrole to read jane's audit
        apiVersion: rbac.authorization.k8s.io/v1beta1
        kind: ClusterRole
        metadata:
          name: audit-reader-jane
        rules:
        - nonResourceURLs: ["/logs/audit-user-jane*"]
          verbs: ["get"]
   3.2 bind this cluster role to jane
        apiVersion: rbac.authorization.k8s.io/v1beta1
        kind: ClusterRoleBinding
        metadata:
          name: audit-reader-jane
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: audit-reader-jane
        subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: User
          name: jane
**Release note**:

```
Add access control supporat to advanced audit, use --audit-grouped-by-user=true to split apiserver's audit into different files.
```

### CODE REVIEW

**Comment by ericchiang** [comment]
Instead of adding features to the existing audit logging implementation, can this be rolled into the advanced audit logging work being done for this release? https://github.com/kubernetes/community/pull/145

**Comment by soltysh** [comment]
Completely agree with @ericchiang, we're currently changing how the audit will work, with the rest endpoint you'll be able to divide the audit into appropriate buckets on the receiving end. I don't think any change to the audit is needed for that. @CaoShuFeng if you're interested you can help implementing the advanced audit feature and close this one, wdyt?

**Comment by soltysh** [comment]
@timstclair fyi

**Comment by CaoShuFeng** [comment]
@soltysh 
Get it.

**Comment by soltysh** [comment]
Thanks!

**Comment by CaoShuFeng** [comment]
reopened in:
https://github.com/kubernetes/kubernetes/pull/47721

**Pull request closed without merging**
