### PR TITLE
Uniquify kubemark image builds and use new registry format

### PR DESCRIPTION
**Pull request by shyamjvs**
Solves issues 1 and 3 in https://github.com/kubernetes/kubernetes/issues/59567.

/cc @wojtek-t 

fyi - @thockin @kubernetes/sig-scalability-misc 

```release-note
NONE
```

### CODE REVIEW

**Comment by shyamjvs** [comment]
Hmm.. Didn't know I wasn't in owners of `cluster/images/kubemark`. Will add myself.

**Comment by wojtek-t** [comment]
Awesome - thanks!

/lgtm
/approve no-issue

**Comment by shyamjvs** [comment]
The kubemark presubmit failed because the cluster startup returned error code 141 at the line:

```
KUBEMARK_IMAGE_TAG=$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 6 | head -n 1)
```

Because `set -o pipefail` was causing the above command to fail due to `head` reading the first line and returning immediately, causing the previous pipe to break. Fixed it now by replacing `cat` with `head`.

**Comment by shyamjvs** [comment]
The bazel-test failure seems unrelated.
The kubemark test failure was due to the following command failing in the script:

```
sed -i'' -e "s/{{full_registry}}/${FULL_REGISTRY}/g" "${RESOURCE_DIRECTORY}/hollow-node.yaml"
```

Because $FULL_REGISTRY has a slash character within it, which is confusing `sed`. I fixed it now using apostrophe as the delimiter instead of slash there.

**Comment by shyamjvs** [comment]
Re-applying lgtm after the above fix.

**Pull request merged**
