### PR TITLE
[Federation][Bugfix] Make the dns provider configurable in kubefed init

### PR DESCRIPTION
**Pull request by irfanurrehman**
Fixes: Issue #36690 

The design doc PR relating the whole feature for kubefed is at #34484.

cc @kubernetes/sig-cluster-federation @madhusudancs @nikhiljindal

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36492)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
LGTM. Will add the labels when other commits that this depends on are reviewed and merged.

**Comment by nikhiljindal** [comment]
@k8s-bot  ok to test

**Comment by madhusudancs** [comment]
@irfanurrehman, @nikhiljindal has already LGTM'ed this. Can you please rebase this to be your first PR in your chain? Or you can even get this off the chain as a separate PR since this does not really depend on your previous PRs. This is a bug fix and I think we should get this into 1.5 to enable people not using Google Cloud DNS. The other PRs can go in, in 1.6.

**Comment by madhusudancs** [comment]
@saad-ali Should I file an exception for this. We need this to make this tool work smoothly on non-GCP environments.

**Comment by saad-ali** [comment]
@madhusudancs The [deadline for exceptions](https://github.com/kubernetes/features/blob/master/release-1.5/release-1.5.md) was EOD Tuesday, November 8. All requests for exception were reviewed during the burndown meeting today. For all intents and purposes this PR missed the 1.5 train. If there is an extraordinary reason for this to be part of 1.5, [file an exception](https://github.com/kubernetes/features/blob/master/EXCEPTIONS.md) ASAP and we'll review it at the next burndown meeting, on Friday.

**Comment by irfanurrehman** [comment]
@madhusudancs I have made this PR commits independent of other PRs. Please let me know if I need to do something further. thanks!

**Comment by nikhiljindal** [comment]
LGMT.
@saad-ali This is just a bug fix. We were missing a flag for cloud-dns. This adds that.
I think its fine to add this to 1.5

**Comment by saad-ali** [comment]
> @saad-ali This is just a bug fix. We were missing a flag for cloud-dns. This adds that.

Hmm, the PR description makes it sound like it is a feature:

> This one **implements one of the TODO items** pending in the previous set of kubefed PRs.
> The **design doc** PR for kubefed is at #34484.

If this is really a just a bug fix, could you update the PR description and reference the bug being fixed.

**Comment by madhusudancs** [comment]
@saad-ali 

> Hmm, the PR description makes it sound like it is a feature:

That's true. It is borderline bug fix/feature and that's debatable. The reason why I left it as a TODO was because I thought it wasn't important for an alpha feature of which this is part of. I have changed my thoughts since then. Not having this change causes a lot of inconvenience for non-GCP users and even our testing of this feature on non-GCP providers. I think it is worth merging this in than causing inconvenience to many many users.

@irfanurrehman could you please update the PR title?

**Comment by saad-ali** [comment]
> That's true. It is borderline bug fix/feature and that's debatable. The reason why I left it as a TODO was because I thought it wasn't important for an alpha feature of which this is part of. I have changed my thoughts since then. Not having this change causes a lot of inconvenience for non-GCP users and even our testing of this feature on non-GCP providers. I think it is worth merging this in than causing inconvenience to many many users.

Ok. We should be able to make an exception. Can you also summarize the risk of this PR in destabilizing the existing bits?

**Comment by irfanurrehman** [comment]
updated the title and description!!

**Comment by madhusudancs** [comment]
> Ok. We should be able to make an exception. Can you also summarize the risk of this PR in destabilizing the existing bits?

@saad-ali thanks. Do you want me to email you the details about this as described in the [exception process](https://github.com/kubernetes/features/blob/master/EXCEPTIONS.md)?

Risk is very minimal and super-contained. These changes apply and are specific to a new command line tool we are introducing in federation called `kubefed`. `kubefed` will be in alpha in 1.5. Also, these changes don't affect anything else outside federation/`kubefed`, so this change destabilizing anything else in Kubernetes is close to zero.

@irfanurrehman thanks!

**Comment by saad-ali** [comment]
> @saad-ali thanks. Do you want me to email you the details about this as described in the exception process?

> Risk is very minimal and super-contained. These changes apply and are specific to a new command line tool we are introducing in federation called kubefed. kubefed will be in alpha in 1.5. Also, these changes don't affect anything else outside federation/kubefed, so this change destabilizing anything else in Kubernetes is close to zero.

Ack. Exception approved. Ok for post-code freeze merge.

**Pull request merged**
