### PR TITLE
Initial HoloKubelet proposal

### PR DESCRIPTION
**Pull request by gmarek**
cc @wojtek-t @davidopp @timothysc @dchen1107 @bgrant0607 @lavalamp

### CODE REVIEW

**Comment by wojtek-t** [comment]
We should first decide whether we would like to proceed with HoloKubelet or reuse the real Kubelet - discussion was started in #12530. However, this is a good entry point for this discussion.

**Comment by gmarek** [comment]
Right. This was written beforehand, so I decided to put it up for discussion either way. It should be clear what 'dry-run' Kubelet is and I think that it's good to understand what the other option is.

**Comment by gmarek** [comment]
cc @fgrzadkowski

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/kubernetes/pull/11951 is an example, that reusing the existing Kubelet  with fake interfaces might be a better idea to avoid divergence between them

**Comment by gmarek** [comment]
We decided to proceed with mocking all Kubelets internals and use it for the testing. Closing this PR.

**Pull request closed without merging**
