### PR TITLE
Removed cluster/saltbase/salt/_states/container_bridge.py since it is…

### PR DESCRIPTION
**Pull request by dchen1107**
… useless now.

@thockin @zmerlynn

### CODE REVIEW

**Comment by zmerlynn** [comment]
LGTM

**Comment by zmerlynn** [comment]
@thockin @roberthbailey for rubber stamps

**Comment by thockin** [comment]
LGTM

**Comment by roberthbailey** [comment]
LGTM.

**Comment by zmerlynn** [comment]
Kicking Shippable, though I can't imagine it mattering...

**Comment by zmerlynn** [comment]
Actually, I like to live "dangerously". The pull builder passed, there's no way Shippable matters on this PR. :P

**Pull request merged**
