### PR TITLE
Remove Framework dependency on nodeinfo snapshot

### PR DESCRIPTION
**Pull request by ahg-g**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Removes the dependency of Framework on NodeInfo Snapshot struct, and replace it with SharedLister interface. This will make it easier for CA to integrate with the Framework by allowing it to either use our NodeInfo Snapshot or create their own datastructure that implements SharedLister interface.

Part of #83554

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/priority important-soon
/assign @Huang-Wei

### CODE REVIEW

**Comment by Huang-Wei** [comment]
/lgtm

Thanks @ahg-g , now the interface looks neat!

BTW: I recalled that per our offline discussion, we may need another CacheSharedLister? (for the binding cycle)

**Comment by ahg-g** [comment]
> /lgtm
> 
> Thanks @ahg-g , now the interface looks neat!
> 
> BTW: I recalled that per our offline discussion, we may need another CacheSharedLister? (for the binding cycle)

yes, we will likely need to provide that, we can do it in 1.18 since we don't yet have in-tree plugins that will use it.

**Pull request merged**
