### PR TITLE
AWS: Don't pass empty filters to AWS requests (release-1.14)

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix invalid filter parameter

**Which issue(s) this PR fixes**:

Ref #82923
Ref #22788

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by andrewsykim** [comment]
/assign @d-nishi @mcrute @nckturner

Can one of you verify if this fixes the issue in https://github.com/kubernetes/kubernetes/issues/82923 please?

**Comment by andrewsykim** [comment]
Do we need a similar fix in master?

**Comment by gyuho** [comment]
Shouldn't this be the other way? This is the same issue as https://github.com/kubernetes/kubernetes/pull/22788.

```go
if len(request.Filters) == 0 {
    request.Filters = nil
}
```

**Comment by SataQiu** [comment]
@gyuho Thank you for pointing me that :)
According to #22788,  we can't pass an empty filters list to the AWS API.
I will update this patch.

**Comment by SataQiu** [comment]
> 
> 
> Do we need a similar fix in master?

Thank you for reminding me :smile: 
I have send a similar PR against the master branch. #82956

**Comment by andrewsykim** [comment]
Looks like https://github.com/kubernetes/kubernetes/pull/78498 was the original fix but it never got cherry-picked into v1.14, can we close this?

**Comment by SataQiu** [comment]
All right! Close this because of #78498 
/close

**Pull request closed without merging**
