### PR TITLE
PodSecurity: promote config and feature gate to beta

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Promotes PodSecurity to beta

xref https://github.com/kubernetes/enhancements/issues/2579

#### Does this PR introduce a user-facing change?
```release-note
The PodSecurity admission plugin has graduated to beta and is enabled by default. The admission configuration version has been promoted to pod-security.admission.config.k8s.io/v1beta1. See https://kubernetes.io/docs/concepts/security/pod-security-admission/ for usage guidelines.
```

/sig auth
/assign @tallclair

### CODE REVIEW

**Comment by tallclair** [comment]
Should we include a `v1beta1` verison of the configuration API as part of this?

**Comment by liggitt** [comment]
yes, good point

**Comment by liggitt** [comment]
added

**Comment by liggitt** [comment]
prereqs have merged, config version is updated as well

**Pull request merged**
