### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by RomanKrasavtsev**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
fix typo

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note
NONE
```

### CODE REVIEW

**Comment by RomanKrasavtsev** [comment]
I signed it

**Review by divyenpatel — APPROVED** [review]
/LGTM

**Pull request merged**
