### PR TITLE
fix 404ing node-selection link in docs

### PR DESCRIPTION
**Pull request by iameli**
This link goes to a 404 page. I updated all references of it to point to the actual destination. Let me know if there's something smarter to be doing here.

### CODE REVIEW

**Comment by iameli** [comment]
I signed it!

**Comment by bgrant0607** [comment]
Thanks @iameli. All of these files are generated. 

@mbohlool Has the source been updated?

**Comment by mbohlool** [comment]
I think the source is updated. But, @iameli, it would be nice if you can separate changes in two commits:

1. source update (I think the change to pkg/api/v1/types.go file) 
2. auto generated updates. hack/update-all.sh or hack/update-openapi-spec.sh, hack/update-federation-openapi-spec.sh, hack/update-swagger-spec.sh,  hack/update-api-reference-docs.sh 

Also, as far as I can remember, staging/ folder should not be touched, unless something changed @caesarxuchao

**Comment by iameli** [comment]
I believe this has been fixed elsewhere. There's a working link now at e.g. https://kubernetes.io/docs/api-reference/v1/definitions/

**Pull request closed without merging**
