### PR TITLE
Reword double negative; link to readme

### PR DESCRIPTION
**Pull request by caipre**
**What this PR does / why we need it**:
Small improvement in docs.

```release-note
NONE
```

### CODE REVIEW

**Comment by caipre** [comment]
@cblecker Is anything more needed here? This is my first PR to k8s, so I'm not familiar with all the checks.

**Comment by cblecker** [comment]
ping @jbeda @smarterclayton @dchen1107

@caipre: The next step is approval from a top-level owner. I've pinged them above.

**Comment by caipre** [comment]
🎉 

Thanks @cblecker , @jbeda !

**Pull request merged**
