### PR TITLE
Add conformance column to matrix.

### PR DESCRIPTION
**Pull request by erictune**

### CODE REVIEW

**Comment by erictune** [comment]
@erickhan

**Comment by lavalamp** [comment]
LGTM-- please squash. You'll have owners make PRs adding "Yes" in this column? And a link to logs from their pass?

**Comment by erictune** [comment]
Yes.  I'll document the procedure better once I work the kinks out doing it myself on GCE, GKE, vagrant, and docker.

**Comment by erictune** [comment]
squashed.

**Comment by lavalamp** [comment]
LGTM

**Pull request merged**
