### PR TITLE
persist services need to be retried in service controller cache.

### PR DESCRIPTION
**Pull request by mfanjie**
fix issue reported by @anguslees
more detail on #25189

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31217)

### CODE REVIEW

**Comment by anguslees** [comment]
lgtm

**Comment by mfanjie** [comment]
can you help to add v1.4 label? Thanks

???? iPhone

? 2016?8?23??18:46?Angus Lees <notifications@github.com<mailto:notifications@github.com>> ???


lgtm

-

**Comment by anguslees** [comment]
No, I can't modify labels either unfortunately.

**Comment by mfanjie** [comment]
@bprashanth can you add v1.4 label? this need to be fixed in 1.4 release. Thanks.

**Pull request merged**
