### PR TITLE
Remove redundant forwarding rule in filter table

### PR DESCRIPTION
**Pull request by tnqn**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
https://github.com/kubernetes/kubernetes/pull/87748 removed [the clusterCIDR check in the forwarding rules](https://github.com/kubernetes/kubernetes/commit/8c6956e5bb4f9557e6ba459f1f6bbcb80e3b5b80#diff-2ccafd63d57233fd0697b9852514604ab880e29aeb073035765ad7541cad1b35L1516), making the two rules identical except the comments and the comments became a little confusing. 

This PR merges the two rules.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by tnqn** [comment]
@andrewsykim could you please take a look?

/test pull-kubernetes-node-e2e-containerd

**Comment by aojea** [comment]
/lgtm
/assign @thockin @danwinship 
another one for the bucket of cleanups :)

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
