### PR TITLE
Fix path construction bug in shell e2e

### PR DESCRIPTION
**Pull request by pmorie**
@roberthbailey I don't have the bandwidth to rewrite this test like we discussed, but I can at least fix the path construction bug.

### CODE REVIEW

**Comment by roberthbailey** [comment]
Shippable is complaining (legitimately) that this leaves unused imports which break the build. Can you fix those?

**Comment by pmorie** [comment]
Weak, my bad.  I had thought this built.

**Comment by pmorie** [comment]
I know what I did now.  I took logic for skips if the err was os.IsNotExist.

**Comment by roberthbailey** [comment]
LGTM.

**Pull request merged**
