### PR TITLE
Push server docker images during the release

### PR DESCRIPTION
**Pull request by fgrzadkowski**
Ref #11751

@ihmccreery @mikedanese

### CODE REVIEW

**Comment by luxas** [comment]
@fgrzadkowski How about `hyperkube` and the release process? Do you do it by hand for the moment?

**Comment by ihmccreery** [comment]
@luxas Yes; #18893 is out to fix this.

**Comment by caesarxuchao** [comment]
@ihmccreery, wrong PR number?

**Comment by ihmccreery** [comment]
Oops, sorry, please ignore my last comment.

**Comment by fgrzadkowski** [comment]
@luxas @ihmccreery I'm working on a PR to push hyperkube during the release.

**Comment by fgrzadkowski** [comment]
@ihmccreery Can you please take a look. I have a follow up PR which releases hyperkube :)

**Comment by ihmccreery** [comment]
LGTM.  Sorry about the delay.

**Comment by ihmccreery** [comment]
@k8s-bot test this please

**Comment by ihmccreery** [comment]
Looks like Jenkins is having trouble with this:

```
09:01:19 + go run ./hack/e2e.go -v --up
09:01:20 2015/12/22 09:01:20 e2e.go:303: Running: get status
09:01:20 /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/hack/e2e-internal/../../cluster/gce/../../cluster/common.sh: line 29: /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/hack/e2e-internal/../../cluster/gce/../../cluster/../build/common.sh: No such file or directory
09:01:20 2015/12/22 09:01:20 e2e.go:309: Error running get status: exit status 1
09:01:20 2015/12/22 09:01:20 e2e.go:305: Step 'get status' finished in 9.058325ms
09:01:20 2015/12/22 09:01:20 e2e.go:303: Running: up
09:01:20 /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/hack/e2e-internal/../../cluster/gce/../../cluster/common.sh: line 29: /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace/kubernetes/hack/e2e-internal/../../cluster/gce/../../cluster/../build/common.sh: No such file or directory
09:01:20 2015/12/22 09:01:20 e2e.go:309: Error running up: exit status 1
09:01:20 2015/12/22 09:01:20 e2e.go:305: Step 'up' finished in 9.274041ms
09:01:20 2015/12/22 09:01:20 e2e.go:141: Error starting e2e cluster. Aborting.
09:01:20 exit status 1
```

My guess is that /build/common.sh isn't packaged the `build` directory properly?

**Comment by nikhiljindal** [comment]
Were you guys able to resolve the ```build/common.sh: No such file or directory``` issue?
I am getting the same in https://github.com/kubernetes/kubernetes/pull/19040

**Pull request merged**
