### PR TITLE
Automated cherry pick of #71945: kubeadm: fixed etcd sync endpoints

### PR DESCRIPTION
**Pull request by pytimer**
Cherry pick of #71945 on release-1.13.

#71945: kubeadm: fixed etcd sync endpoints

### CODE REVIEW

**Comment by neolit123** [comment]
thanks @pytimer 
/priority critical-urgent
/kind bug
/ok-to-test
/assign @timothysc @fabriziopandini 
/assign @tpepper

**Comment by tpepper** [comment]
FYI we're looking at a 1.13.2 release probably next week, perhaps as soon as Dec. 17.  This is now on our radar.

**Comment by fabriziopandini** [comment]
Thanks @pytimer !
/approve
/lgtm

**Review by luxas — APPROVED** [review]
/lgtm
From me as well. Thanks!

**Comment by timothysc** [comment]
@kubernetes/sig-release 

Requires acls.

**Pull request merged**
