### PR TITLE
Fix nil pointer dereference in the azure provider

### PR DESCRIPTION
**Pull request by ldx**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
PlatformFaultDomain in the VM properties returned by Azure will be nil
if the VM is not part of an availability set. Use to.Int32() from the
Azure SDK to safely retrieve its value.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix nil pointer dereference in azure cloud provider
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by ldx** [comment]
@matthyx any idea why that test fails?

`I1222 19:23:43.605] Dec 22 19:23:29.470: INFO: At 2019-12-22 19:22:59 +0000 UTC - event for terminating-pod: {kubelet e2e-069af6ce28-674b9-minion-group-cjnx} FailedMount: MountVolume.SetUp failed for volume "default-token-gtp54" : failed to sync secret cache: timed out waiting for the condition`

It looks like https://github.com/kubernetes/kubernetes/issues/70044

**Comment by matthyx** [comment]
This is definitely a flake... Can you check for open issues from @liggitt

**Comment by liggitt** [comment]
flakes #86318 #86312 #86491

**Comment by ldx** [comment]
@matthyx @khenidak @justaugustus any of you guys can give this a once over? It's pretty straightforward.

**Review by feiskyer — COMMENTED** [review]
Thanks for the fix

/area provider/azure
/lgtm
/approve

**Comment by feiskyer** [comment]
@ldx  would you like cherry pick this to old branches?  (Refer [here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#initiate-a-cherry-pick) for the detailed steps)

**Comment by ldx** [comment]
> @ldx would you like cherry pick this to old branches? (Refer [here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#initiate-a-cherry-pick) for the detailed steps)

Sure, which branches should this be cherrypicked to?

**Comment by justaugustus** [comment]
> Sure, which branches should this be cherrypicked to?

@ldx -- All of the [active release branches](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md), please: 1.17, 1.16, and 1.15

**Pull request merged**
