### PR TITLE
dependencies: update github.com/ishidawataru/sctp

### PR DESCRIPTION
**Pull request by liyuerich**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This PR is supposed to update  github.com/ishidawataru/sctp to the latest version v0.0.0-20230406120618-7ff4192f6ff2

#### Which issue(s) this PR fixes:

Fixes # NONE

#### Special notes for your reviewer:
NONE

#### Does this PR introduce a user-facing change?

NONE

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

NONE

### CODE REVIEW

**Review by mimani68 — APPROVED** [review]

**Comment by liyuerich** [comment]
@dims @logicalhan 
Could you help to review and approve this PR?  thanks so much.

**Comment by liyuerich** [comment]
update comment of this PR in order to remove "do-not-merge/release-note-label-needed" label

**Comment by liyuerich** [comment]
/cc @dims  @logicalhan

still need your approval, please help to review. thanks.

**Comment by dims** [comment]
looks like there are a few bugs (leaks!) we could pick up here - https://github.com/ishidawataru/sctp/compare/7c296d48a2b5...7ff4192f6ff2

/approve
/lgtm

**Pull request merged**
