### PR TITLE
Automated cherry pick of #63535: Bump Heapster to v1.5.3

### PR DESCRIPTION
**Pull request by serathius**
Cherry pick of #63535 on release-1.10.

#63535: Bump Heapster to v1.5.3

### CODE REVIEW

**Comment by MaciekPytel** [comment]
@serathius Can you update release note of #63535 to include what has changed to heapster? Basically copy the point in your PR description to release note.

**Comment by serathius** [comment]
@MaciekPytel done

**Comment by MaciekPytel** [comment]
@serathius Can you fix the issue with CLA label? Otherwise this is ready to merge.

**Comment by wojtek-t** [comment]
The cla test is passing:
```
cla/linuxfoundation — serathius authorized
```
So it seems only the label is missing - let me add it manually.

**Pull request merged**
