### PR TITLE
Backporting TPR fix to 1.4

### PR DESCRIPTION
**Pull request by foxish**
This fix is in line with: https://github.com/kubernetes/kubernetes/pull/36996 for https://github.com/kubernetes/kubernetes/issues/36991

cc @jessfraz @erictune @roberthbailey

### CODE REVIEW

**Comment by roberthbailey** [comment]
@jessfraz as the 1.4 release manager.

**Comment by roberthbailey** [comment]
(not sure why I can't assign this to you...)

**Comment by jessfraz** [comment]
Hey sorry I lost the ability to add labels or I'd do it
(I had to re-register my GH account internally and it messed something up)

/lgtm

**Comment by roberthbailey** [comment]
I also added the cherry-pick-approved label and removed the do-not-merge label

**Comment by roberthbailey** [comment]
And the approved label since that should be done by the release branch owner. @grodrigues3

**Comment by foxish** [comment]
Is the submit-queue supposed to merge this automatically?

**Comment by jessfraz** [comment]
yeah its in the queue http://submit-queue.k8s.io/#/queue

**Pull request merged**
