### PR TITLE
fix assert.Equal argument order

### PR DESCRIPTION
**Pull request by CaoShuFeng**
Reference:
https://godoc.org/github.com/stretchr/testify/assert#Equal

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by php-coder** [comment]
@tallclair It's green. PTAL.

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/59317)

**Comment by php-coder** [comment]
@tallclair PTAL

/test pull-kubernetes-e2e-gce

**Comment by sttts** [comment]
/assign tallclair
/assign liggitt

For approval.

**Pull request merged**
