### PR TITLE
cleanup kubelet new node status test

### PR DESCRIPTION
**Pull request by derekwaynecarr**
**What this PR does / why we need it**:
this scopes the test to just testing allocatable values.  extra parts of the original test were copied from another test that was not relevant.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
when picking this test to earlier versions of openshift, i ran into some issues with node addresses.  since that was not the focus of the test, i wanted to scope it to just comparing allocatable values.

**Comment by wojtek-t** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Pull request merged**
