### PR TITLE
fix unbound variable issue in verify.sh

### PR DESCRIPTION
**Pull request by makhov**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

The PR fixes issue in `verify.sh` script for Mac OS. 
```
$ make verify
hack/make-rules/verify.sh: line 98: EXCLUDED_CHECKS[@]: unbound variable
make: *** [verify] Error 1
```

The issue was introduced by the previous fix (#76420), where the quotes were added but escape backslashes were not removed.

**Which issue(s) this PR fixes**:

I haven't found a related issue.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by spiffxp** [comment]
>The issue was introduced by the previous fix, where the quotes were added but escape backslashes were not removed.

What PR was this?

**Comment by makhov** [comment]
@spiffxp 
It was the PR #76420

Actually, it worked on Linux (I've checked in the docker image) but I use macOS, and I get the error without the fix.

**Review by spiffxp — APPROVED** [review]
/sig testing
/priority important-soon
/approve
/lgtm

**Pull request merged**
