### PR TITLE
remove prometheus dependencies from test/integration/apiserver/flowcontrol

### PR DESCRIPTION
**Pull request by yiyang5055**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

remove prometheus dependencies from test/integration/apiserver/flowcontrol

**Which issue(s) this PR fixes**:

part of #89267 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```
/kind cleanup

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/ok-to-test
/priority backlog

**Review by tanjunchen — COMMENTED** [review]
/cc @logicalhan

**Pull request closed without merging**
