### PR TITLE
Automated cherry pick of #61203 upstream release 1.8

### PR DESCRIPTION
**Pull request by wojtek-t**
Cherry pick of #61203 on release-1.8.
#61203 : Fix deprecated gcloud compute networks --mode switches.

### CODE REVIEW

**Comment by shyamjvs** [comment]
/lgtm

Ref issue https://github.com/kubernetes/test-infra/issues/7646

**Comment by wojtek-t** [comment]
@jpbetz - I'm going to self-approve this cherrypick to fix tests in 1.8 branch.

**Pull request merged**
