### PR TITLE
snapshot clientsets pending context migration

### PR DESCRIPTION
**Pull request by mikedanese**
https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20200123-client-go-ctx.md

Part of #46503

/kind feature
/sig api-machinery

```release-note
NONE
```

### CODE REVIEW

**Comment by mikedanese** [comment]
Generated with:

```sh
#!/bin/bash

set -o nounset
set -o pipefail
set -o errexit

function migrate () {
  local src_pkg="${1}"
  local src_path="staging/src/${src_pkg}"
  local target_pkg=$(canonicalize_path "${src_pkg}/../deprecated")
  local target_path=$(canonicalize_path "${src_path}/../deprecated")

  echo "Source package: '${src_pkg}'"
  echo "Target package: '${target_pkg}'"
  echo "Source path: '${src_path}'"
  echo "Target path: '${target_path}'"

  cp -a "${src_path}" "${target_path}"

  for file in $(find "${target_path}" -name BUILD); do
    rm "${file}"
  done

  for file in "${target_path}/"*.go; do
    sed \
      "s/^package $(basename ${src_pkg})/package $(basename ${target_pkg})/" \
      -i "${file}"
  done

  for file in $(find "${target_path}" -name '*.go'); do
    sed "s|"\""${src_pkg}|"\""${target_pkg}|" \
      -i "${file}"
  done

  ./hack/update-bazel.sh

  buildozer \
    "set visibility //${target_path}:__subpackages__" \
    $(bazel query "kind('go_*', //${target_path}/...)")
}

function main() {
  local clientset_pkgs=(
    "k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset"
    "k8s.io/client-go/kubernetes"
    "k8s.io/kube-aggregator/pkg/client/clientset_generated/clientset"
    "k8s.io/metrics/pkg/client/clientset/versioned"
  )
  for clientset_pkg in "${clientset_pkgs[@]}"; do
    migrate "${clientset_pkg}"
  done
}

main "${@}"
```

**Comment by liggitt** [comment]
needs gofmt run on the results, and the existing golint exceptions copied for the snapshot directories

**Comment by liggitt** [comment]
> All checks have passed
> 16 successful checks

it's a miracle

**Pull request merged**
