### PR TITLE
GPU e2e_node test now checks array bounds

### LINKED ISSUE #53354: The gpu_device_plugin.go e2e_node test is flaky
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): COS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by RenaudWasTaken**
**What this PR does / why we need it**:
[NVIDIA GPU device plugin e2e_node is consistently failing](https://k8s-testgrid.appspot.com/wg-resource-management#kubelet-serial-gce-e2e). This PR aims to fix that. 

Fixes #53354

**Special notes for your reviewer**:
- PR this was introduced: https://github.com/kubernetes/kubernetes/pull/52250
- @mindprince @jiayingz 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by rohitagarwal003 — APPROVED** [review]
/lgtm

@RenaudWasTaken Did you confirm that the test consistently passes after this?
cc - @jiayingz

**Comment by RenaudWasTaken** [comment]
@mindprince this fixes the `panic` that we see in the tests.
I haven't been able to reproduce this test locally (for various reasons) thus depending on @jiayingz 

I believe it should also fix  the "pod ran to completion" error too tough I'm less familiar
with how this error is generated as `Restart` is set to `Always`.

Currently the GPU tests for this PR ran twice without failing which is more than what we can see on the dashboard so IMHO this is a good sign that it should we won't be seeing any flakiness after this fix.

**Comment by mindprince** [comment]
`pull-kubernetes-e2e-gce-gpu` runs e2e tests. We don't run serial node_e2e tests on PRs. So, the only way to check that serial node_e2e tests are passing is to run those tests locally.

**Comment by RenaudWasTaken** [comment]
@mindprince thanks for clarifying this.

@jiayingz can you confirm / infirm if this patch does correctly run the e2e_node tests ? Thanks!

**Comment by jiayingz** [comment]
I think we need to add a bit more checking to make sure device plugin re-registers after kubelet restarts, see PR https://github.com/kubernetes/kubernetes/pull/53336.

**Pull request closed without merging**
