### PR TITLE
chores: Replace deprecation ioutil fucntions

### PR DESCRIPTION
**Pull request by dongjiang1989**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

Go 1.16 deprecated several io/ioutil functions.

`ioutil.ReadFile` -> `os.ReadFile`
`ioutil.ReadAll` -> `io.ReadAll`
`ioutil.ReadDir` -> `os.ReadDir`

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```
ref: https://pkg.go.dev/io/ioutil

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dongjiang1989** [comment]
@yue9944882  PTAL, thanks

**Comment by dongjiang1989** [comment]
@derekwaynecarr  PTAL, Thanks

**Comment by BenTheElder** [comment]
This doesn't need a release-note, it is not user-facing (in fact Kubernetes doesn't even support Go old enough for this to break anyone). 
Please set NONE instead.
/triage accepted

**Review by BenTheElder — COMMENTED** [review]
/lgtm

**Comment by dongjiang1989** [comment]
> This doesn't need a release-note, it is not user-facing (in fact Kubernetes doesn't even support Go old enough for this to break anyone). 
> 
> Please set NONE instead.
> 
> /triage accepted

Thanks for your review.
Done

**Comment by dongjiang1989** [comment]
@deads2k  PTAL, thanks

**Comment by BenTheElder** [comment]
cc @jpbetz

**Comment by BenTheElder** [comment]
`/kind deprecation` is for Kubernetes deprecating things and has additional process, this is not a deprecation in Kubernetes.

**Comment by dongjiang1989** [comment]
> `/kind deprecation` is for Kubernetes deprecating things and has additional process, this is not a deprecation in Kubernetes.

Thanks. I got it. removed `/kind deprecation`.

**Comment by dongjiang1989** [comment]
@BenTheElder @jpbetz  PTAL

**Comment by jpbetz** [comment]
/approve
(Code freeze is in effect, so this won't merge for a while, but it looks good)

**Comment by dongjiang1989** [comment]
> /approve (Code freeze is in effect, so this won't merge for a while, but it looks good)

@jpbetz  When you hava time, please take a look,  merge it.  thanks

**Comment by dongjiang1989** [comment]
@BenTheElder @jpbetz PTAL. Approved it, thanks

**Comment by BenTheElder** [comment]
@dongjiang1989 I'm not an approver here, but 1.31 _just_ released, code will start merging in a bit.

nudging the approval bot: based on https://github.com/kubernetes/kubernetes/pull/121997#issuecomment-1981144483
/approve

**Pull request merged**
