### PR TITLE
kubectl: add ability to copy configmaps around

### PR DESCRIPTION
**Pull request by 0xmichalis**
@kubernetes/kubectl this adds the ability to copy config maps around.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32367)

### CODE REVIEW

**Comment by kargakis** [comment]
On a second thought, I don't like it that much.

**Comment by kargakis** [comment]
Actually I am reopening for discussion because I cannot find any convenient way currently to copy a configmap to another configmap. @pmorie ptal

**Comment by smarterclayton** [comment]
Should be able to export then create?

**Comment by kargakis** [comment]
I would prefer that flow if I didn't have to change the name in between.
Exporting is for backing up and restoring in another namespace. This is
slightly different (works ootb for the current ns), has less steps, and I
control the name. It is also a step forward for
https://github.com/kubernetes/kubernetes/issues/22368. There is an argument
that this may spread across all create subcommands and why users really
need to copy things. So far it seems to make sense for things that need to
be managed in the same namespace like CMs and Secrets.

**Comment by kargakis** [comment]
Convinced myself for second time that I don't like this - will use sed for now

**Pull request closed without merging**
