### PR TITLE
Run copy.sh to update client-go for pvcs

### PR DESCRIPTION
**Pull request by wongma7**
Following up https://github.com/kubernetes/kubernetes/pull/31834 to copy the changes to client-go

Ought to be v1.4, only touches client-go. (same reasoning as here: https://github.com/kubernetes/kubernetes/pull/31644#issuecomment-243274461)

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31980)

### CODE REVIEW

**Comment by caesarxuchao** [comment]
LGTM. Thanks @wongma7.

**Comment by caesarxuchao** [comment]
@wongma7 I assume there is no manual changes in this PR, right? Nothing catches my eye but I'd like to get your confirmation.

**Comment by wongma7** [comment]
@caesarxuchao right, no manual changes, just ran copy.sh

**Comment by caesarxuchao** [comment]
Thanks for the confirmation. I added the label.

**Pull request merged**
