### PR TITLE
replace the ioutil by the os

### PR DESCRIPTION
**Pull request by chaunceyjiang**
Signed-off-by: chaunceyjiang <chaunceyjiang@gmail.com>

#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Ref https://github.com/kubernetes/kubernetes/issues/100367

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chaunceyjiang** [comment]
Friendly ping @gnufied

**Comment by dixudx** [comment]
@chaunceyjiang There are quite a bunch of usages on deprecated `ioutil.ReadFile` in this repository. Please help address them all.

**Pull request closed without merging**
