### PR TITLE
Nonbreaking changes working towards removing the RO port

### PR DESCRIPTION
**Pull request by lavalamp**
Split off from #8155.

### CODE REVIEW

**Comment by erictune** [comment]
Various comments on the individual commits.

**Comment by erictune** [comment]
Everything except commit e295f14 looks good.  Fine if you want to drop that commit from this PR and revisit it later, or fix in this PR.

**Comment by lavalamp** [comment]
I removed the kubectl commits and will modify and send in another PR.

**Comment by lavalamp** [comment]
Argh. My docs are gen'd just fine, shippable...

**Comment by erictune** [comment]
LGTM

**Pull request merged**
