### PR TITLE
Alternative unsafe copy

### PR DESCRIPTION
**Pull request by smarterclayton**
Have run this for 2 hours in the stresser without an error (no guarantee).

@wojtek-t can we do a 500 kubemark run with this prior to merge?

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35670)

### CODE REVIEW

**Comment by smarterclayton** [comment]
@wojtek-t can you try a kubemark-500 run against this PR?  This is a different assignment than #34784 (which might actually be more correct) and it's survived 45 minutes of the stress tester with no panics.

**Comment by smarterclayton** [comment]
@kubernetes/sig-testing is there anything in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/35670/pull-kubernetes-e2e-gce-gci/1790/ that can be recovered (by stopping the build / extracting the logs)?

**Comment by ixdy** [comment]
@smarterclayton build log [here](https://gist.githubusercontent.com/ixdy/1b3bb6f98d195728ba317ba5287d3a16/raw/7dc4522904320d566e587c5115ff7d09f1724a3e/pull-kubernetes-e2e-gce-gci%2520build%25201790)

(at least) two things happened:
* the e2e tests timed out after 55m (not sure why)
* copying cluster logs got stuck (causing the overall Jenkins timeout and lack of uploaded logs)

cc @kubernetes/test-infra-maintainers

**Comment by smarterclayton** [comment]
Thanks - this includes unsafe code so pathological behavior is possible.
The copy failure may have happened on a previous run of kubemark-500 while
testing code here.

On Oct 28, 2016, at 1:58 PM, Jeff Grafton <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> build log here
<https://gist.githubusercontent.com/ixdy/1b3bb6f98d195728ba317ba5287d3a16/raw/7dc4522904320d566e587c5115ff7d09f1724a3e/pull-kubernetes-e2e-gce-gci%2520build%25201790>

(at least) two things happened:

   - the e2e tests timed out after 55m (not sure why)
   - copying cluster logs got stuck (causing the overall Jenkins timeout
   and lack of uploaded logs)

cc @kubernetes/test-infra-maintainers
<https://github.com/orgs/kubernetes/teams/test-infra-maintainers>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/35670#issuecomment-256986819>,
or mute the thread

**Comment by smarterclayton** [comment]
@k8s-bot gci gce e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot gci gce e2e test this
@k8s-bot kubemark gce test this

**Comment by smarterclayton** [comment]
@k8s-bot gci gce e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot kubemark gce test this

**Comment by smarterclayton** [comment]
@k8s-bot test this

**Comment by smarterclayton** [comment]
@k8s-bot gci gce e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot gci gce e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot gci gce e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot gci gce e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot gci gce e2e test this

**Comment by smarterclayton** [comment]
```
W1029 11:41:11.575] NAME                                   MACHINE_TYPE   PREEMPTIBLE  CREATION_TIMESTAMP
W1029 11:41:11.575] e2e-gce-agent-pr-32-0-minion-template  n1-standard-2               2016-10-29T11:41:07.883-07:00
W1029 11:41:17.140] ERROR: (gcloud.compute.instance-groups.managed.create) Some requests did not succeed:
W1029 11:41:17.140]  - Internal Error
W1029 11:41:17.140] 
W1029 11:41:17.720] ERROR: (gcloud.compute.instance-groups.managed.wait-until-stable) Some requests did not succeed:
W1029 11:41:17.720]  - The resource 'projects/k8s-jkns-pr-gci-gce/zones/us-central1-f/instanceGroupManagers/e2e-gce-agent-pr-32-0-minion-group' was not found
W1029 11:41:17.720] 
W1029 11:41:18.313] INSTANCE_GROUPS=
```

@k8s-bot gci gce e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot gci gce e2e test this

@wojtek-t I'd like to get a kubemark run on this if possible, but if not I think this ready for a try in the queue and we can easily disable and revert if it regresses (if it regresses I'm going to kick this to 1.6).

**Comment by wojtek-t** [comment]
Let's try it and rollback in case of problems.

/lgtm

**Comment by smarterclayton** [comment]
One sec, going to move the test to a separate package.

**Comment by smarterclayton** [comment]
Priority bumped because we need soak time in the server to determine whether this breaks downstream jobs.

**Comment by smarterclayton** [comment]
Reapplying label, bazel missing

**Comment by smarterclayton** [comment]
@k8s-oncall I'm watching the queue for this one - if this flakes like its predecessor I'll roll it back (we probably won't know until kubemark-500 has a chance to chew on it)

**Comment by smarterclayton** [comment]
@kubernetes/goog-gke @kubernetes/sig-testing is there a way to get access to the node logs for:

```
Creating cluster e2e-gke-agent-pr-53-0...done.
W1031 09:58:58.413] ERROR: (gcloud.container.clusters.create) Operation [<Operation
W1031 09:58:58.413]  name: u'operation-1477932115378-88525c1f'
W1031 09:58:58.413]  operationType: OperationTypeValueValuesEnum(CREATE_CLUSTER, 1)
W1031 09:58:58.413]  selfLink: u'https://test-container.sandbox.googleapis.com/v1/projects/154064302321/zones/us-central1-f/operations/operation-1477932115378-88525c1f'
W1031 09:58:58.413]  status: StatusValueValuesEnum(DONE, 3)
W1031 09:58:58.413]  statusMessage: u'All cluster resources were brought up, but the cluster API is reporting that only 0 nodes out of 2 have registered. Cluster may be unhealthy.'
W1031 09:58:58.414]  targetLink: u'https://test-container.sandbox.googleapis.com/v1/projects/154064302321/zones/us-central1-f/clusters/e2e-gke-agent-pr-53-0'
W1031 09:58:58.414]  zone: u'us-central1-f'>] finished with error: All cluster resources were brought up, but the cluster API is reporting that only 0 nodes out of 2 have registered. Cluster may be unhealthy.
```

?

**Comment by smarterclayton** [comment]
@k8s-bot cvm gke e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot unit test this issue #35898

**Comment by smarterclayton** [comment]
@k8s-bot unit test this

**Comment by smarterclayton** [comment]
```
I1031 14:52:36.193] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I1031 14:52:36.193] >                              START TEST                                >
I1031 14:52:36.193] >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I1031 14:52:36.194] Start Test Suite on Host 
I1031 14:52:36.194] 
I1031 14:52:36.194] Failure Finished Test Suite on Host 
I1031 14:52:36.194] unable to create gce instance with running docker daemon for image e2e-node-ubuntu-trusty-docker10-v1-image.  instance tmp-node-e2e-e4a20de6-e2e-node-ubuntu-trusty-docker10-v1-image not running docker daemon - Command failed: Permission denied (publickey).

I1031 14:52:36.194] 
I1031 14:52:36.194] <<<<<<
```

@k8s-bot node e2e test this

**Comment by smarterclayton** [comment]
issue #35898

@k8s-bot unit test this

**Comment by smarterclayton** [comment]
@k8s-bot unit test this

**Comment by smarterclayton** [comment]
@k8s-bot unit test thiS

**Comment by smarterclayton** [comment]
@k8s-bot unit test this

**Comment by smarterclayton** [comment]
@k8s-bot unit test this

**Comment by wojtek-t** [comment]
I have seen any issues since that was merged yet.

**Comment by smarterclayton** [comment]
Not seeing the same CPU dip in the 500 I was seeing at at 5 - was hoping for more impact.  Going back to profiles now.

**Pull request merged**
