### PR TITLE
Improve lookup of unscheduled pods in daemonset controller

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Avoids a map allocation with the same computational complexity

#### Which issue(s) this PR fixes:

Supersedes #116806

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
Nvm, this is wrong

/close

**Comment by alculquicondor** [comment]
/reopen

Let's see if tests fail. Otherwise we are missing some :)

**Comment by soltysh** [comment]
/hold
so that we don't accidentally merge this, but we want to see test failure

**Comment by alculquicondor** [comment]
/close
unit tests fail locally

**Pull request closed without merging**
