### PR TITLE
azure: add k8s info to user-agent string

### PR DESCRIPTION
**Pull request by colemickens**
**What this PR does / why we need it**: Adds k8s info to the UA that the azure-sdk-for-go clients use

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: non applicable

**Special notes for your reviewer**: none

**Release note**:

```release-note
azure: clients send k8s version info in UA string
```

# ~~WIP~~
~~(This is a WIP. I don't have the actual k8s version plumbed in... yet. I'll remove this comment when it's not a WIP).~~

### CODE REVIEW

**Comment by colemickens** [comment]
Not sure why the CLA bot so confused, but looks like it sorted it out...

**Comment by colemickens** [comment]
cc: @brendandburns @anhowe

**Comment by colemickens** [comment]
(In interest of disclosure, I haven't tested this yet.)

**Comment by brendandburns** [comment]
LGTM, but looks like you need to run `./hack/update-bazel.sh`

**Comment by colemickens** [comment]
I'm having problems running update-bazel. I don't have the time right now to debug godep/bazel/whatever yet again. Any suggestions appreciated.

```
$ echo $PWD
/mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/k8s.io/kubernetes

$ echo $GOPATH
/mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/

$ ./hack/godep-restore.sh
Note: checking out 'v79'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at f15f6db... Record error from fillPackage
godep v79 (linux/amd64/go1.8)
Starting to download all kubernetes godeps. This takes a while
Download finished

$ ./hack/update-bazel.sh
extract err: cannot find package "github.com/Masterminds/semver" in any of:
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/k8s.io/kubernetes/vendor/github.com/Masterminds/semver (vendor tree)
        /usr/lib/go/src/github.com/Masterminds/semver (from $GOROOT)
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/github.com/Masterminds/semver (from $GOPATH)
extract err: cannot find package "github.com/ernesto-jimenez/gogen/imports" in any of:
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/k8s.io/kubernetes/vendor/github.com/ernesto-jimenez/gogen/imports (vendor tree)
        /usr/lib/go/src/github.com/ernesto-jimenez/gogen/imports (from $GOROOT)
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/github.com/ernesto-jimenez/gogen/imports (from $GOPATH)
extract err: cannot find package "golang.org/x/crypto/chacha20poly1305/internal/chacha20" in any of:
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/k8s.io/kubernetes/vendor/golang.org/x/crypto/chacha20poly1305/internal/chacha20 (vendor tree)
        /usr/lib/go/src/golang.org/x/crypto/chacha20poly1305/internal/chacha20 (from $GOROOT)
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/golang.org/x/crypto/chacha20poly1305/internal/chacha20 (from $GOPATH)
extract err: cannot find package "golang.org/x/net/internal/netreflect" in any of:
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/k8s.io/kubernetes/vendor/golang.org/x/net/internal/netreflect (vendor tree)
        /usr/lib/go/src/golang.org/x/net/internal/netreflect (from $GOROOT)
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/golang.org/x/net/internal/netreflect (from $GOPATH)
extract err: cannot find package "golang.org/x/net/internal/netreflect" in any of:
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/k8s.io/kubernetes/vendor/golang.org/x/net/internal/netreflect (vendor tree)
        /usr/lib/go/src/golang.org/x/net/internal/netreflect (from $GOROOT)
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/golang.org/x/net/internal/netreflect (from $GOPATH)
extract err: cannot find package "golang.org/x/net/internal/netreflect" in any of:
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/k8s.io/kubernetes/vendor/golang.org/x/net/internal/netreflect (vendor tree)
        /usr/lib/go/src/golang.org/x/net/internal/netreflect (from $GOROOT)
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/golang.org/x/net/internal/netreflect (from $GOPATH)
extract err: cannot find package "golang.org/x/tools/go/buildutil" in any of:
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/k8s.io/kubernetes/vendor/golang.org/x/tools/go/buildutil (vendor tree)
        /usr/lib/go/src/golang.org/x/tools/go/buildutil (from $GOROOT)
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/golang.org/x/tools/go/buildutil (from $GOPATH)
extract err: cannot find package "golang.org/x/tools/go/loader" in any of:
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/k8s.io/kubernetes/vendor/golang.org/x/tools/go/loader (vendor tree)
        /usr/lib/go/src/golang.org/x/tools/go/loader (from $GOROOT)
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/golang.org/x/tools/go/loader (from $GOPATH)
extract err: cannot find package "golang.org/x/text/internal/export/idna" in any of:
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/k8s.io/kubernetes/vendor/golang.org/x/text/internal/export/idna (vendor tree)
        /usr/lib/go/src/golang.org/x/text/internal/export/idna (from $GOROOT)
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/golang.org/x/text/internal/export/idna (from $GOPATH)
extract err: cannot find package "golang.org/x/text/unicode/runenames" in any of:
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/k8s.io/kubernetes/vendor/golang.org/x/text/unicode/runenames (vendor tree)
        /usr/lib/go/src/golang.org/x/text/unicode/runenames (from $GOROOT)
        /mnt/persistentdisk/home/cole/code/colemickens/kubernetes_gopath/src/golang.org/x/text/unicode/runenames (from $GOPATH)
```

**Comment by cblecker** [comment]
@colemickens: This is because you're introducing a bunch of new dependencies by adding `github.com/Azure/go-autorest/autorest` to the imported packages. If you look at the glide lock file (https://github.com/Azure/go-autorest/blob/master/glide.lock) you can see a bunch of those new dependencies.

You'll need to [add these new dependencies to godep](https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md), and then re-run update-bazel.

**Comment by colemickens** [comment]
@cblecker thank you, I should've caught that. will address asap.

**Comment by colemickens** [comment]
@cblecker I'm sorry, I think I'm still confused, `github.com/Azure/go-autorest/autorest` was already included transitively ([it's present in Godeps.json right now...](https://github.com/kubernetes/kubernetes/blob/master/Godeps/Godeps.json#L65)). Also, I'm not trying to update the package so I'm not sure I understand why I need to do anything with `godep` or why `update-bazel.sh` wouldn't just work.

Still expecting it's user error on my end but I could use a pointer if you know. Thank you.

**Comment by cblecker** [comment]
You can also test locally with `hack/verify-bazel.sh` :)

**Comment by colemickens** [comment]
I'm wondering if bazel gets tripped up with my home dir being symlinked similar to how godep gets tripped up. I undid all the godep changes, set GOPATH to be the real full path and then `./hack/update-bazel.sh` just worked... 

`./hack/verify-bazel.sh` returned no output and exit code zero, so I think it's okay now... we'll see what the bots say. Thanks again for the support.

**Comment by colemickens** [comment]
(I also rebased again, but that seems less likely to be helpful)

**Comment by cblecker** [comment]
@k8s-bot cvm gce e2e test this

**Comment by colemickens** [comment]
cc: @brendandburns @saad-ali Everything's green, just need an LGTM.

**Comment by cblecker** [comment]
I was confused about how this got merged, but it seems https://github.com/kubernetes/kubernetes/commit/5c21498dbf18cfd14fa36c54f911a82be5db1434 was also a part of https://github.com/kubernetes/kubernetes/pull/43699 and was merged there.

**Pull request merged**
