### PR TITLE
Added InterPodAffinity unit test case with Namespace.

### PR DESCRIPTION
**Pull request by k82cn**
**What this PR does / why we need it**:
Added InterPodAffinity unit test case with Namespace: unit test case for #45098

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes # N/A

**Release note**:

```release-note-none
```

### CODE REVIEW

**Comment by k82cn** [comment]
The test will failed without #45098 (tested in local).

**Comment by davidopp** [comment]
@kubernetes/sig-scheduling-pr-reviews

**Comment by bsalamat** [comment]
/lgtm

Thanks, Klaus! :)

**Comment by k82cn** [comment]
@wojtek-t , ping :).

**Pull request merged**
