### PR TITLE
dependencies: update cilium/ebpf to v0.11.0

### PR DESCRIPTION
**Pull request by akhilerm**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
update cilium/ebpf to v0.11.0

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
The changes in this PR has been separated from https://github.com/kubernetes/kubernetes/pull/117253 . Ref: https://github.com/kubernetes/kubernetes/pull/117253#issuecomment-1512888481 so as to make the review of vendored BTF marshalling code easier and unblock the other dependency update changes

#### Does this PR introduce a user-facing change?

```release-note
dependencies: update cilium/ebpf to v0.11.0
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
I can review this from a dependency perspective, but we really need node folks involved here to answer the following questions:
* is it intentional we're pulling in this _large_ dependency (it looks like the only use is in vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/devices.go and vendor/github.com/opencontainers/runc/libcontainer/cgroups/ebpf/ebpf_linux.go ... it's not clear if we're accidentally pulling this in or if we actually depend on the functionality it provides)
* can we drive upstream cleanup of the signal registration and panic-on-init-failure behavior added in github.com/cilium/ebpf/internal/sys/signals.go in this bump so that behavior is not inherited by every binary that links in this package?

/sig node
/cc @bobbypage

**Comment by pacoxu** [comment]
https://github.com/opencontainers/runc/pull/2145 and https://github.com/opencontainers/runc/pull/2903 /cc @kolyshkin

**Comment by kolyshkin** [comment]
>> is it intentional we're pulling in this large dependency (it looks like the only use is in vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/devices.go and vendor/github.com/opencontainers/runc/libcontainer/cgroups/ebpf/ebpf_linux.go ... it's not clear if we're accidentally pulling this in or if we actually depend on the functionality it provides)


> Added in [opencontainers/runc#2145](https://github.com/opencontainers/runc/pull/2145) and [opencontainers/runc#2903](https://github.com/opencontainers/runc/pull/2903) /cc @kolyshkin


Minor correction: this was added by opencontainers/runc#2145, and is only used by `github.com/opencontainers/runc/libcontainer/cgroups/ebpf` package.

The usage is justified. In cgroup v2, per-cgroup device access is controlled by an eBPF program that needs to be loaded. Which is what runc does using the above library.

Now, runc/libcontainer is used by both runc and kubelet. Obviously, runc uses this functionality, but kubelet does not.

I have managed to decouple device handling in https://github.com/opencontainers/runc/pull/3452. This will be available in runc 1.2.0 (once it's out, that is).

**Comment by bobbypage** [comment]
Thanks @liggitt for raising question regarding why we need this dependency and the signal registration on init.

@akhilerm is there any specific reason we need to update this dependency to v0.10? 

If not, perhaps another approach would be wait for runc 1.2.0 release which sounds like will allow us to _drop_ this dependency since libcontainer usage does not depend on this library as @kolyshkin mentioned.

**Comment by akhilerm** [comment]
> is there any specific reason we need to update this dependency to v0.10?

@bobbypage No.  I was updating the dependencies to the latest versions in k/k since many modules were on old versions.

As mentioned , I think we can wait for runc `v1.2.0` so that the dependency can be dropped.

**Comment by akhilerm** [comment]
@liggitt Do you happen to know why the `verify-vendor.sh` script is failing [here](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/117457/pull-kubernetes-dependencies/1679019876326313984#1:build-log.txt%3A842). When I checked inside the script , it fails while running the `dependencyverifier` on the `unwanted-references.json` file. 

NOTE: The `pin-dependency.sh` and `update-vendor.sh` was used to update the dependencies.  and the same `verify-vendor.sh` fails locally also.

**Comment by liggitt** [comment]
looks like cilium/ebpf stopped using the golang.org/x/exp, so drop it from the list of consumers in the unwanted deps file:

```
  []uint8(
  	"""
  	... // 89 identical lines
  	    "golang.org/x/exp": [
  	      "github.com/antlr/antlr4/runtime/Go/antlr/v4",
- 	      "github.com/cilium/ebpf",
  	      "github.com/google/cel-go"
  	    ],
  	... // 34 identical lines
  	"""
  )
```

**Comment by liggitt** [comment]
oh, I take it back... cilium *started* using that repo, and we don't want to take additional deps on it... can you open an issue / PR to the epbf repo to drop use of the unstable exp dependency?

**Pull request closed without merging**
