### PR TITLE
deprecate PSP in 1.21, but leave removal at 1.25

### PR DESCRIPTION
**Pull request by deads2k**
After discussion in sig-auth, the future of restricting pod security settings does not lie in PSP because compatibility restrictions will prevent the kinds of changes that are required.  To clearly signal this, we will deprecate PSP in 1.21 and leave the removal of the api as 1.25 in keeping with sig-arch required transitioning out of beta.

Meeting minutes here: https://docs.google.com/document/d/1woLGRoONE3EBVx-wTb4pvp4CI7tmLZ6lS26VTbosLKM/edit
Discussion doc here: https://docs.google.com/document/d/1VKqjUlpU888OYtIrBwidL43FOLhbmOD5tesYwmjzO4E/edit#
Shortcomings presentation here: https://docs.google.com/presentation/d/1Kv6BSBNyLCyglMbK7e6tVOaDYe89LV2aHL2Hlb-9HX8/edit

/kind cleanup
/kind api-change
/kind deprecation
/priority important-soon

@kubernetes/sig-auth-api-reviews 
@enj @liggitt @mikedanese @tallclair 

```release-note
The PodSecurityPolicy API is deprecated in 1.21, and will no longer be served starting in 1.25.
```

### CODE REVIEW

**Comment by liggitt** [comment]
/triage accepted

Updated release note to drop forward-looking statements about replacements. We will update the release notes with references to the current state of the proposal when 1.21 releases.

**Comment by enj** [comment]
/lgtm

I 💯 agree with the reasoning for this deprecation.

Test failures are real - codegen is out of date.

**Review by enj — APPROVED** [review]

**Comment by tallclair** [comment]
/lgtm

I was going to suggest also tagging PSP in the extensions group, but it looks like it was flagged for removal in v1.16. ¯\ _(ツ)_/¯

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/extensions/v1beta1/types.go#L949

**Comment by mikedanese** [comment]
For posterity.

/lgtm

**Comment by jrsapi** [comment]
Greetings @deads2k ! 
 1.21 Enhancement shadow checking in. Since this has been merged and being deprecated in 1.21. Friendly reminder to add this to the [enhancements tracking sheet](https://docs.google.com/spreadsheets/d/1I_ybuEI6gNNPJT7xcO_y-eu_BpayTdBX3nerVsHybNA/edit#gid=0).

**Pull request merged**
