### PR TITLE
Make NetworkPolicy docs reflect reality

### PR DESCRIPTION
**Pull request by danwinship**
spinoff of #39164; this just updates the docs to reflect the way the v1beta1 API has actually been implemented

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by danwinship** [comment]
@thockin

**Comment by thockin** [comment]
needs a rebase, though

**Comment by danwinship** [comment]
should be release-note-none because it doesn't make sense to document this separately from the v1 PR

**Comment by danwinship** [comment]
@thockin: the merge bot added do-not-merge earlier and never removed it even though this should be good to go now...

**Pull request merged**
