### PR TITLE
Move the 'private' (authenticated) image...

### PR DESCRIPTION
**Pull request by mattmoor**
...into a bucket owned by google-containers.

### CODE REVIEW

**Comment by mattmoor** [comment]
@satnam6502 FYI

**Comment by roberthbailey** [comment]
LGTM.

**Comment by satnam6502** [comment]
So we should be moving all our test images into this bucket?

**Comment by mattmoor** [comment]
No, this bucket is just for testing *authenticated* access, so just the "private" test's image.

**Pull request merged**
