### PR TITLE
Automated cherry pick of #59880: Drop init container annotations during conversion

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #59880 on release-1.9.

#59880: Drop init container annotations during conversion

### CODE REVIEW

**Comment by mbohlool** [comment]
does it make sense to add a test for this?

**Comment by liggitt** [comment]
rebased to pick up fix for aws presubmit, retagging

**Comment by mbohlool** [comment]
how is this tested? The core conversion is touched and I am afraid of cherrypicking it with no test.

**Comment by mbohlool** [comment]
chatted with @liggitt offline, this is tested manually and also it is ok to push this back to 1.9.5.

/hold

**Comment by mbohlool** [comment]
The branch is frozen. holding this for 1.9.5.

/hold

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60121)

**Pull request merged**
