### PR TITLE
fix comment about nodeStatusReportFrequency in kubelet.go

### PR DESCRIPTION
**Pull request by monstercy**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
 /kind cleanup

**What this PR does / why we need it**:
fix comment about nodeStatusReportFrequency in kubelet.go
**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by mattjmcnaughton** [comment]
/lgtm
/ok-to-test
/assign @derekwaynecarr 

thanks for your pr :)

**Review by neolit123 — COMMENTED** [review]
/kind cleanup
/priority backlog

**Comment by monstercy** [comment]
ping @derekwaynecarr, Could you kindly take a look, please?

**Comment by monstercy** [comment]
ping @derekwaynecarr

**Comment by monstercy** [comment]
@yujuhong ptal

**Pull request merged**
