### PR TITLE
acronym(api) has a consistent case.

### PR DESCRIPTION
**Pull request by chenpengdev**
**What this PR does / why we need it**:
Words in names that are initialisms or acronyms (e.g. "URL" or "NATO") have a consistent case.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by resouer** [comment]
Not sure about this ... is this some kind of conversion in somewhere else?

**Comment by chenpengdev** [comment]
是的

**Comment by chenpengdev** [comment]
@resouer https://github.com/golang/go/wiki/CodeReviewComments#initialisms

**Comment by resouer** [comment]
If this convention is respected by Kubernetes repo, you may need to fix all in-consistency in it  (specific pkg at least) instead of one line in single file.

And it would be better if you can work out a check tool and include it in `/hack/verify-xxx` scripts.

**Comment by resouer** [comment]
So I suggest you to raise a issue first, i.e. "respect CodeReviewComments#initialisms in Kubernetes repo".

And then send PRs to fix it (can also work with other ppl if the work is huge)

**Comment by chenpengdev** [comment]
K8s [codeing-conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/coding-conventions.md#code-conventions) includes CodeReviewComments#initialisms.
Ｍaybe there has a difference between code and comment, the comments are't very strict.

**Comment by chenpengdev** [comment]
Closing.

**Pull request closed without merging**
