### PR TITLE
chore: properly validate 'ALL' capability

### LINKED ISSUE #115142: Inconsistent validation behaviour when adding capabilities
### What happened?

Setting `allowPrivilegeEscalation: false` in combination with adding `CAP_SYS_ADMIN` capabilities fails and produces the following error message:
```
cannot set `allowPrivilegeEscalation` to false and `capabilities.Add` CAP_SYS_ADMIN
```

However, using `ALL` instead of `CAP_SYS_ADMIN` passes.
This results in an inconsistent behaviour as `ALL` includes `CAP_SYS_ADMIN` and should therefore behave the same way.

### What did you expect to happen?

Since adding `ALL` includes `CAP_SYS_ADMIN` it should fail as well.
An error message like the following should be sufficient:
```
cannot set `allowPrivilegeEscalation` to false and `capabilities.Add` to CAP_SYS_ADMIN or ALL
```

### How can we reproduce it (as minimally and precisely as possible)?

`CAP_SYS_ADMIN` fails as expected:
```console
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false # <-- IMPORTANT
          capabilities:
            add:
            - "CAP_SYS_ADMIN" # <-- IMPORTANT
EOF
The Deployment "nginx" is invalid: spec.template.spec.containers[0].securityContext: Invalid value: core.SecurityContext{Capabilities:(*core.Capabilities)(0xc011989500), Privileged:(*bool)(nil), SELinuxOptions:(*core.SELinuxOptions)(nil), WindowsOptions:(*core.WindowsSecurityContextOptions)(nil), RunAsUser:(*int64)(nil), RunAsGroup:(*int64)(nil), RunAsNonRoot:(*bool)(nil), ReadOnlyRootFilesystem:(*bool)(nil), AllowPrivilegeEscalation:(*bool)(0xc00c2549b6), ProcMount:(*core.ProcMountType)(nil), SeccompProfile:(*core.SeccompProfile)(nil)}: cannot set `allowPrivilegeEscalation` to false and `capabilities.Add` CAP_SYS_ADMIN
```

`ALL` passes:
```console
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false # <-- IMPORTANT
          capabilities:
            add:
            - "ALL" # <-- IMPORTANT
EOF
deployment.apps/nginx created
```

### Anything else we need to know?

Will provide a PR with a potential solution soon.

### Kubernetes version

<details>

```console
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.0-alpha.0.1032+5e9fc39d17fbc6", GitCommit:"5e9fc39d17fbc636605ac69e4c487a261fbc0f67", GitTreeState:"clean", BuildDate:"2023-01-17T20:32:41Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by f1ko**
Signed-off-by: Filip Nikolic <oss.filipn@gmail.com>

#### What type of PR is this?

/kind bug

/kind api-change

#### What this PR does / why we need it:

It ensures consistent validation behaviour for `ALL` and `CAP_SYS_ADMIN` capabilities in combination with `allowPrivilegeEscalation: false`.

#### Which issue(s) this PR fixes:

Fixes #115142

#### Special notes for your reviewer:

Copy-paste instructions for reproducing can be found in the issue.

#### Does this PR introduce a user-facing change?

```release-note
Fixed validation behaviour for `ALL` capability in combination with `allowPrivilegeEscalation: false`.

Prior to this change the apiserver denied `allowPrivilegeEscalation: false` in combination with `CAP_SYS_ADMIN` but allowed it with `ALL` (which implicitly grants `CAP_SYS_ADMIN`).
Now both cases will be denied.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lavalamp** [comment]
This doesn't look safe, it may mark existing data as invalid, no?

**Comment by F1ko** [comment]
@lavalamp that's right.

If someone was to deploy a pod with capabilities `ALL` and `allowPrivilegeEscalation: false` before and after this patch the behavior would change (prior to the patch it would be allowed; later it would be denied).

May I suggest a deprecation note for that reason?
I'd be happy to implement it.

**Comment by lavalamp** [comment]
The problem is that such an item might not be editable any more, possibly it might not even be deletable.

**Comment by liggitt** [comment]
> The problem is that such an item might not be editable any more, possibly it might not even be deletable.

Exactly. Tightening validation has to consider and tolerate existing data in update requests. 

The validation options approach described in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#new-enum-value-in-existing-field could be applied here:

1. add a validation option to PodValidationOptions to indicate whether to allow the ALL capability alongside `allowPrivilegeEscalation: false`
2. update GetValidationOptionsFromPodSpecAndMeta to set that option to false on create, and true on update IFF the existing pod spec already contains the `ALL` capability alongside `allowPrivilegeEscalation: false`
3. plumb the PodValidationOptions through validation to the point at which the capability/allowPrivilegeEscalation validation is done, and conditionally forbid ALL based on the option set

I'd also like @tallclair to weigh in on the capability validation here in general... I'm actually not certain how effective the existing validation is based on things like https://github.com/kubernetes/kubernetes/pull/105237 or case-insensitive handling of the value

**Comment by tallclair** [comment]
Per https://github.com/kubernetes/kubernetes/pull/105237/files#r802187255, I'd prefer to see the `CAP_SYS_ADMIN` requirement removed, rather than adding to the list. These checks seem more appropriate to security policy, rather than API validation.

**Comment by liggitt** [comment]
/remove-label api-review

dropping from API review queue until it's settled whether this is a change that *should* be made

**Pull request closed without merging**
