### PR TITLE
Calling the heap.Init() method on a heap with length 0 is redundant

### PR DESCRIPTION
**Pull request by daniel-hutao**
Signed-off-by: Daniel Hu <farmer.hutao@outlook.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Calling the heap.Init() method on a heap with length 0 is redundant

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
There is also no reason not to do it. it's useful for people reading the code to understand that it's a heap.

**Review by caesarxuchao — COMMENTED** [review]
/lgtm
/approve

**Comment by caesarxuchao** [comment]
Ha, ok, just saw Daniel's comment, which is also fair.

/hold

**Comment by lavalamp** [comment]
It's fine, if you think it's an improvement I don't mind

/hold cancel

**Comment by caesarxuchao** [comment]
No, Daniel, I agree with you, calling `heap.Init()` here is a cheap way to improve readability. Let's keep it.

Without this `heap.Init()`, it will be too subtle to see this queue is used as a heap.

/lgtm cancel
/approve cancel

**Comment by daniel-hutao** [comment]
It's ok, I agree with it's useful to understand that it's a heap.

**Pull request closed without merging**
