### PR TITLE
Fix some logs and commend information for healthz

### PR DESCRIPTION
**Pull request by yuexiao-wang**
Fix some logs which should be a lower case letter for the first letter and modify some commend information which is consistent in context.

Signed-off-by: yuexiao-wang wang.yuexiao@zte.com.cn

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34410)

### CODE REVIEW

**Comment by yuexiao-wang** [comment]
Fix issue: #34427

**Comment by yuexiao-wang** [comment]
@smarterclayton PTAL
Thanks!

**Comment by yuexiao-wang** [comment]
@smarterclayton PTAL
Thanks!

**Comment by smarterclayton** [comment]
@k8s-bot ok to test

**Comment by yuexiao-wang** [comment]
@smarterclayton PTAL
Jenkins GCI GKE smoke e2e  is faild.
Thanks

**Comment by yuexiao-wang** [comment]
@smarterclayton PTAL
Jenkins Kubemark GCE e2e is failed.

**Comment by fabianofranz** [comment]
@k8s-bot gci gke e2e test this

**Pull request merged**
