### PR TITLE
refactor kubelet todo item, change canRunPod to softAdmitHandler

### PR DESCRIPTION
**Pull request by oulinbao**
**What this PR does / why we need it**:
refactor the todo item

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by wackxu** [comment]
It is duplicate of https://github.com/kubernetes/kubernetes/pull/56530

**Comment by dixudx** [comment]
@oulinbao Could you close this PR, since #56530 has already implemented the same handler.

**Comment by feiskyer** [comment]
duplicate of #56530

**Comment by oulinbao** [comment]
OK, but I have refactored the repeat codes, please @wackxu have a look.

**Pull request closed without merging**
