### PR TITLE
Add kube-metrics-adapter to list of Custom Metrics Implementations

### PR DESCRIPTION
**Pull request by gjtempleton**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:
Adds link to implementation of the custom metrics API server by Zalando at https://github.com/zalando-incubator/kube-metrics-adapter
**Which issue(s) this PR fixes**:

NONE
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by DirectXMan12** [comment]
maybe add a couple more details (e.g. "directly from pods" or "from several different backend" or "configured directly on the HPA") to say what distinguishes it, otherwise seems fine.

**Comment by gjtempleton** [comment]
Thanks for having a look. I've added a bit more detail now.

**Pull request merged**
