### PR TITLE
Move e2e dependent images from kubernetes/kubernetes.github.io repo

### LINKED ISSUE #48530: Test image dependencies from kubernetes/kubernetes.github.io repo
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
Part of conformance test following images are used in `test/e2e` which needs to be ported to support multi architecture

1. gcr.io/google_containers/liveness:e2e	- https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/liveness/image/Dockerfile
2. gcr.io/google_containers/update-demo:nautilus - https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/update-demo/images/nautilus/Dockerfile
3. gcr.io/google_containers/update-demo:kitten - https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/update-demo/images/kitten/Dockerfile

As most of the test images are under `test/images` which is easy to maintain. I'm in dilemma to move these images here or keep it in the doc repo only and port them to support multiarchitecture?

I'm looking for suggestions here from broader team!

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:
Move e2e dependent images from kubernetes/kubernetes.github.io repo
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #48530

**Special notes for your reviewer**:

**Release note**:

```NONE
```

### CODE REVIEW

**Review by luxas — APPROVED** [review]
/lgtm
/ok-to-test

**Comment by cblecker** [comment]
```
I0719 19:12:18.639] Verifying hack/make-rules/../../hack/verify-boilerplate.sh
I0719 19:12:19.727] Boilerplate header is wrong for: /go/src/k8s.io/kubernetes/test/images/liveness/Dockerfile
I0719 19:12:19.728] Boilerplate header is wrong for: /go/src/k8s.io/kubernetes/test/images/liveness/server.go
I0719 19:12:19.728] Boilerplate header is wrong for: /go/src/k8s.io/kubernetes/test/images/nautilus/Dockerfile
I0719 19:12:19.728] Boilerplate header is wrong for: /go/src/k8s.io/kubernetes/test/images/kitten/Dockerfile
I0719 19:12:19.729] FAILED   hack/make-rules/../../hack/verify-boilerplate.sh	1s
```
/ok-to-test

**Comment by mkumatag** [comment]
Fixed the boilerplate copyright banners

**Comment by luxas** [comment]
ping @ixdy

**Comment by ixdy** [comment]
/lgtm

at some point we should probably stop including `test/images` in `kubernetes-test.tar.gz`, as much fun as it is to ship a kitten with every release.

**Comment by cblecker** [comment]
I'm pretty sure k8s would be ruined if we dropped the kitten.

**Comment by mkumatag** [comment]
> /lgtm
> 
> at some point we should probably stop including test/images in kubernetes-test.tar.gz, as much fun as it is to ship a kitten with every release.

I'm not really sure where this tar is used or published. I don't see it in CHANGELOG page atleast. My vote is for using images directly from image repository instead of shipping sourcecode somewhere and building it.

@cblecker all this time kitten was never part of `kubernetes-test.tar.gz`!

**Comment by ixdy** [comment]
We add the `test/images` directory [here](https://github.com/kubernetes/kubernetes/blob/04c863cb1d89392dac4e88b86d586236e1c284ab/build/lib/release.sh#L453-L460). This was added in #11694, probably because some e2e tests used specs from the `test/images` directory. I'm not sure whether that's still true.

Not really relevant to this PR, in any case. :)

**Comment by mkumatag** [comment]
We use spec files from `test/e2e/testing-manifests` and not really sure any of the files we are still referring from `test/images`. Will take a close look at it later and submit a different PR to fix it.
> We add the test/images directory here. This was added in #11694, probably because some e2e tests used specs from the test/images directory. I'm not sure whether that's still true.
> 
> Not really relevant to this PR, in any case. :)

**Pull request merged**
