### PR TITLE
fix ReadOnlyPort defaulting, CAdvisorPort documentation

### LINKED ISSUE #51345: Fix ReadOnlyPort defaulting
See #51341

### PR DESCRIPTION
**Pull request by mtaufen**
The ReadOnlyPort defaulting prevented passing 0 to diable via
the KubeletConfiguraiton struct.

The HealthzPort defaulting prevented passing 0 to disable via the
KubeletConfiguration struct. The documentation also failed to mention
this, but the check is performed in code.

The CAdvisorPort documentation failed to mention that you can pass 0 to
disable.

fixes #51345

### CODE REVIEW

**Comment by mtaufen** [comment]
HealthzPort needs this treatment too, one sec

**Comment by liggitt** [comment]
```
I0825 17:31:24.808] pkg/kubelet/apis/kubeletconfig/v1alpha1/zz_generated.conversion.go:157: cannot use in.ReadOnlyPort (type *int32) as type int32 in assignment
I0825 17:31:24.808] pkg/kubelet/apis/kubeletconfig/v1alpha1/zz_generated.conversion.go:193: cannot use in.HealthzPort (type *int32) as type int32 in assignment
I0825 17:31:24.809] pkg/kubelet/apis/kubeletconfig/v1alpha1/zz_generated.conversion.go:316: cannot use in.ReadOnlyPort (type int32) as type *int32 in assignment
I0825 17:31:24.809] pkg/kubelet/apis/kubeletconfig/v1alpha1/zz_generated.conversion.go:364: cannot use in.HealthzPort (type int32) as type *int32 in assignment
```

**Comment by mtaufen** [comment]
Ah yup, changed to pointer type. Fixed.

**Comment by mtaufen** [comment]
Test failure... odd failure message:

`E0825 18:34:00.991539 6099 serving.go:189] Couldn't create in cluster config due to unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined. SharedInformerFactory will not be set. W0825 18:34:00.992587 6099 authentication.go:56] Authentication is disabled I0825 18:34:00.997791 6099 serve.go:85] Serving securely on 127.0.0.1:37645 I0825 18:34:00.997896 6099 crd_finalizer.go:242] Starting CRDFinalizer I0825 18:34:00.998128 6099 customresource_discovery_controller.go:152] Starting DiscoveryController I0825 18:34:00.998160 6099 naming_controller.go:277] Starting NamingConditionController 2017-08-25T18:34:01.005772157Z AUDIT: id="29ebbc1b-5036-429b-ade6-05a1f9393824" ip="127.0.0.1" method="GET" user="<none>" groups="<none>" as="<self>" asgroups="<lookup>" namespace="<none>" uri="/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions?resourceVersion=0" 2017-08-25T18:34:01.028168583Z AUDIT: id="787458dd-409a-47dd-ac99-6f83bebead43" ip="127.0.0.1" method="GET" user="<none>" groups="<none>" as="<self>" asgroups="<lookup>" namespace="<none>" uri="/healthz"`

**Comment by liggitt** [comment]
Captured text is spurious. Flake in that test is tracked in https://github.com/kubernetes/kubernetes/issues/49423

**Comment by mtaufen** [comment]
Ah thanks. SG.

**Pull request merged**
