### PR TITLE
Limit range supporting a default resource limits value

### PR DESCRIPTION
**Pull request by derekwaynecarr**
**Use Case:**
1. As a namespace administrator, I need a way to limit the amount of resources a single pod may consume in that namespace.  
2. As a namespace administrator, I need a way to set sensible default resource requirements for a pod when a pod author does not specify resource requirements (limits or requests)
3. As a pod author, I should be able to supply my own resource requirements that are different than the namespace defaults as long as they fall within the value min/max range for that resource.

**API Change:**
1. Add a Default to go with Min/Max on LimitRangeItem

**System Behavior Change:**
1. Sets a pod resource limits to the resource default value if omitted by the pod author.
2. Sets a pods resource requests to the resource min value if omitted by the pod author.

**CLI Change:**

``` shell
cluster/kubectl.sh describe limits limits
Name:       limits
Type        Resource    Min Max Default
----        --------    --- --- ---
Pod     cpu     250m    2   -
Pod     memory      1Mi 1Gi -
Container   memory      1Mi 1Gi 1Mi
Container   cpu     250m    2   250m
```

**Benefits:**

Many end-users do not know what to set for resource requests or limits.  In many instances, this results in no value being specified by pod authors (see our examples).  This is problematic when an administrator wants to restrict the use of unbounded resources in a particular namespace and allow for over commit by enforcing requests and limits.

With this feature, the administrator can ensure sensible default values (if desired) are set for each container resource requests and limits.  The end-user is able to specify actual values as long as they fall within the specified min/max limit if they need more resources.

### CODE REVIEW

**Comment by brendandburns** [comment]
This looks reasonable to me, though I defer to @bgrant0607 for the API changes.

Can you split this into three PRs:
  1. Clean up all of the commas in the example JSON files
  2. The default resource changes
  3. The removal of the admission code which is apparently unused?

That will make each change easier to review and merge

Thanks!
--brendan

**Comment by bgrant0607** [comment]
At a 30s glance, the one new field looks reasonable, though there is the issue of pod vs. container resources, which I don't see how to resolve until we support pod-level resources.

cc @erictune

**Comment by derekwaynecarr** [comment]
@brendandburns  - broke this PR into a single commit for the API change based on initial feedback from you and @bgrant0607 

@jwforres - you should be aware of this PR for the UI work around LimitRange

**Comment by derekwaynecarr** [comment]
I want to chat on the approach a little more with @danmcp from Red Hat side.

**Comment by derekwaynecarr** [comment]
@danmcp and I chatted on this topic in-person.  This should capture the output of what we are looking to enable in near term for allowing sensible defaults to be specified for resource requests and limits if omitted.  This should not conflict with any future work we would look to do with quality of service tiers that should allow for unbounded resource limits, but defined resource min requests per our discussion at the meet-up with @bgrant0607

**Comment by derekwaynecarr** [comment]
updated pr initial comment text

**Comment by brendandburns** [comment]
LGTM, shippable looks like a flake.  Fine to merge during merge hours.

**Pull request merged**
