### PR TITLE
WIP: testing split disk e2e tests

### PR DESCRIPTION
**Pull request by kannon92**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kannon92** [comment]
@kwilczynski the Crio bump looks to have improved the tests but the failures are still concerning.

I have two jobs for this feature:

1) test split filesystem garbage collection (splits)
2) e2e tests where split filesystem
Is configured and feature is turned on

1 and 2 seem to have failure but I’m more concerned with 2 at the moment.

**Comment by kwilczynski** [comment]
Closing in favour of the following:

- https://github.com/kubernetes/kubernetes/pull/125417

The linked Pull Request supersedes this change.

**Pull request closed without merging**
