### PR TITLE
typo - extra space - in Fatalf format string

### PR DESCRIPTION
**Pull request by dims**
Change-Id: Ifeff0ee29aa6ccdc4c3ebdd2a071cebfafaf937e

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by poothia** [comment]
lgtm

**Comment by dims** [comment]
@jsafrane @jingxu97 can you please lgtm?

**Pull request merged**
