### PR TITLE
Fix typo in kuberuntime_container.go

### PR DESCRIPTION
**Pull request by disconnect3d**
This PR fixes a small typo in kuberuntime_container.go

### CODE REVIEW

**Comment by mattjmcnaughton** [comment]
/ok-to-test

Thanks for the pr @disconnect3d !

Please add a release note and also sign the CLA. Lmk if I can help you with either of those.

**Comment by disconnect3d** [comment]
/remove-lifecycle stale
/retest
@mattjmcnaughton 
> Please add a release note and also sign the CLA. Lmk if I can help you with either of those.
Could you add a release note, please?

**Comment by mattjmcnaughton** [comment]
For future reference, you can find the list of supported `prow` bot commands here: https://github.com/oracle/kubernetes-test-infra/blob/master/commands.md.

**Pull request closed without merging**
