### PR TITLE
fix BusyBox sed

### PR DESCRIPTION
**Pull request by tipok**
BusyBox sed works the same way as GNU sed

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> 
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Code completion for zsh under alpine is not working currently because BusyBox sed is not identified as a GNU sed.
This leads to
LWORD='[[:<:]]'
RWORD='[[:>:]]'
which is not working in BusyBox sed

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks for the PR @tipok ,
does kubeadm even work on Alpine?
it only supports systemd ATM and AFAIK Alpine needs OpenRC.

in any case we are currently in code freeze, and this can merge after the 10th of Sept.

**Comment by tipok** [comment]
@neolit123 thank you.
Actually i haven't tested `kubeadm`.
I just aligned two of the snippets to stay the same. Not sure if running `kubeadm` on a machine with BusyBox' `sed`  is a valid use case. Let me know if i should remove the change in `kubeadm`.

**Comment by neolit123** [comment]
@tipok 
possible better to omit the kubeadm change for now.
if users discover the bug (possibly in the future once we support OpenRC) we can look into fixing the non-GNU sed problems.

**Comment by tipok** [comment]
@neolit123 
changed the PR. Thank you

**Comment by neolit123** [comment]
/remove-area kubeadm
/ok-to-test
/priority backlog

thanks.
if you are not getting any review from the kubectl maintainers, try asking in the #sig-cli channel on slack.

**Review by dixudx — APPROVED** [review]
/lgtm

**Comment by rosti** [comment]
@neolit123 just to clarify, kubeadm does have OpenRC code, but IDK if someone is testing it or even if it works.

**Comment by neolit123** [comment]
> just to clarify, kubeadm does have OpenRC code,

yes it does. the part that is currently missing is the abstraction of the unit file we write in the case of systemd.

**Comment by tipok** [comment]
i've merged the master into my fork. I'm not sure if this can be merged now. The same changes are merged in the helm release.

**Comment by tipok** [comment]
@neolit123 and @dixudx after some merges into the master i had to merge the master into my fork so it's not conflicting. because of that labels were removed.

I would be very happy if you could recheck the PR and maybe merge it into the master.

Thank you.

**Comment by neolit123** [comment]
hi,
please squash the commits locally and force push to have a single one.
> do-not-merge/contains-merge-commits

the bots will not allow adding merge commits.

i can then re-apply LGTM for you, but you still need to find an approver.
maybe pinging someone from https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/OWNERS on k8s slack.

/remove-lifecycle stale

**Comment by tipok** [comment]
@neolit123 thank you for the clarification.

**Comment by neolit123** [comment]
/lgtm
/retest

type `/retest` on non-related CI failures.

**Review by janetkuo — APPROVED** [review]

**Pull request merged**
