### PR TITLE
Fix range copy issue

### PR DESCRIPTION
**Pull request by r4f4**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: Fix a range issue so that container image overrides work properly. Without this, tests in Openshift CI in s390x fails with exec format error since the wrong images are used.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: None

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
why is this only a problem in 1.17?

**Comment by oomichi** [comment]
This also seems good for me.

/release-note-none
/ok-to-test
/lgtm

**Comment by r4f4** [comment]
> ~why is this only a problem in 1.17?~
> 
> never mind, i saw:
> #92935 (backport for 1.16)

Yes, sorry for not mentioning that before.

**Comment by r4f4** [comment]
Anything stopping this from being merged?

**Comment by r4f4** [comment]
I guess the do-not-merge/cherry-pick-not-approved label needs to be lifted.

**Comment by oomichi** [comment]
@r4f4  Yes, you are right.
The bot says
```
AFTER it has been approved by code owners, please ping the kubernetes/release-managers team in a comment to request a cherry pick review.
```

**Comment by mkumatag** [comment]
@kubernetes/release-managers can someone help us to merge this?

**Pull request merged**
