### PR TITLE
Build patch from openapi only for registered types

### LINKED ISSUE #156: Apply should not assume that publishing openapi spec means support strategic merge patch
It was discussed in https://github.com/kubernetes/kubernetes/pull/51321#pullrequestreview-80212182.

According to https://github.com/kubernetes/kubernetes/pull/51321#discussion_r154271945, what we should do for this release is:
send strategic merge patch if the type is registered, JSON merge patch otherwise.

Creating this issue for tracking purpose.

### PR DESCRIPTION
**Pull request by mengqiy**
Address the concern in https://github.com/kubernetes/kubernetes/pull/51321#pullrequestreview-80212182.

fixes kubernetes/kubectl#156

```release-note
NONE
```

/assign @apelisse

### CODE REVIEW

**Comment by mengqiy** [comment]
/assign @liggitt 
cc @pwittrock

**Comment by liggitt** [comment]
/lgtm
Thanks

**Comment by shiywang** [comment]
@liggitt I think we need a milestone 1.9 for this pr

**Comment by apelisse** [comment]
Agreed, done

**Comment by mengqiy** [comment]
@pwittrock Can you please add label `status/approved-for-milestone` to make the bot happy?

**Comment by pwittrock** [comment]
@mengqiy We should have an issue for this so it could be tracked as part of the release.

**Comment by mengqiy** [comment]
> We should have an issue for this so it could be tracked as part of the release.

Will create an issue shortly.

**Pull request merged**
