### PR TITLE
Bump Dashboard to v2.0.1

### PR DESCRIPTION
**Pull request by maciaszczykm**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**: It updates dashboard to the newest version.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

For more information on release notes see: https://git.k8s.io/community/contributors/guide/release-notes.md
-->
```release-note
Bump Dashboard to v2.0.1
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by hwdef** [comment]
/lgtm   

for hack

**Comment by maciaszczykm** [comment]
@hwdef Thanks. Can you assign someone to /approve?

**Comment by hwdef** [comment]
@maciaszczykm 

Yes,I try to contact other people, there will be results tomorrow.

**Review by SataQiu — APPROVED** [review]
Thanks!
/approve
for hack

**Pull request merged**
