### PR TITLE
changelog-1.22:Fix notes of PR 101151

### PR DESCRIPTION
**Pull request by mysunshine92**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
@kubernetes/sig-release-leads PTAL fixes an issue in 1.22 changelog

**Review by justaugustus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
