### PR TITLE
Use protobuf for kubectl top

### PR DESCRIPTION
**Pull request by serathius**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Encoding JSON takes around 30% of CPU and 15% of memory used by Metrics Server. Switching to proto will allow large savings in resources needed for MS. 

```release-note
kubect: Added --use-protocol-buffers flag to kubectl top pods and nodes
```

### CODE REVIEW

**Comment by brianpursley** [comment]
This seems like it would be ok, but we don't set content type anywhere else in kubectl currently.  Maybe a topic for the next sig-cli meeting.

/cc @soltysh

**Comment by serathius** [comment]
kubectl uses normally generic client that doesn't support proto. `kubectl top` is only exception that I know that it uses concrete client.

**Comment by soltysh** [comment]
> kubectl uses normally generic client that doesn't support proto. `kubectl top` is only exception that I know that it uses concrete client.

That's not necessarily true, we're not using generic client any more at least. Most commands create ad-hoc client which has all the necessary capabilities including support for proto, if needed.

@serathius what is the benefit for kubectl users behind this change?

**Comment by soltysh** [comment]
> This seems like it would be ok, but we don't set content type anywhere else in kubectl currently. Maybe a topic for the next sig-cli meeting.

Yeah, it's a good topic to have.

**Comment by serathius** [comment]
> @serathius what is the benefit for kubectl users behind this change?

Switching from JSON to proto allows Metrics Server to save around 30% of CPU and 15% of memory used. By saving on JSON encoding we plan to improve freshness of metrics, from 1 minute to 15 seconds. With this we both improve autoscaling quality and usefulness of `kubectl top`.

**Comment by dougsland** [comment]
Note from SIG-CLI meeting:
This change will require a flag option in kubectl and a warning message that in the next release it will be enabled by default. Other than that people is exited about this change.

@soltysh @serathius please let me know if I missed anything.

**Review by dougsland — COMMENTED** [review]
Note from SIG-CLI meeting:
This change will require a flag option in kubectl and a warning message that in the next release it will be enabled by default. Other than that people is exited about this change.

@soltysh @serathius please let me know if I missed anything.

**Comment by serathius** [comment]
ping @soltysh

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
