### PR TITLE
[WIP] Add --checkpoint to drain

### PR DESCRIPTION
**Pull request by adrianreber**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This PR implements `--checkpoint` on drain. This means that Pods can be checkpointed instead of being killed when draining a node, so that the Pods can be restored later with the same state. This is especially, maybe only, interesting for stateful containers which need a long time to start up (Java), need to load a lot of data from storage (database), or for other stateful containers without a storage backend.

The basic steps to use this would look something like this:

 * `kubectl drain 127.0.0.1 --checkpoint`
 * `reboot`
 * Restart kubelet (and restore all checkpointed containers)

This PR does not yet implement the restore part. The corresponding CRI-O implementation to support checkpoint/restore already implements checkpointing **and** restoring of Pods, but it has not been added to this PR, yet.

The motivation behind this PR is to implement Pod migration and in a way it is almost possible with the changes in this PR. The checkpoints created during `drain --checkpoint` can be copied to another node and upon kubelet start the Pods should be restored there. The motivation to start with the `drain` use case is that it seems to be one of the simpler starting points to introduce checkpoint/restore/migrate into Kubernetes as it is a manual and user triggered operation only concerning a single node so far.

This is heavily inspired by Jakob Schrettenbrunner's work referenced in #3949

This PR is pretty large, but my initial approach to go in small steps and just add the necessary changes to the CRI API (https://github.com/kubernetes/enhancements/pull/1990) feels kind of stuck because it was not possible to see all the implications of adding checkpoint/restore to the CRI API. So this is kind of the other extreme, a really large PR which shows all necessary changes to implement a subset of the possibilities checkpoint/restore offers.

**Which issue(s) this PR fixes**:
Maybe https://github.com/kubernetes/kubernetes/issues/3949

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
This adds the parameter --checkpoint to kubectl drain
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**

 - KEP: https://github.com/kubernetes/enhancements/pull/1990
 - CRI-O: https://github.com/cri-o/cri-o/pull/4199
 - crictl: https://github.com/kubernetes-sigs/cri-tools/pull/662

### CODE REVIEW

**Comment by sftim** [comment]
@adrianreber, it looks like the Checkpoint subresource is in the `policy` API group. Why that group?

**Comment by adrianreber** [comment]
> @adrianreber, it looks like the Checkpoint subresource is in the `policy` API group. Why that group?

I was following the eviction code path. So wherever I saw eviction I replicated it for checkpoint to go from kubectl to the api server to the kubelet.

**Comment by adrianreber** [comment]
Please also see https://github.com/kubernetes/kubernetes/pull/97689

I split out the CRI API changes from this PR into https://github.com/kubernetes/kubernetes/pull/97689 for easier review. Especially for the discussions in https://github.com/kubernetes/enhancements/pull/1990

**Comment by adrianreber** [comment]
Rebased and force updated. This is now the code I used in my video demoing this feature: https://people.redhat.com/~areber/2021-01-29-kubectl-drain-checkpoint.mp4

**Comment by adrianreber** [comment]
Rebased and force updated.

This is now using a newly introduced CRI experimental API as discussed in yesterday's sig node meeting.

Also see https://github.com/kubernetes/kubernetes/pull/97689

**Comment by yimin-zhao** [comment]
Hi, @adrianreber, I have watched our demo video, it's awesome! Recently I am trying to reproduce your work on my local machines. Here I have two questions:
1. Base on your demo video, once pod is registered in `/var/lib/kubelet/checkpoints/checkpointed.pods`, later when kubelet restarts, it will restore the pod automatically. (I know in your code, you use `TerminationMessagePath` as a maker to decide whether to restore a pod, but pardon me for not fully understanding.) So I wonder, what if I simple restart the kubelet after run `drain --checkpoint` on one node, so I found kubelet is keeping trying to restore the checkpointed pod, and crio also keeps reporting error `name is reserved`.
2. Then I try to scp the tar file to another node and restart the kubelet, And I find criu now returns errors
```
f6a455635ac513f2b9ce127e9cc25e00d3c4864e50cdd33e.scope to /system.slice/crio-487ef3f1c9e0c56d3764f3893c433f796375beb2fd8674af1f403f91f4f3ff87.scope
(00.036358) cg: rewriting kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod7e0e25c3_e634_4abd_a3e2_523244d323e2.slice/crio-6a4d5fc42876c344f6a455635ac513f2b9ce127e9cc25e00d3c4864e50cdd33e.scope to /system.slice/crio-487ef3f1c9e0c56d3764f3893c433f796375beb2fd8674af1f403f91f4f3ff87.scope
(00.036359) cg: Preparing cgroups yard (cgroups restore mode 0x4)
(00.036533) cg: Opening .criu.cgyard.jstrwF as cg yard
(00.036541) cg:         Making controller dir .criu.cgyard.jstrwF/pids (pids)
(00.036754) cg: Determined cgroup dir pids//system.slice/crio-487ef3f1c9e0c56d3764f3893c433f796375beb2fd8674af1f403f91f4f3ff87.scope already exist
(00.036757) cg: Skip restoring properties on cgroup dir pids//system.slice/crio-487ef3f1c9e0c56d3764f3893c433f796375beb2fd8674af1f403f91f4f3ff87.scope
(00.036773) cg:         Making controller dir .criu.cgyard.jstrwF/cpuset (cpuset)
(00.036909) cg: Determined cgroup dir cpuset//system.slice/crio-487ef3f1c9e0c56d3764f3893c433f796375beb2fd8674af1f403f91f4f3ff87.scope already exist
(00.036911) cg: Skip restoring properties on cgroup dir cpuset//system.slice/crio-487ef3f1c9e0c56d3764f3893c433f796375beb2fd8674af1f403f91f4f3ff87.scope
(00.036919) cg:         Making controller dir .criu.cgyard.jstrwF/net_cls (net_cls)
(00.037041) Error (criu/cgroup.c:1817): cg:     Can't mount controller dir .criu.cgyard.jstrwF/net_cls: Device or resource busy
```

For question 1, I know it may be a feature/by-design, but if kubelet can really restore the pod on the same node, it's more like a kubernetes' checkpoint/restore. For question 2, I wonder that have you ever seen this error before? Any information or clue will be helpful.

Regards.

**Comment by adrianreber** [comment]
> Hi, @adrianreber, I have watched our demo video, it's awesome! Recently I am trying to reproduce your work on my local machines. Here I have two questions:
> 
>     1. Base on your demo video, once pod is registered in `/var/lib/kubelet/checkpoints/checkpointed.pods`, later when kubelet restarts, it will restore the pod automatically. (I know in your code, you use `TerminationMessagePath` as a maker to decide whether to restore a pod, but pardon me for not fully understanding.) So I wonder, what if I simple restart the kubelet after run `drain --checkpoint` on one node, so I found kubelet is keeping trying to restore the checkpointed pod, and crio also keeps reporting error `name is reserved`.

Not sure I understand your question correctly, but I think the problem you describe does not exist if you do a reboot or a `crictl rmp -fa` to make sure the checkpointed containers are removed from CRI-O. The problem you describe could be related that there is still some container/pod metadata around and restoring fails if the name already exists.

This probably means that this PR still requires some clean up after `drain --checkpoint` to completely remove all remains of the checkpointed pods after `drain`.

>     2. Then I try to scp the tar file to another node and restart the kubelet, And I find criu now returns errors
> 
> 
> ```
> f6a455635ac513f2b9ce127e9cc25e00d3c4864e50cdd33e.scope to /system.slice/crio-487ef3f1c9e0c56d3764f3893c433f796375beb2fd8674af1f403f91f4f3ff87.scope
> (00.036358) cg: rewriting kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod7e0e25c3_e634_4abd_a3e2_523244d323e2.slice/crio-6a4d5fc42876c344f6a455635ac513f2b9ce127e9cc25e00d3c4864e50cdd33e.scope to /system.slice/crio-487ef3f1c9e0c56d3764f3893c433f796375beb2fd8674af1f403f91f4f3ff87.scope
> (00.036359) cg: Preparing cgroups yard (cgroups restore mode 0x4)
> (00.036533) cg: Opening .criu.cgyard.jstrwF as cg yard
> (00.036541) cg:         Making controller dir .criu.cgyard.jstrwF/pids (pids)
> (00.036754) cg: Determined cgroup dir pids//system.slice/crio-487ef3f1c9e0c56d3764f3893c433f796375beb2fd8674af1f403f91f4f3ff87.scope already exist
> (00.036757) cg: Skip restoring properties on cgroup dir pids//system.slice/crio-487ef3f1c9e0c56d3764f3893c433f796375beb2fd8674af1f403f91f4f3ff87.scope
> (00.036773) cg:         Making controller dir .criu.cgyard.jstrwF/cpuset (cpuset)
> (00.036909) cg: Determined cgroup dir cpuset//system.slice/crio-487ef3f1c9e0c56d3764f3893c433f796375beb2fd8674af1f403f91f4f3ff87.scope already exist
> (00.036911) cg: Skip restoring properties on cgroup dir cpuset//system.slice/crio-487ef3f1c9e0c56d3764f3893c433f796375beb2fd8674af1f403f91f4f3ff87.scope
> (00.036919) cg:         Making controller dir .criu.cgyard.jstrwF/net_cls (net_cls)
> (00.037041) Error (criu/cgroup.c:1817): cg:     Can't mount controller dir .criu.cgyard.jstrwF/net_cls: Device or resource busy
> ```
> 
> For question 1, I know it may be a feature/by-design, but if kubelet can really restore the pod on the same node, it's more like a kubernetes' checkpoint/restore. 

Sorry, I don't understand this comment.

> For question 2, I wonder that have you ever seen this error before? Any information or clue will be helpful.

This seems to be a CRIU problem because the cgroups are configured differently on the different nodes. Do your nodes differ? Is there a different kernel or OS running on those two systems. See https://github.com/checkpoint-restore/criu/issues/453  where something like this has been discussed.

**Comment by yimin-zhao** [comment]
> Not sure I understand your question correctly, but I think the problem you describe does not exist if you do a reboot or a `crictl rmp -fa` to make sure the checkpointed containers are removed from CRI-O. The problem you describe could be related that there is still some container/pod metadata around and restoring fails if the name already exists.
> 
> This probably means that this PR still requires some clean up after `drain --checkpoint` to completely remove all remains of the checkpointed pods after `drain`.

I tried `crictl rmp -fa` and restart crio, not working, I will try to reboot later.

> This seems to be a CRIU problem because the cgroups are configured differently on the different nodes. Do your nodes differ? Is there a different kernel or OS running on those two systems. See [checkpoint-restore/criu#453](https://github.com/checkpoint-restore/criu/issues/453) where something like this has been discussed.

I have two VMs, CentOS 7.9 and CentOS 8.3. Thanks for the link, I'll go to check.

**Comment by adrianreber** [comment]
> > Not sure I understand your question correctly, but I think the problem you describe does not exist if you do a reboot or a `crictl rmp -fa` to make sure the checkpointed containers are removed from CRI-O. The problem you describe could be related that there is still some container/pod metadata around and restoring fails if the name already exists.
> > This probably means that this PR still requires some clean up after `drain --checkpoint` to completely remove all remains of the checkpointed pods after `drain`.
> 
> I tried `crictl rmp -fa` and restart crio, not working, I will try to reboot later.

Not sure. Maybe it is still a misunderstanding. Not sure what your problem is.

> > This seems to be a CRIU problem because the cgroups are configured differently on the different nodes. Do your nodes differ? Is there a different kernel or OS running on those two systems. See [checkpoint-restore/criu#453](https://github.com/checkpoint-restore/criu/issues/453) where something like this has been discussed.
> 
> I have two VMs, CentOS 7.9 and CentOS 8.3. Thanks for the link, I'll go to check.

Ah, that does not sound like a good idea. In theory it can work, but I would recommend to do migrations only using the same Linux distribution. From CentOS 8.x to another 8.x should work. 7.x to 8.x is ambitious.

**Comment by yimin-zhao** [comment]
> > I tried `crictl rmp -fa` and restart crio, not working, I will try to reboot later.
> 
> Not sure. Maybe it is still a misunderstanding. Not sure what your problem is.

After I rebooted the machine, it seems that crio will do cleanup work for the invalid containers info, it's good and the error "name is reversed" is also gone. Now the crio will hange if criu return errors, I have to restart crio manaually ;) 
BTW, Can you help to look at this error?

```
(00.082412)      1: mnt: Start with 0:/tmp/.criu.mntns.JdF1zc
(00.082511)      1: mnt: Start with 0:/tmp/.criu.mntns.JdF1zc
(00.082855)      1: mnt: Start with 0:/tmp/.criu.mntns.JdF1zc
(00.082863)      1: mnt:        Mounting overlay @/tmp/.criu.mntns.JdF1zc/13-0000000000/ (0)
(00.082979)      1: mnt: 646:/tmp/.criu.mntns.JdF1zc/13-0000000000/ private 1 shared 0 slave 0
(00.083766)      1: mnt:        Mounting tmpfs @/tmp/.criu.mntns.JdF1zc/13-0000000000/etc/resolv.conf (0)
(00.083774)      1: mnt:        Bind /var/run/containers/storage/overlay-containers/f8dec854a2b2f9e6f995eef8ecddff3547b94bdf3b49288f65f8a27dd54f7ecf/userdata/resolv.conf to /tmp/.criu.mntns.JdF1zc/13-0000000000/etc/resolv.conf
(00.084038)      1: mnt: 665:/tmp/.criu.mntns.JdF1zc/13-0000000000/etc/resolv.conf private 0 shared 0 slave 1
(00.084509)      1: mnt:        Mounting tmpfs @/tmp/.criu.mntns.JdF1zc/13-0000000000/etc/hostname (0)
(00.084517)      1: mnt:        Bind /var/run/containers/storage/overlay-containers/f8dec854a2b2f9e6f995eef8ecddff3547b94bdf3b49288f65f8a27dd54f7ecf/userdata/hostname to /tmp/.criu.mntns.JdF1zc/13-0000000000/etc/hostname
(00.085049)      1: mnt: 666:/tmp/.criu.mntns.JdF1zc/13-0000000000/etc/hostname private 0 shared 0 slave 1
(00.085877)      1: mnt:        Mounting unsupported @/tmp/.criu.mntns.JdF1zc/13-0000000000/etc/hosts (0)
(00.085888)      1: mnt:        Bind /var/lib/kubelet/pods/5b2ff449-a263-46da-837e-2259b0ad4c5b/etc-hosts to /tmp/.criu.mntns.JdF1zc/13-0000000000/etc/hosts
(00.086137)      1: mnt: 667:/tmp/.criu.mntns.JdF1zc/13-0000000000/etc/hosts private 1 shared 0 slave 0
(00.086339)      1: mnt:        Mounting tmpfs @/tmp/.criu.mntns.JdF1zc/13-0000000000/run/secrets (0)
(00.086345)      1: mnt:        Bind /var/run/containers/storage/overlay-containers/dc317d4c718650aa5b2b2ba68b4c9fb17505a246b7ce7a77c115192f42c71821/userdata/run/secrets to /tmp/.criu.mntns.JdF1zc/13-0000000000/run/secrets
(00.086539)      1: mnt: 669:/tmp/.criu.mntns.JdF1zc/13-0000000000/run/secrets private 1 shared 0 slave 0
(00.086799)      1: mnt:        Mounting tmpfs @/tmp/.criu.mntns.JdF1zc/13-0000000000/run/secrets/kubernetes.io/serviceaccount (0)
(00.087049)      1: Error (criu/mount.c:2033): mnt: Unable to mount tmpfs /tmp/.criu.mntns.JdF1zc/13-0000000000/run/secrets/kubernetes.io/serviceaccount (id=670): No such file or directory
(00.087063)      1: Error (criu/mount.c:2098): mnt: Can't mount at /tmp/.criu.mntns.JdF1zc/13-0000000000/run/secrets/kubernetes.io/serviceaccount: No such file or directory
(00.087069)      1: mnt: Start with 0:/tmp/.criu.mntns.JdF1zc
(00.160017) Error (criu/mount.c:3396): mnt: Can't remove the directory /tmp/.criu.mntns.JdF1zc: Device or resource busy
(00.160043) Error (criu/cr-restore.c:2483): Restoring FAILED.
```
```
journalctl  -u crio
...
"Container creation error: time=\"2021-03-09T17:20:00+08:00\" level=warning msg=\"lstat /sys/fs/cgroup/devices/system.slice/crio-dc317d4c7505a246b7ce7a77c115192f42c71821.scope: no such file or directory\"\ntime=\"2021-03-09T17:20:00+08:00\" level=error msg=\"criu failed: type NOTIFY errno 0\\nlog file: /var/run/containers/storage/overlay-containers//dc317d4c718650aa5b2b2ba68b4c9fb17505a246b7ce7a77c115192f42c71821/userdata/restore.log\"\n"
```

> > I have two VMs, CentOS 7.9 and CentOS 8.3. Thanks for the link, I'll go to check.
> 
> Ah, that does not sound like a good idea. In theory it can work, but I would recommend to do migrations only using the same Linux distribution. From CentOS 8.x to another 8.x should work. 7.x to 8.x is ambitious.

My situation is almost identical to your link content, I guess I need to find another vm for this operation.

Thanks.

**Comment by adrianreber** [comment]
You need the latest version of runc with https://github.com/opencontainers/runc/pull/2798

**Comment by yimin-zhao** [comment]
> You need the latest version of runc with [opencontainers/runc#2798](https://github.com/opencontainers/runc/pull/2798)

Cool! I didn't know this pull request before.

**Comment by yimin-zhao** [comment]
@adrianreber Hi, I recently are working on a prototype that using dax with this pull request. And when I reboot `kubelet` and the criu does restore, I got this error, 
```
Opening 0x000001c1e00000-0x000001c2000000 0x000000e5e00000 (81) vma
(00.149951)      1: Opening file dev/dax0.0
(00.149953)      1: dev permission: rwx r-x r-x dev/dax0.0 permission: rwx rwx rwx
(00.149959)      1: current working dir: /
(00.149966)      1: owner: root
(00.149970)      1: current user: root
(00.149970)      1: group: root
(00.149975)      1: Error: Can't open file dev/dax0.0 on restore1: Operation not permitted
(00.149977)      1: Error: Can't open file dev/dax0.0: Operation not permitted
(00.149978)      1: Error: `- Can't open vma
```
The dax file was mapped through the yaml file, In this container, the process will open the dax and call `map()` on it. The dax's owner on host is root and permission was set to 777. However, when criu open this file, as you can see, it got error `Operation not permitted`. I also disabled the `selinux` and still don't know what's going on. Do you have any ideas? 
I found `seccomp` can block some syscalls, and return EPERM if the syscall is in the blacklist, is this relevant to my issue?

Thank you very much.

**Comment by adrianreber** [comment]
> @adrianreber Hi, I recently are working on a prototype that using dax with this pull request. And when I reboot `kubelet` and the criu does restore, I got this error,
> 
> ```
> Opening 0x000001c1e00000-0x000001c2000000 0x000000e5e00000 (81) vma
> (00.149951)      1: Opening file dev/dax0.0
> (00.149953)      1: dev permission: rwx r-x r-x dev/dax0.0 permission: rwx rwx rwx
> (00.149959)      1: current working dir: /
> (00.149966)      1: owner: root
> (00.149970)      1: current user: root
> (00.149970)      1: group: root
> (00.149975)      1: Error: Can't open file dev/dax0.0 on restore1: Operation not permitted
> (00.149977)      1: Error: Can't open file dev/dax0.0: Operation not permitted
> (00.149978)      1: Error: `- Can't open vma
> ```
> 
> The dax file was mapped through the yaml file, In this container, the process will open the dax and call `map()` on it. The dax's owner on host is root and permission was set to 777. However, when criu open this file, as you can see, it got error `Operation not permitted`. I also disabled the `selinux` and still don't know what's going on. Do you have any ideas?
> I found `seccomp` can block some syscalls, and return EPERM if the syscall is in the blacklist, is this relevant to my issue?

CRIU restores seccomp, so seccomp should not be a problem. Not sure if the mapping from the yaml file does something special with the device in the container. Not sure what dax is, but devices and CRIU are not always easy, because there might be some device state which is not correctly restored. Sorry, cannot help you with this.

**Comment by yiminmv** [comment]
> CRIU restores seccomp, so seccomp should not be a problem. Not sure if the mapping from the yaml file does something special with the device in the container. Not sure what dax is, but devices and CRIU are not always easy, because there might be some device state which is not correctly restored. Sorry, cannot help you with this.

I have some clues about this issue: the key is that I create the container as privileged (I know it's not a good idea) and when do restore, it lost this information. So may I ask that what makes you didn't dump this option? Is this a bug or is there something you are concerning about?

**Comment by adrianreber** [comment]
> > CRIU restores seccomp, so seccomp should not be a problem. Not sure if the mapping from the yaml file does something special with the device in the container. Not sure what dax is, but devices and CRIU are not always easy, because there might be some device state which is not correctly restored. Sorry, cannot help you with this.
> 
> I have some clues about this issue: the key is that I create the container as privileged (I know it's not a good idea) and when do restore, it lost this information. So may I ask that what makes you didn't dump this option? Is this a bug or is there something you are concerning about?

This can be a bug, right. Not sure what is missing. seccomp and selinux should be handled correctly.

**Comment by yiminmv** [comment]
> > I have some clues about this issue: the key is that I create the container as privileged (I know it's not a good idea) and when do restore, it lost this information. So may I ask that what makes you didn't dump this option? Is this a bug or is there something you are concerning about?
> 
> This can be a bug, right. Not sure what is missing. seccomp and selinux should be handled correctly.
Please look at this: https://github.com/cri-o/cri-o/blob/master/pkg/container/container.go#L345
and here is the only way to set a container as privileged: 
https://github.com/cri-o/cri-o/blob/master/server/container_create_linux.go#L138

**Comment by dims** [comment]
please reopen when you are able to rebase and make progress. thanks!

**Pull request closed without merging**
