### PR TITLE
Describers with pod templates should have consistent output

### LINKED ISSUE #38698: Deployment description lacks basic info
Misses the image I run, we can argue about more fields too
```
$ kc describe deploy
Name:			nginx
Namespace:		default
CreationTimestamp:	Tue, 13 Dec 2016 14:54:23 +0100
Labels:			name=nginx-undo
Selector:		name=nginx-undo
Replicas:		2 updated | 842354255776 total | 2 available | 2 unavailable
StrategyType:		RollingUpdate
MinReadySeconds:	0
RollingUpdateStrategy:	1 max unavailable, 1 max surge
Conditions:
  Type		Status	Reason
  ----		------	------
  Available 	True	MinimumReplicasAvailable
OldReplicaSets:	nginx-2812786133 (0/842353733888 replicas created), nginx-3142235609 (0/842353338192 replicas created), nginx-3224745434 (0/842353205456 replicas created), nginx-3389568476 (0/842353077040 replicas created), nginx-3719214560 (0/842352825968 replicas created), nginx-3472012765 (0/842352977168 replicas created), nginx-3554522590 (0/842352983344 replicas created), nginx-3225007578 (0/842353207792 replicas created), nginx-3307255259 (0/842353211664 replicas created), nginx-3554325982 (0/842352981216 replicas created), nginx-3554391518 (0/842352981888 replicas created), nginx-3801593313 (0/842352648352 replicas created), nginx-2895164886 (0/842353736848 replicas created), nginx-314819091 (2/842353341736 replicas created), nginx-3224876506 (0/842353206624 replicas created), nginx-3389765084 (0/842353079280 replicas created), nginx-3471947229 (0/842352976640 replicas created), nginx-3142497753 (0/842353340608 replicas created), nginx-3389371868 (0/842353075296 replicas created), nginx-3472143837 (0/842352978496 replicas created), nginx-3636704735 (0/842352821328 replicas created), nginx-3636835807 (0/842352822656 replicas created), nginx-3224614362 (0/842353343440 replicas created), nginx-3719083488 (0/842352824736 replicas created), nginx-3636770271 (0/842352822096 replicas created), nginx-3883972066 (0/842352650160 replicas created), nginx-3060119000 (0/842353337088 replicas created), nginx-3224810970 (0/842353206032 replicas created), nginx-3306993115 (0/842353209440 replicas created), nginx-3472078301 (0/842352977920 replicas created), nginx-3554194910 (0/842352979760 replicas created), nginx-3307386331 (0/842353212912 replicas created), nginx-3389634012 (0/842353077616 replicas created), nginx-3554457054 (0/842352982512 replicas created)
NewReplicaSet:	nginx-3966416355 (2/842352651248 replicas created)
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  4m		4m		1	{deployment-controller }		Normal		ScalingReplicaSet	Scaled up replica set nginx-314819091 to 3
  3m		3m		1	{deployment-controller }		Normal		ScalingReplicaSet	Scaled up replica set nginx-3189421475 to 1
  3m		3m		1	{deployment-controller }		Normal		ScalingReplicaSet	Scaled down replica set nginx-314819091 to 2
  3m		3m		1	{deployment-controller }		Normal		ScalingReplicaSet	Scaled up replica set nginx-3189421475 to 2
  3m		3m		1	{deployment-controller }		Normal		ScalingReplicaSet	Scaled down replica set nginx-3189421475 to 0
  3m		3m		1	{deployment-controller }		Normal		ScalingReplicaSet	Scaled up replica set nginx-3271800228 to 2
  3m		3m		1	{deployment-controller }		Normal		ScalingReplicaSet	Scaled down replica set nginx-3271800228 to 0
  3m		3m		1	{deployment-controller }		Normal		ScalingReplicaSet	Scaled up replica set nginx-3354178981 to 2
  3m		3m		1	{deployment-controller }		Normal		ScalingReplicaSet	Scaled down replica set nginx-3354178981 to 0
  3m		1s		171	{deployment-controller }		Normal		ScalingReplicaSet	(events with common reason combined)
```
@kubernetes/kubectl @kubernetes/sig-cli @kubernetes/deployment

### PR DESCRIPTION
**Pull request by smarterclayton**
Added a test to verify it.

Fixes #38698

### CODE REVIEW

**Comment by smarterclayton** [comment]
@kubernetes/sig-apps-pr-reviews @kubernetes/sig-cli-pr-reviews

**Comment by smarterclayton** [comment]
Um... we don't do this for stateful sets either, fixing it there.

**Comment by smarterclayton** [comment]
Um.  All of our PodTemplate describers are inconsistent.  ...............

**Comment by smarterclayton** [comment]
I'm going to fix the rest of the describers while i'm in here - this is pretty inconsistent.

**Comment by smarterclayton** [comment]
So summary of changes here:

1. All objects with a pod template use a consistent pod template
2. Remove the images field - redundant with pod template (wasn't showing init containers)
3. Do a better job of aligning some extra columns
4. Include volume claim templates in stateful set describer
5. Make sure labels and annotations fields are in the right spot.

I notice that we are now wildly inconsistent with use of `CamelCase` vs `Camel Case` field labels - I'm not going to change one or the other right now, but we should start enforcing much stronger reviews on these for consistency.

**Comment by smarterclayton** [comment]
Rebased due to storage classes being added

**Comment by smarterclayton** [comment]
@k8s-bot cvm gke e2e test this
@k8s-bot gci gke e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot node e2e test this

**Comment by fabianofranz** [comment]
@k8s-bot gci gke e2e test this
@k8s-bot cvm gke e2e test this

**Pull request merged**
