### PR TITLE
Adding a retry and traceroute to the master version checking

### PR DESCRIPTION
**Pull request by krousey**
This is hitting a lot of connection refused errors in the e2e upgrade tests. We should make this more robust in case this is intermittent network errors. In the event of an error, attempt to log a traceroute to the master.

cc @kubernetes/sig-cluster-lifecycle-bugs @dchen1107 

#47379

### CODE REVIEW

**Comment by roberthbailey** [comment]
@krousey - please link the upgrade test failure issue to appease the bot.

**Comment by luxas** [comment]
/retest

I assume this should be cherrypicked into v1.7 in order to get upgrade tests more stable?

**Review by luxas — APPROVED** [review]

**Comment by luxas** [comment]
@dchen1107 Can I add v1.7 milestone?

**Comment by krousey** [comment]
I added traceroute to this PR and attached an issue. Please take another look.

**Comment by dchen1107** [comment]
@krousey I think we don't need this to cherrypick into 1.7 branch. I believe the same problem in previous release, and in 1.7, thus still in master branch. If this can help that issue, we can cherrypick the real fix based on your test results from 1.6->master upgrade.

**Pull request merged**
