### PR TITLE
Migrated remaining lines of `server.go` and `csi.go` to structured logging

### PR DESCRIPTION
**Pull request by shivanshuraj1333**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
added missing migration points

#### Which issue(s) this PR fixes:

Ref: https://github.com/kubernetes/kubernetes/issues/105841

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by shivanshu1333** [comment]
looking for LGTM from @pohly / @serathius

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by pohly** [comment]
/assign @ahg-g

For approval.

**Pull request merged**
