### PR TITLE
Multiarch manifest for volume-tester docker images

### LINKED ISSUE #48376: Make test/images/volumes-tester multiarch
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
This issue is to track work to convert test/images/volumes-tester to multi architecture.

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/kubernetes/issues/48376

**Special notes for your reviewer**:
@dims @luxas 

Changes made:
- Removed the ceph folder which is not used anymore and merged into rbd image
- Converted following images multi-arch:
```
volume/gluster
volume/iscsi
volume/nfs
volume/rbd
```

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mkumatag** [comment]
@cjwagner please help me pushing following 3 images from this PR:

```shell
$ make all-push WHAT=volume/gluster
$ make all-push WHAT=volume/iscsi
$ make all-push WHAT=volume/nfs
$ make all-push WHAT=volume/rbd
```

**Comment by dims** [comment]
@mkumatag looks like @ixdy is on call this week https://storage.googleapis.com/kubernetes-jenkins/oncall.html so we can wait for him to get active (west coast time i believe)

@mkumatag - we should probably separate test/utils/image/manifest.go into another PR. i'd like the jobs here to be green before we request the images to be built.

**Comment by mkumatag** [comment]
> @mkumatag looks like @ixdy is on call this week https://storage.googleapis.com/kubernetes-jenkins/oncall.html so we can wait for him to get active (west coast time i believe)
> 
> @mkumatag - we should probably separate test/utils/image/manifest.go into another PR. i'd like the jobs here to be green before we request the images to be built.

@dims Currently we don't have a way to validate the changes in `test/images` folder, only way is to build them, push and use them in the test to make sure things are working.

In this case, it does make sense to have all the changes in PR because if something gets failed with new images, we can modify/edit the changes in the same PR and push again the changes.

I don't want to merge the code of `test/images` folder without validating the images built.

@ixdy what do you say?

**Comment by dims** [comment]
Ah good point @mkumatag let's leave it to @ixdy

**Comment by dims** [comment]
related to https://github.com/kubernetes/kubernetes/issues/66986

**Comment by spiffxp** [comment]
/assign
@dims reached out to me on slack, I'll see if I can run the make commands

**Comment by spiffxp** [comment]
logs: https://gist.github.com/spiffxp/1eb3d6356b37c8549fe0db8b045aac79

**Comment by dims** [comment]
thanks a ton @spiffxp 

/retest

**Comment by spiffxp** [comment]
/retest
all four pushed

**Comment by ixdy** [comment]
attempting to build/push these images now.

**Pull request merged**
