### PR TITLE
deflake TestPatch by waiting for cache

### LINKED ISSUE #39471: TestPatch {client}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-test-go/1808/
Failed: TestPatch {client}

```
client_test.go:282: Failed updating patchpod with patch type application/merge-patch+json: Operation cannot be fulfilled on pods "patchpod": <nil>
```

### PR DESCRIPTION
**Pull request by deads2k**
Fixes #39471

Rather than retry on conflicts for an unknown number of times, we have the resource version after the previous patch and we can use that to wait for a GET response that is at least as current as that resourceVersion.

@kubernetes/sig-api-machinery-pr-reviews @liggitt @wojtek-t

### CODE REVIEW

**Comment by deads2k** [comment]
@k8s-bot kops aws e2e test this

**Comment by liggitt** [comment]
Why wouldn't we fix the bug in guaranteed update? This means all clients would have to do the same thing, right?

**Comment by deads2k** [comment]
> Why wouldn't we fix the bug in guaranteed update? This means all clients would have to do the same thing, right?

What bug?  Retrying with live data?  Doesn't help here because the first one that patch sees is used to decide if the object has changed in a conflicting way.  Most of the time, this is correct for patch.  With this test, not so much.

**Comment by deads2k** [comment]
opened https://github.com/kubernetes/kubernetes/issues/42644

**Comment by deads2k** [comment]
doesn't interact with other changes, isolated to test behavior. retest not required.

**Pull request merged**
