### PR TITLE
Automated cherry pick of #106827: apf: ensure exempt request notes the classification

### LINKED ISSUE #106826: apf: exempt request does not note flowschema and prioritylevelconfiguration in the response header
### What happened?

In Priority and Fairness, exempt request does not note `flowschema` and `prioritylevelconfiguration` in the response header.

```
$ kubectl version --v=10
I1203 10:51:20.707201   76091 loader.go:372] Config loaded from file:  /tmp/iwejiofejwpoifjiowepfjiopewjfiopwejofewjpiofewjiopfwejiopfeijowjoipewwe
I1203 10:51:20.711092   76091 round_trippers.go:435] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.21.0 (darwin/amd64) kubernetes/cb303e6" '<redacted>/version?timeout=32s'
I1203 10:51:21.057483   76091 round_trippers.go:454] GET <redacted>/version?timeout=32s 200 OK in 346 milliseconds
I1203 10:51:21.057506   76091 round_trippers.go:460] Response Headers:
I1203 10:51:21.057512   76091 round_trippers.go:463]     Audit-Id: f6a22fb1-0895-4180-bc1d-d8563506e749
I1203 10:51:21.057517   76091 round_trippers.go:463]     Cache-Control: no-cache, private
I1203 10:51:21.057520   76091 round_trippers.go:463]     Content-Type: application/json
I1203 10:51:21.057523   76091 round_trippers.go:463]     Content-Length: 273
I1203 10:51:21.057527   76091 round_trippers.go:463]     Date: Fri, 03 Dec 2021 16:51:21 GMT
I1203 10:51:21.089022   76091 request.go:1123] Response Body: {
  "major": "1",
  "minor": "23+",
  "gitVersion": "v1.23.0-rc.0",
  "gitCommit": "4084668283df9a88d3fc240195e6cd603b67f5db",
  "gitTreeState": "clean",
  "buildDate": "2021-11-24T12:55:48Z",
  "goVersion": "go1.17.3",
  "compiler": "gc",
  "platform": "linux/amd64"
}
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.0-rc.0", GitCommit:"4084668283df9a88d3fc240195e6cd603b67f5db", GitTreeState:"clean", BuildDate:"2021-11-24T12:55:48Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.23) exceeds the supported minor version skew of +/-1
```

We’re missing `X-Kubernetes-Pf-Flowschema-Uid` and `X-Kubernetes-Pf-Prioritylevel-Uid` from the response headers

### What did you expect to happen?

We expect the response headers  `X-Kubernetes-Pf-Flowschema-Uid` and `X-Kubernetes-Pf-Prioritylevel-Uid` to be present in the output.

```
I1203 10:47:24.009849   75978 round_trippers.go:463]     X-Kubernetes-Pf-Flowschema-Uid: 11c20f2c-ab85-484a-8bc2-67b43b7e9cfa
I1203 10:47:24.009853   75978 round_trippers.go:463]     X-Kubernetes-Pf-Prioritylevel-Uid: 029866d0-b946-4008-a133-58b94bc88c1e
```

### How can we reproduce it (as minimally and precisely as possible)?

- issue a request that is exempt in priority and fairness, configured kubeconfigs with with the user in `system:masters`
- and use verbosity `kubectl version --v=10`

### Kubernetes version

it's a regression, we see this in `1.23.0-rc.0`

### PR DESCRIPTION
**Pull request by tkashem**
Cherry pick of #106827 on release-1.23.

#106827: apf: ensure exempt request notes the classification

#### Which issue(s) this PR fixes:
Fixes #106826

```release-note
NONE
```

### CODE REVIEW

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm
Thanks!

**Comment by MikeSpreitzer** [comment]
@kubernetes/release-managers
This is ready for cherry-pick review.

**Comment by wojtek-t** [comment]
/lgtm
/approve

@kubernetes/release-managers - for cherrypick approval

**Comment by cpanato** [comment]
@tkashem @wojtek-t this is needed only for release 1.23 or do we also need to CP for 1.22/1.21/1.20? thanks!

**Comment by wojtek-t** [comment]
@cpanato  - this is regression in 1.23 - so only 1.23 cherrypick (this one) is needed - no others are needed.

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
