### PR TITLE
job controller: don't mutate shared cache object

### PR DESCRIPTION
**Pull request by adtac**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Cherry pick of https://github.com/kubernetes/kubernetes/pull/100553/commits/0a21157c96f5a06254f54416419e6abba93da7b3

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/100551

#### Special notes for your reviewer:

cc @ialidzhikov @alculquicondor @ahg-g 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig apps

### CODE REVIEW

**Comment by adtac** [comment]
(Not using the cherry_pick_pull.sh script becase that PR has more than just the bug fix; you can't select specific commits with that shell script.)

**Comment by ialidzhikov** [comment]
/assign @soltysh
for approval

**Comment by ialidzhikov** [comment]
ping @soltysh @ahg-g 
for approval

**Review by janetkuo — APPROVED** [review]

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
