### PR TITLE
Add pkg/printers OWNERS

### PR DESCRIPTION
**Pull request by smarterclayton**
Should also include more sig-api-machinery as this will be moving to server side

### CODE REVIEW

**Comment by smarterclayton** [comment]
@kubernetes/sig-cli-pr-reviews and @kubernetes/sig-api-machinery-pr-reviews for review of the owners list change

**Comment by deads2k** [comment]
lgtm

**Comment by fabianofranz** [comment]
lgtm

**Comment by AdoHe** [comment]
lgtm

**Comment by smarterclayton** [comment]
Merging so there are more approvers for 1.6 - no code change.

**Pull request merged**
