### PR TITLE
Fix many typos in both code and comments

### PR DESCRIPTION
**Pull request by tuanvc**
This PR fixes many typos in both code (eg: function name) and comments

### CODE REVIEW

**Comment by andrewsykim** [comment]
/kind cleanup 
/ok-to-test

@tuanvcw please add release notes in the PR description (even if it's "NONE")

**Comment by tuanvcw** [comment]
/release-note-none
Thank you very much, @andrewsykim 
Wish you a great day ahead :)

**Comment by tuanvcw** [comment]
Hi @andrewsykim, @freehan, @dashpole,
Have a nice day.
If there's anything else I could do to move this forward, please don't hesitate to let me know.
Thank you in advance :)

**Comment by tuanvcw** [comment]
Needs approved, lgtm labels.

**Comment by andrewsykim** [comment]
/lgtm

/assign @enisoc 
for approval

**Pull request merged**
