### PR TITLE
fix test cases expected

### PR DESCRIPTION
**Pull request by LexCC**
**What type of PR is this?**
> /kind failing-test

**What this PR does / why we need it**:
Fix the failing test.
Case[12] and Case[13] expected the result is not ipvs then kmods set invalid modules, but ``GetKernelVersionAndIPVSMods()`` func has set the correct loaded modules.
```
k8s.io/kubernetes/cmd/kube-proxy/app/server_others_test.go:144: Case[12] Expected "iptables", got "ipvs"
k8s.io/kubernetes/cmd/kube-proxy/app/server_others_test.go:144: Case[13] Expected "iptables", got "ipvs"
```
https://github.com/kubernetes/kubernetes/blob/61fa0fd44a3513b94d7c29ff859340804c107ea0/cmd/kube-proxy/app/server_others_test.go#L112-L127
https://github.com/kubernetes/kubernetes/blob/61fa0fd44a3513b94d7c29ff859340804c107ea0/pkg/util/ipvs/ipvs.go#L143-L147
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
@JieJhih 
thanks for the PR.
the CI seems to be failing because the new unit test doesn't seem to be passing?
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/76844/pull-kubernetes-bazel-test/1119357709129355265/

please have a look at the whole log.
thanks.

/kind failing-test
/priority backlog

**Comment by JieJhih** [comment]
@neolit123 I'm not sure is that caused by Jenkins system? Case[12] I can get ``ipvs`` but Jenkins get ``iptables``
Ref. https://github.com/kubernetes/kubernetes/blob/61fa0fd44a3513b94d7c29ff859340804c107ea0/pkg/util/ipvs/ipvs.go#L127-L150

**Comment by JieJhih** [comment]
@neolit123 
I figure out kmods is set by fakeKernelHandler. But there was a problem, if the os is not Linux kernel ipvsModules are empty, then the conditions will be skipped, return ipvs is true.
```
func (fake *fakeKernelHandler) GetModules() ([]string, error) {
	return fake.modules, nil
}
```
https://github.com/kubernetes/kubernetes/blob/b3847120241251d624d570e2212937c659614ea7/pkg/proxy/ipvs/proxier.go#L525-L555

**Comment by neolit123** [comment]
@JieJhih 
i haven't looked in the IPVS code that much, it's maintained by SIG Network.
you can try pinging them on slack at #sig-network but also try the #pr-reviews channel.

**Comment by danwinship** [comment]
this has been obsoleted by other fixes
/close

**Pull request closed without merging**
