### PR TITLE
test: fix NodeLogQuery tests to query the correct node for logs

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind failing-test
#### What this PR does / why we need it:
Currently, the test queries the local node, which is not correct for most kubernetes environments. Instead, ssh to the target node and call journalctl there

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by haircommander** [comment]
related to https://issues.redhat.com/browse/OCPBUGS-16760

**Review by mrunalp — APPROVED** [review]

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/priority important-soon
/approve

please file a bug to add those to some CI test definition

**Comment by aravindhp** [comment]
Thanks for fixing this @haircommander!

FYI @marosset @fabi200123

**Pull request merged**
