### PR TITLE
README.md: Update outdated links

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
the PR aims to update some links.
Some links with "#" would not redirect to right point of pages.
Other links without "#" can work, but they are outdated. I change them by the way.

**Special notes for your reviewer**:

**Release note**:

```release-note
```
none

### CODE REVIEW

**Comment by thockin** [comment]
/lgtm
/approve
@k8s-bot ok to test

**Comment by zhangxiaoyu-zidif** [comment]
@thockin could you remove "do not merge" label. Thanks.

**Pull request merged**
