### PR TITLE
Update GCE/debian to container-vm-v20150611

### PR DESCRIPTION
**Pull request by zmerlynn**
Updates:
- Docker 1.6.2
- /sys/fs/cgroup/memory/memory.use_hierarchy=1

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @dchen1107 @roberthbailey

**Comment by dchen1107** [comment]
LGTM.

**Comment by roberthbailey** [comment]
LGTM.

**Comment by zmerlynn** [comment]
@k8s-bot test this please

**Comment by zmerlynn** [comment]
FWIW, this has already accumulated a few green dots on the GKE side. (We flipped our CI already.)

**Comment by zmerlynn** [comment]
@k8s-bot test this please

**Comment by dchen1107** [comment]
Let's merge this one since @zmerlynn indicates it works with GKE already. Thanks!

**Pull request merged**
