### PR TITLE
remove experimental windows container hyper-v support with Docker

### LINKED ISSUE #94490: Remove alpha support for Hyper-v on Docker for Windows
**What happened**:
Hyper-v support was added as an [experimental feature via annotations](https://github.com/kubernetes/kubernetes/pull/58751) for docker.  Hyper-v support is now focused on Containerd because of better support of HCSv2 in Containerd (for example allows for multiple containers in a pod in hyper-v).

There is still annotation support that should be removed in all the various locations:

https://github.com/kubernetes/kubernetes/blob/9d9d305017d688526e179cee6af8791716c330df/pkg/kubelet/apis/well_known_annotations_windows.go#L36

**What you expected to happen**:
hyper-v support for docker will not go past alpha so the annotations should be depreciated following the guidelines at https://kubernetes.io/docs/reference/using-api/deprecation-policy/

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Windows
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig windows

### PR DESCRIPTION
**Pull request by wawa0210**
**What type of PR is this?**

/kind cleanup
/kind deprecation

**What this PR does / why we need it**:

https://github.com/kubernetes/kubernetes/pull/95505

As mentioned in this pr, hyper-v will be deprecated in 1.20 and will be removed in 1.21, 1.20 has been released, this pr will remove this feature

**Which issue(s) this PR fixes**:

Fixes  #94490

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
[ACTION REQUIRED] removing experimental windows container hyper-v support with Docker
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

/sig windows
/area kubelet

### CODE REVIEW

**Comment by marosset** [comment]
@wawa0210 can you update the release notes section in the PR header to something a bit more descriptive like 
`[ACTION REQUIRED] removing experimental windows container hyper-v support with Docker`
Thanks!

**Comment by wawa0210** [comment]
> @wawa0210 can you update the release notes section in the PR header to something a bit more descriptive like
> `[ACTION REQUIRED] removing experimental windows container hyper-v support with Docker`
> Thanks!

done

**Review by pacoxu — APPROVED** [review]

**Review by ehashman — COMMENTED** [review]
/lgtm
/retest

**Comment by ehashman** [comment]
@wawa0210 this looks like a real test failure, would you PTAL? https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/97141/pull-kubernetes-e2e-azure-disk-windows/1349783846916198400

/lgtm cancel

**Comment by wawa0210** [comment]
> @wawa0210 this looks like a real test failure, would you PTAL? https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/97141/pull-kubernetes-e2e-azure-disk-windows/1349783846916198400
> /lgtm cancel

It should be the Flaking Test. I opened an additional issue for easy tracking and does not affect this pr
https://github.com/kubernetes/kubernetes/issues/98084

**Comment by wawa0210** [comment]
/cc @ehashman

Can you help review again?

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by wawa0210** [comment]
获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
