### PR TITLE
Automated cherry pick of #114351: Ignore container events with nil PodSandboxStatus

### PR DESCRIPTION
**Pull request by ruiwen-zhao**
Cherry pick of #114351 on release-1.26.

#114351: Ignore container events with nil PodSandboxStatus

This is a bug fix. Without this fix, when Evented PLEG is enabled, kubelet will panic if container runtime sends container events with nil PodSandboxStatus.

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Review by mikebrow — APPROVED** [review]
LGTM

**Review by mrunalp — APPROVED** [review]
/lgtm

**Pull request merged**
