### PR TITLE
Clean up the network plugin code

### PR DESCRIPTION
**Pull request by yujuhong**
Moves the `pkg/kubelet/network` package down to `dockershim` since network
setup is done by the runtime. Also remove various interfaces/code added only for
backward compatibility with non-CRI runtimes, which are now removed from the
codebase.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yujuhong** [comment]
test pull-kubernetes-e2e-gce-device-plugin-gpu

**Comment by thockin** [comment]
nice!

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by yujuhong** [comment]
> Automatic merge from submit-queue (batch tested with PRs 61549, 62230, 62055, 61082, 62212). If you want to cherry-pick this change to another branch, please follow the instructions here.

This is interesting. PR didn't get merged because of the merge conflict. 
/cc @BenTheElder @krzyzacy, is this expected?

**Comment by yujuhong** [comment]
Resolved the conflict and reapplied lgtm

**Comment by yujuhong** [comment]
/test pull-kubernetes-kubemark-e2e-gce

Quota issues...

**Comment by BenTheElder** [comment]
> This is interesting. PR didn't get merged because of the merge conflict.
/cc @BenTheElder @krzyzacy, is this expected?

I don't think this is expected, but I'm not as familiar with the submit-queue. We've migrated everything but kubernetes/kubernetes to `tide` which generally speaking has much better and more straightforward behavior.

cc @cjwagner

**Comment by cjwagner** [comment]
This is definitely not expected and it doesn't look like a race condition based on the timing either...
I'm not sure what happened here, but I think the solution is switching to Tide ASAP unless we see another occurrence of this.

**Pull request merged**
