### PR TITLE
Fix golint failures of e2e/framework/[a-c].go

### PR DESCRIPTION
**Pull request by oomichi**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This fixes golint failures on the following files:
- test/e2e/framework/authorizer_util.go
- test/e2e/framework/cleanup.go
- test/e2e/framework/create.go

NOTE: Factories and ItemNotSupported in create.go are used in create.go only.
So this renames to lower case.

ref: https://github.com/kubernetes/kubernetes/issues/68026

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by spiffxp** [comment]
Do you have an umbrella issue for addressing these golint failures?

**Review by spiffxp — APPROVED** [review]
/lgtm
/approve

**Comment by oomichi** [comment]
@spiffxp Thanks for your review.

> Do you have an umbrella issue for addressing these golint failures?

Yes, we have. I added the following on the PR message.

`ref: https://github.com/kubernetes/kubernetes/issues/68026`

**Comment by spiffxp** [comment]
ok cool this is for all golint, got it

**Pull request merged**
