### PR TITLE
Promote Event resource lifecycle test  +5 test endpoint coverage

### LINKED ISSUE #86288: Promote CoreV1Event test - +5 coverage
- [x] [mock test ticket](#)
- [x] [PR](https://github.com/kubernetes/kubernetes/pull/86858)
- [ ] [promotion](https://github.com/kubernetes/kubernetes/pull/89753)

This issue proposes the writing of a new test for the API endponts `readCoreV1NamespacedEvent`, `patchCoreV1NamespacedEvent`, `listCoreV1NamespacedEvent`, `listCoreV1EventForAllNamespaces`, `deleteCoreV1NamespacedEvent`, and `createCoreV1NamespacedEvent` with the intention of promoting it to Conformance. This issue contains a very basic mock test in order to start the conversation about what a good e2e test would look like for this endpoint. The code below is verified to be hitting the intended endpoint, show as per the queries in APIsnoop's live view of the cluster's audit logs.

## Deploy APISnoop

```shell
kubectl apply -f ~/cncf/apisnoop/deployment/k8s/raiinbow.yaml
```

# Identifying an untested feature using APISnoop

According to these query results from APIsnoop, we are lacking in tests for the following endpoints related to Events

```sql-mode
SELECT
  operation_id,
  -- k8s_action,
  -- path,
  description
  FROM untested_stable_core_endpoints
  where path not like '%volume%'
  and operation_id like '%Event%'
 ORDER BY operation_id desc
 -- LIMIT 25
       ;
```

```sql-mode
             operation_id              |             description              
---------------------------------------|--------------------------------------
 replaceCoreV1NamespacedEvent          | replace the specified Event
 readCoreV1NamespacedEvent             | read the specified Event
 patchCoreV1NamespacedEvent            | partially update the specified Event
 listCoreV1NamespacedEvent             | list or watch objects of kind Event
 listCoreV1EventForAllNamespaces       | list or watch objects of kind Event
 deleteCoreV1NamespacedEvent           | delete an Event
 deleteCoreV1CollectionNamespacedEvent | delete collection of Event
 createCoreV1NamespacedEvent           | create an Event
(8 rows)

```

We chose the following 5 endpoints for this **mock** test:
- `readCoreV1NamespacedEvent`
- `patchCoreV1NamespacedEvent`
- `listCoreV1NamespacedEvent`
- `listCoreV1EventForAllNamespaces`
- `deleteCoreV1NamespacedEvent`
- `createCoreV1NamespacedEvent`

# API References

-   [Kubernetes API Reference Docs](https://kubernetes.io/docs/reference/kubernetes-api/)
-   [client-go - Events](https://github.com/kubernetes/client-go/blob/master/kubernetes/typed/core/v1/event.go)

# The mock test

## Example in Go

Test outline:
1. create Event in namespace default with custom fields

2. list all events in all namespaces
   find event created in #1 in response of #2

3. update the content of the event created in #1

4. get events by name in namespace default
   ensure that the event updated from #4

5. delete event by name

6. list all events in namespace
   ensure event in namespace default was deleted

```shell
go get -v -u k8s.io/apimachinery/pkg/apis/meta/v1
go get -v -u k8s.io/client-go/kubernetes
go get -v -u k8s.io/client-go/tools/clientcmd
```

This mock test uses client-go's standard functions for talking to the Event area of the API.

```go
package main

import (
  "fmt"
  "flag"
  "os"
  //"encoding/json"
  v1 "k8s.io/api/core/v1"
  metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
  "k8s.io/client-go/kubernetes"
  "k8s.io/client-go/tools/clientcmd"
  "k8s.io/apimachinery/pkg/types"
)

func main() {
  // uses the current context in kubeconfig
  kubeconfig := flag.String("kubeconfig", fmt.Sprintf("%v/%v/%v", os.Getenv("HOME"), ".kube", "config"), "(optional) absolute path to the kubeconfig file")
     flag.Parse()
  config, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)
  if err != nil {
    fmt.Println(err)
    return
  }
  // make our work easier to find in the audit_event queries
  config.UserAgent = "live-test-writing"
  // creates the clientset
  clientset, _ := kubernetes.NewForConfig(config)

  eventTestName := "event-test"

  // create a test event in default namespace
  _, err = clientset.CoreV1().Events("default").Create(&v1.Event{
    ObjectMeta: metav1.ObjectMeta{
      Name: eventTestName,
    },
    Message: "This is a test event",
    Reason: "Test",
    Type: "Normal",
    Count: 1,
  })
  if err != nil {
    fmt.Println("[error]", err)
    return
  }
  fmt.Println("[status] test event created")

  // get a list of Events in all namespaces
  eventsList, err := clientset.CoreV1().Events("").List(metav1.ListOptions{})
  if err != nil {
    fmt.Println("[error]", err)
    return
  }
  if len(eventsList.Items) == 0 {
    fmt.Println("[error] no events found")
    return
  }
  foundCreatedEvent := false
  var eventCreatedName string
  for _, val := range eventsList.Items {
    if val.ObjectMeta.Name == eventTestName && val.Message == "This is a test event" {
      foundCreatedEvent = true
      eventCreatedName = val.ObjectMeta.Name
    }
  }
  if foundCreatedEvent == false {
    fmt.Println("[error] unable to find event")
    return
  }
  fmt.Println("[status] created event found")

  // patch the event's message
  eventPatch := fmt.Sprintf(`{"message":"This is a test event - patched"}`)
  _, err = clientset.CoreV1().Events("default").Patch(eventTestName, types.StrategicMergePatchType, []byte(eventPatch))
  if err != nil {
    fmt.Println("[error]", err)
    return
  }
  fmt.Println("[status] patched event successfully")

  // get event by name
  event, err := clientset.CoreV1().Events("default").Get(eventCreatedName, metav1.GetOptions{})
  if err != nil {
    fmt.Println("[error]", err)
    return
  }
  if event.Message != "This is a test event - patched" {
    fmt.Println("[error]", err)
    return
  }
  fmt.Println("[status] found event with patched message")

  // delete original event
  err = clientset.CoreV1().Events("default").Delete(eventCreatedName, &metav1.DeleteOptions{})
  if err != nil {
    fmt.Println("[error]", err)
    return
  }

  // get a list of Events default namespace
  eventsList, err = clientset.CoreV1().Events("").List(metav1.ListOptions{})
  if err != nil {
    fmt.Println("[error]", err)
    return
  }
  if len(eventsList.Items) == 0 {
    fmt.Println("[error] no events found")
    return
  }
  foundCreatedEvent = false
  for _, val := range eventsList.Items {
    if val.ObjectMeta.Name == eventTestName && val.Message == "This is a test event - patched" {
      foundCreatedEvent = true
      eventCreatedName = val.ObjectMeta.Name
    }
  }
  if foundCreatedEvent == true {
    fmt.Println("[error] found event")
    return
  }

  fmt.Println("[status] complete")
}
```

# Verify with APISnoop

Discover useragents
```sql-mode
select distinct useragent from audit_event where bucket='apisnoop' and useragent not like 'kube%' and useragent not like 'coredns%' and useragent not like 'kindnetd%';
```

```sql-mode
     useragent     
-------------------
 live-test-writing
(1 row)

```

Display endpoints hit by the test
```sql-mode
select * from endpoints_hit_by_new_test where useragent like 'live%';
```

```
     useragent     |          operation_id           | hit_by_ete | hit_by_new_test 
-------------------+---------------------------------+------------+-----------------
 live-test-writing | createCoreV1NamespacedEvent     |          0 |               2 
 live-test-writing | deleteCoreV1NamespacedEvent     |          0 |               2 
 live-test-writing | listCoreV1EventForAllNamespaces |          0 |               2 
 live-test-writing | patchCoreV1NamespacedEvent      |          0 |               2 
 live-test-writing | readCoreV1NamespacedEvent       |          0 |               1 
(5 rows)                                                                            
```

Show the change in coverage after the mock test
```sql-mode
select * from projected_change_in_coverage;
```

```sql-mode
   category    | total_endpoints | old_coverage | new_coverage | change_in_number 
---------------|-----------------|--------------|--------------|------------------
 test_coverage |             438 |          183 |          188 |                5
(1 row)

```

# Final notes
If a test with these calls gets merged in, **conformance will go up by 5 endpoints**.

# 
/sig testing
/sig architecture
/area conformance

### PR DESCRIPTION
**Pull request by BobyMCbobs**
- [x] [mock test ticket](https://github.com/kubernetes/kubernetes/issues/86288)
- [x] [PR](https://github.com/kubernetes/kubernetes/pull/86858)
- [ ] [promotion](#)

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Promotes the following E2E tests to Conformance:
`test/e2e/framework/events/events.go: "should ensure that an event can be fetched, patched, deleted, and listed"`

**Which issue(s) this PR fixes**:
Fixes #86288

**Special notes for your reviewer**:
Adds +5 conformance endpoint coverage

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
NONE
```

/area conformance
/area test
@kubernetes/cncf-conformance-wg

### CODE REVIEW

**Comment by spiffxp** [comment]
/hold
needs two weeks' worth of data in testgrid

**Comment by hh** [comment]
/retitle Promote Event resource lifecycle test  +5 test endpoint coverage

**Comment by spiffxp** [comment]
/override pull-kubernetes-node-e2e-containerd
ref: https://github.com/kubernetes/kubernetes/issues/89847

**Comment by BobyMCbobs** [comment]
/unhold

This test has had two weeks to soak. The [testgrid results](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=should%20ensure%20that%20an%20event%20can%20be%20fetched%2C%20patched%2C%20deleted%2C%20and%20listed) appear to have no flakes.
Ready to continue! :smiley:

**Pull request merged**
