### PR TITLE
cleanup: delete useless code from kubelet volumemanager

### PR DESCRIPTION
**Pull request by cvvz**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

delete unnecessary code from kubelet volumemanager. Since we no longer call out to the container runtime in `findAndRemoveDeletedPods`(which does before: https://github.com/kubernetes/kubernetes/commit/c723d9e5c4074c165a558ad148841b54c8bb0117), there is no need to limit the rate. Aslo, actually `dswp.timeOfLastGetPodStatus` is never assigned a valid time, so this code snippet doesn't work at all.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
/ok-to-test

**Comment by bart0sh** [comment]
Can someone from SIG-storage look at this PR?
/sig storage

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
