### PR TITLE
kubeadm: fix typo in help text; ca.cert should be ca.crt

### LINKED ISSUE #27145: kubeadm init phase typo
Hello,

The documentation available at https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init-phase/#cmd-phase-certs states that the init phase is creating ca.cert and ca.key, the public key name has a typo. Instead it should be ca.crt.  
This makes the process of providing your own CA fail because kubeadm expects a different name.
```
Synopsis
Generate the self-signed Kubernetes CA to provision identities for other Kubernetes components, and save them into ca.cert and ca.key files.
```

### PR DESCRIPTION
**Pull request by su225**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Fixes a typo in Kubeadm documentation

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/website/issues/27145

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by su225** [comment]
I signed it

**Review by neolit123 — COMMENTED** [review]
thanks

/lgtm
/approve
/triage accepted
/priority backlog

we are in code freeze for 1.21, but this will auto-merge in the following weeks.

**Comment by neolit123** [comment]
/retitle kubeadm: fix typo in help text; ca.cert should be ca.crt

**Pull request merged**
