### PR TITLE
update libc to pick up some fixes

### PR DESCRIPTION
**Pull request by mikedanese**
http://metadata.ftp-master.debian.org/changelogs/main/g/glibc/glibc_2.24-10_changelog

### CODE REVIEW

**Comment by ixdy** [comment]
/lgtm

probably needs cherry-pick, too?

**Comment by mikedanese** [comment]
As soon as Bazel goes green we should merge

**Comment by mikedanese** [comment]
I gotta pull of the bandaid. @apelisse is out on leave and this is going to break all builds. We need to fix the rotation.

**Comment by mikedanese** [comment]
I would happily accept a post merge approval.

**Comment by thockin** [comment]
How does this break builds?

**Comment by ixdy** [comment]
the originally linked deb file (http://ftp.us.debian.org/debian/pool/main/g/glibc/libc6_2.24-9_amd64.deb) no longer exists.

if you had the deb cached, the build would work fine. if you were starting from a clean bazel workspace, when you tried to download the deb, it would fail.

**Comment by mikedanese** [comment]
What @ixdy said. We are discussing ways to mitigate this. We can probably change this to a test failure rather than a build failure.

**Pull request merged**
