### PR TITLE
test/e2e: cleanup e2e core framework's import from sub package e2elog

### PR DESCRIPTION
**Pull request by kidlj**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR is part of https://github.com/kubernetes/kubernetes/issues/81245, to avoid core e2e framework having imports from sub e2e packages.

#### Which issue(s) this PR fixes:

Ref: https://github.com/kubernetes/kubernetes/issues/81245

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/ok-to-test
/priority backlog

this seems valid as per https://github.com/kubernetes/kubernetes/issues/81245

**Comment by aojea** [comment]
I think a linter should detect this things, no?

**Comment by kidlj** [comment]
Hello, @oomichi, would you please review this PR for us?

**Comment by oomichi** [comment]
Thanks for doing this.

/lgtm
/approve

**Comment by oomichi** [comment]
> 
> 
> I think a linter should detect this things, no?

@aojea That is a nice point.
At this time, we have a lot of violations for this rule.
But it will be possible to enable the linter after fixing these violations.

**Pull request merged**
