### PR TITLE
type: "Kubernetes distinguished" --> "Kubernetes distinguishes"

### PR DESCRIPTION
**Pull request by DazWilkin**

### CODE REVIEW

**Comment by thockin** [comment]
ok to test

**Comment by thockin** [comment]
@DazWilkin Can you take a look at the CLA?  We can't do anything until it's signed.

**Comment by wojtek-t** [comment]
Jenkins test failure:
"Kubectl client Guestbook application should create and stop a working application [Conformance]"

@k8s-bot test this please

**Comment by wojtek-t** [comment]
@DazWilkin - can you please sign CLA - we cannot merge even such PR without that.

**Comment by thockin** [comment]
Why closed?  it turns out that Daz is a Google employee :)

**Pull request closed without merging**
