### PR TITLE
hyperkube: Build debian-hyperkube-base v1.1.0 image

### PR DESCRIPTION
**Pull request by justaugustus**
**What type of PR is this?**

/kind regression
/area dependency
/priority critical-urgent

**What this PR does / why we need it**:

- Use debian-iptables v12.1.0 as base image
  Should ensure kube-proxy behaves the same in hyperkube as it would for
  the standard kube-proxy image.
- Removes the following packages (which are already present in the
  debian-iptables image):
  - conntrack
  - ebtables
  - iptables
  - ipset
  - kmod
  - netbase

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

**Which issue(s) this PR fixes**:

Attempt to fix https://github.com/kubernetes/kubernetes/issues/92275, https://github.com/kubernetes/kubernetes/issues/92272, https://github.com/kubernetes/kubernetes/issues/92250.
Should supersede https://github.com/kubernetes/kubernetes/pull/92281.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by justaugustus** [comment]
/assign @BenTheElder @danwinship @cblecker 
/area release-eng
cc: @kubernetes/release-engineering 

cc-ing reporters/commenters:
cc: @ialidzhikov @vpnachev @juliantaylor @majst01 @waynr @superseb @dmitry-irtegov @aojea

**Comment by aojea** [comment]
/lgtm
for the network changes
/hold
for the image dependencies changes, is not something I'm familiar enough to review

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by aojea** [comment]
/hold cancel
sascha lgtmed

**Comment by danwinship** [comment]
So where does kubelet get run from when you're using hyperkube? The iptables wrapper script was written under the assumption that kubelet would _not_ use the wrapper script.

Specifically, the iptables wrapper tries to use the same mode that other things on the system are using, but it can only figure that out if _something_ in the base system sets up some iptables rules before anything that uses the iptables wrapper runs. Normally, that something would be kubelet, which always creates a few iptables rules before starting any pods. But if kubelet is also going to end up using the iptables wrapper rather than the system iptables binaries, then we're relying on there being something else in the system that sets up some iptables rules before kubelet runs.

(Though... I guess if kubelet is being run out of the hyperkube image by docker or something like that, then docker would have set up some iptables rules before kubelet runs, so again things would work...)

**Comment by justaugustus** [comment]
Given the conversation in Slack (https://kubernetes.slack.com/archives/C2C40FMNF/p1592857876443000), it seems like this should be reasonable to move forward with?

If so, can I get an `/approve`?
/assign @caseydavenport @thockin @dcbw

**Comment by thockin** [comment]
@danwinship Even if there are no other rules, as long as kubelet and kube-proxy use the same logic, they should make the same choice, right?

IOW, I think this seems OK, but I am anxious about saying that with authority.  You are closer to the impl..

**Comment by danwinship** [comment]
The theoretical failure mode I was worried about is:

1. system boots, /usr/sbin/iptables points to iptables-nft
2. some stuff starts up, but nothing has touched iptables yet
3. kubelet starts, runs iptables wrapper, falls back to iptables-legacy by default because there are no iptables rules at all
4. firewall starts, uses iptables-nft, creates a bunch of rules
5. kube-proxy starts, runs iptables wrapper, sees that there are more nft rules than legacy rules, so uses nft
6. kubelet and kube-proxy are now out of sync

But I guess there's really no obvious way for that to happen because if you're running kubelet out of the hyperkube image, you have to be using docker, in which case 2 would actually be "some stuff starts up, including docker, which creates iptables rules using iptables-nft", so then 3 would be "kubelet starts, sees iptables-nft rules, uses iptables-nft" and everything would work.

Someone responded in the thread Stephen linked to above and he was using docker to start kubelet, but he was also running into a bunch of other problems because the mountpoints he was using for that container ended up breaking iptables 1.8's use of `/etc/alternatives`, etc.

The hyperkube image is already gone in 1.19, right? Maybe the easiest fix here would just be to revert it back to the old debian image, since we don't have to maintain it going forward anyway?

**Comment by danwinship** [comment]
(Suggesting that because of the other problems the slack user was having. If we only care about "picking the right iptables mode", then yes, I think switching from debian-base to debian-iptables should fix that.)

**Comment by justaugustus** [comment]
> Someone responded in the thread Stephen linked to above and he was using docker to start kubelet, but he was also running into a bunch of other problems because the mountpoints he was using for that container ended up breaking iptables 1.8's use of `/etc/alternatives`, etc.

I would consider their downstream mountpoint... "unsupported" is maybe the wrong word, but not the most important thing to solve. I haven't personally seen the mountpoint issues reported elsewhere, so I think it's local to their environment.

> The hyperkube image is already gone in 1.19, right? Maybe the easiest fix here would just be to revert it back to the old debian image, since we don't have to maintain it going forward anyway?

I do wish that was a potential option.
While hyperkube is deprecated from 1.19 onwards, it's still present in the 1.18 --> 1.16 branches, which means we're on the hook to support it until we EOL Kubernetes 1.18.

> (Suggesting that because of the other problems the slack user was having. If we only care about "picking the right iptables mode", then yes, I think switching from debian-base to debian-iptables should fix that.)

Yep, yep, picking the right iptables mode is what I'd like to solve first.
There's a good chance that base image change will resolve the currently open issues.

**Comment by dmitry-irtegov** [comment]
I think there is deeper problem with current iptables selection logic.

There are manifests that still are hardcoded to use iptables-legacy.  At least, dns-node-cache and flannel.

If one of these manifests is used on the cluster, it creates enough legacy rules to force kube-proxy to legacy mode.

On normal startup it is impossible, but think about a pod restart....

**Comment by BenTheElder** [comment]
kube-proxy shouldn't be starting after pods like dns-node-cache and flannel on normal startup, and on pod restart it shouldn't be a problem if the other network tools in use also correctly implement something like this If they use iptables.

If they don't implement this, those tools already left the system broke if the host used iptables / nft not matching them, and kube proxy is matching the host.

**Comment by BenTheElder** [comment]
On restart kube-proxy will also have lots of old kube-proxy rules.

**Comment by BenTheElder** [comment]
This flake is a known problematic test.
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/92354/pull-kubernetes-e2e-kind/1275668877891604482

The following flake with the base image though, that one is ??

**Comment by dmitry-irtegov** [comment]
> ... if the other network tools in use also correctly implement something like this If they use iptables.
This makes sence.  But you probably should mention this in release notes and/or docs.   So maintainers of these tools will know what they should do and why.

Also, the recommendation to unload/blacklist ip_tables kernel module might help. So people will know what breaks and why.

**Comment by BenTheElder** [comment]
??
```

1/4992 Tests Failed. | expand_less
-- | --
[sig-node] RuntimeClass should reject a Pod requesting a RuntimeClass with an unconfigured handler expand_less7stest/e2e/common/runtimeclass.go:47 Jun 24 07:08:27.187: Error creating Pod Unexpected error:     <*errors.StatusError \| 0xc001d6e460>: {         ErrStatus: {             TypeMeta: {Kind: "", APIVersion: ""},             ListMeta: {                 SelfLink: "",                 ResourceVersion: "",                 Continue: "",                 RemainingItemCount: nil,             },             Status: "Failure",             Message: "pods \"test-runtimeclass-runtimeclass-1410-unconfigured-handler-\" is forbidden: pod rejected: RuntimeClass \"runtimeclass-1410-unconfigured-handler\" not found",             Reason: "Forbidden",             Details: {                 Name: "test-runtimeclass-runtimeclass-1410-unconfigured-handler-",                 Group: "",                 Kind: "pods",                 UID: "",                 Causes: nil,                 RetryAfterSeconds: 0,             },             Code: 403,         },     }     pods "test-runtimeclass-runtimeclass-1410-unconfigured-handler-" is forbidden: pod rejected: RuntimeClass "runtimeclass-1410-unconfigured-handler" not found occurred test/e2e/framework/pods.go:83 | [sig-node] RuntimeClass should reject a Pod requesting a RuntimeClass with an unconfigured handler expand_less | 7s | test/e2e/common/runtimeclass.go:47 Jun 24 07:08:27.187: Error creating Pod Unexpected error:     <*errors.StatusError \| 0xc001d6e460>: {         ErrStatus: {             TypeMeta: {Kind: "", APIVersion: ""},             ListMeta: {                 SelfLink: "",                 ResourceVersion: "",                 Continue: "",                 RemainingItemCount: nil,             },             Status: "Failure",             Message: "pods \"test-runtimeclass-runtimeclass-1410-unconfigured-handler-\" is forbidden: pod rejected: RuntimeClass \"runtimeclass-1410-unconfigured-handler\" not found",             Reason: "Forbidden",             Details: {                 Name: "test-runtimeclass-runtimeclass-1410-unconfigured-handler-",                 Group: "",                 Kind: "pods",                 UID: "",                 Causes: nil,                 RetryAfterSeconds: 0,             },             Code: 403,         },     }     pods "test-runtimeclass-runtimeclass-1410-unconfigured-handler-" is forbidden: pod rejected: RuntimeClass "runtimeclass-1410-unconfigured-handler" not found occurred test/e2e/framework/pods.go:83
[sig-node] RuntimeClass should reject a Pod requesting a RuntimeClass with an unconfigured handler expand_less | 7s
test/e2e/common/runtimeclass.go:47 Jun 24 07:08:27.187: Error creating Pod Unexpected error:     <*errors.StatusError \| 0xc001d6e460>: {         ErrStatus: {             TypeMeta: {Kind: "", APIVersion: ""},             ListMeta: {                 SelfLink: "",                 ResourceVersion: "",                 Continue: "",                 RemainingItemCount: nil,             },             Status: "Failure",             Message: "pods \"test-runtimeclass-runtimeclass-1410-unconfigured-handler-\" is forbidden: pod rejected: RuntimeClass \"runtimeclass-1410-unconfigured-handler\" not found",             Reason: "Forbidden",             Details: {                 Name: "test-runtimeclass-runtimeclass-1410-unconfigured-handler-",                 Group: "",                 Kind: "pods",                 UID: "",                 Causes: nil,                 RetryAfterSeconds: 0,             },             Code: 403,         },     }     pods "test-runtimeclass-runtimeclass-1410-unconfigured-handler-" is forbidden: pod rejected: RuntimeClass "runtimeclass-1410-unconfigured-handler" not found occurred test/e2e/framework/pods.go:83


```

**Comment by BenTheElder** [comment]
agree re: relnotes @justaugustus

**Comment by justaugustus** [comment]
> ??

Where are you seeing that failure?

> agree re: relnotes @justaugustus

This PR only builds the new image, which is why it doesn't include a release note.
Follow up PRs will actually utilize the new image (user-facing change) and those will include release notes.

**Comment by BenTheElder** [comment]
ack

re the failure: the last kind flake, it's not related to this PR, but it is very ??

**Pull request merged**
