### PR TITLE
Functionize client connection in glusterfs plugin.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by deads2k** [comment]
I don't see the value in hiding this inside of a function.  Why would I do that?

**Comment by humblec** [comment]
@deads2k planning to bring more callers of this function in the plugin. I could also embed this commit in the next PR. Thought of keeping the PR separate . Please let me know if you think its better to embed this commit in the next/following PR.

**Comment by deads2k** [comment]
I'm questioning the whole approach of hiding one function call in another since it appears to be a pass through.  It seems like we should just call the original function without indirection.

**Comment by humblec** [comment]
@deads2k Yep, I get it. :) The plan is to keep the function args under scrutiny , then adjust the args or bring more error handling in the modularized function instead of keep repeating in all existing and upcoming callers.

**Pull request closed without merging**
