### PR TITLE
Add Starting log with correlator options func for event broadcaster

### LINKED ISSUE #90168: Add the option to log not-skipped events only to EventBroadcaster
**What would you like to be added**:
EventBroadcaster should allow to log only those events which aren't skipped by the correlator and are actually passed to sinks.

**Why is this needed**:
`NewBroadcasterWithCorrelatorOptions()` allows creating a broadcaster with rate-limiting options. However, those options only get applied when recording to sink via `StartRecordingToSink()` and not when logging via `StartLogging()`. If a user produces a lot of events, it's likely that they'd want to only log information about those that actually passed rate-limiting, to avoid filling up the log. With the current implementation, they'd have to either replicate the rate-limiting logic on the caller side, or implement a wrapper around a sink which does the logging.

We encountered this problem in Cluster Autoscaler and we'll solve it with the wrapper for now, but I think it'd beneficial to add the option directly to EventBroadcaster.

### PR DESCRIPTION
**Pull request by gavinfish**
**What type of PR is this?**

 /kind feature

**What this PR does / why we need it**:

Correlator options only get applied when recording to sink via StartRecordingToSink() and not when logging via StartLogging(). Add a new func to log information applied the correlator options. like those that actually passed rate-limiting.

**Which issue(s) this PR fixes**:

Fixes #90168

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
none
```

### CODE REVIEW

**Comment by fedebongio** [comment]
Thank you for the PR!
/assign @yliaog

**Comment by yliaog** [comment]
please add tests in event_test.go for the added function

**Comment by gavinfish** [comment]
> please add tests in event_test.go for the added function

@yliaog done

**Comment by gavinfish** [comment]
@towca could you please help me take look at this PR?

**Pull request closed without merging**
