### PR TITLE
Update kubectl describe to print out PV node affinity

### LINKED ISSUE #60119: PV NodeAffnity should be added to 'kubectl describe'
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-bugs 
/assign

**What happened**:
Now that it's a field, it needs a separate entry in 'kubectl describe'

### PR DESCRIPTION
**Pull request by msau42**
**What this PR does / why we need it**:
Print out PV NodeAffinity in kubectl describe.

Sample output:
```
Name:            example-local-pv
Labels:          foo1=bar1
                 foo2=bar2
Annotations:     <none>
Finalizers:      []
StorageClass:    local-storage
Status:          Available
Claim:
Reclaim Policy:  Delete
Access Modes:    RWO
Capacity:        5Gi
Node Affinity:
  Required Terms:
    Term 0:  kubernetes.io/hostname in [my-node]
             foo1 in [bar1, bar2]
    Term 1:  foo2 exists
Message:
Source:
    Type:  LocalVolume (a persistent volume backed by local storage on a node)
    Path:  /mnt/disks/ssd1
Events:    <none>
```

No NodeAffinity is set:
```
Name:            nfs
Labels:          <none>
Annotations:     <none>
Finalizers:      []
StorageClass:    
Status:          Available
Claim:           
Reclaim Policy:  Retain
Access Modes:    RWX
Capacity:        1Mi
Node Affinity:   <none>
Message:         
Source:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    10.244.1.4
    Path:      /exports
    ReadOnly:  false
Events:        <none>
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #60119

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
It turns out Pod NodeAffinity is not printed in kubectl describe, so there's no precedent to follow here.  Open to any suggestions.

@kubernetes/sig-storage-pr-reviews 
/assign @jsafrane @bsalamat

**Comment by bsalamat** [comment]
@msau42 I think the format you have used looked good. And, we (not necessarily you) should add NodeAffinity output for Pods as well.

**Pull request merged**
