### PR TITLE
Use shell internal functionality instead of basename/dirname

### PR DESCRIPTION
**Pull request by joakimr-axis**
For generate-groups.sh and generate-internal-groups.sh existing built-in
shell variable handling can be used instead of calling external programs
basename and dirname. Also remove some superfluous quotes to improve
readability.

Signed-off-by: Joakim Roubert <joakimr@axis.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by joakimr-axis** [comment]
PR https://github.com/kubernetes/kubernetes/pull/84521 moved here.

**Comment by lavalamp** [comment]
I would delete every shell file in the repo if I were allowed, so I may not be the best person to review this.

Using unquoted strings makes me very uncomfortable. Do we have a style guide we're following for shell? E.g. the internal google style guide wants those quotes to stay.

We use basename and dirname all over the place. Are you planning on changing all of our shell files?

I am far from a shell expert but I find the shell-native substitute to be super opaque. These files aren't performance critical (are they?) so I'd personally keep the more legible existing code.

**Comment by joakimr-axis** [comment]
> Using unquoted strings makes me very uncomfortable.

In what parts of this patch are you uncomfortable? I can only see that it is those

[ "${GENS}" = all ]

parts, where you then would prefer the superfluous

[ "${GENS}" = 'all' ]

? (Using double quotes, "all", as in the present code is in all cases wrong since nothing is to be expanded). I can add those single quotes if you like.

> We use basename and dirname all over the place. Are you planning on changing all of our shell files?

If it is requested, I could do that. No problem.
The reason I updated these two files was that I was working with this part of the code and ran across them.

> I am far from a shell expert but I find the shell-native substitute to be super opaque. These files aren't performance critical (are they?) so I'd personally keep the more legible existing code.

I would not call my self a shell expert either, but those simple constructions are IMO sort of shell scripting 101 (and very well described in the shell man pages). Certainly it is much more performance efficient, just like not doing a couple of extra unneeded memcopies in C code, but more importantly using shell internals minimizes the external dependencies and thus add robustness.

**Comment by lavalamp** [comment]
We may have different ideas of what is included in shell 101 :)

/assign @liggitt

Who should either have an answer or know who our current shell expert is :)

**Comment by liggitt** [comment]
From my perspective, this change makes these scripts much less readable/maintainable. The difference in performance is not a concern here. I'll defer to @sttts on whether this change is desireable.

/cc @BenTheElder @cblecker 
for shell feedback

/unassign

**Comment by BenTheElder** [comment]
I agree, preferring:
- quoting things as consistently as possible to encourage correct expansion behavior (including appropriate use of braces, avoid unintentional string splitting)
- using `basename` is more appropriate, it is POSIX and clearer about the intention: path manipulation

**Comment by joakimr-axis** [comment]
Ok, I hear you. No worries, I will drop this PR.
Please do note, though, that the ##*/ construction is found in the present codebase in the files

vendor/github.com/client9/misspell/install-misspell.sh
hack/make-rules/verify.sh
hack/lib/swagger.sh
hack/lib/golang.sh
cluster/gce/util.sh
cluster/gce/upgrade-aliases.sh
cluster/gce/gci/configure.sh

so if _not_ using ##*/ is the goal there is some maintenance pending.

**Comment by BenTheElder** [comment]
It's true, we have some fairly major maintenance ongoing... originally the scripts had little to no consistent standards, we've at least started incrementally requiring them to pass shellcheck but it's been a pretty huge effort to fix them all 😞 

really appreciate anyone taking a stab at that, thank you.

**Pull request closed without merging**
