### PR TITLE
User, Admin, and Developer guides.

### PR DESCRIPTION
**Pull request by erictune**
First pass at organizing our docs for three separate audiences:
User, Cluster Admin, and developer.  Wrote a top-level guide
for each one, by selecting parts of the old docs/README.md.
The new docs/README.md mostly points to these 3 guides.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
I like this separation

**Comment by erictune** [comment]
thx

**Comment by erictune** [comment]
@brendandburns

**Comment by erictune** [comment]
TODO(me): rebase and pick up the change to docs/README.md in #5226 and any others.

**Comment by erictune** [comment]
rebased.

**Comment by bgrant0607** [comment]
LGTM as a first cut.

**Comment by thockin** [comment]
AWESOME

**Pull request merged**
