### PR TITLE
Stop() for Ticker to enable leak-free code

### PR DESCRIPTION
**Pull request by ash2k**
**What this PR does / why we need it**:
I wanted to use the clock package but the `Ticker` without a `Stop()` method is a deal breaker for me.

**Release note**:
```release-note
NONE
```
/kind enhancement
/sig api-machinery

### CODE REVIEW

**Comment by ash2k** [comment]
@yliaog PTAL

**Comment by ash2k** [comment]
For approval, please.
/assign @smarterclayton

**Comment by ash2k** [comment]
Tests are failing because of a race in tests https://github.com/kubernetes/kubernetes/issues/62601

**Comment by ash2k** [comment]
/assign vishh dchen1107

@dchen1107 @vishh @derekwaynecarr PTAL

**Comment by resouer** [comment]
@ash2k May I ask the how often the scheduling integration test, specifically `TestTaintNodeByCondition`, fails in this PR?

**Comment by ash2k** [comment]
@resouer I've seen it only once.

**Pull request merged**
