### PR TITLE
Update structured-merge-diff version

### PR DESCRIPTION
**Pull request by jennybuckley**
/priority important-soon
/kind feature
/assign apelisse
/sig api-machinery
/wg apply

```release-note
NONE
```

At least one test isn't passing for some reason

### CODE REVIEW

**Comment by sttts** [comment]
@jennybuckley I took your commit and completed it https://github.com/kubernetes/kubernetes/pull/74133/commits/d283a1361e8db42823f8a887a24aa1ed6487cc45. If you want to pick it back here....

**Comment by lavalamp** [comment]
I thought we weren't going to make breaking changes to smd?

**Pull request merged**
