### PR TITLE
print more test info like other case

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
add more test info, think you very much

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by soltysh** [comment]
@zjj2wry can you explain what's the value of this PR?

**Comment by zjj2wry** [comment]
@soltysh small change to print more test info to locate error like other testcase.

**Comment by soltysh** [comment]
@zjj2wry is it failing currently and you're trying to debug this, or this is just in case? If the latter I don't see any reason we need it, yet.

**Pull request closed without merging**
