### PR TITLE
Fix several spelling errors in comments

### PR DESCRIPTION
**Pull request by goltermann**
What the title says

### CODE REVIEW

**Comment by goltermann** [comment]
@lavalamp k8s-bot picked up "kind/api-change" on this one.  Is this a false positive, or is there something I shouldn't have touched?

**Comment by jlowdermilk** [comment]
@goltermann, no the munger just applies that tag based on [filepath regex](https://github.com/kubernetes/contrib/blob/master/mungegithub/path-label.txt). This change is purely cosmetic.

**Comment by lavalamp** [comment]
@goltermann you're fixing spelling in some of our API documentation, so it's correct.

**Comment by goltermann** [comment]
@jlowdermilk Had to update some generated stuff - can you recheck and re-lgtm?

**Pull request merged**
