### PR TITLE
[WIP] Added fieldSelector to kubectl/resource/Helper::List.

### LINKED ISSUE #33087: Add fieldSelector to kubectl.resource.Helper::List
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature request

**Kubernetes version** (use `kubectl version`):
master

**Description**  :

When working on #15834 , the proposed solution is to use `fieldSelector` instead of resource URL. And after go through the code, there's also a `TODO` in Helper::List to support `fieldSelector`. The purpose of this issue is to make Helper::List support `fieldSelector`, and then 
#15834 can re-use it directly.

### PR DESCRIPTION
**Pull request by k82cn**
fixes #33087

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33449)

### CODE REVIEW

**Comment by deads2k** [comment]
Do you have a concrete use for this?  We've intentionally avoided adding a field selector argument to `kubectl` since field selectors are inconsistently and inefficiently implemented across our types.

If you'd like to add field selectors, I think I'd suggest starting with ensuring consistency in the API, then move to syntax, then move to exposing it.

@fabianofranz @liggitt

**Comment by k82cn** [comment]
@deads2k , I'd like to use it for https://github.com/kubernetes/kubernetes/issues/15834 .

**Comment by deads2k** [comment]
> @deads2k , I'd like to use it for #15834 .

Yeah, I don't think I want people to be confused a partially working field selector and adding it like this will encourage people to try to wire it up.

How about starting with consistent (and ideally efficient)  field selector support in the API itself?

**Comment by k82cn** [comment]
@deads2k , any suggestion on "consistent (and ideally efficient) field selector support", I'd like to handle it :).

**Comment by deads2k** [comment]
> @deads2k , any suggestion on "consistent (and ideally efficient) field selector support", I'd like to handle it :).

I would focus on consistent first.  The field selector needs to be evaluated against the external encoding of the object.  I would find where we evaluate the label selector (I don't know which layer its at) and try to work my way out from there.

I haven't look at the problem in detail.

**Comment by k82cn** [comment]
Thanks @deads2k, and would you also keep in the loop for "consistent"? I'd like to learn it :).

**Comment by k82cn** [comment]
Close this PR first, will work with @deads2k to enhance field selector API.

**Pull request closed without merging**
