### PR TITLE
Remove unnecessary variable declaration

### PR DESCRIPTION
**Pull request by odinuge**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Just a simple cleanup

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

/kind node

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

**Pull request merged**
