### PR TITLE
prevent RC hotloop on denied pods

### PR DESCRIPTION
**Pull request by deads2k**
If a pod is rejected during creation, the RC controller hot-loops. This can happen most frequently due to insufficient quota.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30626)

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
LGTM

**Comment by derekwaynecarr** [comment]
@deads2k - see the jenkins failure

```
SUCCESS  hack/make-rules/../../hack/verify-flags-underscore.py	47s
pkg/controller/replication/replication_controller_test.go:1208: possible formatting directive in Fatal call
```

**Comment by deads2k** [comment]
@k8s-bot test this: issue #30570

**Comment by deads2k** [comment]
@k8s-bot test this: issue #26760

**Comment by deads2k** [comment]
I have no idea how @derekwaynecarr was unassigned and he's no longer in my assignee lists or comment autocomplete.  Weird.

**Comment by deads2k** [comment]
@k8s-bot test this: issue #30683

**Pull request merged**
