### PR TITLE
proxy/ipvs: use healthzServer for instantiating the IPVS IPv6 proxier

### LINKED ISSUE #117863: [Failing test] kind ipvs ipv6 job failing
### Which jobs are failing?

image

### Which tests are failing?

it seems all the job is timing out

### Since when has it been failing?

05-04

### Testgrid link

https://testgrid.k8s.io/sig-network-kind#sig-network-kind,%20ipvs,%20IPv6,%20master

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig network

### PR DESCRIPTION
**Pull request by aroradaman**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
context: https://github.com/kubernetes/kubernetes/issues/117863#issuecomment-1544714492
#### Which issue(s) this PR fixes:

Fixes #117863

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
When dual-stack graduated , the feature flag was removed so all proxies are dual-stack.
For IPv6 only clusters we were not passing the healthserver neither the recorder, in one of this cases, when the client tries to connect to the healthserver it panics and holds the lock, deadlocking the ipvs proxier.

without a good knowledge of the ipvs proxier, this change seems correct to me and brings parity with the iptables proxier

https://github.com/kubernetes/kubernetes/blob/ac7e5cbf692603d1ed691dcfe245d2d19715150c/pkg/proxy/iptables/proxier.go#L337-L351

/lgtm
/approve

/hold

for more eyes, but we can unhold if there is no response for a few days

/assign @uablrek @danwinship

**Comment by uablrek** [comment]
Does anybody know by heart if _the same instance_ of healthzServer can be used by multiple proxiers?

**Comment by aojea** [comment]
> Does anybody know by heart if _the same instance_ of healthzServer can be used by multiple proxiers?

it can, is how proxy iptables works today, but @danwinship already reported something about it

**Comment by uablrek** [comment]
This also
/lgtm

**Review by uablrek — APPROVED** [review]

**Comment by aojea** [comment]
image

Now the test fails but does not bring down kube-proxy

```
023-05-13T10:38:34.043216746Z stderr F I0513 10:38:34.043041       1 log.go:194] http: panic serving [fd00:10:244:2::178]:33648: runtime error: invalid memory address or nil pointer dereference
2023-05-13T10:38:34.043253681Z stderr F goroutine 18086 [running]:
2023-05-13T10:38:34.04326039Z stderr F net/http.(*conn).serve.func1()
2023-05-13T10:38:34.04326689Z stderr F 	/usr/local/go/src/net/http/server.go:1854 +0xbf
2023-05-13T10:38:34.043272232Z stderr F panic({0x1ed7c40, 0x3681fd0})
2023-05-13T10:38:34.043277028Z stderr F 	/usr/local/go/src/runtime/panic.go:890 +0x263
2023-05-13T10:38:34.043284666Z stderr F k8s.io/kubernetes/pkg/proxy/healthcheck.hcHandler.ServeHTTP({{{0xc000a01570, 0xd}, {0xc0001b7b90, 0x15}}, 0xc000833400}, {0x254faf0?, 0xc000268b60}, 0xc000ae5af8?)
2023-05-13T10:38:34.043289754Z stderr F 	pkg/proxy/healthcheck/service_health.go:239 +0xf5
2023-05-13T10:38:34.043293607Z stderr F net/http.serverHandler.ServeHTTP({0xc0005682a0?}, {0x254faf0, 0xc000268b60}, 0xc00095e500)
2023-05-13T10:38:34.043297041Z stderr F 	/usr/local/go/src/net/http/server.go:2936 +0x316
2023-05-13T10:38:34.043300303Z stderr F net/http.(*conn).serve(0xc0000d8c60, {0x2550ad8, 0xc000b9f980})
2023-05-13T10:38:34.043303926Z stderr F 	/usr/local/go/src/net/http/server.go:1995 +0x612
2023-05-13T10:38:34.043307428Z stderr F created by net/http.(*Server).Serve
2023-05-13T10:38:34.043310746Z stderr F 	/usr/local/go/src/net/http/server.go:3089 +0x5ed
2023-05-13T10:38:35.047653288Z stderr F I0513 10:38:35.047497       1 log.go:194] http: panic serving [fd00:10:244:2::178]:33660: runtime error: invalid memory address or nil pointer dereference
2023-05-13T10:38:35.047679869Z stderr F goroutine 18088 [running]:
2023-05-13T10:38:35.047683838Z stderr F net/http.(*conn).serve.func1()
2023-05-13T10:38:35.047687992Z std
```

I think that the fact of this test failing legitimate the use of the healthserver here

/hold cancel

**Comment by ArchangelSDY** [comment]
@aojea @aroradaman Can you backport this to v1.27? After upgrading to 1.27 I found kube-proxy healthcheck is panicing due to:

https://github.com/kubernetes/kubernetes/blob/ffe14bd334daa8bb95e45252e13da5e35348424b/pkg/proxy/healthcheck/service_health.go#L238

And this:

https://github.com/kubernetes/kubernetes/blob/ffe14bd334daa8bb95e45252e13da5e35348424b/pkg/proxy/ipvs/proxier.go#L509

**Pull request merged**
