### PR TITLE
Fix issue #21746

### PR DESCRIPTION
**Pull request by olivierlemasle**
Fix issue #21746

This was a regression due to commit e2c79ea1f1
(cf https://github.com/kubernetes/kubernetes/pull/20965)

### CODE REVIEW

**Comment by olivierlemasle** [comment]
I guess this commit will fix the error occuring with "kube-push" if the bearer token is already present, but it will not fix it the token was not present (if the cluster was created before e2c79ea1f173 was merged)

**Comment by derekwaynecarr** [comment]
Taking this PR review since its vagrant...

**Comment by derekwaynecarr** [comment]
Thanks for the PR.  I verified this fixed kube-push.

**Comment by olivierlemasle** [comment]
@k8s-bot test this issue: #21487

**Comment by olivierlemasle** [comment]
@derekwaynecarr Could you please re-test this pull request?

**Comment by wojtek-t** [comment]
@k8s-bot test this please github issue: #IGNORE (jenkins issues)

**Comment by kargakis** [comment]
I can confirm this fixes kube-push.sh. Thanks.

**Comment by derekwaynecarr** [comment]
@k8s-bot test this please github issue: #IGNORE (jenkins issues)

**Pull request merged**
