### PR TITLE
WIP: scheduler: contextual logging

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This makes kube-scheduler log output more useful.

#### Which issue(s) this PR fixes:
Related-to: https://github.com/kubernetes/kubernetes/issues/91633

#### Special notes for your reviewer:

The basic work is in the initial commit. The commits at the end start with full instrumentation and then gradually reduce the runtime overhead.

Someone needs to decide what the right tradeoff between information in log entries and runtime performance is.

#### Does this PR introduce a user-facing change?
```release-note
kube-scheduler log output is more informative.
```

### CODE REVIEW

**Comment by knelasevero** [comment]
I want to take this over.

Should we discuss the tradeoff between information in log entries versus runtime performance in the issue or here?

**Comment by pohly** [comment]
Beware that a newer klog will be needed to prevent panics when a test leaks goroutines that continue to log through ktesting, see https://github.com/kubernetes/klog/pull/337

**Comment by pohly** [comment]
@knelasevero  is continuing with this work.

**Pull request closed without merging**
