### PR TITLE
Follow go style guide and fix versioning doc link

### PR DESCRIPTION
**Pull request by sakeven**
Signed-off-by: sakeven <jc5930@sina.cn>

**What this PR does / why we need it**:

1. Follow go style guide
  * should drop = "" from declaration of var gitMajor; it is the zero value
  * should omit type string from declaration of var gitVersion; it will be inferred from the right-hand side
2. Fix  versioning doc link.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
/lgtm
/approve no-issue


```I0915 04:08:23.999] FAILED   hack/make-rules/../../hack/verify-golint.sh	60s
I0915 04:08:23.999] Verifying hack/make-rules/../../hack/verify-govet.sh
W0915 04:08:24.100] Some packages in hack/.golint_failures are passing golint. Please remove them.
W0915 04:08:24.100] 
W0915 04:08:24.101]   pkg/version
W0915 04:08:24.101]

**Comment by xiangpengzhao** [comment]
@sakeven as @thockin mentioned, please remove `pkg/version` from `hack/.golint_failures` and commit it.

**Comment by sakeven** [comment]
@xiangpengzhao @thockin updated, PTAL.

**Pull request merged**
