### PR TITLE
remove unused `pkg/api/unversioned`

### LINKED ISSUE #61084: `pkg/api/unversioned` should be removed
/kind cleanup
/sig api-machinery

`pkg/api/unversioned` is deprecated in 2016, and marked if heapster stop using this pkg, it can be safely removed. Since https://github.com/kubernetes/heapster/pull/1537, heapster not use it anymore. So it's time to remove it.

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

clean code, see #61084 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #61084

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm

These got moved when to meta/v1, but we had cycles back then so we couldn't delete these.

/assign @liggitt 
for approval.

**Comment by deads2k** [comment]
@smarterclayton cruft removal

**Comment by smarterclayton** [comment]
Yay

**Comment by deads2k** [comment]
> Yay

I take this to mean approved.  This is dead code.  Tagging.

**Pull request merged**
