### PR TITLE
README.md the kube-dns outdated link

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
the release1.5 that the README.md file the kube-dns outdated link
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```NONE

### CODE REVIEW

**Comment by spxtr** [comment]
I don't think we need to fix this on the 1.5 branch. Do we have any docs pointing to that README?

**Comment by zmerlynn** [comment]
Agree with @spxtr, is there any reason this is a direct patch on the branch?

**Comment by jianglingxia** [comment]
I have not found docs pointing to that README right now ,but now mater branch has changed that : https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns 
in the page I think the named Administrators guide  change to Kubernetes DNS Admin Guide ?what about you? @spxtr @zmerlynn

**Comment by spxtr** [comment]
It looks like it's been fixed on master, so we don't need to fix it on all the release branches.

**Pull request closed without merging**
