### PR TITLE
Graduate WarningHeader feature to GA

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Graduates the WarningHeader feature to GA

GA criteria:

- [x] At least two releases after Beta
- [x] Complete test plan for implemented items
- [x] Implement in-process helpers for admission warnings
- [x] Gather feedback on metric structure and use from multi-cluster admins
- [x] Implement in-process helpers for field-level validation warnings - https://github.com/kubernetes/kubernetes/pull/101688
- [x] API server output of Warning headers for deprecated API use is unconditionally enabled (this PR)
- [x] Server metric for deprecated API use is registered at stability level STABLE (this PR)

#### Does this PR introduce a user-facing change?
```release-note
The `WarningHeader` feature is now GA and is unconditionally enabled. The `apiserver_requested_deprecated_apis` metric has graduated to stable status. The `WarningHeader` feature-gate is no longer operative and will be removed in v1.24. 
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
[KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1693-warnings
```

xref https://github.com/kubernetes/enhancements/issues/1693

### CODE REVIEW

**Comment by liggitt** [comment]
/assign @logicalhan

for metric graduation approval

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve
(from instrumentation)

**Comment by logicalhan** [comment]
Probably should amend the release note to include the metric change.

**Comment by ehashman** [comment]
+1 to @logicalhan, metric + feature gate changes also LGTM :)

**Pull request merged**
