### PR TITLE
Add node label to cAdvisor prometheus metrics

### PR DESCRIPTION
**Pull request by liuxu623**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Add node label to cAdvisor prometheus metrics
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Add node label to cAdvisor prometheus metrics
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dashpole** [comment]
I thought prometheus already supported doing this with relabeling?  What is the use-case for this change?

**Comment by liuxu623** [comment]
> I thought prometheus already supported doing this with relabeling? What is the use-case for this change?

prometheus relabel node label depend use kubernetes_sd_configs, not all users use kubernetes_sd_configs.

**Comment by dashpole** [comment]
@brancz  @kubernetes/sig-instrumentation-api-reviews 
Do we want the kubelet attaching node information (including node name) to metrics as labels?  Or is that the responsibility of the entity scraping metrics?

**Comment by ehashman** [comment]
> prometheus relabel node label depend use kubernetes_sd_configs, not all users use kubernetes_sd_configs.

Sure but no matter how we're scraping this info from cadvisor, the node info should be present in the metadata from the scrape job, no?

I tend to agree that this is the responsibility of the entity scraping metrics as opposed to something we should be attaching at a label/metric level.

**Comment by liuxu623** [comment]
> > prometheus relabel node label depend use kubernetes_sd_configs, not all users use kubernetes_sd_configs.
> 
> Sure but no matter how we're scraping this info from cadvisor, the node info should be present in the metadata from the scrape job, no?
> 
> I tend to agree that this is the responsibility of the entity scraping metrics as opposed to something we should be attaching at a label/metric level.

If we don't use `kubernetes_sd_configs`, maybe we couldn't get correct the nodeName in k8s.

**Pull request closed without merging**
