### PR TITLE
dependencies: update klog to v2.40.1

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

The new release adds support for multi-line string output (required for
contextual logging) and Verbose.InfoSDepth (required to properly attach
verbosity to some log messages in helper code).

#### Does this PR introduce a user-facing change?
```release-note
In text format, log messages that previously used quoting to prevent multi-line output (for example, text="some \"quotation\", a\nline break") will now be printed with more readable multi-line output without the escape sequences.
```

### CODE REVIEW

**Comment by pohly** [comment]
/hold

The update klog segfaults when passed a nil fmt.Stringer. I'll investigate how that was handled before. 

https://github.com/kubernetes/klog/issues/278

**Comment by dims** [comment]
@pohly please update to https://github.com/kubernetes/klog/tree/v2.40.1 of klog

**Comment by dims** [comment]
/approve
/lgtm
/assign @liggitt @thockin 
(for root approval)

**Pull request merged**
