### PR TITLE
Add full default list for scheduler policy configuration.

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/cc @bsalamat

### CODE REVIEW

**Comment by gyliu513** [comment]
@kubernetes/sig-scheduling-pr-reviews

**Comment by bsalamat** [comment]
/lgtm
Thanks, @gyliu513!

**Pull request closed without merging**
