### PR TITLE
Remove old salt configs

### PR DESCRIPTION
**Pull request by roberthbailey**
Stop copying certs into /usr/share/nginx/ since nothing relies on that location any longer.

GKE no longer relies on the old location, and was the only reason we left this in for backwards compatibility.

### CODE REVIEW

**Comment by jlowdermilk** [comment]
lgtm

**Comment by nikhiljindal** [comment]
Shippable is red.
@roberthbailey Can you please take a look?

**Comment by jlowdermilk** [comment]
I forgot there's a test for the legacy cert location. I'll see if I can find it.

**Comment by roberthbailey** [comment]
One failed with

```
F0511 18:03:28.562099    9335 integration.go:946] FAILED: (Scheduler probably didn't process deletion of 'phantom.bar') Pod never started running: timed out waiting for the condition
!!! Error in ./hack/test-integration.sh:48
  '"${KUBE_OUTPUT_HOSTBIN}/integration" --v=${LOG_LEVEL} --api-version="$1" --max-concurrency="${KUBE_INTEGRATION_TEST_MAX_CONCURRENCY}"' exited with status 255
Call stack:
  1: ./hack/test-integration.sh:48 runTests(...)
  2: ./hack/test-integration.sh:62 main(...)
Exiting with status 1
+++ [0511 18:03:28] Integration test cleanup complete
```

The other failed with
```
F0511 17:59:18.440449   11915 integration.go:399] static-pod-from-spec FAILED: mirror pod has not been created or is not running: timed out waiting for the condition
!!! Error in ./hack/test-integration.sh:48
  '"${KUBE_OUTPUT_HOSTBIN}/integration" --v=${LOG_LEVEL} --api-version="$1" --max-concurrency="${KUBE_INTEGRATION_TEST_MAX_CONCURRENCY}"' exited with status 255
Call stack:
  1: ./hack/test-integration.sh:48 runTests(...)
  2: ./hack/test-integration.sh:62 main(...)
Exiting with status 1
+++ [0511 17:59:18] Integration test cleanup complete
```

**Comment by roberthbailey** [comment]
I rebased and re-pushed. Let's see if that makes shippable happy.

**Comment by roberthbailey** [comment]
Ok. I searched for the filesystem location in the repo and didn't see anything obvious.

**Comment by jlowdermilk** [comment]
There is an e2e test for cert file location, but it doesn't check the legacy dir, so shouldn't need changing. Hopefully rebase fixes.

**Pull request merged**
