### PR TITLE
Adding framework to allow multiple upgrade tests

### PR DESCRIPTION
**Pull request by krousey**
**What this PR does / why we need it**: This adds a framework for multiple tests to run during an upgrade. This also moves the existing services test to that framework.

### CODE REVIEW

**Comment by krousey** [comment]
@k8s-bot cvm gke e2e test this

**Comment by krousey** [comment]
@fejta please review/approve

**Comment by fejta** [comment]
I'll send you two a PR that adds you as owners
/lgtm
/approve

**Pull request merged**
