### PR TITLE
rev etcd to 2.0.12

### PR DESCRIPTION
**Pull request by brendandburns**
@davidopp @lavalamp @thockin

### CODE REVIEW

**Comment by dchen1107** [comment]
Are we comfortable to upgrade etcd server to a new version now?

**Comment by thockin** [comment]
The risk of this falling over is scary - what's the reward?

**Comment by lavalamp** [comment]
Very scary, esp since I have no way of telling what source was sitting on your computer when you pushed the button.

**Comment by davidopp** [comment]
> Very scary, esp since I have no way of telling what source was sitting on your computer when you pushed the button.

Not disagreeing, but can you explain? Isn't the makefile just building a Docker container from a binary it fetches? How is source code sitting on his computer related?

**Comment by lavalamp** [comment]
The makefile builds source.

**Comment by dchen1107** [comment]
For issue #10122, @cjcullen  and I discussed, the current proposed solution is not starting any pods / containers until network configuration is done. In this case, shouldn't no rush to upgrade to a new etcd version?

**Comment by alex-mohr** [comment]
etcd 2.0.9 was also built from someone's desktop.   After chatting with a few people and looking at the CLs pulled into 2.0.12 -- especially fixes for bugs that cause an etcd install to become semi-permanently unhealthy -- it seems like a reasonable approach to switch to it as the least-worst option.

And if the release-of-etcd process is scary, we should figure out a sustainable long term approach but not block this particular PR on it.

**Comment by dchen1107** [comment]
LGTM based on our offline discussion.

**Comment by dchen1107** [comment]
I am going to merge this one for now, so that @zmerlynn can cut 0.19.3 to include this one. @zmerlynn please make sure you cut 0.19.3 is solely based on 0.19.1 + this pr. Thanks!

**Comment by zmerlynn** [comment]
On it.

**Comment by alex-mohr** [comment]
... and apologies to those not involved in offline discussions.

Note that if we find issues with 2.0.12 in the RC validation process, we can roll it back.

**Comment by dchen1107** [comment]
Ok to test.

**Comment by zmerlynn** [comment]
I'm going to go ahead and merge this - we've had a lot of internal soak time with these bits from a private build.

**Pull request merged**
