### PR TITLE
tighten quota controller interface

### PR DESCRIPTION
**Pull request by deads2k**
While debugging a quota performance problem, I had to chase some references deeper than necessary because the interfaces were overly broad. This tightens them.

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
> /lint

@spxtr Why would this be separate instead of as part of the verify script?

**Comment by spxtr** [comment]
> @spxtr Why would this be separate instead of as part of the verify script?

It's perfectly acceptable for packages to fail golint, and it's up to the reviewer to approve of exceptions. Rather than have some script that ignores [hundreds of packages](https://github.com/kubernetes/kubernetes/blob/master/hack/.golint_failures) entirely, lets make it nice to solve iteratively :)

**Comment by deads2k** [comment]
> It's perfectly acceptable for packages to fail golint, and it's up to the reviewer to approve of exceptions. Rather than have some script that ignores hundreds of packages entirely, lets make it nice to solve iteratively :)

Interesting.  I didn't realize that I had failed linting.

**Pull request merged**
