### PR TITLE
Enable the Go race detector in test-integration

### PR DESCRIPTION
**Pull request by lubinsz**
Signed-off-by: Bin Lu <bin.lu@arm.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind cleanup

**What this PR does / why we need it**:
Enable the Go race detector in test-integration
**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:
None
**Does this PR introduce a user-facing change?**:
None
```release-note
None
```

### CODE REVIEW

**Comment by SataQiu** [comment]
Thanks @lubinsz 
/kind cleanup
/sig testing
/priority backlog
/lgtm
It seems good to me. Could you have a look? @fejta

**Comment by BenTheElder** [comment]
This makes sense in theory but seems to be introducing a lot of failures (which is not surprising). It might be challenging to actually get in ...

**Pull request closed without merging**
