### PR TITLE
Backport Konnectivity Proxy 0.1.5 to release-1.27.

### PR DESCRIPTION
**Pull request by jkh52**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This picks up bugfixes in delta: https://github.com/kubernetes-sigs/apiserver-network-proxy/compare/v0.1.2...v0.1.5

#### Which issue(s) this PR fixes:

Notable fixes:
* A fix for nil deref: https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/513
* Metric bugfix: https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/511
* CVE fixes.

#### Special notes for your reviewer:

Similar PR for release-1.28 branch: https://github.com/kubernetes/kubernetes/pull/120884

#### Does this PR introduce a user-facing change?
```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
/lgtm

would be good to get @andrewsykim or @cheftako to add the approval and labels

**Comment by jkh52** [comment]
Friendly ping.

/assign @sttts

**Comment by liangyuanpeng** [comment]
Kindly ping @deads2k @sttts

**Review by liangyuanpeng — APPROVED** [review]

**Pull request closed without merging**
