### PR TITLE
e2e: suppress too verbose output

### LINKED ISSUE #111868: e2e: too verbose ginkgo output
### What would you like to be added?

After migration to Ginkgo v2 there is quite a bit of additional unnecessary output at the start and end of a test suite run. This is annoying in particular when running a single failing test with `-ginkgo.v` because the test failure is not visible at the end of the output and a lot of scrolling is necessary.

The output points to https://github.com/kubernetes/kubernetes/blob/d5fdf3135e7c99e5f81e67986ae930f6a2ffb047/test/e2e/e2e_test.go#L142-L144

Example:
```
...
S[ReportAfterEach] TOP-LEVEL
  /nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e_test.go:143
...
[sig-node] DRA [Feature:DynamicResourceAllocation] kubelet
  registers plugin
  /nvme/gopath/src/k8s.io/kubernetes/test/e2e/dra/dra.go:29
[BeforeEach] [sig-node] DRA [Feature:DynamicResourceAllocation]
  /nvme/gopath/src/k8s.io/kubernetes/test/e2e/framework/framework.go:186
STEP: Creating a kubernetes client 08/16/22 13:07:45.663
Aug 16 13:07:45.663: INFO: >>> kubeConfig: /var/run/kubernetes/admin.kubeconfig
...
S[ReportAfterEach] TOP-LEVEL
  /nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e_test.go:143
S[ReportAfterEach] TOP-LEVEL
  /nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e_test.go:143
S[ReportAfterEach] TOP-LEVEL
  /nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e_test.go:143
S[ReportAfterEach] TOP-LEVEL
  /nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e_test.go:143
S[ReportAfterEach] TOP-LEVEL
  /nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e_test.go:143
S[ReportAfterEach] TOP-LEVEL
  /nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e_test.go:143
S[ReportAfterEach] TOP-LEVEL
  /nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e_test.go:143
S
------------------------------
[SynchronizedAfterSuite] 
/nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e.go:87
[SynchronizedAfterSuite] TOP-LEVEL
  /nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e.go:87
{"msg":"Test Suite completed","completed":0,"skipped":7067,"failed":1,"failures":["[sig-node] DRA [Feature:DynamicResourceAllocation] kubelet registers plugin"]}
Aug 16 13:07:45.790: INFO: Running AfterSuite actions on all nodes
Aug 16 13:07:45.790: INFO: Running Cleanup Action: k8s.io/kubernetes/test/e2e/storage.glob..func20.2
Aug 16 13:07:45.790: INFO: Running Cleanup Action: k8s.io/kubernetes/test/e2e/storage.glob..func10.2
Aug 16 13:07:45.790: INFO: Running Cleanup Action: k8s.io/kubernetes/test/e2e/storage.glob..func9.2
Aug 16 13:07:45.790: INFO: Running Cleanup Action: k8s.io/kubernetes/test/e2e/storage/vsphere.glob..func17.3
Aug 16 13:07:45.790: INFO: Running Cleanup Action: k8s.io/kubernetes/test/e2e/storage/vsphere.glob..func9.2
Aug 16 13:07:45.790: INFO: Running Cleanup Action: k8s.io/kubernetes/test/e2e/storage/vsphere.glob..func4.2
Aug 16 13:07:45.790: INFO: Running Cleanup Action: k8s.io/kubernetes/test/e2e/storage/vsphere.glob..func1.3
[SynchronizedAfterSuite] TOP-LEVEL
  /nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e.go:87
Aug 16 13:07:45.790: INFO: Running AfterSuite actions on node 1
------------------------------
[SynchronizedAfterSuite] PASSED [0.000 seconds]
[SynchronizedAfterSuite] 
/nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e.go:87

  Begin Captured GinkgoWriter Output >>
    [SynchronizedAfterSuite] TOP-LEVEL
      /nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e.go:87
    Aug 16 13:07:45.790: INFO: Running AfterSuite actions on all nodes
    Aug 16 13:07:45.790: INFO: Running Cleanup Action: k8s.io/kubernetes/test/e2e/storage.glob..func20.2
    Aug 16 13:07:45.790: INFO: Running Cleanup Action: k8s.io/kubernetes/test/e2e/storage.glob..func10.2
    Aug 16 13:07:45.790: INFO: Running Cleanup Action: k8s.io/kubernetes/test/e2e/storage.glob..func9.2
    Aug 16 13:07:45.790: INFO: Running Cleanup Action: k8s.io/kubernetes/test/e2e/storage/vsphere.glob..func17.3
    Aug 16 13:07:45.790: INFO: Running Cleanup Action: k8s.io/kubernetes/test/e2e/storage/vsphere.glob..func9.2
    Aug 16 13:07:45.790: INFO: Running Cleanup Action: k8s.io/kubernetes/test/e2e/storage/vsphere.glob..func4.2
    Aug 16 13:07:45.790: INFO: Running Cleanup Action: k8s.io/kubernetes/test/e2e/storage/vsphere.glob..func1.3
    [SynchronizedAfterSuite] TOP-LEVEL
      /nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e.go:87
    Aug 16 13:07:45.790: INFO: Running AfterSuite actions on node 1
  << End Captured GinkgoWriter Output
------------------------------
[ReportAfterSuite] Kubernetes e2e suite report
/nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e_test.go:147
[ReportAfterSuite] TOP-LEVEL
  /nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e_test.go:147
------------------------------
[ReportAfterSuite] PASSED [0.000 seconds]
[ReportAfterSuite] Kubernetes e2e suite report
/nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e_test.go:147

  Begin Captured GinkgoWriter Output >>
    [ReportAfterSuite] TOP-LEVEL
      /nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e_test.go:147
  << End Captured GinkgoWriter Output
------------------------------

Ran 1 of 7068 Specs in 0.603 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 7067 Skipped
--- FAIL: TestE2E (0.76s)
FAIL
```

/cc @onsi

### Why is this needed?

Running tests in a console became harder than it used to be.

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup
/kind regression

#### What this PR does / why we need it:

The migration to Ginkgo v2 in Kubernetes v1.25.0 added thousand lines of extra output each time the e2e.test binary gets invoked, even when running only a single test:

```
...
S[ReportAfterEach] TOP-LEVEL
  /nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e_test.go:143
S[ReportAfterEach] TOP-LEVEL
  /nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e_test.go:143
S[ReportAfterEach] TOP-LEVEL
  /nvme/gopath/src/k8s.io/kubernetes/test/e2e/e2e_test.go:143
...
```

#### Which issue(s) this PR fixes:
Fixes #111868

#### Special notes for your reviewer:

It's probably worth backporting this.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/lgtm
/approve
@liggitt @dims for deps

Thankssssssss

**Comment by aojea** [comment]
the output of the e2e tests is really clean right now :1st_place_medal:

**Comment by liggitt** [comment]
/approve

I dropped the release note, I don't think that warrants addition to the CHANGELOG

**Comment by pohly** [comment]
Let's also cherry-pick to release-1.25 -> https://github.com/kubernetes/kubernetes/pull/112161

**Pull request merged**
