### PR TITLE
[FEATURE-SERVERSIDE-APPLY] Fix unstructured meta accessor for ManagedFields

### PR DESCRIPTION
**Pull request by apelisse**
**What type of PR is this?**
> /kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
lgtm, but what about a test?

**Comment by apelisse** [comment]
That actually fixes the test that was broken. I do consider the test going red to green to be a test :-)

**Pull request merged**
