### PR TITLE
Field validation e2e to conformance

### PR DESCRIPTION
**Pull request by kevindelgado**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

Converts field validation e2e tests into conformance tests

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
This is dependent on https://github.com/kubernetes/kubernetes/pull/115271 to merge first

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
```
KEP: https://github.com/kubernetes/enhancements/issues/2885

### CODE REVIEW

**Comment by aojea** [comment]
You should graduate first the feature, let's soak the tests and demonstrate that they run without flakes for 1 or 2 weeks (I can't remember) and then you send a PR for promoting them to conformance , but I don't think we should do everything at the same time 

cc: @liggitt and @dims to correct me

**Comment by kevindelgado** [comment]
> You should graduate first the feature, let's soak the tests and demonstrate that they run without flakes for 1 or 2 weeks (I can't remember) and then you send a PR for promoting them to conformance , but I don't think we should do everything at the same time
> 
> cc: @liggitt and @dims to correct me

Sorry this was just stacked on https://github.com/kubernetes/kubernetes/pull/115271, rebased now that that has merged.

Happy to wait as long as necessary, just wanted to have this PR up for review in the meantime

**Comment by liggitt** [comment]
promotion lgtm once testgrid signal shows stability, but I'm not a conformance reviewer

/unassign
/assign @dims @johnbelamaric

**Comment by johnbelamaric** [comment]
> You should graduate first the feature, let's soak the tests and demonstrate that they run without flakes for 1 or 2 weeks (I can't remember) and then you send a PR for promoting them to conformance , but I don't think we should do everything at the same time

Supposed to have no flakes for 14 days.

**Comment by kevindelgado** [comment]
/assign @apelisse

I am leaving the kubernetes project and handing this off to Antoine to shepard through GA

**Comment by dims** [comment]
@apelisse do you want to update this PR or open a fresh one?

@kevindelgado Best Wishes!

**Comment by apelisse** [comment]
I don't think it'll be easy to modify the PR directly, I'll open a new one.

**Pull request closed without merging**
