### PR TITLE
Correct the word "Contribution" in many files

### PR DESCRIPTION
**Pull request by truongnh1992**
Although it is spelling mistakes, it might make an affects while reading.

Signed-off-by: Nguyen Hai Truong <truongnh@vn.fujitsu.com>

**What type of PR is this?**
/kind cleanup
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/ok-to-test
/priority backlog
/sig storage
/sig node

**Comment by anarchistHH1983** [comment]
lgtm
/ok-to-test
/priority backlog
/sig storage
/sig node

—

**Review by saad-ali — APPROVED** [review]
/lgtm
/approve

**Pull request closed without merging**
