### PR TITLE
Replace raw string with const var.

### PR DESCRIPTION
**Pull request by k82cn**
Replace raw string with const string var.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36718)

### CODE REVIEW

**Comment by k82cn** [comment]
ping @erictune .

**Comment by k82cn** [comment]
@erictune , any comments on this?

**Comment by k82cn** [comment]
@erictune , any suggestions?

**Comment by thockin** [comment]
/lgtm

LGTM from the bulk LGTM tool

**Pull request merged**
