### PR TITLE
fix gosimple lint check

### PR DESCRIPTION
**Pull request by lala123912**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
go simple, schema.AdditionalProperties.Allows == false should be simplified to ! schema.AdditionalProperties.Allows, etc.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by fedebongio** [comment]
/assign @roycaihw 
Haowei, would you mind taking a look to this one?
/triage accepted

**Comment by roycaihw** [comment]
I didn't find these change being super useful. Is there anything else that the gosimple lint does?

If we do want to make these kind of change, I'd like to see the linter being part of the presubmits, and having a centralized place for tracking and fixing those violations (like what we did with staticcheck). I believe there will be more places having `xxx == false` in our codebase. 

api-machinery is not the right sig to make the decision. Could you file an issue and loop in sig contributor-experience and sig testing?

**Pull request closed without merging**
