### PR TITLE
Automated cherry pick of #38736

### PR DESCRIPTION
**Pull request by ixdy**
Cherry pick of #38736 on release-1.5.

#38736: Rename root BUILD to BUILD.bazel

### CODE REVIEW

**Comment by ixdy** [comment]
I manually fixed `cluster/mesos/docker/util.sh` as well, as this file no longer exists in master.

`docs/` still refer to `build-tools/`, as in master.

cc @mikedanese @spxtr

**Comment by ixdy** [comment]
@k8s-bot build this

**Comment by ixdy** [comment]
verification is failing because the docs need to be updated. I can do that, but then I worry the bot will tag this with `do-not-merge` due to docs changes.

**Comment by mikedanese** [comment]
lgtm

**Comment by spxtr** [comment]
So how do we move this forward? Do we need to rope in the 1.5 owner?

**Comment by mikedanese** [comment]
cc @saad-ali

**Comment by ixdy** [comment]
I'm still not sure what to do about the docs verification failure. Let me see what happens if I update them.

**Comment by ixdy** [comment]
well, everything passes, and mergebot doesn't seem mad at me...

**Comment by ixdy** [comment]
ah, there we go.

I'm not sure what to do here. should we disable the verification check? should we merge manually?

**Comment by spxtr** [comment]
Saad should probably just manually merge.

**Comment by saad-ali** [comment]
Ack, will manually merge to unblock

**Comment by ixdy** [comment]
Thanks! `build-tools/` is now dead! :)

**Pull request merged**
