### PR TITLE
Revert "removes the remainder from ScalerFor method"

### PR DESCRIPTION
**Pull request by shyamjvs**
Reverts kubernetes/kubernetes#58298

Ref https://github.com/kubernetes/kubernetes/issues/59043

```release-note
NONE
```

### CODE REVIEW

**Comment by DirectXMan12** [comment]
I believe I've found the underlying issue (https://github.com/kubernetes/kubernetes/issues/59043#issuecomment-361648494).  Let's try and fix that instead of just reverting.

**Comment by deads2k** [comment]
/hold 

Please wait to see if @DirectXMan12's fix resolves this problem before merging.

**Comment by shyamjvs** [comment]
Let's close this one as the other PR seems to fix the problem.

/close

**Pull request closed without merging**
