### PR TITLE
juju charm updates to support 1.12

### PR DESCRIPTION
**Pull request by kwmonroe**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:

/kind feature

**What this PR does / why we need it**:
This includes updates to the Juju charms to support k8s 1.12.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
This is a relatively large PR, but the bulk of the work comes from refactoring duplicate charm code into a common library, as well as template changes required for 1.12 components (e.g. ingress and default-http-backend).

**Does this PR introduce a user-facing change?**:

```release-note
Update Juju charms to deploy 1.12 by default
```

### CODE REVIEW

**Comment by kwmonroe** [comment]
recheck CLA

**Comment by mikedanese** [comment]
What is the workflow that is going on here? Where was this code reviewed?

/hold

**Comment by mikedanese** [comment]
@kubernetes/sig-cluster-lifecycle-pr-reviews

**Comment by mikedanese** [comment]
Can we document this development workflow for this code so that we have some link back to where this integration is being developed? Right now, I think this is marginally worse then our process for vendored code which at least carries origin with revision.

**Comment by roberthbailey** [comment]
@kwmonroe / @Cynerva - could one (or both) of you come to the next sig cluster lifecycle meeting. Last I talked with folks maintaining this code there wasn't a good place to put it outside of the cluster directory. We now have quite a bit of precedent for creating sig cluster lifecycle repositories for this type of code in the kubernetes-sigs organization, and I think that this would be a prime candidate to move out of core and into a separate repository. 

/cc @timothysc

**Comment by kwmonroe** [comment]
@mikedanese We started working in our [juju-solutions/kubernetes fork](https://github.com/juju-solutions/kubernetes) so that we could land PRs during code freeze, with the intention of merging that work back upstream periodically. This PR represents the first such merge.

@roberthbailey @timothysc I agree that this is not ideal. Needing to work around the freeze is a signal that we're in the wrong location. What's worked well for other projects like ours (kops, kubernetes-anywhere, etc) is not being in kubernetes/kubernetes but in kubernetes/_project_ so I recommend for consistency's sake we just move to kubernetes/charms. There aren't projects like ours in kubernetes-sigs so it would seem odd to go that route unless and until we move the other projects like ours there as well.

**Comment by timothysc** [comment]
/cluster is deprecated, only google maintains things there. 
/unassign @timothysc

**Comment by roberthbailey** [comment]
> @roberthbailey @timothysc I agree that this is not ideal. Needing to work around the freeze is a signal that we're in the wrong location. What's worked well for other projects like ours (kops, kubernetes-anywhere, etc) is not being in kubernetes/kubernetes but in kubernetes/project so I recommend for consistency's sake we just move to kubernetes/charms. There aren't projects like ours in kubernetes-sigs so it would seem odd to go that route unless and until we move the other projects like ours there as well.

Can you open a tracking issue to discuss this? I'd like to rope in more people, but a PR is the wrong place to move this discussion forward.

**Comment by kwmonroe** [comment]
> Can you open a tracking issue to discuss this? I'd like to rope in more people, but a PR is the wrong place to move this discussion forward.

@roberthbailey you bet!  Issue opened over at https://github.com/kubernetes/community/issues/2892

@mikedanese when you put the /hold on, you asked about about code reviews; these commits were reviewed in [PRs to the fork](https://github.com/juju-solutions/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+merged%3A%3E2018-08-01) mentioned earlier.  As this PR only affects code under `cluster/juju`, can it be cleared for merging while we find a new home?

**Comment by kwmonroe** [comment]
After discussions around https://github.com/kubernetes/community/issues/2892, we're working to move ./cluster/juju out of tree. Closing this PR as it will not be relevant much longer.

**Pull request closed without merging**
