### PR TITLE
Automated cherry pick of #53225

### PR DESCRIPTION
**Pull request by crassirostris**
Cherry pick of #53225 on release-1.8.

#53225: Fix basic audit in GCE deploy scripts

### CODE REVIEW

**Comment by crassirostris** [comment]
@roberthbailey Could you please approve?

**Comment by roberthbailey** [comment]
@jpbetz should approve as the release branch manager.

**Comment by crassirostris** [comment]
I see, sorry for bothering!

**Comment by crassirostris** [comment]
@jpbetz Could you please approve?

**Comment by jpbetz** [comment]
@roberthbailey PTAL

**Comment by jpbetz** [comment]
We're about to cut release 1.8.1. We are minimizing the cherry picks we accept to keep the branch stable. If this is a critical fix, please let me know and I'll review, otherwise it will be cherry picked for 1.8.2.  Thanks!

**Comment by jpbetz** [comment]
@crassirostris This one still needs approval.

**Comment by crassirostris** [comment]
@roberthbailey It seems you still has to approve (apply the /approve label)

**Pull request merged**
