### PR TITLE
Update go-restful to get stable sorting in spec

### PR DESCRIPTION
**Pull request by krousey**
This is so we can get stable sorting of required fields and reduce unnecessary churn when regenerating the swagger spec. See https://github.com/emicklei/go-restful/issues/207

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks.

Look at the Shippable failures. This update broke our schema validation, apparently:
```
github.com/GoogleCloudPlatform/kubernetes/pkg/api/validation
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/validation/schema.go:88: invalid operation: models[typeName] (type swagger.ModelList does not support indexing)
```

**Comment by krousey** [comment]
Changed the schema validation to the new API. Everything built locally.

**Comment by bgrant0607** [comment]
LGTM, assuming tests pass.

**Comment by krousey** [comment]
Shippable test timed out on a Pod creation. I requested another run.

**Comment by thockin** [comment]
build break, rolling back, sorry

**Comment by bgrant0607** [comment]
Which build?

**Comment by bgrant0607** [comment]
Travis didn't even start yet:
https://travis-ci.org/GoogleCloudPlatform/kubernetes/builds/64494302

**Comment by bgrant0607** [comment]
And Shippable was green:
https://app.shippable.com/builds/5567a8b17472310c00b375ab

**Comment by krousey** [comment]
It was a local failure that Tim saw while trying to fix another build
failure. He reverted before we figured out that make clean would have fixed
it. It's already been merged in another PR.

**Pull request merged**
