### PR TITLE
Add support for `--restart`

### LINKED ISSUE #4366: kubectl run should support run-once commands
When I run the simplest form of `run-container`:

```
$ kubectl run-container vmarmol-secret vmarmol/secret:latest
```

I expected this to be a one-time pod (it is a command I was running to test HTTPS connections and exits quickly). However, in reality it created a replicaController pod. According to the examples in kubectl.sh:

```
    $ kubectl run-container nginx --image=dockerfile/nginx
    // Starts a single instance of nginx.

    $ kubectl run-container nginx --image=dockerfile/nginx --replicas=5
    // Starts a replicated instance of nginx.
```

I was expecting to need to use the `--replicas` flag in order to get that behavior. Is this intended? The implementation currently takes the default of `--replicas=1` which probably explains the behavior.

### PR DESCRIPTION
**Pull request by brendandburns**
@bgrant0607 @deads2k @jlowdermilk 

Fixes #4366

### CODE REVIEW

**Comment by brendandburns** [comment]
Depends on #12220 please only review the second commit.

**Comment by brendandburns** [comment]
Rebased and re-pushed.

--brendan

**Comment by jlowdermilk** [comment]
Second commit lgtm. One request: can you add an e2e test for `kubectl run` creating a pod when `--restart` is `OnFailure|Never`? Should be able to copy [existing run test](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/kubectl.go#L499) with minor changes.

**Comment by bgrant0607** [comment]
Please add "Fixes #4366" to your PR description.

**Comment by brendandburns** [comment]
Added requested end-to-end tests.  Tests are green.  Please take another look.

Thanks!
--brendan

**Comment by jlowdermilk** [comment]
lgtm

**Comment by jlowdermilk** [comment]
Needs rebase (1st commit merged with changes?).

**Comment by brendandburns** [comment]
Rebased, re-pushed, tests are all green.

**Pull request merged**
