### PR TITLE
Fix some lint errors in pkg/proxy

### PR DESCRIPTION
**Pull request by bradhoekstra**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix golint failures of

* pkg/proxy/iptables
* pkg/proxy/utils

**Which issue(s) this PR fixes**:
Re: #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks for the linter fixes @bradhoekstra 
/ok-to-test
/priority backlog

**Review by cmluciano — COMMENTED** [review]
/lgtm

Thanks!

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
