### PR TITLE
Remove GA featuregate about KubeletPodResources in 1.30

### PR DESCRIPTION
**Pull request by bzsuni**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Removed generally available feature gate `KubeletPodResources`.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None 
```

### CODE REVIEW

**Comment by bzsuni** [comment]
/assign @dims
for features approval, thank you very much

**Comment by bart0sh** [comment]
/lgtm
/assign @mrunalp @dchen1107 
for a final approval

**Comment by sftim** [comment]
Changelog suggestion
```markdown
Removed generally available feature gate `KubeletPodResources`.
```

**Comment by bzsuni** [comment]
> Changelog suggestion
> 
> ```
> Removed generally available feature gate `KubeletPodResources`.
> ```

Done, thank you for your comments

**Comment by bzsuni** [comment]
@dims 
Could you please help me approve this pr?

**Pull request merged**
