### PR TITLE
Nominate Huang-Wei to scheduler approvers

### PR DESCRIPTION
**Pull request by Huang-Wei**
*What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

According to the requirement of Approver at [community-membership.md](https://github.com/kubernetes/community/blob/master/community-membership.md), I meet the following requirements so I'd like to add myself as an approver of scheduler.

I have:

- Reviewer of the codebase for at least 3 months (since Nov. 2018)
- Primary reviewer for ~10 substantial PRs to the codebase
- Merged [33 PRs](https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=state%3Amerged+is%3Apr+author%3AHuang-Wei+) to k/k and [5 PRs](https://prow.k8s.io/pr?query=is%3Apr%20is%3Amerged%20author%3AHuang-Wei) to kubernetes sub repos.
- Reviewed [~80 PRs](https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+reviewed-by%3AHuang-Wei+) to the codebase

As an approver,

* I agree to only approve familiar PRs
* I agree to be responsive to review/approve requests as per community expectations
* I agree to continue my reviewer work as per community expectations
* I agree to mentor contributors and reviewers

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

cc/ @bsalamat @k82cn 
/sig scheduling

### CODE REVIEW

**Comment by k82cn** [comment]
LGTM, thanks very much for your contribution. 
Let's wait for Bobby's comments :)

 PS, please also add the links on your merged PRs.

**Comment by Huang-Wei** [comment]
> PS, please also add the links on your merged PRs.

Thanks Klaus. Done.

/retest

**Comment by bsalamat** [comment]
/lgtm

Thanks a lot, @Huang-Wei for your contributions to SIG Scheduling!

**Comment by Huang-Wei** [comment]
Kindly ping @wojtek-t @liggitt for approval.

**Comment by liggitt** [comment]
/approve
based on lgtm from sig-scheduling leads and existing scheduling maintainers

**Pull request merged**
