### PR TITLE
adjust order and fix typo for kube upgrade

### PR DESCRIPTION
**Pull request by haojue**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
PerformPostUpgradeTasks has been updated, the docstring comment of `func runApply` needs to be updated accordingly.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pacoxu — COMMENTED** [review]
/lgtm
/priority backlog

**Review by neolit123 — COMMENTED** [review]
thanks, this can wait after code freeze (1.28)
/approve

**Comment by haojue** [comment]
> thanks, this can wait after code freeze (1.28) /approve

thanks @pacoxu and @neolit123 , I noticed there is a failure in the checks, as this is only docstring comment update, so might be stability issue of CI system?

**Pull request merged**
