### PR TITLE
deprecate ExperimentalHostUserNamespaceDefaulting

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
#### What type of PR is this?

/kind cleanup
/sig node
/cc @rata 

#### What this PR does / why we need it:

See  here: https://github.com/kubernetes/kubernetes/issues/76982

#### Special notes for your reviewer:

It is safe to take for 1.27, but may be too late

#### Does this PR introduce a user-facing change?

```release-note
Marked the feature gate `ExperimentalHostUserNamespaceDefaulting` as deprecated.
Enabling the feature gate already had no effect; the deprecation allows for removing the feature gate in a future release.
```

### CODE REVIEW

**Review by rata — APPROVED** [review]
LGTM

@SergeyKanzhelev I had this in my TODO, but you managed to get to it before. Thanks!

**Comment by sftim** [comment]
Changelog suggestion:
```markdown
Marked the feature gate `ExperimentalHostUserNamespaceDefaulting` as deprecated.
Enabling the feature gate already had no effect; the deprecation allows for removing the feature gate in a future release.
```

**Comment by sftim** [comment]
We **can** deprecate this, but (minor thing) watch out that https://kubernetes.io/blog/2023/03/17/upcoming-changes-in-kubernetes-v1-27/ didn't mention it.

**Comment by SergeyKanzhelev** [comment]
> We **can** deprecate this, but (minor thing) watch out that https://kubernetes.io/blog/2023/03/17/upcoming-changes-in-kubernetes-v1-27/ didn't mention it.

Hardly the major theme as it doesn't deprecate any functionality, just the ability to turn the flag on/off

**Comment by sftim** [comment]
I wonder if we might also want to remove the feature gate entirely.

**Comment by rata** [comment]
I was about to open a PR to remove it, but it was already done long ago

**Pull request merged**
