### PR TITLE
'core' package to prevent dependency creep and isolate core functiona…

### PR DESCRIPTION
**Pull request by jayunit100**
**What this PR does / why we need it**:

Solves these two problems: 

- Top level Scheduler root directory has several files in it that are needed really by the factory and algorithm implementations.  Thus they should be subpackages of scheduler.
- In addition scheduler.go and generic_scheduler.go don't naturally differentiate themselves when they are in the same package.  scheduler.go is eseentially the daemon entry point and so it should be isolated from the core 

*No release note needed*

### CODE REVIEW

**Comment by jayunit100** [comment]
@k8s-bot bazel test this

**Comment by jayunit100** [comment]
TO ease the review process, what we're doing here is 

- moving extender, equivalencecache, generic_scheduler.go into core.
- updating the algorithm and factory packages as necessary to reflect this
- later  we might decide the use case for equivalencecache means it should be in the same place as schedulercache hierarchichally, for now however, its best to keep it close by to its brothers and sisters that are all migrating from the top level package.

**Comment by jayunit100** [comment]
follow up to #40696

**Review by timothysc — APPROVED** [review]
lgtm... @wojtek-t I've asked @jayunit100 to rationalize some of the libraries and structure of the scheduler as part of 1.6 cleanup release to make it easier to reason about and import.

**Comment by jayunit100** [comment]
bumppp :)

**Comment by jayunit100** [comment]
bumpity bumpity, shall we merge ?:)

**Pull request merged**
