### PR TITLE
cluster/gce/coreos: Update addon manifests.

### PR DESCRIPTION
**Pull request by yifan-gu**
cc @yujuhong @timstclair @ArtfulCoder

### CODE REVIEW

**Comment by dchen1107** [comment]
I think we talked about before not to duplicate those addons manifests, so that you don't need to always upgrade those config files. Can you take a look at prepare-manifests-tar() in cluster/gce/util.sh, which creates a tarball of kube-system manifests for a given cluster. Today, it is used for trusty-based only, but I don't see any reason not being extended to other os distro.

**Comment by yifan-gu** [comment]
@dchen1107 Updated the manifests. Maybe we should get this in first, as the upstream manifests are somehow broken today.

**Comment by yujuhong** [comment]
@dchen1107, are you okay with the PR as it is (and a separate PR as you suggested in https://github.com/kubernetes/kubernetes/pull/22663#issuecomment-193445439 to remove duplicated manifests) or do you want to go straight to your suggestion?

**Comment by yifan-gu** [comment]
Ping @dchen1107 ?

**Comment by dchen1107** [comment]
I am ok to let this in first to unblock rktnetes 1.0, but can we address the issue I pointed out at https://github.com/kubernetes/kubernetes/pull/22663#issuecomment-193445439 before 1.3?

**Comment by yifan-gu** [comment]
@dchen1107 Sure, btw I heard we are moving to ansible? What's the plan/proposal of that? 
@sjpotter Do you want to take a swing on this after the cadvisor integration work?

**Comment by dchen1107** [comment]
@mikedanese is working on that, but I don't know the latest status. 

LGTM

**Comment by yifan-gu** [comment]
Removing LGTM, as https://github.com/kubernetes/kubernetes/commit/3e1c0b59517c8ceb39dfdc59e1748688f5f86688 Changes the way we run kube-addons.
We need to update this PR to use that change.

**Comment by euank** [comment]
@yifan-gu necessary changes might be able to be cherry picked without too much trouble from https://github.com/coreos/kubernetes/commit/a4e570c76e3219d5fee1154ace316bd7439817fd

**Comment by yifan-gu** [comment]
Thanks for the heads up, will cherry pick the changes.

**Comment by yifan-gu** [comment]
Tested, the kube-up works fine with this PR.

**Comment by euank** [comment]
On a related note, there will also be a need for CNI plugins to be placed correctly for rktnetes quite soon. I'd be happy to make an additional pull request for it (I have most of the work [here](https://github.com/euank/kubernetes/tree/cni-plugins)), but if it's more appropriate to include here feel free.

I'm having a couple kube-up issues with this PR unfortunately, so I'd like to hold off on merging while I dig into that a little more.

**Comment by euank** [comment]
My problem above was a misunderstanding on my part; I retract my concern.

Changes LGTM, though I agree that the overall approach could be better (and could/should be addressed with a future PR)

**Comment by yifan-gu** [comment]
Fix https://github.com/kubernetes/kubernetes/issues/25219

**Comment by yifan-gu** [comment]
But the l7 is crashing loop because the liveness probe is failing. Investigating..

**Comment by yifan-gu** [comment]
Can't reproducing the l7 loadbalencer crashloop after rebasing now.

**Comment by yifan-gu** [comment]
This PR also installs the CNI binaries into `/opt/cni/`, which is required by #25062.

**Pull request merged**
