### PR TITLE
add newline for  unimplemented RequiredDuringSchedulingRequiredDuringExecution

### LINKED ISSUE #50483: RequiredDuringSchedulingRequiredDuringExecution was treated as comments of RequiredDuringSchedulingIgnoredDuringExecution
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

Unimplemented `RequiredDuringSchedulingRequiredDuringExecution` should not be treated as comments of `RequiredDuringSchedulingIgnoredDuringExecution`

* [pkg/api/types.go#L1937](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1937)

* [staging/src/k8s.io/api/core/v1/types.go#L2155](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L2155)

> // NOT YET IMPLEMENTED. TODO: Uncomment field once it is implemented.

**What you expected to happen**:
add newline to separate them.

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:
Unimplemented `RequiredDuringSchedulingRequiredDuringExecution` should not be treated as  comments of `RequiredDuringSchedulingIgnoredDuringExecution`

* [pkg/api/types.go#L1937](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/types.go#L1937)

* [staging/src/k8s.io/api/core/v1/types.go#L2155](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L2155)

>  // NOT YET IMPLEMENTED. TODO: Uncomment field once it is implemented.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:fixes #50483 

**Special notes for your reviewer**:

* Add an empty line to separate them. 

/cc @aveshagarwal @bsalamat @gyliu513 @k82cn @timothysc

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by bsalamat** [comment]
Those fields are not implemented yet. TODOs should remain.

**Comment by dixudx** [comment]
@bsalamat Pod affinity/anti-affinity has already been enabled in beta feature since `v1.6`.

**Comment by k82cn** [comment]
@dixudx , the `TODO` is for `RequiredDuringSchedulingRequiredDuringExecution` which is not implemented yet; so we can not remove it.

But it should NOT be included as `RequiredDuringSchedulingIgnoredDuringExecution`'s comments, can you find a way to correct that? maybe an empty line?

**Comment by k82cn** [comment]
please also run ./hack/update-all.sh to update docs.

**Comment by dixudx** [comment]
@k82cn PTAL. Thanks.

**Comment by bsalamat** [comment]
@dixudx RequiredDuringSchedulingRequiredDuringExecution is not implemented, but the new version of the PR which leaves the TODOs in place and adds blank lines to remove the TODOs from generated files LGTM.

**Review by gyliu513 — COMMENTED** [review]
/lgtm

**Comment by dixudx** [comment]
@gyliu513 @k82cn @caesarxuchao Need your approval. Thanks.

**Comment by k82cn** [comment]
/lgtm

@smarterclayton , would you help to approve that? This PR add a empty line after `RequiredDuringSchedulingRequiredDuringExecution` which is a member that commented out; it fixes the doc error that includes unnecessary comments to the other member.

**Comment by k82cn** [comment]
ping for approve :).

**Comment by sttts** [comment]
Poor @smarterclayton should hire an assistent for approvals now that @lavalamp is out. Looks like @thockin could approve too.

**Pull request merged**
