### PR TITLE
Continue streaming kubelet logs when runtime is unavailable

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Container runtimes are able to run existing containers even when their main CRI server is not available for any reason. The call to the container status RPC happens quite frequently during log parsing, means that a single CRI interruption will also abort streaming the logs.

We now check that specific use case and continue following the log streaming if the CRI is unavailable. We still abort the streaming accordingly if the CRI comes back and the container status reports that the workload has exited.

#### Which issue(s) this PR fixes:

Refers to https://github.com/cri-o/cri-o/issues/7826

#### Does this PR introduce a user-facing change?

```release-note
Continue streaming kubelet logs when the CRI server of the runtime is unavailable.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
PTAL @kubernetes/sig-node-pr-reviews

**Comment by kannon92** [comment]
Is this patch just related to kubelet logs?

**Comment by kannon92** [comment]
> Is this patch just related to kubelet logs?

I researched this. The code that @saschagrunert added is only used in https://github.com/saschagrunert/kubernetes/blob/7ea3d0245a63fbbba698f1cb939831fe8143db3e/pkg/kubelet/kuberuntime/logs/logs.go#L442

So this change is actually only limited to logs.

**Comment by saschagrunert** [comment]
@kubernetes/sig-node-pr-reviews PTAL

**Comment by pacoxu** [comment]
/lgtm
no change, comparing to last push & just rebase

**Pull request merged**
