### PR TITLE
Fix error message of isDir

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
Use IsRegular to replace isDir
Accoding to the code logic, using IsRegular is proper.
 
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
Why?

**Comment by zhangxiaoyu-zidif** [comment]
@sttts 
I see that the if{} want to check whether is a file. 
According to 
https://golang.org/src/os/types.go?s=3331:3365#L98
IsRegular is a method to check file. So I think use IsRegular is correct.=)

**Comment by sttts** [comment]
Does it break symlinks?

**Comment by zhangxiaoyu-zidif** [comment]
@sttts Thank you, sir.
You are right. if i use IsRegular, i will ignore symlink. After all, symlink is not a regular file and available in this situation.
Let me think how to amend this PR, and then make it perfect.

**Comment by alexandercampbell** [comment]
`IsDir()` seems to be the best choice here.
Maybe we should change the error message to say `"env config file cannot be a directory"`? That way the error message does a better job of explaining why the error is returned.

**Comment by zhangxiaoyu-zidif** [comment]
@sttts @alexandercampbell 
I tried to use Perm() to distinct symlink and regular, but consider that only support unix. So I give it up.
So far, I am willing to accept alexandercampbell 's suggestion. Just to fix the comment.
Maybe with golang's upgrade, we will get better method. =)
PTAL.
Thanks for review.

**Comment by zhangxiaoyu-zidif** [comment]
f os.FileInfo
when  (  f.Mode() & os.ModeSymlink ) > 0 that is symlink.
If it's necessary use "IsRegualr() |  (  f.Mode() & os.ModeSymlink ) " to get the file?
I am not sure =)

**Comment by alexandercampbell** [comment]
/lgtm
@zhangxiaoyu-zidif thank you for your patience! Your code looks good to me now.

You could certainly use `IsRegular() || ( f.Mode() & os.ModeSymlink != 0 )` to see if the file is regular or a symlink. But I think the `IsDir()` check makes more sense here.

There are a few other edge cases (like ModeTemporary) which we don't want to worry about. The best way to check if a file is readable: try reading it.

**Comment by alexandercampbell** [comment]
@stts are you able to approve PRs in this area?

**Comment by sttts** [comment]
@alexandercampbell no, I can't. @fabianofranz approved?

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by zhangxiaoyu-zidif** [comment]
ping @fabianofranz  PTAL

**Comment by alexandercampbell** [comment]
@pwittrock would you mind asking the bot to re-run the failing test? I'm certain it's unrelated.

**Comment by alexandercampbell** [comment]
@zhangxiaoyu-zidif would you mind updating the title of this PR to be more accurate?

**Comment by fabianofranz** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by fabianofranz** [comment]
@k8s-bot ok to test
/approve no-issue

**Pull request merged**
