### PR TITLE
Updated port for HA master etcd.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Updated port for HA master etcd to 2379 (needed after #30514).

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32204)

### CODE REVIEW

**Comment by gmarek** [comment]
This fixes experimental HA functionality in 1.4 release. I believe it should go in v1.4 - @pwittrock

**Comment by fgrzadkowski** [comment]
LGTM

**Comment by pwittrock** [comment]
Cherrypick Terms of Service

1. You are responsible for manually QAing this change in the next beta / release candidate to contain it

2.  You must provide a risk assessment in the PR description including the following
  - Risk surface of accepting this cherrypick: what could go wrong
  - How easy it is to revert if needed 
  - Why it is worth the risk, burden to cherrypick and verify the tests stay green, and noise it creates

3. If this is a launching blocking fix you must provide a justification.  Otherwise define its urgency as one of:
  - launching blocking
  - important
  - best effort

**Comment by gmarek** [comment]
cc @jszczepkowski

**Comment by jszczepkowski** [comment]
2.
- low risk: we are only changing kube-up script for HA master (currenlty not tested and not used)
- easy to revert if needed: fix contains only 3 trivial lines of shell script
- if the patch is cherry picked: we will be able to test experimental HA master on branch 1.4

3.
- best effort: not launch blocking, experimental functionality

**Comment by jszczepkowski** [comment]
Part of https://github.com/kubernetes/features/issues/48

**Pull request merged**
