### PR TITLE
Prune inactive owners from cloud-provider related OWNERS files.

### PR DESCRIPTION
**Pull request by mrbobbytables**
**What type of PR is this?**

/kind cleanup

**Which issue(s) this PR fixes**:

This is part of a larger cleanup of inactive owners.

OWNERS removed had no activity from January 1st, 2018 to September 1st, 2019. 

For more information on this clean up, see the below links:
- Tracking Issue: https://github.com/kubernetes/kubernetes/issues/76269
- [Kubernetes-dev mailing list announcement](https://groups.google.com/d/msg/kubernetes-dev/4160VsBL7OI/BsBRZSqpCQAJ)

**Special notes for your reviewer**:

Assigning common approvers across all OWNERS files touched by this PR.

/assign andrewsykim cheftako dims mikedanese wlan0

**Does this PR introduce a user-facing change?**: 

```release-note
NONE
```

/sig contributor-experience
/priority important-soon

### CODE REVIEW

**Comment by mrbobbytables** [comment]
For notification purposes:
@jszczepkowski @markturansky @girishkalele @jdef

**Comment by mikedanese** [comment]
/lgtm
/approve
/hold

Feel free to unhold after comment grace period.

**Comment by mrbobbytables** [comment]
As 10 days have past, with no further comments, going to go ahead and remove the hold.
/hold cancel

**Pull request merged**
