### PR TITLE
Use IP addresses to test external connectivity

### PR DESCRIPTION
**Pull request by aojea**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
/kind flake

**What this PR does / why we need it**:

Current IPv6 e2e test for external connectivity is using a domain address (google.com) as the target and is [reported flaky](https://github.com/leblancd/kube-v6-test/blob/master/README.md)

The same IPv4 test uses the well known Google DNS address 8.8.8.8, instead of the domain name. We should be coherent in the testing, this patch changes the target to use the Google IPv6 DNS IPv6 address 2001:4860:4860::8888.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by danwinship** [comment]
> Also, using DNS domain names as targets for connectivity can lead to failures
> and unpredictability on the tests because, in dual stack environments,
> the OS will decide what DNS record will use to connect to the domain.
> 
> Ref:
> https://umbrella.cisco.com/blog/2014/06/04/dual-stack-search-domains-host-roulette/

That should be removed from the commit message, as it is not relevant to this test; the test uses `ping6`, which does a DNS lookup requesting only IPv6 records.

/ok-to-test

**Comment by aojea** [comment]
Upss, @thockin seems I messed it up and committed to the wrong branch,  should I remove the commit from this branch and send it in this new PR #75237 ?

**Comment by aojea** [comment]
IMHO It's cleaner to submit the different commits in different PRs, they are somehow related but the tests belong to different SIGs

**Comment by oomichi** [comment]
This change itself seems good for me because of
```
$ nslookup 2001:4860:4860::8888
8.8.8.8.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.6.8.4.0.6.8.4.1.0.0.2.ip6.arpa        name = dns.google.
```

/retest

**Pull request merged**
