### PR TITLE
Update metrics documentation for v1.31

### PR DESCRIPTION
**Pull request by mengjiao-liu**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
The metrics documentation was not updated in time for the 1.31 release so the 1.31 metrics reference is out of date and doesn't match the code.

After this PR merge, I will update the page https://kubernetes.io/docs/reference/instrumentation/metrics/ using the latest metrics reference.

#### Which issue(s) this PR fixes:

ref: https://github.com/kubernetes/website/issues/48538

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig instrumentation

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by mengjiao-liu** [comment]
ping @kubernetes/release-managers

**Comment by mengjiao-liu** [comment]
This affects users who access the v1.31 metrics reference page, and it is best to update it as soon as possible to avoid blocking the website's PR https://github.com/kubernetes/website/issues/48538.
PTAL @justaugustus @saschagrunert @cici37

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
