### PR TITLE
Add federation api and cm servers to hyperkube

### PR DESCRIPTION
**Pull request by colhom**
\cc @nikhiljindal @quinton-hoole 

[Analytics]()

### CODE REVIEW

**Comment by colhom** [comment]
@luxas given that federation is a blocker, I would think exposing federation binaries via hyperkube is mandatory functionality for v1.3.

**Comment by luxas** [comment]
@mikedanese @ixdy @lavalamp Someone that may trigger the tests?

**Comment by lavalamp** [comment]
add to whitelist

**Comment by quinton-hoole** [comment]
My apologies, I overlooked this PR.  Sorting it out now.

**Comment by quinton-hoole** [comment]
ok to test

**Comment by colhom** [comment]
Verification failures do not seem related to this PR:

```sh
Verifying ./hack/../hack/verify-govet.sh
federation/pkg/dnsprovider/providers/aws/route53/testing/route53api.go:79: arg change.ResourceRecordSet.Name for printf verb %s of wrong type: *string
federation/pkg/dnsprovider/providers/aws/route53/testing/route53api.go:84: arg change.ResourceRecordSet.Name for printf verb %s of wrong type: *string
federation/pkg/dnsprovider/providers/aws/route53/testing/route53api.go:105: arg input.Name for printf verb %s of wrong type: *string
federation/pkg/dnsprovider/providers/google/clouddns/clouddns.go:110: k8s.io/kubernetes/federation/pkg/dnsprovider/providers/google/clouddns/internal/stubs.ManagedZone composite literal uses unkeyed fields
FAILED   ./hack/../hack/verify-govet.sh	342s

....

Verifying ./hack/../hack/verify-symbols.sh
Go version: go version go1.6.2 linux/amd64
+++ [0617 13:06:17] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
+++ [0617 13:06:18] Building go targets for linux/amd64:
    cmd/hyperkube
+++ [0617 13:07:01] Placing binaries
Found bad symbol 'testing[.]':
00000000042371c0 r go.importpath.k8s.io/kubernetes/federation/pkg/dnsprovider/providers/aws/route53/testing.
00000000057cb858 b go.itab.*k8s.io/kubernetes/vendor/github.com/aws/aws-sdk-go/service/route53.Route53.k8s.io/kubernetes/federation/pkg/dnsprovider/providers/aws/route53/testing.Route53API
000000000188e470 t k8s.io/kubernetes/federation/pkg/dnsprovider/providers/aws/route53/testing.init
00000000057c85db b k8s.io/kubernetes/federation/pkg/dnsprovider/providers/aws/route53/testing.initdone.
FAILED   ./hack/../hack/verify-symbols.sh	47s
```

**Comment by goltermann** [comment]
Not sure why that would have happened.  @k8s-bot test this issue #INGORE

**Comment by goltermann** [comment]
@k8s-bot verify this issue: #IGNORE

**Comment by goltermann** [comment]
@colhom No idea why this is the only PR hung up on those vet issues, but they're being fixed by @mikedanese in #27558.

**Comment by goltermann** [comment]
@k8s-bot verify this issue: #IGNORE

**Comment by goltermann** [comment]
@colhom the vet errors are cleaned up, but the symbols issue does appear to be related to your PR.  Take a look at hack/verify-symbols.sh.  It's flagging that your PR now builds in symbols named "*testing*" into hyperkube.

@quinton-hoole any ideas?  Should we alter the regex at https://github.com/kubernetes/kubernetes/blob/master/hack/verify-symbols.sh#L32, or alter something in federation code?

**Comment by quinton-hoole** [comment]
@goltermann @colhom I'm guessing that this might be tripping up the verify-symbols.sh check.  

 https://github.com/kubernetes/kubernetes/tree/642049652b991e69f6bd2eb1ba3c5112f0f57339/federation/pkg/dnsprovider/providers/aws/route53/testing

The easiest might be to rename that package.  I can send in a PR for that.  I'm not familiar enough with the aims behind verify-symbols to know for sure whether that would be subverting a good check or not.  That package is so minute that I don' think it makes much difference whether it's in or out of the production binaries.

**Comment by quinton-hoole** [comment]
https://github.com/kubernetes/kubernetes/pull/27734 should do the trick.

**Comment by goltermann** [comment]
@k8s-bot verify this issue: #27734

**Comment by goltermann** [comment]
@k8s-bot ok to test

**Pull request merged**
