### PR TITLE
Add release note block to cherry-pick script

### PR DESCRIPTION
**Pull request by ehashman**
#### What type of PR is this?

/kind cleanup
/sig testing

#### What this PR does / why we need it:

Cherry-pick script always is missing a release-note block, this adds one to fill in.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
I think this approach is not a correct one. The script should rather use the rel note of the PR that is being backoported. Have in mind that the script can backport n PR at once. Also I think that there is already a machinery that can collect release notes from backports without rel notes - the changelog of the patch releases should be generated via automation. So I am wondering even why we need such change.

**Review by fejta — APPROVED** [review]
/lgtm
/approve

**Comment by ehashman** [comment]
> I think this approach is not a correct one. The script should rather use the rel note of the PR that is being backoported. Have in mind that the script can backport n PRs at once. Also I think that there is already a machinery that can collect release notes from backports without rel notes - the changelog of the patch releases should be generated via automation. So I am wondering even why we need such change.

Because currently if you don't specify a release note on backport PRs, the merge is blocked: https://github.com/kubernetes/kubernetes/pull/103977#event-5080287533 https://github.com/kubernetes/kubernetes/pull/103977#issuecomment-888422493

**Comment by ehashman** [comment]
flake #100788 
/retest

**Pull request merged**
