### PR TITLE
add --ignore-not-found option

### PR DESCRIPTION
**Pull request by juanvallejo**
Related downstream issue https://github.com/openshift/origin/issues/12867#event-961812896

Adds `--ignore-not-found` option that works similarly to the one found in [delete](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/delete.go#L154).

Allows for scripts to request specific resources that might not exist, without dealing with ambiguous exit code `1`.

**Release note**:
```release-note
NONE
```

cc @smarterclayton @jupierce @fabianofranz

### CODE REVIEW

**Comment by fabianofranz** [comment]
@k8s-bot ok to test

**Comment by fabianofranz** [comment]
@juanvallejo worth adding a test, e.g. https://github.com/juanvallejo/kubernetes/blob/10d17369a1d6694f62f27af83e8309916d645a5a/pkg/kubectl/cmd/delete_test.go#L292

**Comment by juanvallejo** [comment]
@fabianofranz Thanks, done!

**Comment by juanvallejo** [comment]
@fabianofranz :/ I think the remaining test failures are flakes

**Comment by fabianofranz** [comment]
@k8s-bot test this

**Comment by juanvallejo** [comment]
@fabianofranz I believe there was a flake with the etcd3 e2e test

**Comment by fabianofranz** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
