### PR TITLE
Update runc to 1.0.0

### LINKED ISSUE #102676: Pod stuck in ContainerCreating: Unit ...slice already exists
#### What happened:

Errors like this one 

> May 27 06:38:19.960408 ip-10-0-220-230 hyperkube[1448]: E0527 06:38:19.960361    1448 pod_workers.go:190] "Error syncing pod, skipping" err="failed to ensure that the pod: 5ac83c3f-0b16-4cf2-a3cb-f67c19cd0e16 cgroups exist and are correctly applied: failed to create container for [kubepods burstable pod5ac83c3f-0b16-4cf2-a3cb-f67c19cd0e16] : Unit kubepods-burstable-pod5ac83c3f_0b16_4cf2_a3cb_f67c19cd0e16.slice already exists." pod="openshift-machine-config-operator/machine-config-daemon-mm7gt" podUID=5ac83c3f-0b16-4cf2-a3cb-f67c19cd0e16

(when using cgroupDriver: systemd)

#### What you expected to happen:

No such errors

#### How to reproduce it (as minimally and precisely as possible):

I don't know for sure.

#### Anything else we need to know?:

This was introduced in k8s in #102147 and backported to 1.21 in #102196, so needs to be fixed in both master and `release-1.21`.

RH BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1965545

The cause is a regression in runc/libcontainer: https://github.com/opencontainers/runc/issues/2996

The fix is in https://github.com/opencontainers/runc/pull/2997, which should make its way into runc 1.0.0 GA.

Currently there is DNM PR to bump runc to the version with the fix: https://github.com/kubernetes/kubernetes/pull/102508, but we have decided (https://github.com/kubernetes/kubernetes/pull/102250#issuecomment-855922711) to wait until the release.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

- Update runc to 1.0.0 final (release notes: https://github.com/opencontainers/runc/releases/tag/v1.0.0), fixing some issues in libcontainer.
- Remove the device rules from pod cgroups (not needed with the above runc/libcontainer version).

#### Which issue(s) this PR fixes:

Fixes: #102676

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

none

### CODE REVIEW

**Comment by BenTheElder** [comment]
/retest
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102508/pull-kubernetes-unit/1399993974831190016 data race in CSI test.

**Comment by odinuge** [comment]
Test failure in `pull-kubernetes-node-crio-cgrpv2-e2e` is expected. Looks like this works ok on cgroup v2 as well.

**Comment by odinuge** [comment]
Is there a reason why we don't want to split the dependency bump and the device changes @kolyshkin?

**Comment by kolyshkin** [comment]
> Is there a reason why we don't want to split the dependency bump and the device changes @kolyshkin?

runc 1.0.0 includes the fix for SkipDevices to work properly with the systemd driver (https://github.com/opencontainers/runc/pull/2958). This is why the update and the removal of "allow all" device rule is tied together. One thing this PR does is making sure this PR really fixes the issue.

Surely we can do it in a sequential fashion -- update to 1.0 first, then remove the rules. I don't see the reason why though.

**Comment by kolyshkin** [comment]
rebased, updated runc 3a0234e1fe2e82 -> 2f8e8e9d977500

**Comment by kolyshkin** [comment]
Need to address this
> Errors from staticcheck:
> 
> test/e2e/storage/drivers/csi-test/mock/service/service.go:31:2: package github.com/golang/protobuf/ptypes is deprecated: Well-known types have specialized functionality directly injected into the generated packages for each message type. See the deprecation notice for each function for the suggested alternative.  (SA1019)
> 
> test/e2e/storage/drivers/csi-test/mock/service/service.go:250:11: ptypes.TimestampNow is deprecated: Call the timestamppb.Now function instead.  (SA1019)

**Comment by kolyshkin** [comment]
runc 1.0.0 is out, this is no longer a WIP

**Comment by ehashman** [comment]
Just read through the patch notes, https://github.com/kubernetes/kubernetes/pull/92863 will need to update to use the new APIs. Not sure on the merge order here, but I imagine that will merge first so we will need to fix the APIs here before bump.

**Comment by kolyshkin** [comment]
> Just read through the patch notes, #92863 will need to update to use the new APIs. Not sure on the merge order here, but I imagine that will merge first so we will need to fix the APIs here before bump.

The API change actually happened a few releases ago. Left some suggestions in https://github.com/kubernetes/kubernetes/pull/92863 -- if that PR will be fixed, the order doesn't matter.

**Comment by kolyshkin** [comment]
Just realized this PR also fixes issue #102676; updated the description accordingly.

**Comment by kolyshkin** [comment]
Rebased.

/remove-sig api-machinery

**Comment by odinuge** [comment]
Lets see if there are any new regressions (all these are expected to fail tho. :/)

/test pull-kubernetes-node-crio-cgrpv2-e2e
/test pull-kubernetes-node-kubelet-serial-crio-cgroupv1
/test pull-kubernetes-node-kubelet-serial-crio-cgroupv2
/test pull-kubernetes-node-kubelet-serial

**Comment by odinuge** [comment]
> Lets see if there are any new regressions (all these are expected to fail tho. :/)
> 
> /test pull-kubernetes-node-crio-cgrpv2-e2e
> /test pull-kubernetes-node-kubelet-serial-crio-cgroupv1
> /test pull-kubernetes-node-kubelet-serial-crio-cgroupv2
> /test pull-kubernetes-node-kubelet-serial

Those are still flaky and have a lot of permanently failing tests, but I can't see any new issues, so all good it looks.

Although this release is also pretty big, I assume this should be back ported as well, since it fixes a regression from https://github.com/kubernetes/kubernetes/pull/102196? 

/cc @dims @liggitt @bobbypage 
/lgtm
/skip

**Comment by liggitt** [comment]
> since it fixes a regression from #102196?

what was the regression? I wasn't aware of that

**Comment by odinuge** [comment]
> what was the regression? I wasn't aware of that

https://github.com/kubernetes/kubernetes/issues/102676

**Comment by liggitt** [comment]
> #92863 will need to update to use the new APIs. Not sure on the merge order here, but I imagine that will merge first so we will need to fix the APIs here before bump.

it we intend to take this back to 1.21, I'd prefer we bump the dependency before making other changes we don't intend to take back to 1.21

**Comment by liggitt** [comment]
dependency update mechanics lgtm

would like a node approver to approve, then I can tag this

https://github.com/liggitt/kubernetes/blob/56efa75173922e93af6ef146f50422a22680cc46/OWNERS_ALIASES#L232-L239

**Comment by kolyshkin** [comment]
> if we intend to take this back to 1.21

I believe we do

> I'd prefer we bump the dependency before making other changes we don't intend to take back to 1.21

Do you mean to split this PR into two? I would say it's not needed, as the other change is a cleanup coupled to runc-1.0.0 bump, but sure, I have separated the second commit into https://github.com/kubernetes/kubernetes/pull/103163

**Comment by kolyshkin** [comment]
@odinuge @dims @liggitt this needs to be re-LGTM'ed (the only changes are second commit is removed)

**Review by mrunalp — APPROVED** [review]

**Comment by liggitt** [comment]
> Do you mean to split this PR into two?

no, I was talking about merge order between https://github.com/kubernetes/kubernetes/pull/92863 and this... if https://github.com/kubernetes/kubernetes/pull/92863 is not intended to go to 1.21, we should merge this PR first

**Comment by kolyshkin** [comment]
> no, I was talking about merge order between #92863 and this... if #92863 is not intended to go to 1.21, we should merge this PR first

Ah, OK, I reverted the split, so both commits are back here.

Yes, I think this should go in first, and #92863 is not intended to be backported to 1.21.

**Comment by liggitt** [comment]
/approve
dep mechanics lgtm, node approval at https://github.com/kubernetes/kubernetes/pull/102508#pullrequestreview-692106066

needs a final `update-vendor.sh` run... looks like there's a stale go.sum file

**Comment by BenTheElder** [comment]
should we be upgrading the runc binary in the CI jobs? AFAIK this has been pretty adhoc

**Comment by dims** [comment]
@BenTheElder we update the runc in CI when we update containerd (goes as a pair)

**Comment by BenTheElder** [comment]
> @BenTheElder we update the runc in CI when we update containerd (goes as a pair)

Yes, but do we do that after this PR? containerd has already updated AFAIK.

Also the project has blocking CI on GCE with:
- docker
- containerd
- cri-o *

Plus KIND with it's own version of containerd.

So if we should be updating it, we have some work to coordinate.

**Comment by kolyshkin** [comment]
> needs a final update-vendor.sh run... looks like there's a stale go.sum file

Rebased, re-run update-vendor.sh, fixed now. The cause, I guess, is a recently merged #103099 (commit 6f9011a4ae44605107cac329851c6e08985b38b8)

**Comment by kolyshkin** [comment]
1.21 backport: https://github.com/kubernetes/kubernetes/pull/103392

**Comment by hakman** [comment]
@kolyshkin The kOps project has some periodic e2e conformance tests that run against the `ci/latest` k8s marker. This week we noticed that these tests stopped working. Symptoms were that the static pods used to bring up the cluster failed to start randomly, tracked under https://github.com/kubernetes/kops/issues/11911. Together with @justinsb @rifelpet and @olemarkus we tried to find clues, but found nothing conclusive.

The conformance tests results can be found here: https://testgrid.k8s.io/kops-misc#kops-aws-misc-amd64-conformance.

After some testing using various kubernetes versions, I think I tracked the moment that the issue appeared to this change:
https://storage.googleapis.com/kubernetes-release-dev/ci/v1.22.0-beta.0.307+c206af0367f76f - works as before
https://storage.googleapis.com/kubernetes-release-dev/ci/v1.22.0-beta.0.310+4748bb04b61f87 - static pods fail to start

Would you mind checking if this is in any way related with failures we are seeing in kOps tests?

**Comment by BenTheElder** [comment]
For some clarity: https://github.com/kubernetes/kubernetes/compare/c206af0367f76f...4748bb04b61f87 (based on commits in links above)

**Comment by hakman** [comment]
We managed to find more info about the issue we are seeing in kOps. By switching the cgroup driver from `systemd` to `cgroupfs`, clusters are starting again and can pass the conformance tests. I hope this helps.
https://github.com/kubernetes/kops/pull/11919
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kops-e2e-k8s-ci

**Comment by odinuge** [comment]
Thanks for the report @hakman! And thanks for all the details! I have done some digging, and it turns out https://github.com/opencontainers/runc/pull/3019 cause some strange behavior where various cgroups are freezed without being thawed (more info here: https://www.kernel.org/doc/Documentation/cgroup-v1/freezer-subsystem.txt). We still lack a great deal of coverage for the systemd cgroup driver.

The result of this freezing is that everything just _stops_, and stuff just times out in places where that shouldn't be possible.

I vote for reverting this PR, and awaits a proper fix, since this essentially breaks kubelet systemd cgroup driver support :/

The regression in v1.21 could also be fixed by https://github.com/kubernetes/kubernetes/pull/102250 as well, so we should look into that in order to fix that release (or revert the previous runc bump there as well).

Output after kubeadm init (that just times out):

```
odin@xps ~ % grep -R ""  /sys/fs/cgroup/freezer/kubepods.slice/**/freezer.state 
/sys/fs/cgroup/freezer/kubepods.slice/freezer.state:THAWED
/sys/fs/cgroup/freezer/kubepods.slice/kubepods-besteffort.slice/freezer.state:THAWED
/sys/fs/cgroup/freezer/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod6ca0ea8a_ed75_4049_8ca1_40a79c10a2b8.slice/freezer.state:THAWED
/sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/freezer.state:FROZEN
/sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod1519ed09d4a881bb0d1512a9b0b37628.slice/cri-containerd-2d5af28874c4f84c788ed9d6b73f97ce25d1475285bf505bbbe871ebc6dbec9b.scope/freezer.state:FROZEN
/sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod1519ed09d4a881bb0d1512a9b0b37628.slice/cri-containerd-535fded4daa260ba8d41d3ffc7db4edecc14912cdfd3f883347ce4c68469fb13.scope/freezer.state:FROZEN
/sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod1519ed09d4a881bb0d1512a9b0b37628.slice/cri-containerd-f1459055dd2ce055b03b14d56f32f8d1a9219b218c0b41afa29d05956c82c2e3.scope/freezer.state:FROZEN
/sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod1519ed09d4a881bb0d1512a9b0b37628.slice/freezer.state:FROZEN
/sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod1e851413_9e5c_476a_a807_55f54700db56.slice/freezer.state:FROZEN
/sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2169c1802eafeb63cc8e3e07d6294e16.slice/cri-containerd-9cf394c64876814e6d90c382ae0ba54e7198e39abd108021404b4c17278ce01f.scope/freezer.state:FROZEN
/sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2169c1802eafeb63cc8e3e07d6294e16.slice/freezer.state:FROZEN
/sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod7083cd00f13e827a6dfc9f3d4d9510b3.slice/cri-containerd-101c8e3864d28bbcb1d1c1b40eaa2129a65c86120f38eb4cc5b635561e914c5e.scope/freezer.state:FROZEN
/sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod7083cd00f13e827a6dfc9f3d4d9510b3.slice/cri-containerd-eefa3339f42c5f861b3b0304bf7425d652250de727e11b849ef951df06e89739.scope/freezer.state:FROZEN
/sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod7083cd00f13e827a6dfc9f3d4d9510b3.slice/cri-containerd-fcd69f24e18b31cec69be0127b9097bc63a60a8ce838fb603eb588c55fc6707c.scope/freezer.state:FROZEN
/sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod7083cd00f13e827a6dfc9f3d4d9510b3.slice/freezer.state:FROZEN
/sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod78aa97a0670eff5cbcc2e5f9d4370fe1.slice/cri-containerd-c6dab44a2943cd7c4146893d2577a1495946b5bb12b8884065159095a2960324.scope/freezer.state:FROZEN
/sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod78aa97a0670eff5cbcc2e5f9d4370fe1.slice/freezer.state:FROZEN
/sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod87c9b6ea_8287_4946_9b34_e77647c249cb.slice/freezer.state:FROZEN

**Comment by odinuge** [comment]
Opened a revert here: https://github.com/kubernetes/kubernetes/pull/103483

/cc @dims @liggitt @kolyshkin @hakman

**Comment by mkumatag** [comment]
we are also seeing issues on ppc64le platform, hitting with the following error while starting the containers,
```
Jul 05 08:40:12 config1-1625472016-master.power-iaas.cloud.ibm.com kubelet[25341]: E0705 08:40:12.449311   25341 remote_runtime.go:116] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to start sandbox container for pod \"etcd-config1-1625472016-master.power-iaas.cloud.ibm.com\": operation timeout: context deadline exceeded"
```

**Pull request merged**
