### PR TITLE
Close watcher early for volume detachment

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
In waitForVolumeDetachmentInternal, the watcher should be stopped before the recursive call.

```release-note
NONE
```

### CODE REVIEW

**Comment by tedyu** [comment]
ping @jsafrane for review

**Comment by jsafrane** [comment]
I am curious how #79144 will end up, IMO attach and detach should use the same approach and not to recurse. Or is detach different in any way?

**Comment by tedyu** [comment]
@jsafrane 
It seems #79144 would take longer to settle.
It would be nice to let this proceed in terms of bug fix.

We can always revisit once there is progress on #79144

**Comment by tedyu** [comment]
ping @jsafrane for review.

It would be good to keep watcher handling consistent across detachment and attachment.

**Pull request merged**
