### PR TITLE
Revert "Merge pull request #9165 from smarterclayton/graceful"

### PR DESCRIPTION
**Pull request by roberthbailey**
This reverts commit 4f856b595da89107a118f3c51e0c19d8a55d52a5, reversing
changes made to d78525a83b798cc9b0abd136d1d3acc8b39b5d85.

Conflicts:
    pkg/kubelet/status_manager.go

### CODE REVIEW

**Comment by roberthbailey** [comment]
I've manually verified that other than the import difference in `pkg/kubelet/status_manager.go` this is a precise rollback of https://github.com/kubernetes/kubernetes/pull/9165. Will self merge on green in an attempt to fix the e2e tests.

**Comment by smarterclayton** [comment]
Thanks for the patience, will try to get whatever is still causing e2e hang
ups fixed.

On Aug 18, 2015, at 8:59 PM, Robert Bailey <notifications@github.com> wrote:

/cc @smarterclayton <https://github.com/smarterclayton>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/12891#issuecomment-132406995>
.

**Comment by roberthbailey** [comment]
No worries. I was hoping we'd be able to fix it without reverting but so it goes...

**Comment by smarterclayton** [comment]
I'm going for a hat trick on reverts

On Aug 18, 2015, at 9:20 PM, Robert Bailey <notifications@github.com> wrote:

No worries. I was hoping we'd be able to fix it without reverting but so it
goes...

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/12891#issuecomment-132409530>
.

**Pull request merged**
