### PR TITLE
e2e-runner.sh: don't overwrite readonly var

### PR DESCRIPTION
**Pull request by j3ffml**
ref #27215

### CODE REVIEW

**Comment by spxtr** [comment]
didn't see that one coming...

**Comment by spxtr** [comment]
Why not unpack binaries?

**Comment by jlowdermilk** [comment]
> didn't see that one coming...

yeah :(

> Why not unpack binaries?

unpack binaries is already called in fetch_published_version_tars

**Comment by spxtr** [comment]
so it is.

**Comment by spxtr** [comment]
I guess the way to prevent this sort of thing is to make the change in a test job pulling from your own branch.

**Pull request merged**
