### PR TITLE
make scheduler_perf usable from other repositories

### LINKED ISSUE #118459: make scheduler_perf easy to use from external
### What would you like to be added?

Currently many parts of `scheduler_perf` is implemented in [scheduler_perf_test.go](https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler_perf/scheduler_perf_test.go), 
and that prevents external scheduler from using scheduler_perf.

### Why is this needed?

In [kube-scheduler-wasm-extension](https://github.com/sanposhiho/kube-scheduler-wasm-extension), I'd like to check an overall scheduling performance via scheduler_perf because the performance is a critical point for the project.
But, I believe it's a common use case for other custom schedulers as well.

/sig scheduling

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

- just move most of test/integration/scheduler_perf/scheduler_perf_test.go to test/integration/scheduler_perf/scheduler_perf.go so that other repositories can import and run the same benchmark.
  - keep only `BenchmarkPerfScheduling` in test/integration/scheduler_perf/scheduler_perf_test.go
- move `TestScheduling` to test/integration/scheduler_perf/scheduler_test.go.
- add `outOfTreePluginRegistry` so that other repositories can run scheduler_perf with any out-of-tree plugins.

#### Which issue(s) this PR fixes:

Fixes #118459

#### Special notes for your reviewer:

See the intention here: https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/pull/52

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sanposhiho** [comment]
/unhold
/assign @pohly 

@pohly Please take a look 🙏

**Comment by pohly** [comment]
You might want to change `package benchmark` into `package benchmark_test` in `test/integration/scheduler_perf/scheduler_perf_test.go`. That'll ensure that only exported symbols of the package are used, i.e. the in-tree tests and benchmarks will be more like the external user.

Normally I would have asked about how external users get access to the package because importing `k8s.io/kubernetes` is frowned upon, but as this is for developers of a scheduler plugin, they need to do that already because of `k8s.io/kubernetes/pkg/scheduler/framework`.

**Comment by sanposhiho** [comment]
@pohly 🙏

**Review by pohly — APPROVED** [review]
/lgtm

**Review by kerthcet — COMMENTED** [review]
Do we have an instruction about how to use this, like under the README.md?

**Comment by sanposhiho** [comment]
Yes we do. Or you may mean something another>?
https://github.com/sanposhiho/kubernetes/blob/74a6a4581f0471660506988bda20376b118fd943/test/integration/scheduler_perf/README.md

**Comment by kerthcet** [comment]
Like how to use the scheduler_perf from other repositories as titled.

**Pull request merged**
