### PR TITLE
Fix golint failures of cmd/kube-proxy/app

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fix golint failures of cmd/kube-proxy/app

**Which issue(s) this PR fixes**:

Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/priority backlog
/sig cluster-lifecycle

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/assign @thockin 
/remove-sig cluster-lifecycle
/sig network

**Review by thockin — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
