### PR TITLE
Fix golint failures of e2e/framework/pv_util.go

### PR DESCRIPTION
**Pull request by oomichi**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This fixes golint failures of e2e/framework/pv_util.go

Ref: #68026

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by oomichi** [comment]
With on-flight PRs, we have 280 golint failures under test/e2e/framework/ after this PR.

**Review by neolit123 — COMMENTED** [review]
thanks!
/lgtm
/priority backlog

**Comment by oomichi** [comment]
Oops, sorry for my typo..

**Pull request merged**
