### PR TITLE
Revert list of primitives fix

### PR DESCRIPTION
**Pull request by mengqiy**
Revert #36678 #35647 #37038 according to https://github.com/kubernetes/kubernetes/pull/35647#issuecomment-262415809
The revert order is:
1) #37038
2) #36678
3) #35647

cc: @pwittrock @dims

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37343)

### CODE REVIEW

**Comment by ymqytw** [comment]
@k8s-bot gci gke e2e test this

**Comment by dims** [comment]
LGTM 👍

**Comment by fabianofranz** [comment]
@ymqytw Are they all pure `git revert` of the original commits? I mean, no additional changes?

**Comment by ymqytw** [comment]
@fabianofranz Yes. They are all pure git revert. No additional changes.

**Comment by ymqytw** [comment]
Anyone can help tagging?

**Comment by dims** [comment]
@saad-ali Can you please bless this revert?

**Comment by dchen1107** [comment]
Manually merge those group of commits.

**Pull request merged**
