### PR TITLE
testclient: Properly propagate object names when GETing them

### PR DESCRIPTION
**Pull request by 0xmichalis**
@deads2k @mikedanese PTAL

### CODE REVIEW

**Comment by deads2k** [comment]
I don't know that I'm sold in general.  If the action is unhandled, why would we return an ambiguous value?  That would mean that either you got something that had nothing but a name or you got the "empty" default object, but you'd have no way to figure out which was which.

I could envision an alternative where an unhandled get results in a "NotFound" error.

**Comment by kargakis** [comment]
I would expect that a successful GET would return the object with the name I asked for. It would have saved me a couple of hours today:)

**Comment by deads2k** [comment]
> I would expect that a successful GET would return the object with the name I asked for. It would have saved me a couple of hours today:)

I would assert that a NotFound error would be just as effective at indicating the failure to you and would be more proper in that case.

**Comment by deads2k** [comment]
@kargakis This is what I'm working towards to make this easier for us to use:
 1. provide proper types to distinguish particular actions (done)
 1. allow registration of chained reaction functions for particular verb/resource tuples (will make pull today)
 1. update default reactor to properly roundtrip values (do a create, then a get, get back what you added).

Based on what you've said here, I'd add
 4. Correctly provide errors for invalid Get (maybe Update from default reactor too?)

**Comment by kargakis** [comment]
@deads2k when registering a new testclient, we can pass an [arbitrary](https://github.com/GoogleCloudPlatform/kubernetes/blob/ded48a376107a66abb374e38ec6fc1d48e66678e/pkg/client/testclient/testclient.go#L32) amount of objects in it. How about returning "NotFound"/the object based on those?

**Comment by deads2k** [comment]
> @deads2k when registering a new testclient, we can pass an arbitrary amount of objects in it. How about returning "NotFound"/the object based on those?

That was the intent of the code that existed and I'm making it a reality as we speak.

**Comment by kargakis** [comment]
> That was the intent of the code that existed and I'm making it a reality as we speak.

Sup, I'm closing this then.

**Pull request closed without merging**
