### PR TITLE
 tokenrequest: change audiences to audience 

### PR DESCRIPTION
**Pull request by mikedanese**
Use the correct terminology. A token has one audience with multiple
members.

One more :100: 

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
is that the case?

> aud
>     REQUIRED. Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. It MAY also contain identifiers for other audiences. In the general case, the aud value is an array of case sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case sensitive string. 

seems like audiences works as well...

**Comment by liggitt** [comment]
a singular name for a plural (slice) field seems stranger to me

**Comment by mikedanese** [comment]
I am going off the JWT spec:

> "aud" (Audience) Claim
>
>   The "aud" (audience) claim identifies the recipients that the JWT is
>   intended for.  Each principal intended to process the JWT MUST
>   identify itself with a value in the audience claim.  If the principal
>   processing the claim does not identify itself with a value in the
>   "aud" claim when this claim is present, then the JWT MUST be
>   rejected.  In the general case, the "aud" value is an array of case-
>   sensitive strings, each containing a StringOrURI value.  In the
>   special case when the JWT has one audience, the "aud" value MAY be a
>   single case-sensitive string containing a StringOrURI value.  The
>   interpretation of audience values is generally application specific.
>   Use of this claim is OPTIONAL.

Audience is singular and is represented by an array of StringOrURI in the general case. Subsequently, OIDC fudged this a bit.

> a singular name for a plural (slice) field seems stranger to me

Audience is a collective noun already. Audiences sounds strange to me.

**Comment by liggitt** [comment]
Ok, I don't feel strongly

**Comment by mikedanese** [comment]
Me neither. I had been going off JWT spec and hadn't actually noticed that oidc differs. @ericchiang want to tie break?

**Comment by mikedanese** [comment]
Let's go with OIDC

**Comment by ericchiang** [comment]
For what it's worth, we just call it `Audience` in go-oidc https://godoc.org/github.com/coreos/go-oidc#IDToken

**Pull request closed without merging**
