### PR TITLE
Fix broken api-reference docs in 1.0 branch

### PR DESCRIPTION
**Pull request by thockin**
They were not being regenerated.  This PR was largely manual, sadly, and even some code had to be tweaked to compile properly (different issue coming).

I verified that all the links resolve now.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Thanks! LGTM.

**Comment by caesarxuchao** [comment]
Eh.......I did the same thing to HEAD in #11726. I didn't know about cherry-pick back then...

**Comment by caesarxuchao** [comment]
Sorry for the repeated labor. I was too callow.

**Comment by wojtek-t** [comment]
Jenkins test flake:
"Probing container with readiness probe should not be ready before initial delay and never restart"

@k8s-bot test this please

**Comment by caesarxuchao** [comment]
@k8s-bot test this

**Comment by wojtek-t** [comment]
Jenkins failure is unrelated flake:
"Monitoring should verify monitoring pods and all cluster nodes are available on influxdb using heapster."

@k8s-bot test this please

**Pull request merged**
