### PR TITLE
util/iptables: grab iptables locks if iptables-restore doesn't support --wait

### PR DESCRIPTION
**Pull request by dcbw**
When iptables-restore doesn't support --wait (which < 1.6.2 don't), it may
conflict with other iptables users on the system, like docker, because it
doesn't acquire the iptables lock before changing iptables rules. This causes
sporadic docker failures when starting containers.

To ensure those don't happen, essentially duplicate the iptables locking
logic inside util/iptables when we know iptables-restore doesn't support
the --wait option.

Unfortunately iptables uses two different locking mechanisms, one until
1.4.x (abstract socket based) and another from 1.6.x (/run/xtables.lock
flock() based).  We have to grab both locks, because we don't know what
version of iptables-restore exists since iptables-restore doesn't have
a --version option before 1.6.2.  Plus, distros (like RHEL) backport the
/run/xtables.lock patch to 1.4.x versions.

Related: https://github.com/kubernetes/kubernetes/pull/43575
See also: https://github.com/openshift/origin/pull/13845
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1417234

@kubernetes/rh-networking @kubernetes/sig-network-misc @eparis @knobunc @danwinship @thockin @freehan

### CODE REVIEW

**Comment by thockin** [comment]
When kube-proxy runs in a container this will only interlock with itself - how is that useful?

**Comment by dcbw** [comment]
> When kube-proxy runs in a container this will only interlock with itself - how is that useful?

When kube-proxy runs in a container, it still has to call iptables-restore and iptables too.  Wouldn't those also only lock themselves?  I assume to get whole-machine locking (including with kubelet's invocations of docker) you'd need to ensure that both kube-proxy and kubelet containers mapped /run into their container space.

**Comment by thockin** [comment]
Yes, I think they would only lock against themselves.  what happens
in-kernel when 2 iptables invocatiosn run in parallel?  Failure of 1?

**Comment by dcbw** [comment]
> Yes, I think they would only lock against themselves. what happens in-kernel when 2 iptables invocatiosn run in parallel? Failure of 1?

@thockin correct; one will exit with EAGAIN failure while attempting to call TC_COMMIT() in libiptc/libiptc.c, printing that failure text to stderr/stdout.  And docker will then fail container startup because it cannot add some of the iptables rules it wants to add, or kube-proxy or kubelet+hostports will fail the iptables invocation too.

**Comment by thockin** [comment]
given that kubelet and kube-proxy don't share /run, isn't this the case
already?

**Comment by dcbw** [comment]
> given that kubelet and kube-proxy don't share /run, isn't this the case already?

@thockin if you split these things up and run them each in a separate container, then yes.

We don't run into kube-proxy + kubelet fights with OpenShift because:

1. the openshift-node process combines kubelet and kube-proxy into one process, so they don't fight each other at all
2. all our containerized images already map /run into the container's filesystem.

**Comment by thockin** [comment]
Should we instead just retry on error?  That will work regardless of
flocks.  Or should this PR also map /run from the host (scary) in the
kube-proxy pod?

**Comment by dcbw** [comment]
> Or should this PR also map /run from the host (scary) in the kube-proxy pod?

@thockin scary.  I'd rather rely on the container definition to do that.

**Comment by dcbw** [comment]
> Should we instead just retry on error? That will work regardless of flocks.

@thockin yeah, we could retry.  But I hesitate to keep piling up hacks that will eventually get fixed by just upgrading iptables...

**Comment by thockin** [comment]
well, if the wait lock is an flock, no iptables upgrade will ever fix
this...

**Comment by dcbw** [comment]
> well, if the wait lock is an flock, no iptables upgrade will ever fix
> this...

@thockin ?  not sure I understand.  The current code simply duplicates what iptables 1.6.x does.  So the moment you update your iptables binaries, kubelet notices and starts using --wait=2 instead of it's own workaround locking.

**Comment by thockin** [comment]
but it will only ever flock against itself if it runs in a container.  I
guess kubelet usually doesn't, but is kubelet usually fighting with itself
or with kube-proxy or with other external things?

**Comment by dcbw** [comment]
> but it will only ever flock against itself if it runs in a container. I guess kubelet usually doesn't, but is kubelet usually fighting with itself or with kube-proxy or with other external things?

@thockin I assume that we are going to map /run into the container.  Also remember that not everyone runs this stuff containerized and those people would get correct locking already.  The involved things are 1) kubelet (eg, hostports), 2) kube-proxy, 3) docker.

Would you prefer that I update the container generation scripts to do that as part of this PR?  I'm happy to do that.

**Comment by thockin** [comment]
Could you take a look?  It is a bit scary to host-share /run, isn't it?

**Comment by thockin** [comment]
And you're right it is better than nothing, I guess.  Could we hostPath me
until just the file used to flock?

**Comment by dcbw** [comment]
> And you're right it is better than nothing, I guess. Could we hostPath me until just the file used to flock?

@thockin Tested this out, and guess what, it works.  Yay!

```
spec:
  containers:
    - name: whatever
      volumeMounts:
      - mountPath: /run/xtables.lock
        name: iptables-lock
  volumes:
  - name: iptables-lock
    hostPath:
      path: /run/xtables.lock
```

**Comment by dcbw** [comment]
@thockin any idea where the docker invocations would be for running containreized kube?  The only ones I can really find are `cluster/get-kube-local.sh` and `hack/local-up-cluster.sh`.

**Comment by thockin** [comment]
Should we update ./cluster/saltbase/salt/kube-proxy/kube-proxy.manifest ?

I don't know how to run containerized kubelet any more..  @vishh ?

**Comment by vishh** [comment]
containerized kubelet is not supported by upstream for production deployments. OpenShift runs kubelet+kube-proxy in a container, but AFAIK, there are no upstream recipes for it.

**Comment by thockin** [comment]
I'm fine with this - would be nice to put that hostPath into the "standard" kube-proxy YAML.

/approve
/lgtm

**Comment by thockin** [comment]
Dan, do you want to add an OWNERS file for pkg/util/iptables and list
yourself as a reviewer? :)

**Comment by dcbw** [comment]
> Dan, do you want to add an OWNERS file for pkg/util/iptables and list yourself as a reviewer? :)

@thockin done; added the required xtables.lock map bits to hack & cluster scripts too.  Hope it's not too presumptuous to add myself as an approver to OWNERS as well here, happy to remove if that's not OK.

**Comment by thockin** [comment]
/lgtm
/approve

We have a gap in tools.  I want to know about all PRs in this dir, but I don't need to be an approver for all.  I am happy to have you approving in here - that is what I meant. :)

**Comment by danwinship** [comment]
This seems to have broken pull-kubernetes-cross? https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/39164/pull-kubernetes-cross/2468/

**Comment by dcbw** [comment]
yay :(  I'll do a PR to move this stuff to a +linux file

**Comment by k82cn** [comment]
@dcbw , can you replace `syscall` with `x/sys`, here's the notes from golang.org (https://golang.org/pkg/syscall/):


>NOTE: This package is locked down. Code outside the standard Go repository should be migrated to use the corresponding package in the golang.org/x/sys repository. That is also where updates required by new systems or versions should be applied. See https://golang.org/s/go1.4-syscall for more information.

**Comment by dcbw** [comment]
Note for anyone reading this later: turns out you need to make sure /run/xtables.lock exists before running the container, otherwise docker will create a directory called /run/xtables.lock when doing the volume map.

**Pull request merged**
