### PR TITLE
Add git branch to make build short hash unique

### LINKED ISSUE #1801: Build: short_hash could consider git branch?
When I change branches, I really want the prior build invalidated.  Could we consider the git branch (if this is a git repo) in the short_hash that uniquifies the build?

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

KUBE_ROOT_HASH depends just on the host name and
directory path. So when working with branches, it could lead
to some confusion since the hash is the same even when
you switch from branch to branch. Let us use the git branch
information when we compute the short hash

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Fixes #1801

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by spxtr** [comment]
Hah, issue #1801 is fixed by PR #46896. Awesome.

/lgtm

**Comment by dims** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
