### PR TITLE
Drop k8s.io/node-api packages

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Removes the k8s.io/node-api staging component, since the types were moved to k8s.io/api and the clients moved to k8s.io/client-go

**Does this PR introduce a user-facing change?**:
```release-note
The k8s.io/node-api component is no longer updated. Instead, use the RuntimeClass types located within k8s.io/api, and the generated clients located within k8s.io/client-go
```

/cc @tallclair

### CODE REVIEW

**Comment by tallclair** [comment]
Thanks! This should be fine. I kept it for a few releases to give clients to migrate to the built-in api, but I think plenty of time has passed and I don't know of any using this. LMK when it's ready for review.

**Comment by liggitt** [comment]
it should be good now

**Comment by liggitt** [comment]
rebased

**Comment by tallclair** [comment]
/lgtm

Thanks for cleaning this up.

Feel free to self reapply the LGTM after resolving the conflicts.

**Comment by liggitt** [comment]
rebased

**Comment by liggitt** [comment]
rebased

**Pull request merged**
