### PR TITLE
Adding approvers for componentconfig

### PR DESCRIPTION
**Pull request by vishh**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36908)

### CODE REVIEW

**Comment by vishh** [comment]
cc @mtaufen @mikedanese

**Comment by mtaufen** [comment]
LGTM

**Comment by mtaufen** [comment]
Let's get this in.

**Comment by thockin** [comment]
need rebase

**Comment by mtaufen** [comment]
@vishh if you give me permissions to push to `vishh:cc-owner`, I'll do the rebase.

**Comment by vishh** [comment]
@mtaufen done.

**Pull request merged**
