### PR TITLE
[go1.17] Update to go1.17.5 and golang.org/x/net to v0.0.0-20211209124913-491a49abca63

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature
/area dependency release-eng release-eng/security security

#### What this PR does / why we need it:

- Update Kubernetes to go1.17.4 on release-1.23 branch
- Update Kubernetes to go1.17.5 on release-1.23 branch
- golang.org/x/net to v0.0.0-20211209124913-491a49abca63

Tracking issue: https://github.com/kubernetes/release/issues/2341

/assign @dims @liggitt @justaugustus 
cc: @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
- Kubernetes is now built with Golang 1.17.5
- golang.org/x/net to v0.0.0-20211209124913-491a49abca63
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by justaugustus — APPROVED** [review]
/lgtm
/approve
/hold cancel

**Review by saschagrunert — APPROVED** [review]

**Comment by cpanato** [comment]
/assign @smarterclayton
can you please take a look at this one?

**Comment by justaugustus** [comment]
From https://github.com/kubernetes/kubernetes/pull/106981#issuecomment-991885379:

> not sure if we want to close the other in favor of this one, but if we merge #106835 I will rebase this after

@cpanato -- I would suggest cherry picking the commits from https://github.com/kubernetes/kubernetes/pull/106959 and https://github.com/kubernetes/kubernetes/pull/106981 onto this branch and closing those PRs out.

**Comment by cpanato** [comment]
cherry picked the change from those PRs https://github.com/kubernetes/kubernetes/pull/106981 and https://github.com/kubernetes/kubernetes/pull/106959 here

**Comment by cpanato** [comment]
> From [#106981 (comment)](https://github.com/kubernetes/kubernetes/pull/106981#issuecomment-991885379):
> 
> > not sure if we want to close the other in favor of this one, but if we merge #106835 I will rebase this after
> 
> @cpanato -- I would suggest cherry picking the commits from #106959 and #106981 onto this branch and closing those PRs out.

done

**Pull request merged**
