### PR TITLE
Fix portforward test flake with GOMAXPROCS > 1

### LINKED ISSUE #6846: portforward test is flaky - fix it
ok  	github.com/GoogleCloudPlatform/kubernetes/pkg/cloudprovider/aws	1.520s	coverage: 25.5% of statements
I0414 23:19:35.411491   17545 portforward.go:228] Forwarding from 5000 -> 5000
W0414 23:19:35.427217   17545 portforward.go:183] Unable to listen on port {5000 5000}: listen tcp 127.0.0.1:5000: bind: address already in use
I0414 23:19:35.427821   17545 portforward.go:228] Forwarding from 6000 -> 6000
I0414 23:19:35.435015   17545 portforward.go:265] Handling connection for 5000
--- FAIL: TestForwardPorts (0.22s)
	portforward_test.go:295: 2: expected to read '1234', got ''
FAIL
coverage: 83.3% of statements
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/client/portforward	0.677s

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #6846

Running hack/test-go.sh with GOMAXPROCS was flaking the portforward test:

```
GOMAXPROCS=4 hack/test-go.sh pkg/client/unversioned/portforward
```

Cause was an EOF returned from the test stream Write() func, which indicated server should close the connection. With a single proc, the remote->local Read() io.Copy() usually completed before the local->remote Write() io.Copy() encountered the EOF and closed the connection.

Symptom was failed tests like this:

```
--- FAIL: TestForwardPorts-4 (0.00s)
    portforward_test.go:371: 0: expected to read '1234', got ''
```

### CODE REVIEW

**Comment by ncdc** [comment]
I need to rewrite the port forward tests the same way I did for exec, to remove the fake upgrader, connection, stream, etc... So much to do, so little time.

**Comment by ncdc** [comment]
> With a single proc, the remote->local io.Copy() usually completed before the local->remote io.Copy() encountered the EOF and closed the connection

I'm trying to fix this in #12283 but it's taking me a while to find enough contiguous time to write the e2e tests to feel confident that everything is functioning properly.

**Comment by liggitt** [comment]
@ncdc would you be ok taking the test-only fix until #12283 is done/tested?

**Comment by ncdc** [comment]
Definitely

**Comment by smarterclayton** [comment]
LGTM

**Pull request merged**
