### PR TITLE
kubeadm enable endpoint-reconciler for HA clusters

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
enable endpoint-reconciler on kube-apiserver when creating HA clusters with kubeadm

**Which issue(s) this PR fixes**:
[#529](https://github.com/kubernetes/kubeadm/issues/529) 

**Special notes for your reviewer**:
CC @luxas 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by luxas — APPROVED** [review]
/lgtm
/approve

Thanks @fabriziopandini for the patch!

**Comment by fabriziopandini** [comment]
@luxas fixed flaky test that was blocking merge

**Pull request merged**
