### PR TITLE
WIP: Towards https in ctrl-manager through SecureServingOptions struct

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by sttts** [comment]
@deads2k @hzxuzhonghu compare https://github.com/kubernetes/kubernetes/pull/59114/files#diff-8f73bf4b0f1cbea0bc90eb7e5ac86fa2R158. This is a quick try to separate the existing SecureServingOptions from the actual genericapiserver config struct, towards a common base for control plane components.

**Comment by deads2k** [comment]
It's not obvious to me why I would split this out.  While I don't expect a kube-controller-manager to be aggregated, allowing it to loop back to itself seems fairly reasonable.

**Comment by sttts** [comment]
> If you can write up a little explanation about why I'd want to split them, the split itself looks pretty clean.

Actually, the split out of the loopback device is merely an example that we might have logic in ApplyTo that applies only to one context (apiserver here). The loopback is now also set by the insecure serving code. We can move that back into the main SecureServingOptions and the SecureServingInfo when we have deleted the insecure mode.

The point of this PR is that we split up the config as well, in parallel to the options. That way it becomes modular.

**Comment by deads2k** [comment]
> The point of this PR is that we split up the config as well, in parallel to the options. That way it becomes modular.

Ok.

/lgtm

**Comment by hzxuzhonghu** [comment]
@sttts doesn't `LoopbackClientConfig ` https://github.com/kubernetes/kubernetes/pull/59114/files#diff-c15d69437252be511f1f5e1d9affbaafR88 overwritten by `SecureServingOptions.ApplyTo`?
Can we put `LoopbackClientConfig` totally in `SecureServingOptions`?

**Comment by hzxuzhonghu** [comment]
And make this happen in v1.10, since then will not support insecure loopback.

**Comment by sttts** [comment]
> Can we put LoopbackClientConfig totally in SecureServingOptions?

When insecure serving is gone, yes. Can you link the PR here?

**Comment by hzxuzhonghu** [comment]
> When insecure serving is gone, yes. Can you link the PR here?
Yes, I can. And it maybe a year later.

**Comment by hzxuzhonghu** [comment]
How about put loopback also in InsecureServingOptions? We prefer the one under SecureServingOptions.

**Comment by sttts** [comment]
> How about put loopback also in InsecureServingOptions?

We are killing the insecure code path right now. Moreover, we need exactly one loopback client config.

But this change was not the core of the PR, compare https://github.com/kubernetes/kubernetes/pull/59114#issuecomment-362017030.

**Comment by hzxuzhonghu** [comment]
Sound good.

**Pull request closed without merging**
