### PR TITLE
controller framework: don't send update event when relist

### PR DESCRIPTION
**Pull request by mqliang**
@bprashanth @lavalamp

### CODE REVIEW

**Comment by bprashanth** [comment]
Why? We should let the controller decided what to do, if they actually just want to reprocess the object that's fine, but they can also do the reflect.DeepEqual themselves.

**Comment by lavalamp** [comment]
Yeah, this behavior is deliberate and I'm quite surprised that no tests broke.

**Comment by mqliang** [comment]
The reason why I want do the reflect.DeepEqual is: when cluster is large and a periodic list happens, a large number of Sync event will block the work queue, thus a Added/Updated/Deleted event may have a long latency(those events are usually caused by users, they should be processed ASAP).

Letting the controller decided what to do sounds good to me. But I propose to distinguish Sync event from Added/Updated/Deleted event, for example, when work queue pop controllers(rc/rs/job, etc) to sync, Added/Updated/Deleted event will have a higher priority. Only when there is no Added/Updated/Deleted events, we process Sync event. Any thoughts?

What we should do is let [work queue](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replication/replication_controller.go#L93) distinguish priority. WDYT?

**Comment by mqliang** [comment]
I have done a benchmark about replication_controller: if we have 1000 namespace, each have 10 RCs, each RC have 10 replicas(so, 100, 000 pod in total), when periodic list happens, replication_controller need 20s to process the RCs added into work queue by relist, which means if a user create a new RC, it will be processed after 20 seconds. Users are always captious and impatient.

**Comment by mqliang** [comment]
@wojtek-t You may be interested in this.

**Comment by bprashanth** [comment]
I think https://github.com/kubernetes/kubernetes/issues/23394 should be enough?

**Comment by wojtek-t** [comment]
Agree with @bprashanth - we should do #23394  (which some is already working on btw). Then this one is not needed. So closing this one.

**Comment by mqliang** [comment]
> I think #23394 should be enough?

IIUC, use replication_controller as example:

* Relist means "reflector send LIST request to etcd, replace local cache with items get form etcd, and put all deltas to a queue, then the controller framework pop deltas from the queue and put the RC need to process to work queue".
* Resync means "go through the items in the local cache, put all RCs(in local cache) to work queue".

Since both relist and resync will add ALL RCs(all RCs from etcd when relist, all RCs from local storage when resync) to work queue, when cluster is large, a large number of RCs will block work queue for a long time. If a unfortunate user create a new RC just at that time, he will get a bad user experience.

**Comment by mqliang** [comment]
@wojtek-t If my above understanding is correct, I don't think https://github.com/kubernetes/kubernetes/issues/23394 and a priority work queue is conflict, they are complementary actually: RCs added by Added/Updated/Deleted event(usually caused by users) will have a higher priority when pop, so they could be processed ASAP. RCs added by periodic relist/resync will have a relatively lower priority. 

Will file a dedicated issue to discuss this if I understand relist/resync correctly. Feel free to correct me if I am wrong.

**Comment by lavalamp** [comment]
The whole point of the resync is that items get periodically evaluated at the desired frequency. This PR would completely disable that, so we can't accept it.

If resync work causes high tail latency for other users, then IMO we should do something like resync in smaller batches, or add more workers. A priority queue sounds very complicated and I'd rather not do that at the moment.

**Comment by wojtek-t** [comment]
+100 for what @lavalamp wrote. That was exactly what I was thinking.

**Pull request closed without merging**
