### PR TITLE
add k8petstore-nodeport.sh for examples/k8petstore

### PR DESCRIPTION
**Pull request by caesarxuchao**
This PR depends on #9586. The last commit is the diff.

k8petstore-nodeport.sh is tested on GCE. It needs to be modified if it's not run on a cloud platform. 

@jayunit100 @eparis , could you take a look? Thanks.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Hi @jayunit100 @eparis, I'm trying to run k8petstore.sh on a local cluster that is created by hack/local-cluster-up.sh, but the fectrl pod keeps restarting, here is the log:

```
$ kubectl logs fectrl-h8str
Found redis master host 6379Now connecting to : 10.0.0.57:6379
Connection pool established : 10.0.0.57:6379
Router created
=========== Read ENV 'STATIC_FILES', path to assets : /tmp/static
ERROR :  dial tcp 10.0.0.57:6379: no route to hostERROR :  dial tcp 10.0.0.57:6379: no route to hostERROR :  dial tcp 10.0.0.57:6379: no route to hostERROR :  dial tcp 10.0.0.57:6379: no route to hostpanic: interface conversion: interface is nil, not int64

goroutine 1 [running]:
main.main()
        /gopath/src/main/PetStoreBook.go:101 +0xc30
```

Any suggestion on how to debug this? Thanks.

**Comment by jayunit100** [comment]
Hi ... whats the error?  It looks simply like Redis isn't up yet.   looks like maybe the original comment was deleted ?

**Comment by caesarxuchao** [comment]
Hi @jayunit100, I found the cause of the error. Sorry for the false alarm. I will update the script again. I'm making it work for local cluster now.

**Comment by jayunit100** [comment]
okcool. we can improve the error reporting in a later issue.

**Comment by caesarxuchao** [comment]
Hi @jayunit100, now the script also works if k8s is running on a local cluster. PTAL. Is there other situations that I missed?

**Comment by jayunit100** [comment]
LGTM thanks !

**Comment by caesarxuchao** [comment]
@k8s-bot ok to test

**Comment by caesarxuchao** [comment]
@k8s-bot ok to test

**Pull request merged**
