### PR TITLE
Automated cherry pick of #51480 upstream release 1.7

### PR DESCRIPTION
**Pull request by jpbetz**
Cherrypick of #51480

**What this PR does / why we need it**:

Backporting to support Kubernetes users with slower internet connections that need the ability to increase this timeout.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by roberthbailey** [comment]
@wojtek-t

**Comment by wojtek-t** [comment]
@jpbetz - please add a release note to the original PR

**Comment by wojtek-t** [comment]
> @jpbetz - please add a release note to the original PR

Also - this should probably also contain: https://github.com/kubernetes/kubernetes/pull/52316

**Comment by wojtek-t** [comment]
@jpbetz - so I added release note myself. Since we're short on time, I will go ahead an create the cherrypick containing the other PR I mentioned too.

**Comment by wojtek-t** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/pull/52415

**Comment by jpbetz** [comment]
Thanks @wojtek-t!

**Pull request closed without merging**
