### PR TITLE
Disabled cluster registry addon by default

### PR DESCRIPTION
**Pull request by piosz**
This is not widely used right now and reserves significant amount of cpu (500m cores on 4-nodes cluster which is default option in GCE).

@bgrant0607 @brendandburns @fgrzadkowski @roberthbailey @uluyol @zmerlynn

### CODE REVIEW

**Comment by bgrant0607** [comment]
Do we document how to enable and use the registry anywhere?

**Comment by thockin** [comment]
AFAIK there are no good docs on this.

**Comment by thockin** [comment]
I'll see if I can whip up a very small doc on this - just a README in the addons dir.

**Comment by thockin** [comment]
chaneg LGTM

**Pull request merged**
