### PR TITLE
Automated cherry pick of #69737: Add tolerations for Stackdriver Logging and Metadata Agents.

### PR DESCRIPTION
**Pull request by qingling128**
Cherry pick of #69737 on release-1.10.

#69737: Add tolerations for Stackdriver Logging and Metadata Agents.

### CODE REVIEW

**Comment by x13n** [comment]
/lgtm

But since I'm not in OWNERS on 1.10 branch:

/assign @piosz

**Comment by qingling128** [comment]
Thanks @piosz !

Could someone help with the `cncf-cla: yes` and `do-not-merge/cherry-pick-not-approved` labels?

**Comment by qingling128** [comment]
The other PRs into `v1.11` and `v1.12` had `cncf-cla: yes` applied by the bot automatically. Am I missing anything?

**Comment by x13n** [comment]
I don't know, it should be applied by the bot.
@MaciekPytel can you approve the cherrypick? Also, do you know why cncf-cla label may be missing?

**Comment by qingling128** [comment]
@MaciekPytel Friendly ping.

**Comment by wasylkowski-a** [comment]
FYI, @MaciekPytel is away and will be back next week.

**Comment by qingling128** [comment]
@wasylkowski-a Thanks for the heads up! I'll check back next week.

**Comment by qingling128** [comment]
Tried the `git commit --amend` suggestion. `cncf-cla: yes` seems present now. Thaks @idealhack 

The lgtm label needs to be re-added though. PTAL @x13n @MaciekPytel

**Comment by idealhack** [comment]
/lgtm

since there’s no difference after the force pushing

**Pull request merged**
