### PR TITLE
Automated cherry pick of #89341: bump k8s.io utils

### PR DESCRIPTION
**Pull request by aojea**
Cherry pick of #89341 on release-1.18.

#89341: bump k8s.io utils

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by alejandrox1** [comment]
cc @kubernetes/patch-release-team 
/priority critical-urgent
/kind bug

again, thank you @aojea :sweat_smile:

**Review by SataQiu — COMMENTED** [review]
/test pull-kubernetes-e2e-kind
/lgtm

**Comment by liggitt** [comment]
/approve

based on thockin's review at https://github.com/kubernetes/utils/pull/145#issuecomment-602236993

**Pull request merged**
