### PR TITLE
bump smd to version with backported bugfixes

### PR DESCRIPTION
**Pull request by kwiesmueller**
/kind bug
/priority important-soon

**What this PR does / why we need it**:

Bumps the version for smd to the latest state of the release-1.0 branch to include recent bugfixes.

Namely: https://github.com/kubernetes-sigs/structured-merge-diff/pull/140 / https://github.com/kubernetes-sigs/structured-merge-diff/pull/131

```release-note
NONE
```

### CODE REVIEW

**Comment by apelisse** [comment]
/lgtm
/approve 

I think that's correct.

**Comment by jennybuckley** [comment]
Why is the version v1.0.2-0.20191224094529-3d0c538beda9 and not v1.0.2 ?

**Comment by jennybuckley** [comment]
Did we tag v1.0.2 in SMD to the wrong commit?

**Comment by apelisse** [comment]
This commit was made before we tagged ...

**Comment by kwiesmueller** [comment]
i can update it

**Comment by lavalamp** [comment]
Yeah please update and `go mod tidy`, then I can approve

**Comment by justaugustus** [comment]
Today is the cherry pick deadline for the next patch release cycle.
If you intend to get this PR into this cycle, it must be approved by the relevant owners ASAP.

**Pull request merged**
