### PR TITLE
Add liveness probe for cluster autoscaler

### PR DESCRIPTION
**Pull request by aleksandra-malinowska**
Configure a liveness probe for cluster autoscaler.

### CODE REVIEW

**Comment by MaciekPytel** [comment]
@aleksandra-malinowska can you link the issue in autoscaler repo in description?

**Comment by mwielgus** [comment]
How this was tested?

**Comment by aleksandra-malinowska** [comment]
@MaciekPytel - I don't think we have an issue for that

@mwielgus - tested this config by running cluster autoscaler image with failing health check and verifying it restarts as expected

**Pull request merged**
