### PR TITLE
test images: Adds cuda-vector-add-old image

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind cleanup
/sig testing

#### What this PR does / why we need it:

Currently, the only image left in ``gcr.io/kubernetes-e2e-test-images`` is the ``cuda-vector-add:1.0`` image.

According to ``8408188cdf4b8d3a6063015ea5a52de9b2a90821``, the 1.0 image was based on CUDA 8.0, while the 2.0 version is based on CUDA 10.0. We can simply rebuild the 1.0 image based on the CUDA 8.0 image and then promote the new image.

Added ``ALIAS`` file, which specifies what the image name should be, similarly to how we build multiple versions of ``nginx`` and ``httpd``.

Note that the image ``CMD`` was changed from ``./vectorAdd`` to ``nvidia-smi && ./vectorAdd`` in 2.0.

#### Which issue(s) this PR fixes:

Related: https://github.com/kubernetes/kubernetes/issues/96770
Related: https://github.com/kubernetes/kubernetes/pull/100886
Depends On: https://github.com/kubernetes/test-infra/pull/21695

#### Special notes for your reviewer:

Image building logs: https://paste.ubuntu.com/p/qyx7csww7h/

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by spiffxp** [comment]
/cc
to review after k8s-infra meeting

**Comment by pacoxu** [comment]
milestone  1.22 as #96770 ?

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/milestone v1.22
As sig-testing chair

**Pull request merged**
