### PR TITLE
clean unused error type variable

### PR DESCRIPTION
**Pull request by WanLinghao**
**What this PR does / why we need it**:
The function which invoked this variable was removed by
https://github.com/kubernetes/kubernetes/pull/58725/
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by WanLinghao** [comment]
@mikedanese PTAL

**Comment by php-coder** [comment]
@WanLinghao Please, fix the compilation:
> pkg/serviceaccount/jwt.go:25:2: imported and not used: "errors"

/lgtm cancel

**Comment by WanLinghao** [comment]
@php-coder  Not noticing this produced lots of trash mail, sorry about that. Anyway,  I have fixed the excess package name, so please unhold this, Thanks!

**Comment by WanLinghao** [comment]
@deads2k Please help me unhold this patch, thanks!

**Pull request merged**
