### PR TITLE
kubelet: enable CRI container metrics

### LINKED ISSUE #46984: CRI: instruct kubelet to (optionally) consume container stats from CRI
#45614 augmented CRI with container stats method. 
 - [ ] Make cadvisor (`pkg/kubelet/cadvisor`) implement the container stats part of the summary api (`pkg/kubelet/server/stats`).
 - [ ] Refactor kubelet to have the flexibility to consume container stats either from cadvisor or from CRI.

We may also need to modify cadvsior to report UUID for the as the storage identifier.

Related issues:
 - ImageFS implementation (#33048)
 - Previous meta issue: #27097. 
/cc @dchen1107 @feiskyer @Random-Liu

### PR DESCRIPTION
**Pull request by yujuhong**
Fixes #46984

### CODE REVIEW

**Comment by dchen1107** [comment]
Can you update your pr with the referred issue?

/lgtm

**Comment by Random-Liu** [comment]
Can we mark this 1.8? I believe this is a 1.8 feature, right?

**Comment by sjenning** [comment]
fyi @derekwaynecarr

**Pull request merged**
