### PR TITLE
Update npd version to 0.8.13 in configure.sh

### PR DESCRIPTION
**Pull request by bzsuni**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
none
```

### CODE REVIEW

**Comment by pacoxu** [comment]
Would you update https://github.com/kubernetes/kubernetes/blob/04e38b2de8ad16f1e778106c35f6d2cf94799ed4/build/dependencies.yaml#L91-L108？

**Comment by bzsuni** [comment]
> Would you update the below?
> 

I've made some changes. Would you be so kind as to review it for me once again? Thank you.

**Pull request merged**
