### PR TITLE
Fix godeps restore by responding to structural changes in go-md2man

### PR DESCRIPTION
**Pull request by derekwaynecarr**
In an effort to try to bump up a dependency in go-dockerclient I discovered that we are no longer able to do a godep restore or save at head because of changes to go-md2man.

I updated the go-md2man dependency and changed the code in gen_kubectl_man to match.

cc @eparis since you were in this area.

Fixes https://github.com/GoogleCloudPlatform/kubernetes/issues/10195

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
Actually, I need to update man pages that are generated from this.

**Comment by karlkfi** [comment]
did you need to alias the import?

**Comment by derekwaynecarr** [comment]
@eparis - I think you are the manpage expert, so last commit contains the generated output to make it easier for you to see.  I can squash commit 2 and 3 if this looks right to you.

**Comment by derekwaynecarr** [comment]
I do not understand the Travis or Shippable complaints.  The way I see it, the docs at HEAD are missing fields.

**Comment by pmorie** [comment]
@derekwaynecarr Shippable looks like a possible problem w/ godeps -- couldn't find the md2man package.  Travis looks like verify-gendocs.sh isn't happy, did you run that locally?

**Comment by derekwaynecarr** [comment]
@pmorie - it builds locally and precommit hooks worked locally.

**Comment by pmorie** [comment]
I kicked travis, cannot find how to kick shippable

**Comment by eparis** [comment]
so NAK.  This is picking up the 'in' and 'out' flags defined in md2man in our man pages. I'll keep poking. I thought when I tried to do this it failed because both mangen and md2man were providing `func main()`

**Comment by eparis** [comment]
To begin to fix this I created:
https://github.com/cpuguy83/go-md2man/pull/14

Hopefully he will take that PR and we can cleanly rebase...

**Comment by derekwaynecarr** [comment]
I opened https://github.com/GoogleCloudPlatform/kubernetes/pull/12147 to fix the short-term issue, will close this for now and when your issue is resolved upstream, we can revisit.

**Pull request closed without merging**
