### PR TITLE
Support completion for kubectl config set-context

### PR DESCRIPTION
**Pull request by superbrothers**
**What this PR does / why we need it**:
This PR adds completion support for kubectl config set-context. I tested this PR with both bash and zsh.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Support completion for kubectl config set-context
```

### CODE REVIEW

**Comment by superbrothers** [comment]
@shiywang ping

**Comment by superbrothers** [comment]
@dshulyak @shiywang Could you please review this PR?

**Comment by shiywang** [comment]
this generally LGTM, @superbrothers could you fix the bazel test, then I will test on my laptop and label it.

**Comment by superbrothers** [comment]
@shiywang I rebased this branch. Thank you for your comment!

**Pull request closed without merging**
