### PR TITLE
Remove workaround for libcontainer Getfilecon bug

### PR DESCRIPTION
**Pull request by pmorie**
https://github.com/docker/libcontainer/issues/499 has been fixed

### CODE REVIEW

**Comment by pmorie** [comment]
@vmarmol PTAL

**Comment by pmorie** [comment]
I have a clean e2e run now.  SELinux isn't enabled in GCE and therefore the bug doesn't present there.

**Comment by vmarmol** [comment]
LGTM, thanks for noticing and fixing!

**Comment by timothysc** [comment]
Sweet, I'll give it a whirl!

**Pull request merged**
