### PR TITLE
Fix after the pod workers delete pod syncTerminated failed ,kubelet cann't start a new pod with the same namespacedname

### LINKED ISSUE #113091: after the pod workers delete pod syncTerminated failed  ,kubelet cann't start a new pod with the same namespacedname
### What happened?

Started a cluster with kubelet v1.22.5
Added a static pod yaml to /etc/kubernetes/manifest/
Observed the pod run successfully
Then remove the static pod yaml
Observed the pod is removed
And then add the same static pod yaml only change the pod id
Observed the static pod new start 

kubelet log display：
"Error syncing pod, skipping" err="mounted volumes=[cert-dir data-dir log-dir resource-dir static-pod-dir usr-local-bin]: timed out waiting for the condition"……

kubelet log also display  Cyclicly： 
"Pod cannot start yet"
"Pod cannot start yet"
……

### What did you expect to happen?

after the old pod deleted , a new pod with the same name and namespace can be start successfully

### How can we reproduce it (as minimally and precisely as possible)?

it occurs in a private cloud environment occasionally；
 the kubelet log shows  umount pod volumes failed when deleting the old pod will occurs the  bug 

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
v1.22.5
```

</details>

### Cloud provider

<details>
openshift
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by dsxing**
fix-113091

#### What type of PR is this?

/kind bug 

#### What this PR does / why we need it:

when delete a pod , the pod worker will Terminate and cleanup the pod information;
if syncTerminatedPodFn returned error such as umount the pod volumes failed or delete cgroups failed, 
the pod was put to workQueue and expected to retry synchronization , And the pod status.finished was **false**;
but the pod was deleted, and  the syncLoopIteration  configCh will never receive a message  to  dispatch the pods for the config change to the appropriate  handler callback for the event type;
so the old pod info was stored in pod worker map 'startedStaticPodsByFullname' and cann't be cleanup;
(the 'startedStaticPodsByFullname' map use pod.Name + "_" + pod.Namespace as pod keys).
on the other hand，the housekeeping timer could not cleanup the pod infomations because of the pod status.finished was **false**, 

so a new pod with the same namespacedname cann't start, because the map 'startedStaticPodsByFullname' store the old pod information with the same key.

This PR set pod **status.finished= true** when pod worker call syncTerminatedPodFn return an error , so that the housekeeping timer will cleanup the pod information, the new pod the same namespacedname  can start successfully

#### Which issue(s) this PR fixes:

Fixes #113091
Fixes https://github.com/kubernetes/kubernetes/issues/113091

#### Special notes for your reviewer:

/cc  @smarterclayton
/cc  @ehashman

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by s-kawamura-w664** [comment]
I am not familiar with the kubelet, but this PR is similar to #113065.
Is there any difference?

**Comment by smarterclayton** [comment]
I am fairly certain the bug listed here is the same as what #113065 is intended to fix.  However, the issue here might not be actually fixed, and so we might want to add a small tweak to #113065 so that HandlePodCleanups also drives the pod worker loop for those pods.

**Comment by dsxing** [comment]
oh,   The phenomenon is the same
> I am fairly certain the bug listed here is the same as what #113065 is intended to fix. However, the issue here might not be actually fixed in that change, and so we might want to add a small tweak to #113065 so that HandlePodCleanups also drives the pod worker loop for those pods.

**Comment by dsxing** [comment]
> I am not familiar with the kubelet, but this PR is similar to #113065. Is there any difference?

oh,  the phenomenon is the same;

**Comment by SergeyKanzhelev** [comment]
please re-open the PR with tests included. Without tests this change will be hard to validate and accept. Especially given there is another PR trying to address similar issue.

/close

**Pull request closed without merging**
