### PR TITLE
dependencies :  update  gopkg.in/natefinch/lumberjack.v2 v2.0.0 to v2.2.1

### PR DESCRIPTION
**Pull request by mohitsharma-in**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
update `gopkg.in/natefinch/lumberjack.v2` v2.0.0 to v2.2.1 
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/ok-to-test

very minor changes in the actual code that got updated in vendor. 
/approve

**Comment by mohitsharma-in** [comment]
Can someone please LGTM also

**Pull request merged**
