### PR TITLE
add support to log in kubeadm

### LINKED ISSUE #42727: Where's the log files of cluster setup by kubeadm?
Hi there,

I setup my Kubernetes cluster on CentOS 7 by kubeadm, I can view the logs via 'kubectl logs $pod -f', but I can't find the logs files either in the /var/log/containers directory or the /var/lib/docker/containers directory.  And even I searched the whole system by the system find command, there's no log file related to kubernetes pod. This is really weird.

Any suggestions?

### PR DESCRIPTION
**Pull request by xilabao**
output log messge to  `/var/log/kubernetes/` 
fixes https://github.com/kubernetes/kubernetes/issues/42727

### CODE REVIEW

**Comment by xilabao** [comment]
@errordeveloper

**Comment by xilabao** [comment]
@luxas

**Comment by wuzesheng** [comment]
@xilabao When will this PR be merged?

**Comment by xilabao** [comment]
@wuzesheng  It's decided by the maintainers.  Need feedback from member of the team. 
@errordeveloper @luxas @jbeda @mikedanese

**Comment by wuzesheng** [comment]
@xilabao OK, Got it, thanks for working on this issue:)

**Comment by mikedanese** [comment]
We don't do this in any other component. We just pipe stdout to a file which is a very common pattern. I don't know why we would do anything different here. I'm opposed to this change.

**Comment by xilabao** [comment]
> We just pipe stdout to a file which is a very common pattern.


@mikedanese api-server and others are created in container. I think it's necessary to pipe stdout to a file in code. and it's helpful to mount the log dir for other logs. such as audit log. 
 I looked at https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/kube-apiserver/kube-apiserver.manifest#L215

**Comment by luxas** [comment]
I'm sorry @xilabao, but the community is collectively moving away from files on disk at every place possible in general, and this would unfortunately be a step backwards.

There are still lots of ways to collect and aggregate logs in your cluster; I'd recommend running Fluentd or the like for that. Or you can just stream `docker logs <apiserver-cid>` to a file of your taste on your disk if you really really need this.

**Comment by m1093782566** [comment]
@luxas. How should we grab the log from kubelet? Since kubelet is not run inside container.

**Comment by luxas** [comment]
@m1093782566 `journalctl -xeu kubelet` for instance. Just grab the logs as from any other systemd unit

**Comment by nelson-cf** [comment]
anyone know where are the container logs on the kube nodes?  Trying to read them into fluentd, but I can not find them.

**Comment by nelsonfassis** [comment]
@luxas and how am I supposed to use it with filebeat, for example? They don't have something similar on their documentation and I couldn't make it work, can you help us?

It is supposed to work like this:
    - type: log
      paths:
        - /var/lib/docker/containers/*/*.log

However there is no */*.log on my nodes. 

Thanks

**Comment by nelsonfassis** [comment]
If someone has the same problems that I had:
You can edit you /etc/docker/daemon.json to set its default log to json files and set a max size and max files to take care of the log rotation. After that, logs wont be written to journald and you will be able to send your log files to ES.

**Comment by rwarford** [comment]
Lack of logging is a significant problem.  For example, I have been attempting to set up a cluster in AWS using Kubeadm (kops wasn't an option in this particular case).  However, kube-proxy crashes a couple of seconds after I init the cluster.  Unfortunately the pod is deleted immediately and so I have no way to get to the logs to determine what has happened.

**Pull request closed without merging**
