### PR TITLE
Fixing docker fake client - InspectExec

### PR DESCRIPTION
**Pull request by krzysied**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Prevents docker nil pointer panics when fake client is used.

**Which issue(s) this PR fixes**:

ref #84855

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/assign @random-liu @wojtek-t 

Thank you for your work here :)

**Comment by krzysied** [comment]
Why do I see "pull-kubernetes-kubemark-e2e-gce-scale "? 
It wasn't started anywhere here.

**Comment by krzysied** [comment]
Third attempt to merge this PR - https://github.com/kubernetes/kubernetes/pull/84983
This time github hasn't added pull-kubernetes-kubemark-e2e-gce-scale...

**Pull request closed without merging**
