### PR TITLE
Explicitly declare the interfaces for extension points

### PR DESCRIPTION
**Pull request by chendave**
This make it easier to catch the issue during the compilation, also,
this also align with other plugins, i.e. plugin of "InterPodAffinity".

Signed-off-by: Dave Chen <dave.chen@arm.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by damemi — APPROVED** [review]
/lgtm
/retest

**Comment by alculquicondor** [comment]
/approve

Some go folks would say that this is an antipattern, but if it makes developing easier, it's fine.

Note that compatibility tests and other scheduler initialization tests would catch that the interface wasn't properly defined, but at runtime.

**Pull request merged**
