### PR TITLE
Automated cherry pick of #16919 upstream release-1.1

### PR DESCRIPTION
**Pull request by ikehz**
Cherry pick of #16919 onto release-1.1: enable prerelease push official release.

FYI @brendandburns

### CODE REVIEW

**Comment by ihmccreery** [comment]
@k8s-bot test this again please

**Comment by ihmccreery** [comment]
@k8s-bot unit test this please

**Comment by ihmccreery** [comment]
@k8s-bot test this again please

**Comment by ihmccreery** [comment]
@k8s-bot unit test this please

**Comment by quinton-hoole** [comment]
LGTM!  Thanks @ihmccreery

**Comment by ihmccreery** [comment]
@k8s-bot unit test this please

**Comment by ihmccreery** [comment]
@k8s-bot unit test this please :disappointed:

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by ihmccreery** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
unit tests are failing with the following error:

    11:30:41 _output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait_test.go:256: too many arguments in call to WaitFor

@ihmccreery can you please rebase (it should fix this problem)

**Comment by ihmccreery** [comment]
Just a rebase; re-applying LGTM.

**Pull request merged**
