### PR TITLE
drop the option mark from the InvolvedObject field of internal event object

### LINKED ISSUE #127403: Is event.InvolvedObject fields is required in kubernetes?
### What happened?

When I try to create an event with an empty `InvolvedObject` in k8s with client-go, I get a validation error `“InvolvedObject.namespace does not match event.namespace”` and the creation fails.

### What did you expect to happen?

This is probably because the validation step of event does not check the status of the `InvolvedObject` itself, but refers to event.InvolvedObject.Namespace.
https://github.com/kubernetes/kubernetes/blob/7ad1eaa66bc5cf270a0b44889aac555529feff83/pkg/apis/core/validation/events.go#L159-L161

### How can we reproduce it (as minimally and precisely as possible)?

This function will fail due to a validating error.
```
func createEvent(clientset *kubernetes.Clientset, pod *corev1.Pod) {
	event := &corev1.Event{
		ObjectMeta: metav1.ObjectMeta{
			GenerateName: "pod-created-",
			Namespace:    pod.Namespace,
		},
		// InvolvedObject: corev1.ObjectReference{
		// 	Kind:      "Pod",
		// 	Namespace: pod.Namespace,
		// 	Name:      pod.Name,
		// 	UID:       pod.UID,
		// },
		Reason:  "PodCreated",
		Message: fmt.Sprintf("Pod %s was created", pod.Name),
		Type:    "Normal",
		Source: corev1.EventSource{
			Component: "pod-watcher",
		},
	}

	_, err := clientset.CoreV1().Events(pod.Namespace).Create(context.TODO(), event, metav1.CreateOptions{})
	if err != nil {
		fmt.Printf("Error creating event: %v\n", err)
	}
}
```

The below function is working.
```
func createEvent(clientset *kubernetes.Clientset, pod *corev1.Pod) {
	event := &corev1.Event{
		ObjectMeta: metav1.ObjectMeta{
			GenerateName: "pod-created-",
			Namespace:    pod.Namespace,
		},
		InvolvedObject: corev1.ObjectReference{
		// 	Kind:      "Pod",
			Namespace: pod.Namespace,
		// 	Name:      pod.Name,
		// 	UID:       pod.UID,
		// },
		Reason:  "PodCreated",
		Message: fmt.Sprintf("Pod %s was created", pod.Name),
		Type:    "Normal",
		Source: corev1.EventSource{
			Component: "pod-watcher",
		},
	}

	_, err := clientset.CoreV1().Events(pod.Namespace).Create(context.TODO(), event, metav1.CreateOptions{})
	if err != nil {
		fmt.Printf("Error creating event: %v\n", err)
	}
}
```

### Anything else we need to know?

It looks like validating only checks the `Namespace` field in `InvolvedObject`.
If kubernetes decide to require `InvolvedObject` field for event resource, I feel we need to add more validation.

### Kubernetes version

<details>

```console
 Kubernetes v1.29.2
```

</details>

### Cloud provider

<details>
```
on-prem
```
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

See https://github.com/kubernetes/kubernetes/issues/127403#issuecomment-2362142902

#### Which issue(s) this PR fixes:

Fixes #127403

#### Special notes for your reviewer:

/hold

util https://github.com/kubernetes/kubernetes/issues/127403#issuecomment-2372846238 is resolved.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
answered at https://github.com/kubernetes/kubernetes/issues/127403#issuecomment-2374491518

this change is all we should do

/hold cancel

**Comment by BenTheElder** [comment]
Thanks!

**Comment by koba1t** [comment]
Thanks, @carlory and @BenTheElder!

**Pull request merged**
