### PR TITLE
Change no-negcache to neg-ttl=5s in kube-dns

### PR DESCRIPTION
**Pull request by joekohlsdorf**
**What this PR does / why we need it**:
In https://github.com/kubernetes/kubernetes/pull/53604 a change was introduced which disables negative DNS caching in dnsmasq to mitigate failing service discovery due to long negative DNS cache TTL.

Every major cloud provider has a limit for the number of queries to their DNS servers, kube-dns should do as much as possible to reduce the number of queries hitting these upstream DNS servers. One kube-dns instance could be serving hundreds of containers and none of them are doing DNS caching.

Imagine an application which doesn't have database connection pooling that connects to a database which runs outside of Kubernetes and is accessed by its hostname. This leads to a query for every connection attempt to the upstream DNS servers because the resolver will always try to also look up AAAA records which in most cases don't exist; with `--no-negcache` these will never be cached. One could argue that the app is broken but traditionally the argument has always been that you should implement DNS caching, in Kubernetes the right place to do this is kube-dns.

Instead of disabling negative DNS caching, this PR reintroduces it with a very low TTL. In our environment, setting `--neg-ttl=5` reduced the amount of queries to the upstream DNS server across the cluster by a factor of 10. A cache of 5s is a reasonable tradeoff between speed of service-discovery, performance and cache effectiveness.

**Which issue(s) this PR fixes**: https://github.com/kubernetes/dns/issues/239

**Release note**:
```release-note
Activate negative DNS caching with a TTL of 5s in kube-dns dnsmasq.
```

### CODE REVIEW

**Comment by joekohlsdorf** [comment]
Rebased PR onto current master, please have a look @bowei.

**Comment by MrHohn** [comment]
@prameshj

**Comment by chrisohaver** [comment]
Recommend reviewing kubernetes/dns#121 to see if this change will re-introduce that issue. (upstream DNS providers may respond with unreasonably long negative cache TTLs)

Regarding the ` --neg-ttl` this option ...
> --neg-ttl=<time>   Negative replies from upstream servers normally contain time-to-live information in SOA records which dnsmasq uses for caching. If the replies from upstream servers omit this information, dnsmasq does not cache the reply. This option gives a default value for time-to-live (in seconds) which dnsmasq uses to cache negative replies even in the absence of an SOA record.

The dnsmasq man page implies that this setting is used only when the upstream DNS does not include an SOA record.  If the upstream does contain an SOA record, then the TTL of the SOA record is used.  If the SOA TTL really big number, then dnsmasq will cache it for that length of time (not 5 seconds).

So, IIUC, this change would re-open kubernetes/dns#121.

May want to consider also using ... `--max-cache-ttl`, to set the maximum TTL value for entries in the cache to mitigate this.  I don't know if that setting also applies to negative cache (hopefully it does).

FYI (shameless plug), CoreDNS in it's default configuration does not have these issues.  It enables negative caching by default, and has a max-ttl behavior for cache by default.

**Comment by chrisohaver** [comment]
> I was actually thinking about just closing this entirely without any action because CoreDNS is now the default (and dnsmasq should rest in peace) so having this fix in newer versions of K8s does nothing.

Well, kube-dns isn't dead yet.  And CoreDNS isn't the default yet.  In 1.11 it became an approved alternative to kube-dns (in 1.10 it was a beta alternative to kube-dns).  In other words, it's no longer beta in 1.11.

It _is_ the default in _kubeadm_ 1.11... but that's not the same as "default in kubernetes"...

In 1.13, or possibly later, we hope to make CoreDNS the "recommended default in kubernetes".  This is mainly just a documentation change at that point.  Once it happens, more k8s cloud providers and install tools will start moving to CoreDNS.

Kube-dns wont be deprecated until later (if that happens), so it will still be getting parallel support with CoreDNS for a at least few more releases.

**Comment by prameshj** [comment]
Removing the --no-negcache flag in dnsmasq opens up the possibility of making cluster internal hostnames unresolvable. If resolution of a hostname in the 'cluster.local' domain happens in the upstream DNS resolver for some reason, that will return NXDOMAIN and dnsmasq caches the NXDOMAIN response. It does require the user to follow specific steps to make this happen, but leaving the flag on for now seems like the best option.

**Comment by joekohlsdorf** [comment]
For this reason it is set to a very low value of 5s.

With the current default you can hit AWS DNS request limits easily. The worst about it is that there are no metrics for this so most people probably don't even know when this is happening.

Adding `--no-negcache` should never have gotten accepted as a solution for https://github.com/kubernetes/dns/issues/121 and #53604 which I already explained in the PR.

**Comment by chrisohaver** [comment]
>Adding --no-negcache should never have gotten accepted as a solution for kubernetes/dns#121 and #53604 which I already explained in the PR.

Setting a `--max-cache-ttl`, if it applies to negative cache too (which I would guess it does), seems like a better solution to kubernetes/dns#121.

The `--neg-ttl` will add a TTL to all negative responses that don't have a TTL. This includes upstream responses, and could result in caching responses longer than the authoritative server intended.  IMO, strictly speaking thats a little bit of a no-no, so probably shouldn't be a default setting (just IMO).

kube-dns should be adding the negative cache TTLs to the cluster domain responses.  They shouldn't be added by dnsmasq, which acts on every upstream response too.

**Comment by krmayankk** [comment]
Curious does dnsmasq only cache cluster local entries or does it also cache entries which it resolves from upstream servers which dont match the cluster local domains ?

**Comment by chrisohaver** [comment]
> Curious does dnsmasq only cache cluster local entries or does it also cache entries which it resolves from upstream servers which dont match the cluster local domains ?

dnsmasq caches everything.  From it's perspective kube-dns is just another upstream server.  
There might be an option to restrict cache to certain domains.  I didnt see one scanning the flags just now, but if there is, it's not used in the k8s deployment.

**Comment by joekohlsdorf** [comment]
In the source code of dnsmasq I verified that this change will reintroduce negative caching according to the SOA records minimum TTL if one is present. `neg-ttl` is used as default if no SOA record is present (shouldn't happen).

Unfortunately `max-ttl` is not respected for negative answers.

In https://github.com/kubernetes/dns/issues/121 the problem reported was that the TTL in the SOA record wasn't respected. From looking at the code I doubt that this is possible. I'll try to reproduce this.

**Comment by adamalex** [comment]
@joekohlsdorf if you have a moment could you comment as to why this is no longer being pursued? I'm in the process of troubleshooting some cluster dns issues and this seems like a potential solution. Thanks for any info you can provide

**Pull request closed without merging**
