### PR TITLE
using glog.Infof instead of glog.V(0).Infof

### PR DESCRIPTION
**Pull request by Pingan2017**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yue9944882** [comment]
> grep -ranI 'glog.V(0).' .

@Pingan2017 thx for fixing this. could fix other pkgs as well? ^^^

**Comment by Pingan2017** [comment]
@yue9944882  done! PTAL, Thanks!

**Comment by Pingan2017** [comment]
Thanks ! @yue9944882 
/assign @dchen1107 @gmarek

**Comment by Pingan2017** [comment]
ping @dchen1107 @gmarek
 for review, Thanks!

**Comment by Pingan2017** [comment]
@yue9944882 @yujuhong  Could u take a look? Thanks!

**Pull request closed without merging**
