### PR TITLE
Automated cherry pick of #11381

### PR DESCRIPTION
**Pull request by zmerlynn**
We should bump ContainerVM before 1.0.1. #11381 has baked in the main branch long enough.

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @roberthbailey @dchen1107

**Comment by roberthbailey** [comment]
LGTM.

**Comment by dchen1107** [comment]
LGTM thanks!

**Comment by zmerlynn** [comment]
(Travis is a flake.)

**Comment by zmerlynn** [comment]
And now Travis is the short version from master. :)

**Comment by zmerlynn** [comment]
Shippable is 1/2 here, and the 1 looks like a flake, plus this is all config.

**Pull request merged**
