### PR TITLE
fix failing travis

### PR DESCRIPTION
**Pull request by deads2k**
Looks like https://github.com/kubernetes/kubernetes/pull/20626 missed these files.

Fixes https://github.com/kubernetes/kubernetes/issues/21538

@kubernetes/rh-oncall

### CODE REVIEW

**Comment by deads2k** [comment]
This is failing travis.  Adding priority to match issue.

**Comment by deads2k** [comment]
Looks like this is making all travis runs red (see the PR queue), bumping to p0.  If this gets a clean verify, we should consider a manual merge.

**Comment by deads2k** [comment]
travis is clean, can I get a merge to fix travis?

**Comment by deads2k** [comment]
Self-applied lgtm to fix travis

**Comment by justinsb** [comment]
LGTM also

**Comment by deads2k** [comment]
@liggitt manual merge?  Flaked on https://github.com/kubernetes/kubernetes/issues/21467

**Comment by liggitt** [comment]
"deployment should support rollback" e2e flake. got one clean e2e run (https://github.com/kubernetes/kubernetes/pull/21539#issuecomment-186217283) and travis and unit tests pass, manually merging

**Comment by AdoHe** [comment]
@deads2k @liggitt Thanks very much. I must hang my head, I just checkout these two files.

**Pull request merged**
