### PR TITLE
Updated priority of mirror pod by PriorityClass.

### LINKED ISSUE #58471: Priority admission controller should resolve priority of mirror pods
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Priority admission controller [skips resolving PriorityClassName](https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/priority/admission.go#L159) of mirror pods. This is an error and should be removed.

**What you expected to happen**:
Integer value of Priority should be populated by the admission controller.

**How to reproduce it (as minimally and precisely as possible)**:
Create a static pod with PriorityClassName set. The created mirror pod will not get the integer value of priority.

/sig scheduling
xref #58379

### PR DESCRIPTION
**Pull request by k82cn**
Signed-off-by: Da K. Ma <madaxa@cn.ibm.com>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #58471 

**Release note**:
```release-note
Updated priority of mirror pod according to PriorityClassName.
```

### CODE REVIEW

**Comment by bsalamat** [comment]
LGTM

**Comment by k82cn** [comment]
Will remove WIP after double confirmed kubelet's behaviour and added a unit test :).

**Comment by k82cn** [comment]
Added UT cases, it's ready for review :).

**Comment by derekwaynecarr** [comment]
LGTM

/approve

**Comment by vainu-arto** [comment]
Would this be a candidate for cherry-picking to 1.9 and 1.8?

**Comment by bsalamat** [comment]
This is a bug in an alpha feature, but I still think we should cherrypick it to 1.8 and 1.9.

**Comment by k82cn** [comment]
Opened related issues for cherry pick :).

**Pull request merged**
