### PR TITLE
Add annotations for defaultedInternalConfig

### PR DESCRIPTION
**Pull request by xichengliudui**
**What type of PR is this?**

**What this PR does / why we need it**:
add annotations for defaultedInternalConfig

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
/hold
/kind cleanup
/priority needs-more-evidence

@xichengliudui 
i'm sorry but the comment is redundant for this private small utility function.

i will defer to @fabriziopandini for a `/close` but my vote goes for that.

**Comment by xichengliudui** [comment]
@fabriziopandini  Is the comment of this function redundant?

**Comment by neolit123** [comment]
please at least change it to this:
```
// defaultedInternalConfig obtains the internal kubeadm ClusterConfiguration with default values.
```

**Pull request closed without merging**
