### PR TITLE
feat(scheduler): rename PluginContext to CycleState

### PR DESCRIPTION
**Pull request by draveness**
/kind cleanup
/sig scheduling
/assign @alculquicondor @ahg-g 

**What this PR does / why we need it**:
rename PluginContext to CycleState

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Rename PluginContext to CycleState in the scheduling framework
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/lgtm

Any particular reason why you used the variable name `cycleState` in some places and `state` in others?
I'm ok with just having `state` for the variables unless there is ambiguity.

**Comment by draveness** [comment]
> Any particular reason why you used the variable name `cycleState` in some places and `state` in others?
> I'm ok with just having `state` for the variables unless there is ambiguity.

I make the following changes

+ pluginContext -> cycleState
+ pc -> state

**Comment by alculquicondor** [comment]
To increase consistency, I suggest we just use `state` unless there's a collision. WDYT @ahg-g ?

**Comment by draveness** [comment]
> To increase consistency, I suggest we just use `state` unless there's a collision. WDYT @ahg-g ?

I think it would be hard to do this since we already have such inconsistency among the codebase, e.g. pluginContext and pc. If you think it would be a problem, I could replace `cycleState` with `state` in the PR. It does not sound like a big problem to me.

**Comment by ahg-g** [comment]
> To increase consistency, I suggest we just use `state` unless there's a collision. WDYT @ahg-g ?

+1 for consistency. We can't use ```cs``` since it refers usually to a ```ClientSet``` instance, so I guess we can set the precedence that ```state``` in the context of the scheduler means ```CycleState```.

**Comment by draveness** [comment]
> > To increase consistency, I suggest we just use `state` unless there's a collision. WDYT @ahg-g ?
> 
> +1 for consistency. We can't use `cs` since it refers usually to a `ClientSet` instance, so I guess we can set the precedence that `state` in the context of the scheduler means `CycleState`.

done

**Review by alculquicondor — COMMENTED** [review]
/lgtm

Thanks @draveness

**Comment by draveness** [comment]
/retest

Regards,
Draven

**Comment by draveness** [comment]
@ahg-g Rebased the master and fixed the test, PTAL

**Comment by draveness** [comment]
/retest

Regards,
Draven

**Pull request merged**
