### PR TITLE
Should always use plural form for resource names

### PR DESCRIPTION
**Pull request by yue9944882**
> Resource collections should be all lowercase and plural, whereas kinds are CamelCase and singular. Group names must be lower case and be valid DNS subdomains.

Singular resource name is meaningless (for now).

/kind cleanup
/sig api-machinery

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by 0xmichalis — APPROVED** [review]
/lgtm

**Comment by sttts** [comment]
Please don't mix manual and generated changes.

Can you rebase?

**Pull request closed without merging**
