### PR TITLE
kubectl create (role, job, cronjob) respect --namespace with --dry-run

### PR DESCRIPTION
**Pull request by Antiarchitect**
Signed-off-by: Andrey Voronkov <voronkovaa@gmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
For `kubectl create role`, `kubectl create job`, `kubectl create cronjob` respect `--namespace` global option when doing Dry Run.
Constructions like `kubectl create role ... --dry-run -o yaml | kubectl apply -f -` are useful for Create or Update operations imitation inside the scripts.

**Which issue(s) this PR fixes**:

I have not found them :(

**Special notes for your reviewer**:
Not a Go coder at all, so I cannot write appropriate tests, but here is system kubectl output:

### kubectl v1.14.0
```
kubectl create role --namespace test testrole --verb=* --resource=*.apps --dry-run -o yaml                                   
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: testrole
rules:
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - '*'
```
### Built kubectl
```
_output/dockerized/bin/linux/amd64/kubectl create role --namespace test testrole --verb=* --resource=*.apps --dry-run -o yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: testrole
  namespace: test
rules:
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - '*'
```

### kubectl v1.14.0
```
kubectl create job --namespace test testjob --image nginx:1.15.10-alpine --dry-run -o yaml
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: testjob
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: nginx:1.15.10-alpine
        name: testjob
        resources: {}
      restartPolicy: Never
status: {}
```
### Built kubectl
```
_output/dockerized/bin/linux/amd64/kubectl create job --namespace test testjob --image nginx:1.15.10-alpine --dry-run -o yaml
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: testjob
  namespace: test
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: nginx:1.15.10-alpine
        name: testjob
        resources: {}
      restartPolicy: Never
status: {}
```

### kubectl v1.14.0
```
kubectl create cronjob --namespace test testcronjob --image nginx:1.15.10-alpine --schedule "0 * * * *" --dry-run -o yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: testcronjob
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: testcronjob
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: nginx:1.15.10-alpine
            name: testcronjob
            resources: {}
          restartPolicy: OnFailure
  schedule: 0 * * * *
status: {}
```
### Built kubectl
```
_output/dockerized/bin/linux/amd64/kubectl create cronjob --namespace test testcronjob --image nginx:1.15.10-alpine --schedule "0 * * * *" --dry-run -o yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: testcronjob
  namespace: test
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: testcronjob
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: nginx:1.15.10-alpine
            name: testcronjob
            resources: {}
          restartPolicy: OnFailure
  schedule: 0 * * * *
status: {}
```
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by juanvallejo** [comment]
/ok-to-test
/lgtm

cc @soltysh

**Comment by Antiarchitect** [comment]
@juanvallejo We need to fix tests somehow. Not sure I have expertise in Go to do that but working on it.

**Comment by Antiarchitect** [comment]
@juanvallejo I've managed to fix tests - all green now.

**Comment by Antiarchitect** [comment]
@juanvallejo @mengqiy

**Review by soltysh — CHANGES_REQUESTED** [review]
Why should we care about fixing those? The namespace is implied through the client call and applied correctly. I don't think we need to set it explicitly, we rarely do anywhere else. 
/hold

**Comment by Antiarchitect** [comment]
At least for the similar behavior for all objects created via `kubectl create`: only these three do not respect `--namespace` option on dry-run.

**Pull request closed without merging**
