### PR TITLE
[Federation] Replace the indexing lister with a regular store in the replicaset controller

### PR DESCRIPTION
**Pull request by perotinus**
This is part of the refactoring work to allow the replicaset controller to use the generic sync controller.

None of the other controllers use a lister, including the deployment controller

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by spiffxp** [comment]
@k8s-bot ok to test

**Comment by marun** [comment]
Assuming tests pass this lgtm

@k8s-bot pull-kubernetes-federation-e2e-gce test this
status: http://prow.k8s.io/?type=presubmit&pull=45256&job=pull-kubernetes-federation-e2e-gce

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45256#-:-KjndDxC3raSq4UTFPrh:bnw97i4)*

**Comment by madhusudancs** [comment]
/approve

Waiting for the tests to add lgtm.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45256#-:-Kjnl_r3a7WScO39ew4H:b-f3b7u7)*

**Comment by perotinus** [comment]
@madhusudancs Looks like the tests passed: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45256/pull-kubernetes-federation-e2e-gce/3991/

**Comment by perotinus** [comment]
@madhusudancs Can you rerun the tests? I think this is a flake.

**Comment by madhusudancs** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
