### PR TITLE
fix taint controller panic

### LINKED ISSUE #51586: Taint controller panic error
Just saw this while running kube master locally:

```
controller : E0829 23:28:35.313186    4919 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
controller : /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
controller : /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
controller : /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
controller : /data/go/src/runtime/asm_amd64.s:514
controller : /data/go/src/runtime/panic.go:489
controller : /data/go/src/runtime/panic.go:63
controller : /data/go/src/runtime/signal_unix.go:290
controller : /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/node/scheduler/taint_controller.go:287
controller : /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/node/node_controller.go:375
controller : /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/node/util/controller_utils.go:297
controller : /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:195
controller : <autogenerated>:57
controller : /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:545
controller : /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:381
controller : /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
controller : /data/go/src/runtime/asm_amd64.s:2197
controller : panic: runtime error: invalid memory address or nil pointer dereference [recovered]
controller :    panic: runtime error: invalid memory address or nil pointer dereference
controller : [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1c25ffd]
controller : 
controller : goroutine 953 [running]:
controller : k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
controller :    /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
controller : panic(0x2ebb520, 0x4e5cad0)
controller :    /data/go/src/runtime/panic.go:489 +0x2cf
controller : k8s.io/kubernetes/pkg/controller/node/scheduler.(*NoExecuteTaintManager).NodeUpdated(0x0, 0x0, 0xc421902000)
controller :    /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/node/scheduler/taint_controller.go:287 +0x1ad
controller : k8s.io/kubernetes/pkg/controller/node.NewNodeController.func8(0xc421902000, 0x348f980, 0xc4202a2000)
controller :    /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/node/node_controller.go:375 +0x44
controller : k8s.io/kubernetes/pkg/controller/node/util.CreateAddNodeHandler.func1(0x348f980, 0xc4202a2000)
controller :    /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/node/util/controller_utils.go:297 +0x89
controller : k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(0xc4218b5960, 0xc4218b5980, 0xc4218b59a0, 0x348f980, 0xc4202a2000)
controller :    /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:195 +0x49
controller : k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*ResourceEventHandlerFuncs).OnAdd(0xc4218df520, 0x348f980, 0xc4202a2000)
controller :    <autogenerated>:57 +0x73
controller : k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc4218e8370)
controller :    /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:545 +0x287
controller : k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).(k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.run)-fm()
controller :    /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:381 +0x2a
controller : k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc42025e758, 0xc4218b59d0)
controller :    /home/shared/go_projects/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x4f
controller : created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
```

Yet to investigate more closely and check which PR could have introduced this. cc @bowei

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #51586 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@xiangpengzhao thanks

**Comment by hzxuzhonghu** [comment]
Since #51633 solve this kind of panic . close this pr

**Comment by bowei** [comment]
This change still seems worthwhile to have as having the assignment after the reference seems to be a bug waiting to happen.

**Comment by xiangpengzhao** [comment]
agree with @bowei
/reopen
hope it can be merged before code freeze

**Comment by xiangpengzhao** [comment]
@k8s-ci-robot are you kidding me, my bot? :(

**Comment by spxtr** [comment]
`error:  "status code 422 not one of [200], body: {"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","field":"state","message":"state cannot be changed. The taint-controller-panic branch has been deleted."}],"documentation_url":"https://developer.github.com/v3/pulls/#update-a-pull-request"}"`

You can't reopen a PR whose branch [has been deleted](https://github.com/kubernetes/kubernetes/pull/51603#event-1228743051). We should augment prow to catch this error and make a comment!

**Comment by xiangpengzhao** [comment]
@spxtr thanks for investigating this! Agree on making a comment in this case. BTW, how can I find the log if I want to debug similar issue in the future?

**Comment by xiangpengzhao** [comment]
@hzxuzhonghu mind restoring the branch and reopening PR?

**Comment by spxtr** [comment]
> @spxtr thanks for investigating this! Agree on making a comment in this case. BTW, how can I find the log if I want to debug similar issue in the future?

The logs aren't public. Feel free to open an issue in kubernetes/test-infra.

**Comment by hzxuzhonghu** [comment]
OK， I reopen

**Comment by liggitt** [comment]
fixed by #51633

**Comment by bowei** [comment]
reopen this -- I want the code change anyway

**Pull request merged**
