### PR TITLE
add iproute2 to hyperkube base image

### LINKED ISSUE #92272: hyperkube kubelet: KillPodSandboxError ... networkPlugin cni failed to teardown pod ... network: neither iptables nor ip6tables usable
**What happened**:

* I attempted to bump the 1.16, 1.17, and 1.18 versions in my team's kubernetes image repo to 1.16.11, 1.17.7, and 1.18.4, respectively.
* The images built successfully but none of the e2e tests we run, including the kubernetes conformance e2e tests, ever actually ran correctly without a clear indication as to why -- ginkgo was just mysteriously succeeding without any tests passed, skipped, or failed. this prompted me to take a closer look a 1.18.4 cluster.
* I expected corednes pods to be in "Running" status but instead found:
```
kube-system   coredns-6b6854dcbf-tqxgn          0/1     Completed   0          5h24m
kube-system   coredns-6b6854dcbf-wztzn          0/1     Completed   0          5h24m
```
* ...and the following event on one of those pods:
```
  Normal  SandboxChanged  98s (x627 over 136m)  kubelet, test-1-18-4-0b8b9360-3fhas  Pod sandbox changed, it will be killed and re-created.
```
* This even prompted me to log on to a worker node and notice repeated messages like the following in the kubelet logs:
```
Jun 18 21:41:53 test-1-18-4-06729635-3f4er docker[1211]: E0618 21:41:53.316852    1291 pod_workers.go:191] Error syncing pod f364dc8e-6e7d-4869-976a-678a3ce913ac ("coredns-6b6854dcbf-2t9cv_kube-system(f364dc8e-6e7d-4869-976a-678a3ce913ac)"), skipping: failed to "KillPodSandbox" for "f364dc8e-6e7d-4869-976a-678a3ce913ac" with KillPodSandboxError: "rpc error: code = Unknown desc = networkPlugin cni failed to teardown pod \"coredns-6b6854dcbf-2t9cv_kube-system\" network: neither iptables nor ip6tables usable"
```

This led me to grep through the kubernetes repo at v1.18.4 for the message `network: neither iptables nor ip6tables usable` but I didn't find anything. So I did the same thing in the containernetworking plugins repo and found the following references:

* https://github.com/containernetworking/plugins/blob/ad10b6fa91aacd720f1f9ab94341a97a82a24965/plugins/meta/portmap/portmap.go#L120
* https://github.com/containernetworking/plugins/blob/ad10b6fa91aacd720f1f9ab94341a97a82a24965/plugins/meta/portmap/portmap.go#L384

It's kind of hard to tell which of the possible `maybeGetIptables` function failures occurred because it doesn't lift the error into the calling context but this led me to believe that there is something different about the iptables installed in the hyperkube container that we are are using to run our kubelets. And I did find a potentially significant difference at least between 1.18.3 and 1.18.4 (i haven't compared the patch level versions on 1.16 and 1.17 yet):

```
zsh/4 10048 % docker run --rm -it --entrypoint "" gcr.io/google-containers/hyperkube:v1.18.3 iptables --version
iptables v1.6.0
```

```
zsh/4 10047 % docker run --rm -it --entrypoint "" gcr.io/google-containers/hyperkube:v1.18.4 iptables --version
iptables v1.8.2 (nf_tables)
```

I'm not familiar enough with iptables to say with any kind of certainty that this is really the root cause of the problem, but if not then it's a pretty good red herring.

**What you expected to happen**:

I was hoping that `1.16.11`, `1.17.7`, and `1.18.4` would "just work" similar to the previous patch level versions.

**How to reproduce it (as minimally and precisely as possible)**:

I'm so far from really understanding what's going on at pretty much all times that it's actually kind of depressing but without just dumping a bunch of configuration files that I don't think would be very helpful, here is what I think may be happening:

We have `--network-plugin=cni` passed to kubelet in our systemd unit file, and some part of kubelet is somehow delegating networking stuff to the CNI binaries that appear to be copied into the hyperkube image:
```
zsh/4 10049 % docker run --rm -it --entrypoint "" gcr.io/google-containers/hyperkube:v1.18.4 ls /opt/cni/bin
bandwidth  bridge  dhcp  firewall  flannel  host-device  host-local  ipvlan  loopback  macvlan  portmap  ptp  sbr  static  tuning  vlan
```

So I'm guessing that `portmap` here corresponds to the code I linked to above in the cni plugins repo.

**Anything else we need to know?**:

I considered the possibility of *not* filing this bug and instead chiming in on #92242 or #92250 but I thought it would be better to post a new issue rather than risk the information I've gathed being lost in the noise of comments.

**Environment**: 
- Kubernetes version (use `kubectl version`):
1.16.11, 1.17.7, and 1.18.4
- Cloud provider or hardware configuration:
Digitalocean
- OS (e.g: `cat /etc/os-release`):
```
zsh/4 10051 % docker run --rm -it --entrypoint "" gcr.io/google-containers/hyperkube:v1.18.3 cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
zsh/4 10054 [2] % docker run --rm -it --entrypoint "" gcr.io/google-containers/hyperkube:v1.18.4 cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
- Kernel (e.g. `uname -a`):
```
Linux test-1-18-4-06729635-3f4er 4.19.0-0.bpo.6-amd64 #1 SMP Debian 4.19.67-2+deb10u2~bpo9+1 (2019-11-12) x86_64 GNU/Linux
```

- Install tools:
hyperkube

- Network plugin and version (if this is a network-related bug):
happens on both v0.7.4 and v0.8.6 of https://github.com/containernetworking/plugins

(we volume mount a directory containing the cni plugin binaries from our worker node host into the kubelet hyperkube containers so it appears that we can end up using a different CNI version than upstream -- I don't know why we do this, maybe in the past hyperkube didn't include the binaries or maybe we needed a specific version of CNI temporarily and just never went back to using the bundled binaries; regardless, because I've tried both versions I assume this isn't the root cause of the problem I'm seeing)

### PR DESCRIPTION
**Pull request by waynr**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

This is a very naive attempt to address one of the problems described in #92272, specifically the need to have the `iproute2` package available in the hyperkube image in order for kubelet to do its thing.

**Which issue(s) this PR fixes**:

Fixes #92272

**Special notes for your reviewer**:

I am also considering adding the following to the hyperkube image:

```
# update-alternatives --set iptables /usr/sbin/iptables-legacy
# update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
# update-alternatives --set arptables /usr/sbin/arptables-legacy
# update-alternatives --set ebtables /usr/sbin/ebtables-legacy
```

Based on docs in https://wiki.debian.org/nftables

I think this change would be justified because it would follow a principle of least surprise for users upgrading to a new patch version of hyperkube since presumably anyone who was using previous versions of hyperkube, like me, were also running it on a system using the default legacy iptables backend.

I am currently working on building a custom hyperkube from this branch to validate that the `iproute2` package install fixes my second problem since I solved the first by updating my VM image to debian 10 (but I can revert that if reviewers agree that it is surprising to change the default iptables backend targeted by hyperkube).

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
Please No. Please build your own image. we are trying to get rid of a whole bunch of things by moving to distroless and hyperkube is already gone from releases.

/close

**Comment by waynr** [comment]
@justaugustus @dims 

The hostile response to this PR kind of surprises me.

>  hyperkube is already gone from releases

This isn't true, at least for 1.6.11, 1.17.7, and 1.18.4 as evidenced by the fact that hyperkube containers exist for these versions:

* https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/hyperkube@sha256:53075c039804d03d5b9add68cc91d4d7f8045f48fa04b1a0b14a8393e1cc81ca/details?tab=info
* https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/hyperkube@sha256:a4ed392789f1f30cf6c826adea9358aa1e373720d03b51e8313ab0fb46d5dd1b/details?tab=info
* https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/hyperkube@sha256:a20cd9d592d660651350ed80b91c4054bc108fe6925b3b0e55c1a3bfadd17f3e/details?tab=info

Additionally, it looks like the hyperkube image is being actively maintained:

* https://github.com/kubernetes/kubernetes/pull/91476

^^ this appears to my somewhat untrained eye to be the change that broke my particular usage of hyperkube on debian 9 VMs.

Of course I'm not trying to deny that you intend to stop supporting hyperkube, only to point out that for the release branch this PR targets it still appears to be actively developed. I can also appreciate your intent to move toward a distroless distribution of binaries, as it seems like it may reduce the likelihood of exactly the kind of problem I am currently running into. (but I am curious how distroless will work when at least the kubelet binary appears to shell out to local binaries for some system tasks)

Still, it's surprising to encounter the issues described in #92272 and the response to this PR on a patch-level version where the release notes refer to hyperkube as if it is being actively maintained, rather than a minor-level release where it's easier to countenance that kind of backwards incompatibility.

**Comment by dims** [comment]
Apologies. i wasn't trying to be hostile (i used 2 "please" in the same sentence!)

- as to the existence of the hyperkube containers for previous release. they do because we don't go back and delete them. they are already released!
- 91476 is just a build change because we are trying to move some of the build infrastructure from google owned to community owned.
- ack on the rest of the observations.

**Comment by waynr** [comment]
> Apologies. i wasn't trying to be hostile (i used 2 "please" in the same sentence!)

Ha, sorry that was probably a poor choice of words on my part. Maybe I should have said "abrupt dismissal" instead of "hostile response" :)

> as to the existence of the hyperkube containers for previous release. they do because we don't go back and delete them. they are already released!

I wouldn't expect the existing releases to be deleted; my intent with this PR was to fix the bugs introduced in `v1.18.4` hyperkube that make it broken where `v1.18.3` was not broken (for more details of why i think v1.18.4 is broken, see #92272) with the hope that my changes would also be cherry-picked into `release-1.17` and `release-1.16` because I suspect that `v1.16.11` and `v1.17.7` are broken in a similar way given that they contain the same change and I saw the same test failure in my CI pipeline.

With a couple fixes to the hyperkube image on these branches I could wait for `v1.18.5`, `v1.17.8`, and `v1.16.12` and feel secure knowing that I could pull in any future critical bug or security fixes moving forward and save major rewrites of my team's build & deployment for 1.19.

> 91476 is just a build change because we are trying to move some of the build infrastructure from google owned to community owned.

The problem with this change from my point of view is that it implicitly the base image of hyperkube from debian 9 to debian 10. The consequences of this that I have uncovered so far:

* debian 10 includes a version of iptables that by default targets the `nf_tables` backend whereas debian 9's iptables by default targets the legacy (i believe i can address this fairly easily in my team's build system by bumping our base VM image, but there is also a way to fix this in the hyperkube image itself)

* it looks like the debian 9 hyperkube image also gets `iproute2` installed either by default or as a dependency of one of the explicitly installed packages whereas this doesn't happen on the debian 10 hyperkube.

Also, part of my confusion about your intent not to support hyperkube comes from the fact that the `release-1.18` branch still contains the build setup and there is even a hyperkube container image with a `v1.18.5-rc0` tag.

**Comment by dims** [comment]
/reopen

that's fair @waynr

**Comment by justaugustus** [comment]
@waynr -- Thanks for the thorough reports and apologies for any confusion.
hyperkube is deprecated from 1.19.0 onwards, but we will continue to support the image for 1.18, 1.17, and 1.16 releases.

I've opened https://github.com/kubernetes/kubernetes/pull/92354, which should supersede this PR.
/close

**Comment by waynr** [comment]
@justaugustus I have just confirmed with a custom build of the hyperkube image that this PR finishes addressing #92272 for me and I've rebased it onto `release-1.18` so it now also includes your fix from #92354

**Comment by justaugustus** [comment]
@waynr -- I've carried this PR over in https://github.com/kubernetes/kubernetes/pull/92581, given your responses (https://github.com/kubernetes/kubernetes/issues/92272#issuecomment-650201780, https://github.com/kubernetes/kubernetes/issues/92272#issuecomment-650204053).

(Branches that get rebased while the PR is closed makes the PR unusable.)

**Pull request closed without merging**
