### PR TITLE
Better documented exported functions and variables

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
/lgtm
/priority important-longterm

**Comment by humblec** [comment]
@neolit123 Thanks! can you please approve this PR please ?

**Comment by neolit123** [comment]
> @neolit123 Thanks! can you please approve this PR please ?

hello, this change has to be approved by the API maintainers.

**Comment by humblec** [comment]
I will wait for @thockin 's blessing :)

**Comment by humblec** [comment]
@liggitt one more to your queue :), thanks!

**Pull request merged**
