### PR TITLE
fluentd-elasticsearch - update fluentd to 1.3.3 & added filter_parser for json fields in es

### PR DESCRIPTION
**Pull request by monotek**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
/kind feature
> /kind flake

**What this PR does / why we need it**:
- updated fluentd to 1.3.3
- added filter_parser plugin to restore removed functionality of kubernetes_metadata (https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/145)
- updated all gems to newest version
- changed configmap to fit upcoming es 7.0.x

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # https://github.com/kubernetes/kubernetes/issues/69603

**Special notes for your reviewer**:
Please be aware that the 2.4.0 image has to be build and pushed to gcr.io to get the edited deamonset work.

**Does this PR introduce a user-facing change?**:

```release-note
Updates Fluentd to 1.3.2 & added filter_parser 
```

### CODE REVIEW

**Comment by monotek** [comment]
@coffeepac
Tests are looking good. 
Can you please build the 2.4.0 image and push it to gcr.io before the merge?

**Comment by desaintmartin** [comment]
What kind of json logging issues do you have?

**Comment by monotek** [comment]
I build the image, which is supposed to be 2.4.0, with the Fluentd 1.3.2 updates yesterday (https://cloud.docker.com/u/monotek/repository/docker/monotek/fluentd-elasticsearch) and used it with the fluentd-elasticsearch helm chart (with this version: https://github.com/helm/charts/pull/9382), adding the needed config changes.

What fails is that json logs, like the ones Kibana produces, are not split up in single Elasticsearch fields like before.

I need to check where the problem is because i was sure that this worked before with the state of the PR which used Fluentd 1.3.0 but i was not able to get it working yesterday. 

Therefore putting the pr on hold to not ship a broken version.

**Comment by monotek** [comment]
Replaced the fabric8 json parser plugin by Fluentds build in filter_parser plugin.

Works now :-)

/hold cancel

**Comment by monotek** [comment]
Could somebody trigger the 2.4.0 image build?
I'd like to update the helm chart to to use this version.

Can we move the image to somewhere else?
Maybe hub.docker.com or quay.io?
So we wouldn't need the manual build step by a google employee.
I'm also fine with any other kind of automatic build on gcr.io ;-)

**Comment by sn-x** [comment]
Any updates on when can we expect the image to be available?

**Comment by monotek** [comment]
updated fluentd to 1.3.3 using newest versions of all gems.

unfortunately i cant tell when the image is build.

if you like to try it out you can use: monotek/fluentd-elasticsearch:26 

source: https://cloud.docker.com/repository/docker/monotek/fluentd-elasticsearch/tags

**Comment by coffeepac** [comment]
I have pinged the relevant engineers at google.  Hopefully they can respond quickly.

**Comment by sn-x** [comment]
Looks like json parsing started working on a new index for default kibana logs. I guess I have issues with nested json in json logs from node bunyan library. I'll try to debug it and let you know what I have discovered.

**Comment by monotek** [comment]
@coffeepac

Oops. Seems we have merged without the image build? Should I add another pr with your new image repo url?

**Comment by coffeepac** [comment]
no, a googler has built this image so it should work just fine.

changing the repo will be done in a follow-up PR

**Comment by monotek** [comment]
Saw it some hours ago. Already updated the helm chart: https://github.com/kiwigrid/helm-charts/pull/17 😎

**Pull request merged**
