### PR TITLE
Don't run test that needs linux du command on OS X

### PR DESCRIPTION
**Pull request by erictune**

### CODE REVIEW

**Comment by thockin** [comment]
@pwittrock Can we make it so that any test that hist this path is safe on MacOS?

**Comment by pwittrock** [comment]
Yes the problem seems to be that Mac OS du doesn't recognize the -B command.  We can implement separately for Mac

**Comment by pwittrock** [comment]
Eric how would you like to proceed?  Should we just remove the GetMetrics lines until I have a fix so that the test continues to run on Mac OS

**Comment by pwittrock** [comment]
I was able to fix the du issue for darwin, but will run into statfs not running working.  May be this should only be covered in an e2e test?

**Comment by pwittrock** [comment]
Got a work around coming for this.  Will post when ready.

**Comment by erictune** [comment]
Sgtm

**Comment by pwittrock** [comment]
Working around is in PR #21364

**Comment by erictune** [comment]
@k8s-bot please e2e test flake #21463

**Comment by pwittrock** [comment]
@erictune I should have put you as a reviewer for PR #21364, but Saad reviewed (automatically assigned).  If you are ok with the changes in #21364, are we good to close this PR?

**Comment by erictune** [comment]
@pwittrock thanks.

**Pull request closed without merging**
