### PR TITLE
added etcd-version and coredns-version flag to kubeadm

### LINKED ISSUE #100512: Add flags to kubeadm for customizing  the image version of etcd and coreDNS
#### What would you like to be added:
Ref: #100174
Ref: #2411
Add flags to kubeadm for customizing  the image version of etcd and coreDNS
#### Why is this needed:
Sometimes users want to compile k8s components and build customized k8s component images, push them to the docker repository, and then install k8s with kubedm. At this time, they need to specify the tag of the customized k8s component. Now,    using --image-repository and  --kubernetes-version flags can customizes the respository and the version of Kubernetes components. But there isn't flags to customize the versions of etcd and coreDNS.

### PR DESCRIPTION
**Pull request by wangyysde**
#### What type of PR is this?
/kind feature

#### Which issue(s) this PR fixes:

Fix #100512

#### Does this PR introduce a user-facing change?
NONE

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by fabriziopandini** [comment]
@wangyysde I'm sorry but I'm -1 for this change for two reasons:
- We are avoiding changes to existing API version in kubeadm, even if non breaking/additions; in order to add new fields it is required to include this change in the next API version (you can refer the kubeadm repo for changes planned/under evaluation for the next release)
- We are carefully restricting the usage of flags in kubeadm for the most common use cases only

Currently, many Kubeadm users are addressing your use case by using the existing image meta field, but if this does not fit your use case we are happy to discuss it in the kubeadm office hours

**Comment by fabriziopandini** [comment]
/hold
@neolit123 please see my comment above

**Comment by wangyysde** [comment]
@fabriziopandini

> 
-  I know that we can specify the repository and version of k8s components by using --image-repository or --kubernetes-version flag. But I don't know how to specify the versions of coreDNS and etcd by using the existing image meta field.
-  Currently,as if the version of  the k8s components can be specified,but  the version of  the two external component image (coreDNS and Etcd) can not be specified. I don't know why  the k8s components' version can be specified while the two external component can not ?
- I think that the two flags can be added in the next milestone. But I am a beginner in the kubernetes community. Anyone can tell me what I must to do if I want to commit this issues with the PR to the next milestone? Thanks.

**Comment by fabriziopandini** [comment]
you can specify CoreDNS version by setting `dns.imageTag: vX.Y.Z` (eventually including also additional build metadata) in the `ClusterConfiguration`
Same for etcd using `etcd.local.imageTag: vX.Y.Z`

**Comment by neolit123** [comment]
@fabriziopandini already explained the problem here, so we cannot merge this change.
i've commented on the issue too.

**Comment by fabriziopandini** [comment]
/close
We can move the discussion on a new issue in the kubeadm repo if required.

**Pull request closed without merging**
