### PR TITLE
Create network with appropriate addresses

### PR DESCRIPTION
**Pull request by wojtek-t**
@zmerlynn - can you please ensure that we do something like that for GKE also?

### CODE REVIEW

**Comment by wojtek-t** [comment]
@thockin @roberthbailey - FYI

**Comment by gmarek** [comment]
@k8s-bot test this issue: #26628

**Comment by wojtek-t** [comment]
I'm temporarily adding do-not-merge label, to let others jump into it before it merges.

**Comment by roberthbailey** [comment]
This doesn't look right to me. The range that you give the network is the range that it will assign internal VM ip addresses from. That range should be completely separate from the range which we assign pod or service IP addresses. To illustrate:

Network range is 10.240.0.0/16
Cluster range is 10.244.0.0/14
Service range is 10.0.0.0/16

then

Node 1 gets ip 10.240.0.1
Node 2 gets ip 10.240.2.4
Pod 1 (on node 1 which has 10.244.1.0/24 assigned) gets ip 10.244.1.1
Pod 2 (on node 2 which has 10.244.2.0/24 assigned) gets ip 10.244.2.1
Service 1 gets ip 10.0.0.8
Service 2 gets ip 10.0.0.17

If you set the network range to 10.244.0.0/14 then the VM ips will conflict with the pod ips and packet routing won't work.

**Comment by wojtek-t** [comment]
@roberthbailey - thanks for the explanation

Closing.

**Pull request closed without merging**
