### PR TITLE
Remove usages of sets.Strings

### PR DESCRIPTION
**Pull request by MaGaroo**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
In this PR, usages of deprecated parts of utils/sets package are removed. More specifically, `sets.Set[string]` is used instead of `sets.String`

#### Which issue(s) this PR fixes:
Not any

#### Does this PR introduce a user-facing change?
No

### CODE REVIEW

**Comment by Vivekgaddigi** [comment]
what difference does this make?

**Comment by MaGaroo** [comment]
> what difference does this make?

`sets.String` is deprecated.

**Comment by pohly** [comment]
"Deprecated" can have different meanings ranging from "we will remove this API" to "please consider the new alternatives, but entirely up to you". `sets` falls into the latter, see https://kubernetes.slack.com/archives/CHGFYJVAN/p1693815116607339?thread_ts=1690902243.923879&cid=CHGFYJVAN

Please leave the code as it is. Maintainers may decide to replace it while changing it for other reasons, but doing it for its own sake is not worth the code churn.

Okay to close?

**Comment by MaGaroo** [comment]
Oh I see. Sure. I close it.

**Comment by MaGaroo** [comment]
Oh I see. Sure. I close it.

**Pull request closed without merging**
