### PR TITLE
Adding more e2e tests for federated namespace cascading deletion and fixing bugs

### PR DESCRIPTION
**Pull request by nikhiljindal**
Ref https://github.com/kubernetes/kubernetes/issues/33612

Adding more e2e tests for testing cascading deletion of federated namespace.
New tests are now verifying that cascading deletion happen when DeletionOptions.OrphanDependents=false and it does not happen when DeleteOptions.OrphanDependents=true.

Also updated deletion helper to always add OrphanFinalizer. generic registry will remove it if DeleteOptions.OrphanDependents=false. Also updated namespace registry to do the same.

We need to add the orphan finalizer to keep the orphan by default behavior. We assume that its dependents are going to be orphaned and hence add that finalizer. If user does not want the orphan behavior, he can do so using DeleteOptions and then the registry will remove that finalizer.

cc @kubernetes/sig-cluster-federation @caesarxuchao @derekwaynecarr

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36283)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Verified that new federated namespace tests pass

cc @k8s-bot federation gce e2e test this

**Comment by caesarxuchao** [comment]
Can you document fed controllers need to always add orphanFinalizer in the PR description?

**Comment by nikhiljindal** [comment]
Done

**Comment by caesarxuchao** [comment]
Why we need to always add orphanFinalizer for fed resources:
* main reason: we want all fed resources to by default to orphan. (k8s only default rs and rs to orphan)
* minor reason: namespace controller won't add orphanFinalizer even if DeleteOptions.Orphan=true, and we can't change namespace registry to add orphanFianlizer, because in k8s, no one is going to enforce orphan for namespace even if it has the finalizer.

We decided to change the name of the `DeletingUnderlyResources` finalizer, because having it and the OprhanFinalizer both set will be confusing to user.

**Comment by caesarxuchao** [comment]
LGTM. Let's discuss how to rename the `federation.kubernetes.io/delete-from-underlying-clusters` finalizer so that it's less confusing to co-exist with the orphanFinalizer.

**Comment by nikhiljindal** [comment]
@k8s-bot unit test this

**Comment by caesarxuchao** [comment]
> because in k8s, no one is going to enforce orphan for namespace even if it has the finalizer.

I can't recall why I said that. @nikhiljindal do you remember?

I'm reviewing https://github.com/kubernetes/kubernetes/pull/76051.

**Comment by zhouhaibing089** [comment]
> no one is going to enforce orphan for namespace even if it has the finalizer.

I think you probably mean: when you delete a namespace, even you say you want to orphan it, it will never happen. since the namespace_controller will always delete all the resources inside that namespace.

**Comment by zhouhaibing089** [comment]
@caesarxuchao: That probably makes sense. The `orphan` behavior does not fit for namespace. `deleteOptions.OrphanDependents` means nothing when deleting namespace.

**Comment by liggitt** [comment]
dependents strictly means "things which reference this object in their ownerReferences list". it does not mean "things contained within this namespace"

**Comment by zhouhaibing089** [comment]
@liggitt: Technically, can I put a namespace into the ownerReference list in:

1. Another namespace?
1. An object staying in another namespace?

**Comment by zhouhaibing089** [comment]
I guess I can, because garbage collector controller takes care of the finalizer on namespace, too..

**Comment by liggitt** [comment]
yes

**Comment by zhouhaibing089** [comment]
Well, then the semantics of `orphan` is the same for namespace, as well.

**Pull request merged**
