### PR TITLE
Backport of #106539: Replace url label in rest client latency metrics by host and path

### PR DESCRIPTION
**Pull request by dgrisonnet**
This commit is a cherry pick of a188f5bf7e2b1fc6b7be9e1386f0506d3033e2a8
without the API changes.

Since the issue that this commit is fixing can have severe security
impacts on the monitoring stack, the fix needs to be backported.
However, we don't want to break the existing APIs while porting the fix
so while cherry-picking the change, only the patch was kept.

The `rest_client_request_duration_seconds` and
`rest_client_rate_limiter_duration_seconds` metrics have a url label
that used to contain the whole uri of the request. This is very
dangerous and can lead to cardinality explosions since its values aren't
bounded. We don't really need to expose the whole uri since these
metrics are used to mesure the availability of the different proxy in
front the apiserver. The most valuable information is the host to be
able to differentiate between the different proxy. In the future, we
might also want to add the path to be able to add some granularity, but
since there is no immediate use case for that, so there is no need to
add it now.

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

This PR is a backport of a cardinality explosion fix.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

As explained above, this is a partial cherry-pick that brings only the patch to the issue without the API breaking changes.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/assign @logicalhan 
/cc @mitchellmaler

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by FernFerret** [comment]
Hi all, I think this was omitted from the release notes, or I somehow misread them. There are 3 cherry picks, only posting on this one since this is the only release that it hit me on.

I realize it's not super critical but I thought I broke all the metrics in my lab cluster and spent the afternoon getting here (admittedly I had no idea what I was looking for, which is why it took so long). It's a pretty small change and something that's reasonably generic, so it was hard to look for.

Not sure if there's any way to amend the release notes but just posting here so others who find this don't fret when they see metrics change.

**Comment by dgrisonnet** [comment]
Hi @FernFerret, sorry for the bad experience. I intendedly didn't add a release note for these backports because they are fairly small fixes that shouldn't have any impact on the users. That said since you ran into an issue because of that maybe it should have been documented inside of the release notes. Could you perhaps share how you noticed this change so that I can better understand how we could improve on that in the future?

**Comment by FernFerret** [comment]
Hi @dgrisonnet no worries at all! I had a lot of fun finding out what happened.

The main thing I noticed was that (admittedly several hours after) I upgraded my lab I saw this in one of my grafana plots:

image

When I saw this I thought maybe I broke something with the metrics, maybe a new `relabel` config got deployed, or my proxy was stripping urls. The only reason I thought this was I'd read the release notes and didn't see anything that should be touching the scheduler metrics.

The query for this plot is effectively (with the legend value of `{{verb}} {{url}}`):

```
histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job="kube-controller-manager", verb="POST"}[5m])) by (verb, url, le))
```

This is just one of the [stock plots](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14/controller-manager.yaml) that comes with the Grafana. I'm trying to learn how to monitor the control plane better in my lab so I can tune my larger instances.

I assume this won't affect most people, it just hit me by a strange coincidence because I was interested in learning about the metrics and just decided to do a routine upgrade.

Its likely there's nothing wrong here, I was just surprised. As I noted earlier I'm trying to learn how these subsystems work, so maybe an experienced user would have said "those metrics weren't useful, I'm so glad the authors fixed them!"

I thought I was responsible for this because I made 3 changes in rapid succession:

* Switched from binding `0.0.0.0` to using a variant of this [haproxy daemonset](https://github.com/prometheus-community/helm-charts/issues/1704#issuecomment-1100607982).
* Upgraded from `1.23.5 to 1.23.7`
* Upgraded `kube-prom-stack` (I thought this when I was investigating, but this happened hours earlier)

Luckily I had system logs in my monitoring stack and was able to determine that my kubernetes upgrade caused this intentionally. I was posting my journey in the [#kubernetes-sigs](https://kubernetes.slack.com/archives/C20HH14P7/p1653852778207909) slack.

Thanks again for your response and all the hard work!

**Pull request merged**
