### PR TITLE
update wrong group for priorityclasses

### LINKED ISSUE #54690: priority admission controller can not verify priorityclass
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug

**What happened**:

When I use priorityclass, I create two global default priorityclass and there is nothing wrong

**What you expected to happen**:
priority admission controller should prevent it.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #54690

**Special notes for your reviewer**:

assgin @bsalamat 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by k82cn** [comment]
I think we need to update AdmissionController if necessary instead of api group.

**Comment by wackxu** [comment]
@k82cn Sorry, can you describe in detail? Do you mean we should separate the Priority AdmissionController or something else?

**Comment by wackxu** [comment]
@bsalamat need change? Any suggestion?

**Comment by bsalamat** [comment]
@wackxu Your change looks good to me, but please fix similar problem in `plugin/pkg/admission/priority/admission_test.go` as well.

@k82cn Could you please elaborate what you mean by "update AdmissionController if necessary instead of api group"?

**Comment by wackxu** [comment]
@bsalamat addressed

**Comment by k82cn** [comment]
> @k82cn Could you please elaborate on "update AdmissionController if necessary instead of api group"?

Never mind, mis-understand; the `PriorityClass` should be in scheduling group as you suggested.

**Comment by bsalamat** [comment]
@deads2k Could you please approve this?

**Pull request merged**
