### PR TITLE
Automated cherry pick of #71145: Fix bug with volume getting marked as not in-use with pending #71429: Fix flake with e2e test that checks detach while mount in

### PR DESCRIPTION
**Pull request by gnufied**
Cherry pick of #71145 #71429 on release-1.11.

#71145: Fix bug with volume getting marked as not in-use with pending
#71429: Fix flake with e2e test that checks detach while mount in

/sig storage
/kind bug

```release-note
Do not detach volumes while mount is in progress
```

### CODE REVIEW

**Comment by foxish** [comment]
Needs LGTM+Approval from owners.

**Comment by gnufied** [comment]
/assign @saad-ali 

can you approve?

**Pull request merged**
