### PR TITLE
Automated cherry pick of #24208

### PR DESCRIPTION
**Pull request by ncdc**
Cherry pick of #24208 on release-1.2.

### CODE REVIEW

**Comment by ncdc** [comment]
@wojtek-t @liggitt

**Comment by liggitt** [comment]
LGTM, needs cherry pick approval

**Comment by thockin** [comment]
I thought we are not doing cherry-picks this way any more?

@david-mcmahon

**Comment by david-mcmahon** [comment]
This one errantly got the `release-note-label-needed` label too.  Removed.  Adding Robby to `cherrypick-approved` the original PR.
cc @eparis

**Comment by thockin** [comment]
Sorry, David schooled me, I was misinterpreting the rules.  Sorry to close
your PR, Jan :)

**Comment by eparis** [comment]
Parent has "release-note-none" so this PR must follow the PR process.

**Comment by ncdc** [comment]
Updated parent PR to "release-note"

**Comment by david-mcmahon** [comment]
Ah yes, @eparis, that makes sense, but it is confusing that the cherrypick PR that shouldn't have release-note-* label management gets release-note-label-needed when the parent PR doesn't have a valid release-note- label (which is required for cherrypicks to a branch).  I don't immediately see a better way to handle this unless we can detect that the parent has been cherrypicked and that release-note-none is invalid and then update the parent PR with release-note-label-needed.

**Comment by eparis** [comment]
I think the best I can do is to comment in the cherrypick-pr why it is getting the 'cp-label-needed' label.

**Comment by eparis** [comment]
(and then a human needs to solve the situation)

**Comment by david-mcmahon** [comment]
@eparis that works too.  Something to tie the two together.  Thank you for continuing to adjust on this.

**Comment by roberthbailey** [comment]
Let's see if the bot will merge this w/o a release note label or if it complains...

**Comment by eparis** [comment]
we can really test the bot, and remove cp-approved.  see if it automatically gets applied from the parent...

**Comment by eparis** [comment]
I'll keep and eye on this pr. I'm hoping the automation system is going to automatically apply cp-approved, the milestone, and will get it into the merge queue.

**Comment by roberthbailey** [comment]
@eparis sgtm.

**Comment by eparis** [comment]
The bot works!!!

**Pull request merged**
