### PR TITLE
Removing comment to improve generated docs.

### LINKED ISSUE #101309: Misnamed feature gate in API server help
#### What happened:
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#list-deployment-v1-apps (which is generated automatically) mentions a feature gate named `WatchBookmarks`. This is not the correct name; that feature gate is / was `WatchBookmark`. Also, the feature has graduated.

So what happened was I saw an incorrect feature gate name.

#### What you expected to happen:
The generated docs don't mention `WatchBookmark` _or_ `WatchBookmarks` 

ie, I think the fix is to remove
```go
	// If the feature gate WatchBookmarks is not enabled in apiserver,
	// this field is ignored.
```

#### How to reproduce it (as minimally and precisely as possible):
- generate the documentation
- read the documentation

or, short cut, go and look at https://github.com/kubernetes/apimachinery/blob/8daf28983e6ecf28bd8271925ee135c1179ad13a/pkg/apis/meta/v1/types.go#L360

#### Environment:
- Kubernetes version (use `kubectl version`): v1.21
- Cloud provider or hardware configuration: n/a
- OS (e.g: `cat /etc/os-release`): n/a
- Kernel (e.g. `uname -a`): n/a
- Install tools: n/a
- Network plugin and version (if this is a network-related bug):
- Others: 

/kind bug
/sig api-machinery
/priority backlog
(IMO)

### PR DESCRIPTION
**Pull request by amanchourasiya**
Removed unnecessary comment so that the generated docs don't mention WatchBookmark or WatchBookmarks.

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR removes an unnecessary comment that was generating docs that mention WatchBookmark or WatchBookmarks.

#### Which issue(s) this PR fixes:

Fixes #101309 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by amanchourasiya** [comment]
I signed it

**Comment by sftim** [comment]
LGTM
/retest

**Comment by sftim** [comment]
@amanchourasiya you will also need to [generate](https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream/#generating-the-openapi-spec-and-related-files) some extra files, in a second commit. 

See https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#generate-code for more details, or for a simple life try running `make update`. I think you can also run the update in a container that mounts your source tree, but I'm not sure if that is clearly documented.

**Comment by liggitt** [comment]
change looks good, some of the generated docs/files need updating, see the failed checks in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101320/pull-kubernetes-verify/1386247843907375104

**Comment by amanchourasiya** [comment]
Updated the PR with updated generated files

**Comment by amanchourasiya** [comment]
I ran 'make' and some autogenerated files were updated and I added them to this PR. But still, one test is failing.
I am building inside a container and 'make update' doesn't seem to work. @sftim is there any other way I can generate the file that is causing this [test](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101320/pull-kubernetes-verify/1387264278305705984)  to fail in my container development environment?

**Comment by liggitt** [comment]
you can try running those specific generators individually:

```
hack/update-generated-swagger-docs.sh 
hack/update-generated-protobuf.sh 
```

**Comment by amanchourasiya** [comment]
Hi, @liggitt  I am able to run this command 'hack/update-generated-swagger-docs.sh' and it's giving me an update on one autogenerated file but this 'https://github.com/amanchourasiya/kubernetes.git' again requires docker.

**Comment by liggitt** [comment]
this is the expected diff for the proto files that the verify job is failing on:

```diff
diff --git a/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto b/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto
index f1cb025a317..7d450644d2a 100644
--- a/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto
+++ b/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto
@@ -499,8 +499,6 @@ message ListOptions {
   // assume bookmarks are returned at any specific interval, nor may they
   // assume the server will send any BOOKMARK event during a session.
   // If this is not a watch, this field is ignored.
-  // If the feature gate WatchBookmarks is not enabled in apiserver,
-  // this field is ignored.
   // +optional
   optional bool allowWatchBookmarks = 9;
 
```

you can apply that manually and squash your commits, then this should be ready

**Pull request merged**
