### PR TITLE
Update vendor prometheus/common/... to latest release

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/kind flake
/sig instrumentation

**What this PR does / why we need it**:

update the vendor `github.com/prometheus/common/...` to latest release for better performance.
ref: https://github.com/kubernetes/kubernetes/pull/70926

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mxinden — COMMENTED** [review]
Given that this is probably mostly used through https://github.com/prometheus/client_golang, we should how about treating it as a transient dependency of https://github.com/prometheus/client_golang? Given that client_golang introduced go modules, we could pin a specific version of prometheus/common.

What do you think @danielqsj?

**Comment by danielqsj** [comment]
@mxinden agree. 
After this PR merged, 
the version of `github.com/prometheus/client_golang` is pinned as `v0.9.1`,
the dependency `github.com/prometheus/common` is pinned as `v0.2.0`. 
Does it look good ?

**Comment by mxinden** [comment]
@danielqsj is there a particular reason why not to go with prometheus/client_golang v0.9.2, given that there are no 'CHANGE' sections in the changelog for the version?

**Comment by danielqsj** [comment]
@mxinden Agree about bump prometheus/client_golang into v0.9.2. Will update it soon.

**Comment by danielqsj** [comment]
@mxinden updated, PTAL

**Comment by danielqsj** [comment]
ping @apelisse

**Review by mxinden — APPROVED** [review]
Thanks for the changes @danielqsj.

**Comment by apelisse** [comment]
Approving Godeps update to `prometheus/client_go` v0.9.2 and `prometheus/common` v0.2.0. No red-flag.

/approve

**Pull request merged**
