### PR TITLE
Switch to versioned ListOptions in server.

### PR DESCRIPTION
**Pull request by wojtek-t**
Part 2 of #18645

### CODE REVIEW

**Comment by wojtek-t** [comment]
@smarterclayton - the PR is almost ready.

The remaining issue is this test failing:
https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master_test.go#L471

The issue is that ListOptions is not registered for the "company.com" API group, which I'm not sure how to solve properly (obviously we can register it in the test, but that doesn't solve the main problem here).
@smarterclayton - any suggestions?

**Comment by smarterclayton** [comment]
Let me try the test out from your branch - I *think* we want to allow this in conversion (third party is a bit of a hack anyway).

**Comment by smarterclayton** [comment]
The assumption in resthandler (today) is that ListOptions exists in the group version, but third party doesn't provide a scope.Creater that is aware of ListOptions.  master.go#1012 creates a thirdpartyresourcedata.NewObjectCreater - I think that method should create the appropriate delegate type (extensions/v1beta1#ListOptions), and conversion should work correctly at that point.

**Comment by wojtek-t** [comment]
>
The assumption in resthandler (today) is that ListOptions exists in the group version, but third party doesn't provide a scope.Creater that is aware of ListOptions. master.go#1012 creates a thirdpartyresourcedata.NewObjectCreater - I think that method should create the appropriate delegate type (extensions/v1beta1#ListOptions), and conversion should work correctly at that point.

hmm - I'm not sure I understood.
We are already passing "api.Scheme" as delegate to NewObjectCreater:
https://github.com/kubernetes/kubernetes/blob/master/pkg/master/master.go#L1012
which should be aware of extensions/v1beta1#ListOptions and v1#ListOptions

I think that issue here is that we are passing "company.com#ListOptions" to "delegate" which api.Scheme cannot create an object for.

So maybe the correct fix is to add another case for ListOptions:
https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/thirdpartyresourcedata/codec.go#L294
matching ListOptions and change the group/version to extensions/v1beta1 or v1.

@smarterclayton WDYT?

**Comment by smarterclayton** [comment]
Yes I think so - roughly what I was trying to convey (translate 3rd party
group into external group).

**Comment by wojtek-t** [comment]
OK - thanks (I guess I didn't understand what you were suggesting).
I will fix it tomorrow.

**Comment by wojtek-t** [comment]
@smarterclayton - it's now ready to go

PTAL

**Comment by smarterclayton** [comment]
LGTM thanks

**Comment by wojtek-t** [comment]
Simple rebase - reapplying lgtm label

**Comment by wojtek-t** [comment]
Unit test failure is: https://github.com/kubernetes/kubernetes/issues/18713

@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
Trivial rebase - reapplying lgtm label

**Comment by wojtek-t** [comment]
One more trivial rebase

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
I'm still getting the following error:

    git checkout -f cd3115aa5fb61c9c45658bb852d4dbe1c23d53be
    FATAL: Could not checkout cd3115aa5fb61c9c45658bb852d4dbe1c23d53be
    hudson.plugins.git.GitException: Could not checkout cd3115aa5fb61c9c45658bb852d4dbe1c23d53be

I've seen it in other PRs too - I opened https://github.com/kubernetes/kubernetes/issues/18960 for it

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
Tests just passed - merging manually to unblock further cleanup.

**Pull request merged**
