### PR TITLE
Use K8s in the README

### LINKED ISSUE #7: Small request for kubernetes.io
For https://kubernetes.io:

change "Kubernetes (K8s) is an open-source system..." to "Kubernetes, also called K8s, is an open-source system..."
incorporate "K8s" into one or more of the other headers on that page, e.g. "Run Anywhere" => "Run K8s Anywhere"
For https://github.com/kubernetes/kubernetes:

add "K8s" as a separate item next to or near the logo
or alternatively, change the headers for "To start using Kubernetes" => "To start using K8s", and same for "To start developing Kubernetes" => "To start developing K8s"

### PR DESCRIPTION
**Pull request by celestehorgan**
Signed-off-by: Celeste Horgan <celeste@cncf.io>

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

This PR closes https://github.com/cncf/techdocs/issues/7 on request from @caniszczyk. Using K8s in the repository's README helps the CNCF trademark the phrase "K8s" :) 

**Which issue(s) this PR fixes**:

Fixes https://github.com/cncf/techdocs/issues/7

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
The existing README already linked to k8s.io URLs, too.

**Comment by nikhita** [comment]
Looks like this is ready to be merged? :eyes:

**Pull request merged**
