### PR TITLE
Move Ceph server secret creation to common code.

### PR DESCRIPTION
**Pull request by jsafrane**
The secret should be created only on one place.

**Release note**:

```release-note
NONE
```

@jeffvance @copejon @rootfs @msau42 PTAL

### CODE REVIEW

**Comment by jeffvance** [comment]
Makes sense.
/lgtm

**Comment by jsafrane** [comment]
Fixed gofmt, @jeffvance please re-lgtm.

/assign @soltysh @eparis 
for approval

**Pull request merged**
