### PR TITLE
WIP: Revert staging changes in #35583

### PR DESCRIPTION
**Pull request by justinsb**
I should not have made changes to the staging/ area; sorry!

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36405)

### CODE REVIEW

**Comment by justinsb** [comment]
cc @caesarxuchao

**Comment by caesarxuchao** [comment]
Thank you @justinsb! LGTM.

**Comment by justinsb** [comment]
(marking WIP while I figure out what's going on; it looks like staging depends on the root vendor directory)

**Comment by justinsb** [comment]
Trying again by directly reverting the two commits and then reapplying the "new package" commit, but not trying to reapply the removal from root Godeps.

**Comment by caesarxuchao** [comment]
Last failure: 
```
FAILED   hack/make-rules/../../hack/verify-bazel.sh	23s
```

**Comment by caesarxuchao** [comment]
Hey @justinsb, #36465 ran the hack/update-staging-client-go.sh (mwielgus needed to populate the latest clientset changes to client-go), which fixed the dependency on k8s.io/kubernetes: https://github.com/mwielgus/kubernetes/blob/a927dddb43fbb7afac70abbc3419bb21c57635ec/staging/src/k8s.io/client-go/pkg/util/flowcontrol/throttle.go#L22. Can we close this PR? Sorry for the troubles.

**Comment by dims** [comment]
@justinsb : per @caesarxuchao we can close this PR. am looking at all the PR(s) marked v1.5 and noticed this. please switch milestones at least if this is not appropriate for v1.5 release.

**Comment by caesarxuchao** [comment]
#36465 merged. Closing this one.

**Pull request closed without merging**
