### PR TITLE
Remove the "www" and "third-party ui" directories from kubernetes repo

### PR DESCRIPTION
**Pull request by ohohoreilly**
This PR is a fix for issue https://github.com/kubernetes/kubernetes/issues/12666

@brendandburns can you please take a look?

### CODE REVIEW

**Comment by brendandburns** [comment]
LGTM.

**Comment by brendandburns** [comment]
Looks like you need to run `hack/update-generated-docs.sh`

**Comment by preillyme** [comment]
@brendandburns done and I've updated this PR. I was missing the
 ```[Analytics]()``` section.

**Comment by mikedanese** [comment]
#12657

**Comment by preillyme** [comment]
@mikedanese I didn't see your PR https://github.com/kubernetes/kubernetes/pull/12657

Would you like to close yours or mine?

**Comment by mikedanese** [comment]
I prefer #12657 as of now. It removes kube-ui entirely. We should remove the addon source since it now lives in the upstream repo, and we need to also remove go-bindata generation of kube-ui from here

https://github.com/kubernetes/kubernetes/blob/master/hack/build-ui.sh

**Comment by mikedanese** [comment]
If there is anything I'm missing feel free to take over, but I did a pretty exhaustive search list night

**Comment by mikedanese** [comment]
LGTM. Thanks.

**Pull request merged**
