### PR TITLE
use return fast and ignore an else block to improve code in kubelet

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

**What this PR does / why we need it**:
This PR uses return fast and ignore an else block for code. And I think this will make code more clean and more readable. This ignoring else block will make the main code stream keep in the same block.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
NONE

**Special notes for your reviewer**:
NONE

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by m1093782566** [comment]
+1

**Comment by allencloud** [comment]
@thockin 
I am afraid we have a typo in `/approve no issue`. Maybe it should be `/approve no-issue`

**Comment by allencloud** [comment]
ping @thockin

**Comment by dchen1107** [comment]
/lgtm
/approve no-issue

@allencloud Thanks for cleanup. Can you please rebase it?

**Comment by allencloud** [comment]
@dchen1107 
Thanks for your feedback and approval.
Actually I found in the previous these codes have been removed. So it happens to be conflict.
Therefore, I am afraid I have to close this PR. Thanks again.

**Comment by m1093782566** [comment]
:+1:

**Pull request closed without merging**
