### PR TITLE
Update log-dump script in release-1.5

### PR DESCRIPTION
**Pull request by shyamjvs**
As discussed offline - to fix failing log-dump on 1.5 jobs.
I've pretty much replaced the script with the one we have at head, but with logexporter-related code removed.

cc @mwielgus @abgworrall

### CODE REVIEW

**Comment by abgworrall** [comment]
Looks like the test failures might actually be failures, not flakes :O

**Comment by shyamjvs** [comment]
Fixed the pull-kubernetes-verify presubmit. The kops-aws failure seems unrelated (it didn't even reach the cluster startup step).

**Comment by shyamjvs** [comment]
@justinsb @kubernetes/test-infra-maintainers Kops seems to fail due to some bizarre reason. Could you PTAL?

**Comment by krzyzacy** [comment]
hummm - looks like if we want to support 1.5 - we need to add [hack/print-workspace-status.sh](https://github.com/kubernetes/kubernetes/blob/release-1.6/hack/print-workspace-status.sh) back to 1.5

**Comment by zmerlynn** [comment]
I didn't think the kops PR builder was supposed to even be running on `release-1.5`, looking.

**Comment by zmerlynn** [comment]
Ah, nevermind. The break is at `-1.4`.

**Comment by krzyzacy** [comment]
@zmerlynn oh - I think that's before it hit kops-aws-runner... we probably want to just skip the suite? Will that affect the required context?

**Comment by zmerlynn** [comment]
I'm ok merging this without the kops presubmit. We can watch the post-submit kops job.

**Comment by justinsb** [comment]
Happy to manually review any 1.5 changes for AWS impact if needed - this one should not impact AWS end users

**Pull request merged**
