### PR TITLE
Add gke-ci and gke-ci-reboot to source control

### PR DESCRIPTION
**Pull request by spxtr**
This is hopefully the last change to make to e2e.sh, so once this is in and tested I can make the changes to release-1.0 and release-1.1 branches and add the rest of the e2e tests.
#18122

### CODE REVIEW

**Comment by ixdy** [comment]
LGTM

**Comment by spxtr** [comment]
Thanks, I'll merge tomorrow morning.

**Comment by spxtr** [comment]
@k8s-bot e2e test this again please

**Comment by spxtr** [comment]
@k8s-bot test this again please

**Comment by spxtr** [comment]
```
Summarizing 1 Failure:

[Fail] Services [It] should prevent NodePort collisions 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:644
```
Flake?

**Comment by spxtr** [comment]
@k8s-bot test this

**Comment by spxtr** [comment]
Manually merging to watch Jenkins.

**Pull request merged**
