### PR TITLE
Consistently print errors to stderr and add newlines to cordon

### PR DESCRIPTION
**Pull request by smarterclayton**
```release-note
NONE
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
@kubernetes/sig-cli-bugs

**Comment by smarterclayton** [comment]
Wow, the drain test cases are a bit of a horror show of internal types and using the wrong codecs.  Going to have to fix that.

**Comment by smarterclayton** [comment]
I unfortunately had to work around the scheme problem, it was more involved than I expected.

@juanvallejo looks like the drain tests were broken when we switched to external types, but no one noticed because we never printed the error output.  We need to fix drain to work with an external scheme that doesn't use legacy, but it's more involved.  Can you make sure there is a sig-cli work item to cover this test?  I can file an issue.

**Comment by smarterclayton** [comment]
bazel i hate you

**Comment by dims** [comment]
LOL, this time it's not bazel's fault :) need to update drain_test.go i think

**Comment by smarterclayton** [comment]
It was Bazel's fault, the way we build inside bazel is slightly different than the way outside, which causes different error messages to show up

**Comment by dims** [comment]
aha! thanks @smarterclayton

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
