### PR TITLE
[release-1.24] releng/go: Bump images, versions and deps to use Go 1.20.7 and newer protoc

### PR DESCRIPTION
**Pull request by jeremyrickard**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

- Bump images, versions and deps to use Go 1.20.7

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/release/issues/3181

#### Does this PR introduce a user-facing change?
```release-note
Kubernetes is now built with Go 1.20.7
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

/assign @saschagrunert @cpanato 
cc @kubernetes/release-engineering

### CODE REVIEW

**Comment by liggitt** [comment]
1.24 is done, right? (this PR isn't to merge)

**Comment by liggitt** [comment]
/retest

the vet error is weird… nothing in vet changed between 1.20.6 and 1.20.7

**Comment by liggitt** [comment]
Might need to pick https://github.com/kubernetes/kubernetes/pull/111846 but I have no idea why CI chose *now* to complain about this on release-1.24

**Comment by jeremyrickard** [comment]
> Might need to pick #111846 but I have no idea why CI chose _now_ to complain about this on release-1.24

OK, to test this out I cherry picked that into this PR. If it's successful I can remove it and do a separate cherry pick PR and rebase on the branch after that goes in.

**Pull request merged**
