### PR TITLE
WIP: Test CRI-O prow jobs

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

Nothing to see here.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by saschagrunert** [comment]
The SSH key injection fails, we have to merge those PRs to get it working again:

- https://github.com/kubernetes/kubernetes/pull/115657
- https://github.com/kubernetes/test-infra/pull/28706

**Comment by saschagrunert** [comment]
The job `pull-kubernetes-node-kubelet-serial-crio-cgroupv1` seems to fail since ever, we have to investigate this after the test-infra job generation migration.

**Comment by haircommander** [comment]
new serial failure dropped:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/115654/pull-kubernetes-node-kubelet-serial-crio-cgroupv1/1624135660317184000/
at least it's not on provisioning :)

**Comment by pacoxu** [comment]
> /test pull-kubernetes-node-swap-fedora-serial /test pull-kubernetes-node-swap-fedora /test pull-kubernetes-node-memoryqos-cgrpv2

These tests are fixed. I opened https://github.com/kubernetes/kubernetes/issues/115372 for it.

**Pull request closed without merging**
