### PR TITLE
Cherry pick stabilizing HPA e2e tests to 1.12

### PR DESCRIPTION
**Pull request by jbartosik**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
/kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: HPA e2e tests are failing in 1.12. I fixed them on HEAD but they're failing in 1.12.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by jbartosik** [comment]
Issue #70655

**Comment by liggitt** [comment]
which PR is this a cherry pick of? was there a reason the official cherry pick script was not used? (`hack/cherry_pick_pull.sh upstream/release-1.12 <original-pr>`)

**Comment by AishSundar** [comment]
@feiskyer  1.12 patch manager for CP request. This CP into 1.11 is critical to get a clean CI Signal for 1.13

**Comment by jbartosik** [comment]
@liggitt this is squash of [1](https://github.com/kubernetes/kubernetes/pull/70125), [2](https://github.com/kubernetes/kubernetes/pull/70233), [3](https://github.com/kubernetes/kubernetes/pull/70441), [4](https://github.com/kubernetes/kubernetes/pull/70579), and [5](https://github.com/kubernetes/kubernetes/pull/70649). It took me a few attempts to get this.

**Comment by jbartosik** [comment]
+ changes to boiler plate because boilerplate check was failing.

**Comment by liggitt** [comment]
> @liggitt this is squash of [1](https://github.com/kubernetes/kubernetes/pull/70125), [2](https://github.com/kubernetes/kubernetes/pull/70233), [3](https://github.com/kubernetes/kubernetes/pull/70441), [4](https://github.com/kubernetes/kubernetes/pull/70579), and [5](https://github.com/kubernetes/kubernetes/pull/70649). It took me a few attempts to get this.

ok. please preserve the source commits when possible so we can verify the picked change corresponds to changes made/tested in master

**Comment by jbartosik** [comment]
> > @liggitt this is squash of [1](https://github.com/kubernetes/kubernetes/pull/70125), [2](https://github.com/kubernetes/kubernetes/pull/70233), [3](https://github.com/kubernetes/kubernetes/pull/70441), [4](https://github.com/kubernetes/kubernetes/pull/70579), and [5](https://github.com/kubernetes/kubernetes/pull/70649). It took me a few attempts to get this.
> 
> ok. please preserve the source commits when possible so we can verify the picked change corresponds to changes made/tested in master

Ack. Is this PR ok the way it is or should I resend it unsquashed?

**Comment by liggitt** [comment]
> Ack. Is this PR ok the way it is or should I resend it unsquashed?

did a manual review for this one

/approve

**Pull request merged**
