### PR TITLE
Fix typo test/cmd/README

### PR DESCRIPTION
**Pull request by raresraf**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Fixes typo in `test/cmd/README`

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
Typo in `Adding Tests` section from `test/cmd/README`

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by raresraf** [comment]
I signed it

**Review by oomichi — COMMENTED** [review]
/approve

**Pull request merged**
