### PR TITLE
WIP: testing only Change default runtime used in test back to docker

### PR DESCRIPTION
**Pull request by msau42**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
Suspecting that the switch to containerd caused a performance regression

**Which issue(s) this PR fixes**:

Fixes #
Addresses #92045
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by msau42** [comment]
cc @dims 
Using this to test if the slow job no longer times out

**Comment by msau42** [comment]
https://prow.k8s.io/log?id=1271200321766428672&job=pull-kubernetes-e2e-gce-storage-slow
Ran 267 of 5104 Specs in 792.648 seconds

Tests completed in 13 mins which is back to what it was before.

**Comment by dims** [comment]
let's please fix the specific jobs if they really need docker, guidance is in this email:
https://groups.google.com/forum/#!msg/kubernetes-sig-testing/Lrh-00O5Gu4/C_-AaYEMAgAJ

**Comment by msau42** [comment]
Jobs are being switched in https://github.com/kubernetes/test-infra/pull/17924

And opened https://github.com/kubernetes/kubernetes/issues/92057 to track the performance regression.

/close

**Comment by msau42** [comment]
/reopen
to test if this is the cause of windows timeouts

**Pull request closed without merging**
