### PR TITLE
Fix issue that kubelet may use stale node info to predicate pods

### LINKED ISSUE #85334: kubelet may use stale node info to predicate pods
**What happened**:
kubelet may use stale node info to predicate pods

**What you expected to happen**:
pod should not be rejected

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
If new labels are labeled in a node, and pods use nodeSelector,
kubelet may reject the pods at kubelet restarting because node
cache is not populated and kubelet still uses stale node info
which has no new labels.

This is the error from reflector of node ListWatch in a goroutine, triggered at https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L457:
```
Nov 05 12:44:34 kubelet[14390]: E1105 12:44:34.893917 14390 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:452: Failed to list *v1.Node: Stream error http2.StreamError{StreamID:0x9, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection. Please retry.
```
This is the error when predicating pods, it called here https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_getters.go#L240, and if node cache is not ready, it calls initialNode instead, which has no latest node info:
```
Nov 05 12:44:34 kubelet[14390]: I1105 12:44:34.919779 14390 predicate.go:133] Predicate failed on Pod: xxx(a1bfbee0-5d58-11e9-adbb-ac1f6b0b668c), for reason: Predicate MatchNodeSelector failed
```
There is race condition between them.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CentOS Linux 7
- Kernel (e.g. `uname -a`): 4.15
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by keyingliu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
If new labels are labeled in a node, and pods use nodeSelector,
kubelet may reject the pods at kubelet restarting because node
cache is not populated and kubelet still uses stale node info
which has no new labels.

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/85334
```
Nov 05 12:44:34 kubelet[14390]: E1105 12:44:34.893917 14390 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:452: Failed to list *v1.Node: Stream error http2.StreamError{StreamID:0x9, Code:0x2, Cause:error(nil)} when reading response body, may be caused by closed connection. Please retry.
Nov 05 12:44:34 kubelet[14390]: I1105 12:44:34.919779 14390 predicate.go:133] Predicate failed on Pod: xxx(a1bfbee0-5d58-11e9-adbb-ac1f6b0b668c), for reason: Predicate MatchNodeSelector failed
Nov 05 12:44:34 kubelet[14390]: E1105 12:44:34.923945 14390 kubelet.go:2245] node "xxx" not found
```

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by keyingliu** [comment]
@danielqsj  I filed this PR again as we were seeing this issue frequently recently. PTAL

**Comment by keyingliu** [comment]
The change blocks kubelet from running for master nodes... and static pods cannot be launched.

**Comment by keyingliu** [comment]
PR updated: try to get node from apiserver directly if node is not in cache.

**Comment by ehashman** [comment]
@keyingliu Can you please update your PR description to indicate this fixes #85334?

**Comment by keyingliu** [comment]
@ehashman updated

**Comment by keyingliu** [comment]
I also have another thought: for kubelet predicates, the node info must be up to date, the PR can be:
```
diff --git a/pkg/kubelet/kubelet.go b/pkg/kubelet/kubelet.go
index 90953e74fa9..226ff67d161 100644
--- a/pkg/kubelet/kubelet.go
+++ b/pkg/kubelet/kubelet.go
@@ -772,7 +772,7 @@ func NewMainKubelet(kubeCfg *kubeletconfiginternal.KubeletConfiguration,
        klet.admitHandlers.AddPodAdmitHandler(klet.containerManager.GetAllocateResourcesPodAdmitHandler())

        criticalPodAdmissionHandler := preemption.NewCriticalPodAdmissionHandler(klet.GetActivePods, killPodNow(klet.podWorkers, kubeDeps.Recorder), kubeDeps.Recorder)
-       klet.admitHandlers.AddPodAdmitHandler(lifecycle.NewPredicateAdmitHandler(klet.getNodeAnyWay, criticalPodAdmissionHandler, klet.containerManager.UpdatePluginResources))
+       klet.admitHandlers.AddPodAdmitHandler(lifecycle.NewPredicateAdmitHandler(klet.ensureCacheNode, criticalPodAdmissionHandler, klet.containerManager.UpdatePluginResources))
        // apply functional Option's
        for _, opt := range kubeDeps.Options {
                opt(klet)
diff --git a/pkg/kubelet/kubelet_getters.go b/pkg/kubelet/kubelet_getters.go
index f786a6921b2..4e6141106fb 100644
--- a/pkg/kubelet/kubelet_getters.go
+++ b/pkg/kubelet/kubelet_getters.go
@@ -22,6 +22,7 @@ import (
        "io/ioutil"
        "net"
        "path/filepath"
+       "time"

        cadvisorapiv1 "github.com/google/cadvisor/info/v1"
        cadvisorv2 "github.com/google/cadvisor/info/v2"
@@ -32,6 +33,7 @@ import (

        v1 "k8s.io/api/core/v1"
        "k8s.io/apimachinery/pkg/types"
+       "k8s.io/apimachinery/pkg/util/wait"
        "k8s.io/kubernetes/pkg/kubelet/cm"
        "k8s.io/kubernetes/pkg/kubelet/config"
        kubecontainer "k8s.io/kubernetes/pkg/kubelet/container"
@@ -238,7 +240,7 @@ func (kl *Kubelet) GetNode() (*v1.Node, error) {
        return kl.nodeLister.Get(string(kl.nodeName))
 }

-// getNodeAnyWay() must return a *v1.Node which is required by RunGeneralPredicates().
+// getNodeAnyWay() must return a *v1.Node.
 // The *v1.Node is obtained as follows:
 // Return kubelet's nodeInfo for this node, except on error or if in standalone mode,
 // in which case return a manufactured nodeInfo representing a node with no pods,
@@ -252,6 +254,26 @@ func (kl *Kubelet) getNodeAnyWay() (*v1.Node, error) {
        return kl.initialNode(context.TODO())
 }

+// ensureCacheNode() must return a *v1.Node which is required by RunGeneralPredicates().
+// It keeps waiting for the node lister cache to be populated
+// It should panic as predicates need up to date node info
+func (kl *Kubelet) ensureCacheNode() (*v1.Node, error) {
+       if kl.kubeClient == nil {
+               return kl.initialNode(context.TODO())
+       }
+       var n *v1.Node
+       var e error
+       if err := wait.PollImmediate(time.Millisecond*20, time.Second*30, func() (done bool, err error) {
+               if n, e = kl.nodeLister.Get(string(kl.nodeName)); e == nil {
+                       return true, nil
+               }
+               return false, nil
+       }); err != nil {
+               panic("failed to get node %s from node lister")
+       }
+       return n, nil
+}
+
 // GetNodeConfig returns the container manager node config.
 func (kl *Kubelet) GetNodeConfig() cm.NodeConfig {
        return kl.containerManager.GetNodeConfig()
diff --git a/pkg/kubelet/kubelet_test.go b/pkg/kubelet/kubelet_test.go
index 336af7ffeb1..1f24ecffb45 100644
--- a/pkg/kubelet/kubelet_test.go
+++ b/pkg/kubelet/kubelet_test.go
@@ -303,7 +303,7 @@ func newTestKubeletWithImageList(
        kubelet.evictionManager = evictionManager
        kubelet.admitHandlers.AddPodAdmitHandler(evictionAdmitHandler)
        // Add this as cleanup predicate pod admitter
-       kubelet.admitHandlers.AddPodAdmitHandler(lifecycle.NewPredicateAdmitHandler(kubelet.getNodeAnyWay, lifecycle.NewAdmissionFailureHandlerStub(), kubelet.containerManager.UpdatePluginResources))
+       kubelet.admitHandlers.AddPodAdmitHandler(lifecycle.NewPredicateAdmitHandler(kubelet.ensureCacheNode, lifecycle.NewAdmissionFailureHandlerStub(), kubelet.containerManager.UpdatePluginResources))

        allPlugins := []volume.VolumePlugin{}
        plug := &volumetest.FakeVolumePlugin{PluginName: "fake", Host: nil}
@@ -695,7 +695,7 @@ func TestHandlePluginResources(t *testing.T) {

        // add updatePluginResourcesFunc to admission handler, to test it's behavior.
        kl.admitHandlers = lifecycle.PodAdmitHandlers{}
-       kl.admitHandlers.AddPodAdmitHandler(lifecycle.NewPredicateAdmitHandler(kl.getNodeAnyWay, lifecycle.NewAdmissionFailureHandlerStub(), updatePluginResourcesFunc))
+       kl.admitHandlers.AddPodAdmitHandler(lifecycle.NewPredicateAdmitHandler(kl.ensureCacheNode, lifecycle.NewAdmissionFailureHandlerStub(), updatePluginResourcesFunc))

        recorder := record.NewFakeRecorder(20)
        nodeRef := &v1.ObjectReference{
```

**Comment by keyingliu** [comment]
@yifan-gu @krmayankk can you take a look?

**Comment by ehashman** [comment]
@keyingliu can you also please add a test to demonstrate that this fixes the connected issue? :)

**Comment by ehashman** [comment]
/hold

while waiting for tests

**Comment by KevinWang15** [comment]
+1

**Pull request closed without merging**
