### PR TITLE
Fix prometheus-to-sd sidecar in metadata proxy

### PR DESCRIPTION
**Pull request by shyamjvs**
Ref https://github.com/kubernetes/kubernetes/issues/55695#issuecomment-344300188

This is making 2 changes:
- restoring resource requests and limits of the metadata-proxy sidecar as it was before, and remove them for prom-to-sd sidecar (best effort) like at everywhere else
- pass pod name and namespace args to prom-to-sd sidecar (because just noticed)

/cc @ihmccreery @loburm @crassirostris - Does this make sense?

### CODE REVIEW

**Comment by crassirostris** [comment]
SGTM, thanks

Deferring to @loburm to lgtm

**Comment by shyamjvs** [comment]
@mikedanese @cjcullen Could one of you please approve the pr? This needs to go in asap to unblock folks running kubemark-500 presubmit.

**Comment by crassirostris** [comment]
Or @roberthbailey

**Pull request merged**
