### PR TITLE
Support verify option for kubectl version to check client and server version mismatch

### PR DESCRIPTION
**Pull request by nak3**
**What this PR does / why we need it**:

As an kubernetes user, we would like to keep same client's and server's version or same build accurately. Although it is possible to check the version mismatch roughly by writing shell script, it would be great if kubectl supports such function by default.

**Release note**:
```release-note
`kubectl version` command supports --verify option to check client and server version mismatch.
```

### CODE REVIEW

**Review by frapposelli — APPROVED** [review]
LGTM

**Comment by nak3** [comment]
Thank you @fabiand  
Could you please take a look @soltysh

**Comment by soltysh** [comment]
> As an kubernetes user, we would like to keep same client's and server's version or same build accurately. Although it is possible to check the version mismatch roughly by writing shell script, it would be great if kubectl supports such function by default.

I'm not sure how the fix proposed in this PR helps you enforce this with every invocation of `kubectl`. You still need a wraper checking that, which is what you said you can do. We do provide +/-1 compatibility and as such I don't think we want to include any artificial changes that will ensure you're always working with the current version of a server and client. Personally, I'd imagine your server having such a strict rule not to allow clients to talk to it using a different version, but that's a server option not a client.

**Comment by nak3** [comment]
As one example, would like to produce warning message in a cron script. It could be compatible until +1 upgrade, but would like to notice as soon as possible.

An example cron job script:
```
#!/bin/bash

kubectl version --verify --short
if [ $? -eq 1 ]; then
  echo "WARNING: Probably server version was updated. Consider to upgrade client version. Otherwise, kubectl will not be compabile in the future." | mail -s "ACTION REQUIRED" to@foo.example.com
fi

// Some monitoring commands //
kubectl get node --template=...
kubectl get pods --template=...
```

**Comment by soltysh** [comment]
I don't think that the script you've provided needs the change you're proposing in this PR. That functionality is already available with the current code. It will only require a few additional lines of bash to compare the versions returned by the server and client.

**Comment by nak3** [comment]
OK, another example is that we would like to check version mismatch on ansible playbook or remote command execution.
Inserting client/server version check task, especially during upgrade, sometimes necessary and one line command is really helpful.

**Comment by idealhack** [comment]
/ok-to-test
/assign @smarterclayton
/sig cli
@kubernetes/sig-cli-maintainers

**Comment by liggitt** [comment]
How does this differ from the --match-server-version flag?

https://github.com/kubernetes/kubernetes/blob/64bb688ecec332ee4e1ecdad1f3582fb61f82bae/pkg/kubectl/cmd/util/kubectl_match_version.go#L103

**Comment by nak3** [comment]
Oh, I'm sorry, honestly I didn't know the option. It is same feature with this PR. Closing this PR.

**Pull request closed without merging**
