### PR TITLE
fixs typo: if -> it

### PR DESCRIPTION
**Pull request by zgfh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
fix a typo
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Review by yagonobre — APPROVED** [review]
Thanks @zgfh 
/ok-to-test
/lgtm

**Review by neolit123 — APPROVED** [review]
thanks @zgfh 
/priority backlog
/approve

**Comment by neolit123** [comment]
@zgfh please make sure you have signed the CLA:
https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by nikhita** [comment]
/close

Closing + reopening to try fixing the cla label

**Comment by zgfh** [comment]
@neolit123 @nikhita thanks a lot.I create a new PR to fix cla: https://github.com/kubernetes/kubernetes/pull/72476

**Pull request closed without merging**
