### PR TITLE
Remove and replace ptr functions

### PR DESCRIPTION
**Pull request by WanLinghao**
/kind cleanup

**What this PR does / why we need it**:
Remove and replace ptr functions with util functions
```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
/lgtm
/priority backlog
/sig cli

**Comment by neolit123** [comment]
@WanLinghao 
please run ./hack/update-bazel.sh

**Comment by WanLinghao** [comment]
@juanvallejo PTAL

**Comment by juanvallejo** [comment]
/hold
I'd like to get @soltysh 's approval on this as well, since it's introducing a new dependency

/sig cli

**Review by soltysh — APPROVED** [review]
I'm ok with the change, do you think you can grep through `pkg/kubectl` and replace all the places there too?
/approve
/hold cancel

**Comment by WanLinghao** [comment]
@deads2k @thockin This patch is ready to approve

**Comment by WanLinghao** [comment]
@thockin friendly ping

**Comment by WanLinghao** [comment]
@deads2k @thockin  friendly ping

**Comment by WanLinghao** [comment]
@janetkuo Hi, Could you please take a look

**Review by thockin — COMMENTED** [review]
/lgtm
/approve

**Comment by thockin** [comment]
Removing LGTM until tests pass

**Comment by WanLinghao** [comment]
@thockin Hi, this patch is ready

**Comment by WanLinghao** [comment]
@thockin This patch needs your lgtm thanks

**Review by thockin — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
