### PR TITLE
Scheduler: remove the misleading comments in `NodeResourcesBalancedAllocation`

### PR DESCRIPTION
**Pull request by chendave**
Signed-off-by: Dave Chen <dave.chen@arm.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-notes
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
cc @Huang-Wei

**Comment by alculquicondor** [comment]
I actually don't follow why it "MUST" be used with one of the mentioned plugins.
I think we should modify the comment to say "SHOULD" and include both plugins.
But @Huang-Wei is the most familiar with this feature, so I'll leave the decision to him.

**Comment by chendave** [comment]
thank you @alculquicondor for review,  actually, I don't follow as well, this is only something that I saw from the the comments.

hi @Huang-Wei , 
Could you pls share your considerations when the plugin was firstly implemented?

**Comment by Huang-Wei** [comment]
@chendave Sry for the late response. This plugin wasn't authored by me actually... 

Based on my understanding, how `NodeResourcesBalancedAllocation` scores just depend on running Pods' total cpu/mem requests vs. incoming Pod's cpu/mem request - either the incoming Pod makes the node's cpu/mem ratio more balanced or skewed. It's not related with whether `NodeResourcesLeastAllocated` or `NodeResourcesMostAllocated` is enabled - those 2 plugins are scored based on **absolute usage** of cpu/mem. I can easily give examples on `NodeResourcesBalancedAllocation` behave orthogonally or tangentially with either of those 2 plugins.

So I agree that the comment is problematic and we need to fix the comment.

**Comment by chendave** [comment]
@Huang-Wei , thank you for your reply, I will come back later to take care of this when I got some time free.

**Comment by chendave** [comment]
> @chendave Sry for the late response. This plugin wasn't authored by me actually...
> 
> Based on my understanding, how `NodeResourcesBalancedAllocation` scores just depend on existing Pods' total cpu/mem requests vs. incoming Pod's cpu/mem request - either the incoming Pod makes the node's cpu/mem ratio more balanced or skewed. It's not related with whether `NodeResourcesLeastAllocated` or `NodeResourcesMostAllocated` is enabled - those 2 plugins are scored based on **absolute usage** of cpu/mem. I can easily give examples on `NodeResourcesBalancedAllocation` behave orthogonally or tangentially with either of those 2 plugins.
> 
> So I agree that the comment is problematic and we need to fix the comment.

fallback to remove those problematic doc comments only.

**Comment by alculquicondor** [comment]
Thanks @chendave 
/lgtm
/approve

**Comment by Huang-Wei** [comment]
@chendave could you update the comments based on our discussion result?

**Comment by liggitt** [comment]
/test pull-kubernetes-verify

master verify is failing on go1.14 fmt/vet/staticcheck issues, fixed in https://github.com/kubernetes/kubernetes/pull/92438

**Comment by chendave** [comment]
weird, I cannot see this comment on the github directly, just a test with
my gmail.  I was thinking the discussion result has already been included
in the original comments, so no need to update them any more.

**Pull request merged**
