### PR TITLE
Fixed port name validation error message.

### LINKED ISSUE #107212: The error message of portname valid syntax is wrong
### What happened?

https://github.com/kubernetes/kubernetes/blob/65ac7f09ec36736f1282adf876f54b665a35d750/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L318-L346

The `portNameOneLetterRegexp` only support at least one letter，but the error message is  at least one letter or number.
It will be error if portname only numbers, ex: '1-2' or '1' or '123'.

### What did you expect to happen?

Fix the error message or regex syntax

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: test
    workload-type: deployments
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
      workload-type: deployments
  template:
    metadata:
      labels:
        app: test
        workload-type: deployments
    spec:
      containers:
        - name: container123
          image: nginx
          ports:
            - name: 1-2   # < here
              protocol: TCP
              containerPort: 80
```

### Anything else we need to know?

_No response_

### Kubernetes version

at least 1.19+

### Cloud provider

None

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by mk46**
Fixed port name validation error message.
Fixes #107212

### CODE REVIEW

**Comment by Ranler** [comment]
There is a old patch but I don't known why: https://github.com/kubernetes/kubernetes/commit/ccdbe2f79b5ca3be61d83cd4e796867be150f278

**Review by pacoxu — APPROVED** [review]
/lgtm

https://github.com/kubernetes/kubernetes/blob/65ac7f09ec36736f1282adf876f54b665a35d750/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L322-L323

This change just synced the checking code with the error message.

However, https://github.com/kubernetes/kubernetes/blob/851d37ed40400338fea54b3187710d6326cd2908/pkg/apis/discovery/validation/validation.go#L153
checked the port name in another way. 

> There is a old patch but I don't known why: [ccdbe2f](https://github.com/kubernetes/kubernetes/commit/ccdbe2f79b5ca3be61d83cd4e796867be150f278)

/cc @dchen1107

**Comment by mk46** [comment]
Hi @dims, Please take a look. Waiting for the final pass to land in master. Thanks!!

**Comment by pacoxu** [comment]
/assign deads2k
https://github.com/kubernetes/kubernetes/commit/6a4d5cd7cc58e28c20ca133dab7b0e9e56192fe3

**Pull request merged**
