### PR TITLE
kubectl version should print just client information in the absence of kubeconfig

### PR DESCRIPTION
**Pull request by deads2k**
If the kubeconfig is empty (distinct from kubeconfig is invalid or failed to build), then we should output the client information instead of failing

```release-note
NONE
```

@kubernetes/sig-cli-maintainers 
/kind bug
/priority important-soon

### CODE REVIEW

**Review by juanvallejo — APPROVED** [review]

**Comment by AishSundar** [comment]
@deads2k we are seeing [timeouts in release blocking serial jobs](https://github.com/kubernetes/kubernetes/issues/70810) and think this PR might be the cause. Can you please investigate as priority. Thanks.

**Comment by yue9944882** [comment]
hey @AishSundar, i believe they are completely irrelevant. the change in this pull wont bring any change to kubelet 🙂

**Comment by AishSundar** [comment]
@yue9944882 yep we figured that out offline and triaged the test failure to the right owner.

**Pull request merged**
