### PR TITLE
cloud node controller: check Kubernetes server version before applying new node labels

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: andrewsykim <kim.andrewsy@gmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
In v1.17, we deprecated the beta zone/region/instance-type labels for nodes and added the "GA" versions of them (see https://github.com/kubernetes/kubernetes/pull/82049 and https://github.com/kubernetes/kubernetes/pull/81431). This works as expected for in-tree cloud providers, however, for out-of-tree providers using the CCM (cloud-controller-manager), there's a version skew issue if a CCM depends on k8s.io/kubernetes@v1.17 even though the cluster itself is on a prior version. In this case, the CCM would try to add the GA topology labels even though they should only be present v1.17.0 and onward. 

Ideally, users are always running a CCM that uses the same version of k8s.io/kubernetes as the version of Kubernetes they are running. However, I think this is asking too much of users since the imported version of k8s.io/kubernetes in the CCM is not easily discoverable for users.

This PR adds a server version check in the CCM so that if a CCM >= v1.17 is running on a cluster < v1.17.0, it will not add the new topology labels. 

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
I haven't seen any user reports of this issue, my guess is because there's typically a version gap between k/k releases and out-of-tree releases so there hasn't been any released providers supporting v1.17 yet.  

**Does this PR introduce a user-facing change?**:

```release-note
cloud node controller: check Kubernetes server version before applying new GA node topology labels
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/hold

We intentionally do not base client behavioral decisions based on detected server version. 

The scenario is theoretical enough that I'd like to understand the problem being addressed here. If there are expected to be version mismatches like this at play, I think that will invalidate a lot of assumptions and tests; I don't think piece-mill version gating of behavior is a great idea.

**Comment by andrewsykim** [comment]
This is more of an attempt to make compatibility between external cloud providers and Kubernetes better. 

The problem right now is that external cloud providers depend on a single version of k8s.io/kubernetes for a given release of the provider. But... they also claim that a specific version of the provider works against N Kubernetes versions, which has historically been true because most of the logic in the cloud-based controllers have not changed in a backwards/forwards incompatible way. 

With the addition of the GA node labels, there's now a chance that when a cloud provider cuts a new release, say v1.2 w/ k8s.io/kubernetes@v1.17, a user would naturally assume v1.2 can also work on v1.16, v1.15, etc which would lead to those labels being introduced before v1.17. 

The _most ideal_ solution would be to tell providers to be very clear about what versions of Kubernetes a given release supports (which many do today) and expect users to strictly follow that.. however... this sounds like it would cause a lot of pain for both maintainers of the provider and it's users since:
* maintainers have to manage a complex compatibility matrix across their providers and Kubernetes. 
* maintainers would have to manage release branches once they update to k8s.io/kubernetes v1.17 and want to support older versions. Maybe this was inevitable? 
* it wouldn't be clear to users that the CCM needs to be upgraded/downgraded along side core Kubernetes -- and rightly so because decoupling from core k8s was one of the goals.

**Comment by andrewsykim** [comment]
fwiw I do think checking the server version is hacky, would it be any better or different to check the node version since we are reconciling against node objects anyways?

**Comment by liggitt** [comment]
> In this case, the CCM would try to add the GA topology labels even though they should only be present v1.17.0 and onward.

can you describe the problems encountered by the CCM adding the GA labels on old clusters? since it doesn't remove the beta labels, this seems strictly additive to me

**Comment by andrewsykim** [comment]
Correct, it is strictly additive. The biggest concern is inconsistency with what is in core and that ultimately leading users to confusion. 

I see your point that it's mostly harmless cause it's only additive changes. Thanks @liggitt! 

/close

**Pull request closed without merging**
