### PR TITLE
[DO NOT MERGE] hack/ginkgo-e2e.sh: debugging EKS

### PR DESCRIPTION
**Pull request by gyuho**
**What type of PR is this?**

/hold

**What this PR does / why we need it**:

https://k8s-testgrid.appspot.com/sig-aws-eks-ci-kubernetes-e2e-1-10#ci-kubernetes-e2e-1-10-aws-eks-1-10-prod-conformance and others are still failing:

> error during ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Conformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8 --report-dir=/workspace/_artifacts --disable-log-dump=true: exit status 1

We want to create a test PR in kubernetes/kubernetes to debug around "hack/ginkgo-e2e.sh" script.
In order to do that, we have created `pull-kubernetes-e2e-aws-eks-1-11-prod-conformance` here https://github.com/kubernetes/test-infra/blob/445cfb0a00afcd4441d004dbd0eafa02425c3604/config/jobs/kubernetes/sig-aws/eks/k8s-aws-eks-presubmits.yaml#L5.

Ref. https://github.com/kubernetes/test-infra/pull/10387
Ref. https://github.com/kubernetes/test-infra/pull/10457

**Special notes for your reviewer**:

/hold

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gyuho** [comment]
There was a typo in `/test` command. Didn't mean to trigger generated security tests.

Now

/test pull-kubernetes-e2e-aws-eks-1-11-prod-conformance

**Comment by gyuho** [comment]
@shyamjvs 

```
W1220 17:43:32.427] Run: ('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-aws-eks-1-11-prod-conformance', '--up', '--down', '--test', '--deployment=eks', '--provider=eks', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e', '--check-version-skew=false', '--extract=local', '--ginkgo-parallel=30', '--test_args=--ginkgo.focus=\\[Conformance\\] --ginkgo.skip=\\[Slow\\]|\\[Serial\\]|\\[Disruptive\\]|\\[Flaky\\]|\\[Feature:.+\\] --minStartupPods=8', '--timeout=180m')
W1220 17:43:32.468] 2018/12/20 17:43:32 main.go:326: Limiting testing to 3h0m0s
W1220 17:43:32.471] 2018/12/20 17:43:32 eks.go:263: curl https://github.com/aws/aws-k8s-tester/releases/download/0.1.7/aws-k8s-tester-0.1.7-linux-amd64
```

Seems like `--extract=local` isn't going to work?

Should we try

```
--extract=ci/k8s-stable1
```

?

https://prow.k8s.io/log?job=pull-kubernetes-e2e-aws-eks-1-11-prod-conformance&id=1

**Comment by shyamjvs** [comment]
I think `--extract=local` should be fine (for e.g see - https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-presubmit-jobs.yaml#L26).

**Comment by shyamjvs** [comment]
Do you have a link to the presubmit job's testgrid?

**Comment by shyamjvs** [comment]
Ok, it seems like the reason for the failure is:

```
./hack/ginkgo-e2e.sh: line 23: KUBECONFIG: unbound variable
```

which is happening due to one of the echo statements you added. Did you mean to use `KUBE_CONFIG_FILE` instead?

**Comment by shyamjvs** [comment]
@krzyzacy @BenTheElder Do you know why logs for the presubmit run aren't there - https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/72246/pull-kubernetes-e2e-aws-eks-1-11-prod-conformance/2/ ?

**Comment by krzyzacy** [comment]
looks like the job should upload to pr-logs instead of logs

**Comment by krzyzacy** [comment]
also consider use podutils instead of bootstrap to configure your jobs which can save you a lot of hassle...

**Comment by gyuho** [comment]
> main.go:313: Something went wrong: failed to acquire k8s binaries: error starting /go/src/k8s.io/release/push-build.sh --nomock --verbose --noupdatelatest --bucket=kubernetes-release-pull --ci --gcs-suffix=/pull-kubernetes-e2e-aws-eks-1-11-prod-conformance --allow-dup: fork/exec /go/src/k8s.io/release/push-build.sh: no such file or directory
W1220 17:43:33.529] Traceback (most recent call last):

Also seems like `--extract=local` expects `push-build.sh` script :0

**Comment by krzyzacy** [comment]
So - what do you want to test here - an upstream kubernetes version, or the local version from your PR?

If for later, you'll need to checkout your PR and build it. How about referencing the gce presubmit job? https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-gcp/sig-gcp-gce-config.yaml#L37-L54

**Comment by gyuho** [comment]
> what do you want to test here ... or the local version from your PR?

Yes, local version of PR so that we can debug `./hack/ginkgo-e2e.sh` as we make changes to it. Let me try referencing the GCE job then.

> podutils instead of bootstrap to configure

Ok, I will also look into podutils. Thanks for the help!

**Comment by gyuho** [comment]
@shyamjvs @krzyzacy @BenTheElder 

Finally we are now able to run e2e tests!

The fix was adding [`KUBERNETES_CONFORMANCE_*` and `KUBECTL`](https://github.com/kubernetes/test-infra/pull/10546) to our Prow job configuration.

Results can be found at:
- Conformance
  - https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/72246/pull-kubernetes-e2e-aws-eks-1-11-prod-conformance/13/
  - https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-1-11-aws-eks-1-11-prod-conformance/119
- Release e2e
  - https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-1-11-aws-eks-1-11-prod/119
  - https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-stable-aws-eks-1-11-prod/119

Some tests are failing, which we will investigate one by one.

Thanks a lot!

**Pull request closed without merging**
