### PR TITLE
Modify the judgment conditions

### LINKED ISSUE #56347: cloudstack kubelet configuration: error when fetching metadata
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

kubelet throws the exception when --cloud-provider=cloudstack is included:

`Unable to construct v1.Node object for kubelet: could not get instance type: <nil>`

**What you expected to happen**:

There shouldn't be an exception. 

**How to reproduce it (as minimally and precisely as possible)**:
Add the following line to /etc/systemd/system/kubelet.service.d/10-kubeadm.conf:

`
Environment="KUBELET_EXTRA_ARGS=--cloud-provider=cloudstack --cloud-config=/etc/kubernetes/cloud.conf" 
`
and also configure the cloud.conf file.

**Anything else we need to know?**:

The condition check in the InstanceType() function in metadata.go is wrong. It currently reads:
```
// InstanceType returns the type of the specified instance.
func (m *metadata) InstanceType(name types.NodeName) (string, error) {
        instanceType, err := m.get(metadataTypeInstanceType)
	if err == nil {
		return "", fmt.Errorf("could not get instance type: %v", err)
	}
```

but the correct code is (condition negated):

```
func (m *metadata) InstanceType(name types.NodeName) (string, error) {
	instanceType, err := m.get(metadataTypeInstanceType)
	if err != nil {
		return "", fmt.Errorf("could not get instance type: %v", err)
	}

```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.8
- Cloud provider or hardware configuration: cloudstack
- OS (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS (Xenial Xerus)
- Kernel (e.g. `uname -a`): 4.4.0-98-generic
- Install tools: kubeadm
- Others:

/sig cloudstack

### PR DESCRIPTION
**Pull request by stewart-yu**
**What this PR does / why we need it**:
It should be a mistakes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #56347 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by stewart-yu** [comment]
kind/bug

**Comment by jhorwit2** [comment]
@deads2k not sure why but the approved label didn't get added

**Comment by deads2k** [comment]
> @deads2k not sure why but the approved label didn't get added

I'm not a cloud provider approver.  I'll manually tag this one though.  It's fairly obvious.

**Pull request merged**
