### PR TITLE
Automated cherry pick of #103160: Remove extra zone test

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
Cherry pick of #103160 on release-1.21.

#103160: Remove extra zone test

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
cc @msau42 @mattcary

**Review by cpanato — APPROVED** [review]
/triage accepted
/priority important-soon

from RelEng:
/lgtm

**Pull request merged**
