### PR TITLE
fix log message error in nodelifecycle

### PR DESCRIPTION
**Pull request by gosoon**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

The corresponding log error under the code block，this PR does fix error log.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by neolit123** [comment]
thanks for the PR, it looks good.

/check-cla

please sign the CLA as the bot instructed above and make sure you have the CLA email added to your github account. if you have issues please contact the CNCF help desk.

**Comment by neolit123** [comment]
> k8s-ci-robot added cncf-cla: yes and removed

looks like you signed it.

/ok-to-test
/lgtm
/priority backlog
/assign @bowei

**Comment by gosoon** [comment]
@neolit123 And then what's the next step？

**Comment by neolit123** [comment]
the assigned approver should take a look and approve. if you are not getting a response try asking in the #sig-apps channel of k8s slack.

**Pull request merged**
