### PR TITLE
Updating config files to use latest heapster image

### PR DESCRIPTION
**Pull request by nikhiljindal**
Latest image includes https://github.com/GoogleCloudPlatform/heapster/pull/387

### CODE REVIEW

**Comment by krousey** [comment]
@k8s-bot test this please

**Comment by nikhiljindal** [comment]
cc @bgrant0607 
heapster is still emitting beta3 URLs.
@krousey and I are trying to debug.

**Comment by krousey** [comment]
@k8s-bot test this please

**Comment by krousey** [comment]
@k8s-bot test this please

**Comment by krousey** [comment]
@nikhiljindal The tests timed out, but heapster was using v1 in that last one. The v1beta3 in that run came from elasticsearch which I think @satnam6502 just fixed.

**Comment by nikhiljindal** [comment]
@k8s-bot test this please

**Comment by krousey** [comment]
@k8s-bot test this please

**Comment by krousey** [comment]
@k8s-bot test this and please work this time :pray:

**Comment by krousey** [comment]
@nikhiljindal It's in. Once they do a release, you can update the tag to the official one and submit this.

cc @vmarmol @rjnagal

**Comment by krousey** [comment]
@nikhiljindal ... What happened to this? Where did all the other commits come from?

**Comment by krousey** [comment]
#10755

**Comment by nikhiljindal** [comment]
Yes sorry, I messed this up.
Sent https://github.com/GoogleCloudPlatform/kubernetes/pull/10872

**Comment by vmarmol** [comment]
I actually only *just* Heapster to gcr.io

**Pull request closed without merging**
