### PR TITLE
Automated cherry pick of #23466

### PR DESCRIPTION
**Pull request by andyzheng0831**
Cherry pick of #23466 on release-1.2.

### CODE REVIEW

**Comment by andyzheng0831** [comment]
I make this cherry-pick PR according to the comment https://github.com/kubernetes/kubernetes/pull/23466#issuecomment-202502718

**Comment by andyzheng0831** [comment]
@ixdy please review this cherry-pick. We don't want to miss 1.2.1 release. Thanks

**Comment by andyzheng0831** [comment]
cc/ @roberthbailey @fabioy, can you review this cherry pick so that we can catch up with the 1.2.1 release? Although it is not a fix to breakage, it would be better to make e2e green. Thanks!

**Comment by ixdy** [comment]
LGTM

@bgrant0607 @eparis why did this get the `do-not-merge` label?

**Comment by ixdy** [comment]
also cc @david-mcmahon re: cherry-picking process

**Comment by david-mcmahon** [comment]
@ixdy https://github.com/kubernetes/kubernetes/pull/23543#issuecomment-202511995

**Comment by ixdy** [comment]
@david-mcmahon it'd be helpful if the bot suggested adding the `cherrypick-candidate`, or even if it added it automatically.

Probably also worth updating `hack/cherry_pick_pull.sh` so it adds the label when it [creates the PR](https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh#L155)? Though I'm not sure if it'd then fail for anyone who doesn't have commit access.

**Comment by david-mcmahon** [comment]
@ixdy agreed.  Not sure why it doesn't just do that already.  Maybe there is a permission issue?   The script uses hub and could apply a label, but yes what is unknown to me is how/if that would fail.

**Comment by david-mcmahon** [comment]
@ixdy, looks like [this functionality](https://github.com/github/hub/pull/968) is only available in a very recent version of hub.  We'd have to check the version and use the labeling feature based on that.

**Comment by andyzheng0831** [comment]
It seems like this pr will not be automatically merged because do-not-merge is present

**Comment by eparis** [comment]
@ixdy to be fair, the bot did tell you why it added the label: https://github.com/kubernetes/kubernetes/pull/23543#issuecomment-202511995

**Comment by eparis** [comment]
I'm sure that @bgrant0607 will come through soon and approve or not.

**Comment by bgrant0607** [comment]
Hmm. The original PR has the cherrypick-approved label.

**Pull request merged**
