### PR TITLE
Bump etcd revision after changes to migrate script

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #92286

```release-note
NONE
```

/kind bug

### CODE REVIEW

**Review by jingyih — COMMENTED** [review]
/lgtm

**Comment by jingyih** [comment]
I realized we probably should have bumped the revision as part of #92286. Any changes under `cluster/images/etcd` triggers a new image build and push to staging repo.

**Comment by wojtek-t** [comment]
> I realized we probably should have bumped the revision as part of #92286. Any changes under cluster/images/etcd triggers a new image build and push to staging repo.

yes - it's a follow-up exactly; sorry, I forgot about it

/retest

**Comment by BenTheElder** [comment]
Because of the promotion system (by sha256) as long as the promotion PRs happen promptly / with the correct digest the "prod" registry will have the "correct" image anyhow, but we should probably keep this bumped.

**Pull request merged**
