### PR TITLE
Automated cherry pick of #75455: build/gci: bump CNI version to 0.7.5

### PR DESCRIPTION
**Pull request by philips**
Cherry pick of #75455 on release-1.13.

#75455: build/gci: bump CNI version to 0.7.5

```release-note
bump CNI (network plugins) version to 0.7.5
```

### CODE REVIEW

**Comment by dcbw** [comment]
Test seems like a flake:

```
I0319 06:50:30.056] +++ Running case: verify.swagger-spec 
I0319 06:50:30.060] +++ working dir: /go/src/k8s.io/kubernetes
I0319 06:50:30.063] +++ command: bash "hack/make-rules/../../hack/verify-swagger-spec.sh"
I0319 06:50:30.564] Terminate 683 on timeout
E0319 06:50:30.666] Build timed out
E0319 06:50:30.666] Command failed
I0319 06:50:30.666] process 683 exited with code -15 after 73.8m
```

/kind bug
/retest

**Comment by tpepper** [comment]
/priority important-soon

The PR from which this is cherry picked did not have a release note, but feels like it should have at least said "bump CNI version to 0.7.5".

**Comment by tpepper** [comment]
/lgtm
(confirmed with Tim Hockin it was missing, but intended)

**Pull request merged**
