### PR TITLE
Update to storm example

### PR DESCRIPTION
**Pull request by mattf**
fixed an anchor and added source information

### CODE REVIEW

**Comment by cjcullen** [comment]
@mattf Can you squash these commits too?

**Comment by piosz** [comment]
Is this PR active? If not please close it according to https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/pull-requests.md

**Comment by mattf** [comment]
@piosz i was waiting on reviewer comments. side - the shippable failure - i can't get any details on it, can you?

**Comment by piosz** [comment]
@mattf after you click on shippable details, you should "signup for free" using your github credentials. Then you can see the details, especially:
```
FAIL	github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet	2.034s
```

You should also ping the reviewer, however @cjcullen asked you to squash commits. You can do this using `git rebase -i HEAD^^` and then choosing appropriate options.

**Comment by mattf** [comment]
@piosz thanks for pointing that out. @cjcullen squashed.

**Pull request merged**
