### PR TITLE
kubeadm: update the state in app/cmd.go

### PR DESCRIPTION
**Pull request by neolit123**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Update the stdout text when invoking `kubeadm` without flags and arguments:

- BETA->GA
- master->control-plane
- exclude @ mentions as only members can use them

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
NONE

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/assign @timothysc @luxas @fabriziopandini 
/priority important-soon
cc @kubernetes/sig-cluster-lifecycle-pr-reviews

### CODE REVIEW

**Review by fabriziopandini — APPROVED** [review]
@neolit123 thanks!
/approve

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Pull request merged**
