### PR TITLE
Integration test for kube-apiextensions-server: integers

### PR DESCRIPTION
**Pull request by nikhita**
**What this PR does / why we need it**: Check if integers are present after decoding.
Originally an issue for TPRs: #30213

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: for #45511 

**Special notes for your reviewer**:

**Release note**:

```
NONE
```
@sttts

### CODE REVIEW

**Comment by sttts** [comment]
@k8s-bot ok to test

**Comment by nikhita** [comment]
@k8s-bot unit test this

**Comment by nikhita** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by nikhita** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
