### PR TITLE
[1.18] Update repo-infra to v0.0.8 (to support go1.14.6 and go1.13.14)

### PR DESCRIPTION
**Pull request by justaugustus**
**What type of PR is this?**

/kind cleanup
/area dependency release-eng
/sig testing release

**What this PR does / why we need it**:

https://github.com/kubernetes/repo-infra/releases/tag/v0.0.8 pulls in bazel toolchain updates to support go1.14.6 and go1.13.14.

Needed for the in-flight Golang updates: https://github.com/kubernetes/release/issues/1410

/assign @fejta @BenTheElder 
cc: @markyjackson-taulia @Verolop @kubernetes/release-engineering 

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

Combined cherry pick of https://github.com/kubernetes/kubernetes/pull/89430, https://github.com/kubernetes/kubernetes/pull/90347, https://github.com/kubernetes/kubernetes/pull/91312, bddd52046d8122af98eab4a172cebb45066a78d1, and https://github.com/kubernetes/kubernetes/pull/92362.

**Does this PR introduce a user-facing change?**:

```release-note
- Update bazel to 2.2.0
- Update repo-infra to 0.0.8 (to support go1.14.6 and go1.13.14)
  - Includes:
    - bazelbuild/bazel-toolchains@3.4.0
    - bazelbuild/rules_go@v0.22.8
```

### CODE REVIEW

**Comment by justaugustus** [comment]
/kind cleanup
/area dependency release-eng
/sig testing release

@fejta @mikedanese -- Can you help me debug these bazel test failures?
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/91348/pull-kubernetes-bazel-build/1263646213018750978
- https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/91348/pull-kubernetes-bazel-test/1263646213027139585

**Comment by fejta** [comment]
There aren't any failures to debug. Looks like some network hiccup.

**Comment by fejta** [comment]
does 1.18 include https://github.com/kubernetes/kubernetes/pull/89430? If not you'll need to cherrypick this in.

**Comment by tpepper** [comment]
Given discussion on 1.14 vs 1.15 @justaugustus should we close this?

**Comment by justaugustus** [comment]
> Given discussion on 1.14 vs 1.15 @justaugustus should we close this?

@tpepper -- we'll still need this to update bazel for future go releases. Next bump will be to k/repo-infra 0.0.7 to support go1.13.13, go1.14.5 (ref: https://github.com/kubernetes/release/issues/1408)

**Comment by justaugustus** [comment]
(I reorganized the commits (instead of squashing them all in) and pulled in bddd52046d8122af98eab4a172cebb45066a78d1.)

Still getting this reasonably vague bazel error...

```
+ bazel build --config=remote --remote_instance_name=projects/k8s-prow-builds/instances/default_instance -- //... -//vendor/... -//build/... //build/release-tars
$TEST_TMPDIR defined: output root default is '/bazel-scratch/.cache/bazel' and max_idle_secs default is '15'.
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from /home/prow/go/src/github.com/kubernetes/kubernetes/build/root/.bazelrc:
  'build' options: --host_force_python=PY2 --verbose_failures --stamp --workspace_status_command hack/print-workspace-status.sh --sandbox_tmpfs_path=/tmp --define gotags=selinux --sandbox_fake_username
INFO: Found applicable config definition build:remote in file /home/prow/go/src/github.com/kubernetes/kubernetes/build/root/.bazelrc: --config=remote-cache --remote_executor=remotebuildexecution.googleapis.com --jobs=500 --host_javabase=@rbe_default//java:jdk --javabase=@rbe_default//java:jdk --host_java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8 --java_toolchain=@bazel_tools//tools/jdk:toolchain_hostjdk8 --crosstool_top=@rbe_default//cc:toolchain --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1 --extra_toolchains=@rbe_default//config:cc-toolchain --extra_execution_platforms=:rbe_with_network --host_platform=:rbe_with_network --platforms=:rbe_with_network --spawn_strategy=remote --strategy=Javac=remote --strategy=Closure=remote --strategy=Genrule=remote --define=EXECUTOR=remote --strategy=PackageTar=sandboxed
INFO: Found applicable config definition build:remote-cache in file /home/prow/go/src/github.com/kubernetes/kubernetes/build/root/.bazelrc: --remote_cache=remotebuildexecution.googleapis.com --remote_timeout=3600 --auth_enabled=true
INFO: Invocation ID: 5bc38b9e-d9b9-4497-9146-d4970ba6ece3
ERROR: Failed to query remote execution capabilities: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
+ ../test-infra/hack/coalesce.py
+ exit 34
```

**Comment by justaugustus** [comment]
Ughhh, I think this has to do with the container image that bazel-build and bazel-test is running on:

```console
ERROR: /home/prow/go/src/github.com/kubernetes/kubernetes/WORKSPACE:21:1: Traceback (most recent call last):
	File "/home/prow/go/src/github.com/kubernetes/kubernetes/WORKSPACE", line 21
		repo_infra_configure(go_version = "1.13.9", minimum_baz...")
	File "/bazel-scratch/.cache/bazel/_bazel_root/7989b31489f31aee54f32688da2f0120/external/io_k8s_repo_infra/repos.bzl", line 26, in repo_infra_configure
		versions.check(minimum_bazel_version = "2.2.0")
	File "/bazel-scratch/.cache/bazel/_bazel_root/7989b31489f31aee54f32688da2f0120/external/bazel_skylib/lib/versions.bzl", line 105, in versions.check
		fail("Current Bazel version is {}; ex...))
Current Bazel version is 0.25.2; expected at least 2.2.0
ERROR: Error evaluating WORKSPACE file
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': error loading package 'external': Could not load //external package
ERROR: error loading package '': Encountered error while reading extension file 'repositories/repositories.bzl': no such package '@io_bazel_rules_docker//repositories': error loading package 'external': Could not load //external package 
```

(ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/91348/pull-kubernetes-bazel-build/1284665293909528576)

I've opened https://github.com/kubernetes/test-infra/pull/18370 to use the new transitional bazel image.

**Comment by justaugustus** [comment]
**t i n y   j o y**

With the transitional image, [bazel-build](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/91348/pull-kubernetes-bazel-build/1284678632593166337) and [bazel-test](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/91348/pull-kubernetes-bazel-test/1284681148454146048).

Going to try this again with 458203b16be288b528eab3485435a180f85f8361 and ea8e43eefec0a6c88f3b0cf6c6f78356490f7393 dropped.

**Comment by justaugustus** [comment]
/assign @liggitt @BenTheElder @fejta 

This is looking good, so I've opened cherry picks:
- 1.17: https://github.com/kubernetes/kubernetes/pull/93218
- 1.16: https://github.com/kubernetes/kubernetes/pull/93219

**Comment by justaugustus** [comment]
The go1.13.14 update in https://github.com/kubernetes/kubernetes/pull/93232 includes these changes and has gone green, so I'm closing this in favor of it.
/close

**Pull request closed without merging**
