### PR TITLE
DEBUG: debug the unit tests

### PR DESCRIPTION
**Pull request by yujuhong**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by yujuhong** [comment]
Closing since this is no longer needed.

**Comment by BenTheElder** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/56900/pull-kubernetes-unit/69821/#k8siokubernetespkgkubeletconfig-testreadpodsfromfilechanged
It seems to get different failure text sometimes, but it fails a lot.

**Comment by BenTheElder** [comment]
Hitting 1.7 too :-( https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/52755/pull-kubernetes-unit/69823/

**Comment by BenTheElder** [comment]
FYI unit not runs against jenkins on release 1.6,1.7,1.8 because we needed to get a 1.8 PR through, but strangley
/test pull-kubernetes-unit-prow
was passing against the 1.8 PR !?
I'm looking into this some more today, the PR was https://github.com/kubernetes/kubernetes/pull/56900

**Comment by yujuhong** [comment]
No longer needed

**Pull request closed without merging**
