### PR TITLE
Change pod.spec.NodeSelector to full label selector

### PR DESCRIPTION
**Pull request by pravisankar**
This will enable user to take advantage of exists,
in, notin, != operators for filtering nodes.

### CODE REVIEW

**Comment by roberthbailey** [comment]
@bgrant0607 for v1.0 triage.

**Comment by bgrant0607** [comment]
cc @sdminonne

**Comment by bgrant0607** [comment]
Thank you for the change. I do want to generalize the selectors in the API (see #341 for the full discussion), but, I'm sorry, we cannot take this change at this time. This is a non-backward-compatible API change and isn't critical for 1.0.

Also, a string isn't a workable representation for the selector in the API, since it is hostile to patching and merging, among other reasons. Please see previous discussion in #7053.

**Comment by pravisankar** [comment]
Closing this PR in favor of #7053

**Pull request closed without merging**
