### PR TITLE
Automated cherry pick of #103176: Update golang.org/x/net to v0.0.0-20210520170846-37e1c6afe023

### PR DESCRIPTION
**Pull request by jonesbr17**
Cherry pick of #103176 on release-1.21.

#103176: Update golang.org/x/net to v0.0.0-20210520170846-37e1c6afe023

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by jonesbr17** [comment]
@fedebongio I've rebased the PR to address the merge conflicts. Anything else that needs to be done to get this reviewed?

**Comment by jonesbr17** [comment]
@fedebongio PR has been rebased again to address merge conflicts

**Comment by aojea** [comment]
the diff of the original pr only shows 2 changes in go.mo
```
	golang.org/x/net v0.0.0-20210405180319-a5a99cb37ef4
	golang.org/x/net v0.0.0-20210520170846-37e1c6afe023
```

why are there so many changes in this PR go.mod?

**Comment by jonesbr17** [comment]
@aojea I ran the [cherry-pick script](https://git.k8s.io/kubernetes/hack/cherry_pick_pull.sh) which automatically generated this PR from the original

**Comment by jonesbr17** [comment]
This has been superseded by https://github.com/kubernetes/kubernetes/commit/1c15f1c1d9cb9271322c2445d773783ada646f41

**Pull request closed without merging**
