### PR TITLE
update prometheus/client_golang to v1.19.0

### PR DESCRIPTION
**Pull request by shijinye**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
update prometheus/client_golang to v1.19.0

#### Which issue(s) this PR fixes:

Fixes # None

#### Does this PR introduce a user-facing change?

```release-note
update prometheus/client_golang to v1.19.0
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by dims** [comment]
/ok-to-test

can you please add some context on why we are updating?

**Comment by AntWDev** [comment]
I've got a project which imports github.com/prometheus/common v0.48.0 and k8s.io/component-base v0.29.2 directly. This is causing build failures due to 
`could not import k8s.io/component-base/metrics/testutil (-: # k8s.io/component-base/metrics/testutil
/home/antw/go/pkg/mod/k8s.io/component-base@v0.29.2/metrics/testutil/metrics.go:73:59: undefined: expfmt.FmtText) (typecheck)
	"k8s.io/component-base/metrics/testutil"
`
So this update is required to fix this

**Comment by AntWDev** [comment]
Any updates on this?

**Comment by mythi** [comment]
> I've got a project which imports github.com/prometheus/common v0.48.0 and k8s.io/component-base v0.29.2 directly. This is causing build failures due to `could not import k8s.io/component-base/metrics/testutil (-: # k8s.io/component-base/metrics/testutil /home/XXX/go/pkg/mod/k8s.io/component-base@v0.29.2/metrics/testutil/metrics.go:73:59: undefined: expfmt.FmtText) (typecheck) "k8s.io/component-base/metrics/testutil" ` So this update is required to fix this

I don't think this PR alone is going to help. AFAUI `metrics.go` needs fixing too since `prometheus/common` has a breaking change:

```
diff --git a/staging/src/k8s.io/component-base/metrics/testutil/metrics.go b/staging/src/k8s.io/component-base/metrics/testutil/metrics.go
index df3f8ee0c1d..c595f55d64a 100644
--- a/staging/src/k8s.io/component-base/metrics/testutil/metrics.go
+++ b/staging/src/k8s.io/component-base/metrics/testutil/metrics.go
@@ -70,7 +70,7 @@ func NewMetrics() Metrics {
 
 // ParseMetrics parses Metrics from data returned from prometheus endpoint
 func ParseMetrics(data string, output *Metrics) error {
-       dec := expfmt.NewDecoder(strings.NewReader(data), expfmt.FmtText)
+       dec := expfmt.NewDecoder(strings.NewReader(data), expfmt.NewFormat(expfmt.TypeTextPlain))
        decoder := expfmt.SampleDecoder{
                Dec:  dec,
                Opts: &expfmt.DecodeOptions{},
```

**Comment by dgrisonnet** [comment]
@shijinye could you perhaps rebase this PR and address @mythi's comment above? Seems like there is at least one place that would need to be updated.

**Comment by dgrisonnet** [comment]
Closing since this was covered in https://github.com/kubernetes/kubernetes/pull/124346

/close

**Pull request closed without merging**
