### PR TITLE
Allow core CephFS/RBD mounters to find Ceph monitors via DNS SRV queries

### PR DESCRIPTION
**Pull request by dmlambea**
**What this PR does / why we need it**:  According to RFC 2782, SRV records are useful to decouple services from hostnames/addresses. By using SRV lookups, service clients don't need to know final hostnames/addresses, but only service names and domains.

Currently, Ceph-related Volumes/PersistentVolumes require the pods to be informed with fixed hostnames/IPs so the mount process can reach the Ceph monitors. This PR adds a new field of type SRVRecordSource with the information to address a DNS service record. Ceph mounters can now perform DNS lookups if no monitor addresses are specified. Backwards compatibility is ensured by honouring the monitors fields before attempting to perform lookups, so the lookup only takes place if the monitors field is empty.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Add monitorSRVRecord to the CephFS/RBD Volume/PersistentVolume core types, so DNS SRV records can be used to lookup for Ceph monitors' addresses at mount-time instead of requiring to put the hostnames/addresses in the pod data.
```

### CODE REVIEW

**Comment by dims** [comment]
@dmlambea : please rebase the PR when you get a chance, don't worry about the labels (especially the cncf-cla" label should persist across rebases)

**Comment by dmlambea** [comment]
@rootfs I think that PR is not focused in the same problem as I have. I don't have the need to configure the host's DNS to forward queries to the in-cluster DNS, because it is not my use case. The ceph cluster is managed apart from the Kubernetes cluster, so the host DNS is actually well configured beforehand.

What I need is to avoid setting IP/hostname data in pod definitions, but service names (in my case, ceph monitors). This way, all changes related to the Ceph cluster is delegated to the Ops team. My PR allows the "mount" cmdline to be fed with IP/hostnames obtained from SRV records, regardless of the amount of monitors in the cluster and the hostnames/IP assigned to them. The global type I've added can be reused to improve any other k8s type that might require the addressing of SRV records.

**Comment by rootfs** [comment]
@dmlambea the use case in that ceph rbd provisioner is similar to yours: instead of using monitor IP directly, it obtains the monitor's DNS records, and append to the monitor IPs, if the IPs are resolved by kube-dns.

In a broader scenario, you can use both IP and DNS names for your ceph monitors in rbd storage class and do not have to set SRV record here.

**Comment by rootfs** [comment]
@dmlambea  I am not comfortable with new API and changes to existing one. For an off tree rbd driver, you can take a look at [ceph-csi](https://github.com/ceph/ceph-csi).

**Comment by dmick** [comment]
As it turns out ceph-mon already can consult SRV records to find the rest of the mon cluster.  I guess I'm not exactly sure why the other daemons don't/can't; maybe that's another possible path

**Comment by rootfs** [comment]
@dmlambea thanks, ping me when you are on ceph-csi.

**Comment by dmick** [comment]
Actually @dmlambea, all monclients (including the daemons and Ceph clients) should be doing the SRV search if they're not given a monmap; maybe this will help you?  I've successfully connected to clusters with no monitors specified by providing SRV records for the domains _ceph-mon._tcp[.domain] (the ceph-mon part of the string and the domain are settable, see http://docs.ceph.com/docs/master/rados/configuration/mon-lookup-dns/).   Maybe this will resolve your issue without waiting for ceph-csi drivers?

**Comment by dmlambea** [comment]
@dmick  the client in my case in the in-tree driver (pkg/volume/cephfs/cephfs.go), which is composing the mount commandline to be passed to the mounter (in pkg/util/mount/...) as a valid "mount" command. The linux kernel driver (http://docs.ceph.com/docs/jewel/cephfs/kernel/) is used and it needs the IPs because it does not perform any searches. Because of this, my work was to enhance the in-tree driver so that it can guess the IPs for the mounter to work properly.

As I understand, the monclient in the URL you wrote is a wrapper that might be or might not be available in the host machines. But anyways, the in-tree driver is not using it, so for now my patch is the easiest/safest way.

I agree with @rootfs: altering the API is a delicate operation. I will take a look at ceph-csi, but it will take a bit of time since my cluster is still 1.9.x.

Another option would be not to alter the API, but parse the "monitors" configuration to see if the value matches a SRV record query (e.g, if the monitor looks like "_<name>._tcp.<domain>") and if it's the case, then perform the DNS query. This would allow the core, in-tree mounter to look for monitors in DNS without requiring an API change. Not as elegant as having a dedicated API, but I think it would work for all cases. If you like this option, please let me know and I'll drop this PR in favor of that new approach.

**Comment by dmick** [comment]
You're right in that the kernel clients (krbd and kcephfs, colloquially) don't use the same code as the userland clients, and they seem to not support SRV searching.  I was thinking in the wrong context.

I believe the plan, at least, is to move to the CSI drivers, so yes, I'd also advise against this PR's approach.  I was hoping I'd found a loophole but I guess not.

**Comment by dmlambea** [comment]
Ok, let's close this PR then. I will be on ceph-csi a.s.a.p.

@rootfs, @dmick, thank you very much for your comments and support!

**Pull request closed without merging**
