### PR TITLE
 remove duplicate words in comments

### PR DESCRIPTION
**Pull request by charlesh001**
**What this PR does / why we need it**:
remove duplicate words in comments, as it may cause confused.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
remove the duplicate words

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by huangqg** [comment]
hi, I have signed the cncf-cla

**Comment by xiangpengzhao** [comment]
@huangqg this PR includes many of other commits. I notice that you sent this PR from your master branch. Please create a new branch to send a patch :)

**Comment by huangqg** [comment]
@xiangpengzhao  thanks for your response, I'll create a new branch then submit.

**Pull request closed without merging**
