### PR TITLE
Automated cherry pick of #65443: azure: Move configuration of resource group in storage class.

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #65443 on release-1.8.

#65443: azure: Move configuration of resource group in storage class.

```release-note
NONE
```

### CODE REVIEW

**Comment by jsafrane** [comment]
/lgtm
/assign @colemickens @brendandburns 
for approval

**Comment by nikhita** [comment]
/assign @jpbetz 
for cherry-pick approval

**Pull request merged**
