### PR TITLE
use klog.Info and klog.Warning when had no format

### PR DESCRIPTION
**Pull request by pandaamanda**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
kubelet changes lgtm.

/approve

**Comment by lavalamp** [comment]
Next time I recommending sending separate PRs so you can get approval from just a single SIG, you'll get a faster response that way

**Pull request merged**
