### PR TITLE
Automated cherry pick of #70735 #73845 upstream release 1.11 

### PR DESCRIPTION
**Pull request by wojtek-t**
Cherry pick of #73845 on release-1.11.
#70735 : Use watch cache when rv=0 even when limit is set
#73845 : Avoid going back in time in watchcache watchers

### CODE REVIEW

**Comment by liggitt** [comment]
pick doesn't appear clean, there were some legitimate build/test failures

**Comment by wojtek-t** [comment]
> pick doesn't appear clean, there were some legitimate build/test failures

@liggitt - yes sorry, BUILD file didn't merge correctly. Hopefully should be fixed now.

**Comment by wojtek-t** [comment]
@liggitt - I'm sorry, one more thing (s/ParseResourceVersion/ParseListResourceVersion - in 1.11).

**Pull request merged**
