### PR TITLE
kubeadm: update versions for 1.19

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:

update current/minimal supported versions.

**Which issue(s) this PR fixes**:

xref https://github.com/kubernetes/kubeadm/issues/2076

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
@kubernetes/sig-cluster-lifecycle-pr-reviews 
looking for LGTM. thanks.

**Comment by fabriziopandini** [comment]
🥳

**Pull request merged**
