### PR TITLE
Revert "Update cassandra.list"

### PR DESCRIPTION
**Pull request by thockin**
Reverts kubernetes/kubernetes#25711

https://github.com/kubernetes/kubernetes/pull/25711#issuecomment-219911835

### CODE REVIEW

**Comment by thockin** [comment]
Since I approved it in the first place: LGTM

**Comment by bgrant0607** [comment]
cc @chrislovecnm

**Comment by chrislovecnm** [comment]
@thockin please push the 'Merge pull request' button 😄

**Comment by zmerlynn** [comment]
@chrislovecnm: I did the next best thing.

**Comment by chrislovecnm** [comment]
@zmerlynn much thanks!

**Comment by chrislovecnm** [comment]
@zmerlynn the latest image v9 is using 3.5

**Pull request merged**
