### PR TITLE
Automated cherry pick of #62568: Generated build files

### PR DESCRIPTION
**Pull request by liztio**
Cherry pick of #62568 on release-1.10.

#62568: Generated build files

### CODE REVIEW

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve 

We've already went through the details on the original PR.

**Comment by liztio** [comment]
@fejta your bot is fighting @k8s-ci-robot 🤖 🤖

**Review by fabriziopandini — APPROVED** [review]
/lgtm

**Comment by timothysc** [comment]
@kubernetes/sig-testing-bugs ^ kubemark does not seem to be happy, and it totally unrelated to this change.

**Comment by BenTheElder** [comment]
/cc @shyamjvs 
looks to me like more quota issues with scalability projects
/retest

**Comment by krzyzacy** [comment]
I believe @shyamjvs need to cherry-pick some of his custom subnetwork fixes back to older releases

**Comment by shyamjvs** [comment]
Yes, my cherrypick (https://github.com/kubernetes/kubernetes/pull/62847) is in - it should hopefully pass now.

/retest

**Pull request merged**
