### PR TITLE
Fix typo in node lifecycle controller

### PR DESCRIPTION
**Pull request by jhedev**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

fixes a typo

**Which issue(s) this PR fixes**:

Fixes a typo

**Special notes for your reviewer**:

none

**Does this PR introduce a user-facing change?**:

```release-notes
NONE
```

### CODE REVIEW

**Review by odinuge — APPROVED** [review]
LGTM 😄

**Comment by andrewsykim** [comment]
/approve
/lgtm

Thanks!

**Pull request merged**
