### PR TITLE
Hide the v1.0 content from web crawlers

### PR DESCRIPTION
**Pull request by janetkuo**
Addresses #15893

Hide the v1.0 content from web crawlers and focus SEO on new v1.1. 
cc @RichieEscarez

### CODE REVIEW

**Comment by bgrant0607** [comment]
@brendandburns Do you know robots.txt format?

**Comment by bgrant0607** [comment]
LGTM

**Comment by nikhiljindal** [comment]
LGTM

**Comment by janetkuo** [comment]
@k8s-oncall is @k8s-merge-robot doing the right thing here?

**Comment by nikhiljindal** [comment]
the merge bot does not work for gh-pages branch.
Removing the LGTM tag. Will add it when we are ready to merge this.

**Comment by janetkuo** [comment]
Added link to sitemap based on suggestions found here http://www.advancedhtml.co.uk/robots-sitemaps.htm

**Comment by janetkuo** [comment]
merging this for v1.1 release

**Pull request merged**
