### PR TITLE
kubelet: Replace deprecated pointer function

### PR DESCRIPTION
**Pull request by tmilox**
Signed-off-by: TommyStarK <thomasmilox@gmail.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

If applied this commit will replace the deprecated `(Int32|Int64|Float64|Bool|String)Ptr` function by `Int32|Int64|Float64|Bool|String`.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Comment by TommyStarK** [comment]
following instructions from k8s-ci-robot

/assign thockin

**Pull request merged**
