### PR TITLE
Make Restart e2e regex more specific so that it doesn't accidentally …

### LINKED ISSUE #13996: DaemonRestart test is not run in the kubernetes-e2e-gce-flaky builds
DaemonRestart tests are marked as flaky, but they are not run in the kubernetes-e2e-gce-flaky builds

E.g., In http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-flaky/5060/consoleFull, the args passed to ginkgo is
```
 '--ginkgo.skip=Autoscaling\sSuite|Skipped|Reboot|Restart|Example|Reboot' '--ginkgo.focus=DaemonRestart|ResourceUsage|monotonically\sincreasing\srestart\scount|should\sbe\sable\sto\schange\sthe\stype\sand\snodeport\ssettings\sof\sa\sservice|allows\sscheduling\sof\spods\son\sa\sminion\safter\sit\srejoin
```

Could it be that "DaemonRestart" also matches "Restart" in `--ginkgo.skip` and gets skipped always? 

/cc @quinton-hoole

### PR DESCRIPTION
**Pull request by ghost**
…match DaemonRestart.

Fixes #13996

### CODE REVIEW

**Comment by yujuhong** [comment]
Thanks for the quick fix!

It'd be nice to prevent regression, but I'm not sure that there's any easy way to check this.

**Comment by quinton-hoole** [comment]
e2e flake was a github pull failure again.  
```
 > git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/pull/*:refs/remotes/origin/pr/* --prune
ERROR: Timeout after 10 minutes
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/kubernetes/kubernetes
```

@ixdy is looking into it.  Retrying in the mean time.

@k8s-bot test this again please.

**Comment by ixdy** [comment]
OK, confirmed that upgrading Jenkins and its plugins doesn't fix the issue. Will upgrade the VM size next...

**Comment by quinton-hoole** [comment]
Another similar failure to fetch from github.  Retrying.

```
  > git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/pull/*:refs/remotes/origin/pr/* --prune
17:59:02 ERROR: Error fetching remote repo 'origin'
17:59:08 hudson.plugins.git.GitException: Failed to fetch from https://github.com/kubernetes/kubernetes
```

@k8s-bot please test this again

**Comment by alex-mohr** [comment]
Another #14074 unable to pull github.
Given one pass and eyeballing safety, manually merging.

**Pull request merged**
