### PR TITLE
Fix a condition to stop spammy logs #5209

### PR DESCRIPTION
**Pull request by gmarek**

### CODE REVIEW

**Comment by wojtek-t** [comment]
The shippable failure doesn't seem to be related to your change, but can you please double check it?

**Comment by gmarek** [comment]
I rerun Shippable. It's a flake.

**Comment by vmarmol** [comment]
LGTM, Thanks @gmarek! This was annoying yesterday.

@yujuhong looks like this was changed in your [commit](https://github.com/GoogleCloudPlatform/kubernetes/pull/5103/files#diff-0d64fd1b097fff84be9e16633e6acf20). I don't think it was intended? Holding off on merge in case we're missing something :)

**Comment by yujuhong** [comment]
@gmarek, @vmarmol, could you explain why this is causing too much spam? The change was intended (and I should've fixed the comment too).

After my change, the containers names should have 6 parts (delimited by underscore):
`k8s_<container_name>_<pod_name>_<pod_namespace>_<hash>_<rand>`
Kubelet will not be able to recognize the old containers. It is likely that you have old k8s container that haven't been removed yet, hence the spamming. Could you try removing them? Thanks!

**Comment by vmarmol** [comment]
@yujuhong ah I see, thanks for the clarification! I thought I was missing something. This is a clean install of a new cluster from HEAD. I suspect the issue is that the container-vm image already comes pre-loaded with a Kubelet and a cAdvisor manifest. Before we install the new Kubelet, the old one starts the cAdvisor which is then unrecognized by the new Kubelet. Will file an issue.

@gmarek I am closing this PR and filing an issue, we'll continue there.

**Pull request closed without merging**
