### PR TITLE
Add python-client to supported client list

### PR DESCRIPTION
**Pull request by mbohlool**
Client is in development and soon to be released out of alpha, but it is supported. I would like to add it to this list so it gets more attraction.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37719)

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37719)

**Comment by bgrant0607** [comment]
@mbohlool Please close this and resubmit to community repo.

**Comment by mbohlool** [comment]
Do you mean here? https://github.com/kubernetes/community/blob/master/contributors/devel/client-libraries.md

Is there any document explaining the process of changing files like this and how often they will be merged back into main repo?

**Comment by bgrant0607** [comment]
@mbohlool The files in the kubernetes repo will be deleted.

**Pull request closed without merging**
