### PR TITLE
fix OldReplicaSets in `kubectl describe deploy`

### PR DESCRIPTION
**Pull request by llorllale**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

This PR makes `kubectl describe deploy [name]` add names of all replicasets to `OldReplicaSets` regardless if they are in they have active pods or not.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
When describing deployments, `OldReplicaSets` now always shows all replicasets controlled the deployment, not just those that still have replicas available.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by llorllale** [comment]
Hey @dougsland @soltysh - any chance this small PR can be reviewed soon?

**Comment by dougsland** [comment]
> Hey @dougsland @soltysh - any chance this small PR can be reviewed soon?

Sure, just triggered the `ok-to-test` to start.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
