### PR TITLE
Add continue for shortcut

### LINKED ISSUE #117068: Here need to add "continue" sig/storage
https://github.com/kubernetes/kubernetes/blob/d89d5ab2680bc74fe4487ad71e514f4e0812d9ce/pkg/apis/core/validation/validation.go#L4074

### PR DESCRIPTION
**Pull request by haoruan**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Add continue for shortcut
#### Which issue(s) this PR fixes:

Fixes #117068

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by carlory** [comment]
Hi @haoruan , here is [xing-yang's comment](https://github.com/kubernetes/kubernetes/issues/117068#issuecomment-1523788563) about the issue. If you think it's still needed, please comment on the issue.

**Comment by haoruan** [comment]
Got it, thanks

**Pull request closed without merging**
