### PR TITLE
Moving example JSON files to /examples/ directory; update test

### PR DESCRIPTION
**Pull request by MikeJeffrey**
https://github.com/GoogleCloudPlatform/kubernetes/issues/2633

### CODE REVIEW

**Comment by erictune** [comment]
I see the deletes but not the adds in this PR.

**Comment by MikeJeffrey** [comment]
I think I have the files correct now, but with duplicate commit messages. Not sure how to fix those.

**Comment by bgrant0607** [comment]
Sorry, see #5039

**Comment by bgrant0607** [comment]
```
F0304 19:19:13.174317   25748 integration.go:278] Unexpected error: open api/examples/controller.json: no such file or directory
```

**Comment by bgrant0607** [comment]
There are other references, also:
https://github.com/GoogleCloudPlatform/kubernetes/search?utf8=%E2%9C%93&q=api%2Fexamples

**Pull request closed without merging**
