### PR TITLE
stop using pkg/errors in cmd

### PR DESCRIPTION
**Pull request by Haleygo**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
We should be using Go native error wrapping instead of github.com/pkg/errors, get them fixed in cmd but not touching cmd/kubeadm

#### Which issue(s) this PR fixes:

Fixes # Part of https://github.com/kubernetes/kubernetes/issues/103043

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
kubeadm is out of scope - see the notes in https://github.com/kubernetes/kubernetes/issues/103043
you can leave only the kube-proxy changes.

**Comment by Haleygo** [comment]
> kubeadm is out of scope - see the notes in #103043
> you can leave only the kube-proxy changes.

drop cmd/kubeadm now, thanks for reminding

**Comment by Haleygo** [comment]
@dcbw @RA489 Can you guys help to review this? thanks a lot :)

**Comment by Haleygo** [comment]
@aojea Can you help review this little change? 
thanks :)

**Pull request closed without merging**
