### PR TITLE
migration from go-spew to kr/pretty

### LINKED ISSUE #103942: Should we remove go-spew from the dependency as it seems be abandoned
#### What would you like to be added:
Replace [github.com/davecgh/go-spew][1] with its alternatives, like:
- https://github.com/kr/pretty

#### Why is this needed:
Seems the `github.com/davecgh/go-spew` [has been abandoned][3], the last commit happened in the year 2018.
The effect, such as:
- The library still does not support `Go Module`
- Some [panic(issues)][2] not be handled for a long time.

[1]:https://github.com/davecgh/go-spew
[2]:https://github.com/davecgh/go-spew/issues
[3]:https://github.com/davecgh/go-spew/issues/128

### PR DESCRIPTION
**Pull request by mcbenjemaa**
Signed-off-by: Mohamed Chiheb <mc.benjemaa@gmail.com>

WIP
#### What type of PR is this?
/kind cleanup
/sig architecture
/area code-organization

#### Which issue(s) this PR fixes:

Fixes #103942

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mcbenjemaa** [comment]
Test succeeded.

Great, I can move forward and complete the migration.

**Comment by liggitt** [comment]
I'm not sure this is a net benefit, given github.com/davecgh/go-spew is still required by things under vendor, so we can't drop it yet

**Comment by mcbenjemaa** [comment]
> I'm not sure this is a net benefit, given github.com/davecgh/go-spew is still required by things under vendor, so we can't drop it yet


@liggitt Although, I think we gotta start remove it from the codebase.

**Comment by serathius** [comment]
Aside of dependency cleanup I think that we should not use marshallers like spew or kr/pretty. Looks like we use them mostly in test code to provide debug information, however this is somewhat incompatible with how we marshal objects in non-test code. We are investing a lot of effort info migrating k/k logging to Structured logging where marshalling is delegated to logging library. I think we should make sure that we don't create two separate worlds, one using klog.InfoS and other using kr/pretty.

This is something that needs a broader discussion between WG Structured logging & SIG testing, where we would agree on what needs to be done to stop using custom marshallers in tests. I also don't see net benefit if we are not removing spew as dependency.

**Comment by dims** [comment]
Is this PR still needed, please rebase if so (or we can close it?)

**Comment by mcbenjemaa** [comment]
I think still needed.
 I'm waiting to remove `spew` from `kustomise` as it seems that's being referenced from the vendor of k/k.

**Comment by dims** [comment]
thanks @mcbenjemaa will check back in a couple of weeks and close it. we can always re-open later.

**Pull request closed without merging**
