### PR TITLE
Tag smd properly for kubernetes 1.17

### PR DESCRIPTION
**Pull request by apelisse**
Update `sigs.k8s.io/structured-merge-diff` to use v2 (and specifically v2.0.1), and also update `kube-openapi` to use a compatible version. This is needed in order to backport the latest v2 version of SMD that fixes the no-op apply bug.

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by lavalamp** [comment]
Can you modify the description/release note to explain what this accomplishes?

**Comment by lavalamp** [comment]
/lgtm
/approve

Thanks!

**Comment by justaugustus** [comment]
Ping @kubernetes/patch-release-team

**Comment by apelisse** [comment]
Ping @kubernetes/patch-release-team

This is blocking the actual useful things we have to prepare for the next relase.

**Pull request merged**
