### PR TITLE
Fix k8sm flaky UT.

### LINKED ISSUE #25349: unit flake: TestDQ_sanity_check is flaky
Failure:

    --- FAIL: TestDQ_sanity_check (2.01s)
	delay_test.go:137: delay too short: 1.881104721s, expected: 2s
    --- PASS: TestDFIFO_sanity_check (2.06s)
    --- PASS: TestDQ_ordered_add_pop (3.13s)
    FAIL
    FAIL	k8s.io/kubernetes/contrib/mesos/pkg/queue	3.453s

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/25344/kubernetes-pull-test-unit-integration/24932/build-log.txt

### PR DESCRIPTION
**Pull request by k82cn**
fixes #25349

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33364)

### CODE REVIEW

**Comment by k82cn** [comment]
ping @jdef , any comments?

**Comment by jdef** [comment]
Not convinced that this will fix anything. It's a flake because when build systems get slow tests that depend on specific timing based on the real clock (vs a fake one) may fail.

**Comment by k82cn** [comment]
The PR will fix the issue, because it'll record the time before starting timer. Refer to the description in issue:

>Here maybe the root case after reviewing the code: the TestDQ_sanity_check do the following steps:
>
>1. add testJob into DelayedQueue
>1. get current time (before := time.Now())
>1. pop item from DelayedQueue
>1. get current time (now := time.Now())
>1. check the wait period (now.Sub(before))
>
>The problem is that: the timer start at "Step 1" in q.Add() of  DelayedQueue, if there's any delay between "Step 1" & "Step 2", the wait period will be shorter than expected. The proposed PR is to record time before adding item.

**Comment by jdef** [comment]
OK, re-read everything. With your changes the test will now time (add+pop) operations. Which should be greater than `delay` in a sane world. Thanks for submitting this.

**Comment by jdef** [comment]
lgtm

**Comment by jdef** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33364)*

**Pull request merged**
