### PR TITLE
CRI: update documents for container logpath

### PR DESCRIPTION
**Pull request by feiskyer**
**What this PR does / why we need it**:

The container log path has been changed from  `containername_attempt#.log` to `containername/attempt#.log` in #59906. This PR updates CRI documents for it.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
CRI: update documents for container logpath. The container log path has been changed from containername_attempt#.log to containername/attempt#.log 
```

### CODE REVIEW

**Comment by feiskyer** [comment]
ping @Random-Liu @dchen1107

**Comment by feiskyer** [comment]
ping @Random-Liu @dchen1107

**Comment by feiskyer** [comment]
ping @yujuhong @Random-Liu

**Comment by yujuhong** [comment]
Thanks! lgtm 

Can you add a release note so we can patch 1.10?

**Comment by feiskyer** [comment]
@yujuhong release note added. PTAL

**Pull request merged**
