### PR TITLE
upgrade sigs.k8s.io/structured-merge-diff/v4 to v4.2.1

### LINKED ISSUE #104641: Incorrect initContainers order when using server-side apply
#### What happened:

The order of `initContainers` is significant, but when using `kubectl apply --server-side` to change this field, the intended order is not preserved.

#### What you expected to happen:

I expected the order of `initContainers` to match my submitted intent.

#### How to reproduce it (as minimally and precisely as possible):

Files:

```yaml
==> 00.yaml <==                                                            
apiVersion: v1
kind: Service
metadata:                                                                  
  name: init-container-order
spec:                
  clusterIP: None                                                          
---                                                                        
apiVersion: apps/v1                                                        
kind: StatefulSet
metadata:                                                                  
  name: init-container-order
spec:
  serviceName: init-container-order
  selector:
    matchLabels: { name: init-container-order }
  template:
    metadata:
      labels: { name: init-container-order }
    spec:
      initContainers:
      - { image: busybox, name: original }
      containers:
      - { image: busybox, name: main }

==> 01.yaml <==
apiVersion: v1
kind: Service
metadata:
  name: init-container-order
spec:
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: init-container-order
spec:
  serviceName: init-container-order
  selector:
    matchLabels: { name: init-container-order }
  template:
    metadata:
      labels: { name: init-container-order }
    spec:
      initContainers:
      - { image: busybox, name: first }
      - { image: busybox, name: original }
      - { image: busybox, name: last }
      containers:
      - { image: busybox, name: main }
```

```diff
● diff -u 00.yaml 01.yaml 
--- 00.yaml     2021-08-27 20:39:10.000000000 -0500
+++ 01.yaml     2021-08-27 20:39:08.000000000 -0500
@@ -18,6 +18,8 @@
       labels: { name: init-container-order }
     spec:
       initContainers:
+      - { image: busybox, name: first }
       - { image: busybox, name: original }
+      - { image: busybox, name: last }
       containers:
       - { image: busybox, name: main }
```

---

Create the StatefulSet and see it has one init container:

```
● kubectl apply --server-side -f 00.yaml 
service/init-container-order serverside-applied
statefulset.apps/init-container-order serverside-applied

● kubectl get sts/init-container-order -o jsonpath='{.spec.template.spec.initContainers[*].name}{"\n"}'
original
```

Add two more init containers, one before and one after the original. See that they are **both added to the end**:

```
● kubectl apply --server-side -f 01.yaml 
service/init-container-order serverside-applied
statefulset.apps/init-container-order serverside-applied

● kubectl get sts/init-container-order -o jsonpath='{.spec.template.spec.initContainers[*].name}{"\n"}'
original first last
```

#### Anything else we need to know?:

`kubectl replace` puts them in the intended order:

```
● kubectl replace -f 01.yaml 
service/init-container-order replaced
statefulset.apps/init-container-order replaced

● kubectl get sts/init-container-order -o jsonpath='{.spec.template.spec.initContainers[*].name}{"\n"}'
first original last
```

#### Environment:
- Kubernetes version (use `kubectl version`):
  ```
  Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:56:19Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4+k3s1", GitCommit:"3e250fdbab72d88f7e6aae57446023a0567ffc97", GitTreeState:"clean", BuildDate:"2021-08-19T19:09:53Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Install tools: `k3d`, `brew install kubernetes-cli`

/sig api-machinery

### PR DESCRIPTION
**Pull request by jiahuif**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This PR upgrade `sigs.k8s.io/structured-merge-diff/v4` v4.2.1

#### Which issue(s) this PR fixes:

Fixes #104641
Replaces #105983
#### Does this PR introduce a user-facing change?

```release-note
kube-apiserver: when merging lists, Server Side Apply now prefers the order of the submitted request instead of the existing persisted object
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig api-machinery

### CODE REVIEW

**Comment by liggitt** [comment]
glad to see the test change in test/integration/client/client_test.go from https://github.com/kubernetes/kubernetes/pull/105983 wasn't needed with this PR

will defer review to @apelisse and can approve the dep update once this has lgtm

**Comment by apelisse** [comment]
Awesome, thanks!
/lgtm
/approve

**Comment by jiahuif** [comment]
@liggitt Actually, I forgot to update the integration test, because the order in the test was wrong.
What the test expects:
`{nginx} apply {sidecar} = {sidecar, nginx}`
what we want
`{nginx} apply {sidecar} = {nginx, sidecar}`

The test was written with no assumption about the order. Now that we fix the ordering issue, we should enforce it in the test as well.

**Comment by apelisse** [comment]
Yeah, reading the test, it looks like side-car was applied first and then nginx. So we should have nginx last which is what we have now.
/lgtm

**Comment by cbandy** [comment]
I see container env vars have the same merge strategy as init containers. Does this change address the ordering of both fields?

**Comment by jiahuif** [comment]
Yes it does! Under the hood they are both using the list merge algorithm.

> I see container env vars have the same merge strategy as init containers. Does this change address the ordering of both fields?

**Pull request merged**
