### PR TITLE
Automated cherry pick of #46660

### PR DESCRIPTION
**Pull request by seanknox**
Cherry pick of #46660 on release-1.6.

#46660: Azure cloudprovider retry using flowcontrol

### CODE REVIEW

**Comment by seanknox** [comment]
cc @jdumars

**Comment by caesarxuchao** [comment]
/assign @enisoc 

enisoc is the 1.6 release manager.

**Comment by enisoc** [comment]
Since this is contained to azure cloudprovider, it's ok with me as long as the OWNERS /approve.

**Comment by seanknox** [comment]
@jackfrancis with this cherry-pick back into v1.6 looks like some dependency probs maybe?

**Comment by jackfrancis** [comment]
@seanknox Try running `./hack/update-bazel.sh` on your branch and pushing the changed files as a follow-up commit.

**Comment by seanknox** [comment]
That was the trick, thanks @jackfrancis. @brendandburns @colemickens v1.6 backport of Azure cloud provider backoff ready for your review.

**Comment by jdumars** [comment]
@brendandburns or @colemickens could you look this over and LGTM if it LGTY?

**Comment by jdumars** [comment]
Thank you everyone!

**Pull request merged**
