### PR TITLE
Update kustomize.md

### PR DESCRIPTION
**Pull request by fgogolli**
Fix typo on nameName vs newName
Fix documentation bug on SecretGeneratorArgs

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Documentation fix.

**Which issue(s) this PR fixes**:

Fixes #

Fix typo on nameName vs newName

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
> This PR fixes a documentation typo in the kustomize reference page of kubectl.

please change this to `NONE`

**Review by neolit123 — COMMENTED** [review]
/lgtm
/priority backlog
/ok-to-test

i think i saw a similar PR for this submitted already?
maybe it hasn't merged yet.

**Review by soltysh — CHANGES_REQUESTED** [review]
/approve
@fgogolli please squash your changes to a single commit

**Comment by fgogolli** [comment]
@soltysh It should be good now, sorry for the double push.
@eddiezane Thanks very much for the headsup!

.. and thanks to both for the merge! 👍

**Pull request merged**
