### PR TITLE
e2e: backport regenerate namespace name if the name is already taken …

### PR DESCRIPTION
**Pull request by ScrapCodes**
…#90591

**What type of PR is this?**

/kind flake
**What this PR does / why we need it**:
It fixes the flaky test in skew jobs which run the old code, by applying the fix offered in #90591. 
This PR backports to branch release-1.18
**Which issue(s) this PR fixes**:

#94520

**Special notes for your reviewer**:
There is another PR for branch release-1.17 #94717
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by ScrapCodes** [comment]
Hi @knight42, please take a look here as well.

Thanks !

**Review by knight42 — APPROVED** [review]
/ok-to-test

lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm
/priority important-soon

**Comment by tpepper** [comment]
@neolit123 did you intend to also approve this one on 1.18  in addition to https://github.com/kubernetes/kubernetes/pull/94717 on 1.17?  Would be weird to have 1.19 and 1.17 fixed but not 1.18...?

**Pull request merged**
