### PR TITLE
remove duplicate code

### PR DESCRIPTION
**Pull request by gongguan**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
clean duplicate code
duplicate code between [here](https://github.com/kubernetes/kubernetes/blob/81a8b9804a3bf310cb74446bd8a8e08e0317de22/pkg/controller/endpoint/endpoints_controller.go#L195) and [there](https://github.com/kubernetes/kubernetes/blob/81a8b9804a3bf310cb74446bd8a8e08e0317de22/pkg/controller/util/endpoint/controller_utils.go#L84)
maybe the author forget to clean old code.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
clean duplicate GetPodServiceMemberships function
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by gongguan** [comment]
/assign @bowei 
please take a look

**Review by MrHohn — APPROVED** [review]
/lgtm
/approve
cc @robscott

**Comment by gongguan** [comment]
@MrHohn feel sorry for not removing related dependency.
Could you please label lgtm again?

**Comment by MrHohn** [comment]
Yep, no worries
/lgtm

**Pull request merged**
