### PR TITLE
Delete PSP API types and generated clients

### PR DESCRIPTION
**Pull request by enj**
/kind cleanup
/triage accepted

```release-note
NONE
```

### CODE REVIEW

**Comment by rikatz** [comment]
Shouldn't the tags of lifecycle be kept? I though that even deleting the API and its registration, the lifecycle tags should be maintained for warnings, etc.

**Comment by liggitt** [comment]
> the lifecycle tags should be maintained for warnings

No, the warnings are issued server-side. If the API is no longer being served, there is nothing emitting warnings on use any more.

**Pull request merged**
