### PR TITLE
rkt: return non error if the pod doesn't exist in GetPodStatus()

### PR DESCRIPTION
**Pull request by yifan-gu**
Previously, GetPodStatus() will return error if the pod is never
created. However we've never seen the sync loop fail because in the
beginning of the loop, if the pod is not found, it will be created.

This works fine except the pod that keeps crashing. Because the above
logic will keep restarting the pod as if it's never created.

This PR fixes the bug.

/cc @dchen1107 @yujuhong

### CODE REVIEW

**Comment by yujuhong** [comment]
This makes the code behaves more like the docker counterpart.. :)
Kicked off shippable again.

**Comment by yujuhong** [comment]
@k8s-bot ok to test

**Comment by yujuhong** [comment]
rkt is not tested in e2e yet.

**Comment by yifan-gu** [comment]
Anyway will need to rebase after #14686

**Pull request merged**
