### PR TITLE
fix typo and format for klog

### PR DESCRIPTION
**Pull request by pandaamanda**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
@pandaamanda could you update the release note block in the PR body to read `NONE` instead of `Node` :)

/retest

**Comment by pandaamanda** [comment]
> @pandaamanda could you update the release note block in the PR body to read `NONE` instead of `Node` :)
> 
> /retest

**Comment by pandaamanda** [comment]
> @pandaamanda could you update the release note block in the PR body to read `NONE` instead of `Node` :)
> 
> /retest

already updated.

**Pull request closed without merging**
