### PR TITLE
Remove unversioned selectors

### PR DESCRIPTION
**Pull request by wojtek-t**

### CODE REVIEW

**Comment by wojtek-t** [comment]
@smarterclayton - one more small cleanup PR - can you please take a look?

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by smarterclayton** [comment]
LGTM

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by gmarek** [comment]
@k8s-bot unit test this

**Comment by gmarek** [comment]
@k8s-bot unit test this

**Pull request merged**
