### PR TITLE
spelling error 'doen't'

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jsafrane** [comment]
Can you please put all your spelling fixes into one PR / commit? It makes little sense to have a separate commit for each word you fix.

**Review by alejandrox1 — COMMENTED** [review]
Thank you for the PR @qingsenLi 

/lgtm
/priority backlog
/milestone v1.17
/remove-lifecycle rotten
/cc @kubernetes/sig-storage-pr-reviews

**Comment by alejandrox1** [comment]
/cc @msau42 
could you please take a look?

**Comment by alejandrox1** [comment]
/cc @kubernetes/sig-storage-pr-reviews 
ptal

**Pull request merged**
