### PR TITLE
fix typo in daemon

### PR DESCRIPTION
**Pull request by yarntime**
fix typo in daemon.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37617)

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by bgrant0607** [comment]
@k8s-bot kops aws e2e test this

**Comment by apelisse** [comment]
@k8s-bot bazel test this

**Comment by bgrant0607** [comment]
@apelisse Why is the merge bot unassigning people from the PR?

**Review by janetkuo — APPROVED** [review]

**Comment by janetkuo** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
