### PR TITLE
Generate kubeadm referencedoc and man pages

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
Improve kubeadm reference doc and start generating kubeadm man pages.
With this PR, also kubeadm will start following the same approach used by other tools

**Which issue this PR fixes** 
initial work for [#265](https://github.com/kubernetes/kubeadm/issues/265)

**Special notes for your reviewer**:
This [document](https://docs.google.com/document/d/1w22y-C1YD1mmqqETxrQrCLnJpzwttscanddgvfYceYY/edit?usp=sharing)  contains the design proposal for how to implement this goal, that will be implemented partially in https://github.com/kubernetes/kubernetes (this PR) and partially in https://github.com/kubernetes/website

In order to keep the PR as small and clean possible I didn't generated new placeholders files under `/docs/man` and `/docs/admin` at this stage. If this is necessary, I will do this later in this PR or eventually in another PR; however, if this is not strictly necessary, IMO we should avoid to pollute this repo with placeholders to file that are maintained in another repo.

cc @kubernetes/sig-docs-maintainers @Bradamant3 @heckj

### CODE REVIEW

**Comment by mkumatag** [comment]
Fix the error for `./hack/verify-generated-docs.sh` script
```
I1026 09:29:48.761] List of generated docs doesn't match a freshly built list. Please run hack/update-generated-docs.sh
```

/cc @luxas

**Comment by lavalamp** [comment]
If it is going to live here, we should generate man pages.

/approve

(fix tests please)

**Comment by mkumatag** [comment]
@fabriziopandini add release note - https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#write-release-notes-if-needed

**Comment by luxas** [comment]
Thanks @fabriziopandini!

**Pull request merged**
