### PR TITLE
Do not set CNI in cases where there is a private master and network policy provider is set.

### PR DESCRIPTION
**Pull request by dnardo**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
In GCE and in a "private master" setup, do not set the network-plugin provider to CNI by default if a network policy provider is given.
```

### CODE REVIEW

**Comment by dnardo** [comment]
ping @dchen1107

**Comment by caseydavenport** [comment]
@dnardo where is the KUBERNETES_PRIVATE_MASTER variable defined?

Do we need to add an entry here? https://github.com/dnardo/kubernetes/blob/00b62df55483a8addb71af69db5ca413ac5f9863/cluster/common.sh#L586

**Comment by dchen1107** [comment]
/lgtm

This is purely GKE related feature, not introducing the risk the OSS K8S release.

**Comment by dchen1107** [comment]
@dnardo Please create a cherrypick pr for 1.7 release. Thanks!

**Comment by cmluciano** [comment]
/retest

federation build rbac rule errors

**Pull request merged**
