### PR TITLE
Refactor kubelet server into its own package

### PR DESCRIPTION
**Pull request by timstclair**
Refactor Kubelet's server functionality into a server package. Most
notably, move pkg/kubelet/server.go into
pkg/kubelet/server/server.go. This will lead to better separation of
concerns and a more readable code hierarchy.

/cc @kubernetes/goog-node

### CODE REVIEW

**Comment by yujuhong** [comment]
LGTM. Thanks for the cleanup!

**Comment by dchen1107** [comment]
Nice! LGTM

**Comment by yujuhong** [comment]
@k8s-bot unit test this

**Comment by timstclair** [comment]
@k8s-bot unit test this

**Comment by timstclair** [comment]
Rebased.

**Pull request merged**
