### PR TITLE
Revert "Copy and display source location prominently on Kubernetes instances"

### PR DESCRIPTION
**Pull request by gmarek**
Reverts kubernetes/kubernetes#27840

This broke cluster upgrade, ref https://github.com/kubernetes/kubernetes/issues/27764#issuecomment-227971330. cc @janetkuo @zmerlynn

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

**Comment by wojtek-t** [comment]
@davidopp

**Comment by wojtek-t** [comment]
LGTM

**Comment by piosz** [comment]
@zmerlynn before re-adding this please make sure that `cluster/gce/upgrade.sh` is working.

**Pull request merged**
