### PR TITLE
turn on and off watch cache in integration test

### LINKED ISSUE #21096: hack/test-integration.sh should turn on watch cache
@kubernetes/goog-csi @lavalamp

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #21096 

@lavalamp @wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Comment by caesarxuchao** [comment]
@k8s-bot e2e test this please. Issue: #21178

**Comment by caesarxuchao** [comment]
@k8s-oncall, I've filed #21178 and include the issue in my test request. Don't know why k8s-bot still complains about missing issue number, and why it removes my comment.

**Comment by mikedanese** [comment]
Sounds like https://github.com/kubernetes/kubernetes/pull/21089#issuecomment-183045712

**Pull request merged**
