### PR TITLE
Automated cherry pick of #88006: Unregister csiplugin even if socket path is gone #89934: Simplify unregistration of csiplugin

### LINKED ISSUE #87282: kubelet can't unregister csiplugin after csiplugin pod is deleted from node
**What happened**:
```
Error: "UnregisterPlugin error -- dial failed at socket /var/lib/kubelet/plugins_registry/xxx-reg.sock, err: failed to dial socket /var/lib/kubelet/plugins_registry/xxx-reg.sock, err: context deadline exceeded"
```

Before deleting csiplugin pod, we will firstly remove register unix domain socket </var/lib/kubelet/plugins_registry/xxx-reg.sock>, which will trigger kubelet unregister csiplugin.
After we update our k8s cluster from v1.14.3 to v1.16.3, I noticed that above error logs, meanwhile `kubectl get csinode node-xxx`, I can see old plugin in spec.drivers list but it should not(The error does not happen in v1.14.3).

**What you expected to happen**:
csiplugin can be unregistered by kubelet exactly，and there are no error logs.

**How to reproduce it (as minimally and precisely as possible)**:
deploy csinode daemonset as describing at [here](https://github.com/kubernetes-csi/node-driver-registrar#example)

**Anything else we need to know?**:
maybe this issue was imported by the [commit](https://github.com/kubernetes/kubernetes/commit/5e185544421d5504b0fe2ae32c8ebfb3000a1224)
And after reading code implementation, I find kubelet will dial unix domain socket <var/lib/kubelet/plugins_registry/xxx-reg.sock> when it's trigger by removing xxx-reg.sock, which is confusing

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by tedyu**
Cherry pick of #88006 #89934 on release-1.18.

#88006: Unregister csiplugin even if socket path is gone
#89934: Simplify unregistration of csiplugin

/kind bug

Fixes #87282

```release-note
NONE
```

### CODE REVIEW

**Comment by mattjmcnaughton** [comment]
@tedyu can you share more around the impact this is having on users? If its a great impact, we might want to cherry-pick to 1.16 and 1.17 as well. Alternatively, if its fairly small, it might not need to be cherry-picked at all.

**Comment by tedyu** [comment]
The impact of not fixing the bug is quite big: csiplugin cannot be unregistered.

**Comment by mattjmcnaughton** [comment]
On Mon, Apr 13, 2020 at 07:18:37PM -0700, Zhihong Yu wrote:
> The impact of not fixing the bug is quite big: csiplugin cannot be unregistered.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/90125#issuecomment-613189085

Ok - is the bug present in 1.16 and 1.17? Worth cherry-picking to those
releases?

**Comment by tedyu** [comment]
@taragu 
Can you let us know which branches your commit went to ?
https://github.com/kubernetes/kubernetes/commit/5e185544421d5504b0fe2ae32c8ebfb3000a1224

thanks

**Comment by tedyu** [comment]
@saad-ali 
Can you take a look ?

**Comment by saad-ali** [comment]
> @taragu
> Can you let us know which branches your commit went to ?
> 5e18554
> 
> Looks like it is in 1.18 and 1.17

1.15, 1.16, 1.17, and 1.18

**Pull request merged**
