### PR TITLE
Split AsVersionedObjects so it can be reused

### PR DESCRIPTION
**Pull request by smarterclayton**
Some commands want the functionality but not a runtime.Object

### CODE REVIEW

**Comment by saad-ali** [comment]
Assigning to @bgrant0607 for v1.0 triage. Please re-assign as appropriate.

**Comment by smarterclayton** [comment]
This is not critical for us because we're carrying it as a patch - can be post 1.0

----- Original Message -----

**Comment by bgrant0607** [comment]
LGTM.

**Comment by bgrant0607** [comment]
This is small/simple, and tests pass, so it can go in.

**Pull request merged**
