### PR TITLE
Fix eTP:Local NodePort test

### PR DESCRIPTION
**Pull request by danwinship**
#### What type of PR is this?
/kind cleanup
/kind failing-test

#### What this PR does / why we need it:
Fixes the `externalTrafficPolicy: Local` NodePort test to:
1. not be part of the LoadBalancer suite, since it's not a LoadBalancer test
2. not assume that pod-to-other-node-IP traffic will be unmasqueraded (so it is not GCE-specific, as the original was)
3. ensure that the client and endpoint are on different nodes, so that a hostNetwork-to-NodePort connection is guaranteed to use the node's "public" IP rather than some internal pod-network IP.
4. work with IPv6

(Split out of  #124729 which has gotten messy and will probably get closed.)

(The conversion from `utilpointer` to `ptr` was done while I was testing another change that needed to use `ptr`, but then I ended up reverting that part, but I left in the cleanup...)

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/sig network
/triage accepted
/priority important-soon

### CODE REVIEW

**Comment by aojea** [comment]
/retest
it seems this PR hit all possible flakes 😅 

I think this test carried with the assumption that ExternalTrafficPolicy: Local == Source IP preservation, when that is a consequence of that implementation since it avoids masquerading external traffic ... but in this case the traffic is internal and  as you well explain this can be different depending the implementation

/lgtm
/approve

**Comment by danwinship** [comment]
> but in this case the traffic is internal and as you well explain this can be different depending the implementation

To be clear, the implementation-dependentness here is not with the service proxy's implementation of externalTrafficPolicy, it's with the pod network's implementation of pod-to-other-node traffic. In pod networks with routable/externally-visible pod IPs (like GCE), traffic to other nodes doesn't need to be masqueraded, but in most pod networks with private/internal-only pod IPs (like kindnet), any pod traffic that leaves the node gets masqueraded (even if it's going to another node). So the test was failing in kind because the original source IP had already been masqueraded away before the packet even reached the eTP:Local NodePort.

**Comment by aojea** [comment]
Yeah, I was referring to the Pod network but the comment was not clear, thanks for the correction and the detailed explanation

**Pull request merged**
