### PR TITLE
Revert "It fixes a bug where AAD token obtained by kubectl is incompa…

### LINKED ISSUE #87464: Azure AD: Migration path from 1.17.0 to 1.17.1
**What happened**:
Kubernetes 1.17.1 included a breaking change to how Azure AD may be used for OIDC authentication in Kubernetes: https://github.com/kubernetes/kubernetes/pull/86412 For all teams which were successfully using Azure AD's implementation of OIDC in Kubernetes previously, this change means:
- `>=1.17.1 clusters are only compatible with >=1.17.1 kubectl versions and client libraries`
- `<=1.17.0 clusters are only compatible with <= 1.17.0 kubectl versions and client libraries`

Notably, this includes not only teams who directly use AAD, but also all AKS clusters. See https://github.com/Azure/aks-engine/issues/2582.

**What you expected to happen**:
Associated with a breaking change, **a migration path should be provided**. In this case (and as currently released), both the apiserver and all clients of the apiserver need to simultaneously change versions to avoid impact. In larger deployments of Kubernetes, a single cluster may have hundreds (or more) of disparate clients. Such a large change cannot be reasonably executed without impacting customers and causing critical service outages.

This is a request for details on how cluster operators and Kubernetes users (that use Azure AD) should migrate from 1.17.0 to 1.17.1 without impact.

**How to reproduce it (as minimally and precisely as possible)**:
1. Launch a cluster on 1.17.0
2. Follow instructions here to tie into Azure AD: https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/plugin/pkg/client/auth/azure
3. Verify valid authn/authz with `kubectl <= 1.17.0`
4. Verify invalid authn/authz with `kubectl >= 1.17.1`
5. Repeat test with a 1.17.1 cluster and `kubectl` versions below 1.17.1

**Anything else we need to know?**:
The fact that this underlying functionality _should_ change is not disputed. (see the evidence in the original ticket https://github.com/kubernetes/kubernetes/issues/86410). Azure AD has improperly injected `spn:` into all JWT token `aud` fields for a long time now. The issue is not with the new functionality itself, but rather the manner in which the change was implemented. Without a designated migration path, this change is highly impactful to clients. 

**Environment**:
- Kubernetes version (use `kubectl version`): apiserver: 1.17.1, kubectl: 1.17.0 (and vice versa)
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: 

Tagging original author and approvers of the PR: @feiskyer @andyzhangx @enj

/sig cloud-provider
/area provider/azure

### PR DESCRIPTION
**Pull request by weinong**
…tible with on-behalf-of flow and oidc."

This reverts commit d1480ab49d603d0a95e509b627252ee7af8559ae.

Revert this commit due to incomplete migration path

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Previous change introduced a breaking behavior between kubectl and api-server with AzureAD OIDC. This PR reverts the change.

**Which issue(s) this PR fixes**:

Fixes #87464

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Reverted a kubectl azure auth module change where oidc claim spn: prefix was omitted resulting a breaking behavior with existing Azure AD OIDC enabled api-server
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
note that the breaking change was already cherry-picked to 1.15/1.16/1.17 as well

**Comment by andyzhangx** [comment]
@weinong  pls run `hack/update-gofmt.sh` to fix the error

**Comment by weinong** [comment]
@andyzhangx I ran `hack/update-gofmt.sh` but nothing got updated.. ?

**Review by feiskyer — COMMENTED** [review]
/retest

**Review by feiskyer — COMMENTED** [review]
/priority critical-urgent
/lgtm
/approve

**Comment by feiskyer** [comment]
@liggitt could you help to approve the changes?

/assign liggitt

**Comment by weinong** [comment]
@liggitt this revert PR also touched a file that added after my commit. that file was added in [this commit](https://github.com/kubernetes/kubernetes/commit/b264a7474814f55d82b3c1f2ba6edb6e14d117a9) but didn't get cherry-picked to 1.15, 1.16, and 1.17. Once this PR is merged, my cherry pick would not be straightforward. I guess I can fix it in my cherry pick PR?

**Comment by liggitt** [comment]
Yes, when you cherry-pick, you'll get a chance to resolve conflicts.

/retest

**Pull request merged**
