### PR TITLE
test-images: server address is now configurable

### PR DESCRIPTION
**Pull request by mzylowski**
This commit perform changes discussed in #32128
Should be merged before #35301

cc: @pskrzyns

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35302)

### CODE REVIEW

**Comment by ixdy** [comment]
@mzylowski can you please sign the CLA?

**Comment by ixdy** [comment]
@k8s-bot ok to test

**Comment by mzylowski** [comment]
I signed it!

**Comment by pskrzyns** [comment]
LGTM
@ixdy the new image will be automatically added to registry ?

**Comment by ixdy** [comment]
@pskrzyns no, someone will need to manually push it after this PR merges. I can do that.

**Comment by ixdy** [comment]
gcr.io/google_containers/portforwardtester:1.1 has been pushed.

**Comment by pskrzyns** [comment]
thx

**Pull request merged**
