### PR TITLE
Fix issue #55031 to remove dependence on package lxn/win

### LINKED ISSUE #55031: Kubelet.exe Crashes on Windows Server Core
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
kubelet.exe crashes on Windows Server Core. 

**What you expected to happen**:
Kubelet running and joining to the cluster.

**How to reproduce it (as minimally and precisely as possible)**:
Build kubelet.exe from master and run it on a machine with Core (UI-less).

**Anything else we need to know?**:
There was a dependency introduced in PR #50396 on [this package](https://github.com/lxn/win/). This loads `OpenGL32.dll`, which isn't present on the UI-less Windows Core variant, thus causing a panic:

    panic: The specified module could not be found.

    goroutine 1 [running]:
    k8s.io/kubernetes/vendor/github.com/lxn/win.MustLoadLibrary(0x34a64bd, 0xc, 0xc)
            .../local/go/src/k8s.io/kubernetes/vendor/github.com/lxn/win/win.go:48 +0x73
    k8s.io/kubernetes/vendor/github.com/lxn/win.init.8()
            .../local/go/src/k8s.io/kubernetes/vendor/github.com/lxn/win/opengl32.go:117 +0x41
    k8s.io/kubernetes/vendor/github.com/lxn/win.init()
            <autogenerated>:1 +0x81
    k8s.io/kubernetes/pkg/kubelet/winstats.init()
            <autogenerated>:1 +0x77
    ...

Though the package is necessary, OpenGL is not. lxn/win#23 is open on the package to be Core-friendly, but it doesn't seem to be going anywhere.

**Environment**:
- Kubernetes version (use `kubectl version`): Built from #51063 directly.
- Cloud provider or hardware configuration: n/a
- OS (e.g. from /etc/os-release): Windows Server Standard Core 1709
- Kernel (e.g. `uname -a`): 16299.15.amd64fre.rs3_release.170928-1534

### PR DESCRIPTION
**Pull request by JiangtianLi**
**What this PR does / why we need it**:
This PR fixes issue #55031 where kubelet.exe crashes on Windows Server Core. The root cause is that kubelet.exe depends on package lxn/win pdh and kernel32 wrapper for node metrics. However, opengl32.dll is not available in Server Core and lxn/win requires the presence of all win32 DLLs. 

This PR uses a slim win32 package JeffAshton/win_pdh since most win32 APIs needed are PDH API. Also this PR makes own implementation of GetPhysicallyInstalledSystemMemory until golang Windows syscall has it or lxn/win fixes opengl32 issue. 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #55031

**Special notes for your reviewer**:

**Release note**:

```release-note

```
/sig windows
/sig node

### CODE REVIEW

**Comment by brendandburns** [comment]
This LGTM, but do we usually pull in deps as git submodules? That seems odd.

**Comment by JiangtianLi** [comment]
@brendandburns I am not familiar with vendor dependence in k8s and I followed https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md and clone JeffAshton/win_pdh under vendor. I also ran hack/update-bazel.sh afterwards. Sorry if I didn't do the vendor correctly. I'll compare other vendor package and see.

**Comment by thockin** [comment]
Godeps changes seem OK.  I can't review this otherwise - Windows folks, PTAL.

**Comment by JiangtianLi** [comment]
pull-kubernetes-unit appears to be flaky since:
- Similar [test run](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-unit/64760/) failed with the same result (FAIL	k8s.io/kubernetes/test/integration/garbagecollector)
- The test also failed on the master HEAD when I ran locally

**Comment by rjmorse** [comment]
Would it make sense to defer the Windows OS Get Version changes so they're addressed in PR https://github.com/kubernetes/kubernetes/pull/55143 or would it be better for the method in *this* PR to address Issue https://github.com/kubernetes/kubernetes/issues/55083 ?

**Comment by JiangtianLi** [comment]
@rjmorse Sounds good. Thanks for pointing out. Will revert that part.

**Comment by bsteciuk** [comment]
The code changes to switch the package amount to essentially a no-op, the code being run in the old package and the trimmed down new package are identical, and the newly implemented method appears to do the same as well.
LGTM

**Review by bsteciuk — APPROVED** [review]

**Comment by JiangtianLi** [comment]
@brendandburns  Can you please take a look? I have updated the PR.

**Comment by PatrickLang** [comment]
Hmm - not in v1.9.0-beta.0 yet. Should it be?

**Comment by rjmorse** [comment]
I don't think it should be - the v1.9.0 beta 0 was created the day before this was merged.

**Pull request merged**
