### PR TITLE
Fix e2e test failure: pull redis image from gcr instead of docker

### LINKED ISSUE #25677: e2e broken: Kubectl describe should check if kubectl describe prints relevant information for rc and pods
This has been broken ever since #24806 merged, cc @jayunit100. [Example failure](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-flaky/16994). This test needs to be fixed, deflaked, and then moved out of the flaky suite.

### PR DESCRIPTION
**Pull request by janetkuo**
## Pull Request Guidelines
1. Please read our [contributor guidelines](https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md).
2. See our [developer guide](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md).
3. Follow the instructions for [labeling and writing a release note for this PR](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/pull-requests.md#release-notes) in the block below.

``` release-note
* Use the release-note-* labels to set the release note state 
* Clear this block to use the PR title as the release note 
-OR-
* Enter your extended release note here
```

Fixes #25677

cc @jayunit100 @fejta  
[Analytics]()

### CODE REVIEW

**Comment by jayunit100** [comment]
hi janet, i see you're working on this already ? thanks .  let me know how i can help .

**Comment by spxtr** [comment]
LGTM once it passes gofmt

**Comment by janetkuo** [comment]
gofmt updated

**Comment by janetkuo** [comment]
@jayunit100 thanks I got this

**Pull request merged**
