### PR TITLE
Update Cluster Autoscaler to 1.14.2

### PR DESCRIPTION
**Pull request by losipiuk**
```release-note
Update Cluster Autoscaler to 1.14.2
 - https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.14.2 
 - https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.14.1
```

### CODE REVIEW

**Comment by tpepper** [comment]
Could we get a little more detail on why this version is being changed? What does .2 bring versus prior?

Also the release note: The commit shows a change from .0 to .2 but the release note mentions .1 and .2 which is a little strange.

**Comment by losipiuk** [comment]
> Could we get a little more detail on why this version is being changed? What does .2 bring versus prior?
> 
> Also the release note: The commit shows a change from .0 to .2 but the release note mentions .1 and .2 which is a little strange.

See https://github.com/kubernetes/kubernetes/pull/77065#issuecomment-489541206 :)

**Pull request merged**
