### PR TITLE
kubeadm: remove flaky unit tests for chroot

### LINKED ISSUE #77213: [Failing Test] bazel-test-master is failing
**Which jobs are failing**:
`ci-kubernetes-bazel-test`

**Which test(s) are failing**:
`//cmd/kubeadm/app/util:go_default_test` ([spyglass](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-bazel-test/1122855768916234241))

**Since when has it been failing**:
Failing 4/27.

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#bazel-test-master

**Reason for failure**:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //cmd/kubeadm/app/util:go_default_test
-----------------------------------------------------------------------------
--- FAIL: TestChroot (0.10s)
    chroot_test.go:62: subprocess output:
        === RUN   TestChroot
        --- FAIL: TestChroot (0.00s)
            chroot_test.go:48: Expected file "/go_default_test" to exist, but got stat /go_default_test: no such file or directory
        FAIL
    chroot_test.go:64: subprocess error: exit status 1
[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
[endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
FAIL
```

/kind failing-test
/priority critical-urgent
/milestone v1.15
/sig cluster-lifecycle
/cc @jimangel @smourapina @rarchk @alenkacz

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:
This unit test contains some hacks that are causing the [bazel-test](https://testgrid.k8s.io/sig-release-master-blocking#bazel-test-master)
e2e job to flake very often. Instead of maintaining this
unit test remove it completely. It has little benefits
WRT testing app/util/chroot*.go:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/chroot_unix.go

**Which issue(s) this PR fixes**:

Fixes #77213

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/priority critical-urgent
/kind failing-test
@kubernetes/sig-cluster-lifecycle-pr-reviews 
cc @dims @alejandrox1

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm

let's please get this in to allow us unblock master.

**Comment by anguslees** [comment]
Lgtm.

You haven't included any information on how the test was failing (afaics?), and I would like to learn what part of fork+exec doesn't work under bazel.  Do you have any more information you can capture here?

**Comment by neolit123** [comment]
@anguslees 
the failures are here:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-bazel-test/1123356264596770823

i didn't investigate the details, but seeing that it only works from time to time:
https://testgrid.k8s.io/sig-release-master-blocking#bazel-test-master <-- green vs red runs, led me to believe that it's probably best to remove it at this point.

**Comment by anguslees** [comment]
Thanks.  For posterity, the failures look like:

```
I0501 01:49:28.497] --- FAIL: TestChroot (0.06s)
I0501 01:49:28.497] chroot_test.go:62: subprocess output:
I0501 01:49:28.497] === RUN TestChroot
I0501 01:49:28.497] --- FAIL: TestChroot (0.00s)
I0501 01:49:28.498] chroot_test.go:48: Expected file "/go_default_test" to exist, but got stat /go_default_test: no such file or directory
I0501 01:49:28.498] FAIL
I0501 01:49:28.498] chroot_test.go:64: subprocess error: exit status 1
I0501 01:49:28.498] [endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
I0501 01:49:28.498] [endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
I0501 01:49:28.498] [endpoint] WARNING: port specified in controlPlaneEndpoint overrides bindPort in the controlplane address
I0501 01:49:28.499] FAIL
```

**Comment by anguslees** [comment]
Translation of above error: chroot() call succeeded, but the testfile (`os.Args[0]`) didn't exist in the expected place after chrooting to the parent dir of `os.Args[0]`.

Odd.  I'm also confused about why now?  This is a relatively old test.  I presume it has been failing for some time and something changed that raised this to release-blocking?  I'm struggling to navigate the testgrid page to find examples of failures in anything other than the bazel-test-master table that confusingly is reporting errors in _non-master_ branches (but not master since this revert PR).  My naive attempts to find those same release branches directly don't appear to show test failures.

**Comment by neolit123** [comment]
>  I presume it has been failing for some time and something changed that raised this to release-blocking

this test job has been in release blocking before the unit test was added AFAIK.
so possibly it started failing recently.

**Pull request merged**
