### PR TITLE
Remove struct tags from pkg/api/types.go

### PR DESCRIPTION
**Pull request by thockin**
WIP, we'll see how tests fare

### CODE REVIEW

**Comment by pmorie** [comment]
Should we have a hook that checks for these, ie opposite of existing hook
for internal versions?

**Comment by thockin** [comment]
I don't think we need a hook for this - it's easy enough to keep correct once it is bulk removed.

**Comment by bprashanth** [comment]
Is this still a wip or can i merge on green?

**Comment by thockin** [comment]
We should abandon this PR.

Sadly, the codebase is not ready for this.  Specifically:

1. clientcmd depends on api.TypeMeta (not documented) and the JSON tags therein.  
2. kubectl does a JSON marshal/unmarshal which breaks without the core JSON tags.

**Pull request closed without merging**
