### PR TITLE
Fixing broken link in docs pointing to api-conventions.md

### LINKED ISSUE #1163: Dead link
**Link to the issue (please include a link to the specific documentation or example)**:
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1Pod.md
**Description of the issue (please include outputs or screenshots if possible)**:
In the items' description:
"List of pods. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md"
This "api-conventions.md" link can't be opened, please update it. 
Thank you!

### PR DESCRIPTION
**Pull request by moshevayner**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Right now there are docs pointing to broken link - https://git.k8s.io/community/contributors/devel/api-conventions.md
This PR fixes the broken link to point to the updated link:
https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes-client/python/issues/1163

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

```release-note
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```

```

### CODE REVIEW

**Comment by MoShitrit** [comment]
Looked at the failures, both seem like they failed because of timeouts on things that aren't related to what I changed. Seems like a flaky test, maybe?
/retest

**Comment by MoShitrit** [comment]
Something doesn't seem right here.
I'd love to get some help with understanding why would these tests fail by just updating a comment? 🤷‍♂️

**Comment by lavalamp** [comment]
Likely something generated needs to be updated, but the error message is definitely not helpful. Running it locally might print out more specifically what is wrong. Or you could just try `hack/update-all.sh`

/approve

**Comment by MoShitrit** [comment]
> Likely something generated needs to be updated, but the error message is definitely not helpful. Running it locally might print out more specifically what is wrong. Or you could just try `hack/update-all.sh`
> 
> /approve

Thanks @lavalamp !
I re-ran `hack/update-all.sh` and it says it ran successfully (although there were some warnings thrown, pasting the output below).
Yet when I ran `git status`/ `git diff` nothing seems to have changed.

```
$ ./hack/update-all.sh
NOTE: ./hack/update-all.sh has been replaced by 'make update'

The equivalent of this invocation is:
    make update


Running in silent mode, run with SILENT=false if you want to see script logs.
Running in short-circuit mode; run with FORCE_ALL=true to force all scripts to run.
Running update-generated-protobuf
Object "-Version" is unknown, try "ip help".
Object "-Version" is unknown, try "ip help".
Running update-codegen
vendor/k8s.io/code-generator/hack/../generate-internal-groups.sh: line 117: OPENAPI_EXTRA_PACKAGES[@]: unbound variable
./vendor/k8s.io/code-generator/generate-internal-groups.sh: line 117: OPENAPI_EXTRA_PACKAGES[@]: unbound variable
Running update-generated-runtime
Object "-Version" is unknown, try "ip help".
Object "-Version" is unknown, try "ip help".
Running update-generated-device-plugin
Object "-Version" is unknown, try "ip help".
Object "-Version" is unknown, try "ip help".
Running update-generated-api-compatibility-data
Running update-generated-docs
I0511 17:03:53.673305   21258 registry.go:150] Registering EvenPodsSpread predicate and priority function
I0511 17:03:53.673486   21258 registry.go:150] Registering EvenPodsSpread predicate and priority function
I0511 17:03:56.190340   21301 registry.go:150] Registering EvenPodsSpread predicate and priority function
I0511 17:03:56.190464   21301 registry.go:150] Registering EvenPodsSpread predicate and priority function
Running update-generated-swagger-docs
Running update-openapi-spec
Running update-bazel
Running update-gofmt
Update scripts completed successfully

$ git status
Refresh index: 100% (22105/22105), done.
On branch fix-python-1163
nothing to commit, working tree clean

$ git diff
$
```

Could one of these warnings from the `hack` script output be related?

**Comment by MoShitrit** [comment]
Still not sure why that test is failing.
It seems to have several different failures, but I'm still not sure how did my change cause them to fail.
To make sure I didn't miss anything, I re-created my local branch from upstream master to make sure I'm up to date.
Then, manually updated `types.go` to replace the broken links with the fixed ones and committed that. Then, ran `make update` and it ran successfully except for the same warnings I had before but it seems to have updated the files it needed to (2nd commit in my PR).
Then I force pushed my local branch, but the test keeps failing.
What's even more weird is that, looking at the flow, it seems like different tests are failing at different times.. 

```
$ git checkout -b fix-python-1163
Switched to a new branch 'fix-python-1163'
$ git status
On branch fix-python-1163
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   staging/src/k8s.io/api/flowcontrol/v1alpha1/types.go

no changes added to commit (use "git add" and/or "git commit -a")
$ git add .
$ git commit -m "Fixing broken link of api-conventions doc"
[fix-python-1163 48c5bc9f0fd] Fixing broken link of api-conventions doc
 1 file changed, 8 insertions(+), 8 deletions(-)
$ make update
Running in silent mode, run with SILENT=false if you want to see script logs.
Running in short-circuit mode; run with FORCE_ALL=true to force all scripts to run.
Running update-generated-protobuf
Object "-Version" is unknown, try "ip help".
Object "-Version" is unknown, try "ip help".
Running update-codegen
Running update-generated-runtime
Object "-Version" is unknown, try "ip help".
Object "-Version" is unknown, try "ip help".
Running update-generated-device-plugin
Object "-Version" is unknown, try "ip help".
Object "-Version" is unknown, try "ip help".
Running update-generated-api-compatibility-data
Running update-generated-docs
I0512 01:39:29.562538   47351 registry.go:150] Registering EvenPodsSpread predicate and priority function
I0512 01:39:29.562659   47351 registry.go:150] Registering EvenPodsSpread predicate and priority function
I0512 01:39:31.843654   47393 registry.go:150] Registering EvenPodsSpread predicate and priority function
I0512 01:39:31.843773   47393 registry.go:150] Registering EvenPodsSpread predicate and priority function
Running update-generated-swagger-docs
Running update-openapi-spec
Running update-bazel
Running update-gofmt
Update scripts completed successfully
$ git status
On branch fix-python-1163
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   api/openapi-spec/swagger.json
	modified:   staging/src/k8s.io/api/flowcontrol/v1alpha1/generated.proto
	modified:   staging/src/k8s.io/api/flowcontrol/v1alpha1/types_swagger_doc_generated.go

no changes added to commit (use "git add" and/or "git commit -a")
$ git commit -m 'Generated output of `make update` command'
``` 

I'm not really sure how to proceed with this, would love to get some pointers please.

**Comment by MoShitrit** [comment]
So I [posted this question](https://kubernetes.slack.com/archives/C0EG7JC6T/p1589315036299400) on the #sig-api-machinery Slack channel and was pointed to [this issue](https://github.com/kubernetes-sigs/kind/issues/1248) which could explain the failing test.
I also just noticed that this test isn't marked as `Required`, so turns out my merged is blocked because I still need the `/lgtm` label.
@lavalamp given that you already approved the PR- would you mind adding that label for me as well please? 😄 
Thanks much!

**Comment by MoShitrit** [comment]
Finally everything passed!! 🎉 
So now seems like I only need `/lgtm` to merge 😄

**Comment by lavalamp** [comment]
/lgtm

Thanks!

**Pull request merged**
