### PR TITLE
Remove duplication in 1.21 CHANGELOG

### PR DESCRIPTION
**Pull request by wilsonehusin**
Signed-off-by: Wilson E. Husin <wilsonehusin@gmail.com>

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Changelog document somehow has duplication. We're investigating on the [`krel`](https://github.com/kubernetes/release) end to prevent future cases.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by wilsonehusin** [comment]
/hold

i'm missing something

**Comment by wilsonehusin** [comment]
/hold cancel

fixed the dependencies ordering

**Comment by wilsonehusin** [comment]
sorry folks I keep noticing something is wrong 😅 I _think_ this should be final though

**Comment by wilsonehusin** [comment]
I'm going to give a little delay before telling prow to retest these since at a glance it looks like flakes but I don't know if the two failures are related or not.

**Comment by wilsonehusin** [comment]
🤨 is prow flaking a lot?
🤔 maybe we should reduce checks for Markdown changes...

/retest

**Comment by wilsonehusin** [comment]
👋🏼 can anyone help re-review? thanks!

cc @pmmalinov01 @puerco

**Comment by wilsonehusin** [comment]
...what?

/retest

**Comment by sladyn98** [comment]
Is the failure related to this change ? :(

**Comment by yangjunmyfm192085** [comment]
Let me try one more time

**Comment by pmmalinov01** [comment]
Whoohoo 🎉 
/pony

**Pull request merged**
