### PR TITLE
Move AppArmor feature-gate checking out of validation

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Moves feature-gate checking of apparmor annotations out of validation into the strategy utility methods, and avoids dropping data on update if the existing object already used data related to a feature.

* First commit plumbs pod annotations to the DropDisabledFields method
* Second commit moves the feature gate checking from validation to the strategy methods

**Which issue(s) this PR fixes**:
xref https://github.com/kubernetes/kubernetes/issues/72651

**Does this PR introduce a user-facing change?**:
```release-note
If the AppArmor feature gate is disabled, AppArmor-specific annotations in pod and pod templates are dropped when the object is created, and during update of objects that do not already contain AppArmor annotations, rather than triggering a validation error.
```

/sig api-machinery
/sig auth

### CODE REVIEW

**Review by sbezverk — APPROVED** [review]

**Comment by tallclair** [comment]
IIUC, there are a few user-facing changes, which might warrant a release note?
1. Pods requesting AppArmor with the feature disabled will have the annotation silently dropped rather than triggering a validation error.
2. In the event that the feature is rolled back, existing workloads will continue to be accepted.

Thanks for fixing this!

**Pull request merged**
