### PR TITLE
kubectl: Allow --patch-file to be passed to `kubectl patch`

### PR DESCRIPTION
**Pull request by smarterclayton**
The current structure is limited in the size of the patch it can
accept depending on the shell of the environment (for instance, a
900kb patch cannot be applied in bash 4 on Fedora 32). Allow a user
to specify `--patch-file` to provide a file containing the patch
rather than directly on the command line.

/kind bug

```release-note
Very large patches may now be specified to `kubectl patch` with the `--patch-file` flag instead of including them directly on the command line. The `--patch` and `--patch-file` flags are mutually exclusive.
```

```docs

```

### CODE REVIEW

**Comment by brianpursley** [comment]
/lgtm

It might be a little confusing to someone at first because there are both `-f` and `--patch-file` flags, but they serve different purposes. I think it is fine.

**Review by brianpursley — APPROVED** [review]

**Comment by smarterclayton** [comment]
Yeah, unfortunately we can't really alter `-f` and it's in broad use across so many commands, whereas in this specific case it would be more natural to patch from a file than read options from a file.

**Comment by liggitt** [comment]
https://github.com/kubernetes/test-infra/issues/19080#issuecomment-685141853

/retest

**Pull request merged**
