### PR TITLE
Enable custom metrics in gce-autoscaling jenkins job

### PR DESCRIPTION
**Pull request by mwielgus**

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

**Comment by eparis** [comment]
@k8s-bot test this flake: #22615

**Comment by mwielgus** [comment]
Summarizing 2 Failures:

[Fail] Kubectl client Kubectl run rc [It] should create an rc from an image [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:906

[Fail] ReplicaSet [It] should serve a basic image on each replica with a private image 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/replica_set.go:108

Ran 148 of 251 Specs in 850.126 seconds
FAIL! -- 146 Passed | 2 Failed | 0 Pending | 103 Skipped

**Comment by mwielgus** [comment]
@k8s-bot test this flake: #22603

**Comment by mwielgus** [comment]
I0307 09:14:43.123865   25854 genericapiserver.go:393] Node port range unspecified. Defaulting to 30000-32767.
F0307 09:14:50.373001   25854 controller.go:90] Unable to perform initial service nodePort check: unable to persist the updated port allocations: client: etcd cluster is unavailable or misconfigured
!!! Error in ./hack/test-integration.sh:63
  'KUBE_API_VERSIONS="v1,autoscaling/v1,batch/v1,extensions/v1beta1" KUBE_TEST_API_VERSIONS="$1" "${KUBE_OUTPUT_HOSTBIN}/integration" --v=${LOG_LEVEL} --max-concurrency="${KUBE_INTEGRATION_TEST_MAX_CONCURRENCY}" --watch-cache=false' exited with status 255
Call stack:
  1: ./hack/test-integration.sh:63 runTests(...)
  2: ./hack/test-integration.sh:77 main(...)
Exiting with status 1

**Comment by mwielgus** [comment]
@k8s-bot test this flake: #22603

**Comment by bgrant0607** [comment]
@mwielgus Is that really the right flake issue to cite? It's neither the same test nor symptom.

**Comment by bgrant0607** [comment]
Also, you could have specified "...unit test this..." to rerun integration tests but not e2e.

**Comment by mwielgus** [comment]
Ooops I copied the bot command from the previous broken run but somehow failed to update the issue number. Sorry for confusion and thanks for the hint with "...unit test this...".

**Comment by bgrant0607** [comment]
@piosz Does this need to be cherrypicked into 1.2, or should it not be?

**Comment by mwielgus** [comment]
@bgrant0607 Yes (once the tests are submitted too).

**Comment by bgrant0607** [comment]
Added to 1.2 milestone and cherrypick-candidate label.

**Comment by piosz** [comment]
Removing label cherrypick-candidate because this change only touches our test infrastructure.

**Pull request merged**
