### PR TITLE
resource-name not present in the URL for list,watch,deletecollection

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
cc @deads2k @liggitt 
/sig cli
/sig auth

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zjj2wry** [comment]
@liggitt Do we need to perform validation on the server-side or client-side?

**Comment by liggitt** [comment]
> Do we need to perform validation on the server-side or client-side?

The server is agnostic to resources and verbs, so it does not do any validation on them beyond format validation

**Pull request merged**
