### PR TITLE
kubelet: only register api source when connecting

### LINKED ISSUE #59275: kubelet manifest dir sync broken
/kind bug

cc. @timothysc 

**What happened**:
Since https://github.com/kubernetes/kubernetes/pull/50984 - specifically https://github.com/kubernetes/kubernetes/pull/50984/files#diff-bf28da68f62a8df6e99e447c4351122dR303, kubelet always calls `cfg.Channel(kubetypes.ApiserverType)`, leading it to always register an apiserver source with the `PodConfig`. This leads to `PodConfig.SeenAllSources` to never return true in cases where the kubelet is not configured to communicate with an apiserver. 

The direct result of this is that when removing a manifest from the directory, kubelet never kills the containers.

**What you expected to happen**:

The containers get killed properly.

**How to reproduce it (as minimally and precisely as possible)**:

Configure kubelet standalone without an apiserver, and with a static pod manifest path. Add a manifest, then remove it. Observe the containers stick around. Set logging to greater than level 6, and see a lot of `Feb 02 16:57:17 i-0ad42c5386ecaee18 kubelet[2496]: I0202 16:57:17.315020    2524 config.go:99] Looking for [api file], have seen map[file:{}]`.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.2 (1.8.7 works)

### PR DESCRIPTION
**Pull request by roboll**
**What this PR does / why we need it**:
before this change, an api source was always registered, even when there
was no kubeclient. this lead to some operations blocking waiting for
podConfig.SeenAllSources to pass, which it never would.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #59275

**Special notes for your reviewer**:

**Release note**:

```release-note
Fix the bug where kubelet in the standalone mode would wait for the update from the apiserver source.
```

### CODE REVIEW

**Review by timothysc — APPROVED** [review]
It generally /lgtm given your description of the problem, but the original code mod was part of a recommendation from @kubernetes/sig-node-pr-reviews

**Comment by yujuhong** [comment]
@roboll could you also create a cherrypick PR to patch 1.9? Thanks!

**Comment by yujuhong** [comment]
> It generally /lgtm given your description of the problem, but the original code mod was part of a recommendation from @kubernetes/sig-node-pr-reviews

I think it's just a bug and/or oversight. Not sure whether this was recommended explicitly....

**Pull request merged**
