### PR TITLE
Automated cherry pick of #29860

### PR DESCRIPTION
**Pull request by erictune**
Cherry pick of #29860 on release-1.3.

### CODE REVIEW

**Comment by ericchiang** [comment]
@googlebot I'm okay with these commits being contributed to Google.

**Comment by liggitt** [comment]
LGTM

**Comment by liggitt** [comment]
some days the bot works for you, some days you work for the bot

**Comment by liggitt** [comment]
> @liggitt needs to say he is okay

Not sure why, if I'm not on the commit as a committer or author, but if it makes the bot happy, @googlebot I'm okay with these commits being contributed to Google

**Comment by erictune** [comment]
Weird. I was sure I saw your face next to the commit when I looked at it, but it sure isn't you now.

**Pull request merged**
