### PR TITLE
fix typo for kubectl explain pod.spec.serviceAccount

### PR DESCRIPTION
**Pull request by pandaamanda**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
fix the result of `kubectl explain pod.spec.serviceAccount`
```
[root@node24 .kube]# kubectl explain pod.spec.serviceAccount
KIND:     Pod
VERSION:  v1

FIELD:    serviceAccount <string>

DESCRIPTION:
     DeprecatedServiceAccount is a depreciated alias for ServiceAccountName.
     Deprecated: Use serviceAccountName instead.
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by dougsland — APPROVED** [review]

**Review by dougsland — COMMENTED** [review]
LGTM

**Review by soltysh — CHANGES_REQUESTED** [review]
This change is not correct, the name is intentionally like this to express that this name should not be used. 
/close

**Pull request closed without merging**
