### PR TITLE
Allow the actual inhibit delay to be greater than the expected inhibit delay

### LINKED ISSUE #102818: Graceful node shutdown conflicts with unattended-upgrades package
#### What happened:
setting shutdownGracePeriod: "60s" and shutdownGracePeriodCriticalPods: "30s" in /etc/kubernetes/kubelet-config.yaml results in /var/log/kubelet.log messages like:
Jun 2 19:41:48 test-c2rtl5620bsn3hi5voeg-kublettest1-default-0000042f kubelet.service[7402]: E0602 19:41:48.214662 7402 kubelet.go:1404] "Failed to start node shutdown manager" err="node shutdown manager was unable to update logind InhibitDelayMaxSec to 1m0s (ShutdownGracePeriod), current value of InhibitDelayMaxSec (30s) is less than requested ShutdownGracePeriod" 

#### What you expected to happen:
I expected the graceful node shutdown configuration settings to take precedence.

#### How to reproduce it (as minimally and precisely as possible):
configure graceful node shutdown (shutdownGracePeriod: "60s" and shutdownGracePeriodCriticalPods: "30s" ) on a node with the unattended-upgrades package installed

check the log for messages indicating "node shutdown manager was unable to update logind InhibitDelayMaxSec ..."

#### Anything else we need to know?:
unattended-upgrades writes /usr/lib/systemd/logind.conf.d/unattended-upgrades-logind-maxdelay.conf containing InhibitDelayMaxSec=30

the Kubernetes code writes /etc/systemd/logind.conf.d/99-kubelet.conf which contains a definition of InhibitDelayMaxSec ultimately based on the values in /etc/kubernetes/kubelet-config.yaml

/usr/lib/systemd/logind.conf.d/unattended-upgrades-logind-maxdelay.conf has a higher precedence than /etc/systemd/logind.conf.d/99-kubelet.conf so the InhibitDelayMaxSec value in /usr/lib/systemd/logind.conf.d/unattended-upgrades-logind-maxdelay.conf is used.

for any value other than 30 seconds ... the Kubernetes implementation of GracefulNodeShutdown is incompatible with the unattended-upgrades package 

#### Environment:
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+IKS", GitCommit:"04e16b9d6c7af21e462f7ac675c34b667cd6149e", GitTreeState:"clean", BuildDate:"2021-05-24T08:21:44Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+IKS", GitCommit:"04e16b9d6c7af21e462f7ac675c34b667cd6149e", GitTreeState:"clean", BuildDate:"2021-05-24T08:19:13Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
IBM Cloud

- OS (e.g: `cat /etc/os-release`):
cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
uname -a
Linux test-c2v7ef52068f5kndi8s0-testcluster-default-000002f4.iks.ibm 4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?
/kind bug
/sig node

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Graceful node shutdown, allow the actual inhibit delay to be greater than the expected inhibit delay
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by bobbypage** [comment]
This change makes sense, but I don't think it will fix https://github.com/kubernetes/kubernetes/issues/102818

If I understood the issue in https://github.com/kubernetes/kubernetes/issues/102818 it was that ubuntu installs a `/usr/lib/systemd/logind.conf.d/unattended-upgrades-logind-maxdelay.conf` config with `InhibitDelayMaxSec=30`. 

Kubelet also writes a config to `/etc/systemd/logind.conf.d/99-kubelet.conf` but it looks that file is not taking precedence. 


The systemd docs (https://www.freedesktop.org/software/systemd/man/logind.conf.html) note:

"In addition to the "main" configuration file, drop-in configuration snippets are read from /usr/lib/systemd/*.conf.d/, /usr/local/lib/systemd/*.conf.d/, and /etc/systemd/*.conf.d/. Those drop-ins have higher precedence and override the main configuration file. Files in the *.conf.d/ configuration subdirectories are sorted by their filename in lexicographic order, regardless of in which of the subdirectories they reside."

So based on that it looks like the kubelet file should take precedence? Perhaps it might be issue with the lexicographic ordering...

**Comment by wzshiming** [comment]
> So based on that it looks like the kubelet file should take precedence? Perhaps it might be issue with the lexicographic ordering...

Yes, I also think this is a lexicographic ordering issue. But it does not make sense to preempt and eventually overwrite other configurations here. If there are other applications that rely on suppression locks but require more time, I think they should be allowed to exist.

**Comment by bobbypage** [comment]
>  If there are other applications that rely on suppression locks but require more time, I think they should be allowed to exist.

I agree, that makes sense. However in the ubuntu case, if the config file for `unattended-upgrades` is 30seconds and the kubelet requests something which is greater than 30 seconds, then I think kubelet inhibit delay should take precedence. 

In other words, I don't think kubelet should ever _decrease_ the overall `InhibitDelayMaxSec`, but I don't see a problem with it overriding it with a greater value. What do you think?

**Comment by wzshiming** [comment]
> In other words, I don't think kubelet should ever decrease the overall InhibitDelayMaxSec, but I don't see a problem with it overriding it with a greater value. What do you think?

I agree. This PR is done in this way

**Comment by bobbypage** [comment]
> > In other words, I don't think kubelet should ever decrease the overall InhibitDelayMaxSec, but I don't see a problem with it overriding it with a greater value. What do you think?
> 
> I agree. This PR is done in this way

Yup, agree! The only thing I'm not clear on is in PR description:

> Which issue(s) this PR fixes:
   > Fixes #102818

As we discussed, it seems like #102818 is an unrelated issue (i.e. possibly due to lexicographic sorting). Is that correct?

**Comment by wzshiming** [comment]
> As we discussed, it seems like #102818 is an unrelated issue (i.e. possibly due to lexicographic sorting of logind override files). Is that correct?

Yes, I break the link.

**Comment by bobbypage** [comment]
> > As we discussed, it seems like #102818 is an unrelated issue (i.e. possibly due to lexicographic sorting of logind override files). Is that correct?
> 
> Yes, I break the link.
> 
> I looked through logind's documentation, and I didn't think of an elegant solution for #102818

Thanks! 

LGTM for this change
/lgtm 

Can we discuss further the logind issue on the corresponding issue #102818? I'm still unclear if issue is lexicographic sorting of files or something else...

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
