### PR TITLE
revamp replicaset e2e tests

### PR DESCRIPTION
**Pull request by crimsonfaith91**
**What this PR does / why we need it**:
This PR removes some replicaset e2e tests as they will be converted to integration tests:
(1) condition check test
(2) pod adoption test
(3) pod release(orphaning) test

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: xref #52118

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by enisoc** [comment]
Looks good overall. However, one of the reasons we did orphan/adopt as an e2e was because it exposed the need to add new RBAC privileges when a controller started using PATCH for the first time.

Can you check whether RBAC is active in integration tests? And if not, is it feasible to activate it for controller integration tests?

**Comment by crimsonfaith91** [comment]
@enisoc Noted! I will investigate about the RBAC and get back to you on Monday (9/25).

**Comment by crimsonfaith91** [comment]
@enisoc I think RBAC can be enabled in integration test environment by:
(1) set a RBAC authorizer to master config authorizer: https://github.com/kubernetes/kubernetes/blob/master/test/integration/auth/rbac_test.go#L85
(2) set authenticator based on the RBAC authorizer:
https://github.com/kubernetes/kubernetes/blob/master/test/integration/auth/rbac_test.go#L416-L426

**Comment by enisoc** [comment]
That looks like a good path. Since there is an integration test for RBAC, we should be able to copy parts of the setup.

For our workload controller integration tests, we would need to enable RBAC, add the bootstrap roles, and make sure the controllers use their respective service accounts. It may be more work than it's worth though. Let's hold off on it for now and discuss with the team.

**Comment by crimsonfaith91** [comment]
@enisoc Sound good to me. I will ask about this during tomorrow's stand-up.

**Comment by crimsonfaith91** [comment]
@enisoc I combined the 2 tests rather than removing them. Does everything look good?

**Comment by enisoc** [comment]
LGTM for the combined orphan/adopt test. As discussed offline, we'll keep the condition check for now since we have not yet replaced it with an integration test.

**Comment by crimsonfaith91** [comment]
@enisoc Noted, i will add the test back. There is a TODO for condition check test on issue #51484

**Pull request merged**
