### PR TITLE
build: Update to debian-base@v2.1.3 and debian-iptables@v12.1.2

### PR DESCRIPTION
**Pull request by justaugustus**
**What type of PR is this?**

/kind cleanup
/area dependency security
/sig release api-machinery

**What this PR does / why we need it**:

- build: Update to debian-base@v2.1.3 and debian-iptables@v12.1.2
- cluster/images/etcd: Build etcd@3.4.9-3 using debian-base@v2.1.3

cc: @kubernetes/release-engineering @cjcullen 
ref: https://github.com/kubernetes/release/pull/1450, https://github.com/kubernetes/kubernetes/pull/93562, https://github.com/kubernetes/kubernetes/issues/92616, https://github.com/kubernetes/kubernetes/issues/93114

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
build: Update to debian-base@v2.1.3 and debian-iptables@v12.1.2
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
/test pull-kubernetes-e2e-kind
(pod pending timeout)

**Comment by spiffxp** [comment]
well... it merged

I'm not sure it should have because pull-kubernetes-conformance-kind-ga-only-parallel was in "triggered" state.  This might be https://github.com/kubernetes/test-infra/issues/18782 again

But I also suspect that job's failures weren't legitimate
```
wrapper.sh] [EARLY EXIT] Interrupted, entering handler ...
wrapper.sh] [CLEANUP] Cleaning up after Docker in Docker ...
Stopping Docker: dockerProgram process in pidfile '/var/run/docker-ssd.pid', 1 process(es), refused to die.
wrapper.sh] [CLEANUP] Done cleaning up after Docker in Docker.
wrapper.sh] [EARLY EXIT] Completed handler ...
{"component":"entrypoint","file":"prow/entrypoint/run.go:247","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process gracefully exited before 15m0s grace period","severity":"error","time":"2020-08-12T21:34:05Z"
```

So hooray?

**Pull request merged**
