### PR TITLE
Set priority of Event v1 higher than v1beta1

### LINKED ISSUE #91965: Set priority of Event v1 higher than v1beta1 in 1.20
**What would you like to be added**:

The Event API is being promoted to v1 in #91645 and right now v1beta1 has higher priority than v1 in pkg/apis/events/install/install.go. We should bump this in 1.20.

**Why is this needed**:

The new Event API is being promoted.

### PR DESCRIPTION
**Pull request by chelseychen**
**What type of PR is this?**

/kind api-change

**What this PR does / why we need it**:

Events API has been promoted to v1 in 1.19, so we should increase its priority as promised in #91965.

**Which issue(s) this PR fixes**:

Fixes #91965

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
- [KEP]: <https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/383-new-event-api-ga-graduation>

```

### CODE REVIEW

**Comment by chelseychen** [comment]
/assign @wojtek-t @liggitt 

Hi, I just noticed we have this left-over issue that needs to be done. Thanks for your review :)

**Comment by liggitt** [comment]
this change looks fine, but practically, it doesn't have an effect, because we still store events as core v1 in etcd

/lgtm
/approve

**Comment by chelseychen** [comment]
@liggitt 
Hi Jordan, it showed merging is blocked so I synced this PR to head, which removed LGTM label. Could you please add the label again? Thanks! Also, would you be able to merge this PR as well?

**Pull request merged**
