### PR TITLE
Automated cherry pick of #115129: bump honnef.co/go/tools to support go1.20

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #115129 on release-1.25.

#115129: bump honnef.co/go/tools to support go1.20

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/release-managers

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
