### PR TITLE
fix recevied => received

### PR DESCRIPTION
**Pull request by BingGuanqi**
fix recevied => received

Signed-off-by: Guanqi Bing <guanqi.bing@daocloud.io>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by Moriadry-zz — APPROVED** [review]
LGTM
Nice shot!

**Comment by Moriadry** [comment]
Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.

**Comment by matthyx** [comment]
/remove-lifecycle stale
/cc
@BingGuanqi please sign the CLA in order to process your PR

**Pull request closed without merging**
