### PR TITLE
e2e_apps: stop using deprecated framework.ExpectConsistOf

### PR DESCRIPTION
**Pull request by taoyounger**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it:**
e2e_apps: stop using deprecated framework.ExpectConsistOf

**Which issue(s) this PR fixes:**
Ref https://github.com/kubernetes/kubernetes/pull/115961

**Special notes for your reviewer:**
Does this PR introduce a user-facing change?

```
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:**
```

```

### CODE REVIEW

**Comment by carlory** [comment]
Can you do the same change in all of test/e2e? Then we won't have to deal with another PR which does the same thing elsewhere.

**Comment by ty-dc** [comment]
> Can you do the same change in all of test/e2e? Then we won't have to deal with another PR which does the same thing elsewhere.

I tried doing this, but it looks like ExpectConsistOf only exists in this one file.

**Review by pohly — APPROVED** [review]
/approve

**Pull request merged**
