### PR TITLE
Rename cel admission package and the feature gate to validatingadmissionpolicy

### PR DESCRIPTION
**Pull request by cici37**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR is to Rename cel admission package and the feature gate to `validatingadmissionpolicy`.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Rename the feature gate for CEL in Admission Control to `ValidatingAdmissionPolicy`.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
[KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3488-cel-admission-control
```

### CODE REVIEW

**Comment by cici37** [comment]
@liggitt if you have time? It is just the package rename and ok to be in after code freeze. :)

**Comment by andrewsykim** [comment]
Btw, this seems like a good PR to also rename the feature gate to ValidatingAdmissionPolicy like we discussed offline. If you don't want to replace all the instances of CELValidatingAdmission, you could just change the value of `CELValidatingAdmission` to `ValidatingAdmissionPolicy` and then have a follow-up PR to change the constant name.

**Comment by andrewsykim** [comment]
Adding the milestone since this PR was already approved before code freeze and the feature gate name change seems important

/milestone v1.26

**Pull request merged**
