### PR TITLE
Whitelist CronJob for kubectl apply --prune

### PR DESCRIPTION
**Pull request by tomoe**
**What this PR does / why we need it**:
Support CronJob for kubectl apply --prune

**Special notes for your reviewer**: N/A

**Release note**:

```release-note
kubectl apply --prune supports CronJob resource. 
```

### CODE REVIEW

**Comment by clusc** [comment]
+1

**Comment by tomoe** [comment]
Hi @adohe and @rootfs, could you take a look?

**Comment by tomoe** [comment]
Friendly ping: @adohe and @rootfs
Could you take a look, or else reassign to someone who can review? 

Thanks!

**Review by adohe-zz — APPROVED** [review]

**Pull request merged**
