### PR TITLE
Kubelet: simplify the lock acquring pattern

### PR DESCRIPTION
**Pull request by yujuhong**
Avoid holding both podStatusesLock and podLock at the same time.

### CODE REVIEW

**Comment by yujuhong** [comment]
cc/ @vmarmol, @fgrzadkowski

**Comment by vmarmol** [comment]
LGTM, thanks @yujuhong!

You had mentioned before of trying to merge pod and podStatus into a separate thread-safe object, do you think that's still worthwhile?

**Comment by yujuhong** [comment]
I think it'd help with code clarity, and it'll prevent people from misusing the objects. If you agree with it, I can file an issue and work on it :)

**Comment by vmarmol** [comment]
+1! The deadlock from before shows how easy the misuse is. Feel free to work on it if you have time :)

**Pull request merged**
