### PR TITLE
Use BoolPtr() function from utils instead of self-written versions

### PR DESCRIPTION
**Pull request by php-coder**
**What this PR does / why we need it**:
This PR replaces multiple versions of home-grown `BoolPtr()` function to use the one from utils package.

### CODE REVIEW

**Comment by tallclair** [comment]
Thanks! Here's a bunch more places if you feel like getting them all:
```
$ git grep -E 'func\ [^ (]+\([^ ]+\ bool\)\ \*bool' !(vendor) | grep -v pkg/util/pointer
pkg/apis/batch/fuzzer/fuzzer.go:func newBool(val bool) *bool {
pkg/apis/batch/v1beta1/defaults_test.go:func newBool(val bool) *bool {
pkg/apis/batch/v2alpha1/defaults_test.go:func newBool(val bool) *bool {
pkg/apis/batch/validation/validation_test.go:func newBool(val bool) *bool {
pkg/controller/cronjob/utils_test.go:func boolptr(b bool) *bool { return &b }
pkg/kubectl/cmd/drain_test.go:func boolptr(b bool) *bool { return &b }
pkg/kubelet/apis/kubeletconfig/v1alpha1/defaults.go:func boolVar(b bool) *bool {
pkg/printers/internalversion/printers_test.go:func boolP(b bool) *bool {
pkg/registry/batch/job/storage/storage_test.go:func newBool(val bool) *bool {
pkg/registry/batch/job/strategy_test.go:func newBool(a bool) *bool {
staging/src/k8s.io/apimachinery/pkg/conversion/queryparams/convert_test.go:func boolp(b bool) *bool { return &b }
test/e2e/framework/jobs_util.go:func newBool(val bool) *bool {
```

**Comment by php-coder** [comment]
@tallclair Thanks! I've updated PR to also cover these cases. I didn't modify `staging/src/k8s.io/apimachinery/pkg/conversion/queryparams/convert_test.go` as it will add forbidden dependency (one of our checks will fail).

Also created dedicated issue for doing the same but for `Int32Ptr()`: https://github.com/kubernetes/kubernetes/issues/59971

**Comment by tallclair** [comment]
I just thought of a few more you might want to fix:

```go
$ git grep -E '([tT]rue := true|[fF]alse := false)' !(vendor)
pkg/apis/core/validation/validation_test.go:    bTrue := true
pkg/apis/core/validation/validation_test.go:    bFalse := false
pkg/kubelet/kubelet_pods_test.go:       bTrue := true
pkg/kubelet/kuberuntime/kuberuntime_container_test.go:  runAsNonRootTrue := true
pkg/kubelet/kuberuntime/security_context_test.go:       runAsNonRootTrue := true
pkg/kubelet/kuberuntime/security_context_test.go:       runAsNonRootFalse := false
pkg/kubelet/rkt/rkt_test.go:    runAsNonRootTrue := true
pkg/kubelet/rkt/rkt_test.go:    boolTrue := true
pkg/kubelet/rkt/rkt_test.go:    boolFalse := false
pkg/security/podsecuritypolicy/provider_test.go:        readOnlyRootFSFalse := false
pkg/security/podsecuritypolicy/provider_test.go:        readOnlyRootFSTrue := true
pkg/securitycontext/util_test.go:       pfalse := false
pkg/securitycontext/util_test.go:       ptrue := true
test/e2e/common/apparmor.go:    True := true
test/e2e/node/mount_propagation.go:     bTrue := true
test/e2e_node/security_context_test.go:                 apeFalse := false
test/e2e_node/security_context_test.go:                 apeTrue := true
```

**Comment by php-coder** [comment]
@tallclair Thanks! I'll fix them on Monday.

BTW I remember that I used names `yes` and `no` for such cases :)

**Comment by php-coder** [comment]
@tallclair It's green. PTAL.

**Comment by php-coder** [comment]
@brendandburns @sttts PTAL

**Comment by sttts** [comment]
Would this be a candidate for github.com/kubernetes/utils/ptr? /cc @thockin 

/lgtm
/approve

**Comment by php-coder** [comment]
/assign @smarterclayton

It's green. PTAL.

**Comment by php-coder** [comment]
@smarterclayton ping. PTAL.

**Comment by php-coder** [comment]
@smarterclayton PTAL

**Comment by php-coder** [comment]
@smarterclayton ping, PTAL

**Comment by php-coder** [comment]
@thockin PTAL

**Comment by php-coder** [comment]
@lavalamp PTAL

**Comment by lavalamp** [comment]
Is this really an improvement? Linking in a library to remove a one-liner that's pretty hard to get wrong? I lean towards not adding an additional dependency.

**Comment by php-coder** [comment]
> I lean towards not adding an additional dependency.

Dependency? Do you mean that additional import increases size of a binary?

I see it as 1) it could reduce binary size by removing duplicated functions 2) as most of the changes related to tests, the size shouldn't be an issue

**Comment by php-coder** [comment]
> I lean towards not adding an additional dependency.

@lavalamp Would you accept this PR if it modifies only test files?

**Comment by lavalamp** [comment]
It is not about binary size, it is about build-time dependencies, and what that implies when vendoring. The go ethos is that it is not worth importing a package for a one line function. (irritatingly, I can't find a cite in 3 minutes of searching, sorry)

**Comment by php-coder** [comment]
> I lean towards not adding an additional dependency.

@lavalamp BTW we have a precedent already -- @thockin has [approved and merged](https://github.com/kubernetes/kubernetes/pull/60073#issuecomment-378054561) a similar PR but for Int32/int64-functions. May this fact lean you to another side, the side of adding an additional dependency? :)

**Comment by php-coder** [comment]
If it's not going to be merged, let's
/close
it then.

**Pull request closed without merging**
