### PR TITLE
Tweak kubelet config comments for consistency and readability

### PR DESCRIPTION
**Pull request by tengqm**
**What type of PR is this?**

/kind cleanup
/kind documentation

**What this PR does / why we need it**:

This PR tweaks the comments for the exposed kubelet configuration structs for consistency and consumability.

**Special notes for your reviewer**:

Most of the existing field comments have been documented using user-facing field names, this is an excellent practice. Some recent changes to the source have broken this, thus needs a fix.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ehashman** [comment]
This LGTM but do we want to try getting #96246 merged first? I think this one will need to be rebased after.

**Comment by tengqm** [comment]
@ehashman I can do the rebase when the other PR is in.

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by ehashman** [comment]
ah, this needs rebase, @tengqm can you PTAL?

**Comment by tengqm** [comment]
Conflicts resolved, but the PR may need another rebase when  #96246 is in.

**Comment by ehashman** [comment]
Still needs a rebase :)

**Review by ehashman — COMMENTED** [review]
/lgtm

**Review by mrunalp — APPROVED** [review]

**Comment by liggitt** [comment]
/approve

for API files

**Pull request merged**
