### PR TITLE
Type aliases request.Context with context.Context

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

Use golang 1.9 type aliases to remove duplicated `type Context interface`

**Special notes for your reviewer**:

/assign liggitt

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ash2k** [comment]
What is the reason this is better than just replacing the imports?

**Comment by liggitt** [comment]
> What is the reason this is better than just replacing the imports?

agree, I'd rather collapse onto the standard type... should be a pretty mechanical change

**Comment by hzxuzhonghu** [comment]
>What is the reason this is better than just replacing the imports?

It is for less modification imports and arguments. Since the  mechanical change pr is open and approved, this should be closed.

**Pull request closed without merging**
