### PR TITLE
refactor hard code in test/e2e/apimachinery/garbage_collector.go

### PR DESCRIPTION
**Pull request by hanxiaoshuai**
**What this PR does / why we need it**:
refactor hard code in test/e2e/apimachinery/garbage_collector.go
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hanxiaoshuai** [comment]
cc @soltysh Could you have a look at this PR? Thanks

**Comment by caesarxuchao** [comment]
@deads2k could you help approve? Thanks.

**Comment by caesarxuchao** [comment]
@sttts could you help approve? Thanks.

/assign @sttts

**Pull request merged**
