### PR TITLE
store validatingadmissionpolicy and bindings at v1

### PR DESCRIPTION
**Pull request by alexzielenski**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

VAP went GA in 1.30. For the initial `v1` release, it kept storing at `v1beta1` in accordance with keeping stored versions compatible with version N - 1.

This PR removes the v1beta1 hardcode, allowing `v1` to be used as the storage version which is compatible with a downgrade to 1.30

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

/sig api-machinery
/cc @cici37 @deads2k @siyuanfoundation 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
Thanks for the PR!
Maybe update the storagehash inside pkg/controlplane/storageversionhashdata/data.go as well? :)

**Comment by jpbetz** [comment]
/assign @deads2k
For api approval

**Comment by deads2k** [comment]
lgtm

/approve

**Pull request merged**
