### PR TITLE
Fix typo allcoated -> allocated

### PR DESCRIPTION
**Pull request by dkkb**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Fixes some typos
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dkkb** [comment]
Ping @sttts for approval 😀

**Comment by MadhavJivrajani** [comment]
/ok-to-test
🙃

**Pull request merged**
