### PR TITLE
[1.20] APF e2e: disable drown-out tests temporarily

### PR DESCRIPTION
**Pull request by adtac**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**: The test is severely flaky due to test-environment factors. While we have merged a mitigation, the issue seems to persist. We recommend disabling the test temporarily and figuring out a way to resolve the root cause of the flakiness after.

**Which issue(s) this PR fixes**:

Related to https://github.com/kubernetes/kubernetes/issues/96710 (do not close the issue until the true root cause for the flake is fixed)

**Special notes for your reviewer**:

/cc @lavalamp @fedebongio @hasheddan @kubernetes/release-team @kubernetes/release-managers 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig api-machinery

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm
/priority critical-urgent

Will wait until original PR merges for cherry-pick approval.

**Comment by adtac** [comment]
/test pull-kubernetes-e2e-kind
(flake in the other APF test, will likely be addressed by https://github.com/kubernetes/kubernetes/pull/96984)

**Pull request merged**
