### PR TITLE
[WIP] Switch to using multi-arch images with manifests

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by mkumatag** [comment]
I see only 5 tests are failing now and they are because of we didn't push `gcr.io/k8s-authenticated-test/serve-hostname:1.1` image which needed for testing ReplicaSet should serve a basic image on each replica with a private image testcase I requested https://github.com/kubernetes/kubernetes/pull/63453#issuecomment-407798138 for pushing those missing images

**Comment by mkumatag** [comment]
Most importantly I want to see tests running on containerd environment properly because we had this manifest issue earlier in containerd environment.

**Comment by mkumatag** [comment]
I see the remaining two jobs are failing with timeout of 2 hours.. need to check why is that happening..

**Comment by ixdy** [comment]
/unassign
Please reassign when this is ready for review.

**Comment by dims** [comment]
@mkumatag can you please take a look at why the 2 jobs failed?

**Pull request closed without merging**
