### PR TITLE
Fix kubelet from panic after getting the wrong signal

### LINKED ISSUE #97951: GracefulNodeShutdown dbus shutdown events not continuing if they are not valid
**What happened**:

https://github.com/kubernetes/kubernetes/blob/9caf675ed1a055ebce18cf34e8284028a729fd00/pkg/kubelet/nodeshutdown/systemd/inhibit_linux.go#L125-L157

 kubelet from panic after getting the wrong signal, and restart.

image

`gdbus emit --system --object-path /org/freedesktop/login1 --signal org.freedesktop.login1.Manager.PrepareForShutdown`

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 7
- Kernel (e.g. `uname -a`):  Linux zsm-test-2 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by wzshiming**
**What type of PR is this?**
/kind bug
/sig node

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #97951

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubelet: Fix kubelet from panic after getting the wrong signal
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by bobbypage** [comment]
@wzshiming thanks for re-opening this, sorry for the confusion on https://github.com/kubernetes/kubernetes/pull/97952.

I agree this is still an issue and needs to be fixed. 

Can you please make it clear in the PR description this fixes two issues:

1. If the `PrepareForShutdown` event is nil or `len(event.Body) == 0` it should not fall through and 
continue to read the body
2. If the `PrepareForShutdown` is malformed (i.e. nil, `len(event.Body) == 0`, or it's not a bool), the loop should continue and skip over the event rather and break.

**Comment by ialidzhikov** [comment]
@wzshiming , does it make sense to cherry-pick this PR into release-1.20?

**Comment by wzshiming** [comment]
I think it still makes sense. #99091

**Pull request merged**
