### PR TITLE
Print/log pointers of structs with %#v instead of %+v

### LINKED ISSUE #26591: Pointers of structs can't be printed with %+v anymore
I remember this worked before, but now printing pointer of kubernetes objects with `%+v` becomes useless (which affected lots of logs). 

```go
curPod := cur.(*api.Pod)
oldPod := old.(*api.Pod)
glog.V(4).Infof("Pod %s updated %+v -> %+v.", curPod.Name, oldPod, curPod)
```

```
I0531 13:46:55.896399   31819 deployment_controller.go:335] Pod nginx-3137573019-po48c updated kind:"" apiVersion:""  -> kind:"" apiVersion:"" .
```

Changing `%+v` to `%#v`, or de-reference the pointer when using `%+v` would work.

### PR DESCRIPTION
**Pull request by nhlfr**
There are many places in k8s where %+v is used to format a pointer to struct, which isn't working as expected.

Fixes #26591

### CODE REVIEW

**Comment by janetkuo** [comment]
LGTM, please rebase and I'll apply the tag

**Comment by nhlfr** [comment]
@janetkuo done. Sorry for such a late response (I was on PTO).

**Comment by janetkuo** [comment]
@nhlfr thanks for the fix!

**Comment by dims** [comment]
Looks good to me 👍

**Pull request merged**
