### PR TITLE
Automated cherry pick of #49259: update json-patch to fix nil value issue when creating mergepatch

### LINKED ISSUE #59200: kubectl annotate breaks slashes in keys with cli 1.7 and master 1.8
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
`kubectl annotate` is broken when annotation key contains a slash with cli 1.7 and master 1.8. 

**What you expected to happen**:
`kubectl annotate` should work even with slashes in annotation keys (it's allowed) with one minor version skew between cli and master (see https://github.com/kubernetes/website/issues/7103).

**How to reproduce it (as minimally and precisely as possible)**:
Use cli 1.7.12 and master 1.8.5 (probably same issue with other master 1.8 versions)
```
$ kubectl create configmap my-config --from-literal=key1=config1
configmap "my-config" created

 $ kubectl annotate configmap my-config example.com/foo=bar
The ConfigMap "my-config" is invalid: metadata.annotations: Invalid value: "example.com~1foo": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
```

Logs with `-v 10`:
```
I0201 11:13:19.813961    2540 request.go:991] Request Body: {"metadata":{"annotations":{"example.com~1foo":"bar"}}}
```

**Anything else we need to know?**:

Some other tests:
- OK `foo=bar`
- OK `test/foo=bar`
- KO `test.com/foo=bar`
- KO `example/foo=bar`
- KO `teste/foo=bar`

This is strange: 
- `test/` prefix seems special: it's the only one accepted 
- the regex is unexpected: aren't the slashes allowed? They are used everywhere in kubernetes.

It all works with the same master and the cli `1.8.5` and `1.9.2`.

This has already been bug reported but dismissed as `probably related to using incompatible versions` (see https://github.com/kubernetes/kubectl/issues/60 and #52283). But cli 1.7 should work with master 1.8, shouldn't it?

**Environment**:
- Kubernetes version (use `kubectl version`):
```$  kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.12", GitCommit:"3bda299a6414b4866f179921610d6738206a18fe", GitTreeState:"clean", BuildDate:"2017-12-29T09:00:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.5-gke.0", GitCommit:"2c2a807131fa8708abc92f3513fe167126c8cce5", GitTreeState:"clean", BuildDate:"2017-12-19T20:05:45Z", GoVersion:"go1.8.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
  - cluster: GKE
  - client: GCE
- OS (e.g. from /etc/os-release):
ubuntu 16.04

### PR DESCRIPTION
**Pull request by yue9944882**
Cherry pick of #49259 on release-1.7.

#49259: update json-patch to fix nil value issue when creating mergepatch

### CODE REVIEW

**Comment by yue9944882** [comment]
cc /assign @wojtek-t release-1.7 branch mgr

**Comment by brendandburns** [comment]
I believe this should be done as a patch to the master branch and then cherry-picked back into this branch...

**Comment by yue9944882** [comment]
@brendandburns WDYM？Release branches after 1.8 and master branch is already using latest json-patch. Only release-1.7 is outdated.

**Comment by yue9944882** [comment]
@brendanburns @wojtek-t Maybe this PR is what we need. [https://github.com/kubernetes/kubernetes/commit/8447cee0e0de612703a2fe3c5de0a2345e9bd0c5](https://github.com/kubernetes/kubernetes/commit/8447cee0e0de612703a2fe3c5de0a2345e9bd0c5)

**Comment by yue9944882** [comment]
aka Backport of #49259

**Comment by yue9944882** [comment]
flaky
/test pull-kubernetes-e2e-gce

**Comment by yue9944882** [comment]
@brendanburns How do you think about approving this? Or is 1.7 branch under maintainence yet?

**Comment by yue9944882** [comment]
@k8s-merge-robot PTAL :-)

**Pull request merged**
