### PR TITLE
If a node status is unknown, overwrite, don't patch.

### PR DESCRIPTION
**Pull request by brendandburns**
**What this PR does / why we need it**:
If a node gets into a situation where it fails to heartbeat for a while, and the NodeController marks it status unknown (`NotReady`) but then it attempts to restart heart-beating, it can get into a situation where the `Patch` operation perma-fails because of the delta between the NodeController based status and the kubelet based status.

In such situations, Patch doesn't make sense anyway, we should simply overwrite the NodeStatus, which is what this PR does.

**Which issue(s) this PR fixes** :
Fixes #https://github.com/kubernetes/kubernetes/issues/58002

**Special notes for your reviewer**:

@dchen1107 @feiskyer 

**Release note**:
```release-note
Fixes a bug where a node which became status unknown, couldn't restart heartbeating.
```

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
LGTM

**Comment by liggitt** [comment]
do we have info about the delta that fails patch? what info will overwriting status drop?

**Comment by liggitt** [comment]
@kubernetes/sig-node-pr-reviews

**Comment by brendandburns** [comment]
@liggitt if you look at the referenced issue, it prints the delta.  Basically the entirety of the node status is `Unknown` for all aspects of node status. This is because it is written by the NodeController here:

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L791

**Comment by liggitt** [comment]
> the Patch operation perma-fails because of the delta between the NodeController based status and the kubelet based status.
>
> @liggitt if you look at the referenced issue, it prints the delta

this really seems like a bug in patch computation, or patch application, or node controller backoff that should be fixed, not worked around in this one case.

the message in the linked issue only occurs when the resource is being actively changed in conflicting ways:
1. client submits patch
2. server looks up object from etcd (saves firstResourceVersion), applies patch, submits update to etcd
3. if the etcd update hits a resourceVersion conflict, the server looks up the new object from etcd (saves currentResourceVersion), and sees if `delta(original object + client patch, new object)` conflicts with the client patch. if it does, then it fails with the error in the linked issue.

Retry should succeed at step 2 eventually. I would not expect a situation in which a successful patch cannot be computed permanently.

In particular, the resource version logging is very odd to me: `firstResourceVersion: "104201", currentResourceVersion: "4293"` indicates the node object from etcd as seen by the apiserver *regressed*

also, the issue states that "when I change the leader of etcd cluster, this issue will be gone". that seems like a corrupted etcd cluster issue, not a node status patching issue.

**Comment by brendandburns** [comment]
@liggitt some thoughts:
1) I don't actually understand why this code-path uses patch at all. Especially if the state of the node is 'Unknown' a straight update actually seems like the correct behavior (and actually it seems like the correct behavior in general)

2) I don't think we can assume monotonically increasing resource versions. For example, an etcd could be recovered from a snapshot backup and we'd expect resource versions to go backwards.

3) When I observed this, the kubelet was in a permanent failure state, repeatedly attempting to update the status and failing (I wish I had saved more of the logs...) which indicates to me that somehow the Kubelet had cached an invalid Node object somewhere.

Here's one possible scenario (I think) where this could happen:

1) Kubelet reads node state at resource version v2 using cache and list/watch cache.
2) Etcd suffers a total failure and is restored using a previous backup, Node version is now v1
3) Kubelet will never actually update it's cache since the list/watch only lists from v2 forward, but version is currently v1
4) Kubelet never successfully updates node status, because it reads a newer Node object (v2) from it's cache, rather than the older (recovered) version from the API server.

I haven't completed tracked through the code, but from my high-level understanding of the codepaths involved that is theoretically possible.  The only solution in that case would be to restart the kubelet.

As an alternative, I'd be ok with remedying this with a watchdog on the kubelet, e.g. if I haven't been able to update my status in N minutes due to Conflicts (rather than lost network connectivity) I should probably just suicide and hope for the best after restart.

That might have automatically resolved the issues I saw...

**Comment by liggitt** [comment]
> I don't actually understand why this code-path uses patch at all

The main reasons:
* avoid resource version conflicts with non-overlapping updates
* avoid dropping unknown status fields (kubelets can skew two versions older than the apiserver and node controller)

> I don't think we can assume monotonically increasing resource versions. For example, an etcd could be recovered from a snapshot backup and we'd expect resource versions to go backwards.

I'd have to think about what behavior would occur via the API in that case. I think it would drop existing watches, and hang when they tried to restart (same as if you attempted to establish a watch with a far future rv). In any case, absent a catastrophic etcd cluster recovery scenario, I wouldn't expect regression of RV (and the issue didn't mention something like that was happening at the time, which makes me think etcd cluster corruption was more likely)

> Kubelet reads node state at resource version v2 using cache and list/watch cache.

Mobile at the moment, so I might be wrong, but I really thought the heartbeat was done with live get/patch, not anything fed from a watch/cache. If so, that would mean the kubelet should recover from a etcd snapshot restore (at least for node status purposes) after one heartbeat. 

I'd be really curious to see etcd cluster endpoint status (raft index and mvcc store revision) for a cluster in this state, as well as the result of watching the node api object in question while the kubelet updates are failing with conflict errors.

**Comment by brendandburns** [comment]
@liggitt I realized that `journalctl` keeps history even though I restarted the kubelet, so I still have logs, here's what it looks like:

```
Feb 28 20:05:48 aks-nodepool1-39841472-1 docker[1886]: I0228 20:05:48.054138    1979 kubelet.go:1893] SyncLoop (REMOVE, "api"): "awesome-bumblebee-nginx-ingr
ess-controller-2457738317-1zw8g_default(3f361099-180f-11e8-bc4f-0a58ac1f05db)"
Feb 28 20:05:48 aks-nodepool1-39841472-1 docker[1886]: I0228 20:05:48.054273    1979 kubelet.go:2076] Failed to delete pod "awesome-bumblebee-nginx-ingress-c
ontroller-2457738317-1zw8g_default(3f361099-180f-11e8-bc4f-0a58ac1f05db)", err: pod not found
Feb 28 20:05:58 aks-nodepool1-39841472-1 docker[1886]: I0228 20:05:58.080153    1979 kubelet_node_status.go:469] Using Node Hostname from cloudprovider: "aks
-nodepool1-39841472-1"
Feb 28 20:06:05 aks-nodepool1-39841472-1 docker[1886]: I0228 20:06:05.250822    1979 server.go:794] GET /stats/summary/: (186.244628ms) 200 [[Go-http-client/
1.1] 10.244.3.11:39214]
Feb 28 20:06:08 aks-nodepool1-39841472-1 docker[1886]: E0228 20:06:08.091850    1979 kubelet_node_status.go:357] Error updating node status, will retry: failed to patch status "{\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"NetworkUnavailable\"},{\"type\":\"OutOfDisk\"},{\"type\":\"MemoryPressure\"},{\"type\":\"DiskPressure\"},{\"type\":\"Ready\"}],\"conditions\":[{\"lastHeartbeatTime\":\"2018-02-28T20:05:58Z\",\"type\":\"OutOfDisk\"},{\"lastHeartbeatTime\":\"2018-02-28T20:05:58Z\",\"type\":\"MemoryPressure\"},{\"lastHeartbeatTime\":\"2018-02-28T20:05:58Z\",\"type\":\"DiskPressure\"},{\"lastHeartbeatTime\":\"2018-02-28T20:05:58Z\",\"type\":\"Ready\"}]}}" for node "aks-nodepool1-39841472-1": Patch https://metapartic-metaparticle-sit-50ec25-bc44ca0b.hcp.centralus.azmk8s.io:443/api/v1/nodes/aks-nodepool1-39841472-1/status: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Feb 28 20:06:18 aks-nodepool1-39841472-1 docker[1886]: E0228 20:06:18.205480    1979 kubelet_node_status.go:357] Error updating node status, will retry: error getting node "aks-nodepool1-39841472-1": Get https://metapartic-metaparticle-sit-50ec25-bc44ca0b.hcp.centralus.azmk8s.io:443/api/v1/nodes/aks-nodepool1-39841472-1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Feb 28 20:06:21 aks-nodepool1-39841472-1 docker[1886]: W0228 20:06:21.074716    1979 pod_container_deletor.go:77] Container "ae6b08bf62786f4235ec3df607b3753d1bdd71e043607c25109f323f05e30014" not found in pod's containers
Feb 28 20:06:28 aks-nodepool1-39841472-1 docker[1886]: E0228 20:06:28.207246    1979 kubelet_node_status.go:357] Error updating node status, will retry: error getting node "aks-nodepool1-39841472-1": Get https://metapartic-metaparticle-sit-50ec25-bc44ca0b.hcp.centralus.azmk8s.io:443/api/v1/nodes/aks-nodepool1-39841472-1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Feb 28 20:06:35 aks-nodepool1-39841472-1 docker[1886]: E0228 20:06:35.704279    1979 event.go:200] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"aks-nodepool1-39841472-1.1512782cc49cc920", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"8998078", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"aks-nodepool1-39841472-1", UID:"aks-nodepool1-39841472-1", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"FailedNodeAllocatableEnforcement", Message:"Failed to update Node Allocatable Limits \"\": failed to set supported cgroup subsystems for cgroup : Failed to set config for supported subsystems : failed to write 2000191488 to memory.limit_in_bytes: write /var/lib/docker/overlay2/1765c10562494848a3f8e1e12631c0f528c76ce2219925946ca22415a88fa8ff/merged/sys/fs/cgroup/memory/memory.limit_in_bytes: invalid argument", Source:v1.EventSource{Component:"kubelet", Host:"aks-nodepool1-39841472-1"}, FirstTimestamp:v1.Time{Time:time.Time{sec:63654004958, nsec:0, loc:(*time.Location)(0x928cc00)}}, LastTimestamp:v1.Time{Time:time.Time{sec:63655445165, nsec:688199216, loc:(*time.Location)(0x928cc00)}}, Count:24004, Type:"Warning"}': 'Timeout: request did not complete within allowed duration' (will not retry!)
Feb 28 20:06:38 aks-nodepool1-39841472-1 docker[1886]: E0228 20:06:38.208792    1979 kubelet_node_status.go:357] Error updating node status, will retry: error getting node "aks-nodepool1-39841472-1": Get https://metapartic-metaparticle-sit-50ec25-bc44ca0b.hcp.centralus.azmk8s.io:443/api/v1/nodes/aks-nodepool1-39841472-1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Feb 28 20:06:48 aks-nodepool1-39841472-1 docker[1886]: E0228 20:06:48.209301    1979 kubelet_node_status.go:357] Error updating node status, will retry: error getting node "aks-nodepool1-39841472-1": Get https://metapartic-metaparticle-sit-50ec25-bc44ca0b.hcp.centralus.azmk8s.io:443/api/v1/nodes/aks-nodepool1-39841472-1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Feb 28 20:06:48 aks-nodepool1-39841472-1 docker[1886]: E0228 20:06:48.210424    1979 kubelet_node_status.go:349] Unable to update node status: update node status exceeds retry count
Feb 28 20:07:01 aks-nodepool1-39841472-1 docker[1886]: I0228 20:07:01.571652    1979 kubelet_node_status.go:469] Using Node Hostname from cloudprovider: "aks-nodepool1-39841472-1"
Feb 28 20:07:05 aks-nodepool1-39841472-1 docker[1886]: I0228 20:07:05.188492    1979 server.go:794] GET /stats/summary/: (127.346101ms) 200 [[Go-http-client/1.1] 10.244.3.11:39214]
Feb 28 20:07:11 aks-nodepool1-39841472-1 docker[1886]: E0228 20:07:11.578479    1979 kubelet_node_status.go:357] Error updating node status, will retry: fail
ed to patch status "{\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"NetworkUnavailable\"},{\"type\":\"OutOfDisk\"},{\"type\":\"MemoryPressure\"},{\
"type\":\"DiskPressure\"},{\"type\":\"Ready\"}],\"conditions\":[{\"lastHeartbeatTime\":\"2018-02-28T20:07:01Z\",\"type\":\"OutOfDisk\"},{\"lastHeartbeatTime\
":\"2018-02-28T20:07:01Z\",\"type\":\"MemoryPressure\"},{\"lastHeartbeatTime\":\"2018-02-28T20:07:01Z\",\"type\":\"DiskPressure\"},{\"lastHeartbeatTime\":\"2
018-02-28T20:07:01Z\",\"type\":\"Ready\"}]}}" for node "aks-nodepool1-39841472-1": Patch https://metapartic-metaparticle-sit-50ec25-bc44ca0b.hcp.centralus.az
mk8s.io:443/api/v1/nodes/aks-nodepool1-39841472-1/status: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Feb 28 20:07:15 aks-nodepool1-39841472-1 docker[1886]: E0228 20:07:15.001053    1979 event.go:200] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind
:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"aks-nodepool1-39841472-1.1512782cc49cc920", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", Re
sourceVersion:"8998078", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil)
, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Init
ializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"aks-nodepool1
-39841472-1", UID:"aks-nodepool1-39841472-1", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"FailedNodeAllocatableEnforcement", Message:"Failed to
 update Node Allocatable Limits \"\": failed to set supported cgroup subsystems for cgroup : Failed to set config for supported subsystems : failed to write 
2000191488 to memory.limit_in_bytes: write /var/lib/docker/overlay2/1765c10562494848a3f8e1e12631c0f528c76ce2219925946ca22415a88fa8ff/merged/sys/fs/cgroup/mem
ory/memory.limit_in_bytes: invalid argument", Source:v1.EventSource{Component:"kubelet", Host:"aks-nodepool1-39841472-1"}, FirstTimestamp:v1.Time{Time:time.T
ime{sec:63654004958, nsec:0, loc:(*time.Location)(0x928cc00)}}, LastTimestamp:v1.Time{Time:time.Time{sec:63655445225, nsec:688531328, loc:(*time.Location)(0x
928cc00)}}, Count:24005, Type:"Warning"}': 'Operation cannot be fulfilled on events "aks-nodepool1-39841472-1.1512782cc49cc920": there is a meaningful confli
ct (firstResourceVersion: "8998078", currentResourceVersion: "8998307"):
Feb 28 20:07:15 aks-nodepool1-39841472-1 docker[1886]:  diff1={"count":24004,"lastTimestamp":"2018-02-28T20:06:05Z","metadata":{"resourceVersion":"8998307"}}
Feb 28 20:07:15 aks-nodepool1-39841472-1 docker[1886]: , diff2={"count":24005,"lastTimestamp":"2018-02-28T20:07:05Z","message":"Failed to update Node Allocat
able Limits \"\": failed to set supported cgroup subsystems for cgroup : Failed to set config for supported subsystems : failed to write 2000191488 to memory
.limit_in_bytes: write /var/lib/docker/overlay2/1765c10562494848a3f8e1e12631c0f528c76ce2219925946ca22415a88fa8ff/merged/sys/fs/cgroup/memory/memory.limit_in_
bytes: invalid argument"}
Feb 28 20:07:15 aks-nodepool1-39841472-1 docker[1886]: ' (will not retry!)
Feb 28 20:07:15 aks-nodepool1-39841472-1 docker[1886]: W0228 20:07:15.721985    1979 reflector.go:323] k8s.io/kubernetes/pkg/kubelet/kubelet.go:402: watch of
 *v1.Service ended with: too old resource version: 6828989 (8998320)
Feb 28 20:07:15 aks-nodepool1-39841472-1 docker[1886]: I0228 20:07:15.997150    1979 kubelet_node_status.go:469] Using Node Hostname from cloudprovider: "aks
-nodepool1-39841472-1"
Feb 28 20:07:16 aks-nodepool1-39841472-1 docker[1886]: I0228 20:07:16.000463    1979 kubelet_node_status.go:410] Recording NodeHasSufficientDisk event messag
e for node aks-nodepool1-39841472-1
Feb 28 20:07:16 aks-nodepool1-39841472-1 docker[1886]: I0228 20:07:16.000557    1979 kubelet_node_status.go:410] Recording NodeHasSufficientMemory event mess
age for node aks-nodepool1-39841472-1
Feb 28 20:07:16 aks-nodepool1-39841472-1 docker[1886]: I0228 20:07:16.000628    1979 kubelet_node_status.go:410] Recording NodeHasNoDiskPressure event message for node aks-nodepool1-39841472-1
Feb 28 20:07:16 aks-nodepool1-39841472-1 docker[1886]: I0228 20:07:16.000669    1979 kubelet_node_status.go:410] Recording NodeReady event message for node aks-nodepool1-39841472-1
Feb 28 20:07:16 aks-nodepool1-39841472-1 docker[1886]: E0228 20:07:16.051910    1979 kubelet_node_status.go:357] Error updating node status, will retry: fail
ed to patch status "{\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"NetworkUnavailable\"},{\"type\":\"OutOfDisk\"},{\"type\":\"MemoryPressure\"},{\
"type\":\"DiskPressure\"},{\"type\":\"Ready\"}],\"conditions\":[{\"lastHeartbeatTime\":\"2018-02-28T20:07:16Z\",\"lastTransitionTime\":\"2018-02-28T20:07:16Z
\",\"message\":\"kubelet has sufficient disk space available\",\"reason\":\"KubeletHasSufficientDisk\",\"status\":\"False\",\"type\":\"OutOfDisk\"},{\"lastHe
artbeatTime\":\"2018-02-28T20:07:16Z\",\"lastTransitionTime\":\"2018-02-28T20:07:16Z\",\"message\":\"kubelet has sufficient memory available\",\"reason\":\"K
ubeletHasSufficientMemory\",\"status\":\"False\",\"type\":\"MemoryPressure\"},{\"lastHeartbeatTime\":\"2018-02-28T20:07:16Z\",\"lastTransitionTime\":\"2018-0
2-28T20:07:16Z\",\"message\":\"kubelet has no disk pressure\",\"reason\":\"KubeletHasNoDiskPressure\",\"status\":\"False\",\"type\":\"DiskPressure\"},{\"last
HeartbeatTime\":\"2018-02-28T20:07:16Z\",\"lastTransitionTime\":\"2018-02-28T20:07:16Z\",\"message\":\"kubelet is posting ready status\",\"reason\":\"Kubelet
Ready\",\"status\":\"True\",\"type\":\"Ready\"}]}}" for node "aks-nodepool1-39841472-1": Operation cannot be fulfilled on nodes "aks-nodepool1-39841472-1": t
here is a meaningful conflict (firstResourceVersion: "8998384", currentResourceVersion: "8998261"):
Feb 28 20:07:16 aks-nodepool1-39841472-1 docker[1886]:  diff1={"metadata":{"resourceVersion":"8998261"},"status":{"$setElementOrder/conditions":[{"type":"Net
workUnavailable"},{"type":"OutOfDisk"},{"type":"MemoryPressure"},{"type":"DiskPressure"},{"type":"Ready"}],"conditions":[{"lastHeartbeatTime":"2018-02-28T20:
05:19Z","lastTransitionTime":"2018-02-28T20:00:45Z","message":"Kubelet stopped posting node status.","reason":"NodeStatusUnknown","status":"Unknown","type":"
OutOfDisk"},{"lastHeartbeatTime":"2018-02-28T20:05:19Z","lastTransitionTime":"2018-02-28T20:00:45Z","message":"Kubelet stopped posting node status.","reason"
:"NodeStatusUnknown","status":"Unknown","type":"MemoryPressure"},{"lastHeartbeatTime":"2018-02-28T20:05:19Z","lastTransitionTime":"2018-02-28T20:00:45Z","mes
sage":"Kubelet stopped posting node status.","reason":"NodeStatusUnknown","status":"Unknown","type":"DiskPressure"},{"lastHeartbeatTime":"2018-02-28T20:05:19
Z","lastTransitionTime":"2018-02-28T20:00:45Z","message":"Kubelet stopped posting node status.","reason":"NodeStatusUnknown","status":"Unknown","type":"Ready
"}]}}
Feb 28 20:07:16 aks-nodepool1-39841472-1 docker[1886]: , diff2={"status":{"$setElementOrder/conditions":[{"type":"NetworkUnavailable"},{"type":"OutOfDisk"},{
"type":"MemoryPressure"},{"type":"DiskPressure"},{"type":"Ready"}],"conditions":[{"lastHeartbeatTime":"2018-02-28T20:07:16Z","lastTransitionTime":"2018-02-28
T20:07:16Z","message":"kubelet has sufficient disk space available","reason":"KubeletHasSufficientDisk","status":"False","type":"OutOfDisk"},{"lastHeartbeatT
ime":"2018-02-28T20:07:16Z","lastTransitionTime":"2018-02-28T20:07:16Z","message":"kubelet has sufficient memory available","reason":"KubeletHasSufficientMem
ory","status":"False","type":"MemoryPressure"},{"lastHeartbeatTime":"2018-02-28T20:07:16Z","lastTransitionTime":"2018-02-28T20:07:16Z","message":"kubelet has
 no disk pressure","reason":"KubeletHasNoDiskPressure","status":"False","type":"DiskPressure"},{"lastHeartbeatTime":"2018-02-28T20:07:16Z","lastTransitionTim
e":"2018-02-28T20:07:16Z","message":"kubelet is posting ready status","reason":"KubeletReady","status":"True","type":"Ready"}]}}
Feb 28 20:07:27 aks-nodepool1-39841472-1 docker[1886]: I0228 20:07:27.992098    1979 kubelet_node_status.go:469] Using Node Hostname from cloudprovider: "aks
-nodepool1-39841472-1"
Feb 28 20:07:27 aks-nodepool1-39841472-1 docker[1886]: I0228 20:07:27.995619    1979 kubelet_node_status.go:410] Recording NodeHasSufficientDisk event messag
e for node aks-nodepool1-39841472-1
Feb 28 20:07:27 aks-nodepool1-39841472-1 docker[1886]: I0228 20:07:27.995667    1979 kubelet_node_status.go:410] Recording NodeHasSufficientMemory event mess
age for node aks-nodepool1-39841472-1
Feb 28 20:07:27 aks-nodepool1-39841472-1 docker[1886]: I0228 20:07:27.995685    1979 kubelet_node_status.go:410] Recording NodeHasNoDiskPressure event messag
e for node aks-nodepool1-39841472-1
Feb 28 20:07:27 aks-nodepool1-39841472-1 docker[1886]: I0228 20:07:27.995707    1979 kubelet_node_status.go:410] Recording NodeReady event message for node a
ks-nodepool1-39841472-1
...
Mar 05 20:00:06 aks-nodepool1-39841472-1 docker[1886]: I0305 20:00:06.071999    1979 kubelet_node_status.go:410] Recording NodeHasSufficientDisk event messag
e for node aks-nodepool1-39841472-1
Mar 05 20:00:06 aks-nodepool1-39841472-1 docker[1886]: I0305 20:00:06.072109    1979 kubelet_node_status.go:410] Recording NodeHasSufficientMemory event mess
age for node aks-nodepool1-39841472-1
Mar 05 20:00:06 aks-nodepool1-39841472-1 docker[1886]: I0305 20:00:06.073381    1979 kubelet_node_status.go:410] Recording NodeHasNoDiskPressure event messag
e for node aks-nodepool1-39841472-1
Mar 05 20:00:06 aks-nodepool1-39841472-1 docker[1886]: I0305 20:00:06.073466    1979 kubelet_node_status.go:410] Recording NodeReady event message for node aks-nodepool1-39841472-1
Mar 05 20:00:06 aks-nodepool1-39841472-1 docker[1886]: E0305 20:00:06.167928    1979 kubelet_node_status.go:357] Error updating node status, will retry: failed to patch status "{\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"NetworkUnavailable\"},{\"type\":\"OutOfDisk\"},{\"type\":\"MemoryPressure\"},{\"type\":\"DiskPressure\"},{\"type\":\"Ready\"}],\"conditions\":[{\"lastHeartbeatTime\":\"2018-03-05T20:00:06Z\",\"lastTransitionTime\":\"2018-03-05T20:00:06Z\",\"message\":\"kubelet has sufficient disk space available\",\"reason\":\"KubeletHasSufficientDisk\",\"status\":\"False\",\"type\":\"OutOfDisk\"},{\"lastHeartbeatTime\":\"2018-03-05T20:00:06Z\",\"lastTransitionTime\":\"2018-03-05T20:00:06Z\",\"message\":\"kubelet has sufficient memory available\",\"reason\":\"KubeletHasSufficientMemory\",\"status\":\"False\",\"type\":\"MemoryPressure\"},{\"lastHeartbeatTime\":\"2018-03-05T20:00:06Z\",\"lastTransitionTime\":\"2018-03-05T20:00:06Z\",\"message\":\"kubelet has no disk pressure\",\"reason\":\"KubeletHasNoDiskPressure\",\"status\":\"False\",\"type\":\"DiskPressure\"},{\"lastHeartbeatTime\":\"2018-03-05T20:00:06Z\",\"lastTransitionTime\":\"2018-03-05T20:00:06Z\",\"message\":\"kubelet is posting ready status\",\"reason\":\"KubeletReady\",\"status\":\"True\",\"type\":\"Ready\"}]}}" for node "aks-nodepool1-39841472-1": Operation cannot be fulfilled on nodes "aks-nodepool1-39841472-1": there is a meaningful conflict (firstResourceVersion: "8998384", currentResourceVersion: "8998261"):
Mar 05 20:00:06 aks-nodepool1-39841472-1 docker[1886]:  diff1={"metadata":{"resourceVersion":"8998261"},"status":{"$setElementOrder/conditions":[{"type":"NetworkUnavailable"},{"type":"OutOfDisk"},{"type":"MemoryPressure"},{"type":"DiskPressure"},{"type":"Ready"}],"conditions":[{"lastHeartbeatTime":"2018-02-28T20:05:19Z","lastTransitionTime":"2018-02-28T20:00:45Z","message":"Kubelet stopped posting node status.","reason":"NodeStatusUnknown","status":"Unknown","type":"OutOfDisk"},{"lastHeartbeatTime":"2018-02-28T20:05:19Z","lastTransitionTime":"2018-02-28T20:00:45Z","message":"Kubelet stopped posting node status.","reason":"NodeStatusUnknown","status":"Unknown","type":"MemoryPressure"},{"lastHeartbeatTime":"2018-02-28T20:05:19Z","lastTransitionTime":"2018-02-28T20:00:45Z","message":"Kubelet stopped posting node status.","reason":"NodeStatusUnknown","status":"Unknown","type":"DiskPressure"},{"lastHeartbeatTime":"2018-02-28T20:05:19Z","lastTransitionTime":"2018-02-28T20:00:45Z","message":"Kubelet stopped posting node status.","reason":"NodeStatusUnknown","status":"Unknown","type":"Ready"}]}}
Mar 05 20:00:06 aks-nodepool1-39841472-1 docker[1886]: , diff2={"status":{"$setElementOrder/conditions":[{"type":"NetworkUnavailable"},{"type":"OutOfDisk"},{"type":"MemoryPressure"},{"type":"DiskPressure"},{"type":"Ready"}],"conditions":[{"lastHeartbeatTime":"2018-03-05T20:00:06Z","lastTransitionTime":"2018-03-05T20:00:06Z","message":"kubelet has sufficient disk space available","reason":"KubeletHasSufficientDisk","status":"False","type":"OutOfDisk"},{"lastHeartbeatTime":"2018-03-05T20:00:06Z","lastTransitionTime":"2018-03-05T20:00:06Z","message":"kubelet has sufficient memory available","reason":"KubeletHasSufficientMemory","status":"False","type":"MemoryPressure"},{"lastHeartbeatTime":"2018-03-05T20:00:06Z","lastTransitionTime":"2018-03-05T20:00:06Z","message":"kubelet has no disk pressure","reason":"KubeletHasNoDiskPressure","status":"False","type":"DiskPressure"},{"lastHeartbeatTime":"2018-03-05T20:00:06Z","lastTransitionTime":"2018-03-05T20:00:06Z","message":"kubelet is posting ready status","reason":"KubeletReady","status":"True","type":"Ready"}]}}
Mar 05 20:00:06 aks-nodepool1-39841472-1 docker[1886]: E0305 20:00:06.168108    1979 kubelet_node_status.go:349] Unable to update node status: update node status exceeds retry count
Mar 05 20:00:18 aks-nodepool1-39841472-1 docker[1886]: I0305 20:00:18.102268    1979 kubelet_node_status.go:469] Using Node Hostname from cloudprovider: "aks-nodepool1-39841472-1"
```

So the kubelet gets stuck for over one week unable to update it's status...

It seems to me that this indicates that something in the node update status flow is stuck and it's holding onto an old version of the Node somehow and sending in patches that are invalid.

Reading the code, it's a little unclear to me exactly how this could happen, but it seems that some sort of watch dog for "failed to update for > 12 hours, restarting the kubelet" makes sense as a safety valve here.

**Comment by brendandburns** [comment]
fwiw, I'm suspicious of the API Server cache in this case, but the code seems to indicate it only hits the cache on try 1, so there's no smoking gun...

**Comment by liggitt** [comment]
fwiw, https://github.com/kubernetes/kubernetes/pull/63146 dropped the problematic behavior of trying to detect conflicts between the incoming patch and the delta from the first-seen version of the resource, so the "there is a meaningful conflict" error reported in #58002 will not occur now. if the patch submitted by the kubelet can be applied, it is applied and the node is updated.

**Comment by derekwaynecarr** [comment]
@brendandburns i am concerned about the impact this may have with the readiness++ proposal where kubelet is not authoritative for all node status, see: https://github.com/kubernetes/community/pull/1991

the idea of a kubelet that is not running in standalone mode existing when unable to provide status is probably worth pursuing.  i have been thinking about other options to improve monitoring of the kubelet.  right now, the kubelet remote api could be enhanced in a few ways to detect wedge scenarios.  in particular, i have been wanting to expose the node status the kubelet last attempted to tell the apiserver via a kubelet endpoint.  this would let me build a simple daemonset monitoring pod that checked if a kubelet was wedged, or not ready (due to container runtime problems) without confusing the not ready state as a network condition.  a simple remedy would be to restart kubelet, restart runtime, or power cycle machine.

**Pull request closed without merging**
