### PR TITLE
Update bazel build to dockerize cloud-controller-manager

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: followup to #45154. Also added a comment so that hopefully this sort of followup isn't needed again. :)

**Release note**:

```release-note
NONE
```

/assign @mikedanese @luxas

### CODE REVIEW

**Comment by ixdy** [comment]
cc @wlan0

**Comment by ixdy** [comment]
(first push missed updating `build/debs/BUILD`. I think this actually works now.)

**Comment by ixdy** [comment]
```
Tag latest not found in repository docker.io/library/busybox
```
what?

@k8s-bot pull-kubernetes-cross test this
@k8s-bot unit test this

**Review by luxas — COMMENTED** [review]
Thanks @ixdy for fixing this up!

Didn't notice those rules, with the comment I'll hopefully do the next time ;)

**Comment by ixdy** [comment]
@luxas I don't expect anyone to know (or care) about the parallel bazel rules. I'm hoping to soon have automation (or even just a single source of truth) to alleviate this problem.

**Pull request merged**
