### PR TITLE
use python3 in hack

### LINKED ISSUE #114967: Python2 still in use
### What happened?

python2 is long deprecated, everything should be on python3, but that doesn't appear to be the case in this repo.

/sig testing

### PR DESCRIPTION
**Pull request by AxeZhan**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Currently some files in k/k are still using python2, we should upgrade them to python3.
#### Which issue(s) this PR fixes:

Fixes #114967 

#### Special notes for your reviewer:
I ran this command to find py files in k/k repo:
```
find ./ -name "*.py"                  
.//staging/src/k8s.io/kubectl/pkg/util/i18n/translations/extract.py
.//hack/boilerplate/test/pass.py
.//hack/boilerplate/test/fail.py
.//hack/boilerplate/boilerplate.py
.//hack/boilerplate/boilerplate_test.py
.//hack/verify-flags-underscore.py
.//hack/verify-publishing-bot.py
```

I ran this script to update and check these py files:
```
#!/usr/bin/env python
import sys
from lib2to3.main import main

sys.exit(main("lib2to3.fixes"))
```

please leave a comment if there's a more appropriate method :)
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
None of these required _any_ source changes?

**Comment by kidddddddddddddddddddddd** [comment]
> None of these required _any_ source changes?

Yesterday I just ran these files with python3 locally, and everything was fine.
Today I ran a script to check these files, and it shows some changes.
```
#!/usr/bin/env python
import sys
from lib2to3.main import main

sys.exit(main("lib2to3.fixes"))

```

I'd be glad to receive some suggestions about how to check this more properly :)

**Review by BenTheElder — COMMENTED** [review]
/ok-to-test

**Comment by thockin** [comment]
Thanks!  I stumbled on this in my own work.  Anything holding up approval?

**Comment by kidddddddddddddddddddddd** [comment]
> Thanks! I stumbled on this in my own work. Anything holding up approval?

Actually I don't know. Maybe you can read the statement and give me some advice.

**Comment by thockin** [comment]
I'm not at all a python expert, I just know that I don't have python2 installed :)

This looks OK to me, but I can't say I know what all the diffs are about.

**Comment by dims** [comment]
This is a good start, let's get this in and see if we find any other problems. 

(Yes, i've dabbled with this python2->3 migration before, the automated thing finds a lot of it for sure, but it may not catch 100% of things)

/approve
/lgtm

**Comment by BenTheElder** [comment]
Thank you!

**Pull request merged**
