### PR TITLE
Release 0.21

### PR DESCRIPTION
**Pull request by zmerlynn**
Branch point v0.20.2-440-g639a7da

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @thockin 

Does the doc commit look like what you're expecting? And does it LGTY?

**Comment by zmerlynn** [comment]
No, this is broken - either process or script. I shouldn't be merging the 0.21 substitutes back, I assume.

**Comment by zmerlynn** [comment]
Yeah, I spent a while thinking about this, and I'm going to sleep. No easy answer.

The process we use right now is to create the release branch locally, tag it, propose a PR (like this one), then push the branch. Most of those instructions are actually sitting right in `mark-new-version.sh`, and some are here: https://github.com/zmerlynn/kubernetes/blob/i1883/docs/devel/releasing.md#branching-tagging-and-merging.

The problem, and I didn't really think about it long enough when it went in, is that the new sandwich commit you're creating, is always going to get backmerged back like this - git will always try to mutate head from the release version. We take that as good from the release version because we've been trying to keep the head version in sync with the patch version (long story), but not for these cases.

We do have a weird cost for merging back and forth between release N-1 and master (we try to keep the release tags merged back to master). Not sure how to crack this particular nut.

cc @eparis, how might have a thought before I wake up.

**Comment by thockin** [comment]
The version subst looks right to me, but yeah not to master.  Maybe the right process is to create a new branch (in the UI or CLI for precision) and then offer a PR to that branch?

**Comment by zmerlynn** [comment]
The problem is that even if a PR is offered to the branch, if the subst is even made and a backmerge is attempted to master (which happens on the next patch, too), we're in the same boat, so even if we reorder and push the branch now and then make a PR for the doc merge after the version commits (which doesn't exactly work because you want them in the tarball, I think?).

The horri-bad solution I came up with was a retro-script to re-fix it on HEAD after the backmerge, but I'm trying to stop myself from writing it.

**Pull request closed without merging**
