### PR TITLE
kubeadm: Default to v1.6.0 stable in offline scenarios in beforehand

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:

In offline scenarios, kubeadm will fallback to the latest well-known version.
This PR bumps that to v1.6. We can merge now, and in the small gap between the merge of this PR and the actual v1.6 release, kubeadm devs will have to explicitely set k8s version.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
@jbeda

### CODE REVIEW

**Comment by pires** [comment]
I was going to review but it seems I was unassigned 👍 .

**Comment by luxas** [comment]
Ohh, sorry @pires, seems like Github strikes again. I assigned @jbeda from the get go (at the point no one else was assigned), but seems like a race condition made me unassign you at the same time without me noticing or it being intentional.

Anyway, this is really straightforward, can I get an LGTM from @jbeda or @pires, thanks?

**Comment by luxas** [comment]
@k8s-bot node e2e test this
@k8s-bot gce etcd3 e2e test this

**Comment by luxas** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
