### PR TITLE
Release 1.2 cherry pick batch

### PR DESCRIPTION
**Pull request by eparis**
Includes the following:
#22851: Bumped Heapster to v1.0.0-beta1
#22791: AWS EBS: Remove the attached volumes cache
#22788: AWS: Don't pass empty filters to AWS requests
#22502: Adding a unit test to #22418
#22779: AWS kube-up: Clean up distro handling
#22783: AWS kube-up: add retries around delete-security-group
#22784: AWS: Increase timeout deleting ELB; log remaining security groups
#22793: AWS: Tag created EBS volumes with our cluster tag
#22803: bump cadvisor to v0.22.1
#22605: Added e2e test for batch API group
#22674: Set a default value for "$@" in yaml-quote.
#22847: Adding FullyLabeledReplicas field to replicaset status
#22882: Trusty: fix several bugs
#22929: Test relative timestamps using UTC
#22901: Cleanup /etc/motd after doc link shift

### CODE REVIEW

**Comment by eparis** [comment]
@bgrant0607

**Comment by bgrant0607** [comment]
Will merge as soon as tests pass. It should fix the unit-test build.

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
Tests passed. Merging.

**Comment by bgrant0607** [comment]
cc @david-mcmahon

**Pull request merged**
