### PR TITLE
register queue metrics in controller manager

### LINKED ISSUE #87966: Kube controller manager should export queue metrics
**What would you like to be added**:
kube-controller-manager currently does not expose work queue metrics

**Why is this needed**:
queuing delay and queue length are important information to debug control plane performance in large scale cluster

/assign zhan849
/sig apps

### PR DESCRIPTION
**Pull request by zhan849**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
/kind feature

**What this PR does / why we need it**:
register queue metrics in controller manager

**Which issue(s) this PR fixes**:

Fixes #87966

**Special notes for your reviewer**:
`"k8s.io/component-base/metrics/prometheus/workqueue"` registers prometheus metrics provider to the work queue in its `init()` function so simply importing the package will have those metrics served.

**Does this PR introduce a user-facing change?**:

```release-note
Controller manager serve workqueue metrics
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/assign @cheftako

### CODE REVIEW

**Comment by zhan849** [comment]
seems these tests are passing but gce is having some problems
```
I0210 04:56:42.655] Will upload results to gs://kubernetes-jenkins/pr-logs using pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com
I0210 04:56:42.655] Upload result and artifacts...
I0210 04:56:42.655] Gubernator results at https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/87967/pull-kubernetes-e2e-gce-100-performance/1226730031888207872
I0210 04:56:42.655] Call:  gsutil ls gs://kubernetes-jenkins/pr-logs/pull/87967/pull-kubernetes-e2e-gce-100-performance/1226730031888207872/artifacts
W0210 04:56:43.531] CommandException: One or more URLs matched no objects.
```

/retest

**Comment by liggitt** [comment]
See https://github.com/kubernetes/test-infra/issues/16202#issuecomment-583955160

**Review by logicalhan — APPROVED** [review]
/lgtm

**Comment by zhan849** [comment]
@logicalhan thanks! can I get an `/approve` as well so this steps into the merge pool?

**Comment by zhan849** [comment]
> @logicalhan thanks! can I get an `/approve` as well so this steps into the merge pool?

ping @logicalhan @cheftako ^^

**Pull request merged**
