### PR TITLE
Use bionic repo for docker as focal is not yet available

### LINKED ISSUE #90667: [Failing Test] gce-ubuntu-master-containerd (ci-kubernetes-e2e-ubuntu-gce-containerd)
**Which jobs are failing**:

> gce-ubuntu-master-containerd (ci-kubernetes-e2e-ubuntu-gce-containerd)

**Which test(s) are failing**:

> Overall
> Up

**Since when has it been failing**:

> 04-30 10:00 PDT

**Testgrid link**:

> https://testgrid.k8s.io/sig-release-master-informing#gce-ubuntu-master-containerd

**Reason for failure**:

> W0501 09:18:22.072] scp: /var/log/kube-addon-manager.log*: No such file or directory
> W0501 09:18:22.072] scp: /var/log/konnectivity-server.log*: No such file or directory
> W0501 09:18:22.072] scp: /var/log/fluentd.log*: No such file or directory
> W0501 09:18:22.072] scp: /var/log/kubelet.cov*: No such file or directory
> W0501 09:18:22.073] scp: /var/log/startupscript.log*: No such file or directory
> W0501 09:18:22.075] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].

**Anything else we need to know**:

/cc @kubernetes/ci-signal
/milestone v1.19
/priority critical-urgent
/sig testing

### LINKED ISSUE #90668: [Failing Test] gce-ubuntu-master-default (ci-kubernetes-e2e-ubuntu-gce)
**Which jobs are failing**:

> gce-ubuntu-master-default (ci-kubernetes-e2e-ubuntu-gce)

**Which test(s) are failing**:

> Overall
> Up

**Since when has it been failing**:

> 04-30 10:00 PDT

**Testgrid link**:

> https://testgrid.k8s.io/sig-release-master-informing#gce-ubuntu-master-default

**Reason for failure**:

> W0501 09:18:42.774] scp: /var/log/kube-addon-manager.log*: No such file or directory
> W0501 09:18:42.774] scp: /var/log/konnectivity-server.log*: No such file or directory
> W0501 09:18:42.775] scp: /var/log/fluentd.log*: No such file or directory
> W0501 09:18:42.775] scp: /var/log/kubelet.cov*: No such file or directory
> W0501 09:18:42.775] scp: /var/log/startupscript.log*: No such file or directory
> W0501 09:18:42.780] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].

**Anything else we need to know**:

/cc @kubernetes/ci-signal
/milestone v1.19
/priority critical-urgent
/sig testing

### PR DESCRIPTION
**Pull request by dims**
Signed-off-by: Davanum Srinivas <davanum@gmail.com>

**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #90667
Fixes #90668

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/hold

for the 2 optional presubmits need to be green before we can merge

**Review by justaugustus — CHANGES_REQUESTED** [review]
@dims -- Can you open a tracking issue to remove these conditionals once the new repos are available and point to that issue in both code comments?

**Comment by dims** [comment]
@justaugustus Done! https://github.com/kubernetes/kubernetes/issues/90709

**Pull request merged**
