### PR TITLE
Add command "kubectl replace"

### PR DESCRIPTION
**Pull request by caesarxuchao**
Add command "kubectl replace". "kubectl update" is still supported as an alias.
"kubectl replace --force" is supported, but "kubectl replace --patch" is NOT supported. It's moved to "kubectl patch" as a separate command in another commit.
#10202

@bgrant0607 @nikhiljindal @krousey

### CODE REVIEW

**Comment by jlowdermilk** [comment]
This is a pretty straightforward s/update/replace with `--patch` moved to a separate command by #10374. LGTM

**Comment by a-robinson** [comment]
@bgrant0607 @alex-mohr for lead approvals

**Comment by bgrant0607** [comment]
Please add update as a deprecated alias for replace. For an example, see:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/rollingupdate.go#L109

**Comment by caesarxuchao** [comment]
Done. I will squash after getting LGTMs.

**Comment by bgrant0607** [comment]
LGTM.

**Pull request merged**
