### PR TITLE
Make unit test runs MUCH faster

### PR DESCRIPTION
**Pull request by thockin**
Running tests rebuilds almost everything.  Most unit tests do not need to be
rebuilt.  This installs test artifacts and makes subsequent test runs as much
as 6x faster.  I saw pkg/apiserver tests drop from 30+ seconds to 5 seconds.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31853)

### CODE REVIEW

**Comment by thockin** [comment]
@rsc this feels silly - is this really best practice?

**Comment by thockin** [comment]
For context I just did a full unit test run in under 3 minutes.

**Comment by thockin** [comment]
ok to test

**Comment by thockin** [comment]
@k8s-bot test this: github issue #IGNORE

**Comment by thockin** [comment]
@k8s-bot test this: github issue #IGNORE

**Comment by lavalamp** [comment]
lgtm!

**Comment by stevekuznetsov** [comment]
@thockin do we have any word from the Go team if this is the best approach? This seems weird.

**Comment by thockin** [comment]
No word from Go team.  I'll ask by email.

**Comment by stevekuznetsov** [comment]
@thockin I just tried this in Origin using this patch:

The results don't show any difference:
```
$ time TEST_KUBE=true hack/test-go.sh
ok  	github.com/openshift/origin/examples	1.401s	coverage: 0.0% of statements
ok  	github.com/openshift/origin/pkg/api	14.795s	coverage: 32.1% of statements
...
ok  	github.com/openshift/origin/vendor/k8s.io/kubernetes/third_party/golang/go/scanner	1.082s	coverage: 94.7% of statements
ok  	github.com/openshift/origin/vendor/k8s.io/kubernetes/third_party/golang/go/token	1.212s	coverage: 75.4% of statements
hack/test-go.sh succeeded after 1400 seconds

real  23m19.827s
user 148m23.519s
sys    8m56.479s


$ time TEST_KUBE=true hack/test-go.sh
ok  	github.com/openshift/origin/examples	1.544s	coverage: 0.0% of statements
ok  	github.com/openshift/origin/pkg/api	15.647s	coverage: 32.1% of statements
...
ok  	github.com/openshift/origin/vendor/k8s.io/kubernetes/third_party/golang/go/scanner	1.046s	coverage: 94.7% of statements
ok  	github.com/openshift/origin/vendor/k8s.io/kubernetes/third_party/golang/go/token	1.306s	coverage: 75.4% of statements
hack/test-go.sh succeeded after 1490 seconds

real  24m49.412s
user 157m05.007s
sys    9m40.595s
```

Any thoughts on why you'd see such a large difference? Seems like we're setting things up the same way.

@smarterclayton I can't imagine that we have ~3x the unit tests in Origin as we do in k8s, but our tests take ~21min on Jenkins whereas the stuff under `/vendor` takes 7min. Thoughts?

**Comment by smarterclayton** [comment]
It could be the directory magic - maybe Tim's tests are reusing the same output dir, but ours aren't.

**Comment by thockin** [comment]
That was my guess.

**Comment by stevekuznetsov** [comment]
Let's adopt that magic. Sounds nice.

**Comment by thockin** [comment]
I asked teh golang-nute ML and was reassured that yes, this is effectively
how it works.

**Comment by jbeda** [comment]
See also: https://github.com/kubernetes/kubernetes/pull/30787/commits/8962a7c8e674478868ce146271c689b57017619b

**Pull request merged**
