### PR TITLE
Deleted a redundant line from #91275

### PR DESCRIPTION
**Pull request by KofClubs**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

There is a line of comment that should be deleted by #91275. This line of comment no longer points to any code. I deleted it.

#### Which issue(s) this PR fixes:

Refs #86843 #90747 #91275

#### Does this PR introduce a user-facing change?

NONE

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm
/assign @sjenning

**Review by mrunalp — APPROVED** [review]
/approve

**Pull request merged**
