### PR TITLE
Automated cherry pick of #75371: fix race condition issue for smb mount on windows

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #75371 on release-1.12.

#75371: fix race condition issue for smb mount on windows

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Comment by feiskyer** [comment]
/ok-to-test

@jingxu97 Could you help to approve the cherry pick? If you want this to be included in Kubernetes v1.12.8, please get it approved by end of this Friday.

/assign @jingxu97

**Comment by andyzhangx** [comment]
ping @jsafrane @jingxu97 for approval, thanks

**Comment by andyzhangx** [comment]
ping @jsafrane @jingxu97 for approval, thanks

**Pull request merged**
