### PR TITLE
WIP: godeps changes

### PR DESCRIPTION
**Pull request by lavalamp**
I did a godep restore / save cycle with current godep version. I am very skeptical about this change; opening the PR to see if it passes tests.

### CODE REVIEW

**Comment by eparis** [comment]
how did travis fail but jenkins unit pass?

**Comment by eparis** [comment]
I tried to do the same cycle in https://github.com/kubernetes/kubernetes/pull/21771

**Comment by eparis** [comment]
(and have a different diffstat)

**Comment by eparis** [comment]
pinning godep back to version v53 removes these problems...

@lavalamp what do you think if I pin it to version 53 in the verify check, and ask people to use version 53. That gets us unblocked and I can file some bugs with the godep people....

**Comment by lavalamp** [comment]
@eparis Do you have any idea why godeps wants to delete a bunch of dependencies?

**Comment by lavalamp** [comment]
Heh, when I wrote that github wasn't showing me your previous comments. Will look at your PR.

**Comment by lavalamp** [comment]
Yes, that sounds like a good plan.

**Pull request closed without merging**
