### PR TITLE
Use ip address from CNI output

### LINKED ISSUE #65756: Kubernetes obtains ip address from containers' eth0 instead of CNI output
/kind bug

In current implementation Kubernetes doesn't get ip address from CNI output,
it gets ip address from container's eth0 (network.DefaultInterfaceName) interface
in (network.GetPodIP). But there is possible use cases without eth0 inside container,
e.g. VhostUser CNI plugin, when it used w/o multus CNI plugin. Also there is no
agreement to keep interface exactly with the eth0 name inside the container.

Expected behaviour: obtain ip address from CNI output, due to there is use cases
w/o VETH pair, e.g. vhost-user type of ports. In any case relying on the name of
interface is not so robust. CNI spec says about VETH as none mandatory type
of interfaces.

Also CNI specification v0.3.0 says that the list of ip addresses is possible,
but that point is out of scope for this bug.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10 and higher
- Cloud provider or hardware configuration: doesn't matter
- OS (e.g. from /etc/os-release): doesn't matter
- Kernel (e.g. `uname -a`): doesn't matter
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by AlexeyPerevalov**
Before this patch Kubernetes obtains ip address from container's eth
device. But in case when containers work only with loopback device and
with vhostuser (it's not device it's UNIX domain socket file) Kubernetes
can't rely on this approach, it should rely on CNI output. Most of plugins
provide IP address of created port.

This patch also touches unit test, CNI spec declares ip field as mandatory
field of ADD/GET command output. But some users may relay on current behaviour
so code where ip is empty and obtained from container's eth is preserved,
but it's not covered in unit test.

Signed-off-by: Alexey Perevalov <a.perevalov@samsung.com>
Fixes #65756 
```release-note
NONE
```

### CODE REVIEW

**Comment by dcbw** [comment]
@AlexeyPerevalov thanks for the PR; the nsenter requirement should definitely go away.  I was holding off on doing something like this because I wanted to get the CNI GET support first (which is now done) and then to make kubelet/dockershim use the GET call and libcni's caching rather than doing it all internally in kubelet.

Also, I don't see where the podIPs get cleared from the map on pod teardown?

There may also be concurrency issues; you probably need to lock the podIP map as it could be accessed from multiple goroutines, for example if one pod is being added at the same time as PLEG loop is getting pod status.

**Comment by AlexeyPerevalov** [comment]
Thanks, for review, I'm in vacation now, I'll be able to fix comments tomorrow.

**Comment by AlexeyPerevalov** [comment]
I signed it

**Comment by AlexeyPerevalov** [comment]
I'll pull from new repo.

**Pull request closed without merging**
