### PR TITLE
Automated cherry pick of #101120: Upgrade kustomize-in-kubectl to v4.1.2

### PR DESCRIPTION
**Pull request by KnVerey**
Cherry pick of #101120 on release-1.21.

#101120: Upgrade kustomize-in-kubectl to v4.1.2

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

/kind bug

#### Does this PR introduce a user-facing change?

Please note that although the bump is to 4.1.2, the user-facing change is in 4.1.0. The remaining patch versions had to be cut for dependency compatibility with this repo. Hence the release note pointing to 4.1.0.

```release-note
Upgrades functionality of `kubectl kustomize` as described at https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.1.0
```

### CODE REVIEW

**Review by monopole — APPROVED** [review]
/lgtm

thanks!

**Comment by KnVerey** [comment]
@kubernetes/release-managers this PR is ready for cherry pick review. The motivation is specifically the Helm generator risk mitigation described in [the Kustomize release notes]( https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.1.0). This is the only cherry pick required, since the Helm generator did not exist in the versions of Kustomize that are bundled with older versions of kubectl.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
