### PR TITLE
Do not require tty in hyperkube build

### LINKED ISSUE #31412: Hyperkube build now requires a TTY
I can no longer build `hyperkube` as part of my continuous integration setup.

This is vital because we use `hyperkube` in `kubernetes-anywhere` and I build `hyperkube` as part of that process.

I believe the issue is here: https://github.com/kubernetes/kubernetes/commit/d711fd8764fc26041f82729e7b74c25738e7a55c#diff-86f22fb5b693949f04077054c41b762fR104

cc: @luxas

### PR DESCRIPTION
**Pull request by aaronlevy**
fixes https://github.com/kubernetes/kubernetes/issues/31412

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31490)

### CODE REVIEW

**Comment by luxas** [comment]
LGTM, any other opinions? Should this be marked v1.4?
For my curiousity, I'd like to know where a tty isn't available... 
So I know for the future

**Comment by aaronlevy** [comment]
@luxas for us it's a jenkins build. But I don't manage those machines, just noticed the job started failing.

If it's not v1.4 - this might not be necessary as I'm assuming the CNI builds will be ready by then. But if this doesn't block up the merge queue too much, it would be nice to not have to carry patches until then (or change our build to modify that line).

**Comment by luxas** [comment]
un-LGTM now as #31477 is on its way in.

This PR is before #31477 in the queue, so if I'd let this merge; #31477 would have to be rebased, which is completely unnecessary.

Thanks for the patch (and the explanation) anyway!

**Comment by asalkeld** [comment]
This should be closed.

**Pull request closed without merging**
