### PR TITLE
kubectl: fix golint warnings

### PR DESCRIPTION
**Pull request by tcharding**
**What this PR does / why we need it**:

Currently code in `pkg/kubectl` generates various `golint` warnings. The majority of these are for documentation and punctuation on error strings. 

This PR fixes the majority of the `golint` warnings for `pkg/kubectl` excluding subdirectories. Also, since there is an outstanding effort to move generators to a sub package this PR does not fix warnings around generator code.

**Special notes for your reviewer**:

This work was previously submitted as numerous small PR's but on request from @soltysh these have been closed and combined into a single big PR.

**Release note**:

```release-note
NONE
```
/sig cli
/kind cleanup

### CODE REVIEW

**Comment by cblecker** [comment]
```I1102 02:34:53.679] ========================
I1102 02:34:53.680] FAILED TESTS
I1102 02:34:53.680] ========================
I1102 02:34:53.680] hack/make-rules/../../hack/verify-bazel.sh
I1102 02:34:53.680] hack/make-rules/../../hack/verify-golint.sh
```

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/52805)

**Pull request closed without merging**
