### PR TITLE
kube-controller-manager: Add configure-cloud-routes option

### LINKED ISSUE #25602: kube-controller-manager ties node CIDR allocation with cloud route provisioning
kube-controller-manager currently has one flag, allocate-node-cidrs, which turns on two controllers:

1. A controller which assigns a CIDR to every node created
1. A controller which configures cloud routes for those nodes (on clouds that support this)

However I would like to do the CIDR allocation, without setting up the cloud routes.  In particular, AWS has a 50 node limit for cloud routes, so in order to support bigger clusters, I'm pondering setting up a simple complete graph of GRE tunnels between nodes, using a simple controller on each node that watches the nodes and sets up the tunnels.

One way to separate the two controllers would be to add a flag which turns off cloud route management, but defaults to true.  It would only come in to play when allocate-node-cidrs=true; then setting manage-cloud-routes=false would allow for kube-controller-manager to set podCIDR on nodes, but would not ask the cloud provider configure the routes.

```
fs.BoolVar(&s.ManageCloudRoutes, "manage-cloud-routes", true, "Should routes for Pod CIDRs be configured on the cloud provider.")
```

cc @thockin

### PR DESCRIPTION
**Pull request by justinsb**
This allows kube-controller-manager to allocate CIDRs to nodes (with
allocate-node-cidrs=true), but will not try to configure them on the
cloud provider, even if the cloud provider supports Routes.

The default is configure-cloud-routes=true, and it will only try to
configure routes if allocate-node-cidrs is also configured, so the
default behaviour is unchanged.

This is useful because on AWS the cloud provider configures routes by
setting up VPC routing table entries, but there is a limit of 50
entries.  So setting configure-cloud-routes on AWS would allow us to
continue to allocate node CIDRs as today, but replace the VPC
route-table mechanism with something not limited to 50 nodes.

We can't just turn off the cloud-provider entirely because it also
controls other things - node discovery, load balancer creation etc.

Fix #25602

### CODE REVIEW

**Comment by bprashanth** [comment]
```
./federation/apis/federation/types.generated.go up to date.
FAILED   ./hack/../hack/verify-codecgen.sh	447s
```

**Comment by justinsb** [comment]
Finally passed the integration tests - thanks for the heads-up @bprashanth :-)

Going to leave the e2e flake until I hear whether the PR is something we'll consider - not least because I suspect even if we accept the idea, we'll likely change the name.

**Comment by justinsb** [comment]
@thockin any thoughts?  Could support the general disaggregation of KCM; perhaps in that light it should be "enable-route-controller" (default true)?

**Comment by thockin** [comment]
LGTM

@mikedanese @cjcullen @Q-Lee FYI

if you rebase and get green before Monday, you're in.

**Comment by thockin** [comment]
also permission to self-lgtm when rebased and green

**Comment by mikedanese** [comment]
LGTM

**Comment by cjcullen** [comment]
Looks fine to me.

**Comment by justinsb** [comment]
Re-adding lgtm after rebase.

**Comment by colemickens** [comment]
Is there any reason to not allow the  case where:
 * I want to allocate Pod CIDRs myself, but,
 * I want cloudprovider to write the route table myself?

It's a use-case that we ran into today, it's mostly to unblock some testing of some half-baked functionality, but if I squint I could imagine someone wanting that configuration in a real cluster.

**Pull request merged**
