### PR TITLE
[gce_runner] use metadata file when values have special characters

### PR DESCRIPTION
**Pull request by dims**
Fix for https://github.com/kubernetes/test-infra/issues/31773

`PULL_REFS` has both `:` and `,`, let's use a file in this case and not try to do it in the `--metadata` (use `--metadata-from-file`)

/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by tzneal — APPROVED** [review]
/lgtm

**Review by akhilerm — APPROVED** [review]

**Comment by dims** [comment]
webhook missed the lgtm from @tzneal for some reason!

**Comment by akhilerm** [comment]
> webhook missed the lgtm from @tzneal for some reason!

I think the comment was first `lgtm` and then `/lgtm`. can see an edit history.

**Pull request merged**
