### PR TITLE
Eliminate redundant field in node controller manager

### PR DESCRIPTION
**Pull request by combk8s**
This PR eliminate redundant struct in node controller:
- 'knownNodeSet' in 'NodeController' is redundant, since the 'nodeStatusMap' has saved all kown nodes information. We can use 'nodeStatusMap' to determine whether the a new node is observed or an old node has been deleted.

### CODE REVIEW

**Comment by brendandburns** [comment]
Needs gofmt:

```
hack/verify-gofmt.sh
!!! 'gofmt -s' needs to be run on the following files: 
./pkg/controller/node/nodecontroller.go
```

**Comment by fgrzadkowski** [comment]
@combk8s First of all, thank you for this change!

As our bot suggested, you'll need to sign CLA. Please update this PR once you do this.

**Comment by combk8s** [comment]
I signed a CLA

**Comment by combk8s** [comment]
I signed a CLA

**Comment by combk8s** [comment]
CLA

**Comment by combk8s** [comment]
I used an alternative email, the CLA thing is strange

**Comment by combk8s** [comment]
I signed it!

**Comment by combk8s** [comment]
I signed a CLA

**Comment by combk8s** [comment]
Oh, I am sorry I used a different email address in the git commits than was used to sign the CLA. I have signen my CLA and resubmit it https://github.com/kubernetes/kubernetes/pull/14716, I will close this one.

**Pull request closed without merging**
