### PR TITLE
KEP 3836 - promote to beta

### PR DESCRIPTION
**Pull request by alexanderConstantinescu**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

https://github.com/kubernetes/enhancements/issues/3836 was promoted to beta in 1.29, see https://github.com/kubernetes/enhancements/pull/4258. I however forgot to update the feature gate in 1.29....I only realised this now when going over the KEP work for 1.30 :/

I am therefore updating the feature gate to beta here, following what was already agreed. 

/assign @thockin 
/sig network 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Promote KubeProxyDrainingTerminatingNodes to Beta 
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
https://github.com/kubernetes/enhancements/issues/3836
```

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by sftim** [comment]
Would this need a changelog entry?

**Comment by alexanderConstantinescu** [comment]
> Would this need a changelog entry?

Added a simple one indicating the promotion to Beta. Let me know if this is enough?

**Comment by sftim** [comment]
Changelog suggestion
```diff
-Promote KubeProxyDrainingTerminatingNodes to Beta
+Promoted the feature gate `KubeProxyDrainingTerminatingNodes` to beta
```

Please also submit a docs update PR - see https://kubernetes.io/docs/contribute/new-content/new-features/#ready-for-review-feature-gates

**Pull request merged**
