### PR TITLE
Pipe through the ability to set the external hostname for swagger URLs.

### LINKED ISSUE #3758: Swagger base path displays internal IP
The 'basePath' field is exposing the internal IP of the instance running the master. I.e. I get a 10.x.x.x. IP. The IP should be the external one, if possible. Otherwise clients outside the network of the master will be unable to form requests.

### PR DESCRIPTION
**Pull request by brendandburns**
Closes https://github.com/GoogleCloudPlatform/kubernetes/issues/3758

### CODE REVIEW

**Comment by brendandburns** [comment]
Rebased.

**Comment by nikhiljindal** [comment]
LGTM, Thanks!
Will merge when travis is green.

**Comment by nikhiljindal** [comment]
Travis and shippable are red because of TestSyncPodsDeletesWithNoPodInfraContainer which I think is flaky. Have restarted them just to be sure.

**Comment by brendandburns** [comment]
Rebased and resent.  That test passes on my machine.

**Pull request merged**
