### PR TITLE
Automated cherry pick of #23561

### PR DESCRIPTION
**Pull request by david-mcmahon**
Cherry pick of #23561 on release-1.2.

### CODE REVIEW

**Comment by bgrant0607** [comment]
Why are we cherrypicking this? The original PR isn't attached to the 1.2 milestone, isn't labeled cherrypick-candidate, has no description, and doesn't reference a P0 issue.

**Comment by david-mcmahon** [comment]
Fair questions, of course.  This is one of possibly a few changes that are infrastructure related. 
I think the test team has some of these occasionally too.  They don't fit into the product-level criteria for a cherrypick to a branch, but they avoid having to maintain "if branch" conditions in tools that operate on all branches.  

Let's come up with an official channel/process for funneling these few changes into the branch(es) that might come up from time to time.  Maybe we use another label like cherrypick-*-infra?

**Comment by bgrant0607** [comment]
I don't think we need a special process. There shouldn't be ANY PRs with no description whatsoever.

**Comment by david-mcmahon** [comment]
I updated the original PR with this text:
"This PR allows OUT_DIR, set (and modifiable) in the top level Makefile is honored by all the scripts that include common.sh. It also means that any script called directly can now modify the output directory default of _output."

Is this ok to put on the release-1.2 branch?

**Comment by bgrant0607** [comment]
Thanks. Labeled original PR with cherrypick-candidate, cherrypick-approved, and release-note.

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
