### PR TITLE
Retrieve username/password from basicauth section of kubeconfig

### PR DESCRIPTION
**Pull request by bprashanth**
I guess this is the ~~dumb~~ right thing to do?

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32814)

### CODE REVIEW

**Comment by pwittrock** [comment]
What is this fixing.  Has this been a critical issue for something / someone?

**Comment by bprashanth** [comment]
https://docs.google.com/document/d/1yv9tm5qeCqbyw5SWysHaXxSLDRZ-RmK8QRBrkbnh6Tg/edit#

**Comment by bprashanth** [comment]
Fixes the crashloop issue Wojciech described

**Comment by eparis** [comment]
you set the milestone to 1.3. do you want this in 1.4 and 1.3?

**Comment by bprashanth** [comment]
Yeah, but more importantly in 1.3, 1.4 will only matter when we do 1.5 and don't get the cluster lifecycle stuff by then (and it only allowed me to set a single milestone so i picked 1.3)

**Comment by gmarek** [comment]
Merging to unblock upgrade testing.

**Comment by fabioy** [comment]
@bprashanth This is marked cherrypick-candidate for 1.3. Is this still needed for 1.3? If so, please create a cherrypick PR.

**Pull request merged**
