### PR TITLE
vendor update: github.com/golang/protobuf

### PR DESCRIPTION
**Pull request by shiywang**
When I'm working on PR: https://github.com/kubernetes/kubernetes/pull/54782, I met a problem here: https://github.com/golang/protobuf/issues/372, which I think we need to update our vendor of protobuf
and I ask Dr. Stefan for suggestion, here is our coversation

shiywang [5:09 PM] 
hi, Dr. Stefan i'm sorry to bother, I have a simple question, I was working on a pr which need to use protobuf custom field, and I run into this problem here: https://github.com/golang/protobuf/issues/372  which I think is due to our codebase's protobuf vendor is too old `vendor/github.com/golang/protobuf`,  do you think I can update that vendor to lastest one ?  also I noticed there's also an extend package called `vendor/github.com/gogo/protobuf/proto` what's the releationship between those two ?  which one should I update ?

sttts
[5:11 PM] 
hi

[5:11] 
don't know much about the proto internals either, @claytonc is probably the only one

[5:12] 
create a vendor/github.com/golang/protobuf bump PR and assign it to him

shiywang [5:12 PM] 
sounds good, thank you sir

so 
/assign @smarterclayton 
for suggestion, thanks

```release-note
NONE
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
We use gogo/protobuf, and should continue using it.  It provides our high performance marshal and unmarshal work for protobuf.

**Comment by brendandburns** [comment]
@smarterclayton this is a version bump, not a new library.  We already also include `github.com/golang/protobuf` (https://github.com/kubernetes/kubernetes/tree/master/vendor/github.com/golang/protobuf)

So this PR LGTM, do you have other concerns?

**Comment by smarterclayton** [comment]
Yeah as long as it's a safe bump.

**Comment by shiywang** [comment]
ok, cool, I will submit a vendor update pr

**Comment by shiywang** [comment]
@brendanburns @smarterclayton PTAL, thanks

**Comment by brendandburns** [comment]
Given that everything is passing, I'm going to assume the bump is safe.

/lgtm
/approve no-issue

**Pull request merged**
