### PR TITLE
Remove unused func

### PR DESCRIPTION
**Pull request by chymy**
Signed-off-by: chymy <chang.min1@zte.com.cn>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Function NodeSelectorRequirementsAsFieldSelector is unused.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by zetaab** [comment]
just a comment here: if this function is not used anywhere inside k/k it might be that someone else is referring to this function because it is exported. Removing this will break these another things(?).

**Comment by chymy** [comment]
thanks for review
/close

**Pull request closed without merging**
