### PR TITLE
Pod affinity test clean up as AffinitInAnnotation is removed.

### PR DESCRIPTION
**Pull request by aveshagarwal**
**What this PR does / why we need it**:
These tests are already covered under "empty topologyKey" pod affinity test cases.
These test cases were added only to test the scenario when the AffinitInAnnotation
feature was disabled. Since AffinitInAnnotation is removed now, these test cases are
no longer needed as they are duplicate now.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

@kubernetes/sig-scheduling-misc  @bsalamat

### CODE REVIEW

**Comment by bsalamat** [comment]
/lgtm

@aveshagarwal Thanks for the cleanup!

**Comment by aveshagarwal** [comment]
@kubernetes/sig-scheduling-pr-reviews

**Comment by wanghaoran1988** [comment]
LGFM, thanks

**Comment by aveshagarwal** [comment]
@bsalamat @lavalamp could you help with approval?

**Review by timothysc — APPROVED** [review]
/lgtm 

/approve

**Pull request merged**
