### PR TITLE
fix some errors about changelog 1.11

### PR DESCRIPTION
**Pull request by yangjunmyfm192085**
Signed-off-by: JunYang <yang.jun22@zte.com.cn>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix some error hyperlinks.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
it is ok, besides this is an older release but it is good to have everything up-to-date

thanks

**Comment by yangjunmyfm192085** [comment]
> it is ok, besides this is an older release but it is good to have everything up-to-date
> 
> thanks

sorry,I think I may not understand what you mean too much,so I am still waiting the pr to be processed.
I checked it again this morning. 
Can you help me review it again, thanks.

**Comment by cpanato** [comment]
Hey @yangjunmyfm192085 , thanks for the PR. After looking again and checking the previous PR related to this change. In general, I don't think we should continue maintaining outdated documents, especially for [releases we no longer maintain](https://kubernetes.io/docs/setup/release/version-skew-policy/). Kubernetes 1.11 reached end-of-life, so I'm going to close this.

/approve cancel
/close

**Pull request closed without merging**
