### PR TITLE
AWS: make it possible to have multiple subnets in the same zone

### PR DESCRIPTION
**Pull request by manolitto**
It should be possible to have mutliple subnets in the same availability zone within one VPC.
Each subnet can have it's own associated route table.
Typical scenario with a public subnet accommodating a NAT instance and routing to the internet gateway:
- subnet "kube-subnet-1a" in zone "eu-west-1a" with route table "kube-rt"
- subnet "public-1a" in zone  "eu-west-1a" with route table "public-rt"

Solution:
- Annotate the subnet with "Role" = "kube-subnet"
- Search for route table already associated with the subnet

### CODE REVIEW

**Comment by mbforbes** [comment]
Same +cc @justinsb and temp assigned to @erictune (has context w/ other PR)

**Comment by erictune** [comment]
@mbforbes I'm out this week and next.  Reassigning to @thockin  for networking expertise.

**Comment by mbforbes** [comment]
Whoops, sorry about that @erictune—will route PRs elsewhere.

**Comment by thockin** [comment]
This has to be someone who know AWS

**Comment by thockin** [comment]
Sorry, I meant to @justinsb

**Comment by wojtek-t** [comment]
@manolitto are you going to proceed with this PR or can we close it?

**Comment by manolitto** [comment]
This PR is obsolete in the meantime, yes we can close it.

**Pull request closed without merging**
