### PR TITLE
fix a typo

### PR DESCRIPTION
**Pull request by maxwell92**
fix a typo

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33822)

### CODE REVIEW

**Comment by maxwell92** [comment]
@k8s-bot ok to test

**Review by krmayankk — APPROVED** [review]

**Review by errordeveloper — APPROVED** [review]
LGTM

**Comment by errordeveloper** [comment]
I'll cherry pick.

**Comment by errordeveloper** [comment]
Well, no, better if @maxwell92 can rebase.

**Comment by rmmh** [comment]
56ea178e7c77ab88b949107c420bc58d593143b3 got rid of the typo

**Pull request closed without merging**
