### PR TITLE
Update to using kubedns 1.17.3 image.

### LINKED ISSUE #101283: [sig-network] update client-go to 1.14+ in images
#### What happened:

the following images are using old client-go that would not work correctly starting 1.22+ if those images use in-cluster config(mounted service account token) to talk to kube-apiserver:
- ~k8s.gcr.io/k8s-dns-dnsmasq-nanny~
- ~k8s.gcr.io/k8s-dns-kube-dns~
- ~k8s.gcr.io/k8s-dns-sidecar~
- k8s.gcr.io/networking/ip-masq-agent-amd64

#### What you expected to happen:

if the above images use in-cluster config, they should use client-go 1.14+.

xref: https://github.com/kubernetes/kubernetes/issues/75551

/assign @thockin @bowei 
/cc @liggitt

### PR DESCRIPTION
**Pull request by prameshj**
#### What this PR does / why we need it:
Uses the latest kubedns version.

#### Which issue(s) this PR fixes:

Updates kube-dns-* images for #101283

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm

**Comment by prameshj** [comment]
Waiting on a kubetest cluster to verify that this works.

**Comment by liggitt** [comment]
@prameshj, any update?

**Comment by prameshj** [comment]
> @prameshj, any update?

Yes, I verified that this works.

/hold cancel

**Pull request merged**
