### PR TITLE
[Federation] Include Scales subresource in federation

### PR DESCRIPTION
**Pull request by irfanurrehman**
This PR implements second part of federated pod autoscaler.
This is on top of https://github.com/kubernetes/kubernetes/pull/38976.
The issue to handle the whole feature is #38974

cc @kubernetes/sig-cluster-federation
@mwielgus  @deepak-vij @nikhiljindal @quinton-hoole 

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by nikhiljindal** [comment]
If this is going to be alpha (which is what I assume), this should be disabled by default: https://github.com/kubernetes/kubernetes/issues/38593.
This should also have release notes.

**Comment by irfanurrehman** [comment]
@nikhiljindal apologies for the delayed response. Somehow missed this.
I saw ur comment on https://github.com/kubernetes/kubernetes/issues/38593 and saw that this PR referenced it.
Please let me know, if I can do something. (Meanwhile, I am sort of off next 4 days)

**Comment by eparis** [comment]
/approve
(my little piece)

**Comment by quinton-hoole** [comment]
@irfanurrehman Do we still need this?  I suspect so.  If so, please assign as appropriate.  Thanks.

**Comment by irfanurrehman** [comment]
closing as this is not needed anymore!

**Pull request closed without merging**
