### PR TITLE
rkt: Copy the /etc/hosts /etc/resolv.conf into pod dir before mounting.

### PR DESCRIPTION
**Pull request by yifan-gu**
rkt: Copy the /etc/hosts /etc/resolv.conf into pod dir before mounting.

This enables the container to modify the /etc/hosts/ /etc/resolv.conf without changing the host's ones.
With this PR, we now match the docker's behavior.

Fix https://github.com/kubernetes/kubernetes/issues/29022

cc @kubernetes/sig-rktnetes @quentin-m

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29024)

### CODE REVIEW

**Comment by euank** [comment]
LGTM, but would be nice to have a unit test (so some file-copy mocking). Unit testing parts of this code related to running pods is perhaps a bigger issue and different can of worms though.

**Comment by yifan-gu** [comment]
@euank Yeah, ideally we should be able to test the conversion between k8s pod and rkt pod. But that requires much more work, so would prefer to defer it now.

I tested manually on local cluster, this works as expected (the `/etc/resolv.conf` and `/etc/hosts` have the same content as the ones on the host, besides, modifying the `/etc/resolv.conf` and `/etc/hosts` doesn't change the contents of the files on the host.

**Comment by fabioy** [comment]
@yifan-gu Cherrypick approved. Please feel free to create a cherrypick PR. Thanks.

**Comment by fabioy** [comment]
This was cherrypicked in #29867. Removing label.

**Pull request merged**
