### PR TITLE
don't test kube-proxy in system resource container monitoring e2e

### LINKED ISSUE #17773: MonitorResources test is failing in flaky suite
For some reason it's failing with error: 
```
04:36:49   Expected error:
04:36:49       <*errors.errorString | 0xc20827f470>: {
04:36:49           s: "missing info for container \"/kube-proxy\" on node \"e2e-flaky-minion-ajl8\"",
04:36:49       }
04:36:49       missing info for container "/kube-proxy" on node "e2e-flaky-minion-ajl8"
04:36:49   not to have occurred
```
cc @wojtek-t @ixdy

### PR DESCRIPTION
**Pull request by mikedanese**
since it is running in a docker container now

Fixes #17773 cc @gmarek

### CODE REVIEW

**Comment by mikedanese** [comment]
Now i'm just getting
```
• Failure [19.706 seconds]
Resource usage of system containers
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/monitor_resources.go:140
  should not exceed expected amount. [It]
  /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/monitor_resources.go:139

  Expected
      <map[string]e2e.resourceUsagePerContainer | len:3>: {
          "e2e-test-mikedanese-minion-0bbz": {
              "/kubelet": {
                  Name: "",
                  Timestamp: {sec: 0, nsec: 0, loc: nil},
                  CPUUsageInCores: 0.0370422561846943,
                  MemoryUsageInBytes: 895651020,
                  MemoryWorkingSetInBytes: 157816422,
                  CPUInterval: 0,
              },
          },
          "e2e-test-mikedanese-minion-kcy7": {
              "/kubelet": {
                  Name: "",
                  Timestamp: {sec: 0, nsec: 0, loc: nil},
                  CPUUsageInCores: 0.034968315092566246,
                  MemoryUsageInBytes: 896801177,
                  MemoryWorkingSetInBytes: 159694848,
                  CPUInterval: 0,
              },
          },
          "e2e-test-mikedanese-minion-x70b": {
              "/kubelet": {
                  Name: "",
                  Timestamp: {sec: 0, nsec: 0, loc: nil},
                  CPUUsageInCores: 0.03474062510682582,
                  MemoryUsageInBytes: 896272793,
                  MemoryWorkingSetInBytes: 160859750,
                  CPUInterval: 0,
              },
          },
      }
  to be empty

  /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/monitor_resources.go:138
```

**Comment by mikedanese** [comment]
but that is also fixed when i multiply kubelet resource limit by 10.

**Comment by yujuhong** [comment]
LGTM. We may want to monitor the resource usage of kube-proxy as a pod, but let's get the test fixed first.

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by wojtek-t** [comment]
@mikedanese - thanks!

**Pull request merged**
