### PR TITLE
Move ixdy to emeritus

### PR DESCRIPTION
**Pull request by ixdy**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
I haven't really worked on kubernetes/kubernetes for a while, so I shouldn't be reviewing or approving changes in it. Moving myself to `emeritus_approvers`.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ixdy** [comment]
/assign @liggitt

for toplevel approval

**Comment by dims** [comment]
thanks for everything that you have done for us @ixdy !!! 😍

**Comment by ixdy** [comment]
/retest

I'd forgotten how frustrating it is to merge anything in k/k.

**Comment by BenTheElder** [comment]
thank you jeff

**Comment by mkumatag** [comment]
Thanks @ixdy for all your help.

**Pull request merged**
