### PR TITLE
Add KUBE_COVER help to "make test"

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Add help info on `KUBE_COVER` to tell contributors how to run test with code coverage.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
/sig contributor-experience

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by spxtr** [comment]
I'm surprised that this actually works. The code that does this is [pretty amazing](https://github.com/kubernetes/kubernetes/blob/master/hack/make-rules/test.sh#L266-L310).

/lgtm
/approve no-issue

**Comment by xiangpengzhao** [comment]
It indeed works and is very useful :)

**Pull request merged**
