### PR TITLE
Add KnVerey as a sig-cli reviewer

### PR DESCRIPTION
**Pull request by eddiezane**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR adds @KnVerey as a sig-cli reviewer.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by thockin** [comment]
Happy to approve once there's an LGTM

**Review by soltysh — APPROVED** [review]
/lgtm
@thockin go for it :smiley:

**Pull request merged**
