### PR TITLE
[WIP] kubectl convert converting externals

### PR DESCRIPTION
**Pull request by yue9944882**
**What this PR does / why we need it**:

internal -> external in kubectl convert

/cc @soltysh @deads2k 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
conversion goes through internal objects. it is not possible to convert from one external type directly to another. just referencing the external scheme will not directly convert objects.

**Comment by yue9944882** [comment]
> conversion goes through internal objects. it is not possible to convert from one external type directly to another. 

@liggitt I thought we could make it by registered conversion functions. `kubectl convert` might need a lot more changes. 😇 Working on it

**Comment by yue9944882** [comment]
@liggitt Yeah, sadly I got stuck right here. `kubectl convert` seems imposible without internals

**Pull request closed without merging**
