### PR TITLE
Add a QPS limiter to the kubernetes client.

### PR DESCRIPTION
**Pull request by brendandburns**
This is a starting point.  I'm open to other settings for max QPS (or alternately setting it via flag differently for different binaries)

See #5865

### CODE REVIEW

**Comment by smarterclayton** [comment]
Does this have to be inside rest client?  Would we expect qps to be stored in client config on disk?  Otherwise RESTClient is designed to be wrapped, so could this be either a wrapper on RESTClient?  Kube Client should/can take an interface for RESTClient (although I may not have completed that refactor yet).

**Comment by vmarmol** [comment]
Assigning to @smarterclayton, feel free to reassign :)

**Comment by brendandburns** [comment]
There is no RESTClient interface yet, so I don't think the re-factor is complete.  RESTClient is really the only place where this is possible to store this for now, since it is the central point that all of the other client interfaces route through.

I'd rather not gate this PR on that refactor.  I can plumb this up into a config flag if you want me to.

(```gofmt'd``` now too...)

Thanks!
--brendan

**Comment by smarterclayton** [comment]
There is, but it's in pkg/resource.

I'm fine with this as a start point as long as you add a TODO to hoist it out of client.

----- Original Message -----

**Comment by smarterclayton** [comment]
pkg/kubectl/resource i meant

----- Original Message -----

**Comment by brendandburns** [comment]
Fixed the test, and added a TODO.  ptal.

Thanks!
--brendan

**Comment by brendandburns** [comment]
ok, fixed tests for realz...

**Comment by brendandburns** [comment]
Switched to the new RateLimiter::Accept() method.

**Comment by satnam6502** [comment]
What's the relation between this and `Retry-After` ?

**Comment by brendandburns** [comment]
ugh ```test-cmd.sh``` is failing on shippable/travis but not my machine.  @smarterclayton any suggestions for debugging?

**Comment by smarterclayton** [comment]
Usually it's not having enough cpu - you can set maxprocs or severely cpu constrain the resources for test-cmd to emulate it.  I run it on a one cpu vm.

**Comment by brendandburns** [comment]
Ok, I updated test-cmd.sh, it was using ```delete rc <foo>``` not ```stop rc <foo>```

ptal
Thanks
--brendan

**Comment by smarterclayton** [comment]
LGTM, you can self merge because I'm not at my laptop

**Comment by timothysc** [comment]
Can folks please label this as perf for tracking.

**Comment by roberthbailey** [comment]
@timothysc done.

**Comment by fgrzadkowski** [comment]
Side effect of this PR is that density test is creating pods much slower than earlier (~6 pods per second). For 50 node cluster and rc with 1500 replicas (30 pods per node) this gives 300 seconds just to create rc.

The same applies to stopping rc and scheduling.

Is this intentional?

**Comment by wojtek-t** [comment]
As discussed offline with Filip I think that we should increase the limits.
Currently (in a healthy situation) scheduler is able to schedule at least 10 pods per second. We shouldn't block the healthy situation and allow only 2-3 bindings per second, because of throttling (see #3954) [2-3 bindings per second is what experiments show with current throttling].
So I think that increasing the limit by, say, 5x is what we should do here.

I'm not sure what to do with replication controller - I think that we should increase the limit, but it's more subtle here. We definitely will be throttling such cases (i.e. resizing from 0 to 1500) but I'm not sure how long it should take for replication controller. But we definitely don't want to make it slower than the scheduler can process them.

**Comment by timothysc** [comment]
It seems weird to me that we are sprinkling magic numbers in vs. doing backoffs.

**Comment by smarterclayton** [comment]
Derek and I were talking - all of the controllers in the controller-manager are sharing one client.  Maybe we should have multiple per cm.

**Comment by fgrzadkowski** [comment]
@smarterclayton I don't think it'd help. Even with a separate client we'd be able to create 5 pods per second.

**Comment by smarterclayton** [comment]
I was more concerned with RC preventing other controllers from running.  There's no "fair" sharing if the have the same limiter, so Derek and my concern was that the replication controller manager would starve other things like the ResourceQuota and ResourceUsage controllers, which means that it's potentially possible for those *never* to get updated (in theory).

----- Original Message -----

**Pull request merged**
