### PR TITLE
First draft of roadmap to 1.0 update

### PR DESCRIPTION
**Pull request by thockin**
I tried to incorporate everything we talked about on Friday.  I wasn't sure how or if to list general UX friction or overall reliability.

I tried to keep it short and sweet - not a worklist (which is instantly obsolete).  It's possible I went too far.

I tried to link to issues as much as I could, but I admit I got tired at some point - could use more links if people know them.

### CODE REVIEW

**Comment by pires** [comment]
@thockin will you include the proxy cache thing in this roadmap?

**Comment by thockin** [comment]
I don't think the image cache in critical for a 1.0 launch.  It's a very
neat idea, but I'm hoping it can be solved by community rather than by the
core team - we're stretched thin as it is.

**Comment by sidharta-s** [comment]
@thockin There seems to be no mention of networking in the updated roadmap - are "a kick the tires implementation"  and "Clean factoring of a la carte networking functionality" out of scope for 1.0?

**Comment by smarterclayton** [comment]
Tim, we should discuss "plug points" so that someone can integrate networking into the Kubelet as 1.0, but I don't think we have to block 1.0 on having those plug points implemented (especially if we can't agree what they are).

**Comment by bgrant0607** [comment]
@sidharta-s @smarterclayton Yes, significant changes to networking are out of scope. It's just a matter of prioritization. Something>>nothing. We're trying to cut to the minimal set of improvements needed to serve some useful workload. There will be plenty left to do beyond 1.0.

**Comment by bgrant0607** [comment]
LGTM

**Comment by thockin** [comment]
@sidharta-s kick-the-tires is partially subsumed by Platforms, and partially evicted from the 1.0 plan.  I don't think it is critical to 1.0 to have an uber-SDN API if we have decent support for a few platforms AND networking on them.

@smarterclayton I agree we need to discuss, and hopefullyhave those extension points ready.  I don't think we'd block 1.0 just for those extension points though.

Can I get one more LGTM before committing this?

**Comment by smarterclayton** [comment]
That's a SGTM and a LGTM

**Pull request merged**
