### PR TITLE
Tighten validation of mirror pod annotations

### PR DESCRIPTION
**Pull request by liggitt**
Tightens validation for pods with a mirror pod annotation:
1. spec.nodeName must be set
2. makes the mirror pod annotation immutable
3. starts validating pod-specific annotations during pod status update

None of these changes affect usage of the mirror pod annotation by kubelets, which only set it on pod creation (verified this is true back to 1.5.x)

the second commit updates the pod validation tests to look for specific error messages (best reviewed ignoring whitespace changes)

This is the validation portion of https://github.com/kubernetes/community/blob/master/contributors/design-proposals/kubelet-authorizer.md and https://github.com/kubernetes/features/issues/279

```release-note
Mirror pods must now indicate the nodeName they are bound to on creation. The mirror pod annotation is now treated as immutable and cannot be added to an existing pod, removed from a pod, or modified.
```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/sig-auth-pr-reviews @kubernetes/sig-node-pr-reviews

**Comment by liggitt** [comment]
@k8s-bot kubemark e2e test this

**Comment by deads2k** [comment]
lgtm

**Comment by timstclair** [comment]
/lgtm
/approve

Nice!

**Comment by smarterclayton** [comment]
/approve

API changes LGTM - annotation move to public package decoupled from kubelet.

**Pull request merged**
