### PR TITLE
Fixes for update-api-reference-docs.sh

### PR DESCRIPTION
**Pull request by pmorie**
@k8s-oncall Could someone take a look at this?

cc @bgrant0607 @thockin @eparis @ncdc

### CODE REVIEW

**Comment by ncdc** [comment]
Why privileged?

**Comment by pmorie** [comment]
@ncdc I get permissioned denied without it.

**Comment by ncdc** [comment]
What's the error message?

**Comment by pmorie** [comment]
@ncdc 

```
$ hack/update-api-reference-docs.sh 
Generating api reference docs at /home/pmorie/code/kubernetes/hack/../docs/api-reference
Reading swagger spec from: /home/pmorie/code/kubernetes/hack/../api/swagger-spec/
--2015-10-22 20:26:27--  https://raw.githubusercontent.com/kubernetes/kubernetes/master/pkg/api/v1/register.go
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 23.235.46.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|23.235.46.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4250 (4.2K) [text/plain]
Saving to: ‘register.go’

     0K ....                                                  100% 66.0M=0s

2015-10-22 20:26:27 (66.0 MB/s) - ‘register.go’ saved [4250/4250]

cp: cannot stat ‘/swagger-source/v1.json’: Permission denied
```

**Comment by ncdc** [comment]
While privileged is a quick fix, it seems like more of a hammer than we need? Can we figure out why the bind mount has the wrong permissions, or if it's an selinux denial?

**Comment by pmorie** [comment]
The AVC log is clean on my system.  It might be a dontaudit thing, I will look later and we can just hold off on this for now, but this is supremely annoying that it doesn't get run in update-all.sh.

**Comment by pmorie** [comment]
@ashcrow is going to see if he can repro

**Comment by eparis** [comment]
while it could be selinux, it could also be that the container is running as uid=0, the file is owned by uid!=0, but the container does not have CAP_DAC_OVERRIDE....

**Comment by ashcrow** [comment]
I reproduced it on Fedora 22. Same output.

- Nothing of note in ```audit.log```
- ```--add-cap DAC_OVERRIDE``` produced the same error results

**Comment by pmorie** [comment]
I wonder if this is a docker bug.  I'm going to recut this PR later tonight to just be the update to update-all.sh

**Comment by nikhiljindal** [comment]
sounds good!

**Comment by bgrant0607** [comment]
cc @caesarxuchao

**Comment by bgrant0607** [comment]
Without privileged, it depends on the file/path permissions and ownership. On our images, containers run as the docker user by default. A user can't even access the docker socket without either being root (sudo) or in the docker group.

**Comment by bgrant0607** [comment]
My guess is that even with --privileged, this script fails for most people.

**Comment by caesarxuchao** [comment]
@ashcrow, just out of curious, do you know why the command fails even with `--add-cap DAC_OVERRIDE`, doesn't that mean "Bypass file read, write, and execute permission checks"?

**Comment by ashcrow** [comment]
@caesarxuchao correct, it does mean that. I'm not sure to be honest. It may end up being a dontaudit thing as noted above. I'm going to try a few more tests on a clean VM to see if I can get any more helpful data.

**Comment by ashcrow** [comment]
```--cap-add ALL``` also gave the same results.

On a Fedora 22 VM I set selinux to permissive and the containers worked as expected. However, no useful information was provided in the audit log ... I think the dontaudit note @pmorie is right.

**Comment by eparis** [comment]
two things, looks like we need `--rm` on the run command so your don't leave dead containers behind.
also adding `:z` to the end of the `-v` mounts will take care of the selinux/perm problem.  Although I don't have a non-selinux system to make sure `:z` doesn't cause an error there....

**Comment by ashcrow** [comment]
@eparis I can spin up a VM and test ```:z```  without selinux. Doing so now.

**Comment by ashcrow** [comment]
OS: Fedora 22
- Confirmed adding ```:z``` to ```-v``` switches fixes the issue with selinux enabled
- Confirmed adding ```z``` to ```-v``` switches fixes the issue with selinux disabled

**Comment by eparis** [comment]
/me is not sure how the DAC checks are passing, but they seem to be working.

**Comment by ashcrow** [comment]
Pulled @pmorie's work and added @eparis's fixes in https://github.com/kubernetes/kubernetes/pull/16159

**Pull request closed without merging**
