### PR TITLE
replace deprecated sets.String to sets.Set

### PR DESCRIPTION
**Pull request by wujunwei**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
`sets.Set` is newly implemented, and `sets.String` got marked as deprecated.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bart0sh** [comment]
@wujunwei Thank you for your PR!

Please, try to include more similar changes into the PR.
hint:
```
$ git grep sets.String ./pkg/kubelet/ |wc -l
101
```

Please read [our trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits) for more details.

**Comment by wujunwei** [comment]
> Please, try to include more similar changes into the PR.

Got it ! PTAL :)

**Comment by wujunwei** [comment]
I have merge the latest branch and fix the conflicts, PTAL  @bart0sh

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Comment by wujunwei** [comment]
This PR contains lots file of `kubelet`  Rebase is required almost every three days. so what should I do can make it merged more quickly ？@bart0sh

**Comment by bart0sh** [comment]
@wujunwei 
> can make it merged more quickly 

It depends on approvers. I've already reviewed this PR and assigned approvers. All you can do is to keep your PR ready for merge and gently ping approvers to look at it.

@liggitt can you look at this PR please?

**Comment by liggitt** [comment]
cleanup PRs are appreciated, but don't usually take priority over reviews of bugfixes or enhancements targeting the current milestone

**Comment by liggitt** [comment]
I didn't look at this closely, but wondered whether any of these replacements are in code paths that are exercised frequently enough that increased cost of generics would be an issue (xref https://github.com/kubernetes/community/blob/master/sig-architecture/generics.md#recommendations-for-reviewers)

**Comment by bart0sh** [comment]
@liggitt Thank you for taking a look. Very much appreciated.

@wujunwei Please, make sure this PR doesn't cause performance issues. It would make sense to divide it to smaller PRs to avoid frequent rebases.

**Comment by wujunwei** [comment]
刚开始

> @liggitt Thank you for taking a look. Very much appreciated.
> 
> @wujunwei Please, make sure this PR doesn't cause performance issues. It would make sense to divide it to smaller PRs to avoid frequent rebases.

I did this at first, but you suggested that trying to include more similar changes into the PR https://github.com/kubernetes/kubernetes/pull/115007#issuecomment-1381354638

**Comment by bart0sh** [comment]
> I did this at first, but you suggested that trying to include more similar changes into the PR

Sorry about that. At that point it looked feasible to do. Now, 2 days before the code freeze - not so much.

However, dividing or not dividing this PR is a minor thing. Most important is to follow @liggitt's suggestion.

**Comment by wujunwei** [comment]
Got it, I will do a benchmark about it  and reopen it again.

**Pull request closed without merging**
