### PR TITLE
client-go: add missing template functions and types for extensions

### PR DESCRIPTION
**Pull request by skitt**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

Now that imports aren't automatically added, the `client-go` generator produces broken code for extensions since it references a few functions and types directly without declaring them properly (`klog.Warningf`, `time.Duration`, `time.Second`).

The generated code also references `c.client` and `c.ns` which are no longer accessible following the generic refactor.

This fixes both issues by adding missing template functions and types, and going through the appropriate getters.

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/cc @BenTheElder @jpbetz 

@skitt since when is this a regression? 1.31, 1.30?

**Comment by skitt** [comment]
Actually I can answer my own question — if we want to cherrypick the fix back to 1.31 then of course it has to be a specific PR.

**Comment by skitt** [comment]
[This specific commit](https://github.com/kubernetes/kubernetes/pull/127292/commits/1ca571702f0b2c190136ef7f1cd6ffe5d21d27ce) fixes another bug in extension handling, but I haven’t checked whether it’s a regression — it’s possible that these specific extensions never worked.

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Comment by skitt** [comment]
@thockin there was a merge conflict, this needs a new lgtm if you don’t mind!

**Comment by aojea** [comment]
@skitt did you finally merge the PR that validated the generated code?

**Comment by skitt** [comment]
> @skitt did you finally merge the PR that validated the generated code?

@aojea no, that’s still open (#127472), I’ll rework it on top of this taking the review comments into account.

**Pull request merged**
