### PR TITLE
Resolves #59015, Scheduler: Add support for EBS types t3, r5, & z1d

### LINKED ISSUE #59015: Number of NVMe disks attachable is lower than max predefined count for EBS
Kubernetes's scheduler defined a default limit of 39 volumes for EBS disks per node (`DefaultMaxEBSVolumes`) but this limit is far lower  for NVMe disks (something like 25-28). We need to find out why and if we should document this.

### PR DESCRIPTION
**Pull request by cuppett**
Fixes #59015

The new t3, r5, r5d and z1 need matched as well according to this:

From current AWS documentation:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/volume_limits.html

T3, C5, C5d, M5, M5d, R5, R5d, and z1d instances support a maximum of
28 attachments, and every instance has at least one network interface
attachment. If you have no additional network interface attachments on
these instances, you could attach 27 EBS volumes.

**Release note**:

```NONE

```

### CODE REVIEW

**Comment by cuppett** [comment]
@misterikkit I had to open new PR based on original. I think I've addressed all your comments now. Thanks!

**Comment by gnufied** [comment]
@saad-ali @childsb can we add this to 1.12 milestone? It will be important to get this fixed in 1.12 because fixes for some of the recent security vulnerabilities are only available in newer instance types.

**Comment by gnufied** [comment]
For scheduler side of things.

/assign @aveshagarwal

**Comment by gnufied** [comment]
since this is a bug fix for newer AWS instance types. 

/priority critical-urgent

**Comment by justinsb** [comment]
cc @mikesplain and @sethpollack - would be great to get this into an API so it isn't tied to a k8s release!

**Pull request merged**
