### PR TITLE
Update dependencies: aws-sdk-go to 1.6.10; also cadvisor

### PR DESCRIPTION
**Pull request by dashpole**
updating cadvisor mainly to include [this bugfix #1558](https://github.com/google/cadvisor/pull/1558)

Because cadvisor vendors a newer version of aws than kubernetes, the aws dependency needed to be updated as well.
cc: @justinsb @zmerlynn @timstclair

### CODE REVIEW

**Comment by timstclair** [comment]
I think we should consider splitting the aws update into a separate PR. Also, the cAdvisor update to the AWS API didn't change cAdvisor code at all, so I think you should be able to update cAdvisor without the AWS dependency.

**Comment by justinsb** [comment]
I don't know how you got it to go green, but I'm not going to look a magic gift horse in the mouth.

/lgtm

**Comment by dashpole** [comment]
Oh, its going to remove the lgtm because I dont have a release note

**Comment by dashpole** [comment]
@k8s-bot cvm gke e2e test this
@k8s-bot gci gke e2e test this
@k8s-bot kops aws e2e test this

**Comment by dashpole** [comment]
@calebamiles this is the PR that updated the cAdvisor dependency.  However, IIRC, this introduced problems with the AWS builds, and may not be a clean cherrypick.  @justinb, is this safe to cherrypick into 1.4?

**Comment by calebamiles** [comment]
Thanks @dashpole, @justinsb would this be ok to cherry pick onto the {1.4, 1.5} release branches?


**cc: @euank, @saad-ali, @jessfraz**

**Comment by justinsb** [comment]
Updating aws-sdk-go should be fine.  I don't believe we had any genuine problems, just problems with godeps.

I presume the motivation is the cadvisor fixes?

**Comment by dashpole** [comment]
@justinsb yes, specifically a fix that prevents it from leaking goroutines if the user doesnt have the "find" command.

**Comment by jessfraz** [comment]
whoa this is pretty big is it necessary for 1.4

**Comment by jessfraz** [comment]
updating the deps in the release branches is not exactly simple/fun, is this fixing a specific bug

**Comment by dashpole** [comment]
This fixes [cadvisor #1558](https://github.com/google/cadvisor/pull/1558).  I am not quite sure what constitutes a "neccessary" bug fix.  This issue is pretty major for those experiencing it, as it leaks goroutines if the image doesnt have GNU find.

**Comment by jessfraz** [comment]
is something shelling out to `find`?

**Comment by dashpole** [comment]
Yes, the way that we estimate inode usage inside a container's writeable layer uses the find command.

**Comment by jessfraz** [comment]
ok I guess we can cherrypick, thanks for the explanation, i might send a PR to cadvisor :)

**Comment by dashpole** [comment]
If you are curious, we are considering doing this in pure go instead of using find.  https://github.com/google/cadvisor/pull/1576

**Comment by jessfraz** [comment]
oh sweet!

**Comment by dashpole** [comment]
@jessfraz any idea if this was cherrypicked?

**Pull request merged**
