### PR TITLE
minor cleanup for apiserver/errors.go

### PR DESCRIPTION
**Pull request by xiang90**
1. cleanup the function
2. cleanup its test

### CODE REVIEW

**Comment by fabioy** [comment]
Could you rebase it to a single commit?Thank you.

**Comment by xiang90** [comment]
@fabioy Done. PTAL.

**Comment by fabioy** [comment]
Thank you. Change looks straighforward, but I'll let someone from apiserver take a look.

**Comment by erictune** [comment]
@davidopp ping

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
