### PR TITLE
add andyxning to podgc owner reviewers

### PR DESCRIPTION
**Pull request by andyxning**
**What type of PR is this?**
/kind cleanup
/sig contributor-experience

**What this PR does / why we need it**:
This PR updates OWNERS for [podgc](pkg/controller/podgc) pkg by adding myself @andyxning . The PR https://github.com/kubernetes/kubernetes/pull/92796 has been raised for more than 15 days, but it seems that the current owners @foxish and @gmarek are not reachable. And no one can help review the PR which is upset.

I am willing to take care about reviewing and approve code about podgc.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by andyxning** [comment]
Friendly ping.

**Comment by BenTheElder** [comment]
/uncc
I'm not appropriate to approve this.

**Comment by mrbobbytables** [comment]
Sorry, caught up when I saw Ben's uncc.
Agree bumping them to emeritus would probably be best. The next escalation point would be to go up the [controllers dir OWNERS](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/OWNERS)
/cc @cheftako @deads2k

**Pull request closed without merging**
