### PR TITLE
Automated cherry pick of #63492: Always track kubelet -> API connections

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #63492 on release-1.9.

#63492: Always track kubelet -> API connections

### CODE REVIEW

**Comment by liggitt** [comment]
holding to let the master PR make it through serial/soak/scale tests

**Comment by mbohlool** [comment]
This will not get into 1.9.8 patch release. Please contact me if you think it should be otherwise it will be included in next patch release.

**Comment by liggitt** [comment]
/milestone v1.9
@mbohlool can we unhold this now?

**Comment by mbohlool** [comment]
@liggitt hold cancelled. still needs LGTM/Approval.

**Comment by johanneswuerbach** [comment]
Friendly ping :-). This is a blocker for us updating from 1.8 ~> 1.9.

**Comment by stephanlindauer** [comment]
Another friendly ping ;)
Can we get an ETA when this will be patched in 1.9?

**Comment by mbohlool** [comment]
Deadline for 1.9.9 is next Tuesday. If it get merged before that, it will be included in 1.9.9 patch release.

**Pull request merged**
