### PR TITLE
Demote e2e test as per #10792

### PR DESCRIPTION
**Pull request by ghost**
Demote e2e test as per #10792.

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@ixdy @yujuhong for review and merge please.   This should make e2e runs considerably less noisy.

**Comment by yujuhong** [comment]
There are quite a few flaky tests. What's our criteria on demoting test?

**Comment by yujuhong** [comment]
More clearly, I saw a few tests that rely on getting /containerLogs through proxy also failing sporadically:
 - Docker Container should be able to override the image's default commmand (docker entrypoint)
 - Variable Expansion should allow substituting values in a container's args

Should we demote them all?

**Comment by quinton-hoole** [comment]
I'm starting at the top of the list (ranked by flakyness) and working my way down.  Next on my list is "Docker Containers should be able to override the image's default command".  Let me know fi you have any other favorites :-)

**Comment by quinton-hoole** [comment]
Yes,, "Variable Expansion..." is third on my list.

**Comment by yujuhong** [comment]
@quinton-hoole, I was just wondering if we had a explicit threshold :)

**Comment by quinton-hoole** [comment]
Good point.  The threshold is not written down anywhere, but I tend to use 95% as a hard cutoff per test.  Any test that has failed more than once in the past 30 runs tends to cause too much noise.

**Comment by yujuhong** [comment]
The PR looks good to me. Will check jenkins after it's done. I was just curious about the procedure because I think we need one (if there isn't any) :)

**Pull request merged**
