### PR TITLE
Fix compiler error in test/e2e_node/utils_linux.go

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

e2eCriProxy is declared in test file.
image

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by zhifei92** [comment]
@carlory  Thank you for your feedback. I think it's better to `rename utils_linux.go` to `utils_linux_test.go`.

**Comment by toVersus** [comment]
A fix with a different approach has already been proposed in https://github.com/kubernetes/kubernetes/pull/128514.
/cc @hoskeri

**Comment by carlory** [comment]
@toVersus  Sorry, I don't know that PR. Thanks for your quick fix. 

It may not be better to make e2eCriProxy a parameter because e2eCriProxy is a global variable, and we can use it immediately. It will be easier to use.

Can you follow @zhifei92's suggestion to update your PR? 

If you want to do it, I will close this PR. Sorry again for my mistake.

@zhifei92 A small question how to name a file for e2e tests, `*.go` or `*_test.go`? I feel like the file names in this directory are a bit confusing

**Comment by SergeyKanzhelev** [comment]
approved other PR

/close

**Comment by zhifei92** [comment]
> It may not be better to pass e2eCriProxy as parameter because e2eCriProxy is a global variable, and we can use it immediately. It will be easier to use.

I agree with this point of view.

> A small question how to name a file for e2e tests, *.go or *_test.go? I feel like the file names in this directory are a bit confusing

As helper functions for e2e tests, naming them with _test.go is reasonable. We can add some comments to clarify their purpose.

**Comment by SergeyKanzhelev** [comment]
If you have a better solution, please propose the PR. Less globals we have assumed - the better from my point of view. I would NOT suggest to spend a lot of time on this as it will be a trivial edit and will fall under trivial edits policy.

**Pull request closed without merging**
