### PR TITLE
Condition is always 'false' because 'err' is always 'nil' in top_pod.go

### PR DESCRIPTION
**Pull request by chymy**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Condition is always 'false' because 'err' is always 'nil' in top_pod.go
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by dougsland — COMMENTED** [review]
looks like a dup of lines 178-180
/lgtm

**Comment by chymy** [comment]
/assign @brianpursley 
Thanks

**Review by brianpursley — APPROVED** [review]

**Comment by chymy** [comment]
/assign @seans3 
Thanks

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
