### PR TITLE
Restrict functions and structs that aren't used outside of the nodecontroller to have package private scope

### PR DESCRIPTION
**Pull request by roberthbailey**
This makes reasoning about the code in this package much simpler.

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM, big improvement

**Comment by davidopp** [comment]
LGTM

**Comment by wojtek-t** [comment]
Nice - can you please rebase so that I can merge it?

**Comment by roberthbailey** [comment]
Rebased, but I noticed that a couple of the unit tests are failing locally (both on this branch and at head). I'm happy to wait until those are fixed at head and rebase again so that travis / shippable pass on this PR before it goes in.

**Comment by erictune** [comment]
@roberthbailey please rebase.

**Comment by roberthbailey** [comment]
Rebased (again).

**Comment by wojtek-t** [comment]
All tests passing - merging now.

**Pull request merged**
