### PR TITLE
dra: cleanup manager unit tests

### PR DESCRIPTION
**Pull request by tmilox**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

If applied this commit will remove unused variables during unit tests.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bart0sh** [comment]
/lgtm

@mrunalp @klueska @derekwaynecarr @dchen1107 please, approve. thanks.

**Comment by bart0sh** [comment]
@mrunalp @klueska This is a trivial cleanup PR. Can you approve it, please?

**Comment by klueska** [comment]
Sorry for the delay
/lgtm
/approve

**Pull request merged**
