### PR TITLE
Support passing a proxy to client-go with --proxy-network-type and --proxy-address

### PR DESCRIPTION
**Pull request by jac-stripe**
**What this PR does / why we need it**:
This PR adds the ability to route client-go traffic through a proxy. This allows users of e.g. kubectl to route traffic through a unix socket with `--proxy-network-type=unix --proxy-address=/tmp/sock`, similar to how curl supports a `--unix-socket` option.

**Special notes for your reviewer**:
Unfortunately kubernetes is quite behind on mergo versions, and mergo is used quite extensively. Given that mergo functionality is different in newer versions and we actually _rely_ on the old functionality, I put in a small hack with a TODO to avoid upgrading mergo. Upgrading will probably be a big job, and I hope it won't block this PR.

**Release note**:

```release-note
Adds a via-unix-socket option to client-go to allow routing outgoing client-go traffic through a unix-socket
```

### CODE REVIEW

**Comment by jac-stripe** [comment]
I should have CLA now

**Comment by eparis** [comment]
Can you help me understand why you want this and what you are doing with it?

**Comment by eparis** [comment]
@kubernetes/sig-cli-maintainers new flags to kubectl

**Comment by liggitt** [comment]
is there an associated proposal with use cases for this?

**Comment by jmillikin-stripe** [comment]
The primary use case for this PR is to have kubectl access the API via an authenticating HTTP proxy. Instead of specifying the TLS certificates directly in the kubeconfig file, we want TLS credentials to be injected into the requests by the proxy.

Hardcoding it to be a UNIX socket is too specific to Stripe's setup, so I've asked jac to rewrite this PR a bit. Ideally we would have a `proxy` key in the kubeconfig, like this:

```yaml
clusters:
- name: some-cluster
  cluster:
    server: https://1.2.3.4
    proxy: https://tls-proxy.corp
- name: other-cluster
  cluster:
    server: https://5.6.7.8
    proxy: unix:/some/local/socket
```

Exact syntax of the proxy address is undetermined -- suggestions welcomed. Is there a standard for these sorts of addresses in k8s already?

**Comment by liggitt** [comment]
kubectl should support standard http_proxy/https_proxy envvars already

**Comment by jmillikin-stripe** [comment]
> kubectl should support standard http_proxy/https_proxy envvars already

Is there a way to set those per-cluster in the config file?

**Comment by liggitt** [comment]
no

**Comment by jmillikin-stripe** [comment]
OK, it'd be nice if we could have the details for connecting to a particular cluster API endpoint be stored entirely in the config file, instead of partially extracted from the environment.

**Comment by jac-stripe** [comment]
Furthermore, http_proxy does not _seem_ to support unix sockets as proxies (unless I just can't find docs)
We use a proxy running on each laptop that can sign requests to our infrastructure with a TLS certificate; it listens on a Unix socket to prevent any issues with requests from a malicious site in the browser. It would be really nice to be able to use that proxy with kubectl.

**Pull request closed without merging**
