### PR TITLE
WIP: prune genproto / cloud deps

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Bumps to temporary forks of dependencies identified in https://github.com/kubernetes/kubernetes/issues/113366 as depending on oauth2 / cloud.google.com/go/compute/metadata to flush out what changes are needed to update to latest versions of those deps without pulling all cloud modules.

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/kubernetes/issues/113366

#### Special notes for your reviewer:

* This is not expected to merge as-is, but to flush out remaining upstream changes or bumps needed
* Builds on https://github.com/kubernetes/kubernetes/pull/113424
* Includes a license script fix commit from https://github.com/kubernetes/kubernetes/pull/113225

/hold

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/area code-organization
/cc @dims

### CODE REVIEW

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by dims** [comment]
This PR has the label work-in-progress, please revisit to see if you still need this, please close if not

**Comment by liggitt** [comment]
closing for now, a respin would likely need to start from scratch

**Pull request closed without merging**
