### PR TITLE
fix static check failures in component-base/metrics

### PR DESCRIPTION
**Pull request by Zhuzhenghao**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind cleanup

**What this PR does / why we need it**:
```
Errors from staticcheck:

vendor/k8s.io/component-base/metrics
```
**Which issue(s) this PR fixes**:

Ref: #81657

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Review by SataQiu — COMMENTED** [review]
Thanks @Zhuzhenghao 
/lgtm
/approve

**Comment by logicalhan** [comment]
Would you mind fixing the verify test failure?

**Comment by RainbowMango** [comment]
@logicalhan 
I suggest holding this PR for a while if we still working on stability framework.
Because sometimes we may introduce some functions/variables first then migrate, otherwise, we much put them together(in one pr).

**Pull request closed without merging**
