### PR TITLE
AWS: Allow configuration of a single security group for ELBs

### PR DESCRIPTION
**Pull request by nbutton23**
**What this PR does / why we need it**:
AWS has a hard limit on the number of Security Groups (500).  Right now every time an ELB is created Kubernetes is creating a new Security Group.  This allows for specifying a Security Group to use for all ELBS

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
For some reason the Diff tool makes this look like it was way more changes than it really was. 
**Release note**:

```release-note
```

### CODE REVIEW

**Comment by nbutton23** [comment]
@justinsb You asked me to tag you in this PR

**Comment by justinsb** [comment]
@k8s-bot ok to test

/lgtm

**Comment by dlsniper** [comment]
Just a small comment about an inaccuracy from the PR. AWS has a default, soft-limit, of 500 security groups. While I'm sure there's a hard limit somewhere, I couldn't find the docs for it.

Here's the link to the documentation regarding this: http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Appendix_Limits.html#vpc-limits-security-groups

**Comment by nbutton23** [comment]
@dlsniper  Interesting. . . Our AWS concierge told us it was a hard limit for perforce reasons. . .

**Pull request merged**
