### PR TITLE
Cherry pick of #15265 upstream release 1.1

### PR DESCRIPTION
**Pull request by andyzheng0831**
This change also removes an outdated TODO comment.

### CODE REVIEW

**Comment by andyzheng0831** [comment]
cc/ @roberthbailey 
cc/ @dchen1107 
cc/ @yinghan

**Comment by roberthbailey** [comment]
LGTM.

**Comment by andyzheng0831** [comment]
@k8s-bot test this

**Comment by andyzheng0831** [comment]
The original #15265 is merged. Can someone help restart shippable of this PR and do a review?

**Comment by roberthbailey** [comment]
I kicked shippable.

**Comment by dchen1107** [comment]
LGTM

**Comment by roberthbailey** [comment]
Hmmm, auto-merges should be paused because kubernetes-e2e-gce isn't passing according to both http://submit-queue.k8s.io/ and the jenkins dashboard. 

@eparis - Are merges to the release branch exempt?

**Comment by eparis** [comment]
@roberthbailey no, should not be exempt. Likely:
https://github.com/kubernetes/contrib/issues/153
https://github.com/kubernetes/contrib/issues/155

**Pull request merged**
