### PR TITLE
Add mpuckett159 to sig-cli reviewers

### PR DESCRIPTION
**Pull request by eddiezane**
#### What type of PR is this?

/kind cleanup
/sig cli

#### What this PR does / why we need it:

This PR adds @mpuckett159 as a sig-cli reviewer. :tada: 

Thank you, Marly, for your contributions!

#### Special notes for your reviewer:

/assign @soltysh @KnVerey @seans3 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by soltysh** [comment]
/hold
for @dims approval
for sig-cli reviewer

**Comment by KnVerey** [comment]
/approve

Thanks, Marly! 🎉

**Comment by eddiezane** [comment]
Dims has approved. Congrats Marly!

/unhold

**Pull request merged**
