### PR TITLE
Update kube-dns and nodelocaldns to 1.23.1

### PR DESCRIPTION
**Pull request by bzsuni**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Update kube-dns and nodelocaldns to [1.23.1](https://github.com/kubernetes/dns/releases/tag/1.23.1)
The importent changes are:
- Vuln fixes for https://github.com/advisories/GHSA-xw78-pcr6-wrg8 and https://github.com/advisories/GHSA-hq6q-c2x6-hmch by @irLinja in https://github.com/kubernetes/dns/pull/622
- refactor: upgrade base images version for vuln fixes by @irLinja in https://github.com/kubernetes/dns/pull/629
- Update go version to 1.22 by @kl52752 in https://github.com/kubernetes/dns/pull/631

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
This should not have a release note as cluster/ is only used for CI and is officially deprecated / not supported.

https://github.com/kubernetes/kubernetes/tree/master/cluster/README.md

**Comment by bzsuni** [comment]
Thank you. Is this PR no longer needed? @BenTheElder

**Comment by BenTheElder** [comment]
No, we should still test CI with the latest, thanks for the PR

**Comment by bzsuni** [comment]
/assgin @kl52752 
for approval please

**Comment by DamianSawicki** [comment]
I double-checked, and all 4 images are already in `registry.k8s.io`.

/lgtm

**Comment by DamianSawicki** [comment]
I'm confused about the PR description, though.
> #### What this PR does / why we need it:
> Update kube-dns and nodelocaldns to [1.23.1](https://github.com/kubernetes/dns/releases/tag/1.23.1)
> 
> ```
> [root@sun kubernetes]# docker inspect registry.k8s.io/dns/k8s-dns-sidecar-s390x:1.23.1
> [
>     {
>         "Id": "sha256:6a1b15cd9aee25f2742c9e75883564ec9e65e20262ee34350e8ced6958e78a0a",
>         "RepoTags": [
>             "registry.k8s.io/dns/k8s-dns-sidecar-s390x:1.23.1"
>         ],
>         "RepoDigests": [
>             "registry.k8s.io/dns/k8s-dns-sidecar-s390x@sha256:02e23ef290952b46fa0e3cc3381fb588f1eac71453137f8e67664e152d2d82db"
>         ],
> 
> ...
> ```

The PR does not touch `registry.k8s.io/dns/k8s-dns-sidecar-s390x`, it only touches `registry.k8s.io/dns/k8s-dns-sidecar`. Could you please clarify or fix this @bzsuni?

**Comment by bzsuni** [comment]
```
[root@sun kubernetes]# docker image pull registry.k8s.io/dns/k8s-dns-kube-dns:1.23.1
1.23.1: Pulling from dns/k8s-dns-kube-dns
Digest: sha256:9f6f3d013fa9ba050bc6c77821fdb9f816528394f50dca04caf63cd25ccd03ce
Status: Image is up to date for registry.k8s.io/dns/k8s-dns-kube-dns:1.23.1
registry.k8s.io/dns/k8s-dns-kube-dns:1.23.1

[root@sun kubernetes]# docker image pull registry.k8s.io/dns/k8s-dns-dnsmasq-nanny:1.23.1
1.23.1: Pulling from dns/k8s-dns-dnsmasq-nanny
Digest: sha256:455441fcb4c8582b1d74c0aefe09d02e1d3f260ff28d2f09a24bf341b292eaa2
Status: Image is up to date for registry.k8s.io/dns/k8s-dns-dnsmasq-nanny:1.23.1
registry.k8s.io/dns/k8s-dns-dnsmasq-nanny:1.23.1

[root@sun kubernetes]# docker image pull registry.k8s.io/dns/k8s-dns-sidecar:1.23.1
1.23.1: Pulling from dns/k8s-dns-sidecar
Digest: sha256:9be4f0156c3fd35a256beb4261aff91b60b3126f10afeb57d830b99c93f01abf
Status: Image is up to date for registry.k8s.io/dns/k8s-dns-sidecar:1.23.1
registry.k8s.io/dns/k8s-dns-sidecar:1.23.1

[root@sun kubernetes]# docker image pull registry.k8s.io/dns/k8s-dns-node-cache:1.23.1
1.23.1: Pulling from dns/k8s-dns-node-cache
Digest: sha256:e3dccb1a21d16ff614bbf9352144ae72f2d1597da047e15a24cc3a3b21761038
Status: Image is up to date for registry.k8s.io/dns/k8s-dns-node-cache:1.23.1
registry.k8s.io/dns/k8s-dns-node-cache:1.23.1

```

**Comment by bzsuni** [comment]
> The PR does not touch `registry.k8s.io/dns/k8s-dns-sidecar-s390x`, it only touches `registry.k8s.io/dns/k8s-dns-sidecar`. Could you please clarify or fix this @bzsuni?

Thanks a lot, I have updated the decription @DamianSawicki

**Comment by DamianSawicki** [comment]
@kl52752 Could you please /approve in addition to your /lgtm?

**Pull request merged**
