### PR TITLE
Fix quota controller worker deadlock

### PR DESCRIPTION
**Pull request by ironcladlou**
The resource quota controller worker pool can deadlock when:

* Worker goroutines are idle waiting for work from queues
* The Sync() method detects discovery updates to apply

The problem is workers acquire a read lock while idle, making write lock
acquisition dependent upon the presence of work in the queues.

The Sync() method blocks on a pending write lock acquisition and won't unblock
until every existing worker processes one item from their queue and releases
their read lock. While the Sync() method's lock is pending, all new read lock
acquisitions will block; if a worker does process work and release its lock, it
will then become blocked on a read lock acquisition; they become blocked on
Sync(). This can easily deadlock all the workers processing from one queue while
any workers on the other queue remain blocked waiting for work.

Fix the deadlock by refactoring workers to acquire a read lock *after* work is
popped from the queue. This allows writers to get locks while workers are idle,
while preserving the worker pause semantics necessary to allow safe sync.

```release-note
Fixes a possible deadlock preventing quota from being recalculated
```

/cc @kubernetes/sig-api-machinery-bugs

### CODE REVIEW

**Comment by ironcladlou** [comment]
Something @liggitt mentioned which I should add here: this change does introduce the possibility of `Sync` blocking workers which have popped from the queue, but `Sync` is periodic and short lived (and is a single place that could be easily made more strictly timebound). Lock-after-pop is the pattern employed in the garbage collector to avoid this same deadlock (and in fact the sync/worker pause code here seems to be based on the GC code).

Going forward I wonder if a worker pool drain/refill would be an improvement, but that would be a much more invasive change.

**Comment by deads2k** [comment]
@ironcladlou good catch

**Comment by jennybuckley** [comment]
cc @jennybuckley

**Pull request merged**
