### PR TITLE
Update to container-vm-v20150505 (Also updates GCE to Docker 1.6)

### PR DESCRIPTION
**Pull request by zmerlynn**

### CODE REVIEW

**Comment by zmerlynn** [comment]
Ran 38 of 43 Specs in 1317.103 seconds
SUCCESS! -- 38 Passed | 0 Failed | 1 Pending | 4 Skipped I0505 16:54:33.660644   18816 driver.go:96] All tests pass

**Comment by zmerlynn** [comment]
cc @dchen1107

**Comment by dchen1107** [comment]
Lgtm

**Comment by roberthbailey** [comment]
LGTM.

**Pull request merged**
