### PR TITLE
e2e/log-dump: Collect kernel log with journald

### PR DESCRIPTION
**Pull request by euank**
Related to #31928

The kern.log file does not exist on journald distros typically.

cc @vishh @Random-Liu 

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32330)

### CODE REVIEW

**Comment by vishh** [comment]
Thanks for the fix @euank! Much appreciated!!! LGTM

**Comment by euank** [comment]
Well, it didn't break anything for the gce pr e2e, kern.log still shows up there.

I realize now that the GCI image of interest is run against master, not PRs, so I'd have to do some manual validation to make sure it does work on them... I'll give it a whirl..

**Comment by vishh** [comment]
FYI: e2e tests should be running with GCI by default on GCE.

**Comment by euank** [comment]
@vishh I'm pretty sure it's overridden to debian (see https://github.com/kubernetes/test-infra/blob/83df55d58d05c66cb38882d4ae56e10f9f72a76a/jenkins/job-configs/kubernetes-jenkins/kubernetes-e2e-gce.yaml#L66) for the nodes, and masters still default to debian iirc?

**Comment by euank** [comment]
On a default `kube-up`'d cluster, I verified that before this change I saw `scp: /var/log/kern.log: No such file or directory` and didn't see `kern.log` dumped locally.

After this change, I do see `kern.log`.

I'm happy for merging this, my original note no longer applies :+1:

**Comment by eparis** [comment]
1. Please provide a risk assessment in the description
 - Risk surface of accepting this cherrypick: what could go wrong
 - How easy it is to revert if needed
 - Why it is worth the risk, burden to cherrypick and verify the tests stay green, and noise it creates
2. How urgent is this? blocking / important / best effort? We have dozens of cherrypick requests and each one creates a lot of overhead because large batches introduce a high-risk of destabilizing the tests in a way that is hard to track down. We have to break them up into smaller batches and monitor the tests to catch issues early on and track them back to their root cause.

**Comment by vishh** [comment]
@eparis this will help debug test flakes. There is no production code being introduced.

**Pull request merged**
