### PR TITLE
replace HTTP status code with  HTTP status code const

### PR DESCRIPTION
**Pull request by tanshanshan**
**What this PR does / why we need it**:

replace HTTP status code with  HTTP status code const

Thanks!

**Special notes for your reviewer**:

**Release note**:

```release-note
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37349)

### CODE REVIEW

**Comment by mikedanese** [comment]
/lgtm

Thanks!

**Comment by tanshanshan** [comment]
@mikedanese , could you give me a lgtm label?
Thanks.

**Comment by mikedanese** [comment]
Oops.

**Comment by mikedanese** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
