### PR TITLE
Add `-x` Shorthand For `--context` Flag

### LINKED ISSUE #84367: Add `-x` Shorthand For `--context` Flag
**What would you like to be added**:

It would be fantastic if there were a shorthand flag for the `--context` flag. I would suggest `-x`

**Why is this needed**:

When working with multiple contexts it is tedious to type `--context` all the time.

### PR DESCRIPTION
**Pull request by oke-py**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

Add `-x` shorthand for kubectl `--context` flag

**Which issue(s) this PR fixes**:

Fixes #84367

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Add `-x` shorthand for kubectl `--context` flag
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hpandeycodeit — APPROVED** [review]
lgtm

**Comment by pwittrock** [comment]
Not sure we want to do this.  Does it conflict with other short hand flags?  UX changes such as this one are hard to undo and could be solved with an alias

**Comment by oliverisaac** [comment]
How would you propose using `--context` as an alias? Unlike other reasonably-aliased flags `context` requires an argument. I've been using a hacky bash-script-workaround to simulate the -x flag without side-effects.

**Comment by pwittrock** [comment]
```sh
alias kubectl="kubectl --context "
```

**Pull request closed without merging**
