### PR TITLE
cluster/gce: Make functions in configure-vm.sh reusable.

### PR DESCRIPTION
**Pull request by yifan-gu**
This moves the functions in configure-vm.sh into configure-common.sh,
and then in configure-vm.sh, it adds a function to download and source
the configure-common.sh.
This enables other distros to reuse most of the codes.

This would help https://github.com/kubernetes/kubernetes/pull/17243 to remove duplicated codes.

/cc @andyzheng0831 @dchen1107 @davidopp @brendandburns

### CODE REVIEW

**Comment by andyzheng0831** [comment]
Frankly speaking, I think this is unnecessary for 3 reasons:
(1) After the refactoring, the new script is in the same dir as the original script. So, what is the benefit?
(2) Actually, the code still heavily relies on salt. I don't think this will be a suitable way for coreos and trusty. It means that later we will have another round of refactoring to get rid of salt. And meanwhile we will have to keep a version that uses salt.
(3) I am not sure if coreos will use it or not, but my trusty stuff will not, because this version has too much salt stuff that is not used in trusty.

My suggestion: we don't have to make this refactoring. If a distro needs the code, simply sourcing configure-vm.sh would achieve the same purpose

**Comment by yifan-gu** [comment]
@andyzheng0831 
> My suggestion: we don't have to make this refactoring. If a distro needs the code, simply sourcing configure-vm.sh would achieve the same purpose

I want to source the configure-vm.sh like you said, but sourcing it will not only imports the functions, it also executes the script, which I don't know how to deal with except moving the functions into another file. Not shell expert, if you have any suggestions, I am all ears :)

> (3) I am not sure if coreos will use it or not, but my trusty stuff will not, because this version has too much salt stuff that is not used in trusty.

I used the mount-master(https://github.com/kubernetes/kubernetes/pull/17810/files#diff-789ea8198901c1305d63a9d8eed5212dR207) and [create-salt-master-auth](https://github.com/kubernetes/kubernetes/pull/17810/files#diff-789ea8198901c1305d63a9d8eed5212dR352) at least. Besides it's true it uses some salt functions, this is because I don't want to duplicate the salt code, even in https://github.com/kubernetes/kubernetes/pull/17243 there are still two or three places I use the salt (e.g. load the docker images for master components, running the addon updator script, etc.) I totally agree we should move away from salt, but before we have a clear way to replace those logics without salt, keep some of the salt scripts will make it way more easier to get coreos/gce cluster running today, and next, we should definitely spend time thinking how to rewrite them without salt. How do you think about it?

**Comment by yifan-gu** [comment]
Rebased

**Comment by andyzheng0831** [comment]
@yifan-gu, for your question about sourcing a shell script: If you define a function in file xxx.sh, you can source it in yyy.sh to call the function, without executing xxx.sh. I am not sure if you can call it in a systemd service or not. I can do it in an upstart job, just like the current cluster/gce/trusty/node.yaml. When creating node instances, cluster/gce/trusty/configure.sh is uploaded to metadata server and then downloaded to an instance. I even did not chmod the file to be executable, because the upstart jobs just source it (. /etc/configure.sh), and then call functions.

**Comment by yifan-gu** [comment]
@andyzheng0831 Ok, but `cluster/gce/trusty/configure.sh` doesn't contain scripts, it's all functions. `cluster/gce/configure-vm.sh` contains [scripts](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/configure-vm.sh#L644). Sourcing it will execute the scripts. 

For example: https://gist.github.com/yifan-gu/7bc722d37a42ab9ea6d3

BTW I found a workaround here http://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced/14706745#14706745 But seems this requires at least Bash 3.0

**Comment by andyzheng0831** [comment]
I would suggest to put your script under cluster/gce/coreos, instead of changing the existing container-vm stuff. (1) Changing container-vm script will break Google Container Engine. So, please try not to rename/add/remove the container-vm files, unless you know how to fix Google Container Engine; (2) As I mentioned, naming it to something with *common* is misleading, because it is not really common for all distros under cluster/gce/. 

If you really think we should refactor the shell code to put the common functions shared by all three distros in one file under cluster/gce/, we can do it later when both coreos and ubuntu master supports are done. At that moment, we will have better understanding about what functions are *common*. Refactor is always an enhancement and improvement, so not a high-priority job.

**Comment by zmerlynn** [comment]
We may not want this for a separate reason, in that it incurs Yet Another Download. We (GKE) can be pretty sensitive to gets, and this actually flips the startup script around from something we can (and do) completely cache for each release (and then stuff in the instance metadata) to something that might fail.

It also adds minor latency in that path, though I'm sure it's pretty negligible.

**Comment by yifan-gu** [comment]
@zmerlynn @andyzheng0831 Thanks for the feedback, I am closing this for now :)

**Pull request closed without merging**
