### PR TITLE
Automated cherry pick of #54956

### PR DESCRIPTION
**Pull request by vladimirvivien**
Cherry pick of #54956 on release-1.8.

#54956: Remove dependency on drv_cfg binary for querying scalio

```release-note
ScaleIO driver completely removes dependency on drv_cfg binary so a Kubernetes cluster can easily run a containerized kubelet.
```

### CODE REVIEW

**Comment by vladimirvivien** [comment]
@rootfs @msau42 would one of you please add milestone 1.8 tag to this PR.

**Comment by saad-ali** [comment]
This is not strictly a bug fix, but because it is completely isolated to the scale IO volume plugin and does not break backwards compatibility I'm ok with having it cherry picked. It will be up to the release manager to make the ultimate decision.

**Comment by saad-ali** [comment]
Assigning to @jpbetz, 1.8 patch release manager.

**Pull request merged**
