### PR TITLE
use versioned configuration for initresource admission plugin

### LINKED ISSUE #55374: initialresources admission plugin flags pollute all commands
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 kind feature

**What happened**:

The same problem as issue https://github.com/kubernetes/kubernetes/issues/55284

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

use versioned configuration for initresource admission plugin

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #55374

**Special notes for your reviewer**:

**Release note**:

```release-note
use versioned configuration for initresource admission plugin
```

### CODE REVIEW

**Comment by deads2k** [comment]
I like this intent, but I'm not prepared at this moment to try to push it into 1.9.  As I recall, we tried to warn people it would change and this definitely fixes a TODO, but I'd like some more time to consider how to handle the transition and I don't have time to devote to review.

@derekwaynecarr this will be great step forward.  
@piosz I see your fingerprints in here.  The comments warned this was coming.  This will make the configuration consistent.

**Comment by piosz** [comment]
The plugin is deprecated and should be removed. Not sure if it makes sense to work on it.

cc @kubernetes/sig-autoscaling-misc working on VPA

**Comment by wackxu** [comment]
@piosz @deads2k Can I verify the plugin is deprecated ? If so, I can help remove it.

**Comment by deads2k** [comment]
> @piosz @deads2k Can I verify the plugin is deprecated ? If so, I can help remove it.

@derekwaynecarr @liggitt @lavalamp deprecated?

**Comment by piosz** [comment]
@wackxu confirming that it's deprecated.

**Comment by wackxu** [comment]
@piosz Then we can remove it? If so, I can helo do it.

**Pull request closed without merging**
