### PR TITLE
kubelet: minor cleaning up

### PR DESCRIPTION
**Pull request by xiang90**

### CODE REVIEW

**Comment by satnam6502** [comment]
Error strings should not be capitalized. https://github.com/golang/go/wiki/CodeReviewComments#error-strings

**Comment by xiang90** [comment]
> Error strings should not be capitalized. https://github.com/golang/go/wiki/CodeReviewComments#error-strings

When you pass it over: yes. The doc you linked to me tells the reason.
When you print it out, you need to capitalize it.

**Comment by satnam6502** [comment]
OK, indeed, if we only use log messages (as opposed to error messages) in a "line oriented" manner. I wonder if we do embed log messages anywhere.

**Comment by xiang90** [comment]
@satnam6502 I do see we print out uncapitalized error message in some other places (other pkgs in k8s).
But this pull request still does the correct thing.

**Comment by satnam6502** [comment]
Yes, I think we do the wrong thing in lots of places :-)
I often conflate log messages and error messages (bad) and I suspect some of the log messages we have used to be error messages but their capatalization was lost in translation.

**Comment by xiang90** [comment]
@satnam6502 OK. What do you want me to do to get this merged?

**Comment by thockin** [comment]
LGTM

**Comment by satnam6502** [comment]
We usually do not merge in the weekend.  Can you wait until Tuesday AM?

**Pull request merged**
