### PR TITLE
add event broadcaster logging for all contoller managers

### LINKED ISSUE #51400: controller manager should all use EventBroadcaster logging
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

**What happened**:
some controller manager like persistentvolume use EventBroadcaster,  but has no log.

**What you expected to happen**:
I think it will be more direct for us to use logging to debug or trace something

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:
add event broadcaster logging for controller -manager, and it help debug/trace resource status directly.
 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #51400

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
@staebler  event-y stuff

**Comment by derekwaynecarr** [comment]
this makes sense to me.

please rebase, and then we can merge.

**Comment by hzxuzhonghu** [comment]
@derekwaynecarr Thanks, rebased.

**Comment by hzxuzhonghu** [comment]
kindly ping @derekwaynecarr , need your review again.

**Pull request merged**
