### PR TITLE
Remove unnecessary nil check in if statement in nodelease controller

### PR DESCRIPTION
**Pull request by ZP-AlwaysWin**
**What type of PR is this?**
Remove unnecessary judgment
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

```
OwnerReferences []OwnerReferencematches 
so nil len(OwnerReferences) ==0 

change:
 if lease.OwnerReferences == nil || len(lease.OwnerReferences) == 0 ==>if len(lease.OwnerReferences) == 0 
```
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/release-note-none

Small nit: I think "Remove unnecessary nil check in if statement in nodelease controller` could be a slightly more descriptive pr title.

**Comment by ZP-AlwaysWin** [comment]
> /lgtm
> /release-note-none
> 
> Small nit: I think "Remove unnecessary nil check in if statement in nodelease controller` could be a slightly more descriptive pr title.

Thanks，I hava changed pr title.

**Review by feiskyer — APPROVED** [review]
lgtm

**Pull request merged**
