### PR TITLE
delete unused events

### PR DESCRIPTION
**Pull request by mysunshine92**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

 /kind cleanup

**What this PR does / why we need it**:
when use grepping shows me that some events  are unused,so i do the cleanup work for this PR.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/ok-to-test

/lgtm

LGTM, although still want to confirm that we don't need to keep around this events for backwards compatibility.

**Comment by mattjmcnaughton** [comment]
Please run `gofmt` on this code via running `hack/update-gofmt.sh`. That should fix `pull-kubernetes-verify`. Thanks :)

**Comment by mysunshine92** [comment]
> 
> 
> Please run `gofmt` on this code via running `hack/update-gofmt.sh`. That should fix `pull-kubernetes-verify`. Thanks :)

thank you, i have modify it.

**Comment by mattjmcnaughton** [comment]
/lgtm

Modulo I'd like someone to confirm we don't need this events for backwards compat.

**Comment by derekwaynecarr** [comment]
There is no API guarantee or even delivery guarantee for events.  If the events are not used, we are free to remove them.

/approve
/lgtm

**Pull request merged**
