### PR TITLE
Added dashboard banner passthrough to GCE kube-up.

### PR DESCRIPTION
**Pull request by konryd**
**What this PR does / why we need it**: This PR adds GCE-specific provider flag for setting system-banner in the dashboard ui.

```release-note
CUSTOM_KUBE_DASHBOARD_BANNER environment variable will be used to populate notification banner in Kubernetes Dashboard add-on.
```

### CODE REVIEW

**Comment by mwielgus** [comment]
Why do we need this banner?

**Comment by konryd** [comment]
It is used to pass through provider-specific notices.

**Comment by mwielgus** [comment]
Have you tested it manually?

**Comment by konryd** [comment]
Yes:

```
$ KUBE_ENABLE_CLUSTER_UI=true CUSTOM_KUBE_DASHBOARD_BANNER="hello" hack/dev-build-and-up.sh
```

**Comment by konryd** [comment]
Tested manually with and without the dashboard.

**Review by maciaszczykm — APPROVED** [review]
/lgtm

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60639)

**Pull request merged**
