### PR TITLE
test: extend time for a condition to appear in status

### PR DESCRIPTION
**Pull request by 0xmichalis**
Fixes https://github.com/kubernetes/kubernetes/issues/36574

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36644)

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM 👍

**Comment by kargakis** [comment]
@k8s-bot cvm gke e2e test this https://github.com/kubernetes/kubernetes/issues/33388

**Comment by kargakis** [comment]
@k8s-bot cvm gce e2e test this https://github.com/kubernetes/kubernetes/issues/33380

**Comment by kargakis** [comment]
@mfojtik I have slightly updated this test to use WaitForDeploymentStatusValid which also takes available pods into account.

**Comment by kargakis** [comment]
LGTMed by @mfojtik in IRC

**Comment by kargakis** [comment]
@k8s-bot gci gke e2e test this issue: https://github.com/kubernetes/kubernetes/issues/34774

**Comment by kargakis** [comment]
@k8s-bot bazel test this

**Pull request merged**
