### PR TITLE
cleanup: Removes GcrRelease and SampleRegistry from manifest.go

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What this PR does / why we need it:

Those fields are not used for any images, we can remove them.

#### Which issue(s) this PR fixes:

Related: #1458

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
/lgtm

**Review by cndoit18 — APPROVED** [review]

**Comment by claudiubelu** [comment]
Needs milestone.

**Comment by mkumatag** [comment]
@kubernetes/milestone-maintainers can someone add the milestone for this PR?

**Comment by liggitt** [comment]
cleanup like this can wait for the branch to reopen for 1.23

**Pull request merged**
