### PR TITLE
Fix a bug in kubectl exec handling.

### LINKED ISSUE #9113: kubectl exec <pod> needs to remove <pod> from args it sends to container
When running `kubectl exec`, if you don't specify the deprecated `-p <pod>` and instead just do `<pod>`, it doesn't strip off the 1st command line arg, so

```
kubectl exec nginx date
```

sends the command `nginx date` to the container, whereas

```
kubectl exec -p nginx date
```

correctly sends just `date`

Regression from #8604

### PR DESCRIPTION
**Pull request by brendandburns**
Closes #9113

### CODE REVIEW

**Comment by brendandburns** [comment]
@bgrant0607 @ncdc @smarterclayton

**Comment by thockin** [comment]
LGTM

**Comment by bgrant0607** [comment]
LGTM, also.

**Comment by bgrant0607** [comment]
Merging before next e2e starts.

**Pull request merged**
