### PR TITLE
Rename the name of event source in controller-manager

### LINKED ISSUE #51753: Make the resource of event  more obvious
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
kubect create -f statefulset_demo.yaml  to create statefulset, and describe the statefulset, output the event likes
<pre>
Events:
 FirstSeen    LastSeen    Count    From        SubObjectPath    Type        Reason            Message
 ---------    --------    -----    ----        -------------    --------    ------            -------
 1m        1m        1    statefulset            Normal        SuccessfulCreate    create Claim www-web-0 Pod web-0 in StatefulSet web success
 1m        1m        1    statefulset            Normal        SuccessfulCreate    create Pod web-0 in StatefulSet web successful
</pre>

**What you expected to happen**:
the From of event change to 'statefulset-controller' in output, let know the source of event more obvious, likes the event when create job and other resource(replicaset,replication).
<pre>
Events:
 FirstSeen    LastSeen    Count    From        SubObjectPath    Type        Reason            Message
 ---------    --------    -----    ----        -------------    --------    ------            -------
 3m        3m        1    job-controller            Normal        SuccessfulCreate    Created pod: pi-7gd2m
</pre>
**How to reproduce it (as minimally and precisely as possible)**:
create a statefulset and describe it to see the event

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):kubernetes 1.7
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by huzhengchuan**
**What this PR does / why we need it**: Make the event source more obvious 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #51753

**Special notes for your reviewer**:

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
/ok-to-test

I remember there was a guy who had cleaned up such things but maybe he missed some places. Can you please check all the controllers to make sure they all use their names in the event?

**Comment by huzhengchuan** [comment]
Thanks, I check it @xiangpengzhao

**Comment by huzhengchuan** [comment]
@kargakis  @jingxu97  @bowei  
please help review it, thanks.

**Comment by bowei** [comment]
Is there some doc regarding how these things /should/ be named? I'm all for consistency, but it would be good to have some reference for what the desired state is.

**Comment by huzhengchuan** [comment]
thanks for your review. @bowei
I see design-proposals about event, but not found any doc about how to named it.
But we should make the event source more obvious， and keep the same style as other events.

**Comment by huzhengchuan** [comment]
/assign @mikedanese @saad-ali 
help me review it, tks! 
I think the pr is valid. If you have a different view, please tell me．

**Pull request merged**
