### PR TITLE
Sending #35255 again: Remove versioned LabelSelectors

### PR DESCRIPTION
**Pull request by caesarxuchao**
ref #35255: "Remove versioned LabelSelectors"

FYI @smarterclayton 

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35651)

### CODE REVIEW

**Comment by MrHohn** [comment]
The broken Addon Manager image is replaced with a healthy image(gcr.io/google-containers/kube-addon-manager:v5.2).  Built and pushed with commit(2a589b09637aa3745a7151adf2f1fcce36e8b8ac). I will add changelogs to addon manager after.

The differences between v5.2 and v5.1 is that v5.2 use v1.4.4 kubectl instead of 1.3.0-beta2 and adds support for ConfigMap.

cc @mikedanese

**Comment by caesarxuchao** [comment]
Nice. Thanks!

**Comment by caesarxuchao** [comment]
Didn't change any code other than the generated conversion functions. Self apply the lgtm. Also bumped the priority, because I had already rebased 3 times yesterday after got the lgtm.

**Comment by smarterclayton** [comment]
LGTM continues to hold from previous.

**Pull request merged**
