### PR TITLE
Fix: Enqueue daemonset to workqueue when add  controllerRevisoin owner reference is daemonset.

### PR DESCRIPTION
**Pull request by xigang**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

The daemonset key needs to be added to the workqueue to prevent events from being lost when adding ControllerRevision

#### Which issue(s) this PR fixes:

Prevent daemonset events from being lost in the `daemonset controller`.

#### Does this PR introduce a user-facing change?

```
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by xigang** [comment]
cc @janetkuo

**Comment by thockin** [comment]
Shouldn't thins have some documented repro and some tests?  Help us understand when this bug triggers?

**Comment by xigang** [comment]
> Shouldn't thins have some documented repro and some tests? Help us understand when this bug triggers?

@thockin 😄 Thanks for the reply. When I was looking at the Daemonset Controller code logic, when created an owner reference that was a ControllerRevision for Daemonset, I understand that we should put the daemonset key  into the daemonset workqueue. I understand that this logic needs to be added.

ref:https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemon_controller.go#L386
```
// addHistory enqueues the DaemonSet that manages a ControllerRevision when the ControllerRevision is created
// or when the controller manager is restarted.
func (dsc *DaemonSetsController) addHistory(obj interface{}) {
	history := obj.(*apps.ControllerRevision)
	if history.DeletionTimestamp != nil {
		// On a restart of the controller manager, it's possible for an object to
		// show up in a state that is already pending deletion.
		dsc.deleteHistory(history)
		return
	}

	// If it has a ControllerRef, that's all that matters.
	if controllerRef := metav1.GetControllerOf(history); controllerRef != nil {
		ds := dsc.resolveControllerRef(history.Namespace, controllerRef)
		if ds == nil {
			return
		}
		klog.V(4).Infof("ControllerRevision %s added.", history.Name)
                // + Add the daemonset key to the workqueue.
		return
	}

	// Otherwise, it's an orphan. Get a list of all matching DaemonSets and sync
	// them to see if anyone wants to adopt it.
	daemonSets := dsc.getDaemonSetsForHistory(history)
	if len(daemonSets) == 0 {
		return
	}
	klog.V(4).Infof("Orphan ControllerRevision %s added.", history.Name)
	for _, ds := range daemonSets {
		dsc.enqueueDaemonSet(ds)
	}
}
```

**Comment by xigang** [comment]
@janetkuo this pr needs to be confirmed :)

**Review by soltysh — CHANGES_REQUESTED** [review]
/hold
as Tim mentioned earlier we need to have a test case confirming this case, please

**Pull request closed without merging**
