### PR TITLE
Update batch types.go docs

### PR DESCRIPTION
**Pull request by soltysh**
@bgrant0607 you asked about it in https://github.com/kubernetes/kubernetes/pull/42663#discussion_r109065758

### CODE REVIEW

**Comment by soltysh** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by soltysh** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by smarterclayton** [comment]
This needs to be on top of 42663 because of the cron job change.

**Comment by soltysh** [comment]
@smarterclayton #42663 landed, this is rebased and good to go.

**Comment by bgrant0607** [comment]
Thanks @soltysh. Sorry I couldn't get to this sooner.

**Comment by soltysh** [comment]
No worries :)

**Pull request merged**
