### PR TITLE
Endpoint's weight is 0, need to gracefully delete it

### PR DESCRIPTION
**Pull request by yingchunliu-zte**
Signed-off-by: yingchunliu-zte <liu.yingchun@zte.com.cn>

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
When RS was gracefully deleted, after kube-proxy was restarted, RS was not really deleted. When the endpoint becomes ready again, the weight of RS will be kept at 0, which makes the service inaccessible.

When the weight of RS is 0, RS needs to be gracefully deleted

@mrbobbytables @robscott @thockin @M00nF1sh

### CODE REVIEW

**Comment by yingchunliu-zte** [comment]
> @mrbobbytables @robscott @thockin @M00nF1sh

@mrbobbytables @robscott @thockin @M00nF1sh

**Comment by robscott** [comment]
I don't have enough context here, but this seems reasonable.

/ok-to-test
/cc @andrewsykim

**Comment by uablrek** [comment]
There was a PR, https://github.com/kubernetes/kubernetes/pull/111635 in this area not long ago. Is it related in any way?

**Comment by uablrek** [comment]
> When RS was gracefully deleted, after kube-proxy was restarted, RS was not really deleted.

I don't follow. First "gracefully deleted" then "not really deleted"?

Please describe the complete sequence how to recreate, like:
1. Scale-in a Deployment so some PODs are deleted
2. During the grace period, re-start kube-proxy (or what?)
3. ...

Please write an issue first next time, then a PR. The issue template indicates a good description.

**Comment by uablrek** [comment]
@yingchunliu-zte Can you please provide the steps to reproduce the problem as requested above. I will test it and apply this PR and verify that the problem is fixed.

**Comment by yingchunliu-zte** [comment]
> @yingchunliu-zte Can you please provide the steps to reproduce the problem as requested above. I will test it and apply this PR and verify that the problem is fixed.

@uablrek 
GracefulTerminationManager.GracefulDeleteRS(vs *utilipvs.VirtualServer, rs *utilipvs.RealServer) error
        ele := &listItem{
                VirtualServer: vs,
                RealServer:    rs,
        deleted, err := m.deleteRsFunc(ele)  //When rs has links, rs will not be deleted
        if deleted
                return nil
        rs.Weight = 0
        err = m.ipvs.UpdateRealServer(vs, rs) //When the weight of rs is updated to 0, kube-proxy restarts. 
                                                                    //After restarting, the weight of rs will always be 0
        m.rsList.add(ele)
        return nil

**Comment by daman1807** [comment]
@yingchunliu-zte  In case the kube-proxy pod, with an endpoint deferred for graceful termination, restarts the reconciliation loop will add the endpoint back to the graceful termination list at first sync. 


The sync loop [reads all the endpoints programmed in the kernel ](https://github.com/kubernetes/kubernetes/blob/dc08463dff71f95780a217534f5829b72facf7e7/pkg/proxy/ipvs/proxier.go#L1843), add the [unwanted endpoints back to graceful termination](https://github.com/kubernetes/kubernetes/blob/dc08463dff71f95780a217534f5829b72facf7e7/pkg/proxy/ipvs/proxier.go#L1967
) and [updates the endpoint if it becomes healthy](https://github.com/kubernetes/kubernetes/blob/dc08463dff71f95780a217534f5829b72facf7e7/pkg/proxy/ipvs/proxier.go#L1936) which I guess covers the cases you are addressing over here.

Will need more details to reproduce this, closing this for now.
/cc @uablrek 

Feel free to re-open the PR by linking it to an issue that describes the exact problem and steps to reproduce it 🙂

**Comment by danwinship** [comment]
/close
(per previous comment)

@aroradaman FYI the bots only read the first 1024 characters or something like that so if you put bot commands at the end of a long comment they won't see it

**Pull request closed without merging**
