### PR TITLE
A Kubernetes Hello World job

### LINKED ISSUE #28694: Request: A Kubernetes "Hello World" deployment
Similar to what Docker does (https://github.com/docker-library/docs/tree/master/hello-world) we should have a 'hello world' deployment, where, in one line, you can create a deployment (or replica set) that outputs something friendly and exits.

### PR DESCRIPTION
**Pull request by mengqiy**
fixes #28694

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31680)

### CODE REVIEW

**Comment by soltysh** [comment]
See my comment in the original issue, I'm not sure we need this.

**Comment by soltysh** [comment]
Anyway thanks for your contribution! Greatly appreciated :smile:

**Comment by ymqytw** [comment]
I can close this PR, if some one can close issue #28694.

**Comment by soltysh** [comment]
@ymqytw yes please, I've already closed the accompanying issue.

**Pull request closed without merging**
