### PR TITLE
kubelet: Fix racy kubelet tests.

### LINKED ISSUE #7788: TestSyncPodsCreatesNetAndContainerPullsImage has non-deterministic order of docker` calls
https://app.shippable.com/builds/5549046d42da970c000f2958
```
--- FAIL: TestSyncPodsCreatesNetAndContainerPullsImage (0.17s)
	kubelet_test.go:127: expected []string{"list", "list", "list", "list", "inspect_image", "create", "start", "inspect_container", "create", "start", "list", "inspect_container", "inspect_container"}, got []string{"list", "list", "list", "inspect_image", "list", "create", "start", "inspect_container", "create", "start", "list", "inspect_container", "inspect_container"}
```
The `list` and `inspect` are reversed in the actual calls.

### PR DESCRIPTION
**Pull request by yifan-gu**
Add fakePodWorkders to run syncPod() in serial for testing.

Fix #7788 

//cc @yujuhong @vmarmol @dchen1107

### CODE REVIEW

**Comment by yujuhong** [comment]
Thanks @yifan-gu for the PR! Looks good overall.

My only concern is that we would be testing the behaviors of the pod workers in kubelet_tests.go without using the actually pod workers. The fake pod_worker may eventually deviate from the actually implementation as time goes by. Ideally, we would want to move away from examining all docker calls in details in kubelet_test.go, but this may not be done for a while.

Maybe we can add one or two tests for the fake pod worker to verify that it's issuing the same docker calls as the actual pod worker? What do you think about it? We can do this in a followup PR, or if you are busy with other things, feel free to file an issue. I can grab it when I have time :)

**Comment by dchen1107** [comment]
LGTM overall. I am ok to merge the pr with TODOs based on @yujuhong's comments. Thanks!

**Comment by yifan-gu** [comment]
@yujuhong Yes I see your concern. I think we can add tests for the fake one to verify it invokes `syncPodFn' for the same number of times, and with the same args as the real one.
I can do that in this PR.

**Comment by yifan-gu** [comment]
Tests added, PTAL, thanks! @yujuhong @dchen1107

**Comment by yujuhong** [comment]
LGTM. Thanks!

**Comment by yifan-gu** [comment]
Shippable failed, any ideas? I can't access the result :(

**Comment by yujuhong** [comment]
@yifan-gu, did you kick off shippable/travis build or are they just taking forever to finish?

**Comment by yifan-gu** [comment]
@yujuhong NM, I just noticed there is a build failure by my fault, so I fixed it and rebased. Wait for travis now :)

**Comment by yujuhong** [comment]
Flake in one of the shippable build, but the other build passed. Merging.

**Comment by yifan-gu** [comment]
@yujuhong What flakes? It that related?

**Comment by yujuhong** [comment]
Nope. It's the good old pod status not being reported in time bug #6651.

**Pull request merged**
