### PR TITLE
added socialvpn and tinc to possible solutions

### PR DESCRIPTION
**Pull request by milesrichardson**
I encourage you to evaluate SocialVPN and Tinc as possible solutions to the networking layer of Kubernetes. [David Wolinsky](http://www.davidwolinsky.com/) did much of the original research on SocialVPN, and I personally know him as a very smart guy. Tinc is a mature project and supported on many platforms.

### CODE REVIEW

**Comment by thockin** [comment]
I don't have anything against these projects, but this isn't just a place to list favorite network tech.  Has anyone implemented kubernetes on top of these things?  Is there a doc somewhere on how to set them up for Docker?

**Comment by milesrichardson** [comment]
Understandable.

Here are docs for tinc:

http://www.flockport.com/lxc-advanced-networking-guide/ (lxc only)

https://gist.github.com/noteed/11031504 (docker specific)

Socialvpn no good docs, so perhaps delete that from the list. But tinc should probably be on there, it's a very easy solution to implement.

**Comment by thockin-cc** [comment]
If you edit this to just be Tinc (and include a link to that gist), I'm OK
with it.

I'd be happy to see someone set up a kube-cluster with it...

**Comment by thockin** [comment]
This is over a month old.  Please re-open if you want to continue the conversation.

**Pull request closed without merging**
