### PR TITLE
[release-1.30] [go] Bump images, dependencies and versions to go 1.22.2 and distroless iptables

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

- Bump images, dependencies and versions to go 1.22.3 and distroless iptables

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/release/issues/3597

/assign @MadhavJivrajani @liggitt @puerco   @saschagrunert   
cc @kubernetes/release-managers 

#### Does this PR introduce a user-facing change?

```release-note
Kubernetes is now built with go 1.22.3
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by saschagrunert** [comment]
The legacy cloud providers have been removed in https://github.com/kubernetes/kubernetes/pull/124767.

**Comment by cpanato** [comment]
> The legacy cloud providers have been removed in #124767.

we should cherry pick to the release branches, lets confirm that and i will cherry pick

**Comment by liggitt** [comment]
/lgtm
/approve
(for all the actual changes in this PR)

**Comment by cpanato** [comment]
@saschagrunert @liggitt all good, i think we need to wait until the patch releases are out

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
