### PR TITLE
improve the comments

### PR DESCRIPTION
**Pull request by runzhliu**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by SataQiu — COMMENTED** [review]
thanks @runzhliu 
/ok-to-test
/lgtm
/approve

**Comment by SataQiu** [comment]
@runzhliu Please squash the commits.

**Comment by runzhliu** [comment]
@SataQiu sure ;)

**Review by SataQiu — COMMENTED** [review]
/lgtm

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
