### PR TITLE
Remove [k8s.io] tag and redundant [sig-storage] tags from volume tests

### LINKED ISSUE #50178: Some storage tests are duplicated tags
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig storage

**What happened**:
Some storage test names in e2e testgride have redundant tags:
```
[k8s.io] [sig-storage] GCP Volumes [k8s.io] GlusterFS should be mountable
[k8s.io] [sig-storage] GCP Volumes [k8s.io] NFSv3 should be mountable for NFSv3
[k8s.io] [sig-storage] GCP Volumes [k8s.io] NFSv4 should be mountable for NFSv4
[sig-storage] Volume plugin streaming [Slow] [sig-storage] GlusterFS should write files of various sizes, verify size, validate content
[sig-storage] Volume plugin streaming [Slow] [sig-storage] NFS should write files of various sizes, verify size, validate content
```

**What you expected to happen**:
Redundant tags should be removed

### PR DESCRIPTION
**Pull request by msau42**
**What this PR does / why we need it**:
Removes redundant tags from storage e2e test names

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50178

**Release note**:
/release-note-none

### CODE REVIEW

**Comment by m1093782566** [comment]
@msau42 I don't understand what benefit can we bring from doing it? Could you please explain it? Thanks!

**Comment by msau42** [comment]
@m1093782566 I'm cleaning up the names of the tests so that when you look at them in testgrid, they are consistent with all the other tests.  Right now the names look like:
```
[k8s.io] [sig-storage] GCP Volumes [k8s.io] GlusterFS should be mountable
[k8s.io] [sig-storage] GCP Volumes [k8s.io] NFSv3 should be mountable for NFSv3
[k8s.io] [sig-storage] GCP Volumes [k8s.io] NFSv4 should be mountable for NFSv4
[sig-storage] Volume plugin streaming [Slow] [sig-storage] GlusterFS should write files of various sizes, verify size, validate content
[sig-storage] Volume plugin streaming [Slow] [sig-storage] NFS should write files of various sizes, verify size, validate content
```

There's a lot of duplicate tags in these names.  I want to remove them so it looks more like other sig storage tests:
```
[sig-storage] EmptyDir wrapper volumes should not conflict
```

**Pull request merged**
