### PR TITLE
Simple some code for GarbageCollector

### PR DESCRIPTION
**Pull request by mlmhl**
**What this PR does / why we need it**:

Use `beingDeleted` utility function instead of implementing it manually to make the code more simple and clearer.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mlmhl** [comment]
Thanks @hzxuzhonghu 
For approval @caesarxuchao

**Comment by mlmhl** [comment]
ping @caesarxuchao

**Review by awhite2117 — APPROVED** [review]

**Pull request closed without merging**
