### PR TITLE
Remove the status of the terminated containers in the summary endpoint

### PR DESCRIPTION
**Pull request by piosz**
cherry-pick of #48739
related issue #47853 

```release-note
Remove the status of the terminated containers in the Summary API in Kubelet.
```

### CODE REVIEW

**Comment by yujuhong** [comment]
/lgtm

@piosz is this required to fix the bug, or are you going to patch 1.7 with a newer heapster image?

**Comment by piosz** [comment]
The latter one (see #51620). Kubernetes 1.7 works with nodes in 1.5 and 1.6 which doesn't have the fix, though of course we should merge it as well.

**Comment by yguo0905** [comment]
Given that new heapster with the fix https://github.com/kubernetes/heapster/pull/1790 will be released for 1.7, we don't necessarily need this cherry-pick PR? (Just want to make as few changes as possible for the 1.7 branch.)

**Comment by yujuhong** [comment]
> Given that new heapster with the fix kubernetes/heapster#1790 will be released for 1.7, we don't necessarily need this cherry-pick PR? (Just want to make as few changes as possible for the 1.7 branch.)

+1
@piosz, I don't think we need to cherry-pick this PR. WDYT?

**Comment by piosz** [comment]
Agree - there was no fix in Heapster yet while I cherry-picked the PR.

**Pull request closed without merging**
