### PR TITLE
cleanup useless functions in pkg/quota/evaluator/core/services.go

### PR DESCRIPTION
**Pull request by tianshapjq**
**What this PR does / why we need it**:
cleanup useless functions in pkg/quota/evaluator/core/services.go

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
it's definitely un-used.

/assign derekwaynecarr

**Comment by derekwaynecarr** [comment]
thank you for the cleanup.

/approve no-issue
/lgtm

**Pull request merged**
