### PR TITLE
Fix the issue in Windows kube-proxy when processing unqualified name. This is for DNS client such as ping or iwr that validate name in response and original question.

### LINKED ISSUE #42605: DNS resolving does not work on windows nodes
BUG REPORT
## Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

## Environment**:
Azure ACS with windows agents
**What happened**:
unable to connect from one deployed service to other service based on the documented kubernetes dns name of the deployed service

## repro steps:
Created two services using the following commands:
kubectl create deployment iis --image=microsoft/iis
kubectl expose iis --port:80 --type=LoadBalancer
 service is now available on external network
now I want from in this container to connect to a database using the dns name db.default.svc.cluster.local
so created new service:
kubectl create deployment db --image=marcelv/iisexpress
and expose this internal in the cluster
kubectl create service clusterip db --tcp=1433:1433

now I execute a command in the iis container to see if I can connect to the new db service:
kubectl exec <nameofthepod> cmd.exe
inside container I execute:
nslookup
db.default.svc.cluster.local
this results the ip address I also see when I call the kubectl get services command
but when I want to connect to the dns name on port 1433 it wont resolve the ip adres
if you do
ping db.default.svc.cluster.local
Ping request could not find host db.default.cluster.local. Please check the name and try again.

so with a direct dns query it works, but the implicit name resolving on windows does not work.
I tried to resolve it using 
ipconfig /registerdns
no avail
looking at the DNS cash does not show any entries

So it seems DNS is not fully functional inside the cluster.

## What you expected to happen**:
I expect to be able to connect to the network via DNS  from the pod
I also deployed a .net application that tried to resolve the address
but those fal with a wind32 error network path not found

### PR DESCRIPTION
**Pull request by JiangtianLi**
**What this PR does / why we need it**:
This PR is an additional fix to #41618 and [the corresponding commit](https://github.com/kubernetes/kubernetes/commit/b9dfb69dd7679ae31bad1fb4980561fea22f8ed4). The DNS client such as nslookup does not validate name matching in response and original question. That works fine when we append DNS suffix to unqualified name in DNS query in Windows kube-proxy. However, for DNS client such as ping or Invoke-WebRequest that validates name in response and original question, the issue arises and the DNS query fails although the received DNS response has no error. 

This PR fixes the additional issue by restoring the original question name in DNS response. Further, this PR refactors DNS message routines by using miekg's DNS library.

This PR affects the Windows kube-proxy only.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #42605 

**Special notes for your reviewer**:

**Release note**:

```release-note
Fix DNS suffix search list support in Windows kube-proxy.
```

### CODE REVIEW

**Comment by JiangtianLi** [comment]
This PR addresses the comment in #44872 since I closed #44872 due to my bad rebase.

**Comment by JiangtianLi** [comment]
One side note, with rebasing the latest master, building Windows kube-proxy is broken due to #45554.

**Comment by fejta** [comment]
Thanks for the fix! 

Networking team: kubernetes is broken on windows, and our cross-build suite is failing. Will someone from sig-networking review?

@k8s-bot ok to test
@kubernetes/sig-network-pr-reviews 

/assign @bowei @thockin @dcbw 
/unassign @lavalamp

**Review by pires — APPROVED** [review]
LGTM **but** I didn't got a chance to test it manually on a Windows node.

**Comment by JiangtianLi** [comment]
Thanks all for the review. The change has been patched in my private branch for [1.6.0](https://github.com/JiangtianLi/kubernetes/tree/k8swin160) and [1.6.2.](https://github.com/JiangtianLi/kubernetes/tree/k8swin162). Once cross-build issue is fixed, we can verify with the latest build.

**Comment by thockin** [comment]
I have NO IDEA what this code is doing - no other proxy mode has anything DNS related - can you explain what is happening here?  Did you build a DNS server into kube-proxy?

**Comment by thockin** [comment]
I'm going to approve this to unblock, but I'd like to discuss what the heck is going on here.

**Comment by JiangtianLi** [comment]
@thockin Sorry, I should have more context here. This PR is an additional fix to #41618 and the corresponding [commit.](https://github.com/kubernetes/kubernetes/commit/b9dfb69dd7679ae31bad1fb4980561fea22f8ed4). There is no new DNS server built into kube-proxy. 

The issue this PR and #41618 is trying to fix is that DNS suffix search list doesn't work in Windows container (--dns-search option from this [link](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-networking)). Therefore lookup unqualified name such as `kubernetes` or any other unqualified service name doesn't work in Windows container. The users have to specify or change to full qualified name in their apps in Windows container to reach service endpoint. 

To overcome that and until Windows releases container that fix DNS suffix search list issue, we have come up with a solution to fix in Windows kube-proxy. The idea is to have kubeproxy do what DNS client would do to search DNS suffix search list and append it to query, i.e., intercept DNS packet and append a list of common DNS suffix ("cluster.local", "svc.cluster.local", "default.svc.cluster.local", and host DNS suffix) to the name in DNS query. This has worked pretty well for most Windows user scenarios.

Hope that clarifies a bit. Please let me know if you have any question.

**Comment by bowei** [comment]
@JiangtianLi does that code belong in kube-proxy? It seems like something that could be a separate Windows only module that implements the *nix style resolv.conf behavior.

**Comment by JiangtianLi** [comment]
@bowei Thanks for the suggestion. Yes, that code belongs to kube-proxy. The code is in the winuserspace part of the kube-proxy. So it is in Windows kube-proxy and separated from the *nix kube-proxy.

**Comment by thockin** [comment]
Yeah, I find this exceptionally weird, but I am willing to grant latitude since it seems a) temporary and b) contained.  Before long we need to really decide if it is worthwhile for the Window kube-proxy to actually be part of kube-proxy, or a separate thing.

**Comment by thockin** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by JiangtianLi** [comment]
@thockin Agreed that this fix is a workaround to get Windows scenario work. Windows's kube-proxy forked from kube-proxy and implemented a few Windows specific features. sig-windows folks should have more context. Thanks for the approval. I felt this fix should be with its precedent commit in the upstream rather than in my private branch separately.

**Pull request merged**
