### PR TITLE
handle fail path when getting pod count in podtopologyspread

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

#### What type of PR is this?
/kind cleanup
/sig scheduling

#### What this PR does / why we need it:
1. handle fail path when getting pod count in Filter phase
2. solve hard comments in test

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
In general, I don't think we should have code just for tests.

/assing @Huang-Wei 
who initially wrote these tests

**Comment by Huang-Wei** [comment]
The comment is clear to explain why `node-b` and `node-x` got a Success. May I know the motivation of this PR. Is it blocking your ongoing work? If it does, does it work to just bypass checking `node-b` and `node-x`? (remove them in `wantStatusCode`)

> In general, I don't think we should have code just for tests.

+1

**Comment by kerthcet** [comment]
/close 
as we discussed in the pr.

**Pull request closed without merging**
