### PR TITLE
pod constraints func for quota validates resources

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Fixes https://github.com/kubernetes/kubernetes/issues/25484

This prevents quota from prematurely charging for quota usage around a pod when the pod had invalid resources.  For example, if a container limit < container request, prior to this a quota would charge the usage, but the pod failed validation.

We do not do full validation on the pod because at this point, the pod does not have all of ObjectMeta filled out.

/cc @smarterclayton

### CODE REVIEW

**Comment by lavalamp** [comment]
Is this the only way to fix the reported issue? I feel like there's probably N ways to make an invalid pod and by the time you fix them all you'll have reimplemented pod validation. Why not just call the actual pod validation method? (also ugh, but better than code duplication)

**Comment by smarterclayton** [comment]
Without the separation of the admission queues, I don't think we can
assume quota is far enough along the queue to be able to invoke
validation safely.  It probably is... But I'd rather not risk that
without solving the queue problem.

**Comment by derekwaynecarr** [comment]
@lavalamp - the object lacks a UID and may not have Name at this point, so I cannot call the pod validate directly.  agree it's not ideal.

**Comment by derekwaynecarr** [comment]
alternative is that quota could do name and uid assignment, and call validate pod directly.

**Comment by smarterclayton** [comment]
Veto.

On May 12, 2016, at 7:30 PM, Derek Carr <notifications@github.com> wrote:

alternative is that quota could do name and uid assignment, and call
validate pod directly.

—
You are receiving this because you were assigned.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/25487#issuecomment-218914527>

**Comment by smarterclayton** [comment]
Can we call the resource validation directly somehow?

On May 12, 2016, at 7:30 PM, Derek Carr <notifications@github.com> wrote:

alternative is that quota could do name and uid assignment, and call
validate pod directly.

—
You are receiving this because you were assigned.
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/25487#issuecomment-218914527>

**Comment by derekwaynecarr** [comment]
thats what I am doing: 

https://github.com/kubernetes/kubernetes/pull/25487/files#diff-9b60439f29cb51347a55472508f51f60R83

Overall, I am fine keeping this as-is for now.

**Pull request merged**
