### PR TITLE
Use v0.0.0 gitVersion on branches in support of new .gitattributes solution.

### PR DESCRIPTION
**Pull request by david-mcmahon**
Update bad link as well.
Prefer master branch untyped values.

ref #55353.

### CODE REVIEW

**Comment by jsafrane** [comment]
I am not the right person to review this
/unassign
/assign @lavalamp
(decided by [fair dice roll](https://www.google.com/search?q=random+number+between+1+and+5))

**Comment by david-mcmahon** [comment]
@wojtek-t Can you approve/lgtm?

**Comment by david-mcmahon** [comment]
ping.

**Pull request merged**
