### PR TITLE
Update to go 1.12.4

### PR DESCRIPTION
**Pull request by cblecker**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Update to use golang 1.12.4

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Update to use go 1.12.4
```

### CODE REVIEW

**Comment by cblecker** [comment]
/test pull-kubernetes-node-e2e
--

**Comment by javier-b-perez** [comment]
I have created the image staging-k8s.gcr.io/kube-cross:v1.12.4-1
Waiting for image to propagate to k8s.gcr.io/kube-cross:v1.12.4-1, might take a few hours. I will report back

**Comment by javier-b-perez** [comment]
Image should be there now
/test pull-kubernetes-cross

**Comment by cblecker** [comment]
Looks like this are passing. Can I get an LGTM?

**Pull request merged**
