### PR TITLE
Add fluent-plugin-rewrite-tag-filter to fluentd-elasticsearch image

### PR DESCRIPTION
**Pull request by ialidzhikov**
Signed-off-by: ialidzhikov <i.alidjikov@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature

/kind flake

**What this PR does / why we need it**:
[Fluentd rewrite tag filter](https://github.com/fluent/fluent-plugin-rewrite-tag-filter) is widely used in context of kubernetes. Currently fluentd cannot match events by regex expression and very often you need to use mechanism as fluent-plugin-rewrite-tag-filter to modify the tag. I would suggest to include this plugin in the fluentd-elasticsearch image. Otherwise if you want to use this plugin, you would need to build and maintain your own image.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
The helm chart [stable/fluentd](https://github.com/helm/charts/tree/master/stable/fluentd) also refers gcr.io/google-containers/fluentd-elasticsearch image. Users that want to use the rewrite-tag-filter will be able to do it without building and maintaining their own images and charts. @coffeepac , @piosz what do you think about it?

**Comment by monotek** [comment]
If there is already an image available (gcr.io/google-containers/fluentd-elasticsearch)  why should we change this one? 

Just change the image in the yaml or use the helm chart you mentioned if you have a special use case.

**Comment by ialidzhikov** [comment]
> If there is already an image available (gcr.io/google-containers/fluentd-elasticsearch) why should we change this one?
> 
> Just change the image in the yaml or use the helm chart you mentioned if you have a special use case.

I didn't get that. With the PR I think I change exactly gcr.io/google-containers/fluentd-elasticsearch - the image that is referred also from the official helm chart. My proposal just adds a frequently used plugin and this will prevent the users of this image to build and maintain their own images adding this plugin. 
If the proposal above is not okay for you I can close the PR.

**Comment by monotek** [comment]
Sorry. I was in a hurry and misinterpreted what you wrote.

The thing is we don't need this functionality for the purpose of the image, so we would just ship functionality we don't use in fluentd config.

@coffeepac 
thoughts?

**Comment by coffeepac** [comment]
For posterity, I agree with @monotek.  These images are already large for both size and maintenance surface area.  We need to keep it constrained so the ongoing workload remains manageable.

**Pull request closed without merging**
