### PR TITLE
Fixed flakiness of e2e tests for horizontal pod autoscaler.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Enabled e2e tests for horizontal pod autoscaler: added to "Autoscaling Suite".

### CODE REVIEW

**Comment by piosz** [comment]
On hold until the tests that are already enabled become stable.

**Comment by jszczepkowski** [comment]
I've redone this PR. Flakiness of memory tests should be fixed by using larger amount of memory to make it less affected by the image size of consumer's pod.

**Comment by piosz** [comment]
LGTM

**Comment by wojtek-t** [comment]
e2e not required (tests will not be run because of [Skipped] in their name)

**Pull request merged**
