### PR TITLE
prefer double quotes and consistent usage in .proto files.

### PR DESCRIPTION
**Pull request by perezd**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Minor style convention nit.

**Special notes for your reviewer**:

We're applying this patch internally at Google and wanted to ensure it's the same externally.

**Does this PR introduce a user-facing change?**:

NONE

### CODE REVIEW

**Comment by dashpole** [comment]
Should we fix this across the board?

```
$ git grep "syntax = 'proto3';"
pkg/kubelet/apis/podresources/v1alpha1/api.proto:syntax = 'proto3';
pkg/kubelet/pluginmanager/pluginwatcher/example_plugin_apis/v1beta1/api.proto:syntax = 'proto3';
pkg/kubelet/pluginmanager/pluginwatcher/example_plugin_apis/v1beta2/api.proto:syntax = 'proto3';
staging/src/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.proto:syntax = 'proto3';
staging/src/k8s.io/kubelet/pkg/apis/deviceplugin/v1alpha/api.proto:syntax = 'proto3';
staging/src/k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1/api.proto:syntax = 'proto3';
staging/src/k8s.io/kubelet/pkg/apis/pluginregistration/v1/api.proto:syntax = 'proto3';
staging/src/k8s.io/kubelet/pkg/apis/pluginregistration/v1alpha1/api.proto:syntax = 'proto3';
staging/src/k8s.io/kubelet/pkg/apis/pluginregistration/v1beta1/api.proto:syntax = 'proto3';
```

**Comment by dashpole** [comment]
also, if you re-run the generation scripts, does it undo this change?

**Comment by perezd** [comment]
This is the main one that is impacting my work internally, but if you'd like to add the others I'm supportive! Also, not sure what regeneration scripts you are referring to.

**Comment by dashpole** [comment]
Ah, nevermind.  I was referring to hack/update-generated-runtime.sh, but that generates a file _from_ this one, so ignore that comment.

**Comment by dashpole** [comment]
We use double-quotes elsewhere in this file, so I think it makes sense to be consistent.

/approve

**Comment by dashpole** [comment]
I'm going to follow-up updating the rest of the proto files.

**Pull request merged**
