### PR TITLE
Add Rolling update by node

### PR DESCRIPTION
**Pull request by titilambert**
Hello !

This PR implements the first version of the rolling update by node. (see https://github.com/kubernetes/kubernetes/issues/18450). This means you never have two version of RCs running on the same Node.
It uses a node-label to accomplish the task: this means that your RCs (the new one and the old) have to have the same NodeSelector and of course you have to have at least one Node matching this NodeSelector.

Example:

```
kubectl rolling-update-by-node oldRC -f newRCManifestFile.yml  --namespace=MyNamesSpace --node-label=MyNodeLabel
```

Steps of rolling update by node:
- Create the new Replication Controller
- Get/Save number of concerned Pods on each concerned Node
- For each node:
  - Set the corresponding Node label to a maintenance value 
  - Scale down old RC and delete Pods on the current Node
  - Set the corresponding Node label to the value of the label (from the new RC)
  - Waiting for Pod deletion
  - Scale up the new RC (by the number of Pods collecte in step 2)
- Scale up the new RC (if needed)
- Scale down the old RC to 0 (if needed)
- Delete all old Pods (if needed)

Note: _Stop and continue_ and _rollback_ the operation work

Thanks for your feedback

### CODE REVIEW

**Comment by jlowdermilk** [comment]
@k8s-bot ok to test

**Comment by jlowdermilk** [comment]
cc @bgrant0607.

This is a pretty large change and it looks like there's still discussion in the issue about the problem being solved and what the right approach is. I'm going to hold off reviewing until there's clear consensus there.

**Comment by bgrant0607** [comment]
cc @mml @mikedanese @davidopp

**Comment by bgrant0607** [comment]
@titilambert Thanks, but we'll need to look at this after 1.2.

**Comment by bgrant0607** [comment]
@titilambert I'm trying to move away from kubectl-based orchestration (#12143). Let's discuss this in #18450.

**Pull request closed without merging**
