### PR TITLE
fix typo in api-resources help text

### PR DESCRIPTION
**Pull request by jhamfler**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Fixes a small typo for better understanding the api-resources help text in kubectl.

#### Does this PR introduce a user-facing change?

```release-note
Fixed typo for better understanding the api-resources help text in kubectl.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by brianpursley** [comment]
Hi @jhamfler 

Thank you for pointing out the problem in the help text.

Sorry you had an issue with EasyCLA.  I don't know the specific problem, but understand it can be frustrating if it is not working, especially for such a small change.

Since it has been a while, I went ahead and made the change for your fix in another PR https://github.com/kubernetes/kubernetes/pull/117603

**Comment by jhamfler** [comment]
@brianpursley thank you for helping out.

**Pull request closed without merging**
