### PR TITLE
Make label comamnd's response msg more exact.

### LINKED ISSUE #104371: `kubectl label` msg is not distinguished between label and unlabel
#### What happened:
Currently, the `kubectl label` cmd output msg is not distinguished between label and unlabel (using `-` suffix ), both of
them response `labeled`.

#### What you expected to happen:
To distinguish between label and unlabel msg: `labeled/unlabeled`, just like `tainted/untainted`.

### PR DESCRIPTION
**Pull request by agile6v**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Provide more exact response msg for users.

#### Which issue(s) this PR fixes:

Fixes #104371 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by agile6v** [comment]
ping @rikatz

**Comment by pacoxu** [comment]
/triage accepted
#104372 fixed the problem simply
And this approach did some refactors.

**Comment by soltysh** [comment]
/close
in favor of https://github.com/kubernetes/kubernetes/pull/104372 which is simpler and has more extensive tests added

**Pull request closed without merging**
