### PR TITLE
Runasusername windows

### PR DESCRIPTION
**Pull request by jsturtevant**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
/kind feature
> /kind flake

**What this PR does / why we need it**:
This adds windows configuration and wires up username in the podspec to the runtime interface.

#64009 added run_as_username to the container runtime interface, but did not hook it up in the Kubernetes v1.Container.SecurityContext.runAsUser field. 

**Which issue(s) this PR fixes**:

Fixes #
#73387

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Add v1.Container.SecurityContext.Windows.runAsUserName to the pod spec 
```

### CODE REVIEW

**Comment by michmike** [comment]
@liggitt  should take a look at this as well. LGTM
/assign @liggitt

**Comment by jsturtevant** [comment]
There is more discussion happening for this feature at https://github.com/kubernetes/enhancements/pull/799.  The consensus from the sig-windows meeting this morning was to push this feature out to 1.15 and go through the KEP process.  Putting this issue on hold until that is submitted and approved.

/hold

The commits here are a working prototype and I was able to verify using these [yaml files](https://github.com/jsturtevant/windows-k8-playground/tree/master/sample-apps/securitycontext).  A sample yaml file as it is currently prototyped would have a security context that looks like:

```
    spec:
      containers:
      - name: sc-customuser
        image: stefanscherer/whoami:windows-amd64-1.8.2-1809 
        securityContext:
          windowsOptions:
            runAsUserName: ContainerUser
```

You can validate by exec into the container and running:

```
kubectl exec -it sc-customuser-6799b77b6d-sfckq cmd
Microsoft Windows [Version 10.0.17763.253]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>echo %username%
ContainerUser
```

cc: @PatrickLang @michmike

**Comment by liggitt** [comment]
@PatrickLang are this and https://github.com/kubernetes/kubernetes/pull/75459 being combined? wanted to make sure I was looking at the right PRs and that they were ready for review

**Comment by PatrickLang** [comment]
we're combining these at least into 1 KEP. I'm not 100% yet whether it will be 2 PRs or 1.

**Comment by ddebroy** [comment]
Combined KEP for GMSA + RunAsUsername fields: https://github.com/kubernetes/enhancements/pull/972

**Comment by liggitt** [comment]
@ddebroy @PatrickLang 

wanted to check in on this... do we want https://github.com/kubernetes/kubernetes/pull/75459 to land before starting review on this, or is this ready to do in parallel?

**Comment by ddebroy** [comment]
@liggitt @PatrickLang @jsturtevant I think we can get the reviewing for this done in parallel and rebase with https://github.com/kubernetes/kubernetes/pull/75459 if needed. It will be great if @jsturtevant can rebase this on https://github.com/kubernetes/kubernetes/pull/77147 first since that has been merged.

**Comment by liggitt** [comment]
> It will be great if @jsturtevant can rebase this on #77147 first since that has been merged.

agreed. can you do that first?

**Comment by ddebroy** [comment]
A couple of things that needs to be added from a API review perspective:

1. We agreed on minimal [length validation](https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/20190418-windows-security-context.md#validation-of-fields) for the field. Please add the corresponding check (+ unit test) in `validateWindowsSecurityContextOptions` in pkg/apis/core/validation/validation.go

2. I think we need a feature flag associated with [RunAsUsername](https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/20190418-windows-security-context.md#upgrade--downgrade-and-version-skew-strategy)  along with a corresponding entry in `dropDisabledFields` (+ unit tests) to prevent users from setting the field if not explicitly enabled.

**Comment by ddebroy** [comment]
Update on this PR: it will be postponed to v1.16 based on an update from Patrick.

**Comment by PatrickLang** [comment]
This was discussed in an API review with @liggitt , and we have the recommended final name in https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/20190418-windows-security-context.md

Here's an example

```
apiVersion: v1
kind: Pod
metadata:
  name: iis
  labels:
    name: iis
spec:
  securityContext:
    windowsOptions:
      gmsaCredentialSpecName: webapp1-credspec
      runAsUserName: "NT AUTHORITY\\NETWORK SERVICE"
  containers:
    - name: iis
      image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2019
      ports:
        - containerPort: 80
    - name: logger
      image: eventlogger:2019
      ports:
        - containerPort: 80
  nodeSelector:
    beta.kubernetes.io/os : windows
```

**Pull request closed without merging**
