### PR TITLE
Automated cherry pick of #90296: go-to-protobuf: fix rewrite of embedded struct fields

### PR DESCRIPTION
**Pull request by mandelsoft**
Cherry pick of #90296 on release-1.18.

#90296: go-to-protobuf: fix rewrite of embedded struct fields

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

Release notes:
```release-note
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
Hm, do we really need to backport this? It doesn't actually change any Kubernetes behavior? Can you not just use the libraries at head?

**Comment by mandelsoft** [comment]
@lavalamp unfortunately this did not work. If I change the dependency to the generator project to the latest version is also generates incompatible REST API stubs for using the rest client. The usage of the context parameter seems to have changed.

**Comment by lavalamp** [comment]
ACK, ok, that seems like a good reason.

/ok-to-test
/approve
/lgtm

**Comment by lavalamp** [comment]
Wait, I just realized there's a binary in this PR? Do we really check that binary in?

**Comment by mandelsoft** [comment]
The binary has been removed, sorry for that.

**Comment by feiskyer** [comment]
/kind bug
/priority important-soon
from parent PR

**Pull request merged**
