### PR TITLE
Fix README registry error on juju worker

### LINKED ISSUE #384: registry-auth secret set improperly
After deploying the bundle for OLS, they ran into problems pulling images from their private registry.  After some investigation we found that the secret set in registry-auth, when base64 decoded, was one character off from the secret in the file used to run the deploy, saved in our secrets store and handed over to OLS.  At some point during the registry creation process the secret must have been mangled/truncated.

### PR DESCRIPTION
**Pull request by ktsakalozos**
**What this PR does / why we need it**: Update instructions on Juju Kubernetes Worker.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/384

**Special notes for your reviewer**:

**Release note**:

```NONE
```

### CODE REVIEW

**Comment by mbruzek** [comment]
Yeah this looks like a documentation only change. It looks like it fixes issue #384 of another repository, and I am not quite sure the kube-bot knows about other repos.

/lgtm
/approve no-issue

**Comment by ktsakalozos** [comment]
thanks @mbruzek

**Pull request merged**
