### PR TITLE
Fix traffic distribution comment to reflect graduated status in v1.31

### PR DESCRIPTION
**Pull request by robert-cronin**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This fix will reduce confusion for users by making it clear in the reference docs that the new `trafficDistribution` feature is now graduated to beta in v1.31. 

#### Which issue(s) this PR fixes:

Partial fix for https://github.com/kubernetes/website/issues/47776

#### Special notes for your reviewer:

As I understand it, we will still need to cherry pick the first commit for v1.31 and regenerate the reference documentation in [k/website](https://github.com/kubernetes/website). This is the first fix of this kind for me so any guidance would be appreciated, thank you!

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [Enhancement Tracking Issue]: https://github.com/kubernetes/enhancements/issues/4444
```

### CODE REVIEW

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Comment by robscott** [comment]
Thanks!

FYI @gauravkghildiyal 
/lgtm

**Comment by gauravkghildiyal** [comment]
Thanks @robert-cronin 

/lgtm

**Pull request merged**
