### PR TITLE
Fix v0.0.0 in kubectl built from master

### PR DESCRIPTION
**Pull request by liggitt**
Fixes https://github.com/kubernetes/kubernetes/issues/40813

### CODE REVIEW

**Comment by caesarxuchao** [comment]
It doesn't work for me. I played with other vendored package, it looks like ldflags doesn't work for code in vendor/ in general.

**Comment by caesarxuchao** [comment]
Eh, the trick is to `make clean` first.

**Comment by ymqytw** [comment]
@liggitt Why this small fix is not for 1.6 but the issue #40813 is for 1.6?

**Comment by caesarxuchao** [comment]
I think it's 1.6. Updated the label.

Thanks @ymqytw for noticing this.

**Comment by caesarxuchao** [comment]
@zmerlynn could you approve the change? Thanks.

**Comment by liggitt** [comment]
> @liggitt Why this small fix is not for 1.6 but the issue #40813 is for 1.6?

I wouldn't consider it release-blocking, since the official release doesn't have this problem, but it wouldn't bother me if it went in.

**Pull request merged**
