### PR TITLE
fix golint for /pkg/kubelet/preemption and some golint failures for /pkg/kubelet/sysctl

### PR DESCRIPTION
**Pull request by mysunshine92**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
 
/kind cleanup

**What this PR does / why we need it**:
fix golint for /pkg/kubelet/preemption
Fix some golint failures of /pkg/kubelet/sysctl

**Which issue(s) this PR fixes**:

Fixes #
refer #68026
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/ok-to-test

thanks for your work here :) assuming tests pass, looks good to me :)

**Comment by mattjmcnaughton** [comment]
@mysunshine92 it looks like golint is failing for `/pkg/kubelet/sysctl`. Mind fixing and also mind updating the title of your pr to include `/pkg/kubelet/sysctl`? Thanks!

**Comment by mysunshine92** [comment]
> 
> 
> @mysunshine92 it looks like golint is failing for `/pkg/kubelet/sysctl`. Mind fixing and also mind updating the title of your pr to include `/pkg/kubelet/sysctl`? Thanks!

thanks,i have modified those.

**Comment by mysunshine92** [comment]
cc @mattjmcnaughton 
please add an /lgtm label, thanks.

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

thanks for your work here :)

**Pull request closed without merging**
