### PR TITLE
modify error output in cniNetworkPlugin

### PR DESCRIPTION
**Pull request by mars1024**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

When cni validation fails, it will print error message like 
```
Sep 22 22:29:16 kubelet[5427]: W0922 22:29:16.598269    5427 cni.go:202] Error validating CNI config &{cbr0  false [0x8d20e40 0x8d20e80] [123 10 32 32 34 110 97 109 101 34 58 32 34 99 98 114 48 34 44 10 32 32 34 112 108 117 103 105 110 115 34 58 32 91 10 32 32 32 32 123 10 32 32 32 32 32 32 34 116 121 112 101 34 58 32 34 102 108 97 110 110 101 108 34 44 10 32 32 32 32 32 32 34 100 101 108 101 103 97 116 101 34 58 32 123 10 32 32 32 32 32 32 32 32 34 104 97 105 114 112 105 110 77 111 100 101 34 58 32 116 114 117 101 44 10 32 32 32 32 32 32 32 32 34 105 115 68 101 102 97 117 108 116 71 97 116 101 119 97 121 34 58 32 116 114 117 101 10 32 32 32 32 32 32 125 10 32 32 32 32 125 44 10 32 32 32 32 123 10 32 32 32 32 32 32 34 116 121 112 101 34 58 32 34 112 111 114 116 109 97 112 34 44 10 32 32 32 32 32 32 34 99 97 112 97 98 105 108 105 116 105 101 115 34 58 32 123 10 32 32 32 32 32 32 32 32 34 112 111 114 116 77 97 112 112 105 110 103 115 34 58 32 116 114 117 101 10 32 32 32 32 32 32 125 10 32 32 32 32 125 10 32 32 93 10 125 10]}: [plugin flannel does not support config version ""]
```
We can not get some valid information from it, this is because pointers and byte slice defined in `NetworkConfigList`,
```
type NetworkConfigList struct {
	Name         string
	CNIVersion   string
	DisableCheck bool
	Plugins      []*NetworkConfig
	Bytes        []byte
}
```
So we need to modify error output to what we expect, the raw string of config file.

```release-note
None
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
Can you post what the new error message will look like?

/lgtm

**Comment by mars1024** [comment]
> Can you post what the new error message will look like?
> 
> /lgtm

Of course, it will look like 
```
Sep 22 22:29:16 kubelet[5427]: W0922 22:29:16.598269    5427 cni.go:202] Error validating CNI config list {
  "name": "cbr0",
  "plugins": [
    {
      "type": "flannel",
      "delegate": {
        "hairpinMode": true,
        "isDefaultGateway": true
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }
    }
  ]
}
: [plugin flannel does not support config version ""]
```

**Comment by mattjmcnaughton** [comment]
On Mon, Oct 14, 2019 at 09:07:34PM -0700, Bruce Ma wrote:
> > Can you post what the new error message will look like?
> > 
> > /lgtm
> 
> Of course, it will look like 
> ```
> Sep 22 22:29:16 kubelet[5427]: W0922 22:29:16.598269    5427 cni.go:202] Error validating CNI config list {
>   "name": "cbr0",
>   "plugins": [
>     {
>       "type": "flannel",
>       "delegate": {
>         "hairpinMode": true,
>         "isDefaultGateway": true
>       }
>     },
>     {
>       "type": "portmap",
>       "capabilities": {
>         "portMappings": true
>       }
>     }
>   ]
> }
> : [plugin flannel does not support config version ""]
> ```
> 
> -- 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/83896#issuecomment-542026892

Cool! +1 that is more helpful.

**Comment by mars1024** [comment]
@dcbw  Could you help to take a look at this PR? Thanks ~

**Comment by mars1024** [comment]
@dcbw @thockin Could you help to promote this PR? Thanks for your time !

**Review by thockin — COMMENTED** [review]
What we should do is print up to a fixed max-size, like 4KB or somethign.  For well-formed files that will capture the whole thing.  For bugs or other cases it protects us.

e.g. `string(confList.Bytes)[:4096]`

**Comment by mars1024** [comment]
> What we should do is print up to a fixed max-size, like 4KB or somethign. For well-formed files that will capture the whole thing. For bugs or other cases it protects us.
> 
> e.g. `string(confList.Bytes)[:4096]`

@thockin Thanks, updated, PTAL ~

**Comment by mars1024** [comment]
@mattjmcnaughton Hi, the LGTM has been removed by a force-push, PTAL again, thanks!

**Review by mattjmcnaughton — COMMENTED** [review]
Will let @thockin do the final sign-off :)

**Comment by mars1024** [comment]
> Will let @thockin do the final sign-off :)

Yes, of course ...

**Comment by mars1024** [comment]
@thockin @dcbw Hi, do you have time to take a look at this? I think 1.17 code freeze is coming soon... Thanks!

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
