### PR TITLE
[e2e] Refactor: cleanup Logf from framework/util

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Refactor: cleanup `Logf` from `framework/util.go`.
`Logf` has been defined in `framework/log/logger.go`.

**Which issue(s) this PR fixes**:

Ref #77095

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by draveness** [comment]
PTAL at the issue https://github.com/kubernetes/kubernetes/issues/77359

The files in `test/e2e/framework` have already fixed in another PR https://github.com/kubernetes/kubernetes/pull/78084.

**Comment by SataQiu** [comment]
Sorry for missing that @draveness 
I'll be careful.
But it seems that this PR has fixed more files.
I searched all the files and made the cleanup changes.
This does not conflict with PR #78084.

**Review by neolit123 — COMMENTED** [review]
thanks!

/lgtm
/approve
/priority backlog

**Comment by thockin** [comment]
Thanks!

/approve

**Pull request merged**
