### PR TITLE
WIP Move SelectorSpreading priority to MapReduce-like framework

### PR DESCRIPTION
**Pull request by gmarek**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35630)

### CODE REVIEW

**Comment by dims** [comment]
@gmarek Do we need this for 1.5? (I see a 1.5 milestone)

**Comment by wojtek-t** [comment]
No - we can merge it after 1.5. Removing milestone.

**Comment by timothysc** [comment]
@gmarek you don't intend to get this into 1.6 do you?

**Comment by gmarek** [comment]
@timothysc - nope. We don't need to get it in, and in the current implementation of framework this seems to be slower than 'normal' version. Once the scheduler will be our bottleneck again we may revisit this PR (which is why I keep it open).

**Pull request closed without merging**
