### PR TITLE
delete job when namespace is deleted

### PR DESCRIPTION
**Pull request by mikedanese**

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
LGTM - thanks for finding this gap!

**Comment by soltysh** [comment]
LGTM, but your missing test case.

**Comment by derekwaynecarr** [comment]
This will fail a test case I believe.  We had a test case that ensured the right stuff is called when experimental flag is true.

**Comment by derekwaynecarr** [comment]
See: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/namespace/namespace_controller_test.go#L115

**Comment by derekwaynecarr** [comment]
Shippable errors are related to test-cmd.sh and not this PR.

LGTM

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Pull request merged**
