### PR TITLE
update examples/logging-demo to use kube-system namespace, add instruction on how to enable elasticsearch on GCE

### PR DESCRIPTION
**Pull request by caesarxuchao**
#10168

@satnam6502  @JanetKuo @krousey @nikhiljindal @bgrant0607

### CODE REVIEW

**Comment by satnam6502** [comment]
No, the logging demo should not use the kube-system namespace.

**Comment by caesarxuchao** [comment]
@satnam6502, what's your suggestion? Currently this example is not working.

**Comment by satnam6502** [comment]
Why is it not working? I just run it right now?

**Comment by satnam6502** [comment]
```
$ kubectl get pods
NAME                           READY     STATUS    RESTARTS   AGE
synthetic-logger-0.25lps-pod   1/1       Running   0          11m
synthetic-logger-10lps-pod     1/1       Running   0          11m
satnam@satnam-linux:~/gocode/src/github.com/GoogleCloudPlatform/kubernetes/examples/logging-demo$ kubectl logs synthetic-logger-0.25lps-pod
synthetic-logger-0.25lps-pod: 0: 2015-07-07 23:56:13.860440250+00:00
synthetic-logger-0.25lps-pod: 1: 2015-07-07 23:56:17.862951356+00:00
synthetic-logger-0.25lps-pod: 2: 2015-07-07 23:56:21.865430602+00:00
synthetic-logger-0.25lps-pod: 3: 2015-07-07 23:56:25.867834140+00:00
synthetic-logger-0.25lps-pod: 4: 2015-07-07 23:56:29.870172036+00:00
synthetic-logger-0.25lps-pod: 5: 2015-07-07 23:56:33.873023478+00:00
```

**Comment by satnam6502** [comment]
Most of the README.md should be deleted and the information about accessing logs via Cloud Logging at https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/logging.md or Elasticsearch at https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/logging-elasticsearch.md be linked to instead

**Comment by caesarxuchao** [comment]
Yes, the synthetic load generator works. But 1. elasticsearch is not enabled by default in GCE now 2. add-ons are moved to a kube-system namespace, so the many Makefile command will not have any output or report error.

**Comment by caesarxuchao** [comment]
@satnam6502 will improve the instructions in this example in another PR. Close this PR.

**Pull request closed without merging**
