### PR TITLE
Automated cherry pick of #67691: Bump versions of components with latest security patches.

### PR DESCRIPTION
**Pull request by loburm**
Cherry pick of #67691 on release-1.9.

#67691: Bump versions of components with latest security patches.

### CODE REVIEW

**Comment by cjcullen** [comment]
It looks like this 1.9 cherrypick pulled in scaler-deployment.yaml. Was that intentional?

**Comment by loburm** [comment]
@cjcullen thanks for catching this. I removed a file.

**Comment by nikhita** [comment]
/sig cluster-lifecycle
/kind bug

/assign @mikedanese 
for approval

**Pull request merged**
