### PR TITLE
Automated cherry pick of #119776: Fix a job quota related deadlock

### PR DESCRIPTION
**Pull request by ASverdlov**
Cherry pick of #119776 on release-1.27.

#119776: Fix a job quota related deadlock

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by pacoxu** [comment]
```
pkg/controller/cronjob/cronjob_controllerv2.go:1: : # k8s.io/kubernetes/pkg/controller/cronjob [k8s.io/kubernetes/pkg/controller/cronjob.test]
pkg/controller/cronjob/cronjob_controllerv2_test.go:1719:49: undefined: fmt (typecheck)
```
/lgtm cancel
Please see the CI failure.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by soltysh** [comment]
ping @kubernetes/release-managers for cherry-pick approval

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
