### PR TITLE
Add plugins

### PR DESCRIPTION
**Pull request by kahootali**
Signed-off-by: kahootali <kahoot.ali@gmail.com>

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
/kind flake

**What this PR does / why we need it**:
This PR adds some plugins to fluentd's image, these plugins are common and many people need these plugins when using fluentd

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Comment by kahootali** [comment]
i signed it

**Comment by coffeepac** [comment]
@kahootali I'm not sure these are appropriate for this image.  We try to only include plugins that are used by the fluentd config in this repo.

**Comment by kahootali** [comment]
@coffeepac okay, I will create my own image based on this. Thanks, I am closing this PR.

**Pull request closed without merging**
