### PR TITLE
update go.mod files to go 1.18

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Switches go.mod files to use go1.18

This changes how the vendor dir prunes go.mod files and how `go mod tidy` normalizes transitive dependencies in go.mod files.

This messes up our `go mod graph`-based dependency counts for indirect dependencies (xref https://github.com/kubernetes/kubernetes/issues/104461), but overall dependency counts should still be accurate.

We may want to do this anyway, despite the `go mod graph` issues, to start to take advantage of dependency pruning go added in go1.17

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
as expected, this confuses our dependency stats view of direct dependencies, but other metrics are unaffected:

```diff
{
-	"directDependencies": 163,
+	"directDependencies": 230,
 	"transitiveDependencies": 262,
 	"totalDependencies": 323,
 	"maxDepthOfDependencies": 29
```

**Comment by thockin** [comment]
This seems like the right thing to do.

**Comment by liggitt** [comment]
rebased

**Comment by dims** [comment]
/approve
/lgtm

Let's do this!!!

**Pull request merged**
