### PR TITLE
fix: remove deprecated RegisterPriorityFunction

### LINKED ISSUE #80224: Cleanup RegisterPriorityFunction in the scheduler
/kind cleanup
/sig scheduling
/assign
/priority important-longterm

The `RegisterPriorityFunction` has deprecated which needs to be removed from the codebase.

+ [ ] Remove RegisterPriorityFunciton

### PR DESCRIPTION
**Pull request by draveness**
/kind cleanup
/sig scheduling
/priority important-longterm

**What this PR does / why we need it**:

+ Convert InterPodPredicates to map reduce pattern.
+ Remove deprecated RegisterPriorityFunciton

**Which issue(s) this PR fixes**:

Fixes #80224

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by draveness** [comment]
/retest

Regards,
Draven

**Comment by Huang-Wei** [comment]
I will take a look at this.

**Review by Huang-Wei — COMMENTED** [review]
@draveness Thanks for the PR. But the logic may be more complex than it looks like.

The key challenge is: in the `map-reduce` pattern today, `map` function is applied for **every node which passed all Predicates**. However, for some Priority like InterPodAffinity, it also needs to process the pods from the nodes which failed the predicates. That answers why in current logic:

https://github.com/kubernetes/kubernetes/blob/e0ff9634d5b5a480595930236c87dec1327dbf13/pkg/scheduler/algorithm/priorities/interpod_affinity.go#L116

There are actually two "node list", one is _"all node list"_ (from nodeNameToInfo) and the other is _"node list which pass the predicates"_.

So if we want to apply `map-reduce` pattern to InterPodAffinity, we need to pass in "all node list" to `map` function; `reduce` function should remain unchanged.

**Comment by draveness** [comment]
> There are actually two "node list", one is _"all node list"_ (from nodeNameToInfo) and the other is _"node list which pass the predicates"_.

I noticed the `InterPodAffinity` holds a nodeLister, so I get all the nodes with `nodeLister.Nodes()`. But I'm not sure whether the nodes I got from the lister are consistent with `nodeNameToInfo`, does that make sense to you?

> So if we want to apply `map-reduce` pattern to InterPodAffinity, we need to pass in "all node list" to `map` function; `reduce` function should remain unchanged.

If we have to pass in "all node list" to `map` function, we should also update the `Score` interface in scheduling framework which will replace the `map` function in the future IMO.

cc/ @bsalamat

**Comment by ahg-g** [comment]
I suggest we move directly to the framework rather than moving to Map/Reduce. Map/Reduce itself should be deprecated in favor of Score/NormalizeScore etc..

/cc @Huang-Wei @bsalamat

**Comment by Huang-Wei** [comment]
@ahg-g I agree. It makes more sense to adapt this change into new framework.

**Comment by draveness** [comment]
> @ahg-g I agree. It makes more sense to adapt this change into new framework.
> I suggest we move directly to the framework rather than moving to Map/Reduce. Map/Reduce itself should be deprecated in favor of Score/NormalizeScore etc..

I created an issue https://github.com/kubernetes/kubernetes/issues/80667 to track this and will start to work on it after the NormalizeScore extension point merged into the master branch.

**Pull request closed without merging**
