### PR TITLE
Update elasticsearch plugin to 4.0.5.

### PR DESCRIPTION
**Pull request by alex0ptr**
/kind bug

**What this PR does / why we need it**:
This PR updates the elasticserach plugin in fluentd-es-image to 4.0.5.

**Which issue(s) this PR fixes**:

The changelog for the plugin is here: https://github.com/uken/fluent-plugin-elasticsearch/blob/master/History.md

### CODE REVIEW

**Comment by coffeepac** [comment]
@alex0ptr thanks for the PR!  A few notes:
- one, apologies for the slow response and thank you for your patience
- two, why do you want to upgrade this plugin?  Normally I would just test it and go but I'm operating under diminished personal resources until COVID-19 clears out, which may be a bit
- three, this is a change for the image, but not a large one, please update the patch version for this image in both the makefile and the daemonset config

**Comment by ehashman** [comment]
I echo @coffeepac's comments -- without more context, I'm not sure what this PR is intended to fix. The template isn't fully completed, this isn't addressing an issue, there is possibly more follow-up work to do, etc.

@alex0ptr if you could please provide a little more detail that would be great, otherwise I am going to close this PR!

**Pull request closed without merging**
