### PR TITLE
Demand that builds run in a GOPATH

### PR DESCRIPTION
**Pull request by thockin**
I am not sure we should do this, but I split it out from #28903 for discussion.

### CODE REVIEW

**Comment by dims** [comment]
Are we saying we will rip out the other PR (https://github.com/kubernetes/kubernetes/pull/28903) and use this instead? (In the future)?

**Comment by thockin** [comment]
No, this would be additive, which is why I don't see much value in this PR.  I just want others to agree :)

**Comment by thockin** [comment]
i.e. I hope to get shot down :)

**Comment by dims** [comment]
I don't think we should "demand" in 1.4 :) +1 to deal with the other request about how to make us go gettable instead of this.

**Comment by thockin** [comment]
I'm going to close this one.

**Pull request closed without merging**
