### PR TITLE
update security contacts for apimachinery repos

### LINKED ISSUE #92084: Security contacts for apiextensions-apiserver not specified or out of date
The purpose of the `SECURITY_CONTACTS` file for each Kubernetes repository is to provide a list of people who can assist the Kubernetes [Product Security Committe](https://github.com/kubernetes/community/tree/master/committee-product-security) in the event that a security issue related to the repository is discovered or disclosed.  As described in the file, those on the list should agree to our [Embargo Policy](https://git.k8s.io/security/private-distributors-list.md#embargo-policy).

Please update the [`/staging/src/k8s.io/apiextensions-apiserver/SECURITY_CONTACTS`](/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/SECURITY_CONTACTS) file for the apiextensions-apiserver repository. After finding people who are willing to work in this capacity, you should add them to the list, then remove PSC members (except any PSC member will be working as a security contact for this repository). The list is GitHub usernames, optionally followed by an email address. If no email address is listed, the PSC will use the email address found on git commits made by the listed user.

The file may already have people listed who are secuirty contacts. In that case, simply remove any PSC members who aren't also security contacts for the repo.

See https://github.com/kubernetes/security/issues/92 for more information

/area security
/committee product-security
/kind cleanup
/lifecycle frozen
/priority important-soon
/sig api-machinery

### LINKED ISSUE #92085: Security contacts for apimachinery not specified or out of date
The purpose of the `SECURITY_CONTACTS` file for each Kubernetes repository is to provide a list of people who can assist the Kubernetes [Product Security Committe](https://github.com/kubernetes/community/tree/master/committee-product-security) in the event that a security issue related to the repository is discovered or disclosed.  As described in the file, those on the list should agree to our [Embargo Policy](https://git.k8s.io/security/private-distributors-list.md#embargo-policy).

Please update the [`/staging/src/k8s.io/apimachinery/SECURITY_CONTACTS`](/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/SECURITY_CONTACTS) file for the apimachinery repository. After finding people who are willing to work in this capacity, you should add them to the list, then remove PSC members (except any PSC member will be working as a security contact for this repository). The list is GitHub usernames, optionally followed by an email address. If no email address is listed, the PSC will use the email address found on git commits made by the listed user.

The file may already have people listed who are secuirty contacts. In that case, simply remove any PSC members who aren't also security contacts for the repo.

See https://github.com/kubernetes/security/issues/92 for more information

/area security
/committee product-security
/kind cleanup
/lifecycle frozen
/priority important-soon
/sig api-machinery

### LINKED ISSUE #92087: Security contacts for apiserver not specified or out of date
The purpose of the `SECURITY_CONTACTS` file for each Kubernetes repository is to provide a list of people who can assist the Kubernetes [Product Security Committe](https://github.com/kubernetes/community/tree/master/committee-product-security) in the event that a security issue related to the repository is discovered or disclosed.  As described in the file, those on the list should agree to our [Embargo Policy](https://git.k8s.io/security/private-distributors-list.md#embargo-policy).

Please update the [`/staging/src/k8s.io/apiserver/SECURITY_CONTACTS`](/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/SECURITY_CONTACTS) file for the apiserver repository. After finding people who are willing to work in this capacity, you should add them to the list, then remove PSC members (except any PSC member will be working as a security contact for this repository). The list is GitHub usernames, optionally followed by an email address. If no email address is listed, the PSC will use the email address found on git commits made by the listed user.

The file may already have people listed who are secuirty contacts. In that case, simply remove any PSC members who aren't also security contacts for the repo.

See https://github.com/kubernetes/security/issues/92 for more information

/area apiserver
/area security
/committee product-security
/kind cleanup
/lifecycle frozen
/priority important-soon
/sig api-machinery

### LINKED ISSUE #92088: Security contacts for client-go not specified or out of date
The purpose of the `SECURITY_CONTACTS` file for each Kubernetes repository is to provide a list of people who can assist the Kubernetes [Product Security Committe](https://github.com/kubernetes/community/tree/master/committee-product-security) in the event that a security issue related to the repository is discovered or disclosed.  As described in the file, those on the list should agree to our [Embargo Policy](https://git.k8s.io/security/private-distributors-list.md#embargo-policy).

Please update the [`/staging/src/k8s.io/client-go/SECURITY_CONTACTS`](/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/SECURITY_CONTACTS) file for the client-go repository. After finding people who are willing to work in this capacity, you should add them to the list, then remove PSC members (except any PSC member will be working as a security contact for this repository). The list is GitHub usernames, optionally followed by an email address. If no email address is listed, the PSC will use the email address found on git commits made by the listed user.

The file may already have people listed who are secuirty contacts. In that case, simply remove any PSC members who aren't also security contacts for the repo.

See https://github.com/kubernetes/security/issues/92 for more information

/area security
/committee product-security
/kind cleanup
/lifecycle frozen
/priority important-soon
/sig api-machinery

### LINKED ISSUE #92091: Security contacts for code-generator not specified or out of date
The purpose of the `SECURITY_CONTACTS` file for each Kubernetes repository is to provide a list of people who can assist the Kubernetes [Product Security Committe](https://github.com/kubernetes/community/tree/master/committee-product-security) in the event that a security issue related to the repository is discovered or disclosed.  As described in the file, those on the list should agree to our [Embargo Policy](https://git.k8s.io/security/private-distributors-list.md#embargo-policy).

Please update the [`/staging/src/k8s.io/code-generator/SECURITY_CONTACTS`](/kubernetes/kubernetes/blob/master/staging/src/k8s.io/code-generator/SECURITY_CONTACTS) file for the code-generator repository. After finding people who are willing to work in this capacity, you should add them to the list, then remove PSC members (except any PSC member will be working as a security contact for this repository). The list is GitHub usernames, optionally followed by an email address. If no email address is listed, the PSC will use the email address found on git commits made by the listed user.

The file may already have people listed who are secuirty contacts. In that case, simply remove any PSC members who aren't also security contacts for the repo.

See https://github.com/kubernetes/security/issues/92 for more information

/area code-generation
/area security
/committee product-security
/kind cleanup
/lifecycle frozen
/priority important-soon
/sig api-machinery

### LINKED ISSUE #92095: Security contacts for kube-aggregator not specified or out of date
The purpose of the `SECURITY_CONTACTS` file for each Kubernetes repository is to provide a list of people who can assist the Kubernetes [Product Security Committe](https://github.com/kubernetes/community/tree/master/committee-product-security) in the event that a security issue related to the repository is discovered or disclosed.  As described in the file, those on the list should agree to our [Embargo Policy](https://git.k8s.io/security/private-distributors-list.md#embargo-policy).

Please update the [`/staging/src/k8s.io/kube-aggregator/SECURITY_CONTACTS`](/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-aggregator/SECURITY_CONTACTS) file for the kube-aggregator repository. After finding people who are willing to work in this capacity, you should add them to the list, then remove PSC members (except any PSC member will be working as a security contact for this repository). The list is GitHub usernames, optionally followed by an email address. If no email address is listed, the PSC will use the email address found on git commits made by the listed user.

The file may already have people listed who are secuirty contacts. In that case, simply remove any PSC members who aren't also security contacts for the repo.

See https://github.com/kubernetes/security/issues/92 for more information

/area security
/committee product-security
/kind cleanup
/lifecycle frozen
/priority important-soon
/sig api-machinery

### LINKED ISSUE #92103: Security contacts for sample-apiserver not specified or out of date
The purpose of the `SECURITY_CONTACTS` file for each Kubernetes repository is to provide a list of people who can assist the Kubernetes [Product Security Committe](https://github.com/kubernetes/community/tree/master/committee-product-security) in the event that a security issue related to the repository is discovered or disclosed.  As described in the file, those on the list should agree to our [Embargo Policy](https://git.k8s.io/security/private-distributors-list.md#embargo-policy).

Please update the [`/staging/src/k8s.io/sample-apiserver/SECURITY_CONTACTS`](/kubernetes/kubernetes/blob/master/staging/src/k8s.io/sample-apiserver/SECURITY_CONTACTS) file for the sample-apiserver repository. After finding people who are willing to work in this capacity, you should add them to the list, then remove PSC members (except any PSC member will be working as a security contact for this repository). The list is GitHub usernames, optionally followed by an email address. If no email address is listed, the PSC will use the email address found on git commits made by the listed user.

The file may already have people listed who are secuirty contacts. In that case, simply remove any PSC members who aren't also security contacts for the repo.

See https://github.com/kubernetes/security/issues/92 for more information

/area security
/committee product-security
/kind cleanup
/lifecycle frozen
/priority important-soon
/sig api-machinery

### LINKED ISSUE #92105: Security contacts for sample-controller not specified or out of date
The purpose of the `SECURITY_CONTACTS` file for each Kubernetes repository is to provide a list of people who can assist the Kubernetes [Product Security Committe](https://github.com/kubernetes/community/tree/master/committee-product-security) in the event that a security issue related to the repository is discovered or disclosed.  As described in the file, those on the list should agree to our [Embargo Policy](https://git.k8s.io/security/private-distributors-list.md#embargo-policy).

Please update the [`/staging/src/k8s.io/sample-controller/SECURITY_CONTACTS`](/kubernetes/kubernetes/blob/master/staging/src/k8s.io/sample-controller/SECURITY_CONTACTS) file for the sample-controller repository. After finding people who are willing to work in this capacity, you should add them to the list, then remove PSC members (except any PSC member will be working as a security contact for this repository). The list is GitHub usernames, optionally followed by an email address. If no email address is listed, the PSC will use the email address found on git commits made by the listed user.

The file may already have people listed who are secuirty contacts. In that case, simply remove any PSC members who aren't also security contacts for the repo.

See https://github.com/kubernetes/security/issues/92 for more information

/area security
/committee product-security
/kind cleanup
/lifecycle frozen
/priority important-soon
/sig api-machinery

### PR DESCRIPTION
**Pull request by deads2k**
fixes https://github.com/kubernetes/kubernetes/issues/92084
fixes https://github.com/kubernetes/kubernetes/issues/92085
fixes https://github.com/kubernetes/kubernetes/issues/92087
fixes https://github.com/kubernetes/kubernetes/issues/92088
fixes https://github.com/kubernetes/kubernetes/issues/92091
fixes https://github.com/kubernetes/kubernetes/issues/92095
fixes https://github.com/kubernetes/kubernetes/issues/92103
fixes https://github.com/kubernetes/kubernetes/issues/92105

@lavalamp let's tweak from here.  I knew Chao for client-go, but I wasn't sure how you wanted to apportion the rest or if these contacts were good enough since we will know the names of individuals we need.

/kind bug
/priority important-soon
@kubernetes/sig-api-machinery-api-reviews 
/assign @lavalamp 

```release-note
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
/lgtm
/approve

thanks :)

**Comment by fedebongio** [comment]
Thank you for taking care of this one David!

**Comment by joelsmith** [comment]
Thanks @deads2k !

**Pull request merged**
