### PR TITLE
Automated cherry pick of #11254 upstream release 1.0

### PR DESCRIPTION
**Pull request by thockin**
Assuming #11254 will not need further changes

### CODE REVIEW

**Comment by bgrant0607** [comment]
The doc is going to move, so the doc link in the message will need to be updated.
cc @davidopp

**Comment by davidopp** [comment]
LGTM

doc/services-firewalls.md is the one remaining doc that I felt should move out of docs/ but couldn't figure out which subdir to put it in. So anyway, it's still at top-level, so this PR doesn't need to be rebased or anything.

**Comment by davidopp** [comment]
@zmerlynn

**Comment by zmerlynn** [comment]
LGTM. Checked the patches hadn't drifted before taking off the WIP.

**Pull request merged**
