### PR TITLE
E2E test for kubectl replace

### LINKED ISSUE #10764: All kubectl commands should be covered by e2e tests
`hack/test-cmd.sh` is good, but insufficient, as some of the commands exercise provider-specific logic. We need e2e coverage for every kubectl command that talks to the server, at least for defaults.

- [x] [kubectl api-versions](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_api-versions.md)	 - Print available API versions.
- [x] [kubectl cluster-info](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_cluster-info.md)	 - Display cluster info
- [x] ~~[kubectl config](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_config.md)	 - config modifies kubeconfig files~~ N/A this doesn't make server calls, no e2e needed
- [x] [kubectl create](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_create.md)	 - Create a resource by filename or stdin
- [x] [kubectl delete](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_delete.md)	 - Delete a resource by filename, stdin, resource and name, or by resources and label selector.
- [x] [kubectl describe](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_describe.md)	 - Show details of a specific resource
- [x] [kubectl exec](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_exec.md)	 - Execute a command in a container.  (tested by `test/e2e/kubectl.go`)
- [x] [kubectl expose](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_expose.md)	 - Take a replicated application and expose it as Kubernetes Service
- [x] [kubectl get](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_get.md)	 - Display one or many resources  (tested by `test/e2e/kubectl.go`)
- [x] [kubectl label](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_label.md)	 - Update the labels on a resource
- [x] [kubectl logs](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_logs.md)	 - Print the logs for a container in a pod.  (tested by `test/e2e/examples.go`, but test is disabled)
- [x] ~~[kubectl namespace](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_namespace.md)	 - SUPERCEDED: Set and view the current Kubernetes namespace~~ N/A, deprecated command
- [x] [kubectl patch](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_patch.md)	 - Update field(s) of a resource by stdin.
- [x] [kubectl port-forward](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_port-forward.md)	 - Forward one or more local ports to a pod.  (tested by `test/e2e/kubectl.go`)
- [x] [kubectl proxy](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_proxy.md)	 - Run a proxy to the Kubernetes API server
- [ ] [kubectl replace](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_replace.md)	 - Replace a resource by filename or stdin.
- [x] [kubectl rolling-update](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_rolling-update.md)	 - Perform a rolling update of the given ReplicationController.  (tested by `test/e2e/kubectl.go`)
- [x] [kubectl run](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_run.md)	 - Run a particular image on the cluster.
- [x] [kubectl scale](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_scale.md)	 - Set a new size for a Replication Controller. (tested by `test/e2e/kubectl.go`)
- [x] [kubectl stop](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_stop.md)	 - Gracefully shut down a resource by name or filename.  (tested by `test/e2e/kubectl.go`)
- [x] [kubectl version](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_version.md)	 - Print the client and server version information.

Working on adding missing tests now.

### PR DESCRIPTION
**Pull request by dims**
Fixes #10764

### CODE REVIEW

**Comment by fejta** [comment]
@dims please let me know when this passes tests

**Comment by dims** [comment]
@fejta yes of course will do.

**Comment by dims** [comment]
@fejta the e2e test i added seems to work

**Comment by fejta** [comment]
LGTM, thanks so much!

**Pull request merged**
