### PR TITLE
Updated default k8s release to 1.1.8 in cluster/ubuntu/download-relea…

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
…se.sh

Resolves issue #22139

### CODE REVIEW

**Comment by eparis** [comment]
ok to test

**Comment by MikeSpreitzer** [comment]
@k8s-bot test this #20778

**Comment by MikeSpreitzer** [comment]
@k8s-bot test this issue: #20778

**Comment by MikeSpreitzer** [comment]
Why did the k8s-merge-robot remove the lgtm label an hour ago?

**Comment by eparis** [comment]
because you didn't include an issue/flake in your retest request.  re-adding.

**Comment by eparis** [comment]
@k8s-bot test this issue: #20778

**Pull request merged**
