### PR TITLE
kubeadm: fix unnecessary namespace field for clusterrole

### PR DESCRIPTION
**Pull request by my-git9**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

The Namespace is unnecessary fileld for clusterrole and clusterrolerolebinding resources.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
are these the only places where this happens?

**Comment by my-git9** [comment]
> are these the only places where this happens?

I haven't found it anywhere else yet

**Comment by neolit123** [comment]
/retitle kubeadm: fix unnecessary namespace field for clusterrole

**Pull request merged**
