### PR TITLE
Break deployment controller into separate self-contained files

### PR DESCRIPTION
**Pull request by 0xmichalis**
Fixes https://github.com/kubernetes/kubernetes/issues/25867
- rolling.go (has all the logic for rolling deployments)
- recreate.go (has all the logic for recreate deployments)
- sync.go (has all the logic for getting and scaling replica sets)
- rollback.go (has all the logic for rolling back a deployment)
- util.go (contains all the utilities used throughout the controller)

Leave back at deployment_controller.go all the necessary bits for
creating, setting up, and running the controller loop.

Also add package documentation.

@kubernetes/deployment @mfojtik this is an honest refactoring of the controller. In the long term, I believe it will help a lot with maintainance.

### CODE REVIEW

**Comment by pwittrock** [comment]
@kargakis Will this create merge conflicts with the perma-fail PR or other PRs you have open?  If so, what is the best order to review in?

**Comment by kargakis** [comment]
Let's get this in, and I will rework perm-failed and the one that checks
for synced old sets during Recrete.

**Comment by kargakis** [comment]
@pwittrock ping

**Comment by mfojtik** [comment]
@kargakis this refactoring makes things pretty clean, LGTM.

**Comment by pwittrock** [comment]
@kargakis I am OOO through July 14.  I will try to take a look at this, but will have limited availability.

**Comment by pwittrock** [comment]
@janetkuo Can you take a first pass at this?

**Comment by pwittrock** [comment]
@janetkuo Never mind I think I got this covered.

**Comment by kargakis** [comment]
Updated the license headers to make ./hack/verify-boilerplate.sh happy - reapplying lgtm

**Pull request merged**
