### PR TITLE
Deflake TestPrepareRun

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

the max-in-flight filter takes a few milliseconds to initialize and raced the /healthz get, producing this flake:

```
=== RUN   TestPrepareRun
W0306 19:41:03.993313   72776 authorization.go:47] Authorization is disabled
W0306 19:41:03.994050   72776 authentication.go:40] Authentication is disabled
    genericapiserver_test.go:336: [+]ping ok
        [+]log ok
        [-]poststarthook/max-in-flight-filter failed: reason withheld
        healthz check failed
        
    genericapiserver_test.go:337: 
        	Error Trace:	genericapiserver_test.go:337
        	Error:      	Not equal: 
        	            	expected: 200
        	            	actual  : 500
        	Test:       	TestPrepareRun
```

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=pull-kubernetes-unit&test=PrepareRun

/kind flake

```release-note
NONE
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm
/approve

Thanks for debugging!

**Comment by liggitt** [comment]
Triage board shows no occurrences since this merged, what time period is the top flakes list computed over?

**Comment by spiffxp** [comment]
1 week

File an issue on us to update the 1 day query to look the same

**Comment by spiffxp** [comment]
I opened https://github.com/kubernetes/test-infra/issues/21296

**Pull request merged**
