### PR TITLE
Track opened connections with a single tracker per authenticator

### LINKED ISSUE #91913: kubectl output flooded with warnings about aws-iam-authenticator
**What happened**:
`kubectl -A describe pods`

Results in a flood of messages like:
`W0608 10:47:22.221620   25245 exec.go:203] constructing many client instances from the same exec auth config can cause performance problems during cert rotation and can exhaust available network connections; 3825 clients constructed calling "aws-iam-authenticator"`

**What you expected to happen**:

No warnings.

**How to reproduce it (as minimally and precisely as possible)**:
In an EKS environment where aws-iam-authenticator is used to get tokens:
```
users:
- name: myuser
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - dev
      command: aws-iam-authenticator
      env:
      - name: AWS_PROFILE
        value: dev
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:34:25Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: EKS
- OS (e.g: `cat /etc/os-release`): macos
- Kernel (e.g. `uname -a`): Darwin Kernel Version 19.5.0

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Consolidates connection tracking when creating exec auth clients to use a single tracker per authenticator.

This side-steps the following issues to unblock exec auth:
* clientset.New creating egregiously many new restclients for a clientset (~40+)
* `kubectl describe` creating a new clientset per object
* `kubectl get` creating a new clientset per object (for some output types)

**Which issue(s) this PR fixes**:
Fixes #91913

**Does this PR introduce a user-facing change?**:
```release-note
Using exec auth plugins with kubectl no longer results in warnings about constructing many client instances from the same exec auth config.
```

/cc @enj @ankeesler 
@kubernetes/sig-auth-pr-reviews

### CODE REVIEW

**Review by ankeesler — COMMENTED** [review]
lol, i tried something remarkably similar yesterday, so that is a good sign.

one thing i still can't convince myself of: will sibling clients that use the same exec authenticator potentially interrupt each other's connections?
- scenario: 2 `rest.RESTClient`'s, using the same `exec.Authenticator`
- `rest.RESTClient` *A* wants to make HTTP call, so it creates TCP connection to API, gets certs from `tls.Config.GetCert`, creates TLS session, starts long REST operation (i.e., `watch`?)
- `rest.RESTClient` *B* wants to make HTTP call, so it creates TCP connection to API, gets certs from `tls.Config.GetCert`, `exec.Authenticator` sees that cert has expired, so it goes to refresh the cert and therefore calls `CloseAll()` on all the TCP connections, and thus `rest.RESTClient` *A*'s long REST operation is interrupted because the TCP connection is closed

**Comment by liggitt** [comment]
> will sibling clients that use the same exec authenticator potentially interrupt each other's connections?

Yes, as they did before this PR

**Comment by ankeesler** [comment]
> Yes, as they did before this PR

ah, yes. dang should have caught that! alrighty, this seems like a net improvement then.

**Comment by liggitt** [comment]
kind flakes were both https://github.com/kubernetes/kubernetes/issues/96803

/retest

**Comment by ipleten** [comment]
Is there any chances it can be backported to v1.19?

**Pull request merged**
