### PR TITLE
Promote SidecarContainers feature to beta

### PR DESCRIPTION
**Pull request by gjkim42**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This promotes the SidecarContainers feature to beta.
https://github.com/kubernetes/kubernetes/pull/120620: The main change is that sidecar termination is serialized.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
The SidecarContainers feature has graduated to beta and is enabled by default.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/753-sidecar-containers
```

### CODE REVIEW

**Review by tzneal — APPROVED** [review]
/lgtm

Holding pending outcome of SIG Node discussion today.

/hold

**Comment by tzneal** [comment]
/unhold

No objections from SIG Node

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

as discussed at SIG Node meeting today we changed scope of KEP a bit and this is good to go now

**Pull request merged**
