### PR TITLE
update gopass to fix format error

### PR DESCRIPTION
**Pull request by xilabao**
```
#kubectl get no
Please enter Username: admin
Please enter Password: ********
                               NAME        STATUS    AGE       VERSION
127.0.0.1   Ready     28s       v1.7.0-alpha.2.357+904b02075623d7-dirty
```
`godep update github.com/howeyc/gopass/` can fix it.

### CODE REVIEW

**Comment by xilabao** [comment]
@ncdc @jbeda

**Comment by spiffxp** [comment]
@k8s-bot ok to test

**Comment by xilabao** [comment]
@k8s-bot bazel test this
@k8s-bot verify test this

**Comment by xilabao** [comment]
@ncdc @jbeda kindly ping

**Comment by xilabao** [comment]
@jbeda need your approval.  thanks！

**Comment by xilabao** [comment]
can someone approve this? thanks.
@jbeda @smarterclayton @brendandburns @lavalamp @thockin @bgrant0607 @wojtek-t

**Comment by ncdc** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this #20051

**Pull request merged**
