### PR TITLE
Make Google Cloud Logging the default for GCE

### PR DESCRIPTION
**Pull request by satnam6502**
Addresses #9757

### CODE REVIEW

**Comment by saad-ali** [comment]
That was easy :) 
And just to be safe, please deploy and verify that it works as intended
Otherwise LGTM

**Comment by satnam6502** [comment]
As shown in #9760 this change was used to make working cluster running Flunetd -> GCP on each node. I ran a counter pod and observed the ingested logs in the console. Ready to merge.

**Comment by fabioy** [comment]
@k8s-bot ok to test

Just a quick, sanity build.

**Comment by saad-ali** [comment]
@k8s-bot test this please

**Comment by saad-ali** [comment]
@satnam6502 I assume `gcp` enables logs to GCL, right? How do I view the logs in GCL?

**Comment by satnam6502** [comment]
http://blog.kubernetes.io/2015/06/cluster-level-logging-with-kubernetes.html

**Comment by satnam6502** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/logging.md

**Comment by saad-ali** [comment]
Great, thanks @satnam6502

**Pull request merged**
