### PR TITLE
Prevents automatic restart of static Pods

### PR DESCRIPTION
**Pull request by saikey0379**
What type of PR is this?
/kind bug

What this PR does / why we need it:
When the Kubelet version is updated, the static POD is prevented from automatically restarting due to the POD structure update
Therefore, change the UID value method to MD5 based on the file content to avoid unexpected restart during the upgrade due to different structure

### CODE REVIEW

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by dims** [comment]
If you still need this PR then please remove the merge commits (see bot comment above), if not, please close the PR

**Comment by saikey0379** [comment]
> If you still need this PR then please remove the merge commits (see bot comment above), if not, please close the PR

Yes，I still need this PR ，Thanks

**Comment by bart0sh** [comment]
/remove-lifecycle rotten

@saikey0379
> Yes，I still need this PR ，Thanks

Please work on removing `do-not-merge/contains-merge-commits` and `do-not-merge/release-note-label-needed` labels from this PR.

Covering your code with unit tests would also help to proceed further with this PR.

**Comment by bart0sh** [comment]
@saikey0379 please [sign the CLA](https://www.kubernetes.dev/docs/guide/#sign-the-cla) to proceed further with this PR.

**Pull request closed without merging**
