### PR TITLE
Update aws-sdk-go to 1.0.7

### PR DESCRIPTION
**Pull request by therc**
I'm also adding the ECR package and a couple of new dependencies.

### CODE REVIEW

**Comment by therc** [comment]
See #17733 for recent fireworks. It's working for me, but I might have not sacrificed enough goats to the bot gods.

**Comment by therc** [comment]
The failure is probably because I am not using the new dependencies yet. Do I really have to split the Godeps changes in two?

**Comment by therc** [comment]
I took out service/ecr and its two new dependencies.

**Comment by davidopp** [comment]
Test is failing with below. Did you do the necessary godep magic?

```
Your godeps changes are not reproducable
diff -Naupr '--exclude=symlink' /home/travis/gopath/src/github.com/kubernetes/kubernetes/Godeps/_workspace/src/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/build.go /tmp/gopath.bqDIFC/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/build.go
--- /home/travis/gopath/src/github.com/kubernetes/kubernetes/Godeps/_workspace/src/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/build.go	2016-01-07 22:09:39.000000000 +0000
+++ /tmp/gopath.bqDIFC/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/aws/aws-sdk-go/private/protocol/json/jsonutil/build.go	1970-01-01 00:00:00.000000000 +0000
@@ -1,243 +0,0 @@
-// Package jsonutil provides JSON serialisation of AWS requests and responses.
-package jsonutil
-
-import (
-	"bytes"
-	"encoding/base64"
-	"fmt"
-	"reflect"
-	"sort"
-	"strconv"
-	"time"
-)
```
[...]

**Comment by therc** [comment]
godep is like black magic.  I am still not sure how I got it to work initially, because I kept hitting https://github.com/tools/godep/issues/320. I removed the actual Go files that used to be refences, then ran a random permutation of godep commands from my history and hack/verify-godeps.sh is happy now.

**Comment by davidopp** [comment]
@k8s-bot test this please

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
