### PR TITLE
Enable v1beta3 API via --runtime_config=api/v1beta3 flag

### PR DESCRIPTION
**Pull request by smarterclayton**
This exposes the proper v1beta3 API endpoint when the user specifies the --runtime_config=api/v1beta3 argument to the apiserver. v1beta3 is still considered experimental and subject to change.

--runtime_config is a map of string keys and values, that can be specified by providing

```
--runtime_config=a=b,b=c,d,e
```

Only the key must be specified, the value can be omitted.

Enables v1beta3 in hack/local-up-cluster.sh and hack/test-cmd.sh

@bgrant0607

Will allow completion of remaining #1519 items

### CODE REVIEW

**Comment by smarterclayton** [comment]
This is ready for final review - all blockers should be resolved.  Only change from earlier is that we now omit namespace from the path if `Request.Namespace()` is not invoked.

**Comment by bgrant0607** [comment]
Cool. LGTM.

I still see 4 commits. Are any of these covered by other PRs?

**Comment by smarterclayton** [comment]
Nope, this is totally isolated now.

**Comment by smarterclayton** [comment]
Announced https://groups.google.com/d/topic/kubernetes-dev/ZqbLnrg5--8/discussion

----- Original Message -----

**Pull request merged**
