### PR TITLE
Nutanix volume plugin for Kubernetes.

### PR DESCRIPTION
**Pull request by subodh01**
Nutanix volume plugin for Kubernetes. This diff does not contain generated code. There will be a separate commit for that.

**What this PR does / why we need it**:
This PR implements volume plugin to use Nutanix cluster for persistent volume.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
This PR implements a new feature.

**Special notes for your reviewer**:
I am planning to submit 3 separate PRs for this feature. Besides this PR, there will be a PR for generated code and another one for Unit test and a document with example.

**Release note**:

```
Nutanix volume plugin for Kubernetes. This adds support for both static and dynamic provisioning of persistent volume on Nutanix cluster.
```

### CODE REVIEW

**Comment by subodh01** [comment]
Submitted CNCF CLA, please check again

**Comment by subodh01** [comment]
Related PR for generated code: https://github.com/kubernetes/kubernetes/pull/48479

**Comment by mml** [comment]
@kubernetes/sig-storage-pr-reviews

**Comment by subodh01** [comment]
Implementing out of tree volume plugin using flexvolume

**Pull request closed without merging**
