### PR TITLE
Use const componentKubelet and NamespaceSystem

### PR DESCRIPTION
**Pull request by yiqinguo**
In this case,if change modify the kube-system or kubelet string,only need modify the variables or constants.

### CODE REVIEW

**Comment by dims** [comment]
Can you please add more details on why this change is needed etc?

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by dashpole** [comment]
thanks for the cleanup work!  This will have to wait until after the code freeze to merge.
/release-note-none
/lgtm

**Comment by yiqinguo** [comment]
@k8s-bot pull-kubernetes-verify test this

**Comment by NickrenREN** [comment]
Code you modified needs to be gofmt-ed.

> I0613 04:27:18.435]  		// No cloud provider yet, so can't get the nodename via Cloud.Instances().CurrentNodeName(hostname), try just using the hostname
I0613 04:27:18.436] -		configmap, err := kubeClient.CoreV1Client.ConfigMaps(api.NamespaceSystem).Get(fmt.Sprintf("%s-%s",componentKubelet, hostname), metav1.GetOptions{})
I0613 04:27:18.436] +		configmap, err := kubeClient.CoreV1Client.ConfigMaps(api.NamespaceSystem).Get(fmt.Sprintf("%s-%s", componentKubelet, hostname), metav1.GetOptions{})
I0613 04:27:18.436]  		if err != nil {
I0613 04:27:18.436]  			return nil, fmt.Errorf("cloud provider was nil, and attempt to use hostname to find config resulted in: %v", err)
I0613 04:27:18.436]  		}
I0613 04:27:18.443] FAILED   hack/make-rules/../../hack/verify-gofmt.sh	13s

**Comment by NickrenREN** [comment]
`I0613 04:27:18.435]  		// No cloud provider yet, so can't get the nodename via Cloud.Instances().CurrentNodeName(hostname), try just using the hostname
I0613 04:27:18.436] -		configmap, err := kubeClient.CoreV1Client.ConfigMaps(api.NamespaceSystem).Get(fmt.Sprintf("%s-%s",componentKubelet, hostname), metav1.GetOptions{})
I0613 04:27:18.436] +		configmap, err := kubeClient.CoreV1Client.ConfigMaps(api.NamespaceSystem).Get(fmt.Sprintf("%s-%s", componentKubelet, hostname), metav1.GetOptions{})
I0613 04:27:18.436]  		if err != nil {
I0613 04:27:18.436]  			return nil, fmt.Errorf("cloud provider was nil, and attempt to use hostname to find config resulted in: %v", err)
I0613 04:27:18.436]  		}
I0613 04:27:18.443] FAILED   hack/make-rules/../../hack/verify-gofmt.sh	13s`

**Pull request closed without merging**
