### PR TITLE
modify the initialization statement

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Review by luxas — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
