### PR TITLE
Update gophercloud vendor dependency to v0.1.0

### PR DESCRIPTION
**Pull request by toliu**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

Related: #79234

**What this PR does / why we need it**:

this PR just Update `github.com/gophercloud/gophercloud` to v0.1.0 according to [specification requirements](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/vendor.md#justifications-for-an-update), 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
after [comparison](https://github.com/gophercloud/gophercloud/compare/c818fa66e4c8...v0.1.0), I found that after upgrading to v0.1.0, the following changes may affect us. but upgrading from v0.1.0 to v0.2.0 doesn't seem to affect our changes. 

this PR just upgrades `github.com/gophercloud/gophercloud` to v0.1.0.
- the following bug fixes may affect us: 
1.  [Core: Reauth Concurrency fixes](https://github.com/gophercloud/gophercloud/commit/a2b0ad6ce68c8302027db1a5f9dbb03b0c8ab072) --> [newOpenstack](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L415) 
2. [Core: Fix deadlock with reauthentication](https://github.com/gophercloud/gophercloud/commit/3f3cc5a566b2284815a4b6feb9e8c8f3d74aecdf) --> [newOpenstack](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L415) 
3. [Networking V2: Fix deleting external gateway for router](https://github.com/gophercloud/gophercloud/commit/ccaa267cb11183095eae75516a17b1b971c9aadb) --> [updateRoutes](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_routes.go#L106)
4. [check for project id if project name specified](https://github.com/gophercloud/gophercloud/commit/71f66c29139556381ce304ec5c4b25a5ce3b4d8b)  --> When user need to read Openstack configuration from environment variables
5. [Block Storage V3: Add volume image metadata field](https://github.com/gophercloud/gophercloud/commit/007769a86dc5d6a0fd6365ae181a2cdc165fcb80) --> [VolumesV3](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack_volumes.go#L68)
- the following fix may affect cluster security:
1. [Don't print token on token auth method](https://github.com/gophercloud/gophercloud/commit/1992d5238d782a2ae0063b16eb9705548e6b351b)
2. [Hide application credential auth while debug](https://github.com/gophercloud/gophercloud/commit/ad4210895ed0335a9b5e178b51f22e16a4fc6a8d)
 
> If I have any missing commits, please fix me.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by toliu** [comment]
Hello @cblecker ,sorry about the CLA, now I have logged in to the CAL, please restart the test.

**Comment by dims** [comment]
@toliu can you please sign the CLA? details here - https://github.com/kubernetes/community/blob/master/CLA.md

**Comment by dims** [comment]
/assign @thockin @liggitt 

Can one of you please give the root approval for this dependency change?

**Comment by saschagrunert** [comment]
Hey @toliu :wave:, can we please edit the release-notes to be simply `NONE`, without the `*`es?

**Pull request merged**
