### PR TITLE
Automated cherry pick of #72534: kube-proxy: rename internal field for clarity #74394: Fix small race in e2e

### PR DESCRIPTION
**Pull request by spencerhance**
Cherry pick of #72534 #74394 on release-1.12.

#72534: kube-proxy: rename internal field for clarity
#74394: Fix small race in e2e

### CODE REVIEW

**Comment by feiskyer** [comment]
/ok-to-test

@thockin Could you help to approve the cherry pick? If you want this to be included in Kubernetes v1.12.8, please get it approved by end of this Friday.

/assign @thockin

**Comment by spencerhance** [comment]
Fixed the failing checks.  @thockin, mind taking another look?

**Comment by feiskyer** [comment]
Since the e2e tests [[sig-network] Services should be able to change the type and ports of a service [Slow] [DisabledForLargeClusters]Changes](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sstable2-slow/1120095462427201537), this cherry pick is reverted by #76885.

@spencerhance Could you fix the test failures and create a separate cherry pick for this?

**Pull request merged**
