### PR TITLE
delete ovirt kube-up

### PR DESCRIPTION
**Pull request by mikedanese**
untouched since 2014. I'm not sure what this file is.

### CODE REVIEW

**Comment by roberthbailey** [comment]
@simon3z (since he added this in #1189). 

Should we also remove the files in https://github.com/kubernetes/kubernetes/tree/master/pkg/cloudprovider/providers/ovirt?

**Comment by simon3z** [comment]
@mikedanese @roberthbailey this file is the configuration example for the ovirt cloudprovider. I am not sure if now we're keeping these config examples somewhere else (e.g. what about aws). The fact that an example config file is not touched since 2014 doesn't seem a criteria to remove an entire cloudprovider.

**Comment by mikedanese** [comment]
So this is a cloudprovider config not a kube-up? And there is no documentation on what it is used for or how to use it? sig-cluster-lifecycle is working to remove cluster/. This feels like dead code.

**Comment by mikedanese** [comment]
This config is sufficiently documented here https://kubernetes.io/docs/getting-started-guides/ovirt/. It doesn't need to be duplicated in cluster.

**Comment by simon3z** [comment]
@mikedanese OK for me to remove the example configuration (but not the cloudprovider).

**Comment by mikedanese** [comment]
@simon3z great. That's what we will do then.

**Pull request merged**
