### PR TITLE
remove unused parameter

### PR DESCRIPTION
**Pull request by duan-yue**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
code clean
**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by duan-yue** [comment]
@freehan I rebase the newest code, but it still fails on some test. Though I think the failure is not caused by my commit, should I close this pr?

**Comment by freehan** [comment]
can you try to run the following unit test?
`go test -v k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry -run TestStoreWatch$`

**Comment by duan-yue** [comment]
Yes, it will pass. [ log ](https://gist.github.com/duan-yue/db17cbca54f6d561441ae34dc62fb9b2)

**Comment by duan-yue** [comment]
@freehan  @dcbw,  I rebase repo and the test has been pass.

**Comment by freehan** [comment]
Thanks!
/lgtm
/approve

**Comment by duan-yue** [comment]
@matchstick waiting for your approval

**Comment by dcbw** [comment]
/test pull-kubernetes-kubemark-e2e-gce

GCE setup flake

**Pull request closed without merging**
