### PR TITLE
Switch k/k to k8s.io/utils/inotify

### PR DESCRIPTION
**Pull request by quinton-hoole**
**Special notes for your reviewer**:
This is hopefully the final step in #80092

**Does this PR introduce a user-facing change?**:
No

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
None

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@dims My CLA seems to have got messed up when my github account went through some weirdness.  Do you have the requisite superpowers to fix that? If not, I can try to resign the CLA, but it seems that would be the wrong thing to do.

**Comment by quinton-hoole** [comment]
Also, it seems that running hack/update-vendor.sh did not in fact update the vendor directory, despite reporting success. @liggitt ?  Any advice much appreciated.

**Comment by liggitt** [comment]
> it seems that running hack/update-vendor.sh did not in fact update the vendor directory, despite reporting success. @liggitt ? Any advice much appreciated.

update-vendor.sh rebuilds the vendor dir based on the content of the root go.mod file. it doesn't look like you modified that to pull in a new version of k8s.io/utils

see https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/vendor.md#adding-or-updating-a-dependency for instructions on using `hack/pin-dependency.sh` and `hack/update-vendor.sh` to bump a specific dependency to a new version

**Comment by BenTheElder** [comment]
> @dims My CLA seems to have got messed up when my github account went through some weirdness. Do you have the requisite superpowers to fix that? If not, I can try to resign the CLA, but it seems that would be the wrong thing to do.

The CNCF helpdesk has some powers but nobody in the project does currently as far as I know.https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting

**Review by mattjmcnaughton — COMMENTED** [review]
@quinton-hoole @dims just confirming, this is (generally) the same code as `sigma/go-inotify`, its just the sigma project was no longer being maintained, so now its hosted under `k8s.io/utils`?

If yes, makes sense to me modulo resolving any verify errors.

**Comment by dims** [comment]
@mattjmcnaughton yes! ( cc @sigma )

**Comment by dims** [comment]
@quinton-hoole so, to get this going again:
1) please contact the helpdesk (link from @BenTheElder above)
2) run `hack/pin-dependency.sh k8s.io/utils 3dccf664f023863740c508fb4284e49742bedfa4` to bump to latest k8s.io/utils dependency
3) run `hack/update-vendor.sh` 
4) update the PR with the results of #2 and #3.

You should see files under `vendor/k8s.io/utils/inotify/` get added after #2 and #3, as well as updates to the go.mod/go.sum with the SHA from step 2.

Thanks,
Dims

**Comment by quinton-hoole** [comment]
Thanks @liggitt , @dims , @BenTheElder 
I've just done all of the above.  The helpdesk has not responded yet (understandably).  Hopefully this will merge as soon as they've sorted out my CLA. 

I'm going to be offline (sailing!) for two weeks.  If anyone wants to pick this up while I'm gone (including stealing the commits into a new PR if needed), please do feel free to do so. Otherwise I will tie up any remaining loose ends when I return.

**Comment by dims** [comment]
@Pothulapati please feel free to take this over based on @quinton-hoole 's comments :)

**Comment by cblecker** [comment]
Closing in favour of #80689 
/close

**Pull request closed without merging**
