### PR TITLE
[etcd] Reduce the etcd surface area in the integration test to minimize deps

### PR DESCRIPTION
**Pull request by timothysc**
This is a code refactor for isolation of client usage.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37124)

### CODE REVIEW

**Comment by hongchaodeng** [comment]
Good cleanup!
LGTM
Defer to @wojtek-t and/or @gmarek

**Comment by hongchaodeng** [comment]
@k8s-bot bazel test this

**Comment by timothysc** [comment]
@k8s-bot cvm gke e2e test this

**Comment by timothysc** [comment]
@k8s-bot gci gke e2e test this

**Pull request merged**
