### PR TITLE
hack/make-rules/test.sh: run all staging unit tests

### PR DESCRIPTION
**Pull request by sttts**
```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
looks reasonable at first glance, though the fact that CI doesn't use this script means we don't have a reasonable way of making sure it keeps working :-/

**Comment by sttts** [comment]
> looks reasonable at first glance, though the fact that CI doesn't use this script means we don't have a reasonable way of making sure it keeps working :-/

Which is true for much of the build infrastructure next to bazel. Having two build systems is suboptimal.

**Pull request merged**
