### PR TITLE
Report Hostname node address for vsphere

### PR DESCRIPTION
**Pull request by liggitt**
xref https://github.com/kubernetes/kubernetes/issues/67714

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
/cc @abrarshivani @baludontu @divyenpatel @imkin @kerneltime @luomiao @frapposelli @dougm

apologies for the mass cc, not sure who is best positioned to review this. this is a follow up to https://github.com/kubernetes/kubernetes/pull/65594 making cloud providers authoritative for the node addresses they report, and updates vsphere to report the HostName address it has for the local kubelet to preserve pre-1.12 behavior.

**Comment by divyenpatel** [comment]
@liggitt 

With 1.9 latest code base - `v1.9.11-beta.0.15+65310cab62aa05`, I see `Hostname` type `address` is already available for vsphere nodes.

```
"addresses": [
            {
                "address": "10.160.215.21",
                "type": "ExternalIP"
            },
            {
                "address": "10.160.215.21",
                "type": "InternalIP"
            },
            {
                "address": "kubernetes-node1",
                "type": "Hostname"
            }
        ],
```

I have checked vsphere cloud provider code on the master branch, I see no difference for the function `func (vs *VSphere) NodeAddresses(nodeName k8stypes.NodeName) ([]v1.NodeAddress, error) {` between two branch.

on the master branch build (`v1.13.0-alpha.0.626+ed3c32c3f9af0e-dirty`), I see only `ExternalIP` and `InternalIP` reported.

```
    "status": {
        "addresses": [
            {
                "address": "10.162.7.189",
                "type": "ExternalIP"
            },
            {
                "address": "10.162.7.189",
                "type": "InternalIP"
            }
        ],
```

Can you point to the code in kubernetes master branch which caused this regression?

**Comment by liggitt** [comment]
See the description in https://github.com/kubernetes/kubernetes/issues/67714

**Review by divyenpatel — APPROVED** [review]

**Comment by figo** [comment]
@liggitt this issue failed test in cross-cloud CI and also a conformance tests CI for vSphere, https://github.com/crosscloudci/crosscloudci/issues/65#, i saw your pull while submitting a fix, thanks for the fix, my fix is the same, so i just create another pull request to submit the test part, https://github.com/kubernetes/kubernetes/pull/68017 thanks

**Pull request merged**
