### PR TITLE
Kubelet: Remove GetAPIPodStatus from runtime interface

### PR DESCRIPTION
**Pull request by Random-Liu**
For issue #18302

Based on #19579, #19784, #19785 and #19850.

Only the last two commits are new.

In this PR, I removed the `GetAPIPodStatus()` from the runtime interface. However, there are a number of unit tests relying on it, so I just removed the old test and will add test for `convertStatusToAPIStatus()` in future PRs.

@yujuhong @yifan-gu Because of the merge queue, there are soooooo many pending PRs, it may make the PR very hard to review. Sorry about that, :(

### CODE REVIEW

**Comment by Random-Liu** [comment]
@k8s-bot e2e test this please.

**Comment by Random-Liu** [comment]
@k8s-bot e2e test this please.

**Comment by Random-Liu** [comment]
@k8s-bot e2e test this please.

**Comment by yifan-gu** [comment]
@Random-Liu Feel free to ping me to review once the depending PRs are merged

**Comment by Random-Liu** [comment]
@yifan-gu Sure! There are too many pending PRs now...Hahaha

**Comment by Random-Liu** [comment]
@yujuhong Addressed comments and rebased. PTAL~

**Comment by Random-Liu** [comment]
@yujuhong Addressed comments. :) Will squash this commit before merging.

**Comment by yujuhong** [comment]
LGTM. Feel free to apply the label after squashing the commits.

**Comment by Random-Liu** [comment]
@yujuhong Thanks! :)

**Comment by Random-Liu** [comment]
All test passed, self apply LGTM.

**Comment by Random-Liu** [comment]
@k8s-bot test this please

**Comment by Random-Liu** [comment]
Apply P1 because this is part of 1.2 plan and there is still a pending PR #20205 dependents on this.

**Comment by Random-Liu** [comment]
@k8s-bot test this issue: #20694

**Comment by Random-Liu** [comment]
@k8s-bot test this issue: #20694

**Comment by Random-Liu** [comment]
@k8s-bot test this issue: #20694

**Comment by yujuhong** [comment]
@k8s-bot test this issue: #19997

**Pull request merged**
