### PR TITLE
Improve description for --masquerade-all and --cluster-cidr flags

### PR DESCRIPTION
**Pull request by caseydavenport**
**What this PR does / why we need it**:

Improves the help text for the kube-proxy's `--masquerade-all` and `--cluster-cidr` flags, which previously were vague and confusing.

Fixes https://github.com/kubernetes/kubernetes/issues/47213

```release-note
NONE
```

### CODE REVIEW

**Review by cmluciano — COMMENTED** [review]
lgtm

**Comment by xiangpengzhao** [comment]
Hi Casey, why did you close this PR? It seems useful :)

**Comment by thockin** [comment]
@caseydavenport did you delete the branch on purpose?

**Comment by caseydavenport** [comment]
@xiangpengzhao @thockin huh, I have no recollection of closing this.

**Comment by cmluciano** [comment]
Hitting flakes here https://github.com/kubernetes/kubernetes/issues/51379

**Comment by caseydavenport** [comment]
@thockin I rebased this, so will need a new lgtm.

**Pull request merged**
