### PR TITLE
fix typo in kubelet

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by xiangpengzhao — APPROVED** [review]

**Comment by xiangpengzhao** [comment]
please fill `Release note:` with `NONE` in the template for your future PRs, so that the bot can tag `release-note-none` automatically. (You can also reply `/release-note-none`)

**Comment by k82cn** [comment]
@k8s-bot ok to test

**Comment by k82cn** [comment]
/lgtm

typo

**Comment by yujuhong** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

/lgtm

**Pull request merged**
