### PR TITLE
harmonize command line output when failed to parse command line

### LINKED ISSUE #107012: Malformed error messages
### What happened?

kubectl returns the traceback for commands that don't exit:
```
$ kubectl list services -A
E1214 11:26:50.918812    3285 run.go:120] "command failed" err="unknown command \"list\" for \"kubectl\"\n\nDid you mean this?\n\tget\n\twait\n"
```

### What did you expect to happen?

Instead, it should return that the command does not exist, 
eg.
```
$ kubectl list services -A
Unknown command "list" for kubectl. Did you mean this?
    get
    wait 
```

### How can we reproduce it (as minimally and precisely as possible)?

```kubectl list services -A```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:08:39Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Cloud provider

<details>
minikube
</details>

### OS version

<details>

```console
macOS
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by xyz-li**
Signed-off-by: LiHui <andrewli@kubesphere.io>

#### What type of PR is this?

/kind bug 

#### What this PR does / why we need it:
If cobra cannot run the cmd, there is must be an error to parse the command line, then`component-base/cli` should just print that error message.

#### Which issue(s) this PR fixes:

Fixes #107012 

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MadhavJivrajani** [comment]
/ok-to-test
@xyz-li please also add a release note (in the PR description) since this is a user-facing change :)

**Review by pohly — COMMENTED** [review]
I had a different solution in mind: if logging was not initialized, then we shouldn't use `klog.ErrorS`.

Let's hold this for a day so that I can think more about it tomorrow.

/hold

**Comment by pohly** [comment]
I kept thinking about this and now wonder whether any solution based on "let's use logging after parsing is done" (no matter how "parsing done" gets detected) will really work in all cases for a tool like `kubectl`. What if the actual kubectl command runs and then returns an error? Is logging it with `klog.ErrorS` really the right output for that scenario?

Perhaps the right solution is to parameterize it somehow: in kubectl, always print the error. In other tools, use the heuristic but otherwise switch to logging as soon as it is set up because the "normal" output of those other tools is a log event stream.

**Comment by xyz-li** [comment]
> I kept thinking about this and now wonder whether any solution based on "let's use logging after parsing is done" (no matter how "parsing done" gets detected) will really work in all cases for a tool like `kubectl`. What if the actual kubectl command runs and then returns an error? Is logging it with `klog.ErrorS` really the right output for that scenario?
I agree with you. 

A user runs `kubectl customize`, the output is ` E1215 16:30:10.934187   50699 run.go:122] "command failed" err="unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/Users/xxx/go/src/k8s.io/kubernetes'"`. This is a runtime error(or not ?), logging it with `klog.ErrorS` is hard to read.

**Comment by pohly** [comment]
> A user runs `kubectl kustomize`

Thanks for pointing that one out. I was looking for a case like that, but the ones that I tried worked because they use some kubectl specific `handleErr` and that worked. Looks like `kustomize` is not doing that and while I suspect that this might be an oversight, it confirms my concern.

**Pull request closed without merging**
