### PR TITLE
Optimize Cobra parameters of Controller Manager

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Optimize Cobra parameters of Controller Manager
#### Which issue(s) this PR fixes:

NONE

#### Special notes for your reviewer:
Optimize Cobra parameters of Controller Manager
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by binacs — APPROVED** [review]
/ok-to-test

**Comment by JingLMalan** [comment]
Awesome

**Comment by fedebongio** [comment]
Thank you @mikedanese for taking a look!
/cc @cici37 @jpbetz

**Pull request merged**
