### PR TITLE
Restore service latency test & fix bugs

### PR DESCRIPTION
**Pull request by lavalamp**
Ref #9555
Ref #9354

### CODE REVIEW

**Comment by ixdy** [comment]
@k8s-bot test this please

I believe the test failure was a flake caused by overloading GitHub while starting up the Jenkins builder.

**Comment by lavalamp** [comment]
Comments addressed, PTAL.

**Comment by lavalamp** [comment]
Changed to not make 600MB log files.

**Comment by ixdy** [comment]
Not a real e2e failure - this hit jenkinsci/ghprb-plugin#104.

**Comment by lavalamp** [comment]
shippable hit two different flakes... we really need to clean that up.

**Comment by lavalamp** [comment]
@quinton-hoole I can haz OK? this is blocking my other PR...

**Comment by quinton-hoole** [comment]
Oh yes.  My apologies!  LGTM!

**Comment by quinton-hoole** [comment]
Merging because it's purely test code, and a very useful signal.

**Comment by quinton-hoole** [comment]
Very easy to roll back if it fails.  I'll keep an eye on it this weekend.

**Comment by quinton-hoole** [comment]
@k8s-bot test this please

**Comment by quinton-hoole** [comment]
I'm demoting this to flaky, as it's failing ~70% of the runs on our Jenkins continuous integration with the following error:

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service_latency.go:99
Tail latency is > 4x median latency

**Comment by quinton-hoole** [comment]
I have reason to believe that this is a GCE issue rather than K8s.  I'll chat to you on Monday - pretty sure that we can sort it out.

**Comment by quinton-hoole** [comment]
My theory was rubbish.  Jenkins was misreporting this test as stable in some environments, whereas in actual fact it is flaky in all of them.  Back to you @lavalamp

**Comment by lavalamp** [comment]
Interesting, I will take a look. Why didn't I see any failures when I looked yesterday? Can you link to a failure?

**Comment by quinton-hoole** [comment]
It's in the flaky bucket.  I've sent you a link via email - it's a Google-internal link.

**Comment by quinton-hoole** [comment]
@lavalamp This is still failing ~70% of the time.  I'll open a separate issue to track fixing this.

Jenkins link: 
job/kubernetes-e2e-gce-flaky/1162/testReport/(root)/Kubernetes%20e2e%20suite/Service_endpoints_latency_should_not_be_very_high/history/

**Comment by lavalamp** [comment]
Yes, I know how to fix it and have a ton of code locally, but I'm busy fixing the proxy.

**Comment by quinton-hoole** [comment]
No worries.  Just want to make sure that we don't lose track of it.

**Pull request merged**
