### PR TITLE
Openstack: Update lb member when node port changes

### PR DESCRIPTION
**Pull request by dagnello**
Ensures lb members are update if node port changes.

cc @suonto

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34426)

### CODE REVIEW

**Comment by dagnello** [comment]
@anguslees can we run tests on this?

**Comment by anguslees** [comment]
@k8s-bot ok to test

**Comment by anguslees** [comment]
/lgtm

(the e2e failure looks like just another (unrelated) GCE quota limit issue)

**Comment by dagnello** [comment]
@anguslees can we re-run tests for this?

**Comment by dagnello** [comment]
@k8s-bot ok to test

**Comment by anguslees** [comment]
@k8s-bot gce e2e test this

**Comment by dagnello** [comment]
@anguslees looks like release note label needed and do-not-merge removed

**Pull request merged**
