### PR TITLE
Move release-1.2 forward to 3d58b9c07fdd2bf8cb063c30d791b94649b794e5

### PR DESCRIPTION
**Pull request by eparis**
however this excludes PR #22430

### CODE REVIEW

**Comment by bgrant0607** [comment]
cc @david-mcmahon

**Comment by bgrant0607** [comment]
Diff: 
https://gist.githubusercontent.com/eparis/591788686969412309e4/raw/98fc74502eb9cc72432e4c02604774196277dab4/git%2520diff%2520release-1.2..upstream%2520master

**Comment by eparis** [comment]
I'm trying to figure out how to get a diffstat without the (obvious) docs nonsense... We'll see....

**Comment by bgrant0607** [comment]
The diff of the PR I wanted to exclude is at the bottom. At a glance, the rest looks like doc-munging-related changes.

**Comment by eparis** [comment]
Diff from this PR to upstream master (3d58b9c07fdd2bf8)

https://gist.github.com/eparis/591788686969412309e4

This diff ignores all changes to files which end in .md
This diff ignores all changes which include the words 'releases.k8s.io'

This is the rest....

**Comment by eparis** [comment]
I got that diff by adding the following to my .git/config
```
[diff]
	tool = eparis-diff
[difftool "eparis-diff"]
	cmd = /tmp/diff.sh $LOCAL $REMOTE
```
And then putting the following in /tmp/diff.sh
```bash
#!/bin/bash

LOCAL="$1"
REMOTE="$2"

if [[ $LOCAL == *".md" ]]; then
	exit
fi

diff -Naup -I 'releases.k8s.io' "${LOCAL}" "${REMOTE}"
```

And running:
```
git difftool -y 3eb6278653c09c9f99f13f31fbdcaf1984dca65f..3d58b9c07fdd2bf8cb063c30d791b94649b794e5
```

So now you can reproduce my results at home!

(I am assuming that everyone will have my commit in their tree, in case you don't and are interested...)

I have
```
[remote "upstream"]
	url = https://github.com/kubernetes/kubernetes
	pushurl = crap
	fetch = +refs/heads/*:refs/remotes/upstream/*
	fetch = +refs/pull/*/head:refs/remotes/upstream/pr/*
```

So all I have to do is
```
git remote update
git show upstream/pr/22710
  or
git show 3eb6278653c09c9f99f13f31fbdcaf1984dca65f
```

**Comment by bgrant0607** [comment]
Awesome. LGTM

**Comment by bgrant0607** [comment]
cc @roberthbailey

**Comment by david-mcmahon** [comment]
Can we include the reproduction steps here for history's sake?  In case we need to do something like this in the future.  Commands with comments, please.

**Comment by eparis** [comment]
Notice this does not 'rewrite' history, it does not leave a vestigial tag, it just marches the release-1.2 branch forward. I hope people won't need to do this often. A wholesale update like this just doesn't belong. But basically what happened was the bgrant reviewed every PR between the release-1.2 branch (4d599ea3090b36b8c8658695495e66daa5bc8d80) and master (3d58b9c07fdd2bf8cb063c30d791b94649b794e5) he indicated every commit between those 2 points was reasonable for 1.2 except possibly #22430. So I found the first commit before the problematic PR. That first commit was 7e9256b39e4681bc23c53f2a5a0779f7b3308bc7.

So my basic steps (with a bit of psudo-code)
```
// create my local release-1.2 branch
- git checkout -b release-1.2 upstream/release-1.2

// Merge everything in master that we know is good into the release-1.2 branch
// but automatically solve conflicts by taking 'their' changes.
- git merge 7e9256b39 -X theirs

// Get all of the merges that I didn't get from the merge
- git log --merges 7e9256b39..3d58b9c07fdd2b --oneline --reverse
        a6aaf81 Merge pull request #22430 from gmarek/round-robin
        1c6a6aa Merge pull request #22697 from eparis/docs-readme-link
        43aa3d3 Merge pull request #18338 from gmarek/register-kubelet
        75699ff Merge pull request #22458 from bprashanth/ing_tls_e2e
        3d58b9c Merge pull request #22678 from spxtr/feature-tests

// For each merge I need to cherry-pick. We know that parent #1 of each merge is the 'trunk' so that helps. So I do this for all of the above EXCEPT a6aaf81
- git cherry-pick -m 1 $SHA

// Sadly a 1c6a6aa touches docs and so does the release branch, so it had a conflict.
- git status // to see what files were a problem
- vim + filenames to fix the problems
- git add $filenames
- git commit

// Now we've got all the code we need but most likely the -X theirs merge strategy screwed up the docs. So we re-run
- build/versionize-docs.sh

// Then we push it and open the PR and feel really smug.
- git push eparis release-1.2:release-1.2
```

**Comment by bgrant0607** [comment]
Merging.

**Pull request merged**
