### PR TITLE
Scheduler adds NvidiaGPU comparision in getResourceRequest()

### PR DESCRIPTION
**Pull request by lixiaobing1**
In file "plugin\pkg\scheduler\algorithm\predicates\predicates.go", function getResourceRequest(), line 391, only mem and cpu handled, NvidiaGPU is required to add to compare:
        if gpu := requests.NvidiaGPU().Value(); gpu > result.nvidiaGPU {
            result.nvidiaGPU = gpu
        }

### CODE REVIEW

**Comment by jfrazelle** [comment]
can a test be added to `predicates_test.go`

**Comment by lixiaobing10051267** [comment]
I will add some test cases next.

**Comment by lixiaobing10051267** [comment]
test cases have been added

**Comment by davidopp** [comment]
@Hui-Zhi could you review this?

**Comment by Hui-Zhi** [comment]
@davidopp Sure.

@lixiaobing10051267 So far only 0 (default) and 1 are currently supported, so I don't think we need this right not. Regarding multiple GPU support, I have another pull request: #28216, if this request be merged, will need to check GPU in the predicates.

**Comment by lixiaobing10051267** [comment]
ok, thanks very much.

**Pull request closed without merging**
