### PR TITLE
Network tests: check for errors when dialing from node to services

### PR DESCRIPTION
**Pull request by fedepaol**
The current implementation does not check for errors, so any failure in
DialFromNode won't float.

Signed-off-by: Federico Paolinelli <fpaoline@redhat.com>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

In the "host to service backed by hostnetwork" test we don't check for the error returned by `DialFromNode`, so any failure won't be reported.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/ok-to-test
Thanks, it was my fault, I created those tests before the refactor of the function (it didn´t return error previously) and I didn´t check it again,  so they merged with the old logic, that expected the function to fail the framework.

@fedepaol we have the same issue with the dual-stack tests
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/dual_stack.go#L473
do you want to add an additional commit and fix them there too?

**Comment by aojea** [comment]
/lgtm

if this merges, we just need to remember to update the dual-stack ones

**Comment by fedepaol** [comment]
> /lgtm
> 
> if this merges, we just need to remember to update the dual-stack ones

This test is not implemented in dual stack, I am working on a PR for that (actually, it's how I found it was not checking the error)

**Comment by aojea** [comment]
> This test is not implemented in dual stack, I am working on a PR for that (actually, it's how I found it was not checking the error)

I mean, there are tests in the dualstack file that are not checking for the error, same as here, they need to be modified to check for the error

**Comment by fedepaol** [comment]
> > This test is not implemented in dual stack, I am working on a PR for that (actually, it's how I found it was not checking the error)
> 
> I mean, there are tests in the dualstack file that are not checking for the error, same as here, they need to be modified to check for the error
> 
> https://github.com/kubernetes/kubernetes/blob/081f68d6852872573d63e2b922d1afdcc602746b/test/e2e/network/dual_stack.go#L476-L479

Got it, will change them too

**Comment by aojea** [comment]
great, thanks for fixing this
/lgtm
Hope there are no more Easter eggs tests hidden

**Comment by aojea** [comment]
thanks for the great effort, too many places, I double checked and I think that this is the good one
```
grep -r DialF test/ | grep -vE "err|//|ginkgo"
Binary file test/images/agnhost/agnhost matches
test/e2e/framework/network/utils.go:    return config.DialFromContainer(protocol, echoHostname, config.EndpointPods[0].Status.PodIP, targetIP, EndpointHTTPPort, targetPort, maxTries, minTries, expectedEps)
test/e2e/framework/network/utils.go:    return config.DialFromContainer(protocol, echoHostname, config.TestContainerPod.Status.PodIP, targetIP, testContainerHTTPPort, targetPort, maxTries, minTries, expectedEps)
test/e2e/framework/network/utils.go:    return config.DialFromContainer(protocol, dialCommand, config.TestContainerPod.Status.PodIP, targetIP, testContainerHTTPPort, targetPort, maxTries, minTries, expectedResponse)
```

those return belongs to a function that return an error
/lgtm

**Review by MrHohn — APPROVED** [review]
/approve

**Pull request merged**
