### PR TITLE
kubeadm: use defer to unlock mutex in certs.go

### PR DESCRIPTION
**Pull request by rainrambler**
Use defer feature for unlock

#### What type of PR is this?
kind cleanup

#### What this PR does / why we need it:
Use defer feature for unlock.

#### Which issue(s) this PR fixes:
N/A

#### Does this PR introduce a user-facing change?
No

### CODE REVIEW

**Comment by neolit123** [comment]
Hi the PR looks ok but you need to sign the CLA.
See the message from the bot above.

**Comment by rainrambler** [comment]
I signed it

**Comment by neolit123** [comment]
@rainrambler 

the bot is not updating the label to `cncf-cla: yes`
sometimes the CLA signing is buggy and you have to contact the CNCF help desk for them to fix it.

**Comment by rainrambler** [comment]
> @rainrambler
> 
> the bot is not updating the label to `cncf-cla: yes`
> sometimes the CLA signing is buggy and you have to contact the CNCF help desk for them to fix it.

Thanks @neolit123 , check-cla returns yes now.

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve 
/triage accepted
/ok-to-test

/retitle kubeadm: use defer to unlock mutex in certs.go

**Pull request merged**
