### PR TITLE
places vsphere volumes as per zones

### LINKED ISSUE #73301: vSphere volumes do not have zone labels auto applied
**What happened**:
With zones marked using tags in vCenter and using VCP, the k8s nodes show the zone information correctly in its labels, but a volume does not have the zone labels applied. A node's zone information works correctly due to PR https://github.com/kubernetes/kubernetes/pull/66795.

```
$:~> kubectl get nodes --show-labels
NAME                 STATUS                     AGE       VERSION                                     LABELS
kubernetes2-master   Ready,SchedulingDisabled   6d        v1.14.0-alpha.0.1570+ccf84273118a1f-dirty   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=region_1,failure-domain.beta.kubernetes.io/zone=zone_1,kubernetes.io/hostname=kubernetes2-master
kubernetes2-node1    Ready                      6d        v1.14.0-alpha.0.1570+ccf84273118a1f-dirty   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=region_1,failure-domain.beta.kubernetes.io/zone=zone_1,kubernetes.io/hostname=kubernetes2-node1
```

However, a newly created volume does not show any zone labels today.

```
$:~> kubectl get pv --show-labels
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM          STORAGECLASS   REASON    AGE       LABELS
pvc-aab193fe-1fc8-11e9-a263-005056929afb   1Mi        RWO           Delete          Bound     default/pvc1   sc1                      17h       None
```

**What you expected to happen**:

A newly created volume should be automatically applied with the well-known zone labels.

```
$:~> kubectl get pv --show-labels
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM          STORAGECLASS   REASON    AGE       LABELS
pvc-aab193fe-1fc8-11e9-a263-005056929afb   1Mi        RWO           Delete          Bound     default/pvc1   sc1                      17h       failure-domain.beta.kubernetes.io/region=region_1,failure-domain.beta.kubernetes.io/zone=zone_1
```

This is important since the scheduler places the pod on a node of the same zone based on the Volume's zone information.

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup zones in vCenter by tagging an ESX host, cluster or datacenter with the tag name of your choice and tag category, say "zoneCategory" and "regionCategory".
2. Update the /etc/kubernetes/vsphere.conf file in each k8s node to include the following and restart kubelet.
```
[Labels]
    zone = "zoneCategory"
    region = "regionCategory"
```
3. Create a PV and look at the auto-applied labels on it as shown above. The zone information is missing.

**Anything else we need to know?**:
The partially addresses https://github.com/kubernetes/kubernetes/issues/67703

**Environment**:
- Kubernetes version (use `kubectl version`): any
- Cloud provider or hardware configuration: vSphere

### PR DESCRIPTION
**Pull request by subramanian-neelakantan**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This is a cherry-pick of PRs #72731 and PR #72687 to be merged into release-1.13. When this PR is merged, vSphere volumes will get placed as per zone requested in allowedTopologies property of a storage class. Also the newly created volume is labelled with the zone information. See the base PRs for more details.

**Which issue(s) this PR fixes**:

Fixes #73301
refers to issue #67703

**Special notes for your reviewer**:
All the existing vsphere e2e tests were run against this PR and found to be passing.
1.   This change ensures that volumes get provisioned based on the zone information provided in allowedTopologies.
```
Storage class spec:
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fastpolicy1
provisioner: kubernetes.io/vsphere-volume
parameters:
    diskformat: zeroedthick
    storagePolicyName: vSAN Default Storage Policy
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - zone1
```
PV creation Logs:
```
I0109 11:17:52.321372       1 vsphere.go:1147] Starting to create a vSphere volume with volumeOptions: &{CapacityKB:1048576 Tags:map[kubernetes.io/created-for/pvc/namespace:default kubernetes.io/created-for/pvc/name:pvcsc-1-policy kubernetes.io/created-for/pv/name:pvc-34650c12-1400-11e9-aef4-005056804cc9] Name:kubernetes-dynamic-pvc-34650c12-1400-11e9-aef4-005056804cc9 DiskFormat:zeroedthick Datastore: VSANStorageProfileData: StoragePolicyName:vSAN Default Storage Policy StoragePolicyID: SCSIControllerType: Zone:[zone1]}
...
I0109 11:17:59.430113       1 vsphere.go:1334] The canonical volume path for the newly created vSphere volume is "[vsanDatastore] 98db185c-6683-d8c7-bc55-0200435ec5da/kubernetes-dynamic-pvc-34650c12-1400-11e9-aef4-005056804cc9.vmdk"
```

2.   This change also applies zone labels to vSphere Volumes automatically. The zone labels are visible on the PV:
```
$ kubectl get pv --show-labels
NAME           CAPACITY   ACCESSMODES   STATUS    CLAIM            REASON    AGE       LABELS
pv-abc                5Gi        RWO                   Bound     default/claim1                    46s       failure-domain.beta.kubernetes.io/region=VC1,failure-domain.beta.kubernetes.io/zone=cluster-1
```

**Does this PR introduce a user-facing change?**:
```release-note
Applies zone labels to vSphere Volumes and honors allowedTopologies when provisioning.
```

/sig vmware
/sig storage
/sig api-machinery
/cc @vladimirvivien @frapposelli

### CODE REVIEW

**Comment by frapposelli** [comment]
/lgtm
/approve

/assign @tpepper 

This is for the next 1.13 patch release

**Comment by frapposelli** [comment]
/assign @SandeepPissay @divyenpatel @deads2k @derekwaynecarr

PTAL

**Comment by roycaihw** [comment]
cc @cheftako

**Comment by tpepper** [comment]
In the future please use the [cherry-pick automation](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md).

As I read the description and saw the size/XL this came across as a feature.  Then I looked at the resolved issue and it is marked as a feature.  I need some convincing this is actually a cherry pick candidate.

**Comment by subramanian-neelakantan** [comment]
> In the future please use the cherry-pick automation.
Will do. Thanks for letting me know the right process.

> As I read the description and saw the size/XL this came across as a feature. Then I looked at the resolved issue and it is marked as a feature. I need some convincing this is actually a cherry pick candidate.
This cherry-pick contains two related PRs - #72731 and #72687 - both of which fix slightly different issues. vSphere cloud provider already implements the zones interface. With Zones support the nodes get zone labels as per the tags in vcenter inventory and users could provision pods to zones. However it did not work well when volumes were not placed in specific configurations. PR #72687 fixes issue #73301 (zone labels need to be auto-applied to a volume, so that pod scheduler can choose the right pod as per volume) and PR #72731 fixes the issue of placing the volume in a datastore of the right zone. These issues were causing wrong and strange behaviour of volumes in a vsphere environment that uses zones when the datastore were not shared across all k8s nodes.

I apologize for not giving the reference of the right issues in the description. I have done that now. Kindly take another look and let me know if you have questions.

**Comment by subramanian-neelakantan** [comment]
@tpepper PTAL

**Comment by subramanian-neelakantan** [comment]
@deads2k @derekwaynecarr can you take a look at this PR for a cherry pick into 1.13?

**Comment by derekwaynecarr** [comment]
echo the sentiment on using the automation.  the admission changes look fine.

/approve

**Comment by subramanian-neelakantan** [comment]
Cleaned up the release notes in description.

**Pull request merged**
