### PR TITLE
Remove runtime.VersionedObject from universal apimachinery

### PR DESCRIPTION
**Pull request by yue9944882**
we have a lot of legacy code supporting`runtime.VersionedObject`while actually it's completely unused for several releases. removing this makes the decoder much cleaner.

/sig api-machinery
/kind cleanup

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by justinsb** [comment]
My understanding is that because this is in staging, this is possibly part of a public API.  So I don't think we can be sure that `VersionedObjects` is unused just because it isn't used in k/k.

However, I agree with you that it certainly looks like it isn't something that would be used by production code (it feels like a debug/diagnostics tool)

**Comment by yue9944882** [comment]
> So I don't think we can be sure that VersionedObjects is unused just because it isn't used in k/k.

@justinsb yeah i suppose thats the exact reason why this definition has been kept in k/k for several releases. but it definitely makes the decoders (json/protobuf/versioning) difficult to understand (which is the motivation of this pull 😅). 

@kubernetes/api-approvers could u shed some light on whether to prune this from k/k?

**Comment by bgrant0607** [comment]
@lavalamp or @deads2k probably know

**Comment by deads2k** [comment]
/hold

I'd like time to investigate this one.

**Comment by deads2k** [comment]
I'm really not sure.  I'm not sure I'd take the risk at this point in the release.

@smarterclayton @lavalamp think we're just falling back to a different path?  I don't remember history here.

**Comment by smarterclayton** [comment]
This was for generic Cli commands that needed the internal version.  There was some discussion about using it in the rest storage, but I don’t think we ever did.

I’m favor of removing this but not in 1.13.  Have you done a GitHub sweep to identify possible callers?

**Comment by yue9944882** [comment]
> Have you done a GitHub sweep to identify possible callers?

didnt find any go project using `runtime.VersionedObject`. mystery huh.🤔

**Comment by lavalamp** [comment]
This is a confusing type and if we can delete it, we should, esp. while we don't offer compatibility guarantees for the apimachinery library.

I agree with the others that we should wait until after the release though.

**Comment by yue9944882** [comment]
the question again for `runtime.NestedObjectEncoder`. wdyt if we prune that together?

**Comment by liggitt** [comment]
can this be revived? I'd like to simplify as much here as we can, and I haven't seen any evidence of use here

**Comment by yue9944882** [comment]
sure reviving 👨🏼‍🔬

**Comment by deads2k** [comment]
I don't seem immediate issues.  I forgot about this, sorry.

/hold cancel

**Pull request merged**
