### PR TITLE
initial e2e tests for ValidatingAdmissionPolicy

### PR DESCRIPTION
**Pull request by jiahuif**
#### What type of PR is this?

/kind feature
#### What this PR does / why we need it:
- initial tests for ValidatingAdmissionPolicy
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
The way we used before to add a e2e test for alpha feature is to add a args in test-infra: https://github.com/kubernetes/test-infra/pull/26994/files
And then use the args in e2e test like: 
```
SIGDescribe("CustomResourceValidationRules [Privileged:ClusterAdmin][Feature:CustomResourceValidationExpressions]"
```
Replace Feature:CustomResourceValidationExpressions with the feature you defined in test-infra.

**Comment by jiahuif** [comment]
/assign @cici37 
Test is passing. Could you take another look? Thank you.

**Comment by cici37** [comment]
/lgtm
/assign @jpbetz 
for approval. Thanks!

**Pull request merged**
