### PR TITLE
Rename {kube- ->}apiextensions-{-> api}server

### PR DESCRIPTION
**Pull request by sttts**
Completely mechanical renaming, as preparation of the repo sync. This repo is generic, the prefix does not make sense.

Part of issue https://github.com/kubernetes/kubernetes/issues/46702

TODOs
- [ ] Waiting for the submit queue to settle, then rebase.

### CODE REVIEW

**Comment by deads2k** [comment]
Seems like there should have been a bunch of package rename changes in .go files.

**Comment by sttts** [comment]
Waiting for a lgtm before I rebase. This breaks easily as long as apiextension PRs keep merging.

**Comment by deads2k** [comment]
lgtm.  @caesarxuchao ?

**Comment by sttts** [comment]
@smarterclayton is this approved? as this touched quite a number of packages due to the import rewrites, it needs a top-level approval.

**Comment by smarterclayton** [comment]
I'd rather drop this in after the queue clears.

/approve 

if you can wait for that (and mention this to dawn so she's aware)

**Comment by nikhita** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Pull request merged**
