### PR TITLE
DO NOT MERGE: Testing new e2e image

### PR DESCRIPTION
**Pull request by zmerlynn**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37298)

### CODE REVIEW

**Comment by spxtr** [comment]
@k8s-bot test this

**Comment by zmerlynn** [comment]
@k8s-bot cvm gke e2e test this
@k8s-bot gce etcd3 e2e test this

**Comment by zmerlynn** [comment]
@k8s-bot bazel test this

**Comment by zmerlynn** [comment]
Trying to tickle kops timeout so I can see logging work, too.

@k8s-bot aws e2e test this

**Comment by zmerlynn** [comment]
again!
@k8s-bot aws e2e test this

**Comment by zmerlynn** [comment]
@k8s-bot node e2e test this
@k8s-bot cri node e2e test this

**Comment by ixdy** [comment]
@k8s-bot gce e2e test this

**Pull request closed without merging**
