### PR TITLE
Sort list of formats for --logging-format description to make it deterministic

### LINKED ISSUE #94628: 1.19: 1 bit non-determinism in kube-scheduler.1
**What happened**:
50% of builds have a different man page content

**What you expected to happen**:
It should be possible to get bit-identical build results - might need a patch similar to #68983 - @dims knows these things.

**How to reproduce it (as minimally and precisely as possible)**:
build kubernetes1.19 openSUSE package a few times and compare results. e.g. with [my rbk script](https://github.com/bmwiedemann/reproducibleopensuse/blob/master/rbk) 

**Anything else we need to know?**:

**Environment**:
- OS: openSUSE-Tumbleweed 20200906

While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds), I found that
when building the kubernetes1.19 package, there was sometimes such a difference between builds:

```diff
--- old//usr/share/man/man1/kube-scheduler.1    2020-09-08 18:04:00.987086806 +0000
+++ new//usr/share/man/man1/kube-scheduler.1    2020-09-08 18:04:01.015086912 +0000
@@ -257,7 +257,7 @@

 .PP
 \fB\-\-logging\-format string                                   Sets the log format. Permitted formats\fP
-        "json", "text".
+        "text", "json".

 .PP
 .RS
```

### PR DESCRIPTION
**Pull request by dims**
Signed-off-by: Davanum Srinivas <davanum@gmail.com>

**What type of PR is this?**

/kind cleanup
/kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #94628

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by monotek — APPROVED** [review]
/lgtm

**Review by ehashman — APPROVED** [review]
/approve
/lgtm

**Comment by bmwiedemann** [comment]
Tested the patch. Works fine.

The non-determinism probably comes from https://golang.org/src/hash/maphash/maphash.go?#L170 which uses randomness to avoid attacks where user-supplied hash keys are chosen to force the hash-table into a long list that slows processing down as a DoS.

I wonder if it would make it easier to be reproducible-by-default if go had a hash that has a constant hash seed for cases without user-input. Or if there was something like `$PERL_HASH_SEED` that can be set globally in the build environment.

**Pull request merged**
