### PR TITLE
Remove more legacy schemes and api

### PR DESCRIPTION
**Pull request by jmannanc**
**What this PR does / why we need it**:
Just removing more legacy schemes and api to corev1. My reference was this PR: https://github.com/kubernetes/kubernetes/pull/66926

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yue9944882** [comment]
/lgtm cancel 

@SneakyFish5 plz run `./hack/update-all.sh` and better make sure it's tested in your local env.😃

**Comment by SneakyFish5** [comment]
Seems like the tests are failing, could anyone offer guidance as to why? Did I use the wrong scheme pkg for BUILD?

**Pull request closed without merging**
