### PR TITLE
Use strong type for container ID

### PR DESCRIPTION
**Pull request by timstclair**
Change all references to the container ID in pkg/kubelet/... to the
strong type defined in pkg/kubelet/container: ContainerID

The motivation for this change is to make the format of the ID
unambiguous, specifically whether or not it includes the runtime
prefix (e.g. "docker://").

@yifan-gu 

cc/ @yujuhong @dchen1107 @vishh

### CODE REVIEW

**Comment by yifan-gu** [comment]
@timstclair Thanks for taking this important(though uninteresting)work!! Appreciate! :tophat: 

LGTM.

**Comment by yujuhong** [comment]
LGTM. Thanks for taking on this!

**Comment by yifan-gu** [comment]
Sorry, this needs a rebase since #14686 gets merged. I think we'd better hold other kubelet PRs so we can get this in first, otherwise there will be a lot of rebasing work.. /cc @kubernetes/goog-node

**Comment by yujuhong** [comment]
Agreed. #15051 is probably going to merge first. I will *try* to block the rest until this one lands.

**Comment by timstclair** [comment]
Rebased and changed `kubetypes` to `kubeletTypes` for consistency.

**Comment by dchen1107** [comment]
ok to test

**Comment by dchen1107** [comment]
We have to manually merge this one since it is block a lot of node related prs. cc/ @JanetKuo, oncall. Thanks!

**Pull request merged**
