### PR TITLE
refactor: partition statefulset pods with partitionStatefulSetPods

### PR DESCRIPTION
**Pull request by draveness**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

partition statefulset pods with partitionStatefulSetPods

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by draveness** [comment]
ping @smarterclayton @kow3ns @tnozicka.
It has been a week since opened, is there any review for this PR?

**Comment by tnozicka** [comment]
Is there a reason we need this PR? what issue it fixes? Is it needed for some followup changes? On the first look extracting some code into a function doesn't seem to add value but introduces a possibility of bugs, need to go through the PR flow and cost review time.

**Comment by draveness** [comment]
Hi @tnozicka, `updateStatefulSet` is a method with nearly 300 lines of code, which makes it a little harder to read and understand. I think it's easier to maintain the code with less code. 
The logic of partition the pods is quite clear in this method and won't cause any ambiguity, extract it from `updateStatefulSet` would do a little help of enhancing code maintainability.
Finally, thanks for your reply, and if it's not necessary, i would close this PR. 🤣

**Comment by tnozicka** [comment]
Also an important point is this breaks backports so I'd like to see stronger reason for refactoring it then just someone would find it easier to read.

**Pull request closed without merging**
