### PR TITLE
Fix wrong URL in cli-roadmap doc

### PR DESCRIPTION
**Pull request by feihujiang**
I found there is no component/CLI and component/client lables, these two URLs has no result.  So I changed them to component/kubectl and component/clientlib.

### CODE REVIEW

**Comment by feihujiang** [comment]
@bgrant0607 @lavalamp please review.

**Comment by bgrant0607** [comment]
Thanks. LGTM.

**Comment by bgrant0607** [comment]
Could you cherrypick this into 1.1?
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md

**Comment by feihujiang** [comment]
@bgrant0607  OK

**Pull request merged**
