### PR TITLE
Use on disk Dockerfile for server-images.

### PR DESCRIPTION
**Pull request by vinayakankugoyal**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
#98908 - Moves the server image Dockerfile to on-disk and uses ARG.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/test pull-kubernetes-cross
thanks!

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by vinayakankugoyal** [comment]
I am guessing this would be considered under sig/release ?

**Pull request merged**
