### PR TITLE
Update the latestReleaseBranch to release-1.3 in the munger.

### PR DESCRIPTION
**Pull request by david-mcmahon**
Ref #27218 #27205

### CODE REVIEW

**Comment by lavalamp** [comment]
@david-mcmahon can you separate changes you made and automatically made changes into two commits? This is unreviewable right now, github won't show the whole diff.

**Comment by david-mcmahon** [comment]
PTAL

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
I'll have to manually merge this. Should this message still be included in these docs? Many of them are now just placeholders. @johndmulhausen

**Comment by johndmulhausen** [comment]
LGTM. This is harmless but also probably the last release we should have these placeholders; between now and 1.4 let's try and kill any links to main repo docs once and for all.

**Comment by david-mcmahon** [comment]
@johndmulhausen is there an issue opened for that yet?

**Comment by lavalamp** [comment]
manual override merge.

**Pull request merged**
