### PR TITLE
Ansible: Get DNS working - Add kubectl kubeconfig file

### PR DESCRIPTION
**Pull request by eparis**

### CODE REVIEW

**Comment by eparis** [comment]
@jeffbean

**Comment by eparis** [comment]
@nzwulfin

**Comment by jeffbean** [comment]
LGTM.

**Comment by zmerlynn** [comment]
@k8s-bot: ok to test

**Comment by zmerlynn** [comment]
@k8s-bot: test this

**Comment by zmerlynn** [comment]
LGTM from a `contrib/ansible` only change, no risk to core. Merging on green.

**Pull request merged**
