### PR TITLE
Remove --redirect-container-streaming functionality

### PR DESCRIPTION
**Pull request by tallclair**
Addresses the v1.20 step of https://github.com/kubernetes/enhancements/issues/1558

```release-note
--redirect-container-streaming is no longer functional. The flag will be removed in v1.22
```

### CODE REVIEW

**Comment by tallclair** [comment]
/assign @Random-Liu 
Are you able to review this for me?

**Comment by SergeyKanzhelev** [comment]
/lgtm

the only very small nit thing I noticed that enhancement version history is not populated https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20191205-container-streaming-requests.md#implementation-history Version history may be found in rollout plan section https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20191205-container-streaming-requests.md#rollout-plan

**Comment by tallclair** [comment]
/assign @derekwaynecarr 
For approval

**Pull request merged**
