### PR TITLE
failed to attach cinder volume when another instance with the same name exists in openstack

### LINKED ISSUE #60491: Kubelet failed to get node info: failed to get external ID from cloud provider: multiple results where only one expected
Hi there,

I'm trying to install kubernetes cluster on Openstack with flag `--cloud-provider=openstack`. And when restart kubelet, i have error:
```
Feb 27 17:08:01 test1 kubelet[16407]: F0227 17:08:01.757592   16407 kubelet.go:1364] Kubelet failed to get node info: failed to get external ID from cloud provider: multiple results where only one expected
```

- The reason is on my openstack system, i have more than 1 instance with the same name `test1`. And i think it's the big problem when install kubernetes cluster on cloud-system.

Of course, when i change name of instance, everything is OK, but in the future, i don't know if there's some instances with the same name.

Please check this error for complete kubelet.

### LINKED ISSUE #86797: failed to attach cinder volume when another instance with the same name exists in openstack
**What happened**:
while attaching cinder volume to node , attach operation failed with the following errors:
```text
I1218 09:10:34.927983       1 reconciler.go:289] attacherDetacher.AttachVolume started for volume "mysql-persistent-storage" (UniqueName: "kubernetes.io/cinder/ea7455a8-2aee-45a7-8637-adac7543cd8c") from node "k8s-master3" 
E1218 09:10:35.256436       1 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/cinder/ea7455a8-2aee-45a7-8637-adac7543cd8c\"" failed. No retries permitted until 2019-12-18 09:12:37.25638979 +0000 UTC m=+844.289409933 (durationBeforeRetry 2m2s). Error: "AttachVolume.Attach failed for volume \"mysql-persistent-storage\" (UniqueName: \"kubernetes.io/cinder/ea7455a8-2aee-45a7-8637-adac7543cd8c\") from node \"k8s-master3\" : multiple results where only one expected"
I1218 09:10:35.256462       1 event.go:221] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"mysql", UID:"402d5aa6-2176-11ea-8453-fa163e9e83ee", APIVersion:"v1", ResourceVersion:"42246", FieldPath:""}): type: 'Warning' reason: 'FailedAttachVolume' AttachVolume.Attach failed for volume "mysql-persistent-storage" : multiple results where only one expected
```
**What you expected to happen**:
attach cinder volume successfully
**How to reproduce it (as minimally and precisely as possible)**:
install kubernetes v1.13.5
config kubernetes to use external cloud provider: --cloud-provider=external
create or rename a server instance with the same name in openstack
create a volume in openstack manually, and got the volume id , fill it in the following yaml
create simple pod yaml: mysql.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: mysql-test
  labels:
    name: mysql
spec:
  containers:
  - resources:
      limits :
        cpu: 0.5
    image: your-habor-address/mysql-image:5.7.26
    name: mysql
    args:
    - "--ignore-db-dir"
    - "lost+found"
    env:
    - name: MYSQL_ROOT_PASSWORD
      # change this
      value: yourpassword
    ports:
    - containerPort: 3306
      name: mysql
    volumeMounts:
    # name must match the volume name below
    - name: mysql-persistent-storage
      # mount path within the container
      mountPath: /var/lib/mysql
  volumes:
  - name: mysql-persistent-storage
    cinder:
      volumeID: the-volume-id-from-openstack
      fsType: ext4
```
create the pod : kubectl apply -f mysql.yaml
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
v1.13.5
- Cloud provider or hardware configuration: 
openstack
- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
- Kernel (e.g. `uname -a`):
Linux k8s-node1 3.10.0-693.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by zxcvb0987**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> 
/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
find the node by node name from node lister, and use SystemUUID to filter out the servers from openstack, so that no more "multiple results where only one expected" errors happen
**Which issue(s) this PR fixes**:

Fixes #60491
Fixes #86797

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by idealhack** [comment]
thank you but 1.13 is EOL and not accept patches anymore, see https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#114-and-older

/close

**Comment by idealhack** [comment]
if this is still a bug in master, you can fix it there and cherry-pick to all supported versions.

**Comment by houruiming1** [comment]
> if this is still a bug in master, you can fix it there and cherry-pick to all supported versions.

ok, thanks for the suggestion.

**Pull request closed without merging**
