### PR TITLE
Removing ServiceAppProtocol feature gate

### PR DESCRIPTION
**Pull request by robscott**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This removes the ServiceAppProtocol feature gate. This feature gate went GA in 1.20 and can be safely removed as part of
1.22.

#### Does this PR introduce a user-facing change?
```release-note
The ServiceAppProtocol feature gate has been removed. It reached GA in Kubernetes 1.20.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
Enhancement issue: https://github.com/kubernetes/enhancements/issues/1507

/sig network
/priority important-soon
/triage accepted
/assign @thockin

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by thockin** [comment]
I removed this from the tracking board.  You can close the KEP issue now.

**Comment by robscott** [comment]
Filed https://github.com/kubernetes/kubernetes/issues/103221 to cover unit test flake.

**Pull request merged**
