### PR TITLE
code cleanup: modify kube-scheduler, remove useless return value

### PR DESCRIPTION
**Pull request by binacs**
# Same as #101144 

#### What type of PR is this?

/kind cleanup
/kind design

#### What this PR does / why we need it:

#101144 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by BinacsLee** [comment]
/assign @alculquicondor 

Sorry for the mistake (close the PR). I've fixed the failing tests.

Could you please take a moment to review it again?

Thank you very much!

**Comment by BinacsLee** [comment]
Hi @alculquicondor , sorry to have to take your time.
The code has passed the test, could you please merging this PR?
Thanks!

**Review by alculquicondor — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
