### PR TITLE
Revert storage v1

### PR DESCRIPTION
**Pull request by liggitt**
If we're unable to get storage.k8s.io/v1 enabled in GKE, we should revert https://github.com/kubernetes/kubernetes/pull/40088 to get the queue running again.

### CODE REVIEW

**Comment by liggitt** [comment]
cc @jsafrane @ncdc @k8s-oncall

**Comment by liggitt** [comment]
this is in case we can't get GKE CI working with the v1 storage API
cc @thockin @saad-ali @msau42

**Comment by msau42** [comment]
I don't think it's going to get enabled in the next few hours so go ahead and revert it if it's blocking the entire submit queue.

**Comment by wojtek-t** [comment]
This is supposed to fix merge-queue. So merging manually.

**Pull request merged**
