### PR TITLE
Change Until... NeverStop to Forever

### PR DESCRIPTION
**Pull request by gmarek**

### CODE REVIEW

**Comment by gmarek** [comment]
@k8s-bot test this issue: #21484

**Comment by lavalamp** [comment]
Is this blocking anything? I'd actually like to get rid of forever & thread the stop channel all the way through to the top level. Having no stop channel encourages lazy tests that leave things running in memory.

I don't feel SUPER strongly so you can put the label back if you really disagree.

**Comment by gmarek** [comment]
No, it was just a cleanup.

**Comment by wojtek-t** [comment]
@gmarek - should we close this?

**Pull request closed without merging**
