### PR TITLE
Remove insensitive wordings from the docs like just - easy or - simple

### PR DESCRIPTION
**Pull request by m14815**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Clean up some insensitive wordings from docs to improve readability (This is a re-PR of PR #99548)
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/approve
for cmd/kubeadm

**Comment by fedebongio** [comment]
/assign @kevindelgado 
(for api-machinery)
/triage accepted

**Review by kevindelgado — COMMENTED** [review]
/lgtm

**Pull request closed without merging**
