### PR TITLE
[1.21][go1.16] Update to go1.16.6

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature
/area dependency release-eng release-eng/security security

#### What this PR does / why we need it:

Update Kubernetes to go1.16.6

Tracking issue: https://github.com/kubernetes/release/issues/2157

/assign @dims @liggitt @justaugustus 
cc: @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Kubernetes is now built with Golang 1.16.6
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cpanato** [comment]
/assign @dims @liggitt @justaugustus
cc: @kubernetes/release-engineering

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
