### PR TITLE
kubelet: Add a hidden flag to enable docker CRI integration for testing

### PR DESCRIPTION
**Pull request by yujuhong**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32903)

### CODE REVIEW

**Comment by Random-Liu** [comment]
LGTM. You should have tried locally, right?

**Comment by yujuhong** [comment]
> LGTM. You should have tried locally, right?

Yep, it seems fine. kubelet was up and running and was able to create containers.

**Comment by yujuhong** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by Random-Liu** [comment]
I tried and got:
```
 57 E0916 16:16:41.395057   71663 kuberuntime_container.go:293] getKubeletContainers failed: Error response from daemon: json: cannot unmarshal obj    ect into Go value of type []string
 58 E0916 16:16:41.395109   71663 kubelet.go:1114] Container garbage collection failed: Error response from daemon: json: cannot unmarshal object i    nto Go value of type []string
 59 panic: runtime error: index out of range
```
I'll look into it.

**Comment by Random-Liu** [comment]
Seems like `pkg/genericapiserver/openapi/zz_generated.openapi.go` needs to be generated.

**Comment by yujuhong** [comment]
> Seems like pkg/genericapiserver/openapi/zz_generated.openapi.go needs to be generated.

Will run the script and update the PR.

**Comment by Random-Liu** [comment]
LGTM

**Comment by Random-Liu** [comment]
@k8s-bot test this issue #IGNORE.

**Comment by Random-Liu** [comment]
@k8s-bot test this issue #IGNORE.

**Comment by Random-Liu** [comment]
@k8s-bot test this issue https://github.com/kubernetes/kubernetes/issues/31729.

**Comment by errordeveloper** [comment]
Great, looking forward to test this out!

**Comment by yujuhong** [comment]
@k8s-bot test this issue #31729.

**Comment by yujuhong** [comment]
@k8s-bot test this issue #32770.

**Pull request merged**
