### PR TITLE
Fix typo, old link for contributors

### PR DESCRIPTION
**Pull request by sungjunyoung**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
- Fix typo in comments on function `IsLikelyNotMountPoint`
- Fix old link to new link in pr template

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by poothia** [comment]
lgtm

**Review by nikhita — APPROVED** [review]
/lgtm
/ok-to-test

**Comment by nikhita** [comment]
/assign @castrojo @msau42 
for approval

**Pull request merged**
