### PR TITLE
Log the OS images used during GCP cluster creation

### PR DESCRIPTION
**Pull request by abgworrall**
/assign @fejta

### CODE REVIEW

**Comment by fejta** [comment]
/lgtm

Very nice!

**Comment by abgworrall** [comment]
Thanks, @fejta ! It seemed a bit clunky to me, but hey, it worked.

Do you know if this could be easily backported into 1.7, 1.6 and 1.5 ? I'd like to see this data on those branches, too.

**Comment by abgworrall** [comment]
Oh, I had a specific question, too; is `TestContext.OutputDir`end up being `artifacts`, the dir which contains `metadata.json` ? I'm hopeful I can persuade whatever reads & displays that file to also pick up my new `images.json` ...

**Pull request merged**
