### PR TITLE
Allow usining FakeOOMAdjuster in Kubelet

### PR DESCRIPTION
**Pull request by gmarek**
Required for #13731

@wojtek-t @yujuhong @fgrzadkowski

### CODE REVIEW

**Comment by yujuhong** [comment]
lgtm

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@gmarek - it seems that exactly the same test (cni.TestCNIPlugin) failed for the second time (I haven't heard about this test being flaky).
Can you please take a look?

**Comment by gmarek** [comment]
Works for me every time. I rebased and pushed the new version - maybe it'll help.

**Comment by gmarek** [comment]
It helped:)

**Pull request merged**
