### PR TITLE
the --enable-hostpath-provisioner option is deprecated 

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind deprecation

#### What this PR does / why we need it:

See https://github.com/kubernetes/kubernetes/issues/123804#issuecomment-1985508047

#### Which issue(s) this PR fixes:

Part of #123804

#### Does this PR introduce a user-facing change?

```release-note
kube-controller-manager: the --enable-hostpath-provisioner option is deprecated and will be removed in a future release
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sftim** [comment]
Changelog suggestion
```diff
-kube-controller-manager: the --enable-hostpath-provisioner option is deprecated and will be removed in a future release
+kube-controller-manager: deprecated the `--enable-hostpath-provisioner` command line flag; it will be removed in a future release.
```

**Comment by jsafrane** [comment]
/hold 

For KEP https://github.com/kubernetes/enhancements/pull/4548

**Pull request closed without merging**
