### PR TITLE
add healthz check feature

### LINKED ISSUE #52387: whether the kube-scheduler add healthz check feature?
**Is this a BUG REPORT or FEATURE REQUEST?**:

>
> /kind feature

**What happened**:
kube-controller-manager has default healthz check feature.  the code is:
```
func init() {
	healthz.DefaultHealthz()
}

```
and whether the kube-scheduler add healthz check feature?
**What you expected to happen**:
kube-scheduler add healthz check feature

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.0.583+dfd4dd876a6488", GitCommit:"dfd4dd876a6488ff6374afff5c8858a9a2481379", GitTreeState:"clean", BuildDate:"2017-09-13T06:13:07Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by jiulongzaitian**
Signed-off-by: zhangjie <zhangjie0619@yeah.net>

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #52387

**Special notes for your reviewer**:

**Release note**:

```release-note
   add healthz check feature
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
I think that we already expose healthz from scheduler. 
@jiulongzaitian Can you please double check that it's not the case?

@bsalamat ^^

**Comment by jiulongzaitian** [comment]
@wojtek-t I can not find healthz.DefaultHealthz()  in scheduler . Do you mean startHTTP func ? but it also exist in controller manager.

**Comment by wackxu** [comment]
The health check endpoint is already registered in https://github.com/kubernetes/kubernetes/blob/master/plugin/cmd/kube-scheduler/app/server.go#L160.
So we do not need add health check. Actually I think  healthz.DefaultHealthz() is redundant in controller-manage and I have open a PR #52406 to resolve it.

**Comment by wojtek-t** [comment]
@wackxu - thanks for finding it - that's what I though.

I'm closing this PR then.

**Comment by jiulongzaitian** [comment]
@wojtek-t @wackxu thank you

**Pull request closed without merging**
