### PR TITLE
Fix ordering of conversion methods so that it's deterministic

### PR DESCRIPTION
**Pull request by wojtek-t**
This bug was exposed by @thockin in #8552 

cc @thockin @lavalamp @smarterclayton

### CODE REVIEW

**Comment by thockin** [comment]
LGTM

**Comment by dchen1107** [comment]
@wojtek-t, you have to rebase to get this merged now. Sorry about this.

**Comment by thockin** [comment]
My #8552 depends on this one first.

**Comment by dchen1107** [comment]
@thockin, yes, I notice it. Thanks!

**Comment by wojtek-t** [comment]
Rebased.

**Comment by dchen1107** [comment]
Thanks will merge it once shippable is green.

**Comment by wojtek-t** [comment]
Shippable is green :)

**Pull request merged**
