### PR TITLE
vendor: Update elazarl/goproxy to fix e2e test with go1.8

### PR DESCRIPTION
**Pull request by mikkeloscar**
**What this PR does / why we need it**:

This updates the dependency `github.com/elazarl/goproxy` to include this fix https://github.com/elazarl/goproxy/commit/c4fc26588b6ef8af07a191fcb6476387bdd46711 which makes kubernetes e2e tests build with go1.8. It was crashing before as described in https://github.com/elazarl/goproxy/issues/188#issuecomment-281092250 and #38228

**Which issue this PR fixes**

This is part of the fix for #38228 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by colemickens** [comment]
@lavalamp Can you please LGTM this? This is making it really painful to run e2e tests in some environments.

**Comment by lavalamp** [comment]
/lgtm
/approve
/release-note-none

(chatting at me on slack is a better way to get my attention--I have too many github notifications to pay attention to.)

**Comment by mikkeloscar** [comment]
Flake on **Jenkins GCE e2e** #43072 (https://github.com/kubernetes/kubernetes/issues/43072#issuecomment-287681287)

**Comment by luxas** [comment]
@k8s-bot bazel test this
@k8s-bot cvm gce e2e test this

**Comment by nielsole** [comment]
Is there any chance that this fix will be backported e.g. for 1.6.4?

**Comment by mikkeloscar** [comment]
@nielsole I would not expect any of the go 1.8 related fixes to be backported to 1.6.*. There were a lot of changes needed which was included in 1.7, but hard to backport (see: #38228)

**Pull request merged**
