### PR TITLE
bump kube-openapi dep

### PR DESCRIPTION
**Pull request by lavalamp**
```release-note
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
I just realized that the hack/verify-generated*.sh files *don't use the --verify-only flag* for gengo-produced binaries. This is completely insane. The whole point of using gengo is that you don't have to do anything fancy to verify. :( :( :(

**Comment by lavalamp** [comment]
There's apparently two reasons we don't use --verify-only:
* it only verifies that expected files are present and doesn't verify that unexpected files are absent
* kube-openapi generates an intermediate file that we don't check in.

**Comment by lavalamp** [comment]
OK I've fixed a problem in kube-openapi, regenerated the violations list, and updated this PR, let's hope it passes tests.

**Comment by roycaihw** [comment]
>   it only verifies that expected files are present and doesn't verify that unexpected files are absent

Right. I had a PR around this problem for `codegen`: https://github.com/kubernetes/kubernetes/pull/63642. `hack/verify-codegen.sh` uses `--verify-only` and doesn't detect unexpected files. 

I prefer the way that [`hack/verify-openapi-spec.sh`](https://github.com/kubernetes/kubernetes/blob/9d6ea5b4a3ce89df98b73a529b8b0da164aa6af5/hack/verify-openapi-spec.sh#L33) does-- it's not using `--verfiy-only`, but moving existing files to a `_tmp` directory and regenerating everything. By comparing on directory level it's able to detect unexpected files. 

Note this "`_tmp` directory" way doesn't work well when your directory contains both manually written files and generated file (the `codegen` case #63642).

> The whole point of using gengo is that you don't have to do anything fancy to verify. :( :( :(

Given that gengo only operates on individual-file level but not directory level, it's hard to detect unexpected files :(

> OK I've fixed a problem in kube-openapi, regenerated the violations list, and updated this PR, let's hope it passes tests.

Thanks for working on this! My violations list change has blocked bumping this dependency for a long time... e.g. https://github.com/kubernetes/kubernetes/pull/68576#issuecomment-428717813

**Comment by roycaihw** [comment]
Please update staging godeps before merging

**Comment by lavalamp** [comment]
argh, running it now

**Comment by lavalamp** [comment]
Updated.

**Comment by roycaihw** [comment]
LGTM. Waiting for tests to be green before applying the label

**Pull request merged**
