### PR TITLE
Revert "kubemark: enable CRI for the hollow nodes"

### PR DESCRIPTION
**Pull request by yujuhong**
This reverts commit c89e9cdbf109c569bff06e5db8354402bd440ffd.

### CODE REVIEW

**Comment by yujuhong** [comment]
Copying my own https://github.com/kubernetes/kubernetes/issues/42709#issuecomment-284955055

We can't reproduce this in our own environment. I would ask that maybe we consider do one of the following:

- If the test doesn't flake frequently enough that it'd affect submit queue, we don't revert the PR so that we can properly debug it.
- Move kubemark-500 out of submit queue blocking for a day or two for proper debugging. The risk of a PR getting in and breaking kubemark 500 is pretty low (IMO) during code freeze.

**Comment by wojtek-t** [comment]
I'm against moving kubemark-500 out of blocking.

But since size of queue is now pretty small, I'm fine with having it hang with "do-not-merge" label - if we accumulate too long queue, we should just merge it.

**Comment by gmarek** [comment]
Last few runs have hollow-node logs, so we can unblock the queue now. We can repeat this experiment if needed.

**Comment by wojtek-t** [comment]
Agree - there are a bunch of failed runs with all logs there. I'm merging it manually now.

**Pull request merged**
