### PR TITLE
use dedent for create_quota.go

### PR DESCRIPTION
**Pull request by lojies**
use dedent for create_quota.go

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32174)

### CODE REVIEW

**Comment by AdoHe** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32174#-:-KR3cDq7aIAOzVdm3QVb:bnfp4nl)*

**Comment by brendandburns** [comment]
@deads2k @janetkuo 

Do we really want to suck in yet another dependency to do this?  The cognitive load and extra dependency really doesn't seem worth it to me.

I'm not strongly opposed, but I personally don't really see the win.

**Comment by deads2k** [comment]
> @deads2k @janetkuo
> 
> Do we really want to suck in yet another dependency to do this? The cognitive load and extra dependency really doesn't seem worth it to me.

As I recall, it was a request from thockin in https://github.com/kubernetes/kubernetes/pull/17609. I don't much care either way.

**Comment by brendandburns** [comment]
Ok, consensus seems to be in favor, who am I to stand in the way of progress.

LGTM

@k8s-bot ok to test

**Pull request merged**
