### PR TITLE
Update kubelet.go

### PR DESCRIPTION
**Pull request by RomanKrasavtsev**
Fix typo

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Fix typo

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note
NONE
```

### CODE REVIEW

**Comment by RomanKrasavtsev** [comment]
Hi @Random-Liu @dashpole @erekwaynecarr, I need your help :)

**Comment by dashpole** [comment]
don't worry about that test, it isn't required

**Comment by RomanKrasavtsev** [comment]
Hey @dashpole @Random-Liu, I would be very grateful if could you approve my PR. Thanks.

**Comment by RomanKrasavtsev** [comment]
ping @dashpole @Random-Liu

**Pull request closed without merging**
