### PR TITLE
Automated cherry pick of #61715: Increase cpu/mem thresholds for c-m in density test

### PR DESCRIPTION
**Pull request by shyamjvs**
Cherry pick of #61715 on release-1.10.

#61715: Increase cpu/mem thresholds for c-m in density test

```release-note
NONE
```

### CODE REVIEW

**Comment by shyamjvs** [comment]
This is basically to fix the flaky failures in our 1.10 100-node job (which is already fixed in 1.11).

**Comment by MaciekPytel** [comment]
Yay, less flakes :D Thanks!

**Pull request merged**
