### PR TITLE
PR #55183 follow up: Reinstate admission chain composition and ns test

### PR DESCRIPTION
**Pull request by jpbetz**
Addresses feedback to already merged https://github.com/kubernetes/kubernetes/pull/55183:

- https://github.com/kubernetes/kubernetes/pull/55183#discussion_r151152026
- https://github.com/kubernetes/kubernetes/pull/55183#discussion_r151152303

@kubernetes/sig-api-machinery-pr-reviews

```release-note
None
```

### CODE REVIEW

**Comment by deads2k** [comment]
@jpbetz thanks for putting this together.  Can you take a look at the patch @sttts built on top this here: https://github.com/kubernetes/kubernetes/pull/55938/files#diff-3261d858c5ff02eafa130fd670fe7d46R21 ?

**Comment by jpbetz** [comment]
Verify failing due to out-of-date openapi spec k8s version reference. It had 1.9, but it i now 1.10.  Rebased to pick up fix.

**Comment by sttts** [comment]
@jpbetz https://github.com/kubernetes/kubernetes/pull/55938 is green and ready to go.

**Comment by jpbetz** [comment]
Superseded by #55938

**Pull request closed without merging**
