### PR TITLE
Remove tolerate-unready-endpoints annotation

### PR DESCRIPTION
**Pull request by tossmilestone**
Signed-off-by: He Xiaoxi <tossmilestone@gmail.com>

#### What type of PR is this?

/kind deprecation

#### What this PR does / why we need it:

Remove `tolerate-unready-endpoints` annotation in Service deprecated from 1.11, use `Service.spec.publishNotReadyAddresses` instead.

#### Which issue(s) this PR fixes:

None

#### Does this PR introduce a user-facing change?

```release-note
Remove `tolerate-unready-endpoints` annotation in Service deprecated from 1.11, use `Service.spec.publishNotReadyAddresses` instead.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
it seems there are 2 operators still using it :upside_down_face: 

https://grep.app/search?q=TolerateUnreadyEndpointsAnnotation&case=true

should we open an issue on their repos to warn them?

/assign @thockin

**Comment by aojea** [comment]
hmm, this annotation is not working for endpoint slices, that is default and GA since v1.21.

The deprecation started in 1.13, so I think we should remove it to not cause more confusion, we had an incident in Openshift because of this :(
/lgtm

**Comment by tossmilestone** [comment]
@aojea the change will appear in the release note, and the users of the annotation should notice the change when upgrading k8s. So i think it's ok to remove the annotation.

**Comment by aojea** [comment]
> @aojea the change will appear in the release note, and the users of the annotation should notice the change when upgrading k8s. So i think it's ok to remove the annotation.

they will notice when they use 1.21 if they use kube-proxy, because endpoint slices doesn't recognize the label and things will fail ;) ... I had an internal bug because of this

**Comment by aojea** [comment]
seems that only one of the projects is active, I've opened an issue on their repo

https://github.com/nats-io/nats-operator/issues/339

**Comment by thockin** [comment]
Thanks @aojea - you did all the homework.

/approve

**Pull request merged**
