### PR TITLE
WIP - debug gc timing

### PR DESCRIPTION
**Pull request by jpbetz**

### CODE REVIEW

**Comment by jpbetz** [comment]
From the [controller manager logs](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/88297/pull-kubernetes-e2e-gce/1230052385993265154/artifacts/e2e-ab19c54dae-674b9-master/kube-master-configuration.log) of `pull-kubernetes-e2e-gce` runs, looks like the `GarbageCollector.Sync()` is holding the `gc.workerLock` for extended periods of time (15+ seconds) while calling `gc.resyncMonitors()` which in turn calls `graphBuilder.syncMonitors()` > `DeferredDiscoveryRESTMapper.KindFor` > `DeferredDiscoveryRESTMapper.getDelegate` > `GetAPIGroupResources`.

**Comment by lavalamp** [comment]
It seems like a correct fix for that is to keep the last known discovery response and just use it if possible? Are we blocking because the requested thingy is a brand new CRD and therefore we don't have any knowledge about it yet and really do need to wait for a discovery request to go through?

It does not make very much sense that SSA would make that path any better or worse.

**Comment by liggitt** [comment]
That is expected... when GC detects available API resources have changed, it blocks until it has resynced informers for the new resources.

What is not expected is long delays [outside of syncMonitors](https://github.com/kubernetes/kubernetes/issues/87668#issuecomment-584385565)

**Comment by liggitt** [comment]
> It seems like a correct fix for that is to keep the last known discovery response and just use it if possible?

We only block in cases where we have discovery has changed and we know we have new resources to set up informers for:

https://github.com/kubernetes/kubernetes/blob/d4c5637680184c0a2478e624f3db769660bcb088/pkg/controller/garbagecollector/garbagecollector.go#L175-L184

**Comment by lavalamp** [comment]
I'm not convinced pausing all workers is necessary in that case--we should be double-checking with GET/precondition before doing anything destructive. But in any case, that behavior isn't new and shouldn't be exacerbated by SSA. It *might* explain why the GC e2e tests are already close to the edge of being flaky, but it's probably not the thing pushing them over the edge.

**Comment by jpbetz** [comment]
The long delays outside of `sync.Monitors` are almost entirely due to the latency of `attemptToDeleteItem` > `getObject` > `gc.apiResource` > `gc.restMapper.RESTMapping` > `getDelegate` > `GetAPIGroupResources` (the latency of sync also funnels into `getDelegate` > `GetAPIGroupResources`)

Latency distribution of `attemptToDeleteItem` for all of `pull-kubernetes-e2e-gce`:

With server side apply at 0% (`DefaultTrackOnCreateProbability float32 = 0.0`):
```
5.05 -> 6.59: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇  48
        8.13: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇  25
        9.67: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇  39
       11.21: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇  41
       12.76: ▇▇▇▇▇▇▇▇▇▇▇  18
       14.30: ▇▇▇  6
       15.84: ▏  1
       17.38: ▇▇  4
       18.92: ▇▇  4
       20.46: ▇▇  4
```

With server side apply at 100% (`DefaultTrackOnCreateProbability float32 = 1.0`):

```
5.13 -> 7.44: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇  43
        9.76: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇  43
       12.08: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇  71
       14.39: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇  49
       16.71: ▇▇▇▇▇▇▇▇▇▇▇▇  29
       19.02: ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇  38
       21.34: ▇▇▇▇▇  13
       23.66: ▇▇▇  8
       25.97: ▇▇  5
       28.29: ▇▇  5
```

Roughly 35% more latency with server side apply enabled, and that's enough to exceed the e2e test timeouts more consistently.

**Comment by jpbetz** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/88382 to fix the discovery `memCacheClient` which is the main source of latency. I'll close this PR after I get a few more runs with it to see what the impact is to e2e test stability.

**Comment by jpbetz** [comment]
No garbage collector failures in last 2 runs. Trying a couple more

/test pull-kubernetes-e2e-gce

**Comment by jpbetz** [comment]
Still no GC errors. Retrying

/test pull-kubernetes-e2e-gce

**Pull request closed without merging**
