### PR TITLE
Automated cherry pick of #112129: dependencies: update to ginkgo v2.1.6 and gomega v1.20.1

### PR DESCRIPTION
**Pull request by pohly**
Cherry pick of #112129 on release-1.25.

#112129: dependencies: update to ginkgo v2.1.6 and gomega v1.20.1

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by pohly** [comment]
/release-note-none

As in https://github.com/kubernetes/kubernetes/pull/112129#issuecomment-1233127910.

**Comment by aojea** [comment]
I have doubts this qualifies for cherry-picking if is just for e2e logs verbosity https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#what-kind-of-prs-are-good-for-cherry-picks

Maybe based on the changelog fixes can be justified?

vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
vendor/github.com/onsi/gomega/CHANGELOG.md

**Comment by pohly** [comment]
I consider it a regression caused by the Ginkgo v2 migration that affects users of conformance testing.

We can of course also keep this open until people notice and complain :shrug:

**Comment by aojea** [comment]
> I consider it a regression caused by the Ginkgo v2 migration that affects users of conformance testing.

I've just run a conformance test and I can confirm this pollutes unnecessarily the output with lots (considerable number) of useless lines, and this can cause an issue on users/companies that try to certificate their products

I agree with pohly

/lgtm
/approve

**Comment by dims** [comment]
/approve

/assign @liggitt @thockin 
(for root OWNERS approval)

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
