### PR TITLE
Automated cherry pick of #64355: bump(github.com/evanphx/json-patch): 94e38aa1586e8a6c8a75770bddf5ff84…

### PR DESCRIPTION
**Pull request by wgliang**
Cherry pick of #64355 on release-1.10.

#64355: update package github.com/evanphx/json-patch

### CODE REVIEW

**Comment by wgliang** [comment]
@thockin 
how to check `pull-kubernetes-verify` test, it shows:

```
Checking for 'Godeps/' changes against '/master'
fatal: Not a valid object name /master

```
when i run ./hack/verify-godeps.sh

**Comment by MaciekPytel** [comment]
@wgliang The name of this PR says 'automated cherry-pick', but the name of the branch looks like it is actually manual?

**Comment by MaciekPytel** [comment]
It looks like @liggitt opened a cherry-pick of the same PR (#64446), which actually passes verify tests. Maybe we should close this one in favor of #64446?

@wgliang

**Comment by wgliang** [comment]
Ok, I'll close it.

**Pull request closed without merging**
