### PR TITLE
making some apiserver metrics stable

### LINKED ISSUE #105862: Proposed graduation of apiserver metrics from alpha to stable
### What would you like to be added?

I would like to propose the graduation of the following apiserver metrics from alpha to stable:

- [apiserver_response_sizes](https://github.com/kubernetes/kubernetes/blob/0d50c969c587c8a6c16e0962118305ac652c5a6b/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go#L118)
- [aggregator_unavailable_apiservice](https://github.com/kubernetes/kubernetes/blob/0d50c969c587c8a6c16e0962118305ac652c5a6b/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/metrics.go#L39)
- [admission_controller_admission_duration_seconds](https://github.com/kubernetes/kubernetes/blob/0d50c969c587c8a6c16e0962118305ac652c5a6b/staging/src/k8s.io/apiserver/pkg/admission/metrics/metrics.go#L236)
- [admission_step_admission_duration_seconds](https://github.com/kubernetes/kubernetes/blob/0d50c969c587c8a6c16e0962118305ac652c5a6b/staging/src/k8s.io/apiserver/pkg/admission/metrics/metrics.go#L236)
- [admission_webhook_admission_duration_seconds](https://github.com/kubernetes/kubernetes/blob/0d50c969c587c8a6c16e0962118305ac652c5a6b/staging/src/k8s.io/apiserver/pkg/admission/metrics/metrics.go#L236)
- [apiserver_current_inflight_requests](https://github.com/kubernetes/kubernetes/blob/0d50c969c587c8a6c16e0962118305ac652c5a6b/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go#L172)

### Why is this needed?

With the exception of the `aggregator_unavailable_apiservice` metric these metrics have been stable for 2 years. The `aggregator_unavailable_apiservice` metric has been stable for 12 months.

### PR DESCRIPTION
**Pull request by rezakrimi**
#### What type of PR is this?
/kind cleanup
/kind feature

#### Which issue(s) this PR fixes:

Fixes #105862 

#### Does this PR introduce a user-facing change?

```release-note
Graduating `controller_admission_duration_seconds`, `step_admission_duration_seconds`, `webhook_admission_duration_seconds`, `apiserver_current_inflight_requests` and `apiserver_response_sizes` metrics to stable. 
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by liggitt** [comment]
/approve
zero-diff promotion

**Pull request merged**
