### PR TITLE
[ADD] support for customize REDIS_MASTER_NAME

### PR DESCRIPTION
**Pull request by thuandt**
Support customize redis sentinel `master_name` instead `mymaster`

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/24786)

### CODE REVIEW

**Comment by thuandt** [comment]
I signed it!

**Comment by bgrant0607** [comment]
cc @kubernetes/examples

**Comment by viglesiasce** [comment]
@bgrant0607 who has access to push to kuberentes repo on Docker Hub?

This makes a change to the kubernetes/redis image which would need to be pushed as kubernetes/redis:v2 (and likely latest), then the pod/RC manifests updated in order to use the new image.

**Comment by jeffmendoza** [comment]
I can push to `gcr.io/google-samples/redis` if that makes sense

**Comment by thuandt** [comment]
@jeffmendoza When I try deploy multi redis-sentinel cluster, own app need connect to 2 redis-sentinel cluster, I want different `master_name` with each cluster instead only `mymaster`. That's why we have this PR.

**Comment by bgrant0607** [comment]
@viglesiasce @jeffmendoza I think @fejta can push to gcr.io/google_containers(?), which is where most of the other examples seem to live.

**Comment by fejta** [comment]
Please assign this to me after merging and I can create and push the image.

**Comment by jeffmendoza** [comment]
This example moved to examples/storage/redis

**Pull request closed without merging**
