### PR TITLE
Remove NONE in CHANGELOG-1.9

### PR DESCRIPTION
**Pull request by yuexiao-wang**
Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

**What this PR does / why we need it**:
There should be not NONE in CHANGELOG and remove these NONE

**Which issue this PR fixes** : fixes #

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by yuexiao-wang** [comment]
@verult @abgworrall PTAL

**Comment by verult** [comment]
My PR can be removed from the changelog as it only affects e2e tests.

**Comment by yuexiao-wang** [comment]
I am waiting for the result from you. If need to remove the PR from CHANGELOG, I would like to do it

**Comment by xiangpengzhao** [comment]
I think the three places you touch can be removed directly.
BTW, this PR don't need a release note :)
/release-note-none

**Comment by xiangpengzhao** [comment]
The bot doesn't allow me to label `release-note-none`. @yuexiao-wang can you modify the PR body?

**Comment by yuexiao-wang** [comment]
see https://github.com/kubernetes/kubernetes/pull/55302

**Pull request closed without merging**
