### PR TITLE
waitgroup  is threadsafe , Let's Remove unnecessary code base.

### PR DESCRIPTION
**Pull request by jjmengze**
#### What type of PR is this?
/kind deprecation
/kind clean

#### What this PR does / why we need it:
waitgroup  is threadsafe  , it seems to  me that reducing  unnecessary code base  is awesome.

#### Which issue(s) this PR fixes:
none

#### Special notes for your reviewer:
none 

#### Does this PR introduce a user-facing change?
```release-note
"NONE"
```
#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
pretty sure this is still used

/ok-to-test

**Comment by jjmengze** [comment]
@deads2k  I  am very sorry for this error when I notice that it still has some dependencies.

Well, modify these dependencies to wait package? because the waitgroup add and wait function of go standard library is an atomic operation.

**Comment by deads2k** [comment]
/hold

The contract for this method is not actually a waitgroup.  I'm open a rename and a doc clarification, but we cannot remove this.  It is used to prevent future requests to a kube-apiserver.

**Comment by deads2k** [comment]
> The contract for this method is not actually a waitgroup. I'm open a rename and a doc clarification, but we cannot remove this. It is used to prevent future requests to a kube-apiserver.

this looks correct. It was a tricky name.  We cannot remove this.

**Pull request closed without merging**
