### PR TITLE
Fixing heapster memory requirements.

### PR DESCRIPTION
**Pull request by Q-Lee**
[Analytics]()

### CODE REVIEW

**Comment by Q-Lee** [comment]
@zmerlynn - this fixes the heapster memory usage bug you found

**Comment by davidopp** [comment]
cc/ @vishh @fgrzadkowski @mwielgus @piosz

**Comment by wojtek-t** [comment]
Thanks for the fix @Q-Lee 

I'm oncall today so I'm manually merging it to unblock some tests.

**Comment by andyzheng0831** [comment]
@roberthbailey @Q-Lee @wojtek-t @zmerlynn please fix the breakage to GCI (in cluster/gce/gci/configure-helper.sh). Adding, removing, or renaming a variable in kube-system manifest requires according changes in cluster/gce/gci/configure-helper.sh. Both GCE and GKE CI tests capture the breakage after this PR was merged

**Comment by wojtek-t** [comment]
@andyzheng0831 - sorry for the problem. Looking now.

**Comment by wojtek-t** [comment]
#26159 should hopefully fix the problem

**Comment by wojtek-t** [comment]
Yeah - seems to be fixed now.

**Pull request merged**
