### PR TITLE
Update PV/PVC YAML tempalte to use `storageClassName`.

### LINKED ISSUE #51435: Update PV/PVC YAML tempalte to use `storageClassName`
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

/kind bug

> /kind feature

**What happened**:
In the Kubernetes 1.6 release, dynamic provisioning has been promoted to stable (having entered beta in 1.4). In 1.6, `StorageClassName` attribute has been added to `PersistentVolume` and `PersistentVolumeClaim` objects and should be used instead of annotation `volume.beta.kubernetes.io/storage-class`.

**What you expected to happen**:
We should now update the `volume.beta.kubernetes.io/storage-class` to use `StorageClassName`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/cc @kubernetes/sig-storage-bugs

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #51435

**Special notes for your reviewer**:

**Release note**:

```release-note
Use `StorageClassName` for example pv/pvc templates.
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
@gyliu513 FYI: dup of https://github.com/kubernetes/kubernetes/pull/51310 :)

**Comment by gyliu513** [comment]
Already being handled in https://github.com/kubernetes/kubernetes/pull/51310 by @xiangpengzhao

**Comment by xiangpengzhao** [comment]
@gyliu513 I'm so sorry for not opening issues when I worked on these replacements and removing of storage class annotations :)

**Comment by gyliu513** [comment]
No worry, I opened the issues for you ;-) @xiangpengzhao

**Pull request closed without merging**
