### PR TITLE
Implement ReplicaSet registry.

### PR DESCRIPTION
**Pull request by madhusudancs**
Only the last commit needs review. This PR is based on other PRs which are in review separately, unfortunately there is no easy way to do diff against PRs.

This is part of an ongoing work to create ReplicaSet and move Deployments to the new selector format.

### CODE REVIEW

**Comment by bgrant0607** [comment]
Similar to #19747, ensure there are comments in both the RC code and here that indicate the two implementations should be kept in sync.

**Comment by mikedanese** [comment]
5th commit LGTM. Code is a copy paste of replication controller and I can't find anything that's obviously wrong with it.

**Comment by madhusudancs** [comment]
> Similar to #19747, ensure there are comments in both the RC code and here that indicate the two implementations should be kept in sync.

Done.

@bgrant0607 @mikedanese PTAL.

**Comment by mikedanese** [comment]
I'm not applying lgtm label since this PR depends on other PRs.

**Comment by bgrant0607** [comment]
Submit queue is finally moving again. I believe the PRs that this depends on have been merged. Please rebase.

**Comment by madhusudancs** [comment]
@bgrant0607 This depends on Scale. I will rebase this PR once Scale related changes are reviewed and merged.

**Comment by bgrant0607** [comment]
I visually compared the files to the RC files. 

LGTM

**Comment by bgrant0607** [comment]
@lavalamp Could we please get a manual merge on this?

**Comment by lavalamp** [comment]
OK, just waiting for tests to pass.

**Pull request merged**
