### PR TITLE
fix typo of Node Allocatable Cgroup

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
fix the than not that and add some comment
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
/assign @Random-Liu @derekwaynecarr 
for approval :)

**Comment by jianglingxia** [comment]
PTAL @random-liu
thanks very much!

**Comment by tengqm** [comment]
@jianglingxia I'm very concerned with patches like this.
Each PR will trigger at least:

- Emails to be sent to all developers who has a subscription
- Someone has to spend time scanning the change to give it a ok-to-test
- Someone developer or team to be notified for review
- All CI jobs have to run to verify that the code doesn't break anyone
- Sometimes the gate fails, and a "/retest" is triggered to run all of them over again
- Someone to approve
- The change may cause some conflicts with other PRs which have to be rebased
...

Please, please think twice before submitting such a PR which just fix a word in the comment.
That comment is not affecting end users. It is not even causing a big problem for developers.

**Pull request closed without merging**
