### PR TITLE
Tune the error messages in scheduler cache 

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

#### What type of PR is this?
/kind cleanup
/sig scheduling

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by sanposhiho — APPROVED** [review]
Looking good.
/lgtm

**Review by SataQiu — APPROVED** [review]
/lgtm

**Comment by kerthcet** [comment]
/assign @ahg-g 
for approval

**Comment by ahg-g** [comment]
/lgtm
/approve

Thanks, this is easier to read as well.

**Pull request merged**
