### PR TITLE
Bundle the SyncResults under one lock in ReasonCache#Update

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
In ReasonCache#Update, we obtain and release lock for each SyncResult addition / removal.

This PR bundles all the SyncResult additions / removals under one lock.

```release-note
NONE
```

### CODE REVIEW

**Comment by tedyu** [comment]
cc @yujuhong @dchen1107

**Comment by tedyu** [comment]
ping @yifan-gu @dashpole for review

**Comment by tedyu** [comment]
ping @yujuhong for review

**Comment by tedyu** [comment]
ping @yifan-gu @dashpole for review

**Comment by dashpole** [comment]
Can you say a bit more about the problem this is solving?  Are you seeing lock contention or some other issue here?

**Pull request closed without merging**
