### PR TITLE
Move deployment example to docs/user-guide

### PR DESCRIPTION
**Pull request by janetkuo**
https://github.com/kubernetes/kubernetes/pull/20928#issuecomment-182146812

cc @bgrant0607 @kubernetes/goog-ux

### CODE REVIEW

**Comment by nikhiljindal** [comment]
examples_test also tests the yaml file, so you need to update that.

**Comment by janetkuo** [comment]
@nikhiljindal PTAL. Thanks!

**Comment by bgrant0607** [comment]
LGTM, but when we update user-guide/deployments.md, we should make the yaml file consistent with at least one of the examples in the doc.

**Comment by janetkuo** [comment]
@k8s-bot e2e test this issue: #18963

**Comment by bgrant0607** [comment]
This could probably move to hack/testdata, also, if it's just intended to be a test-cmd.sh input.

**Pull request merged**
