### PR TITLE
Use upgraded container-vm by default on worker nodes for GCE k8s clusters

### PR DESCRIPTION
**Pull request by vishh**
For https://github.com/kubernetes/kubernetes/issues/25276
Depends on https://github.com/kubernetes/test-infra/pull/417

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31023)

### CODE REVIEW

**Comment by vishh** [comment]
cc @dchen1107

**Comment by vishh** [comment]
cc @pwittrock

**Comment by dchen1107** [comment]
I want to make sure all of us on the same page:

* GKE is not going to switch to GCI as default within 1.4 time frame.
* Separate PR kubernetes/test-infra#417 is going to explicitly switch existing Jenkins job to debian based containervm image. That one has to be merged first.
* Beyond that PR, I want separate PR(s) to clone the missing kubernetes-gce-e2e-soak, kubernetes-gce-e2e-scalability, probably also kubernetes-gce-e2e-upgrade, and kubernetes-gce-e2e-features jenkins jobs (listed by me in https://github.com/kubernetes/kubernetes/issues/25276) landed first. 
* If all above are passed, we can switch GCE default to GCI.

**Comment by vishh** [comment]
@dchen1107 https://github.com/kubernetes/test-infra/pull/420 is the PR that should enable most of those critical tests. Over the next week, I hope to get to complete test parity.

**Comment by vishh** [comment]
All critical tests have been added at this stage. Let's wait for at-least a day to get enough test data. With that, I'm hoping that we can make an informed decision on the impact of this change. This might push this PR beyond the freeze date. Apologies!

**Comment by dchen1107** [comment]
We are holding the PR for testing results.

**Comment by vishh** [comment]
All critical tests excepting GKE ones are either passing or are not more
flaky than container-vm ones.

https://github.com/kubernetes/kubernetes/pull/31330 is out to fix the
GKE-GCI tests.

**Comment by vishh** [comment]
Update: The GKE tests are running now. Waiting for a couple of runs to gather some concrete data.

**Comment by vishh** [comment]
Update: https://github.com/kubernetes/kubernetes/issues/31456 is the only major blockers. All other tests are either passing or are being fixed.

**Comment by vishh** [comment]
One more issue to track - https://github.com/kubernetes/kubernetes/issues/31465

**Comment by dchen1107** [comment]
@vishh and I went over all critical builds including GCE & GKE, and most of tests are passed. Several issues were filed separately, and we are going to address them one-by-one. I am going to unblock this pr for now. 

cc/ @pwittrock, the release czar for 1.4.

**Comment by dchen1107** [comment]
LGTM

**Comment by vishh** [comment]
Thanks @dchen1104 and @pwittrock

**Comment by owenhaynes** [comment]
Does this not break GlusterFS, CephFS and possibly other Volumes from ever working?

**Comment by vishh** [comment]
@owenhaynes This PR only changes the default for now. It will still be possible to use the old version of container-vm and one can install gluster or ceph packages. I hope that containerized volume mounters will be ready for production before the old container-vm will be deprecated.

**Comment by caseydavenport** [comment]
Please see https://github.com/kubernetes/kubernetes/pull/32151#issuecomment-246544577

This PR broke CNI on GCE deployments.  We either need to get the above PR merged and added to the v1.4 milestone, or revert this change.

**Comment by lxpollitt** [comment]
cc @thockin

**Comment by thockin** [comment]
@pwittrock

**Comment by pwittrock** [comment]
ACK.  @dchen1107  @vishh  Please file an issue for the 1.4 milestone and come up with a resolution.  We need the resolution merged into 1.4 by Wednesday and then QA'ed manually on the beta build.

**Comment by thockin** [comment]
PR to set the flag is LGTM'ed, but calico is still broken

**Comment by vishh** [comment]
@thockin is there an issue for Calico stuff?

**Comment by caseydavenport** [comment]
@vishh - Will raise one now and report back

**Comment by caseydavenport** [comment]
@vishh https://github.com/kubernetes/kubernetes/issues/32625

**Comment by spiffxp** [comment]
@vishh @dchen1107 this PR has a release-note-action-required label on it, but I can't tell what the action is, CHANGELOG.md only has the PR title in it

can you please clarify what the action required is?

**Comment by vishh** [comment]
@spiffxp This PR got reverted. Updated release-note label.

**Pull request merged**
