### PR TITLE
support updating etcd ttl

### PR DESCRIPTION
**Pull request by tdaajames**
Signed-off-by: Wang Yufei <tdaajames@163.com>

**What this PR does / why we need it**:
In some situation we want to update the ttl of etcd key not just the value, so we update the ttl when it's not zero.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```
None
```

### CODE REVIEW

**Comment by deads2k** [comment]
I'm not in favor of changing this semantic one day before freeze.

**Comment by tdaajames** [comment]
CLA signed

**Comment by tdaajames** [comment]
Release notes none

**Comment by lavalamp** [comment]
I'm not in favor of exposing the TTL any more than it already is. Especially given the way TTL works in etcd3.

**Pull request closed without merging**
