### PR TITLE
Add monit support for restarting etcd to the master.

### LINKED ISSUE #3852: Automatically restart etcd
We don't currently automatically restart etcd.  We should.

### PR DESCRIPTION
**Pull request by brendandburns**
Closes #3852

### CODE REVIEW

**Comment by thockin** [comment]
Dawn was proposing to run etcd as a Docker container - thoughts?

**Comment by brendandburns** [comment]
My thought is stop the bleeding.  Rather than hoist this into a container as a one-off (which has it's own potential complexity [network overhead, configuration problems, etc]

Let's get this in.  If we rip it out in 2 days, as we move everything into a Pod, great.  But in the interim, we'll restart etcd.

**Comment by thockin** [comment]
LGTM

who restarts monit?

**Comment by brendandburns** [comment]
It's intended to be super-simple...

**Comment by thockin** [comment]
Even simple things get killed when the system goes OOM.

No need to fix it now, but our final answer should be a bit more guaranteed.

**Pull request merged**
