### PR TITLE
Process GCE ILB services with the v1 annotation in the service controller

### PR DESCRIPTION
**Pull request by prameshj**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR adds logic for the service controller/gce controller to process ILB services with the v1 finalizer. This is to cover a corner case where the forwarding rule got deleted for a v1 ILB. Currently, if the finalizer list contains v2 finalizer, the service controller will skip processing. Instead, it should process services that have V1 finalizer set.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by freehan — APPROVED** [review]
/lgtm
/approve

**Review by andrewsykim — COMMENTED** [review]
Deferring full review to other folks, but it's clear to me that this is a bug

/approve

**Pull request merged**
