### PR TITLE
Promote GMSA support for Windows to GA

### PR DESCRIPTION
**Pull request by ddebroy**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test

/kind feature

> /kind flake

**What this PR does / why we need it**:
Graduates GMSA support in Windows to GA/stable

**Which issue(s) this PR fixes**:
Fixes # https://github.com/kubernetes/enhancements/issues/689

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
Docs: https://github.com/kubernetes/website/pull/19349
KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-windows/20181221-windows-group-managed-service-accounts-for-container-identity.md
```

### CODE REVIEW

**Comment by ddebroy** [comment]
cc @michmike @wk8

**Comment by ddebroy** [comment]
The API review was completed as part of the feature moving through Alpha/Beta phases. The API review aspect in this PR is mainly around removal of the feature flag for GA.

**Review by michmike — APPROVED** [review]
/lgtm
/approve

**Comment by michmike** [comment]
@liggitt can you please take a look and approve? thanks!

**Comment by liggitt** [comment]
mechanics of the API change and feature gate change lgtm. does the corresponding e2e test need the feature tag removed so it runs unconditionally?

**Comment by JeremyWx** [comment]
@liggitt we are working to address your comments.  Will let you know ASAP.

**Comment by ddebroy** [comment]
Removed the conditional feature flags for the tests.

**Comment by JeremyWx** [comment]
@liggitt PR has been updated.  Tests can be found here:  https://testgrid.k8s.io/sig-windows#aks-engine-azure-windows-master-staging&include-filter-by-regex=GMSA&width=20

**Comment by liggitt** [comment]
thanks

/lgtm
/approve

**Pull request merged**
