### PR TITLE
Unify generic proxy code in apimachinery

### PR DESCRIPTION
**Pull request by smarterclayton**
Make the utility package truly generic, consolidate all generic proxy in
apimachinery.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Prereq for https://github.com/kubernetes/kubernetes/issues/32026

**Comment by smarterclayton** [comment]
@kubernetes/sig-api-machinery-pr-reviews @kubernetes/sig-api-machinery-pr-reviews the proxy needs to be usable from kubectl to solve #32026

**Comment by sttts** [comment]
@smarterclayton unit tests failed. You really want this: https://github.com/kubernetes/kubernetes/pull/48683

**Pull request merged**
