### PR TITLE
fix init container test which is broken in the version skew suites

### PR DESCRIPTION
**Pull request by mikedanese**
@erictune @dchen1107 @pwittrock

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33340)

### CODE REVIEW

**Comment by erictune** [comment]
thanks @mikedanese you are super fast.

**Comment by mikedanese** [comment]
@k8s-cherrypick-bot this isn't a cherry-pick this is a change for only the release branch that should not be in master.

**Comment by erictune** [comment]
Maybe hold off on this till we agree on what is happening in #33055

**Comment by mikedanese** [comment]
@k8s-bot please e2e test this for me.

**Comment by mikedanese** [comment]
@k8s-bot please kubemark test this for me.

**Comment by mikedanese** [comment]
@erictune Do we still want this?

**Comment by erictune** [comment]
I'd say abandon this PR.  If you are testing a patch against 1.3, you want to run this test against your cluster that has 1.3 master and 1.3 kubelets.

The problem, IIUC, it that our upgrade testing procedure assumes that the 1.3 test should pass against a skewed cluster (1.4 master and 1.3 kubelet).  That is usually the case, but in the case of this feature, we've decided not to provide that property.  So, the correct fix is probably to skip this test when we are doing an upgrade test.  I'll figure out how to do that.

**Comment by mikedanese** [comment]
Ok.

**Pull request closed without merging**
