### PR TITLE
add a return to recordToSink to try and prevent a race

### LINKED ISSUE #55069: pkg/kubelet/config TestInvalidPodFiltered flake
```
E1103 17:16:02.482172   13603 event.go:194] Unable to construct event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"", Namespace:"", Name:"", UID:"", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"", Message:"", Source:v1.EventSource{Component:"", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Count:0, Type:""}': 'request construction error: '<nil>'' (will not retry!)
```
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/54523/pull-kubernetes-unit/62637/

@kubernetes/sig-node-test-failures 
/kind flake

### PR DESCRIPTION
**Pull request by rphillips**
**What this PR does / why we need it**: Issue #55069 has a race and a flaky test. It appears the code is missing a return on an error path.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #55069

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by anfernee** [comment]
not sure i can do this. but /lgtm

**Comment by caesarxuchao** [comment]
Thanks for the fix. But I don't understand why the missing return will lead to race?

**Comment by caesarxuchao** [comment]
@euank

**Comment by rphillips** [comment]
@caesarxuchao If there is an error condition with EventCorrelate, then the error is logged but the code continues.

**Comment by caesarxuchao** [comment]
I understand that part, and I agree that adding a `return` seems reasonable, but I still don't understand why it will lead to a race

**Comment by rphillips** [comment]
The initial issue has a flaky test... I think the error may be thrown and the function falls through to a recordEvent infinite loop. I think it could be described as a race with the e2e tests, because it falls through or at the minimum a logic error that propagates to the tests.

**Comment by caesarxuchao** [comment]
Actually the original code is correct. If the `EventCorrelate()` fails, we want to record the event, though in the risk of creating large amounts of events.

Also, this doesn't fix https://github.com/kubernetes/kubernetes/issues/55069. The test that introduces the [RequestConstructionError](https://github.com/kubernetes/kubernetes/blob/2a71ed2141b6b2ea1d41b4c3e08eb10a358d4760/staging/src/k8s.io/client-go/tools/record/event_test.go#L394) won't hit the error path in this PR.

**Comment by caesarxuchao** [comment]
I'm going to close this PR. Please feel free to reopen it if you find my previous comment wrong.

**Pull request closed without merging**
