### PR TITLE
Touch an empty file to trigger PR tests on release-1.6

### PR DESCRIPTION
**Pull request by ixdy**
/test all

#53017

### CODE REVIEW

**Comment by yujuhong** [comment]
Hm....why do we skip pull-kubernetes-bazel-test for presubmit test in 1.6?

**Comment by BenTheElder** [comment]
@yujuhong, bazel was broken for 1.6 for a while, we need to set up things to be pinned to build with bazel 0.5.2, we have plans to do this. eg https://github.com/kubernetes/test-infra/issues/4754

**Comment by krzyzacy** [comment]
```
I1009 21:06:12.867] push-build.sh: BEGIN main on 5c48d4ca-ad33-11e7-a40f-0a580a6c0010 Mon Oct  9 21:06:12 UTC 2017
I1009 21:06:12.867] 
I1009 21:06:14.710] Unable to get latest version from build tree!
```

**Comment by ixdy** [comment]
release-1.6 never got the version stamping patches, I believe. it's pretty old.

**Comment by ixdy** [comment]
I don't think gce-bazel is even supposed to work on 1.6.

**Comment by enisoc** [comment]
Closing to keep my queue clean. Feel free to reopen if you're still using this.

**Comment by krzyzacy** [comment]
/reopen
(make sure https://github.com/kubernetes/test-infra/pull/5726 still works)

**Pull request closed without merging**
