### PR TITLE
kubeadm: refactor and cleanup component config tests

### PR DESCRIPTION
**Pull request by rosti**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

This change has a couple of parts (in separate commits):
1. It cleans up, deduplicates, and allows for further expansion unit tests in the `componentconfigs` package. In addition to that, reliance on kube-proxy's and kubelet's component configs is greatly reduced by replacing them in most places with `ClusterConfiguration`.

2. Last remnants of the fuzzer replacement tests are removed. With that folks who add new fields to kubelet's or kube-proxy's component configs no longer have to update kubeadm as well.

**Which issue(s) this PR fixes**:

Fixes none

**Special notes for your reviewer**:
This change depends on:
- #91980
- #88124 

But it's not formally part of the effort around the component configs KEP. It's just a cleanup.
Also, take a look at the last 2 commits only. The rest are from the aforementioned PRs.

/cc @kubernetes/sig-cluster-lifecycle-pr-reviews
/area kubeadm
/priority important-longterm
/assign @fabriziopandini @neolit123

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
> https://github.com/kubernetes/kubernetes/pull/90980

this might be the wrong PR?

**Comment by rosti** [comment]
> > #90980
> 
> this might be the wrong PR?

Ooops, yes. It's #91980 . So we can say it's an off by a 1000 error :)

**Comment by neolit123** [comment]
@rosti #91980 and #88124 merged.

**Comment by rosti** [comment]
@neolit123 rebased the PR.

**Pull request merged**
