### PR TITLE
pin golint in image

### PR DESCRIPTION
**Pull request by jessfraz**
updates https://github.com/kubernetes/kubernetes/issues/37254 for release-1.4

pins golint on the release branch

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37710)

**Comment by jessfraz** [comment]
testing I indeed picked the correct golint sha

**Comment by jessfraz** [comment]
we need https://github.com/kubernetes/test-infra/pull/1239 for this to work

**Comment by jessfraz** [comment]
@k8s-bot verify test this

**Comment by jessfraz** [comment]
merging all green

**Pull request merged**
