### PR TITLE
Automated cherry pick of #15475

### PR DESCRIPTION
**Pull request by bprashanth**
Cherry pick of #15475 on release-1.1.

### CODE REVIEW

**Comment by bprashanth** [comment]
For https://github.com/kubernetes/kubernetes/issues/20503

**Comment by bprashanth** [comment]
@jijun2 askin on google-bots behest (https://github.com/kubernetes/kubernetes/pull/20534#issuecomment-178964412), are you ok with cherrypicking your unittest fix to the 1.1 branch?

**Comment by ixdy** [comment]
Should probably cherry-pick #20111 too.

**Comment by bprashanth** [comment]
@ixdy that doesn't rebase cleanly. Can i get this one and send a follow up pr for that? (since I expect using hardcoded paths to be the main source of flake)

**Comment by ixdy** [comment]
Should we cherry-pick this to 1.1? @ihmccreery @jlowdermilk

**Comment by jlowdermilk** [comment]
If it will fix cni_test flakes we've seen on the 1.1 branch, I'd say it's worth cherrypicking. Changes are all test code, so should be very low risk.

**Comment by jlowdermilk** [comment]
@k8s-bot ok to test

**Comment by bprashanth** [comment]
@k8s-bot test this github issue #15493

**Comment by ixdy** [comment]
LGTM

**Comment by bprashanth** [comment]
How do we handle the cla complaint? I cc'd original author @jijun2 in https://github.com/kubernetes/kubernetes/pull/20534#issuecomment-178965221 but I think he's unavailable. Safe to ignore?

**Comment by ixdy** [comment]
The original PR (#15475) shows @jijun2 accepting the CLA, so I think we're OK.

**Comment by bprashanth** [comment]
So just hand merge? since sq won't pick it up

**Comment by ixdy** [comment]
SQ should pick this up eventually.

**Comment by bprashanth** [comment]
ah, cla:human-approved. Missed that.

**Pull request merged**
