### PR TITLE
fix typo in build/common.sh

### PR DESCRIPTION
**Pull request by StevenYCChou**
**What this PR does / why we need it**:
It fixes the typo in comments in `build/common.sh`:
- backgound -> background
- stoped -> stopped

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by xiangpengzhao — APPROVED** [review]
Good catch :)

**Comment by StevenYCChou** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by StevenYCChou** [comment]
rebased from master.

**Comment by ixdy** [comment]
@k8s-bot ok to test
/lgtm

**Pull request merged**
