### PR TITLE
Fix race in RetryWatcher's unit tests

### PR DESCRIPTION
**Pull request by tnozicka**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fix for https://github.com/kubernetes/kubernetes/issues/56876

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cc @liggitt @dims @nikhita

### CODE REVIEW

**Comment by dims** [comment]
/priority critical-urgent
/assign @liggitt
/lgtm

Jordan, we need this for the publishing-bot to start working again

**Comment by nikhita** [comment]
Fyi I updated the "Fixes #xxxx" line to "Fix for #xxxx" because the publishing bot issue should only be closed/reopened by the bot, or the bot gets confused.

**Comment by nikhita** [comment]
@tnozicka also thanks for the quick fix!! :)

**Pull request merged**
