### PR TITLE
Add doc on setting proxy while building kubernetes in a container

### LINKED ISSUE #5358: Add more detailed settings in the doc on how to build kubernetes
I was tring to build kubernetes following /kubernetes/build/README.md. But failed for some times. I looked into the error and found it's because I'm behind a proxy. Then I edited the dockerfile under build/build-image/ folder, added some proxy settings into it and solved the problem.

Though it may not be a problem for experienced guys. Would it be better for the beginners to describe these detaied settings in the document? Can I add the proxy settings I found into the doc?

I'm new to kubernetes and need your opinion.

### PR DESCRIPTION
**Pull request by hurf**
fixes #5358

### CODE REVIEW

**Comment by gmarek** [comment]
LGTM. Please squash commits.

**Comment by hurf** [comment]
Sorry, also due to the proxy problem(git upload is forbidden), I made this change by online editor and don't know how to reduce the commits by web. Maybe I can try it later by git client on another machine.

**Comment by gmarek** [comment]
Sure. Currently merges are allowed only during US West Coast work hours, so no hurry.

**Comment by satnam6502** [comment]
@hurf : let me know if you want help with the squash issue. For example, I could check out your PR into my clone, squash,  push it to my repo and then create another PR. However, it would be much better if you could squash the two commits in this PR into one, thank you kindly.

**Comment by hurf** [comment]
Yes I do need help about the squash issue.
I used `git rebase -i HEAD~2` in my repo, and changed `pick` to  `squash` before commit `c584209` and `c3d377f`, then I used `git push`. I didn't notice why `8c133eb` is included in the commit.
What should I do now? How can I fix this?

**Comment by hurf** [comment]
I think I've work it out:-)

**Comment by gmarek** [comment]
When you do a rebase, you can pick 'reword' (if I recall correctly) to change the commit message. When squashing you can use 'fixup' instead of 'squash' to drop commit messages of subsequent commits instead of appending them.

**Comment by gmarek** [comment]
@hurf - do you want to fix the comment, just for practice, or should I merge this PR?

**Comment by hurf** [comment]
@gmarek - I'd like to fix this. Last two days I was on a business trip and didn't have time to. I'll do it in two hours after the current meeting I'm in.

**Comment by gmarek** [comment]
Sure. I just wasn't sure if you want to do it. If you'll run into any problems catch me, or someone else on IRC.

**Pull request merged**
