### PR TITLE
remove tpr api access

### PR DESCRIPTION
**Pull request by deads2k**
xref https://github.com/kubernetes/kubernetes/issues/48152

TPR tentacles go pretty deep. This gets us started by removing API access and we'll move down from there.

@kubernetes/sig-api-machinery-misc 
@ironcladlou this should free up the GC implementation since TPRs will no longer be present and failing.

```release-note
The deprecated ThirdPartyResource (TPR) API has been removed. To avoid losing your TPR data, you must [migrate to CustomResourceDefinition](https://kubernetes.io/docs/tasks/access-kubernetes-api/migrate-third-party-resource/) before upgrading.
```

### CODE REVIEW

**Comment by enisoc** [comment]
LGTM but can we wait until next week to merge it? One of our PMs pointed out to me that the 1.7 announcement will be the first time a lot of people hear about the deprecation. A couple more days without any major concerns being raised should give us more confidence that we won't cause significant pain for users by removing it in 1.8.

**Comment by deads2k** [comment]
> LGTM but can we wait until next week to merge it?

Sure.  The bad behavior of TPRs and finalizers is blocking generic GC for discovered resources, but waiting until next week won't make or break it.

**Comment by deads2k** [comment]
just generated changes in `api`

**Comment by sttts** [comment]
lgtm

**Comment by deads2k** [comment]
> LGTM but can we wait until next week to merge it?

Issue has been open over a week.  Going ahead with this now.

**Pull request merged**
