### PR TITLE
make env variable parsing more robust

### LINKED ISSUE #18964: kubectl run --env parsing naive
I'm running application with several env variables. One of them has a key ending with ==. Another variable has a comma separated list of email addresses. While perfectly valid on *nix and windows, we can't pass these values into Kubernetes run command. It fails with "error: invalid env:"

Example command:
`kubectl run MyApp --env="THIS_ENV=isOK" --env="HAS_COMMAS=foo,bar" --env="HAS_EQUALS=jJnro54iUu75xNy==" `

The parsing in https://github.com/kubernetes/kubernetes/blob/51e8c2e5f8075b6a200f3fb4e06446cda27e2c4e/pkg/kubectl/run.go#L593 should be more robust

### PR DESCRIPTION
**Pull request by mqliang**
fix https://github.com/kubernetes/kubernetes/issues/18964#event-497692443

### CODE REVIEW

**Comment by mqliang** [comment]
@k8s-bot unit test this please

**Comment by brendandburns** [comment]
LGTM, thanks for the PR!

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by mqliang** [comment]
@k8s-bot test this please.

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by gmarek** [comment]
Failure is probably relevant:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:866
Expected error:
    <*errors.errorString | 0xc2084ee9f0>: {
        s: "Error running &{/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@3/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://146.148.81.72 --kubeconfig=/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@3/.kube/config delete jobs e2e-test-nginx-job --namespace=e2e-tests-kubectl-urch0] []  <nil>  Error from server: 100: Key not found (/registry/pods/e2e-tests-kubectl-urch0/e2e-test-nginx-job-25nlg) [920]\n [] <nil> 0xc2084c2ee0 exit status 1 <nil> true [0xc2082aa2c0 0xc2082aa420 0xc2082aa440] [0xc2082aa2c0 0xc2082aa420 0xc2082aa440] [0xc2082aa418 0xc2082aa438] [0x833c00 0x833c00] 0xc20837bf20}:\nCommand stdout:\n\nstderr:\nError from server: 100: Key not found (/registry/pods/e2e-tests-kubectl-urch0/e2e-test-nginx-job-25nlg) [920]\n\n",
    }
    Error running &{/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@3/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://146.148.81.72 --kubeconfig=/var/lib/jenkins/workspace/kubernetes-pull-build-test-e2e-gce@3/.kube/config delete jobs e2e-test-nginx-job --namespace=e2e-tests-kubectl-urch0] []  <nil>  Error from server: 100: Key not found (/registry/pods/e2e-tests-kubectl-urch0/e2e-test-nginx-job-25nlg) [920]
     [] <nil> 0xc2084c2ee0 exit status 1 <nil> true [0xc2082aa2c0 0xc2082aa420 0xc2082aa440] [0xc2082aa2c0 0xc2082aa420 0xc2082aa440] [0xc2082aa418 0xc2082aa438] [0x833c00 0x833c00] 0xc20837bf20}:
    Command stdout:
    
    stderr:
    Error from server: 100: Key not found (/registry/pods/e2e-tests-kubectl-urch0/e2e-test-nginx-job-25nlg) [920]
    
    
not to have occurred
```

@mqliang PTAL

**Comment by gmarek** [comment]
@brendandburns - can you please review the fix?

**Comment by mqliang** [comment]
@gmarek rebased then all the test passed. PTAL

**Comment by devth** [comment]
@mqliang parsing still fails with an env like:

```
--env="POST='{""foo"": ""bar"", ""baz"": ""qux""}'"
```

```
error: invalid env:  baz: qux}'
```

**Comment by willis7** [comment]
@mqliang, both types fail for me. Has there been a regression?

**Comment by mqliang** [comment]
@devth @willis7 Sorry for my missing. I am recently really occupied. Would you guys mind submit a PR to fix this?

**Comment by jicki** [comment]
kubectl run zookeeper-1 --image=zk:alpine --env="NODES=zookeeper-1,zookeeper-2,zookeeper-3"                  
error: invalid env: zookeeper-2

**Comment by lzvoyager** [comment]
I'm running into similar problem, using kubectl on a linux machine. Thought this issue was fixed already?

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.6", GitCommit:"114f8911f9597be669a747ab72787e0bd74c9359", GitTreeState:"clean", BuildDate:"2017-03-28T13:36:31Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Pull request merged**
