### PR TITLE
Automated cherry pick of #11569

### PR DESCRIPTION
**Pull request by nikhiljindal**
Cherrypicking changes to build/mark-new-version from #11569 and #11124
Have removed other doc changes.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @lavalamp @brendandburns

**Comment by nikhiljindal** [comment]
cc @zmerlynn

**Comment by zmerlynn** [comment]
This breaks `mark-new-version`. Please fix it, show me it's working, and compound cherry-pick the resulting set.

Pretty soon I'm just going to swap the Jenkins build over to ALWAYS run mark-new-version, because people seem to be breaking it every day now.

**Comment by lavalamp** [comment]
Breaks in what way?

**Comment by nikhiljindal** [comment]
Fixed the breakage in https://github.com/GoogleCloudPlatform/kubernetes/pull/11609

**Comment by nikhiljindal** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/11619 is another try at this including #11609

**Pull request closed without merging**
