### PR TITLE
Netpol: Support UDP protocol in network policies

### PR DESCRIPTION
**Pull request by eth0xFEED**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Adds network policy e2e test support, specifically for the UDP protocol. We need this coverage so that network policy isn't only tested with TCP.

```release-note
NONE
```

Ignore all commits except last one, those are being tracked in Pull: [https://github.com/kubernetes/kubernetes/pull/91592]

### CODE REVIEW

**Comment by jayunit100** [comment]
Follow on to #91592

**Comment by aojea** [comment]
needs rebase @eth0xFEED :)

**Comment by aojea** [comment]
@knabben didn't implement you this in another PR? 
or am I mixing things?

**Comment by aojea** [comment]
just receive confirmation this was already implemented
Thanks for the effort anyway
/close

**Pull request closed without merging**
