### PR TITLE
Fix typos in files which are used for generating OpenAPI

### PR DESCRIPTION
**Pull request by invidian**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Right now when projects use https://github.com/kubernetes-sigs/custom-metrics-apiserver/blob/master/test-adapter/generated/openapi/zz_generated.openapi.go, they inherit couple of typos, which will be detected by tools like `codespell`.

This PR fixes those typos.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/ok-to-test

**Comment by invidian** [comment]
There are still some files with those typos, but I'm not sure if they should be fixed as well:
```console
$ git grep -E '(fileystem|assigment|coersion)' | cut -d: -f1
staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/testdata/swagger.json
staging/src/k8s.io/cli-runtime/artifacts/openapi/swagger.json
staging/src/k8s.io/cli-runtime/artifacts/openapi/swagger.json
staging/src/k8s.io/kubectl/testdata/openapi/swagger.json
staging/src/k8s.io/kubectl/testdata/openapi/swagger.json
vendor/sigs.k8s.io/kustomize/api/krusty/kustomizer.go
vendor/sigs.k8s.io/kustomize/kyaml/openapi/kubernetesapi/v1204/swagger.json
vendor/sigs.k8s.io/kustomize/kyaml/openapi/kubernetesapi/v1204/swagger.json
```

**Comment by caesarxuchao** [comment]
/assign @lavalamp 
for approval

**Pull request merged**
