### PR TITLE
Fix conversions generator

### LINKED ISSUE #96015: Conversion generator doesn't correctly regenerate conversions if only some directories changed
In the codegenerator we have:
https://github.com/kubernetes/gengo/blob/master/parser/parse.go#L465-L470

So basically we process only packages that are explicitly requested by the user and ignore ones that are imported.
So in order to have the conversion func imported by the generator, the package where it lives has to be explicitly imported.

So we should basically always pass all input packages to conversion generator.

This is problematic, when regenerating conversions, we simply pass to input directories only those that were changed in the meantime:
https://github.com/kubernetes/kubernetes/blob/master/build/root/Makefile.generated_files#L437

We should fix that - probably by passing all CONVERSION_DIRS as inputs to conversion-gen

/kind-bug
@kubernetes/sig-api-machinery-bugs 
@roycaihw @lavalamp @sttts @deads2k

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix https://github.com/kubernetes/kubernetes/issues/96015

```release-note
NONE
```

/kind bug
/priority critical-urgent

### CODE REVIEW

**Comment by wojtek-t** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by thockin** [comment]
What about #96063 instead?  That should impact the build somewhat less.

**Comment by wojtek-t** [comment]
I'm fine with that - I think it's missing deepcopy-gen - I can switch this PR to do what you did with deepcopy gen next week.

/hold

**Comment by thockin** [comment]
I can't get deepcopy-gen to fail - can you?

**Comment by wojtek-t** [comment]
> I can't get deepcopy-gen to fail - can you?

Not in the current shape, but in theory the same thing can happen.
But I'm fine with leaving as is for now until we face this issue in the future.

**Pull request closed without merging**
