### PR TITLE
Automated cherry pick of #66264: extend timeout to workaround slow arm64 math

### PR DESCRIPTION
**Pull request by joejulian**
Cherry pick of #66264 on release-1.11.

#66264: extend timeout to workaround slow arm64 math

### CODE REVIEW

**Comment by guineveresaenger** [comment]
@foxish for cherry-pick approval

**Comment by guineveresaenger** [comment]
/cc @foxish 

fun with bots...apologies for noise

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Pull request merged**
