### PR TITLE
Automated cherry pick of #119762: fix wait.PollUntilContextCancel immediately executes

### PR DESCRIPTION
**Pull request by liangyuanpeng**
Cherry pick of #119762 on release-1.28.

#119762: fix wait.PollUntilContextCancel immediately executes

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
cc @apelisse for approval.
/kind bug

**Comment by apelisse** [comment]
I would suggest keeping the same approver as for the original PR
/assign @smarterclayton

**Comment by liangyuanpeng** [comment]
kindly ping @smarterclayton 

Any help moving forward with this PR would be greatly appreciated,Thanks.

**Pull request closed without merging**
