### PR TITLE
Update the kubelet with the ability to register itself with the master.

### PR DESCRIPTION
**Pull request by brendandburns**
See #2303

### CODE REVIEW

**Comment by bgrant0607** [comment]
@brendandburns Are you planning to pick this up again?

**Comment by erictune** [comment]
ping @brendanburns  to close PR or state plan for it

**Comment by phemmer** [comment]
> ping @brendanburns to close PR or state plan for it

I think that might be a bad ping. @brendanburns vs @brendandburns

**Comment by bgrant0607** [comment]
Discussed w/ @brendandburns. We're planning to do this, but not using this exact approach. Closing.

**Pull request closed without merging**
