### PR TITLE
Juju Documentation Update

### PR DESCRIPTION
**Pull request by lazypower**
Greetings,

We noticed our docs are a bit behind the work we've done to update Juju since we've upstreamed the charm code. Please take a look  :tophat: tip.

### CODE REVIEW

**Comment by mbruzek** [comment]
I have signed the CLA.  These commits are okay to commit.

**Comment by erictune** [comment]
Our CLA database says that chuckbutler has signed the CLA, but mbruzek has not.

**Comment by erictune** [comment]
I'm fine merging this time since mbruzek said these were okay to merge.  Next time it will be easier if you can sort out the CLA for all parties.

**Comment by erictune** [comment]
@erickhan any issues with use of logos in the diagram?

**Comment by erictune** [comment]
wierd.  mbruzek shows up as having signed CLA on #9668.
Anyhow, everything looks good except I want a quick check on the use of logos.  After that it is good to go.

**Comment by erickhan** [comment]
re: logos... hrm.

The author should check with the logo usage of the logos he/she uses. If the logo owners ask us to remove, we should remove. Any more complicated, we can get a lawyer, as IANAL. 

As for Kubernetes' logo use, it's [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/logo_usage_guidelines.md). 

Sooo, @chuckbutler ... if you've verified the logo use, lgtm. For Kubernetes' logo use, this diagram's use here lgtm.

**Comment by chuckbutler** [comment]
@erickhan  I'll ship off an email to the CoreOS folks (cc @kelseyhightower) and to the Docker folks so we have on record an express written permission moving forward.

As far as I can tell we're within the ToS for using their TradeMarked material - but always good to have the proof. I'll CC / forward when I have received the responses.

Thanks for taking a look.

**Comment by chuckbutler** [comment]
Closing stale PR

**Pull request closed without merging**
