### PR TITLE
Rename controller 17648

### PR DESCRIPTION
**Pull request by ReneSaenz**
**What this PR does / why we need it**:
Rename controller pkg/registry/core/controller to pkg/registry/core/replicationcontroller
This will clarify the purpose of the controller since intent is replicationcontroller

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
please refer to:
https://github.com/kubernetes/kubernetes/issues/17648

**Special notes for your reviewer**:

none

**Release note**:

```NONE
```

### CODE REVIEW

**Comment by kargakis** [comment]
@ReneSaenz a couple of things:
* you need to sign the CLA
* you need to run hack/update-bazel.sh
* finally squash all commits into one

and this should be good to go

**Comment by ReneSaenz** [comment]
@kargakis thank you for the feedback. Will do

**Comment by ReneSaenz** [comment]
@kargakis Found out my git profile was wrong, so I think that is why it did not recognize the CLA. Fixed my email address.
Got latest and when trying to do a commit to merge I get the following error. Could you guide me in how to fix this?

...
Checking for files that need boilerplate... OK

Checking for problems with flag names... ERROR!
There appear to be problems with the following:
  Found a flag declared with an _ but which is not explicitly listed as a valid flag name in hack/verify-flags/excluded-flags.txt
Are you certain this flag should not have been declared with an - instead?
application_metrics_count_limit
docker_env_metadata_whitelist
docker_root
event_storage_age_limit
event_storage_event_limit
global_housekeeping_interval
log_cadvisor_usage

Checking for API descriptions... OK

...

**Comment by kargakis** [comment]
I don't think you need to fix that issue - you don't touch flags
anyway.What do you mean by "do a commit to merge"?At this point you need to
`git fetch` the Kubernetes master, `git merge` in your local master, then
`git rebase master` in your feature branch and resolve the conflicts.

**Comment by ReneSaenz** [comment]
@kargakis I will close this PR and open a new one from another branch I have created.

**Comment by ReneSaenz** [comment]
@kargakis 

closed this PR. Please refer to the new one

https://github.com/kubernetes/kubernetes/pull/40280

**Pull request closed without merging**
