### PR TITLE
Updated validate.go

### PR DESCRIPTION
**Pull request by deveshgoyal1000**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Makes more understandable.

### CODE REVIEW

**Review by deveshgoyal1000 — COMMENTED** [review]
There was a grammatical mistake

**Comment by TommyStarK** [comment]
/release-note edit
```
NONE
```

**Comment by TommyStarK** [comment]
/release-note-edit

NONE

**Comment by TommyStarK** [comment]
/release-note edit

```release-note
NONE
```

**Comment by bart0sh** [comment]
@deveshgoyal1000 Thank you for your PR. It seems to only contain trivial edits. Please
read [our trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits). We encourage you to take a look at confirmed issues and bugs or issues marked help-wanted.

**Pull request closed without merging**
