### PR TITLE
Move autoscaling/v2 from alpha1 to beta1

### PR DESCRIPTION
**Pull request by DirectXMan12**
This graduates autoscaling/v2alpha1 to autoscaling/v2beta1.  The move is more-or-less just a straightforward rename.

Part of kubernetes/features#117

```release-note
v2 of the autoscaling API group, including improvements to the HorizontalPodAutoscaler, has moved from alpha1 to beta1.
```

### CODE REVIEW

**Comment by mwielgus** [comment]
Does this PR also enable the api by default?

**Comment by DirectXMan12** [comment]
> Does this PR also enable the api by default?

No, I haven't changed whether it's enabled by default or not.  Good catch, I'll fix that once I fix some of the verification errors.

**Comment by sttts** [comment]
Storage version is v1, so this change is fine. kubectl also uses v1 I guess. So only those clients explicitly opting in will miss the v2alpha1 group with this hard cut. So looks good to me.

**Comment by DirectXMan12** [comment]
Dearest verify-api-reference-doc,

Have you been drinking?  `./hack/update-api-reference-docs.sh` makes no changes, yet you still complain.

Sincerely,
Solly

**Comment by DirectXMan12** [comment]
@sttts any idea what's going on with verify?

**Comment by sttts** [comment]
> @sttts any idea what's going on with verify?

You just forgot to update api docs?

**Comment by sttts** [comment]
> Have you been drinking? ./hack/update-api-reference-docs.sh makes no changes, yet you still complain.

looks like you did think about it. Hmm.

**Comment by DirectXMan12** [comment]
@sttts yeah, I can't get update-api-reference-docs to produce any changes, but verify-api-reference-docs *insists* v1alpha1 existing.  It's almost like it's using an old version of the container image to verify.

**Comment by sttts** [comment]
Stupid question: `make clean`?

**Comment by sttts** [comment]
@DirectXMan12 don't know much about the `*-api-reference-docs` scripts either. I fear you have to debug them to know what's going on :-/

**Comment by piosz** [comment]
cc @kubernetes/sig-autoscaling-api-reviews

**Comment by DirectXMan12** [comment]
figured it out.  There were some leftover files that I somehow missed on my initial pass through, and `update-api-reference-docs` will never delete anything.

**Comment by DirectXMan12** [comment]
/retest

flake on #51379

**Comment by smarterclayton** [comment]
Changes look good to me, but will defer to the sig.

/approve

**Comment by DirectXMan12** [comment]
/retest

@piosz @kubernetes/sig-instrumentation-bugs there are what seem like a bunch of flakes on Stackdriver logging.  Can one of you take a look and make sure it's not some actual error?

**Comment by DirectXMan12** [comment]
looks like it's related to https://github.com/kubernetes/kubernetes/issues/51700

**Comment by sjenning** [comment]
cross failure is fixed in https://github.com/kubernetes/kubernetes/pull/51984

**Comment by derekwaynecarr** [comment]
adding to 1.8 milestone per feature freeze exception being granted.

/cc @jdumars

**Pull request merged**
