### PR TITLE
Fix small typo - "nfds"

### PR DESCRIPTION
**Pull request by k-angelo**
What this PR does / why we need it:
Simple code and typo fixed in nfs tests. The tests in nfs are useful as an example of how to configure a NFS server and this typo was hurting code comprehension.

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
none

Special notes for your reviewer:
none

Release note:

none

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by tao12345666333** [comment]
Signed. Thanks.

**Comment by konstantinos-angelo** [comment]
I signed it

**Comment by ixdy** [comment]
It looks like this typo has existed since this file was created (#7435). @jsafrane I imagine this wasn't intentional?

/lgtm

**Comment by nikhita** [comment]
@konstantinos-angelo looks like the CLA hasn't been signed yet...can you take a look at it again? Thanks!

/release-note-none

**Comment by konstantinos-angelo** [comment]
@nikhita Thanks for the notification :)

**Pull request merged**
