### PR TITLE
remove deprecated function NewFilteredSharedInformerFactory

### PR DESCRIPTION
**Pull request by tanjing2020**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by sttts** [comment]
/ok-to-test

Has there been an analysis via github search whether this func is still used much in the ecosystem?

**Comment by tanjing2020** [comment]
I'm not sure. Before confirming clearly, keep this interface.
/close

**Pull request closed without merging**
