### PR TITLE
Suggest udacity course to learn k8s in Readme

### PR DESCRIPTION
**Pull request by nrkfeller**
**What this PR does / why we need it**:
Suggest visitors to view the Udacity course on kubernetes. Many users will benefit from going directly there (as i would have when getting started)
**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #
<no issue>
**Special notes for your reviewer**:

**Release note**:

``` release-note
```

Many users will benefit by going directly to this course to learn how to get started rather than reading through the documentation

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32395)

### CODE REVIEW

**Comment by nrkfeller** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32395)*

**Comment by nrkfeller** [comment]
ok to test

**Comment by dchen1107** [comment]
ok to test

**Comment by dchen1107** [comment]
LGTM 

cc/ @devin-donnelly

**Comment by dchen1107** [comment]
@devin-donnelly ping...

**Comment by dchen1107** [comment]
LGTM

**Pull request merged**
