### PR TITLE
fix the typos of e.g.

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
fix the typos of e.g.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
@ghodss PTAL

**Comment by zhangxiaoyu-zidif** [comment]
@lavalamp could you approve it.

**Comment by k82cn** [comment]
@zhangxiaoyu-zidif , please combine those commits into one.

**Comment by zhangxiaoyu-zidif** [comment]
@k82cn how to combine those commits into one? use some git commands or close this pr and then request another one? Thanks very much.

**Comment by k82cn** [comment]
Try following commands:

```
git reset XXX <== the hashcode just before your first commit
git commit -a -m "xxx"
git push --force
```

**Comment by zhangxiaoyu-zidif** [comment]
@k82cn  I failed to combine them into one, so I restart one PR #44024 . Thanks for your help. I will learn how to combine later.

**Pull request closed without merging**
