### PR TITLE
Update kube-openapi and structured-merge-diff

### PR DESCRIPTION
**Pull request by apelisse**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
mechanics of the bump look fine.

I had a couple questions about the `fields-to-discriminateBy` name. Mixing kebab-case and camelCase looks pretty strange. Is `discriminateBy` a term used in openapi, or did we come up with that? If we picked it, did we consider alternatives like `fields-to-discriminator-value`?

It doesn't look like this causes any generation changes to our openapi, so we can defer those questions to a follow-up if you want, but let's resolve that before we start publishing union/discriminator extensions in our openapi.

**Comment by apelisse** [comment]
This has been replaced.

**Pull request closed without merging**
