### PR TITLE
fix typo in kubeadm log

### PR DESCRIPTION
**Pull request by CaoDonghui123**
#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it:
fix typo in kubeadm log
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm
/ok-to-test
/priority important-longterm
/sig cluster-lifecycle

**Comment by liggitt** [comment]
Thanks for the PR, but changes to files in vendor have to be made upstream in the source repo first and then updated. This change would be made in the https://github.com/kubernetes/klog repo

/close

**Pull request closed without merging**
