### PR TITLE
[WIP] Cleanup stale approvers/reviewers from OWNERS files

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

Folks listed here are not members of kubernetes org and do not have any
commits
in the kubernetes/kubernetes repository:
- chira001
- chuckbutler
- dineshgovindasamy
- girishkalele
- lixiaobing10051267
- rusenask
- wasylkowski

Folks listed here are members of kubernetes org but do not have any
commits
in the kubernetes/kubernetes repository:
- cupofcat
- danielromlein
- luomiao
- mhenc
- nhlfr
- parispittman
- Phillels
- rrati

Folks listed here have the wrong ID listed:
- MikaelCluseau (should be mcluseau)

Folks listed here have typo in their ID:
- liggit (should be liggitt)

Change-Id: I688c8ed37a14c93513361985f8f45ce63223acca

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by parispittman** [comment]
I was added to suggest, review, and make changes to the github templates when needed. cblecker beats me to the punch on most days. :)

**Comment by spiffxp** [comment]
/hold
I have a bit of an issue with the second list being a hard and fast rule.  As a signal to look closer, or ask these folks if they're fine being removed, OK.  But, [the requirements to be a reviewer as written today](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements-1) allow someone to be a reviewer without having committed any code if they've reviewed PR's.  Same goes for approver status.  So I'd want proof they're not meeting those criteria as well.

Unfortunately getting data on reviews is not as easy as querying an endpoint today.  I want to lean on devstats but it may need a bit of tuning.  [Developer Activity Counts by Repository Group]( https://k8s.devstats.cncf.io/d/13/developer-activity-counts-by-repository-group?orgId=1&var-period_name=Last%20year&var-metric=reviews&var-repogroup_name=Kubernetes) looks like a good start

>Review is defined when someone adds /approve or /lgtm comment or adds approved or lgtm label or adds PR review comment

Based on that it looks like the following users have reviewed in this repo in the last year
- luomiao
- rrati
- nhlfr
- parispittman

**Comment by dims** [comment]
@spiffxp i've opened an issue there as well - https://github.com/cncf/devstats/issues/139

**Comment by nikhita** [comment]
From the first list, `chuckbutler` probably had their username changed. It's now https://github.com/lazypower. They have the following contributions in the project: https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Alazypower+is%3Aclosed and are a member of the Kubernetes org.

**Pull request closed without merging**
