### PR TITLE
Use RWMutex to improve locking for serviceCache

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
In serviceCache, we can utilize RWMutex to improve efficiency of locking.

```release-note
NONE
```

### CODE REVIEW

**Comment by tedyu** [comment]
The failed test was introduced by #78513

**Review by draveness — APPROVED** [review]
/lgtm
/priority backlog

**Comment by tedyu** [comment]
@andrewsykim
Can you take a look ?

**Comment by andrewsykim** [comment]
/approve

Thanks @tedyu 

cc @MrHohn

**Pull request merged**
