### PR TITLE
Fix golint failures in cmd/cloud-controller-manager/app/apis/config/v1apha1

### PR DESCRIPTION
**Pull request by abserari**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by abserari** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).

check CLA

**Comment by jiahuif** [comment]
Thanks for the PR!

Unfortunately, it is common for the codebase to use `SetDefaults_SomeResource` as function names. I would vote for not changing that for the sake of consistency.

**Comment by abserari** [comment]
> @abserari: The following tests **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-kubernetes-node-e2e	[1f2ec99](https://github.com/kubernetes/kubernetes/commit/1f2ec994f6340afd818e70ae79e0a56d1664acaa)	[link](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/95352/pull-kubernetes-node-e2e/1314295766251999232/)	`/test pull-kubernetes-node-e2e`
> pull-kubernetes-verify	[1f2ec99](https://github.com/kubernetes/kubernetes/commit/1f2ec994f6340afd818e70ae79e0a56d1664acaa)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/95352/pull-kubernetes-verify/1314295767673868288)	`/test pull-kubernetes-verify`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=95352). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Aabserari). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

/retest

**Comment by abserari** [comment]
> Thanks for the PR!
> 
> Unfortunately, it is common for the codebase to use `SetDefaults_SomeResource` as function names. I would vote for not changing that for the sake of consistency.

Oh, So sorry, Now  I would close it and find another to test my first PR.

**Comment by abserari** [comment]
I guess if golint_failure in the file. If you have a comment after the line, you will not be trying to change it to satisfied the golint.

**Pull request closed without merging**
