### PR TITLE
glog.Warning output content not complete, lack of string fomat "%s"

### PR DESCRIPTION
**Pull request by lixiaobing1**
glog.Warning output content not complete, lack of string fomat "%s"

### CODE REVIEW

**Comment by dims** [comment]
@wojtek-t @lixiaobing10051267 - This PR was probably not a good idea.

I tried this sample code - http://paste.openstack.org/show/537439/ and saw the following output http://paste.openstack.org/show/537440/.

Please see that
```
glog.Warning("DetachDisk called on non-attached disk: %s", "myname3")
```
ended up printing
```
W0719 10:41:42.105695   64827 a.go:19] DetachDisk called on non-attached disk: %smyname3
```

Note that the first string is a format string only if `glog.Warningf` was used. In this case `glog.Warning` is being used.

**Comment by wojtek-t** [comment]
That's actually a good point - sorry I missed that it is Warning not Warningf.

@lixiaobing10051267 - can you please fix it?

**Comment by dims** [comment]
@wojtek-t : i found a few more locations, so please see:
https://github.com/kubernetes/kubernetes/pull/29209/

**Comment by lixiaobing10051267** [comment]
ok, i will fix it.

**Pull request merged**
