### PR TITLE
easier auto-conversion, strict compat with deprecatedPublicIPs

### PR DESCRIPTION
**Pull request by thockin**
@wojtek-t for opinions on the auto-conversion stuff (first commit)

### CODE REVIEW

**Comment by wojtek-t** [comment]
>
Alternative approach 1:  Make the generator always generate:
    auto_convert_v1_FooBar_To_api_FooBar()
...and then IFF no custom FooBar conversion is defined, also define:
    convert_v1_FooBar_To_api_FooBar()
...which calls the auto_convert... form.  This is a little cleaner but more net
code.

I agree this approach is cleaner and personally I would go this way.

I'm completely fine with proceeding with your suggestion - this will be strictly better that what we have now. Thanks for doing this @thockin !

>
Alternative approach 2:  Make the generated code call custom code at the end of
each generated function.  This has less net code and is more self-contained but
is a little less obvious.

**Comment by lavalamp** [comment]
How would you get the old behavior, if you wanted it? E.g. if there were large changes and nothing the autogenerated wanted to do was useful.

**Comment by lavalamp** [comment]
Prefixing with an _ isn't clear to me. Does that mean it's non-recursive? What prevents one from calling the current auto-generated thing?

**Comment by thockin** [comment]
New push of this is up.  codegen retooled as discussed.  Prefers old field for max compat.

**Comment by thockin** [comment]
@wojtek-t PTAL at code-gen

**Comment by thockin** [comment]
@wojtek-t rebasing this one is hard, so sooner is better.

**Comment by wojtek-t** [comment]
LGTM - thanks @thockin !

**Comment by bgrant0607** [comment]
I assume this is no longer WIP.

**Pull request merged**
