### PR TITLE
Fix documentation in clientcmd/doc.go.

### PR DESCRIPTION
**Pull request by technosophos**
The package documentation in `clientcmd` seems to reflect an older API. This updates the documentation to use the current API.

### CODE REVIEW

**Comment by technosophos** [comment]
I added another small and related documentation fix for the `unversioned` package.

**Comment by ashcrow** [comment]
The doc changes look good. The shippable failure is likely unrelated since there is no functionality change in this PR.

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Pull request merged**
