### PR TITLE
e2e: DaemonSet maxSurge test should account for terminated pods that are terminated by the test

### LINKED ISSUE #121823: [Flaking] [sig-apps] Daemon set [Serial] should surge pods onto nodes when spec was updated and update strategy is RollingUpdate
### Failure cluster [2dc5e72feecececa1727](https://go.k8s.io/triage#2dc5e72feecececa1727)
https://storage.googleapis.com/k8s-triage/index.html?test=should%20surge%20pods%20onto%20nodes%20when%20spec%20was%20updated%20and%20update%20strategy%20is%20RollingUpdate

##### Error text:
```
[FAILED] invariants were violated during daemonset update:
An old pod with UID bddc4da1-7cb5-404f-825f-ff62ecb12ec4 has been running alongside a newer version for longer than 1m0s
In [It] at: test/e2e/apps/daemon_set.go:813 @ 10/30/23 14:43:33.844

```
#### Recent failures:
[2023/11/8 23:32:39 ci-kubernetes-e2e-gci-gce-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1722275947316514816)
[2023/11/8 16:56:39 ci-kubernetes-e2e-gce-cos-k8sstable1-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sstable1-serial/1722176289084805120)
[2023/11/8 05:23:06 ci-kubernetes-soak-gci-gce-stable2](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-soak-gci-gce-stable2/1722001751260794880)
[2023/11/5 10:15:26 ci-kubernetes-e2e-gci-gce-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1720988155324141568)
[2023/11/4 12:58:25 ci-kubernetes-e2e-gci-gce-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1720666784987615232)

/kind flake
/sig apps

This is an old flaking since https://github.com/kubernetes/kubernetes/issues/107174, but the flaky rate is not that high.

The rate in recent runs in https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial is about 3/23 ~ 13%.

### PR DESCRIPTION
**Pull request by atiratree**
#### What type of PR is this?

/kind bug
/kind failing-test
/kind flake

#### What this PR does / why we need it:

We can see from the logs that new pods are being terminated periodically before they reach readiness. This causes the invariant to fail. The invariant should be calculated from each new pod and not from the first one, which may not even be alive anymore.

Also, because we disturb the rollout during the `Check that daemon pods surge and invariants are preserved during that rollout`, it is safer to increase the timeout by 5 minutes.

#### Which issue(s) this PR fixes:

Fixes #121823

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by atiratree** [comment]
need to confirm this with stress locally first
/hold

**Comment by atiratree** [comment]
observed https://github.com/kubernetes/kubernetes/issues/124791
/test pull-kubernetes-node-e2e-containerd

**Comment by atiratree** [comment]
/hold cancel
passing stress runs

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
