### PR TITLE
Adding myself to sig-network reviewers and approvers

### PR DESCRIPTION
**Pull request by robscott**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
I've [reviewed and approved a lot of PRs at this point](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+reviewed-by%3Arobscott), want to formally become a sig-network reviewer and approver to help out more.

/sig network
/assign @thockin

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Sucker!

/lgtm
/approve

**Comment by aojea** [comment]
/lgtm
+1

**Pull request merged**
