### PR TITLE
Match regexes for error strings in e2e

### LINKED ISSUE #19723: Services e2e tests require different output between 1.1 and HEAD
**Services should prevent NodePort collisions**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:639 Expected : Service "nodeport-collision-2" is invalid: spec.ports[0].nodePort: Invalid value: 31108: provided port is already allocated to equal : Service "nodeport-collision-2" is invalid: spec.ports[0].nodePort:
invalid value '31108', Details: provided port is already allocated*

**Services should check NodePort out-of-range**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:705 Expected : Service "nodeport-range-test" is invalid: spec.ports[0].nodePort: Invalid value: 26176: provided port is not in the valid range to equal : Service "nodeport-range-test" is invalid: spec.ports[0].nodePort: invalid value '26176', Details: provided port is not in the valid range*

This is just caused by the error messages changing:

> Invalid value: 31108: provided port is already allocated

vs.

> invalid value '31108', Details: provided port is already allocated

@kubernetes/kube-api Do we care?

### PR DESCRIPTION
**Pull request by thockin**
Fixes #19723

### CODE REVIEW

**Comment by ihmccreery** [comment]
Thanks @thockin.  This is the right thing to do for master.  Can you also please cherry-pick this back to `release-1.1`, since the `release-1.1` tests against a HEAD cluster are actually what's causing this to fail?  (Sorry the original bug wasn't clear about that.)

**Comment by ihmccreery** [comment]
@k8s-bot test this again please

**Comment by ihmccreery** [comment]
Except the build is failing:

```
_output/local/go/src/k8s.io/kubernetes/test/e2e/service.go:649: undefined: MatchRegex
```

**Comment by thockin** [comment]
s/Regex/Regexp/

will offer a CP now, assuming this flies.

**Pull request merged**
