### PR TITLE
Switch to Redcarpet for markdown rendering

### PR DESCRIPTION
**Pull request by thockin**
@caesarxuchao

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Thanks! Let me test it.

**Comment by thockin** [comment]
waiting for OK...

**Comment by caesarxuchao** [comment]
We need to change ```shell to ```console, otherwise not build.
```
grep -lR "\`\`\`shell" ./ | xargs sed -i "s/\`\`\`shell/\`\`\`console/g"
```

**Comment by thockin** [comment]
done in #11583

**Comment by thockin** [comment]
also, Ipreprocess docs on import and sub shell -> sh

**Comment by thockin** [comment]
OK to merge?

**Comment by thockin** [comment]
http://thockin.github.io/kubernetes/v1.0/docs is my integration branch with
redcarpet and head docs

**Comment by bgrant0607** [comment]
I vote to merge now

**Comment by thockin** [comment]
Chao has one issue we're looking at, hold tight

**Comment by thockin** [comment]
Merging

**Comment by caesarxuchao** [comment]
one small issue though, it renders bullet list written in "1. " to numbered list. I can submit a munger to fix replace "1. " fashion bullet list with "- " bullet list.

**Comment by bgrant0607** [comment]
We want numbered lists in md to be converted to html ordered lists

**Comment by caesarxuchao** [comment]
I mean things like this:

```
1. aaa
1. bbb
```
should be rendered to 
- aaa
- bbb, 

but currently under redcarpet it's rendered to 
1. aaa
2. bbb

it doesn't cause much damage though.

**Comment by thockin** [comment]
1. aaa
1. bbb

is markdown code for "auto-number, please".

**Comment by caesarxuchao** [comment]
Please ignore my comment. Apparently I was wrong.

**Pull request merged**
