### PR TITLE
Revert "Deprecate HostConfig at container start"

### PR DESCRIPTION
**Pull request by Random-Liu**
Reverts kubernetes/kubernetes#20615 to have a second test and unblock people.

### CODE REVIEW

**Comment by dchen1107** [comment]
lgtm

**Comment by yujuhong** [comment]
LGTM

**Comment by dchen1107** [comment]
#20737

**Comment by pwittrock** [comment]
If all the tests pass can this be manually merged?

**Comment by janetkuo** [comment]
@k8s-oncall: feel free to manually merge this one

**Pull request merged**
