### PR TITLE
Enable batch/v1beta1.CronJobs by default

### LINKED ISSUE #51692: [SQ-blocking] kops-aws presubmit failing continuously due to cronjob e2e test
Ref: https://k8s-testgrid.appspot.com/kubernetes-presubmits#pull-kubernetes-e2e-kops-aws

The test "Garbage collector should delete jobs and pods created by cronjob" is failing continuously with:

```
I0831 02:54:25.154] Aug 31 02:54:10.012: INFO: Failed to delete the CronJob: the server could not find the requested resource
```

cc @k8s-oncall @kubernetes/sig-aws-misc @kubernetes/test-infra-maintainers

### PR DESCRIPTION
**Pull request by soltysh**
This PR re-applies the cronjobs->beta back (https://github.com/kubernetes/kubernetes/pull/51720)  with the fix from @shyamjvs.

Fixes #51692

@apelisse @dchen1107 @smarterclayton ptal
@janetkuo @erictune fyi

### CODE REVIEW

**Comment by jdumars** [comment]
@radhikapc @Bradamant3 for visibility

**Comment by jdumars** [comment]
This will also require changes in GKE, correct?  @mikedanese

**Review by janetkuo — APPROVED** [review]

**Comment by janetkuo** [comment]
> This will also require changes in GKE, correct? 

yes

**Comment by soltysh** [comment]
@justinsb this PR although passed kops tests is again not running tests from this PR, see:
```
I0901 00:40:02.985] Sep  1 00:39:55.241: INFO: Could not find {batch v2alpha1 cronjobs} resource, skipping test: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"Status", APIVersion:"v1"}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Failure", Message:"the server could not find the requested resource", Reason:"NotFound", Details:(*v1.StatusDetails)(0xc4211aade0), Code:404}}
```
It's skipping test due to CronJobs not being present in `batch/v2alpha1` but I've modified the test in this PR to check `batch/v1beta1, so it's clearly not being picked up. If this merges this will block the kops again. Can we get that job fixed or disabled since it's blocking release work?

**Comment by smarterclayton** [comment]
/approve

Because kops-aws presubmit was not testing against the PR directly and is disabled

**Comment by soltysh** [comment]
Re-applying lgtm label after the rebase.

**Comment by fabianofranz** [comment]
This caused our skew tests to break again: https://k8s-testgrid.appspot.com/sig-cli#skew-cluster1.8-kubectl1.7-gce

**Comment by pwittrock** [comment]
@abgworrall  @smarterclayton @soltysh This looks like it was not ready at code freeze, but got merged into 1.8 anyway.  Was this intended?  As @fabianofranz mentioned, it broke sig-cli tests (again).

**Comment by soltysh** [comment]
The change was intended, the breakage apparently not. If it wasn't done we'd never hit the bug and never were able to fix it properly, this is how I see it. That bit that was broken was not related to cronjobs itself, but our restmapper implementation.

**Pull request merged**
