### PR TITLE
[bug]fix the appending bug

### PR DESCRIPTION
**Pull request by DjangoPeng**
Fix the `DOCKER_OPTS` appending bug. Reference the [issue#33124](https://github.com/kubernetes/kubernetes/issues/33124)

``` release-note
Fix the DOCKER_OPTS appending bug.
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33163)

### CODE REVIEW

**Comment by roberthbailey** [comment]
@DjangoPeng does this need to be cherry picked into the 1.4 branch?

**Comment by DjangoPeng** [comment]
@roberthbailey That's fine, because it's a general bug. BTW, why not merge it into `master` branch directly?

**Comment by roberthbailey** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33163)*

**Comment by roberthbailey** [comment]
The cherry pick process is described in https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md. If you want to backport this bug fix to 1.4, you wait until it merges into master and then send a second pull request against the release branch.

**Comment by DjangoPeng** [comment]
@roberthbailey I think it need to be cherry picked into 1.4 at the same time. As I said above, it's a general bug in the `kube-up.sh`. Everytime people install the k8s may cause the same problem if they download the `1.4` without the fix.

**Comment by roberthbailey** [comment]
I've set the appropriate tags; please run the script to create the cherry pick pull request.

**Comment by DjangoPeng** [comment]
I'll do it later, cause I can't push code into github in my company.

**Comment by DjangoPeng** [comment]
@roberthbailey  I have run the script

**Comment by jessfraz** [comment]
@DjangoPeng can you ping me on the PR

**Comment by DjangoPeng** [comment]
@jessfraz Sorry, I have just finished my vacation. I saw that you have picked it, thx~

**Pull request merged**
