### PR TITLE
LimitRange documentation should be under admin

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Per your request @bgrant0607

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks much. 

Please also update tests:
./hack/test-cmd.sh:  kubectl create "${kube_flags[@]}" -f docs/user-guide/limitrange/valid-pod.yaml
./hack/test-cmd.sh:  kubectl delete -f docs/user-guide/limitrange/valid-pod.yaml "${kube_flags[@]}"
./hack/test-cmd.sh:  kubectl create -f docs/user-guide/limitrange/valid-pod.yaml "${kube_flags[@]}"
./hack/test-cmd.sh:  kubectl create -f docs/user-guide/limitrange/valid-pod.yaml "${kube_flags[@]}"
./hack/test-cmd.sh:  kubectl create -f docs/user-guide/limitrange/valid-pod.yaml "${kube_flags[@]}"
./hack/test-cmd.sh:  kubectl create -f docs/user-guide/limitrange/valid-pod.yaml "${kube_flags[@]}"
./hack/test-cmd.sh:  kubectl create -f docs/user-guide/limitrange/valid-pod.yaml "${kube_flags[@]}"
./hack/test-cmd.sh:  kubectl create -f docs/user-guide/limitrange/valid-pod.yaml "${kube_flags[@]}"
./hack/test-cmd.sh:  kubectl create "${kube_flags[@]}" --namespace=other -f docs/user-guide/limitrange/valid-pod.yaml
./hack/test-cmd.sh:  kubectl create -f docs/user-guide/limitrange/valid-pod.yaml "${kube_flags[@]}"
./examples/examples_test.go:            "../docs/user-guide/limitrange": {

@thockin Do we have a plan for keeping docs up to date on kubernetes.io?

**Comment by derekwaynecarr** [comment]
@bgrant0607 - i always forget hack/test-cmd uses this piece.  updates made as requested.

**Comment by derekwaynecarr** [comment]
Looks like Shippable is now unhappy with me.  Updating as needed.

**Comment by derekwaynecarr** [comment]
Shippable is green now.

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
