### PR TITLE
client-go: make retry in Request thread safe

### LINKED ISSUE #109155: client-go: the retry logic in rest.Request should be thread safe
### What happened?

the newly refactored retry logic introduced in 1.22 by https://github.com/kubernetes/kubernetes/pull/102217 broke the thread safety of `*Request`. According to Clayton, it's not a release blocker for 1.24. 
So the goal is to fix it in 1.25 and then back port all the way to 1.22.

Please note that there are other members (not related to retry logic) of `Request` that are not thread safe depending on how different methods of a `Request` object is used from multiple go routines.

https://github.com/kubernetes/kubernetes/pull/102217/files#r837633535

Also, the comments on some of these methods and sections for retry logic can be improved:
- For instance, we may want to rename `IsErrorRetryable` to `IsHttpErrRetryable` and `checkWait` to `isServerIndicatedRetry`. 
That would have helped bring this back into mental cache faster and possibly help some future refactorer.

### What did you expect to happen?

Maintain thread safety of `*Request`

### PR DESCRIPTION
**Pull request by tkashem**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
cherry-pick of https://github.com/kubernetes/kubernetes/pull/109114

#### Which issue(s) this PR fixes:

Fixes #109155

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tkashem** [comment]
i can reproduce the concurrency issue:
```
go test -v -race -count=1 k8s.io/client-go/rest -run=TestRequestConcurrencyWithRetry
=== RUN   TestRequestConcurrencyWithRetry
==================
WARNING: DATA RACE
Read at 0x00c000211bd8 by goroutine 28:
  k8s.io/client-go/rest.(*withRetry).NextRetry()
      /home/akashem/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/with_retry.go:125 +0xad
  k8s.io/client-go/rest.(*Request).request.func2()
      /home/akashem/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:1000 +0x196
  k8s.io/client-go/rest.(*Request).request()
      /home/akashem/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:1023 +0x764
  k8s.io/client-go/rest.(*Request).Do()
      /home/akashem/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:1038 +0xe4
  k8s.io/client-go/rest.TestRequestConcurrencyWithRetry.func2()
      /home/akashem/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request_test.go:3131 +0xd9

Previous write at 0x00c000211bd8 by goroutine 9:
  k8s.io/client-go/rest.(*withRetry).NextRetry()
      /home/akashem/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/with_retry.go:125 +0xc8
  k8s.io/client-go/rest.(*Request).request.func2()
      /home/akashem/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:1000 +0x196
  k8s.io/client-go/rest.(*Request).request()
      /home/akashem/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:1023 +0x764
  k8s.io/client-go/rest.(*Request).Do()
      /home/akashem/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:1038 +0xe4
  k8s.io/client-go/rest.TestRequestConcurrencyWithRetry.func2()
      /home/akashem/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request_test.go:3131 +0xd9

Goroutine 28 (running) created at:
  k8s.io/client-go/rest.TestRequestConcurrencyWithRetry()
      /home/akashem/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request_test.go:3128 +0x7e4
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /usr/lib/go/src/testing/testing.go:1486 +0x47

Goroutine 9 (running) created at:
  k8s.io/client-go/rest.TestRequestConcurrencyWithRetry()
      /home/akashem/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request_test.go:3128 +0x7e4
  testing.tRunner()
      /usr/lib/go/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /usr/lib/go/src/testing/testing.go:1486 +0x47
==================
    request_test.go:3141: Expected attempts: 200, but got: 29
    testing.go:1312: race detected during execution of test
--- FAIL: TestRequestConcurrencyWithRetry (0.00s)
=== CONT
    testing.go:1312: race detected during execution of test
FAIL
FAIL	k8s.io/client-go/rest	0.050s
FAIL
```

with the fix, the previous behavior is restored
```
$ stress ./rest.test -test.run=TestRequestConcurrencyWithRetry
5s: 387 runs so far, 0 failures
10s: 743 runs so far, 0 failures
...
8m50s: 39707 runs so far, 0 failures
8m55s: 40123 runs so far, 0 failures
```

**Comment by aojea** [comment]
/hold

this is incorporating the new unit test that didn't merge yet

https://github.com/kubernetes/kubernetes/pull/112072

**Comment by wojtek-t** [comment]
/lgtm
/approve
/hold cancel

@kubernetes/release-managers - for cherrypick approval

**Comment by cpanato** [comment]
@tkashem @wojtek-t this CP is only required for the 1.23 branch?

**Comment by wojtek-t** [comment]
> @tkashem @wojtek-t this CP is only required for the 1.23 branch?

And 1.22: https://github.com/kubernetes/kubernetes/pull/112394

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
