### PR TITLE
patch: define the environment variable once in the deployment after fixing the deployment resource descriptor

### LINKED ISSUE #58477: Duplicated environment variable in deployment disappears completely when fixed
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
For `deployment` resource:

A container has defined environment variable with name `x` that is duplicated (there are two env vars with the same name, the value is also the same).

When you fix the `deployment` resource descriptor so that environment variable with name `x` appears only once and push it with `kubectl apply`, deployment with no environment variable named `x` is created and therefore no environment variable named `x` is passed to replica set and pods.

**What you expected to happen**:
After fixing the `deployment`, environment variable with name `x` is defined in the `deployment` once .

**How to reproduce it (as minimally and precisely as possible)**:
1. create deployment with container with duplicated environment variable
1. `kubectl apply` it
1. fix deployment removing one of duplicated environment variable definitions
1. `kubectl apply` it
1. `kubectl get deployment/your-deployment -o yaml` prints deployment without 

**Anything else we need to know?**:
nope

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T20:00:41Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:40:06Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: private Kubernetes cluster
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by oliver11rz**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
The problem is:
A container has defined environment variable with name key11 that is duplicated (there are two env vars with the same name, the value is also the same).
When you fix the deployment resource descriptor so that environment variable with name x appears only once and push it with kubectl apply, deployment with no environment variable named x is created and therefore no environment variable named x is passed to replica set and pods.
This can have a serious impact on the production environment, such as the specified IP address disappearing.
We expect to define environment variable with name x once after fixing the deployment.

#### Which issue(s) this PR fixes:
Fixes #58477

#### Does this PR introduce a user-facing change?
```release-note
Defined the environment variable once in the deployment after fixing the deployment resource descriptor.
```
#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
Before fix:
A container has defined environment variable with name key11 that is duplicated (there are two env vars with the same name, the value is also the same). 
deploy same key
deploy same key success

When you fix the deployment resource descriptor so that environment variable with name key11 appears only once and push it with kubectl apply, deployment with no environment variable named key11 is created and therefore no environment variable named key11 is passed to replica set and pods.
deploy fix configuration
deploy fix configuration success

After fix:
After fixing the deployment, environment variable with name key11is defined in the deployment once .
after fix
success

### CODE REVIEW

**Comment by oliver11rz** [comment]
I don't know how to start to test and pass the checks , anyone helps and review?

**Comment by oliver11rz** [comment]
Is there anyone helps and review? It needs trusted user reviews the PR and leaves an /ok-to-test message, so i can start the tests.

**Comment by pacoxu** [comment]
/uncc HirazawaUi bart0sh pacoxu
as this is not related to sig node.

> * **[staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/OWNERS](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/OWNERS)**

The change related file owners can be found in above link.

/ok-to-test
/cc @liggitt 
who may know the context

**Comment by oliver11rz** [comment]
@apelisse Hello friend, there is a bug in strategic patch computation. Could you please help me to review and merge it ?

**Review by HirazawaUi — COMMENTED** [review]
This is a known issue with client-side apply that cannot be fixed in a backwards-compatible way, so we don't seem to be planning to fix it....

Using server-side apply will handle this correctly.

**Comment by jpbetz** [comment]
/sig apps
(I think?)

**Comment by mengqiy** [comment]
This is work-as-intended. The test you are changing is to exercise this behavior.
More context can be found in https://github.com/kubernetes/kubernetes/issues/38332.

**Comment by oliver11rz** [comment]
> This is a known issue with client-side apply that cannot be fixed in a backwards-compatible way, so we don't seem to be planning to fix it....
> 
> Using server-side apply will handle this correctly.

I want to fix the deployment resource descriptor that environment variable appears only once, but kubernetes delete all envs(with same keys). I think it's a mistake and this will lead to serious accidents.
This PR can ensure duplicate variables to be unique if it is needed. I think it's also a protective measure.

**Comment by oliver11rz** [comment]
> This is a known issue with client-side apply that cannot be fixed in a backwards-compatible way, so we don't seem to be planning to fix it....
> 
> Using server-side apply will handle this correctly.

@HirazawaUi
I want to fix the deployment resource descriptor that environment variable appears only once, but kubernetes delete all envs(with same keys). I think it's a mistake and this will lead to serious accidents.
This PR can ensure duplicate variables to be unique if it is needed. I think it's also a protective measure.

**Comment by oliver11rz** [comment]
> This is work-as-intended. The test you are changing is to exercise this behavior. More context can be found in #38332.

@mengqiy
I think there's a problem with the current behavior. 
I want to fix the deployment resource descriptor and apply it to make environment variable appears only once, but kubernetes delete all envs(with same keys). I think it's a mistake and this will lead to serious accidents.
This PR can ensure duplicate variables to be unique if it is needed. I think it's also a protective measure.

**Comment by oliver11rz** [comment]
There is no any protective measure to solve this problem in k8s.If a problem occurs, pods need to be rebuilt in the production scenario, which has a great impact.
This PR can ensure duplicate variables to be unique if it is needed. I think it's also a protective measure.
Could you please help to review again and merge? thanks! @HirazawaUi @mengqiy @pwittrock @apelisse

**Comment by liggitt** [comment]
This change is not correct. This makes a patch indicating all entries should be deleted leave *some* of the duplicate entries.

/close

**Comment by liggitt** [comment]
The problem is that there is no difference in what the client sends when deleting one of the entries and all of the entries with a given key.

**Comment by oliver11rz** [comment]
> The problem is that there is no difference in what the client sends when deleting one of the entries and all of the entries with a given key.
But there is diference when the client want to save only one of the entries with a given key. 
The client fixes the deployment resource descriptor to save only one entries, however, it will delete all entries. This PR can promise to save the last entiry instead of all entries.
@liggitt could you please help to see if this is correct? thanks!

**Pull request closed without merging**
