### PR TITLE
[FEATURE-SERVERSIDE-APPLY] Merge master into feature-serverside-apply

### PR DESCRIPTION
**Pull request by apelisse**
Merge master into the feature branch, and also change the API from lastApplied to ManagedFields with the field set.

There are two tests that are broken:
- unstructured: because we don't have code to go from unstructured to actual FieldSet
- //pkg/master because the version of go-openapi we use has a few bugs (fixed in master, I tested).

```release-note
NONE
```

### CODE REVIEW

**Comment by apelisse** [comment]
@lavalamp @jennybuckley

**Comment by apelisse** [comment]
Best way to review is probably to checkout the PR, and diff against master :-/

**Comment by lavalamp** [comment]
Thanks for taking care of this!

**Pull request merged**
