### PR TITLE
azure file migration go beta

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
azure file migration go beta in 1.21

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
feat: azure file migration go beta in 1.21. Feature gates CSIMigration to Beta (on by default) and CSIMigrationAzureFile to Beta (off by default since it requires installation of the AzureFile CSI Driver)
The in-tree AzureFile plugin "kubernetes.io/azure-file" is now deprecated and will be removed in 1.23. Users should enable CSIMigration + CSIMigrationAzureFile features and install the AzureFile CSI Driver (https://github.com/kubernetes-sigs/azurefile-csi-driver) to avoid disruption to existing Pod and PVC objects at that time.
Users should start using the AzureFile CSI Driver directly for any new volumes.

Azure File CSI driver does not support using same persistent volume with different fsgroups, when CSI migration is enabled for azurefile driver, such case is not supported. (there is a case we support where volume is mounted with 0777 and then it readable/writable by everyone)
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
feat: azure file migration go beta in 1.21. Feature gates CSIMigration to Beta (on by default) and CSIMigrationAzureFile to Beta (off by default since it requires installation of the AzureFile CSI Driver)
The in-tree AzureFile plugin "kubernetes.io/azure-file" is now deprecated and will be removed in 1.23. Users should enable CSIMigration + CSIMigrationAzureFile features and install the AzureFile CSI Driver (https://github.com/kubernetes-sigs/azurefile-csi-driver) to avoid disruption to existing Pod and PVC objects at that time.
Users should start using the AzureFile CSI Driver directly for any new volumes.

Azure File CSI driver does not support using same persistent volume with different fsgroups, when CSI migration is enabled for azurefile driver, such case is not supported. (there is a case we support where volume is mounted with 0777 and then it readable/writable by everyone)
```

/priority important-soon
/sig cloud-provider
/area provider/azure
/triage accepted
/assign @msau42

### CODE REVIEW

**Comment by pwittrock** [comment]
I don't seem like the right person to review this.

**Comment by kikisdeliveryservice** [comment]
This is for https://github.com/kubernetes/enhancements/issues/1885 correct?

**Comment by msau42** [comment]
Correct, I can be the tech reviewer for this

**Comment by andyzhangx** [comment]
/hold
since there is blocking issue here: https://github.com/kubernetes/kubernetes/issues/96508, let's hold for a few days, to check whether it could be fixed soon or postponed to 1.21

**Comment by kikisdeliveryservice** [comment]
> /hold
> since there is blocking issue here: https://github.com/kubernetes/kubernetes/issues/96508, let's hold for a few days, to check whether it could be fixed soon or postponed to 1.21

Just so you're aware: code freeze is EOD PST today. Please keep us updated about your plans for 1.20. 

Thanks!
Kirsten

**Comment by kikisdeliveryservice** [comment]
Hi @andyzhangx 

[Code Freeze](https://github.com/kubernetes/sig-release/blob/master/releases/release_phases.md#code-freeze) is now in effect. Your PR is still unmerged, and has a hold. If you believe this should be in the 1.20 Release, please file an [Exception](https://github.com/kubernetes/sig-release/blob/master/releases/EXCEPTIONS.md).

Best,
Kirsten

/milestone clear

**Comment by andyzhangx** [comment]
@msau42 it's ready to go beta since block issue was fixed by https://github.com/kubernetes/kubernetes/pull/97877

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by gnufied** [comment]
We should cover restrictions and known issues in azurefile CSI driver if they enable the migration. @andyzhangx @msau42 - should we open a new PR to address that?

Namely we need to capture:
1. If CSI migration is enable for azurefile driver then users can't use fsgroup for pods currently.

The other thing we need to do is deprecate the support for using same volume multiple times on a node with different fsgroup. That is unsupported as well (well there is a case we support where volume could be mounted with  777 and then it readable/writable by everyone).

**Comment by andyzhangx** [comment]
> We should cover restrictions and known issues in azurefile CSI driver if they enable the migration. @andyzhangx @msau42 - should we open a new PR to address that?
> 
> Namely we need to capture:
> 
> 1. If CSI migration is enabled for azurefile driver then users can't use fsgroup for pods currently.
> 
> The other thing we need to do is deprecate the support for using same volume multiple times on a node with different fsgroup. That is unsupported as well (well there is a case we support where volume could be mounted with 777 and then it readable/writable by everyone).

@gnufied thanks, I have appended following note in the PR:
```
Azure File CSI driver does not support using same persistent volume with different fsgroups, when CSI migration is enabled for azurefile driver, such case is not supported. (there is a case we support where volume is mounted with 0777 and then it readable/writable by everyone)
```

**Comment by gnufied** [comment]
I think there are two separate issues:

1. If Azurefile CSI migration is enabled, using fsgroup of pods won't be supported *at all*. This is what we are trying to fix here - https://github.com/container-storage-interface/spec/pull/468 but in current beta status we should note that mounting volumes via pod's fsgroup is not supported.
2. The second issue is more like longer term thing. Assuming a version of https://github.com/container-storage-interface/spec/pull/468 gets merged and we start supporting fsgroup for mounting azurefile volumes, we *still* can't support using same volume with different fsgroup on same node because driver has node-stage. So this behaviour needs to be deprecated.

**Pull request merged**
