### PR TITLE
Fix the output of jsonpath in client-go

### PR DESCRIPTION
**Pull request by ChiuWang**
**What this PR does / why we need it**:
before & after:
jsonpath
the jsonpath output didn't contain line break

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CaoShuFeng** [comment]
I think this breaks backward compatibility.
Some program(like bash script) which relay this format may break.

**Comment by charrywanganthony** [comment]
I found the problem and I'm fixing it.

**Comment by charrywanganthony** [comment]
@nikhita PTAL

**Pull request closed without merging**
