### PR TITLE
Create registrytest support for etcd test to reduce amount of boilerplate in tests

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #12207

This is build on top of #13380 - only the second commit is unique for this PR.

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by nikhiljindal** [comment]
This is perfect!
Thanks a lot @wojtek-t 
This greatly reduces unnecessary boilerplate in our tests. Thanks a lot for cleaning it up!

**Comment by nikhiljindal** [comment]
cc @lavalamp since I had discussed this with him

**Comment by wojtek-t** [comment]
@nikhiljindal - I'm glad that you like it
I've rebased the PR

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by nikhiljindal** [comment]
Service test timed out https://github.com/kubernetes/kubernetes/issues/13478.
Its been failing continuously on my PR.

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Pull request merged**
