### PR TITLE
ConfigMap integration test

### PR DESCRIPTION
**Pull request by pmorie**
Add an integration test for the ConfigMap API resource.  Depends on #19716.

### CODE REVIEW

**Comment by pmorie** [comment]
Ready for review; works on top of #19716.

**Comment by pmorie** [comment]
@thockin PTAL

**Comment by thockin** [comment]
Just one nit then LGTM

**Comment by thockin** [comment]
FWIW this is a very skeleton test.  It doesn't actually verify any level of behavioral correctness - we need to make it possible to do more e2e-like testing in integration-test mode, so we can do less of it in e2e mode.

@ihmccreery

**Comment by pmorie** [comment]
@thockin 

> FWIW this is a very skeleton test. It doesn't actually verify any level of behavioral correctness - we need to make it possible to do more e2e-like testing in integration-test mode, so we can do less of it in e2e mode.

Completely agree.

**Comment by pmorie** [comment]
@thockin I'm happy to add more behavioral tests around the API in a follow-up, secrets needs similar treatment.

**Comment by pmorie** [comment]
@thockin PTAL, apparently the comment where you specified your nit is lost, but I believe it was about using multiple env vars in the test.

**Comment by pmorie** [comment]
@thockin ping, let's cross this one off the list

**Comment by pmorie** [comment]
@k8s-bot test this issue: #20908

**Pull request merged**
