### PR TITLE
[release-1.26] releng/go: Update images, deps and version to go 1.19.10

### PR DESCRIPTION
**Pull request by puerco**
#### What type of PR is this?
/kind feature
/area dependency

#### What this PR does / why we need it:

Update images, dependencies and version to Go 1.19.10

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/release/issues/3099

#### Special notes for your reviewer:

/assign @xmudrii @saschagrunert @cpanato @Verolop @jeremyrickard 
/cc @kubernetes/release-engineering 
/priority critical-urgent

#### Does this PR introduce a user-facing change?

```release-note
Kubernetes 1.26.x is now built with Go 1.19.10
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/triage accepted
/priority important-soon

/lgtm

**Review by thockin — COMMENTED** [review]
Is checking in go.sum still useful ?

/lgtm
/approve

**Pull request merged**
