### PR TITLE
Automated cherry pick of #24797 upstream release 1.3

### PR DESCRIPTION
**Pull request by saad-ali**
Cherry pick #24797 ("add enhanced volume and mount logging for block devices") to upstream release 1.3.

### CODE REVIEW

**Comment by saad-ali** [comment]
> We found a Contributor License Agreement for you (the sender of this pull request) and all commit authors, but as best as we can tell these commits were authored by someone else. If that's the case, please add them to this pull request and have them confirm that they're okay with these commits being contributed to Google. If we're mistaken and you did author these commits, just reply here to confirm.

@screeley44 Since you are the original author of the commit, can you please confirm.

**Comment by fabioy** [comment]
@screeley44 Cherrypick approved. Please resolve the cla issue. Thanks.

**Comment by erinboyd** [comment]
The Red Hat CLA covers this PR

**Comment by erinboyd** [comment]
The Red Hat CLA covers this PR

**Comment by saad-ali** [comment]
Thanks @erinboyd. @fabioy I will rebase the PR.

**Pull request merged**
