### PR TITLE
Bump up npd version to v0.4.1

### LINKED ISSUE #47219: [e2e flakes] ci-kubernetes-e2e-gke-reboot - at least one node failed to reboot in the time given
ci-kubernetes-e2e-gke-reboot has been flaking for the last couple of days.

https://k8s-testgrid.appspot.com/release-master-blocking#gke-reboot

Seeing a lot of errors that look like:

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:122
Jun  8 18:43:57.650: Test failed; at least one node failed to reboot in the time given.
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/reboot.go:168
```

Also the logs are saying something about failing to pull images:

> I0608 18:33:48.649] Jun  8 18:33:48.608: INFO: event for kube-dns-2836479273-b44kg: {kubelet gke-bootstrap-e2e-default-pool-44cef888-1bwq} Failed: Failed to pull image "gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.2": rpc error: code = 2 desc = failed to register layer: rename /var/lib/docker/image/aufs/layerdb/tmp/layer-969822486 /var/lib/docker/image/aufs/layerdb/sha256/60ab55d3379d47c1ba6b6225d59d10e1f52096ee9d5c816e42c635ccc57a5a2b: directory not empty
> I0608 18:33:48.649] Jun  8 18:33:48.608: INFO: event for kube-dns-2836479273-b44kg: {kubelet gke-bootstrap-e2e-default-pool-44cef888-1bwq} Failed: Failed to pull image "gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.2": rpc error: code = 2 desc = failed to register layer: rename /var/lib/docker/image/aufs/layerdb/tmp/layer-099381612 /var/lib/docker/image/aufs/layerdb/sha256/7cbcbac42c44c6c38559e5df3a494f44987333c8023a40fec48df2fce1fc146b: directory not empty
> I0608 18:33:48.649] Jun  8 18:33:48.608: INFO: event for kube-dns-2836479273-b44kg: {kubelet gke-bootstrap-e2e-default-pool-44cef888-1bwq} Failed: Failed to pull image "gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.2": rpc error: code = 2 desc = failed to register layer: rename 

Last three failures:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-reboot/5335
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-reboot/5334
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-reboot/5333

cc @kubernetes/kubernetes-release-managers @dchen1107

### PR DESCRIPTION
**Pull request by ajitak**
```
Bump up npd version to v0.4.1
```

Fixes #47219

### CODE REVIEW

**Comment by Random-Liu** [comment]
@ajitak Do you expect NPD to start the docker monitor? If so, you also need to pass in the docker monitor config. https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/node-problem-detector/npd.yaml#L51

**Comment by ajitak** [comment]
@Random-Liu updated yaml to pass docker monitor config.

**Comment by Random-Liu** [comment]
@ajitak Please also update the systemd service of gci.

**Comment by Random-Liu** [comment]
Fixes https://github.com/kubernetes/kubernetes/issues/47219.

@kubernetes/kubernetes-release-managers This helps fix a 1.7 issue.

**Comment by dchen1107** [comment]
The memory overhead looks ok by design based on the data published at: https://github.com/kubernetes/node-problem-detector/issues/85#issuecomment-281503607
 since the new change in new NPD image only introduce a new goroutine for docker logs, and by design we bound the memory per goroutine. 

@ajitak Can you check the log level of that docker image corruption issue at docker log? If the docker level is info, not warning or above, the new config in NPD doesn't help the production.

**Comment by ajitak** [comment]
log level of docker image corruption issue at docker log is error.

**Comment by dchen1107** [comment]
Great!

/lgtm

**Comment by Random-Liu** [comment]
Offline discussed with @dchen1107 and @ajitak. The extra resource overhead should be fine based on https://github.com/kubernetes/node-problem-detector/issues/85#issuecomment-281503607.

We should pay attention to the node resource usage after this PR to make sure the docker log parsing doesn't introduce too much overhead.

**Comment by Random-Liu** [comment]
@ajitak You need to cherry-pick this to 1.7. See https://github.com/kubernetes/community/blob/master/contributors/devel/cherry-picks.md.

**Pull request merged**
