### PR TITLE
Azure: Add container service client and deployment client.

### PR DESCRIPTION
**Pull request by nilo19**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Azure: Add container service client and deployment client.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/priority important-soon
/area provider/azure
/sig cloud-provider

### CODE REVIEW

**Comment by andyzhangx** [comment]
@nilo19 why do you want to add aks client on cloud provider lib?

**Comment by nilo19** [comment]
@andyzhangx need to refer to this in cluster autoscaler. Also for possible usage in the future.

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Comment by feiskyer** [comment]
@cblecker could you help to approve the vendor changes?

**Pull request merged**
