### PR TITLE
Prune unused event strategy

### PR DESCRIPTION
**Pull request by yue9944882**
**What this PR does / why we need it**:

As the title.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
/assign @gmarek 

for review first.

**Comment by sttts** [comment]
/hold

after @gmarek's comment.

**Comment by yue9944882** [comment]
Thanks @gmarek @sttts 

Just had a look at the proposal for event v2. It's making perfect sense to me. Good luck! 👍🏻

[https://github.com/gmarek/community/blob/f452e8e335d29b13089700c2b8b434027283fe37/contributors/devel/event-style-guide.md](https://github.com/gmarek/community/blob/f452e8e335d29b13089700c2b8b434027283fe37/contributors/devel/event-style-guide.md)

**Pull request closed without merging**
