### PR TITLE
Update aws-sdk-go dependency

### PR DESCRIPTION
**Pull request by apelisse**
Update aws dependency.

kubernetes/contrib has a dependency on kubernetes/kubernetes that has a dependency on aws-sdk-go 1.0.8.
kubernetes/contrib also has a dependency on aws-sdk-go 1.0.9 or higher.

Update aws-sdk-go to latest version to make everyone happy.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36023)

### CODE REVIEW

**Comment by jbeda** [comment]
This is jumping all the way to v1.4.20-8.  That is a pretty big change.  What type of testing/verification do we have on this?

**Comment by apelisse** [comment]
Honestly, I have no idea. Should I make the change smaller by using a less recent version?

**Comment by jbeda** [comment]
Can we dig up who updated this last and ask them how they tested/validated?  We should find an active AWS user and make sure we won't break them.

@justinsb -- was this you?  Any opinions here?

**Comment by justinsb** [comment]
We should do this for 1.6 (unless there's some reason to do it sooner @apelisse )

aws-sdk-go is reasonably good at not introducing new bugs (and is pretty widely used), so we typically update and rely on e2e.

We should probably update to latest when the branch reopens though (we're currently at 1.5.4)

**Comment by apelisse** [comment]
Well, I'm trying to simplify the dependencies in kubernetes/contrib, and it means this dependency needs to be updated. There is no urgency though, and can wait for 1.5 to be shipped.

**Comment by apelisse** [comment]
I'll mark it as keep open as it might be time to do it, even though it would maybe be better to re-update.

**Comment by justinsb** [comment]
So we managed to get the aws-sdk-go dependency to 1.6.10, so I believe this PR is obsolete now.  Thank you for it though @apelisse !

**Pull request closed without merging**
