### PR TITLE
Allow empty value for env in kubectl run

### LINKED ISSUE #28734: kubectl run --env FOO="" fails, but should not
It should be possible to pass empty environment variables to pods run by env (to clear an env var set inside the image, for example).

    kubectl run ... --env FOO= 

is valid syntax for "set env var FOO to empty string".

### PR DESCRIPTION
**Pull request by dims**
Fixes #28734

### CODE REVIEW

**Comment by dims** [comment]
@smarterclayton : does this PR look ok? please let me know when you get a chance.

**Comment by smarterclayton** [comment]
LGTM

**Comment by dims** [comment]
@smarterclayton Can you please re-add lgtm tag when you get a chance. Thanks!

**Comment by dims** [comment]
@k8s-bot test this issue: #30132

**Pull request merged**
