### PR TITLE
fix kubectl wait with no resource name provided

### LINKED ISSUE #69039: kubectl wait fails for jobs with metadata.generateName
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:

I created a job with metadata.generateName twice and waited for completion, but got:

    panic: interface conversion: runtime.Object is *unstructured.UnstructuredList, not *unstructured.Unstructured

**What you expected to happen**:

kubectl to wait for the last job to complete.

**How to reproduce it (as minimally and precisely as possible)**:

    kubectl create -f job.yaml
    kubectl create -f job.yaml
    kubectl wait --for=condition=complete -f job.yaml

job.yaml (shortened):

    apiVersion: batch/v1
    kind: Job
    metadata:
      generateName: my-job-

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.3
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by CaoShuFeng**
Fixes: https://github.com/kubernetes/kubernetes/issues/69039

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by juanvallejo** [comment]
/lgtm

cc @soltysh for approval

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
