### PR TITLE
apimachinery util/diff cleanups

### PR DESCRIPTION
**Pull request by thockin**
I saw this in looking at a different PR and could not resist cleaning up.

I'd like to replace `ObjectGoPrintSideBySide` too, but that needs more attention.

/kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Review by logicalhan — COMMENTED** [review]
/lgtm
/approve

**Comment by thockin** [comment]
Rebased and merge-conflicts resolved.

**Comment by bart0sh** [comment]
/lgtm

@thockin pkg/util/diff/diff.go:ObjectReflectDiff became unused. Any plans to remove/deprecate it?

**Comment by thockin** [comment]
These functions are part of the exposed API, so I think we'll leave them for now.

**Pull request merged**
