### PR TITLE
Add preconditions to pod/rs update retry func

### PR DESCRIPTION
**Pull request by janetkuo**
#22388; Follow up #22384

@kubernetes/sig-config

### CODE REVIEW

**Comment by janetkuo** [comment]
@bgrant0607 somehow the comment is gone with the commit being updated. I changed `applyUpdate` to return error and put the precondition check in it. We'll still ignore precondition violated error like how we handle not found error. PTAL.

**Comment by bgrant0607** [comment]
Yes, comments on commits that are blown away by rebases are hard to find again.

**Comment by bgrant0607** [comment]
LGTM. Thanks!

**Comment by eparis** [comment]
This PR is already included in the release-1.2 branch and does not require cherrypick-ing

**Pull request merged**
