### PR TITLE
fix err message in storage extensions

### PR DESCRIPTION
**Pull request by xilabao**
**Release note**:

```release-note
`NONE`
```

### CODE REVIEW

**Comment by deads2k** [comment]
@k8s-bot ok to test

**Comment by deads2k** [comment]
@pwittrock how do we add @xilabao to the auto-testing group of people?

**Comment by xilabao** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by deads2k** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Pull request merged**
