### PR TITLE
Backport e2e Image Override Changes

### PR DESCRIPTION
**Pull request by r4f4**
Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

**What type of PR is this?**

**What this PR does / why we need it**: Enables Openshift CI on s390x

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: NONE

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by neolit123** [comment]
@r4f4 1.16 is still in support, but was this change requested by a maintainer?
where is the PR that merged these changes in master?
is the change present in 1.17 and 1.18 already?

**Comment by r4f4** [comment]
> @r4f4 1.16 is still in support, but was this change requested by a maintainer?
> where is the PR that merged these changes in master?
> is the change present in 1.17 and 1.18 already?

@neolit123 These changes are in master (it's where we backported them from) as well as in 1.17 and 1.18. We need them in 1.14, 1.15 and 1.16 because they impact the Openshift versions in which we need to run CI and use the image override feature.

**Comment by dbenoit17** [comment]
Here are the two patches from master that this PR is based on.

kubernetes/kubernetes@302e9d9#diff-d511d08b2cdc3d78d9e75c3c131ed2ce
kubernetes/kubernetes@2dab911#diff-d511d08b2cdc3d78d9e75c3c131ed2ce

**Comment by mkumatag** [comment]
> Here are the two patches from master that this PR is based on.
> 
> [302e9d9#diff-d511d08b2cdc3d78d9e75c3c131ed2ce](https://github.com/kubernetes/kubernetes/commit/302e9d9f6b2c510ef70314784592521f39ff9637#diff-d511d08b2cdc3d78d9e75c3c131ed2ce)
> [2dab911#diff-d511d08b2cdc3d78d9e75c3c131ed2ce](https://github.com/kubernetes/kubernetes/commit/2dab911ac296ae7c94e1191ce3aa37bbdfd974a8#diff-d511d08b2cdc3d78d9e75c3c131ed2ce)

Here are the PRs pointing these commits:

https://github.com/kubernetes/kubernetes/pull/74703 - its already present in the 1.16 branch
https://github.com/kubernetes/kubernetes/pull/81093 - This merged in 1.17 release and can be merged!

@neolit123 not sure if 1.16 is still open for the merge, if yes - second PR can be cherry-pick which is a low impactful to the code.

@dbenoit17 But this PR contains some more extra code, which needs to pushed first in the master branch and later release branches if required.

**Comment by dbenoit17** [comment]
@mkumatag Thanks for finding those.  We can close this and open a cherry-pick request on that other branch.  We should also refactor out the additional changes and submit them as a separate PR.

**Comment by r4f4** [comment]
Closing this in favour of a cherry-pick request. Thanks.

**Pull request closed without merging**
