### PR TITLE
Fix typo in comment

### PR DESCRIPTION
**Pull request by rowleyaj**

### CODE REVIEW

**Comment by rowleyaj** [comment]
@xiangpengzhao not sure whats happening with this but I'm hoping the test failures are unrelated to this change since it's only in a comment :/ ?

**Comment by rowleyaj** [comment]
Wow thanks merge robot... I'm honestly surprised this hasn't been merged already. It was a copypasta error that I came across whilst I was reviewing the code to determine how Kubernetes tags the resources it creates.

The last run of the tests failed - as has every run prior. Always on unrelated things, and different each time.

Result | FAILURE
-- | --
Tests | 1 failed / 5500 succeeded
Started | 2017-09-30 00:45 BST
Elapsed | 18m26s

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/50923/pull-kubernetes-unit/56033/

Looking at https://github.com/rowleyaj/kubernetes/blob/5d94c2014a91239f33ec19fd855f899558ca50f5/pkg/cloudprovider/providers/aws/OWNERS it seems like the people to mention here would be:

approvers:
- @justinsb
- @zmerlynn
reviewers:
- @gnufied
- @jsafrane
- @justinsb
- @zmerlynn

Is there anyway to get this merged, or do I have to have the luck of the draw to make the tests pass first?

**Comment by xiangpengzhao** [comment]
I believe the test failure is a flake.

**Comment by jsafrane** [comment]
/assign @justinsb 
for approval
(we really need more approvers for AWS code...)

**Pull request merged**
