### PR TITLE
kubelet/dockertools: Remove dockerContainerCommandRunner.

### PR DESCRIPTION
**Pull request by yifan-gu**
Replace with docker manager.

Will remove `kubelet.runner` after this.

@dchen1107 @vmarmol

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM. Will merge once travis or shippable is green

**Comment by yujuhong** [comment]
Just out of curiosity, logistically, is there a reason why we want to keep a separate `ContainerCommandRunner` interface?

**Comment by yifan-gu** [comment]
@yujuhong I don't think so. Should be removed later

**Comment by yujuhong** [comment]
SGTM.

**Pull request merged**
