### PR TITLE
Update old local tests to use general host executor and local test resource manager

### LINKED ISSUE #71237: Update local PV tests to use the new storage test framework
**What would you like to be added**:
We've been refactoring the storage e2e tests to be plugin-agnostic.  We should migrate as many local PV tests to use it as much as possible, and maybe even consider converting local PV test cases to be plugin-agnostic if it makes sense.

There are still major changes going on in this area right now though.  We should wait until https://github.com/kubernetes/kubernetes/pull/70862 and https://github.com/kubernetes/kubernetes/pull/70992 have merged.

@kubernetes/sig-storage-feature-requests 

/kind feature

### PR DESCRIPTION
**Pull request by cofyc**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Update persistent_volumes-local.go to use utils.HostExec/utils.LocalTestResourceManager.
This simplifies the code and makes it more maintainable.

**Which issue(s) this PR fixes**:

Fixes #71237 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
cc @jsafrane @gnufied

**Comment by msau42** [comment]
/lgtm cancel
looks like there's some build failure

**Comment by cofyc** [comment]
The new test I added in https://github.com/kubernetes/kubernetes/pull/74716 needs to be updated. I'll fix soon.

**Comment by cofyc** [comment]
@jsafrane @msau42 Fixed.

**Pull request merged**
