### PR TITLE
Automated cherry pick of #63894: Bump grpc max message size for docker service

### PR DESCRIPTION
**Pull request by dims**
Cherry pick of #63894 on release-1.10.

#63894: Bump grpc max message size for docker service

### CODE REVIEW

**Comment by nikhita** [comment]
/assign @MaciekPytel 
for cherry-pick approval

**Comment by MaciekPytel** [comment]
/hold
For 1.10.6

**Comment by nikhita** [comment]
Closing and reopening to retrigger prow to remove the `do-not-merge/cherry-pick-not-approved` label.

/assign

**Comment by nikhita** [comment]
/unassign

The labels are fixed now. :+1:

**Comment by nikhita** [comment]
@yujuhong @Random-Liu ptal.

**Comment by dims** [comment]
Looks like there isnt much interest. closing

**Pull request closed without merging**
