### PR TITLE
tests: Splits hostname from DNS test

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind failing-test

/area conformance

/sig testing
/sig windows

**What this PR does / why we need it**:

At the moment, Windows cannot mount individual files into Containers, which means
that the Kubelet-managed hosts file cannot be mounted into the Container, causing
the ``[sig-network] DNS should provide DNS for pods for Hostname and Subdomain``
test to fail.

The test mentioned test has ``/etc/hosts`` file entry checks. This commits separates the DNS
check and the ``/etc/hosts`` checks into two tests.

**Which issue(s) this PR fixes**:

Related issue: #70189
Related issue: #73425

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by johnbelamaric** [comment]
When these are promoted to compliance, there will need to be an explanation for the LinuxOnly tag plus a link to the windows KEP section with details.

/lgtm

**Comment by johnbelamaric** [comment]
Is it the checking for the hostname looking at /etc/hosts that is the problem, or the actual functionality does not work on Windows? That is, if it works but the way we checked was wrong, can we fix that with the agnhost image?

**Comment by bclau** [comment]
> 
> 
> Is it the checking for the hostname looking at /etc/hosts that is the problem, or the actual functionality does not work on Windows? That is, if it works but the way we checked was wrong, can we fix that with the agnhost image?

The actual functionality does not work on Windows. Basically, the ``/etc/hosts`` file should be mounted by Kubelet, but mounting individual files is not  supported on Windows. For more details on this, see [1].

That is something that will eventually be fixed on Windows once ContainerD support is added, allowing us to be able to do this. When that is done, we will have to switch to the agnhost image.

[1] https://github.com/kubernetes/community/pull/3521

**Comment by johnbelamaric** [comment]
Ok, sounds good.

/priority important-soon

**Review by MrHohn — APPROVED** [review]
/approve

**Comment by mgdevstack** [comment]
Subdomain resolution is verified for a headless service based on it's FQDN but not actual subdomain name. On linux platforms, A subdomain `default-subdomain.my-namespace.svc.cluster.local` MUST be resolvable for a headless service named `default-subdomain` by serving "A" records at that name.

If above subdomain resolution is not supported on Windows, does it make sense to add [LinuxOnly] to subdomain e2e with following code addition?
```
hostFQDN := fmt.Sprintf("%s.%s.%s.svc.%s", podHostname, serviceName, f.Namespace.Name, framework.TestContext.ClusterDNSDomain)
subdomain := fmt.Sprintf("%s.%s.svc.%s", serviceName, f.Namespace.Name, framework.TestContext.ClusterDNSDomain)
namesToResolve := []string{hostFQDN, subdomain}
```

**Comment by bclau** [comment]
> 
> 
> Subdomain resolution is verified for a headless service based on it's FQDN but not actual subdomain name. On linux platforms, A subdomain `default-subdomain.my-namespace.svc.cluster.local` MUST be resolvable for a headless service named `default-subdomain` by serving "A" records at that name.
> 
> If above subdomain resolution is not supported on Windows, does it make sense to add [LinuxOnly] to subdomain e2e with following code addition?
> 
> ```
> hostFQDN := fmt.Sprintf("%s.%s.%s.svc.%s", podHostname, serviceName, f.Namespace.Name, framework.TestContext.ClusterDNSDomain)
> subdomain := fmt.Sprintf("%s.%s.svc.%s", serviceName, f.Namespace.Name, framework.TestContext.ClusterDNSDomain)
> namesToResolve := []string{hostFQDN, subdomain}
> ```

The subdomain ``default-subdomain.my-namespace.svc.cluster.local`` should also be resolvable on Windows.

**Pull request merged**
