### PR TITLE
Automated cherry pick of #101950: Make watch order conformance test reliable

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #101950 on release-1.21.

#101950: Make watch order conformance test reliable

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/release-managers

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
