### PR TITLE
serve_hostnames: fix compilation

### PR DESCRIPTION
**Pull request by mikedanese**
this and #35373 allows `bazel build //test/...`

@ixdy @spxtr

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35467)

### CODE REVIEW

**Comment by spxtr** [comment]
Why are the actual code changes necessary?

**Comment by mikedanese** [comment]
@spxtr confused at what you mean. c is undefined and the client api changed since this was submitted. I don't know how it got in this state but it's totally broken. I guess i could look at the blame.

**Comment by spxtr** [comment]
Wat.

**Comment by spxtr** [comment]
Okay looks fine but I'm worried that we had such obviously broken code sitting around.

/lgtm

**Comment by ixdy** [comment]
@spxtr we don't build everything in the repo in CI, so it's possible for nonessential stuff to break. We used to `go install ./...`, which probably would have caught this, but that's slow.

**Pull request merged**
