### PR TITLE
[release-1.27] releng/go: Bump images, versions and deps to use Go 1.20.6

### PR DESCRIPTION
**Pull request by xmudrii**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

- Bump images, versions and deps to use Go 1.20.6

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/release/issues/3148

#### Does this PR introduce a user-facing change?
```release-note
Kubernetes is now built with Go 1.20.6
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

/assign @saschagrunert @cpanato 
cc @kubernetes/release-engineering

### CODE REVIEW

**Comment by liggitt** [comment]
/lgtm
/approve

is master already updated to 1.20.6?

**Review by cpanato — APPROVED** [review]
from releng:
/lgtm

**Pull request merged**
