### PR TITLE
Add WrapUpdatedObjectInfo helper

### PR DESCRIPTION
**Pull request by liggitt**
This makes it easier to attach checks/transformations to the updated object in storage Update functions, while still keeping the data flow intact (so admission, patch, and other injected checks continue to work as intended), without needing to do anything tricky to get the updated object out of the UpdatedObjectInfo introduced in https://github.com/kubernetes/kubernetes/pull/25787

This is especially useful when one storage is delegating to another, but wants its checks to be run in the heart of the eventual GuaranteedUpdate call.

### CODE REVIEW

**Comment by liggitt** [comment]
cc @ericchiang @caesarxuchao

**Comment by ericchiang** [comment]
Awesome, this works great

**Comment by caesarxuchao** [comment]
An example use case: https://github.com/kubernetes/kubernetes/pull/25634#discussion_r64507472

**Comment by caesarxuchao** [comment]
LGTM. Thanks.

**Pull request merged**
