### PR TITLE
support using dnsconfig defined in pod with highest priority

### LINKED ISSUE #78206: Optimizing the Pod's DNS Searches Priority
**The Pod.Spec.DNSConfig.Searches must be the highest search priority in Pod's DNS configuration.**
The field of Pod.Spec.DNSConfig is the custom configuration of Pod's DNS, so it must be the highest priority when setting Pod's DNS.

**What happened**:

For now, the Pod's DNS searches priority is: 

1. In-Cluster Service domains' searches
2. Node(Host)'s searches
3. the Pod.Spec.DNSConfig.Searches.

**What you expected to happen**:

The Pod's DNS searches priority should be: 

1. The Pod.Spec.DNSConfig.Searches.
2. In-Cluster Service domains' searches
3. Node(Host)'s searches

**How to reproduce it (as minimally and precisely as possible)**:

The Kubernetes In-Cluster domain is *cluster.local*, and the Node resolv.conf file has searches *my-domain.com*, When I create a Pod with Pod.Spec.DNSConfig.Searches=[zone1.cluster.local, zone1.my-domain.com], then the Pod's DNS searches are: *bar.svc.cluster.local, svc.local.local, cluster.local, my-domain.com, zone1.cluster.local, zone1.my-domain.com*. Then the Pod's App can not got the best resolved IPs when try to resolve the datacenter domain *global-service*, because it try to resolve with the domain *global-service.my-domain.com*, while we think it must try to resolve *global-service.zone1.my-domain.com* firstly.

The example Pod is ClusterFirst DNS type, and the Host DNS type also has this issue.

**Anything else we need to know?**:

Nothing yet.

**Environment**:

The latest version Kubernetes also has this issue.

### PR DESCRIPTION
**Pull request by fankangbest**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

/kind bug
/kind feature

**What this PR does / why we need it**:
There are three fields in pod's dnsconfig: Nameservers, Searches and Options. Now Options will overwrite the existing dnsconfig. So Nameservers and Serches also should get higher priority than existing dnsconfig.

**Which issue(s) this PR fixes**:

Fixes #78206

**Special notes for your reviewer**:
There is a want that we use dnsconfig defined in pod firstly. This PR can support this need.
**Does this PR introduce a user-facing change?**:

```release-note
Support to use Nameservers and Searches in pod's dnsconfig with first priority.
```

### CODE REVIEW

**Comment by alejandrox1** [comment]
@fankangbest thank you for working on this! let's get this merged.
Could you please rebase?

/cc @kubernetes/sig-network-pr-reviews 
/cc @kubernetes/sig-node-pr-reviews 
ptal
/cc

/remove-area e2e-test-framework
/remove-sig testing
/priority important-soon
/milestone v1.17
/remove-sig api-machinery
/remove-sig apps
/remove-sig auth
/remove-sig cluster-lifecycle
/remove-sig scheduling
/remove-sig storage

**Comment by alejandrox1** [comment]
actually, this is mostly network so let me clean it up a bit more...
/remove-area kubectl
/remove-area code-generation
/remove-area dependency
/remove-area test
/remove-area provider/gcp

**Comment by alejandrox1** [comment]
/assign @mrhohn @bowei 
ptal

**Review by MrHohn — COMMENTED** [review]
Changing the behavior at the global level would need more discussion, and probably need to be written down as a KEP. It is not entirely clear if this model (pod dns config over host dns config) would be a better fit in all use cases, and whether a new mechanism is desired to allow tweaking this at a more granular level.
cc @prameshj

**Comment by alejandrox1** [comment]
/milestone clear
/hold
Based on MrHohn's comment

@fankangbest was there a KEP for this?

**Comment by alejandrox1** [comment]
@fankangbest any updates on this?

**Pull request closed without merging**
