### PR TITLE
Fix 404 url on k/kubectl/docs

### PR DESCRIPTION
**Pull request by ahmadnurus**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Partial #85495

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by tanjunchen** [comment]
@prksu Numbers 1 to 12, I have modified and merged, but I think your  https://gitbookio.gitbooks.io/docs-toolchain/setup.html  looks better.
can you fix conflicts?Thanks!

**Comment by prksu** [comment]
@tanjunchen great. i don't see your PR before.
i just fix merge conflict.

**Comment by tanjunchen** [comment]
/lgtm
@liggitt  Thanks

**Comment by liggitt** [comment]
the specified link does not 404, and I would prefer not to deep link to websites we don't control... deep-links are more likely to 404 in the future

/close

**Pull request closed without merging**
