### PR TITLE
fix the doc about generateName conflict

### LINKED ISSUE #107790: The error code for GenerateName conflict shouldn't be 409
### What happened?

The error code of `pods "pod-gvh4t" already exists, the server was not able to generate a unique name for the object`  is 409.
Is this an expected behavior? The doc seems to say no:
> If this field is specified and the generated name exists, the server will
NOT return a 409 - instead, it will either return 201 Created or 500 with Reason
ServerTimeout indicating a unique name could not be found in the time allotted, and the client
should retry (optionally after the time indicated in the Retry-After header).

https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L134-L137

`NewGenerateNameConflict` seems to create `StatusError` which error code is 409.

https://github.com/kubernetes/kubernetes/blob/fbdd0d7b4165bc5a677d45e4dc693e3260297bfa/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go#L175-L190

### What did you expect to happen?

The error code of `pods "pod-gvh4t" already exists, the server was not able to generate a unique name for the object`  isn't 409. Or, the doc doesn't say "If this field is specified and the generated name exists, the server will NOT return a 409".

### How can we reproduce it (as minimally and precisely as possible)?

Create a large number of Pods with generateName, and cause name conflicts.

### Anything else we need to know?

Just question: if the API is correct in returning 409 for a GenerateName-conflict, how do we determine that error? We want to retry when GenerateName conflict returns in most cases because the retry may solve this conflict.

### Kubernetes version

latest master (maybe after https://github.com/kubernetes/kubernetes/pull/104699?)

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

The error code for GenerateName conflict is 409, so the current doc for generateName is incorrect.

#### Which issue(s) this PR fixes:

Fixes #107790

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sanposhiho** [comment]
This PR is definitely needed, but hard to get everyone's review 😓 
/assign @lavalamp

**Comment by lavalamp** [comment]
/lgtm
/approve

Thanks!

**Comment by sanposhiho** [comment]
I'll try to regenerate the files later.

/hold

**Comment by sanposhiho** [comment]
@lavalamp 
Could you review it again? (just rebased and re-generated files)

**Comment by sanposhiho** [comment]
@lavalamp Thanks.
/unhold

**Pull request merged**
