### PR TITLE
fix #46271: returning nil ttl will keep the same value

### LINKED ISSUE #46271: [Bug] Returning nil TTL will not keep the same value as the comment mentioned
Hi,

As the [comment](https://github.com/kubernetes/apiserver/blob/master/pkg/storage/interfaces.go#L174) mentioned, when `tryUpdate UpdateFunc` returns a nil TTL in method `GuaranteedUpdate`, the TTL attached to the key will not change. But in current codes under `pkg/storage/etcd3`, the TTL will be unset, because [it](https://github.com/kubernetes/apiserver/blob/master/pkg/storage/etcd3/store.go#L498) will return 0 when `ttlPtr` is nil. And a zero TTL will finally unset the TTL.

The following test case will fail as `timeout` without key deleted:
```
func TestGuaranteedUpdateWithNilTTL(t *testing.T) {
	ctx, store, cluster := testSetup(t)
	defer cluster.Terminate(t)

	input := &example.Pod{ObjectMeta: metav1.ObjectMeta{Name: "foo"}}
	key := "/somekey"

	out := &example.Pod{}
	err := store.GuaranteedUpdate(ctx, key, out, true, nil,
		func(_ runtime.Object, _ storage.ResponseMeta) (runtime.Object, *uint64, error) {
			ttl := uint64(1)
			return input, &ttl, nil
		})
	if err != nil {
		t.Fatalf("Create failed: %v", err)
	}

	err = store.GuaranteedUpdate(ctx, key, out, true, nil,
		func(_ runtime.Object, _ storage.ResponseMeta) (runtime.Object, *uint64, error) {
			input.Namespace = "update"
			return input, nil, nil
		})
	if err != nil {
		t.Fatalf("Update failed: %v", err)
	}

	w, err := store.Watch(ctx, key, out.ResourceVersion, storage.Everything)
	if err != nil {
		t.Fatalf("Watch failed: %v", err)
	}
	testCheckEventType(t, watch.Deleted, w)
}
```

I think it is a bug. And it should be fixed.

### PR DESCRIPTION
**Pull request by wu8685**
fix #46271

### CODE REVIEW

**Comment by wu8685** [comment]
@k8s-bot ok to test

**Comment by wojtek-t** [comment]
@xiang90 @hongchaodeng - can one of you please take a look?

**Comment by wojtek-t** [comment]
@xiang90 @hongchaodeng - can one of you please take a look?

**Comment by hongchaodeng** [comment]
@k8s-bot ok to test

**Comment by hongchaodeng** [comment]
@wu8685 
Can you change commit message and title to "etcd3: xxx".

This is good catch. The interface is inconsistent. Although I guess it doesn't matter, only events will give TTL, and it always return the TTL.

Please fix the test and lgtm

**Comment by wu8685** [comment]
do I need `ok to test` again to trigger these tests?

**Comment by wu8685** [comment]
seems there are some problem to trigger the tests

**Comment by wu8685** [comment]
@hongchaodeng could you comment `/retest` to trigger the tests. Thanks

**Comment by wu8685** [comment]
@wojtek-t @hongchaodeng 
could you comment `/retest` to help me trigger the test?

**Pull request closed without merging**
