### PR TITLE
Use http's basic auth instead of manual encoding

### PR DESCRIPTION
**Pull request by krousey**
In some places, we were encoding/decoding basic auth headers manually. I moved this to use http's native basic auth features. I also deleted keystone_test.go because it wasn't testing the keystone package, and what it was testing was already being tested by basic_auth_test.go

@kubernetes/goog-csi

### CODE REVIEW

**Comment by krousey** [comment]
@k8s-bot e2e test this please

**Comment by krousey** [comment]
@k8s-bot e2e test this

**Comment by caesarxuchao** [comment]
LGTM. Thanks.

**Comment by krousey** [comment]
@k8s-bot test this

**Pull request merged**
