### PR TITLE
Enable support for AWS LB

### PR DESCRIPTION
**Pull request by justinsb**
The (non-AWS-specific) change here is that we pass []*api.ServicePort into the LoadBalancer provider.

We then use this to implement AWS Load Balancers.  AWS needs the full ServicePort because we need to see the NodePort for a LoadBalanced service on AWS, because we can't match on source IP, because ELB (apparently) works by relaying TCP connections.

This also paves the way for e.g. UDP load balancing.

### CODE REVIEW

**Comment by justinsb** [comment]
I saw that had accidentally been using this branch as my integration branch.  I cleaned it up - should hopefully be much easier to review now!  Thanks & sorry!

**Comment by iterion** [comment]
@justinsb looks like you have merge conflicts now. I'm excited to see this merged soon!

**Comment by thockin** [comment]
needs rebase, but LGTM otherwise

**Comment by justinsb** [comment]
Rebased and looking good on my e2e testing on AWS!

**Pull request merged**
