### PR TITLE
kubeadm: too early return for reset with dry-run or force mode

### PR DESCRIPTION
**Pull request by chendave**
/kind bug

Due to the change from this: https://github.com/kubernetes/kubernetes/commit/8aeee521e60a4063d825e852e85bf0674d800123, `RunRootCheckOnly` could be missed if it's reset with dry-run or force.

Signed-off-by: Dave Chen <dave.chen@arm.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
cc @neolit123 @pacoxu 

sorry, blame on my previous change https://github.com/kubernetes/kubernetes/commit/8aeee521e60a4063d825e852e85bf0674d800123, we missed the check on the privileged user when the user ack with 'y' or 'yes'.

**Comment by neolit123** [comment]
> cc @neolit123 @pacoxu
> 
> sorry, blame on my previous change [8aeee52](https://github.com/kubernetes/kubernetes/commit/8aeee521e60a4063d825e852e85bf0674d800123), we missed the check on the privileged user when the user ack with 'y' or 'yes'.

can please send pr fix?

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
