### PR TITLE
Make configFactory private

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

Fix TODO make this private if possible, so that only its interface is externally used.
I have check the use of configFactory and it is safe to make it private.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wackxu** [comment]
@timothysc @davidopp Please take a look at this PR, it needs your approve, thanks.

**Comment by timothysc** [comment]
@k8s-bot test this #IGNORE

**Review by timothysc — APPROVED** [review]
/lgtm 

/approve

**Pull request merged**
