### PR TITLE
Fix the typo in translations' README.md

### PR DESCRIPTION
**Pull request by warmchang**
**What this PR does / why we need it**:
Tiny fix the typo in README file.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
No issues.

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test
/release-note-none
/lgtm

**Comment by warmchang** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
ref: https://github.com/kubernetes/kubernetes/issues/46827

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-unit test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by warmchang** [comment]
@cblecker , past the pull-kubernetes-unit and pull-kubernetes-federation-e2e-gce test, could you please 
 approve & merge it?

**Comment by cblecker** [comment]
The next step with this is approval from @brendandburns

**Pull request merged**
