### PR TITLE
chore(kubelet): simpler createAndInitKubelet func

### PR DESCRIPTION
**Pull request by jackfrancis**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This PR simplifies the way that the `cmd/kubelet/app` package hands off its `kubeServer` configuration (of type `*options.KubeletServer`) to the local `createAndInitKubelet` function. Rather than dereferencing the required set of properties that are eventually sent to `pkg/kubelet --> NewMainKubelet()` we can simply pass along the `kubeServer` to the private func, reducing a bit of passing and receiving overhead in `cmd/kubelet/app`.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by ehashman — COMMENTED** [review]
:+1: but we might want to wait until between releases to do this refactor in case it breaks in-flight work.

/priority backlog
/triage accepted
/lgtm

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by bobbypage** [comment]
/lgtm

Thanks for cleanup!

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by jackfrancis** [comment]
@mrunalp @pacoxu hopefully this is a quick review

this is a simple PR I've had open for a while that makes ongoing maintenance, such as this change in this PR, easier:

https://github.com/kubernetes/kubernetes/commit/0819451ea678a6da8d78afeff12173273e711799#diff-3a14a9838132c6668f4d100c26afa05b471b149c469edfece9b84fcd058c8a4bL1117

**Comment by jackfrancis** [comment]
@mrunalp @pacoxu this is a (hopefully) simple housekeeping change that is a candidate for 1.25 milestone

**Review by pacoxu — APPROVED** [review]
/lgtm

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
