### PR TITLE
e2e: use regexp to parse kubelet /metrics output

### PR DESCRIPTION
**Pull request by yujuhong**

### CODE REVIEW

**Comment by yujuhong** [comment]
I am using these chagnes for my own testing.
  - The first commit uses regexp to parse the output. String parsing is still hacky, and this just makes it a little less brittle.
  - The second commit extends KubeletMetric to record count/sum for some particular use cases. 

 Not sure if any of these is worth checking in, but thought I'd upload them just in case.

**Comment by ixdy** [comment]
This PR is over a month old and needs rebase.

**Comment by ixdy** [comment]
ping - is this still being worked on?

**Comment by yujuhong** [comment]
I think it makes the tests slightly more reliable/readable, but it doesn't seem like there is enough interest. I will close it for now.

**Pull request closed without merging**
