### PR TITLE
Automated cherry pick of #114459: fix double lock and excercise its codepath in tests

### PR DESCRIPTION
**Pull request by alexzielenski**
Cherry pick of #114459 on release-1.26.

#114459: fix double lock and excercise its codepath in tests

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fixes a 1.26 regression in the alpha Aggregated Discovery feature that can cause a stuck apiserver if an aggregated apiservice returned 304 Not Modified for aggregated discovery information
```

### CODE REVIEW

**Comment by alexzielenski** [comment]
/hold cancel

master pr merged

but still needs cherry pick approved

**Comment by liggitt** [comment]
Only 1.26

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
