### PR TITLE
Update the error returned from fixture.go on unknown patch type.

### PR DESCRIPTION
**Pull request by vagababov**
Currently the type is not returned.

**What type of PR is this?**
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
The error is missing the passed in type complicating test debugging.

```release-note
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
LGTM.

Can you squash?
Could you also remove the release note? The fix is too trivial for a release note.

Thanks.

**Comment by vagababov** [comment]
> LGTM.
> 
> Can you squash?
> Could you also remove the release note? The fix is too trivial for a release note.
> 
> Thanks.

Sure, can squash.
I think release not was required by the Prow. I didn't add it at first.

**Comment by vagababov** [comment]
/test pull-kubernetes-verify
getting closer

**Comment by caesarxuchao** [comment]
@vagababov , see https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md
```
For pull requests that don't need to be mentioned at release time, use the /release-note-none Prow command to add the release-note-none label to the PR. You can also write the string "NONE" as a release note in your PR description:
```

I took the liberty to remove the release note and applied the label.

**Comment by vagababov** [comment]
Thanks, so it says `merging is blocked`. Will prow merge this or I need something else?

**Comment by caesarxuchao** [comment]
Prow will merge it. "Merging is blocked" means that we don't have permissions to manually merge it.

**Comment by vagababov** [comment]
Thanks!

**Comment by vagababov** [comment]
I had to re-merge

**Pull request closed without merging**
