### PR TITLE
Add GOMAXPROCS in a few more places

### PR DESCRIPTION
**Pull request by lavalamp**
Follow up to #4240.

...Something not in this PR broke doc generation...

### CODE REVIEW

**Comment by vmarmol** [comment]
LGTM

**Comment by lavalamp** [comment]
...and doc generation is not broken, just my GOPATH. This should be good to go.

**Comment by vmarmol** [comment]
Thanks for the double-check :) will merge on green.

**Comment by smarterclayton** [comment]
So this is to prevent people from being able to set GOMAXPROCS?

**Comment by lavalamp** [comment]
No, this is so that if someone parallelizes something, it'll actually have an effect. We could also use a command line parameter to set the number of os threads we use, but this should be OK for the moment.

Nothing stops people from setting it to a higher value later, of course.

**Pull request merged**
