### PR TITLE
Cleanup ginkgo declarative naming in E2Es

### PR DESCRIPTION
**Pull request by jayunit100**
quinton noted eariler that we need to follow ginkgo conventions for test reporting this is pretty importatnt. so lets clean this up before it gets out of control   :).     i think this covers  the only 3   ones i found.  there might be a couple other stragglers

### CODE REVIEW

**Comment by yujuhong** [comment]
@jayunit100, what are the ginkgo conventions? Is it documented anywhere?

**Comment by jayunit100** [comment]
in general, 

(1) each test should be "declared" in such a way that, when concatenated with the `It` segments, we get a complete sentence.  For example: 

```
_ = Declare("The cow", func() {
It("should be nice") })
/// some tests
```

**Comment by yujuhong** [comment]
It'd be nice to document the convention somewhere so that people can follow. @quinton-hoole, could you suggest a place for that?

@jayunit100, you'd need to rebase.

**Comment by quinton-hoole** [comment]
Good idea Yuju.  We should probably add a line or two here, similar to "common go style mistakes".

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/collab.md

Here are a few useful links, although I should probably condense them into something easier to follow:

http://onsi.github.io/ginkgo/#structuring-your-specs
http://en.wikipedia.org/wiki/Behavior-driven_development#Specification_as_a_ubiquitous_language

Opened #8515 to track this.

**Comment by quinton-hoole** [comment]
This PR LGTM!  Thanks so much for the tidy-up Jay.

**Comment by erictune** [comment]
@jayunit100 needs a quick rebase, then it should be good to merge.

**Comment by jayunit100** [comment]
Ok sorry I'm juggling somw thing but I'll get to this tonite unless someone
beats me to it :)

**Comment by erictune** [comment]
no prob.

**Comment by bgrant0607** [comment]
please rebase

**Comment by jayunit100** [comment]
cleaning now............

**Comment by jayunit100** [comment]
ok rebased

**Comment by bgrant0607** [comment]
Broke e2e and was reverted. 

Namespaces can't have spaces.

```
-		testingNs, err = createTestingNS("kubectl", c)
+		testingNs, err = createTestingNS("Kubectl client", c)
```

**Pull request merged**
