### PR TITLE
Add resync to the scheduler watch caches.

### PR DESCRIPTION
**Pull request by brendandburns**
@lavalamp @wojtek-t

### CODE REVIEW

**Comment by brendandburns** [comment]
I'm going to self-merge this so that we can let it soak in the tests overnight and see if it fixes things.

If it doesn't fix anything, we can revert it in the morning.

**Comment by wojtek-t** [comment]
@brendandburns - what is it supposed to fix? I'm really against having such small resync periods, because it will significantly affect performance.

**Comment by davidopp** [comment]
I agree with @wojtek-t . If resync ever fixes a problem, it means there is an underlying correctness bug that we are hiding. I do not think resync is the right solution.

**Comment by wojtek-t** [comment]
@brendandburns @lavalamp - did we revert this PR? If not, I think we should do it.

**Comment by davidopp** [comment]
+1

**Comment by wojtek-t** [comment]
I've created #17004

**Comment by DanielJoyce** [comment]
Would be nice if we had a way to tickle the scheduler to reallocate pods that should otherwise fit...

**Pull request merged**
