### PR TITLE
Update e2e csi images to k8s.gcr.io

### PR DESCRIPTION
**Pull request by msau42**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Switch csi e2e test images from using k8s-staging to k8s.gcr.io

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by msau42** [comment]
There is no hostpath image available in k8s.gcr.io yet. We need to release a new hostpath driver version. cc @pohly

**Comment by pohly** [comment]
> There is no hostpath image available in k8s.gcr.io yet. We need to release a new hostpath driver version. cc @pohly

Looks like 1.4.0 was created three days ago: https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/US/sig-storage/hostpathplugin@sha256:d2b357bb02430fee9eaa43b16083981463d260419fe3acb2f560ede5c129f6f5/details?tab=info

**Review by pohly — APPROVED** [review]
/lgtm

**Pull request merged**
