### PR TITLE
Remove red rectangles in quoted region in gh-pages

### PR DESCRIPTION
**Pull request by janetkuo**
Remove tabs inside ```yaml of *.md files in the hope of fixing #16391

cc @bgrant0607 @caesarxuchao @krousey @nikhiljindal

### CODE REVIEW

**Comment by thockin** [comment]
Is this somethign we can munge?

**Comment by bgrant0607** [comment]
LGTM, thanks

**Comment by bgrant0607** [comment]
@thockin We should be able to munge it, but we don't fully understand the problem yet.

**Comment by bgrant0607** [comment]
#16541 was filed re. munger

**Comment by bgrant0607** [comment]
Merging.

**Pull request merged**
