### PR TITLE
Automated cherry pick of #69550 upstream release 1.12

### PR DESCRIPTION
**Pull request by tallclair**
**What this PR does / why we need it**:

Automated cherry pick of #69550 upstream release 1.12

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by feiskyer** [comment]
@tallclair Could you add a release note in #69550?

**Review by dougm — COMMENTED** [review]
/lgtm

**Comment by tallclair** [comment]
> @tallclair Could you add a release note in #69550?

Done.

**Pull request merged**
