### PR TITLE
Normalize RepoTags before checking for match

### LINKED ISSUE #52110: 1.8 regression: Can't pull images from docker.io without explicit path on centos/fedora/rhel
https://github.com/kubernetes/kubernetes/pull/51751 bumped the vendored docker library and introduced a regression where pods with images that don't contain an explicit "docker.io/" repo path result in `ErrImagePull` failures.

```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sleep
    - "100"
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
```

Results in the following error:
```
Failed to pull image "busybox": rpc error: code = Unknown desc = no such image: "docker.io/library/busybox:latest"
```

Pod gets `ErrImagePull`

`docker images` shows that the image has been pulled, though not by that name
```
$ docker images | grep busybox
docker.io/busybox                                      latest              d20ae45477cb        2 weeks ago         1.13 MB
```

Changing the image to `docker.io/busybox` in the pod spec corrects the issue.

I think the new code that is changing the behavior is somewhere in here
https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/docker/distribution/reference/normalize.go#L78-L98

`familiarizeName()` is a new function brought in by the bump.

If I checkout the commit before the bump, the problem does not occur.

@derekwaynecarr @DirectXMan12 @dashpole 

related: https://bugzilla.redhat.com/show_bug.cgi?id=1496630

### PR DESCRIPTION
**Pull request by ncdc**
Possible fix. Written quickly. Hacky atm. Needs tests.

Fixes #52110

### CODE REVIEW

**Comment by ncdc** [comment]
If somebody wants to take this over, put a comment in the code why this is happening, add better error checking, and tests, please feel free. I have to go now and will be afk for several hours.

This change is needed for projectatomic-based docker, which sets the `RepoTags` for an image from the docker hub under "library" as e.g. `docker.io/busybox:latest` instead of what upstream docker does (`busybox:latest`). If we normalize each tag from `RepoTags` prior to doing the suffix tests, we'll be working with 2 normalized values instead of just 1 (the image that's passed in was normalized up the call stack).

**Comment by liggitt** [comment]
@miminar, can you take a look as well?

**Comment by dims** [comment]
@ncdc, i picked up your PR and am working on it here:
https://github.com/kubernetes/kubernetes/pull/53161

**Comment by yujuhong** [comment]
> @ncdc, i picked up your PR and am working on it here:
> #53161

Let's close this one to avoid confusion.

**Pull request closed without merging**
