### PR TITLE
Extend the get-cluster.sh script to use sudo if necessary.

### PR DESCRIPTION
**Pull request by brendandburns**

### CODE REVIEW

**Comment by zmerlynn** [comment]
+1, except that it needs to lock for racing gcloud updates. :) https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/jenkins/e2e.sh#L105

(This actually did show up on our Jenkins server already. :/)

**Comment by brendandburns** [comment]
```flock``` doesn't exist on OS X.  I'd rather not do this.  Besides, shouldn't ```gcloud update ...``` handle the locking itself?

**Comment by zmerlynn** [comment]
It should, and I have an internal bug open, but until it does, there's a problem here with racing `gcloud components update` calls. The problem isn't unique to the sudo case, but having this case error out was the last way I had to protect Jenkins from the race.

If you're going to go this route:
* add an env variable as to whether we update gcloud at all (then we can just disable it in Jenkins and leave the update at the top level)
* update GKE as well, or move these to a common function (they're getting pretty large).

**Comment by brendandburns** [comment]
ok, added an environment variable for both GCE and GKE.

ptal
--brendan

**Pull request merged**
