### PR TITLE
Revert "list vm instead of get when getting virtual machine"

### PR DESCRIPTION
**Pull request by chewong**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind feature
> /kind flake

 /kind failing-test

**What this PR does / why we need it**:

Reverting #86817 as it seems like it causes VMAS-related tests to fail

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by chewong** [comment]
@feiskyer FYI I reverted https://github.com/kubernetes/kubernetes/pull/86817 in this PR and pull-kubernetes-e2e-azure-disk works again

**Comment by andyzhangx** [comment]
cc @feiskyer @zqingqing1 
looks like vmas test failure in https://github.com/kubernetes/kubernetes/pull/87122 is due to this PR.
For every azure related change, we need to run all azure e2e tests

**Comment by feiskyer** [comment]
OK, let's revert so as to unblock other PRs.

@chewong could you open an issue and investigate why it would fail in the new issue?

**Review by feiskyer — COMMENTED** [review]
PR needs rebase.

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

/hold for running disk e2e

**Comment by chewong** [comment]
@andyzhangx we currently don't have any presubmit job named `pull-cloud-provider-azure-e2e`/

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve
thanks.

**Pull request merged**
