### PR TITLE
[go1.16] Update to go1.16.10

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature
/area dependency release-eng security

#### What this PR does / why we need it:

Update Kubernetes to go1.16.10 for release 1.22 branch

Tracking issue: https://github.com/kubernetes/release/issues/2304

/assign @dims @justaugustus @saschagrunert 
cc: @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Kubernetes is now built with Golang 1.16.10
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Review by justaugustus — APPROVED** [review]
/lgtm
/approve

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
