### PR TITLE
[Federation] Automate configuring nameserver in cluster-dns for CoreDNS provider

### PR DESCRIPTION
**Pull request by shashidharatd**
Addresses issue #42894 #42822

**Release note**:
```
[Federation] CoreDNS server will be automatically added to nameserver resolv.conf chain When using CoreDNS as dns provider for federation during federation join.
```
cc @madhusudancs @kubernetes/sig-federation-bugs

### CODE REVIEW

**Comment by shashidharatd** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by madhusudancs** [comment]
@shashidharatd as we discussed yesterday, this is targetted for v1.7 right? (I have set the milestone to 1.7 already, but let me know if you think this is for v1.6).

**Comment by shashidharatd** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by shashidharatd** [comment]
ok @madhusudancs, targetting 1.7 should be fine.

**Comment by shashidharatd** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by quinton-hoole** [comment]
I don't yet know enough about how kubedns is deployed in various environments to do a proper review of this, so I'm going to remove myself from the assignee list.  If you want me to study up on kubedns deployments, let me know.

It does strike me as odd that we're adding CoreDNS-specific logic when it's not necessary for other DNS providers.  Is it not possible to use the standard DNS recursion logic here instead, like the other DNS providers?  I'm way out of my depth here, so will discuss it with you in person rather that confuse things here :-)

**Comment by shashidharatd** [comment]
@quinton-hoole, Sorry for the delay in responding to the concern raised by you. Below is the explanation. Hope you agree otherwise would follow the suggestions if any.

> It does strike me as odd that we're adding CoreDNS-specific logic when it's not necessary for other DNS providers. Is it not possible to use the standard DNS recursion logic here instead, like the other DNS providers? I'm way out of my depth here, so will discuss it with you in person rather that confuse things here :-)

CoreDNS is private nameserver and we need additional measures to make sure the federation domain lookups by pods are answered by the CoreDNS server. Here is an blog explaining how to do this currently in kubernetes http://blog.kubernetes.io/2017/04/configuring-private-dns-zones-upstream-nameservers-kubernetes.html

Regarding the CoreDNS-specific logic in kubefed, We did discuss the alternatives previously on this PR. Alternative-1: Implement generically to add a private nameserver to DNS lookup chain (via additional flag to `kubefed` during cluster join.)
Alternative-2: Implicitly add the CoreDNS server to the DNS lookup chain during cluster join(if the CoreDNS DNS provider is used). Here user need not explicitly take care of this, but this introduces little additional burden to kubefed developers.

@madhusudancs, preferred to use Alternative-2 as it is better user experience and User's preferences should always come first than developer's preferences.

**Comment by madhusudancs** [comment]
Reviewed 1 of 8 files at r1, 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[federation/pkg/kubefed/join.go, line 278 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42895#-KkF31PUTRJCX5VdOKU-:-KkF31PUTRJCX5VdOKU0:bdi6rnz) ([raw file](https://github.com/kubernetes/kubernetes/blob/c1cac7d7f36ad9ceb977529158714a31d61b5992/federation/pkg/kubefed/join.go#L278)):*
> ```Go
> 		}
> 		newConfigMap = appendStubDomains(newConfigMap,
> 			cmDep.Annotations[util.FedDNSProvider],
> ```

I think this isn't sufficient. kubefed panics if they keys don't exist. So you need the equivalent of 

```go
provider, ok := cmDep.Annotations[util.FedDNSProvider]
if !ok {
    ...
}
```

for all the three keys. Instead of doing that here, I am Ok if oyu pass cmDep.Annotations to the function and then do the check there.

---

*[federation/pkg/kubefed/join.go, line 401 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42895#-KkF2s-AifkFfBhFH0lw:-KkF2s-AifkFfBhFH0lx:bmkp17l) ([raw file](https://github.com/kubernetes/kubernetes/blob/c1cac7d7f36ad9ceb977529158714a31d61b5992/federation/pkg/kubefed/join.go#L401)):*
> ```Go
> }
> 
> func appendStubDomains(configMap *api.ConfigMap, dnsProvider, dnsZoneName, nameServer string) *api.ConfigMap {
> ```

Can we call this `populateStubDomainsIfRequired()` or something like that?

---

*[federation/pkg/kubefed/join_test.go, line 297 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42895#-KkF4CZqe8Lev93BVMKs:-KkF4CZqe8Lev93BVMKt:b-h0orra) ([raw file](https://github.com/kubernetes/kubernetes/blob/c1cac7d7f36ad9ceb977529158714a31d61b5992/federation/pkg/kubefed/join_test.go#L297)):*
> ```Go
> 	deploymentList.Items = append(deploymentList.Items, deployment)
> 
> 	if dnsProvider == util.FedDNSProviderCoreDNS {
> ```

Write this block before appending to the list for clarity.

Also, it's not necessary to initialize the list and append in two separate statements? They can be combined?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42895)*

**Comment by shashidharatd** [comment]
@madhusudancs, have handled the comments. PTAL. Thanks!

---

Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[federation/pkg/kubefed/join.go, line 278 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42895#-KkF31PUTRJCX5VdOKU-:-KkGea8Pa9tmZgnaEv72:byn8qj2) ([raw file](https://github.com/kubernetes/kubernetes/blob/c1cac7d7f36ad9ceb977529158714a31d61b5992/federation/pkg/kubefed/join.go#L278)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

I think this isn't sufficient. kubefed panics if they keys don't exist. So you need the equivalent of 

```go
provider, ok := cmDep.Annotations[util.FedDNSProvider]
if !ok {
    ...
}
```

for all the three keys. Instead of doing that here, I am Ok if oyu pass cmDep.Annotations to the function and then do the check there.

</blockquote></details>

@madhusudancs, there won't be panic, if key does not exist. the variable would be initialized with `zero value for the type`. Here is the [reference](https://golang.org/doc/effective_go.html#maps).

I re-factored the function to take complete annotations as suggested.

---

*[federation/pkg/kubefed/join.go, line 401 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42895#-KkF2s-AifkFfBhFH0lw:-KkGfNeeBDpC9yy7j_Wl:b-93o2ao) ([raw file](https://github.com/kubernetes/kubernetes/blob/c1cac7d7f36ad9ceb977529158714a31d61b5992/federation/pkg/kubefed/join.go#L401)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

Can we call this `populateStubDomainsIfRequired()` or something like that?
</blockquote></details>

Renamed to populateStubDomainsIfRequired().

---

*[federation/pkg/kubefed/join_test.go, line 297 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42895#-KkF4CZqe8Lev93BVMKs:-KkGfTf6FFRijaSRUF9Z:bb6un1j) ([raw file](https://github.com/kubernetes/kubernetes/blob/c1cac7d7f36ad9ceb977529158714a31d61b5992/federation/pkg/kubefed/join_test.go#L297)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

Write this block before appending to the list for clarity.

Also, it's not necessary to initialize the list and append in two separate statements? They can be combined?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42895#-:-KkGfWGyiiP_pLojwWp9:b-bj1149)*

**Comment by madhusudancs** [comment]
/lgtm

---

Reviewed 2 of 4 files at r4.
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[federation/pkg/kubefed/join.go, line 278 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42895#-KkF31PUTRJCX5VdOKU-:-KkKWR1lxIJzRr_eLrC4:b-gwbepz) ([raw file](https://github.com/kubernetes/kubernetes/blob/c1cac7d7f36ad9ceb977529158714a31d61b5992/federation/pkg/kubefed/join.go#L278)):*
<details><summary><i>Previously, shashidharatd (Shashidhara T D) wrote…</i></summary><blockquote>

@madhusudancs, there won't be panic, if key does not exist. the variable would be initialized with `zero value for the type`. Here is the [reference](https://golang.org/doc/effective_go.html#maps).

I re-factored the function to take complete annotations as suggested.
</blockquote></details>

Ok. I stand corrected.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42895#-:-KkKX1BZyt6wY8VCpr95:b-8ks5qa)*

**Pull request merged**
