### PR TITLE
dependencies: update ginkgo to v2.7.0

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

The new ginkgo release adds sorting of specs. This was triggered by the observation that parallel test execution of Kubernetes E2E tests sometimes ran the same spec twice and (presumably) other specs not at all because spec order was random due to iteration over a map.

Sorting should avoid that problem.

#### Special notes for your reviewer:

PR #114761 fixed the randomness in the E2E storage test. That change is no longer necessary and it can be reverted.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

/cc @onsi

### CODE REVIEW

**Comment by onsi** [comment]
thanks @pohly - i think a useful validation would be to grab the report output from this PR (either JSON or JUnit) and grab the report output from a recent test run that has the same test suite but uses the prior version of ginkgo - and compare to validate that things have been deduped/ordered correctly. ideally both would have run in parallel but that's actually not super important.

i'd be happy to do that work if you can point me at the relevant json or xml files.

**Comment by aojea** [comment]
> i think a useful validation would be to grab the report output from this PR (either JSON or JUnit)

image

image

image

image

😄

**Comment by onsi** [comment]
thanks @aojea - so "pull-kubernetes-conformance-kind-ipv6-parallel" is the one I should always look at?  I had always assumed "kind" and "ipv6" meant "a subset of" but you're saying this is _the_ test suite, correct?

**Comment by onsi** [comment]
Quick update.  I pulled the JSON reports from both of the runs @pohly suggested - and from the original run that first surfaced this issue.  I'm finding that the JSON report from here:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-e2e-gce/1611104335188463616

(i.e. the "different PR" that @pohly mentions) is fine: there are no duplicate specs being run.  I believe this is because this run had the slice code that @pohly inserted to ensure a stable distribution of specs).

Unfortunately the report for this PR:

 https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-e2e-gce/1611104335188463616

_does_ exhibit the duplicate specs.  I'm not sure why yet.  When I iterate over a map locally and run in parallel I see the spec duplication issue occur when I turn off my Ginkgo-side sorting and then see it disappear when I turn my sorting back on.  So I know the fix is helping make specs generated by iterating over maps deterministic... but it doesn't seem to be working here.

I have two hypotheses:

1. There's something about this particular suite (e.g. something obscure related to file names or the actual spec structure in use here) that is breaking my sort solution.  I'm going to dig into this by using the report to generate a synthetic spec tree and then look at how the sort does/does not work for it.

2. Somehow the spec run for this PR didn't actually pick up the latest sha of Ginkgo?  I stared at the logs and I'm pretty sure it did.  But.... possibly not?

Finally - some good news: these are the only specs that exhibit this behavior.  So, as far as I can tell, no other dynamically generated specs in the suite have a non-deterministic order (and this includes specs that were skipped by e2e-gce).

Will dig into it some more tomorrow.

**Comment by onsi** [comment]
There was a third hypotheses that proved correct:  I had a bug on my end.  I somehow hadn't thought to try with `--randomize-all`.  The details aren't super interesting or important but I should have a fix out by tomorrow - I just want to take some time in the morning to add a better integration test on my end to make sure I cover this case more comprehensively and avoid a regression in the future.

**Comment by onsi** [comment]
Alright - all fixed on my end.  The latest sha on Ginkgo master now correctly orders specs.  @pohly and/or @aojea do you mind bumping and rerunning this again?  Once that's done I'll grab the report JSON and run it through my validation.  If all goes well I'll cut an actual Ginkgo release.

**Comment by pohly** [comment]
This PR now uses https://github.com/onsi/ginkgo/commit/89dda203832c75e84fcfcca8963e6242c00f1a5b

**Comment by onsi** [comment]
thanks @pohly  - will keep an eye on it and circle back later today.

**Comment by onsi** [comment]
ok this last run looks good.  I'll be cutting a new Ginkgo release soon.  this will be a minor release as it will include a few additional features that have been added recently.

**Comment by onsi** [comment]
Ginkgo 2.7.0 was release which includes this fix

**Comment by pohly** [comment]
This issue with random test coverage must have existed for a long time, right? The storage tests which triggered it are years old.

I think this points towards a blind spot in our E2E testing: unless someone manually checks test coverage, we are not getting alerted when tests that should run don't run anymore. I'm not sure what the solution is - after all, which tests to run is determined fairly dynamically in a decentralized way, so there can't be a central list of "these tests must run".

**Comment by onsi** [comment]
> This issue with random test coverage must have existed for a long time, right? The storage tests which triggered it are years old.

Yes, that's right.  It was only caught because of a fortunate confluence of events.

> I think this points towards a blind spot in our E2E testing: unless someone manually checks test coverage, we are not getting alerted when tests that should run don't run anymore. I'm not sure what the solution is - after all, which tests to run is determined fairly dynamically in a decentralized way, so there can't be a central list of "these tests must run".

I too am not sure that a bullet-proof solution exists.  But I can think of a few things to consider prioritizing:

### Ensure all specs have a unique name

It seems that prow's current behavior when computing the rollup for the `JUnit` section of the report (e.g. "873/7092" tests passed) is to parse the junit xml and count specs by their `Name` (i.e. the concatenation of their container strings and `It` string that Ginkgo [generates](https://github.com/onsi/ginkgo/blob/master/reporters/junit_report.go#L180-L194) to populate the `Name` field of the `JUnitTestCase`).  As I was digging into this I noticed that the numerator ("873") was not stable between different runs in the presence of duplicate specs - this is because different parallel runs were happening to run different subsets of the storage tests.  Prow was merging all specs with the same name and counting them as one.  (Incidentally this is also how @aojea discovered the issue - we had a case where a spec ran more than once.  In one case it ran and passed and then it later ran and failed.  Prow marked this as "flaky" - which means prow isn't reading the [`FlakeAttempts`](https://github.com/onsi/ginkgo/blob/master/reporters/junit_report.go#L172) property to determine flakiness - it's just doing it's own aggregation of the report making assumptions that aren't strictly compatible with GInkgo).

But that's all background information.  A helpful policy and validation might be to require that every spec have a unique `Name`.  That would guard against:
(a) developers inadvertantly having specs with the same name, which appears to generate confusing/inconsistent Prow reports
(b) this weird parallel duplication thing from happening again.  (I do have tests in Ginkgo now that will ensure that Ginkgo doesn't cause this kind of problem any more... but I understand that some degree of trust has been lost here!)

This could be as simple as parsing the xml or json report and asserting that `Name` is unique.  Alternatively you can add a `ReportAfterSuite` that will run after the suite has completed and will have access to the spec report that ran.  It could then quickly validate that all spec names are unique and, if not, fail with a clear error.  I do that in the [integration spec](https://github.com/onsi/ginkgo/blob/master/integration/_fixtures/nondeterministic_fixture/nondeterministic_fixture_suite_test.go#L17-L36) that I just added to ensure this issue doesn't occur again.

### Compare the output of `ginkgo --dry-run` to what actually ran

It's true that there is so much dynamism here (particularly with the use of filters and labels) that it could be hard to predict what ought to run.  One thing to potentially look into would be something like this:

1. Run `ginkgo --dry-run --json-report=preliminary.json PLUS-ALL-YOUR-ADDITIONAL-FILTER-FLAGS`
2. Run your actual `ginkgo` command
3. Write something that compares the output of `ginkgo` to the output of `--dry-run` captured in `preliminary.json` (or `.xml` if you prefer).

The idea here would be that `--dry-run` would not have any of the complexity of actually running specs or even running in parallel.  It simply filters specs and generates a report of what will run (these will have `status="passed"`) and what will be skipped (`status="skipped"`).  Of course I know that y'all do some runtime `Skip()`ing as well so whatever compares and constrasts will have to be smart about things.  Here too I could imagine doing this in a `ReportAfterSuite` so that the spec is self-validating and you don't have to maintain anything outside of the e2e suite itself.

---

Obviously, without

> a central list of "these tests must run"

these are, at best, mitigations that reduce risk.  But they are options that come to mind.

**Comment by pohly** [comment]
> Ensure all specs have a unique name

I don't think that this is a problem, even if we don't enforce it.

> Compare the output of ginkgo --dry-run to what actually ran

That would catch bugs in Ginkgo. Despite this episode with sorting of specs I still trust that this isn't going to be much of a problem :grin: 

My main concern is that we configure jobs incorrectly or add skip calls that don't work as intended. That can only be detected by monitoring a job over time and alerting when tests disappear. But as there are legitimate reasons for that, too, it cannot be fully automatic. :cry:

**Comment by pohly** [comment]
/cc @kubernetes/dep-approvers 

This Ginkgo update is ready for review + approval.

**Comment by liggitt** [comment]
/test pull-kubernetes-dependencies
to run check added in https://github.com/kubernetes/kubernetes/pull/114952

**Comment by pohly** [comment]
@liggitt: pull-kubernetes-dependencies passed.

**Comment by aojea** [comment]
/lgtm
/approve

for the test, missing deps
Thanks

**Comment by liggitt** [comment]
/approve
for deps

**Pull request merged**
