### PR TITLE
automated-cherry-pick-of-#117354-upstream-release-1.27

### PR DESCRIPTION
**Pull request by kkkkun**
/kind documentation

Cherry pick of https://github.com/kubernetes/kubernetes/pull/117354 on release-1.27.

### CODE REVIEW

**Comment by dims** [comment]
/release-note-none
/ok-to-test
/approve
/lgtm

small change in CHANGELOG/CHANGELOG-1.27.md

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
