### PR TITLE
1.1 cherry-pick cadvisor bump

### PR DESCRIPTION
**Pull request by jimmidyson**
@dchen1107 Don't have permissions to assign to you so self-assign please

### CODE REVIEW

**Comment by jimmidyson** [comment]
Intermediate commits were for some other cherry-picked code updates required.

**Comment by dchen1107** [comment]
LGTM

**Comment by pmorie** [comment]
@jimmidyson Thanks for doing this, this makes my life a lot simpler.

**Comment by jimmidyson** [comment]
Anything for you @pmorie ;)

**Comment by jimmidyson** [comment]
Shippable fail was due to #16238

**Comment by pmorie** [comment]
Let's see if we can get some shippable love

**Comment by jimmidyson** [comment]
@pmorie Thanks, but this is due to a package rename by a dependency - `godep restore` doesn't like it when packages are removed from the dependency source repo's master branch it seems... Any ideas to fix #16238 appreciated.

**Comment by jimmidyson** [comment]
Rebased after #16259 & #16260 have been merged. Fingers crossed.

**Comment by jimmidyson** [comment]
e2e success. Hurry up shippable!

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
Need to update release notes for all cAdvisor changes for 1.1 release.

**Pull request merged**
