### PR TITLE
correct canonical import for azure legacy provider mockfileclient

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

The canonical import path in this package is wrong.
This breaks running unit tests with make. https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-coverage-unit/1253727282426548225

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve
cc @ZeroMagic

**Review by ZeroMagic — APPROVED** [review]
/lgtm

**Pull request merged**
