### PR TITLE
temporary band-aid to make node proxy work again

### LINKED ISSUE #4304: apiserver proxy stopped accepting namespaces
The apiserver proxy rewrites links to the form "/proxy/ns/default/...":

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/proxy.go#L162

But this form stopped working recently, seemingly around https://github.com/GoogleCloudPlatform/kubernetes/commit/18609e17062ad4a56c3533f80014299815bfee76. The "/proxy/ns/default/..." form always returns "404: Page Not Found", similar to the problem seen in https://github.com/GoogleCloudPlatform/kubernetes/pull/4283. If you remove "/ns/default" from the URL, it works.

### PR DESCRIPTION
**Pull request by lavalamp**
Fixes #4304

@derekwaynecarr Do you think this is a reasonable short term patch?

I'm starting a cluster to verify it works.

### CODE REVIEW

**Comment by lavalamp** [comment]
Confirmed, node proxy works again.

**Comment by derekwaynecarr** [comment]
I can't reason too fully on this now since my kids are consuming my attention so I do not want to hold this up.  Is the proxy path prepend value ultimately visible to the end users during URL rewriting?  If so, this won't work because the proxy is registered in a different path.  I could be completely wrong here, and I blame fatherhood.  Can review more tomorrow.  I prefer a solution that changes how we install the proxy api in apiserver to always register proxy with namespace in path.

**Comment by derekwaynecarr** [comment]
If it works now, fine.  Put a TODo to do this right and did you test with v1beta3?

**Comment by lavalamp** [comment]
Disconfirmed, actually @derekwaynecarr is right, it doesn't work still. Hm.

**Comment by derekwaynecarr** [comment]
I still think my PR was the right first step and it works in v1beta3 so lets just deprecate 1 and 2 :-). Take my PR and change where we install the API to also expose the proxy at /proxy/namespace for v1 and v2 and I think we would work.

**Comment by lavalamp** [comment]
I actually started with your PR but then noticed that the restmapper was already plumbed through -- it's part of apiRequestInfoResolver. Then I thought that maybe this would be very simple and work, but it doesn't. :)

**Comment by lavalamp** [comment]
Closing this. Will try something else.

**Pull request closed without merging**
