### PR TITLE
Use the core client with version

### LINKED ISSUE #49535: Use the core client with version
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**:
When rebase #48976 to fix the conflict with #48847, find that some codes use `clientSet.CoreV1()`, while some codes still use the **Deprecated** `clientSet.Core()`.

**What you expected to happen**:
Replace the **Deprecated** `clientSet.Core()` with `clientSet.CoreV1()`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by supereagle**
**What this PR does / why we need it**:
Replace the **deprecated** `clientSet.Core()` with `clientSet.CoreV1()`.

**Which issue this PR fixes**: fixes #49535

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by supereagle** [comment]
/assign @caesarxuchao
 PTAL.

**Comment by caesarxuchao** [comment]
Thanks @supereagle

**Comment by supereagle** [comment]
Kindly ping @wojtek-t for /approve, thanks a lot.

**Pull request merged**
