### PR TITLE
Add ubuntu kube-push for upgrading of k8s cluster

### PR DESCRIPTION
**Pull request by huangyuqi**
Add upgrading for ubuntu kubernetes .If you want to upgrade a k8s cluster, you just need to run `$ ./kubernetes/cluster/kube-push.sh`.The script will download the latest version of k8s,and replace all the kubernetes's binaries of cluster's nodes. The format of upgrade command is like this: `./kube-push.sh [-m|-n <node id>] <version>` Updates Kubernetes binaries. Can be done for all components (by default), master(-m) or specified node(-n). If the version is not specified will try to use local binaries. Warning: upgrading single node is experimental. Some examples are as follows:
- upgrade master:    `./kube-push.sh -m 1.0.4`
- upgrade node:      `./kube-push.sh -n 192.0.0.2 1.0.4` (the id is the node's name)
- upgrade all nodes: `./kube-push.sh 1.0.4`

The script will not delete your data of cluster, it just replace the binaries.

### CODE REVIEW

**Comment by huangyuqi** [comment]
@mikedanese I have closed the old PR(https://github.com/kubernetes/kubernetes/pull/12710), because it is chaotic. Would you please kindly check the new one? Thanks very much.

**Comment by huangyuqi** [comment]
@mikedanese I have test this script in my experimental environment  repeatedly. And it can work normally. Would you please help me to check this? Thanks very much.

**Comment by mikedanese** [comment]
I reviewed this in #12710. This is LGTM

**Comment by mikedanese** [comment]
@huangyuqi thanks!

**Comment by huangyuqi** [comment]
@mikedanese thanks so much!

**Pull request merged**
