### PR TITLE
Use `Int32Ptr` function from utils instead of self-written versions

### LINKED ISSUE #59971: Eliminate duplicated versions of the utilpointer.Int32Ptr()
We should do the similar changes that I did for `BoolPtr()` in #59924 but for `utilpointer.Int32Ptr()`. Here are the candidates:
```console
$ git grep -E 'func\ [^ (]+\([^ ]+\ int32\)\ \*int32' !(vendor) | grep -v pkg/util/pointer
pkg/apis/apps/v1/defaults_test.go:func newInt32(val int32) *int32 {
pkg/apis/apps/v1beta1/defaults_test.go:func newInt32(val int32) *int32 {
pkg/apis/apps/v1beta2/defaults_test.go:func newInt32(val int32) *int32 {
pkg/apis/autoscaling/v1/defaults_test.go:func newInt32(val int32) *int32 {
pkg/apis/autoscaling/v2beta1/defaults_test.go:func newInt32(val int32) *int32 {
pkg/apis/autoscaling/validation/validation_test.go:func newInt32(val int32) *int32 {
pkg/apis/batch/v1/defaults_test.go:func newInt32(val int32) *int32 {
pkg/apis/batch/v1beta1/defaults_test.go:func newInt32(val int32) *int32 {
pkg/apis/core/v1/defaults_test.go:func newInt(val int32) *int32 {
pkg/apis/extensions/v1beta1/defaults_test.go:func newInt32(val int32) *int32 {
staging/src/k8s.io/client-go/examples/create-update-delete-deployment/main.go:func int32Ptr(i int32) *int32 { return &i }
```

/kind cleanup
/help

### PR DESCRIPTION
**Pull request by justaugustus**
**What this PR does / why we need it**:
Replaces instances of newInt{,32} with `Int32Ptr` function from `k8s.io/kubernetes/pkg/util/pointer`

**Which issue(s) this PR fixes**:
Fixes #59971

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by php-coder** [comment]
@justaugustus Thank you!

/ok-to-test
/lgtm

**Review by php-coder — APPROVED** [review]

**Comment by justaugustus** [comment]
Tests pass! This is ready for someone to take a look at again and hit with `/lgtm` + `/approve` :)

**Comment by justaugustus** [comment]
As a reminder to myself:

### Check for instances
```bash
$ git grep -E 'func\ [^ (]+\([^ ]+\ int32\)\ \*int32' !(vendor) | grep -v pkg/util/pointer

pkg/apis/apps/v1/defaults_test.go:func newInt32(val int32) *int32 {
pkg/apis/apps/v1beta1/defaults_test.go:func newInt32(val int32) *int32 {
pkg/apis/apps/v1beta2/defaults_test.go:func newInt32(val int32) *int32 {
pkg/apis/autoscaling/v1/defaults_test.go:func newInt32(val int32) *int32 {
pkg/apis/autoscaling/v2beta1/defaults_test.go:func newInt32(val int32) *int32 {
pkg/apis/autoscaling/validation/validation_test.go:func newInt32(val int32) *int32 {
pkg/apis/batch/v1/defaults_test.go:func newInt32(val int32) *int32 {
pkg/apis/batch/v1beta1/defaults_test.go:func newInt32(val int32) *int32 {
pkg/apis/core/v1/defaults_test.go:func newInt(val int32) *int32 {
pkg/apis/extensions/v1beta1/defaults_test.go:func newInt32(val int32) *int32 {
staging/src/k8s.io/client-go/examples/create-update-delete-deployment/main.go:func int32Ptr(i int32) *int32 { return &i }
```

### Fix
* remove function definition
* import `utilpointer "k8s.io/kubernetes/pkg/util/pointer"`
* find & replace w/ instances of `utilpointer.Int32Ptr`
* rinse & repeat

### Commit
### Update Bazel
`./hack/update-bazel.sh`

### Commit bazel updates

### Run quick tests
`make quick-verify`

### Push
### Profit?

**Comment by justaugustus** [comment]
Another note...

In running a slightly different regex (after commit):
```bash
$ git grep -E 'func\ [^ (]+\([^ ]+\ int(32|64)?\)\ \*int(32|64)?' !(vendor) | grep -v pkg/util/pointer

pkg/apis/core/validation/validation_test.go:func newInt32(val int) *int32 {
pkg/controller/deployment/sync_test.go:func intOrStrP(val int) *intstr.IntOrString {
pkg/kubectl/autoscale_test.go:func newInt32(value int) *int32 {
plugin/pkg/admission/security/podsecuritypolicy/admission_test.go:func userIDPtr(i int) *int64 {
plugin/pkg/admission/security/podsecuritypolicy/admission_test.go:func groupIDPtr(i int) *int64 {
staging/src/k8s.io/apiextensions-apiserver/test/integration/validation_test.go:func int64Ptr(f int64) *int64 {
staging/src/k8s.io/apimachinery/pkg/conversion/queryparams/convert_test.go:func intp(n int) *int { return &n }
staging/src/k8s.io/client-go/examples/create-update-delete-deployment/main.go:func int32Ptr(i int32) *int32 { return &i }
test/e2e/apps/deployment.go:func intOrStrP(num int) *intstr.IntOrString {
test/e2e/auth/pod_security_policy.go:func intPtr(i int64) *int64 {
test/integration/deployment/util.go:func intOrStrP(num int) *intstr.IntOrString {
```

You can see that there are additional cases, some not necessarily relevant, which could be addressed e.g., `int --> *int32`

I'll open a separate issue to discuss.

**Comment by justaugustus** [comment]
@liggitt PTAL and approve, if all is good

**Pull request merged**
