### PR TITLE
Remove some dead code

### PR DESCRIPTION
**Pull request by wojtek-t**
Something I faced while debugging around #10282

### CODE REVIEW

**Comment by mbforbes** [comment]
@davidopp sufficient context?

**Comment by davidopp** [comment]
LGTM

This seems fine as it only is removing
- constants
- function definitions
- imports

If there were a bug in this PR, the code wouldn't compile.

Technically it needs a second LGTM though, since it's not a docs or test change.

**Comment by davidopp** [comment]
@dchen1107 or @quinton-hoole for a second LGTM.

**Comment by wojtek-t** [comment]
@dchen1107 @quinton-hoole - can you please take a look?

**Comment by quinton-hoole** [comment]
Sure, I can take a look.

**Comment by quinton-hoole** [comment]
I'm super-keen on removing code.  But could you provide some context as to what this code was previously used for, and why it's no longer required?

**Comment by wojtek-t** [comment]
@quinton-hoole IIUC, this code comes from the old times, when we had all registry code in a single place. Then generic registry was created and most of the code were migrated to per-resource registry built on top of generic one. It seems that pkg/registry/etcd contains those that were not yet migrated, but in case of controllers it seems they were migrated but not removed from here.
Does it sound ok?

Can you please LGTM it?

**Comment by quinton-hoole** [comment]
LGTM!  Thanks for the cleanup @wojtek-t

**Pull request merged**
