### PR TITLE
The link(node-allocatable) in Changelog.md is "404 not found"

### PR DESCRIPTION
**Pull request by zhangmingld**
The link(node-allocatable) in Changelog.md is "404 not found"

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Review by resouer — COMMENTED** [review]
lgtm, but please fix the CLA problem

**Comment by zhangmingld** [comment]
I change my local git config，but i still get cla/linuxfoundation info “zhangmingld authorized, but 1 other problem”。。what happend。。。

**Comment by zhangmingld** [comment]
i will close it and do a new pr

**Comment by zhangmingld** [comment]
@resouer ,the new pr link https://github.com/kubernetes/kubernetes/pull/50132 
i can not fix the cla, so i closed it and do a new ,thankyou ~

**Pull request closed without merging**
