### PR TITLE
Fixes broken link in PodSpec

### PR DESCRIPTION
**Pull request by henriquetruta**
The PodSpec reference to NodeSelector misses
the `.md` extension in the file.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by cblecker** [comment]
LGTM

**Comment by brendandburns** [comment]
@k8s-bot ok to test

/approve
/lgtm

**Comment by henriquetruta** [comment]
@k8s-bot node e2e test this

**Comment by henriquetruta** [comment]
@k8s-bot verify test this
@k8s-bot kops aws e2e test this

**Comment by brendandburns** [comment]
@k8s-bot verify test this

**Comment by cblecker** [comment]
```
I0130 12:50:15.969] /go/src/k8s.io/kubernetes/docs/api-reference is out of date. Please run hack/update-api-reference-docs.sh
I0130 12:50:15.975] FAILED   hack/make-rules/../../hack/verify-api-reference-docs.sh	104s
```

**Comment by cblecker** [comment]
LGTM with changes

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/40544#-:-KbqSp6w5NeTtHZi513f:bjpd5kg)*

**Comment by brendandburns** [comment]
@henriquetruta I no longer see the changes, bad rebase or did this get changed somewhere else?

**Comment by henriquetruta** [comment]
@brendandburns I think it wasn't a rebase issue. The tests were failing, so I ran locally the script mentioned in the log (verify-api-reference-docs.sh) and thought it had generated some kind of binary stuff. And then, I pushed the generated files. Sorry, it's my first PR here. 
What should I have done? Am I supposed to run this script (and/or any other) locally?

**Comment by cblecker** [comment]
Hi @henriquetruta --
It looks like the right way to update this link is to update https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L2147 with the .md extension, and then run `make update` to update all the different generated docs from the api

Give that a shot!

**Comment by henriquetruta** [comment]
Hi @cblecker, thanks for the tips. I did it, and after somethings broken, I made it to work. Then, I commited just the api html and the .go file, and it is still failing here. Should I've committed all generated files? Am I missing something?

**Comment by cblecker** [comment]
@henriquetruta Yeah, I'd rebase off of master, and `make update`, and then commit all the generated files. The API spec updates in a number of places, not just the HTML version.

**Comment by henriquetruta** [comment]
@cblecker done! Does it look ok now?

**Comment by brendandburns** [comment]
Hrm, it appears to have stripped our analytics from all docs, I don't think we want that...

Either revert all files with just that change, or:

edit `types.go`

Then 

`./hack/update-generated-docs.sh`

then commit.

Sorry!

**Comment by henriquetruta** [comment]
@brendandburns looks like I finally made it!  :D

**Comment by cblecker** [comment]
Reviewed 1 of 3 files at r3, 13 of 13 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/40544)*

**Comment by henriquetruta** [comment]
@k8s-bot unit test this

**Comment by cblecker** [comment]
```
I0330 12:14:37.151]   /go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go is out of date. Please run hack/update-staging-client-go.sh
I0330 12:14:37.152] FAILED   hack/make-rules/../../hack/verify-staging-client-go.sh	93s
```

**Comment by henriquetruta** [comment]
@k8s-bot unit test this
@k8s-bot verify test this

**Comment by cblecker** [comment]
@henriquetruta per my above comment (https://github.com/kubernetes/kubernetes/pull/40544#issuecomment-290517856), the verify failure is real

**Comment by cblecker** [comment]
@henriquetruta ping - PR needs rebase

**Comment by cblecker** [comment]
Hey @henriquetruta.. would you mind pinging me after the rebase? I don't see just the commit pushes, and if you ping me I can LGTM this into the queue.

**Comment by henriquetruta** [comment]
@cblecker done! Sorry for the long time

**Comment by cblecker** [comment]
@henriquetruta Thanks for sticking with this. Let's get this merged!
/lgtm

**Comment by cblecker** [comment]
Reviewed 1 of 3 files at r3, 19 of 19 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/40544)*

**Comment by henriquetruta** [comment]
@k8s-bot gci gce e2e test this
@k8s-bot unit test this

**Pull request merged**
