### PR TITLE
[go115] Require go1.15 in build helper scripts

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Requires scripts like hack/update-gofmt.sh to be run with go1.15+

/milestone v1.19

```release-note
NONE
```

/cc @justaugustus

### CODE REVIEW

**Review by justaugustus — COMMENTED** [review]
@liggitt -- Do we have any version number weirdness to worry about here?
e.g., `go1.15` vs `go1.15.0`

Otherwise:
/lgtm
/approve
/hold lift at will

**Comment by justaugustus** [comment]
/test pull-kubernetes-e2e-kind
(pod pending timeout)

**Comment by liggitt** [comment]
> Do we have any version number weirdness to worry about here?
> e.g., `go1.15` vs `go1.15.0`

the comparison passes with a go version of `go1.15` as well, so I think we're ok

/retest
/hold cancel

**Comment by liggitt** [comment]
interestingly, CI is still on go1.15rc2, which also passes the comparison

> Checking kubectl version
> Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-alpha.0.592+598b07b1cdb263", GitCommit:"598b07b1cdb263db9d79c9253498762146374923", GitTreeState:"clean", BuildDate:"2020-08-13T16:19:32Z", GoVersion:"go1.15rc2", Compiler:"gc", Platform:"linux/amd64"}

at least this will catch people on 1.14 and earlier

**Comment by hasheddan** [comment]
/test pull-kubernetes-e2e-kind

@spiffxp looks like this timed out after 5m, didn't we bump to 15m?

**Pull request merged**
