### PR TITLE
Automated cherry pick of #65882: Add script to verify generated files #65986: verify-generated-files: ensure git tree is clean #65985: Don't gitignore pkg/generated/bindata.go

### LINKED ISSUE #65968: Kubernetes repository can't be vendored
We have written a cli tool that uses kubectl util libraries. Today I was trying to upgrade from Kubernetes 1.10 dependency to 1.11 . But I found that I can't compile code after I revendor to Kubernetes 1.11 . The problem is that  https://github.com/kubernetes/kubernetes/blob/v1.11.0/pkg/kubectl/util/i18n/i18n.go#L107 uses generated code from https://github.com/kubernetes/kubernetes/tree/v1.11.0/pkg/generated package. But the generated code is not committed to the repo. So, after vendoring I can't compile any more. I know committing generated code is not ideal but what other option do I have ? We don't use Bazel and will not use Bazel. 

Thanks. Looking forward to some solution.

/kind bug
/sig cli

### PR DESCRIPTION
**Pull request by ixdy**
Cherry pick of #65882 #65986 #65985 #66076 on release-1.11.

#65882: Add script to verify generated files
#65986: verify-generated-files: ensure git tree is clean
#65985: Re-add pkg/generated/bindata.go
#66076: Don't delete pkg/generated/bindata.go in make clean

```release-note
Re-adds `pkg/generated/bindata.go` to the repository to allow some parts of k8s.io/kubernetes to be go-vendorable.
```

Fixes #65968.

### CODE REVIEW

**Comment by ixdy** [comment]
added in a cherry-pick of #66076, since otherwise we break the build jobs. 🤦‍♂️

**Comment by foxish** [comment]
Please note that this will miss 1.11.1 unless approved by EOD tomorrow.

**Comment by ixdy** [comment]
uggggh github

/retest

**Pull request merged**
