### PR TITLE
Fix path import slash in code generator with windows

### LINKED ISSUE #40: Problem with codegen on Windows
I downloaded the repo, modified the api files and codegen script to suit my needs and tried to run `update-codegen.sh` from Git Bash, but it failed with these errors.

```
Keith@DESKTOP-021AQFL MINGW64 ~/go/src/gamepod.cc/agent (master)
$ ./hack/update-codegen.sh
Generating deepcopy funcs
Generating clientset for gamepod:v1alpha1 at gamepod.cc/agent/pkg/client/clientse                          t
W1223 18:13:29.376607   33732 import_tracker.go:45] Warning: backslash used in i                          mport path 'gamepod.cc\agent\pkg\client\clientset\versioned\scheme', this is uns                          upported.
F1223 18:13:29.441608   33732 main.go:64] Error: Failed executing generator: som                          e packages had errors:
errors in package "gamepod.cc\\agent\\pkg\\client\\clientset\\versioned":
unable to format file "..\\..\\gamepod.cc\\agent\\pkg\\client\\clientset\\versio                          ned\\clientset.go" (20:34: unknown escape sequence (and 3 more errors)).

errors in package "gamepod.cc\\agent\\pkg\\client\\clientset\\versioned\\fake":
unable to format file "..\\..\\gamepod.cc\\agent\\pkg\\client\\clientset\\versio                          ned\\fake\\clientset_generated.go" (20:34: unknown escape sequence (and 10 more                           errors)).

errors in package "gamepod.cc\\agent\\pkg\\client\\clientset\\versioned\\typed\\                          gamepod\\v1alpha1":
unable to format file "..\\..\\gamepod.cc\\agent\\pkg\\client\\clientset\\versio                          ned\\typed\\gamepod\\v1alpha1\\gameserver.go" (22:11: illegal character U+005C '\                          ' (and 10 more errors)).
unable to format file "..\\..\\gamepod.cc\\agent\\pkg\\client\\clientset\\versio                          ned\\typed\\gamepod\\v1alpha1\\gamepod_client.go" (17:2: invalid import path: "ga                          mepod.cc\\agent\\pkg\\client\\clientset\\versioned\\scheme").

errors in package "gamepod.cc\\agent\\pkg\\client\\clientset\\versioned\\typed\\                          gamepod\\v1alpha1\\fake":
unable to format file "..\\..\\gamepod.cc\\agent\\pkg\\client\\clientset\\versio                          ned\\typed\\gamepod\\v1alpha1\\fake\\fake_gamepod_client.go" (19:28: unknown esca                          pe sequence (and 3 more errors)).

```

Where `gamepod` is my api name and `gameserver` is my CRD. Upon looking in some of the files in the error message I found out that it was using backslashes in import paths for files it generated:

```
// pkg/client/clientset/versioned/clientset.go

...

package versioned

import (
	flowcontrol "k8s.io/client-go/util/flowcontrol"
	stablev1alpha1 "gamepod.cc\agent\pkg\client\clientset\versioned\typed\gamepod\v1alpha1"
	discovery "k8s.io/client-go/discovery"
	rest "k8s.io/client-go/rest"
)

...
```

However when I run `update-codegen.sh` with the same code on a Linux VPS it runs completely fine and generates the correct import paths so it appears this is a problem caused by the scripts not using the correct path separator under Git Bash/MSYS2. 

I assume this is less of an issue with sample-controller and probably an issue with `kubernetes/code-generator` or `kubernetes/gengo` but I'm not sure where to look so I assume this is the best place to start.

Here are the most relevant files:

```
// hack/update-codegen.sh

set -o errexit
set -o nounset
set -o pipefail
SCRIPT_ROOT=$(dirname ${BASH_SOURCE})/..
CODEGEN_PKG=${CODEGEN_PKG:-$(cd ${SCRIPT_ROOT}; ls -d -1 ./vendor/k8s.io/code-generator 2>/dev/null || echo ../code-generator)}
# generate the code with:
# --output-base    because this script should also be able to run inside the vendor dir of
#                  k8s.io/kubernetes. The output-base is needed for the generators to output into the vendor dir
#                  instead of the $GOPATH directly. For normal projects this can be dropped.
${CODEGEN_PKG}/generate-groups.sh "deepcopy,client,informer,lister" \
  gamepod.cc/agent/pkg/client gamepod.cc/agent/pkg/apis \
  gamepod:v1alpha1 \
  --output-base "$(dirname ${BASH_SOURCE})/../../.." \
  --go-header-file ${SCRIPT_ROOT}/hack/boilerplate.go.txt
```

```
// pkg/apis/gamepod/v1alpa1/types.go

package v1alpa1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// GameServer is a specification for a Game Server resource
type GameServer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              GameServerSpec   `json:"spec"`
	Status            GameServerStatus `json:"status"`
}

// GameServerSpec is the spec for a GameServer resource
type GameServerSpec struct {
	Game GameServerGame `json:"game"`
}

// GameServerGame is the spec for the Game key of the GameServer resource spec
type GameServerGame struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// GameServerStatus is the status for a GameServer resource
type GameServerStatus struct {
	Created bool `json:"installed"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// GameServerList is a list of GameServer resources
type GameServerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata"`
	Items           []GameServer `json:"items"`
}
```

### PR DESCRIPTION
**Pull request by gaoxinge**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This pull request fix path import slash in code generator with windows.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/sample-controller/issues/40 and https://github.com/kubernetes/code-generator/issues/88.

#### Special notes for your reviewer:

NONE

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by gaoxinge** [comment]
I signed it

**Comment by gaoxinge** [comment]
I signed it

**Comment by caesarxuchao** [comment]
Thanks for the PR, @gaoxinge.

Except running the sample controller on Windows, are there other use cases? Based on the linked issues, I think it's not worth the maintenance costs.

If we want to purse this, we need to add tests to verify the code generators work in the Windows environments.

**Comment by gaoxinge** [comment]
@caesarxuchao I think it is that the code compatible with windows is maintainable, but my way of fix is not maintainable. Give me some time,  and I will find a way to fix this issue, which is more maintainable and testable.

**Pull request closed without merging**
