### PR TITLE
Regional registries: Hack the manifests!

### PR DESCRIPTION
**Pull request by zmerlynn**
Allow the `gcr.io/google_containers` registry to be overridden regionally by just blasting a new KUBE_ADDON_REGISTRY out. Instead of adding every addon to Salt and asking all of the other consumers (Trusty, Juju, Mesos, etc) to change, just script the sed ourselves.

This is probably the 9th grossest thing I've ever done, but it works well, and it works quickly. I kind of wish it didn't.

### CODE REVIEW

**Comment by andyzheng0831** [comment]
@roberthbailey, thanks for heads-up. This won't break our trusty stuff, but the new logic is not supported there automatically. I think what I need to change is very similar to the change of cluster/saltbase/install.sh in this PR, i.e., if ${KUBE_ADDON_REGISTRY} is different from gcr.io/google_containers we use the regional registry. I will make the change by noon of Monday before leaving for offsite.

**Comment by andyzheng0831** [comment]
@zmerlynn @roberthbailey , what is the difference between KUBE_DOCKER_REGISTRY and KUBE_ADDON_REGISTRY? If both are set, which one overwrites which?

**Comment by zmerlynn** [comment]
@andyzheng0831: It's complicated. Neither should overwrite the other. `KUBE_DOCKER_REGISTRY` should be the relevant variable for the stuff that's built in the release and is currently side-loaded in the server tar, and `KUBE_ADDON_REGISTRY` is the rest.

**Comment by andyzheng0831** [comment]
@zmerlynn , got you. My change follows the same logic as what you explained.

**Pull request merged**
