### PR TITLE
Remove examples directory

### LINKED ISSUE #60887: Remove remaining examples
I was working on separate demo based on guestbook-go example and wanted to push some updates to it's code. 
But looks like there are multiple versions. About 6 months ago some examples were moved to https://github.com/kubernetes/examples and have their README mention it. 
It was not noticed couple of times and resulted in new examples still being added to old location.
I think remaining examples should be moved and whole directory removed to avoid confusion. 

To allow anyone to pick that issue would be nice to for someone to describe what else should be done beside removing directory so nothing breaks (docs, etc.)

/area example
/kind cleanup
/sig apps
cc @ahmetb

### PR DESCRIPTION
**Pull request by serathius**
Removes `examples` directory, which was migrated https://github.com/kubernetes/examples/pull/210
Moves manifests used in tests to `test/e2e/testing-manifests`
I will submit PR to https://github.com/kubernetes/k8s.io to fix links to https://releases.k8s.io/*/examples
Fixes #60887

**Special notes for your reviewer**:
```release-note
NONE
```
cc @ahmetb @ixdy

### CODE REVIEW

**Review by zouyee — COMMENTED** [review]
I think some changes need to be splited

**Comment by serathius** [comment]
No, I waited for redirect in k8s. Forgot to rerun tests.

**Comment by serathius** [comment]
ping  @ahmetb

**Comment by ahmetb** [comment]
Thanks a lot for this work.
/lgtm

**Comment by ahmetb** [comment]
@serathius needs rebase. I'll talk to thockin to get approval, then maybe we need to lift the blockade (@BenTheElder is there a way to override the blockade?)

**Comment by BenTheElder** [comment]
@ahmetb we could remove it from the config temporarily, or (probably better) we can have someone with write permissions to k/k manually remove the label.
The former is not super great because it lifts it for *all* PRs until we put it back
The latter might be annoying because it will need to be done on every push, but otherwise I think that should work.


@deads2k xref: https://github.com/kubernetes/kubernetes/pull/63075

**Comment by spiffxp** [comment]
As I understand it, the way to go would be:
- get the PR rebased
- have someone with repo write access remove the do-not-merge/blocked-paths label
- the blockade plugin [won't try to re-apply the label again until the PR is synchronized](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/blockade/blockade.go#L135-L139)

I'll remove the label now and we can find out if the bot will fight back

**Comment by ahmetb** [comment]
Thank you so much @serathius. 

If we get complaints about examples/ directory disappearing altogether, we can add a README.md pointing to the new repo but we already had that for > 6 months.

**Pull request merged**
