### PR TITLE
Shell completion of multiple resource names

### PR DESCRIPTION
**Pull request by marckhouzam**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This PR teaches the completion functions to repeat resource names when applicable and supported. The logic checks if a resource name has already been specified by the user and does not include it again when repeating the completion.

For example, the `get` command can receive multiple pods names, therefore with this commit:
  `kubectl get pod pod1 [tab]`
will provide completion of pod names again, but not show `pod1` a second time since it is already part of the command-line.

The improvement affects the following commands:
- annotate
- apply edit-last-applied
- apply view-last-applied
- autoscale
- delete
- describe
- edit
- expose
- get
- label
- patch
- rollout history
- rollout pause
- rollout restart
- rollout resume
- rollout undo
- scale
- taint

Note that "rollout status" only accepts a single resource name, unlike the other "rollout ..." commands; this required the creation of a special completion function that did not repeat just for that case.

#### Which issue(s) this PR fixes:

Replaces #101427

#### Special notes for your reviewer:

The PR adds a utility function to remove a list of values from an array.  It is used to prevent the completion from suggesting choices that are already on the command-line (as explained above).  I don't know if such a utility already existed in the code base or if I put it in the right place (`cmd/util/helpers.go#Unique(..)`)

#### Does this PR introduce a user-facing change?

```release-note
Shell completion now knows to continue suggesting resource names when the command supports it.  For example "kubectl get pod pod1 <TAB>" will suggest more pod names.
```

/cc @phil9909

### CODE REVIEW

**Review by brianpursley — CHANGES_REQUESTED** [review]
Looks good.  I left a few comments, but this looks like a good improvement to completions.

**Comment by marckhouzam** [comment]
Thanks for the review @brianpursley, I believe the latest version addresses your comments.

**Review by brianpursley — APPROVED** [review]
Looks good.  Tried it out locally and seems to work well.  Nice work.

**Review by eddiezane — COMMENTED** [review]
This is awesome! Thanks for adding. A few nits to address and then lgtm.

**Review by eddiezane — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
