### PR TITLE
dockershim: move docker to the given cgroup

### PR DESCRIPTION
**Pull request by yujuhong**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34490)

### CODE REVIEW

**Comment by yujuhong** [comment]
@k8s-bot cri test this

**Comment by yujuhong** [comment]
@k8s-bot cri test this

**Comment by yujuhong** [comment]
@k8s-bot cri test this

**Comment by yujuhong** [comment]
@k8s-bot cri test this

**Comment by yujuhong** [comment]
This PR is blocked on testing on non-systemd nodes + CRI.

**Comment by yujuhong** [comment]
@k8s-bot cri test this

**Comment by yujuhong** [comment]
@k8s-bot cri test this.

**Comment by Random-Liu** [comment]
*[pkg/kubelet/dockershim/docker_service.go, line 117 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34490#-KV2Y8YruE-ZYz9_sGY2:-KV2Y8YruE-ZYz9_sGY3:bimww1y) ([raw file](https://github.com/kubernetes/kubernetes/blob/6c42e61505c4873b80354678fb211eb7b8478269/pkg/kubelet/dockershim/docker_service.go#L117)):*
> ```Go
> // Start initializes and starts components in dockerService.
> func (ds *dockerService) Start() error {
> 	if err := ds.containerManager.Start(); err != nil {
> ```

Why not just return `ds.containerManager.Start()` now? It is the only thing needs to start. :)

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34490)*

**Comment by Random-Liu** [comment]
*[pkg/kubelet/dockershim/cm/container_manager_linux.go, line 54 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34490#-KV2YRFIZ-YO4UbuFuOd:-KV2YRFIZ-YO4UbuFuOe:b-3pdwo9) ([raw file](https://github.com/kubernetes/kubernetes/blob/6c42e61505c4873b80354678fb211eb7b8478269/pkg/kubelet/dockershim/cm/container_manager_linux.go#L54)):*
> ```Go
> )
> 
> func NewContainerManager(cgroupsName string) ContainerManager {
> ```

Why we only have linux implementation for this? This won't compile on other platform.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34490)*

**Comment by Random-Liu** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/kubelet/dockershim/cm/container_manager_linux.go, line 81 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34490#-KV2_57gxdpapLvZNa9O:-KV2_57gxdpapLvZNa9P:b-xkz4ua) ([raw file](https://github.com/kubernetes/kubernetes/blob/6c42e61505c4873b80354678fb211eb7b8478269/pkg/kubelet/dockershim/cm/container_manager_linux.go#L81)):*
> ```Go
> 
> func (m *containerManager) doWork() {
> 	// TODO(yujuhong): Get real docker version to pass to the function.
> ```

Why not address the TODO now?

---

*[pkg/kubelet/dockershim/cm/container_manager_linux.go, line 123 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34490#-KV2dre_T8cKn9Z-UeWd:-KV2dre_T8cKn9Z-UeWe:bs84e1l) ([raw file](https://github.com/kubernetes/kubernetes/blob/6c42e61505c4873b80354678fb211eb7b8478269/pkg/kubelet/dockershim/cm/container_manager_linux.go#L123)):*
> ```Go
> 	}
> 
> 	memoryCapacity, err := parseCapacity(out, memoryCapacityRegexp)
> ```

nit: Just return here?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34490)*

**Comment by Random-Liu** [comment]
LGTM with nits and PR needs rebase.

**Comment by yujuhong** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/kubelet/dockershim/docker_service.go, line 117 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34490#-KV2Y8YruE-ZYz9_sGY2:-KVCyOpx_00n2-qS4Kj8:bwb38d7) ([raw file](https://github.com/kubernetes/kubernetes/blob/6c42e61505c4873b80354678fb211eb7b8478269/pkg/kubelet/dockershim/docker_service.go#L117)):*
<details><summary><i>Previously, Random-Liu (Lantao Liu) wrote…</i></summary>
> Why not just return `ds.containerManager.Start()` now? It is the only thing needs to start. :)
</details>
I anticipated more things will need to be added soon ;) Anyway, just return directly for now

---

*[pkg/kubelet/dockershim/cm/container_manager_linux.go, line 54 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34490#-KV2YRFIZ-YO4UbuFuOd:-KVCuvvLCesOvgBW9NXF:b-n5kwgf) ([raw file](https://github.com/kubernetes/kubernetes/blob/6c42e61505c4873b80354678fb211eb7b8478269/pkg/kubelet/dockershim/cm/container_manager_linux.go#L54)):*
<details><summary><i>Previously, Random-Liu (Lantao Liu) wrote…</i></summary>
> Why we only have linux implementation for this? This won't compile on other platform.
</details>
yep. forgot to add that. 

---

*[pkg/kubelet/dockershim/cm/container_manager_linux.go, line 81 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34490#-KV2_57gxdpapLvZNa9O:-KVCxy9cSEArGhlm7Xi4:b-iyk3vc) ([raw file](https://github.com/kubernetes/kubernetes/blob/6c42e61505c4873b80354678fb211eb7b8478269/pkg/kubelet/dockershim/cm/container_manager_linux.go#L81)):*
<details><summary><i>Previously, Random-Liu (Lantao Liu) wrote…</i></summary>
> Why not address the TODO now?
</details>
Sure. Didn't add it because dockershim doesn't support 1.10 and below. Will do it.

---

*[pkg/kubelet/dockershim/cm/container_manager_linux.go, line 123 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34490#-KV2dre_T8cKn9Z-UeWd:-KVCyLCuRPB_Bino22-2:bb7f2mf) ([raw file](https://github.com/kubernetes/kubernetes/blob/6c42e61505c4873b80354678fb211eb7b8478269/pkg/kubelet/dockershim/cm/container_manager_linux.go#L123)):*
<details><summary><i>Previously, Random-Liu (Lantao Liu) wrote…</i></summary>
> nit: Just return here?
</details>
done

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34490)*

**Comment by yujuhong** [comment]
Rebased and addressed comments.

**Comment by yujuhong** [comment]
@Random-Liu addressed comments. 
@dchen1107 are you ok with this?

**Comment by yujuhong** [comment]
@Random-Liu PTAL. thanks

**Comment by Random-Liu** [comment]
@yujuhong Sure, will review soon. :)

**Comment by Random-Liu** [comment]
Review status: 0 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[pkg/kubelet/dockershim/docker_service.go, line 75 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34490#-KVS2FfVz5kM9DPVPenA:-KVS2FfVz5kM9DPVPenB:b-vu8gls) ([raw file](https://github.com/kubernetes/kubernetes/blob/ab017a7a0ffc443ac30e5e0087af1c7e6fc74fe6/pkg/kubelet/dockershim/docker_service.go#L75)):*
> ```Go
> 		containerManager: cm.NewContainerManager(dockerCgroupsName, client),
> 	}
> 	if streamingConfig != nil {
> ```

At least add a TODO to consolidate streaming server start and docker service start.

---

*[pkg/kubelet/dockershim/cm/container_manager_linux.go, line 89 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34490#-KVSaykeLjPeIZ-7RhOH:-KVSaykeLjPeIZ-7RhOI:b-ivty2b) ([raw file](https://github.com/kubernetes/kubernetes/blob/ab017a7a0ffc443ac30e5e0087af1c7e6fc74fe6/pkg/kubelet/dockershim/cm/container_manager_linux.go#L89)):*
> ```Go
> 	version, err := semver.Parse(v.Version)
> 	if err != nil {
> 		glog.Errorf("Unable to parse docker version %q: %v", v.Version, err)
> ```

Should we return if there is an error?

---

*[pkg/kubelet/dockershim/cm/container_manager_unsupported.go, line 33 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34490#-KVSbGydRwXPZbEZyaKR:-KVSbGydRwXPZbEZyaKS:b-wqjq3r) ([raw file](https://github.com/kubernetes/kubernetes/blob/ab017a7a0ffc443ac30e5e0087af1c7e6fc74fe6/pkg/kubelet/dockershim/cm/container_manager_unsupported.go#L33)):*
> ```Go
> 
> func (m *unsupportedContainerManager) Start() error {
> 	return nil
> ```

Return error here? See https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/container_manager_unsupported.go#L35

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34490)*

**Comment by yujuhong** [comment]
> At least add a TODO to consolidate streaming server start and docker service start.

Streaming server `Start` hasn't been implemented yet. The constructor doesn't actually call `Start()`.


Addressed other comments.

**Comment by Random-Liu** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34490#-:-KVW3AGP_8b2aKD_KYp0:bnfp4nl)*

**Comment by yujuhong** [comment]
Rebased. Reapplying lgtm

**Pull request merged**
