### PR TITLE
Properly defaulting the status in log code

### LINKED ISSUE #16686: APIserver returns inconsistent HTTP response status codes
From kube-apiserver.log, Kube-apiserver returns 200 as Success code upon some requests, otherwise return 0 as Success.  

I1102 20:11:33.640539       5 handlers.go:131] GET /api/v1/nodes/kubernetes-minion-3io1: (2.683448ms) 200 [[kubelet/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 10.240.0.5:60298]
I1102 20:11:33.650298       5 handlers.go:131] PUT /api/v1/nodes/kubernetes-minion-3io1/status: (5.474235ms) 200 [[kubelet/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 10.240.0.5:60298]
I1102 20:11:34.705053       5 handlers.go:131] GET /api/v1/nodes: (2.139174ms) 200 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51473]
I1102 20:11:37.294175       5 handlers.go:131] GET /api/v1/nodes/kubernetes-minion-jmxr: (1.452673ms) 200 [[kubelet/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 10.240.0.3:35008]
I1102 20:11:37.302534       5 handlers.go:131] PUT /api/v1/nodes/kubernetes-minion-jmxr/status: (4.833358ms) 200 [[kubelet/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 10.240.0.3:35008]
I1102 20:11:38.218652       5 handlers.go:131] GET /healthz: (104.272µs) 0 [[Go 1.1 package http] 127.0.0.1:51479]
I1102 20:11:39.099377       5 handlers.go:131] GET /api/v1/watch/persistentvolumes?resourceVersion=1687: (9.998412938s) 0 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51469]
I1102 20:11:39.106081       5 handlers.go:131] GET /api/v1/watch/persistentvolumeclaims?resourceVersion=1687: (10.000876825s) 0 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51470]
I1102 20:11:39.119484       5 handlers.go:131] GET /api/v1/watch/persistentvolumes?resourceVersion=1687: (9.998155747s) 0 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51471]
I1102 20:11:39.202130       5 handlers.go:131] GET /api/v1/watch/namespaces?resourceVersion=1667: (59.977954152s) 0 [[heapster/v1.0.3 (linux/amd64) kubernetes/$Format] 10.240.0.5:34499]
I1102 20:11:39.708804       5 handlers.go:131] GET /api/v1/nodes: (1.471292ms) 200 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51473]
I1102 20:11:40.100355       5 handlers.go:131] GET /api/v1/persistentvolumes: (884.225µs) 200 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51473]
I1102 20:11:40.105488       5 handlers.go:131] GET /api/v1/persistentvolumeclaims: (942.355µs) 200 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51484]
I1102 20:11:40.120856       5 handlers.go:131] GET /api/v1/persistentvolumes: (1.065416ms) 200 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51486]
I1102 20:11:40.219264       5 handlers.go:131] GET /api/v1/namespaces: (1.441822ms) 200 [[heapster/v1.0.3 (linux/amd64) kubernetes/$Format] 10.240.0.5:34528]
I1102 20:11:40.332206       5 handlers.go:131] GET /api/v1/nodes: (1.958739ms) 200 [[kube-controller-manager/v1.1.1 (linux/amd64) kubernetes/f9ad30f] 127.0.0.1:51489]

### PR DESCRIPTION
**Pull request by krousey**
fixes #16686

### CODE REVIEW

**Comment by krousey** [comment]
cc @lavalamp @dchen1107

**Comment by krousey** [comment]
I verified that healthz now properly logs a 200 status.

**Comment by krousey** [comment]
@k8s-bot unit test this

**Comment by caesarxuchao** [comment]
Thank you @krousey. LGTM.

**Pull request merged**
