### PR TITLE
delete unused func in latencies.go

### PR DESCRIPTION
**Pull request by YuikoTakada**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This removes the following functions from e2e/framework/metrics/latencies.go:

HighLatencyRequests since #83322
ResetMetrics since #83322
VerifySchedulerLatency since #83322
ResetSchedulerMetrics since #83322
LogSuspiciousLatency since #83322
Ref: #84380

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thank you for the PR @YuikoTakada 
/approve
/ok-to-test
/priority backlog

**Comment by neolit123** [comment]
@YuikoTakada 
try running /hack/update-bezel.sh and commit the result too.

**Comment by YuikoTakada** [comment]
@neolit123 thank you for your comments. I'll check it.

**Review by alejandrox1 — APPROVED** [review]
/lgtm
Thank you for working on this @YuikoTakada !

**Comment by alejandrox1** [comment]
those ci failures look "flaky".
/retest

prev err:
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/84897/pull-kubernetes-e2e-gce/1192356555396222980/
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/84897/pull-kubernetes-e2e-kind/1192356555396222977
* https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/84897/pull-kubernetes-e2e-gce-100-performance/1192356555366862848/

**Comment by oomichi** [comment]
@YuikoTakada Nice work, could you remove "WIP" from the title?
That blocks a merger with `do-not-merge/work-in-progress` label.

**Pull request merged**
