### PR TITLE
Automated cherry pick of #112624: fsquota: only generate pod uuid is nil

### PR DESCRIPTION
**Pull request by pacoxu**
Cherry pick of #112624 on release-1.24.

#112624: fsquota: only generate pod uuid is nil

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by mattcary** [comment]
FYI there is some open conversation on #112624 still, is that the reason for the hold?

**Comment by pacoxu** [comment]
> FYI there is some open conversation on #112624 still, is that the reason for the hold?

Yes. This fix may not fix the whole issue and we may wait https://github.com/kubernetes/kubernetes/pull/115314.

**Comment by mattcary** [comment]
> > FYI there is some open conversation on #112624 still, is that the reason for the hold?
> 
> Yes. This fix may not fix the whole issue and we may wait #115314.
👍

**Pull request closed without merging**
