### PR TITLE
Remove Ipaddress uid

### PR DESCRIPTION
**Pull request by aojea**
Don't use the UID in the IPAddress object reference, the IPAddress is unique, and if the Object referenced has been deleted and recreated and no longer uses the IPAddress the controller has to ensure the IPAddress object is deleted and it can not be mutated

/kind cleanup
```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @danwinship @thockin 

https://github.com/kubernetes/kubernetes/pull/116516/commits/bac6c11e4bbf19081c2d9c3302d7da976e85b1ac#r1348962407

**Comment by danwinship** [comment]
> Don't use the UID in the IPAddress object reference, the IPAddress is unique, and if the Object referenced has been deleted and recreated and no longer uses the IPAddress the controller has to ensure the IPAddress object is deleted and it can not be mutated

I'm not sure what you're saying there, but the relevant point is that we aren't using the field and don't intend to use it.

/lgtm

**Comment by aojea** [comment]
> I'm not sure what you're saying there, but the relevant point is that we aren't using the field and don't intend to use it.

there is no much point in using UID for references , is complicated also to try to explain why you'll need to use them XD

**Comment by thockin** [comment]
UID is a ref is useful when we need to know that the referent has not been deleted and recreated.  Is there any risk here, where an IPAddress declares a parent and that parent is sneakily removed and recreated?  Can we think up any way that could cause a problem?  @aojea 

If not, clear the hold.

/approve
/hold

**Comment by aojea** [comment]
> UID is a ref is useful when we need to know that the referent has not been deleted and recreated. Is there any risk here, where an IPAddress declares a parent and that parent is sneakily removed and recreated? Can we think up any way that could cause a problem? @aojea

With Services it can not happen,
1. if the Service is recreated with the same IP will fail, because already exist an IPAddress object with that IP
2. if the Service gets a different IP the reconciler will detect the mismatch, Service > ClusterIP > IPAddress2 will be ok but IPAddress > Service xxx ClusterIP will fail

If another object wants to use IPAddresses it has somehow to implement some logic to keep the 1to1 relation, so the UID is just not adding much value, the only thing I can think about is if the Object is different and keeps the same IP, at least not having the UID as reference will allow the controller to not have to delete the IPAddress and recreate to update the new Reference (remember IPaddress.Spec is inmutable)

**Pull request merged**
