### PR TITLE
[Kubelet] Update registry related settings

### PR DESCRIPTION
**Pull request by dims**
We should consider updating our Kubelet's defaults for accessing registries. The defaults reflect the situation with registries many years ago when they were slow and had trouble handling larger traffic. for example, EKS sets the values picked in this PR which has been working fine for a while.

- "serialize-image-pulls" from `true` to `false`
- "registry-qps" from `5` to `20`
- "registry-burst" from `10` to `40`

[1] https://github.com/awslabs/amazon-eks-ami/blob/master/doc/USER_GUIDE.md#customizing-kubelet-config

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### What type of PR is this?
/kind feature

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Kubelet's Registry related settings have been updated. "serialize-image-pulls" is now false to allow multiple images to be pulled at the same time. "registry-qps" and "registry-burst" have been updated to 20 and 40 respectively (from 5 and 10)
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/sig node
/assign @SergeyKanzhelev @mrunalp @mikebrow 

Not in a rush to land this, opening the conversation here. Hoping folks will chime in with their experiences.

**Comment by dims** [comment]
> @dims please fix CI failures

thanks! doing that now.

**Comment by pacoxu** [comment]
Thanks for the PR and this would fix https://github.com/kubernetes/kubernetes/issues/108405.
+1 to do this. especially `"serialize-image-pulls" from true to false`.

For registry-burst and registry-qps, as we proposed in https://github.com/kubernetes/enhancements/pull/3713/ and discussed at https://github.com/kubernetes/kubernetes/issues/112044. It may not be a bottleneck for users for it is not a real node-level parallel image-pulling limit.

**Comment by SergeyKanzhelev** [comment]
/assign @ruiwen-zhao

I understand `serialize-image-pulls` can cause performance issues without https://github.com/kubernetes/enhancements/pull/3713. Is the change of default something we can do as part of the KEP to be on a safe side?

In general lgtm though

**Comment by smarterclayton** [comment]
Have we changed kubelet defaults before?  Defaults are generally part of the API compatibility guarantees and changing these has the potential to regress an installation on upgrade.

Recommending these changes to consumers seems reasonable in documentation and our install guides regardless of the above.

**Comment by ruiwen-zhao** [comment]
> /assign @ruiwen-zhao
> 
> I understand `serialize-image-pulls` can cause performance issues without [kubernetes/enhancements#3713](https://github.com/kubernetes/enhancements/pull/3713). Is the change of default something we can do as part of the KEP to be on a safe side?
> 
> In general lgtm though

I still prefer keep the default as is in [kubernetes/enhancements#3713](https://github.com/kubernetes/enhancements/pull/3713), i.e. keeping serial pull as default. My rationale is that changing the default might be breaking for some users, and we need to make sure proper communication happen beforehand. That communication itself might take some effort and I would avoid mixing it with [kubernetes/enhancements#3713](https://github.com/kubernetes/enhancements/pull/3713).

**Comment by pacoxu** [comment]
> Have we changed kubelet defaults before? Defaults are generally part of the API compatibility guarantees and changing these has the potential to regress an installation on upgrade.

@smarterclayton I tried to read the kubelet configuration default.go change history and find some.

1. https://github.com/kubernetes/kubernetes/commit/0064010cddfa009fe16ae23fcd0c57f4f15d227c#diff-64312739de7a7da86a275e2ada9e0caf61e826c20b90ffbb6c1bafa464d15fcf after feature gate was promoted, switch a bool from false to true.
2. https://github.com/kubernetes/kubernetes/pull/111520 changed 100ms to 100us, but reverted for CI failures.
3. https://github.com/kubernetes/kubernetes/pull/74781 configMapAndSecretChangeDetectionStrategy is changed from `Cache` to `Watch`

For the bool flag, I think it is quite similar to a feature gate.
- false in alpha, which is disabled by default.
- true in beta or GA, which is enabled by default. This should happen if it meet some bars to promote the feature to Beta/GA.

I listed some related issues and features at https://github.com/kubernetes/kubernetes/issues/108405. Overall, beta should be reasonable.

**Comment by SergeyKanzhelev** [comment]
@smarterclayton and @ruiwen-zhao arguments convinced me that keeping defaults as-is may be a good idea. Another default we need to recommend is: https://github.com/kubernetes/kubernetes/pull/98207

**Comment by dims** [comment]
Let me close this and we can continue in the other locations/KEPs

**Pull request closed without merging**
