### PR TITLE
controller: a couple of fixes for csr

### PR DESCRIPTION
**Pull request by 0xmichalis**
Fixes:
- delete resource handler wasn't taking into account tombstones
- csr would requeue twice on update failure

@deads2k @mikedanese ptal

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33001)

### CODE REVIEW

**Comment by errordeveloper** [comment]
cc @yifan-gu @gtank @aaronlevy @kubernetes/sig-cluster-lifecycle

**Comment by deads2k** [comment]
lgtm

**Comment by kargakis** [comment]
@k8s-bot test this issue: https://github.com/kubernetes/kubernetes/issues/32770

**Comment by errordeveloper** [comment]
Should this get cherry-picked? To me it sound like this a good fix to go into 1.4.

**Comment by mikedanese** [comment]
@kargakis Thanks for fixing.

**Comment by mikedanese** [comment]
@errordeveloper there shouldn't be much of a negative affect to this since the sync loop is idempotent

**Comment by errordeveloper** [comment]
Ack.

**Pull request merged**
