### PR TITLE
kube-up: prevent the encryption secret from being empty in GCE clusters

### LINKED ISSUE #71908: cluster/kube-up.sh failed while waiting for the API to be reachable
**What happened**:

Following the document, [Running Kubernetes on Google Compute Engine](https://kubernetes.io/docs/setup/turnkey/gce/), `cluster/kube-up.sh` failed.

```
$ cluster/kube-up.sh
... Starting cluster in us-central1-b using provider gce
... calling verify-prereqs
... calling verify-kube-binaries
... calling verify-release-tars
... calling kube-up
.
.
.
Using master: kubernetes-master (external IP: 35.224.164.246)
Waiting up to 300 seconds for cluster initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This may time out if there was some uncaught error during start up.

........................................................................................................................................Cluster failed to initialize within 300 seconds.
Last output from querying API server follows:
-----------------------------------------------------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 35.224.164.246 port 443: Connection refused
-----------------------------------------------------
```

Error logs below were written on kubernetes-master instance.

```
$ grep ^error /var/log/kube-apiserver.log 
error: error while parsing encryption provider configuration file "/etc/srv/kubernetes/encryption-provider-config.yml": key key1 has no provided secret
```
Secret value is null.
```yaml
$ cat /etc/srv/kubernetes/encryption-provider-config.yml
kind: EncryptionConfiguration
apiVersion: apiserver.config.k8s.io/v1
resources:
  - resources:
    - secrets
    providers:
    - aesgcm:
        keys:
        - name: key1
          secret: 
```

**What you expected to happen**:

Referring to [cluster/gce/config-default.sh#L221-L232](https://github.com/kubernetes/kubernetes/blob/396271cf52af70bc96ed378dd9ce1a865cc99647/cluster/gce/config-default.sh#L221-L232), `encryption-provider-config.yml` should be like this.

```yaml
kind: EncryptionConfiguration
apiVersion: apiserver.config.k8s.io/v1
resources:
  - resources:
    - secrets
    providers:
    - aesgcm:
        keys:
        - name: key1
          secret: +c6JL+0CBPoUhP2Ply9smxBrm+jH18feXmDEMh+gj+8=
```

**How to reproduce it (as minimally and precisely as possible)**:

```bash
$ curl -sS https://get.k8s.io | bash
$ cd kubernetes
$ cluster/kube-up.sh
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.0
- Cloud provider or hardware configuration: GCE
- OS (e.g. from /etc/os-release):
```
$ cat /etc/os-release
BUILD_ID=10323.64.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=94bdaa2af49562e7aba0168cae050911d105f5cb
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=65
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=65
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
```
- Kernel (e.g. `uname -a`):
```
$ uname -a
Linux kubernetes-master 4.4.111+ #1 SMP Wed Mar 28 13:44:38 PDT 2018 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux
```
- Install tools: `cluster/kube-up.sh`
- Others:

/kind bug

### PR DESCRIPTION
**Pull request by pires**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

The `dd` binary bundled with `macOS` doesn't support the `iflags` operand, causing the generated encryption secret to be empty and consequently KAS to fail. This PR makes `kube-up.sh` prefer `gdd` whenever present, falling back to `dd`. It additionally introduces validation of the generated secret and  instructions on how to proceed shall it still be found to be empty. 

**Which issue(s) this PR fixes**:

Fixes #71908

**Special notes for your reviewer**:

cc @kubernetes/sig-gcp-pr-reviews 

**Does this PR introduce a user-facing change?**:

```release-note
kube-up: prevent the encryption secret from being empty in GCE clusters
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
i think we should add release note closer to the the PR title, to indicated we are adding a fix for kube-up?
/priority backlog

**Comment by pires** [comment]
I'm just following the PR template, as always.

**Comment by pires** [comment]
Any updates on this?

**Comment by jbeda** [comment]
I’m happy to merge this as is.  But we have a similar situation with tar and handle it by detecting if we can find gnu tar — https://github.com/kubernetes/kubernetes/blob/a7a6bf4386f260a9325cb4b7f4c812bcea2d2382/build/common.sh#L278.  Let me know which you prefer.  Also feel free to ping me on twitter/slack as I’m bad at github these days.

**Comment by pires** [comment]
Interesting. I think I like the solution you propose better, meaning, move `dd` validation directly into `common.sh` and just make sure we validate before this thing runs. I'll ping you over twitter/slack as soon as I'm able to get it done - hopefully, tomorrow morning.

Thanks a lot, Joe 🙇

**Comment by pires** [comment]
@jbeda thank you very much for taking time to look into this. After looking more deeply at the current state of things, this PR is actually no longer needed as [the only `dd` operation](https://github.com/kubernetes/kubernetes/blob/master/build/common.sh#L422) is now compatible with MacOS `dd`.
I am sorry for wasting your time.

**Comment by jbeda** [comment]
Glad it is working now!

**Pull request closed without merging**
