### PR TITLE
Updated Gophercloud to fix indirect dependency issues

### PR DESCRIPTION
**Pull request by spothanis**
This is to fix
https://github.com/kubernetes/kubernetes/issues/13565
@saad-ali @eparis

### CODE REVIEW

**Comment by saad-ali** [comment]
Thanks @spothanis 
LGTM

Could you rebase. A test fix went in fixing the shippable flake.

**Comment by saad-ali** [comment]
Sorry, one more rebase required (to pick up #14372).

**Comment by mikedanese** [comment]
Has the release been cut? We should cherry-pick this into v1.1.

**Comment by saad-ali** [comment]
> Has the release been cut?

No, I don't believe it has.

**Comment by spothanis** [comment]
sure

**Comment by spothanis** [comment]
shippable is unhappy again :), rebase?

**Comment by saad-ali** [comment]
All good and ready to merge (sadly we're in a merge freeze).

**Pull request merged**
