### PR TITLE
remove service.deletecollection since the server doesn't support it

### PR DESCRIPTION
**Pull request by deads2k**
Updates the generated service client to match the API available.

@kubernetes/sig-api-machinery-pr-reviews 
@kubernetes/api-reviewers 

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
Does the namespace client have the same issue?

**Comment by deads2k** [comment]
> Does the namespace client have the same issue?

I don't know.  This came in off a bug report.  Does it?

**Comment by liggitt** [comment]
> If you know/knew phrasing it as a question is a little obnoxious. Updated.

sorry, I knew namespaces didn't support delete collection. I didn't know if the namespace client had already been updated to skip this method as well.

/lgtm

**Pull request merged**
