### PR TITLE
Fix networking test

### PR DESCRIPTION
**Pull request by lavalamp**
Remove the dependency on the RO port.

### CODE REVIEW

**Comment by vmarmol** [comment]
Networking e2e passed?

**Comment by lavalamp** [comment]
I ran just this test manually, I can run it the official way tomorrow if you're nervous.

**Comment by quinton-hoole** [comment]
BTW, the failure in Jenkins looks as below.  Essentially the test pod fails to start. I'll try to repro locally for debugging purposes.

INFO: Waiting for pod nettest-0 in namespace e2e-tests-nettest-13fd880b-a01a-4325-bbf3-3a0eace611a1 status to be "running" (found "Pending") (15.02196219s)
INFO: Waiting for pod nettest-0 in namespace e2e-tests-nettest-13fd880b-a01a-4325-bbf3-3a0eace611a1 status to be "running" (found "Failed") (20.030619573s)

**Comment by quinton-hoole** [comment]
Since reverting this PR, we now have a different problem, in that the test is taking too long and timing out.  It's progressing, by the looks of things.  Just taking far too long.

Networking 
  should function for intra-pod communication
..... [irrelevant stuff deleted] .....
INFO: Proxy status call returned in 4.861944ms
INFO: Attempt 35/60: test still running
INFO: About to make a proxy status call
Build timed out (after 90 minutes). Marking the build as aborted.
Build timed out (after 90 minutes). Marking the build as failed.

Ran 40 of 46 Specs in 5069.444 seconds
FAIL! -- 18 Passed | 0 Failed | 1 Pending | 5 Skipped Build was aborted
Recording test results

**Comment by lavalamp** [comment]
Very sorry for breaking this. Not sure why my manual test gave a different result.

**Pull request merged**
