### PR TITLE
[scheduler cleanup phase 2]: Rename `pkg/scheduler/cache` to `pkg/scheduler/nodeinfo`

### PR DESCRIPTION
**Pull request by yuexiao-wang**
Signed-off-by: yuexiao-wang wang.yuexiao@zte.com.cn

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Nearly all of the "cache" functionality has been moved from this package into pkg/scheduler/internal/cache. 
Rename `pkg/scheduler/cache` to `pkg/scheduler/nodeinfo`
 

**Which issue(s) this PR fixes**:

Fixes # https://github.com/kubernetes/kubernetes/issues/71862

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yuexiao-wang** [comment]
@misterikkit  PTAL

**Review by yagonobre — COMMENTED** [review]
Thanks @yuexiao-wang 
/ok-to-test

**Comment by yuexiao-wang** [comment]
@yagonobre Thanks

**Comment by wgliang** [comment]
Just a rename action.
/lgtm
thanks @yuexiao-wang

**Review by bsalamat — COMMENTED** [review]
/lgtm
/approve

**Review by misterikkit — CHANGES_REQUESTED** [review]
Looks like you need to update the `package` statements inside the new package.

**Comment by yuexiao-wang** [comment]
I have updated the ·package· statements inside the new packages.
@misterikkit @bsalamat @wgliang PTAL

**Comment by misterikkit** [comment]
/lgtm

With so many people at kubecon, it may be difficult to get approvers for the other packages.

@wojtek-t Would you be willing to use your global approve powers on this mechanical name change PR?

**Pull request merged**
