### PR TITLE
update kube-openapi

### LINKED ISSUE #315: Deserializing into `spec.Swagger` is almost 20x slower than deserializing into `map[string]interface{}`
Running the following benchmark on my laptop:
```
const openapipath = "api/openapi-spec/swagger.json"

func BenchmarkJsonUnmarshalSwagger(b *testing.B) {
	content, err := os.ReadFile(openapipath)
	if err != nil {
		b.Fatalf("Failed to open file: %v", err)
	}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		t := spec.Swagger{}
		err := json.Unmarshal(content, &t)
		if err != nil {
			b.Fatalf("Failed to unmarshal: %v", err)
		}
	}
}

func BenchmarkJsonUnmarshalInterface(b *testing.B) {
	content, err := os.ReadFile(openapipath)
	if err != nil {
		b.Fatalf("Failed to open file: %v", err)
	}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		t := map[string]interface{}{}
		err := json.Unmarshal(content, &t)
		if err != nil {
			b.Fatalf("Failed to unmarshal: %v", err)
		}
	}
}
```

Yields the following results:
```
apelisse ~/code/kubernetes/bench_api_parsing> go test -bench=. .
goos: darwin
goarch: amd64
pkg: k8s.io/kubernetes/bench_api_parsing
cpu: Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
BenchmarkJsonUnmarshalSwagger-8     	       3	 529833040 ns/op
BenchmarkJsonUnmarshalInterface-8   	      37	  29475772 ns/op
PASS
ok  	k8s.io/kubernetes/bench_api_parsing	5.013s
```
For readability purposes, that's 529ms and 29ms respectively.

For context, this is about [`spec.Swagger`](https://github.com/kubernetes/kube-openapi/blob/master/pkg/validation/spec/swagger.go#L24-L32), the OpenAPI v2 definition which is mostly a clone of [`go-openapi`](https://github.com/go-openapi/spec)

After a short investigation, the problem seems fairly obvious: the [arbitrary vendor extensions](https://github.com/kubernetes/kube-openapi/blob/a70c9af30aea67d5b769998c5e3f18458b277e72/pkg/validation/spec/info.go#L91-L93) (as defined by [OpenAPI](https://swagger.io/docs/specification/openapi-extensions/)) forces the json to be deserialized multiple times, at many different levels within the object, causing the deserialization into `spec.Swagger` to reach `O(n²)` complexity (my maths is probably dubious).

Vendor extensions can appear at many different layers in the OpenAPI object, e.g. in:
- [`spec.Swagger`](https://github.com/kubernetes/kube-openapi/blob/master/pkg/validation/spec/swagger.go#L30)
- [`spec.Header`](https://github.com/kubernetes/kube-openapi/blob/master/pkg/validation/spec/header.go#L38)
- [`spec.Paths`](https://github.com/kubernetes/kube-openapi/blob/master/pkg/validation/spec/paths.go#L31)
- [`spec.Operations`](https://github.com/kubernetes/kube-openapi/blob/master/pkg/validation/spec/operation.go#L72)
- And many others ...

The problem, or lack of good solutions, comes from the rigid API (`UnmarshalJSON(data []byte) error`) that forces the custom unmarshaler to receive a byte slice rather than an already decoded, or temporary format. Deserializing methods that do use more flexible APIs, like them YAML v3 parser (`UnmarshalYAML(value *yaml.Node) error`), do not suffer of the same problem, as highlighted through #279 from @alexzielenski.

This bug, which was improperly understood until now, has had various consequences on the entire Kubernetes ecosystem for the last 5 years:
1. Because deserializing into `spec.Swagger` was unacceptably slow for frequently invoked command-line tools, kubectl decided to use `gnostic`/`protobuf` even though the gnostic type is grossly unusable.
2. #283 was written to transform `gnostic` into `spec.Swagger` efficiently, but the `Swagger` to `gnostic` would also be needed, as well as a OpenAPI v3 version.
3. So many issues have been written about poor Kubernetes apiserver performance related to parsing/serializing OpenAPI into/from json within the server, with various work-arounds like lazy-marshaling. e.g. #251

Many of this was noticed by customers, users and Kubernetes providers, as the evidence can show:
- https://jonnylangefeld.com/blog/the-kubernetes-discovery-cache-blessing-and-curse
- https://blog.upbound.io/scaling-kubernetes-to-thousands-of-crds/
- https://www.youtube.com/watch?v=jYiLN0vmncw

As an example of why this is important for the apiserver, here's a graph showing the way the OpenAPI is (over-)serialized/deserialized:
2022 OpenAPI Wiring

For now, the solution discussed with @liggitt is to create a new `UnmarshalUnstructured(interface{}) error` interface that could replace the slow `UnmarshalJSON` interface, maybe like the following:
```golang
// UnmarshalJSON unmarshals a swagger spec from json
func (s *Swagger) UnmarshalJSON(data []byte) error {
	var sw Swagger
	var i interface{}{}
	if err := json.Unmarshal(data, &i); err != nil {
		return err
	}
	if err := FromUnstructured(i, &sw.SwaggerProps); err != nil {
		return err
	}
	if err := FromUnstructured(i, &sw.VendorExtensible); err != nil {
		return err
	}
	*s = sw
	return nil
}
```
And `FromUnstructured` would automatically call the `UnmarshalUnstructured` methods when available. One drawback is that it forces it to deserialize into a `map[string]interface{}` first and then copy, which is possibly slower than deserializing into the object directly.

A remark for the end, the exact same problem also applies to serialization/marshaling, though it is less critical.

### PR DESCRIPTION
**Pull request by alexzielenski**
Brings in an optimized json parser for openapi. See https://github.com/kubernetes/kube-openapi/issues/315, https://github.com/kubernetes/kube-openapi/issues/319 

```shell
hack/pin-dependency.sh k8s.io/kube-openapi=github.com/alexzielenski/kube-openapi json_next
hack/update-vendor.sh
```

#### What type of PR is this?

/kind feature

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kube-openapi/issues/315

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig api-machinery
/cc @apelisse @liggitt

### CODE REVIEW

**Comment by apelisse** [comment]
Not important, but your original description of the PR is not accurate anymore :-)
/lgtm
/approve
/assign @liggitt 
/priority important-soon

**Comment by apelisse** [comment]
/lgtm cancel

I missed the explain file that sneaked in :-)

**Comment by alexzielenski** [comment]
;)

**Comment by liggitt** [comment]
sounds good
/hold cancel

**Pull request merged**
