### PR TITLE
Fix kubeadm e2e CI build

### LINKED ISSUE #54330: Kubeadm E2E test using weave-net is broken with CNI version bump
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Kubeadm E2E test is currently broken due to the commit https://github.com/kubernetes/kubernetes/pull/51250. I report the same issue on my local cluster. If I revert PR 51250, everything works fine. We believe the current weave-net plugin doesn't work with the CNI version change.

Right now all kubeadm related development is blocked on this. Could we consider reverting this change from head until we figure out what's wrong in weave-net/CNI? 

More context in https://github.com/kubernetes/kubernetes/issues/54180

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:

This fixes kubeadm e2e tests; the tarfile was extracted to the wrong directory in #51250.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

fixes: https://github.com/kubernetes/kubernetes/issues/54330

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
@ixdy @pipejakob @kubernetes/sig-cluster-lifecycle-bugs @medinatiger @dims @cmluciano @dixudx

### CODE REVIEW

**Review by timothysc — APPROVED** [review]
/lgtm

**Comment by luxas** [comment]
FWIW: This fixes the build, see https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/54573/pull-kubernetes-e2e-kubeadm-gce/8612/

**Comment by ixdy** [comment]
lgtm2, thanks!

**Comment by dims** [comment]
Verified on another PR. 👍

**Comment by dixudx** [comment]
Thanks @luxas

**Pull request merged**
