### PR TITLE
 Update sidecar controllers to latest versions in the e2e 

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

/kind bug

```release-note
NONE
```

### CODE REVIEW

**Comment by humblec** [comment]
> In the PR description, can you add that hostpath images are not updated yet? Also what about snapshot-controller image?

@xing-yang I have updated hostpath images too. Also updated the snapshot controller in addons dir. ptal..  Did I miss any other paths to update?

**Comment by xing-yang** [comment]
We have not cut images for CSI hostpath driver and node-driver-registrar and livenessprobe sidecars following the 1.25 release yet, but I'm fine to get this merged first.

**Pull request merged**
