### PR TITLE
Replace instances of v1beta1 with v1beta3

### PR DESCRIPTION
**Pull request by RichieEscarez**
Per issue 7502, replaced all instances of “v1beta1/proxy” with
“v1beta3/proxy/namespaces/default” and “v1beta1/redirect” with
“v1beta3/redirect/namespaces/default”. Also removed all trailing ‘/‘
forward slashes.

### CODE REVIEW

**Comment by satnam6502** [comment]
Can you delete the section which contains:
```
$ cat ~/.kube/kubernetes-satnam2_kubernetes/kubernetes_auth
{
  "User": "admin",
  "Password": "4mty0Vl9nNFfwLJz",
  "CAFile": "/Users/satnam/.kube/kubernetes-satnam2_kubernetes/kubernetes.ca.crt",
  "CertFile": "/Users/satnam/.kube/kubernetes-satnam2_kubernetes/kubecfg.crt",
  "KeyFile": "/Users/satnam/.kube/kubernetes-satnam2_kubernetes/kubecfg.key"
}
```
and replace it with the use of `kubectl config view` for obtaining the basic authentication username and password? Thansk. @roberthbailey

**Comment by RichieEscarez** [comment]
The section you refer to above that you want replaced with `kubectl config view' was done with pull request 7956. Should i instead combine all changes into one branch/one PR?

**Comment by satnam6502** [comment]
If you write a # symbol in front of the number 7956 it forms a link #7956

**Comment by satnam6502** [comment]
OK, let's wait for the other PR to merge, and then you can rebase this one -- otherwise it is too hard for me to understand what is going on!
Any idea why your CLA is not approved yet?

**Comment by RichieEscarez** [comment]
ICLA signed (requirement for contractors)

**Comment by satnam6502** [comment]
Can you re-base your other merged PR? Something like this I think:
```
$ fetch upstream
$ rebase upstream/master
$ push -f origin 7094-v1beta1_to_v1beta3
```

**Comment by RichieEscarez** [comment]
I did author these commits.

**Comment by satnam6502** [comment]
Note that you have other people's commits in here. Please can you:
```
$ git rebase -i HEAD^10
```
and delete the other commits? Thanks.

**Comment by satnam6502** [comment]
I propose that you change:
```
To access a service endpoint /alpha/beta/gamma/ via the proxy service for your service myservice you need to specify an HTTPS address for the Kubernetes master followed by /api/v1beta3/proxy/namespaces/default/services/myservice/alpha/beta/gamma.
```
to:
```
To access a cluster service endpoint via the proxy you should prefix the name of the service with /api/v1beta3/proxy/namespaces/default/services e.g. /api/v1beta3/proxy/namespaces/default/services/elasticsearch and /api/v1beta3/proxy/namespaces/default/services/elasticsearch/_search?q=user:kimchy
```

**Pull request merged**
