### PR TITLE
Make KubeProxy test faster

### PR DESCRIPTION
**Pull request by ArtfulCoder**
#14206

### CODE REVIEW

**Comment by ArtfulCoder** [comment]
Test takes about 4.5 to 5 mins to run

**Comment by thockin** [comment]
LGTM

**Comment by thockin** [comment]
@k8s-bot test this please

**Comment by ArtfulCoder** [comment]
will increase the test sleep time

**Comment by thockin** [comment]
@k8s-bot test this please

**Comment by thockin** [comment]
@k8s-bot test this

**Comment by ArtfulCoder** [comment]
Increased timeout value for LB setup (from 45 seconds to 120 seconds)

**Comment by ArtfulCoder** [comment]
@k8s-bot test this

**Comment by erictune** [comment]
@ArtfulCoder rebase this to pick up other test flake fixes so this can pass Shippable.

**Comment by ArtfulCoder** [comment]
done

**Comment by ixdy** [comment]
This test is still taking 10m+ in the pull request jenkins: https://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce/9870/testReport/(root)/Kubernetes%20e2e%20suite/KubeProxy_should_test_kube_proxy/history/

**Comment by ixdy** [comment]
The post-submit parallel gce is also showing 10m+ runtimes: https://goto.google.com/k8s-test/job/kubernetes-e2e-gce-parallel/8298/testReport/(root)/Kubernetes%20e2e%20suite/KubeProxy_should_test_kube_proxy/history/

**Pull request merged**
