### PR TITLE
Rename kubedns-deployment.yaml in hack/local-up-cluster.sh for consistency

### PR DESCRIPTION
**Pull request by shashidharatd**
**What this PR does / why we need it**:

~~- Adds namespace for kube-dns service account explicitly (to be consistencet with kubedns-controller and kubedns-svc).~~
- Rename kubedns-deployment.yaml to kubedns-controller.yaml in hack/local-up-cluster.sh  for naming consistency.

**Special notes for your reviewer**:
This PR is purely `good to have` and the functions work perfectly fine without these changes.

cc @deads2k

### CODE REVIEW

**Comment by deads2k** [comment]
I'm not sure about pinning the namespace name.  I haven't fully considered it, but it seems like we'd be well served by separating the add-ons by namespace.


I like the file rename in local-up though.

**Comment by shashidharatd** [comment]
yeah fair enough. alternatively we should be removing the namespace from the addons, but its a lot of change for now. so lets hold back this change for now.

**Comment by shashidharatd** [comment]
@k8s-bot unit test this
@k8s-bot cvm gce e2e test this

**Comment by shashidharatd** [comment]
@k8s-bot cvm gce e2e test this

**Comment by shashidharatd** [comment]
@k8s-bot cvm gce e2e test this

**Comment by shashidharatd** [comment]
Closing this as it is trivial and will be taken care of when #42832 is addressed.

**Pull request closed without merging**
