### PR TITLE
Fixed nil dereference in dynamic provisioning e2e tests

### LINKED ISSUE #52815: DynamicProvisioner E2E slow tests failing
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

A couple of `DynamicProvisioner` tests the the `slow` GKE and GCE suites have been consistently failing since yesterday. See [testgrid](https://k8s-testgrid.appspot.com/google-gke#gci-gke-slow&include-filter-by-regex=DynamicProvisioner)

**What you expected to happen**:
Tests should pass.

**How to reproduce it (as minimally and precisely as possible)**:
Look at failing tests.

**Anything else we need to know?**:
The failing tests correspond to the merge of https://github.com/kubernetes/kubernetes/pull/52350

CC @wongma7 @kubernetes/sig-storage-test-failures @kubernetes/sig-storage-bugs

### PR DESCRIPTION
**Pull request by verult**
**What this PR does / why we need it**: Fixed nil dereference in dynamic provisioning e2e tests.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #52815

**Release note**:

```release-note-none
```
/sig storage
/assign @saad-ali 
/cc @wongma7 
/release-note-none

### CODE REVIEW

**Comment by wongma7** [comment]
lgtm, thanks! i overlooked the beta/default tests.

**Review by wongma7 — APPROVED** [review]

**Comment by verult** [comment]
/test pull-kubernetes-unit

https://github.com/kubernetes/kubernetes/issues/52818

**Comment by saad-ali** [comment]
Thanks for jumping on this quickly and saving the day @verult!

/lgtm
/approve

**Comment by xiangpengzhao** [comment]
/release-note-none

This PR doesn't need a release note. A release-note label will lead to noise in CHANGELOG.

**Pull request merged**
