### PR TITLE
use versioned configuration for podnodeselector

### PR DESCRIPTION
**Pull request by wackxu**
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

parts of https://github.com/kubernetes/kubernetes/issues/57424
xref https://github.com/kubernetes/kubernetes/issues/57424#issuecomment-360334419

**Special notes for your reviewer**:
/assign @liggitt 

**Release note**:

```release-note
use versioned configuration for podnodeselector
```

### CODE REVIEW

**Comment by wackxu** [comment]
@liggitt Could you take a look? This fix the second part 

> Should probably drop the alpha from the annotations and include in well known annotations constants
Also need to update the admission plugin config to read from a versioned config object

**Comment by wanghaoran1988** [comment]
Could you please squash  your commits into two commits, one for the main changes, another for generated? for easyly review.

**Comment by wackxu** [comment]
@wanghaoran1988 Updated， PTAL， Thanks for your review.

**Comment by derekwaynecarr** [comment]
can you update so tests pass?

thank you for improving this area.  all admission configuration should be versioned.

**Pull request closed without merging**
