### PR TITLE
Fix capitalization of Kubernetes in the docs

### PR DESCRIPTION
**Pull request by a-robinson**

### CODE REVIEW

**Comment by thockin** [comment]
LGTM

**Comment by davidopp** [comment]
I don't have time to review this as I'm reviewing three of Brendan's docs. If Tim said it looks good, let's go with that.

**Comment by thockin** [comment]
I actually looked at it.

On Mon, Jul 20, 2015 at 2:26 PM, David Oppenheimer <notifications@github.com

**Comment by krousey** [comment]
@a-robinson Please rebase and squash as there are now conflicts.

**Comment by a-robinson** [comment]
Squashed and rebased

**Pull request merged**
