### PR TITLE
vendor: upgrade cadvisor to 0.39.2

### LINKED ISSUE #99230: Failing kubelet /stats/summary API and ResourceMetricsAPI tests on cgroup v2
#### Which jobs are failing:
pull-kubernetes-node-crio-cgrpv2-e2e

#### Which test(s) are failing:
E2eNode Suite: [k8s.io] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api
E2eNode Suite: [k8s.io] ResourceMetricsAPI [NodeFeature:ResourceMetrics] when querying /resource/metrics should report resource usage through the resource metrics api

#### Since when has it been failing:
From what I have observed these tests have always failed on cgroup v2 host.

#### Testgrid link:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/99110/pull-kubernetes-node-crio-cgrpv2-e2e/1361561789094957056/

#### Reason for failure:
cgroup v2 has a different set of files compared to cgroup v1 to report the metrics. A lot of places in cadvisor, where the metrics end up getting read from, still assume cgroup v1 paths and files. 

#### Anything else we need to know:
Some of the following PRs end up addressing the issue partially, but not completely. 

https://github.com/google/cadvisor/pull/2801
https://github.com/google/cadvisor/pull/2800

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

inherit some fixes for cgroup v2 from cAdvisor that are needed for the e2e tests:

https://github.com/google/cadvisor/pull/2837
https://github.com/google/cadvisor/pull/2839

#### Which issue(s) this PR fixes:

Fixes #99230

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by giuseppe** [comment]
all green!

@dims @soltysh @sttts  PTAL

**Comment by dims** [comment]
/approve
/lgtm

@giuseppe can you please add a little more works into the PR with links to the bug being fixed in cadvisor that we need to pull in here?

**Comment by giuseppe** [comment]
> @giuseppe can you please add a little more works into the PR with links to the bug being fixed in cadvisor that we need to pull in here?

sure, I've added a link to the issues addressed in cAdvisor

**Comment by giuseppe** [comment]
@kolyshkin FYI

**Comment by dims** [comment]
@giuseppe don't we need the new changes in `runc` repo filed in the last couple of days? (for the metrics issue for disk io stuff)

**Comment by giuseppe** [comment]
> @giuseppe don't we need the new changes in `runc` repo filed in the last couple of days? (for the metrics issue for disk io stuff)

These fixes are not related to the disk io metrics issues fixed in runc upstream.  Do we need to wait for a new tag to inherit the runc fixes though?  I am fine to also bump runc if it is allowed

**Comment by kolyshkin** [comment]
@giuseppe I _think_ this fixes https://github.com/kubernetes/kubernetes/issues/99230, might need to be added to the summary

**Pull request merged**
