### PR TITLE
Promote OpenAPI V3 to GA

### PR DESCRIPTION
**Pull request by Jefftree**
/kind feature

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Promoted `OpenAPIV3` to GA
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
/triage accepted
/cc @lavalamp @deads2k @apelisse

### CODE REVIEW

**Comment by apelisse** [comment]
Looks good to me, thanks

**Comment by rjsadow** [comment]
/release-note-edit

```release-note Promoted `OpenAPIV3` to GA```

**Comment by lavalamp** [comment]
I'll approve and let @deads2k lgtm?

/approve

**Comment by deads2k** [comment]
Glad to see this wrapping up.

/lgtm

**Pull request merged**
