### PR TITLE
Remove duplicated content

### PR DESCRIPTION
**Pull request by vflong**
Signed-off-by: weifeilong <weifeilong2013@gmail.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #
https://github.com/kubernetes/kubernetes/issues/97140
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
Thanks @vflong! Could you sign the CLA?

/ok-to-test
/release-note none

**Comment by vflong** [comment]
I signed it

**Review by SataQiu — COMMENTED** [review]
Thanks @vflong !
/lgtm

**Pull request closed without merging**
