### PR TITLE
Fix kubernetes-mesos issue 342: pod readiness bug

### PR DESCRIPTION
**Pull request by jdef**
- regression introduced by rebasing work performed for #8882
- see https://github.com/mesosphere/kubernetes-mesos/issues/342
- depends #9710

### CODE REVIEW

**Comment by davidopp** [comment]
LGTM

**Comment by davidopp** [comment]
Still LGTM after new commits.

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/352

**Comment by davidopp** [comment]
Still LGTM after new commits

**Pull request merged**
