### PR TITLE
adjust package name for pkg/cloudprovider directory

### LINKED ISSUE #12741: controller package names don't match the folders
During the controller refactoring, the package names weren't made to match the folder names.  This is annoying an unexpected.

See https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/namespace/namespace_controller.go as an example.

### PR DESCRIPTION
**Pull request by zhengguoyong**
Fix #12741

### CODE REVIEW

**Comment by zhengguoyong** [comment]
@deads2k

**Comment by deads2k** [comment]
I like the change for package and directory consistency, but this isn't an area of code I normally touch so I'll defer to others.

**Comment by zhengguoyong** [comment]
ok,also thanks you so much. @deads2k  

would you please help me review this PR?
 thanks. @thockin

**Comment by thockin** [comment]
Thanks!

**Pull request merged**
