### PR TITLE
Automated cherry pick of #37418

### PR DESCRIPTION
**Pull request by bprashanth**
Cherry pick of #37418 on release-1.5.

#37418: Cleanup old cloud resources after 48 hours

### CODE REVIEW

**Comment by bprashanth** [comment]
Improves test reliability by purging leaks, so worthy of cheerypick. No change to produce code.

**Comment by saad-ali** [comment]
@k8s-bot cvm gke e2e test this

**Comment by bprashanth** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
