### PR TITLE
Poll instead of watch for ready ReplicaSets in e2e test

### PR DESCRIPTION
**Pull request by janetkuo**
xref #47697

### CODE REVIEW

**Comment by gmarek** [comment]
Why this change? If watch is unreliable we do have much bigger problems than flaky tests...

**Comment by kargakis** [comment]
@gmarek it's watch.Until, and not watches in general, that is problematic. There is discussion elsewhere about it.

**Comment by janetkuo** [comment]
@gmarek see #31345, `watch.Until` has caused lots of test flakes

**Comment by gmarek** [comment]
Oh, OK. Thx

**Pull request merged**
