### PR TITLE
bump(fsouza/go-dockerclient): 299d728486342c894e7fafd68e3a4b89623bef1d

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
@deads2k @smarterclayton @derekwaynecarr PTAL

(This is needed as part of the S2I bump we do in OpenShift to make sure all go-dockerclient deps are in sync and works properly. The main reason we need this in S2I is that this adds `UploadToContainer` and `DownloadFromContainer` methods that allows to adding files into a running containers.

**Comment by deads2k** [comment]
@k8s-bot ok to test

**Comment by eparis** [comment]
add to whitelist
@deads2k I think that because the bot is dumb, you can't prefix the `ok to test` with his name (but you must with `test this`)

**Comment by eparis** [comment]
@ixdy if verify-godeps.sh not running in jenkins unit/integration?

**Comment by eparis** [comment]
hack/verify-godeps.sh says something is very wrong.  Can you try to debug it locally? Reach out to me if you can't figure out why it is failing?

**Comment by ixdy** [comment]
@eparis Jenkins runs `hack/verify-all.sh`, which for some reason is skipping `hack/verify-godeps.sh`.

**Comment by mfojtik** [comment]
@ixdy @eparis sorry for that, I fixed the commit, now the `verify-godeps.sh` should work fine.

**Comment by mfojtik** [comment]
@eparis @ixdy do you guys know if that failure is a flake or it is related to the bump? I don't think it is related and all exec/portforward e2e tests that could be affected seems to work fine.

**Comment by eparis** [comment]
@k8s-bot e2e test this

**Comment by mfojtik** [comment]
@k8s-bot e2e test this

**Comment by mfojtik** [comment]
@eparis @ixdy I think we are good to go now

**Pull request merged**
