### PR TITLE
Automated cherry pick of #98755 upstream release 1.20

### PR DESCRIPTION
**Pull request by aojea**
/kind bug
/kind failing-test

```release-note
kubelet: the HostPort implementation in dockershim was not taking into consideration the HostIP field, causing that the same HostPort can not be used with different IP addresses.
This bug causes the conformance test "HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol" to fail.
```

The fix is working per https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-ubuntu-master-default&width=5

### CODE REVIEW

**Comment by aojea** [comment]
/assign @johnbelamaric @dims @danehans 
Following up on https://github.com/kubernetes/kubernetes/pull/98755#pullrequestreview-583645418

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by aojea** [comment]
/retest

> Kubernetes e2e suite: [sig-apps] Deployment should run the lifecycle of a Deployment

**Pull request merged**
