### PR TITLE
Remove retries from most oidc tests.

### PR DESCRIPTION
**Pull request by spxtr**
This cuts these tests down from 11 seconds to 2 seconds on my computer. On Jenkins they're taking 15 seconds each, we'll see how far this cuts that.

### CODE REVIEW

**Comment by liggitt** [comment]
+1 to faster tests

-1 to changing global vars without restoring original values (not new to this PR but hadn't noticed it before)

LGTM otherwise

**Comment by spxtr** [comment]
This more than halved their time, but they still take 20s on Jenkins.

**Comment by liggitt** [comment]
probably long dns resolution on 'https://foo'. changing to a bogus IP/port might make it faster

**Comment by spxtr** [comment]
@k8s-bot node e2e test this

**Comment by spxtr** [comment]
@liggitt I reset to the default value after the last test. This package needs to be fixed to not read settings from a global variable, and the tests need to be much faster, but I don't have the time to do that.

In the meantime, this PR halves the runtime of the tests, which is pretty significant.

**Comment by liggitt** [comment]
I'd rather see something like https://github.com/spxtr/kubernetes/pull/3 remove the global var to allow testing with different retry/backoff params

**Comment by spxtr** [comment]
SGTM. Mind making the issue against the kubernetes repo?

**Comment by liggitt** [comment]
that builds on this PR... feel free to squash it in

**Comment by liggitt** [comment]
thanks, go ahead and squash to a single commit if you don't mind

**Comment by spxtr** [comment]
Hmm, should someone else review this code now?

**Comment by liggitt** [comment]
heh, maybe. @yifan-gu / @ericchiang, want to take a look?

**Comment by ericchiang** [comment]
lgtm

**Pull request merged**
