### PR TITLE
fix annotate.go single resource check

### PR DESCRIPTION
**Pull request by juanvallejo**
``` release-note
Fix issue with kubectl annotate when --resource-version is provided.
```

When using `kubectl annotate` with a `--resource-version` on a resource, such as `kubectl annotate pod <pod_name> --resource-version=1820 description='myannotation'`, the command fails with the error: `error: --resource-version may only be used with a single resource`.

Upon printing the output of `resources` that the annotate command receives from cli args, it prints: `Resources:[pod <pod_name>]`. In other words, it treats the name of the resource as a second resource. This PR addresses this issue by using the resource builder `Singular` flag to determine if only a single resource was passed.

### CODE REVIEW

**Comment by pwittrock** [comment]
@AdoHe would you be willing to review this?

**Comment by AdoHe** [comment]
Ok, I will review this today.

**Comment by AdoHe** [comment]
@juanvallejo I think the `Validate` function can be simplify, also is there any reason we still keep this function? seems we can use `validateAnnotations` directly.

**Comment by juanvallejo** [comment]
@AdoHe 
> I think the Validate function can be simplify

Hm, I'm not sure what you mean by this.

> also is there any reason we still keep this function? seems we can use validateAnnotations directly.

It is to keep the same [pattern (complete, validate, run)](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/annotate.go#L117-L125) used in [some other commands](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/attach.go#L67-L69)

**Comment by AdoHe** [comment]
@juanvallejo for simplify, I mean:
```
func (o AnnotateOptions) Validate(args []string) error {
	return validateAnnotations(o.removeAnnotations, o.newAnnotations)
}
```
Ok, we keep this and follow this pattern.

**Comment by juanvallejo** [comment]
@AdoHe Sounds good, I have gone ahead and simplified the `Validate` method. Thanks for your feedback.

**Comment by AdoHe** [comment]
@juanvallejo you ever update this? It seems nothing changed.

**Comment by juanvallejo** [comment]
@AdoHe Sorry about that, forgot to push latest changes

**Comment by AdoHe** [comment]
LGTM. Thanks @juanvallejo 
@pwittrock please apply the `ok-to-test` label, I have no right to do this.

**Comment by pwittrock** [comment]
@AdoHe Done.  Thanks.

**Comment by AdoHe** [comment]
ok to test. @pwittrock please help remove `do-not-merge` label.

**Comment by pwittrock** [comment]
ok to test

**Comment by pwittrock** [comment]
@AdoHe Alright, I think it is finally going to go through now :)

**Pull request merged**
