### PR TITLE
ListResources before bring down the cluster

### PR DESCRIPTION
**Pull request by MrHohn**
From #31827.

We already list GCP resources [before bring up the cluster](https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gci-gce/2718/artifacts/gcp-resources-before.txt), [after bring up the cluster](https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gci-gce/2718/artifacts/gcp-resources-cluster-up.txt) and[ after bring down the cluster](https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-e2e-gci-gce/2718/artifacts/gcp-resources-after.txt). This PR also lists GCP resources before bring down the cluster. It will be helpful for checking whether everything is still as expected. Specifically we could know whether the firewall rules got clobbered or not.

@bowei @bprashanth

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36619)

### CODE REVIEW

**Comment by spxtr** [comment]
Good idea. To test this in PR Jenkins before merging you need to add a dummy commit on the end of the PR that touches `hack/jenkins/.use_head_e2e` and also add `hack/jenkins/.use_head_e2e` to `KUBE_TEST_PORTABLE` in `hack/lib/golang.sh`.

**Comment by MrHohn** [comment]
Thanks for telling! Added the dummy and waiting for the result.

**Comment by MrHohn** [comment]
New tests are run. But because `FAIL_ON_GCP_RESOURCE_LEAK` is set to `false` by the pull-kubernetes-e2e-* jobs, still don't see the output of ListResources().

Any way to flip this flag for testing?

**Comment by spxtr** [comment]
oh bother I didn't think about that. you can just flip it in e2e.go itself, after the flag.parse. Don't forget to unset it :)

**Comment by MrHohn** [comment]
Seems like it works as expected. Got [gcp-resources-cluster-down.txt](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/36619/pull-kubernetes-e2e-gce-gci/4426/artifacts/gcp-resources-cluster-down.txt).

**Comment by spxtr** [comment]
Neat, this looks great. Please remove the dummy commit, then lgtm.

**Comment by MrHohn** [comment]
Thanks! Dummy commit removed.

**Comment by MrHohn** [comment]
@k8s-bot test this please

**Comment by MrHohn** [comment]
@k8s-bot cvm gce e2e test this please

**Comment by MrHohn** [comment]
@k8s-bot verify test this please

**Pull request merged**
