### PR TITLE
Remove redundant filter from e2e-gce-parallel test job.

### PR DESCRIPTION
**Pull request by ghost**
GCE_DEFAULT_SKIP_TESTS is already included in the definition of GCE_PARALLEL_SKIP_TESTS above, so it's redundant and confusing here.  It send @ihmccreery on a wild goose chase. Delete it.

### CODE REVIEW

**Comment by ihmccreery** [comment]
I'd suggest removing the nested skips, rather than removing the duplication.  Nested skips sound confusing to me.  (Note that `GCE_FLAKY_TESTS` isn't nested in `GCE_PARALLEL_FLAKY_TESTS`—though there is some overlap.)

**Comment by quinton-hoole** [comment]
@ihmccreery agreed, done.  PTAL.

**Comment by ihmccreery** [comment]
LGTM.

**Comment by brendandburns** [comment]
generated docs are out of date for some reason...

**Comment by ArtfulCoder** [comment]
@quinton-hoole is there anything for you to do here ?
Brendan talks about docs being out of date
also, do you want to squash the commits ?

**Comment by quinton-hoole** [comment]
@ArtfulCoder  Yeah, there's a merge conflict. I'll fix it now.

**Pull request merged**
