### PR TITLE
Remove dashboard cluster addon

### PR DESCRIPTION
**Pull request by shu-mutou**
#### What type of PR is this?

/kind deprecation

#### What this PR does / why we need it:

Remove dashboard cluster addon.
Due to dashboard addon is no longer maintained.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Cluster addon for dashboard was removed. To install dashboard, see [here](https://github.com/kubernetes/dashboard/blob/master/docs/user/README.md).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
The entire cluster folder is deprecated. If the dashboard add on isn't used by CI, which I don't think it is, we should simply drop it

**Comment by shu-mutou** [comment]
Because some other addons are maintaining and I didn't find deprecation policy for addons, I thought this addon should be set as deprecated once.
I agree with removing. I will change this PR to remove entirely this addon.

**Comment by liggitt** [comment]
drop related stuff in the cluster scripts:

`CUSTOM_KUBE_DASHBOARD_BANNER` and `ENABLE_CLUSTER_UI`

`function update-dashboard-deployment`

```
  if [[ "${ENABLE_CLUSTER_UI:-}" == "true" ]]; then
    setup-addon-manifests "addons" "dashboard"
    local -r dashboard_deployment_yaml="${dst_dir}/dashboard/dashboard-deployment.yaml"
    update-dashboard-deployment ${dashboard_deployment_yaml}
  fi
```

**Comment by oomichi** [comment]
https://github.com/kubernetes/kubernetes/blob/cf18d80d035780739575b8cc889e8f26bf36779f/hack/local-up-cluster.sh#L928 also still uses the yaml which is deleted with this pull request.

**Comment by atoato88** [comment]
[`k/k/test/e2e/ui/dashboard.go`](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/ui/dashboard.go) has some tests for dashboard UI.
Should we delete this test?

**Comment by liggitt** [comment]
> [`k/k/test/e2e/ui/dashboard.go`](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/ui/dashboard.go) has some tests for dashboard UI.
> Should we delete this test?

yes

**Comment by oomichi** [comment]
pull-kubernetes-local-e2e seems failed due to unrelated reason according to https://github.com/kubernetes/kubernetes/pull/107626#issuecomment-1016018532

**Comment by shu-mutou** [comment]
@dims @liggitt @oomichi @atoato88 @floreks @maciaszczykm Passed required tests. Pleas take a look again. Thanks!

**Pull request merged**
