### PR TITLE
Remove duplicate code in client-go/tools/cache/controller.go

### PR DESCRIPTION
**Pull request by Adirio**
**What type of PR is this?**
/kind cleanup
/sig api-machinery

**What this PR does / why we need it**:
Remove duplicate code by extracting it to a non-exported function.

**Special notes for your reviewer**:
Syntactic sugar

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by Adirio** [comment]
Following @k8s-ci-robot suggestion:

/assign @ncdc

**Comment by Adirio** [comment]
@roycaihw this PR seems to need a priority, I did not found any documentation on the piority assign process. Should I just assign one with `/priority XXXX`?

**Comment by roycaihw** [comment]
@Adirio Yes you can pick one from https://github.com/kubernetes/kubernetes/labels?utf8=%E2%9C%93&q=priority

**Comment by roycaihw** [comment]
Actually it'd be better if you can add documentation to `newInformer`, like the ones for `NewInformer` and `NewIndexerInformer`.

**Comment by Adirio** [comment]
/priority important-longterm
Guess this is the one that fits better.

Will add documentation tomorrow

**Comment by Adirio** [comment]
@roycaihw Done, would you please add LGTM label again?

**Comment by Adirio** [comment]
Seems the only thing this PR is missing is an aproved label. If you need anything more just get in touch.

**Comment by roycaihw** [comment]
/assign @caesarxuchao 
for approval

**Comment by Adirio** [comment]
This PR is only requiring an aproval label. Can anyone set it or give some feedback on the reasons it is not being aproved so that it can be merged/closed/fixed?

**Pull request merged**
