### PR TITLE
Run test for grabbing metrics from Kubelet only on GCE

### PR DESCRIPTION
**Pull request by gmarek**
Ref. #19468

cc @roberthbailey

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

**Comment by gmarek** [comment]
Merging to unblock the build.

**Comment by roberthbailey** [comment]
/cc @brendandburns

Is this a flake or a persistent failure? I don't think that flat-out disabling this test on GKE is a good idea, because it doesn't allow us to collect any data about how often (or why) this fails. 

@cjcullen -- since this is part of the proxying code can you take a look.

**Comment by gmarek** [comment]
It's like 20% flaky, but the point is that we don't need to run this test on GKE, as it's main goal is to check the list of metrics we're exposing. There's no difference in that between GCE and GKE.

If there's a problemy with proxy, some other test should check that.

**Comment by roberthbailey** [comment]
If the test is flaky on GKE but not GCE then there clearly is a difference between the two deployments (that we should root cause and fix).

**Comment by gmarek** [comment]
Yeah, but that's not the main reason behind this test. We can use it for the time-being, but I guess it'd be better to have a dedicated regression test.

**Pull request merged**
