### PR TITLE
Add subresource apply support to client-go

### PR DESCRIPTION
**Pull request by jpbetz**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This depends on server-side support for apply subresources, which is also WIP.

#### Special notes for your reviewer:

Based on https://github.com/kubernetes/kubernetes/pull/99214 since it has not yet merged.

**Does this PR introduce a user-facing change?**:

Release note will be added when all the last change in the umbrella issue is merged

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

- [KEP]: [KEP 2155](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/2155-clientgo-apply)

```docs
TODO
```

/sig api-machinery
/wg api-expression

### CODE REVIEW

**Comment by jpbetz** [comment]
rebased

**Comment by apelisse** [comment]
Looks reasonable to me, though I don't know a lot about this code.

**Pull request merged**
