### PR TITLE
addons: add ports to the grafana controller

### PR DESCRIPTION
**Pull request by simon3z**

### CODE REVIEW

**Comment by simon3z** [comment]
@sub-mod can you review this? Thanks!

**Comment by sub-mod** [comment]
@simon3z hostport is not needed

**Comment by vishh** [comment]
+1 to @sub-mod's comment on removing hostport. Otherwise LGTM.

**Comment by simon3z** [comment]
Closing in favor of https://github.com/GoogleCloudPlatform/kubernetes/pull/5651

**Pull request closed without merging**
