### PR TITLE
[k8s.io/apiserver/plugin/pkg/audit/webhook/webhook]: fixup go vet

### PR DESCRIPTION
**Pull request by ideapark**
Signed-off-by: Zhou Peng <p@ctriple.cn>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note none

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by deads2k** [comment]
What are the other govet failures in this package.  I'm glad to take changes, but I'd like to see all the go vet failures in one package fixed and then the exclusion removed so we don't slip further.

Ping me on slack once updated.  deads2k

**Comment by iobuf** [comment]
~/kubernetes/staging/src/k8s.io/apiserver/plugin/pkg/audit/webhook$ go vet 
# k8s.io/apiserver/plugin/pkg/audit/webhook
./webhook.go:125:4: k8s.io/utils/trace.Field composite literal uses unkeyed fields
./webhook.go:126:4: k8s.io/utils/trace.Field composite literal uses unkeyed fields

no more `go vet` warnings

**Pull request closed without merging**
