### PR TITLE
Automated cherry pick of #24987

### PR DESCRIPTION
**Pull request by andyzheng0831**
Cherry pick of #24987 on release-1.2.

### CODE REVIEW

**Comment by andyzheng0831** [comment]
@roberthbailey @dchen1107 @zmerlynn please review this cherry-pick

cc/ @wonderfly @fabioy FYI

**Comment by dchen1107** [comment]
LGTM

**Comment by roberthbailey** [comment]
@k8s-bot test this #IGNORE (travis stalled out doing the build)

**Comment by roberthbailey** [comment]
Thanks mergebot. I was actually just trying to re-run travis, which is known to be flaky (or broken?) on the release branch, and didn't realize I could do it without pestering you.

**Comment by eparis** [comment]
travis doesn't respond to @k8s-bot requests. have to actually go to the details link, sign in with your github info, and click the 'restart' button.  Or close/reopen.

**Comment by roberthbailey** [comment]
@eparis I figured that out right after the bot started testing.

**Comment by roberthbailey** [comment]
After talking with @spxtr I'm going to ignore the travis failures and manually merge.

**Pull request merged**
