### PR TITLE
typos

### PR DESCRIPTION
**Pull request by KyleAMathews**

### CODE REVIEW

**Comment by roberthbailey** [comment]
Thanks for the contribution. Our lawyers say that we can't take even simple changes like this without a signed CLA on file. CONTRIB.md explains the process.

**Comment by KyleAMathews** [comment]
I signed one before last year on May 29th

**Comment by roberthbailey** [comment]
I didn't find you in our database. Was it with a different github account? Is there a specific email address I could search for?

**Comment by KyleAMathews** [comment]
mathews.kyle@gmail.com

**Comment by roberthbailey** [comment]
Found it; thanks!

**Pull request merged**
