### PR TITLE
Specify CustomResourceWebhookConversion is beta

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature

/kind documentation

**What this PR does / why we need it**:
Specify CustomResourceWebhookConversion is beta.
Ref kubernetes/kubernetes#78426

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
/ok-to-test
/priority important-longterm
please provide the links to k/enhancements.

**Comment by roycaihw** [comment]
The enhancement issue is https://github.com/kubernetes/enhancements/issues/598

**Review by yue9944882 — APPROVED** [review]

**Comment by ialidzhikov** [comment]
I think `/approve` is needed.

**Comment by roycaihw** [comment]
The feature went to GA in 1.16 and the kube_features file is up-to-date

/close

**Pull request closed without merging**
