### PR TITLE
dependencies: update golang.org/x/tools to v0.9.1

### PR DESCRIPTION
**Pull request by taoyounger**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
This PR is supposed to update golang.org/x/tools to v0.9.1

Fixes # none

### CODE REVIEW

**Comment by BenTheElder** [comment]
> What this PR does / why we need it:
> This PR is supposed to update golang.org/x/tools to v0.9.1

ok but why do we need to update this? Are we gaining an important bug fix? What's the motivation?

we only have so much bandwidth to review dependency updates, we purposely don't just update everything constantly, it risks breakage and costs time to review

**Comment by ty-dc** [comment]
> > What this PR does / why we need it:
> > This PR is supposed to update golang.org/x/tools to v0.9.1
> 
> ok but why do we need to update this? Are we gaining an important bug fix? What's the motivation?
> 
> we only have so much bandwidth to review dependency updates, we purposely don't just update everything constantly, it risks breakage and costs time to review

ok, thanks for your reply.

**Pull request closed without merging**
