### PR TITLE
fix a potential deadlock in graceful node shutdown unit tests

### PR DESCRIPTION
**Pull request by charlesxsh**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR tries to fix a potential deadlock issue. If line 251's timeout happened before line 248, line 216's send operation will be blocked forever.

#### Special notes for your reviewer:
Similar issue/fix: https://github.com/kubernetes/kubernetes/pull/83925

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bobbypage** [comment]
Thanks for the PR. Your explanation makes sense, but as far as I understand, I'm not sure the how important the deadlock is since if line 251 timeout happens first, the unit test will fail with `t.Fatal()` which should abort the unit test anyways, making it irrelevant the channel send is blocked. Is that correct or am I misunderstanding?

**Comment by bobbypage** [comment]
/retitle fix a potential deadlock in graceful node shutdown unit tests

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
