### PR TITLE
Use log functions of core framework on sub [p-s]

### PR DESCRIPTION
**Pull request by oomichi**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This makes sub packages of e2e test framework to use log functions
of core framework instead for avoiding circular dependencies.

Ref: https://github.com/kubernetes/kubernetes/issues/81427

**Special notes for your reviewer**:

test/e2e/framework/ssh will make circular dependencies if
updating it. It is necessary to solve the issue in advance
before this work.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by SataQiu — APPROVED** [review]
/lgtm

**Comment by k-toyoda-pi** [comment]
`e2e/framework/statefulset` contains `e2efwk` definication. It is different from other files. Is it be modified in other PR?

**Comment by oomichi** [comment]
@k-toyoda-pi 

> e2e/framework/statefulset contains e2efwk definication. It is different from other files. Is it be modified in other PR?

That is a nice point.
Such kind thing is checked with the list `hack/.import-aliases` and now the list doesn't contain `e2efwk`.
So we have two options:
- Replace `e2efwk` with `framework` like the other test files.
- Add `e2efwk` to the list and update all other test files.

Anyways that should be done with different PR as you said.

**Comment by k-toyoda-pi** [comment]
@oomichi Thanks for explanation.
/lgtm

**Pull request merged**
