### PR TITLE
Typo Fix

### PR DESCRIPTION
**Pull request by gambol99**
- nothing much here just a typo fix found when copying and pasting into a kops [#PR5349](https://github.com/kubernetes/kops/pull/5349)

### CODE REVIEW

**Comment by nikhita** [comment]
/assign @thockin 
for approval

**Review by KashifSaadat — APPROVED** [review]

**Comment by php-coder** [comment]
/kind cleanup

Looks like it wasn't approved because bot expects `/approve no-issue` command.

**Comment by nikhita** [comment]
The comment says approved but looks like the label didn’t get added. Maybe lack of tokens?

@thockin can you approve again?

**Comment by nikhita** [comment]
> Looks like it wasn't approved because bot expects /approve no-issue command.

We got rid of the approve no-issue command thankfully :D

**Comment by nikhita** [comment]
ping @thockin for approval (again :confused:)

**Comment by gambol99** [comment]
hiya .. i'm gonna close this PR ... I don't mean it discourteously but the carbon foot print alone to get this merged is becoming somewhat farcical

**Comment by nikhita** [comment]
> hiya .. i'm gonna close this PR ... I don't mean it discourteously but the carbon foot print alone to get this merged is becoming somewhat farcical

@gambol99 sorry about that!

Now that the PR is approved + lgtm'ed again it should get merged automatically. The last comment that you see is from the merge bot. I think the tests will run once again by the submit queue too but it should be fairly quick now.

If it doesn't merges soon, I'll try to carry this change in another commit and close this PR myself. :+1: 

/reopen

**Pull request merged**
