### PR TITLE
Rkt image size

### LINKED ISSUE #19494: rkt: retrieve image size from rkt api service
As https://github.com/coreos/rkt/pull/1916 is merged, we should be able to return the image size information to kubelet.

cc @derekparker @sjpotter @jonboulle

### PR DESCRIPTION
**Pull request by derekparker**
Fixes #19494

### CODE REVIEW

**Comment by derekparker** [comment]
cc: @yifan-gu @jonboulle

**Comment by yifan-gu** [comment]
LGTM! Thanks @derekparker !

**Comment by yifan-gu** [comment]
@derekparker Need a rebase

**Comment by derekparker** [comment]
@yifan-gu rebased.

**Comment by jonboulle** [comment]
LGTM

**Comment by yifan-gu** [comment]
hack/verify-godeps.sh is not happy:
>https://travis-ci.org/kubernetes/kubernetes/builds/101925196

**Comment by derekparker** [comment]
@yifan-gu not sure what the issue is there, ran locally just fine, seems like possibly a network error since it could not clone a repo? Also Jenkins build failed, also not sure why... everything passes locally. Is it a flicker, can we restart those checks or am I missing something and there is a legit failure?

**Comment by yifan-gu** [comment]
@k8s-bot test this please

**Comment by yifan-gu** [comment]
@k8s-bot unit test this please

**Comment by yifan-gu** [comment]
@derekparker OK, maybe close reopen to trigger the ci again?

**Comment by yifan-gu** [comment]
@k8s-bot test this please

**Comment by yifan-gu** [comment]
@k8s-bot ok to test

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

Tests have been pending for 24 hours

**Pull request merged**
