### PR TITLE
switch to use ContainerID instead of DockerID in network plugin interface

### LINKED ISSUE #15663: Change the network plugin's interface
Currently the network plugin's [interface](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/plugins.go#L49) takes a docker container ID as the parameter. AFAICS, the container ID is used to get the PID of the infra container. So will it be feasible to change it to the PID that holds the network namespace? This would make the interface more generic for other runtimes such as rkt :)

Related https://github.com/kubernetes/kubernetes/issues/15638#issuecomment-148194718

/cc @dchen1107 @jonboulle @thockin

### PR DESCRIPTION
**Pull request by freehan**
fix: #15663

### CODE REVIEW

**Comment by freehan** [comment]
@k8s-bot test this: #IGNORE

**Comment by dchen1107** [comment]
LGTM

**Comment by freehan** [comment]
Looks like a GCE problem

```console
[k8s.io] Services
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:420
  should be able to change the type and ports of a service [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:716

  Apr  6 16:37:53.747: failed to release static IP e2e-external-lb-test-fd4211cf-fc4f-11e5-b0cc-42010af0000e: failed to delete static IP "e2e-external-lb-test-fd4211cf-fc4f-11e5-b0cc-42010af0000e": ERROR: (gcloud.compute.addresses.delete) Some requests did not succeed:
   - Backend Error
  

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:537
```

**Comment by freehan** [comment]
@k8s-bot e2e test this github: #IGNORE

**Comment by dchen1107** [comment]
LGTM again.

**Pull request merged**
