### PR TITLE
Automated cherry pick of #103176: Update golang.org/x/net to v0.0.0-20210520170846-37e1c6afe023

### PR DESCRIPTION
**Pull request by jonesbr17**
Cherry pick of #103176 on release-1.19.

#103176: Update golang.org/x/net to v0.0.0-20210520170846-37e1c6afe023

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by RSAlderman** [comment]
Related to cherry picks to get change in releases [1.20](https://github.com/kubernetes/kubernetes/pull/103695) and 
[1.21](https://github.com/kubernetes/kubernetes/pull/103694)

**Comment by RSAlderman** [comment]
@bowei / @andrewsykim can you review and correct the labels appropriately so this backport can be merged?

**Comment by aojea** [comment]
1.19 no longer receive patches https://kubernetes.io/releases/patch-releases/

**Pull request closed without merging**
