### PR TITLE
fix todo: move GetPauseImageNameForHostArch to the test/utils/image

### PR DESCRIPTION
**Pull request by hanxiaoshuai**
**What this PR does / why we need it**:
fix todo: move GetPauseImageNameForHostArch to the test/utils/image
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hanxiaoshuai** [comment]
cc @hzxuzhonghu

**Comment by jianglingxia** [comment]
oh，i have commited three days ago，#59094

**Pull request closed without merging**
