### PR TITLE
genericapiserver: cut off more dependencies – episode 2

### PR DESCRIPTION
**Pull request by sttts**
Compare commit subjects.

approved based on #40363

### CODE REVIEW

**Comment by deads2k** [comment]
```
pkg/util: move Trie to k8s.io/apiserver - ok, but followup issue to move to its own package
pkg/util: move CompileRegex helper into apiserver  - ok
genericapiserver: cutting off pkg/api deps - ok because its a test
genericapiserver: cut off pkg/api from responsewriters - ok
pkg/util: move uuid and strategicpatch into k8s.io/apimachinery - ok
pkg/util: move httpstream to k8s.io/apimachinery - ok
Move netutil.CanonicalAddr to k8s.io/apiserver - ok
pkg/util: move proxy into k8s.io/apiserver - ok
```

**Comment by sttts** [comment]
@deads2k removed the httpstream move (needs some more transitive deps resolved first) and added a move commit for third_party/forked/golang/json. ptal

**Comment by deads2k** [comment]
> @deads2k removed the httpstream move (needs some more transitive deps resolved first) and added a move commit for third_party/forked/golang/json. ptal

lgtm

**Comment by sttts** [comment]
@k8s-bot bazel test this

**Comment by sttts** [comment]
Bazel flake ^^: https://github.com/kubernetes/kubernetes/issues/40295

**Comment by deads2k** [comment]
@k8s-bot kops aws e2e test this

**Comment by ymqytw** [comment]
@sttts @deads2k Is there a PR to add pkg `strategicpatch` back to repo `apimachinery`?
I found pkg `strategicpatch` is missing.

**Comment by ymqytw** [comment]
I'm curious how the tests passed when we don't have that pkg.

**Comment by sttts** [comment]
@ymqytw it's in there:
```shell
$ git show d7eb3b687021ec9c3f462e356dbea72a18482680
...
diff --git a/pkg/util/strategicpatch/patch.go b/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go
similarity index 100%
rename from pkg/util/strategicpatch/patch.go
rename to staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go
```

Looks like github doesn't show the full patch?

**Comment by ymqytw** [comment]
I'm confused what is the `staging` directory used for? Will it be automatically committed to `k8s.io/apimachinery `by some script?

Some `kubectl` code import `"k8s.io/apimachinery/pkg/util/strategicpatch"`. But the `strategicpatch` pkg is in `staging` directory under repo `k8s.io/kubernetes/` instead of in `k8s.io/apimachinery/`. How does this work?

**Comment by sttts** [comment]
@ymqytw staging is our short/mid-term solution to keep the one big kubernetes repo, before we have tooling around testing, releases etc. for multiple repos. The staging packages are symlinked in the vendor directory. Hence, you are able to import them in go as they were in seperate repos.

For thirdparty development outside of k8s.io/kubernetes we regularly export the staging version into their own github repos. So go-get, godeps and friends will work. But this is all not necessary for things done in k8s.io/kubernetes. So in kubectl just import `"k8s.io/apimachinery/...."` and the symbol link in the vendor dir will make go find the packages.

If you have to change code in apimachinery, do it in staging. This is the "authorative" version (only client-go has some magic copying package into staging, apimachiney and apiserver don't).

**Comment by ymqytw** [comment]
@sttts Thank you so much for your explantation. This is VERY helpful!

> If you have to change code in apimachinery, do it in staging.

Now I know where my changes should go.

**Pull request merged**
