### PR TITLE
Automated cherry pick of #76656: Switch to instance-level update APIs for Azure VMSS loadbalancer operations

### PR DESCRIPTION
**Pull request by feiskyer**
Cherry pick of #76656 on release-1.11.

#76656: Switch to instance-level update APIs for Azure VMSS loadbalancer operations

Previously, VMSS API doesn't support configurations for each instance. Hence, Azure cloud provider upgrades manually for all instances whenever loadbalancer backend pools need to be updated. This would cause all instances restarted if there're also some other VMSS model changes.

To fix this issue, the PR switches to instance-level update APIs for Azure VMSS loadbalancer operations. It also upgrades Azure SDK to v14.7.0.

/kind bug
/priority critical-urgent
/sig azure

### CODE REVIEW

**Comment by justaugustus** [comment]
Commented on the flake issue opened here: https://github.com/kubernetes/kubernetes/issues/73105#issuecomment-486914764
/test pull-kubernetes-kubemark-e2e-gce-big

**Comment by feiskyer** [comment]
@cblecker @foxish Could you help to approve the changes?

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
