### PR TITLE
etcd: Build image 3.5.7-0

### PR DESCRIPTION
**Pull request by mzaian**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Build Image for [v3.5.7](https://github.com/etcd-io/etcd/releases/tag/v3.5.7).

**Which issue(s) this PR fixes**:
Fixes NONE #

**Does this PR introduce a user-facing change?**:
```
NONE
```

### CODE REVIEW

**Comment by cici37** [comment]
/test pull-kubernetes-unit
/assign @jpbetz 
for etcd approval
/triage accepted

**Comment by hakman** [comment]
@dims There's been some interesting changes in how etcd builds the official images.
The dependency on `busybox` has been removed in https://github.com/etcd-io/etcd/pull/15036, which may allow just using the official images and adding another layer with the `cp` utility (is it still needed?).

/lgtm
/assign @dims 
/release-note-none

**Comment by dims** [comment]
/lgtm
/approve

Are you talking about https://github.com/etcd-io/etcd/pull/15036/files#diff-2f60a4131f094ce9749a4e155ad2960ec62bbe04f0a1f33b0cbf3f7bf2d971c6R35 @hakman ?

**Comment by hakman** [comment]
> Are you talking about https://github.com/etcd-io/etcd/pull/15036/files#diff-2f60a4131f094ce9749a4e155ad2960ec62bbe04f0a1f33b0cbf3f7bf2d971c6R35 @hakman ?

@dims Yes, that's the commit. The image seems pretty similar to the ones built from `cluster/images/etcd/Dockerfile`, except for a few extra files:
https://github.com/kubernetes/kubernetes/blob/81df4d7dc41dd2e22efd2f20eebcced76b8a7930/cluster/images/etcd/Dockerfile#L37-L38

**Comment by dims** [comment]
@hakman in our etcd image, we have a migration script that has helped us move between etcd versions just by updating to a new etcd container. We can open a fresh issue and vote on if we really need that anymore

- https://github.com/kubernetes/kubernetes/blob/master/cluster/images/etcd/migrate/migrate.go#L32-L44
- https://github.com/kubernetes/kubernetes/blob/master/cluster/images/etcd/README.md?plain=1#L21-L38

@wojtek-t could we get rid of the migrate stuff?

**Pull request merged**
