### PR TITLE
tests: Switch dockerhub registry images to promoted registry

### LINKED ISSUE #97027: Migrate kubernetes e2e tests away from use of docker.io images
Part of umbrella to migrate kubernetes e2e test images/registries to community-owned infrastructure: https://github.com/kubernetes/k8s.io/issues/1458

The following docker.io images are used by 1.20 e2e tests
```
docker.io/gluster/glusterdynamic-provisioner:v1.0
docker.io/library/busybox:1.29
docker.io/library/httpd:2.4.38-alpine
docker.io/library/httpd:2.4.39-alpine
docker.io/library/nginx:1.14-alpine
docker.io/library/nginx:1.15-alpine
docker.io/library/perl:5.26
docker.io/library/redis:5.0.5-alpine
```

We should migrate them to community owned infrastructure (ref: https://github.com/kubernetes/sig-release/issues/1369 for deciding how to implement a mirror registry)

We should consider doing this for release branches as well, which may use different images/tags.  So these wouldn't necessarily be cherry-picks

Two possible approaches:
- change the registry in source (I would prefer eliminating the extra "docker library" registry, and consolidate to a single e2e test image registry)
- start running tests with a config that swaps out docker.io for some other registry

/sig testing
/sig release
/area release-eng
/wg k8s-infra
/milestone v1.21

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind cleanup
/sig testing
/sig windows

/priority important-soon

#### What this PR does / why we need it:

Due to the dockerhub rate limiting, we had to find an alternative solution. We've mirrored the dockerhub images into our own.

Additionally, our own busybox, httpd, and nginx images also have Windows support.

#### Which issue(s) this PR fixes:

Fixes #97027

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by claudiubelu** [comment]
/cc @spiffxp 
/cc @dims 
/cc @chewong 

This should close the issue #97027. From a quick look, there doesn't seem to be any relevant dockerhub image left.

**Review by spiffxp — APPROVED** [review]
/retest
/approve
/lgtm

**Pull request merged**
