### PR TITLE
fix comment error

### PR DESCRIPTION
**Pull request by jonyhy96**
fix comment error
```release-note
None
```

### CODE REVIEW

**Comment by php-coder** [comment]
@jonyhy96 Please, consider combining all your PRs into one. A lot of time and resources are spending for checking every PR and wasting them for several PRs with typos non-rational.

**Comment by php-coder** [comment]
@jonyhy96 We appreciate your input and welcoming you here! Thank you for your effort and patience!

**Comment by jonyhy96** [comment]
This PR has been ignored for so long
close it

**Comment by sttts** [comment]
@jonyhy96 please reopen so it can be merged.

**Pull request closed without merging**
