### PR TITLE
Version API descriptions

### PR DESCRIPTION
**Pull request by thockin**
This relies on releases.k8s.io/vx.y.z to version the description strings in the API.  This operates in the current branch, which I guess the releaser would have already `git branch`ed to `release-x.y`

Please review commit-by-commit for sanity - it's actually a very small change :)

@zml @alex-mohr @nikhiljindal @bgrant0607

### CODE REVIEW

**Comment by zmerlynn** [comment]
Thanks for the separate commits. LGTM.

**Comment by bprashanth** [comment]
Waiting on Brian's ok-to-merge

**Comment by thockin** [comment]
@bgrant0607 triage for 1.0 ?

**Comment by bgrant0607** [comment]
I'm ok with this going into 1.0 so long as we can get a 2nd LGTM from someone else.

**Comment by alex-mohr** [comment]
Zach, seems reasonable to merge if this is compatible with new release process?

**Comment by zmerlynn** [comment]
Yeah, I LGTM'd this a bit ago. :) It seems fine.

**Comment by yujuhong** [comment]
@thockin, I don't see any shippable results, and e2e doesn't test this PR much. Would you mind pushing again to trigger a shippable build?

**Pull request merged**
