### PR TITLE
Add support for vpshere cloud provider in kubeup

### PR DESCRIPTION
**Pull request by kerneltime**
**What this PR does / why we need it**:
vSphere cloud provider added in 1.3 was not configured when deploying via kubeup

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #

**Special notes for your reviewer**:

**Release note**:

``` release-note
Add support for vSphere Cloud Provider when deploying via kubeup on vSphere.
```

When deploying on vSphere using kube up add configuration
for vSphere cloud provider.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31467)

### CODE REVIEW

**Comment by kerneltime** [comment]
cc @imkin

**Comment by kerneltime** [comment]
@eparis vSphere cloud provider was added in 1.3 but the kube scripts were not updated to support it. This is fixing the gap in kube up script to support vSphere cloud provider. The corresponding documentation https://github.com/kubernetes/kubernetes.github.io/pull/1102 has been updated and we would like to make sure customers in 1.4 can use kube up to use the cloud provider.

**Comment by eparis** [comment]
@luxas you probably know better than me our current recommendations...

**Comment by luxas** [comment]
ok to test

**Comment by luxas** [comment]
cc @abrarshivani @dkalleg @dagnello for a context from the vSphere side

cc @mikedanese @roberthbailey @zmerlynn that knows more about the kube-up process

and cc @pwittrock for deciding about if this should make v1.4

For me, it does look like a resonable change to do in order to be able to demo vSphere out-of-the-box turnup to new users. 

@kerneltime but be aware that new features aren't allowed. You should start looking at other ways to bootstrap a cluster on vSphere too, in order to be future-proof.

**Comment by mikedanese** [comment]
This missed feature freeze. This should not go in v1.4.

**Comment by kerneltime** [comment]
@mikedanese This is not a new feature per se but fix for a missing update to the official installer in 1.3 when the cloud provider was introduced. We are considering back porting this to 1.3 as well since customers have no documented way to use the cloud provider within kubernetes in 1.3 or 1.4 and have to depend on external scripts of custom hacks. The changes are limited to the installer itself and no new feature is introduced into the cloud provider. 1.5 is Dec with a new installer in the works. The goal for this PR is to not leave customers stranded..

**Comment by kerneltime** [comment]
@luxas we plan to look into kube anywhere for 1.5 timeline

**Comment by mikedanese** [comment]
@k8s-bot ok to test.

**Comment by mikedanese** [comment]
@kerneltime need to fix verification tests.

**Comment by kerneltime** [comment]
@mikedanese Updated by adding the use of underscore to the exceptions list. This is a private variable used in shell. Let me know if this is ok.

**Comment by mikedanese** [comment]
Thats ok but you need to sign the new CLA :)

**Comment by kerneltime** [comment]
I am not sure why the cla/linuxfoundation is showing an issue, when I login it says I am good to commit.
Took a look at the Jenkins failure and does not seem related to change.
```
Creating cluster e2e-gke-agent-pr-15-0...done.
ERROR: (gcloud.container.clusters.create) Operation [<Operation
 name: u'operation-1475712846452-7ba8998e'
 operationType: OperationTypeValueValuesEnum(CREATE_CLUSTER, 1)
 selfLink: u'https://test-container.sandbox.googleapis.com/v1/projects/943316867058/zones/us-central1-f/operations/operation-1475712846452-7ba8998e'
 status: StatusValueValuesEnum(DONE, 3)
 statusMessage: u'All cluster resources were brought up, but the cluster API is reporting that only 0 nodes out of 2 have registered. Cluster may be unhealthy.'
 targetLink: u'https://test-container.sandbox.googleapis.com/v1/projects/943316867058/zones/us-central1-f/clusters/e2e-gke-agent-pr-15-0'
 zone: u'us-central1-f'>] finished with error: All cluster resources were brought up, but the cluster API is reporting that only 0 nodes out of 2 have registered. Cluster may be unhealthy.
2016/10/05 17:32:15 e2e.go:671: Step 'up' finished in 18m13.97325405s
2016/10/05 17:32:15 e2e.go:146: Saved XML output to /workspace/_artifacts/junit_runner.xml.
2016/10/05 17:32:15 e2e.go:163: Something went wrong: starting e2e cluster: error running up: exit status 1
exit status 1
+ chmod -R o+r /workspace/_artifacts
+ rc=1
+ trap '' EXIT
+ exit 1
+ rc=1
+ [[ 1 -ne 0 ]]
+ [[ -x cluster/log-dump.sh ]]
+ [[ -d _artifacts ]]
+ echo 'Dumping logs for any remaining nodes'
Dumping logs for any remaining nodes
+ ./cluster/log-dump.sh _artifacts
Dumping master and node logs to _artifacts
Master SSH not supported for gke
ssh: connect to host 104.198.136.252 port 22: Connection timed out
ERROR: (gcloud.compute.copy-files) [/usr/bin/scp] exited with return code [1]. See https://cloud.google.com/compute/docs/troubleshooting#ssherrors for troubleshooting hints.
ssh: connect to host 104.197.184.105 port 22: Connection timed out
```

**Comment by kerneltime** [comment]
@zmerlynn I need to have this PR cherry picked to 1.4 without this code we are unable to deploy vsphere cloud provider on top of vSphere for customers and developers starting from k8s docs.

**Pull request merged**
