### PR TITLE
Fix Typos in pkg/kubelet/dockershim/docker_service.go

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/test pull-kubernetes-kubemark-e2e-gce-big

Thanks for this PR!

As we move forward with this, could you please update the PR title to be more descriptive? Additionally, could you please write a commit message outlining what you are actually changing? In this case, maybe `Fix Typos in pkg/kubelet/dockershim/docker_service.go` would be appropriate.

Thanks :)

**Comment by mattjmcnaughton** [comment]
Please add "/assign tallclair" once the PR title and metadata have been updated.

**Comment by qingsenLi** [comment]
@mattjmcnaughton thanks for review
/assign @tallclair

**Pull request merged**
