### PR TITLE
Automated cherry pick of #110094: apiserver: refactor - move AuditBackend.Run out of NonBlockingRun

### PR DESCRIPTION
**Pull request by vpnachev**
Cherry pick of #110094 on release-1.24.

#110094: apiserver: refactor - move AuditBackend.Run out of NonBlockingRun

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fix a deadlock in the kube-apiserver that prevents graceful shutdown.
```

### CODE REVIEW

**Comment by vpnachev** [comment]
I would appreciate if this cherry-pick as approved. 
We are currently facing issues to shut-down gracefully kube-apiserver and this cherry-pick fixes this issue for us.

**Comment by tkashem** [comment]
from https://github.com/kubernetes/kubernetes/pull/110094#discussion_r875005364

> So this PR is not changing any behavior, I believe. I updated the comment.
I apologize, the details are a little hazy now, my recollection is that this PR is a pure refactor and does not change any behavior. can you please clarify how this PR alone solves the deadlock issue, maybe with some termination logs?

including this, we made a series of PRs to improve graceful shutdown, my understanding is that you would need the bunch to see improvements.

**Comment by vpnachev** [comment]
> can you please clarify how this PR alone solves the deadlock issue, maybe with some termination logs?
> 
> including this, we made a series of PRs to improve graceful shutdown, my understanding is that you would need the bunch to see improvements.


We are running kube-apiserver with buffered audit logging and found that for 1.24, the graceful termination is in deadlock. Basically, these logs repeats forever and kube-apiserver does not shut down unless it is signaled with SIGTERM for second time or SIGKILL
```
2022-11-03 17:37:59 {"log":"[-]shutdown failed: process is shutting down"}
2022-11-03 17:37:59 {"log":"shutdown check failed: readyz","pid":"1","severity":"INFO","source":"healthz.go:257"}
2022-11-03 17:37:57 {"log":"[-]shutdown failed: process is shutting down"}
2022-11-03 17:37:57 {"log":"shutdown check failed: readyz","pid":"1","severity":"INFO","source":"healthz.go:257"}
2022-11-03 17:37:47 {"log":"[-]shutdown failed: process is shutting down"}
2022-11-03 17:37:47 {"log":"shutdown check failed: readyz","pid":"1","severity":"INFO","source":"healthz.go:257"}
2022-11-03 17:37:37 {"log":"[-]shutdown failed: process is shutting down"}
2022-11-03 17:37:37 {"log":"shutdown check failed: readyz","pid":"1","severity":"INFO","source":"healthz.go:257"}
2022-11-03 17:37:30 {"log":"[-]shutdown failed: process is shutting down"}
2022-11-03 17:37:30 {"log":"shutdown check failed: readyz","pid":"1","severity":"INFO","source":"healthz.go:257"}
2022-11-03 17:37:27 {"log":"[-]shutdown failed: process is shutting down"}
2022-11-03 17:37:27 {"log":"shutdown check failed: readyz","pid":"1","severity":"INFO","source":"healthz.go:257"}
2022-11-03 17:37:17 {"log":"[-]shutdown failed: process is shutting down"}
2022-11-03 17:37:17 {"log":"shutdown check failed: readyz","pid":"1","severity":"INFO","source":"healthz.go:257"}
2022-11-03 17:37:07 {"log":"[-]shutdown failed: process is shutting down"}
2022-11-03 17:37:07 {"log":"shutdown check failed: readyz","pid":"1","severity":"INFO","source":"healthz.go:257"}
``` 

Then I found https://github.com/kubernetes/kubernetes/issues/108483 and all PRs linked to it. I was thinking that either #110094 and/or #110026 can fix the issue. As I am able to reproduce the deadlock all the time, I just built a custom image with manually cherry-picked #110094 ontop of 1.24.7 and then I was no longer able to reproduce the deadlock. This is why I think #110094 resolves the issue that I observe. 


Maybe it will be nice all non-testing related code from #108483 to be cherry-picked to the still supported versions.

**Comment by vpnachev** [comment]
As the cherry-pick deadline is approaching, I would like to know if there is anything else that I can help so that this change to be part of v1.24.9 release?

**Comment by vpnachev** [comment]
A friendly ping @tkashem @aojea @wojtek-t as the cherry-pick deadline is in just few days.

**Comment by aojea** [comment]
> Maybe it will be nice all non-testing related code from #108483 to be cherry-picked to the still supported versions.

this is not possible, most of them don't meet the criteria https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#what-kind-of-prs-are-good-for-cherry-picks

I'm scared of backporting a change like this, we just had fixed a regression this past week related to the shutdown and , as you pointed out in your comments, this is part of a large series of changes and the risk to regress is not minimum

**Comment by vpnachev** [comment]
Ok, I understood the risk of cherry-picking all of the PRs related to #108483, I am also not sure how easy it could be as there are really a lot of code changes there that might be hard to be backported to older branches.

Then what about this PR solely? I really believe it should be accepted as it fixes a bug in the `kube-apiserver` graceful shutdown when buffered audit plugin is enabled no matter if the audit backend is `log` or `webhook`. 
I am not sure if I open a bug issue, a different fix will be implemented, but it will for sure impose a delay.

**Comment by vpnachev** [comment]
As today is the cherry-pick deadline, can I get a more clear feedback what I can do get this fix in?

**Comment by vlerenc** [comment]
@aojea I don't understand all this. The 1.24 API server is not properly shutting down with audit log enabled w/o this fix and nothing happens - everybody is scared? This is causing outages and issues and it's a bug and we have analysed it and we provided a hotfix, yet nobody cares about 1.24 anymore? Is Kubernetes dead already if such things are turned down? Have you even tried to reproduce the problem, because it's fairly easy and the outcome is a dead API server that hangs itself. How is that OK and nobody is even willing to accept a fix for it?

**Comment by dims** [comment]
@vlerenc please take a deep breath and re-read what you wrote.

**Comment by vlerenc** [comment]
Sure @dims. What shall I specifically "re-read"?

That the maintainers are scared? Well, that's what they wrote themselves:
> "I'm scared of backporting a change like this..."

Or that nobody cares about the 1.24 API servers that hang themselves? Well, that's de-facto the case. You have not helped shaking off that feeling either.

Or that I am wondering whether Kubernetes is dead? Well... if people are scared to fix glaring bugs that cause outages and everything got so large and out of hand, it reminds me of OpenStack and other such projects that were crushed under their own weight. I still hope, Kubernetes is not there (yet) as it cleans itself up now and then, but being scared to fix bugs is an alarming smell.

**Comment by dims** [comment]
@vlerenc - @aojea made it clear that "this is part of a large series of changes and the risk to regress is not minimum" and we have a set of criteria for cherry-picks and this PR which proposes a tiny bit of it does not qualify. there is not even a test case of some sort in this PR.

Clearly, you don't see how you are engaging is counter productive and your language/tone comes across as a tantrum. I hope you can do better to engage and earn trust with folks in this community.

**Comment by vlerenc** [comment]
Well, thank you for your feedback @dims. Trust works both ways and a broken API server that hangs itself and no other plan on the horizon doesn't instil trust either. That's also not the only issue that nobody feels empowered anymore to fix (kube-proxy probe for external traffic policy local or that the kubelet always breaks all workload when it restarts as it reports it not ready, etc.). Anyway, in the end it is your call whether you do something about it or not.

**Comment by vpnachev** [comment]
> there is not even a test case of some sort in this PR.

Is this not expected for automated cherry pick PRs when the original PRs also lack tests?

**Comment by vlerenc** [comment]
@dims @aojea OK, I see I was emotional and I am sorry. I guess, being confronted with severe outages on our side and seeing that we won't get an upstream fix (with this/our PR) made me "too pushy" (rarely if ever useful).

We will try to invent some local bandaid or maybe fork the API server then as we have no choice. Business-critical clusters always run with enabled audit logging and not everybody of our thousands of internal stakeholders can switch to 1.25 already because of the significant changes there and going back is no option either. With this in mind (no back to 1.23, no stay with 1.24, no forward to 1.25), I felt cornered and overreacted. I am sorry. We will find another way then.

**Comment by dims** [comment]
@vpnachev for `I decided to be kind and help the community by spending couple of my days to identify the PR that actually already fixed the issue in 1.25 and propose exactly the same change to be backported to still supported version` i very much thank you!! Yes, this is more appreciated than just opening a bug which is likely to get stale. We can all be mad about things, but when we are in the community, we should do better, which you did and i appreciate you for that.

**Comment by dims** [comment]
> @dims @aojea OK, I see I was emotional and I am sorry.

I was as well and i apologize as well in escalating. We are all trying to do the right thing here. I am hoping we will find a way together. Yes, like @vpnachev said, 1.24.9 will still have this problem. let's revisit the objections from @tkashem and @aojea and see how we can allay them.  

I'd also recommend dropping by the api-machinery next meeting if we don't have consensus on this by them. I also got a ping from @apelisse out of band, thanks @apelisse for watching this unfold and setting nudging me. Hoping you can chime in as well on how best to proceed.

**Comment by apelisse** [comment]
@alexzielenski and I took a quick look at it, we think if we added #110132, and especially if we see it fail before the fix, that would increase the confidence that: 1. the fix does what it says it does, 2. the termination isn't broken by the fix.

**Comment by dims** [comment]
@vpnachev @vlerenc Sounds like @apelisse has shown us a way forward. Let's try that.

**Comment by vpnachev** [comment]
Running locally built `kube-apiserver` with the changes from #110132 and #110096 does not fix the kube-apiserver hang during shut-down. These 2 PRs also do not bring a failing test which is to be fixed by #110094. 

Therefore, I think #110132 and #110096 are not related to the kube-apiserver hang bug fixed by #110094 and they should not be included in this cherry-pick PR.

@dims @apelisse any feedback or other ideas are welcomed!

**Comment by apelisse** [comment]
Would you be able to look into the code of #110132 to see why it doesn't fail with the fix? Is it not running the audit log component? If it doesn't, can you use the code from that PR to write your own test that does hang with the audit-log component enabled? Let me know if that's too much to ask 😅

**Comment by vpnachev** [comment]
I just tried to quickly implement a test and for inspiration I used https://github.com/kubernetes/kubernetes/blob/9710807c82740b9799453677c977758becf0acbb/staging/src/k8s.io/apiserver/pkg/server/genericapiserver_test.go#L582-L669, but I failed to provoke the bug and I think it is because I was looking in the wrong place (I am sorry, I am quite new to the k8s code base). Next week I will take a deeper look in https://github.com/kubernetes/kubernetes/blob/v1.24.9/staging/src/k8s.io/apiserver/pkg/server/genericapiserver_graceful_termination_test.go and try again.

**Comment by vpnachev** [comment]
I managed to write a small unit test that catches the apiserver shutdown hang, therefore I directly pushed the change [317db1f](https://github.com/kubernetes/kubernetes/pull/113741/commits/317db1fdff4dde469c23eab824c85ffe851abd55) to this PR instead of opening another one.

**Comment by aleksandra-malinowska** [comment]
Is any fix for this issue merged yet? I'm wondering if there are any versions of 1.24 that are not affected.

**Comment by dguendisch** [comment]
Not to my knowledge (for 1.24).
In Gardener we went now for workarounds to avoid hitting this issue.
(one workaround is https://github.com/gardener/gardener/pull/7250, the other workaround will be to ensure (from a separate sidecar) that kapi is properly killed and not stuck in shutdown)

**Comment by tkashem** [comment]
> @tkashem Any chance you can provide some guidance here since you wrote the initial code

@apelisse I will take a look at it, thanks!
/assign

**Comment by ialidzhikov** [comment]
@tkashem any news?

**Comment by tkashem** [comment]
@apelisse @aojea i posted my finding in the above comment, i would like your thoughts here as to its merit for backport.

**Comment by apelisse** [comment]
I would think so. Do we have any good way to test that this is solved? Very much appreciate your help @tkashem, thank you!

**Comment by tkashem** [comment]
@apelisse Yes, I used the test in this PR to reproduce the issue (the test fails), and with the minimum change I posted above the test passes.

The branch where I tested it: https://github.com/kubernetes/kubernetes/compare/release-1.24...tkashem:kubernetes:pr-113741-test?expand=1

@vpnachev can incorporate the changes in this PR (or I can open a new PR) if we decide to backport it.

**Comment by vpnachev** [comment]
Thank you for the time and attention to this change, @tkashem!

Technically, I am fine to push https://github.com/tkashem/kubernetes/commit/842244dfba448c3fc70a614deaf1f89986062ffb to this PR, but conceptually it will no longer be a cherry-pick of #110094. From this point of view, if it is decided the fix to be included in 1.24, I think it would be better another PR to be opened. 

Of course, if the maintainers think it is acceptable to still push the change with this PR, I am fine to do it.

**Comment by vpnachev** [comment]
Kubernetes v1.24 officially reached its end of life today, hence there is no need of this PR. 
Thanks everyone for the contribution to the change and sorry that we have not managed to get it in.

**Pull request closed without merging**
