### PR TITLE
Fix typo in util_linux.go

### PR DESCRIPTION
**Pull request by farah**
**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:
Fixes a typo.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by farah** [comment]
I don't understand how this could fail? All I changed was a word in a comment.

**Comment by SergeyKanzhelev** [comment]
Can you also fix another occurrence of this typo:

pkg/kubelet/cri/remote/util/util_unix.go:
  59: 	// Create the socket on a tempfile and move it to the destination socket to handle improprer cleanup

pkg/kubelet/util/util_unix.go:
  59: 	// Create the socket on a tempfile and move it to the destination socket to handle improprer cleanup

**Comment by farah** [comment]
Was hoping nobody would catch those. Was saving those for another PR 😁

**Review by SergeyKanzhelev — APPROVED** [review]

**Pull request merged**
