### PR TITLE
Add few logs to e2e to help track status discrepancies

### PR DESCRIPTION
**Pull request by soltysh**
#### What type of PR is this?
/kind cleanup
/sig apps
/sig testing

#### What this PR does / why we need it:
This adds a few logs which will help track the problem described in https://github.com/kubernetes/kubernetes/issues/121397

#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
/assign @mimowo 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by soltysh** [comment]
/triage accepted
/priority backlog
/hold 
until we make sure we see what we want

**Comment by soltysh** [comment]
/hold 
this is working as expected

**Comment by soltysh** [comment]
/hold cancel
I've meant above :sweat:

**Comment by mimowo** [comment]
I'm running this locally, and I'm getting different logs at STEP 1 (I believe this is the only STEP here @soltysh you think might be wrong here). 

So, I'm getting:
```
  Oct 24 12:00:43.533: INFO: STEP 1: v1.StatefulSetStatus{ObservedGeneration:1, Replicas:3, ReadyReplicas:3, CurrentReplicas:3, UpdatedReplicas:3, CurrentRevision:"ss3-544c8dd79d", UpdateRevision:"ss3-544c8dd79d", CollisionCount:(*int32)(0xc004e00e60), Conditions:[]v1.StatefulSetCondition(nil), AvailableReplicas:3}
  Oct 24 12:00:53.576: INFO: STEP 2: v1.StatefulSetStatus{ObservedGeneration:2, Replicas:3, ReadyReplicas:3, CurrentReplicas:1, UpdatedReplicas:2, CurrentRevision:"ss3-544c8dd79d", UpdateRevision:"ss3-5d57fd86c", CollisionCount:(*int32)(0xc00168c4c0), Conditions:[]v1.StatefulSetCondition(nil), AvailableReplicas:3}
  Oct 24 12:01:14.128: INFO: STEP 3: v1.StatefulSetStatus{ObservedGeneration:2, Replicas:3, ReadyReplicas:3, CurrentReplicas:1, UpdatedReplicas:2, CurrentRevision:"ss3-544c8dd79d", UpdateRevision:"ss3-5d57fd86c", CollisionCount:(*int32)(0xc001af0580), Conditions:[]v1.StatefulSetCondition(nil), AvailableReplicas:3}
```
So for me at `STEP 2` I get `CurrentReplicas:1, UpdatedReplicas:2` and you get `CurrentReplicas:2, UpdatedReplicas:0`. I think both of the answers are actually possible based on the timing. Currently `STEP 2` is logged when the things are changing. Namely: `CurrentReplicas` go down from 3 to 1, and `UpdatedReplicas` go up from 0 to 2. This stabalizes only after ""Await for all replicas running, all are updated but pod-0".

**Comment by mimowo** [comment]
Now, in the second experiment I log the event types with `kubectl get sts -A -w --output-watch-events -o custom-columns="TYPE:.type,NAME:.object.metadata.name,REPLICAS:.object.status.replicas,CURRENT:.object.status.currentReplicas,UPDATED:.object.status.updatedReplicas,CURRENT_REVISION:.object.status.currentRevision,UPDATE_REVISION:.object.status.updateRevision" | ts '%Y-%m-%d %H:%M:%.S'`

```
2023-10-24 13:04:08.584022 TYPE    NAME   REPLICAS   CURRENT   UPDATED   CURRENT_REVISION   UPDATE_REVISION
2023-10-24 13:04:08.584252 ADDED   ss3    0          <none>    <none>    <none>             <none>
2023-10-24 13:04:08.616193 MODIFIED   ss3    0          <none>    <none>    ss3-544c8dd79d     ss3-544c8dd79d
2023-10-24 13:04:08.624835 MODIFIED   ss3    1          1         1         ss3-544c8dd79d     ss3-544c8dd79d
2023-10-24 13:04:09.857002 MODIFIED   ss3    1          1         1         ss3-544c8dd79d     ss3-544c8dd79d
2023-10-24 13:04:09.863565 MODIFIED   ss3    2          2         2         ss3-544c8dd79d     ss3-544c8dd79d
2023-10-24 13:04:12.188318 MODIFIED   ss3    2          2         2         ss3-544c8dd79d     ss3-544c8dd79d
2023-10-24 13:04:12.210142 MODIFIED   ss3    3          3         3         ss3-544c8dd79d     ss3-544c8dd79d
2023-10-24 13:04:13.865437 MODIFIED   ss3    3          3         3         ss3-544c8dd79d     ss3-544c8dd79d
2023-10-24 13:04:18.630139 MODIFIED   ss3    3          3         3         ss3-544c8dd79d     ss3-544c8dd79d
2023-10-24 13:04:18.647282 MODIFIED   ss3    3          2         <none>    ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:19.277765 MODIFIED   ss3    3          2         <none>    ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:19.883396 MODIFIED   ss3    2          2         <none>    ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:19.889099 MODIFIED   ss3    3          2         1         ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:21.894871 MODIFIED   ss3    3          1         1         ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:22.179636 MODIFIED   ss3    3          1         1         ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:22.890276 MODIFIED   ss3    2          1         1         ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:22.894888 MODIFIED   ss3    3          1         2         ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:24.894589 MODIFIED   ss3    3          1         2         ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:28.676293 MODIFIED   ss3    3          <none>    2         ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:28.951458 MODIFIED   ss3    3          <none>    2         ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:29.358016 MODIFIED   ss3    2          <none>    2         ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:39.210137 MODIFIED   ss3    3          1         2         ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:40.930777 MODIFIED   ss3    3          1         2         ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:49.738115 MODIFIED   ss3    3          1         2         ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:49.749475 MODIFIED   ss3    3          1         2         ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:49.756527 MODIFIED   ss3    3          1         1         ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:50.204818 MODIFIED   ss3    3          1         1         ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:50.970618 MODIFIED   ss3    2          1         1         ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:50.995624 MODIFIED   ss3    2          1         <none>    ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:51.221810 MODIFIED   ss3    2          1         <none>    ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:51.976022 MODIFIED   ss3    1          1         <none>    ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:51.983522 MODIFIED   ss3    1          <none>    <none>    ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:52.537332 MODIFIED   ss3    1          <none>    <none>    ss3-544c8dd79d     ss3-5d57fd86c
2023-10-24 13:04:52.975335 MODIFIED   ss3    0          <none>    <none>    ss3-5d57fd86c      ss3-5d57fd86c
2023-10-24 13:04:59.756551 DELETED    ss3    0          <none>    <none>    ss3-5d57fd86c      ss3-5d57fd86c
```

**Pull request closed without merging**
