### PR TITLE
loadbalancer and loadbalancer claim proposal

### PR DESCRIPTION
**Pull request by mqliang**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37269)

### CODE REVIEW

**Comment by mqliang** [comment]
@bprashanth 

cc @ddysher @kubernetes/sig-network

**Comment by mqliang** [comment]
I signed it

**Comment by caseydavenport** [comment]
@kubernetes/sig-network-proposals

**Comment by ddysher** [comment]
@mqliang close and move to community repo?

**Comment by mqliang** [comment]
close this infavour of https://github.com/kubernetes/community/pull/275

**Pull request closed without merging**
