### PR TITLE
Http3 testing

### PR DESCRIPTION
**Pull request by aojea**
/kind feature

#### What this PR does / why we need it:

Add support to agnhost to be able to test HTTP3 in the CI

#### Which issue(s) this PR fixes:

Related to: https://github.com/kubernetes/kubernetes/issues/106864

#### Special notes for your reviewer:

Depends on: https://github.com/kubernetes/kubernetes/pull/107015

#### Does this PR introduce a user-facing change?
```release-note
e2e agnhost image support HTTP3
```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @claudiubelu @spiffxp @BenTheElder 
/hold
depends on https://github.com/kubernetes/kubernetes/pull/107015

**Comment by dims** [comment]
this PR has been on hold for about 2 weeks. Can you please see how to unblock this by reviewing comments etc? or please close this out (Trying to declutter our open list of PRs)

**Comment by BenTheElder** [comment]
can we wait for go to add http3 to the stdlib? or is that not happening?

**Comment by aojea** [comment]
> can we wait for go to add http3 to the stdlib? or is that not happening?

doesn't seem something that is going to happen 
https://github.com/golang/go/issues/32204

anyway, I'd like to add http/3 to the apiserver, I opened a thread in the mailing list and probably will write a KEP soon unless there is some negative feedback, that will bring the dependencies and solve this problem

**Pull request closed without merging**
