### PR TITLE
[release 1.5] Cherrypick: Fixed wc zombie goroutine issue

### PR DESCRIPTION
**Pull request by dashpole**
cherrypick of #39477.
I forgot about this until now...

cc @saad-ali

### CODE REVIEW

**Comment by dashpole** [comment]
@k8s-bot node e2e test this

**Comment by dashpole** [comment]
@k8s-bot node e2e test this

**Comment by dashpole** [comment]
it was failing to set up firewalls before the test.  The testgrid would seem to indicate the problem is resolved.
@k8s-bot node e2e test this

**Comment by saad-ali** [comment]
Assigning to 1.5 branch owner: @mwielgus

**Pull request merged**
