### PR TITLE
WIP: component-base/metrics: enable openmetrics

### PR DESCRIPTION
**Pull request by dgrisonnet**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

Enable the OpenMetrics metrics format for all components.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dgrisonnet** [comment]
This is very much WIP as I wanted to check what was going to break if we were to enable OpenMetrics for all components before delving into adding new integration tests.

**Comment by logicalhan** [comment]
I don't understand the point of this... Prometheus' open-metrics format is effectively abandoned as is OpenMetrics in general.

**Comment by dgrisonnet** [comment]
It is not abandoned in the end. They are just archiving the repo and are planning to put the format itself in Prometheus: https://cloud-native.slack.com/archives/C01AUBA4PFE/p1692293964333339?thread_ts=1692293362.079469&cid=C01AUBA4PFE

There is also an ongoing effort being tracked to support native histograms in the OpenMetrics format: https://github.com/prometheus/prometheus/issues/11265

**Comment by dgrisonnet** [comment]
Checking scalability tests as well.

/test pull-kubernetes-e2e-gce-100-performance

**Comment by dashpole** [comment]
Just as a note: this change is a no-op unless our tests are scraping metrics with the openmetrics header set: https://github.com/prometheus/common/blob/main/expfmt/encode.go#L86, which I suspect they are not.

**Comment by logicalhan** [comment]
> Just as a note: this change is a no-op unless our tests are scraping metrics with the openmetrics header set: https://github.com/prometheus/common/blob/main/expfmt/encode.go#L86, which I suspect they are not.

Yeah they don't. I actually prototyped this before, you are going to want to set the header prior to making the requests in the tests which don't exist yet.

**Comment by dgrisonnet** [comment]
Correct, but for the scalability tests where an actual Prometheus instance is run, we will already expose OpenMetrics with that change since OpenMetrics is accepted by default by the Prometheus server: https://github.com/prometheus/prometheus/blob/main/scrape/scrape.go#L811. No?

**Comment by dashpole** [comment]
True.  I didn't realize the header was added by default now

**Comment by logicalhan** [comment]
> Correct, but for the scalability tests where an actual Prometheus instance is run, we will already expose OpenMetrics with that change since OpenMetrics is accepted by default by the Prometheus server: https://github.com/prometheus/prometheus/blob/main/scrape/scrape.go#L811. No?

I'd still want to test it with unit tests. It's not obvious what's happening over the wire in a remote scalability test.

**Comment by dgrisonnet** [comment]
Yeah definitely that's my plan, I just wanted to verify if it was breaking anything before adding new tests.

**Comment by dgrisonnet** [comment]
I continued discussing with the Prometheus team and it seems that there are currently some issues with client_golang support for OpenMetrics which will cause collision with some metrics that we are using: https://github.com/prometheus/client_golang/issues/829.

To avoid these issues, we came to the conclusion that starting with the Prometheus proto format would be better as it doesn't have any compatibility issues and it supports both exemplars and native histograms. The full discussion happened in https://cloud-native.slack.com/archives/C01AUBA4PFE/p1692705555987529?thread_ts=1692293362.079469&cid=C01AUBA4PFE, but the gist of it is that OpenMetrics is still being improved and until the incompatibilities issues are resolved, it is safe for us to start adding exemplars and native histograms while telling our users that if they want them to be consumed by Prometheus they need to set `--enable-feature=native-histograms` on their server.

**Pull request closed without merging**
