### PR TITLE
Migrate gke e2e test to sig cluster

### PR DESCRIPTION
**Pull request by guangxuli**
**What this PR does / why we need it**:

Migrate gke relevant e2e test files to sig clusterops. Not fully sure whether these e2e files exactly belong to sig-clusterops, IMO, it fits in some degree, feel free to contact me if you have better idea.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Ref Umbrella issue #49161

**Special notes for your reviewer**:

**Release note**:
```release-note
none
```

### CODE REVIEW

**Comment by guangxuli** [comment]
kindly ping @liggitt expect your suggestion here.

**Comment by liggitt** [comment]
reassigning per https://github.com/kubernetes/community/tree/master/sig-cluster-ops

**Comment by jdumars** [comment]
@abgworrall FYI this is probably an early task for SIG GCP

**Comment by guangxuli** [comment]
All test passed @abgworrall @jdumars @janetkuo ptal.

**Comment by jdumars** [comment]
@guangxuli can you please rebase?  Thanks!

**Comment by guangxuli** [comment]
@jdumars rebased, thanks, could you help you review this.

**Comment by jdumars** [comment]
Thanks @guangxuli  - I have asked @abgworrall to look at this since it's not really a SIG Cluster Ops thing, and is really for SIG-GCP.  I don't want this to get lost in the shuffle.

**Comment by guangxuli** [comment]
@jdumars sure, thanks, if you and @abgworrall agree, i will move this file to sig gcp.

**Comment by guangxuli** [comment]
no plan to rebase this PR since it has been move to another new PR due to our discussion.

**Comment by guangxuli** [comment]
I should close this PR since it has been instead by PR #55212

**Pull request closed without merging**
