### PR TITLE
kube-flannel bridge

### PR DESCRIPTION
**Pull request by mikedanese**
kube flannel bridge, this is a bad place for it.

depends on #28178 and #27880

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29208)

### CODE REVIEW

**Comment by luxas** [comment]
Is this something we should use or are you only testing?
Isn't it possible to run flannel itself in a DaemonSet or do we get extra features when vendoring and writing a new binary?

It might make sense for it to be in hyperkube (aka "kube" in v1.4) 
cc @jbeda (I think you were asking for this)

**Comment by mikedanese** [comment]
It works, feel free to test it out. It only uses the flannel network manager and implements a subnet manager that uses cidr's assigned by the node controller. This is not possible without embedding flannel.

**Comment by justinsb** [comment]
If we use `--configure-cloud-routes=false`, does that avoid the need to embed flannel?

**Comment by mikedanese** [comment]
@justinsb Yes.

**Comment by eghobo** [comment]
@mikedanese: does it work with 'host-gw' backend?

**Comment by mikedanese** [comment]
Not yet but it will. I tested with the vxlan backend. Working on merging this into flannel proper right now.

https://github.com/kubernetes/kubernetes/pull/29208/commits/96bfcff5e0e1a86f04be0eee6ab241a03f3e876f#diff-9d4a714c7a2a167489bc50a4d1a53b40R50

**Comment by luxas** [comment]
I think this is great.
Some comments:
 - We should probably rename this to `kube-net-overlay` or something like that...
 - ...and include Weave and (maybe) Calico. A flag should be added to switch between those
 - Sane defaults should exist inside the app for the configs you now have in the ConfigMap

I can review this, and this is definitely something we want in v1.4!
You may split it up in small PRs if you want.
cc @kubernetes/sig-cluster-lifecycle

**Comment by luxas** [comment]
@mikedanese Does this work on bare-metal or have you only tested it in the cloud?

**Comment by mikedanese** [comment]
@luxas I have not tested on bare metal.

I will be moving this into the flannel project so the flannel daemon will have this functionality. Calico (which will use flannel in new versions(canal)) can just piggyback on this feature. Weave will have to implement a similar configuration backend inside the weave daemon.

**Pull request closed without merging**
