### PR TITLE
Move SSHTunneler to genericapiserver and remove federated-apiserver's dependency on pkg/master

### PR DESCRIPTION
**Pull request by nikhiljindal**
cc @jianhuiz

### CODE REVIEW

**Comment by lavalamp** [comment]
Why?

**Comment by nikhiljindal** [comment]
@lavalamp: pkg/master contains kubernetes apiserver specific code.
federation/cmd/federation-apiserver will use genericapiserver and will not depend on pkg/master.

Specifically, depending on pkg/master pulls in all kubernetes resoruces via https://github.com/kubernetes/kubernetes/blob/master/pkg/master/import_known_versions.go which we do not want in federation apiserver.

**Comment by lavalamp** [comment]
Oh, I see, it's about not including pkg/master from ubernetes.

I'm not sure if ubernetes needs this tunnling stuff at all but we can worry about that later.

**Comment by lavalamp** [comment]
LGTM

**Pull request merged**
