### PR TITLE
Update podCondition.lastTransitionTime on status change

### PR DESCRIPTION
**Pull request by mmiranda96**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Update lastTransitionTime of podCondition when condition.Status changes. See capture for detail:
Screen Shot 2021-05-18 at 5 47 53 PM

#### Which issue(s) this PR fixes:
Not a tracked issue.

#### Special notes for your reviewer:
This PR is a followup to #91282, which includes updated tests.

#### Does this PR introduce a user-facing change?
```release-note
Fixed a bug in which podCondition.lastTransitionTime was not updated whenever the status changed.
```

### CODE REVIEW

**Comment by matthyx** [comment]
> See capture for detail:

@mmiranda96 how do you reproduce this capture? This is weird and I don't understand why `updateLastTransitionTime` didn't do its job...

/hold

**Comment by mmiranda96** [comment]
> how do you reproduce this capture?

These are the steps that I followed to get the capture:
1. Create a local cluster.
2. Create a new pod. For this particular case, this is the template I used:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
```
3.  Get the pod YAML via `kubectl get po test -o yaml`.

>  I don't understand why `updateLastTransitionTime` didn't do its job...
It looks like it does. My change is a no-op, closing this PR. Sorry for the mess 😅

**Pull request closed without merging**
