### PR TITLE
[go1.23][DNM] .go-version: start testing with go1.23rc1

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
Start testing with go1.23rc1:https://groups.google.com/d/msgid/golang-dev/V3M-e00CT0ecP2z5Rvyz2Q%40geopod-ismtpd-16?utm_medium=email&utm_source=footer

### CODE REVIEW

**Comment by MadhavJivrajani** [comment]
`pull-kubernetes-dependencies` is expected to fail since we aren't actually bumping the version here.

**Comment by MadhavJivrajani** [comment]
The verify failures seem legitimate, starting a discussion here: https://github.com/dominikh/go-tools/issues/1565

**Comment by MadhavJivrajani** [comment]
Bumping to use HEAD of go-tools got rid of the panics.

We now have a bunch of linter errors like
```
ERROR: cmd/kube-scheduler/app/options/configfile_test.go:106:20: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
ERROR: 			expectedErr:    fmt.Errorf(apiVersionMissing),
ERROR: 			                ^
ERROR: cmd/kube-scheduler/app/options/configfile_test.go:112:20: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
ERROR: 			expectedErr:    fmt.Errorf(apiVersionTooOld),
ERROR: 			                ^
ERROR: cmd/kubeadm/app/cmd/completion_test.go:32:3: SA1006: printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
ERROR: 		t.Errorf(shellsError)
ERROR: 		^
```

Fairly certain these come from here: https://github.com/dominikh/go-tools/commit/6787ce86c9478050a346fd3f222c10b1d5ae3cf3

Considering we will be backporting any fixes here, do we want to do a cleanup of all of these occurrences? Or do we want to exempt them?

Might be a little tedious to do the backport, but we should probably do it. Thoughts @dims? (after the grpc stuff has settled down 🙏🏼 )

**Comment by dims** [comment]
> Might be a little tedious to do the backport, but we should probably do it. Thoughts @dims? (after the grpc stuff has settled down 🙏🏼 )

let's ask other too... @liggitt ? ( am ok either with silencing or backport )

**Comment by liggitt** [comment]
can we exclude the SA1006 check in the verify runner in a backport, then fixup in code in HEAD only?

**Comment by MadhavJivrajani** [comment]
Ack @liggitt, we can exempt for back ports 👍

**Comment by MadhavJivrajani** [comment]
New failures
```
ERROR: pkg/util/procfs/procfs_linux_test.go:72:5: SA4032: due to the file's build constraints, runtime.GOOS will never equal "darwin" (staticcheck)
ERROR: 	if runtime.GOOS == "darwin" || runtime.GOOS == "windows" {
ERROR: 	   ^
ERROR: pkg/util/procfs/procfs_linux_test.go:82:5: SA4032: due to the file's build constraints, runtime.GOOS will never equal "darwin" (staticcheck)
ERROR: 	if runtime.GOOS == "darwin" || runtime.GOOS == "windows" {
ERROR: 	   ^
ERROR: pkg/util/procfs/procfs_linux_test.go:101:5: SA4032: due to the file's build constraints, runtime.GOOS will never equal "darwin" (staticcheck)
ERROR: 	if runtime.GOOS == "darwin" || runtime.GOOS == "windows" {
ERROR: 	   ^
ERROR: staging/src/k8s.io/component-base/logs/example/test/logger_test.go:45:1: SA3000: TestMain should call os.Exit to set exit code (staticcheck)
ERROR: func TestMain(m *testing.M) {
ERROR: ^
```

**Comment by dims** [comment]
/close

i think we are done with this, right @MadhavJivrajani ? please reopen if not.

**Pull request closed without merging**
