### PR TITLE
Automated cherry pick of #70392: Lookup PX api port from k8s service

### PR DESCRIPTION
**Pull request by harsh-px**
Cherry pick of #70392 on release-1.13.

#70392: Lookup PX api port from k8s service

### CODE REVIEW

**Comment by aleksandra-malinowska** [comment]
@harsh-px Looks reasonable to cherry-pick, but it still needs LGTM and approve from SIG (as any other PR)

**Comment by harsh-px** [comment]
/assign @jsafrane

for approval

**Pull request merged**
