### PR TITLE
fix the winkernel proxy bug, when we try to delete a hnsendpoint which is still in use.

### PR DESCRIPTION
**Pull request by xlgao-zju**
**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:
fix the winkernel proxy bug, when we try to delete a hnsendpoint which is still in use.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix the winkernel proxy bug, when we try to delete a hnsendpoint which is still in use.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by xlgao-zju** [comment]
ping @dineshgovindasamy @madhanrm @feiskyer @ksubrmnn for review

**Comment by ksubrmnn** [comment]
@kumarvin123 ptal

**Comment by ksubrmnn** [comment]
Thanks for the change @xlgao-zju!

Can you use this map with endpoint ref counts in your change? It should be more efficient https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/winkernel/proxier.go#L584

FYI @elweb9858 please continue to review

**Comment by ksubrmnn** [comment]
I believe this issue was fixed in https://github.com/kubernetes/kubernetes/pull/91706. I think this will be available in 1.19. Can you try building a binary with that change?

**Comment by elweb9858** [comment]
Hi @xlgao-zju, thanks for looking into this issue! @sbangari  is currently addressing this in https://github.com/kubernetes/kubernetes/pull/93638

**Comment by xlgao-zju** [comment]
> Hi @xlgao-zju, thanks for looking into this issue! @sbangari is currently addressing this in #93638

so, once https://github.com/kubernetes/kubernetes/pull/93638 is merged, we can close this issue.

**Comment by elweb9858** [comment]
> > Hi @xlgao-zju, thanks for looking into this issue! @sbangari is currently addressing this in #93638
> 
> so, once #93638 is merged, we can close this issue.

I believe so. @sbangari  can confirm.

**Comment by sbangari** [comment]
> > > Hi @xlgao-zju, thanks for looking into this issue! @sbangari is currently addressing this in #93638
> > 
> > 
> > so, once #93638 is merged, we can close this issue.
> 
> I believe so. @sbangari can confirm.

Yes #93638 will resolve this issue.

**Comment by feiskyer** [comment]
let's close this PR then.

/close

**Pull request closed without merging**
