### PR TITLE
Use Watch() for VerifyControllerAttachedVolume instead of a single poll

### PR DESCRIPTION
**Pull request by codablock**
This PR is a replacement for https://github.com/kubernetes/kubernetes/pull/40603. I was not able to push fixes and rebases to the original branch as I don't have access to the Github organization anymore.

CC @saad-ali You probably have to update the PR link in [Q2 2017 (v1.7)](https://docs.google.com/spreadsheets/d/1t4z5DYKjX2ZDlkTpCnp18icRAQqOE85C1T1r2gqJVck/edit#gid=14624465)

I assume the PR will need a new "ok to test" 

**ORIGINAL PR DESCRIPTION**
This PR changes VerifyControllerAttachedVolume from the kubelet volume manager to use a watch instead of a single get for node status.

VerifyControllerAttachedVolume is an asynchronous operation which returned pretty fast with an error in and thus exponential backoff hit pretty hard here. This PR changes the operation to wait/watch for some time (1 minute) for the node status to report that the volume is attached and only returns an error after timeout.

It also moves the ReportedInUse check into the watch loop and thus makes us independent from the node status cache.

This PR is an alternative solution for the same problem I tried to fix in https://github.com/kubernetes/kubernetes/pull/40531. I would prefer the new solution.

```release-note
NONE
```

### CODE REVIEW

**Comment by spiffxp** [comment]
@k8s-bot ok to test

**Comment by rootfs** [comment]
@codablock can you fix the failed tests at https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45344/pull-kubernetes-unit/29661/

**Comment by rootfs** [comment]
@codablock would the watch block `VerifyControllerAttachedVolume()` and `reconcile()` and other operations?

**Comment by codablock** [comment]
@rootfs You just made me question this whole PR for a few seconds :D But after checking the source, I found https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go#L48, which states that operations are executed in parallel, so the watch will not block the other operations.

I'm looking into the test failure atm.

**Comment by rootfs** [comment]
@codablock i see, it is a goroutinemap, that makes sense now.

**Comment by codablock** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by rootfs** [comment]
lgtm to me
@saad-ali @jingxu97 @tsmetana want to take a look?

**Comment by tsmetana** [comment]
Looks OK.

**Comment by codablock** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by codablock** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by derekwaynecarr** [comment]
code looks fine to me, but will defer to @saad-ali

**Comment by codablock** [comment]
Can anyone take a look? This PR (including the original one) is in my open PRs list for quite some time now and as more time passes, as harder it gets for me to do rebases and get back into the code when discussion happens.

I'll do a final rebase when I get the final lgtm, if that's ok with everyone.

**Comment by codablock** [comment]
I'm thinking about closing this PR, and will probably do this in the next days. If anyone else wants to pick up the changes and create a new PR, I'm fine with that.

**Comment by codablock** [comment]
Closing as there seems to be no interest in this.

**Comment by oivindoh** [comment]
Struggling with the issue this fixes and noticing that this wonderful fix kind of just fizzled out makes me sad :-(

**Comment by codablock** [comment]
The code is still available here: https://github.com/codablock/kubernetes/tree/verifycontrollerattached_watch

It's just that I'm unable to properly update/rebase the code with the latest code as I don't work on k8s related projects at the moment. So if anyone wants to pick up the work and bring it up-to-date, I'm happy to see this.

**Pull request closed without merging**
