### PR TITLE
Remove pkg/util/goroutinemap/exponentialbackoff from lintignore with changes

### PR DESCRIPTION
**Pull request by chrischdi**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Fix golint failures of pkg/util/goroutinemap/exponentialbackoff

**Which issue(s) this PR fixes**:

Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by matthyx** [comment]
@chrischdi can you rebase the PR and fix the conflict?

**Comment by chrischdi** [comment]
> @chrischdi can you rebase the PR and fix the conflict?

Hi @matthyx,

I just did the rebase :-)

**Comment by matthyx** [comment]
/test pull-kubernetes-node-e2e-containerd
/lgtm
@saad-ali PTAL

**Comment by chrischdi** [comment]
/remove-lifecycle stale

@saad-ali maybe we can get this merged soon? :-)

I rebased again.

**Pull request closed without merging**
