### PR TITLE
Fix cross-compliation of mount_exec.go

### PR DESCRIPTION
**Pull request by jsafrane**
Added dummy implementation for non-linux platforms

Fixes: #55711

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@jsafrane you need a bit more than removing the `// +build linux` comment

this seems to work for me - http://paste.openstack.org/show/626283/

**Comment by jsafrane** [comment]
I created new `exec_mount_unsupported.go` in the end.

**Comment by dims** [comment]
Looks cleaner than my effort +1 @jsafrane

**Comment by david-mcmahon** [comment]
@kubernetes/test-infra-maintainers Do we not have a cross build CI job?  Or maybe the problem is we don't have one for the submit queue, which is understandable since it would take quite some time to run.

**Comment by david-mcmahon** [comment]
Of course we have one. https://k8s-testgrid.appspot.com/sig-release-misc#cross-build

**Comment by ixdy** [comment]
We have a cross build job for PRs, but it only runs on request or when certain filenames are touched. The offending PR didn't touch any files that would trigger the CI job.

**Comment by david-mcmahon** [comment]
Thanks @ixdy.  Is it worth expanding the net at all based on this failure?

**Comment by ixdy** [comment]
I'm not sure how we'd have detected this one; our triggering is based only on filenames, and nothing here looked suspicious. (Usually the platform-specific files have a suffix like `_linux.go`, `_windows.go`, or `_darwin.go`, which we would trigger on.)

**Comment by rmmh** [comment]
We should add a verify check that build tags are only used in appropriately suffixed files.

`// +build linux` shouldn't occur in a file that isn't marked as OS-specific.

We have 9 files outside of vendor/third_party that violate this, and wouldn't trigger the cross build test:

```shell
~/k8s$ ag '// \+build linux' | grep -Ev '_linux|_test|vendor/|third_party/'
test/e2e_node/resource_collector.go:1:// +build linux
test/e2e_node/benchmark_util.go:1:// +build linux
pkg/kubelet/cm/node_container_manager.go:1:// +build linux
pkg/volume/util/fs.go:1:// +build linux darwin
pkg/util/bandwidth/linux.go:1:// +build linux
pkg/util/mount/nsenter_mount.go:1:// +build linux
pkg/util/mount/exec_mount.go:1:// +build linux
pkg/util/nsenter/nsenter.go:1:// +build linux
pkg/util/flock/flock_unix.go:1:// +build linux darwin freebsd openbsd netbsd dragonfly
```

**Pull request merged**
