### PR TITLE
Automated cherry pick of #24609 #25504 #25763 #25609 #25706

### PR DESCRIPTION
**Pull request by andyzheng0831**
Cherry pick of #24609 #25504 #25763 #25609 #25706 on release-1.2.

### CODE REVIEW

**Comment by andyzheng0831** [comment]
@zmerlynn we have several PRs need to be cherry picked into release-1.2. Without them our current jenkins testing GCI on release-1.2 branch is broken. I packed them in one PR as there are many conflicts with each other. I verified that with this PR we can spin up GCI cluster with all kube-system pods running.

Please help me set the right labels. Thanks!

**Comment by zmerlynn** [comment]
Not sure why it didn't pick up the `cherrypick-approved` on any of the base PRs, but they were all approved, so I approved this one.

**Comment by andyzheng0831** [comment]
I guess the jenkins testing release-1.2 branch does not cover GCI config. We only switched the master branch to using GCI. I will add a "e2e-not-required" to reduce the commit queue burden.

**Comment by andyzheng0831** [comment]
@k8s-bot unit test this issue #25513

**Pull request merged**
