### PR TITLE
Automated cherry pick of #67288: Immediately close the other side of the connection when proxying

### PR DESCRIPTION
**Pull request by tossmilestone**
Cherry pick of #67288 on release-1.9.

#67288: Immediate close the other half of the connection when

**Release note**:
```release-note
Immediately close the other side of the connection when proxying.
```

### CODE REVIEW

**Comment by mbohlool** [comment]
Please add a release note to the base PR.

**Comment by tossmilestone** [comment]
@mbohlool updated the release note

**Comment by tossmilestone** [comment]
@mbohlool the original pr already has none release note, and I have no permission to edit the pr. Could you help to do that?

**Pull request merged**
