### PR TITLE
change the fmt package to pkg/errors

### PR DESCRIPTION
**Pull request by jianglingxia**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
switch to github.com/pkg/errors the packages as follows:
 cluster/images/etcd-version-monitor/etcd-version-monitor.go
 cmd/kubeadm/app/cmd/util/cmdutil.go
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fabriziopandini** [comment]
I comment for the kubeadm part only
@yuexiao-wang could you kindly confirm that this PR doesn't overlaps with your work/sync with @jianglingxia  on this effort?
/hold

@jianglingxia  please add Rif to the issue you are working on

**Comment by jianglingxia** [comment]
some pr left some file of cmd/kubeadm/app/cmd/util/cmdutil.go and fixed it!

**Comment by jianglingxia** [comment]
@yuexiao-wang you can fixed the cmd/kubeadm/app/cmd/util/cmdutil.go file in your pr,in kubeadm left the fie! I will close the pr!thanks
@ fabriziopandini  thank you for your advices!

**Comment by yuexiao-wang** [comment]
@jianglingxia thanks.
I will fix them in my PR

**Pull request closed without merging**
