### PR TITLE
Separate out cri related code into self contained package

### PR DESCRIPTION
**Pull request by dims**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Previous attempts to extract cri related code met with stiff resistance. We had PRs earlier to move streaming to staging/ etc. So in this PR we just consider moving code into a package that be used standalone w/o dragging in all of k/k. 

Essentially the `pkg/kubelet/cri` uses only stuff in staging/ and does not use anything else inside k8s.io/kubernetes. We have a new .import-restrictions in that directory to ensure that things stay that way.

two things to note:
- had to move logreduction into component-base (anyone have a better suggestion?)
- copied some of the utils code into remote/ so we will have some duplication.

Also note that i've prototyped this on the containerd/cri side as well:
https://github.com/containerd/cri/pull/1463

If we do this, `containerd/cri` repo vendor/ directory will pull in 15k LOC less than they do today

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
> Essentially the `pkg/kubelet/cri` uses only stuff in staging/ and does not use anything else inside k8s.io/kubernetes.

I'm having a hard time seeing what this move actually accomplishes at a module level, dependency-wise... anything using this package still depends on k8s.io/kubernetes, right?

**Comment by dims** [comment]
@liggitt yes, this is step 1. The longer term plan is for CRI to support streaming directly per @tallclair comment in https://github.com/kubernetes/enhancements/pull/937#issuecomment-480342251

**Comment by dims** [comment]
@liggitt once this lands containerd/cri will ONLY need the cri/ package from k8s.io/kubernetes until we make the changes for updating the CRI.

**Comment by mikebrow** [comment]
> @liggitt once this lands containerd/cri will ONLY need the cri/ package from k8s.io/kubernetes until we make the changes for updating the CRI.

@dims thank you for taking this problem on.  Solving, or at least improving, the downstream dependency packaging issues around the streaming package is pretty important for CRI integrations, esp. with the pressing demand for moving to go v1.14 & go modules. 

While moving the CRI dependencies for streaming into CRI makes a lot of sense from a container runtime perspective, other users of the streaming package may not be happy with that move. I'd be equally happy if the streaming package used "only stuff in staging/" and did "not use anything else inside k8s.io/kubernetes" and had "new .import-restrictions in that directory to ensure that things stay that way."  I don't think there would be a problem if the tests for CRI had one exception to the rule and used a combination of the CRI package and the streaming package if streaming isn't moved or copied to cri/.  Trying to keep from forking code if possible, esp. having to fork streaming/ to the container runtimes.

**Comment by liggitt** [comment]
golint is failing with:
```
Some packages in hack/.golint_failures do not exist anymore. Please remove them.

  pkg/kubelet/remote
```

**Comment by derekwaynecarr** [comment]
@mrunalp does this help reduce anything in cri-o as well?

**Comment by liggitt** [comment]
Isolating the streaming bits into their own package makes sense to me. I'm ok with this as long as the kubelet maintainers are ok with the util duplication

**Comment by derekwaynecarr** [comment]
I would like to get a summary for what cri-o and containerd are vendoring so we can prioritize a working path for both at the same time.  @mrunalp said he would comment on the deps for cri-o

**Comment by dims** [comment]
@derekwaynecarr 

- here's the WIP/analysis for CRI-O : https://github.com/cri-o/cri-o/pull/3757#issuecomment-627589396
- here's the WIP/analysis for containerd : https://github.com/containerd/cri/pull/1463

**Comment by mrunalp** [comment]
This is what we have in the crio go.mod file today:
```
require (
        ...
        k8s.io/apimachinery v0.17.4                                                                                                                                                                                 
        k8s.io/client-go v0.0.0                                                                                                                                                                                     
        k8s.io/cri-api v0.0.0                                                                                                                                                                                       
        k8s.io/klog v1.0.0                                                                                                                                                                                          
        k8s.io/kubernetes v1.18.1                                                                                                                                                                                   
        k8s.io/release v0.3.0                                                                                                                                                                                       
        k8s.io/utils v0.0.0-20200327001022-6496210b90e8                                                                                                                                                             
        ...                                                                                                                                                                                     
)                                                                                                                                                                                                                   
                                                                                                                                                                                                                    
replace (                                                                                                                                                                                                           
        k8s.io/api => k8s.io/kubernetes/staging/src/k8s.io/api v0.0.0-20200505125908-b48f5af2602b                                                                                                                   
        k8s.io/apiextensions-apiserver => k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver v0.0.0-20200505125908-b48f5af2602b                                                                           
        k8s.io/apimachinery => k8s.io/kubernetes/staging/src/k8s.io/apimachinery v0.0.0-20200505125908-b48f5af2602b                                                                                                 
        k8s.io/apiserver => k8s.io/kubernetes/staging/src/k8s.io/apiserver v0.0.0-20200505125908-b48f5af2602b                                                                                                       
        k8s.io/cli-runtime => k8s.io/kubernetes/staging/src/k8s.io/cli-runtime v0.0.0-20200505125908-b48f5af2602b                                                                                                   
        k8s.io/client-go => k8s.io/kubernetes/staging/src/k8s.io/client-go v0.0.0-20200505125908-b48f5af2602b                                                                                                       
        k8s.io/cloud-provider => k8s.io/kubernetes/staging/src/k8s.io/cloud-provider v0.0.0-20200505125908-b48f5af2602b                                                                                             
        k8s.io/cluster-bootstrap => k8s.io/kubernetes/staging/src/k8s.io/cluster-bootstrap v0.0.0-20200505125908-b48f5af2602b                                                                                       
        k8s.io/code-generator => k8s.io/kubernetes/staging/src/k8s.io/code-generator v0.0.0-20200505125908-b48f5af2602b                                                                                             
        k8s.io/component-base => k8s.io/kubernetes/staging/src/k8s.io/component-base v0.0.0-20200505125908-b48f5af2602b                                                                                             
        k8s.io/cri-api => k8s.io/kubernetes/staging/src/k8s.io/cri-api v0.0.0-20200505125908-b48f5af2602b                                                                                                           
        k8s.io/csi-translation-lib => k8s.io/kubernetes/staging/src/k8s.io/csi-translation-lib v0.0.0-20200505125908-b48f5af2602b                                                                                   
        k8s.io/kube-aggregator => k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator v0.0.0-20200505125908-b48f5af2602b                                                                                           
        k8s.io/kube-controller-manager => k8s.io/kubernetes/staging/src/k8s.io/kube-controller-manager v0.0.0-20200505125908-b48f5af2602b                                                                           
        k8s.io/kube-proxy => k8s.io/kubernetes/staging/src/k8s.io/kube-proxy v0.0.0-20200505125908-b48f5af2602b                                                                                                     
        k8s.io/kube-scheduler => k8s.io/kubernetes/staging/src/k8s.io/kube-scheduler v0.0.0-20200505125908-b48f5af2602b                                                                                             
        k8s.io/kubectl => k8s.io/kubernetes/staging/src/k8s.io/kubectl v0.0.0-20200505125908-b48f5af2602b                                                                                                           
        k8s.io/kubelet => k8s.io/kubernetes/staging/src/k8s.io/kubelet v0.0.0-20200505125908-b48f5af2602b                                                                                                           
        k8s.io/kubernetes => k8s.io/kubernetes v1.19.0-alpha.3                                                                                                                                                      
        k8s.io/legacy-cloud-providers => k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers v0.0.0-20200505125908-b48f5af2602b                                                                             
        k8s.io/metrics => k8s.io/kubernetes/staging/src/k8s.io/metrics v0.0.0-20200505125908-b48f5af2602b                                                                                                           
        k8s.io/sample-apiserver => k8s.io/kubernetes/staging/src/k8s.io/sample-apiserver v0.0.0-20200505125908-b48f5af2602b                                                                                         
)    
```

**Comment by mrunalp** [comment]
@dims Thanks for opening a PR with your analysis.

**Comment by dims** [comment]
@liggitt thanks for the review.

@derekwaynecarr let's get this in, as mentioned above it does not help cri-o bigtime right away as cri-o has way more dependencies. I can work with @mrunalp to do the same i did with containerd and file PRs down the road.

**Comment by mattjmcnaughton** [comment]
> /assign @mattjmcnaughton

I think we're on the same page conceptually @dims ! Thank you for your work here. I'll defer to one of the other folks tagged around the details, as they have a more complete picture of the whole system than I do.

**Comment by dims** [comment]
@derekwaynecarr @liggitt here's the plan on the containerd side https://github.com/containerd/cri/issues/1479#issuecomment-630847911

**Comment by mikebrow** [comment]
> @derekwaynecarr @liggitt here's the plan on the containerd side [containerd/cri#1479 (comment)](https://github.com/containerd/cri/issues/1479#issuecomment-630847911)

@dimms I think you meant to link to https://github.com/containerd/cri/pull/1463 1479 is a different issue.. (that of merging the containerd/containerd and containerd/cri repos.)

**Comment by dims** [comment]
whoops! thanks @mikebrow

**Comment by derekwaynecarr** [comment]
I tried to think if I had any alternate options for splitting this out, but nothing struck me, so this will do for now.

/approve
/lgtm

**Comment by gyuho** [comment]
> Does this PR introduce a user-facing change?:

This change should've highlighted that `k8s.io/kubernetes/pkg/kubelet/remote` is now `k8s.io/kubernetes/pkg/kubelet/cri/remote`.

**Pull request merged**
