### PR TITLE
kubeadm: Cleanup CommonConfiguration

### PR DESCRIPTION
**Pull request by rosti**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

`CommonConfiguration` is an interface, that aims at abstracting common
configuration of `InitConfiguration` and `JoinConfiguration`. It was never widely
used and never got too much functionality attached to it. With recent
developments in the kubeadm config field, it got even more out of touch with
reality and where things are going.
Thus, the only viable solution is to remove it completely.

**Which issue(s) this PR fixes**:

NONE

**Special notes for your reviewer**:

/cc @kubernetes/sig-cluster-lifecycle-pr-reviews
/area kubeadm
/priority important-longterm
/assign @neolit123
/assign @fabriziopandini

This is for 1.15!
/hold

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by yagonobre — COMMENTED** [review]
Thanks @rosti, removing code is always good!
/lgtm

**Comment by fabriziopandini** [comment]
@rosti thanks for the cleanup
/approve
/lgtm

**Review by neolit123 — COMMENTED** [review]
/hold cancel
i guess this is ready to go.

**Comment by neolit123** [comment]
/retest
i've reported the `pull-kubernetes-e2e-gce-100-performance` flake, but this is not getting any attention.

**Pull request merged**
