### PR TITLE
Keep kubectl delete hack for DaemonSet until 1.12

### PR DESCRIPTION
**Pull request by janetkuo**
**What this PR does / why we need it**:
As pointed out here: https://github.com/kubernetes/kubernetes/pull/64797#issuecomment-395152965, the server side fix is in 1.11. We're keeping kubectl hack until 1.12 to support 1.11 kubectl + 1.10.0-4 server. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by janetkuo** [comment]
We can also add something in kubectl that only runs the hack for server version <= 1.10.4, but not sure if it's worth it for this short-lived hack.

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by liggitt** [comment]
> We can also add something in kubectl to make it only run the hack for server version <= 1.10.4, but not sure if it's worth it for this short-lived hack.

yeah, that's not worth it.

@soltysh I would drop this as soon as 1.11 gets cut, since we're also picking the server-side fix back to 1.10.x, etc

**Comment by soltysh** [comment]
> @soltysh I would drop this as soon as 1.11 gets cut, since we're also picking the server-side fix back to 1.10.x, etc

If 1.10.x then - yeah, that makes sense.

**Pull request merged**
