### PR TITLE
if no cycle dependency , use framework in test/e2e_node/

### PR DESCRIPTION
**Pull request by tanjunchen**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

ref:https://github.com/kubernetes/kubernetes/issues/81427

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by tanjunchen** [comment]
/priority backlog
/cc @oomichi 
/cc @SataQiu 
Thanks

**Review by SataQiu — COMMENTED** [review]
Thanks @tanjunchen !
/lgtm
/approve

**Pull request merged**
