### PR TITLE
Fix data race by eliminating concurrency in test

### LINKED ISSUE #19151: Data race in pkg/client/record/event_test.go
```
=== RUN   TestWriteEventError
E1228 22:00:39.256276    7624 event.go:197] Unable to write event: 'A weird error' (may retry after sleeping)
E1228 22:00:39.257527    7624 event.go:197] Unable to write event: 'A weird error' (may retry after sleeping)
E1228 22:00:39.257625    7624 event.go:197] Unable to write event: 'A weird error' (may retry after sleeping)
E1228 22:00:39.257697    7624 event.go:197] Unable to write event: 'A weird error' (may retry after sleeping)
E1228 22:00:39.257761    7624 event.go:197] Unable to write event: 'A weird error' (may retry after sleeping)
E1228 22:00:39.257828    7624 event.go:197] Unable to write event: 'A weird error' (may retry after sleeping)
E1228 22:00:39.257930    7624 event.go:197] Unable to write event: 'A weird error' (may retry after sleeping)
E1228 22:00:39.258028    7624 event.go:197] Unable to write event: 'A weird error' (may retry after sleeping)
E1228 22:00:39.258095    7624 event.go:197] Unable to write event: 'A weird error' (may retry after sleeping)
E1228 22:00:39.258159    7624 event.go:197] Unable to write event: 'A weird error' (may retry after sleeping)
E1228 22:00:39.258220    7624 event.go:197] Unable to write event: 'A weird error' (may retry after sleeping)
E1228 22:00:39.258299    7624 event.go:197] Unable to write event: 'A weird error' (may retry after sleeping)
E1228 22:00:39.258455    7624 event.go:130] Unable to write event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo.14243213bbc18f38", GenerateName:"", Namespace:"baz", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Pod", Namespace:"baz", Name:"foo", UID:"bar", APIVersion:"version", ResourceVersion:"", FieldPath:""}, Reason:"Reason", Message:"retry2", Source:api.EventSource{Component:"eventTest", Host:""}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63586936840, nsec:255934264, loc:(*time.Location)(0x1e116c0)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63586936840, nsec:255934264, loc:(*time.Location)(0x1e116c0)}}, Count:1, Type:"Normal"}' (retry limit exceeded!)
E1228 22:00:39.259305    7624 event.go:197] Unable to write event: 'A weird error' (may retry after sleeping)
E1228 22:00:39.259496    7624 event.go:188] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo.142432146e91ed38", GenerateName:"", Namespace:"baz", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Pod", Namespace:"baz", Name:"foo", UID:"bar", APIVersion:"version", ResourceVersion:"", FieldPath:""}, Reason:"Reason", Message:"giveUp2", Source:api.EventSource{Component:"eventTest", Host:""}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63586936843, nsec:255934264, loc:(*time.Location)(0x1e116c0)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63586936843, nsec:255934264, loc:(*time.Location)(0x1e116c0)}}, Count:1, Type:"Normal"}': '' (will not retry!)
E1228 22:00:39.259989    7624 event.go:197] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E1228 22:00:39.260083    7624 event.go:197] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E1228 22:00:39.260172    7624 event.go:197] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E1228 22:00:39.260265    7624 event.go:197] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E1228 22:00:39.260348    7624 event.go:197] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E1228 22:00:39.260427    7624 event.go:197] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E1228 22:00:39.260495    7624 event.go:197] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E1228 22:00:39.260570    7624 event.go:197] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E1228 22:00:39.260652    7624 event.go:197] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E1228 22:00:39.260722    7624 event.go:197] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E1228 22:00:39.260796    7624 event.go:197] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E1228 22:00:39.260863    7624 event.go:197] Unable to write event: 'unexpected object: <nil>' (may retry after sleeping)
E1228 22:00:39.260944    7624 event.go:130] Unable to write event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"foo.14243214aa2cb738", GenerateName:"", Namespace:"baz", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Pod", Namespace:"baz", Name:"foo", UID:"bar", APIVersion:"version", ResourceVersion:"", FieldPath:""}, Reason:"Reason", Message:"retry1", Source:api.EventSource{Component:"eventTest", Host:""}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63586936844, nsec:255934264, loc:(*time.Location)(0x1e116c0)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63586936844, nsec:255934264, loc:(*time.Location)(0x1e116c0)}}, Count:1, Type:"Normal"}' (retry limit exceeded!)
==================
WARNING: DATA RACE
Read by goroutine 40:
  k8s.io/kubernetes/pkg/client/record.TestWriteEventError()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event_test.go:459 +0x12a9
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

Previous write by goroutine 42:
  k8s.io/kubernetes/pkg/client/record.TestWriteEventError.func1()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event_test.go:440 +0x308
  k8s.io/kubernetes/pkg/client/record.(*testEventSink).Create()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event_test.go:49 +0x6d
  k8s.io/kubernetes/pkg/client/record.recordEvent()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:169 +0x206
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartRecordingToSink.func1()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:125 +0x223
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:227 +0x14e

Goroutine 40 (running) created at:
  testing.RunTests()
      /tmp/workdir/go/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /tmp/workdir/go/src/testing/testing.go:494 +0xe4
  main.main()
      k8s.io/kubernetes/pkg/client/record/_test/_testmain.go:70 +0x20f

Goroutine 42 (running) created at:
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartEventWatcher()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:229 +0x8f
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartRecordingToSink()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:141 +0x9bc
  k8s.io/kubernetes/pkg/client/record.TestWriteEventError()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event_test.go:447 +0xb4d
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc
==================
```

### PR DESCRIPTION
**Pull request by krousey**
I broke out the error retry logic into a named function that could be
tested independently of the rest of the event processing framework. This
allows the test to know when the retry logic is done.

The problem with the original test was there was no reliable way to know
when it was done trying record an event. A sentinal event was being
used, but there is no ordering guarantee. I could have added
synchronization around attempts tracking to fix the data race, but the
test case was still fundamentally flawed and would error occasionally.

fixes #19151

### CODE REVIEW

**Comment by krousey** [comment]
Ran 130k iterations without failure or race.

**Comment by krousey** [comment]
@k8s-bot test this

**Comment by krousey** [comment]
@k8s-bot e2e test this

**Comment by krousey** [comment]
:fire::fire::fire::fire: Can't fix flake due to other flakes.... :fire::fire::fire::fire:  ... This is fine... :fire::fire::fire::fire:

@k8s-bot e2e test this

**Comment by krousey** [comment]
grrr another :snake: :eyes: :game_die: :game_die: 

@k8s-bot e2e test this. And do it right this time :pray:

**Comment by saad-ali** [comment]
LGTM

**Comment by krousey** [comment]
@k8s-bot e2e test this

**Comment by davidopp** [comment]
@k8s-bot test this please

**Comment by davidopp** [comment]
All tests passed so I'm going to manually merge since this should help with smoke flakes.

**Pull request merged**
