### PR TITLE
Change default node images for GCE to GCI

### PR DESCRIPTION
**Pull request by gmarek**
cc @wojtek-t @dchen1107

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37486)

### CODE REVIEW

**Comment by vishh** [comment]
Why are you changing the default @gmarek ?

**Comment by gmarek** [comment]
@vishh two reasons - 1) it's a default on GKE and I guess it should be default on GCE (not hard opinion there), 2) ContainerVM has some serious problems with itself (my machines are dying - I do have a hard opinion there).

**Comment by vishh** [comment]
@gmarek This switch cannot happen now for very many reasons, both technical ( feature differences between these images) and functional (user facing behavioral changes).

We need to fix the issues in ContainerVM since a lot of users still use it. It doesn't matter which image is the default.

**Comment by gmarek** [comment]
Fair enough.

**Comment by mtaufen** [comment]
+1 @vishh. There is some additional reasoning here: https://github.com/kubernetes/kubernetes/pull/36822

**Pull request closed without merging**
