### PR TITLE
Install pip in kubekins test image and install AWS cli when needed

### PR DESCRIPTION
**Pull request by ixdy**
Follow-on to https://github.com/kubernetes/test-infra/pull/66. This fixes AWS hopefully.

I haven't pushed the image yet.

cc @fejta

### CODE REVIEW

**Comment by spxtr** [comment]
I'm okay with this, but I would eventually like to use separate images for these things. Doing unit/integration tests plus e2e tests on all platforms using the same image is a bit nasty.

**Comment by ixdy** [comment]
Using the same image doesn't bother me as much (since there's still a lot that's needed by both), but I have no strong opinion.

@k8s-bot test this please, issue #IGNORE 

(we of course can't test the AWS bits until this gets fully pushed.)

**Comment by ixdy** [comment]
@k8s-bot node e2e test this please, issue #IGNORE

I suspect this was my own fault

**Comment by ixdy** [comment]
yep, all passing now.

**Comment by ixdy** [comment]
@k8s-bot node e2e test this please, flake #28255

**Pull request merged**
