### PR TITLE
JSONPath output shoud be JSON

### LINKED ISSUE #16707: jsonpath template output should be json
I would expect the output to be json. @kubernetes/kubectl 

$ kubectl get no -o jsonpath="{.items}"  
[map[kind:Node apiVersion:v1 metadata:map[uid:58f92fa4-81c3-11e5-8109-42010af0000b resourceVersion:3018 creationTimestamp:2015-11-03T00:39:31Z labels:map[kubernetes.io/hostname:k-5-master] name:k-5-master selfLink:/api/v1/nodes/k-5-master] spec:map[podCIDR:10.244.0.0/24 externalID:18000990123038728740 providerID:gce://mikedanese-k8s/us-central1-b/k-5-master unschedulable:true] status:map[nodeInfo:map[machineID: systemUUID:5A5B3748-A867-EBA7-EC86-23FEAA14660D bootID:6e05e906-0ca4-4ee3-927e-a36798084cb6 kernelVersion:3.16.0-0.bpo.4-amd64 osImage:Debian GNU/Linux 7 (wheezy) containerRuntimeVersion:docker://1.8.3 kubeletVersion:v1.2.0-alpha.2.626+8fc36e6068334a-dirty kubeProxyVersion:v1.2.0-alpha.2.626+8fc36e6068334a-dirty] capacity:map[cpu:2 memory:7679608Ki pods:40] conditions:[map[type:Ready status:True lastHeartbeatTime:2015-11-03T02:38:07Z lastTransitionTime:2015-11-03T00:39:31Z reason:KubeletReady message:kubelet is posting ready status] map[type:OutOfDisk status:False lastHeartbeatTime:2015-11-03T02:38:07Z lastTransitionTime:2015-11-03T00:39:31Z reason:KubeletHasSufficientDisk message:kubelet has sufficient disk space available]] addresses:[map[type:InternalIP address:10.240.0.11] map[type:ExternalIP address:104.197.106.102]] daemonEndpoints:map[kubeletEndpoint:map[Port:10250]]]] map[spec:map[podCIDR:10.244.2.0/24 externalID:14275614848584897735 providerID:gce://mikedanese-k8s/us-central1-b/k-5-minion-0jkl] status:map[daemonEndpoints:map[kubeletEndpoint:map[Port:10250]] nodeInfo:map[osImage:Debian GNU/Linux 7 (wheezy) containerRuntimeVersion:docker://1.8.3 kubeletVersion:v1.2.0-alpha.2.626+8fc36e6068334a-dirty kubeProxyVersion:v1.2.0-alpha.2.626+8fc36e6068334a-dirty machineID: systemUUID:0EAF030D-B18B-57C9-9616-4008F51DEAF4 bootID:84fbf71d-959d-46e5-8cd2-8a62859508c0 kernelVersion:3.16.0-0.bpo.4-amd64] capacity:map[cpu:2 memory:7679608Ki pods:40] conditions:[map[type:Ready status:True lastHeartbeatTime:2015-11-03T02:38:07Z lastTransitionTime:2015-11-03T00:40:52Z reason:KubeletReady message:kubelet is posting ready status] map[type:OutOfDisk status:False lastHeartbeatTime:2015-11-03T02:38:07Z lastTransitionTime:2015-11-03T00:40:15Z reason:KubeletHasSufficientDisk message:kubelet has sufficient disk space available]] addresses:[map[type:InternalIP address:10.240.0.32] map[address:130.211.149.36 type:ExternalIP]]] kind:Node apiVersion:v1 metadata:map[uid:73548e00-81c3-11e5-8109-42010af0000b resourceVersion:3019 creationTimestamp:2015-11-03T00:40:15Z labels:map[kubernetes.io/hostname:k-5-minion-0jkl] name:k-5-minion-0jkl selfLink:/api/v1/nodes/k-5-minion-0jkl]] map[kind:Node apiVersion:v1 metadata:map[name:k-5-minion-1mq6 selfLink:/api/v1/nodes/k-5-minion-1mq6 uid:6dfcefcc-81c3-11e5-8109-42010af0000b resourceVersion:3017 creationTimestamp:2015-11-03T00:40:06Z labels:map[kubernetes.io/hostname:k-5-minion-1mq6]] spec:map[podCIDR:10.244.1.0/24 externalID:2970383975702131324 providerID:gce://mikedanese-k8s/us-central1-b/k-5-minion-1mq6] status:map[conditions:[map[message:kubelet is posting ready status type:Ready status:True lastHeartbeatTime:2015-11-03T02:38:05Z lastTransitionTime:2015-11-03T00:40:42Z reason:KubeletReady] map[lastHeartbeatTime:2015-11-03T02:38:05Z lastTransitionTime:2015-11-03T00:40:06Z reason:KubeletHasSufficientDisk message:kubelet has sufficient disk space available type:OutOfDisk status:False]] addresses:[map[type:InternalIP address:10.240.0.31] map[type:ExternalIP address:108.59.86.162]] daemonEndpoints:map[kubeletEndpoint:map[Port:10250]] nodeInfo:map[kernelVersion:3.16.0-0.bpo.4-amd64 osImage:Debian GNU/Linux 7 (wheezy) containerRuntimeVersion:docker://1.8.3 kubeletVersion:v1.2.0-alpha.2.626+8fc36e6068334a-dirty kubeProxyVersion:v1.2.0-alpha.2.626+8fc36e6068334a-dirty machineID: systemUUID:B2C51EC4-7CB7-62DE-3005-40D3C3C4AA7E bootID:84635e0a-b6b8-4c85-b5aa-354b0f93a356] capacity:map[memory:7679608Ki pods:40 cpu:2]]] map[kind:Node apiVersion:v1 metadata:map[labels:map[kubernetes.io/hostname:k-5-minion-j8s2] name:k-5-minion-j8s2 selfLink:/api/v1/nodes/k-5-minion-j8s2 uid:74dff725-81c3-11e5-8109-42010af0000b resourceVersion:3016 creationTimestamp:2015-11-03T00:40:18Z] spec:map[providerID:gce://mikedanese-k8s/us-central1-b/k-5-minion-j8s2 podCIDR:10.244.3.0/24 externalID:15940688070743728911] status:map[daemonEndpoints:map[kubeletEndpoint:map[Port:10250]] nodeInfo:map[systemUUID:4FEBAB9C-F20C-1EAE-939D-7CF3E8A98E34 bootID:70059938-8e08-4202-a2c2-4b6658e0f88c kernelVersion:3.16.0-0.bpo.4-amd64 osImage:Debian GNU/Linux 7 (wheezy) containerRuntimeVersion:docker://1.8.3 kubeletVersion:v1.2.0-alpha.2.626+8fc36e6068334a-dirty kubeProxyVersion:v1.2.0-alpha.2.626+8fc36e6068334a-dirty machineID:] capacity:map[cpu:2 memory:7679608Ki pods:40] conditions:[map[message:kubelet is posting ready status type:Ready status:True lastHeartbeatTime:2015-11-03T02:38:02Z lastTransitionTime:2015-11-03T00:40:56Z reason:KubeletReady] map[lastHeartbeatTime:2015-11-03T02:38:02Z lastTransitionTime:2015-11-03T00:40:18Z reason:KubeletHasSufficientDisk message:kubelet has sufficient disk space available type:OutOfDisk status:False]] addresses:[map[type:InternalIP address:10.240.0.33] map[address:104.154.40.190 type:ExternalIP]]]]]

### PR DESCRIPTION
**Pull request by dims**
Fixes #16707

### CODE REVIEW

**Comment by lavalamp** [comment]
Please add a test. I will revisit when 1.3 is locked down.

**Comment by dims** [comment]
test this issue: #IGNORE

**Comment by mikkeloscar** [comment]
@dims Why was this abandoned?

**Comment by dims** [comment]
@mikkeloscar i should have left notes as i don't remember now :) Please feel free to do another PR with the code

**Comment by mikkeloscar** [comment]
Alright, I will look into it then. :)

**Pull request closed without merging**
