### PR TITLE
Automated cherry pick of #116749: Adding additional validations to queried endpoint

### PR DESCRIPTION
**Pull request by princepereira**
Cherry pick of #116749 on release-1.24.

#116749: Adding additional validations to queried endpoint

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
This PR adds additional validation for endpoint ip configuration while iterating through queried endpoint list.
```

### CODE REVIEW

**Comment by jsturtevant** [comment]
@sbangari for approval

**Comment by marosset** [comment]
@sbangari @MikeZappa87 for approval

**Comment by marosset** [comment]
1.24 is in maintenance mode now so I'm closing this
https://kubernetes.io/releases/patch-releases/#support-period
@princepereira @MikeZappa87 - FYI
/close

**Pull request closed without merging**
