### PR TITLE
Fix StatefulSet revision update with OnDelete strategy

### LINKED ISSUE #106055: StatefulSetStatus CurrentRevision doesn't update with OnDelete update strategy
### What happened?

This is the same as https://github.com/kubernetes/kubernetes/issues/73492

When using the OnDelete update strategy, after all the pods from the old revision are deleted the CurrentRevision doesn't get updated in the Status

### What did you expect to happen?

Once the old revision pods have all been deleted the CurrentRevision should be updated.

### How can we reproduce it (as minimally and precisely as possible)?

Create a statefulset with >1 replicas and OnDelete update strategy.  Make a change to the Spec, then delete all the current pods.

### Anything else we need to know?

I have reopened the issue so I can work on a fix for it

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:"2021-05-21T16:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

None

### OS version

_No response_

### Install tools

_No response_

### Container runtime (CRI) and and version (if applicable)

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by FillZpp**
Signed-off-by: Siyu Wang <FillZpp.pub@gmail.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Fix StatefulSet revision update with OnDelete strategy.

#### Which issue(s) this PR fixes:

Fixes #106055 

#### Does this PR introduce a user-facing change?

```release-note
Fix StatefulSet revision update with OnDelete strategy.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dbason** [comment]
https://github.com/kubernetes/kubernetes/pull/106059 is already open for this issue.  It covers some additional corner cases.

**Comment by FillZpp** [comment]
> #106059 is already open for this issue. It covers some additional corner cases.

OK, I didn't see it since the issue has no one assigned.

/close

**Pull request closed without merging**
