### PR TITLE
Update github.com/rackspace/gophercloud to HEAD

### PR DESCRIPTION
**Pull request by kazegusuri**
In openstack cloudprovider, access token will be expired in a day or some days after first auth. `AllowReauth` option to reauth is set [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/6c5b390160856cd8334043344ef6e08568b0a5c9/pkg/cloudprovider/openstack/openstack.go#L115), but it is not implemented in current synced version in gophercloud.  Current HEAD of gopherclouds supports automatic reauth when token is expired.

### CODE REVIEW

**Comment by kazegusuri** [comment]
I have checked it works in my OpenStack environment, but I'm not sure this effects other envs such as Rackspace.

**Comment by bgrant0607** [comment]
@doublerr Would you like to take a look?

**Comment by bgrant0607** [comment]
Well, since this is just a pure update, I'm going to merge.

**Comment by doublerr** [comment]
@bgrant0607 thanks for the heads up. We don't currently use the cloudprovider settings but should be soon.

**Pull request merged**
