### PR TITLE
Automated cherry pick of #38772

### PR DESCRIPTION
**Pull request by zmerlynn**
Cherry pick of #38772 on release-1.5, changing deprecation to 1.6.

#38772: AWS: Add a strong deprecation message

### CODE REVIEW

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Comment by zmerlynn** [comment]
@k8s-bot test this

@mwielgus: Please make sure this makes the 1.5.4 cut.

**Comment by zmerlynn** [comment]
@mwielgus: Nevermind, I see you just cut it. This was sitting for days in the [cherrypick queue](http://cherrypick.k8s.io/#/queue)

**Comment by mwielgus** [comment]
@zmerlynn - No - PR #42194 was not in the queue. The base one was. I guess this one wasn't marked as cherrypick and the queue didn't pick it up.  Anyway, the whole cp experience is broken but we are trying to improve it - see https://github.com/kubernetes/test-infra/issues/1795

**Comment by zmerlynn** [comment]
| @zmerlynn - No - PR #42194 was not in the queue. The base one was. I guess this one wasn't marked as cherrypick and the queue didn't pick it up.

The base being in queue in the "merged" section with "v1.5" is enough signal to know that you're expecting a cherry-pick, and it was visible on the PR.

**Comment by mwielgus** [comment]
Yes, maybe, but this should't work that way. The release owner should get a clear list of PRs that requires his approval and not wander through PRs content looking for something that he can actually approve.

Anyway, sorry for not including your PR in 1.5.4.

**Comment by justinsb** [comment]
@mwielgus can we get this into 1.5.8 ?  What is it missing?  I added cherrypick-candidate in case that is the missing label...

**Comment by marun** [comment]
I'm assuming since this is targeting the release-1.5 branch that it should be targeting the v1.5 milestone.

**Comment by mwielgus** [comment]
@k8s-bot test this please

**Pull request merged**
