### PR TITLE
DaemonSetSpec.Template should not be a pointer.

### PR DESCRIPTION
**Pull request by madhusudancs**
Pod template for DaemonSets isn't optional, like Deployments and Jobs, so the DaemonSetSpec.Template field should not be a pointer.

cc @mikedanese

### CODE REVIEW

**Comment by madhusudancs** [comment]
@bgrant0607 suggested that Template fields in Deployment and Job should be pointers, instead of making the Template field in DaemonSet a pointer, to be consistent with v1 API, eg. ReplicationController. He also said that the idea is to be able to add non-inlined templates in the future for which we need pointer template fields. 

I am closing this PR.

**Comment by mikedanese** [comment]
@bgrant0607 This advice seems to contradict your past recommendations.

https://github.com/kubernetes/kubernetes/pull/14079/files#r40389805

https://github.com/kubernetes/kubernetes/pull/16330#discussion_r43137804

**Comment by bgrant0607** [comment]
@mikedanese Clearly I don't care much. :-) Either way is acceptable, but consistency is more important than correctness. Let's make all the new APIs the same as each other at least. I delegate the decision to you.

**Comment by madhusudancs** [comment]
Reopening this PR due to the discussion above.

**Comment by madhusudancs** [comment]
@bgrant0607 @mikedanese PTAL.

**Comment by bgrant0607** [comment]
LGTM. Needs rebase.

**Comment by madhusudancs** [comment]
New push was just a rebase, adding the LGTM label back.

**Comment by madhusudancs** [comment]
@k8s-bot test this please.

**Comment by madhusudancs** [comment]
@k8s-bot test this please.

**Comment by soltysh** [comment]
Fixes https://github.com/kubernetes/kubernetes/issues/19859

**Pull request merged**
