### PR TITLE
Making DHCP_OPTION_SET_ID creation optional

### PR DESCRIPTION
**Pull request by j1n6**
Reason: We have a pre-configured VPC in AWS. `kube-up.sh` should not making changes to the VPC DHCP option if there's already DHCP options configured. 

PR Changes: When `DHCP_OPTION_SET_ID` is given in environment variable, kube-up.sh will skip the `DHCP_OPTION_SET_ID` creation.

### CODE REVIEW

**Comment by roberthbailey** [comment]
ok to test

**Comment by activars** [comment]
Any one can review this sooner?

**Comment by roberthbailey** [comment]
@activars sorry for the delay. This wasn't tagged with 1.3 so it wasn't at the top of my review list. This LGTM, but it won't be merged by the submit queue until the master branch is opened to non-1.3 changes.

**Comment by roberthbailey** [comment]
ok to test

**Comment by activars** [comment]
@roberthbailey Thanks. pls let me know if there are anything I need to do.

**Comment by roberthbailey** [comment]
Nope. This PR is just waiting for the master branch to exit the slush period around the 1.3 release and start accepting new PRs.

**Comment by roberthbailey** [comment]
ok to test

**Pull request merged**
