### PR TITLE
Calling 'vagrant up' directly is not supported.  Instead, please run the...

### PR DESCRIPTION
**Pull request by marctrem**
... following:

  export KUBERNETES_PROVIDER=vagrant
  ./cluster/kube-up.sh

### CODE REVIEW

**Comment by alex-mohr** [comment]
@derekwaynecarr please take a look as part of vagrant?  (and thanks for claiming stewardship!)

**Comment by derekwaynecarr** [comment]
No problem.  I have some other pressing Kube issues but hope to get any vagrant items resolved by early next week.

**Comment by satnam6502** [comment]
What's the status of this PR?

**Comment by brendandburns** [comment]
This seems totally reasonable.  @derekwaynecarr any objections to merging?

**Comment by derekwaynecarr** [comment]
LGTM. Sorry had fell off my radar.  Thanks for fix to doc.

**Pull request merged**
