### PR TITLE
Automated cherry pick of #107406: fix: delete non existing disk issue

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #107406 on release-1.21.

#107406: fix: delete non existing disk issue

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Review by andrewsykim — COMMENTED** [review]
/approve

ack'ing that this is a bug fix

**Comment by ialidzhikov** [comment]
/cc @nilo19 @feiskyer 
as this PR is still missing /lgtm

**Comment by bridgetkromhout** [comment]
/cc kubernetes/release-managers

This was already merged into 1.22, 1.23, and 1.24.

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
