### PR TITLE
WIP: [scheduler_perf]: consume metrics and render graphs

### PR DESCRIPTION
**Pull request by ingvagabund**
**What type of PR is this?**

NOT MEANT TO BE MERGED AS IT IS!!!

This is an example of how to directly consume metrics from the kube-scheduler
Metrics are consumed through `legacyregistry.DefaultGatherer.Gather()` from
`k8s.io/component-base/metrics/legacyregistry` package.

Also, the commit carries a set of graphs showing pod scheduled duration
progress of pods as they went through the scheduler. X axis is the time
elapsed, each point on the X axis corresponds to a single pod. Y axis
denotes the time it took to schedule a pod from the time the scheduler
started to process it for the first time until it was bound (including
retries).

Progress of scheduling of 5000 pods over 1000 nodes:
alt text

The same data, just rendered from scheduler's `pod_scheduling_duration_seconds` metrics:
alt text

The same data, just rendered from scheduler's `pod_scheduling_duration_seconds` metrics with smaller exponential buckets ( (0.001, 1.2, 65) configuration):
alt text

All the data were collected by running the following commands over this PR:
```
$ cd test/integration/scheduler_perf
$ time go test -run TestBenchmarkScheduling$ -logtostderr=true 2>&1 | tee scheduler.logs
# generate dataset and gnuplot scripts in the current directory
$ cat scheduler.logs | python parse_scheduler_logs.py
# generate graphs in png format
$ gnuplot *.g
```

Conclusion: TBD

/kind design

**What this PR does / why we need it**:
TBD

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liu-cong** [comment]
cc

**Comment by ingvagabund** [comment]
Based on the dataItem file generated in the clusterloader tests and unified metrics, I got this (you can ignore the preemption as there was nothing to preempt):
```json
[{"data":{"Perc50":0.617283,"Perc90":1.75,"Perc99":3},"unit":"ms","labels":{"Metric":"scheduler_scheduling_algorithm_predicate_evaluation_seconds","Name":"100Nodes_0ExistingPods_100Pods"}},{"data":{"Perc50":1.65909,"Perc90":4.888888,"Perc99":7.111111},"unit":"ms","labels":{"Metric":"scheduler_scheduling_algorithm_priority_evaluation_seconds","Name":"100Nodes_0ExistingPods_100Pods"}},{"data":{"Perc50":-9223372036854.775,"Perc90":-9223372036854.775,"Perc99":-9223372036854.775},"unit":"ms","labels":{"Metric":"scheduler_scheduling_algorithm_preemption_evaluation_seconds","Name":"100Nodes_0ExistingPods_100Pods"}},{"data":{"Perc50":10.75,"Perc90":31.2,"Perc99":50.285714},"unit":"ms","labels":{"Metric":"scheduler_binding_duration_seconds","Name":"100Nodes_0ExistingPods_100Pods"}},{"data":{"Perc50":0.641025,"Perc90":1.923076,"Perc99":3.6},"unit":"ms","labels":{"Metric":"scheduler_scheduling_algorithm_predicate_evaluation_seconds","Name":"100Nodes_100ExistingPods_100Pods"}},{"data":{"Perc50":1.790123,"Perc90":7,"Perc99":10.666666},"unit":"ms","labels":{"Metric":"scheduler_scheduling_algorithm_priority_evaluation_seconds","Name":"100Nodes_100ExistingPods_100Pods"}},{"data":{"Perc50":-9223372036854.775,"Perc90":-9223372036854.775,"Perc99":-9223372036854.775},"unit":"ms","labels":{"Metric":"scheduler_scheduling_algorithm_preemption_evaluation_seconds","Name":"100Nodes_100ExistingPods_100Pods"}},{"data":{"Perc50":9.507246,"Perc90":30.222222,"Perc99":49.230769},"unit":"ms","labels":{"Metric":"scheduler_binding_duration_seconds","Name":"100Nodes_100ExistingPods_100Pods"}},{"data":{"Perc50":1.36565,"Perc90":4.095238,"Perc99":6.47619},"unit":"ms","labels":{"Metric":"scheduler_scheduling_algorithm_predicate_evaluation_seconds","Name":"1000Nodes_0ExistingPods_1000Pods"}},{"data":{"Perc50":4.880636,"Perc90":12.988235,"Perc99":15.341176},"unit":"ms","labels":{"Metric":"scheduler_scheduling_algorithm_priority_evaluation_seconds","Name":"1000Nodes_0ExistingPods_1000Pods"}},{"data":{"Perc50":-9223372036854.775,"Perc90":-9223372036854.775,"Perc99":-9223372036854.775},"unit":"ms","labels":{"Metric":"scheduler_scheduling_algorithm_preemption_evaluation_seconds","Name":"1000Nodes_0ExistingPods_1000Pods"}},{"data":{"Perc50":6.325301,"Perc90":19.142857,"Perc99":36.705882},"unit":"ms","labels":{"Metric":"scheduler_binding_duration_seconds","Name":"1000Nodes_0ExistingPods_1000Pods"}},{"data":{"Perc50":1.786628,"Perc90":6.199261,"Perc99":7.675276},"unit":"ms","labels":{"Metric":"scheduler_scheduling_algorithm_predicate_evaluation_seconds","Name":"1000Nodes_1000ExistingPods_1000Pods"}},{"data":{"Perc50":6.614097,"Perc90":14.766169,"Perc99":17.4},"unit":"ms","labels":{"Metric":"scheduler_scheduling_algorithm_priority_evaluation_seconds","Name":"1000Nodes_1000ExistingPods_1000Pods"}},{"data":{"Perc50":-9223372036854.775,"Perc90":-9223372036854.775,"Perc99":-9223372036854.775},"unit":"ms","labels":{"Metric":"scheduler_scheduling_algorithm_preemption_evaluation_seconds","Name":"1000Nodes_1000ExistingPods_1000Pods"}},{"data":{"Perc50":7.779141,"Perc90":23.523809,"Perc99":37.028571},"unit":"ms","labels":{"Metric":"scheduler_binding_duration_seconds","Name":"1000Nodes_1000ExistingPods_1000Pods"}},{"data":{"Perc50":1.858466,"Perc90":7.053164,"Perc99":9.923664},"unit":"ms","labels":{"Metric":"scheduler_scheduling_algorithm_predicate_evaluation_seconds","Name":"1000Nodes_0ExistingPods_5000Pods"}},{"data":{"Perc50":8.019704,"Perc90":15.901477,"Perc99":25.448818},"unit":"ms","labels":{"Metric":"scheduler_scheduling_algorithm_priority_evaluation_seconds","Name":"1000Nodes_0ExistingPods_5000Pods"}},{"data":{"Perc50":-9223372036854.775,"Perc90":-9223372036854.775,"Perc99":-9223372036854.775},"unit":"ms","labels":{"Metric":"scheduler_scheduling_algorithm_preemption_evaluation_seconds","Name":"1000Nodes_0ExistingPods_5000Pods"}},{"data":{"Perc50":9.031556,"Perc90":26.587064,"Perc99":40.921212},"unit":"ms","labels":{"Metric":"scheduler_binding_duration_seconds","Name":"1000Nodes_0ExistingPods_5000Pods"}},{"data":{"Perc50":1.506823,"Perc90":5.732959,"Perc99":7.600373},"unit":"ms","labels":{"Metric":"scheduler_scheduling_algorithm_predicate_evaluation_seconds","Name":"1000Nodes_5000ExistingPods_5000Pods"}},{"data":{"Perc50":7.105685,"Perc90":15.818446,"Perc99":25.149051},"unit":"ms","labels":{"Metric":"scheduler_scheduling_algorithm_priority_evaluation_seconds","Name":"1000Nodes_5000ExistingPods_5000Pods"}},{"data":{"Perc50":-9223372036854.775,"Perc90":-9223372036854.775,"Perc99":-9223372036854.775},"unit":"ms","labels":{"Metric":"scheduler_scheduling_algorithm_preemption_evaluation_seconds","Name":"1000Nodes_5000ExistingPods_5000Pods"}},{"data":{"Perc50":6.341669,"Perc90":19.132686,"Perc99":32.354243},"unit":"ms","labels":{"Metric":"scheduler_binding_duration_seconds","Name":"1000Nodes_5000ExistingPods_5000Pods"}}]
```

**Comment by fedebongio** [comment]
Not clear what to do with this one or if it belongs to API Machinery. Please ping us again when is not WIP anymore. Thanks.

**Comment by ingvagabund** [comment]
> Not clear what to do with this one or if it belongs to API Machinery. Please ping us again when is not WIP anymore. Thanks.

@fedebongio definitely not api-machinery related. The PR carries another PR for api-machinery that needs to be merged separately.

**Comment by ingvagabund** [comment]
On the way to find out which scheduling pieces tends to randomize the scheduling throughput per a unit of time I am plotting relation between number of pods to be scheduled (the triangular part) and the predicates/priorities evaluation time.

alt text

Data from 15 runs of the scheduler over 20k pods and 600 nodes, snapshot period 250ms. The lowest accumulation of curved lines corresponds to predicates evaluation time. The accumulation of curved lines in the middle corresponds to priorities evaluation time. The remaining (triangular like) lines corresponds to a number pods not yet scheduled (multiplied by 0.01 for transparency).

The graph clearly shows peaks and fluctuations of predicates/priorities evaluation time until the number of pods to be scheduled reaches it's maximum. After that the evaluation time of both predicates and priorities tends to be almost constant.

**Comment by ingvagabund** [comment]
Even after rebooting my system (12GB, 4CPUs) multiple times with just a terminal (nothing else running besides GUI), I get the following scheduling throughputs:

Right after 1. reboot
- Average:254.79738562091504, Perc50:248, Perc90:364, Perc99:440
- Average:256.91089108910893, Perc50:244, Perc90:372, Perc99:452}
- Average:251.3548387096774, Perc50:244, Perc90:360, Perc99:420}
- Average:256.17105263157896, Perc50:244, Perc90:368, Perc99:424}
- Average:256.91089108910893, Perc50:248, Perc90:364, Perc99:448}

Right after 2. reboot
- Average:215.90027700831024, Perc50:204, Perc90:316, Perc99:424}
- Average:214.56749311294766, Perc50:208, Perc90:316, Perc99:384}
- Average:216.81337047353762, Perc50:204, Perc90:320, Perc99:392}
- Average:215.74515235457065, Perc50:208, Perc90:320, Perc99:368}
- Average:215.97783933518005, Perc50:204, Perc90:316, Perc99:432}
- Average:215.33701657458565, Perc50:208, Perc90:320, Perc99:396}

Right after 3. reboot
- Average:223.46131805157594, Perc50:212, Perc90:328, Perc99:400}
- Average:225.13294797687863, Perc50:212, Perc90:328, Perc99:400}
- Average:223.17478510028653, Perc50:212, Perc90:328, Perc99:396}

Right after 4. reboot
- Average:228.60997067448682, Perc50:216, Perc90:336, Perc99:432}
- Average:227.14619883040936, Perc50:216, Perc90:336, Perc99:436}
- Average:228.25806451612902, Perc50:216, Perc90:332, Perc99:424}
- Average:229.21176470588236, Perc50:220, Perc90:336, Perc99:444}

Right after 5. reboot
- Average:221.14772727272728, Perc50:212, Perc90:336, Perc99:392}
- Average:223.12893982808023, Perc50:212, Perc90:332, Perc99:408}
- Average:219.48169014084507, Perc50:212, Perc90:324, Perc99:388}
- Average:223.79310344827587, Perc50:212, Perc90:332, Perc99:416}
- Average:221.53846153846155, Perc50:212, Perc90:324, Perc99:400}
- Average:221.5954415954416, Perc50:216, Perc90:320, Perc99:384}

**Pull request closed without merging**
