### PR TITLE
Fixed #25858 Limit elasticsearch memory usage for fielddata to avoid `too large Data exception`

### LINKED ISSUE #25858: Data too large, data for [kubernetes.container_name] would be larger than limit of [633785548/604.4mb]]
When I do aggs on container_name, I will get the following errors:  

```
Elasticsearch INFO: 2016-05-19T01:50:57Z
  Adding connection to https://ginger-seer-3740-cluster.caicloudapp.com/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging

Elasticsearch DEBUG: 2016-05-19T01:50:57Z
  starting request { method: 'POST',
    path: '/_search',
    body:
     { query: { filtered: [Object] },
       aggs: { group_by_containername: [Object] },
       sort: { container_name: [Object] } },
    query: { size: 20 } }


Elasticsearch TRACE: 2016-05-19T01:51:20Z
  -> POST https://ginger-seer-3740-cluster.caicloudapp.com:443/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging/_search?size=20
  {
    "query": {
      "filtered": {
        "query": {
          "bool": {
            "should": [],
            "must_not": [],
            "must": [
              {
                "wildcard": {
                  "namespace_name": "monitor"
                }
              },
              {
                "wildcard": {
                  "pod_name": "monitor-3524605461-lttdi"
                }
              }
            ]
          }
        },
        "filter": {
          "range": {
            "@timestamp": {
              "gte": "2016-05-15",
              "lte": "2016-05-15"
            }
          }
        }
      }
    },
    "aggs": {
      "group_by_containername": {
        "terms": {
          "field": "container_name"
        }
      }
    },
    "sort": {
      "container_name": {
        "order": "asc"
      }
    }
  }
  <- 200
  {
    "took": 22603,
    "timed_out": false,
    "_shards": {
      "total": 35,
      "successful": 30,
      "failed": 1,
      "failures": [
        {
          "index": "logstash-2016.05.18",
          "shard": 4,
          "status": 500,
          "reason": "RemoteTransportException[[Curtis Connors][inet[/172.16.56.3:9300]][indices:data/read/search[phase/query]]]; nested: ElasticsearchException[org.elasticsearch.common.breaker.CircuitBreakingException: [FIELDDATA] Data too large, data for [kubernetes.container_name] would be larger than limit of [633785548/604.4mb]]; nested: UncheckedExecutionException[org.elasticsearch.common.breaker.CircuitBreakingException: [FIELDDATA] Data too large, data for [kubernetes.container_name] would be larger than limit of [633785548/604.4mb]]; nested: CircuitBreakingException[[FIELDDATA] Data too large, data for [kubernetes.container_name] would be larger than limit of [633785548/604.4mb]]; "
        }
      ]
    },
    "hits": {
      "total": 0,
      "max_score": null,
      "hits": []
    },
    "aggregations": {
      "group_by_containername": {
        "doc_count_error_upper_bound": 0,
        "sum_other_doc_count": 0,
        "buckets": []
      }
    }
  }
```

Then I get the FieldData from indices stats:  

```
"logstash-2016.05.15":{
  "primaries":{
    "fielddata":{
      "memory_size_in_bytes":5115824,
      "evictions":0,
      "fields":{
        "kubernetes.namespace_name":{"memory_size_in_bytes":170256},
        "kubernetes.container_name":{"memory_size_in_bytes":1099640},
        "kubernetes.pod_name":{"memory_size_in_bytes":1105424},
        "@timestamp":{"memory_size_in_bytes":2740504}
      }
    }
  },
  "total":{
    "fielddata":{
      "memory_size_in_bytes":10154292,
      "evictions":0,
      "fields":{
        "kubernetes.namespace_name":{"memory_size_in_bytes":252316},
        "kubernetes.container_name":{"memory_size_in_bytes":2202608},
        "kubernetes.pod_name":{"memory_size_in_bytes":2215040},
        "@timestamp":{"memory_size_in_bytes":5484328}
      }
    }
  }
}
```

Actually, **evictions is 0**.  
And then, I get some useful informations from elasticsearch home page:  

```
Setting                              Description  
indices.fielddata.cache.size         The max size of the field data cache, eg 30% of node heap space, or an absolute value, eg 12GB. Defaults to unbounded.  
indices.breaker.total.limit          Starting limit for overall parent breaker, defaults to 70% of JVM heap
indices.breaker.fielddata.limit      Limit for fielddata breaker, defaults to 60% of JVM heap
indices.breaker.request.limit        Limit for request breaker, defaults to 40% of JVM heap
```

The indices.fielddata.cache.size controls how much heap space is allocated to fielddata. As you are issuing queries, aggregations on analyzed strings will load into fielddata if the field wasn’t previously loaded. If the resulting fielddata size would exceed the specified size, other values will be evicted in order to make space.  
**By default, this setting is unbounded—Elasticsearch will never evict data from fielddata.**  
That's the point, The too large Data exception is due to the default value of fielddata.cache unbounded resulting in.  
While you can still run queries that access fielddata from the old indices, you can’t load any new values. Instead, we should evict old values to make space for the new values.  
To prevent this scenario, place an upper limit on the fielddata by adding this setting to the config/elasticsearch.yml file:   

```
indices.fielddata.cache.size:  20%
```

References:
[https://www.elastic.co/guide/en/elasticsearch/guide/current/_limiting_memory_usage.html](https://www.elastic.co/guide/en/elasticsearch/guide/current/_limiting_memory_usage.html)
[https://www.elastic.co/guide/en/elasticsearch/guide/1.x/_limiting_memory_usage.html](https://www.elastic.co/guide/en/elasticsearch/guide/1.x/_limiting_memory_usage.html)

### PR DESCRIPTION
**Pull request by keontang**
Fixes #25858

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/25859)

### CODE REVIEW

**Comment by mikedanese** [comment]
This is a hard one for me to understand without context. @a-robinson @jimmidyson would you like to take a look at this one?

**Comment by a-robinson** [comment]
@jimmidyson, feel comfortable approving this? I haven't done the legwork necessary to understand everything involved here, but can if you aren't very familiar with it either.

**Comment by jimmidyson** [comment]
From the [docs](https://www.elastic.co/guide/en/elasticsearch/guide/current/_limiting_memory_usage.html#fielddata-size):

> This setting is a safeguard, not a solution for insufficient memory.
>
> If you don’t have enough memory to keep your fielddata resident in memory, Elasticsearch will constantly have to reload data from disk, and evict other data to make space. Evictions cause heavy disk I/O and generate a large amount of garbage in memory, which must be garbage collected later on.

While I feel this setting is worth having to prevent unbounded growth, I'm not sure how to gauge what the value should be. Clusters with differing numbers of pods, logs & queries will require a different value for this to perform adequately.

@keontang How did you arrive at 20%? Are you running with this value? With what size cluster & log volume?

**Comment by keontang** [comment]
@jimmidyson , yes, you said it that clusters with differing numbers of pods, logs & queries will require a different value for this to perform adequately.  
At the very beginning, I ran the k8s cluster in my three vm machines(only 1g memory & 1cpu), so I need to set `indices.fielddata.cache.size` to 20%.  
Now, I have two cluster of physical machines(8G memory & 20G disk) to run. One has 6 machines, and the other has 3 machines. And my default configuration of `fielddata.cache.size` is 40%. Everything is running ok for two weeks.  
I run es cluster with two pods:
```
kube-system   elasticsearch-logging-v1-e6tw0                            1/1       Running   0          7d
kube-system   elasticsearch-logging-v1-qn9fa                            1/1       Running   0          19d
kube-system   fluentd-elasticsearch-i-7c1e9ojm                          1/1       Running   0          66d
kube-system   fluentd-elasticsearch-i-ijxxxm8i                          1/1       Running   1          5d
kube-system   fluentd-elasticsearch-i-wx80nuri                          1/1       Running   0          66d
```

So I think 40% is more generic.

**Comment by jfrazelle** [comment]
can you make the title of the pull request more descriptive as to what it is actually fixing

**Comment by keontang** [comment]
@jfrazelle 
Done

**Comment by keontang** [comment]
Anybody PTAL？

**Comment by keontang** [comment]
signed linuxfoundation cla

**Comment by keontang** [comment]
signed linuxfoundation cla

**Pull request closed without merging**
