### PR TITLE
Amendments to SELinux enhancement proposal

### PR DESCRIPTION
**Pull request by pmorie**
Makes some changes to the proposal from #33951 based on some further research.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35127)

### CODE REVIEW

**Comment by yifan-gu** [comment]
@pmorie Sorry, was pulled into other works yesterday.

My question was when is `Getfilecon()` supposed to be called by rkt?

/cc @euank @lucab @s-urbaniak

**Comment by pmorie** [comment]
@yifan-gu `Getfilecon` is already called in `rkt.go`

**Comment by yifan-gu** [comment]
LGTM

**Comment by eparis** [comment]
@k8s-bot test this

**Comment by euank** [comment]
LGTM as well. We should maybe reconsider our use of `Getfilecon` in rkt.go, but that's a separate issue

**Pull request merged**
