### PR TITLE
kubeadm: handle dry run GET actions from fake discovery

### LINKED ISSUE #2796: fix failing dryrun e2e job
some of our recent changes broke the dryrun e2e

https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-dryrun-latest

tip: to see what commits was it one can click a red box and drag to a green box. i am currently on mobile and can't do that.

we should try to fix this before xmas and not having any failing tests during the holidays...preferably since folks are not around.

@pacoxu @SataQiu @chendave

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

The kubeadm dry run client reactor code is flawed as it assumes all invoked "get" verb actions can be casted to GetAction. Apparently that is not the case when Discovery().ServerVersion() and other discovery calls are made. In such cases the action type is the bare ActionImpl.

Catch if an action can be casted to ActionImpl and construct a GetAction from it. GetActionImpl only supersets ActionImpl with a Name field (empty string in this case).

Add unit test for Discovery().ServerVersion().

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/2796

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pacoxu — COMMENTED** [review]
/lgtm

**Comment by neolit123** [comment]
/test pull-kubernetes-unit
failures seem unrelated

**Comment by pacoxu** [comment]
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-dryrun-latest/1605538614094073856/build-log.txt

still failed https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-dryrun-latest.

It should include this PR.

**Comment by neolit123** [comment]
occasionally there is a problem where the latest-x.xx.txt version markers return an older ci version. kinder's jobs depend on these job markers to pull artifacts from the ci buckets. so i think this is the problem.

**Comment by pacoxu** [comment]
> edit: all recent runs are against v1.27.0-alpha.0.562+55181b72a2c0aa which i think does not have the patch.

If I remember correctly, we have a similar issue before and it is finally solved after the ci is using the correct build.
- 55181b72a2c0aa is a commit early yesterday before this PR is merged.

**Pull request merged**
