### PR TITLE
clientgo/examples/in-cluster: add instructions to run the example

### PR DESCRIPTION
**Pull request by ahmetb**
This patch adds instructions for how to run the in-cluster client-go example.
To make this example executable, providing a Dockerfile and build steps so
that it can directly be run on minikube.

This is part of the body of work improving the client library samples.

Signed-off-by: Ahmet Alp Balkan <ahmetb@google.com>

### CODE REVIEW

**Comment by ahmetb** [comment]
[this](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46133/pull-kubernetes-federation-e2e-gce/5740/) is likely a flake:
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by ahmetb** [comment]
[more flake](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46133/pull-kubernetes-federation-e2e-gce/5754/).
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by sttts** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by ahmetb** [comment]
@k8s-bot kops aws e2e test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by ahmetb** [comment]
hmm the test failures do not appear to be related to the example, but are consistent:

@k8s-bot kops aws e2e test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by ahmetb** [comment]
@sttts I think I need help diagnosing why am I keep getting the same set of test failures, which seems like they are not relevant to this patch. I appreciate any inputs.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46133/pull-kubernetes-federation-e2e-gce/6064/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46133/pull-kubernetes-e2e-kops-aws/26160/

**Pull request merged**
