### PR TITLE
Remove manual conversions for ListOptions

### PR DESCRIPTION
**Pull request by wojtek-t**
Manual conversions for ListOptions wasn't copying the `AllowWatchBookmark` fields (and thus the feature doesn't work without this change).

Ref #73585
Ref https://github.com/kubernetes/enhancements/issues/956

```release-note
Fix a bug that ListOptions.AllowWatchBookmarks wasn't propagating correctly in kube-apiserver.
```

### CODE REVIEW

**Comment by liggitt** [comment]
based on the auto-generated function, I don't see any reason for a manually written one. do we know why it was introduced in the first place?

**Comment by liggitt** [comment]
/lgtm
/approve

/hold
I don't see any issues with this, but would like to know what the reason for it being added was, to make sure we don't introduce any issues

**Comment by wojtek-t** [comment]
@liggitt - it was created by @smarterclayton in https://github.com/kubernetes/kubernetes/pull/40178
It was part of moving ListOptions to meta api group - my guess would be that there wasn't any bigger thought behind by, but we can wait for @smarterclayton - to confirm?

**Comment by smarterclayton** [comment]
I think this is just historical.  At the time the generators didn't work for internal versions outside of k8s.io/kubernetes I believe.

/lgtm
/hold cancel

**Comment by smarterclayton** [comment]
/hold

I want to verify that Convert is called.

**Comment by smarterclayton** [comment]
Yeah, this was a bug in the generator before.

/hold cancel
/lgtm

**Pull request merged**
