### PR TITLE
Skip monitoring e2e tests until new Heapster release

### PR DESCRIPTION
**Pull request by mwielgus**
With 0.19.1 Influxdb problems should be fixed.

### CODE REVIEW

**Comment by gmarek** [comment]
LGTM

**Comment by wojtek-t** [comment]
Why not move it to flaky - then it will be running, and we will be able to detect more regressions...

**Comment by mwielgus** [comment]
Marked as flaky.

**Comment by wojtek-t** [comment]
LGTM (I didn't know that we finally changed it to be handled in test names).

**Comment by wojtek-t** [comment]
Thanks!

**Pull request merged**
