### PR TITLE
Godep: Add godep for rkt.

### PR DESCRIPTION
**Pull request by yifan-gu**
rkt: v0.5.4
appc spec: v0.5.1

### CODE REVIEW

**Comment by yifan-gu** [comment]
@dchen1107 @vmarmol @bakins

**Comment by dchen1107** [comment]
LGTM on this Godep and will merge it once it is green.

**Comment by yifan-gu** [comment]
Thank you!

**Comment by pmorie** [comment]
Kicked shippable

**Comment by yifan-gu** [comment]
@pmorie Thank you!

**Comment by pmorie** [comment]
Yet another shippable flake, kicked again :footprints:

**Comment by vmarmol** [comment]
Travis is green, LGTM. Merging!

**Comment by erictune** [comment]
So, for docker, we vendor client libraries, but for rkt, we vendor the entire rkt implementation?  And we plan to compile all of rkt into Kubelet?

Just thinking through what this means. 
  - Upgrading kubelet upgrades rkt support as well. 
  - how do we start kubelet in a container without a separate rkt binary?  With `--run_once`? 
  - how is the rkt version reported, compared to how docker version is reported?

**Comment by vmarmol** [comment]
@erictune this is a bit misleading, we still use the `rkt` binary for most operations. We are importing the client libraries and APIs around it. Today, it is a bit of an ugly hybrid. With time I think we will move fully to a client.

**Comment by pmorie** [comment]
@vmarmol, this threw me too and was why I was asking if we were embedding
rocket the other day.

**Comment by erictune** [comment]
Is this just vendoring the client?  That is a lot of files.  Or is it
vendoring all of rkt?  Is there a way to vendor just the client?

**Comment by yifan-gu** [comment]
@erictune That's because now we exposed the internal storage type of rkt to get the image manifest. I think we will fix it when rkt binary provides a way to retrieve the image manifest. All the rkt package should be removed. Only appc/spec is necessary.

**Comment by erictune** [comment]
Okay, as long as you have a plan :-)

**Pull request merged**
