### PR TITLE
Poll for stats until Windows kubelet present it in the stats endpoint

### LINKED ISSUE #115932: [Flaky] HostProcess containers container stats validation
### Which jobs are flaking?

ci-kubernetes-e2e-capz-master-containerd-windows

### Which tests are flaking?

Kubernetes e2e suite: [It] [sig-windows] [Feature:WindowsHostProcessContainers] [MinimumKubeletVersion:1.22] HostProcess containers container stats validation 

### Since when has it been flaking?

feb 8th 2023

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1627766458253578240

### Reason for failure (if possible)

reading of the log is showing reporting zero

### Anything else we need to know?

It looks like the pod had started up just as it check the failure on the test. Adding a retry or a longer wait might make the test more reliable

### Relevant SIG(s)

/sig windows

### PR DESCRIPTION
**Pull request by knabben**
#### What type of PR is this?
/kind flake
/kind failing-test
/sig windows

#### What this PR does / why we need it:
Polling the Kubelet stats endpoint until a CPU/Mem value appears for the pod, or fail close.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/115932

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by knabben** [comment]
cc @jsturtevant

**Review by jsturtevant — COMMENTED** [review]
lgtm generally, one minor suggest for readability. Due to the infrequency of this flake, we will have to merge and monitor.

**Pull request merged**
