### PR TITLE
Document that kubectl commands shouldn't have aliases

### PR DESCRIPTION
**Pull request by janetkuo**
## Pull Request Guidelines
1. Please read our [contributor guidelines](https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md).
2. See our [developer guide](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md).
3. Follow the instructions for [labeling and writing a release note for this PR](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/pull-requests.md#release-notes) in the block below.

``` release-note
* Use the release-note-* labels to set the release note state 
* Clear this block to use the PR title as the release note 
-OR-
* Enter your extended release note here
```

Ref https://github.com/kubernetes/kubernetes/issues/25180#issuecomment-217453402 @kubernetes/kubectl 

[Analytics]()

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM, thanks.

**Comment by janetkuo** [comment]
Running `hack/update-generated-docs.sh`

**Comment by kargakis** [comment]
@fabianofranz fyi

**Comment by fabianofranz** [comment]
LGTM

**Pull request merged**
