### PR TITLE
Clean validation_test go file

### PR DESCRIPTION
**Pull request by NickrenREN**
When i wrote test cases for feature gate of local storage quota, found some unused vars and useless code, remove them

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
LGTM, but needs rebase

**Comment by NickrenREN** [comment]
Thanks @liggitt  done.

**Comment by NickrenREN** [comment]
@liggitt  It seems bot does not response to your comment

**Comment by sttts** [comment]
Manually applied labels. Strange that the bot ignored the commands.

**Comment by NickrenREN** [comment]
Thanks @sttts

**Pull request merged**
