### PR TITLE
support kubectl replace configmap with --from-file and --from-literal

### PR DESCRIPTION
**Pull request by mengqiy**
Split PR #32429 into several small ones for easier review.
Partial: #30558.  Will open another PR for `kubectl replace secret` soon.

Support update `kubectl replace configmap` with `--from-file` and `--from-literal`
Behavior:
`--force` is false: reuse the old object and just replace the data field.
`--force` is true: delete the old object if it exist; ignore the 'not found' error otherwise. Then create a new object using generator. This usage is related to #30337

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33335)

### CODE REVIEW

**Comment by ymqytw** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/kubectl/cmd/get_test.go, line 93 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33335#-KSIubeJavbJxvwHR58-:-KSIubeJavbJxvwHR580:b-fwpyt3) ([raw file](https://github.com/kubernetes/kubernetes/blob/2eb5baa1580a007b56f12c9f16af09bdd178fdb2/pkg/kubectl/cmd/get_test.go#L93)):*
> ```Go
> }
> 
> func genTestData() (*api.ConfigMapList, *api.SecretList) {
> ```

This function will also be used by the unit test for updating secret.

---

*[pkg/kubectl/cmd/replace.go, line 47 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33335#-KSIuDSPH7cFYYdlw7D-:-KSIuDSPH7cFYYdlw7D0:bc41o32) ([raw file](https://github.com/kubernetes/kubernetes/blob/2eb5baa1580a007b56f12c9f16af09bdd178fdb2/pkg/kubectl/cmd/replace.go#L47)):*
> ```Go
> 	Resource string
> 	// Subtype of the resource (optional)
> 	Subtype string
> ```

Subtype is not used in updating configmap, but will be used in updating secret.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33335)*

**Comment by ymqytw** [comment]
SGTM. I will hold until everyone is happy with this first replace subcommand.

**Comment by ymqytw** [comment]
@liggitt Ping

**Comment by liggitt** [comment]
I don't think we really want parallel suites of `kubectl create <foo>` and `kubectl replace <foo>` commands.

A standard way to take the output of `create foo` and apply it to an existing object seems better to me. That is already sort of possible with `kubectl create ... --dry-run -o yaml | kubectl apply`. Is there a way to clean up that interaction instead of creating a completely new command that just composes those two things?

@kubernetes/sig-cli @kubernetes/rh-ux

**Comment by ymqytw** [comment]
> That is already sort of possible with kubectl create ... --dry-run -o yaml | kubectl apply.

I think it should be `kubectl create ... --dry-run -o yaml | kubectl replace -f -`, since apply uses PATCH while replace uses PUT.

**Comment by fruch** [comment]
Any news on this one ? I'm looking for something like that

**Comment by ymqytw** [comment]
Does `kubectl create -f config.yaml --dry-run -o yaml | kubectl replace -f -` work for you?

**Comment by fruch** [comment]
I'll try, does it update the related pods ?

**Comment by ymqytw** [comment]
@fruch Yes, it will.

**Comment by jonathan-kosgei** [comment]
@mengqiy @fruch is `kubectl create -f config.yaml --dry-run -o yaml | kubectl replace -f -` the supported method to update a configmap?

**Comment by mengqiy** [comment]
@jonathan-kosgei Yes

**Comment by xeor** [comment]
Will that be the `official` way? This is one of the things I imagined finding in the `--help`. Finding the solution to something that should be a `--force` away, in a github issue is kinda weird..

**Comment by jeremyd** [comment]
kubectl replace configmap react-config --from-file=$envfile --namespace=mynamespace

```
Error: unknown flag: --from-file
```

There seem to be a lot of closed bugs on this, but it doesn't look like the functionality fully made it?  Is it possible to update from a file now?

**Comment by mengqiy** [comment]
--from-file is not supported now.

It seems there are a lot of people request this feature.
I will try to implement this by reuse some code that already exist or find someone to do this.

**Pull request closed without merging**
