### PR TITLE
Fix issue #3090 - update systemd unit files

### PR DESCRIPTION
**Pull request by timothysc**
Currently the systemd files reference /etc/kubernetes, given that all
the files are environment override variables they belong in sysconfig
per distribution spec:

http://fedoraproject.org/wiki/Packaging:
Systemd#EnvironmentFiles_and_support_for_.2Fetc.2Fsysconfig_files

Also, root group promotion is required in systemd for the kubelet, lest
it will be given default priority = to all other services.

### CODE REVIEW

**Comment by timothysc** [comment]
@nhorman that is no different then several other tools, including Docker, which also use sysconfig.

**Comment by nhorman** [comment]
@timothysc your point being?  The fact that other tools do the same thing that kubernetes does doesn't make that thing right.  Its fine to do, but no mater how many other tools do it, as the number of configuration points increases, it becomes unruly.  Command lines become too complex to administer without configuration files, and configuration files start to become to complex for a linear configuration, not to mention the potential exhaustion of environment space.

**Comment by bgrant0607** [comment]
Is this PR still active?

**Comment by eparis** [comment]
This PR did two things, and we only talked about one of them.  It moved the config files.  I don't like that.

It also created some cgroup/resource lines in kubelet.  I'd like a PR to discuss those separately. Can those be exposed as config variables somehow?  Maybe not.... 

I'd like to see this closed and a new PR openned. although @timothysc may disagree.

**Comment by erictune** [comment]
ping @timothysc to close PR or state plan for it

**Pull request closed without merging**
