### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
Fix a typo

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by cblecker** [comment]
I don't know that this is a typo. It's just a contraction missing the apostrophe.

**Comment by zhangxiaoyu-zidif** [comment]
@cblecker so what‘s your suggestion. Keep it or modify “its” to “it’s”

**Comment by davidopp** [comment]
@k8s-bot ok to test

**Comment by zhangxiaoyu-zidif** [comment]
@davidopp could you help solve the question of failed tests? Thanks very much.

**Comment by cblecker** [comment]
@k8s-bot kops aws e2e test this
@k8s-bot non-cri e2e test this

**Pull request merged**
