### PR TITLE
Default value of min and max shouldn't be negative.

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Found below logs in https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/55574/pull-kubernetes-unit/64695/. It's confusing.
```
error: --max=MAXPODS is required and must be at least 1, max: -1
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
/assign @adohe @fabianofranz
for approval :)

**Comment by fabianofranz** [comment]
@janetkuo WDYT?

**Review by janetkuo — CHANGES_REQUESTED** [review]
`-1` was chosen intentionally, which means the field is unset.  `--max` is a required field, and we don't want to set it for users.  

If it's confusing, would it be better if we remove `, max: -1`?
```
error: --max=MAXPODS is required and must be at least 1
```

In general, changing default values can be breaking. Such change needs more discussions and definitely needs a release note.

**Comment by xiangpengzhao** [comment]
>If it's confusing, would it be better if we remove , max: -1?

Then we should remove the value output in the error info of both L191 and L194. I'm not sure if users want to know from the error info what value they configure (or what the default value is if they don't configure).

Since this is just a trivial UX issue, maybe we can leave the code as-is.

https://github.com/kubernetes/kubernetes/blob/2a70dc8746a4f3f4e3cddcd64cff79fde8aeae85/pkg/kubectl/cmd/autoscale.go#L187-L197

**Comment by janetkuo** [comment]
I'm fine with either not printing the value of max/min flag or leaving the code as-is.

**Comment by xiangpengzhao** [comment]
/close
leaving the code as-is as it provides more info (a bit confusing in the default case though)

**Pull request closed without merging**
