### PR TITLE
Add netbase package to gci mounter container image

### PR DESCRIPTION
**Pull request by vishh**
cc @rootfs @jingxu97

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35819)

### CODE REVIEW

**Comment by rootfs** [comment]
LGTM

**Comment by jingxu97** [comment]
LGTM

**Comment by jingxu97** [comment]
Just one question, is ubuntu:xenial a good choice for our case mounter image? Why this is missing the netbase package?

**Comment by vishh** [comment]
I don't have a base image preference. The examples for NFS I found online
were using ubuntu and so I went with it.

**Comment by jingxu97** [comment]
Bump to priority P0 because it is related to production issue and this change is required for testing

**Pull request merged**
