### PR TITLE
fix some typos

### PR DESCRIPTION
**Pull request by SataQiu**
**What this PR does / why we need it**:
Fix some typos about api

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
/kind cleanup
/ok-to-test

it would be much better to combine more typo fixes in single PRs.

**Comment by logicalhan** [comment]
Hi @SataQiu, I appreciate the PR but the double 'thats' in these comments seem grammatically correct to me. I believe that the first 'that' indicates a subordinate clause while the second 'that' is demonstrative and refers to the 'having made the format difficult to use'.

**Comment by SataQiu** [comment]
@neolit123 Thank you for reminding me.  I will pay attention to that.

**Comment by SataQiu** [comment]
@logicalhan Maybe you are right. Thank you.

**Pull request closed without merging**
