### PR TITLE
Add logging loader to confirm regression in log throughput

### PR DESCRIPTION
**Pull request by serathius**
/wg structured-logging
/cc @pohly

### CODE REVIEW

**Review by pohly — COMMENTED** [review]
This benchmark is clearly useful, but it could be better. Ideally we should have one "go test -bench=." invocation that needs to be run before and after making logging changes. The PR with those changes then needs to contain the benchstat comparison between the before and after state. Let me try to integrate this into https://github.com/kubernetes/kubernetes/pull/106594

Shall we merge this PR anyway or do you want to wait?


Even better of course would be automation and a failed pre-pull test. Not sure whether that is realistic and it probably shouldn't be informative, not blocking.

**Comment by pohly** [comment]
On my machine I get for the current PR (commit 42927438012c62bcd7cc72b6b2174feba9726cf3):

```
$ go run ./staging/src/k8s.io/component-base/logs/loader/cmd/logger.go 1>/tmp/stdout.out 2>/tmp/stderr.out && du /tmp/*.out
404044	/tmp/stderr.out
0	/tmp/stdout.out
```

When I rebase it on top of master with the regression fix, I get:

```
$ go run ./staging/src/k8s.io/component-base/logs/loader/cmd/logger.go 1>/tmp/stdout.out 2>/tmp/stderr.out && du /tmp/*.out
431992	/tmp/stderr.out
0	/tmp/stdout.out
```

In other words, there isn't a lot of difference. That mirrors my experience with integrating this benchmark into "go test -bench" style, see https://github.com/kubernetes/kubernetes/pull/106594#issuecomment-995907067

@serathius: is your /tmp perhaps on some actual filesystem? Which one, which hardware? In my case, /tmp is a tmpfs.

**Comment by serathius** [comment]
> @serathius: is your /tmp perhaps on some actual filesystem? Which one, which hardware? In my case, /tmp is a tmpfs.

Yes, you're right on my machine /tmp is not tmpfs. I also seen the same case that problem is not noticeable when writing to memory. On my first try I run
```
go run ./staging/src/k8s.io/component-base/logs/loader/cmd/logger.go 2>&1 | pv
```
which didn't show the problem.

Please replace /tmp/ with some disk backed directory.

**Comment by pohly** [comment]
> Please replace /tmp/ with some disk backed directory.

I switched to NVMe disk. There I see a difference:
```
$ go run ./staging/src/k8s.io/component-base/logs/loader/cmd/logger.go --logging-format=json 1>stdout.out 2>stderr.out && du *.out
338896	stderr.out
0	stdout.out
```

```
$ go run ./staging/src/k8s.io/component-base/logs/loader/cmd/logger.go --logging-format=json 1>stdout.out 2>stderr.out && du *.out
0	stderr.out
239032	stdout.out
```

**Comment by dims** [comment]
@serathius @pohly do we want to land this in 1.24?

**Comment by serathius** [comment]
I think this code was incorporated in benchmark code. @pohly  Can you confirm before closing the PR?

**Comment by pohly** [comment]
Correct, PR #106594 was extended to cover a similar scenario in a more automated way (`go test -bench` instead of manually running the command here and comparing output. However, I still have open questions for you in that PR around modeling disk performance and the PR itself still needs to be merged.

Let's close this one here once PR #106594 is done and merged.

**Pull request closed without merging**
