### PR TITLE
CSI is GA in k8s v1.13

### PR DESCRIPTION
**Pull request by yuansmin**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
according to [k8s docs](https://kubernetes.io/docs/concepts/storage/volumes/#out-of-tree-volume-plugins), CSI is GA in k8s v1.13

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by lavalamp** [comment]
This is a generated file, please fix the original source (will be in a types.go file somewhere). Changing just this file won't (shouldn't) pass tests:

/ok-to-test

**Comment by yuansmin** [comment]
> This is a generated file, please fix the original source (will be in a types.go file somewhere). Changing just this file won't (shouldn't) pass tests:
> 

updated, I found it in staging directory

**Comment by yuansmin** [comment]
hi @lavalamp , the tests is ok, could you please review this pr again?

**Comment by lavalamp** [comment]
apologies for the delay.

**Pull request closed without merging**
