### PR TITLE
Parameters are not used

### PR DESCRIPTION
**Pull request by Pingan2017**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE

### CODE REVIEW

**Comment by Pingan2017** [comment]
update release node

**Comment by xiangpengzhao** [comment]
/assign @saad-ali 
for approval. Thanks!

**Comment by xiangpengzhao** [comment]
`pull-kubernetes-verify` failed due to gofmt. But seems like the existing importing sequence is correct. I don't know why gofmt suggest the below way.

@ixdy any thoughts?

```
I0812 17:43:27.057] Verifying hack/make-rules/../../hack/verify-gofmt.sh
I0812 17:43:39.583] diff ./pkg/util/goroutinemap/goroutinemap.go gofmt/./pkg/util/goroutinemap/goroutinemap.go
I0812 17:43:39.583] --- /tmp/gofmt006364707	2017-08-12 17:43:36.590990360 +0000
I0812 17:43:39.583] +++ /tmp/gofmt586539302	2017-08-12 17:43:36.590990360 +0000
I0812 17:43:39.584] @@ -23,10 +23,10 @@
I0812 17:43:39.584]  
I0812 17:43:39.584]  import (
I0812 17:43:39.584]  	"fmt"
I0812 17:43:39.584] -	"sync"
I0812 17:43:39.584]  	"github.com/golang/glog"
I0812 17:43:39.585]  	k8sRuntime "k8s.io/apimachinery/pkg/util/runtime"
I0812 17:43:39.585]  	"k8s.io/kubernetes/pkg/util/goroutinemap/exponentialbackoff"
I0812 17:43:39.585] +	"sync"
I0812 17:43:39.585]  )
I0812 17:43:39.585]  
I0812 17:43:39.585]  // GoRoutineMap defines a type that can run named goroutines and track their
I0812 17:43:39.586] FAILED   hack/make-rules/../../hack/verify-gofmt.sh	12s
```

**Comment by cblecker** [comment]
The line break was removed, so gofmt is alpha sorting the list.

**Comment by xiangpengzhao** [comment]
@cblecker I see. Thanks!
@Pingan2017 please keep the empty line after `"time"`

**Comment by xiangpengzhao** [comment]
/lgtm

ping @saad-ali for approval :)

**Comment by Pingan2017** [comment]
PTAL @xiangpengzhao @saad-ali ,Thank you!
I just combine the two commits.

**Comment by xiangpengzhao** [comment]
/lgtm

Since @saad-ali is the only approver in pkg/util/goroutinemap/OWNERS, we should wait until his response :)

**Pull request closed without merging**
