### PR TITLE
Move Prober to its own subpackage

### PR DESCRIPTION
**Pull request by vmarmol**
/cc @yujuhong @dchen1107 @yifan-gu

### CODE REVIEW

**Comment by yifan-gu** [comment]
LGTM! Thanks! @vmarmol

**Comment by yujuhong** [comment]
LGTM overall, just one question: do we create a separate `types` package just because the network plugin needs to know the docker id?

**Comment by vmarmol** [comment]
@yujuhong yes. Long term we should move the network package away from that type and onto something more generic.

**Comment by yujuhong** [comment]
Will merge on green but shippable and travis are taking forever to run.

**Comment by yujuhong** [comment]
travis passed. I am going to merge this one since the other PR is still queued up.

**Pull request merged**
