### PR TITLE
Revert "Revert the workaround needed to cleanup for Ginkgo V1"

### PR DESCRIPTION
**Pull request by aojea**
/kind flake

```release-note
NONE
```

The storage tests are still using the custom logic for Cleanups on the e2e framework

```
grep -r AddCleanupAction test/e2e
test/e2e/framework/cleanup.go:// AddCleanupAction installs a function that will be called in the event of the
test/e2e/framework/cleanup.go:func AddCleanupAction(fn func()) CleanupActionHandle {
test/e2e/framework/cleanup.go:// AddCleanupAction.
test/e2e/framework/cleanup.go:// RunCleanupActions runs all functions installed by AddCleanupAction.  It does
test/e2e/storage/drivers/csi.go:        *cleanupHandle = framework.AddCleanupAction(cleanupFunc)
test/e2e/storage/vsphere/vsphere_scale.go:      framework.AddCleanupAction(func() {
test/e2e/storage/vsphere/vsphere_volume_diskformat.go:  framework.AddCleanupAction(func() {
test/e2e/storage/vsphere/persistent_volumes-vsphere.go: framework.AddCleanupAction(func() {
test/e2e/storage/vsphere/vsphere_volume_placement.go:   framework.AddCleanupAction(func() {
test/e2e/storage/flexvolume_mounted_volume_resize.go:   framework.AddCleanupAction(func() {
test/e2e/storage/flexvolume_online_resize.go:   framework.AddCleanupAction(func() {
test/e2e/storage/mounted_volume_resize.go:      framework.AddCleanupAction(func() {
```

if we remove the `RemoveCleanupAction` from the `func (f *Framework) AfterEach() {`  they will run again in `SynchronizedAfterSuite`

We partially reverted some of this logic here https://github.com/kubernetes/kubernetes/pull/111063, as a consequence we have the e2e framework in an inconsistent state, that makes very complicate to debug issues

### CODE REVIEW

**Comment by aojea** [comment]
/assign @chendave 

we should do the change clean, partial reverts are complicated

/priority critical-urgent

**Comment by chendave** [comment]
> if we remove the RemoveCleanupAction from the func (f *Framework) AfterEach() { they will run again in SynchronizedAfterSuite

sorry, I don't understand this. `RemoveCleanupAction` just remove the action that was added by `AddCleanupAction`, what's the problem here?

**Comment by chendave** [comment]
check it again, I cannot find any issue with that pr, but if revert that one will be helpful for debugging, I am fine with the revert here too.

**Comment by aojea** [comment]
> check it again, I cannot find any issue with that pr, but if revert that one will be helpful for debugging, I am fine with the revert here too.

@chendave the partial reverts removes the `RemoveCleanupAction()` hook from `func (f *Framework) AfterEach()`.

The storage tests add the Cleanup hooks with `AddCleanupAction` , however, since this change, those hooks are not going to be removed on AfterEach anymore, that means that they will run again on `SynchronizedAfterSuite`.

Anyway, the e2e is very fragile with a lot of tech debt, the CI is being flaky for several weeks since the ginkgo v2 update, and we should try to do changes incrementally and only after we are sure everything is stable, or is very hard to identify the root cause of the problems.

**Comment by aojea** [comment]
image

image

**Pull request merged**
