### PR TITLE
Break up Go e2e tests into files and convert basic.sh

### PR DESCRIPTION
**Pull request by satnam6502**
This PR add a Go version of the `basic.sh` end-to-end test. The test here is much more comprehensive and checks for the error result code of every operation and it verifies that each pod returns the correct hostname in response to a HTTP GET. The `TestBasic` function is made more robust by checking for any replication controllers lying around from a previous aborted run (these are deleted). It also cleans up after itself by resizing the replication controller to zero (to get rid of the pods) and then deleting the replication controller. This allows the test to be run repeatedly against a cluster without tearing it down and bringing it up again.

I have also disabled node level and cluster level logging for GCE end-to-end tests. This setup significantly slows down cluster creation which slows down all our e2e tests for no good reason (although we should think about e2e tests for logging and monitoring -- but perhaps they can be handled separately).

Not deleting `basic.sh` yet because it is used by some other tests. Will remove when the other tests have been ported over.

As a minor fix (that makes no difference really) I fixed the pod specification for the env var test to use the correct container port.

@lavalamp @zmerlynn @filbranden

### CODE REVIEW

**Comment by brendandburns** [comment]
Please don't add another test to the monolithic e2e.go, monolithic tests are really hard to debug, and don't play nice with the GUI integrations we have set up in Jenkins.

Please port this code out either to it's own go file, or add a flag to just run this one test, and wrap that in the basic.sh file.

I think we need to stick to a one-test per run policy, so that our log files, reporting, etc. are sane.

**Comment by satnam6502** [comment]
OK. I took advice on how to add this Go test and it was suggested that the best thing to do right now was to add to e2e.go -- but yes -- agree -- it would be better to factor this out into its own unit and make a library out of the helper functions.

**Comment by zmerlynn** [comment]
I've been considering a way that hack/e2e.go could actually probe subtests
in cmd/e2e and run them separately so they're not monolithic, but one
problem is actually that the cmd/e2e  runner has an obnoxious timeout that,
when triggered, can leave the system all but unusable for further e2es. :/

**Comment by lavalamp** [comment]
I think this is the right place for this test, and that this file needs to be broken up into multiple files and made into a proper framework.

We should fix the obnoxious timeout.

**Comment by satnam6502** [comment]
I would prefer a setup in which the e2e tests are imported imported from a regular Go package rather than being separate binaries that are execed. Breaking the file file into parts that make up a package seems like the right way to go. I will do that for my test, and if/when that merges I could do a PR which does the same thing for the other tests. I will also add a flag to allow the conditional execution of each test.

**Comment by zmerlynn** [comment]
Clearly we should use the old argv[0] trick and just hardlink this binary
to each of its tests.

**Comment by satnam6502** [comment]
Using `argv[0]` is causing problems in `hack/e2e.go` because this program may executed by `go run` which means `aegv[0]` is actually a location somewhere in `\tmp` and the current setup only works by accident (due to a series of bugs that cancel each other out if you execute from the kubernetes root directory but executing from the `hack` directory does not work).

**Comment by zmerlynn** [comment]
Sorry, I should've put a <sarcasm> tag on there.

We should also figure out how to add auto-discovery to hack/e2e.go if we go
down this path, though, because I don't want the barrier to people adding
new tests to be too high (i.e. they shouldn't have to add it in 3 places)

**Comment by satnam6502** [comment]
I've only had three cups of tea this morning so I am in the early stages of my bootstrap process. Apologies.

**Comment by satnam6502** [comment]
Proposal:
* Don't have e2e tests in `cmd/e2/...`. The tests should be under a well name directory like `testing` (rather than `hack`).
* Adding a test for feature `wombat` involves addding a file `testing/wombat.go` which is in the `e2e` package with a top level function `TestWomat` and then updating the `testing/e2e.go` file which contain the main program which imports the `testing` package.

Then to add a test someone needs to write one file and make an easy modification to another file both of which are in the same directory.

**Comment by zmerlynn** [comment]
Just to flesh out my "crazy" thought if we wanted to leave the monolithic
binary in place.

In hack/e2e.go, we add "subtest" discovery: For every shell script, we run
"foo.sh --list". If it returns a non-0 exit code, we assume stdout is a
list of tests where we can then do "foo.sh test1".

Then we in cmd/e2e, we have to add a "--list" option that does test
discovery. We also in the other .sh scripts, add "--list" options that just
bail.

I think this can be made to play nicely with the TAP output in hack/e2e.go,
etc. It does take us down a rabbit hole of cobbling together more framework
of our own, though, and I was somewhat resistant because .. surely
someone's done this stuff for us.

**Comment by satnam6502** [comment]
What's the issue with a monolithic e2e test **binary**? I can see that we don't want a monolithic source file.

**Comment by zmerlynn** [comment]
Oh, I don't see anything wrong with the test binary being monolithic.

**Comment by zmerlynn** [comment]
Well. Sorry. My coffee isn't kicking in, either.

The problem with the monolithic binary is that right now the thing that
runs it the most is actually Jenkins, via hack/e2e.go, which is really
running it via the shell script. As long as the tests can be discovered and
run separately via those means, we're fine.

**Comment by satnam6502** [comment]
We could make a special in `hack/e2e.go` which instead of conditionally running `hack/goe2e.sh` instead has a separate code path which runs a top level test driver from the package `cmd/e2e/e2e.go` and this driver could be given the value of the `--tests` flag to allow conditional execution of the Go e2e tests. So the `hack/e2e` could be run with `--test="basic integration.sh` which works by checking each item to see if it is a named in the table for Go e2e tests (including matching for `*`) -- otherwise look for a file as is currently done. That would be a minimal change to the current framework to allow conditional execution of Go e2e tests.

**Comment by satnam6502** [comment]
I assume all of this is a stepping stone towards to point where we have no bash e2e tests? Am I right in assuming we want to port **all** of the e2e bash scripts to Go?

**Comment by filbranden** [comment]
+1 to porting all the e2e bash scripts to Go.

Also agree that it should be a single Go binary running all the tests. By default it would run all of them in sequence (or in parallel) but we should be able to request a single test to be run with command line parameters (e.g. `-t <testname>` or similar).

I also think eventually we should integrate kube-up/kube-down to it and cloud provider support as well, it should all be Go and none of it be shell scripts... At that point, we should be able to handle a test failure by recreating the cluster or we could implement a "janitor" that would "repair" a cluster making sure it's in a sane state after a test failure.

Does that make sense?

I'm assigning this one to me but please keep the comments coming.

**Comment by satnam6502** [comment]
@filbranden : as for reviewing this PR, please can you hold off while I re-work the PR in light of the comments here. I propose first I re-work this PR to put put `TestBasic` into a separate file. Once that merges I propose to write another PR which re-organizes the Go e2e tests to support conditional execution of tests.

**Comment by filbranden** [comment]
Sure, I'll hold until you upload a new commit with the comments here.

Agreed on next step allowing conditional execution of Go tests.

Cheers,
Filipe

**Comment by zmerlynn** [comment]
hack/e2e.go already has up/down built in and could act as janitor, as you
suggest. It doesn't take as hard a line on test failure today, but that
wouldn't be hard to add to the existing framework that's already there,
versus recreating a new one in cmd/e2e. In addition, hack/e2e.go has an
added goal of being runnable just about anywhere (it uses no non-standard
deps), so it's basically just a script.

**Comment by zmerlynn** [comment]
Also, when the e2e test stops going through the non-canonical way to create
clusters, i.e. if it stops calling kube-up.sh, is when Jenkins stops using
it for cluster creation as well. We have to test the binary release and
standard cluster creation, though doing cluster janitorial stuff after that
is fine. So in general, the hack/e2e.go method is great for this today, and
replumbing it seems unnecessary.

If you're unfamiliar with what Jenkins is doing, I just checked in the
Jenkins scripts so it was more obvious to people how things were getting
called there:
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/hack/jenkins

**Comment by satnam6502** [comment]
hack/e2e.go is not runnable from anywhere and does not even run from the directory that our documentation says it can be run from (`hack`). I plan to fix this bug.

**Comment by satnam6502** [comment]
@filbranden @lavalamp @zmerlynn @roberthbailey and others might want to take note of the change I am proposing to the e2e tests here. This is what I had to do to conform to "put the basic Go test in a separate file". I decided I should also break up all the other tests, I added these e2e tests to the package test/e2e (and relocated them) and made cmd/e2e.go be a simple top level for these tests -- currently driven by test/e2e/driver.go -- but in a subsequent PR we should directly drive these tests from hack/e2e.go by import test/e2e

PTAL

**Comment by zmerlynn** [comment]
I added a script to imitate the Jenkins style binary test process: `hack/e2e-from-release.sh`. It builds a full release and then runs tests on the tar distribution alone. Can you verify this runs cleanly there? (Also, it looks like you need to rebase.)

**Comment by satnam6502** [comment]
Attempted to rebase...

**Comment by satnam6502** [comment]
@filbranden @zmerlynn rebased and green.

**Comment by satnam6502** [comment]
FWIW, sample output for the basic.sh test I converted to Go.
```
I0114 23:27:36.956254   22948 driver.go:83] Running test 8 TestBasic
I0114 23:27:37.110567   22948 basic.go:97] Replica 1: facca972-9c87-11e4-bdc2-42010af03b47
I0114 23:27:37.110596   22948 basic.go:97] Replica 2: facd1258-9c87-11e4-bdc2-42010af03b47
I0114 23:27:42.158533   22948 util.go:52] Waiting for pod facca972-9c87-11e4-bdc2-42010af03b47 status to be "Running" (found "Unknown")
I0114 23:27:47.202148   22948 util.go:52] Waiting for pod facca972-9c87-11e4-bdc2-42010af03b47 status to be "Running" (found "Unknown")
I0114 23:27:52.246249   22948 util.go:52] Waiting for pod facca972-9c87-11e4-bdc2-42010af03b47 status to be "Running" (found "Unknown")
I0114 23:27:57.291857   22948 util.go:52] Waiting for pod facca972-9c87-11e4-bdc2-42010af03b47 status to be "Running" (found "Unknown")
I0114 23:28:02.336155   22948 util.go:52] Waiting for pod facca972-9c87-11e4-bdc2-42010af03b47 status to be "Running" (found "Unknown")
I0114 23:28:12.477425   22948 basic.go:115] Pod facca972-9c87-11e4-bdc2-42010af03b47 hostIP 146.148.44.81
I0114 23:28:12.555074   22948 basic.go:137] Got expected result from replica 1:  facca972-9c87-11e4-bdc2-42010af03b47
I0114 23:28:12.555114   22948 basic.go:115] Pod facd1258-9c87-11e4-bdc2-42010af03b47 hostIP 146.148.56.56
I0114 23:28:12.633173   22948 basic.go:137] Got expected result from replica 2: facd1258-9c87-11e4-bdc2-42010af03b47
I0114 23:28:12.756136   22948 driver.go:89]         test 8 passed
```

**Comment by filbranden** [comment]
Looks OK.

I'd prefer if the split of e2e.go into multiple files and the conversion of basic.sh into Go were in two separate commits (even if the two commits go with the same PR) but that's probably minor...

I'd use underscores (or dashes) to separate the parts in the file names since otherwise it's fairly hard to read a test name such as "kubeletsendsevents" or "podhasserviceenvvars", did you have a good reason not to use underscores (or dashes) to separate the elements?

Otherwise I'd say good to go. @zmerlynn do you agree?

**Comment by zmerlynn** [comment]
LGTM. I'll admit to somewhat rubber stamp scanning that the existing tests
were the same (and would have also preferred a break up commit then the
functional change), but doing it after the fact is frankly painful.

**Comment by satnam6502** [comment]
@zmerlynn : yes, apologies. I had originally intended this PR to add TestBasic to cmd/e2e/e2e.go but when Brendan spoke up against a monolithic source file it led to a series of decisions which ended up conflating the split into a package with the conversion of a test.

**Comment by filbranden** [comment]
Thanks for renaming the *.go files! Looks great, merging it now.

**Comment by zmerlynn** [comment]
Er, dumb question... why did basic.sh itself stay around? :) Just watched the e2e run and was surprised to see it still there. Forgot to scan for the deletion.

**Comment by satnam6502** [comment]
`basic.sh` is used by some other tests like `private.sh`. Once they are ported to Go then they can all be removed. Sorry: I meant to explain this in this thread!

**Pull request merged**
