### PR TITLE
Add sts alias for kubectl statefulset

### PR DESCRIPTION
**Pull request by justinsb**
Saves a lot of typing!

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37099)

### CODE REVIEW

**Comment by justinsb** [comment]
ping @AdoHe

**Comment by AdoHe** [comment]
@justinsb sorry about just notice it now, could you please rebase this?

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc fyi

**Comment by AdoHe** [comment]
@justinsb please rebase this, then I will apply label.

**Comment by smarterclayton** [comment]
This is an API change and has been discussed before - we should make sure previous comments are taken into account.  Adding no not merge until then.

**Comment by justinsb** [comment]
Link to previous discussion @smarterclayton ?  Link to this being an API?

**Comment by smarterclayton** [comment]
Once we add a shortcut name to the CLI we can't remove it without a lengthy
deprecation process.  So like command names it follows longer rules for
introduction and change.

The original petset cli issue on May 16, 2016
<https://github.com/kubernetes/kubernetes/pull/25646#issuecomment-219387596>
tried
to add "ps" but that was denied, and in retrospect was correct.

Now that we're settled on a final stateful set name (helpfully), the only
issue is whether ss is confusing or not to a casual user or to an advanced
user.  Once the shortcut is added, we will support it for a very long time.

**Comment by smarterclayton** [comment]
"Follows API rules".

It looks like we don't have a good overall description in a single doc on
what is considered an API.  I'll add it to my list to fill that out so I
have a definitive link to post in the future.

**Comment by justinsb** [comment]
OK, thanks @smarterclayton.  I did find this policy: https://kubernetes.io/docs/deprecation-policy/ (section "Deprecating a flag or CLI").  We certainly haven't followed that policy, though we certainly should; and the deprecation period is very short (as I understand we could introduce it in 1.6, mark it deprecated in 1.7 and remove it in 1.8).  Though there is no indication that a beta status of a feature implies the beta status of features relating to that feature (and it would seem that this would be unfeasible), so we could also introduce the alias as alpha and change it at will.  But I think more renames are the last thing anyone needs at this point.

Closing as this PR is unlikely to be a source of joy for anyone.

**Comment by smarterclayton** [comment]
No I think stateful sets are going to deserve a shortcut - I just wanted to ensure we treated it with gravity!

**Comment by AdoHe** [comment]
LGTM. @justinsb I am sorry please rebase this and then I will apply the label.

**Comment by smarterclayton** [comment]
@kubernetes/sig-cli-api-reviews can all the SIG CLI maintainers weigh in on whether the API change to add "ss" as the shortcut makes sense and is what they would expect?  Any disagreement or objections?

**Comment by kargakis** [comment]
I don't feel strong about it but then again I can't think of something better.

**Comment by AdoHe** [comment]
@pwittrock @fabianofranz ptal.

**Comment by idvoretskyi** [comment]
I would avoid having this alias naming as it is ambiguous and non-polite for many people - [SS](https://en.wikipedia.org/wiki/Schutzstaffel).

**Comment by soltysh** [comment]
👍 to what Ihor mentioned, I'd personally propose something along `sset` instead.

**Comment by smarterclayton** [comment]
sset is fairly unintuitive, unfortunately.  It also is hard to say out loud.

**Comment by idvoretskyi** [comment]
@smarterclayton not sure that shouting "SS!" will be much better.

**Comment by kargakis** [comment]
How about state, stset, sts

Unless we believe StatefulSets can rewrite world history (which I do!) :)

**Comment by smarterclayton** [comment]
I'm not advocating for 'ss', just that the alias needs to be easy to type
and should be fairly intuitive for an end user to communicate about.  sts
isn't terrible.

On Mon, Feb 13, 2017 at 11:20 AM, Michail Kargakis <notifications@github.com

**Comment by k8s-mirror-cli-api-reviews** [comment]
Agree, "sts" is a good one.

**Comment by gyliu513** [comment]
Related to #42129

**Comment by kargakis** [comment]
Let's move forward with this one. Is everybody agreeing with `sts`?

@kubernetes/sig-cli-api-reviews @kubernetes/api-reviewers

**Comment by adohe** [comment]
`sts` sounds good to me. @justinsb could you please rebase this? Time for us to move forward. :)

**Comment by fabianofranz** [comment]
> Is everybody agreeing with sts?

Works for me.

**Comment by smarterclayton** [comment]
From an API review perspective `sts` sounds acceptable.  We are unlikely to add SpaceTransportSystem in the near future.

**Comment by adohe** [comment]
@justinsb kindly ping.

**Comment by justinsb** [comment]
Updated to use sts - I agree we need to move on.

**Comment by kow3ns** [comment]
@foxish

**Comment by foxish** [comment]
/lgtm cancel
I think we shouldn't be changing kubectl.
These short names moved into the discovery API in https://github.com/kubernetes/kubernetes/pull/41343, so we should use that. cc @deads2k

**Comment by deads2k** [comment]
> /lgtm cancel
> I think we shouldn't be changing kubectl.
> These short names moved into the discovery API in #41343, so we should use that. cc @deads2k

I agree.  I think we should be trying to limit special cases.  You can add the shortName to discovery using  a mechanism like this: https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/autoscaling/horizontalpodautoscaler/storage/storage.go#L63-L66

**Comment by fabianofranz** [comment]
@foxish @deads2k Are we still covered for `kubectl` [version skew](https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md#principles) in case of changing it server-side only?

**Comment by deads2k** [comment]
> @foxish @deads2k Are we still covered for kubectl version skew in case of changing it server-side only?

I think so.  Any `kubectl` 1.6 or later respects the shortNames from the server.  This just appears like a new resource alias for any other type we'd want to add.  If you switch to a server which doesn't have the shortName, you can't reference it that way just like you couldn't use a resource that wasn't there.

As we move more functionality server-side, the version of your client matters less than the version of your server.

**Comment by justinsb** [comment]
Done the new way in #45595

**Comment by foxish** [comment]
We could add a comment here to the kubectl code pointing to the new way of adding short names. I think that might be useful for folks trying to do this in future.

**Comment by kargakis** [comment]
> We could add a comment here to the kubectl code pointing to the new way of adding short names. I think that might be useful for folks trying to do this in future.

Yes, a comment and a link to this issue would be nice.

**Comment by kargakis** [comment]
Superseded by #45595

@justinsb if you plan to address https://github.com/kubernetes/kubernetes/pull/37099#issuecomment-300514824, please reopen.

**Pull request closed without merging**
