### PR TITLE
Update UI redirect to kube-system.

### LINKED ISSUE #9356: Don't show cluster addons by default
We've discussed using labels or even namespaces so that cluster addons don't show up in kubectl output by default. Users appear confused by this when they get pods, rcs, services.

Addons are labeled, so this filtering should be possible.

### PR DESCRIPTION
**Pull request by bgrant0607**
Fixes #9356.

### CODE REVIEW

**Comment by bgrant0607** [comment]
cc @zmerlynn

**Comment by zmerlynn** [comment]
LGTM. Still haven't cut. :)

**Comment by bgrant0607** [comment]
cc @lavalamp for ok-to-merge

**Comment by lavalamp** [comment]
OK to merge

**Comment by zmerlynn** [comment]
Cc @yujuhong for merge

**Pull request merged**
