### PR TITLE
Automated cherry pick of #39342 #39074 #38196

### PR DESCRIPTION
**Pull request by ixdy**
Cherry pick of #39342 #39074 #38196 on release-1.3.

#39342: Update boilerplate.py to support 2017
#39074: Support set user with `--ssh-user` flag when running remote
#38196: fix mesos unit tests

### CODE REVIEW

**Comment by krzyzacy** [comment]
There's no running 1.3-node test, but this won't hurt.

**Comment by ixdy** [comment]
@krzyzacy we're still running node e2e tests for PRs. https://github.com/kubernetes/kubernetes/pull/39707 failed because of it.

**Comment by fabioy** [comment]
Eek, must we pick up all the copyright year changes as well?

**Comment by krzyzacy** [comment]
@ixdy ah... forgot about that part :-p

**Comment by ixdy** [comment]
@fabioy yep, because dumb. https://github.com/kubernetes/kubernetes/pull/39342#issuecomment-269938039 (and see where it recently failed on 1.3 here: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/39707/pull-kubernetes-verify/12024/)

**Comment by ixdy** [comment]
oh, we need #38196 for the mesos unit test. I will add it...

**Comment by ixdy** [comment]
yay, all build pass. can I get an LG?

**Pull request merged**
