### PR TITLE
Update vendor package github.com/vmware/govmomi

### PR DESCRIPTION
**Pull request by fdawg4l**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

Part of #69776 involves updating github.com/vmware/govmomi

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fdawg4l** [comment]
cc @dougm @frapposelli

**Review by dougm — COMMENTED** [review]
/ok-to-test

**Comment by cblecker** [comment]
Thanks for this PR. It didn't pass tests, and we're revisiting how we are handling dep bumps (see #69776)

Going to close this one out..
/close

**Pull request closed without merging**
