### PR TITLE
[cluster/centos] fix https

### PR DESCRIPTION
**Pull request by zouyee**
**What this PR does / why we need it**:
[cluster/centos] fix https
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```NONE
```

### CODE REVIEW

**Comment by roberthbailey** [comment]
Did you test this? With other SSL configs for etcd there is also some plumbing added to do cert checking. 

Also, it seems weird that etcd is exposed on a non-localhost address on the master IP, but if that's the centos config then this change doesn't make it any worse.

**Comment by zouyee** [comment]
HI, @roberthbailey , according the config(https://github.com/kubernetes/kubernetes/blob/master/cluster/centos/master/scripts/apiserver.sh#L35), [apiserver about etcd config](https://github.com/kubernetes/kubernetes/blob/master/cluster/centos/master/scripts/apiserver.sh#L35)has configured using `etcd communication key`

**Comment by roberthbailey** [comment]
Thanks! (I'm not super familiar with the centos variant of the kube-up script).

/approve no-issue

As an aside, have you heard that the cluster directory is deprecated and we hope to remove it soon?

**Comment by zouyee** [comment]
I find the information in `README`, by the way, whether PRs were no longer accepted?

**Comment by roberthbailey** [comment]
PRs are welcome (and thank you for cleaning things up!). I just wanted to make sure you were aware of the current status of this part of the repository.

**Review by mariida — APPROVED** [review]

**Pull request merged**
