### PR TITLE
Remove use of HugePages feature flag in test

### PR DESCRIPTION
**Pull request by odinuge**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
The flag was removed in 1.14, and huge pages are now enabled by
default.

Removed here: https://github.com/kubernetes/kubernetes/pull/72785

/sig node
/sig testing

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

**Comment by derekwaynecarr** [comment]
thanks for the cleanup.

/approve
/lgtm

**Pull request merged**
