### PR TITLE
Support update PodManagementPolicy filed for StatefulSet

### PR DESCRIPTION
**Pull request by tanjing2020**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Support update PodManagementPolicy for sts.
Change serial to parallel can improve performance when upgrading.
So it's excellent if update PodManagementPolicy allowed.

same as #91853

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tanjing2020** [comment]
for((i=1;i<=count;i++));
do
    $kubeComd patch sts -nfst-manage nginx-test -p '{"spec":{"replicas":30, "podManagementPolicy":"Parallel"}}'
    # sleep 1
    $kubeComd patch sts -nfst-manage nginx-test -p '{"spec":{"replicas":30, "podManagementPolicy":"OrderedReady"}}'
    echo $i
done


nginx-test-0                                    0/1     Pending     0              0s
nginx-test-0                                    0/1     Pending     0              0s
nginx-test-1                                    0/1     Pending     0              0s
nginx-test-2                                    0/1     Pending     0              0s
nginx-test-1                                    0/1     Pending     0              0s
nginx-test-0                                    0/1     ContainerCreating   0              0s
nginx-test-3                                    0/1     Pending             0              0s
nginx-test-2                                    0/1     Pending             0              0s
nginx-test-4                                    0/1     Pending             0              0s
nginx-test-3                                    0/1     Pending             0              0s
nginx-test-5                                    0/1     Pending             0              0s
nginx-test-4                                    0/1     Pending             0              0s
nginx-test-1                                    0/1     ContainerCreating   0              0s
nginx-test-5                                    0/1     Pending             0              0s
nginx-test-6                                    0/1     Pending             0              0s
nginx-test-2                                    0/1     ContainerCreating   0              0s
nginx-test-6                                    0/1     Pending             0              0s
nginx-test-7                                    0/1     Pending             0              0s
nginx-test-7                                    0/1     Pending             0              0s
nginx-test-3                                    0/1     ContainerCreating   0              0s
nginx-test-8                                    0/1     Pending             0              0s
nginx-test-9                                    0/1     Pending             0              0s
nginx-test-4                                    0/1     ContainerCreating   0              0s
nginx-test-10                                   0/1     Pending             0              0s
nginx-test-8                                    0/1     Pending             0              0s
nginx-test-11                                   0/1     Pending             0              0s
nginx-test-9                                    0/1     Pending             0              0s
nginx-test-10                                   0/1     Pending             0              0s
nginx-test-11                                   0/1     Pending             0              0s
nginx-test-12                                   0/1     Pending             0              0s
nginx-test-12                                   0/1     Pending             0              0s
nginx-test-13                                   0/1     Pending             0              0s
nginx-test-13                                   0/1     Pending             0              0s
nginx-test-14                                   0/1     Pending             0              0s
nginx-test-15                                   0/1     Pending             0              0s
nginx-test-13                                   0/1     ContainerCreating   0              0s
nginx-test-14                                   0/1     Pending             0              0s
nginx-test-16                                   0/1     Pending             0              0s
nginx-test-17                                   0/1     Pending             0              0s
nginx-test-16                                   0/1     Pending             0              0s
nginx-test-15                                   0/1     Pending             0              0s
nginx-test-18                                   0/1     Pending             0              0s
nginx-test-17                                   0/1     Pending             0              0s
nginx-test-14                                   0/1     ContainerCreating   0              0s
nginx-test-19                                   0/1     Pending             0              0s
nginx-test-18                                   0/1     Pending             0              0s
nginx-test-19                                   0/1     Pending             0              0s
nginx-test-20                                   0/1     Pending             0              0s
nginx-test-16                                   0/1     ContainerCreating   0              0s
nginx-test-17                                   0/1     ContainerCreating   0              0s
nginx-test-20                                   0/1     Pending             0              0s
nginx-test-21                                   0/1     Pending             0              1s
nginx-test-22                                   0/1     Pending             0              0s
nginx-test-21                                   0/1     Pending             0              1s
nginx-test-19                                   0/1     ContainerCreating   0              1s
nginx-test-22                                   0/1     Pending             0              0s
nginx-test-23                                   0/1     Pending             0              0s
nginx-test-20                                   0/1     ContainerCreating   0              1s
nginx-test-23                                   0/1     Pending             0              0s
nginx-test-22                                   0/1     ContainerCreating   0              0s
nginx-test-24                                   0/1     Pending             0              0s
nginx-test-24                                   0/1     Pending             0              0s
nginx-test-25                                   0/1     Pending             0              0s
nginx-test-25                                   0/1     Pending             0              0s
nginx-test-26                                   0/1     Pending             0              0s
nginx-test-26                                   0/1     Pending             0              0s
nginx-test-27                                   0/1     Pending             0              0s
nginx-test-23                                   0/1     ContainerCreating   0              0s
nginx-test-24                                   0/1     ContainerCreating   0              0s
nginx-test-27                                   0/1     Pending             0              0s
nginx-test-28                                   0/1     Pending             0              0s
nginx-test-25                                   0/1     ContainerCreating   0              0s
nginx-test-29                                   0/1     Pending             0              0s
nginx-test-28                                   0/1     Pending             0              0s
nginx-test-5                                    0/1     ContainerCreating   0              1s
nginx-test-29                                   0/1     Pending             0              0s
nginx-test-29                                   0/1     ContainerCreating   0              0s
nginx-test-28                                   0/1     ContainerCreating   0              0s
nginx-test-27                                   0/1     ContainerCreating   0              0s
nginx-test-6                                    0/1     ContainerCreating   0              4s
nginx-test-22                                   1/1     Running             0              3s
nginx-test-23                                   1/1     Running             0              3s
nginx-test-7                                    0/1     ContainerCreating   0              4s
nginx-test-15                                   0/1     ContainerCreating   0              5s
nginx-test-8                                    0/1     ContainerCreating   0              5s
nginx-test-16                                   1/1     Running             0              6s
nginx-test-29                                   1/1     Running             0              5s
nginx-test-18                                   0/1     ContainerCreating   0              6s
nginx-test-21                                   0/1     ContainerCreating   0              6s
nginx-test-17                                   1/1     Running             0              6s
nginx-test-10                                   0/1     ContainerCreating   0              6s
nginx-test-19                                   1/1     Running             0              7s
nginx-test-26                                   0/1     ContainerCreating   0              6s
nginx-test-14                                   1/1     Running             0              7s
nginx-test-11                                   0/1     ContainerCreating   0              7s
nginx-test-13                                   1/1     Running             0              8s
nginx-test-25                                   1/1     Running             0              7s
nginx-test-12                                   0/1     ContainerCreating   0              8s
nginx-test-9                                    0/1     ContainerCreating   0              8s
nginx-test-20                                   1/1     Running             0              9s
nginx-test-28                                   1/1     Running             0              8s
nginx-test-24                                   1/1     Running             0              8s
nginx-test-27                                   1/1     Running             0              9s
nginx-test-1                                    1/1     Running             0              11s
nginx-test-2                                    1/1     Running             0              14s
nginx-test-0                                    1/1     Running             0              14s
nginx-test-3                                    1/1     Running             0              14s
nginx-test-4                                    1/1     Running             0              16s
nginx-test-5                                    1/1     Running             0              16s
nginx-test-8                                    1/1     Running             0              16s
nginx-test-7                                    1/1     Running             0              16s
nginx-test-11                                   1/1     Running             0              18s
nginx-test-6                                    1/1     Running             0              18s
nginx-test-10                                   1/1     Running             0              18s
nginx-test-12                                   1/1     Running             0              19s
nginx-test-9                                    1/1     Running             0              20s
nginx-test-15                                   1/1     Running             0              20s
nginx-test-26                                   1/1     Running             0              20s
nginx-test-18                                   1/1     Running             0              21s
nginx-test-21                                   1/1     Running             0              21s

**Comment by liggitt** [comment]
/unassign

Thanks for the PR. API changes should start with an accepted [proposal](https://github.com/kubernetes/enhancements/tree/master/keps#readme) and agreement from the owning SIG (in this case, sig-apps).

@kubernetes/sig-apps-feature-requests

**Pull request closed without merging**
