### PR TITLE
Bumped Heapster to v0.20.0-alpha12

### PR DESCRIPTION
**Pull request by piosz**
@mwielgus

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
@bgrant0607 Once we verify that `alpha12` release fixed the last issue we discovered in GKE/Heapster intergration we will create final Heapster release and send last PR to change configuration (hopefully tomorrow).

**Comment by bgrant0607** [comment]
@fgrzadkowski Any changes you'd like in 1.2.0-beta.1 need to be merged in the next 24 hours.

**Comment by piosz** [comment]
No, although we'd like to start testing it ASAP.

**Comment by eparis** [comment]
This PR was sucessfully cherry picked in PR #22855
please verify that the release-1.2 branch contains these changes as you would expect and contact @eparis if there appear to be problems.

**Pull request merged**
