### PR TITLE
genericapiserver: expose openapi service to allow updating the served spec

### PR DESCRIPTION
**Pull request by roycaihw**
expose openapi service from genericapiserver so that servers built on top of it can control/update the served spec. Needed for CRD openapi publishing

an alternative is what kube-aggregator does today: it [disables genericapiserver](https://github.com/kubernetes/kubernetes/blob/addcd7bb079d2b2709d4a1a06cb121db09347870/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go#L140-L143) from installing the handler, and does a [custom installation](https://github.com/kubernetes/kubernetes/blob/addcd7bb079d2b2709d4a1a06cb121db09347870/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go#L211-L216) itself, which is not a good pattern to follow IMO

/assign @mbohlool @sttts 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by roycaihw** [comment]
adding a test for the exposed openapi service

**Comment by apelisse** [comment]
I remember having a discussion with @mbohlool not wanting to do that? I may be misunderstanding.

**Comment by mbohlool** [comment]
I actually wanted this but I remember a reviewer didn't want this. I don't remember what was the reason, long time ago, but I am fine with this.

symbolic
/lgtm

**Pull request merged**
