### PR TITLE
Upgrade aws-sdk-go to 1.23.15

### PR DESCRIPTION
**Pull request by Logiraptor**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
This adds support for additional AWS regions

**Which issue(s) this PR fixes**:
None I am aware of

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by Logiraptor** [comment]
Still working through signing the corporate CLA with my employer, Pivotal. 

/sig cloud-provider

**Comment by jvshahid** [comment]
According to the flaky test dashboard, the test above has 6 flakes.  This flake seems related to https://github.com/kubernetes/kubernetes/issues/85303.  We are going to comment on the issue and rerun the tests.

/test pull-kubernetes-node-e2e-containerd

**Comment by cblecker** [comment]
@jvshahid is listed as a co-author on the commit, but has not signed the CLA. That check won't pass until it is.

**Review by cblecker — APPROVED** [review]
/uncc @cheftako @smarterclayton 
/lgtm
/assign @liggitt

**Comment by Logiraptor** [comment]
It looks like another PR was merged which upgrades the aws-sdk-go. This PR is no longer relevant.

**Pull request closed without merging**
