### PR TITLE
cluster,hack: Use community infra GCS bucket for retrieving CI builds

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Part of https://github.com/kubernetes/release/issues/1711 and https://github.com/kubernetes/k8s.io/issues/1569.

Clean up of references to gs://kubernetes-release-dev: https://cs.k8s.io/?q=kubernetes-release-dev&i=nope&files=&excludeFiles=&repos=

Accompanying PR for https://github.com/kubernetes/test-infra/pull/22790 (merge order is unimportant).

/assign @puerco @cpanato @saschagrunert @spiffxp 
cc: @kubernetes/release-engineering 

Signed-off-by: Stephen Augustus <foo@auggie.dev>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
