### PR TITLE
Fix quantity.CanonicalizeBytes docstring name

### PR DESCRIPTION
**Pull request by jonboulle**

### CODE REVIEW

**Comment by bgrant0607** [comment]
cc @wojtek-t @lavalamp

**Comment by smarterclayton** [comment]
LGTM

**Comment by lavalamp** [comment]
lgtm, looks like you have a unit test flake

**Comment by jonboulle** [comment]
so what needs to happen to get this in?

**Comment by smarterclayton** [comment]
@k8s-bot test this issue #IGNORE

**Pull request merged**
