### PR TITLE
kubectl: kubectl top sort by name

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
Please link to an issue and description of what this change is for.

**Comment by zjj2wry** [comment]
@smarterclayton i no issue for this, but has familar issue(#47163) for this. this pr sort kubectl top by name default.

**Comment by eduherminio** [comment]
Any plans to implement this?

**Pull request closed without merging**
