### PR TITLE
Volume deletion should be idempotent

### PR DESCRIPTION
**Pull request by jsafrane**
- Describe* calls should return `aws.Error` so caller can handle individual errors. `aws.Error` already has enough context (`"InvalidVolume.NotFound: The volume 'vol-0a06cc096e989c5a2' does not exist"`)
- Deletion of already deleted volume should succeed.

**Release note**:

Fixes: #60778

```release-note
NONE
```

/sig storage
/sig aws

/assign @justinsb @gnufied

### CODE REVIEW

**Comment by jsafrane** [comment]
I always got "MissingRegion: could not find region configuration" from `aws.DeleteVolume` when forcefully deleting a volume in e2e.test. Removing e2e test.

**Comment by gnufied** [comment]
@jsafrane which e2e test you are referring to?

**Comment by jsafrane** [comment]
I tried to write e2e test:

1. create PVC
2. wait until it's provisioned by default storage class
3. delete underlying GCE PD or AWS EBS
4. delete PVC
5. expect the PV is deleted

I got stuck at "delete underlying AWS EBS" - e2e framework already has [functions to do so](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/pv_util.go#L735), however I got "MissingRegion: could not find region configuration" in 
pull-kubernetes-e2e-kops-aws.

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60490)

**Comment by jsafrane** [comment]
@gnufied @justinsb: e2e test added with minimal changes to the test framework.

I'll refactor it in a subsequent PR for 1.11 to be consistent with GCE cloud provider for the tests (i.e. set it up at startup and add `framework.GetAWSCloud()`) so individual tests don't need to instantiate it by themselves.

**Comment by jsafrane** [comment]
@saad-ali, can you please approve test changes and squeeze it into 1.10?

**Pull request merged**
