### PR TITLE
fix typo: onlyCluAndMemoryParam --> onlyCpuAndMemoryParam

### PR DESCRIPTION
**Pull request by imroc**

### CODE REVIEW

**Comment by imroc** [comment]
@denkensk @Random-Liu  seems the failure is unrelated

**Comment by imroc** [comment]
@denkensk @Random-Liu  PTAL. test passed

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Comment by nikhita** [comment]
/kind cleaup
/release-note-none

/assign @Random-Liu 
for approval

**Pull request closed without merging**
