### PR TITLE
Optimize describe pvc output organization

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind cleanup

**What this PR does / why we need it**:
Currently, describe pvc ouput is like this, it may hard to read. We'd better remove the `Mounted by xx` up

image

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by cwdsuzhou** [comment]
/aasign @juanvallejo 

PTAL

**Comment by cwdsuzhou** [comment]
/assign @soltysh 

PTAL

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
