### PR TITLE
Correct docs

### PR DESCRIPTION
**Pull request by hoffin**
**What this PR does / why we need it**:
There was a change to the registry-proxy but the documentaiton wasn't completely updated to reflect change made.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Linked to [contribute deis/registry-proxy as a replacement for kube-registry-proxy](https://github.com/kubernetes/kubernetes/pull/35797)

**Special notes for your reviewer**:
First time contributing.
**Release note**:

```release-note
Updated the kube-registry-proxy readme example.
```

### CODE REVIEW

**Comment by hoffin** [comment]
I signed the CLA

**Comment by bacongobbler** [comment]
docs LGTM

**Comment by eparis** [comment]
I thought these things were supposed to be automatically generated/updated from appropriete .yaml files. We'll see what the verification test says. If it is happy, I am happy.

**Comment by eparis** [comment]
also, the CLA has not been signed correctly. Not sure how to help with that...

**Comment by hoffin** [comment]
CLA should be sorted now.

**Comment by eparis** [comment]
@k8s-bot ok to test

**Comment by surajssd** [comment]
@eparis @hoffin 

When I try to pull this image `gcr.io/google_containers/kube-registry-proxy:0.4` it says it's not available?

```bash
$ sudo docker pull gcr.io/google_containers/kube-registry-proxy:0.4
Trying to pull repository gcr.io/google_containers/kube-registry-proxy ... 
manifest unknown: Failed to fetch "0.4" from request "/v2/google_containers/kube-registry-proxy/manifests/0.4".
```

Can you guys tell what is the real problem?

**Comment by hoffin** [comment]
When I used it I assumed it was still being uploaded. I just created my own public image.
quay.io/hoffin/registry-proxy:0.4
We need someone with access to the registry to build and upload.

**Comment by surajssd** [comment]
@hoffin I think @roberthbailey can help in that respect, I need this for PR https://github.com/kubernetes/kubernetes/pull/35582

**Comment by hoffin** [comment]
I agree with your PR, I did just that after getting up and running.

**Comment by solsson** [comment]
The missing image is tracked in https://github.com/kubernetes/kubernetes/issues/38843

**Pull request merged**
