### PR TITLE
Update Changelog 1.9

### PR DESCRIPTION
**Pull request by jstriebel**
**What this PR does / why we need it**:
The upgrade from version `1.9.3` to `1.9.4` included a breaking change (#58720), namely `Changes secret, configMap, downwardAPI and projected volumes to mount read-only`.

This change was added to the changelog in the part `Other notable changes`, and not in `Action Required`, which is usually the case with breaking changes. This PR moves it there.

For reference: this change was discussed in #62099.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by jstriebel** [comment]
I lost track of this PR before, now everything is merged again.
Could anybody of you review this please? @neolit123 @bgrant0607 @thockin @lavalamp

**Comment by jstriebel** [comment]
@neolit123 Should this still be merged?

**Comment by neolit123** [comment]
sadly, i do not know the policy on that.
you can ask in the #sig-release channel on slack.

**Pull request closed without merging**
