### PR TITLE
Fix autogeneration mark for instrumentation doc

### PR DESCRIPTION
**Pull request by sftim**
#### What type of PR is this?

/kind feature
/kind documentation

#### What this PR does / why we need it:

Update the generator code that produces https://kubernetes.io/docs/reference/instrumentation/metrics/ so that the page gets correctly marked as automatically generated.

#### Special notes for your reviewer:
Eventually this change will reach the live website. No hurry on that.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

/sig instrumentation

### CODE REVIEW

**Comment by dashpole** [comment]
/retest
cc @logicalhan

**Comment by sftim** [comment]
Given https://github.com/kubernetes/kubernetes/pull/113814#issuecomment-1310444075

/triage accepted

**Comment by sftim** [comment]
This is a fixup for PR #113824

**Comment by sftim** [comment]
/retitle Fix autogeneration mark for instrumentation doc

**Review by logicalhan — COMMENTED** [review]
/lgtm

Thanks!

**Pull request merged**
