### PR TITLE
Use fixed days to test translateTimestamp for months

### LINKED ISSUE #17998: TestTranslateTimestamp shouldn't use time.Now when testing for days in months
Build is "broken" because TestTranslateTimestamp in pkg/kubectl/resource_printer_test.go does a "time.Now().AddDate(0, -3, 0)" and compares it to "92d". Test should either use a fixed date, or allow for variability in days per month.

Failed tests:
1 tests failed.
FAILED:  kubectl.TestTranslateTimestamp

Error Message:
Failed

Stack Trace:
resource_printer_test.go:1226: On months ago, expected '92d', but got '91d'

### PR DESCRIPTION
**Pull request by hurf**
Use fixed days to avoid days in different months.

Closes: #17998

@karlkfi I've put a test with fixed days. Can you review it?

Terribly sorry for the inconvenience brought in by the bug.

### CODE REVIEW

**Comment by hurf** [comment]
@k8s-bot test this please

**Comment by smarterclayton** [comment]
LGTM

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by karlkfi** [comment]
Sorry for not getting to this earlier....
If I'm reading that test correctly, tho, it just checks that -90 gets converted to "90d". The "months ago" is just for the test failure output? If that's the case, then we're never actually testing the month conversion, are we?

FWIW, I've use https://github.com/dustin/go-humanize in the past to humanize time durations. I'm not sure why we need yet another version of this kind of code in k8s.

**Comment by hurf** [comment]
@karlkfi Hi Karl, the test is intended to show that we don't have a `month` unit.

For `go-humanize`, once I tried to introduce it to k8s, See #12331. But first its units are too long for cli output, we need to make some change to allow custom defined units. Second, others think if we just use one of its functions, it's not worth to introduce the whole package.

**Comment by karlkfi** [comment]
One of the beauties of Godep is that it only imports the packages you need. Too bad go-humanize isn't packaged with more granularity. But thanks for the explanation.

**Pull request merged**
