### PR TITLE
Add secret to Federation API Server e2e test.

### PR DESCRIPTION
**Pull request by ghost**
Still busy testing this...

cc: @colhom @mml @madhusudancs @mfanjie

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@k8s-bot unit test this issue: #IGNORE

**Comment by quinton-hoole** [comment]
OK, I tested this and it works fine. @nikhiljindal LGTM?  
The e2e test failure on Jenkins is unrelated to this PR: 

```
ERROR: (gcloud.compute.instances.create) Some requests did not succeed:
 - The resource 'projects/google-containers/global/images/gci-beta-52-8350-23-0' is not ready
```

**Comment by nikhiljindal** [comment]
awesome, lgtm, thanks!

**Comment by quinton-hoole** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by quinton-hoole** [comment]
Another e2e flake:

```
+ go run ./hack/e2e.go -v --build
2016/06/10 11:28:43 e2e.go:212: Running: build-release
ERROR: gcloud crashed (error): [Errno 111] Connection refused
```

**Comment by quinton-hoole** [comment]
@k8s-bot test this issue: #24476

**Comment by quinton-hoole** [comment]
@k8s-bot test this issue: #24476

**Comment by quinton-hoole** [comment]
@k8s-bot test this issue: #24476

**Comment by quinton-hoole** [comment]
```
Build was aborted
Aborted by anonymous
```

**Comment by quinton-hoole** [comment]
e2e tests all passed, but the jenkins node was taken out of service, so it reported an error anyway.

```
SUCCESS! -- 180 Passed | 0 Failed | 0 Pending | 129 Skipped 

Ginkgo ran 1 suite in 11m46.463937815s
Test Suite Passed
2016/06/10 15:46:25 e2e.go:214: Step 'Ginkgo tests' finished in 11m47.635136292s
+ exitcode=0
+ [[ '' == \t\r\u\e ]]
+ [[ '' == \t\r\u\e ]]
+ [[ true == \t\r\u\e ]]
+ sleep 30
FATAL: no longer a configured node for agent-pr-1
java.lang.IllegalStateException: no longer a configured node for agent-pr-1
	at hudson.model.AbstractBuild$AbstractBuildExecution.getCurrentNode(AbstractBuild.java:453)
	at hudson.model.AbstractBuild$AbstractBuildExecution.reportBrokenChannel(AbstractBuild.java:810)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
ERROR: Step ‘Publish JUnit test result report’ failed: no workspace for kubernetes-pull-build-test-e2e-gce #44195
[PostBuildScript] - Execution post build scripts.
ERROR: Build step failed with exception
```

**Comment by mml** [comment]
I think you missed a spot.

https://github.com/kubernetes/kubernetes/commit/23e99c47adfb50ff84a844b1c759d2fa3c08bc16

**Comment by quinton-hoole** [comment]
@mml As discussed, that file comes from a PR that has not merged into HEAD yet, so we can't include it here.  We can fix that separately.  @dchen1107 this one is safe to merge, thanks!

**Comment by dchen1107** [comment]
Ok, manually merging it ...

**Pull request merged**
