### PR TITLE
cleanup(kubectl taint): fix Errorf and comment error, and remove unne…

### PR DESCRIPTION
**Pull request by yuzhiquan**
cleanup(kubectl taint): fix Errorf and comment error, and remove unnecessary bool flag

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
fix Errorf and comment error, and remove unnecessary bool flag.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

-->
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by yuzhiquan** [comment]
gently ping @tanjunchen .

**Comment by yuzhiquan** [comment]
Needs approved, lgtm labels.  @k8s-ci-robot @tanjunchen @soltysh @freeformz

**Comment by yuzhiquan** [comment]
gently ping @tanjunchen @soltysh @freeformz

**Comment by yuzhiquan** [comment]
Gently ping @soltysh @derekwaynecarr @smarterclayton

**Comment by yuzhiquan** [comment]
Gently ping @soltysh @derekwaynecarr @smarterclayton

**Comment by yuzhiquan** [comment]
Would you mind to have a review? @liggitt

**Comment by tanjunchen** [comment]
ping @liggitt  
it seems ok

**Pull request merged**
