### PR TITLE
return fitErr before PrioritizeNodes

### PR DESCRIPTION
**Pull request by mqliang**

### CODE REVIEW

**Comment by mqliang** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
There is already in-flight PR doing this - see:
https://github.com/kubernetes/kubernetes/pull/18416

**Comment by mqliang** [comment]
@wojtek-t Ok, sorry for not noticing that.

**Comment by wojtek-t** [comment]
@mqliang - no worries - thanks for trying to fix it!

**Pull request closed without merging**
