### PR TITLE
Added missing user setup for RBD StorageClass documentation.

### PR DESCRIPTION
**Pull request by elsonrodriguez**
Also some other minor fixes.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34042)

### CODE REVIEW

**Comment by elsonrodriguez** [comment]
@zmerlynn PTAL, the docs will be confusing without this snippet.

**Comment by elsonrodriguez** [comment]
@rootfs @zmerlynn Thoughts? This needs to be in the 1.5 docs for the instructions to make sense.

**Comment by elsonrodriguez** [comment]
This should probably be in 1.5

**Comment by elsonrodriguez** [comment]
@jsafrane  Review/Merge?

**Comment by jsafrane** [comment]
@k8s-bot ok to test

**Comment by jsafrane** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
