### PR TITLE
Small fix for number of pods and nodes in test function

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
**What this PR does / why we need it**:
Small fix to have correct pods and nodes in test function.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
Scheduler perf, nodes and pods number fix for 100 nodes 3k pods.
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
Good catch!
/cc @k82cn

**Comment by k82cn** [comment]
@k8s-bot ok to test

**Comment by ravisantoshgudimetla** [comment]
Can someone bump the bot again to test. All the failures seem to be flakes.

**Review by jayunit100 — APPROVED** [review]

**Pull request merged**
