### PR TITLE
Update kubeadm OWNERS file

### PR DESCRIPTION
**Pull request by luxas**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

- Graduates @neolit123 to approver :tada: 
- Adds two new reviewers @rosti & @yagonobre :100: 
- Removes @stealthybox & @xiangpengzhao :wave: 

from the kubeadm OWNERS file.

Welcome and congrats new reviewers and approvers!
Thanks for your contributions, and hopefully we'll see you
around again @stealthybox & @xiangpengzhao!

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

@kubernetes/sig-cluster-lifecycle 
/assign @luxas @timothysc @fabriziopandini

### CODE REVIEW

**Comment by luxas** [comment]
/priority backlog

I (formally) approve the OWNERS changes in this file
/approve

Putting the hold so we can get the other approvers' approval of this change as well
/hold

@rosti @yagonobre @neolit123 @xiangpengzhao @stealthybox Please ACK or `/lgtm` this change

**Comment by fabriziopandini** [comment]
+1 from me
This is a good opportunity to say thanks to @rosti @yagonobre @neolit123 @xiangpengzhao @stealthybox. 
Really appreaciated!

**Comment by xiangpengzhao** [comment]
ACK +1
Thanks folks! Very glad to have been working with you guys! Hopefully I will have more time for kubeadm in the future :)

**Comment by rosti** [comment]
ACK from me

**Comment by yagonobre** [comment]
Ack from me

**Comment by neolit123** [comment]
LGTM, thanks Lucas.

**Review by timothysc — APPROVED** [review]
/lgtm

**Comment by stealthybox** [comment]
It's been a pleasure contributing so far -- see around you soon!

ack :)
/lgtm

**Comment by stealthybox** [comment]
Congrats @neolit123 🌮!
You've put a lot of work into kubeadm and your approver status is very well deserved ^^

**Comment by luxas** [comment]
Great, all ACK's needed are here, I'll unhold this
/hold cancel

**Comment by neolit123** [comment]
thanks @stealthybox 
drop in the meetings or slack when you have more time for kubeadm.
your insights are always valuable!!

**Pull request merged**
