### PR TITLE
kubeadm: use strings in TestTokenOutput

### PR DESCRIPTION
**Pull request by bart0sh**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Used strings instead of bytes in the TestTokenOutput test cases as
expected output is a plain text.

This should also simplify the data representation and the test code a bit.

```release-note
NONE
```

### CODE REVIEW

**Review by fabriziopandini — APPROVED** [review]
/lgtm
/approve

**Review by Klaven — APPROVED** [review]
/lgtm! Thanks!

**Pull request merged**
