### PR TITLE
when copy file from host to pod like this: 1.kubectl copy /tmp/test-f…

### LINKED ISSUE #65530: kubectl cp file pod: causes a panic
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
`kubectl cp file pod:` panics
```
$ kubectl cp file pod:
panic: runtime error: index out of range

goroutine 1 [running]:
k8s.io/kubernetes/pkg/kubectl/cmd.copyToPod(0x2349d00, 0xc420890480, 0xc4203d5b80, 0x231f0c0, 0xc42000c018, 0x231f0c0, 0xc42000c020, 0x0, 0x0, 0x0, ...)
	/workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go:171 +0x888
k8s.io/kubernetes/pkg/kubectl/cmd.runCopy(0x2349d00, 0xc420890480, 0xc4203d5b80, 0x231f0c0, 0xc42000c018, 0x231f0c0, 0xc42000c020, 0xc4200a1500, 0x2, 0x4, ...)
	/workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go:138 +0x23b
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdCp.func1(0xc4203d5b80, 0xc4200a1500, 0x2, 0x4)
	/workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/cp.go:73 +0x89
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203d5b80, 0xc4200a1440, 0x4, 0x4, 0xc4203d5b80, 0xc4200a1440)
	/workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:757 +0x2c1
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4202f2a00, 0xc420821ed8, 0xc420821ee0, 0x12a05f200)
	/workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:843 +0x334
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4202f2a00, 0x18cba28, 0x24e9960)
	/workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:791 +0x2b
main.main()
	/workspace/anago-v1.10.4-beta.0.68+5ca598b4ba5abb/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:50 +0x196
```

**What you expected to happen**:
Syntax error, as it is not legit cp syntax.

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl cp file pod:`

**Anything else we need to know?**:
Occurs in every version 1.9.x and 1.10.x, but 1.8.x is safe.
#65482 is similar, but it has a fix candidate already going in, that is not fixing this, so opening a separate issue.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: VM
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`): `Linux tumi 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

/sig cli

### PR DESCRIPTION
**Pull request by soltysh**
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #65530

**Special notes for your reviewer**:
/assign @juanvallejo 
since you were looking at the original one as well.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by soltysh** [comment]
/assign @MaciekPytel 
for 1.10 approval

**Review by juanvallejo — APPROVED** [review]

**Comment by MaciekPytel** [comment]
/hold
For 1.10.6

**Comment by MaciekPytel** [comment]
@soltysh Who would be the right approver for this?

**Comment by soltysh** [comment]
> @soltysh Who would be the right approver for this?

@MaciekPytel  this is a cherry-pick from current master (not quite clean), and since I co-lead the effort I'd consider myself as the righteous approver, additionally the PR was already verified by Juan.

**Pull request merged**
