### PR TITLE
Update GCI_VERSION to cos-77-12371-114-0 as older image is deprecated

### LINKED ISSUE #87651: cos-77-12371-89-0 is deprecated
Example from a recent [pull-kubernetes-e2e-gce job](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/87606/pull-kubernetes-e2e-gce/1222164302757105664/build-log.txt)
```
W0128 14:38:13.618]  - The resource 'projects/cos-cloud/global/images/cos-77-12371-89-0' is deprecated. A suggested replacement is 'projects/cos-cloud/global/images/cos-77-12371-114-0'.
```

### PR DESCRIPTION
**Pull request by dims**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
`cos-77-12371-89-0` has been deprecated, so we need to move to the suggested newer image which is `cos-77-12371-141-0`. Details about the image are here:
https://cloud.google.com/container-optimized-os/docs/release-notes/m77#cos-77-12371-141-0

**Which issue(s) this PR fixes**:

Fixes #87651

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/assign @BenTheElder @cblecker 
cc @liggitt

**Comment by BenTheElder** [comment]
thanks dims!
/lgtm

**Pull request merged**
