### PR TITLE
Add note about directory structure in code-generator

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
This PR enhances the documentation of code-generator to:
1. Point the reader at the kube_codegen.sh script, and
2. Enhance the comments in that script to describe further the input directory structure.

This does NOT address issue https://github.com/kubernetes/code-generator/issues/165, which is requesting a relaxation of requirements on higher levels of directory structure.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by MikeSpreitzer** [comment]
@MikeSpreitzer

**Comment by MikeSpreitzer** [comment]
The force-push to aa03a5fbcc7 is a correction of the comment about input directory structure.

**Comment by MikeSpreitzer** [comment]
The force-push to b88fefad1f8 is another correction.

**Comment by jiahuif** [comment]
/assign @deads2k
As code-generator owner. Thank you.

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
