### PR TITLE
Don't use strokes in the logo SVG

### PR DESCRIPTION
**Pull request by thockin**
Mixing strokes and paths makes for weird scaling.  Convert the
logo-with-border to use a path.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
Random assignee.  Does anyone else feel like they want some ownership of logo artifacts?

@dankohn ?

**Comment by dankohn** [comment]
Please note that logos in https://github.com/cncf/artwork/tree/master/kubernetes need to be updated once this one is.

**Comment by dankohn** [comment]
@ccraigross leads the LF/CNCF creative services team.

**Comment by thockin** [comment]
Thanks, I didn't know his github :)

**Comment by thockin** [comment]
We should add him as an org member and a reviewer of logo/

**Comment by thockin** [comment]
Craig approved by email

**Pull request merged**
