### PR TITLE
e2e: Stop using deprecated zone nodeSelector

### PR DESCRIPTION
**Pull request by justinsb**
Update to the non-deprecated label names.

/kind cleanup

```release-note
NONE
```

/sig storage

### CODE REVIEW

**Comment by Jiawei0227** [comment]
Hey @justinsb thanks for your change. Can you update the unit test as well?

**Comment by oomichi** [comment]
This is a kind of 518844fd25f593326340d936bab3cedda0f7dda9

/triage accepted
/lgtm

**Pull request merged**
