### PR TITLE
bump k8s version to v1.1.2 on ubuntu/calico

### LINKED ISSUE #17794: outdated references in Getting Started guide for Ubuntu and Calico
https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/ubuntu-calico.md says to download v1.1.1 but now v1.1.2 is the latest.

[erroneous complaint deleted here]

### PR DESCRIPTION
**Pull request by dalanlan**
Fix #17794

### CODE REVIEW

**Comment by davidopp** [comment]
@mikespreitzer

**Comment by davidopp** [comment]
LGTM

**Comment by djosborne** [comment]
Awesome, thanks @dalanlan

**Comment by MikeSpreitzer** [comment]
yes, LGTM too.

**Pull request merged**
