### PR TITLE
CRI: add apparmor and seccomp

### PR DESCRIPTION
**Pull request by feiskyer**
This PR adds apparmor and seccomp to CRI.

All app armor related node e2e tests are passed in my local environment.

CC @yujuhong @Random-Liu @kubernetes/sig-node

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33450)

### CODE REVIEW

**Comment by feiskyer** [comment]
@k8s-bot e2e test this

**Comment by Random-Liu** [comment]
Hm...Just saw this...I'm also working on this on.

I discussed with @yujuhong last week that we prefer to use annotation instead of changing CRI.

**Comment by feiskyer** [comment]
@Random-Liu I think set them explicitly is more clear. A problem of setting annotations is: the format of annotations may be changed silently. That is although CRI looks not changed, but annotations changed, which indicates CRI is actually also changed.

**Comment by yujuhong** [comment]
@feiskyer to avoid duplicated efforts, please comment on the CRI issues to claim an item before you start working on it! Thanks.

**Comment by yujuhong** [comment]
> @Random-Liu I think set them explicitly is more clear. A problem of setting annotations is: the format of annotations may be changed silently. That is although CRI looks not changed, but annotations changed, which indicates CRI is actually also changed.

People use annotations for this purpose exactly -- it's too premature to define the objects in the API, but still want to be provide an option to use it (and gather feedback).  I mentioned to @Random-Liu last week that we may still use annotations to pass these settings given that the security context and objects in k8s API are still evolving. 

That said, it's possible that although seccomp/apparmor in k8s API are not set in stone yet, that all kubelet will ever need to convey to the container runtime is a path to the profile, and it's ok to add this to CRI. cc'ing a couple more folks for opinions. @pmorie @timstclair @smarterclayton @erictune @jfrazelle 

Also, we still need to handle the cases where the runtime does not support these security features. 
(#32803)

**Comment by yifan-gu** [comment]
What is the format of the profile? Seems it's just a string that points to a json file [defined by docker](https://docs.docker.com/engine/security/seccomp/)? If so that sounds very runtime-specific, so I am -1 on adding it to the CRI unless we have some more general format on this.
For runtime specific features, I suggest we go through annotation or add a byte/string field called `Data` or `Others`.

**Comment by feiskyer** [comment]
@yujuhong @yifan-gu Agree this implementation is somewhat docker-specific. There is no general profile format yet and those annotations have already passed to sandboxconfig.Annotations.

**Comment by feiskyer** [comment]
Closing this one in favor of #33500.

**Pull request closed without merging**
