### PR TITLE
Don't specify a description for Calico CRDs

### PR DESCRIPTION
**Pull request by caseydavenport**
**What this PR does / why we need it**:

CRDs have lost the "description" field, so as it stands these won't validate. This is needed to allow Calico to function again. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
I thought we always allow unknown fields.  Did something change in machinery?

@lavalamp @kubernetes/sig-api-machinery-api-reviews

**Comment by thockin** [comment]
@jberkus

**Comment by caseydavenport** [comment]
> CRDs never had a description field

Lovely, I wonder how that ended up in our CRDs then :/

**Comment by liggitt** [comment]
/milestone v1.11

adding to the milestone. no risk, high impact bug fix

**Pull request merged**
