### PR TITLE
publishing: Use go1.15.12 for 1.20 and 1.19 release branches

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind cleanup
/area dependency

#### What this PR does / why we need it:
Go updates for release 1.19 and 1.20 branches

Tracking issue: https://github.com/kubernetes/release/issues/2060
Slack thread: https://kubernetes.slack.com/archives/C2C40FMNF/p1620388464296500

/hold wait for 
 - https://github.com/kubernetes/kubernetes/pull/101845
 - https://github.com/kubernetes/kubernetes/pull/101846

/assign @nikhita @dims 
cc: @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by nikhita** [comment]
Lgtm for this PR but the bot is broken right now, so I'd like to merge this PR after the bot is fixed. I am taking a look today.

There were issues that popped up with the last go bump -- go1.15.11 brought in some changes that broke the bot. We should be able to mitigate these changes, will send another fix soon. Previous attempts at fixing this- https://github.com/kubernetes/publishing-bot/pull/254, https://github.com/kubernetes/publishing-bot/pull/255, https://github.com/kubernetes/publishing-bot/pull/256

**Comment by nikhita** [comment]
/hold cancel

slack thread for context - https://kubernetes.slack.com/archives/C2C40FMNF/p1620656409316900?thread_ts=1620656336.316500&cid=C2C40FMNF

**Comment by cpanato** [comment]
both PRs are merged.
/hold cancel

**Pull request merged**
