### PR TITLE
Refactor federation dns test case with sets.String

### LINKED ISSUE #51396: Refactor unit test case with sets.String to replace string slice
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature
/kind feature

**What happened**:
Refactor unit test case with sets.String to replace string slice
To use golang sets.String, that will help check if two groups equal with each other.

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
change to make got and want use sets.String instead, since that is both safe and more clearly shows the intent.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #51396

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
/assign @enisoc 
PTAL

**Comment by zhangxiaoyu-zidif** [comment]
Hi, @enisoc 
Do you have other golang refactor points to do?
I'd love to do some similar work to improve my golang coding. :)

**Comment by enisoc** [comment]
/lgtm

@zhangxiaoyu-zidif I don't know if this would be interesting to you, but one thing I've wanted to do is speed up integration tests by standardizing and tightening poll intervals.

For example, this one could be more like 100ms instead of 10s:

https://github.com/kubernetes/kubernetes/blob/3168bd4b123629d7d33ee976437175d8cde5f0cc/test/integration/replicaset/replicaset_test.go#L169

There also may be opportunities to combine related integration test functions (e.g. all the RS orphan/adopt/controllerRef tests) via [subtests](https://blog.golang.org/subtests) so they share the startup/teardown of the apiserver instead of duplicating that work.

You could compare the total time for each test before and after to show the impact. It's important to show that integration tests can be fast because we're planning to add many more test cases for workload controllers.

**Comment by zhangxiaoyu-zidif** [comment]
@enisoc 
I'd love to try it. When I send that PR, I will assign it to you.
Thanks very much!

**Comment by madhusudancs** [comment]
/approve 

(for federation)

**Pull request merged**
