### PR TITLE
Secrets and ConfigMaps: Manage Generation

### PR DESCRIPTION
**Pull request by alvaroaleman**
This change makes the apiserver manage the Generation on ConfigMaps and Secets by
setting it to `1` on creation and incrementing it whenever the `Data` or
`BinaryData` changes. Changes to the object as a whole can already be
 deducted from the `ResourceVersion` changing.

The main use-case is controllers that react to `ConfigMap`/`Secret` content
changes, with this change they can get away with only watching the
ObjectMeta.

/kind feature
/sig api-machinery
(I think? Not sure)

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
The Generation on ConfigMaps and Secrets will be set to 1 on Creation and increased by 1 on non-metadata updates
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
should the `immutable` field inform generation? I can see reasons for and against… not having a clear `spec` stanza makes the dividing line a little less clear

**Comment by alvaroaleman** [comment]
> should the immutable field inform generation? I can see reasons for and against… not having a clear spec stanza makes the dividing line a little less clear

Oh I didn't realize that a this can be enabled on an existing cm/secret. My interpretation for `Generation` would be "non-metadata changes except status" (which doesn't exist here) so I would argue that it should be bumped. Practically speaking I guess I would assume it doesn't matter too much either way, since that change can be done at most once per cm/secret and I would assume it is not super common to enable this later on.

**Pull request closed without merging**
