### PR TITLE
A test we always skip should not be a conformance test

### LINKED ISSUE #62217: Conformance test is always skipped
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/container_probe.go#L281

- Should we just yank the conformance tag?

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:
We should not have a test marked Conformance when it is always skipped

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #62217

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@marun @smarterclayton WDYT? please take a look

**Comment by bgrant0607** [comment]
/lgtm
/approve

cc @kubernetes/sig-node-pr-reviews

**Pull request merged**
