### PR TITLE
Correct sc parameters for gluster dynamic provisioner.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@roots @jsafrane PTAL.

**Comment by humblec** [comment]
@jsafrane any way we are converting to `lower` strings while parsing. Not sure, we need to keep it `lowercase` in sc parameter examples. If thats `not` the best practise, I will discard this PR.

**Comment by jsafrane** [comment]
The best practice is to use camelCase as everywhere else in Kubernetes json and yaml files. Volume plugins use case-insensitive comparison to be more benevolent on input.

**Comment by humblec** [comment]
@jsafrane Thanks !!! In that case, I will close this PR .

**Pull request closed without merging**
