### PR TITLE
remove pd-external from e2e config

### LINKED ISSUE #70258: Remove out of tree pd test config
**What happened**:
Remove out of tree plugin config introduced in https://github.com/kubernetes/kubernetes/pull/70254 once we can refactor the e2e tests enough to be able to vendor them as a library in external repos according to https://github.com/kubernetes/kubernetes/issues/69819

/assign

/king bug

### PR DESCRIPTION
**Pull request by msau42**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
PD CSI driver framework is switching to use the e2e external framework in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/249

**Which issue(s) this PR fixes**:

Fixes #70258

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
/assign @davidz627 
/hold 
until the new framework has merged and confirmed success

**Comment by davidz627** [comment]
We probably should also remove this: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/csi_volumes.go#L37

**Comment by msau42** [comment]
whoooooops repushed

**Pull request merged**
