### PR TITLE
Fix typo of e2e utils under network framework

### PR DESCRIPTION
**Pull request by hj-johannes-lee**
Fix typo "contaienr" to "container"

#### What type of PR is this?
/kind documentation

#### Which issue(s) this PR fixes:

Fixes typo of e2e utils under network framework

#### Does this PR introduce a user-facing change?
No.

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve
/ok-to-test

**Comment by hj-johannes-lee** [comment]
@oomichi Sorry for not being that careful. I added 'NONE' following the instruction, since there is no impact.!

**Comment by oomichi** [comment]
> @oomichi Sorry for not being that careful. I added 'NONE' following the instruction, since there is no impact.!

No problem at all.
When I submitted my first PR, I also was confused due to the `NONE` of the release-note ;-)

**Pull request merged**
