### PR TITLE
Revert "Introduce APIs to support multiple ClusterCIDRs (#108290)"

### PR DESCRIPTION
**Pull request by JamesLaverack**
This reverts commit b9792a9daef4d978c5c30b6d10cbcdfa77a9b6ac.

#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it:

This change reverts https://github.com/kubernetes/kubernetes/pull/108290, see https://github.com/kubernetes/enhancements/issues/2593#issuecomment-1096821073 for further details.

API Changes:

- Removes networking.k8s.io/v1alpha1 API group
- Removes ClusterCIDRConfig type in networking.k8s.io/v1alpha1 API group

#### Which issue(s) this PR fixes:

NONE

#### Special notes for your reviewer:

Please bring comments about the nature of this revert to the k/enhancements issue here: https://github.com/kubernetes/enhancements/issues/2593#issuecomment-1096821073

#### Does this PR introduce a user-facing change?

```release-note
Remove a v1alpha1 networking API for ClusterCIDRConfig
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]:  https://github.com/kubernetes/enhancements/pull/2594
```

/sig network
/release-blocker
/priority critical-urgent
/milestone 1.24

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

From a SIG Release perspective.

**Review by justaugustus — APPROVED** [review]
/lgtm
/approve
/assign @thockin @liggitt

**Comment by sftim** [comment]
D'oh, I meant /retest - sorry

**Comment by liggitt** [comment]
I don't have context on the PR being reverted, will defer to Tim on this one
/unassign

**Comment by lavalamp** [comment]
I agree that reverting this is probably the right thing to do, I'll let @thockin give the approve though.

**Comment by thockin** [comment]
Sigh.

I'm a little grumpy about this but not enough to argue it against the decision of release folks.

/lgtm
/approve

**Comment by liggitt** [comment]
CI failure is legitimate, need to regen openapi

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by liggitt** [comment]
Refetch tags before you regen the openapi, your local tags are incorrectly including v1alpha1 flowcontrol APIs which are no long served in 1.24

**Pull request merged**
