### PR TITLE
fix wrong log when did a rollout status to daemonset

### PR DESCRIPTION
**Pull request by zhangmingld**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
 /kind cleanup

**What this PR does / why we need it**:
before: Waiting for daemon set
after: Waiting for daemonset
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ash2k** [comment]
Actually, repository is full of `daemon set`. I don't think it's something worth changing.

**Comment by zhangmingld** [comment]
> 
> 
> Actually, repository is full of `daemon set`. I don't think it's something worth changing.

In fact ，i think a daemon set is ok in the repostory ， but when we use kubectl , it still shows daemon set , i think it is a little problem

**Pull request closed without merging**
