### PR TITLE
OWNERS: Update SIG Release aliases

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind cleanup documentation

#### What this PR does / why we need it:

- OWNERS(sig-release): Reflect Marko's position as RelEng subprj lead 
- OWNERS(sig-release): Add `release-team-subproject-leads` alias
- CHANGELOG: Reflect correct approvers/reviewers
  - Add `release-team-subproject-leads` alias to approvers/reviewers
  - Add 1.32 Release Notes Lead to approvers/reviewers
  - Prune previous Release Team entries

Signed-off-by: Stephen Augustus <foo@auggie.dev>

cc: @kubernetes/sig-release-leads @gracenng @katcosgrove @xmudrii 
ref: https://github.com/kubernetes/kubernetes/pull/129172, https://github.com/kubernetes/sig-release/issues/2695
xref: https://github.com/kubernetes/sig-release/issues/2516, https://github.com/kubernetes/sig-release/issues/2515

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]

**Comment by dims** [comment]
/approve
/lgtm

/hold 

( please remove hold when ready @justaugustus )

**Comment by xmudrii** [comment]
A bit late, but
/lgtm
Thanks for taking care of this!

**Pull request merged**
