### PR TITLE
[WIP] Integration fixes

### PR DESCRIPTION
**Pull request by aojea**
/kind cleanup
/kind failing-test

#### What this PR does / why we need it:

Fixes for the testing of the apiserver on the integration framework

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
This is odd, there are several tests that depend on the shutdown behavior of the apiserver
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/108060/pull-kubernetes-integration/1492050139156582400

Check `TestDedupOwnerReferences`, if shutdown is 1s it fails with multiple races, bumping it to 10s makes the test works

**Comment by aojea** [comment]
do we have a problem shutting down the connection to etcd?

```
wget -O - https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/108060/pull-kubernetes-integration/1493249706472509440/artifacts/ss.txt | grep 2379 | wc
--2022-02-14 17:59:28--  https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/108060/pull-kubernetes-integration/1493249706472509440/artifacts/ss.txt
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.184.16, 142.250.178.176, 216.58.215.176, ...
   4308   30158 1038228
```

4308 connections sound excessive , it is one per group version  last time I've checked
https://github.com/kubernetes/kubernetes/pull/105826

**Comment by aojea** [comment]
this triggers the failure of the job because one of the `test binaries` gets stale and timeouts after 10 mins

**Comment by aojea** [comment]
@liggitt goroutine party d5e0dedcf457f77713e5a5da529fc896c69ec7ec :smile:

**Comment by liggitt** [comment]
> 🤔 am I doing the right assumption assuming EtcdMain() is only called once per test binary?

yeah... each package runs in a separate process, and TestMain is called once for the process

**Comment by aojea** [comment]
all the goroutines seems related to grpc blocked on some io operations,  most traces looks that are coming from the watcher cache

**Comment by aojea** [comment]
```
	controlPlaneConfig := framework.NewIntegrationTestControlPlaneConfig()
	_, _, closeFn := framework.RunAnAPIServer(controlPlaneConfig)
	closeFn()
```
1000 goroutines orphan

```
	s := apitesting.StartTestServerOrDie(t, nil, nil, etcdConfig)
	s.TearDownFn()
```
200 goroutines

**Comment by aojea** [comment]
we could finally solve the mistery, :smile:

**Pull request closed without merging**
