### PR TITLE
lowercase node name in generated static pod name 

### LINKED ISSUE #59801: Cloud Provider should not return upper case hostname
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

/kind bug

> /kind feature

**What happened**:

I created a static pod for etcd as following with vsphere as cloud provider:

```
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "name": "k8s-etcd",
        "namespace": "kube-system",
        "annotations": {
            "scheduler.alpha.kubernetes.io/critical-pod": ""
        }
    },
    "spec": {
        "containers": [
            {
                "command": [
                    "etcd",
                    "--name=etcd0",
                    "--data-dir=/var/lib/etcd",
                    "--initial-advertise-peer-urls=https://9.111.255.77:2380",
                    "--listen-peer-urls=https://0.0.0.0:2380",
                    "--listen-client-urls=https://0.0.0.0:4001",
                    "--advertise-client-urls=https://9.111.255.77:4001",
                    "--cert-file=/etc/cfc/conf/etcd/server.pem",
                    "--key-file=/etc/cfc/conf/etcd/server-key.pem",
                    "--client-cert-auth",
                    "--peer-auto-tls",
                    "--trusted-ca-file=/etc/cfc/conf/etcd/ca.pem",
                    "--initial-cluster-token=etcd-cluster-1",
                    "--initial-cluster=etcd0=https://9.111.255.77:2380",
                    "--grpc-keepalive-timeout=0",
                    "--grpc-keepalive-interval=0",
                    "--snapshot-count=10000",
                    "--initial-cluster-state=new"
                ],
                "image": "ibmcom/etcd:v3.2.14",
                "imagePullPolicy": "IfNotPresent",
                "name": "etcd",
                "volumeMounts": [
                    {
                        "mountPath": "/var/lib/etcd",
                        "name": "data"
                    },
                    {
                        "mountPath": "/etc/cfc/conf/etcd",
                        "name": "etcd-certs"
                    }
                ]
            }
        ],
        "hostNetwork": true,
        "volumes": [
            {
                "hostPath": {
                    "path": "/var/lib/etcd"
                },
                "name": "data"
            },
            {
                "hostPath": {
                    "path": "/etc/cfc/conf/etcd"
                },
                "name": "etcd-certs"
            }
        ]
    }
}
```

But the hostname is using upper name, and when kubelet start the etcd static pod, it will report error as follows:
```
Can't process manifest file "/etc/cfc/pods/etcd.json": invalid pod: [metadata.name: Invalid value: "k8s-etcd-ICP-Master": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*') spec.nodeName: Invalid value: "ICP-Master": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
```

I think that the vsphere should not return upper case hostname, but only lower case hostname.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by yue9944882**
**What this PR does / why we need it**:
Cast appended node name to lowercase when generating static pod name on kubelet starting.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #59801 

**Special notes for your reviewer**:
Not sure about how to deal with other illegal node names e.g. containing invalid no-alphabetic characters. Maybe just let it fail-hard is not a bad idea.
But considering that containing uppercase letter in the hostname is somehow a usual case even in the production environment of some companies, tolerating uppercase and cast it implicitly should be good.

**Release note**:

```release-note
force node name lowercase on static pod name generating
```

### CODE REVIEW

**Review by gyliu513 — COMMENTED** [review]
/lgtm

**Review by gyliu513 — COMMENTED** [review]
Just found that we do not have unit-test for this function, can you please add a unit test for this?

**Comment by yue9944882** [comment]
@errordeveloper I just made some stupid mistake in my previous submit. 
PTAL plz. Thx

**Comment by yue9944882** [comment]
@gyliu513 WDYM？A unittest proving the node name is successfully lowercased？

**Comment by gyliu513** [comment]
@yue9944882 yes, add a new unit test case for the function that you updated

**Comment by yue9944882** [comment]
@gyliu513 PTAL thx😉

**Review by gyliu513 — COMMENTED** [review]
/lgtm

Thanks @yue9944882

**Comment by yue9944882** [comment]
@dchen1107 Do you think about approving this plz?

**Comment by yue9944882** [comment]
@yujuhong @tallclair @Random-Liu Do u think about approving this plz? thx

**Comment by tallclair** [comment]
This seems like it might be a deeper issue. If uppercase node names are allowed, what happens when you have 2 nodes with the same name but different capitalization?

**Comment by gyliu513** [comment]
I prefer that we keep current logic of lower case the host name directly as it is not good to have two same host name in one cluster but different capitalization, please take a look at calico, it is already coverting all host name to lowercase automatically https://github.com/projectcalico/calico/issues/1441#issuecomment-367497385 , comments @yue9944882 @tallclair

**Comment by dchen1107** [comment]
I am ok with current logic, but want to make sure the cause described at https://github.com/kubernetes/kubernetes/pull/59849#issuecomment-367129338 has a explicit error for one of failing static pod. @yue9944882 can you add another tests with two nodes with same name but different capitalization? 

/approve

**Comment by dchen1107** [comment]
I approved this pr, but cancelled lgtm. Once you addressed my comment, please feel free to re-apply lgtm. Thanks!

**Comment by yue9944882** [comment]
@dchen1107 ACK, test added.

**Review by gyliu513 — COMMENTED** [review]
/lgtm

**Pull request merged**
