### PR TITLE
enable race detection on integration tests

### PR DESCRIPTION
**Pull request by mikedanese**
Fix an old TODO

### CODE REVIEW

**Comment by ixdy** [comment]
/lgtm

wonder how (much more) flaky this'll make the integration tests...

**Comment by mikedanese** [comment]
cc @wojtek-t

**Comment by fejta** [comment]
/unassign
@kubernetes/sig-api-machinery-pr-reviews

**Comment by smarterclayton** [comment]
/approve

I haven't seen many flakes caused by race detection except the two Go testing ones which I believe were fixed in 1.8

**Comment by mikedanese** [comment]
Test improvement so including in 1.7

**Pull request merged**
