### PR TITLE
Better handling of ginkgo args in jenkins

### PR DESCRIPTION
**Pull request by thockin**
@wojtek-t

### CODE REVIEW

**Comment by thockin** [comment]
@ixdy 

@davidopp in lieu of quinton

**Comment by wojtek-t** [comment]
Nice fix - LGTM

**Comment by davidopp** [comment]
LGTM

**Comment by thockin** [comment]
@k8s-bot test this please

**Comment by ixdy** [comment]
LGTM, thanks.

**Comment by erictune** [comment]
I'm not merging any code until Jenkins is green for a turn.

**Pull request merged**
