### PR TITLE
Add CentOS bare metal automated deployment guide

### PR DESCRIPTION
**Pull request by kevin-wangzefeng**
Getting started guide to deploy kubernetes with automated scripts on CentOS bare-metal nodes.

ref #12914

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
@nikhiljindal, @derekwaynecarr, @thockin Could you please take a look? Thanks.

**Comment by ashcrow** [comment]
@kevin-wangzefeng I read through it and it makes sense. Seeing that this PR is almost a month old, have you been able to test it more recently?

Re-pining @nikhiljindal, @derekwaynecarr, @thockin

**Comment by thockin** [comment]
I have no context on which to review the contents for accuracy.  Is there a good reviewer I can lean on?

**Comment by kevin-wangzefeng** [comment]
Rebased to latest master and tested, PTAL.

**Comment by kevin-wangzefeng** [comment]
@brendandburns I've refreshed this PR, Could you please take a look? Thanks.

**Comment by tedstirm** [comment]
I went through this guide and just thought I would highlight three issues I ran into when using this deployment. 
* There is no mention to the user that they need to make sure that the flannel option `--iface` gets set correctly. I had to update flannel.sh to add this flag when starting flannel. It would be nice if this option existed in the config-default.sh. I would also highly recommend either linking to or describing how to verify Flannel is configured. Flannel Verification: https://github.com/kubernetes/kubernetes/blob/v1.2.0-alpha.5/docs/getting-started-guides/fedora/flannel_multi_node_cluster.md
* The deployment doesn't install flannel on the master node. This means if the user tries to use the kube-ui addon they won't be able to access it from the url provided by `kubectl cluster-info`.
* To add DNS support the user has to update the kubelet.sh directly. It would be nice if the guide mentions that or added an option to config-default.sh

With the above issues resolved you can pretty much use the deployAddons.sh from the ubuntu cluster setup to add: a kube-system namespace, DNS and the Kube-UI.

I'm not sure if this is the right place to report these issues or not. If it isn't just let me know and I will report these issues elsewhere.

**Comment by kevin-wangzefeng** [comment]
@tedstirm, thanks very much for the feedback. Sorry to tell I haven't got time to update the scripts as well as the guide now, will probably refresh them a few weeks.

**Comment by tedstirm** [comment]
@kevin-wangzefeng No worries.

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

Tests have been pending for 24 hours

**Comment by erictune** [comment]
Let me know when this is ready for review.

**Comment by erictune** [comment]
This will need to be sent as a PR against https://github.com/kubernetes/kubernetes.github.io now.

**Pull request closed without merging**
