### PR TITLE
Arm/fix container security context docs

### PR DESCRIPTION
**Pull request by andrewmelis**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:
Two links were listed to provide more info about security context in
the container documentation. One of the links now permanently
redirects to the other (301 status code). This change removes the
outdated link.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by andrewmelis** [comment]
> This PR [may require API review](https://git.k8s.io/community/sig-architecture/api-review-process.md#what-apis-need-to-be-reviewed).

Although this PR touches several of the core types files, I'm not sure it requires API review as only comments are changed.

Could a maintainer provide some guidance on how to move forward here? I'm happy to take whatever steps are necessary but I also don't want to waste anyone's time.

**Review by neolit123 — COMMENTED** [review]
/lgtm
/ok-to-test

https://kubernetes.io/docs/concepts/policy/security-context/
redirects to
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Comment by andrewmelis** [comment]
Anything I can do to help move this forward? @neolit123

**Comment by neolit123** [comment]
we are soon in code freeze for 1.21.
also, i cannot merge this change. you can try asking in #pr-reviews or #sig-auth on k8s slack.

/unassign

**Pull request merged**
