### PR TITLE
Revert gs://kubernetes-release-dev changes

### PR DESCRIPTION
**Pull request by zmerlynn**
Reverts #28172 & #28193. I honestly can't figure out why this is breaking GKE, but it's the most likely culprit, so let's start here.

[Analytics]()

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @kubernetes/release-maintainers @kubernetes/test-infra-maintainers

**Comment by zmerlynn** [comment]
@david-mcmahon / @mwielgus (k8s WAW) / @k8s-oncall: What do you think about a manual merge for this ASAP? It might be useful to start getting runs. (The green dots are mostly irrelevant - I just checked PR builder manually and it looks fine and the rest aren't going to flag this, I'm pretty sure.)

**Comment by mwielgus** [comment]
Just to confirm - all these changes related only to the continuous integration?

**Comment by zmerlynn** [comment]
Though it looks like the SQ might get it anyways, if it notices.

**Pull request merged**
