### PR TITLE
add OWNERS for client-go

### PR DESCRIPTION
**Pull request by deads2k**
client-go is the source (not a copy) for the generic client libraries we wrote.  This is a copy of the OWNERS file from `pkg/client`.

### CODE REVIEW

**Comment by deads2k** [comment]
@k8s-bot unit test this: issue #39471

**Comment by deads2k** [comment]
@caesarxuchao @lavalamp @krousey

**Comment by deads2k** [comment]
@smarterclayton

**Comment by cblecker** [comment]
@k8s-bot cvm gke e2e test this

**Pull request merged**
