### PR TITLE
Output the same error when using kubectl describe for a nonexisting resource

### PR DESCRIPTION
**Pull request by feihujiang**
@marekbiskup #10532 has been merged, So I created a new commit, and changed according to your advice, Could you please review this new commit?

### CODE REVIEW

**Comment by marekbiskup** [comment]
add to whitelist

**Comment by marekbiskup** [comment]
LGTM

**Comment by marekbiskup** [comment]
@bgrant0607 this is a follow-up from #10532 that unifies error messages for `kubectl describe node asdf` and `node/asdf` (now the error message should be in singular and with exactly the same text).

I suggest we also put it in.

**Comment by bgrant0607** [comment]
Please rebase.

@JanetKuo PTAL

**Comment by feihujiang** [comment]
@bgrant0607  @JanetKuo  Sorry, I'm on a business trip, will be back this Friday, and then I'll do this as soon as possible.

**Comment by JanetKuo** [comment]
LGTM. Please comment after rebasing.

**Comment by feihujiang** [comment]
@JanetKuo  Hi, I have rebased onto the master, please review.

**Pull request merged**
