### PR TITLE
Handle cAdvisor partial failures

### LINKED ISSUE #25131: Pods missing on Grafana/InfluxDB dashboards
Hi,

I'm having a lot of cases in which pods are missing on the Grafana dashboard so I can't view their metrics.

Using kubernetes 1.2.1 on AWS.

Any way to troubleshoot this?

### PR DESCRIPTION
**Pull request by timstclair**
Kubernetes side of https://github.com/google/cadvisor/issues/1286

Partially fixes https://github.com/kubernetes/kubernetes/issues/25131

(Depends on cAdvisor Godeps bump https://github.com/kubernetes/kubernetes/pull/25914)

/cc @kubernetes/sig-node

### CODE REVIEW

**Comment by timstclair** [comment]
Fixed import (`goimports` fail)

**Comment by vishh** [comment]
LGTM

**Comment by vishh** [comment]
@timstclair Can you remove the `do-not-merge` label once #25914 is merged?

**Comment by timstclair** [comment]
Removing do-not-merge since this is just a no-op without the dependent PR

**Pull request merged**
