### PR TITLE
Set MemorySwap to zero on Windows

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes https://github.com/kubernetes/kubernetes/issues/39003

@dchen1107 @michmike @kubernetes/sig-node-misc

### CODE REVIEW

**Review by pires — APPROVED** [review]
This fixes it. However, changes in `pkg/kubelet/dockertools/docker_manager.go` could be refactored into a method and go into `pkg/kubelet/dockertools/docker_manager_windows.go` since it's already there for specific Windows stuff.

**Comment by brendandburns** [comment]
@pires moved to docker_manager_windows as you suggested. please take another look.

**Comment by brendandburns** [comment]
@k8s-bot bazel test this

**Comment by pires** [comment]
@brendandburns LGTM, thanks!

**Comment by feiskyer** [comment]
LGTM

**Comment by yujuhong** [comment]
LGTM

**Comment by vishh** [comment]
@brendandburns while you are here, I think we can set Linux Swap to `0` as well since we do not support Swap!

**Comment by smarterclayton** [comment]
I think this may have broken compile on Mac:

```
    test/e2e_node/e2e_node.test
# k8s.io/kubernetes/pkg/kubelet/dockertools
pkg/kubelet/dockertools/docker_manager_unsupported.go:28: undefined: dockercontainer in dockercontainer.HostConfig
make: *** [all] Error 1
```

and it looks like there are errors related to this in cross-build https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-cross-build/516

**Comment by smarterclayton** [comment]
the windows errors may be unrelated, but docker_manager_unsupported.go is missing an import statement

**Comment by pires** [comment]
Sorry @brendandburns, all but I screwed up big time reviewing this. @vishh I'm going to fix OSX and Windows builds plus address your comment and will ping when I open the new PR.

**Comment by warmchang** [comment]
👍

**Pull request merged**
