### PR TITLE
Remove all MAINTAINER statements in the codebase as they are deprecated

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:
ref: https://github.com/docker/docker/pull/25466

**Release note**:

```release-note
Remove all MAINTAINER statements in Dockerfiles in the codebase as they are deprecated by docker
```
@ixdy @thockin (who else should be notified?)

### CODE REVIEW

**Comment by luxas** [comment]
@k8s-bot cvm gke e2e test this

**Comment by thockin** [comment]
before we lose information, shouldn't we convert all of these to label, as suggested in the Docker deprecation?

**Comment by luxas** [comment]
For me it doesn't matter, this is a machine-generated thing anyway.
Personally, I've never been fond of the MAINTAINER statement, but in such a large project like this it might make sense. What I was thinking when I uploaded this patch with a full removal was that we have the OWNERS files that covers this anyway, the only thing the label would do would be to take up an extra layer per image.

Also, the downside with the label is that it will flow down to images that are based on our images. Additionally, there are some places where there are two names, and as far as I understand we can't do that with a label.
If we do choose the label, we have to standardize on what we should put there. `LABEL maintainer`? `LABEL author`?

@thockin What do you think?

**Comment by thockin** [comment]
LGTM

**Pull request merged**
