### PR TITLE
Use api.Pod and api.Service objects instead of JSON snippets

### PR DESCRIPTION
**Pull request by filbranden**
Additionally, start to use unique names for the pods and services.

Unfortunately, the service name here may not be made unique since that
affects the names of the environment variables that get defined.

Tested by running cmd/e2e -t TestPodHasServiceEnvVars against an API server in GCE.

@satnam6502 @bgrant0607 @thockin @erictune 

@bgrant0607 The problem with using a JSON or YAML is that we need to support variable fields such as the name. JSON interpolation is unacceptable to me, it's akin to using regexps to parse XML. What would be acceptable is to use an internal object/map representation and serialize it to JSON, but then is there really much difference between that and using the internal representation directly?

I'd be willing to use the internal representation for a specific version of the API (v1beta1, v1beta2, v1beta3) and call the conversion method to turn it into the internal representation, would you think that would be acceptable?

@erictune (who originally wrote `TestPodHasServiceEnvVars` in commit 441445fae4c67) I'd like to push for the ability to override the environment variable prefix so that it doesn't need to match the service name exactly. Otherwise if I'm trying to create unique service names then the variable names will be unpredictable. What do you think of that idea?

Thanks,
Filipe

### CODE REVIEW

**Comment by zmerlynn** [comment]
I'd also wait on this one until #3942, out of courtesy, since it will move this test in (per discussion).

**Comment by thockin** [comment]
I think this is OK or at least no worse than a million other instances.

I don't understand the prefix you mean...

**Comment by filbranden** [comment]
@zmerlynn Yeah it's fine to wait, I don't mind rebasing this one.

@thockin If the service is named **fooservice** then the env vars will be called `FOOSERVICE_PORT_xyz`, `FOOSERVICE_HOST` etc. If, on the other hand, the service is called **test-envvars-1234-5678-abcd** (where *1234-5678-abcd* is a uuid-like random substring) then the env vars will be called `TEST_ENVVARS_1234_5678_ABCD_PORT_xyz`, `TEST_ENVVARS_1234_5678_ABCD_HOST`, etc.

I think we should allow a manifest to specify that the service name should be **test-envvars-1234-5678-abcd** but that the env vars should use the `FOOSERVICE_` prefix, in other words, dissociate the prefix of the environment variable names from the name of the service.

The actual exact name of the service could indeed be exposed as one of the environment variables, in case it might be useful.

**Comment by thockin** [comment]
What you are asking for is a significant change - pods do not currently say
anything about the services they depend on.

Isn't this a place where you could randomize the namespace andnot the
service name?

**Comment by filbranden** [comment]
Hmmm, yes, quite possible namespace might be enough.

@satnam6502 what do you think? Maybe we should use fixed service (and pod) names and use a UUID in the namespace of *all* objects a single test uses.

I think that also solves the internal API vs. YAML since if we use a namespace we can still have a YAML file with fixed names. Maybe that would work...

**Comment by zmerlynn** [comment]
See #3973 where @thockin basically proposed this.

**Comment by thockin** [comment]
Yeah, we have namespaces but we hardly use them.  This is what they are for.

**Comment by smarterclayton** [comment]
Yeah, we switched to using namespaces for tests so we could do things in parallel and be sure they wouldn't collide.  A few of our QA teams are doing similar.

**Comment by bgrant0607** [comment]
Yes, you want to use namespaces. That's needed to make things like label selectors work without interference.

**Comment by erictune** [comment]
I think uniqifying namesnis wrong way to go.  Wiping etcd between test runs
is the at to go. Don't try to dual purpose e2e as fuzz test.

**Comment by smarterclayton** [comment]
Although if we had... it would have caught that namespacing was totally broken in a bunch of places :)

----- Original Message -----
> I think uniqifying namesnis wrong way to go.  Wiping etcd between test runs
> is the at to go. Don't try to dual purpose e2e as fuzz test.

**Comment by filbranden** [comment]
Rebased after #3942, PTAL.

**Comment by erictune** [comment]
@smarterclayton agree.  But a test that does unpredictable stuff and finds
interactions is super hard to debug and so supplement to but not a
substitute for individual focused isolated e2e feature tests.

**Comment by filbranden** [comment]
@satnam6502 OK to merge this one?

**Comment by satnam6502** [comment]
Will merge without waiting two hours: I think we've had enough discussion.

**Comment by filbranden** [comment]
Thanks!

**Pull request merged**
