### PR TITLE
Support passing a header to the manifest URL in the kubelet.

### LINKED ISSUE #11982: kubelet should be able to hit GCE's v1 metadata server instead of v1beta1
GCE's v1beta1 metadata API is no longer documented and probably doesn't have a whole lot of life left. However, GCE's container VM image relies on the kubelet to be able to talk to the metadata server when using it as a manifest URL, and is going to need it to continue working. The [v1 metadata API](https://cloud.google.com/compute/docs/metadata?hl=en#querying) requires the caller to specify the HTTP header "Metadata-Flavor: Google".

We need to make the kubelet able to attach this header when talking to the GCE metadata server.

### PR DESCRIPTION
**Pull request by a-robinson**
Needed to support using GCE's v1 metadata API, which requires passing
the header "Metadata-Flavor: Google".

Fixes #11982 and enables #11963 to work.

@brendandburns @roberthbailey @zmerlynn

### CODE REVIEW

**Comment by a-robinson** [comment]
I'm not too attached to the method of doing this by adding a new flag, but it seemed more general than trying to decide based on parsing the manifest URL.

I don't think that just using the cloud provider is sufficient, since it should be a feasible use case to run on GCE and use an HTTP endpoint other than the metadata server.

**Comment by zmerlynn** [comment]
LGTM

**Comment by zmerlynn** [comment]
I assume the Salt changes are going into #11963?

**Comment by a-robinson** [comment]
Yeah, the salt changes will go into the other PR once I can rebase onto this.

I also just added a second commit here to quiet the error logging, so please take another quick look.

**Comment by zmerlynn** [comment]
LGTM

**Comment by zmerlynn** [comment]
@k8s-bot test this (you flake monster)

**Comment by a-robinson** [comment]
Still appears to be a flake, or unrelated at the very least..

**Comment by a-robinson** [comment]
@k8s-bot test this please

**Comment by a-robinson** [comment]
The shippable failure is completely unrelated, although doesn't look like the sort of thing that's a flake, it looks like bad code may have been merged to master recently?
```
# github.com/GoogleCloudPlatform/kubernetes/pkg/runtime_test
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/runtime/conversion_generation_test.go:37: not enough arguments in call to runtime.NewConversionGenerator
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/runtime/conversion_generation_test.go:50: not enough arguments in call to g.RegisterConversionFunctions
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/runtime/deep_copy_generation_test.go:36: not enough arguments in call to runtime.NewDeepCopyGenerator
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/runtime/deep_copy_generation_test.go:50: too many arguments in call to g.WriteImports
```

**Comment by mikedanese** [comment]
@a-robinson #12027

**Comment by a-robinson** [comment]
Thanks, this should be good to merge then.

**Comment by a-robinson** [comment]
@mikedanese can I get a merge soon? This and #11963, which depends on this, need to get into the 1.0 branch before the next patch is cut.

**Comment by a-robinson** [comment]
Thanks!

**Pull request merged**
