### PR TITLE
Align ownership of secret and configmap tests with sig-node

### PR DESCRIPTION
**Pull request by derekwaynecarr**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Aligns ownership of common secret and configmap testing with sig-node.

#### Special notes for your reviewer:
@wojtek-t per discussion on slack in sig-node.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm

Thanks!

**Comment by wojtek-t** [comment]
@derekwaynecarr - actually requires regenerating conformance file
If you won't get to it today, I can do that tomorrow.

**Comment by BenTheElder** [comment]
/hold
(to prevent the bot from auto-retesting, while the tests are going to fail until https://github.com/kubernetes/kubernetes/pull/99410#issuecomment-785348191)

**Pull request closed without merging**
