### PR TITLE
users of watchtools.NewIndexerInformerWatcher should wait for the informer to sync

### PR DESCRIPTION
**Pull request by p0lyn0mial**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
previously users of this method were relying on the fact that a call to LIST was made.
Instead, users should use the dedicated `HasSynced` method.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by wojtek-t — COMMENTED** [review]
Just some small nits - other than that LGTM

**Comment by p0lyn0mial** [comment]
@wojtek-t updated, ptal

**Pull request merged**
