### PR TITLE
WIP: Use vanity gcr.kubernetes.io registry

### PR DESCRIPTION
**Pull request by thockin**
Most of this was automatic, but some was not.  It's a little weird because the vanity domain doesn't need a "user" like docker hub does.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/28425)

### CODE REVIEW

**Comment by luxas** [comment]
Oh, I was just going to ask if we could break out kubernetes-only stuff to another domain than gcr.io/google_containers...

+1

**Comment by fejta** [comment]
LGTM but needs a rebase... Also discussion around whether to use kubernetes.io vs k8s.io?

**Comment by thockin** [comment]
We opted for kubernetes.io because k8s is just "a shortcut".  I'm partly
regretting it.  To switch, I'd have to get a new cert...

This is blocked on a couple bugs in the GCR stack with vanity domains.

**Comment by fejta** [comment]
Okay, let me know when this needs another review!

**Comment by fejta** [comment]
@thockin please assign back to me when this is ready for a review

**Comment by luxas** [comment]
@thockin Will this be a placeholder for `gcr.io/google_containers` or will it be dedicated for k8s (with k8s ACLs)?

**Comment by thockin** [comment]
when this is ready it should be an alias to gcr.io/google_containers, for
easier organization

**Pull request closed without merging**
