### PR TITLE
Made some grammar edits to the README

### PR DESCRIPTION
**Pull request by lmaffeo**
**What type of PR is this?**
> /kind documentation

**What this PR does / why we need it**:
This PR fixes some grammatical errors and inconsistencies that I found in the README introduction. We need it to keep Kubernetes content as accurate, consistent, and readable as we can. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by lmaffeo** [comment]
@k8s-ci-robot I have signed the CNCF CLA and attached it here:
[CNCF_Individual_Contributor_License_Agreement.pdf](https://github.com/kubernetes/kubernetes/files/3558194/CNCF_Individual_Contributor_License_Agreement.pdf)

**Comment by Adirio** [comment]
/kind cleanup
IMO you are just changin how things are written, but they weren't wrong previosuly.

**Comment by zacharysarah** [comment]
@lmaffeo 👋 Welcome to Kubernetes! Thanks for this PR, it's a helpful improvement. ✨ 

/lgtm
/approve

**Comment by nikhita** [comment]
/sig docs

/assign @liggitt 
for approval

**Comment by nikhita** [comment]
FYI I've updated the main PR body to remove the release note.

**Pull request merged**
