### PR TITLE
replace err with nil when err is nil

### PR DESCRIPTION
**Pull request by tanshanshan**
**What this PR does / why we need it**:

When err is nil ,replace err with nil, that can make code more readable

Thanks.
**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot cvm gce e2e test this

**Comment by mikedanese** [comment]
@k8s-bot cvm gce e2e test this

**Comment by rmmh** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
