### PR TITLE
Fix golint failures for e2e/[..]/kubemark

### PR DESCRIPTION
**Pull request by oomichi**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This fixes golint failures under test/e2e/framework/providers/kubemark.

ref: https://github.com/kubernetes/kubernetes/issues/68026

**Does this PR introduce a user-facing change?**:

```release-note-none

```

### CODE REVIEW

**Comment by oomichi** [comment]
@fejta Could you take a look at this?
I am trying to fix the failures under test/e2e/framework.
After this, we'll just have 2 remaining.

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve 

same comment that this will land in 1.15

**Pull request merged**
