### PR TITLE
add role/clusterrole to describe.go

### PR DESCRIPTION
**Pull request by xilabao**
**What this PR does / why we need it**:
```
# ./cluster/kubectl.sh describe clusterrole system:kube-scheduler 
Name:		system:kube-scheduler
Labels:		kubernetes.io/bootstrapping=rbac-defaults
Annotations:	rbac.authorization.kubernetes.io/autoupdate=true
PolicyRule:
  Resources			Non-Resource URLs	Resource Names		Verbs
  ---------			-----------------	--------------		-----
  bindings			[]			[]			[create]
  endpoints			[]			[]			[create]
  endpoints			[]			[kube-scheduler]	[delete]
  endpoints			[]			[kube-scheduler]	[get]
  endpoints			[]			[kube-scheduler]	[patch]
  endpoints			[]			[kube-scheduler]	[update]
  events			[]			[]			[create patch update]
  nodes				[]			[]			[get list watch]
  persistentvolumeclaims	[]			[]			[get list watch]
  persistentvolumes		[]			[]			[get list watch]
  pods				[]			[]			[get list watch]
  pods/binding			[]			[]			[create]
  pods/status			[]			[]			[update]
  replicasets.extensions	[]			[]			[get list watch]
  replicationcontrollers	[]			[]			[get list watch]
  services			[]			[]			[get list watch]
  statefulsets.apps		[]			[]			[get list watch]

```
**Which issue this PR fixes**: 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by eparis** [comment]
@k8s-bot ok to test
/release-note-none

**Comment by deads2k** [comment]
I think we should present user readable names and categorize rules along resources.  @liggitt got a link to the way we do it openshift so @xilabao can port it upstream?

**Comment by liggitt** [comment]
1. first we break down rules into simple rules (upstream version already in kubernetes at https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/rbac/validation/policy_comparator.go#L58)

2. then we compact those rules by combining rules differ only by verb: https://github.com/openshift/origin/blob/master/pkg/authorization/rulevalidation/compact_rules.go#L16

3. then we print pretty versions of each of the resulting rules: https://github.com/openshift/origin/blob/master/pkg/authorization/api/helpers.go#L77

**Comment by xilabao** [comment]
finished. @deads2k @liggitt PTAL
```
# ./cluster/kubectl.sh describe clusterrole view       
Name:		view
Labels:		kubernetes.io/bootstrapping=rbac-defaults
Annotations:	rbac.authorization.kubernetes.io/autoupdate=true
PolicyRule:
  Resources				Non-Resource URLs	Resource Names	API Groups	Verbs
  ---------				-----------------	--------------	----------	-----
  [bindings]				[]			[]		[]		[get list watch]
  [configmaps]				[]			[]		[]		[get list watch]
  [cronjobs]				[]			[]		[batch]		[get list watch]
  [daemonsets]				[]			[]		[extensions]	[get list watch]
  [deployments]				[]			[]		[apps]		[get list watch]
  [deployments]				[]			[]		[extensions]	[get list watch]
  [deployments/scale]			[]			[]		[apps]		[get list watch]
  [deployments/scale]			[]			[]		[extensions]	[get list watch]
  [endpoints]				[]			[]		[]		[get list watch]
  [events]				[]			[]		[]		[get list watch]
  [horizontalpodautoscalers]		[]			[]		[autoscaling]	[get list watch]
  [ingresses]				[]			[]		[extensions]	[get list watch]
  [jobs]				[]			[]		[batch]		[get list watch]
  [limitranges]				[]			[]		[]		[get list watch]
  [namespaces]				[]			[]		[]		[get list watch]
  [namespaces/status]			[]			[]		[]		[get list watch]
  [persistentvolumeclaims]		[]			[]		[]		[get list watch]
  [pods]				[]			[]		[]		[get list watch]
  [pods/log]				[]			[]		[]		[get list watch]
  [pods/status]				[]			[]		[]		[get list watch]
  [replicasets]				[]			[]		[extensions]	[get list watch]
  [replicasets/scale]			[]			[]		[extensions]	[get list watch]
  [replicationcontrollers]		[]			[]		[]		[get list watch]
  [replicationcontrollers/scale]	[]			[]		[]		[get list watch]
  [replicationcontrollers/scale]	[]			[]		[extensions]	[get list watch]
  [replicationcontrollers/status]	[]			[]		[]		[get list watch]
  [resourcequotas]			[]			[]		[]		[get list watch]
  [resourcequotas/status]		[]			[]		[]		[get list watch]
  [scheduledjobs]			[]			[]		[batch]		[get list watch]
  [serviceaccounts]			[]			[]		[]		[get list watch]
  [services]				[]			[]		[]		[get list watch]
  [statefulsets]			[]			[]		[apps]		[get list watch]
```

**Comment by xilabao** [comment]
@k8s-bot pull-kubernetes-verify test this

**Comment by xilabao** [comment]
@k8s-bot pull-kubernetes-unit test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by xilabao** [comment]
change the resource column. @deads2k PTAL. 
BTW, @smarterclayton  could you approve the pr? thx. 
```
# ./cluster/kubectl.sh describe clusterrole view   
Name:		view
Labels:		kubernetes.io/bootstrapping=rbac-defaults
Annotations:	rbac.authorization.kubernetes.io/autoupdate=true
PolicyRule:
  Resources					Non-Resource URLs	Resource Names	Verbs
  ---------					-----------------	--------------	-----
  bindings					[]			[]		[get list watch]
  configmaps					[]			[]		[get list watch]
  cronjobs.batch				[]			[]		[get list watch]
  daemonsets.extensions				[]			[]		[get list watch]
  deployments.apps				[]			[]		[get list watch]
  deployments.extensions			[]			[]		[get list watch]
  deployments.apps/scale			[]			[]		[get list watch]
  deployments.extensions/scale			[]			[]		[get list watch]
  endpoints					[]			[]		[get list watch]
  events					[]			[]		[get list watch]
  horizontalpodautoscalers.autoscaling		[]			[]		[get list watch]
  ingresses.extensions				[]			[]		[get list watch]
  jobs.batch					[]			[]		[get list watch]
  limitranges					[]			[]		[get list watch]
  namespaces					[]			[]		[get list watch]
  namespaces/status				[]			[]		[get list watch]
  persistentvolumeclaims			[]			[]		[get list watch]
  pods						[]			[]		[get list watch]
  pods/log					[]			[]		[get list watch]
  pods/status					[]			[]		[get list watch]
  replicasets.extensions			[]			[]		[get list watch]
  replicasets.extensions/scale			[]			[]		[get list watch]
  replicationcontrollers			[]			[]		[get list watch]
  replicationcontrollers/scale			[]			[]		[get list watch]
  replicationcontrollers.extensions/scale	[]			[]		[get list watch]
  replicationcontrollers/status			[]			[]		[get list watch]
  resourcequotas				[]			[]		[get list watch]
  resourcequotas/status				[]			[]		[get list watch]
  scheduledjobs.batch				[]			[]		[get list watch]
  serviceaccounts				[]			[]		[get list watch]
  services					[]			[]		[get list watch]
  statefulsets.apps				[]			[]		[get list watch]
```

**Comment by deads2k** [comment]
/lgtm

change to helpers, not the api, approving.

**Pull request merged**
