### PR TITLE
Update Web UI Explore page

### PR DESCRIPTION
**Pull request by bcbroussard**
Hide blank label drop downs
Escape characters in group descriptions
Update label selectors

screen shot 2015-06-29 at 3 18 08 pm

cc @jackgr @bgrant0607 @lavalamp

### CODE REVIEW

**Comment by bcbroussard** [comment]
This is a low risk change, ok for v1

**Comment by bcbroussard** [comment]
@jackgr and @bgrant0607 had requested these changes in an offline discussion

**Comment by bgrant0607** [comment]
The labelSelector fix is part of the update to v1beta3/v1 that was previously missed, I assume.

**Comment by bcbroussard** [comment]
@bgrant0607 yes, I updated `label=` query to `labelSelector=`

**Comment by bgrant0607** [comment]
LGTM. 

@bcbroussard do you still want to merge this given that the UI has moved to kubernetes-ui/kube-ui?

**Comment by bcbroussard** [comment]
@bgrant0607 That depends how soon you think it will move over. From your comments on https://github.com/GoogleCloudPlatform/kubernetes/pull/10077#issuecomment-117707925, it seems it could be a little while. If that is the case, I'd vote to continue merging here until we have a cut-over date in sight.

What do you think?

**Comment by lavalamp** [comment]
OK, we're going to cut a container for the UI soon, today. So this needs to get merged ASAP if it's going to make it.

**Comment by preillyme** [comment]
LGTM

**Pull request merged**
