### PR TITLE
Add milestone tag clarifications

### PR DESCRIPTION
**Pull request by goltermann**
Add Milestone details to our issues page that defines Priority

### CODE REVIEW

**Comment by goltermann** [comment]
It's not clear why I didn't get a CLA label.  I'm in the Google organization and have committed plenty of things before.

**Comment by goltermann** [comment]
I signed it!

**Comment by bgrant0607** [comment]
LGTM, thanks

**Comment by dchen1107** [comment]
Manually merged this pr since it only touched devel doc

**Pull request merged**
