### PR TITLE
etcd: Build image v3.5.12

### PR DESCRIPTION
**Pull request by bzsuni**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Build image [v3.5.12](https://github.com/etcd-io/etcd/releases/tag/v3.5.12)
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Build etcd image v3.5.12
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
none
```

### CODE REVIEW

**Comment by mzaian** [comment]
Hello @bzsuni
 
Please update the release-note

/retest

**Review by justaugustus — APPROVED** [review]
/retest-required
/lgtm
/approve

**Comment by bzsuni** [comment]
> Hello @bzsuni
> 
>  
> 
> Please update the release-note
> 
> 
> 
> /retest 

Done. Thanks

**Comment by pacoxu** [comment]
/hold
as https://github.com/kubernetes/kubernetes/issues/123127 will fail `pull-kubernetes-node-e2e-containerd` which is required CI.

**Comment by pacoxu** [comment]
Etcd 3.5.12 fixed some bugs, and should this be cherry-picked to v1.26~1.29? @ahrtr @serathius

**Comment by ahrtr** [comment]
> Etcd 3.5.12 fixed some bugs, and should this be cherry-picked to v1.26~1.29? @ahrtr @serathius

Yes, it's always recommended to bump to the latest version.

**Comment by pacoxu** [comment]
This PR is for the image build. 

And https://github.com/kubernetes/kubernetes/pull/123150 needs check-pick.

**Pull request merged**
