### PR TITLE
rkt: remove rkt image manager.

### PR DESCRIPTION
**Pull request by yifan-gu**
This removes the dead code of rkt image manager as the generic
image manager is being used.

cc @dchen1107 @jonboulle @yujuhong

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM

**Comment by jonboulle** [comment]
LGTM

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Pull request merged**
