### PR TITLE
Revert "Enable CoreDNS as default for kube-up deployments"

### PR DESCRIPTION
**Pull request by shyamjvs**
Reverts kubernetes/kubernetes#67569

Because of https://github.com/kubernetes/kubernetes/issues/68613

/cc @wojtek-t @chrisohaver @thockin @bowei 
/sig network
/sig scalability
/kind bug
/priority critical-urgent
/milestone v1.12
/status approved-for-milestone

```release-note
Use KubeDNS by default in GCE setups, as CoreDNS has significantly higher memory usage in large clusters.
```

### CODE REVIEW

**Comment by tpepper** [comment]
please let's give the diagnosis and fix discussion a little time before moving forward with revert

**Comment by wojtek-t** [comment]
> please let's give the diagnosis and fix discussion a little time before moving forward with revert

I don't actually agree with that - see this:
https://github.com/kubernetes/kubernetes/issues/68613#issuecomment-421099236

Also, according to our charter approved by steering-committed:
https://github.com/kubernetes/community/blob/master/sig-scalability/charter.md

we have a right to revert a PR that is causing SLO violation (which is exactly the case here).

**Comment by tpepper** [comment]
I was merely looking for the discussion to reach a clear decision in #68613 with stakeholder input.  Certainly you can revert according to your charter and even apparently without any other stakeholder input.  Only looking for an hour or two to get a broad set of folks into the #68613 discussion.  Does a revert have any other implications to others?

**Comment by wojtek-t** [comment]
> I was merely looking for the discussion to reach a clear decision in #68613 with stakeholder input. Certainly you can revert according to your charter and even apparently without any other stakeholder input. Only looking for an hour or two to get a broad set of folks into the #68613 discussion. Does a revert have any other implications to others?

That's why I didn't revert it in the morning - I wanted to make everyone on the same page.
[And I didn't remove the "hold" label yet].

>  Does a revert have any other implications to others?

We are only reverting default in one of the deployment tools. So I think it shouldn't.
I think the only implication is that we may want to switch some documentation to reflect that we don't have full convincement that it meets our scalability/performance requirements.

**Comment by wojtek-t** [comment]
> This revert scoped local to cluster/gce/*, are you ok that we'd still be declaring CoreDNS stable/ga default for kubernetes broadly, but I presume then changing this PR to have a release note indicating the issue. I'm ok with that.

I guess I may be fine with declaring it GA with a "star" referring to this issue.
Whether we want to announce it as default broadly is debatable - I would probably like to hear opinions of @kubernetes/sig-network-bugs  on that (@thockin @bowei others)

> Would we leave #68613 open, drop /priority and /milestone, and triage further once master thaws for 1.13?

Yes - definitely.

**Comment by rajansandeep** [comment]
The last 2 runs look like legit errors. 
Or this test is super flaky.

**Comment by tpepper** [comment]
I think it's flaking provider underneath the test.  First fails were early build.  Later look like a common yet inconsistent symptom we're chasing in other issues for the release.

**Comment by tpepper** [comment]
I continue to think this looks like underlying issues unrelated to the patch.  The failure details are different each time.  Just rolling dice here hoping to have it merged ahead of next scale test runs Friday.  :(

/test pull-kubernetes-e2e-gke

I've opened issue #68653 to track.

**Comment by wojtek-t** [comment]
Given that we want to verify our scalability tests with this PR and enabling re-revert for experimenting further, I'm merging this manually before today's run will start.
I consider the risk to be very small.

**Comment by shyamjvs** [comment]
Thanks Wojtek! +1 to that decision.

**Comment by tpepper** [comment]
This issue never got its release not update.

**Comment by wojtek-t** [comment]
> This issue never got its release not update.

What do you mean?

**Comment by spiffxp** [comment]
> What do you mean?

CoreDNS is no longer the default for kube-up deployments, but the release notes may not reflect that since this has `NONE` in its release notes block

**Comment by tpepper** [comment]
Gah.  What a difference an 'e' makes,  edited above:
```This issue never got its release not update.```
---> as per Aaron's translation
```This issue never got its release note update.```

We want to release note if we think there's a problem with CoreDNS, since it is the default elsewhere.

**Comment by wojtek-t** [comment]
@tpepper - I added release note - please let me know if that look reasonable to you.

**Comment by chrisohaver** [comment]
How do we modify an existing release note? Now that we have more data, we can qualify the note better.

**Comment by chrisohaver** [comment]
`Use KubeDNS by default in GCE setups, as CoreDNS has significantly higher memory usage in large clusters.`

Is this how the release note is going out?  The data we have collected shows that CoreDNS uses less memory than kube-dns in clusters less than 2300 nodes.  And at 5000 nodes, CoreDNS uses about 10% more memory than kube-dns.

**Comment by tpepper** [comment]
No that's stale.  Current draft is in
https://docs.google.com/document/d/1hUtktrIewcsLTmVD8RYp1zcefvbf36Ww0GMjHSRozZc/edit
and is:

```
Feature #566 <https://github.com/kubernetes/kubernetes/issues/566> enabling
CoreDNS as the default for kube-up deployments was dropped from the release
due to a scalability memory resource consumption issue observed. The root
cause in CoreDNS remains unclear, but CoreDNS folks are investigating. If a
cluster operator is considering using CoreDNS on a cluster greater than
1000 nodes, it may be necessary to give more consideration to CoreDNS pod
memory resource limits and experimentally measure that memory usage versus
cluster resource availability.
```

Sounds like that number now needs updated. Please suggest in line in doc
linked above ^^^

**Pull request merged**
