### PR TITLE
Support validating package versions in node conformance test

### PR DESCRIPTION
**Pull request by yguo0905**
ref: https://github.com/kubernetes/kubernetes/issues/46891

**What this PR does / why we need it**:

This PR adds a package validator in node conformance test for checking whether the locally installed packages meet the image spec.

**Special notes for your reviewer**:

The image spec for GKE (which has the package spec) will be in a separate PR. Then we will publish a new node conformance test image for GKE whose name should use the convention in https://github.com/kubernetes/kubernetes/issues/45760 and have `gke` in it.

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by yguo0905** [comment]
@dchen1107

**Comment by dchen1107** [comment]
Can we switch the existing node conformance test to use this new package validator? A separate pr should be ok.

/lgtm

**Comment by dchen1107** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by dchen1107** [comment]
@k8s-bot pull-kubernetes-verify test this

**Comment by yguo0905** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by yguo0905** [comment]
@dchen1107, the test failed because of a godep issue on updating the semver version. I've fixed it in the "Update semver to 3.5.0" commit -- the "Support validating package versions in node conformance test" commit is unchanged. PTAL.

**Comment by yguo0905** [comment]
@k8s-bot pull-kubernetes-unit test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by yguo0905** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this
@k8s-bot pull-kubernetes-verify test this

**Pull request merged**
