### PR TITLE
Make CRI logs parsing to a library

### LINKED ISSUE #55136: Make CRI logs parsing to a library
We should make the CRI log parsing code in kubelet to be a library. So that container runtimes and external tools don't need to copy the whole code ( vendor it instead ).

Referring https://github.com/kubernetes-incubator/cri-tools/issues/169.

### PR DESCRIPTION
**Pull request by feiskyer**
**What this PR does / why we need it**:
Make CRI logs parsing to a library.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #55136

**Special notes for your reviewer**:

**Release note**:

```release-note
Add CRI log parsing library at pkg/kubelet/apis/cri/logs
```

### CODE REVIEW

**Comment by Random-Liu** [comment]
@feiskyer Will look at this today.

**Comment by Random-Liu** [comment]
Should this be in `apis/cri`? I don't think this is part of "api", right?

I think it's fine to just put it into `pkg/kubelet/kuberuntime/logs`. Just like streaming server, it's also part of cri, and it's in `pkg/kubelet/server/streaming`.

**Comment by feiskyer** [comment]
@Random-Liu Updated. PTAL

**Pull request merged**
