### PR TITLE
kubeadm: Bump minimum supported versions and add etcd version for 1.2…

### PR DESCRIPTION
**Pull request by EricWvi**
#### What type of PR is this?
/kind cleanup

With great pleasure to contribute to Kubernetes!

#### Which issue(s) this PR fixes:
kubernetes/kubeadm#2539

Clean up 1.23 housekeeping tasks:

Bump minimum supported versions and add etcd version for 1.23 and placeholder for 1.24
Does this PR introduce a user-facing change?
```
None
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```
None
```

### CODE REVIEW

**Comment by EricWvi** [comment]
#### What type of PR is this?
/kind cleanup

With great pleasure to contribute to Kubernetes!

#### What this PR does / why we need it:
#### Which issue(s) this PR fixes:
kubernetes/kubeadm#2539

Clean up 1.23 housekeeping tasks:

Bump minimum supported versions and add etcd version for 1.23 and placeholder for 1.24
Does this PR introduce a user-facing change?
```
None
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```
None
```

**Comment by neolit123** [comment]
thanks for the PR but this is no longer needed.

https://github.com/kubernetes/kubeadm/issues/2539

like i said on the issue:
> NOTE !!! this is no longer needed once we merge:
> ...

let me edit that.

there is a function in kubeadm that returns the min/max etcd for a version:
https://github.com/kubernetes/kubernetes/blob/332488aae4399dde6f983a429d564fa8aa42d77e/cmd/kubeadm/app/constants/constants.go#L491

we can update the etcd version only once etcd is updated.

/close

**Comment by pacoxu** [comment]
After #104116 is merged, you may bump the version to 3.5.0-1 and add the 1.24 placeholder as well.

BTW, files that are mentioned in https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml#L79-L93, should be updated as well.

**Comment by neolit123** [comment]
Does that mean that someone need to push / promote the new etcd image first?

On the side of kubeadm we should also cleanup the etcd map versions a
little. The 1.23 binary should contain a map with1.20 min, 1.23 max.

**Pull request closed without merging**
