### PR TITLE
Fix typo in docker_sandbox.go

### PR DESCRIPTION
**Pull request by oshothebig**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR fixes a typo found in `pkg/kubelet/dockershim/docker_sandbox.go`

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/ok-to-test
/assign @random-liu
/lgtm

Thanks!

**Comment by oshothebig** [comment]
Thank you for reviewing the PR. After rebasing to the latest master, the PR passed `pull-kubernetes-integration`.

**Comment by oshothebig** [comment]
@Random-Liu Could you review the Pull Request?

**Pull request merged**
