### PR TITLE
Remove spurious vendordiff.patch file

### PR DESCRIPTION
**Pull request by jpbetz**
Was accidentally committed during a large vendor change as part of https://github.com/kubernetes/kubernetes/pull/69322

```release-note
NONE
```

/sig api-machinery
/kind cleanup

### CODE REVIEW

**Comment by dims** [comment]
i was wondering how/why it got in there :)

/lgtm

**Comment by lavalamp** [comment]
/approve

happens to the best of us :)

**Comment by dims** [comment]
we could add a `hack/verify-vendordiff.sh` ? :)

**Pull request merged**
