### PR TITLE
Ubuntu: download client and server tarballs instead of mondo-tarball

### PR DESCRIPTION
**Pull request by ixdy**
Part of #28629 / #28435.

This should be functionally the same, except that you will download ~1/3 the bytes.

cc @WIZARD-CXY

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34371)

### CODE REVIEW

**Comment by techtonik** [comment]
These binaries can not be discovered by users. Why are they not available from GitHub?

**Comment by resouer** [comment]
Thanks.  LGTM 

But seems need to find someone to approve

**Review by resouer — APPROVED** [review]

**Comment by resouer** [comment]
And please re-run the failing tests please? They are flaky I suppose.

**Comment by techtonik** [comment]
@k8s-bot kubemark e2e test this
@k8s-bot gci gce e2e test this

**Comment by techtonik** [comment]
@kubernetes/test-infra-maintainers, @k8s-bot doesn't listen to me. Does it talk only to his owners and their friends?

**Comment by resouer** [comment]
@k8s-bot kubemark e2e test this

**Comment by resouer** [comment]
@k8s-bot gci gce e2e test this

**Comment by resouer** [comment]
Comment one by one, be kind to the bot :) 

And I think @ixdy should have write permission?

**Comment by ixdy** [comment]
@k8s-bot gci gce e2e test this

**Comment by ixdy** [comment]
@techtonik you're right that these are undiscoverable, and that's good feedback. I intend to have the release announcements/notes link to the binaries on GCS, and will prioritize fixing that.

**Comment by WIZARD-CXY** [comment]
cool

**Pull request merged**
