### PR TITLE
Print a more helpful error message when failing to start rolling-updates

### PR DESCRIPTION
**Pull request by ixdy**
Hopefully this will help us track down where the 1.3 -> 1.4 upgrades are breaking down. We'll need to cherry-pick this into release-1.4 to have any effect, though.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33122)

### CODE REVIEW

**Comment by davidopp** [comment]
I'm going to remove cherrypick label on the assumption that deleting the project solves the problem.

ref/ #32708

**Comment by ixdy** [comment]
Updated this PR once again to print a better error message (and `gcloud` output) if we fail to start a rolling-update.

**Comment by ixdy** [comment]
Not tested (hopefully not buggy). Probably still want to cherrypick this to 1.4.

**Comment by davidopp** [comment]
ref/ #32466

**Comment by ixdy** [comment]
@k8s-bot kubemark test this please, issue #IGNORE

**Comment by ixdy** [comment]
ping?

not super important for 1.4, but it'd probably still be a good idea to get this in.

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
