### PR TITLE
ipv6 support: addr scope should be global or site

### PR DESCRIPTION
**Pull request by pacoxu**
## What type of PR is this?
/kind bug

## What this PR does / why we need it:

When I use fefe:ffff:1::100 as default ipv6 pool with calico， the pod ip cannot be shown in pod spec. These ipv6 addr are with site scope, not global scope. 

However, it seems that site is deprecated but still can used inside cluster. 
Since https://tools.ietf.org/html/rfc3879, deprecating Site Local Addresses, I'm not sure whether we should support site ipv6 ip.

## Additional documentation 
I tried calico dual stack mode with kubernetes and my ipv6 addr cannot be shown in pod spec.

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if27: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether 36:10:b4:f4:03:c0 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.29.125.4/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fefe:ffff::ff3b:3eea:d343/128 scope site
       valid_lft forever preferred_lft forever
    inet6 fe80::3410:b4ff:fef4:3c0/64 scope link
       valid_lft forever preferred_lft forever
```

After looking into the code, I find the ipv6 address of calico pod is scope site(in another environement, the scop is global and this one is site in ipv6 dual stack.

According to https://serverfault.com/questions/63014/ip-address-scope-parameter, I think both global and site should be accepted here. Calico
> from http://linux-ip.net/html/tools-ip-address.html :
> 
> Scope | Description
> global | valid everywhere
> site | valid only within this site (IPv6)
> link | valid only on this device
> host | valid only inside this host (machine)

``` release note
fixes of bugs which have not been released
```

Signed-off-by: pacoxu <paco.xu@daocloud.io>

### CODE REVIEW

**Comment by pacoxu** [comment]
from https://github.com/kubernetes/kubernetes/pull/89251

According to https://github.com/kubernetes/kubernetes/pull/89251#issuecomment-601397169 message, site will be depreacated, but can be used now.

**Comment by aojea** [comment]
> The PR contained something else, so I open a new PR, based on #89251
> 
> According to [#89251 (comment)](https://github.com/kubernetes/kubernetes/pull/89251#issuecomment-601397169) message, site will be depreacated, but can be used now.

We should take into account that this change is only affecting dockershim, what happens if we use CRI-O or containerd instead?

**Pull request closed without merging**
