### PR TITLE
Reduce calling getNodeName() to improve kubelet code

### PR DESCRIPTION
**Pull request by FengyunPan**
None

### CODE REVIEW

**Comment by NickrenREN** [comment]
same as #40347

**Comment by jianglingxia** [comment]
can you help me that a question:the node name come from where?
I read the code that the func 
nodeName, err := getNodeName(cloud, nodeutil.GetHostname(s.HostnameOverride))
if the cloud is not nil that run the func
instances, ok := cloud.Instances()
and nodeName, err := instances.CurrentNodeName(hostname)
but the CurrentNodeName run the getMetadata fun then return the md.Name,why it know which one vm?I can not understand this?thanks for your reply,thanks very  @FengyunPan 
func (i *Instances) CurrentNodeName(hostname string) (types.NodeName, error) {
	md, err := getMetadata()
	if err != nil {
		return "", err
	}
	return types.NodeName(md.Name), nil
}

**Pull request closed without merging**
