### PR TITLE
Fix condition for deleting master etcd firewall rule

### PR DESCRIPTION
**Pull request by ixdy**
Fix tiny bug in #33094.

cc @fgrzadkowski @jszczepkowski

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33963)

### CODE REVIEW

**Comment by ixdy** [comment]
@k8s-bot gci gke e2e test this
@k8s-bot unit test this

**Comment by ixdy** [comment]
@k8s-bot unit test this, issue #33880

**Comment by fgrzadkowski** [comment]
Thanks for the fix!

LGTM

**Pull request merged**
