### PR TITLE
Move rest handler of subresources of pod to rest package

### PR DESCRIPTION
**Pull request by feihujiang**
Ref #12207

### CODE REVIEW

**Comment by feihujiang** [comment]
@k8s-bot test this please

**Comment by liggitt** [comment]
cc @csrwng

**Comment by csrwng** [comment]
I'd prefer to see separate go files  for each subresource in the rest package. That way it's more obvious what's there.

**Comment by lavalamp** [comment]
LGTM-- @csrwng's suggestion is good but I won't block this on it.

**Comment by feihujiang** [comment]
@k8s-bot test this please
@k8s-bot unit test this

**Comment by feihujiang** [comment]
@k8s-bot test this please

**Pull request merged**
