### PR TITLE
Automated cherry pick of #123003: bugfix: dont skip reconcile for unchanged policy if last sync

### PR DESCRIPTION
**Pull request by ritazh**
Cherry pick of #123003 on release-1.28.

#123003: bugfix: dont skip reconcile for unchanged policy if last sync

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by jiahuif** [comment]
/lgtm
/triage accepted
@kubernetes/release-managers For cherrypick

**Comment by ritazh** [comment]
@kubernetes/release-managers For cherrypick

**Comment by ritazh** [comment]
@alexzielenski approved this here https://github.com/kubernetes/kubernetes/pull/123477#issuecomment-1964927196 
can another approver pls approve
@cici37

**Comment by cici37** [comment]
Approve the cherry pick since backport to 1.29 has been approved in https://github.com/kubernetes/kubernetes/pull/123080

**Pull request merged**
