### PR TITLE
Add runtime handler field to ImageSpec struct

### PR DESCRIPTION
**Pull request by kiashok**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
This PR brings in CRI changes needed for KEP [4216](https://github.com/kubernetes/enhancements/issues/4216)  .
New runtime handler field is added to ImageSpec struct

#### Which issue(s) this PR fixes:
Addresses CRI changes needed for KEP  4216

Fixes #

#### Does this PR introduce a user-facing change?
No 

```release-note
CRI: support image pull per runtime class
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
[KEP 4126]: https://github.com/kubernetes/enhancements/pull/4217/commits/51df9e2d2bc391e43000da7221a4955fcaa82012

```

### CODE REVIEW

**Comment by kiashok** [comment]
cc @jsturtevant @marosset @aravindhp @mikebrow @mrunalp @haircommander

**Comment by kiashok** [comment]
> /lgtm /assign @mrunalp @SergeyKanzhelev

@mrunalp @SergeyKanzhelev could you take a look at this PR when you have some time please?

**Comment by pacoxu** [comment]
/release-note-edit
```release-note
CRI: support image pull per runtime class
```

Would you update the CRI-API changelog https://github.com/kubernetes/kubernetes/blob/afc302c2d24fea7be7d6af33c79fdb81e1a33131/staging/src/k8s.io/cri-api/README.md#change-history?

**Comment by kiashok** [comment]
> /release-note-edit
> 
> ```
> CRI: support image pull per runtime class
> ```
> 
> Would you update the CRI-API changelog https://github.com/kubernetes/kubernetes/blob/afc302c2d24fea7be7d6af33c79fdb81e1a33131/staging/src/k8s.io/cri-api/README.md#change-history?

update the PR with this change.

**Review by mikebrow — APPROVED** [review]
/lgtm

**Review by haircommander — APPROVED** [review]

**Comment by sftim** [comment]
Changelog suggestion
```suggestion
CRI: Added support for pulling container images per runtime class
```

**Pull request merged**
