### PR TITLE
Convert kubelet and proxy to hyperkube

### PR DESCRIPTION
**Pull request by jbeda**
This is part of #108.

Next up is to change salt to use the combined binary.

### CODE REVIEW

**Comment by jbeda** [comment]
Running e2e now.

**Comment by smarterclayton** [comment]
First pass looks good to me, didn't have time to dig very far though.

**Comment by jbeda** [comment]
e2e passes no problem.

**Comment by bgrant0607** [comment]
Sorry, too many meetings. Will try to look soon. Took a quick look and didn't see major problems if someone wants to merge.

**Comment by bgrant0607** [comment]
There are additional improvements that could be made, but this seems like a reasonable step. LGTM.

**Pull request merged**
