### PR TITLE
code-generator: add myself to OWNERS

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by MHBauer** [comment]
Is this where all the `*-gen` is now? For 1.8-release? 

What's the sync policy with https://github.com/kubernetes/code-generator?

Is there a transition policy for existing users?

Should this just be a drop-in replacement for commands that existed in `kubernetes/cmd/libs/go2idl/`?

Where's the best place to ask these questions and stay in sync?

**Comment by sttts** [comment]
@MHBauer: yes, https://github.com/kubernetes/code-generator is a drop-in for `kubernetes/cmd/libs/go2idl/`. It still lives in the staging directory and therefore is published nightly to the external repo (with the side-note that the export bot is broken right now, we are working on getting it running again).

There is no transition period to existing users. We do not give any compatibility guarantees for code, especially not inside of kube (client-go has some pseudo semver). But as this is a drop-in and makes the vendoring life for many people a lot easier, this should not be a problem.

**Comment by sttts** [comment]
> Where's the best place to ask these questions and stay in sync?

It's traditionally part of sig-apimachinery.

**Comment by wojtek-t** [comment]
LGTM

I will let Daniel actually tag it. @lavalamp

**Comment by lavalamp** [comment]
I will LGTM this if you will fix https://github.com/kubernetes/code-generator/issues/1

;)

**Comment by sttts** [comment]
> I will LGTM this if you will fix kubernetes/code-generator#1
> 
> ;)

That's a fair deal :)

**Pull request merged**
