### PR TITLE
Add Cinder volume plugin attach tests.

### PR DESCRIPTION
**Pull request by jsafrane**
@kubernetes/sig-storage

### CODE REVIEW

**Comment by jsafrane** [comment]
@rootfs, you're already reviewing #27280, this should be a breeze.

There is one thing I do not like there - why `Attach`/`Detach` calls `InstanceID(hostname)`? All other cloud providers do not need it and use the name provided by the caller as instanceID. It complicates the tests quite a bit.

**Comment by rootfs** [comment]
LGTM thanks!

**Comment by rootfs** [comment]
@jsafrane Unlike AWS, on openstack, we don't use instanceID for hostname or override host name with instanceID. But OpenStack uses instanceID (i.e. server_id) in [AttachDisk](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L573) and [DetachDisk](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/openstack/openstack.go#L608). I was thinking converting server_id to host_name, but quickest is to get instanceID from host name.

**Comment by zhouhaibing089** [comment]
cc @spothanis

**Comment by jsafrane** [comment]
rebased

**Comment by goltermann** [comment]
@saad-ali can you add LGTM when you get a chance?

**Comment by saad-ali** [comment]
> @saad-ali can you add LGTM when you get a chance?

There are higher pri changes (https://github.com/kubernetes/kubernetes/pull/27567) we need to get in before this.

**Comment by jsafrane** [comment]
rebased

**Comment by saad-ali** [comment]
LGTM Thanks @jsafrane

**Pull request merged**
