### PR TITLE
Consistent configurations of jenkins e2e cluster and default private e2e cluster.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Configurations of jenkins e2e cluster and default private e2e cluster made consistent.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
CC @piosz

**Comment by jszczepkowski** [comment]
The default configuration of e2e on jenkins and in private cell should be the same. It is misleading when you starts default private cluster with 2 small nodes and you experience strange failures of e2e tests (which happens w/o this PR).

**Comment by quinton-hoole** [comment]
I would guess that the "strange failures" you're seeing are a result of #13236.
But you are right, it makes sense for the configurations to be the same.
@ixdy, any objections (I think that you wrote the original config, and may have had some reason for making them diverge)?  Otherwise LGTM.

**Comment by piosz** [comment]
The problem is that 2 small nodes (1cpu, 3.8G memory) aren't enough to run all addons. It is unrelated  to the mentioned issue.

**Comment by quinton-hoole** [comment]
@piosz are you sure?  The tests always used to run fine on those two nodes.  Perhaps the addons grew.  Fair enough.

As for the e2e tests on this specific PR, Jenkins doesn't make sense to me.   It says the tests all passed, but that they timed out.  And that they timed out but that they completed in 22 minutes.  We might need to increase the timeout on the Jenkins job.  I'll dig a little further.  In the mean time I'll rerun.

```
Build timed out (after 30 minutes). Marking the build as failed.

Ran 84 of 147 Specs in 1315.051 seconds
FAIL! -- 80 Passed | 0 Failed | 2 Pending | 61 Skipped Build was aborted

Recording test results

Ginkgo ran 1 suite in 22m0.611933556s
Test Suite Failed
```

**Comment by quinton-hoole** [comment]
@k8s-bot test this again please

**Comment by piosz** [comment]
Sorry, of course I didn't mean that 2 nodes aren't enough to just run addons, but I can see at least 13 addons containers running in the 2 node cluster, which actually reserves 65% of CPU available in the cluster. It may be tricky to run more than a few containers for testing purposes there.

**Comment by quinton-hoole** [comment]
As I suspected, that Jenkins e2e failure above was a flake.  The next one passed as expected.  LGTM.

**Comment by ixdy** [comment]
Jenkins diverged in #9678. I'm not sure why we didn't just update the test config instead.

**Comment by quinton-hoole** [comment]
Oops!  Guilty as charged - I LGTM'd that boo-boo :-)

**Comment by piosz** [comment]
Shippable is flaky

**Pull request merged**
