### PR TITLE
Optimized the way to obtain pvc and pv in kubelet

### PR DESCRIPTION
**Pull request by fengxiaoye**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Optimize the way of getting PVC and PV in kubelet, get PVC and PV from apiserver cache, and save the IO usage of etcd

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by fengxiaoye** [comment]
@davidz627 help to add "/ok-to-rest".thanks.

**Review by ehashman — COMMENTED** [review]
Please review our policy on [trivial edits](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits).

/close

**Pull request closed without merging**
