### PR TITLE
Have the /rootfs rw for containerized node e2e

### PR DESCRIPTION
**Pull request by ingvagabund**
**What this PR does / why we need it**:

The ``[sig-storage] HostPath [It] should support subPath [NodeConformance]`` test needs it otherwise the kubelet complains with:

```
  Jun 19 20:05:27 ip-172-18-11-17.ec2.internal docker[26836]: E0619 20:05:27.495132   26860 kubelet_pods.go:198] failed to create subPath directory for volumeMount "test-volume" of container "test-container-1": cannot create directory /rootfs/tmp/sub-path: read-only file system
```

Gubernator test results at https://k8s-gubernator.appspot.com/build/kubernetes-github-redhat/logs/ci-kubernetes-conformance-node-e2e-containerized-rhel/2421. Short snippet:

```
• Failure [312.655 seconds]
[sig-storage] HostPath
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/host_path.go:33
  should support subPath [NodeConformance] [It]
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/host_path.go:88

  Expected error:
      <*errors.errorString | 0xc4219998d0>: {
          s: "expected pod \"pod-host-path-test\" success: Gave up after waiting 5m0s for pod \"pod-host-path-test\" to be \"success or failure\"",
      }
      expected pod "pod-host-path-test" success: Gave up after waiting 5m0s for pod "pod-host-path-test" to be "success or failure"
  not to have occurred
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**: The tests are run inside RH infrastructure so no CI tests are needed to run

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by dims** [comment]
@ingvagabund do we need to fix local-up-cluster.sh too? https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh#L821

**Comment by ingvagabund** [comment]
@dims we do. The `[sig-storage] HostPath [It] should support subPath [NodeConformance]` test creates directory under `/tmp` which in the containerized case is mapped to `/rootfs/tmp`.

**Comment by ingvagabund** [comment]
@calebamiles thank you, appreciated.

**Pull request merged**
