### PR TITLE
Plug deduced type in

### PR DESCRIPTION
**Pull request by apelisse**
Use deduced type when using CRDs.

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by kwi** [comment]
Hi :)

**Comment by apelisse** [comment]
> Hi :)

Sorry :-) Github's auto-completion is slower than I want :-)

**Comment by kwi** [comment]
> > Hi :)
> 
> Sorry :-) Github's auto-completion is slower than I want :-)

Ahah, no worries, I loved the attention :D

**Pull request merged**
