### PR TITLE
controller test: use cancellation from ktesting

### PR DESCRIPTION
**Pull request by mengjiao-liu**
#### What type of PR is this?
/kind cleanup

see https://github.com/kubernetes/kubernetes/commit/63aa2615834393acd277abccb3f79422cb0c4452 for more details.

And PR https://github.com/kubernetes/kubernetes/pull/122293 is very large, in order to avoid interfering with reviewers, it is not suitable to convert all the places that need to use `tCtx := ktesting.Init(t)`. This PR is to convert the remaining test code of the controller directories.

#### Which issue(s) this PR fixes:

follow up: 
- https://github.com/kubernetes/kubernetes/pull/123399
- https://github.com/kubernetes/kubernetes/pull/122293#discussion_r1478295105

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by carlory** [comment]
the `pull-kubernetes-e2e-gce-storage-slow` failures would be fixed by https://github.com/kubernetes/test-infra/pull/32160

**Comment by mengjiao-liu** [comment]
The code involved is a little too much, temporarily closed.
/close

**Pull request closed without merging**
