### PR TITLE
Support completions for kubectl config rename-context

### PR DESCRIPTION
**Pull request by superbrothers**
**What this PR does / why we need it**:
With this PR, kubectl config rename-context supports completion for current context.
```
$ kubectl config rename-context <tab>
cluster01  minikube
```

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Support completion for kubectl config rename-context
```

### CODE REVIEW

**Comment by superbrothers** [comment]
@dims Thank you for your approval. However you might need to write `/approve no-issue` in a comment in order to merge this PR.

**Comment by superbrothers** [comment]
@dims Would you please rerun the following tests?

```
/test pull-kubernetes-e2e-kops-aws
/test pull-kubernetes-e2e-gce-etcd3
/test pull-kubernetes-e2e-gce-bazel
```

**Comment by superbrothers** [comment]
@dims The failed test is not related to this PR. Please run `/test pull-kubernetes-e2e-gce-bazel`.

**Comment by cblecker** [comment]
bump @smarterclayton for approval
/retest

**Pull request merged**
