### PR TITLE
Increase apiserver mem-threshold in density test

### PR DESCRIPTION
**Pull request by shyamjvs**
Ref: https://github.com/kubernetes/kubernetes/issues/60500#issuecomment-372682659 (fixes part of that issue)

/sig scalability
/kind bug
/priority important-soon
/cc @wojtek-t
/cc @crassirostris (for the release-note)

```release-note
Audit logging with buffering enabled can increase apiserver memory usage (e.g. up to 200MB in 100-node cluster). The increase is bounded by the buffer size (configurable). Ref: issue #60500
```

### CODE REVIEW

**Comment by shyamjvs** [comment]
@crassirostris Could you PTAL at the release-note?

**Comment by crassirostris** [comment]
@shyamjvs I'd shorten it:

```
Audit logging with buffering enabled can increase apiserver memory usage (e.g. up to 200MB in 100-node cluster). Ref: issue #60500
```

**Comment by shyamjvs** [comment]
Thanks - changed it. Also added `The increase is bounded by the buffer size (configurable).` to make it clear it's not an arbitrary/unpredicatable increase.

**Comment by crassirostris** [comment]
SGTM

**Pull request merged**
