### PR TITLE
GCI: fix a breakage in controller-manager

### PR DESCRIPTION
**Pull request by andyzheng0831**
This PR fixes the breakage to GCI caused by PR #19242.

### CODE REVIEW

**Comment by mikedanese** [comment]
LGTM

**Comment by andyzheng0831** [comment]
I verified this fix by running k8s e2e tests. All passed. Safe to merge. The default ContainerVM-based test will not cover this fix. Mark it as e2e-not-required. Considering the PR breaking GCI is p0, and currently both GCI k8s ci and GKE ci are blocked, prefer to mark this fix as P1

**Comment by andyzheng0831** [comment]
@mikedanese please add a lgtm label so it can be in queue

**Comment by mikedanese** [comment]
I manually merged

**Pull request merged**
