### PR TITLE
AWS: Strip more comments from instance user-data

### PR DESCRIPTION
**Pull request by justinsb**
To stay under the 16KB limit

### CODE REVIEW

**Comment by wojtek-t** [comment]
@justinsb - can you please rebase?

**Comment by wojtek-t** [comment]
@justinsb - can you please rebase?

**Comment by wojtek-t** [comment]
@justinsb - friendly ping - can you please rebase this PR?

**Comment by wojtek-t** [comment]
@justinsb - can you please rebase?

**Comment by wojtek-t** [comment]
@justinsb - can you please rebase?

**Comment by wojtek-t** [comment]
@justinsb - can you please rebase this PR?

**Comment by justinsb** [comment]
Rebased.... ironically I think it was a conflict against my own PR.

Sorry for the ridiculous delay!

**Pull request merged**
