### PR TITLE
Automated cherry pick of #53146 #53678 #54644

### PR DESCRIPTION
**Pull request by jdumars**
Cherry pick of #53146 #53678 #54644 on release-1.8.

#53146: Add a label which prevents a node from being added to a cloud
#53678: Append an alpha label to the exclude load balancer
#54644: wqFlag gate node exclusion for service load balancers.

```release-note
Add a label which prevents a node from being added to a cloud.Append an alpha label to the exclude load balancer. `wqFlag` gate node exclusion for service load balancers.
```

### CODE REVIEW

**Comment by jdumars** [comment]
@jpbetz FYI ~ this is the wrap up of https://github.com/kubernetes/kubernetes/pull/53656

**Comment by jpbetz** [comment]
Thanks @jdumars

**Comment by jpbetz** [comment]
@jdumars I threw in a release note, please update if needed.

**Comment by jdumars** [comment]
@jpbetz thanks so much!

**Pull request merged**
