### PR TITLE
Update Godeps after removing influx tests

### PR DESCRIPTION
**Pull request by DirectXMan12**
When the influx tests were removed, it should have also removed the
influx deps from Godeps.  This does that.

See also  #66175

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by DirectXMan12** [comment]
cc @tpepper

**Comment by tpepper** [comment]
fyi @mohammedzee1000

**Comment by cblecker** [comment]
Adding `queue/fix` as batches will fail without this.

**Pull request merged**
