### PR TITLE
Do not update asw when populating the desired state of world

### PR DESCRIPTION
**Pull request by FengyunPan**
Only based on pod, we can not make sure the volume is attached.
If volume is attached, we have already marked it attached by node
when populating the actual state of world.
So after populating the actual state of world, we just populate
the desired state of world by pod and do not update the actual
state of world.

/assign @jingxu97

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by gnufied** [comment]
@FengyunPan can you open a issue that this PR is trying to fix?

**Comment by FengyunPan** [comment]
@gnufied Ok, I have created a issue for this PR: #51531

**Comment by wongma7** [comment]
cc @tsmetana

**Comment by jingxu97** [comment]
@FengyunPan, the reason for that part you are trying to delete is that when controller populate actual state of world, it uses the information from node status which is a list of volume attached. But it does not have enough information to fill out all the fields and leave them empty. When updating the desired state, some information obtained from pods objects and then related volume objects) could be used to fill those empty fields in actual state.

**Comment by FengyunPan** [comment]
@jingxu97 Oh, I see. My mistake, populateDesiredStateOfWorld call MarkVolumeAsAttached (https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/attach_detach_controller.go#L377) push related volume objects into actual state.

**Pull request closed without merging**
