### PR TITLE
update kubernetes-dashboard version to v1.7.1

### PR DESCRIPTION
**Pull request by zouyee**
update version to v1.7.1
**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
duplicate of https://github.com/kubernetes/kubernetes/pull/53046 ?

**Comment by roberthbailey** [comment]
Looks like a dupe, so I'm going to close this PR. Please re-open if this PR should be reviewed instead of #53046.

**Comment by maciaszczykm** [comment]
It should be not. It is a duplicate.

**Comment by roberthbailey** [comment]
In that case, can you update the description? Also, there should be a release note when you bump the version of an addon.

**Comment by maciaszczykm** [comment]
@roberthbailey Sorry for misunderstanding, but I think that this issue is a duplicate of #53046. My last comment was about reopening this issue.

**Comment by roberthbailey** [comment]
Roger; re-closing.

**Pull request closed without merging**
