### PR TITLE
fix chinese syntax

### PR DESCRIPTION
**Pull request by xuhuilong**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by CaoShuFeng** [comment]
/lgtm
Much better to understand.

**Comment by xuhuilong** [comment]
it passed! thanks @zjj2wry

**Comment by xuhuilong** [comment]
it passed! thanks, @zjj2wry

**Comment by cblecker** [comment]
@xuhuilong @deads2k bindata wasn't regenerated. Opened https://github.com/kubernetes/kubernetes/pull/62424 to do this.

**Pull request merged**
