### PR TITLE
Add namespace to swagger nicknames to prevent duplicate nicknames

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/GoogleCloudPlatform/kubernetes/issues/11229

cc @bgrant0607 

Post 1.0

### CODE REVIEW

**Comment by bgrant0607** [comment]
We might need this for generated docs. @caesarxuchao 

LGTM. Please create a cherrypick PR after this is merged.

**Comment by bgrant0607** [comment]
Shippable failure was due to doc move. Restarting shippable. If that doesn't work you might need to rebase.

**Comment by bgrant0607** [comment]
Reassigned to @lavalamp for another LGTM

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
Just to verify: were clients using this nickname field? I'm assuming not, because otherwise this change would not be safe?

**Comment by nikhiljindal** [comment]
@lavalamp Users will have to recreate their client from updated swagger spec, to pick up this change.

Earlier, there was no way for them to send a namespaced request (Both namespaced and unnamespaced had the same nickname, and namespaced one was overwritten by the unnamespaced one).
After this change, they will be still be able to send the unnamespaced request using the old nickname. We now have a new nickname for namespaced requests.

So hopefully, this doesnt break anything :)

**Comment by nikhiljindal** [comment]
Cherrypick request: https://github.com/GoogleCloudPlatform/kubernetes/pull/11347

**Pull request merged**
