### PR TITLE
ignore replicaset-replicas-before-scale annotation in deployment rollbacks

### PR DESCRIPTION
**Pull request by atiratree**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

This is a prerequisite for upcoming feature `DeploymentPodReplacementPolicy` (https://github.com/kubernetes/kubernetes/pull/123430)

Add a new annotation to make sure N-1 kubectl rollback works with a cluster that turns on the new  feature. Same applies for  N-1 kube-controller-manager rollback.

We are unable to fully scale due to the new `TerminationComplete` policy . This policy ensures that there is only a certain number of pods specified up to `deployment.spec.replicas + maxSurge`, which includes terminating pods. If we want to scale above this number, we have to postpone the scaling to the future when terminating pods disappear.

1. We scale old replicaset(s) partially (e.g. from 6->7, later 7->9) according to the current running and terminating pods.
2. When these pods terminate, we can go back to scaling the old replicaset(s) (e.g. from 7->9). To implement this we need to know the original number of replicas (6) so that we do not overscale some of the replicasets. We are scaling proportionally the old state of the cluster and cannot obtain this information from the current/new state of the cluster. 

https://github.com/kubernetes/kubernetes/blob/a4eaf6e1200fa6f2050c71ef7a7e8ab27a8e4947/pkg/controller/deployment/util/deployment_util.go#L510

3. We can store this number in the `deployment.kubernetes.io/replicaset-replicas-before-scale` annotation and retrieve this in the next scaling iteration to compute the total number of replicas the old replicaset should scale to. We should not fallback the scaling to the newest replicaset instead of the old ones; to persist the original proportional availability of the application.

Storing the annotation for partial scaling (done only when scaling old replicasets):

https://github.com/kubernetes/kubernetes/blob/d8347ac1fdc767bc89826920359a7bb0dd922674/pkg/controller/deployment/sync.go#L410-L419

https://github.com/kubernetes/kubernetes/blob/d8347ac1fdc767bc89826920359a7bb0dd922674/pkg/controller/deployment/util/deployment_util.go#L456-L474

Scaling during partial scaling to ensure that we compute the correct number of replicas

https://github.com/kubernetes/kubernetes/blob/d8347ac1fdc767bc89826920359a7bb0dd922674/pkg/controller/deployment/util/deployment_util.go#L585-L620

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
KEP: https://github.com/kubernetes/enhancements/issues/3973
```

### CODE REVIEW

**Comment by atiratree** [comment]
@kannon92 @dejanzele @soltysh @jpbetz 

Could you please review this? It would be great if we could merge this into v1.30 to allow N-1 kubectl rollbacks in v1.31, where `DeploymentPodReplacementPolicy` should be fully implemented as alpha (https://github.com/kubernetes/kubernetes/pull/123430).

/label api-review

**Comment by kannon92** [comment]
LGTM to me but I should leave this for someone more familar with this code.

**Comment by atiratree** [comment]
In today's sig-apps call, we have decided to postpone the introduction of the annotation into 1.31 along with the alpha version of the feature.  We will specifically document in the KEP/docs that this feature should be used with the latest kubectl. In the next release (1.32), the rollbacks should be backwards compatible.

**Comment by soltysh** [comment]
This was discussed earlier today during sig-apps call. The topic of proportionally scaling deployments is an open topic that will further looked into during the implementation (https://github.com/kubernetes/kubernetes/pull/123430), but for backwards compatibility that's the reason we have alpha release, when the feature is off, to allow all the components (including kubectl) to catch up with the supported n-1 skew window. Thus we've decided not to merge this in 1.30. 

/close

**Pull request closed without merging**
