### PR TITLE
kubeadm: add --control-plane-endpoint flag

### LINKED ISSUE #1625: kubeadm should allow specifying `--control-plane-endpoint`
For the options that make sense, we should provide CLI flags. I argue that it makes sense to add a flag for `controlPlaneEndpoint` ASAP, to not have to force the user to create a config file just for running the automated HA flow. This will reduce the burden on first-time users significantly IMO.

I think we should consider backporting such a change to v1.15.1.
(I realized this when writing the v1.15 blog post, FWIW)

@timothysc @fabriziopandini @neolit123

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#1625

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: provide "--control-plane-endpoint" flag for `controlPlaneEndpoint`
```

### CODE REVIEW

**Review by rosti — APPROVED** [review]
Thanks @SataQiu !
This is a good flag to have, however we also need to inherit it in the init phases, where appropriate.
A hint to start with are the phases, that inherit the `APIServerAdvertiseAddress` option, but others might need it as well.

/approve
/hold

**Review by neolit123 — COMMENTED** [review]
/hold
adding comments to https://github.com/kubernetes/kubeadm/issues/1625

**Comment by neolit123** [comment]
> adding comments to kubernetes/kubeadm#1625

didn't see @rosti commented already here on the PR.

**Comment by neolit123** [comment]
SGTM, let's have approval from @fabriziopandini when he is back.
/assign @fabriziopandini

**Review by luxas — APPROVED** [review]
Thank you very much for this @SataQiu!
Please fix @rosti's comment and then we're good to go

**Comment by SataQiu** [comment]
I'm not sure if this covers all the `InheritFlags`, is there a good way to look it up? @rosti

**Comment by neolit123** [comment]
/assign @rosti
PTAL

**Review by fabriziopandini — APPROVED** [review]
@SataQiu thanks for this PR!

> I'm not sure if this covers all the InheritFlags, is there a good way to look it up

AFAIK, you can assume that the control plane endpoint flag should exist where the advertise address flag already exists (and from a quick check, you are already ok)

> SGTM, let's have approval from @fabriziopandini when he is back.

In this case I agree with @luxas and @rosti; hopefully, we can manage to get this backported into the .1

/approve
/lgtm

**Pull request merged**
