### PR TITLE
[WIP] Experimental cinder volume provider

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I5c7a31b65f5444380d4e197141fc0be602b7febe

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jsafrane** [comment]
Can you please elaborate on why is this PR needed? It looks to me it adds a new cloud provider that is exactly the same as already existing OpenStack.

**Comment by dims** [comment]
@jsafrane i am looking at decoupling the "cinder" one so it can stay in the main k/k repository. possibly vendoring in the code from `"k8s.io/kubernetes/pkg/cloudprovider/providers/openstack"` 

cc @gnufied @flaper87 @j-griffith

**Comment by gnufied** [comment]
@dims It would be awesome if we can read through a design of what we are trying to accomplish and how vendoring will work. This PR alone does not capture the complete picture I am afraid and I think this should go through typical KEP/design process. 

cc @saad-ali @kubernetes/sig-storage-api-reviews

**Comment by dims** [comment]
@gnufied ack. i'll iterate a bit until i am clearer on what i want to accomplish.

**Comment by hogepodge** [comment]
@dims @gnufied https://github.com/kubernetes/community/pull/2774

Staring point for KEP. WIP, did my best to capture the intent but it's a very rough working draft.

**Comment by hogepodge** [comment]
cc @cheftako

**Comment by dims** [comment]
we'll need just the cinder_provider.go from here later. will just pull that into another PR later

**Pull request closed without merging**
