### PR TITLE
replace CloneTLSConfig() with (*tls.Config).Clone()

### PR DESCRIPTION
**Pull request by mikedanese**

### CODE REVIEW

**Comment by smarterclayton** [comment]
Change LGTM, self merge when green

**Comment by mikedanese** [comment]
@k8s-bot unit test this
@k8s-bot node e2e test this
@k8s-bot verify test this

**Comment by mikedanese** [comment]
@k8s-bot unit test this

**Comment by CaoShuFeng** [comment]
I known we are moving to go 1.8.
After this go 1.7 can't compile, do we need to document that kubernetes 1.7 doesn't support go 1.7 anymore?
Thanks

**Pull request merged**
