### PR TITLE
federation ingress controller: Fixing a panic by initialising the map before using it

### PR DESCRIPTION
**Pull request by nikhiljindal**
Ref https://github.com/kubernetes/kubernetes/issues/32733#issuecomment-248428635

cc @kubernetes/sig-cluster-federation @quinton-hoole

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33120)

### CODE REVIEW

**Comment by madhusudancs** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33120#-:-KS8Mv_qPnHTWJMm4U3K:bnfp4nl)*

**Comment by nikhiljindal** [comment]
Thanks @madhusudancs 
Added the LGTM label.

@k8s-bot federation gce e2e test this

**Comment by nikhiljindal** [comment]
Not sure why the unit test failed on Jenkins.
It is passing for me locally.

Retrying
@k8s-bot unit test this issue: #IGNORE

**Comment by nikhiljindal** [comment]
Federation replicaset test still failed with:
```
STEP: Updating federation replicaset "federation-replicaset" in namespace "e2e-tests-federation-replicaset-rndu0"
STEP: Successfully updated federation replicaset "federation-replicaset" in namespace "e2e-tests-federation-replicaset-rndu0"
STEP: Replicas not match, federation replicas: 15/5, clusters replicas: 15/15

STEP: Replicas not match, federation replicas: 15/15, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

STEP: Replicas not match, federation replicas: 15/14, clusters replicas: 14/14

Sep 20 14:44:47.610: INFO: Unexpected error occurred: timed out waiting for the condition
```

Retrying to see if its a flake
@k8s-bot federation gce e2e test this

**Pull request merged**
