### PR TITLE
Add missing dependency google.golang.org/api/dns

### PR DESCRIPTION
**Pull request by ghost**
Add missing dependency:

google.golang.org/api/dns

to vendor/

### CODE REVIEW

**Comment by madhusudancs** [comment]
Looks like a trivial vendored code addition/update. LGTM.

**Comment by quinton-hoole** [comment]
Looks like a license failure on one of the dependencies....

```
FAILED   ./hack/../hack/verify-godep-licenses.sh	23s
Verifying ./hack/../hack/verify-godeps.sh
Checking for 'Godeps/' changes against 'origin/master'
Starting to download all kubernetes godeps. This takes a while
Download finished
Your Godeps.json is different:
--- /go/src/k8s.io/kubernetes/Godeps/Godeps.json	2016-05-21 14:02:49.443328202 -0700
+++ /tmp/gopath.JAvXZL/src/k8s.io/kubernetes/Godeps/Godeps.json	2016-05-21 14:26:40.834138057 -0700
@@ -724,11 +724,6 @@
 			"Rev": "7c47e2558a0bbbaba9ecab06bc6681e73028a28a"
 		},
 		{
-			"ImportPath": "github.com/emicklei/go-restful/examples/msgpack",
-			"Comment": "v1.2-54-g7c47e25",
-			"Rev": "7c47e2558a0bbbaba9ecab06bc6681e73028a28a"
-		},
-		{
 			"ImportPath": "github.com/emicklei/go-restful/log",
 			"Comment": "v1.2-54-g7c47e25",
 			"Rev": "7c47e2558a0bbbaba9ecab06bc6681e73028a28a"
@@ -2019,10 +2014,6 @@
 			"Rev": "4300f6b0c8a7f09e521dd0af2cee27e28846e037"
 		},
 		{
-			"ImportPath": "google.golang.org/api/dns/v1",
-			"Rev": "4300f6b0c8a7f09e521dd0af2cee27e28846e037"
-		},
-		{
 			"ImportPath": "google.golang.org/api/gensupport",
 			"Rev": "4300f6b0c8a7f09e521dd0af2cee27e28846e037"
 		},
@@ -2100,16 +2091,6 @@
 			"Rev": "20b71e5b60d756d3d2f80def009790325acc2b23"
 		},
 		{
-			"ImportPath": "gopkg.in/vmihailenco/msgpack.v2",
-			"Comment": "v2.5.1",
-			"Rev": "005134bfb4bf69b74e05382eddacea6a4585e4aa"
-		},
-		{
-			"ImportPath": "gopkg.in/vmihailenco/msgpack.v2/codes",
-			"Comment": "v2.5.1",
-			"Rev": "005134bfb4bf69b74e05382eddacea6a4585e4aa"
-		},
-		{
 			"ImportPath": "gopkg.in/yaml.v2",
 			"Rev": "a83829b6f1293c91addabc89d0571c246397bbf4"
 		},
Removing /tmp/gopath.JAvXZL
FAILED   ./hack/../hack/verify-godeps.sh	508s
```

**Comment by quinton-hoole** [comment]
I'm not sure how to resolve this error.  @brendandburns ?  @lavalamp ?

**Comment by quinton-hoole** [comment]
@nikhiljindal FYI, as you're doing such a marvellous job of shepherding the cluster federation PR's through the pipeline.

**Comment by quinton-hoole** [comment]
Blocked on #26105

**Comment by quinton-hoole** [comment]
So the godep licenses are apparently out of date.  But when I run hack/update-godep-licenses.sh it just crashes.  I'll have to debug that.

```
$ ./hack/update-godep-licenses.sh --create-missing
./hack/update-godep-licenses.sh: line 183: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
!!! Error in ./hack/update-godep-licenses.sh:183
  'declare -Ag FILE_CONTENT' exited with status 2
Call stack:
  1: ./hack/update-godep-licenses.sh:183 main(...)
Exiting with status 1

```


```
Your godep licenses file is out of date. Run hack/update-godep-licenses.sh --create-missing and commit the results.
--- /go/src/k8s.io/kubernetes/Godeps/LICENSES	2016-05-24 12:45:53.454825113 -0700
+++ /go/src/k8s.io/kubernetes/_tmp/kube-godep-licenses.4sRQGK/Godeps/LICENSES	2016-05-24 13:04:04.306854538 -0700
@@ -64925,6 +64925,38 @@ OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 
 
 ================================================================================
+= vendor/google.golang.org/api/dns/v1 licensed under: =
+
+Copyright (c) 2011 Google Inc. All rights reserved.
+
+Redistribution and use in source and binary forms, with or without
+modification, are permitted provided that the following conditions are
+met:
+
+   * Redistributions of source code must retain the above copyright
+notice, this list of conditions and the following disclaimer.
+   * Redistributions in binary form must reproduce the above
+copyright notice, this list of conditions and the following disclaimer
+in the documentation and/or other materials provided with the
+distribution.
+   * Neither the name of Google Inc. nor the names of its
+contributors may be used to endorse or promote products derived from
+this software without specific prior written permission.
+
+THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
+"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
+LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
+A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
+OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
+SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
+LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
+DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
+THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
+OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+
+
+================================================================================
 = vendor/google.golang.org/api/gensupport licensed under: =
 
 Copyright (c) 2011 Google Inc. All rights reserved.
Removing workspace: /go/src/k8s.io/kubernetes/_tmp/kube-godep-licenses.4sRQGK
FAILED   ./hack/../hack/verify-godep-licenses.sh	20s
Verifying ./hack/../hack/verify-godeps.sh
Checking for 'Godeps/' changes against 'origin/master'
Starting to download all kubernetes godeps. This takes a while
Download finished
Your Godeps.json is different:
--- /go/src/k8s.io/kubernetes/Godeps/Godeps.json	2016-05-24 12:45:53.442825113 -0700
+++ /tmp/gopath.Se60P8/src/k8s.io/kubernetes/Godeps/Godeps.json	2016-05-24 13:07:53.414860846 -0700
@@ -2043,10 +2044,6 @@
 			"Rev": "4300f6b0c8a7f09e521dd0af2cee27e28846e037"
 		},
 		{
-			"ImportPath": "google.golang.org/api/dns/v1",
-			"Rev": "4300f6b0c8a7f09e521dd0af2cee27e28846e037"
-		},
-		{
 			"ImportPath": "google.golang.org/api/gensupport",
 			"Rev": "4300f6b0c8a7f09e521dd0af2cee27e28846e037"
 		},
Removing /tmp/gopath.Se60P8
FAILED   ./hack/../hack/verify-godeps.sh	266s
```

**Comment by lavalamp** [comment]
@quinton-hoole I noticed this problem a couple days ago and managed to make https://github.com/kubernetes/kubernetes/pull/26008, which is now out of date. I didn't have time to figure out what was going on.

**Comment by quinton-hoole** [comment]
@goltermann @karlkfi FYI - godep license checks and license regenerator seems to be broken.  To unblock the release, I'm going to temporarily disable it.  Does anyone actually understand what this is for, and what it's supposed to do?

**Comment by goltermann** [comment]
It's definitely used by Google for GKE - we need to verify that all godeps are using an appropriate license for us to release GKE containing a new minor version of Kubernetes.

**Comment by karlkfi** [comment]
@quinton-hoole:  `declare: -A: invalid option` means your bash is old. If you want it to be more friendly you could add a bash version check at the top of the file.

Both `hack/verify-godeps.sh` and `hack/verify-godep-licenses.sh` are failing. So it's probably related. Fix the out of date godeps and then run `hack/update-godep-licenses.sh --create-missing` and commit the results.

The problem is that godeps frequently become out of date on master and then whoever makes a new PR gets to fix it, even if they didn't change any godeps.

**Comment by quinton-hoole** [comment]
Thanks Karl. I sorted it out in the linked PR.

**Comment by quinton-hoole** [comment]
Apparently not quite.  Still failing in #26020, but for different reasons now.

**Comment by quinton-hoole** [comment]
Blocked on #26348

**Comment by quinton-hoole** [comment]
Closing in favor of #26020

**Pull request closed without merging**
