### PR TITLE
Remove deprecated sets.String from pkg/kubelet

### PR DESCRIPTION
**Pull request by gjkim42**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

This removes deprecated sets.String from pkg/kubelet to avoid warning messages.
- s/sets.String/sets.New[string]/g
- s/sets.NewString/sets.New[string]/g
- Use sets.List instead of (sets.String).List
- ~Remove sets.String from util.GetPodVolumeNames as it's used in pkg/kubelet~ <- addressed by https://github.com/kubernetes/kubernetes/pull/124740

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bart0sh** [comment]
/lgtm

/assign @mrunalp @derekwaynecarr @dchen1107 
for approval

**Review by mrunalp — APPROVED** [review]

**Comment by gjkim42** [comment]
/assign @liggitt 

Could you take a look? The PR just replaces deprecated sets.string, but needs api-reviewers approval.

**Comment by pacoxu** [comment]
> /assign @liggitt
> 
> Could you take a look? The PR just replaces deprecated sets.string, but needs api approval.

For [pkg/kubelet/apis/config/OWNERS](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/OWNERS), only test is updated here.

**Comment by liggitt** [comment]
/remove-label api-review

this doesn't involve a user-facing API

**Comment by liggitt** [comment]
/approve

for api config unit test change

**Pull request merged**
