### PR TITLE
Move pkg/api/v1/node to pkg/util/node

### PR DESCRIPTION
**Pull request by wgliang**
**What this PR does / why we need it**:

kind/api-change 

Move pkg/api/v1/node to pkg/util/node

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
I don't think pkg/util is the right place. Compare https://github.com/kubernetes/kubernetes/pull/55492

/hold

**Comment by wgliang** [comment]
@sttts 
Sorry, I didn't get the connection between them. And It also has TODO like this PR in pkg/api/v1/node/util.go.

**Comment by sttts** [comment]
@wgliang my PR moves the same package. IMO `pkg/util` without an API group in the path is a bad naming scheme. But we already have `pkg/util/node` (one out of 50ish packages 😱), so your PR does not make it worse at least ([broken window theory](https://en.wikipedia.org/wiki/Broken_windows_theory)). I think we should come up with a better package scheme.

**Pull request closed without merging**
