### PR TITLE
Automated cherry pick of #73661

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #73661 on release-1.13.

#73661: fix smb remount issue on Windows

### CODE REVIEW

**Comment by tpepper** [comment]
@jsafrane looks like you probably intended to lgtm this one but had a key press off-by-one error?

**Comment by andyzhangx** [comment]
/lgtm
since it's a typo...

**Comment by jsafrane** [comment]
yeah, it hsould be /lgtm  :-)

**Pull request merged**
