### PR TITLE
fix local and cross-file links

### PR DESCRIPTION
**Pull request by mgannholm**
fixing broken links, grammar.

### CODE REVIEW

**Comment by thockin** [comment]
@krousey

**Comment by krousey** [comment]
@k8s-bot test this please

**Comment by thockin** [comment]
No need to run e2e for trivial changes, really.

**Comment by krousey** [comment]
@mgannholm Please sign the Google CLA. If you are my manager, please associate your Google account with your Github account to satisfy the CLA bot. :smile:

**Comment by krousey** [comment]
@mgannholm Also, this will probably have some conflicts with #11598 which I'm going to merge as soon as shippable passes.

**Comment by krousey** [comment]
@mgannholm Please resolve conflicts from @amygdala 's PR

**Pull request closed without merging**
