### PR TITLE
fix: Provide IPv6 support for internal load balancer

### PR DESCRIPTION
**Pull request by nilo19**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Cherry pick from https://github.com/kubernetes-sigs/cloud-provider-azure/pull/703: feat: Provide IPv6 support for internal load balancer.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
fix: Provide IPv6 support for internal load balancer
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
/triage accepted
/sig cloud-provider
/area provider/azure
/priority critical-urgent
cc @feiskyer

### CODE REVIEW

**Review by aramase — COMMENTED** [review]
/lgtm

**Comment by aramase** [comment]
/hold

for reviews from @feiskyer

**Review by feiskyer — APPROVED** [review]
/lgtm
/hold cancel

**Review by khenidak — APPROVED** [review]

**Comment by nilo19** [comment]
@feiskyer need milestone to merge

**Comment by feiskyer** [comment]
@cheftako @dims could you help to approve this bug fix?

**Comment by ialidzhikov** [comment]
Same as https://github.com/kubernetes/kubernetes/pull/103997#issuecomment-890053813. Can you create a cherry-pick for release-1.22 branch?

**Comment by cheftako** [comment]
@feiskyer Can you generate the v1.22 cherry-pick?

**Comment by ialidzhikov** [comment]
> @feiskyer or @nilo19 Can you generate the v1.22 cherry-pick?

https://github.com/kubernetes/kubernetes/pull/104051

**Pull request merged**
