### PR TITLE
Generate protobuf into vendor for pseudo vendored models

### LINKED ISSUE #39764: Protobuf not generated for changes to k8s.io/apimachinery/pkg/apis/meta/v1
Protobuf can't generate for things that are in vendor today.

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes #39764

@ncdc

### CODE REVIEW

**Comment by ncdc** [comment]
This isn't actually generating *into* vendor, but into staging, right?

**Comment by smarterclayton** [comment]
Correct, but vendor is detectable and staging is arbitrary.

**Comment by ncdc** [comment]
Are the diffs in staging showing up in this commit because the dirs in staging are symlinked into vendor?

**Comment by smarterclayton** [comment]
Yes

**Comment by ncdc** [comment]
Ok. LGTM but would recommend another +1 from @deads2k

**Comment by deads2k** [comment]
Yes, this seems reasonable.  If we end up moving API objects to a different repo under staging, we'd need similar changes, correct?

**Comment by smarterclayton** [comment]
Applying label

**Comment by ncdc** [comment]
Sorry, thanks - been pretty swamped

**Comment by smarterclayton** [comment]
Just spotted a bug - fixing.

**Comment by smarterclayton** [comment]
Added one more place where we had to use the vendored dir (rewriting the generated.proto file to remove gogoproto extensions).

**Comment by smarterclayton** [comment]
@k8s-bot node e2e test this.

**Comment by smarterclayton** [comment]
@k8s-bot node e2e test this.

**Comment by fejta** [comment]
ref https://github.com/kubernetes/test-infra/issues/1561
@k8s-bot node e2e test this

**Pull request merged**
