### PR TITLE
chore: clean up the tests that have external dependencies

### LINKED ISSUE #102987: TestGetServicePrincipalTokenFromMSI unit tests fails on ppc64le
#### Which jobs are failing:

https://prow.ppc64le-cloud.org/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le

#### Which test(s) are failing:
Below two test cases started failing on ppc64le:
vendor/k8s.io/legacy-cloud-providers/azure/auth:
1. TestGetServicePrincipalTokenFromMSIWithUserAssignedID
2. TestGetServicePrincipalTokenFromMSI

#### Since when has it been failing:
6th June 2021

#### Testgrid link:
https://k8s-testgrid.appspot.com/sig-node-ppc64le#unit-tests

#### Reason for failure:
```
azure_auth_test.go:73: 
        	Error Trace:	azure_auth_test.go:73
        	Error:      	Received unexpected error:
        	            	MSI not available
        	Test:       	TestGetServicePrincipalTokenFromMSIWithUserAssignedID
```

#### Anything else we need to know:
503d048...a68644b was the delta between the passing and failing tests
Started failing after https://github.com/kubernetes/kubernetes/pull/102441

### PR DESCRIPTION
**Pull request by feiskyer**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

chore: clean up the tests that have external dependencies.

Because of changes in https://github.com/Azure/go-autorest/pull/613, the tests that depends on `adal.NewServicePrincipalTokenFromMSI` would start to fail because it is requiring the IMDS endpoints be available. Because the function doesn't provide a way to pass in test endpoint, this PR deletes the two test cases that depend on the function to unblock tests.

#### Which issue(s) this PR fixes:

Fixes #102987

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cheftako** [comment]
Removing tests not my favorite way to make things pass. Will still approve if you get one of the other azure experts to lgtm.

**Comment by feiskyer** [comment]
@cheftako agreed. but it should be ok since no new features would be added for legacy cloud providers.

**Pull request merged**
