### PR TITLE
[Federation] Modify the comments in Federation E2E tests to use standard Go conventions for documentation comments

### PR DESCRIPTION
**Pull request by perotinus**
```release-note
NONE
```

### CODE REVIEW

**Comment by perotinus** [comment]
cc @madhusudancs

**Comment by madhusudancs** [comment]
/lgtm
/approve

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41364#-:-KcuJ7-Ji8JF64dMxLnp:b6yv7yi)*

**Comment by madhusudancs** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/41364)*

**Comment by madhusudancs** [comment]
@k8s-bot ok to test

**Pull request merged**
