### PR TITLE
Revert "Add an option to conditionally disable compression based on client ip."

### PR DESCRIPTION
**Pull request by deads2k**
This reverts commit 023583a15586328569ccab505db2f57f398e04b3 from https://github.com/kubernetes/kubernetes/pull/111507

The topic of disabling compression came up in our [June 15 api machinery call](https://docs.google.com/document/d/1x9RNaaysyO0gXHIr1y50QFbiL1x8OWnk2v3XnrdkT5Y/edit#).  In that call, we expressed misgivings and I would have expected to see a followup discussion before merging a change like this.  Adding a GA flag at the last minute with minimal discussion concerns me.  I'm used to seeing KEP updates for significant flags, in part so that PRR has a chance to review and in part so the sig can discuss alternatives like client-side handling and options for choosing uncompressed data.

Separately, the concerns from @shyamjvs in https://github.com/kubernetes/kubernetes/pull/111507#issuecomment-1218371898 ought to be addressed before re-merging.

Given the additional surface area, the last minute addition, and the lack of discussion with sig given the proximity of the previous call, we can revert this from 1.25 and try again in 1.26.

/kind bug
/priority important-soon
/sig api-machinery
/assign @liggitt @lavalamp 

```release-note
NONE
```

### CODE REVIEW

**Comment by cici37** [comment]
Does it miss the Release Notes?
Since we have a release note for adding the flag, maybe worth to mention in the release note again that the flag is removed.

**Comment by liggitt** [comment]
> Does it miss the Release Notes?

I cleared out the release note from the original PR... is there a way to omit the change from the 1.25 release notes entirely rather than highlight the addition and removal?

**Comment by cici37** [comment]
> > Does it miss the Release Notes?
> 
> I cleared out the release note from the original PR... is there a way to omit the change from the 1.25 release notes entirely rather than highlight the addition and removal?

It has to be manually removed from release notes. I will let the release notes team know. cc @csantanapr

**Pull request merged**
