### PR TITLE
double const in mount_linux.go

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
fix some typo and double const
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
/ok-to-test
/lgtm

Thanks!

**Comment by xiangpengzhao** [comment]
/assign @jingxu97
for approval. Thanks!

**Comment by jianglingxia** [comment]
PLAT @saad-ali  @jingxu97 
thanks

**Comment by xiangpengzhao** [comment]
@jianglingxia please rebase.

**Comment by jianglingxia** [comment]
thanks @xiangpengzhao  maybe Trouble to you review and label lgtm again!

**Comment by xiangpengzhao** [comment]
@jianglingxia np :)

**Pull request merged**
