### PR TITLE
Use --force flag for reconciling addons

### PR DESCRIPTION
**Pull request by kawych**
**What this PR does / why we need it**:
Addon manager should use kubectl `--force` flag when reconciling addons. Without it, following scenario breaks the cluster:

- `kubectl delete` on any resource with immutable fields, i.e. kube-dns service
- immediately `kubectl create` your own resource with the same name, but different value for the immutable field, for example service `kube-dns` with ClusterIP = 10.35.240.12

After that, Addon Manager fails to reconcile this resource. A failure in this steps leads to further failures, for example Addon Manager doesn't attempt to prune not-wanted addons.

**Release note**:
```release-note
Fix Addon Manager failure to reconcile addons with immutable fields.
```

### CODE REVIEW

**Comment by MrHohn** [comment]
Humm, good observation on that. What does it mean for those immutable fields after adding the `--force` flag? Would we get into a situation that apiserver force the API objects to be changed, but controllers fail to operate because of the invalid state?

/assign @mikedanese  
/kind bug

**Comment by kawych** [comment]
I've tested this, it requires also newer version of kubectl. I have one more problem with that - if Addon Manager finds kube-dns service with incorrect ClusterIP (immutable field), instead of re-aplying it immediately, kube-dns service gets pruned and recreated only in the next Addon Manager run.

@MrHohn The behavior I expect is for the resource to be re-created with correct configuration.
"Would we get into a situation that apiserver force the API objects to be changed, but controllers fail to operate because of the invalid state?" - I didn't fully understand. Do you mean:
(1) If cluster uses forces addon changes, can it cause controllers to fail?
(2) If Addon Manager forces addon changes, can it cause controllers to fail?
For (1) I don't know, maybe it's possible. For (2), I believe not, any difference in addon configuration is probably caused by cluster user applying/forcing their changes, and I believe Addon Manager should revert those changes.

**Review by MrHohn — APPROVED** [review]
/lgtm

**Comment by kawych** [comment]
@mikedanese PTAL

**Comment by mikedanese** [comment]
I'm looking at the kubectl apply flags and I see this:
```
--force=false: Only used when grace-period=0. If true, immediately remove resources from API and bypass graceful deletion. Note that immediate deletion of some resources may result in inconsistency or data loss and requires confirmation.
```
1) This doesn't sound like the behavior you are describing.
2) It requires confirmation?

From the code, it looks like this does what you describe. But this looks really scary to me:

https://github.com/kubernetes/kubernetes/blob/9f15368c5ceda5900a64c9bb54178531d8f7fbf2/pkg/kubectl/cmd/apply/apply.go#L945-L947

 What happens if we push an object config that is invalid in some clusters? What if a customer accidentally misconfigures an admission webhook and we start getting invalid requests on applies? It seems like we would just start deleting objects and recreating them.

Even more likely, what if the deployment controller updates a deployment at the same time we run apply and get a conflict? Wouldn't we delete the deployment, wait for it to fully delete, then recreate it?

cc @apelisse

**Comment by kawych** [comment]
/remove-lifecycle rotten

> What if a customer accidentally misconfigures an admission webhook and we start getting invalid  requests on applies? It seems like we would just start deleting objects and recreating them.

I think the same behavior happens for normal apply behavior, with the exception of immutable objects - only because normal `kubectl apply` will fail.

> Even more likely, what if the deployment controller updates a deployment at the same time we run apply and get a conflict? Wouldn't we delete the deployment, wait for it to fully delete, then recreate it?

Not sure if this is possible, if so, it indeed seems like an issue. However, the desired outcome would be not to simply skip reconciling, but to pick up the updated deployment and perform reconcile on it, right? The code you linked includes retries for the patch operation, shouldn't it resolve the problem?

Note the problem that I'm trying to address here: Addon Manager fails to reconcile some addons and the reconcile loop breaks. I believe the right solution would be to force reconciling immutable objects. If there are risks to it, we have to think of another solution. For example, can we add a logic that resumes the reconcile loop, so that `kubectl apply` on a single object doesn't affect all other objects?

**Comment by apelisse** [comment]
I'm not an expert of client-side apply, adding people who wrote/reviewed the change: @dixudx @soltysh

**Comment by soltysh** [comment]
`--force` in apply is enforced when a conflict occurs or in case of invalid resources. So what @mikedanese writes holds true, I don't have the option to verify how this affects addon manager, but I can speak about using `--force` is very dangerous and I'd discourage from using it in automated scripts.

**Pull request closed without merging**
