### PR TITLE
Adds support for multiple resources to kubectl

### LINKED ISSUE #3050: kubectl commands should support multiple resources
Currently, it could not delete multiple pods at once, need to delete them one by one, it's very inconvenient if I have tons of pods to delete.

Unlike docker, docker can multiple stop/rm containers/images at once.

    # kubectl delete pods cae4affd-8726-11e4-bf50-0023ae9d8532,b30089bd-8726-11e4-bf50-0023ae9d8532
    F1219 10:34:57.539428   29761 delete.go:60] pod "cae4affd-8726-11e4-bf50-0023ae9d8532,b30089bd-8726-11e4-bf50-0023ae9d8532" not found

    # kubectl delete pods cae4affd-8726-11e4-bf50-0023ae9d8532 b30089bd-8726-11e4-bf50-0023ae9d8532
    E1219 10:35:02.354295   29767 cmd.go:132] If passing in command line parameters, must be resource and name
    E1219 10:35:02.354350   29767 cmd.go:133] See 'kubectl delete -h' for help.

### PR DESCRIPTION
**Pull request by kbeecher**
You can specify multiple resources by name when using the delete, get
and stop commands.

Resolves #3050

### CODE REVIEW

**Comment by kbeecher** [comment]
I had already set up and signed a CLA using my endocode.com address. However, the email address on my GitHub account was not an endocode.com one.

I have updated my account so that the primary email is the same which I used to sign the CLA.

**Comment by vmarmol** [comment]
Assigning to @brendanburns 

@kbeecher I can't seem to find your CLA :( I see an info@ address, is that yours?

Do you see it in: https://cla.developers.google.com/clas

**Comment by bgrant0607** [comment]
cc @smarterclayton

**Comment by smarterclayton** [comment]
LGTM - thanks for adding tests

**Comment by bgrant0607** [comment]
@kbeecher Did you intend for that to be a corporate CLA? It was registered as a user CLA.

**Comment by kbeecher** [comment]
@vmarmol @bgrant0607 The CLA was definitely a corporate one, I have it in my inbox now. I entered the info@ address because the CLA needed a Google Group for our contributors.

**Comment by bgrant0607** [comment]
Thanks a lot.

**Pull request merged**
