### PR TITLE
Update ginkgo and bolt Godeps so k8s builds on ARM64

### PR DESCRIPTION
**Pull request by luxas**
Required for #19769. 
Related to: #19712

@mikedanese @gmarek @eparis @wojtek-t @brendandburns @zmerlynn @ixdy @thockin

### CODE REVIEW

**Comment by ixdy** [comment]
ok to test

**Comment by luxas** [comment]
Without this patch ARM64 fails with these errors:
```
# github.com/boltdb/bolt
Godeps/_workspace/src/github.com/boltdb/bolt/db.go:85: undefined: maxMapSize
Godeps/_workspace/src/github.com/boltdb/bolt/db.go:85: invalid array bound maxMapSize
# github.com/onsi/ginkgo/internal/remote
Godeps/_workspace/src/github.com/onsi/ginkgo/internal/remote/output_interceptor_unix.go:34: undefined: syscall.Dup2
Godeps/_workspace/src/github.com/onsi/ginkgo/internal/remote/output_interceptor_unix.go:35: undefined: syscall.Dup2
```
The bolt issue is fixed here: boltdb/bolt#435
and I fixed onsi/ginkgo here: onsi/ginkgo#209

With this PR, `arm64` we will have full `arm64` support and #19769 can be merged
@lavalamp @ixdy @zmerlynn

**Comment by ixdy** [comment]
I think this is fine? This bumps bolt from 1.0 to 1.1; nothing in Kubernetes appears to use it directly, though several other Godeps do. I'm not sure who's a good person to decide whether this is safe.

**Comment by luxas** [comment]
I'm not an expert either... The builds are passing at least, and I don't think `bolt` can have changed that much between `1.0` and `1.1`, but one can never know for sure.

I think we should merge it cause it passes. WDYT @mikedanese?
We bumped `kr/pty` earlier without any problems so far

**Comment by ixdy** [comment]
Release notes for boltdb 1.1 are [here](https://github.com/boltdb/bolt/releases/tag/v1.1.0).

Looks like it's used by
* coreos/etcd
* hashicorp/raft-boltdb
* influxdb/influxdb

**Comment by mikedanese** [comment]
I'm fine with this. Tests pass.

> Looks like it's used by
> 
> coreos/etcd
> hashicorp/raft-boltdb
> influxdb/influxdb

Looks like a case of spaghetti imports. Where are all these invisible boltdbs??

**Comment by ixdy** [comment]
@mikedanese I just grep'd our repo, and all of the imports for bolt/boltdb were under Godeps as listed.

**Comment by lavalamp** [comment]
LGTM - @ixdy we'll want to pay attention to all the other e2e jenkins tests after this merges, on the off chance that something about the e2e test output breaks.

**Comment by ixdy** [comment]
@k8s-bot test this issue: #IGNORE
ok to test

**Pull request merged**
