### PR TITLE
Revert "kube-proxy: check KUBE-MARK-DROP"

### LINKED ISSUE #85414: [Flaky test] gce-cos-master-alpha-features (ci-kubernetes-e2e-gci-gce-alpha-features)
**Which jobs are failing**:
gce-cos-master-alpha-features

**Which test(s) are failing**:
[sig-network] Networking should recreate its iptables rules if they are deleted [Disruptive]

**Since when has it been failing**:
as far as testgrid can see, since forever, it's like ... 10% flake

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features

**Reason for failure**:
```
I1118 07:39:08.800] [1mSTEP[0m: Deleting pod execpod-6v4xj in namespace nettest-1831
I1118 07:39:08.844] [1mSTEP[0m: verifying that kubelet rules are eventually recreated
I1118 07:44:10.242] Nov 18 07:44:10.241: FAIL: kubelet did not recreate its iptables rules
I1118 07:44:10.243] Unexpected error:
I1118 07:44:10.244]     <*errors.errorString | 0xc0000d9950>: {
I1118 07:44:10.244]         s: "timed out waiting for the condition",
I1118 07:44:10.244]     }
I1118 07:44:10.244]     timed out waiting for the condition
I1118 07:44:10.244] occurred
I1118 07:44:10.244] [1mSTEP[0m: deleting ReplicationController iptables-flush-test in namespace nettest-1831, will wait for the garbage collector to delete the pods
I1118 07:44:10.455] Nov 18 07:44:10.455: INFO: Deleting ReplicationController iptables-flush-test took: 41.88912ms
```

**Anything else we need to know**:
/cc @kubernetes/ci-signal
/sig network
/priority important-soon
/milestone v1.17

### PR DESCRIPTION
**Pull request by aojea**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

This reverts commit 1ca0ffeaf2c4401549b82f549f7481313308d4b9.

kube-proxy is not recreating the rules associated to the
KUBE-MARK-DROP chain, that is created by the kubelet.

Is preferrable to avoid the dependency between the kubelet and
kube-proxy, so each of them handles their own rules.

**Which issue(s) this PR fixes**:

Fixes #85414

**Special notes for your reviewer**:

This is only needed for kube-proxy operating in dual-stack with iptables, and that PR wasn't merged.
Also, there is a discussion about this topic with a better solution than this
https://github.com/kubernetes/kubernetes/issues/82125#issuecomment-553255113

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @danwinship @thockin 

my apologies for introducing this bug 
/sig network

**Comment by danwinship** [comment]
Ugh, yeah, it looks like every time the proxier syncs, it deletes the contents of kubelet's `KUBE-MARK-DROP` chain. That's bad. (The fact that we apparently have no tests that `KUBE-MARK-DROP` is working correctly is also bad.)

So this fix is correct, and removing it won't break anything ([because it was only half of the fix anyway](https://github.com/kubernetes/kubernetes/pull/84422#issuecomment-549169717)) and this is absolutely needed for 1.17, beyond just fixing the flaky test.

/lgtm
/approve

(I don't have milestone bits either but @thockin should notice this when he gets back to work. Or it looks like @khenidak could set the milestone.)

**Comment by danwinship** [comment]
> (The fact that we apparently have no tests that `KUBE-MARK-DROP` is working correctly is also bad.)

#85572

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-gce
timed out :thinking:

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-gce
Failed test
k8s.io] Pods should support pod readiness gates [NodeFeature:PodReadinessGate

**Pull request merged**
