### PR TITLE
test/e2e/framework:move functions to test/e2e/scheduling/

### PR DESCRIPTION
**Pull request by tanjunchen**
**What type of PR is this?**
 
 /kind cleanup
 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

ref:https://github.com/kubernetes/kubernetes/issues/86052

**Special notes for your reviewer**:

ObserveNodeUpdateAfterAction and ObserveEventAfterAction are only used in e2e scheduling  tests.
So this moves the function to them.

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by oomichi** [comment]
Nice work.

/lgtm

**Comment by tanjunchen** [comment]
/cc @SataQiu 
could you review this pr?Thanks

**Review by SataQiu — COMMENTED** [review]
Thanks @tanjunchen !
/lgtm
/approve

**Pull request merged**
