### PR TITLE
updated fluentd to 1.2.4

### PR DESCRIPTION
**Pull request by monotek**
**What this PR does / why we need it**: 
* updates fluentd in fluentd-elasticsearch to version 1.2.4
* also updates activesupport, fluent-plugin-elasticsearch & oj gems

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
* updates fluentd in fluentd-elasticsearch to version 1.2.4
* also updates activesupport, fluent-plugin-elasticsearch & oj gems
```

### CODE REVIEW

**Comment by neolit123** [comment]
@monotek
please add a release note.
/ok-to-test

**Comment by monotek** [comment]
release notes added...

**Review by dixudx — APPROVED** [review]
/lgtm

Please update `cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml` accordingly to use latest v2.3.0 after this PR gets merged.

**Comment by monotek** [comment]
@coffeepac 

Seems theres is still no automatic build of the image: 

https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/fluentd-elasticsearch?gcrImageListsize=50

Are these build jobs available in a repo, where i can contribute? 
If so, where?

**Comment by coffeepac** [comment]
nope.  this is a google-internal image.  Its on my list to make it not that.  I'll file an issue against myself so I stop letting it fall off my list.

**Comment by aleks-mariusz** [comment]
any ideas when this will be generally available publicly to start using ?

**Comment by coffeepac** [comment]
@aleks-mariusz I'm waiting for https://github.com/kubernetes/kubernetes/pull/67484#issuecomment-413624916 to get merged before I ask a googler to build.  they can kick both jobs off at once.  after that it will take ~24 hours.  

Due to team geography (Ie:  they're sleeping soon) I expect this will take ~36 hours

**Comment by aleks-mariusz** [comment]
cool, but i saw a typo in that issue (the first part of the commit has 6.3.2 but the second has 6.3.0).. made a mention of this on that issue as well.

**Pull request merged**
