### PR TITLE
bump kube-ui addon version to v2

### PR DESCRIPTION
**Pull request by mikedanese**

### CODE REVIEW

**Comment by mikedanese** [comment]
Flake. @k8s-bot ok to test

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by timstclair** [comment]
Where's this coming from? The kube-ui [makefile](https://github.com/kubernetes/kube-ui/blob/master/Makefile) still says the current version is 1.1, but maybe someone forgot to update it when they pushed v2?

**Comment by mikedanese** [comment]
This is in conjunction with kubernetes/kube-u#27

**Comment by timstclair** [comment]
Ah, sorry, I missed those. LGTM

**Comment by sttts** [comment]
I have tested the v2 image behind a nginx reverse proxy, resembling the setup we have in DCOS. Everything looks fine.

LGTM.

**Comment by mikedanese** [comment]
```
Summarizing 1 Failure:

[Fail] Services [It] should serve multiport endpoints from pods 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1147

Ran 85 of 148 Specs in 638.230 seconds
FAIL! -- 84 Passed | 1 Failed | 2 Pending | 61 Skipped 
```

Looks like a flake.

@k8s-bot ok to test

**Comment by mikedanese** [comment]
```
Summarizing 2 Failures:

[Fail] Probing container [It] with readiness probe should not be ready before initial delay and never restart 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:59

[Fail] Services [It] should serve a basic endpoint from pods 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1147

Ran 85 of 149 Specs in 519.349 seconds
FAIL! -- 83 Passed | 2 Failed | 2 Pending | 62 Skipped 
```

@k8s-bot ok to test

**Comment by mikedanese** [comment]
```
Ran 86 of 150 Specs in 565.789 seconds
SUCCESS! -- 86 Passed | 0 Failed | 2 Pending | 62 Skipped 
```
All tests passed and still failed. That's tree flakes in a row. @ixdy @ArtfulCoder is PR builder flaky right now?

**Pull request merged**
