### PR TITLE
use copy() instead of a loop

### PR DESCRIPTION
**Pull request by wongearl**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

use copy() instead of a loop

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
