### PR TITLE
[1.18] Fix DS expectations on recreate

### PR DESCRIPTION
**Pull request by tnozicka**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
backport of https://github.com/kubernetes/kubernetes/pull/91915

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cc @soltysh

### CODE REVIEW

**Comment by tnozicka** [comment]
/shrug
verify is timing out but reporting 28/28 passed

/retest

**Review by soltysh — APPROVED** [review]
/lgtm
ping @kubernetes/release-managers for cherry-pick approval

**Comment by tnozicka** [comment]
@kubernetes/release-managers ptal

**Pull request merged**
