### PR TITLE
pkg/scheduler: Replace deprecated func usage from the `k8s.io/utils/pointer` pkg

### PR DESCRIPTION
**Pull request by ialidzhikov**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
See https://github.com/kubernetes/kubernetes/pull/111585 and https://github.com/kubernetes/kubernetes/pull/111585#issuecomment-1214203495.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/approve

**Comment by ialidzhikov** [comment]
Looks like in this PR I wrongly introduced adaptations in the `pkg/util/tolerations/tolerations_test.go`. This PR should be only for `pkg/scheduler`. That's why I will revert the changes in `pkg/util/tolerations/tolerations_test.go` - as because of this it requires approval from `pkg/OWNERS` and not `pkg/scheduler/OWNERS`.

**Pull request merged**
