### PR TITLE
Update the template to version 1.2.1

### PR DESCRIPTION
**Pull request by aabed**

### CODE REVIEW

**Comment by aabed** [comment]
I signed it!

**Comment by aabed** [comment]
@thockin is there something blocking the merge, shall I change anything

Thanks

**Comment by aabed** [comment]
@thockin is there something wrong?

**Comment by thockin** [comment]
All docs have moved.  The bot said:

```
Adding label:do-not-merge because PR changes docs prohibited to auto merge
See http://kubernetes.io/editdocs/ for information about editing docs
```

Please re-apply this PR to the new docs repo.

**Pull request closed without merging**
