### PR TITLE
Promote LocalStorageCapacityIsolationFSQuotaMonitoring to beta

### LINKED ISSUE #79040: Graduate LocalStorageCapacityIsolationFSQuotaMonitoring to beta
**What would you like to be added**:

LocalStorageCapacityIsolationFSQuotaMonitoring allows use of XFS-style quotas to monitor emptydir storage consumption.  It is alpha in 1.15; graduate it to beta in 1.16

**Why is this needed**:

Monitoring by quota is a lot more efficient than monitoring by du.

xref https://github.com/kubernetes/enhancements/issues/1029

### PR DESCRIPTION
**Pull request by RobertKrawitz**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Graduate LocalStorageCapacityIsolationFSQuotaMonitoring to beta

**Which issue(s) this PR fixes**:

Fixes #79040

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: Yes
```release-note

Use of filesystem quotas to monitor consumption of EmptyDir volumes is graduating to beta.

`LocalStorageCapacityIsolationFSQuotaMonitoring`: When `LocalStorageCapacityIsolation` is enabled for [local ephemeral storage](/docs/concepts/configuration/manage-compute-resources-container/) and the backing filesystem for [emptyDir volumes](/docs/concepts/storage/volumes/#emptydir) supports project quotas and they are enabled, use project quotas to monitor [emptyDir volume](/docs/concepts/storage/volumes/#emptydir) storage consumption rather than filesystem walk for better performance and accuracy.
```
xref https://github.com/kubernetes/enhancements/issues/1029

### CODE REVIEW

**Comment by dashpole** [comment]
This should probably wait until after we have agreed on beta criterion ;).  One of the items required for beta is user feedback.  Do we have any of that yet, since it was only merged recently?

**Comment by RobertKrawitz** [comment]
Well, 1.15 was only just released :-)  I agree that this should wait, but I wanted to get the KEP update and the PR out.

**Review by derekwaynecarr — CHANGES_REQUESTED** [review]
Do we have the data from the identified beta criteria documented?

see:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/20180906-quotas-for-ephemeral-storage.md#phase-2-beta-target-116

**Pull request closed without merging**
