### PR TITLE
Automated cherry pick of #106599: Fix Bugs in CPUManager distribute NUMA policy option

### PR DESCRIPTION
**Pull request by klueska**
Cherry pick of #106599 on release-1.23.

#106599: Fix Bugs in CPUManager distribute NUMA policy option

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
None
```

### CODE REVIEW

**Comment by fromanirh** [comment]
/lgtm
trivial cherry-pick

**Comment by klueska** [comment]
@kubernetes/release-managers please review.

**Comment by cpanato** [comment]
@klueska this is only needed for 1.23 branch?

**Comment by klueska** [comment]
Yes. The feature that these bug fixes target was only added in 1.23, but the bug fixes themselves didn't make it in before the release.

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
