### PR TITLE
KEP-4222: Add duplicate key and field case-sensitivity CBOR decode tests.

### PR DESCRIPTION
**Pull request by dinhxuanvu**
1. Test: Decoding map with duplicate keys into struct or map produces error
2. Test: Decoding a map into a Go struct matches json field tag names case-sensitively

#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: [<link>](https://kep.k8s.io/4222)
```

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
This PR is a follow-up of #123267 to increase test coverage for CBOR serializer.
/cc @deads2k 
PTAL. Thanks

**Comment by benluddy** [comment]
/retitle KEP-4222: Add duplicate key and field case-sensitivity CBOR decode tests.

**Pull request merged**
