### PR TITLE
Remove the Heapster/InfluxDB test

### PR DESCRIPTION
**Pull request by DirectXMan12**
Heapster is now deprecated, and we shouldn't be testing Influx
functionality here anyway (that test belongs in the Heapster repo at
best anyway).

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by DirectXMan12** [comment]
cc @kubernetes/sig-instrumentation-pr-reviews

**Comment by loburm** [comment]
But this is not going to be cherry-picked in 1.11, isn't it?

**Comment by DirectXMan12** [comment]
@loburm I wasn't initially planning on it, why?

**Comment by loburm** [comment]
Just wanted to ensure that those tests are not going to be removed from 1.11 testing pipeline.
/lgtm

**Comment by tpepper** [comment]
@DirectXMan12 I'm wondering if this commit is related to a new test failure in https://k8s-testgrid.appspot.com/sig-release-master-blocking#verify:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-verify-master/22119

**Comment by DirectXMan12** [comment]
@tpepper yeah, I've got a patch coming along.  Forgot to remove stuff from godeps after it was no longer needed.

**Comment by serathius** [comment]
@DirectXMan12 Looks like you didn't clean up the test suite https://k8s-testgrid.appspot.com/sig-instrumentation#gce-influxdb
For 1.11 Influxdb is no longer part of pull tests, so it will not be tested

**Pull request merged**
