### PR TITLE
Replace docker/distribution with distribution/distribution/v3

### LINKED ISSUE #103849: Migrate from github.com/docker/distribution to github.com/distribution/distribution/v3
#### What happened:
Kubernetes libraries have a dependency on `github.com/docker/distribution`
#### What you expected to happen:
Kubernetes libraries have a dependency on `github.com/distribution/distribution/v3`. Note the github org just changed, its the same project. I believe the v2 -> v3 was mostly to get around go.mod weirdness with versions, rather than large breaking changes, but am not sure.
#### How to reproduce it (as minimally and precisely as possible):
Look at go.mod, I suppose

#### Anything else we need to know?:
`github.com/docker/distribution@v2.7.1+incompatible`, the library in use, is 2.5 years old. It does not have a go.mod file, and in turn depends on a bunch of other libraries without go.mod files. This generally makes importing these libraries a pain - you can see 350 projects needing to add `replace` hacks to go.mod to work around these issues: https://github.com/search?q=%22replace+github.com%2Fdocker%2Fdistribution%22&type=code

It would be great to upgrade to the latest version.

### PR DESCRIPTION
**Pull request by howardjohn**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Replace docker/distribution with distribution/distribution/v3. See #103849 for motivation
#### Which issue(s) this PR fixes:
Fixes #103849

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
Let's please wait for things to shake out https://github.com/kubernetes/kubernetes/issues/103849#issuecomment-885042301 

this is too many dependencies in our tree than we should be letting in. also concerned about all the transitive-y deps that point to personal repos in the go.sum.

at the very least let's wait till docker/docker switches. thanks!

cc @liggitt

**Comment by liggitt** [comment]
> I have no problem with that, but if I understand right most/all of the new dependencies are not actually new - they were just hidden since docker/distribution doesn't use a go.mod. All of the ones I spot-checked are in https://github.com/distribution/distribution/blob/v2.7.1/vendor.conf. Not sure how big of a difference that makes though - go modules interacting with non-go.mod repos is not something I am familiar with

unused transitive dependencies now being in go.mod actually makes the situation for us worse... it makes `go` consider all of those transitives when resolving minimum required versions and increases the likelihood of problematic cycles or gridlock

**Comment by howardjohn** [comment]
Closing per discussion above

**Pull request closed without merging**
