### PR TITLE
Fix bug in federated ingress e2e test. Fixes #33350

### LINKED ISSUE #33350: Follow up Federated Ingress test failures and address review comments in PR #33339
PR #33339 fixes a known bug but it still does not fix all the Federated Ingress test failures. So this is a note to follow up on those failures and address the optional review comments left in the PR.

cc @kubernetes/sig-cluster-federation @nikhiljindal

### PR DESCRIPTION
**Pull request by ghost**
Replaced previous description, which no longer applies now that the bug is found and fixed...

Symptom:
Sep 23 21:13:36.750: INFO: Waiting for Ingress federated-ingress to acquire IP, error an empty namespace may not be set when a resource name is provided.

Bug:
CreateIngressOrFail() function takes a namespace argument, but doesn't include that explicitly in the creation request, and then returns the request (in which namespace is "") rather than the response (in which namespace is correctly set).  This unset namespace is in turn used later, and results in the abovementioned error.

Fix: 
Return the response from the ingress creation request, rather than the request itself.

Also some minor comment cleanup.

cc @mfanjie @kubernetes/sig-cluster-federation FYI

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33372)

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@k8s-bot federation gce e2e test this

**Comment by quinton-hoole** [comment]
The federation e2e tests failed due to a quota issue.  Should be resolved shortly.

https://github.com/kubernetes/kubernetes/issues/33357

**Comment by quinton-hoole** [comment]
I've verified that that the federation control plane comes up just fine in another project, and @madhusudancs has verified that it works again on Jenkins now that he's cleared the leaked test resources to free up some quota.

**Comment by quinton-hoole** [comment]
I'm running e2e tests on a locally created GCE cluster (from HEAD), but in the mean time, run them on Jenkins too, to gather more data:

@k8s-bot federation gce e2e test this

**Comment by quinton-hoole** [comment]
OK, some progress.  I got 2 of the three ingress tests passing.  The only one failing now is:

Fail] [k8s.io] Federated ingresses [Feature:Federation] Federated Ingresses Ingress connectivity and DNS [BeforeEa
ch] should be able to connect to a federated ingress via its load balancer 

Busy debugging that.  I suspect it may be as simple as a timeout that needs adjustment, given how long and unpredictable L7 loadbalancer setup times are on GCE.

**Comment by quinton-hoole** [comment]
Because I have all of the tests running locally, I don't imagine it will take me long to find and fix this bug now.

**Comment by quinton-hoole** [comment]
OK, there is at least one bug in the test itself.  The test is omitting the namespace in a get call.

Sep 23 21:13:36.750: INFO: Waiting for Ingress federated-ingress to acquire IP, error an empty namespace may not be set when a resource name is provided.

Other than that, looking at the outcome of the test, it's a pass: Identical ingresses, sharing the same external IP, are created in all clusters.

federation-e2e-gce-us-central1-f
{
    "kind": "Ingress",
    "apiVersion": "extensions/v1beta1",
    "metadata": {
        "name": "federated-ingress",
        "namespace": "e2e-tests-federated-ingress-6qhax",
        "selfLink": "/apis/extensions/v1beta1/namespaces/e2e-tests-federated-ingress-6qhax/ingresses/federated-ingress",
        "uid": "d10a86bf-81df-11e6-98a7-42010af00002",
        "resourceVersion": "26745",
        "generation": 1,
        "creationTimestamp": "2016-09-23T22:48:16Z",
        "annotations": {
            "ingress.kubernetes.io/backends": "{\"k8s-be-30435--41a24f5324298728\":\"Unknown\"}",
            "ingress.kubernetes.io/forwarding-rule": "k8s-fw-e2e-tests-federated-ingress-6qhax-federated-ingress--410",
            "ingress.kubernetes.io/target-proxy": "k8s-tp-e2e-tests-federated-ingress-6qhax-federated-ingress--410",
            "ingress.kubernetes.io/url-map": "k8s-um-e2e-tests-federated-ingress-6qhax-federated-ingress--410"
        }
    },
    "spec": {
        "backend": {
            "serviceName": "testingress-service",
            "servicePort": 80
        }
    },
    "status": {
        "loadBalancer": {
            "ingress": [
                {
                    "ip": "130.211.39.83"
                }
            ]
        }
    }
}
federation-e2e-gce-us-central1-b
{
    "kind": "Ingress",
    "apiVersion": "extensions/v1beta1",
    "metadata": {
        "name": "federated-ingress",
        "namespace": "e2e-tests-federated-ingress-6qhax",
        "selfLink": "/apis/extensions/v1beta1/namespaces/e2e-tests-federated-ingress-6qhax/ingresses/federated-ingress",
        "uid": "ba7f4ad9-81df-11e6-a0fc-42010af00006",
        "resourceVersion": "26783",
        "generation": 1,
        "creationTimestamp": "2016-09-23T22:47:38Z",
        "annotations": {
            "ingress.kubernetes.io/backends": "{\"k8s-be-30435--41a24f5324298728\":\"Unknown\"}",
            "ingress.kubernetes.io/forwarding-rule": "k8s-fw-e2e-tests-federated-ingress-6qhax-federated-ingress--410",
            "ingress.kubernetes.io/target-proxy": "k8s-tp-e2e-tests-federated-ingress-6qhax-federated-ingress--410",
            "ingress.kubernetes.io/url-map": "k8s-um-e2e-tests-federated-ingress-6qhax-federated-ingress--410"
        }
    },
    "spec": {
        "backend": {
            "serviceName": "testingress-service",
            "servicePort": 80
        }
    },
    "status": {
        "loadBalancer": {
            "ingress": [
                {
                    "ip": "130.211.39.83"
                }
            ]
        }
    }
}

**Comment by nikhiljindal** [comment]
Thanks for the great debugging and fixing this @quinton-hoole!

Code changes LGTM.
Feel free to self apply the label, once we have a passing federation e2e.

**Comment by nikhiljindal** [comment]
@k8s-bot federation gce e2e test this

**Comment by madhusudancs** [comment]
@k8s-bot federation gce e2e test this

**Comment by nikhiljindal** [comment]
Is this still active?

**Comment by quinton-hoole** [comment]
Yes, I think we still need to merge this.
I will chase it down.

**Comment by quinton-hoole** [comment]
Replaced by #33977 . Closing.

**Pull request closed without merging**
