### PR TITLE
support fc volume attach and detach

### LINKED ISSUE #48953: Need to enforce RWO for FC PV
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
RWO FC PV is not enforced. As a result, such PV can be attached to multiple nodes and led to data corruption.

**What you expected to happen**:
RWO FC PV should be single attached

**How to reproduce it (as minimally and precisely as possible)**:
- Create a FC PV
- Create 2 Pods that claim this FC PV
- If Pods are running on different nodes, the PV is multi attached

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by rootfs**
**What this PR does / why we need it**:
Support FC volume attach and detach to enforce RWO access

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #48953

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rootfs** [comment]
@brendandburns @deads2k can you approve?

**Comment by brendandburns** [comment]
/lgtm

@rootfs is there an issue for this?

**Comment by rootfs** [comment]
@brendandburns Not yet, I'll create an issue. Thanks!

**Comment by rootfs** [comment]
@brendanburns can you add lgtm again? thanks!

**Comment by rootfs** [comment]
@kubernetes/sig-storage-pr-reviews

**Comment by jsafrane** [comment]
IMO, there should be a common implementation both for iSCSI and FC, both provide a block device and can't have 3rd party attach/detach.

**Comment by rootfs** [comment]
@jsafrane I am working on iscsi. Will see how much commonality between the two.

**Comment by mtanino** [comment]
@rootfs @jsafrane 
>>IMO, there should be a common implementation both for iSCSI and FC, both provide a block device and can't have 3rd party attach/detach.

Can't we expose attach/detach interface for 3rd party vendor usage at FC driver?
It might be similar to flex volume driver.

**Comment by rootfs** [comment]
@mtanino the idea is to use attach/detach as "soft fencing":  no FC/iSCSI vendor API or SCSI reservation is thus needed.

**Comment by mtanino** [comment]
@rootfs 
Sorry for the confusion, my question wasn't about for this attach/detach implementation.
In my understanding, iSCSI has similar functionality of attach/detach using iscsiadm command in setup/teardown path but FC doesn't.(jsut call echo > /sys/... and find SCSI disk)

Therefore, if we'll implement attach/detach path to FC, I think it might worth to have a functionality to expose them for 3rd party vendor usage IN THE FUTURE.

**Comment by rootfs** [comment]
@mtanino I see your point. Yes FA SAN zoning logically belongs to attach/detach controller.

**Comment by mtanino** [comment]
@rootfs 
Yeah, I suppose those two candidates.

- FA SAN zoning
- Storage Group/Host Group creation and configuration (*1)
  This create a group to expose volumes to specific server(In iSCSI storage, this called iSCSI target)

(*1)
http://www.storagefreak.net/2015/01/emc-vnx-how-to-create-a-storage-group
http://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.vs-irrg%2FGUID-7B383DBD-ED07-4687-8794-6CE21C1628AD.html

**Comment by brendandburns** [comment]
@rootfs is this ready to merge?

**Comment by rootfs** [comment]
@brendandburns thanks!

**Pull request merged**
