### PR TITLE
Use e2e framework log instead of sub one

### PR DESCRIPTION
**Pull request by gavinfish**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Remove log subpackage and use log from core e2e framework. This is a follow up of #81426.

**Which issue(s) this PR fixes**:

Ref: #81232
Ref: #81245

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by gavinfish** [comment]
/hold
Since some core e2e test framework still depend on sub ones, this change will cause cycle in dependency error. Wait for #81245.

**Comment by fejta** [comment]
Please rebase and pass tests

**Pull request closed without merging**
