### PR TITLE
Updating Calico to v2.6.1

### PR DESCRIPTION
**Pull request by heschlie**
**What this PR does / why we need it**:

Updating Calico to the most recent release v2.6.1.

[Release page](https://docs.projectcalico.org/v2.6/releases/) and [blog post](https://www.projectcalico.org/project-calico-2-6-released/)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by heschlie** [comment]
CC @caseydavenport

**Comment by caseydavenport** [comment]
This adds support for Egress and CIDR network policy, which was added in k8s v1.8.


I think we should get this cherry picked into the v1.8 branch.

**Pull request merged**
