### PR TITLE
[WIP] Experiments with containerd/runc DO NOT MERGE -- Another containerd commit (7699c5e9)

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/cc @dims @liggitt 
xref: 7699c5e9

### CODE REVIEW

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/91786

**Comment by BenTheElder** [comment]
mhmmm https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/91790/pull-kubernetes-e2e-gce-ubuntu-containerd/1268637240855105536/
> [k8s.io] [sig-node] Pods Extended [k8s.io] Pod Container Status should never report success for a pending container

**Comment by dims** [comment]
`[k8s.io] [sig-node] Pods Extended [k8s.io] Pod Container Status should never report success for a pending container `

/test pull-kubernetes-e2e-gce-ubuntu-containerd

**Comment by dims** [comment]
unrelated failure
/test pull-kubernetes-e2e-gce-ubuntu-containerd

**Pull request closed without merging**
