### PR TITLE
Remove direct reference to label

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Remove direct reference to Prometheus.Label.

To get [metrics stability](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20190404-kubernetes-control-plane-metrics-stability.md) into Beta, we will make it illegal to directly import prometheus methods in Kubernetes components.

**Which issue(s) this PR fixes**:
Refer #https://github.com/kubernetes/enhancements/issues/1238

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

/milestone v1.17
/priority important-soon
/assign @k82cn

### CODE REVIEW

**Review by wgliang — APPROVED** [review]
/lgtm

**Comment by Huang-Wei** [comment]
/hold

There are still some references to `prometheus` in the scheduler codebase. Can you finish them in one PR? I don't think it's worth splitting them into several PRs. (e.g., #82741 and this one and further ones)

In terms of scheduler codebase, I mean:

- cmd/kube-scheduler/
- pkg/scheduler/
- testing code (I checked and there are no references to prometheus)

**Comment by RainbowMango** [comment]
@Huang-Wei 
* cmd/kube-scheduler/ :  Seems no reference to prometheus now.
* pkg/scheduler/: current PR.
* testing code (I checked and there are no references to prometheus)  ,  yes, no reference to prometheus.

By the way,  #82741 and the current are in different iterations.

**Comment by Huang-Wei** [comment]
@RainbowMango I'd like to use this chance to get rid of stuff under `cmd/*`:

```
⇒  ag prometheus cmd/kube-scheduler
cmd/kube-scheduler/BUILD
25:        "//staging/src/k8s.io/component-base/metrics/prometheus/clientgo:go_default_library",

cmd/kube-scheduler/scheduler.go
28:	_ "k8s.io/component-base/metrics/prometheus/clientgo"
```

And `pkg/scheduler/*`:

```
pkg/scheduler/internal/queue/BUILD
44:        "//vendor/github.com/prometheus/client_model/go:go_default_library",

pkg/scheduler/internal/queue/scheduling_queue_test.go
26:	dto "github.com/prometheus/client_model/go"
1224:// TestPendingPodsMetric tests Prometheus metrics related with pending pods
```

Not sure they have equivalent implementations in the `k8s.io/component-base/metrics` repo.

**Comment by RainbowMango** [comment]
@Huang-Wei 
Thanks for the quick response.

> 25:        "//staging/src/k8s.io/component-base/metrics/prometheus/clientgo:go_default_library",
> 28:	_ "k8s.io/component-base/metrics/prometheus/clientgo"

We intend to remove the direct reference to `prometheus.xxx`, and replace them by `metrics.xxx`.
`"k8s.io/component-base/metrics/prometheus/clientgo"` belongs to k/k and it is expected.

> 44:        "//vendor/github.com/prometheus/client_model/go:go_default_library",
> 26:	dto "github.com/prometheus/client_model/go"

`component-base/metrics` does not have the substitute for `dto.Metric` and `metrics.GaugeMetric` interface maybe updated accordingly.
Thanks for help me identify the problem. I'll investigate it more and put it to the next iteration.

**Comment by Huang-Wei** [comment]
@RainbowMango Thanks for the explanation.

/hold cancel

**Pull request merged**
