### PR TITLE
Delete hpa first before deleting the resources it controls in test-cmd.sh

### LINKED ISSUE #21716: integration flake: In hack/test-cmd.sh, get unexpected frontend pod
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/21713/kubernetes-pull-test-unit-integration/15643/?debugUI=CLOUD
```
I0222 14:50:43.494360    9763 event.go:211] Event(api.ObjectReference{Kind:"ReplicationController", Namespace:"default", Name:"frontend", UID:"b32e8642-d9b6-11e5-ba54-0242ac110002", APIVersion:"v1", ResourceVersion:"1033", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: frontend-9i1jc
replicationcontroller "frontend" deleted
I0222 14:50:43.915532    9763 replication_controller.go:422] Replication Controller has been deleted default/frontend
horizontalpodautoscaler "frontend" deleted

FAIL!
Get pods {{range.items}}{{.metadata.name}}:{{end}}
  Expected: 
  Got:      frontend-9i1jc:
(B
711 ./hack/test-cmd.sh
(B
!!! Error in ./hack/test-cmd.sh:51
  'return 1' exited with status 1
```

Looks like in `hack/test-cmd.sh` L707, pod frontend-9i1jc hasn't been deleted by `kubectl delete rc,hpa frontend "${kube_flags[@]}"` before we check that no pod exists. Maybe it's related to delete grace period.

cc @caesarxuchao

### PR DESCRIPTION
**Pull request by janetkuo**
Fixes #21716

cc @kubernetes/kubectl @kubernetes/autoscaling

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM, Thanks!

**Comment by bgrant0607** [comment]
@k8s-oncall: I'm going to manually merge this once tests pass in order to fix test flakes.

**Comment by kargakis** [comment]
Should the reaper delete the hpa too?

**Comment by bgrant0607** [comment]
@kargakis The reaper for which resource?

**Comment by kargakis** [comment]
> @kargakis The reaper for which resource?

If we set an hpa for a rc or a deployment then the respective reaper would somehow detect that hpa and delete it. Makes sense?

**Comment by eparis** [comment]
This PR is already included in the release-1.2 branch and does not require cherrypick-ing

**Pull request merged**
