### PR TITLE
Updating go-restful to generate "type":"object" instead of "type":"any" in swagger-spec (breaks kubectl 1.1)

### PR DESCRIPTION
**Pull request by nikhiljindal**
Updating go-restful to include https://github.com/emicklei/go-restful/pull/270 (replacing type "any" by type "object". Ref https://github.com/swagger-api/swagger-codegen/issues/2347 on why we want to do that)
Ref https://github.com/kubernetes/kubernetes/issues/4700#issuecomment-194719759

First commit generated using:

```
godep restore
go get -u github.com/emicklei/go-restful
godep update github.com/emicklei/go-restful
```

Second commit generated by running 

```
./hack/update-swagger-spec.sh
```

Third commit generated by running:

```
./hack/update-api-reference-docs.sh
```

cc @kubernetes/sig-api-machinery @bgrant0607

### CODE REVIEW

**Comment by nikhiljindal** [comment]
We can wait for 1.2 to wrap up before merging this to prevent cherrypick conflicts.

**Comment by quinton-hoole** [comment]
LGTM @nikhiljindal, but needs a rebase. We can remove the do-not-merge label as soon as that's done, and v1.2 has been branched (i.e. in the next few hours).

**Comment by nikhiljindal** [comment]
Rebased. Removing the needs-rebase and do-not-merge tags.

**Comment by nikhiljindal** [comment]
Adding back LGTM since its just a rebase

**Comment by nikhiljindal** [comment]
@k8s-bot integration test this please

**Comment by nikhiljindal** [comment]
The unit test breakage is real which seems to have been caused by a change in go-restful.
Filed https://github.com/emicklei/go-restful/issues/272

**Comment by quinton-hoole** [comment]
@nikhiljindal Let me know when this is ready to merge.  Assigning to you in the mean time.

**Comment by nikhiljindal** [comment]
Updated go-restful with the fix for https://github.com/emicklei/go-restful/issues/272 and all tests pass now.
Assigning back to @quinton-hoole

**Comment by quinton-hoole** [comment]
@nikhiljindal LGTM!

**Comment by nikhiljindal** [comment]
Updated the release note label and added back the LGTM label.

**Comment by nikhiljindal** [comment]
Actually I just realized that this will break old kubectl (that expects type "any") talking to new api server (that gives type "object").

Will discuss with @bgrant0607 once. Removing the LGTM tag in the meantime.

**Comment by nikhiljindal** [comment]
Discussed with @bgrant0607 and we decided that we should first update 1.2 kubectl to accept both type any and type object. Sent https://github.com/kubernetes/kubernetes/pull/24054 for that.
Then we can merge this PR to start generating type object in 1.3 apiserver.

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/pull/24054 is now submitted and cherrypicked in 1.2 so this PR is ready to go.

Rebased and the first commit is gone as https://github.com/kubernetes/kubernetes/pull/24129 updated go-restful.

This is now ready to go in and should go in soon since swagger spec is now broken on HEAD.
https://github.com/kubernetes/kubernetes/pull/24129 updated go-restful but did not update the spec (which should have been caught by the verify-swagger-spec script, if not for https://github.com/kubernetes/kubernetes/issues/24233).
Adding back the LGTM tag, since this was a trivial rebase.

**Comment by nikhiljindal** [comment]
Updated the title to reflect better release notes

**Comment by nikhiljindal** [comment]
cc @k8s-oncall since ./hack/verify-all.sh is currently broken on HEAD (but passes in our CI tests on jenkins and travis)

**Comment by ihmccreery** [comment]
> breaks kubectl 1.1

Our [versioning policy](https://github.com/kubernetes/kubernetes/blob/master/docs/design/versioning.md#supported-releases) states that we'll support back two minor versions, so v1.3 should support v1.1.  Why did we decide this was okay?

**Comment by nikhiljindal** [comment]
I discussed this with @bgrant0607 and he pointed out that that policy doesnt talk about kubectl version skew.
Users are going to have a bad time if they try to use 1.1 kubectl with 1.3 apiserver since we have changed a lot of things.

I am not sure if any of our docs explicitly talk about kubectl and master version skew.
Also, am not sure if validation was on by default in kubectl 1.1.
Will find out and reply.

**Comment by bgrant0607** [comment]
@ihmccreery Our version-skew policy is not clearly documented, and neither is the meaning of "support", but the "Supported Releases" section of that document is definitely not about version-skewed operation. See https://github.com/kubernetes/kubernetes/blob/master/docs/design/versioning.md#upgrades, for instance.

Practically speaking, kubectl even now isn't friendly to version-skewed operation. The most egregious problem is round-tripping #3955, which we plan to address in 1.3, but which means that any version of kubectl prior to 1.3 will still have that problem.

**Comment by ihmccreery** [comment]
Seems to me the implicit assertion here is that we support kubectl only one minor version back.  If so, we should document it as such.  This is going to cause pain when we release v1.3 for anyone still running a v1.1 kubectl.  Admittedly, no one "should" be, but...

**Comment by ihmccreery** [comment]
cc @kubernetes/goog-gke @roberthbailey

**Comment by roberthbailey** [comment]
I think the versioning policy was primarily created to account for the version skew between the master components and nodes. The best thing would be to make kubectl fail gracefully when it's incompatible with the apiserver and tell the user (kindly, without an arcane error or stack trace) that they should update. Supporting skew between the latest patch release of version 1.x and the new release of 1.y is important, because people will generally update one part of their system before the other (CLI tool / apiserver), but I don't think we need nearly as a wide a range as we intend for nodes. Also note that updating your CLI tool is quick and painless and doesn't have the side effect of possibly causing down time for your application. So encouraging updating it should be the default.

**Comment by erictune** [comment]
@nikhiljindal  Does this PR require action by the user when upgrading to 1.3.0?  (Think about non-developer users.) If so, please edit your first comment to have  a release-note block, like in https://github.com/kubernetes/kubernetes/pull/28132.  If not, please change to release-note-none.

**Comment by erictune** [comment]
@nikhiljindal if this is a breaking change, please update CHANGELOG.md.

**Pull request merged**
