### PR TITLE
fix typo in e2e test

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
failures looks not related

/lgtm
/retest

**Comment by qingsenLi** [comment]
/assign @tallclair @sjenning 
wait for approve label,thanks

**Review by alejandrox1 — APPROVED** [review]
/approve
/priority backlog
/triage accepted

**Pull request merged**
