### PR TITLE
Don't supress the node update error while logging

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:

 /kind cleanup

**What this PR does / why we need it**:
We don't want to supress the logging when the node update is failing, this test is flaking for downstream in OpenShift and we want to add some debugging code around this.

/cc @Huang-Wei @ahg-g 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
/release-note-none
/kind cleanup
/priority backlog

**Comment by ravisantoshgudimetla** [comment]
/assign @neolit123 

for approval

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
