### PR TITLE
Change port names to avoid validation failure

### PR DESCRIPTION
**Pull request by satnam6502**
Addresses #10452

### CODE REVIEW

**Comment by satnam6502** [comment]
Risk: low.
Possible reviewers: @a-robinson @thockin @saad-ali @dchen1107

**Comment by satnam6502** [comment]
I still think the original port names are fine and there is a bug in our validation code which incorrectly fails these configs.

**Comment by satnam6502** [comment]
The reason this fix works has nothing to do with hyphens: it is because the name is now < 15 chars in length.

**Comment by roberthbailey** [comment]
@satnam6502 -- both shippable and jenkins failed tests. Can you investigate see what the errors are?

**Comment by satnam6502** [comment]
Once a get a moment this weekend I will -- otherwise Monday morning.

**Comment by satnam6502** [comment]
@k8s-bot ok to test

**Comment by thockin** [comment]
LGTM

**Comment by satnam6502** [comment]
@k8s-bot ok to test

**Comment by satnam6502** [comment]
@davidopp @roberthbailey perhaps you can server as the two additional TLs for this review.

**Comment by eparis** [comment]
LGTM tested in my setup and the controller is now able to run.

**Comment by satnam6502** [comment]
@eparis thanks for testing!

**Comment by eparis** [comment]
although we should probably fix ther other places found in #10549 .....

**Comment by satnam6502** [comment]
@eparis please can you verify I got all the missing cases you identified? Thanks.

**Comment by eparis** [comment]
I would have done:
- release-0.19.0/docs/getting-started-guides/coreos/azure/addons/fluentd-elasticsearch/es-controller.yaml:
- release-0.20.0/docs/getting-started-guides/coreos/azure/addons/fluentd-elasticsearch/es-controller.yaml

As well...

**Comment by eparis** [comment]
it's sort of rewriting history and those releases did work.  so this LGTM

**Comment by roberthbailey** [comment]
LGTM.

**Comment by davidopp** [comment]
LGTM

**Comment by satnam6502** [comment]
@zmerlynn please could this be merged soonish? It is needed to fix a test and for the work on the namespace conversion. Thanks. @marekbiskup

**Comment by zmerlynn** [comment]
It was in my next batch.

**Pull request merged**
