### PR TITLE
Automated cherry pick of #96495 upstream release 1.19

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Automated cherry pick of #96495 : kubelet: dockershim ExecSync should return context.DeadlineExeceeded on timeout

**Which issue(s) this PR fixes**:

Ref #97364 #95534

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
The change you attempt to cherry pick contains a potentially breaking change for some applications. This is not something we want to drop on people in a patch for a minor version. 

You can see how critical it is in this comment: https://kubernetes.io/blog/2020/12/08/kubernetes-1-20-release-announcement/#exec-probe-timeout-handling

Please re-open with the justification if you believe this must be cherry-picked

/close

**Comment by andrewsykim** [comment]
Agreed with @SergeyKanzhelev -- even though this is technically a "bug fix", it's probably too risky to cherry-pick into a patch version.

**Pull request closed without merging**
