### PR TITLE
Bumped Heapster to v1.2.0-beta.0

### PR DESCRIPTION
**Pull request by piosz**
[Analytics]()

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/28284)

### CODE REVIEW

**Comment by piosz** [comment]
@gmarek @wojtek-t I bumped it also for kubemark

**Comment by gmarek** [comment]
Did you check if it works on kubemark?

**Comment by piosz** [comment]
@gmarek how can I do it?

**Comment by gmarek** [comment]
Start a kubmark (test/kubemark/start-kubemark.sh) and see if heapster is running (kubectl get pod --namespace=kubemark)

**Comment by piosz** [comment]
closing in favor of #30993

**Pull request closed without merging**
