### PR TITLE
Correct spelling errors in the comments

### PR DESCRIPTION
**Pull request by liangwenguo**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liangwenguo** [comment]
@aleksandra-malinowska can you give me an approve?

**Comment by nikhita** [comment]
/assign @MaciekPytel 
for approval

This is a quick one! :)

**Pull request merged**
