### PR TITLE
Bump metadata proxy to 0.1.4-r1 to pick up security fixes

### PR DESCRIPTION
**Pull request by ikehz**
**What this PR does / why we need it**: Use metadata proxy 0.1.4-r1 to pick up security fixes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Use GCE metadata proxy 0.1.4-r1 to pick up security fixes.
```

### CODE REVIEW

**Comment by mikedanese** [comment]
@ihmccreery can you rebase?

**Comment by ihmccreery** [comment]
@mikedanese done.

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60244)

**Comment by ihmccreery** [comment]
@jpbetz, can you please add the right labels & milestone?

**Comment by jpbetz** [comment]
@ihmccreery I've added all labels except `cherrypick-approved`.  We're currently stabilizing the branch. Once stable I'll add `cherrypick-approved` and make sure this gets in.

**Comment by ihmccreery** [comment]
@jpbetz Why are we stabilizing 1.8?

**Comment by jpbetz** [comment]
/hold
Hold all unmerged cherrypicks for cut of patch release on Monday.

**Pull request merged**
