### PR TITLE
fixgo lint failures test/integration/...

### PR DESCRIPTION
**Pull request by xichengliudui**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by BenTheElder — APPROVED** [review]
please run:
`./hack/update-bazel.sh`
`./hack/update-gofmt.sh`
otherwise these changes look good, thanks.

**Comment by xichengliudui** [comment]
Great. Thank you.

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
