### PR TITLE
Add ncdc to client-go/tools/cache OWNERS

### PR DESCRIPTION
**Pull request by ncdc**
Signed-off-by: Andy Goldstein <andy.goldstein@gmail.com>

@kubernetes/sig-api-machinery-misc @lavalamp @smarterclayton @deads2k @sttts @liggitt @caesarxuchao @cheftako any objections?

### CODE REVIEW

**Comment by sttts** [comment]
lgtm

**Comment by lavalamp** [comment]
I don't think I object to this :) but can you say what client changes you've made / intend to make?

**Comment by ncdc** [comment]
@lavalamp in this space, I've done the following:
- wrote `lister-gen` and`informer-gen` (which I realize are in a different repo, but they're related)
- added support for per-shared informer resync periods
- reviewed several changes to shared informer internals

I am hoping to get approval status to continue with the shared informer reviews and changes as needed.

**Comment by lavalamp** [comment]
Do you want to own stuff in e.g. the discovery or rest directories? If not I suggest adding new OWNERs files just to the directories you want to own--that would be good anyway, this file is getting pretty bloated.

**Comment by ncdc** [comment]
@lavalamp I can limit to just tools/cache/OWNERS for now, although that file doesn't have any approvers listed - it only has reviewers. What do you recommend we do in there?

**Comment by lavalamp** [comment]
Just add an `approvers` section. Thanks!

**Comment by ncdc** [comment]
@lavalamp updated. I took a wild guess at adding other approvers based on people I think have been involved with this code in the past. I'll happily adjust as feedback dictates.

**Comment by lavalamp** [comment]
/lgtm
/approve no-issue

Many of those folks already have approver power from a higher level directory but it doesn't hurt anything to repeat them here. Thanks!

**Pull request merged**
