### PR TITLE
Vanity imports round 2

### PR DESCRIPTION
**Pull request by mikedanese**
A little bit more is required to fix the build than what is in #12253 

ref #12211

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by thockin** [comment]
LGTM.  Go ahead and close my PR, please.

**Comment by mikedanese** [comment]
Per discussion with @thockin, I'm going to merge this on CI green.

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by karlkfi** [comment]
Worth mentioning that this changes the depth of the packages, and might break anything that was trying to relatively navigate down to the GOPATH from the KUBE_ROOT. 

ex (from a PR of mine):
```
GOPATH=$(cd "${KUBE_ROOT}/../../../.." && pwd)
+GOPATH="${GOPATH}:${KUBE_ROOT}/Godeps/_workspace"
```

**Comment by thockin** [comment]
Any file's dept relative to KUBE_ROOT should be the same.

old:
github.com/GoogleCloudPlatform/kubernetes/pkg/foo/bar : KUBE_ROOT=
github.com/GoogleCloudPlatform/kubernetes

new
k8s.io/kubernetes/pkg/foo/bar : KUBE_ROOT=k8s.io/kubernetes


It seems you are traversing up above KUBE_ROOT, which is dubious from the
start.  Many people use symlinks which will break this.  e.g. my KUBE_ROOT
is ~/src/kubernetes, which is a link to ~/src/go/src/k8s.io/kubernetes, but
pwd show the short form.

**Pull request merged**
