### PR TITLE
Mark pods not ready while the node state changes to NotReady

### PR DESCRIPTION
**Pull request by dsxing**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
The current code logic is such that when a node's state changes from true to any other state, MarkPodsNotReady needs to be executed. However, in certain special scenarios, such as this issue, when the kubelet changes the node's state to false and a leaderelection switch occurs in kcm, MarkPodsNotReady will not be executed. Then, another kcm pod starts and the node's state is false. After the node becomes NotReady, the node's state changes from false to unknown, but MarkPodsNotReady still won't be executed. Of course, this probability is very low, and it is difficult to reproduce.
#### Which issue(s) this PR fixes:

Fixes #112733 , #109998

#### Special notes for your reviewer:
/cc  @bobbypage 
/cc  @SergeyKanzhelev 

#### Does this PR introduce a user-facing change?
NONE

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lance5890** [comment]
m

**Comment by dsxing** [comment]
@bobbypage Can you review the code? 
Thanks

**Pull request closed without merging**
