### PR TITLE
fix typos in some files

### PR DESCRIPTION
**Pull request by charlesh001**
**What this PR does / why we need it**:
fix typos in checks.go and staticpods.go

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
NONE

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
@huangqg 
please sign the CLA as outlined by this comment:
https://github.com/kubernetes/kubernetes/pull/68079#issuecomment-417383845

**Comment by idealhack** [comment]
needs milestone to be included before code freeze.

**Pull request merged**
