### PR TITLE
Revert "Periodically update pod status from kubelet."

### PR DESCRIPTION
**Pull request by fgrzadkowski**
Reverts GoogleCloudPlatform/kubernetes#5205

Apart from the deadlock fixed in #5540 this PR is breaks something else (e.g. scheduler hangs on binding).

### CODE REVIEW

**Comment by wojtek-t** [comment]
cc @vmarmol

**Comment by wojtek-t** [comment]
Since the original PR broke e2e tests, I'm going to merge this PR now.

**Comment by wojtek-t** [comment]
Confirmed that reverting this PR fixed e2e tests on jenkins.
@fgrzadkowski is currently working on fixing the problems with the original PR and resend it for review.

**Comment by vmarmol** [comment]
Thanks for catching and reverting!

**Pull request merged**
