### PR TITLE
Remove obsolete sentinel.py from redis example

### PR DESCRIPTION
**Pull request by tback**

### CODE REVIEW

**Comment by tback** [comment]
I signed it!

**Comment by tback** [comment]
Before this change the image failed to build because sentinel.py is absent.

**Comment by brendandburns** [comment]
LGTM, thanks for the fix!

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Pull request merged**
