### PR TITLE
Fix nodeshutdown inhibitLock race

### LINKED ISSUE #110881: Nodeshutdown test failed due to data race
### Which jobs are flaking?

pull-kubernetes-unit

### Which tests are flaking?

`TestFeatureEnabled/shutdownGracePeriodRequested_0;_disables_feature` test failed with `data race`

### Since when has it been flaking?

It should be introduced by #98088

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/110858/pull-kubernetes-unit/1542073307128401920

### Reason for failure (if possible)

From the test fail result, we can know that there is data race at:

https://github.com/kubernetes/kubernetes/blob/91aca10d5984313c1c5858979d4946ff9446615f/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L297-L306

https://github.com/kubernetes/kubernetes/blob/91aca10d5984313c1c5858979d4946ff9446615f/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L320-L327

the `inhibitLock` is read and written at the same time.

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by tossmilestone**
Signed-off-by: He Xiaoxi <xxhe@alauda.io>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Fixes flaky test of nodeshutdown

#### Which issue(s) this PR fixes:

Fixes None

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
/cc @wzshiming @bobbypage 

@tossmilestone you should fix the merged commit firstly https://github.com/kubernetes/kubernetes/pull/110882#issuecomment-1170963992

**Comment by wzshiming** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/110858/pull-kubernetes-unit/1542073307128401920


``` console
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/cilium/ebpf/link/syscalls.go:50 +0x2a8
```

``` console
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/ktesting/testinglogger.go:279 +0x524
```

From the error logs, it doesn't look like this patch fix is causing a data race.

**Comment by tossmilestone** [comment]
@wzshiming it looks like I have found the wrong cause, but the `inhibitLock` indeed have the data race risk.

**Pull request closed without merging**
