### PR TITLE
Update federation openapi spec

### PR DESCRIPTION
**Pull request by liggitt**
hack/verify-federation-openapi-spec.sh fails on master

### CODE REVIEW

**Comment by cblecker** [comment]
@liggitt Where are you seeing the failure? Looks like the 3 most recent runs by SQ all show green:
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-verify-master/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-verify-master/3711

Don't know if I'm missing something, or if there is a gap to be fixed in the hack/ scripts.

**Comment by liggitt** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42152/pull-kubernetes-verify/24034/

**Comment by liggitt** [comment]
checking out master and running `hack/update-federation-openapi-spec.sh` produces this diff

**Pull request merged**
