### PR TITLE
Add iptables rules to allow nodeport traffic in ipvs mode

### LINKED ISSUE #98465: NodePort service in ipvs mode depends on INPUT chain policy to be accessible externally
**What happened**:
Similar to https://github.com/kubernetes/kubernetes/issues/97225, when `INPUT` chain in `filter` table has policy `DROP`, node port service in `ipvs` mode is not working.

**What you expected to happen**:
`ipvs` mode for `kube-proxy` should have consistent behavior as `iptables` mode. For `iptables` mode, even if we change policy for `INPUT` chain to `DROP`, we can still access the node port service.

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure kube-proxy to ipvs mode. My environment was using `iptables` mode during bootstrap so I have to change the proxy mode from `iptables` to `ipvs`. What I did is just change the `mode` field in `kube-proxy` configmap (in `kube-system` namespace) from `""` to `"ipvs"`.

Also, to eliminate the impacts from the `iptables` mode, I have to remove all chains/rules created in that mode. What I did is use `iptables-save > <filename>` to dump the iptable and remove all lines containing `KUBE`, then use `iptables-restore < <filename>` to restore the iptable.
2. Deploy the following service and workload:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: us.gcr.io/google-containers/nginx
        ports:
        - containerPort: 80
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30010
```
3. Change the policy of `INPUT` chain in `filter` table to `DROP`. Notice if you don't have any rule allowing ssh or loopback interface traffic, you'd better add rules to allow them before changing the policy. Here's what I did:
```
iptables -A INPUT -p tcp --dport ssh -j ACCEPT -m comment --comment "Accept SSH traffic"
iptables -A INPUT -i lo -j ACCEPT -m comment --comment "Accept loopback interface traffic"
iptables -P INPUT DROP
```
4. Then curl the node port service at `<node/external/IP>:30010`. Won't be able to access the service. If you switch the `kube-proxy` mode back to `iptables` mode, then it works.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `1.20.2`
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): antrea
- Others:

### PR DESCRIPTION
**Pull request by hanlins**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Explicitly add iptables rules to allow nodeport traffic in ipvs mode.

**Which issue(s) this PR fixes**:

Fixes #98465 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fixed a bug that node port service in ipvs mode doesn't work if the policy for INPUT chain in filter table is DROP.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by uablrek** [comment]
/lgtm

Since dual-stack e2e tests are under construction I tested manually access to nodeport with and without this PR with a dual-stack service;
```
$ kubectl get svc mconnect-preferdual
NAME                  TYPE           CLUSTER-IP    EXTERNAL-IP        PORT(S)          AGE
mconnect-preferdual   LoadBalancer   12.0.184.76   10.0.0.2,1000::2   5001:32083/TCP   31s
```
Access to both `node-ipv4:32083` and `node-ipv6:32083` works with INPUT=DROP, and does _not_ work without this PR.

**Comment by aojea** [comment]
> Since dual-stack e2e tests are under construction I tested manually access to nodeport with and without this PR with a dual-stack service;

There are some test already, you can run them manually

/test pull-kubernetes-e2e-azure-dualstack
/test pull-kubernetes-e2e-iptables-azure-dualstack
/test pull-kubernetes-e2e-kind-ipvs-dual-canary
/test pull-kubernetes-e2e-kind-dual-canary

once we have it fully supported in kind I will try to make it run by default

**Comment by hanlins** [comment]
@aojea I think job `pull-kubernetes-e2e-iptables-azure-dualstack` is failing consistently, checked [job history](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-iptables-azure-dualstack), it's failing since the beginning of 2021, https://github.com/kubernetes/kubernetes/pull/99066 is also failing the same case.

**Comment by aojea** [comment]
> @aojea I think job `pull-kubernetes-e2e-iptables-azure-dualstack` is failing consistently, checked [job history](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-iptables-azure-dualstack), it's failing since the beginning of 2021, #99066 is also failing the same case.

yep, sorry, feel free to disregard it, the failing test is unrelated to your PR and it seems it is failing constantly in this job 

> Kubernetes e2e suite: [sig-auth] ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance] expand_less

**Comment by hanlins** [comment]
PTAL @andrewsykim @uablrek, thanks!

**Comment by uablrek** [comment]
I have re-rested with `v1.21.0-beta.1.378+cf3374e43491c5` without this PR and `v1.21.0-beta.1.378+cf3374e43491c5-dirty` with this PR.

It doesn't work without this PR. But I noted some things that likely was in the old version as well, but I missed them;

* Even with the patch access to `node-ip:nodeport` does not work from the main netns on the node.
* Access to `node-ip:nodeport` does not work from within PODs either (but that may be an odd case)

Access from an external source to `node-ip:nodeport` works with the DROP rule but...

After some time (~1min) it stops working! 

I noticed;
```
E0322 12:34:42.119506     396 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.EndpointSlice: failed to list *v1beta1.EndpointSlice: Get "https://192.168.1.1:6443/apis/discovery.k8s.io/v1beta1/endpointslices?labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=721": dial tcp 192.168.1.1:6443: i/o timeout
```
in the kube-proxy log.

My guess is that the DROP rule prevents traffic to the api-server. Likely just more ACCEPT rules than the 2 mentioned in the issue are needed.

**NOTE** I run my `kube-proxy` directly on the node, not in a static container as is the norm. This could be the reason and other users using the "normal" setup are not affected.

**Comment by hanlins** [comment]
Hi @uablrek, thanks for the feedback! To allow the pod traffic, what I did in my environment is adding this rule to `INPUT` chain in `filter` table statically:
```
-A INPUT -i lo -j ACCEPT
```
Weeks back when I test this fix, I found etcd stoped talking to API server without this rule and failed the cluster, that seems like what you've described. This rule fits the need of my product but I'm not sure if we should add it to k8s codebase from a security perspective. Maybe we should just document if `INPUT` policy is `DROP` then you need this rule to make it work.

**Comment by uablrek** [comment]
I think this PR must wait until the full impact of setting DROP policy on the INPUT chain on the main K8s node interface has been cleared out.

There is just too much going on, not only node-port traffic. For instance all CNI-plugin traffic and kube-api connections. It looks like this PR _only_ opens for nodePorts.

@thockin Can you please take a look at this?

For instance kube-proxy and kubelet communication with the api-server;
```
# netstat -putn | grep -E 'kube-proxy|kubelet'
tcp        0      0 192.168.1.3:56452       192.168.1.1:6443        ESTABLISHED 382/kube-proxy      
tcp        0      0 192.168.1.3:56488       192.168.1.1:6443        ESTABLISHED 377/kubelet         
tcp        0      0 192.168.1.3:56484       192.168.1.1:6443        ESTABLISHED 377/kubelet         
tcp        0      0 192.168.1.3:56490       192.168.1.1:6443        ESTABLISHED 377/kubelet         
tcp        0      0 192.168.1.3:56480       192.168.1.1:6443        ESTABLISHED 377/kubelet         
tcp        0      0 192.168.1.3:56466       192.168.1.1:6443        ESTABLISHED 377/kubelet         
```
When you set `iptables -P INPUT DROP` even with this PR applied it look like this after a short time;
```
# netstat -putn | grep -E 'kube-proxy|kubelet'
tcp        0      1 192.168.1.3:56784       192.168.1.1:6443        SYN_SENT    377/kubelet         
tcp        0      1 192.168.1.3:56790       192.168.1.1:6443        SYN_SENT    377/kubelet         
tcp        0      1 192.168.1.3:56772       192.168.1.1:6443        SYN_SENT    382/kube-proxy      
tcp        0      1 192.168.1.3:56788       192.168.1.1:6443        SYN_SENT    377/kubelet         
tcp        0      1 192.168.1.3:56786       192.168.1.1:6443        SYN_SENT    377/kubelet         
tcp        0      1 192.168.1.3:56768       192.168.1.1:6443        SYN_SENT    377/kubelet         
tcp        0      1 192.168.1.3:56780       192.168.1.1:6443        SYN_SENT    377/kubelet         
tcp        0      1 192.168.1.3:56770       192.168.1.1:6443        SYN_SENT    382/kube-proxy      
tcp        0      1 192.168.1.3:56766       192.168.1.1:6443        SYN_SENT    377/kubelet         
tcp        0      1 192.168.1.3:56782       192.168.1.1:6443        SYN_SENT    377/kubelet         
```
And the CNI-plugin is blocked. At least my cluster becomes unusable.

**Comment by aojea** [comment]
> I think this PR must wait until the full impact of setting DROP policy on the INPUT chain on the main K8s node interface has been cleared out.

so, ipvs mode can not set default policy to DROP on the INPUT chain, unless you add additional iptables rules to accept pod, apiserver, cni, ... traffic? did I understand it correctly?

**Comment by hanlins** [comment]
> so, ipvs mode can not set default policy to DROP on the INPUT chain, unless you add additional iptables rules to accept pod, apiserver, cni, ... traffic? did I understand it correctly?

From my team's use case, to get around the issue @uablrek mentioned, we set `INPUT` chain policy to `DROP`, and added rule by doing:
```
iptables -t filter -A INPUT -i lo -j ACCEPT
```
This is the rule we applied that doesn't need to be changed after the system is running. This PR is intended only for the dynamic part, i.e. to manage the rules for node ports which can be changed from time to time by users.

I'm not sure if the rule I mentioned above would work for all CNI solutions but I think it should cover most overlay-based CNIs. We probably want to test it in multiple CNI solutions to gain confidence, and maybe adding that rule in @uablrek's environment and recheck could be the first step.

**Comment by uablrek** [comment]
Just try to set `iptables -P INPUT DROP` in _any_ (multi-node) system ipvs or iptables does not matter and kubelet<->api-server communication will be dropped.

And allowing incoming traffic on `lo` may be sufficient for a one-node system with non-replicated `etcd` and `api-server` on the same node.

Also the pod-pod network uses the main interface and be blocked, e.g a VXLAN port?. I don't know about probes, web-hooks, etc, etc.

My point is that the full situation of `iptables -P INPUT DROP` should be investigated before any code usable for just a few systems is added.

**Comment by uablrek** [comment]
Oh, and for the record, I have _always_ added the `iptables -t filter -A INPUT -i lo -j ACCEPT` when testing. It is not enough.

**Comment by uablrek** [comment]
> so, ipvs mode can not set default policy to DROP on the INPUT chain, unless you add additional iptables rules to accept pod, apiserver, cni, ... traffic? did I understand it correctly?

Yes, except for the ipvs part. It is the same with iptables.

**Comment by hanlins** [comment]
I see, @uablrek can you help me to update https://github.com/kubernetes/kubernetes/issues/98465 with your findings, or open a separate issue to track it? Currently, that issue only covers the node port issue for ipvs, we could either expand it or create new ones to capture these problems. I'd prefer to make incremental changes but I do agree it would be great to learn more about the impact before merging.

Also, I'm curious about the CNI you're using, is it something common or something proprietary? I do want to reproduce your scenario in my daytime.

**Comment by uablrek** [comment]
You are right, pod-pod seems to work since traffic goes to the FORWARD chain. But all communication in main netns is affected. Most important `kubelet`. Also `etcd` if it runs on nodes.

I have tried `calico/cni:v3.18.0` and `bridge` CNI-plugins.

**Comment by aojea** [comment]
> My point is that the full situation of `iptables -P INPUT DROP` should be investigated before any code usable for just a few systems is added.

> Yes, except for the ipvs part. It is the same with iptables.

I see it now, yeah, if you set default to DROP all the host traffic will be dropped unless you insert the rules for the traffic that you want to allow for the host daemons: ssh, kubelet, apiserver, cni, ...

The "Kubernetes network responsibility" topic was discussed here too https://github.com/kubernetes/kubernetes/issues/82125 , right now it belongs to kubelet and kube-proxy, but not everybody uses kube-proxy and as  @thockin comments in that thread, maybe kubelet should not now anything about network. So it seems that there is no really the role of "host network responsible" in Kubernetes.

I, personally, don't think that Kubernetes should manage ALL the iptables rules in the host, hence, switching the default iptables policy on the INPUT chain to DROP should not be a Kubernetes responsibility, I think that is on the cluster admin to decide the policy he wants to implement and allow the host traffic he wants, if you set the default policy to drop, you need to know which traffic you want to allow (ssh, kubelet, apiserver, ...) and you need to insert the corresponding rules, however, I see that kube-proxy should consider all the scenarios and insert the ACCEPT rule for the healthcheck nodeport.

It will be nice to hear from @danwinship, @andrewsykim  and @thockin about this topic.

**Comment by uablrek** [comment]
> I see that kube-proxy should consider all the scenarios and insert the ACCEPT rule for the healthcheck nodeport.

Even for `proxy-mode=ipvs` there is a rule for healthcheck nodeport in the INPUT chain already. I don't know how to test is though. Perhaps it is a cloud-provider thing that I don't use?

```
vm-002 ~ # iptables -nL INPUT
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
KUBE-NODE-PORT  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes health check rules */
KUBE-FIREWALL  all  --  0.0.0.0/0            0.0.0.0/0           
vm-002 ~ # iptables -nL KUBE-NODE-PORT
Chain KUBE-NODE-PORT (1 references)
target     prot opt source               destination         
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            /* Kubernetes health check node port */ match-set KUBE-HEALTH-CHECK-NODE-PORT dst
vm-002 ~ # kubectl version --short
Client Version: v1.21.0-beta.1.378+cf3374e43491c5
Server Version: v1.21.0-beta.1.378+cf3374e43491c5  # <--- This pr NOT applied.
```

**Comment by aojea** [comment]
> Perhaps it is a cloud-provider thing that I don't use?

yep, most probably

**Comment by uablrek** [comment]
The `KUBE-NODE-PORT` chain for proxy-mode=ipvs exists in `v1.21.0-beta.1` but not in `v1.20.5`.

There must be some PR similar to this one already merged.

**Comment by uablrek** [comment]
@hanlins Since `KUBE-NODE-PORT` has appeared in K8s `v1.21.0-beta.1` can you please test with that version (if you havn't already that is)?

**Comment by aojea** [comment]
> The `KUBE-NODE-PORT` chain for proxy-mode=ipvs exists in `v1.21.0-beta.1` but not in `v1.20.5`.
> 
> There must be some PR similar to this one already merged.

https://github.com/kubernetes/kubernetes/pull/97824

**Pull request closed without merging**
