### PR TITLE
Automated cherry pick of #76061: test/e2e/network: Honor --dns-domain in more places

### PR DESCRIPTION
**Pull request by va4st**
Cherry pick of #76061 on release-1.14.

#76061: test/e2e/network: Honor --dns-domain in more places

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
Thanks for the cherrypick!
/lgtm
/approve

**Comment by tpepper** [comment]
Does this fix a test that is currently failing on the 1.14 branch?  Can you share a link to testgrid?

**Comment by vryzhenkin** [comment]
@tpepper Likely not, because I'm pretty sure that there used usual cluster.local domain. This test start failing if default domain will be changed to anything else.

**Comment by vryzhenkin** [comment]
@MrHohn Hey, any chance to merge it?

**Comment by MrHohn** [comment]
@vryzhenkin Sorry I'm not privileged to approve cherrypicks. You will have to justify the need of cherrypicking to @tpepper.

**Pull request merged**
