### PR TITLE
Updates etcd-client to 3.1.10

### PR DESCRIPTION
**Pull request by timothysc**
I have no idea why azure sdk update became transitive but godeps we're restored before update

Fixes: https://github.com/kubernetes/kubernetes/issues/49386
xref: https://github.com/kubernetes/kubernetes/pull/49393

```
NONE
```

/cc @kubernetes/sig-scalability-pr-reviews @kubernetes/sig-api-machinery-misc @hongchaodeng @wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
@brendandburns - since this PR is touching some Azure files, can you please take a look?

**Comment by brendandburns** [comment]
@wojtek-t looks like the azure SDK changes are just a file-mode change from `0644` to `0755` (not sure why they were `0644` to begin with, but it doesn't really matter to me :)

/lgtm

**Comment by brendandburns** [comment]
@timothysc  (although on the other hand, do we really want the SDK files to be executable?)

**Pull request merged**
