### PR TITLE
Remove docker-multinode

### PR DESCRIPTION
**Pull request by luxas**
This guide has moved to kube-deploy.
We don't want this hanging around in `v1.3`, so let's remove it.

PR for kube-deploy: kubernetes/kube-deploy#12

@mikedanese @johndmulhausen @bgrant0607

### CODE REVIEW

**Comment by luxas** [comment]
@eparis Is there any way to convince the bot we may touch this (for the last time)?

**Comment by bgrant0607** [comment]
@luxas Don't worry about the label. We can just merge this by hand.

**Comment by bgrant0607** [comment]
@luxas We need to add redirectors to the new location in kubernetes.github.io, also.

**Comment by luxas** [comment]
I don't think we should maintain it in two different places.
All scripts in `kubernetes.github.io` should also be deleted (of course, the commits that have been made should be ported over to kube-deploy), and the docs guide should describe how to use/setup the `kube-deploy` deployment. The source of truth should be in kube-deploy.

@bgrant0607 Does this sound like a good idea?

**Comment by mikedanese** [comment]
I think we should maintain the getting started guide (e.g. just the doc) in kubernets.github.io. That's the location where it is most user visible and discoverable. We can point to that documentation from kube-deploy.

**Comment by luxas** [comment]
@k8s-bot e2e test this please github issue: #IGNORE

**Comment by luxas** [comment]
@mikedanese Want to proceed with this one as the kube-deploy PR is in?

**Comment by luxas** [comment]
@k8s-bot unit test this please github issue: #IGNORE

**Comment by luxas** [comment]
@mikedanese or @k8s-oncall 
Mind a manual merge for this as the bot doesn't like the fact we're touching the old docs?

**Pull request merged**
