### PR TITLE
Remove versioned LabelSelectors

### PR DESCRIPTION
**Pull request by caesarxuchao**
We have LabelSelectors defined in `unversioned`, `batch/v1`, `batch/v2alpha1`, and `extensions/v1beta1`.  Their definitions are all the same. I kept the definition in `unversioned` and removed the others. It only makes sense to define a versioned LabelSelectors if the definition is different.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35255)

### CODE REVIEW

**Comment by awh** [comment]
@caesarxuchao any idea on when this will make it into `client-go`? This is currently blocking me from porting the weave network policy controller (https://github.com/weaveworks/weave-npc/pull/24#issuecomment-254862278)

**Comment by caesarxuchao** [comment]
@k8s-bot gce e2e test this, issue #IGNORE

**Comment by caesarxuchao** [comment]
@k8s-bot cvm gce e2e test this

**Comment by caesarxuchao** [comment]
Looks like the e2e test failure is https://github.com/kubernetes/kubernetes/issues/31708#issue-174061209

**Comment by caesarxuchao** [comment]
Somehow the heaper deployment is not created when the e2e cluster started up. Its manifest existed in /etc/kubernetes/addons/cluster-monitoring/influxdb/heapster-controller.yaml. I manually created it, and all the failed tests passed. @piosz do you know what's going on? My PR just removed the duplicate definitions of LabelSelector.

**Comment by MrHohn** [comment]
Sorry for the delay. I don't have a theory yet.

From the apiserver's log, seems like the addon manager did try to list `deployment` in every loop, but never try create the heapster deployment.

```
I1021 05:02:24.888511       5 panics.go:76] GET /apis/extensions/v1beta1/deployments?labelSelector=kubernetes.io%2Fcluster-service%3Dtrue: (1.553677ms) 200 [[kubectl/v1.3.0 (linux/amd64) kubernetes/caf9a4d] 127.0.0.1:47444]
```

Would it be something related to the kubectl version? Current addon manager is using v1.3.0. kubectl. For the reason it failed to create the `deployment`, my guess is it failed ahead while [getting current deployments from apiserver](https://github.com/kubernetes/kubernetes/blob/cde5559d0951a2e78d24ef1055adfa432de80b3a/cluster/addons/addon-manager/kube-addon-update.sh#L198-L200).

**Comment by caesarxuchao** [comment]
Thanks @MrHohn. Sorry for @ you after hour. So it seems not to be a known issue. I'll debug the script tomorrow.

**Comment by caesarxuchao** [comment]
I think I found the problem:
```
INFO: Creating new Deployment from file /etc/kubernetes/addons/cluster-monitoring/influxdb/heapster-controller.yaml in namespace kube-system, name: heapster-v1.2.0
error validating "/etc/kubernetes/addons/cluster-monitoring/influxdb/heapster-controller.yaml": error validating data: unexpected type: unversioned.LabelSelector; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by caesarxuchao** [comment]
The problem is kubectl's validation and is fixed in 1.3: https://github.com/kubernetes/kubernetes/pull/27944.

The addon manager image is using 1.3.0-beta2 kubectl. I'll update the image.

**Comment by MrHohn** [comment]
cc @mikedanese

**Comment by MrHohn** [comment]
Sorry, forgot to mention, the deployment heapster may not work properly with the new addon manager as it will fight with the addon-resizer containers which run within the heapster pod. And it will lead to the system keep deleting and re-creating the heapster pod.

One solution to resolve this would be remove the resource limit fields from the heapster deployment manifest([here](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/influxdb/heapster-controller.yaml#L54-L61) and [here](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/influxdb/heapster-controller.yaml#L68-L75), other related manifests as well).

Ref [here](https://github.com/kubernetes/kubernetes/pull/34513#issuecomment-253085168).

**Comment by caesarxuchao** [comment]
> And it will lead to the system keep deleting and re-creating the heapster pod.

Thanks. That's what I observed. I'll try the solution.

**Comment by caesarxuchao** [comment]
ref https://github.com/kubernetes/kubernetes/issues/34943

**Comment by caesarxuchao** [comment]
I checkout one commit before https://github.com/kubernetes/kubernetes/pull/34513, built and pushed a v5.2 image with 1.4.4 kubectl.

**Comment by caesarxuchao** [comment]
@k8s-bot e2e test this, issue #IGNORE

**Comment by caesarxuchao** [comment]
cc @kubernetes/sig-api-machinery

**Comment by caesarxuchao** [comment]
@mikedanese @MrHohn could you take a look at the last commit that modifies the addon-manager? Also I had checked out one commit before #34513, built and pushed a v5.2 image with 1.4.4 kubectl.

**Comment by MrHohn** [comment]
The addon manager part SGTM.

**Comment by smarterclayton** [comment]
Non-addon changes LGTM.  Please squash the conversion changes into one PR and feel free to self merge.

**Comment by caesarxuchao** [comment]
Thanks. Squashed. Added the label per comments.

**Comment by caesarxuchao** [comment]
Ran hack/update-bazel.sh, no other changes. Added back the lgtm.

**Comment by caesarxuchao** [comment]
@mikedanese do you know why verify-bazel.sh fails, but update-bazel.sh doesn't update anything? Do I need some local setup? Thanks.

**Comment by caesarxuchao** [comment]
Rebased 3 times after getting the lgtm. Bump the priority.

**Comment by gmarek** [comment]
This PR broke slow tests: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/10667

**Comment by MrHohn** [comment]
I am deeply sorry.

Found addon manager broken after #30372. It's easy to reproduce. Pushing a new addon manager with the former commit(2a589b09637aa3745a7151adf2f1fcce36e8b8ac) using v1.4.4 kubectl works properly in my own cluster.

**Comment by caesarxuchao** [comment]
Thanks @MrHohn!

**Pull request merged**
