### PR TITLE
Ensure service deleted when the Azure resource group has been deleted

### LINKED ISSUE #100855: LoadBalancer cannot be deleted when the underlying resource group is deleted
#### What happened:

I recall that this issue was reported previously in https://github.com/kubernetes/kubernetes/issues/75198. It was fixed in the master back then with https://github.com/kubernetes/kubernetes/pull/93962 and it was cherry-picked into `release-1.19` with https://github.com/kubernetes/kubernetes/pull/94713.
However we still observe the same issue with the legacy azure cloud-controller-manager v1.19.9.

#### What you expected to happen:

legacy azure cloud controller-manager to be able to delete LoadBalancer when the underlying resource group is deleted.

#### How to reproduce it (as minimally and precisely as possible):

1. Create a LoadBalancer

2. Delete manually the underlying resource group

3. Delete the LoadBalancer created in step 1

4. Make sure that the deletion of the LoadBalancer fails

Events of the Service:
```
$ k describe svc baz

Events:
  Type     Reason                   Age                  From                             Message
  ----     ------                   ----                 ----                             -------
  Warning  UnAvailableLoadBalancer  30m (x2 over 79m)    service-controller               There are no available nodes for LoadBalancer
  Warning  PortNotAllocated         2m23s (x9 over 26m)  portallocator-repair-controller  Port 30551 is not allocated; repairing
  Warning  ClusterIPNotAllocated    2m23s (x9 over 26m)  ipallocator-repair-controller    Cluster IP 10.223.73.211 is not allocated; repairing
  Warning  ListLoadBalancers        62s (x60 over 26m)   azure-cloud-provider             Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'foo' could not be found."}}
  Warning  SyncLoadBalancerFailed   2s (x62 over 26m)    service-controller               Error syncing load balancer: failed to check if load balancer exists before cleanup: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'foo' could not be found."}}
```

```
$ k logs cloud-controller-manager-8645fbc87b-fjkgt

I0406 09:01:52.729842       1 azure_wrap.go:273] Route table "worker_route_table" not found
I0406 09:02:01.595833       1 azure_wrap.go:109] Public IP "foo-a0afb50cc4981439b9e9b25aaae12345" not found
E0406 09:02:01.649910       1 azure_backoff.go:277] LoadBalancerClient.List(foo) failure with err=&{false 404 0001-01-01 00:00:00 +0000 UTC Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'foo' could not be found."}}}
E0406 09:02:01.649952       1 controller.go:275] error processing service kube-system/baz (will retry): failed to check if load balancer exists before cleanup: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'foo' could not be found."}}
I0406 09:02:01.650035       1 event.go:291] "Event occurred" object="kube-system/baz" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to check if load balancer exists before cleanup: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'foo' could not be found.\"}}"
I0406 09:02:02.782078       1 azure_wrap.go:273] Route table "worker_route_table" not found
I0406 09:02:12.727320       1 azure_wrap.go:273] Route table "worker_route_table" not found
I0406 09:02:22.726149       1 azure_wrap.go:273] Route table "worker_route_table" not found
I0406 09:02:31.594960       1 azure_wrap.go:109] Public IP "foo-a0afb50cc4981439b9e9b25aaae12345" not found
E0406 09:02:31.611763       1 azure_backoff.go:277] LoadBalancerClient.List(foo) failure with err=&{false 404 0001-01-01 00:00:00 +0000 UTC Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'foo' could not be found."}}}
E0406 09:02:31.611802       1 controller.go:275] error processing service kube-system/baz (will retry): failed to check if load balancer exists before cleanup: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'foo' could not be found."}}
I0406 09:02:31.611941       1 event.go:291] "Event occurred" object="kube-system/baz" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to check if load balancer exists before cleanup: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'foo' could not be found.\"}}"
I0406 09:02:32.726256       1 azure_wrap.go:273] Route table "worker_route_table" not found
I0406 09:02:42.735297       1 azure_wrap.go:273] Route table "worker_route_table" not found
I0406 09:02:52.727760       1 azure_wrap.go:273] Route table "worker_route_table" not found
I0406 09:03:01.595419       1 azure_wrap.go:109] Public IP "foo-a0afb50cc4981439b9e9b25aaae12345" not found
E0406 09:03:01.616405       1 azure_backoff.go:277] LoadBalancerClient.List(foo) failure with err=&{false 404 0001-01-01 00:00:00 +0000 UTC Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'foo' could not be found."}}}
E0406 09:03:01.616441       1 controller.go:275] error processing service kube-system/baz (will retry): failed to check if load balancer exists before cleanup: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'foo' could not be found."}}
I0406 09:03:01.616687       1 event.go:291] "Event occurred" object="kube-system/baz" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to check if load balancer exists before cleanup: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'foo' could not be found.\"}}"
I0406 09:03:02.732814       1 azure_wrap.go:273] Route table "worker_route_table" not found
I0406 09:03:12.726431       1 azure_wrap.go:273] Route table "worker_route_table" not found
I0406 09:03:22.725267       1 azure_wrap.go:273] Route table "worker_route_table" not found
I0406 09:03:31.597935       1 azure_wrap.go:109] Public IP "foo-a0afb50cc4981439b9e9b25aaae12345" not found
E0406 09:03:31.616554       1 azure_backoff.go:277] LoadBalancerClient.List(foo) failure with err=&{false 404 0001-01-01 00:00:00 +0000 UTC Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'foo' could not be found."}}}
E0406 09:03:31.616587       1 controller.go:275] error processing service kube-system/baz (will retry): failed to check if load balancer exists before cleanup: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'foo' could not be found."}}
I0406 09:03:31.616688       1 event.go:291] "Event occurred" object="kube-system/baz" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to check if load balancer exists before cleanup: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'foo' could not be found.\"}}"
I0406 09:03:32.734746       1 azure_wrap.go:273] Route table "worker_route_table" not found
I0406 09:03:42.734031       1 azure_wrap.go:273] Route table "worker_route_table" not found
I0406 09:03:52.726793       1 azure_wrap.go:273] Route table "worker_route_table" not found
I0406 09:04:01.605512       1 azure_wrap.go:109] Public IP "foo-a0afb50cc4981439b9e9b25aaae12345" not found
E0406 09:04:01.621104       1 azure_backoff.go:277] LoadBalancerClient.List(foo) failure with err=&{false 404 0001-01-01 00:00:00 +0000 UTC Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'foo' could not be found."}}}
E0406 09:04:01.621147       1 controller.go:275] error processing service kube-system/baz (will retry): failed to check if load balancer exists before cleanup: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceGroupNotFound","message":"Resource group 'foo' could not be found."}}
I0406 09:04:01.621202       1 event.go:291] "Event occurred" object="kube-system/baz" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to check if load balancer exists before cleanup: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'foo' could not be found.\"}}"
I0406 09:04:02.759779       1 azure_wrap.go:273] Route table "worker_route_table" not found
```

#### Environment:
- Kubernetes version (use `kubectl version`): v1.19.9
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: https://github.com/gardener/gardener
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by feiskyer**
#### What type of PR is this?
/kind bug
/sig cloud-provider
/area provider/azure

#### What this PR does / why we need it:

Ensure service deleted when the Azure resource group has been deleted.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/100855

#### Does this PR introduce a user-facing change?

```release-note
Ensure service deleted when the Azure resource group has been deleted
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by feiskyer** [comment]
reopen since it is closed wrongly by a cherry-pick.

**Comment by nilo19** [comment]
@andrewsykim @cheftako could you help to approve this bug fix?

**Comment by feiskyer** [comment]
ping @cheftako @andrewsykim for approval

**Pull request merged**
