### PR TITLE
Remove readiness probes to Elasticsearch and Kibana logging

### PR DESCRIPTION
**Pull request by satnam6502**
To stabilize this test I need a readiness probe as well as a liveness probe.

### CODE REVIEW

**Comment by quinton-hoole** [comment]
LGTM

**Comment by satnam6502** [comment]
Please do not merge yet.

**Comment by satnam6502** [comment]
Updated configs and ready to merge after another LGTM. @jlowdermilk

**Comment by satnam6502** [comment]
Note the Elasticsearch / Kibana is broken at head until this PR merges.

**Comment by satnam6502** [comment]
Risk assessment: medium-low.
Value: well, this PR takes us from being broken to being fixed.

**Pull request merged**
