### PR TITLE
Update SMD to v4.0.1 and kube-openapi

### PR DESCRIPTION
**Pull request by apelisse**
**What this PR does / why we need it**:
Updates SMD to 4.0 for the new release.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
there are no actual code changes, right? just a bump to v4 import paths?

**Comment by apelisse** [comment]
Correct:
```diff
$ git show vendor/sigs.k8s.io/structured-merge-diff/**.go
commit f4c145511a0bb62ea7ee1f2154945c84c17ffcd5
Author: Antoine Pelisse <apelisse@gmail.com>
Date:   Mon Aug 10 13:02:25 2020 -0700

    Update SMD to v4.0.1 and kube-openapi

diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/doc.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/doc.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/doc.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/doc.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/element.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/element.go
similarity index 99%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/element.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/element.go
index 1b4872b86c2..1578f64c048 100644
--- a/vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/element.go
+++ b/vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/element.go
@@ -21,7 +21,7 @@ import (
 	"sort"
 	"strings"
 
-	"sigs.k8s.io/structured-merge-diff/v3/value"
+	"sigs.k8s.io/structured-merge-diff/v4/value"
 )
 
 // PathElement describes how to select a child field given a containing object.
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/fromvalue.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/fromvalue.go
similarity index 98%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/fromvalue.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/fromvalue.go
index 36b2d4a916e..20775ee0223 100644
--- a/vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/fromvalue.go
+++ b/vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/fromvalue.go
@@ -17,7 +17,7 @@ limitations under the License.
 package fieldpath
 
 import (
-	"sigs.k8s.io/structured-merge-diff/v3/value"
+	"sigs.k8s.io/structured-merge-diff/v4/value"
 )
 
 // SetFromValue creates a set containing every leaf field mentioned in v.
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/managers.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/managers.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/managers.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/managers.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/path.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/path.go
similarity index 98%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/path.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/path.go
index cc7fb9c6759..0413130bd17 100644
--- a/vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/path.go
+++ b/vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/path.go
@@ -20,7 +20,7 @@ import (
 	"fmt"
 	"strings"
 
-	"sigs.k8s.io/structured-merge-diff/v3/value"
+	"sigs.k8s.io/structured-merge-diff/v4/value"
 )
 
 // Path describes how to select a potentially deeply-nested child field given a
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/pathelementmap.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/pathelementmap.go
similarity index 98%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/pathelementmap.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/pathelementmap.go
index fc8a1ff3fdd..9b14ca581b0 100644
--- a/vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/pathelementmap.go
+++ b/vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/pathelementmap.go
@@ -19,7 +19,7 @@ package fieldpath
 import (
 	"sort"
 
-	"sigs.k8s.io/structured-merge-diff/v3/value"
+	"sigs.k8s.io/structured-merge-diff/v4/value"
 )
 
 // PathElementValueMap is a map from PathElement to value.Value.
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/serialize-pe.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/serialize-pe.go
similarity index 99%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/serialize-pe.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/serialize-pe.go
index fcb6b2fc967..cb18e7b1ca9 100644
--- a/vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/serialize-pe.go
+++ b/vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/serialize-pe.go
@@ -24,7 +24,7 @@ import (
 	"strings"
 
 	jsoniter "github.com/json-iterator/go"
-	"sigs.k8s.io/structured-merge-diff/v3/value"
+	"sigs.k8s.io/structured-merge-diff/v4/value"
 )
 
 var ErrUnknownPathElementType = errors.New("unknown path element type")
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/serialize.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/serialize.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/serialize.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/serialize.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/set.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/set.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/fieldpath/set.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/fieldpath/set.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/merge/conflict.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/merge/conflict.go
similarity index 98%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/merge/conflict.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/merge/conflict.go
index 88cb1417df2..75a492d8ea8 100644
--- a/vendor/sigs.k8s.io/structured-merge-diff/v3/merge/conflict.go
+++ b/vendor/sigs.k8s.io/structured-merge-diff/v4/merge/conflict.go
@@ -21,7 +21,7 @@ import (
 	"sort"
 	"strings"
 
-	"sigs.k8s.io/structured-merge-diff/v3/fieldpath"
+	"sigs.k8s.io/structured-merge-diff/v4/fieldpath"
 )
 
 // Conflict is a conflict on a specific field with the current manager of
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/merge/update.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/merge/update.go
similarity index 99%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/merge/update.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/merge/update.go
index 7b88cbd8eef..e648d8a270f 100644
--- a/vendor/sigs.k8s.io/structured-merge-diff/v3/merge/update.go
+++ b/vendor/sigs.k8s.io/structured-merge-diff/v4/merge/update.go
@@ -16,8 +16,8 @@ package merge
 import (
 	"fmt"
 
-	"sigs.k8s.io/structured-merge-diff/v3/fieldpath"
-	"sigs.k8s.io/structured-merge-diff/v3/typed"
+	"sigs.k8s.io/structured-merge-diff/v4/fieldpath"
+	"sigs.k8s.io/structured-merge-diff/v4/typed"
 )
 
 // Converter is an interface to the conversion logic. The converter
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/schema/doc.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/schema/doc.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/schema/doc.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/schema/doc.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/schema/elements.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/schema/elements.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/schema/elements.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/schema/elements.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/schema/equals.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/schema/equals.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/schema/equals.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/schema/equals.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/schema/schemaschema.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/schema/schemaschema.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/schema/schemaschema.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/schema/schemaschema.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/typed/doc.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/typed/doc.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/typed/doc.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/typed/doc.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/typed/helpers.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/typed/helpers.go
similarity index 97%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/typed/helpers.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/typed/helpers.go
index 0834f4d3275..9b6845e8da6 100644
--- a/vendor/sigs.k8s.io/structured-merge-diff/v3/typed/helpers.go
+++ b/vendor/sigs.k8s.io/structured-merge-diff/v4/typed/helpers.go
@@ -21,9 +21,9 @@ import (
 	"fmt"
 	"strings"
 
-	"sigs.k8s.io/structured-merge-diff/v3/fieldpath"
-	"sigs.k8s.io/structured-merge-diff/v3/schema"
-	"sigs.k8s.io/structured-merge-diff/v3/value"
+	"sigs.k8s.io/structured-merge-diff/v4/fieldpath"
+	"sigs.k8s.io/structured-merge-diff/v4/schema"
+	"sigs.k8s.io/structured-merge-diff/v4/value"
 )
 
 // ValidationError reports an error about a particular field
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/typed/merge.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/typed/merge.go
similarity index 98%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/typed/merge.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/typed/merge.go
index e9573cc2310..5112e2536f5 100644
--- a/vendor/sigs.k8s.io/structured-merge-diff/v3/typed/merge.go
+++ b/vendor/sigs.k8s.io/structured-merge-diff/v4/typed/merge.go
@@ -19,9 +19,9 @@ package typed
 import (
 	"math"
 
-	"sigs.k8s.io/structured-merge-diff/v3/fieldpath"
-	"sigs.k8s.io/structured-merge-diff/v3/schema"
-	"sigs.k8s.io/structured-merge-diff/v3/value"
+	"sigs.k8s.io/structured-merge-diff/v4/fieldpath"
+	"sigs.k8s.io/structured-merge-diff/v4/schema"
+	"sigs.k8s.io/structured-merge-diff/v4/value"
 )
 
 type mergingWalker struct {
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/typed/parser.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/typed/parser.go
similarity index 98%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/typed/parser.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/typed/parser.go
index 845fdfe4ec0..3949a78fc67 100644
--- a/vendor/sigs.k8s.io/structured-merge-diff/v3/typed/parser.go
+++ b/vendor/sigs.k8s.io/structured-merge-diff/v4/typed/parser.go
@@ -20,8 +20,8 @@ import (
 	"fmt"
 
 	yaml "gopkg.in/yaml.v2"
-	"sigs.k8s.io/structured-merge-diff/v3/schema"
-	"sigs.k8s.io/structured-merge-diff/v3/value"
+	"sigs.k8s.io/structured-merge-diff/v4/schema"
+	"sigs.k8s.io/structured-merge-diff/v4/value"
 )
 
 // YAMLObject is an object encoded in YAML.
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/typed/remove.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/typed/remove.go
similarity index 95%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/typed/remove.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/typed/remove.go
index cfa6365ac72..a2811953016 100644
--- a/vendor/sigs.k8s.io/structured-merge-diff/v3/typed/remove.go
+++ b/vendor/sigs.k8s.io/structured-merge-diff/v4/typed/remove.go
@@ -14,9 +14,9 @@ limitations under the License.
 package typed
 
 import (
-	"sigs.k8s.io/structured-merge-diff/v3/fieldpath"
-	"sigs.k8s.io/structured-merge-diff/v3/schema"
-	"sigs.k8s.io/structured-merge-diff/v3/value"
+	"sigs.k8s.io/structured-merge-diff/v4/fieldpath"
+	"sigs.k8s.io/structured-merge-diff/v4/schema"
+	"sigs.k8s.io/structured-merge-diff/v4/value"
 )
 
 type removingWalker struct {
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/typed/tofieldset.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/typed/tofieldset.go
similarity index 96%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/typed/tofieldset.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/typed/tofieldset.go
index b3c4ff00217..0662d0f0a80 100644
--- a/vendor/sigs.k8s.io/structured-merge-diff/v3/typed/tofieldset.go
+++ b/vendor/sigs.k8s.io/structured-merge-diff/v4/typed/tofieldset.go
@@ -19,9 +19,9 @@ package typed
 import (
 	"sync"
 
-	"sigs.k8s.io/structured-merge-diff/v3/fieldpath"
-	"sigs.k8s.io/structured-merge-diff/v3/schema"
-	"sigs.k8s.io/structured-merge-diff/v3/value"
+	"sigs.k8s.io/structured-merge-diff/v4/fieldpath"
+	"sigs.k8s.io/structured-merge-diff/v4/schema"
+	"sigs.k8s.io/structured-merge-diff/v4/value"
 )
 
 var tPool = sync.Pool{
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/typed/typed.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/typed/typed.go
similarity index 98%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/typed/typed.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/typed/typed.go
index 056a07dee0c..1a99159a6eb 100644
--- a/vendor/sigs.k8s.io/structured-merge-diff/v3/typed/typed.go
+++ b/vendor/sigs.k8s.io/structured-merge-diff/v4/typed/typed.go
@@ -21,9 +21,9 @@ import (
 	"strings"
 	"sync"
 
-	"sigs.k8s.io/structured-merge-diff/v3/fieldpath"
-	"sigs.k8s.io/structured-merge-diff/v3/schema"
-	"sigs.k8s.io/structured-merge-diff/v3/value"
+	"sigs.k8s.io/structured-merge-diff/v4/fieldpath"
+	"sigs.k8s.io/structured-merge-diff/v4/schema"
+	"sigs.k8s.io/structured-merge-diff/v4/value"
 )
 
 // AsTyped accepts a value and a type and returns a TypedValue. 'v' must have
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/typed/union.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/typed/union.go
similarity index 98%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/typed/union.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/typed/union.go
index 26526cb8754..1fa5d88ae63 100644
--- a/vendor/sigs.k8s.io/structured-merge-diff/v3/typed/union.go
+++ b/vendor/sigs.k8s.io/structured-merge-diff/v4/typed/union.go
@@ -20,8 +20,8 @@ import (
 	"fmt"
 	"strings"
 
-	"sigs.k8s.io/structured-merge-diff/v3/schema"
-	"sigs.k8s.io/structured-merge-diff/v3/value"
+	"sigs.k8s.io/structured-merge-diff/v4/schema"
+	"sigs.k8s.io/structured-merge-diff/v4/value"
 )
 
 func normalizeUnions(w *mergingWalker) error {
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/typed/validate.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/typed/validate.go
similarity index 97%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/typed/validate.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/typed/validate.go
index 5c5a1cb64e0..a2f8f4eff12 100644
--- a/vendor/sigs.k8s.io/structured-merge-diff/v3/typed/validate.go
+++ b/vendor/sigs.k8s.io/structured-merge-diff/v4/typed/validate.go
@@ -19,9 +19,9 @@ package typed
 import (
 	"sync"
 
-	"sigs.k8s.io/structured-merge-diff/v3/fieldpath"
-	"sigs.k8s.io/structured-merge-diff/v3/schema"
-	"sigs.k8s.io/structured-merge-diff/v3/value"
+	"sigs.k8s.io/structured-merge-diff/v4/fieldpath"
+	"sigs.k8s.io/structured-merge-diff/v4/schema"
+	"sigs.k8s.io/structured-merge-diff/v4/value"
 )
 
 var vPool = sync.Pool{
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/value/allocator.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/value/allocator.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/value/allocator.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/value/allocator.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/value/doc.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/value/doc.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/value/doc.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/value/doc.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/value/fields.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/value/fields.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/value/fields.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/value/fields.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/value/jsontagutil.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/value/jsontagutil.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/value/jsontagutil.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/value/jsontagutil.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/value/list.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/value/list.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/value/list.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/value/list.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/value/listreflect.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/value/listreflect.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/value/listreflect.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/value/listreflect.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/value/listunstructured.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/value/listunstructured.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/value/listunstructured.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/value/listunstructured.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/value/map.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/value/map.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/value/map.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/value/map.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/value/mapreflect.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapreflect.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/value/mapreflect.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapreflect.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/value/mapunstructured.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapunstructured.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/value/mapunstructured.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapunstructured.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/value/reflectcache.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/value/reflectcache.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/value/reflectcache.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/value/reflectcache.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/value/scalar.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/value/scalar.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/value/scalar.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/value/scalar.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/value/structreflect.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/value/structreflect.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/value/structreflect.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/value/structreflect.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/value/value.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/value/value.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/value/value.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/value/value.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/value/valuereflect.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/value/valuereflect.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/value/valuereflect.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/value/valuereflect.go
diff --git a/vendor/sigs.k8s.io/structured-merge-diff/v3/value/valueunstructured.go b/vendor/sigs.k8s.io/structured-merge-diff/v4/value/valueunstructured.go
similarity index 100%
rename from vendor/sigs.k8s.io/structured-merge-diff/v3/value/valueunstructured.go
rename to vendor/sigs.k8s.io/structured-merge-diff/v4/value/valueunstructured.go
```

**Comment by liggitt** [comment]
Uh… that was weird

**Pull request merged**
