### PR TITLE
AWS: Recognize ca-central-1 region

### PR DESCRIPTION
**Pull request by justinsb**
Recognize the newly announced ca-central-1 region

### CODE REVIEW

**Comment by dims** [comment]
@justinsb Move the milestone please if appropriate?

**Comment by idyll** [comment]
As a person huddling from the cold in the Great White North right now, I would find warmth in the release of this change. ;) ☃️ 🇨🇦 :otocat: 🎄 🎁

**Comment by justinsb** [comment]
@dims I want to merge this into master and then have it cherry-picked into 1.4 and 1.5.  I lose track of the correct magic tagging...

**Comment by dims** [comment]
Ack @idyll @justinsb let's wait for @erictune 's lgtm :)

**Comment by dims** [comment]
LGTM 👍

**Comment by idyll** [comment]
So I'm new to the Kubernetes world... I have been using Docker with Convox and other tools on AWS up to this point. But this PR has me curious now.

Is this typical of the process around this project? I totally get this is open source, people have other priorities etc. Not trying to be a jerk. Just want to understand. 

It's a one line PR, with what appears to be low risk consequences, yet has sat open for over a week. And I can't (and likely many others like me) use Kubernetes without it...

**Comment by derekwaynecarr** [comment]
This is a priority for us at Red Hat and transferring assignee to @liggitt to apply tag.

**Comment by liggitt** [comment]
@k8s-bot please bazel test this

**Comment by saad-ali** [comment]
> I want to merge this into master and then have it cherry-picked into 1.4 and 1.5. I lose track of the correct magic tagging...

Cherry pick approved. Please create a cherry pick PR and put the 1.5 milestone and cherrypick-candidate label on it.

**Pull request merged**
