### PR TITLE
Specify host/container ports for InfluxDB, so that the UI is accessible

### PR DESCRIPTION
**Pull request by saad-ali**
CC @vishh

### CODE REVIEW

**Comment by vishh** [comment]
LGTM.

cc @thockin: Here is a case where we need to use hostports to make it work across all deployments.

**Comment by thockin** [comment]
Can someone explain why?  either here or email or IRL

**Comment by saad-ali** [comment]
Spoke with Tim offline: a better approach would be to get rid of these container/host port mappings, and create a load balancer rule to forward external traffic to the influx DB UI Kubernetes service IP.

**Comment by vishh** [comment]
The problem with a load balancer is that it does not work off the box for
all users.

**Comment by saad-ali** [comment]
But even this approach of  bridging host/container ports 8083/8086 won't work out-of-the-box for all users, right? It requires creating a firewall rule (different depending on cloud provider) to open up port 8083/8086 on the host machine to external traffic.

**Comment by vishh** [comment]
Yes. But that at-least works with most cloud providers and on-prem users. Until we can provide some fallback mechanism for load balancers, I am not comfortable using load balancers by default.

**Pull request merged**
