### PR TITLE
Promote NodePort service creation e2e test to conformance

### PR DESCRIPTION
**Pull request by johnbelamaric**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Promotes the NodePort service creation E2E test to conformance.

**Special notes for your reviewer**:
This replaces #75539 which cannot merge due to CLA and rebase issues.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cc @spiffxp

### CODE REVIEW

**Comment by spiffxp** [comment]
/lgtm

I hadn't followed along with https://github.com/kubernetes/kubernetes/pull/75539 so it took me a bit to catch up
- we now check connectivity using `nc` which should address the os-agnostic concerns raised by @PatrickLang (ref: https://github.com/kubernetes/kubernetes/pull/75539#issuecomment-485951702)
- we no longer exec a command on the node to really confirm ports are in use (agree this was too introspective, I like the new black box approach ref: https://github.com/kubernetes/kubernetes/pull/79667/files#r300998823)
- I think we can now get rid of the windows-specific tests @PatrickLang mentions (ref: https://github.com/kubernetes/kubernetes/pull/75539#issuecomment-485948665)

This looks way better, thanks for your work in simplifying this @mgdevstack

/assign @smarterclayton @bgrant0607 
for the /approve

**Comment by johnbelamaric** [comment]
Use of `CheckServiceReachability` implies anti-affinity, which does not have a conformance test yet. We should prioritize an explicit test for that.

**Comment by bgrant0607** [comment]
I don't see anti-affinity in this, but I agree we should have a test for that.

Exec pod:
https://github.com/kubernetes/kubernetes/blob/9aefaa163f9a8a397de20f4acd41aa25658e9133/test/e2e/framework/pod/resource.go#L463

Service pods:
https://github.com/kubernetes/kubernetes/blob/9aefaa163f9a8a397de20f4acd41aa25658e9133/test/e2e/framework/service/jig.go#L1035

I would like the description comment to be more descriptive, but that can be fixed in a follow up.

This checks reachability by service name, cluster IP, and nodeports using nc.

I confirmed that this runs on windows.

/lgtm
/approve

**Comment by bgrant0607** [comment]
Much better description. Thanks much.

/lgtm
/approve

**Comment by BenTheElder** [comment]
this is flaking a lot xref: https://github.com/kubernetes/kubernetes/pull/79667#issuecomment-521060822 https://github.com/kubernetes/kubernetes/issues/81200
https://testgrid.k8s.io/conformance-gce#GCE,%20master%20(dev)&show-stale-tests=&width=5&sort-by-flakiness=

**Comment by johnbelamaric** [comment]
Yes, see #81341 for the fix (we expect).

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/test-infra/pull/14731

**Pull request merged**
