### PR TITLE
Upgrades spf13/cobra to v1.7.0

### PR DESCRIPTION
**Pull request by jpmcb**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

[Cobra v1.7.0](https://github.com/spf13/cobra/releases/tag/v1.7.0) carries several optimizations and improvements for completions including bug fixes for powershell completions and the ability to source zsh completions directly.

As well, v1.6.1 had a fix for a panic edge case that did not affect kubernetes CLIs, but regardless, might be nice to consume.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@jpmcb please rebase and i'll approve/lgtm quickly

**Comment by jpmcb** [comment]
Force pushed to resolved the merge conflict! Thanks Dims!

**Pull request merged**
