### PR TITLE
Use busybox as base image for docker images of kubernetes-master components

### PR DESCRIPTION
**Pull request by ArtfulCoder**

### CODE REVIEW

**Comment by roberthbailey** [comment]
First commit is also in #6957.

**Comment by roberthbailey** [comment]
Why busybox? Can you give a brief description for the reason to change the base image?

**Comment by ArtfulCoder** [comment]
1. With scratch as base image, it is difficult to debug anything in the kube-master pods.
2. Also, kube-controller-manager uses hostname command and we dont have it in scratch.

busybox image size is small and gives us a good working container that addresses the above two points.

**Comment by ArtfulCoder** [comment]
updated the PR to remove the unwanted commit

**Comment by dchen1107** [comment]
@roberthbailey We can change it back later if busybox image is too big and cause trouble for us. Now we need this for debugging. 

LGTM.

**Comment by roberthbailey** [comment]
SGTM. Was mostly curious.

**Pull request merged**
