### PR TITLE
Fix typo in API server help for shutdown-delay-duration

### LINKED ISSUE #83120: Typo in API server shutdown-delay-duration help
**What happened**: https://github.com/kubernetes/kubernetes/blob/327f53ba57aeaa4b7e7c20b1ef98c42b26b7ea7f/staging/src/k8s.io/apiserver/pkg/server/options/server_run_options.go#L218 has a typo, `/readzy` (should be `/readyz`)

This also shows up in the rendered documentation.

**What you expected to happen**:
Documentation has correct path for readyz endpoint.

**How to reproduce it (as minimally and precisely as possible)**:
Easiest to see this wrong in the source code, I think.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16
- Cloud provider or hardware configuration: _not applicable_
- OS (e.g: `cat /etc/os-release`): _not applicable_
- Kernel (e.g. `uname -a`): _not applicable_
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig docs
/kind bug
/priority backlog

### PR DESCRIPTION
**Pull request by sftim**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Correct a typo in the API server help

**Which issue(s) this PR fixes**:
Fixes #83120

**Special notes for your reviewer**:
Once merged, SIG Docs will need to do a similar fix for the generated docs on the website; I'll PR that too.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/sig docs

### CODE REVIEW

**Review by jpbetz — APPROVED** [review]
/lgtm

**Comment by php-coder** [comment]
@sttts PTAL , this is just a typo :)

**Comment by sftim** [comment]
@kubernetes/sig-api-machinery-api-reviews would anyone have a moment to take a look at this one-line PR?

**Comment by sftim** [comment]
Oops, might have tagged the wrong group. Sorry if I have.

**Comment by sftim** [comment]
@kubernetes/sig-api-machinery-bugs this was for you, sorry.

**Pull request merged**
