### PR TITLE
Bump addon-resizer version in heapster

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #31105

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31614)

### CODE REVIEW

**Comment by wojtek-t** [comment]
@pwittrock - this PR is addressing part of P0 flaky test issue, can we have this merged for 1.4?

**Comment by wojtek-t** [comment]
@pwittrock - this PR is addressing part of P0 flaky test issue, can we have this merged for 1.4?

**Comment by pwittrock** [comment]
Fixes a p0 flake

**Comment by pwittrock** [comment]
@wojtek-t @gmarek 

If I am reading the scalability test history correctly, it looks like they started failing relatively consistently around the time this was merged.

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/

Would you take a look, and rollback if necessary?

Currently, the scalability test is the only one that is too problematic for a release.

**Comment by wojtek-t** [comment]
@pwittrock - yes - it seems to be related (the consequences seems to be indirect, but still). I'm reverting this PR and will try to debug offline.

**Comment by wojtek-t** [comment]
OK - so I actually debugged the issue and fixed (at least it's working now when I'm running 100-node clusters) it in https://github.com/kubernetes/contrib/pull/1664
Since this PR is already reverted, I will send another one that will bump to the next version.

**Pull request merged**
