### PR TITLE
Improve and simplify maintenance of APF bootstrap objects

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Three things:

- Make deletion of unwanted object conditional on ResourceVersion, to avoid being confused by concurrent updates.

- Remove unnecessary split between finding unwanted objects and removing them.

- Remove unnecessary layers of indirection to reach constant logic.

#### Which issue(s) this PR fixes:

This addresses point 4 of #107097 .

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-misc 
/cc @wojtek-t 
/cc @tkashem

**Comment by MikeSpreitzer** [comment]
@deads2k 
@lavalamp

**Review by wojtek-t — COMMENTED** [review]
/assign @tkashem

**Comment by MikeSpreitzer** [comment]
#111422 is an alternative to this, I hope we can merge that one.

**Comment by MikeSpreitzer** [comment]
Closing in favor of #111422

**Pull request closed without merging**
