### PR TITLE
add POD annotations as runtime config for extensible function of CNI

### PR DESCRIPTION
**Pull request by mainred**
**What this PR does / why we need it**:
POD annotations is added as runtime config, and can be used by CNI for extensible work.

Currently we only expose containerID, namespace, pod name network namespace from container/kubernetes to CNI,  and make a restriction on the use of CNI.

**Special notes for your reviewer**:

**Release note**:

```release-note
add POD annotations as runtime config for extensible function of CNI
```

### CODE REVIEW

**Comment by thockin** [comment]
/ok-to-test

I am not as familiar with CNI as I once was, but this seems OK?  This comes through as CNI_ARGS, right?

@dcbw @bboreham thoughts?  I feel like this was discussed at some point but not sure why we didn't do it.  Maybe we want to be more selective than all annotations?

**Comment by thockin** [comment]
I feel like there's got to be some use-cases for a user being able to
specify something about their pod and have that be reflected in CNI, but
maybe it's just not as arbitrary as that.
It came up recently in a context I can't quite recall.  I think it was
around GPUs that are also netdevs, and how to link the two plugin
lifecycles, but the details have been temporarily paged out

We don't want CNI plugins being coupled to Kubernetes concepts, the same as
we don't want containers coupling to Kubernetes.  This is a big part of why
the downward API is so convoluted.  Do we have examples of plugins that say
"if only I knew X, I could be smarter" ??  Like, what if an annotation `
cni.io/args: "[{my-plugin-foo, true}, {my-plugin-bar, 42}]"` could be
recognized by the CNI driver adapter and turned into args to pass in to the
driver.  Do we have any itch that would scratch?

What is the use-case driving this PR?

**Comment by mainred** [comment]
> What is the use-case driving this PR?

I am recently working on static IP for a POD, and of course, it is some kind of customized.  So ownerReference is needed by the IPAM to specify the IP address.

Above is my motivation,  and I think even CNI is platform-independent, but need to/can be extensible for on platform of customized, and above platform for common use.

I think we can 
- add a switch for kubelet, default to be False, which means not adding annotations as CNI env vars, and selective.
- use more selective method as thockin said to eliminate unuseful info.

**Comment by bboreham** [comment]
“I need a specific ip” and “I need a specific MAC” come up fairly often. If Kubernetes wants to facilitate them, they could be turned into specific fields in the CNI request. 

That way the CNI plugin doesn’t need to know anything about Kubernetes.

**Comment by thockin** [comment]
Both “I need a specific ip” and “I need a specific MAC” are things that may or may not be supported on any given CNI driver

**Comment by mainred** [comment]
Maybe we should keep CNI clear and simple, adding annotations as environment for CNI has alternative ways, e.g. static way from config and dynamic one from Apiserver. 
I’ll close this pull request if no one else has opinion on it.

**Pull request closed without merging**
