### PR TITLE
update to new level of agnhost

### PR DESCRIPTION
**Pull request by deads2k**
updating to use https://github.com/kubernetes/kubernetes/pull/110174 .

Following directions from https://github.com/kubernetes/kubernetes/tree/master/test/images#promoting-images

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
@aojea trouble building the image?  locally I see

```
[deads@fedora origin]$ oc logs -f service-test-9kqmn
exec /agnhost: no such file or directory
```

**Comment by aojea** [comment]
/retest

the anghost binary needs to be built with `CGO_ENABLED=0 go build ` in order to run in alpine :shrug:

**Comment by aojea** [comment]
> @aojea trouble building the image? locally I see
> 
> ```
> [deads@fedora origin]$ oc logs -f service-test-9kqmn
> exec /agnhost: no such file or directory
> ```

@deads2k fixes, seems this is good to go , at least in CI is not failing

**Comment by deads2k** [comment]
now a real update

/hold cancel
/sig network

**Comment by aojea** [comment]
hmm https://storage.googleapis.com/k8s-triage/index.html?sig=network#7ccacb7807a6b800df8c

things started to fail on these tests, that use the healthz endpoint for readiness

**Pull request merged**
