### PR TITLE
Reverting 18442

### PR DESCRIPTION
**Pull request by ArtfulCoder**

### CODE REVIEW

**Comment by ArtfulCoder** [comment]
@deads2k

**Comment by ArtfulCoder** [comment]
#18442 is One of the causes of this issue https://github.com/kubernetes/kubernetes/issues/18845

Hence the revert.

**Comment by caesarxuchao** [comment]
@ArtfulCoder Could you point out where you had to manually fix during the revert?

**Comment by ArtfulCoder** [comment]
@caesarxuchao  pkg/api/unversioned/group_version.go

**Comment by ArtfulCoder** [comment]
Manually merging to fix e2e

**Comment by caesarxuchao** [comment]
I take a look at #18526 and it seems to not depend on #18442, so the revert should be safe.

**Comment by ArtfulCoder** [comment]
Thanks Chao!

**Pull request merged**
