### PR TITLE
contribute deis/registry-proxy as a replacement for kube-registry-proxy

### PR DESCRIPTION
**Pull request by bacongobbler**
This PR is a proposal to replace the `kube-registry-proxy` addon code with [deis/registry-proxy](https://github.com/deis/registry-proxy). We have been running this component in production for several months ([since Workflow v2.3.0](https://github.com/deis/charts/blob/15d4c1c29875b463d59d64e1893fd72010f9876a/workflow-v2.3.0/tpl/deis-registry-proxy-daemon.yaml)) without any issues.

There are several benefits that this proxy provides over the current implementation:
- it's the same code that is provided in [docker/distribution's contrib dir](https://github.com/docker/distribution/tree/master/contrib/compose) which I have personally used for both Docker v1 and v2 engine deployments without any issues
- the ability to [disable old Docker clients](https://github.com/deis/registry-proxy/blob/master/rootfs/etc/nginx/conf.d/default.conf.in#L19-L23) that are incompatible with the v2 registry
- better default connection timeouts, using best practices from the Docker community as a whole
- workarounds for bugs like https://github.com/docker/docker/issues/1486 (see https://github.com/deis/registry-proxy/blob/master/rootfs/etc/nginx/conf.d/default.conf.in#L15-L16)

Things that this PR differs from the current implementation:
- it's not HAProxy.

I'm not sure how the release process goes for this component, but I bumped the version to v0.4 and changed the maintainer to myself considering this is a massive overhaul. Please let me know if this is acceptable as a replacement or if we should perhaps consider this as an alternative implementation.

Happy Friday!

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35797)

### CODE REVIEW

**Comment by bacongobbler** [comment]
Hold up; gonna have to get Deis to sign the Linux CLA now.

**Comment by bacongobbler** [comment]
Okay, I've signed the CLA

**Comment by roberthbailey** [comment]
this looks reasonable assuming we get agreement from the current maintainers to swap out the implementation.

**Comment by uluyol** [comment]
REGISTRY_CA was previously unused and I don't remember what the planned use for it was. It looks like now you are using it to authenticate the registry itself which is fine and probably won't confuse anyone since it was meaningless before.

Please add some docs for using REGISTRY_CA. Besides that LGTM.

**Comment by bacongobbler** [comment]
It was a last-minute addon to get it feature-complete with what's in the current implementation. We don't even have that in deis/registry-proxy so if it's unused and nobody has seen any need for it I'm all for removing that chunk of code. Does that work for you, or would you like to go ahead with documentation on REGISTRY_CA?

**Comment by uluyol** [comment]
It's probably a good idea to authenticate the registry if it's using TLS, but if this is untested then removal (+ adding a TODO) sounds better.

Someone probably needs to push the image to gcr.io, I don't have permissions to do that.

**Comment by bacongobbler** [comment]
For others willing to manually test this:

```
$ docker run -dp 5000:5000 registry:2.3.1
$ cd cluster/addons/registry/images
$ make build
$ docker run -dp 5001:80 -e REGISTRY_HOST=$MY_IP_ADDRESS -e REGISTRY_PORT=5000 gcr.io/google_containers/kube-registry-proxy:0.4
$ curl localhost:5001/v2/
{}
$ docker tag gcr.io/google_containers/kube-registry-proxy:0.4 192.168.0.19:5001/kube-registry-proxy:0.4
$ docker push 192.168.0.19:5001/kube-registry-proxy:0.4
The push refers to a repository [192.168.0.19:5001/kube-registry-proxy]
2b2818699de8: Pushed 
6a549b57a119: Pushed 
5f70bf18a086: Pushed 
bbf4634aee1a: Pushed 
64d0c8aee4b0: Pushed 
4dcab49015d4: Pushed 
0.4: digest: sha256:bd7da72ec6db3c1bfb8b9813113529e05aa8c7de9e732dc4274c7b9ddd12ee68 size: 2397
```

**Comment by surajssd** [comment]
@roberthbailey hey whichever PR goes second might need to rebase on the first one, I guess :)

**Comment by roberthbailey** [comment]
this looks good to me but i'll wait for an ack from @uluyol before applying the label.

**Comment by uluyol** [comment]
LGTM

**Comment by bacongobbler** [comment]
ping, anything needed on my end to get this through?

**Comment by roberthbailey** [comment]
It won't merge until the code freeze lifts next week.

**Comment by bgrant0607** [comment]
cc @thockin @pwittrock

**Comment by bgrant0607** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by thockin** [comment]
LGTM, just skimmed though :)

**Comment by hoffin** [comment]
I've just been through the process of using this and there's a small change needed to the documentation. I've created a [PR here](https://github.com/kubernetes/kubernetes/pull/38397).
Great stuff. Working well so far.

**Pull request merged**
