### PR TITLE
Start building etcd v3.6.0-alpha.0 image for scalability tests

### PR DESCRIPTION
**Pull request by serathius**
/kind feature

```release-note
NONE
```

/sig scalability

### CODE REVIEW

**Comment by pacoxu** [comment]
During reading the changelog of etcd v3.6, there is a breaking change and has it any influences to Kubernetes upgradetion?
- [Breaking Changes](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.6.md#breaking-changes) etcd will no longer start on data dir created by newer versions (for example etcd v3.6 will not run on v3.7+ data dir). To downgrade data dir please check out etcdutl migrate command.

**Comment by serathius** [comment]
> During reading the changelog of etcd v3.6, there is a breaking change and has it any influences to Kubernetes upgradetion?
> 
> * [Breaking Changes](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.6.md#breaking-changes) etcd will no longer start on data dir created by newer versions (for example etcd v3.6 will not run on v3.7+ data dir). To downgrade data dir please check out etcdutl migrate command.

This change is in data compatibility policy for downgrades. Etcd never really supported downgrades as it recommenced to restore backup from before upgrade, however it prevented users from doing so. Fact that data was backward compatible was never guaranteed nor validated. 

With introduction of downgrade support to etcd we are trying to provide a downgrade guarantees, however this first comes with restrictions about removing unsafe operations. With v3.6 etcd will no longer allow administrators to just downgrade the binary and run on the same data directory. On the other side etcd will provide an tooling and documentation about how a proper etcd downgrade process should be executed.

As this change is in downgrade behavior to v3.6, there is no immediate impact of this PR to K8s as it would change ability of downgrading from v3.7 to v3.6. As for future actions that K8s should do for v3.7, it will require updating K8s https://github.com/kubernetes/kubernetes/blob/master/cluster/images/etcd/migrate-if-needed.sh script to utilize official etcd tooling like `etcdutl migrate`.

**Comment by pacoxu** [comment]
Thanks for the clarification.

**Pull request merged**
