### PR TITLE
controller/endpoint: explict log msg when syncing error

### PR DESCRIPTION
**Pull request by sak0**
explict log msg for retrying sync

Signed-off-by: CuiHaozhi <cuihaozhi@chinacloud.com.cn>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm

**Comment by MrHohn** [comment]
@sak0 Please remove the release note and I will approve.

**Comment by sak0** [comment]
@MrHohn removed

**Comment by MrHohn** [comment]
Thanks!
/approve

**Pull request merged**
