### PR TITLE
Improve the author and number info of the PR.

### PR DESCRIPTION
**Pull request by warmchang**
**What this PR does / why we need it**: Improve the author and number info of the PR.

### CODE REVIEW

**Comment by nikhita** [comment]
@yujuhong fyi

**Comment by xiangpengzhao** [comment]
@warmchang Thanks for the PR! But 1.6 is no longer supported in 1.10 cycle, so I'm not sure if we still want to update 1.6 CHANGELOG. @jdumars WDYT?

**Comment by warmchang** [comment]
What's your suggestion? @yujuhong @ethernetdan

**Comment by dchen1107** [comment]
Ahh, I agreed with @xiangpengzhao 's comment: https://github.com/kubernetes/kubernetes/pull/57714#issuecomment-355260923

**Comment by dchen1107** [comment]
May I suggest close this one?

**Comment by warmchang** [comment]
ok, close it, thanks.
/close

**Pull request closed without merging**
