### PR TITLE
fix kubectl config return 0 on error

### PR DESCRIPTION
**Pull request by shiywang**
Fixes https://github.com/kubernetes/kubernetes/issues/42852
cc @kubernetes/sig-cli-bugs
@ymqytw ptal

### CODE REVIEW

**Comment by ymqytw** [comment]
It seems that it no longer print help message with your change. But we still need the help message.

**Comment by shiywang** [comment]
## kubectl config return 0 on error umbrella

@ymqytw @pwittrock @AdoHe @fabianofranz I create a list to check all command if they return 0 on error, still checking
Available Commands:
  - [ ] annotate      
  - [ ] api-versions  
  - [ ] apply         
  - [ ] attach        
  - [ ] autoscale     
  - [ ] certificate   
  - [ ] cluster-info  
  - [ ] completion    
  - [ ] config        
  - [ ] convert       
  - [ ] cordon        
  - [ ] cp            
  - [ ] create        
  - [ ] delete        
  - [ ] describe      
  - [ ] drain         
  - [ ] edit          
  - [ ] exec          
  - [ ] explain       
  - [ ] expose        
  - [ ] get           
  - [ ] help          
  - [ ] label         
  - [ ] logs          
  - [ ] patch         
  - [ ] port-forward  
  - [ ] proxy         
  - [ ] replace       
  - [ ] rolling-update
  - [ ] rollout       
  - [ ] run           
  - [ ] scale         
  - [ ] set           
  - [ ] stop          
  - [ ] taint         
  - [ ] top           
  - [ ] uncordon      
  - [ ] version

**Comment by shiywang** [comment]
@ymqytw  `cmd.Help()` added, ptal

**Comment by fabianofranz** [comment]
@kubernetes/sig-cli-pr-reviews 
@k8s-bot ok to test

**Comment by shiywang** [comment]
@ymqytw really weired, I always using `make` and `make test WHAT=./pkg/kubectl/cmd` to check my code and all pass, but still failed in jenkins tests, turn out there's one line in `pkg/kubectl/cmd/config/create_authinfo_test.go` didn't even pass the compile, How do you check that ? 
Is `make test =./pkg/kubectl/cmd`  wrong ?

**Comment by liggitt** [comment]
to get subpackages, you need to do `make test WHAT=./pkg/kubectl/cmd/...`

**Comment by shiywang** [comment]
@liggitt oh, I see, thanks

**Comment by shiywang** [comment]
@fabianofranz  @ymqytw  ptal

**Comment by shiywang** [comment]
@ymqytw  kindly ping

**Comment by fabianofranz** [comment]
good job @shiywang 
/approve

**Comment by ymqytw** [comment]
@k8s-bot non-cri e2e test this

**Pull request merged**
