### PR TITLE
Allow custom transport even when client cert auth is used

### LINKED ISSUE #103225: Custom Transport can't be used with client-go if client cert is used
#### What happened:
https://github.com/kubernetes/client-go/blob/v0.21.1/transport/transport.go#L36-L39

`transport.New(config *Config) ) (http.RoundTripper, error)` does not allow setting custom Transport if client cert auth is used. I would like to be able to set custom transport even when client cert auth is used.

I am using a custom transport that is used to connect to airgapped clusters (imagine my hosted web app wants to connect to a KIND cluster running on a user desktop). Using `HTTPWrappersForConfig` is not enough in this case. I need to be able to catch the final `request` object and pass it via my tunnel to talk to such air gapped clusters. I hit this issue when I call `RESTClientFor(config *Config)`.

As a side note, I tried to use the `kubernetes.New(rest.Interface)` api. That is also not possible due to #103224 . 

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Allow custom transport even when client cert auth is used

#### Which issue(s) this PR fixes:

Fixes #103225

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/hold

Doesn't this mean the CA/Cert info in the config is simply ignored in favor of the custom transport? That seems misleading/dangerous (which is why this check was added in the first place).

**Comment by tamalsaha** [comment]
I also pass the cert info with the tunnel to complete the connection. It is not ignored. For Kind clusters, if client cert auth is ignored the http request will not work.

In general, IMHO, if a user wants to set custom transport, client-go should assume that the user of the library knows what they are doing and let them do that.

**Comment by liggitt** [comment]
> I also pass the cert info with the tunnel to complete the connection. It is not ignored.

it is ignored by client-go transport.New...

**Comment by liggitt** [comment]
> In general, IMHO, if a user wants to set custom transport, client-go should assume that the user of the library knows what they are doing and let them do that.

accepting options that conflict with each other and silently ignoring some of them doesn't make for a great experience... can you clear the CA/Cert fields as you consume them to construct your custom transport?

**Comment by tamalsaha** [comment]
> can you clear the CA/Cert fields as you consume them to construct your custom transport?

I can't clear those otherwise I am going to get 401 errors (when client cert auth is used).

**Comment by liggitt** [comment]
> I can't clear those otherwise I am going to get 401 errors (when client cert auth is used).

do you have a pointer to your code where this is happening?

**Comment by enj** [comment]
@tamalsaha I am going to close this out because we believe the current behavior to be correct.  Please feel free to reopen and respond to Jordan's comment in https://github.com/kubernetes/kubernetes/pull/103230#issuecomment-870680595 if you are still encountering the issue.

/close

**Pull request closed without merging**
