### PR TITLE
apis: update comment for Eviction resource

### PR DESCRIPTION
**Pull request by 0xmichalis**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35390)

### CODE REVIEW

**Comment by mml** [comment]
Did we change the path name?

I know it is nonsense to talk of a pod having "evictions" plural, but at the same time, when you POST a request... as an attempt to create a resource, it's usually to a path that describes the directory which, at least notionally, encloses a collection of these things.  While we **do** use the singular for another subresource, `scale`, that is because we are actually PUTting and POSTing the singleton scale resource, whereas here we are asking if we can create *an* eviction (and we might get denied).

OK, having put in my 2c, If everyone else has already adopted the `/eviction` pathname, then LGTM.

**Comment by kargakis** [comment]
Right now it is setup as `eviction`, this PR brings the docs up to date

**Comment by kargakis** [comment]
@mml mind tagging this and having a separate issue for changing the path to `evictions` if you want? As it stands, the doc is inaccurate.

**Comment by mml** [comment]
My fault.  I implied you could add the label in my last comment, but should have been more explicit.

**Pull request merged**
