### PR TITLE
Support the node label `node.kubernetes.io/exclude-from-external-load-balancers`

### LINKED ISSUE #401: Exclude node from LoadBalancer doesn't work as expected
**What happened**:

Exclude node from LoadBalancer only works when first time a node joins cluster, it doesn't work when apply the node label later.

e.g. when running `kubectl label node k8s-agentpool-86949660-0 node.kubernetes.io/exclude-from-external-load-balancers=true`, the node is still in LoadBalancer backend address pool.

**What you expected to happen**:

The node should be removed from LoadBalancer backend address pool.

**How to reproduce it**:

Run `kubectl label node <node-name> node.kubernetes.io/exclude-from-external-load-balancers=true` and then check LoadBalancer backend address pool list.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/kind bug

### PR DESCRIPTION
**Pull request by nilo19**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
Support the node label `node.kubernetes.io/exclude-from-external-load-balancers`.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes-sigs/cloud-provider-azure/issues/401

**Special notes for your reviewer**:
The kubernetes controller manager supports excluding nodes from the load balancer backend pools by enabling the feature gate `ServiceNodeExclusion`, which is in beta state since v1.19. This PR let users to exclude nodes from the LB by labeling `node.kubernetes.io/exclude-from-external-load-balancers=true` on the nodes. There are several things that need to be mentioned.
1. To use the feature, the feature gate `ServiceNodeExclusion` should be on.
2. The labeled nodes would be excluded from the LB in the next LB reconcile loop, which needs one or more LB typed services to trigger. Basically, users could trigger the update by creating a service. If there are one or more LB typed services existing, no extra operations are needed.
3. To re-include the nodes, just remove the label and the update would be operated in the next LB reconcile loop.

**Does this PR introduce a user-facing change?**:

```release-note
Support the node label `node.kubernetes.io/exclude-from-external-load-balancers`
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/sig cloud-provider
/area provider/azure
/priority important-soon

### CODE REVIEW

**Review by andrewsykim — COMMENTED** [review]
Support for ServiceNodeExclusion is done at the service controller level, not per cloud provider, wondering how this PR is adding support for the node label.

**Comment by nilo19** [comment]
> Support for ServiceNodeExclusion is done at the service controller level, not per cloud provider, wondering how this PR is adding support for the node label.

The label only works when the node joins the cluster with the label at the first time. Label an existing node would not work for Azure. I would change it to a bug fix instead of a feature.

**Comment by andrewsykim** [comment]
> The label only works when the node joins the cluster with the label at the first time. Label an existing node would not work for Azure. I would change it to a bug fix instead of a feature.

Is there a specific behavior with the Azure cloud provider that results in this?

**Comment by nilo19** [comment]
> > The label only works when the node joins the cluster with the label at the first time. Label an existing node would not work for Azure. I would change it to a bug fix instead of a feature.
> 
> Is there a specific behavior with the Azure cloud provider that results in this?

yes

**Comment by andrewsykim** [comment]
Can you explain the behavior a bit? Is it because node objects are cached indefinitely so the label is not picked up? Is the list of nodes passed into `EnsureLoadBalancer` and `UpdateLoadBalancer` ignored?

**Comment by nilo19** [comment]
The label is picked up but Azure only ensures that all nodes are joined to the LB backend pool, and fails to decouple the labeled node from the LB.

**Comment by nilo19** [comment]
Actually, the labeled node would not be in the node list of the LB reconcile loop. This PR adds a check that if the node in the pool is not in the list, remove it.

**Comment by nilo19** [comment]
close and create a new PR to git rid of the `/kind feature`  history
/close

**Pull request closed without merging**
