### PR TITLE
promote PodNodeSelector admission controller annotations to stable

### PR DESCRIPTION
**Pull request by colemickens**
**What this PR does / why we need it**:
* promotes the `PodNodeSelector` admission controller and annotations to stable, per discussion on #57424
* deprecates the alpha annotation (`scheduler.alpha.kubernetes.io/node-selector`) but supports it simultaneously with the new annotation (`scheduler.kubernetes.io/node-selector`), again per discussion on #57424
* adds tests showing the alpha and stable annotations are merged and considered correctly
* moves the parsing of the config files node selector into plugin initialization
* adds api validation checks for the pod node selector values
* introduces versioned configuration for PodNodeSelector plugin

(**Note:** it intentionally drops support for the alpha configuration format due to some discussed potential concerns about incorrectly parsing legacy configuration in a way that leaves the cluster mistakenly open in some way. The format also was just undesirable due to effectively being a map with a special-cased key.)

**Which issue(s) this PR fixes**: Partially addresses #57424 (the other half, addressing `PodTolerationRestriction` will follow this PR).

Corresponding Docs PR: https://github.com/kubernetes/website/pull/7134 (This will be updated again to discuss the versioned config, etc).

**Release note**:

```release-note
* PodNodeSelector: `scheduler.alpha.kubernetes.io/node-selector` is deprecated in favor of `scheduler.kubernetes.io/node-selector`
* PodNodeSelector: support for alpha configuration format is removed. support for v1 configuration is added.
```

cc: @ericchiang @liggitt

### CODE REVIEW

**Comment by ericchiang** [comment]
Flaking on https://github.com/kubernetes/kubernetes/issues/59426


/test pull-kubernetes-unit

**Comment by lavalamp** [comment]
Stable features should not be using annotations like this, I think. Has this been debated?

**Comment by lavalamp** [comment]
Why is this api machinery?

**Comment by adampl** [comment]
Hi, what about this issue? Has it been sorted out?

**Comment by pierluigilenoci** [comment]
@colemickens what happened to this PR?

**Comment by adampl** [comment]
@colemickens reopen?

**Pull request closed without merging**
