### PR TITLE
Remove hacks added for mesos

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

Since Mesos is no longer in your main repository and since we have
things like dynamic kubelet configuration in progress, we should
drop these undocumented, untested, private hooks.

cmd/kubelet/app/server.go::CreateAPIServerClientConfig
CreateAPIServerClientConfig::getRuntime
pkg/kubelet/kubelet_pods.go::getPhase

Also remove stuff from Dependencies struct that were specific to
the Mesos integration (ContainerRuntimeOptions and Options)

Also remove stale references in test/e2e and and test owners file

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Drop hacks used for Mesos integration that was already removed from main kubernetes repository
```

### CODE REVIEW

**Comment by ncdc** [comment]
@smarterclayton @deads2k @liggitt @sttts are you using any of these funcs in origin that are no longer exported in this PR?

**Comment by liggitt** [comment]
> @smarterclayton @deads2k @liggitt @sttts are you using any of these funcs in origin that are no longer exported in this PR?

no

**Comment by dims** [comment]
@mtaufen @ncdc @liggitt can we please merge this early for 1.10 so there's opportunity to spot any uses in the wild 

Thanks,
Dims

**Comment by mtaufen** [comment]
SGTM

**Comment by ncdc** [comment]
@dims wfm, although you'll likely only find out about issues if people update their vendored copy of kube against master after this merges. I'm not sure how likely that will be.

**Comment by dims** [comment]
/assign @thockin @vishh

Can i get some approvals/lgtm please? ripping out code left over from mesos stuff and have consensus from @ncdc @mtaufen @liggitt

**Comment by thockin** [comment]
nice cleanup!  Thanks.

/lgtm
/approve no-issue

**Pull request merged**
