### PR TITLE
stop: Make use of deprecation field

### PR DESCRIPTION
**Pull request by 0xmichalis**

### CODE REVIEW

**Comment by kargakis** [comment]
@kubernetes/kubectl

**Comment by jlowdermilk** [comment]
Needs `hack/update-generated-docs.sh`

**Comment by kargakis** [comment]
@jlowdermilk thanks. Do I need to update any e2e test? I looked into the one failing above but I don't see why...

**Comment by ashcrow** [comment]
@kargakis I've seen the @k8s-teamcity-mesosphere happening with folks who have a slightly older fork. If you'd like to verify you can rebase and it should pass fine.

**Comment by ashcrow** [comment]
@kargakis mind forcing a rebuild. I think the failure is flake related as the build log is empty.

**Comment by jlowdermilk** [comment]
@k8s-bot e2e test this

**Comment by kargakis** [comment]
rebased due to conflicts

**Comment by kargakis** [comment]
had to rebase

**Pull request merged**
