### PR TITLE
Removed unused provider specific code in gce provider

### PR DESCRIPTION
**Pull request by piosz**

### CODE REVIEW

**Comment by piosz** [comment]
cc @bprashanth @justinsb @roberthbailey

**Comment by davidopp** [comment]
Hmm, I wonder if we should keep this, in case at some point we decide it would be useful for the Kubernetes control plane to create and know about MIGs?

**Comment by bprashanth** [comment]
Don't do this, there're downstream clients that use them (specifically the GCE L7 controller, to avoid copying all the oauth logic around and leave the option of running it a part of controller manager open).

**Comment by bprashanth** [comment]
If we'd like to do this soon please file a bug on me and I can figure out the refactor and whether or not we should merge/move the L7 controller.

**Comment by davidopp** [comment]
I don't see any reason to do this soon. I'm going to close the issue and @piosz can reopen if he thinks it's urgent.

**Comment by piosz** [comment]
Thanks for letting us know @bprashanth. I've just noticed that the code is not used anywhere. The code also operate on Instance Group concept and I'm pretty sure we don't want to operate on them (we want to operate on Instance Group Managers aka Managed Instance Group).

BTW @davidopp I think that keeping code just "in case at some point we decide it would be useful" is extremely bad strategy. We will end up with 3x larger codebase with a thousands of lines of dead code.

**Comment by davidopp** [comment]
Very sorry, I thought this was for MIGs, I didn't realize it was for something else. So I don't object to getting rid of it.

But I guess @bprashanth said we should keep it anyway.

**Comment by piosz** [comment]
No worries. Anyway I think we should move this somewhere else. This is not an implementation of the CloudProvider interface.

**Pull request closed without merging**
