### PR TITLE
use pause image with fat-manifest

### PR DESCRIPTION
**Pull request by lubinsz**
What this PR does / why we need it:
Pause manifest code is merged in #57723, so we should use new image in test.

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #

Special notes for your reviewer:

Release note:

### CODE REVIEW

**Comment by lubinsz** [comment]
hi @dims 
It seems that the failed case has nothing to do with my modification.
Thanks.

**Comment by fabriziopandini** [comment]
@lubinsz  sorry for the delay in responding but I was ooo
Could you kindly provide a little bit of background? 
Does that means that there will be only one pause image from now on (without -arch suffix)? Does this affect also older  kubeadm  releases or only v1.12?

**Comment by lubinsz** [comment]
@fabriziopandini 
Hi,
Pause manifest code is merged in #57723. 
It means, starting from 1.12, different platforms use the same name image with fat-manifest.
So, the advantage of doing this is that, even in Arm platform, we can also run the test case with
the same name pause image:  k8s.gcr.io/pause:3.1

**Comment by lubinsz** [comment]
ping @fabriziopandini

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Pull request merged**
