### PR TITLE
update golangci-lint for go 1.19 and delete hardcode go version in golangci-lint config

### LINKED ISSUE #111734: Update config for `unused` plugin in .golangci.yaml to golang 1.19
Here's the update to .golangci.yaml to clean up unused code that shows up when we specify `go` version to `1.19`

```
[dims@dims-m1-7728 17:05] ~/go/src/k8s.io/kubernetes ⟩ git diff
diff --git .golangci.yaml .golangci.yaml
index e6a6ff9e17b9..c1cd7399f837 100644
--- .golangci.yaml
+++ .golangci.yaml
@@ -45,4 +45,4 @@ linters-settings: # please keep this alphabetized
       "ST1019",  # Importing the same package multiple times.
     ]
   unused:
-    go: "1.18"
+    go: "1.19"
```

and then run `hack/verify-golangci-lint.sh`, you will see the following failures:
```
[dims@dims-m1-7728 17:05] ~/go/src/k8s.io/kubernetes ⟩ hack/verify-golangci-lint.sh
installing golangci-lint and logcheck plugin from hack/tools into /Users/dims/go/src/k8s.io/kubernetes/_output/local/bin
running golangci-lint
pkg/volume/util/hostutil/hostutil.go:78:6: func `getFileType` is unused (unused)
func getFileType(pathname string) (FileType, error) {
     ^
pkg/util/iptables/iptables_unsupported.go:31:6: func `grabIptablesFileLock` is unused (unused)
func grabIptablesFileLock(f *os.File) error {
     ^
pkg/volume/util/fsquota/quota.go:48:6: func `enabledQuotasForMonitoring` is unused (unused)
func enabledQuotasForMonitoring() bool {
     ^
pkg/kubelet/config/file.go:49:2: field `eventType` is unused (unused)
	eventType podEventType
	^
pkg/kubelet/config/file.go:48:2: field `fileName` is unused (unused)
	fileName  string
	^
pkg/kubelet/config/file.go:42:2: const `podDelete` is unused (unused)
	podDelete
	^
pkg/kubelet/config/file.go:40:2: const `podAdd` is unused (unused)
	podAdd podEventType = iota
	^
pkg/kubelet/config/file.go:37:6: type `podEventType` is unused (unused)
type podEventType int
     ^
pkg/kubelet/config/file.go:41:2: const `podModify` is unused (unused)
	podModify
	^
cmd/kubelet/app/options/globalflags.go:53:6: func `register` is unused (unused)
func register(global *flag.FlagSet, local *pflag.FlagSet, globalName string) {
     ^
cmd/kubelet/app/options/globalflags.go:74:6: func `registerDeprecated` is unused (unused)
func registerDeprecated(global *flag.FlagSet, local *pflag.FlagSet, globalName, deprecated string) {
     ^
pkg/volume/local/local_test.go:472:6: func `testFSGroupMount` is unused (unused)
func testFSGroupMount(plug volume.VolumePlugin, pod *v1.Pod, tmpDir string, fsGroup int64) error {
     ^
pkg/volume/awsebs/aws_util.go:220:6: func `getDiskByIDPaths` is unused (unused)
func getDiskByIDPaths(volumeID aws.KubernetesVolumeID, partition string, devicePath string) []string {
     ^
pkg/volume/awsebs/aws_util.go:205:6: func `verifyDevicePath` is unused (unused)
func verifyDevicePath(devicePaths []string) (string, error) {
     ^
pkg/volume/awsebs/aws_util.go:267:6: func `findNvmeVolume` is unused (unused)
func findNvmeVolume(findName string) (device string, err error) {
     ^
pkg/kubelet/cm/helpers.go:25:6: func `hardEvictionReservation` is unused (unused)
func hardEvictionReservation(thresholds []evictionapi.Threshold, capacity v1.ResourceList) v1.ResourceList {
     ^
pkg/kubelet/cm/container_manager.go:198:6: func `containerDevicesFromResourceDeviceInstances` is unused (unused)
func containerDevicesFromResourceDeviceInstances(devs devicemanager.ResourceDeviceInstances) []*podresourcesapi.ContainerDevices {
     ^
pkg/kubelet/cm/helpers_unsupported.go:55:6: func `getCgroupProcs` is unused (unused)
func getCgroupProcs(dir string) ([]int, error) {
     ^
pkg/kubelet/kuberuntime/security_context.go:28:37: func `(*kubeGenericRuntimeManager).determineEffectiveSecurityContext` is unused (unused)
func (m *kubeGenericRuntimeManager) determineEffectiveSecurityContext(pod *v1.Pod, container *v1.Container, uid *int64, username string) (*runtimeapi.LinuxContainerSecurityContext, error) {
                                    ^
pkg/kubelet/kuberuntime/security_context.go:112:6: func `convertToRuntimeSELinuxOption` is unused (unused)
func convertToRuntimeSELinuxOption(opts *v1.SELinuxOptions) *runtimeapi.SELinuxOption {
     ^
pkg/kubelet/kuberuntime/security_context.go:86:6: func `convertToRuntimeSecurityContext` is unused (unused)
func convertToRuntimeSecurityContext(securityContext *v1.SecurityContext) *runtimeapi.LinuxContainerSecurityContext {
     ^
pkg/kubelet/kuberuntime/security_context.go:126:6: func `convertToRuntimeCapabilities` is unused (unused)
func convertToRuntimeCapabilities(opts *v1.Capabilities) *runtimeapi.Capability {
     ^
pkg/kubelet/nodeshutdown/storage.go:56:6: func `timestamp` is unused (unused)
func timestamp(t time.Time) float64 {
     ^
pkg/kubelet/nodeshutdown/storage.go:28:6: type `storage` is unused (unused)
type storage interface {
     ^
pkg/kubelet/kubelet_volumes_test.go:576:6: type `stubBlockVolume` is unused (unused)
type stubBlockVolume struct {
     ^
pkg/kubelet/kubelet_volumes_test.go:560:22: func `(*stubVolume).GetPath` is unused (unused)
func (f *stubVolume) GetPath() string {
                     ^
pkg/kubelet/kubelet_volumes_test.go:568:22: func `(*stubVolume).SetUp` is unused (unused)
func (f *stubVolume) SetUp(mounterArgs volume.MounterArgs) error {
                     ^
pkg/kubelet/kubelet_volumes_test.go:581:27: func `(*stubBlockVolume).GetGlobalMapPath` is unused (unused)
func (f *stubBlockVolume) GetGlobalMapPath(spec *volume.Spec) (string, error) {
                          ^
pkg/kubelet/kubelet_volumes_test.go:601:27: func `(*stubBlockVolume).UnmapPodDevice` is unused (unused)
func (f *stubBlockVolume) UnmapPodDevice() error {
                          ^
pkg/kubelet/kubelet_volumes_test.go:597:27: func `(*stubBlockVolume).TearDownDevice` is unused (unused)
func (f *stubBlockVolume) TearDownDevice(mapPath string, devicePath string) error {
                          ^
pkg/kubelet/kubelet_volumes_test.go:593:26: func `stubBlockVolume.MapPodDevice` is unused (unused)
func (f stubBlockVolume) MapPodDevice() error {
                         ^
pkg/kubelet/kubelet_volumes_test.go:605:27: func `(*stubBlockVolume).SupportsMetrics` is unused (unused)
func (f *stubBlockVolume) SupportsMetrics() bool {
                          ^
pkg/kubelet/kubelet_volumes_test.go:589:27: func `(*stubBlockVolume).SetUpDevice` is unused (unused)
func (f *stubBlockVolume) SetUpDevice() (string, error) {
                          ^
pkg/kubelet/kubelet_volumes_test.go:555:6: type `stubVolume` is unused (unused)
type stubVolume struct {
     ^
pkg/kubelet/kubelet_volumes_test.go:609:27: func `(*stubBlockVolume).GetMetrics` is unused (unused)
func (f *stubBlockVolume) GetMetrics() (*volume.Metrics, error) {
                          ^
pkg/kubelet/kubelet_volumes_test.go:585:27: func `(*stubBlockVolume).GetPodDeviceMapPath` is unused (unused)
func (f *stubBlockVolume) GetPodDeviceMapPath() (string, string) {
                          ^
pkg/kubelet/kubelet_volumes_test.go:572:22: func `(*stubVolume).SetUpAt` is unused (unused)
func (f *stubVolume) SetUpAt(dir string, mounterArgs volume.MounterArgs) error {
                     ^
pkg/kubelet/kubelet_volumes_test.go:564:22: func `(*stubVolume).GetAttributes` is unused (unused)
func (f *stubVolume) GetAttributes() volume.Attributes {
                     ^
test/e2e_node/image_list.go:230:6: func `getSampleDevicePluginImage` is unused (unused)
func getSampleDevicePluginImage() (string, error) {
     ^
test/e2e_node/image_list.go:268:6: func `getKubeVirtDevicePluginImage` is unused (unused)
func getKubeVirtDevicePluginImage() (string, error) {
     ^
test/e2e_node/image_list.go:102:6: func `getNodeProblemDetectorImage` is unused (unused)
func getNodeProblemDetectorImage() string {
     ^
test/e2e_node/util.go:68:5: var `stopServices` is unused (unused)
var stopServices = flag.Bool("stop-services", true, "If true, stop local node services after running tests")
    ^
test/e2e_node/image_list.go:216:6: func `getGPUDevicePluginImage` is unused (unused)
func getGPUDevicePluginImage() (string, error) {
     ^
test/e2e_node/image_list.go:75:6: func `updateImageAllowList` is unused (unused)
func updateImageAllowList() {
     ^
test/e2e_node/image_list.go:248:6: func `getSRIOVDevicePluginImage` is unused (unused)
func getSRIOVDevicePluginImage() (string, error) {
     ^
test/e2e_node/util.go:290:6: func `runCommand` is unused (unused)
func runCommand(cmd ...string) (string, error) {
     ^
test/e2e_node/util.go:67:5: var `startServices` is unused (unused)
var startServices = flag.Bool("start-services", true, "If true, start local node services")
    ^
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/api
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/cli-runtime
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/cloud-provider
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/cluster-bootstrap
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/code-generator
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/component-base
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/component-helpers
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/controller-manager
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/cri-api
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/csi-translation-lib
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/kube-aggregator
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/kube-controller-manager
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/kube-proxy
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/kube-scheduler
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/kubectl
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/kubelet
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/legacy-cloud-providers
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/metrics
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/mount-utils
staging/src/k8s.io/mount-utils/mount_unsupported.go:97:36: func `(*SafeFormatAndMount).diskLooksUnformatted` is unused (unused)
func (mounter *SafeFormatAndMount) diskLooksUnformatted(disk string) (bool, error) {
                                   ^
staging/src/k8s.io/mount-utils/mount_helper_unix.go:175:6: func `isMountPointMatch` is unused (unused)
func isMountPointMatch(mp MountPoint, dir string) bool {
     ^
staging/src/k8s.io/mount-utils/mount.go:33:2: const `defaultMountCommand` is unused (unused)
	defaultMountCommand = "mount"
	^
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/pod-security-admission
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/sample-apiserver
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/sample-cli-plugin
running golangci-lint for /Users/dims/go/src/k8s.io/kubernetes/staging/src/k8s.io/sample-controller

Please review the above warnings. You can test via "./hack/verify-golangci-lint.sh"
If the above warnings do not make sense, you can exempt this warning with a comment
 (if your reviewer is okay with it).
In general please prefer to fix the error, we have already disabled specific lints
 that the project chooses to ignore.
See: https://golangci-lint.run/usage/false-positives/
```

### PR DESCRIPTION
**Pull request by Abirdcfly**
Signed-off-by: Abirdcfly <fp544037857@gmail.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
1. https://github.com/golangci/golangci-lint/pull/3037 support go 1.19 and golangci-lint `v1.48.0` was the first Git tag to include this pull request.So update go.mod by `hack/update-vendor.sh`
2. go version in golangci-lint config file is not needed:
	1. `linters-settings.staticcheck.go` is deprecated and should use the global `run.go` instead. [source doc](https://golangci-lint.run/usage/linters/#staticcheck)
	2.  `run.go`is default use Go version from the go.mod file. [source doc](https://golangci-lint.run/usage/configuration/#run-configuration)

#### Which issue(s) this PR fixes:

Fixes #111734

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
this will need to wait until 1.25 ships. let's revisit after that please.

**Comment by aojea** [comment]
> this will need to wait until 1.25 ships. let's revisit after that please.

I see

/lgtm cancel

**Comment by dims** [comment]
/approve
/lgtm

NOTE: this can merge when we re-open master branch for next kubernetes version (1.26)

**Comment by dims** [comment]
/assign @liggitt 

(for root OWNERS approval)

**Pull request merged**
