### PR TITLE
Remove the claim that "Deleting a Job will cleanup the pods it created"

### PR DESCRIPTION
**Pull request by davidopp**
as it apparently isn't true.

ref/ #16255

@mikedanese @erictune

### CODE REVIEW

**Comment by mikedanese** [comment]
It looks like we try to https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/stop.go#L241

**Comment by bgrant0607** [comment]
Yeah, not yet.

Please cherrypick.

LGTM

**Comment by davidopp** [comment]
> It looks like we try to https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/stop.go#L241

I agree with @mikedanese 

If I'm reading the code correctly, the line he mentioned calls
JobScaler.Scale() which calls
ScaleCondition() which calls
JobScaler.ScaleSimple() which calls
Update() here https://github.com/kubernetes/kubernetes/blob/0e0ae670ad8b4f95f599799580f76c6b56a8eb95/pkg/kubectl/scale.go#L216

And it seems that JobController tries to do the right thing when there is update of job.Spec.Parallelism (in this case update to 0), in particular
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/controller.go#L100
and
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/controller.go#L374

So it might be worth investigating why this isn't working, before we just document that it doesn't work.

Unless there's something I'm missing, which is quite possible.

**Comment by bgrant0607** [comment]
Needs to clarify whether talking about via the API or via kubectl.

**Comment by soltysh** [comment]
When #16494 lands, this won't be necessary anymore.

**Pull request closed without merging**
