### PR TITLE
Fix labelname in nodelocaldns yaml

### PR DESCRIPTION
**Pull request by prameshj**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
 /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Fix a typo in the yaml
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm
/approve

**Review by jankovad1998-sudo — COMMENTED** [review]
Gg

**Pull request merged**
