### PR TITLE
MINION->NODE shell/docs variables replacement for #1111

### PR DESCRIPTION
**Pull request by 13rac1**
Mass rename of all instances of `MINION` to `NODE` for #1111. This covers shell variables and documentation. It does not cover comments or other details, because the change is large enough already.

There are 48 variables containing the characters `MINION`.

```
$ grep -oh "[A-Z_]*MINION[A-Z_]*" * -R | sort | uniq | wc
     48      48     851
```

I don't know if it's reasonable to break this commit into multiple PRs, since all 143 instances of `NUM_MINIONS` and 62 instances `MINION_NAMES` should (must?) all change at the same time. I can break into multiple commits if needed.

Let me know if you have any thoughts about a different way to approach.

_This was pulled out of #17024 to simplify that PR._

### CODE REVIEW

**Comment by thockin** [comment]
Needs rebase

**Comment by thockin** [comment]
At a glance this seems ok, but it is terrifying.

How hard would it be to break this into a series of commits:

* MINION_SIZE
* NUM_MINIONS
* MINION_DISK_TYPE
* MINION_DISK_SIZE
etc

Each commit would be MUCH more easily reviewed...

If you tell me to go to heck, I'll accept that, but XXL PRs get bottom prio :)

**Comment by eosrei** [comment]
Bah! Rebase already! I'd really like to get all instances of "minion" changed, it was really quite confusing while learning the system. I'm hoping to get #1111 fixed.

This is *only* XL! :grin: 

I was thinking today that I could break it into multiple commits. How many do you want? There are 48 separate variables, so 48 commits *is* unreasonable. But some smaller number is totally possible. Here is the list of these variables by occurrence:
```
 $ grep -oh "[A-Z_]*MINION[A-Z_]*" * -R | sort | uniq -c
      4 ENABLE_MINION_PUBLIC_IP
      6 IAM_PROFILE_MINION
      3 KUBE_ENABLE_MINION_PUBLIC_IP
      9 KUBE_GCE_MINION_IMAGE
      9 KUBE_GCE_MINION_PROJECT
      4 KUBEMARK_NUM_MINIONS
     11 KUBE_MINION_IMAGE
      1 KUBE_MINION_IP_ADDRESS
     32 KUBE_MINION_IP_ADDRESSES
      3 KUBERNETES_MINION_MEMORY
      2 MINION_ADDRESS
      2 MINION_BLOCK_DEVICE_MAPPINGS
      2 MINION_CONTAINER_ADDRS
      4 MINION_CONTAINER_NETMASKS
      6 MINION_CONTAINER_SUBNET_BASE
      5 MINION_CONTAINER_SUBNETS
      3 MINION_CPU
      9 MINION_DISK_SIZE
      3 MINION_DISK_TYPE
      2 MINION_HOSTNAME
      1 MINION_ID
      6 MINION_IDS
      3 MINION_IMAGE
      3 MINION_IMAGE_PROJECT
      4 MINION_IP
      5 MINION_IP_BASE
      2 MINION_IP_RANGE
      4 MINION_IP_RANGES
     13 MINION_IPS
      3 MINION_MEMORY_MB
      3 MINION_NAME
     62 MINION_NAMES
      4 MINION_PORT
      5 MINION_ROOT_DISK_SIZE
      5 MINION_ROOT_DISK_TYPE
      7 MINIONS
      1 MINIONS_ARRAY
     18 MINION_SCOPES
     15 MINION_SG_ID
      5 MINION_SG_NAME
     32 MINION_SIZE
     29 MINION_TAG
    143 NUM_MINIONS
      3 NUM_MINIONS_BKP
      6 NUM_MINIONS_PARALLEL
      3 OLD_MINION_TAG
      7 PREEMPTIBLE_MINION
      3 VAGRANT_MINION_NAMES
```

Anything with over ten occurrences? Would result in 9 commits + everything else in one commit. Note: This would not include MINION_DISK_TYPE/SIZE.

**Comment by thockin** [comment]
I could live with 10+

I thought maybe this could be scripted away - for each token, global sed,
git commit.

**Comment by eosrei** [comment]
I edited my reply, but you replied to the email so didn't see it. Should have written another comment. The edit said:
> Or.. haha. I suppose I can script into 48 commits.

Do you want 48? Or ~10? Pick a number of commits and I'll make it happen.

**Comment by thockin** [comment]
10 seems like a good balance

**Comment by eosrei** [comment]
I didn't realize how difficult breaking this apart into 10 would be. There's no easy way to change, for example, NUM_MINIONS without first changing NUM_MINIONS_BKP, unless I get overly complex with the regex or do it manually. I scripted the process, but had to carefully manage the name input order, then rebased everything into 14 reasonably sized commits. 

If you care here is a copy of the non-rebased commits: https://github.com/kubernetes/kubernetes/compare/master...eosrei:VAR-rename-many

**Comment by eosrei** [comment]
Oh and thanks for reviewing this extremely boring PR. Haha

**Comment by thockin** [comment]
LGTM

**Comment by eosrei** [comment]
Thanks! Is there anything I can do about the Jenkins unit/integration test failure? I cannot view the results.

**Comment by eosrei** [comment]
PR needed rebase. The following files were updated:

* hack/conformance-test.sh
* hack/jenkins/e2e.sh

**Comment by thockin** [comment]
@k8s-bot unit test this please

**Comment by eosrei** [comment]
PR needed rebase. #17428 changed the following files:

* cluster/gce/config-default.sh
* cluster/gce/config-test.sh

Changed commit diff: https://github.com/kubernetes/kubernetes/commit/3a5d2509addf393eda48ef45618903e051cd9b75#diff-57380bb03c3598646d5a3cb66518fa0b

Needs `lgtm` and `ok-to-merge` please.

**Comment by eosrei** [comment]
Mesophere tests failure is due to a full disk:
```
rsync: write failed on "/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/bin/linux/amd64/kubelet": No space left on device (28)
```

**Comment by eosrei** [comment]
Rebased again. #17758 reverted a change in `cluster/gce/config-test.sh`.
Changed commit diff: https://github.com/kubernetes/kubernetes/commit/83ed2fa22e80b9cc66c5bc18b64bddbaa54cfe5e#diff-e6e5eefc330d75c8ef2e218de62c5fdf

Needs lgtm again.

**Comment by eosrei** [comment]
@thockin Please apply the `lgtm` label again so I don't need to keep rebasing this.

**Comment by eosrei** [comment]
@jbeda @bgrant0607 This PR is related to # 1111, I've rebased three times due to conflicts since the first `lgtm`. It's mergable right now, but missing `lgtm`. Can you help? Thank you.

**Comment by jbeda** [comment]
Thanks for the continual rebasing.  Must be a total pain on a PR this big.  LGTM applied.

**Comment by eosrei** [comment]
It's merged! Finally! :D Thank you so much.

**Pull request merged**
