### PR TITLE
Refactor kubectl stdin test

### LINKED ISSUE #73099: The test "Simple pod should support inline execution and attach" is inherently racy.
The test case "executing a command with run and attach without stdin" is inherently racy.

The test runs`kubectl run run-test --image=docker.io/library/busybox:1.29 --restart=OnFailure --attach=true --stdin -- sh -c cat && echo 'stdin closed'`, and expected to see `stdin closed` in the output.

The case when the test passes:
* case 1:
  * Kubernetes creates and starts the container without stdin;
  * The container exits before attach runs;
  * kubectl falls back to get container log, which contains `stdin closed`. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/run/run.go#L527
* case 2:
  * Kubernetes creates and starts the container without stdin;
  * kubectl attach before "stdin closed" is printed;
  * kubectl attach contains `stdin closed`.

The case when the test fails:
  * Kubernetes creates and starts the container without stdin;
  * The container prints "stdin closed", but hasn't exited yet;
  * kubectl attach contains nothing.

One example failure: https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-containerd-e2e-ubuntu-gce/7057

Related issue: https://github.com/kubernetes/kubernetes/issues/24070

Can we modify this test not to check the output? Or use `kubectl log` to check output instead?

/cc @kubernetes/sig-node-bugs @kubernetes/sig-cli-bugs

### PR DESCRIPTION
**Pull request by aledbf**
**What type of PR is this?**

/kind failing-test
/kind flake

**What this PR does / why we need it**:

Use `kubectl log` to check output instead of the output from `kubectl run`

**Which issue(s) this PR fixes**:

Fixes #73099

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
/milestone v1.19

**Comment by aledbf** [comment]
/retest

(the kind failures are not related to the change in the PR)

**Comment by BenTheElder** [comment]
I guess that means we no longer test attach in this sub-case? (IIRC log is a different call) cc @liggitt 

Super happy to see an approach to fixing this, was just trying to come up with a reasonable option...

**Comment by hasheddan** [comment]
@janetkuo @soltysh could I get one of you to take a look here? :)

**Comment by liggitt** [comment]
this is not release blocking, if we get a fix we want to cherry-pick, we can do that

**Comment by soltysh** [comment]
> I guess that means we no longer test attach in this sub-case? (IIRC log is a different call) cc @liggitt

No, we're still attaching b/c that's how we inject data into stdin, the only change here is how we verify the output from that container.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
Thanks @aledbf

**Pull request merged**
