### PR TITLE
Fix selector output when get/describe replicasets

### PR DESCRIPTION
**Pull request by janetkuo**
https://github.com/kubernetes/kubernetes/pull/20886#discussion-diff-52506673

``` console
# BEFORE:
$ kubectl get rs 
CONTROLLER               CONTAINER(S)   IMAGE(S)   SELECTOR   REPLICAS   AGE
nginx-deployment-awla1   nginx          nginx      <error>    3          59s

# AFTER:
$ kubectl get rs 
CONTROLLER               CONTAINER(S)   IMAGE(S)   SELECTOR                                           REPLICAS   AGE
nginx-deployment-ydomw   nginx          nginx      name in (nginx),pod-template-hash in (811039852)   3          3s
```

@kubernetes/kubectl @mqliang

### CODE REVIEW

**Comment by bgrant0607** [comment]
cc @AdoHe

**Comment by bgrant0607** [comment]
LGTM

**Comment by ghodss** [comment]
Didn't we want to pull containers, images and selectors into -o wide? As per #19775.

**Comment by mqliang** [comment]
Sorry for my missing.

**Comment by janetkuo** [comment]
> Didn't we want to pull containers, images and selectors into -o wide? As per #19775.

@ghodss PR #20557 for this isn't merged yet. cc @AdoHe on printing replicasets.

**Comment by janetkuo** [comment]
@k8s-bot e2e test this issue: #18281

**Pull request merged**
