### PR TITLE
Small fix in salt manifest for kube-apiserver for request-timeout flag

### PR DESCRIPTION
**Pull request by jpbetz**
**What this PR does / why we need it**:

Fixes a minor bug in salt manifest (typo from #51480)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes
**Special notes for your reviewer**:

**Release note**:

xref: #51355

### CODE REVIEW

**Comment by jpbetz** [comment]
cc @mml @enisoc

**Comment by mml** [comment]
/assign mikedanese
@mikedanese can you approve this 1-character correction plz?

**Pull request merged**
