### PR TITLE
Automated cherry pick of #66581 upstream release 1.11

### PR DESCRIPTION
**Pull request by janetkuo**
Automated cherry pick of #66581 upstream release 1.11

**Release note**:

```release-note
extensions/v1beta1.Deployment .spec.progressDeadlineSeconds should be defaulted to "no deadline" instead of 600. 
```

### CODE REVIEW

**Comment by janetkuo** [comment]
/assign @smarterclayton 
since you've reviewed & approved #66581

**Comment by redbaron** [comment]
@janetkuo , @smarterclayton , @foxish , can this be approved please? 

How come cherry picks hang so long?  Just look at this list: https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+is%3Aopen+%22Automated+cherry+pick+of%22+sort%3Acreated-asc , all of them has already be discussed ,tested and merged into and all what needed is a final glance at them

**Pull request merged**
