### PR TITLE
remove the use of ServerAPIVersions

### PR DESCRIPTION
**Pull request by caesarxuchao**
With this PR and #15796 and #15808, we removed all the use of ServerAPIVersions(). We can remove that function after these are merged.

assign to @JanetKuo as she reviewed the other two PRs
cc @lavalamp

### CODE REVIEW

**Comment by wojtek-t** [comment]
Generated docs are out of date. Please run hack/update-generated-docs.sh
!!! Error in hack/verify-generated-docs.sh:28

@caesarxuchao  Can you please fix that?

**Comment by caesarxuchao** [comment]
Thank you.

I just found this PR needs my other PR #15973. I'll take care.

**Comment by wojtek-t** [comment]
@caesarxuchao - can you please rebase?

**Comment by caesarxuchao** [comment]
Thanks for the reminder. I totally forgot this PR... #18551 covers the changes in this PR, so I'll close it.

**Pull request closed without merging**
