### PR TITLE
Set Accelerators=false by default

### PR DESCRIPTION
**Pull request by feiskyer**
`hack/local-up-cluster.sh` sets FEATURE_GATES to `AllAlpha=true` by default, which also sets `Accelerators=true`. But Accelerators feature is only working for docker runtime, so it's better to disable it by default for easily configuring runtimes via CRI (e.g. cri-o and frakti).

**Release note**:

```release-note
NONE
```

cc/ @vishh @yujuhong

### CODE REVIEW

**Comment by feiskyer** [comment]
@k8s-bot gci gke e2e test this
@k8s-bot cvm gke e2e test this
@k8s-bot gci gce e2e test this

**Comment by yujuhong** [comment]
@vishh could you add a check in kubelet to only start the gpu manager if --container-runtime=docker?

**Comment by vishh** [comment]
Yeah. That's a bug I introduced unknowingly. It was only meant for testing.

**Comment by vishh** [comment]
Ok https://github.com/kubernetes/kubernetes/pull/42500 should fix this. Apologies for the issue in the first place.

**Comment by feiskyer** [comment]
Closing in favor of  #42500.

**Pull request closed without merging**
