### PR TITLE
[1.16] kubelet: block non-forwarded packets from crossing the localhost boundary

### PR DESCRIPTION
**Pull request by joelsmith**
Cherry pick of #91569 on release-1.16.

#91569: kubelet: block non-forwarded packets from crossing the

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
NONE
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by markjacksonfishing — APPROVED** [review]
/lgtm

**Pull request merged**
