### PR TITLE
regenerate openapi with 1.24 removed alpha CSIStorageCapacity API

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

There is one alpha API targeting automatic removal in 1.24. When the beta.0 tag was created, that kicked in automatically and is failing master validation of the generated openapi spec.

```release-note
NONE
```

/milestone v1.24
/priority critical-urgent
/cc @deads2k

### CODE REVIEW

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by pohly** [comment]
> When the beta.0 tag was created, that kicked in automatically and is failing master validation of the generated openapi spec.

Sounds like a chicken-and-egg problem with the automatism? Would it have been possible to avoid this by removing the alpha API manually beforehand?

**Comment by liggitt** [comment]
> Would it have been possible to avoid this by removing the alpha API manually beforehand?

yes

**Comment by liggitt** [comment]
got picked up and merged in https://github.com/kubernetes/kubernetes/pull/109151

**Pull request closed without merging**
