### PR TITLE
Update Calico CoreOS doc to use CNI plugin, conformance.

### PR DESCRIPTION
**Pull request by caseydavenport**
Updated getting started guide to use the Calico CNI plugin.

I've attached conformance test results from the `release-1.1` branch.

### CODE REVIEW

**Comment by caseydavenport** [comment]
@brendandburns - updated the PR after fixing a few hack/update-generated-docs.sh issues.

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

Tests have been pending for 24 hours

**Comment by brendandburns** [comment]
@k8s-bot unit test this please issue: #IGNORE 

something is hung up in Jenkins

**Comment by wojtek-t** [comment]
@caseydavenport 

FAIL: changes needed but not made due to --verify
/workspace/kubernetes/docs/ is out of date. Please run hack/update-generated-docs.sh

Can you please fix it?

**Comment by caseydavenport** [comment]
@wojtek-t sorry - should be fixed now.

**Pull request merged**
