### PR TITLE
Automated cherry pick of #55512

### PR DESCRIPTION
**Pull request by dashpole**
Cherry pick of #55512 on release-1.8.

#55512: allow configuring of the docker storage driver on gce

### CODE REVIEW

**Comment by mikedanese** [comment]
Just a sec.
/hold

**Comment by yujuhong** [comment]
@mikedanese why holding the PR?

**Comment by dashpole** [comment]
@yujuhong https://github.com/kubernetes/kubernetes/pull/55512#pullrequestreview-76620974

**Comment by jpbetz** [comment]
Please re-add `cherrypick-candidate` if/when hold is removed.

**Pull request closed without merging**
