### PR TITLE
cherry pick pr #111557 to 1.24 :update smd to 4.2.3

### PR DESCRIPTION
**Pull request by aojea**
/kind bug
/sig api-machinery

Includes dependency bump from #111557 and test from https://github.com/kubernetes/kubernetes/pull/111912

```release-note
Fix performance issue when creating large objects using SSA with fully unspecified schemas (preserveUnknownFields).
```

### CODE REVIEW

**Comment by liggitt** [comment]
/approve
for dependency update

/hold for @apelisse lgtm / review / confirmation this patch release is safe for previous release branches

**Comment by apelisse** [comment]
That actually backports another bug fix that is totally fine, thanks!
/unhold

**Comment by aojea** [comment]
ping @kubernetes/release-managers

**Comment by aojea** [comment]
@apelisse it needs lgtm label

**Comment by aojea** [comment]
ping @kubernetes/release-managers

**Comment by saschagrunert** [comment]
Ref: https://github.com/kubernetes/kubernetes/pull/111914#issuecomment-1306799346

**Comment by aojea** [comment]
> New changes are detected. LGTM label has been removed.

ping @kubernetes/release-managers the lgtm was removed during the rebase

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by aojea** [comment]
@liggitt this keeps slipping releases :/

**Comment by liggitt** [comment]
/lgtm
/approve

can you reach out to the release managers in slack to make sure this is on their radar for January releases?

**Pull request merged**
