### PR TITLE
Add StatefuleSet case  to scaleExample

### PR DESCRIPTION
**Pull request by riverzhang**
Add StatefuleSet to scaleExample.
When I use the scale function to help, you can view all the resources can scale, including not shown here statefulset.

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by riverzhang** [comment]
@lavalamp,   Cloud you please review my code If you have time.

**Review by kow3ns — APPROVED** [review]

**Pull request closed without merging**
