### PR TITLE
Update kuberuntime_manager_test.go

### PR DESCRIPTION
**Pull request by runzhliu**
Typo fix.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pigletfly — APPROVED** [review]
/lgtm

**Comment by derekwaynecarr** [comment]
Thank you for the fix.

/lgtm
/approve

**Pull request merged**
