### PR TITLE
remove unused e2e jenkins jobs

### LINKED ISSUE #62754: Clean up stale node e2e jenkins configs
(make an issue to remind myself)
cc @mindprince

### PR DESCRIPTION
**Pull request by paulangton**
**What this PR does / why we need it**:
Removes unused e2e jenkins jobs which have since been migrated to Prow.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #62754

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/kind cleanup

### CODE REVIEW

**Comment by krzyzacy** [comment]
/assign @yujuhong @Random-Liu 

I think those scripts are not being used anymore. I'm not sure about the gpu & nvidia installer stuff, please double check.

**Comment by Random-Liu** [comment]
Please search `test/e2e_node/jenkins/` in test-infra, there are still things in used I think.

**Comment by yujuhong** [comment]
The yaml configurations are still in use by the jobs in test-infra. They can use some cleanup though...

**Comment by krzyzacy** [comment]
🙃 @paulangton you want to move those to test-infra/jobs/e2e_node, and fix the reference paths..

pull-node-e2e is magically still passing?

**Pull request closed without merging**
