### PR TITLE
fall back to go build when static cgo not possible

### PR DESCRIPTION
**Pull request by eparis**
Instead of just failing, use go build if people don't have the magic cgo
stuff we need build-able/write-able.

### CODE REVIEW

**Comment by thockin** [comment]
LGTM, good compromise.

**Comment by ArtfulCoder** [comment]
Where is "use_go_build"used ? I didn't see where the fallback occurs. Did I miss something or is there a file missing in the PR ?
Are there other changes done to make dynamically linked binaries run in a pod ?

**Comment by derekwaynecarr** [comment]
+1 to idea but not following how it's used

**Comment by eparis** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/lib/golang.sh#L286

**Comment by eparis** [comment]
I didn't say anything about dynamically linked binaries. I'm just working around the stupidness of go install...

**Comment by eparis** [comment]
```
$ ldd _output/local/bin/linux/amd64/kube-apiserver 
	not a dynamic executable
```

**Comment by eparis** [comment]
Is this more obvious?

**Comment by ArtfulCoder** [comment]
LGTM

**Pull request merged**
