### PR TITLE
WIP: client-go per API call stack-trace via user-agent for #APIsnoop

### PR DESCRIPTION
**Pull request by hh**
In our search for meaningful API usage information, we need to identify the source code location of client side requests (specifically e2e tests) as they make K8s API calls.

[APISnoop's](http://github.com/cncf/apisnoop) current method requires this information to be available via the audit-logging mechanism.

User-agent will be available in 1.13 via audit-logging -> https://github.com/kubernetes/kubernetes/pull/64812

This is related to Add user-agent to audit-logging -> #64791 but delves a bit deeper in providing a stacktrace for any program that uses k8s.io/client-go when env `KUBE_USERAGENT_STACKTRACE=true`

Release Note:
```release-note
Support KUBE_USERAGENT_STACKTRACE
```

This may be an extremely verbose user-agent, but the information it provides will enable accurate correlation between API requests and their precise origin (down to a function within a commit).

A simple example from kubectl after being parsed from user-agent in audit-logs:

```
get /api?timeout=32s
    k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).Do()
        _output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:805
    k8s.io/kubernetes/vendor/k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroups()
        _output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/discovery/discovery_client.go:138
    k8s.io/kubernetes/vendor/k8s.io/client-go/discovery.(*CachedDiscoveryClient).ServerGroups()
        _output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/discovery/cached_discovery.go:109
    k8s.io/kubernetes/vendor/k8s.io/client-go/discovery.ServerResources()
        _output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/discovery/discovery_client.go:230
    k8s.io/kubernetes/vendor/k8s.io/client-go/discovery.(*CachedDiscoveryClient).ServerResources()
        _output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/discovery/cached_discovery.go:94
    k8s.io/kubernetes/vendor/k8s.io/client-go/restmapper.discoveryCategoryExpander.Expand()
        _output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/restmapper/category_expansion.go:61
    k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.(*Builder).ReplaceAliases()
        _output/local/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/builder.go:563
    k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.(*Builder).ResourceTypeOrNameArgs()
        _output/local/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/builder.go:533
    k8s.io/kubernetes/pkg/kubectl/cmd/get.(*GetOptions).Run()
        _output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:311
    k8s.io/kubernetes/pkg/kubectl/cmd/get.NewCmdGet.func1()
        _output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:159
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute()
        _output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC()
        _output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846
    k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute()
        _output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794
    main.main()
        _output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:50
```

The raw audit-event with user-agent set via this patch:

```json
{
   "kind":"Event",
   "apiVersion":"audit.k8s.io/v1beta1",
   "metadata":{
      "creationTimestamp":"2018-06-19T03:15:27Z"
   },
   "level":"Metadata",
   "timestamp":"2018-06-19T03:15:27Z",
   "auditID":"1ee40a9b-3afa-42b2-80d2-e980d17e580e",
   "stage":"ResponseComplete",
   "requestURI":"/api?timeout=32s",
   "verb":"get",
   "user":{
      "username":"kubecfg",
      "groups":[
         "system:masters",
         "system:authenticated"
      ]
   },
   "sourceIPs":[
      "147.75.76.213"
   ],
   "userAgent":"kubectl/v1.12.0 (linux/amd64) kubernetes/b143093 stacktrace=[k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Request).Do():_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/request.go:805;k8s.io/kubernetes/vendor/k8s.io/client-go/discovery.(*DiscoveryClient).ServerGroups():_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/discovery/discovery_client.go:138;k8s.io/kubernetes/vendor/k8s.io/client-go/discovery.(*CachedDiscoveryClient).ServerGroups():_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/discovery/cached_discovery.go:109;k8s.io/kubernetes/vendor/k8s.io/client-go/discovery.ServerResources():_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/discovery/discovery_client.go:230;k8s.io/kubernetes/vendor/k8s.io/client-go/discovery.(*CachedDiscoveryClient).ServerResources():_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/discovery/cached_discovery.go:94;k8s.io/kubernetes/vendor/k8s.io/client-go/restmapper.discoveryCategoryExpander.Expand():_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/restmapper/category_expansion.go:61;k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.(*Builder).ReplaceAliases():_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/builder.go:563;k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource.(*Builder).ResourceTypeOrNameArgs():_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/genericclioptions/resource/builder.go:533;k8s.io/kubernetes/pkg/kubectl/cmd/get.(*GetOptions).Run():_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:311;k8s.io/kubernetes/pkg/kubectl/cmd/get.NewCmdGet.func1():_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get/get.go:159;k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute():_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760;k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC():_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846;k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute():_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794;main.main():_output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:50]",
   "responseStatus":{
      "metadata":{

      },
      "code":200
   },
   "requestReceivedTimestamp":"2018-06-19T03:15:27.250302Z",
   "stageTimestamp":"2018-06-19T03:15:27.250544Z",
   "annotations":{
      "authorization.k8s.io/decision":"allow",
      "authorization.k8s.io/reason":""
   }
}
```

/cc @AishSundar @lavalamp @kubernetes/client-go-reviewers @kubernetes/sig-api-machinery-feature-requests @kubernetes/sig-architecture-feature-requests

### CODE REVIEW

**Comment by liggitt** [comment]
This is creative, but I don't think we should do this, for a few reasons:
* it can exceed header size limits
* there isn't a hard-coded number of frames to skip that reliably lands us in "interesting" code
* given this use, I actually think we should protect the server from logging excessively long useragents in audit events now (it would likely be included with the default metadata audit info, but this demonstrates the content can be larger than the body of many api requests)
* triggering debug behavior deep in a library via an envvar is convenient, but also would expose applications built using client-go to this behavior whether they wanted it or not. 
* do we actually need this level of detail? API calls per test case seems sufficient to me

**Comment by tallclair** [comment]
alternative approach: https://github.com/cncf/apisnoop/issues/23#issuecomment-399280296

**Comment by yliaog** [comment]
i think a KEP proposal is good to get discussions, comments.

**Comment by hh** [comment]
KEP PR:  https://github.com/kubernetes/community/pull/2363

Readable Link: https://github.com/ii/k8s-community/blob/apisnoop-kep/keps/sig-architecture/0016-20180601-identifying-api-usage-patterns.md#summary

/cc @yliaog @tallclair @liggitt

**Comment by liggitt** [comment]
closing this until agreement on a direction is reached in the kep

/close

**Pull request closed without merging**
