### PR TITLE
staging/publishing: add release-1.32 branch

### PR DESCRIPTION
**Pull request by dims**
Follow steps to update publishing-bot rules for release-1.32 from :
https://github.com/kubernetes/sig-release/blob/master/release-engineering/role-handbooks/branch-manager.md#update-publishing-bot-rules

```
update-rules --branch release-1.32 --rules staging/publishing/rules.yaml --o staging/publishing/rules.yaml
```

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
cc @kubernetes/release-managers @fsmunoz

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by akhilerm — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by xmudrii** [comment]
@dims @akhilerm I'm going to apply the milestone and put it on hold, when you're ready, unhold
/milestone v1.32
/hold
cc @kubernetes/release-team-leads

**Comment by dims** [comment]
/hold cancel

we are ready! let's try this.

**Pull request merged**
