### PR TITLE
Add IPv6 to command options.

### PR DESCRIPTION
**Pull request by steveperry-53**
**What this PR does / why we need it**:
This PR adds IPv6 information to the descriptions for several command options.

[Related PR in kubernetes/website](https://github.com/kubernetes/website/pull/6498)

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by steveperry-53** [comment]
@lavalamp @derekwaynecarr @jayunit100

**Comment by jayunit100** [comment]
... lgtm but needs a rebase ...  thanks for doing this ~ by the way, do we need any other IPv6 docs (i.e. calico references or whatever) in the meantime?

**Comment by steveperry-53** [comment]
@jayunit100 Thanks for the review. I don't see that this needs a rebase. I'm not sure what else we need in the way of IPv6 docs. Maybe @mmueen from [PR 6498in kubernetes/website](https://github.com/kubernetes/website/pull/6498) would be a good contact.

**Pull request merged**
