### PR TITLE
update github.com/docker/libnetwork to c8a5fca4a652

### LINKED ISSUE #87318: Incorrect IPVS table when I modify a deployment with a service unchanged
**What happened**:

I use a service kind in order to expose my application.  When I applied a change in a existing deployment, no problem, the current Pod is destroy and a new begin to start. Howewer, the old IP is not delete from IPVS table, I have two IP which are present.

**How to reproduce it (as minimally and precisely as possible)**:

````
kubectl apply -f myapp.yml
deployment.apps/myapp configured
service/myapp-api unchanged
````
````
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  [SRV_IP]:80 rr
  -> [OLD_IP]:80 Masq    1      0          0
  -> [NEW_IP]:80 Masq    1      0          0
````

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g: `cat /etc/os-release`): RHEL7
- Network plugin: Calico

Do you have the same issue?

### LINKED ISSUE #87604: Nodeport issues with ipv6-only Cluster
**What happened**:
I have an running ipv6-only cluster using IPVS.  The pod to pod and pod to service communication is working fine. But I am not able to access the pod externally using nodeport. 

 sudo kubectl get svc
NAME            TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                         AGE
elasticsearch   NodePort    fd20::91c1   <none>        9200:32140/TCP,9300:30866/TCP   15s
kubernetes      ClusterIP   fd20::1      <none>        443/TCP                         4m33s

 sudo kubectl get pods -o wide
NAME                             READY   STATUS    RESTARTS   AGE   IP           NODE    NOMINATED NODE   READINESS GATES
elasticsearch-669dc996cd-bsrcg   1/1     Running   0          19m   fd20::7043   demo1   <none>           <none>

**What you expected to happen:**

I expected to have an ipvs rule related to node port. But no entry in IPVS. 

IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  [fd20::1]:443 rr
  -> [2001:db8:0:f101::2]:6443    Masq    1      5          0
TCP  [fd20::a]:53 rr
  -> [fd20::7041]:53              Masq    1      0          0
  -> [fd20::7042]:53              Masq    1      0          0
TCP  [fd20::a]:9153 rr
  -> [fd20::7041]:9153            Masq    1      0          0
  -> [fd20::7042]:9153            Masq    1      0          0
TCP  [fd20::91c1]:9200 rr
  -> [fd20::7043]:9200            Masq    1      0          0
TCP  [fd20::91c1]:9300 rr
  -> [fd20::7043]:9300            Masq    1      0          0
UDP  [fd20::a]:53 rr
  -> [fd20::7041]:53              Masq    1      0          0
  -> [fd20::7042]:53              Masq    1      0          0

**Environment**:
- Kubernetes version (use `kubectl version`): Kubernetes v1.17.2
- Network Plugin/Version : Calico Version  -  v 3.10.2
- OS (e.g: `cat /etc/os-release`):  Ubuntu 16.04.5 LTS
- Kernel (e.g. `uname -a`): Linux demo1 4.4.0-131-generic #157-Ubuntu  x86_64 GNU/Linux
- Tools used:  kubeadm 

**How to reproduce it (as minimally and precisely as possible):**
1. install latest kubernetes (v.1.17.2) version 
2. create a pod as type nodeport.

**Anything else we need to know?**:
I could see lots of error messages in kube-proxy 

E0128 08:08:55.468535       1 proxier.go:1976] Failed to add destination: [fd20::7043]:9200, error: file exists
E0128 08:08:55.468740       1 graceful_termination.go:144] Delete rs "[fd20::91c1]:9200/TCP/253.32.0.0:9200" err: Delete destination "253.32.0.0:9200" err: no such file or directory
E0128 08:08:55.468785       1 proxier.go:2006] Failed to delete destination: [fd20::91c1]:9200/TCP/253.32.0.0:9200, error: no such file or directory
E0128 08:08:55.469064       1 proxier.go:1976] Failed to add destination: [fd20::7043]:9300, error: file exists
E0128 08:08:55.469177       1 graceful_termination.go:144] Delete rs "[fd20::91c1]:9300/TCP/253.32.0.0:9300" err: Delete destination "253.32.0.0:9300" err: no such file or directory
E0128 08:08:55.469230       1 proxier.go:2006] Failed to delete destination: [fd20::91c1]:9300/TCP/253.32.0.0:9300, error: no such file or directory
E0128 08:08:55.469531       1 proxier.go:1976] Failed to add destination: [fd20::7041]:53, error: file exists
E0128 08:08:55.469600       1 proxier.go:1976] Failed to add destination: [fd20::7042]:53, error: file exists
E0128 08:08:55.469713       1 graceful_termination.go:144] Delete rs "[fd20::a]:53/TCP/253.32.0.0:53" err: Delete destination "253.32.0.0:53" err: no such file or directory
E0128 08:08:55.469781       1 proxier.go:2006] Failed to delete destination: [fd20::a]:53/TCP/253.32.0.0:53, error: no such file or directory.

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: andrewsykim <kim.andrewsy@gmail.com>
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
docker/libnetwork had a bug where parsing IPVS destination addresses were assumed to be IPv4 addresses. For the IPVS proxier, it meant that in some cases it couldn't clean up stale IPv6 endpoints because they were being translated to IPv4 (hence they did not exist). This bug was fixed in https://github.com/docker/libnetwork/pull/2416 and https://github.com/docker/libnetwork/pull/2433.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/87318 
Fixes https://github.com/kubernetes/kubernetes/issues/87604

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix a bug in the dual-stack IPVS proxier where stale IPv6 endpoints were not being cleaned up 
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
@andrewsykim I think that this PR also fixes https://github.com/kubernetes/kubernetes/issues/87604

Can you verify and update the description if affirmative?
/cc @uablrek

**Comment by andrewsykim** [comment]
@aojea yeah seems like it's related

**Comment by uablrek** [comment]
When applying this PR on v1.18.0-alpha.2.252+89714227ffe0ec-dirty I get this crash in kube-proxy;
```
I0130 16:46:28.931309     260 shared_informer.go:212] Caches are synced for service config 
I0130 16:46:28.931323     260 shared_informer.go:212] Caches are synced for endpoints config 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x14cff1c]

goroutine 63 [running]:
k8s.io/kubernetes/pkg/proxy/ipvs.(*Proxier).syncProxyRules(0xc00000b4a0)
        /home/uablrek/go/src/k8s.io/kubernetes-orig/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go:1604 +0x636c
k8s.io/kubernetes/pkg/proxy/ipvs.(*Proxier).OnEndpointsSynced(0xc00000b4a0)
        /home/uablrek/go/src/k8s.io/kubernetes-orig/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go:894 +0x62
k8s.io/kubernetes/pkg/proxy/config.(*EndpointsConfig).Run(0xc00038ba40, 0xc0000840c0)
        /home/uablrek/go/src/k8s.io/kubernetes-orig/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:141 +0x108
created by k8s.io/kubernetes/cmd/kube-proxy/app.(*ProxyServer).Run
        /home/uablrek/go/src/k8s.io/kubernetes-orig/_output/local/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:698 +0xb78
```
I have not investigated anything so I might have made some misstake, but just FYI.

**Comment by uablrek** [comment]
On an ipv6-only cluster that is.

**Comment by andrewsykim** [comment]
@uablrek not seeing the same thing, just tested w/ IPv6 only on Kind
```
I0130 20:42:38.284242       1 server_others.go:79] IPv6 bind address (::), assume IPv6 operation
I0130 20:42:38.321040       1 node.go:135] Successfully retrieved node IP: 2001:db8:1::242:ac11:3
I0130 20:42:38.321066       1 server_others.go:210] Using ipvs Proxier.
W0130 20:42:38.321336       1 proxier.go:433] IPVS scheduler not specified, use rr by default
W0130 20:42:38.321355       1 ipset.go:107] ipset name truncated; [KUBE-6-LOAD-BALANCER-SOURCE-CIDR] -> [KUBE-6-LOAD-BALANCER-SOURCE-CID]
W0130 20:42:38.321366       1 ipset.go:107] ipset name truncated; [KUBE-6-NODE-PORT-LOCAL-SCTP-HASH] -> [KUBE-6-NODE-PORT-LOCAL-SCTP-HAS]
I0130 20:42:38.321521       1 server.go:580] Version: v1.18.0-alpha.2.265+3552dc82d788e2-dirty
I0130 20:42:38.321907       1 conntrack.go:52] Setting nf_conntrack_max to 262144
I0130 20:42:38.324510       1 config.go:133] Starting endpoints config controller
I0130 20:42:38.324710       1 shared_informer.go:205] Waiting for caches to sync for endpoints config
I0130 20:42:38.324908       1 config.go:315] Starting service config controller
I0130 20:42:38.324955       1 shared_informer.go:205] Waiting for caches to sync for service config
I0130 20:42:38.425054       1 shared_informer.go:212] Caches are synced for endpoints config 
I0130 20:42:38.425176       1 shared_informer.go:212] Caches are synced for service config 
```

Can you share how your cluster is setup?

**Comment by liggitt** [comment]
dependency update mechanics look good, will defer to network folks for review (and would be good to understand if the panic mentioned in https://github.com/kubernetes/kubernetes/pull/87695#issuecomment-580352673 is related)

**Comment by uablrek** [comment]
I get the kube-proxy crash in v1.17.2 so it is not related at all to this PR.

I will investigate the crash and maybe write a new issue. I start crio, kubelet and kube-proxy outside containers with start-scripts so I may bump into races that others do not see. I think this may be one of those. But I will investigate further.

Oh, and after the re-start kube-proxy works perfectly with this PR applied. The error printouts are gone, which verifies the function.

**Comment by aojea** [comment]
/hold cancel
per last comment
/retest

**Comment by aojea** [comment]
@andrewsykim @uablrek is this something should be backported?

**Comment by uablrek** [comment]
IMO yes, at least to 1.16 since it should support dual-stack. Earlier versions not so important IMHO

**Comment by liggitt** [comment]
If the only reason is for dual stack, I would not expect a backport just for an alpha feature.

**Comment by andrewsykim** [comment]
Haven't been able to reproduce this bug extensively but this looks like it would also affect IPv6 single stack.

**Comment by andrewsykim** [comment]
@uablrek @aojea would you happen to know? ^

**Comment by uablrek** [comment]
Yes, ipv6-only and dual-stack suffers from this bug.

But ipv6-only is also "alpha" since 1.9 I think.

**Comment by uablrek** [comment]
I can reproduce the problem on both ipv6-only and alpha. Just create a ipv6 service with endpoints and wait for the "sync" and check the kube-proxy logs.

**Comment by andrewsykim** [comment]
IPv6 single-stack is alpha but I know some users do depend on it for production.. having said that I don't think we've added IPv6-only support for the IPVS proxy until we added dual-stack support in v1.16 anyways. I think it's worth backporting only for the IPv6 single-stack case but I'll defer to @liggitt on that one.

**Comment by cblecker** [comment]
I'm -1 to backporting a vendor update for a bugfix to an alpha feature.

**Pull request merged**
