### PR TITLE
Update standard app protocols

### PR DESCRIPTION
**Pull request by dprotaso**
Add websocket support - see https://github.com/kubernetes/enhancements/pull/3996

#### What this PR does / why we need it:
Update godoc to include details from https://github.com/kubernetes/enhancements/pull/3996

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/enhancements/pull/3996

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
failure looks legit in the verify script

/assign @robscott @thockin

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
