### PR TITLE
Revert conversion reversion with fixed tests

### PR DESCRIPTION
**Pull request by smarterclayton**
@mikedanese 

Reverts reversion of #12027

### CODE REVIEW

**Comment by smarterclayton** [comment]
Shippable was a flake on 

```
--- FAIL: TestDQ_ordered_add_pop (51.63 seconds)
delay_test.go:219: task 1 had delay-priority 3s, expected 2s
FAIL
coverage: 63.2% of statements
FAIL	github.com/GoogleCloudPlatform/kubernetes/contrib/mesos/pkg/queue	62.330
```

**Comment by mikedanese** [comment]
LGTM. Will merge on green.

**Comment by smarterclayton** [comment]
Trap is green

**Comment by mikedanese** [comment]
Green means trap.

**Pull request merged**
