### PR TITLE
include discovery client in adaptor

### PR DESCRIPTION
**Pull request by pweil-**
set the discovery client if it is available

@caesarxuchao @deads2k

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm

**Comment by pweil-** [comment]
@k8s-bot unit test this again please, issue https://github.com/kubernetes/kubernetes/issues/21245

**Comment by pweil-** [comment]
@k8s-bot test this issue: #21245

**Comment by caesarxuchao** [comment]
LGTM. Thank you @pweil-.

**Comment by caesarxuchao** [comment]
Could you apply the same changes to pkg/client/clientset_generated/release_1_2/clientset_adaption.go as well? Thanks.

**Comment by pweil-** [comment]
updated

**Comment by caesarxuchao** [comment]
Thanks a bunch.

**Comment by caesarxuchao** [comment]
ok to test

**Comment by pweil-** [comment]
@k8s-bot test this issue 21463

**Pull request merged**
