### PR TITLE
Mark shorthand flags deprecated

### PR DESCRIPTION
**Pull request by feihujiang**
Ref #15471

### CODE REVIEW

**Comment by ncdc** [comment]
I've noticed that "please" is misspelled "plese" in multiple locations

**Comment by ncdc** [comment]
@kubernetes/rh-ux

**Comment by feihujiang** [comment]
@ncdc Thanks for pointing them point, I fixed.

**Comment by brendandburns** [comment]
Can you go through all of our docs and make sure that we don't reference those flags there either?

Thanks!

**Comment by feihujiang** [comment]
OK, I will check.

**Comment by feihujiang** [comment]
@brendandburns I'm so sorry, I made a mistake, and couldn't reopen this PR. I had to new a PR #16024, please review that one.

**Pull request closed without merging**
