### PR TITLE
Revert "remove versioned LabelSelector definitions"

### PR DESCRIPTION
**Pull request by gmarek**
Reverts second part of #35255, as #35622 while solving original problem, surfaced other one: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke/18644

cc @caesarxuchao @wojtek-t @smarterclayton 

I had to hand-regenerate generated files, so we need to wait for tests to pass before merging this.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35634)

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

**Comment by gmarek** [comment]
Merging to unblock the queue.

**Comment by foxish** [comment]
@gmarek Do we expect this to fix e2e-gke and e2e-gce?

**Comment by gmarek** [comment]
@test-foxish - at least e2e-gke. e2e-gce probably too.

**Comment by foxish** [comment]
Yes, the submit-queue is back to normal as of now. Thanks @gmarek :)

**Pull request merged**
