### PR TITLE
`kubectl cp` command support passing full Windows path as target

### LINKED ISSUE #77310: kubectl cp command fails passing full Windows path as target
**What happened**: Running the following command in Windows fails:
kubectl cp -n test -c [container]  [pod]:/log "d:/log"

**What you expected to happen**:
error: src doesn't exist in local filesystem

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Windows
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### LINKED ISSUE #101985: kubectl cp command fails when passing full Windows path such as c:\Temp\foobar.txt
#### What happened:
The following command fails on Windows:
`kubectl cp c:\Temp\foobar.txt "pod-name:/tmp/forbar.txt" `
reporting the following:
`error: one of src or dest must be a local file specification`

This issue was already reported https://github.com/kubernetes/kubernetes/issues/77310 and fixed, but regression was introduced in kubectl v1.20.
This command copies file successfully in if kubectl version is 1.19, but fails in 1.20 and 1.21

#### What you expected to happen:
c:\Temp\foobar.txt should be copied to the pod.
#### How to reproduce it (as minimally and precisely as possible):
On Windows:
Create c:\Temp\foobar.txt file and try to run 
`kubectl cp c:\Temp\foobar.txt "pod-name:/tmp/forbar.txt" `

I believe, kubectl treats c in c:\Temp\foobar.txt as a pod name.

#### Anything else we need to know?:
Similar issue: https://github.com/kubernetes/kubernetes/issues/77310

#### Environment:
- Kubernetes version (use `kubectl version`): v1.20 and v1.21
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): Windows 10
- Kernel (e.g. `uname -a`): N/A
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?
/kind bug
/sig windows cli

#### Which issue(s) this PR fixes:

Fixes #77310
Fixes #101985

#### Does this PR introduce a user-facing change?

```release-note
`kubectl cp` command support passing full Windows path as target
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by odinuge** [comment]
This looks like a duplicate of https://github.com/kubernetes/kubernetes/pull/78622 that was closed due to the general issues with `kubectl cp` (ref. https://github.com/kubernetes/enhancements/issues/2381).

This issue is still bothering me tho, so I would definitely get this fixed.

**Comment by wzshiming** [comment]
> This looks like a duplicate of #78622 that was closed due to the general issues with `kubectl cp` (ref. [kubernetes/enhancements#2381](https://github.com/kubernetes/enhancements/issues/2381)).
> 
> This issue is still bothering me tho, so I would definitely get this fixed.

Yes. but the direction is different, could you take a look, only under Windows and full path.

**Comment by wzshiming** [comment]
hi @deads2k could you have time to take a look

**Review by soltysh — CHANGES_REQUESTED** [review]
/hold
I'm introducing a new way of parsing paths, such that the local path is OS dependent and properly handled by golang, and the remote is always linux-base. Have a look if https://github.com/kubernetes/kubernetes/pull/94165 solves your problem.

**Pull request closed without merging**
