### PR TITLE
fix e2e test for kubectl interactive delete

### PR DESCRIPTION
**Pull request by atiratree**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

https://github.com/kubernetes/kubernetes/pull/122653 introduced a new test that has seen CI failures due to an insufficient timeouts https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/123273/pull-kubernetes-e2e-kind-ipv6/1765042688438046720

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by atiratree** [comment]
updated the code to fix verify job that failed with:

```
ERROR wrong alias for import "k8s.io/kubernetes/test/e2e/framework/deployment" should be e2edeployment in file test/e2e/kubectl/delete.go
```

**Pull request merged**
