### PR TITLE
Multiple MIGs in e2e cluster autoscaling tests.

### PR DESCRIPTION
**Pull request by jszczepkowski**
[Analytics]()

Implemented support for multiple MIGs in e2e cluster autoscaling tests.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
CC @piosz

**Comment by mwielgus** [comment]
lgtm

**Comment by jszczepkowski** [comment]
@k8s-bot test this issue: #26131

**Comment by jszczepkowski** [comment]
@k8s-bot unittest this issue: #26256

**Comment by jszczepkowski** [comment]
@k8s-bot unit test this issue: #26256

**Pull request merged**
