### PR TITLE
Fix typos in docker.go

### PR DESCRIPTION
**Pull request by xiangpengzhao**
Fix minor typos in variable name

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
The Jenkins unit/integration shows `No test results found`. Is there any way to trigger Jenkins unit/integration again? Thanks! @vishh

**Comment by vishh** [comment]
@k8s-bot test this issue #ignore

**Comment by vishh** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by xiangpengzhao** [comment]
@k8s-bot test this issue: #25024

**Comment by xiangpengzhao** [comment]
@k8s-bot test this

**Comment by xiangpengzhao** [comment]
@k8s-bot test this issue: #25791 
Thanks, dear robot :smile:

**Comment by xiangpengzhao** [comment]
After fixing `No test results found` mentioned in #25791, I'm not so sure why the Jenkins unit/integration fails now.

**Comment by vishh** [comment]
@k8s-bot test this github issue #IGNORE

**Comment by xiangpengzhao** [comment]
squashed, please check it, thanks! @vishh

**Comment by vishh** [comment]
ok to test

**Comment by lavalamp** [comment]
@vishh please remember to apply retest-not-required for changes like this, thanks.

**Comment by vishh** [comment]
@lavalamp :+1:

**Pull request merged**
