### PR TITLE
fix issue #46908

### LINKED ISSUE #46908: No validation of envFrom in pod.spec.containers
Scenario:

```
$ cat badpod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: invalid-config-env
spec:
  containers:
  - name: hello-pod
    image: docker.io/ocpqe/hello-pod:latest
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
    - name: duplicate_key
      value: FROM_ENV
    - name: expansion
      value: $(REPLACE_ME)
    envFrom:
    - configMapRef:
        name: $%^&*#
$ kubectl create -f badpod.yaml
```

Expected results:

pod would not be created as pod.spec.containers[0].envFrom.configMapRef.name is invalid

Actual results:

pod is created.

Turns out we are not doing any validation of envFrom in container spec today.

### PR DESCRIPTION
**Pull request by dixudx**
**Which issue this PR fixes** : fixes #46908

### CODE REVIEW

**Comment by eparis** [comment]
@k8s-bot ok to test
/release-note-none
lgtm but do we need any tests to make sure we don't mess this up again in the future?

**Comment by dixudx** [comment]
@eparis wait for approval

**Comment by eparis** [comment]
I'm waiting on @derekwaynecarr to review, and you to add a test to verify this is working as expected.

**Comment by xiangpengzhao** [comment]
could you please amend your commit message and PR title? people won't know what this PR does unless they search for the ref issue.

**Comment by xiangpengzhao** [comment]
dup of #46909 by @derekwaynecarr ..

**Comment by eparis** [comment]
good call. Let's close this PR and @dixudx can make and comments or suggestions in #46909

**Pull request closed without merging**
