### PR TITLE
master.go: converting API_v1beta* functions to private since they are not used outside

### PR DESCRIPTION
**Pull request by nikhiljindal**

### CODE REVIEW

**Comment by lavalamp** [comment]
@erictune Is there a reason why the auth stuff should stay public?

@smarterclayton Is there a reason why the API_x stuff should stay public?

**Comment by erictune** [comment]
no objection to the change.  wait for clayton though.

**Comment by smarterclayton** [comment]
We no longer need API_ public (our equiv of standalone.go is https://github.com/openshift/origin/blob/master/pkg/cmd/server/kubernetes/master.go).

We may need the auth stuff to remain public - David is starting on the policy stuff and we may want to prototype it first.

**Comment by smarterclayton** [comment]
We need handler container public and installswagger public.

https://github.com/openshift/origin/blob/master/pkg/cmd/server/origin/master.go

master really needs to be a factory with a default path, and the ability to reuse more code.  It's kind of a black hole in terms of its influence.  If I had to state a concrete use case, I would phrase it as "let people building on top of Kubernetes be able to reproduce the bulk of master functionality".  Ie, someone wants to provide their own plugins, or wrap the Kube api with a simple golang filter should be able to.

What's the best way to encode these things?  Tests on master?  The Kube service publish is a great example of reuse - I want to sync a running component into Kube, even though I'm not on Kube.

**Comment by nikhiljindal** [comment]
Thanks for the pointers clayton.
I do not see InstallSwaggerAPI being used in openshift.

I have updated the PR as per your comments.
Please take another look.

**Comment by smarterclayton** [comment]
LGTM

**Comment by bgrant0607** [comment]
@nikhiljindal Please rebase.

**Comment by nikhiljindal** [comment]
Rebased. Its now ready to merge!

**Pull request merged**
