### PR TITLE
Add ut coverage for auth.authorizer.abac

### PR DESCRIPTION
**Pull request by robert-cronin**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Increases Unit Test coverage for `pkg/auth/authorizer/abac/abac.go` to 96.3% by adding test cases for the following parts:
- `policyLoadError` struct
- `NewFromFile` function
- `matches` function
- `subjectMatches` function

#### Which issue(s) this PR fixes:

N/A

#### Special notes for your reviewer:

These new test cases improve the testing of edge cases and error handling in the abac auth code.

If I've missed any guidelines or made any mistakes, I welcome any feedback. Thank you in advance for your review!

#### Does this PR introduce a user-facing change?

```release-note
N/A
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
N/A
```

### CODE REVIEW

**Comment by nilekhc** [comment]
There are no plans to make any changes to ABAC package at this moment as we consider this functionality is frozen. The functionality may be completely deprecated in the future.

/close

**Comment by robert-cronin** [comment]
> There are no plans to make any changes to ABAC package at this moment as we consider this functionality is frozen. The functionality may be completely deprecated in the future.
> 
> /close  
> 
> 

Thanks for the heads up @nilekhc! I'll shift my focus elsewhere. Cheers!

**Pull request closed without merging**
