### PR TITLE
Static Consumption added to autoscaling_utils.go

### PR DESCRIPTION
**Pull request by socaa**
Part of #11570 

@piosz

### CODE REVIEW

**Comment by ixdy** [comment]
This is failing to build:
```
# k8s.io/kubernetes/test/e2e
_output/local/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:45: undefined: NewResourceConsumer
_output/local/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:52: undefined: NewResourceConsumer
_output/local/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:59: undefined: NewResourceConsumer
_output/local/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:66: undefined: NewResourceConsumer
_output/local/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:75: undefined: NewResourceConsumer
_output/local/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:84: undefined: NewResourceConsumer
_output/local/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:93: undefined: NewResourceConsumer
_output/local/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:103: undefined: NewResourceConsumer
_output/local/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:110: undefined: NewResourceConsumer
_output/local/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:117: undefined: NewResourceConsumer
_output/local/go/src/k8s.io/kubernetes/test/e2e/horizontal_pod_autoscaling.go:117: too many errors
```

**Comment by socaa** [comment]
PTAL

@piosz
@ixdy

**Comment by socaa** [comment]
PTAL

@piosz

**Comment by socaa** [comment]
PTAL

@piosz

**Comment by piosz** [comment]
LGTM. Discussed some comments offline.

**Pull request merged**
