### PR TITLE
Fix flexvolume pluginname issue

### PR DESCRIPTION
**Pull request by fredkan**
## Introduction:

Flexvolume Plugin Name should be same format as other volume plugin name. 
Current, Flexvolume Plugin Name is like "flexvolume-kubernetes.io/fakeAttacher", which has prefix "flexvolume-". The added prefix is useless and is unsuitable to the some process.

## Issues Detail:
For volumemanger:

```
"reconciler Run" calls "syncStates" process.
```

For syncStates, below 2 steps are not matched:

```
getVolumesFromPodDir: get the volumes info from local host dir;
reconstructVolume: reconstruct volume info for the untracked volumes.
```

For getVolumesFromPodDir:

```
getVolumesFromPodDir is getting the volumes info, including volume plguin name;
but volume PluginName is got from the host volume dirs: 

Example:
# ls /var/lib/kubelet/pods/a11a65c5-b11b-11e9-9f57-00163e30bccd/volumes/
alicloud~disk  kubernetes.io~secret

the volume plugin names will be used as: aliclou/disk, kubernetes.io/secret
```
The getVolumesFromPodDir function is not easy to add prefix "flexvolume-" to the flexvolume pluginName, as we don't know which dir is flexvolume idr.

For reconstructVolume:

```
reconstructVolume: will call FindPluginByName with pluginName: aliclou/disk
FindPluginByName: will build the plugin list if pluginName not searched;

In plugin list build process, below code is used:

		if plugin.GetPluginName() == name {
			matchedPluginNames = append(matchedPluginNames, plugin.GetPluginName())
			matches = append(matches, plugin)
		}

So the flexvolume plguin will be compared as: flexvolume-alicloud/disk  < -- >  alicloud/disk; Flexvolume plugin will not be built successful.
```

## Fix

We can remove the prefix string "flexvolume-"" for flexvolume pluginName, I don't find anyplace have to use the prefix.

### CODE REVIEW

**Comment by fredkan** [comment]
@jsafrane @sjenning  Please help to review this issue. 

If removing prefix "flexvolume-" has some risk, please help to point out.

**Comment by jsafrane** [comment]
/assign @gnufied 
will it change also entry names in node.status.volumeaAttached? If so, it will make cluster update almost impossible, as newly started controller-manager won't recognize the old attached volumes.

**Comment by fredkan** [comment]
> /assign @gnufied
> will it change also entry names in node.status.volumeaAttached? If so, it will make cluster update almost impossible, as newly started controller-manager won't recognize the old attached volumes.

Node Status is using the old name.

```
  volumesInUse:
  - flexvolume-alicloud/disk/d-2zehdugwfq4s4f9fgo5q
```

**Comment by gnufied** [comment]
@fredkan how is `node.Status.VolumeInUse` not changing? See - https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/util.go#L368 which will call `plugin.GetPluginName()` and it would now return different value of plugin name.

**Comment by gnufied** [comment]
Also btw - is this alibaba-cloud plugin attachable btw? If yes - it does look like this would also change, value of `node.Status.VolumesAttached` property.


Another way of fixing this bug is perhaps fixing following function:

```
func (f *flexVolume) GetPath() string {
	name := f.driverName
	return f.plugin.host.GetPodVolumeDir(f.podUID, utilstrings.EscapeQualifiedName(name), f.volName)
}
```

If we change volume path here then it would mean that when kubelet is upgraded with running pods, it won't be able to see these new volumes. But it sounds like reconstruction was broken for flexvolume plugins anyways and if they drain and upgrade the node - it will work.

**Comment by fredkan** [comment]
> Also btw - is this alibaba-cloud plugin attachable btw? If yes - it does look like this would also change, value of `node.Status.VolumesAttached` property.
> 
> Another way of fixing this bug is perhaps fixing following function:
> 
> ```
> func (f *flexVolume) GetPath() string {
> 	name := f.driverName
> 	return f.plugin.host.GetPodVolumeDir(f.podUID, utilstrings.EscapeQualifiedName(name), f.volName)
> }
> ```
> 
> If we change volume path here then it would mean that when kubelet is upgraded with running pods, it won't be able to see these new volumes. But it sounds like reconstruction was broken for flexvolume plugins anyways and if they drain and upgrade the node - it will work.

Thanks.

I do a test, and update kubelet will work well with this fix.

**Comment by fredkan** [comment]
@jsafrane @gnufied Thanks for your review.

## With Old Kubelet (using "flexvolume-***" plugin name):

In Alibaba Cloud Kubernetes platform:

1. Create alicloud/disk type pv, and create pvc to bound it.

2. Create Pod to use the pvc;

All work well;

```
# kubectl get pod
NAME                              READY   STATUS    RESTARTS   AGE
dynamic-create-5c9cc76d8c-s4fwj   1/1     Running   0          8s
# kubectl get pvc
NAME       STATUS   VOLUME                   CAPACITY   ACCESS MODES   STORAGECLASS        AGE
pvc-disk   Bound    d-2zeajm9b61u6kyk81ve0   20Gi       RWO            alicloud-disk-ssd   115s
# kubectl get pv
NAME                     CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM              STORAGECLASS        REASON   AGE
d-2zeajm9b61u6kyk81ve0   20Gi       RWO            Delete           Bound    default/pvc-disk   alicloud-disk-ssd            114s
```

Pod is running on Node: 2zecj47gcrhcpjdtaj7v, and node.status.volumesInUse is like "flexvolume-**"

```
# kubectl describe pod dynamic-create-5c9cc76d8c-s4fwj | grep Node:
Node:               cn-beijing.i-2zecj47gcrhcpjdtaj7v/192.168.0.3
# kubectl get node cn-beijing.i-2zecj47gcrhcpjdtaj7v -oyaml
  volumesInUse:
  - flexvolume-alicloud/disk/d-2zeajm9b61u6kyk81ve0
```

## Upgrade Kubelet with fix version(remove prefix "flexvolume-")

1. login node: cn-beijing.i-2zecj47gcrhcpjdtaj7v/192.168.0.3

2. replace kubelet to /usr/bin/kubelet, and restart kubelet;

3. node.status.volumesInUse is upgarded, and the frefix "flexvolume-" is removed;

```
# kubectl get node cn-beijing.i-2zecj47gcrhcpjdtaj7v -oyaml
  volumesInUse:
  - alicloud/disk/d-2zeajm9b61u6kyk81ve0
```

With kubelet upgraded, the alicloud/disk driver works well:

```
# kubectl get pod
NAME                              READY   STATUS    RESTARTS   AGE
dynamic-create-5c9cc76d8c-s4fwj   1/1     Running   0          6m
# kubectl delete pod dynamic-create-5c9cc76d8c-s4fwj
pod "dynamic-create-5c9cc76d8c-s4fwj" deleted
# kubectl get pod
NAME                              READY   STATUS    RESTARTS   AGE
dynamic-create-5c9cc76d8c-m5drs   1/1     Running   0          23s
# kubectl get pv
NAME                     CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM              STORAGECLASS        REASON   AGE
d-2zeajm9b61u6kyk81ve0   20Gi       RWO            Delete           Bound    default/pvc-disk   alicloud-disk-ssd            8m39s
# kubectl describe pv d-2zeajm9b61u6kyk81ve0
***
```

## Upgrade the cluster:

Restart controller manager can be considered same as upgrade cluster;

PV, and driver is works well;

```
# kubectl get pod
NAME                              READY   STATUS    RESTARTS   AGE
dynamic-create-5c9cc76d8c-m5drs   1/1     Running   0          2m19s
# kubectl get pvc
NAME       STATUS   VOLUME                   CAPACITY   ACCESS MODES   STORAGECLASS        AGE
pvc-disk   Bound    d-2zeajm9b61u6kyk81ve0   20Gi       RWO            alicloud-disk-ssd   10m
# kubectl get pv
NAME                     CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM              STORAGECLASS        REASON   AGE
d-2zeajm9b61u6kyk81ve0   20Gi       RWO            Delete           Bound    default/pvc-disk   alicloud-disk-ssd            10m
```

```
# kubectl delete pod dynamic-create-5c9cc76d8c-m5drs
pod "dynamic-create-5c9cc76d8c-m5drs" deleted
# kubectl get pod
NAME                              READY   STATUS    RESTARTS   AGE
dynamic-create-5c9cc76d8c-ktdwk   1/1     Running   0          6s
```

node.status.volumesInUse is also upgarded.

```
# kubectl get node cn-beijing.i-2zecj47gcrhcpjdtaj7v -oyaml
  volumesInUse:
  - alicloud/disk/d-2zeajm9b61u6kyk81ve0
```

Also, remove deployment, pvc, pv, and renew them again. Everything looks good.

**Comment by gnufied** [comment]
What about the version skew between kubelet and controller-manager? What happens if an upgraded controller-manager attaches a volume and writes with new name to - `node.Status.VolumesAttached` but an older kubelet can't find the volume?

**Pull request closed without merging**
