### PR TITLE
manual cherry-pick of 16073

### PR DESCRIPTION
**Pull request by caesarxuchao**
manual cherry-pick of #16073

cc @bgrant0607 @janetkuo

### CODE REVIEW

**Comment by caesarxuchao** [comment]
It's just doc changes. @nikhiljindal, It would be great if we can manually merge this. I have another PR depends on this one.

**Comment by nikhiljindal** [comment]
Note that this breaks all those links since there is no api-reference/v1 folder in v1.1.0.
I assume you are going to follow this up with another PR changing all these links again to release-1.1 instead of v1.1.0?

**Comment by caesarxuchao** [comment]
Yes, that PR is in the pipe!

**Comment by bgrant0607** [comment]
Better to be consistent with the code in the release branch.

**Comment by bgrant0607** [comment]
Merging.

**Pull request merged**
