### PR TITLE
[1.18] Automated cherry pick of fixes for "large leases overload event etcd" issue (96836)

### PR DESCRIPTION
**Pull request by mborsz**
Cherry pick of #97009 #97480 #98257 on release-1.18.

#97009: apiserver add --lease-reuse-duration-seconds to config lease
#97480: apiserver add metric etcd_lease_object_counts
#98257: api-server add --lease-max-object-count

All those three PRs are a fix for an issue where creating a large number of events was causing event-etcd overload (https://github.com/kubernetes/kubernetes/issues/96836).

```release-note
Fixed a bug where a high churn of events was causing master instability by reducing the maximum number of objects (events) attached to a single etcd lease.
```

### CODE REVIEW

**Comment by mborsz** [comment]
https://github.com/kubernetes/kubernetes/pull/100084 for 1.20 cherry pick
https://github.com/kubernetes/kubernetes/pull/100450 for 1.19 cherry pick

**Comment by wojtek-t** [comment]
/lgtm
/approve

@kubernetes/release-managers - for cherrypick approval

**Pull request merged**
