### PR TITLE
Make sure the volume name is not empty when the PVC is bound

### PR DESCRIPTION
**Pull request by chendave**
Current logic to check whether a PVC is fully bound are:
1. PVC's volume name is not empty
2. Annotation "pv.kubernetes.io/bind-completed" is properly set

https://github.com/kubernetes/kubernetes/blob/45ce2fae405bfc4d4f1b125a7ec7ba9b69148cb3/pkg/controller/volume/scheduling/scheduler_binder.go#L720-L722

The behavior in the test case only set the annotation, and leave the
volume name to be set by a `FakePVController`.

This will cause a problem for us to run some testcase like scheduler's perf test, scheduling pod with volume as an example, the first try will always hit "unbound immediate PersistentVolumeClaims" exception.

```
        "scheduler-perf-9k75q": *{
                code: UnschedulableAndUnresolvable (3),
                reasons: []string len: 1, cap: 1, [
                        "pod has unbound immediate PersistentVolumeClaims",
                ],
                err: error nil,},
        "scheduler-perf-dp9mg": *{
                code: UnschedulableAndUnresolvable (3),
                reasons: []string len: 1, cap: 1, [
                        "pod has unbound immediate PersistentVolumeClaims",
                ],
                err: error nil,},
		...
```

As a result, the metric data "schedule_attempts_total", or "scheduling_algorithm_duration_seconds" etc. will not accurate enough.

Signed-off-by: Dave Chen <dave.chen@arm.com>

**What type of PR is this?**

Add one of the following kinds:
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig testing
/sig scheduling

### CODE REVIEW

**Comment by chendave** [comment]
@adtac @alculquicondor  fyi as something related with schedule perf.

/cc @oomichi  pretty easy one but does an issue we need to address to make the metric data more meaningful.

**Comment by alculquicondor** [comment]
was this function only being used in perf tests and not E2E?

/lgtm

**Review by oomichi — COMMENTED** [review]
Thanks for doing this.

/approve

**Comment by chendave** [comment]
> was this function only being used in perf tests and not E2E?

I think so, I cannot find it is used anywhere outside of scheduler_perf.

**Pull request merged**
