### PR TITLE
added eventsToRegister for NodeUnschedulable plugin

### LINKED ISSUE #94009: Avoid moving pods out of unschedulable status unconditionally
Currently we unconditionally move pods out of unschedulable status when an event happens. However, we can optimize this by setting some conditions for each event to avoid unnecessarily doing that:

1) PV, PVC, StorageClass or CSINode add/update: move only pods with a PVC.
2) Service add/update: only if ServiceAffinity plugin is enabled in one of the profiles
3) Node add/update: test the pods against the [kubelet admission logic](https://github.com/kubernetes/kubernetes/blob/3b5aedcef43fa01538518ecbc7de369b27ecd191/pkg/kubelet/lifecycle/predicate.go#L224), this include: NodeAffinity, NodeName NodePorts, NodeResources and TaintsTolerations filters.
4) Pod delete: keep it as is (spreading or affinity constraints must be tested, which is expensive to do)

This is necessary to avoid wasting scheduling cycles.

Related proposal: https://docs.google.com/document/d/1Dw1qPi4eryllSv0F419sKVbGXiPvSv6N_mJd6AVSg74/edit

/sig scheduling
/assign @adtac

### PR DESCRIPTION
**Pull request by Jerry-Ge**
Signed-off-by: Jerry Ge jerry.ge@arm.com

#### What type of PR is this?

/kind feature
/sig scheduling

#### Which issue(s) this PR fixes:
Fixes #94009 

#### Special notes for your reviewer:
@Huang-Wei 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
@Jerry-Ge `Fixes XYZ` would automatically close issue XYZ, and this PR shouldn't close #94009.

And for the sake of issue tracking, could you combine this PR into #100279?

**Comment by Jerry-Ge** [comment]
> @Jerry-Ge `Fixes XYZ` would automatically close issue XYZ, and this PR shouldn't close #94009.
> 
> And for the sake of issue tracking, could you combine this PR into #100279?

Ahh! I see, thanks for the note and I will update both of the points. :D

**Comment by Jerry-Ge** [comment]
Combined the PR with #100279

**Pull request closed without merging**
