### PR TITLE
Vendor PyYAML in third_party

### PR DESCRIPTION
**Pull request by cblecker**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Vendors a copy of PyYAML. A clean install of Python won't have the yaml library.

I don't really like this, but I also don't really like that we're using python for this anyways. Would much rather go or bash.

/assign @nikhita @dims 

@guineveresaenger: This was the thing you hit. 🤦‍♂ 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
ewwww ... ugh! :( let me spend a bit of time tomorrow on this unless this is a blocker for something

**Comment by cblecker** [comment]
@dims Not a blocker. I was just telling Guin that `make verify` should run locally, and this script made a dirty liar out of me :(

**Comment by guineveresaenger** [comment]
😅 thank you for following up on this today!

**Comment by dims** [comment]
@cblecker Let's do this instead as a short-term solution, yes, we should rewrite this in `golang` in the longer term. https://github.com/kubernetes/kubernetes/pull/78518/files

**Comment by cblecker** [comment]
Closing in favour of #78518

**Pull request closed without merging**
