### PR TITLE
in docs master.md, update docker command to run flanneld correctly

### PR DESCRIPTION
**Pull request by jim3ma**
the origin command
 **sudo docker -H unix:///var/run/docker-bootstrap.sock run -d --net=host --privileged -v /dev/net:/dev/net quay.io/coreos/flannel:0.5.5 --ip-masq**
is not correct. it must be:
**sudo docker -H unix:///var/run/docker-bootstrap.sock run -d --net=host --privileged -v /dev/net:/dev/net quay.io/coreos/flannel:0.5.5 /opt/bin/flanneld --ip-masq -iface="eth0"**

### CODE REVIEW

**Comment by majinjing3** [comment]
I signed it!

**Comment by majinjing3** [comment]
ok to test

**Comment by luxas** [comment]
Half the problem is fixed here: #18894

**Comment by erictune** [comment]
lgtm but you need to rebase.

**Comment by erictune** [comment]
ok to test

**Comment by luxas** [comment]
@majinjing3 Are you going to do this? 
You have to shrink this to one commit and merge it with the `master` branch.
The `iface` problem is already fixed on `master`, but not the /opt/bin/flanneld` thing

**Comment by luxas** [comment]
It's OK @majinjing3 

@erictune  I'll pick this up in a future PR

**Comment by majinjing3** [comment]
@luxas @erictune 
**Sorry for checking notification so late.**
I have rebased this commit in my local env. And I have found some issues in master.sh and worker.sh when re-run them twice about adding paramater into DOCKER_CONF="/etc/sysconfig/docker". 
I found them because setting wrong interface for flannel firstly, then them didn't work for me.
I will review them and update tomrrow, then create a new PR.
**Thanks for you comments.**

**Pull request closed without merging**
