### PR TITLE
fix unbound variable build/lib/release.sh bash 4.3

### PR DESCRIPTION
**Pull request by adisky**
**What type of PR is this?**

 /kind bug

**What this PR does / why we need it**:
After PR https://github.com/kubernetes/kubernetes/pull/77910, unbound variable error in /hack/lib/golang.sh was resolved, I have declared only those variables globally that are referenced in /hack/lib/golang.sh , but some variables left that are not referenced in that script causing error at later stage
 _**/home/zuul/src/k8s.io/kubernetes/build/lib/release.sh: line 162: KUBE_NODE_PLATFORMS[@]: unbound variable**_
This PR declares the remaining variables also

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm

/hold

for either @cblecker or @spiffxp

**Comment by tpepper** [comment]
This has broken MacOS build:

```
/Users/tpepper/src/github.com/kubernetes/kubernetes/hack/lib/golang.sh: line 166: declare: -g: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
!!! [0517 10:55:19] Call tree:
!!! [0517 10:55:19]  1: /Users/tpepper/src/github.com/kubernetes/kubernetes/hack/lib/init.sh:55 source(...)
!!! [0517 10:55:19]  2: build/../build/common.sh:37 source(...)
!!! [0517 10:55:19]  3: build/release.sh:29 source(...)
make: *** [quick-release] Error 1
```

**Pull request merged**
