### PR TITLE
fix slice sort algorithm in freeCores/freeCPUS

### PR DESCRIPTION
**Pull request by enzoyes**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Take freeCores now for example(https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/cpumanager/cpu_assignment.go#L82): 
```go
func (a *cpuAccumulator) freeCores() []int {
...
	sort.Slice(socketIDs,
		func(i, j int) bool {
			iCores := a.details.CoresInSockets(socketIDs[i]).Filter(a.isCoreFree)
			jCores := a.details.CoresInSockets(socketIDs[j]).Filter(a.isCoreFree)
			return iCores.Size() < jCores.Size() || socketIDs[i] < socketIDs[j]
		})
...
```
Currently, when `iCores.Size() > jCores.Size() ` socketIDs will sort by result of `socketIDs[i] < socketIDs[j]`. In my opinion, it should act like below. 
```
1. iCores.Size() < jCores.Size(), return true.
2. iCores.Size() > jCores.Size(), return false.
3. iCores.Size() == jCores.Size(), try to compare if socketIDs[i] < socketIDs[j]
```
Problems the same in freeCPUs. 
The fix could make allocations more socket/core affiniate.
Testcases now is hard to get a error, so i add a test.

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
@ranchothu as this is marked as bug, what exactly the bug is? Based on the PR description, this is change of behavior. Can you please update the description to provide more details

**Comment by ranchothu** [comment]
Hi, @SergeyKanzhelev,
the new added case could be an example to clarify why i think it maybe a bug, topology like this:
```go
0:  {CoreID: 0, SocketID: 1},
1:  {CoreID: 0, SocketID: 1},
2:  {CoreID: 1, SocketID: 1},
3:  {CoreID: 1, SocketID: 1},
4:  {CoreID: 2, SocketID: 1},
5:  {CoreID: 2, SocketID: 1},
6:  {CoreID: 3, SocketID: 0},
7:  {CoreID: 3, SocketID: 0},
8:  {CoreID: 4, SocketID: 0},
9:  {CoreID: 4, SocketID: 0},
10: {CoreID: 5, SocketID: 0},
11: {CoreID: 5, SocketID: 0},
12: {CoreID: 6, SocketID: 2},
13: {CoreID: 6, SocketID: 2},
14: {CoreID: 7, SocketID: 2},
15: {CoreID: 7, SocketID: 2},
16: {CoreID: 8, SocketID: 2},
17: {CoreID: 8, SocketID: 2},
```
And if the available cpusets be `(0, 1, 2, 3, 6, 7, 8, 9, 10, 11, 12, 13)`, what should the expect `freeCPUs` sort?
Current implement gets sort `12 13 6 7 8 9 10 11 0 1 2 3`. Seems a strange result with core number in sockets not always ascending.
    available cores  in socket 0: 3 cores  (cpu 6, 7, 8, 9, 10, 11)
    available cores in socket 1: 2 cores (cpu 0,1,2,3)
    available cores in socket 2: 1 cores (cpu 12,13)
I think the sort should be `12, 13, 0, 1, 2, 3, 6, 7, 8, 9, 10, 11`,  because we should sort with core numbers in socket first.

may my description help your understand the PR.

**Comment by SergeyKanzhelev** [comment]
/triage accepted
/priority backlog

thank you for more information. I think this is enough information for reviewer to start review. Moved PR into "Needs reviewer" status

**Comment by ranchothu** [comment]
ping @klueska , PTAL

**Comment by klueska** [comment]
Hi @ranchothu, thank for your PR.

Interestingly enough, I have an other PR (which I haven't pushed yet) that makes a similar change, while also reworking / simplifying alot of the logic in the CPUManager's allocation algorithm. This PR is a precursor for supporting CPU allocations that take sub-socket NUMA nodes into account.  It also lays the groundwork for support for other policies that don't follow the existing algorithm for "packing" CPUs onto sockets / NUMA nodes, but rather distributing them across different NUMA nodes.

I have added your test case into my WIP PR and it seems to be passing (meaning my PR must address the issue you point out here as well). As such, I'm included to close this PR and just wait for my PR to be ready.  That said, if you could break this PR into two commits -- one for the change and one for the test update, I can cherry-pick your test commit into my branch to give you credit for putting it together.

**Comment by ranchothu** [comment]
@klueska , thanks for your review. I've break the PR, may the tesecase be helpful for you.

As you mentioned above, a cpu manager with sub-socket numa nodes is considered in your future work, aha:), i'm also working on something similiar(uncore cache into account), done but haven't pushed, maybe i will wait for your PR and push mine based on yours. Reference here if you're interested in(https://github.com/kubernetes/enhancements/pull/2684).

**Comment by fromanirh** [comment]
Hi, in the testcase patch you mention triple sockets. Which system do have triple sockets?

**Comment by ranchothu** [comment]
hi, @fromanirh, just an example to bring out the bug(socket number should larger than 2, maybe 3,4...).

**Comment by fromanirh** [comment]
> hi, @fromanirh, just an example to bring out the bug(socket number should larger than 2, maybe 3,4...).

Hi, thanks for clarifying! I think this is an important bit of information and should be documented in the testcase.

**Comment by ranchothu** [comment]
close. Problem have been resolved in https://github.com/kubernetes/kubernetes/pull/102014. And new testcase cherry-picked to https://github.com/kubernetes/kubernetes/pull/102014.

**Pull request closed without merging**
