### PR TITLE
Add FakeNeverRateLimitter

### PR DESCRIPTION
**Pull request by gmarek**

### CODE REVIEW

**Comment by gmarek** [comment]
@k8s-bot unit test this

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
Please fix the race:

WARNING: DATA RACE
Read by goroutine 42:
  k8s.io/kubernetes/pkg/util.TestNeverFake()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/throttle_test.go:120 +0x336
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

Previous write by goroutine 43:
  k8s.io/kubernetes/pkg/util.TestNeverFake.func1()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/throttle_test.go:109 +0x42

Goroutine 42 (running) created at:
  testing.RunTests()
      /tmp/workdir/go/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /tmp/workdir/go/src/testing/testing.go:494 +0xe4
  main.main()
      k8s.io/kubernetes/pkg/util/_test/_testmain.go:114 +0x20f

Goroutine 43 (finished) created at:
  k8s.io/kubernetes/pkg/util.TestNeverFake()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/throttle_test.go:110 +0x1d1
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

[You probably need to use atomic bool instead]

**Comment by gmarek** [comment]
Done.

**Pull request merged**
