### PR TITLE
Display healthcheck nodeport and other fields in describe service

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Some fields such as `HealthCheckNodePort` are not displayed currently. This PR fixes it.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Update: found this when tracing #49999

**Special notes for your reviewer**:
/sig cli network

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by MrHohn** [comment]
/ok-to-test

You may also want to update `describe_test.go` as well?

**Comment by xiangpengzhao** [comment]
Test case updated. PTAL. @MrHohn 
/assign @smarterclayton
for approval

Thanks!

**Comment by smarterclayton** [comment]
Looks ok to me, @kubernetes/sig-cli-pr-reviews

**Review by MrHohn — APPROVED** [review]
Thanks, this LGTM. Will wait a while for comments from CLI folks.

**Pull request merged**
