### PR TITLE
update coredns to v1.10.1

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
- [x] #116060  https://github.com/coredns/corefile-migration/releases/tag/v1.0.20 (v1.0.19 supports v1.10.1 migration)
- [x] https://github.com/coredns/coredns/releases/v1.10.1
- [x] https://github.com/kubernetes/k8s.io/pull/4736

#### Which issue(s) this PR fixes:
Fixes None

#### Does this PR introduce a user-facing change?
```release-note
upgrade coredns to v1.10.1
```

### CODE REVIEW

**Comment by dims** [comment]
@pacoxu one more place to fix the version number?

**Comment by pacoxu** [comment]
> @pacoxu one more place to fix the version number?

Thanks for reminding me. Updated.

**Comment by pacoxu** [comment]
/priority important-soon
(should be in v1.27)
/triage accepted

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Review by SataQiu — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
