### PR TITLE
remove duplicated check on validateTokenRequests for new object

### PR DESCRIPTION
**Pull request by Songjoy**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

remove duplicated check on validateTokenRequests for new object

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by carlory** [comment]
/remove-kind bug
/kind cleanup
/lgtm

Good catch! thank you. It has been checked in https://github.com/kubernetes/kubernetes/pull/122451/files#diff-570bec16d0d942e4e21b5149b9675fc3f2182c8a8aee1f8fc9cc66dafa7b4259R417

/assign @thockin

**Comment by Songjoy** [comment]
/assign jsafrane 

Can you take a look at the PR for me? Thank you.

**Review by hijodeputa133 — CHANGES_REQUESTED** [review]
Nada de fusiones

**Review by hijodeputa133 — CHANGES_REQUESTED** [review]
Ruben_Bernardez_Hernandez

**Review by hijodeputa133 — CHANGES_REQUESTED** [review]
no

**Pull request merged**
