### PR TITLE
Automated cherry pick of #57512: RBD Plugin: Pass monitors addresses in a comma-separated

### PR DESCRIPTION
**Pull request by cofyc**
Cherry pick of #57512 on release-1.9.

#57512: RBD Plugin: Pass monitors addresses in a comma-separated

### CODE REVIEW

**Comment by cofyc** [comment]
@rootfs 
I'm still running 1.9 clusters in production and would like to backport #57512 to 1.9 releases. Could you help to approve this? No conflicts in cherry-pick.

**Comment by dims** [comment]
@kubernetes/sig-storage-pr-reviews 

/ok-to-test

**Comment by cofyc** [comment]
@mbohlool Done in https://github.com/kubernetes/kubernetes/pull/57512#issuecomment-389046928. Is it ok?

**Comment by mbohlool** [comment]
please add a release note to the parent pr

**Comment by cofyc** [comment]
@mbohlool Done in https://github.com/kubernetes/kubernetes/pull/57512#issue-159652192. PR #57512 has `release-note` label now.

**Pull request merged**
