### PR TITLE
rename imported pkgs for readability

### PR DESCRIPTION
**Pull request by thockin**
Get rid of "newer" in conversions and defaults.  It doesn't make things easier to read IMO (let's argue).

Change "current" to "versioned" when possible.  It's unfortunate that I can not alias my own pkg to another name - I think it's more readable.

### CODE REVIEW

**Comment by thockin** [comment]
I could move conversions and defaults into sub-pkgs (or just 1 pkg) since they rely on init() and then alias the versioned api pkg to "versioned".  Thoughts?

**Comment by brendandburns** [comment]
Shippable is kicking errors:

```
--- FAIL: TestNoManualChangesToGenerateConversions (0.35s)
	conversion_generation_test.go:140: please update conversion functions; generated: v1beta3.functions.txt; diff: first difference: expected func convert_v1beta3_AWSElasticBlockStoreVolumeSource_To_api_AWSElasticBlockStoreVolumeSource(in *AWSElasticBlockStoreVolumeSource, out *AWSElasticBlockStoreVolumeSource, s conversion.Scope) error {
		, got func convert_v1beta3_AWSElasticBlockStoreVolumeSource_To_api_AWSElasticBlockStoreVolumeSource(in *AWSElasticBlockStoreVolumeSource, out *api.AWSElasticBlockStoreVolumeSource, s conversion.Scope) error {
	conversion_generation_test.go:140: please update conversion functions; generated: v1.functions.txt; diff: first difference: expected func convert_v1_AWSElasticBlockStoreVolumeSource_To_api_AWSElasticBlockStoreVolumeSource(in *AWSElasticBlockStoreVolumeSource, out *AWSElasticBlockStoreVolumeSource, s conversion.Scope) error {
		, got func convert_v1_AWSElasticBlockStoreVolumeSource_To_api_AWSElasticBlockStoreVolumeSource(in *AWSElasticBlockStoreVolumeSource, out *api.AWSElasticBlockStoreVolumeSource, s conversion.Scope) error {
FAIL
coverage: 70.5% of statements
```

**Comment by thockin** [comment]
Tests should be fixed now.

**Comment by brendandburns** [comment]
and now it needs a rebase...  feel free to merge on green if I don't get to it.

**Comment by thockin** [comment]
rebased

**Pull request merged**
