### PR TITLE
Continue fixing bash scripts

### PR DESCRIPTION
**Pull request by ipuustin**
**What this PR does / why we need it**:

This PR continues the work of fixing bugs in shell scripts (see https://github.com/kubernetes/kubernetes/pull/59572 for the previous PR). The fixed scripts are `hack/grab-profiles.sh` and `hack/update-codegen.sh`. Most of the issues are found by using `shellcheck`. The goal is to make the scripts work and behave as they did previously, but fix obvious bugs and make them more robust and resilient for irregular input such as file names with special characters or whitespace in them.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sbezverk** [comment]
@ipuustin  Please see this log of the failure:
```console
sbezverk@kube-4:~/developing/go/src/k8s.io/kubernetes$ hack/update-codegen.sh -v
++ dirname hack/update-codegen.sh
+ KUBE_ROOT=hack/..
+ source hack/../hack/lib/init.sh
++ set -o errexit
++ set -o nounset
++ set -o pipefail
++++ dirname hack/../hack/lib/init.sh
+++ cd hack/../hack/lib/../..
+++ pwd -P
++ KUBE_ROOT=/home/sbezverk/developing/go/src/k8s.io/kubernetes
++ KUBE_OUTPUT_SUBPATH=_output/local
++ KUBE_OUTPUT=/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local
++ KUBE_OUTPUT_BINPATH=/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local/bin
++ KUBE_RSYNC_COMPRESS=0
++ export no_proxy=127.0.0.1,localhost
++ no_proxy=127.0.0.1,localhost
++ THIS_PLATFORM_BIN=/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/bin
++ source /home/sbezverk/developing/go/src/k8s.io/kubernetes/hack/lib/util.sh
+++ [[ -z '' ]]
+++ declare -r 'color_start=\033['
+++ declare -r 'color_red=\033[0;31m'
+++ declare -r 'color_yellow=\033[0;33m'
+++ declare -r 'color_green=\033[0;32m'
+++ declare -r 'color_norm=\033[0m'
++ source /home/sbezverk/developing/go/src/k8s.io/kubernetes/hack/lib/logging.sh
+++ KUBE_VERBOSE=5
++ kube::log::install_errexit
++ trap kube::log::errexit ERR
++ set -o errtrace
++ source /home/sbezverk/developing/go/src/k8s.io/kubernetes/hack/lib/version.sh
++ source /home/sbezverk/developing/go/src/k8s.io/kubernetes/hack/lib/golang.sh
+++ readonly KUBE_GO_PACKAGE=k8s.io/kubernetes
+++ KUBE_GO_PACKAGE=k8s.io/kubernetes
+++ readonly KUBE_GOPATH=/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local/go
+++ KUBE_GOPATH=/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local/go
+++ KUBE_SERVER_TARGETS=($(kube::golang::server_targets))
++++ kube::golang::server_targets
++++ targets=(cmd/kube-proxy cmd/kube-apiserver cmd/kube-controller-manager cmd/cloud-controller-manager cmd/kubelet cmd/kubeadm cmd/hyperkube cmd/kube-scheduler vendor/k8s.io/kube-aggregator vendor/k8s.io/apiextensions-apiserver cluster/gce/gci/mounter)
++++ local targets
++++ echo cmd/kube-proxy cmd/kube-apiserver cmd/kube-controller-manager cmd/cloud-controller-manager cmd/kubelet cmd/kubeadm cmd/hyperkube cmd/kube-scheduler vendor/k8s.io/kube-aggregator vendor/k8s.io/apiextensions-apiserver cluster/gce/gci/mounter
+++ readonly KUBE_SERVER_TARGETS
+++ KUBE_SERVER_BINARIES=("${KUBE_SERVER_TARGETS[@]##*/}")
+++ readonly KUBE_SERVER_BINARIES
+++ KUBE_NODE_TARGETS=($(kube::golang::node_targets))
++++ kube::golang::node_targets
++++ targets=(cmd/kube-proxy cmd/kubeadm cmd/kubelet)
++++ local targets
++++ echo cmd/kube-proxy cmd/kubeadm cmd/kubelet
+++ readonly KUBE_NODE_TARGETS
+++ KUBE_NODE_BINARIES=("${KUBE_NODE_TARGETS[@]##*/}")
+++ readonly KUBE_NODE_BINARIES
+++ KUBE_NODE_BINARIES_WIN=("${KUBE_NODE_BINARIES[@]/%/.exe}")
+++ readonly KUBE_NODE_BINARIES_WIN
+++ [[ -n '' ]]
+++ [[ '' == \t\r\u\e ]]
+++ KUBE_SERVER_PLATFORMS=(linux/amd64 linux/arm linux/arm64 linux/s390x linux/ppc64le)
+++ readonly KUBE_SERVER_PLATFORMS
+++ KUBE_NODE_PLATFORMS=(linux/amd64 linux/arm linux/arm64 linux/s390x linux/ppc64le windows/amd64)
+++ readonly KUBE_NODE_PLATFORMS
+++ KUBE_CLIENT_PLATFORMS=(linux/amd64 linux/386 linux/arm linux/arm64 linux/s390x linux/ppc64le darwin/amd64 darwin/386 windows/amd64 windows/386)
+++ readonly KUBE_CLIENT_PLATFORMS
+++ KUBE_TEST_PLATFORMS=(linux/amd64 linux/arm linux/arm64 linux/s390x linux/ppc64le darwin/amd64 windows/amd64)
+++ readonly KUBE_TEST_PLATFORMS
+++ KUBE_CLIENT_TARGETS=(cmd/kubectl)
+++ readonly KUBE_CLIENT_TARGETS
+++ KUBE_CLIENT_BINARIES=("${KUBE_CLIENT_TARGETS[@]##*/}")
+++ readonly KUBE_CLIENT_BINARIES
+++ KUBE_CLIENT_BINARIES_WIN=("${KUBE_CLIENT_BINARIES[@]/%/.exe}")
+++ readonly KUBE_CLIENT_BINARIES_WIN
+++ KUBE_TEST_TARGETS=($(kube::golang::test_targets))
++++ kube::golang::test_targets
++++ targets=(cmd/gendocs cmd/genkubedocs cmd/genman cmd/genyaml cmd/genswaggertypedocs cmd/linkcheck vendor/github.com/onsi/ginkgo/ginkgo test/e2e/e2e.test)
++++ local targets
++++ echo cmd/gendocs cmd/genkubedocs cmd/genman cmd/genyaml cmd/genswaggertypedocs cmd/linkcheck vendor/github.com/onsi/ginkgo/ginkgo test/e2e/e2e.test
+++ readonly KUBE_TEST_TARGETS
+++ KUBE_TEST_BINARIES=("${KUBE_TEST_TARGETS[@]##*/}")
+++ readonly KUBE_TEST_BINARIES
+++ KUBE_TEST_BINARIES_WIN=("${KUBE_TEST_BINARIES[@]/%/.exe}")
+++ readonly KUBE_TEST_BINARIES_WIN
+++ KUBE_TEST_PORTABLE=(test/e2e/testing-manifests test/kubemark hack/e2e.go hack/e2e-internal hack/get-build.sh hack/ginkgo-e2e.sh hack/lib)
+++ readonly KUBE_TEST_PORTABLE
+++ KUBE_TEST_SERVER_TARGETS=($(kube::golang::server_test_targets))
++++ kube::golang::server_test_targets
++++ targets=(cmd/kubemark vendor/github.com/onsi/ginkgo/ginkgo)
++++ local targets
++++ [[ linux-gnu == \l\i\n\u\x* ]]
++++ targets+=(test/e2e_node/e2e_node.test)
++++ echo cmd/kubemark vendor/github.com/onsi/ginkgo/ginkgo test/e2e_node/e2e_node.test
+++ readonly KUBE_TEST_SERVER_TARGETS
+++ KUBE_TEST_SERVER_BINARIES=("${KUBE_TEST_SERVER_TARGETS[@]##*/}")
+++ readonly KUBE_TEST_SERVER_BINARIES
+++ KUBE_TEST_SERVER_PLATFORMS=("${KUBE_SERVER_PLATFORMS[@]}")
+++ readonly KUBE_TEST_SERVER_PLATFORMS
+++ readonly KUBE_PARALLEL_BUILD_MEMORY=40
+++ KUBE_PARALLEL_BUILD_MEMORY=40
+++ KUBE_ALL_TARGETS=("${KUBE_SERVER_TARGETS[@]}" "${KUBE_CLIENT_TARGETS[@]}" "${KUBE_TEST_TARGETS[@]}" "${KUBE_TEST_SERVER_TARGETS[@]}" cmd/gke-certificates-controller)
+++ readonly KUBE_ALL_TARGETS
+++ KUBE_ALL_BINARIES=("${KUBE_ALL_TARGETS[@]##*/}")
+++ readonly KUBE_ALL_BINARIES
+++ KUBE_STATIC_LIBRARIES=(cloud-controller-manager kube-apiserver kube-controller-manager kube-scheduler kube-proxy kube-aggregator kubeadm kubectl)
+++ readonly KUBE_STATIC_LIBRARIES
+++ KUBE_BINDATAS=(test/e2e/generated/gobindata_util.go)
+++ readonly KUBE_BINDATAS
++ source /home/sbezverk/developing/go/src/k8s.io/kubernetes/hack/lib/etcd.sh
+++ ETCD_VERSION=3.2.14
+++ ETCD_HOST=127.0.0.1
+++ ETCD_PORT=2379
+++ kube::util::host_platform
+++ local host_os
+++ local host_arch
+++ case "$(uname -s)" in
++++ uname -s
+++ host_os=linux
+++ case "$(uname -m)" in
++++ uname -m
+++ host_arch=amd64
+++ echo linux/amd64
++ KUBE_OUTPUT_HOSTBIN=/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local/bin/linux/amd64
++ KUBE_AVAILABLE_GROUP_VERSIONS='v1 admissionregistration.k8s.io/v1alpha1 admissionregistration.k8s.io/v1beta1 admission.k8s.io/v1beta1 apps/v1beta1 apps/v1beta2 apps/v1 authentication.k8s.io/v1 authentication.k8s.io/v1beta1 authorization.k8s.io/v1 authorization.k8s.io/v1beta1 autoscaling/v1 autoscaling/v2beta1 batch/v1 batch/v1beta1 batch/v2alpha1 certificates.k8s.io/v1beta1 extensions/v1beta1 events.k8s.io/v1beta1 imagepolicy.k8s.io/v1alpha1 networking.k8s.io/v1 policy/v1beta1 rbac.authorization.k8s.io/v1 rbac.authorization.k8s.io/v1beta1 rbac.authorization.k8s.io/v1alpha1 scheduling.k8s.io/v1alpha1 settings.k8s.io/v1alpha1 storage.k8s.io/v1beta1 storage.k8s.io/v1 storage.k8s.io/v1alpha1 '
++ KUBE_NONSERVER_GROUP_VERSIONS='
 abac.authorization.kubernetes.io/v0  abac.authorization.kubernetes.io/v1beta1  componentconfig/v1alpha1  imagepolicy.k8s.io/v1alpha1 admission.k8s.io/v1beta1'
+ kube::golang::setup_env
+ kube::golang::verify_go_version
++ which go
+ [[ -z /usr/local/go/bin/go ]]
+ local go_version
+ go_version=($(go version))
++ go version
+ local minimum_go_version
+ minimum_go_version=go1.9.1
++ echo -e 'go1.9.1\ngo1.9.4'
++ sort -s -t. -k 1,1 -k 2,2n -k 3,3n
++ head -n1
+ [[ go1.9.1 != go1.9.1 ]]
+ kube::golang::create_gopath_tree
+ local go_pkg_dir=/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes
++ dirname /home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes
+ local go_pkg_basedir=/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io
+ mkdir -p /home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io
+ [[ ! -e /home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes ]]
++ readlink /home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes
+ [[ /home/sbezverk/developing/go/src/k8s.io/kubernetes != \/\h\o\m\e\/\s\b\e\z\v\e\r\k\/\d\e\v\e\l\o\p\i\n\g\/\g\o\/\s\r\c\/\k\8\s\.\i\o\/\k\u\b\e\r\n\e\t\e\s ]]
+ cat
+ export GOPATH=/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local/go
+ GOPATH=/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local/go
+ [[ -n '' ]]
+ export PATH=/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local/go/bin:/usr/local/go/bin:/home/sbezverk/developing/go/src/k8s.io/kubernetes/third_party/etcd:/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/sbezverk/developing/go/bin
+ PATH=/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local/go/bin:/usr/local/go/bin:/home/sbezverk/developing/go/src/k8s.io/kubernetes/third_party/etcd:/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/sbezverk/developing/go/bin
+ local subdir
++ kube::realpath .
++ [[ ! -e . ]]
++ kube::readlinkdashf .
++ sed 's|/home/sbezverk/developing/go/src/k8s.io/kubernetes||'
++ [[ -d . ]]
++ cd .
++ pwd -P
+ subdir=
+ cd /home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/
++ go env GOROOT
+ export GOROOT=/usr/local/go
+ GOROOT=/usr/local/go
+ unset GOBIN
+ export GO15VENDOREXPERIMENT=1
+ GO15VENDOREXPERIMENT=1
+ BUILD_TARGETS=(vendor/k8s.io/code-generator/cmd/client-gen vendor/k8s.io/code-generator/cmd/lister-gen vendor/k8s.io/code-generator/cmd/informer-gen)
+ make -C /home/sbezverk/developing/go/src/k8s.io/kubernetes 'WHAT=vendor/k8s.io/code-generator/cmd/client-gen vendor/k8s.io/code-generator/cmd/lister-gen vendor/k8s.io/code-generator/cmd/informer-gen'
make: Entering directory '/home/sbezverk/developing/go/src/k8s.io/kubernetes'
make[1]: Entering directory '/home/sbezverk/developing/go/src/k8s.io/kubernetes'
make[1]: Leaving directory '/home/sbezverk/developing/go/src/k8s.io/kubernetes'
+++ [0214 14:15:29] Building the toolchain targets:
    k8s.io/kubernetes/hack/cmd/teststale
    k8s.io/kubernetes/vendor/github.com/jteeuwen/go-bindata/go-bindata
+++ [0214 14:15:29] Generating bindata:
    test/e2e/generated/gobindata_util.go
+++ [0214 14:15:30] Building go targets for linux/amd64:
    vendor/k8s.io/code-generator/cmd/client-gen
    vendor/k8s.io/code-generator/cmd/lister-gen
    vendor/k8s.io/code-generator/cmd/informer-gen
make: Leaving directory '/home/sbezverk/developing/go/src/k8s.io/kubernetes'
++ kube::util::find-binary client-gen
+++ kube::util::host_platform
+++ local host_os
+++ local host_arch
+++ case "$(uname -s)" in
++++ uname -s
+++ host_os=linux
+++ case "$(uname -m)" in
++++ uname -m
+++ host_arch=amd64
+++ echo linux/amd64
++ kube::util::find-binary-for-platform client-gen linux/amd64
++ local -r lookfor=client-gen
++ local -r platform=linux/amd64
++ locations=("${KUBE_ROOT}/_output/bin/${lookfor}" "${KUBE_ROOT}/_output/dockerized/bin/${platform}/${lookfor}" "${KUBE_ROOT}/_output/local/bin/${platform}/${lookfor}" "${KUBE_ROOT}/platforms/${platform}/${lookfor}")
++ local locations
++ locations+=($(find "${KUBE_ROOT}/bazel-bin/" -type f -executable     -path "*/${platform/\//_}*/${lookfor}" 2>/dev/null || true))
+++ find /home/sbezverk/developing/go/src/k8s.io/kubernetes/bazel-bin/ -type f -executable -path '*/linux_amd64*/client-gen'
+++ true
+++ ls -t /home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/bin/client-gen /home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/dockerized/bin/linux/amd64/client-gen /home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local/bin/linux/amd64/client-gen /home/sbezverk/developing/go/src/k8s.io/kubernetes/platforms/linux/amd64/client-gen
+++ head -1
+++ true
++ local -r bin=/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/bin/client-gen
++ echo -n /home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/bin/client-gen
+ clientgen=/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/bin/client-gen
++ kube::util::find-binary lister-gen
+++ kube::util::host_platform
+++ local host_os
+++ local host_arch
+++ case "$(uname -s)" in
++++ uname -s
+++ host_os=linux
+++ case "$(uname -m)" in
++++ uname -m
+++ host_arch=amd64
+++ echo linux/amd64
++ kube::util::find-binary-for-platform lister-gen linux/amd64
++ local -r lookfor=lister-gen
++ local -r platform=linux/amd64
++ locations=("${KUBE_ROOT}/_output/bin/${lookfor}" "${KUBE_ROOT}/_output/dockerized/bin/${platform}/${lookfor}" "${KUBE_ROOT}/_output/local/bin/${platform}/${lookfor}" "${KUBE_ROOT}/platforms/${platform}/${lookfor}")
++ local locations
++ locations+=($(find "${KUBE_ROOT}/bazel-bin/" -type f -executable     -path "*/${platform/\//_}*/${lookfor}" 2>/dev/null || true))
+++ find /home/sbezverk/developing/go/src/k8s.io/kubernetes/bazel-bin/ -type f -executable -path '*/linux_amd64*/lister-gen'
+++ true
+++ ls -t /home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/bin/lister-gen /home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/dockerized/bin/linux/amd64/lister-gen /home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local/bin/linux/amd64/lister-gen /home/sbezverk/developing/go/src/k8s.io/kubernetes/platforms/linux/amd64/lister-gen
+++ head -1
+++ true
++ local -r bin=/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/bin/lister-gen
++ echo -n /home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/bin/lister-gen
+ listergen=/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/bin/lister-gen
++ kube::util::find-binary informer-gen
+++ kube::util::host_platform
+++ local host_os
+++ local host_arch
+++ case "$(uname -s)" in
++++ uname -s
+++ host_os=linux
+++ case "$(uname -m)" in
++++ uname -m
+++ host_arch=amd64
+++ echo linux/amd64
++ kube::util::find-binary-for-platform informer-gen linux/amd64
++ local -r lookfor=informer-gen
++ local -r platform=linux/amd64
++ locations=("${KUBE_ROOT}/_output/bin/${lookfor}" "${KUBE_ROOT}/_output/dockerized/bin/${platform}/${lookfor}" "${KUBE_ROOT}/_output/local/bin/${platform}/${lookfor}" "${KUBE_ROOT}/platforms/${platform}/${lookfor}")
++ local locations
++ locations+=($(find "${KUBE_ROOT}/bazel-bin/" -type f -executable     -path "*/${platform/\//_}*/${lookfor}" 2>/dev/null || true))
+++ find /home/sbezverk/developing/go/src/k8s.io/kubernetes/bazel-bin/ -type f -executable -path '*/linux_amd64*/informer-gen'
+++ true
+++ ls -t /home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/bin/informer-gen /home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/dockerized/bin/linux/amd64/informer-gen /home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/local/bin/linux/amd64/informer-gen /home/sbezverk/developing/go/src/k8s.io/kubernetes/platforms/linux/amd64/informer-gen
+++ head -1
+++ true
++ local -r bin=/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/bin/informer-gen
++ echo -n /home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/bin/informer-gen
+ informergen=/home/sbezverk/developing/go/src/k8s.io/kubernetes/_output/bin/informer-gen
+ IFS=' '
+ read -ra GROUP_VERSIONS
+ GV_DIRS=()
+ INTERNAL_DIRS=()
+ for gv in '"${GROUP_VERSIONS[@]}"'
++ kube::util::group-version-to-pkg-path v1
++ staging_apis=($(
    pushd ${KUBE_ROOT}/staging/src/k8s.io/api > /dev/null
      find . -name types.go | xargs -n1 dirname | sed "s|\./||g" | sort
    popd > /dev/null
  ))
+++ pushd /home/sbezverk/developing/go/src/k8s.io/kubernetes/staging/src/k8s.io/api
+++ find . -name types.go
+++ xargs -n1 dirname
+++ sed 's|\./||g'
+++ sort
+++ popd
++ local group_version=v1
++ [[  admissionregistration/v1alpha1 admissionregistration/v1beta1 admission/v1beta1 apps/v1 apps/v1beta1 apps/v1beta2 authentication/v1 authentication/v1beta1 authorization/v1 authorization/v1beta1 autoscaling/v1 autoscaling/v2beta1 batch/v1 batch/v1beta1 batch/v2alpha1 certificates/v1beta1 core/v1 events/v1beta1 extensions/v1beta1 imagepolicy/v1alpha1 networking/v1 policy/v1beta1 rbac/v1 rbac/v1alpha1 rbac/v1beta1 scheduling/v1alpha1 settings/v1alpha1 storage/v1 storage/v1alpha1 storage/v1beta1  =~  v1  ]]
++ [[ v1 == \v\1 ]]
++ echo vendor/k8s.io/api/core/v1
++ return
+ api_dir=vendor/k8s.io/api/core/v1
+ nopkg_dir=vendor/k8s.io/api/core/v1
+ nopkg_dir=core/v1
+ pkg_dir=core/v1
+ [[  
 abac.authorization.kubernetes.io/v0  abac.authorization.kubernetes.io/v1beta1  componentconfig/v1alpha1  imagepolicy.k8s.io/v1alpha1 admission.k8s.io/v1beta1  == *\ \v\1\ * ]]
+ GV_DIRS+=("${pkg_dir}")
+ int_group=core/
+ [[ core/v1 = core/* ]]
+ int_group=api/
+ found=0
hack/update-codegen.sh: line 67: INTERNAL_DIRS[@]: unbound variable
```

**Comment by sbezverk** [comment]
@cblecker Please see above logs collected from linux machine.

**Comment by ipuustin** [comment]
@sbezverk : thanks for the logs. See also https://github.com/kubernetes/kubernetes/issues/59856. Which distribution and bash version are you using?

**Pull request merged**
