### PR TITLE
update the wrong format of string TargetPort

### LINKED ISSUE #54546: kubectl describe svc print wrong format of targetPort
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:

 when using  `kubectl describe svc `, the TargetPort is wrong 

```
TargetPort  %!d(*string=port1)/TCP
```

**What you expected to happen**:

if the targetPort is string, show the name correctly.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

update the wrong format of string TargetPort

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #54546 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dixudx** [comment]
@wackxu Please add a test for this. Thanks.

**Comment by wackxu** [comment]
@dixudx addressed

**Comment by vhosakot** [comment]
I see https://github.com/kubernetes/kubernetes/issues/54546 in k8s 1.8.4.

```
Name:              calico-typha
TargetPort:        %!d(string=calico-typha)/TCP

Name:              elasticsearch-logging
TargetPort:        %!d(string=db)/TCP

Name:                     kibana-logging
TargetPort:               %!d(string=ui)/TCP

Name:              tiller-deploy
TargetPort:        %!d(string=tiller)/TCP
```

Is this fix available in k8s 1.8.4?

I see this fix was merged on Nov 6, 2017 and k8s 1.8.4 was released on Nov 20, 2017 per https://github.com/kubernetes/kubernetes/releases/tag/v1.8.4.

**Pull request merged**
