### PR TITLE
Wait for goroutines creating routes to finish.

### PR DESCRIPTION
**Pull request by davidopp**
ref/ #21561 

cc/ @alex-mohr

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM (apply P1 label since this is apparently causing a bunch of issues especially in GKE)

**Comment by davidopp** [comment]
Do priority labels actually influence the order of the merge queue?

**Comment by wojtek-t** [comment]
@davidopp - yes; all PRs with priority labels are merged before any others (first P0s, then P1s, ...)

**Comment by alex-mohr** [comment]
FWIW, it's only causing significant issues for 1.2 k8s-on-gce at 200+ node scales -- and gke inherits k8s-on-gce issues.

That said, since we want 1k nodes for 1.2, it's low risk, and I've manually tested with enhanced glog.Infof logs, worth getting it in.

**Comment by alex-mohr** [comment]
(And of course, many thanks to @davidopp for putting this PR together!)

**Pull request merged**
