### PR TITLE
Revert 102925: "Fix Node Resources plugins score when there are pods with no requests

### PR DESCRIPTION
**Pull request by harisund**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:
Ref #105220, this partially reverts the changes from #102925 which caused unexpected spreading behavior in the BalancedResourceAllocation plugin

This partially reverts commit f7b2ca58586d2197fff5ad88d6b727d6bfcacf36.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

This introduces the same revert for branch 1.19 as seen in PRs #105239 (for 1.20) and #105238 (for 1.21)

#### Does this PR introduce a user-facing change?

```release-note
Fixes a regression in 1.19.13 which introduced unexpected scheduling behavior based on balanced resource allocation
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
/sig scheduling

### CODE REVIEW

**Review by harisund — COMMENTED** [review]
The force push is because I changed the email address the commit was associated with to the one I have signed the CLA with. The actual contents of the commit remain unchanged. 

```
[hsundararaja@sjc-ubu-eng-054][~/vmware/kubernetes/kubernetes]  (1.19-revert-102925)   $
$ git show  8bab7df | git patch-id
a764881aad92ae95cf574c1f75b8a1a486e3f674 8bab7df29cf10c64f4252139fc71ab0010da281e
[hsundararaja@sjc-ubu-eng-054][~/vmware/kubernetes/kubernetes]  (1.19-revert-102925)   $
$ git show aab99a0 | git patch-id
a764881aad92ae95cf574c1f75b8a1a486e3f674 aab99a0709a488f23a8a0b0c17047072a0319ea6

```

And this is the same patch-id as that seen in #105239 and #105238

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
