### PR TITLE
[WIP] Upgrade to Go 1.5.1

### PR DESCRIPTION
**Pull request by karlkfi**
Running some tests....

### CODE REVIEW

**Comment by karlkfi** [comment]
mesos/docker smoke test passed (Guestbook): https://teamcity.mesosphere.io/viewLog.html?buildId=47881&buildTypeId=Oss_KubernetesMesos_e2eTests&tab=buildResultsDiv&guest=1

Not sure why jenkins failed... looks like a git pull failure.

**Comment by mikedanese** [comment]
typically we update shippable/travis testing go versions and let that soak for a week or two before bumping the go version we use for building releases.

**Comment by karlkfi** [comment]
That's reasonable. I was mostly just curious.

**Comment by quinton-hoole** [comment]
@karlkfi Jenkins was flaky yesterday.  We've fixed it now.

@k8s-bot test this again please

**Comment by jdef** [comment]
this looks like a testing PR, closing out since someone else appears to be driving go1.5 upgrade compat

**Pull request closed without merging**
