### PR TITLE
Add upgrade Docker VM

### PR DESCRIPTION
**Pull request by johscheuer**
Add an Error Message to upgarde your Docker VM if needed, example output:

``` bash
+++ [0622 13:19:48] No docker host is set. Checking options for setting one...
+++ [0622 13:19:49] docker-machine was found.
+++ [0622 13:19:49] A Docker host using docker-machine named 'kube-dev' is ready to go!
Can't connect to 'docker' daemon.  please fix and retry.

Possible causes:
  - On Mac OS X, DOCKER_HOST hasn't been set. You may need to:
    - Create and start your VM using docker-machine or boot2docker:
      - docker-machine create -d virtualbox --virtualbox-memory 4096 --virtualbox-cpu-count -1 kube-dev
      - boot2docker init && boot2docker start
    - Set your environment variables using:
      - eval $(docker-machine env kube-dev)
      - $(boot2docker shellinit)
  - On Linux, user isn't in 'docker' group.  Add and relogin.
    - Something like 'sudo usermod -a -G docker jscheuermann'
    - RHEL7 bug and workaround: https://bugzilla.redhat.com/show_bug.cgi?id=1119282#c8
  - On Linux, Docker daemon hasn't been started or has crashed.
!!! Error in hack/../hack/update-generated-protobuf.sh:53
  'return 1' exited with status 1
Call stack:
  1: hack/../hack/update-generated-protobuf.sh:53 main(...)
Exiting with status 1
Updating generated-protobuf FAILED

$docker info
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
```

After running `docker-machine upgrade kube-dev` everything is fine again. So we should add a hint in the error message that this can also happen.

### CODE REVIEW

**Comment by ixdy** [comment]
ok to test

LGTM

**Comment by ixdy** [comment]
un-LGTM. maybe remove 6b945421214c4ba71635489c24e83524161cee11 from the commit, or squash commits? or fold your other PR into this one?

**Comment by johscheuer** [comment]
Removed  6b94542 from commit

**Comment by fejta** [comment]
@k8s-bot unit test this issue: #28076

**Comment by fejta** [comment]
@k8s-bot unit test this issue: #28076

**Pull request merged**
