### PR TITLE
github.com/matttproud/golang_protobuf_extensions v1.0.2

### PR DESCRIPTION
**Pull request by liggitt**
pick up tagged version with go.mod info

cc @dims @thaJeztah 

```release-note
NONE
```

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM (assuming green ☺️)

**Comment by dims** [comment]
@liggitt CI is asking to run `hack/update-vendor.sh` again :(

**Comment by pacoxu** [comment]
/hold
to avoid keeping retesting

The CI needs to be fixed.

**Comment by pacoxu** [comment]
The failure is caused by [#112690](https://github.com/kubernetes/kubernetes/pull/112690) that was merged.

**Comment by pacoxu** [comment]
The failure is caused by [#112690](https://github.com/kubernetes/kubernetes/pull/112690) that was merged.

**Comment by liggitt** [comment]
fixed up

/hold cancel

**Pull request merged**
