### PR TITLE
Update to go 1.12.7

### PR DESCRIPTION
**Pull request by tao12345666333**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test

/kind feature
> /kind flake

**What this PR does / why we need it**:

go1.12.7 (released 2019/07/08) includes fixes to cgo, the compiler,
and the linker.
See the <a href="https://github.com/golang/go/issues?q=milestone%3AGo1.12.7">Go 1.12.7 milestone</a> on our issue tracker for details.

https://github.com/golang/go/compare/go1.12.6...go1.12.7

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update to use go 1.12.7
```

### CODE REVIEW

**Comment by tao12345666333** [comment]
/assign @fejta @luxas 

PTAL :smile_cat:

**Comment by neolit123** [comment]
@tao12345666333 hi, you can mention this PR in  #sig-testing and/or #sig-release on the k8s slack about this. normally they can decided if we should bump golang.

**Comment by tao12345666333** [comment]
@neolit123  Thanks for your reminder!

**Comment by tao12345666333** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/79912

**Comment by tao12345666333** [comment]
```
W0711 02:36:41.825] Step 1/16 : FROM k8s.gcr.io/kube-cross:v1.12.7-1
W0711 02:36:41.825] manifest for k8s.gcr.io/kube-cross:v1.12.7-1 not found
```
We need `k8s.gcr.io/kube-cross:v1.12.7-1` image.  

@javier-b-perez PTAL  Thanks.

**Comment by cblecker** [comment]
/unassign fejta luxas
/assign @javier-b-perez 

Bazel tests passing. We should be good to build/push the image.

**Comment by javier-b-perez** [comment]
I've created the image [1] and started the process to have kube-cross:v1.12.7-1 in k8s.gcr.io
[1] gcr.io/k8s-staging-build-image/kube-cross:v1.12.7-1

**Comment by javier-b-perez** [comment]
Image should be available in k8s.gcr.io/kube-cross:v1.12.7-1

**Comment by cblecker** [comment]
@tao12345666333 Can you also update the version here:
https://github.com/kubernetes/kubernetes/blob/2659b3755aa16e1c5f729350d27721f7ce701240/build/dependencies.yaml#L37

**Comment by tao12345666333** [comment]
sure

**Comment by tao12345666333** [comment]
@cblecker Addressed. Thanks.

**Pull request merged**
