### PR TITLE
fix go vet errors

### PR DESCRIPTION
**Pull request by jessfraz**
``` release-note
```

This fixes the `go vet` errors brought about by go 1.7 testing re (#28742).

The are all pretty trivial and mostly related to literal composites.

also related to #16086

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29802)

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@jfrazelle So sorry for the long delay.  
LGTM!

**Comment by jfrazelle** [comment]
ill reabse!

**Comment by jfrazelle** [comment]
@k8s-bot test this issue #26626

**Comment by jfrazelle** [comment]
@k8s-bot test this issue #27455

**Comment by jfrazelle** [comment]
it's green again :)

**Pull request merged**
