### PR TITLE
Kubelet/kubectl weird output fix

### LINKED ISSUE #51452: kubelet --help wired output
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
kubelet --helpd prints some wired output at top
goes like:
2017/08/28 21:37:12 proto: duplicate proto type registered: google.protobuf.Any
2017/08/28 21:37:12 proto: duplicate proto type registered: google.protobuf.Duration
2017/08/28 21:37:12 proto: duplicate proto type registered: google.protobuf.Timestamp

**What you expected to happen**:
prints help information directly
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
seems it was caused by package conflict.
**Environment**:
- Kubernetes version (use `kubectl version`):Kubernetes v1.8.0-alpha.3.347+877ee91930ccf9-dirty
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):Ubuntu 16.04 LTS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by adityadani**
**What this PR does / why we need it**:
All kube binaries print the following message at the top when executed:
```
2017/08/28 21:37:12 proto: duplicate proto type registered: google.protobuf.Any
2017/08/28 21:37:12 proto: duplicate proto type registered: google.protobuf.Duration
2017/08/28 21:37:12 proto: duplicate proto type registered: google.protobuf.Timestamp
```
This PR addresses the above issue
It involves the following two changes:
1. Updating vendor packages
- Removes everything under the repo ``go.pedge.io``
- Updates repo libopenstorage/openstorage (which was using the above package)
2. Updates the portworx volume native driver to adhere to the newly vendor'ed code.

This is a cherry-pick candidate. #52132 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 

fixes #51452

**Special notes for your reviewer**:
I have divided the changes into 2 commits
1. Vendor'ed changes
2. Changes in portworx volume driver.

```release-note
Remove duplicate proto errors in kubelet.
```

### CODE REVIEW

**Comment by adityadani** [comment]
@wojtek-t 
Here is the original PR #52132 that got merged into master.
A lot of users have requested to back port this change to 1.7 release.

**Comment by mjura** [comment]
@adityadani: thank you for doing this
@wojtek-t: Can you please approve this for testing?

**Comment by adityadani** [comment]
@wojtek-t Can you add the lgtm label ?

**Comment by wojtek-t** [comment]
I won't lgtm it myself. The change is pretty large, and I'm not convinced it's really needed.
How I understand this fix is that it is fixing something in kubelet logs.
My personal opinion is that risk for backporting it is not worth the gains of it.

@dchen1107 @yujuhong - since it seems to be kubelet related, what are your thoughts?

**Comment by yujuhong** [comment]
> @dchen1107 @yujuhong - since it seems to be kubelet related, what are your thoughts?

It's not just kubelet. Other binaries (e.g., controller manager) suffer from the same issue too. Although the log spam is annoying, there is no other side effect AFAIK.

@saad-ali the majority of the change is in the volume plugin. How safe is this?

**Comment by adityadani** [comment]
Even kubectl will show this error
```
$ kubectl apply -f spec.yaml
2017-10-18 23:34:33.251681 I | proto: duplicate proto type registered: google.protobuf.Any
2017-10-18 23:34:33.251737 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-10-18 23:34:33.251754 I | proto: duplicate proto type registered:google.protobuf.Timestamp
```

**Comment by wojtek-t** [comment]
With 1.10 already out, 1.7 branch is no longer supported. I'm closing this one.

**Pull request closed without merging**
