### PR TITLE
Add clarity and fix bugs for kubelet e2e test

### PR DESCRIPTION
**Pull request by yujuhong**

### CODE REVIEW

**Comment by brendandburns** [comment]
LGTM.

**Comment by vishh** [comment]
LGTM

**Comment by yujuhong** [comment]
@k8s-oncall, could we merge this PR? It'd be nice to get some more resource usage results before v1.1.

**Comment by fabioy** [comment]
Merge bot is going again, so hopefully it'll go in soon. Thanks.

**Pull request merged**
