### PR TITLE
Do not hold the lock for a long time

### PR DESCRIPTION
**Pull request by lavalamp**
Followup to #30839.

I'm not convinced this is a super great idea but I'll throw it out and let others decide.

Ref https://github.com/kubernetes/minikube/issues/368
Ref #30759

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30948)

### CODE REVIEW

**Comment by wojtek-t** [comment]
I think that it depends on how frequently we do resyncs - if they are relatively rare (in which direction we are trying to go), this should be a good idea in my opinion.

**Comment by deads2k** [comment]
This looks like it would help fairness while running a resync, but I really couldn't predict what the cost of all the extra lock acquisitions would be.  Do we know how long the average resync takes now (how long we're locking everyone out)?

The change seems reasonable, at least to try.

**Comment by deads2k** [comment]
> Do we know how long the average resync takes now (how long we're locking everyone out)?

Ah, I made through to the end of the other pull.  Yeah, this seems like a good idea.

**Comment by lavalamp** [comment]
@k8s-bot unit test this #IGNORE (build got killed)

**Comment by lavalamp** [comment]
In that case, @deads2k or @wojtek-t would one of you like to actually LGTM? :)

**Comment by wojtek-t** [comment]
Sure - I can do that :)

**Comment by dlorenc** [comment]
Would it be possible to cherry pick this into the next 1.3.* release? This has bitten a few minikube users.

**Comment by mrook** [comment]
Yeah would be nice if this gets merged, pretty sure I'm seeing this same error in my ingress controller:

/usr/lib/google-golang/src/runtime/panic.go:569 +0x9e fp=0xc420b76be0 sp=0xc420b76bc0 pc=0x44185e
k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).queueActionLocked(0xc420154840, 0x142fc83, 0x4, 0x140b1c0, 0xc4206aed30, 0x1, 0x0)
/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go:511 +0x179 fp=0xc420b76e88 sp=0xc420b76db0 pc=0x6752d9
created by k8s.io/contrib/ingress/vendor/github.com/golang/glog.init.1
/usr/local/google/home/beeps/goproj/src/k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/client/cache/reflector.go:283 +0x303

**Pull request merged**
