### PR TITLE
Automated cherry pick of #31189 #31704 #32831 #32907 #33003 #33349 #31190 #33581 #34089 #34234 #32822 #33393 #34246 #34435 upstream release 1.4

### PR DESCRIPTION
**Pull request by wojtek-t**
We are going to release etcd v3 in 1.4.x release.

```
Cherrypick etcd v3-related bug fixes to 1.4 branch
```

This PR is cherrypicking the necessary PR so the 1.4 branch.
Those PRs include:
- Updates of etcd Godeps
- Update to pkg/storage/etcd directory
- Two PR that were unnecessary to avoid conflicts: #31189 #31704

@hongchaodeng @xiang90 @lavalamp

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35100)

### CODE REVIEW

**Comment by wojtek-t** [comment]
Something is wrong here - etcd3 tests are failing. I will take a look into it later.

**Comment by jessfraz** [comment]
I bet its because of the changes to godep

**Comment by wojtek-t** [comment]
There are no logs from the failed etcd3 run. I'm kicing the tests again to see what is happening there.

@k8s-bot test this, issue: #IGNORE

**Comment by wojtek-t** [comment]
The reason why it's not working is that we are starting etcd;2.2.1 here (which doesn't expose v3 api) and apiserver is trying to talk using v3 API. I still understand why we are doing this though.

**Comment by wojtek-t** [comment]
OK - it seems that I simply forgot about one fix PR: https://github.com/kubernetes/kubernetes/pull/32477

I will close this PR and reopen another one with that another PR.

**Comment by wojtek-t** [comment]
I opened https://github.com/kubernetes/kubernetes/pull/35205 instead of this one (I wanted to use the cherrypick script instead of doing this manually).

**Pull request closed without merging**
