### PR TITLE
Fix some races/multi-thread access in the reboot test.

### PR DESCRIPTION
**Pull request by brendandburns**
@ixdy @mbforbes @quinton-hoole 

I think that this should fix the problems that are causing this test to perma-fail on GKE.

I'm going to self-merge this on green, because I want e2e to run green over the weekend.

### CODE REVIEW

**Comment by quinton-hoole** [comment]
LGTM 
(damn go for loops and closures tripping over each other) :-)

**Comment by roberthbailey** [comment]
This doesn't seem to have fixed the reboot test, which is still failing on GKE.

/cc @mbforbes

**Comment by quinton-hoole** [comment]
I'll open a separate issue to track fixing this.

**Comment by mbforbes** [comment]
Whoops!

**Pull request merged**
