### PR TITLE
remove hack/e2e.go

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: removes hack/e2e.go which has been a wrapper around k8s.io/test-infra/kubetest for O(years).

We've had notices about kubetest in the output already:
https://github.com/kubernetes/kubernetes/blob/90f41951cd53ec63bf13d52371f88bbc3bb764db/hack/e2e.go#L56
https://github.com/kubernetes/kubernetes/blob/90f41951cd53ec63bf13d52371f88bbc3bb764db/hack/e2e.go#L79

**Which issue(s) this PR fixes**: https://github.com/kubernetes/kubernetes/issues/82448

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
Looks like a bunch more references need to be cleaned up @BenTheElder 

/area code-organization

**Comment by BenTheElder** [comment]
ACK, `make test-e2e` might be especially thorny to remove, it's hard to know who is using these :(

hmmm...

**Comment by dims** [comment]
@BenTheElder wanna refresh this? better to get it in early in the cycle.

**Comment by dims** [comment]
/close

fixed in another PR

**Pull request closed without merging**
