### PR TITLE
Update exported vars to uppercase in test/cmd

### PR DESCRIPTION
**Pull request by xychu**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Separated from https://github.com/kubernetes/kubernetes/pull/73518#issuecomment-464992905

**Which issue(s) this PR fixes**:

Part of #72956

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/ok-to-test
@kubernetes/bash-firefighters I wonder if it might be better to disable this lint here rather than update all of these, it's hard to tell if every instance / reference was updated.

**Comment by spiffxp** [comment]
legit test failure
```
/go/src/k8s.io/kubernetes/test/cmd/../../test/cmd/delete.sh: line 39: id_field: unbound variable
```

**Comment by xychu** [comment]
@spiffxp have fixed and rebased master branch.

**Comment by spiffxp** [comment]
FYI the integration test failure doesn't appear to be a flake

**Comment by spiffxp** [comment]
/test pull-kubernetes-integration
I take that back, I'm pretty sure it is a flake, ref: https://github.com/kubernetes/kubernetes/issues/74431

**Comment by spiffxp** [comment]
I'm also torn whether this is something we actually want to go through with.  I personally find these tests more readable without the all-caps stuff

**Comment by xychu** [comment]
> I'm also torn whether this is something we actually want to go through with. I personally find these tests more readable without the all-caps stuff

@spiffxp https://github.com/kubernetes/kubernetes/pull/73388#discussion_r251661796 and https://github.com/koalaman/shellcheck/wiki/SC2154
Yes, if not disable SC2154 another way should be `${var:?}`, but it is needed either for all the un-exported vars or the first time for each var where it is used in current file. IMPO, the later way would be confusing as the first place used is hard to maintain, and use `${var:?}` for all vars would need as many changes as export them via all-caps. That's why I started #73518.

cc @BenTheElder

**Comment by BenTheElder** [comment]
previously I've updated to use `${var:?}` for the case where we're referencing var from script a while it is defined in script b, imo this is a good pattern for that specific case.

**Comment by xychu** [comment]
https://github.com/kubernetes/kubernetes/pull/74635 created and will fix others as well.
This could be closed.

**Pull request closed without merging**
