### PR TITLE
Automated cherry pick of #38814 #39079 release 1.5

### PR DESCRIPTION
**Pull request by jszczepkowski**
```release-note
fixed cluster validation script for HA clusters
```

### CODE REVIEW

**Comment by saad-ali** [comment]
Please rebase

**Comment by jszczepkowski** [comment]
@saad-ali 
Rebease completed, all tests are green now.

**Review by saad-ali — APPROVED** [review]

**Comment by saad-ali** [comment]
@kubernetes/test-infra-maintainers Any idea why the submit queue is not picking up this PR? All checks look green:

```
@k8s-merge-robot  Submit Queue — Required Github CI test is not green: Jenkins Bazel Build
Details@k8s-ci-robot  Jenkins CRI GCE Node e2e — Build succeeded.
Details@k8s-ci-robot  Jenkins GCE Node e2e — Build succeeded.
Details@k8s-ci-robot  Jenkins GCE e2e — Build succeeded.
Details@k8s-ci-robot  Jenkins GCE etcd3 e2e — Build succeeded.
Details@k8s-ci-robot  Jenkins GCI GCE e2e — Build succeeded.
Details@k8s-ci-robot  Jenkins GCI GKE smoke e2e — Build succeeded.
Details@k8s-ci-robot  Jenkins GKE smoke e2e — Build succeeded.
Details@k8s-ci-robot  Jenkins Kubemark GCE e2e — Build succeeded.
Details@k8s-ci-robot  Jenkins unit/integration — Build succeeded.
Details@k8s-ci-robot  Jenkins verification — Build succeeded.
Details@thelinuxfoundation  cla/linuxfoundation — jszczepkowski authorized
```

**Comment by saad-ali** [comment]
@k8s-bot bazel test this

**Comment by ixdy** [comment]
@saad-ali you figured it out, but SQ actually tells you, though for some reason you have to click on the "PRs" tab: http://submit-queue.k8s.io/#/prs?prDisplay=39137&historyDisplay=39137

**Comment by ixdy** [comment]
Ah, the link on GitHub is subtly wrong. https://github.com/kubernetes/contrib/pull/2232 to fix.

**Comment by spxtr** [comment]
Oh, I suggest merging this by hand. https://github.com/kubernetes/test-infra/pull/1436 added the ability to only run tests against certain branches, but it doesn't even set a green checkmark. I'll make a fix today.

**Comment by spxtr** [comment]
@k8s-bot bazel test this

**Comment by spxtr** [comment]
OK, it says "Skipped" now :)

**Pull request merged**
