### PR TITLE
Update RBAC rules for CSIDriver

### LINKED ISSUE #68819: CSI E2E tests: fail with upcoming CSI release
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When testing k8s master with the "canary" CSI images (= the images which will be tagged as the next release end of this week), the CSI volume tests fail.

PVCs remain pending because the external-attacher runs into a permission issue (from its log):
```
E0919 08:34:56.218106       1 leaderelection.go:224] error retrieving resource lock e2e-tests-csi-mock-plugin-l84wg/csi-hostpath: endpoints "csi-hostpath" is forbidden: User "system:serviceaccount:e2e-tests-csi-mock-plugin-l84wg:csi-hostpath-service-account" cannot get resource "endpoints" in API group "" in the namespace "e2e-tests-csi-mock-plugin-l84wg"
I0919 08:34:56.218136       1 leaderelection.go:180] failed to acquire lease e2e-tests-csi-mock-plugin-l84wg/csi-hostpath
```

**What you expected to happen**:

Should work?

**How to reproduce it (as minimally and precisely as possible)**:

* build k8s master
* start cluster: `RUNTIME_CONFIG= ALLOW_PRIVILEGED=1 FEATURE_GATES="BlockVolume=true,MountPropagation=true,KubeletPluginsWatcher=true"  hack/local-up-cluster.sh -O`
* run tests: `make WHAT=test/e2e/e2e.test && go run hack/e2e.go -- --provider=local --test --test_args="--ginkgo.focus=CSI.plugin.test.using.CSI.driver:.hostPath -csiImageVersion=canary"`

**Anything else we need to know?**:

It works with the latest released versions of the CSI containers (i.e. without `-csiImageVersion=canary`). That is how this test currently runs in the k8s CI.

If new permissions are needed, then https://kubernetes-csi.github.io/docs/Example.html also needs to be updated.

### PR DESCRIPTION
**Pull request by pohly**
The leadership election in external-provisioner versions > v0.3.0 needs
additional permissions, otherwise the provisioner fails in the CSI E2E
test completely with:

E0919 08:34:56.218106       1 leaderelection.go:224] error retrieving
resource lock e2e-tests-csi-mock-plugin-l84wg/csi-hostpath: endpoints
"csi-hostpath" is forbidden: User
"system:serviceaccount:e2e-tests-csi-mock-plugin-l84wg:csi-hostpath-service-account"
cannot get resource "endpoints" in API group "" in the namespace
"e2e-tests-csi-mock-plugin-l84wg"

**What this PR does / why we need it**:

This makes it possible to run the CSI E2E tests with a more recent release of the external-provisioner, something that is planned for the 1.12 release.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #68819

**Special notes for your reviewer**:

This turned into a more complete set of changes. For example, leadership election gets enabled and turned on also for the external-attacher.

It's probably best to review each commit separately.

/sig storage

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jsafrane** [comment]
This allows the external attacher to read/write **any** endpoints in the cluster, which is not what we want. Admin (or e2e test) should give the permission to operate only in the namespace where the attacher runs, like it's in the example: https://github.com/kubernetes-csi/external-attacher/blob/master/deploy/kubernetes/deployment.yaml#L58

**Comment by jsafrane** [comment]
BTW, are you sure that the *attacher* wanted to modify *endpoints*? In the code I can see that is uses ConfigMaps for leader election.

https://github.com/kubernetes-csi/external-attacher/blob/4ca824612061ca6def199640a68a8dba7bf0348d/cmd/csi-attacher/leader.go#L52

(btw, we should unify the provisioner and the attacher to use one object, either endpoints or config maps).

**Comment by pohly** [comment]
You are right, it was the provisioner.

**Comment by pohly** [comment]
So I guess this has to be fixed in a) test/e2e/storage/csi_objects.go) and b) the kubernetes-csi documentation, right?

**Comment by liggitt** [comment]
Yes, setup of leader election permissions belongs more to the deployment of the csi components… that is what knows how it does leader election and what namespace/name it should have access to

**Comment by pohly** [comment]
I've revised the commit to use RoleBindings inside the namespace, as suggested by @jsafrane on Slack, but did quite get it right - the test now fails again with the same error in this configuration.

**Comment by pohly** [comment]
@jsafrane this is now working for me and implementes what we discussed on Slack and in https://github.com/kubernetes/kubernetes/issues/68819.

An alternative PR is https://github.com/kubernetes/kubernetes/pull/68887. Jan and I ended up working on this in parallel ;-}

**Comment by liggitt** [comment]
This is better than putting the permissions in the bootstrap policy, but hard-coding permissions inside the e2e test means that we're testing something unrelated to what is actually deployed.

What is really needed is a manifest describing the required permissions that can be used by the e2e test and by actual deployers, ensuring this test verified the permissions are sufficient

**Comment by pohly** [comment]
Jordan Liggitt <notifications@github.com> writes:
> This is better than putting the permissions in the bootstrap policy,
> but hard-coding permissions inside the e2e test means that we're
> testing something unrelated to what is actually deployed.

The problem is that deployments are defined by CSI driver
maintainers. There are some possible variations (version of the sidecar
containers, with or without leadership election) which change the set of
permissions.

> What is really needed is a manifest describing the required
> permissions that can be used by the e2e test and by actual deployers,
> ensuring this test verified the permissions are sufficient

As Jan said in
https://github.com/kubernetes/kubernetes/issues/68819#issuecomment-423098702,
those manifests should be kept with the sidecar apps. Then they can be
updated together with the code that depends on them. The rules embedded
with the test (either in code or via a manifest file) can only be a
copy.

I agree that being able to drop a verbatim copy from the external repo
into Kubernetes is nice. But this will require more planning (like
setting up and documenting those external manifest files) and also might
have to be done slightly differently in the test (should we create roles
under a global, unique name or mangle the names so that each test gets
its own rules so that different tests can use potentially different
rules?). Anyway, just my 2 cents.

**Comment by pohly** [comment]
Let's merge PR #68887 instead, because it is closer to the final goal.

**Pull request closed without merging**
