### PR TITLE
Retry 'service unavailable' failures in proxy test

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #10792 

cc @davidopp @quinton-hoole

### CODE REVIEW

**Comment by davidopp** [comment]
LGTM

@quinton-hoole is out for a month.

We won't be able to get a shippable result until we fix #11136 and #11106

**Comment by thockin** [comment]
shippable is fixed - @davidopp mark this OK if you're ready to merge it

**Comment by wojtek-t** [comment]
@thockin - ready for merge

**Comment by lavalamp** [comment]
I don't know about this-- we already try N times, the point of which was to make sure it *always* works. If the network is eating our requests that's a bug that needs to be fixed. Adding this retry logic kinda defeats the purpose.

**Comment by wojtek-t** [comment]
@lavalamp - I would agree if this was because of our network (e.g. kube-proxy or sth like that eating our requests). However, in this case apiserver was sending a request: "GET http://"kubelet-ip":10250/logs" and it's not reaching Kubelet at all. IIUC it's not going through any other components - it should just reach Kubelet. Or am I missing something?

**Comment by wojtek-t** [comment]
To give you a bit more context:
- an example failure is: kubernetes-e2e-gce/7561
- at 22:26:06 apiserver gets the request to proxy logs from node: e2e-gce-minion-4qfv:1025:

        I0712 22:26:06.333028       8 handlers.go:137] GET /api/v1/proxy/nodes/e2e-gce-minion-4qfv:10250/logs/: (2.052688ms) 503

-  it sends the request directly to Kubelet using its IP address: "https://10.240.175.77:10250/logs/'
- Kubelet doesn't even get the request
- Kubelet is up at that time, it's ready, it correctly responded to all requests before and after it - it just didn't respond to that __one__ particular request

Unfortunately we can't get more information out of the logs that we have, but from Kubernetes perspective everything seems to be correct. My feeling is that it is some problem with GCE networking, that's why I added this retry mechanism - but if you have any other suggestions, I'm happy to revert this change if you know what else can be wrong.

**Comment by lavalamp** [comment]
I agree with you that it seems mysterious, and I don't have an explanation. But I'd rather have it count up how many requests succeeded/failed (like ping) so we have records in our test logs and can keep track of this mysterious request loss. We can set a threshold that keeps our tests green. We can get GCE networking folks involved. We should not be papering over this, IMO.

**Comment by thockin** [comment]
It would be nice to log failures, that's a great point.  I just can't repro a lot of these things readily.

**Comment by wojtek-t** [comment]
>
I agree with you that it seems mysterious, and I don't have an explanation. But I'd rather have it count up how many requests succeeded/failed (like ping) so we have records in our test logs and can keep track of this mysterious request loss. We can set a threshold that keeps our tests green. We can get GCE networking folks involved. We should not be papering over this, IMO.

@lavalamp 
SGTM - I will leave the threshold as I made it in this PR (10% requests can fail), but I will add logging (log error if there will be non-zero number of failures). I will prepare a PR tomorrow.
Does it sound ok for you?

**Comment by lavalamp** [comment]
Yes, thanks.

**Comment by lavalamp** [comment]
@thockin is unable to reproduce. I think we should *not* assume this is a GCE network problem. Also see #11119 which sounds an awful lot like this problem.

**Comment by wojtek-t** [comment]
@lavalamp - I also tried to reproduce it many times and didn't manage to do it. My hypothesis (but this is just a hypothesis and I don't know how to confirm it) is that it depends on the load on GCE and it fails if the load in GCE is high.
Also #11119 talks only about Vagrant - these failures happens on GCE so this doesn't need to be the same thing.

**Pull request merged**
