### PR TITLE
Adding gnufied as reviewer for volume controller

### PR DESCRIPTION
**Pull request by gnufied**
I have helped review several PRs and made new
PRs to this area.

cc @childsb @saad-ali

### CODE REVIEW

**Comment by gnufied** [comment]
@pmorie @eparis can you approve or lgtm this?

**Comment by eparis** [comment]
add yourself as an approver while you are in there (also add saad and jsafrane as approvers)

**Comment by gnufied** [comment]
@eparis  saad, jan are already approvers. I am content to be a reviewer for now.

**Comment by gnufied** [comment]
This was changed since I opened this PR - https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/OWNERS and they were added as owners.

**Comment by eparis** [comment]
@gnufied cool, glad it was updated!

In the future please use the release note block supplied in the template. If you just enter 'NONE' in the block it will set the label correctly.

**Comment by gnufied** [comment]
@eparis thanks I will.

**Pull request merged**
