### PR TITLE
Use real proxier inside hollow-proxy but with mocked syscalls

### PR DESCRIPTION
**Pull request by shyamjvs**
Fixes https://github.com/kubernetes/kubernetes/issues/43701

This should make hollow-proxy better mimic the real kube-proxy in performance.
Maybe next we should have a more realistic implementation even for fake iptables (adding/updating/deleting rules/chains in an table, just not on the real one)? Though I'm not sure how important it is.

cc @kubernetes/sig-scalability-misc @kubernetes/sig-network-misc @wojtek-t @gmarek

### CODE REVIEW

**Comment by shyamjvs** [comment]
Sorry about all those assignments/unassignments. Messed up with the k8s-merge-bot.

**Comment by wojtek-t** [comment]
@shyamjvs - thanks a lot for working on it. Did you verify the impact of this change in some larger kubemarks? (For example 500-node one - how much more cpu is hollow-proxy using with it)?

**Comment by shyamjvs** [comment]
@wojtek-t I haven't checked it for large cluster. Will do it and see.

**Comment by shyamjvs** [comment]
So I ran the test on 500-node kubemark cluster and also verified that our new hollow-proxy is working by looking at logs. And the performance doesn't seem to be much affected.
Strangely it has even gone down by a little bit as compared to our 500-kubemark CI test (~30-32% in CI and ~28% with modified proxy), but maybe this is too little a variation.

**Comment by wojtek-t** [comment]
OK - let's merge and we will see what will happen.

/lgtm
/approve

**Comment by wojtek-t** [comment]
@shyamjvs This PR broke kubemark-scale (which isn't extremely surprising). Can you please take a look into it and confirm what the actual reason is (I would suspect that hollow-proxy is not starving hollow-kubelet, but we should confirm if that's really the case).

The next steps are (in my opinion):
- smart revert of this PR (we don't need to revert all of it)
- try to work on slightly better fake implementation of fake ip-tables (we're very heavily utilizing the "restore" functionality) - with fake implementation we're pretty much builting everything from scratch all the time.
- try to improve kube-proxy performance (which is something Tim and me are working on anyway)

**Comment by shyamjvs** [comment]
@wojtek-t Thanks for the lead. I'll look into it.

**Comment by gmarek** [comment]
The first thing to try is probably just try creating a small external cluster with Nodes of the same size as in kubemark-scale, as see what happens when you try to schedule the same number of hollow-nodes there.

**Comment by shyamjvs** [comment]
Ok, so it seems like there are no logs at all from the nodes/master as all those runs timed out. (http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/418/artifacts/)
So the only useful information seems to be in build-log.txt and something clearly went wrong with the hollow-kubelet with infinite such messages before timing out:

```
I0514 09:25:31.885] May 14 09:25:31.656: INFO: Condition Ready of node hollow-node-zht3k is false instead of true. Reason: NodeStatusUnknown, message: Kubelet stopped posting node status.
I0514 09:25:31.885] May 14 09:25:31.656: INFO: Condition Ready of node hollow-node-zj7k7 is false instead of true. Reason: NodeStatusUnknown, message: Kubelet stopped posting node status.
I0514 09:25:31.885] May 14 09:25:31.656: INFO: Condition Ready of node hollow-node-zjzc5 is false instead of true. Reason: NodeStatusUnknown, message: Kubelet stopped posting node status.
I0514 09:25:31.885] May 14 09:25:31.656: INFO: Condition Ready of node hollow-node-zk14q is false instead of true. Reason: NodeStatusUnknown, message: Kubelet stopped posting node status
I0514 09:25:31.886] May 14 09:25:31.656: INFO: Condition Ready of node hollow-node-zpwx6 is false instead of true. Reason: NodeStatusUnknown, message: Kubelet stopped posting node status.
```

@wojtek-t I'm not sure if I totally understand your 2nd point. IIUC the new state of the table that we restore to, is generated inside syncProxyRules() method of the proxier (https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L1468) and this is done both for real/fake proxy before calling RestoreAll. The RestoreAll function itself merely just copies the new table (https://github.com/kubernetes/kubernetes/blob/master/pkg/util/iptables/testing/fake.go#L88). If you think it makes sense, we can experiment by removing that copy operation. WDYT?

@gmarek Thanks for the suggestion. Will try it.

**Comment by wojtek-t** [comment]
> @wojtek-t I'm not sure if I totally understand your 2nd point. IIUC the new state of the table that we restore to, is generated inside syncProxyRules() method of the proxier (https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L1468) and this is done both for real/fake proxy before calling RestoreAll. The RestoreAll function itself merely just copies the new table (https://github.com/kubernetes/kubernetes/blob/master/pkg/util/iptables/testing/fake.go#L88). If you think it makes sense, we can experiment by removing that copy operation. WDYT?

@shyamjvs  - I meant "Save" instead of "Restore". Sorry for confusion.

> The first thing to try is probably just try creating a small external cluster with Nodes of the same size as in kubemark-scale, as see what happens when you try to schedule the same number of hollow-nodes there.

That would work only if we create the same amount of services/endpoints - otherwise we won't reproduce it - see e.g. kubemark-500 which works fine now.

**Comment by shyamjvs** [comment]
@wojtek-t We are seeing 2 kinds of hollow-node failures:

```
NAME                    READY     STATUS       RESTARTS   AGE
hollow-node-7dtn0       0/3       Preempting   0          6h
hollow-node-8z27j       0/3       Preempting   0          6h
hollow-node-h5ljc       0/3       OutOfcpu     0          6h
hollow-node-jv570       0/3       OutOfcpu     0          6h
hollow-node-sf82k       0/3       Preempting   0          6h
```

The OutOfcpu ones failed with the following status:
```
Name:		hollow-node-jv570
Namespace:	kubemark
Node:		kubemark-2000-minion-group-sscq/
.....
Status:		Failed
Reason:		OutOfcpu
Message:	Pod Node didn't have enough resource: cpu, requested: 120, used: 7960, capacity: 8000
```
(and also events with the same msg as above)

And the kernel logs from the minion suggest OOM'ing:
```
May 15 17:01:18 kubemark-2000-minion-group-sscq kernel: Out of memory: Kill process 20719 (kubemark) score 1004 or sacrifice child
May 15 17:01:18 kubemark-2000-minion-group-sscq kernel: Killed process 20719 (kubemark) total-vm:1698420kB, anon-rss:833424kB, file-rss:0kB
May 15 17:03:28 kubemark-2000-minion-group-sscq kernel: kubemark invoked oom-killer: gfp_mask=0x24201ca, order=0, oom_score_adj=999
May 15 17:03:28 kubemark-2000-minion-group-sscq kernel: kubemark cpuset=<redacted> mems_allowed=0
May 15 17:03:28 kubemark-2000-minion-group-sscq kernel: CPU: 7 PID: 19768 Comm: kubemark Not tainted 4.4.21+ #1
May 15 17:03:28 kubemark-2000-minion-group-sscq kernel: Hardware name: Google Google Compute Engine/Google Compute Engine, BIOS Google 01/01/2011
```

On doing a top on the minion, all the high CPU using 'kubemark' processes were that of hollow-proxy.
I couldn't get any better way to obtain a per-container breakup of resource usage to prove that it's hollow-proxy. (Do you know of some?)
Also it is unclear to me why one suggests OutOfcpu and the other suggests OOM.

**Comment by shyamjvs** [comment]
I think there are at least 2 issues at play here:

- hollow-proxy is OOM'ing on the real node as can be seen from its kernel logs. And I think the reason behind it is, it's failing to write to the file `/proc/<PID>/oom_score_abj`. That file holds a no. from -1000 to 1000 saying how easily the process should be oom-killed (ref: https://askubuntu.com/a/60675). The default value in that file seems to be `987` (making it too easily oom-killable) and kube-proxy tries to over-write it with `0`. However the write fails due to container not running in privileged mode:
```
I0515 18:44:38.712104       7 oom_linux.go:65] attempting to set "/proc/self/oom_score_adj" to "0"
I0515 18:44:38.712457       7 oom_linux.go:75] write /proc/self/oom_score_adj: permission denied
I0515 18:44:38.812619       7 oom_linux.go:75] write /proc/self/oom_score_adj: permission denied
I0515 18:44:38.915579       7 oom_linux.go:82] failed to set "/proc/self/oom_score_adj" to "0": write /proc/self/oom_score_adj: permission denied
I0515 18:44:38.915652       7 server.go:536] write /proc/self/oom_score_adj: permission denied
```
I'll send out a PR that should hopefully fix this (and thus the "Preempting" hollow-nodes).

- hollow-proxy is consuming too much CPU. This seems to be mainly due to all the rules and chains creation inside the syncProxyRules function before it tries to `RestoreAll` the iptables. This is something we have to live with, if we want to pay the cost of having real proxier that saves/restores tables. However, one small optimization that can be done here is to make the `Save` operation do real work for fake IPtables. This would help avoid some unnecessary string appends in `writeLine` function calls. I'll send out a PR making this change (that might slightly help us).

**Comment by shyamjvs** [comment]
If the OOM'ing problem still persists after the above change, then we should consider writing/reading the tables to a file rather than keeping them in memory. This would increase I/O operations, but make hollow-proxy use more memory only while syncing, and also that's how iptables works.

**Comment by shyamjvs** [comment]
Implemented the above said comment as well in PR #45856

**Comment by wojtek-t** [comment]
@shyamjvs - we are working on changing proxier so that we are not doing so many syncProxyRules calls. So it's not only we can do here to be honest, from your description.

Regarding iptables Save operation - I agree that should slightly help.

Regarding OOM-scores - I don't think this is something we want to do. The problem is that in a real cluster where we have kube-proxy, kubelet and a bunch of user pods, kube-proxy is indeed much more important than those user pods.
In kubemark, we have **only** hollow-kubelets and hollow-nodes, and all the pods are critical. So this won't solve any of our problems - it seems to be setup issue.

**Comment by shyamjvs** [comment]
> @shyamjvs - we are working on changing proxier so that we are not doing so many syncProxyRules calls. So it's not only we can do here to be honest, from your description.

Sorry I should've been more clear. I was talking about optimizations in hollow-proxy as compared to real proxy (to make them more similar). The optimizations you are working on would improve both :)

> Regarding OOM-scores - I don't think this is something we want to do. The problem is that in a real cluster where we have kube-proxy, kubelet and a bunch of user pods, kube-proxy is indeed much more important than those user pods.

SGTM, thanks for explaining. However I have a slight concern in the context of OOM score (commented here https://github.com/kubernetes/kubernetes/pull/45854#issuecomment-301724638)

**Comment by wojtek-t** [comment]
@shyamjvs - can you please smartly revert this PR to fix kubemark-scale, before we solve the problem in kube-proxy? Thanks!

**Comment by wojtek-t** [comment]
By "smartly revert" I mean probably something like just temporarily passing "FakeProxier" instead of "Proxier" to the ProxyServer (and leave other changes that you did as they are - they will be useful in the future).

**Pull request merged**
