### PR TITLE
Reordered getting started guides by provider name.

### PR DESCRIPTION
**Pull request by ashcrow**
Ordered getting started guide README.md by IaaS Provider.

### CODE REVIEW

**Comment by erictune** [comment]
I'd like better-supported guides to appear higher in the list.

**Comment by ashcrow** [comment]
How about ordered by the notes (via uses/tested with) and support level?

**Comment by erictune** [comment]
I think that would be fine.  
Suggest following order (which is what I think you had in mind)
Primary key: Commercial > Project > Community
Secondary key:  Tested-with version

**Comment by ashcrow** [comment]
Updated with the new order.

**Pull request merged**
