### PR TITLE
fix vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructuredscheme staticcheck

### PR DESCRIPTION
**Pull request by habibrosyad**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fixes `vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructuredscheme` staticcheck errors:

```sh
vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructuredscheme/scheme.go:32:2: var codecs is unused (U1000)
```

**Which issue(s) this PR fixes**:

Part of #92402

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by habibrosyad** [comment]
Hmm, checked several recent PRs, and most of them fail for this:
/test pull-kubernetes-integration

**Comment by lavalamp** [comment]
/lgtm
/approve

Thanks!

(looks like integration test is having troubles running etcd, not related to this change)

**Comment by habibrosyad** [comment]
@lavalamp could you /lgtm again?

**Pull request merged**
