### PR TITLE
Fix winkernel proxy regression failing to query v1 endpoints created by dockershim CNI

### PR DESCRIPTION
**Pull request by daschott**
### What happened?

https://github.com/kubernetes/kubernetes/pull/109124 has introduced a regression for Kubernetes clusters using dockershim as the runtime that invoke CNIs using the v1 HNS APIs. Winkernel proxier is unable to retrieve endpoints due to this hcsshim call failing to retrieve v1 HNS endpoints: https://pkg.go.dev/github.com/Microsoft/hcsshim@v0.8.22/hcn#ListEndpointsOfNetwork

This causes service proxy rules to not be created, as local endpoints would not be found.

Clusters using the containerD runtime and CNIs that leverage HCN APIs are not impacted.

Source:
We have noticed this is failing on our dockershim related tests: https://testgrid.k8s.io/sig-windows-1.22-release#aks-engine-windows-dockershim-1.22
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-1-22-windows/1536521484288135168

### What did you expect to happen?

Service proxy rules are created for all expected services

### How can we reproduce it (as minimally and precisely as possible)?

Create a Kubernetes cluster with Windows and dockershim runtime

### Anything else we need to know?

This issue does not occur on clusters with the containerD runtime (that use v2 CNI workflow creating HCN endpoints instead of HNS endpoints) 

### Kubernetes version

1.23, 1.22

### Cloud provider

Reproduced on Azure, but all are impacted.

### OS version

Windows Server 2019

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

Dockershim

### Related plugins (CNI, CSI, ...) and versions (if applicable)

Azure CNI + dockershim. Any CNI creating v1 HNS endpoints will be impacted.

### CODE REVIEW

**Comment by daschott** [comment]
/kind bug
/sig windows
Putting a hold since dockershim is deprecated, but fix is needed for v1.23 and v1.22, waiting on guidance from release team if fix is desired in upstream branches.
/hold

**Comment by daschott** [comment]
related fixes in v1.22 and v1.23: #110592, #110590

**Comment by feiskyer** [comment]
@daschott do we need it in 1.24 as well?

**Comment by daschott** [comment]
@feiskyer I don't think this is required in v1.24 and not in main since dockershim is deprecated in these releases and there are no reasons to create v1 HNS endpoints anymore without dockershim.

We brought this up during SIG-Windows community today and could not see other concerns raised because CNI already moved to HCN v2 APIs in order to support containerD. 

I am converting this into a draft PR while the backports https://github.com/kubernetes/kubernetes/pull/110702 and https://github.com/kubernetes/kubernetes/pull/110701 are being reviewed in case there are any last-minute concerns. Planning to close this once the backport gets merged.

**Comment by daschott** [comment]
cc @jsturtevant

**Comment by jsturtevant** [comment]
/close
Discussed at sig-windows, newer versions of cni's are using hns v2 apis and we want new CNIs and other components using the newer apis going forward. We went ahead with the backports in https://github.com/kubernetes/kubernetes/pull/110702 and https://github.com/kubernetes/kubernetes/pull/110701

**Pull request closed without merging**
