### PR TITLE
kubelet: remove useless comment code for node status

### PR DESCRIPTION
**Pull request by xigang**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by xigang** [comment]
@haircommander This PR needs approval, thank you.

**Comment by haircommander** [comment]
@SergeyKanzhelev @mrunalp @tallclair @yujuhong PTAL

**Pull request merged**
