### PR TITLE
add a clean code for TestCanSupport

### PR DESCRIPTION
**Pull request by guangxuli**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34389)

### CODE REVIEW

**Comment by guangxuli** [comment]
@saad-ali ptal,thanks.

**Comment by guangxuli** [comment]
@saad-ali can you take a look for this PR? Thanks.

**Comment by saad-ali** [comment]
Sorry I've been back logged on PRs. Taking a look.

**Comment by saad-ali** [comment]
@k8s-bot ok to test

**Comment by saad-ali** [comment]
@guangxuli What motivated this change. Were you running into an issues?

+@pmorie who wrote the original code: is the directory clean up done somewhere else, or is it assumed that cleanup is not necessary since it is a temp dir?

I see this pattern across multiple files--`pkg/volume/git_repo/git_repo_test.go`, `pkg/volume/secret/secret_test.go`), and even other locations in this config map file--whatever we decide to do we should make sure to apply it consistently.

**Comment by guangxuli** [comment]
@saad-ali there is no issue for this PR, and in theory it doesn't matter but we should do the right thing and remove the temp files since we know we can. what do you think? :)  yeah, some locations also need a  modification. thanks.

**Comment by saad-ali** [comment]
Ack, that's fine. Go ahead and update the other occurrences as well.

**Comment by guangxuli** [comment]
@saad-ali done, PTAL, thanks.

**Comment by saad-ali** [comment]
You're gonna hate me, but can I ask you to also make the change in `pkg/volume/git_repo/git_repo_test.go` and `pkg/volume/secret/secret_test.go`?

**Comment by guangxuli** [comment]
@saad-ali I know that, but I made a mistake, I had't pull all changes. sorry, :) I will do that right now.

**Comment by saad-ali** [comment]
@k8s-bot gci gke e2e test this

**Comment by saad-ali** [comment]
Thanks!

**Comment by saad-ali** [comment]
LGTM

**Pull request merged**
