### PR TITLE
Fix typos in markdown

### PR DESCRIPTION
**Pull request by calvinballing**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

I ran cspell locally in order to clean up various typos throughout the codebase.  This PR is specifically focused on fixing typos found in markdown.

This was broken off of the larger https://github.com/kubernetes/kubernetes/pull/121268 to make reviewing/merging easier.

#### Which issue(s) this PR fixes:

Fixes # n/a
I can make an issue for this if needed.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by swatisehgal — COMMENTED** [review]
/triage accepted 
/priority important-longterm

/lgtm

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Pull request merged**
