### PR TITLE
Flocker docs update

### LINKED ISSUE #19338: flocker example needs needs more detail
We found that some users coming to the `examples/flocker` document were getting a little confused. It should include more detail about where to install Flocker services, how to set environment variables, that you can create volumes now with Docker CLI and give more detail in example including how to use it with a spec that includes a replication controller.

### PR DESCRIPTION
**Pull request by wallnerryan**
fixes https://github.com/kubernetes/kubernetes/issues/19338

### CODE REVIEW

**Comment by wallnerryan** [comment]
seeing travis is failing, but unclear how to fix this
```
FAIL: changes needed but not made due to --verify
/home/travis/gopath/src/github.com/kubernetes/kubernetes/examples/ is out of date. Please run hack/update-generated-docs.sh
!!! Error in hack/verify-generated-docs.sh:28
  '"${KUBE_ROOT}/hack/after-build/verify-generated-docs.sh" "$@"' exited with status 1
Call stack:
  1: hack/verify-generated-docs.sh:28 main(...)
Exiting with status 1
make: *** [verify] Error 1
```
happy to fix whatever is failing with a pointer as why its failing

**Comment by jlowdermilk** [comment]
Hi @wallnerryan, thanks for the pr. Two things: 1) please squash to a single commit. 2) to fix the travis complaint run
```
hack/update-generated-docs.sh
```

**Comment by gmarek** [comment]
```
!!! Error in ./hack/../hack/verify-generated-docs.sh:28
  '"${KUBE_ROOT}/hack/after-build/verify-generated-docs.sh" "$@"' exited with status 1
```

@wallnerryan - please squash commits and run `hack/update-generated-docs.sh` as @jlowdermilk asked.

**Comment by wallnerryan** [comment]
Hi @jlowdermilk and @gmarek thanks for taking a look. FWIW i am having issues running `hack/update-generated-docs.sh` because i am getting the error.

```
!! Error in hack/update-generated-docs.sh:26
  '"${KUBE_ROOT}/hack/build-go.sh" cmd/gendocs cmd/genkubedocs cmd/genman cmd/genbashcomp cmd/mungedocs' exited with status 1
Call stack:
  1: hack/update-generated-docs.sh:26 main(...)
Exiting with status 1
```

I dont have a full go dev env for these changes, would i need this in order to run the script?

**Comment by wallnerryan** [comment]
squashed commits in meantime

**Comment by wallnerryan** [comment]
looks like go 1.4.2 needed update to 1.5. Running the script now and will update PR soon

**Comment by wallnerryan** [comment]
@jlowdermilk @gmarek squashed and ran script. Looks like build state is

```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

any suggestions?

**Comment by jlowdermilk** [comment]
Try rebasing onto master, running `make clean` then `hack/update-generated-docs.sh`.

**Comment by wallnerryan** [comment]
@jlowdermilk @gmarek rebased and ran hack again, things seem to be OK

**Comment by jlowdermilk** [comment]
Thanks @wallnerryan, lgtm.

**Pull request merged**
