### PR TITLE
fix format error in CHANGELOG-1.12.md

### PR DESCRIPTION
**Pull request by linyouchong**
**What this PR does / why we need it**:
fix format error in CHANGELOG-1.12.md

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
https://github.com/kubernetes/kubernetes/pull/69199 has this change + some other fixes too.

**Comment by linyouchong** [comment]
@neolit123 @nikhita 
Thanks!

**Pull request closed without merging**
