### PR TITLE
using cobra commands for test/images

### PR DESCRIPTION
**Pull request by hanxiaoshuai**
**What this PR does / why we need it**:
using cobra commands for MasqTestProxy
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ixdy** [comment]
I'm not really familiar with cobra commands. What does this do?

**Comment by hanxiaoshuai** [comment]
@ixdy Package cobra is a commander providing a simple interface to create powerful modern CLI interfaces. once we switch everything over to Cobra commands, we can go back to calling utilflag.InitFlags() (by removing its pflag.Parse() call). 
cc@deads2k

**Comment by ixdy** [comment]
is there an issue tracking this effort?

**Comment by hzxuzhonghu** [comment]
@ixdy Does not find a issue, but @deads2k know this.

**Comment by hzxuzhonghu** [comment]
@ixdy  as #58684 merged, all components `kube-controller-manager kube-proxy` all using combra. this is the last one blocking the call of `utilflag.InitFlags()` widespread.

I open a pr #60179 follow up this one.

**Comment by ixdy** [comment]
@hzxuzhonghu can you also please update the `VERSION` file for each of these images? or is this expected to have no user-visible changes?

**Comment by hzxuzhonghu** [comment]
no user visible changes

**Pull request closed without merging**
