### PR TITLE
add prerelease lifecycle tags to policy

### PR DESCRIPTION
**Pull request by deads2k**
This adds the lifecycle annotation tags matching https://github.com/kubernetes/enhancements/blob/master/keps/sig-architecture/1635-prevent-permabeta/README.md 

The clock is set for deprecation in 1.22 and removal of beta levels in 1.25.

/kind cleanup
/priority important-soon
@kubernetes/sig-node-api-reviews 

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
@kubernetes/sig-node-api-reviews @kubernetes/sig-scheduling-api-reviews @kubernetes/sig-apps-api-reviews for PDB and eviction

@kubernetes/sig-auth-api-reviews for PSP

**Comment by deads2k** [comment]
@mortent I got pointed to https://github.com/kubernetes/enhancements/pull/1502 .  I wanted to make sure you saw this PR aligning the API lifecycle tags to the beta policy.

**Comment by mortent** [comment]
@deads2k Thanks for the heads up.

**Comment by jessehu** [comment]
Hi @deads2k @liggitt, since PSP API will be deprecated in 1.22 and removed 1.25, what's the replacement and plan? Thanks.

**Comment by jeanluclariviere** [comment]
I would also be curious to know what will be replacing PSPs

**Comment by enj** [comment]
@jessehu @jeanluclariviere see https://github.com/kubernetes/website/pull/20789 for the details.

cc @tallclair

**Pull request merged**
