### PR TITLE
cluster/: ensure retention period on pre-existing staging buckets

### PR DESCRIPTION
**Pull request by BenTheElder**
#### What type of PR is this?

/kind cleanup
/sig testing

#### What this PR does / why we need it:

Ensures we avoid excessive retention on CI staging buckets used to upload builds for bringing up GCE clusters.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

follow up for https://github.com/kubernetes/kubernetes/pull/115634/files#r1122203091

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by justinsb** [comment]
I actually thought we already had a relatively short retention period here.

I agree that this shouldn't break anything prod, and if it breaks anything we want to know.  (I suspect it might break e.g. some job pinned to an old and rarely built branch of kOps, but having those get surfaced is probably no bad thing)

**Comment by BenTheElder** [comment]
```
$ gsutil retention get gs://kubernetes-release-pull
gs://kubernetes-release-pull/ has no Retention Policy.
```

however it's only like 5.11TB, and I thoguht we had per-project staging but I'm not seeing that in the logs.

this PR was meant to be a cheap fix that took time proportional to the savings. it's not worth digging into further right now.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/116222

retention policy (required to keep) != lifecycle policy (TTL rules)

**Pull request closed without merging**
