### PR TITLE
Automated cherry pick of #65799: Escape illegal characters in remote extra keys

### PR DESCRIPTION
**Pull request by dekkagaijin**
Cherry pick of #65799 on release-1.9.

#65799: Escape illegal characters in remote extra keys

```release-note
action required: the API server and client-go libraries have been fixed to support additional non-alpha-numeric characters in UserInfo "extra" data keys. Both should be updated in order to properly support extra data containing "/" characters or other characters disallowed in HTTP headers.
```

### CODE REVIEW

**Comment by dekkagaijin** [comment]
@liggitt ptal

**Comment by dekkagaijin** [comment]
FYI this cherry pick required me to use bytes.Buffer instead of a strings.Builder (introduced in go1.10), which shouldn't be a meaningful change.

**Comment by dekkagaijin** [comment]
@liggitt lgtm?

**Comment by dekkagaijin** [comment]
@mbohlool ping

**Comment by dekkagaijin** [comment]
Looks like we're running into quota issues, I'll re-run the test again later when there might be less contention.

**Comment by dekkagaijin** [comment]
@liggitt @mbohlool ping

**Comment by dekkagaijin** [comment]
@mbohlool @liggitt ping. Is there a kubernetes.slack channel I can poke for these kind of things?

**Comment by liggitt** [comment]
yeah, #sig-release is good

**Comment by mbohlool** [comment]
> Is there a kubernetes.slack channel I can poke for these kind of things?

for 1.9 you can ping me directly on slack but the fact that I will set the schedule for the patch release myself and start looking at PRs a good amount of time before that would make sure your PR will go into the next patch release unless you think the review of your PR may take longer than expected which you should ping me sooner. You are always welcome to ping me anyway.

**Comment by dekkagaijin** [comment]
@mbohlool fair enough. Is where anywhere where this release schedule is posted? I don't have any way to knowing when a PR will be reviewed in a batch vs. when it needs nagging.

**Comment by dekkagaijin** [comment]
@mbohlool SGTM, thanks. This isn't an urgent patch, so I'll trust that it'll get picked up during the next 1.9 release process :)

**Pull request merged**
