### PR TITLE
Ensure the ptr is pointing to reflect.Slice in ExtractList

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by thockin** [comment]
LGTM

Is this just caution, or did it manifest in some way?

**Comment by mfojtik** [comment]
@thockin the code in this PR is not ready yet, I just found that if items is *[]runtime.Object, it prints the error... still debugging...

**Comment by mfojtik** [comment]
@thockin done :-) to answer the question, this is just a caution, there is no use-case for this in the code (neither in openshift codebase).

**Comment by mfojtik** [comment]
@smarterclayton @csrwng fyi.

**Comment by csrwng** [comment]
LGTM

**Pull request merged**
