### PR TITLE
cleanup unused code for kubeapiserver

### PR DESCRIPTION
**Pull request by 249043822**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

remove unused code

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

NONE
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by deads2k** [comment]
this is fallout from removing the insecure serving option.

/lgtm
/approve

**Comment by 249043822** [comment]
@deads2k I have fixed tests failure, need re-labled lgtm, thanks

**Pull request merged**
