### PR TITLE
Automated cherry pick of #94987 upstream release 1.19

### PR DESCRIPTION
**Pull request by zshihang**
**What type of PR is this?**

/kind cleanup
/kind failing-test

**What this PR does / why we need it**:

cherrypick https://github.com/kubernetes/kubernetes/pull/94987, which would partially fix upgrade test. see https://github.com/kubernetes/kubernetes/issues/94487.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
Needed to get upgrade tests working again

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by zshihang** [comment]
@cpanato please remove do-not-merge/cherry-pick-not-approved to unblock the merge.

**Pull request merged**
