### PR TITLE
Refine extractFileSpec

### PR DESCRIPTION
**Pull request by hezhizhen**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/priority backlog
/kind cleanup

**Comment by hezhizhen** [comment]
@soltysh Fixed the failed test.

**Comment by hezhizhen** [comment]
@soltysh Passed all the tests.

**Comment by hezhizhen** [comment]
Ping @soltysh

**Comment by hezhizhen** [comment]
Any updates?

**Pull request merged**
