### PR TITLE
Speed up pkg/controller/endpointslice unit tests

### PR DESCRIPTION
**Pull request by wzshiming**
**What type of PR is this?**
/kind cleanup
/kind flake

**What this PR does / why we need it**:
35s -> 13s

**Which issue(s) this PR fixes**:

xref #98486

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by wzshiming** [comment]
```
5s: 0 runs so far, 0 failures
10s: 0 runs so far, 0 failures
15s: 8 runs so far, 0 failures
20s: 8 runs so far, 0 failures
25s: 8 runs so far, 0 failures
30s: 16 runs so far, 0 failures
35s: 16 runs so far, 0 failures
40s: 17 runs so far, 0 failures
45s: 24 runs so far, 0 failures
50s: 24 runs so far, 0 failures
55s: 32 runs so far, 0 failures
1m0s: 32 runs so far, 0 failures
1m5s: 32 runs so far, 0 failures
1m10s: 40 runs so far, 0 failures
1m15s: 40 runs so far, 0 failures
1m20s: 42 runs so far, 0 failures
1m25s: 48 runs so far, 0 failures
1m30s: 48 runs so far, 0 failures
1m35s: 56 runs so far, 0 failures
1m40s: 56 runs so far, 0 failures
1m45s: 56 runs so far, 0 failures
1m50s: 64 runs so far, 0 failures
1m55s: 64 runs so far, 0 failures
2m0s: 70 runs so far, 0 failures
2m5s: 72 runs so far, 0 failures
2m10s: 72 runs so far, 0 failures
2m15s: 80 runs so far, 0 failures
2m20s: 80 runs so far, 0 failures
2m25s: 83 runs so far, 0 failures
2m30s: 88 runs so far, 0 failures
2m35s: 88 runs so far, 0 failures
2m40s: 96 runs so far, 0 failures
2m45s: 96 runs so far, 0 failures
2m50s: 96 runs so far, 0 failures
2m55s: 104 runs so far, 0 failures
3m0s: 104 runs so far, 0 failures
3m5s: 109 runs so far, 0 failures
3m10s: 112 runs so far, 0 failures
3m15s: 112 runs so far, 0 failures
3m20s: 120 runs so far, 0 failures
3m25s: 120 runs so far, 0 failures
3m30s: 124 runs so far, 0 failures
3m35s: 128 runs so far, 0 failures
3m40s: 128 runs so far, 0 failures
3m45s: 136 runs so far, 0 failures
3m50s: 136 runs so far, 0 failures
```

**Comment by robscott** [comment]
Thanks for fixing this @wzshiming! @mborsz can you confirm that there should be no issues running these tests in parallel?

**Comment by robscott** [comment]
These tests all look very safe to run in parallel to me, thanks again for fixing this!

/lgtm
/approve

**Pull request merged**
