### PR TITLE
fix force deleted pod termination failure avoiding new pod starting

### PR DESCRIPTION
**Pull request by 249043822**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

This pr try to fix the two general scenarios as below:
1. force deleted pod terminal, `syncTerminatingPod` failed as the cri runtime timeout
   1) a pod was force deleted with `terminationGracePeriodSeconds `0
   2) kubelet started to call `deletePod` to terminate the pod
   3) the pod was removed from pod manager
   4) pod worker called `syncTerminatingPod` to kill pod
   5) `syncTerminatingPod` returned error as cri runtime call timeout
   6)  the pod was put to workQueue and expected to retry to sync again
   7)  `syncLoopIteration` ignored the pod's sync as it was not in pod manager again
   8)  pod worker for this pod halted and could not work again and it's status would be `Terminating ` forever
   9) housekeeping could not cleanup the runtimepod as it's status was `Terminating`
2. static pod terminal, `syncTerminatedPod` failed as wait umout volumes timeout or other errors, it prevents the new static pod starting
   1) modified a static pod manifest like changing log level
   2) kubelet started to call `deletePod` to terminate the pod
   3) the pod was removed from pod manager
   4) kubelet received a ADD for the same pod full name
   5) podworker could not start the new pod as the terminal for the old pod  with the same full name did not finished
   6) pod worker called `syncTerminatingPod` to kill pod and the containers for old pod were stopped
   7)  pod worker called `syncTerminatedPod` to finish cleanup
   8) `syncTerminatedPod` returned error as wait umout volumes timeout or other errors
   9)  the pod was put to workQueue and expected to retry to sync again
   10)  `syncLoopIteration` ignored the pod's sync as it was not in pod manager again
   11)  pod worker for this pod halted and could not work again and it's status would be not finished forever
   12) housekeeping could not remove the pod worker forever
    
#### Which issue(s) this PR fixes:

Fixes #https://github.com/kubernetes/kubernetes/pull/112998#issuecomment-1277474134
https://github.com/kubernetes/kubernetes/pull/112998#issue-1405418195
#### Special notes for your reviewer:
/cc @smarterclayton 
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by smarterclayton** [comment]
Please summarize the scenario that causes this failure in the PR description and commit message.  Specifically, the sequence of operations and the observed failure mode.

**Comment by 249043822** [comment]
> Please summarize the scenario that causes this failure in the PR description and commit message. Specifically, the sequence of operations and the observed failure mode.

@smarterclayton Done
Actually both the failures we met before,  but the related logs not exist now, I can only provide the analysis for these

**Comment by smarterclayton** [comment]
For the first issue, that's a bug in the housekeeping loop.  We should split that out into a separate fix with the title

> Force deleted pods may fail to terminate if the container runtime experiences an error during termination

The bug is that the kubelet config loop is responsible for triggering the pod worker to progress and the handlePodCleanups method does not send that trigger for pods that have been removed from config.  Currently https://github.com/kubernetes/kubernetes/blob/99360e5dbc26c60c773a9e8b0d2f95960e49e284/pkg/kubelet/kubelet_pods.go#L1126-L1150 skips over those pods, when it should not.  The fix is to remove the switch statement and always send a short Kill update on any running pod that is not in the pod.  The bug is fairly severe - force deletion can lead to orphaned pods that are never terminated and fully released. @bobbypage FYI.  We should have an e2e/integration/unit test (in order of preference) that reproduces the issue

I believe the fix for the first issue will fix the second issue.

The current change doesn't fix the issues in the necessary spot because we have to ensure force deleted pods transition through each phase correctly.

**Comment by smarterclayton** [comment]
#113091 / #113093 identified another related issue - if syncTerminatedPod exits, and the pod is force deleted, no further updates are delivered to the pod worker.  This is a scenario that HandlePodCleanups must be responsible for.  However, unlike dangling runtime pods we have no pod structure to pass into the pod worker (gone from config + runtime), and UpdatePod considers it an error if Pod or RunningPod is missing.  However, proper cleanup of the pod *requires* syncTerminatedPod to exit cleanly (responsible for removing handlers), so the fix must be in HandlePodCleanups and involve notifying the pod worker via UpdatePod, without the presence of a pod.  Which means a slightly more dramatic change to UpdatePod...

**Comment by smarterclayton** [comment]
Now that #113145 has merged please let me know if you see an issue still.

**Comment by bart0sh** [comment]
@249043822 please, address https://github.com/kubernetes/kubernetes/pull/113065#issuecomment-1463230389 and rebase or close this PR, thanks.

**Pull request closed without merging**
