### PR TITLE
allow kubectl proxy to handle specified reject methods and default to…

### PR DESCRIPTION
**Pull request by suyogbarve**
What this PR does / why we need it:
"kubect proxy" command had a bug and was not supporting feature to reject http methods
--reject-methods='POST,PUT,PATCH'
this was due to missing filter for RejectMethods in kubectl/cmd/proxy.go
This PR adds the desired flag, however to retain the current behaviour of "kubectl proxy" the Default Rejected methods are changed from 'POST,PUT,PATCH' to '^$' i.e. none.

Issue not created and no existing issue found

### CODE REVIEW

**Comment by suyogbarve** [comment]
@eparis : This PR is in lieu of https://github.com/kubernetes/kubernetes/pull/44794 which contains changes as per your suggestions

**Comment by eparis** [comment]
@k8s-bot ok to test
/release-note-none
/lgtm

but would like to hear @brendandburns confirm...

**Comment by suyogbarve** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by eparis** [comment]
maybe @smarterclayton will come /approve this

**Comment by suyogbarve** [comment]
@fabianofranz @liggitt @pwittrock any thoughts?

**Comment by fabianofranz** [comment]
Looks good.

**Pull request merged**
