### PR TITLE
Update links for the user and troubleshooting guides for the build cop

### PR DESCRIPTION
**Pull request by roberthbailey**
to copy-paste from the oncall documentation.

### CODE REVIEW

**Comment by idvoretskyi** [comment]
Please , file the same PR to kubernetes.github.io repo.

**Comment by roberthbailey** [comment]
@idvoretskyi what would I change in the kubernetes.github.io repo repo? This doc points our users with support questions to the kubernetes.github.io repo but I'm not actually updating any troubleshooting instructions in this document.

**Comment by idvoretskyi** [comment]
@roberthbailey my fail, that's ok.

**Comment by roberthbailey** [comment]
@idvoretskyi great, I was thinking I'd missed something. :)

**Pull request merged**
