### PR TITLE
Change fluentd-gcp monitoring to use metrics exposed by SD plugin

### PR DESCRIPTION
**Pull request by crassirostris**
Following https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/pull/135, make fluentd-gcp expose metrics in Prometheus registry and use them instead of counting records in the pipeline.

/cc @piosz @igorpeshansky

```release-note
Fluentd-gcp DaemonSet exposes different set of metrics.
```

### CODE REVIEW

**Review by igorpeshansky — APPROVED** [review]
LGTM :shipit:

**Comment by piosz** [comment]
/lgtm
/approve
I assume @igorpeshansky reviewed the configuration in depth.

**Comment by igorpeshansky** [comment]
@piosz Yes, I've reviewed the configs.

**Comment by piosz** [comment]
@igorpeshansky thx!

**Pull request merged**
