### PR TITLE
Untie ES version from paths

### PR DESCRIPTION
**Pull request by mulloymorrow**

### CODE REVIEW

**Comment by satnam6502** [comment]
@mulloymorrow thanks for this PR. Any reason for the change? This close to our 1.0 deadline I am loathed to change anything that is broken and not keen on cosmetic changes.

**Comment by mulloymorrow** [comment]
I signed it!

**Comment by mulloymorrow** [comment]
yes just a cosmetic change. I will close this PR. One question though, I'm having trouble building elasticsearch_discovery.go. I'd like to create my own elasticsearch image. The dockerfile example seems to be expecting a binary called  "elasticsearch_discovery". Anyway you can release this binary?

**Comment by satnam6502** [comment]
Here is a compromise. Why don't we work on improving the Dockerfile -- but not update the actual image until the next required change?

**Comment by satnam6502** [comment]
So one good change would be to add a variable like `ELASTICSEARCH` which is set to the exact name of the elasticsearch file with suffix so this does not need to be repeated. Then install in a dir which dos not mention the version name. How about that?

**Comment by satnam6502** [comment]
Does the `Makefile` not work for you?

**Comment by satnam6502** [comment]
Specifically https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/es-image/Makefile

**Comment by satnam6502** [comment]
Ah! You are talking about the example!

**Comment by satnam6502** [comment]
Then you need thishttps://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/elasticsearch/Makefile

**Comment by mulloymorrow** [comment]
yes this fails: https://github.com/GoogleCloudPlatform/kubernetes/issues/9214

**Comment by satnam6502** [comment]
`make all`

**Pull request closed without merging**
