### PR TITLE
prevent kubelet from killing containers when pod's finalizers not empty

### LINKED ISSUE #73584: Containers deleted while pod still having finalizers set
**What happened**:
Pod enters `Terminating` state and containers get deleted even if finalizers still exist on pod.

**What you expected to happen**:
Pods should stay in `Running` state and containers should stay up while finalizers still exist on pod.

**How to reproduce it (as minimally and precisely as possible)**:
```console
$ kubectl apply -f- <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: finalizer-pod
  finalizers:
    - test.example.com/my-finalizer
spec:
  containers:
  - name: nginx
    image: nginx
EOF
$ kubectl delete pod finalizer-pod --timeout 1s
pod "finalizer-pod" deleted
$ kubectl get pod
NAME            READY     STATUS        RESTARTS   AGE
finalizer-pod   0/1       Terminating   0          74s
```

**Anything else we need to know?**:
We need this in order to do gracefull failovers when pods get deleted. We cannot use container lifecycle hooks because we need to coordinate the failover across containers and pods. 

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"10ecc6db83fd47a93eb0940e2e4434f2b0a5c3ec", GitTreeState:"clean", BuildDate:"2018-08-15T21:23:47Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `Docker for Mac`
- OS (e.g. from /etc/os-release):
```
PRETTY_NAME="Docker Desktop"
```
- Kernel (e.g. `uname -a`):
```
Linux e10fa4332909 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by Wenfeng-GAO**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
In our use case, the pod's ip is directly registered to our slb/soa service,  so we should make sure that ip is successfully picked out of slb/soa service before shutting down the docker runtime. 

However, graceperiodseconds and prestophooks are not able to provide a strong guarantee for our use case.

This pr prevent kubelet from killing containers when pod's finalizers not empty, and preserve pod's status to `Terminating` as it's being killed.

**Which issue(s) this PR fixes**:

Fixes #73584

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
prevent containers being stopped when delete pod if pod has finalizers
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
/uncc

Hi! In the issue, it looks like @liggitt commented that this functionality was working as intended. Is there reason to believe that is no longer true?

**Comment by ayanamist** [comment]
I think it's not a backward-compatible change.
We now use finalizer to help CNI manage IP: add "cni-allocated" finalizer to a Pod when cni allocation completes, and this finalizer will keep kubelet invoking CNI release if previous CNI release failed after Pod deletion starts.
If this PR is effective, now containers are always running if Pod has finalizer, and CNI release will never be invoked by kubelet, and "cni-allocated" finalizer will never be removed, which make a deadlock.

**Comment by Wenfeng-GAO** [comment]
I think the root cause is Kubelet  lacks the ability to solve some certain problems. 

- The use case I mentioned above expects Kubelet to not stop containers until pod's ip has successfully dropped out of our slb service, which I think is a common or reasonable demand. So I think finalizers is a way to solve this kind of problem if Kubelet supports
- On the other hand, the use case of finalizers as @ayanamist mentioned, from my point of view, is because Kubelet failed to handle CNI release conflict issues

We just use the mechanism of finalizers to find a walk-around solution. 

And yes, it's not a backward-compatible change.

**Comment by liggitt** [comment]
Since this change is not backwards compatible, I'm going to go ahead and close it. I would recommend opening an issue and tagging `/sig network` to work through possible approaches to solving the problems you are encountering in a compatible way.

/close

**Pull request closed without merging**
