### PR TITLE
Remove unused package //pkg/util/normalizer

### PR DESCRIPTION
**Pull request by rosti**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

With the merger of #79335, the only user of `k8s.io/kubernetes/pkg/util/normalizer` stopped using it and, therefore, made this package redundant. Hence we can now remove it altogether.

**Which issue(s) this PR fixes**:

NONE

**Special notes for your reviewer**:

/assign @thockin 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by thockin** [comment]
This is still flagged WIP - ping me when that is removed

**Comment by rosti** [comment]
@thockin this should be ready for a review now

**Review by fabriziopandini — APPROVED** [review]
@rosti thanks for the cleanup!
/approve
/lgtm

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
