### PR TITLE
upgrade kustomize to v4.1.3

### PR DESCRIPTION
**Pull request by gautierdelorme**
Signed-off-by: Gautier Delorme <gautier.delorme@gmail.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This upgrades kustomize to depend on kustomize [v4.1.3](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.1.3). Especially it allows k/k to drop some `go-openapi` dependencies (specifically it removes the vendored `go-openapi/spec` module).

#### Does this PR introduce a user-facing change?

```release-note
Upgrade functionality of `kubectl kustomize` as described at https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.1.3
```

### CODE REVIEW

**Comment by liggitt** [comment]
/lgtm
/approve

now to get https://github.com/kubernetes/kubernetes/issues/102145 in place to make sure this doesn't creep back in

**Comment by liggitt** [comment]
/hold cancel

needs rebase, sorry

**Comment by gautierdelorme** [comment]
@liggitt no worry, rebased 👍

**Pull request merged**
