### PR TITLE
Update Calico cpva to v0.8.3

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Ref https://github.com/kubernetes-sigs/cluster-proportional-vertical-autoscaler/pull/36

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm

**Comment by ialidzhikov** [comment]
@justaugustus , can you assist with `/milestone v1.20`?

**Pull request merged**
