### PR TITLE
Incremented the elasticsearch version

### PR DESCRIPTION
**Pull request by IvanovOleg**
**What this PR does / why we need it**:
Applies changes implemented in:
https://github.com/kubernetes/kubernetes/pull/65627

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by coffeepac** [comment]
@IvanovOleg would prefer a release note of NONE . no need for this to show up in the 1.12 release notes

**Comment by IvanovOleg** [comment]
`kubelet, stg-orion-k8s-agentpool1-2  Failed to pull image "k8s.gcr.io/elasticsearch:v6.2.5": rpc error: code = Unknown desc = failed to resolve image "k8s.gcr.io/elasticsearch:v6.2.5": k8s.gcr.io/elasticsearch:v6.2.5 not found`
It looks like somebody should build it.

**Comment by IvanovOleg** [comment]
Is anybody going to build this image?

**Comment by loburm** [comment]
I'll build it, but next time we shouldn't bump version in the Makefile and in manifests file at the same file. Because otherwise we are going to have build in not healthy state.

**Comment by loburm** [comment]
Image should be available.

**Pull request merged**
