### PR TITLE
Update klog dependency

### PR DESCRIPTION
**Pull request by mtaufen**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Update klog dependency to include recent changes, notably opening existing files with O_APPEND instead of O_TRUNC.

**Does this PR introduce a user-facing change?**:
```release-note
Pre-existing log files are now opened with O_APPEND, instead of O_TRUNC. This helps prevent losing logs when components crash-loop, and also enables external log rotation utilities to truncate log files in-place without components extending log files to their pre-truncation sizes on subsequent writes.
```

### CODE REVIEW

**Comment by mtaufen** [comment]
@dims @liggitt looks like https://github.com/kubernetes/klog/pull/39 changed --logtostderr default from false to true. I'm worried this could break existing logging configurations because when set, it disables logs from being sent to files, even if --log_file is set (--alsologtostderr is the correct flag for enabling both file and stderr logging).

**Comment by mtaufen** [comment]
Discussion on what to revert was resolved and merged in https://github.com/kubernetes/klog/pull/50.
Updated this PR to include those changes.
@liggitt @dims PTAL.
The O_APPEND change is critical for log rotation on Windows, where we will use an external log rotation utility to truncate files in-place. Without O_APPEND, writers immediately extend the file back to its pre-truncation size.

**Comment by dims** [comment]
/approve 

@mtaufen thanks for driving this!

**Comment by mtaufen** [comment]
Had to run update-staging-godeps. Re-adding label after update.

**Pull request merged**
