### PR TITLE
Update dashboard and metrics-scraper image

### LINKED ISSUE #105503: The dashboard display that the server could not find the requested resource (get ingresses.extensions) when list ingress ressources
#### What happened:
I use local-up-cluster.sh script to install kubernetes and kubernetes-dashboard is installed. I login dashboard and list ingress resources. The web get Unknown error (404) and display "the server could not find the requested resource (get ingresses.extensions)"

#### What you expected to happen:
I can list ingress resources.

#### How to reproduce it (as minimally and precisely as possible):
- Set environment parameter KUBE_ENABLE_CLUSTER_DASHBOARD is `true`
- Run local-up-cluster.sh script

#### Environment:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.0-alpha.2.211+a53e2eaeaba064-dirty", GitCommit:"a53e2eaeaba064309dceca2dc27f3ac09c6375b0", GitTreeState:"dirty", BuildDate:"2021-10-05T07:28:08Z", GoVersion:"go1.17.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.0-alpha.2.211+a53e2eaeaba064-dirty", GitCommit:"a53e2eaeaba064309dceca2dc27f3ac09c6375b0", GitTreeState:"dirty", BuildDate:"2021-09-25T03:52:10Z", GoVersion:"go1.17.1", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by gujun4990**
Kubernetes use networking.k8s.io/v1 API for Ingress resource, so
the dashboard need to adapt this. Therefore update dashboard to 2.3.1
and update metrics-scraper to 1.0.7.

Signed-off-by: jun.gu <gujun4990@outlook.com>

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Kubernetes use networking.k8s.io/v1 API for Ingress resource, so
the dashboard need to adapt this. Therefore update dashboard to 2.3.0
and update metrics-scraper to 1.0.6.

#### Which issue(s) this PR fixes:

Fixes #105503

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by floreks** [comment]
You can bump versions to `v2.3.1` and `v1.0.7`.

**Comment by gujun4990** [comment]
> You can bump versions to `v2.3.1` and `v1.0.7`.

ok

**Comment by floreks** [comment]
metrics scraper should be [v1.0.7](https://github.com/kubernetes-sigs/dashboard-metrics-scraper/releases/tag/v1.0.7)

**Comment by dims** [comment]
@floreks can we close this out since we decided to drop the dashboard addon?

**Comment by floreks** [comment]
@dims +1 from me

/close

**Pull request closed without merging**
