### PR TITLE
Drop hyperkube use from local-up-cluster.sh

### PR DESCRIPTION
**Pull request by dims**
We should just use the regular binaries used everywhere else and drop
hyperkube. Only the local-up-cluster related CI jobs use hyperkube at
the moment, so this will help deprecate and eliminate hyperkube at least
from the main kubernetes repository.

Change-Id: Ic53a4b56420565f546ac75be6cc23d214766c057

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/lgtm
/hold
(for review)

btw, should we add a release note for this type of change?

**Comment by neolit123** [comment]
found this in the logs:
```
I0811 17:25:36.825] make: Leaving directory '/go/src/k8s.io/kubernetes'
W0811 17:26:10.410] 2019/08/11 17:26:10 process.go:153: Running: pkill hyperkube
W0811 17:26:10.440] 2019/08/11 17:26:10 process.go:155: Step 'pkill hyperkube' finished in 29.608797ms
W0811 17:26:10.440] 2019/08/11 17:26:10 local.go:225: unable to kill hyperkube processes: error during pkill hyperkube: exit status 1
```

**Comment by dims** [comment]
@neolit123 looks like we have to fix that in test-infra repo:
https://github.com/kubernetes/test-infra/blob/master/kubetest/local.go#L223

**Comment by dims** [comment]
@neolit123 we don't ship this and we don't tell users to use this (devs only). so we should be good here.

**Comment by neolit123** [comment]
yes, agreed.

**Comment by tpepper** [comment]
@dims do you intend to cherry picking this to the three patch branches?  Won't k/test-infra/kubetest run the older branches' local-cluster-up.sh and expect a hyperkube?

**Comment by neolit123** [comment]
> Won't k/test-infra/kubetest run the older branches' local-cluster-up.sh and expect a hyperkube?

AFAIK, in terms of our CI, not if the appropriate versioned kubekins image (that hosts kubetest) is used). but this change will break someone that tries to use a standalone recent (e.g. build from test-infra master) kubetest against a older branch of k/k.

**Comment by neolit123** [comment]
my suggestion on the mailing list was - announce hyperkube deprecation and give it at least 1 release for removal. but given hyperkube is used in production we should probably apply the GA deprecation rules on it.

**Pull request merged**
