### PR TITLE
Revert "scheduler: align with ctrl-managers and apiservers, add https+auth in options"

### PR DESCRIPTION
**Pull request by wojtek-t**
This PR completely broke scheduler performance:
https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-5000

Pod startup time exploded to ~20s.

Ref: https://github.com/kubernetes/kubernetes/pull/60372

### CODE REVIEW

**Comment by wojtek-t** [comment]
@deads2k @aveshagarwal @timothysc @k82cn

**Comment by sttts** [comment]
On it.

**Comment by shyamjvs** [comment]
/lgtm

(So we don't block on the fix)

**Comment by deads2k** [comment]
@wojtek-t @shyamjvs have you looked to see if it's as simple as a QPS option getting dropped?  It seems pretty aggressive to push this through so quickly five days after the cause merged.

**Comment by wojtek-t** [comment]
> @wojtek-t @shyamjvs have you looked to see if it's as simple as a QPS option getting dropped? It seems pretty aggressive to push this through so quickly five days after the cause merged.

from @sttts on slack:
```
componentconfigs with `--kube-api-qps=100 --kube-api-burst=100`  driving the scheduler are unchanged after that PR. that would have been too simple.
```

it's 5 days due to kubecon and noone really looking into stuff...

**Comment by shyamjvs** [comment]
+1. I would vote for reverting (so we don't mask any other regressions that
may potentially happen in the meanwhile). Re-reverting shouldn't be too
hard later on IMO once we sit down and root-cause the issue. It'll also let
us debug this more peacefully.

Feel free to disagree if you think the fix is too trivial and can be made
right away.

**Comment by shyamjvs** [comment]
If we are fairly confident we have a fix that would work, then we can
probably get that in straight away.

Otherwise, there's a kubemark-5000 presubmit (that I added a while ago)
which can be optionally triggered on the PR if needed :)

**Comment by sttts** [comment]
It looks like the scheduler is restarting every few minutes (https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/985/artifacts/kubemark-5000-master/kube-scheduler.log) and tries repeatedly to re-listen on the insecure port:
```
insecure_serving.go:47] Serving healthz insecurely on [::]:10251
```
No idea yet whether both is connected. The later is visible on a local cluster as well.

**Comment by wojtek-t** [comment]
> It looks like the scheduler is restarting every few minutes (https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kubemark-gce-scale/985/artifacts/kubemark-5000-master/kube-scheduler.log) and tries repeatedly to re-listen on the insecure port:

If that's the case, I'm pretty sure this is the reason of that - restart means that it's not scheduling pods that are being created in the meantime.

**Pull request merged**
