### PR TITLE
Automated cherry pick of #62076: Add support to ingest log entries to Stackdriver against new

### PR DESCRIPTION
**Pull request by qingling128**
Cherry pick of #62076 on release-1.10.

#62076: Add support to ingest log entries to Stackdriver against new

### CODE REVIEW

**Comment by MaciekPytel** [comment]
/approve 
For cluster/gce. I'm also approving cherry-pick. 

@kawych @x13n can one of you lgtm? You understand this much better than I do.

**Comment by qingling128** [comment]
Rebased off `release-1.10` to include https://github.com/kubernetes/kubernetes/pull/62174 so that we are using the latest Metadata Agent.

**Comment by qingling128** [comment]
@MaciekPytel @x13n - Hi, is there any known issue going on with the e2e test suite? Seems it's complaining about these scp commands:

```
W0409 22:11:36.143] scp: /var/log/fluentd.log*: No such file or directory
W0409 22:11:36.143] scp: /var/log/node-problem-detector.log*: No such file or directory
W0409 22:11:36.143] scp: /var/log/startupscript.log*: No such file or directory
W0409 22:11:36.147] ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
```

It does not seem to be related to the changes to this PR, but it's blocking the actual tests from running.

Any thoughts?

**Comment by qingling128** [comment]
For the reference, in the [past runs](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/62076/pull-kubernetes-e2e-gce/29450/?log#log) when this PR was merged to master, we were able to allocate nodes after a few retries:

```
I0406 16:13:48.184] .....Kubernetes cluster created.
W0406 16:13:48.285] Using master: e2e-29450-master (external IP: 35.202.69.159)
I0406 16:13:48.385] Cluster "k8s-jkns-pr-gce-etcd3_e2e-29450" set.
I0406 16:13:48.475] User "k8s-jkns-pr-gce-etcd3_e2e-29450" set.
I0406 16:13:48.620] Context "k8s-jkns-pr-gce-etcd3_e2e-29450" created.
I0406 16:13:48.766] Switched to context "k8s-jkns-pr-gce-etcd3_e2e-29450".
I0406 16:13:48.909] User "k8s-jkns-pr-gce-etcd3_e2e-29450-basic-auth" set.
I0406 16:13:48.912] Wrote config for k8s-jkns-pr-gce-etcd3_e2e-29450 to /workspace/.kube/config
I0406 16:13:49.749] 
I0406 16:13:49.749] Kubernetes cluster is running.  The master is running at:
I0406 16:13:49.749] 
I0406 16:13:49.749]   https://35.202.69.159
I0406 16:13:49.750] 
I0406 16:13:49.750] The user name and password to use is located in /workspace/.kube/config.
I0406 16:13:49.750] 
I0406 16:13:49.795] Validating gce cluster, MULTIZONE=
W0406 16:13:49.895] ... calling validate-cluster
W0406 16:13:49.895] Project: k8s-jkns-pr-gce-etcd3
W0406 16:13:49.896] Network Project: k8s-jkns-pr-gce-etcd3
W0406 16:13:49.896] Zone: us-central1-f
W0406 16:13:54.031] No resources found.
I0406 16:13:54.132] Waiting for 5 ready nodes. 0 ready nodes, 0 registered. Retrying.
W0406 16:14:09.210] No resources found.
I0406 16:14:09.310] Waiting for 5 ready nodes. 0 ready nodes, 0 registered. Retrying.
W0406 16:14:24.481] No resources found.
I0406 16:14:24.582] Waiting for 5 ready nodes. 0 ready nodes, 0 registered. Retrying.
I0406 16:14:40.720] Waiting for 5 ready nodes. 0 ready nodes, 5 registered. Retrying.
I0406 16:14:56.359] Waiting for 5 ready nodes. 3 ready nodes, 5 registered. Retrying.
I0406 16:15:11.699] Found 5 node(s).
I0406 16:15:11.997] NAME                          STATUS                     ROLES     AGE       VERSION
I0406 16:15:11.998] e2e-29450-master              Ready,SchedulingDisabled   <none>    41s       v1.11.0-alpha.0.2161+5c69fd68205206
I0406 16:15:11.998] e2e-29450-minion-group-05wc   Ready                      <none>    36s       v1.11.0-alpha.0.2161+5c69fd68205206
I0406 16:15:11.999] e2e-29450-minion-group-5sn4   Ready                      <none>    42s       v1.11.0-alpha.0.2161+5c69fd68205206
I0406 16:15:11.999] e2e-29450-minion-group-hchd   Ready                      <none>    38s       v1.11.0-alpha.0.2161+5c69fd68205206
I0406 16:15:12.000] e2e-29450-minion-group-jvxh   Ready                      <none>    34s       v1.11.0-alpha.0.2161+5c69fd68205206
```

**Comment by qingling128** [comment]
So I managed to run the e2e tests in my own GCP project following https://github.com/kubernetes/community/blob/master/contributors/devel/e2e-tests.md.

It turned out to be blocked by the same issue. The interesting thing is that even though the e2e tests failed due to the issue spinning up nodes (after a dozens of retries, it claimed failure):
```
Waiting for 4 ready nodes. 0 ready nodes, 0 registered. Retrying.
No resources found.
```

I was able to see the created nodes in Stackdriver UI and ssh'ed to them.

screen shot 2018-04-10 at 2 30 31 pm
screen shot 2018-04-10 at 2 30 08 pm
screen shot 2018-04-10 at 2 43 44 pm

Maybe the logic to check whether a GCE node is created is off?

**Comment by qingling128** [comment]
Just did a diff of the related files between master and release-1.10 branch. Seems the `ENABLE_NODE_JOURNAL` support is in master but not release-1.10. This line (https://github.com/kubernetes/kubernetes/pull/62076/files#diff-6e3b476b9225d1213dc6ad13e453fc16R2081) sneaked into this cherry pick. Because we restructured the method, it showed up as a new change and not a part of the cherry-pick conflicts and I missed it.

Removed the line and re-triggering the tests now.

**Comment by qingling128** [comment]
Now it's failing for:

```
I0410 20:12:09.939] Checking/setting cloud tools: OK
I0410 20:12:09.939] 
I0410 20:12:09.939] push-build.sh::common::set_cloud_binaries(): /google-cloud-sdk/bin/gcloud --quiet auth configure-docker
I0410 20:12:13.751] ERROR: (gcloud.auth) Invalid choice: 'configure-docker'.
I0410 20:12:13.751] This command is available in one or more alternate release tracks.  Try:
I0410 20:12:13.751]   gcloud alpha auth configure-docker
I0410 20:12:13.751]   gcloud beta auth configure-docker
I0410 20:12:13.792] Releasing Kubernetes requires gsutil and gcloud. Please download,
I0410 20:12:13.796] install and authorize through the Google Cloud SDK:
I0410 20:12:13.800] 
I0410 20:12:13.804] https://developers.google.com/cloud/sdk/
I0410 20:12:13.806] 
```

It's a known issue reported an hour ago at https://github.com/kubernetes/test-infra/issues/7633. It was triggered by https://github.com/kubernetes/release/pull/515 that was merged 2 hours ago.

**Comment by qingling128** [comment]
The PR has been [reverted](https://github.com/kubernetes/release/pull/546) temporarily. Trying the tests again.

**Comment by MaciekPytel** [comment]
It looks like the tests were globally broken for k8s today (for 2 separate reasons): https://github.com/kubernetes/test-infra/issues/7295,
https://github.com/kubernetes/kubernetes/issues/62356. The fix for the latter just got merged, so probably they should start passing soon.

**Comment by qingling128** [comment]
@MaciekPytel - Got it. Thanks for the heads up. Fingers crossed.

**Comment by qingling128** [comment]
@MaciekPytel - Seems the tests have passed the point where they failed before. Looks promising. We would still need a /lgtm label.

**Comment by qingling128** [comment]
Tests passed. Pending a /lgtm label. Could someone help with that? @MaciekPytel @x13n @piosz @kawych

**Comment by MaciekPytel** [comment]
Re-applying lgtm label after rebase as we need to close 1.10.1.

**Comment by qingling128** [comment]
Thanks @MaciekPytel ! Is this now waiting for the submit queue to pick it up?

**Comment by qingling128** [comment]
The failures are related to another known issue of the test framework. A request to revert the related change has been made by the test infra team. Standing by for further notice when it's recovered.

**Comment by BenTheElder** [comment]
see: https://github.com/kubernetes/kubernetes/issues/62356#issuecomment-380327060

**Comment by BenTheElder** [comment]
we're well past staging, seeing this though.
```
I0411 05:25:00.759] +++ Logging using Fluentd to gcp
W0411 05:25:01.025] /go/src/k8s.io/kubernetes/kubernetes/cluster/../cluster/../cluster/gce/util.sh: line 818: METADATA_CONCEALMENT_NO_FIREWALL: unbound variable
W0411 05:25:01.062] /go/src/k8s.io/kubernetes/kubernetes/cluster/../cluster/../cluster/gce/util.sh: line 818: CUSTOM_KUBE_DASHBOARD_BANNER: unbound variable
W0411 05:25:01.064] /go/src/k8s.io/kubernetes/kubernetes/cluster/../cluster/../cluster/gce/util.sh: line 818: LOGGING_STACKDRIVER_RESOURCE_TYPES: unbound variable
W0411 05:25:01.066] /go/src/k8s.io/kubernetes/kubernetes/cluster/../cluster/../cluster/gce/util.sh: line 818: STACKDRIVER_METADATA_AGENT_URL: unbound variable
```

**Comment by qingling128** [comment]
@BenTheElder - That warning is fine. The passed test runs have them as well.

**Comment by BenTheElder** [comment]
> @BenTheElder - That warning is fine. The passed test runs have them as well.

maybe we should avoid reading unbound variables though? 🤷‍♂️

**Comment by qingling128** [comment]
>maybe we should avoid reading unbound variables though? 🤷‍♂️

Oh, yup. That for sure. I mainly meant it's not a sign of the tests failing again. I'm creating a ticket to fix that in a separate PR.

**Comment by qingling128** [comment]
Finally! 😁 All tests passed. 🍾 🍾 🍾

**Comment by qingling128** [comment]
@MaciekPytel - This is finally merged now. Can we still make sure this PR is included in the patch release?

**Pull request merged**
