### PR TITLE
Manually cherry-pick 4379bbd as it is part of a larger PR

### PR DESCRIPTION
**Pull request by mbohlool**
The commit 4379bbd fixes a bug in openapi spec that resulted in some of the type missing group-version-kind extension. That is specificly serious for the projects that vendor kubernetes in (like minikube). It results in them not having GVKs at all (https://github.com/kubernetes/minikube/issues/1996).

```release-note
Bugfix: OpenAPI models may not get group-version-kind extension if kubernetes is vendored in another project (e.g. minikube). Kubectl 1.8 needs this extension to work with those projects.
```
@wojtek-t

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Seems related: 

FAILED   hack/make-rules/../../hack/verify-federation-openapi-spec.sh	130s

**Comment by caesarxuchao** [comment]
lgtm after the test fixed.

**Comment by mbohlool** [comment]
/test pull-kubernetes-e2e-gce-bazel

Anybody has any idea why this test is failing? looking at log I only see timeout error, but I see it passes for other PRs.

**Comment by wojtek-t** [comment]
@mbohlool - can you please add a user-friendly release-note for this?

**Comment by mbohlool** [comment]
@wojtek-t Done. Also I am not sure why pull-kubernetes-e2e-gce-bazel is not passing. Do you think it is this PR's fault or it is consistently failing for 1.7 PRs?

**Pull request merged**
