### PR TITLE
add fuzzer for kube-proxy config to do scheme test

### PR DESCRIPTION
**Pull request by m1093782566**
**What this PR does / why we need it**:

add fuzzer for kube-proxy config to do scheme test

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
@m1093782566 FYI, this is dup of https://github.com/kubernetes/kubernetes/pull/55986
/cc @sttts

**Comment by cmluciano** [comment]
Is this componentconfig currently in the "do not fuzz list"? If not, why do we need to change the default values that are being injected?

**Comment by m1093782566** [comment]
> Is this componentconfig currently in the "do not fuzz list"? If not, why do we need to change the default values that are being injected?

Sorry, I am not following...

**Pull request closed without merging**
