### PR TITLE
Remove dangling shell functions

### PR DESCRIPTION
**Pull request by joonas**
**What this PR does / why we need it**:

This is clean up for shell functionality that was left over from when something was first added and subsequently removed, but didn't include cleaning up all of the logic they references.

**Special notes for your reviewer**:

I traced back the functions to when they were added and had their references removed, so I thought I'd share that for context:

* `kube::golang::current_platform` was added in 5d33ce46cc, but never ended up being used. My understanding is that this is due to having more or less the same logic available in `kube::golang::host_platform`, which is what's being used.

* `kube::util::gen-analytics` was added in 553f9f822b and had the use of it removed in 902ffd53bc when docs 

* `kube::util::analytics-link` was added in 553f9f822b and had the use of it removed in ffcc6cadb0

* `kube::util::get_random_port` was added in 5d08dcf837 and superseded by `kubectl proxy --port=0` in 22b43d8f82

* `kube::util::test_host_port_free` was added in 5d08dcf837 and superseded by `kubectl proxy --port=0` in 22b43d8f82

I should also note that [`kube::golang::unset_platform_envs()`](https://github.com/kubernetes/kubernetes/blob/e8e72a44444d9ded58bcba13d650c98dab2cb465/hack/lib/golang.sh#L301-L307) was introduced in 5d33ce46cc and is currently unused, but was referenced in 9848d6cc8d and subsequently removed in 38690ff7a7. If that's something worth including here, I'd be happy to add that also.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
Looks good. Giving others time to speak up.

**Comment by cblecker** [comment]
/ok-to-test
/approve no-issue

I'm totally aboard the removing unused code train :) 🚂

**Comment by joonas** [comment]
Went ahead and rebased since #47699 fixed up some typos in `hack/lib/golang.sh` that lead to a conflict, anything else I could do to help move things along? :)

**Pull request merged**
