### PR TITLE
Eliminate racy scale command from resource-alias test.

### LINKED ISSUE #22128: integration flake: casandra failure
test-cmd.sh failed with the following:

    12:01:47 service "cassandra" created
    12:01:47 
    12:01:47 FAIL!
    12:01:47 Get all -l'app=cassandra' {{range.items}}{{range .metadata.labels}}{{.}}:{{end}}{{end}}
    12:01:47   Expected: cassandra:cassandra:cassandra:
    12:01:47   Got:      cassandra:cassandra:cassandra:cassandra:
    12:01:47 (B
    12:01:47 1535 ./hack/test-cmd.sh

https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-test-go/8954/build-log.txt

### PR DESCRIPTION
**Pull request by bgrant0607**
Fixes #22128.

cc @mqliang @janetkuo @kargakis @bprashanth

### CODE REVIEW

**Comment by jayunit100** [comment]
Ah yes, I found the same: scaling should be decoupled from Cassandra tests which are complicated enough asis, until it's totally robust

**Comment by bgrant0607** [comment]
@k8s-bot test this issue: #22134

**Comment by jayunit100** [comment]
this patch makes sense, it makes two cassandra resources and then verifies that there are at least two labels.  so lgtm thanks!

**Comment by bgrant0607** [comment]
Thanks, @jayunit100. Merging to mitigate flakes.

**Pull request merged**
