### PR TITLE
Host is not used in fun GetConnectionInfo

### PR DESCRIPTION
**Pull request by zhengguoyong**
The var Host is not used in fun GetConnectionInfo, del it.

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM

**Comment by zhengguoyong** [comment]
e2e fail, would you kindly help show me the log?  i cannot access it.
thanks very much.
@wojtek-t

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by zhengguoyong** [comment]
i just found that the parameter(host string) is not used in fun GetConnectionInfo,
so i will del it.   @liggitt @wojtek-t 
If you will use this, i will close this PR. :)   @gmarek
thanks all.

**Comment by liggitt** [comment]
yeah, #16153 is almost to LGTM, and will start using that param

**Pull request closed without merging**
