### PR TITLE
[Proposal][Prototype]Add local disk space as a resource for scheudling

### PR DESCRIPTION
**Pull request by hex108**
In this PR, I make a prototype for local disk space scheduling to make sure I'm in the right direction. The proposal doc(included in this PR) is at https://github.com/hex108/kubernetes/blob/local_disk/docs/proposals/local-disk-scheduling.md.

> Local disk is useful for containers to store data. It is faster to write data to local disk(mounted into container) than to container. And a container crashing does not remove a pod from a node, so data in local disks is safe across container crashing.

> Now `emptyDir` supports local disk, however it does not take disk space into consideration. Then there might be some out of disks errors if containers use too mush disk space. PR [Sticky emptydir proposal](https://github.com/kubernetes/kubernetes/pull/30044) is discussing it. PR [LocalDisk Volume Proposal](https://github.com/kubernetes/kubernetes/pull/30499) make another proposal to support local disk. PV/PVC and dynamic provision suggeted in both PRs.

> In this proposal, we'd like to provide another way: add local disk space as a resource for scheduling. Kubelet reports its local disks information, and scheduler takes disk space into consideration if user requests local disk space in spec. There are mainly two reasons for us to add local disk space for scheduling. First, if we treat local disk as a resource like CPU/Memory, it will be more convinient for user to request local disk. Second, if we let kubelet to allocate local disk, scheduler could not know whether there is enough disk space for kubelet to allocate, then kublete might fail to allocate when it tries to launch pod.

### CODE REVIEW

**Comment by davidopp** [comment]
cc/ @kubernetes/sig-node  @kubernetes/sig-scheduling

**Comment by davidopp** [comment]
@hex108 I would suggest putting the proposal into a separate PR, and getting that accepted first, before submitting a PR with the implementation.

**Comment by davidopp** [comment]
It's not clear to me that the "Local disk request" you described is needed, assuming we implement sticky emptyDir (#30044). PersistentVolume lets you specify
```
capacity:
    storage: XXX
```
so it seems that the "request" part is already taken care of.

I agree we need Kubelet to compute and report free disk space, and scheduler to implement disk space predicate, but I think the amount requested is already implicitly specified.

**Comment by davidopp** [comment]
I guess I would suggest that you write up a proposal with the minimum extra functionality you'd need to add to #30044 in order to do disk space scheduling. In other wordds, assume #30044 has already been implemented as described, and explain what more we need.

**Comment by hex108** [comment]
Thanks @davidopp for the suggestion. I'll report another PR for the proposal.

**Comment by vishh** [comment]
@hex108 I'm working on a design for local disk management as well. Would you like to collaborate?

**Comment by hex108** [comment]
@vishh Very glad to know it and work with you.

**Pull request closed without merging**
