### PR TITLE
Automated cherry pick of #23445 #27310

### PR DESCRIPTION
**Pull request by ikehz**
Cherry pick of #23445 #27310 on on release-1.1.

Part of fix for #26594.

### CODE REVIEW

**Comment by ihmccreery** [comment]
@ncdc Can you please confirm you're okay with this commit being contributed to Google?  Thanks!

**Comment by ihmccreery** [comment]
@k8s-bot test this again please issue #27451.

**Comment by ihmccreery** [comment]
@k8s-bot test this again please issue #27451.

**Comment by ihmccreery** [comment]
@k8s-bot unit test this again please issue #27462.

**Comment by roberthbailey** [comment]
@k8s-bot unit test this again please issue #27462.

**Comment by roberthbailey** [comment]
Weird error:
```
Checking out Revision eb7f7177459919cd439b46cfe78b43faec5a87a8 (origin/pr/27392/merge)
 > /usr/bin/git config core.sparsecheckout # timeout=10
 > /usr/bin/git checkout -f eb7f7177459919cd439b46cfe78b43faec5a87a8 # timeout=20
FATAL: Could not checkout eb7f7177459919cd439b46cfe78b43faec5a87a8
hudson.plugins.git.GitException: Could not checkout eb7f7177459919cd439b46cfe78b43faec5a87a8
```

**Comment by roberthbailey** [comment]
@k8s-bot unit test this issue: #IGNORE

**Comment by roberthbailey** [comment]
@k8s-bot unit test this issue: #18895

**Pull request merged**
