### PR TITLE
Use reflect.DeepEqual to replace slicesEqual

### LINKED ISSUE #50952: Use util function to replace self-contained function
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature
/kind feature

**What happened**:
In some files, i found that there are many self-contained function, whose feature is as same as some util function. Obviously, they are redundant. 

**What you expected to happen**:
Use util function to replace self-contained function

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/kubernetes/kubernetes/issues/50952

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm.

@vishh this is a simple fix. probably should get merged.

**Comment by zhangxiaoyu-zidif** [comment]
@jingxu97  Hi, could you add "/approve no-issue"
 Thanks a lot

**Comment by xiang90** [comment]
@jingxu97 @saad-ali can you approve this with no issue again? thanks!

**Comment by zhangxiaoyu-zidif** [comment]
@vishh
please add /approve no-issue
thanks very much

**Pull request merged**
