### PR TITLE
kubectl get jobs printing fix

### PR DESCRIPTION
**Pull request by erictune**

### CODE REVIEW

**Comment by erictune** [comment]
jenkins failure can't possibly be related.

**Comment by mikedanese** [comment]
LGTM but  cc @JanetKuo

**Comment by a-robinson** [comment]
Merging as 1.1 is approaching quickly. @JanetKuo, if you have any feedback, we can also get that in quickly

**Comment by mikedanese** [comment]
@erictune was this chery-picked?

**Comment by janetkuo** [comment]
@mikedanese looks like it's not https://github.com/kubernetes/kubernetes/blob/release-1.1/pkg/kubectl/resource_printer.go#L726

**Pull request merged**
