### PR TITLE
kubectl edit: Wire show-managed-fields flag

### LINKED ISSUE #1322: Kubectl edit: `--show-managed-fields` does nothing
### What happened?

I edited an object like so `kubectl edit svc my-server --show-managed-fields` and epected to see managed fields but didn't. When using `kubectl get -oyaml --show-managed-fields` they are shown

### What did you expect to happen?

See managed fields

### How can we reproduce it (as minimally and precisely as possible)?

`kubectl edit some-type some-name --show-managed-fields`

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
$ k version --client --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.3
Kustomize Version: v4.5.7
# paste output here
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by ardaguclu**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Currently, `kubectl edit` does not support `--show-managed-fields` flag and there is no provided option for users can see managed fields in their editor via `kubectl edit`.

This PR wires `--show-managed-fields` flag in JSONYamlPrinter. But managed fields will be only shown as read only. If there is any changes detected on these fields, kubectl edit will return error.

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubectl/issues/1322

#### Does this PR introduce a user-facing change?

```release-note
kubectl edit will support --show-managed-fields flag but it will not allow any changes on managed fields.
```

### CODE REVIEW

**Comment by ardaguclu** [comment]
@henvic @apelisse  what do you think about this change?

**Comment by ardaguclu** [comment]
/hold 
for review.

**Comment by henvic** [comment]
@ardaguclu, this change looks good to me. Maybe add a test to check the following scenarios?

* When it's kept the same
* When it's removed
* When it's changed

**Comment by ardaguclu** [comment]
@apelisse could you PTAL this patch if you have a moment?. Thanks.

**Comment by KnVerey** [comment]
@ardaguclu can you please add the tests @henvic requested?

**Comment by ardaguclu** [comment]
@henvic @KnVerey thanks for reviewing this PR. I'm planning to go back to this PR to add testing, however that will not happen in soon. That's why, I'm closing this PR to unblock people who might want to work on this issue.

/close

**Pull request closed without merging**
