### PR TITLE
migrate test/integration/apiserver/apiserver_test.go to structured lo…

### PR DESCRIPTION
**Pull request by thickforest**
…gging

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by cndoit18 — COMMENTED** [review]
Same comment
https://github.com/kubernetes/kubernetes/pull/102429#pullrequestreview-671738214

**Comment by neolit123** [comment]
/close
let's decided on structured logging for test/ before sending the PRs.

**Pull request closed without merging**
