### PR TITLE
Revert "Merge pull request #92312 from Sh4d1/kep_1860"

### PR DESCRIPTION
**Pull request by Sh4d1**
This reverts commit ef16faf409b7aec6b2171ec3e4a39c3f3f68c030, reversing
changes made to 2343b8a68bacd5f641f3cfa2be07329c140a6446.

**What type of PR is this?**:
/kind bug

**What this PR does / why we need it**:
As per https://github.com/kubernetes/enhancements/issues/1860#issuecomment-725028455 this reverts #92312

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
The whole PR will be reverted, I don't think the internal parts will be needed before the code freeze. 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cc @thockin @liggitt @jeremyrickard

### CODE REVIEW

**Comment by thockin** [comment]
@Sh4d1 Are we going to revisit this?

**Comment by thockin** [comment]
1.22 is locked and loaded now.  1.23 ?

**Comment by Sh4d1** [comment]
Sorry, tough summer! I also missed your review on https://github.com/kubernetes/kubernetes/pull/101027 :( 

I'm going to take a break from Kubernetes starting from September, so not sure I'll be able to follow up on this one. 
If someone wants to continue this:
- https://github.com/kubernetes/kubernetes/pull/101027 needs to be finished
- https://github.com/kubernetes/kubernetes/pull/97681 needs to be rebased once the one above is merged, and then with Tim's comment it should be pretty easy to get it working :) 

I'll see if I can at least address the comments on the first one, but can't guarantee anything!

**Pull request merged**
