### PR TITLE
Kubelet: only check podUID when it is actually set

### LINKED ISSUE #38188: Kubectl attach failed: pod not found
Meta from https://github.com/kubernetes/frakti/issues/54.

When enabled frakti with kubelet, `kubectl attach` failed with errors:

```
# cluster/kubectl.sh get pods
NAME                      READY     STATUS    RESTARTS   AGE
busybox-983667326-wlbt7   1/1       Running   0          21m
# cluster/kubectl.sh attach busybox-983667326-wlbt7
If you don't see a command prompt, try pressing enter.
error: unable to upgrade connection: pod busybox-983667326-wlbt7_default not found
```

Kubelet logging:

```
I1206 08:36:42.017475   31088 server.go:741] POST /attach/default/busybox-983667326-wlbt7/busybox?error=1&output=1: (3.672091ms) 500
goroutine 1433 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).recordStatus(0xc42017cc40, 0x1f4)
	/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/httplog/log.go:219 +0xbb
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc42017cc40, 0x1f4)
	/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/httplog/log.go:198 +0x35
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteHeader(0xc420bb8f00, 0x1f4)
	/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:200 +0x41
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteErrorString(0xc420bb8f00, 0x1f4, 0xc4212ae180, 0x2d, 0xc421956180, 0x1f)
	/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:180 +0x46
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Response).WriteError(0xc420bb8f00, 0x1f4, 0x5b36f60, 0xc421326e10, 0x0, 0xc420bdc07d)
	/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/response.go:165 +0x78
k8s.io/kubernetes/pkg/kubelet/server.(*Server).getAttach(0xc4200a35e0, 0xc4201fac00, 0xc420bb8f00)
	/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:611 +0x1fb
k8s.io/kubernetes/pkg/kubelet/server.(*Server).(k8s.io/kubernetes/pkg/kubelet/server.getAttach)-fm(0xc4201fac00, 0xc420bb8f00)
	/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:323 +0x3e
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch.func6(0xc4201fac00, 0xc420bb8f00)
	/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:267 +0x3e
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc4201faea0, 0xc4201fac00, 0xc420bb8f00)
	/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/filter.go:21 +0x95
k8s.io/kubernetes/pkg/kubelet/server.(*Server).InstallAuthFilter.func1(0xc4201fac00, 0xc420bb8f00, 0xc4201faea0)
	/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:249 +0x151
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc4201faea0, 0xc4201fac00, 0xc420bb8f00)
	/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/filter.go:19 +0x68
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc420f78000, 0x5b5b920, 0xc42017cc40, 0xc421779d10)
	/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:269 +0x996
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).(k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.dispatch)-fm(0x5b5b920, 0xc42017cc40, 0xc421779d10)
	/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:120 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4204ce610, 0x5b5b920, 0xc42017cc40, 0xc421779d10)
	/usr/local/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc420e69c50, 0x5b5b920, 0xc42017cc40, 0xc421779d10)
	/usr/local/go/src/net/http/server.go:2022 +0x7f
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc420f78000, 0x5b5b920, 0xc42017cc40, 0xc421779d10)
	/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:287 +0x4d
k8s.io/kubernetes/pkg/kubelet/server.(*Server).ServeHTTP(0xc4200a3590, 0x5b5b920, 0xc42017cc40, 0xc421779d10)
	/gopath/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/server/server.go:740 +0x10e
net/http.serverHandler.ServeHTTP(0xc4203ad600, 0x5b619a0, 0xc42121ed00, 0xc421779d10)
	/usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420924300, 0x5b646a0, 0xc4216de1c0)
	/usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2293 +0x44d

logging error output: "pod busybox-983667326-wlbt7_default not found"
```

This is because the `podUID` param in [GetAttach()](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L1342) could be empty string:

```
ws.
		Path("/attach")
	ws.Route(ws.GET("/{podNamespace}/{podID}/{containerName}").
		To(s.getAttach).
		Operation("getAttach"))
	ws.Route(ws.POST("/{podNamespace}/{podID}/{containerName}").
		To(s.getAttach).
		Operation("getAttach"))
	ws.Route(ws.GET("/{podNamespace}/{podID}/{uid}/{containerName}").
		To(s.getAttach).
		Operation("getAttach"))
	ws.Route(ws.POST("/{podNamespace}/{podID}/{uid}/{containerName}").
		To(s.getAttach).
		Operation("getAttach"))
```

### PR DESCRIPTION
**Pull request by feiskyer**
Fixes #38188.

cc/ @timstclair @yujuhong

### CODE REVIEW

**Comment by feiskyer** [comment]
@k8s-bot unit test this

**Review by timstclair — APPROVED** [review]
LGTM, thanks!

**Comment by feiskyer** [comment]
@k8s-bot cvm gce e2e test this
@k8s-bot gci gce e2e test this
@k8s-bot gce etcd3 e2e test this

**Comment by feiskyer** [comment]
Made a rebase to check whether etcd3 e2e test could be passed.

**Comment by feiskyer** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
