### PR TITLE
Replace deprecate aws functions

### PR DESCRIPTION
**Pull request by sergeylanzman**
1. Replace deprecate aws functions
2. Delete unused functions
3. Rename variables
```release-note
NONE
```

### CODE REVIEW

**Comment by justinsb** [comment]
/retest

Odd flake pulling binaries (?)

**Comment by jsafrane** [comment]
@justinsb you must /approve no-issue

**Comment by justinsb** [comment]
/approve no-issue

Sorry for messing up the approval

**Pull request closed without merging**
