### PR TITLE
Fix Kubelet /logs endpoint

### LINKED ISSUE #15222: /logs Kubelet endpoint does not work.
When going to
```
https://XXX.XXX.XXX.XXX/api/v1/proxy/nodes/kubernetes-minion-cc6s/logs/kubelet.log
```

I'm getting `404: Page Not Found` response. Plain `logs/` correctly prints all *available* log files.

cc @dchen1107 @yujuhong @davidopp

### PR DESCRIPTION
**Pull request by dchen1107**
Fix #15222

### CODE REVIEW

**Comment by dchen1107** [comment]
cc/ @lavalamp I tested this through proxy and node locally, both are works.

**Comment by dchen1107** [comment]
This is a regression caused by #12811, and 1.1 branch is broken too.

**Comment by lavalamp** [comment]
thanks!

**Comment by lavalamp** [comment]
We should add a quick e2e so it doesn't happen again.

**Comment by dchen1107** [comment]
@lavalamp Agreed on e2e test. Standalone kubelet conformance test suite is targeted for 1.2 :-)

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Pull request merged**
