### PR TITLE
Graduate DaemonSet API to v1beta1, enable it by default.

### PR DESCRIPTION
**Pull request by madhusudancs**
This is based on @janetkuo's PR #20517 that enables Deployments by default. So only last two commits need review.

cc @bgrant0607 @janetkuo @kargakis @mikedanese @davidopp

### CODE REVIEW

**Comment by bgrant0607** [comment]
Why does this need to include the Deployment PR? Let's just make them independent.

**Comment by madhusudancs** [comment]
> Why does this need to include the Deployment PR? Let's just make them independent.

@bgrant0607 Same reason as here - https://github.com/kubernetes/kubernetes/pull/21131#issuecomment-183475523

Rebased and removed the dependencies. PTAL.

**Comment by bgrant0607** [comment]
ENABLE_DAEMONSETS could also be removed from config-default.sh scripts (grep for it).

This needs to be rebased, but will need to be rebased again once the ReplicaSet PR merges, probably.

**Comment by bgrant0607** [comment]
From discussion:

* Re-combine with #21131
* Remove ENABLE_DEPLOYMENT from config-default.sh scripts
* Remove `[Feature:DaemonSet]` and `[Feature:Deployment]`from e2e tests

cc @janetkuo

**Comment by bgrant0607** [comment]
LGTM

**Comment by madhusudancs** [comment]
@davidopp This PR removes Feature: tags from DaemonSet e2e tests.

**Comment by janetkuo** [comment]
@madhusudancs please squash

**Comment by madhusudancs** [comment]
@janetkuo sorry, seeing your comment now. PR has already merged :(

**Pull request merged**
