### PR TITLE
Don't raise observedGeneration when waiting for expectations and object hasn't been processed

### PR DESCRIPTION
**Pull request by tnozicka**
**What this PR does / why we need it**:
Fixes updating `ds.Status.ObservedGeneration` - update should be done only if the object has been processed.

**Release note**:

```release-note
NONE
```

/assign @janetkuo @kow3ns 
/cc @kubernetes/sig-apps-pr-reviews

### CODE REVIEW

**Comment by tnozicka** [comment]
/kind bug

/test pull-kubernetes-e2e-kops-aws
(infra flake)

**Comment by tnozicka** [comment]
/retest
(aws flake)

**Comment by tnozicka** [comment]
/milestone v1.12
low risk fix
@janetkuo PTAL

**Comment by nikopen** [comment]
pinged sig-apps for a review

**Review by janetkuo — APPROVED** [review]

**Comment by janetkuo** [comment]
/approve

Not sure why the approval tag isn't auto-applied.

**Comment by mikedanese** [comment]
@janetkuo lgtm no longer implies approve in this repo

/shrug

**Pull request merged**
