### PR TITLE
Automated cherry pick of #86027: Fix broken SELinux detection

### PR DESCRIPTION
**Pull request by idealhack**
Cherry pick of #86027 on release-1.16.

#86027: Fix broken SELinux detection

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by cblecker** [comment]
@idealhack You may need to re-run `hack/update-bazel.sh` on this PR.

**Comment by idealhack** [comment]
@cblecker thanks, the test is now passing.

in the meantime...
/test pull-kubernetes-e2e-gce

**Comment by idealhack** [comment]
not sure why, but `hack/update-openapi-spec.sh` (suggested by [pull-kubernetes-verify](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/86036/pull-kubernetes-verify/1204996235262431236)) gave me:

```diff
diff --git a/api/openapi-spec/swagger.json b/api/openapi-spec/swagger.json
index dfee4e9..5338ecd 100644
--- a/api/openapi-spec/swagger.json
+++ b/api/openapi-spec/swagger.json
@@ -20106,7 +20106,7 @@
   },
   "info": {
     "title": "Kubernetes",
-    "version": "v1.16.5"
+    "version": "v1.12.0"
   },
   "paths": {
     "/api/": {
```

**Comment by liggitt** [comment]
@idealhack  You need to fetch tags from the kubernetes repo

**Comment by liggitt** [comment]
cc @tpepper on openapi version being incorrect

@idealhack you shouldn't need to change that as part of this PR. There's an open issue about the release branches getting the wrong version generated.

**Pull request merged**
