### PR TITLE
Fix 'flock' command in hack/jenkins/e2e.sh

### PR DESCRIPTION
**Pull request by gmarek**

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
Merging this quickly as this might fix jenkins

**Comment by brendandburns** [comment]
I think this broke jenkins, I'm going to revert.

**Comment by gmarek** [comment]
What was the symptom?

**Comment by fgrzadkowski** [comment]
@brendandburns AFAIU this fixed jenkins (or fixed something). Before this CL jenkins tests where crash looping. The problems we have noticed was that:
* wrong brackets were used - ```{``` instead of ```(```
* File descriptor 9 was opened as ```jenkins```, but we were locking it using ```root```
* ```gcloud``` commands were started as jenkins (```root``` was required)

**Comment by ixdy** [comment]
I'm pretty sure that this was on the right track and the revert by @brendandburns was incorrect - Jenkins is again broken with
```
+ sudo flock -x -n 9
flock: 9: Bad file descriptor
```

Looking at a green run from earlier today, it seems like things were appearing to work when really they were failing:
```
+ export KUBE_SKIP_UPDATE=y
+ KUBE_SKIP_UPDATE=y
bash: line 1153: /var/run/lock/gcloud-components.lock: Permission denied
```

Because the lockfile `/var/run/lock/gcloud-components.lock` was owned by root, this entire section was silently failing, but oddly not failing the build. As a result, we never even ran gcloud update, which fails in the reverted version, since it needs sudo.

I've recreated the `/var/run/lock/gcloud-components.lock` and made it owned by root to "fix" Jenkins. Please revert the revert (and remove `update preview` since preview is gone) and then remove the lockfile when you merge.

**Comment by gmarek** [comment]
I reverted the revert and removed the lock file. It wasn't enough so I made it writable by everyone. Most of jenkins jobs are happy, but some are still failing, somewhere around those lines.

Last lines from Jenkins output:
```
+ flock -x -n 9
Build step 'Execute shell' marked build as failure
```

**Comment by ixdy** [comment]
Which builds are failing? Some of them use a release-branch e2e.sh instead of master, so we may need to cherry-pick it over.

**Pull request merged**
