### PR TITLE
Bump e2e mounttest image version to 0.8

### PR DESCRIPTION
**Pull request by billy2180**
Reduce the number of image files required for e2e test run
```release-note
NONE
```

### CODE REVIEW

**Comment by spiffxp** [comment]
@k8s-bot ok to test
/lgtm
@kubernetes/sig-auth-pr-reviews these look like tests you'd be interested in, were they back at 0.7 due to cruft or some specific reason?

**Comment by spiffxp** [comment]
(only meant to approve given the question I asked, but otherwise it does lgtm)
/lgtm cancel
/approve

**Comment by spiffxp** [comment]
/approve cancel
@billy2180 please rebase / remove the merge commit and I'll add my approval back

**Comment by billy2180** [comment]
@spiffxp Done, PTAL

**Comment by spiffxp** [comment]
/approve
/lgtm

someone from cluster/OWNERS will need to add their approval

**Pull request merged**
