### PR TITLE
update comment

### PR DESCRIPTION
**Pull request by goushicui**
#### What type of PR is this?
re-open from https://github.com/kubernetes/kubernetes/pull/113085,  thks

#### What this PR does / why we need it:
/kind documentation
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by goushicui** [comment]
@SergeyKanzhelev

**Comment by bart0sh** [comment]
Thank you for your PR. It seems to only contain trivial edits. Please read our [trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits).

/ok-to-test
/release-note-none

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Pull request merged**
