### PR TITLE
revise kubeProxy filed as part of the kubeadm configuration

### LINKED ISSUE #105534: proxy/ipvs/README.md: passing mode:ipvs to `kubeadm init --config=file`
https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/README.md#cluster-created-by-kubeadm says:

> Cluster Created by Kubeadm
> If you are using kubeadm with a configuration file, you have to add mode: ipvs below the kubeProxy field as part of the kubeadm configuration.
> 
> ...
> kubeProxy:
>  config:
>    mode: ipvs
>...
> before running
>
> `$ kubeadm init --config <path_to_configuration_file>`
> to specify the ipvs mode before deploying the cluster.

My understanding is, that `kubeProxy:` is not anymore correct.  The correct snippet would be:
```
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
```

### PR DESCRIPTION
**Pull request by cyclinder**
Signed-off-by: cyclinder <qifeng.guo@daocloud.io>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
revise kubeProxy filed as part of the kubeadm configuration
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/105534

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cyclinder** [comment]
PTAL @lbernail  @m1093782566

**Comment by aojea** [comment]
/ok-to-test
/lgtm
/approve
Thanks

**Pull request merged**
