### PR TITLE
user --prune-allowlist in kube-addons.sh

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

xref #113116

#### Special notes for your reviewer:

- [ ] follow up:  we should remove `--prune-whitelist` in v1.28 or later. https://github.com/kubernetes/kubernetes/pull/120246

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Review by brianpursley — COMMENTED** [review]
I'm not familiar with addon-manager, but the `--prune-whitelist` is deprecated and replaced by `--prune-allowlist` in kubectl.  It still exists for now in a deprecated state, but will be removed at some point in the future (version 1.28 or later)

So it could make sense to update the kubectl command here in anticipation of that, *depending on how far back you need to support kubectl versions* since the `--prune-allowlist` didn't exist until recently.

**Comment by pacoxu** [comment]
@mrhohn do you have time to take a look?

**Review by MrHohn — APPROVED** [review]
Sorry this falls off my radar. This LGTM.

Would you need a new kube-addon-manager released for this? If so, let's also bump the version in Makefile and add CHANGELOG entry for this.

cc @spencer-p 


/approve

**Comment by spencer-p** [comment]
It looks like the cluster/addons/addon-manager/Makefile is still installing
kubectl 1.20.2, which I assume needs to be bumped to use the new flag as
well.

**Comment by MrHohn** [comment]
Thanks, this looks good. Could you update https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/CHANGELOG.md as well with this new version?

**Comment by pacoxu** [comment]
> Thanks, this looks good. Could you update https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/addon-manager/CHANGELOG.md as well with this new version?

I updated it to [v9.1.7](https://github.com/kubernetes/kubernetes/pull/117573/commits/f562375c8a63dbdee51d9f954d3062f5ddd4f2a2).

**Comment by pacoxu** [comment]
Later, I will update ` registry.k8s.io/addon-manager/kube-addon-manager` image version after the new version image is ready.

https://github.com/kubernetes/kubernetes/blob/f562375c8a63dbdee51d9f954d3062f5ddd4f2a2/cluster/gce/manifests/kube-addon-manager.yaml#L26-L27

**Review by MrHohn — APPROVED** [review]
Thanks!
/lgtm

**Pull request merged**
