### PR TITLE
Fix fake dynamic client do not handle list error

### PR DESCRIPTION
**Pull request by kingonion**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Return immediately if there's error for list operation of fake dynamic client.

#### Which issue(s) this PR fixes:
Fixes N/A

#### Special notes for your reviewer:
Thanks!

#### Does this PR introduce a user-facing change?
```
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```
NONE
```

### CODE REVIEW

**Review by MadhavJivrajani — COMMENTED** [review]
I'm not 100% sure but is it possible to return a non-nil list obj with a non-nil error? Have you encountered something similar?

**Comment by kingonion** [comment]
> I'm not 100% sure but is it possible to return a non-nil list obj with a non-nil error? Have you encountered something similar?
 
Hi @MadhavJivrajani, I was using fake action to increase the code coverage, the testing didn't return expected error. It took me sometime to find out that I should return `true, nil, err` for the fake action. I fixed it. Then I found the errors were checked for other operations. Maybe we should check error for list operation too.

**Pull request closed without merging**
