### PR TITLE
Remove Google Cloud KMS's in-tree integration

### PR DESCRIPTION
**Pull request by sakshamsharma**
Removes the following introduced by #48574 and others:
* `kms.go` which contained the cloudkms-specific code for Google Cloud KMS service.
* Registering the Google Cloud KMS in the KMS plugin registry.
* Google's `cloudkms` API package from `vendor` folder. 

The following changes are upcoming:
* Removal of KMSPluginRegistry. This would not be needed anymore, since KMS providers will be out-of-tree from now on (so no need of registering them, an address of the process would be enough).
* A service which allows encrypt/decrypt functionality (satisfies `envelope.Service` interface) if initialized with an IP/Port of an out-of-tree process serving KMS requests. Will tentatively use gRPC requests to talk to this external service.

Reference: https://github.com/kubernetes/kubernetes/pull/54439#issuecomment-340062801 and https://github.com/kubernetes/kubernetes/issues/51965#issuecomment-339333937.

```release-note
Google KMS integration was removed from in-tree in favor of a out-of-process extension point that will be used for all KMS providers.
```

### CODE REVIEW

**Comment by luxas** [comment]
cc @kubernetes/sig-api-machinery-pr-reviews @kubernetes/sig-auth-pr-reviews @kubernetes/sig-architecture-pr-reviews

**Comment by bgrant0607** [comment]
@sakshamsharma Was this functionality user-visible in any way?

**Comment by sakshamsharma** [comment]
@bgrant0607 yes, although there was no release note for this since it was not complete yet.
The configuration to run this is described in the description of #48574.

**Comment by liggitt** [comment]
it is user-facing, but extremely well documented as an alpha feature subject to change without notice:

* it was alpha in 1.7 and 1.8
* the flag to enable it was `--experimental-encryption-provider-config`
* the [current documentation](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/) states: "Encryption at rest is alpha in 1.7.0 which means it may change without notice. Users may be required to decrypt their data prior to upgrading to 1.8.0."
* [1.8 release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.8.md) stated: "Encryption of resources stored on disk (resources at rest) remained in alpha"
* the [tracking feature](https://github.com/kubernetes/features/issues/460) is labeled as alpha

**Comment by sakshamsharma** [comment]
@liggitt The feature referred in your comment (encryption at rest) is not being removed. We are simply removing the Google-Cloud-KMS integration of that feature, which only exists through the above mentioned PR and a few others. This was only added in 1.8, did not exist in 1.7.

The only users which would be affected are the ones who have `kms:` encryption-provider used in the configuration file. All other encryption providers (`aes` for instance) shall continue to work as expected.
As far as I know, we never released any documentation for KMS integration.

**Comment by liggitt** [comment]
> @liggitt The feature referred in your comment (encryption at rest) is not being removed. We are simply removing the Google-Cloud-KMS integration of that feature, which only exists through the above mentioned PR and a few others. This was only added in 1.8, did not exist in 1.7.

Right... I was just giving the overall picture of the encryption-at-rest feature, of which the cloudprovider KMS integration is just a part

**Comment by destijl** [comment]
The google-side of the KMS integration isn't launched yet, I think (saksham can correct me) you could have made it work by reading the code and figuring out what KMS bits you needed to create, and doing some manual setup, but it wasn't a launched feature.

**Comment by destijl** [comment]
/lgtm

I think this needs a release note. Something like:

```Google KMS integration was removed from in-tree in favor of a out-of-process extension point that will be used for all KMS providers.```

**Comment by sakshamsharma** [comment]
Requesting approval, bump.

**Comment by luxas** [comment]
/assign @bgrant0607 
for approval

**Pull request merged**
