### PR TITLE
List objects in deterministic order

### LINKED ISSUE #3772: Return resources in deterministic order
kubectl returns resources in a random order, which makes it hard to look for things when users have a lot resources.  Returning resources in deterministic order should be a helpful and trivial change (hopefully).  

We have an issue about pagination #2349, but that's a larger and separate issue.

### PR DESCRIPTION
**Pull request by deyuanix**
Closes #3772

/cc @smarterclayton

### CODE REVIEW

**Comment by dchen1107** [comment]
Can you add / update testcase in etcd_tools_test.go for this?

**Comment by smarterclayton** [comment]
This may break default event behavior, which may be relying on the default sort.  Can you verify?  Another option is to make this a Boolean on EtcdHelper and set it on a per registry basis.

**Comment by ddysher** [comment]
@dchen1107 test updated

@smarterclayton I'll take a look later

**Comment by ddysher** [comment]
@smarterclayton What is the 'default event behavior'? For event, we sort all of them based on Timestamp in client: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/sorted_event_list.go
So I think we are good here?

**Comment by smarterclayton** [comment]
Yeah I think so.

**Comment by ddysher** [comment]
Sounds good.  PTAL

**Comment by dchen1107** [comment]
LGTM.

**Pull request merged**
