### PR TITLE
Remove duplicate error messages from cli commands

### LINKED ISSUE #79454: kubectl version command error message is not proper
**What happened**:

**kubectl version --client=yes** command  is giving the following error message. Error message is repeated at the start and the end and also containing programming jargon

Error: invalid argument "yes" for "--client" flag: strconv.ParseBool: parsing "yes": invalid syntax

Examples:
   Print the client and server versions for the current context
  kubectl version

Options:
      --client=false: Client version only (no server required).
  -o, --output='': One of 'yaml' or 'json'.
      --short=false: Print just the version number.

Usage:
  kubectl version [flags] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).

invalid argument "yes" for "--client" flag: strconv.ParseBool: parsing "yes": invalid syntax

**What you expected to happen**:

The error message can be improved with one of the two variants

invalid argument "yes" for "--client" flag

Examples:
   Print the client and server versions for the current context
  kubectl version

Options:
      --client=false: Client version only (no server required).
  -o, --output='': One of 'yaml' or 'json'.
      --short=false: Print just the version number.

Usage:
  kubectl version [flags] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).

(or)

Invalid argument "yes" for "--client" flag

**How to reproduce it (as minimally and precisely as possible)**:

Run the command **kubectl version --client=yes**

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Amazon Linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by odinuge**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind bug

**What this PR does / why we need it**:
Since we never use the cobras "SilenceErrors" or "SilenceUsage",
a command executed with "cmd.Execute()" will never return an error
without printing it.

The current behavior results in all error messages being printed twice:

Example:

```
$ kubectl abc
Error: unknown command "abc" for "kubectl"
Run 'kubectl --help' for usage.
unknown command "abc" for "kubectl"
```

This applies to all cli commands using Cobra. To verify, follow the code
path of the Execute function:

https://github.com/spf13/cobra/blob/c439c4fa0937/command.go#L793

/sig cli

**Which issue(s) this PR fixes**:

Fixes #79454

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix duplicate error messages in cli commands
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve
/ok-to-test

**Comment by apelisse** [comment]
OK It doesn't look like we're using `SilenceErrors` anywhere, so that should be fine. Also this output shouldn't be used by script so it shouldn't be a backward compatibility problem.

/lgtm
/approve

**Comment by odinuge** [comment]
From `cmd/OWNERS`
/assign @thockin

:smile:

**Comment by BenTheElder** [comment]
belated LGTM :upside_down_face:

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by odinuge** [comment]
Is this something we want to cherry-pick into previous releases? The bug is quite annoying, and the fix is very simple..

Eg. this:

```bash
$ kubeadm ini
Error: unknown command "ini" for "kubeadm"

Did you mean this?
        init

Run 'kubeadm --help' for usage.
error: unknown command "ini" for "kubeadm"

Did you mean this?
        init
```

**Comment by BenTheElder** [comment]
@odinuge good question, raised to #sig-release on slack :sweat_smile:

**Comment by odinuge** [comment]
Ahh, good idea! Didn't think about asking on slack :smile:

**Pull request merged**
