### PR TITLE
Removed unused functions.

### PR DESCRIPTION
**Pull request by k82cn**
Signed-off-by: Da K. Ma <klaus1982.cn@gmail.com>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Review by tnozicka — APPROVED** [review]
/lgtm

**Comment by tnozicka** [comment]
/assign @janetkuo 
(for approval)

**Review by janetkuo — APPROVED** [review]

**Pull request merged**
