### PR TITLE
Add MrHohn to couple e2e tests

### PR DESCRIPTION
**Pull request by MrHohn**
/assign @bowei 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by bowei — APPROVED** [review]
LGTM

**Comment by MrHohn** [comment]
/assign @fejta 
For approval :)

**Comment by MrHohn** [comment]
@fejta Thanks!

**Comment by fejta** [comment]
/cc
/cc @cjwagner 
testing

**Comment by fejta** [comment]
/uncc
/uncc @cjwagner 
works!

**Pull request merged**
