### PR TITLE
Abstract contains function to common place

### PR DESCRIPTION
**Pull request by linyouchong**
**What this PR does / why we need it**:
There are identical "contains" func in multiple files,better to abstract it to common place

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
NONE
**Release note**:
NONE

### CODE REVIEW

**Comment by jsafrane** [comment]
golint complains:

```
/pkg/volume/testing/testing.go
I1020 09:06:03.828] \ No newline at end of file
```

**Comment by linyouchong** [comment]
@jsafrane, thanks,I have fixed it!

**Pull request merged**
