### PR TITLE
Running  update-api-reference-docs on HEAD to fix verify-api-reference-docs

### PR DESCRIPTION
**Pull request by nikhiljindal**
PR generated by running hack/update-api-reference-docs.sh
Verified that hack/verify-api-reference-docs.sh passes after this.

This fixes jenkins which was broken by https://github.com/kubernetes/kubernetes/pull/15906

cc @k8s-oncall

### CODE REVIEW

**Comment by jlowdermilk** [comment]
Hah, I just sent the same pr as a dupe. lgtm

**Comment by jlowdermilk** [comment]
Actually, can you add this to the [makefile](https://github.com/kubernetes/kubernetes/blob/master/Makefile#L43) so travis runs it?

**Comment by nikhiljindal** [comment]
Running it on travis will require some more work.
verify-api-reference-docs.sh requires docker.

**Comment by jlowdermilk** [comment]
Ok. Merging to unbreak jenkins.

**Pull request merged**
