### PR TITLE
Normalize godep comment

### LINKED ISSUE #70686: Prevent `Comment` field conflicts in Godeps/Godeps.json
**What would you like to be added**:

Prevent `Comment` field conflicts in Godeps/Godeps.json

**Why is this needed**:

`godep` may generate different comments on same commit in same repo. It's annoying when updating dependencies. More discussion: https://github.com/kubernetes/kubernetes/pull/69976#pullrequestreview-167565874

`godep` uses `git describe --tags <commit>` to generate comment, different git versions or local configs will generate different results (latest git use dynamic abbreviation size by default which depends on repo state). And some repo may tag one commit with multiple names which results in multiple comments (depends on your repo state), e.g. 

- https://github.com/go-openapi/analysis/tree/v0.17.1
- https://github.com/go-openapi/analysis/tree/v0.17.2

/kind feature

### PR DESCRIPTION
**Pull request by cofyc**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

It removes `-g<sha1hash>` postfix to normalize comment fields in `Godeps.json` file.

`godep` may generate different comments using different abbreviation size for same commit in same repo. Removing `Comment` field results in human unreadable file, so I try to normalize it to prevent unnecessary `Godeps.json` conflicts.

Note that if a repo tagged same commit with multiple names, it is still possible to generate different comments for same commit (depends on repo state). IMO it's acceptable, it's not usual and able to fix (updating repo to fetch tags).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #70686 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by fejta — COMMENTED** [review]
/uncc
/cc @dims 
/approve
for hack change

**Comment by dims** [comment]
@cofyc @fejta i'd like some discussion on this suggestion https://github.com/kubernetes/kubernetes/issues/70686#issuecomment-436250682

**Comment by thockin** [comment]
This is weird and awkward, but i guess it's better than status quo.  I am ambivalent about the alternative proposal, but demanding I change my local git config seems hostile.  Can't we embed git configs in the repo that override user-prefs?

**Comment by cofyc** [comment]
/close
Closing in favour of #70718. Fixing `godep` is better (although we need fork right now).

**Comment by thockin** [comment]
Closing in favor of #70718

**Comment by thockin** [comment]
LOL GitHub UI glitch?  I swear the button said "close"

**Pull request closed without merging**
