### PR TITLE
Add documentation for FinalizerName

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Fixes https://github.com/kubernetes/kubernetes.github.io/issues/1829

/cc @caesarxuchao

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37860)

**Comment by bgrant0607** [comment]
@derekwaynecarr FYI, you can assign PRs when you create them if you have a particular reviewer in mind.

**Comment by caesarxuchao** [comment]
Thanks @derekwaynecarr. lgtm.

**Comment by caesarxuchao** [comment]
Don't we have to run some update scripts, like https://github.com/kubernetes/kubernetes/blob/master/hack/update-api-reference-docs.sh?

**Comment by derekwaynecarr** [comment]
@caesarxuchao -- i ran scripts and got no changes.

**Comment by derekwaynecarr** [comment]
@caesarxuchao -- which i agree is weird ;-)

**Comment by derekwaynecarr** [comment]
looking at hack/update-all, maybe i messed up ordering.

**Comment by caesarxuchao** [comment]
Looks like our doc generator has problems. The `Capability` type is [commented](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L1335-L1336), but [k8s.io](http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_capability) doesn't show the comments either.

**Pull request merged**
