### PR TITLE
Add a value to PodConfigNotificationMode for distinguishing uninitialized values

### PR DESCRIPTION
**Pull request by tmrts**
Adds `PodConfigNotificationUnknown`.

### CODE REVIEW

**Comment by jlowdermilk** [comment]
@k8s-bot  ok to test

**Comment by yujuhong** [comment]
LGTM.

**Comment by tmrts** [comment]
@yujuhong is it a flake? I can't access the logs

**Comment by yujuhong** [comment]
@k8s-bot ok to test

**Comment by yujuhong** [comment]
@tmrts, the cluster failed to start. I kicked off another run.

**Pull request merged**
