### PR TITLE
Replace jenkins job builder git plugin with custom raw xml to address…

### PR DESCRIPTION
**Pull request by pwittrock**
… issues with the generated xml.

cc @timstclair

### CODE REVIEW

**Comment by ixdy** [comment]
cc @spxtr 

can you gist the XML diff (using https://github.com/ixdy/kubernetes/blob/jjb-diff/hack/jenkins/diff-job-config-patch.sh)?

**Comment by ixdy** [comment]
x-ref #23873

Per discussion just now with @pwittrock and @timstclair:
* It's not clear that this fix is entirely correct. (The Jenkins UI, current job config YAML, and job config YAML in this PR all produce different XML.)
* I will manually fix `cadvisor-dockercanarybuild-ci`, `cadvisor-gce-e2e-ci`, `heapster-dockercanarybuild-ci`, and `heapster-gce-e2e-ci` through the UI momentarily.
* @pwittrock will work on getting a proper fix for the YAML early next week.

**Comment by pwittrock** [comment]
fyi, here is the diff I get:

[diff.txt](https://github.com/kubernetes/kubernetes/files/218011/diff.txt)

@ixdy what do we need to do to have confidence in this?  Should I break out the timeout update into a separate PR?

**Comment by pwittrock** [comment]
cc @lavalamp

**Comment by pwittrock** [comment]
Issue: #24209

**Comment by pwittrock** [comment]
I am just going to move the timeout into #24222 to minimize the number of things that can go wrong.

**Comment by ixdy** [comment]
@k8s-bot unit test this please, issue #IGNORE (generate jjb diff)

**Comment by ixdy** [comment]
https://review.openstack.org/324975 to fix in JJB

**Pull request closed without merging**
