### PR TITLE
bindata on master wants to generate

### PR DESCRIPTION
**Pull request by deads2k**
I'm getting a diff produced on master from 

```
git checkout master && git fetch upstream && git merge upstream/master && git push
make clean
hack/generate-bindata.sh
```

Checking to see if it tolerates being checked in.

### CODE REVIEW

**Comment by deads2k** [comment]
@k8s-bot unit test this: issues #39604

**Comment by deads2k** [comment]
@fabianofranz @brendandburns  mind trying against master, this is driving me bonkers

**Comment by liggitt** [comment]
when I pull this branch and do `make clean`, I get different output... it tries to put the paths back to ../../../... and the content is output differently.

Can you add -nocompress and regen? I think gzip output changed from 1.6 to 1.7

```
go-bindata -nometadata -nocompress -prefix "${KUBE_ROOT}" -o "${BINDATA_OUTPUT}.tmp" -pkg generated \
	-ignore .jpg -ignore .png -ignore .md \
	"${KUBE_ROOT}/translations/..."
```

**Comment by liggitt** [comment]
looks like the paths are different when invoked via make vs directly using `hack/generate-bindata.sh`

**Comment by liggitt** [comment]
trying the nocompress fix in https://github.com/kubernetes/kubernetes/pull/39673

**Pull request closed without merging**
