### PR TITLE
Fix incorrect owner in OWNERS

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
typo: yuyuhong --> yujuhong

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
https://github.com/kubernetes/kubernetes/issues/50048#issuecomment-319846621

**Special notes for your reviewer**:
/assign @yujuhong 
I don't know whether you can approve this PR or not in such case :smile: 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
k8s-merge-robot is smart!

**Comment by yujuhong** [comment]
Well...I didn't know I own this package, but thanks for fixing anyway.
/approve no-issue

**Pull request merged**
