### PR TITLE
kubelet: Sort the container statuses in convertStatusToAPIStatus().

### LINKED ISSUE #21951: Container state is not updated correctly for rkt pods
From kubectl we saw:
```
$ kubectl get pods l7-lb-controller-5sdcm --namespace=kube-system
NAME                     READY     STATUS    RESTARTS   AGE
l7-lb-controller-5sdcm   0/2       Running   2          36m
```

```
$ kubectl describe pod l7-lb-controller-5sdcm --namespace=kube-system
Name:				l7-lb-controller-5sdcm
Namespace:			kube-system
Image(s):			gcr.io/google_containers/defaultbackend:1.0,gcr.io/google_containers/glbc:0.5.1
Node:				yifan-rkt-minion-ubcl/10.240.0.25
Start Time:			Thu, 25 Feb 2016 01:34:18 +0000
Labels:				k8s-app=glbc,kubernetes.io/cluster-service=true,name=glbc,version=v0.5.1
Status:				Running
Reason:				
Message:			
IP:				10.244.3.8
Replication Controllers:	l7-lb-controller (1/1 replicas created)
Containers:
  default-http-backend:
    Container ID:	rkt://28fdda34-c6d8-40bb-859b-1bd5eda222a3:default-http-backend
    Image:		gcr.io/google_containers/defaultbackend:1.0
    Image ID:		rkt://sha512-9abe60da0597010d5e003cfff11a51c4e57daf563c38077cb21b117fee31e650
    QoS Tier:
      cpu:	Guaranteed
      memory:	Guaranteed
    Limits:
      cpu:	10m
      memory:	20Mi
    Requests:
      cpu:			10m
      memory:			20Mi
    State:			Waiting
    Last Termination State:	Terminated
      Reason:			Completed
      Exit Code:		0
      Started:			Thu, 25 Feb 2016 01:34:18 +0000
      Finished:			Mon, 01 Jan 0001 00:00:00 +0000
    Ready:			False
    Restart Count:		1
    Environment Variables:
  l7-lb-controller:
    Container ID:	rkt://28fdda34-c6d8-40bb-859b-1bd5eda222a3:l7-lb-controller
    Image:		gcr.io/google_containers/glbc:0.5.1
    Image ID:		rkt://sha512-440555dfb4a9ae3c9445a30cc4e000eb1e81fd3d7672f574b7df0606a794c094
    QoS Tier:
      cpu:	Guaranteed
      memory:	Burstable
    Limits:
      memory:	100Mi
      cpu:	100m
    Requests:
      cpu:			100m
      memory:			50Mi
    State:			Waiting
    Last Termination State:	Terminated
      Reason:			Completed
      Exit Code:		0
      Started:			Thu, 25 Feb 2016 01:34:18 +0000
      Finished:			Mon, 01 Jan 0001 00:00:00 +0000
    Ready:			False
    Restart Count:		1
    Environment Variables:
Conditions:
  Type		Status
  Ready 	False 
Volumes:
  default-token-1neqx:
    Type:	Secret (a secret that should populate this volume)
    SecretName:	default-token-1neqx
Events:
  FirstSeen	LastSeen	Count	From				SubobjectPath				Reason		Message
  ─────────	────────	─────	────				─────────────				──────		───────
  35m		35m		1	{kubelet yifan-rkt-minion-ubcl}	spec.containers{default-http-backend}	Pulling		pulling image "gcr.io/google_containers/defaultbackend:1.0"
  35m		35m		1	{default-scheduler }							Scheduled	Successfully assigned l7-lb-controller-5sdcm to yifan-rkt-minion-ubcl
  35m		35m		1	{kubelet yifan-rkt-minion-ubcl}	spec.containers{default-http-backend}	Pulled		Successfully pulled image "gcr.io/google_containers/defaultbackend:1.0"
  35m		35m		1	{kubelet yifan-rkt-minion-ubcl}	spec.containers{l7-lb-controller}	Pulling		pulling image "gcr.io/google_containers/glbc:0.5.1"
  34m		34m		1	{kubelet yifan-rkt-minion-ubcl}	spec.containers{l7-lb-controller}	Pulled		Successfully pulled image "gcr.io/google_containers/glbc:0.5.1"
  34m		34m		2	{kubelet yifan-rkt-minion-ubcl}	spec.containers{default-http-backend}	Created		Created with rkt id 462fd938
  34m		34m		2	{kubelet yifan-rkt-minion-ubcl}	spec.containers{default-http-backend}	Started		Started with rkt id 462fd938
  33m		33m		2	{kubelet yifan-rkt-minion-ubcl}	spec.containers{default-http-backend}	Killing		Killing with rkt id 462fd938
  34m		33m		3	{kubelet yifan-rkt-minion-ubcl}	spec.containers{l7-lb-controller}	Unhealthy	Liveness probe failed: HTTP probe failed with statuscode: 500
  33m		33m		2	{kubelet yifan-rkt-minion-ubcl}	spec.containers{default-http-backend}	Created		Created with rkt id 59a157c5
  33m		33m		2	{kubelet yifan-rkt-minion-ubcl}	spec.containers{default-http-backend}	Started		Started with rkt id 59a157c5
  33m		33m		2	{kubelet yifan-rkt-minion-ubcl}	spec.containers{default-http-backend}	Created		Created with rkt id 28fdda34
  33m		33m		2	{kubelet yifan-rkt-minion-ubcl}	spec.containers{default-http-backend}	Started		Started with rkt id 28fdda34
  33m		33m		3	{kubelet yifan-rkt-minion-ubcl}	spec.containers{default-http-backend}	Pulled		Container image "gcr.io/google_containers/defaultbackend:1.0" already present on machine
  33m		33m		3	{kubelet yifan-rkt-minion-ubcl}	spec.containers{l7-lb-controller}	Pulled		Container image "gcr.io/google_containers/glbc:0.5.1" already present on machine
  33m		33m		2	{kubelet yifan-rkt-minion-ubcl}	spec.containers{default-http-backend}	Created		Created with rkt id d7693b36
  33m		33m		2	{kubelet yifan-rkt-minion-ubcl}	spec.containers{default-http-backend}	Started		Started with rkt id d7693b36
```

But on the node, `rkt list` shows the containers are running:

```
$ sudo /opt/rkt/rkt list
UUID		APP			IMAGE NAME							STATE	CREATED		STARTED		NETWORKS
88d26ee2	heapster		gcr.io/google_containers/heapster:v0.18.2			running	33 minutes ago	33 minutes ago	kubenet:ip4=10.244.3.10, default-restricted:ip4=172.16.28.10
ba5fd04f	kubernetes-dashboard	gcr.io/google_containers/kubernetes-dashboard-amd64:v0.1.0	running	37 minutes ago	37 minutes ago	kubenet:ip4=10.244.3.3, default-restricted:ip4=172.16.28.3
d7693b36	default-http-backend	gcr.io/google_containers/defaultbackend:1.0			running	35 minutes ago	35 minutes ago	kubenet:ip4=10.244.3.8, default-restricted:ip4=172.16.28.8
		l7-lb-controller	gcr.io/google_containers/glbc:0.5.1		
```

cc @sjpotter @kubernetes/sig-node

### PR DESCRIPTION
**Pull request by yifan-gu**
Fix #21951

cc @sjpotter @kubernetes/sig-node

### CODE REVIEW

**Comment by yifan-gu** [comment]
Note that this doesn't solve the issue why there are many created/started events. e.g.:
```
$ kubectl describe pod l7-lb-controller-57xlr --namespace=kube-system
Name:				l7-lb-controller-57xlr
Namespace:			kube-system
Image(s):			gcr.io/google_containers/defaultbackend:1.0,gcr.io/google_containers/glbc:0.5.1
Node:				yifan-rkt2-minion-psk8/10.240.0.6
Start Time:			Fri, 26 Feb 2016 01:14:41 +0000
Labels:				k8s-app=glbc,kubernetes.io/cluster-service=true,name=glbc,version=v0.5.1
Status:				Running
Reason:				
Message:			
IP:				10.244.2.14
Replication Controllers:	l7-lb-controller (1/1 replicas created)
Containers:
  default-http-backend:
    Container ID:	rkt://f73e451c-620c-4185-a453-0da3d4941167:default-http-backend
    Image:		gcr.io/google_containers/defaultbackend:1.0
    Image ID:		rkt://sha512-9abe60da0597010d5e003cfff11a51c4e57daf563c38077cb21b117fee31e650
    QoS Tier:
      cpu:	Guaranteed
      memory:	Guaranteed
    Limits:
      memory:	20Mi
      cpu:	10m
    Requests:
      cpu:			10m
      memory:			20Mi
    State:			Running
      Started:			Fri, 26 Feb 2016 01:27:52 +0000
    Last Termination State:	Terminated
      Reason:			Completed
      Exit Code:		0
      Started:			Fri, 26 Feb 2016 01:26:40 +0000
      Finished:			Mon, 01 Jan 0001 00:00:00 +0000
    Ready:			True
    Restart Count:		11
    Environment Variables:
  l7-lb-controller:
    Container ID:	rkt://f73e451c-620c-4185-a453-0da3d4941167:l7-lb-controller
    Image:		gcr.io/google_containers/glbc:0.5.1
    Image ID:		rkt://sha512-6c3ad84ff196321e52b6de92ba443f554c47fbd7f9cf84e3773fecc27a8d8abe
    QoS Tier:
      memory:	Burstable
      cpu:	Guaranteed
    Limits:
      cpu:	100m
      memory:	100Mi
    Requests:
      cpu:			100m
      memory:			50Mi
    State:			Running
      Started:			Fri, 26 Feb 2016 01:27:52 +0000
    Last Termination State:	Terminated
      Reason:			Completed
      Exit Code:		0
      Started:			Fri, 26 Feb 2016 01:26:40 +0000
      Finished:			Mon, 01 Jan 0001 00:00:00 +0000
    Ready:			True
    Restart Count:		11
    Environment Variables:
Conditions:
  Type		Status
  Ready 	True 
Volumes:
  default-token-fsnk5:
    Type:	Secret (a secret that should populate this volume)
    SecretName:	default-token-fsnk5
Events:
  FirstSeen	LastSeen	Count	From					SubobjectPath			Reason		Message
  ─────────	────────	─────	────					─────────────			──────		───────
  21m		21m		1	{default-scheduler }							Scheduled	Successfully assigned l7-lb-controller-57xlr to yifan-rkt2-minion-psk8
  21m		21m		1	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Pulling		pulling image "gcr.io/google_containers/defaultbackend:1.0"
  21m		21m		1	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Pulled		Successfully pulled image "gcr.io/google_containers/defaultbackend:1.0"
  21m		21m		1	{kubelet yifan-rkt2-minion-psk8}	spec.containers{l7-lb-controller}	Pulling		pulling image "gcr.io/google_containers/glbc:0.5.1"
  20m		20m		1	{kubelet yifan-rkt2-minion-psk8}	spec.containers{l7-lb-controller}	Pulled		Successfully pulled image "gcr.io/google_containers/glbc:0.5.1"
  20m		20m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Created		Created with rkt id ea204347
  20m		20m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Started		Started with rkt id ea204347
  20m		19m		3	{kubelet yifan-rkt2-minion-psk8}	spec.containers{l7-lb-controller}	Unhealthy	Liveness probe failed: HTTP probe failed with statuscode: 500
  19m		19m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Killing		Killing with rkt id ea204347
  19m		19m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Created		Created with rkt id 5b58de58
  19m		19m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Started		Started with rkt id 5b58de58
  19m		19m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Started		Started with rkt id 75210f79
  19m		19m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Created		Created with rkt id 75210f79
  19m		19m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Created		Created with rkt id 6fcfe767
  19m		19m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Started		Started with rkt id 6fcfe767
  17m		17m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Started		Started with rkt id 6418bce2
  17m		17m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Created		Created with rkt id 6418bce2
  16m		16m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Created		Created with rkt id c4d3d2bb
  16m		16m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Started		Started with rkt id c4d3d2bb
  15m		15m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Created		Created with rkt id b564cb6c
  15m		15m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Started		Started with rkt id b564cb6c
  13m		13m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Created		Created with rkt id ae95e903
  13m		13m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Started		Started with rkt id ae95e903
  12m		12m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Started		Started with rkt id 897c82f9
  12m		12m		2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Created		Created with rkt id 897c82f9
  11m		11m		1	{kubelet yifan-rkt2-minion-psk8}	spec.containers{l7-lb-controller}	Created		Created with rkt id 2966c308
  11m		11m		1	{kubelet yifan-rkt2-minion-psk8}	spec.containers{l7-lb-controller}	Started		Started with rkt id 2966c308
  9m		9m		1	{kubelet yifan-rkt2-minion-psk8}					FailedSync	Error syncing pod, skipping: failed to SyncPod: failed to run [prepare --quiet --pod-manifest /tmp/manifest-l7-lb-controller-57xlr-724448693]: exit status 1
stdout: 
stderr: image: using image from file /opt/rkt/stage1-coreos.aci
prepare: cannot acquire lock: resource temporarily unavailable


  9m	9m	2	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Failed	Failed to create rkt container with error: failed to run [prepare --quiet --pod-manifest /tmp/manifest-l7-lb-controller-57xlr-724448693]: exit status 1
stdout: 
stderr: image: using image from file /opt/rkt/stage1-coreos.aci
prepare: cannot acquire lock: resource temporarily unavailable

  9m	9m	1	{kubelet yifan-rkt2-minion-psk8}	spec.containers{l7-lb-controller}	Created	Created with rkt id 7a3d6d33
  9m	9m	1	{kubelet yifan-rkt2-minion-psk8}	spec.containers{l7-lb-controller}	Started	Started with rkt id 7a3d6d33
  19m	8m	12	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Pulled	Container image "gcr.io/google_containers/defaultbackend:1.0" already present on machine
  19m	8m	12	{kubelet yifan-rkt2-minion-psk8}	spec.containers{l7-lb-controller}	Pulled	Container image "gcr.io/google_containers/glbc:0.5.1" already present on machine
  11m	8m	4	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Started	(events with common reason combined)
  11m	8m	3	{kubelet yifan-rkt2-minion-psk8}	spec.containers{default-http-backend}	Created	(events with common reason combined)
  8m	8m	1	{kubelet yifan-rkt2-minion-psk8}	spec.containers{l7-lb-controller}	Created	Created with rkt id f73e451c

```

**Comment by Random-Liu** [comment]
@yifan-gu The unit test failed.
```
FAIL	k8s.io/kubernetes/pkg/kubelet/rkt	0.233s
```

**Comment by yujuhong** [comment]
> Note that this doesn't solve the issue why there are many created/started events. e.g.:

That may just mean that kubelet never realized those containers were running. If you search the log for the PLEG events and didn't see any events about those containers, you may want to add more logging to see if there is any state change. E.g, I have a PR to add more logging #21999

**Comment by yifan-gu** [comment]
> That may just mean that kubelet never realized those containers were running. If you search the log for the PLEG events and didn't see any events about those containers, you may want to add more logging to see if there is any state change. E.g, I have a PR to add more logging #21999

From the journal logs, I saw:

```
Feb 26 18:27:39 yifan-rkt2-minion-q1l5 rkt[3339]: [ 1243.713198] glbc[6]: I0226 18:27:39.389569       6 controller.go:155] Created new loadbalancer controller
Feb 26 18:27:39 yifan-rkt2-minion-q1l5 rkt[3339]: [ 1243.713517] glbc[6]: I0226 18:27:39.389586       6 main.go:195] Created lbc
Feb 26 18:27:39 yifan-rkt2-minion-q1l5 rkt[3339]: [ 1243.713777] glbc[6]: I0226 18:27:39.389613       6 controller.go:188] Starting loadbalancer controller
Feb 26 18:27:39 yifan-rkt2-minion-q1l5 rkt[3339]: [ 1244.003189] glbc[6]: I0226 18:27:39.679535       6 utils.go:86] Syncing yifan-rkt2-master
Feb 26 18:27:39 yifan-rkt2-minion-q1l5 rkt[3339]: [ 1244.003960] glbc[6]: I0226 18:27:39.680331       6 utils.go:86] Syncing yifan-rkt2-minion-hmpy
Feb 26 18:27:39 yifan-rkt2-minion-q1l5 rkt[3339]: [ 1244.004294] glbc[6]: I0226 18:27:39.680669       6 utils.go:86] Syncing yifan-rkt2-minion-j065
Feb 26 18:27:39 yifan-rkt2-minion-q1l5 rkt[3339]: [ 1244.004626] glbc[6]: I0226 18:27:39.681000       6 utils.go:86] Syncing yifan-rkt2-minion-q1l5
Feb 26 18:35:56 yifan-rkt2-minion-q1l5 systemd[1]: Stopping k8s_85471555-dcb6-11e5-bfac-42010af00004.service...
Feb 26 18:35:56 yifan-rkt2-minion-q1l5 systemd[1]: Stopped k8s_85471555-dcb6-11e5-bfac-42010af00004.service.
Feb 26 18:35:56 yifan-rkt2-minion-q1l5 systemd[1]: Stopped k8s_85471555-dcb6-11e5-bfac-42010af00004.service.
Feb 26 18:36:03 yifan-rkt2-minion-q1l5 systemd[1]: Stopped k8s_85471555-dcb6-11e5-bfac-42010af00004.service.
Feb 26 18:36:03 yifan-rkt2-minion-q1l5 systemd[1]: Started k8s_85471555-dcb6-11e5-bfac-42010af00004.service.
Feb 26 18:36:06 yifan-rkt2-minion-q1l5 rkt[4157]: networking: loading networks from /etc/rkt/net.d
Feb 26 18:36:06 yifan-rkt2-minion-q1l5 rkt[4157]: networking: loading network kubenet with type bridge
Feb 26 18:36:06 yifan-rkt2-minion-q1l5 rkt[4157]: networking: loading network default-restricted with type ptp
Feb 26 18:36:06 yifan-rkt2-minion-q1l5 rkt[4157]: stage1: warning: no volume specified for mount point "k8s-managed-etc-hosts", implicitly creating an "empty" volume. This volume will be removed when the pod is garbage-collected.
Feb 26 18:36:06 yifan-rkt2-minion-q1l5 rkt[4157]: stage1: warning: no volume specified for mount point "k8s-managed-etc-hosts", implicitly creating an "empty" volume. This volume will be removed when the pod is garbage-collected.
Feb 26 18:36:06 yifan-rkt2-minion-q1l5 rkt[4157]: Cannot bind mount directory /var/lib/rkt/pods/run/2bda03d0-67cd-4361-85f1-853d24fa1357/sharedVolumes/k8s-managed-etc-hosts on file /var/lib/rkt/pods/run/2bda03d0-67cd-4361-85f1-853d24fa1357/stage1/rootfs/opt/stage2/default-http-backend/rootfs/etc/hosts.
Feb 26 18:36:12 yifan-rkt2-minion-q1l5 systemd[1]: Stopped k8s_85471555-dcb6-11e5-bfac-42010af00004.service.
Feb 26 18:36:12 yifan-rkt2-minion-q1l5 systemd[1]: k8s_85471555-dcb6-11e5-bfac-42010af00004.service: Unit entered failed state.
Feb 26 18:36:12 yifan-rkt2-minion-q1l5 systemd[1]: k8s_85471555-dcb6-11e5-bfac-42010af00004.service: Failed with result 'exit-code'.
Feb 26 18:36:12 yifan-rkt2-minion-q1l5 systemd[1]: Stopping k8s_85471555-dcb6-11e5-bfac-42010af00004.service...
Feb 26 18:36:12 yifan-rkt2-minion-q1l5 systemd[1]: Started k8s_85471555-dcb6-11e5-bfac-42010af00004.service.
```

So the first restart could be related to dns: The health check will fail if the dns doesn't come up yet.

But during the restart, there is some issue with the kubelet managed etc hosts:
`stage1: warning: no volume specified for mount point "k8s-managed-etc-hosts", implicitly creating an "empty" volume. This volume will be removed when the pod is garbage-collected.`

However I don't know why kubelet is trying to mount the /etc/hosts. As it should not get the IP from pod status when creating the pod. One possibility is that since PodStatus is a cached value, so kubelet is able to get the "old pod IP" and then it decides to make the /etc/hosts. Needs confirmation @Random-Liu @yujuhong  [1]

[1] https://github.com/kubernetes/kubernetes/blob/v1.2.0-alpha.8/pkg/kubelet/kubelet.go#L1163

**Comment by yifan-gu** [comment]
Updated the PR, so instead of assuming GetPodStatus() returns sorted container statuses, now we sort the container statuses in convertStatusToAPIStatus().

**Comment by yujuhong** [comment]
> However I don't know why kubelet is trying to mount the /etc/hosts. As it should not get the IP from pod status when creating the pod. One possibility is that since PodStatus is a cached value, so kubelet is able to get the "old pod IP" and then it decides to make the /etc/hosts. Needs confirmation @Random-Liu @yujuhong [1]

https://github.com/kubernetes/kubernetes/blob/v1.2.0-alpha.8/pkg/kubelet/kubelet.go#L1164
The pod in pod.Status.PodIP is the api.Pod, which means it'd use the IP that you sent to the apiserver last time.

On the other hand, docker seems to be [overwriting PodStatus.PodIP](https://github.com/kubernetes/kubernetes/blob/v1.2.0-alpha.8/pkg/kubelet/dockertools/manager.go#L1830) before calling that, so it'd have the pod IP from the infra container already....

**Comment by Random-Liu** [comment]
LGTM

**Pull request merged**
