### PR TITLE
Add more information to node describe

### PR DESCRIPTION
**Pull request by deyuanix**
Should be ready to merge after #5137 and #5116

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM

**Comment by smarterclayton** [comment]
Actually, can you add a test in hack/test-cmd.sh that verifies that the node describe includes one of these fields?

**Comment by alex-mohr** [comment]
Just for process to manage merging, I'm removing status/lgtm given "Actually, can you add a test in hack/test-cmd.sh that verifies that the node describe includes one of these fields?"

**Comment by ddysher** [comment]
Do we test `kubectl describe` in hack/test-cmd.sh?  I see only get test.

**Comment by smarterclayton** [comment]
We don't, but we should.  `[ "$(kubectl describe ... | grep something in the output)" ]` I would consider acceptable.

**Comment by ddysher** [comment]
@smarterclayton PTAL   I'll put another quick PR to test pod describe, service describe, etc.  After this one.

**Comment by bgrant0607** [comment]
Merging.

**Pull request merged**
