### PR TITLE
Add ipvs sync period parameters - align to iptables proxier

### LINKED ISSUE #52957: Add ipvs sync period parameters - align to iptables proxier
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by m1093782566**
**What this PR does / why we need it**:

Add ipvs sync period parameters - align to iptables proxier

**Which issue this PR fixes**: 

fixes #52957

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cmluciano** [comment]
@m1093782566 Can you also make the relevant changes to [kubeadm](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/proxy/manifests.go)

**Comment by m1093782566** [comment]
> @m1093782566 Can you also make the relevant changes to kubeadm

sure, buuut can I do that in another PR?

**Comment by thockin** [comment]
Is it wise to set these while it is still alpha?  I guess its not hurting
/lgtm
/approve

**Comment by m1093782566** [comment]
agree.

**Pull request merged**
