### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by Cosrider**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

For the overall rigour of the code

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?
none
```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
Thank you for your PR. It seems to only contain trivial edits. Please read our [trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits). We encourage you to take a look at confirmed issues and bugs or issues marked `help-wanted`.

**Comment by pacoxu** [comment]
partially dup with #110673

**Comment by Cosrider** [comment]
> partially dup with #110673

fixed

**Pull request closed without merging**
