### PR TITLE
[WIP] Move to jsoniter for encoding speedup

### PR DESCRIPTION
**Pull request by jackkleeman**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Work in progress - consider changing to jsoniter from std/json for json encoding, for performance reasons.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
Given the history of subtle encoding differences between implementations, we probably need a fair amount of due diligence before a change like this.  Is there a KEP?

/hold

**Comment by fedebongio** [comment]
/cc @lavalamp @deads2k 
fyi

**Comment by lavalamp** [comment]
I think I'd want to see some really good perf numbers (e.g. at least a 20% improvement on one of CPU usage or garbage creation) before even considering something like this.

**Comment by jackkleeman** [comment]
We have been running this internally and not seen as large of a perf bump as I'd hoped. If there are anxieties, im happy to close :)

**Pull request closed without merging**
