### PR TITLE
Make kube-proxy iptables SNAT masquerade mark configurable (#2)

### PR DESCRIPTION
**Pull request by caseydavenport**
@matthewdupre started this here: https://github.com/kubernetes/kubernetes/pull/20496

Just finishing off the last review comments and squashing for him.

### CODE REVIEW

**Comment by matthewdupre** [comment]
googlebot: I consent to my commits being included / have signed the CLA.

**Comment by thockin** [comment]
Travis is complaining about verify-codecgen.sh

**Comment by matthewdupre** [comment]
I've picked up this branch, rebased it, changed to use a pointer (lifting the code from OOMScoreAdj) and sorted the autogeneration out.  Latest version is in #20496.

Thanks

**Comment by caseydavenport** [comment]
Alrighty,  closing this one since @matthewdupre seems to have it all covered in #20496.

**Pull request closed without merging**
