### PR TITLE
Bump grpc max message size for docker service

### LINKED ISSUE #63858: Bug: ResourceExhausted desc = grpc: received message larger than max (4195017 vs. 4194304)
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

- Nodes in `NotReady` status
- Pods in `Unknown` status

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: AWS
- OS (e.g. from /etc/os-release): Debian 8 (jessie)
- Kernel (e.g. `uname -a`): `Linux ... 4.4.115-k8s #1 SMP Thu Feb 8 15:37:40 UTC 2018 x86_64 GNU/Linux`
- Install tools: kops
- Others:
    - Logs:

```
==> /var/log/daemon.log <==
May 15 12:02:19 ip-10-133-93-99 kubelet[2524]: E0515 12:02:19.150508    2524 remote_runtime.go:262] ListContainers with filter &ContainerFilter{Id:,State:nil,PodSandboxId:,LabelSelector:map[string]string{},} from runtime service failed: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4195017 vs. 4194304)

May 15 12:02:19 ip-10-133-93-99 kubelet[2524]: E0515 12:02:19.150586    2524 kuberuntime_container.go:323] getKubeletContainers failed: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4195017 vs. 4194304)

May 15 12:02:19 ip-10-133-93-99 kubelet[2524]: E0515 12:02:19.150613    2524 generic.go:197] GenericPLEG: Unable to retrieve pods: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4195017 vs. 4194304)


==> /var/log/syslog <==
May 15 12:02:21 ip-10-133-93-99 kubelet[2524]: E0515 12:02:21.554728    2524 remote_runtime.go:262] ListContainers with filter &ContainerFilter{Id:,State:nil,PodSandboxId:,LabelSelector:map[string]string{},} from runtime service failed: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4195017 vs. 4194304)

May 15 12:02:21 ip-10-133-93-99 kubelet[2524]: E0515 12:02:21.554842    2524 kuberuntime_container.go:323] getKubeletContainers failed: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4195017 vs. 4194304)

May 15 12:02:21 ip-10-133-93-99 kubelet[2524]: E0515 12:02:21.554873    2524 generic.go:197] GenericPLEG: Unable to retrieve pods: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4195017 vs. 4194304)

May 15 12:02:21 ip-10-133-93-99 kubelet[2524]: I0515 12:02:21.788754    2524 kubelet.go:1794] skipping pod synchronization - [PLEG is not healthy: pleg was last seen active 1h3m27.338264092s ago; threshold is 3m0s]
```

- Possible prerequisites: a lot of jobs (1657) that failed (state: Error) because of internal problems
- Cluster size: 3 masters, 4 worker nodes
- **Workaround:** how to get the node back

```
docker system prune
...
service docker restart && service kubelet restart
```

- Possible related to https://github.com/kubernetes/kubernetes/issues/51099

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:
When we have a lot of containers, we run into the limit in grpc ( https://github.com/grpc/grpc-go/blob/master/clientconn.go#L118 )

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #63858

**Special notes for your reviewer**:
In https://github.com/kubernetes/kubernetes/pull/63977 we fixed the send and receive sizes on the client side. we should fix the docker service too 

**Release note**:

```release-note
Increase dockershim grpc service default request and response size. This reduces chances of failures when there are a large number of pods.
```

### CODE REVIEW

**Comment by ceshihao** [comment]
I think it is OK as a temporary solution.
However, it can not resolve the problem finally if more and more message (size > 16M), and we have to increase it again.

Perhaps, it can have a final solution, like stream output proto, result pagination or something else.

**Comment by dims** [comment]
@ceshihao it's a WIP to see if this helps this specific scenario that fails, if it does, then we can try to figure out how to turn it into something acceptable

**Comment by ceshihao** [comment]
Great, thanks.

**Comment by dims** [comment]
cc @runcom @sjenning @feiskyer

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Comment by yujuhong** [comment]
I think bumping the limit is reasonable (although maybe we should have a more concrete example to reason able the size).

As for a long-term solution such as pagination, I am not against the idea, but do feel like we need a better justification (e.g., expected #containers and the size of each container) for adding the complexity. 

/approve

**Comment by mkumatag** [comment]
@dims can this be cherry-picked for 1.10 release?

**Comment by dims** [comment]
@mkumatag Done!

**Pull request merged**
