### PR TITLE
Automated cherry pick of #107004: Point flowcontrol users at v1beta2

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #107004 on release-1.23.

#107004: Point flowcontrol users at v1beta2

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
NONE
```

### CODE REVIEW

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm

**Comment by liggitt** [comment]
/sig api-machinery
/priority important-soon
/kind cleanup feature
/triage accepted
@kubernetes/release-managers

**Comment by liggitt** [comment]
@kubernetes/release-managers this would be good to get in 1.23.1

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
