### PR TITLE
Add a cloud-provider hook to scrub DNS for pods

### PR DESCRIPTION
**Pull request by thockin**
GCE needs this hook and it seems general enough to include.

### CODE REVIEW

**Comment by thockin** [comment]
Related: internal b/25155987

Fixes #15917

Needs CP into 1.0 and 1.1

**Comment by thockin** [comment]
@k8s-bot test this

**Comment by jlowdermilk** [comment]
Sorry about failing tests. I broke e2e job trying to add in unit/integration. Should be working now. @k8s-bot test this

**Comment by thockin** [comment]
Need a review on this ASAP so I can CP this for 1.0 and 1.1

**Comment by ArtfulCoder** [comment]
LGTM

few clarifying Qs:
1. so it seems that we want to ensure that we respect ClusterFirst dnsPolicy under all scenarios, hence its appended after the scrub call ?
2. if resolv.conf flag == "", kubelet does the right thing and does not even invoke scrubDNS ?

We need to update the DNS e2e so that it reads /etc/resolv.conf and ensures that the count is under 6.
but no need to block this PR on e2e..

**Comment by thockin** [comment]
@k8s-bot unit test this please

**Comment by thockin** [comment]
@ArtfulCoder good call on the e2e, but yeah, let's not block this.

**Comment by jlowdermilk** [comment]
Please ignore the red x on "Jenkins GCE e2e/unit/integration". That was from a broken iteration of the pr builder.

**Comment by jlowdermilk** [comment]
@k8s-oncall please manually merge (red x is not relevant, actual tests are passing).

**Comment by lavalamp** [comment]
e2e has hit #15800

**Comment by lavalamp** [comment]
Manually merging on account of known flake.

**Pull request merged**
