### PR TITLE
Release 0.9.1

### PR DESCRIPTION
**Pull request by zmerlynn**
Pulls #3601, #3470, #3723, #3725.

cc @jbeda @jlowdermilk

### CODE REVIEW

**Comment by jlowdermilk** [comment]
LGTM, waiting for travis.

**Comment by zmerlynn** [comment]
I'm still running e2es, give me one second.

**Comment by dchen1107** [comment]
@zmerlynn since you are cutting v0.9.1, could you please also cherrypick #3725 too? I created a label called release/cherrypick0.9 earlier.

**Comment by zmerlynn** [comment]
Ah, sorry, I didn't see the label. Working on it.

**Comment by zmerlynn** [comment]
I don't see anything under that label.

**Comment by zmerlynn** [comment]
@dchen1107: Added, restarting e2es.

**Comment by dchen1107** [comment]
LGTM

**Comment by zmerlynn** [comment]
Mumble. Flakes on private.sh and services.sh as usual. Let me make sure I
can get a green on those and make sure I can bring up on GKE (which is
being finnicky).

**Comment by zmerlynn** [comment]
Okay, we're good.

**Comment by zmerlynn** [comment]
Merging on @jbeda looking over my shoulder.

**Comment by dchen1107** [comment]
Great, thanks!

**Pull request merged**
