### PR TITLE
let --version flag be treated as --version=true

### LINKED ISSUE #17266: Kubernetes components --version flag requires a argument to printout the version information since 1.1 release
@dyema reported that:

Kubelet has a weird way of handling --version flag in v1.1: it requires a boolean value to be specified at commandline.  
```
$ kubelet --version=true
Kubernetes v1.1.1
```
The older version handles it more sanely:
```
$ kubelet --version
Kubernetes v1.0.1
```
Then I verified it with our master components, and all of them have the same regression:
```
/ # /usr/local/bin/kube-apiserver --version
flag needs an argument: --version
Usage of /usr/local/bin/kube-apiserver:
      --admission-control="AlwaysAdmit": Ordered list of plug-ins to do admission control of resources into cluster. Comma-delimited list of: AlwaysAdmit, AlwaysDeny, DenyEscalatingExec, DenyExecOnPrivileged, InitialResources, LimitRanger, NamespaceAutoProvision, NamespaceExists, NamespaceLifecycle, ResourceQuota, SecurityContextDeny, ServiceAccount
      --admission-control-config-file="": File with admission control configuration.
...
/ # /usr/local/bin/kube-apiserver --version=true
Kubernetes v1.1.1-beta.518+f9ad30f7c96fa0-dirty
```

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #17266.

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM 

cc/ @andyzheng0831

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by caesarxuchao** [comment]
@k8s-bot e2e test this please

**Comment by dchen1107** [comment]
ok to test

**Pull request merged**
