### PR TITLE
Updated & added visibility to apiserver x509 test certificates expiring this year

### PR DESCRIPTION
**Pull request by seantywork**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

Since four x509 certificates hard-coded in staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509_test.go
were signed in 2014 with 10 years period, those certificates are scheduled to expire in December this year.
The certificates include rootCAcert, selfSignedCert, clientCNCert, and serverCert.
Plus, it wasn't clear whether the test certificates were about to expire or not because some certificates were present only in PEM encoded format without proper documentation on how they had been created or what the contents were. 
So, I updated the certificates to have 100-year validity period along with documenting the exact openssl commands and certificate outputs. 

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

Time really flies, doesn't it?

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/lgtm
/approve
/ok-to-test

thanks! once this passes tests and merges, mind cherry-picking this back to supported branches so we don't get unit test failures in a few months?

**Comment by seantywork** [comment]
> pos according to the following rule



> /lgtm /approve /ok-to-test
> 
> thanks! once this passes tests and merges, mind cherry-picking this back to supported branches so we don't get unit test failures in a few months?

will do as soon as possiblem, thanks!

**Comment by liggitt** [comment]
/lgtm cancel

the gofmt and unit test failures look related

**Comment by seantywork** [comment]
> /lgtm cancel
> 
> the gofmt and unit test failures look related

my mistake, it seems that I have accidentally type "f" out of nowhere in selfSignedCert data... fixing it! (also gofmt-ing)

**Comment by seantywork** [comment]
hello @liggitt
I've created cherry-picks for this to release-1.26 to release-1.30.
Is there anything I can do to move them forward?

links:
  - https://github.com/kubernetes/kubernetes/pull/124802
  - https://github.com/kubernetes/kubernetes/pull/124803
  - https://github.com/kubernetes/kubernetes/pull/124804
  - https://github.com/kubernetes/kubernetes/pull/124805
  - https://github.com/kubernetes/kubernetes/pull/124806

**Pull request merged**
