### PR TITLE
Verify petset status.replicas in e2e test

### PR DESCRIPTION
**Pull request by janetkuo**
**What this PR does / why we need it**: follow up #33983. PetSet status.replicas bug is fixed, so adding tests for it (especially for the `should handle healthy pet restarts during scale` case)

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #

**Special notes for your reviewer**:  cc @erictune @foxish @kubernetes/sig-apps

**Release note**:

``` release-note
NONE
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35164)

### CODE REVIEW

**Review by smarterclayton — APPROVED** [review]

**Comment by smarterclayton** [comment]
Cursory glance looks ok but will defer to foxish

**Comment by foxish** [comment]
LGTM

**Comment by janetkuo** [comment]
@k8s-bot cvm gke e2e test this

**Comment by janetkuo** [comment]
@k8s-bot gci gke e2e test this

**Pull request merged**
