### PR TITLE
Enable hack/verify-staging-client-go.sh

### PR DESCRIPTION
**Pull request by caesarxuchao**
This script will make sure the staging area of client-go is up to date. Currently, this is not 100% necessary, because kubernetes/kubernetes is not using client-go yet, so we can tolerate some lag in the staging area. If this script incurs too much operational cost, @ixdy feel free to disable the verification script again.

### CODE REVIEW

**Comment by ixdy** [comment]
How frequently would we expect this check to fail? What would cause it to fail?

**Comment by caesarxuchao** [comment]
Any changes to the clients and their dependencies (like pkg/apis or pkg/api) will cause the verification to fail. It's quite frequent.

**Comment by deads2k** [comment]
@caesarxuchao  client-go can't have a verify script enforced in the queue.  It vendors apimachinery.  API machinery is synced based on this script: https://github.com/kubernetes/apimachinery/blob/master/hack/sync-from-kubernetes.sh which happens *after* kube is committed.

Because client-go is also vendored into kube, it builds with the kube level of api machinery.  This means that if you change apimachinery in a way that requires a reaction, you'll end up stuck if you try to enforce a verify script since the API machinery change won't have a commit available to vendor.

Once we finish making client-go authoritative for all packages that aren't API, then it becomes possible to diff the API specific packages for changes.

**Comment by caesarxuchao** [comment]
I have many things to catch up regarding splitting the repos. May I start with asking you a few questions? Thanks.

To make a change to k8s.io/apimachinery, the developer needs to modify the packages in k8s.io/kubernetes/pkg/ first, then run prime-apimachinery.sh to push the changes to staging, and then run k8s.io/apimachinery/hack/sync-from-kubernetes.sh to sync the repo. Is the flow correct?

staging/src/k8s.io/apiserver is authoritative, right?

In your comment, by "kube level of api machinery", do you mean staging/src/k8s.io/apimachinery?

If the developer has properly run staging/prime-apimachinery.sh and staging/copy.sh, and has committed the changes, then the verify script will work, won't it?

**Comment by deads2k** [comment]
> To make a change to k8s.io/apimachinery, the developer needs to modify the packages in k8s.io/kubernetes/pkg/ first, then run prime-apimachinery.sh to push the changes to staging, and then run k8s.io/apimachinery/hack/sync-from-kubernetes.sh to sync the repo. Is the flow correct?

Not quite.  Just update `staging/src/k8s.io/apimachinery` and merge.  Then wait for the "automated-by-deads2k-this-sucks" process to run the sync script.  That really should get automated, but I was waiting for you to get back to help have it run similarly to how you do client-go, though perhaps more frequently. :)



> staging/src/k8s.io/apiserver is authoritative, right?

Yes.



> In your comment, by "kube level of api machinery", do you mean staging/src/k8s.io/apimachinery?

Yes



> If the developer has properly run staging/prime-apimachinery.sh and staging/copy.sh, and has committed the changes, then the verify script will work, won't it?

No, because the godep step won't find the the updated apimachinery code, it will find the current level from k8s.io/apimachinery.  New packages fail as a for instance.

We should remove or rename `staging/prime-apimachinery.sh`.  It's a really handy template for "start splitting me out a repo".

**Comment by caesarxuchao** [comment]
> Not quite. Just update staging/src/k8s.io/apimachinery and merge.

It looks like staging/src/k8s.io/apimachinery is authoritative, except for the API types?

> No, because the godep step won't find the the updated apimachinery code, it will find the current level from k8s.io/apimachinery.

By "k8s.io/apimachinery", do you mean the remote repo? I think godep will prefer the code in the local gopath, and the staging area is in the gopath, see this [line](https://github.com/kubernetes/kubernetes/blob/master/hack/godep-save.sh#L23) in godep-save.sh, so I expect the godep step will find the latest change in the staging/apimachinery.

**Comment by caesarxuchao** [comment]
>  That really should get automated, but I was waiting for you to get back to help have it run similarly to how you do client-go, though perhaps more frequently. :)

Added to my todo list. Is every 24 hour frequent enough?

**Comment by deads2k** [comment]
> By "k8s.io/apimachinery", do you mean the remote repo? I think godep will prefer the code in the local gopath, and the staging area is in the gopath, see this line in godep-save.sh, so I expect the godep step will find the latest change in the staging/apimachinery.

It can't because it choose a commit sha which has to exist in order for godep to succeed.  That commit sha needs to match an actual commit or you'll break downstream tooling.

**Comment by deads2k** [comment]
> Added to my todo list. Is every 24 hour frequent enough?

I could see extending it to do nothing if no new commits in the sub-tree were present.  Then every hour seems pretty reasonable.




> It looks like staging/src/k8s.io/apimachinery is authoritative, except for the API types?

apimachinery is fully authoritative, including the types.

**Pull request closed without merging**
