### PR TITLE
core/v1/event_expansion.go use v1.GetReference

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix https://github.com/kubernetes/client-go/issues/47.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Sent https://github.com/kubernetes/kubernetes/pull/39116 to fix.

**Comment by rmmh** [comment]
@k8s-bot kops test this

**Comment by caesarxuchao** [comment]
@k8s-bot unit test this

**Comment by caesarxuchao** [comment]
@k8s-bot unit test this
@k8s-bot cvm gce e2e test this

**Pull request merged**
