### PR TITLE
Remove dockerless build tag and DockerLegacyService interface

### PR DESCRIPTION
**Pull request by hakman**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
As part of the removal of dockershim, we should also the `dockerless` build tag and the `DockerLegacyService` interface.

#### Which issue(s) this PR fixes:

Refs #106893

#### Special notes for your reviewer:
Refs #87746

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by hakman** [comment]
Thanks @dims. The `pull-kubernetes-typecheck` test will fail until https://github.com/kubernetes/test-infra/pull/24710 is merged.

**Review by pacoxu — APPROVED** [review]
/lgtm
/cc @SergeyKanzhelev

**Review by adisky — COMMENTED** [review]
/lgtm

**Pull request merged**
