### PR TITLE
dra: test examples: ensure that the claim parameter name is consistent

### PR DESCRIPTION
**Pull request by swatisehgal**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
In the Dynamic Resource allocation example specs, the claim parameter name specified was inconsistent.

This commit fixes that with a better/more consistent name, which is used to define the configmap and is also referenced in the `ResourceClaimTemplate` spec.

#### Special notes for your reviewer:
Related to Dynamic Resource Allocation feature: https://github.com/kubernetes/enhancements/issues/3063 introduced in 1.26.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/pull/3502
- [Usage]: https://github.com/kubernetes/kubernetes/pull/111023

```

### CODE REVIEW

**Review by pohly — APPROVED** [review]
/lgtm
/approve

**Comment by pohly** [comment]
@kubernetes/release-managers : can this be included in 1.26?

The change is completely harmless (nothing uses this file) but it is relevant for people who try out the new dynamic resource allocation feature manually.

**Comment by klueska** [comment]
@swatisehgal
I assume you came across this bug because you were looking into that it would take to write a DRA driver yourself.
We are planning on publishing an [example / template driver](https://github.com/kubernetes/org/issues/3837) soon which people can fork and use as a starting point.

I also have the NVIDIA GPU driver that can be used as an example until then:
https://gitlab.com/nvidia/cloud-native/k8s-dra-driver

**Comment by swatisehgal** [comment]
> @swatisehgal I assume you came across this bug because you were looking into that it would take to write a DRA driver yourself. We are planning on publishing an [example / template driver](https://github.com/kubernetes/org/issues/3837) soon which people can fork and use as a starting point.
> 
> I also have the NVIDIA GPU driver that can be used as an example until then: https://gitlab.com/nvidia/cloud-native/k8s-dra-driver

Thanks @klueska for the pointers. Yes, you are right, I am trying to get a better understanding of DRA in general and was thinking about writing a DRA driver. I am looking forward to seeing the dra-example-driver repo populated. For now, I will refer to NVIDIA [k8s-dra-driver](https://gitlab.com/nvidia/cloud-native/k8s-dra-driver) as a reference implementation.

**Review by bart0sh — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm
/triage accepted
/priority important-soon
/milestone v1.26

**Pull request merged**
