### PR TITLE
Automated cherry pick of #120177: apiextensions-apiserver: generate applyconfigurations

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Cherry pick of #120177 on release-1.27.

#120177: apiextensions-apiserver: generate applyconfigurations

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
/cc kubernetes/release-managers
I did not make cherry-picks further back in time since the generator shell scripts did not learn about applyconfigurations until this release.

**Comment by saschagrunert** [comment]
@stevekuznetsov can we get approval for https://github.com/kubernetes/kubernetes/pull/120356 as well as https://github.com/kubernetes/kubernetes/pull/120442 (CI related)?

**Comment by stevekuznetsov** [comment]
@saschagrunert I'm working on it!

**Comment by stevekuznetsov** [comment]
@saschagrunert they are all approved now. The metrics sorting cherry-pick needs to go in first, at which point the 1.28 cherry-pick companion to this one will pass & they are all ready.

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
