### PR TITLE
Add RBAC support to fluentd-elasticsearch cluster addon

### LINKED ISSUE #46023: cluster addon fluentd-elasticsearch does not work with RBAC enabled
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

rbac elasticsearch elasticsearch-logging fluentd-elasticsearch 

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.3.395+885ddcc1389bf7", GitCommit:"885ddcc1389bf744f00e7a5f96fbff5515423022", GitTreeState:"clean", BuildDate:"2017-05-15T06:32:31Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: bare metal on premises
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.2
- **Kernel** (e.g. `uname -a`): Linux overmind 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm 
- **Others**:

**What happened**:
fluentd and and elasticsearch pods did not start 

**What you expected to happen**:
fluentd and elasticsearch to start 

**How to reproduce it** (as minimally and precisely as possible):
Enable "fluentd-elasticsearch" cluster addon on a Cluster with RBAC enabled

**Anything else we need to know**:

I'm uncertain if these cluster addons are still supported, at least https://kubernetes.io/docs/concepts/cluster-administration/addons/ lists them under deprecated and #44454 mentions that currently there will be no improvements to this addon specifically. Still it is completely broken with RBAC enabled.

### PR DESCRIPTION
**Pull request by simontesar**
**What this PR does / why we need it**:
Adds rbac support to the fluentd-elasticsearch addon

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #46023 

**Special notes for your reviewer**:

**Release note**:

```release-note
Add RBAC support to fluentd-elasticsearch cluster addon
```

### CODE REVIEW

**Comment by coffeepac** [comment]
@k8s-bot ok to test

**Comment by simt2** [comment]
@k8s-bot test this

**Comment by coffeepac** [comment]
this looks good @simt2!  Thanks!

Two notes:
- have you signed the CLA with the CNCF?
- need to add a release note.  'Add RBAC roles for elasticsearch logging addon' is sufficient.

Get through those and get the tests to pass and we're good to go.

**Comment by simt2** [comment]
@coffeepac 
I did sign the CLA, I'm in the process of debugging why this check does not work. Also the Readme(or the pull request template?) said that if no release note is given, the commit text will be used as defaut - I guess this is not the case.

**Comment by coffeepac** [comment]
@simt2 thanks for adding the release note.  I'm not sure why that instruction is out of whack.  once you get your CLA check cleared this we'll be ready to go in.

**Comment by coffeepac** [comment]
@simt2 can you please check on your CLA?  it hasn't passed yet

**Comment by simt2** [comment]
I've figured it out. At the time of commit my mail was set to private and thus empty in the commit. Check passes now.

**Comment by coffeepac** [comment]
thanks for tracking it down @simt2 !  and thanks for letting me know the resolution.  will help me get other people through the CLA check later.

**Pull request merged**
