### PR TITLE
kubelet/cri: remove meaningless code

### PR DESCRIPTION
**Pull request by Iceber**
#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it:
`err` is already nil.

https://github.com/kubernetes/kubernetes/blob/eb44008ce2d05adcc9cd9c6a2950a53a2bf3caeb/pkg/kubelet/cri/remote/remote_runtime.go#L392-L405
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by wzshiming — COMMENTED** [review]
/ok-to-test

**Comment by ehashman** [comment]
/close

Thank you for your PR. It seems to only contain trivial edits. Please read our [trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits). We encourage you to take a look at confirmed issues and bugs or issues marked `help-wanted`.

**Pull request closed without merging**
