### PR TITLE
Prune all kubeapiserver internal informer/lister codes from k/k

### PR DESCRIPTION
**Pull request by yue9944882**
the hub/internal object types is only used thru the handler chain. now we remove internal informers/listers to restrict that usage.

@kubernetes/sig-api-machinery-misc 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
nice cleanup! I wonder if we can remove the internal clients as well.

**Comment by yue9944882** [comment]
@liggitt yuh huh. about to. i just tried that locally but it involves larger changes than i thought. will do it in another pull 😉

**Comment by jennybuckley** [comment]
cc @yliaog

**Comment by deads2k** [comment]
/approve

Though it will need higher level approval.

**Comment by lavalamp** [comment]
/approve

This is awesome!!!

**Pull request merged**
