### PR TITLE
kubelet: move kuberuntime.go to api/services.go

### PR DESCRIPTION
**Pull request by yujuhong**
Also add a testing package and add placeholders for fake services.

### CODE REVIEW

**Comment by feiskyer** [comment]
lgtm.

**Comment by yujuhong** [comment]
Applied lgtm according to https://github.com/kubernetes/kubernetes/pull/29884#issuecomment-236749684

**Comment by yujuhong** [comment]
@k8s-oncall, could you manually merge this? This PR moves a file (of interfaces) to a different package and add some placeholder files for test fixtures. None of these are used in production. It'd help avoid more rebases for downstream PRs.

**Comment by lavalamp** [comment]
[build cop] This should get merged by the queue as soon as it starts merging again.

**Pull request merged**
