### PR TITLE
bump golang to 1.7.3

### PR DESCRIPTION
**Pull request by jessfraz**
**What this PR does / why we need it**: bumps the go version to 1.7.3

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #

**Special notes for your reviewer**:

**Release note**:

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35716)

### CODE REVIEW

**Comment by luxas** [comment]
LGTM, have you pushed the image?

**Comment by jessfraz** [comment]
yup I pushed it

**Comment by jessfraz** [comment]
@k8s-bot kubemark e2e test this

**Comment by jessfraz** [comment]
rebased

**Comment by luxas** [comment]
@jessfraz Have you repushed the image?
Otherwise it won't pick up the changes made in #35694

cc @wojtek-t

**Comment by luxas** [comment]
Otherwise LGTM :+1:

**Comment by jessfraz** [comment]
Yes I did :)

**Comment by luxas** [comment]
Great, thanks!
Just had to double-check :)

If this would have been assigned to me, I would have applied lgtm

**Comment by dims** [comment]
Hi @jessfraz @lavalamp is this still targetted at v1.5?

**Comment by jessfraz** [comment]
Ah yes I think it would be good I can update

**Comment by jessfraz** [comment]
rebased and repushed the image

**Comment by dims** [comment]
LGTM 👍   - pending the CI jobs of course :)

**Comment by jessfraz** [comment]
ah nevermind i dont have access to push there

**Comment by jessfraz** [comment]
@k8s-bot test this please

**Comment by jessfraz** [comment]
the image is pushed now

**Comment by jessfraz** [comment]
@k8s-bot unit test this

**Comment by jessfraz** [comment]
@k8s-bot gci gce e2e test this

**Comment by jessfraz** [comment]
green!!

**Comment by dims** [comment]
LGTM 👍

**Comment by saad-ali** [comment]
Technically it is past code freeze and we shouldn't be making changes unless they are fixing bugs. Is there a compelling reason to do this now, or can it wait?

Removing milestone until we have consensus.

**Comment by jessfraz** [comment]
the go 1.7.3 release fixed bugs I think it is best to have the most recent patch version but can understand otherwise

**Comment by dims** [comment]
@saad-ali : here's what changed between 1.7.1 and 1.7.3 (cc @jessfraz) 
https://github.com/golang/go/compare/f75aafdf56dd90eab75cfeac8cf69358f73ba171...2f6557233c5a5c311547144c34b4045640ff9f71

**Comment by saad-ali** [comment]
> the go 1.7.3 release fixed bugs I think it is best to have the most recent patch version but can understand otherwise

The changes include:

> go1.7.3 (released 2016/10/19) includes fixes to the compiler, runtime, and the <code>crypto/cipher</code>, <code>crypto/tls</code>, <code>net/http</code>, and <code>strings</code> packages. See the <a href="https://github.com/golang/go/issues?q=milestone%3AGo1.7.3">Go 1.7.3 milestone</a> on our issue tracker for details.

Picking up the latest bug fixes is a good idea, and relatively low risk. Ok, for post-code freeze merge for 1.5.

**Comment by ixdy** [comment]
as @Pensu noted on #37790, I think we're still using go1.7.1 for arm and ppc. Not sure if that was intended...

**Comment by jessfraz** [comment]
oh that was not intended ill look into fixing, we might want to wait to fix til 1.7.4 which should be out today anyways

**Pull request merged**
