### PR TITLE
bump(github.com/onsi/gingko):bb93381d543b0e5725244abe752214a110791d01

### PR DESCRIPTION
**Pull request by smarterclayton**
Adds support for extracting stdout and stderr from failed tests runs
into junit, which makes junit more effective for debugging failures.

After this I'll submit a change to gubernator to show the stdout/stderr

### CODE REVIEW

**Comment by smarterclayton** [comment]
@kubernetes/sig-testing-pr-reviews now captures all debug output from the logs in junit, so you don't have to leave the junit report page in jenkins or other tools to see why an e2e test failed.

**Comment by smarterclayton** [comment]
Example of the junit generated this way:

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_gce/871/artifact/origin/artifacts/junit/junit.xml/*view*/

**Comment by smarterclayton** [comment]
@k8s-bot test this issue #IGNORE

**Comment by ixdy** [comment]
Neat!
/lgtm

**Comment by smarterclayton** [comment]
@k8s-bot cvm gke e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot gci gce e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot non-cri e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot cvm gke e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot non-cri node e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
