### PR TITLE
kube-proxy/iptables: optimize endpoint map creation by excluding invalid endpoints earlier

### PR DESCRIPTION
**Pull request by dcbw**
We don't need to do as much work as we were doing, if we exclude invalid endpoints earlier in the endpoints processing.

Fixes: https://github.com/kubernetes/kubernetes/issues/42210

@freehan @liggitt @thockin if you could review this with a fine-toothed comb...  I can't immediately think of why invalid endpoints would be useful for the HealthChecker, and this PR prevents the HC from seeing these endpoints.

### CODE REVIEW

**Comment by dcbw** [comment]
@freehan can you test with your setup as well?  I don't have the capacity to do that, so I was testing with 250 services, each with 30 endpoints.

pperf from this PR: http://people.redhat.com/dcbw/new-steady.svg
pperf without this PR: http://people.redhat.com/dcbw/old-steady.svg

**Comment by dcbw** [comment]
@kubernetes/rh-networking @kubernetes/sig-network-misc

**Comment by dcbw** [comment]
Looks like net issues with gcr.io?  @k8s-bot cvm gce e2e test this

**Comment by ethernetdan** [comment]
@bprashanth @matchstick how does this look? this is a blocker for 1.6

**Comment by thockin** [comment]
Nice cleanup - @dcbw is it really a blocker?  What's the measured impact?

**Comment by thockin** [comment]
NM, I see this is the perf regression.  Awesome.

**Pull request merged**
