### PR TITLE
Remove CephFS image

### PR DESCRIPTION
**Pull request by jsafrane**
It's not used anywhere (https://github.com/kubernetes/kubernetes/blob/master/test/utils/image/manifest.go) and it's obsoleted by Ceph RBD image that supports CephFS too.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by warmchang** [comment]
The volume-rbd image can provide both RBD and FS storage?

**Comment by jsafrane** [comment]
> The volume-rbd image can provide both RBD and FS storage?

Yes

**Comment by jsafrane** [comment]
/assign @ixdy @luxas 
There are not so many `test/images` approvers and this is trivial.

**Comment by jsafrane** [comment]
Removed from `kubernetes/cluster/gce/manifests/e2e-image-puller.manifest`, PTAL

**Comment by jsafrane** [comment]
/assign @gmarek @vishh
for approval of cluster/gce

**Review by luxas — APPROVED** [review]
/lgtm
Thanks @jsafrane, always good with cleanup PRs!

**Comment by ixdy** [comment]
`test/images/volumes-tester/ceph` was deleted in f4caccccfe49bc1075842d18c84385ebbab6a9c7, but the change to `cluster/gce/manifests/e2e-image-puller.manifest` still applies.

**Pull request closed without merging**
