### PR TITLE
GCE: Bump GLBC manifest to v1.1.1

### PR DESCRIPTION
**Pull request by nicksardo**
**Special notes for your reviewer**:
/assign bowei
/cc bowei
/cc rramkumar1

**Release note**:
```release-note
GCE: Bump GLBC version to 1.1.1 - fixing an issue of handling multiple certs with identical certificates
```

### CODE REVIEW

**Comment by cbandy** [comment]
I noticed that the [external dependencies section](https://kubernetes.io/docs/setup/release/notes/#external-dependencies) of the Kubernetes 1.11 release notes say:
> * Ingress glbc is unchanged from 1.10: v1.0.0

**Comment by bowei** [comment]
@cbandy -- can you send a PR with the doc fix?

**Comment by cbandy** [comment]
Sorry, I don't know how the notes are generated.

**Pull request merged**
