### PR TITLE
Promote CRD e2e tests to conformance

### LINKED ISSUE #81192: Conformance Tests for CRDs
- [x] write e2e tests for all CRD operations 
  - [x] https://github.com/kubernetes/kubernetes/pull/81240
  - [x] https://github.com/kubernetes/kubernetes/pull/82036 - discovery
  - 5 Untested beta Operations:
        - list ApiextensionsV1beta1 CustomResourceDefinition
        - deletecollection ApiextensionsV1beta1 CustomResourceDefinition
        - replace ApiextensionsV1beta1 CustomResourceDefinitionStatus
        - patch ApiextensionsV1beta1 CustomResourceDefinitionStatus
        - read ApiextensionsV1beta1 CustomResourceDefinitionStatus
    - [apisnoop beta coverage](https://apisnoop.cncf.io/?showUntested=true&showTested=true&showConformanceTested=true&zoomed=category-beta-apiextensions)
- [x] switch to v1 CRD APIs
    - [x] https://github.com/kubernetes/kubernetes/pull/81497
    - [x] https://github.com/kubernetes/kubernetes/pull/81684
    - [apisnoop stable coverage](https://apisnoop.cncf.io/?showUntested=true&showTested=true&showConformanceTested=true&zoomed=category-stable-apiextensions)
- [x] remove skips/time.Sleeps - https://github.com/kubernetes/kubernetes/pull/81684
- [x] [monitor for flakes](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=CustomResource&show-stale-tests=&width=5) and promote to conformance tests - https://github.com/kubernetes/kubernetes/pull/81864
- [x] [monitor https://github.com/kubernetes/kubernetes/pull/82036 for flakes](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default&width=20&sort-by-flakiness=&include-filter-by-regex=&include-filter-by-regex=CustomResource.*discovery) and promote to conformance - https://github.com/kubernetes/kubernetes/pull/82198

crd-conformance-apisnoop

[apisnoop for CRDs](https://apisnoop.cncf.io/?showUntested=true&showTested=true&showConformanceTested=true&zoomed=category-beta-apiextensions) / [test grid](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=CustomResource&show-stale-tests=&width=5)

/cc @liggitt @sttts @roycaihw @caesarxuchao @hh 
/sig api-machinery
/area conformance
/area custom-resources
/kind feature

### PR DESCRIPTION
**Pull request by jpbetz**
Test stability status: https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default&width=5&sort-by-flakiness=&include-filter-by-regex=.*CustomResource.*

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

CRDs graduate to GA in 1.16. Conformance tests are now required for graduation to GA.

**Which issue(s) this PR fixes**:

Fixes #81192

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

- [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20180415-crds-to-ga.md)

/area conformance
@kubernetes/sig-architecture-pr-reviews @kubernetes/sig-api-machinery-pr-reviews @kubernetes/cncf-conformance-wg

/cc @liggitt @roycaihw @sttts @caesarxuchao 
/priority important-soon

### CODE REVIEW

**Review by johnbelamaric — COMMENTED** [review]
Looks pretty good, mostly just some nits and questions. Thanks!

**Comment by xmudrii** [comment]
Hello! I'm the bug triage lead for the 1.16 release cycle and I'd just like to remind that the code freeze starts tomorrow PST EOD. Is there any ETA how much time will be needed to finish this PR?

As the underlying issue is in the v1.16 milestone (#81192), I'll add this PR to the milestone for tracing purposes.
/milestone v1.16

**Comment by roycaihw** [comment]
The ipv6 test is green (thanks @aojea!). We split out the test functionality change into a separate PR https://github.com/kubernetes/kubernetes/pull/82061, so we can keep the conformance promotion clean. 

@johnbelamaric If things look good, I can squash and rebase on top of https://github.com/kubernetes/kubernetes/pull/82061.

**Comment by johnbelamaric** [comment]
@roycaihw yes, that sounds great

**Comment by roycaihw** [comment]
@johnbelamaric Rebased. The first commit is #82061 (in the merge queue), the second commit the conformance promotion.

**Comment by roycaihw** [comment]
added a [Privileged:ClusterAdmin] tag per discussion in https://github.com/kubernetes/kubernetes/pull/81857#issuecomment-526281659

**Comment by johnbelamaric** [comment]
/lgtm

Note for conformance approvers: These tests require clusterAdmin, because this functionality is inherently privileged. To mitigate this in environments where the tests cannot be run as clusterAdmin, we added a `[Privileged:ClusterAdmin]` tag to that they can be easily excluded. This is a new tag and I will propose an update to the docs to cover this case.

**Comment by roycaihw** [comment]
Thanks @johnbelamaric! 

Note for conformance approvers: 
- The first commit is https://github.com/kubernetes/kubernetes/pull/82061, which is in the merge queue already. This PR (the second commit) rebases on top of that. 
- There is a new test in the merge queue, which covers the last bit of endpoints (discovery doc) https://github.com/kubernetes/kubernetes/pull/82036. I will add that test into conformance suite, either with an update in this pull or opening a separate pull, depending on how fast the merge queue goes

**Comment by smarterclayton** [comment]
/approve

CRD are fundamental to extension of conformant clusters

**Pull request merged**
