### PR TITLE
Fix comment in HPA's scale event replicaChange

### PR DESCRIPTION
**Pull request by pbetkier**
The field replicaChange in timestampedScaleEvent was wrongly described as either positive or negative depending on the scale direction. In fact the change is set as unsigned, positive or 0 even for downscales.

#### What type of PR is this?

/kind cleanup

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pbetkier** [comment]
@ josephburnett needs an approve and lgtm please :)

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by HeshamAboElMagd** [comment]
Hello @pbetkier @mwielgus . Bug Triage team here. I just wanted to touch base to check if this ticket is targeted for 1.26.

**Comment by pbetkier** [comment]
It's a comment fix. It may well go to 1.26 already, but it's not essential.

**Pull request merged**
