### PR TITLE
Fix references to PetSet

### PR DESCRIPTION
**Pull request by foxish**
Removing PetSet references in scaler/reaper code

```release-note
NONE
```

### CODE REVIEW

**Review by janetkuo — APPROVED** [review]

**Review by gyliu513 — COMMENTED** [review]
Only one minor comment, do you want to update here https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/statefulset/stateful_set.go#L50 as well?

s/pets/stateful pods

**Comment by cblecker** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by foxish** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
