### PR TITLE
fix typo in CHANGELOG

### PR DESCRIPTION
**Pull request by cheyang**
Signed-off-by: cheyang <cheyang@163.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by cheyang** [comment]
@nikhita Looks like the typo fix shouldn't impact unit test. Please have a look.

**Comment by nikhita** [comment]
> Looks like the typo fix shouldn't impact unit test.

It doesn't. :)

This looks like a flake - the test failed due to other reasons and not due to code changes you made. Should be fixed with a `/retest`.

**Comment by cheyang** [comment]
@thockin @dchen1107 Please have a look, thx.

**Comment by cheyang** [comment]
@nikhita Can you help to find guys to review it? Thx.

**Pull request closed without merging**
