### PR TITLE
fix comment of IngressClassParametersReferenceScopeCluster

### PR DESCRIPTION
**Pull request by wangrzneu**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #
fix comment of IngressClassParametersReferenceScopeCluster
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Can you please make the same fix in staging/src/k8s.io/api/networking/v1/types.go ?

**Comment by wangrzneu** [comment]
> Can you please make the same fix in staging/src/k8s.io/api/networking/v1/types.go ?

Done

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
