### PR TITLE
Update LastTransitionTime correctly in RoutesController.

### PR DESCRIPTION
**Pull request by prameshj**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
 /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR updates routesController code to set the LastTransitionTime field correctly in NodeCondition. If the condition continues to be "NetworkUnavailable", the transition time should not be updated.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by m3ngyang** [comment]
[`LastTransitionTime`](https://github.com/kubernetes/api/blob/21721929cffa4119565dd1922a54a3e38c440f85/core/v1/types.go#L4520) means the last time that the condition transit from one status to another. I think the current value is right, because a node's condition may transit from `RouteCreated` to `NoRouteCreated` if the user delete the route by mistake.

**Comment by prameshj** [comment]
> [`LastTransitionTime`](https://github.com/kubernetes/api/blob/21721929cffa4119565dd1922a54a3e38c440f85/core/v1/types.go#L4520) means the last time that the condition transit from one status to another. I think the current value is right, because a node's condition may transit from `RouteCreated` to `NoRouteCreated` if the user delete the route by mistake.

Makes sense. What i was trying to do has already been added in - https://github.com/kubernetes/kubernetes/pull/73977/files#diff-7dd6ce55a1322dbd91e73e1995d8573fR294
The current code is only updating transitionTime when there is a change.

**Pull request closed without merging**
