### PR TITLE
cri-tools deb: Rename cri_tools to the correct cri-tools

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:
This deb was incorrectly named `cri_tools` in CI testing.
We should make this match what we ship in official releases.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
@kubernetes/sig-cluster-lifecycle-pr-reviews @dims @ixdy

### CODE REVIEW

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Review by chuckha — COMMENTED** [review]
should we be consistent with rpms as well?

**Comment by detiber** [comment]
@chuckha it looks like rpm was already using a `-` :joy:

**Comment by chuckha** [comment]
sigh, i saw cri_tools, but that's the file name, thx for the 👁 @detiber

**Pull request merged**
