### PR TITLE
style(pkg/volume/csi/fake): fix golint failures

### PR DESCRIPTION
**Pull request by wangao1236**
**What type of PR is this?**

According to this issue: #68026, I revise some errors about golint in kubernetes.

**What this PR does / why we need it**:

Fixing linting issues in pkg/volume/csi/fake.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

I revised some errors about golint in the following package:
+ pkg/volume/csi/fake

After I revised above errors, I run hack/update-bazel.sh and hack/update-gofmt.sh to make sure I fix any problems with gofmt or bazel.

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by wangao1236** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)



> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

/check-cla

**Review by oomichi — COMMENTED** [review]
/cc @oomichi 
/ok-to-test

**Comment by wangao1236** [comment]
> @wangao1236: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-kubernetes-e2e-gce-storage-slow	[b62fef8](https://github.com/kubernetes/kubernetes/commit/b62fef80dc119e3c53cea2ab1d4e3e186311bbda)	[link](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/94977/pull-kubernetes-e2e-gce-storage-slow/1308478565695623168/)	`/test pull-kubernetes-e2e-gce-storage-slow`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=94977). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3wangao1236). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

**Comment by wangao1236** [comment]
> @wangao1236: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-kubernetes-e2e-gce-storage-slow	[b62fef8](https://github.com/kubernetes/kubernetes/commit/b62fef80dc119e3c53cea2ab1d4e3e186311bbda)	[link](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/94977/pull-kubernetes-e2e-gce-storage-slow/1308478565695623168/)	`/test pull-kubernetes-e2e-gce-storage-slow`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=94977). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3wangao1236). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

/retest

**Comment by wangao1236** [comment]
> @wangao1236: The following test **failed**, say `/retest` to rerun all failed tests:
> 
> Test name	Commit	Details	Rerun command
> pull-kubernetes-e2e-gce-csi-serial	[b62fef8](https://github.com/kubernetes/kubernetes/commit/b62fef80dc119e3c53cea2ab1d4e3e186311bbda)	[link](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/94977/pull-kubernetes-e2e-gce-csi-serial/1308709687641772032/)	`/test pull-kubernetes-e2e-gce-csi-serial`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=94977). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3wangao1236). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

/retest

**Comment by wangao1236** [comment]
> [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> 
> This pull-request has been approved by: _[wangao1236](https://github.com/kubernetes/kubernetes/pull/94977#)_
> To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cblecker**, **davidz627**
> You can assign the PR to them by writing `/assign @cblecker @davidz627` in a comment when ready.
> 
> The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=kubernetes%2Fkubernetes).
> 
> Needs approval from an approver in each of these files:
> * **[hack/OWNERS](https://github.com/kubernetes/kubernetes/blob/master/hack/OWNERS)**
> * **[pkg/volume/csi/OWNERS](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/OWNERS)**
> 
> Approvers can indicate their approval by writing `/approve` in a comment
> Approvers can cancel approval by writing `/approve cancel` in a comment

/assign @oomichi

**Review by oomichi — COMMENTED** [review]
/lgtm

**Comment by wangao1236** [comment]
/assign @saad-ali
Conflicting files have been handled, please review again. Thanks~

**Pull request closed without merging**
