### PR TITLE
add label examples for kubectl run

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

Add `--labels` examples for kubectl run

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
xref #49854

**Special notes for your reviewer**:
/cc @ahmetb 

**Release note**:

```release-note
add examples for kubectl run --labels
```

### CODE REVIEW

**Comment by dixudx** [comment]
`pull-kubernetes-node-e2e` did not report CI success here.

/test pull-kubernetes-node-e2e

**Comment by dixudx** [comment]
@ahmetb @fabianofranz @derekwaynecarr PTAL. Need your `approval`. Thanks.

**Comment by ahmetb** [comment]
If approved, we can skip the flaky checks. If there are no issues created about the flakes you're seeing please consider creating an issue.

**Comment by dixudx** [comment]
@brendandburns  @thockin Need your `approval`. Thanks.

**Comment by dixudx** [comment]
/assign @smarterclayton @thockin 
Need your `approval`. Thanks.

**Pull request merged**
