### PR TITLE
[WIP] Set ownership of `spec.replicas` to scale subresource

### PR DESCRIPTION
**Pull request by mariantalla**
(with @hoegaarden )

**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:
This PR implements field ownership on `replicas.scale` for the scale subresource, so that changes to that field would behave the same way (including conflicts where applicable) as a server-side apply of the main resource.

**Which issue(s) this PR fixes**:

xref: https://github.com/kubernetes/kubernetes/issues/82046

**Special notes for your reviewer**:
* The path that we're exploring in this PR is adding a `managedField` entry for `spec.replicas`, on behalf of the scale subresource (i.e. the scale subresource appears as the manager of the field).
  * To begin with we've implemented it for replica sets; if we see that the approach works we'd have to extend that to other resources too... I'm cautious of duplication there.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/cc @apelisse @jennybuckley @julianvmodesto @hoegaarden

### CODE REVIEW

**Comment by apelisse** [comment]
@julianvmodesto @jennybuckley

**Comment by julianvmodesto** [comment]
Not sure if you've seen @jennybuckley's idea yet here:
https://github.com/kubernetes/kubernetes/pull/83294#issuecomment-536734088

Seems nice since we could keep the logic to update fieldmanager in the internal package and we could re-use it for ReplicaSets, Deployments etc. as well as CRDs.

**Comment by apelisse** [comment]
Adding the entry in the ManagedFieldsEntry is not good enough to grab the ownership from other users. You also have to remove it from other users, which is definitely not trivial. The best way to do that is to call FieldManager.Update() with the old and new object (I think both are available in the ScaleREST). Jenny and Julian have discussed the wiring of the FieldManager in ScaleREST.

**Comment by mariantalla** [comment]
Alright, the commit state is a bit (or, a lot!) messy at the moment, so here's where work for this PR is at for now:
* In `pkg/registry/apps/replicaset/storage/storage.go` there's logic that ensures that there only ever is one field manager for spec.replicas. It does this by looping through all managed fields, removing any that mention `spec.replicas` and adding an entry that specifies that the current manager is the field manager.
  * That's not a very effective implementation, for a number of reasons, so I don't see us sticking with it eventually. For one, it would need to be duplicated for other main resources too. On top of that, it opens space for a number of bugs (for example the case where there's an entry for a manager of `spec.replicas` AND `spec.somethingelse`).

* We've started working through @jennybuckley 's idea (from https://github.com/kubernetes/kubernetes/pull/83294#issuecomment-536734088). There's a bare-minimum implementation of a scaleFieldManager in `staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/fieldmanager.go`, and then logic (in [`staging/src/k8s.io/apiserver/pkg/endpoints/installer.go`](https://github.com/kubernetes/kubernetes/blob/feba99bc750b095bd59103991bf591bfba7319b8/staging/src/k8s.io/apiserver/pkg/endpoints/installer.go#L556-L557)) to install scaleFieldManager as THE FieldManager in the case of `scale` subresources.

Next steps: 
* Ensure that the end-to-end flow is as expected, i.e. that scaleFieldManager does get called when requests to `/scale` happen.
* Implement the `Apply()` and `Update()` logic for scaleFieldManager.

Yesterday at the working group meeting we said we'd [speak with the rest of sig-api-machinery](https://docs.google.com/document/d/1x9RNaaysyO0gXHIr1y50QFbiL1x8OWnk2v3XnrdkT5Y/edit#heading=h.zeytuh8oowk9) on whether a more reasonable approach would be to redirect subresource `Apply`/`Update`s  to `Apply`/`Update`s of the main resource. Related context: https://github.com/kubernetes/kubernetes/issues/84530 .

**Comment by apelisse** [comment]
/close

@nodo is working on an alternative implementation of this.

**Pull request closed without merging**
