### PR TITLE
kuberuntime: remove unused GetNs code

### PR DESCRIPTION
**Pull request by yujuhong**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36380)

### CODE REVIEW

**Comment by yujuhong** [comment]
@k8s-bot cri test this

**Comment by yujuhong** [comment]
This is just a minor cleanup.

**Comment by Random-Liu** [comment]
LGTM

**Comment by Random-Liu** [comment]
@k8s-bot cri test this.

**Comment by yujuhong** [comment]
Failure caused by #36381

**Comment by yujuhong** [comment]
#36381 has been fixed. Re-running all the tests.

**Comment by yujuhong** [comment]
@k8s-bot cri test this

**Comment by yujuhong** [comment]
@k8s-bot unit test this: #36364

**Comment by bprashanth** [comment]
I don't remember exactly how the interfaces resolve, but do we need this to support the full feature set with cri and running an in process shim? The way I had in mind to do this is basically init the dockerService with the old network host, i.e https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L513, and create a https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L471

**Comment by bprashanth** [comment]
oh i guess not, the criNetworkHost will do it through the runtime https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/networks.go#L66

**Comment by yujuhong** [comment]
@bprashanth yes, for CRI, we always rely on the shim to handle the network plugins. This PR also passed all CRI tests.

**Comment by bprashanth** [comment]
I was trying to maintain a mode where we are still running the shim, AND still preserving hostports, with the caveat that the shim is not truly remote. Not sure if this is important anyway.

**Pull request merged**
