### PR TITLE
Updated etcd to 3.1.0 to remove panic while running TestUpdate with go1.8

### PR DESCRIPTION
**Pull request by abdasgupta**
Following error was coming while running "make -j5 test:
```
=== RUN   TestCreate
2017-02-16 04:50:38.798542 I | integration: launching node3379114931262850295 (unix://localhost:node3379114931262850295.sock.bridge)
2017-02-16 04:50:38.809464 I | etcdserver: name = node3379114931262850295
2017-02-16 04:50:38.809473 I | etcdserver: data dir = /tmp/etcd293713271
2017-02-16 04:50:38.809481 I | etcdserver: member dir = /tmp/etcd293713271/member
2017-02-16 04:50:38.809487 I | etcdserver: heartbeat = 10ms
2017-02-16 04:50:38.809493 I | etcdserver: election = 100ms
2017-02-16 04:50:38.809499 I | etcdserver: snapshot count = 0
2017-02-16 04:50:38.809510 I | etcdserver: advertise client URLs = unix://127.0.0.1:21002.21302.sock
2017-02-16 04:50:38.809518 I | etcdserver: initial advertise peer URLs = unix://127.0.0.1:21001.21302.sock
2017-02-16 04:50:38.809530 I | etcdserver: initial cluster = node3379114931262850295=unix://127.0.0.1:21001.21302.sock
2017-02-16 04:50:38.819351 I | etcdserver: starting member 5b381e884051e903 in cluster 1b02a122ad8cd17
2017-02-16 04:50:38.819386 I | raft: 5b381e884051e903 became follower at term 0
2017-02-16 04:50:38.819397 I | raft: newRaft 5b381e884051e903 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2017-02-16 04:50:38.819404 I | raft: 5b381e884051e903 became follower at term 1
2017-02-16 04:50:38.852217 I | etcdserver: set snapshot count to default 10000
2017-02-16 04:50:38.852229 I | etcdserver: starting server... [version: 3.0.14, cluster version: to_be_decided]
2017-02-16 04:50:38.856222 I | integration: launched node3379114931262850295 (unix://localhost:node3379114931262850295.sock.bridge)
2017-02-16 04:50:38.856673 I | membership: added member 5b381e884051e903 [unix://127.0.0.1:21001.21302.sock] to cluster 1b02a122ad8cd17
2017-02-16 04:50:38.859544 I | raft: 5b381e884051e903 is starting a new election at term 1
2017-02-16 04:50:38.859576 I | raft: 5b381e884051e903 became candidate at term 2
2017-02-16 04:50:38.859584 I | raft: 5b381e884051e903 received vote from 5b381e884051e903 at term 2
2017-02-16 04:50:38.859597 I | raft: 5b381e884051e903 became leader at term 2
2017-02-16 04:50:38.859605 I | raft: raft.node: 5b381e884051e903 elected leader 5b381e884051e903 at term 2
2017-02-16 04:50:38.859763 I | etcdserver: setting up the initial cluster version to 3.0
2017-02-16 04:50:38.860673 N | membership: set the initial cluster version to 3.0
2017-02-16 04:50:38.860699 I | api: enabled capabilities for version 3.0
2017-02-16 04:50:38.860717 I | etcdserver: published {Name:node3379114931262850295 ClientURLs:[unix://127.0.0.1:21002.21302.sock]} to cluster 1b02a122ad8cd17
panic: test timed out after 2m0s

goroutine 12126 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1022 +0xd8
created by time.goFunc
	/usr/local/go/src/time/sleep.go:170 +0x44

goroutine 1 [chan receive, 2 minutes]:
testing.(*T).Run(0xc4201eb790, 0x1424537, 0xa, 0x149c978, 0x1edb840)
	/usr/local/go/src/testing/testing.go:698 +0x290
testing.runTests.func1(0xc4201eb790)
	/usr/local/go/src/testing/testing.go:881 +0x64
testing.tRunner(0xc4201eb790, 0xc420599d90)
	/usr/local/go/src/testing/testing.go:657 +0x9c
testing.runTests(0xc4204a30c0, 0x1eceb40, 0x6, 0x6, 0x0)
	/usr/local/go/src/testing/testing.go:887 +0x258
testing.(*M).Run(0xc42057bf00, 0xc420599f00)
	/usr/local/go/src/testing/testing.go:822 +0xe8
main.main()
	k8s.io/kubernetes/federation/registry/cluster/etcd/_test/_testmain.go:52 +0xe0

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_ppc64x.s:1271 +0x4

goroutine 5 [chan receive]:
k8s.io/kubernetes/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x1edcba0)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:879 +0x64
created by k8s.io/kubernetes/vendor/github.com/golang/glog.init.1
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/golang/glog/glog.go:410 +0x1fc

goroutine 68 [select, 1 minutes]:
k8s.io/kubernetes/vendor/github.com/coreos/etcd/wal.(*filePipeline).run(0xc4202dea40)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/wal/file_pipeline.go:89 +0x168
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/wal.newFilePipeline
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/wal/file_pipeline.go:47 +0x12c

goroutine 43 [chan receive]:
k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc420308aa0)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x64
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/logutil.NewMergeLogger
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0xc4

goroutine 67 [select]:
k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc/backend.(*backend).run(0xc4202d7440)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:193 +0x184
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc/backend.newBackend
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc/backend/backend.go:119 +0x200

goroutine 55 [chan receive]:
k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc420309360)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:174 +0x64
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/logutil.NewMergeLogger
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/logutil/merge_logger.go:92 +0xc4

goroutine 64 [sleep]:
time.Sleep(0x989680)
	/usr/local/go/src/runtime/time.go:59 +0xf8
k8s.io/kubernetes/vendor/github.com/coreos/etcd/integration.(*cluster).waitMembersMatch(0xc4204a2000, 0xc4201eb860, 0xc4202bd310, 0x1, 0x1)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/integration/cluster.go:324 +0x1fc
k8s.io/kubernetes/vendor/github.com/coreos/etcd/integration.(*cluster).Launch(0xc4204a2000, 0xc4201eb860)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/integration/cluster.go:168 +0x154
k8s.io/kubernetes/vendor/github.com/coreos/etcd/integration.NewClusterV3(0xc4201eb860, 0xc4202de000, 0x0)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/integration/cluster.go:755 +0x8c
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd/testing.NewUnsecuredEtcd3TestClientServer(0xc4201eb860, 0xc420203d40, 0x0, 0x0)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd/testing/utils.go:316 +0x4c
k8s.io/kubernetes/pkg/registry/registrytest.NewEtcdStorage(0xc4201eb860, 0x14248bb, 0xa, 0x0, 0x0)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/registrytest/etcd.go:41 +0x3c
k8s.io/kubernetes/federation/registry/cluster/etcd.newStorage(0xc4201eb860, 0xc4201d1318, 0xc400000001)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/registry/cluster/etcd/etcd_test.go:34 +0x44
k8s.io/kubernetes/federation/registry/cluster/etcd.TestCreate(0xc4201eb860)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/registry/cluster/etcd/etcd_test.go:70 +0x30
testing.tRunner(0xc4201eb860, 0x149c978)
	/usr/local/go/src/testing/testing.go:657 +0x9c
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x270

goroutine 65 [IO wait, 2 minutes]:
net.runtime_pollWait(0x3fffa2013ee0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x50
net.(*pollDesc).wait(0xc420134378, 0x72, 0x1e50818, 0xc4204a32a0)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420134378, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc420134310, 0x0, 0x1e5ab60, 0xc4204a32a0)
	/usr/local/go/src/net/fd_unix.go:430 +0x180
net.(*UnixListener).accept(0xc4203d20f0, 0x3abc0, 0x16808, 0xc400000001)
	/usr/local/go/src/net/unixsock_posix.go:162 +0x30
net.(*UnixListener).Accept(0xc4203d20f0, 0xdede24, 0xc42003ef48, 0xc42003ef40, 0xc420132a40)
	/usr/local/go/src/net/unixsock.go:237 +0x4c
k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/transport.(*unixListener).Accept(0xc420484180, 0x149ff38, 0xc4202d60c0, 0xc42003ef98, 0x58a575ee)
	<autogenerated>:94 +0x60
k8s.io/kubernetes/vendor/github.com/coreos/etcd/integration.(*bridge).serveListen(0xc4202d60c0)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/integration/bridge.go:89 +0x68
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/integration.newBridge
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/integration/bridge.go:53 +0x264

goroutine 69 [select]:
k8s.io/kubernetes/vendor/github.com/coreos/etcd/raft.(*node).run(0xc4202d7800, 0xc4203d4c30)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/raft/node.go:307 +0xd10
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/raft.StartNode
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/raft/node.go:204 +0x54c

goroutine 70 [select]:
k8s.io/kubernetes/vendor/github.com/coreos/etcd/lease.(*lessor).runLoop(0xc4202bc780)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/lease/lessor.go:379 +0x164
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/lease.newLessor
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/lease/lessor.go:168 +0x170

goroutine 71 [select]:
k8s.io/kubernetes/vendor/github.com/coreos/etcd/lease.(*lessor).runLoop(0xc4202bc9b0)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/lease/lessor.go:379 +0x164
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/lease.newLessor
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/lease/lessor.go:168 +0x170

goroutine 72 [select, 2 minutes]:
k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/schedule.(*fifo).run(0xc42002c540)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/schedule/schedule.go:146 +0x320
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/schedule.NewFIFOScheduler
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/schedule/schedule.go:71 +0x1ac

goroutine 73 [select]:
k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc.(*watchableStore).syncWatchersLoop(0xc42046c480)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc/watchable_store.go:280 +0x1c0
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc.newWatchableStore
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc/watchable_store.go:84 +0x25c

goroutine 74 [select, 2 minutes]:
k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc.(*watchableStore).syncVictimsLoop(0xc42046c480)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc/watchable_store.go:306 +0x184
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc.newWatchableStore
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/mvcc/watchable_store.go:85 +0x27c

goroutine 75 [select]:
k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).run(0xc4204b6900)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/server.go:595 +0x588
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).start
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/server.go:491 +0x238

goroutine 77 [select, 1 minutes]:
k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).purgeFile(0xc4204b6900)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/server.go:502 +0x20c
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/server.go:468 +0x84

goroutine 78 [select]:
k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver.monitorFileDescriptor(0xc42002d080)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/metrics.go:89 +0x168
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/server.go:469 +0xa8

goroutine 79 [select]:
k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).monitorVersions(0xc4204b6900)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/server.go:1234 +0x318
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver.(*EtcdServer).Start
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/server.go:470 +0xc8

goroutine 80 [IO wait, 1 minutes]:
net.runtime_pollWait(0x3fffa2014120, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x50
net.(*pollDesc).wait(0xc420134228, 0x72, 0x1e50818, 0xc4203ee3c0)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420134228, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc4201341c0, 0x0, 0x1e5ab60, 0xc4203ee3c0)
	/usr/local/go/src/net/fd_unix.go:430 +0x180
net.(*UnixListener).accept(0xc4203f8ff0, 0xc420155710, 0x303034, 0x302f40)
	/usr/local/go/src/net/unixsock_posix.go:162 +0x30
net.(*UnixListener).Accept(0xc4203f8ff0, 0x302f74, 0xc4203f8ff0, 0x1e5f720, 0xc4204a21e0)
	/usr/local/go/src/net/unixsock.go:237 +0x4c
k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/transport.(*unixListener).Accept(0xc420484050, 0xc4201556e0, 0x1201f60, 0x1ec56e0, 0x12ebb80)
	<autogenerated>:94 +0x60
net/http.(*Server).Serve(0xc420089340, 0x1e69520, 0xc420484050, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2643 +0x1cc
net/http/httptest.(*Server).goServe.func1(0xc42002d200)
	/usr/local/go/src/net/http/httptest/server.go:235 +0x70
created by net/http/httptest.(*Server).goServe
	/usr/local/go/src/net/http/httptest/server.go:236 +0x5c

goroutine 87 [IO wait, 1 minutes]:
net.runtime_pollWait(0x3fffa2014060, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x50
net.(*pollDesc).wait(0xc420134298, 0x72, 0x1e50818, 0xc4203eeb00)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420134298, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc420134230, 0x0, 0x1e5ab60, 0xc4203eeb00)
	/usr/local/go/src/net/fd_unix.go:430 +0x180
net.(*UnixListener).accept(0xc4203f9080, 0xc4203266f0, 0x303034, 0x302f40)
	/usr/local/go/src/net/unixsock_posix.go:162 +0x30
net.(*UnixListener).Accept(0xc4203f9080, 0x302f74, 0xc4203f9080, 0x1e5f720, 0xc4204a2300)
	/usr/local/go/src/net/unixsock.go:237 +0x4c
k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/transport.(*unixListener).Accept(0xc4204840a0, 0xc4203263f0, 0x1201f60, 0x1ec56e0, 0x12ebb80)
	<autogenerated>:94 +0x60
net/http.(*Server).Serve(0xc420468dc0, 0x1e69520, 0xc4204840a0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2643 +0x1cc
net/http/httptest.(*Server).goServe.func1(0xc42002daa0)
	/usr/local/go/src/net/http/httptest/server.go:235 +0x70
created by net/http/httptest.(*Server).goServe
	/usr/local/go/src/net/http/httptest/server.go:236 +0x5c

goroutine 82 [select]:
k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver.(*raftNode).start.func1(0xc4204b6928)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/raft.go:151 +0xabc
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver.(*raftNode).start
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/raft.go:254 +0x1b4

goroutine 83 [select]:
k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/schedule.(*fifo).run(0xc42002d380)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/schedule/schedule.go:146 +0x320
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/schedule.NewFIFOScheduler
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/schedule/schedule.go:71 +0x1ac

goroutine 88 [select]:
k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.monitorLeader.func1(0xc4204b6900, 0xc4203b64d0)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/interceptor.go:147 +0x354
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc.monitorLeader
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/interceptor.go:173 +0xac

goroutine 89 [IO wait, 1 minutes]:
net.runtime_pollWait(0x3fffa2013fa0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x50
net.(*pollDesc).wait(0xc420134308, 0x72, 0x1e50818, 0xc4203eeb80)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420134308, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc4201342a0, 0x0, 0x1e5ab60, 0xc4203eeb80)
	/usr/local/go/src/net/fd_unix.go:430 +0x180
net.(*UnixListener).accept(0xc4203f9e00, 0x18, 0xc4204cde78, 0x8)
	/usr/local/go/src/net/unixsock_posix.go:162 +0x30
net.(*UnixListener).Accept(0xc4203f9e00, 0x9944f8, 0xc4204cdf38, 0xc4204cdf30, 0xc4202bd450)
	/usr/local/go/src/net/unixsock.go:237 +0x4c
k8s.io/kubernetes/vendor/github.com/coreos/etcd/pkg/transport.(*unixListener).Accept(0xc420484160, 0x14a1fe0, 0xc42037a0a0, 0x1e69520, 0xc420484160)
	<autogenerated>:94 +0x60
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).Serve(0xc42037a0a0, 0x1e69520, 0xc420484160, 0x0, 0x0)
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/google.golang.org/grpc/server.go:348 +0x118
created by k8s.io/kubernetes/vendor/github.com/coreos/etcd/integration.(*member).Launch
	/root/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/etcd/integration/cluster.go:609 +0x66c
exit status 2
FAIL	k8s.io/kubernetes/federation/registry/cluster/etcd	120.107s
```
This error basically comes from not receiving any response from the socket address. Socket address generated in the version of etcd being used with kubernetes currently, contains '.' character whereas Go1.8 doesn't support '.' character in the socket address. So, latest 3.1.0 version of etcd resolved this problem by generating adresses which does not contain any '.' character. Kubernetes needs to update it's vendored etcd to 3.1.0 for the above mentioned reason. This pull request takes care of that.

Signed-off-by: Abhishek Dasgupta <a10gupta@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by abdasgupta** [comment]
I signed it!

**Comment by abdasgupta** [comment]
Can you approve it please, cc @bgrant0607 ?

**Comment by wojtek-t** [comment]
Duplicate of #41427

Though, I don't think we will accept this PR before 1.6 branch is cut.

**Comment by abdasgupta** [comment]
@wojtek-t  Yeah. https://github.com/kubernetes/kubernetes/pull/41427 is taking care of the etcd issue. Should I close the issue now?

**Comment by bgrant0607** [comment]
Yes, thanks.

**Pull request closed without merging**
