### PR TITLE
Migrate prometheus bucket functionality to metrics stability framework for apiserver

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR migrate prometheus bucket to metrics stability framework.
The [metrics stability framework](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20190605-metrics-stability-migration.md) has provided bucket functionality. (refer: https://github.com/kubernetes/kubernetes/pull/82583)

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

/assign @sttts

### CODE REVIEW

**Comment by RainbowMango** [comment]
/test pull-kubernetes-bazel-build
no logs...

**Comment by liggitt** [comment]
/unassign

this is good for @logicalhan to review

**Comment by RainbowMango** [comment]
> /unassign
> 
> this is good for @logicalhan to review

Fine, let's wait for @logicalhan review. 

Thanks for quick response.

**Review by logicalhan — APPROVED** [review]
/lgtm

**Pull request merged**
