### PR TITLE
Remove kubectl dependency internal version

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:
ref kubernetes/kubectl#83

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
use `k8s.io/api/core/v1` replace `k8s.io/kubernetes/pkg/api`

use `k8s.io/client-go/kubernetes/typed/core/v1` replace `k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/internalversion`

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zjj2wry** [comment]
https://github.com/kubernetes/kubectl/issues/114

**Comment by zjj2wry** [comment]
@apelisse

**Comment by zjj2wry** [comment]
assign @apelisse this remove `top command` and `service generator` dependency

**Comment by apelisse** [comment]
Looks good to me, but I have limited knowledge of this.

**Comment by pwittrock** [comment]
yes!

**Comment by pwittrock** [comment]
cc @liggitt this looks good to me, but you have a better eye for some of the black magic behind versioned/internal APIs.

Plan to approve EOD Monday if you don't have any concerns.

**Pull request merged**
