### PR TITLE
fixing issue where SMB share paths cannot resolve with CRI-containerD on Windows

### LINKED ISSUE #94213: SMB mount does not work on containerd on Windows
**What happened**:
Deploy a Windows cluster with containerd configured, SMB mount does not work by trying following project:
 - https://github.com/kubernetes-csi/csi-driver-smb
 - https://github.com/kubernetes-sigs/azurefile-csi-driver

It reports following error:
```

Events:
  Type     Reason            Age                    From                 Message
  ----     ------            ----                   ----                 -------
  Warning  FailedScheduling  4m42s (x3 over 5m1s)   default-scheduler    running "VolumeBinding" filter plugin for pod "busybox-azurefile-0": pod has unbound immediate PersistentVolumeClaims
  Normal   Scheduled         4m40s                  default-scheduler    Successfully assigned default/busybox-azurefile-0 to 1094k8s001
  Normal   Pulling           4m24s                  kubelet, 1094k8s001  Pulling image "e2eteam/busybox:1.29"
  Normal   Pulled            3m55s                  kubelet, 1094k8s001  Successfully pulled image "e2eteam/busybox:1.29"
  Warning  Failed            3m55s                  kubelet, 1094k8s001  Error: failed to generate container "44bea7c01ab600727305945241e1db481be97d6aaf7c3118b527eac86c92aee0" spec: failed to generate spec: failed to resolve symlink "": The system cannot find the file specified.
  Warning  Failed            3m54s                  kubelet, 1094k8s001  Error: failed to generate container "a78a01134aa4d840253501b541e1f31eadac6e9ae29d049883c4cc1a79e45f6e" spec: failed to generate spec: failed to resolve symlink "": The system cannot find the file specified.
  Warning  Failed            3m41s                  kubelet, 1094k8s001  Error: failed to generate container "9686356d344bc1e3c7113277d7e22999cd274d3caa1deba75e813186f987d636" spec: failed to generate spec: failed to resolve symlink "": The system cannot find the file specified.
  Warning  Failed            3m28s                  kubelet, 1094k8s001  Error: failed to generate container "238476ccb56952ddb08dc545d5691538e56bdbb06dfdd800f3cd9f058381065c" spec: failed to generate spec: failed to resolve symlink "": The system cannot find the file specified.
  Warning  Failed            3m14s                  kubelet, 1094k8s001  Error: failed to generate container "d39de41599e788a090604a181d06912b7fc8319ca470f3adc10b2e882fac3862" spec: failed to generate spec: failed to resolve symlink "": The system cannot find the file specified.
  Warning  Failed            2m59s                  kubelet, 1094k8s001  Error: failed to generate container "90e9a6d4187b8381f7c16170c89830404a3c56b235724db96ceee597222f4688" spec: failed to generate spec: failed to resolve symlink "": The system cannot find the file specified.
  Warning  Failed            2m48s                  kubelet, 1094k8s001  Error: failed to generate container "b7cc74cfc596f7774337a5dd2be900f6b33ad2340b37dc86fc259dc62228c31b" spec: failed to generate spec: failed to resolve symlink "": The system cannot find the file specified.
  Warning  Failed            2m36s                  kubelet, 1094k8s001  Error: failed to generate container "92b62f3e6b02b7dc7ffa97c898346bbc821d466314a142fb99dd436743ebc853" spec: failed to generate spec: failed to resolve symlink "": The system cannot find the file specified.
  Warning  Failed            2m24s                  kubelet, 1094k8s001  Error: failed to generate container "893a5d27796c34ae9bfd5a140bc4557aadaf0b3e52c4cca69befcfec6388676f" spec: failed to generate spec: failed to resolve symlink "": The system cannot find the file specified.
  Normal   Pulled            100s (x11 over 3m54s)  kubelet, 1094k8s001  Container image "e2eteam/busybox:1.29" already present on machine
  Warning  Failed            100s (x3 over 2m9s)    kubelet, 1094k8s001  (combined from similar events): Error: failed to generate container "5a7b513e6b4fce31b4968737b573287e4b75a3bf541a7ec9db0880e82c9fcd6c" spec: failed to generate spec: failed to resolve symlink "": The system cannot find the file specified.

I0825 02:11:13.264774    4476 kubelet.go:1953] SyncLoop (PLEG): "busybox-azurefile-0_default(8a6c81a5-761f-4c6f-9cb0-7e2fd5b1c052)", event: &pleg.PodLifecycleEvent{ID:"8a6c81a5-761f-4c6f-9cb0-7e2fd5b1c052", Type:"ContainerStarted", Data:"73e1e4ebb8130d15a1babce1441c72a0fec6262cbc311e944b21ebcf2983b744"}
E0825 02:11:41.599214    4476 remote_runtime.go:200] CreateContainer in sandbox "73e1e4ebb8130d15a1babce1441c72a0fec6262cbc311e944b21ebcf2983b744" from runtime service failed: rpc error: code = Unknown desc = failed to generate container "44bea7c01ab600727305945241e1db481be97d6aaf7c3118b527eac86c92aee0" spec: failed to generate spec: failed to resolve symlink "": The system cannot find the file specified.
E0825 02:11:41.599214    4476 kuberuntime_manager.go:801] container start failed: CreateContainerError: failed to generate container "44bea7c01ab600727305945241e1db481be97d6aaf7c3118b527eac86c92aee0" spec: failed to generate spec: failed to resolve symlink "": The system cannot find the file specified.
E0825 02:11:41.599214    4476 pod_workers.go:191] Error syncing pod 8a6c81a5-761f-4c6f-9cb0-7e2fd5b1c052 ("busybox-azurefile-0_default(8a6c81a5-761f-4c6f-9cb0-7e2fd5b1c052)"), skipping: failed to "StartContainer" for "busybox-azurefile" with CreateContainerError: "failed to generate container \"44bea7c01ab600727305945241e1db481be97d6aaf7c3118b527eac86c92aee0\" spec: failed to generate spec: failed to resolve symlink \"\": The system cannot find the file specified."
E0825 02:11:42.487537    4476 remote_runtime.go:200] CreateContainer in sandbox "73e1e4ebb8130d15a1babce1441c72a0fec6262cbc311e944b21ebcf2983b744" from runtime service failed: rpc error: code = Unknown desc = failed to generate container "a78a01134aa4d840253501b541e1f31eadac6e9ae29d049883c4cc1a79e45f6e" spec: failed to generate spec: failed to resolve symlink "": The system cannot find the file specified.
E0825 02:11:42.487537    4476 kuberuntime_manager.go:801] container start failed: CreateContainerError: failed to generate container "a78a01134aa4d840253501b541e1f31eadac6e9ae29d049883c4cc1a79e45f6e" spec: failed to generate spec: failed to resolve symlink "": The system cannot find the file specified.
E0825 02:11:42.487537    4476 pod_workers.go:191] Error syncing pod 8a6c81a5-761f-4c6f-9cb0-7e2fd5b1c052 ("busybox-azurefile-0_default(8a6c81a5-761f-4c6f-9cb0-7e2fd5b1c052)"), skipping: failed to "StartContainer" for "busybox-azurefile" with CreateContainerError: "failed to generate container \"a78a01134aa4d840253501b541e1f31eadac6e9ae29d049883c4cc1a79e45f6e\" spec: failed to generate spec: failed to resolve symlink \"\": The system cannot find the file specified."
E0825 02:11:55.567146    4476 remote_runtime.go:200] CreateContainer in sandbox "73e1e4ebb8130d15a1babce1441c72a0fec6262cbc311e944b21ebcf2983b744" from runtime service failed: rpc error: code = Unknown desc = failed to generate container "9686356d344bc1e3c7113277d7e22999cd274d3caa1deba75e813186f987d636" spec: failed to generate spec: failed to resolve symlink "": The system cannot find the file specified.
E0825 02:11:55.567146    4476 kuberuntime_manager.go:801] container start failed: CreateContainerError: failed to generate container "9686356d344bc1e3c7113277d7e22999cd274d3caa1deba75e813186f987d636" spec: failed to generate spec: failed to resolve symlink "": The system cannot find the file specified.
E0825 02:11:55.567146    4476 pod_workers.go:191] Error syncing pod 8a6c81a5-761f-4c6f-9cb0-7e2fd5b1c052 ("busybox-azurefile-0_default(8a6c81a5-761f-4c6f-9cb0-7e2fd5b1c052)"), skipping: failed to "StartContainer" for "busybox-azurefile" with CreateContainerError: "failed to generate container \"9686356d344bc1e3c7113277d7e22999cd274d3caa1deba75e813186f987d636\" spec: failed to generate spec: failed to resolve symlink \"\": The system cannot find the file specified."
time="2020-08-25T02:12:03Z" level=error msg="failed to waitForNotification: callbackNumber 5 does not exist in callbackMap"
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.6
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): `Microsoft Windows [Version 10.0.17763.1158]`
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig windows
/sig storage

### PR DESCRIPTION
**Pull request by marosset**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Partially Fixes #94213

**Special notes for your reviewer**:

Here is the equivalent PR that went into csi-proxy: https://github.com/kubernetes-csi/csi-proxy/pull/98

As mentioned in the comments the underlying issue here is the behavior of the EvalSymlinks call in golang on Windows.
This change is intended as a work-around until a version of containerD for Windows is built with a versin of golang containing the fix (https://github.com/golang/go/pull/42096)

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by marosset** [comment]
/hold
I want to do a little bit more validation before this merges.

**Comment by marosset** [comment]
/hold cancel

I tested these changes with a private kubelet running on nodes configured with both docker and containerd.
In both cases I was able to create PVCs using the `kubernetes.io/azure-file` storage class and successfully schedule containers that used those PVCs.

**Comment by andyzhangx** [comment]
@marosset  should we cherry-pick this PR to old releases? what's the minimum supported k8s version for containerd on Windows?

**Comment by marosset** [comment]
@andyzhangx I was planning on backporting this to v1.19 this week.

**Pull request merged**
