### PR TITLE
Fix golint failures - staging/src/k8s.io

### PR DESCRIPTION
**Pull request by avorima**
/kind cleanup

**Which issue(s) this PR fixes**:

Part of #68026

**Special notes for your reviewer**:

Initially I planned on just removing a few packages as instructed, but the verify script kept on complaining until I removed all of the `staging/src/k8s.io` entries.

```release-note
NONE
```

### CODE REVIEW

**Comment by avorima** [comment]
I signed it

**Comment by cblecker** [comment]
@avorima Which verify script? I don't actually see any changes to the `staging/` directory that would fix any lints.. just removal from the lint failures file.

**Comment by avorima** [comment]
@cblecker I just followed [these instructions](https://github.com/kubernetes/kubernetes/issues/68026#issue-355336120). The script I'm talking about is `hack/verify-golint.sh` Apparently there where supposed to be some changes to be made, but as I said it just complained that there where leftover packages left in the `.golint_failures` so I removed them

**Comment by cblecker** [comment]
@avorima As you can see if you look at the above test results, there are still many lint errors in those packages

**Comment by avorima** [comment]
@cblecker Yes, indeed. The results of `golint` and `hack/verify-golint.sh` are very different. I'll close this PR and start smaller.

**Pull request closed without merging**
