### PR TITLE
fix HPA plain metric calculate

### PR DESCRIPTION
**Pull request by zach593**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

fix inconsistency in plain metric replica calculator when usageRatio == 1.0, keep same with resource replicas

related to https://github.com/kubernetes/kubernetes/pull/36585

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by zach593** [comment]
@mortent  @mwielgus

**Comment by pbetkier** [comment]
Looks like a bug indeed !

**Comment by pbetkier** [comment]
/test pull-kubernetes-e2e-autoscaling-hpa-cm

updated -cm presubmits config, should pass now

**Comment by zach593** [comment]
@mortent @mwielgus could you have a look? this one seems easy, tks.

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
