### PR TITLE
Automated cherry pick of #63492: Always track kubelet -> API connections

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #63492 on release-1.8.

#63492: Always track kubelet -> API connections

### CODE REVIEW

**Comment by liggitt** [comment]
holding to let the master PR make it through serial/soak/scale tests

**Comment by jpbetz** [comment]
Once serial/soak/scale tests on master are clear, I'm okay with this being merged.

**Comment by liggitt** [comment]
scale/serial/slow test runs showed no regression
/hold cancel

**Pull request merged**
