### PR TITLE
generate_test: Add unit test

### PR DESCRIPTION
**Pull request by gaocegege**
Signed-off-by: Ce Gao <ce.gao@outlook.com>

**What this PR does / why we need it**:

Add unit test cases for  pkg/api/v1/generate.go

```release-note
NONE
```

### CODE REVIEW

**Comment by gaocegege** [comment]
PR is ready :thinking: 

PTAL

**Comment by brendandburns** [comment]
Looks like you may need to rebase?

**Comment by brendandburns** [comment]
Compile error, I think you need to regenerate the generated code? See the `./hack/...` directory.

**Comment by gaocegege** [comment]
Sorry, I was busy with my coursework these days. There is no generate.go now then I close the PR.

**Pull request closed without merging**
