### PR TITLE
Remove boolean waitForComponentRestart which is always true in upgradeComponent

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
In upgradeComponent, waitForComponentRestart is only assigned once.

this PR removes the unnecessary boolean.

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by Klaven — COMMENTED** [review]
this looks good to me, and maintains the current functionality. my only question, should we be using/assigning this var somewhere else? it's odd it's so high up in the file compared to where it was used. Will have to go back in history later to understand more.

**Comment by tedyu** [comment]
Browsing through the code, I haven't found place where the variable should be assigned.
I think we don't need it.

**Comment by neolit123** [comment]
thanks

/lgtm
/approve
/priority backlog

**Pull request merged**
