### PR TITLE
Automated cherry pick of #72455: e2e-node-tests: fix path to system specs

### PR DESCRIPTION
**Pull request by rojkov**
Cherry pick of #72455 on release-1.13.

#72455: e2e-node-tests: fix path to system specs

contributes to #73142

```release-note
NONE
```

### CODE REVIEW

**Comment by timothysc** [comment]
@neolit123 It's extremely rare to backport e2e changes.  Is something terribly broken by this?

**Comment by neolit123** [comment]
@timothysc 

> It's extremely rare to backport e2e changes. Is something terribly broken by this?

@dims reported these broken tests:
https://github.com/kubernetes/kubernetes/issues/73142

original PR that moved a GKE.yaml file from kubeadm folder to e2e:
https://github.com/kubernetes/kubernetes/pull/72455

something is not right in general here...
these tests that are failing need a release-1.13 branch and in the release-1.13 branch the file should still be fetched from the kubeadm path, **unless** something is building from master and looking for the GKE file in the release-1.13 branch. quite frankly, i wouldn't be surprised.

we can hold on this but the tests will remain red until we find a fix.
@rojkov want to take a deeper look?

**Comment by timothysc** [comment]
@neolit123 let's chat about this next week during the standard meeting, this seems really weird to me. 

@spiffxp ^ FYI.

**Comment by rojkov** [comment]
Honestly speaking I don't quite understand where the test logs come from, but from this snippet of the log
```
I0121 14:45:47.903] cd to /go/src
I0121 14:45:47.903] Checkout: /go/src/k8s.io/kubernetes release-1.12 to /go/src/k8s.io/kubernetes
I0121 14:45:47.904] Call:  git init k8s.io/kubernetes
I0121 14:45:47.913] Initialized empty Git repository in /go/src/k8s.io/kubernetes/.git/
I0121 14:45:47.914] process 59 exited with code 0 after 0.0m
I0121 14:45:47.914] Call:  git config --local user.name 'K8S Bootstrap'
I0121 14:45:47.920] process 60 exited with code 0 after 0.0m
I0121 14:45:47.920] Call:  git config --local user.email k8s_bootstrap@localhost
I0121 14:45:47.925] process 61 exited with code 0 after 0.0m
I0121 14:45:47.926] Call:  git fetch --quiet --tags https://github.com/kubernetes/kubernetes release-1.12
I0121 14:46:34.487] process 62 exited with code 0 after 0.8m
I0121 14:46:34.488] Call:  git checkout -B test FETCH_HEAD
W0121 14:46:36.973] Switched to a new branch 'test'
I0121 14:46:37.003] process 74 exited with code 0 after 0.0m
```
it's obvious that the GKE node conformance check is run against the `release-1.12` branch. I expect the test is going to fail until the fix is merged to the branch.

Though the problem is we won't know that for sure until the merge.

**Comment by timothysc** [comment]
/hold 

No one has given me a answer to - who owns these tests, why they are here, and why we need this cherry pick.

**Comment by neolit123** [comment]
i found these tests under an experimental sig-node dashboard, so there is a good chance that they were forgotten. it's probably best to close this backport and see if someone complains. ¯\_(ツ)_/¯

**Comment by tpepper** [comment]
@timothysc @neolit123 shall we close this now?

**Comment by neolit123** [comment]
let's close this and leave it to sig-node to raise tickets if they need these experimental jobs to be fixed.

as a side note @feiskyer approved this similar PR for the 1.12 branch and it merged as we didn't have a `hold` on that:
https://github.com/kubernetes/kubernetes/pull/73162

:this-is-fine:

/close

**Comment by yguo0905** [comment]
/reopen

For example, the test in https://k8s-testgrid.appspot.com/cos-cos1-k8sstable1#e2enode-cos1-k8sstable1-gkespec is broken.

I'd also like to run the test manually using customized system spec.

Could we reconsider merging the fix?

**Comment by yguo0905** [comment]
There're conflicts.

If the author doesn't have time to rebase, I have mine at https://github.com/kubernetes/kubernetes/pull/76921.

**Comment by rojkov** [comment]
@yguo0905 #76921 has an issue with missed `extraEnvs` in `run_local.go`, so I've rebased this backport.

**Comment by yguo0905** [comment]
/assign @aleksandra-malinowska
This is a test-only change to fix tests.

**Comment by yguo0905** [comment]
/assign @yujuhong 
This is to fix the 1.13 node e2e tests using GKE system spec (https://github.com/kubernetes/kubernetes/pull/73161#issuecomment-485626680). If this makes sense to you, can you please approve?

**Comment by timothysc** [comment]
/hold 
@yujuhong  - Please outline why we need to cherry-pick tests back.  This should be an exception.

**Comment by timothysc** [comment]
meh, I don't care enough to be pedantic about this, I'll defer to the patch manager.

**Comment by yujuhong** [comment]
@timothysc this fixes bugs in the test that prevents folks from running node e2e tests using the GKE spec. It doesn't affect release blocking tests.

**Comment by yguo0905** [comment]
@timothysc, did https://github.com/kubernetes/kubernetes/pull/73161#issuecomment-485967402 address the concern?

@aleksandra-malinowska, can you please approve this cherry-pick if it makes sense to you?

**Comment by tpepper** [comment]
We've discussed from patch mgmt side and are going to take this one in.  We don't have strong policy on refusing patching like this, risk is near zero given the e2e test context, and it provides benefit to users.

**Pull request merged**
