### PR TITLE
Automated cherry pick of #41360

### PR DESCRIPTION
**Pull request by enisoc**
Cherry pick of #41360 on release-1.5.

#41360: fluentd-gcp: Add kube-apiserver-audit.log.

### CODE REVIEW

**Comment by enisoc** [comment]
@k8s-bot non-cri node e2e test this

**Comment by mwielgus** [comment]
@piosz @Crassirostris - you have recently done some changes in fluentd - are you ok with this version bump?

**Comment by piosz** [comment]
@mwielgus @enisoc we recently encountered some regression with fluentd consuming more resources around introducing this change to HEAD. I'd like to see some evidences that it doesn't have too big negative impact on fluentd, so please hold with merging this to stable branch. @enisoc if this is a priority for you, please reach @Crassirostris and me to figure out how do we want to perform those tests.

OTOH this is clearly a new feature rather than a bug fix. What is the policy here? Do we expect features to be introduced in patch releases?

**Comment by piosz** [comment]
related issue #41647

**Comment by enisoc** [comment]
@piosz Understood, thanks. Feel free to pull me in if you need help with testing the effect of my change on master.

Regarding the patch release, I imagine it comes down to a judgement call by some person or group. I will try to figure out who should make that call.

**Comment by enisoc** [comment]
@piosz To clarify, the audit log that this fluentd config reads is empty (unused) by default. Are you concerned about the stability of fluentd with the added config to read the empty file? Or are you concerned about the stability impact that could occur if a particular user enables the audit log via https://github.com/kubernetes/kubernetes/pull/41577?

**Comment by piosz** [comment]
The latter one. There is no problem in fluentd with tracking an empty file. What volume of logs do you expect from audit logs? Currently we are able to support ~200kb/s.

**Comment by enisoc** [comment]
@piosz The events that trigger entries in the audit log are already being logged in a different format in `kube-apiserver.log`. So conservatively, I would expect it to be similar to having a second copy of `kube-apiserver.log`. Do we have enough margin in fluentd to handle that?

**Comment by mwielgus** [comment]
@piosz - can we merge it?

**Comment by piosz** [comment]
@mwielgus let's wait with this till the EOW, so I can sync f2f with @enisoc and @cjcullen.

**Comment by mwielgus** [comment]
@piosz So this pr will skip 1.5.4

**Comment by piosz** [comment]
@mwielgus @enisoc let's merge this right after 1.5.4 release.

**Comment by piosz** [comment]
@mwielgus we are ok to go

**Comment by enisoc** [comment]
The last I heard is that we are OK with requiring upgrade to v1.6.x to enable audit logs to fluentd.

**Pull request closed without merging**
