### PR TITLE
Add test image for networking related tests

### PR DESCRIPTION
**Pull request by bowei**
This test image is to support the e2e test for #32551

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35454)

### CODE REVIEW

**Comment by bowei** [comment]
@bprashanth @thockin

**Comment by thockin** [comment]
Does this EOL existing test packages like netexec and serve_hostname?

How do I list what runners are available?

**Comment by bowei** [comment]
- Does not EOL other packages (yet)
- The runners are listed as part of -help

**Comment by thockin** [comment]
@k8s-bot verify test this

**Comment by bowei** [comment]
@k8s-bot verify test this

**Comment by bowei** [comment]
@k8s-bot node e2e test this.

**Pull request merged**
