### PR TITLE
Run server-side print tests only on k8s 1.10+

### LINKED ISSUE #60765: [test failed] [1.10 upgrade] Servers with support for Table transformation
the tests are failing in http://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.9-master-upgrade-master

/sig sig-api-machinery
/priority failing-test
/priority critical-urgent
/kind bug
/status approved-for-milestone
/milestone v1.10

cc @jdumars @jberkus 
/assign @lavalamp @deads2k

### PR DESCRIPTION
**Pull request by soltysh**
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #60765

**Release note**:
```release-note
None
```

/assign @smarterclayton @deads2k 
@juanvallejo fyi

### CODE REVIEW

**Comment by soltysh** [comment]
Cherry-pick for branch 1.10 in https://github.com/kubernetes/kubernetes/pull/60798.

**Comment by soltysh** [comment]
Setting milestone for 1.10, since that's what we need it for.

**Review by juanvallejo — APPROVED** [review]

**Pull request merged**
