### PR TITLE
[Minor] Fix typos in the variable name in scheduling_queue_test.go

### PR DESCRIPTION
**Pull request by akankshakumari393**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR fixes Minor Typos.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by denkensk — COMMENTED** [review]
/lgtm

Thanks. @akankshakumari393

**Comment by akankshakumari393** [comment]
Thanks for the quick reviews @denkensk 🚀

**Review by damemi — COMMENTED** [review]
/approve

**Pull request merged**
