### PR TITLE
update outdated documentation for nginx example

### PR DESCRIPTION
**Pull request by kprobst**

### CODE REVIEW

**Comment by thockin** [comment]
This appears to be a move backwards - are you running against a not-recent sourcebase?

**Comment by kprobst** [comment]
I see what's going on. The current release (0.17.1) still has run-container, which is what I and others saw (e.g., after doing curl -sS https://get.k8s.io | bash). This was changed in https://github.com/GoogleCloudPlatform/kubernetes/pull/8596 recently. The documentation is in consistent with head rather than the latest release, right? This of course means that people that use the latest release might see what looks like outdated documentation. Do we have plans to version documentation for releases?

In any case, I'll retract this PR.

**Comment by thockin** [comment]
It's a great question - one we need to tackle as part of 1.0.

**Comment by thockin** [comment]
Maybe something like providing shortlinks to versioned docs
docs.k8s.io/v0.17/foo.md

**Comment by kprobst** [comment]
Great, I've filed https://github.com/GoogleCloudPlatform/kubernetes/issues/8969.

**Pull request closed without merging**
