### PR TITLE
DaemonSet internals are still in extensions

### LINKED ISSUE #64384: `pull-kubernetes-e2e-gce-device-plugin-gpu` test always fail
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

We can see all related with `pull-kubernetes-e2e-gce-device-plugin-gpu` test failed.  #64366 #64364 #64339 #63839 and so on.
 I think it maybe relate with PR #63979 and #64340.

**What happened**:
Always fails.
**What you expected to happen**:
Pass all.

### PR DESCRIPTION
**Pull request by soltysh**
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #64384

**Special notes for your reviewer**:

/assign @jiayingz @vishh

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mindprince** [comment]
Can you update `test/e2e/scheduling/BUILD`?

**Comment by soltysh** [comment]
Done.

**Comment by jiayingz** [comment]
Thanks a lot for fixing the problem!
/lgtm

**Pull request merged**
