### PR TITLE
Removed a race condition from ResourceConsumer

### LINKED ISSUE #47127: gce-serial tests are panicking due to NPE in autoscaling code
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial/1173

```
I0607 01:09:38.349] [91m[1mâ€¢! Panic [32.767 seconds][0m
I0607 01:09:38.349] [k8s.io] Initializers
I0607 01:09:38.349] [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:617[0m
I0607 01:09:38.349]   [91m[1mshould dynamically register and apply initializers to pods [Serial] [It][0m
I0607 01:09:38.349]   [90m/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/extension/initializers.go:206[0m
I0607 01:09:38.349] 
I0607 01:09:38.350]   [91m[1mTest Panicked[0m
I0607 01:09:38.350]   [91mruntime error: invalid memory address or nil pointer dereference[0m
I0607 01:09:38.350]   /usr/local/go/src/runtime/asm_amd64.s:514
I0607 01:09:38.350] 
I0607 01:09:38.350]   [91mFull Stack Trace[0m
I0607 01:09:38.350]   	/usr/local/go/src/runtime/panic.go:489 +0x2cf
I0607 01:09:38.350]   k8s.io/kubernetes/test/e2e/common.(*ResourceConsumer).sendConsumeCPURequest.func1(0x2ef4ce0, 0xc421f65140, 0xc42114fd3f)
I0607 01:09:38.351]   	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/autoscaling_utils.go:231 +0x5f
```

### PR DESCRIPTION
**Pull request by wasylkowski**
**What this PR does / why we need it**: Without this PR there is a race condition in ResourceConsumer that sometimes results in communication to pods that might not exist anymore.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #47127

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wasylkowski** [comment]
This should fix #47127
@smarterclayton please take a look
@wojtek-t

**Comment by smarterclayton** [comment]
@k8s-bot ok to test

**Comment by wasylkowski** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by wojtek-t** [comment]
I'm not convinced about this PR - let's talk about it offline.

**Comment by wojtek-t** [comment]
DIscussed offline.

/lgtm

**Comment by wojtek-t** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by wasylkowski** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by wasylkowski** [comment]
The failing tests pass locally, so this looks like a flake. Retrying again...
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by wasylkowski** [comment]
Ref: #46847

**Comment by smarterclayton** [comment]
This is fixing flaking tests in 1.7 and blocking PRs in the queue.

**Pull request merged**
