### PR TITLE
Federation controller tests refactoring - move common func to utils

### PR DESCRIPTION
**Pull request by mwielgus**
cc: @quinton-hoole @kubernetes/sig-cluster-federation

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31265)

### CODE REVIEW

**Comment by quinton-hoole** [comment]
LGTM.  Thanks @mwielgus !

**Comment by mwielgus** [comment]
@k8s-bot test this issue: #28827

**Comment by mwielgus** [comment]
@k8s-bot e2e test this issue:#30542

**Comment by mwielgus** [comment]
@k8s-bot e2e test this issue: #28827

**Comment by mwielgus** [comment]
@k8s-bot test this issue: #28827

**Pull request merged**
