### PR TITLE
ceph-fuse should add option --client-quota to support capicity

### PR DESCRIPTION
**Pull request by silenceshell**
**What this PR does / why we need it**:

ceph-fuse should add option `--client-quot`a to support capicity, only set attr on dir will not effect the quota(`df` shows we have used all the space, but we can still copy more files to this volume).

see alse [cephfs-quota-cant-work](https://stackoverflow.com/questions/34487176/cephfs-quota-cant-work)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

no issue.

**Special notes for your reviewer**:

**Release note**:

```release-note

NONE

```

### CODE REVIEW

**Comment by cofyc** [comment]
Which version of `ceph-fuse` are you using?

In my test version `luminous`, `ceph-fuse` does not have `--client-quota` option:

```
$ ceph-fuse --version
ceph version 12.2.5 (cad919881333ac92274171586c827e01f554a70a) luminous (stable)
$ ceph-fuse --help
usage: ceph-fuse [-n client.username] [-m mon-ip-addr:mon-port] <mount point> [OPTIONS]
  --client_mountpoint/-r <sub_directory>
                    use sub_directory as the mounted root, rather than the full Ceph tree.

usage: ceph-fuse mountpoint [options]

general options:
    -o opt,[opt...]        mount options
    -h   --help            print help
    -V   --version         print version

FUSE options:
    -d   -o debug          enable debug output (implies -f)
    -f                     foreground operation
    -s                     disable multi-threaded operation

  --conf/-c FILE    read configuration from the given configuration file
  --id ID           set ID portion of my name
  --name/-n TYPE.ID set name
  --cluster NAME    set cluster name (default: ceph)
  --setuser USER    set uid to user or uid (and gid to user's gid)
  --setgroup GROUP  set gid to group or gid
  --version         show version and quit

```

I don't need to set `--client-quota` to enforce client quota limit. If I run `ceph-fuse` with `--client-quota`, command failed:

```
$ ceph-fuse -k /etc/ceph/ceph.client.admin.keyring -m <mon>:<port> /mnt/test -r /volumes/kubernetes/kubernetes-dynamic-pvc-3b7fdbf4-5f00-11e8-9333-0242ac110003 --id admin --client-quota
2018-05-24 11:26:38.532535 7fab255f2080 -1 asok(0x55d554a041e0) AdminSocketConfigObs::init: failed: AdminSocket::bind_and_listen: failed to bind the UNIX domain socket to '/var/run/ceph/ceph-client.admin.asok': (17) File exists
ceph-fuse[11407]: starting ceph client
2018-05-24 11:26:38.535974 7fab255f2080 -1 init, newargv = 0x55d554a91c70 newargc=10
fuse: unknown option `--client-quota'
ceph-fuse[11407]: fuse failed to start
2018-05-24 11:26:38.578840 7fab255f2080 -1 fuse_lowlevel_new failed
```

**Comment by silenceshell** [comment]
My ceph-fuse version is 10.2.6, host centos 7.3, kernel version 3.10.0-514.el7.x86_64.

Here is the different behevior of with and without `--client-quota`. Without `--client-quota` the quota limit is not effective.

There is also not this option of my ceph-fuse, but it does works. Sorry I am not familiar with ceph, is there any more information to collect?

```
# ceph-fuse --version
ceph version 10.2.6 (656b5b63ed7c43bd014bcafd81b001959d5f089f)
# ceph-fuse 
usage: ceph-fuse [-m mon-ip-addr:mon-port] <mount point> [OPTIONS]
  --client_mountpoint/-r <root_directory>
                    use root_directory as the mounted root, rather than the full Ceph tree.

usage: ceph-fuse mountpoint [options]

general options:
    -o opt,[opt...]        mount options
    -h   --help            print help
    -V   --version         print version

FUSE options:
    -d   -o debug          enable debug output (implies -f)
    -f                     foreground operation
    -s                     disable multi-threaded operation

  --conf/-c FILE    read configuration from the given configuration file
  --id/-i ID        set ID portion of my name
  --name/-n TYPE.ID set name
  --cluster NAME    set cluster name (default: ceph)
  --setuser USER    set uid to user or uid (and gid to user's gid)
  --setgroup GROUP  set gid to group or gid
  --version         show version and quit
# ceph-fuse -r  /xxx /mnt/xxx --client-quota
2018-05-24 11:38:21.316079 7fc1c61edec0 -1 init, newargv = 0x7fc1d0286780 newargc=11
ceph-fuse[36268]: starting ceph client
ceph-fuse[36268]: starting fuse
# df -h|grep xxx
ceph-fuse        92M     -     -    - /mnt/xxx
# dd if=/dev/zero of=test2 bs=1M count=100
dd: error writing ‘test2’: Disk quota exceeded
1+0 records in
0+0 records out
0 bytes (0 B) copied, 0.000924576 s, 0.0 kB/s
# ls -l -h
total 101M
-rw-r--r-- 1 root root 100M May 24 11:39 test
-rw-r--r-- 1 root root    0 May 24 11:45 test2
#
# umount /mnt/xxx
# ceph-fuse -r  /xxx /mnt/xxx
2018-05-24 11:38:43.166539 7f6447700ec0 -1 init, newargv = 0x7f645179a780 newargc=11
ceph-fuse[38485]: starting ceph client
ceph-fuse[38485]: starting fuse
# cd /mnt/xxx
# df -h |grep xxx
ceph-fuse        92M     -     -    - /mnt/xxx
# ls -l -h 
total 101M
-rw-r--r-- 1 root root 100M May 22 23:47 test
-rw-r--r-- 1 root root    0 May 22 23:47 test2
# dd if=/dev/zero of=test2 bs=1M count=100
100+0 records in
100+0 records out
104857600 bytes (105 MB) copied, 1.06062 s, 98.9 MB/s
# ls -l -h
total 201M
-rw-r--r-- 1 root root 100M May 24 11:39 test
-rw-r--r-- 1 root root 100M May 24 11:40 test2
# df -h|grep xxx
ceph-fuse        92M  -64Y -108M 100% /mnt/xxx
#
```

**Comment by ltxdzh** [comment]
I made a test for the ```ceph-fuse``` option ```--client-quota```，here is the result.
On ceph-fuse jewel version, the ```--client-quota``` option works well:
```
# ceph-fuse --version
ceph version 10.2.5 (c461ee19ecbc0c5c330aca20f7392c9a00730367)
# ceph-fuse -r /k8s_test /mnt/k8s_test/ --client-quota                    
ceph-fuse[36981]: starting ceph client
2018-06-12 10:30:38.854069 7f5f65a06f00 -1 init, newargv = 0x563cfdf8e7e0 newargc=11
ceph-fuse[36981]: starting fuse
# df -h
Filesystem      Size  Used Avail Use% Mounted on
ceph-fuse        92M     0   92M   0% /mnt/k8s_test
```

On ceph-fuse mimic version, the option ```--client-quota``` is not supported, instead, the quota takes effect automaticlly, if seted with ```setfattr```:
```
# ceph-fuse --version
ceph version 13.2.0 (79a10589f1f80dfe21e8f9794365ed98143071c4) mimic (stable)
# ceph-fuse -r /k8s_test /mnt/k8s_test/ --client-quota
2018-06-12 10:43:05.848 7f1def760c00 -1 init, newargv = 0x5621efe7e530 newargc=8
ceph-fuse[175199]: starting ceph client
fuse: unknown option `--client-quota'
ceph-fuse[175199]: fuse failed to start
2018-06-12 10:43:05.858 7f1def760c00 -1 fuse_lowlevel_new failed
# ceph-fuse -r /k8s_test /mnt/k8s_test/ 
2018-06-12 10:43:10.801 7fd683b14c00 -1 init, newargv = 0x5637922e1140 newargc=7
ceph-fuse[175227]: starting ceph client
ceph-fuse[175227]: starting fuse
# df -h
Filesystem      Size  Used Avail Use% Mounted on
ceph-fuse        92M     0   92M   0% /mnt/k8s_test
```

The two tests use same ceph cluster, mimic version. Considering the comment of @cofyc, I think ceph-fuse has removed the option ```--client-quota``` since luminous version.

**Comment by cofyc** [comment]
According to tests @ltxdzh did, I think we should have some version or feature test logic. It's not safe to add `--client-quota` flag for all ceph-fuse versions.

**Comment by silenceshell** [comment]
@cofyc Would you please help reviewing the code? Thanks.

**Pull request closed without merging**
