### PR TITLE
build debian stable image with dnsutils for e2e

### PR DESCRIPTION
**Pull request by aojea**
/kind cleanup
```release-note
NONE
```

Build a new debian image for e2e tests so we have a libc container in addition to the muslc ones, like agnhost

TODO: Replace jessie image https://github.com/kubernetes/kubernetes/pull/127046

### CODE REVIEW

**Comment by aojea** [comment]
/assign @thockin @BenTheElder 

it has to merge , then promoted and then we can safely replace the jessie image

**Comment by BenTheElder** [comment]
> Build a new debian image for e2e tests so we have a libc container in addition to the muslc ones, like agnhost

IMHO we should switch agnhost to **g**libc?

**Comment by danwinship** [comment]
/hold
commenting on the other bug; we do not need 2 test containers here

**Comment by aojea** [comment]
> /hold commenting on the other bug; we do not need 2 test containers here

agree

**Pull request closed without merging**
