### PR TITLE
Automated cherry pick of #92196: Pods which have not "started" can not be "ready"

### PR DESCRIPTION
**Pull request by matthyx**
Cherry pick of #92196 on release-1.18.

#92196: Pods which have not "started" can not be "ready"

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

Relates to #89995
This is a bug fix for the startupProbe, which is beta in 1.18

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
lgtm, test failures - flakiness

/kind bug
/assign @dashpole 
/retest

Priority of original PR was `priority/important-longterm`. I'm not sure if it's the same in cherry-picks

**Comment by matthyx** [comment]
Thanks @SergeyKanzhelev I quickly made them tonight and was gonna add the missing bits tomorrow morning.
Looks like you are faster than me <3

**Comment by SergeyKanzhelev** [comment]
so what's the guidance on setting priority for cherry-picks? Same as for regular PRs?

**Comment by matthyx** [comment]
That one would be important soon as I would like to fix that bug in the next 1.18 release parch

**Comment by SergeyKanzhelev** [comment]
it looks like only 1.18 owners can approve =)

/unassign @dashpole 
/assign @ dchen1107

/priority important-soon

**Comment by matthyx** [comment]
Maybe Tim can help us here...
/assign @thockin

**Comment by thockin** [comment]
I'm fine to backport this, but I am not an owner for the release branch.

/lgtm

**Comment by matthyx** [comment]
/assign @justaugustus 
Stephen, could you have a look?

**Pull request merged**
