### PR TITLE
nodelocaldns.yaml: remove force_tcp option which used for external dn…

### PR DESCRIPTION
**Pull request by lemonli**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>

/kind cleanup

**What this PR does / why we need it**:
I think `force_tcp` is not necessary when query an external domain name according to this [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/0030-nodelocal-dns-cache.md#proposal) 
and udp may perform better as default.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by prameshj** [comment]
The force_tcp option was removed for stubDomains in node-cache-1.15.13. It could be removed for external dns as well.

**Comment by prameshj** [comment]
Was a specific performance issue observed with the force_tcp option?

**Comment by lemonli** [comment]
> Was a specific performance issue observed with the force_tcp option?
Some cloud providers deny  tcp connections to their dns server

**Comment by lemonli** [comment]
@MrHohn @prameshj  Ready to merge

**Comment by prameshj** [comment]
> /hold
> 
> Would like to understand this more. We did this on purpose to make the upstream more reliable.

This PR is changing the behavior only for external DNS queries. The lookups to clusterDNS will still be over TCP.

**Comment by bowei** [comment]
ok

/remove-hold

**Comment by lemonli** [comment]
@bowei @MrHohn ready to merge, thx.

**Review by MrHohn — APPROVED** [review]
/approve

**Pull request merged**
