### PR TITLE
generated code should pass go vet for go1.10

### PR DESCRIPTION
**Pull request by bhcleek**
**What this PR does / why we need it**:

Update code generator and the code it generates to pass `go vet`.

go1.10 runs `go vet` whenever `go test` is run. Because of this, generated code for CRDs needs to pass `go vet`.

**Release note**:

```release-note
Code generated for CRDs now passes `go vet`.
```

### CODE REVIEW

**Comment by sttts** [comment]
lgtm when it's green
/approve

**Comment by bhcleek** [comment]
The bazel test failures are valid. I'm working on fixing them now.

**Comment by sttts** [comment]
/assign @deads2k 
/assign @DirectXMan12 

for approval.

**Comment by deads2k** [comment]
/approve 
/hold

holding to squash all that generated code into one "generated" commit.

**Comment by bhcleek** [comment]
I rebased to reduce the number of commits; all regenerated fakes are now in a single commit.

**Comment by deads2k** [comment]
it's just the generated expression in metrics.  tagging.

**Pull request merged**
