### PR TITLE
test(kubelet): fix failing test TestDefaultsYAML on non-linux OS

### LINKED ISSUE #73853: TestDefaultsYAML/KubeletConfiguration_default_v1beta1 is failing on MacOS
**Which jobs are failing**:

TestConfigFileAndDefaultsToInternalConfig is failing on MacOS.

**Which test(s) are failing**:

```
$ go test ./cmd/kubeadm/app/util/config/... -v -run TestConfigFileAndDefaultsToInternalConfig
    --- FAIL: TestConfigFileAndDefaultsToInternalConfig/incompleteYAMLToDefaultedv1beta1 (0.00s)
        initconfiguration_test.go:123: the expected and actual output differs.
            	in: testdata/defaulting/master/incomplete.yaml
            	out: testdata/defaulting/master/defaulted.yaml
            	groupversion: kubeadm.k8s.io/v1beta1
            	diff: 
            --- expected
            +++ actual
            @@ -115,7 +115,6 @@
               imagefs.available: 15%!
            (MISSING)   memory.available: 100Mi
               nodefs.available: 10%!
            (MISSING)-  nodefs.inodesFree: 5%!
            (MISSING) evictionPressureTransitionPeriod: 5m0s
             failSwapOn: true
             fileCheckFrequency: 20s
```

**Since when has it been failing**:

**Testgrid link**:

**Reason for failure**: 

`nodefs.inodesFree: 5%` is missing.

**Anything else we need to know**:

Refer https://github.com/kubernetes/kubernetes/pull/67709.

/sig node
/kind bug
/assign

### PR DESCRIPTION
**Pull request by knight42**
Signed-off-by: Jian Zeng <zengjian.zj@bytedance.com>

#### What type of PR is this?

/kind cleanup
/kind failing-test

#### What this PR does / why we need it:

The failing test `TestDefaultsYAML` on non-linux OS is caused by the different default `EvictionHard` on different OS:
* linux: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/v1beta1/defaults_linux.go#L22
* others: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/v1beta1/defaults_others.go#L22

This PR adds separate YAML files for non-linux test to match the different default `EvictionHard`.

#### Which issue(s) this PR fixes:

Fixes #73853

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
> different default `EvictionHard` on different OS

that is the root issue I think we should fix... making API-level defaults OS-specific depending on the OS the config was deserialized on does not work well... it makes it hard to reason about the API values or write config file validation that can run on any OS

**Comment by SergeyKanzhelev** [comment]
@knight42 do you plan to move this PR forward or just close it?

**Comment by dims** [comment]
/close

@knight42 looks like @SergeyKanzhelev was waiting on an answer, please reopen if needed.

**Pull request closed without merging**
