### PR TITLE
cleanup: delete same utils.go in pkg/apis/storage

### PR DESCRIPTION
**Pull request by Abirdcfly**
Signed-off-by: Abirdcfly <fp544037857@gmail.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
```bash
$ diff pkg/apis/storage/util/helpers.go pkg/apis/storage/v1/util/helpers.go
19c19,21
< import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
---
> import (
>       metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
> )
$ diff pkg/apis/storage/util/helpers.go pkg/apis/storage/v1beta1/util/helpers.go

```

There are 3 same files here, one is enough.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Abirdcfly** [comment]
/assign @thockin for approve.PTAL.

I guess `pull-kubernetes-e2e-gce-storage-snapshot` will fail, already reported by https://github.com/kubernetes/kubernetes/issues/110658.

**Comment by pohly** [comment]
I can't think of a reason why those files should be duplicated, so:
/lgtm
/approve

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
