### PR TITLE
bazel: statically link dockerized components

### PR DESCRIPTION
**Pull request by mikedanese**
and remove libc from docker images when it's not needed.

### CODE REVIEW

**Comment by ixdy** [comment]
Only dockerized components? Or should we be statically linking things like kubelet and kubeadm too?

**Comment by ixdy** [comment]
ah, I guess [these](https://github.com/kubernetes/kubernetes/blob/c68ae58c93d71b75c2ba6bcea565431cbbcaf061/hack/lib/golang.sh#L195-L204)?

which means we're missing 
* cloud-controller-manager
* kube-aggregator
* kubeadm

**Comment by ixdy** [comment]
@mikedanese can you add those ^ three binaries?

**Comment by mikedanese** [comment]
Done.

**Comment by ixdy** [comment]
that was weird.
@k8s-bot bazel test this

**Comment by mikedanese** [comment]
@thockin mind approving?

**Pull request merged**
