### PR TITLE
Use Go 1.21 Ordered and clear for sets

### PR DESCRIPTION
**Pull request by skitt**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Go 1.21 provides its own type constraint permitting ordered types, cmp.Ordered; use that instead of the private ordered constraint.

Go 1.21 introduces a clear function for maps, use that to clear sets.

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jiahuif** [comment]
/lgtm
/assign @jpbetz 
for `k8s.io/apimachinery/OWNERS`

**Comment by dims** [comment]
`ordered` is private, so there's definitely no users outside k/k. +1 to the cleanup. 

@skitt are you happy with the existing tests to cover any change in behavior?

/lgtm
/assign @liggitt

**Comment by skitt** [comment]
> @skitt are you happy with the existing tests to cover any change in behavior?

@dims I could always add more tests but I’m not sure they’d be all that useful. The coverage seems fine to me as-is.

**Pull request merged**
