### PR TITLE
KEP-127: api: add user namespaces field to NodeRuntimeHandlerFeatures

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind api-change
/kind bug
#### What this PR does / why we need it:
with all of the churn at the end of 1.30, it seems this piece was missed

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Added information about user namespace support into node status. The kubelet now populates this information into `.status.runtimeHandlers[]` if the kernel, OCI runtime, CRI implementation and kubelet support UserNamespaces.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sftim** [comment]
Changelog suggestion
```diff
-expose UserNamespace support in the node status RuntimeHandler structure, so a user can query whether a node supports user namespaces or not, without attempting to create a pod and failing to do so.
+Added information about user namespace support into node status.
+The kubelet now populates this information into `.status.runtimeHandlers[]` if the associated features are
+enabled and configured.
```

**Comment by haircommander** [comment]
updated! thanks for the suggestion

**Comment by haircommander** [comment]
closing in favor of https://github.com/kubernetes/kubernetes/pull/126034

**Pull request closed without merging**
