### PR TITLE
test/e2e/framework: handle the case where BeforeEach was never called 

### LINKED ISSUE #87536: Test panic in "AfterEach" for skipped tests during "AllNodesReady"
**What happened**:
When running external CSI Driver tests with the Kubernetes E2E: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/sigs.k8s.io_gcp-compute-persistent-disk-csi-driver/458/pull-gcp-compute-persistent-disk-csi-driver-kubernetes-integration/1220789322400141312/

We seem to be getting the following error.

```
I0124 20:03:31.324] [BeforeEach] [Testpattern: Pre-provisioned PV (block volmode)] multiVolume [Slow]
I0124 20:03:31.324]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go:95
I0124 20:03:31.324] Jan 24 20:03:31.150: INFO: Driver supports dynamic provisioning, skipping PreprovisionedPV pattern
I0124 20:03:31.329] [AfterEach] [Testpattern: Pre-provisioned PV (block volmode)] multiVolume [Slow]
I0124 20:03:31.329]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:175
I0124 20:03:31.329] Jan 24 20:03:31.151: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
I0124 20:03:31.329] E0124 20:03:31.152140   71880 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
I0124 20:03:31.329] goroutine 143 [running]:
I0124 20:03:31.330] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x41cc500, 0x7c969c0)
I0124 20:03:31.330] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
I0124 20:03:31.330] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
I0124 20:03:31.330] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
I0124 20:03:31.330] panic(0x41cc500, 0x7c969c0)
I0124 20:03:31.331] 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
I0124 20:03:31.331] k8s.io/kubernetes/test/e2e/framework.AllNodesReady.func1(0xc00243cc50, 0xc00056a000, 0x7f5987da1d98)
I0124 20:03:31.331] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:1351 +0x5e
I0124 20:03:31.331] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc00243cde0, 0xbedf00, 0x0, 0x0)
I0124 20:03:31.332] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:209 +0x6f
I0124 20:03:31.332] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.pollImmediateInternal(0xc000894b80, 0xc00243cde0, 0xc000894b80, 0x1)
I0124 20:03:31.332] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:344 +0x2f
I0124 20:03:31.342] k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.PollImmediate(0x77359400, 0x29e8d60800, 0xc00243cde0, 0x33, 0xc00243cda0)
I0124 20:03:31.343] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:340 +0x4d
I0124 20:03:31.343] k8s.io/kubernetes/test/e2e/framework.AllNodesReady(0x0, 0x0, 0x29e8d60800, 0x4aca277, 0xb)
I0124 20:03:31.343] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:1348 +0x17f
I0124 20:03:31.343] k8s.io/kubernetes/test/e2e/framework.(*Framework).AfterEach(0xc00221dcc0)
I0124 20:03:31.344] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:457 +0x43c
I0124 20:03:31.344] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc001976f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
I0124 20:03:31.345] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113 +0xb8
I0124 20:03:31.345] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc001976f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
I0124 20:03:31.345] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:64 +0xcf
I0124 20:03:31.346] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*SetupNode).Run(0xc0022657d8, 0x53a8460, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
I0124 20:03:31.346] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/setup_nodes.go:15 +0x64
I0124 20:03:31.346] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample.func1(0xc00243d6e0, 0xc002f444b0, 0x53a8460, 0xc0001188c0)
I0124 20:03:31.346] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:180 +0x344
I0124 20:03:31.347] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc002f444b0, 0x0, 0x53a8460, 0xc0001188c0)
I0124 20:03:31.347] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:197 +0x2e6
I0124 20:03:31.347] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc002f444b0, 0x53a8460, 0xc0001188c0)
I0124 20:03:31.347] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0x101
I0124 20:03:31.348] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc002c103c0, 0xc002f444b0, 0x4)
I0124 20:03:31.348] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0x10f
I0124 20:03:31.348] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc002c103c0, 0x1)
I0124 20:03:31.349] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x120
I0124 20:03:31.349] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc002c103c0, 0xc0020d70f8)
I0124 20:03:31.350] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:66 +0x117
I0124 20:03:31.350] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc0001022d0, 0x7f5984092e50, 0xc001e90f00, 0x4af08de, 0x14, 0xc0026ea750, 0x3, 0x3, 0x5473440, 0xc0001188c0, ...)
I0124 20:03:31.350] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:62 +0x42b
I0124 20:03:31.351] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0x53ac980, 0xc001e90f00, 0x4af08de, 0x14, 0xc002ce41c0, 0x3, 0x4, 0x4)
I0124 20:03:31.351] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:226 +0x217
I0124 20:03:31.351] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters(0x53ac980, 0xc001e90f00, 0x4af08de, 0x14, 0xc001fae860, 0x2, 0x2, 0x2)
I0124 20:03:31.351] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:214 +0xad
I0124 20:03:31.352] k8s.io/kubernetes/test/e2e.RunE2ETests(0xc001e90f00)
I0124 20:03:31.352] 	_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:110 +0x30a
I0124 20:03:31.352] k8s.io/kubernetes/test/e2e.TestE2E(0xc001e90f00)
I0124 20:03:31.352] 	_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:111 +0x2b
I0124 20:03:31.356] testing.tRunner(0xc001e90f00, 0x4c9fc68)
I0124 20:03:31.356] 	/usr/local/go/src/testing/testing.go:909 +0xc9
I0124 20:03:31.356] created by testing.(*T).Run
I0124 20:03:31.357] 	/usr/local/go/src/testing/testing.go:960 +0x350
I0124 20:03:31.357] 
I0124 20:03:31.357] 
I0124 20:03:31.358] S [SKIPPING] in Spec Setup (BeforeEach) [0.003 seconds]
I0124 20:03:31.358] External Storage [Driver: csi-gcepd]
I0124 20:03:31.358] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/external/external.go:165
I0124 20:03:31.358]   [Testpattern: Pre-provisioned PV (block volmode)] multiVolume [Slow]
I0124 20:03:31.358]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go:94
I0124 20:03:31.359]     should access to two volumes with different volume mode and retain data across pod recreation on the same node [BeforeEach]
I0124 20:03:31.359]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/multivolume.go:211
I0124 20:03:31.359] 
I0124 20:03:31.359]     Driver supports dynamic provisioning, skipping PreprovisionedPV pattern
I0124 20:03:31.359] 
I0124 20:03:31.360]     /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/base.go:688
```

From initial investigation it looks like this happens in the `AfterEach` during `AllNodesReady` check but only when the test is being skipped. Hunch is that maybe since the test is skipped some resources are never created or they are cleaned up already and they are nil when the `AfterEach` is called and expecting them. Kind of low priority since it doesn't make any tests actually fail.

/cc @msau42 @misterikkit 
/sig storage

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:

Some tests under e2e/storage never end up calling the
Framework#BeforeEach() prolog. Handle such cases by returning
early in AfterEach() by checking a new field "beforeEachStarted".

Also add a nil check for ClientSet in AfterEach().

see discussion in https://github.com/kubernetes/kubernetes/pull/87338#issuecomment-577929755

**Which issue(s) this PR fixes**:

fixes https://github.com/kubernetes/kubernetes/issues/87536

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/kind bug
/priority critical-urgent

/cc @spiffxp @lavalamp @liggitt @BenTheElder @oomichi

### CODE REVIEW

**Comment by liggitt** [comment]
Is this intended to merge or just to debug what test is misbehaving?

**Comment by neolit123** [comment]
> Is this intended to merge or just to debug what test is misbehaving?

i was intending it to merge, but if there are objections it's fine to run it on PR level.

/hold
/approve cancel

**Comment by neolit123** [comment]
these stack traces are not very useful:
```
I0124 04:27:43.966] [BeforeEach] [Testpattern: Inline-volume (default fs)] subPath
I0124 04:27:43.966]   test/e2e/storage/testsuites/base.go:95
I0124 04:27:43.966] Jan 24 04:27:43.465: INFO: Driver supports dynamic provisioning, skipping InlineVolume pattern
I0124 04:27:43.966] [AfterEach] [Testpattern: Inline-volume (default fs)] subPath
I0124 04:27:43.966]   test/e2e/framework/framework.go:175
I0124 04:27:43.966] Jan 24 04:27:43.466: FAIL: The framework ClientSet must not be nil at this point
I0124 04:27:43.966] 
I0124 04:27:43.966] Full Stack Trace
I0124 04:27:44.078] k8s.io/kubernetes/test/e2e/framework.(*Framework).AfterEach(0xc000a34640)
I0124 04:27:44.078] 	test/e2e/framework/framework.go:364 +0xc8a
I0124 04:27:44.078] k8s.io/kubernetes/test/e2e.RunE2ETests(0xc000cfe100)
I0124 04:27:44.078] 	test/e2e/e2e.go:110 +0x30a
I0124 04:27:44.079] k8s.io/kubernetes/test/e2e.TestE2E(0xc000cfe100)
I0124 04:27:44.079] 	test/e2e/e2e_test.go:111 +0x2b
I0124 04:27:44.079] testing.tRunner(0xc000cfe100, 0x4ca75e8)
I0124 04:27:44.079] 	GOROOT/src/testing/testing.go:909 +0xc9
I0124 04:27:44.080] created by testing.(*T).Run
I0124 04:27:44.080] 	GOROOT/src/testing/testing.go:960 +0x350
I0124 04:27:44.080] 
```

we also have the option to re-create the ClientSet in AfterEach. this will ensure that all cleanup API calls pass.

as noted in the OP and the discussion in the other tickets, all errors come from sig-storage tests. these tests seem to be nil-ing the framwork.ClientSet, but i cannot find where.

@kubernetes/sig-storage-bugs 
do you have anyone who is familiar with your test setup?

**Comment by pohly** [comment]
I'm trying to reproduce it.

**Comment by pohly** [comment]
The problem is that `f.BeforeEach` isn't called for those tests where the failure occurs (confirmed in dlv). These tests are intentionally written so that they register some `BeforeEach` callback where they check some conditions *before* invoking `NewFramework` and thus those checks run before `f.BeforeEach`. If the checks fail, the test gets skipped quickly because the somewhat slow `f.BeforeEach/AfterEach` pair is avoided.

Has Ginkgo been updated recently? This used to work. That `f.AfterEach` is now getting called without the corresponding `f.BeforeEach` looks suspicious.

**Comment by pohly** [comment]
> Has Ginkgo been updated recently? This used to work. That f.AfterEach is now getting called without the corresponding f.BeforeEach looks suspicious.

No, it was the same before, for example in 1.17.0. The difference is that the nil pointer access is now detected whereas e2e.test in 1.17.0 silently ignored it.

This still looks like suspicious behavior in Ginkgo, but as it is what it is, the easiest solution would be to replace the if check in this PR with:
```
	if f.ClientSet == nil {
                // This can happen because framework.BeforeEach was not called, for example
                // because another BeforeEach callback called ginkgo.Skip. At least Ginkgo
                // v1.10.1 then still calls framework.AfterEach.
                return
	}
```

**Comment by liggitt** [comment]
> The problem is that `f.BeforeEach` isn't called for those tests where the failure occurs 

does that explain test runs that pass, but still encounter this?

**Comment by neolit123** [comment]
> This still looks like suspicious behavior in Ginkgo, but as it is what it is, the easiest solution would be to replace the if check in this PR with:


how about constructing a client a allowing AfterEach to do the namespace cleanup etc?

**Comment by neolit123** [comment]
> These tests are intentionally written so that they register some BeforeEach callback where they check some conditions before invoking NewFramework and thus those checks run before f.BeforeEach. If the checks fail, the test gets skipped quickly because the somewhat slow f.BeforeEach/AfterEach pair is avoided.

maybe these tests should simply avoid calling AfterEach too. i think it's possible to overload it...

**Comment by pohly** [comment]
> does that explain test runs that pass, but still encounter this?

Yes. I think Ginkgo marks the test as "skipped" when `ginkgo.Skip` is called and then ignores all ensuing errors. That's also why the test runs for this PR show no failing tests although the new `Failf` is called multiple times.

> how about constructing a client and allowing AfterEach to do the namespace cleanup etc?

There is no namespace cleanup which needs to be done in this case. That was the whole point of skipping before `framework.BeforeEach` is called. If checking `f.ClientSet` feels unclean, then a new internal `f.initialized` boolean could be introduced, too.

Hmm, but that still doesn't handle the case well where `framework.BeforeEach` was called but then failed halfway through. In that case we want `framework.AfterEach` to be called (which Ginkgo probably does, given that it even calls it when `framework.BeforeEach` wasn't called at all...) and then clean up whatever resources were allocated.

> maybe these tests should simply avoid calling AfterEach too. i think it's possible to overload it...

The tests don't even know that `framework.BeforeEach` and `framework.AfterEach` exist. They are exported, but only used internally in `NewFramework` (https://github.com/kubernetes/kubernetes/blob/c398c9c9da4e7e0a7ef62ff3c5b630d9fcf5c262/test/e2e/framework/framework.go#L152-L178).

So no, I don't think the test can or should force `framework.AfterEach` to be skipped.

**Comment by neolit123** [comment]
> If checking f.ClientSet feels unclean, then a new internal f.initialized boolean could be introduced, too.

i think not using f.ClientSet as the marker whether BeforeEach was run or not is the better decision.

> Hmm, but that still doesn't handle the case well where framework.BeforeEach was called but then failed halfway through. In that case we want framework.AfterEach to be called (which Ginkgo probably does, given that it even calls it when framework.BeforeEach wasn't called at all...) and then clean up whatever resources were allocated.

i think if BeforeEach is even entered we need a marker that indicates that, in which case AfterEach should be called too.

are you willing to send a PR for that?

**Comment by pohly** [comment]
> i think if BeforeEach is even entered we need a marker that indicates that, in which case AfterEach should be called too

We don't control whether `framework.AfterEach` is called. I don't want to be pedantic, just very clear :man_shrugging: All we can do is control what we do in `framework.AfterEach`.

> are you willing to send a PR for that?

For the marker, or for making `framework.AfterEach` also tolerant against partial execution of `framework.BeforeEach`?

**Comment by neolit123** [comment]
> For the marker, or for making framework.AfterEach also tolerant against partial execution of framework.BeforeEach?

aside from using a marker i don't know what other way we have to make framework.AfterEach tolerant against partial execution of framework.BeforeEach.

```
func (f *Framework) BeforeEach() {
   f.beforeEachStarted = true
   // construct client
   ...
}
```

```
func (f *Framework) AfterEach() {
   if !f.beforeEachStarted {
      // log a message and return...
   }
   if f.ClientSet == nil {
      // fail, this should not happen....
   }
   ...
}
```

we should have the client set nil check in any case because i saw there is at least one test under e2e/network that modifies f.ClientSet directly.

**Comment by lavalamp** [comment]
I agree with everything in @neolit123's comment, let's do that.

**Comment by pohly** [comment]
> aside from using a marker i don't know what other way we have to make `framework.AfterEach`tolerant against partial execution of framework.BeforeEach

At each operation in `AfterEach` it could check whether the corresponding operation in `BeforeEach` has completed.

For example, `f.gatherer` gets set here: https://github.com/kubernetes/kubernetes/blob/e92a7cfd2a82cd483229fecc1020f0d5eda31dc7/test/e2e/framework/framework.go#L263

But if `BeforeEach` doesn't get that far, then `f.gatherer` will be nil although `BeforeEach` was called. It looks like someone has anticipated that, because there is a `f.gatherer != nil` check here before using it: https://github.com/kubernetes/kubernetes/blob/e92a7cfd2a82cd483229fecc1020f0d5eda31dc7/test/e2e/framework/framework.go#L413

> ```
> func (f *Framework) BeforeEach() {
>   f.beforeEachStarted = true
>   // construct client
>   ...
>}
>
> func (f *Framework) AfterEach() {
>  if !f.beforeEachStarted {
>     // log a message and return...
>  }
>  if f.ClientSet == nil {
>     // fail, this should not happen....
> }
>  ...
> }

I don't think that there should be a log message when `f.beforeEachStarted` wasn't called. It's normal for the storage tests.

I suspect the `f.beforeEachStarted` check will just hide problems in AfterEach where if checks are missing. If it gets set at the start as shown here, then when `BeforeEach` fails, we still enter `AfterEach` and then who knows what'll happen, because it is not something that happens regularly and thus will be untested. If it gets set at the end instead, then `AfterEach` will not clean up partially allocated resources after a `BeforeEach` failure.

**Comment by lavalamp** [comment]
That also seems like a great point, but is maybe a step 2 fix?

A fully general fix might involve something like:
* splitting every component creation/deletion into separate functions
* When the creation function finishes, it adds the deletion function to a list 
* AfterEach executes every function in the list

**Comment by neolit123** [comment]
@pohly 

> But if BeforeEach doesn't get that far, then f.gatherer will be nil although BeforeEach was called. It looks like someone has anticipated that, because there is a f.gatherer != nil check here before using it:

checking everything for `!= nil` in AfterEach is an option.

> I don't think that there should be a log message when f.beforeEachStarted wasn't called. It's normal for the storage tests.

ok, SGTM.

> I suspect the f.beforeEachStarted check will just hide problems in AfterEach where if checks are missing. If it gets set at the start as shown here, then when BeforeEach fails, we still enter AfterEach and then who knows what'll happen, because it is not something that happens regularly and thus will be untested

these seem like cases where we want to panic and error out.
with the early `beforeEachStarted` we catch the sig-storage special case which decides to completely skip BeforeEach.

i can update this PR to fix the sig-storage problem. but we can log an issue for future refactors if you think this is something that we should do.

**Comment by pohly** [comment]
> i can update this PR to fix the sig-storage problem. but we can log an issue for future refactors if you think this is something that we should do.

That's probably the fastest fix at the moment. Please go ahead.

**Comment by neolit123** [comment]
i do not see the panics after this change. retesting due to flakes.

**Comment by neolit123** [comment]
something went wrong in pull-k8s-e2e-gce:

```
> I0124 23:56:18.781] push-build.sh::release::gcs::bazel_push_build(): rm -rf /go/src/k8s.io/kubernetes/_output/gcs-stage/v1.18.0-alpha.2.128+7ab6c4f0d2ebc3
I0124 23:56:18.793] 
I0124 23:56:18.793] push-build.sh::release::gcs::bazel_push_build(): mkdir -p /go/src/k8s.io/kubernetes/_output/gcs-stage/v1.18.0-alpha.2.128+7ab6c4f0d2ebc3
I0124 23:56:21.604] Checking whether gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce/v1.18.0-alpha.2.128+7ab6c4f0d2ebc3 already exists: - Destination exists. To remove, run:
I0124 23:56:21.631]   gsutil -m rm -r
I0124 23:56:21.631]   gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce/v1.18.0-alpha.2.128+7ab6c4f0d2ebc3
I0124 23:56:21.651] flag --allow-dup set, continue with overwriting
I0124 23:56:21.685] OK
I0124 23:56:21.719] Publish release artifacts to gs://kubernetes-release-pull using Bazel...
I0124 23:56:21.754] - Hashing and copying public release artifacts to
I0124 23:56:21.754] gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce/v1.18.0-alpha.2.128+7ab6c4f0d2ebc3:
W0124 23:56:21.855] $TEST_TMPDIR defined: output root default is '/bazel-scratch/.cache/bazel' and max_idle_secs default is '15'.
W0125 01:10:32.112] 2020/01/25 01:10:32 process.go:199: Interrupt after 1h20m0s timeout during /go/src/k8s.io/release/push-build.sh --nomock --verbose --noupdatelatest --bucket=kubernetes-release-pull --ci --gcs-suffix=/pull-kubernetes-e2e-gce --allow-dup. Will terminate in another 15m
W0125 01:10:32.117] 
W0125 01:10:32.117] Bazel caught interrupt signal; shutting down.
W0125 01:10:32.117] 
```

https://prow.k8s.io/log?id=1220855865557389314&job=pull-kubernetes-e2e-gce

/retest pull-kubernetes-e2e-gce

**Comment by spiffxp** [comment]
/retest
flake https://github.com/kubernetes/kubernetes/issues/87441

**Pull request merged**
