### PR TITLE
Automated cherry pick of #59276: kubelet: only register api source when connecting

### PR DESCRIPTION
**Pull request by roboll**
Cherry pick of #59276 on release-1.9.

#59276: kubelet: only register api source when connecting

### CODE REVIEW

**Comment by roboll** [comment]
@mbohlool any chance you can put some eyes on this so it can make it into 1.9.4?

**Comment by mbohlool** [comment]
Is there any test for this?

**Comment by roboll** [comment]
@mbohlool and I talked in slack, no tests for this unfortunately. (it is tested manually)

open to pointers on how to write a test for this, but i'm not familiar with the e2e test machinery.

**Comment by yujuhong** [comment]
/test pull-kubernetes-e2e-kops-aws

The existing e2e test frameworks all assume apiserver is available, so it's going to be non-trivial to add a test there.
Since this PR is fixing a relatively uncommon kubelet mode (i.e., standalone) and has been verified manually, could we let the cherrypick go through? @mbohlool

**Pull request merged**
