### PR TITLE
Fix static IP issue for Azure internal LB

### LINKED ISSUE #56686: Azure internal loadbalancer with user specified IP broken
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
E2E case `[It] should be able to create an internal type load balancer [Slow] [DisabledForLargeClusters]` fails on Azure

```
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/service.go:49
[It] should be able to create an internal type load balancer [Slow] [DisabledForLargeClusters]
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1403
�[1mSTEP�[0m: creating pod to be part of service lb-internal
Dec  1 08:59:32.938: INFO: Waiting up to 2m0s for 1 pods to be created
Dec  1 08:59:33.158: INFO: Found all 1 pods
Dec  1 08:59:33.158: INFO: Waiting up to 2m0s for 1 pods to be running and ready: [lb-internal-d8sdv]
Dec  1 08:59:33.158: INFO: Waiting up to 2m0s for pod "lb-internal-d8sdv" in namespace "e2e-tests-services-w5qln" to be "running and ready"
Dec  1 08:59:33.378: INFO: Pod "lb-internal-d8sdv": Phase="Pending", Reason="", readiness=false. Elapsed: 220.083953ms
Dec  1 08:59:35.599: INFO: Pod "lb-internal-d8sdv": Phase="Pending", Reason="", readiness=false. Elapsed: 2.44126331s
Dec  1 08:59:37.820: INFO: Pod "lb-internal-d8sdv": Phase="Running", Reason="", readiness=false. Elapsed: 4.661891757s
Dec  1 08:59:40.040: INFO: Pod "lb-internal-d8sdv": Phase="Running", Reason="", readiness=true. Elapsed: 6.882135395s
Dec  1 08:59:40.040: INFO: Pod "lb-internal-d8sdv" satisfied condition "running and ready"
Dec  1 08:59:40.040: INFO: Wanted all 1 pods to be running and ready. Result: true. Pods: [lb-internal-d8sdv]
�[1mSTEP�[0m: creating a service with type LoadBalancer and cloud specific Internal-LB annotation enabled
Dec  1 08:59:40.312: INFO: Waiting up to 20m0s for service "lb-internal" to have a LoadBalancer
�[1mSTEP�[0m: switching to external type LoadBalancer
Dec  1 08:59:57.223: INFO: Waiting up to 20m0s for service "lb-internal" to have an external LoadBalancer
�[1mSTEP�[0m: switching back to interal type LoadBalancer, with static IP specified.
Dec  1 09:03:18.138: INFO: Waiting up to 20m0s for service "lb-internal" to have an internal LoadBalancer
Dec  1 09:23:18.799: INFO: Loadbalancer IP not changed to internal.
[AfterEach] [sig-network] Services
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:135
�[1mSTEP�[0m: Collecting events from namespace "e2e-tests-services-w5qln".
�[1mSTEP�[0m: Found 12 events.
```

Error log is:
```
E1201 10:07:04.387097       1 service_controller.go:776] Failed to process service e2e-tests-services-qchsw/lb-internal. Retrying in 5m0s: failed to ensure load balancer for service e2e-tests-services-qchsw/lb-internal: user supplied IP Address 10.240.11.11 was not found
```

In #55740, determinePublicIPName is called even if internal load balancer wanted, and static IP specified. But it will fail when user specifies a static IP.

This is a regression in v1.9.0-beta.1

**What you expected to happen**:
The internal balancer with specified static IP should work.

**How to reproduce it (as minimally and precisely as possible)**:
```
kind: Service
apiVersion: v1
metadata:
  name: ng-in-static
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    a: a1
  type: LoadBalancer
  loadBalancerIP: 10.240.11.11
```

**Anything else we need to know?**:

**Environment**:
```
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-beta.1", GitCommit:"5898890a735c4e418a33f41b960f816824d0587c", GitTreeState:"clean", BuildDate:"2017-11-30T19:37:07Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by karataliu**
**What this PR does / why we need it**:
Fix regression for Azure internal LB with static IP support

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #56686

**Special notes for your reviewer**:

**Release note**:
```release-note

```

### CODE REVIEW

**Comment by andyzhangx** [comment]
/lgtm
cc @jdumars
This works in v1.9.0-beta.0, but fails in v1.9.0-beta.1 . Could you mark it as v1.9 milestone? Thanks.

**Comment by karataliu** [comment]
@brendandburns could you please take a look?

**Comment by dims** [comment]
@colemickens @jdumars - please approve if appropriate

**Pull request merged**
