### PR TITLE
Automated cherry pick of #38836 #39114 #39059 upstream release 1.5

### LINKED ISSUE #38322: Memory pressure shouldn't hard evict static pods
If a node runs out of memory, we kill something. Then if there is memory pressure, we don't admit best effort (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/eviction_manager.go#L110). Maybe we can admit static-pods, even if they're best effort? 

@kubernetes/sig-node if we can't differentiate static from non-static, maybe we can use the `scheduler.alpha.kubernetes.io/critical-pod` annotation?

### PR DESCRIPTION
**Pull request by dchen1107**
Fixed #38322

**Release note**:

```
* Kubelet admits critical pods including kube-proxy even under memory pressure
* Make critical pods have the same oom score as the guaranteed pods
* Stop evicting static pods
```

### CODE REVIEW

**Comment by saad-ali** [comment]
@k8s-bot cri node e2e test this

**Comment by saad-ali** [comment]
@k8s-bot node e2e test this

**Comment by saad-ali** [comment]
@k8s-bot cri node e2e test this

**Comment by saad-ali** [comment]
@k8s-bot node e2e test this

**Comment by dchen1107** [comment]
pr https://github.com/kubernetes/kubernetes/pull/39630 was merged into 1.5 branch, which should address https://github.com/kubernetes/kubernetes/issues/39597 for 1.5 node e2e failure above. 

@k8s-bot node e2e test this

**Comment by dchen1107** [comment]
@k8s-bot cri node e2e test this

**Comment by saad-ali** [comment]
All checks are green. Manually merging since submit queue is blocked.

```
All checks have passed
14 successful checks
```

**Pull request merged**
