### PR TITLE
Add link to v1 docs

### PR DESCRIPTION
**Pull request by bgrant0607**
Adds link to v1 docs

cc @thockin @RichieEscarez @caesarxuchao

### CODE REVIEW

**Comment by bgrant0607** [comment]
I'll rebase this once #11636 goes in.

**Comment by thockin** [comment]
LGTM.  Trying to raise Richie to coordinate

**Comment by bgrant0607** [comment]
Rebased to drop the other commit

**Comment by bgrant0607** [comment]
Merging to make progress.

**Pull request merged**
