### PR TITLE
Delete failing kubectl skew test

### PR DESCRIPTION
**Pull request by fabianofranz**
**What this PR does / why we need it**: Deletes a `kubectl` test in the **release-1.7** branch that always fails skew tests against a 1.8 cluster.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/kubernetes/kubernetes/issues/51048

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fabianofranz** [comment]
@k8s-merge-robot wake up.

**Comment by fabianofranz** [comment]
@k8s-merge-robot thou shalt behave.
/retest

**Comment by pwittrock** [comment]
Added queue - blocks others since this fixes a release blocking test that we want for cutting alphas.

**Pull request merged**
