### PR TITLE
fix evented pleg global pod cache update issue

### LINKED ISSUE #123087: kubelet started multi-containers for static pods when EventedPLEG is enabled
### What happened?

See context in https://github.com/kubernetes/kubernetes/issues/122721 and 

### What did you expect to happen?

Static Pods should be started normally when EventedPLEG is enabled.

- revert to alpha due to this bug: https://github.com/kubernetes/kubernetes/pull/122697
- 

### How can we reproduce it (as minimally and precisely as possible)?

It is observed in alpha CIs like #122721.

### Anything else we need to know?

EventedPLEG has a known issue: https://github.com/kubernetes/kubernetes/issues/121349, and it will cause static pod startup failure(most time)

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by wxx213**
This PR is also a try to fix #123087 
The latest CI reproduce is in #127063, and the failed test is [pull-kubernetes-e2e-kind-alpha-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/127063/pull-kubernetes-e2e-kind-alpha-features/1830544265197916160)

The failed pod(with dup container) is [etcd-kind-control-plane](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/127063/pull-kubernetes-e2e-kind-alpha-features/1830544265197916160/artifacts/kind-control-plane/pods/kube-system_etcd-kind-control-plane_8576f269a22e23776703c0b546bd96cd/etcd/) where the second container start failed with error `"discovery failed","error":"listen tcp 172.18.0.2:2380: bind: address already in use"`

I checked the [kubelet.log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/127063/pull-kubernetes-e2e-kind-alpha-features/1830544265197916160/artifacts/kind-control-plane/kubelet.log) for the pod etcd-kind-control-plane, and I found the second [SyncPod](https://github.com/kubernetes/kubernetes/blob/bce499c13661a9b6c376caa53655a132d903d79b/pkg/kubelet/kubelet.go#L1750) function is called before the pod app container `Started` event arrived in EventedPLEG which makes the second [SyncPod](https://github.com/kubernetes/kubernetes/blob/bce499c13661a9b6c376caa53655a132d903d79b/pkg/kubelet/kubelet.go#L1750) work only got the `Created`  state for the pod app container, then the dup container was created.

```
Sep 02 10:03:25 kind-control-plane kubelet[256]: I0902 10:03:25.131007     256 kubelet.go:1758] "SyncPod enter" pod="kube-system/etcd-kind-control-plane" podUID="8576f269a22e23776703c0b546bd96cd"

Sep 02 10:03:25 kind-control-plane kubelet[256]: I0902 10:03:25.132798     256 evented.go:295] "Received Container Started Event" event="&ContainerEventResponse{ContainerId:9c970048c3076261a8641ecc39b7bcea0b902fdf3be732c30dcda56671257661,ContainerEventType:CONTAINER_STARTED_EVENT,CreatedAt:1725271405127989525,PodSandboxStatus:&PodSandboxStatus{Id:86cd2a05f3aa427058a85365f466a8520e9c160bb6a8ab83d5f93e8b02f88de1,Metadata:&PodSandboxMetadata{Name:etcd-kind-control-plane,Uid:8576f269a22e23776703c0b546bd96cd,Namespace:kube-system,Attempt:0,},State:SANDBOX_READY,CreatedAt:1725271402556627049,Network:&PodSandboxNetworkStatus{Ip:,AdditionalIps:[]*PodIP{},},Linux:&LinuxPodSandboxStatus{Namespaces:&Namespace{Options:&NamespaceOption{Network:NODE,Pid:CONTAINER,Ipc:POD,TargetId:,UsernsOptions:&UserNamespace{Mode:NODE,Uids:[]*IDMapping{},Gids:[]*IDMapping{},},},},},Labels:map[string]string{component: etcd,io.kubernetes.pod.name: etcd-kind-control-plane,io.kubernetes.pod.namespace: kube-system,io.kubernetes.pod.uid: 8576f269a22e23776703c0b546bd96cd,tier: control-plane,},Annotations:map[string]string{kubeadm.kubernetes.io/etcd.advertise-client-urls: https://172.18.0.2:2379,kubernetes.io/config.hash: 8576f269a22e23776703c0b546bd96cd,kubernetes.io/config.seen: 2024-09-02T10:03:22.097057905Z,kubernetes.io/config.source: file,},RuntimeHandler:,},ContainersStatuses:[]*ContainerStatus{&ContainerStatus{Id:9c970048c3076261a8641ecc39b7bcea0b902fdf3be732c30dcda56671257661,Metadata:&ContainerMetadata{Name:etcd,Attempt:0,},State:CONTAINER_RUNNING,CreatedAt:1725271404930307430,StartedAt:1725271405125058026,FinishedAt:0,ExitCode:0,Image:&ImageSpec{Image:registry.k8s.io/etcd:3.5.15-0,Annotations:map[string]string{},UserSpecifiedImage:,RuntimeHandler:,},ImageRef:sha256:2e96e5913fc06e3d26915af3d0f2ca5048cc4b6327e661e80da792cbf8d8d9d4,Reason:,Message:,Labels:map[string]string{io.kubernetes.container.name: etcd,io.kubernetes.pod.name: etcd-kind-control-plane,io.kubernetes.pod.namespace: kube-system,io.kubernetes.pod.uid: 8576f269a22e23776703c0b546bd96cd,},Annotations:map[string]string{io.kubernetes.container.hash: cdf7d3fa,io.kubernetes.container.restartCount: 0,io.kubernetes.container.terminationMessagePath: /dev/termination-log,io.kubernetes.container.terminationMessagePolicy: File,io.kubernetes.pod.terminationGracePeriod: 30,},Mounts:[]*Mount{&Mount{ContainerPath:/var/lib/etcd,HostPath:/var/lib/etcd,Readonly:false,SelinuxRelabel:false,Propagation:PROPAGATION_PRIVATE,UidMappings:[]*IDMapping{},GidMappings:[]*IDMapping{},RecursiveReadOnly:false,Image:nil,},&Mount{ContainerPath:/etc/kubernetes/pki/etcd,HostPath:/etc/kubernetes/pki/etcd,Readonly:false,SelinuxRelabel:false,Propagation:PROPAGATION_PRIVATE,UidMappings:[]*IDMapping{},GidMappings:[]*IDMapping{},RecursiveReadOnly:false,Image:nil,},&Mount{ContainerPath:/etc/hosts,HostPath:/var/lib/kubelet/pods/8576f269a22e23776703c0b546bd96cd/etc-hosts,Readonly:false,SelinuxRelabel:false,Propagation:PROPAGATION_PRIVATE,UidMappings:[]*IDMapping{},GidMappings:[]*IDMapping{},RecursiveReadOnly:false,Image:nil,},&Mount{ContainerPath:/dev/termination-log,HostPath:/var/lib/kubelet/pods/8576f269a22e23776703c0b546bd96cd/containers/etcd/93996d20,Readonly:false,SelinuxRelabel:false,Propagation:PROPAGATION_PRIVATE,UidMappings:[]*IDMapping{},GidMappings:[]*IDMapping{},RecursiveReadOnly:false,Image:nil,},},LogPath:/var/log/pods/kube-system_etcd-kind-control-plane_8576f269a22e23776703c0b546bd96cd/etcd/0.log,Resources:&ContainerResources{Linux:&LinuxContainerResources{CpuPeriod:100000,CpuQuota:0,CpuShares:102,MemoryLimitInBytes:0,OomScoreAdj:-997,CpusetCpus:,CpusetMems:,HugepageLimits:[]*HugepageLimit{},Unified:map[string]string{},MemorySwapLimitInBytes:0,},Windows:nil,},ImageId:,User:nil,},},}"
```
In normally, the `Started` event timeline is always ahead of the the second [SyncPod](https://github.com/kubernetes/kubernetes/blob/bce499c13661a9b6c376caa53655a132d903d79b/pkg/kubelet/kubelet.go#L1750) function call , so the podWorkerLoop function will be blocked in [GetNewerThan](https://github.com/kubernetes/kubernetes/blob/fe25e97403e2244cb74120cf01d28d4067c78c60/pkg/kubelet/pod_workers.go#L1256) until the pod cache was updated.

I continue checked the [getIfNewerThan](https://github.com/kubernetes/kubernetes/blob/fe25e97403e2244cb74120cf01d28d4067c78c60/pkg/kubelet/container/cache.go#L166) function, and found may be the `globalTimestampIsNewer` caused the 'unblock' in  [GetNewerThan](https://github.com/kubernetes/kubernetes/blob/fe25e97403e2244cb74120cf01d28d4067c78c60/pkg/kubelet/pod_workers.go#L1256). For EventedPLEG, the `globalTimestampIsNewer` is updated in [updateGlobalCache](https://github.com/kubernetes/kubernetes/blob/fe25e97403e2244cb74120cf01d28d4067c78c60/pkg/kubelet/pleg/evented.go#L149), actually it did nothing and just update the global cahce timeline every 5 seconds. This is not right and would break the dependency for timeline in [podWorkerLoop](https://github.com/kubernetes/kubernetes/blob/fe25e97403e2244cb74120cf01d28d4067c78c60/pkg/kubelet/pod_workers.go#L1214)

This PR add `GenericPLEG Relist` call every 60 seconds in EvnetedPLEG to update the gloabl pod cache, maybe the `60 seconds` is too long for the pod reconcile performence.

Anyway, let's first confirm the root cause for #123087

### CODE REVIEW

**Comment by wxx213** [comment]
> link

@pacoxu How about the reproduce?

**Comment by wxx213** [comment]
> @wxx213: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-kubernetes-e2e-kind-alpha-features	[7179c32](https://github.com/kubernetes/kubernetes/commit/7179c32a7317694915f3a94d2664000fbb7dc9f6)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/127086/pull-kubernetes-e2e-kind-alpha-features/1830910913968869376)	false	`/test pull-kubernetes-e2e-kind-alpha-features`
> pull-kubernetes-unit	[7179c32](https://github.com/kubernetes/kubernetes/commit/7179c32a7317694915f3a94d2664000fbb7dc9f6)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/127086/pull-kubernetes-unit/1830910916732915712)	true	`/test pull-kubernetes-unit`
> pull-kubernetes-e2e-kind-evented-pleg	[7179c32](https://github.com/kubernetes/kubernetes/commit/7179c32a7317694915f3a94d2664000fbb7dc9f6)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/127086/pull-kubernetes-e2e-kind-evented-pleg/1830910915898249216)	false	`/test pull-kubernetes-e2e-kind-evented-pleg`
> pull-kubernetes-node-e2e-containerd	[7179c32](https://github.com/kubernetes/kubernetes/commit/7179c32a7317694915f3a94d2664000fbb7dc9f6)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/127086/pull-kubernetes-node-e2e-containerd/1830910917580165120)	true	`/test pull-kubernetes-node-e2e-containerd`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=127086). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Awxx213). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

/retest

**Comment by bart0sh** [comment]
@wxx213 please provide details in the PR description, thanks!

**Comment by wxx213** [comment]
> @wxx213 please provide details in the PR description, thanks!

done

**Comment by wxx213** [comment]
> @wxx213: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-kubernetes-e2e-kind-evented-pleg	[7179c32](https://github.com/kubernetes/kubernetes/commit/7179c32a7317694915f3a94d2664000fbb7dc9f6)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/127086/pull-kubernetes-e2e-kind-evented-pleg/1830910915898249216)	false	`/test pull-kubernetes-e2e-kind-evented-pleg`
> pull-kubernetes-e2e-gce-cos-alpha-features	[64ccc64](https://github.com/kubernetes/kubernetes/commit/64ccc649eb1375f23569fa3f3ec2d35773575d68)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/127086/pull-kubernetes-e2e-gce-cos-alpha-features/1831239924897026048)	false	`/test pull-kubernetes-e2e-gce-cos-alpha-features`
> pull-kubernetes-e2e-kind-alpha-features	[9c47a72](https://github.com/kubernetes/kubernetes/commit/9c47a723aca95e8d36423a68ed51f9fa0d5f24a8)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/127086/pull-kubernetes-e2e-kind-alpha-features/1831532606634594304)	false	`/test pull-kubernetes-e2e-kind-alpha-features`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=127086). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Awxx213). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

It seems that the test `pull-kubernetes-e2e-kind-alpha-features` has some problem, it used GenericPLEG to made the test and still failed, could anyone help to check this?

**Comment by hshiina** [comment]
`GetNewerThan()` does not block pod workers because Evented PLEG sets wrong timestamps to the cache. This problem is being fixed in #124297.

**Comment by hshiina** [comment]
> It seems that the test `pull-kubernetes-e2e-kind-alpha-features` has some problem, it used GenericPLEG to made the test and still failed, could anyone help to check this?

`EventedPLEG` looks excluded from this job:
https://github.com/kubernetes/test-infra/blob/798cebf81d4188591e7c39d3be9eac4133429e15/config/jobs/kubernetes/sig-testing/kubernetes-kind.yaml#L308-L310

I don't think the failure is related to this fix.

**Comment by hshiina** [comment]
According to the [Job History](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind-alpha-features), this job has been failing recently.

I also reproduced this failure on my laptop:
```
$ cat kind-all-alpha.yaml 
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  AllAlpha: true
  EventedPLEG: false

$ kind create cluster --image kindest/node:v1.31.0 --config kind-all-alpha.yaml 
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.31.0) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✗ Starting control-plane 🕹️ 
```

**Comment by wxx213** [comment]
> `GetNewerThan()` does not block pod workers because Evented PLEG sets wrong timestamps to the cache. This problem is being fixed in #124297.

Yes, wrong timestamps should be more likely to cause the issue in #123087, great work. The EventedPLEG's  current periodic global cache update could rarely cause the dup container issue. I may close this PR later if no more discussion for this.

**Pull request closed without merging**
