### PR TITLE
mktemp on OSX behaves differently than Linux

### PR DESCRIPTION
**Pull request by smarterclayton**
hack/test-integration and hack/test-cmd are currently broken

### CODE REVIEW

**Comment by erictune** [comment]
lgtm.

FWIW, I think `mktemp -d -t foo.XXXXXX` will work on both linux and osx, so you could avoid the `||`.

**Comment by smarterclayton** [comment]
It does, I will fix

On Wed, Aug 5, 2015 at 2:35 AM, Eric Tune <notifications@github.com> wrote:

> lgtm.
>
> FWIW, I think mktemp -d -t foo.XXXXXX will work on both linux and osx, so
> you could avoid the ||.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/12008#issuecomment-127889643>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
Oh wait, it doesn't.  It doesn't properly create the nested directories:

$ rm -rf /var/folders/zw/j6656mbn1rv4fnqqdggss8h80000gn/
$ ls /var/folders/zw/
$ mktemp -d -t bar.XXXXX
mktemp: mkdtemp failed on
/var/folders/zw/j6656mbn1rv4fnqqdggss8h80000gn/T/bar.XXXXX.Zv5fSUYW: No
such file or directory

On Wed, Aug 5, 2015 at 3:56 PM, Clayton Coleman <ccoleman@redhat.com> wrote:

> It does, I will fix
>
> On Wed, Aug 5, 2015 at 2:35 AM, Eric Tune <notifications@github.com>
> wrote:
>
>> lgtm.
>>
>> FWIW, I think mktemp -d -t foo.XXXXXX will work on both linux and osx,
>> so you could avoid the ||.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/GoogleCloudPlatform/kubernetes/pull/12008#issuecomment-127889643>
>> .
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by erictune** [comment]
weird.  worked for me when I tried it.  Anyhow, still LGTM

**Pull request merged**
