### PR TITLE
fix htmlpreview links to point to subdictory

### PR DESCRIPTION
**Pull request by caesarxuchao**
@nikhiljindal @RichieEscarez

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@k8s-bot test this please

**Comment by nikhiljindal** [comment]
LGTM, thanks!

**Comment by caesarxuchao** [comment]
e2e flake
```
Stacktrace

/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:562
Oct 22 01:21:27.681: Failed to find Events: in Name:		redis-master
Namespace:	e2e-tests-kubectl-btu3c
Image(s):	redis
Selector:	app=redis,role=master
Labels:		app=redis,role=master
Replicas:	1 current / 1 desired
Pods Status:	1 Running / 0 Waiting / 0 Succeeded / 0 Failed
No volumes.
No events.
```

**Comment by caesarxuchao** [comment]
@k8s-bot test this please

**Comment by caesarxuchao** [comment]
I should had cherry-picked this. Now it's too late, it has many conflicts. I'll directly send a PR to release-1.1.

**Pull request merged**
