### PR TITLE
Add basic unit tests for syncProxyRules

### LINKED ISSUE #20766: unit test needed: kube-proxy iptables syncProxyRules
This function could be dep-injected and tested better

### PR DESCRIPTION
**Pull request by asalkeld**
Add some unit test coverage for syncProxyRules()

Fixes #20766

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29895)

### CODE REVIEW

**Comment by asalkeld** [comment]
Needs a retest 

"Failed to setup provider config: Error building GCE/GKE provider: googleapi: Error 500: Internal Error, internalError"

**Comment by asalkeld** [comment]
needed rebasing, the endpointInfos type changed.

**Comment by asalkeld** [comment]
@k8s-bot test this issue #26846

**Comment by asalkeld** [comment]
@k8s-bot test this issue #32685

**Comment by marun** [comment]
I think this is a unit test in name only.  It effectively duplicates logic from syncProxyRules and tests very few paths of the function.  If ensuring coverage for syncProxyRules is the goal, I think a refactor is suggested that decomposes the function into testable chunks.  The current form would be very difficult to test effectively with reasonable effort.

**Comment by asalkeld** [comment]
OK @marun that sounds reasonable, I'll start breaking that function up and testing each bit separately.

**Pull request closed without merging**
