### PR TITLE
Remove Reachable Condition

### PR DESCRIPTION
**Pull request by deyuanix**
@davidopp @gmarek

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks. LGTM, but please rebase and regenerate the swagger.

**Comment by ddysher** [comment]
Rebased and regenerated swagger.

**Comment by bgrant0607** [comment]
Hmm. The generated swagger is not correct. I suggest reverting those files and we'll figure out the problem in a subsequent PR.

**Comment by ddysher** [comment]
I've clean up my repo and regenerated swagger.  Please take another look if these are correct (it looks correct now).  If not, I'll revert then.

**Comment by bgrant0607** [comment]
Those look similar to the changes in #6232. @nikhiljindal which version is correct? Maybe an outdated version was merged.

**Comment by nikhiljindal** [comment]
Looks like we didnt upgrade swagger spec after https://github.com/GoogleCloudPlatform/kubernetes/pull/6143 and https://github.com/GoogleCloudPlatform/kubernetes/pull/6117.
The type changes (bool to boolean) and addition of path parameter are surely due to those PRs.

**Comment by bgrant0607** [comment]
Ok, thanks.

**Pull request merged**
