### PR TITLE
Add TestContainerOutputRegex method to framework

### PR DESCRIPTION
**Pull request by pmorie**
@smarterclayton @zmerlynn @vmarmol 

Needed for #13052

### CODE REVIEW

**Comment by pmorie** [comment]
Oh snap @k8s-bot

**Comment by smarterclayton** [comment]
The code looks fine but I'm not an expert on the style for e2e.

**Comment by pmorie** [comment]
@kubernetes/goog-testing can someone review this please?

**Comment by pmorie** [comment]
Closing since this didn't add that much to the other PR.

**Pull request closed without merging**
