### PR TITLE
remove the elasticsearch template

### PR DESCRIPTION
**Pull request by harryge00**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```
NONE
```
Loading file-based index template has been disabled since 2.0.0-beta1 version of Elasticsearch.  https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_index_api_changes.html#_file_based_index_templates 

So the `template-k8s-logstash.json` is not longer useful.

On the other hand, as https://github.com/kubernetes/kubernetes/issues/25127 indicated, we might better curl the elasticsearch API to load this template.

### CODE REVIEW

**Comment by piosz** [comment]
cc @crassirostris

**Comment by coffeepac** [comment]
@harryge00 looks good and thank you, can you please add a [release note](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release-notes.md) for this?

**Comment by coffeepac** [comment]
@k8s-bot ok to test

**Comment by harryge00** [comment]
@coffeepac I have added release notes

**Comment by crassirostris** [comment]
@harryge00 @coffeepac I think something like removing files should not be in the release notes. Release notes exist for the users to track behavior changes that might affect them. If that change doesn't change _anything_, then I personally think release notes are not necessary. Otherwise, the behavior changes should be described, not developer's actions, e.g. 'fluentd-elasticsearch deployment index schema template is now set up by Elasticsearch'

@harryge00 does removing this file changes the behavior?

@coffeepac do you agree?

**Comment by coffeepac** [comment]
@harryge00 thank you!

@crassirostris the file may be used be someone who has built some automation around using this file.  that automation would break.  if that bar is too low then adding the no-op release note is fine with me.  we do need something in the release note or the merge bot won't merge it.

**Comment by crassirostris** [comment]
@coffeepac It's possible to add `release-notes-none` label

**Comment by coffeepac** [comment]
@crassirostris so it can be.  good to know.  I was letting @harryge00 decide if there should be an actual note or a no-note.  

I'm fine either way, this doesn't affect the behavior of the specified version of ES.

**Comment by crassirostris** [comment]
Thanks!

**Comment by harryge00** [comment]
I agree that the removal does not affect Elasticsearch behavior, whose version is later than v2.0.0-beta1 . @coffeepac @crassirostris

**Comment by coffeepac** [comment]
@harryge00 okay, then no release is preferred.  can you please either remove the release note I asked you to add or replace it with `NONE`?

**Comment by harryge00** [comment]
@coffeepac updated

**Comment by coffeepac** [comment]
lgtm

**Comment by crassirostris** [comment]
/lgtm

We'll look into the problem

**Pull request merged**
