### PR TITLE
 updated code to improve output messages on error for files under test/e2e/aggregator.go

### PR DESCRIPTION
**Pull request by DeeptanshuDas**
#### Which issue(s) this PR fixes:  test/e2e/aggregator.go

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tzneal** [comment]
This changes nearly 2 million lines of code.  Did you submit against the correct branch?

**Comment by bart0sh** [comment]
@DeeptanshuDas can you provide a better description for the change? Please, rebase.

**Comment by jiahuif** [comment]
Please cleanup the commits. I cannot see the intended changes clearly.

**Comment by DeeptanshuDas** [comment]
> Please cleanup the commits. I cannot see the intended changes clearly.

I delete the recent commits hope so this will be helpful for you

**Comment by DeeptanshuDas** [comment]
> @DeeptanshuDas can you provide a better description for the change? Please, rebase.

#119873  I change the ExpectEqual (boolean) to  if (<failure check>) framework.Failf(<informative message>) form

**Comment by bart0sh** [comment]
> https://github.com/kubernetes/kubernetes/pull/119873 I change the ExpectEqual (boolean) to if () framework.Failf() form

This PR changes 5000+ files. I really doubt it's needed to change `ExpectEqual`? Please, look at the changes you're proposing to merge and clean them up. Most probably you're targeting another branch or included other people changes.

**Pull request closed without merging**
