### PR TITLE
bump: upgrade gorilla/websocket from v1.4.2 to v1.5.0

### PR DESCRIPTION
**Pull request by tukwila**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR will update gorilla/websocket from v1.4.2 to v1.5.0.
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Gorilla websocket is important lib in k8s long term connection protocol so it should be updated with the newly version.
https://github.com/gorilla/websocket/releases/tag/v1.5.0

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by jiahuif** [comment]
/assign @seans3 
For context on the websocket part. Thank you.
/triage accepted

**Comment by aojea** [comment]
/ok-to-test
/lgtm

not many changes but this seems specially useful https://github.com/gorilla/websocket/commit/bcef8431c98087addcb2f0ab484ff295abe41a74

/assign @seans3 @liggitt

**Pull request merged**
