### PR TITLE
Lock checksum calculation for v1 CPUManager state to pre 1.18 logic

### LINKED ISSUE #86676: 1.18: panic in "pkg/kubelet/cm/qos_container_manager_linux.go"
**TL;DR:** we discovered the checkpoint file panic in the kubelet that was introduced recently.
see the comments bellow.

**What happened**:
created a 3 control-plane cluster from latest CI 1.17 using kubeadm.
initiated a upgraded from latest CI 1.17 to latest CI 1.18 using kubeadm.

pods such as api-server, etcd end up with stopped containers:
```
KUBECONFIG=/etc/kubernetes/admin.conf kubectl describe po -n kube-system etcd-kinder-upgrade-control-plane-1 | grep Events -A 10
Events:
  Type     Reason            Age                 From                                     Message
  ----     ------            ----                ----                                     -------
  Warning  DNSConfigForming  27m (x17 over 45m)  kubelet, kinder-upgrade-control-plane-1  Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 8.8.8.8 8.8.4.4 2001:4860:4860::8888
  Normal   Killing           26m                 kubelet, kinder-upgrade-control-plane-1  Stopping container etcd
```

the pod list gets stuck at this state, which is slightly incorrect as all containers running on the `-1` node are terminated:

```
root@kinder-upgrade-control-plane-1:/# KUBECONFIG=/etc/kubernetes/admin.conf kubectl get po -A   
NAMESPACE     NAME                                                     READY   STATUS        RESTARTS   AGE
kube-system   calico-kube-controllers-564b6667d7-j6qzw                 0/1     Running       0          42m
kube-system   calico-node-fg6mt                                        1/1     Running       0          39m
kube-system   calico-node-k94w9                                        1/1     Running       0          37m
kube-system   calico-node-nkfp6                                        0/1     Running       0          42m
kube-system   coredns-6955765f44-nvj5d                                 0/1     Running       0          42m
kube-system   coredns-6955765f44-trz6l                                 1/1     Running       0          24m
kube-system   etcd-kinder-upgrade-control-plane-1                      1/1     Running       0          42m
kube-system   etcd-kinder-upgrade-control-plane-2                      1/1     Running       0          39m
kube-system   etcd-kinder-upgrade-control-plane-3                      1/1     Running       0          37m
kube-system   kube-apiserver-kinder-upgrade-control-plane-1            1/1     Running       0          24m
kube-system   kube-apiserver-kinder-upgrade-control-plane-2            1/1     Running       0          39m
kube-system   kube-apiserver-kinder-upgrade-control-plane-3            1/1     Running       0          37m
kube-system   kube-controller-manager-kinder-upgrade-control-plane-1   1/1     Running       0          24m
kube-system   kube-controller-manager-kinder-upgrade-control-plane-2   1/1     Running       1          39m
kube-system   kube-controller-manager-kinder-upgrade-control-plane-3   1/1     Running       0          37m
kube-system   kube-proxy-cmssx                                         1/1     Running       0          39m
kube-system   kube-proxy-f9vvn                                         1/1     Terminating   0          42m
kube-system   kube-proxy-hqq22                                         1/1     Running       0          23m
kube-system   kube-scheduler-kinder-upgrade-control-plane-1            1/1     Running       0          24m
kube-system   kube-scheduler-kinder-upgrade-control-plane-2            1/1     Running       0          39m
kube-system   kube-scheduler-kinder-upgrade-control-plane-3            1/1     Running       0          37m
```

a panic is observed in the kubelet logs of the primary node:
```
$ journalctl -xeu kubelet

<snip>

Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]: goroutine 603 [running]:
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x3a2dec0, 0x6d6df80)
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/
pkg/util/runtime/runtime.go:74 +0xa3
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/
pkg/util/runtime/runtime.go:48 +0x82
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]: panic(0x3a2dec0, 0x6d6df80)
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]:         /usr/local/go/src/runtime/panic.go:679 +0x1b2
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]: k8s.io/kubernetes/pkg/kubelet/cm.(*qosContainerManagerImpl).setCPUCgroupConfig(0xc000a8a0a0, 0xc000f14f38
, 0x428037b, 0xa)
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cm/qos_containe
r_manager_linux.go:169 +0x3b
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]: k8s.io/kubernetes/pkg/kubelet/cm.(*qosContainerManagerImpl).UpdateCgroups(0xc000a8a0a0, 0x0, 0x0)
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cm/qos_containe
r_manager_linux.go:285 +0x291
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]: k8s.io/kubernetes/pkg/kubelet/cm.(*containerManagerImpl).UpdateQOSCgroups(0xc000415200, 0xc000b7c800, 0xc
000d7e580)
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cm/container_ma
nager_linux.go:561 +0x3a
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).killPod(0xc000c2e000, 0xc000b7c800, 0x0, 0xc000d15300, 0x0, 0x4,
 0x4)
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet_pods.go
:832 +0x113
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncPod(0xc000c2e000, 0x0, 0xc000b7c800, 0x2, 0xc000d15300, 0x0,
 0xc000143320, 0xc000d3bbf0)
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1613
 +0x2493
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]: k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop.func1(0xc0007a2ea0, 0xc000213730, 0xc000f15e88,
 0xc0003271e0, 0x4a5ebc0)
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:
175 +0x25d
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]: k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop(0xc000213730, 0xc000959f20)
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:
184 +0x13f
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]: k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod.func1(0xc000213730, 0xc000959f20)
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:
222 +0x6c
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]: created by k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:
220 +0x3d3
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]: E1227 21:41:30.920880   30265 runtime.go:78] Observed a panic: "invalid memory address or nil pointer der
eference" (runtime error: invalid memory address or nil pointer dereference)
Dec 27 21:41:30 kinder-upgrade-control-plane-1 kubelet[30265]: goroutine 497 [running]:
```

**What you expected to happen**:
the kubelet not killing containers.

**How to reproduce it (as minimally and precisely as possible)**:

it is possible with the tool `kinder` in the kubeadm repository, but it might take a while depending on your internet speed.

```
git clone git@github.com:kubernetes/kubeadm.git --depth=1
cd ./kubeadm/kinder
go build

docker pull kindest/base:v20190403-1ebf15f
./kinder build node-image-variant --base-image=kindest/base:v20190403-1ebf15f --image=kindest/node:test --with-init-artifacts=v1.17.1-beta.0.30+7d04da8a4a80f2 --with-upgrade-artifacts=v1.18.0-alpha.1.181+13133857aff48f --loglevel=debug
./kinder create cluster --name=kinder-upgrade --image=kindest/node:test --control-plane-nodes=3 --loglevel=debug
./kinder do kubeadm-init --name=kinder-upgrade --automatic-copy-certs --loglevel=debug --kubeadm-verbosity=6
./kinder do kubeadm-join --name=kinder-upgrade --automatic-copy-certs --loglevel=debug --kubeadm-verbosity=6
./kinder do kubeadm-upgrade --upgrade-version=v1.18.0-alpha.1.181+13133857aff48f --name=kinder-upgrade --loglevel=debug --kubeadm-verbosity=6
```
^ the last command (upgrade) should fail near upgrading the etcd member on the second CP node.

> Failed to get etcd status for https://172.17.0.3:2379: failed to dial endpoint https://172.17.0.3:2379 with maintenance client: context deadline exceeded

at this point it is possible to ctrl+c (or wait for timeout - 10minutes) and execute in the primary CP node:

```
docker exec -it  kinder-upgrade-control-plane-1 bash
kubectl --kubeconfig /etc/kubernetes/admin.conf kubectl describe po -n kube-system etcd-kinder-upgrade-control-plane-1
journalctl -xeu kubelet
crictl ps -a
```

to delete the cluster:
```
kinder delete cluster --name kinder-upgrade
```

**Anything else we need to know?**:
- the tool kinder is doing something wrong, it upgrades the primary CP node kubelet before upgrading the api server on the second CP node. this is incorrect upgrade order, which i will TODO/verify if it affects the panic behavior here. [1]
- the kinder runs containerd on the DIND nodes (based on kind).

this started failing after this DIFF:
https://github.com/kubernetes/kubernetes/compare/0b830f3d6...e5f0648c6

a PR that touches `pkg/kubelet/cm/container_manager_linux.go` in that diff is:
https://github.com/kubernetes/kubernetes/pull/84462

/sig node
/kind bug
cc @klueska @liggitt

i'm adding this priority:
/priority awaiting-more-evidence

but if it still fails once [1] is corrected, i will escalate the priority.

xref:
https://github.com/kubernetes/kubeadm/issues/1981

**Environment**:
- Kubernetes version (use `kubectl version`): see above.
- Cloud provider or hardware configuration: docker-in-docker
- OS (e.g: `cat /etc/os-release`): `Ubuntu 18.04.1 LTS` in the DIND nodes.
- Kernel (e.g. `uname -a`): `Linux kinder-upgrade-control-plane-1 4.13.0-41-generic #46-Ubuntu SMP Wed May 2 13:38:30 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubeadm/kinder
- Network plugin and version (if this is a network-related bug): calico 3.8.2
- Others: NONE

### PR DESCRIPTION
**Pull request by klueska**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
The updated CPUManager from PR #84462 implements logic to migrate the CPUManager checkpoint file from an old format to a new one. To do so, it defines the following types:

```
type CPUManagerCheckpoint = CPUManagerCheckpointV2
type CPUManagerCheckpointV1 struct {  ...  }
type CPUManagerCheckpointV2 struct {  ...  }
```

This replaces the old definition of just:

```
type CPUManagerCheckpoint struct {  ...  }
```

Code was put in place to ensure proper migration from checkpoints in V1 format to checkpoints in V2 format. However, all of the unit tests were performed on V1 checkpoints that were generated using the type name `CPUManagerCheckpointV1` and not the original type name of `CPUManagerCheckpoint`. As such, the checksum in the checkpoint file uses the `CPUManagerCheckpointV1` type to calculate its checksum and not the original type name of `CPUManagerCheckpoint`.

This causes problems in the real world since all pre-1.18 checkpoint files will have been generated with the original type name of `CPUManagerCheckpoint`. When verifying the checksum of the checkpoint file across an upgrade to 1.18, the checksum is calculated assuming a type name of `CPUManagerCheckpointV1` (which is incorrect) and the file is seen to be corrupt.

This patch ensures that all V1 checksums are verified against a type name of `CPUManagerCheckpoint` instead of `CPUManagerCheckpointV1`. It also locks the algorithm used to calculate the checksum in place, since it wil never change in the future (for pre-1.18 checkpoint files at least).

This patch also reverses the alias from:
```
type CPUManagerCheckpoint = CPUManagerCheckpointV2
```
to
```
type CPUManagerCheckpointV2 = CPUManagerCheckpoint
```

This change is to prevent problems when we remove the V1->V2 migration code in the future. Without this, the checksums of all checkpoints would be hashed with the name `CPUManagerCheckpointV2` embedded inside of them, which is undesirable. We want the checkpoints to be hashed with the name `CPUManagerCheckpoint` instead.

**Which issue(s) this PR fixes**:

Fixes #86676

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
/lgtm
i verified that this fixes https://github.com/kubernetes/kubernetes/issues/86676

**Comment by tedyu** [comment]
Currently there is no version field in checkpoint file.
If we introduce version field, it would be easy for subsequent releases to tell which format the checkpoint file is migrated from.
Absence of the version field means V1.

Kevin:
What do you think ?

**Comment by klueska** [comment]
I thought about introducing a version field when putting together the original PR, but found it unnecessary since this format conversion only needs to happen for 1.17 -> 1.18 upgrades and the Entry fields are distinct enough that it’s unambiguous which version we are dealing with. The plan is to eventually remove all of the V1 code (probably in 1.20) and only have the V2 format. 

Speaking of which. In light of the PR that fixes this issue, I need to rename all references to CPUManagerCheckpointV2 to simply CPUManagerCheckpoint in order to avoid this same issue once all references to V1 checkpoints are removed.

That said, I’m not opposed to adding a version field if others feel strongly, but I don’t think it’s strictly necessary.

**Comment by neolit123** [comment]
the common way to handle versioning in k8s is versioned APIs using apimachinery.
apimachinery gives you conversion out of the box, instead of custom migration logic, but it seems like overkill it in this case of a structure with 3 fields.
/cc @mtaufen 

it becomes a question if this structure is going to change in the future.
if it sees multiple iterations in the next few years, then it makes sense to version it now (either with custom conversion or using apimachinery) to be on the safe side.

**Comment by klueska** [comment]
> Speaking of which. In light of the PR that fixes this issue, I need to rename all references to CPUManagerCheckpointV2 to simply CPUManagerCheckpoint in order to avoid this same issue once all references to V1 checkpoints are removed.

This has been addressed as a second commit to this PR.

> the common way to handle versioning in k8s is versioned APIs using apimachinery.

`apimachinery` definitely feels like overkill for an API that is completely internal to the CPUManager.

> it becomes a question if this structure is going to change in the future.

I don't see this structure changing its format in a backwards incompatible way anytime soon (if ever). It may have fields added to it in the future, but this does not require tracking the version, since upgrades will work without modification.

**Comment by neolit123** [comment]
> I don't see this structure changing its format in a backwards incompatible way anytime soon (if ever). It may have fields added to it in the future, but this does not require tracking the version, since upgrades will work without modification.

/lgtm
i'm in favor of fixing this for 1.18 as soon as possible, due to the 1.17->1.18 upgrade issue (and to have a clean e2e signal in the kubeadm upgrade tests).

**Comment by neolit123** [comment]
@klueska 

> `/approve`

interesting, you are not present in the approver list for https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/cpumanager/OWNERS
but the both accept your approve command.

**Comment by neolit123** [comment]
> interesting, you are not present in the approver list for

never mind, you are in here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/OWNERS#L12

thanks

**Comment by nepomucen** [comment]
@klueska , @neolit123 
Would you be so kind, and share your opinion in context of [this StackOverflow issue](https://stackoverflow.com/questions/67301925/kubelet-fails-with-error-checkpoint-is-corrupted-after-version-rollback) (related in general to [#84462](https://github.com/kubernetes/kubernetes/pull/84462)).

Do I understand correctly, that changes around CPUManagerCheckpoint internal API (V1->V2), and related to it conversion of CPUManager checkpoint file format during upgrade from 1.17->1.18, is simply irreversible, if I can say I like this ?

Would it mean that system integration/e2e tests for stable releases are never run for scenarios like in the linked SO-post ?
"Test X on Y and downgrade to Y"

**Comment by neolit123** [comment]
i'm not aware of any downgrade tests related to the CPUManager API changes.

i can see newer kubelets can take a v1 from disk and convert it to v2.
but after downgrade, if a v2 exists on disk the 1.17 kubelet would fail.

node drain is required before kubelet upgrade and downgrade. but the drain process or kubelet restarts do not remove the `cpu_manager_state` file. this means the kubelet downgrade to 1.17 with a v2 checksum file would always fail without the user action of deleting the file.

1.17 is already out of support, but we know that users are trailing behind, so maybe this can be documented at least - e.g. here:
https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/
you can log a new issue and tag it with `/sig node` for more feedback.

also @klueska has a much better understanding of this space.

**Pull request merged**
