### PR TITLE
prevent installation of docker from upstream

### PR DESCRIPTION
**Pull request by wwwtyro**
**What this PR does / why we need it**: Disallows installation of upstream docker from PPA in the Juju kubernetes-worker charm.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Disallows installation of upstream docker from PPA in the Juju kubernetes-worker charm.
```

### CODE REVIEW

**Comment by marcoceppi** [comment]
Could you include release notes or signal that there are none?

**Comment by chuckbutler** [comment]
/unapprove

This PR only handles half of the situation. It does remove the config flag for fresh deployments, but we also need to consider the upgrading users scenario where if they have enabled this, we're heading them down a sad path.

I feel like this shoudl also include some removal code to revert the daemon installation to archive at this juncture so we dont have users upgrading into a broken state.

**Comment by chuckbutler** [comment]
Thats a clever way to solve the problem. +1 to this, make layer-docker do the heavy lifting on upgrade. 

/approve

**Pull request merged**
