### PR TITLE
Fix comment in authentication API

### PR DESCRIPTION
**Pull request by vboctor**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fixes a typo in a comment.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

N/A

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

NONE

/sig api-machinery

### CODE REVIEW

**Comment by vboctor** [comment]
I signed it

**Review by jianhuiz — APPROVED** [review]

**Comment by nikhita** [comment]
/release-note-none

/assign @liggitt 
for approval

**Comment by liggitt** [comment]
lgtm, can you fix the same typo in the versioned API files? those are what actually make it out into generated docs (will require `make update` to regenerate docs as well)

**Comment by mourya007** [comment]
You can fix this comment in the other files also like:
https://github.com/kubernetes/kubernetes/blob/ec2e767e59395376fa191d7c56a74f53936b7653/staging/src/k8s.io/api/authentication/v1/types.go#L31

https://github.com/kubernetes/kubernetes/blob/2bd14ea60e934f0d7a499a1a830a05262238605a/staging/src/k8s.io/client-go/transport/round_trippers.go#L218

**Comment by liggitt** [comment]
closing for lack of activity

/close

**Pull request closed without merging**
