### PR TITLE
Do not set container state to be Unknown when determineContainerIP fails

### LINKED ISSUE #43851: Hundreds of pause containers running in the same pod
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:52:01Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**:'OpenStack VM'
- **OS** (e.g. from /etc/os-release):`14.04.4 LTS, Trusty Tahr`
- **Kernel** (e.g. `uname -a`):`Linux xubuntu 3.16.0-73-generic #95~14.04.1-Ubuntu SMP Thu Jun 9 08:00:04 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**:`Manually`
- **Others**:

**What happened**:
There are hundreds of pause containers running in the same pod.
```
CONTAINER ID        IMAGE                                      COMMAND             CREATED                  STATUS                  PORTS               NAMES
c08b72a73e83        gcr.io/google_containers/pause-amd64:3.0   "/pause"            Less than a second ago   Up Less than a second                       k8s_POD.d8dbe16c_rc-nginx-single-9ptd9_default_cb399fca-1523-11e7-ae68-fa163e09f30e_05fa7820
edb56312438b        gcr.io/google_containers/pause-amd64:3.0   "/pause"            2 seconds ago            Up 1 second                                 k8s_POD.d8dbe16c_rc-nginx-single-9ptd9_default_cb399fca-1523-11e7-ae68-fa163e09f30e_d791a4e0
3101a11067b0        gcr.io/google_containers/pause-amd64:3.0   "/pause"            4 seconds ago            Up 3 seconds                                k8s_POD.d8dbe16c_rc-nginx-single-9ptd9_default_cb399fca-1523-11e7-ae68-fa163e09f30e_585b96f4
3c416fa67746        gcr.io/google_containers/pause-amd64:3.0   "/pause"            6 seconds ago            Up 5 seconds                                k8s_POD.d8dbe16c_rc-nginx-single-9ptd9_default_cb399fca-1523-11e7-ae68-fa163e09f30e_a6be5223
f60ec5fe060b        gcr.io/google_containers/pause-amd64:3.0   "/pause"            8 seconds ago            Up 8 seconds                                k8s_POD.d8dbe16c_rc-nginx-single-9ptd9_default_cb399fca-1523-11e7-ae68-fa163e09f30e_874040ec
eabba571dfb5        gcr.io/google_containers/pause-amd64:3.0   "/pause"            10 seconds ago           Up 10 seconds                               k8s_POD.d8dbe16c_rc-nginx-single-9ptd9_default_cb399fca-1523-11e7-ae68-fa163e09f30e_d7895b4f
bb7e93a580d8        gcr.io/google_containers/pause-amd64:3.0   "/pause"            13 seconds ago           Up 12 seconds                               k8s_POD.d8dbe16c_rc-nginx-single-9ptd9_default_cb399fca-1523-11e7-ae68-fa163e09f30e_b8efe2a5
be9403cb6a7d        gcr.io/google_containers/pause-amd64:3.0   "/pause"            14 seconds ago           Up 13 seconds  
```

**What you expected to happen**:
Only one pause container running in a pod.

**How to reproduce it** (as minimally and precisely as possible):
https://github.com/kubernetes/kubernetes/blob/v1.5.1/pkg/kubelet/dockertools/docker_manager.go#L446
Set err to be a non-nil value here to simulate a race condition happening.
```go
			ip, err = dm.determineContainerIP(podNamespace, podName, iResult)
			// Kubelet doesn't handle the network error scenario
			if err != nil {
				status.State = kubecontainer.ContainerStateUnknown
				status.Message = fmt.Sprintf("Network error: %#v", err)
			}
```

**Anything else we need to know**:
On our prod env,  there is a "thick" CNI plugin which may cost seconds to SetUpPod. In such case, a [race condition](https://github.com/kubernetes/kubernetes/issues/25281#issuecomment-217591358) will cause pause status to be set to `ContainerStateUnknown` ([setting](https://github.com/kubernetes/kubernetes/blob/v1.5.1/pkg/kubelet/dockertools/docker_manager.go#L449)). The pod is recreated but its pause container will not be killed because it's not [running status](https://github.com/kubernetes/kubernetes/blob/v1.5.1/pkg/kubelet/dockertools/docker_manager.go#L2136). Then pod is going on being created again and again without pause container being killed.

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
fixes #43851 

**Special notes for your reviewer**:
Fix the issue as is written in Dan's closed PR #30147  (https://github.com/kubernetes/kubernetes/pull/30147/files#diff-e2eefa11d78ba95197ce406772c18c30R408)
Though we will deprecate dockertools, I think it's OK to fix the issue currently.

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by yujuhong** [comment]
Explained in https://github.com/kubernetes/kubernetes/issues/43851#issuecomment-290465267. I don't think there is a *bug*. With your PR, if the network of your infra container is not set up properly, kubelet will never create a new infra container to replace it.

**Comment by xiangpengzhao** [comment]
@yujuhong I'd like to discuss more about the issue I encountered. I do believe there is a bug somewhere. Feel free to correct me if I understand incorrectly:)

The background is that I have a "thick" and a bit slow CNI plugin. It may cost several seconds to SetUpPod.

- If the plugin is working on setting up pod network, GetPodStatus-->inspectContainer-->[determineContainerIP](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker_manager.go#L442) will find no ip before the plugin finishes successfully. Then the infra container will be set to `ContainerStateUnknown`. 
- SyncPod-->computePodContainerChanges will find infra container ["Need to restart pod infra container for %q because it is not found"](https://github.com/xiangpengzhao/kubernetes/blob/eb03f6736a3c9f1deb9997c9b08a25cd8d783502/pkg/kubelet/dockertools/docker_manager.go#L2044) and `createPodInfraContainer` will be true.
- SyncPod-->[killPodWithSyncResult](https://github.com/xiangpengzhao/kubernetes/blob/eb03f6736a3c9f1deb9997c9b08a25cd8d783502/pkg/kubelet/dockertools/docker_manager.go#L2217)
- in killPodWithSyncResult, the old infra container is deleted only when it's in running state. BUT at this time it's actual state is unknown. **Then the old infra container will not be deleted**. 
```go
if networkContainer.State == kubecontainer.ContainerStateRunning {
	killContainerResult := kubecontainer.NewSyncResult(kubecontainer.KillContainer, networkContainer.Name)
	result.AddSyncResult(killContainerResult)
	if err := dm.KillContainerInPod(networkContainer.ID, networkSpec, pod, "Need to kill pod.", gracePeriodOverride); err != nil {
		killContainerResult.Fail(kubecontainer.ErrKillContainer, err.Error())
		glog.Errorf("Failed to delete container %v: %v; Skipping pod %q", networkContainer.ID.ID, err, runtimePod.ID)
	}
}
```
- SyncPod-->[createPodInfraContainer](https://github.com/xiangpengzhao/kubernetes/blob/eb03f6736a3c9f1deb9997c9b08a25cd8d783502/pkg/kubelet/dockertools/docker_manager.go#L2274) then creates a new infra container.
- There are more and more infra containers...

**Comment by xiangpengzhao** [comment]
> With your PR, if the network of your infra container is not set up properly, kubelet will never create a new infra container to replace it.

Agreed. This PR has the issue you mentioned. 

I think there might be two ways to fix:
- If here in [SyncPod](https://github.com/xiangpengzhao/kubernetes/blob/eb03f6736a3c9f1deb9997c9b08a25cd8d783502/pkg/kubelet/dockertools/docker_manager.go#L2314) err is not nil, we should also `KillContainerInPod(podInfraContainerID)` as [here](https://github.com/xiangpengzhao/kubernetes/blob/eb03f6736a3c9f1deb9997c9b08a25cd8d783502/pkg/kubelet/dockertools/docker_manager.go#L2291) does.
```go
podIP, err = dm.determineContainerIP(pod.Namespace, pod.Name, podInfraContainer)
if err != nil {
	glog.Errorf("Network error: %v; Skipping pod %q", err, format.Pod(pod))
	result.Fail(err)
	return
}
```
- in [killPodWithSyncResult](https://github.com/xiangpengzhao/kubernetes/blob/eb03f6736a3c9f1deb9997c9b08a25cd8d783502/pkg/kubelet/dockertools/docker_manager.go#L1521), try to kill infra container no matter what its state is.
```go
if networkContainer.State == kubecontainer.ContainerStateRunning {
	killContainerResult := kubecontainer.NewSyncResult(kubecontainer.KillContainer, networkContainer.Name)
	result.AddSyncResult(killContainerResult)
	if err := dm.KillContainerInPod(networkContainer.ID, networkSpec, pod, "Need to kill pod.", gracePeriodOverride); err != nil {
		killContainerResult.Fail(kubecontainer.ErrKillContainer, err.Error())
		glog.Errorf("Failed to delete container %v: %v; Skipping pod %q", networkContainer.ID.ID, err, runtimePod.ID)
	}
}
```

**Comment by xiangpengzhao** [comment]
https://github.com/kubernetes/kubernetes/blob/v1.5.1/pkg/kubelet/dockertools/docker_manager.go#L1496

Just find that in v1.5.1(my env version with issue #43851), `killPodWithSyncResult` doesn't have condition `if networkContainer.State == kubecontainer.ContainerStateRunning`. So maybe my analysis above is incorrect. I'm confused... 

>in killPodWithSyncResult, the old infra container is deleted only when it's in running state. BUT at this time it's actual state is unknown. Then the old infra container will not be deleted.
```go
if networkContainer.State == kubecontainer.ContainerStateRunning {
	killContainerResult := kubecontainer.NewSyncResult(kubecontainer.KillContainer, networkContainer.Name)
	result.AddSyncResult(killContainerResult)
	if err := dm.KillContainerInPod(networkContainer.ID, networkSpec, pod, "Need to kill pod.", gracePeriodOverride); err != nil {
		killContainerResult.Fail(kubecontainer.ErrKillContainer, err.Error())
		glog.Errorf("Failed to delete container %v: %v; Skipping pod %q", networkContainer.ID.ID, err, runtimePod.ID)
	}
}
```

**Comment by xiangpengzhao** [comment]
No matter what the root cause is, it seems like it's unworthy to take a further deep dive on it. #43884 
@yujuhong Feel free to close this PR and #43851 :)

**Comment by yujuhong** [comment]
@xiangpengzhao thanks for digging into this! Indeed the docker manager code is going away soon, but if there are serious bugs, we can still patch it for the <=1.6 branches. 

On the other hand, it's still a bit unclear to me what's the actual root cause of the problem. Since we both agree that this PR may not be the right fix. let's close it for now. If you still experience the same issue, feel free to open a bug with more information. :-)

**Comment by xiangpengzhao** [comment]
Thanks @yujuhong !

**Pull request closed without merging**
