### PR TITLE
chore: io/ioutil deprecated

### PR DESCRIPTION
**Pull request by testwill**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
https://github.com/kubernetes/kubernetes/pull/118370  split emptydir
Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by rata** [comment]
@testwill Can you please ping me here if all tests are green?

**Comment by testwill** [comment]
Hello,  @rata  all tests are green.

**Comment by rata** [comment]
Cool! Assigning Tim as the bot said


/assign thockin

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
