### PR TITLE
Attempt to deflake HPA e2e test

### PR DESCRIPTION
**Pull request by jbartosik**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
/kind flake

**What this PR does / why we need it**: Attempt to deflake release blocking test

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

issue #73045

### CODE REVIEW

**Comment by liggitt** [comment]
is this a cherry pick of a change already made in 1.12+?

**Comment by liggitt** [comment]
will defer to @mwielgus or @DirectXMan12 on whether this fix makes sense

**Comment by jbartosik** [comment]
@liggitt @foxish please approve.

**Comment by jbartosik** [comment]
I still need label do-not-merge/cherry-pick-not-approved removed before I can merge this PR.

**Pull request merged**
