### PR TITLE
Automated cherry pick of #101005: Set namespace when using kubectl create service

### PR DESCRIPTION
**Pull request by zxh326**
Cherry pick of #101005 on release-1.21.

#101005: Set namespace when using kubectl create service

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

cc @eddiezane

### CODE REVIEW

**Comment by eddiezane** [comment]
@kubernetes/release-managers requesting cherry pick approval for this bug fix.

Not super pressing but there is [a user waiting](https://github.com/kubernetes/kubernetes/issues/100995) needing this fix and if possible would like to get it to them before 1.22 ships in August.

**Review by hasheddan — COMMENTED** [review]
/retest

@eddiezane should this also go to other active branches?

**Comment by eddiezane** [comment]
Talked to @hasheddan on Slack.

I opened https://github.com/kubernetes/kubernetes/pull/101769 for 1.20 but cherry pick to 1.19 isn't easily done due to https://github.com/kubernetes/kubernetes/pull/95256.

**Pull request merged**
