### PR TITLE
Federated Read Access to Pod Object

### PR DESCRIPTION
**Pull request by kshafiee**
The purpose of this PR is to enable to user to get the list of pod objects in the underlying federated clusters. To do this,

Step 1: Pod object is added to federation
Step 2: pass-through functionality is implmeneted

### CODE REVIEW

**Comment by kshafiee** [comment]
@nikhiljindal @XiaoningDing @madhusudancs @deepak-vij

**Comment by nikhiljindal** [comment]
As discussed offline, this only works for pods. Doesnt work for other resources like deployments where `GET /extensions/v1beta1/deployments` returns federated deployments (from federation control plane) and not deployments from underlying clusters.
We want a consistent berhaviour for all resources.

**Comment by quinton-hoole** [comment]
@kshafiee Is there a design doc for this?  We will need one before reviewing the code.

**Comment by kshafiee** [comment]
Design doc. for your reference @quinton-hoole 
[Federated Read Access to Pod Object.docx](https://github.com/kubernetes/kubernetes/files/791612/Federated.Read.Access.to.Pod.Object.docx)

**Comment by quinton-hoole** [comment]
Deprecated by https://github.com/kubernetes/kubernetes/issues/33622#issuecomment-304390631
Please see there for refreshed design and upcoming implementation.

**Pull request closed without merging**
