### PR TITLE
Replace hard-coded TEST_ETCD_IMAGE with target version.

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
As we will upgrade etcd to a higher version (ref: #56438), we don't want to hard-code a etcd image name.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
ref: #56438

**Special notes for your reviewer**:
/cc @jpbetz 
@kubernetes/sig-cluster-lifecycle-pr-reviews 

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by krousey** [comment]
/assign @mml 
Since you wrote the etcd upgrade stuff. Does this behave like you'd expect?

**Comment by jpbetz** [comment]
Thanks. This is sorely needed.
/lgtm

**Comment by mml** [comment]
@xiangpengzhao can you rebase?  This LGTM.

**Comment by xiangpengzhao** [comment]
/remove-lifecycle stale

Sorry for delay. Rebased. @jpbetz @mml PTAL. Thanks!

**Pull request closed without merging**
