### PR TITLE
Update cadvisor dependency

### PR DESCRIPTION
**Pull request by piosz**
Set maxHousekeepingInterval to 15 seconds.
Added a new dep: gcloud-golang/compute/metadata.

### CODE REVIEW

**Comment by piosz** [comment]
cc @dchen1107 @vishh @vmarmol

**Comment by vmarmol** [comment]
Lets separate into 2 commits:

- The Godeps
- The 15s change

**Comment by piosz** [comment]
Done

**Comment by piosz** [comment]
@k8s-bot test this please

**Comment by vmarmol** [comment]
LGTM

**Comment by dchen1107** [comment]
LGTM

**Pull request merged**
