### PR TITLE
duplicated klog.V(5) when had a if klog.V(5)

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by k82cn** [comment]
/assign

/hold

The new diff does not align with the original logic: if log_level is 4, no logs in this new diff :(

**Comment by qingsenLi** [comment]
/cc @k82cn 
thanks,I just remove the duplicated klog.V(5)

**Pull request merged**
