### PR TITLE
Add KEDA to the External Metrics API implementations

### PR DESCRIPTION
**Pull request by zroubalik**
Signed-off-by: Zbynek Roubalik zroubali@redhat.com

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Adding KEDA to the External Metrics API implementations list.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:
N/A

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
N/A

### CODE REVIEW

**Comment by ehashman** [comment]
KEDA is a CNCF sandbox project (https://github.com/cncf/toc/issues/335), adding this to the docs seems fine to me. 

/priority backlog
/lgtm

**Comment by zroubalik** [comment]
Hi, any update on this please? Is there anything I should add to get this merged? Thanks!

**Comment by ehashman** [comment]
Not sure why this is missing an approved.

/approve

**Comment by ehashman** [comment]
/retest

flake

**Pull request merged**
