### PR TITLE
Check CA file before creating tlsConfig

### PR DESCRIPTION
**Pull request by FengyunPan**
Improve code.

Currently newETCD3Storage() inits tlsInfo firstly, then check the arg which is used to init tlsInfo.
I think that is unreasonable, we should check the arg  before initing tlsInfo.

### CODE REVIEW

**Comment by jdumars** [comment]
@FengyunPan could you please add some more information about what this PR is doing and why it's needed?

**Comment by FengyunPan** [comment]
@jdumars Sorry for my mistake. I update it.
 Currently newETCD3Storage() inits tlsInfo firstly, then check the arg which is used to init tlsInfo.
I think that is unreasonable, we should check the arg  before initing tlsInfo.

**Comment by grodrigues3** [comment]
@dims you're not in any OWNERS file so you can't /approve no-issue

**Comment by jdumars** [comment]
@smarterclayton can you try and approve this one again?

**Comment by FengyunPan** [comment]
@smarterclayton It seems need you to add '/approve no-issue' label.

**Comment by FengyunPan** [comment]
@pwittrock My pr just do a improvement and that is not an issuse, do you agree?

**Comment by dims** [comment]
@FengyunPan Can you fix the "commit missing GitHub user" problem that the CLA bot is tripping on?

**Comment by dims** [comment]
@FengyunPan ping. please see request above

**Comment by FengyunPan** [comment]
@dims Sorry for delay.

**Pull request closed without merging**
