### PR TITLE
No timeout for kubectl logs

### LINKED ISSUE #27588: Kubelet times out docker container logs after 2 minutes
When streaming logs to a client of a long-running pod, the log will be closed after 2 minutes with

```
net/http: request canceled
```

In the kubelet docker client, a default context (with 2 min timeout) is created for the Logs call:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/kube_docker_client.go#L339

### PR DESCRIPTION
**Pull request by dchen1107**
Fix #27588

cc/ @smarterclayton

### CODE REVIEW

**Comment by dchen1107** [comment]
cc/ @Random-Liu

**Comment by smarterclayton** [comment]
LGTM - I don't see how cancel would be relevant here.

**Comment by Random-Liu** [comment]
LGTM. This is the same with image pulling https://github.com/kubernetes/kubernetes/pull/26122. I misunderstood the context before, I thought it only works across the function call. However, the engine-api holds the context in a separate go routine and wait for all response fully transferred.

**Comment by Random-Liu** [comment]
One question is that, for detach mode container exec, should we set timeout or not?
If not, we should also change the code.
@smarterclayton @dchen1107

**Comment by smarterclayton** [comment]
Yeah, let's remove timeout for exec and attach as well for now until we understand what we want.

**Comment by Random-Liu** [comment]
@k8s-bot test this issue #26135

**Pull request merged**
