### PR TITLE
Add etcd basic authentication support

### PR DESCRIPTION
**Pull request by codeb2cc**
Add flags `etcd-username` and `etcd-password` to support etcd's authentication feature:
https://github.com/coreos/etcd/blob/master/Documentation/authentication.md

### CODE REVIEW

**Comment by codeb2cc** [comment]
I signed it!

**Comment by zmerlynn** [comment]
Needs rebase.

**Comment by zmerlynn** [comment]
@k8s-bot ok to test

**Comment by codeb2cc** [comment]
╮（╯＿╰）╭

**Pull request closed without merging**
