### PR TITLE
 Use volumeutil.LoadPodFromFile for pod spec

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Minor cleanup.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/cc @luxas 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by luxas — APPROVED** [review]
LGTM after you squash the commits to one
Thank you!

**Comment by xiangpengzhao** [comment]
@luxas squashed. PTAL. Thanks!

**Review by luxas — APPROVED** [review]
/lgtm
/approve no-issue

**Comment by xiangpengzhao** [comment]
@luxas fixed a verification failure. Need reapplying `lgtm` :)

**Pull request merged**
