### PR TITLE
Remove unused sub-pkgs in pkg/util

### LINKED ISSUE #48386: Remove those "empty" sub-pkgs of pkg/util which only exist until heapster rebases
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig api-machinery
/assign
/cc @deads2k 

**What happened**:
There are several "empty" sub-pkgs of `pkg/util` which don't include codes but doc.go and BUILD files. They were once relied on by heapster. As per https://github.com/kubernetes/heapster/pull/1483, https://github.com/kubernetes/heapster/pull/1537 and https://github.com/kubernetes/heapster/pull/1537/files, heapster had rebased and no longer relies on these pkgs so we can remove them.

**What you expected to happen**:
remove below sub-pkgs
```
pkg/util/errors/
pkg/util/framer
pkg/util/intstr/
pkg/util/json
pkg/util/net/ note: this pkg still has a non-empty sub-pkg, but we can remove its doc.go and BUILD files
pkg/util/rand
pkg/util/runtime
pkg/util/sets
pkg/util/uuid note: this pkg wasn't relied on by heapster but it was moved to apimachinery, seems like it's time to remove it too.
pkg/util/validation
pkg/util/wait
pkg/util/yaml
```
**How to reproduce it (as minimally and precisely as possible)**:
nope

**Anything else we need to know?**:
If @deads2k can help confirm this, I will send a PR to remove them.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Remove no longer used sug-pkgs in pkg/util

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #48386

**Special notes for your reviewer**:
/cc @deads2k 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
Need to make sure that `hack/verify-godeps.sh` works.

**Comment by deads2k** [comment]
> Need to make sure that hack/verify-godeps.sh works.

I ran it manually and it worked fine.

/lgtm
/release-note-none

**Comment by xiangpengzhao** [comment]
Thanks @deads2k for helping verify it !

CI told me other verification scripts `hack/verify-generated-protobuf.sh` and `hack/verify-golint.sh` also failed.
```
W0703 06:29:03.601] cp: cannot stat '/go/src/k8s.io/kubernetes/pkg/util/intstr/*': No such file or directory
I0703 06:29:03.702] FAILED   hack/make-rules/../../hack/verify-generated-protobuf.sh	0s
```

```
I0703 06:31:41.548] FAILED   hack/make-rules/../../hack/verify-golint.sh	48s
```

I ran `hack/verify-generated-protobuf.sh` locally. It's the same error.
```
cloud@ubuntu:~/go/src/k8s.io/kubernetes$ hack/verify-generated-protobuf.sh
cp: cannot stat ‘/home/cloud/go/src/k8s.io/kubernetes/pkg/util/intstr/*’: No such file or directory
!!! Error in hack/verify-generated-protobuf.sh:38
  Error in hack/verify-generated-protobuf.sh:38. 'cp -a "${KUBE_ROOT}/${APIROOT}"/* "${_tmp}/${APIROOT}/"' exited with status 1
Call stack:
  1: hack/verify-generated-protobuf.sh:38 main(...)
Exiting with status 1
```

But I ran `hack/update-generated-protobuf.sh`, no files change. Am I missing something?

**Comment by xiangpengzhao** [comment]
Oh, `hack/verify-generated-protobuf.sh` hard-coded the path `pkg/util/intstr` in it.

**Comment by xiangpengzhao** [comment]
@deads2k CI failures addressed. PTAL. Could you also comment a `/ok to test` please? Thanks!
BTW: lint failed due to `hack/.linted_packages` file updates. fixed the lint errors in this PR, too

**Comment by deads2k** [comment]
@smarterclayton this is cleaning cruft since heapster rebased.

**Comment by xiangpengzhao** [comment]
Sorry, I remembered the wrong command. It's `/ok-to-test` :)

@deads2k

**Pull request merged**
