### PR TITLE
Disable CoreOS image from node e2e testing.

### PR DESCRIPTION
**Pull request by vishh**
For #26903

Marking this as a `P0` since it is failing node e2e consistently.

### CODE REVIEW

**Comment by euank** [comment]
LGTM, apologies for not having time to look into the failure. I'll look into it today in the hope we can get this reenabled asap and not be blind :)

**Comment by ncdc** [comment]
+1 to manual merge if possible

**Comment by dchen1107** [comment]
Yes, manually merging. LGTM

**Pull request merged**
