### PR TITLE
Automated cherry pick of #78997: Fix nil pointer

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #78997 on release-1.15.

#78997: Fix nil pointer

### CODE REVIEW

**Comment by tpepper** [comment]
/kind bug
@kubernetes/patch-release-team 

parent PR still needs to merge

**Comment by liggitt** [comment]
> parent PR still needs to merge

that's unlikely to happen soon, since master thawed.

**Comment by tpepper** [comment]
Given #78997 is done and definitely merge bound and just floating through tide pools with other PRs, I'm going to go ahead and approve this for the 1.15 branch.

**Pull request merged**
