### PR TITLE
bump klog to  v2.120.0

### PR DESCRIPTION
**Pull request by pacoxu**
https://github.com/kubernetes/kubernetes/pull/121554 is waiting for this bump to use the new added [Add SafePtr wrapper by @kaisoz](https://github.com/kubernetes/klog/pull/393) to avoid `panic log` in job controller.

/kind cleanup

```release-note
None
```
See https://github.com/kubernetes/klog/releases/tag/v2.120.0

/assign @dims 
/cc @kaisoz @alculquicondor

### CODE REVIEW

**Review by kaisoz — APPROVED** [review]

**Comment by kaisoz** [comment]
/lgtm

Thanks @pacoxu

**Review by justankiit — COMMENTED** [review]
Looks good now!!

**Comment by dims** [comment]
/assign @liggitt @thockin 

for `api/OWNERS`

**Pull request merged**
