### PR TITLE
Kubeadm config refactor JoinControlPlane

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
As agree in latest review of kubeadm v1beta1 api, we should introduce JoinControlPlane struct and make it pointer/nullable because it corresponds to an alpha feature

rif: https://github.com/kubernetes/kubeadm/issues/911 

**Special notes for your reviewer**:
/sig cluster-lifecycle
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews
/area kubeadm
/assign @timothysc
/assign @luxas
/cc @rosti 

**Does this PR introduce a user-facing change?**:
```release-note
Kubeadm:  attributes for join --control-plane workflow are now grouped into a dedicated JoinControlPlane struct
```

### CODE REVIEW

**Review by timothysc — APPROVED** [review]
/approve 
/lgtm 

could nit, but we need to keep going.

**Review by timothysc — COMMENTED** [review]
/lgtm
/test pull-kubernetes-e2e-kops-aws

**Review by luxas — COMMENTED** [review]
Retroactive LGTM. Thanks @fabriziopandini :tada:!

**Pull request merged**
