### PR TITLE
Add windows config to Kubelet CRI

### PR DESCRIPTION
**Pull request by feiskyer**
**What this PR does / why we need it**:

Currently Container Runtime Interface (CRI) only supports LinuxContainerConfig and therefore LinuxContainerResources in ContainerConfig. Windows resource config is different from Linux's, although it shares some common properties. 

This PR adds windows config to CRI. Add newly added WindowsContainerResources is original from OCI spec (see https://github.com/opencontainers/runtime-spec/blob/master/specs-go/config.go#L437).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

First part of #56734. A further PR is needed to fill the values after we have agreement on the spec.

**Special notes for your reviewer**:

**Release note**:

```release-note
Add windows config to Kubelet CRI
```

/assign @yujuhong @brendandburns 
/cc @taylorb-microsoft @JiangtianLi @dchen1107

### CODE REVIEW

**Comment by brendandburns** [comment]
This LGTM, but do we want SIG-Node to sign off on the API changes?

@kubernetes/sig-node-api-reviews

**Comment by feiskyer** [comment]
> This LGTM, but do we want SIG-Node to sign off on the API changes?

@brendandburns Yep, of course. @JiangtianLi is preparing a proposal and will present it on next sig-node meeting.

**Comment by JiangtianLi** [comment]
I drafted the proposal here: https://github.com/kubernetes/community/pull/1510.

**Comment by yujuhong** [comment]
/hold
Let's discuss over the proposal now that there's one.

**Review by JiangtianLi — APPROVED** [review]
lgtm

**Comment by feiskyer** [comment]
Since windows pod-level resource management is not decided yet, I think we could add container resources first and address pod-level in another PRs. This PR only adds WindowsContainerResources  to CRI.

@dchen1107  @yujuhong @brendandburns @patricklang  PTAL

**Comment by feiskyer** [comment]
ping @yujuhong @brendandburns  Could you help to take a look at this?

**Comment by brendandburns** [comment]
As I said, this looks fine to me, but I'd like an ack from @dchen1107 or @yujuhong

**Comment by yujuhong** [comment]
Ack. Reviewing https://github.com/kubernetes/community/pull/1510. Will review this PR once questions are resolved over there.

**Pull request merged**
