### PR TITLE
Upgrade to docker 1.8.2 for Debian Wheezy on GCE

### PR DESCRIPTION
**Pull request by yujuhong**
Due to #13749, this PR only upgrades Docker for Debian Wheezy on GCE so that we can start testing the new version in jenkins.

### CODE REVIEW

**Comment by yujuhong** [comment]
I believe this PR is still blocked by #12506

**Comment by yujuhong** [comment]
@k8s-bot ok to test

**Comment by yujuhong** [comment]
#12506 was resolved. Kicking off jenkins again.

**Comment by yujuhong** [comment]
@dchen1107, PR is ready for review since e2e passed

**Comment by yujuhong** [comment]
Changed this PR to upgrade to 1.8.2 based on @dchen1107's https://github.com/kubernetes/kubernetes/issues/13749#issuecomment-139594818

**Comment by dchen1107** [comment]
LGTM

**Pull request merged**
