### PR TITLE
Services e2e uses kubectl exec instead of docker run.

### PR DESCRIPTION
**Pull request by bprashanth**
Replaces ssh+docker pull, exec, sort | uniq with kubectl exec and sort | uniq in go.

### CODE REVIEW

**Comment by thockin** [comment]
needs rebase

**Comment by thockin** [comment]
This is fine, since it is done, but we should be moving in the direction of gcr.io/google_containers/netexec:1.0 instead - it's more flexible and less ad-hoc.  We could probably pick a better name for it to make it clear what it does, and document it better.

**Comment by bprashanth** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Pull request merged**
