### PR TITLE
podresources: Introducing cpu_affinity in ContainerResources

### PR DESCRIPTION
**Pull request by swatisehgal**
#### What type of PR is this?

/kind feature
/kind api-change

#### What this PR does / why we need it:
This provides the podresource API client a user friendly way to learn about [taskset](https://man7.org/linux/man-pages/man1/taskset.1.html) corresponding to cpus allocated to a container. 

Prior to this PR, in order to determine the taskset the client had to:

1. Call `GetAllocatableResources` gRPC endpoint to get a list of all the allocatable CPUs
2. Call `GetCpuIds` on all `ContainerResources` in the system
3. Subtract out all of the CPUs from the `GetCpuIds` calls from the `GetAllocatableResources` call

#### Which issue(s) this PR fixes:
Fixes # https://github.com/kubernetes/kubernetes/issues/105698

#### Special notes for your reviewer:
Related PR: https://github.com/kubernetes/kubernetes/pull/97415
Implementation in this PR is based on the discussion: [here](https://github.com/kubernetes/kubernetes/pull/97415#discussion_r720306286) 
#### Does this PR introduce a user-facing change?

```release-note
Kubelet podresources API provides a way to determine taskset of a container
```

### CODE REVIEW

**Comment by fromanirh** [comment]
I'm afraid this change will need a KEP (/extension), and possibly a feature gate

**Comment by wgahnagl** [comment]
/triage accepted 

What priority is this? Could you get verify and typecheck tests passing and link this to an issue?

**Review by ffromani — COMMENTED** [review]
initial review

**Comment by dims** [comment]
Is this PR still needed, please rebase if so (or we can close it?)

**Comment by swatisehgal** [comment]
@dims The PR has been rebased, thanks for the ping!

**Comment by swatisehgal** [comment]
The PR needs some clean up to make the CI happy, will mark it WIP for now.

**Comment by swatisehgal** [comment]
WIP removed, the PR is ready for review

**Comment by endocrimes** [comment]
LGTM with the rebase - sorry this slipped :(

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by swatisehgal** [comment]
This could be a nice addition to podresource API but I don't have the bandwidth to drive it in this cycle. I will close it for now, we can reopen if others in the community ask for it and/or I have the bandwidth to move this forward.

/close

**Pull request closed without merging**
