### PR TITLE
apis:core:validation: remove unused, changes to idiomatic go

### PR DESCRIPTION
**Pull request by droslean**
Remove unexported unused functions `fsResourceIsEphemeralStorage()`,`isLocalStorageResource()`.
Replace an unnecessary loop to idiomatic go way.

 /kind cleanup

### CODE REVIEW

**Review by 0xmichalis — APPROVED** [review]
/lgtm

**Review by aixeshunter — APPROVED** [review]

**Comment by kargakis** [comment]
needs an approval

/assign @liggitt

**Pull request merged**
