### PR TITLE
Update adoption/release of DaemonSet controller history, and wait for history store sync

### PR DESCRIPTION
**Pull request by janetkuo**
**What this PR does / why we need it**: 
~Depends on #47075, so that DaemonSet controller can update history's controller ref. Ignore that commit when reviewing.~ (merged)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: #46981 

**Special notes for your reviewer**: @kubernetes/sig-apps-bugs 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by janetkuo** [comment]
/retest

Test failed due to GitHub service outage.

**Comment by lukaszo** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by enisoc** [comment]
/lgtm

---

Reviewed 8 of 8 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/47084#-:-KmCtgIoPiTJWEKH7HF-:b-8ks5qa)*

**Comment by janetkuo** [comment]
Rebased

**Comment by janetkuo** [comment]
@k8s-bot pull-kubernetes-unit test this

**Pull request merged**
