### PR TITLE
Improve cephfs fuse error log level

### PR DESCRIPTION
**Pull request by mlmhl**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Currently when setting up a cephfs volume, will fallback to kernel mount if fuse mount failed. However, the log level of according ceph-fuse error is `V(4)`, which won't be printed in many production environments(Production environments usually set log level to `V(3)`). Print it as an error or warning log maybe better.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jsafrane** [comment]
> Print it as an error or warning log maybe better.

If a cluster uses lot of Ceph volumes and use kernel mode, then the log will be full of errors that are not really errors. From admin perspective, cluster is working and volumes are mounted. Why exactly admin needs the information that kernel was used instead of fuse?

I think that `V(2)` is more appropriate.

**Comment by mlmhl** [comment]
Thanks @jsafrane ! You are right. Changed the log level to `V(2)`, PTAL.

**Pull request merged**
