### PR TITLE
Automated cherry pick of #42422

### PR DESCRIPTION
**Pull request by kerneltime**
Cherry pick of #42422 on release-1.5.

#42422: Support adding disks to more than one scsi adapter Fixes

### CODE REVIEW

**Comment by kerneltime** [comment]
@lavalamp Let me know if you want me to change any thing.. waiting for the LGTM

**Comment by lavalamp** [comment]
I think you should get an lgtm from the 1.5 release manager, @jessfraz would that be you?

**Comment by jessfraz** [comment]
I'm only 1.4

**Comment by kerneltime** [comment]
cc @saad-ali I think the last time @saad-ali was LGTMing 1.5

**Comment by mwielgus** [comment]
The PR is missing LGTM.

**Comment by BaluDontu** [comment]
@mwielgus this PR doesn't have a lgtm label. can you add if everything looks good.

**Comment by kerneltime** [comment]
@mwielgus ping..

**Comment by mwielgus** [comment]
@BaluDontu @kerneltime 
This is the task of the PR author to get all of the required lgtms and approvals from the subproject owners. 
Patch release manager responsibility is to do the final checking that the lgtmed and approved PR is not to big/doesn't change too much.  I have no knowledge about the scsi storage module so I won't lgtm this PR.

**Comment by BaluDontu** [comment]
@kerneltime : Can you please close this PR.

**Comment by mwielgus** [comment]
I'm not in charge of giving LGTM for random PR. You have to get it on your own. Once you get both LGTM and Approve I do the final checks and approve for the patch release.

**Comment by mwielgus** [comment]
@kerneltime please confirm that the fix is merged and close the pr. Removing my assignment.

**Comment by mwielgus** [comment]
No confirmation, closing.

**Pull request closed without merging**
