### PR TITLE
metadata client: add support for API streaming 

### PR DESCRIPTION
**Pull request by p0lyn0mial**
#### What type of PR is this?
/kind feature

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
xref: https://github.com/kubernetes/enhancements/issues/3157

#### Does this PR introduce a user-facing change?

```release-note
Added new functionality into the Go client code (`client-go`) library. The `List()` method for the metadata client allows enabling API streaming when fetching collections; this improves performance when listing many objects.
To request this behaviour, your client software must enable the `WatchListClient` client-go feature gate. Additionally, streaming is only available if supported by the cluster; the API server that you connect to must also support streaming.
If the API server does not support or allow streaming, then `client-go` falls back to fetching the collection using the **list** API verb.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by p0lyn0mial** [comment]
`Kubernetes e2e suite: [It] [sig-api-machinery] API Streaming (aka. WatchList) [Serial] [Feature:WatchList] should be requested by metadata client's List method when WatchListClient is enabled` green in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/127388/pull-kubernetes-e2e-gce-cos-alpha-features/1835667213365809152

**Comment by sftim** [comment]
Changelog suggestion. The thing you fetch using **list** (or via the newer streaming watch approach) is a _collection_.

```diff
-Introduces new functionality to the metadata client's `List` method, allowing users to enable API streaming. To activate this feature, users can set the `client-go.WatchListClient` feature gate.
+Added new functionality into the Go client code (`client-go`) library. The `List()` method for the metadata client allows enabling API streaming when fetching collections; this improves performance when listing many objects.
-
-It is important to note that the server must support streaming for this feature to function properly. If streaming is not supported by the server, the client will revert to using the normal `LIST` method to obtain data.
+You must enable the `WatchListClient` feature gate for `client-go` to request this behavior. Additionally, streaming is only available if supported by the cluster; the API server that you connect to must also support streaming.
+If the API server does not support or allow streaming, then `client-go` falls back to fetching the collection using the **list** API verb.
```

**Comment by p0lyn0mial** [comment]
@sftim updated, thanks.

**Pull request merged**
