### PR TITLE
clean up quotations in API docs.

### PR DESCRIPTION
**Pull request by jiahuif**
in v1 built-in APIs.

#### What type of PR is this?

/kind cleanup
#### Which issue(s) this PR fixes:

Makes progress towards #106437

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jiahuif** [comment]
/priority important-longterm
This is a clean-up and should not block 1.23 release.

**Comment by apelisse** [comment]
That's not consistent with what you implemented for enums? You've implemented as `BQ DQ RollingUpdate DQ BQ`, see https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json

cc @thockin @sftim

**Pull request closed without merging**
