### PR TITLE
remove all instances of docker tag -f

### PR DESCRIPTION
**Pull request by jessfraz**
**What this PR does / why we need it**: There is no flag `-f` for newer versions of `docker tag`

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #

**Special notes for your reviewer**:

**Release note**:

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34361)

### CODE REVIEW

**Comment by jessfraz** [comment]
@k8s-bot gci gce e2e test this

**Comment by jessfraz** [comment]
@k8s-bot kubemark e2e test this

**Comment by zmerlynn** [comment]
If `-f` is gone, don't we need to now precede all these calls with `docker rmi <foo> || true` to make this a neutral change?

**Comment by jessfraz** [comment]
How were you using the `-f`? to force a tag? I guess I don't see where this would fail?

**Comment by jessfraz** [comment]
https://github.com/docker/docker/blame/master/docs/deprecated.md#L78

**Comment by zmerlynn** [comment]
So the PR broke CLI compatibility. That sucks. The only way to be backwards compatible with both versions is what I suggested originally.

**Comment by jessfraz** [comment]
gotcha will update

**Comment by zmerlynn** [comment]
It may not be a big deal, but I still use a backleveled version of Docker to build and should probably fix that (the Docker on my workstation is still `1.9.1`). The Docker build requirements have never exactly been clear, we've always been clearer on the Docker runtime reqs for k8s. It looks like if we pegged build at 1.10, that `tag` would be guaranteed to do the same thing as 1.12, but it's not like we check the docker version we're building with anywhere. :/

**Comment by jessfraz** [comment]
i added the `docker rmi` so it should be all good now

**Review by zmerlynn — APPROVED** [review]

**Comment by jessfraz** [comment]
@k8s-bot verify test this

**Comment by jessfraz** [comment]
@k8s-bot unit test this

**Pull request merged**
