### PR TITLE
cleanup : keep use flags variable

### PR DESCRIPTION
**Pull request by zgfh**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
keep use flags variable， if not right，let me know，thanks
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/ok-to-test
/priority backlog
/kind cleanup

**Comment by zgfh** [comment]
@dims @mengqiy  please have a look

**Pull request closed without merging**
