### PR TITLE
Follow up of https://github.com/kubernetes/kubernetes/pull/76050#discussion_r271540758

### PR DESCRIPTION
**Pull request by caesarxuchao**
/sig cluster-lifecycle
/assign @BenTheElder

### CODE REVIEW

**Comment by fejta** [comment]
Ben do you want to make yourself an approver for hack? Feel free to send me a PR to this effect

/approve

**Review by BenTheElder — APPROVED** [review]
/lgtm

Thanks!
@fejta will do :-)

**Pull request merged**
