### PR TITLE
fix TestUnreservePlugin failed issue

### LINKED ISSUE #77573: TestUnreservePlugin is flaky
This test just merged in #77457 and is flaky. Example failure in https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/77564/pull-kubernetes-integration/1125927448479797249/

```
framework_test.go:310: test #1: Expected the unreserve plugin to be called only once.
```

/sig scheduling
/cc @bsalamat @danielqsj

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #77573

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by danielqsj** [comment]
Before this revert PR https://github.com/kubernetes/kubernetes/pull/77577 is merged, could you help review this hotfix ?

**Review by neolit123 — COMMENTED** [review]
/kind cleanup
/priority backlog

**Comment by danielqsj** [comment]
@neolit123  thanks. Due to the revert PR was merged. I close this PR and open another PR https://github.com/kubernetes/kubernetes/pull/77598. PTAL

**Pull request closed without merging**
