### PR TITLE
Automated cherry pick of #48762 upstream release 1.5

### PR DESCRIPTION
**Pull request by saad-ali**
Cherry picks #48762 to release-1.5:

* Workaround docker-wait freeze with 17.06.0
* Workaround moby/moby#33948 and maybe fix kops timeouts

### CODE REVIEW

**Comment by saad-ali** [comment]
CC @abgworrall

**Comment by abgworrall** [comment]
/lgtm
(although I don't have permissions to lgtm)

**Comment by saad-ali** [comment]
`pull-kubernetes-unit: k8s.io/kubernetes/federation/pkg/kubefed/init TestCertsTLS` will fail until cherrypick https://github.com/kubernetes/kubernetes/pull/48903 is merged. Will manually merge on green to break the deadlock and unblock other PRs.

**Comment by abgworrall** [comment]
Will this need to be rebased, in order to pick up #48903, and thus get `pull-kubernetes-unit` passing ? (In retrospect, I think I should have planned to cherrypick both of them into one PR ...)

**Comment by saad-ali** [comment]
> Will this need to be rebased, in order to pick up #48903, and thus get pull-kubernetes-unit passing ? (In retrospect, I think I should have planned to cherrypick both of them into one PR ...)

Yes, looks like all the tests passed and merge bot is retesting now.

**Comment by saad-ali** [comment]
```
All checks have passed
12 successful checks
```

Merging

**Pull request merged**
