### PR TITLE
Copy Spec.Host to Status.Host on pod creation

### PR DESCRIPTION
**Pull request by yujuhong**

### CODE REVIEW

**Comment by yujuhong** [comment]
This is related to #5354.

Copying the host from spec to status probably doesn't belong in `ResetBeforeCreate()`, but since we'd eventually remove status.host, it seems like an okay temporary fix to unblock the use of `Spec.Host`.

@bgrant0607

**Comment by bgrant0607** [comment]
This is just for the case that the pod is created with Spec.Host set rather than being scheduled later? Is that the only case that doesn't work currently? 

Probably the defaulting code would be more appropriate, though I realize this was easier. I don't have a strong preference, since I'm hoping this will all be gone soon.

**Comment by yujuhong** [comment]
Yes, this PR applies only to the pods with Spec.Host already set by the client on creation. So far, this is the only case that I've discovered.

Since this is going to be removed soon, I think it's fine. I can test again once the "posting pod status from kubelet" PR is merged, and remove this if it's no longer an issue.

Thanks!

**Comment by wojtek-t** [comment]
I think it's not clear from the above:
#5256 seems to break 3 e2e tests - this PR is fixing 2 of them (the PD-related ones)

cc @jszczepkowski

**Comment by bgrant0607** [comment]
We probably should just revert #5256, then.

**Comment by wojtek-t** [comment]
This was also my first thought, but I changed my mind, because two fix all those three tests we just need to merge 2 PR that already exist:
#5355 (this one)
#5364 
Both PRs are one-liners, thus I think it might make sense to merge them instead of reverting this one.

What do you think about it?

**Comment by bgrant0607** [comment]
Ok, sure. Let's merge those 2.

**Comment by wojtek-t** [comment]
Thanks Brian!

**Pull request merged**
