### PR TITLE
Fix data race in node lifecycle controller test

### PR DESCRIPTION
**Pull request by mfojtik**
**What type of PR is this?**

/kind flake

**What this PR does / why we need it**:

Attempt to fix a data race:

```
=== RUN   Test_NodesDeleted/node_is_not_ready_and_does_not_exist
W0723 05:48:04.489133   30131 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0723 05:48:04.495879   30131 node_lifecycle_controller.go:226] Cannot find valid providerID for node name "node0", assuming non existence
==================
WARNING: DATA RACE
Read at 0x00c0002c2443 by goroutine 29:
  testing.(*common).logDepth()
      /usr/local/go/src/testing/testing.go:665 +0xa1
  testing.(*common).Logf()
      /usr/local/go/src/testing/testing.go:658 +0x8f
  testing.(*common).Logf-fm()
      /usr/local/go/src/testing/testing.go:693 +0x73
  k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartLogging.func1()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record/event.go:282 +0x24d
  k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record/event.go:308 +0x122

Previous write at 0x00c0002c2443 by goroutine 11:
  testing.tRunner.func1()
      /usr/local/go/src/testing/testing.go:900 +0x353
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:913 +0x1bb

Goroutine 29 (running) created at:
  k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record/event.go:299 +0x8f
  k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartLogging()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record/event.go:280 +0x9c
  k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/nodelifecycle.Test_NodesDeleted.func1()
      /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/nodelifecycle/node_lifecycle_controller_test.go:293 +0x4e2
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:909 +0x199
```

This is not 100% reproducible locally, might be rare, but caught in OpenShift Kubernetes fork: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_kubernetes/166/pull-ci-openshift-kubernetes-master-unit/1286171049615953920
**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mfojtik** [comment]
@wlan0 @thockin i think testing.Logf is thread-safe, but I'm not sure the eventBroadcaster.Shutdown() alone prevent this data race... better safe than sorry? :-)

**Comment by liggitt** [comment]
I think this was resolved by https://github.com/kubernetes/kubernetes/pull/93619

**Pull request closed without merging**
