### PR TITLE
Add log v for default branch

### PR DESCRIPTION
**Pull request by yuzhiquan**
#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it:
Add log v for default branch, avoid tons of useless log in client-go,like https://github.com/kubernetes-sigs/external-dns/issues/2348
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yuzhiquan** [comment]
Ping @wojtek-t @deads2k for review.

**Comment by dims** [comment]
/assign @smarterclayton  @sttts 

NOTE to Clayton/Stefan: one line change, quick review!

**Pull request closed without merging**
