### PR TITLE
remove TODO: use pkg/probe/http to do component health checking

### PR DESCRIPTION
**Pull request by mqliang**
remove TODO: use pkg/probe/http to do component health checking

### CODE REVIEW

**Comment by mqliang** [comment]
@k8s-bot unit test this please

**Comment by ncdc** [comment]
cc @kubernetes/rh-cluster-infra

**Comment by mqliang** [comment]
@k8s-bot unit test this please

**Comment by brendandburns** [comment]
@k8s-bot test this please.

**Comment by mqliang** [comment]
@k8s-bot test this please.

**Comment by mqliang** [comment]
@k8s-bot test this please.

**Comment by gmarek** [comment]
failure: #19299
@k8s-bot test this

**Pull request merged**
