### PR TITLE
kubelet: Add cpu-conversion-factor option

### PR DESCRIPTION
**Pull request by Hexta**
Use --cpu-conversion-factor to calculate effective number of CPU.
```
<Effective number of CPU> = <Real number of CPU> * cpu-conversion-factor
```
In accordance with https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resources.md#processor-cycles

It will be extremely useful for heterogeneous configurations where same
application should be run on nodes with different CPU speed.

**Release note**:
```
Add  --cpu-conversion-factor option to kubelet for calculating effective number of CPU.
```

### CODE REVIEW

**Comment by Hexta** [comment]
I signed it!

**Comment by lavalamp** [comment]
I think Dawn is probably better suited for this. ...I suspect there would be a lot more to a change like this than just lying to the scheduler :) :) but I will let her take this one.

**Comment by Hexta** [comment]
@lavalamp thanks for reply!
I added commit with recalculating containers requests and limits  for CPU using cpu-conversion-factor.
```
<requests CPU> /= cpu-conversion-factor
<limits CPU> /= cpu-conversion-factor
```

**Comment by Hexta** [comment]
Is anybody here?

**Comment by TBBle** [comment]
In case anyone comes looking for this later, the referenced design document moved to https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/resources.md#processor-cycles

**Pull request closed without merging**
