### PR TITLE
ipvs proxy: add unit test for udp graceful termination

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kiman@vmware.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
In https://github.com/kubernetes/kubernetes/pull/77802/, we disabled graceful termination for UDP connections. This adds a unit test for the udp case in graceful termination where the real server should be immediately deleted even though there are active connections. 

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by lbernail — APPROVED** [review]
/lgtm

**Comment by lbernail** [comment]
As a quick side note: we don't have any check with multiple destinations. I think we should have one with 2+ destinations where we remove a single rs, to be sure that we don't remove a RS that should remain (or set its weight to 0)

**Comment by andrewsykim** [comment]
ref https://github.com/kubernetes/kubernetes/pull/78999

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
