### PR TITLE
fix kubectl taint test flake

### PR DESCRIPTION
**Pull request by kevin-wangzefeng**
**What this PR does / why we need it**:
Kubectl taint tests fail often recently, this PR is trying to fix it.

**Which issue this PR fixes**: ref #29503, #32535

**Special notes for your reviewer**:
This PR cannot 100% fix the flake, but just reduce the failing rate, if the two "kubectl taint" tests are running at the same time, it still has chance to fail.
Maybe should mark the tests "Serial" (see also #31906, #36781), but then they won't run for each PR.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36820)

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
@k8s-bot gci gce e2e test this

**Comment by kevin-wangzefeng** [comment]
@davidopp PTAL

**Comment by davidopp** [comment]
LGTM

Thanks!

**Comment by kevin-wangzefeng** [comment]
@k8s-bot kubemark e2e test this

**Pull request merged**
