### PR TITLE
Automated cherry pick of #15997

### PR DESCRIPTION
**Pull request by janetkuo**
Automated cherry pick of #15997 upstream release 1.1

### CODE REVIEW

**Comment by JanetKuo** [comment]
@k8s-bot test this

**Comment by JanetKuo** [comment]
@k8s-bot test this

**Comment by JanetKuo** [comment]
@k8s-bot test this

**Comment by janetkuo** [comment]
@k8s-bot test this

**Comment by janetkuo** [comment]
@k8s-bot test this please

**Comment by janetkuo** [comment]
@k8s-bot test this

**Comment by jlowdermilk** [comment]
@janetkuo, I don't think the failures are a mistake. The error actually does look like a compile problem.
```
17:54:31 _output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/resource_printer.go:1390: invalid indirect of minPods (type string)
```

**Comment by janetkuo** [comment]
@jlowdermilk oh thanks! It's weird that this commit passed the test before.

**Comment by jlowdermilk** [comment]
It's also possible the workspace on the pr builder got broken in some weird way, I'll take a look

**Comment by janetkuo** [comment]
@jlowdermilk looks like it's broken by the other merged PR. It should be fixed now. Thanks!

**Pull request merged**
