### PR TITLE
Automated cherry pick of #14671

### PR DESCRIPTION
**Pull request by ironcladlou**
Cherry pick of #14671 on release-1.1.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
LGTM, thanks!

**Comment by ironcladlou** [comment]
@nikhiljindal I found this along the way: https://github.com/kubernetes/kubernetes/pull/14933

**Comment by nikhiljindal** [comment]
```integration.TestServiceAccountTokenAuthentication``` which is unrelated.
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
Failed due to a Quota exceed error.
@k8s-bot ok to test

**Pull request merged**
