### PR TITLE
 Make STS available replicas optional

### LINKED ISSUE #109210: `StatefulSetStatus` attribute `availableReplicas` set to required by mistake?
### What happened?

Looking at the [swagger specifications](https://github.com/kubernetes/kubernetes/blob/17381762dd6caafe72cda9e9c39e42405391f1e9/api/openapi-spec/v3/apis__apps__v1_openapi.json#L1207) for `StatefulSetStatus`, it defines `availableReplicas` as a required attribute.  But looking at the [description](https://github.com/kubernetes/kubernetes/blob/17381762dd6caafe72cda9e9c39e42405391f1e9/api/openapi-spec/v3/apis__apps__v1_openapi.json#L1147) of `availableReplicas`, it states `...This is a beta field and enabled/disabled by StatefulSetMinReadySeconds feature gate`.  Should this in fact be a required attribute?  

I come about this from using [lightkube](https://github.com/gtsystem/lightkube/), a python package that generates models from the swagger definitions and thus builds a `StatefulSetStatus` that requires an attribute that is not enabled.

### What did you expect to happen?

That only truly required attributes be required in the swagger definition

### How can we reproduce it (as minimally and precisely as possible)?

Reproduction is not applicable as this is an issue with a spec

### Anything else we need to know?

_No response_

### Kubernetes version

Appeared in 1.22 (I believe) and affects current versions.  Does not affect 1.21

### Cloud provider

n/a

### OS version

_No response_

### Install tools

_No response_

### Container runtime (CRI) and version (if applicable)

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
#### Which issue(s) this PR fixes:

Fixes #109210

#### Does this PR introduce a user-facing change?

```release-note
Make STS available replicas optional again.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
Make STS available replicas optional again.
```

### CODE REVIEW

**Comment by liggitt** [comment]
lgtm otherwise

**Comment by liggitt** [comment]
was this cherry-picked from https://github.com/kubernetes/kubernetes/pull/109241? the openapi go file is not committed in 1.23, so drop it from the PR

**Comment by liggitt** [comment]
/reopen

still needs the comment at https://github.com/kubernetes/kubernetes/pull/109274#issuecomment-1126846071 addressed

**Comment by odinuge** [comment]
> I opened https://github.com/kubernetes/kubernetes/pull/113122/files with your comment addressed. please let me know if there is anything required. Also would appreciate it if we can get this in a 1.23 hotfix release soon. Thanks!

Thanks @ashrayjain! I'll just close this one.

/close

**Pull request closed without merging**
