### PR TITLE
Fix typo in comments on SystemReserved and KubeReserved

### PR DESCRIPTION
**Pull request by RobertKrawitz**
/kind cleanup

**What this PR does / why we need it**: Fix a typo in comments that could lead to confusion.

**Which issue(s) this PR fixes**:

Fixes #N/A

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: No

```
NONE
```

### CODE REVIEW

**Comment by RobertKrawitz** [comment]
@derekwaynecarr @dashpole fixing a comment that used `pids=` where it should be `pid=`.

**Comment by poothia** [comment]
lgtm

**Pull request merged**
