### PR TITLE
Preserve authentication webhook error message, deduplicate aggregated errors when printing

### LINKED ISSUE #73592: API server logs wrong error message for Webhook token authentication failure
**What happened**:

I configured my API server with a Webhook token authentication server by way of the "authentication-token-webhook-config-file" command-line flag, and confirmed that the API server does pass bearer tokens through, issuing HTTP POST requests with a JSON-encoded `TokenReview` body.

When my Webhook server indicates authentication failure, it responds with HTTP status code 200 and a JSON-encoded `TokenReview` in the body, this time with the `TokenReviewStatus` object's "Error" field populated. Here's an example:
```json
{
  "metadata": {
    "creationTimestamp": "2019-01-31T14:07:06Z"
  },
  "spec": {},
  "status": {
    "user": {},
    "error": "Something went wrong!"
  }
}
```
When the API server receives this response, it refuses the original motivating request with an HTTP status code 401 response, but the API server writes the following into its log file:
> E0131 14:06:40.549602       1 authentication.go:65] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, invalid bearer token]]

This use of this default error message is due to an omission in file _plugin/pkg/authenticator/token/webhook/webhook.go_, where [the `(*WebhookTokenAuthenticator).AuthenticateToken` method ignores the `TokenReviewStatus` "Error" field](https://sourcegraph.com/github.com/kubernetes/apiserver@master/-/blob/plugin/pkg/authenticator/token/webhook/webhook.go#L121-123), and [only pays attention to an HTTP-level communication failure](https://sourcegraph.com/github.com/kubernetes/apiserver@master/-/blob/plugin/pkg/authenticator/token/webhook/webhook.go#L104-108).

**What you expected to happen**:

The API server should instead log a message that includes the value from [the `TokenReviewStatus` object's "Error" field](https://sourcegraph.com/github.com/kubernetes/api@master/-/blob/authentication/v1beta1/types.go#L79-81).

Per a brief discussion with @liggitt [in the "sig-auth" channel of the "Kubernetes" Slack team](https://kubernetes.slack.com/archives/C0EN96KUY/p1548944406313400), he agreed that the API server log message should include such an error message from the Webhook server, provided it's present and nonempty.

**How to reproduce it (as minimally and precisely as possible)**:

- Configure an API server to delegate to a Webhook token authentication server.
- Force that Webhook server to respond "successfully" with an HTTP 200 response, but with the "Authenticated" field set to false (or omitted) and with a particular error message in the `TokenReviewStatus` "Error" field.
- Make an HTTP request of the API server with an HTTP "Authentication" header with a value starting with the string "Bearer " followed by at least one more character.
- Inspect the logs from the API server, looking for a message that begins with "Unable to authenticate the request due to an error."

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
  AWS EC2

- OS (e.g. from /etc/os-release):
```
ID=coreos
VERSION=1967.3.0
VERSION_ID=1967.3.0
BUILD_ID=2019-01-08-0044
PRETTY_NAME="Container Linux by CoreOS 1967.3.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```

- Kernel (e.g. `uname -a`):
  `Linux ip-10-105-48-17 4.14.88-coreos #1 SMP Mon Jan 7 23:48:02 -00 2019 x86_64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz GenuineIntel GNU/Linux`

- Install tools:
  _kubeadm_

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
* Plumbs an error message returned from an authentication webhook
* Improves string output of aggregated errors containing duplicated or nested messages

**Which issue(s) this PR fixes**:
Fixes #73592

**Does this PR introduce a user-facing change?**:
```release-note
error messages returned in authentication webhook status responses are now correctly included in the apiserver log
```

/sig auth

### CODE REVIEW

**Comment by seh** [comment]
The proposed release note mentions including the Webhook server's failure message in the 401 response. #73592 was concerned with what winds up _in the API server's log file_. I don't see the previous "invalid bearer token" message in the API server's 401 response now. Is the release note correct?

**Comment by liggitt** [comment]
> The proposed release note mentions including the Webhook server's failure message in the 401 response. #73592 was concerned with what winds up _in the API server's log file_.

you're right, corrected.

**Comment by dims** [comment]
Quite the gymnastics to get the correct list of errors :) great test cases too. Thanks!

/lgtm

**Comment by liggitt** [comment]
> great test cases too. Thanks!

not quite good enough. realized a multi-level case I'd missed. updated to handle that correctly and added to the test to cover that case.

**Comment by seh** [comment]
> you're right, corrected.

After more time using my Webhook through the API server, and not getting failure messages coming through in the API server's responses, I'm wondering whether not tunneling these Webhook errors through is a deliberate decision, or just a gap in the current implementation.

I don't mean just including them in the API server log, but in the _Status_ "reason" or "message" field. Was there some concern for information (or abstraction) leaking?

**Comment by dims** [comment]
ah aggregate within aggregate! thanks.

/lgtm

**Pull request merged**
