### PR TITLE
Use %q formatter for error messages from the AWS SDK. #47789

### PR DESCRIPTION
**Pull request by rrati**
Error messages from the AWS SDK can have return keys in them, so use %q formatter for those messages.

### CODE REVIEW

**Comment by rrati** [comment]
@kubernetes/sig-aws-misc @justinsb @eparis

**Comment by gnufied** [comment]
@rrati did we double check if quote `\n` is handled correctly in syslog etc?

**Comment by rrati** [comment]
@gnufied I didn't check in syslog.  Just how %q reacted with \n in the string compared to a %v when printing to stdout.  I'll take that test and see how syslog/systemd handle it

**Comment by rrati** [comment]
@gnufied Output in systemd is the same as on stdout:

Jun 23 08:56:18 <hostname> testoutput[16718]: 3
Jun 23 08:56:18 <hostname> testoutput[16718]: 2
Jun 23 08:56:18 <hostname> testoutput[16718]: 1
Jun 23 08:56:18 <hosntame> testoutput[16718]: world
Jun 23 08:56:18 <hostname> testoutput[16718]: With v hello
Jun 23 08:56:18 <hostname> testoutput[16718]: With q "hello\nworld\n1\n2\n3"

**Review by justinsb — APPROVED** [review]
lgtm

**Pull request merged**
