### PR TITLE
Fix the link pointing to the latest api-reference

### LINKED ISSUE #19721: Broken link: Kubectl API Reference in kubernetes.io/docs
1. Open http://kubernetes.io/v1.0/docs/api-reference/definitions.html (or http://kubernetes.io/v1.0/docs/api-reference/operations.html)
2. Click on "View the latest version here."
3. It brings you to http://kubernetes.io/v1.1/docs/api-reference/definitions.html (404 not found). However the link should be http://kubernetes.io/v1.1/docs/api-reference/v1/definitions.html

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #19721 

Thanks to @timstclair for pointing out the javascript.

### CODE REVIEW

**Comment by timstclair** [comment]
LGTM, but here's an alternative solution:
Move the archived reference to `.../api-reference/v1/...` and add a 301 redirect at the old location.

**Comment by ixdy** [comment]
@eparis @brendandburns we probably need to make the merge bot ignore CI for merges to `gh-pages`.

**Comment by brendandburns** [comment]
merged to stop the madness...

**Comment by brendandburns** [comment]
@ixdy can you file a bug?

**Comment by ixdy** [comment]
@brendandburns kubernetes/contrib/issues/473

**Comment by eparis** [comment]
Should have been fixed in https://github.com/kubernetes/contrib/pull/432 ?

**Comment by eparis** [comment]
actually that only fixed 50% of the madness  :-(

**Comment by ixdy** [comment]
ah, well kubernetes/contrib#432 appears to have gone in after this PR (was originally from 10 days ago, I'm just behind).

**Pull request merged**
