### PR TITLE
More go friendly variable names.

### PR DESCRIPTION
**Pull request by humblec**
clusterId -> clusterID
volumeId  -> volumeID

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@k8s-bot ok to test

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by humblec** [comment]
@k8s-bot bazel test this

**Comment by humblec** [comment]
@k8s-bot node e2e test this

**Comment by humblec** [comment]
@thockin @smarterclayton @zmerlynn can any one of you please approve this PR ?

**Pull request merged**
