### PR TITLE
Preload aws-sdk-go godep for 1.1 branch

### PR DESCRIPTION
**Pull request by jimmidyson**
See #16238 - this just fixes it for 1.1 branch so we can get some godep bumps in e..g #16193 

/cc @eparis @justinsb @dchen1107

### CODE REVIEW

**Comment by jimmidyson** [comment]
Unrelated shippable flake:

    FAIL	k8s.io/kubernetes/pkg/kubelet/network/cni	0.111s

**Comment by eparis** [comment]
Apparently Travis isn't running the check correctly...
```
fatal: ambiguous argument 'origin/release-1.1...HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Which is really weird...   So I'm going to wait on shippable to LGTM....

**Comment by jimmidyson** [comment]
@eparis Nice to see it passed then ;) Perhaps we need to add a `git fetch origin` in there somewhere - not sure if travis just pulls down the PR branch & builds or merges with target branch first?

**Comment by eparis** [comment]
Travis is supposed to merge origin/$branch with pr/HEAD and test that.   I'll try to figure out how to dig into it in another easier to test repo.  Not your problem   :)

**Comment by jimmidyson** [comment]
Thanks!

**Comment by eparis** [comment]
shippable failure in test-integration, again...  testing again...   wth

**Comment by dchen1107** [comment]
@lavalamp This one is blocking #16238 which is blocking upgrading cAdvisor and libcontainer libraries. thanks!

**Comment by lavalamp** [comment]
Am watching. We have *got* to find a better way of testing godep than this script.

**Comment by jimmidyson** [comment]
The problem in this case is godep itself, not the script. Maybe it's time to move to something like gvt.

**Comment by eparis** [comment]
As much as the script is a PITA it is doing a really good job showing when our godeps are broken. The problem is almost always with `go get` or `godep` (and/or the fact that golang conflates the location/url of the import with how you write and `import` section, but I digress)

This script is not showing false positives. It is telling us times that a developer straight up can't use our godeps.

It would be nice if we could run it every night to find problems instead of only learning about problems the next time someone wants to make changes. Sucks to need to get a fix in only to be blocked by something broken for a while....

**Comment by lavalamp** [comment]
Yeah, my complaint isn't that it doesn't work, it's that we don't run it all the time because it involves a full download of everything.

**Comment by lavalamp** [comment]
@k8s-bot unit test this please

**Comment by lavalamp** [comment]
@ixdy / @jlowdermilk What's up with ```16:31:42 /workspace/run.sh: line 43: ./hack/install-etcd.sh: No such file or directory```?

I need a clean build on something before I merge this.

**Comment by lavalamp** [comment]
@k8s-bot unit test this please

**Comment by ixdy** [comment]
@lavalamp that is "we probably need to cherrypick #15336 into release-1.1".

**Comment by ixdy** [comment]
Oh, https://github.com/kubernetes/kubernetes/pull/16288 already opened to do that.

**Comment by jlowdermilk** [comment]
@lavalamp, yeah sorry, the pr builder can't do unit/integration against the release branches yet, because the test scripts (mostly the hack/verify...) have diverged between 1.0/1.1 and head. A couple changes need to be cherrypicked into release branches for jenkins unit/integration to work against branches.

**Comment by lavalamp** [comment]
Oh, I didn't notice this was going into 1.1 branch without a corresponding PR to master. Maybe we should have the munger flag that.

@jimmidyson Can you send this to master, too?

...now that I'm waiting for a green I wonder if this script is even run by the test given that there's no godep change...

**Comment by eparis** [comment]
Why would we want this in 1.1? https://github.com/kubernetes/kubernetes/pull/16245 doesn't work around the broken godeps, it actually makes godeps work.

**Comment by jimmidyson** [comment]
@eparis Do you mean why would we want this in *master*? You've previously said this is the right fix for 1.1 branch & the bump should only happen in master.

**Comment by eparis** [comment]
@jimmidyson yes, I updated my comment.

**Comment by jimmidyson** [comment]
@eparis Is this in the merge queue at last?

**Comment by eparis** [comment]
I will be, but it will fail...  @lavalamp can you manually merge.  submit queue bot is broken on internal E2E and it doesn't handle the incomplete "Jenkins unit/integration"....

**Comment by dchen1107** [comment]
Can we manually merge this and see if it can fix the issue for #16127? We can revert this one if it doesn't work. Thanks!

**Comment by jimmidyson** [comment]
I think #16127 is probably going to need both this & #16260.

**Comment by lavalamp** [comment]
OK, shippable passed, that's all I was waiting for.

**Comment by lavalamp** [comment]
@eparis I see, I didn't realize we were doing two different fixes for this.

**Comment by jimmidyson** [comment]
@lavalamp Now I think about it I should have rolled them into one... oops!

**Comment by dchen1107** [comment]
Thanks!

**Pull request merged**
