### PR TITLE
remove no longer supported scheduler option `runAllFilters`

### LINKED ISSUE #108770: Remove `alwaysCheckAllPredicates` in scheduler configurator
### What would you like to be added?

Since scheduler Policy API was total removed, we don't support `alwaysCheckAllPredicates` any more. https://github.com/kubernetes/kubernetes/blob/a504daa0484d35d07f144e3f65f5a481570e96ec/pkg/scheduler/factory.go#L66-L67

### Why is this needed?

Remove unsupported configuration.

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

#### What type of PR is this?
/kind feature
/sig scheduling

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/108770

#### Does this PR introduce a user-facing change?

```release-note
The scheduler framework option `runAllFilters` is removed.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kerthcet** [comment]
/hold 
Waiting for the final agreement.

**Review by Huang-Wei — COMMENTED** [review]
Some comments. LGTM otherwise.

1. Change the kind to cleanup. It's not a feature. (also reword the tile please)
2. Fixes <issue #> (instead of a particular comment)
3. The release note can be updated (the internal `alwaysCheckAllPredicates` is not exposed to end-users):
    ```
    The scheduler framework option `WithRunAllFilters` is removed.
    ```

**Comment by kerthcet** [comment]
/retitle remove no longer supported scheduler option `runAllFilters`
/remove-kind feature
/kind cleanup

**Pull request merged**
