### PR TITLE
Use the correct time field to estimate progress in deployments

### PR DESCRIPTION
**Pull request by 0xmichalis**
Fixes https://github.com/kubernetes/kubernetes/issues/36427

@kubernetes/deployment

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36430)

### CODE REVIEW

**Comment by kargakis** [comment]
@k8s-bot node e2e test this https://github.com/kubernetes/kubernetes/issues/36159

**Comment by mfojtik** [comment]
LGTM

**Comment by kargakis** [comment]
@k8s-bot unit test this https://github.com/kubernetes/kubernetes/issues/36422

**Comment by kargakis** [comment]
@k8s-bot unit test this issue: https://github.com/kubernetes/kubernetes/issues/32988

**Comment by kargakis** [comment]
@k8s-bot unit test this issue: #32988

**Comment by kargakis** [comment]
@k8s-bot unit test this issue: #32988

**Pull request merged**
