### PR TITLE
External dependency of k8s.io/api

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix https://github.com/kubernetes/kubernetes/issues/48007

It's unfortunate that k8s.io/api has external dependencies.

Most of the dependencies are introduced by "k8s.io/apimachinery/pkg/util/intstr" and ugorji.

### CODE REVIEW

**Comment by cblecker** [comment]
@caesarxuchao on a side note, should `staging/src/k8s.io/api` have an OWNERS file?

**Comment by caesarxuchao** [comment]
Yes. Will add in another PR.

**Comment by lavalamp** [comment]
The API package should NOT depend on the apimachinery package. Need to move IntOrString to a place that both can reach.

**Comment by caesarxuchao** [comment]
It's not just IntOrString, also the ObjectMeta and TypeMeta etc.

**Comment by lavalamp** [comment]
Ah right. OK, those are probably legit, at least for the moment.

**Pull request merged**
