### PR TITLE
Inventory of kubectl dependency on main repository

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

Add an import-boss file to inventory what kubectl depends on, so
we can prune this list over time and eventually get kubectl out
of the main k/k repository.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Related to https://github.com/kubernetes/kubectl/issues/114

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by pwittrock** [comment]
api deps tracked in kubernetes/kubectl#83

You can list the dependencies with this command:

```sh
go list -f '{{ join .Deps "\n"}}' k8s.io/kubernetes/cmd/kubectl | grep k8s.io/kubernetes | grep -v kubectl | grep -v vendor
```

**Comment by monopole** [comment]
Not a bad idea to raise the barrier to new bad deps.
Can you document this file with the command use to find current deps - what Phil wrote above.

You get a few more deps if you start with cmd/kubectl, might want to review the list.

**Comment by dims** [comment]
Thanks for the tips @pwittrock @monopole - I'll add more verbiage to the commit message so the steps are preserved. Also note that the `AllowedPrefixes` are about prefixes, so i was pruning them. For example:

```
                "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset"
```

will match all of
```
                "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/scheme",
                "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/admissionregistration/internalversion",
                "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/apps/internalversion",
                "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/authentication/internalversion",
                "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/authorization/internalversion",
                "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/autoscaling/internalversion",
                "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/batch/internalversion",
                "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/certificates/internalversion",
                "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/internalversion",
                "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/extensions/internalversion",
                "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/networking/internalversion",
                "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/policy/internalversion",
                "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/rbac/internalversion",
                "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/scheduling/internalversion",
                "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/settings/internalversion",
                "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/storage/internalversion",
```

However re-thinking we should just add the whole bunch in the file. So we can feel good when we yank even some of them :)

**Comment by monopole** [comment]
Suggest you add commentary to the file directly (in addition to PR commit message),
so anyone who stumbles on the "." file can immediately copy/paste the deps command etc.

**Comment by dims** [comment]
@monopole - it's a json file right? (hence no comments?)

**Comment by dims** [comment]
related to https://github.com/kubernetes/kubectl/issues/114

/test pull-kubernetes-e2e-kops-aws

**Comment by monopole** [comment]
I've seen (otherwise ignored) comment fields added to json for this reason; don't know if one exists here.

/lgtm

will be interesting to see what this does

**Comment by monopole** [comment]
you could add kubernetes/kubectl#114 to pr descript
/approve no-issue

**Pull request merged**
