### PR TITLE
fix incorrect prometheus azure metrics

### LINKED ISSUE #77721: some azure metrics are wrong
**What happened**:
Following azure metrics are wrong, `mc.observe` func is invoked twice:
```
azLoadBalancersClient.CreateOrUpdate: load_balancers_create_or_update
azLoadBalancersClient.Delete: load_balancers_delete
azLoadBalancersClient.Get: public_ip_addresses_create_or_update
azRouteTablesClient.CreateOrUpdate: route_tables_create_or_update
azPublicIPAddressesClient: public_ip_addresses_delete
azVirtualMachineScaleSetVMsClient.Udate: vmssvm_update
azDisksClient.CreateOrUpdate: disks_create_or_update
azDisksClient.Delete: disks_delete
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/assign
/sig azure

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Following azure metrics are wrong:
```
azLoadBalancersClient.CreateOrUpdate: load_balancers_create_or_update
azLoadBalancersClient.Delete: load_balancers_delete
azLoadBalancersClient.Get: public_ip_addresses_create_or_update
azRouteTablesClient.CreateOrUpdate: route_tables_create_or_update
azPublicIPAddressesClient: public_ip_addresses_delete
azVirtualMachineScaleSetVMsClient.Udate: vmssvm_update
azDisksClient.CreateOrUpdate: disks_create_or_update
azDisksClient.Delete: disks_delete
```

**Which issue(s) this PR fixes**:

Fixes #77721

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix incorrect prometheus azure metrics
```

/assign @feiskyer
/priority important-soon
/sig azure

/test pull-kubernetes-e2e-aks-engine-azure

### CODE REVIEW

**Comment by andyzhangx** [comment]
/test pull-kubernetes-e2e-aks-engine-azure
@feiskyer PTAL

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve
/test

**Pull request merged**
