### PR TITLE
Use watch param instead of deprecated /watch/ prefix

### PR DESCRIPTION
**Pull request by liggitt**
Switches clients to use watch param instead of /watch/ prefix

```release-note
Clients now use the `?watch=true` parameter to make watch API calls, instead of the `/watch/` path prefix
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
/approve

Lgtm and will mark when green

**Comment by liggitt** [comment]
@k8s-bot gci gce e2e test this

**Comment by smarterclayton** [comment]
Wanna bet?

**Comment by wojtek-t** [comment]
> Wanna bet?

:)

It seems that this PR broke our performance tests.
But looking into it, i think the issue is with the metrics, i.e. now we seem to be reporting "watch" requests as "LIST" in the prometheus.

I will see how easy is to fix this and if easy, i will fix it, otherwise I will revert this PR.

**Comment by wojtek-t** [comment]
Hmm - I don't know how to easily fix it, so i'm going to revert it to unblock submit queue.

**Pull request merged**
