### PR TITLE
Add comment for VMware support

### PR DESCRIPTION
**Pull request by xavierbaude**
to avoid loosing a lot of time

### CODE REVIEW

**Comment by xavierbaude** [comment]
I signed it!

**Comment by xavierbaude** [comment]
I signed it!

**Comment by pires** [comment]
@yujuhong this is true. I've advocated in the past to deprecate CoreOS VMware support because no one seems to maintain it. I do, however, maintain an external version with Vagrant, which supports the variable used.

> The $private_ipv4 and $public_ipv4 substitution variables referenced in other documents are only supported on Amazon EC2, Google Compute Engine, OpenStack, Rackspace, DigitalOcean, and Vagrant.

@xavierbaude check https://github.com/pires/kubernetes-vagrant-coreos-cluster and let me know.

**Comment by yujuhong** [comment]
@pires, do you think it's worth adding the comment here?

**Comment by pires** [comment]
@yujuhong tbh I think it's worth removing the VMware specific part of the CoreOS documentation, which I'll be doing in a PR in a few moments.

**Comment by xavierbaude** [comment]
Your are right, maybe it's not the right choice to put comment in master.yml file. But I can write a specific VMware ESXi procedure here with a sed of private_ip : https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_multinode_cluster.md

A lot of people and enterprise use VMware, for me it's a good opportunity to catch these people ;).

**Comment by pires** [comment]
@xavierbaude please do and open a PR for it to get merged. Right now, I'm favoring #13151

**Comment by yujuhong** [comment]
I am closing this PR now that we have #13151 and #13207

**Pull request closed without merging**
