### PR TITLE
Bump addon-manager version to v6.4-alpha.1 in kubemark

### PR DESCRIPTION
**Pull request by shyamjvs**
Fixes https://github.com/kubernetes/kubernetes/issues/41493

cc @wojtek-t @liggitt

### CODE REVIEW

**Comment by shyamjvs** [comment]
@wojtek-t We have two image registries google_containers and google-containers. Just curious what the difference between them is?

**Comment by liggitt** [comment]
LGTM

**Comment by wojtek-t** [comment]
> @wojtek-t We have two image registries google_containers and google-containers. Just curious what the difference between them is?

I have no idea. Can you check how many images we hae in both? Maybe we can deprecate some of those two?

**Comment by tonglil** [comment]
@wojtek-t I'm not sure, `google_containers` seem to redirect to `google-containers`.

For example: `gcr.io/google_containers/kubernetes-dashboard-arm64` takes me to https://console.cloud.google.com/kubernetes/images/tags/kubernetes-dashboard-arm64?location=GLOBAL&project=google-containers. Where as `https://gcr.io/google-containers/pause` goes to https://console.cloud.google.com/kubernetes/images/tags/pause?location=GLOBAL&project=google-containers.

Pulling from either registry will result in the same image.

It would be great to standardize on one of them for naming sake.

**Pull request merged**
