### PR TITLE
Fix shellcheck warnings/errors in cluster/gce/config-test.sh

### PR DESCRIPTION
**Pull request by joakimr-axis**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fixes shellcheck failures in cluster/gce/config-test.sh

**Which issue(s) this PR fixes**:
ref: #72956

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Review by fejta — COMMENTED** [review]
/approve
/lgtm

**Review by fejta — COMMENTED** [review]
/lgtm

**Comment by BenTheElder** [comment]
/approve
the bash looks great, thank you :pray: 
cc @cheftako

**Pull request merged**
