### PR TITLE
remove the TokenRequest and TokenRequestProjection feature gates

### PR DESCRIPTION
**Pull request by wawa0210**
**What type of PR is this?**

/kind cleanup
/kind deprecation

**What this PR does / why we need it**:

part of https://github.com/kubernetes/kubernetes/pull/97148

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
The GA TokenRequest and TokenRequestProjection feature gates have been removed and are unconditionally enabled. Remove explicit use of those feature gates in CLI invocations.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
Should we do a cleanup in e2e test code as well?
Refer to https://github.com/kubernetes/kubernetes/blob/3af376d3ad5009fa82c94c1ef1fed17dc1f8c29a/test/e2e/auth/service_accounts.go#L422-L426

**Comment by wawa0210** [comment]
> Should we do a cleanup in e2e test code as well?
https://github.com/kubernetes/kubernetes/blob/3af376d3ad5009fa82c94c1ef1fed17dc1f8c29a/test/e2e/auth/service_accounts.go#L422-L426

This test still works normally. These two feature gates are moved from beta to GA. The functions work by default. They just cannot be enabled through kubelet.

**Review by pacoxu — APPROVED** [review]

**Comment by ehashman** [comment]
This is for https://github.com/kubernetes/enhancements/issues/542 (issue description links back to this PR)

I think it's good to keep the e2e test to ensure that the new stable behaviour doesn't regress?

/lgtm

**Comment by tossmilestone** [comment]
@wawa0210 This PR is a big change and will impact many controller-based application, the release-note description is too short and didn't not described the full impact. And the default 1y expiration is just like an timebomb!

**Pull request merged**
