### PR TITLE
Move create* into separate package

### LINKED ISSUE #38761: kubectl create should be in its own package
Similar to the rest of our nested commands (set, rollout). Unfortunately a straight move is not possible atm because of create depending on edit (thus introducing cyclic dependencies in kubectl). We should probably move the edit functionality in a common location (eg. the already existing pkg/kubectl/cmd/util/editor) and have the kubectl commands re-use it. I am not sure if we want to do such a thing, just wanted to bring this up

@kubernetes/kubectl @kubernetes/sig-cli thoughts

### PR DESCRIPTION
**Pull request by tcharding**
**What this PR does / why we need it**:

`create` should be in its own package

**Which issue this PR fixes**

fixes #38761

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```
/sig cli
/kind cleanup

### CODE REVIEW

**Comment by tcharding** [comment]
Should this be spit into separate commits?

**Comment by tcharding** [comment]
Note: I had to add imports manually

**Comment by fabianofranz** [comment]
> Should this be spit into separate commits?

No, one commit is ok.

Compilation error though:

```
federation/pkg/kubefed/util/util.go:153: undefined: cmd.NameFromCommandArgs
```

**Comment by tcharding** [comment]
bizarre compilation error. Patch builds and passes unit tests on my machine. Also patch doesn't touch `federation/pkg/kubefed/util/util.go` according to 

`git diff-tree --no-commit-id --name-only -r bf4b8bf | grep federation`

Any ideas?

**Comment by tcharding** [comment]
Hard coded paths in the tests
```
cmd.Flags().Set("filename", "../../../../examples/guestbook/frontend-service.yaml"
```
naughty, naughty

**Comment by tcharding** [comment]
All unit tests passing `git test ./...` run from within `kubernetes/pkg/kubectl/cmd`

**Comment by tcharding** [comment]
Fixed the call sites in `federation\pkg` and rebased

**Comment by tcharding** [comment]
Ran `hack/update-bazel.sh` after modifying import paths.

**Comment by tcharding** [comment]
I'm getting the following bazel build error. I am unsure how to proceed, commenting here and linking to this in slack.


```
make bazel-build
Loading: 
Loading: 0 packages loaded
ERROR: /home/tobin/build/go/src/k8s.io/kubernetes/test/integration/garbagecollector/BUILD:38:1: //test/integration/garbagecollector:package-srcs: invalid label '127.0.0.1:2100116336' in element 0 of attribute 'srcs' in 'filegroup' rule: invalid target name '127.0.0.1:2100116336': target names may not contain ':'
ERROR: package contains errors: test/integration/garbagecollector
ERROR: error loading package 'test/integration/garbagecollector': Package 'test/integration/garbagecollector' contains errors
INFO: Elapsed time: 0.926s
FAILED: Build did NOT complete successfully (16 packages loaded)
Makefile:528: recipe for target 'bazel-build' failed
make: *** [bazel-build] Error 1
```

**Comment by tcharding** [comment]
Do new PR's have to pass `hack/verify-golint.sh`? `golint` does not like the function names for this package however they are inline with the rest of `kubectl/pkg/cmd/`? Specifically, `golint` doesn't like that a lot of the functions stutter.

**Comment by tcharding** [comment]
`make test` passes locally. ATM I do not know how to proceed with fixing the `bazel` build errors.

**Comment by tcharding** [comment]
This is a duplacate of #44936, closing.

**Pull request closed without merging**
