### PR TITLE
Make a namespace before using it

### PR DESCRIPTION
**Pull request by thockin**
@bgrant0607

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
@thockin says passed for him.

**Comment by thockin** [comment]
it passed locally, I'm on alert if there are any more problems, holler and I'll jump

**Comment by bgrant0607** [comment]
Doesn't appear to fix the problem.

**Comment by bgrant0607** [comment]
Hitting this:
https://github.com/GoogleCloudPlatform/kubernetes/blob/46bd6f298ac248580a2ba9cbc322cdc1fb8ee3c9/pkg/kubectl/resource/visitor.go#L533

**Comment by bgrant0607** [comment]
It appears to get that error when creating the namespace, as I sort of suspected it would, but does still seem to create the namespace:
```
the namespace from the provided object "services-23751" does not match the namespace "default". You must pass '--namespace=services-23751' to perform this operation.
namespaces/services-23751
```

**Comment by bgrant0607** [comment]
I'm going to rollback this, and the earlier PR.

**Comment by derekwaynecarr** [comment]
Is this one I missed earlier?  Was I running e2e wrong?  Not sure why I missed this, but apologies if I had.

**Comment by thockin** [comment]
OH hell.

**Comment by derekwaynecarr** [comment]
I am also confused why the client message is happening as I am able to create a namespace locally using kubectl.  Is it possible to see the config of kubectl at this point?  Maybe there is a problem with a namespace being set on kubeconfig, but I don't remember that causing a problem before either.

**Comment by derekwaynecarr** [comment]
Which earlier PR?

**Comment by thockin** [comment]
I did a fresh build and I do not see this failure

**Comment by thockin** [comment]
I can also do it manually and see it not fail.

```
thockin@freakshow kubernetes services-e2e /$ cat /tmp/y
apiVersion: v1beta3
kind: Namespace
metadata:
  name: thtest

thockin@freakshow kubernetes services-e2e /$ k get namespaces
NAME      LABELS    STATUS
default   <none>    Active

thockin@freakshow kubernetes services-e2e /$ k --namespace=thtest create -f
/tmp/y
namespaces/thtest

thockin@freakshow kubernetes services-e2e /$ k get namespaces
NAME      LABELS    STATUS
default   <none>    Active
thtest    <none>    Active

```

**Pull request merged**
