### PR TITLE
MESOS: Remove unused Watch code in executor

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by sttts** [comment]
@jdef ptal

**Comment by karlkfi** [comment]
Do you know why the watch code was there in the first place? was it just a placeholder? do we have a backlog ticket to add it back in with a real implementation?

**Comment by jdef** [comment]
placeholder. the way that we monitor pods in the executor is pretty hokey
and needs to be re-thought.

**Comment by jdef** [comment]
lgtm

**Comment by karlkfi** [comment]
> the way that we monitor pods in the executor is pretty hokey and needs to be re-thought.

there an issue for this or is it too far out to bother?

**Comment by sttts** [comment]
A new monitoring should be part of the split of the executor and kubelet into two processes.

**Comment by jdef** [comment]
@sttts agreed

**Comment by sttts** [comment]
Rebased to be mergeable again.

**Pull request merged**
