### PR TITLE
[feature branch] Revert #62918: Expose openapi spec to API handlers

### PR DESCRIPTION
**Pull request by jennybuckley**
**What this PR does / why we need it**:
This change was merged to the feature branch too quickly without a chance to be reviewed by everyone.

#62918 (what this undoes) has one more line change because number of spaces in the line
```
Mapper:  apiGroupInfo.GroupMeta.RESTMapper
```
in k8s.io/apiserver/pkg/server/genericapiserver.go was modified by it, and that line was removed in a sync with master since #62918 was merged

```release-note
NONE
```

### CODE REVIEW

**Comment by mtaufen** [comment]
added release-note NONE

**Comment by mtaufen** [comment]
What's the status of this (8 days old)? Still looking to revert?
Nobody is assigned, currently.

**Comment by apelisse** [comment]
Thank you @mtaufen !

**Pull request merged**
