### PR TITLE
openstack: remove orphaned routes from terminated instances

### PR DESCRIPTION
**Pull request by databus23**
**What this PR does / why we need it**:
At the moment the openstack cloudprovider only returns routes where the `NextHop` address points to an existing openstack instance. This is a problem when an instance is terminated before the corresponding node is removed from k8s. The existing route is not returned by the cloudprovider anymore and therefore never considered for deletion by the route controller. When the route's `DestinationCIDR` is reassigned to a new node the router ends up with two routes pointing to a different `NextHop` leading to broken networking.

This PR removes skipping routes pointing to unknown next hops when listing routes. This should cause [this conditional](https://github.com/kubernetes/kubernetes/blob/93dc3763b0393b870855b2806b693a3224b039fa/pkg/controller/route/route_controller.go#L208) in the route controller to succeed and have the route removed if the route controller [feels responsible](https://github.com/kubernetes/kubernetes/blob/93dc3763b0393b870855b2806b693a3224b039fa/pkg/controller/route/route_controller.go#L206).

```release-note
OpenStack cloudprovider: Ensure orphaned routes are removed.
```

### CODE REVIEW

**Comment by FengyunPan** [comment]
/assign @anguslees 
PTAL

**Review by anguslees — COMMENTED** [review]
Hrm.  I feel we should **remove the `servers.ListOpts{Status: "ACTIVE"}` filter** and set `route.Blackhole=true` when we don't find the node, rather than rely on `route.TargetNode=""` triggering the removal code - since the latter is more surprising.  What do you think?

I note the AWS provider sets `Blackhole` based on a similarly-named flag from AWS api (I presume when the destination instance of the route is removed?), and otherwise skips entries where `nodeNamesByAddr[]` doesn't exist (our current behaviour).

**Comment by databus23** [comment]
@anguslees I agree on removing `servers.ListOpts{Status: "ACTIVE"}`. I saw the `Blackhole` feature on the route struct but ignored it as it seemed to be an AWS only feature.
Now that I read the AWS documentation it does kind of fit:
>  The state of a route in the route table (active | blackhole ). The blackhole state indicates that the route's target isn't available (for example, the specified gateway isn't attached to the VPC, the specified NAT instance has been terminated, and so on).

Let me change it as suggested.

**Comment by databus23** [comment]
lgty @anguslees ?

**Review by anguslees — APPROVED** [review]
/lgtm

**Comment by databus23** [comment]
@anguslees Can you give this an `/approve no-issue` or what else is required to finish up this PR?

**Comment by databus23** [comment]
Not sure whats up with the @k8s-merge-robot  constantly retesting this PR...

**Pull request merged**
