### PR TITLE
Refactor downward API volume to use AtomicWriter

### PR DESCRIPTION
**Pull request by pmorie**
Make the downward API plugin use `AtomicWriter` instead.

@thockin @saad-ali @sdminonne

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/24625)

### CODE REVIEW

**Comment by sdminonne** [comment]
LGTM thanks @pmorie

**Comment by pmorie** [comment]
@k8s-bot test this issue: #24424

**Comment by pmorie** [comment]
@k8s-bot test this issue: #24424

**Comment by pmorie** [comment]
(re-adding lgtm after rebase)

**Comment by pmorie** [comment]
@k8s-bot test this issue #24620

**Pull request merged**
