### PR TITLE
Reduce number of binaries travis builds to minimum

### PR DESCRIPTION
**Pull request by lavalamp**
Builds on #11245.

### CODE REVIEW

**Comment by lavalamp** [comment]
Hm, how to get travis to pick this up?

**Comment by lavalamp** [comment]
Looks like this shaves off 30 seconds or so. @thockin @erictune

**Comment by thockin** [comment]
Actually, I think "does everything build" is a useful part of this sanity check, so I am thumbs-down on this

**Comment by lavalamp** [comment]
Looks like it's keeping up now, so this isn't needed anyway. We can revive it if it gets bogged down in the future.

**Pull request closed without merging**
