### PR TITLE
apply #40326 on release-1.4: Prep node_e2e for GCI to COS name change

### PR DESCRIPTION
**Pull request by jessfraz**
```release-note
Prep node_e2e for GCI to COS name change
```

### CODE REVIEW

**Comment by tmrts** [comment]
Cherry pick LGTM

@Random-Liu PTAL

**Comment by mtaufen** [comment]
Thanks @jessfraz!

**Comment by saad-ali** [comment]
1.5 cherry pick in https://github.com/kubernetes/kubernetes/pull/41170 -- please take a look

**Comment by jessfraz** [comment]
merging since all green

**Pull request merged**
