### PR TITLE
Simple code and typo fixed in in controller

### PR DESCRIPTION
**Pull request by denkensk**
**What this PR does / why we need it**:
Simple code and typo fixed in in controller

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
none

**Special notes for your reviewer**:
none

**Release note**:
```release-note
none
```

### CODE REVIEW

**Comment by yue9944882** [comment]
[https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#10-trivial-edits](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#10-trivial-edits)

thanks for contributing! plz don't split trival pulls. 🙂  u can take an issue tagged `good first issue` if u r trying contributing out of curiosity. PRs are always welcome! thx!

**Comment by denkensk** [comment]
close

**Pull request closed without merging**
