### PR TITLE
Scheduler Reduce functions can use PriorityMetadata

### PR DESCRIPTION
**Pull request by gmarek**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35623)

### CODE REVIEW

**Comment by gmarek** [comment]
rerunning test - head was broken at the time.

**Comment by wojtek-t** [comment]
@gmarek - can you please rebase (to remove the commits that are already merged).

**Comment by wojtek-t** [comment]
Once done, lgtm

**Comment by gmarek** [comment]
@wojtek-t done, PTAL.

**Pull request merged**
