### PR TITLE
Fix typos in pkg/api module

### PR DESCRIPTION
**Pull request by andreykurilin**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29924)

### CODE REVIEW

**Comment by lavalamp** [comment]
```
/go/src/k8s.io/kubernetes/api/swagger-spec is out of date. Please run hack/update-swagger-spec.sh
FAILED   hack/make-rules/../../hack/verify-swagger-spec.sh	117s
```

**Comment by andreykurilin** [comment]
@lavalamp done

**Comment by lavalamp** [comment]
lgtm thanks

**Comment by andreykurilin** [comment]
I'll try to update this failure tomorrow...

**Comment by andreykurilin** [comment]
@lavalamp : I could not success with hack/update-api-reference-docs.sh . It fails with unknown reasons for me. Can you help?
```
$ hack/update-api-reference-docs.sh
Note: This assumes that swagger spec has been updated. Please run hack/update-swagger-spec.sh to ensure that.
Generating api reference docs at /home/akurilin/projects/golang/src/k8s.io/kubernetes/_output/generated_html
Reading swagger spec from: /home/akurilin/projects/golang/src/k8s.io/kubernetes/api/swagger-spec/
Starting Build
Settings evaluated using settings file '/master/settings.gradle'.
Projects loaded. Root project using build file '/build/build.gradle'.
Included projects: [root project 'build']
Evaluating root project 'build' using build file '/build/build.gradle'.
All projects evaluated.
Selected primary task 'gendocs' from project :
Tasks to be executed: [task ':gendocs']
:gendocs (Thread[main,5,main]) started.
:gendocs
Executing task ':gendocs' (up-to-date check took 0.001 secs) due to:
  Task has not declared any outputs.
reading from ./input.json
overview.adoc was written to: ./
Path processed: ...
paths.adoc was written to: ./
Definition processed: ...
definitions.adoc was written to: ./
*** generating docs to ./
:gendocs (Thread[main,5,main]) completed. Took 0.79 secs.

BUILD SUCCESSFUL

Total time: 2.72 secs

This build could be faster, please consider using the Gradle Daemon: http://gradle.org/docs/2.5/userguide/gradle_daemon.html
cp: cannot create regular file ‘/output/definitions.html’: Read-only file system
!!! Error in hack/update-api-reference-docs.sh:70
  'docker run ${user_flags} --rm -v "${TMP_IN_HOST}":/output:z -v "${SWAGGER_PATH}":/swagger-source:z -v "${REGISTER_FILE}":/register.go:z --net=host -e "https_proxy=${KUBERNETES_HTTPS_PROXY:-}" gcr.io/google_containers/gen-swagger-docs:v8 "${SWAGGER_JSON_NAME}"' exited with status 1
Call stack:
  1: hack/update-api-reference-docs.sh:70 main(...)
Exiting with status 1
```

**Comment by lavalamp** [comment]
@nikhiljindal can you say what might cause "cp: cannot create regular file
‘/output/definitions.html’: Read-only file system"?

**Comment by andreykurilin** [comment]
@nikhiljindal @lavalamp any suggestions?

**Comment by lavalamp** [comment]
try `make clean` first? You may have stumbled over some issues in our build system that should be better now?

---

Review status: 0 of 18 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/29924#-:-KPUqj2C0XSwqLXcXUVD:b-nsr0io)*

**Pull request closed without merging**
