### PR TITLE
To support kubectl exec via socks5 proxy

### LINKED ISSUE #104005: `kubectl exec` was failed when use socks5 proxy
#### What happened:
```
❯ k exec --tty sleep-64d7d56698-bct4r -n sample -c sleep -- sh
error: error sending request: Post "https://9881A2BCF1B7A06ABFBDAA4EC92FFAC3.sk1.ap-east-1.eks.amazonaws.com/api/v1/namespaces/sample/pods/sleep-64d7d56698-bct4r/exec?command=sh&container=sleep&stderr=true&stdout=true": EOF
```

#### What you expected to happen:
Not fail.

#### How to reproduce it (as minimally and precisely as possible):
To create a socks5 proxy though ssh tunnel or another way.
And add config in ~/.kube/config, for example;
```
clusters:
- cluster:
   certificate-authority-data: *****
   proxy-url: socks5://127.0.0.1:9999
   server: ****
```
#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by Patrick0308**
#### What type of PR is this?
To support kubectl exec over socks5 proxy

#### What this PR does / why we need it:
Socks5 is a commonly used proxy protocol, we need to support it.

#### Which issue(s) this PR fixes:

Fixes #104005

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by fedebongio** [comment]
/assign @caesarxuchao 
/sig cli
in the linked bug #104004 people is suggesting this is a FR rather than a bug. 
/triage accepted

**Comment by caesarxuchao** [comment]
FYI, we have a few attempts on this feature:
https://github.com/kubernetes/kubernetes/pull/84205
https://github.com/kubernetes/kubernetes/pull/72943

**Comment by Patrick0308** [comment]
reopen #104056

**Pull request closed without merging**
