### PR TITLE
Added deprecation notice and guidance for cloud providers.

### PR DESCRIPTION
**Pull request by jagosan**
**What this PR does / why we need it**:
Adding context/background and general guidance for incoming cloud providers. 

**Which issue this PR fixes** 

**Special notes for your reviewer**:
Generalized message per discussion with @bgrant0607

### CODE REVIEW

**Comment by jagosan** [comment]
CLA signed.

**Comment by thockin** [comment]
@k8s-bot ok to test

**Comment by thockin** [comment]
It should probably be README.md for consistency.

**Comment by jagosan** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by jagosan** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
