### PR TITLE
added fluentd detect-exceptions plugin to fluentd-es-image for multiline logging

### PR DESCRIPTION
**Pull request by monotek**
**What this PR does / why we need it**:
This PR adds proper multiline logging (java stacktraces for example) to fluentd-es docker image by adding the fluentd detect-exceptions plugin.

Plugin: https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions

Its also used in GCP and it also works outside of Kubernetes, so it should be safe to use it here too.

**Release note**:
```release-note
fluentd-es addon: multiline stacktraces are now grouped into one entry automatically
```

### CODE REVIEW

**Comment by crassirostris** [comment]
Looks reasonable

/ok-to-test
/approve no-issue

Deferring to @coffeepac to lgtm

**Comment by crassirostris** [comment]
Oh, I noticed the problem: you should update the configmap version so that configuration is updated properly

**Comment by monotek** [comment]
@crassirostris 
done: https://github.com/kubernetes/kubernetes/pull/58063/commits/61af8cd47b579d957b2ba654ac4b2552f9dbb3a1

**Comment by crassirostris** [comment]
@monotek You should also change the metadata in the configmap yaml to match (in the end of the file)

**Comment by monotek** [comment]
@crassirostris
sorry... done in: https://github.com/kubernetes/kubernetes/pull/58063/commits/40db04803c0d3755347e93cce335c8c0f4b7fd83

/retest

**Comment by crassirostris** [comment]
Cool, thanks! A couple of last nits from me:

- This change is user-visible, you can add a release note like `fluentd-es addon: multiline stacktraces are now grouped into one entry automatically`
- Please squash commits

**Comment by monotek** [comment]
all done :-)

**Comment by crassirostris** [comment]
LGTM, thanks a lot! Waiting for @coffeepac's feedback

**Comment by monotek** [comment]
do i have to do something about the failed test?

It says: "error deleting firewall: error during gcloud compute firewall-rules delete -q e2e-ports-05547cde --project=k8s-jkns-pr-gci-gke: exit status 1"

I doubt the problem is part of the PR?

**Comment by crassirostris** [comment]
Yup, just disregard it, it's not required for the PR to be merged

**Comment by coffeepac** [comment]
I think we need a fresh `gcr.io/google-containers/fluentd-elasticsearch` image, current version won't have this gem installed.

**Comment by crassirostris** [comment]
@coffeepac  Good catch, thanks!

@monotek Please bump the image version in the `Makefile` and in the DaemonSet yaml, I'll build it later

**Comment by monotek** [comment]
done :-)

**Comment by crassirostris** [comment]
Cool, LGTM! @coffeepac ?

**Comment by coffeepac** [comment]
thanks a bunch @monotek !

**Pull request merged**
