### PR TITLE
Build github.com/onsi/ginkgo/ginkgo as a part of the release

### PR DESCRIPTION
**Pull request by ixdy**
Builds the ginkgo test runner as a part of the release process. After this is merged, we can try using the native ginkgo runner again.

@quinton-hoole @zmerlynn

### CODE REVIEW

**Comment by ixdy** [comment]
I have no idea how to test this besides hoping for the best.

**Comment by zmerlynn** [comment]
I'm still confused. Is there nowhere to put this in the build system that makes any sense? I'm against this because it's another step before you can run e2es. (Jenkins is just mimicking the dev e2e flow, with some extras.)

**Comment by ixdy** [comment]
Other alternatives I can see:
1. build `github.com/onsi/ginkgo/ginkgo` as part of `build/release.sh` (seems a little weird, especially if one isn't going to run e2e tests, but there's really no other place to put it?)
2. run `ginkgo` from `hack/ginkgo-e2e.sh` with `go run ...` rather than calling the binary directly (not even sure if this would work, but maybe?)
3. as currently implemented: install godep and then build/install `ginkgo` using godep

I'm guessing option 1 is your preference?

**Comment by zmerlynn** [comment]
We build other test artifacts as part of "make release" and package them with the test tar. I don't see this as that different, unless the license would prohibit it.

**Comment by ixdy** [comment]
I guess the main difference here is that the rest of the test artifacts are under the `github.com/GoogleCloudPlatform/kubernetes` package. Ginkgo would not be. It's doable, it'll just require a bit of refactoring of the build scripts to support.

**Comment by zmerlynn** [comment]
I think I'd still rather go that route. If we had a real set of packages (rpms, debs, etc.), this would be different, but we don't. The tars are basically all the binaries you need to run the server, client and tests.

**Comment by quinton-hoole** [comment]
We should seriously consider building rpms, debs etc packages for
distribution.  Has anyone considered this?  Does anyone have strong
opinions either way?

Q

**Comment by ixdy** [comment]
OK, I've reworked this PR so that it builds ginkgo as a part of the release process (and copies the binary into the appropriate output directories, tarballs, etc). Can you take a look?

I'm not sure if we want to include someone familiar with the build scripts as well.

I've tested with `make` and `build/release.sh` - what else should I do?

**Comment by zmerlynn** [comment]
I'm actually pretty familiar with the build scripts, too. :)

**Comment by ixdy** [comment]
In that case, we're already set. :) I just wasn't sure who is familiar with them.

**Comment by zmerlynn** [comment]
You might try `hack/e2e-from-release.sh` to make sure the binary release is sane.

**Comment by ixdy** [comment]
`hack/e2e-from-release.sh` appears to have worked as well, I think.

**Comment by zmerlynn** [comment]
Well, damn the torpedoes?

**Comment by zmerlynn** [comment]
LGTM

**Pull request merged**
