### PR TITLE
Revert "Scheduler should use shared informer for pods"

### PR DESCRIPTION
**Pull request by wojtek-t**
This reverts commit 479f01d340b917ac3544f094f38edaed0ab44128.

@smarterclayton @deads2k - I don't really have time to debug this today, so for now I'm reverting this commit. We should try to understand what does it change with respect to #46196 (assuming that this will fix the problem).

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot unit test this

**Comment by gmarek** [comment]
\lgtm

**Comment by wojtek-t** [comment]
@deads2k @smarterclayton - so reverting this fixed the problem. It must be something wrong with this commit, though I don't know what exactly.

**Comment by deads2k** [comment]
> @deads2k @smarterclayton - so reverting this fixed the problem. It must be something wrong with this commit, though I don't know what exactly.

@wojtek-t Thanks for the heads up and for targeting the revert at a commit.

**Comment by wojtek-t** [comment]
> @wojtek-t Thanks for the heads up and for targeting the revert at a commit.

No problem. I was trying to understand the problem, but the commit looks reasonable and I didn't have time for reproducing adding logs, etc. to really debug it. But since this is just one commit, hopefully you will be able to do it.
Note that this also broke some of the scheduler predicates tests (see in the issue for it), which might be easier to reproduce even.

**Comment by smarterclayton** [comment]
Yeah, hopefully this is obvious on the predicates test.

**Comment by smarterclayton** [comment]
```
I0521 05:16:54.615] May 21 05:16:54.558: INFO: At 2017-05-21 05:06:54 -0700 PDT - event for maxp-311: {default-scheduler } FailedScheduling: No nodes are available that match all of the following predicates:: Insufficient pods (3).
I0521 05:16:54.615] May 21 05:16:54.558: INFO: At 2017-05-21 05:06:54 -0700 PDT - event for maxp-312: {default-scheduler } FailedScheduling: No nodes are available that match all of the following predicates:: Insufficient pods (3).
I0521 05:16:54.615] May 21 05:16:54.558: INFO: At 2017-05-21 05:06:54 -0700 PDT - event for maxp-313: {default-scheduler } FailedScheduling: No nodes are available that match all of the following predicates:: Insufficient pods (3).
```

and

```
I0521 05:16:54.780] May 21 05:16:54.661: INFO: e2e-image-puller-bootstrap-e2e-minion-group-3029  bootstrap-e2e-minion-group-3029  Succeeded         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-05-21 04:35:24 -0700 PDT PodCompleted } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-05-21 04:35:28 -0700 PDT PodCompleted } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-05-21 04:35:24 -0700 PDT  }]
I0521 05:16:54.780] May 21 05:16:54.661: INFO: e2e-image-puller-bootstrap-e2e-minion-group-lnb7  bootstrap-e2e-minion-group-lnb7  Succeeded         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-05-21 04:35:30 -0700 PDT PodCompleted } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-05-21 04:35:34 -0700 PDT PodCompleted } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-05-21 04:35:30 -0700 PDT  }]
I0521 05:16:54.780] May 21 05:16:54.661: INFO: e2e-image-puller-bootstrap-e2e-minion-group-zwjz  bootstrap-e2e-minion-group-zwjz  Succeeded         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-05-21 04:35:26 -0700 PDT PodCompleted } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-05-21 04:35:30 -0700 PDT PodCompleted } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-05-21 04:35:26 -0700 PDT  }]
````

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-serial/1102/build-log.txt

**Comment by smarterclayton** [comment]
So it looks like I am not properly excluding things from the cache.  That would explain the predictability.

**Pull request merged**
