### PR TITLE
NC should log the whole node condition.

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/cc @gmarek

### CODE REVIEW

**Comment by gmarek** [comment]
Why? It's NodeReady condition, so I'm not sure changing this actually adds more data.

**Comment by gyliu513** [comment]
The message makes people confused, as the message will be sth like
```
ReadyCondition for Node xxxx transitioned from True to {json file here}
```

So I think that we should keep `from` and `to` have same content. @gmarek

**Comment by gmarek** [comment]
Fair point.
/lgtm

**Pull request merged**
