### PR TITLE
Changed SdcGUID according to ScaleIO API reference

### PR DESCRIPTION
**Pull request by grebennikov**
Client module calls system libraty responsible for communicating
with ScaleIO appliance via its REST API.
According to the API reference ScaleIO returns a key "SdcGuid"

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by msau42** [comment]
@astripei70 can you find someone on your team to review this?

**Comment by astripei70** [comment]
@msau42 The change is as per the VxFlexOS v3.x API spec.
 We recommend using out-of-tree CSI driver https://github.com/dell/csi-vxflexos as we go through the process of deprecating ScaleIO in-tree plugin.

**Pull request closed without merging**
