### PR TITLE
fix: do not return early in the node informer when there is no change…

### LINKED ISSUE #108112: Addition service load balancer disruption on azure while upgrading from 1.23 to 1.23
### What happened?

Doing a micro upgrade from one level of 1.23 to another level of 1.23, we noticed disruption to  PDB based app went from about 5s to about 13s when compared to a 1.22.z to 1.22.z+1 update.

### What did you expect to happen?

I did not expect any disruption.

### How can we reproduce it (as minimally and precisely as possible)?

This one is a bit difficult, we have thousands of runs to compare averages and distributions against.  It's specifically azure, it's specifically the service load balancer, it's worst on 1.23 to 1.23 upgrades versus 1.22 to 1.23 upgrades.

### Anything else we need to know?

We tracked it down to one of these three commits:

1. https://github.com/kubernetes/kubernetes/pull/105253
2. https://github.com/kubernetes/kubernetes/pull/105839
3. https://github.com/kubernetes/kubernetes/pull/105188

When we revert all three, we see improved behavior (our test was in https://github.com/openshift/kubernetes/pull/1148).

We attempted to workaround by setting the exclude-from-lb label, but this filter prevents the change from being observed by the informer's cache: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure.go#L752-L755

When we attempted to remove the filter entirely (attempt here https://github.com/openshift/kubernetes/pull/1174/files#diff-c94e623481fb506d90b33e51830aabc3e8829a308a70dc9e4ebd0f31d436edc1R779), we get
> I0212 12:57:01.695808       1 azure_standard.go:1005] EnsureBackendPoolDeleted: skipping the node ci-ln-87q96z2-1d09d-hnn5d-worker-westus-5x7n9 belonging to another vm set CI-LN-87Q96Z2-1D09D-HNN5D_CI-LN-87Q96Z2-1D09D-HNN5D-WORKER-WESTUS-AS 

from https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/azure_standard.go#L1003-L1007

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

Azure

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by nilo19**
… of the topology label.

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

The node cache will not be updated if there is no change of the topology label, which is not expected.

#### Which issue(s) this PR fixes:

Fixes #108112

#### Does this PR introduce a user-facing change?

```release-note
fix a 1.23 regression: do not return early in the node informer when there is no change of the topology label.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]
/lgtm

Thanks for the fix. We need cherrypick this to 1.22/1.23 as well.

**Review by andrewsykim — COMMENTED** [review]
/approve

**Comment by ricky-rav** [comment]
That's great, @feiskyer, thanks a lot! 

Could you also backport it all the way to 1.20 (except for 1.21...I see that, for some reason, there is no check against topology labels in 1.21)? Thanks!

**Comment by feiskyer** [comment]
@ricky-rav 1.20 is not active now per https://kubernetes.io/releases/patch-releases/, but we should cherry-pick to other active branches.

**Pull request merged**
