### PR TITLE
kubectl: move custom columns printers and flags

### PR DESCRIPTION
**Pull request by seans3**
* Moves **CustomColumnsPrinter** to `kubectl/cmd/get`, which is the only place that uses it.
* Moves **CustomColumnsPrintFlags** to `kubectl/cmd/get`, which is the only place that uses it.
* Moves `sorter.go` and tests to `kubectl/cmd/get`, which is the only place that uses it. This move is necessary to resolve a circular dependency.
* Moves some references of `pkg/printers` to `cli-runtime/pkg/genericclioptions/printers`, which removes an internal dependency.

helps fix:
https://github.com/kubernetes/kubectl/issues/80

```release-note
NONE
```

/assign
/sig cli
/area kubectl
/kind cleanup

### CODE REVIEW

**Comment by juanvallejo** [comment]
@seans3 I think that since we expect custom-column printers to be exclusive to the `get` command, they should just be co-located with that command in `pkg/kubectl/cmd/get`

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by mtaufen** [comment]
/lgtm
after rebase

**Pull request merged**
