### PR TITLE
For LoadBalancer Service type don't create a HNS policy for empty or invalid external loadbalancer IP

### LINKED ISSUE #99964: LoadBalancer Service type with invalid external loadbalancer IP breaks the datapath
#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by sbangari**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
The PR fixes an issue where an empty IP address value in the load balancer ingress IP field is breaking the data path. Kube proxy doesn't honor the ingress IP address being empty and plumbs an invalid HNS policy. The fix prevents the plumbing of such invalid HNS policy.

#### Which issue(s) this PR fixes:

Fixes #99964

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by Keith-Mange — APPROVED** [review]
lgtm

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by feiskyer** [comment]
Add to v1.21 milestone since this is a bug fix.
/milestone v1.21

**Pull request merged**
