### PR TITLE
Fixs a validation error in teh admission registration API

### PR DESCRIPTION
**Pull request by tengqm**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

The validation logic is checking an non-existent field due to typo in source code.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tengqm** [comment]
Got this error when running `hack/update-codegen.sh` ...

```
$ hack/update-codegen.sh 
go version go1.21.1 darwin/amd64
+++ [1003 18:35:36] Generating protobufs for 66 targets
2023/10/03 18:35:40 Unrecognized package: k8s.io/apimachinery/pkg/apis/testapigroup/v1
!!! [1003 18:35:40] Call tree:
!!! [1003 18:35:40]  1: hack/update-codegen.sh:919 codegen::protobuf(...)
```

Don't know how to proceed now.

**Comment by cici37** [comment]
/lgtm
/triage accepted
I thought it should be an API change, surprisingly see it was not labeled.
/api-review
Please feel free to remove the api-review label if it does not fit :)

**Pull request merged**
