### PR TITLE
Add validation for EnvVarSource variant

### PR DESCRIPTION
**Pull request by pmorie**
Missed during the implementation of #18974 

@erictune PTAL

### CODE REVIEW

**Comment by thockin** [comment]
@k8s-bot unit test this please

**Comment by pmorie** [comment]
Re-adding LGTM after rebase.

**Comment by pmorie** [comment]
@k8s-bot test this

**Comment by thockin** [comment]
@k8s-bot test this

**Comment by pmorie** [comment]
@k8s-bot test this

**Pull request merged**
