### PR TITLE
Remove dead code in fake docker client

### PR DESCRIPTION
**Pull request by mattjmcnaughton**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
The `FakeDockerClient` had a number of methods defined on it which were
not being called anywhere. The majority were of the form `Assert...`.

In the spirit of removing dead code, remove the methods which aren't
being called.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
NONE
```

### CODE REVIEW

**Comment by mattjmcnaughton** [comment]
/assign @yujuhong
(if I'm reading the git history correctly, @yujuhong, you wrote the fake docker client, so I imagine you have a good amount of context :) )

**Comment by yujuhong** [comment]
> (if I'm reading the git history correctly, @yujuhong, you wrote the fake docker client, so I imagine you have a good amount of context :) )

I couldn't remember if I wrote it or just moved/modified it...
Regardless, a lot of the functions were replaced by higher-level fakes when we switched to CRI.  +1 for removing the dead code. 

/lgtm
/approve

**Pull request merged**
