### PR TITLE
verify-generated-files-remake.sh: fix issues reported by shellcheck.

### PR DESCRIPTION
**Pull request by ipuustin**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

I'm going through the bash scripts using `shellcheck` static analyzer. This PR fixes some issues found by `shellcheck` to make the scripts bit less fragile in regards to bash versions and potentially dangerous input.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
LGTM (without testing).
thanks @ipuustin 

/ok-to-test
/priority backlog
/sig testing
/sig release

**Comment by ipuustin** [comment]
No, I hadn't noticed such a file existed. Great that this is being tracked! There are still shellcheck issues in the file but those are difficult to fix without breaking bash 3 in OS X (because `mapfile` isn't available there).

**Comment by ixdy** [comment]
/hold cancel

eek @ macOS bash.

**Comment by ixdy** [comment]
@BenTheElder notes that might be fixable without using `mapfile` by using a loop similar to the one in `verify-shellcheck.sh`:
https://github.com/kubernetes/kubernetes/blob/8f1082c6aff6df3cb5e103474d9d846b6f8ebf90/hack/verify-shellcheck.sh#L70-L78

**Comment by ixdy** [comment]
(alternately we could require bash 4+)

**Comment by BenTheElder** [comment]
(note that shellcheck has an example loop targetting ksh that works equally well and passes the lint for bash3 https://github.com/koalaman/shellcheck/wiki/SC2206)

**Comment by ipuustin** [comment]
Thanks for the advice! I can lift the loop structure from `verify-shellcheck.sh`. That file looks like that's the canonical source of correct bash style that everyone should follow. However, it can be that here we can possibly get rid of the arrays altogether and clean up the logic a bit -- I'll fix that either in this PR or in a follow-up one.

**Pull request merged**
