### PR TITLE
clean deprecated func

### PR DESCRIPTION
**Pull request by rokkiter**
clean deprecated func
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bart0sh** [comment]
@rokkiter Did you remove `NewNamedRateLimitingQueue`? I can only see it replaced everywhere, but not removed.

**Comment by rokkiter** [comment]
Thanks to review,NewNamedRateLimitingQueue is been removed in new commit

**Comment by rokkiter** [comment]
this pr had rebase, please review.
thinks a lot.

**Pull request closed without merging**
