### PR TITLE
Bump Cluster Autoscaler to 0.6.1

### PR DESCRIPTION
**Pull request by mwielgus**
Couple minor bugfixes and godep refresh.

Do not merge until I complete the tests.

```release-note
Cluster Autoscaler - fixes issues with taints and updates kube-proxy cpu request.
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
@mwielgus - please add a release note (what bug is this bump fixing).

**Comment by mwielgus** [comment]
@wojtek-t Release notes updated.

**Comment by mwielgus** [comment]
Good to merge.

**Pull request merged**
