### PR TITLE
fix: azure disk resize error if source does not exist

### LINKED ISSUE #93020: use update disk when resize azure disk
**What happened**:
Should use update disk instead of createOrUpdate disk:  https://docs.microsoft.com/en-us/rest/api/compute/disks/update

The PVC resize is validating for the existence of the snapshot in the field 'sourceResourceId' causing the following error below:
```
Warning  VolumeResizeFailed  4m10s (x19 over 26m)  volume_expand  error expanding volume 'pr-ers-aaas-openwhisk/pr-openwhisk-couchdb-pvc' of plugin 'kubernetes.io/azure-disk': compute.DisksClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code='LinkedAuthorizationFailed' Message='The client '8387ed90-cd59-4789-bde8-2ede96178420' with object id '8387ed90-cd59-4789-bde8-2ede96178420' has permission to perform action 'Microsoft.Compute/disks/write' on scope '/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Compute/disks/restore-0f4d92cb-660f-4c37-b86b-5b0638dc2b17'; however, it does not have permission to perform action 'Microsoft.Compute/disks/beginGetAccess/action' on the linked scope(s) '/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Compute/snapshots/kubernetes-dynamic-pvc-4b469e13-4b2d-11ea-8-a312872c-1507-48b0-ac20-8f1aa1914a5d' or the linked scope(s) are invalid.'	
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/assign 
/priority important-soon
/sig cloud-provider
/area provider/azure

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR fixes azure disk resize error if source does not exist

**Which issue(s) this PR fixes**:

Fixes #93020

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix: azure disk resize error if source does not exist
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
fix: azure disk resize error if source does not exist
```

/assign @feiskyer 
/priority important-soon
/sig cloud-provider
/area provider/azure

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Comment by andyzhangx** [comment]
/hold
let me check whether I could fix the resize disk issue in this PR, thus it's easier to do cherry-pick

**Comment by andyzhangx** [comment]
/hold cancel
@feiskyer PTAL, thanks.

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Comment by andyzhangx** [comment]
@feiskyer could you approve? I already added a azure disk resize e2e test, and now it works well.

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
