### PR TITLE
disable the container health check function for sanbox

### LINKED ISSUE #98497: Is it necessary to disable the container health check function  for sanbox like the service container
**What would you like to be added**:

Is it necessary to disable the container health check function  for sanbox like the service container in [docker_sandbox.go]。 
related to：
https://github.com/kubernetes/kubernetes/issues/25829
https://github.com/kubernetes/kubernetes/pull/50796

**Why is this needed**:
[kubenetes]： As our sanbox container （pause）, it is generally not like the service container in the k8s cluster system. Health check can be set via pod.sec.

[Docker]：For the sake of CIS requirements.，user-defined healthchecks may be added during making container image （HEALTHCHECK --interval=60s --timeout=20s CMD exit 0），but，pause container  not supporting commands such as CMD exit 0, Therefore, the container-layer health check will fail. The result is as follows (unhealthy):

image

However, the health check here fails  does not affect the functions of this container as a sandbox.

**So，Is it necessary to disable the container health check function  for sanbox like the service container?**
docker_sandbox.go-->makeSandboxDockerConfig
docker_container.go--> CreateContainer -->  line: Healthcheck: &dockercontainer.HealthConfig{Test: []string{"NONE"},},

### PR DESCRIPTION
**Pull request by yangjunmyfm192085**
Signed-off-by: JunYang <yang.jun22@zte.com.cn>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
disable the container health check function for sanbox like the service container in [docker_sandbox.go]
**Which issue(s) this PR fixes**:

Fixes #98497

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by heqg** [comment]
LGTM

**Comment by yangjunmyfm192085** [comment]
Could you take a look?@SergeyKanzhelev
Thank you very much.

**Comment by yangjunmyfm192085** [comment]
@mrunalp ,could you please take a look this ? 
Thank you very much.

**Review by yangjunmyfm192085 — COMMENTED** [review]
/cc @mrunalp

**Review by yangjunmyfm192085 — COMMENTED** [review]
@mrunalp thanks for your review. I have updated.
Could you help review again, thanks

**Review by 249043822 — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
Is this PR still needed, please rebase if so (or we can close it?)

**Review by yangjunmyfm192085 — COMMENTED** [review]
@dims, thanks for reminding, but dockershim has been removed in the current code, so we closed this pr

**Pull request closed without merging**
