### PR TITLE
Fix running e2e against local cluster

### PR DESCRIPTION
**Pull request by derekwaynecarr**
required env vars were not being set.

/cc @pmorie

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31639)

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
@k8s-bot test this issue https://github.com/kubernetes/kubernetes/issues/31083

**Comment by derekwaynecarr** [comment]
ok to test

**Comment by aveshagarwal** [comment]
@derekwaynecarr what is the issue it is solving? I am able to run e2e locally without issues:

`#./hack/local-cluster-up.sh`

and then by running in another terminal:

`e2e.test --host="127.0.0.1:8080" --provider="local" --ginkgo.v=true -ginkgo.focus="Downward API" --kubeconfig="$HOME/.kube/config"`

**Comment by derekwaynecarr** [comment]
@aveshagarwal - I was getting an error when it invoked: /hack/e2e-internal/e2e-status.sh

**Pull request merged**
