### PR TITLE
Automated cherry pick of #32201

### PR DESCRIPTION
**Pull request by soltysh**
Cherry pick of #32201 on release-1.4.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32385)

### CODE REVIEW

**Comment by soltysh** [comment]
Added missing generated changes.

**Comment by foxish** [comment]
We aren't doing individual cherrypicks yet, and still in batch mode. Is there a reason why this one should be merged separately?

@nikhiljindal @soltysh

**Comment by soltysh** [comment]
@foxish there has been changes in master that make this cherry-pick non-automatic at this point. `WithAudit` invocation was moved from `genericapiserver.go` to `config.go` in that directory, which does not exists yet in 1.4 branch.

**Comment by foxish** [comment]
@soltysh All right. That makes sense. We're doing a batch of cherrypicks later today. After we get done with that, this will be next in line.

**Pull request merged**
