### PR TITLE
Replace the deprecated ioutil method in the staging apimachinery directory

### PR DESCRIPTION
**Pull request by HirazawaUi**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Replace the deprecated ioutil method, Because they are no longer recommended in go version 1.16 or 1.17

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by yangjunmyfm192085 — APPROVED** [review]
/ok-to-test

**Comment by apelisse** [comment]
Will someone write a script that:
1. Does this automatically
2. Does this automatically and check as a CI job that it didn't do anything?

**Comment by HirazawaUi** [comment]
> Will someone write a script that:
> 
> 1. Does this automatically
> 2. Does this automatically and check as a CI job that it didn't do anything?
> 
> Something similar to what we do in the hack/{verify,update} scripts?

I'd like to write scripts to automate it, but I don't quite understand the meaning of "check as a CI job that it didn't do anything" and whether the script should be done after all relevant PRs are merged or after closing all PRs

**Comment by apelisse** [comment]
Look at the files in that directory:
https://github.com/kubernetes/kubernetes/tree/master/hack
They all have a `update-$something.sh` and a `verify-$something.sh`. Most of the verify script actually run update and then check if it changed anything. Write a `update-ioutil-deprecation.sh` that properly replaces all instances everywhere, write a correspodning `verify-ioutil-deprecation.sh`. Commit these two files. Run the script to update all the locations, commit all the fixes, now everything should be good. Make a pull-request with these two commits.

**Comment by HirazawaUi** [comment]
> Look at the files in that directory: https://github.com/kubernetes/kubernetes/tree/master/hack They all have a `update-$something.sh` and a `verify-$something.sh`. Most of the verify script actually run update and then check if it changed anything. Write a `update-ioutil-deprecation.sh` that properly replaces all instances everywhere, write a correspodning `verify-ioutil-deprecation.sh`. Commit these two files. Run the script to update all the locations, commit all the fixes, now everything should be good. Make a pull-request with these two commits. Also include your verify and update script into update-all to make sure they run automatically when the verify check is performed.

Thanks for the explanation, I will finish the script later

**Comment by HirazawaUi** [comment]
@apelisse Do we need proceed with this PR？

**Pull request closed without merging**
