### PR TITLE
Fix markdown formatting

### PR DESCRIPTION
**Pull request by lavalamp**
Apparently github does different formatting on comments (where I tested this) and files.

```release-note
NONE
```

### CODE REVIEW

**Comment by apelisse** [comment]
I still don't think it looks like you want. I've tried to fix it:

1. API Types and Toolchain (OpenAPI)
   1. New Go IDL Tags
   2. New OpenAPI extensions tags
   3. OpenAPI Compilation toolchain
   4. Fix-up existing APIs
   5. CRD (`validation` field) compatible spec
2. Merging
   1. Ownership semantic
   2. Merge logic
3. Machinery/Wiring
   1. New PATCH handler Content-Type
   2. Metadata API Change
      - Added a map[workflow-id]last-applied-state to metadata.
   3. OpenAPI data model wiring to strategy/registry
   4. Updated PUT Handler
   5. Admission chain
   6. Conversion/Defaulting
   7. Validation
4. User Experience
   1. Kubectl
   2. Version skew and upgrade path
   3. Dry-run
5. Feature Health
   1. Testing
   2. Monitoring
   3. Documentation

**Comment by jennybuckley** [comment]
@apelisse
is the difference in the numbering being "i, ii, iii, ..." vs "n.1, n.2, n.3, ..." ?

**Pull request merged**
