### PR TITLE
Revert "update jwt-go to v3.0.0-4-g01aeca5"

### PR DESCRIPTION
**Pull request by krousey**
Reverts kubernetes/kubernetes#28520

Causing apiserver panic crash loop in gke e2e tests.
#27839

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x88b3ec]
goroutine 1852 [running]:
panic(0x282f900, 0xc82000e070)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
k8s.io/kubernetes/pkg/serviceaccount.(*jwtTokenAuthenticator).AuthenticateToken(0xc8203658f0, 0xc8223c28c7, 0x5c, 0x0, 0x0, 0x2, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/serviceaccount/jwt.go:138 +0x17c
k8s.io/kubernetes/pkg/auth/authenticator/bearertoken.(*Authenticator).AuthenticateRequest(0xc820384550, 0xc8222928c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/auth/authenticator/bearertoken/bearertoken.go:46 +0x1fe
k8s.io/kubernetes/plugin/pkg/auth/authenticator/request/union.unionAuthRequestHandler.AuthenticateRequest(0xc820445f00, 0x5, 0x8, 0xc8222928c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/plugin/pkg/auth/authenticator/request/union/union.go:40 +0xfa
k8s.io/kubernetes/plugin/pkg/auth/authenticator/request/union.(*unionAuthRequestHandler).AuthenticateRequest(0xc82031e700, 0xc8222928c0, 0x0, 0x0, 0x7ff2887aa9e8, 0x0, 0x0)
        <autogenerated>:1 +0xc6
k8s.io/kubernetes/pkg/auth/handlers.NewRequestAuthenticator.func1(0x7ff288635668, 0xc821716b08, 0xc8222928c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/auth/handlers/handlers.go:51 +0x9e
net/http.HandlerFunc.ServeHTTP(0xc8202a76d0, 0x7ff288635668, 0xc821716b08, 0xc8222928c0)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/api.NewRequestContextFilter.func1(0x7ff288635668, 0xc821716b08, 0xc8222928c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101 +0x157
net/http.HandlerFunc.ServeHTTP(0xc8202c71a0, 0x7ff288635668, 0xc821716b08, 0xc8222928c0)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/api.NewRequestContextFilter.func1(0x7ff288635668, 0xc821716b08, 0xc8222928c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/api/requestcontext.go:101 +0x157
net/http.HandlerFunc.ServeHTTP(0xc8202c71c0, 0x7ff288635668, 0xc821716b08, 0xc8222928c0)
        /usr/local/go/src/net/http/server.go:1618 +0x3a
k8s.io/kubernetes/pkg/apiserver.(*timeoutHandler).ServeHTTP.func1(0xc82141fee0, 0x7ff288635628, 0xc821716b08, 0xc8222928c0, 0xc82221a120)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:195 +0x91
created by k8s.io/kubernetes/pkg/apiserver.(*timeoutHandler).ServeHTTP
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/handlers.go:197 +0x15b
```

### CODE REVIEW

**Comment by cjcullen** [comment]
LGTM. Thanks.

**Comment by krousey** [comment]
cc @liggitt @colemickens

**Comment by liggitt** [comment]
since the issue is known, can we merge the actual fix (https://github.com/kubernetes/kubernetes/pull/28542) instead?

**Comment by krousey** [comment]
@liggitt I'd rather roll back to get the queue working that rushing a review

**Pull request merged**
