### PR TITLE
Fix typo in error message for anonymous field in AuthenticationConfig…

### PR DESCRIPTION
**Pull request by vinayakankugoyal**
…uration.

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

It fixes a typo in error message for the `anonymous` field in the `AuthenticationConfiguration`.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by vinayakankugoyal** [comment]
/assign @jpbetz  

since liggitt is OOO

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
