### PR TITLE
DO NOT SUBMIT test a change

### PR DESCRIPTION
**Pull request by fejta**
oh yeah

### CODE REVIEW

**Comment by fejta** [comment]
@k8s-bot kubemark gci (e2e )?test this

**Comment by fejta** [comment]
@k8s-bot kubemark gci e2e test this

**Comment by fejta** [comment]
@k8s-bot pull-kubernetes-kubemark-e2e-gce-gci test this

**Comment by fejta** [comment]
@k8s-bot kubemark e2e test this

**Comment by fejta** [comment]
@k8s-bot tell me a joke

**Comment by dims** [comment]
LOL

**Comment by ixdy** [comment]
@k8s-bot e2e test this

**Comment by ixdy** [comment]
(I have a theory I may have broken retesting if no new commits have gone into the repo between test runs. your PR is conveniently already open.)

**Comment by fejta** [comment]
Should we add sig-ixdy??? Your profile suggests there may be sufficient interest :wink:

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Comment by ixdy** [comment]
@k8s-bot aws test this

**Comment by ixdy** [comment]
@k8s-bot how do I trigger this test?

**Comment by fejta** [comment]
Cole's github context migrator is almost finished, so then it should be really easy to figure out how to retest things!!

**Comment by ixdy** [comment]
it seems like retesting might be OK; since we create a new merge commit each time, the sha1 keeps changing.

**Comment by ixdy** [comment]
@k8s-bot test this

**Comment by fejta** [comment]
@k8s-bot pull-kubernetes-unit test this
@k8s-bot pull-kubernetes-e2e-gce test this
/assign @ixdy
/unassign
/cc @rmmh 
/sig cli
/remove-sig testing

**Comment by ixdy** [comment]
@k8s-bot tell me a joke

**Comment by ixdy** [comment]
@k8s-bot test this

**Comment by ixdy** [comment]
@k8s-bot test this

**Comment by fejta** [comment]
:v20170603-4b639c3d

**Comment by fejta** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by fejta** [comment]
@k8s-bot pull-kubernetes-bazel test this

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-e2e-gce-bazel test this

**Comment by fejta** [comment]
testing 123
http://prow.k8s.io

**Comment by fejta** [comment]
testing
https://github.com/kubernetes/test-infra/pull/3785

**Comment by fejta** [comment]
Gubernator, did I horribly break you?

**Comment by fejta** [comment]
Looks like it

**Comment by fejta** [comment]
How about now?

**Comment by fejta** [comment]
Yaay!

**Pull request closed without merging**
