### PR TITLE
add a knob to enable quorum read

### PR DESCRIPTION
**Pull request by mqliang**
ref https://github.com/kubernetes/kubernetes/issues/19902

### CODE REVIEW

**Comment by mqliang** [comment]
@k8s-bot test this please

**Comment by krousey** [comment]
@k8s-bot test this

**Comment by krousey** [comment]
This looks fine for the most part. 

@nikhiljindal is this the right place to inject the quorum option in the API server config?

**Comment by nikhiljindal** [comment]
This seems like a generic knob which will be useful for all apiservers.
I think we can add it to genericapiserver.ServerRunOptions instead of adding to APIServer struct in cmd/kube-apiserver/app/options/options.go

**Comment by mqliang** [comment]
@nikhiljindal  Reworked. PTAL

**Comment by wojtek-t** [comment]
@mqliang - thanks for this change!

**Pull request merged**
