### PR TITLE
DNM: WIP: silly change to exercise the CI job

### PR DESCRIPTION
**Pull request by ffromani**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
test PR to troubleshoot the pull-kubernetes-node-kubelet-serial-cpu-manager lane

#### Which issue(s) this PR fixes:
Fixes N/A

#### Special notes for your reviewer:
test PR to troubleshoot the pull-kubernetes-node-kubelet-serial-cpu-manager lane

#### Does this PR introduce a user-facing change?
```release-note
none
```

### CODE REVIEW

**Comment by sftim** [comment]
/hold

“do not merge”

**Comment by ffromani** [comment]
/test pull-kubernetes-node-kubelet-serial-cpu-manager

it seems a CNI failure (to be further investigated). Let's retry just once to make sure.

**Comment by ffromani** [comment]
fixed by https://github.com/kubernetes/test-infra/pull/30685
related: https://github.com/kubernetes/test-infra/pull/30688

**Pull request closed without merging**
