### PR TITLE
Fixed a missing Unlock of b.delegateUpdateMutex

### PR DESCRIPTION
**Pull request by lzhfromustc**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
In `(backend).stopAllDelegates`, `b.delegateUpdateMutex.Lock()` is used without Unlock. This patch added a defer Unlock.
```Go
// stopAllDelegates closes the stopChan for every delegate to enable
// goroutines to terminate gracefully. This is a helper method to propagate
// the primary stopChan to the current delegate map.
func (b *backend) stopAllDelegates() {
	b.delegateUpdateMutex.Lock()
	for _, d := range b.GetDelegates() {
		close(d.stopChan)
	}
}
```

**Special notes for your reviewer**:
Here is all other places where b.delegateUpdateMutex is used. I think this can prove that `(backend).stopAllDelegates` is abnormal.
```Go
// addSink is called by the shared informer when a sink is added
func (b *backend) addSink(sink *auditregv1alpha1.AuditSink) {
	b.delegateUpdateMutex.Lock()
	defer b.delegateUpdateMutex.Unlock()
        ...
}

// deleteSink is called by the shared informer when a sink is deleted
func (b *backend) deleteSink(sink *auditregv1alpha1.AuditSink) {
	b.delegateUpdateMutex.Lock()
	defer b.delegateUpdateMutex.Unlock()
        ...
}

// updateSink is called by the shared informer when a sink is updated.
// The new sink is only rebuilt on spec changes. The new sink must not have
// the same uid as the previous. The new sink will be started before the old
// one is shutdown so no events will be lost
func (b *backend) updateSink(oldSink, newSink *auditregv1alpha1.AuditSink) {
	b.delegateUpdateMutex.Lock()
	defer b.delegateUpdateMutex.Unlock()
        ...
}
```

**Does this PR introduce a user-facing change?**:
NONE

```release-note
NONE
```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
please sign the cla

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm

**Comment by lzhfromustc** [comment]
Thank you @hzxuzhonghu ! It is the first time for me to open PR to kubernetes. I will ask my company about what to do and sign CLA later.

**Comment by lzhfromustc** [comment]
I signed it

**Comment by lzhfromustc** [comment]
I signed it

**Comment by jpbetz** [comment]
/lgtm

Was a deadlock ever reported due to this? Or is it possible that it never caused a deadlock because it's typically the last acquire on the lock during shutdown? Either way, the fix is correct. Thanks!

**Comment by lzhfromustc** [comment]
Ohhh, I wrongly merged my master!
I will open another PR for this bug, and refer the reviewers here.

**Pull request closed without merging**
