### PR TITLE
Skip `PreScore` when the `TopologySpreadConstraints` is specified

### PR DESCRIPTION
**Pull request by chendave**
`DefaultPodTopologySpread` need't score when the `TopologySpreadConstraints`
is specified.

`PreScore` needn't do this as well, this cut off the cost of `PreScore` if possible.

Signed-off-by: Dave Chen <dave.chen@arm.com>

/sig scheduling

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
Run with benchmark here is what I got, 

without the change, 
```
BenchmarkPerfScheduling/SchedulingBasic/5000Nodes/5000InitPods/1000PodsToSchedule-20                   1        2364095375 ns/op
```

with the change
```
BenchmarkPerfScheduling/SchedulingBasic/5000Nodes/5000InitPods/1000PodsToSchedule-20                   1        2350705128 ns/op
```

Might good to consider cherry pick this, since `DefaultPodTopologySpread` is enabled by default before the current master head.

/cc @Huang-Wei  @alculquicondor

**Comment by chendave** [comment]
hmm.... I think I read it wrong, should be skipped only when the `TopologySpreadConstraints` is in place, 
```
len(pod.Spec.TopologySpreadConstraints) != 0
```

Sorry,  I think I need to update the commit message. :(

**Comment by ahg-g** [comment]
Yes, please update the commit message, we skip this simply when PodTopologySpread constraints are specified. This change is nice to have, but should have real impact on performance, so no need to cherry pick it.

**Comment by ahg-g** [comment]
> DefaultPodTopologySpread doesn't take into account default constraints
and needn't score when the pod.Spec.TopologySpreadConstraints is not
specified.

Should be: "when the pod.Spec.TopologySpreadConstraints is specified"

Note that this score function is not configured at all if default constraints are specified and the feature flag is enabled: https://github.com/kubernetes/kubernetes/blob/d8febccacfc9d51a017be9531247689e0e36df04/pkg/scheduler/algorithmprovider/registry.go#L174

**Comment by chendave** [comment]
> > DefaultPodTopologySpread doesn't take into account default constraints
> > and needn't score when the pod.Spec.TopologySpreadConstraints is not
> > specified.
> 
> Should be: "when the pod.Spec.TopologySpreadConstraints is specified"
> 
> Note that this score function is not configured at all if default constraints are specified and the feature flag is enabled:
> 
> https://github.com/kubernetes/kubernetes/blob/d8febccacfc9d51a017be9531247689e0e36df04/pkg/scheduler/algorithmprovider/registry.go#L174

yes, I am still based on the code couple of days before, so this is not shown in my IDE, thank you!

**Comment by alculquicondor** [comment]
My 2 cents: I think the improvement in the benchmark is not significant to justify a cherry pick.

**Comment by Huang-Wei** [comment]
Thanks @kubernetes/enhancements 

I think the trivial perf improvement is due to the workload characteristics - the `SchedulingBasic ` suite doesn't have pods with TopologySpreadConstraints specified. So this sort of proves we don't need to backport it as it doesn't hit the critical path. But this PR is still valuable for workloads with TopologySpreadConstraints specified.

**Comment by chendave** [comment]
> Thanks @kubernetes/enhancements
> 
> I think the trivial perf improvement is due to the workload characteristics - the `SchedulingBasic ` suite doesn't have pods with TopologySpreadConstraints specified. So this sort of proves we don't need to backport it as it doesn't hit the critical path. But this PR is still valuable for workloads with TopologySpreadConstraints specified.

Obviously, `SchedulingBasic ` doesn't suit in this case, I use it just because my misunderstanding when I firstly read the code. 
But I still don't understand why perf improvements show the difference, will take a look later.

**Comment by ahg-g** [comment]
I am not sure I understand what perf improvement you see, are you referring to the 2364095375 vs 2350705128? that is within the margin of error! nothing to investigate.

**Comment by chendave** [comment]
> I am not sure I understand what perf improvement you see, are you referring to the 2364095375 vs 2350705128? that is within the margin of error! nothing to investigate.

gotcha, thank you!

**Pull request merged**
