### PR TITLE
Automated cherry pick of #90749: fix: azure disk dangling attach issue

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #90749 on release-1.15.

#90749: fix: azure disk dangling attach issue

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by andyzhangx** [comment]
`pull-kubernetes-e2e-azure-file` and `pull-kubernetes-e2e-azure-file-windows` tests are broken due to the compile issue, not related to this cherry-pick PR.

**Comment by tpepper** [comment]
Release 1.15 is out of support (https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md) and we're no longer doing cherry picks to the release-1.15 branch.

**Pull request closed without merging**
