### PR TITLE
Replace links to Helm Charts in example guidelines

### PR DESCRIPTION
**Pull request by pierreozoux**

### CODE REVIEW

**Comment by pierreozoux** [comment]
@k8s-bot node e2e test this
@k8s-bot non-cri node e2e test this

**Comment by pierreozoux** [comment]
@brendandburns is there anything I can do to fix these tests? I don't know what it means :disappointed:

**Comment by brendandburns** [comment]
@pierreozoux I think these are flakes and not your problem.

**Comment by brendandburns** [comment]
@k8s-bot node e2e test this
@k8s-bot non-cri node e2e test this

**Pull request merged**
