### PR TITLE
fix Remove hyperkube short aliases

### LINKED ISSUE #69896: Deprecate hyperkube short aliases
Hyperkube supports a number of short aliases for commands, such as `apiserver`, `controller-manager`, `proxy`, `scheduler`, etc, rather than the longer `kube-apiserver`, `kube-controller-manager`, `kube-proxy`, `kube-scheduler` etc.

There are comments indicating this is "unfortunate"
https://github.com/kubernetes/kubernetes/blob/ef195428a0c5b16e3f3621b7fe59fa151ca28929/cmd/hyperkube/main.go#L90-L94

and we still currently create these aliases in the hyperkube docker image:
https://github.com/kubernetes/kubernetes/blob/ef195428a0c5b16e3f3621b7fe59fa151ca28929/cluster/images/hyperkube/Dockerfile#L17-L29

It'd be nice to simplify this, assuming we can find all uses of the short aliases and remove them.

/kind cleanup

Not sure which sig should own this, so tagging a few.
/sig architecture cluster-lifecycle cli

cc @luxas @mikedanese

### PR DESCRIPTION
**Pull request by Rand01ph**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Remove hyperkube short aliases

**Which issue(s) this PR fixes**:

Fixes #69896

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Remove hyperkube short aliases from source code, Because hyperkube docker image currently create these aliases. [action required] If you are currently using /hyperkube {apiserver,scheduler,controller-manager,proxy} please switch to using the correct binary names.
```

### CODE REVIEW

**Comment by Rand01ph** [comment]
Signed the CLA

**Comment by mikedanese** [comment]
/hold

This needs a release note.

**Comment by Rand01ph** [comment]
> /hold
> 
> This needs a release note.

@mikedanese Thank you for your reminding, I add it in the PR body.

**Review by luxas — APPROVED** [review]
/lgtm

**Comment by alvaroaleman** [comment]
Any chance we can make the release note a bit more explicit? This pr removes the `/hyperkube {apiserver,scheduler,controller-manager}` commands, this is definitely an `[action required]` for anyone who uses those.

Also it would be nice if we deprecated the flags themselves next time instead of [a command that creates a symlink for them](https://github.com/kubernetes/kubernetes/pull/74975) :upside_down_face:

**Comment by dims** [comment]
@alvaroaleman wanna file a PR for the second part? Also i updated the release note and tacked on your suggestion to the end. Please do propose an alternative if this does not read better and i'll happily update it.

**Comment by alvaroaleman** [comment]
@dims thanks for updating the release note, looks much better now! What do you mean by "wanna file a PR for the second part?", for what can I file a PR there?

**Comment by dims** [comment]
@alvaroaleman from your statement "we deprecated the flags themselves" i thought i missed something which needed another PR. that's what i was referring to. thanks!

**Pull request merged**
