### PR TITLE
fix several typos in metrics.go

### PR DESCRIPTION
**Pull request by huzunhao**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
fix several typos in metrics.go.
It is easy to mislead the use of ode with unclear semantics.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by yangjunmyfm192085 — COMMENTED** [review]
/test pull-kubernetes-e2e-gce-ubuntu-containerd

**Review by s-kawamura-w664 — COMMENTED** [review]
Good catch!
/lgtm

**Comment by dgrisonnet** [comment]
/close

Thank you for your PR. It seems to only contain trivial edits. Please read our [trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits). We encourage you to take a look at confirmed issues and bugs or issues marked help-wanted.

**Pull request closed without merging**
