### PR TITLE
Use go native func after upgrading to go1.9

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Since we have already upgraded to go1.9 (#51375), use go native func after upgrading to go1.9.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
ref: #52033

**Special notes for your reviewer**:
/cc @aanm @bowei 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
Our currently supported minimum go version is go1.8.3 ( [minimum_go_version=go1.8.3](https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh#L324) ). If this PR gets merged, K8S will fail to build with go1.8.3. So, do we want to make go1.9.1 for our supported minimum go version for now? If so, we may want to announce this as the last [announcement](https://groups.google.com/forum/#!msg/kubernetes-dev/0XRRz6UhhTM/YODWVnuDBQAJ).
/cc @cblecker

**Comment by cblecker** [comment]
If we are using functions that won’t build on earlier versions, yes, we should bump the minimum version now. All the CI should be running on go1.9, so it should be safe. (cc: @ixdy @luxas)

**Review by aanm — APPROVED** [review]
Thanks for taking care of this @xiangpengzhao

**Review by cblecker — APPROVED** [review]
/lgtm

**Comment by xiangpengzhao** [comment]
Friendly ping @bowei  :)

**Pull request merged**
