### PR TITLE
Fix TODO move GetPauseImageNameForHostArch func to test/utils

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
Fix TODO move GetPauseImageNameForHostArch func to test/utils
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jianglingxia** [comment]
can help me with the test always failed? I have exec the command of verify-gofmt.sh and succeed and make succeed! thanks all!

**Review by mkumatag — APPROVED** [review]
I'm working on creating a manifest image for pause which will rule out all these functions to construct platform based images.. time being changes looks okay to me.

**Comment by jianglingxia** [comment]
/test pull-kubernetes-unit
thanks @mkumatag ,the CI always failed,you mean that my changes no problem ?

**Comment by mkumatag** [comment]
As tests were passed in previous runs, your changes are not creating the problem anyways. Let's wait for the tests result.
> /test pull-kubernetes-unit
> thanks @mkumatag ,the CI always failed,you mean that my changes no problem ?

**Comment by jianglingxia** [comment]
thanks @mkumatag 
for approve @shyamjvs  @enj  thanks

**Comment by jianglingxia** [comment]
/assign @liggitt 
PTAL thanks

**Comment by liggitt** [comment]
/approve
go ahead and squash to a single commit

**Pull request closed without merging**
