### PR TITLE
fix some bad URL in the /cluster/uju/layers/kubernetes-e2e/README.md

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

There are some bad URL when I read the file and I have fix it.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
/ok-to-test
/lgtm

Thanks for the contribution!

**Comment by wackxu** [comment]
@mikedanese Please take a look at this PR, it needs your approve, thanks.

**Comment by wackxu** [comment]
cc @mikedanese @mbruzek @Cynerva Could you help review this pr? It needs you approve.Thanks!

**Comment by Cynerva** [comment]
/approve no-issue

Thanks @wackxu for fixing these! :+1:

**Pull request merged**
