### PR TITLE
[FEATURE BRANCH] Rebase 'feature-rate-limiting' branch w/ master 

### PR DESCRIPTION
**Pull request by yue9944882**
we need commit https://github.com/kubernetes/kubernetes/commit/ffaaa90cc60d44d9708c3edb6542b981fe74c1a9 so that #77048 can pass the ci

### CODE REVIEW

**Comment by mattjmcnaughton** [comment]
@yue9944882 purely for my own curiosity, do you mind sharing more about how y'all are using feature branches for the rate limiting feature? Just trying to understand the diff workflows in use for k8s :)

**Comment by lavalamp** [comment]
@BenTheElder I think I filed an issue about the dep approvers getting tagged on these, if not, I intended to. :)

@mattjmcnaughton The primary purpose of the feature branch is to permit incremental progress / cooperative feature building while never leaving master in a state where a feature is half-done / broken.

**Comment by BenTheElder** [comment]
Yeah the current dep-approvers situation is just bad in general because it assigns the entire team instead of selecting someone, but that's not a feature branch specific problem, overall the approvers mechanisms are poorly behaved 😐

**Pull request merged**
