### PR TITLE
Apply test firewalls to both the new gke- node tags and the old k8s- tags

### PR DESCRIPTION
**Pull request by cjcullen**
This should get gke-ci and gke-test green again.

### CODE REVIEW

**Comment by cjcullen** [comment]
Oops, I forgot about teardown.

**Comment by jlowdermilk** [comment]
Needs rebase and/or `hack/run-gendocs.sh`.
```
diffing /root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/docs/ against freshly generated docs
Some md files are missing ga-beacon analytics link:
/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/examples/blog-logging/diagrams/README.md
/root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/docs/ is out of date. Please run hack/run-gendocs.sh
```

**Comment by jlowdermilk** [comment]
Rebase past https://github.com/GoogleCloudPlatform/kubernetes/commit/1ba99dcf7ae8d8c7bd6fe8aecb8c8ba8ace35bd0 to fix shippable.

**Comment by cjcullen** [comment]
Shippable is happy again.

**Comment by jlowdermilk** [comment]
lgtm

**Comment by cjcullen** [comment]
This change doesn't affect GCE E2E's so the failure is definitely a flake.

That said, it's awesome that we have e2e's running against PRs now!

**Pull request merged**
