### PR TITLE
Automated cherry pick of #57192: Reduce CPU request of Dasboard addon

### PR DESCRIPTION
**Pull request by kawych**
Cherry pick of #57192 on release-1.9.

#57192: Reduce CPU request of Dasboard addon

**Release note**:
```release-note
Free up CPU requested but unused by Kubernetes Dashboard.
```

### CODE REVIEW

**Comment by kawych** [comment]
/assign @mbohlool 
To review cherry-pick

/unassign @jbeda 
/unassign @zmerlynn 
/assign @x13n 
/assign @mikedanese

**Comment by mbohlool** [comment]
Is this fixing a bug or issue? I can't find a related issue. Also What is the user impact and why it is important to cherry pick this into 1.9?

**Comment by mbohlool** [comment]
@kawych @mikedanese @piosz @bryk

(cc'ed people from parent PR)

This cherrypick is inactive for 11 days. The deadline for 1.9.1 cherry pick approvals is today. Please update the PR with the answer to these questions:

> Is this fixing a bug or issue? I can't find a related issue. Also What is the user impact and why it is important to cherry pick this into 1.9?

**Comment by kawych** [comment]
Analogously to #57462, the problem is that resource requirements are set too high for some addons (Dashboard in this case). This is in the context of new addons, i.e. Metrics Server that was introduced in 1.8, Metadata Agent introduced in 1.9 (now disabled by default). On small clusters the addons are using up increasing fraction of resources (the biggest effect is visible on 1-node clusters), this PR aims to mitigate that. As discussed with @bryk this change is safe for Kubernetes Dashboard.

User impact of this bug:
- low (and getting lower) available resources on small clusters
- possible evictions of user workloads with cluster upgrades

**Comment by kawych** [comment]
@mbohlool 
Looks like the tests are failing due to #57728.

**Comment by mbohlool** [comment]
@kawych thanks for explanation. The PR still needs approval from anyone in this list: https://github.com/kubernetes/kubernetes/blob/master/cluster/OWNERS

I will approve it for cherrypick but please find somebody from that list to approve it.

**Comment by mbohlool** [comment]
I think I had some power to approve this as an exception. The change look simple.

**Pull request merged**
