### PR TITLE
Makefile cleanup

### PR DESCRIPTION
**Pull request by xiangpengzhao**
Keep the same style for each PHONY and rule.

cc @thockin

### CODE REVIEW

**Comment by thockin** [comment]
ok to test

**Comment by xiangpengzhao** [comment]
Jenkins unit/integration failed due to :
```
FATAL: Could not checkout 80a21a15868b023412e26bed7aabd8fb4783f1ee
......
Caused by: hudson.plugins.git.GitException: Command "/usr/bin/git checkout -f 80a21a15868b023412e26bed7aabd8fb4783f1ee" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: 80a21a15868b023412e26bed7aabd8fb4783f1ee
```
@thockin Please help me to request a re-test. Thanks!

**Comment by thockin** [comment]
@k8s-bot testthis: github issue #IGNORE

**Comment by xiangpengzhao** [comment]
Oops! The test failed again. :sweat: 
@thockin BTW, other two PRs #29683 and #27711 also need your help to review. But I don't know why they are labeled `do-not-merge` by the bot. I saw that many other PRs were also labeled, too.

**Comment by thockin** [comment]
@k8s-bot testthis: github issue #IGNORE

**Pull request merged**
