### PR TITLE
Revert "plumb context from CRI calls through kubelet"

### LINKED ISSUE #113547: [Failing test] [sig-node] Pods Extended Pod Container Status should never report success for a pending container
### Which jobs are failing?

Jobs affecting master presubmits a
https://testgrid.k8s.io/sig-release-master-blocking#gce-ubuntu-master-containerd
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind

### Which tests are failing?

[sig-node] Pods Extended Pod Container Status should never report success for a pending container

### Since when has it been failing?

Since 11-02 03.00 GMT+1

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#gce-ubuntu-master-containerd

### Reason for failure (if possible)

most probably https://github.com/kubernetes/kubernetes/pull/113408

### Anything else we need to know?

The PR that got merged flaked on those tests multiple times

https://prow.k8s.io/pr-history/?org=kubernetes&repo=kubernetes&pr=113408

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by aojea**
/kind failing-test
/kind flake
/kind regression

Fixes #113547

```release-note
NONE
```

Test started to fail around the time this test got merged.

The test fail with a context cancellation error

> Oct 28 14:06:37.039: INFO: At 2022-10-28 14:04:35 +0000 UTC - event for pod-terminate-status-1-2: {kubelet e2e-931c198785-a7d53-minion-group-s2qg} Failed: Error: context canceled

There are several places on the PR that have some questions about the context plumbed down

The PR flaked several times on the failing tests before merging

https://prow.k8s.io/pr-history/?org=kubernetes&repo=kubernetes&pr=113408

### CODE REVIEW

**Comment by liggitt** [comment]
/lgtm
/approve

I'll be happy to see this reintroduced once this blip is fixed

**Comment by liggitt** [comment]
bumping priority since this is failing the majority of e2e runs leading up to code freeze

**Comment by aojea** [comment]
/test pull-kubernetes-node-e2e-containerd

Tests passed, it failed on

> 
> I1102 14:09:11.767] Dumping logs from master locally to '/workspace/_artifacts'
> W1102 14:09:12.696] ERROR: (gcloud.compute.addresses.describe) Could not fetch resource:
> W1102 14:09:12.696]  - The resource 'projects/k8s-infra-e2e-boskos-053/regions/us-west1/addresses/bootstrap-e2e-master-ip' was not found

**Pull request merged**
