### PR TITLE
Multi master patch

### LINKED ISSUE #41019: CDK - known_tokens are wrong when rebooting one of the master randomly
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
Token, secrets, Unable to authenticate the request due to an error: crypto/rsa: verification error

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-17T20:36:07Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-17T20:20:10Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Physical servers (16 cores 32 thrads, 64GB of RAM) for worker at our own datacenter in France, Virtual Machines for K8s management (4vCPU, 8GB of RAM) (masters, lbapi, etcd), and some EC2 instances (t2.medium) for United States workers.
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS
- **Kernel** (e.g. `uname -a`): Linux mth-k8smaster-01 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: Canonical Kubernetes through Juju bundle charms

**What happened**:
After a fresh install of a new cluster through Canonical Kubernetes bundle charm, if I reboot one of my 3 masters, it reboot with a new token secret different from the two others.

**What you expected to happen**:
Those tokens need to be syced among the masters: they aren't right now. I got a new token that it loaded into the k8s object store during turn up and its not agree'ing with what the other masters have which would be why it showed up after reboot, not before.

**How to reproduce it** (as minimally and precisely as possible):
- Bootstrap a CDK with 3 masters / 5 etcd / 5 worker (all other charms scale at default value)
- Do a random reboot of 2 of your masters
- Check /srv/kubernetes/known_tokens.csv on all of them
- They must be different on all your masters now.

-> If you can't reproduce, please try again to reboot some masters again. Sometime it's random. This time it happens at the first reboot immediately after a fresh-install (no extra-operation).

**Anything else we need to know**:
Discussed on IRC #juju@freenode, bug opened at Juju team request :+1:

### PR DESCRIPTION
**Pull request by lazypower**
**What this PR does / why we need it**: Corrects a sync files issue present when running in a HA Master configuration. This PR adds logic to syncronize on first deployment for `/etc/kubernetes/serviceaccount.key` which will cause cypto verification failure if not 1:1 on each master unit. Additionally syncs basic_auth and additional files in /srv/kubernetes. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #41019

**Special notes for your reviewer**: This requires PR #41251 as a dependency before merging. 

**Release note**:

```release-note
Juju - K8s master charm now properly keeps distributed master files in sync for an HA control plane.
```

### CODE REVIEW

**Comment by ivan4th** [comment]
/lgtm

I don't see any problems with this patch, but I can't test juju-based clusters at the moment. I already mentioned this in another PR, but maybe I'm should be removed from the reviewer list of this directory?

**Comment by chuckbutler** [comment]
@k8s-bot gce etcd3 e2e test this

@k8s-bot non-cri e2e test this

**Comment by chuckbutler** [comment]
@ivan4th - I'll make sure to follow up and issue a PR removing you from the reviewers list. Thanks for letting us know you're not comfortable reviewing these submissions. I'm happy to remove you and should you ever feel comfortable moving forward just issue an incoming PR and let me know so I can +1 :)

**Comment by chuckbutler** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by chuckbutler** [comment]
@k8s-bot bazel test this

**Comment by chuckbutler** [comment]
Fantastic this looks good now.    I don't see a follow up that it's on it's way to the submit queue however, and based on PR #41256  it seems like our contributions are stuck in a limbo.

**Comment by chuckbutler** [comment]
Limbo averted. things are progressing 🎉

**Comment by chuckbutler** [comment]
@ivan4th - i got ninja'd by another branches lint fixes. Once I've got the tests settled I'll re-ping for re LGTM label. Thanks for supporting this branch until landing.

**Comment by chuckbutler** [comment]
Minor flake here - I0222 09:47:26.605] FAILED   hack/make-rules/../../hack/verify-staging-godeps.sh	211s

@k8s-bot verify test this

**Comment by chuckbutler** [comment]
upstream issue seems resolved. giving this another go

@k8s-bot verify test this

**Comment by chuckbutler** [comment]
@ivan4th - ok this looks ready to re-review/LGTM again. all the tests have passed and the merge conflict is resolved. Thanks!

**Comment by chuckbutler** [comment]
@k8s-bot bazel test this

**Comment by chuckbutler** [comment]
xref for test flakes: #40295 #39975

**Comment by chuckbutler** [comment]
@k8s-bot non-cri node e2e test this
@k8s-bot non-cri  e2e test this
@k8s-bot kops aws e2e test this
@k8s-bot kubemark e2e test this

**Comment by mbruzek** [comment]
This change has been reviewed and approved days ago.  Now this is getting"Jenkins overloaded" messages. We do want to get this change in before code freeze as it is an important fix for our cluster.

@k8s-bot gce etcd3 e2e test this
@k8s-bot gce node e2e test this

**Comment by mbruzek** [comment]
@k8s-bot gce Node e2e test this

**Comment by mbruzek** [comment]
@k8s-bot node e2e test this

**Comment by mbruzek** [comment]
All the required tests passed. I see it in the submit queue! Yeah!

**Pull request merged**
