### PR TITLE
Fix typo in lister-gen, regenerate

### PR DESCRIPTION
**Pull request by ncdc**
NamespaeLister -> NamespaceLister

@stevekuznetsov, just for you 😄

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@ncdc never been happer!

**Comment by ncdc** [comment]
@deads2k now with an updated staging client dir

**Comment by ncdc** [comment]
@smarterclayton or @lavalamp, care to approve?

**Comment by deads2k** [comment]
> @smarterclayton or @lavalamp, care to approve?

Just a typo fix there.  I'll manually add the tag for it.

**Pull request merged**
