### PR TITLE
LICENSES is the correct name of the file

### PR DESCRIPTION
**Pull request by dims**
In d39ac98cc5d54568c784ebb31852209a62171921, we changed the name of the
file in the k/k repo, but we still generate the older file name so we do
not break folks using the old name. quick look in the tar.gz shows that
we still generate the name correctly.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/lgtm
/hold for green CI

can we trigger the alpha job on this PR as a presubmit?

**Comment by dims** [comment]
Another variation to try and fix https://github.com/kubernetes/kubernetes/issues/85196

**Pull request closed without merging**
