### PR TITLE
fix check the api versions in federation up

### PR DESCRIPTION
**Pull request by xilabao**
**What this PR does / why we need it**:
$(${KUBE_ROOT}/cluster/kubectl.sh api-versions) will be change to the constant value.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
@kubernetes/sig-federation-bugs @kubernetes/sig-federation-test-failures

**Comment by madhusudancs** [comment]
What's the purpose of this change? I am not entirely sure why this is a better alternative to what is already in there.

cc @csbell

**Comment by xilabao** [comment]
@madhusudancs because `${KUBE_ROOT}/cluster/kubectl.sh api-versions`  only run once, the "while" always failed util timeout.

**Comment by madhusudancs** [comment]
@xilabao that cannot be the case. The while condition is evaluated everytime the loop is executed, that is after every 2 seconds for 10 seconds. 

Could you post your logs? Or add some additional logging statements in the loop and see what's happening.

**Comment by xilabao** [comment]
@madhusudancs  I create a test script to explain it.
In one terminal, I run the script:
```
timeout 1m bash <<EOF
  while [[ ! "$(tail -n 1 /tmp/log)" =~ "hello" ]]; do
    echo "---------------"
    sleep 2
  done
EOF
```
In another terminal: run `echo "hello" > /tmp/log`

the script stop when time out.

**Comment by madhusudancs** [comment]
@xilabao I am sorry, you are right. Expansion happens when the commands inside the subshell are evaluated. If this were a while loop not inside a subshell, this should have worked. But not inside a subshell unfortunately. Please also see @csbell's version in PR #48891.

**Comment by xilabao** [comment]
closed. #48891 looks more healthy.

**Pull request closed without merging**
