### PR TITLE
CHANGELOG: add a hyperlink to issue 18517

### PR DESCRIPTION
**Pull request by heqg**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
/add a hyperlink to issue 18517

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

```release-note
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Comment by heqg** [comment]
/assign @liggitt
can you help me to review or approve this pr ?
If it will be merged, it is much better.
Thank you very much.

**Comment by liggitt** [comment]
Please combine into https://github.com/kubernetes/kubernetes/pull/97519

**Comment by saschagrunert** [comment]
I guess we can close this one, since it is now part of https://github.com/kubernetes/kubernetes/pull/97519

/close

**Pull request closed without merging**
