### PR TITLE
Remove unused code in InterPodAffinity

### PR DESCRIPTION
**Pull request by sakeven**
Signed-off-by: sakeven <jc5930@sina.cn>

**What this PR does / why we need it**:

nodeLister and podLister are unused in InterPodAffinity.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by resouer** [comment]
I aske @kevin-wangzefeng for review (let me know if you have no bandwidth)

**Review by kevin-wangzefeng — APPROVED** [review]
/lgtm, thanks.

**Comment by sakeven** [comment]
@resouer @kevin-wangzefeng  could you approve this pr?

**Comment by resouer** [comment]
Should ask @davidopp for approve, please take a look.

**Pull request closed without merging**
