### PR TITLE
fix: Clarify allowed format for metric label overrides

### PR DESCRIPTION
**Pull request by yongruilin**
Clarify on the allowed format flag "--allow-metric-labels"

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Clarify on the allowed format flag "--allow-metric-labels"

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by pacoxu** [comment]
/lgtm
https://github.com/kubernetes/kubernetes/blob/1f9d2577da68290c0466c1404bbff6100e1e303a/staging/src/k8s.io/component-base/metrics/options_test.go#L28-L32
/priority backlog
/cc @mengjiao-liu

**Review by mengjiao-liu — COMMENTED** [review]
/lgtm
Thanks for the catch!

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
