### PR TITLE
split util/slice for kubectl

### PR DESCRIPTION
**Pull request by mengqiy**
Split util/slice to remove the dependency of kubectl on `k8s.io/kubernetes/pkg/util/slice`.

```release-note
NONE
```
/assign @apelisse @monopole 

cc: @pwittrock 

ref #48209

### CODE REVIEW

**Comment by apelisse** [comment]
Can we just remove that sort code altogether and replace with `sort.Slice`?

**Comment by mengqiy** [comment]
> Can we just remove that sort code altogether and replace with sort.Slice?

Yes we can, but we will need to define `Less()` over and over again.

I was thinking add support in upstream golang repo for this (https://github.com/golang/go/issues/8905).
But I found out we just miss the timeline https://github.com/golang/go/wiki/Go-Release-Cycle#timeline.

**Comment by mengqiy** [comment]
Fix go lint.

**Comment by mengqiy** [comment]
Rebased to fix `BUILD` file.
@apelisse PTAL. Thanks.

**Pull request merged**
