### PR TITLE
kubeadm: Add RA489 as reviewer

### PR DESCRIPTION
**Pull request by RA489**
Some of the PR done in kubeadm is below:

 https://github.com/kubernetes/kubernetes/pull/73452/files
 https://github.com/kubernetes/kubernetes/pull/74501/files
 https://github.com/kubernetes/kubernetes/pull/69511/files
 https://github.com/kubernetes/kubernetes/pull/87886/files
 https://github.com/kubernetes/kubeadm/pull/1571/files
 https://github.com/kubernetes/test-infra/pull/21643
 https://github.com/kubernetes/kubeadm/pull/2412
 https://github.com/kubernetes/kubernetes/pull/98008
 https://github.com/kubernetes/kubernetes/pull/69275/files
 https://github.com/kubernetes/kubernetes/pull/74399
 https://github.com/kubernetes/test-infra/pull/19852/files
 https://github.com/kubernetes/kubeadm/pull/2337
 https://github.com/kubernetes/kubernetes/pull/70625

Thanks!!

### CODE REVIEW

**Comment by neolit123** [comment]
+1 on my side.
/cc @fabriziopandini 

/priority backlog
/triage accepted

**Comment by fabriziopandini** [comment]
+1 from my side, thanks for all the contributions so far.
I'm looking forward for more involvement of @RA489 in the project duties like issue triage, reviews, and of course in the office hours discussions
/approve

**Comment by neolit123** [comment]
we can merge this after 1.22 opens.
1.21 is for critical PRs only at this point.

**Pull request merged**
