### PR TITLE
e2e: backport regenerate namespace name if the name is already taken …

### PR DESCRIPTION
**Pull request by ScrapCodes**
…#90591

**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
It fixes the flaky test in skew jobs which run the old code, by applying the fix offered in #90591. 
This PR backports to branch release-1.17

**Which issue(s) this PR fixes**:

#94520 

**Special notes for your reviewer**:
There is another PR for branch release-1.18 #94716 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by ScrapCodes** [comment]
Hi @knight42, please take a look !

**Review by knight42 — APPROVED** [review]
lgtm

/ok-to-test

**Comment by neolit123** [comment]
hi, i see a backport for 1.17 and .18.

https://github.com/kubernetes/kubernetes/pull/94716
https://github.com/kubernetes/kubernetes/pull/94717

is there one for 1.19?

/approve
/priority important-longterm

@kubernetes/release-managers

**Comment by knight42** [comment]
I think this fix is already included in 1.19 https://github.com/kubernetes/kubernetes/blob/v1.19.1/test/e2e/framework/util.go#L344-L355

**Comment by neolit123** [comment]
thanks for confirming, @knight42

**Comment by ScrapCodes** [comment]
Thanks @neolit123, you are right.

**Review by hasheddan — APPROVED** [review]
/lgtm
/priority important-soon

**Pull request merged**
