### PR TITLE
add-err-handling-in-images/etcd/migrate

### PR DESCRIPTION
**Pull request by hwdef**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

add error handling

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by hwdef** [comment]
| /test pull-kubernetes-verify
-- | --

**Comment by jpbetz** [comment]
/lgtm

Thanks for fixing!

**Comment by hwdef** [comment]
@jpbetz 
Can you add an approved label for this PR?
Thanks.

**Pull request merged**
