### PR TITLE
Refactor image manager for client/server container runtime

### PR DESCRIPTION
**Pull request by feiskyer**
Refactor image manager for client/server implementation of the container runtime at #13768

### CODE REVIEW

**Comment by yujuhong** [comment]
@k8s-bot ok to test

**Comment by dchen1107** [comment]
LGTM

**Comment by feiskyer** [comment]
@k8s-merge-robot ok-to-merge has already been added.

**Comment by dchen1107** [comment]
I am merging this one since it adds a useful refactory with proper test fixit.

**Pull request merged**
