### PR TITLE
Automated cherry pick of #72895 upstream release 1.12

### PR DESCRIPTION
**Pull request by bsalamat**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Improve efficiency of preemption logic in clusters with many pending pods.
```

/sig scheduling
/priority critical-urgent

### CODE REVIEW

**Comment by feiskyer** [comment]
@bsalamat please fix gofmt errors

**Comment by bsalamat** [comment]
@feiskyer Done

**Review by resouer — APPROVED** [review]
/lgtm

**Pull request merged**
