### PR TITLE
Scheduledjobs e2e

### PR DESCRIPTION
**Pull request by soltysh**
@janetkuo resubmitted e2e for SJ, I've updated all scripts to consume `KUBE_RUNTIME_CONFIG` properly in 2nd commit, ptal

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30575)

### CODE REVIEW

**Comment by janetkuo** [comment]
The change LGTM, but I'm not sure if this will break kubernetes-e2e-gke

**Comment by soltysh** [comment]
You were right GKE does not work, apparently it runs older server version. I need to talk to somebody more familiar with GKE how (or if) it's possible to enable those. For now, I've cut the 2nd commit introducing `KUBE_RUNTIME_CONFIG` to how it was before, since I'm not sure if other providers consume it properly. To address GKE problem I've added skip test, to check if SJ are available. I've checked it against GKE, that I've set up and works as expected. This will also make sure that we're not seeing errors where they should not appear and as soon as SJ are on the tests will start running. Most importantly it's run in GCE which verifies every PR. I'll leave you merging this one, since after it's in you'll be able to monitor the state and eventually roll it back, but that should not be necessary.

**Comment by janetkuo** [comment]
> To address GKE problem I've added skip test, to check if SJ are available.

In this case we usually use `framework.SkipUnlessServerVersionGTE` (see how it's used in test/e2e/kubectl.go)

**Comment by soltysh** [comment]
> In this case we usually use framework.SkipUnlessServerVersionGTE (see how it's used in test/e2e/kubectl.go)

I'll prepare an updated version as a followup.

**Pull request merged**
