### PR TITLE
DO NOT MERGE: Windows unit tests

### PR DESCRIPTION
**Pull request by claudiubelu**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by bart0sh** [comment]
@claudiubelu Thank you for your PR! Please, update PR description and fix failing CI tests.

**Comment by claudiubelu** [comment]
Most unit tests on Windows are now green or skipped, so we don't need this anymore.

/close

**Pull request closed without merging**
