### PR TITLE
Update help document address

### LINKED ISSUE #96697: kubectl explain redirect to a 404 page
**What happened**:
````
 kubectl explain pod.spec.containers.resources.limits

KIND:     Pod
VERSION:  v1

FIELD:    limits <map[string]string>

DESCRIPTION:
     Limits describes the maximum amount of compute resources allowed. More
     info:
     https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
....
````

the URL (https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/) return a 404.

**What you expected to happen**:

I expect the link in the documentation to be valid

**How to reproduce it (as minimally and precisely as possible)**:

kubectl explain pod.spec.containers.resources.limits

**Anything else we need to know?**:

**Environment**:
````
kubectl version

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

### PR DESCRIPTION
**Pull request by wawa0210**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
From the issue #96697. The redirection strategy does not work properly in some browsers. It happens that the address of the document needs to be redirected. It is a good choice to modify directly to the final address

**Which issue(s) this PR fixes**:

Fixes #96697

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by pacoxu — APPROVED** [review]

**Comment by dims** [comment]
/assign @liggitt 

Easy one Jordan, just fixes a broken URL

**Comment by liggitt** [comment]
/lgtm
/approve

probably also worth adding a redirect to the website (https://github.com/kubernetes/website/blob/master/static/_redirects) to sweep any existing attempts to find that content

**Comment by wawa0210** [comment]
> probably also worth adding a redirect to the website (https://github.com/kubernetes/website/blob/master/static/_redirects) to sweep any existing attempts to find that content

already added
https://github.com/kubernetes/website/blob/master/static/_redirects#L103

**Pull request merged**
