### PR TITLE
 Addressing #17258. Abstract ExtractParams in kubectl/run for generators to share

### PR DESCRIPTION
**Pull request by WeixuZhuang**
kubectl/run.go has a TODO in line 292, 133 which indicate that
'abstract this logic so that multiple generators can handle env in the same way.
Same for parse envs.'

This changeset creates a common ExtractParams which shares the common parameter
parsing logic for env and args.

It ensures none of the unit tests or system tests would be broken by this change.

### CODE REVIEW

**Comment by WeixuZhuang** [comment]
I signed it!

**Comment by smarterclayton** [comment]
@kargakis can you review?

**Comment by kargakis** [comment]
@WeixuZhuang thanks for the PR but it's superceded by https://github.com/kubernetes/kubernetes/pull/17195. Mind closing this and add any comments there?

**Comment by WeixuZhuang** [comment]
@kargakis Thanks, you are right. Just close it and I will add comments there.

**Comment by smarterclayton** [comment]
Closing on request

**Pull request closed without merging**
