### PR TITLE
cleancode: graph_builder.go

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:

It makes the source clean & light.

/release-note-none

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
@caesarxuchao @deads2k 
PTAL

**Comment by caesarxuchao** [comment]
Thanks, @zhangxiaoyu-zidif

**Comment by zhangxiaoyu-zidif** [comment]
@caesarxuchao when solving the fmt error,  I delete my branch by mistake. So the PR was closed automatically. Sorry for that. I re-open one: https://github.com/kubernetes/kubernetes/pull/44748.
Thanks for occupying your time and aplology for my mistake sincerelly.

**Comment by caesarxuchao** [comment]
No worries. FYI, you should be able to create a branch of the same name, then you don't need to create another PR.

**Comment by zhangxiaoyu-zidif** [comment]
@caesarxuchao Thank you very much and I will learn to use "git cmd" adroitly

**Pull request closed without merging**
