### PR TITLE
Rename project to Honkernetes

### PR DESCRIPTION
**Pull request by cblecker**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by cblecker** [comment]
If you're seeing this: This is for a dumb KubeCon demo and I'm sorry 🙃

**Comment by liggitt** [comment]
> If you're seeing this

The eye of Sauron sees all

image

**Comment by jeefy** [comment]
Once more

/honk

**Comment by jeefy** [comment]
Once more with feeling because I can't sleep

/honk

**Comment by guineveresaenger** [comment]
_release lead pondering_

**Pull request closed without merging**
