### PR TITLE
FIX: Typos in GCP auth plugin comments.

### PR DESCRIPTION
**Pull request by dooman87**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

This is a small change to docs of the gcp auth plugin fo Golang client. 

I was also thinking of adding specific example to use client-go with GCP. It took me some time to find out that I need to Base64 decode 
cluster certificate that I got from GCP API. Otherwise I was getting `x509: certificate signed by unknown authority` error. Do you think such an example would be useful?

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dooman87** [comment]
@cjcullen @php-coder Not sure why test is failing. I tried to rerun it but it seemed like it failed again. Are tests using the comments that I've changed?

**Comment by php-coder** [comment]
>  I tried to rerun it but it seemed like it failed again. Are tests using the comments that I've changed?

Unfortunately, tests are flaky and re-running them only once isn't enough :-(

/test pull-kubernetes-e2e-gce

**Comment by php-coder** [comment]
PTAL @cjcullen

**Comment by dooman87** [comment]
@php-coder @cjcullen I know there must be many more PRs to review, but wanted to check that this one on the radar still.

**Comment by php-coder** [comment]
@jlowdermilk could you review and approve this trivial change, please?

**Pull request closed without merging**
