### PR TITLE
Validation part 5

### PR DESCRIPTION
**Pull request by thockin**
Part 5 of several, builds on #17248

Make a sub-pkgs and shorter names for better readability

@lavalamp

### CODE REVIEW

**Comment by thockin** [comment]
@k8s-bot unit test this please

@k8s-bot test this please

**Comment by thockin** [comment]
@k8s-bot unit test this please

@k8s-bot test this please

**Comment by thockin** [comment]
Rebased - this one should be (relatively) easy

**Comment by thockin** [comment]
@k8s-bot test this please

**Comment by thockin** [comment]
@k8s-bot unit test this please

**Comment by thockin** [comment]
ready for review before holiday vacations :)  This should be relatively easy to review (unless you don't like the rename)

**Comment by liggitt** [comment]
:christmas_tree: refactors always make me feel festive :snowman:

**Comment by thockin** [comment]
I screwed up a rebase

**Pull request closed without merging**
