### PR TITLE
Cleanup third party (pt 2)

### PR DESCRIPTION
**Pull request by thockin**
Move forked-and-hacked golang code to the forked/ directory.  Remove ast/build/parse code that is now in stdlib.  Remove unused shell2junit

### CODE REVIEW

**Comment by thockin** [comment]
NB this is part 2.  Merge queue is so fast, it beat me to the punch on the first one!

**Comment by krousey** [comment]
@thockin see #28133 for shell2junit. I'm not sure what it's for, I was just looking through PRs and noticed this relation.

**Comment by thockin** [comment]
OK, I'll strip that from this PR

**Comment by thockin** [comment]
shell2junit is restored

**Comment by thockin** [comment]
Assigning to krousey for balance

**Comment by thockin** [comment]
ping - this one should be pretty trivial to review

**Comment by krousey** [comment]
Didn't notice the re-assignment. Sorry. And on call has been hectic this week.

Also, not enough removing in this PR for my liking.

**Pull request merged**
