### PR TITLE
Delete unused yaml files

### LINKED ISSUE #54447: Remove unused files from test/fixtures dir
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
There are many files under `test/fixtures` folder which are not used by any of the tests which can be removed.

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:
This PR is for removing some of these unused yaml files copied earlier from doc dir.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #54447

**Special notes for your reviewer**:

**Release note**:

```NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
Have we confirmed that these are no longer needed by something in kubernetes/website or kubernetes/community?

**Comment by mkumatag** [comment]
@cblecker part of https://github.com/kubernetes/kubernetes/pull/31452 these files kept only as test dependency.

BTW: I see all these files are under https://github.com/kubernetes/website/tree/master/docs/user-guide/configmap for doc purpose.

**Pull request merged**
