### PR TITLE
Default storage class for vSphere Fixes #40070

### LINKED ISSUE #40070: Create a default StorageClass for vSphere
We'd like to deprecate alpha provisioning in 1.6. In order to make current deployments working after upgrade to 1.6 we need to deploy a default StorageClass as part of installation/upgrade on vSphere so it will automatically provision volumes for PVCs marked with annotation `volume.alpha.kubernetes.io/storage-class` - the annotation will be ignored and default storage class must provision the volume instead.

On GCE and AWS, we use addon manager to install the default storage class, see https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/storage-class. Note that some extra code was needed in AWS and GCE installers to actually put the storage class into addons directory during installation, e.g. https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/container-linux/configure-helper.sh#L1129 

Please make sure that:
* A default StorageClass is deployed during "default" installation.
  * It would be nice if admin could turn this off during installation (e.g.  as `export ENABLE_DEFAULT_STORAGE_CLASS=false` on GCE)
* If any additional manual steps are needed to deploy the default storage class make sure they're documented in appropriate installation guide.

### PR DESCRIPTION
**Pull request by kerneltime**
**What this PR does / why we need it**:

Create default storage class for vSphere. This is part of the storage class GA effort https://github.com/kubernetes/features/issues/36

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

fixes #40070

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by kerneltime** [comment]
cc @BaluDontu @divyenpatel @abrarshivani @jsafrane

**Comment by kerneltime** [comment]
@k8s-bot gci gce e2e test this
@k8s-bot gce etcd3 e2e test this
@k8s-bot cvm gce e2e test this

**Comment by jsafrane** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by jsafrane** [comment]
@k8s-bot cvm gce e2e test this

**Comment by jsafrane** [comment]
@k8s-bot cvm gce e2e test this

**Comment by kerneltime** [comment]
Approvers please note. @mikedanese @jbeda

**Pull request merged**
