### PR TITLE
Fix tab completion

### LINKED ISSUE #33685: Tab completion doesn't work correctly when using `-n` instead of `--namespace`
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:16:57Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}                                                                             Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Azure
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Kernel** (e.g. `uname -a`): Whatever is in Xenial right now
- **Install tools**: Kubernetes-Anywhere

**What happened**:

I typed: `kubectl logs -n kube-system [tab]` and got non-kube-system pods suggested.

**What you expected to happen**:

To get the same results as when I type: `kubectl logs --namespace=kube-system [tab]`

**How to reproduce it** (as minimally and precisely as possible):

Try to use the short-hand flag with tab completion. Observe that it doesn't filter to the namespace correctly.

**Anything else do we need to know**:

Here's an asciinema demonstration: https://asciinema.org/a/87449

### PR DESCRIPTION
**Pull request by mengqiy**
Fix tab completion when using `-n` 

fixes #33685

cc: @sttts

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36695)

### CODE REVIEW

**Comment by sttts** [comment]
Please use a better commit message. Otherwise, nobody will understand later what the patch was for.

**Comment by sttts** [comment]
Compare https://github.com/kubernetes/kubernetes/issues/33685#issuecomment-260134911

**Comment by ymqytw** [comment]
Updated commit message. PTAL

**Comment by sttts** [comment]
It mostly works fine. Small issue:

- Try: `kubectl get pods -n kube-system --namespace default`. It gives you the default pods. 
- Try with `<tab>`. This gives you the kube-system pods.

I guess we have to map the value of `n` to `namespace`, i.e. expand the short-cut.

**Comment by ymqytw** [comment]
> `kubectl get pods -n kube-system --namespace default`

This should be an invalid command, right? I guess it is a bug related to `--namespace`

**Comment by ymqytw** [comment]
I have try commands like:
`kubectl get pod --namespace kube-system --namespace default`
`kubectl get pod --show-kind=true --show-kind=false`
It will always take the last flag when a flag appear more than once. It seems that it's a upstream issue related to `spf13/pflag`

>I guess we have to map the value of n to namespace, i.e. expand the short-cut.

This seems to be the solution.

**Comment by ymqytw** [comment]
> Try: `kubectl get pods -n kube-system --namespace default`. It gives you the default pods.
Try with `<tab>`. This gives you the kube-system pods.

@sttts Updated the code. Right now it will respect the last `--namespace` flag.
Please try something like:
`kubectl get pods -n kube-system -n default`


I found an issue with commands that
**resource kind is not at the end of the command and the last flag is a long two-word-flag**
e.g: `kubectl edit pod --output yaml [tab]`
But `kubectl edit --output yaml pod [tab]` will work.

The root cause is
1) Long flag w/o `=` like `--output` is not registered as a `two_word_flag`. In contrast, all short flags like `-f` and `-n` are registered as `two_word_flags`
2) [__kubectl_get_resource()](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/cmd.go#L92) assumes the last item in `nouns` is the resource kind. In the example above, it happens to be `yaml`.

**Comment by sttts** [comment]
Code looks good. But zsh doesn't like it:
```shell
$ exec zsh
$ source <(kubectl completion zsh)
__kubectl_declare:declare:4: __override_short_flag_to_long_mapping: inconsistent type for assignment
```

About the other issue: I have seen that before. Would be great to get that fixed.

**Comment by ymqytw** [comment]
I will get back to fix it for zsh next week.

**Comment by sttts** [comment]
Any news on this?

**Comment by ymqytw** [comment]
@sttts Sorry for late response. I don't have enough cycles for this now. It's OK if someone want to take over this. Otherwise, I will get back to this later in Q1.

**Pull request closed without merging**
