### PR TITLE
replace several error messages as constant, instead of duplicating 

### PR DESCRIPTION
**Pull request by mqliang**
This PR replace several error messages as constant, instead of duplicating

### CODE REVIEW

**Comment by ashcrow** [comment]
@mqliang  Needs a rebase.

Otherwise this looks good to me. :+1:

**Comment by thockin** [comment]
LGTM, thanks for the cleanup!

**Comment by thockin** [comment]
I kicked shippable - if it doesn't pass you might need to rebase to head and repush

**Comment by thockin** [comment]
and if you re-push, let me know.

**Comment by mqliang** [comment]
@thockin I have rebased to head and repushed.

**Pull request merged**
