### PR TITLE
Lint fixes for the master and worker Python code.

### PR DESCRIPTION
**Pull request by mbruzek**
**What this PR does / why we need it**: lint fixes for the python code.

**Which issue this PR fixes** none

**Special notes for your reviewer**: This is lint fixes for the Juju python code.

**Release note**:

```release-note
NONE
```

Please consider these changes so we can pass flake8 lint tests in our build process.

### CODE REVIEW

**Comment by chuckbutler** [comment]
+1 LGTM

/approve

**Comment by chuckbutler** [comment]
Ah, looks like it flagged a variable in our python as a bunk flag

```
I0210 10:40:49.434] Found illegal 'flag' usage. If these are false negatives you should run `hack/verify-flags-underscore.py -e > hack/verify-flags/exceptions.txt` to update the list.
I0210 10:40:49.435] cluster/juju/layers/kubernetes-master/reactive/kubernetes_master.py:        msg = "Cannot change {0} to {1}".format(service_cidr,
I0210 10:40:49.440] FAILED   hack/make-rules/../../hack/verify-flags-underscore.py	51s
I0210 10:40:49.440] Makefile:119: recipe for target 'verify' failed
W0210 10:40:49.541] make: *** [verify] Error 1

```

@mbruzek  I'm still +1 to this if you can run the hack target to fix that flag validation fail. the other failures in that job run look unrelated to these changes.

**Comment by mbruzek** [comment]
I resolved the verification errors and rebased. Please review this change.

@k8s-bot verify test this
@k8s-bot gce etcd3 e2e test this

**Comment by chuckbutler** [comment]
Looks like the Jenkins-GCI-GKE-Smoke test failed due to a missing api version? thats new to me

relevant log here:

```
W0216 12:22:25.616] Creating cluster e2e-gke-agent-pr-50-0...
W0216 12:22:45.933] ....................done.
W0216 12:22:45.934] ERROR: (gcloud.container.clusters.create) Operation [<Operation
W0216 12:22:45.934]  name: u'operation-1487276545593-3dc39628'
W0216 12:22:45.935]  operationType: OperationTypeValueValuesEnum(CREATE_CLUSTER, 1)
W0216 12:22:45.935]  selfLink: u'https://test-container.sandbox.googleapis.com/v1/projects/943316867058/zones/us-central1-f/operations/operation-1487276545593-3dc39628'
W0216 12:22:45.935]  status: StatusValueValuesEnum(DONE, 3)
W0216 12:22:45.935]  statusMessage: u'cluster_api_version not found.'
W0216 12:22:45.935]  targetLink: u'https://test-container.sandbox.googleapis.com/v1/projects/943316867058/zones/us-central1-f/clusters/e2e-gke-agent-pr-50-0'
W0216 12:22:45.935]  zone: u'us-central1-f'>] finished with error: cluster_api_version not found.
```

**Comment by chuckbutler** [comment]
This looks fine to me based on the interactions with the hack script for validation of flag underscores (man that legacy thing kinda irks me). Thanks for fixing this up @mbruzek 

/approve

**Comment by mbruzek** [comment]
I don't know how or why this change could fail the etcd3 tests. 

@k8s-bot gce etcd3 e2e test this

**Comment by mbruzek** [comment]
@nikhiljindal Is it possible to take a look at this before the code freeze?

**Comment by soltysh** [comment]
@k8s-bot gci gke e2e test this

**Comment by soltysh** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by soltysh** [comment]
Generally this is ok.

/lgtm

**Comment by mbruzek** [comment]
@k8s-bot unit test this

**Comment by chuckbutler** [comment]
Is this on its way to the submit queue? or are we still blocked? The test overview looks fine to me. all 16 checks have passed but it's at risk of going over the X hour check where it will expire and need re-testing.

**Pull request merged**
