### PR TITLE
Move ControllerConfiguration out of componentconfig

### LINKED ISSUE #57618: Move `KubeControllerManagerConfiguration` to `pkg/controller/apis/`
The `KubeControllerManagerConfiguration` that is now located in `pkg/apis/componentconfig` should be moved out to `pkg/controller/apis/kubecontrollermanagerconfig` instead

Relevant issues/PRs:
 - https://github.com/kubernetes/kubernetes/issues/53577
 - https://github.com/kubernetes/kubernetes/pull/54211
 - https://github.com/kubernetes/kubernetes/pull/53645
 - https://github.com/kubernetes/kubernetes/pull/55234
 - https://github.com/kubernetes/kubernetes/pull/49051
 - https://github.com/kubernetes/kubernetes/issues/52428
 - https://github.com/kubernetes/kubernetes/pull/52562

@xiangpengzhao has showed interest in helping with this. There is more work to be done that moving indeed, but moving to its own API group/directory is a good first step on our way to beta and beyond for ComponentConfig for the k-c-m. I think @cheftako might be able to help with this at some point in the future as well, maybe with cleaning up the API types/adding structure/etc when prepping for beta (i.e. https://github.com/kubernetes/kubernetes/issues/52428)

We're hoping to get this usable in at least alpha for v1.10

cc @kubernetes/sig-api-machinery-feature-requests @kubernetes/sig-cluster-lifecycle-feature-requests @kubernetes/sig-architecture-feature-requests

### PR DESCRIPTION
**Pull request by guangxuli**
**What this PR does / why we need it**:
per  https://github.com/kubernetes/kubernetes/issues/57618 and https://github.com/kubernetes/kubernetes/issues/53577

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
fix https://github.com/kubernetes/kubernetes/issues/57618 

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by guangxuli** [comment]
after #54211 all test happy, so this PR is done by my convenience.
@madhuri-rai07 feel free to contact me if you are closed to finish your work discussed in  #57618, if yes, i wil close this. Don't worry, it took me a little time to do this.

**Comment by luxas** [comment]
cc @kubernetes/sig-architecture-api-reviews @kubernetes/api-reviewers @kubernetes/sig-cluster-lifecycle-pr-reviews @kubernetes/sig-api-machinery-pr-reviews @cheftako @jagosan @wlan0

**Comment by jamiehannaford** [comment]
looks good. seeing these test failures:

```
W0120 05:37:28.718] cmd/kube-controller-manager/app/plugins.go:89:36: undefined: componentconfig.VolumeConfiguration
W0120 05:37:28.722] cmd/kube-controller-manager/app/plugins.go:94:42: undefined: componentconfig.VolumeConfiguration
W0120 05:37:28.722] cmd/kube-controller-manager/app/plugins.go:118:73: undefined: componentconfig.VolumeConfiguration
```

so will need to edit those imports too.

**Comment by guangxuli** [comment]
@jamiehannaford  yes, correct, will do.

**Comment by bgrant0607** [comment]
Was this in use by anyone?

Also, there needs to be a release note.

**Comment by errordeveloper** [comment]
I've been hearing the kops issue is affecting a lot of folks, maybe we need to wait until it's fixed, or try again in hope it's a flake.

/test pull-kubernetes-e2e-kops-aws

**Review by jamiehannaford — APPROVED** [review]

**Comment by guangxuli** [comment]
thanks @jamiehannaford @luxas @errordeveloper .
This PR is ready to review, so ping our folks.

**Comment by sttts** [comment]
/hold 

For https://github.com/kubernetes/kubernetes/pull/59582. Please rebase onto that.

**Comment by jberkus** [comment]
@guangxuli please rebase so that this is mergeable.

Note that this PR now needs status/approved-for-milestone to merge.  Thanks!

**Comment by guangxuli** [comment]
@jberkus will rebase today.

**Comment by guangxuli** [comment]
@jberkus ptal.

**Comment by sttts** [comment]
This is a kube-controller-manager only type for configuration. It belongs into cmd/kube-controller-manager/apis or something like that. Let's not move anything into pkg/.

**Comment by guangxuli** [comment]
@sttts Hmm, though pkg is specific controller exist, should we not keep consistent with other components? Just like scheduler,kube-proxy and seems that no component placed configuration into cmd/*. 
ping @luxas

**Comment by sttts** [comment]
> Hmm, though pkg is specific controller exist, should we not keep consistent with other components?

We have the plumbing completely in cmd/ for the controller managers. So code wise that location is natural. That's very probably different for the proxy and kubelet.

In general, we should think twice (or more) before moving anything back into pkg/. Everything outside of pkg/ suggests a layered code architecture. With pkg/ our experience has always been that everything turns into a big spaghetti eventually, with a lot of efforts to detangle that again.

**Comment by sttts** [comment]
If it is about consistency, we should rather move the proxy and kubelet config apis out of pkg/ IMO.

**Comment by xiangpengzhao** [comment]
@kubernetes/sig-cluster-lifecycle-pr-reviews @kubernetes/sig-api-machinery-pr-reviews @luxas @mtaufen @ncdc WDYT about @sttts 's concern?

**Comment by sttts** [comment]
This should wait at least until https://github.com/kubernetes/kubernetes/pull/60270 has landed.

**Comment by luxas** [comment]
@kubernetes/sig-api-machinery-pr-reviews @mtaufen can we execute on moving this to e.g. `k8s.io/componentconfig` in v1.12 please?

**Comment by sttts** [comment]
> can we execute on moving this to e.g. k8s.io/componentconfig in v1.12 please?

+1. 

I think we all agree that we have to move the external types to a published repository. Both k8s.io/api and k8s.io/componentconfig sound fine to me, preferring the later.

@kubernetes/sig-api-machinery-api-reviews @deads2k @lavalamp @mtaufen opinions?

**Comment by luxas** [comment]
This has been fixed in v1.12 already with KEP https://github.com/kubernetes/community/pull/2354

**Pull request closed without merging**
