### PR TITLE
Automated cherry pick of #66676: Bump Heapster to v1.5.4

### PR DESCRIPTION
**Pull request by kawych**
Cherry pick of #66676 on release-1.11.

#66676: Bump Heapster to v1.5.4

### CODE REVIEW

**Comment by loburm** [comment]
/approve
@foxish could you take a look?

**Comment by loburm** [comment]
@foxish Could you approve it? This resolves critical bug in GCE/GKE environments (broken monitoring pipeline).

**Comment by kawych** [comment]
Closing in favor of #67078

**Pull request closed without merging**
