### PR TITLE
CRI: Add oom score adj in new CRI implementation.

### PR DESCRIPTION
**Pull request by Random-Liu**
Part of #29478.

This PR adds oom score adj in new CRI implementation and dockershim.

I run [oom score node e2e test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/container_manager_test.go#L77) with new CRI implementation myself, and all tests passed.

@yujuhong @feiskyer

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33443)

### CODE REVIEW

**Comment by feiskyer** [comment]
LGTM

**Comment by Random-Liu** [comment]
@feiskyer There is an unit test panic, will fix soon.

**Comment by Random-Liu** [comment]
Notice that the implementation in this PR only supports docker >= 1.11, which is what we target for CRI.
If we want to support docker <= 1.10, we need to [apply oom score adj ourselves](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/docker_manager.go#L1608-L1634) in dockershim.

**Comment by yujuhong** [comment]
> Notice that the implementation in this PR only supports docker >= 1.11, which is what we target for CRI.
> If we want to support docker <= 1.10, we need to apply oom score adj ourselves in dockershim.
Could you add a TODO in dockershim for that? Thanks!

---

Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/kubelet/dockershim/docker_sandbox.go, line 266 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33443#-KSbMfoQx-ZZdflfn3na:-KSbMfoQx-ZZdflfn3nb:b-lc1y2c) ([raw file](https://github.com/kubernetes/kubernetes/blob/17942adbabbb7a811b9ca4c715f3f57a5ee0a20d/pkg/kubelet/dockershim/docker_sandbox.go#L266)):*
> ```Go
> 		// Use docker's default cpu quota/period.
> 	}
> 	hc.OomScoreAdj = qos.PodInfraOOMAdj
> ```

Importing kubelet's internal package may not make sense in the future. I think we may be forced to define this in dockershim, or pass this via CRI (if necessary). Could you add a  TODO here stating that we should get rid of the dependency?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33443#-:-KSbMwJ5KPOfuWNaRRuU:b-su33e5)*

**Comment by yujuhong** [comment]
Some nits for comments. The rest looks good. 

---







*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33443#-:-KSbN3QnAlKOeyz1l6UO:blk004c)*

**Comment by Random-Liu** [comment]
*[pkg/kubelet/dockershim/docker_sandbox.go, line 266 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33443#-KSbMfoQx-ZZdflfn3na:-KSbX95_t3UM5fqLXIhO:br8g79p) ([raw file](https://github.com/kubernetes/kubernetes/blob/17942adbabbb7a811b9ca4c715f3f57a5ee0a20d/pkg/kubelet/dockershim/docker_sandbox.go#L266)):*
<details><summary><i>Previously, yujuhong (Yu-Ju Hong) wrote…</i></summary>
> Importing kubelet's internal package may not make sense in the future. I think we may be forced to define this in dockershim, or pass this via CRI (if necessary). Could you add a  TODO here stating that we should get rid of the dependency?
</details>
Yeah, I change this because I found that the default value set here was `-999`, which was different from the right default `-998`. I'll add a TODO here. Thanks!

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33443)*

**Comment by Random-Liu** [comment]
*[pkg/kubelet/dockershim/docker_sandbox.go, line 266 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33443#-KSbMfoQx-ZZdflfn3na:-KSbYBGSX1IwAJ3xQVOZ:b8wiluf) ([raw file](https://github.com/kubernetes/kubernetes/blob/17942adbabbb7a811b9ca4c715f3f57a5ee0a20d/pkg/kubelet/dockershim/docker_sandbox.go#L266)):*
<details><summary><i>Previously, Random-Liu (Lantao Liu) wrote…</i></summary>
> Yeah, I change this because I found that the default value set here was `-999`, which was different from the right default `-998`. I'll add a TODO here. Thanks!
</details>
BTW, why it doesn't make sense to import kubelet internal package?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33443)*

**Comment by yujuhong** [comment]
*[pkg/kubelet/dockershim/docker_sandbox.go, line 266 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33443#-KSbMfoQx-ZZdflfn3na:-KSb_HBlrDx-TvQ6AD-a:bqyvdd3) ([raw file](https://github.com/kubernetes/kubernetes/blob/17942adbabbb7a811b9ca4c715f3f57a5ee0a20d/pkg/kubelet/dockershim/docker_sandbox.go#L266)):*
<details><summary><i>Previously, Random-Liu (Lantao Liu) wrote…</i></summary>
> BTW, why it doesn't make sense to import kubelet internal package?
</details>
If we move dockershim to a separate repository....most likely we don't want it importing internal kubelet packages (other than the API) and cause more complicated dependencies. Another thing is that "PodInfraOOMAdj" sounds very docker specific anyway. If we really need to adjust the oom score of the sandbox, maybe we should pass it via CRI. However, sandbox can be just a namespace without a process, so this may be weird? Maybe we should make sure the oom score is the minimum of the oom scores of the containers in it.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33443)*

**Comment by Random-Liu** [comment]
*[pkg/kubelet/dockershim/docker_sandbox.go, line 266 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33443#-KSbMfoQx-ZZdflfn3na:-KSbjwtNQH-86nfjk3jX:b-krv4no) ([raw file](https://github.com/kubernetes/kubernetes/blob/17942adbabbb7a811b9ca4c715f3f57a5ee0a20d/pkg/kubelet/dockershim/docker_sandbox.go#L266)):*
<details><summary><i>Previously, yujuhong (Yu-Ju Hong) wrote…</i></summary>
> If we move dockershim to a separate repository....most likely we don't want it importing internal kubelet packages (other than the API) and cause more complicated dependencies. Another thing is that "PodInfraOOMAdj" sounds very docker specific anyway. If we really need to adjust the oom score of the sandbox, maybe we should pass it via CRI. However, sandbox can be just a namespace without a process, so this may be weird? Maybe we should make sure the oom score is the minimum of the oom scores of the containers in it.
</details>
Hm. Totally make sense. I'll add TODO here.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33443)*

**Comment by Random-Liu** [comment]
@yujuhong Addressed comments.

**Pull request merged**
