### PR TITLE
Switch from gazel to kazel

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: switches to `kazel`, where all new development will be focused. Part of the effort for switching from `gazel` to `gazelle`.

I'm imagining that we'll use `kube::util::go_install_from_commit` to version `gazelle` as well.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: x-ref #47558

**Release note**:

```release-note
NONE
```

/release-note-none
/assign @mikedanese @spxtr

### CODE REVIEW

**Comment by mikedanese** [comment]
@ixdy move .kazelcfg.json to /build/root and symlink it.

**Comment by ixdy** [comment]
@mikedanese is there a reason we didn't put `.gazelcfg` in the `build/root` dir like everything else?

**Comment by mikedanese** [comment]
I think we just missed it.

**Comment by ixdy** [comment]
ok, moved and symlinked. PTAL.

(and I need to track down a top-level OWNER again.)

**Comment by mikedanese** [comment]
For top level approval (just moving .kazecfg.json to build/):
/assign @thockin

**Comment by m1093782566** [comment]
Hi all,

In mac OS, I find update-bazel failed.

```
$ ./hack/update-bazel.sh 
./hack/update-bazel.sh: line 29: kazel: command not found
!!! Error in ./hack/update-bazel.sh:29
  Error in ./hack/update-bazel.sh:29. 'kazel -root="$(kube::realpath ${KUBE_ROOT})"' exited with status 127
Call stack:
  1: ./hack/update-bazel.sh:29 main(...)
Exiting with status 1
```

How should I get the kazel?

**Comment by ixdy** [comment]
@m1093782566 `hack/update-bazel.sh` should be building `kazel` for you, and I'm unable to reproduce this failure on my Mac OS machine.

Can you edit `hack/update-bazel.sh` to add `set -x` and then include the output?

Also, what version of go are you using? What is your `GOPATH` set to?

**Comment by ixdy** [comment]
And what shell are you using?

**Comment by m1093782566** [comment]
I assume it's network issue - I am from china and sometimes unable to visit google servers. Thanks!

**Comment by ixdy** [comment]
@m1093782566 maybe, though I would've expected [this `go get`](https://github.com/kubernetes/kubernetes/blob/fe8f6a15990be1003dbe38c8ad7a4b40973c669b/hack/lib/util.sh#L523) to fail in that case.

**Pull request merged**
