### PR TITLE
kubelet: Fix log typo when killing a container

### PR DESCRIPTION
**Pull request by rata**
Signed-off-by: Rodrigo Campos <rodrigo@kinvolk.io>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
/kind cleanup
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: Fixes a typo in the logs when killing a container.

**Which issue(s) this PR fixes**: None

**Special notes for your reviewer**: None

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]

**Comment by rata** [comment]
@SergeyKanzhelev thanks! I think you need to issue the /lgtm command so the bot adds the lgtm label and the /assign @yujuhong to assign to the approved the bot mentioned in the previous message.

Thanks!

**Comment by dashpole** [comment]
"using 10 seconds grace period override" sounds strange when I say it...
how about "using a %d second grace period override"

**Comment by rata** [comment]
>  how about "using a %d second grace period override"

I guess you meant seconds (with final s)? I'm fine, both sound good in my mind. I can change it to that, if you prefer :)

**Comment by dashpole** [comment]
I meant without the s.  "A ten second delay" sounds correct.  "A ten seconds delay" sounds odd to me.

**Comment by rata** [comment]
@dashpole thanks! Pushed with that change. PTAL :)

**Comment by rata** [comment]
/retest

Those failures are totally unrelated. If this retest doesn't work, will try to wait a little to see if a fix is merged (if it's not a flaky test)

**Pull request merged**
