### PR TITLE
Migrated `pkg/scheduler/framework/plugins/interpodaffinity` to contextual logging

### PR DESCRIPTION
**Pull request by mengjiao-liu**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Migrated `pkg/scheduler/framework/plugins/interpodaffinity` to contextual logging

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/kubernetes/issues/91633#issuecomment-1467645065

#### Special notes for your reviewer:

- [x] The log inside the `GetNamespaceLabelsSnapshot` function in file `pkg/scheduler/framework/plugins/interpodaffinity/plugin.go` is not updated because this function is called by the AssignedPodUpdated function in the file pkg/scheduler/internal/queue/scheduling_queue.go
The `AssignedPodUpdated` function involves `SchedulingQueue` interface changes, so the GetNamespaceLabelsSnapshot function will not be updated for the time being.
The alternative is that we wait for #116849  to merge first.

#116849 has been merged and the PR has updated and to be reviewed.

#### Does this PR introduce a user-facing change?

```release-note
Migrated the interpodaffinity scheduler plugin to use [contextual logging](https://k8s.io/docs/concepts/cluster-administration/system-logs/#contextual-logging).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/3077-contextual-logging
```

/sig instrumentation
/wg structured-logging
/area logging
/sig scheduling

### CODE REVIEW

**Comment by kerthcet** [comment]
I suppose this pr still valid?

**Comment by mengjiao-liu** [comment]
> I suppose this pr still valid?

Thanks for the reminder. I was busy with other things recently.

I have update the PR.

**Review by SataQiu — COMMENTED** [review]
thanks
/lgtm

**Review by kerthcet — COMMENTED** [review]
/lgtm
/approve
/remove-kind feature
/kind cleanup

Thanks!

**Pull request merged**
