### PR TITLE
Automated cherry pick of #109840: kubeadm: only taint CP nodes when the legacy "master" taint

### PR DESCRIPTION
**Pull request by neolit123**
Cherry pick of #109840 on release-1.24.

#109840: kubeadm: only taint CP nodes when the legacy "master" taint

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
kubeadm: only taint control plane nodes when the legacy "master" taint is present. This avoids a bug where "kubeadm upgrade" will re-taint a control plane node with the new "control plane" taint even if the user explicitly untainted the node.
```

### CODE REVIEW

**Comment by cpanato** [comment]
@neolit123 this is only needed for 1.24? don't we backport this to 1.23/22/21?

**Comment by neolit123** [comment]
1.24 only. The function that we are patching was added in 1.24.

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
