### PR TITLE
Enable supervisord on all cloud providers and removed monit.

### PR DESCRIPTION
**Pull request by dchen1107**
https://github.com/kubernetes/kubernetes/issues/15175#issuecomment-153424022

cc/ @brendandburns

### CODE REVIEW

**Comment by zmerlynn** [comment]
LGTM

**Comment by brendandburns** [comment]
Merging early to facilitate a cherry-pick

**Comment by roberthbailey** [comment]
There is some lingering documentation that should be updated to reflect the monit -> supervisord switch as well:

* https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/salt/README.md
* https://github.com/kubernetes/kubernetes/blob/master/docs/admin/high-availability.md
* https://github.com/kubernetes/kubernetes/blob/a1e3a1c39a2a95b7617fa0f9180aaf28a628b72c/docs/admin/cluster-components.md#monit
* https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/scratch.md

As well as a few comments in the code.

**Comment by roberthbailey** [comment]
https://github.com/kubernetes/kubernetes/pull/16761 updates 3 of the 4 places in the documentation that reference monit and I filed https://github.com/kubernetes/kubernetes/issues/16762 to update the HA docs.

**Pull request merged**
