### PR TITLE
Automated cherry pick of #100680: test/e2e: fix the OIDC discovery test with ECDSA service

### PR DESCRIPTION
**Pull request by smira**
Cherry pick of #100680 on release-1.21.

#100680: test/e2e: fix the OIDC discovery test with ECDSA service

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by dims** [comment]
cc @kubernetes/release-managers @kubernetes/release-team-leads 

Dear release team,
Please add the milestone `v1.21` tag to this PR

**Comment by dims** [comment]
@BenTheElder interesting :) they told me to ask for approval before mileston-ing anything as `v1.21`

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
(btw, for future, cherry picks get automatically milestoned upon merge via `milestone_applier`)

**Comment by BenTheElder** [comment]
It's getting milestoned by the bot upon PR _open_. If we intend for it to only be after merge then something is misconfigured | misbehaving. (I feel like previously it was in fact only after merge...?)

**Comment by liggitt** [comment]
PRs to a release branch get the milestone on open.

**Pull request merged**
