### PR TITLE
exported function StartControllers should have comment

### PR DESCRIPTION
**Pull request by StudyNick**
**What this PR does / why we need it**:
exported function StartControllers should have comment

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by StudyNick** [comment]
I signed it!

**Comment by StudyNick** [comment]
@lavalamp please deal with it

**Comment by StudyNick** [comment]
@lavalamp execuse me, please deal it

**Comment by lavalamp** [comment]
I feel like I already commented on this in another PR, is it possible you sent two PRs for this? Sorry for delay, I have a long backlog from being OOO (out of office). (PS, I suspect you're not a native english speaker, so let me add: "please deal with it" is probably not a great way to ask for attention, I suggest "can you take a look")

**Pull request closed without merging**
