### PR TITLE
Migrated pkg/controller/statefulset to contextual logging

### PR DESCRIPTION
**Pull request by my-git9**
#### Which issue(s) this PR fixes:

Ref https://github.com/kubernetes/enhancements/issues/3077

#### Does this PR introduce a user-facing change?

```release-note
Migrate `pkg/controller/statefulset` to contextual logging
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/3077-contextual-logging
```

### CODE REVIEW

**Comment by pohly** [comment]
Please coordinate on #wg-structured-logging before submitting such PRs. Someone else already started working on this.

**Comment by pohly** [comment]
Please coordinate on #wg-structured-logging before submitting such PRs. Someone else already started working on this.

**Comment by my-git9** [comment]
> Please coordinate on #wg-structured-logging before submitting such PRs. Someone else already started working on this.

It's such a shame, I could have claimed these quests earlier😂

**Pull request closed without merging**
