### PR TITLE
fix comment

### PR DESCRIPTION
**Pull request by x1957**
**What this PR does / why we need it**:
fix method name in comment

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm

**Comment by cblecker** [comment]
/retest
/assign @thockin 
for approval

**Review by oomichi — APPROVED** [review]

**Pull request merged**
