### PR TITLE
If the image with :latest tag specified in spec, pull even PullIfNotPresent is set.

### PR DESCRIPTION
**Pull request by dchen1107**

### CODE REVIEW

**Comment by smarterclayton** [comment]
As a note, this change really burns us when trying to test in local environments.  I'm really in favor of yanking this - I don't think latest should override pullIfNotPresent

**Comment by brendandburns** [comment]
It should only have overridden the default if no explicit value was
present.  If there is an explicit value present, we shouldn't overwrite,
regardless of the image spec.

--brendan

**Comment by brendandburns** [comment]
to be clear: this is a bug if it's not the case.

**Comment by dchen1107** [comment]
@brendanburns What you described here is exact opposite of what we implemented here. When the user asks for latest of image with PullIfNotPresent (which is default policy), we treat it as Always. It is our policy choice, not a bug. But it is arguable if it is a good policy or not.

@smarterclayton I am ok to remove this, but before we do it, can I understand your use case more?

**Comment by smarterclayton** [comment]
Our use case is doing test and development on Kubernetes (and things that run on Kubernetes that run in containers) is that we simultaneously want to expose our images as Docker Hub images ("openshift/docker-registry") but test them locally against non-master.  We can mutate our references to not be latest, but latest isn't any more special than any other tag.

If the user says "pullIfNotPresent" and we "pullAlways", that sounds like a bug (a user certainly wouldn't expect it).  Otherwise, we shouldn't allow someone to specify pullIfNotPresent.  And forcing users who want that behavior to use different tag names is a bad idea, because now we're enforcing a certain pattern on how users use tags in repositories they don't control.

----- Original Message -----

**Comment by brendandburns** [comment]
To be clear, I wanted to identify the cases:

In this container, Pull Policy is set to "PullAlways"
{
...
  "image": "foo:latest"
  // No image pull policy specified
...
}


In these containers, Pull Policy is unchanged
{
...
  "image": "foo"
  // No Image pull policy specified
...
}

{
...
  "image": "foo:some-other-version"
  // No Image pull policy specified
...
}

{
...
  "imagePullPolicy": "<anything>"
...
}

Hope that helps.
--brendan

**Comment by smarterclayton** [comment]
----- Original Message -----
> To be clear, I wanted to identify the cases:
> 
> In this container, Pull Policy is set to "PullAlways"
> {
> ...
>   "image": "foo:latest"
>   // No image pull policy specified
> ...
> }
> 
> 
> In these containers, Pull Policy is unchanged
> {
> ...
>   "image": "foo"
>   // No Image pull policy specified
> ...
> }
> 
> {
> ...
>   "image": "foo:some-other-version"
>   // No Image pull policy specified
> ...
> }
> 
> {
> ...
>   "imagePullPolicy": "<anything>"
> ...
> }

Right - this is the case which today is "broken" - in that the value the REST object contains (pullIfPresent) is ignored and the pull policy is converted to pull always when doesn't contain a tag.

**Comment by dchen1107** [comment]
Yes, the latest use case is broken on purpose to mitigate #2360 and continue supporting ContainerVM users. If I remembered correctly, PullPolicy's default setting implementation is different from other default setting, and we were not convergent on which way is the right way. Meanwhile, the current approach of PullPolicy cannot have image_name:tag easily. I think now we are convergent on how to setting defaults, and kubelet start to have validation too. Will send PR to fix the issue.

**Comment by dchen1107** [comment]
@brendandburns @smarterclayton @thockin 

I were wrong. #2587 is not merged yet and we are not convergent on how to set defaults here.

**Comment by bgrant0607** [comment]
#2587 hasn't been merged yet, but I think we have converged on the approach we want to take. We just need something to push it to completion.

**Pull request merged**
