### PR TITLE
Add SidecarContainers feature beta version

### PR DESCRIPTION
**Pull request by Rei1010**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Add SidecarContainers feature beta version info.
The feature is promoted to beta in #121579

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/753-sidecar-containers
```

### CODE REVIEW

**Comment by Rei1010** [comment]
@gjkim42 ptal

**Comment by gjkim42** [comment]
/ok-to-test
/lgtm
/sig node

thanks for catching the missing part...

**Pull request merged**
