### PR TITLE
Add assert to component base cli and config

### PR DESCRIPTION
**Pull request by conwaychriscosmo**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
/kind cleanup

**What this PR does / why we need it**:
Refactors tests in the component base repo to use assert and be more readable.  Not required, but nice to have.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by conwaychriscosmo** [comment]
@logicalhan @mtaufen

**Comment by stewart-yu** [comment]
should we change all test case using `assert`?

**Pull request closed without merging**
