### PR TITLE
Automated cherry pick of #73770: support multiple cidr vpc for nlb health check

### PR DESCRIPTION
**Pull request by M00nF1sh**
Cherry pick of #73770 on release-1.11.

#73770: support multiple cidr vpc for nlb health check

```release-note
[AWS]support multiple cidr vpc for nlb health check
```

### CODE REVIEW

**Comment by M00nF1sh** [comment]
/assign @jsafrane 
Hi Jan, would you aprove these cherry-pick PRs?(v1.11, v1.12, v1.13). Micha is not approvers in these branches 😄

**Comment by foxish** [comment]
Please add a release note @M00nF1sh

**Comment by M00nF1sh** [comment]
@foxish Thanks for the reminder, Just did 😄

**Comment by anarchistHH1983** [comment]
Ready

**Pull request merged**
