### PR TITLE
build: update to klog v2.80.1

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The fix for https://github.com/kubernetes/klog/issues/348 is required before https://github.com/kubernetes/kubernetes/pull/111998 can be merged because the way how a unit test in that PR uses klog triggers the data race.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm

/assign @liggitt @thockin 
(for root OWNERS approval)

**Comment by pohly** [comment]
/retest

pull-kubernetes-unit:
```
=== FAIL: vendor/k8s.io/legacy-cloud-providers/azure TestFindSANameForDisk (unknown)
panic: test timed out after 3m0s 
```

**Comment by pohly** [comment]
/retest

Looks like unit tests are running into the job timeout, also in other PRs.

**Pull request merged**
