### PR TITLE
make list support field selector

### LINKED ISSUE #107809: Fake client list watch support field selector
### What would you like to be added?

```
func (c *FakeEndpoints) List(ctx context.Context, opts v1.ListOptions) (result *corev1.EndpointsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(endpointsResource, endpointsKind, c.ns, opts), &corev1.EndpointsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &corev1.EndpointsList{ListMeta: obj.(*corev1.EndpointsList).ListMeta}
	for _, item := range obj.(*corev1.EndpointsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}
```

As can be seen above, only label selector is supported

### Why is this needed?

We need it to write tests

### PR DESCRIPTION
**Pull request by calvin0327**
#### What type of PR is this?

/kind feature

#### Which issue(s) this PR fixes:

Fixes #107809

#### Does this PR introduce a user-facing change?

```release-note
fakeclient list now support field selector
```

### CODE REVIEW

**Comment by jonyhy96** [comment]
only support name and namespace filter is not enough, pod will use spec.nodeName as filter field

**Comment by jonyhy96** [comment]
@deads2k the unit test failed because of this pr doesn't support field filter other than name and namespace. e.g spec.nodeName. Do u have any better solution for this? FYI, each of those package has it's own GetAttrs func to get suitable `fields.Set`.

**Comment by hzxuzhonghu** [comment]
@liggitt Might be interested

**Comment by liggitt** [comment]
I'm not sure partial/inconsistent support for field selectors is better than no support, and full support requires replicating the server side implementation into client-go, which also seems questionable

**Comment by ritazh** [comment]
/remove-sig auth
Feel free to add us back if needed.

**Pull request closed without merging**
