### PR TITLE
Added oomkill test for init container and fix typos

### PR DESCRIPTION
**Pull request by CoderSherlock**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Added oomkill test to guarantee the the exit code and reason are correct if the init container is oomkilled.

#### Which issue(s) this PR fixes:
N/A

#### Does this PR introduce a user-facing change?
No

### CODE REVIEW

**Comment by CoderSherlock** [comment]
@bobbypage

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

let's wait for branch to open for 1.29

**Pull request merged**
