### PR TITLE
Fix an unnecessary failure during kube-up during bucket ACL setting and make bucket in the configured project

### PR DESCRIPTION
**Pull request by michaelmdresser**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixes 2 small issues in the GCE cluster scripts. See https://github.com/kubernetes/cloud-provider-gcp/pull/155 and https://github.com/kubernetes/cloud-provider-gcp/pull/154 for details. It is the same code and it runs into the same problems.

**Which issue(s) this PR fixes**:

N/A

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by amwat** [comment]
/ok-to-test
/lgtm

/cc @BenTheElder 
for approval

**Comment by BenTheElder** [comment]
FYI @cheftako

**Comment by BenTheElder** [comment]
/lgtm
/approve
thanks!

**Pull request merged**
