### PR TITLE
Update vendor k8s.io/utils and remove internal utils

### PR DESCRIPTION
**Pull request by andrewsykim**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Updates `k8s.io/utils` to latest revision and replaces internal util packages with those in k8s.io/utils. Most notable changes from k8s.io/utils are:
* https://github.com/kubernetes/utils/pull/50
* https://github.com/kubernetes/utils/pull/52
* https://github.com/kubernetes/utils/pull/65
* https://github.com/kubernetes/utils/pull/66
* https://github.com/kubernetes/utils/pull/67

**Which issue(s) this PR fixes**:
As part of a larger initiative https://github.com/kubernetes/kubernetes/issues/69585

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/hold

@andrewsykim can you please refresh from `k8s.io/utils`? (added `integer`, `buffer` and `trace`)

cc @wojtek-t

**Comment by andrewsykim** [comment]
@dims would you like me to replace internal packages here too or do that in another PR?

**Comment by dims** [comment]
@andrewsykim since the PR title is `Update vendor k8s.io/utils and remove internal utils`, i'd say go for it :)

**Comment by dims** [comment]
/lgtm

ignore the local-e2e-containerized job

**Comment by wojtek-t** [comment]
Awesome - thanks!

@krzysied - with that in place, you can now do your changes to tracing.

**Pull request merged**
