### PR TITLE
Automated cherry pick of #27907

### PR DESCRIPTION
**Pull request by vishh**
Cherry pick of #27907 on release-1.3.

### CODE REVIEW

**Comment by vishh** [comment]
Fixes test failure #28683

**Comment by timstclair** [comment]
LGTM, but you need to resolve the release-note issue.

**Comment by fabioy** [comment]
@vishh Please rebase this. Thanks.

**Comment by vishh** [comment]
@timstclair @fabioy release note is not relevant for this PR. it fixes the build.

**Pull request merged**
