### PR TITLE
Update etcd* version to use latest released images.

### PR DESCRIPTION
**Pull request by yuwenma**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

 /kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
We have released new image versions for 1.) etcd, 2.) etcd-version-monitor and 3.)etcd-empty-dir-cleanup. The main change is that those images are rebased from busybox/alpine to distroless/debian-base. This PR bumps the etcd* image versions to use the latest one.

Tests include: 
1. Build etcd, etcd-version-monitor and etcd-empty-dir-cleanup locally to make sure the container can run successfully.
2. Bring up a gke cluster using the updated etcd and etcd-empty-dir-cleanup manifests to make sure the manifest change is correct.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wenjiaswe** [comment]
I checked on gcr.io/google-containers that you have the needed image there already: [etcd 3.3.10-1](https://pantheon.corp.google.com/gcr/images/google-containers/GLOBAL/etcd@sha256:02cd751eef4f7dcea7986e58d51903dab39baf4606f636b50891f30190abce2c/details?tab=info), [etcd-empty-dir-cleanup 3.3.10-1](https://pantheon.corp.google.com/gcr/images/google-containers/GLOBAL/etcd-empty-dir-cleanup@sha256:13e18f320022be5cf7c1c38a6207d02c07d603b52c1dd47b7c69e9324bd3c641/details?tab=info), [etcd-version-monitor 0.1.3](https://pantheon.corp.google.com/gcr/images/google-containers/GLOBAL/etcd-version-monitor@sha256:cef5e88f544fe985fe11e1cc463b5416b18b1a218e5a58f0b3ed806b41418e6d/details?tab=info). 

I saw that there are also some tests using etcd version, like https://github.com/kubernetes/kubernetes/blob/07e3b7cdcac30c513d40f5d16f43bc4d2f869f67/test/e2e/framework/nodes_util.go#L63, https://github.com/kubernetes/kubernetes/blob/master/test/kubemark/start-kubemark.sh#L67, maybe some other places. Could you check if you need to change those as well?

**Comment by neolit123** [comment]
hi @yuwenma 
> The main change is that those images are rebased from busybox/alpine to distroless/debian-base

by moving to distroless would the official GCR images still include etcdctl?
@kubernetes/sig-cluster-lifecycle

**Comment by yuwenma** [comment]
> hi @yuwenma
> 
> > The main change is that those images are rebased from busybox/alpine to distroless/debian-base
> 
> by moving to distroless would the official GCR images still include etcdctl?

Right now, the official etcd image is based on debian-base and it still includes etcdctl. We are currently discussing the change on etcd-io side, but I think it would take some time to allow the kubernetes-etcd to base on distroless. 

> @kubernetes/sig-cluster-lifecycle
> 
> EDIT: actually i still see this image to be busybox based and has etcdctl:
> https://github.com/kubernetes/kubernetes/blob/8993fbc543c18e73668793b5d5e234c0a136735c/cluster/images/etcd/Dockerfile#L18
> 
> https://github.com/kubernetes/kubernetes/blob/8993fbc543c18e73668793b5d5e234c0a136735c/cluster/images/etcd/Makefile#L60

The code you looked at seems to be based on an old version, the master HEAD has been updated to use [debian-base](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/etcd/Makefile#L59).

**Comment by yuwenma** [comment]
> I checked on gcr.io/google-containers that you have the needed image there already: [etcd 3.3.10-1](https://pantheon.corp.google.com/gcr/images/google-containers/GLOBAL/etcd@sha256:02cd751eef4f7dcea7986e58d51903dab39baf4606f636b50891f30190abce2c/details?tab=info), [etcd-empty-dir-cleanup 3.3.10-1](https://pantheon.corp.google.com/gcr/images/google-containers/GLOBAL/etcd-empty-dir-cleanup@sha256:13e18f320022be5cf7c1c38a6207d02c07d603b52c1dd47b7c69e9324bd3c641/details?tab=info), [etcd-version-monitor 0.1.3](https://pantheon.corp.google.com/gcr/images/google-containers/GLOBAL/etcd-version-monitor@sha256:cef5e88f544fe985fe11e1cc463b5416b18b1a218e5a58f0b3ed806b41418e6d/details?tab=info).

Right, I followed the GCE internal approach to update the gcr etcd images. And that has been completed.
> 
> I saw that there are also some tests using etcd version, like
> 
> https://github.com/kubernetes/kubernetes/blob/07e3b7cdcac30c513d40f5d16f43bc4d2f869f67/test/e2e/framework/nodes_util.go#L63
> 
> , [/test/kubemark/start-kubemark.sh@`master`#L67](https://github.com/kubernetes/kubernetes/blob/master/test/kubemark/start-kubemark.sh#L67) [](/kubernetes/kubernetes/blob/HEAD@{2019-05-10T17:59:47Z}/test/kubemark/start-kubemark.sh#L67), maybe some other places. Could you check if you need to change those as well?

Sure, I can update the test reference. Just to confirm, we want the test using the "latest" etcd version (rather than a stable one), right?

**Comment by neolit123** [comment]
> Right now, the official etcd image is based on debian-base and it still includes etcdctl. We are currently discussing the change on etcd-io side, but I think it would take some time to allow the kubernetes-etcd to base on distroless.

> The link to the code is sha1 8993fbc. The master HEAD has been updated to use debian-base.

thanks for details!
there were some comments that by moving to distroless the main etcd image will no longer include etcdctl, so this will break kubeadm, possibly other tools too.

if this is a pending change, ideally it should be announced on kubernetes-dev so that the depending projects can adapt ahead of time.

**Comment by yuwenma** [comment]
> > Right now, the official etcd image is based on debian-base and it still includes etcdctl. We are currently discussing the change on etcd-io side, but I think it would take some time to allow the kubernetes-etcd to base on distroless.
> 
> > The link to the code is sha1 [8993fbc](https://github.com/kubernetes/kubernetes/commit/8993fbc543c18e73668793b5d5e234c0a136735c). The master HEAD has been updated to use debian-base.
> 
> thanks for details!
> there were some comments that by moving to distroless the main etcd image will no longer include etcdctl, so this will break kubeadm, possibly other tools too.
Thanks so much for noticing this. Do you mind pointing me to the comments about the etcd specific discussions.

> 
> if this is a pending change, ideally it should be announced on kubernetes-dev so that the depending projects can adapt ahead of time.
Previously we sent several emails to different sigs about the whole effort of the rebasing changes ([KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/20190316-rebase-images-to-distroless.md)). And etcd is treated as the exception now (tracked [here](https://github.com/kubernetes/sig-release/blob/master/release-engineering/baseimage-exception-list.md) ). Please let me know if there's anything else we should be aware of. 

I think the etcdctl removal is definitely something we should pay very close attention to. Thanks again for pointing it out.

**Comment by neolit123** [comment]
> Thanks so much for noticing this. Do you mind pointing me to the comments about the etcd specific discussions.

i think it was during a sig-cluster-lifecycle meeting but i cannot recall when it was.

> Previously we sent several emails to different sigs about the whole effort of the rebasing changes (KEP). And etcd is treated as the exception now (tracked here ). Please let me know if there's anything else we should be aware of.

thanks for the links. i remembered the KEP now.
it would be great if you can give me an issue # that i can watch.

> I think the etcdctl removal is definitely something we should pay very close attention to. Thanks again for pointing it out.

much appreciated.

**Review by jpbetz — CHANGES_REQUESTED** [review]
`test/e2e/framework/nodes_util.go` and `test/kubemark/start-kubemark.sh` both have references to the etcd image (`TEST_ETCD_IMAGE` and `ETCD_IMAGE` respectively). Update these too?

**Comment by wenjiaswe** [comment]
> > I checked on gcr.io/google-containers that you have the needed image there already: [etcd 3.3.10-1](https://pantheon.corp.google.com/gcr/images/google-containers/GLOBAL/etcd@sha256:02cd751eef4f7dcea7986e58d51903dab39baf4606f636b50891f30190abce2c/details?tab=info), [etcd-empty-dir-cleanup 3.3.10-1](https://pantheon.corp.google.com/gcr/images/google-containers/GLOBAL/etcd-empty-dir-cleanup@sha256:13e18f320022be5cf7c1c38a6207d02c07d603b52c1dd47b7c69e9324bd3c641/details?tab=info), [etcd-version-monitor 0.1.3](https://pantheon.corp.google.com/gcr/images/google-containers/GLOBAL/etcd-version-monitor@sha256:cef5e88f544fe985fe11e1cc463b5416b18b1a218e5a58f0b3ed806b41418e6d/details?tab=info).
> 
> Right, I followed the GCE internal approach to update the gcr etcd images. And that has been completed.
> 
> > I saw that there are also some tests using etcd version, like
> > https://github.com/kubernetes/kubernetes/blob/07e3b7cdcac30c513d40f5d16f43bc4d2f869f67/test/e2e/framework/nodes_util.go#L63
> > 
> > , [/test/kubemark/start-kubemark.sh@`master`#L67](https://github.com/kubernetes/kubernetes/blob/master/test/kubemark/start-kubemark.sh#L67) , maybe some other places. Could you check if you need to change those as well?
> 
> Sure, I can update the test reference. Just to confirm, we want the test using the "latest" etcd version (rather than a stable one), right?

@yuwenma I think so. Since config script is updated to use the latest version then it should be tested: xref: #71615

**Comment by yuwenma** [comment]
PTAL. @wenjiaswe @jpbetz

**Comment by wenjiaswe** [comment]
Looks like there is one more place, just a comment, but you may as well change it in case it causes confusion: https://github.com/kubernetes/kubernetes/blob/8f23ad2c247c0218fbce275a2f0a890c665b1575/cluster/gce/config-test.sh#L178

**Comment by yuwenma** [comment]
> Looks like there is one more place, just a comment, but you may as well change it in case it causes confusion:
> 
> https://github.com/kubernetes/kubernetes/blob/8f23ad2c247c0218fbce275a2f0a890c665b1575/cluster/gce/config-test.sh#L178

Done. I found this piece, but thought it's only a comment in a test file. Updated.

**Pull request merged**
