### PR TITLE
Add dims as approver in build/ directory

### PR DESCRIPTION
**Pull request by dims**
Added as a reviewer here: https://github.com/kubernetes/kubernetes/pull/93821

Thanks!

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
/hold
for comment from other assignees

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Comment by dims** [comment]
/hold cancel

thanks!

**Pull request merged**
