### PR TITLE
rkt: Support subPath volume mounts feature

### LINKED ISSUE #26986: [k8s.io] hostPath should support subPath [Conformance] failed on rktnetes
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/host_path.go:121
Expected error:
    <*errors.errorString | 0xc820347400>: {
        s: "pod 'pod-host-path-test' terminated with failure: &{ExitCode:1 Signal:0 Reason:Error Message: StartedAt:{Time:2016-06-07 08:35:39 +0000 UTC} FinishedAt:{Time:2016-06-07 08:38:39 +0000 UTC} ContainerID:rkt://0bf1f80a-75df-42ff-92ef-703f979039b3:test-container-2}",
    }
    pod 'pod-host-path-test' terminated with failure: &{ExitCode:1 Signal:0 Reason:Error Message: StartedAt:{Time:2016-06-07 08:35:39 +0000 UTC} FinishedAt:{Time:2016-06-07 08:38:39 +0000 UTC} ContainerID:rkt://0bf1f80a-75df-42ff-92ef-703f979039b3:test-container-2}
not to have occurred
```

cc @kubernetes/sig-node @euank @tmrts

### PR DESCRIPTION
**Pull request by yifan-gu**
So that at most one volume object will be created for every unique
host path. Also the volume's name is random generated UUID to avoid
collision since the mount point's name passed by kubelet is not
guaranteed to be unique when 'subpath' is specified.

Should partially fix https://github.com/kubernetes/kubernetes/issues/26986 
The non-existing host path creation issue is not touched here.

cc @kubernetes/sig-rktnetes 
also cc @kubernetes/sig-node for the Mount name comments I added.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30934)

### CODE REVIEW

**Comment by euank** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/kubelet/rkt/rkt.go, line 2344 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30934#-KPVAttLcafrtxKWcMVZ:-KPVAttMktv8gxTkZWLg:baxr822) ([raw file](https://github.com/kubernetes/kubernetes/blob/a42f327321ca3ce20beaa6b0692fc02f7d856b5a/pkg/kubelet/rkt/rkt.go#L2344)):*
> ```Go
> 	}
> 
> 	var volumes []appctypes.Volume
> ```

Might as well make them the right length (either capacity or length) since we know exactly what it is

---

*[pkg/kubelet/rkt/rkt.go, line 2360 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30934#-KPV883krDPK1xGHuEnC:-KPV883lTIv0o1VgfCfB:beqfjw8) ([raw file](https://github.com/kubernetes/kubernetes/blob/a42f327321ca3ce20beaa6b0692fc02f7d856b5a/pkg/kubelet/rkt/rkt.go#L2360)):*
> ```Go
> // The container ports and host ports are mapped by PortMapping.Name.
> func makeContainerAndHostPorts(portMappings []kubecontainer.PortMapping) ([]appctypes.Port, []appctypes.ExposedPort) {
> 	var containerPorts []appctypes.Port
> ```

Might as well initialize these with a total capacity of len(portMappigns) since we have a pretty good idea that'll be close to right.

---

*[pkg/kubelet/rkt/rkt.go, line 2364 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30934#-KPV7lVpmQAV-mu9YP6C:-KPV7lVpmQAV-mu9YP6D:bpv8gxm) ([raw file](https://github.com/kubernetes/kubernetes/blob/a42f327321ca3ce20beaa6b0692fc02f7d856b5a/pkg/kubelet/rkt/rkt.go#L2364)):*
> ```Go
> 
> 	for _, p := range portMappings {
> 		portName := convertToACName(p.Name)
> ```

We lost the logic of skipping over `HostPort == 0` I think? Is that intentional?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30934)*

**Comment by euank** [comment]
I have a couple wording nits, but code-wise and overall LGTM 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/kubelet/rkt/rkt.go, line 2316 \[r2\]](http://reviewable.kubernetes.io:80/reviews/kubernetes/kubernetes/30934#-KPZ1e1CXNEajREIasz_:-KPZ1e1CXNEajREIasza:b-sxze00) ([raw file](https://github.com/kubernetes/kubernetes/blob/5ead6916201478d40366f4de8fb8a436a25fbc4a/pkg/kubelet/rkt/rkt.go#L2316)):*
> ```Go
> // Only one volume will be created for every unique host path.
> // Only one mount point will be created for every unique container path.
> func makeVolumesAndMountPoints(mounts []kubecontainer.Mount) ([]appctypes.Volume, []appctypes.MountPoint) {
> ```

Tiny nit, I think `convertKubeMounts` is slightly clearer than `make`

---

*[pkg/kubelet/rkt/rkt.go, line 2359 \[r2\]](http://reviewable.kubernetes.io:80/reviews/kubernetes/kubernetes/30934#-KPZ2KYHxTOOmUnez49j:-KPZ2KYHxTOOmUnez49k:baorwf4) ([raw file](https://github.com/kubernetes/kubernetes/blob/5ead6916201478d40366f4de8fb8a436a25fbc4a/pkg/kubelet/rkt/rkt.go#L2359)):*
> ```Go
> // makeContainerAndHostPorts creates appc container ports and host ports according to the given port mappings.
> // The container ports and host ports are mapped by PortMapping.Name.
> func makeContainerAndHostPorts(portMappings []kubecontainer.PortMapping) ([]appctypes.Port, []appctypes.ExposedPort) {
> ```

same nit that `convertKubePortMappings` might be a little clearer

---

*[pkg/kubelet/rkt/rkt.go, line 2364 \[r2\]](http://reviewable.kubernetes.io:80/reviews/kubernetes/kubernetes/30934#-KPZ2T_dX1nS1yM5H-6n:-KPZ2T_dX1nS1yM5H-6o:b-adcn4y) ([raw file](https://github.com/kubernetes/kubernetes/blob/5ead6916201478d40366f4de8fb8a436a25fbc4a/pkg/kubelet/rkt/rkt.go#L2364)):*
> ```Go
> 
> 	for _, p := range portMappings {
> 		// No need to do port binding when HostPort is not specified as Docker.
> ```

nit: ending should be "This matches the docker code's behaviour" or be reworded a little.

---


*Comments from [Reviewable](http://reviewable.kubernetes.io:80/reviews/kubernetes/kubernetes/30934#-:-KPZ33MtFZZdAzk8v_2n:b-kxcp0m)*

**Comment by yifan-gu** [comment]
Addressed comments @euank

**Comment by euank** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](http://reviewable.kubernetes.io:80/reviews/kubernetes/kubernetes/30934#-:-KPZeo-qEtZHtLoZUgYN:bnfp4nl)*

**Pull request merged**
