### PR TITLE
fixed a typo in kubectl book

### PR DESCRIPTION
**Pull request by oke-py**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
If I understand correctly, there is a typo in the kubectl book.
https://kubectl.docs.kubernetes.io/pages/imperative_porcelain/introduction.html

If it's not a typo, I feel sorry. I'm not a native English speaker.

**Which issue(s) this PR fixes**:

NONE

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
/ok-to-test
/priority backlog
/lgtm

**Comment by poothia** [comment]
lgtm

**Pull request merged**
