### PR TITLE
Fix kubectl create to create to all resources in a url.

### PR DESCRIPTION
**Pull request by aveshagarwal**
Fixes https://github.com/kubernetes/kubernetes/issues/18751 .

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@kubernetes/rh-cluster-infra

**Comment by aveshagarwal** [comment]
it seems it needs LGTM too.

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

**Comment by bgrant0607** [comment]
@smarterclayton Do you have time to take a quick look?

**Comment by kargakis** [comment]
Needs a test

**Comment by aveshagarwal** [comment]
Updated it with a test case.

**Comment by kargakis** [comment]
@aveshagarwal can you also exercise create in test-cmd.sh?

**Comment by aveshagarwal** [comment]
Added a test case to hack/test-cmd.sh and updated PR.

**Comment by aveshagarwal** [comment]
Flakes:

```
[Fail] Deployment [It] RecreateDeployment should delete old pods and create new ones 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:380

[Fail] Deployment [It] RollingUpdateDeployment should delete old pods and create new ones 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:268
```

**Comment by jlowdermilk** [comment]
@k8s-bot test this please issue: #22300

**Comment by kargakis** [comment]
LGTM

**Comment by kargakis** [comment]
@bgrant0607 please tag this as lgtm

**Comment by bgrant0607** [comment]
@kargakis Done. Thanks for the review.

**Pull request merged**
