### PR TITLE
cmd/kube-apiserver structured logging

### PR DESCRIPTION
**Pull request by learner0810**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yangjunmyfm192085** [comment]
/wg structured-logging
duplicate with https://github.com/kubernetes/kubernetes/pull/99535 and https://github.com/kubernetes/kubernetes/pull/99536

**Comment by pacoxu** [comment]
> /wg structured-logging duplicate with #99535 and #99536

- #99535 is not correct (One line change but wrong...)
- #99536 is closed

/remove-lifecycle rotten
/remove-lifecycle stale

**Comment by dims** [comment]
@learner0810 do we still need this? can you please check last few comments

**Comment by learner0810** [comment]
> @learner0810 do we still need this? can you please check last few comments

We still need this, duplicates of pr #99535 and #99536 are closed

**Pull request closed without merging**
