### PR TITLE
Partially avoid LabelSelectorAsSelector overhead in anti-pod affinity calculation

### PR DESCRIPTION
**Pull request by ahg-g**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

When calculating topology maps for anti-pod affinity evaluation, LabelSelectorAsSelector is called for the pod to be scheduled frequently while evaluating every existing pod, this is redundant and expensive at scale (when having many existing pods).

I modified the AntiPodAffinity scheduler_perf benchmark to schedule 15k pods, this PR improves performance by 18%:

before:
```
/tmp/5k-anti-affinity:BenchmarkSchedulingPodAntiAffinity/5000Nodes/1000Pods-12             15000          10442258 ns/op
```
after:
```
/tmp/5k-anti-affinity2:BenchmarkSchedulingPodAntiAffinity/5000Nodes/1000Pods-12                    15000           8640025 ns/op
```

**Which issue(s) this PR fixes**:
Fixes #

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cc @alculquicondor @Huang-Wei

### CODE REVIEW

**Review by Huang-Wei — COMMENTED** [review]
/lgtm

**Comment by alculquicondor** [comment]
extra points for getting rid of the `errCh` :) cc @hprateek43 

/lgtm

**Pull request merged**
