### PR TITLE
fix golint for pkg/volume/azure_dd

### PR DESCRIPTION
**Pull request by ddymko**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
 Fixes golint issues - pkg/volume/aws_dd
**Which issue(s) this PR fixes**:

Related https://github.com/kubernetes/kubernetes/issues/68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
> Fixes #68026

please change description. If you saying "Fixes", the issue will be closed once the PR is merged. Better would be "Related #68026".

**Comment by SergeyKanzhelev** [comment]
/lgtm
/assign @dashpole 
(for kubelet)

/assign @dims 
(for hack/OWNERS)

**Comment by sajanjswl** [comment]
please squash those multiple commits to a single commit.

**Comment by ddymko** [comment]
Squashed into single commit

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve
/priority important-soon
thanks

**Comment by ddymko** [comment]
Can I merge in master to resolve this conflict or squash it into a single commit?

**Comment by SergeyKanzhelev** [comment]
some uninstended changes were picked up on rebase:

image

Please fix

**Comment by SergeyKanzhelev** [comment]
and this is why -verify test is now failing

**Comment by SergeyKanzhelev** [comment]
@ddymko please rebase

**Comment by ddymko** [comment]
@SergeyKanzhelev sorry for the delay - rebased

**Pull request merged**
