### PR TITLE
Automated cherry pick of #38375

### PR DESCRIPTION
**Pull request by Random-Liu**
Cherry pick of #38375 on release-1.4.

#38375: Add image cache.

### CODE REVIEW

**Comment by Random-Liu** [comment]
/cc @jessfraz @yujuhong @dchen1107 
For https://github.com/kubernetes/kubernetes/issues/38373.

Are we still cherry-picking things into 1.4? A customer encountered the issue https://github.com/kubernetes/kubernetes/issues/38373 and wants a fix.

**Comment by jessfraz** [comment]
@k8s-bot unit test this

**Comment by Random-Liu** [comment]
@jessfraz It seems that there may be some conflict so auto cherrypick doesn't work.

I'll figure out why and update the PR. Thanks!

**Comment by jessfraz** [comment]
oh thanks!

**Comment by Random-Liu** [comment]
@jessfraz Changed one line to resolve the conflict. Thanks.

**Comment by jessfraz** [comment]
thanks!

**Comment by jessfraz** [comment]
merging because all green

**Pull request merged**
