### PR TITLE
Bump external provisioner image to smaller version

### PR DESCRIPTION
**Pull request by wongma7**
The image is roughly half as big so this should improve speed/flakiness maybe
-->
```release-note
NONE
```

### CODE REVIEW

**Comment by jsafrane** [comment]
@k8s-bot ok to test

**Comment by jsafrane** [comment]
lgtm

**Comment by wongma7** [comment]
@jsafrane so I realized another reason we should move from pulling from quay in this e2e test, I would like to have reliable stats for pulls but this is really mucking up the numbers since it pulls it hundreds of times a day :/ Since nobody seems to care about alternative to gcr.io for hosting e2e images, will you help me nag a googler to upload this image to gcr.io??!

**Comment by jsafrane** [comment]
@saad-ali is my favorite uploader to gcr.io :-). Saad, would it be possible if someone like me or @wongma7 got permissions to push to gcr.io/google_containers?

@wongma7, there is test/images/volumes-tester that contains images that are used in e2e tests, perhaps you can add your provisioner there and Saad will push it once the PR is merged.

**Comment by wongma7** [comment]
Still want this. https://github.com/kubernetes/kubernetes/pull/44925 would be even better, but it looks even less likely

**Comment by erictune** [comment]
@kubernetes/sig-storage-pr-reviews

**Comment by rootfs** [comment]
FWIW, 
```console
# docker images |grep nfs-provisioner
quay.io/kubernetes_incubator/nfs-provisioner            v1.0.6                        f02eb15d19db        7 weeks ago         341.1 MB
quay.io/kubernetes_incubator/nfs-provisioner            v1.0.3                        c12625ede8fd        4 months ago        522.4 MB
```

**Comment by wongma7** [comment]
@k8s-bot cvm gce e2e test this

**Comment by wongma7** [comment]
/retest

failed becauase github was down

**Comment by wongma7** [comment]
@foxish can you please re-/approve this? IDK why merge bot removed the label, maybe because tests failed like 5x in a row (because github was returning 500s yesterday, from what I can tell)

**Comment by grodrigues3** [comment]
@wongma7 we require all (non trivial) PRs to reference an issue for 1.7.  This one seems small enough that filing an issue is probably not necessary.  I'll readd the approved label.

**Pull request merged**
