### PR TITLE
WIP: Fix topologyKey comparison for node affinity

### PR DESCRIPTION
**Pull request by sttts**
Adding tests and turning predicate into a equality relation.

### CODE REVIEW

**Comment by sttts** [comment]
Seems like this was a misunderstanding of `NodesHaveSameTopologyKey`. Here `Same` implies that an actual label exists which is not empty. Closing.

**Comment by davidopp** [comment]
cc/ @wojtek-t

**Comment by davidopp** [comment]
Oops, sorry, just noticed you closed it.

**Pull request closed without merging**
