### PR TITLE
Update gopkg.in/yaml.v2 to v2.2.7

### PR DESCRIPTION
**Pull request by cjcullen**
Bump the gopkg.in/yaml.v2 dependency to pick up the most recent performance improvements.

```release-note
Improved yaml parsing performance
```

### CODE REVIEW

**Comment by dims** [comment]
@cjcullen need to rebase if we want to get this in

**Comment by cjcullen** [comment]
I'm trying to sneak in one more optimization upstream, but I'll get this rebased and in this week.

**Pull request merged**
