### PR TITLE
Set the 'WWW-Authenticate' header on 401 responses when basic auth is enabled

### PR DESCRIPTION
**Pull request by roberthbailey**
This is required for basic auth to work with web browsers.

/cc @brendandburns

### CODE REVIEW

**Comment by roberthbailey** [comment]
This depends on #7383 and won't pass tests until that PR is merged.

**Comment by lavalamp** [comment]
LGTM

**Comment by roberthbailey** [comment]
Rebased on top of #7383 and re-pushed.

**Comment by brendandburns** [comment]
Merging on manual test by @roberthbailey

**Pull request merged**
