### PR TITLE
Boilerplate speedup

### PR DESCRIPTION
**Pull request by eparis**
Do all boilerplate checks in 1 python call.  Calling python for every single file is slower than using the bash mess.  But this is calling python 1 time and having the python process all of the files.

It's just a little bit faster.....

```
BEFORE:
$ time hack/verify-boilerplate.sh

real        0m9.378s
user        0m3.405s
sys 0m13.906s

AFTER:
$ time hack/verify-boilerplate.sh

real        0m0.181s
user        0m0.114s
sys 0m0.068s
```

### CODE REVIEW

**Comment by eparis** [comment]
I'd like to land https://github.com/GoogleCloudPlatform/kubernetes/pull/7597 first.  This will then need a rebase.

**Comment by jlowdermilk** [comment]
+1. I'm generally a fan of using python over bash for this sort of thing.

**Comment by jlowdermilk** [comment]
lgtm

**Comment by eparis** [comment]
Rebased.   blocked on https://github.com/GoogleCloudPlatform/kubernetes/pull/7637

**Pull request merged**
