### PR TITLE
Remove e2e  echoserver image and replace it by agnost

### LINKED ISSUE #110605: echoserver:2.5 does not work on arm64 arch
### Problem statement
The [registry.k8s.io/e2e-test-images/echoserver:2.5](http://registry.k8s.io/e2e-test-images/echoserver:2.5) does not seem to work on arms64 linux VM. I got an error

```console
$ kubectl logs echo-597b9f4545-kb4lx
Generating self-signed cert
Generating a RSA private key
..............................+++++
......................................+++++
writing new private key to '/certs/privateKey.key'
-----
Starting nginx
2022/06/13 19:11:29 [alert] 13#13: detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
2022/06/13 19:11:29 [error] 13#13: lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file './resty/core.lua'
	no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file '/usr/share/lua/5.1/resty/core.lua'
	no file '/usr/share/lua/5.1/resty/core/init.lua'
	no file '/usr/share/lua/common/resty/core.lua'
	no file '/usr/share/lua/common/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so')
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file './resty/core.lua'
	no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file '/usr/share/lua/5.1/resty/core.lua'
	no file '/usr/share/lua/5.1/resty/core/init.lua'
	no file '/usr/share/lua/common/resty/core.lua'
	no file '/usr/share/lua/common/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so')
```

The nginx version is rather old `NGINX_VERSION=1.15.12`. That's a version from 16 Apr 2019. Newest version of nginx is from 25 Jan 2022.

## Expected behaviour
echoserver running up to date version of nginx. 
echoserver working on arm64 arch.

### PR DESCRIPTION
**Pull request by aojea**
/kind cleanup
/kind failing-test
Fixes #110605

The echoserver image used for the e2e test is based in nginx and lua, it doesn't compile for other architectures and is hard to maintain.

The ingressconformance has a version in golang that is easier to maintain and the e2e framework can drop on image

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
this image doesn't work :/

**Comment by aojea** [comment]
ok , this seems to make it

/assign @MrHohn @BenTheElder @rikatz @thockin

**Review by MrHohn — APPROVED** [review]
Thanks, happy to see echoserver being replaced by agnost, which brings in things like multi-arch naturally!
/lgtm

**Pull request merged**
