### PR TITLE
Fix detect-minion-names for gke provider

### PR DESCRIPTION
**Pull request by cjcullen**
This fixes the services.sh test on gke-ci.

### CODE REVIEW

**Comment by cjcullen** [comment]
@jlowdermilk @roberthbailey @mbforbes

**Comment by saad-ali** [comment]
Test fixes ok for 1.0. Assigned reviewer

**Comment by mbforbes** [comment]
LGTM

**Comment by jlowdermilk** [comment]
lgtm

**Comment by roberthbailey** [comment]
LGTM.

**Pull request merged**
