### PR TITLE
Don't set NetworkUnavailable condition in non-GCE/GKE clouds

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #27347

@davidopp @erictune @justinsb @simonswine

### CODE REVIEW

**Comment by davidopp** [comment]
LGTM

**Comment by simonswine** [comment]
@wojtek-t :+1:

**Comment by justinsb** [comment]
LGTM also.  Would love to enable the mechanism in 1.4, but for 1.3 disabling it like this is likely the best we can do.

**Comment by wojtek-t** [comment]
@justinsb - yes I would also like to enable it for 1.4, but this will require some non-trivial changes, and it's too late in 1.3.

**Pull request merged**
