### PR TITLE
adding controller manager starting option validations

### PR DESCRIPTION
**Pull request by huangjiuyuan**
**What this PR does / why we need it**:
Many validations of controller manager starting options were missing. I have added some validations of controller manager in `pkg/apis/componentconfig/validation/validation.go` along with unit tests.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

`Adding option validations for controller manager.`

### CODE REVIEW

**Comment by huangjiuyuan** [comment]
Hi, @mtaufen 
This PR have been hanging here for a while. Could you please take a look at this?

**Comment by mtaufen** [comment]
@mikedanese can you take a look? I'm not deeply familiar with the controller manager's configuration.

**Comment by huangjiuyuan** [comment]
Hi, @sttts 
Would you please take a look at this one? It had been here for really long time. Thank you!

**Pull request closed without merging**
