### PR TITLE
cleanup resource-quota controller/monitor map[]struct{} to sets.Set[]

### PR DESCRIPTION
**Pull request by charles-chenzz**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
this PR replace the map[]struct with sets.Set[] on the pkg/controller/resource-quota. Since we use go generic and wrapped the Set, we should start migrating the code and clean it up for better code readability
#### Which issue(s) this PR fixes:

Part of  #116731 

#### Special notes for your reviewer:
review to check whether I missed something
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
/assign @dinhxuanvu
Thank you!
/triage accepted

**Comment by charles-chenzz** [comment]
I think I've finish the clean up but the reason why test failed is the vendor issues, I push code on staging and it haven't been vendor yet. Anyway, I would like to wait for the reviewer to review and give me some advice

**Review by dinhxuanvu — COMMENTED** [review]
Looking good to me. This PR is specific to the resource-quote controller code and  I didn't see anything missing.
/lgtm

**Comment by dinhxuanvu** [comment]
@deads2k Ready for your review. Thanks :)

**Comment by charles-chenzz** [comment]
/close

will file another PR

**Pull request closed without merging**
