### PR TITLE
update-bazel.sh

### PR DESCRIPTION
**Pull request by saad-ali**
Fix bazel BUILD files in `release-1.5` branch by running `./hack/update-bazel.sh`. Should fix failing [ci-kubernetes-verify-release-1.5](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-verify-release-1.5/) test suite.

See issue https://github.com/kubernetes/kubernetes/issues/36843 for background.

CC @kubernetes/test-infra-maintainers @dims

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36844)

### CODE REVIEW

**Comment by saad-ali** [comment]
@kubernetes/test-infra-admins Looks like a bunch of the Jenkins pull jobs are failing with:

```
I1115 13:57:48.384] +++ command: //google-cloud-sdk/install.sh "--disable-installation-options" "--bash-completion=false" "--path-update=false" "--usage-reporting=false"
I1115 13:57:48.387] Welcome to the Google Cloud SDK!
W1115 13:58:49.047] ERROR: (gcloud.components.update) Failed to fetch component listing from server. Check your network settings and try again.
I1115 13:58:49.048] 
I1115 13:58:49.048] This will install all the core command line tools necessary for working with
I1115 13:58:49.048] the Google Cloud Platform.
I1115 13:58:49.048] 
I1115 13:58:49.081] +++ exit code: 1
I1115 13:58:49.084] +++ error: 1
```

Any idea what might be up? Worth opening a separate issue to track this?

**Comment by saad-ali** [comment]
The gcloud.components.update issues looks more widespread then release-1.5: https://github.com/kubernetes/kubernetes/issues/36842

**Comment by ixdy** [comment]
@k8s-bot test this

**Comment by saad-ali** [comment]
@ixdy Looks like everything is green including `Jenkins verification`:

```
I1115 15:23:46.002] Verifying hack/make-rules/../../hack/verify-bazel.sh
I1115 15:24:09.029] [0;32mSUCCESS[0m  hack/make-rules/../../hack/verify-bazel.sh	23s
```

**Comment by saad-ali** [comment]
Manually merging to unblock `release-1.5`. Submit queue is blocked due to issues in master.

**Pull request merged**
