### PR TITLE
feat(scheduler): expose SharedSchedulerListers in framework handle

### PR DESCRIPTION
**Pull request by draveness**
/kind feature
/sig scheduling
/priority important-soon

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

ref: #83523

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Expose SharedSchedulerListers in the framework handle
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by ahg-g** [comment]
/assign @alculquicondor 

Aldo, you created #80372 regarding where to put the scheduler-specific listers, I think it is important to address this now since we want to expose it in the FrameworkHandler. 

We need a way of doing this that allows CA, Kubelet and such to be able to create the framework without needing to instantiate structs defined in scheduler/internal.

It might be the case that we need to move cache out of internal and define the listers under scheduler/framework?

**Comment by alculquicondor** [comment]
Indeed, I'll reactivate the discussion there.

**Comment by draveness** [comment]
/close

superseded by https://github.com/kubernetes/kubernetes/pull/84164

**Pull request closed without merging**
