### PR TITLE
kubeadm: remove the deprecated output.kubeadm.k8s.io/v1alpha2

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

it is no longer used since https://github.com/kubernetes/kubernetes/pull/124464 is merged.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: removed the deprecated output.kubeadm.k8s.io/v1alpha2 API for structured output. Please use v1alpha3 instead.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/approve
/triage accepted
/priority backlog

thanks

**Comment by neolit123** [comment]
/release-note-edit

```release-note
kubeadm: remove the deprecated output.kubeadm.k8s.io/v1alpha2 API for structured output, please use v1alpha3 instead.
```

**Comment by neolit123** [comment]
/release-note-edit

```release-note
kubeadm: remove the deprecated output.kubeadm.k8s.io/v1alpha2 API for structured output. Please use v1alpha3 instead.
```

**Comment by sftim** [comment]
Changelog suggestion (past tense)
```diff
-kubeadm: remove the deprecated output.kubeadm.k8s.io/v1alpha2 API for structured output. Please use v1alpha3 instead.
+kubeadm: removed the deprecated output.kubeadm.k8s.io/v1alpha2 API for structured output. Please use v1alpha3 instead.
```

**Comment by neolit123** [comment]
> Changelog suggestion (past tense)
> 
> ```diff
> -kubeadm: remove the deprecated output.kubeadm.k8s.io/v1alpha2 API for structured output. Please use v1alpha3 instead.
> +kubeadm: removed the deprecated output.kubeadm.k8s.io/v1alpha2 API for structured output. Please use v1alpha3 instead.
> ```

what is the project release note preference?
i've been suggesting [imperative voice](https://en.wikipedia.org/wiki/Imperative_mood) everywhere which also applies to git commits instead of this past tense.

**Comment by sftim** [comment]
> what is the project release note preference? i've been suggesting [imperative voice](https://en.wikipedia.org/wiki/Imperative_mood) everywhere which also applies to git commits instead of this past tense.

Imperative for commits and PR titles; past tense for release notes (see https://www.kubernetes.dev/docs/guide/release-notes/)

**Pull request merged**
