### PR TITLE
list-resources: don't fail if the grep fails to match any resources

### LINKED ISSUE #41917: ci-kubernetes-e2e-gci-gke failing with "Failed to list resources (exit status 1)"
The last 4 runs of https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/ have failed on the `ListResources After` and `ListResources Before` steps with `Failed to list resources (exit status 1)`:
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/5061/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/5062/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/5063/
* https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/5064/

The GCE version of this test suite appears to be fine.

This is blocking the submit queue.

CC @kubernetes/test-infra-maintainers @kubernetes/goog-gke

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: if no resources are found, the `grep` call will exit nonzero, so guard it with ` || true`.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #41917

**Release note**:

cc @krzyzacy @ncdc

### CODE REVIEW

**Comment by ixdy** [comment]
@k8s-bot test this

**Comment by rmmh** [comment]
@k8s-bot cross build this

**Comment by saad-ali** [comment]
Will manually merge after a few of the runs are green to unblock submit queue.

**Comment by saad-ali** [comment]
The following builds have succeeded:
```
Jenkins Bazel Build — Build succeeded.
Jenkins GCE Node e2e — Build succeeded.
Jenkins GCI GKE smoke e2e — Build succeeded.
Jenkins GKE smoke e2e — Build succeeded.
Jenkins Kubemark GCE e2e — Build succeeded.
Jenkins non-CRI GCE Node e2e — Build succeeded.
```

This should be safe to merge now. Manually merging to fix submit queue (which has been blocked all day).

**Comment by krzyzacy** [comment]
@saad-ali @jessfraz you want to cherry-pick this into 1.4/1.5 branches as well.

**Comment by saad-ali** [comment]
> @saad-ali @jessfraz you want to cherry-pick this into 1.4/1.5 branches as well.

Will do!

**Comment by fejta** [comment]
How do we put this into 1.4?

**Pull request merged**
