### PR TITLE
Add BenchmarkSerializeObject* benchmarks

### PR DESCRIPTION
**Pull request by mborsz**
#### What this PR does / why we need it:

This adds a set of benchmark for SerializeObjects to validate overhead caused by gzip compression that happens there.

Current values:
```
goos: linux
goarch: amd64
pkg: k8s.io/apiserver/pkg/endpoints/handlers/responsewriters
BenchmarkSerializeObject10KB-12     	  143100	      9137 ns/op	   12935 B/op	      31 allocs/op
BenchmarkSerializeObject10MB-12     	      37	  27467329 ns/op	  104025 B/op	      40 allocs/op
BenchmarkSerializeObject100MB-12    	       4	 268239229 ns/op	  835488 B/op	      51 allocs/op
BenchmarkSerializeObject1GB-12      	       1	2658076446 ns/op	 5807424 B/op	      79 allocs/op
PASS
ok  	k8s.io/apiserver/pkg/endpoints/handlers/responsewriters	7.701s
```

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
```
/assign @wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
@mborsz - can you paste the current number from these benchmarks?

**Comment by mborsz** [comment]
Done. Numbers are in the description

**Comment by wojtek-t** [comment]
/lgtm
/approve

Thanks!

@smarterclayton - FYI

**Pull request merged**
