### PR TITLE
Automated cherry pick of #64739: Fix panic while provisioning Azure security group rules

### PR DESCRIPTION
**Pull request by feiskyer**
Cherry pick of #64739 on release-1.10.

#64739: Fix panic while provisioning Azure security group rules

### CODE REVIEW

**Comment by feiskyer** [comment]
/assign @andyzhangx 

@andyzhangx pls help to take a look

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by feiskyer** [comment]
CI broken on release-1.10. https://github.com/kubernetes/kubernetes/issues/64925

**Pull request merged**
