### PR TITLE
Revert "kube-proxy: internal config: refactor HealthzAddress and MetricsAddress "

### LINKED ISSUE #127794: [Failing Test] [sig-network] LoadBalancers should not have connectivity disruption during rolling update with externalTrafficPolicy=Cluster
### Which jobs are failing?

sig-release-master-informing.gce-cos-master-slow

### Which tests are failing?

`[It] [sig-network] LoadBalancers [Feature:LoadBalancer] should not have connectivity disruption during rolling update with externalTrafficPolicy=Cluster [Slow]

https://github.com/kubernetes/kubernetes/compare/fbf1a0dc1...a95db4143

### Since when has it been failing?
Since around 16 UTC - 10-01-2024

```
     F 2024-10-01 20:16:23 -0300 -03 [FAILED] Encountered too many errors when doing HTTP requests to the l...ernetes/test/e2e/network/loadbalancer.go:1437 @ 10/01/24 22:39:22.299
      F 2024-10-01 19:12:23 -0300 -03 [FAILED] Encountered too many errors when doing HTTP requests to the l...ernetes/test/e2e/network/loadbalancer.go:1437 @ 10/01/24 21:30:22.163
      F 2024-10-01 18:10:23 -0300 -03 [FAILED] Encountered too many errors when doing HTTP requests to the l...ernetes/test/e2e/network/loadbalancer.go:1437 @ 10/01/24 20:38:51.282
      F 2024-10-01 17:14:23 -0300 -03 [FAILED] Encountered too many errors when doing HTTP requests to the l...bernetes/test/e2e/network/loadbalancer.go:1437 @ 10/01/24 19:35:36.83
      F 2024-10-01 16:10:23 -0300 -03 [FAILED] Encountered too many errors when doing HTTP requests to the l...ernetes/test/e2e/network/loadbalancer.go:1437 @ 10/01/24 18:28:20.918
      F 2024-10-01 15:05:23 -0300 -03 [FAILED] Encountered too many errors when doing HTTP requests to the l...ernetes/test/e2e/network/loadbalancer.go:1437 @ 10/01/24 17:14:59.981
      F 2024-10-01 14:00:22 -0300 -03 [FAILED] Encountered too many errors when doing HTTP requests to the l...ernetes/test/e2e/network/loadbalancer.go:1437 @ 10/01/24 16:29:18.402
```

### Testgrid link
https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-slow&exclude-non-failed-tests=

### Reason for failure (if possible)
From the tracking commits https://github.com/kubernetes/kubernetes/pull/126889 possibly introduced this change.

### Anything else we need to know?

Other jobs started to flake possibly due this change
```
[It] [sig-network] LoadBalancers [Feature:LoadBalancer] should not have connectivity disruption during rolling update with externalTrafficPolicy=Cluster

[It] [sig-network] LoadBalancers [Feature:LoadBalancer] should have session affinity work for LoadBalancer service with Cluster traffic policy [Slow] [LinuxOnly]Kubernetes e2e suite.

[It] [sig-network] LoadBalancers [Feature:LoadBalancer] should be able to switch session affinity for LoadBalancer service with Cluster traffic policy [Slow] [LinuxOnly]
```

### Relevant SIG(s)
/sig network
cc: @kubernetes/release-team-release-signal

### PR DESCRIPTION
**Pull request by aojea**
Reverts kubernetes/kubernetes#126889

Fixes: https://github.com/kubernetes/kubernetes/issues/127794

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/127795 may be related?

**Comment by aojea** [comment]
correlation is strong 
image

This got merged Oct 3.34PM GMT+2

**Pull request merged**
