### PR TITLE
Remove ovirt/cloudstack/photon cloud providers

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I7ae5332b3659a2acd3805a51686af7d06ff86f4e

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

- Photon cloud provider was deprecated in f8ac0c4d41ad295392cff61e59b0ef0dbd0f6764
- Cloudstack cloud provider was deprecated in 1ca80d3b32f95d893e0b152c3ac2fcbc460982dc (external cloud provider is at https://github.com/tsuru/custom-cloudstack-ccm)
- ovirt cloud provider was deprecated in 1ca80d3b32f95d893e0b152c3ac2fcbc460982dc

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Remove deprecated cloud providers - ovirt, cloudstack and photon
```

### CODE REVIEW

**Comment by dims** [comment]
- @dougm (for photon)
- @sandrobonazzola (for ovirt)
- @sebgoa @andrestc @cezarsa (for cloudstack)

**Review by neolit123 — APPROVED** [review]
/approve
for cmd/kubeadm
thanks @dims

**Review by dougm — COMMENTED** [review]
/lgtm

**Review by yadvr — APPROVED** [review]
/approve
for pkg/cloudprovider/providers/cloudstack

**Comment by msau42** [comment]
Can someone from vmware approve the removal of the photon volume plugin?

**Comment by neolit123** [comment]
> Can someone from vmware approve the removal of the photon volume plugin?

/assign @frapposelli @dougm

**Comment by dougm** [comment]
> > Can someone from vmware approve the removal of the photon volume plugin?
> 
> /assign @frapposelli @dougm

I approve, but neither of us are in https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/photon_pd/OWNERS

/assign @abrarshivani

**Comment by msau42** [comment]
According to the deprecation policy, we cannot remove GA behavior until at least a year after the deprecation notice.  So this may need to wait until the next release.

**Comment by dims** [comment]
@msau42 i've marked it as milestone 1.15 (not 1.14), i can add a hold while collecting approvals 

/hold

**Comment by msau42** [comment]
@dims, I also don't see the deprecation notice in the older release notes.  Can we update them and also send out an announcement email to make sure people are not caught off guard?

**Comment by dims** [comment]
@msau42 - please see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#deprecations-and-removals - yes, i will send another email to -dev after i track down the photon one

**Comment by dims** [comment]
@msau42 note to -dev sent! https://groups.google.com/d/msg/kubernetes-dev/nGTt4zJNGDI/JygD7lmcCQAJ

**Comment by liggitt** [comment]
I'd love to see these go in 1.15, but if they were announced deprecated in 1.12, then 1.12 + 1 year means removing in 1.16, right?

**Comment by onitake** [comment]
Note: https://github.com/tsuru/custom-cloudstack-ccm is not a generic CloudStack CCM. See this issue: https://github.com/tsuru/custom-cloudstack-ccm/issues/15

We made one that we think is better suited as a replacement for the old cloud provider: https://github.com/swisstxt/cloudstack-cloud-controller-manager

**Pull request merged**
