### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by davidleitw**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Fix spelling of implemented in pkg/proxy/apis/config/types.go line 206

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

None

```release-note
Fix spelling of implemented in pkg/proxy/apis/config/types.go line 206
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by davidleitw** [comment]
I signed it

**Comment by davidleitw** [comment]
I signed it

**Comment by dims** [comment]
/retest
/approve
/lgtm

NOTE: just edits comments in a couple of lines.

**Comment by jberkus** [comment]
This change does not require a release note.

**Pull request merged**
