### PR TITLE
add some owners for deps

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: Adds @apelisse, @soltysh, and myself to approvers for godeps. This is to spread out the load more :sweat_smile: 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/assign @thockin 
cc @sttts @cblecker

### CODE REVIEW

**Comment by apelisse** [comment]
looks good to me

**Review by cblecker — APPROVED** [review]
👍 
We have some docs that will be published soon explicitly calling out the licenses that are okay. If you have questions, please feel free to ask, and thanks for helping out :)

**Comment by BenTheElder** [comment]
@cblecker thanks, I also just filed https://github.com/kubernetes/community/pull/3254 to add some more review considerations from Tim.

**Comment by soltysh** [comment]
:+1: on my end too

**Pull request merged**
