### PR TITLE
remove  TODO in test/e2e/framework/auth/helpers

### PR DESCRIPTION
**Pull request by tanjunchen**
**What type of PR is this?**
 
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

ref:https://github.com/kubernetes/kubernetes/issues/86721

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by tanjunchen** [comment]
/hold 
for cycle dependency

**Comment by neolit123** [comment]
@oomichi this causes import cycles.
some packages already import `test/e2e/framework` for the logging, yet this one cannot.

on the other hand i remember that we couldn't move the logging to `test/e2e/framework/log` because that also caused issues. :thinking:

**Comment by neolit123** [comment]
hm, but we also now have `test/e2e/framework/log`
@tanjunchen what happens if you import `test/e2e/framework/log` instead of ``test/e2e/framework/` for `Logf`?

**Comment by tanjunchen** [comment]
> hm, but we also now have `test/e2e/framework/log`
> @tanjunchen what happens if you import `test/e2e/framework/log` instead of `test/e2e/framework/` for `Logf`?

Sure, I have noticed that there are two logger :
  test/e2e/framework/log and test/e2e/framework/ in the  other subpackage , so we need to make sure that we use which one or just remove TODO.
i will have a try in test/e2e/framework/log

**Comment by tanjunchen** [comment]
```
not sure why we have the log utils in multiple locations, but ideally logging should be a top level package that only depends on ginkgo and stdlib.
```
for migration?  the logging should be common and top level , i agree.

**Comment by neolit123** [comment]
tests are passing so this seems good.
/lgtm
/hold cancel

**Comment by SataQiu** [comment]
IMO, we should not introduce invalid dependencies. 
Now, we are trying to remove the `framework/log` subpackage #81427
/cc @oomichi

**Comment by tanjunchen** [comment]
you can find the reason for cycle dependency problems in https://github.com/kubernetes/kubernetes/issues/81427 ,
There are still  
```
test/e2e/framework/metrics/*.go
test/e2e/framework/node/*.go
test/e2e/framework/ssh/ssh.go
test/e2e/framework/pod/*.go
test/e2e/kubectl/kubectl_utils.go (It seems that this can also cause problems with circular dependencies)
```
so I konw why. it seems that difficult to handle.

**Comment by oomichi** [comment]
@SataQiu Thanks for taking care of the dependency issue.
You are right, it is better to avoid another issue as possible.
At this time, the local `log()` in the auth package makes the dependency issue disappear to us with the local function.
In addition, `log()` functions exist at 3 places only include the auth package like
```
$ grep "func log(" * -R
e2e/framework/log.go:func log(level string, format string, args ...interface{}) {
e2e/framework/auth/helpers.go:func log(level string, format string, args ...interface{}) {
e2e/framework/log/logger.go:func log(level string, format string, args ...interface{}) {
```
So it is fine to merge the usages into e2elog package(invalid usage anyways) and take care of it with the other packages also later, I feel now.

**Comment by oomichi** [comment]
Sorry for my unclear previous comment.
I mean how about merging this PR and fixing the invalid usage later with the other usages?

**Comment by SataQiu** [comment]
Thanks @oomichi 
I agree to your suggestion, let's merge this for now.
/approve

**Comment by tanjunchen** [comment]
ref:https://github.com/kubernetes/kubernetes/issues/86763

**Pull request merged**
