### PR TITLE
refactor StoreToReplicationControllerLister

### PR DESCRIPTION
**Pull request by mqliang**
refactor StoreToReplicationControllerLister to return api.ReplicationControllerList

### CODE REVIEW

**Comment by bgrant0607** [comment]
@mqliang ReplicationControllerList is the type returned by the API. It doesn't really need to be used internally. Is there something you're trying to do that this change would make easier?

**Comment by mqliang** [comment]
@bgrant0607 
> ReplicationControllerList is the type returned by the API. It doesn't really need to be used internally. Is there something you're trying to do that this change would make easier?

`List()` method of StoreToDeploymentLister/StoreToDaemonSetLister/StoreToServiceLister/StoreToEndpointsLister/StoreToJobLister return a API list, others return an array. I just want make them consistent, so that it will be easier to auto generated this files using a script.

**Comment by bgrant0607** [comment]
LGTM

**Comment by mqliang** [comment]
Temporarily close this. I will send another PR to clean up this file and making all the List() funcs consistent. So that it will be more convenient to auto generate the files using a script in the future

**Pull request closed without merging**
