### PR TITLE
Increase range of job_sync_duration_seconds

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Set the lower end to 4ms, which makes the higher bucket reach 1min.

The job controller makes up to 2 operations per pod in a sync, and it can process up to 500 pods. Having visibility up to 1 min can give a better sense of the performance of the controller when using a low API QPS, such as 20, the default.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Set the resolution for the job_controller_job_sync_duration_seconds metric from 4ms to 1min
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by logicalhan — COMMENTED** [review]
You'll need to update the stable metrics descriptors.

`./hack/update-generated-stable-metrics.sh`

**Comment by alculquicondor** [comment]
Oops, fixed

**Pull request merged**
