### PR TITLE
ServerAPIVersions incorrectly squashes config.Prefix

### PR DESCRIPTION
**Pull request by jdef**
discovered while testing #9171

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM

**Comment by bgrant0607** [comment]
Please add the "lgtm" label so that the oncall knows the PR is ready to merge.

**Comment by bgrant0607** [comment]
Tests didn't run. Will close and re-open.

**Comment by krousey** [comment]
Integration tests failed. Here's a snippet

```
I0608 21:32:10.934376   28161 config.go:244] Setting pods for source file : {[] 0 file}
I0608 21:32:10.984597   28161 integration.go:953] Running 4 tests in parallel.
I0608 21:32:10.986342   28161 integration.go:391] Creating replication controllers
F0608 21:32:10.986448   28161 integration.go:420] failed to get api versions: the server could not find the requested resource
I0608 21:32:10.998678   28161 factory.go:214] About to try and schedule pod foo
I0608 21:32:10.998819   28161 replication_controller.go:199] No controllers found for pod foo, replication manager will avoid syncing
```

@jdef Could you run the integration tests (./hack/test-integration.sh I think) and fix this? Thanks.

**Comment by jdef** [comment]
@krousey I ended up adding a new func `UnversionedPath()` in order to pass the tests. I think it captures the intent of what ServerAPIVersions() needs, although I'm not proud of the "is-this-a-version" test that it implements. Is there a better way to test such?

**Comment by krousey** [comment]
@jdef I'm on interrupts today.
@brendandburns could you take this?

**Comment by krousey** [comment]
Oh wait, @smarterclayton was the original reviewer, not @bgrant0607.

@smarterclayton could you take a look at the changes?

**Comment by smarterclayton** [comment]
LGTM

**Pull request merged**
