### PR TITLE
Automated cherry pick of #14957 upstream release 1.1

### PR DESCRIPTION
**Pull request by brendandburns**
Ref #14957

@ixdy @ihmccreery @quinton-hoole @thockin

### CODE REVIEW

**Comment by quinton-hoole** [comment]
LGTM

**Comment by ixdy** [comment]
@k8s-bot test this please
@k8s-bot unit test this please

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by piosz** [comment]
Merging manually

**Pull request merged**
