### PR TITLE
refactor: rename bad taste variable in client-go

### PR DESCRIPTION
**Pull request by willise**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by lavalamp** [comment]
What part of this is in bad taste?

**Comment by willise** [comment]
> 
> 
> What part of this is in bad taste?

As `meta` is a package name, reusing it as a new variable name looks like not good.

**Comment by lavalamp** [comment]
OK thanks, I don't think we have a style rule against this, so I'd rather not make a change unless it's actually causing a problem.

(note: "bad taste" could mean what you're using it to mean, but most commonly would be used if there was some e.g. rude or not socially acceptable language)

**Pull request closed without merging**
