### PR TITLE
Correct CronJob group version at remaining places

### PR DESCRIPTION
**Pull request by shyamjvs**
...at places left-out by https://github.com/kubernetes/kubernetes/pull/51465

Fixes https://github.com/kubernetes/kubernetes/issues/51692

cc @soltysh

### CODE REVIEW

**Comment by shyamjvs** [comment]
/retest

The pre-submit is still failing with the same error. Would you be able to take a look @soltysh ?

**Comment by shyamjvs** [comment]
From the run I'm seeing kubetest ran with - `--kops-kubernetes-version https://storage.googleapis.com/kubernetes-release-dev/ci/v1.8.0-alpha.3.551+4a6bbb9f50cd82`
That build is from an earlier commit ([4a6bbb9f50cd82](https://github.com/kubernetes/kubernetes/commit/4a6bbb9f50cd82)) which is 8hrs old.
@kubernetes/test-infra-maintainers Why is it running against an old build? Please fix this asap - **this is blocking the SQ**

**Comment by justinsb** [comment]
The logs seem to show that this is passed in to us:

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/51697/pull-kubernetes-e2e-kops-aws/45416/build-log.txt

```
I0831 12:56:35.532] Bootstrap pull-kubernetes-e2e-kops-aws...
I0831 12:56:35.532] Gubernator results at https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/51697/pull-kubernetes-e2e-kops-aws/45416
I0831 12:56:35.533] Root: /var/lib/jenkins/workspace/pull-kubernetes-e2e-kops-aws/go/src
I0831 12:56:35.533] cd to /var/lib/jenkins/workspace/pull-kubernetes-e2e-kops-aws/go/src
I0831 12:56:35.533] Checkout: /var/lib/jenkins/workspace/pull-kubernetes-e2e-kops-aws/go/src/k8s.io/kubernetes master:4a6bbb9f50cd8293916d6b3fb9fd82878e9fd191,51697:3ef65c1d0af35ed94510b596d6bc118a7aeffff1
I0831 12:56:35.533] Call:  git init k8s.io/kubernetes
...
```

**Comment by dims** [comment]
@justinb @shyamjvs - i see a git merge in the build-log.txt that Justin pointed to.

`Call:  git merge --no-ff -m 'Merge +refs/pull/51697/head:refs/pr/51697' 3ef65c1d0af35ed94510b596d6bc118a7aeffff1`

**Comment by shyamjvs** [comment]
For that run the client was built from HEAD and server from HEAD-1 (but neither of them against the PR):

```
W0831 13:19:55.508] 2017/08/31 13:19:55 util.go:108: Running: ./cluster/kubectl.sh version --match-server-version=false
I0831 13:19:55.698] Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.3.552+721923924dec1a", GitCommit:"721923924dec1ab48cee01b5afe5426376d8e7b3", GitTreeState:"clean", BuildDate:"2017-08-31T12:52:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
I0831 13:19:55.699] Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.3.551+4a6bbb9f50cd82", GitCommit:"4a6bbb9f50cd8293916d6b3fb9fd82878e9fd191", GitTreeState:"clean", BuildDate:"2017-08-31T06:30:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by justinsb** [comment]
So @dims pointed out that 4a6bbb9f50cd82 is the latest commit, or close enough....

**Comment by soltysh** [comment]
I'm adding do-not-merge label, b/c now that we reverted cronjobs/beta (https://github.com/kubernetes/kubernetes/pull/51720) this will break. I'll re-pick cronjobs and this in a new PR.

**Comment by shyamjvs** [comment]
Closing this PR then.

**Pull request closed without merging**
