### PR TITLE
Update incorrect comment of RealRSControl

### PR DESCRIPTION
**Pull request by henjoon**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by googs1025** [comment]
for me
/lgtm 
just typo fix

**Comment by soltysh** [comment]
Per https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits

I'm considering this a trivial change. Let's fix this while addressing something else.

/close

**Pull request closed without merging**
