### PR TITLE
Casandra Example Enhancement

### PR DESCRIPTION
**Pull request by kevensen**
Cassandra example - Modified line 103 in java/src/io/k8s/cassandra/KubernetesSeedProvider.java to accept the Kubernetes host as an environment variable from the pod template.  Compiled the Jar and moved it to image/kubernetes-cassandra.jar.  Changed the version number in the pom.xml file.

### CODE REVIEW

**Comment by kevensen** [comment]
I work for Red Hat, Inc.  I believe we have a corporate CLA on file.

**Comment by kevensen** [comment]
Greetings,

I work for Red Hat, Inc.  I believe we have a corporate CLA on file.

Warm Regards,
Ken Evensen
Solutions Architect
Red Hat, Inc.

----- Original Message -----

**Comment by kevensen** [comment]
ok to test

**Comment by cjcullen** [comment]
ok to test

**Comment by cjcullen** [comment]
Not sure why the bots aren't making the RedHat connection...

**Comment by brendandburns** [comment]
LGTM.

**Comment by brendandburns** [comment]
@smarterclayton can you add @kevensen to the red hat group for CLA?

(I'll manually let this one in...)

**Pull request merged**
