### PR TITLE
Make kubelet label types public

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
We use the label definitions in CRI-O, means we now make them public to stop vendoring/copying this part of Kubernetes.

#### Which issue(s) this PR fixes:

Refers to https://github.com/cri-o/cri-o/pull/6953#discussion_r1232274783

#### Special notes for your reviewer:
@haircommander @mrunalp PTAL
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by haircommander** [comment]
/lgtm

thanks!

**Comment by saschagrunert** [comment]
@Random-Liu @SergeyKanzhelev @dchen1107 @derekwaynecarr @dims @endocrimes @klueska @luxas @mrunalp @mtaufen @sig-node-approvers @sjenning @sttts @tallclair @yujuhong

PTAL for approval

**Pull request merged**
