### PR TITLE
Enable Garbage collection by default for RS and RC

### PR DESCRIPTION
**Pull request by krmayankk**
Fixes https://github.com/kubernetes/kubernetes/issues/40898

### CODE REVIEW

**Comment by krmayankk** [comment]
@caesarxuchao @kargakis

**Comment by krmayankk** [comment]
@k8s-bot gci gce e2e test this

**Comment by caesarxuchao** [comment]
LGTM. Thanks @krmayankk.

**Comment by krmayankk** [comment]
@caesarxuchao i see following unit tests fail, do you think they are related ?


 --- FAIL: TestAvailableReplicas (0.00s)
	replica_set_test.go:195: Unexpected number of patches.  Expected 0, saw 2
FAIL
FAIL	k8s.io/kubernetes/pkg/controller/replicaset	9.810s
make: *** [test] Error 1

**Comment by k82cn** [comment]
@krmayankk , I think there's also some build error :).

```
W0211 08:21:19.828]   /root/.cache/bazel/_bazel_root/e9f728bbd90b3fba632eb31b20e1dacd/execroot/kubernetes/_bin/linux-sandbox @/root/.cache/bazel/_bazel_root/e9f728bbd90b3fba632eb31b20e1dacd/bazel-sandbox/6926e7ee-ec53-47da-8504-7e9589a48000-6/linux-sandbox.params -- bazel-out/local-fastbuild/bin/pkg/controller/replication/bazel-out/local-fastbuild/bin/pkg/controller/replication/go_default_test.a.GoCompileFile.params).
I0211 08:21:19.928] k8s.io/kubernetes/pkg/controller/replication/replication_controller_test.go:167: too many arguments in call to NewReplicationManager
I0211 08:21:19.928] k8s.io/kubernetes/pkg/controller/replication/replication_controller_test.go:462: too many arguments in call to NewReplicationManager
```

**Comment by caesarxuchao** [comment]
Yeah, it looks related. Let's see if it's flake.

@k8s-bot unit test this

**Comment by krmayankk** [comment]
@k82cn thanks i fixed it.

**Comment by krmayankk** [comment]
@caesarxuchao doesn't seem like a flake, will investigate more.

**Comment by krmayankk** [comment]
@caesarxuchao @kargakis 

I am still seeing the failure for both rc and rs
```--- FAIL: TestAvailableReplicas (0.00s)
replica_set_test.go:195: Unexpected number of patches. Expected 0, saw 2
FAIL
FAIL    k8s.io/kubernetes/pkg/controller/replicaset    9.810s
make: *** [test] Error 1
```
A patch is done to adopt the orphans. In the test `TestAvailableReplicas` it creates a rs with replica 2 and waits for both pods to come up then in line 1434, it says `// The controller should see only one available pod.` which i dont understand why only one pod should be there ? 
Also since now the GC is enabled by default, it seems RS is adopting the orphans by sending a patch and the probably fix here is to disable adoption, but i dont know where the orphandependant options should be set in the test.

**Comment by caesarxuchao** [comment]
Re: why only one available pod

See the comment [here](https://github.com/kubernetes/kubernetes/blob/v1.6.0-alpha.3/pkg/apis/extensions/v1beta1/types.go#L785-L787).

Seeing 2 patches is also as expected as you said. To fix the test, you can just set up the ownerReference in their two pods to point to the RS, with ownerReference.controller=true. That way the RS controller will think those two pods are already controlled and won't try to send the patch.

**Comment by krmayankk** [comment]
@k8s-bot unit test this

**Comment by krmayankk** [comment]
@kargakis @caesarxuchao @lavalamp can one of you approve. Also it seems the jenkins unit test failure is a flake. Please confirm.

**Comment by kargakis** [comment]
```
I0220 14:36:54.548] FAIL	k8s.io/kubernetes/pkg/controller/podautoscaler	6.443s
```
Yes, this is a flake. We need to update the approvers in the OWNERS files for the controllers, as is only top level (pkg/controller) OWNERS can approve controller changes.
/lgtm

**Comment by kargakis** [comment]
@k8s-bot unit test this

**Comment by kargakis** [comment]
@k8s-bot unit test this https://github.com/kubernetes/kubernetes/issues/41768

**Comment by kargakis** [comment]
This seems related
```
I0221 02:22:14.842] FAIL	k8s.io/kubernetes/test/integration/quota [build failed]
I0221 02:22:14.842] FAIL	k8s.io/kubernetes/test/integration/replicaset [build failed]
I0221 02:22:14.842] FAIL	k8s.io/kubernetes/test/integration/replicationcontroller [build failed]
```
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41282/pull-kubernetes-unit/19043/

**Comment by krmayankk** [comment]
@k8s-bot unit test this #41768

**Comment by caesarxuchao** [comment]
Only the verification test failure seems real:

```
FAILED   hack/make-rules/../../hack/verify-federation-openapi-spec.sh
```
But I guess you just need a rebase and it will be fixed.

**Comment by kargakis** [comment]
@krmayankk if you want this merged you better fix any test failures, otherwise @enisoc will beat you to it :)
https://github.com/kubernetes/kubernetes/pull/41984

**Comment by krmayankk** [comment]
@kargakis thanks for letting me know. This is weird, two people working on the same thing. Also none of these failures are now related to the changes i am doing. will take another look today

**Comment by kargakis** [comment]
> This is weird, two people working on the same thing.

I have seen this a bunch of times before in Kube - has happened to me a couple of them :)

**Comment by enisoc** [comment]
@krmayankk Sorry about that. I'll let yours go first and resolve conflicts on my end. Let's get in touch if you plan to do anything else that touches ControllerRef so we don't duplicate effort. :) I am working off of this TODO list right now: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/controller-ref.md#implementation

**Comment by krmayankk** [comment]
@kargakis @caesarxuchao finally all tests passed , can one of you approve again. lgtm is gone because i had pushed some more changes

**Comment by enisoc** [comment]
@k8s-bot non-cri node e2e test this

Looks like a flake when tearing down the test env.

**Comment by kargakis** [comment]
@deads2k mind approving this one

**Comment by caesarxuchao** [comment]
@krmayankk what happened to the failed test ("gc should orphan pods created by rc if delete options says so") we chatted  on slack? Is it a flake?

**Comment by krmayankk** [comment]
@caesarxuchao yes it occurred 2-3 times before, but it magically disappeared for the last 2 runs

**Comment by caesarxuchao** [comment]
Curious why it didn't occur before. I don't see how this pull can make the test flaky. I'm going to kick the bot to run e2e again to see if we can reproduce.

**Comment by caesarxuchao** [comment]
@k8s-bot gce e2e test this

**Comment by caesarxuchao** [comment]
test failure is not related.

@k8s-bot gce etcd3 e2e test this

**Comment by caesarxuchao** [comment]
Test failure not related

@k8s-bot cvm gce e2e test this

**Comment by krmayankk** [comment]
@caesarxuchao thanks. @kargakis  This PR has a lgtm label, who else need to approve ? cc @deads2k

**Comment by krmayankk** [comment]
adding @lavalamp and @mikedanese  for kube-controller-manager

**Comment by caesarxuchao** [comment]
@deads2k @lavalamp @mikedanese could you approve this change? It needs your approval for cmd/kube-controller-manager.

**Comment by kargakis** [comment]
P2 since this is blocking other work.

**Comment by krmayankk** [comment]
@kargakis @caesarxuchao @mikedanese  thanks all of you for helping out. @enisoc you are good for yours now. I haven't started anything else on the controller ref, but i can sync up offline if you need a helping hand on anything in the todo as i am starting to get familiar in this area, as well.

**Pull request merged**
