### PR TITLE
clean up redundant conditiontype ‘OutOfDisk’

### LINKED ISSUE #48843: Deprecate and remove flags and conditions replaced by eviction flags and conditions.
The deprecated flags are documented [here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/kubelet-eviction.md#deprecation-of-existing-features).
- [x]  1.6: #41941 Depreciate the `--low-diskspace-threshold-mb` and `--outofdisk-transition-frequency` kubelet flags.
- [x]  1.7: #46448 Set the default for `--low-diskspace-threshold-mb` to 0, which causes the OutOfDisk condition to never trigger.
- [x]  1.7  Publicly publish a notification for the removal of these flags and the OutOfDisk condition to kubernetes-dev@googlegroups.com
- [x]  1.8: #48846 Remove `--low-diskspace-threshold-mb` and `--outofdisk-transition-frequency` kubelet flags, and the kubelet disk manager.
- [x]  1.8: Remove all component references to the OutOfDisk condition
- [ ]  1.10+: Remove kubelet generation of the OutOfDisk condition

### PR DESCRIPTION
**Pull request by Pingan2017**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #48843

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
The deprecated node condition type 'OutOfDisk' has been removed. Use the 'DiskPressure' condition instead.
```

### CODE REVIEW

**Review by timothysc — CHANGES_REQUESTED** [review]
This definitely needs a release note, b/c it's api facing.

**Comment by Pingan2017** [comment]
> This definitely needs a release note, b/c it's api facing.

Updated!

**Comment by timothysc** [comment]
/lgtm 

but this require @kubernetes/sig-api-machinery-pr-reviews approval.

**Comment by Pingan2017** [comment]
/hold 
b/c #72507

**Comment by derekwaynecarr** [comment]
If this was removed in 1.13, it should be fine to remove in 1.15, agree @liggitt?

**Comment by liggitt** [comment]
1.15 only has to worry about nodes running >= 1.13, that is true. 

however, since this is cleaning up node objects upgraded from 1.12 to 1.13+, the cleanup code needs to remain in place for 1.15, where no 1.12-level (or older) nodes are supported. 

this can be dropped in 1.16.

**Comment by zhanghuidinah** [comment]
ping,any update?

**Comment by liggitt** [comment]
/hold cancel

once rebased, this can be merged

**Comment by Pingan2017** [comment]
rebased and remove func `RemoveOutOfDiskCondition()`

@liggitt  @derekwaynecarr

**Pull request merged**
