### PR TITLE
Remove dependency of external find utility (#95186)

### LINKED ISSUE #95186: kubelet does not work with busybox `find` command
**What happened**:
kubelet fails to run pods on Alpine Linux with busybox find.
```
E0928 14:40:27.368735    2455 cri_stats_provider.go:591] Unable to fetch container log stats for path /var/log/pods/kube-system_kube-proxy-5qw5z_38dc981c-397a-4896-b8c5-0e0415f3eb46/kube-proxy: cmd [find /var/log/pods/kube-system_kube-proxy-5qw5z_38dc981c-397a-4896-b8c5-0e0415f3eb46/kube-proxy -xdev -printf .] failed. stderr: find: unrecognized: -printf
```

**What you expected to happen**:
I expected the `find` call to exit with success, not failure.

**How to reproduce it (as minimally and precisely as possible)**:
Install and run kublet on Alpine Linux without installing GNU findutils, so busybox implementation of `find` is used.

**Anything else we need to know?**:
`find` failed because the argument `-printf` is not implemented in busybox `find`.

The `-printf` option is not specified in [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/find.html) so it can not be expected to be supported in all `find` implementations.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"archive", BuildDate:"2020-09-21T06:09:21Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-09-14T11:56:23Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
  QEMU/KVM virtual machine
- OS (e.g: `cat /etc/os-release`):
```
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.12.0
PRETTY_NAME="Alpine Linux v3.12"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
- Kernel (e.g. `uname -a`):
```
Linux aworker0 5.4.43-1-virt #2-Alpine SMP Thu, 28 May 2020 20:13:48 UTC x86_64 GNU/Linux
```
- Install tools:
custom
- Network plugin and version (if this is a network-related bug):
not network-related bug
- Others:
I think it would be better to use `filepath.Walk` instead of `exec.Command("find"...)`

Related to #95172

### PR DESCRIPTION
**Pull request by ncopa**
Fix inode usage calculation to use filepath.Walk instead of executing an
external find.

This is needed to make kubelet work on Alpine Linux who may have busybox
find instead of GNU findutils installed. busybox find fails due to the
use of non-standard `-printf` option.

Signed-off-by: Natanael Copa <ncopa@mirantis.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This make kubelet work on machineks that does not have GNU findutils' `find(1)` installed, such as Alpine Linux which uses busybox find.

It is also slightly better to avoid external dependencies in general when it is easy to implement same functionality in go.

**Which issue(s) this PR fixes**:

Fixes #95186

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
@ncopa this came originally from cadvisor, now the cadvisor has moved to filepath.Walk as well, however it's not as straightforward as the code you have here as there were problems along the way, so please see the latest below and adopt/adapt:
https://github.com/google/cadvisor/blob/master/fs/fs.go

thanks,
Dims

**Comment by ncopa** [comment]
Right, i didn't think about hardlinks. I don't think current implementation takes that in account?

I did notice that `filepath.Walk` may be significantly slower though. I don't know if that matters.

**Comment by ncopa** [comment]
I signed it

**Comment by ncopa** [comment]
@dims The current code has a comment saying:
```Go
// Find uses the equivalent of the command `find <path> -dev -printf '.' | wc -c` to count files and directories.
// While this is not an exact measure of inodes used, it is a very good approximation.
func Find(path string) (int64, error) {
```

If I change adapt the code, it will no longer correspond the the command `find <path> -xdev -printf '.' | wc -c`, so the comment would be wrong, and the name of the function would be wrong. Can I simply rename the `Find` function (and adapt the only caller of it)? I am not sure since it is a public function and I am not sure if there are any rules about public APIs.

**Comment by ncopa** [comment]
I am closing this in favor of #96115

**Pull request closed without merging**
