### PR TITLE
kubelet: rename cm ResourceConfig CPU fields

### PR DESCRIPTION
**Pull request by bmoix**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This PR renames the CPU fields in the `ResourceConfig` object from the `kubelet/cm` package to follow the golang guidelines about [acronyms/initialisms](https://github.com/golang/go/wiki/CodeReviewComments#initialisms).

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

Marked lgtm, assuming the tests pass.

This diff is also helpful for resolving some, although not all, of the golint errors for `pkg/kubelet/cm`.

Thanks for including the helpful link showing the Go community preferences :)

**Review by hvaara — COMMENTED** [review]
Hi @bmoix, and thanks for the PR! 🎉 
I'm not a reviewer, but this looks good to me

Ref #68026

**Pull request closed without merging**
