### PR TITLE
allow the token controller to get secrets

### PR DESCRIPTION
**Pull request by mikedanese**
we need this on secret rotation here:

https://github.com/kubernetes/kubernetes/blob/2c1c0f3f7295e0d00651d6e30cfcda56239275e4/pkg/controller/serviceaccount/tokens_controller.go#L478-L481

cc @liggitt

### CODE REVIEW

**Comment by liggitt** [comment]
Change LGTM, but this means we don't exercise rotation in an env with RBAC on. Follow up to add a test?

This should be cherry picked to 1.6

**Comment by mikedanese** [comment]
@k8s-bot kops aws e2e test this

**Comment by mikedanese** [comment]
Needs to update a couple lines below as well.

**Comment by mikedanese** [comment]
I manually tested and this works.

**Comment by liggitt** [comment]
Yup. That's an odd way to slice those permissions. I'm more used to the collection of verbs paired with the resource.

**Comment by mikedanese** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
