### PR TITLE
Fix admission webhook test failure in go1.9

### LINKED ISSUE #54020: admission webhook test failure in go1.9
xref: #49484, #51375 
The `k8s.io/kubernetes/plugin/pkg/admission/webhook` package is failing tests and doesn't seem to work as expected when run under go1.9. It throws some x509 certificate errors. However, the same tests run successfully under go1.8.

go1.8 successful output:
```
$ go test -v ./plugin/pkg/admission/webhook
=== RUN   TestAdmit
got req: /allow
got req: /disallow
got req: /disallowReason
got req: /internalErr
E1016 15:30:57.032550   19814 admission.go:199] failed calling admission webhook "internalErr C": an error on the server ("webhook internal server error") has prevented the request from succeeding
got req: /internalErr
E1016 15:30:57.035062   19814 admission.go:199] failed calling admission webhook "internalErr A": an error on the server ("webhook internal server error") has prevented the request from succeeding
got req: /internalErr
E1016 15:30:57.037306   19814 admission.go:199] failed calling admission webhook "internalErr B": an error on the server ("webhook internal server error") has prevented the request from succeeding
--- PASS: TestAdmit (0.07s)
=== RUN   TestGroup
--- PASS: TestGroup (0.00s)
=== RUN   TestVersion
--- PASS: TestVersion (0.00s)
=== RUN   TestOperation
--- PASS: TestOperation (0.00s)
=== RUN   TestResource
--- PASS: TestResource (0.00s)
=== RUN   TestDefaultServiceResolver
=== RUN   TestDefaultServiceResolver/scenario_0
=== RUN   TestDefaultServiceResolver/scenario_1
=== RUN   TestDefaultServiceResolver/scenario_2
--- PASS: TestDefaultServiceResolver (0.00s)
    --- PASS: TestDefaultServiceResolver/scenario_0 (0.00s)
    --- PASS: TestDefaultServiceResolver/scenario_1 (0.00s)
    --- PASS: TestDefaultServiceResolver/scenario_2 (0.00s)
PASS
ok      k8s.io/kubernetes/plugin/pkg/admission/webhook  0.148s
```

go1.9 failing output:
```
$ go test -v ./plugin/pkg/admission/webhook
=== RUN   TestAdmit
2017/10/16 15:11:08 http: TLS handshake error from 127.0.0.1:62299: remote error: tls: bad certificate
E1016 15:11:08.664921   90108 admission.go:199] failed calling admission webhook "disallowReason": Post https://127.0.0.1:62298/disallowReason: x509: certificate is not valid for any names, but wanted to match webhook-test.default.svc
2017/10/16 15:11:08 http: TLS handshake error from 127.0.0.1:62302: remote error: tls: bad certificate
E1016 15:11:08.670346   90108 admission.go:199] failed calling admission webhook "internalErr C": Post https://127.0.0.1:62298/internalErr: x509: certificate is not valid for any names, but wanted to match webhook-test.default.svc
2017/10/16 15:11:08 http: TLS handshake error from 127.0.0.1:62300: remote error: tls: bad certificate
E1016 15:11:08.670615   90108 admission.go:199] failed calling admission webhook "internalErr B": Post https://127.0.0.1:62298/internalErr: x509: certificate is not valid for any names, but wanted to match webhook-test.default.svc
2017/10/16 15:11:08 http: TLS handshake error from 127.0.0.1:62301: remote error: tls: bad certificate
E1016 15:11:08.670893   90108 admission.go:199] failed calling admission webhook "internalErr A": Post https://127.0.0.1:62298/internalErr: x509: certificate is not valid for any names, but wanted to match webhook-test.default.svc
2017/10/16 15:11:08 http: TLS handshake error from 127.0.0.1:62303: remote error: tls: bad certificate
E1016 15:11:08.676384   90108 admission.go:199] failed calling admission webhook "allow": Post https://127.0.0.1:62298/allow: x509: certificate is not valid for any names, but wanted to match webhook-test.default.svc
2017/10/16 15:11:08 http: TLS handshake error from 127.0.0.1:62304: remote error: tls: bad certificate
E1016 15:11:08.679835   90108 admission.go:199] failed calling admission webhook "disallow": Post https://127.0.0.1:62298/disallow: x509: certificate is not valid for any names, but wanted to match webhook-test.default.svc
--- FAIL: TestAdmit (0.02s)
        admission_test.go:221: "match & disallow ii": expected allowed=false, but got err=<nil>
        admission_test.go:226: "match & disallow ii": expected an error saying "you shall not pass", but got <nil>
        admission_test.go:221: "match & disallow": expected allowed=false, but got err=<nil>
        admission_test.go:226: "match & disallow": expected an error saying "without explanation", but got <nil>
=== RUN   TestGroup
--- PASS: TestGroup (0.00s)
=== RUN   TestVersion
--- PASS: TestVersion (0.00s)
=== RUN   TestOperation
--- PASS: TestOperation (0.00s)
=== RUN   TestResource
--- PASS: TestResource (0.00s)
=== RUN   TestDefaultServiceResolver
=== RUN   TestDefaultServiceResolver/scenario_0
=== RUN   TestDefaultServiceResolver/scenario_1
=== RUN   TestDefaultServiceResolver/scenario_2
--- PASS: TestDefaultServiceResolver (0.00s)
    --- PASS: TestDefaultServiceResolver/scenario_0 (0.00s)
    --- PASS: TestDefaultServiceResolver/scenario_1 (0.00s)
    --- PASS: TestDefaultServiceResolver/scenario_2 (0.00s)
FAIL
exit status 1
FAIL    k8s.io/kubernetes/plugin/pkg/admission/webhook  0.117s
```

---
@kubernetes/sig-node-bugs @derekwaynecarr 
/priority important-soon

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

Go 1.9 has some better checks for SAN extensions, notably:
https://github.com/golang/go/commit/630e93ed2d8a13226903451a0e85e62efd78cdcd

We recently added ServerName to the rest client TLSConfig:
https://github.com/dims/kubernetes/commit/186a0684d582272aa2fbfec390aea5fbb88a8bc6#diff-eb3573c6b11347dc3793c477726480efR262

So we need to be sure that the ServerName "webhook-test.default.svc" is
present in the certificates that we generate."

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Fixes #54020

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@kubernetes/sig-node-pr-reviews

**Comment by cblecker** [comment]
Yup, that's the ticket! Tests pass locally both with the generated certs in this PR, and if I regenerate them again a second time using `gencerts.sh`.
/lgtm

**Comment by luxas** [comment]
Thank you @dims!

**Comment by luxas** [comment]
@mikedanese @liggitt @derekwaynecarr Can one of you approve this? It's needed for Go 1.9, which we want to switch over to ASAP

**Pull request merged**
