### PR TITLE
[prep for go1.21]: use -e in `go list`

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
For some reason, in go1.21, go list does not allow importing main packages anymore, even if it is for the sake of tracking dependencies (which is a valid use case).

A suggestion to work around this is to use -e flag to permit processing of erroneous packages. However, this doesn't seem prudent.

#### Which issue(s) this PR fixes:
Ref https://github.com/kubernetes/kubernetes/pull/118996#issuecomment-1617386511
Ref: https://github.com/golang/go/issues/59186

#### Special notes for your reviewer:
I'm not sure if we should be doing `-e` since that allows processing of ALL erroneous packages.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
/sig architecture

### CODE REVIEW

**Comment by MadhavJivrajani** [comment]
Going to drop the `.go-version` file once canaries are in place: https://github.com/kubernetes/test-infra/pull/29989
so as to try and test with both 1.20 and 1.21

**Comment by MadhavJivrajani** [comment]
need to wait for an autobump to happen in test-infra to verify the dep. canary job is actually passing and that the verify canary job is still failing.

**Comment by liggitt** [comment]
I'm not happy about working around a regression in `go list` this way ...

**Comment by MadhavJivrajani** [comment]
> I'm not happy about working around a regression in go list this way ...

fwiw -- +1, not really a fan of this approach.

**Comment by liggitt** [comment]
digging into this, I actually agree the imports of main packages in the tools tagged files are weird... I'm not sure what I would have expected go list to do, so adding `-e` is actually more reasonable than I thought at first. If you can rebase this I'm ok with merging / backporting it

**Comment by MadhavJivrajani** [comment]
@liggitt done

Just one concern:
> The -e flag changes the handling of erroneous packages, those that
cannot be found or are malformed. By default, the list command
prints an error to standard error for each erroneous package and
omits the packages from consideration during the usual printing.
With the -e flag, the list command never prints errors to standard
error and instead processes the erroneous packages with the usual
printing. Erroneous packages will have a non-empty ImportPath and
a non-nil Error field; other information may or may not be missing
(zeroed).

The "erroneous" packages mentioned here, are we okay with processing them here? Even the ones apart from main imports?

**Comment by liggitt** [comment]
> The "erroneous" packages mentioned here, are we okay with processing them here? Even the ones apart from main imports (in case any happen to come up in the future somehow)?

Errors here would make verify jobs fail (verify-vendor, or verify-codegen, etc). These tools are explicitly for things required to make generation/vendor/test work, so if generation/vendor/test actually do work, I think we're satisfied.

**Comment by liggitt** [comment]
/lgtm
/approve

once this merges, go ahead and open picks back to 1.25

**Comment by MadhavJivrajani** [comment]
Cherry picks are up
@liggitt FYI - I've updated the comment in the tracking issue to put the links in there.

**Pull request merged**
