### PR TITLE
Parameterize vpc name

### PR DESCRIPTION
**Pull request by michaelvilensky**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/28499)

### CODE REVIEW

**Comment by eparis** [comment]
@justinsb LGTM but will let you take a peek...

**Comment by eparis** [comment]
ok to test

**Comment by michaelvilensky** [comment]
any reason why it's not being merged?

**Comment by justinsb** [comment]
Technically kube-up is now in maintenance mode, so we're trying not to add new features: https://github.com/kubernetes/kubernetes/blob/master/cluster/README.md#deprecation-notice-this-directory-has-entered-maintainence-mode-and-will-not-be-accepting-new-providers-please-submit-new-automation-deployments-to-kube-deploy-deployments-in-this-directory-will-continue-to-be-maintained-and-supported-at-their-current-level-of-support

Is this solving a problem you're hitting @michaelvilensky , or is it just optics?

I have no real objection to this though, so I'm fine for it to go in.

@eparis I'll take this and LGTM it once I understand the use-case.

**Comment by michaelvilensky** [comment]
We are deploying a kubernetes cluster on customers AWS cloud as part of  our solution, we strongly prefer to put a manual name tag to the vpc.
It's also possible to edit the name later, but then kube-down probably won't work.

**Comment by justinsb** [comment]
LGTM

**Comment by zmerlynn** [comment]
This change forgot to add to `config-test.sh` as well, which broke the (already broken) AWS build.

**Pull request merged**
