### PR TITLE
kubelet: Added cadvisor metrics unit test.

### PR DESCRIPTION
**Pull request by bwplotka**
Adding more tests so we can safely update cadvisor and another dependency with new optimizations.

See https://github.com/kubernetes/kubernetes/pull/108194 for the update PR that would love to have those tests in.

Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>

### CODE REVIEW

**Comment by dashpole** [comment]
I think this is a good approach overall.  The only suggestion I have (which you probably already tried) would be to use the prometheus GatherAndCompare testutil to check output, rather than doing text comparrision.

**Comment by ehashman** [comment]
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/component-base/metrics/testutil/testutil.go#L44-L48
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/component-base/metrics/registry_test.go#L370-L382
for reference

**Comment by bwplotka** [comment]
Thanks for the feedback! 

I simplified the test by adding a fake clock - this allows us to avoid some output baking.

>  The only suggestion I have (which you probably already tried) would be to use the prometheus GatherAndCompare testutil to check output, rather than doing text comparison.

Yup, tried, aware of those helpers. There is one problem though:

* In this test we treat kubelet as "closebox/blackbox" that starts and we visit the scrape endpoint. What's great about it - we test it in e2e way. We previously had bug where gatherer was working but scrape not (gatherer was used wrongly in our HTTP handler), so there is no gatherer here.

Added todo to add some utility for this in client_golang: https://github.com/prometheus/client_golang/issues/993 - plus some lints as we have in `component-base` - looks pretty useful

**Comment by bwplotka** [comment]
PTAL @ehashman @dashpole

**Comment by ehashman** [comment]
@dgrisonnet any chance of picking this up in a new PR?

**Comment by dgrisonnet** [comment]
I'll get back to you on that, I need to check how much work is actually needed and asses whether I can take it on my plate or not

**Comment by dgrisonnet** [comment]
@ehashman @dashpole based on https://github.com/kubernetes/kubernetes/pull/108277#issuecomment-1059078389, do we still want to move forward with converting this test to use `GatherAndCompare` instead of text comparison?

**Comment by dashpole** [comment]
Should we use `ScrapeAndCompare` instead?

**Comment by dgrisonnet** [comment]
Yeah it sounds like a better alternative

**Pull request closed without merging**
