### PR TITLE
Rename pod.spec.serviceAccount -> pod.spec.serviceAccountName for v1

### PR DESCRIPTION
**Pull request by liggitt**
Per https://github.com/GoogleCloudPlatform/kubernetes/pull/9688#issuecomment-113329445 and https://github.com/GoogleCloudPlatform/kubernetes/issues/7018#issuecomment-102536924

### CODE REVIEW

**Comment by liggitt** [comment]
@bgrant0607 PTAL

**Comment by bgrant0607** [comment]
Thanks much.

LGTM.

**Comment by erictune** [comment]
@lavalamp

**Comment by erictune** [comment]
If someone creates a pod on a cluster with v19 which uses the old name, then upgrades their cluster to v20 or newer, which uses the new name, what happens?
The restarted apiserver won't have either pod.spec.serviceAccount or pod.spec.serviceAccountName set.

**Comment by erictune** [comment]
@mbforbes

**Comment by erictune** [comment]
If someone updates the pod, then the admission controller will fix it and set the default service account on it.  But, until then, it is broken.  And if was originally not the default one, then it is still broken.

@liggitt

**Comment by erictune** [comment]
@bgrant0607

**Comment by erictune** [comment]
@dchen1107

**Comment by liggitt** [comment]
Pod spec (including service account name) can't mutate on update.

**Comment by erictune** [comment]
Will token controller notice that a pod has no service account and change the pod's volumes?  Or are the volumes only set by the admission controller?

**Comment by erictune** [comment]
As @liggitt said, you can't change the pod spec, so nothing could be changing these pods.
Kubelet only restarts if the ContainerManifest changes.

**Comment by liggitt** [comment]
Previously serialized v1 pods in etcd would deserialize with a blank serviceAccountName, but with their volume mounts intact. Updates wouldn't fail validation. This was not intended to break v1 compatibility (I thought v1 was still being cleaned up when this was requested) but I can't think of a way this would break existing pods. 

Existing replication controllers containing a pod spec are another matter. If someone had set a non default service account and serialized to v1 that would be lost and revert to default when new pods were created from the rc

**Comment by lavalamp** [comment]
As far as I can tell, pods with an empty service account name won't pass validation, no? So they can't ever be updated. Don't the mounts reference secrets which would be forbidden to pods without a service account?

Also does admission do this check for updates? I'd expect not, since you're not allowed to update anything but container images at the moment.

@erictune kubelet's hash includes field names & values, so I'd expect this change should cause kubelet to restart?

**Comment by pmorie** [comment]
@lavalamp the references between pods and secrets via service accounts are
enforced in the admission controller

**Comment by pmorie** [comment]
@erictune

It sounds like there should be a schema migration for this since as
@liggitt points out the pod spec cannot be updated (unless I am missing
something - probably need to look at the code to be positive)

**Comment by liggitt** [comment]
Validation won't fail, the field is optional. Volume mounts won't fail, that's enforced at admission. Not sure about hash changes for the Kubelet.

**Comment by bgrant0607** [comment]
Were service accounts functional enough to be used in 0.19?

**Comment by mbforbes** [comment]
FYI #11355 (origin)

**Comment by bgrant0607** [comment]
The original, documented plan was to go to GKE beta with 0.20.0, to have been cut on 6/19 or 6/22. We actually went to beta with 0.19, which was cut June 9.

Do we expect to be able to update the service account token?

The easiest thing to do would be to add back serviceAccount as a deprecated field and populate each field from the other during conversion.

**Comment by liggitt** [comment]
The failure occurs when the 19.3 client code drops the `serviceAccountName` field (which it didn't know about) round-tripping to do an update, which the API server sees as an attempt to mutate the pod.spec in disallowed ways (details in https://github.com/GoogleCloudPlatform/kubernetes/issues/11355#issuecomment-121810329)

A deprecated `serviceAccount` field that mirrors `serviceAccountName` is the only way to let pre-20.0 clients update pod or replication controllers without losing that field.

**Comment by erictune** [comment]
Kubelet hashes the ContainerManifest.  That won't change, so I would not expect a restart.

**Comment by liggitt** [comment]
Are the kubelet hashes related to mirror pods? If so, mirror pods don't have service accounts or secrets, so this wouldn't be an issue.

**Comment by erictune** [comment]
Kubelet watches pods.  It hashes each ContainerManifest.  It compares that with hash of the ContainerManifest that is currently running.  If the hashes differ, it kills the currently running container and starts the modified one.

**Comment by liggitt** [comment]
ok, the term ContainerManifest threw me... looking at the code, it hashes each `api.Container`, so you're right, the serviceAccountName field in the pod.spec wouldn't affect that

**Comment by bgrant0607** [comment]
Filed #11380.

**Pull request merged**
