### PR TITLE
Refactor kubectl create deploy: isolate obj construction logic

### PR DESCRIPTION
**Pull request by aubm**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

A small refactor, following up the comment from @zhouya0 [on my last PR](https://github.com/kubernetes/kubernetes/pull/90676#issuecomment-629918764).

### CODE REVIEW

**Review by brianpursley — APPROVED** [review]

**Review by soltysh — APPROVED** [review]
/sig cli
/priority backlog
/approve
/lgtm

**Pull request merged**
