### PR TITLE
fix cinder volume dir umount issue #24717

### LINKED ISSUE #24717: cinder volume can't be unmounted when pod is deleted
We noticed that if kubelet's root-dir is a symlink, when pod with a cinder volume is deleted, cinder volume is still mounted even though pod's containers have been removed. The below errors are seen in kubelet log.

```
Apr 23 17:11:34 kubernetes-minion-1-3169 kubelet[31412]: W0423 17:11:34.263560   31412 mount.go:99] could not determine device for path: "/mnt/kubelet/pods/473b273e-0976-11e6-851a-74dbd1a0bde4/volumes/kubernetes.io~cinder/pv-openshift-registry"
Apr 23 17:11:34 kubernetes-minion-1-3169 kubelet[31412]: I0423 17:11:34.263570   31412 cinder.go:354] Directory /mnt/kubelet/pods/473b273e-0976-11e6-851a-74dbd1a0bde4/volumes/kubernetes.io~cinder/pv-openshift-registry is not mounted
Apr 23 17:11:34 kubernetes-minion-1-3169 kubelet[31412]: E0423 17:11:34.263578   31412 kubelet.go:1990] Could not tear down volume "473b273e-0976-11e6-851a-74dbd1a0bde4/pv-openshift-registry": directory /mnt/kubelet/pods/473b273e-0976-11e6-851a-74dbd1a0bde4/volumes/kubernetes.io~cinder/pv-openshift-registry is not mounted
Apr 23 17:11:34 kubernetes-minion-1-3169 kubelet[31412]: I0423 17:11:34.263688   31412 kubelet.go:1901] Orphaned pod "473b273e-0976-11e6-851a-74dbd1a0bde4" found, but volumes are not cleaned up; err: <nil>, volumes: [0xc2082bede0]
```

### PR DESCRIPTION
**Pull request by chengyli**
fix https://github.com/kubernetes/kubernetes/issues/24717
If kubelet root-dir is a symlink, the pod's cinder volume dir can't be
umounted even after pod is deleted.
This patch reads target path of symlink before comparing with entries in
proc mounts.

### CODE REVIEW

**Comment by zhouhaibing089** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount.go#L112 should the `mountPath` here be evaluated as symlinks as well?

**Comment by chengyli** [comment]
@zhouhaibing089 Thanks. Yes, this `mountPath` need do `EvalSymlinks` as well.

**Comment by chengyli** [comment]
Could anyone guide me how to find the detail errors for below FAILURE? 
```
TeamCity OSS :: Kubernetes Mesos :: 4 - Smoke Tests Build 22537 outcome was FAILURE
Summary: Exit code 1 Build time: 00:14:04
```

I can only see below error message in build log, but no much clue 
```
[19:06:36]E:	 [Step 6/6] Step Clean, Build, Kube-Up, Smoke Test, Kube-Down (Command Line) failed
```

**Comment by zhouhaibing089** [comment]
@chengyli you could rebase your code to get a clean test again. I thought the test has failed for a long time, though not the way failed like you met.

**Comment by chengyli** [comment]
@saad-ali any actions reuiqred from my side? And who could help to review the code?

**Comment by saad-ali** [comment]
I'll take a look. CC @kubernetes/sig-storage

**Comment by saad-ali** [comment]
LGTM

**Comment by saad-ali** [comment]
@k8s-bot ok to test

**Comment by chengyli** [comment]
@saad-ali , is the test failure caused by this issue https://github.com/kubernetes/kubernetes/issues/25037?

**Comment by saad-ali** [comment]
Yes, that does appear to be the case.

**Comment by saad-ali** [comment]
@k8s-bot unit test this, Issue #25037

**Comment by saad-ali** [comment]
@k8s-bot test this issue: #25037

**Comment by chengyli** [comment]
@saad-ali , could you please help to merge the pr, thanks!

**Comment by saad-ali** [comment]
It will automatically be merged by the merge-bot. The submit queue is pretty backed up, so it might take a few days.

**Comment by chengyli** [comment]
@saad-ali Got it, thanks!

**Comment by roberthbailey** [comment]
@chengyli I'm merging a bunch of small PRs to clear out the queue. In it goes.

**Pull request merged**
