### PR TITLE
Check all places to break the loop when object found

### PR DESCRIPTION
**Pull request by lixiaobing1**
Check all places to break the loop when object found.

### CODE REVIEW

**Comment by lavalamp** [comment]
ok to test

**Comment by lavalamp** [comment]
It looks like in all of these places you can remove the found variable completely and just return early.

**Comment by liggitt** [comment]
@lavalamp I think the test functions are making sure the rule slices match exactly

**Comment by lixiaobing10051267** [comment]
@lavalamp yes, it looks like, but actually the variable  "found" need to be used next:

	for _, expectedRule := range expectedRules {
		found := false
		for _, actualRule := range actualRules {
			if reflect.DeepEqual(expectedRule, actualRule) {
				found = true
			}
		}

		if !found {
			return false
		}
	}

	return true

**Pull request merged**
