### PR TITLE
CHANGELOG: add a hyperlink to issue 86282

### PR DESCRIPTION
**Pull request by chymy**
Signed-off-by: chymy <chang.min1@zte.com.cn>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/triage accepted
/priority important-longterm
/lgtm

@chymy could you add a `NONE` release note here?

**Comment by chymy** [comment]
> /triage accepted
> /priority important-longterm
> /lgtm
> 
> @chymy could you add a `NONE` release note here?

@hasheddan thanks for review. Added.

**Pull request merged**
