### PR TITLE
[feature branch] Support cross group conversion in apply

### PR DESCRIPTION
**Pull request by jennybuckley**
**What type of PR is this?**
/kind feature
/sig api-machinery

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

@apelisse

### CODE REVIEW

**Comment by apelisse** [comment]
/hold

is this wip?

**Comment by apelisse** [comment]
oops, too late

**Comment by jennybuckley** [comment]
It was wip when I made the PR but when it merged it was done, I just forgot to change the name

**Pull request merged**
