### PR TITLE
Remove misleading case of volume scheduling

### PR DESCRIPTION
**Pull request by lichuqiang**
**What type of PR is this?**
/kind flake
/sig storage
/sig scheduling

**What this PR does / why we need it**:
remove misleading case of volume scheduling

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Partially address #70180 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lichuqiang** [comment]
I've been deeply impressed by the understanding that a prebound pv would be protected and won't be bound to other pvcs.
But took a closer look at the code, I realized that neither prebound pvs nor prebound pvcs are guaranteed.
So the removed prebound case should be a misleading.
I ran the test for hundreds of times after update, and did not see the failure. 

/assign @msau42

**Comment by msau42** [comment]
Hm that's surprising to me too.  If a PV is prebound and meets all the criteria, ie capacity, storageclass, etc, then it should be matched to the PVC because we always iterate through all PVs first before deciding to provision

**Comment by lichuqiang** [comment]
> If a PV is prebound and meets all the criteria, ie capacity, storageclass, etc, then it should be matched to the PVC because we always iterate through all PVs first before deciding to provision

I meant I was thinking we have protection for prebound pvs in [findMatchingVolume](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/index.go#L99), and won't get them bound to other pvcs, which is indeed not the case.

**Comment by msau42** [comment]
Sorry, I still don't understand. Can you give an example?

**Comment by lichuqiang** [comment]
I mean I thought in [findMatchingVolume](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/index.go#L99), it would preserve the preboud pv for its pvc, i.e. when it find a pv is prebound to another pvc, it should skip it. But in fact a prebound has chance to be bound to another pvc, if only the pvc comes in first, and meets all the criteria.

e.g. pv-A is prebound to pvc-A, but pvc-B step into [findMatchingVolume](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/index.go#L99) first (the two pvcs are of same criteria), it would consider pv-A available for pvc-B

**Comment by lichuqiang** [comment]
Sorry, forget that. I ignored the guarantee [here in the  findMatchingVolume](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/index.go#L219), so it should not be the issue I mentioned above.

And I added some log for digging. I found that when it failed, the scheduler keeps trying binding with out-of-date pv instance:

```
E1116 17:32:56.088473   44673 scheduler.go:552] error binding volumes: error: Operation cannot be fulfilled on persistentvolumes "pv-w-prebound": the object has been modified; please apply your changes to the latest version and try again
```
The pv has already been bound, but that cached in scheduler was not up-to-date:
```
--- pv in apiserver: &PersistentVolume{...Name:pv-w-prebound,...ResourceVersion:10526,...Status:PersistentVolumeStatus{Phase:Bound,Message:,Reason:,},}

--- pv in cache: &PersistentVolume{...Name:pv-w-prebound,...ResourceVersion:10524,...Status:PersistentVolumeStatus{Phase:Available,Message:,Reason:,},}
```

**Comment by liggitt** [comment]
So it sounds like this is still a valid case to test?

/hold

**Comment by msau42** [comment]
Correct, this pr should not merge

**Comment by cofyc** [comment]
It seems like another race condition in scheduler volume binding, I'm investigating it.

**Comment by lichuqiang** [comment]
FYI: I did some trial to find the root cause:
1. extend the waiting time [here in the test](https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler/volume_binding_test.go#L800), to see if scheduler is able to get cache synced later.
And I found that scheduler would only retry scheduling the pod for 3 times in a second, and will never  re-enqueue the pod in the rest of time.
And took a closer look at the code, on binding failure, [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler.go#L407) we retry scheduling by updating the pod status. But the condition contents are always the same, so I guess it will only trigger pod re-enqueue for the first time. That's why we failed to see pod rescheduled later. @msau42 Is this by design?

2. According to what I saw above, here is a wild guess of what happened on test failure: the scheduler has not been up-to-date upon the first few scheduling, its cache got updated later, but we won't trigger rescheduling then.
As a confirmation, I add a timestamp [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler.go#L403) when constructing the condition content, to ensure the update will trigger rescheduling.
After the change, the pod keeps getting rescheduled as expect, but the cached pv never get synced.
The test still has chance to fail.
So the reschedule issue should be another story, and still not the root cause of test flaking here.

**Comment by cofyc** [comment]
> According to what I saw above, here is a wild guess of what happened on test failure: the scheduler has not been up-to-date upon the first few scheduling.

Adding some logs to print object versions, I found `bindAPIUpdate` will make api calls for old objects. It's because prebound PV may be updated to `Bound` by PV controller, in next run, scheduler binder will not try to bind it. But stale pod binding of this volume is not cleared, BindPodVolumes will try to bind it and fail. I opened a PR to address this #71212.

**Comment by msau42** [comment]
> I found that scheduler would only retry scheduling the pod for 3 times in the first second, and will never re-enqueue the pod in the rest of time.
And took a closer look at the code, on binding failure, here we retry scheduling by updating the pod status. But the condition contents are always the same, so I guess it will only trigger pod re-enqueue for the first time. That's why we failed to see pod rescheduled later.

@bsalamat can you take a look at the Pod condition update above and see if we are correctly updating the Pod to cause it to retry scheduling?

**Comment by bsalamat** [comment]
@msau42 @lichuqiang It is true that updating pod status of an unschedulable pod, does not trigger a scheduler retry. The rationale behind this logic was that a pod status change does not make an unschedulable pod schedulable and there should be other changes in the cluster to trigger a reschedule. For example, a node update, etc.

**Comment by msau42** [comment]
Thanks for the confirmation. We do move the pod to active queue for on [pvc/pv add/update and storageclass add](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/scheduler/factory/factory.go#L497).  It may be good to add some integration tests for these scenarios.

**Pull request closed without merging**
