### PR TITLE
Skip tests when no signal emitting command

### LINKED ISSUE #107343: [Failing test] [sig-node] GracefulNodeShutdown [Serial] [NodeFeature:GracefulNodeShutdown] [NodeFeature:GracefulNodeShutdownBasedOnPodPriority] when gracefully shutting down after restart dbus, should be able to gracefully shutdown
##### Error text:
```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_shutdown_linux_test.go:163
Unexpected error:
    <*errors.errorString | 0xc0014d24e0>: {
        s: "failed to run \"sh -c dbus-send --system /org/freedesktop/login1 org.freedesktop.login1.Manager.PrepareForShutdown boolean:true\": exit status 127 (sh: line 1: dbus-send: command not found\n)",
    }
    failed to run "sh -c dbus-send --system /org/freedesktop/login1 org.freedesktop.login1.Manager.PrepareForShutdown boolean:true": exit status 127 (sh: line 1: dbus-send: command not found
    )
occurred
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_shutdown_linux_test.go:166
```
#### Recent failures:
[1/5/2022, 1:43:54 AM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1478663515207110656)
[1/4/2022, 9:43:54 PM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1478603115933470720)
[1/4/2022, 5:44:00 PM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1478542716957626368)
[1/4/2022, 1:43:33 PM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1478482230207582208)
[1/4/2022, 9:43:05 AM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1478421673387495424)

Failing on cri-o serial job.

Looks like the dbus command isn't available for graceful shutdown tests that aren't running on Ubuntu.

/assign @wzshiming 

/kind failing-test

/sig node

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?

/kind failing-test

#### Which issue(s) this PR fixes:

Fixes #107343

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]

**Comment by bobbypage** [comment]
Thanks for following up with fix!

/lgtm

**Pull request merged**
