### PR TITLE
Skip tests when no signal emitting command

### LINKED ISSUE #107343: [Failing test] [sig-node] GracefulNodeShutdown [Serial] [NodeFeature:GracefulNodeShutdown] [NodeFeature:GracefulNodeShutdownBasedOnPodPriority] when gracefully shutting down after restart dbus, should be able to gracefully shutdown
##### Error text:
```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_shutdown_linux_test.go:163
Unexpected error:
    <*errors.errorString | 0xc0014d24e0>: {
        s: "failed to run \"sh -c dbus-send --system /org/freedesktop/login1 org.freedesktop.login1.Manager.PrepareForShutdown boolean:true\": exit status 127 (sh: line 1: dbus-send: command not found\n)",
    }
    failed to run "sh -c dbus-send --system /org/freedesktop/login1 org.freedesktop.login1.Manager.PrepareForShutdown boolean:true": exit status 127 (sh: line 1: dbus-send: command not found
    )
occurred
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_shutdown_linux_test.go:166
```
#### Recent failures:
[1/5/2022, 1:43:54 AM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1478663515207110656)
[1/4/2022, 9:43:54 PM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1478603115933470720)
[1/4/2022, 5:44:00 PM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1478542716957626368)
[1/4/2022, 1:43:33 PM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1478482230207582208)
[1/4/2022, 9:43:05 AM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1478421673387495424)

Failing on cri-o serial job.

Looks like the dbus command isn't available for graceful shutdown tests that aren't running on Ubuntu.

/assign @wzshiming 

/kind failing-test

/sig node

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?

/kind failing-test
/sig node

#### Which issue(s) this PR fixes:

Fixes #107343

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by ehashman** [comment]
>  W0106 04:00:20.908] 	panic: regexp: Compile(`\[Flaky\]|\[Benchmark\]|\[NodeSpecialFeature:.+\]|\[NodeSpecialFeature\]|\[NodeAlphaFeature:.+\]|\[NodeAlphaFeature\]|\[NodeFeature:Eviction\]|[\NodeFeature:DevicePluginProbe\]`): error parsing regexp: invalid escape sequence: `\N` 

let's get that fixed... oops

**Comment by bobbypage** [comment]
/lgtm

as long term fix, maybe it makes since to switch to `busctl` which is part of systemd and I think is more cross platform across COS, ubuntu and fedora as compared to `dbus-send`

**Comment by wzshiming** [comment]
https://www.freedesktop.org/software/systemd/man/busctl.html

```
busctl --system emit /org/freedesktop/login1 org.freedesktop.login1.Manager PrepareForShutdown b true
```

Tested on Ubuntu 19 and it should be working without error, I returned to the Centos 7 test, that `busctl` did not `emit` command. or we should add more cases to find out if `gdbus`, `dbug-send`, `busctl` exist, and use whichever exists

```
dbus-send --system /org/freedesktop/login1 org.freedesktop.login1.Manager.PrepareForShutdown boolean:true
```

```
gdbus emit --system --object-path /org/freedesktop/login1 --signal org.freedesktop.login1.Manager.PrepareForShutdown true
```

**Comment by SergeyKanzhelev** [comment]
Are test failures legit?

/retest
/assign

**Comment by bobbypage** [comment]
I filed https://github.com/kubernetes/kubernetes/issues/107505 to track improvement as per https://github.com/kubernetes/kubernetes/pull/107361#issuecomment-1006987130 and https://github.com/kubernetes/kubernetes/pull/107361#issuecomment-1007094774

**Review by SergeyKanzhelev — APPROVED** [review]
/skip

failures seems to be not-relevant

/lgtm
/approve

**Pull request merged**
