### PR TITLE
Fix invalid anchors in CHANGELOG.md

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Some stale stuff are left in CHANGELOG.md and there are some anchors invalid.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Introduced by: #53750

**Special notes for your reviewer**:
/cc @dchen1107 

**Release note**:

```release-note
My release note.
```

### CODE REVIEW

**Comment by cblecker** [comment]
I think this will change/conflict with #53761

**Comment by xiangpengzhao** [comment]
@cblecker correct. #53761 will remove the detailed contents of release notes in CHANGELOG.md.
/close
in favor of it.

**Comment by xiangpengzhao** [comment]
[test]
/release-note

**Comment by xiangpengzhao** [comment]
/reopen
for testing.

**Comment by xiangpengzhao** [comment]
/reopen
for testing.

**Pull request closed without merging**
