### PR TITLE
Remove unnecessary loop for calculating expectedCount

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
DisruptionController#getExpectedScale currently uses standalone loop to calculate expectedCount.
This is not needed.

This PR folds the calculation into the main loop.

```release-note
NONE
```

### CODE REVIEW

**Comment by tedyu** [comment]
ping @derekwaynecarr @janetkuo for review

**Comment by tedyu** [comment]
ping @janetkuo

**Comment by tedyu** [comment]
@mikedanese
Can you take a look ?

**Comment by tedyu** [comment]
ping @janetkuo for review

**Comment by mikedanese** [comment]
This doesn't help with readability of the code.

**Comment by tedyu** [comment]
@mikedanese 
I read the change again.
It seems the computation around expectedCount is still straightforward after the re-write.

Do you think adding comment above the computation would make the change more understandable ?

**Pull request closed without merging**
