### PR TITLE
forbid service account to bind to rolebinding in different namespace

### PR DESCRIPTION
**Pull request by xilabao**

### CODE REVIEW

**Comment by ncdc** [comment]
@deads2k @liggitt

**Comment by liggitt** [comment]
The ability to grant permissions to a service account from another namespace is intentional

**Comment by xilabao** [comment]
@liggitt  I don't understand why need to do that.  IMO, clusterrolebinding can work well for serviceaccount to across the namespace. Could you give some tips?

**Comment by liggitt** [comment]
Cluster role binding grants a role across all namespaces. Rolebindings only grant a role within a particular namespace.

**Pull request closed without merging**
