### PR TITLE
Fix CHANGELOG-1.22.md: Cluster Storage Interface -> Container Storage…

### PR DESCRIPTION
**Pull request by bells17**
#### What type of PR is this?

/kind cleanup
/kind documentation
/sig storage

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bells17** [comment]
For approval
/assign @cici37

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
