### PR TITLE
Fix OpenShift example

### LINKED ISSUE #4997: Example running OpenShift Origin on Kubernetes was prematurely merged
This PR was prematurely merged:
https://github.com/GoogleCloudPlatform/kubernetes/pull/4591

Need to update the PR based on the actual steps that were needed to get what was demonstrated at the public Kubernetes meet-up last week.

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Fixes https://github.com/GoogleCloudPlatform/kubernetes/issues/4997

This example requires OpenShift merges: https://github.com/openshift/origin/pull/2015

I think an interesting use case driven from this example is the common need to take a set of files and bundle them into a secret.  We have an experimental command that does this in OpenShift, but it is useful, and would be probably of general value to Kubernetes.

/cc @smarterclayton you should hopefully see this is much simpler now.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Another use case brought up by this:

It's very difficult to use TLS on service accounts today.  The signer cert has to be kept separate from the infrastructure, you have to generate the cert after the service is created (to get both the DNS name and the portalIP), and it's a lot of manual steps.

After seeing how we could do auto secret generation from the service account, I'm inclined to replicate that solution for service certificates.

A user in a namespace would create a secret with a name or annotation matching a service name and a secret.type "ServiceTLSCertificate".  A controller (that has access to a signing cert for a CA that pods in the cluster can trust) would see that secret was created and fill out a cert for the service portalIP and DNS named by the secret's annotation.  Any pods in that service could then mount that secret and have a cert automatically generated.  The consumers of the service could get the CA for the service from DNS (which could automatically add the CA to DNSSEC via skydns).

**Comment by derekwaynecarr** [comment]
Any chance we can merge this now?  

https://github.com/openshift/origin/pull/2055 merged so the updated Docker images should have no more problems doing WATCH against Kubernetes resources.

**Comment by smarterclayton** [comment]
Stop breaking travis

**Comment by smarterclayton** [comment]
Boilerplate is wrong

**Comment by derekwaynecarr** [comment]
Just like @eparis to change boilerplate text and mess up my PRs, this should be all set now ;-)

**Comment by smarterclayton** [comment]
LGTM, will merge on green

**Comment by eparis** [comment]
I like stomping on people's PRs!

**Comment by smarterclayton** [comment]
All known flakes.

**Pull request merged**
