### PR TITLE
Don't allow image pulls to race with image removes.

### PR DESCRIPTION
**Pull request by vmarmol**
This is to keep docker/docker#8926 from occuring.

### CODE REVIEW

**Comment by rjnagal** [comment]
LGTM

**Comment by dchen1107** [comment]
hmm, we shouldn't run into docker/docker#8926  at all since we are not using dangling=true to do image GC a while back. See #3642 and related issues (#3617,#3611, and #3393) for detail analysis I did. 

Also in this PR, you are using pulllock to protect removing the old dead container layer. not images pulling from github, which shouldn't have race at all. Did you observe any race here?

**Comment by vmarmol** [comment]
After further discussion we realized we won't run into this issue since we don't remove images today. Will replace this PR with one that removed pullLock instead.

**Pull request closed without merging**
