### PR TITLE
[VDF] Normalize container image references to k8s.gcr.io

### PR DESCRIPTION
**Pull request by justaugustus**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

- Remove references to `us.gcr.io/k8s-artifacts-prod`
- Remove references to `gcr.io/google-containers` 

Part of the VDF (Vanity Domain Flip): https://github.com/kubernetes/release/issues/270

/assign @dims @liggitt 
cc: @kubernetes/release-engineering @listx 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

There are still some references to cleanup and possibly a few files to regenerate.
/hold until we get the all-clear from @listx on Friday (7/24) that the VDF is complete

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by justaugustus** [comment]
Odd. The [`pull-kubernetes-cross` job failure](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93356/pull-kubernetes-cross/1286033140258705411/) for example:

```
 W0722 20:21:02.646] Step 1/16 : FROM k8s.gcr.io/build-image/kube-cross:v1.14.6-1
W0722 20:21:02.647] manifest for k8s.gcr.io/build-image/kube-cross:v1.14.6-1 not found: manifest unknown: Failed to fetch "v1.14.6-1" from request "/v2/build-image/kube-cross/manifests/v1.14.6-1".
W0722 20:21:02.647] 
W0722 20:21:02.647] To retry manually, run:
W0722 20:21:02.647] 
W0722 20:21:02.647] docker build -t kube-build:build-1a7ee6bd3d-5-v1.14.6-1 --pull=false /workspace/k8s.io/kubernetes/_output/images/kube-build:build-1a7ee6bd3d-5-v1.14.6-1
W0722 20:21:02.647] 
W0722 20:21:02.652] !!! [0722 20:21:02] Call tree:
W0722 20:21:02.654] !!! [0722 20:21:02]  1: build/release.sh:35 kube::build::build_image(...)
W0722 20:21:02.655] make: *** [Makefile:406: release] Error 1
W0722 20:21:02.656] Traceback (most recent call last):
W0722 20:21:02.656]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 50, in <module>
W0722 20:21:02.656]     main(ARGS.env, ARGS.cmd + ARGS.args)
W0722 20:21:02.657]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 41, in main
W0722 20:21:02.657]     check(*cmd)
W0722 20:21:02.657]   File "/workspace/./test-infra/jenkins/../scenarios/execute.py", line 30, in check
W0722 20:21:02.657]     subprocess.check_call(cmd)
W0722 20:21:02.657]   File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
W0722 20:21:02.658]     raise CalledProcessError(retcode, cmd)
W0722 20:21:02.658] subprocess.CalledProcessError: Command '('make', 'release')' returned non-zero exit status 2
E0722 20:21:02.662] Command failed
I0722 20:21:02.662] process 690 exited with code 1 after 0.0m 
```

and that image definitely exists:

```
$ skopeo inspect docker://k8s.gcr.io/build-image/kube-cross:v1.14.6-1
{
    "Name": "k8s.gcr.io/build-image/kube-cross",
    "Digest": "sha256:268c0a52333449a4e0a10847149ea3d3d1c31ed32552c4269a7a7edc1cd0e908",
    "RepoTags": [
        "v1.12.12-1",
        "v1.12.17-1",
        "v1.12.17-2",
        "v1.13.12-2",
        "v1.13.13-1",
        "v1.13.13-2",
        "v1.13.14-1",
        "v1.13.6-1",
        "v1.13.8-1",
        "v1.13.9-1",
        "v1.13.9-2",
        "v1.13.9-3",
        "v1.13.9-4",
        "v1.13.9-5",
        "v1.14.1-1",
        "v1.14.2-1",
        "v1.14.2-2",
        "v1.14.2-3",
        "v1.14.2-4",
        "v1.14.3-1",
        "v1.14.4-1",
        "v1.14.4-2",
        "v1.14.5-1",
        "v1.14.5-2",
        "v1.14.6-1",
        "v1.15.0-beta.1-1"
    ],
    "Created": "2020-07-17T17:55:07.031282608Z",
    "DockerVersion": "19.03.8",
    "Labels": null,
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:e9afc4f90ab09248d75c8081b6dfba749a7f7efdac704ced7e0ceb506e02fa4a",
        "sha256:989e6b19a265d6b8b7934e7ddd7dc07f6e2fc945b3a28dda9b8aecb12cdb30e0",
        "sha256:af14b6c2f8785723bceb5964c5dec1f0489b7750e9d4ec671e49bfba15d80a39",
        "sha256:5573c4b3094956931fd68c310ae92c9eb1a787f0c77ac2730be9d16cce172d5e",
        "sha256:d4020e2aa747ca4d0ca2e87305f22f089fd57a696fd19bfa30182316d51b089a",
        "sha256:abca02d9b2370f6aa65d8da107f760cdd339938a8683dcb5a0fbba6669bb95c2",
        "sha256:0d6cba09e61d563b719356cd7d33f4256a32f419bd9af7e02a6643c91c0ac833",
        "sha256:989d0db68ee0279ac27b7807a53de706445cf59c5a56c49dcfa65abe96e1cbee",
        "sha256:77497207ddddbe39c4c249627962478945cf53c12f509bda83bc44e3e501f780",
        "sha256:d117fbc127b589d5eb190d93714c8855a8207ebaabcd2a378b8ebebb3832e00f",
        "sha256:6ae60386119e9545280eb8f2f0cc82e2d29ffbcbba30cc7786d5aec85ba18f5f",
        "sha256:bb8c369bb17787eedede9131ef14c68a8a2974592ee70ca4d31adb7ea42e8009",
        "sha256:52fc6f0f3b7940210b052f9ded7351c476341046bf8899a4acc5433adc9e944b",
        "sha256:f60181b5d50a0b5419d8d9b2c96c0877120634b0d6a5c4494d283be42bc59976",
        "sha256:b5da32f7aa33cd6d43ebb438273cb5ef83a88886d42a7f1f36d4a2231467b759"
    ],
    "Env": [
        "PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "GOLANG_VERSION=1.14.6",
        "GOPATH=/go",
        "GOARM=7",
        "KUBE_DYNAMIC_CROSSPLATFORMS=armhf   arm64   s390x   ppc64el",
        "KUBE_CROSSPLATFORMS=linux/386   linux/arm linux/arm64   linux/ppc64le   linux/s390x   darwin/amd64 darwin/386   windows/amd64 windows/386",
        "ZIPNAME=protoc-3.0.2-linux-x86_64.zip",
        "TMPDIR=/tmp.k8s"
    ]
}
```

/retest

**Comment by listx** [comment]
@justaugustus VDF is still in progress. Meanwhile, we cannot reliably use k8s.gcr.io to refer to images that only exist in k8s-artifacts-prod. That is, the k8s.gcr.io domain is only reliable to refer to images in google-containers. The image here (build-image/kube-cross:v1.14.6-1) is only in k8s-artifacts-prod, not google-containers (us.gcr.io/google-containers/build-image/kube-cross:v1.14.6-1 comes up empty) --- so this is not surprising.

**Comment by justaugustus** [comment]
@listx -- Yep! I should've mentioned in the description that I don't plan to do anything merge-wise here until we get the all-clear from you on Friday. Will run through retesting and fixing up any remaining references then.

**Comment by justaugustus** [comment]
/hold cancel
(The VDF is complete)

**Comment by justaugustus** [comment]
All good, let it fly!
/hold cancel

**Pull request merged**
