### PR TITLE
Automated cherry pick of #122027: Don't sort under lock

### PR DESCRIPTION
**Pull request by wojtek-t**
Cherry pick of #122027 on release-1.28.

#122027: Don't sort under lock

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fixes a 1.27 performance regression watchcache to fix kube-apiserver scalability under heavy load of list requests
```

### CODE REVIEW

**Comment by jpbetz** [comment]
/approve
Since this can be a significant performance regression for real world clusters

**Comment by wojtek-t** [comment]
@kubernetes/release-managers - for cherrypick approval

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
