### PR TITLE
Automated cherry pick of #38836 #39114 #39059 upstream release 1.4

### LINKED ISSUE #38322: Memory pressure shouldn't hard evict static pods
If a node runs out of memory, we kill something. Then if there is memory pressure, we don't admit best effort (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/eviction_manager.go#L110). Maybe we can admit static-pods, even if they're best effort? 

@kubernetes/sig-node if we can't differentiate static from non-static, maybe we can use the `scheduler.alpha.kubernetes.io/critical-pod` annotation?

### PR DESCRIPTION
**Pull request by dchen1107**
Fixed #38322

**Release note**:

```
* Kubelet admits critical pods including kube-proxy even under memory pressure
* Make critical pods have the same oom score as the guaranteed pods
* Stop evicting static pods
```

### CODE REVIEW

**Comment by jessfraz** [comment]
I think there were some problems with the cherry-pick I can look into them if you dont have time

**Comment by jessfraz** [comment]
never mind just saw the new commit :)

**Comment by dchen1107** [comment]
@jessfraz Sorry for another push. It requires a lot of manual effort to resolve those conflicts. :-(

**Comment by jessfraz** [comment]
no worries thanks for taking the time!

**Comment by dchen1107** [comment]
node e2e issue is caused by dockerized node e2e (https://github.com/kubernetes/kubernetes/issues/39597).

**Comment by jessfraz** [comment]
merged #39632 so this should pass now

**Comment by jessfraz** [comment]
@k8s-bot test this please

**Comment by jessfraz** [comment]
@k8s-bot cvm gce e2e test this

**Comment by jessfraz** [comment]
@k8s-bot verify test this

**Comment by dchen1107** [comment]
https://github.com/kubernetes/kubernetes/pull/39632 was merged which should fix dockerized node-e2e test.

**Comment by jessfraz** [comment]
@k8s-bot test this please

**Comment by jessfraz** [comment]
all green merging

**Pull request merged**
