### PR TITLE
e2e: improve failure handling

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The code was unnecessarily complex (intercepting panics without anyone using that).

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
/hold

There is code in https://github.com/kubernetes/kubernetes/blob/6e31c6531fbb83088d472e7a5680add214060967/test/e2e/upgrades/upgrade_suite.go#L68-L96 which does something with these special panics.

I don't think that code works in all cases (for example, when Ginkgo itself discovers a failure, which is possible now, or when when some test doesn't use the skipper helper package). We need to figure out what that upgrade test really needs to do and how to do it reliably.

**Comment by pohly** [comment]
/hold cancel

I removed that code from [upgrade_suite.go](https://github.com/kubernetes/kubernetes/blob/6e31c6531fbb83088d472e7a5680add214060967/test/e2e/upgrades/upgrade_suite.go#L68-L96) because the result wasn't used anywhere.

**Comment by pohly** [comment]
/assign @aojea 

Can you perhaps review?

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
