### PR TITLE
Fix repeatedly aquire the inhibit lock

### LINKED ISSUE #98087: GracefulNodeShutdown Repeatedly aquire the inhibit lock
**What happened**:

image

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 7
- Kernel (e.g. `uname -a`):  Linux zsm-test-2 3.10.0-1160.11.1.el7.x86_64 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by wzshiming**
**What type of PR is this?**
/kind bug
/sig node

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #98087

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubelet: Fix repeatedly acquiring the inhibit lock
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by bobbypage** [comment]
@wzshiming can you please provide some more info on how you got into the state where kubelet obtained more than one inhibit lock?

As far as I understand, Kubelet should only acquire the inhibit lock here on startup

https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L132

and here

https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L160-L163

if `isShuttingDown == false` (a pending shutdown was cancelled). However, the inhibitLock should be released by `processShutdownEvent`:

https://github.com/kubernetes/kubernetes/blob/af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L251-L252

and `processShutdownEvent` is called in the loop above and should be a blocking call (i.e. I would expect before any shutdown events to be processed for  `processShutdownEvent` to return, thus ensuring that `aquireInhibitLock` is only acquired if existing one is released).

**Comment by wzshiming** [comment]
Run it many times `gdbus emit --system --object-path /org/freedesktop/login1 --signal org.freedesktop.login1.Manager.PrepareForShutdown false`.
`aquireInhibitLock ` is called multiple times, causing the inhibitLock to leak.

**Comment by bobbypage** [comment]
> Run it many times `gdbus emit --system --object-path /org/freedesktop/login1 --signal org.freedesktop.login1.Manager.PrepareForShutdown false`.
> `aquireInhibitLock ` is called multiple times, causing the inhibitLock to leak.

Got it, thanks. That's because we call `aquireInhibitLock` if `PrepareForShutdown false` event is received with the assumption that a prior `PrepareForShutdown == true` event was sent in the past. But if you send it manually like that or due to whatever reason `PrepareForShutdown == true`, wasn't sent before we will incorrectly aquire another inhibit lock.

I think it should be fine to release the inhibit lock if it's already acquired as you proposed.

**Pull request merged**
