### PR TITLE
Automated cherry pick of #51279 upstream release 1.7

### LINKED ISSUE #56653: fluentd-gcp throwing errors "No such file or directory"
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
After upgrading to k8s 1.7.10 I am seeing these errors

`fluentd-gcp: 2017-11-30 23:34:35 +0000 [warn]: emit transaction failed: error_class=Errno::ENOENT error="No such file or directory @ sys_fail2 - (/var/log/fluentd-buffers/kubernetes.containers.buffer..b55f3b6683f4036be.log, /var/log/fluentd-buffers/kubernetes.containers.buffer..q55f3b6683f4036be.log)"`

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.10
- Cloud provider or hardware configuration: Google GKE
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by janetkuo**
Cherrypick #51279 to 1.7 
Fixes #56653

### CODE REVIEW

**Comment by janetkuo** [comment]
@wojtek-t would you cherrypick-approve this one?

**Comment by wojtek-t** [comment]
@janetkuo - cherrypick approved (though I would prefer someone else to lgtm this one).
[BTW - I slightly rephrased the release note in the original PR, to make it a bit more user-oriented]

**Review by kow3ns — APPROVED** [review]

**Pull request merged**
