### PR TITLE
Update replication-controller.md

### PR DESCRIPTION
**Pull request by ttomsu**
Replaces Asgard reference (now deprecated) with Spinnaker reference (the replacement project)

### CODE REVIEW

**Comment by ttomsu** [comment]
What is k8s-merge-robot and why is it continually opening and closing this
pr?

On Thu, Dec 10, 2015 at 2:33 PM, k8s-merge-robot <notifications@github.com>
wrote:

> Travis continuous integration appears to have missed, closing and
> re-opening to trigger it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/18085#issuecomment-163726789>
> .
>



-- 
Travis Tomsu | Software Engineer | ttomsu@google.com | 614-205-9258

**Comment by wojtek-t** [comment]
@k8s-bot ok to test

**Comment by bprashanth** [comment]
@ixdy (only because I'm not sure who'd want to take a look) is the robot busted? It's left ~200 comments on a oneline doc pr.

**Comment by eparis** [comment]
I removed LGTM, not because this doesn't LGTM, but because the bot is going stupid. On monday I'll work with oncall to get it merged.  (The bot screws up PRs for gh-pages and won't ever merge them  :-()

**Comment by ttomsu** [comment]
Ping.

**Comment by bprashanth** [comment]
@k8s-bot unit test this please

**Comment by bprashanth** [comment]
This one line doc change has been put through enough.

**Pull request merged**
