### PR TITLE
fixed problem with non masquerade cidr in kube-up gce/gci

### PR DESCRIPTION
**Pull request by tommywo**
**What this PR does / why we need it**:
fixed typo in script which made setting custom cidr in gce using kube-up impossible

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #

**Special notes for your reviewer**:

**Release note**:

``` release-note
fixed typo in script which made setting custom cidr in gce using kube-up impossible
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35267)

### CODE REVIEW

**Comment by tommywo** [comment]
@eparis can you re-assign it to @k8s-merge-robot

**Comment by eparis** [comment]
why would I do that?

**Comment by eparis** [comment]
@k8s-bot test this

**Comment by tommywo** [comment]
@eparis `i just thought this is how @k8s-merge-robot works. Nevermind ;)

**Pull request merged**
