### PR TITLE
CHANGELOG: Update CHANGELOG-1.18.md

### PR DESCRIPTION
**Pull request by justaugustus**
**What type of PR is this?**
/kind cleanup documentation

**What this PR does / why we need it**:
- Manual splice of notes for `v1.18.0-alpha.5`
  Captures notes from a commit immediately prior to `v1.18.0-alpha.3`
  (which was tagged detached from master)
- Add note about `v1.18.0-alpha.4` being manually tagged
- Remove "Changes by Kind" headings
- Regenerate TOC

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

/assign @saschagrunert @cpanato 
cc: @kubernetes/release-engineering 
ref: https://github.com/kubernetes/sig-release/issues/985

**Special notes for your reviewer**:
Command run to generate these notes:
```shell
$ go run cmd/release-notes/main.go \
--start-sha a71586fac6007382db1c1dbe1ea192d4b21a0dde \
--end-sha 6541758fd4d9fc375839a484a7e03c189b05ce3d \
--debug
```

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

thanks for update this 🎉

**Comment by saschagrunert** [comment]
/test pull-kubernetes-e2e-gce

```
I0213 15:32:15.623] Latency metrics for node e2e-1cc9cb20cc-674b9-minion-group-g1km
I0213 15:32:15.623] Feb 13 15:32:15.209: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
I0213 15:32:15.624] STEP: Destroying namespace "persistent-local-volumes-test-5276" for this suite.
I0213 15:32:15.624] 
I0213 15:32:15.624] 
I0213 15:32:15.624] • Failure [205.344 seconds]
I0213 15:32:15.624] [sig-storage] PersistentVolumes-local 
I0213 15:32:15.624] test/e2e/storage/utils/framework.go:23
I0213 15:32:15.624]   [Volume type: dir-link]
I0213 15:32:15.624]   test/e2e/storage/persistent_volumes-local.go:188
I0213 15:32:15.625]     Two pods mounting a local volume at the same time
I0213 15:32:15.625]     test/e2e/storage/persistent_volumes-local.go:244
I0213 15:32:15.625]       should be able to write from pod1 and read from pod2 [It]
I0213 15:32:15.625]       test/e2e/storage/persistent_volumes-local.go:245
I0213 15:32:15.625] 
I0213 15:32:15.625]       Feb 13 15:31:57.527: Unexpected error:
      
I0213 15:32:15.625]           <*errors.errorString | 0xc0030f9c50>: {
I0213 15:32:15.626]               s: "pod \"security-context-b2ba2cfb-625c-4158-be77-f107c0ca942f\" is not Running: timed out waiting for the condition",
I0213 15:32:15.626]           }
I0213 15:32:15.626]           pod "security-context-b2ba2cfb-625c-4158-be77-f107c0ca942f" is not Running: timed out waiting for the condition
I0213 15:32:15.626]       occurred
I0213 15:32:15.626] 
I0213 15:32:15.626]       test/e2e/storage/persistent_volumes-local.go:713
I0213 15:32:15.626] ------------------------------
I0213 15:32:15.627] {"msg":"FAILED [sig-storage] PersistentVolumes-local  [Volume type: dir-link] Two pods mounting a local volume at the same time should be able to write from pod1 and read from pod2","total":-1,"completed":15,"skipped":58,"failed":1,"failures":["[sig-storage] PersistentVolumes-local  [Volume type: dir-link] Two pods mounting a local volume at the same time should be able to write from pod1 and read from pod2"]}
```

**Pull request merged**
