### PR TITLE
hide deprecated commands

### PR DESCRIPTION
**Pull request by xilabao**
**What this PR does / why we need it**:
```
# kubectl --help
......
Deploy Commands:
  rollout        Manage a deployment rollout
  rolling-update Perform a rolling update of the given ReplicationController
  rollingupdate  Perform a rolling update of the given ReplicationController
  scale          Set a new size for a Deployment, ReplicaSet, Replication Controller, or Job
  resize         Set a new size for a Deployment, ReplicaSet, Replication Controller, or Job
  autoscale      Auto-scale a Deployment, ReplicaSet, or ReplicationController
......
```
**Which issue this PR fixes**: 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xilabao** [comment]
cc @soltysh @dshulyak

**Comment by soltysh** [comment]
@xilabao I'm not sure this is what we want. By moving these under a common deprecated you're actually loosing the information which group they belong to. I'm inclined to double check and if a deprecation is long enough actually start removing those, instead. But I'll leave it up to @kubernetes/sig-cli-maintainers to chime in.

**Comment by adohe** [comment]
I would suggest we still keep the old behavior, leave the deprecated commands to separate group. I would hope we can actually move deprecated commands from each group once we confirmed it's time to do. Thanks anyway @xilabao

**Comment by xiangpengzhao** [comment]
FYI: these deprecated command aliases will be removed in #49935.

**Pull request closed without merging**
