### PR TITLE
Enables ELB creation for services from cloudformation

### PR DESCRIPTION
**Pull request by mariomarin**
It's not possible to use an external load balancer with the current
cloudformation template. This PR tries to solve that; ~~it's still work in progress~~ 
but I need a way to get feedback and help so please comment about this.
- Updates CloudFormation template to CoreOS 713.3.0 (stable)
- Updates binaries to 1.0.1 release in cloudformation
- Hostname override service
- Picks subnets ids and AZs from CommaDelimitedList (~~ugly hack, I need to replace this~~ replaced)
- Instance profiles and policies for ELB creation

~~I am using an ugly hack for getting the subnets ids and the availability zones,
please bear with me while I fix it. There isn't an explode function for cloudformation
so I just picked the first subnet for the master and a couple of subnets for the nodes.~~

~~There seems to be a missing tag since I am getting this error:~~ the error is gone

```
~~Thu, 06 Aug 2015 13:04:49 +0000   Thu, 06 Aug 2015 13:04:49 +0000   1         myservice                              Service                             creating loadbalancer failed   {service-controller }                                  failed to create external load balancer for service default/myservice: error tagging security group: InvalidParameterValue: Value ( '' ) for parameter Tag key is invalid. Tag key cannot be null or empty.
                                  status code: 400, request id: []~~
```

~~But kubernetes is able to create the ELB though there are no instances attached yet.~~
## Edit
- All ugly hacks are gone.
- ELB is working as an external load balancer for my service.

### CODE REVIEW

**Comment by mariomarin** [comment]
@googlebot I signed it!

**Comment by eramus** [comment]
I think this is a nice improvement over the current CF version, but I believe we need some more flexibility on subnet configuration, but that might be better suited for discussion in #11938. Personally, I would like to see better support for launching the entire cluster into private subnets. I believe that would still work with the intent here, because ELB (exposed or internal) is still able to route traffic correctly to the Kubernetes nodes.

One thing that sticks out to me is that the VPC that this will launch into is selectable. Currently Kubernetes will always try to interact with name = `kubernetes-vpc` as discussed in #9801. Although, It looks like @justinsb is working on a patch for this. Im not sure what affect that will have on selecting a VPC via this CF template.

:+1:

**Comment by mariomarin** [comment]
@justinsb Please review

**Comment by eramus** [comment]
I think we should also see what it takes to include API authentication to the CF template. This would make this method of setup closer to the kube-up method. That might be out of scope of simply using a CF template though; a new provider type for the cluster scripts might be required.

We may want start considering putting together an "aws-coreos" kubernetes provider anyway. It would require a good bit of adaption since salt wouldnt really be applicable, but CF could do a lot of the heavy lifting that the current "aws" provider is currently doing.

**Comment by mariomarin** [comment]
@eramus Why don't we continue the discussion in #6599

Please take a look at [my last comment](https://github.com/GoogleCloudPlatform/kubernetes/issues/11889#issuecomment-128614648)

**Comment by mariomarin** [comment]
@justinsb I don't understand why I am seeing this: *justinsb was unassigned by mariomarin 5 hours ago*. I don't think I have privileges to assign PRs

**Comment by mbforbes** [comment]
Don't worry, you didn't unassign him, he's unassignable (not assignable?). Basically he's not listed as a contributor at this time.

Any guesses at a second reviewer in case @justinsb can't? I'll toss to @brendandburns for now.

**Comment by sachingharge** [comment]
Hi,

I am also looking for updated cloudformation template for ELB creation support.
Please let me know if I can able to download latest cloudformation template?

**Comment by mariomarin** [comment]
@sachingharge [Here](https://github.com/mariomarin/kubernetes/blob/72f172333c003272d74ff774807ffc201776ecfd/docs/getting-started-guides/aws/cloudformation-template.json) it is

**Comment by sachingharge** [comment]
@mariomarin, Thanks for sending cloudformation template link.
Is it possible to update cloudformation template with latest Kubernetes release: Kubernetes v1.0.3  and CoreOS stable release AMI IDs: CoreOS 723.3.0?

Thanks!

**Comment by benwilson512** [comment]
Hey, just passing by, this looks like it could be extremely helpful. Is the usage of Kubernetes 1.0.1 simply because that was the latest version at the time, or are there other reasons for not using 1.0.3?

**Comment by benwilson512** [comment]
Also, I'm getting that `InvalidParameterValue: Value ( '' ) for parameter Tag key is invalid. Tag key cannot be null or empty.` error mentioned in the original post. What is required to fix that?

**Comment by mariomarin** [comment]
@sachingharge I've updated the k8s binaries to 1.0.3 and the coreos amis to 723.3.0.

@benwilson512 Please take a look at #12381

**Comment by mariomarin** [comment]
@benwilson512 You need to create a tag `name: kubernetes-vpc tag` for your vpc.

**Comment by jcderr** [comment]
I'll have to tweak it a little, but I can provide an alternate CloudFormation intended for launching into an existing VPC, as well.

**Comment by mariomarin** [comment]
@brendandburns the cloudformation template was deleted with the merge of #13151 . I want to maintain this template, it allows to launch a kubernetes cluster into an existing VPC instead of creating everything from scratch like kube-up does. However, there are many features missing:

- ~~External load balancer~~
- DNS
- Networking tags for VPC and subnets
- Create raid with ephemeral storage
- Pick docker storage (btrfs vs aufs vs others)
- Logging
- Monitoring
- Authentication

We need to solve DNS for service discovery and this PR already solves the ELB creation. The rest of the features are nice to have but not required.

How do you want me to solve the conflicts with upstream?

**Comment by brendandburns** [comment]
@mariomarin can you take it and fork it into a separate github repo?  Or can you volunteer to maintain it for the long term?

The problem in general is keeping all of the different guides correctly updated, and to do that we need someone who can be a dedicated owner.

**Comment by mariomarin** [comment]
@brendandburns Sure, I'd like to be the owner of the cloudformation template and maintain it in the long term.

**Comment by benwilson512** [comment]
@mariomarin Do you have any specific suggestions about setting up the DNS? I tried simply starting the service and pod spec given here https://github.com/kubernetes/kubernetes/tree/release-1.0/cluster/addons/dns but simply could not get anything to resolve. Have you or anyone else to your knowledge configured a DNS to work with this cloudformation template?

**Comment by mariomarin** [comment]
@benwilson512 No, I could't make it work.

Please take a look at #12449, comments in that issue point to networking. I am no sure if this has to do with flannel configuration.


We should think about a separate template for networking that includes all the tags and replaces flannel with AWS networking resources (route tables, internet gateways, etc). The networking template should be really simple since it's hard to please everyone networking requirements.

**Comment by sachingharge** [comment]
Hello Guys,

It looks CoreOS+Kubernetes AWS setup is completely changed and now CoreOS team providing cloudformation template.
https://github.com/coreos/coreos-kubernetes

Now I don't see anything related to CoreOS+Kubernetes AWS cloudformation template in kubernetes git repo.

Can you please let me know your inputs on this?

**Comment by sachingharge** [comment]
@mariomarin, do you see any changes needs to be done in cloudformation template prepare by you to support latest Kubernetes versions?

Thanks!

**Comment by mariomarin** [comment]
@sachingharge In order to support the latest k8s version I just need to change the version of the binaries.

**Comment by mariomarin** [comment]
@brendandburns I am closing pull request this since there is an oficial cloudformation template from the coreos team and the cloudformation template was deleted from master in #13151.

**Comment by sachingharge** [comment]
@mariomarin,
I still don't want to use cloudformation template provided by CoreOS team.

There seems to couple of changes in master.yaml and node.yaml.
https://github.com/kubernetes/kubernetes/tree/master/docs/getting-started-guides/coreos/cloud-configs

As per my understanding cloudformation template maintained by you earlier used to refer these yaml files for master and node setup.

I would like to use latest changes related to master and node setup so I think it is ok to refer these files right? Couple of things are removed in latest master and node.yaml (e.g. Docker cache proxy, waiter.sh)

Do you see any consequences using code from latest master and node.yaml files in CF?

Another thing, do you know any easy way to convert yaml content to JSON in formatted way.
I tried to use YAML to JSON converter but that doesn't work very well.

Thanks in advance!

**Pull request closed without merging**
