### PR TITLE
Add integration tests for policy secondary authz runtime cost limit.

### PR DESCRIPTION
**Pull request by benluddy**
We intentionally gave secondary authorization a high runtime cost. Only two checks per expression and 28 per policy should be allowed if that cost is being counted.

#### What type of PR is this?

/kind cleanup
/sig api-machinery

#### What this PR does / why we need it:

Adds integration tests demonstrating that we have wired up the cost calculations for the our CEL library functions and that the runtime cost budgets are being enforced.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by cici37** [comment]
Thanks for the PR. Since we agreed to go with feature gate approach and the tests have been added in https://github.com/kubernetes/kubernetes/pull/124675, I'll close this one. Thanks again!
/close

**Comment by benluddy** [comment]
> Thanks for the PR. Since we agreed to go with feature gate approach and the tests have been added in #124675, I'll close this one. Thanks again!

Great, thank you!

**Pull request closed without merging**
