### PR TITLE
RFC: Remove useless e2e noise (events)

### PR DESCRIPTION
**Pull request by thockin**
Someone convince me this is worthwhile?  Whenever e2e fails it shows me nothing useful and instead dumps thousands of lines of noise to my terminal.

### CODE REVIEW

**Comment by quinton-hoole** [comment]
I tend to agree.  I assume that it still runs OK without all that gumph in kube-env.sh, util.sh, prepare-e2e etc?  I'm happy to merge this and fix up any breakages/complaints afterwards, on the basis that there's simply too much bash in tests/e2e of dubious value.  LGTM!

**Comment by thockin** [comment]
re-running it to be sure.

**Comment by thockin** [comment]
e2e passes in my client

**Comment by quinton-hoole** [comment]
Cool, I'll merge and keep an eye on it for regressions in Jenkins etc.

**Pull request merged**
