### PR TITLE
kubelet, cgroupv2: do not create /sys/fs/cgroup/sys with cgroupfs

### LINKED ISSUE #94104: cgroup2: `/sys/fs/cgroup/sys/fs/cgroup` is created
**What happened**:

`/sys/fs/cgroup/sys/fs/cgroup/...` is created on a cgroup2 host

**What you expected to happen**:

Such directory should not be created

**How to reproduce it (as minimally and precisely as possible)**:
* Boot Ubuntu 20.04 with `systemd.unified_cgroup_hierarchy=1`
* Install moby/moby@868578e493 with containerd/containerd@6c74c391fdce62b15428d3032d10217355dcf638  and  opencontainers/runc@54c53b10d33275a0cbd900a83fe4ee131b646362
* Install kubernetes-sigs/kind@03b315444b6fecf5d7abe580dd7996a1441242c6 . This version uses `kindest/base:v20200817-222e7545` as the base image.
* Run `kind build node-image foo` with 3352c44949684edc2a72fc7891fbaa2273a2aa35
* Run `kind create cluster --image foo`
* Run `docker exec -it kind-control-plane bash` to drop into the shell of the node
* The following directories are unexpectedly created. (No process seems to belong to these groups actually)

```
/sys/fs/cgroup/sys/fs/cgroup
/sys/fs/cgroup/sys/fs/cgroup/kubepods
/sys/fs/cgroup/sys/fs/cgroup/kubepods/pode48d9140-f441-4b0f-b642-f0179a167e74
/sys/fs/cgroup/sys/fs/cgroup/kubepods/burstable
/sys/fs/cgroup/sys/fs/cgroup/kubepods/burstable/pod4ccfe0c0-9e30-4da2-a47a-d5dfd477c3b9
/sys/fs/cgroup/sys/fs/cgroup/kubepods/burstable/pode3e7e53f7a71dbba7e64b7dae53fcdca
/sys/fs/cgroup/sys/fs/cgroup/kubepods/burstable/pod34f210dce4b6f04e2cfc4e471a6994de
/sys/fs/cgroup/sys/fs/cgroup/kubepods/burstable/pod15464ac199e313ee38dca21358a3f39b
/sys/fs/cgroup/sys/fs/cgroup/kubepods/burstable/pod22df2323-b6f4-4080-b8e3-925eff03637b
/sys/fs/cgroup/sys/fs/cgroup/kubepods/besteffort
/sys/fs/cgroup/sys/fs/cgroup/kubepods/besteffort/pod5e4773e4-af06-46ae-90df-da7562902e7f
/sys/fs/cgroup/sys/fs/cgroup/kubepods/besteffort/pod55f48177c2c2fd78af624ac3fea65204
/sys/fs/cgroup/sys/fs/cgroup/kubepods/besteffort/pod8d223f92-30f1-4aa4-a279-5bf679961755
```

**Environment**:
(See above)

### PR DESCRIPTION
**Pull request by giuseppe**
Closes: https://github.com/kubernetes/kubernetes/issues/94104

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #94104

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/priority important-soon
(possibly based on previous comment, or possibly critical-urgent)

**Comment by giuseppe** [comment]
@BenTheElder thanks!

@derekwaynecarr I think this fix should be in 1.19

**Comment by giuseppe** [comment]
@sjenning PTAL

**Pull request merged**
