### PR TITLE
Change Expose Command's port operation to be not required

### LINKED ISSUE #13782: Change Expose Command's port operation to be not required
I found expose command's port operation is set to be required, but actually it is not required. It can be copied from the resource being exposed if unspecified.

### PR DESCRIPTION
**Pull request by feihujiang**
Fixes #13782

### CODE REVIEW

**Comment by JanetKuo** [comment]
@k8s-bot test this please

**Comment by JanetKuo** [comment]
Code looks good; needs a rebase

**Comment by feihujiang** [comment]
@JanetKuo  I rebased, please review.

**Comment by feihujiang** [comment]
@k8s-bot  test this please

**Comment by feihujiang** [comment]
@k8s-bot  test this again please

**Pull request merged**
