### PR TITLE
Added e2e test: checks service env vars created.

### PR DESCRIPTION
**Pull request by erictune**
Depends on #2607

### CODE REVIEW

**Comment by erictune** [comment]
Rebased.  Now trying to get the e2e to pass.  Will squash if it passes and gets an LGTM.

**Comment by zmerlynn** [comment]
Please hold on adding e2es until at least #3190 is fixed. The release build
has been broken for 5 days and Jenkins hasn't had a chance to run.

**Comment by erictune** [comment]
Ok

**Comment by zmerlynn** [comment]
And we're clear.

**Comment by erictune** [comment]
PTAL

**Comment by thockin** [comment]
Still LGTM - ok to merge

**Pull request merged**
