### PR TITLE
Automated cherry pick of #72621: Increase default maximumLoadBalancerRuleCount to 250

### PR DESCRIPTION
**Pull request by feiskyer**
Cherry pick of #72621 on release-1.13.

#72621: Increase default maximumLoadBalancerRuleCount to 250

### CODE REVIEW

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
For SIG Release and Azure:
/lgtm
/approve
/check-cla
/test pull-kubernetes-verify

**Comment by feiskyer** [comment]
check-cla not working. Applied the label manually.

**Comment by justaugustus** [comment]
For cherry-pick approval:
/assign @tpepper @aleksandra-malinowska

**Comment by feiskyer** [comment]
ping @tpepper @aleksandra-malinowska for cherry pick approval

**Pull request merged**
