### PR TITLE
use klog instead of klog.V(0)--controller manager part

### PR DESCRIPTION
**Pull request by yangjunmyfm192085**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
As mentioned in the issue https://github.com/kubernetes-sigs/logtools/issues/2, Calling V with zero as parameter just causes additional overhead, so we need to avoid this scenario
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
"NONE"
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yangjunmyfm192085** [comment]
/cc @pohly 
Can we use a separate pr to update klog.Info instead of klog.V(0).Info?
https://github.com/kubernetes/kubernetes/pull/112670 This PR cycle is too long.

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by pohly** [comment]
/assign @atiratree 

This needs to be merged before https://github.com/kubernetes/kubernetes/pull/112670. We want to get it merged sooner than that other PR because it blocks enhancing our log linting.

**Review by atiratree — APPROVED** [review]

**Comment by pohly** [comment]
/assign @soltysh 

For approval.

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
