### PR TITLE
Remove undesired verbose fields from log

### PR DESCRIPTION
**Pull request by tnqn**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The if and else branches have the exactly same code, which looks confusing and doesn't make sense. According to the comment, the else branch should log the error and podUID only.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by matthyx — APPROVED** [review]
indeed

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
