### PR TITLE
Remove the local manifest list after push

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

Manifests seem sticky in docker, so let's try to purge so if
we have re-push a fresh set of containers (with same version number as
before) during testing, the manifests are created fresh.

Change-Id: I41c010c08bd50b68ff6973a4ae1e004824fab178

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/assign @spiffxp 

Aaron, this will help cleanup as well (so we won't really need the https://github.com/docker/cli/pull/1282/ or cleaning up `~/.docker/manifests` by hand)

**Comment by spiffxp** [comment]
ack, lgtm

**Pull request merged**
