### PR TITLE
Update to golang@1.13.6

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Update to golang@1.13.6.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Before merge:
- [x] build/push cross-build image for 1.13.6 (`k8s.gcr.io/kube-cross:v1.13.6-1`)

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Comment by cblecker** [comment]
Other than verify and cross, all other jobs should pass. Let's get a green run first, and then we can cut the image.

**Comment by ialidzhikov** [comment]
> Other than verify and cross, all other jobs should pass. Let's get a green run first, and then we can cut the image.

Currently only `pull-kubernetes-cross` and `pull-kubernetes-verify` are failing.

**Comment by cblecker** [comment]
/unassign @cblecker @fejta 
/assign @BenTheElder @javier-b-perez 

Handing off for image build

**Comment by BenTheElder** [comment]
thanks for this 👍 
/lgtm
/approve

**Comment by BenTheElder** [comment]
/retest
🙃

**Pull request merged**
