### PR TITLE
Kubelet: improve godoc throughout

### PR DESCRIPTION
**Pull request by pmorie**
Kubelet doc cleanup - add doc.go throughout, other doc fixups as I notice them.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35386)

### CODE REVIEW

**Comment by feiskyer** [comment]
@k8s-bot test this please, issue #IGNORE

**Comment by yujuhong** [comment]
LGTM. Sorry for the delay....

**Comment by yujuhong** [comment]
@pmorie if you have time to rebase, we can get this in today.

**Comment by pmorie** [comment]
@yujuhong np, but can we get this in now?  I'd prefer not to have to wait until master opens for 1.6, but i'll understand if that's the case.

**Comment by yujuhong** [comment]
@pmorie doc fixes are allowed, so we can still get this in.

**Comment by yujuhong** [comment]
@pmorie do you still wanna get this in?

**Comment by pmorie** [comment]
I can't believe that this is still open.  Ooops.

**Comment by yujuhong** [comment]
@pmorie why did you abandon the PR...? :-(

**Pull request closed without merging**
