### PR TITLE
Manual cherry pick of #83801: Upgrade to etcd 3.3.17 client + bbolt v1.3.3

### PR DESCRIPTION
**Pull request by jpbetz**
Replaces https://github.com/kubernetes/kubernetes/pull/83915.

Upgrade to etcd 3.3.17 client.  This is conceptually a cherrypick of #83801, but was done by running these commands directly on the `release-1.16` branch:

```
hack/pin-dependency.sh github.com/coreos/etcd v3.3.17
hack/pin-dependency.sh github.com/coreos/bbolt v1.3.3
hack/update-vendor.sh
```

Fixes for two major issues with the etcd 3.3 client to 1.16:

- etcd client does not parse IPv6 addresses correctly when members are joining
- failover on multi-member etcd cluster fails certificate check on DNS mismatch

/kind bug
/priority critical-urgent
/cc @liggitt @wojtek-t @odinuge 

```release-note
Upgrade to etcd client 3.3.17 to fix bug where etcd client does not parse IPv6 addresses correctly when members are joining, and to fix bug where failover on multi-member etcd cluster fails certificate check on DNS mismatch
```

### CODE REVIEW

**Comment by liggitt** [comment]
looks good, but I had one question about bbolt in the master PR at https://github.com/kubernetes/kubernetes/pull/83801#issuecomment-542391042

would like that resolved and the bbolt version in master made coherent before this merges

**Comment by jpbetz** [comment]
/hold

Let's target 1.16.3. We will wait until change on master has had time to soak and scale test before canceling the hold

**Comment by jpbetz** [comment]
> looks good, but I had one question about bbolt in the master PR at [#83801 (comment)](https://github.com/kubernetes/kubernetes/pull/83801#issuecomment-542391042)
> 
> would like that resolved and the bbolt version in master made coherent before this merges

Thanks. I'll get bbolt merged to master before releasing the hold on this PR. (I'll also update the hold comment so we don't forget)

**Review by odinuge — APPROVED** [review]
Both etcd https://github.com/kubernetes/kubernetes/pull/83801 and bbolt is now merged into master https://github.com/kubernetes/kubernetes/pull/83970. Thanks!

/lgtm
/unhold

**Comment by liggitt** [comment]
Once we get successful scale test runs on master with the updated bbolt, this lgtm

**Comment by wojtek-t** [comment]
Today`s run has finished and it looks fine. So I think we can unblock this. @liggitt ?

[BTW, bbolt is not used in etcd client, right? So that dependency shouldn't even matter from our perspective, as long as we don't built etcd. What am I missing?]

**Comment by liggitt** [comment]
You're right.

/hold cancel

**Pull request merged**
