### PR TITLE
Wait longer for job to complete

### PR DESCRIPTION
**Pull request by erictune**
2 timeouts in last 30 e2e runs.
Tripling timeout.
Should normally not that that long.
Uses polling so will terminate early in normal case.

### CODE REVIEW

**Comment by erictune** [comment]
fyi @brendandburns

**Comment by erictune** [comment]
I will cherry-pick to release-1.1 once merged.

**Comment by brendandburns** [comment]
LGTM.  thanks!

**Comment by a-robinson** [comment]
Thanks!

**Pull request merged**
