### PR TITLE
scheduler: Fix field apiVersion is missing from events reported from taint manager

### LINKED ISSUE #114083: Field apiVersion is missing from events reported from taint manager
### What happened?

Events from node taint manager doesn't report involved object apiVersion:

image

### What did you expect to happen?

apiVersion is reported as other events. For example:

image

### How can we reproduce it (as minimally and precisely as possible)?

1. Run a pod on node A (not master)
2. Switch off node A
3. Event `Marking for deletion Pod...` is reported, but without apiVersion in involvedObject.

### Anything else we need to know?

The apiVersion is not reported in taint_manager.go The issue is still not fixed in master:

image

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.3-1+db95af67a8a660", GitCommit:"db95af67a8a660dc53ac09b8475161de2f5c711e", GitTreeState:"clean", BuildDate:"2021-01-22T07:54:01Z", GoVersion:"go1.15.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.3-1+db95af67a8a660", GitCommit:"db95af67a8a660dc53ac09b8475161de2f5c711e", GitTreeState:"clean", BuildDate:"2021-01-22T07:24:32Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Irrelevant
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by aimuz**
Signed-off-by: aimuz <mr.imuz@gmail.com>

#### Which issue(s) this PR fixes:

Fixes #114083

#### Does this PR introduce a user-facing change?

```release-note
scheduler: Fix field apiVersion is missing from events reported from taint manager
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by feloy** [comment]
@aimuz The changes LGTM
/lgtm

**Comment by dims** [comment]
@aimuz how about a test to make sure this doesn't get broken again?

**Comment by aimuz** [comment]
@dims  is a good suggestion, I have added the test

**Comment by aimuz** [comment]
/pin @dims @k82cn @feloy

Do you have time to review it?

**Pull request merged**
