### PR TITLE
Generate protobuf for the audit API

### PR DESCRIPTION
**Pull request by timstclair**
Add protobuf generation & annotations for the advanced auditing API. We're not using them directly now, but settling on the field numbering will help with some 3rd party integrations.

For kubernetes/features#22

/cc @ihmccreery

### CODE REVIEW

**Comment by sttts** [comment]
Bazel is unhappy. Otherwise, lgtm.

**Comment by sttts** [comment]
@smarterclayton approved?

**Comment by timstclair** [comment]
Reran `hack/update-bazel.sh`

**Comment by smarterclayton** [comment]
/approve

But open a follow up issue for API machinery to move userinfo to
someplace better

**Comment by timstclair** [comment]
> Audit API depends on client Go?

This is a temporary situation. As I understand it, both the apis in `k8s.io/kubernetes` and `k8s.io/client-go` are moving to `k8s.io/api`, at which time this API will be updated to depend on k8s.io/api. Depending on a client-go is a temporary workaround until this happens, as depending on the k8s.io/kubernetes api creates a circular dependency.  This was recommended by the api machinery team, and is also the strategy used by the [metrics api](https://github.com/kubernetes/metrics/blob/master/pkg/apis/metrics/v1alpha1/types.go).

**Comment by timstclair** [comment]
Adding lgtm, per https://github.com/kubernetes/kubernetes/pull/46717#issuecomment-305400875

**Comment by timstclair** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this
@k8s-bot pull-kubernetes-unit test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by timstclair** [comment]
Rebased. Reapplying LGTM.

**Comment by timstclair** [comment]
Reran `hack/update-generated-protobuf.sh` after rebase. Reapplying LGTM.

**Pull request merged**
