### PR TITLE
Revert #118867: for default unmarshal behavior chang

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

#118867 is merged in v1.28. 
- for v1.28, we may do a cherry-pick. 
- for master, we have to do further change to make sure etcd pod hash "not-change" should pass during the upgrade process

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/kubeadm/issues/2927

With this revert, the `TestFunc` can pass. Without it, it failed. 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by neolit123** [comment]
/hold

please put WIP / hold to avoid accidental merges if a k8s member just passes by and does an `/lgtm`.

**Comment by neolit123** [comment]
> #118867 is merged in v1.27.


no, we added it in 1.28-pre

https://github.com/kubernetes/kubernetes/pull/118867/commits/80b035a116a0d711db830d39add5e64990e07a74

**Comment by pacoxu** [comment]
> > #118867 is merged in v1.27.
> 
> no, we added it in 1.28-pre
> 
> [80b035a](https://github.com/kubernetes/kubernetes/commit/80b035a116a0d711db830d39add5e64990e07a74)

Typo. Fixed.

**Comment by pacoxu** [comment]
/close 
in favor of #120561

**Pull request closed without merging**
