### PR TITLE
append KUBE-HOSTPORTS to system chains instead of prepend

### PR DESCRIPTION
**Pull request by freehan**
Bug fix for conflicting iptables rules between hostport and kube-proxy

### CODE REVIEW

**Comment by bowei** [comment]
@freehan is there a related issue? This is for 1.7, correct?

**Comment by freehan** [comment]
ref: https://github.com/kubernetes/kubernetes/pull/42943

**Comment by freehan** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
