### PR TITLE
Eliminate direct references to prometheus from kubelet

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind feature
/kind cleanup

**What this PR does / why we need it**:
To get [metrics stability](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/20190404-kubernetes-control-plane-metrics-stability.md) into Beta, we will make it illegal to directly import prometheus methods in Kubernetes components.

Eliminate direct references to prometheus from kubelet:
- Use `metrics.DefBuckets` instead of `prometheus.DefBuckets`

**Which issue(s) this PR fixes**:

Ref kubernetes/enhancements#1238

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/test pull-kubernetes-kubemark-e2e-gce-big

**Comment by derekwaynecarr** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
