### PR TITLE
Fix logging.

### PR DESCRIPTION
**Pull request by lavalamp**
Resolves @quinton-hoole's comments from #10427, increases the queue length to 100 since we know it goes as high as 50.

Risk: low.
Priority: medium.

I would kinda like to see the output of these log messages by default.

### CODE REVIEW

**Comment by quinton-hoole** [comment]
Nice! LGTM.  Feel free to assign milestone v1.0 and a priority, and get a second TL review if you want to merge now.

**Comment by quinton-hoole** [comment]
Test cluster nodes never became ready in the e2e test, which hence aborted.  I doubt whether this has to do with this specific PR.  Retrying.

@k8s-bot test this again

**Comment by lavalamp** [comment]
Are we broken @ head?

The e2e cluster never came up because:

[15] INFO: monitoring-heapster-v5-9z944  pull-e2e-2-minion-y29d  Running  [{Ready False}]

**Comment by quinton-hoole** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/issues/10507

**Comment by lavalamp** [comment]
I've added an increase in the queue length to this PR, and I'd like to get it merged. To @davidopp for second LGTM

**Comment by lavalamp** [comment]
@wojtek-t thanks for measuring the queue length.

**Comment by wojtek-t** [comment]
LGTM - thanks @lavalamp

**Comment by quinton-hoole** [comment]
Agreed, good to merge this based on subsequent discussion.  @lavalamp and @quinton-hoole sufficient for 2 TL policy, @davidopp is sick this week.  ok-to-merge.

**Comment by quinton-hoole** [comment]
@k8s-bot test this please

**Comment by lavalamp** [comment]
@k8s-bot test this please

**Pull request merged**
