### PR TITLE
Automated cherry pick of #15884

### LINKED ISSUE #15804: Don't run DaemonRestart tests in GKE in the release-1.1 branch
There are two tests that are running on GKE in `release-1.1` that shouldn't be:

```
Kubernetes e2e suite.DaemonRestart Kubelet should not restart containers across restart
Kubernetes e2e suite.DaemonRestart Scheduler should continue assigning pods to nodes across restart
```

We should backport the skip of those tests into the `release-1.1` branch.

### PR DESCRIPTION
**Pull request by ixdy**
Cherry pick of #15884 on release-1.1.

### CODE REVIEW

**Comment by ihmccreery** [comment]
Please use the automated tool.  See [the doc](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md).  Sorry to ask you to redo work.

**Comment by ixdy** [comment]
I did. It bailed out with

```console
+++ I'm about to do the following to push to GitHub (and I'm assuming origin is your personal fork):

  git push origin automated-cherry-pick-of-#15884-upstream-release-1.1-1445367956:automated-cherry-pick-of-#15884-upstream-release-1.1

+++ Proceed (anything but 'y' aborts the cherry-pick)? [y/n] y
Counting objects: 3308, done.
Delta compression using up to 6 threads.
Compressing objects: 100% (1358/1358), done.
Writing objects: 100% (3308/3308), 961.90 KiB | 0 bytes/s, done.
Total 3308 (delta 2370), reused 2682 (delta 1833)
To git@github.com:ixdy/kubernetes.git
 * [new branch]      automated-cherry-pick-of-#15884-upstream-release-1.1-1445367956 -> automated-cherry-pick-of-#15884-upstream-release-1.1
+++ Creating a pull request on github
Aborted: the origin remote doesn't point to a GitHub repository.

+++ Returning you to the cherrypick branch and cleaning up.
```

but origin looks fine:
```yaml
[remote "origin"]
        url = git@github.com:ixdy/kubernetes.git                                                                                                 
        fetch = +refs/heads/*:refs/remotes/origin/*
```

So basically the script did everything other than create the pull request itself, which I did manually.

**Comment by ihmccreery** [comment]
Fixes #15804.

**Comment by ihmccreery** [comment]
Filed #15969 for problem with cherry pick tool.  LGTM.

**Comment by ixdy** [comment]
Thanks! (And thanks for fixing up the title/description too.)

**Comment by ihmccreery** [comment]
@k8s-bot test this again please.

**Pull request merged**
