### PR TITLE
Drop unnecessary else statement

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind cleanup
Drop unnecessary else statement

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by yue9944882** [comment]
/unshrug

apologies, is it a golint fix?

**Review by idealhack — COMMENTED** [review]
This looks good to me, but I hope we can fix more places like this in one PR since there're many. Please see https://github.com/kubernetes/kubernetes/issues/68026.

**Pull request closed without merging**
