### PR TITLE
Refactor Printer arguments

### LINKED ISSUE #21260: refactor Printer arguments
The signature for creating a printer is growing pretty large now.  We should refactor the signature to take a `PrinterOptions` struct to make it a bit more friendly.

Example:

```
 func(mapping *meta.RESTMapping, noHeaders, withNamespace, wide bool, showAll bool, showLabels bool, absoluteTimestamps bool, columnLabels []string)
```

### PR DESCRIPTION
**Pull request by ivan4th**
[Analytics]()
Fixes #21260

### CODE REVIEW

**Comment by ivan4th** [comment]
@smarterclayton is there anything wrong with this PR? I think it makes the code a bit cleaner, but I already had to rebase it twice because it touches a part of code that changes often

**Comment by kargakis** [comment]
LGTM

**Comment by kargakis** [comment]
cc: @kubernetes/kubectl

**Comment by kargakis** [comment]
@ivan4th you probably need to rebase one more time

**Comment by ivan4th** [comment]
@kargakis rebased. Don't quite understand what does "Github CI tests are not green" mean when all the tests are actually green.

**Pull request merged**
