### PR TITLE
one time fixup to enable branch fast forward, see issue in sig-release #1154

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Add back the changelogs from 1.16/17 and 18 because failed during the branch FF.
Most likely we need to remove those files in the last RC or after we stop te FF

more context: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1594921378246500

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/sig-release/issues/1154

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/assign @tpepper @saschagrunert 
cc @kubernetes/release-managers 

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by tpepper** [comment]
/lgtm
/approve
these are the changelogs as of eg: f3fdd5cf9f51f2a03ebfddef82bc2014e04b62a0 which allows puts the branch in the state branch fast-forwarding would expect.

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
