### PR TITLE
Upgraded aws-sdk-go to 1.37.20 to include latest supported regions

### PR DESCRIPTION
**Pull request by jqmichael**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Upgraded aws-sdk-go to 1.37.20 to include latest supported regions
```
./hack/pin-dependency.sh github.com/aws/aws-sdk-go v1.37.20
./hack/update-vendor.sh
./hack/lint-dependencies.sh
```

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Upgraded aws-sdk-go to 1.37.20
```

### CODE REVIEW

**Comment by jqmichael** [comment]
pull-kubernetes-e2e-kops-aws failing with the two tests below.

```
Kubernetes e2e suite: [sig-node] RuntimeClass should run a Pod requesting a RuntimeClass with a configured handler [NodeFeature:RuntimeHandler] expand_more5m11s | Kubernetes e2e suite: [sig-node] RuntimeClass should run a Pod requesting a RuntimeClass with a configured handler [NodeFeature:RuntimeHandler] expand_more | 5m11s
-- | -- | --
Kubernetes e2e suite: [sig-node] RuntimeClass should run a Pod requesting a RuntimeClass with a configured handler [NodeFeature:RuntimeHandler] expand_more | 5m11s
```

**Comment by liggitt** [comment]
closing due to inactivity, feel free rebase/reopen, or open a new PR with the update

**Comment by liggitt** [comment]
actually, looks like https://github.com/kubernetes/kubernetes/pull/102415 is already open to bump to 1.38.49

**Pull request closed without merging**
