### PR TITLE
Control Plane is a better name

### PR DESCRIPTION
**Pull request by lavalamp**
**What type of PR is this?**

/kind cleanup

Methodology:
```
 9200  [2020-09-01 16:03:51 -0700] mkdir pkg/cluster
 9201  [2020-09-01 16:03:59 -0700] git mv pkg/master/ports pkg/cluster/
 9202  [2020-09-01 16:04:38 -0700] grep -RIl "pkg/master/ports" . | xargs -n1 sed -i 's|pkg/master/ports|pkg/cluster/ports|g'
 9203  [2020-09-01 16:04:52 -0700] hack/update-bazel.sh 
 9204  [2020-09-01 16:06:49 -0700] git st
 9205  [2020-09-01 16:06:52 -0700] git add .
 9206  [2020-09-01 16:07:09 -0700] git commit -m "move port definitions to a common location"
 9207  [2020-09-01 16:07:31 -0700] git mv pkg/master pkg/controlplane
 9208  [2020-09-01 16:08:15 -0700] grep -RIl "master" pkg/controlplane | xargs -n1 sed -i 's|package master|package controlplane|g'
 9209  [2020-09-01 16:08:30 -0700] grep -RIl "pkg/master" . | xargs -n 1 sed -i 's|pkg/master|pkg/controlplane|g'
 9210  [2020-09-01 16:08:50 -0700] grep -RIl 'k8s.io/kubernetes/pkg/controlplane[^/]' | grep "[.]go" | xargs -n1 go run ../toplevelnamechange.go master controlplane
 9211  [2020-09-01 16:09:03 -0700] hack/update-bazel.sh
 9212  [2020-09-01 16:09:47 -0700] git add .
 9213  [2020-09-01 16:09:50 -0700] git st
 9214  [2020-09-01 16:09:58 -0700] git commit -m "rename"
```

I wrote a short script to do the name change without false positives: https://gist.github.com/lavalamp/f9641969bfc5f327f6a89a70b2f4668a

```release-note
NONE
```

/sig api-machinery

### CODE REVIEW

**Comment by lavalamp** [comment]
(This only changes the directory structure, which can't really be done in a smaller increment.)

**Comment by deads2k** [comment]
/lgtm

but you've got a way to please the bots.

**Pull request merged**
