### PR TITLE
Move registry helpers into pkg/registry

### PR DESCRIPTION
**Pull request by sttts**
Preparation for https://github.com/kubernetes/kubernetes/issues/58292 and cleanup of pkg/apis dependencies.

### CODE REVIEW

**Comment by lavalamp** [comment]
I think we should agree on some general principle before we do this, do we want helper functions in our api surface area? Then changes to them are breaking...

**Comment by sttts** [comment]
The helpers in this PR are special because they are registry only. There are no other consumers. But I agree we have to discuss this in general for many of the other moves in https://github.com/kubernetes/kubernetes/issues/58292. Can we move the discussion into that issue?

@lavalamp do you agree that these registry-only helpers (which just wipe out fields depending on feature flags; no other consumer should do such a thing) can move?

**Comment by deads2k** [comment]
> I think we should agree on some general principle before we do this, do we want helper functions in our api surface area? Then changes to them are breaking..

@lavalamp as @sttts  noted, this pull move kube/kube (not kube/api) helpers to their only point of use.  It's an internal move of code we don't expect people to depend on.

I think this is still a good idea.

**Comment by sttts** [comment]
> I think this is still a good idea.

will rebase soon.

**Comment by sttts** [comment]
/assign @smarterclayton 

for approval.

**Pull request closed without merging**
