### PR TITLE
chore(validatingadmissionpolicystatus): use WaitForCacheSync after sharedInformerFactory Start in unit test

### PR DESCRIPTION
**Pull request by omerap12**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Part of #126256 

#### Special notes for your reviewer:
As requested in issue #126256 , I'm splitting this into separate PRs
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by omerap12** [comment]
@Jefftree  Friendly ping :)

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
