### PR TITLE
cleanup(kubelet): use errors.Is(err, os.ErrProcessDone)

### PR DESCRIPTION
**Pull request by cndoit18**
use errors.Is(err, os.ErrProcessDone) here and remove "process already finished" string comparison.

Signed-off-by: cndoit18 <cndoit18@outlook.com>

#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
@cndoit18 please change the release note to NONE. This is not user-visible change

/lgtm

**Comment by cndoit18** [comment]
> @cndoit18 please change the release note to NONE. This is not user-visible change
> 
> 
> 
> /lgtm

Done, thanks

**Review by mrunalp — APPROVED** [review]

**Comment by derekwaynecarr** [comment]
if I recall, this was needed prior to go 1.16.

thanks for cleanup.

/approve
/lgtm

**Pull request merged**
