### PR TITLE
Update 1.10 test gpu_util.go to use the 1.10 nvidia-gpu device-plugin…

### PR DESCRIPTION
**Pull request by jiayingz**
**What this PR does / why we need it**:
Update 1.10 test gpu_util.go to use the 1.10 nvidia-gpu device-plugin yaml.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by MaciekPytel** [comment]
@jiayingz Can you get someone with ownership in test to review? The cherrypick is approved, but it still need to go through normal review process.

**Comment by jiayingz** [comment]
@MaciekPytel Thanks for the reminding!
/cc @vishh

**Pull request merged**
