### PR TITLE
Fix Spelling error  about [workflow] for kubeadm

### PR DESCRIPTION
**Pull request by heqg**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
Fix Spelling error  about [workflow] for kubeadm

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

```release-note
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Review by yagonobre — COMMENTED** [review]
Thanks
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
/approve

**Pull request merged**
