### PR TITLE
Update the addons test so it doesn't try to create clients on providers aren

### PR DESCRIPTION
**Pull request by brendandburns**
@marekbiskup @cjcullen @roberthbailey

### CODE REVIEW

**Comment by roberthbailey** [comment]
Code looks ok; not sure why the presubmit tests are all failing.

**Comment by marekbiskup** [comment]
@brendanburns , thank you for correcting my obvious mistakes.
Errors in shippable are unrelated. Error in the DNS test from jenkins could be releated (DNS is an addon), but on the other hand, the changes are unrelated.

LGTM from me.

**Comment by fgrzadkowski** [comment]
Problem with proxy and DNS might related to https://github.com/GoogleCloudPlatform/kubernetes/pull/10069 . At least in my case (I had similar result) it helped.

**Comment by fgrzadkowski** [comment]
@k8s-bot test this please

**Comment by roberthbailey** [comment]
LGTM.

**Comment by jlowdermilk** [comment]
Test that was causing timeouts is disabled at head. Please rebase.

**Comment by roberthbailey** [comment]
Assigning to @quinton-hoole for second lgtm.

**Comment by quinton-hoole** [comment]
Yup, LGTM.

**Comment by quinton-hoole** [comment]
Does this fix any particular reported issue?

**Comment by quinton-hoole** [comment]
@k8s-bot Test this please.

**Comment by brendandburns** [comment]
@quinton-hoole it is necessary to move the add-ons (e.g. the fluentd daemon on each node) into it's own non-default namespace.  

It's a small part of the much larger:

https://github.com/GoogleCloudPlatform/kubernetes/pull/10331

**Pull request merged**
