### PR TITLE
pkg/credentialprovider/plugin: refactor for better testability with mulitple apiVersions

### PR DESCRIPTION
**Pull request by andrewsykim**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

https://github.com/kubernetes/kubernetes/pull/108847 introduced the v1beta1 APIs for the kubelet credential provider feature. Although the v1beta1 APIs are preferred going forward and there are no changes between v1alpha1 and v1beta1, we should still have tests validating v1alpha1 as long as it's supported. This PR refactors the credential provider plugin so we can unit test against multiple apiVersions and test behavior when the apiVersions are mismatched. These unit tests should also help fill in v1alpha1 coverage we're losing with https://github.com/kubernetes/kubernetes/pull/109006, since the node e2e tests would only be running with v1beta1 APIs.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by adisky** [comment]
@andrewsykim Created PR for pre-submit job
https://github.com/kubernetes/test-infra/pull/25763

**Comment by andrewsykim** [comment]
This is nice to have for more test coverage but not urgent for v1.24

/assign @liggitt @adisky 
/triage accepted
/priority important-longterm

**Comment by andrewsykim** [comment]
/reopen

(coming back from a long break)

I think at this point we'll want to remove the v1alpha1 APIs in v1.26, but I think this refactor is still worthwhile as we'll need to test both v1beta1 and v1 APIs. Working on a separate PR to remove v1alpha1 APIs.

**Comment by liggitt** [comment]
can you sync with @ndixita on https://github.com/kubernetes/kubernetes/pull/111616 to figure out the order of operations with these PRs? I know that one is really close, but I'm not sure if this would disrupt it or make it easier or improve our test coverage when combined with that one

**Comment by andrewsykim** [comment]
> can you sync with @ndixita on https://github.com/kubernetes/kubernetes/pull/111616 to figure out the order of operations with these PRs? I know that one is really close, but I'm not sure if this would disrupt it or make it easier or improve our test coverage when combined with that one

Ah, totally missed this PR, thanks will follow-up!

**Comment by andrewsykim** [comment]
Taking a quick glance at that PR, I think it'll be easier to revisit this after #111616 merges (along with removing v1alpha1 APIs)

**Pull request closed without merging**
