### PR TITLE
HPA incorrectly reported condition status

### PR DESCRIPTION
**Pull request by sukeesh**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR fixes HPA incorrectly reported condition status.

**Example:** Consider a case where 
```golang
desiredReplicas = 1
minimumAllowedReplicas = 2
hpaMinReplicas = 2
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
NA

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by draveness — APPROVED** [review]
/lgtm
/ok-to-test
/priority backlog

**Comment by sukeesh** [comment]
I will fix these errors 🙇

**Review by draveness — COMMENTED** [review]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/79859/pull-kubernetes-bazel-test/1148066804401180672

/retest

**Review by draveness — CHANGES_REQUESTED** [review]
You could take a look at this

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal_test.go#L2497

**Review by draveness — COMMENTED** [review]
Please squash the commits into one

**Comment by sukeesh** [comment]
@draveness Done

**Review by draveness — APPROVED** [review]
/lgtm

Thanks!

**Review by SataQiu — COMMENTED** [review]
/lgtm

**Comment by sukeesh** [comment]
@piosz Can you please approve?

**Comment by sukeesh** [comment]
@mwielgus @jszczepkowski  @MaciekPytel Can one of you please approve this PR? 🙏

/assign @mwielgus @jszczepkowski  @MaciekPytel

**Pull request merged**
