### PR TITLE
Update npd to the official v0.3.0 release.

### PR DESCRIPTION
**Pull request by Random-Liu**
Update npd to the official release v0.3.0.

This also fixes a npd bug https://github.com/kubernetes/node-problem-detector/pull/98.

@dchen1107 @kubernetes/node-problem-detector-reviewers

### CODE REVIEW

**Comment by Random-Liu** [comment]
@kubernetes/release-team Mark 1.6 because this fixes a npd bug in 1.6.

**Comment by Random-Liu** [comment]
@k8s-bot non-cri node e2e test this
@k8s-bot non-cri e2e test this

gcloud flakes:
```
W0315 14:28:48.499] ERROR: (gcloud.components.update) The component [gcloud-deps] failed to download.
W0315 14:28:48.499] 
W0315 14:28:48.499] HTTP Error 404: Not Found
```

**Comment by Random-Liu** [comment]
All 4 tests in https://github.com/kubernetes/kubernetes/pull/42454 passed.
```
Ran 4 of 571 Specs in 377.979 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 567 Skipped PASS
```

**Comment by dchen1107** [comment]
I saw Jenkins Kubemark GCE e2e also passed. Approve the change.

/approve

**Comment by Random-Liu** [comment]
Apply LGTM based on https://github.com/kubernetes/kubernetes/pull/43165#issuecomment-286916990

**Pull request merged**
