### PR TITLE
Allow service names up to 63 characters (RFC 1035)

### LINKED ISSUE #3752: Consider expanding service names
Filing this so we can revisit.
@satnam6502 

Service names (and apparently Namespace names in the client, but not the server) are restricted to DNS 952 labels (24 characters).  Most other API Objects have names that are DNS 1123 subdomains (much longer).

In doing tests it is useful to generate random names, and this is a bit annoying for services.

Can we expand service names?

1) DNS 1035 labels (longer)
2) DNS 1035 subdomains (longer and allow dots)
3) DNS 1123 labels (longer, allow leading digit)
4) DNS 1123 subdomains (longer, allow leading digit and dots)

(4) would be most consistent with other objects.

If we do (2) or (4) we need to convert dots to underscores in env-var names, which could cause a collision (e.g. foo-bar and foo.bar).  Maybe double underscore for dots?

If we do (3) or (4) we need to handle leading digits in env-vars.  Maybe a prefixed underscore?

(1) seems least controversial, but is still different than everything else.

### PR DESCRIPTION
**Pull request by fraenkel**
fixes #3752

### CODE REVIEW

**Comment by dims** [comment]
@fraenkel Hey, nice to bump into you here :) fyi, there's an existing PR for DNS 1123 https://github.com/kubernetes/kubernetes/pull/28005

**Comment by thockin** [comment]
ok to test

**Comment by thockin** [comment]
LGTM, thanks!

**Comment by thockin** [comment]
Tests failed:

expose_test.go:407: truncate-name: Unexpected output! Expected
	service "a-name-that-is-toooo-big-for-a-service-because-it-can-only-handle-63-characters" exposed
	got
	service "a-name-that-is-toooo-big-for-a-service-because-it-can-only-hand" exposed

The other seems to be a flake

**Comment by fraenkel** [comment]
Seems we truncate somewhere but tends to work locally. I can fix the test to match.

**Comment by thockin** [comment]
The truncation looks correct, not sure why it is not working.

Ping me when ready for next review.

On Fri, Jul 29, 2016 at 12:34 PM, Michael Fraenkel <notifications@github.com

**Comment by fraenkel** [comment]
I know the problem. I have been struggling to get a clean run locally. But I will continue to try.

**Comment by fraenkel** [comment]
@thockin Tests now pass.

**Comment by thockin** [comment]
Thanks!!

**Pull request merged**
