### PR TITLE
JSON output streams

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind feature
/kind api-change

#### What this PR does / why we need it:

Split-routing and buffering increase the scalability of logging. See also https://github.com/kubernetes/enhancements/pull/2912#discussion_r703346009 and other comments in that PR.

#### Special notes for your reviewer:

Includes https://github.com/kubernetes/kubernetes/pull/105480

#### Does this PR introduce a user-facing change?
```release-note
JSON log output is configurable and now supports writing info messages to stdout and error messages to stderr. Info messages can be buffered in memory. The default is to write both to stdout without buffering, as before.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components/README.md
```

New command line flags:
```
     --log-json-info-buffer-size quantity  [Experimental] In JSON format with split output streams, the info messages can be buffered for a while to increase performance. The default value of zero bytes disables buffering. The size can be specified as number of bytes (512), multiples of 1000 (1K), multiples of 1024 (2Ki), or powers of those (3M, 4G, 5Mi, 6Gi).
     --log-json-split-stream               [Experimental] In JSON format, write error messages to stderr and info messages to stdout. The default is to write a single stream to stdout.
```

New options for kubelet config:
```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
logging:
  format: json
  options:
    json:
      splitStream: true
      infoBufferSize: 4Mi
```

### CODE REVIEW

**Comment by thockin** [comment]
There were concerns about split the streams on the KEP - are those resolved?

**Comment by pohly** [comment]
> There were concerns about split the streams on the KEP - are those resolved?

We decided to keep the behavior of the stable text output (= traditional klog) unchanged. The split streams for JSON will be opt-in. I just need to add some configuration for it. Another open is how buffering and flushing of those buffers should work (https://kubernetes.slack.com/archives/C020CCMUEAX/p1631205187021600).

**Comment by pohly** [comment]
When we discussed this in the structured logging WG, @serathius pointed out that embedding arbitrary options inside the config API might be frowned upon. Validation of those options was implemented, but they don't become part of the API documentation.

Therefore I added a second commit which replaces that approach with hard-coding the JSON options in the public API. The downside is that this then makes it harder for downstream developers to build custom commands which use some other logging backend. It should still be doable, though.

**Comment by pohly** [comment]
Once https://github.com/kubernetes/kubernetes/pull/105076 is merged, this PR will only have commits for component-base and kubelet. It will affect various commands, but let me make the tags more focused despite that to reduce the noise for those who are not interested:

/remove-area apiserver
/remove-area cloudprovider
/remove-area dependency
/remove-area kubectl
/remove-area release-eng
/remove-area test
/remove-sig auth
/remove-sig cloud-provider
/remove-sig cluster-lifecycle
/remove-sig network
/remove-sig release
/remove-sig scheduling
/remove-sig testing

**Comment by pohly** [comment]
> There were concerns about split the streams on the KEP - are those resolved?

Yes. Output splitting and buffering will both be off by default, so there's not going to be a problem for consumers who expect the traditional behavior.

**Comment by pohly** [comment]
Once https://github.com/kubernetes/kubernetes/pull/105076 is merged, this PR will only have one commit for component-base. It will affect various commands, but let me make the tags more focused despite that to reduce the noise for those who are not interested:

/remove-area apiserver
/remove-area cloudprovider
/remove-area dependency
/remove-area kubectl
/remove-area release-eng
/remove-area test
/remove-sig api-machinery
/remove-sig auth
/remove-sig cloud-provider
/remove-sig cluster-lifecycle
/remove-sig network
/remove-sig release
/remove-sig scheduling
/remove-sig testing

**Comment by pohly** [comment]
It might make sense to wait for a decision on how to do versioning and experimental fields in these component structs - see https://github.com/kubernetes/kubernetes/pull/105539

**Review by thockin — COMMENTED** [review]
Overall this seems  sane, given my limited depth in this subsystem.  Nothing majorly obviously wrong that I see.

**Comment by pohly** [comment]
> throw a hold on it if you want it not to merge?

I'm undecided. We add new fields here without a clear indication of their stability level and I am wondering whether we should be doing this better somehow.

That they appear in `v1alpha1.LoggingConfiguration` doesn't help because that is not visible to the user. The discussion in https://github.com/kubernetes/kubernetes/pull/105448 is about that.

Let's finish the review of this change (coding style, naming) but not merge quite yet, so:

/hold

**Comment by pohly** [comment]
@thockin: do you have an opinion whether the approach from https://github.com/kubernetes/kubernetes/pull/104873/commits/4ca3a977df9900d709df3ce9e67c6e284710eb3f (= embed arbitrary, logging backend specific parameters) is better than the one from https://github.com/kubernetes/kubernetes/pull/104873/commits/fae02538944cb1c07c26d6cf3a857e030ba9601d (= hard-code support for JSON in the LoggingConfiguration, regardless whether that backend is registered)? The commit messages explain both.

You probably looked at the overall change, which is using the approach with hard-coding because that is the more recent commit. I'll squash once I know which approach is preferred.

**Comment by pohly** [comment]
> I will almost always take a strongly-typed solution over a map. In this case, I have a hard time making up reasons why a map would be reasonable - we're not going to add a dozen formats, right?

Probably not. It's mostly a conceptual issue: `component-base/logs` jumps through quite some hoops to be completely independent of the "json" format, and now this PR breaks that abstraction.

But I guess that's okay. In practice, there will only be binaries with "text+json" and those where "json" hasn't been enabled yet, which should become fewer over time. The `--log-json-*` command line flags only get added when "json" is enabled and those commands which have a config file also have "json" support, so the current PR should be fine.

**Comment by pohly** [comment]
/retest

Unrelated test flake.

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
