### PR TITLE
add error info

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fabianofranz** [comment]
@k8s-bot ok to test

**Comment by zjj2wry** [comment]
@fabianofranz i fix some my code error.
```
./current_context_test.go:65: no new variables on left side of :=
./delete_cluster_test.go:61: no new variables on left side of :=
./delete_context_test.go:61: no new variables on left side of :=
./get_clusters_test.go:65: no new variables on left side of :=
./get_contexts_test.go:131: no new variables on left side of :=
```
the filechange just update one line. could you apply the **lgtm** again. 😊 think you ~

**Pull request merged**
