### PR TITLE
bump  github.com/moby/spdystream to v0.3.0

### LINKED ISSUE #125707: data race in spdystream dependency
This data race in spdystream https://github.com/moby/spdystream/pull/91 effects the code in https://github.com/kubernetes/client-go/blob/master/transport/spdy/spdy.go

### PR DESCRIPTION
**Pull request by BenTheElder**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

picks up fix for data-race in Ping

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/125707

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
#125688 
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/125745/pull-kubernetes-unit/1806046857424539648
/retest

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
