### PR TITLE
Windows tests: Adds [Feature:GPUDevicePlugin] tag to Device Plugin test

### LINKED ISSUE #99028: Test "Device Plugin should be able to create a functioning device plugin for Windows" shouldn't run with all [sig-windows] tests
#### Which jobs are failing:

```
https://testgrid.k8s.io/sig-windows-azure#aks-engine-azure-windows-1909-master
https://testgrid.k8s.io/sig-windows-azure#aks-engine-azure-windows-2004-master
https://testgrid.k8s.io/sig-windows-gce#gce-windows-2019-containerd-master
https://testgrid.k8s.io/sig-windows-networking#containerd-overlay-windows-master
https://testgrid.k8s.io/sig-windows-networking#containerd-l2bridge-windows-master
```

Flakes on:

```
https://testgrid.k8s.io/sig-windows-networking#flannel-l2bridge-windows-master
```

Passed on:

```
https://testgrid.k8s.io/sig-windows-networking#flannel-overlay-windows-master (2295.211 seconds)
```

#### Which test(s) are failing:

```
[sig-windows] Device Plugin should be able to create a functioning device plugin for Windows
```

#### Since when has it been failing:

N/A

#### Testgrid link:

See above.

#### Reason for failure:

The test requires hosts with GPUs attached, which is not common in a CI. The test shouldn't be run automatically with every other ``[sig-windows]`` labeled test, it should have a dedicated, specific label which should be excluded in most jobs.

At the very least, it should have the ``[Slow]`` tag since it's quite slow. The test uses the image ``e2eteam/k8s-directx-device-plugin:0.9.0-1809``, which is a Windows image (not Windows servercore image), which is ~10-11 GB in size, so it can take some time to download.

Additionally, in some cases, the test lingers for hours, which is problematic:

```
[BeforeEach] [sig-windows] Device Plugin
  /home/capi/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/windows/framework.go:28
[BeforeEach] [sig-windows] Device Plugin
  /home/capi/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:185
STEP: Creating a kubernetes client
Feb 10 22:53:39.459: INFO: >>> kubeConfig: /tmp/capz-kubeconfig.yaml
STEP: Building a namespace api object, basename device-plugin
STEP: Waiting for a default service account to be provisioned in namespace
[BeforeEach] [sig-windows] Device Plugin
  /home/capi/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/windows/device_plugin.go:45
[It] should be able to create a functioning device plugin for Windows
  /home/capi/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/windows/device_plugin.go:50
STEP: creating Windows device plugin daemonset
STEP: creating Windows testing Pod
STEP: Waiting for the pod Running
Feb 11 03:53:40.905: FAIL: Unexpected error:
    <*errors.errorString | 0xc0001f01d0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
```

This can be observed here: https://prow.k8s.io/view/gcs/k8s-ovn/ci-kubernetes-e2e-sdnoverlay-ctrd-master-windows/1359608248725934080

#### Anything else we need to know:

Worth noting that the test has been explicitly skipped in a few test runs: https://github.com/kubernetes/test-infra/pull/20352/files

/sig windows
/sig testing

/cc @marosset 
/cc @chewong 
/cc @Kerstin08
/cc @aarnaud

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind failing-test
/sig windows
/sig testing

/priority important-soon

#### What this PR does / why we need it:

The test verifies a specific feature, in which GPUs are required, thus, cannot be run in most testing environments. We should exclude this test from most test jobs. We'll be doing this by adding the ``[Feature:GPUDevicePlugin]`` tag (which is also being
used by ``test/e2e/scheduling/nvidia-gpus.go``), and then add it to the ginkgo skip regex. Some tests are already skipping any ``\[Feature:.+\]`` tests [1].

[1] https://github.com/kubernetes/test-infra/blob/d9fbec8e187788b04bf03d86939087cb11d801f8/config/jobs/kubernetes/sig-windows/windows-gce.yaml#L335

#### Which issue(s) this PR fixes:

Partially Fixes #99028

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
cc @palnabarun

**Comment by palnabarun** [comment]
xref: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1617647622287100

This change is not supposed to land in `release-1.21`.

**Pull request merged**
