### PR TITLE
glusterfs: improve a few comments

### PR DESCRIPTION
**Pull request by obnoxxx**
**What this PR does / why we need it**:

This PR fixes a couple of comments in the glusterfs module:
* fixes a typo in a comment
* removes an outdated comment that is not correct (any more)
* updates one comment to refer to upstream gluster documentation instead of downstream red hat product documentation

### CODE REVIEW

**Comment by cblecker** [comment]
/ok-to-test
/release-note-none
/lgtm
/assign @jingxu97
for approval

**Comment by obnoxxx** [comment]
@cblecker wrote:
> actually @obnoxxx, can you combine #60048, #60050, and #60051 into a single PR? They are all comment updates to the same package.

Sure, I can do that. May I ask for the reasoning?
I was kind of trying to follow the "Smaller is better" paradigm of https://github.com/kubernetes/community/blob/master/contributors/devel/pull-requests.md#2-smaller-is-better-small-commits-small-prs :-)

That said, I'll happily merge them.

**Comment by cblecker** [comment]
@obnoxxx In this case, the reasoning is that these are all comment updates (not code changes) to the same package. This minimizes the testing and approvals required to get these merged. If these were all in different packages, then 3 PRs would be preferable.

Thanks!

**Comment by obnoxxx** [comment]
@cblecker ok, that makes sense, thanks!

I have prepared my branch. Would you prefer me updating this PR or create a new one?

**Comment by cblecker** [comment]
This one is fine. Just update the PR title/description

**Comment by obnoxxx** [comment]
@cblecker done, thanks

**Pull request merged**
