### PR TITLE
remove unused function in openstack cloud provider

### PR DESCRIPTION
**Pull request by huzhengchuan**
**What this PR does / why we need it**:
List function not used in openstack cloud provider, and useless, I think need remove it.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by huzhengchuan** [comment]
cc @dims  @anguslees  @NickrenREN 
Can you help me review the pr, thanks.

**Comment by NickrenREN** [comment]
Tests failed. Please check the verify error.
Also I am not sure whether we should remove the public function or keep it as it used to be for future calls.
@huzhengchuan  Could you find the commits(PR) which introduce the function ?

**Comment by huzhengchuan** [comment]
Thanks for your review.  I see the history of function List().
the List() function defined in cloud.go begin (#244)
and implement in openstack cloud provider in (#1676)
and the List() removed in cloud.go (#31678) and in #31678 remove the implement of List() in aws/gce and others cloud providers.
@NickrenREN

**Comment by huzhengchuan** [comment]
@anguslees  
I need you help me review, I see the  #31678 is your work.

**Comment by NickrenREN** [comment]
Seems it should be removed
Approve first, let @anguslees  add lgtm
/approve no-issue

**Comment by NickrenREN** [comment]
Sorry I do not why the bot does not response to my comment

**Pull request merged**
