### PR TITLE
pkg/kubelet/server.go: minor fixes

### PR DESCRIPTION
**Pull request by xiang90**
1. Fix a error assignment issue
2. Drop unnecessary write header: 
   We only need to write header OK beforehand when generating body might block for a while. There are some other places that is 100% unnecessary. 
3. use s.error() to write internal error consistently

### CODE REVIEW

**Comment by nikhiljindal** [comment]
@dchen1107: Are you the right reviewer for this?

**Comment by dchen1107** [comment]
LGTM. Can you add a test to server_test.go? Also squash commits? Thanks!

**Comment by xiang90** [comment]
@dchen1107 Sure. Will do.

**Comment by xiang90** [comment]
@dchen1107 I squashed the commits and added a tests for the code I am fixing in this pull request.

**Pull request merged**
