### PR TITLE
Removing explicit docker start

### PR DESCRIPTION
**Pull request by MartinPodval**
Fixing #15545. Explicit docker start was removed in getting started guides.

### CODE REVIEW

**Comment by MartinPodval** [comment]
I signed it!

**Comment by MartinPodval** [comment]
I signed it!

**Comment by bgrant0607** [comment]
cc @AntonioMeireles

**Comment by fejta** [comment]
This PR has had no meaningful activity for multiple months. If it is still valid please rebase, push a new commit and reopen the PR. Thanks!

**Pull request closed without merging**
