### PR TITLE
Automated cherry pick of #23985

### PR DESCRIPTION
**Pull request by tomdee**
Cherry pick of #23985 on release-1.2.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Thanks. LGTM.

**Comment by caesarxuchao** [comment]
ok to test

**Comment by zmerlynn** [comment]
@caesarxuchao: The cherrypick process is to mark `cherrypick-candidate` on the original PR, otherwise I won't even notice it. This PR is possibly going to miss the 1.2.3 release because of that. Let's discuss on the original PR.

**Comment by david-mcmahon** [comment]
@caesarxuchao for reference: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md

**Pull request merged**
