### PR TITLE
WIP: test staging registry new images

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

DO NOT MERGE: Testing the newly published staging registry images before
they are promoted, so we can make sure we don't break anything.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by listx** [comment]
/hold

Adding a hold just in case.

**Comment by chewong** [comment]
LGTM

pull-kubernetes-e2e-aks-engine-azure-windows failure is unrelated to the test images.

**Pull request closed without merging**
