### PR TITLE
fix issue(51027)kubect logs --selector ignoring --tail=-1

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:
closes issue #51027 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
fix kubect logs --selector ignoring --tail=-1
```

### CODE REVIEW

**Comment by wanghaoran1988** [comment]
@zjj2wry  Could you please update the release note ?

**Comment by zjj2wry** [comment]
@wanghaoran1988 i has add the release-note=NONE.  :)

**Comment by wanghaoran1988** [comment]
I mean you should update the release note and describe that you fixed this issue.

**Comment by zjj2wry** [comment]
@wanghaoran1988 ok, thanks

**Pull request merged**
