### PR TITLE
Enable AWS security groups

### PR DESCRIPTION
**Pull request by justinsb**
This is based on #9295, but adds configuration of security groups on AWS so everything is locked down as it is on GCE.

### CODE REVIEW

**Comment by justinsb** [comment]
The first commit is #9295, the second commit is what I am proposing here.

**Comment by quinton-hoole** [comment]
Awesome!  My baby comes back to haunt me :-)
cc @thockin @a-robinson FYI
I'm a bit swamped with oncall responsibilities this week, but should be able to review early next week if nobody gets there before me.

**Comment by thockin** [comment]
LGTM

needs rebase

**Comment by quinton-hoole** [comment]
@justinsb Let me know as soon as you've rebased.

**Comment by justinsb** [comment]
Rebased.  It was a conflict with my own PR (and not even a real conflict at that).

**Pull request merged**
