### PR TITLE
[cluster/gce] Target the correct project while adding kubeconfig metadata to the master

### LINKED ISSUE #99690: [cluster/gce] Missing --project while adding kubeconfig metadata
#### What happened:

kube-up tries to add metadata to the wrong project.

https://testgrid.k8s.io/conformance-all#Conformance%20-%20GCE%20-%20master%20-%20kubetest2

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest-kubetest2/1366974682632294400

```
ERROR: (gcloud.compute.instances.add-metadata) Could not fetch resource:
 - Required 'compute.instances.get' permission for 'projects/k8s-infra-prow-build/zones/us-central1-b/instances/kt2-3a058694-7bdc-master'
```
It is trying to add metadata to the prow project running the tests instead of the target project.

This is because 

https://github.com/kubernetes/kubernetes/blob/716a0547206a71ecc6e53f8b970728bc85063a60/cluster/gce/util.sh#L2885

is missing a `--project=${PROJECT}`

#### What you expected to happen:
kube-up uses the target project to add metadata

#### How to reproduce it (as minimally and precisely as possible):
Don't set/set a different default project and run cluster/kube-up.

#### Anything else we need to know?:

originally added in https://github.com/kubernetes/kubernetes/pull/77930

kubetest hides the project acquired from boskos under the covers by setting it as the default project

https://github.com/kubernetes/test-infra/blob/81be880b02cc25b7bf77f2ecb9607d0b625460e3/kubetest/main.go#L770

uncovered as part of migration to kubetest2

xref: https://github.com/kubernetes/enhancements/issues/2464

/cc @BenTheElder @spiffxp @mm4tt

### PR DESCRIPTION
**Pull request by amwat**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/99690

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/cc @BenTheElder @spiffxp @mm4tt

### CODE REVIEW

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
This seems like it may exacerbate https://github.com/kubernetes/k8s.io/issues/1751? Let's find out

**Comment by amwat** [comment]
I think kubernetes/k8s.io#1751 might be a bit different since that's to do with ssh-keys which get automatically created/propagate to the VM metadata whenever we run `gcloud compute ssh`

whereas this one is to do with us manually adding additional metadata related to kubeconfig (which @mm4tt probbably knows more about)

Unless we are also leaking this kubeconfig metadata in the audit 🤔  (@spiffxp ?)

**Comment by spiffxp** [comment]
>Unless we are also leaking this kubeconfig metadata in the audit 🤔 (@spiffxp ?)

I haven't seen anything like that show up in our audit output.  We should be fine.  Thanks for explaining the ssh key stuff on that issue

**Comment by BenTheElder** [comment]
cc @cheftako

**Review by ohbus — APPROVED** [review]
/lgtm

**Pull request merged**
