### PR TITLE
Change add-on manifests to apps/v1

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Switches add-on manifests to apps/v1

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
xref https://github.com/kubernetes/kubernetes/issues/43214

**Does this PR introduce a user-facing change?**:
```release-note
Add-on manifests now use the apps/v1 API for DaemonSets, Deployments, and ReplicaSets
```

@kubernetes/sig-apps-pr-reviews 

/cc @kow3ns

### CODE REVIEW

**Comment by dims** [comment]
/lgtm

/hold

( change looks good, not sure if you want this merged right away hence the hold. please feel free to remove hold @liggitt )

**Comment by liggitt** [comment]
yes, this is ready
/hold cancel

**Pull request merged**
