### PR TITLE
Generate IP addresses for minions of large GCE clusters

### PR DESCRIPTION
**Pull request by satnam6502**
Generate a larger set of IP addresses to allow big GCE clusters to be created. @jbeda 
Perhaps the function should go in gce/util.sh although perhaps that creates mutual recursion.

### CODE REVIEW

**Comment by thockin** [comment]
ZOMG!  we need unit tests for our scripts now!

**Comment by satnam6502** [comment]
A unit test for bringing up a cluster?

**Comment by satnam6502** [comment]
The function probably does not belong in util.sh (mutual recursion).

**Comment by thockin** [comment]
IP math looks correct - I leave it to someone with more time this morning to review in context :)

**Comment by satnam6502** [comment]
Looks like @jbeda might not have time to look at this. If @thockin is happy then perhaps merge?

**Comment by thockin** [comment]
LGTM

**Pull request merged**
