### PR TITLE
Simplify func addRod  in kubelet (lock less)

### PR DESCRIPTION
**Pull request by NoicFank**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
1. Simplify the  func AddPod in kubelet
2. Reduce the scope of the lock in AddPod

#### Which issue(s) this PR fixes:

Fixes # NONE

#### Special notes for your reviewer:
NONE

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
NONE
```

### CODE REVIEW

**Comment by NoicFank** [comment]
@matthyx @sjenning PLAT, thanks.

**Comment by matthyx** [comment]
@NoicFank thanks for your PR!
From a first look it seems good, however I don't understand the problem you're trying to solve?
Is it a performance bottleneck you want to tackle?
I think answering those questions will help qualify this PR, add a release note and maybe add some tests.

**Comment by aojea** [comment]
> I think answering those questions will help qualify this PR, add a release note and maybe add some tests.

indeed, moving locking code on this area for not net value doesn't seem worthy

**Comment by SergeyKanzhelev** [comment]
/close

Thank you for your PR. It seems to only contain trivial edits. Please read our [trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits). We encourage you to take a look at confirmed issues and bugs or issues marked `help-wanted`.

Please let us know if this PR actually fixes any issue as mentioned above

**Pull request closed without merging**
