### PR TITLE
kubeadm: update supported etcd version list for 1.32

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
kubeadm: update supported etcd version list for 1.32

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Comment by neolit123** [comment]
/hold
is this something we are supposed to do now?
1.29 is still supported and there is no 1.32 yet?

https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm

**Comment by SataQiu** [comment]
Yes, I don't think there's any harm in supporting a few more versions.

**Review by neolit123 — COMMENTED** [review]
thanks
/lgtm

**Pull request merged**
