### PR TITLE
Remove deprecated storagev1alpha1.VolumeAttachment

### LINKED ISSUE #99827: v1alpha1.VolumeAttachment deprecation
#### What happened:

storage.k8s.io/v1alpha1/VolumeAttachment has been replaced with v1beta1 already since 1.10 and now with v1. Apparently it was never deprecated, though.

#### What you expected to happen:

- deprecation notice in 1.21
- removal in 1.22

/sig storage

### PR DESCRIPTION
**Pull request by ialidzhikov**
/kind api-change
/kind cleanup
/sig storage

Fixes #99827

#### Does this PR introduce a user-facing change?

```release-note
The already deprecated `VolumeAttachment` types under `k8s.io/api/storage/v1alpha1` are now removed. Please use the types under `k8s.io/api/storage/v1`.
```

### CODE REVIEW

**Review by pohly — APPROVED** [review]
/lgtm
/ok-to-test

**Comment by liggitt** [comment]
Stopping serving the REST API is fine, but up until 1.9, volumeattachments were stored in etcd in v1alpha1 format (https://github.com/kubernetes/kubernetes/blob/v1.9.0/test/integration/etcd/etcd_storage_path_test.go#L300-L305)

For a cluster upgraded since that version, what guarantees that all existing volume attachments have been re-persisted to etcd? If we cannot guarantee that, it is not safe to remove the go types and conversions, since that would prevent the API server from listing existing objects from etcd.

**Comment by deads2k** [comment]
> For a cluster upgraded since that version, what guarantees that all existing volume attachments have been re-persisted to etcd? If we cannot guarantee that, it is not safe to remove the go types and conversions, since that would prevent the API server from listing existing objects from etcd.

/hold

holding until we can get confirmation.  To my knowledge, there is no way to guarantee this today.

**Comment by msau42** [comment]
How do we remove alpha api versions today? My understanding is that alpha apis have no upgrade guarantees.

**Comment by liggitt** [comment]
> How do we remove alpha api versions today? My understanding is that alpha apis have no upgrade guarantees.

In the past, it's been done when introducing the beta API, with a release note indicating a cluster with the alpha API enabled must delete all instances before upgrading. Someone trying to upgrade from alpha to beta would have been stopped at that point.

**Comment by ialidzhikov** [comment]
> > How do we remove alpha api versions today? My understanding is that alpha apis have no upgrade guarantees.
> 
> In the past, it's been done when introducing the beta API, with a release note indicating a cluster with the alpha API enabled must delete all instances before upgrading. Someone trying to upgrade from alpha to beta would have been stopped at that point.

@liggitt I see that similar PR that drops the `batch/v2alpha1` API group - see https://github.com/kubernetes/kubernetes/pull/96987. What is the difference between this PR and https://github.com/kubernetes/kubernetes/pull/96987?
What is your suggestion to proceed with this PR?

**Comment by liggitt** [comment]
> @liggitt I see that similar PR that drops the `batch/v2alpha1` API group - see #96987. What is the difference between this PR and #96987?

CronJobs have an active built-in controller that writes updates to their status, which re-persists in the current storage version. I don't see the same for VolumeAttachments.

**Comment by ialidzhikov** [comment]
> CronJobs have an active built-in controller that writes updates to their status, which re-persists in the current storage version. I don't see the same for VolumeAttachments.

Okay, thanks for explaining. Then I guess #99827 is not that trivial.
I will close this PR for now as I don't have capacity to follow up on it.

**Pull request closed without merging**
