### PR TITLE
fix wrong bandwidth quota

### LINKED ISSUE #70014: bandwidth limit doesn't work
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
**What happened**:
bandwidth limit doesn't work
**What you expected to happen**:
bandwidth limit work
**How to reproduce it (as minimally and precisely as possible)**:
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#support-traffic-shaping
```
apiVersion: v1
kind: Pod
metadata:
  name: test
  annotations:
    kubernetes.io/ingress-bandwidth: 1M
    kubernetes.io/egress-bandwidth: 1M
spec:
  containers:
  - name: test
    image: nginx:1.13
```
```
Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "4df4f85bbe21bf7e1696d07aae18b544f9ff4e0010d0da14cd503fbe071582a6" network for pod "test": NetworkPlugin cni failed to set up pod "test_default" network: if rate is set, burst must also be set
```

**Anything else we need to know?**:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/network/cni/cni.go#L378-L385
```
if ingress != nil {
    bandwidthParam.IngressRate = int(ingress.Value() / 1000)
    bandwidthParam.IngressBurst = 0 // default to no limit
}
if egress != nil {
    bandwidthParam.EgressRate = int(egress.Value() / 1000)
    bandwidthParam.EgressBurst = 0 // default to no limit
}
```
https://github.com/containernetworking/plugins/blob/master/plugins/meta/bandwidth/main.go#L110-L113
```
case burst == 0 && rate != 0:
    return fmt.Errorf("if rate is set, burst must also be set")
case rate == 0 && burst != 0:
    return fmt.Errorf("if burst is set, rate must also be set")
```
**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.1
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Debian 8
- Kernel (e.g. `uname -a`): 4.9.0-0.bpo.6-amd64
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by ggaaooppeenngg**
Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
bandwidth quota is not right, tested on ubuntu 16.04, it should not be divided by 1000.
**Which issue(s) this PR fixes**:

Fixes #70014 

**Special notes for your reviewer**:
/sig network
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by MrHohn** [comment]
@m1093782566 Could you take a look? thanks!
/assign @m1093782566

**Comment by m1093782566** [comment]
/ok-to-test

LGTM

**Comment by ggaaooppeenngg** [comment]
@m1093782566 have a look.

**Comment by SataQiu** [comment]
Here's a similar PR.
Ref：#67438

**Review by johscheuer — COMMENTED** [review]
This is already in master (see: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/network/cni/cni.go#L411), so I assume this PR can be closed ?

**Pull request closed without merging**
