### PR TITLE
Make GeneralPredicates a MUST have predicate for scheduler

### LINKED ISSUE #71662: Scheduler's predicates should be matched against kubelet
**What would you like to be added**:
Make `GeneralPredicates` a MUST have predicate for scheduler.

**Why is this needed**:
Admin could configure scheduler's predicates. Take a extremely special case for example, we just configures `PodFitsHostPorts` predicates as following:

```
$ cat scheduler-policy.yaml
{
  "kind" : "Policy",
  "apiVersion" : "v1",
  "predicates" : [
      {"name" : "PodFitsHostPorts"}
    ],
   "priorities" : [
	{"name" : "MostRequestedPriority", "weight" : 100}
    ]
}
```
Suppose there are two kubelet nodes with same allocatable resource(kubelet A has 1 cpu and 500Mi left for allocating, kubelet B has 5 cpu and 2048Mi left for allocating), then user creates a deployment whose pod resource request is 3 cpu 1024Mi.  

According to the configure policy, scheduler will schedule the pod to kubelet A which does not have sufficient resource actually, because it just uses predicate `PodFitsHostPorts`. And kubelet will use `pkg/kubelet/lifecycle/predicates#Admit`(which calls `GeneralPredicates`) to admit, then rejects it because there is no sufficient resource.

The controller finds the pod rejected by kubelet, and creates a new pod, scheduler will schedule it to kubelet A again according to its policy. And kubelet A will reject it again.

The root cause is that scheduler use predicates configured by admin, and kubelet uses 
stable predicates, e.g. `GeneralPredicates`, they might not be matched.

As discussed in https://github.com/kubernetes/kubernetes/issues/67874, should we make GeneralPredicates as MUST in scheduler policy?

/kind feature

### PR DESCRIPTION
**Pull request by hex108**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Add GeneralPredicates as a MUST have predicate for scheduler.

**Which issue(s) this PR fixes**:

Fixes #71662

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
It will add predicate GeneralPredicates if admin did not add it.
```

### CODE REVIEW

**Comment by liggitt** [comment]
this invalidates existing configurations, correct?

**Comment by hex108** [comment]
@liggitt This PR will add predicates `GeneralPredicates` if admin did not add it, it does not affect other things.

**Comment by yastij** [comment]
/hold

Does this break existing configurations ? cc @bsalamat

**Review by bsalamat — CHANGES_REQUESTED** [review]
This change is incorrect. GeneralPredicates is not "a" predicate, it is a "set" of predicates. The scheduler runs each of those predicates individually. This PR would make the scheduler run them twice (with the default scheduler config).

**Comment by hex108** [comment]
@bsalamat Yes, it is a set of predicates. It includes `PodFitsResources`, 
 `EssentialPredicates`(including `PodFitsHost`, `PodFitsHostPorts`, `PodMatchNodeSelector`). If admin configure these predicates, we could remove them after adding `GeneralPredicates `, but I am not sure it is appropriate.

In fact, `GeneralPredicates` has been a default predicate. And if we use default configure, we will not add `GeneralPredicates` again.

**Pull request closed without merging**
