### PR TITLE
Using 'kubectl proxy' behind a reverse proxy

### LINKED ISSUE #100928: "kubectl proxy" not working behind a reverse proxy
We have multiple K8S environments

Every K8S environment is behind a firewall, so there is no direct access to K8S api-server (except some privileged hosts)

During our investigation we found out, that the kubectl proxy command does not work, behind a reverse proxy, when the routing requests using the query path.

  ```
                                    0
                      does work    /|\ does not work
                      +-----------  | ---------+
                      |            / \         |
                      |                        |
                      |                        | https://reverse-proxy/k8s-cluster/
                      |                        |
                      |                        v
                      |                +-------+-------+
                      |                |    reverse    |
                      |                |    proxy      |
                      |                |               |
 https://k8s-cluster/|                +-------+-------+
                      |                        |
                      |                        |
                      |                        |
                      |   +--------------------+
                      |   |
                      v   v
               +----------------+
               |                |
               |                |
               |   k8s cluster  |
               |                |
               |                |
               +----------------+
 ```

It does work, if the reverse proxy not using query path to route ( https://reverse-proxy/ -> https://k8s-cluster/ )

Obviously /reverse-proxy prefix is missing in the request

To reproduce:

## No reverse proxy
kubectl --insecure-skip-tls-verify --server https://k8s-server:6443 proxy
curl -D- localhost:8001/apis -> 200

## Reverse proxy not using query path to route
kubectl --insecure-skip-tls-verify --server https://reverse-proxy/ proxy
curl -D- localhost:8001/apis -> 200

## Reverse proxy with query path
kubectl --insecure-skip-tls-verify --server https://reverse-proxy/k8s-cluster/ proxy
curl -D- localhost:8001/apis -> 503

### PR DESCRIPTION
**Pull request by whiterm**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Using 'kubectl proxy' behind a reverse proxy

#### Which issue(s) this PR fixes:

Fixes #100928

### CODE REVIEW

**Comment by whiterm** [comment]
I signed it

**Comment by whiterm** [comment]
I signed it

**Comment by caesarxuchao** [comment]
The change makes sense to me. Not sure why the original code only proxy to the url.Host but not the full url. Is there any security concern? @deads2k do you know?

**Comment by caesarxuchao** [comment]
/assign @deads2k 

is there any security concern on proxying to the full path?

/remove-sig cli
/sig auth

**Comment by enj** [comment]
/remove-sig auth

Deferring to David in regards to the security aspects of this change.

**Pull request closed without merging**
