### PR TITLE
disable nfsv4 and use nfsv3

### LINKED ISSUE #22529: e2e nfs server image kernel dump
GCE minion VM OS version is
```
$ uname -a
Linux kubernetes-minion-z14o 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4google (2016-01-26) x86_64 GNU/Linux
```

The nfs server image [enables NFSv4](https://github.com/kubernetes/kubernetes/blob/master/test/images/volumes-tester/nfs/run_nfs.sh#L35) and hits [a known bug](https://lists.debian.org/debian-kernel/2014/09/msg00477.html) with the following dump stack

```text
[  291.871015] ------------[ cut here ]------------
[  291.875844] WARNING: CPU: 0 PID: 4433 at /mnt/ssd0/linux-3.16.7-ckt20/fs/nfsd/nfs4recover.c:530 nfsd4_legacy_tracking_init+0x1aa/0x240 [nfsd]()
[  291.888873] NFSD: attempt to initialize legacy client tracking in a container!
[  291.896249] Modules linked in: veth sg sch_htb xt_nat xt_REDIRECT xt_tcpudp xt_comment xt_conntrack iptable_filter ipt_MASQUERADE iptable_nat nf_conntrack_ipv4 nf_de
frag_ipv4 nf_nat_ipv4 xt_addrtype ip_tables x_tables nf_nat nf_conntrack bridge stp llc aufs(C) ib_iser rdma_cm iw_cm ib_cm ib_sa ib_mad ib_core ib_addr iscsi_tcp libis
csi_tcp libiscsi scsi_transport_iscsi nfsd auth_rpcgss oid_registry nfs_acl nfs lockd fscache sunrpc virtio_net crct10dif_pclmul crc32_pclmul crc32c_intel aesni_intel p
arport_pc parport i2c_piix4 i2c_core processor button psmouse aes_x86_64 lrw gf128mul thermal_sys glue_helper ablk_helper serio_raw cryptd evdev pcspkr ext4 crc16 mbcac
he jbd2 sd_mod crc_t10dif crct10dif_common virtio_scsi scsi_mod virtio_pci virtio virtio_ring
[  291.975112] CPU: 0 PID: 4433 Comm: rpc.nfsd Tainted: G        WC    3.16.0-4-amd64 #1 Debian 3.16.7-ckt20-1+deb8u4google
[  291.986302] Hardware name: Google Google, BIOS Google 01/01/2011
[  291.992590]  0000000000000009 ffffffff8150db3f ffff8800b96bbd80 ffffffff810677d7
[  292.000857]  ffff880129eabe00 ffff8800b96bbdd0 0000000000004000 0000000000000002
[  292.008939]  0000000000000000 ffffffff8106783c ffffffffa02ad9c8 ffff880100000018
[  292.017024] Call Trace:
[  292.019597]  [<ffffffff8150db3f>] ? dump_stack+0x41/0x51
[  292.025061]  [<ffffffff810677d7>] ? warn_slowpath_common+0x77/0x90
[  292.031567]  [<ffffffff8106783c>] ? warn_slowpath_fmt+0x4c/0x50
[  292.037772]  [<ffffffffa02a938a>] ? nfsd4_legacy_tracking_init+0x1aa/0x240 [nfsd]
[  292.045568]  [<ffffffffa02a94f1>] ? nfsd4_client_tracking_init+0x51/0x130 [nfsd]
[  292.053421]  [<ffffffffa02a3af2>] ? nfs4_state_start_net+0x2a2/0x340 [nfsd]
[  292.060635]  [<ffffffffa027eb20>] ? nfsd_svc+0x1d0/0x330 [nfsd]
[  292.066898]  [<ffffffffa027f600>] ? write_pool_threads+0x260/0x260 [nfsd]
[  292.074030]  [<ffffffffa027f68a>] ? write_threads+0x8a/0xf0 [nfsd]
[  292.080526]  [<ffffffff81141a5a>] ? __get_free_pages+0xa/0x50
[  292.086441]  [<ffffffff811cdbc0>] ? simple_transaction_get+0xa0/0xc0
[  292.093266]  [<ffffffffa027f093>] ? nfsctl_transaction_write+0x43/0x70 [nfsd]
[  292.100720]  [<ffffffff811a8562>] ? vfs_write+0xb2/0x1f0
[  292.106414]  [<ffffffff811a90a2>] ? SyS_write+0x42/0xa0
[  292.111788]  [<ffffffff81513d0d>] ? system_call_fast_compare_end+0x10/0x15
[  292.119062] ---[ end trace 9ae275fce49e7003 ]---
[  292.123836] NFSD: Unable to initialize client recovery tracking! (-22)
[  292.130690] NFSD: starting 10-second grace period (net ffff8800b1c4e080)
[  306.272014] cbr0: port 1(veth36a05d3) entered forwarding state
```

### PR DESCRIPTION
**Pull request by rootfs**
fix #22529

### CODE REVIEW

**Comment by fejta** [comment]
@jsafrane you're maintaining this image, right? If so will review this PR and assign back to me once it is in a state you like? Thanks!

**Comment by jsafrane** [comment]
I checked that the update image runs NFS server that can be mounted from elsewhere. However, e2e tests need to be changed to mount `<IP>:/exportfs` instead of `<IP>:/`

**Comment by rootfs** [comment]
@jsafrane this container still exports `/exports`. The change is that instead of directly `ADD index.html /exports/index.html`, the `run_nfs.sh` copies the file. The idea is that, `/exports` is a bind-mount, we can still ensure `index.html` can be copied to `/exports`.

**Comment by jsafrane** [comment]
@rootfs, in NFSv4, you can mount the export with fsid=0 as `'<host>:/'`. In NFSv3 you must mount complete path to exported directory, hence `'<host>:/exports'`.

**Comment by rootfs** [comment]
@jsafrane i see, i misread your first comment. I thought we need to export `/`.

**Comment by rootfs** [comment]
@jsafrane updated Dockerfile, both `/exports` and `/` are exported.

**Comment by jsafrane** [comment]
LGTM

**Comment by rootfs** [comment]
thanks @jsafrane 
@fejta  I cannot push to `gcr.io`, if you can help, that'll be great.

**Comment by jsafrane** [comment]
@k8s-bot, test this issue: 23350

**Comment by rootfs** [comment]
@fejta can you make the image? Thanks.

**Comment by fejta** [comment]
@rootfs I will create this image after the change is merged.

**Comment by rootfs** [comment]
@fejta Thanks. I am not sure how the tags are assigned. Can you update the tag once this fix is merged or are you comfortable if I can have another commit to update the tag?

**Comment by fejta** [comment]
See the Makefile I linked in the previous image, which presently [assigns a tag](https://github.com/kubernetes/kubernetes/blob/master/test/images/volumes-tester/nfs/Makefile#L24) of 0.5. Commiting a change that increases this to 0.6 or something ([squash](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/) it with the existing one) sounds like a great idea.

**Comment by rootfs** [comment]
@fejta Thanks. Tag updated and commits squashed.

**Comment by fejta** [comment]
Thanks much!

**Comment by fejta** [comment]
Working to push the image, will update when it is done.

**Comment by fejta** [comment]
Image version `gcr.io/google_containers/volume-nfs:0.6` now exists (and this is also what :latest refers to)

**Pull request merged**
