### PR TITLE
Backport issue 32551

### PR DESCRIPTION
**Pull request by bowei**
- Adds TCPCloseWaitTimeout option to kube-proxy for sysctl nf_conntrack_tcp_timeout_time_wait
- Add test image for networking related tests
- Update generated code

```release-note
Adds TCPCloseWaitTimeout option to kube-proxy for sysctl nf_conntrack_tcp_timeout_time_wait
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36099)

### CODE REVIEW

**Comment by bowei** [comment]
@k8s-bot verify test this

**Comment by bowei** [comment]
@k8s-bot verify test this

**Comment by bowei** [comment]
looks like failing due to godep issue

**Comment by jessfraz** [comment]
rebase after https://github.com/kubernetes/kubernetes/pull/36203 is merged to fix the godep issue

**Comment by bowei** [comment]
@k8s-bot verify test this

**Comment by bowei** [comment]
@jessfraz can you lgtm? or @thockin

**Comment by thockin** [comment]
LGTM

**Comment by jessfraz** [comment]
Thanks so much

**Pull request merged**
