### PR TITLE
update detailed help message for HTTPGetAction.Port

### LINKED ISSUE #48290: API documentation (kubectl explain) for readinessProbe.httpGet.port is misleading
Client/server version: v1.6.4

```
$ kubectl explain deployment.spec.template.spec.containers.readinessProbe.httpGet

...

   port	<string> -required-
     Name or number of the port to access on the container. Number must be in
     the range 1 to 65535. Name must be an IANA_SVC_NAME.
```

Note the `<string>` tag.

When I try to use this as the following in YAML:

```yaml
        readinessProbe:
          initialDelaySeconds: 2
          httpGet:
            path: "/"
            port: "80"
```

and pass it to `kubectl apply`, I get error:

```
$ kubectl apply -f deployment.yaml
The Deployment "hello-web" is invalid:
* spec.template.spec.containers[0].readinessProbe.httpGet.port: Invalid value: "80": must contain at least one letter or number (a-z, 0-9)
```

When I remove quotes and send to API as `port: 80` (as integer), it works.

It looks like the type information for this field is misleading. Maybe we should have a better error message for intorstring fields.

/sig api-machinery

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

**Which issue this PR fixes** : fixes #48290

**Special notes for your reviewer**:

@ahmetb @kargakis 

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by ahmetb** [comment]
This does not fix #48290. Problems outlined in that issue:

- swagger spec shows `port` field is `string` however it's string or int &rarr; this PR doesn't fix this.
- error message `Invalid value: "80": must contain at least one letter or number (a-z, 0-9)` is unhelpful &rarr; in this PR, I cannot see how you fixed this message to tell users this field is either an int, or a string.

**Comment by dixudx** [comment]
@ahmetb 

* About the error message:
   Actually another PR #48413 was used to fix this. The error msg *"Invalid value: "80": must contain at least one letter or number (a-z, 0-9)"* you mentioned was caused by method [`ValidatePortNumOrName`](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go#L1846-L1860). When the type is *String*, it is treated as Name instead of *PortNum in string type*.

   But the later hanlder [`runHTTPHandler`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/lifecycle/handlers.go#L121) in kubelet will make a first attempt to parse it as an integer.  If that fails, an attempt is made to find a port with the same name in the container spec.

   The behavior is a little bit different.

   Also the method [`ValidatePortNumOrName`](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/validation/validation.go#L1846-L1860) is used by other port validations. I am afraid directly modifying the behavior would break some codes. I would like to have another PR focusing on these validations. WDYT?

* Swagger spec:
   Currently the [supported data types](https://swagger.io/specification/#data-types-12) does not include something like "int-or-string". But we can achieve this in OPENAPI.

To incorporate swagger spec, we'd better make some limitations. So I closed #48413 and opened this new one.

**Comment by shiywang** [comment]
I was wondering can we add a new validation func behaviors just like [runHTTPHandler]( https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/lifecycle/handlers.go#L121) or doing that in converting, @liggitt is this possible ?

**Comment by shiywang** [comment]
@liggitt we can't doing the behaviors like `runHTTPHandler` in api validation or converting right ? if so, I think this docs enhance is ok.

**Comment by dixudx** [comment]
keep open

**Pull request closed without merging**
