### PR TITLE
remove trusty GCE kube-up.sh

### PR DESCRIPTION
**Pull request by mikedanese**
Asked on the mailing list. No one objected. Lot's of people were in favor.

cc @roberthbailey 

```release-note
Remove support for trusty in GCE kube-up.
```

### CODE REVIEW

**Comment by pipejakob** [comment]
Mechanically, this change looks fine to me, but I don't have much context on who might have been using this in the first place or why we should remove it now, so you'll probably want approval from someone with that context.

/lgtm

**Comment by justinsb** [comment]
@k8s-bot non-cri e2e test this
@k8s-bot unit test this
@k8s-bot kops aws e2e test this

**Review by zmerlynn — APPROVED** [review]
/lgtm

**Comment by roberthbailey** [comment]
I've tagged this for the 1.6 branch since we don't want to ship a 1.6 release with broken getting started scripts. 

/lgtm

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
@k8s-bot non-cri e2e test this

**Comment by mikedanese** [comment]
@k8s-bot crossbuild this

**Comment by dchen1107** [comment]
@mikedanese Which mailing list your email sent to originally? I couldn't find it from my inbox.

**Pull request merged**
