### PR TITLE
Add Leader Election to federation-controller-manager

### PR DESCRIPTION
**Pull request by kshafiee**
This PR is to add "leader election" to 'federation-controller-manager'. 

The implementation method is the result of discussion in PR #35878 

cc @kubernetes/sig-cluster-federation

### CODE REVIEW

**Comment by zhouhaibing089** [comment]
general comment, what is the difference between `federation/client/leaderelection` and `pkg/client/leaderelection`?

**Comment by kshafiee** [comment]
@zhouhaibing089 
The reason we can't use `pkg/client/leaderelection` as is for federation is that we don't have Endpoints API in federation. So, in this PR I added `federation/client/leaderelection` that uses Secrets API instead

**Comment by zhouhaibing089** [comment]
@kshafiee I see there is a comment mentioned using the events api, the way I am thinking about this is either 1 or 2:

1.  did some changes on the existing leader election library, and make it an option to use endpoints api or events api, or anything else.
2.  add the endpoints object kind in federation-apiserver.

The (*mostly*)duplicate code does not seem right.

**Comment by kshafiee** [comment]
@madhusudancs was wondering if you could take a look at this PR and provide feedback please. Thx!

**Comment by quinton-hoole** [comment]
@kshafiee I agree with @zhouhaibing089 https://github.com/kubernetes/kubernetes/pull/39375#issuecomment-270303228 point 1 above.  I'd prefer to make minor modifications to the existing leader election code to enable it to use something other than endpoints (e.g. Secrets), rather than duplicate all of the code.

**Comment by zhouhaibing089** [comment]
@kshafiee it is already possible now: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/leaderelection/resourcelock/interface.go#L52.

The endpoint-based implementation is https://github.com/kubernetes/kubernetes/blob/master/pkg/client/leaderelection/resourcelock/endpointslock.go#L29.

**Comment by kshafiee** [comment]
Thank you @zhouhaibing089 @quinton-hoole for your feedback!

I moved `secretslock` under `pkg/client/leaderelection/resourcelock`. Now leader election can be done using any of `secret` or `endpoint` resource.

**Comment by kshafiee** [comment]
Hi @quinton-hoole just a kind reminder to take a look at this and let me know if this is actually what you meant. Thx much!

**Comment by quinton-hoole** [comment]
@kshafiee Apologies for my delay replying. It's still not clear to me that this is a good way to go about this.

Even excluding the autogenerated code, there are hundreds of lines of essentially cut 'n paste code here, when all that has really changed is the API type where the locks are stored.  endpointslock.go and secretslock.go, and all their reated tests are essentially identical.  Isn't it possible and better to create a common interface structure and code for all of this instead?

**Comment by mikedanese** [comment]
Please don't start adding arbitrary resources to be leaderelection targets. Secrets are meant to be used for things that are secret. What resources does federated apiserver support? Does it support third_party resource?

**Comment by quinton-hoole** [comment]
No, third party resources are not supported (yet).

The current leader election implementation stores it's locks in endpoints
(which seem even less appropriate than secrets). @mikedanese perhaps
ConfigMaps are the best of several not-great options here?

**Comment by mikedanese** [comment]
@quinton-hoole a leader is an attribute of a group of networked processes which in kubernetes is represented as the Endpoints object. That API design wasn't picked arbitrarily. Is there a list of resources that federation apiserver supports that I could look at? ConfigMap is better than Secret.

**Comment by kshafiee** [comment]
@mikedanese @quinton-hoole I would like to invite you to take a look at previous discussion on #35878 the previous PR that I closed, particularly the comment from @madhusudancs 

Madhu mentioned based on the discussion with Nikhil & Quinton one solution is to use secrets API

**Comment by quinton-hoole** [comment]
@mikedanese the list of API types supported by federation is here:

https://kubernetes.io/docs/user-guide/federation/#api-resources

Q

On Feb 21, 2017 14:18, "kshafiee" <notifications@github.com> wrote:

@mikedanese <https://github.com/mikedanese> @quinton-hoole
<https://github.com/quinton-hoole> I would like to invite you to take a
look at previous discussion on #35878
<https://github.com/kubernetes/kubernetes/pull/35878> the previous PR that
I closed, particularly the comment from @madhusudancs
<https://github.com/madhusudancs>

Madhu mentioned based on the discussion with Nikhil & Quinton one solution
is to use secrets API

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/39375#issuecomment-281500146>,
or mute the thread

**Comment by quinton-hoole** [comment]
@kshafiee to be clear, I personally don't care very much at all which
object type is used under the hood to store the lock. I consider that to be
a somewhat arbitrary choice.

What I do object to is the amount of cut n paste code in this PR. The API
type used (endpoint, secret, configmap, whatever) only needs to fulfill the
property of having object metadata including labels/annotations. All API
types have those.  So I think that all you need to define is that
interface, and a factory method to create objects of a given type and that
interface. That would be just a few lines of code, and support all API
types, not just secrets.

**Comment by mikedanese** [comment]
I would approve a ConfigMap implementation. Thanks.

**Pull request closed without merging**
