### PR TITLE
Remove unused chmod/chown abstractions

### PR DESCRIPTION
**Pull request by rata**
**What this PR does / why we need it**: Simplifies the code

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rata** [comment]
(I'm a reviewer in owners file for other path, so maybe I can give run the tests)

@k8s-bot ok to test

**Comment by rata** [comment]
Ohh, okay. I can't give the ok-to-test. I will play with it more in my computer, but it might take a few hours as it's pretty old :)

**Comment by thockin** [comment]
@k8s-bot ok to test

**Comment by thockin** [comment]
I forget why these were added.  Ostensibly for testing, but not used as such.

/lgtm
/approve

**Comment by rata** [comment]
@thockin thanks a lot :)

**Pull request merged**
