### PR TITLE
Fixed : NodePort Service Lost Ipvs Target

### LINKED ISSUE #114440: NodePort service for hostNetwork pod fails when both Ready and Terminating pods are present
### What happened?

We had a nodePort service which use port 30002, transport to a host-network pod which listen 8002.Now it is invalid , we can't access `nodeIp:30002` , but `nodeIp:8002` is valid.

> why we use nodePort when we already use host-network?
Because it could has multiple replicas, we use nodePort to ensure it's avaliable when one pod is down.

1. we check ipvs rules,it's like :
```
ipvsadm -L -n 
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  172.17.0.1:30002 rr
TCP  172.17.0.1:30009 rr
  -> 10.16.203.62:8002
```

We all see , `30002` doesn't have any target.

2. we check endpont status ,it's like:

We all see , the same ipaddr is both in Addresses and NotReadyAddress.

And , there are some invalid pods and one valid pod , this is why the endpoint looks like.

### What did you expect to happen?

if an ipaddr is both in readyAddrs and notReadyAddrs, it shouled be removed  from notReadyAddrs to make sure that
valid IP addresses are not masked by invalid IP addresses。Then the url `http://nodeIP:30002` we called will always be accessible  whenever the deployment has invalid pods or not.

### How can we reproduce it (as minimally and precisely as possible)?

1. apply a pod which use host-network , and bind to a fixed node; the pod shouled not has request and limit value ,ensure is is `BestEffort` , so it will be evicited first.
2. apply a service which use nodePort 30002, and bind to the pod
3. manual  make a Diskpressure which is easily caused by dd a big file.
4. the pod will be evicited ,
5. move the Diskpressure ,And the pod will be created 
6. Then you will reproduce it , the endpoint will has the nodeIp both in readyAddrs and notReadyAddrs.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# v1.22.4
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Kylin Linux Advanced Server"
VERSION="V10 (Tercel)"
ID="kylin"
VERSION_ID="V10"
PRETTY_NAME="Kylin Linux Advanced Server V10 (Tercel)"
ANSI_COLOR="0;31"
$ uname -a
Linux i-24AFE987 4.19.90-21.2.ky10.aarch64 #1 SMP Tue Oct 27 16:46:15 CST 2020 aarch64 aarch64 aarch64 GNU/Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>
containerd -v
containerd github.com/containerd/containerd v1.6.2 de8046a5501db9e0e478e1c10cbcfb21af4c6b2d
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by jason-i-vv**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #114440 

this pr has been tested , which can solve the issue. 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by jason-i-vv** [comment]
> @jason-i-vv: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-kubernetes-node-e2e-containerd	[7a505f9](https://github.com/kubernetes/kubernetes/commit/7a505f98cb41102ed85d5ce8c810fac231d71521)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114441/pull-kubernetes-node-e2e-containerd/1603023075564064768/)	true	`/test pull-kubernetes-node-e2e-containerd`
> pull-kubernetes-conformance-kind-ga-only-parallel	[7a505f9](https://github.com/kubernetes/kubernetes/commit/7a505f98cb41102ed85d5ce8c810fac231d71521)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114441/pull-kubernetes-conformance-kind-ga-only-parallel/1603023075463401472)	true	`/test pull-kubernetes-conformance-kind-ga-only-parallel`
> pull-kubernetes-e2e-kind-ipv6	[7a505f9](https://github.com/kubernetes/kubernetes/commit/7a505f98cb41102ed85d5ce8c810fac231d71521)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114441/pull-kubernetes-e2e-kind-ipv6/1603023075413069824)	true	`/test pull-kubernetes-e2e-kind-ipv6`
> pull-kubernetes-e2e-kind	[7a505f9](https://github.com/kubernetes/kubernetes/commit/7a505f98cb41102ed85d5ce8c810fac231d71521)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114441/pull-kubernetes-e2e-kind/1603023075341766656)	true	`/test pull-kubernetes-e2e-kind`
> pull-kubernetes-unit	[7a505f9](https://github.com/kubernetes/kubernetes/commit/7a505f98cb41102ed85d5ce8c810fac231d71521)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114441/pull-kubernetes-unit/1603023075509538816)	true	`/test pull-kubernetes-unit`
> pull-kubernetes-e2e-gce	[7a505f9](https://github.com/kubernetes/kubernetes/commit/7a505f98cb41102ed85d5ce8c810fac231d71521)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114441/pull-kubernetes-e2e-gce/1603023075228520448/)	true	`/test pull-kubernetes-e2e-gce`
> pull-kubernetes-e2e-gce-100-performance	[7a505f9](https://github.com/kubernetes/kubernetes/commit/7a505f98cb41102ed85d5ce8c810fac231d71521)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114441/pull-kubernetes-e2e-gce-100-performance/1603023075631173632)	true	`/test pull-kubernetes-e2e-gce-100-performance`
> pull-kubernetes-verify	[7a505f9](https://github.com/kubernetes/kubernetes/commit/7a505f98cb41102ed85d5ce8c810fac231d71521)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114441/pull-kubernetes-verify/1603023076843327488)	true	`/test pull-kubernetes-verify`
> pull-kubernetes-integration	[7a505f9](https://github.com/kubernetes/kubernetes/commit/7a505f98cb41102ed85d5ce8c810fac231d71521)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114441/pull-kubernetes-integration/1603214953550974976)	true	`/test pull-kubernetes-integration`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=114441). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Ajason-i-vv). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

@dims Should I do something to work this test? It's my first pr , don't know why this is failed. sorry to bother you！

**Comment by danwinship** [comment]
You can click the "Details" links to see the test results. It appears that your patch has a bug:

```
Failed  === RUN   TestPackSubsets
--- FAIL: TestPackSubsets (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xee7999]

goroutine 19 [running]:
testing.tRunner.func1.2({0xf6f400, 0x16c74e0})
	/usr/local/go/src/testing/testing.go:1396 +0x372
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1399 +0x5f0
panic({0xf6f400, 0x16c74e0})
	/usr/local/go/src/runtime/panic.go:890 +0x262
k8s.io/kubernetes/pkg/api/v1/endpoints.RepackSubsets({0xc000116b90, 0x1, 0xf2f840?})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/api/v1/endpoints/util.go:80 +0xd39
...
```

**Comment by danwinship** [comment]
The commit message should talk about the bug that you're fixing (something something same IP is considered both ready and not ready), not the downstream manifestation of that bug (NodePort / ipvs).

But I'm not quite sure if this fix is correct... I'll follow up on the issue

**Comment by aojea** [comment]
it needs a regression test too

**Comment by jason-i-vv** [comment]
thanks, I got the failed reason,will check it. 
/cc @danwinship

**Comment by jason-i-vv** [comment]
image
@danwinship  why this job `pull-kubernetes-verify` failed? I already solved the job `pull-kubernetes-unit`.

**Comment by aojea** [comment]
/hold

It still needs some clarifications on the open issue

**Comment by danwinship** [comment]
/close
confirmed in the linked issue that this was already fixed in the latest release

**Pull request closed without merging**
