### PR TITLE
Fix enable_cluster_dns test

### LINKED ISSUE #4118: enable_cluster_dns test for kubelet service is broken
https://github.com/GoogleCloudPlatform/kubernetes/blame/master/cluster/saltbase/salt/kubelet/default#L32

That test should be ```{% if pillar.get('enable_cluster_dns', '').lower() == 'true' %}```, like here: https://github.com/GoogleCloudPlatform/kubernetes/blob/55793ac2066745f7243c666316499e1a8cf074f0/cluster/saltbase/salt/kube-addons/init.sls#L12

The boolean vs string situtation here does not fill me with joy, but we need to do a string-comparison, not a boolean-test here.

### PR DESCRIPTION
**Pull request by justinsb**
Fixes #4118

### CODE REVIEW

**Comment by thockin** [comment]
Could you also tackle cluster/saltbase/salt/top.sls - 2 very similar instances and 2 sort-of similar instances there.

cluster/saltbase/salt/top.sls
11:{% if pillar['enable_node_monitoring'] is defined and pillar['enable_node_monitoring'] %}
14:{% if pillar['enable_node_logging'] is defined and pillar['enable_node_logging'] %}
15:  {% if pillar['logging_destination'] is defined and pillar['logging_destination'] == 'elasticsearch' %}
18:  {% if pillar['logging_destination'] is defined and pillar['logging_destination'] == 'gcp' %}

cluster/saltbase/salt/kubelet/default
32:{% if pillar['enable_cluster_dns'] is defined and pillar['enable_cluster_dns'] %}

**Comment by justinsb** [comment]
Do you want me to do this, or are you doing it?  Happy either way.

If you want me to do it, just assign it to me in Github.

**Comment by justinsb** [comment]
I think these two are OK, BTW (unless there's another problem I'm not seeing!):

15: {% if pillar['logging_destination'] is defined and pillar['logging_destination'] == 'elasticsearch' %}
18: {% if pillar['logging_destination'] is defined and pillar['logging_destination'] == 'gcp' %}

**Comment by thockin** [comment]
I was hoping you'd do it since you have a PR open :)

I thought maybe those two should become .get() also to stay consistent, but
I am a relative newb to salt idioms.

**Comment by zmerlynn** [comment]
I think my weird ".get() ==" isn't exactly idomatic, because our use of quoted truth isn't exactly idiomatic. I used it because it made sense for me in Python, but I'm no Salt-speaker either.

**Comment by justinsb** [comment]
Sorry to disappoint, but I don't speak Salt either!

The get() makes sense to me from Python (and I think we're in Jinja, so Python)  But I have no idea about what is idomatic Salt (Salty?).

I'll fix the definitely-broken ones.  I suggest that I don't fix the two which aren't broken, unless someone has a strong opinion.

**Comment by justinsb** [comment]
(There are also a few more occurences of the non-broken case):

cluster/saltbase/salt/sdn/init.sls:{% if grains.network_mode is defined and grains.network_mode == 'openvswitch' %}
cluster/saltbase/salt/top.sls:  {% if pillar['logging_destination'] is defined and pillar['logging_destination'] == 'elasticsearch' %}
cluster/saltbase/salt/top.sls:  {% if pillar['logging_destination'] is defined and pillar['logging_destination'] == 'gcp' %}
cluster/saltbase/salt/top.sls:{% if grains['cloud'] is defined and grains['cloud'] == 'azure' %}
cluster/saltbase/salt/top.sls:{% if grains['cloud'] is defined and grains['cloud'] == 'azure' %}

**Comment by thockin** [comment]
SGTM

**Comment by justinsb** [comment]
I did push a new version of this fix BTW (not sure exactly how alerts work etc)

**Comment by zmerlynn** [comment]
LGTM

**Comment by thockin** [comment]
I am running a quick cluster up with this before commit

**Pull request merged**
