### PR TITLE
Update docs for promoting PodHealthyPolicy of PDB to beta

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3017-pod-healthy-policy-for-pdb
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/triage accepted
/priority important-longterm

**Comment by liggitt** [comment]
/lgtm
/approve

doc change only

**Comment by liggitt** [comment]
no release note needed, that's already included in https://github.com/kubernetes/kubernetes/pull/115363

**Comment by pacoxu** [comment]
/retitle Update docs for promoting PodHealthyPolicy of PDB to beta

**Pull request merged**
