### PR TITLE
WIP: cleanup: Removes redundant checks before returns

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

There are a few redundant checks that are being made in code, making it more verbose and slower than it should.

This removes some of these checks.

#### Which issue(s) this PR fixes:

Fixes: None.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
This will have a better chance of getting reviewed if you do a PR for each SIG

**Comment by claudiubelu** [comment]
> This will have a better chance of getting reviewed if you do a PR for each SIG

Indeed, this touched a lot of files, making it hard to review. This is still WIP at the moment, and I'll split this up when it's ready. Currently trying to find other relevant patterns to add. There are many more similar cases in the generated code, but can't do anything for that at the moment.

**Comment by SergeyKanzhelev** [comment]
/close

please re-open if still needed and ideally do it package by package

**Pull request closed without merging**
