### PR TITLE
fix all keps links 404 for kep folder migration

### PR DESCRIPTION
**Pull request by pacoxu**
**What type of PR is this?**
/kind documentation
/kind cleanup

**What this PR does / why we need it**:
Since enhancements changed the KEP folder structure and many KEP link breaks.
- [ ] #98216 fix broken links to KEPs in swagger.json
- [x] #95980  fix one `kubectl debug KEP link ` of those.

It seems that using enhancements issues/PR link is better than master links

**Which issue(s) this PR fixes**:
part of https://github.com/kubernetes/enhancements/issues/2220

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
None
```

### CODE REVIEW

**Comment by pacoxu** [comment]
/assign @alejandrox1 
/assign @deads2k @jsafrane @mrunalp @sttts @tpepper 
For files in your sig.

**Comment by tpepper** [comment]
/assign @wilsonehusin @justaugustus 
/unassign @tpepper 
for CHANGELOG/

**Comment by wilsonehusin** [comment]
/lgtm
/approve
for CHANGELOG/

**Pull request merged**
