### PR TITLE
Generate fake clientset for release_1_2

### PR DESCRIPTION
**Pull request by caesarxuchao**
1. move the ClientGenArgs struct to a separate package so both generator-for-clientset.go and generator_fake_for_clientset.go can use it.
2. move the generated fake clientset to pkg/client/clientset_generated/<versions>/fake
3. generate the fakes for release_1_2 clientset for the first time.

TODO: move the discovery client and the fake discovery client to a separate package.

cc @lavalamp

### CODE REVIEW

**Comment by krousey** [comment]
@k8s-bot ok to test

**Comment by krousey** [comment]
This LGTM. Squash and apply label.

**Comment by caesarxuchao** [comment]
Squashed. Applying the label per previous comment. Thanks @krousey.

**Comment by caesarxuchao** [comment]
@k8s-oncall, travis is really slow (2+ hours), anyway to bypass it?

**Comment by pwittrock** [comment]
as long as e2e and unit/integration pass you shouldn't need travis for the sq

**Comment by caesarxuchao** [comment]
@pwittrock thanks for the info.

**Comment by caesarxuchao** [comment]
No production code uses the versioned client yet, adding the e2e-not-required label.

**Pull request merged**
