### PR TITLE
Automated cherry pick of #69077: Add fallbacks for getting node IP from Azure IMDS

### PR DESCRIPTION
**Pull request by feiskyer**
Cherry pick of #69077 on release-1.11.

#69077: Add fallbacks for getting node IP from Azure IMDS

### CODE REVIEW

**Comment by feiskyer** [comment]
@andyzhangx @khenidak Could you help to take a look at this?

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by feiskyer** [comment]
ping @foxish for cherry pick approval

**Pull request merged**
