### PR TITLE
Update the CleanupAndExit field for the Options and the OnServiceSynced for the ServiceHandler comment

### PR DESCRIPTION
**Pull request by xigang**
Update the CleanupAndExit field for the Options and the OnServiceSynced for the ServiceHandler comment

**What type of PR is this?**
 /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Update the CleanupAndExit field  comment for the Options and the OnServiceSynced comment for the ServiceHandler

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xigang** [comment]
cc @danwinship @dcbw

**Comment by danwinship** [comment]
/ok-to-test
/lgtm
(although --cleanup-and-exit is probably going away soon anyway)

**Pull request closed without merging**
