### PR TITLE
Mark reason for lint in pkg/controller/nodelifecycle/config/v1alpha1

### PR DESCRIPTION
**Pull request by lianghao208**
Mark reason for lint errors in:
pkg/controller/nodelifecycle/config/v1alpha1,
pkg/controller/podautoscaler/config/v1alpha1,
pkg/controller/nodeipam/config/v1alpha1

**What type of PR is this?**
/kind cleanup

**Which issue(s) this PR fixes**:

Fixes [#68026](https://github.com/kubernetes/kubernetes/issues/68026)

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by lianghao208** [comment]
Can someone label this PR to /ok-to-test ? Thanks! @MHBauer @pwittrock @lavalamp @juanvallejo

**Review by MHBauer — COMMENTED** [review]
I'm fine with this, but please squash everything.

Add a mention that these underscores are automatically generated from gengo. Both the comment and the one single commit message, please.

Ought to be able to skip tests for things like this, but
/ok-to-test

**Review by lianghao208 — COMMENTED** [review]
these underscores are automatically generated from gengo.

**Pull request closed without merging**
