### PR TITLE
remove AddToGroupVersion in kubeproxy scheme

### PR DESCRIPTION
**Pull request by yanxuean**
ref https://github.com/kubernetes/kubernetes/pull/53645#discussion_r148850279
Signed-off-by: yanxuean <yan.xuean@zte.com.cn>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
/assign @ncdc

### CODE REVIEW

**Comment by yanxuean** [comment]
test record
1.kube-proxy config
```yaml
[cloud@cloud-test2:/etc/kubernetes]$ cat proxy-config.yaml
apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: 0.0.0.0
clientConnection:
  kubeconfig: "/etc/kubernetes/proxy.kubeconfig"
  acceptContentTypes: ""
  burst: 10
  contentType: application/vnd.kubernetes.protobuf
  qps: 5
clusterCIDR: ""
configSyncPeriod: 15m0s
conntrack:
  max: 0
  maxPerCore: 32768
  min: 131072
  tcpCloseWaitTimeout: 1h0m0s
  tcpEstablishedTimeout: 24h0m0s
enableProfiling: false
featureGates: ""
healthzBindAddress: 0.0.0.0:10256
hostnameOverride: ""
iptables:
  masqueradeAll: false
  masqueradeBit: 14
  minSyncPeriod: 0s
  syncPeriod: 30s
ipvs:
  minSyncPeriod: 0s
  scheduler: ""
  syncPeriod: 30s
kind: KubeProxyConfiguration
metricsBindAddress: 127.0.0.1:10249
mode: ""
oomScoreAdj: -777
portRange: ""
resourceContainer: /kube-proxy
udpTimeoutMilliseconds: 250ms
``` 
2. kube-config
```yaml
[cloud@cloud-test2:/etc/kubernetes]$ cat proxy.kubeconfig
apiVersion: v1
kind: Config
current-context: proxy-to-cluster.local
preferences: {}
contexts:
- context:
    cluster: cluster.local
    user: proxy
  name: proxy-to-cluster.local
clusters:
- cluster:
    #certificate-authority: /etc/kubernetes/certs/ca.crt
    server: http://172.120.0.209:8080
  name: cluster.local
users:
- name: proxy
  user:
    token: G0bCFkRokxukVPgbiTSZrev07V83v1Zg

```

3. kube-proxy  commandline
```bash
sudo ./kube-proxy.new --config proxy-config.yaml --logtostderr=true --v=5
```


4. kube-proxy log
The setting of this parameter “oomScoreAdj” takes effect.
```
[cloud@cloud-test2:/etc/kubernetes]$ sudo ./kube-proxy.new --config proxy-config.yaml --logtostderr=true --v=5
I1115 10:47:45.633554    1419 feature_gate.go:184] feature gates: map[]
I1115 10:47:45.633702    1419 server.go:334] option: &app.Options{ConfigFile:"proxy-config.yaml", WriteConfigTo:"", CleanupAndExit:false, config:(*kubeproxyconfig.KubeProxyConfiguration)(0xc4201fc000), master:"", healthzPort:10256, scheme:(*runtime.Scheme)(0xc4204f7f00), codecs:serializer.CodecFactory{scheme:(*runtime.Scheme)(0xc4204f7f00), serializers:[]serializer.serializerType{serializer.serializerType{AcceptContentTypes:[]string{"application/json"}, ContentType:"application/json", FileExtensions:[]string{"json"}, EncodesAsText:true, Serializer:(*json.Serializer)(0xc4204f7f40), PrettySerializer:(*json.Serializer)(0xc4204f7f80), AcceptStreamContentTypes:[]string(nil), StreamContentType:"", Framer:json.jsonFramer{}, StreamSerializer:(*json.Serializer)(0xc4204f7f40)}, serializer.serializerType{AcceptContentTypes:[]string{"application/yaml"}, ContentType:"application/yaml", FileExtensions:[]string{"yaml"}, EncodesAsText:true, Serializer:(*json.Serializer)(0xc4204f7fc0), PrettySerializer:runtime.Serializer(nil), AcceptStreamContentTypes:[]string(nil), StreamContentType:"", Framer:runtime.Framer(nil), StreamSerializer:runtime.Serializer(nil)}, serializer.serializerType{AcceptContentTypes:[]string{"application/vnd.kubernetes.protobuf"}, ContentType:"application/vnd.kubernetes.protobuf", FileExtensions:[]string{"pb"}, EncodesAsText:false, Serializer:(*protobuf.Serializer)(0xc420254960), PrettySerializer:runtime.Serializer(nil), AcceptStreamContentTypes:[]string(nil), StreamContentType:"", Framer:protobuf.lengthDelimitedFramer{}, StreamSerializer:(*protobuf.RawSerializer)(0xc42012dcb0)}}, universal:(*recognizer.decoder)(0xc4202a1e20), accepts:[]runtime.SerializerInfo{runtime.SerializerInfo{MediaType:"application/json", EncodesAsText:true, Serializer:(*json.Serializer)(0xc4204f7f40), PrettySerializer:(*json.Serializer)(0xc4204f7f80), StreamSerializer:(*runtime.StreamSerializerInfo)(0xc42012dd10)}, runtime.SerializerInfo{MediaType:"application/yaml", EncodesAsText:true, Serializer:(*json.Serializer)(0xc4204f7fc0), PrettySerializer:runtime.Serializer(nil), StreamSerializer:(*runtime.StreamSerializerInfo)(nil)}, runtime.SerializerInfo{MediaType:"application/vnd.kubernetes.protobuf", EncodesAsText:false, Serializer:(*protobuf.Serializer)(0xc420254960), PrettySerializer:runtime.Serializer(nil), StreamSerializer:(*runtime.StreamSerializerInfo)(0xc42012dd40)}}, legacySerializer:(*json.Serializer)(0xc4204f7f40)}}
I1115 10:47:45.633872    1419 server.go:335] option.config: &kubeproxyconfig.KubeProxyConfiguration{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, FeatureGates:"", BindAddress:"0.0.0.0", HealthzBindAddress:"0.0.0.0:10256", MetricsBindAddress:"127.0.0.1:10249", EnableProfiling:false, ClusterCIDR:"", HostnameOverride:"", ClientConnection:kubeproxyconfig.ClientConnectionConfiguration{KubeConfigFile:"/etc/kubernetes/proxy.kubeconfig", AcceptContentTypes:"", ContentType:"application/vnd.kubernetes.protobuf", QPS:5, Burst:10}, IPTables:kubeproxyconfig.KubeProxyIPTablesConfiguration{MasqueradeBit:(*int32)(0xc4201f70fc), MasqueradeAll:false, SyncPeriod:v1.Duration{Duration:30000000000}, MinSyncPeriod:v1.Duration{Duration:0}}, IPVS:kubeproxyconfig.KubeProxyIPVSConfiguration{SyncPeriod:v1.Duration{Duration:30000000000}, MinSyncPeriod:v1.Duration{Duration:0}, Scheduler:""}, OOMScoreAdj:(*int32)(0xc4201f712c), Mode:"", PortRange:"", ResourceContainer:"/kube-proxy", UDPIdleTimeout:v1.Duration{Duration:250000000}, Conntrack:kubeproxyconfig.KubeProxyConntrackConfiguration{Max:(*int32)(0xc4201f7070), MaxPerCore:(*int32)(0xc4201f7074), Min:(*int32)(0xc4201f7078), TCPEstablishedTimeout:(*v1.Duration)(0xc4201f70c0), TCPCloseWaitTimeout:(*v1.Duration)(0xc4201f70a0)}, ConfigSyncPeriod:v1.Duration{Duration:900000000000}}
I1115 10:47:45.637125    1419 iptables.go:588] couldn't get iptables-restore version; assuming it doesn't support --wait
W1115 10:47:45.645418    1419 server_others.go:269] Flag proxy-mode="" unknown, assuming iptables proxy
I1115 10:47:45.647506    1419 server_others.go:124] Using iptables Proxier.
W1115 10:47:45.651304    1419 server.go:582] Failed to retrieve node info: nodes "cloud-test2" not found
W1115 10:47:45.651436    1419 proxier.go:471] invalid nodeIP, initializing kube-proxy with 127.0.0.1 as nodeIP
W1115 10:47:45.651453    1419 proxier.go:476] clusterCIDR not specified, unable to distinguish between internal and external traffic
I1115 10:47:45.651510    1419 proxier.go:506] minSyncPeriod: 0s, syncPeriod: 30s, burstSyncs: 2
I1115 10:47:45.652403    1419 server_others.go:157] Tearing down inactive rules.
I1115 10:47:45.652476    1419 iptables.go:418] running iptables -C [OUTPUT -t nat -m comment --comment handle ClusterIPs; NOTE: this must be before the NodePort rules -j KUBE-PORTALS-HOST]
I1115 10:47:45.654084    1419 iptables.go:418] running iptables -C [PREROUTING -t nat -m comment --comment handle ClusterIPs; NOTE: this must be before the NodePort rules -j KUBE-PORTALS-CONTAINER]
I1115 10:47:45.655351    1419 iptables.go:418] running iptables -C [OUTPUT -t nat -m addrtype --dst-type LOCAL -m comment --comment handle service NodePorts; NOTE: this must be the last rule in the chain -j KUBE-NODEPORT-HOST]
I1115 10:47:45.656914    1419 iptables.go:418] running iptables -C [PREROUTING -t nat -m addrtype --dst-type LOCAL -m comment --comment handle service NodePorts; NOTE: this must be the last rule in the chain -j KUBE-NODEPORT-CONTAINER]
I1115 10:47:45.658374    1419 iptables.go:418] running iptables -C [INPUT -t filter -m comment --comment Ensure that non-local NodePort traffic can flow -j KUBE-NODEPORT-NON-LOCAL]
I1115 10:47:45.659597    1419 iptables.go:418] running iptables -F [KUBE-PORTALS-CONTAINER -t nat]
I1115 10:47:45.660700    1419 iptables.go:418] running iptables -F [KUBE-PORTALS-HOST -t nat]
I1115 10:47:45.661832    1419 iptables.go:418] running iptables -F [KUBE-NODEPORT-HOST -t nat]
I1115 10:47:45.662987    1419 iptables.go:418] running iptables -F [KUBE-NODEPORT-CONTAINER -t nat]
I1115 10:47:45.664137    1419 iptables.go:418] running iptables -F [KUBE-NODEPORT-NON-LOCAL -t filter]
I1115 10:47:45.665438    1419 iptables.go:418] running iptables -C [OUTPUT -t nat -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I1115 10:47:45.666755    1419 iptables.go:418] running iptables -D [OUTPUT -t nat -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I1115 10:47:45.668430    1419 iptables.go:418] running iptables -C [PREROUTING -t nat -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I1115 10:47:45.669630    1419 iptables.go:418] running iptables -D [PREROUTING -t nat -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I1115 10:47:45.671291    1419 iptables.go:418] running iptables -C [POSTROUTING -t nat -m comment --comment kubernetes postrouting rules -j KUBE-POSTROUTING]
I1115 10:47:45.672554    1419 iptables.go:418] running iptables -D [POSTROUTING -t nat -m comment --comment kubernetes postrouting rules -j KUBE-POSTROUTING]
I1115 10:47:45.674104    1419 iptables.go:320] running iptables-save [-t nat]
I1115 10:47:45.676547    1419 iptables.go:380] running iptables-restore [-T nat --noflush --counters]
E1115 10:47:45.677802    1419 proxier.go:743] Failed to execute iptables-restore for nat: exit status 1 (iptables-restore: line 7 failed
)
I1115 10:47:45.677844    1419 server.go:422] Version: v1.9.0-alpha.2.779+02b3928a921b2e-dirty
I1115 10:47:45.677876    1419 oom_linux.go:65] attempting to set "/proc/self/oom_score_adj" to "-777"
I1115 10:47:45.682756    1419 server.go:448] Running in resource-only container "/kube-proxy"
I1115 10:47:45.682891    1419 healthz.go:70] No default health checks specified. Installing the ping handler.
I1115 10:47:45.682907    1419 healthz.go:74] Installing healthz checkers:"ping"
I1115 10:47:45.682985    1419 healthcheck.go:309] Starting goroutine for healthz on 0.0.0.0:10256
I1115 10:47:45.683074    1419 server.go:572] getConntrackMax: using conntrack-min
I1115 10:47:45.683089    1419 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
I1115 10:47:45.683142    1419 conntrack.go:52] Setting nf_conntrack_max to 131072
I1115 10:47:45.683219    1419 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I1115 10:47:45.683267    1419 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
I1115 10:47:45.683460    1419 bounded_frequency_runner.go:170] sync-runner Loop running
I1115 10:47:45.683509    1419 config.go:102] Starting endpoints config controller
I1115 10:47:45.683539    1419 controller_utils.go:1019] Waiting for caches to sync for endpoints config controller
I1115 10:47:45.683590    1419 config.go:202] Starting service config controller
I1115 10:47:45.683602    1419 controller_utils.go:1019] Waiting for caches to sync for service config controller
I1115 10:47:45.683937    1419 reflector.go:202] Starting reflector *core.Endpoints (15m0s) from k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85
I1115 10:47:45.683963    1419 reflector.go:240] Listing and watching *core.Endpoints from k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85
I1115 10:47:45.684071    1419 reflector.go:202] Starting reflector *core.Service (15m0s) from k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85
I1115 10:47:45.684089    1419 reflector.go:240] Listing and watching *core.Service from k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85
I1115 10:47:45.686339    1419 config.go:224] Calling handler.OnServiceAdd
I1115 10:47:45.686431    1419 config.go:224] Calling handler.OnServiceAdd
I1115 10:47:45.686463    1419 utils.go:49] Skipping service default/nginx due to clusterIP = "None"
I1115 10:47:45.686526    1419 config.go:224] Calling handler.OnServiceAdd
I1115 10:47:45.686916    1419 config.go:124] Calling handler.OnEndpointsAdd
I1115 10:47:45.686947    1419 config.go:124] Calling handler.OnEndpointsAdd
I1115 10:47:45.686971    1419 proxier.go:886] Setting endpoints for "default/kubernetes:https" to [192.168.122.7:6443]
I1115 10:47:45.687065    1419 config.go:124] Calling handler.OnEndpointsAdd
I1115 10:47:45.687078    1419 config.go:124] Calling handler.OnEndpointsAdd
I1115 10:47:45.687094    1419 config.go:124] Calling handler.OnEndpointsAdd

```

**Comment by xiangpengzhao** [comment]
/assign @thockin 
for approval since you're the only one owner of the pkg.

**Pull request merged**
