### PR TITLE
feat: turn on CSIMigrationAzureFile by default on 1.24

### PR DESCRIPTION
**Pull request by andyzhangx**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
turn on CSIMigrationAzureFile by default on 1.24

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
turn on CSIMigrationAzureFile by default on 1.24
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
turn on CSIMigrationAzureFile by default on 1.24
```

/sig cloud-provider
/area provider/azure

/test pull-kubernetes-e2e-aks-engine-azure-file-windows-dockershim
/test pull-kubernetes-e2e-capz-azure-file
/test pull-kubernetes-e2e-capz-azure-file-vmss

### CODE REVIEW

**Comment by dims** [comment]
/assign @xing-yang @msau42 

Are we ready to get this in?

**Comment by andyzhangx** [comment]
> /assign @xing-yang @msau42
> 
> Are we ready to get this in?

@msau42 this PR is ready, could you approve? thanks.

**Comment by msau42** [comment]
We've been asked to provide a KEP to track each cloud provider migration feature separately. Could you help submit a KEP similar to https://github.com/kubernetes/enhancements/pull/3109?

**Comment by Jiawei0227** [comment]
> We've been asked to provide a KEP to track each cloud provider migration feature separately. Could you help submit a KEP similar to [kubernetes/enhancements#3109](https://github.com/kubernetes/enhancements/pull/3109)?

The KEP is created here: https://github.com/kubernetes/enhancements/pull/3123

**Pull request merged**
