### PR TITLE
updating microsft/go-winio package to latest version

### PR DESCRIPTION
**Pull request by marosset**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/lgtm cancel
See https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/117306/pull-kubernetes-dependencies/1649266397995339776

**Comment by dims** [comment]
```
2023/04/21 04:24:58 Good news! Unwanted module "github.com/pkg/errors" dropped the following dependants:
2023/04/21 04:24:58    github.com/Microsoft/go-winio
2023/04/21 04:24:58 !!! Remove those from status.unwantedReferences["github.com/pkg/errors"] in /home/prow/go/src/k8s.io/kubernetes/hack/unwanted-dependencies.json to ensure they don't get reintroduced.
```

**Comment by marosset** [comment]
I was OOO last week and busy before that. I'll get this updated soon.

**Pull request merged**
