### PR TITLE
 Makefile: Add example of how to run integration tests and get code coverage report

### PR DESCRIPTION
**Pull request by tmilox**
Signed-off-by: TommyStarK <thomasmilox@gmail.com>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

If applied this commit will update the Makefile to add an example of how to run integration tests and get code coverage report.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
add a temporal  commit and make it run in the CI, I'll hold it to avoid misunderstanding, you can also add "WIP" to the PR title

/hold

**Comment by TommyStarK** [comment]
Hello @dims, @jeremyrickard 

I know guys you are super busy and this isn't a priority. Had to dig to understand how to enable code coverage report when running integration tests so I thought it could be useful to add a small example in the Makefile.

Remaining at your disposal.

Best,

**Comment by dims** [comment]
/triage accepted
/priority important-soon
/approve
/lgtm

thanks @TommyStarK

**Comment by TommyStarK** [comment]
Thanks to you @dims for taking the time :)

**Pull request merged**
