### PR TITLE
mark AzureDisk CSI migration as GA

### PR DESCRIPTION
**Pull request by andyzhangx**
#### What type of PR is this?
/kind documentation
/kind feature
/assign @msau42 
/priority important-soon
/sig cloud-provider
/area provider/azure
/triage accepted

#### What this PR does / why we need it:
set AzureDisk CSI migration on GA
per https://github.com/kubernetes/enhancements/issues/1490#issuecomment-1017877693

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
mark AzureDisk CSI migration as GA
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
mark AzureDisk CSI migration as GA
migration test links:
https://testgrid.k8s.io/provider-azure-azuredisk-csi-driver#pr-azuredisk-csi-driver-e2e-migration
https://testgrid.k8s.io/provider-azure-azuredisk-csi-driver#pr-azuredisk-csi-driver-e2e-migration-windows
```

### CODE REVIEW

**Comment by msau42** [comment]
@andyzhangx for documentation purposes, can you link to your CI page showing the migration tests here?

**Comment by andyzhangx** [comment]
> @andyzhangx for documentation purposes, can you link to your CI page showing the migration tests here?

@msau42 already added migration test links in `Additional documentation`

**Comment by msau42** [comment]
@andyzhangx do you have a testgrid running our external storage tests? There are more test cases there:
https://github.com/kubernetes/kubernetes/tree/master/test/e2e/storage/external

Or I believe @jsafrane is running those tests in his environment.

**Comment by andyzhangx** [comment]
> @andyzhangx do you have a testgrid running our external storage tests? There are more test cases there: https://github.com/kubernetes/kubernetes/tree/master/test/e2e/storage/external
> 
> Or I believe @jsafrane is running those tests in his environment.

@msau42 I don't have that since those tests are not running periodically, shall we merge this PR?

**Comment by jsafrane** [comment]
We don't run tests with Kubernetes master, we run something with OpenShift with Kubernetes 1.23.3
And we noticed that CI is getting somehow more flaky, but I can't blame CSI migration yet.

Install (with migration enabled) + run e2e tests looks OK: https://testgrid.k8s.io/redhat-openshift-ocp-release-4.11-informing#periodic-ci-openshift-release-master-ci-4.11-e2e-azure
Upgrade from version that does not have CSI migration enabled to one that has it looks worse: https://testgrid.k8s.io/redhat-openshift-ocp-release-4.11-informing#periodic-ci-openshift-release-master-ci-4.11-e2e-azure-upgrade

**Comment by msau42** [comment]
@andyzhangx one of our migration test criteria is to run the k8s storage e2e tests. I think the coverage that @jsafrane linked is sufficient for now but it would be good to get coverage in the provider-azure repo in the long term.

**Comment by jsafrane** [comment]
I found a regression! We started running tests ins "westus" region, which does not have availability zones and CSI translation does not work well there. See https://github.com/kubernetes/kubernetes/issues/108980

It might be easy to fix, if we can assume that `zone: "0"` is used only in those regions without availability zones, but I don't know how Azure numbers zones...

I don't want to block this PR before feature freeze, but it must be fixed before Kubernetes 1.24 gets GA.

**Comment by jsafrane** [comment]
/lgtm
/approve

I am going to fix https://github.com/kubernetes/kubernetes/issues/108980 before 1.24 is released.

**Pull request merged**
