### PR TITLE
fix yaml file path for test/e2e/network/example_cluster_dns.go

### PR DESCRIPTION
**Pull request by cadmuxe**
**What this PR does / why we need it**:
The test is using wrong yaml file path, and framework.TestContext.RepoRoot is not compatible with the test-infra. (RepoRoot need us to use a relative path which is even worse comparing to use GOPATH directly.)

Currently only the following testgrids are running this test. 
https://k8s-testgrid.appspot.com/sig-network-netd#Summary
 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
/assign @bowei 
for approval

**Comment by bowei** [comment]
Hey -- I don't see any other test using this pattern. What is different about this test?

**Comment by cadmuxe** [comment]
1. none of the opensource testgrid is running this test, and the test contains a wrong yaml file path.
2. we need checkout both k8s and the example repo, due to some reason test-infra can't deal the directory correctly. After discussed with @krzyzacy , we decided to use the GOPATH to get the correct path.

**Comment by bowei** [comment]
/approve

If it is not a test run against open source, then does it belong in this repo?

**Comment by krzyzacy** [comment]
the job depends on `github.com/containerd/cri` and `k8s.io/examples`, both are OSS.

alternatively we can choose to put a copy of this config under k/k, but we think that might not be a good idea.

**Comment by cadmuxe** [comment]
it's OSS, we just don't have testgrid running it.

**Pull request merged**
