### PR TITLE
Ignore a few directories created on Jenkins

### PR DESCRIPTION
**Pull request by ikehz**
Automated cherry pick of #15199

### CODE REVIEW

**Comment by ihmccreery** [comment]
I signed it!

**Comment by ihmccreery** [comment]
The CLA bot seems to be confused because I'm cherrypicking someone else's commit.  Not sure what to do there...

**Comment by ihmccreery** [comment]
Ummmm, flake?  @k8s-bot test this again please.

**Comment by ihmccreery** [comment]
Kicking shippable again.

**Comment by ixdy** [comment]
lgtm!

**Comment by zmerlynn** [comment]
@ihmccreery: You can ignore CLAs on cherry-picks: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md

**Pull request merged**
