### PR TITLE
Move performance tests to test/e2e/scalability subdirectory

### PR DESCRIPTION
**Pull request by shyamjvs**
Following the move to make e2e tests more organized and accountable to the respective SIGs.

cc @kubernetes/sig-scalability-pr-reviews @wojtek-t @gmarek @grodrigues3

### CODE REVIEW

**Comment by shyamjvs** [comment]
@gmarek I'm not very sure if empty.go should be here, but kept it because we own it and I can't find a better place for it (maybe test/e2e/common?)

**Comment by grodrigues3** [comment]
@shyamjvs thanks!

**Comment by grodrigues3** [comment]
Is there a sig that this falls under?  scalability?  Or did you choose the perf dir for some other reason?

**Comment by shyamjvs** [comment]
Rebased and reapplying lgtm based on https://github.com/kubernetes/kubernetes/pull/48730#issuecomment-314266873

**Pull request merged**
