### PR TITLE
log: get logger from context if existed

### LINKED ISSUE #119813: client-go should log with the context
### What happened?

we are using the `klog` to do logs, it can be changed by setting the `klog` default logger.

and we have `ctx Context` param in `request`

https://github.com/kubernetes/kubernetes/blob/815b18a46133723b4a08618bb801d2683605a273/staging/src/k8s.io/client-go/rest/request.go#L965

but klog can only print some fixed messages.

### What did you expect to happen?

Context can be used to deliver logger, like controller runtime: 

https://github.com/kubernetes-sigs/controller-runtime/blob/357eb831348772933a2b07b7deeae584538154d0/pkg/log/log.go#L91

if so, we can log more detail in request.

### How can we reproduce it (as minimally and precisely as possible)?

trigger requests throttling.

will produce:

```
│{"level":"info","ts":"2023-08-08T10:00:22+08:00","logger":"klog","msg":"Waited for 11.366890166s due to client-side throttling, not priority and fairness, request: GET:/apis/policy.krui│se.io/v1alpha1?timeout=10s\n"}
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
1.27
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by zwpaper**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

we are using the klog to do logs, when handling requests, we have ctx Context param,
and klog can get logger from context, we use the logger to do logging, 
can print much more useful context.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/119813

#### Special notes for your reviewer:

/wg structured-logging

#### Does this PR introduce a user-facing change?

```release-note
try to use the logger from context in client go request
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mengjiao-liu** [comment]
As far as I know, the migration of `staging/src/k8s.io/...` directories to contextual logging has not started yet, see this enhancements issue https://github.com/kubernetes/enhancements/issues/3077 for the process.

Our general operation is to batch-migrate a directory.

/sig instrumentation
/area logging

/cc @pohly

**Comment by zwpaper** [comment]
did not notice the KEP, is there any plan for migrating client-go? maybe I can help with continuing the PR, or should I wait for your schedule? @pohly

**Comment by pohly** [comment]
I did a prototype conversion before starting with contextual logging. I'll revive that at some point. But for now, let's discuss in the structured logging WG channel what we want to tackle next.

@mengjiao-liu is right, a PR which changes just a few lines in a package is not how we do this. Is it okay to close this?

**Comment by zwpaper** [comment]
yes, let me close this PR at this time.

/close

I would like to help with the migration, and I go through https://github.com/kubernetes/enhancements/issues/3077 and found it looks like the alpha is done, and beta is not yet planned? may I ask that is there any update on the beta, and where can I get started?

**Comment by pohly** [comment]
@zwpaper please ping me on the #wg-structured-logging Slack channel and we can discuss there.

**Pull request closed without merging**
