### PR TITLE
Wait forever in agnhost connect sctp when no timeout is provided.

### PR DESCRIPTION
**Pull request by fedepaol**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test

/kind feature

> /kind flake

**What this PR does / why we need it**:

We added sctp support to the connect command of the agnhost image, but when providing no timeout parameter the command fails with a TIMEOUT error. With this pr, we make the behaviour compatible with the tcp one.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs



```

### CODE REVIEW

**Comment by fedepaol** [comment]
This was highlighed in https://github.com/kubernetes/kubernetes/pull/89582#discussion_r446160376

**Comment by jayunit100** [comment]
should we be looking into this @eth0xFEED ?

**Comment by fedepaol** [comment]
> should we be looking into this @eth0xFEED ?

Ah! I almost forgot about this.
It was done for addressing this comment https://github.com/kubernetes/kubernetes/pull/89582#discussion_r446160376
@jayunit100 I'd say I can get rid of the bumping part and we can wait for this when a new agnhost is bumped (or this can even be closed)

**Pull request closed without merging**
