### PR TITLE
REPLACED BY #6983 - Fix #2741. Add support for alternate Vagrant providers: ...

### LINKED ISSUE #2741: Support VMWare in Vagrantfile
It'd be nice to support vmware in the vagrant file. 

Pull request incoming.

### PR DESCRIPTION
**Pull request by posita**
_UPDATE: This PR is replaced by #6983 and should not be merged._
## 

...VMWare Fusion, VMWare Workstation, and Parallels. (Tagging #2741.)

I tried to mirror the Vagrant philosophy and do the right thing in most cases without tweaking configuration (unless you really wanted to override something). The fall-back order is:
- VMWare Fusion
- VMWare Workstation
- Parallels (Thanks @rickard-von-essen for chef/bento#255 and [maintaining your repository](https://atlas.hashicorp.com/rickard-von-essen)!)
- VirtualBox

If any of these are installed properly (including any required Vagrant plugins), `KUBERNETES_PROVIDER=vagrant .../cluster/kube-up.sh` _should_ just work. :grin: **_CAVEAT**__: I do not have a license to VMWare Fusion. I'm pretty sure it will function, but I have only tested Parallels._

To override, you can set `DEFAULT_VAGRANT_PROVIDER` (e.g., if you have both VMWare and Parallels installed, but want to use Parallels):

``` sh
export KUBERNETES_PROVIDER=vagrant
export DEFAULT_VAGRANT_PROVIDER=parallels
.../cluster/kube-up.sh
```

You can override the box (by name):

``` sh
export KUBERNETES_PROVIDER=vagrant
export DEFAULT_VAGRANT_PROVIDER=parallels
export KUBERNETES_BOX_NAME=rickard-von-essen/opscode_fedora-20 # will fetch from atlas
.../cluster/kube-up.sh
```

And even specify a version:

``` sh
export KUBERNETES_PROVIDER=vagrant
export DEFAULT_VAGRANT_PROVIDER=parallels
export KUBERNETES_BOX_NAME=rickard-von-essen/opscode_fedora-20 # will fetch from atlas...
export KUBERNETES_BOX_VERSION=0.3.0 # ...with this version
.../cluster/kube-up.sh
```

Or specify a URL for the box itself, in which case you now must provide your own name:

``` sh
export KUBERNETES_PROVIDER=vagrant
export DEFAULT_VAGRANT_PROVIDER=parallels
export KUBERNETES_BOX_NAME=rickard-von-essen-fedora20 # will set the name to this value (with version 0)...
export KUBERNETES_BOX_URL=https://atlas.hashicorp.com/rickard-von-essen/boxes/opscode_fedora-20/versions/0.4.0/providers/parallels.box # ...and download the box from here
.../cluster/kube-up.sh
```

**WARNING**: This breaks the existing behavior of `KUBERNETES_BOX_URL`, which is now ignored unless `KUBERNETES_BOX_NAME` is also set. Previously that name was fixed for everything (default or specified by URL) as `fedora20`, irrespective of underlying OS/version. Now if a default box is used, the name is set internally (currently only `kube-fedora20`), but users who specify their own box URL are now forced to name it. To avoid clashes or confusion, it is recommended (but not enforced) that the name distinguish the box from the defaults (e.g., `posita-fedora21`, `kickass-custom-centos`, etc.).

This PR also introduces the ability to set the master memory size independently of the minions (it is included with this PR instead of a separate one because memory configuration is Vagrant provider-specific; see, e.g., [this](https://github.com/GoogleCloudPlatform/kubernetes/pull/6879/files#diff-23b6f443c01ea2efcb4f36eedfea9089R140) vs. [this](https://github.com/GoogleCloudPlatform/kubernetes/pull/6879/files#diff-23b6f443c01ea2efcb4f36eedfea9089R126)):

``` sh
export KUBERNETES_PROVIDER=vagrant
export KUBERNETES_MASTER_MEMORY=1024
export KUBERNETES_MINION_MEMORY=2048
.../cluster/kube-up.sh
```

`KUBERNETES_MEMORY` is maintained for backward compatibility. The following are equivalent to the previous example:

``` sh
export KUBERNETES_PROVIDER=vagrant
export KUBERNETES_MEMORY=1024 # sets both
export KUBERNETES_MINION_MEMORY=2048 # overrides minion
.../cluster/kube-up.sh
```

``` sh
export KUBERNETES_PROVIDER=vagrant
export KUBERNETES_MEMORY=2048 # sets both
export KUBERNETES_MASTER_MEMORY=1024 # overrides master
.../cluster/kube-up.sh
```

### CODE REVIEW

**Comment by posita** [comment]
> Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

I signed it!

**Comment by erictune** [comment]
@derekwaynecarr you touched Vagrantfile once. Are you a good reviewer, or can you suggest one?

**Comment by derekwaynecarr** [comment]
I can review tomorrow.

Thanks for the enhancement.

**Comment by posita** [comment]
I don't have any visibility into the Shippable failure. I haven't been able to reproduce any failures on my end with 9fca1cf (but I can back it out if necessary).

**Comment by derekwaynecarr** [comment]
Shippable is flaky, your PR is safe from Shippable.

I am trying to resolve a few other flaky issues with the Vagrant setup right now based on other changes that happened on the system to run more resources in pods, but once that is stabilized I will look to merge this.

**Comment by posita** [comment]
It looks like I screwed something up trying to resolve the merge conflicts with master (there shouldn't be that many changes associated with this PR). I'm closing this in favor of #6978, which is cleaner.

**Pull request closed without merging**
