### PR TITLE
Update cluster autoscaler to 1.12.0-beta.1

### PR DESCRIPTION
**Pull request by losipiuk**
```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@losipiuk until Sep 12, we don't need to file cherry picks (as release managers fast forward from master):
https://github.com/kubernetes/sig-release/blob/master/releases/release-1.12/README.md

**Comment by losipiuk** [comment]
Thanks @dims. My bad.

**Comment by dims** [comment]
@losipiuk no worries at all. it's hard to keep track of all the dates and what to do and when.

**Pull request closed without merging**
