### PR TITLE
Remove redundant RC and service tests in integration.go

### PR DESCRIPTION
**Pull request by yujuhong**
This is part of #24440

### CODE REVIEW

**Comment by mikedanese** [comment]
LGTM but I defer to @bprashanth

**Comment by bprashanth** [comment]
Thanks!

**Comment by yujuhong** [comment]
Marked p1 to fix flaky integration tests.

**Comment by yujuhong** [comment]
@k8s-bot test this please. ISSUE: #25153

**Comment by yujuhong** [comment]
k8s-bot test this issue: #25153

**Comment by yujuhong** [comment]
@k8s-bot test this issue: #25153

**Comment by yujuhong** [comment]
@k82 test this issue: #25277

**Comment by yujuhong** [comment]
@k8s-bot  test this issue: #25277

**Pull request merged**
