### PR TITLE
e2e_node: unify device tests

### PR DESCRIPTION
**Pull request by endocrimes**
#### What type of PR is this?

/kind cleanup
/kind failing-test
/area test
/sig node

#### What this PR does / why we need it:

The device_plugin_tests have not run successfully in a very long time,
initially being marked flaky and then eventually becoming stale.

The gpu_device_plugin_tests have been used to test the same behaviour,
but are incredibly high maintenance due to external changes in behaviour
from GCP/Nvidia that we have no control over.

This commit takes the existing device plugin tests, makes them look more
like the GPU tests, and removes the cases that have been unsupported for
a long time (namely restarting containers while the plugin is
unavailable).

It also removes the GPU plugin tests, as we do not get more signal by
using real devices here.

#### Special notes for your reviewer:

Sorry for the kinda messy diff - Split mode is a little easier to read - or open the new test file separately.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by endocrimes** [comment]
Note for future us: If we land this PR - we should then follow up by removing GPUs from our test-infra images.

**Comment by bobbypage** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/106466

**Comment by ehashman** [comment]
ran out of time for this one today Dani, I'll try to get it tomorrow since this is eligible for a test freeze merge

**Comment by ehashman** [comment]
/milestone v1.23

discussed during SIG Node CI subproject meeting, this is critical to get the serial lane fully green

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

Thank you for cleanup. I hope this will be easier to maintain. We will keep the issue regarding GPU tests to see if they can be made stable to provide additional coverage

**Pull request merged**
