### PR TITLE
apiserver: add pkg/util/webhook tests

### PR DESCRIPTION
**Pull request by whitlockjc**
This commit adds tests for pkg/util/webhooks.  The purpose of this was not only for better code coverage but also to alleviate the need for consumers to write their own tests for core functionality.

**Reasoning**

While working on the generic webhook admission plugin for https://github.com/kubernetes/community/pull/132, I found out that there are no tests for `staging/k8s.io/apiserver/pkg/util/webhook` and I also noticed that various places in the k8s sources were also replicating the same core tests that could/should be handled in `staging/k8s.io/apiserver/pkg/util/webhook`:

* `staging/src/k8s.io/apiserver/plugin/pkg/authorizer/webhook/webhook_test.go`
* `staging/src/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook_test.go`
* `plugin/pkg/admission/imagepolicy/admission_test.go`
* _possibly more..._

That's what this PR does, adds tests for `staging/k8s.io/apiserver/pkg/util/webhook` so that consumers no longer have to worry about testing client configuration issues, TLS issues, etc. just to use `staging/k8s.io/apiserver/pkg/util/webhook`.

cc @cjcullen

### CODE REVIEW

**Comment by whitlockjc** [comment]
If this PR is approved, there are a few changes that could be made after the fact:

1. Remove all of the superfluous code testing core webhook consumption outside of `staging/k8s.io/apiserver/pkg/util/webhook` _(a few of these are linked above)_
2. Generify the `gencerts.sh` script that was sourced from elsewhere to have one implementation.  The reason for this is the sourced `gencerts.sh` I used had two bugs in it:
    a. Without setting the `subjectAltName` in the client cert results in the following: `x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs`

**Comment by whitlockjc** [comment]
Most recent commit updates `TestWithExponentialBackoff` to have a test for a retry condition that ends in a success.  This gets the code coverage up to 100%.

**Comment by cjcullen** [comment]
@k8s-bot ok to test

**Comment by whitlockjc** [comment]
The failing tests don't seem to be related to my changes.

**Comment by cjcullen** [comment]
Looks like the verify-bazel step failed. Try running hack/update-bazel.sh.

**Comment by whitlockjc** [comment]
Thanks @cjcullen.  I couldn't tell what was up due to the _"error"_ output referencing files I hadn't touched.  I'll pull the PR change into a Linux box and re-run `make test`, as a test is failing on OS X _(not related to my changes)_ and that is keeping the `hack/verify-*` stuff from running.

**Comment by whitlockjc** [comment]
`./hack/verify-bazel.sh` passes locally so I'm not sure why it's failing on Jenkins.

**Comment by whitlockjc** [comment]
It seems Bazel is fixed but the cross build timed out in its previous attempt.  Not sure how to handle that one.

**Comment by whitlockjc** [comment]
It looks like the checks are passing and now there is just the review process.  Let me know if there is anything I can do to expedite the merge.

**Comment by whitlockjc** [comment]
I think I'm going to hold off on fixing conflicts/rebasing until right before the PR is to be merged.

**Comment by whitlockjc** [comment]
I went back on my word and went ahead and rebased.

**Comment by cjcullen** [comment]
Now that 1.7 is open for merges, I think this should be okay to get in.

**Comment by whitlockjc** [comment]
Thanks for the update @cjcullen.  I've rebased.

**Comment by whitlockjc** [comment]
The failing test is not related to these changes.

**Comment by cjcullen** [comment]
If you rebase, it will kick off another round of tests, and hopefully we'll go flake-free this time.

**Comment by whitlockjc** [comment]
Done.

**Comment by whitlockjc** [comment]
One of the two tests failing are my fault, it seems the handling of missing configuration is now different than it use to be.  I'll update the PR and cc @cjcullen when I'm done.

**Comment by whitlockjc** [comment]
@cjcullen I've updated the PR with another rebase and updated the tests for changes to how missing context is handled.  I also added one minor change to get the code coverage to 100%.

**Comment by whitlockjc** [comment]
@cjcullen I'm not sure what is wrong now.  The failed tests do not show on my system and they appear to be an old build because I removed those test messages.  As for the bazel stuff...I removed `vendor/BUILD` and ran `./hack/update-bazel.sh`.  Any ideas?

**Comment by whitlockjc** [comment]
Yup, just verified.  The _Jenkins unit/integration_ test failure is against cbfec5b which was the previous commit, not the new one.

**Comment by whitlockjc** [comment]
@cjcullen I don't know what's wrong with the failing tests.  They no longer appear to be related to the webhook tests.  My update to `vendor/BUILD` was created by `./hack/update-bazel.sh` so unless I ran that when there was a bug, I'm not sure how the bazel issue came about.

**Comment by cjcullen** [comment]
@spxtr Any idea what's going on w/ bazel?

**Comment by spxtr** [comment]
@k8s-bot bazel test this

**Comment by whitlockjc** [comment]
Let me rebase and see what's up.  Maybe rebuilding `vendor/BUILD` might produce different results.

**Comment by spxtr** [comment]
@k8s-bot verify test this

**Comment by whitlockjc** [comment]
Nope, rebase does not produce a different `vendor/BUILD` files.  Not sure what is up.

**Comment by ixdy** [comment]
that's weird. if you do a full git revert of `vendor/BUILD` does update-bazel.sh still try to change it?

**Comment by whitlockjc** [comment]
Every time I rebase, I `rm vendor/BUILD && ./hack/update-bazel.sh`.  The last rebase of `master` resulted in no changes to `vendor/BUILD`.

**Comment by ixdy** [comment]
Hm, weird: if I run update-bazel.sh in an unchanged synced workspace, it doesn't change `vendor/BUILD`, but if I delete it to let it get autogenerated, it adds the useless `load("@io_bazel_rules_go//go:def.bzl")` line. Seems like a bug in gazel. @mikedanese

**Comment by ixdy** [comment]
https://github.com/mikedanese/gazel/pull/38

**Comment by ixdy** [comment]
@whitlockjc you generally shouldn't need to delete `vendor/BUILD` after rebases now; some recent work means this file should be far less conflict-laden.

**Comment by whitlockjc** [comment]
@ixdy Thanks for the heads up.  I just got use to it so I've just kept doing it.  I'll refrain next time I rebase.

**Comment by whitlockjc** [comment]
Would it be alright if I just update the commit to no longer have that offending line?  There is a [gazel issue](https://github.com/mikedanese/gazel/pull/38) reported for the utility creating this offending line but it would at least let us move this PR forward.

**Comment by spxtr** [comment]
As long as it passes verify-bazel then that's fine.

**Comment by whitlockjc** [comment]
I removed the offending line, ran `./hack/verify-bazel.sh` and it ran without error.  While the gazel issue still persists, this PR _should_ pass Bazel verification when the tests run again.

**Comment by whitlockjc** [comment]
Can someone add the `release-note-none` label to this?  I'm not sure adding tests warrants mention in the release notes.

**Pull request merged**
