### PR TITLE
Release 0.17.1

### PR DESCRIPTION
**Pull request by zmerlynn**
- Install specific salt version on AWS (#8131)
- Revert "Introduce an 'svc' segment for DNS search" (#8568)

### CODE REVIEW

**Comment by zmerlynn** [comment]
@googlebot CLAs are good, thanks!

**Comment by zmerlynn** [comment]
cc @thockin: Holding on you. @ArtfulCoder says you want to fight for #8501

**Comment by ArtfulCoder** [comment]
I would like to recommend : #8501 " Support old and new style dns service names."

The dns.go e2e test passed in Jenkins-gce-e2e-run-6266 though the entire e2e run is not complete. (part of build # 2622)

This is a multi-release rollout for adding svc label to DNS names for services.
I think we should have #8501 in 0.17.1 since its step 1 towards that goal.

**Comment by zmerlynn** [comment]
I'm against this mainly because it hasn't had enough bake time, and we're only 5 days from 0.18.0. We'd like to ship 0.17.1 to GKE this week, and that PR increases the risk pretty dramatically due to almost no burn-in.

**Comment by zmerlynn** [comment]
cc @roberthbailey @quinton-hoole

**Comment by quinton-hoole** [comment]
Will check shortly...

**Comment by zmerlynn** [comment]
Ran 38 of 43 Specs in 1425.264 seconds
SUCCESS! -- 38 Passed | 0 Failed | 1 Pending | 4 Skipped I0521 11:05:37.416564   18737 driver.go:96] All tests pass

**Comment by dchen1107** [comment]
Will wait for the final decision on #8501

**Comment by quinton-hoole** [comment]
Something went seriously pear-shaped in the 9:53AM run e2e continuous integration run today, immediately after #8501 merged.  I don't have any reason to suspect #8501 yet, but it's probably worth either excluding it from the release, or explicitly vindicating it from the above run.

Build #6266 (May 21, 2015 9:53:11 AM)

(11 failures / +8)
Kubernetes e2e suite.Reboot should reboot each node and ensure they function upon restart
Kubernetes e2e suite.Services should serve multiport endpoints from pods
Kubernetes e2e suite.Cluster level logging using Elasticsearch should check that logs from pods on all nodes are ingested into Elasticsearch
Kubernetes e2e suite.PD should schedule a pod w/ a readonly PD on two hosts, then remove both.
Kubernetes e2e suite.Networking should function for intra-pod communication
Kubernetes e2e suite.Shell tests that services.sh passes
Kubernetes e2e suite.Services should serve a basic endpoint from pods
Kubernetes e2e suite.PD should schedule a pod w/ a RW PD, remove it, then schedule it on another host
Kubernetes e2e suite.Density [Performance suite] should allow starting 30 pods per node
Kubernetes e2e suite.Services should be able to create a functioning external load balancer
Kubernetes e2e suite.Services should correctly serve identically named services in different namespaces on different external IP addresses

**Comment by zmerlynn** [comment]
This discussion has timed out. If someone wants a 0.17.2, we can make it happen. Requesting merge.

**Comment by roberthbailey** [comment]
The build following the 9:53am run (at 11:05am) timed out and failed after 90 minutes. Right now we have no successful e2e runs with #8501 at head so I don't think it makes sense to cherry pick it into the 0.17 release branch for 0.17.1.

**Comment by roberthbailey** [comment]
@justinsb FYI -- 0.17.1 will have a couple of cherry picks for AWS cluster set up.

**Comment by dchen1107** [comment]
Agreed with @roberthbailey especially I saw dns failure consistently this morning.

**Comment by dchen1107** [comment]
I am going to merge this as is.

**Pull request merged**
