### PR TITLE
Manual cherry pick of #16494 on release-1.1

### PR DESCRIPTION
**Pull request by davidopp**
Manual cherry pick of #16494 into 1.1 release branch

This was easier than dealing with the merge conflicts.

@mikedanese @erictune @bgrant0607 @soltysh

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
@k8s-bot unit test this

**Comment by soltysh** [comment]
LGTM as well :wink:

**Comment by wojtek-t** [comment]
@davidopp - can you please rebase this PR (sorry it seems that it was already manual).

**Comment by davidopp** [comment]
It's not going to be possible to rebase this, there are some significant problems. Mike, Eric, or I will send out a new PR for the cherrypick.

**Pull request closed without merging**
