### PR TITLE
Fix typo `registry`

### PR DESCRIPTION
**Pull request by astraw99**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
fix typo `registry`, to better the code quality.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by pacoxu** [comment]
need squash ...

**Comment by astraw99** [comment]
> need squash ...

Done, PTAL thx.

**Comment by jpbetz** [comment]
While strictly speaking this is a backward incompatible change (it's an exported interface type in the apiserver staging module), it's only very lightly used, so seems safe to fix.

/lgtm

**Comment by astraw99** [comment]
@enj @xiangpengzhao PTAL thanks.

**Comment by astraw99** [comment]
@pacoxu @jpbetz Please help to check if someone can approve this PR, thanks.

**Comment by astraw99** [comment]
@pacoxu @jpbetz PTAL thanks.

**Comment by pacoxu** [comment]
> While strictly speaking **this is a backward incompatible change** (it's an exported interface type in the apiserver staging module), it's only very lightly used, so seems safe to fix.
> 
> /lgtm

/assign @smarterclayton
for confirmation and approval(which is suggested by the robot https://github.com/kubernetes/kubernetes/pull/104227#issuecomment-894777680).


BTW, it seems to only contain trivial edits. Please read our [trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits). We encourage you to take a look at confirmed issues and bugs or issues marked help-wanted.

**Review by neolit123 — COMMENTED** [review]
/ok-to-test

**Comment by astraw99** [comment]
@smarterclayton PTAL thanks.

**Comment by astraw99** [comment]
@smarterclayton PTAL thanks.

**Comment by astraw99** [comment]
/assign @liggitt
PTAL thanks.

**Pull request merged**
