### PR TITLE
Prune examples and e2es per discussion on sig-testing

### PR DESCRIPTION
**Pull request by timothysc**
**What this PR does / why we need it**:
Prune k8petstore from examples and e2es per discussion on sig-testing

**Special notes for your reviewer**:
This can live elsewhere outside the main repository.  

**Release note**:

```
NONE
```

/cc @jayunit100 @fejta @kubernetes/sig-testing-pr-reviews

### CODE REVIEW

**Comment by fejta** [comment]
/lgtm

DEATH TO FAILING TESTS!

**Comment by fejta** [comment]
For build approval:
/assign @spxtr 
For examples approval: 
/assign @eparis

**Comment by timothysc** [comment]
applying from comments.

**Comment by eparis** [comment]
@timothysc this is an inappropriate use of the approved label. We have a system of approvers for a reason. Reaching out to those people who can approve needs to be attempted.

**Comment by timothysc** [comment]
@eparis spxtr approved.

**Comment by spxtr** [comment]
I approved changes to the files I had ownership of, but someone from [examples/OWNERS](https://github.com/kubernetes/kubernetes/blob/master/examples/OWNERS) needed to `/approve` as well.

**Comment by timothysc** [comment]
ahh, my confusion there.

**Comment by spiffxp** [comment]
@eparis @timothysc so do we need to revert?  also, maybe I'm misreading, but this looks like it just pruned building of `examples/k8petstore/web-server/src`, how does this affect e2e's?

**Comment by timothysc** [comment]
@spiffxp no need to revert. 

> how does this affect e2e's 

Examples are rolled into the e2e.tests and are run.  This happened years ago now, but it's still a legacy.  There is a longstanding item to prune the examples b/c this is not where they should live.  Seeing how I removed the other k8petstore test I removed it's accompanying example as well.

**Comment by spiffxp** [comment]
@timothysc Ah, I see.  What I was missing was that you'd already remove the k8petstore e2e test in #43306

**Pull request merged**
