### PR TITLE
Munge preformatted

### PR DESCRIPTION
**Pull request by lavalamp**
The first two commits are already in #11400.

@thockin

### CODE REVIEW

**Comment by thockin** [comment]
LGTM for the sake of movement, but a couple things to touch back on.

**Comment by thockin** [comment]
We should probably munge the notPreformattedRE into simpler form: replace triple-ticks with single ticks when not a preformatted block

**Comment by thockin** [comment]
fails Travis and shippable because of gendocs

**Comment by lavalamp** [comment]
Rebased, fixed comment. Will add test later.

**Comment by lavalamp** [comment]
Cluster creation timeout :/

**Comment by lavalamp** [comment]
@k8s-bot test this please

**Comment by davidopp** [comment]
We decided to wait on this until all the other doc changes are merged. There are about 4 in testing right now.

**Comment by davidopp** [comment]
@k8s-bot test this please

**Comment by ArtfulCoder** [comment]
OKed with Daniel and Brian to merge

**Pull request merged**
