### PR TITLE
Remove deletecollection support from namespace object

### PR DESCRIPTION
**Pull request by liggitt**
Namespace storage accidentally picked up deletecollection support from embedding the generic store. If invoked, it skips the custom namespace `Delete()` storage method that enforces finalization, and skips the namespace lifecycle admission plugin that protects immortal namespaces from deletion.

Given the data integrity implications of skipping namespace finalization, I'd backport this as far as we're releasing patch releases.

```release-note
The namespace API object no longer supports the deletecollection operation.
```

### CODE REVIEW

**Comment by liggitt** [comment]
@kubernetes/api-reviewers

**Comment by ncdc** [comment]
LGTM

cc @smarterclayton @lavalamp

**Comment by smarterclayton** [comment]
Does this mean anything that supports finalizers shouldn't support bulk deletion?

**Comment by liggitt** [comment]
> Does this mean anything that supports finalizers shouldn't support bulk deletion?

The generic store handles finalization on bulk delete correctly for the things which store finalizers in objectmeta. Namespace finalization is special, since namespace finalizers live in spec, which the generic store gleefully ignores. We also try really hard not to let anyone wipe out all namespaces.

**Comment by liggitt** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by smarterclayton** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Comment by lavalamp** [comment]
Did this actually get backported?

**Comment by liggitt** [comment]
> Did this actually get backported?

picked to 1.6 in https://github.com/kubernetes/kubernetes/pull/47098
can open to 1.5 if needed

**Pull request merged**
