### PR TITLE
Revert "apiserver: add callback to get notified of object count"

### PR DESCRIPTION
**Pull request by rphillips**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Reverts kubernetes/kubernetes#102998

#### Which issue(s) this PR fixes:
Discussion:  https://github.com/kubernetes/kubernetes/pull/102998#discussion_r666450428

> the key passed in is not {group}.{resource}, it is the etcd prefix (e.g. /registry/services/specs)

> see https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L1427-L1438 ... the etcd prefix is passed into Count(), the resource is passed into the metrics function

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```

```

### CODE REVIEW

**Comment by tkashem** [comment]
we need to revert it due to https://github.com/kubernetes/kubernetes/pull/102998#discussion_r666450428. but it is unlikely that it is causing the integration test failure - see https://github.com/kubernetes/kubernetes/issues/103512#issuecomment-876606274

/lgtm

**Comment by rphillips** [comment]
3rd test on pull-kubernetes-integration (first 2 have passed on the first try)

/test pull-kubernetes-integration

**Comment by liggitt** [comment]
> 3rd test on pull-kubernetes-integration (first 2 have passed on the first try)

fwiw, re-testing keeps this out of the merge queue...

**Comment by liggitt** [comment]
weirdly, the TestMain failures that just occurred didn't hit the 600+ second timeout:

```
FAIL	k8s.io/kubernetes/test/integration/deployment	242.692s
...
FAIL	k8s.io/kubernetes/test/integration/dualstack	209.791s
```

**Comment by jiahuif** [comment]
This PR seems to case the build to fail. Example run https://prow.k8s.io/log?job=pull-kubernetes-integration&id=1413302198401503232

```
+ make generated_files
+++ [0709 01:03:33] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
Generating prerelease lifecycle code for 27 targets
+++ [0709 01:03:45] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
Generating deepcopy code for 234 targets
+++ [0709 01:03:54] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/defaulter-gen
Generating defaulter code for 93 targets
+++ [0709 01:04:06] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/conversion-gen
Generating conversion code for 128 targets
+++ [0709 01:04:28] Building go targets for linux/amd64:
    ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
Generating openapi code for KUBE
Generating openapi code for AGGREGATOR
Generating openapi code for APIEXTENSIONS
Generating openapi code for CODEGEN
Generating openapi code for SAMPLEAPISERVER
+ go install ./cmd/...
# k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset
vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go:419:55: queue.requests.Width undefined (type fifo has no field or method Width)
+ EXIT_VALUE=2
+ set +o xtrace
```

**Pull request merged**
