### PR TITLE
Automated cherry pick of #66078: fix dynamic client listing bug

### PR DESCRIPTION
**Pull request by the-redback**
Cherry pick of #66078 on release-1.11.

#66078: fix dynamic client listing bug

### CODE REVIEW

**Comment by the-redback** [comment]
cc: @deads2k  @tamalsaha

**Comment by nikhita** [comment]
/sig api-machinery
/kind bug
/ok-to-test

/assign @deads2k 

/assign @foxish 
for cherry-pick approval

**Comment by nikhita** [comment]
@deads2k can you update the release note in the parent PR body (https://github.com/kubernetes/kubernetes/pull/66078)?

It's needed to get the right labels on this PR.

**Comment by deads2k** [comment]
/lgtm

verify looks real though.

**Comment by nikhita** [comment]
@the-redback can you run `hack/update-bazel.sh`? That should fix the verify error.

**Comment by nikhita** [comment]
@the-redback can you squash the commits? thanks!

**Comment by the-redback** [comment]
Sure.

**Comment by nikhita** [comment]
/lgtm

Thanks, @the-redback!

**Comment by foxish** [comment]
This is simply updating mocks and doesn't merit a release note. Is that correct?

**Comment by nikhita** [comment]
> This is simply updating mocks and doesn't merit a release note. Is that correct?

Yes, that is correct. :+1: Thanks for updating the labels.

**Pull request merged**
