### PR TITLE
Fix kubeadm typo

### PR DESCRIPTION
**Pull request by cheyang**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by dixudx** [comment]
/ok-to-test
/area kubeadm

@cheyang Please help find other typos in `cmd/kubeadm`. Thanks for your work.

**Comment by cheyang** [comment]
@dixudx, I think there are no other misspells in kubeadm package. Thx.

**Comment by cheyang** [comment]
@dixudx Can you help to review. Thanks.

**Comment by dixudx** [comment]
@cheyang Please squash your commits .Thanks.

**Comment by cheyang** [comment]
@dixudx Done.

**Comment by cheyang** [comment]
@dixudx Looks like the failure does nothing with my changes. Please take a look. Thanks.

**Comment by cheyang** [comment]
@lavalamp Please take a look, thx.

**Comment by cheyang** [comment]
ping @lavalamp , thanks.

**Review by timothysc — APPROVED** [review]
/approve - thank you for putting your fixes into a single PR.

**Pull request merged**
