### PR TITLE
[Pet Set] petset internal replicas type should be int32

### LINKED ISSUE #32993: [Pet Set] Internal Replicas type should be int32
I find the type of `Replicas` in apps/types.go is `int` while the type of `Replicas`(https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/types.go#L88) in `v1alpha1/types.go` is `int32`(https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/v1alpha1/types.go#L86)

### PR DESCRIPTION
**Pull request by m1093782566**
**What this PR does / why we need it**:

Fixes #32993 

Sometimes an int is 4 bytes and sometimes it's 8(depend on CPU architecture), but an int32 is always 32bits. So set petset internal replicas type to int32, avoid type casting in API version converting.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33160)

### CODE REVIEW

**Comment by m1093782566** [comment]
@bprashanth

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
ok to test

**Comment by m1093782566** [comment]
@bgrant0607 CI passed. PTAL again.

Thanks!

**Comment by m1093782566** [comment]
PR #33160 kubernetes-pull-build-test-gci-kubemark-e2e-gce #19

Recent runs
PR	m1093782566: [Pet Set] petset internal replicas type should be int32
Result	FAILURE
Started	2016-09-24 08:49 CST
Elapsed	14m39s
Version	v1.5.0-alpha.0.1316+14acdc854a3c94
Builder	agent-pr-29
@wojtek-t kubemark test failed(perhaps it's not my fault), please take a look.

**Comment by m1093782566** [comment]
code rebased

**Comment by bprashanth** [comment]
@k8s-bot gke e2e test this

**Comment by bprashanth** [comment]
I think your unittest failure is in petset, so legitimate

**Comment by m1093782566** [comment]
@bgrant0607 @bprashanth @erictune 

Can any guy take a look at this PR? @bgrant0607 has `lgtm` but CI failed since flake tests. I assume flake tests gone.

**Pull request merged**
