### PR TITLE
oom-score-adj: add unit test case

### PR DESCRIPTION
**Pull request by chentao1596**
**What this PR does / why we need it**:
     According to the doc of method 'applyOOMScoreAdj', 'os.ErrNotExist ' will be returned when 'pid' not exist.
    I can not find any test case for it, so added one.

### CODE REVIEW

**Comment by chentao1596** [comment]
@brendandburns @dchen1107 @lavalamp @smarterclayton @thockin hi, /cc, please, thank you!

**Comment by thockin** [comment]
punting to vish

**Comment by spxtr** [comment]
@k8s-bot bazel test this

https://github.com/kubernetes/test-infra/pull/1446

**Comment by thockin** [comment]
Need gofmt.

```
I1227 15:27:15.124] Verifying hack/make-rules/../../hack/verify-gofmt.sh
I1227 15:27:23.869] !!! 'gofmt -s -w' needs to be run on the following files: 
I1227 15:27:23.870] ./pkg/util/oom/oom_linux_test.go

**Comment by chentao1596** [comment]
@thockin hi, i have finished it, PTAL, thank you!

**Comment by thockin** [comment]
This PR actually touches /proc - it's not really a unit test at that point...

To do this right, you want to pass an io.Writer to the function, and then test with a fake writer.  Probably more work than it is worth?

**Comment by thockin** [comment]
Thanks though, I appreciate the effort, I just don't think we should really be accesing procfs

**Pull request closed without merging**
