### PR TITLE
Automated cherry pick of #47875

### PR DESCRIPTION
**Pull request by crassirostris**
Cherry pick of #47875 on release-1.7.

#47875: Implement e2e test for Stackdriver event exporter

### CODE REVIEW

**Comment by piosz** [comment]
@crassirostris I think this should be handled by @caesarxuchao and @dchen1107

**Comment by crassirostris** [comment]
@piosz I took a look at the list of commits and realized it's not there, while some prs before and after are cherrypicked. I've made it in case this PR fell between the cracks

@caesarxuchao @dchen1107 If you haven't cherry-picked the original PR intentionally, feel free to close this one

**Comment by caesarxuchao** [comment]
i'll do a batch cherrypick to save some time from the submit-queue. Closing.

**Comment by crassirostris** [comment]
@caesarxuchao Thanks!

**Comment by caesarxuchao** [comment]
Sorry, I missed this one in last batch cherrypicking. It's not making the 1.7.0. I'll add back the cherrypick approved after 1.7 release cut (planned to be today)

**Comment by caesarxuchao** [comment]
I removed the cherrypick-approved manually to prevent the pr gets merged accidentally.

I'll add it back after 1.7.0 is out.

**Pull request merged**
