### PR TITLE
Drop unsupported iks configuration for kubemark

### LINKED ISSUE #110098: Kubemark script support for IKS not working with latest ibmcloud CLI
### What happened?

While trying to run `kubernetes/test/kubemark/start-kubemark.sh` with a valid ibmcloud account, the following error happened

```
Do you want to build the kubemark image? [y/N]> N
Do you want to use custom clusters? [y/N]> N
CHECKING CLUSTERS

FAILED
'region-set' is not a registered command. Check your list of installed plug-ins. See 'ibmcloud ks help'.
```

I also tried to run `ibmcloud ks region-set` and got the same error. Looks like a compatibility issue.

### What did you expect to happen?

ibmcloud CLI shouldn't return error

### How can we reproduce it (as minimally and precisely as possible)?

Run `kubernetes/test/kubemark/start-kubemark.sh` with a valid IBM cloud account.

### Anything else we need to know?

_No response_

### Kubernetes version

I am trying to build kubemark from source 1ea07d48
<details>

```console
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.0-alpha.4.378+1ea07d482a5ec1", GitCommit:"1ea07d482a5ec15afac5ea837585174579fc0f57", GitTreeState:"clean", BuildDate:"2022-03-29T14:28:44Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
IBM cloud IKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by dims**
Looks like there isn't anyone around to maintain the code in `test/kubemark/iks/` I don't see any test-grid entries either. So let's clean up

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #110098

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
So I'm in favor of dropping unused unmaintained things, but playing devil's advocate here ...

> Looks like there isn't anyone around to maintain the code in test/kubemark/iks/

Based on?

It doesn't look like we had IKS specific OWNERS at _any_ point. It looks like SIG scale merged + owns this and various folks have made fixups.

https://github.com/kubernetes/kubernetes/commits/master/test/kubemark/iks

> I don't see any test-grid entries either. So let's clean up

That's not really a criteria we use? Or else I'd be deleting release builds for various platforms :-)

cc @kubernetes/sig-scalability

**Comment by dims** [comment]
/retest

@BenTheElder i am happy for @kubernetes/sig-scalability-pr-reviews folks to adjudicate :) it's upto them.

**Comment by wojtek-t** [comment]
I'm personally in favor of dropping it - I think I didn't see any maintenance of it after it was added.
We don't have any CI for it, we're not depending on it for release validation or anything like that.

If at some point someone will decide to maintain it, readding back shouldn't be that hard - for now, I agree we should probably remove it.

/lgtm
/approve

/hold
To give @BenTheElder time to object.
Also @marseel - for his thoughts.

**Comment by BenTheElder** [comment]
/lgtm
/approve

like I said, just devil's advocate.
I would happily drop more unused, unmaintained bash.

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
@marseel this is on `/hold` waiting on your feedback, please take a look.

**Pull request merged**
