### PR TITLE
Release 1.2 cherry-picks

### PR DESCRIPTION
**Pull request by eparis**
This PR includes cherrypicks of the following:
#22846: Fix AWS default master sizes
#22666: Fix flake in pod IP as env var e2e
#22853: allow resource.version.group in kubectl
#21535: restore ability to run against secured etcd
#22410: Deprecating --api-version flag
#22564: Update DNS document to talk about the new Pod and Endpoints Annotations to set hostname
#22727: Guarantee we finish writing to the test log before the test exits.
#22802: Close streams with Reset instead of Close when closing streaming connections
#22865: prevent disallowed secret refs from leaking via the downward API
#22862: fix typo in kubectl run help string

### CODE REVIEW

**Comment by bgrant0607** [comment]
cc @david-mcmahon

**Comment by bgrant0607** [comment]
Thanks much. LGTM

**Comment by bgrant0607** [comment]
Will merge once tests pass.

**Comment by bgrant0607** [comment]
Hmm. Travis build timed out

**Comment by bgrant0607** [comment]
Failed build was:
https://travis-ci.org/kubernetes/kubernetes/builds/115417980

Closed and re-opened to try again.

**Comment by bgrant0607** [comment]
Travis passed 2nd time

**Comment by bgrant0607** [comment]
All green. Merging.

**Comment by lavalamp** [comment]
Thanks for making these pick PRs, @eparis. This is tons better than what we did last time.

**Pull request merged**
