### PR TITLE
publishing: Update to go@1.13.4 for kubernetes-1.16

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
For 1.16: https://github.com/kubernetes/kubernetes/blob/release-1.16/build/dependencies.yaml#L36-L37

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
I don't object to this, but I don't think the publishing bot uses the rules.yaml file in release branches

**Comment by ialidzhikov** [comment]
Used as reference #85088. If you say that there is no point, we can close it?

**Comment by liggitt** [comment]
yeah, https://github.com/kubernetes/kubernetes/pull/85088 was to master. this file in this branch is unused.

/close

**Comment by ialidzhikov** [comment]
@liggitt , this PR is also against the master 😄. Should we reopen?

**Comment by liggitt** [comment]
oops, I misread

/reopen

**Comment by zhangxiaoyu-zidif** [comment]
So the release note should contain the changes of go version. will it work for the further v1.16.5?

**Comment by liggitt** [comment]
> So the release note should contain the changes of go version. will it work for the further v1.16.5?

This doesn't change anything user-visible, just what version of go the publishing bot uses when publishing these repos

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/85019 changed the version of go used to build 1.16, and included a release note

**Pull request merged**
