### PR TITLE
remove NewCloudNodeController() second return value

### PR DESCRIPTION
**Pull request by NickrenREN**
NewCloudNodeController() will never return err,remove it

### CODE REVIEW

**Comment by lavalamp** [comment]
Is this hurting anything? I'd just as soon leave it--it's future proof. I don't feel super strongly.

**Comment by NickrenREN** [comment]
No conflicts. I do not know why it needs rebase.
Could you help re-add lgtm label. Thanks in advance @mikedanese

**Comment by NickrenREN** [comment]
@k8s-bot kops aws e2e test this

**Comment by NickrenREN** [comment]
@k8s-bot non-cri e2e test this

**Comment by NickrenREN** [comment]
Thanks @mikedanese

**Pull request merged**
