### PR TITLE
fixes: some wrong comments

### PR DESCRIPTION
**Pull request by lrx0014**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Fixed some wrong comments in registry/rbac packages.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by anarchistHH1983** [comment]
Fixes #

**Review by neolit123 — APPROVED** [review]
/ok-to-test
/priority backlog

**Pull request merged**
