### PR TITLE
Updating cAdvisor deps to v0.20.4

### PR DESCRIPTION
**Pull request by vishh**
cc @timstclair @pwittrock

### CODE REVIEW

**Comment by timstclair** [comment]
LGTM. Thanks!

FYI, this is required for https://github.com/kubernetes/kubernetes/issues/12483

**Comment by pwittrock** [comment]
Looks like cadvisor isn't compiling

**Comment by vishh** [comment]
@timstclair: This PR is missing a zfs lib dependency. I will update this PR. I hope you are not blocked on this.

**Comment by timothysc** [comment]
Please wait to include jitter patches on cadvisor.

**Comment by vishh** [comment]
@timothysc: I have included your jitter patch.

**Comment by vishh** [comment]
@timstclair: I came up with a [small wrapper](https://gist.github.com/vishh/80f7e5da847c6eb93f86) around `godeps` to help with the update process. If it is useful, I can add it to k8s repo.

**Comment by pwittrock** [comment]
@k8s-bot test this please

**Comment by timothysc** [comment]
@vishh thx.

**Comment by pwittrock** [comment]
The tests have been failing consistently.  Can you look into what the issue may be?

**Comment by timothysc** [comment]
```
Summarizing 1 Failure:

[Fail] MetricsGrabber [It] should grab all metrics from a Kubelet. 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/metrics_grabber_test.go:103
```

**Comment by vishh** [comment]
I'm trying to test this PR locally. Will update this PR once I figure out the root cause.

**Comment by vishh** [comment]
I fixed the failing test. It was failing because a new metric got introduced into the kubelet. It doesn't make sense to fail the test whenever new metrics are added. So I updated the test.

PTAL @pwittrock.

**Comment by vishh** [comment]
@pwittrock: `godep restore` seems to be broken on HEAD. Fixing that requires fixing the dependencies that bring in the missing the deps. Should we let this PR go through or block until HEAD is fixed?

**Comment by vishh** [comment]
Travis is failing for this PR due to a known issue #19672. #19794 attempts to fix that issue, but I suspect it is only a partial (but necessary) fix.
Given that there are PRs that are depending on the PR, I recommend we merge this PR and fix #19672 in parallel.

**Comment by pwittrock** [comment]
SGTM

**Comment by vishh** [comment]
@pwittrock: I fixed godeps in cadvisor and that should have made the godep scripts in kube happy. I will need a new LGTM and hopefully travis tests pass this time around.

**Comment by alex-mohr** [comment]
fyi, travis-ci is failing, which is why this isn't merging.

**Comment by vishh** [comment]
Attempting to remove unnecessary godeps is making our scripts unhappy :(
I will revert my optimization on godeps and let it suck in the unnecessary files as well.

**Comment by vishh** [comment]
Ok. I tried again with a clean workspace. Hopefully godeps worked the expected way this time around. Ufff!

**Pull request merged**
