### PR TITLE
Add finalizers to federated configmaps

### PR DESCRIPTION
**Pull request by csbell**
Initial commit for finalizers in configmap.
```release-note
Add support for finalizers in federated configmaps (deletes configmaps from underlying clusters).
```

### CODE REVIEW

**Comment by csbell** [comment]
I signed it!

**Comment by csbell** [comment]
Marcin -- I ran into issues with the fakes in testing. I get unexpected writes to the channel in my testing -- see L151 in configmap_controller_test.go. Here's how I test:

````shell
mkdir -p /tmp/asdf9
make test WHAT=k8s.io/kubernetes/federation/pkg/federation-controller/configmap KUBE_KEEP_VERBOSE_TEST_OUTPUT=y KUBE_JUNIT_REPORT_DIR=/tmp/asdf9 GOFLAGS='-count 20'
less $(ls -1t /tmp/asdf9/junit_*.stdout | head -1)
````

And the result is a mixed bag -- most of the time I have to read 1 or 2 extra messages from the channel before seeing the correct update. Note that the test works fine without my finalziers addition and the use of an extra RegisterFakeCopyOnUpdate to verify the finalizers functionality.

**Comment by quinton-hoole** [comment]
@csbell It looks like you need to sort out your CLA.

Also, could you give a little context as to why this change is required.

**Comment by csbell** [comment]
@quinton-hoole Yes. configmap is the only controller that doesn't have finalizer support. This commit adds it but I ran into issues with the fakes. The resulting test is flaky. Sometimes no issues and sometimes the channel produces updates that are unexpected. Either I'm doing something wrong in the finalizer code, not using the fakes as intended or tickling something in the fake implementation that other controllers don't use.

**Comment by quinton-hoole** [comment]
@csbell FYI, I have found many bugs in the fake implementation, so definitely don't rule that out.  @mwielgus is the expert on those fakes, perhaps ask him to help you debug.

**Comment by quinton-hoole** [comment]
@csbell OK, good to see that CLA and test issues are resolved now.  I will leave @nikhiljindal to review the finalizer code, as he's more familiar than I am with that part of the code base.

**Comment by nikhiljindal** [comment]
Thanks @csbell 
Happy to review!

**Comment by nikhiljindal** [comment]
LGTM. I expect that merging this PR will run into the same problem as https://github.com/kubernetes/kubernetes/issues/40568. So will be good to fix that before merging.

**Comment by nikhiljindal** [comment]
Daemonsets also have cascading deletion support and kubectl tests for that are not flaky, so it might be same for configmaps.
Can you try running kubectl tests in a loop locally  with these changes (you can run `make test-cmd`) and verify that the tests are not flaky. Let me know and I will add LGTM label.

Also, you need to add release notes. You can say "adding cascading deletion support for federated configmaps". Fix the release note label after adding the release notes.

**Comment by marun** [comment]
Please tag this as with sig/federation to make it easier to find.

**Comment by marun** [comment]
This code is the same as the cascading deletion support already in the other simple controllers.  Assuming the tests pass, lgtm.

**Comment by madhusudancs** [comment]
/lgtm

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[federation/pkg/federation-controller/configmap/configmap_controller.go, line 188 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/40464#-KctXxZSdR5kLSpJg_7T:-KctXxZSdR5kLSpJg_7U:bn9zqmp) ([raw file](https://github.com/kubernetes/kubernetes/blob/f4a8505d3effaa15bd295da5034429b71428e3bf/federation/pkg/federation-controller/configmap/configmap_controller.go#L188)):*
> ```Go
> }
> 
> // Returns true if the given object has the given finalizer in its ObjectMeta.
> ```

Minor nit. Not necessary to change it here since these methods aren't exported, but for some future follow up PR. It is a convention to write the function/method doc strings as

```go
// hasFinalizerFunc returns true if the given object has the ...
```

---

*[federation/pkg/federation-controller/configmap/configmap_controller.go, line 201 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/40464#-KctYOM4A8DXWBWbAKpp:-KctYOM4A8DXWBWbAKpq:benpsw9) ([raw file](https://github.com/kubernetes/kubernetes/blob/f4a8505d3effaa15bd295da5034429b71428e3bf/federation/pkg/federation-controller/configmap/configmap_controller.go#L201)):*
> ```Go
> // Removes the finalizer from the given objects ObjectMeta.
> // Assumes that the given object is a configmap.
> func (configmapcontroller *ConfigMapController) removeFinalizerFunc(obj pkgruntime.Object, finalizer string) (pkgruntime.Object, error) {
> ```

Same comment as above.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/40464#-:-Kct_beyNZ2lLRxbYFzo:b-8ks5qa)*

**Comment by csbell** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[federation/pkg/federation-controller/configmap/configmap_controller.go, line 188 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/40464#-KctXxZSdR5kLSpJg_7T:-Kctd8lXlwARNZpwGhJI:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/f4a8505d3effaa15bd295da5034429b71428e3bf/federation/pkg/federation-controller/configmap/configmap_controller.go#L188)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

Minor nit. Not necessary to change it here since these methods aren't exported, but for some future follow up PR. It is a convention to write the function/method doc strings as

```go
// hasFinalizerFunc returns true if the given object has the ...
```

</blockquote></details>

Done.

---

*[federation/pkg/federation-controller/configmap/configmap_controller.go, line 201 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/40464#-KctYOM4A8DXWBWbAKpp:-Kctd9c9ylGugec5YUjU:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/f4a8505d3effaa15bd295da5034429b71428e3bf/federation/pkg/federation-controller/configmap/configmap_controller.go#L201)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

Same comment as above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/40464)*

**Pull request merged**
