### PR TITLE
Remove duplicated code in client-go cache

### PR DESCRIPTION
**Pull request by anfernee**
**What this PR does / why we need it**: Remove duplicated code

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
Cool!

/release-note-none
/ok-to-test

**Comment by xiangpengzhao** [comment]
pull-kubernetes-federation-e2e-gce failed: #52270

We should wait until that issue is fixed.

**Comment by anfernee** [comment]
@xiangpengzhao ping?

**Comment by anfernee** [comment]
@xiangpengzhao this PR still needs some blessing.

**Comment by anfernee** [comment]
@xiangpengzhao can this change be merged?

**Comment by anfernee** [comment]
cc @lavalamp ;)

**Comment by xiangpengzhao** [comment]
>@xiangpengzhao can this change be merged?

I guess so. But I cannot approve it. We should wait for the approvers' approval. Let me try to ping @liggitt :)

**Pull request closed without merging**
