### PR TITLE
Salt configuration for Rescheduler

### PR DESCRIPTION
**Pull request by piosz**
ref #29023

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30870)

### CODE REVIEW

**Comment by piosz** [comment]
cc @davidopp @wojtek-t @kubernetes/sig-scheduling @kubernetes/sig-cluster-lifecycle

**Comment by mwielgus** [comment]
LGTM

**Comment by piosz** [comment]
@k8s-bot unit test this issue: #30947

**Pull request merged**
