### PR TITLE
Add 'checkpoint' command to kubectl

### PR DESCRIPTION
**Pull request by adrianreber**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Kubernetes 1.25 introduced the possibility to checkpoint a container.

For details please see the KEP 2008 Forensic Container Checkpointing https://github.com/kubernetes/enhancements/issues/2008

The initial implementation only provided a kubelet API endpoint to trigger a checkpoint. The main reason for not extending it to the API server and kubectl was that checkpointing is a completely new concept.

Although the result of the checkpointing, the checkpoint archive, is only accessible by root it is important to remember that it contains all memory pages and thus all possible passwords, private keys and random numbers. With the checkpoint archive being only accessible by root it does not directly make it easier to access this potentially confidential information as root would be able to retrieve that information anyway.

Now, at least three Kubernetes releases later, we have not heard any negative feedback about the checkpoint archive and its data. There were, however, many questions to be able to create a checkpoint via kubectl and not just via the kubelet API endpoint.

This commit adds 'checkpoint' support to kubectl. The 'checkpoint' command is heavily influenced by the code of the 'exec' and 'logs' command. The checkpoint command is only available behind the 'alpha' sub-command as the "Forensic Container Checkpointing" KEP is still marked as Alpha.

Example output:
```
 $ kubectl alpha checkpoint test-pod-1 -c container-2
 Node:                  127.0.0.1/127.0.0.1
 Namespace:             default
 Pod:                   test-pod-1
 Container:             container-2
 Checkpoint Archive:    /var/lib/kubelet/checkpoints/checkpoint-archive.tar
```

The tests are implemented that they handle a CRI implementation with and without a implementation of the CRI RPC call 'ContainerCheckpoint'.

#### Does this PR introduce a user-facing change?
```release-note
Added `checkpoint` command to kubectl.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/2008
```

### CODE REVIEW

**Comment by adrianreber** [comment]
@mikebrow PTAL

**Comment by mochizuki875** [comment]
Hi, I'm watching this issue and having high hopes for this feature.
I think it would be convenient to allow k8s user to checkpoint the specific container using kubectl.
Will this PR not be restarted?

**Comment by bart0sh** [comment]
@adrianreber please, rebase the PR, thanks!

**Comment by liggitt** [comment]
The API additions here, exposing this capability via kube-apiserver, and adding kubectl integrations were not discussed at all in the referenced KEP, and specifically emphasized extending the _kubelet_ API, not the kube-apiserver API.

/hold

**Comment by bart0sh** [comment]
@adrianreber please, address [this review comment](https://github.com/kubernetes/kubernetes/pull/120898#issuecomment-2237032550) to proceed further with this PR, thanks!

**Comment by adrianreber** [comment]
> @adrianreber please, address [this review comment](https://github.com/kubernetes/kubernetes/pull/120898#issuecomment-2237032550) to proceed further with this PR, thanks!

I prepared a new KEP but I am currently waiting on my containerd PR to be merged before continuing with this PR and the corresponding KEP.

**Comment by adrianreber** [comment]
https://github.com/containerd/containerd/pull/10365

**Pull request closed without merging**
