### PR TITLE
Reduced pod number for rescheduler e2e.

### LINKED ISSUE #32531: [k8s.io] Rescheduler [Serial] should ensure that critical pod is scheduled in case there is no resources available {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-serial/2248/

Failed: [k8s.io] Rescheduler [Serial] should ensure that critical pod is scheduled in case there is no resources available {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/rescheduler.go:67
Expected error:
    <*errors.errorString | 0xc8211e20b0>: {
        s: "Error while waiting for replication controller kube-dns-v19 pods to be running: Timeout while waiting for pods with labels \"k8s-app=kube-dns,version=v19\" to be running",
    }
    Error while waiting for replication controller kube-dns-v19 pods to be running: Timeout while waiting for pods with labels "k8s-app=kube-dns,version=v19" to be running
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/rescheduler.go:66
```

Previous issues for this test: #31277 #31347 #31710 #32260

### PR DESCRIPTION
**Pull request by k82cn**
fixes #32531

### CODE REVIEW

**Comment by marun** [comment]
@davidopp Not sure if this the right fix, but the targeted issue is a potential release blocker.  The test in question has flaked 19/26 times in the past week in the 1.6 serial job:

http://k8s-testgrid.appspot.com/release-1.6-blocking#gce-serial-1.6

**Comment by k82cn** [comment]
In #42686, the scheduler keep reporting `Insufficient cpu`; maybe different cases.

**Comment by piosz** [comment]
This won't fix the problem. I'll provide more details in the mentioned bug

**Pull request closed without merging**
