### PR TITLE
make k8s support cephfs fuse

### LINKED ISSUE #46636: FUSE client support for K8s CephFS
The goal of this issue is to design a CephFS driver using FUSE client for Kubernetes.</br>
Existing Ceph kernel client has the following drawbacks:</br>
•	Kernel client does not support client-enforced quotas.
•	Kernel CephFS doesn't support quota or capacity, capacity requested by PVC is not enforced or validated.
•	Kernel CephFS doesn't work with SELinux, setting SELinux label in Pod's security context will not work.

@kubernetes/sig-storage

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/kubernetes/issues/46636, https://github.com/kubernetes/kubernetes/issues/44486

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhangxiaoyu-zidif** [comment]
cc @xiangpengzhao  could you help to resolve the problem of CI. It bother me for a fewer days.

**Comment by xiangpengzhao** [comment]
```
I1109 07:41:15.519] ========================
I1109 07:41:15.519] FAILED TESTS
I1109 07:41:15.519] ========================
I1109 07:41:15.519] hack/make-rules/../../hack/verify-api-reference-docs.sh
I1109 07:41:15.519] hack/make-rules/../../hack/verify-staging-godeps.sh
I1109 07:41:15.519] hack/make-rules/../../hack/verify-swagger-spec.sh
```

please run update scripts for these parts.

**Comment by zhangxiaoyu-zidif** [comment]
when execute hack/update-api-reference-docs.sh
```shell
cp: cannot create regular file \u2018/output/definitions.html\u2019: Read-only file system
!!! [1109 16:21:24] Call tree:
!!! [1109 16:21:24]  1: hack/update-api-reference-docs.sh:50 kube::swagger::gen_api_ref_docs(...)
!!! Error in /home/cloud/gopath/src/k8s.io/kubernetes/hack/lib/swagger.sh:115
  Error in /home/cloud/gopath/src/k8s.io/kubernetes/hack/lib/swagger.sh:115. '((i<3-1))' exited with status 1
Call stack:
  1: /home/cloud/gopath/src/k8s.io/kubernetes/hack/lib/swagger.sh:115 kube::swagger::gen_api_ref_docs(...)
  2: hack/update-api-reference-docs.sh:50 main(...)
Exiting with status 1
```

**Comment by xiangpengzhao** [comment]
`cp: cannot create regular file \u2018/output/definitions.html\u2019: Read-only file system`

This is suspicious. Seems like it has sth to do with your local env but I'm not sure.

**Comment by zhangxiaoyu-zidif** [comment]
Hi，@ixdy
do you know how to  pass this CI test. Many thanks.
```shell
root@ubuntu:/home/cloud/gopath/src/k8s.io/kubernetes# hack/update-api-reference-docs.sh
...
This build could be faster, please consider using the Gradle Daemon: http://gradle.org/docs/2.5/userguide/gradle_daemon.html
cp: cannot create regular file \u2018/output/definitions.html\u2019: Read-only file system
!!! [1110 14:22:09] Call tree:
!!! [1110 14:22:09]  1: hack/update-api-reference-docs.sh:50 kube::swagger::gen_api_ref_docs(...)
!!! Error in /home/cloud/gopath/src/k8s.io/kubernetes/hack/lib/swagger.sh:115
  Error in /home/cloud/gopath/src/k8s.io/kubernetes/hack/lib/swagger.sh:115. '((i<3-1))' exited with status 1
Call stack:
  1: /home/cloud/gopath/src/k8s.io/kubernetes/hack/lib/swagger.sh:115 kube::swagger::gen_api_ref_docs(...)
  2: hack/update-api-reference-docs.sh:50 main(...)
Exiting with status 1
```

**Comment by brendandburns** [comment]
General FUSE support was already discussed here:

https://github.com/kubernetes/kubernetes/issues/7890

Do we really want to add it ad-hoc here?

@kubernetes/sig-storage-feature-requests @saad-ali

**Comment by zhangxiaoyu-zidif** [comment]
Considered what ceph member @renhwztetecs said， I think it deserve us do something for Ceph fuse...
/cc @rootfs

**Comment by rootfs** [comment]
Instead of an api change, i prefer node probe cephfs fuse binary and use it when proper. The reasons are:
- cephfs fuse installation is not guaranteed on the nodes. 
- setting it on the api requires additional validation: cephfs fuse only works with keyring file.

**Comment by zhangxiaoyu-zidif** [comment]
@rootfs  Thanks for review and idea.
Is there some example to refer, I would be grateful. Many thanks...

**Comment by rootfs** [comment]
@zhangxiaoyu-zidif remove the api changes :)

Probe cephfs-fuse and build mount options for cephfs-fuse before mounting the filesystem [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/cephfs/cephfs.go#L295)

if cephfs-fuse mount fails, fall back to kernel cephfs

**Comment by Davidrjx** [comment]
@zhangxiaoyu-zidif by fuse, is real quota ideal for you?

**Pull request closed without merging**
