### PR TITLE
SeccomProfilePath cleanup

### LINKED ISSUE #117045: Remove SeccompProfilePath
Look for "// TODO: Deprecated, remove after we switch to Seccomp field". Fix it. See https://github.com/kubernetes/kubernetes/pull/115898 as example.

/cc @saschagrunert 

/help
/good-first-issue
/sig node

add @saschagrunert as a reviewer when sending a PR.

(issue is a follow up from https://github.com/kubernetes/kubernetes/pull/117020/files#r1154025906)

### PR DESCRIPTION
**Pull request by sherifhmdy**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
removes SeccompProfilePath after being replaced by Seccomp
#### Which issue(s) this PR fixes:

Fixes #117045

#### Special notes for your reviewer:
I did not remove the getSeccompProfilePath method from helpers.go neither it's test case. Do I need to?
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

/sig node
/cc @saschagrunert

### CODE REVIEW

**Comment by sherifhmdy** [comment]
@saschagrunert @bart0sh can you guys please, give me the ok-to-test.
also I need to know if I have to delete anything related to the SeccompProfilePath within the kubelet or just the section with the comment mentioned in the original ticket.

thanks

**Comment by bart0sh** [comment]
@sherifhmdy This PR looks like a duplicate of https://github.com/kubernetes/kubernetes/pull/117050/files. Please close if this is the case.

**Comment by sherifhmdy** [comment]
> @sherifhmdy This PR looks like a duplicate of #117050. Please close if this is the case.

okay dear. done

**Pull request closed without merging**
