### PR TITLE
Fix inconsistencies in shell script conditions

### PR DESCRIPTION
**Pull request by joakimr-axis**
Conditions in the shell scripts are currently done in a
non-consistent way. This patch aims to make the codebase
more conform which makes it easier to read and maintain.

* Use -lt -gt -le -ge operators for integer comparisons
* Add double quotes for variables in string comparisons
* Use [ for POSIX compatible comparisons and [[ for bash
  specific comparisons
* Single quotes for static strings
* Use -n and -z operators instead of = "" and != ""
* Use -n operator instead of ! -z
* Use POSIX compatible = string operator instead of ==
* Replace legacy `` with $()

Signed-off-by: Joakim Roubert <joakimr@axis.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Conform way of code makes it easier to read, debug and maintain.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by oomichi** [comment]
The coding style of shell script is checked with `./hack/verify-shellcheck.sh` and some violation script files are managed with https://github.com/kubernetes/kubernetes/issues/72956
I am not sure the above list in this PR message is valid in kubernetes community, but we have a consensus to solve the above issue(https://github.com/kubernetes/kubernetes/issues/72956)

/cc @oomichi

**Comment by php-coder** [comment]
This might be hard to merge as it changes a lot of files.

I personally like the idea to not use bash-specific constructions but as far I remember, in Kubernetes there was a decision to use bash and all its features (that's why the files has `#!/bin/bash` and not `#!/bin/sh`). So, be ready that it might be rejected.

One I can say definitely -- please, don't modify scripts in vendor/ directory as it's not ours scripts and the changes there might make an update difficult.

**Comment by joakimr-axis** [comment]
> This might be hard to merge as it changes a lot of files.

Yes. On the other hand, were it only a subset someone would ask why only just these few files, there are many more affected.

> I personally like the idea to not use bash-specific constructions but as far I remember, in Kubernetes there was a decision to use bash and all its features (that's why the files has `#!/bin/bash` and not `#!/bin/sh`).

Absolutely, nothing wrong with that. But if there is a [[ ]] construction, one starts looking for bash goodies and if it turns out it is in fact just a simple POSIX test it is only harder to read. In the current codebase, there is already a mix of [[ ]] in some places and [] in some places, but not all of the [[ ]] ones contain Bash specific content. So it is inconsistent as is today.

The same goes with the current mixed usage of = and ==. Consistent would have all as == or all as =. Since Bash interprets them the same, there is little reason not to choose the = alternative since that is the POSIX one.

> One I can say definitely -- please, don't modify scripts in vendor/ directory as it's not ours scripts and the changes there might make an update difficult.

No problem, I will remove those from the patchset.

**Comment by lavalamp** [comment]
/assign @BenTheElder 

Thanks for your extensive attention to detail. To make sure your effort doesn't go to waste, I think a change like this also needs to document the standard we're using in some official place. That also helps make sure that everyone is in agreement about the changes; I personally have no idea if these are good things to do to our bash scripts or not.

**Comment by BenTheElder** [comment]
cc @kubernetes/bash-firefighters

**Comment by liggitt** [comment]
Sweeping refactors/cleanups of untested bash scripts have introduced serious bugs in the past (c.f. https://github.com/kubernetes/kubernetes/pull/84871 and https://github.com/kubernetes/kubernetes/pull/77841). Unless these are fixing specific flaws, I would not be inclined to accept these changes.

**Comment by liggitt** [comment]
@joakimr-axis I recognize this represents significant time/energy on your part, which is unfortunate. Next time, I would encourage you to reach out to the owners of a given area prior to doing a sweeping change, just to make sure the direction/intent is agreed on.

**Pull request closed without merging**
