### PR TITLE
Feature flag change when moving from alpha to beta

### PR DESCRIPTION
**Pull request by bridgetkromhout**
Looks like we need this edit, to complete the feature graduation from alpha to beta (ref https://github.com/kubernetes/enhancements/issues/1435#issuecomment-1027499645).

Signed-off-by: Bridget Kromhout <bridget@kromhout.org>

#### Does this PR introduce a user-facing change?

```release-note
Moving MixedProtocolLBService from alpha to beta
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1435-mixed-protocol-lb
```

### CODE REVIEW

**Comment by JamesLaverack** [comment]
/milestone v1.24

After [approved exception](https://groups.google.com/a/kubernetes.io/g/release-team/c/-lTj2MSfil4/m/zS1Z2Pd1BwAJ).

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
