### PR TITLE
tests: e2e-node: refactor node-problem-detector test to avoid selinux…

### PR DESCRIPTION
**Pull request by sjenning**
Fixes https://github.com/kubernetes/kubernetes/issues/43401

This test creates a file in /tmp on the host and creates a HostPath volume in the container to so that the host can inject messages into the logfile being read by the node problem detector in the container.  However, selinux prohibits the container from reading files out of /tmp on the host.

This PR modifies the test to create the log file in an EmptyDir volume instead, which will be properly labeled for container access.

@derekwaynecarr

### CODE REVIEW

**Comment by dims** [comment]
@sjenning can you please fix the conflict? (node_problem_detector.go)

**Comment by sjenning** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by derekwaynecarr** [comment]
i should be an approver on this ;-)  let me open a pr for that...

**Comment by derekwaynecarr** [comment]
ok, bot, i will be an approver after this merges
https://github.com/kubernetes/kubernetes/pull/43926

**Comment by derekwaynecarr** [comment]
ok, bot has now bended to my will ;-)  thanks for fixing this up seth

**Pull request merged**
