### PR TITLE
Cherrypick: Update defaultbackend to v1.5

### PR DESCRIPTION
**Pull request by bowei**
```release-note
Update defaultbackend to 1.5: move /metrics to a private endpoint (:10254).
```

### CODE REVIEW

**Comment by foxish** [comment]
@bowei - can you update the release note? @nicksardo, @zmerlynn PTAL for LGTM

**Comment by jonpulsifer** [comment]
👋 can we get this in? here's a stab at a release note

```release-note
Update defaultbackend to 1.5: moved `/metrics` behind tcp:10254
```

**Comment by bowei** [comment]
stgm

**Pull request merged**
