### PR TITLE
Remove DockerPrefix references in Kubelet.

### PR DESCRIPTION
**Pull request by vmarmol**
Makes this usage generic and usable by other runtimes.

/cc @dchen1107 @yifan-gu

### CODE REVIEW

**Comment by yifan-gu** [comment]
Will we replace the string type with ContainerID in the future?

**Comment by vmarmol** [comment]
@yifan-gu definitely :)

**Comment by yifan-gu** [comment]
@vmarmol Thank you! LGTM!

**Comment by yujuhong** [comment]
LGTM. Will merge on green.

**Comment by yujuhong** [comment]
The shippable builds ran into some problems. I kicked it off again.

**Comment by dchen1107** [comment]
Mergez since travis is green now

**Pull request merged**
