### PR TITLE
Cassandra Cluster Example Add Check for Null Endpoints (redo)

### PR DESCRIPTION
**Pull request by mikeln**
Fix for Issue: Cassandra Cluster Example Custom Seed Cores on First Node #5737

Also note: for this change to be effective, the following jar must be rebuilt and checked in:

```
kubernetes/examples/cassandra/image/kubernetes-cassandra.jar
```

However, this example does not have any visible java build and testing infrastructure.

### CODE REVIEW

**Comment by mikeln** [comment]
Signed SLA:
Samsung SDS America
sdsra-google-contributors@googlegroups.com
mikel.n@samsung.com ( alternate email: github@mikelnelson.net)

**Comment by mikeln** [comment]
Cassandra Cluster Example Add Check for Null Endpoints. #5752
Redo.

**Comment by mikeln** [comment]
Actually.. a question.   Should this pull request actually go against master?   let me know and I'll start it all again.

**Comment by roberthbailey** [comment]
Hi Mikel,

Thanks for looking through the Cassandra example and catching this bug. And sorry about the CLA Bot -- it doesn't always do well with corporate CLAs...

As to your other question, yes, you should make the pull request against master since we are unlikely to make another cherry pick release from the 0.13 branch before we cut a 0.14 next week. 

You should also update https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/cassandra/README.md which inlines the source from this file to keep it in sync (as it inlines this source file).

**Comment by mikeln** [comment]
Ok!  Let me close this one, and open another one against master.

**Comment by mikeln** [comment]
moved to Cassandra Cluster Example Add Check for Null Endpoints (redo2) #5808

**Pull request closed without merging**
