### PR TITLE
Automated cherry pick of #77912: fix azure disk lun error

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #77912 on release-1.14.

#77912: fix azure disk lun error

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Comment by justaugustus** [comment]
Holding as cherry pick deadline has passed, and release has not yet been built.  Branch needs to remain frozen for clear CI signal ahead of release.
/hold

**Comment by tpepper** [comment]
This cherry-pick was not merge ready ahead of the cherry-pick deadline for 1.14.10, the final planned release for the release-1.14 branch, and this was released yesterday.  If you feel this is a highly critical cherry-pick that would prevent a current user upgrading from 1.14 to a supported release, please escalate with @kubernetes/patch-release-team.

**Comment by justaugustus** [comment]
(I'm temporarily reopening this, as we need a PR on `release-1.14` to test https://github.com/kubernetes/kubernetes/issues/86182 against.)

/test all

**Comment by andyzhangx** [comment]
> (I'm temporarily reopening this, as we need a PR on `release-1.14` to test #86182 against.)
> 
> /test all

@justaugustus is it possible to make this cherry-pick into 1.14?

**Comment by justaugustus** [comment]
No. There are no plans to cut another 1.14 release. See Tim's message above: https://github.com/kubernetes/kubernetes/pull/86006#issuecomment-565083347

I've only reopened this because I need a PR to run merge-blocking tests against to test the tag fix described in https://github.com/kubernetes/kubernetes/issues/86182. It'll be closed again when that's done.

**Comment by justaugustus** [comment]
First run passed.
Sending this for another test run.
/test all

**Comment by feiskyer** [comment]
test passed, let's close it

/close

**Pull request closed without merging**
