### PR TITLE
securitycontext: add support for HostUsers

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind cleanup
#### What this PR does / why we need it:
add HostUsers as a field that can be edited through the securitycontext accessors
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dchen1107** [comment]
The code itself is very straightforward to me. But I don't have much context on what the issue this PR addressed, and any impact might be caused by this. @haircommander could you please point me to the issue / bug or design, so that I have much more understanding? 
cc/ @tallclair who has much more context than me. Thanks!

**Comment by haircommander** [comment]
for background: there is some openshift code that uses these [packages](https://github.com/openshift/apiserver-library-go/pull/131) to operate on security contexts, and I'm trying to teach them about user namespaces

thanks y'all!

**Comment by thockin** [comment]
Like Dawn, I have no real idea what this code is for.  Looking quickly, it seems like mostly simple helper funcs.  I'll approve also on @tallclair's review.  That said:

1) This pkg should have an OWNERS file that makes sense for it
2) If this is entirely around `pod` stuff - should it live in a place named more about pods?

**Pull request merged**
