### PR TITLE
Automated cherry pick of #50673

### PR DESCRIPTION
**Pull request by clement-buchart**
Cherry pick of #50673 on release-1.7.

#50673: Use cloud environment to instantiate client

### CODE REVIEW

**Comment by andyzhangx** [comment]
@brendanburns

**Comment by andyzhangx** [comment]
@feiskyer

**Comment by feiskyer** [comment]
LGTM

**Comment by djsly** [comment]
Looking forward to this fix. Need AzureSetorage in Germany. Currently running 1.7.5.
Thanks Guys!

**Comment by djsly** [comment]
this didn't make it to 1.7.8 correct? :(

**Comment by clement-buchart** [comment]
Tests are finally OK.
May this be merged ?

**Comment by andyzhangx** [comment]
@jdumars could you approve, thx

**Comment by jdumars** [comment]
@andyzhangx @wojtek-t is the patch manager for 1.7 and will need to approve this.  I am fine with it, but do not have the final say.

**Comment by wojtek-t** [comment]
@clement-buchart - I'm fine with the cherrypick, but please add a user-friendly release note to the original PR (desribe the bug this change is fixing)

**Comment by andyzhangx** [comment]
@clement-buchart pls add `support German cloud for azure disk mount feature` in `Release note`

**Pull request merged**
