### PR TITLE
Add a brief description on how we handle defaults

### PR DESCRIPTION
**Pull request by yujuhong**

### CODE REVIEW

**Comment by yujuhong** [comment]
This fixes #1502

**Comment by nikhiljindal** [comment]
Any suggestions on who is a good reviewer for this?

**Comment by davidopp** [comment]
LGTM

**Comment by bgrant0607** [comment]
We should add the text about the rationale from https://github.com/GoogleCloudPlatform/kubernetes/issues/1502#issuecomment-70217263

**Comment by yujuhong** [comment]
@bgrant0607, The comment you mentioned has more details which may not be all that relevant to this specific section. I extracted some of it and added a brief explanation. PTAL and let me know if you prefer the detailed version. Thanks!

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
