### PR TITLE
Do not run kubelet in test-cmd.sh

### LINKED ISSUE #41834: make test-cmd failing locally with permission error for dockershim
I am running `make test-cmd` locally which is failing with the following error:

```
error: failed to run Kubelet: failed to create kubelet: failed to listen on "/var/run/dockershim.sock": listen unix /var/run/dockershim.sock: bind: permission denied
```

Is this expected?
Is there a way to change that path?

cc @yujuhong @kubernetes/sig-node-bugs

### PR DESCRIPTION
**Pull request by yujuhong**
The tests are intended to test only `kubectl` commands and do not
require kubelet.

This fixes #41834

/cc @Random-Liu @dchen1107 @nikhiljindal

### CODE REVIEW

**Comment by yujuhong** [comment]
@kubernetes/sig-cli-misc

**Comment by smarterclayton** [comment]
/approved

Was the original intent

**Comment by yujuhong** [comment]
> Was the original intent

@smarterclayton wanna review it too? :) The PR only removes code.

**Comment by dchen1107** [comment]
This change looks good to me.

**Comment by yujuhong** [comment]
@k8s-bot cvm gke e2e test this
@k8s-bot gci gke e2e test this
@k8s-bot unit test this
@k8s-bot kubemark e2e test this 
@k8s-bot gci gce e2e test this
@k8s-bot kops aws e2e test this 
@k8s-bot node e2e test this

**Comment by yujuhong** [comment]
@k8s-bot gci gce e2e test this
@k8s-bot cvm gke e2e test this

**Comment by yujuhong** [comment]
@k8s-bot kubemark e2e test this
@k8s-bot gce etcd3 e2e test this

**Comment by nikhiljindal** [comment]
@k8s-bot kops aws e2e test this

**Comment by pwittrock** [comment]
@k8s-bot non-cri e2e test this

**Comment by pwittrock** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
