### PR TITLE
Implement the `cloudprovider.Instances` interface for CloudStack

### LINKED ISSUE #47303: Support the `cloudprovider.Instances` interface for CloudStack
I would be nice if the CloudStack cloudprovider would support the `cloudprovider.Instances` interface.

### PR DESCRIPTION
**Pull request by svanharmelen**
This PR adds code to support the `cloudprovider.Instances` interface, for the CloudStack provider

Closes #47303

### CODE REVIEW

**Comment by svanharmelen** [comment]
@lavalamp any change you can give the tests a push so we can get this PR going? Thx!

**Comment by svanharmelen** [comment]
@mikedanese could you give a gentle push to get things moving? Thx!

**Comment by lavalamp** [comment]
@k8s-bot ok to test

I am not going to be able to do a review of this in a reasonable amount of time.

**Comment by svanharmelen** [comment]
@lavalamp so what do you suggest? Should I just delete the PR and forget about this?

All tests now fail because the `kubernetes/pkg/types` package is now moved. This wasn't the case when I made this PR. Of course I'm fine with refactoring this, but does that make sense if you say upfront you don't have time for this PR?

**Comment by lavalamp** [comment]
Sorry, I unassigned myself in the hopes someone with more time would get assigned but the bot gave it right back to me. I'll find someone to assign this to.

**Comment by svanharmelen** [comment]
@bgrant0607 @mikedanese rebased again (second time this week), any way we could have a look at this PR so I don't have to keep rebasing this every other day :wink: Thanks!

**Comment by svanharmelen** [comment]
@lavalamp @mikedanese please first review before I go and rebase the PR again. It's only the `vendor/BUILD` file so the rebase is simple enough, but apparently this file changes a lot...

**Comment by svanharmelen** [comment]
Yeah... I know it's been 30 days. I did my best to get anyone to review this PR, but it feels like I'm talking to a wall. Don't know if it's me, if I'm doing something wrong. But I feel completely ignored and think I'll just have to give up on Kubernetes and it not so welcome community... :dissapointed:

**Comment by svanharmelen** [comment]
I know, but I think it's wise to wait with rebasing again until someone cares to review this PR...

**Comment by mikedanese** [comment]
Sorry for the delay. I missed this.

**Comment by svanharmelen** [comment]
Thanks for the update. Guess the next wait is for @thockin. Will rebase as soon as it makes sense to do so...

**Comment by spiffxp** [comment]
@k8s-bot ok to test

**Comment by svanharmelen** [comment]
@spiffxp if I rebase and fix the tests, are you then going to actually review this PR?

That would be awesome...

**Comment by mikedanese** [comment]
This needs godeps approval

**Comment by thockin** [comment]
Can you please open an issue and `closes #1234` in the FIRST comment, so approval can stick?

**Comment by svanharmelen** [comment]
@thockin done...

**Comment by thockin** [comment]
license is MPL - OK

**Comment by svanharmelen** [comment]
I would still like to get this merged... Anyone?

**Comment by dims** [comment]
@svanharmelen need to get the jobs to pass at least

**Comment by svanharmelen** [comment]
@dims they once did... But I kept rebasing and testing without anyone even looking at this PR. So now I would first like feedback on the code/approach. And if that is OK, I'll fix up everything again...

**Comment by mikedanese** [comment]
@svanharmelen this is lgtm'd and approved. We will keep applying these labels but the PR can only merge once the tests are green.

**Comment by svanharmelen** [comment]
@mikedanese check! Then I'll update this PR shortly so we can move this forward... Thx!

**Comment by svanharmelen** [comment]
I'm currently on holiday, but will rebase and fix the tests when I'm back next week...

**Comment by dims** [comment]
@svanharmelen - all this needs is a rebase and green tests if you really want this to get into 1.8...

**Comment by svanharmelen** [comment]
Working on this now, will ping when it should be done...

**Comment by svanharmelen** [comment]
I was sidetracked by work last week, so the PR wasn't updated and tested fully yet. I hope to finish it off early next week.

Will ping when I think it should be done and can be retested. Thanks!

**Comment by dims** [comment]
@svanharmelen it's getting too late for 1.8? Do we still want to get this into 1.8?

**Comment by svanharmelen** [comment]
@dims could you maybe restart the tests? I thought I could trigger them to retest, but @k8s-ci-robot told me otherwise :wink:

**Comment by spiffxp** [comment]
/retest

I'm confused why the bot is telling you this, the issue doesn't have a `needs-ok-to-test` label

**Comment by svanharmelen** [comment]
Thx! And yeah, I thought so too...

**Comment by svanharmelen** [comment]
@dims not sure if there is anything I can/should do to fix this problem:

```
I0919 04:28:10.476] FAILED TESTS
I0919 04:28:10.476] ========================
I0919 04:28:10.476] hack/make-rules/../../hack/verify-bazel.sh
I0919 04:28:10.477] Makefile:126: recipe for target 'verify' failed
W0919 04:28:10.577] make: *** [verify] Error 1
W0919 04:28:13.153] Traceback (most recent call last):
W0919 04:28:13.153]   File "/var/lib/jenkins/workspace/pull-kubernetes-verify/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 111, in <module>
W0919 04:28:13.153]     main(ARGS.branch, ARGS.script, ARGS.force)
W0919 04:28:13.154]   File "/var/lib/jenkins/workspace/pull-kubernetes-verify/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 95, in main
W0919 04:28:13.154]     'bash', '-c', 'cd kubernetes && %s' % script,
W0919 04:28:13.154]   File "/var/lib/jenkins/workspace/pull-kubernetes-verify/./test-infra/jenkins/../scenarios/kubernetes_verify.py", line 53, in check
W0919 04:28:13.154]     subprocess.check_call(cmd)
W0919 04:28:13.154]   File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
W0919 04:28:13.198]     raise CalledProcessError(retcode, cmd)
W0919 04:28:13.198] subprocess.CalledProcessError: Command '('docker', 'run', '--rm=true', '--privileged=true', '-v', '/var/run/docker.sock:/var/run/docker.sock', '-v', '/etc/localtime:/etc/localtime:ro', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-verify/go/src/k8s.io/kubernetes:/go/src/k8s.io/kubernetes', '-v', '/var/lib/jenkins/workspace/pull-kubernetes-verify/go/src/k8s.io/kubernetes/_artifacts:/workspace/artifacts', '-e', 'KUBE_FORCE_VERIFY_CHECKS=n', '-e', 'KUBE_VERIFY_GIT_BRANCH=master', '-e', 'REPO_DIR=/var/lib/jenkins/workspace/pull-kubernetes-verify/go/src/k8s.io/kubernetes', 'gcr.io/k8s-testimages/kubekins-test:1.8-v20170906-3a1c5ae5', 'bash', '-c', 'cd kubernetes && ./hack/jenkins/verify-dockerized.sh')' returned non-zero exit status 2
E0919 04:28:13.204] Command failed
I0919 04:28:13.204] process 21329 exited with code 1 after 53.9m
E0919 04:28:13.204] FAIL: pull-kubernetes-verify
I0919 04:28:13.204] Upload result and artifacts...
I0919 04:28:13.205] Gubernator results at https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/39620/pull-kubernetes-verify/52048
I0919 04:28:13.205] Call:  gsutil ls gs://kubernetes-jenkins/pr-logs/pull/39620/pull-kubernetes-verify/52048/artifacts
W0919 04:28:14.148] CommandException: One or more URLs matched no objects.
E0919 04:28:14.245] Command failed
```

Or is there another issue that I missed?

**Comment by dims** [comment]
@svanharmelen the verify-bazel.sh failed, so essentially you have to run hack/update-bazel.sh and update the PR

```
I0919 03:39:52.469] Verifying hack/make-rules/../../hack/verify-bazel.sh
I0919 03:40:14.167] --- /go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/cloudstack/BUILD	2017-09-19 03:34:14.010092407 +0000
I0919 03:40:14.168] +++ /tmp/BUILD378203572	2017-09-19 03:40:00.714130920 +0000
I0919 03:40:14.168] @@ -21,7 +21,6 @@
I0919 03:40:14.168]          "//conditions:default": [],
I0919 03:40:14.168]      }),
I0919 03:40:14.168]      deps = [
I0919 03:40:14.168] -        "//pkg/api/v1:go_default_library",
I0919 03:40:14.169]          "//pkg/cloudprovider:go_default_library",
I0919 03:40:14.169]          "//pkg/controller:go_default_library",
I0919 03:40:14.169]          "//vendor/github.com/d2g/dhcp4:go_default_library",
I0919 03:40:14.169] 
I0919 03:40:14.169] 
I0919 03:40:14.169] Run ./hack/update-bazel.sh
I0919 03:40:14.208] [0;31mFAILED[0m   hack/make-rules/../../hack/verify-bazel.sh	22s
```

**Comment by svanharmelen** [comment]
@dims done... `./hack/verify-bazel.sh` now succeeds locally.

**Comment by svanharmelen** [comment]
Could I get a /retest here? Thx!

**Comment by svanharmelen** [comment]
Don't know how to proceed here... Anything that I must fix? Of is this the test infra that is teasing me?

**Pull request merged**
