### PR TITLE
Fix errors test

### PR DESCRIPTION
**Pull request by cjcullen**
@thockin @zmerlynn

### CODE REVIEW

**Comment by zmerlynn** [comment]
@cjcullen found another issue and is going to fix it. Blech.

**Comment by cjcullen** [comment]
Fixes #10588

**Comment by zmerlynn** [comment]
Merging soon, because @cjcullen is awesome. Shippable should go green soon.

**Comment by thockin** [comment]
Why did this not trigger on my PR?

**Comment by zmerlynn** [comment]
I think you were actually red on shippable when I merged, and I was just a bad, bad person. (I had been dealing with a huge Shippable latency all morning that then manifested as a failed build, and assumed it was the same failure. But no, it was a real failure. I haven't dug your actual failure out, though.)

**Comment by thockin** [comment]
oh.  Thanks CJ

**Pull request merged**
