### PR TITLE
fix connection upgrades through kuberentes-discovery

### PR DESCRIPTION
**Pull request by deads2k**
The initial upgrade through the proxy doesn't use the passed transport to handle the communication to the remote side.  Since we need auth proxy headers, this broke the upgrade for exec.

This sets those headers once if its an upgrade request (the transport stomps them if called anyway, so it won't shadow.).

@sttts I think this is the last required piece.  Then we start wiring in for e2e.

### CODE REVIEW

**Comment by deads2k** [comment]
@k8s-bot kubemark e2e test this

failed but stil runnig

**Comment by sttts** [comment]
Looking forward to e2e tests for all this.

/lgtm

**Comment by deads2k** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by deads2k** [comment]
@k8s-bot cvm gce e2e test this

**Comment by deads2k** [comment]
@k8s-bot gci gce e2e test this

**Comment by deads2k** [comment]
> Looking forward to e2e tests for all this.

You and me both.

**Pull request merged**
