### PR TITLE
Automated cherry pick of #52710 upstream release 1.7

### PR DESCRIPTION
**Pull request by sttts**
This is necessary to consistently publish the release-1.7 branch of the staging/ repos, compare https://github.com/kubernetes/kubernetes/pull/52710.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
lgtm, but you need to fix the failing verification:

```
I1009 14:23:03.157]   -			"Rev": "38d99d87b97dc52907a6056b071b9f370af47c0c"
I1009 14:23:03.157]   +			"Rev": "38af7749543d897417ab98f91dad5477c9c32228"
I1009 14:23:03.157]    		}
I1009 14:23:03.157]    	]
I1009 14:23:03.157]    }
I1009 14:23:03.157]   /go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go is out of date. Please run hack/update-staging-client-go.sh
I1009 14:23:03.157] FAILED   hack/make-rules/../../hack/verify-staging-client-go.sh	92s
I1009 14:23:03.157] Verifying hack/make-rules/../../hack/verify-staging-godeps.sh
I1009 14:23:03.185] Checking whether godeps are restored
I1009 14:23:05.406] Updating godeps for k8s.io/apiextensions-apiserver
I1009 14:23:55.425] --- /go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/Godeps/Godeps.json	2017-10-09 13:44:40.820739200 +0000
I1009 14:23:55.426] +++ /tmp/tmp.5lkQHuey3Z/go/src/k8s.io/apiextensions-apiserver/Godeps/Godeps.json	2017-10-09 14:23:54.510029188 +0000
I1009 14:23:55.426] @@ -459,10 +459,6 @@
... skipping 244 lines ...
I1009 14:23:55.444] +			"Rev": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
I1009 14:23:55.444] +		},
I1009 14:23:55.444] +		{
I1009 14:23:55.445]  			"ImportPath": "k8s.io/client-go/util/workqueue",
I1009 14:23:55.445]  			"Rev": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
I1009 14:23:55.445]  		}
I1009 14:23:55.524] FAILED   hack/make-rules/../../hack/verify-staging-godeps.sh	52s
```

**Comment by wojtek-t** [comment]
Somithing is still wrong with verify script.

**Comment by sttts** [comment]
@wojtek-t green now

**Comment by wojtek-t** [comment]
@k8s-bot why do you claim it doesn't have approved label?

@kubernetes/test-infra-maintainers ^^

**Comment by cjwagner** [comment]
@wojtek-t As far as I can tell everything is WAI here. What claim are you referring to?
Are you reffering to this comment from k8s-merge-robot?

> This PR is not for the master branch but does not have the `cherrypick-approved` label. Adding the `do-not-merge/cherry-pick-not-approved` label.

**Comment by wojtek-t** [comment]
@cjwagner - I approved the PR and it was stuck in the state with "approved" label and submit queue still claiming it's not for ~6 hours, until I wrote https://github.com/kubernetes/kubernetes/pull/53583#issuecomment-336154395

**Comment by apelisse** [comment]
Might be a missed hook.

**Pull request merged**
