### PR TITLE
turn field validation e2e tests into conformance tests

### PR DESCRIPTION
**Pull request by apelisse**
Replaces #115340

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Converts field validation e2e tests into conformance tests

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@apelisse i can't seem to find data on these tests? https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=field%20validation

**Comment by apelisse** [comment]
Try this: https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=FieldValidation ?

**Comment by dims** [comment]
thanks @apelisse - looking at https://storage.googleapis.com/k8s-triage/index.html?test=FieldValidation

The failures are in:
- ci-cri-containerd-e2e-cos-gce-proto ( https://testgrid.k8s.io/sig-node-cos#e2e-cos-proto )
- ci-cri-containerd-e2e-cos-gce-ip-alias ( https://testgrid.k8s.io/sig-node-cos#e2e-cos-ip-alias )

Both these CI jobs are really broken and unrelated to the conformance tests in question. 

Also looking at https://storage.googleapis.com/k8s-triage/index.html?ci=0&pr=1&test=FieldValidation seems safe to let this in.

Let's please watch this closely.

/approve
/lgtm

**Pull request merged**
