### PR TITLE
*Dns* should be *DNS*

### PR DESCRIPTION
**Pull request by yu8833**
**What this PR does / why we need it**:
Change *Dns* to *DNS*
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
#36739 
**Special notes for your reviewer**:
golint
**Release note**:

```release-note
```

Signed-off-by: yupeng <yu.peng36@zte.com.cn>

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36737)

### CODE REVIEW

**Comment by madhusudancs** [comment]
@k8s-bot federation gce e2e test this

**Comment by madhusudancs** [comment]
@YuPengZTE thanks! LGTM!

**Comment by YuPengZTE** [comment]
#36739

**Comment by madhusudancs** [comment]
@YuPengZTE the unit test failure is a legitimate failure - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/36737/pull-kubernetes-unit/4920/. Please fix.

**Comment by madhusudancs** [comment]
@k8s-bot federation gce e2e test this

**Comment by YuPengZTE** [comment]
@madhusudancs PTAL.

**Comment by madhusudancs** [comment]
@k8s-bot ok to test

**Comment by madhusudancs** [comment]
@k8s-bot federation gce e2e test this

**Comment by madhusudancs** [comment]
@YuPengZTE thanks for the fixes! LGTM.

**Comment by YuPengZTE** [comment]
@madhusudancs you are welcome.

**Pull request closed without merging**
