### PR TITLE
fix eliminate shellcheck failures in /hack/e2e-internal/...

### PR DESCRIPTION
**Pull request by xichengliudui**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Ref #72956

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Comment by xichengliudui** [comment]
thanks you

**Pull request merged**
