### PR TITLE
Make validators return error strings

### PR DESCRIPTION
**Pull request by thockin**
Part of the larger validation PR, broken out for easier review and merge.  Builds on previous PRs in the series.  This is a group of smaller commits, so I don't waster precious PR numbers.

### CODE REVIEW

**Comment by thockin** [comment]
rebased

**Comment by thockin** [comment]
woohoo, actual progress thru my queue.  This one is rebased and ready.  commit-by-commit review is recommended

**Comment by krousey** [comment]
Sorry this went under my radar this long.

**Comment by thockin** [comment]
just a rebase, no changes.  Re-applied LGTM

**Pull request merged**
