### PR TITLE
Add etcd DB size monitoring in density test

### PR DESCRIPTION
**Pull request by shyamjvs**
/cc @wojtek-t 

fyi - @jpbetz @gyuho @kubernetes/sig-scalability-misc 

```release-note
NONE
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
Thanks @shyamjvs !

/lgtm

**Comment by wojtek-t** [comment]
@shyamjvs - those errors seem relevant:
```
I0823 14:21:16.644] 
I0823 14:21:16.644]   [91m[1mTest Panicked[0m
I0823 14:21:16.644]   [91mruntime error: invalid memory address or nil pointer dereference[0m
I0823 14:21:16.644]   GOROOT/src/runtime/panic.go:502
I0823 14:21:16.644] 
I0823 14:21:16.644]   [91mFull Stack Trace[0m
I0823 14:21:16.644]   	GOROOT/src/runtime/panic.go:502 +0x229
I0823 14:21:16.644]   k8s.io/kubernetes/test/e2e/framework.(*EtcdMetricsCollector).StopAndSummarize(0x0, 0x3, 0x4)
```

**Comment by shyamjvs** [comment]
@wojtek-t Fixed the bug you pointed. Let's see if it works now.

**Pull request merged**
