### PR TITLE
Staging legacy AWS cloud provider

### PR DESCRIPTION
**Pull request by mcrute**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Staging the AWS Cloud Provider as part of [KEP 20190125-removing-in-tree-providers](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20190125-removing-in-tree-providers.md). Staging repo setup here https://github.com/kubernetes/legacy-cloud-providers

Ref: #75910

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/sig cloud-provider aws
/priority important-longterm
/cc @andrewsykim @tiffanyfay

### CODE REVIEW

**Comment by andrewsykim** [comment]
@mcrute can you add ` k8s.io/csi-translation-lib` [here](https://github.com/kubernetes/kubernetes/blob/master/staging/publishing/import-restrictions.yaml#L206-L214)?

**Comment by andrewsykim** [comment]
/lgtm cancel

To silence bot

**Comment by andrewsykim** [comment]
Looks like [publishing rules](https://github.com/kubernetes/kubernetes/blob/master/staging/publishing/rules.yaml#L289-L304) still need to be udpated

**Comment by mcrute** [comment]
@andrewsykim should be ready to go now. LGTY?

**Comment by andrewsykim** [comment]
/lgtm

Thanks @mcrute

**Pull request merged**
