### PR TITLE
fix the typo

### PR DESCRIPTION
**Pull request by whitebear009**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
Fix the typo
#### Does this PR introduce a user-facing change?
NONE

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by whitebear009** [comment]
/assign @deads2k
Please take a look, thanks :)

**Comment by dims** [comment]
/close

`iff` means if-and-only-if

https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits

**Pull request closed without merging**
