### PR TITLE
Have etcd listen on all interfaces so that monit probes succeed. Closes ...

### PR DESCRIPTION
**Pull request by davidopp**
...#3852.

### CODE REVIEW

**Comment by thockin** [comment]
Is this aligned with the changes that @ArtfulCoder has in flight?

And really, shouldn't we get etcd on localhost only soon?

**Comment by davidopp** [comment]
> Is this aligned with the changes that @ArtfulCoder has in flight?

This PR becomes moot once etcd is running in a container (I assume that's what you're referring to). However, what's going on now (monit killing etcd every 2 minutes) is incredibly broken so I'd like to submit this even if it's only relevant for one day.

> And really, shouldn't we get etcd on localhost only soon?

Yes, but until all providers go through API server instead of talking to etcd directly, I think we need 0.0.0.0 instead of 127.0.0.1

**Comment by davidopp** [comment]
s/all providers/kubelet on all providers/

**Comment by thockin** [comment]
LGTM

**Pull request merged**
