### PR TITLE
Kubelet: stop using CDI annotations

### LINKED ISSUE #125210: Passing CDI devices as annotations should be removed
Kubelet should stop using annotations to pass CDI device IDs to CRI runtimes. CDIDevices CRI field should be used for this purpose.

This should be done when Kubelet that doesn't support CRI field reaches EOL and two major CRI runtimes support CRI field.

Here is a PR comment that gives more details about this: https://github.com/kubernetes/kubernetes/pull/115891/files#r1112169121

- Kubelet started using CDIDevices CRI field in [v1.28.0](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.28.md#api-change-2). Previous version 1.27 will reach EOL [2024-06-28](https://kubernetes.io/releases/patch-releases/#1-27).

- CRI-O started using it in [v1.28.0](https://github.com/cri-o/cri-o/releases/tag/v1.28.0). Previous version 1.27 will reach EOL [2024-06-28](https://kubernetes.io/releases/patch-releases/#1-27) together with Kubernetes 1.27.

- Containerd started using it in [1.7.2](https://github.com/containerd/containerd/releases/tag/v1.7.2). Version 1.7 will reach EOL in a 6 months after Containerd 2.0 release https://github.com/containerd/containerd/blob/main/RELEASES.md. Previous version 1.6 doesn't support CDI injections and should not be considered.

So, safer option would be to wait until Containerd 1.7 reaches EOL. However it's relatively safe to do it earlier when 1.7.0 and 1.7.1 have little chances to be in real use.

Containerd v1.7.0 and v1.7.1 is not used by the Linux distributions from [this long list](https://pkgs.org/search/?q=containerd), so it's safe to remove annotations support from the Kubelet in 1.31 in my opinion.

### PR DESCRIPTION
**Pull request by bart0sh**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Removing setting CDI annotations by the Device Manager as CRI field CDIDevices is used for the same purpose.

#### Which issue(s) this PR fixes:

Fixes #125210

#### Special notes for your reviewer:

For further details see https://github.com/kubernetes/kubernetes/issues/125210

#### Does this PR introduce a user-facing change?
```release-note
Device manager: stop using annotations to pass CDI device info to runtimes. Containerd versions older than v1.7.2 don't support passing CDI info through CRI and need to be upgraded.
```

### CODE REVIEW

**Comment by ffromani** [comment]
/triage accepted
/priority important-longerm

@bart0sh this change can land in early 1.32, it seems to me that would be ok considering the dependencies listed in the issue, right?

**Comment by bart0sh** [comment]
@ffromani 
> this change can land in early 1.32, it seems to me that would be ok considering the dependencies listed in the issue, right?

correct

**Comment by kannon92** [comment]
LGTM.

Is there any tests or e2e tests we need to clean up as part of this feature?

**Comment by bart0sh** [comment]
> In that issue,
> 
> > Containerd v1.7.0 and v1.7.1 is not used by the Linux distributions from [this long list](https://pkgs.org/search/?q=containerd), so it's safe to remove annotations support from the Kubelet in 1.31 in my opinion.
> 
> Could you ask for feedback from containerd on this?

@mikebrow Do you think it's safe to assume that Containerd 1.7.0 and 1.71. is not used or it makes sense to wait until 1.7 EOL?

**Comment by bart0sh** [comment]
@kannon92 
> Is there any tests or e2e tests we need to clean up as part of this feature?

I've already cleaned up unit tests. e2e_node tests seem to only use CRI field: https://github.com/kubernetes/kubernetes/blob/master/test/images/sample-device-plugin/sampledeviceplugin.go#L80

**Review by elezar — APPROVED** [review]
Thanks @bart0sh. This looks good and removes the need to duplicate the annotation logic that exists in the CDI packages.

One note is that users that are still on Containerd v1.7.0 or v1.7.1 may run into problems when using a Device Plugin that makes use of the CDIDevices CRI field. I think the risk of this low enough.

I don't know if we want to call this out in the release notes?

**Comment by klueska** [comment]
/approve
/lgtm

/hold
pending update to the release notes on this being a breaking change for users of containerd 1.7.0 and 1..7.1.

**Comment by bart0sh** [comment]
@klueska @elezar I've updated release notes, PTAL again, thanks!

**Review by elezar — APPROVED** [review]
lgtm

**Pull request merged**
