### PR TITLE
update standard protocols to match KEP-3726

### PR DESCRIPTION
**Pull request by dprotaso**
#### What type of PR is this?

/kind documentation

Update the documentation based on the latest KEP changes https://github.com/kubernetes/enhancements/pull/4297

#### What this PR does / why we need it:

Updates the godoc of standard application protocols. It specifies h2c implies h2 prior knowledge over clear text and adds the websocket protocols.

#### Which issue(s) this PR fixes:

N/A

#### Special notes for your reviewer:

Thanks for the review.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dprotaso** [comment]
So I'm running `update` scripts locally but it's not producing any further diffs. This is odd - I would expect the files changed to be similar to this earlier PR - https://github.com/kubernetes/kubernetes/pull/119243

**Comment by dprotaso** [comment]
so verify passed - did something change recently in k/k that it doesn't require me to update codegen and swagger spec? 
This was necessary before https://github.com/kubernetes/kubernetes/pull/119243 ?

**Comment by dprotaso** [comment]
Asking in slack to see if something is broken - https://kubernetes.slack.com/archives/C09R23FHP/p1697501250456829

**Comment by dprotaso** [comment]
OK - I got my answer - I was updating the internal types only - for some reason I thought some staging types were autogenerated

**Comment by dprotaso** [comment]
/assign @LiorLieberman @robscott 

This is ready for review and reflects the KEP changes

**Comment by LiorLieberman** [comment]
Thanks! 
/lgtm

**Comment by robscott** [comment]
Thanks @dprotaso!

/lgtm
/assign @thockin

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
