### PR TITLE
Add a more detailed error message for potential auth fails in docker pull.

### LINKED ISSUE #4006: Better error message when missing Docker Registry credentials
I launched a pod forgetting that I had not uploaded my `.dockercfg` into the node's `/` folder. Of course the image pull failed but the error message was not helpful:

```
Sat, 31 Jan 2015 03:52:18 +0000	{kubelet k8s-littlecloud-3-node-3.c.littlebits-electronics.internal}	spec.containers{cloud-api-stream}	failed		Failed to pull image "quay.io/littlebits/cloud-server-api-stream:0.2.13"
```

e.g. It should finish off the message with "because credentials for quay.io are not available to Kubernetes. This may be because ...blah blah"

### PR DESCRIPTION
**Pull request by brendandburns**
Closes #4006

@jlowdermilk @deads2k @smarterclayton

### CODE REVIEW

**Comment by smarterclayton** [comment]
Test case to verify the string

**Comment by jlowdermilk** [comment]
LGTM, but +1 to test case.

**Comment by brendandburns** [comment]
Added a test.

**Comment by smarterclayton** [comment]
LGTM

**Pull request merged**
