### PR TITLE
etcd: Build 3.5.3-0 image

### PR DESCRIPTION
**Pull request by serathius**
/sig release
/kind bug

```release-note
NONE
```
/assign @dims

### CODE REVIEW

**Comment by dims** [comment]
cc @kubernetes/release-team 

we'll need to treat this as an item for release. we can't be using `3.6.0-alpha.0` as it was before and we switch to 3.5.3 which was released this morning. (this is the one where several data corruption issues were fixed)

https://github.com/etcd-io/etcd/releases/tag/v3.5.3
https://github.com/etcd-io/etcd/compare/v3.5.2...v3.5.3

**Comment by liggitt** [comment]
this is for tests only, right?

does kubeadm have a corresponding change to make to pick up 3.5.3? my read of https://github.com/kubernetes/kubernetes/blob/75e49ec824b183288e1dbaccfd7dbe77d89db381/cmd/kubeadm/app/constants/constants.go#L491-L503 is that 1.22+ will use the known-bad 3.5.1 version by default

**Comment by dims** [comment]
@neolit123 can you please add a PR to bump kubeadm to 3.5.3? (see note from @liggitt above)

**Comment by liggitt** [comment]
I agree we should not be using 3.6.0-alpha.0 or 3.5.2 in this image. I don't have a clear understanding of how important it is to get this PR in for 1.24 if the cluster/images/etcd image is only being used in kube CI

**Comment by serathius** [comment]
Sure, feel free to make fixes to PR. I'm leaving for holidays tomorrow so I won't be available for the rest of the week.

**Comment by liggitt** [comment]
> found some more things that need fixing...

not sure if you were referring to my comment about kubeadm, but I wasn't expecting that change in this PR... just noting the other in-repo use I knew of

**Comment by neolit123** [comment]
> does kubeadm have a corresponding change to make to pick up 3.5.3? my read of

> @neolit123 can you please add a PR to bump kubeadm to 3.5.3? (see note from @liggitt above)

yep, i can do that later today.

**Comment by justaugustus** [comment]
> not sure if you were referring to my comment about kubeadm, but I wasn't expecting that change in this PR... just noting the other in-repo use I knew of

@liggitt -- Nope, I noticed that we were not using the:

1. latest versions of the debian-base images --> https://github.com/kubernetes/kubernetes/pull/109470/commits/cddd83c99765a13835d7c6f01844f5b27a18a499
2. golang version that was used in the etcd v3.5.3 release --> https://github.com/kubernetes/kubernetes/pull/109470/commits/b0f3f015d7748951a4ec60682ed27efc72984f2e (ref: https://github.com/etcd-io/etcd/blob/0452feec719fa8ad88ae343e66e9bb222965d75d/Makefile#L58)

/hold cancel
/lgtm

**Comment by justaugustus** [comment]
> > does kubeadm have a corresponding change to make to pick up 3.5.3? my read of
> 
> > @neolit123 can you please add a PR to bump kubeadm to 3.5.3? (see note from @liggitt above)
> 
> yep, i can do that later today.

@dims @neolit123 -- Here's part of it: https://github.com/kubernetes/kubernetes/pull/109471 (not sure of the other kubeadm things that may need to happen elsewhere...)

**Comment by justaugustus** [comment]
cc: @kubernetes/release-team-leads

**Comment by neolit123** [comment]
> @dims @neolit123 -- Here's part of it: https://github.com/kubernetes/kubernetes/pull/109471 (not sure of the other kubeadm things that may need to happen elsewhere...)

thanks for sending the PR!

**Comment by justaugustus** [comment]
> thanks for sending the PR!

No worries! Just give me a heads-up if there's anything missing from it.
I did my best guesses on what needed to be bumped.

**Pull request merged**
