### PR TITLE
clean todo

### PR DESCRIPTION
**Pull request by mouuii**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Since we have SortingPrinter, we can  sort before delegating to another printer, there's no need to have "use sorting" in humanPrinter.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
1. The robot doesn't respond to edits, only new comments
2. Please let the auto-assigned reviewers review first. I'm not an owner for these files.
3. eddiezane should've been assigned for approval *after* the PR is reviewed

From the bot comment:
> **Once this PR has been reviewed and has the lgtm label**, please assign eddiezane for approval. For more information see [the Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

**Comment by mouuii** [comment]
@mpuckett159 PTLA

**Pull request closed without merging**
