### PR TITLE
Update in-tree azureDisk and azureFile tests

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup
/sig storage
/sig cloud-provider

#### What this PR does / why we need it:

Don't implement interfaces that trigger tests with in-line and pre-provisioned Azure volumes.

Similar to vSphere #123036

#### Which issue(s) this PR fixes:

Related-to #122857

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by nilo19** [comment]
@andyzhangx

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by carlory** [comment]
pull-kubernetes-node-e2e-containerd

**Review by justankiit — APPROVED** [review]
Looks fixed!

**Pull request merged**
