### PR TITLE
secret.go: add initial symbol and format err

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
secret.go: add initial symbol and format err
line 198： add initialization symbol 
other lines: format err.

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by zhangxiaoyu-zidif** [comment]
@cblecker  @k8s-ci-robot The test error has no relation with my PR.

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot kops aws e2e test this

**Comment by monopole** [comment]
/lgtm

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/44893#-:-Ki_tpZEKIfYgTmS0Vd7:b-8ks5qa)*

**Pull request merged**
