### PR TITLE
typo fix: fromat->format

### PR DESCRIPTION
**Pull request by scf0920**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by idealhack — APPROVED** [review]
/lgtm

**Comment by nikhita** [comment]
/assign @saad-ali @DirectXMan12 
for approval

**Comment by nikhita** [comment]
@scf0920 I won't bother retesting for sometime:) kops is currently broken on master.

**Comment by scf0920** [comment]
@nikhita Thanks :) . I don't know why no one approval this PR, and now the test failure. so sad...

**Comment by nikhita** [comment]
> @nikhita Thanks :) . I don't know why no one approval this PR, and now the test failure. so sad...

@scf0920 :( one of the files lists only @saad-ali as an approver. Most approvers are usually pretty busy/on PTO sometimes, etc. I'm sorry that it's taking sometime to get approval on this. 

I've reached out to @saad-ali on slack and asked him to approve when he gets a chance. :+1: 

The kops test is flaky, not failing consistently: https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kops-aws, so

/retest

**Comment by saad-ali** [comment]
/lgtm
/approve

Thanks for the fix!

**Pull request merged**
