### PR TITLE
Move some pkg/kubectl into polymorphichelpers

### PR DESCRIPTION
**Pull request by seans3**
* Moves `pkg/kubectl` code into `pkg/kubectl/polymorphichelpers`.
* This cleanup helps with the kubectl move to staging by removing dependencies.

/kind cleanup
/sig cli
/area kubectl
/priority important-soon

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@seanknox looks like we have to do the rebase dance since we have a bunch of things in flight :)

**Comment by seans3** [comment]
/assign @BenTheElder 

for `hack/.golint_failures`

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Comment by lizhenlin1** [comment]
666

**Pull request merged**
