### PR TITLE
use make slice to store objects to improve efficiency

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

**What this PR does / why we need it**:

we we know the slice length in advance, I think we had better use make to create the specified length of slice. This will improve some kind of performance. Since if we create a slice with []type{}, we did not know how much space runtime should reserve, since slice implementation should be continuous in memory. While when we make a slice with specified length, runtime would reserve a continuous memory space which will not result in slice movement in case of current space is not enough.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
NONE

**Special notes for your reviewer**:
NONE

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dashpole** [comment]
@k8s-bot ok to test

**Comment by allencloud** [comment]
Ping @vishh 
Please help me to take a look at this. Thanks a lot. And tell me if I could provide more details. 😸

**Comment by allencloud** [comment]
Ping @vishh
Please help me to take a look at this. Thanks a lot. And tell me if I could provide more details. 😸

**Comment by wojtek-t** [comment]
@k8s-bot pull-kubernetes-kubemark-e2e-gce test this

**Pull request merged**
