### PR TITLE
update label filter prompt

### PR DESCRIPTION
**Pull request by xilabao**
I have to look up the meaning of selector in docs/user-guide/labels.md.  I think  we could print more info when run "--help".

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37066)

### CODE REVIEW

**Comment by AdoHe** [comment]
@kubernetes/kubectl @kubernetes/sig-cli I want to hear more opinions about this, generally I am not opposite to this.

**Comment by AdoHe** [comment]
@xilabao one note: label query not only support equality-based requirement, but also support set-based requirement.

**Comment by fabianofranz** [comment]
Any chance we can make this a little shorter? Something like 

"Selector (label query) to filter on, supports '=', '==', and '!='."

Also single quotes instead of backticks.

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by soltysh** [comment]
LGTM

**Comment by xilabao** [comment]
@AdoHe  fix conflict, PTAL

**Comment by AdoHe** [comment]
@xilabao thanks.

**Comment by AdoHe** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
