### PR TITLE
[go] Bump images, dependencies and versions to go 1.21.4

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

- Bump images, dependencies and versions to go 1.21.4

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/release/issues/3347

#### Does this PR introduce a user-facing change?
```release-note
Kubernetes is now built with Go 1.21.4
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs

```

/assign @saschagrunert @xmudrii  @jeremyrickard @puerco @liggitt @dims 
cc @kubernetes/release-engineering

### CODE REVIEW

**Comment by liggitt** [comment]
publishing bot is unhappy with the patch version in the go version?

**Comment by cpanato** [comment]
running locally seems to pass

```
$ go run -mod=mod ./cmd/validate-rules ../kubernetes/staging/publishing/rules.yaml
I1108 09:02:26.582984   56091 rules.go:108] loading rules file : ../kubernetes/staging/publishing/rules.yaml
I1108 09:02:26.586463   56091 rules.go:144] validating repository order
I1108 09:02:26.586491   56091 rules.go:166] validating go versions
I1108 09:02:26.586535   56091 validate.go:37] validating directories exist in the kubernetes branch
I1108 09:02:27.223199   56091 main.go:50] validation successful
```

**Comment by cpanato** [comment]
the failing job is using go1.20: https://github.com/kubernetes/test-infra/blob/a839e8e6669c1ee75fbebf3f42e828990db45965/config/jobs/kubernetes/publishing-bot/publishing-bot-presubmits.yaml#L158, maybe we need to bump that?

seems the error is not in the publishing-bot, but i might be wrong

**Comment by cpanato** [comment]
PTAL @liggitt

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by SuperQ** [comment]
Just a note here. Because Go 1.21 now enforces the `go` directive in `go.mod`, downstream projects now get auto-upgraded.

It's typical for downstream projects to prefer to support at least the same Go compiler versions as Go itself supports. So this (and the previous commit this fixes) forces downstream projects to use Go 1.21, even tho Go 1.20 is still supported and 1.22 is not released yet.

It would be nice if Kubernetes followed the usual practice of building and testing on the same supported Go compiler versions.

**Comment by liggitt** [comment]
@SuperQ thanks for the feedback, but keeping the latest version of Kubernetes opting into the latest version of go is important to ensure we exercise any behavior changes in go early and ensure those don't cause regressions.

Release alignment for this particular Kubernetes release meant there is only a ~2 month difference between Kubernetes 1.29 being released (December 2023) and go1.20 going out of support (expected February 2024). If there's a critical reason a downstream *cannot* build with go1.21 during those two months, the Kubernetes 1.28 libraries, still on go1.20, can be used (we would also definitely want to know about the reason if it was a regression, etc).

**Comment by SuperQ** [comment]
You can always build with a newer Go compiler, but keep the `go` directive in `go.mod` pinned to an older release. This is about minimum compiler compatibility. You only really ever need to bump the `go.mod` if you intend to use Go compiler or standard library features that are not in older versions.

For example, the new for loop functionality would require `go 1.22` in `go.mod`, but this would break the ability to compile with 1.21.

The main issue here is that prior to Go 1.21, this feature of `go.mod` was a hint, now it's enforced.

For now, we've had to revert k8s.io to 1.28 libraries in Prometheus to maintain our compiler support standards with our community.

**Comment by liggitt** [comment]
go.mod version opts into go runtime behavior changes as well, not just language changes, which we consider important to do in the latest k8s version.

If you want to delay k8s library updates from Dec 2023 to Feb 2024 until go1.20 drops out of support, that seems like an ok tradeoff.

**Pull request merged**
