### PR TITLE
Update godeps after addition of LICENSE files

### PR DESCRIPTION
**Pull request by eparis**
https://github.com/tools/godep/commit/dcbe29c7a18887497b4857e64665d25be43f7c7e

Caused godeps to start including the LICENSE file for all vendored deps.
We need to include it now to keep the deps reproducible.

### CODE REVIEW

**Comment by eparis** [comment]
Fixes #16791

**Comment by eparis** [comment]
@lavalamp @thockin

**Comment by wojtek-t** [comment]
Awesome - thanks. LGTM

**Comment by wojtek-t** [comment]
Applying LGTM label since this is blocking other things.

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-oncall can you please take care of merging it - this is fixing head and blocking other PRs

**Comment by pwittrock** [comment]
Looks like the Jenkins uinit/integration and Shippable tests are failing.  I will merge once this is resolved.

**Comment by pwittrock** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@pwittrock - thanks!

**Pull request merged**
