### PR TITLE
fix kubelet typo

### PR DESCRIPTION
**Pull request by timchenxiaoyu**
fix kubelet typo

### CODE REVIEW

**Comment by dashpole** [comment]
@k8s-bot ok to test

**Comment by timchenxiaoyu** [comment]
@k8s-bot gci gce e2e test this

**Comment by timchenxiaoyu** [comment]
@k8s-bot non-cri node e2e test this

**Comment by timchenxiaoyu** [comment]
@timstclair please check!  give me approve,ths

**Comment by timstclair** [comment]
As discussed elsewhere, please merge all typo fixes into a single PR: https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Atimchenxiaoyu+sort%3Acomments-desc+is%3Aopen

**Comment by timchenxiaoyu** [comment]
@k8s-bot cvm gce e2e test this
@k8s-bot kops aws e2e test this

**Comment by timchenxiaoyu** [comment]
merge all typo

**Pull request closed without merging**
