### PR TITLE
[EXPERIMENTAL] Support graceful destory for CR storage

### LINKED ISSUE #68508: Should support graceful deletion for CR storage
/kind bug
/sig api-machinery

another bug uncovered by #68405. in the extension server, we are removing old CR's storage when some significant changes (spec, some status) land in the corresponding CRD with the help of CRD informer. but when we're destroying the old CRD's storage, there are might be some remaining requests invoking etcd client from the old storage. so a racing happens when the CRD's informer trying to delete/close the old storage together with the old etcd client and the running handler trying to call REST interface via that client. as a result, the handler will fail with a `context canceled` or `grpc: the client connection is closing` which is the reason #68405 is flaky. 

in a word, __updating CRD will fail all processing CR requests__. 

@sttts proposes to make use of the [apimachinery WaitGroup](https://github.com/kubernetes/kubernetes/pull/54849) for the storage and we only delete a storage when the all the running handler's finished. but we might left some problem with that:

- do we count the `WaitGroup` only in the handler ignoring other etcd client references like compactor?  
- ~how will this impact server's performance?~
- does it have to be a `WaitGroup`?
- what about some long running handlers? `watch` has a timeout itself tho, what about infinite handlers like `proxyport`?

otoh, we can add a cooldown period (minute-ish?) for older cr storage to postpone the actual deletion for that storage. surely, it's not stable but a cooldown will at least keep most of short-running handler from failing.

@deads2k @stttts

### PR DESCRIPTION
**Pull request by yue9944882**
Fixes: #68508

/sig api-machinery
/area custom-resources
/kind feature

⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️
EXPERIMENT
⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
alternative in https://github.com/kubernetes/kubernetes/pull/77816/files#diff-2f720a7e61a4ddfcfe9a9e353be8784b

rather than putting the waitgroup in storage, putting it at the crdInfo level maps more naturally to the place in-tree resources do graceful deletion (with a waitgroup handler filter)

**Comment by yue9944882** [comment]
thank you, closing in favor of #77816.

**Pull request closed without merging**
