### PR TITLE
Move some kubelet constants to a common place

### LINKED ISSUE #56516: //cmd/kubeadm fails to build in pure Go mode under Bazel due to cadvisor dependencies
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

I've been working on updating our `rules_go` dependency to be able to build our "static" binaries with cgo disabled to match the output from the non-bazel build.

It almost works, but `//cmd/kubeadm` is failing to build because it's trying to link in an empty library:
```
ERROR: .../code/kubernetes/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/container/raw/BUILD:3:1: GoCompile vendor/github.com/google/cadvisor/container/raw/linux_amd64_pure_stripped/go_default_library~/github.com/google/cadvisor/container/raw.a failed (Exit 1): compile failed: error executing command
  (cd .../.cache/bazel/_bazel_jgrafton/75e5737b0f848bf1b7c3ab3303c8bf72/execroot/__main__ && \
  exec env - \
  bazel-out/host/bin/external/io_bazel_rules_go/go/tools/builders/compile -go bazel-out/host/bin/external/go_stdlib_linux_amd64_pure/bin/go -root_file bazel-out/host/bin/external/go_stdlib_linux_amd64_pure/ROOT -goos linux -goarch amd64 '-cgo=0' -package_list external/go_sdk/packages.txt -src vendor/github.com/google/cadvisor/container/raw/factory.go -src vendor/github.com/google/cadvisor/container/raw/handler.go -dep github.com/golang/glog -dep github.com/google/cadvisor/container -dep github.com/google/cadvisor/container/common -dep github.com/google/cadvisor/container/libcontainer -dep github.com/google/cadvisor/fs -dep github.com/google/cadvisor/info/v1 -dep github.com/google/cadvisor/machine -dep github.com/google/cadvisor/manager/watcher -dep github.com/opencontainers/runc/libcontainer/cgroups -dep github.com/opencontainers/runc/libcontainer/cgroups/fs -dep github.com/opencontainers/runc/libcontainer/configs -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/golang/glog/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/google/cadvisor/container/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/google/cadvisor/container/common/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/google/cadvisor/container/libcontainer/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/google/cadvisor/fs/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/google/cadvisor/info/v1/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/google/cadvisor/machine/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/google/cadvisor/manager/watcher/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/opencontainers/runc/libcontainer/cgroups/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/linux_amd64_pure_stripped/go_default_library~/' -I 'bazel-out/k8-fastbuild/bin/vendor/github.com/opencontainers/runc/libcontainer/configs/linux_amd64_pure_stripped/go_default_library~/' -o 'bazel-out/k8-fastbuild/bin/vendor/github.com/google/cadvisor/container/raw/linux_amd64_pure_stripped/go_default_library~/github.com/google/cadvisor/container/raw.a' -trimpath . -I . -- -p github.com/google/cadvisor/container/raw)

Use --sandbox_debug to see verbose messages from the sandbox
vendor/github.com/google/cadvisor/container/raw/factory.go:23:2: import .../.cache/bazel/_bazel_jgrafton/75e5737b0f848bf1b7c3ab3303c8bf72/bazel-sandbox/4839007188253519489/execroot/__main__/bazel-out/k8-fastbuild/bin/vendor/github.com/google/cadvisor/container/libcontainer/linux_amd64_pure_stripped/go_default_library~/github.com/google/cadvisor/container/libcontainer.a: reading input: EOF
2017/11/28 15:05:07 error running compiler: exit status 1
Target //cmd/kubeadm:kubeadm failed to build
```

The issue seems to be that `cmd/kubeadm` depends on `pkg/kubelet/apis/kubeletconfig/validation`, which in turn depends on `pkg/kubelet/cm` for a few constants.

`pkg/kubelet/cm` is a fairly large package, and it has has build-tag controlled cgo and !cgo variants. The cgo variant depends on cadvisor, libcontainer, and other such cgo-heavy libraries, whereas the !cgo variants do not.

`go build` is pretty lazy about compiling dependencies, so it never builds cadvisor, libcontainer, etc in pure mode. Bazel doesn't have this ability, however, and so it tries to build these libraries in pure mode and fails.

Trying to get these end libraries to build in pure mode seems futile, especially since nobody would ever use them that way. A more viable fix is to break out the constants needed by `pkg/kubelet/apis/kubeletconfig/validation` into a separate package, which simplifies the build and prevents us from ever depending on these cgo-heavy libraries.

I'm not sure if there's precedence for this sort of refactoring, or where exactly the constants should go.

/area build-release

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
More context, see: https://github.com/kubernetes/kubernetes/issues/56516
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #56516
[thanks @ixdy for verifying this!]

**Special notes for your reviewer**:
@ixdy how can I verify #56516 against this locally?

/cc @ixdy @mtaufen 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ixdy** [comment]
Thanks so much for this!

The "easiest" way to test this is to merge or rebase off of https://github.com/ixdy/kubernetes/tree/pure-go-binaries and try to bazel build everything.

I already took your PR and rebased it on my branch, and the build worked - so I think this does indeed fix #56516.

**Comment by xiangpengzhao** [comment]
@ixdy thanks for verifying this! Is this a release blocker? If so, this PR needs to be marked in 1.9 milestone by one of @kubernetes/kubernetes-release-managers .

/cc @kubernetes/sig-node-pr-reviews to confirm this is a right place to move these constants to.

/kind bug
/sig node

**Comment by ixdy** [comment]
No, I don't see this as a release blocker, but it'd be nice to get in soon after code thaw.

**Comment by mtaufen** [comment]
/lgtm
put in v1.10 milestone wrt not a release blocker in above discussion

**Review by BenTheElder — APPROVED** [review]
/lgtm
Thanks @xiangpengzhao!

**Comment by ixdy** [comment]
any chance of an approval now that the queue is open again? @yujuhong

**Pull request merged**
