### PR TITLE
Automated cherry pick of #78672: Enable resize in default gce storageclass

### PR DESCRIPTION
**Pull request by msau42**
Cherry pick of #78672 on release-1.13.

#78672: Enable resize in default gce storageclass

### CODE REVIEW

**Review by saad-ali — APPROVED** [review]
/lgtm
/approve

**Comment by hoegaarden** [comment]
Thanks for the PRs, @msau42!

I was wondering why this is labeled as a bug? The original issue #75004 is labeled as feature, and to me it also looks and reads more like a feature. Could you give us some context on why you think it is of such high importance that it needs to go into all currently supported releases?

/cc @kubernetes/patch-release-team @kubernetes/sig-storage-bugs 

----

other PRs/CPs
- merged: master #78672
- open: 1.15 #79053 ; 1.14 #79054

**Comment by msau42** [comment]
@hoegaarden this sort of falls in between a feature and a bug.  It's a config change that we should have made when we moved the feature to beta to make it easier for users to consume.

**Comment by msau42** [comment]
That being said, it's not urgently breaking anyone and is more of a nice to have to improve the user experience.

**Comment by hoegaarden** [comment]
Consulting https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#patch-releases I don't think this qualifies as a change that should go into a patch release.

I will close this PR (and the ones on the other release branches).

Please, if you don't agree with that decision, ping me, the @kubernetes/patch-release-team, or re-open the PR(s)!

**Pull request closed without merging**
