### PR TITLE
Update yaml and json with multi arch test images

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:
This PR is for updating the yaml and json files under test/images folder with multi arch images
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```NONE
```

### CODE REVIEW

**Review by luxas — APPROVED** [review]
LGTM

**Comment by ixdy** [comment]
/lgtm

I assume at some point there will be templating or something to choose the correct arch?

**Comment by luxas** [comment]
Yes, but AFAICS, this is only example manifests in `test/images`, not manifests that actually are used...

**Pull request merged**
