### PR TITLE
wait until the pods are deleted completely

### PR DESCRIPTION
**Pull request by mengqiy**
Drain the pods on a node safely by keeping polling until all pods has been deleted.

``` release-note
kubectl drain now waits until pods have been delete from the Node before exiting
```

Fixes: #34782

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34778)

### CODE REVIEW

**Comment by AdoHe** [comment]
LGTM.

**Comment by pwittrock** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/kubectl/cmd/drain.go, line 407 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34778#-KUJTWSCpB77lq9yOMtn:-KUJTWSCpB77lq9yOMto:bas54b0) ([raw file](https://github.com/kubernetes/kubernetes/blob/47d2f4e260e301d3031df54dd04281070e94d869/pkg/kubectl/cmd/drain.go#L407)):*
> ```Go
> 	}
> 
> 	return wait.PollImmediate(kubectl.Interval, o.Timeout, func() (bool, error) {
> ```

We should print out the list of pods remaining.  The simplest way to do this is probably set the return value to a variable and if it is an error print the remaining pending pods

---

*[pkg/kubectl/cmd/drain.go, line 417 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34778#-KUJU7BdIqKIwmq7IS-b:-KUJU7BdIqKIwmq7IS-c:b-qapc2a) ([raw file](https://github.com/kubernetes/kubernetes/blob/47d2f4e260e301d3031df54dd04281070e94d869/pkg/kubectl/cmd/drain.go#L417)):*
> ```Go
> 				return false, err
> 			} else {
> 				pods[pendingPodCnt] = pods[i]
> ```

This is a lot of complexity just to prevent reallocating another slice on the client side.  I would rather keep the code simple even at the cost of a few K of memory briefly being allocated.  Just create another slice to store the pending pods and reassign at the end.

---

*[pkg/kubectl/cmd/drain.go, line 422 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34778#-KUJUNyNkORKsOik1C-j:-KUJUNyNkORKsOik1C-k:b-wjokmp) ([raw file](https://github.com/kubernetes/kubernetes/blob/47d2f4e260e301d3031df54dd04281070e94d869/pkg/kubectl/cmd/drain.go#L422)):*
> ```Go
> 		}
> 		if pendingPodCnt > 0 {
> 			pods = pods[:pendingPodCnt]
> ```

Why do we only look at the first `pendingPodCnt` here?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34778)*

**Comment by pwittrock** [comment]
Is there a reasonable way to test this?  Maybe pull your changes into a function and write a unit test?

**Comment by ymqytw** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/kubectl/cmd/drain.go, line 407 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34778#-KUJTWSCpB77lq9yOMtn:-KUQVnU7Pj9DxYkGfbHf:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/47d2f4e260e301d3031df54dd04281070e94d869/pkg/kubectl/cmd/drain.go#L407)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> We should print out the list of pods remaining.  The simplest way to do this is probably set the return value to a variable and if it is an error print the remaining pending pods
</details>
Done.

---

*[pkg/kubectl/cmd/drain.go, line 417 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34778#-KUJU7BdIqKIwmq7IS-b:-KUQVonUbhZaWuAczvrv:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/47d2f4e260e301d3031df54dd04281070e94d869/pkg/kubectl/cmd/drain.go#L417)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> This is a lot of complexity just to prevent reallocating another slice on the client side.  I would rather keep the code simple even at the cost of a few K of memory briefly being allocated.  Just create another slice to store the pending pods and reassign at the end.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34778)*

**Comment by ymqytw** [comment]
Tests added.

**Comment by ymqytw** [comment]
@k8s-bot gci gke e2e test this

**Comment by pwittrock** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/kubectl/cmd/drain.go, line 406 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34778#-KUT89r79rHOm0oJ7dLY:-KUT89r79rHOm0oJ7dLZ:bkdrypk) ([raw file](https://github.com/kubernetes/kubernetes/blob/55c6116d66e328641062258194747cc47c22ad2b/pkg/kubectl/cmd/drain.go#L406)):*
> ```Go
> 	}
> 
> 	getPodFn := func(namespace, name string) (*api.Pod, error) {
> ```

In the future make this a type definition so you don't need to redeclare it.

---

*[pkg/kubectl/cmd/drain_test.go, line 578 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34778#-KUT8WDII6Rl0jtuINtM:-KUT8WDII6Rl0jtuINtN:b-m3sjz3) ([raw file](https://github.com/kubernetes/kubernetes/blob/55c6116d66e328641062258194747cc47c22ad2b/pkg/kubectl/cmd/drain_test.go#L578)):*
> ```Go
> 				if newPod, found := newPodMap[name]; found {
> 					// randomly return old pod
> 					if rand.Float32() < 0.6 {
> ```

Don't do random things in tests.  It makes them unreproducible.  Keep track of the state and make an explicit decision about what to do.  

---

*[pkg/kubectl/cmd/drain_test.go, line 604 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34778#-KUT9Aqu4dotu8AW4yDv:-KUT9Aqu4dotu8AW4yDw:b-ru0emv) ([raw file](https://github.com/kubernetes/kubernetes/blob/55c6116d66e328641062258194747cc47c22ad2b/pkg/kubectl/cmd/drain_test.go#L604)):*
> ```Go
> 					return &oldPod, nil
> 				}
> 				return &api.Pod{}, errors.New(fmt.Sprintf("%q: not found", name))
> ```

Have separate cases for timeout  vs error from client

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/34778)*

**Comment by ymqytw** [comment]
Updated. PTAL

**Comment by jessfraz** [comment]
cherry-pick opened in https://github.com/kubernetes/kubernetes/pull/37140

**Pull request merged**
