### PR TITLE
Move PrintPerfData to the test

### PR DESCRIPTION
**Pull request by oomichi**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

PrintPerfData is called at e2e node tests and it depends on e2elog
and e2emetrics. This moves the function to the place which calls
the function for removing unnecessary dependencies from e2e node
subpackage.

Ref: https://github.com/kubernetes/kubernetes/issues/81427

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by oomichi** [comment]
This removes dependencies to two subpackages from the subpackage, but this makes duplicated function in different test modules.
I feel this is on the balance between merit and demerit, so I'd like to see opinions of that.
(Now I am facing circular dependency issues many times for this kind of cleanups, so I'd like to buy this TBH)

**Review by alejandrox1 — COMMENTED** [review]
/lgtm

**Pull request merged**
