### PR TITLE
CephRBD volume plugin and its csi migration support are removed

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup
/kind api-change
/kind deprecation

#### What this PR does / why we need it:

the CephRBD plugin and csi migration were deprecated in 1.28. In 1.31, we want to remove the support.

- https://github.com/kubernetes/kubernetes/pull/118303
- https://github.com/kubernetes/kubernetes/pull/118552

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
ACTION REQUIRED:

CephRBD volume plugin ( `kubernetes.io/rbd`) was removed in this release. And its csi migration support was also removed, so the `rbd` volume type became non-functional. Alternative is to use RBD CSI driver (https://github.com/ceph/ceph-csi/) in your Kubernetes Cluster. A re-deployment of your application is required to use the new driver if you were using `kubernetes.io/rbd` volume plugin before upgrading cluster version to 1.31+.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by carlory** [comment]
/cc @humblec @saad-ali @dims @jsafrane 

https://github.com/kubernetes/kubernetes/pull/124519 want to remove the file [cmd/kube-controller-manager/app/plugins_providers.go](https://github.com/kubernetes/kubernetes/pull/124519/files#diff-afb319d83106c7544fae215e2ae7c21a5fba847471d323de88d4100f8ce01e55L63). that file is used to register some volume plugins for the kube-controller-manager. i.e. `kubernetes.io/rbd` is one of them. 

In 1.31, we plan to remove the `kubernetes.io/rbd` support. so let's merge this PR before https://github.com/kubernetes/kubernetes/pull/124519. It's more reasonable.

**Comment by jsafrane** [comment]
lgtm from storage point of view, @dims, can you please approve?
@carlory can you please rebase?

**Comment by dims** [comment]
@carlory hit me up after rebase and the CI jobs are green please

**Comment by carlory** [comment]
Ping @dims, the unrequired job `/test pull-kubernetes-e2e-kind-cloud-provider-loadbalancer` always fails, I tested it on master branch and got same result https://github.com/kubernetes/kubernetes/pull/124776. https://github.com/kubernetes/kubernetes/pull/124729 is trying to fix it. 

Do we need block this PR to be merged?

**Comment by dims** [comment]
> Do we need block this PR to be merged?

Not for this PR.

/approve
/lgtm
/skip

**Pull request merged**
