### PR TITLE
Release 0.19.0

### PR DESCRIPTION
**Pull request by brendandburns**
@eparis @cjcullen @alex-mohr

### CODE REVIEW

**Comment by eparis** [comment]
This docs cloning is some new thing? Where'd I miss that discussion?

**Comment by brendandburns** [comment]
@eparis 
Issue: https://github.com/GoogleCloudPlatform/kubernetes/issues/8969
PR: https://github.com/GoogleCloudPlatform/kubernetes/pull/9305

The reasoning is that we need a place where the docs are not always perma-sync'd to HEAD.

**Comment by brendandburns** [comment]
Please hold off on merging this.  I've had requests for some new PRs into 0.19.0, I'm going to create a new roll-up PR.

**Comment by eparis** [comment]
do not forget to update the tag.

**Comment by brendandburns** [comment]
@eparis yep, thanks for the reminder.

**Comment by brendandburns** [comment]
Ok, this is ready for re-review.

@eparis I cleared and re-pushed the tag.  Please let me know if there are problems...

Thanks!
--brendan

**Pull request merged**
