### PR TITLE
e2e test: change from milli bytes to bytes in ephemeral-storage resource limits

### PR DESCRIPTION
**Pull request by s-ito-ts**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
The ephemeral-storage resource limits and requests are used NewMilliQuantity().
Milli bytes may be rounded up and it will cause the test to fail.
```
Resources: &v1.ResourceRequirements{
  Limits: v1.ResourceList{
    v1.ResourceEphemeralStorage: *resource.NewMilliQuantity(milliEphemeralStoragePerPod, "DecimalSI"),
  },
  Requests: v1.ResourceList{
    v1.ResourceEphemeralStorage: *resource.NewMilliQuantity(milliEphemeralStoragePerPod, "DecimalSI"),
  },
},
```

For example, the test fails for the following values:

  Number of pods   = 10
  Node allocatable = 441587256613000m bytes
  Requests per pod = 44158725661300m bytes <- 44158725662 bytes (by rounding up)

  44158725662 bytes x 10 pods > 441587256613 bytes

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
thanks!
/lgtm
/priority important-soon

**Comment by s-ito-ts** [comment]
/assign @wojtek-t
Could you approve this PR?

**Pull request merged**
