### PR TITLE
[WIP] ci: use local_memory_estimate

### PR DESCRIPTION
**Pull request by dims**
**What type of PR is this?**
> /kind bug

**What this PR does / why we need it**:
Let's see if this helps - borrowed from envoy ( https://github.com/envoyproxy/envoy/pull/7558/ )

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
PASS 1 - No OOM or interrupt

**Comment by dims** [comment]
PASS 2 - No OOM or interrupt, just one flake ( https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/87835/pull-kubernetes-e2e-gce/1225093525566132225/ )

/test pull-kubernetes-e2e-gce

**Comment by dims** [comment]
PASS 3 - 2 flakes, no OOM ( https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/87835/pull-kubernetes-e2e-gce/1225109005215469568/ )

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/87835/pull-kubernetes-e2e-gce-device-plugin-gpu/1225070412581310464/ stage failure

**Comment by dims** [comment]
PASS 4 - 2 flakes, no OOM ( https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/87835/pull-kubernetes-e2e-gce/1225109005215469568/ )

**Comment by dims** [comment]
Ack on the gpu failure @BenTheElder

**Comment by dims** [comment]
PASS 5 - same problem as the gpu run ( https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/87835/pull-kubernetes-e2e-gce/1225140837730488320/build-log.txt )

```
W0205 19:44:04.004] Server terminated abruptly (error code: 14, error message: '', log file: '/bazel-scratch/.cache/bazel/_bazel_prow/48d5366022b4e3197674c8d6e2bee219/server/jvm.out')
W0205 19:44:04.005] 
I0205 19:44:04.106] 
I0205 19:44:04.106] 
I0205 19:44:04.106] Signal ERR caught!
```

**Comment by dims** [comment]
Restarting counter with yet another toggle!

**Comment by dims** [comment]
No good. trying something else

**Comment by dims** [comment]
PASS 1 (take 3) - integration test flake - ( https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/87835/pull-kubernetes-integration/1225164126733471745 )

**Comment by dims** [comment]
dead end ... gonna try something else.

**Pull request closed without merging**
