### PR TITLE
Exit from NewController() for PersistentVolumeController when InitPlugins() failed

### PR DESCRIPTION
**Pull request by NickrenREN**
Exit from NewController() for PersistentVolumeController when InitPlugins() failed just like NewAttachDetachController() does

**Release note**:
```release-note
NONE
```
@jsafrane  @saad-ali  PTAL. Thanks in advance

### CODE REVIEW

**Comment by NickrenREN** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by NickrenREN** [comment]
ping @jsafrane . Should i change this ?

**Comment by jsafrane** [comment]
sorry, I got distracted with other stuff
/lgtm

**Comment by NickrenREN** [comment]
@deads2k  this needs your approval

**Pull request merged**
