### PR TITLE
Nominate alculquicondor to scheduler reviewers

### PR DESCRIPTION
**Pull request by alculquicondor**
/kind documentation
/sig scheduling

I'm nominating myself for sig-scheduling reviewers.
I have [submitted 11 PRs](https://github.com/kubernetes/kubernetes/pulls?utf8=✓&q=is%3Apr+author%3Aalculquicondor+merged%3A<%3D2019-09-09+) and [reviewed 12 PRs](https://github.com/kubernetes/kubernetes/pulls?utf8=✓&q=merged%3A<%3D2019-09-09++is%3Apr+-author%3Aalculquicondor+reviewed-by%3Aalculquicondor+).

I've been the primary reviewer of #81876, #80696 (framework), #81068, #80395, #79631 (even pod spreading) and #80696  (cleanup).

cc/ @Huang-Wei @ahg-g 

```release-note
NONE
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
+100 on supporting @alculquicondor to become the sig-scheduling reviewer.

**Comment by ahg-g** [comment]
/lgtm

Thanks Aldo for all your contributions so far, I strongly support this proposal.

**Comment by alculquicondor** [comment]
Thanks for the support!

/assign @smarterclayton

**Pull request merged**
