### PR TITLE
fix todo:Get rid of this duplicate function IsRetryableAPIError in favour of the one in test/utils

### PR DESCRIPTION
**Pull request by hanxiaoshuai**
**What this PR does / why we need it**:
fix todo:Get rid of this duplicate function IsRetryableAPIError in favour of the one in test/utils
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by shyamjvs** [comment]
Thanks for the cleanup @hanxiaoshuai !
Could you please rebase?

**Comment by shyamjvs** [comment]
@jdumars Could you please `/approved-for-milestone` this PR? It's just a testing cleanup.

**Comment by jdumars** [comment]
@shyamjvs done.  Should be good to go once you rebase.

**Comment by hanxiaoshuai** [comment]
@shyamjvs I have rebased , Thanks

**Pull request merged**
