### PR TITLE
Bump godep version to v80

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
Update the minimum godep, to v80 (supposed to be the final version).

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
Can you create a follow-up against https://github.com/kubernetes/publishing-bot updating to v80?

**Comment by sttts** [comment]
Do we plan to backport this?

**Comment by cblecker** [comment]
Not unless there is a reason to.

**Pull request merged**
