### PR TITLE
Automated cherry pick of #102306: Return UnschedulableAndUnresolvable instead of Error when
#102465: Return UnschedulableAndUnresolvable when looking up

### PR DESCRIPTION
**Pull request by ahg-g**
Cherry pick of #102306 #102465 on release-1.20.

#102306: Return UnschedulableAndUnresolvable instead of Error when
#102465: Return UnschedulableAndUnresolvable when looking up

Part of #102305

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by ahg-g** [comment]
@kubernetes/release-managers

**Comment by puerco** [comment]
https://github.com/kubernetes/kubernetes/pull/102514#issuecomment-856411618

**Comment by ahg-g** [comment]
> Quick question about cherry picking this to 1.19:
> [#102514 (comment)](https://github.com/kubernetes/kubernetes/pull/102514#issuecomment-856411618)

created https://github.com/kubernetes/kubernetes/pull/102695

**Pull request merged**
