### PR TITLE
Automated cherry pick of #82322: bump metrics-server version to v0.3.4

### PR DESCRIPTION
**Pull request by olagacek**
Cherry pick of #82322 on release-1.15.

#82322: bump metrics-server version to v0.3.4

### CODE REVIEW

**Comment by tpepper** [comment]
/kind bug
/priority important-soon
from parent PR

**Comment by tpepper** [comment]
Do we have a rationale for cherry-picking this?  What's v0.3.4's advantage over v0.3.3?

**Comment by olagacek** [comment]
It adds some performance fixes (scraping cpu and memory from apiserver instead of all the fields), but as v3.5 is available I've created new cherry pick with 3.5 version as it has some additional performance tuning (using protobuf instead of json). It can be found here: https://github.com/kubernetes/kubernetes/pull/83051

**Pull request closed without merging**
