### PR TITLE
Cherry pick stabilizing HPA e2e tests to 1.11

### PR DESCRIPTION
**Pull request by jbartosik**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
/kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: HPA e2e tests are failing in 1.11. I fixed them on HEAD but they're failing in 1.11.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

Issue #69444
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by jbartosik** [comment]
Issue #70655

**Comment by AishSundar** [comment]
@foxish 1.11 patch manager for CP request. This CP into 1.11 is critical to get a clean CI Signal for 1.13

**Comment by foxish** [comment]
Done, approved.

**Pull request merged**
