### PR TITLE
Enable VolumeSnapshotDataSource Feature Gate

### PR DESCRIPTION
**Pull request by xing-yang**
**What this PR does / why we need it**:
This PR enables feature gate for VolumeSnapshotDataSource.

It also adds a condition called "DataPopulated" into PV. With the feature of snapshot and data source, volume might be created from snapshot source with data populated into the volume instead of an empty one. The external provisioner needs to understand the data source and also mark the condition "DataPopualted" to true. The PV controller will check this condition if the data source of PVC is specified. Only if the condition is true, the PVC can be marked as "Bound" phase.

Address design proposal: kubernetes/community#2495

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
kubernetes/features#177

**Special notes for your reviewer**:

**Release note**:

```release-note
Allow volume to be created from a volume snapshot data source.
```

### CODE REVIEW

**Comment by neolit123** [comment]
@xing-yang is there a tracking issue for this API change?

**Comment by xing-yang** [comment]
@neolit123 Yes, it is here: https://github.com/kubernetes/features/issues/177

**Comment by neolit123** [comment]
@xing-yang 
please link the issue in the first post so that others can see it and also add a `Release note` explaining the feature to the users reading the release notes for 1.12. :+1: 

thanks!

/kind feature

**Comment by xing-yang** [comment]
@neolit123 Added a release note.  Thanks!

**Comment by xing-yang** [comment]
I've included changes in this PR to https://github.com/kubernetes/kubernetes/pull/67087.  So this can be closed now.

**Pull request closed without merging**
