### PR TITLE
Re-enable ECDSA private server key use

### LINKED ISSUE #9889: 0.17 to 0.18 ECDSA keys regression
After successfully setting up TLS-secured kubernetes at 0.17 I failed to upgrade to 0.18, specifically apiserver failing to start with:

```
Invalid Authentication Config: asn1: structure error: tags don't match (16 vs {class:0 tag:2 length:1 isCompound:false}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 set:false omitEmpty:false} tbsCertificate @2
```

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #9889

### CODE REVIEW

**Comment by saad-ali** [comment]
v1.0 triage needed
Assigning @erictune

**Comment by saad-ali** [comment]
Marked associated issue (#9889) as v1.0-candidate. Can merge or wait on this PR based on that triage.

**Comment by erictune** [comment]
The code changes look fine.  But I don't understand how it "enables ECDSA".

**Comment by erictune** [comment]
lgtm

**Comment by liggitt** [comment]
If you used an ECDSA key as the server private key (which works fine), and didn't specify a key to use for service account token signing (which is allowed), it would default to using the server key, then fail because only RSA keys can be used with the JWT library.

**Pull request merged**
