### PR TITLE
Fixes for Azure

### PR DESCRIPTION
**Pull request by Snesha**
With the recent changes to the salt scripts, Azure was dropped. Enabling base scripts for Azure with a couple of other fixes for networking issues.

### CODE REVIEW

**Comment by mikedanese** [comment]
@errordeveloper

**Comment by mikedanese** [comment]
@Snesha Can you please sign the CLA?

**Comment by errordeveloper** [comment]
@mikedanese please don't CC me on this one, as I only maintain the CoreOS/Weave implementation at the moment.

**Comment by mikedanese** [comment]
@errordeveloper ahhh ok did not realize there were multiple azure getting started guides. Sorry.

**Comment by mikedanese** [comment]
Please sign CLA, rebase and reopen if you still want this @Snesha

**Pull request closed without merging**
