### PR TITLE
Automated cherry pick of #89444 upstream release 1.18

### PR DESCRIPTION
**Pull request by saad-ali**
This fixes bug with xfs mount failing because of xfs_repair
being called. Fixes https://github.com/kubernetes/utils/issues/141

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Fix https://github.com/kubernetes/utils/issues/141
Automated cherry pick of #89444 upstream release 1.18

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
/sig storage
/priority important-soon

**Does this PR introduce a user-facing change?**:

```release-note
Fix bug with xfs_repair from stopping xfs mount
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
k8s.io/utils changes look good

/approve
/lgtm

**Comment by saad-ali** [comment]
/hold
Until https://github.com/kubernetes/kubernetes/pull/89444 merges

**Comment by xing-yang** [comment]
#89444 is merged.

/hold cancel

**Pull request merged**
