### PR TITLE
Improve code coverage for pkg/api/util

### PR DESCRIPTION
**Pull request by tanshanshan**
**What this PR does / why we need it**:

Improve code coverage for pkg/api/util .

Thanks.

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@k8s-bot ok to test

**Comment by caesarxuchao** [comment]
Thanks, @tanshanshan.

**Comment by tanshanshan** [comment]
@caesarxuchao  , Could you  give  a release-note-none label ?

Thanks.

**Comment by caesarxuchao** [comment]
@thockin could you approve the change? It just added a unit test for a util function.

**Comment by gyliu513** [comment]
lgtm

**Comment by thockin** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
