### PR TITLE
Do not return partial list of API/Groups on startup

### LINKED ISSUE #47977: Kubectl API discovery caching may be up to 10 minutes stale
kubectl caches API discovery results without being aware of its changes. Registering/Removing a new API service with api aggregator results in a change in API discovery but kubectl has no way to know the result is changed.

Possible solutions:

short term - implement e-tag for API discovery
long term - move to OpenAPI for api discovery

This is possibly a release blocker.

cc @lavalamp @pwittrock @dchen1107

@kubernetes/sig-cli-misc @kubernetes/sig-api-machinery-misc

### PR DESCRIPTION
**Pull request by mbohlool**
fixes #47977

### CODE REVIEW

**Comment by deads2k** [comment]
I'm against this change. It is slicing across layers, plumbing knowledge from higher levels down to lower levels in a way that produces a cyclical dependency inside a given component.

Even worse, this is trying to resolve a "problem" that has existed since we introduced configurable API groups and the server could restart with more groups after the client has already run discovery.  The call chains of requests and responses looks identical to clients in that case as compared to the current condition.

If the federation up scripts need a healthz wait, let them have it there instead of plumbing a healthz request down into an unrelated handler and introducing a cyclical dependency into some of our core libraries.

**Comment by deads2k** [comment]
Also, preventing clients from using discovery information to debug why their server isn't healthy seems like a really bad idea.

**Comment by mbohlool** [comment]
@deads2k What do you mean by cyclical dependency? The dependency I've added in the import statement has been used in other places in the same package.

In regard to existing problem, I don't agree with that. It is true that clients could have an outdated cache if we change API groups and restart the server, but we never had the problem on the first startup. That is a behaviour change.

For debugging, I can return 404 and include the whole list for debugging in the error message.

This could be the wrong fix and we can discuss it, but I think the problem exists and we need a fix for it.

**Comment by deads2k** [comment]
> @deads2k What do you mean by cyclical dependency? The dependency I've added in the import statement has been used in other places in the same package.

You've created a state where a handler relies on the APIServer and the APIServer relies upon the handler.



> In regard to existing problem, I don't agree with that. It is true that clients could have an outdated cache if we change API groups and restart the server, but we never had the problem on the first startup.

To a client, there is no distinction based on the number of startups.  A client has no idea how many startups there have been.

**Comment by liggitt** [comment]
> we never had the problem on the first startup

That is not accurate. Prior to 1.6, there was a bug in the kubectl caching behavior where an empty or partially successful discovery result could get cached (see https://github.com/kubernetes/kubernetes/pull/42267). Additionally, TPR API groups have always appeared in discovery subsequent to server start.

> That is a behaviour change.

Server-side behavior changes which do not break API guarantees, but do expose client-side bugs are a judgement call.

For example, we've never sent gzipped content from the server before 1.7, so a client that sent an `Accept-Encoding: gzip` header without actually handling a gzipped response would be broken by https://github.com/kubernetes/kubernetes/pull/45666

API discovery docs have been dynamic for multiple releases. Bugs in client-side caching behavior (which is what the `kubectl api-versions` and `kubefed init` issues are) are not a good reason to entangle the server startup to this degree, especially when the client-side fixes are well understood and able to be included in the 1.7 release as well.

**Comment by mbohlool** [comment]
> Server-side behavior changes which do not break API guarantees, but do expose client-side bugs are a judgement call.

The fact that our test fails means we will break some users. Our client assumed this behaviour and it is not unreasonable for others to assumed it.

**Comment by mbohlool** [comment]
In the Burndown meeting, the decision was not to fix API server, only document it as a known issue.

I had an alternate fix that addresses some of the comments, just going to leave it here for reference:  https://github.com/mbohlool/kubernetes/commit/1e365522232a826750fec74507eb3ef75fbff6a0

**Pull request closed without merging**
