### PR TITLE
fix failing test TestDefaultsYAML on mac

### LINKED ISSUE #73853: TestDefaultsYAML/KubeletConfiguration_default_v1beta1 is failing on MacOS
**Which jobs are failing**:

TestConfigFileAndDefaultsToInternalConfig is failing on MacOS.

**Which test(s) are failing**:

```
$ go test ./cmd/kubeadm/app/util/config/... -v -run TestConfigFileAndDefaultsToInternalConfig
    --- FAIL: TestConfigFileAndDefaultsToInternalConfig/incompleteYAMLToDefaultedv1beta1 (0.00s)
        initconfiguration_test.go:123: the expected and actual output differs.
            	in: testdata/defaulting/master/incomplete.yaml
            	out: testdata/defaulting/master/defaulted.yaml
            	groupversion: kubeadm.k8s.io/v1beta1
            	diff: 
            --- expected
            +++ actual
            @@ -115,7 +115,6 @@
               imagefs.available: 15%!
            (MISSING)   memory.available: 100Mi
               nodefs.available: 10%!
            (MISSING)-  nodefs.inodesFree: 5%!
            (MISSING) evictionPressureTransitionPeriod: 5m0s
             failSwapOn: true
             fileCheckFrequency: 20s
```

**Since when has it been failing**:

**Testgrid link**:

**Reason for failure**: 

`nodefs.inodesFree: 5%` is missing.

**Anything else we need to know**:

Refer https://github.com/kubernetes/kubernetes/pull/67709.

/sig node
/kind bug
/assign

### PR DESCRIPTION
**Pull request by Abirdcfly**
Signed-off-by: Abirdcfly <fp544037857@gmail.com>

#### What type of PR is this?
/kind bug
/kind cleanup

#### What this PR does / why we need it:
```bash
$ go test k8s.io/kubernetes/pkg/kubelet/apis/config/scheme -run TestDefaultsYAML
--- FAIL: TestDefaultsYAML (0.01s)
    --- FAIL: TestDefaultsYAML/KubeletConfiguration_default_v1beta1 (0.00s)
        helpers.go:90: Output does not match expected, diff (- want, + got):
              (
                """
                ... // 36 identical lines
                  memory.available: 100Mi
                  nodefs.available: 10%
            -     nodefs.inodesFree: 5%
                evictionPressureTransitionPeriod: 5m0s
                failSwapOn: true
                ... // 49 identical lines
                """
              )

        helpers.go:105: if the diff is expected because of a new type or a new field, re-run with UPDATE_COMPONENTCONFIG_FIXTURE_DATA=true to update the compatibility data or generate missing files
FAIL
FAIL    k8s.io/kubernetes/pkg/kubelet/apis/config/scheme        0.023s
FAIL
```
There is a fix pr https://github.com/kubernetes/kubernetes/pull/104376 but closed. 
Fix this problem inspired by @liggitt's suggestion https://github.com/kubernetes/kubernetes/pull/104376#issuecomment-899532470
#### Which issue(s) this PR fixes:

Fixes #73853

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Abirdcfly** [comment]
Besides that, I'm wondering if I should switch to a linux machine to develop the kubernetes code, it seems that there are some tests on mac that don't pass (by `make test`), does it make sense to fix those tests? 🤔

**Comment by endocrimes** [comment]
> Besides that, I'm wondering if I should switch to a linux machine to develop the kubernetes code

@Abirdcfly I'd definitely recommend that - given that most of the codebase only supports being ran on Linux/(increasingly also) Windows, doing development of those parts on a Mac is an uphill battle sometimes

**Comment by Abirdcfly** [comment]
> > Besides that, I'm wondering if I should switch to a linux machine to develop the kubernetes code
> 
> 
> 
> @Abirdcfly I'd definitely recommend that - given that most of the codebase only supports being ran on Linux/(increasingly also) Windows, doing development of those parts on a Mac is an uphill battle sometimes

I'm not sure if we should continue to support compiling and testing kubernetes code on Mac......

If not, I guess we need to delete the Mac-related content in the document? 

Maybe I should @kubernetes/sig-contributor-experience ? (It may be wrong. Please correct me.) 🧐

**Comment by liggitt** [comment]
Apiserver, controllers, and clients definitely work on OSX. This code is specifically in the kubelet, which isn't supported on Darwin

**Comment by liggitt** [comment]
sorry, meant to open the issue, not the PR

**Pull request closed without merging**
