### PR TITLE
change CONTROLLER, ReplicaSet and Job column titles to NAME

### LINKED ISSUE #8476: Print object type as first column in `kubectl get`
When we originally implemented get, the first column was the type, i.e. "POD", not "NAME".  Over time others implemented "NAME" as the primary column in other printers.

One benefit of "\<TYPE\>" is that the output (if saved or pasted or viewed later) gives a clue about the type.  A downside is that the column width can be much longer - i.e. "SERVICE ACCOUNT".

We should make a decision and be consistent (change Pod, or change everything else).

### PR DESCRIPTION
**Pull request by adohe-zz**
@bgrant0607 I just update the CONTROLLER, ReplicaSet and JOB column titles. would you mind reviewing this?

Fixes #8476

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks!

LGTM

**Comment by AdoHe** [comment]
@bgrant0607 would you minding take a look at the e2e failure? I have opened an issue #21530 I want to get this PR merged soon and then I will open other PRs to make kubectl more consistent. Thanks very much :)

**Comment by bgrant0607** [comment]
@k8s-bot test this issue: #21451

**Comment by bgrant0607** [comment]
@AdoHe Sorry, we've been having quite a few test problems recently.

**Comment by bgrant0607** [comment]
@k8s-bot test this issue: #21463

**Comment by bgrant0607** [comment]
@k8s-bot test this issue: #21463

**Pull request merged**
