### PR TITLE
Add the GCE cluster name to instance metadata

### LINKED ISSUE #20082: Add Kubernetes cluster name to instance metadata and the container environment
Good day.

It would be beneficial to have Kubernetes cluster name available through instance metadata (when running on GKE), as an environment variable, or both. 

The use case: In case of multiple instances of an application are running, each in it's own (development) cluster, the application needs to pull developer-specific configuration according to it's cluster name. For example, it my application is named "burgul" and I have developers Alice and Bob, then each of them will launch its own cluster named burgul-dev-alice and burgul-dev-bob respectively. The code running in the cluster then may want to load developer-specific parameters from external configuration service.

The full details are in the following discussion: https://groups.google.com/forum/#!topic/google-containers/FK_6ySjTp7I

### PR DESCRIPTION
**Pull request by roberthbailey**
Fixes #20082.

/cc @haizaar

### CODE REVIEW

**Comment by zmerlynn** [comment]
LGTM

**Comment by roberthbailey** [comment]
@k8s-bot test this issue #21995

**Comment by andyzheng0831** [comment]
@roberthbailey I happen to see this change. FYI, if we want to upload only the cluster name as a metadata, we don't have to echo it in a txt file and upload the file as metadata value. A simpler way is directly using the string as metadata value, and put the <key, value> pair under "--metadata" of gcloud commands

**Comment by roberthbailey** [comment]
@andyzheng0831 - Understood, but I didn't want to change the startup scripts too much. 

The `create-node-template` function assumes that all metadata fields passed in are read from a file, and since there can be a variable number of them, it isn't trivial to just add a new positional argument to the function.

**Comment by wojtek-t** [comment]
@k8s-bot test this please github issue: #IGNORE (old tests)

**Comment by roberthbailey** [comment]
Rebased.

**Comment by roberthbailey** [comment]
Re-applying lgtm since I just rebased.

**Comment by haizaar** [comment]
Thanks for implementing it! Do you have any guesstimate when it will land
in GKE?

On 4 March 2016 at 20:44, Abhi Shah <notifications@github.com> wrote:

> Merged #22043 <https://github.com/kubernetes/kubernetes/pull/22043>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/22043#event-578186985>.
>



-- 
Zaar

**Comment by roberthbailey** [comment]
This commit adds it to OSS GCE for the 1.2 release of k8s. It should be in GKE in a similar timeframe, but you can follow the GKE release notes by watching https://cloud.google.com/container-engine/release-notes or subscribing to https://groups.google.com/forum/#!forum/gke-release-notes to know exactly when the features gets added.

As a side note, the new metadata entry will be present on nodes in new clusters or on nodes that get upgraded (after the feature is released). So any existing nodes won't automatically inherit an updated template with the metadata entry -- you will need to create a new template (by upgrading your nodes) to get the new field.

**Comment by haizaar** [comment]
Thank you Robert!

On 6 March 2016 at 07:44, Robert Bailey <notifications@github.com> wrote:

> This commit adds it to OSS GCE for the 1.2 release of k8s. It should be in
> GKE in a similar timeframe, but you can follow the GKE release notes by
> watching https://cloud.google.com/container-engine/release-notes or
> subscribing to https://groups.google.com/forum/#!forum/gke-release-notes
> to know exactly when the features gets added.
>
> As a side note, the new metadata entry will be present on nodes in new
> clusters or on nodes that get upgraded (after the feature is released). So
> any existing nodes won't automatically inherit an updated template with the
> metadata entry -- you will need to create a new template (by upgrading your
> nodes) to get the new field.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/22043#issuecomment-192809712>
> .
>



-- 
Zaar

**Pull request merged**
