### PR TITLE
test images: Mirrors dockerhub images to staging

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

**What this PR does / why we need it**:

Dockerhub will introduce rate limiting in November, and a lot of E2E tests are relying on the busybox image. It could potentially become an issue causing jobs to fail because of this.

Ideally, we'd have the busybox image mirrored on gcr.io, but that could take some time. Until then, we can just have the Image Builder mirror the image for us in the staging registry and use that for tests until this issue is solved. The busybox image should NOT be promoted out of staging.

During the sig-testing meeting, it was decided that we should do the same for the other images are hosted on dockerhub.

Two different versions of ``httpd`` and ``nginx`` have to build, and thus, the have different folders. An ``ALIAS`` file was added to ``httpd-new`` and ``nginx-new`` in order to keep the same image name.

Note that the image ``docker.io/gluster/glusterdynamic-provisioner:v1.0`` only has a ``linux/amd64`` image.

**Which issue(s) this PR fixes**:

Fixes #

Related PR: Adds Image Builder jobs for these images: https://github.com/kubernetes/test-infra/pull/20265

**Special notes for your reviewer**:

Mitigate dockerhub changes rolling out Nov 1st: https://github.com/kubernetes/test-infra/issues/19477

Image building logs: https://paste.ubuntu.com/p/9q8HtpwpnW/

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by justaugustus** [comment]
/retest
The rationale SGTM!

**Comment by claudiubelu** [comment]
Image building logs: https://paste.ubuntu.com/p/jDvZHshhdV/ (+ commit from: https://github.com/kubernetes/kubernetes/pull/95032)

Note: I was already intending to add the nginx and httpd images (+ Windows support: https://github.com/kubernetes/kubernetes/pull/77269), so I've reused some bits from there.

**Comment by spiffxp** [comment]
/priority important-soon
/kind cleanup
/triage accepted
/hold
/cc @thockin @BenTheElder 
I'd like your input

**Review by spiffxp — APPROVED** [review]
/lgtm

but I would like input from others

**Comment by claudiubelu** [comment]
/hold

It seems that most of these images have been mirrored on ``mirror.gcr.io/library`` as manifest lists, which is great. The only images that are not there at the moment are nginx:1.15-alpine and perl:5.26.

**Comment by claudiubelu** [comment]
Update: nginx:1.15-alpine and perl:5.26 are also on mirror.gcr.io as manifest lists:

ubuntu@ubuntu:~/run_e2e/test-infra$ docker run --rm mplatform/mquery mirror.gcr.io/library/nginx:1.15-alpine
Image: mirror.gcr.io/library/nginx:1.15-alpine
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v6
   - linux/arm64
   - linux/386
   - linux/ppc64le
   - linux/s390x
ubuntu@ubuntu:~/run_e2e/test-infra$ docker run --rm mplatform/mquery mirror.gcr.io/library/perl:5.26
Image: mirror.gcr.io/library/perl:5.26
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v7
   - linux/arm64
   - linux/386
   - linux/ppc64le
   - linux/s390x

**Comment by claudiubelu** [comment]
/close

No longer needed,

**Comment by BenTheElder** [comment]
we still may want to consider this, since the mirror doesn't have guarantees.

**Comment by justaugustus** [comment]
/hold

I feel like this may be the wrong approach here
i.e.,:
- creating new Dockerfiles to maintain
- building and repushing

What I think we want is:
- a remote-to-remote repo copy
- digest preservation
- no fiddling with multi-arch
- stored in the mirror registry so others are aware and can take advantage of these mirrors

@claudiubelu -- can you get me the exact list of images/tags that you're interested in, and give me a few days to work a prototype, so you can see what I mean?

cc: @wilsonehusin

**Comment by claudiubelu** [comment]
> 
> 
> /hold
> 
> I feel like this may be the wrong approach here
> i.e.,:
> 
>     * creating new Dockerfiles to maintain
> 
>     * building and repushing
> 
> 
> What I think we want is:
> 
>     * a remote-to-remote repo copy
> 
>     * digest preservation
> 
>     * no fiddling with multi-arch
> 
>     * stored in the mirror registry so others are aware and can take advantage of these mirrors
> 
> 
> @claudiubelu -- can you get me the exact list of images/tags that you're interested in, and give me a few days to work a prototype, so you can see what I mean?
> 
> cc: @wilsonehusin

From https://github.com/kubernetes/kubernetes/issues/97027 , these are the images that are currently on dockerhub but used in E2E tests (as it can be seen in ``kubernetes/test/utils/image/manifest.go``:

``
docker.io/gluster/glusterdynamic-provisioner:v1.0
docker.io/library/busybox:1.29
docker.io/library/httpd:2.4.38-alpine
docker.io/library/httpd:2.4.39-alpine
docker.io/library/nginx:1.14-alpine
docker.io/library/nginx:1.15-alpine
docker.io/library/perl:5.26
docker.io/library/redis:5.0.5-alpine
``

IMO, we can still go ahead with the images: ``busybox, httpd, nginx``, since ultimately, what we need is not just a simple mirror for them. On dockerhub, they do not contain any Windows images in their manifest lists, but we need them for our test jobs (the Kubernetes busybox image already has a Windows manifest list). I have a PR opened for the nginx and httpd images here: https://github.com/kubernetes/kubernetes/pull/77269

**Comment by BenTheElder** [comment]
I think that's a good point https://github.com/kubernetes/kubernetes/pull/95567#issuecomment-747071427,
also, nothing precludes migrating from a repo to repo copy implementation later (except that it sounds like that won't be sufficient b/c windows), but in the meantime people reported hitting issues with pull limits running tests right now.

I asked for this explicitly when the topic came up in SIG testing, I'm inclined to recommend we take this straightforward approach now to bring things under our control. 

Additionally: performing a build of a custom image discourages users from trying to use kubernetes as a mirror of these images for arbitrary purposes (which we shouldn't take the cost or maintenance load for), instead of seeing these as all our e2e custom images, even if customization is very light.

**Comment by claudiubelu** [comment]
FWIW, the image build logs for the images added in this PR using this PR: https://paste.ubuntu.com/p/zYHHTF4QkW/

**Comment by claudiubelu** [comment]
> 
> 
> /hold
> 
> I feel like this may be the wrong approach here
> i.e.,:
> 
>     * creating new Dockerfiles to maintain
> 
>     * building and repushing
> 
> 
> What I think we want is:
> 
>     * a remote-to-remote repo copy
> 
>     * digest preservation
> 
>     * no fiddling with multi-arch
> 
>     * stored in the mirror registry so others are aware and can take advantage of these mirrors
> 
> 
> @claudiubelu -- can you get me the exact list of images/tags that you're interested in, and give me a few days to work a prototype, so you can see what I mean?
> 
> cc: @wilsonehusin

Any news?

**Comment by jayunit100** [comment]
Hi folks hitting rate limits on e2es. What's the simplest way to unblock this? 

We can run our own builds and publish if needed .  What's the easiest thing to do here that is iterable ?

**Comment by dims** [comment]
going with @BenTheElder 's comment here : https://github.com/kubernetes/kubernetes/pull/95567#issuecomment-747201982

we can always iterate

/approve
/lgtm
/hold cancel

**Pull request merged**
