### PR TITLE
Prune inactive owners from api-approver owned OWNERS files.

### PR DESCRIPTION
**Pull request by mrbobbytables**
**What type of PR is this?**

/kind cleanup

**Which issue(s) this PR fixes**:

This is part of a larger cleanup of inactive owners.

Owners removed had no activity from January 1st, 2018 to September 1st, 2019. 

For more information on this clean up, see the below links:
- Tracking Issue: https://github.com/kubernetes/kubernetes/issues/76269
- [Kubernetes-dev mailing list announcement](https://groups.google.com/d/msg/kubernetes-dev/4160VsBL7OI/BsBRZSqpCQAJ)

**Special notes for your reviewer**:

All of these OWNERS files either reference [api-approvers](https://github.com/kubernetes/kubernetes/blob/f0e1d394f13560cd6094722ec0b3969b05830fd0/OWNERS_ALIASES#L299-L305) as their approver or the [same set of people explicitly defined](https://github.com/kubernetes/kubernetes/blob/f0e1d394f13560cd6094722ec0b3969b05830fd0/pkg/apis/OWNERS#L5-L10) (erictune, lavalamp, smarterclayton, thockin, and liggitt).

With that -- assigning a sub-set for review:

/assign @lavalamp @smarterclayton @thockin 

**Does this PR introduce a user-facing change?**: 

```release-note
NONE
```

/sig contributor-experience
/priority important-soon

### CODE REVIEW

**Comment by lavalamp** [comment]
/lgtm
/approve

/hold

I think it'd be good to @ mention folks in the removal PRs.

**Comment by mrbobbytables** [comment]
For notification:
@markturansky @jszczepkowski @fgrzadkowski @feihujiang @ghodss @tmrts @fabioy @goltermann

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by mrbobbytables** [comment]
As 10 days have past, with no further comments, going to go ahead and remove the hold.
/hold cancel

**Pull request merged**
