### PR TITLE
Update etcd version to 2.0.9 for ubuntu k8s

### PR DESCRIPTION
**Pull request by WIZARD-CXY**
Recently I met the same problem the same as https://github.com/GoogleCloudPlatform/kubernetes/issues/6059 .The solution is simple, just use 2.0.9 version of etcd and it has been merged https://github.com/GoogleCloudPlatform/kubernetes/pull/6544 for saltstack.So I update the doc and script.Tested OK!
 @rjnagal  Please merge it

### CODE REVIEW

**Comment by WIZARD-CXY** [comment]
Interesting bot.please any of the owner may take a look at this small but important patch

**Comment by WIZARD-CXY** [comment]
Interesting bot.please any of the owner may take a look at this small but important patch

**Comment by rjnagal** [comment]
LGTM

**Comment by rjnagal** [comment]
This one just updates etcd on ubuntu cluster and shouldn't affect e2e. Should be safe to merge.

**Pull request merged**
