### PR TITLE
fix spelling error 'retrive' in log

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by SataQiu** [comment]
Thanks @qingsenLi 
/ok-to-test
/kind cleanup
/priority backlog
/cc @SataQiu

**Comment by qingsenLi** [comment]
/cc @abrarshivani @SandeepPissay 
thanks

**Review by SataQiu — APPROVED** [review]

**Comment by andrewsykim** [comment]
@qingsenLi the vSphere cloud provider was moved to staging so this PR needs to be rebased updating the new location https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/legacy-cloud-providers/vsphere

**Comment by qingsenLi** [comment]
/cc @andrewsykim 
Thanks, I have updated the PR.

**Comment by andrewsykim** [comment]
/lgtm
/approve
/retest

Thanks!

**Pull request merged**
