### PR TITLE
Update aws-sdk-go to 1.38.49

### PR DESCRIPTION
**Pull request by hyakuhei**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Update saws/aws-sdk-go from version 1.35.24 to version 1.38.49.

This version change brings the following improvements:
* Large API and documentation improvements throughout the SDK.
* Enables SSO provider to be mixed with other credential providers.
* Support FIPS Global Partition Endpoints

#### Which issue(s) this PR fixes:
n/a

#### Special notes for your reviewer:
hack/pin-dependency.sh github.com/aws/aws-sdk-go v1.38.49
hack/update-vendor.sh
hack/lint-dependencies.sh

#### Does this PR introduce a user-facing change?
NONE

### CODE REVIEW

**Comment by hyakuhei** [comment]
Hmmm, this is my first attempted PR in a long time, I'll fix the CLA issue. (Linux Foundation site seems to say everything is fine)... Standby...

**Comment by dims** [comment]
/approve
/lgtm

/assign @thockin @smarterclayton 

Tim, Clayton, need your root approval please

**Comment by liggitt** [comment]
needs rebase, then lgtm

**Comment by hyakuhei** [comment]
Ok, I clearly broke something here. Standby please.

**Comment by micahhausler** [comment]
Looks like flakes
/test pull-kubernetes-e2e-gce-ubuntu-containerd
/test pull-kubernetes-unit

**Comment by dims** [comment]
good to go!

/approve
/lgtm

/assign @liggitt 

```
Files /logs/artifacts/stats-base.json and /logs/artifacts/stats.json are identical
```

**Pull request merged**
