### PR TITLE
Fix for OOMKiller test consistently failing in EC2 cgroupv1 serial jobs

### LINKED ISSUE #126009: OOMKiller test consistently failing in EC2 cgroupv1 serial jobs
### Which jobs are failing?

* ci-cgroupv1-containerd-node-arm64-e2e-serial-ec2-eks
* ci-cgroupv1-containerd-node-e2e-serial-ec2-eks

### Which tests are failing?

```
E2eNode Suite.[It] [sig-node] OOMKiller for pod using more memory than node allocatable [LinuxOnly] [Serial] single process container without resource limits The containers terminated by OOM killer should have the reason set to OOMKilled
```

### Since when has it been failing?

It has been failing consistently for a long time.

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#ci-cgroupv1-containerd-node-e2e-serial-ec2-eks
https://testgrid.k8s.io/sig-node-containerd#ci-cgroupv1-containerd-node-arm64-e2e-serial-ec2-eks

### Reason for failure (if possible)

```
{ failed [FAILED] Failed waiting for pod to terminate, nodeallocatable-oomkiller-test-2000/oomkill-nodeallocatable-pod: Timed out after 300.001s.
The matcher passed to Eventually returned the following error:
    <*errors.errorString | 0xc0016b6a30>: 
    Expected pod "oomkill-nodeallocatable-pod" in namespace "nodeallocatable-oomkiller-test-2000" to be terminated with reason "", got reason: "Evicted"
    {
        s: "Expected pod \"oomkill-nodeallocatable-pod\" in namespace \"nodeallocatable-oomkiller-test-2000\" to be terminated with reason \"\", got reason: \"Evicted\"",
    }
In [It] at: k8s.io/kubernetes/test/e2e_node/oomkiller_linux_test.go:123 @ 07/10/24 12:18:42.111
}
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by dims**
#### What type of PR is this?

/kind failing-test
/kind bug

#### What this PR does / why we need it:

There is a race condition that shows up in Amazon Linux2 based cgroupv1 CI jobs between eviction manager and the oom kill the tests depends on. More often than not the eviction manager wins and the tests fail.

In this PR which is a test only change we set the 
- PriorityClassName to `"system-node-critical"` to ensure that the pod does not get evicted
- we bump the `dd` parameters to 1024G to ensure oom kills happen in larger instances
- fix a flake when the previous tests restart kubelet, we wait for it to be ready before running this test.

Since we are going to mark cgroupv1 as deprecated we need a solid green signal for the feature as we are still not going to delete the support for a while.

#### Which issue(s) this PR fixes:

Fixes #126009

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
we have a [few good runs](https://testgrid.k8s.io/presubmits-ec2#pull-kubernetes-node-e2e-containerd-serial-ec2-eks&width=20) under our belt!

image

**Review by tzneal — APPROVED** [review]
Ah, nice!

/lgtm

**Pull request merged**
