### PR TITLE
Automated cherry pick of #123077: kubeadm: better checks if the node is CP during "upgrade

### PR DESCRIPTION
**Pull request by neolit123**
Cherry pick of #123077 on release-1.29.

#123077: kubeadm: better checks if the node is CP during "upgrade

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
kubeadm: fix a bug where the --rootfs global flag does not work with "kubeadm upgrade node" for control plane nodes.
```

---
auto close
fixes https://github.com/kubernetes/kubeadm/issues/3007

### CODE REVIEW

**Review by SataQiu — COMMENTED** [review]
/lgtm

**Comment by saschagrunert** [comment]
Are there no CP's required for 1.27/1.26?

**Comment by neolit123** [comment]
> Are there no CP's required for 1.27/1.26?

nope.

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
