### PR TITLE
Remove ioutil from apimachinery

### PR DESCRIPTION
**Pull request by inosato**
Signed-off-by: inosato <si17_21@yahoo.co.jp>

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Remove ioutil from apimachinery.

#### Which issue(s) this PR fixes:

Fixes # NONE
Related to https://github.com/kubernetes/kubernetes/issues/100367

#### Special notes for your reviewer:

NONE

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by apelisse** [comment]
/lgtm
/approve

I have really no idea what the point of this is.

/assign @liggitt 
Since you were involved in the original issue.

**Comment by liggitt** [comment]
/unassign
/assign @dims

my thoughts are the same as on the [first issue](https://github.com/kubernetes/kubernetes/issues/100367#issuecomment-801966004)... I'm not sure this is worth the effort

**Comment by inosato** [comment]
This is what happened after I received your comment, go 1.19 is released.
`ioutil` is now clearly deprecated and may be removed in the future.
https://github.com/golang/go/blob/go1.19/src/io/ioutil/ioutil.go#L25
I think it's a higher priority than before.

**Comment by liggitt** [comment]
> ioutil is now clearly deprecated and may be removed in the future.

it will explicitly not be removed ("The io/ioutil package remains and will continue to work as before, but we encourage new code to use the new definit[io](https://go.dev/pkg/io/)ns in the io and [os](https://go.dev/pkg/os/) packages."), so there's no urgency or functional difference to using the new methods

**Pull request closed without merging**
