### PR TITLE
Revert kube2sky to use kubernetes-ro service 

### PR DESCRIPTION
**Pull request by vishh**
This is required until the master cert is updated to support kubernetes service VIP.

### CODE REVIEW

**Comment by lavalamp** [comment]
Can you just set Insecure = true?

**Comment by vishh** [comment]
@lavalamp: Insecure makes sense. Done.

**Comment by thockin** [comment]
LGTM.  Shippable was half-green, kicked.  Not that shippable will catch issues here.

**Comment by thockin** [comment]
If you're happy with the state of this, self-merge

**Comment by vishh** [comment]
@thockin: Ack. Self merging.

**Comment by thockin-cc** [comment]
Did you push a new container?

**Comment by ArtfulCoder** [comment]
Yes, Vishh did.
Are you seeing any issues ?

**Comment by thockin** [comment]
No issues, just asking

**Comment by vishh** [comment]
Yes i did Tim! :)

**Pull request merged**
