### PR TITLE
remove eviction-manager start return err

### PR DESCRIPTION
**Pull request by NickrenREN**
Start() function will never return err,we do not need the return value

### CODE REVIEW

**Comment by NickrenREN** [comment]
kindly ping @dchen1107  @yujuhong   Do you have time to help ask the k8s-bot to test and review ? Thanks a lot

**Comment by vishh** [comment]
@k8s-bot add to whitelist

**Comment by NickrenREN** [comment]
@k8s-bot unit test this

**Comment by NickrenREN** [comment]
@vishh  Could you ask k8s-bot to unit test again?  Thanks

**Comment by NickrenREN** [comment]
@vishh Could you ask k8s-bot to unit test again? Thanks
Jenkins unit/integration build failed because
client_test.go:295: Failed updating patchpod with patch type application/json-patch+json: jsonpatch remove operation does not apply: doc is missing path: /metadata/labels/foo

seems not related to the codes I modified. I rebase the codes

**Comment by spxtr** [comment]
@k8s-bot ok to test

**Comment by NickrenREN** [comment]
@vishh   @spxtr   Checks passed.  Do you have time to help with the review ? and readd the LGTM label. THanks

**Pull request merged**
