### PR TITLE
AWS: Refactor interfaces to take a single request arg

### PR DESCRIPTION
**Pull request by justinsb**
We're working towards adding logging & rate-limiting, and it is helpful
to have all the methods have the same approximate signature so we can
pass them to an 'interceptor'.

### CODE REVIEW

**Comment by justinsb** [comment]
Actually, I think i might have an easier way to intercept these calls.  This is still a good change, though no longer motivated by the same reasons.  Marking WIP while I complete this "chain of thought"

**Comment by justinsb** [comment]
Rebased; it's still a nice cleanup (IMO), although I was able to get logging working via a different approach (the AWS SDK has its own pipeline).

**Comment by davidopp** [comment]
LGTM

**Comment by davidopp** [comment]
@k8s-bot test this please

**Pull request merged**
