### PR TITLE
Fix: null jsonpath serialization

### PR DESCRIPTION
**Pull request by ls-2018**
#### What type of PR is this?

/kind bug
 
#### Which issue(s) this PR fixes: 
`When we extract a null value from a json string, the current code extracts an <nil>; The string. But it should be null, and this pr fixes the problem. All unit tests passed.
 `
  
#### Special notes for your reviewer:
@jiahuif

### CODE REVIEW

**Comment by apelisse** [comment]
Looks good to me, I'll let @jiahuif lgtm.

**Review by jiahuif — COMMENTED** [review]
/lgtm
cc @cici37

**Comment by ls-2018** [comment]
ok

**Pull request merged**
