### PR TITLE
Revert "Validate if service has duplicate targetPort"

### LINKED ISSUE #53526: upgrading to 1.8 broke Service backwards compatibility by not allowing the same target port multiple times
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/sig api
/sig network

**What happened**:

Prior to 1.8 it was possible to specify the same targetPort in the service definition multiple times. In 1.8, validation was added that prohibited this. 

**What you expected to happen**:
I expect backwards compatibility for GA resources, so having the same targetPort multiple times should be allowed. This is a valid use case IMO for target ports. If you take the example below, the load balancer terminates SSL, so that manifest allows the nginx pods to receive http on port 80 while the load balancer serves traffic on 80 & 443. 

**How to reproduce it (as minimally and precisely as possible)**:

```
kubectl apply -f - <<EOF 
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/oci-load-balancer-tls-secret: ssl-certificate-secret
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
EOF
```

**Anything else we need to know?**:

Original ticket for validation: https://github.com/kubernetes/kubernetes/issues/47222

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Services allow duplicate targetPort. This reverts commit ce54d9072bd637db5441a9c7b92c8d0eb0511629.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #53526

**Special notes for your reviewer**:
/cc @thockin @jhorwit2 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
Hold on this until we can discuss in #47222

**Comment by xiangpengzhao** [comment]
@thockin @jpbetz The reversion (cherry-picking) of this has finally been merged to 1.8. Can we push this forward to master ASAP? Thanks!

**Comment by jpbetz** [comment]
@xiangpengzhao If you want this on master, you need to submit a separate PR.  For future reference— typically we first submit fixes to master and then back port them to releases, which all can be done via a single PR.

**Comment by xiangpengzhao** [comment]
@jpbetz this PR is the parent of https://github.com/kubernetes/kubernetes/pull/55064. It's heading on to the master. I'm afraid that I'm not clear why I should create a new PR. Can you help explain a bit more? Thanks!

**Comment by jpbetz** [comment]
@xiangpengzhao My mistake. Yes, it looks like this PR should be merged. You'll just need approvals from the appropriate owners (not me).

**Comment by xiangpengzhao** [comment]
@jpbetz no worries :) Thanks!

**Comment by xiangpengzhao** [comment]
ping @thockin for approval :)

**Comment by rphillips** [comment]
is this going to be merged into 1.8 as well?

**Comment by xiangpengzhao** [comment]
@rphillips yeah it had been. It was cherry-picked to 1.8, then reverted, and reapplied, finally :) See https://github.com/kubernetes/kubernetes/issues/55064

**Comment by juliole** [comment]
I just hit this problem on 1.9.5 with the following service spec. Isn't it supposed to be resolved on 1.9? Thanks!
spec:
  clusterIP: None
  ports:
  - name: client
    protocol: TCP
    port: 2379
    targetPort: 2379
  - name: web
    protocol: TCP
    port: 2379
    targetPort: 2379

**Comment by caseydavenport** [comment]
@juliole are you sure the problem isn't that you have two identical ports with different names? The original issue was with two different ports resolving to the same targetPort - in your case you have two of the same port resolving to the same target port.

**Comment by juliole** [comment]
@caseydavenport I did not have any validation error on 1.7.4 with same spec. My case looks similar to https://github.com/kubernetes/kubernetes/issues/53949

**Comment by caseeker** [comment]
Having the same problem as what @juliole is describing in 1.9.6

**Comment by lnformer** [comment]
same issue here with kubernetes 1.10.4

**Comment by AmitMatsil** [comment]
we are having the same issue with 1.10.4

**Comment by caseydavenport** [comment]
> # * spec.ports[1].nodePort: Duplicate value: 30014

@lnformer I believe you have a different problem - you have two NodePorts with the same value, which isn't allowed.

**Comment by samirmajen** [comment]
This issue appears to have resurfaced again in 1.18 is this expected behaviour?

`ports:
    - port: 80
      name: http
      targetPort: 8080
    - port: 443
      name: https
      targetPort: 8080
`

duplicate entries for key [containerPort=8080,protocol="TCP"]

**Pull request merged**
