### PR TITLE
Revert "Move rand string func to util for reuse"

### PR DESCRIPTION
**Pull request by vishh**
Reverts GoogleCloudPlatform/kubernetes#9162

### CODE REVIEW

**Comment by mikedanese** [comment]
LGTM. If you wait 1 minute I can push a fix. Up to you.

**Comment by vishh** [comment]
@mikedanese: A fix is better. Saves time. I will close this PR then.

**Comment by vishh** [comment]
#11705 doesn't seem to get past testing. I will go ahead with this revert.

**Comment by mikedanese** [comment]
Still LGTM

**Pull request merged**
