### PR TITLE
[1.10] Automated cherry pick of #63946: Wait for pod deletion instead of termination

### LINKED ISSUE #63923: Failing Test : [sig-storage] Subpath [Volume type: emptyDir] should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow] failing in sig-release-master-upgrade
We are seeing multiple tests (for various volume types) failing to umount gracefully.

## Failing Jobs
* [sig-release-master-upgrade#gce-1.10-master-upgrade-master](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.10-master-upgrade-master)
* [sig-release-master-upgrade#gce-master-1.10-downgrade-cluster](https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-master-1.10-downgrade-cluster)

## Failing Tests
* [[sig-storage] Subpath [Volume type: emptyDir] should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1439#sig-storage-subpath-volume-type-emptydir-should-unmount-if-pod-is-gracefully-deleted-while-kubelet-is-down-disruptiveslow)
* [[sig-storage] Subpath [Volume type: nfsPVC] should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster/617#sig-storage-subpath-volume-type-nfspvc-should-unmount-if-pod-is-gracefully-deleted-while-kubelet-is-down-disruptiveslow)
* [[sig-storage] Subpath [Volume type: emptyDir] should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-master-new-downgrade-cluster/617#sig-storage-subpath-volume-type-emptydir-should-unmount-if-pod-is-gracefully-deleted-while-kubelet-is-down-disruptiveslow)

## Triage results
* https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=storage&job=ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new
* https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=storage&job=ci-kubernetes-e2e-gce-master-new-downgrade-cluster

/kind bug
/priority failing-test
/priority important-soon
/sig storage
/milestone v1.11
@kubernetes/sig-storage-bugs 

cc @jberkus @tpepper

/assign @saad-ali 

@saad-ali @msau42 we are seeing a couple of storage e2e tests failing in sig-release-master-upgrade jobs. Beta v1.11 cut is today. Can you please triage this as priority and let us know if we can resolve it as soon as possible?

### PR DESCRIPTION
**Pull request by msau42**
**What this PR does / why we need it**:
cherry pick of #63946: Wait for pod deletion instead of termination

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #63923

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by saad-ali — APPROVED** [review]

**Comment by jeffvance** [comment]
These files call `WaitForPodTerminated`:
```
test/e2e/common/pods.go
test/e2e/framework/volume_util.go
test/e2e/storage/flexvolume.go
```
Should there be a separate pr to evalute if the wait call should wait for pod deletion instead?

**Comment by msau42** [comment]
Yes I opened https://github.com/kubernetes/kubernetes/issues/63944 to handle the other calls.

**Comment by AishSundar** [comment]
@MaciekPytel since this looks like a CP candidate for 1.10?

**Comment by msau42** [comment]
I believe @MaciekPytel wanted to wait until the next 1.10 patch.

**Pull request merged**
