### PR TITLE
updated fluentd to 1.5.1, es & kibana to 7.1.1

### PR DESCRIPTION
**Pull request by monotek**
Signed-off-by: André Bauer <monotek23@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
/kind flake

**What this PR does / why we need it**:
* updates flunent to 1.5.1 and fluentd-elasticsearch plugin to 3.5.3 to be ES 7.x compatible
* updated elasticsearch to 7.1.1
* updates kibana to 7.1.1

**Which issue(s) this PR fixes**:

Fixes # https://github.com/kiwigrid/helm-charts/issues/116

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
updated fluentd to 1.5.1, elasticsearchs & kibana to 7.1.1
```

### CODE REVIEW

**Comment by coffeepac** [comment]
will give an lgtm after @monotek is able to push the images.  If desired by others I can push the images now and we can sort out image build permissions out of band but this seems like a good case to make sure I'm not the only person who can push new images.

**Comment by monotek** [comment]
I was able to push the image and its available now:
https://console.cloud.google.com/gcr/images/fluentd-elasticsearch/GLOBAL/fluentd?gcrImageListsize=30

**Comment by coffeepac** [comment]
@monotek can you update this PR to point to the quay.io locations?

**Comment by monotek** [comment]
@coffeepac done :-)

**Pull request merged**
