### PR TITLE
kube-apiserver in a pod.

### PR DESCRIPTION
**Pull request by ArtfulCoder**
#5011

### CODE REVIEW

**Comment by dchen1107** [comment]
e2e tests?

**Comment by ArtfulCoder** [comment]
Ran 35 of 39 Specs in 1151.749 seconds
SUCCESS! -- 35 Passed | 0 Failed | 0 Pending | 4 Skipped I0413 15:55:18.160851   23616 driver.go:117] All tests pass

**Comment by dchen1107** [comment]
Cool. Merging it ...

**Comment by justinsb** [comment]
FYI, this broke AWS, because the apiserver can't access /etc/aws.conf

```
F0414 16:10:20.848236       1 plugins.go:79] Couldn't open cloud provider configuration /etc/aws.conf: &os.PathError{Op:"open", Path:"/etc/aws.conf", Err:0x2}
```

I will fix...

**Comment by derekwaynecarr** [comment]
I thought this PR was reverted?

**Comment by dchen1107** [comment]
The previous attempt is reverted due to one mismount volume for apiserver. This is the second attempt. I am very sorry for breaking other cloud provider here. The problem is that we cannot validate the change on AWS at all. I raised this kind of issues in several meetings, but there is no solution so far. @justinsb and @derekwaynecarr Really thank you guys as our gate keeper for this. We are going to cc you two at the first place from now one. Thanks again!

**Comment by derekwaynecarr** [comment]
@dchen1107 - i looked to see if anything was broken, i just wanted to confirm that i was not crazy, and there is no PR or related PR that has been merged yet that has this?  in general, I am fine fixing issues, it's a good way for me to keep up with what is changing ;-)

**Comment by justinsb** [comment]
No worries on breaking AWS - I figure until we have a solution for sharing e2e test results that we'll always be breaking platforms that don't have published test results.

I'm playing around with the idea of aggregating test results... http://kubernetes-dashboard.meteor.com/  That is currently scraping an S3 bucket where I publish the AWS e2e results from Jenkins, and combining them with the scraped commitlog from github.  Lots of bugs, most importantly right now is that if the build is _completely_ broken it just doesn't appear!  Hopefully once #6821 merges!

**Comment by gogogocheng** [comment]
This broke azure with ubuntu, Because in azure, docker and kubelet do not run on master.

**Pull request merged**
