### PR TITLE
go.mod: github.com/moby/term v0.0.0-20210619224110-3f7ff695adc6

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/moby/term/compare/9d4ed1856297...3f7ff695adc6a35abc925370dd0a4dafb48ec64d

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>

#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by thaJeztah** [comment]
yay! looks like it passed now ✅

**Comment by AlexShu88** [comment]
@thaJeztah , I got the logs error:  error response from daemon: {"message":"invalid session token"},  it looks like its caused by this line of code as below, could you please please let me know where can find the daemon logs of "message":"invalid session token"? thank you
https://github.com/Mirantis/dhe-deploy/blob/012904c76e376f737778f4fbdbd26735e33a5fd6/gocode/vendor/github.com/docker/docker/client/version.go#L12

**Comment by thaJeztah** [comment]
@AlexShu88 is that related to this PR? (note that the source you linked to is probably from a private repository). Not sure where `invalid session token` originates from; perhaps from a registry or from the operating system? (`git grep` doesn't show that message in the docker or docker cli codebase at least).

**Comment by AlexShu88** [comment]
@thaJeztah ,yes, its related to private repo, thank you for confirming that its not originate from moby/moby, I did find its from mirantis/orca. thank you.

**Comment by aojea** [comment]
/lgtm

this is fixing an integer overflow based on the diff

https://github.com/moby/term/commit/3f7ff695adc6a35abc925370dd0a4dafb48ec64d

/assign @dims @liggitt

**Review by abdulmge — APPROVED** [review]

**Comment by thaJeztah** [comment]
> this is fixing an integer overflow based on the diff

For clarity; this was also worked around by updating the Ansiterm package in the local go.mod through https://github.com/kubernetes/kubernetes/pull/103010, but it shouldn't hurt to update the moby/term package to get the old Ansiterm dependency out of the dependency tree

**Comment by dims** [comment]
@thaJeztah this looks like the right thing to do, let's please update cadvisor and/or continerd as needed as well since someone may bump this back by mistake.

/approve
/lgtm

**Comment by thaJeztah** [comment]
> @thaJeztah this looks like the right thing to do, let's please update cadvisor and/or continerd as needed as well since someone may bump this back by mistake.
> 
> /approve /lgtm

@dims I opened https://github.com/google/cadvisor/pull/3034 for cAdvisor

**Pull request merged**
