### PR TITLE
Prevent virtual infinite loop in volume controller

### LINKED ISSUE #62571: Volume controller eventually pegs at 100% CPU when using NFS PVs and recycler
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

On a cluster with NFS PVs and a recycler pod, occasionally a recycle operation causes the volume controller to start using 100% CPU. It never seems to recover until the controller is restarted.

**What you expected to happen**:

Recycles should happen or the controller should handle any related errors gracefully.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a cluster with a NFS PV
2. Create a PVC and delete the PVC in a loop until you notice the volume controller CPU usage go to 100% and stay there.

**Anything else we need to know?**:

I believe I have tracked the problem down in `pkg/volume/util/recyclerclient`. In `WatchPod()`, if one of the two channels being watched (pod updates and events) is closed, the `for`/`select` loop turns into a tight infinite loop because the `select` immediately falls through due to the channel being closed.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-alpha.0.2507+a62a157c488385-dirty", GitCommit:"a62a157c4883852472dc0ad7b8fcb506a0095672", GitTreeState:"dirty", BuildDate:"2018-04-14T02:55:56Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-alpha.0.2507+a62a157c488385-dirty", GitCommit:"a62a157c4883852472dc0ad7b8fcb506a0095672", GitTreeState:"dirty", BuildDate:"2018-04-14T02:55:56Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by joelsmith**
**What this PR does / why we need it**:

In WatchPod(), if one of the two channels being watched (pod updates and events) is closed, the for/select loop turns into a tight infinite loop because the select immediately falls through due to the channel being closed.

This PR changes WatchPod() to Watch the two channels independently instead.

**Which issue(s) this PR fixes**:
Fixes #62571

**Release note**:
```release-note
Fix potential infinite loop that can occur when NFS PVs are recycled.

```

### CODE REVIEW

**Comment by joelsmith** [comment]
/sig storage
/kind bug
/assign joelsmith
@gnufied please take a look when you have a moment.
Thanks!

**Comment by gnufied** [comment]
@joelsmith I think it needs a `./hack/update-bazel.sh` run.

**Comment by joelsmith** [comment]
@gnufied thanks for the review. `hack/update-bazel.sh` doesn't make any changes, so I don't think that's the problem. I think we have a new flake and I've opened an issue #62601

**Pull request merged**
