### PR TITLE
Node e2e fix etcd compability issues across versions

### PR DESCRIPTION
**Pull request by pwittrock**

### CODE REVIEW

**Comment by pwittrock** [comment]
@k8s-bot test node e2e experimental

**Comment by pwittrock** [comment]
@k8s-bot test node e2e experimental

**Comment by timstclair** [comment]
LGTM

**Comment by timstclair** [comment]
It looks like this changed etcd to no longer be run with sudo, was that intentional?

@mtaufen - I think that might be the source of https://github.com/kubernetes/kubernetes/issues/26649. You can try making `/usr/local/bin/etcd` world executable.

/cc @dubstack

**Comment by timstclair** [comment]
Sorry - I misread this. Nevermind!!

**Pull request merged**
