### PR TITLE
Upgrade installed packages when building hyperkube to improve the security profile

### PR DESCRIPTION
**Pull request by aaronlevy**
Fixes: https://github.com/kubernetes/kubernetes/issues/25097

### CODE REVIEW

**Comment by roberthbailey** [comment]
ok to test

**Comment by roberthbailey** [comment]
@aaronlevy Would you like this change to have a release note?

**Comment by aaronlevy** [comment]
@roberthbailey I guess I'd defer to you on that. I'm fine with none, or PR title, or I can add more detail if you like.

Also, the test failure looks to be related to: https://github.com/kubernetes/kubernetes/issues/25153

**Comment by roberthbailey** [comment]
@k8s-bot test this issue: ##25153

**Comment by roberthbailey** [comment]
k8s-bot test this issue: #25153

**Comment by luxas** [comment]
LGTM for me too :)

**Pull request merged**
