### PR TITLE
remove unused code in pkg/apis/storage/v1beta1/

### PR DESCRIPTION
**Pull request by islinwb**
**What this PR does / why we need it**:
remove unused code in pkg/apis/storage/v1beta1/

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60681)

**Comment by islinwb** [comment]
@deads2k Thanks for reviewing. The test results show that "verify openapi-spec " failed. But I've run "hack/verify-openapi-spec.sh" without failure many times in my VM. Any ideas on this?

**Comment by deads2k** [comment]
> @deads2k Thanks for reviewing. The test results show that "verify openapi-spec " failed. But I've run "hack/verify-openapi-spec.sh" without failure many times in my VM. Any ideas on this?

try rebasing on master.  Looks like a version mismatch.

**Comment by islinwb** [comment]
@deads2k Tests passed. PTAL. Thanks :)

**Comment by deads2k** [comment]
/lgtm

this can wait until 1.11

**Comment by islinwb** [comment]
@deads2k Can we merge this into v1.11?

**Comment by dims** [comment]
It's way too late for v1.11 (only `priority-critical-urgent` items since RC1 is early next week)

**Comment by islinwb** [comment]
@deads2k PTAL. Thanks!

**Pull request closed without merging**
