### PR TITLE
scheduler_perf: use time.Ticker in throughput measurement

### LINKED ISSUE #94665: scheduler_perf: use time.Ticker in throughput measurement
https://github.com/kubernetes/kubernetes/blob/b56d0acaf5bead31bd17d3b88d4a167fcbac7866/test/integration/scheduler_perf/util.go#L244

https://golang.org/pkg/time/#Ticker

/sig scheduling
/sig testing
/assign

### PR DESCRIPTION
**Pull request by tangwz**
**What type of PR is this?**

/sig scheduling
/sig testing
/kind cleanup

**What this PR does / why we need it**:
use `time.Ticker` in throughput measurement.

**Which issue(s) this PR fixes**:

Fixes #94665

**Special notes for your reviewer**:
@adtac 

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by adtac** [comment]
Very well :)
/cc @alculquicondor to do the actual LGTM :)

**Comment by alculquicondor** [comment]
/ok-to-test

/approve

Although, note that this will cause merge conflicts with the benchmarks refactoring.

**Comment by chendave** [comment]
/lgtm

btw. other similar occurrences can be found in this file, 
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler_test.go

**Comment by tangwz** [comment]
@alculquicondor PTAL.

Thanks.

**Comment by alculquicondor** [comment]
I prefer #93252 gets merged first.

**Comment by tangwz** [comment]
@alculquicondor @chendave I rebased. This need two new lgtm.

**Pull request merged**
