### PR TITLE
backport registry migration to 1.23

### PR DESCRIPTION
**Pull request by xmcqueen**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This continues the backporting of the image registry migration.  This PR goes through `build/dependencies.yaml` and migrates the registry for paths that are in these directories:

- build
- cluster
- test/e2e
- staging

This is per some discussion with @liggitt , though I am not certain I got the directions right.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by xmcqueen** [comment]
rebased

**Review by mrunalp — APPROVED** [review]

**Comment by SergeyKanzhelev** [comment]
@BenTheElder @dims do you have powers to approve this before asking release managers to take it for 1.23?

**Comment by dims** [comment]
let's see @SergeyKanzhelev (probably not!)

/approve
/lgtm

**Comment by liggitt** [comment]
I don't really have context on the files being changed here... at first glance, ~half of them don't seem to be files it matters to change (like the kubectl testdata files or build images I don't think anyone is still building from, like the etcd image in the release-1.23 branch)

I'll defer to other reviewers on this one

/unassign

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Comment by BenTheElder** [comment]
/assign @eddiezane @apelisse 

for [staging/src/k8s.io/kubectl/OWNERS](https://github.com/kubernetes/kubernetes/blob/release-1.23/staging/src/k8s.io/kubectl/OWNERS)

**Pull request closed without merging**
