### PR TITLE
Include static docker binary in kubekins-test image

### PR DESCRIPTION
**Pull request by ixdy**
Fixes kubernetes/test-infra/issues/47.

I haven't pushed this image yet, so I expect CI to fail for now.

### CODE REVIEW

**Comment by ixdy** [comment]
cc @fejta @spxtr

**Comment by mikedanese** [comment]
@k8s-bot ok to test, issue #27797

**Comment by spxtr** [comment]
It might be out of the scope of this PR, but the separate `apt-get install` calls need to be in the same `RUN` command as the `apt-get update`.

**Comment by ixdy** [comment]
what do you mean by "need"?

in any case, I can change it.

**Comment by spxtr** [comment]
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/ under "apt-get"

**Comment by ixdy** [comment]
interesting. fixed.

**Comment by spxtr** [comment]
This looks fine to me. Mind building/pushing the image so we can see what Jenkins thinks?

**Comment by ixdy** [comment]
@k8s-bot test this, issue #IGNORE

**Comment by ixdy** [comment]
Updated to add `dnsutils` for #219.

**Comment by spxtr** [comment]
LGTM. Have you pushed the version with dnsutils?

**Comment by ixdy** [comment]
yes, I have.

**Comment by ixdy** [comment]
@k8s-bot node e2e test this, issue #27668

**Comment by ixdy** [comment]
Rebased for changes to hack/jenkins/dockerized-e2e-runner.sh. There were no changes to test-image, so I'm not repushing the image.

**Comment by ixdy** [comment]
@k8s-bot node e2e test this please

I think this is #27498. Though that test should be deleted on its name alone:
`Container Runtime Conformance Test container runtime conformance blackbox test when running a container with a new image [It] should be able to pull image from gcr.io `

**Comment by ixdy** [comment]
@k8s-bot node e2e test this please, issue #IGNORE

**Comment by ixdy** [comment]
node e2e is frustrating.

@k8s-bot node e2e test this please, issue #IGNORE

**Pull request merged**
