### PR TITLE
make storm examples use gcr image registry

### LINKED ISSUE #38047: [k8s.io] [Feature:Example] [k8s.io] Storm should create and stop Zookeeper, Nimbus and Storm worker servers {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-examples/697/

Failed: [k8s.io] [Feature:Example] [k8s.io] Storm should create and stop Zookeeper, Nimbus and Storm worker servers {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:376
Expected error:
    <*errors.errorString | 0xc42065a040>: {
        s: "Timeout while waiting for pods with labels \"name=storm-worker\" to be running",
    }
    Timeout while waiting for pods with labels "name=storm-worker" to be running
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:360
```

Previous issues for this test: #29225 #33106

### PR DESCRIPTION
**Pull request by rootfs**
**What this PR does / why we need it**:
e2e example test occasionally failed due to image pull timeout.
This fix move storm examples from docker registry to gcr.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #38047

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rootfs** [comment]
@mattf

**Comment by rootfs** [comment]
Need to push the images to gcr.io/google-examples first.

**Comment by zmerlynn** [comment]
Get an LGTM, then cc @jeffmendoza

**Comment by jeffmendoza** [comment]
LMK when this is ready.

**Comment by rootfs** [comment]
@k8s-bot bazel test this

**Comment by mattf** [comment]
@rootfs this essentially swaps hub.docker.io for gcr.io under the assumption that gcr.io will be more reliable?

**Comment by rootfs** [comment]
@mattf yes that's the idea. Since e2e runs on gce, it is more likely gcr is accessible at the time of testing.

**Comment by rootfs** [comment]
@mattf ping

**Comment by mattf** [comment]
e2e failures look unrelated. lgtm.

**Comment by rootfs** [comment]
thank you @mattf 
/assign @zmerlynn

**Pull request closed without merging**
