### PR TITLE
Revert 20202

### LINKED ISSUE #22128: integration flake: casandra failure
test-cmd.sh failed with the following:

    12:01:47 service "cassandra" created
    12:01:47 
    12:01:47 FAIL!
    12:01:47 Get all -l'app=cassandra' {{range.items}}{{range .metadata.labels}}{{.}}:{{end}}{{end}}
    12:01:47   Expected: cassandra:cassandra:cassandra:
    12:01:47   Got:      cassandra:cassandra:cassandra:cassandra:
    12:01:47 (B
    12:01:47 1535 ./hack/test-cmd.sh

https://storage.googleapis.com/kubernetes-jenkins/logs/kubernetes-test-go/8954/build-log.txt

### PR DESCRIPTION
**Pull request by caesarxuchao**
Exactly the same as #21175, which was reverted by the oncall in order to fix #22128, but it's actually not the culprit.

cc @yujuhong @lavalamp

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Adding the lgtm label myself since this PR is exactly the same as #21175.

**Comment by bprashanth** [comment]
@caesarxuchao what's the deletion timestamp on the last object that comes down the watch after a graceful delete? (i.e I delete, the timestamp is set to 10s later, 10s later the "real" delete happens, all watchers see this real delete with an object -- what is the deletion timestamp on this object?). Looks like it's now 0. 

I would prefer if you didn't clobber the actual deletion timestamp. Either that, or you'll have to make some modifications to the rc.

**Comment by caesarxuchao** [comment]
@bprashanth, IIRC, the `deletion timestamp` should be whatever value set during the initial graceful deletion. Why would you think it's 0?

**Comment by bprashanth** [comment]
I haven't followed the lifecycle of this pr and it's reverts, but it looked like you were applying an update of 0 when the kubelet does it's second delet call, before actually popping the object from etcd. so the last state of the object when it's delete has a 0 deletion timestamp. Am I wrong?

**Comment by caesarxuchao** [comment]
@bprashanth I think you meant to say the `DeletionGracePeriod`, not the deletion timestamp, is updated to 0? If so, then yes, the last state of the object would be having a `DeletionGracePeriod`=0.

Could you point me to the affected code in rc?

**Comment by caesarxuchao** [comment]
@k8s-bot e2e test this, issue: #20916

**Comment by bprashanth** [comment]
No I mean the DeletionTimestamp, some downstream components will do unexpected things if it goes nil -> non nil-> nil, including the RCs (https://github.com/kubernetes/kubernetes/blob/75c1dcaacd1dae7a5a5081d6f4b5e85c64e7b935/contrib/mesos/pkg/scheduler/components/controller/controller.go#L80, https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replicaset/replica_set.go#L332). If you're not clobbering it feel free to re-apply lgtm, and apologies for the confusion.

**Comment by caesarxuchao** [comment]
The last update of `DeletionTimeStamp` should be this line: https://github.com/kubernetes/kubernetes/blob/master/pkg/api/rest/delete.go#L66, and it's not nil, so it shouldn't mess up controllers. Reapplying the lgtm.

**Comment by bprashanth** [comment]
@caesarxuchao your issue is https://github.com/kubernetes/kubernetes/issues/21803

**Comment by caesarxuchao** [comment]
Thanks @bprashanth.

@k8s-bot e2e test this, issue #21803

**Pull request merged**
