### PR TITLE
fix(test): delete unused unused var or const

### PR DESCRIPTION
**Pull request by hwdef**
**What type of PR is this?**
> /kind cleanup

**What this PR does / why we need it**:

delete unused var or const in test folder

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
/kind cleanup
/priority backlog
/lgtm

Looks good, thanks

**Comment by hwdef** [comment]
/assign @thockin 
Could you please add an approved label ?
Thank you!

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
