### PR TITLE
vSphere kube-up: Wait for cbr0 configuration to complete before setting up routes.

### LINKED ISSUE #34248: vSphere Deployment container communication broken
**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.): vSphere, "message": "no endpoints available for service \"kube-dns\"", kube-dns, etc -- similar issues include: https://github.com/kubernetes/kubernetes/issues/24407 however it's not quite the same

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Kubernetes version** (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"283137936a498aed572ee22af6774b6fb6e9fd94", GitTreeState:"clean", BuildDate:"2016-07-01T19:26:38Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"clean", BuildDate:"2016-09-26T18:10:32Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: vSphere
- **OS** (e.g. from /etc/os-release): Using provided vmdk
- **Kernel** (e.g. `uname -a`): `Linux kubernetes-minion-4 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64 GNU/Linux` and `Linux kubernetes-master 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64 GNU/Linux`
- **Install tools**: GOVC + the `cluster/vsphere/config-default.sh` script

**What happened**: Our environment utilizes the RFC1918 10.0.0.0/8 block, so I edited `cluster/vsphere/config-default.sh` to utilize an address space we are not using. This is my current configuration:
```
NODE_IP_RANGES="192.168.0.0/17"
MASTER_IP_RANGE="${MASTER_IP_RANGE:-192.168.128.0/17}"
SERVICE_CLUSTER_IP_RANGE="192.168.120.0/21"  # formerly PORTAL_NET
DNS_SERVER_IP="192.168.120.120"
```
After the deployment is finished, I am able to login to the dashboard via the URL provided via `kubectl cluster-info`, however, when I check the DNS server I see:
```
> curl -sk https://admin:password@10.248.30.36/api/v1/proxy/namespaces/kube-system/services/kube-dns
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"kube-dns\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
```
When I list services, I see:
```
> kubectl get svc --namespace=kube-system
NAME                   CLUSTER-IP        EXTERNAL-IP   PORT(S)         AGE
kube-dns               192.168.120.120   <none>        53/UDP,53/TCP   50m
kubernetes-dashboard   192.168.127.194   <none>        80/TCP          50m
```
When I start a container and try to ping kube-dns, I am unable to:
```
> kubectl exec -ti testing-network-2429464084-8jauq /bin/bash
root@testing-network-2429464084-8jauq:/# ping 192.168.120.120
PING 192.168.120.120 (192.168.120.120) 56(84) bytes of data.
^C
--- 192.168.120.120 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 4032ms
```

I can ping external IP addresses:
```
# ping 216.58.192.142
PING 216.58.192.142 (216.58.192.142) 56(84) bytes of data.
64 bytes from 216.58.192.142: icmp_seq=1 ttl=50 time=52.0 ms
64 bytes from 216.58.192.142: icmp_seq=2 ttl=50 time=51.9 ms
^C
--- 216.58.192.142 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 51.968/51.999/52.031/0.230 ms
```

Here's the configuration on each minion and the master:
```
Master - IP: 10.248.30.36
kube@kubernetes-master:~$ ip ro sh
default via 10.248.30.1 dev eth0
10.248.30.0/24 dev eth0  proto kernel  scope link  src 10.248.30.36
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
172.18.0.0/16 via 10.248.30.39 dev eth0
192.168.0.0/24 via 10.248.30.38 dev eth0
192.168.1.0/24 via 10.248.30.40 dev eth0
192.168.2.0/24 via 10.248.30.37 dev eth0
192.168.128.0/17 dev cbr0  proto kernel  scope link  src 192.168.128.1


Minion 1 - IP: 10.248.30.38
kube@kubernetes-minion-1:~$ ip ro sh
default via 10.248.30.1 dev eth0
10.248.30.0/24 dev eth0  proto kernel  scope link  src 10.248.30.38
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
172.18.0.0/16 via 10.248.30.39 dev eth0
192.168.0.0/24 dev cbr0  proto kernel  scope link  src 192.168.0.1
192.168.1.0/24 via 10.248.30.40 dev eth0
192.168.2.0/24 via 10.248.30.37 dev eth0


Minion 2 - IP: 10.248.30.40
kube@kubernetes-minion-2:~$ ip ro sh
default via 10.248.30.1 dev eth0
10.248.30.0/24 dev eth0  proto kernel  scope link  src 10.248.30.40
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
172.18.0.0/16 via 10.248.30.39 dev eth0
192.168.0.0/24 via 10.248.30.38 dev eth0
192.168.1.0/24 dev cbr0  proto kernel  scope link  src 192.168.1.1
192.168.2.0/24 via 10.248.30.37 dev eth0

Minion 2 - IP: 10.248.30.37
kube@kubernetes-minion-3:~$ ip ro sh
default via 10.248.30.1 dev eth0
10.248.30.0/24 dev eth0  proto kernel  scope link  src 10.248.30.37
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
172.18.0.0/16 via 10.248.30.39 dev eth0
192.168.0.0/24 via 10.248.30.38 dev eth0
192.168.1.0/24 via 10.248.30.40 dev eth0
192.168.2.0/24 dev cbr0  proto kernel  scope link  src 192.168.2.1


Minion 4 - IP: 10.248.30.39
kube@kubernetes-minion-4:~$ ip ro sh
default via 10.248.30.1 dev eth0
10.248.30.0/24 dev eth0  proto kernel  scope link  src 10.248.30.39
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
192.168.0.0/24 via 10.248.30.38 dev eth0
192.168.1.0/24 via 10.248.30.40 dev eth0
192.168.2.0/24 via 10.248.30.37 dev eth0
192.168.3.0/24 dev cbr0  proto kernel  scope link  src 192.168.3.1
```

**What you expected to happen**: I expect containers can reach ping eachother.

**How to reproduce it** (as minimally and precisely as possible): I've reproduced this problem using both 172.16.0.0/16 addresses as well as the 192.168.0.0/16 addresses.

**Anything else do we need to know**: I followed the documentation here: http://kubernetes.io/docs/getting-started-guides/vsphere/ and the only change I made was to the network configuration.

### PR DESCRIPTION
**Pull request by kerneltime**
``` release-note
vSphere kube-up: Wait for cbr0 configuration to complete before setting up routes.
```

**What this PR does / why we need it**:
Fixes routing setup when deploying via kube-up.sh on vSphere.
Remove optimizations for salt status check till flakyness of install with optimization
is addressed.

**Which issue this PR fixes**  
fixes #34248, #31310 

**Special notes for your reviewer**:
Ref PR with a similar fix https://github.com/kubernetes/kubernetes/issues/31672

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35232)

### CODE REVIEW

**Comment by kerneltime** [comment]
We need this cherry picked into release-1.4 as well

**Comment by eparis** [comment]
@kubernetes/sig-network

**Comment by kerneltime** [comment]
@eparis to clarify this does not change any of the networking code within kubernetes and only changes the kube-up.sh script for deploying on top of vSphere.

**Comment by imkin** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[cluster/vsphere/util.sh, line 331 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35232#-KUZ39yso9vlQSH6g_hh:-KUZ39yso9vlQSH6g_hi:bdt8urg) ([raw file](https://github.com/kubernetes/kubernetes/blob/4ff1b894871990170c96fd5e14ec5ec3589feaf8/cluster/vsphere/util.sh#L331)):*
> ```Shell
> 
>     network=""
>     top2_octets_final=$(echo $NODE_IP_RANGES | awk -F "." '{ print $1 "." $2 }') # Assume that a 24 bit mask per node
> ```

We could identify the mask from network we setup in config-default.sh

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35232)*

**Comment by kerneltime** [comment]
@imkin This is quick and the mainly a reliable way to insure that the cbr0 interface has been configured correctly before setting up the routes based on the information read from cbr0. The limitation is that the the mask possible is limited to 255 IPs per node. Without this fix overall networking is broken. As discussed we can look at improvements, for now we need to make sure that this fix gets into 1.4.4 release.

**Comment by imkin** [comment]
If the code will fail predictably lets document it clearly.  both for the developer and the user. Please add comments to the config-default and config-common that  sing \16 or higher prefixes are stable.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35232#-:-KUZMnW375bgHYKBynoN:bc3adfx)*

**Comment by kerneltime** [comment]
Will do. Adding documentation for the limitation.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[cluster/vsphere/util.sh, line 331 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35232#-KUZ39yso9vlQSH6g_hh:-KUZfH6ID-Tized4zeQJ:b-773uyl) ([raw file](https://github.com/kubernetes/kubernetes/blob/4ff1b894871990170c96fd5e14ec5ec3589feaf8/cluster/vsphere/util.sh#L331)):*
<details><summary><i>Previously, imkin (Dhawal Yogesh Bhanushali) wrote…</i></summary>
> We could identify the mask from network we setup in config-default.sh
</details>
This is quick and mainly a reliable way to insure that the cbr0 interface has been configured.
For now we will document the limitation and move to an alternate scheme for detecting initialization of network information.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35232#-:-KUZfg-EOTr3mumxLMEy:b-i760tt)*

**Comment by imkin** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35232#-:-KUZhC8khuyRLOSJFAr0:bnfp4nl)*

**Comment by imkin** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35232)*

**Comment by kerneltime** [comment]
cc @abrarshivani @AlainRoy @luomiao

**Comment by kerneltime** [comment]
Let me know if this PR can be automatically cherry picked to release-1.4 else I can file a new PR.

**Comment by eparis** [comment]
it will not be automaticaly picked in any way. You will have to follow the cherry-pick process. See `Individual Cherry Picks` https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md#how-do-cherrypick-candidates-make-it-to-the-release-branch

Also be sure the cc @ jessfraz on your pick

After this merges. I'll also point out that it looks like you are just doing what the flannel host gateway does. Why not use that? A lot of other providers use flannel...

**Comment by eparis** [comment]
@k8s-bot test this

**Comment by eparis** [comment]
adding `retest-not-required` as the tests are going to run vShpere code anyway.

**Comment by kerneltime** [comment]
@eparis can you adjust the release note label?

**Comment by kerneltime** [comment]
@eparis yup agreed. Right now the goal is to make sure that we get release branch fixed and then look into improving the kube-up deployment. There are a few other things we want to do with the kube-up script to reduce time taken to install in addition to looking into flannel. The bigger question is will kube-up be there in 1.5? We are also working on supporting vSphere within kube-anywhere.

**Pull request merged**
