### PR TITLE
WIP: Reintroduce graceful deletion with e2e passing

### PR DESCRIPTION
**Pull request by smarterclayton**
Revert the revert of #9165 which was a revert of a revert of #8641.

### CODE REVIEW

**Comment by bgrant0607** [comment]
cc @yujuhong

**Comment by smarterclayton** [comment]
I have some more e2e tests, this is still WIP until I've nailed them all.

On Wed, Aug 19, 2015 at 1:27 PM, Brian Grant <notifications@github.com>
wrote:

> cc @yujuhong <https://github.com/yujuhong>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/12931#issuecomment-132704833>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bgrant0607** [comment]
cc @gmarek re. node controller

**Comment by smarterclayton** [comment]
First two commits are in other pulls #12926

**Comment by yujuhong** [comment]
One failure: 
```
• Failure [31.586 seconds]
Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:634
  Kubectl describe
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:327
    should check if kubectl describe prints relevant information for rc and pods [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:326

    Aug 19 14:55:11.633: Error running &{/jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace@3/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://104.154.53.168 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace@3/.kube/config describe node pull-e2e-1-minion-sdi5] []  <nil>  format mismatch: DecimalSI vs. BinarySI
     [] <nil> 0xc2081e8840 exit status 1 <nil> true [0xc208050950 0xc208050998 0xc2080509d0] [0xc208050950 0xc208050998 0xc2080509d0] [0xc208050988 0xc2080509c8] [0x682c30 0x682c30] 0xc2082b6480}:
    Command stdout:
    
    stderr:
    format mismatch: DecimalSI vs. BinarySI
    
    

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/util.go:979
```

**Comment by smarterclayton** [comment]
It's a flake, I opened a defect.  I'm still running e2e tests locally, I
want to verify that I've got something clean.  I am also considering
breaking the revert into digestible chunks and only turn on graceful at the
end because the reverts are too much pain for reviewers.

On Aug 19, 2015, at 7:41 PM, Yu-Ju Hong <notifications@github.com> wrote:

One failure:

• Failure [31.586 seconds]
Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:634
  Kubectl describe
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:327
    should check if kubectl describe prints relevant information for
rc and pods [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:326

    Aug 19 14:55:11.633: Error running
&{/jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace@3/kubernetes/platforms/linux/amd64/kubectl
[kubectl --server=https://104.154.53.168
--kubeconfig=/var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace@3/.kube/config
describe node pull-e2e-1-minion-sdi5] []  <nil>  format mismatch:
DecimalSI vs. BinarySI
     [] <nil> 0xc2081e8840 exit status 1 <nil> true [0xc208050950
0xc208050998 0xc2080509d0] [0xc208050950 0xc208050998 0xc2080509d0]
[0xc208050988 0xc2080509c8] [0x682c30 0x682c30] 0xc2082b6480}:
    Command stdout:

    stderr:
    format mismatch: DecimalSI vs. BinarySI



    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/util.go:979

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/12931#issuecomment-132827170>
.

**Comment by smarterclayton** [comment]
I'm closing this in favor of incremental commits so we can land the non-user impacting code distinct from the actual enabling code and pain caused by rebasing reverts.  See links from #9165.  Reviews appreciated.

**Pull request closed without merging**
