### PR TITLE
Automated cherry pick of #62505: update godeps to use latest pflag

### PR DESCRIPTION
**Pull request by dims**
Cherry pick of #62505 on release-1.10.

#62505: update godeps to use latest pflag

```release-note
Show help for deprecated Kubelet flags
```

### CODE REVIEW

**Comment by mtaufen** [comment]
I updated your initial PR comment to fix the release note.
Do you want the PR comment to just say the name of the first commit, or the name of the PR? The latter is "Show help for deprecated Kubelet flags".

**Comment by dims** [comment]
`Show help for deprecated Kubelet flags` sounds good @mtaufen

**Comment by dims** [comment]
Looks like there is no interest. dropping it.

**Comment by liggitt** [comment]
apologies, this fell off the radar. this is still important, imo
/lgtm

**Comment by liggitt** [comment]
/assign @thockin
needs a high-level approver since it touches vendor and godeps. tagging the master PR approver

/assign @MaciekPytel 
for 1.10 approval

**Comment by MaciekPytel** [comment]
@mtaufen Can you copy release note to #62505? For automated cherry-picks the release tooling takes release note from parent PR and so this won't show in release notes for 1.10.4.

**Pull request merged**
