### PR TITLE
Close the used modules file

### PR DESCRIPTION
**Pull request by wzshiming**
It looks like this file forgot to close

#### What type of PR is this?
/kind bug
/sig network

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
good catch, it seems the ipvs job failed but I don't think is related
/ test pull-kubernetes-e2e-gci-gce-ipvs 
/assign @uablrek @andrewsykim

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-gci-gce-ipvs
LGTM

**Review by andrewsykim — COMMENTED** [review]
/approve

Thanks

**Pull request merged**
