### PR TITLE
Generate kubelet server cert with cluster CA

### LINKED ISSUE #1223: kubeadm generate kubelet certs with master(s) CA
## Is this a BUG REPORT or FEATURE REQUEST?

/kind bug

Opening the `kubeadm` side for [this issue](https://github.com/kubernetes-incubator/metrics-server/issues/130) on the metrics-server

## Versions
```
$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:43:08Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Kubernetes version** (use `kubectl version`):

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

- **Cloud provider or hardware configuration**:
Any
- **OS** (e.g. from /etc/os-release):
Any
- **Kernel** (e.g. `uname -a`):
```
$ uname -a
Linux ip-172-31-1-118 4.15.0-1023-aws #23-Ubuntu SMP Mon Sep 24 16:31:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- **Others**:

## What happened?

kubeadm creates certs under `/var/lib/kubelet/pki/kubelet.*` signed with a different CA from the one under `/etc/kubernetes/pki/ca.pem`

## What you expected to happen?

As a result some apps like the metrics-server cannot collect stats from a secured kubelet because the kubelet has certs signed by a different ca from the K8s master(s)

Error sample:

```
E1108 23:49:32.090084       1 manager.go:102] unable to fully collect metrics: [unable to fully scrape metrics from source kubelet_summary:ip-x-x-x-x: unable to fetch metrics from Kubelet ip-x-x-x-x (ip-x-x-x-x): Get https://ip-x-x-x-x:10250/stats/summary/: x509: certificate signed by unknown authority, unable to fully scrape metrics from source kubelet_summary:ip-x-x-x-x: unable to fetch metrics from Kubelet ip-x-x-x-x (ip-x-x-x-x): Get https://ip-x-x-x-x:10250/stats/summary/: x509: certificate is valid for x.x.x.x not ip-x-x-x-x]
```

## How to reproduce it (as minimally and precisely as possible)?

Install the [metrics-server](https://github.com/kubernetes-incubator/metrics-server/) on run:

$ kubectl -n kube-system logs <metrics-server-pod>

## Anything else we need to know?

Some more background [here](https://stackoverflow.com/questions/53212149/x509-certificate-signed-by-unknown-authority-kubeadm/53218524#53218524)

There also steps in there that I followed to fix the issue.

### PR DESCRIPTION
**Pull request by stgleb**
/kind bug

Add kubelet-server phase to join and init commands.
Generate kubelet key and certificate signing request,
create, approve this certificate signing request and download
certificate. 

Implements [kubeadm design proposal](https://github.com/kubernetes/community/pull/602/)
Fixes [kubeadm issue](https://github.com/kubernetes/kubeadm/issues/1223)

### CODE REVIEW

**Comment by anarchistHH1983** [comment]
Sorry. I'm a newbie

**Review by neolit123 — COMMENTED** [review]
/hold

@stgleb the kubeadm config is beta and we should batch multiple changes per release.
due to the kubeadm team being overbooked it was (mostly) decided to not bump v1beta1 to v1beta2 this cycle(?) this change is not batched with other changes and it might not make it in 1.14.

also:
- please add a release note instead of `NONE`
- and link to the original kubeadm issue - `Fixes #1223` seems unrelated.

thanks.
@kubernetes/sig-cluster-lifecycle-pr-reviews 
/assign @timothysc @detiber

**Comment by stgleb** [comment]
@neolit123 Thank you, I am not expecting this to be in 1.14

**Comment by anarchistHH1983** [comment]
Release

**Comment by anarchistHH1983** [comment]
Wip

**Comment by anarchistHH1983** [comment]
Fixes

**Review by luxas — COMMENTED** [review]
Does this mean requiring the CA key to be present on every node?
I'd be _very_ sceptical of doing that from a security perspective

**Comment by stgleb** [comment]
@luxas yes, do you think there might be an option to grant server certs to kubelet like client certs when TLS bootstrap?

**Comment by rosti** [comment]
@stgleb thank you for this!

Unfortunately there are several points that need clearing here:

1. As @luxas mentioned, pre-copying certs and keys on nodes, that are going to be provisioned is not a good idea from security stand point. I'd say uploading them in encrypted secrets on the cluster is the way to go.
There is a similar ongoing effort for the control plane certs & keys when joining HA nodes. Currently users are copying these manually on nodes to be joined as HA, but that effort aims at eliminating this.
Here are a few links on this:
https://github.com/kubernetes/kubeadm/issues/1373
https://github.com/kubernetes/kubeadm/issues/1374
https://github.com/kubernetes/kubeadm/issues/1200

I think, that it's best to reuse ideas and possibly code from that effort. Doing so will result in a far smaller and more focused patch and a more secure and easy to use end result.
Please, reach out to @fabriziopandini to discuss this.

2. Changing anything in the config requires version bumps, which means new config, conversion and tests to support old configs, etc. This requires a full cycle to be done and is quite laborious. Thus the intent is to pile up proposed changes and add then in a new config version, when there are enough good propositions.
I don't think, that you need config format changes to implement this feature, but if you do, please, make sure you file up an `api-change` issue in `k/kubeadm` for this so we can track config changes.

3. Keep the PR focused. There are a few changes, that are unnecessary at this point, but touch a bunch of code.
Most notably the `Configuration` interface. Not that I don't plan on introducing something similar in the future to better replace `InitConfiguration` (mis)use here and there and introduce caching and on-demand fetching of config info from the cluster. But that's another effort in on itself and requires quite some time to get properly done.

4. This is a feature with possible security implications. Let's start by discussing this, how should be implemented, etc. (possibly on some of the kubeadm office hours meetings). We may have to write up a KEP for this and then proceed with implementing this.

Hope, that this does not sound discouraging. The community is always open to new ideas (including this one), but let's first figure out the best path of doing this and then proceed with the implementation.

**Comment by stgleb** [comment]
@rosti Than you for you comment. I agree that my implementation is far from to be perfect.
Currently I am thinking about using csr approve mechanism for gettings approved server certs for kubelet from api server. What do you think about it?

**Comment by rosti** [comment]
@stgleb sounds reasonable.
We need to know in advance the implementation and workflow details and also have folks from SIG Auth review the proposal.
Why don't we start with an email thread in both SIG Cluster Lifecycle and SIG Auth groups?

**Comment by kfox1111** [comment]
I kind of hit this issue the other day. Is there a reason it isn't rolled up in the bootstrap process? The client bootstrap already creates a signed client cert. why not create a server cert at the same time?

**Comment by mark-casey** [comment]
> kfox1111 
> I kind of hit this issue the other day. Is there a reason it isn't rolled up in the bootstrap process? The client bootstrap already creates a signed client cert. why not create a server cert at the same time?

@liggitt just came across this and was recalling your comment from https://github.com/kubernetes/kubeadm/issues/118#issuecomment-420356566. IIRC... for cert renewal, absent a bootstrap token, client certs would be self-authn/authz for renewal and serving certs aren't?

Coming across this again though, I wonder for non-bootstrap scenarios could a kubelet just approve it's own new serving cert CSR by acting as a node/admin with its client cert? Just had the thought so may be half-baked, but it's all happening in the same process right and if the client cert isn't valid such that it could approve the serving CSR isn't the node in bad shape anyway?

**Comment by neolit123** [comment]
@stgleb 
FYI the design proposal is not approved and also there is ongoing discussion in the kubeadm issue whether we should move away from the kubelet self-signed serving certificate and how.

it might be a good idea to hold on commits, because this PR can end up being rejected.
(also we cannot modify v1beta1 at this point as already mentioned).

**Comment by stgleb** [comment]
@neolit123 May I keep it here as a possible solution? I am basically finished.

**Comment by neolit123** [comment]
> @neolit123 May I keep it here as a possible solution? I am basically finished.

sure.

**Pull request closed without merging**
