### PR TITLE
WIP: v1API: Introduce image format for docker image.

### PR DESCRIPTION
**Pull request by yifan-gu**
Try to give some momentum to https://github.com/GoogleCloudPlatform/kubernetes/issues/8702

Need to add tests for validation, defaults, conversion, and update a bunch of codes...

/cc @bgrant0607 @smarterclayton @philips @vmarmol @dchen1107 @jonboulle @bakins

### CODE REVIEW

**Comment by saad-ali** [comment]
Thank you very much for the pull request - we sincerely appreciate the work that goes into sending us a change.

We are currently in a feature-freeze and general code slush as we work toward our 1.0 release.  Our initial triage indicates that this is a non-critical change at this time, so we'd like to leave it open and revisit it after 1.0.  We expect the freeze to wrap up in early to mid July.

If you feel that this triage is incorrect, please respond and let us know why.  We're currently accepting changes that meet any of the following criteria:
1. Changes [directly related to v1.0 issues](https://github.com/GoogleCloudPlatform/kubernetes/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.0)
2. Changes [addressing P0 bugs](https://github.com/GoogleCloudPlatform/kubernetes/issues?q=is%3Aopen+is%3Aissue+label%3Apriority%2FP0)
3. Changes to supported platforms to bring them up to par with the primary development platforms
4. Docs, user experience, and test related fixes

**Comment by bgrant0607** [comment]
I'm sorry. This didn't make the cut. Please see the discussion on #8702.

**Comment by wojtek-t** [comment]
@yifan-gu - are you going to proceed with this PR or can we close it?

**Comment by bgrant0607** [comment]
This requires more thought before we do it. Let's discuss in #8702.

**Pull request closed without merging**
