### PR TITLE
Unrevert CPU manager wiring and `none` policy

### PR DESCRIPTION
**Pull request by ConnorDoyle**
**What this PR does / why we need it**:

Unreverts #51357. Fixes two problems introduced in the first version of the patch set:

- nil deref that broke kubemark.
- wrong signature for Start() in windows container manager that broke cross build.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
i would love to know why the original pr did not find the nil pointer in the testing.

**Comment by smarterclayton** [comment]
/approve

Simple fix and previous approval

**Comment by yujuhong** [comment]
Need to fix the cross-build as well #51815

**Comment by ConnorDoyle** [comment]
Just saw that @yujuhong -- will add a commit for that as well.

**Comment by ConnorDoyle** [comment]
Updated to fix #51815

**Comment by ConnorDoyle** [comment]
@derekwaynecarr and @smarterclayton -- rebased on top of master following merge of the revert PR, needs another lgtm & approve pass please

**Comment by ConnorDoyle** [comment]
Need this test as well...

/test pull-kubernetes-cross

**Comment by ConnorDoyle** [comment]
@derekwaynecarr please add to `v1.8` milestone

**Comment by dchen1107** [comment]
only reviewed the last commit. 

/lgtm

**Comment by ConnorDoyle** [comment]
/test pull-kubernetes-cross

...to verify the windows container manager fix

**Comment by derekwaynecarr** [comment]
waiting for cross build to confirm

**Comment by ConnorDoyle** [comment]
Closing in favor of #51180 (because the point of breaking these up was for ease-of-review, but now it's causing submit-queue headaches.)

**Pull request closed without merging**
