### PR TITLE
Cleanup: fix golint failures in pkg/kubectl

### PR DESCRIPTION
**Pull request by ESWZY**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fix golint failures for package `pkg/kubectl`.

**Which issue(s) this PR fixes**:

Ref: #68026 [Fix golint failures](https://github.com/kubernetes/kubernetes/issues/68026)

Break up: #93222 [Cleanup: fix linting failures](https://github.com/kubernetes/kubernetes/pull/93222)

**Special notes for your reviewer**:

Change some type name and empty import to avoid golint failures.

Thanks for your review! If you have any reply, I will respond as soon as possible!

### CODE REVIEW

**Comment by ESWZY** [comment]
/assign @pwittrock

Thx!

**Comment by BenTheElder** [comment]
/uncc
I don't own kubectl

**Comment by liggitt** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/93228/pull-kubernetes-node-e2e/1285176914083844096 flake is #93210

**Pull request closed without merging**
