### PR TITLE
Implement external provisioning proposal

### PR DESCRIPTION
**Pull request by jsafrane**
In other words, add "provisioned-by" annotation to all PVCs that should be provisioned dynamically.

Most of the changes are actually in tests.

@kubernetes/sig-storage

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35957)

### CODE REVIEW

**Comment by childsb** [comment]
So a couple things i'd like to see with this PR..  I'd like tests that show the positive API flow works (a claim with values set as they would be from an external provisioner and show that the binder handles this case correctly)-- which i believe is already in this PR.  But I'd also like to see tests showing the binder handling cases where the values aren't set properly and the binder doesn't explode.

**Comment by jsafrane** [comment]
This is pretty embarrassing, I found only one single spot not covered by unit tests and I found a bug there. When two provisioners (regardless if external or internal) provision two PVs for single PVC. Kubernetes is supposed to detect it and let one of them to be deleted. And it did not.

I added a fix + unit test to this PR, both for internal and external provisioning.

You can see current test coverage at http://people.redhat.com/jsafrane/volume/coverage/2016-11-03/combined-coverage.html#file1 , IMO there is not much to add.

**Comment by jsafrane** [comment]
I'll write an e2e test for this when problems with NFS client settles down... https://github.com/kubernetes/kubernetes/issues/36170

**Comment by childsb** [comment]
ok thanks jan

**Comment by saad-ali** [comment]
Release-czar approved post-code freeze merge--This was LGTMed and in the merge-queue at code freeze time for 1.5. Leaving 1.5 milestone to let it gets merged after code freeze.

**Pull request merged**
