### PR TITLE
[Discussion][WIP] Dedup the code in schedule_one.go

### LINKED ISSUE #103853: Dedup the code in scheduler.go#scheduleOne()
In scheduler.go#scheduleOne(), some logic was written duplicately to recover failures in different phases. This looks a bit ugly. We should tease out the logic in scheduleOne() and eventually de-duplicated those logic.

The duplicated code includes:

- fwk.RunReservePluginsUnreserve()
- sched.SchedulerCache.ForgetPod()
- sched.recordSchedulingFailure()
- ...

/kind cleanup
/sig scheduling

### PR DESCRIPTION
**Pull request by AxeZhan**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The error handling for scheduler is currently split in 2 places:
`MakeDefaultErrorFunc` in `pkg/scheduler/scheduler.go` which is only called by 
`handleSchedulingFailure` in `pkg/scheduler/schedule_one.go`

what this PR does:
* Merge the 2 functions in a single place, I put them in a new file `pkg/scheduler/error_handler.go`
* Defer the call in 2 places: once in the scheduling routine and once in the binding routine.

#### Which issue(s) this PR fixes:

Fixes #103853 

#### Special notes for your reviewer:
I'm not sure whether this is a good implementation.
I'm also not sure if some of the variables are named properly.
So I think I need some help, and we should have some discussion about this refactoring here.
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kerthcet** [comment]
Well, it's hard to review since you move the whole function to another file, we can't tell the difference easily. Maybe we can separate this into two commits:
1) refactor the implements as advised
2) move them o the right place

**Comment by kidddddddddddddddddddddd** [comment]
> Well, it's hard to review since you move the whole function to another file, we can't tell the difference easily. Maybe we can separate this into two commits:

Thanks for your suggestion. I'll do it, maybe you can review it after a few days.❤️

**Comment by rymond686** [comment]
@kidddddddddddddddddddddd I'm new here, may I make some change base on your job if possible?

**Comment by rymond686** [comment]
> > @kidddddddddddddddddddddd I'm new here, may I make some change base on your job if possible?
> 
> You are welcome to work on this :)



> > @kidddddddddddddddddddddd I'm new here, may I make some change base on your job if possible?
> 
> You are welcome to work on this :)
Wouldn't it be better to put the following code before the call to `sched.SchedulePod`
```
	var (
		failPodInfo        *framework.QueuedPodInfo
		failErr            error
		failReason         string
		failNominatingInfo *framework.NominatingInfo
		moveAction         MoveAction
	)

	defer func() {
		sched.handleSchedulingFailure(fwk, failPodInfo, failErr, failReason, failNominatingInfo, moveAction)
	}()
```

**Pull request closed without merging**
