### PR TITLE
[Federation][e2e] Add wait for namespaces to appear in federated cluster

### PR DESCRIPTION
**Pull request by shashidharatd**
Some federation e2e tests are failing because the namespace (created for every test case) does not seem to appear in one (or more) of federated clusters.
This may be a timing issue, so introducing a wait until the namespace is created in federated clusters.

cc @madhusudancs, @nikhiljindal, @kubernetes/sig-federation-bugs

### CODE REVIEW

**Comment by csbell** [comment]
@k8s-bot federation gce e2e test this

**Comment by madhusudancs** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[test/e2e_federation/util.go, line 58 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42584#-Ke_WAJDn1eC2TWwCvPU:-Ke_WAJDn1eC2TWwCvPV:b-k5kn52) ([raw file](https://github.com/kubernetes/kubernetes/blob/47a4da30ee7fea081dadd8c5d59df7035244d5ee/test/e2e_federation/util.go#L58)):*
> ```Go
> 
> const (
> 	federatedNamespaceTimeout = 60 * time.Second
> ```

1 minute is too low IMO :)

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42584)*

**Comment by madhusudancs** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42584)*

**Comment by shashidharatd** [comment]
@madhusudancs, handled comment, PTAL. Thanks

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/e2e_federation/util.go, line 58 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42584#-Ke_WAJDn1eC2TWwCvPU:-Kea90NHQq-oKgEC2eNk:bkx5lam) ([raw file](https://github.com/kubernetes/kubernetes/blob/47a4da30ee7fea081dadd8c5d59df7035244d5ee/test/e2e_federation/util.go#L58)):*
<details><summary><i>Previously, madhusudancs (Madhusudan.C.S) wrote…</i></summary><blockquote>

1 minute is too low IMO :)
</blockquote></details>

okie. increased the timeout to 5 minutes now.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42584#-:-Kea99iJB3v7gv70YXq2:b-rkm1so)*

**Comment by madhusudancs** [comment]
/lgtm
/approve

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42584#-:-KeaM4WtjvnFzBSoszOx:b6yv7yi)*

**Comment by madhusudancs** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42584)*

**Comment by madhusudancs** [comment]
@k8s-bot non-cri node e2e test this
@k8s-bot cvm gce e2e test this
@k8s-bot non-cri e2e test this

**Pull request merged**
