### PR TITLE
Refactor apimachinery.GroupMeta

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

1. fix TODOs

1. remove redundant ` InterfacesFor` func pointer

1. rewrite `AddVersionInterfaces`

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@yliaog rebased

**Comment by deads2k** [comment]
I think I'd rather see https://github.com/kubernetes/kubernetes/pull/63203

**Pull request closed without merging**
