### PR TITLE
Priority queue

### LINKED ISSUE #28928: Prioritizing Pods in Scheduling
Hey all, I’m looking to extend the default scheduler with a capability that I don’t think exists yet. I wanted to ask here just in case I'm duplicating work.

My workload:
A few services/forever pods, but a large number of terminating pods (not yet using the jobs object, but that’s the general idea). These jobs can run anywhere from 5 min to 3 days, and we pretty much always have more “requests” of the cluster than capacity (this is by design). We currently have a fairly hacky way of setting up a priority queue, where certain jobs are submitted to the cluster before others. The details of this hacky system are not that relevant for this discussion.

The need:
It is my task to rewrite this system to be more robust. While my use case in prod will be a more complicated and dynamic, a more or less FIFO queue is sufficient to discuss the scheduler code in question (as long as the priority of a job can be changed later, such as through an annotation on the pod).

Wait, doesn't the scheduler already do this?
Currently the default scheduler effectively does a for loop over all pods, which somewhat randomly selects pods to schedule in order. If it can't schedule a pod, it will move onto the next one. I don't really want to touch the logic of determining which _node_ to schedule the pod on; I just want to modify which _pods_ are selected to be scheduled. For my needs, the scheduler doesn't have to be lightning fast as long as it's reasonable.

Gotchas
Large request pods: It's possible that small pods can get blocked behind large pods in the queue. I have a straightforward way to overcome this, but that adds more complexity to this issue and I'd rather wait until later.

relevant issues:
Multiple schedulers (wip)
https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/multiple-schedulers.md
Dispatcher feature request
https://github.com/kubernetes/kubernetes/pull/17430

None of the above has been implemented, and frankly I'm ok with just extending my existing scheduler (and running all pods through this mechanism) until multiple schedulers are supported.

relevant issue labels: area/scheduling

relevant code:
I believe all I have to do is implement this function differently:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/scheduler.go#L66
Is that it or am I missing something? I am also unclear of where that actually is calculated... 

Can anyone give me a few pointers/suggestions and I'll code it up?
Once I code it up, where should I contribute this back to? I'm sure I'm not the only one trying to schedule a ton of jobs on a cluster.

### PR DESCRIPTION
**Pull request by astropuffin**
DONOTMERGE

**What this PR does / why we need it**:
To address https://github.com/kubernetes/kubernetes/issues/28928 . In short, I need to implement a priority queue for Pods. How the priority of the pod itself is calculated is business logic, and in general outside of the scope of this PR. However, to give an idea of the requirement, the priority will take into account how long the pod has been pending, the expected duration of the job, and the value of the job itself (in dollars). Thus, it needs to be recalculated frequently.

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #28928

**Special notes for your reviewer**:
Do not merge this PR. It is merely a sample implementation and is in no way viable for production. See the linked issue above for discussion.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31809)

### CODE REVIEW

**Comment by davidopp** [comment]
ok to test

**Comment by davidopp** [comment]
Do we have a priority queue implementation anywhere else in Kubernetes? I'm not sure, but you might want to check, in which case you could maybe reuse some of the code.

I think we would need to have a discussion about how the scheduler queue priority would be specified in the API. I guess we could make it a pod annotation. As you say there are some performance issues to consider; it's probably better to keep all the pending pods in a priority queue and just insert new pending pods in the right place rather than re-evaluating each pod after failed scheduling (also remove the pod when it gets scheduled, of course). There is also some overlap with ongoing work on equivalence classes/caching.

cc/ @wojtek-t

**Comment by wojtek-t** [comment]
>
Do we have a priority queue implementation anywhere else in Kubernetes? I'm not sure, but you might want to check, in which case you could maybe reuse some of the code.

I'm not aware of any.

>
I think we would need to have a discussion about how the scheduler queue priority would be specified in the API. I guess we could make it a pod annotation.

@davidopp I don't understand this comment. Unless I'm missing something, I think the goal here is to use priority queue for re-enqueing a pod if it wasn't successfully scheduled, for decision when its next try to schedule will be. That said, I think it's not really a feature of pod, but it's more like a feature of scheduled. So i think that this (if at all) should be a parameter/flags/part of config data/whatever else of the scheduler itself. What I am missing?

**Comment by davidopp** [comment]
> I don't understand this comment. 

In the first comment in the issue you said "How the priority of the pod itself is calculated is business logic, and in general outside of the scope of this PR. However, to give an idea of the requirement, the priority will take into account how long the pod has been pending, the expected duration of the job, and the value of the job itself (in dollars)." I'm just saying we need to figure out how this priority will be associated with the pod. Presumably it is part of the pod spec. We could do it as an annotation on the pod.

**Comment by wojtek-t** [comment]
OK - sorry. I should have ready everything before. That makes sense to me now.

**Comment by kargakis** [comment]
cc: @deads2k

**Comment by deads2k** [comment]
Switching the scheduler to use our workqueue infrastructure like the controllers and then implementing a priority queuing mechanism there may have more general utility.  Scheduling a pod faster helps, but only if the RS controller has created pods for you.

**Comment by astropuffin** [comment]
Just jumping back on this now. Will rebase and update. I've actually been using this very much non-ideal implementation in prod for months now. It works reasonably well for a mid-size cluster (50 nodes).

**Comment by deads2k** [comment]
> Just jumping back on this now. Will rebase and update. I've actually been using this very much non-ideal implementation in prod for months now. It works reasonably well for a small/mid-size cluster (50 nodes). The bottleneck has actually been the prioritizer (business logic program that updates the priorities), not the scheduler. Kudos to all the work folks have done on optimizing the scheduler framework!

I think previous comments like https://github.com/kubernetes/kubernetes/pull/31809#issuecomment-258120618 still stand.  Will you be addressing that too?

The scheduler is currently a black sheep when compared against every controller and admission plugin in the rest of the code base.  Fixing something here will not provide any general utility to the vast majority of the project and will make future coherence harder to achieve.  That matters because affects future maintenance costs if there are different, slightly incompatible concepts across the codebase.

**Comment by timothysc** [comment]
I'm not a fan of putting business logic into the caching layer from the reflector.  That data will always be pop'd and can/should be evaluated then.

**Comment by astropuffin** [comment]
@deads2k re: [comment](https://github.com/kubernetes/kubernetes/pull/31809#issuecomment-258120618)
I am 100% for putting in the effort to do it the way consensus decides. My ultimate goal is to get this upstreamed so that I'm not running on a fork. I'll have to look deeper into the code to fully understand what you are referencing though. I will reach out for help in slack when I refactor for a cluster upgrade (likely in the next couple weeks).

As far as speed is concerned, the scheduler is already 3+ orders of magnitude faster than I actually require, but I understand that can be a major requirement for larger clusters. The nature of a priority queue will inherently be slower than a non-priority approach, but hopefully not too much slower.

**Comment by wanghaoran1988** [comment]
I am not like priority queue,committed pod should have enough resource to schedule within certain time, [cluster capacity](https://github.com/kubernetes-incubator/cluster-capacity) should be a good way to let you know how many pods you can create before you submit a pod.

**Comment by doprdele** [comment]
Any news on this?

**Comment by timothysc** [comment]
There is a proposal in flight to add priority in 1.7 but the other bits on preemption won't land in this cycle.

**Comment by doprdele** [comment]
Thanks. I'm not really as interested in preemption but priorities would be great. We're trying to determine whether or not we can live without HTCondor as kubernetes provides a much easier way to accomplish our goals wrt job submissions. When do you think 1.7 will be released ?

On Tue, May 16, 2017 at 19:31 "Timothy St. Clair"

<
mailto:
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

There is a proposal in flight to add priority in 1.7 but the other bits on preemption won't land in this cycle.

—

You are receiving this because you commented.

Reply to this email directly,
https://github.com/kubernetes/kubernetes/pull/31809#issuecomment-301943407
, or

**Comment by timothysc** [comment]
June-ish  .

**Comment by astropuffin** [comment]
I rebased my private fork to 1.6.4, but a much more robust version of this is in flight by the scheduling sig. I'm making due with my fork in the meantime, but I'm closing out this PR.

The pod spec has been updated in master:
https://github.com/kubernetes/kubernetes/blob/11b5956f7a37d61e5b264b461adf6b563a0c7b44/staging/src/k8s.io/api/core/v1/types.go#L2529
Having the priority be a int (with the service level sugar to set it on pod creation) exactly fits my needs. However, the controllers for it have yet to be merged, and I'm not sure what that will look like. There will probably be some needed tweaks. Ideally I can disable preemption while still using a priority scheduler. Either way, this PR has served it's purpose as a working example.

Thanks @davidopp for all your help on this!

**Pull request closed without merging**
