### PR TITLE
kubectl: Fix vendored dependency

### LINKED ISSUE #925: vbom.ml has gone
**What happened**:

$ go get k8s.io/kubectl@v0.19.0
go: k8s.io/kubernetes@v1.19.0 requires
	k8s.io/kubectl@v0.0.0 requires
	vbom.ml/util@v0.0.0-20160121211510-db5cfe13f5cc: unrecognized import path "vbom.ml/util": https fetch: Get "https://vbom.ml/util?go-get=1": dial tcp: lookup vbom.ml: No address associated with hostname

**What you expected to happen**:

The import should have been replaced with the non-vanity name as per 

https://github.com/fvbommel/util/commit/c69461e88a3651040fa9fe17c444462f587a751a

https://github.com/fvbommel/util

**How to reproduce it (as minimally and precisely as possible)**:
As above.

### PR DESCRIPTION
**Pull request by eddiezane**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

kubectl currently depends on `vbom.ml/util` but the author of this dependency is removing the vanity url and having users import via GitHub path.

This PR changes the vendored dependency of `vbom.ml/util` to `github.com/fvbommel/sortorder`. Note that `github.com/fvbommel/util` exists but the developer has broken `sortorder` out into its own package which is what kubectl actually used.

https://github.com/fvbommel/util/issues/5
https://github.com/fvbommel/util/issues/6

**Which issue(s) this PR fixes**

Fixes https://github.com/kubernetes/kubectl/issues/925

**Special notes for your reviewer**:

I followed the guide [here](https://github.com/kubernetes/community/blob/9258fa171f569a33b62a07239c10bce137598527/contributors/devel/sig-architecture/vendor.md) on updating vendored deps.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by eddiezane** [comment]
@liggitt does this need to be back ported?

The [original issue](https://github.com/kubernetes/kubectl/issues/925) is for someone running `go get k8s.io/kubectl@v0.19.0`.

**Comment by liggitt** [comment]
> @liggitt does this need to be back ported?

I'm on the fence. It's low-risk, so it's probably fine, but changing dependencies isn't something we typically do on release branches.

> The [original issue](https://github.com/kubernetes/kubectl/issues/925) is for someone running `go get k8s.io/kubectl@v0.19.0`.

I was actually able to run `go get k8s.io/kubectl@v0.19.0` successfully locally... the golang proxy seems to still have the module available. Their issue seemed to be related to requiring `k8s.io/kubernetes`:

```
go: k8s.io/kubernetes@v1.19.0 requires
k8s.io/kubectl@v0.0.0 requires
vbom.ml/util@v0.0.0-20160121211510-db5cfe13f5cc
...
```

**Comment by eddiezane** [comment]
That's fair.

I also wasn't able to reproduce it locally but I was when I ran it in a Docker container. I just assumed it was locally cached.

I guess we can address if it gets reported more.

**Pull request merged**
