### PR TITLE
Remove the kube-discovery binary from the tree

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:

kube-discovery was a temporary solution to implementing proposal: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/bootstrap-discovery.md

However, this functionality is now gonna be implemented in the core for v1.6 and will fully replace kube-discovery:
 - https://github.com/kubernetes/kubernetes/pull/36101 
 - https://github.com/kubernetes/kubernetes/pull/41281
 - https://github.com/kubernetes/kubernetes/pull/41417

So due to that `kube-discovery` isn't used in any v1.6 code, it should be removed.
The image `gcr.io/google_containers/kube-discovery-${ARCH}:1.0` should and will continue to exist so kubeadm <= v1.5 continues to work.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Remove cmd/kube-discovery from the tree since it's not necessary anymore
```
@jbeda @dgoodwin @mikedanese @dmmcquay @lukemarsden @errordeveloper @pires

### CODE REVIEW

**Comment by luxas** [comment]
cc @ixdy @thockin

**Review by pires — APPROVED** [review]
Gotta love PRs that just delete stuff! 👏 

/lgtm

**Comment by luxas** [comment]
Thanks! Would be great to get this fully approved, thanks @eparis for stepping in!

However, marking `do-not-merge` until https://github.com/kubernetes/kubernetes/pull/41417 is merged and I see all tests are passing (i.e. I didn't forgot to remove it in some place)

**Comment by jbeda** [comment]
/lgtm
/approve
:party_parrot:

**Comment by calebamiles** [comment]
@k8s-bot non-cri e2e test this

**Comment by luxas** [comment]
https://github.com/kubernetes/kubernetes/pull/41417 merged, this is unblocked :+1:

**Comment by luxas** [comment]
@k8s-bot node e2e test this

**Comment by luxas** [comment]
@k8s-bot node e2e test this

**Pull request merged**
