### PR TITLE
Propose adding quinton-hoole to federation/OWNERS

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by nikhiljindal** [comment]
oh sorry for missing this.

/lgtm

**Comment by nikhiljindal** [comment]
Looks like you need to resolve some CLA issues?

**Comment by nikhiljindal** [comment]
BTW, there is another copy of this in `test/e2e_federation`.
Please add yourself to that as well.

**Comment by quinton-hoole** [comment]
Yay! 

"Welcome! You have been automatically assigned membership in CNCF - Huawei Technologies Inc. and are authorized to contribute code to this project."

Lets see if CLA-bot works now.

**Comment by nikhiljindal** [comment]
All looks good now.
/approve

**Pull request merged**
