### PR TITLE
Fix gce localssd pv tests

### LINKED ISSUE #68308: Failing test: [sig-storage] PersistentVolumes-local [Volume type: gce-localssd-scsi-fs] [Serial] Set fsGroup for local volume should not set different fsGroups for two pods simultaneously
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-storage-bugs 

**What happened**:
Since 8/31, these tests have started flaking, and then started failing consistently.

https://k8s-testgrid.appspot.com/sig-storage#gce-serial

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/4046

/assign

### PR DESCRIPTION
**Pull request by msau42**
**What this PR does / why we need it**:
When running local PV tests against GCE local SSD, it directly uses the disk so doesn't need to create a tmp dir like the other test formats.  Fsgroup tests do not create test-file so don't error on cleanup if the file doesn't exist.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #68308

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by saad-ali — APPROVED** [review]
/lgtm
/approve
/milestone v1.12

**Comment by tpepper** [comment]
Does this need cherry picked back to 1.11?

Still have upgrade failures with this symptom, eg:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-parallel/4779

**Comment by msau42** [comment]
@tpepper no, the localssd tests are not failing in the upgrade suite

**Pull request merged**
