### PR TITLE
fix pleg TestRelisting

### PR DESCRIPTION
**Pull request by xiaoanyunfei**
**What type of PR is this?**

 /kind bug

**What this PR does / why we need it**:

 `TestRelisting` doesn't get event from chan in the second relist

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/sig node

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/assign @yujuhong @vishh 

Good catch :)

**Comment by dims** [comment]
@xiaoanyunfei can you please contact the CNCF helpdesk to sort out the CLA situation? https://github.com/kubernetes/community/blob/master/CLA.md#setting-up-the-cncf-cla-check

**Comment by xiaoanyunfei** [comment]
> @xiaoanyunfei can you please contact the CNCF helpdesk to sort out the CLA situation? https://github.com/kubernetes/community/blob/master/CLA.md#setting-up-the-cncf-cla-check

Sorry, it's my fault, I removed my old username

**Comment by derekwaynecarr** [comment]
/retest

thanks again for improving the test.

/approve
/lgtm

**Pull request merged**
