### PR TITLE
test/e2e/framework: use restricted policy by default, default existing tests to privileged

### PR DESCRIPTION
**Pull request by s-urbaniak**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

https://github.com/kubernetes/kubernetes/pull/106454 introduced the possibility to configure pod security level for e2e tests. This change:

1. sets `restricted` pod security level by default for new e2e tests
2. sets `privileged` pod security level for existing e2e tests so we don't risk breakage

/sig auth
/assign @deads2k @liggitt 

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
I see three framework creations that aren't setting an explicit level:

```
test/e2e_node/eviction_test.go:	f := framework.NewDefaultFramework("image-gc-eviction-test")
test/e2e/cloud/gcp/node/gpu.go:	f := framework.NewDefaultFramework("gpu-upgrade")
test/e2e/apps/disruption.go:		anotherFramework := framework.NewDefaultFramework("disruption-2")
```

**Review by neolit123 — COMMENTED** [review]
this change is very noisy, as is.

~have you considered having `NamespacePodSecurityEnforceLevel` to be defaulted to `admissionapi.LevelPrivileged` in `NewDefaultFramework()`, which can be overriden post the `NewDefaultFramework()` invocation?~

~the function name implies that something "default" is created.~

**Comment by neolit123** [comment]
NVM, it's restricted by default and privileged as an override.

i guess the noise here is due to:
> so we don't risk breakage

this leaves the possibility for old tests to _never_ be switched to restricted, unless TODOs are left.

**Comment by liggitt** [comment]
> i think it's just better to only add the override to tests that actually break, instead of all of them.

we tried this and it is almost impossible to have confidence pre-merge we're not breaking anything. This is an intermediate step and the intent is to 1) make sure new tests have to make a choice or get restricted by default, 2) be sure we don't break any existing tests, 3) gradually remove the privileged overrides as individual tests are shown to work with more restricted permissions.

**Comment by liggitt** [comment]
> this leaves the possibility for old tests to never be switched to restricted, unless TODOs are left. 

this represents the current default state, so it's not worse than where we are today. some tests require privileged access, so will intentionally not drop this. The work to burn this down will continue as we get this feature to GA

**Comment by neolit123** [comment]
> we tried this and it is almost impossible to have confidence pre-merge we're not breaking anything. 

oh, well. i assumed that a test pod either needs the privileged NS or not and test logs would have made it apparent.

i can see this diff being the safer option.

> The work to burn this down will continue as we get this feature to GA

ideally test owners (SIGs) should help with that, i guess.
perhaps an umbrella issue can ask for help-per-package for the GA.

**Comment by liggitt** [comment]
> test logs would have made it apparent.

of the tests that run, sure. 6900+ of the 7300 e2e tests defined don't run in presubmits.

**Comment by s-urbaniak** [comment]
```
test/e2e_node/eviction_test.go:	f := framework.NewDefaultFramework("image-gc-eviction-test")
test/e2e/cloud/gcp/node/gpu.go:	f := framework.NewDefaultFramework("gpu-upgrade")
test/e2e/apps/disruption.go:		anotherFramework := framework.NewDefaultFramework("disruption-2")
```
thank you, Fixed.

@neolit123: @liggitt describes it all very well. We have no possibility to run all presubmit tests.

What I can do is add a `// TODO: check if the privileged pod security level is actually needed.` to all e2e tests modified here. However, creating an issue for each seems a lot of overhead, the set of changes is big.

**Comment by liggitt** [comment]
The 4 failures in pull-kubernetes-e2e-aks-engine-windows-containerd passed in the kind job, so the API-level pod policy is working properly for those

/milestone v1.24
Test-only change improving coverage of existing code

**Comment by jyotimahapatra** [comment]
@s-urbaniak 👋 1.24 bug triage checking in. The test freeze in at UTC 01:00 Thursday(Approximately 1 day remaining). Could we please merge this in by the test freeze time.

**Comment by s-urbaniak** [comment]
@jyotimahapatra @liggitt sure thing, anything I can help with? it seems the failures are unrelated 🤔

**Comment by liggitt** [comment]
(failures aren't due to this PR... jobs are flaking, different tests are failing each time, and ~50%+ of runs are passing)

**Pull request merged**
