### PR TITLE
Automated cherry pick of #49498 #49328

### PR DESCRIPTION
**Pull request by luxas**
Cherry pick of #49498 #49328 on release-1.7.

#49498: kubeadm: Make sure --config can be mixed with --skip-* flags
#49328: kubeadm: don't customize etcd selinux label

### CODE REVIEW

**Comment by wojtek-t** [comment]
@luxas - what has changed?

**Comment by luxas** [comment]
@wojtek-t No functionality change, but I fixed up a small styling nit in https://github.com/kubernetes/kubernetes/pull/49498 based on the review.
Functionally it's 100% the same, but updated this cherrypick to have the same commits in both branches since I had to fix that nit.

Ok with you?

**Pull request merged**
