### PR TITLE
[WIP][TEST} debug kubeproxy iptables lock

### PR DESCRIPTION
**Pull request by aojea**

### CODE REVIEW

**Comment by aojea** [comment]
ok, one interesting failure here 
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/92811/pull-kubernetes-conformance-kind-ga-only-parallel/1279878461086765057

```
1/5208 Tests Failed. | expand_less
-- | --
[sig-network] Services should have session affinity timeout work for NodePort service [LinuxOnly] [Conformance] expand_less4m59stest/e2e/framework/framework.go:597 Jul  5 21:40:03.634: Unexpected error:     <*errors.errorString \| 0xc0005e6f50>: {         s: "service is not reachable within 2m0s timeout on endpoint 172.18.0.2:31750 over TCP protocol",     }     service is not reachable within 2m0s timeout on endpoint 172.18.0.2:31750 over TCP protocol occurred test/e2e/network/service.go:3313 | [sig-network] Services should have session affinity timeout work for NodePort service [LinuxOnly] [Conformance] expand_less | 4m59s | test/e2e/framework/framework.go:597 Jul  5 21:40:03.634: Unexpected error:     <*errors.errorString \| 0xc0005e6f50>: {         s: "service is not reachable within 2m0s timeout on endpoint 172.18.0.2:31750 over TCP protocol",     }     service is not reachable within 2m0s timeout on endpoint 172.18.0.2:31750 over TCP protocol occurred test/e2e/network/service.go:3313
[sig-network] Services should have session affinity timeout work for NodePort service [LinuxOnly] [Conformance] expand_less | 4m59s
test/e2e/framework/framework.go:597 Jul  5 21:40:03.634: Unexpected error:     <*errors.errorString \| 0xc0005e6f50>: {         s: "service is not reachable within 2m0s timeout on endpoint 172.18.0.2:31750 over TCP protocol",     }     service is not reachable within 2m0s timeout on endpoint 172.18.0.2:31750 over TCP protocol occurred test/e2e/network/service.go:3313

```

problem is kube-proxy does not install the nodeport rules, instead is rejecting the traffic to the nodeport

```
2020-07-05T21:40:11.472894763Z stderr F I0705 21:40:11.469510       1 proxier.go:1680] Opened local port "nodePort for services-1776/affinity-nodeport-timeout" (:31750/tcp)
2020-07-05T21:40:11.4729044Z stderr F I0705 21:40:11.469527       1 traffic.go:91] [DetectLocalByCIDR (10.244.0.0/16)] Jump Not Local: [-A KUBE-SERVICES -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp -p tcp -d 10.96.0.10/32 --dport 53 ! -s 10.244.0.0/16 -j KUBE-MARK-MASQ]
2020-07-05T21:40:11.472937524Z stderr F I0705 21:40:11.469553       1 traffic.go:91] [DetectLocalByCIDR (10.244.0.0/16)] Jump Not Local: [-A KUBE-SERVICES -m comment --comment "kube-system/kube-dns:metrics cluster IP" -m tcp -p tcp -d 10.96.0.10/32 --dport 9153 ! -s 10.244.0.0/16 -j KUBE-MARK-MASQ]
2020-07-05T21:40:11.472944435Z stderr F I0705 21:40:11.469579       1 traffic.go:91] [DetectLocalByCIDR (10.244.0.0/16)] Jump Not Local: [-A KUBE-SERVICES -m comment --comment "default/kubernetes:https cluster IP" -m tcp -p tcp -d 10.96.0.1/32 --dport 443 ! -s 10.244.0.0/16 -j KUBE-MARK-MASQ]
2020-07-05T21:40:11.472953475Z stderr F I0705 21:40:11.469754       1 proxier.go:1567] Restoring iptables rules: *filter
2020-07-05T21:40:11.472978675Z stderr F :KUBE-SERVICES - [0:0]
2020-07-05T21:40:11.472984563Z stderr F :KUBE-EXTERNAL-SERVICES - [0:0]
2020-07-05T21:40:11.472990554Z stderr F :KUBE-FORWARD - [0:0]
2020-07-05T21:40:11.472996638Z stderr F -A KUBE-SERVICES -m comment --comment "services-1776/affinity-nodeport-timeout has no endpoints" -m tcp -p tcp -d 10.110.216.198/32 --dport 80 -j REJECT
2020-07-05T21:40:11.473019145Z stderr F -A KUBE-EXTERNAL-SERVICES -m comment --comment "services-1776/affinity-nodeport-timeout has no endpoints" -m addrtype --dst-type LOCAL -m tcp -p tcp --dport 31750 -j REJECT
2020-07-05T21:40:11.473034603Z stderr F -A KUBE-FORWARD -m conntrack --ctstate INVALID -j DROP
2020-07-05T21:40:11.47306164Z stderr F -A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x00004000/0x00004000 -j ACCEPT
2020-07-05T21:40:11.473067979Z stderr F -A KUBE-FORWARD -m comment --comment "kubernetes forwarding conntrack pod source rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
2020-07-05T21:40:11.473074652Z stderr F -A KUBE-FORWARD -m comment --comment "kubernetes forwarding conntrack pod destination rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
2020-07-05T21:40:11.473080719Z stderr F COMMIT
2020-07-05T21:40:11.473088162Z stderr F *nat
```

**Comment by aojea** [comment]
@BenTheElder FYI, I think that in kind we are being to agressive with iptables and this is causing contention when there is a big number of changes, that may explain the iptables lock issue

diff between kube-prox GCE config
```
I0705 20:58:01.848313       1 proxier.go:328] iptables(IPv4) sync params: minSyncPeriod=10s, syncPeriod=1m0s, burstSyncs=2
```
and KIND config
```
2020-07-05T21:25:18.696487533Z stderr F I0705 21:25:18.693778       1 proxier.go:328] iptables(IPv4) sync params: minSyncPeriod=0s, syncPeriod=30s, burstSyncs=2
```

**Comment by aojea** [comment]
@BenTheElder and the winner holding the lock is .... the portmap plugin

```
wget https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/92811/pull-kubernetes-e2e-kind/1281213384548683778/artifacts/logs/kind-worker/kubelet.log

grep IPTABLES kubelet.log | grep -v ms |  awk '{ print $NF,$0 }' | sort -k1,1 -n | cut -f2- -d' '
(snipped)
Jul 09 14:02:47 kind-worker kubelet[767]: I0709 14:02:47.983562     767 server.go:1336] IPTABLES lock acquired by Pid: 148823 Comm: (ip6tables) PPid: 147327 PComm: (portmap) ElapsedTime: 12.807867801s
Jul 09 14:01:32 kind-worker kubelet[767]: I0709 14:01:32.837867     767 server.go:1336] IPTABLES lock acquired by Pid: 140811 Comm: (ip6tables) PPid: 140644 PComm: (portmap) ElapsedTime: 12.839015454s
Jul 09 14:01:32 kind-worker kubelet[767]: I0709 14:01:32.790118     767 server.go:1336] IPTABLES lock acquired by Pid: 140660 Comm: (iptables) PPid: 139580 PComm: (portmap) ElapsedTime: 12.843264998s
Jul 09 14:02:49 kind-worker kubelet[767]: I0709 14:02:49.116133     767 server.go:1336] IPTABLES lock acquired by Pid: 148823 Comm: (ip6tables) PPid: 147327 PComm: (portmap) ElapsedTime: 13.940434659s
Jul 09 14:01:34 kind-worker kubelet[767]: I0709 14:01:34.144748     767 server.go:1336] IPTABLES lock acquired by Pid: 140811 Comm: (ip6tables) PPid: 140644 PComm: (portmap) ElapsedTime: 14.145899462s
Jul 09 14:01:35 kind-worker kubelet[767]: I0709 14:01:35.259976     767 server.go:1336] IPTABLES lock acquired by Pid: 140811 Comm: (ip6tables) PPid: 140644 PComm: (portmap) ElapsedTime: 15.261130135s
Jul 09 14:02:50 kind-worker kubelet[767]: I0709 14:02:50.517041     767 server.go:1336] IPTABLES lock acquired by Pid: 148823 Comm: (ip6tables) PPid: 147327 PComm: (portmap) ElapsedTime: 15.341346641s
Jul 09 14:01:36 kind-worker kubelet[767]: I0709 14:01:36.372998     767 server.go:1336] IPTABLES lock acquired by Pid: 140811 Comm: (ip6tables) PPid: 140644 PComm: (portmap) ElapsedTime: 16.374148888s
Jul 09 14:01:37 kind-worker kubelet[767]: I0709 14:01:37.471170     767 server.go:1336] IPTABLES lock acquired by Pid: 140811 Comm: (ip6tables) PPid: 140644 PComm: (portmap) ElapsedTime: 17.472321233s
Jul 09 14:01:38 kind-worker kubelet[767]: I0709 14:01:38.573475     767 server.go:1336] IPTABLES lock acquired by Pid: 140811 Comm: (ip6tables) PPid: 140644 PComm: (portmap) ElapsedTime: 18.574628968s
Jul 09 14:01:39 kind-worker kubelet[767]: I0709 14:01:39.770235     767 server.go:1336] IPTABLES lock acquired by Pid: 140811 Comm: (ip6tables) PPid: 140644 PComm: (portmap) ElapsedTime: 19.771386831s
```

**Comment by aojea** [comment]
more findings about this, it seems that when a pod is deleted the portmap is executed 3 times, if we add that to the fact that it executes iptables and ip6tables it means we hold the lock 6 times.

how to repro

1. move the portmap plugin to portmap.bin
2. create a wrapper script to log the calls
```sh
docker exec -it kind-control-plane cat /opt/cni/bin/portmap
#!/bin/sh
echo "$(date +"%T") portmap $@" >> /tmp/debug_portmap
tee -a /tmp/debug_portmap | /opt/cni/bin/portmap.bin $@
echo "\n---------------" >> /tmp/debug_portmap
```

3. create a pod `kubectl run nginx --image=nginx --port=80` 

4. delete the pod `kubectl delete deployment nginx`

```
08:56:59
 portmap 
{"capabilities":{"portMappings":true},"cniVersion":"0.3.1","name":"kindnet","prevResult":{"cniVersion":"0.3.1","dns":{},"interfaces":[{"mac":"6e:14:38:3e:68:1e","name":"veth92e859b0"},{"mac":"66:a5:e2:65:5b:d7","name":"eth0","sandbox":"/var/run/netns/cni-181b692e-690f-2f62-abbb-5813ea98d9ba"}],"ips":[{"address":"10.244.0.14/24","gateway":"10.244.0.1","interface":1,"version":"4"}],"routes":[{"dst":"0.0.0.0/0"}]},"runtimeConfig":{"portMappings":null},"type":"portmap"}
---------------
08:59:57
portmap  
{"capabilities":{"portMappings":true},"cniVersion":"0.3.1","name":"kindnet","runtimeConfig":{"portMappings":null},"type":"portmap"}
---------------
08:59:57
portmap  
{"capabilities":{"portMappings":true},"cniVersion":"0.3.1","name":"kindnet","runtimeConfig":{"portMappings":null},"type":"portmap"}
---------------
08:59:58
portmap  
{"capabilities":{"portMappings":true},"cniVersion":"0.3.1","name":"kindnet","runtimeConfig":{"portMappings":null},"type":"portmap"}
---------------
```

if we configure a hostPort is even worse, it's called more times

```
{"capabilities":{"portMappings":true},"cniVersion":"0.3.1","name":"kindnet","prevResult":{"cniVersion":"0.3.1","dns":{},"interfaces":[{"mac":"fa:1e:d3:37:d0:be","name":"veth27340614"},{"mac":"6a:63:4c:38:96:6c","name":"eth0","sandbox":"/var/run/netns/cni-681e6da5-26f0-0a95-3cb0-cff8e24307f6"}],"ips":[{"address":"10.244.0.17/24","gateway":"10.244.0.1","interface":1,"version":"4"}],"routes":[{"dst":"0.0.0.0/0"}]},"runtimeConfig":{"portMappings":[{"HostPort":8080,"ContainerPort":80,"Protocol":"tcp","HostIP":""}]},"type":"portmap"}
---------------
09:02:27

{"capabilities":{"portMappings":true},"cniVersion":"0.3.1","name":"kindnet","runtimeConfig":{"portMappings":null},"type":"portmap"}
---------------
09:02:28

{"capabilities":{"portMappings":true},"cniVersion":"0.3.1","name":"kindnet","runtimeConfig":{"portMappings":null},"type":"portmap"}
---------------
09:02:29

{"capabilities":{"portMappings":true},"cniVersion":"0.3.1","name":"kindnet","runtimeConfig":{"portMappings":null},"type":"portmap"}
---------------
09:02:30

{"capabilities":{"portMappings":true},"cniVersion":"0.3.1","name":"kindnet","runtimeConfig":{"portMappings":null},"type":"portmap"}
---------------
09:02:30

{"capabilities":{"portMappings":true},"cniVersion":"0.3.1","name":"kindnet","runtimeConfig":{"portMappings":null},"type":"portmap"}
---------------
09:03:15

{"capabilities":{"portMappings":true},"cniVersion":"0.3.1","name":"kindnet","runtimeConfig":{"portMappings":[{"HostPort":8080,"ContainerPort":80,"Protocol":"tcp","HostIP":""}]},"type":"portmap"}
---------------
09:03:16

{"capabilities":{"portMappings":true},"cniVersion":"0.3.1","name":"kindnet","runtimeConfig":{"portMappings":[{"HostPort":8080,"ContainerPort":80,"Protocol":"tcp","HostIP":""}]},"type":"portmap"}
---------------
09:03:17

{"capabilities":{"portMappings":true},"cniVersion":"0.3.1","name":"kindnet","runtimeConfig":{"portMappings":[{"HostPort":8080,"ContainerPort":80,"Protocol":"tcp","HostIP":""}]},"type":"portmap"}

```

**Comment by bboreham** [comment]
Great piece of detective work, Antonio!  We've now merged your PR into the portmap plugin.

Can I ask: are there any issues filed to reduce the number of times Kubelet (or containerd) calls DEL on the same pod?

**Comment by aojea** [comment]
> Great piece of detective work, Antonio! We've now merged your PR into the portmap plugin.

Thanks

> Can I ask: are there any issues filed to reduce the number of times Kubelet (or containerd) calls DEL on the same pod?

I opened one some time ago https://github.com/containerd/cri/issues/1352
I think that since the DEL should be idempotent the runtimes prefer to be safe and run it to avoid sandbox leakage, but that's my guess

**Comment by bboreham** [comment]
That CRI issue seems focused on whether the calls should be concurrent, whereas my point is that they shouldn't need more than one, for a given container.

**Comment by aojea** [comment]
> That CRI issue seems focused on whether the calls should be concurrent, whereas my point is that they shouldn't need more than one, for a given container.

yeah, sorry, 

> That CRI issue seems focused on whether the calls should be concurrent, whereas my point is that they shouldn't need more than one, for a given container.

ups, sorry, no I'm aware of, I attached some kubelet logs here https://pastebin.com/9d83jMvj , that show that `TearDown network`  is called 3 times from the kubelet, I didn't analyzed the events that are triggering the TearDowns that causes that the CRI configured send the DEL to the CNI

**Comment by aojea** [comment]
it was very useful :smile:

**Pull request closed without merging**
