### PR TITLE
Adds Operational Actions to the Kubernetes layer

### PR DESCRIPTION
**Pull request by lazypower**
**What this PR does / why we need it**:

This PR adds management actions to the Kubernetes charm to cordon/drain nodes, as well as resume operation once the action(s) have been taken.

**Special notes for your reviewer**:

If you wish to test these actions, feel free to deploy

```
export KUBERNETES_PROVIDER=juju
cluster/kube-up.sh
... once deployed ...
juju run-action kubernetes/0 microbot replicas=15
juju run-action kubernetes/1 pause
... verify unit is cordoned, and drained ...
juju run-action kubernetes/1 resume
```

**Release note**:

``` release-note
Adds operational actions to the juju charm layer - pause/resume
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31202)

### CODE REVIEW

**Comment by chuckbutler** [comment]
@mbruzek When you have a moment, would you mind taking a look over this PR and ensure its sane? It works well for me in testing.

**Comment by marcoceppi** [comment]
:+1: from me, tested locally

**Comment by chuckbutler** [comment]
@zmerlynn I forgot if the project prefers single squashed commits. Let me know and I'll update accordingly.

**Comment by castrojo** [comment]
LGTM, tested on GCE.

**Comment by mbruzek** [comment]
We still need this PR to land. We got stuck in the v1.4.0 freeze and now our PR is timing out?  Can someone add the 'keep-open' label, I can't add labels.

**Comment by mbruzek** [comment]
@kubebot "ok to test"

**Review by mbruzek — APPROVED** [review]
+1 LGTM

**Comment by chuckbutler** [comment]
I'm going to close this PR as its superseded by other work  and is now stale. The new work will be proposed against kubernetes proper sooner rather than continue to ride this PR against a layer we are deprecating.

**Pull request closed without merging**
