### PR TITLE
Changed buckets for apiserver_request_duration_seconds metric

### PR DESCRIPTION
**Pull request by pawbana**
/kind cleanup

#### What this PR does / why we need it:
As discussed in [pr/105890](https://github.com/kubernetes/kubernetes/pull/105890) (see [comment](https://github.com/kubernetes/kubernetes/pull/105890#discussion_r737390106)) buckets in apiserver_request_duration_seconds metric are rearranged to save space.

#### Which issue(s) this PR fixes:
Fixes issue: [#105346](https://github.com/kubernetes/kubernetes/issues/105346)

#### Does this PR introduce a user-facing change?
```release-note
Changed buckets in apiserver_request_duration_seconds metric from [0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0,1.25, 1.5, 1.75, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5, 6, 7, 8, 9, 10, 15, 20, 25, 30, 40, 50, 60] to [0.05, 0.1, 0.2, 0.4, 0.6, 0.8, 1.0, 1.25, 1.5, 2, 3, 4, 5, 6, 8, 10, 15, 20, 30, 45, 60]
```

### CODE REVIEW

**Comment by dgrisonnet** [comment]
Thanks @pawbana for splitting this change. Could you mention in the PR description that it fixes https://github.com/kubernetes/kubernetes/issues/105346?

/ok-to-test
/lgtm

/assign @wojtek-t

**Comment by pawbana** [comment]
> Thanks @pawbana for splitting this change. Could you mention in the PR description that it fixes #105346?
> 
> /ok-to-test /lgtm
> 
> /assign @wojtek-t

Done

**Pull request merged**
