### PR TITLE
Manage BUILD files using gazelle + kazel

### LINKED ISSUE #47558: switch from gazel to gazelle
Currently the Go rules in BUILD files are generated by [gazel](https://github.com/mikedanese/gazel).

We should switch to using the officially-supported [gazelle tool](https://github.com/bazelbuild/rules_go/tree/master/go/tools/gazelle), along with some sort of successor to gazel which generates the srcs and generated-code rules.

cc @spxtr @mikedanese

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: uses the upstream `gazelle` tool to manage go rules in BUILD files.
This is needed to support Bazel builds on Mac OS and Bazel cross compilation in general.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #47558

**Special notes for your reviewer**:
It's probably easiest to review this commit-by-commit:
* bump to latest `rules_go` (for recent `cgo_library` and `gazelle` improvements)
* update `kazel` with recent compatibility fixes (https://github.com/kubernetes/repo-infra/pull/28, https://github.com/kubernetes/repo-infra/pull/27), update `hack` scripts to download/build `gazelle`, and then run both `gazelle` and `kazel`. (Additionally make `gazelle` skip things it shouldn't touch.)
* run `hack/update-bazel.sh` to autogenerate everything
* remove the old `cgo_genrule` rules - these are now part of `go_library`
* remove the `automanaged` tags from all go rules - `gazelle` doesn't use them, and it prevents an old version of `kazel/gazel` from messing with the rules
* remove the `licenses()` rules from everywhere but `third_party/` - we don't need them, and `gazelle` won't add them on new `BUILD` files it generates.

**Release note**:

```release-note
NONE
```
for review:
/assign @mikedanese @spxtr 
for approval:
/assign @thockin

### CODE REVIEW

**Comment by ixdy** [comment]
rebase 1/N

**Comment by mikedanese** [comment]
/lgtm

feel free to reapply if you are only rebasing.

**Comment by ixdy** [comment]
re-tagging.
rebase 2/N

**Comment by ixdy** [comment]
wow, only 2 rebases! \o/

**Comment by CaoShuFeng** [comment]
I get this when I run "hack/verify-bazel.sh" in master branch:

```
$ hack/verify-bazel.sh 
DRY-RUN: wrote "pkg/generated/openapi/BUILD"

--- /tmp/actual-file-364655342	2017-08-14 13:45:26.857494623 +0800
+++ /tmp/expected-file-492408693	2017-08-14 13:45:26.857494623 +0800
@@ -9,6 +9,8 @@
     name = "go_default_library",
     srcs = ["doc.go"],
     openapi_targets = [
+        "_output/dockerized/go/src/github.com/miekg/coredns/vendor/k8s.io/client-go/1.5/pkg/runtime",
+        "_output/dockerized/go/src/github.com/miekg/coredns/vendor/k8s.io/client-go/1.5/pkg/watch/versioned",
         "federation/apis/federation/v1beta1",
         "pkg/apis/abac/v0",
         "pkg/apis/abac/v1beta1",

Run ./hack/update-bazel.sh
```

**Comment by ixdy** [comment]
@CaoShuFeng yeah, this is not new. we need https://github.com/kubernetes/repo-infra/pull/32 to get merged and then update kubernetes/kubernetes to use it. this will go in hopefully sometime this week.

in the meantime, ignore the error, or delete `_output/dockerized/go/src`.

**Comment by CaoShuFeng** [comment]
Thanks @ixdy

**Comment by ixdy** [comment]
@CaoShuFeng https://github.com/kubernetes/kubernetes/pull/50804 should fix this once merged

**Pull request merged**
