### PR TITLE
Fix bazel //build/rpms

### PR DESCRIPTION
**Pull request by detiber**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Fixes the `build/rpms` target for bazel

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Comment by timothysc** [comment]
b/c this artifact is not part of any infra :-( it ok to punt til 1.14

**Comment by chuckha** [comment]
good fixes all around, i'm glad to see this stuff is getting cleaner

/lgtm

**Review by luxas — APPROVED** [review]
Thanks @detiber!
Can you also bump the CNI version from 0.5.1 to 0.6.0 in here https://github.com/kubernetes/kubernetes/blob/master/build/BUILD#L95 please?

**Comment by chuckha** [comment]
Think it's worth adding a non-blocking test job to see if these commands work?

**Comment by mauilion** [comment]
/hold
Just found that bazel relies on local rpmbuild and %{_sysctldir} is a new enough macro that it's not in all versions of rpmbuild.

I am putting a PR together to address it.

**Comment by mauilion** [comment]
@detiber @luxas I pull this commit and addressed the macro thing into this PR: https://github.com/kubernetes/kubernetes/pull/71540

**Comment by luxas** [comment]
> Just found that bazel relies on local rpmbuild and %{_sysctldir} is a new enough macro that it's not in all versions of rpmbuild.

Will you fix this in some other PR @mauilion or should we unblock this?

**Comment by mauilion** [comment]
it's addressed in https://github.com/kubernetes/kubernetes/pull/71540

I pulled in @detiber commit here and addressed it and the conntrack thing in that one PR

**Comment by detiber** [comment]
closing in favor of #71540 

/close

**Pull request closed without merging**
