### PR TITLE
fix: change disk client API version for Azure Stack

### PR DESCRIPTION
**Pull request by songjiaxun**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Switch the Azure disk client API version for Azure Stack.
This PR is similar to https://github.com/kubernetes/kubernetes/commit/09112ed1f423f5666a82e7102685ac550d6e672d

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve
/retest

**Comment by andyzhangx** [comment]
@chewong @jackfrancis

aks-engine is panic in e2e test:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/96829/pull-kubernetes-e2e-aks-engine-azure/1331424834634125312

```
2020/11/25 02:38:54 util.go:68: curl https://raw.githubusercontent.com/Azure/aks-engine/master/examples/kubernetes.json
2020/11/25 02:38:54 aksengine.go:1128: Deleting resource group: kubetest-58aa29f8-2ec6-11eb-accd-664f61a03ae3.
2020/11/25 02:38:54 process.go:96: Saved XML output to /logs/artifacts/junit_runner.xml.
2020/11/25 02:38:54 process.go:153: Running: bash -c . hack/lib/version.sh && KUBE_ROOT=. kube::version::get_version_vars && echo "${KUBE_GIT_VERSION-}"
2020/11/25 02:39:03 process.go:155: Step 'bash -c . hack/lib/version.sh && KUBE_ROOT=. kube::version::get_version_vars && echo "${KUBE_GIT_VERSION-}"' finished in 9.195966178s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1a2e994]
goroutine 1 [running]:
main.(*aksEngineDeployer).populateAPIModelTemplate(0xc0000b58c0, 0x52, 0xc000910000)
	/workspace/kubetest/aksengine.go:481 +0x2f4
main.(*aksEngineDeployer).Up(0xc0000b58c0, 0xc0114154f2, 0xc91134a4fdf9b)
	/workspace/kubetest/aksengine.go:1023 +0x65
k8s.io/test-infra/kubetest/process.(*Control).XMLWrap(0xc00063b0c0, 0x2fde100, 0x1fab34c, 0x2, 0xc0001c13c0, 0x0, 0x0)
	/workspace/kubetest/process/process.go:103 +0x82
main.run(0x22ce5c0, 0xc0000b58c0, 0x7ffe80ea2901, 0x5, 0x10000, 0x0, 0x0, 0x0, 0x0, 0x7ffe80ea293f, ...)
	/workspace/kubetest/e2e.go:115 +0x56b
main.complete(0xc000409180, 0x0, 0x0)
	/workspace/kubetest/main.go:398 +0x498
main.main()
	/workspace/kubetest/main.go:307 +0x405
+ EXIT_VALUE=2
+ set +o xtrace
Cleaning up after docker in docker.
```

**Review by feiskyer — COMMENTED** [review]
/milestone v1.20

**Pull request merged**
