### PR TITLE
Fix some static check errors in test file

### PR DESCRIPTION
**Pull request by yuxiaobo96**
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix some static check errors in test file.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by oomichi** [comment]
I cannot follow the meaning of `Fix some static check errors in test file.`
Does it mean `fmt.Errorf()` should not have message with uppercase of the first string?
What is actually the `static check`?

**Comment by yuxiaobo96** [comment]
/cc @oomichi
Strings of Error do not begin with an uppercase (except for specific nouns), and do not end with punctuation because they are often printed in the error output log.
This is just my understanding.

**Comment by oomichi** [comment]
@yuxiaobo96 
> Strings of Error do not begin with an uppercase (except for specific nouns), and do not end with punctuation because they are often printed in the error output log.
This is just my understanding.

Could you provide the source of the above rule? (URL or something)

**Comment by yuxiaobo96** [comment]
@oomichi 
This is the link: https://github.com/golang/go/wiki/CodeReviewComments#error-strings.
Maybe I didn't understand its true meaning.
Thank you for your help.

**Comment by oomichi** [comment]
@yuxiaobo96 Thanks for providing the URL, I got the point.
Now I am not sure we (Kubernetes community) need to follow generic golang dev rule, so I am asking it as https://kubernetes.slack.com/archives/C09R23FHP/p1574107301326100

**Comment by yuxiaobo96** [comment]
@oomichi 
Thank you, I have seen it in slack.

**Pull request closed without merging**
