### PR TITLE
[WIP] kubeadm unit test regressions

### PR DESCRIPTION
**Pull request by GheRivero**
[WIP] kubeadm unit test regressions

### CODE REVIEW

**Comment by timothysc** [comment]
I'm confused by why the whole test suite isn't failing it these UTs aren't passing.

**Comment by GheRivero** [comment]
All the tests have bad flags args so the `kubeadm` will fail; but since that's what we are checking ({args: "--api-port=foobar", expected: false}) the tests pass. (Don't know if this was the intention or not) In case we pass valid flags args, the tests will time out cause there is no kubeadm environment (it's executed with --skip-preflight)....

Anyway, these are not proper unit test (more like functional tests) and we truly need to rework them.

**Comment by luxas** [comment]
@GheRivero do you plan to make this mergeable or expand the scope on this one?

**Comment by luxas** [comment]
ping @GheRivero are you gonna work on this or should I close it?

**Pull request closed without merging**
