### PR TITLE
Automated cherry pick of #70353: Improve Azure instance metadata handling

### PR DESCRIPTION
**Pull request by feiskyer**
Cherry pick of #70353 on release-1.11.

#70353: Improve Azure instance metadata handling

### CODE REVIEW

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by feiskyer** [comment]
Fixed gofmt issues because of go1.11.

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by feiskyer** [comment]
ping @foxish @MaciekPytel for cherry pick approval

**Comment by MaciekPytel** [comment]
Sorry, I can't approve cherry-pick to 1.11.

**Pull request merged**
