### PR TITLE
Guarantee we finish writing to the test log before the test exits.

### LINKED ISSUE #22614: unit test flake: TestSchedulerForgetAssumedPodAfterDelete race
kubernetes-jenkins/pr-logs/pull/21645/kubernetes-pull-test-unit-integration/17627

From PR #21645

```
=== RUN   TestSchedulerForgetAssumedPodAfterDelete
==================
WARNING: DATA RACE
Read by main goroutine:
  runtime.slicebytetostring()
      /tmp/workdir/go/src/runtime/string.go:75 +0x0
  ??()
      -:0 +0xc8200e92af
  fmt.(*pp).printArg()
      /tmp/workdir/go/src/fmt/print.go:800 +0x735
  fmt.(*pp).doPrintf()
      /tmp/workdir/go/src/fmt/print.go:1219 +0x2a52
  fmt.Fprintf()
      /tmp/workdir/go/src/fmt/print.go:188 +0x81
  fmt.Printf()
      /tmp/workdir/go/src/fmt/print.go:197 +0xc4
  testing.(*T).report()
      /tmp/workdir/go/src/testing/testing.go:517 +0xaa5
  testing.RunTests()
      /tmp/workdir/go/src/testing/testing.go:570 +0xba0
  testing.(*M).Run()
      /tmp/workdir/go/src/testing/testing.go:494 +0xe4
  main.main()
      k8s.io/kubernetes/plugin/pkg/scheduler/_test/_testmain.go:68 +0x20f

Previous write by goroutine 50:
  runtime.slicestringcopy()
      /tmp/workdir/go/src/runtime/slice.go:141 +0x0
  testing.(*common).log()
      /tmp/workdir/go/src/testing/testing.go:343 +0x1b4
  testing.(*common).Logf()
      /tmp/workdir/go/src/testing/testing.go:356 +0x82
  testing.(*common).Logf-fm()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/scheduler_test.go:69 +0x5f
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartLogging.func1()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:211 +0x2a7
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:232 +0x14e

Goroutine 50 (finished) created at:
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartEventWatcher()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:234 +0x8f
  k8s.io/kubernetes/pkg/client/record.(*eventBroadcasterImpl).StartLogging()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/record/event.go:212 +0xa5
  k8s.io/kubernetes/plugin/pkg/scheduler.TestSchedulerForgetAssumedPodAfterDelete()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/plugin/pkg/scheduler/scheduler_test.go:162 +0x101
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc
==================
```

### PR DESCRIPTION
**Pull request by mml**
Should fix #22614

### CODE REVIEW

**Comment by mml** [comment]
@k8s-bot Probar esto, por favor.

**Comment by mml** [comment]
@k8s-bot test this, please

**Comment by davidopp** [comment]
LGTM

**Comment by mml** [comment]
@k8s-bot good grief, it's just because the travis build timed out..

**Comment by eparis** [comment]
This PR has added the `cherrypick-candidate` label but did not set a milestone. This is an invalid state and will not be considered for cherrypick-ing to any release branch. The `cherrypick-candidate` label will be automatically removed from such PRs in the future.

**Comment by bgrant0607** [comment]
Manually merging. @k8s-oncall

**Comment by eparis** [comment]
This PR is included in #22874 which is slated to be included in the release-1.2 branch.
Please verify that the cherry-pick in that PR looks correct.

**Comment by mml** [comment]
Verified.

**Pull request merged**
