### PR TITLE
Set ginkgo time if not specified explicitly

### PR DESCRIPTION
**Pull request by dims**
See https://github.com/kubernetes/kubernetes/issues/126001 and https://github.com/kubernetes/test-infra/pull/32966

We can do better and avoid heartburn by setting ginkgo timeout if not specified explicitly. We use the warning eye catcher log line `ginkgo flags are missing explicit --timeout` to inform anyone setting up a fresh CI job as well.

#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
Works fine! snippet from [log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/126055/pull-kubernetes-node-e2e-containerd/1811765334173028352/build-log.txt)
```
W0712 14:27:50.118856    9558 remote.go:158] ginkgo flags are missing explicit --timeout (ginkgo defaults to 60 minutes)
I0712 14:27:50.118889    9558 remote.go:165] updated ginkgo flags: --nodes=8 --focus="\[NodeConformance\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]" --no-color -v --timeout=62m
```

**Comment by dims** [comment]
/assign @upodroid @ameukam 

I'd like to test this out over the weekend, pretty please!

**Review by upodroid — APPROVED** [review]
/lgtm 

Enjoy

**Pull request merged**
