### PR TITLE
Automated cherry pick of #23435

### PR DESCRIPTION
**Pull request by jsafrane**
Cherry pick of #23435 on release-1.2.

### CODE REVIEW

**Comment by brendandburns** [comment]
over to @thockin since he LGTM'd for cherry-pick approval.

**Comment by thockin** [comment]
The cherry pick LGTM, but we're not doing cherry picks this way any longer.  Instead, flag the original PR as a cherrypick-candidate and set milestone to 1.2

@david-mcmahon should we delete the cherry-pick tool or make it print something?

**Comment by jsafrane** [comment]
@thockin, I can't label PRs

**Comment by thockin** [comment]
I'll see if I can fix that

**Comment by thockin** [comment]
and it is already labelled for CP

**Comment by david-mcmahon** [comment]
@thockin The [current doc](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md) is correct.  Post X.Y.0 we use the cherry_pick_pull.sh script.
What is not correct however is the bot adding `release-note-label-needed` to this cherrypick PR.  @eparis, can you take a look?

@jsfrane, unless you are on the single ACL that github provides you are unable to add labels.  We're [looking for solutions](https://github.com/kubernetes/kubernetes/issues/24169) if you have any suggestions.

**Comment by eparis** [comment]
assigning to @roberthbailey he is responsible for 1.2.
@jsafrane please re-open

@david-mcmahon I guess the bot could add `release-note-note` if the parent has the release note. And add `release-note-label-needed` if we cannot determine a parent....

**Comment by thockin** [comment]
I'm confused - the doc says just to label the original PR, which is labelled.

**Comment by eparis** [comment]
That's correct, hopefully no labeling needs done here. After the parent gets `cherrypick-approved` (should come from @roberthbailey ) this PR should automatically get `cherrypick-approved`

**Comment by david-mcmahon** [comment]
@thockin that's correct process.  We're trying to figure out why the bot is doing something different.
@eparis, right, release-note-label-needed should only appear if this is a non-cherry-pick (parent unavailable).

**Comment by zmerlynn** [comment]
@k8s-bot unit test this, issue #IGNORE (release branch)

**Pull request merged**
