### PR TITLE
More Go Vet Fixes

### PR DESCRIPTION
**Pull request by goltermann**

### CODE REVIEW

**Comment by goltermann** [comment]
First commit has been reviewed and LGTMed.  Only need review of the "unkeyed fields" one.

Will rebase once the first commit is through the queue.

**Comment by goltermann** [comment]
Fixes more of #22523

**Comment by krousey** [comment]
The second commit LGTM

**Comment by goltermann** [comment]
@krousey want to take another look?  I missed a few files in the first commit, and needed to run gofmt, so there are some changes since last round.

**Pull request merged**
