### PR TITLE
Automated cherry pick of #16080

### PR DESCRIPTION
**Pull request by yujuhong**
Cherry pick of #16080 on release-1.1.

### CODE REVIEW

**Comment by yujuhong** [comment]
@lavalamp, I had to drop the test file because it was added after we cut release-1.1, and it relied on `pkg/api/testing/compat/compatibility_tester.go` which was also not in the 1.1 branch. Let me know if you prefer adding both files to the cherrypick.

**Comment by lavalamp** [comment]
@yujuhong How hard is it to cherrypick the PR(s) that the test depends on?

**Comment by yujuhong** [comment]
@lavalamp, it includes the test framework from #13939. I updated the PR with the tests. PTAL, thanks!

**Comment by lavalamp** [comment]
LGTM

(retaining separate commits might be a good idea next time though)

**Comment by mikedanese** [comment]
@k8s-bot unit test this (not sure if this works)

**Comment by piosz** [comment]
Merging since it is required for #14674

**Comment by yujuhong** [comment]
> (retaining separate commits might be a good idea next time though)

Good point. Not sure how to make it work with the automatic cherry-pick script though...

**Comment by lavalamp** [comment]
You can cherry-pick multiple PRs in the same command, and I think it should
do the right thing...

**Comment by yujuhong** [comment]
> You can cherry-pick multiple PRs in the same command, and I think it should
> do the right thing...

I see. Good to know. Will try next time.

**Pull request merged**
