### PR TITLE
update influxdb dependency to v1.1.1 and change client to v2

### PR DESCRIPTION
**Pull request by KarolKraskiewicz**
**What this PR does / why we need it**:
1. it updates version of influxdb libraries used by tests to v1.1.1 to match version used by grafana
2. it switches influxdb client to v2 to address the fact that [v1 is being depricated](https://github.com/influxdata/influxdb/tree/v1.1.1/client#description)

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
cc @piosz 
1. [vendor/BUILD](https://github.com/KarolKraskiewicz/kubernetes/blob/master/vendor/BUILD)  didn't get regenerated after executing `./hack/godep-save.sh` so I left previous version.
Not sure how to trigger regeneration of this file.
2. `tests/e2e/monitoring.go` seem to be passing without changes, even after changing version of the client. 

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by KarolKraskiewicz** [comment]
This PR is a follow up to https://github.com/kubernetes/kubernetes/pull/41925#issuecomment-281901427

**Comment by thockin** [comment]
@k8s-bot ok to test

**Comment by piosz** [comment]
This needs to be fixed
```
W0313 21:11:13.789]   (cd /root/.cache/bazel/_bazel_root/e9f728bbd90b3fba632eb31b20e1dacd/bazel-sandbox/7b09a824-174a-4b89-8660-c68f217276e0-76/execroot/kubernetes && \
W0313 21:11:13.793]   exec env - \
W0313 21:11:13.793]     GOARCH=amd64 \
W0313 21:11:13.793]     GOOS=linux \
W0313 21:11:13.794]   /root/.cache/bazel/_bazel_root/e9f728bbd90b3fba632eb31b20e1dacd/execroot/kubernetes/_bin/linux-sandbox @/root/.cache/bazel/_bazel_root/e9f728bbd90b3fba632eb31b20e1dacd/bazel-sandbox/7b09a824-174a-4b89-8660-c68f217276e0-76/linux-sandbox.params -- bazel-out/local-fastbuild/bin/vendor/bazel-out/local-fastbuild/bin/vendor/github.com/influxdata/influxdb/models.a.GoCompileFile.params).
I0313 21:11:13.903] k8s.io/kubernetes/vendor/github.com/influxdata/influxdb/models/points.go:294: undefined: parseIntBytes
I0313 21:11:13.904] k8s.io/kubernetes/vendor/github.com/influxdata/influxdb/models/points.go:831: undefined: parseIntBytes
I0313 21:11:13.904] k8s.io/kubernetes/vendor/github.com/influxdata/influxdb/models/points.go:838: undefined: parseFloatBytes
I0313 21:11:13.905] k8s.io/kubernetes/vendor/github.com/influxdata/influxdb/models/points.go:1502: undefined: NewInlineFNV64a
I0313 21:11:13.905] k8s.io/kubernetes/vendor/github.com/influxdata/influxdb/models/points.go:1695: undefined: parseIntBytes
I0313 21:11:13.905] k8s.io/kubernetes/vendor/github.com/influxdata/influxdb/models/points.go:1700: undefined: parseFloatBytes
I0313 21:11:13.906] k8s.io/kubernetes/vendor/github.com/influxdata/influxdb/models/points.go:1706: undefined: parseFloatBytes
I0313 21:11:13.906] k8s.io/kubernetes/vendor/github.com/influxdata/influxdb/models/points.go:1776: undefined: parseIntBytes
I0313 21:11:13.906] k8s.io/kubernetes/vendor/github.com/influxdata/influxdb/models/points.go:1784: undefined: parseBoolBytes
I0313 21:11:13.906] k8s.io/kubernetes/vendor/github.com/influxdata/influxdb/models/points.go:1792: undefined: parseFloatBytes
I0313 21:11:13.907] k8s.io/kubernetes/vendor/github.com/influxdata/influxdb/models/points.go:1792: too many errors
W0313 21:11:14.020] ____[5,920 / 7,978] GoCompile plugin/pkg/auth/authorizer/rbac/bootstrappolicy/go_default_test.a
```

Did you follow this guide: https://github.com/kubernetes/community/blob/master/contributors/devel/godep.md?

**Comment by KarolKraskiewicz** [comment]
@piosz Yes, I followed the guide.
As mentioned above the problem was that [vendor/BUILD](https://github.com/KarolKraskiewicz/kubernetes/blob/master/vendor/BUILD) didn't get regenerated, so I just left the old one (so the new types are not recognized by bazel). I somehow did not realize Bazel builds are now officially supported.

I will see how I can get BUILD regenerated and update PR.

**Comment by KarolKraskiewicz** [comment]
Ok, it seems I need to run `./hack/update-bazel.sh` on the project. I will take a look at it tomorrow.

**Comment by KarolKraskiewicz** [comment]
ok, it should fix bazel build

**Comment by piosz** [comment]
@k8s-bot verify test this

**Comment by piosz** [comment]
@ethernetdan low risk change bump deps used in e2e tests

**Comment by piosz** [comment]
@wojtek-t can you please approve?

**Comment by piosz** [comment]
ping @wojtek-t

**Comment by piosz** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
