### PR TITLE
Automated cherry pick of #73639: Document default value for enableServiceLinks

### PR DESCRIPTION
**Pull request by bradhoekstra**
Cherry pick of #73639 on release-1.13.

#73639: Document default value for enableServiceLinks

### CODE REVIEW

**Comment by tpepper** [comment]
@kubernetes/sig-architecture-pr-reviews this cherry pick is in need of ok-to-test, lgtm, and approved if it is to merge

**Comment by bradhoekstra** [comment]
@lavalamp I've fixed the verify errors.

**Comment by bradhoekstra** [comment]
@tpepper I've fixed the verify errors.

**Pull request merged**
