### PR TITLE
Validation of ObjectMeta is inconsistently applied

### PR DESCRIPTION
**Pull request by smarterclayton**
ObjectMeta validation on create and update should be consistent.

This is a required precursor to #3789 so we can make name generation in one
place.

It depends on #3646 and so should not be merged quite yet.

### CODE REVIEW

**Comment by thockin** [comment]
LGTM

**Comment by smarterclayton** [comment]
Fixed review comment, made PortalIP uncleareable (can only be set, never unset) and made Required message not print anything.

----- Original Message -----

**Comment by thockin** [comment]
LGTM - did you intend to commit my original patch with this?

**Comment by thockin** [comment]
Also travis

**Comment by bgrant0607** [comment]
LGTM, also

**Comment by smarterclayton** [comment]
Updated

----- Original Message -----

**Comment by thockin** [comment]
To be clear: this includes (and obsoletes) my #3646.  To quote a smart person: "Gonna break people's examples".  This is the intent at this time, yes?

**Comment by smarterclayton** [comment]
Do we want to have that discussion on Kube-dev and get agreement?  It will break modifications to services that fail validation, but services aren't modified much.  It'll break examples end users may have created and linked in blogs, but gives a clear error now...

**Comment by thockin** [comment]
We have to do it sooner or later.  we can either do it now or do it in convert with v1beta3 activation, but we can't really do it differently in different API versions.

**Comment by thockin** [comment]
@bgrant0607 thoughts on when to incur this breakage?

**Comment by bgrant0607** [comment]
The sooner the better. The longer we wait, the more people we'll break.

**Comment by thockin** [comment]
+1 - let's just pull the bandaid off.  We have kubernetes-announce that we
never use - worth a short email?

**Comment by smarterclayton** [comment]
Sure - but you have to write it since I can't send to that list....

**Comment by bgrant0607** [comment]
@smarterclayton Fixed. You're now a manager.

**Comment by thockin** [comment]
Want to draft something?  Or else I can try tomorrow..

**Comment by smarterclayton** [comment]
Email sent

----- Original Message -----

**Comment by thockin** [comment]
Great.  Do you want to commit mine today and then rebase your?  Or just
slurp mine into yours as you have done?

**Comment by smarterclayton** [comment]
I'd say merge them together.  It'll auto close yours.

----- Original Message -----

**Comment by thockin** [comment]
OK, we'll take your PR, then.  Currently you pass nameFunc - want to drop
that part?

**Comment by smarterclayton** [comment]
nameFunc is required for the generate name stuff, it's painful to remove only to bring it back in there (unless you're referring to something else and I'm just dense)

**Comment by thockin** [comment]
I was thinking to remove the 952 names restriction for Service, but we can do that as a separate step.

Do you think this is done and ready to go?  Did you run e2e (or do you want me to)?

**Comment by smarterclayton** [comment]
Fixed one more validation (grafana added since your commit).  e2e looks green barring network flakiness in goe2e and service.

----- Original Message -----

**Comment by thockin** [comment]
Waiting for green,. then ready to fire.

**Comment by thockin** [comment]
Bombs away

**Pull request merged**
