### PR TITLE
Cleanup: modify some sentences about statefulset

### PR DESCRIPTION
**Pull request by my-git9**
Cleanup: modify some sentences about statefulset

/kind cleanup

### CODE REVIEW

**Comment by my-git9** [comment]
> /triage accepted /lgtm

Thanks for your review, can you approve it?

**Comment by my-git9** [comment]
@oomichi  ask for approval

**Comment by oomichi** [comment]
> @oomichi ask for approval

OK, I think this seems fine to be approved by a single one because of just typos.

/approve

**Pull request merged**
