### PR TITLE
dra api: NodeResourceModel -> ResourceModel

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

When renaming NodeResourceSlice to ResourceSlice, the embedded [Node]ResourceModel also should have been renamed.

#### Special notes for your reviewer:

This is mostly a Go API change, except for embedding that field name in protobuf (?). Let's do it now before this new API gets released for the first time.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/assign @thockin

### CODE REVIEW

**Comment by thockin** [comment]
Goal is to get this into 30, yes?

Thanks!

/lgtm
/approve

**Comment by pohly** [comment]
> Goal is to get this into 30, yes?

Yes.

/cc @kubernetes/release-team 

Can someone re-add LGTM? I had missed a gofmt issue ([change since LGTM](https://github.com/kubernetes/kubernetes/compare/71b417a0b31419552254223815f4585661159d35..a0add8d2c7578cd9f94fc302d6212f9f7d16175b) in https://github.com/kubernetes/kubernetes/pull/123932#issuecomment-1997916909).

**Comment by thockin** [comment]
@kubernetes/release-team requesting milestone 30

**Pull request merged**
