### PR TITLE
fix: remove ioutil for new go version

### PR DESCRIPTION
**Pull request by my-git9**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
`io/util` package has been deprecated, we should clean it.
The docs url: https://go.dev/doc/go1.16#ioutil

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lavalamp** [comment]
Please don't tag everyone like that, we triage PRs twice a week.

/lgtm
/approve

**Comment by my-git9** [comment]
> Please don't tag everyone like that, we triage PRs twice a week.
> 
> /lgtm /approve

OK, thanks

**Pull request merged**
