### PR TITLE
Automated cherry pick of #16287 #16546 #16565

### PR DESCRIPTION
**Pull request by j3ffml**
Cherry pick of #16287 #16546 #16565 on release-1.0.

### CODE REVIEW

**Comment by jlowdermilk** [comment]
@k8s-bot unit test this

**Comment by jlowdermilk** [comment]
@k8s-bot unit test this

**Comment by jlowdermilk** [comment]
@k8s-bot unit test this

**Comment by jlowdermilk** [comment]
@k8s-bot unit test this

**Comment by jlowdermilk** [comment]
@k8s-bot unit test this

**Comment by ixdy** [comment]
LGTM

**Comment by ixdy** [comment]
Jenkins unit/integration test will fail until #16622 is merged.

**Comment by ixdy** [comment]
@k8s-bot unit test this please

(I pointed the configuration to download upload-to-gcs.sh from my branch.)

**Comment by a-robinson** [comment]
Manual merge while merge-bot is down due to a single flake from a known issue.

**Pull request merged**
