### PR TITLE
Extract strings for the 'kubectl set' family of commands.

### PR DESCRIPTION
**Pull request by brendandburns**

### CODE REVIEW

**Comment by smarterclayton** [comment]
Bazel die?

**Comment by brendandburns** [comment]
@k8s-bot bazel test this

**Comment by brendandburns** [comment]
@smarterclayton bazel flake fixed, I can haz lgtmz?

**Comment by brendandburns** [comment]
(testing if I can self-lgtm via label given the approve)

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by brendandburns** [comment]
@k8s-bot unit test this

https://github.com/kubernetes/kubernetes/issues/39908

**Comment by brendandburns** [comment]
self LGTM + approve on approve from @smarterclayton above, and to avoid the endless rebase treadmill...

**Pull request merged**
