### PR TITLE
Fix comment out typo (from resolve.conf to resolv.conf) and change the content name (from maxResolveConfLength to maxResolvConfLength)

### PR DESCRIPTION
**Pull request by a2ush**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Fix the name of resolver configuration file in the comment out.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

"resolve.conf" is wrong name[1], and "resolv.conf" is used in the execution part of the source code[2].

[1] https://man7.org/linux/man-pages/man5/resolv.conf.5.html
[2] https://github.com/kubernetes/kubernetes/blob/fbffe056dd03bd9c746e8819ad22043d640a4489/pkg/kubelet/network/dns/dns.go#L432

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

None

```docs
None
```

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]
/triage accepted
/lgtm

maybe also change the name of the constant https://github.com/kubernetes/kubernetes/blob/fbffe056dd03bd9c746e8819ad22043d640a4489/pkg/kubelet/network/dns/dns.go#L58 while you are on it.

**Comment by a2ush** [comment]
> /triage accepted /lgtm
> 
> maybe also change the name of the constant
> 
> https://github.com/kubernetes/kubernetes/blob/fbffe056dd03bd9c746e8819ad22043d640a4489/pkg/kubelet/network/dns/dns.go#L58
> 
> while you are on it.

Thank you for your comment. Agreed.
I modified this name and add the new commit.

I think it is better to separate these modifications into each commit, but if they must be a single commit, please let me know that.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
2 LGTM's! shipping it.

/approve

**Pull request merged**
