### PR TITLE
Modify a bug about RunScale

### PR DESCRIPTION
**Pull request by ping035627**
When "cmdutil.ShouldRecord" return false, it should also deal the command.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31226)

### CODE REVIEW

**Comment by pwittrock** [comment]
ok to test

**Comment by AdoHe** [comment]
*[pkg/kubectl/cmd/scale.go, line 185 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31226#-KPyvZ95VCluct-qQhqv:-KPyvZ95VCluct-qQhqw:blriy7h) ([raw file](https://github.com/kubernetes/kubernetes/blob/b3c09c431de19a3536456e0d7537035668770d37/pkg/kubectl/cmd/scale.go#L185)):*
> ```Go
> 			_, err = helper.Patch(info.Namespace, info.Name, api.StrategicMergePatchType, patchBytes)
> 		} else {
> 			_, err = helper.Replace(info.Namespace, info.Name, false, info.Object)
> ```

why use Replace here?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31226)*

**Comment by AdoHe** [comment]
@ping035627 please help fix the failed tests. Thanks

**Comment by AdoHe** [comment]
@ping035627 kindly ping, still work on this?

**Comment by ping035627** [comment]
@AdoHe yes, I am working on the failed, but haven't solved yet, maybe I overlooked something......

**Comment by ping035627** [comment]
@AdoHe sorry, I think I'm wrong, the original realization is right, and I will close the PR.

**Pull request closed without merging**
