### PR TITLE
[WIP]CSI logging migrate to structured logging

### PR DESCRIPTION
**Pull request by jjmengze**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it:**

According to [Structured Logging KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging) we need to make changes in logging
**Which issue(s) this PR fixes:**

```
none
```

**Does this PR introduce a user-facing change?:**

```
get more structured Logging 
```

### CODE REVIEW

**Comment by jsafrane** [comment]
While I understand the need to have more structured logging, the linked KEP does not specify any log in `pkg/volume/csi` to be a candidate for change. Why did you choose `DeRegisterPlugin` and not other CSI plugin functions?

**Comment by jjmengze** [comment]
It seems to me that whether DeRegisterPlugin is candidate  in the KEP, the log needs to be more structured and easier to read.

**Comment by jjmengze** [comment]
@jsafrane Please Take A Look :)

**Comment by jsafrane** [comment]
You did not really answer my question. Why is log in `DeRegisterPlugin` more important than let's say in `RegisterPlugin`? CSI volume plugin is full of `klog.Infof` logs and even errors/warnings, aren't these as important?

**Comment by jjmengze** [comment]
@jsafrane sincerely thank you for your response.

I am aware of what you’re talking about.Sorry I didn't notice that this PR just revise `DeRegisterPlugin`. All of CSI volume plugin is equally important.

But now CSI is full of log.Info and klog.Error log everywhere. Let's make some changes to log more structured .

I can pick it up !

**Pull request closed without merging**
