### PR TITLE
/test/e2e/apimachinery/:fix bug

### PR DESCRIPTION
**Pull request by tanjunchen**
**What type of PR is this?**
 
 /kind bug
 /kind cleanup
 

**What this PR does / why we need it**:

fix bug in /test/e2e/apimachinery/

/cc @neolit123 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Review by gavinfish — COMMENTED** [review]
/lgtm

**Pull request merged**
