### PR TITLE
Sync peer-finder code from contrib repo

### LINKED ISSUE #2643: pets/peer-finder could have a better default domain, messaging
Right now, peer-finder will presume `cluster.local` as the domain name of the kubernetes cluster unless manually overridden.  This, in conjunction with some popular helm charts (including mongodb-replicaset) can lead to an odd circumstance where peer-finder will seemingly hang forever without any message to the user if the domain name is different.

Given that peer-finder is relying heavily on DNS, it would seem reasonable to reference `/etc/resolv.conf` to better guess the domain name if not supplied.

Furthermore, instead of just looping without any message to the user while the presumed host entry is not in the service's peer list, it would be nice to notify the user what peers are there and what the presumed host entry is.

Peer-entry is currently used in an init container in [kubernetes' chart repo](https://github.com/kubernetes/charts/tree/master/stable/mongodb-replicaset) - and init containers are a bit of a pain to debug - so the more information provided to the user the better.

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/contrib/issues/2643

**Special notes for your reviewer**:
This is just an code sync up PR from https://github.com/kubernetes/contrib/pull/2644

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mkumatag** [comment]
ping @ixdy @luxas @dims

**Comment by ixdy** [comment]
building images now

**Pull request merged**
