### PR TITLE
kubeadm: Remove the --cloud-provider flag for beta init UX

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:

We decided the `--cloud-provider` flag promises way too much compared to what it really does. There is a lot you have to do as an user in order to make the current cloud provider integrations to work. And since we're promising to support the `kubeadm init` UX on a beta level in v1.6, we can't have this flag in the UX. A lot is gonna change here... see proposal: https://github.com/kubernetes/community/pull/128

Once we find a cloudprovider solution we can support (probably using the new flow), we'll just add it.
For now, we'll just document how to do cloudprovider integrations by hand instead. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
kubeadm: Remove the --cloud-provider flag for beta init UX
```
@jbeda @dmmcquay @mikedanese @roberthbailey @pires @errordeveloper

### CODE REVIEW

**Comment by pires** [comment]
I agree with removing this but not sure about removing it from the API as we may need it again in the future.

**Comment by jbeda** [comment]
I want to make sure I really understand what the user experience here will be like.  What will a user need to do to get equivalent behavior once this is merged?

I think this change also removes the option to set this via a config file.  I don't think that is a good idea.  If we do that we end up with requiring users to to edit manifests directly to enable the cloud provider.

So -- I'm in favor of removing the flag but not the option in the master config file.

**Comment by luxas** [comment]
@jbeda @pires Please read my proposal in https://github.com/kubernetes/kubeadm/pull/156, this will be accomplished with a general-purpose `--extra-args`/`ExtraArgs []string` field to both the controller-manager and the apiserver using the API (or the `kubeadm phase` command).

**Comment by jbeda** [comment]
@luxas -- lay it out for me because I'm having a hard time stitching this together.

Right now we have something like this:

```
kubeadm init --cloud-provider=aws
```

What will this be replaced with?  I'm not a fan of anything that requires users to encode all the phases manually.  That seems error prone and brittle.

Are we going to allow people to pass flags to individual phases as part of `kubeadm init`?  
Or continue to use a config file?

**Comment by luxas** [comment]
@jbeda They can use `kubeadm phases` and run e.g.
```
kubeadm alpha phases controlplane apiserver --extra-args "cloud-provider=aws"
kubeadm alpha phases controlplane controller-manager --extra-args "cloud-provider=aws"
```
or they can use the config file for passing general args, for example something like:
```yaml
kind: MasterConfiguration
phases:
  controlPlane:
    apiServer:
      extraArgs:
      - cloud-provider=aws
    controllerManager:
      extraArgs:
      - cloud-provider=aws
```

But I need help with implementing all this stuff; please read the proposal https://github.com/kubernetes/kubeadm/pull/156 with all the details.
As we said, the question just about two arguments to the apiserver and controller-manager, the user can set them by him/herself and we should try out the cloud-controller-manager binary instead which actually should do ~80-90% of this stuff for us with `kubectl apply -f` in most cases.

**Comment by luxas** [comment]
What I do need though is PRs merged, so if you do think for some specific reason that we should treat cloudproviders separately (which I don't think in this case because it's just a plain flag to set), I'll just leave it in the API and get this merged

**Comment by jbeda** [comment]
I'm cool with removing the flag right now.  I'm not cool with removing all ways to set cloud provider until we have a sane alternate mechanism implemented.  

So, we should either leave the config file/API method in (and mark it as unstable/alpha if you like) or we should implement extraflags in the config file/API before we change this.  But we shouldn't remove functionality until the replacement is ready.

**Comment by pires** [comment]
Leave the API.

**Comment by luxas** [comment]
@jbeda @pires Updated, this doesn't tpuch the API anymore. Instead added validation to the API + tests.

**Review by pires — APPROVED** [review]
/lgtm

**Comment by luxas** [comment]
@k8s-bot kops aws e2e test this

**Comment by luxas** [comment]
@jbeda This PR can be lgtm'd now -- builds green and your suggestions incorporated

**Pull request merged**
