### PR TITLE
Remove useless variable and if in kubelet.go

### PR DESCRIPTION
**Pull request by lingsamuel**
Signed-off-by: Ling Samuel <lingsamuelgrace@gmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Remove a variable and if, [this PR](https://github.com/kubernetes/kubernetes/pull/91577/files#diff-67dd9e8f3ee257072765326cb4f242852554a2c0753563fa51e292c0a63a7b94L281-L293) makes them useless.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by AlexeyPerevalov** [comment]
updatechannel here was an none local variable in https://github.com/kubernetes/kubernetes/pull/59276/ and it used both in scope of checkpoint restore (cfg.Restore) and in config.NewSourceApiserver.
And when checkpoint was deprecated here in https://github.com/kubernetes/kubernetes/pull/91577
probably it was left as is w/o proper factoring out.
So I'm ok with this change.

**Comment by lingsamuel** [comment]
ping @AlexeyPerevalov

**Pull request merged**
