### PR TITLE
More options documentation

### PR DESCRIPTION
**Pull request by justinsb**
A little more progress in documenting the (most important) AWS options, and the first documented cross-provider option

### CODE REVIEW

**Comment by mbforbes** [comment]
AWS updates seem to be good. Adding @erictune to check on introducing a `cluster/`-level options.md file, because I'm not sure we want to commit to maintaining another file describing config options (they're already overflowing in the `.sh` files and hard to maintain).

**Comment by erictune** [comment]
I haven't forgotten this.  Just a little backed up with other work.  Will try to loop back tomorrow.

**Comment by justinsb** [comment]
No worries - this isn't particularly high priority or blocking in any way!

Happy to remove the cross-provider file and just keep the docs in cluster/aws.  Could also integrate it into config-default.sh, but that doesn't really feel right to me

**Comment by erictune** [comment]
LGTM.  Needs rebase.  Okay for next oncall to merge once mergable.

**Comment by justinsb** [comment]
Rebased

**Pull request merged**
