### PR TITLE
kubelet/cm: refactor, prepare for runc 1.1 bump

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This does some refactoring, simplification, and occasional fixing pkg/kubelet/cm,
preparing the code for runc 1.1 bump. Originally part of #107149.

#### Special notes for your reviewer:

Please review commit by commit. See individual commit messages for details.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

none

### CODE REVIEW

**Comment by kolyshkin** [comment]
@odinuge @ehashman PTAL

**Review by odinuge — APPROVED** [review]
Thanks for working on this @kolyshkin!

Looks like all my initial comments from the other PR is resolved here, so it looks good from my pov. I am a big fan of all the performance improvements here, as well as the cleanups.

Code looks good, but will prefer if someone like @ehashman can also take a quick look to validate this. Thanks

/lgtm

To be sure;
/test pull-kubernetes-node-kubelet-serial-containerd
/test pull-kubernetes-node-kubelet-serial-cpu-manager
/test pull-kubernetes-node-kubelet-serial-crio-cgroupv1
/test pull-kubernetes-node-kubelet-serial-crio-cgroupv2
/test pull-kubernetes-node-kubelet-serial-hugepages
/test pull-kubernetes-node-kubelet-serial-memory-manager
/test pull-kubernetes-node-kubelet-serial-topology-manager
/test pull-kubernetes-node-memoryqos-cgrpv2
/test pull-kubernetes-node-swap-fedora
/test pull-kubernetes-node-swap-fedora-serial
/test pull-kubernetes-node-swap-ubuntu-serial

**Comment by ehashman** [comment]
Looking at tests:

- pull-kubernetes-node-kubelet-serial-cpu-manager
    - failed to build
- pull-kubernetes-node-kubelet-serial-crio-cgroupv1
- pull-kubernetes-node-kubelet-serial-crio-cgroupv2
    - failed to launch a cluster due to "-he resource 'projects/k8s-infra-e2e-boskos-114/regions/us-west1/addresses/bootstrap-e2e-master-ip' was not found"
- pull-kubernetes-node-kubelet-serial-hugepages
    - failed to build
- pull-kubernetes-node-kubelet-serial-memory-manager
    - failed to build
- pull-kubernetes-node-kubelet-serial-topology-manager
    - failed to build
- pull-kubernetes-node-memoryqos-cgrpv2
    - "The resource 'projects/k8s-infra-e2e-boskos-011/regions/us-west1/addresses/bootstrap-e2e-master-ip' was not found"
- pull-kubernetes-node-swap-fedora
- pull-kubernetes-node-swap-fedora-serial
    - Not surprising these failed, they aren't working due to https://github.com/kubernetes/test-infra/issues/24798
- pull-kubernetes-node-swap-ubuntu-serial
   - the only job with an actual test failure:
          ```E2eNode  Suite: [sig-node] Container Manager Misc [Serial] Validate OOM score  adjustments [NodeFeature:OOMScoreAdj] once the node is setup container  runtime's oom-score-adj should be -999
          { Failure test/e2e_node/container_manager_test.go:81 Timed out after 300.001s. Expected     <*errors.errorString \| 0xc000b28000>: {         s: "expected pid 777's oom_score_adj to be -999; found -500",     } to be nil test/e2e_node/container_manager_test.go:87}```

I know a lot of the presubmits aren't in great shape as they weren't a priority after the dockershim migration since they're only used occasionally. Trying to launch this many node tests simultaneously might have hit capacity issues. Let's see if we can focus on just a few critical ones for this PR.

/skip

**Comment by ehashman** [comment]
Given that https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/108597/pull-kubernetes-node-kubelet-serial-containerd/1505844761926307840/ passed I'm not super concerned by most of these failures, I think the jobs are just a bit neglected and we tried to run jobs we wouldn't normally.

I think the Ubuntu bug is a true failure. According to triage, we've only seen it on the runc 1.1 bump PRs. Is it deterministic?

/test pull-kubernetes-node-swap-ubuntu-serial

### Failure cluster [5c6173278f01b3767cdf](https://go.k8s.io/triage#5c6173278f01b3767cdf)

##### Error text:
```
test/e2e_node/container_manager_test.go:81
Timed out after 300.004s.
Expected
    <*errors.errorString | 0xc0017ac050>: {
        s: "expected pid 777's oom_score_adj to be -999; found -500",
    }
to be nil
test/e2e_node/container_manager_test.go:87
```
#### Recent failures:
[3/21/2022, 2:52:29 AM pr:pull-kubernetes-node-swap-ubuntu-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/108597/pull-kubernetes-node-swap-ubuntu-serial/1505844762270240768)
[3/7/2022, 5:32:16 PM pr:pull-kubernetes-node-swap-ubuntu-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/107149/pull-kubernetes-node-swap-ubuntu-serial/1501007527066734592)

**Comment by bobbypage** [comment]
I'm a little confused on the `pull-kubernetes-node-swap-ubuntu-serial` failure. The test that is failing there is `E2eNode Suite: [sig-node] Container Manager Misc [Serial] Validate OOM score adjustments [NodeFeature:OOMScoreAdj] once the node is setup container runtime's oom-score-adj should be -999`. However, the same test is passing in the `pull-kubernetes-node-kubelet-serial-containerd` job (see https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/108597/pull-kubernetes-node-kubelet-serial-containerd/1505844761926307840/).

Maybe this is something specific to setup of ubuntu swap job?
/cc @ehashman

**Comment by bobbypage** [comment]
The swap job is failing because it does not set `container-runtime-process-name` so the swap test is incorrectly thinking the runtime is [dockerd](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/test_context.go#L309) instead of containerd. (dockerd has -500 OOM score, dockerd has -999 which is what test expects). 

The serial job in contrast correctly sets `container-runtime-process-name` so it doesn't have this problem. https://github.com/kubernetes/test-infra/pull/25726 will fix the swap job.

**Comment by bobbypage** [comment]
/lgtm

LGTM on the code changes, thanks for all the refactoring, it's much cleaner now with less duplication of cgroup configuration.

The swap job is now passing as well.

**Review by mrunalp — APPROVED** [review]

**Review by ehashman — COMMENTED** [review]
/lgtm

thanks for fixing the job!

**Comment by kolyshkin** [comment]
Some weird errors, looks like due to go 1.18 being used by default. Let me try to rebase this.

**Comment by kolyshkin** [comment]
I also think that maybe golangci-lint need to be updated to 1.45.0 because of go 1.18. 

Ah, indeed, there's a PR opened already: https://github.com/kubernetes/kubernetes/pull/108901 to disable the jobs. I think I might know how to fix the issue, so here's https://github.com/kubernetes/kubernetes/pull/108902

**Pull request merged**
