### PR TITLE
Update cadvisor dependency.

### PR DESCRIPTION
**Pull request by rjnagal**
Godep also decided to remove unused appengine dependency.

### CODE REVIEW

**Comment by rjnagal** [comment]
@dchen1107 @vishh 

Bringing in a memory-leak fix for cAdvisor.

**Comment by rjnagal** [comment]
running e2e...

**Comment by dchen1107** [comment]
LGTM and thanks for fixing the memory leakage :-)

**Comment by vishh** [comment]
LGTM.

**Comment by rjnagal** [comment]
Jenkins e2e failure looks like a known race in pulling images, but I thought this didn't happen with per-PR e2e runs @quinton-hoole any ideas?

error: server version (version.Info{Major:"0", Minor:"19+", GitVersion:"v0.19.0-228-g991d3b1b7bc44c", GitCommit:"991d3b1b7bc44c1e96993f82a28879896152c247", GitTreeState:"clean"}) differs from client version (version.Info{Major:"0", Minor:"19+", GitVersion:"v0.19.0-228-gc29d8a96f2b433", GitCommit:"c29d8a96f2b433f795783b23bd20516f8127ef35", GitTreeState:"clean"})!

2015/06/12 16:30:55 Error running get status: exit status 1
2015/06/12 16:30:55 Testing requested, but e2e cluster not up!

**Comment by vishh** [comment]
@fabioy: This PR is important

**Comment by vishh** [comment]
LGTM

**Pull request merged**
