### PR TITLE
Update comments for version ordering

### PR DESCRIPTION
**Pull request by cici37**
#### What type of PR is this?
/kind cleanup
/kind documentation

#### What this PR does / why we need it:
We don't need to order based on preferred version now.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
/assign @BenTheElder 
Hi Ben, this is the comment update mentioned yesterday. Would you mind getting it merged when have time? Thank you

**Comment by BenTheElder** [comment]
Sorry this slipped through the cracks, I've completely lost context on this

**Comment by cici37** [comment]
> Sorry this slipped through the cracks, I've completely lost context on this

Ohh, this comes from the API review for https://github.com/kubernetes/kubernetes/pull/112306 when we discovered this comment is out of date :)

**Comment by cici37** [comment]
> /sig testing /approve /lgtm

Thanks for the approval. Sorry it looks like something wrong with the git bot. Would you mind to reapply the labels when you have time? Thank you^^

**Pull request closed without merging**
