### PR TITLE
Add missed clusterEvents to UnrollWildCardResource

### PR DESCRIPTION
**Pull request by kerthcet**
#### What type of PR is this?
/kind bug
/sig scheduling
/assign @pohly 

#### What this PR does / why we need it:

We forget to add the missed events to `UnrollWildCardResource()` which should contain **all specific cluster events**. But this will not impact the default scheduler since all intree plugins have implemented `EventsToRegister`. Also reorder the events to be aligned. 

Missed events:
- {Event: ClusterEvent{Resource: ResourceClaim, ActionType: All}},
- {Event: ClusterEvent{Resource: ResourceClass, ActionType: All}},

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pohly** [comment]
I'm not up-to-date on the event mechanism. Looks good to me, but perhaps @sanposhiho can do the final LGTM?

/assign @sanposhiho

**Review by sanposhiho — APPROVED** [review]
It doesn't affect the default scheduler, LGTM. 
([This test](https://github.com/kubernetes/kubernetes/blob/b3ba6bda2b4e6a5f46716a0449418b64b623e1ce/pkg/scheduler/scheduler_test.go#L839-L852) proves)

/lgtm

**Comment by sanposhiho** [comment]
Actually wait for a sec

/hold

**Pull request merged**
