### PR TITLE
 move client based restmappers to client-go

### PR DESCRIPTION
**Pull request by deads2k**
Moves the client-based restmappers to client-go where everyone who needs them can have access.

```release-note
the shortcuts which were moved server-side in at least 1.9 have been removed from being hardcoded in kubectl
```

@kubernetes/sig-cli-maintainers @kubernetes/sig-api-machinery-pr-reviews

### CODE REVIEW

**Comment by deads2k** [comment]
@soltysh @juanvallejo this is on the path to having a resource builder that only need a clientconfig function.

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
