### PR TITLE
fix a description error in DynamicAuditing feature

### PR DESCRIPTION
**Pull request by WanLinghao**
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

```release-note
NONE
```

### CODE REVIEW

**Comment by WanLinghao** [comment]
@pbarker PTAL

**Comment by pbarker** [comment]
@liggitt PTAL

**Comment by AishSundar** [comment]
/priority critical-urgent
/remove-priority important-soon

Setting priority to critical-urgent to prevent it from getting kicked out of merge queue in case Tide doesnt get to it by Code freeze time.

**Pull request merged**
