### PR TITLE
Cherry pick of 15813: Fix races in ClusterDns e2e test

### PR DESCRIPTION
**Pull request by sttts**
This is important for 1.1 because it fixes a conformance test and should be part of the next conformance test tag.

### CODE REVIEW

**Comment by ArtfulCoder** [comment]
cherry pick of https://github.com/kubernetes/kubernetes/pull/15813

**Comment by sttts** [comment]
@k8s-bot test this please

**Comment by sttts** [comment]
@k8s-bot test this please

**Comment by sttts** [comment]
Rebased to latest release-1.1

**Comment by wojtek-t** [comment]
Jenkins failure is flake:
"Job should run a job to completion when tasks succeed"

@k8s-bot test this please

**Pull request merged**
