### PR TITLE
Partial revert of #59797

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
Need to do a partial revert of #59797. This PR introduced two problems:
- `INTERNAL_DIRS` has an unbound variable error
- The script introduces the use of mapfile which doesn't exist in bash versions prior to bash 4.x. Darwin (OS X) uses bash 3.x by default.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ixdy** [comment]
cc @ipuustin

**Comment by ipuustin** [comment]
Looks good to me. Let's do the revert.

**Pull request merged**
