### PR TITLE
Trusty: fix 'find' commands and add k8s license and motd info

### PR DESCRIPTION
**Pull request by andyzheng0831**
This is for cherry-picking #26741 into release-1.2 branch

### CODE REVIEW

**Comment by andyzheng0831** [comment]
cc/ @kubernetes/goog-image @wonderfly FYI

**Comment by roberthbailey** [comment]
@k8s-bot unit test this issue: #26906

**Comment by roberthbailey** [comment]
"This branch is out-of-date with the base branch"

**Comment by andyzheng0831** [comment]
@roberthbailey What does it mean? Do we need to make the change directly to the release-1.2, or we just ignore this fix for that branch?

**Comment by roberthbailey** [comment]
It means that you need to rebase this change to the head of the 1.2 branch, either yourself or by clicking the button on the github UI. See https://github.com/blog/2051-protected-branches-and-required-status-checks

**Comment by andyzheng0831** [comment]
I noticed my personal k8s repo is too old and does not have release-1.2 branch. The branch in comparison when generating this PR may not be correct. That may explain why the title is not "Automatic cherrypick...". Let me close this one, update my personal repo, and recreate a cherrypick.

**Pull request closed without merging**
