### PR TITLE
kubelet: fix exclusive CPUs not removed from deleted Pod

### LINKED ISSUE #107074: Exclusive CPUs not removed from deleted Pod and put back in the defaultCPUSet.
### What happened?

The `CPUManager` has logic to periodically cleanup stale state and reclaim exclusive CPUs from pods that have recently terminated. It does this by querying the system for a list of `activePods()` and reclaiming CPUs from any pods it is tracking that are not in this list.

This works fine for most pods, but special care needs to be taken to ensure that CPUs are not accidentally reclaimed from pods that have not yet started yet. Allocation of CPUs to the containers of a pod happens during pod admission (i.e. before the pod is added to the `activePods()` list), so a simple state variable (`pendingAdmissionPod`) is used to indicate which pod is currently being admitted and exclude it from cleanup. Since pod admission is serialized, only one pod will ever be pending admission at a given time, and only a single variable is necessary to track this (i.e. whenever a new pod enters the admission loop to have exclusive CPUs granted to it, `pendingAdmissionPod` is overwritten to point to the new pod, clearing way for the previous one to have its state cleaned up when appropriate).

Unfortunately, this simple procedure can cause problems because `pendingAdmissionPod` is never reset to nil after the `last` pod is admitted. This is usually fine, because the next time a pod comes in for admission, it will be overwritten to point to the new pod. But if no new pods come in, then it continues to point to the last pod that we attempted to admit (forever essentially), making it so that we can never cleanup its state if it gets deleted at some point in the future (because it is always treated as an "active" pod so long as it is pointed to by `pendingAdmissionPod`).

I don't think this issue is critical, since in any practical setting pods will be started and stopped all the time, clearing way for the state of previously admitted pods to be cleaned up. But we should consider a better method of tracking pods that are `notYetActiveButPendingAdmission()` so that we can eliminate this weird edge case.

### What did you expect to happen?

With `--cpu-manager-policy=static` enabled on a node.

Look at the CPU set assigned to one of the system pods running on that node in a non-Guaranteed QOS class:
```
$ kubectl exec -it <pod> -- taskset -cp 1
pid 1's current affinity list: 0-255
```

Create a pod requesting exclusive CPUs:
```
$ cat pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
  - image: ubuntu:20.04
    name: test-ctr
    command: ["bash", "-c"]
    args: ["sleep 99999"]
    resources:
      limits:
        cpu: 4000m
        memory: 1Gi
```
```
$ kubectl apply -f pod.yml
pod/test-pod created
```

Look at the set of exclusive CPUs granted to it (we should see 4):
```
$ kubectl exec -it test-pod -- taskset -cp 1
pid 1's current affinity list: 1,2,129,130
```

Look again at the set of CPU set assigned to the pod in the non-Guaranteed QOS class (the 4 CPUs from above are gone):
```
$ kubectl exec -it <pod> -- taskset -cp 1
pid 1's current affinity list: 0,3-128,131-255
```

Delete the test pod:
```
$ kubectl delete pod test-pod
pod "test-pod" deleted
```

Look again at the set of CPU set assigned to the pod in the non-Guaranteed QOS class (we are back to the original set):
```
$ kubectl exec -it <pod> -- taskset -cp 1
pid 1's current affinity list: 0-255
```

### How can we reproduce it (as minimally and precisely as possible)?

Go through the steps above, but the last step doesn't show the original CPU set restored.
```
$ kubectl exec -it <pod> -- taskset -cp 1
pid 1's current affinity list: 0,3-128,131-255
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Baremetal
</details>

### OS version

_No response_

### Install tools

_No response_

### Container runtime (CRI) and and version (if applicable)

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by hj-johannes-lee**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #107074 

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug that makes CPUs not recliamed from already deleted pod if the pod was the lastly deployed pod. (#107074, @klueska )
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pohly** [comment]
/retest

"Pod pending timeout" failure in pull-kubernetes-e2e-kind-ipv6 is unrelated.

**Comment by matthyx** [comment]
/uncc @ehashman 
@hj-johannes-lee can you add a test covering this change?

**Comment by luozhiwenn** [comment]
Is `pendingAdmissionPod` still necessary? Since the modification of #104577 , the activePods contains the pods in the admission process again, which seems can also fix #103952 

Back to this issue, it was introduced by #103979 (fix #103952 ) , and if #103979 is no longer needed, I think it's better to roll it back. 

/cc @smarterclayton @cynepco3hahue

**Comment by bart0sh** [comment]
@hj-johannes-lee Please, address review comments and add tests if you're interested in working on this PR. If not - please close the PR, thanks.

**Comment by hj-johannes-lee** [comment]
@marquiz No, if there is a chnace to do in the future, I can open a new pr.

**Pull request closed without merging**
