### PR TITLE
Deprecate photon cloud provider

### PR DESCRIPTION
**Pull request by dougm**
vmware/photon-controller is no longer maintained, as of Oct 2017.

Adds a detail field to deprecatedCloudProviders, meant for pointing to external provider url or other reason for deprecation.

**What this PR does / why we need it**:

The photon cloud provider is no longer supported, need to let users know.

Photon controller support has already been removed from kube-up in PR #58096

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dougm** [comment]
/assign @dims @dklyle @hogepodge

Related to PR #63524

**Comment by hogepodge** [comment]
Well, this appears to be an instance where the deprecation code we introduced doesn't completely cover the use cases. I would suggest that we allow for a choice between displaying the URL for a supported provider, or giving an explicit message that the provider is unsupported and will be removed without a replacement.

**Pull request merged**
