### PR TITLE
fix(framework): elaborate the document on PostFilter

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

In my company, the developer misunderstood that when PreFilter returned UnschedulableAndUnresolvable, PostFilter wasn't called by the scheduling framework in the first place.
Taking this opportunity, this PR tries to elaborate the document on PostFilter to make minor things clear to plugin developers.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by utam0k** [comment]
👍

**Review by utam0k — COMMENTED** [review]
How about adding this to the description minute of UnschedulableAndUnresolvable below L97:
https://github.com/kubernetes/kubernetes/pull/121950/files#diff-3a4846227d655e390683e5e53ee7472696f9578dfd998a53393d7e8fc8678af5R97
```
However, how UnschedulableAndUnresolvable is handled depends on PostFilter plugins.
```

**Comment by sanposhiho** [comment]
@utam0k modified a bit

**Review by utam0k — APPROVED** [review]
Look good to me. Thanks!

**Comment by sanposhiho** [comment]
@kubernetes/sig-scheduling-approvers Can anyone take a look 🙏

**Pull request merged**
