### PR TITLE
Support Dev Containers / Github Codespaces

### LINKED ISSUE #113019: Add Codespaces configuration dev container
### What would you like to be added?

For contributors to Kubernetes, a configuration to assure that Codespaces will work with Kubernetes will enable the use of a cloud-based development environment to easily provision an environment with all the requirements and dependencies automatically installed and configured. This will make life easy for new and existing contributors when they are working on multiple branches with different dependencies, or don't have access to a computer or network powerful enough to build Kubernetes.

The Codespaces configuration consists of a Development Container ([devcontainer](https://containers.dev)) file `devcontainer.json` which encodes the configuration of the environment.

### Why is this needed?

sig/contribex is working on a new self-paced course for Kubernetes contribution to be hosted on k8s.dev. Codespaces will be one option for working through the course material

### PR DESCRIPTION
**Pull request by Sharpz7**
Based on: https://github.com/craiglpeters/kubernetes-devcontainer

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

This PR adds support for devcontainers. Right now, it will take a significant amount of time to build - but ideally I would want to also create an image that is built as part of this, maybe in its own repo, that could then be pulled to speed up build times.
Also a wider discussion on whether you would want to support devcontainers all over k8s should probably happen.

https://github.com/kubernetes/test-infra/issues/30454
https://github.com/kubernetes/test-infra/pull/30511#discussion_r1305712447

~~Right now, I have added a custom golang install feature that can take advantage of `.go-version` being present, but maybe there is a more elegant solution we can use?~~
I tried this and it didn't work - my bet is the devcontainer is being created before the repo is present so the version cannot be found. This means we now have the version stated in two places... not ideal.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/113019

#### Does this PR introduce a user-facing change?

```release-note
Adds the code/configs to allow for users to use dev-containers when developing k8s. This brings support for GitHub Codespaces, EnvBuilder, the devcontainer-cli and more.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [Usage]: https://github.com/features/codespaces
- [More Info]: https://containers.dev/
```

### CODE REVIEW

**Comment by Sharpz7** [comment]
cc @craiglpeters

**Review by mrbobbytables — COMMENTED** [review]
I have verified it works, and was able to do a quick release.

The only thing that I think is required at this point is adding an OWNERS file to the .devcontainer directory similar to the one in .github
https://github.com/kubernetes/kubernetes/blob/master/.github/OWNERS

with just the contribex leads for approvers

**Comment by Sharpz7** [comment]
I am going to close this PR... I clearly need to learn how to rebase.

**Pull request closed without merging**
