### PR TITLE
Remove unmaintained stackdriver logging e2e test

### LINKED ISSUE #92731: Missing logging agents causing Job ci-kubernetes-e2e-gci-gce-sd-logging to fail
Job ci-kubernetes-e2e-gci-gce-sd-logging always fails with this error:
```
node <nodename> doesn't have logging agents, want 1
```

### Triage Dashhboard Link:
https://storage.googleapis.com/k8s-gubernator/triage/index.html#9faccb3eb85a99912a98

### Error text:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/logging/stackdriver/soak.go:44
Jun 17 00:16:21.307: Logging agents deployed incorrectly
Unexpected error:
    <*errors.errorString | 0xc002964f50>: {
        s: "node bootstrap-e2e-minion-group-0fsc doesn't have logging agents, want 1",
    }
    node bootstrap-e2e-minion-group-0fsc doesn't have logging agents, want 1
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/logging/stackdriver/utils.go:441
```
### Recent failures:
[7/1/2020, 11:36:39 AM ci-kubernetes-e2e-gci-gce-sd-logging](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-sd-logging/1278351753644871680)
[7/1/2020, 11:05:40 AM ci-kubernetes-e2e-gci-gce-sd-logging](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-sd-logging/1278343953086681088)
[7/1/2020, 10:34:13 AM ci-kubernetes-e2e-gci-gce-sd-logging](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-sd-logging/1278335899309969416)
[7/1/2020, 10:02:40 AM ci-kubernetes-e2e-gci-gce-sd-logging](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-sd-logging/1278328098126827522)
[7/1/2020, 9:31:50 AM ci-kubernetes-e2e-gci-gce-sd-logging](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-sd-logging/1278320296067076098)

/sig instrumentation

### PR DESCRIPTION
**Pull request by erain**
Signed-off-by: Yu Yi <yiyu@google.com>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Clean up stackdriver logging e2e test which is unmaintained and unset. (see related issue)

**Which issue(s) this PR fixes**:

Fixes #92731 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by oomichi** [comment]
According to https://github.com/kubernetes/kubernetes/issues/92731#issuecomment-697619602 it is fine to remove the module.

/lgtm

**Comment by erain** [comment]
Thanks @oomichi !

@brancz could you help approve this one PR as well?

**Comment by BenTheElder** [comment]
I agree in principle
/approve
If you're familiar, I'd love a comment outlining what coverage if any we think we lose here of *kubernetes*, so we can look at adding a more general test hitting these API(s) etc.

**Comment by erain** [comment]
Thanks @BenTheElder . I guess we loose the Cloud Logging (a.k.a Stackdriver) agents' coverage mainly. 

There are actually some work WIP in fluent bit and we may add test for using fluent bit talking to Cloud Logging later.

**Comment by BenTheElder** [comment]
Ack. Reading through it again I agree. If we need coverage of that in the future we should probably do it out of tree anyhow...
Thanks.

**Comment by ehashman** [comment]
Woohoo!

**Pull request merged**
