### PR TITLE
kubelet add network-driver option

### LINKED ISSUE #26137: whether kubelet should add a network-mode flag
FYI. I am thinking about this recently when I am integrating kubernetes 1.2 with docker 1.10, and also some docker network plugins. I think after docker provides `docker network` command, `--net` option is not just `none, bridge, host, container, default`. Some docker network plugins may create other meaningful network name. I am not sure whether kubelet should support this case, but I can it's indeed necessary in some use cases. @dchen1107 @Random-Liu WDYT?

### PR DESCRIPTION
**Pull request by adohe-zz**
fixes #26137 
@thockin I just add the network-driver option, ptal.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/26537)

### CODE REVIEW

**Comment by dchen1107** [comment]
I can see the value of having this feature so that the user currently using docker network model won't be forced to switch Kubernetes default model. But I am not comfortable to take this pr especially we are working on the design of Kubernetes network plugin with new CRI (#28667). 

cc/ @thockin

**Comment by AdoHe** [comment]
@thockin ptal.

**Comment by thockin** [comment]
I just wanted to reply that I don't think I will have time to properly review this before the code freeze.  I just want to set expectations.

**Comment by AdoHe** [comment]
@thockin it's ok, this seems not like that necessary if we are going to using new CRI.

**Comment by thockin** [comment]
I would like to see CRI offer a docker-native network mode, but yeah, this is not the way to achieve that. :)

**Pull request closed without merging**
