### PR TITLE
Stop panic in govet levee under golang 1.19

### PR DESCRIPTION
**Pull request by dims**
Related to https://github.com/kubernetes/kubernetes/issues/111452

In this PR, we just ensure that if someone runs ./hack/verify-govet-levee.sh we do not fail/panic. Thanks to suggestion @timothy-king at https://github.com/golang/go/issues/54086#issuecomment-1204589970

Tested with golang 1.19 GA locally

```
[dims@dims-m1-7728 21:56] ~/go/src/k8s.io/kubernetes ⟩ hack/verify-govet-levee.sh
NOTE: /Users/dims/go/src/k8s.io/kubernetes/hack/verify-govet.sh has been replaced by 'make vet'

The equivalent of this invocation is:
    make vet WHAT='-vettool=/Users/dims/go/src/k8s.io/kubernetes/_output/local/bin/levee -config=/Users/dims/go/src/k8s.io/kubernetes/hack/testdata/levee/levee-config.yaml'


+++ [0803 21:56:23] Building go targets for darwin/arm64
    k8s.io/kubernetes/hack/make-rules/helpers/go2make (non-static)
+++ [0803 21:56:29] Building go targets for darwin/arm64
    k8s.io/code-generator/cmd/prerelease-lifecycle-gen (non-static)
+++ [0803 21:56:30] Generating prerelease lifecycle code for       26 targets
+++ [0803 21:56:32] Building go targets for darwin/arm64
    k8s.io/code-generator/cmd/deepcopy-gen (non-static)
+++ [0803 21:56:34] Generating deepcopy code for      241 targets
+++ [0803 21:56:38] Building go targets for darwin/arm64
    k8s.io/code-generator/cmd/defaulter-gen (non-static)
+++ [0803 21:56:39] Generating defaulter code for       94 targets
+++ [0803 21:56:43] Building go targets for darwin/arm64
    k8s.io/code-generator/cmd/conversion-gen (non-static)
+++ [0803 21:56:44] Generating conversion code for      131 targets
+++ [0803 21:56:57] Building go targets for darwin/arm64
    k8s.io/kube-openapi/cmd/openapi-gen (non-static)
+++ [0803 21:56:58] Generating openapi code for KUBE
+++ [0803 21:57:07] Generating openapi code for AGGREGATOR
+++ [0803 21:57:07] Generating openapi code for APIEXTENSIONS
+++ [0803 21:57:08] Generating openapi code for CODEGEN
+++ [0803 21:57:08] Generating openapi code for SAMPLEAPISERVER
  1 run lint-dependencies and follow directions
# sync/atomic
unexpected type received: *types.TypeParam T; please report this issue
unexpected type received: *types.TypeParam T; please report this issue
unexpected type received: *types.TypeParam T; please report this issue
unexpected type received: *types.TypeParam T; please report this issue
# crypto/elliptic
unexpected type received: *types.TypeParam Point; please report this issue
```

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MadhavJivrajani** [comment]
<!DOCTYPE html>

/test pull-kubernetes-e2e-kind
--


<br class="Apple-interchange-newline">

**Comment by aojea** [comment]
👌👌👌

**Pull request merged**
