### PR TITLE
remove alpha toleration forgiveness support for not-ready/unreachable

### PR DESCRIPTION
**Pull request by shivnagarajan**
**What this PR does / why we need it**:

:wave: Am new here 😄 

https://github.com/kubernetes/kubernetes/pull/51266

added handling in the lifecycle controller to ensure that if a node is tainted with the alpha taints for not-ready and unreachable these would get `fixed` up to the new `non-alpha` ones. Specifically this means we would replace 

`"node.alpha.kubernetes.io/notReady"` with `"node.kubernetes.io/not-ready"`

and

`"node.alpha.kubernetes.io/unreachable"` with `"node.kubernetes.io/unreachable"`

This allows nodes that were previously tainted to be fixed up correctly.

The admission side of things currently checks if a pod tolerates either of these and if not present adds the default tolerations.

https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/defaulttolerationseconds/admission.go#L101-L120

In the existing tests for admission in `defaulttolerationseconds`

https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/defaulttolerationseconds/admission_test.go#L67-L197

the tests validate that if alpha tolerations exist the new tolerations are added. Unfortunately, the tests validate that default tolerations are added (which means that even if non-default tolerations for the alpha labels existed, default tolerations get added for the new labels and the tests pass).

Since these deprecated tolerations need no longer be supported, it is better to completely remove support for them. This change completely removes all references to DeprecatedTaintNodeUnreachable and DeprecatedTaintNodeNotReady. Currently the way the code works default tolerations are added for the acceptable tolerations, completely ignoring the existence of the deprecated value for the tolerations.

To remove confusion, and based on previous comments in the code, this change removes all of the handling for the deprecated tolerations altogether. This follows the deprecation policy outlined in https://kubernetes.io/docs/reference/using-api/deprecation-policy/.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
As per deprecation policy in https://kubernetes.io/docs/reference/using-api/deprecation-policy/ 
the taints "node.alpha.kubernetes.io/notReady" and "node.alpha.kubernetes.io/unreachable".  are no
longer supported or adjusted. These uses should be replaced with "node.kubernetes.io/not-ready" 
and "node.kubernetes.io/unreachable" respectively instead.

```

### CODE REVIEW

**Comment by shivnagarajan** [comment]
All the failing tests seem to be because of test-infrastructure timeouts.

/retest

**Comment by shivnagarajan** [comment]
@deads2k k8s-bot automatically suggested you for review on this PR. Let me know if you think I should ping someone else?

Thanks in advance.

**Comment by shivnagarajan** [comment]
I've rebased these changes against current master. 

/cc @k8s-ci-robot

**Comment by shivnagarajan** [comment]
flaky test

/retest

**Comment by shivnagarajan** [comment]
/cc @hzxuzhonghu 

I noticed that you have most recently contributed to the defaultTolerationSeconds admission code. 

Would be great to hear your feedback on this proposed change.

Thanks

**Comment by shivnagarajan** [comment]
/retest 

flaky test I believe

**Comment by hzxuzhonghu** [comment]
`DeprecatedTaintNodeNotReady ` is deprecated in 1.9, I think it's time to remove it now according to https://kubernetes.io/docs/reference/using-api/deprecation-policy/

**Comment by shivnagarajan** [comment]
Cool, I can try and rework this and remove the deprecated taint code altogether. Thanks @hzxuzhonghu

**Comment by shivnagarajan** [comment]
Based on suggestions here, I've reworked this change to completely remove all references to `DeprecatedTaintNodeUnreachable` and `DeprecatedTaintNodeNotReady`. Currently the way the code works default tolerations are added for the acceptable tolerations, completely ignoring the existence of the deprecated value for the tolerations. 

To remove confusion, and based on previous comments in the code, this change removes all of the handling for the deprecated tolerations altogether. This follows the deprecation policy outlined in https://kubernetes.io/docs/reference/using-api/deprecation-policy/. 



@hzxuzhonghu PTAL

**Comment by hzxuzhonghu** [comment]
please add a release note, otherwise lgtm

**Comment by shivnagarajan** [comment]
I'll add a release note.

**Comment by shivnagarajan** [comment]
@hzxuzhonghu  I have added an appropriate release note about this. PTAL

Do let me know if I need to ping anyone else or make any other changes.

**Comment by hzxuzhonghu** [comment]
@kubernetes/sig-scheduling-pr-reviews ptal

**Comment by yastij** [comment]
This mostly lgtm
/cc @resouer

**Review by resouer — APPROVED** [review]
/lgtm

As we have maintained this compatibility for 3 releases (1.9, 1.10, 1.11)

I will request final decision from @liggitt @deads2k, in case of any extra announcement/docs are needed.

**Comment by shivnagarajan** [comment]
@deads2k @derekwaynecarr 

👋 k8s ci suggests either of you as final approvers as listed OWNERS here.

**Comment by yastij** [comment]
cc @kubernetes/api-approvers can you take a look ?

**Comment by shivnagarajan** [comment]
rebased to latest master

**Comment by bgrant0607** [comment]
@yastij @bsalamat Is this still needed, or can it be closed?

**Comment by shivnagarajan** [comment]
I think we can close this. Its been too long, and it is less relevant now I suppose, since this refers to alpha tolerations that were dropped a long time ago.

**Comment by k82cn** [comment]
This's still necessary to remove deprecated (alpha) taint key: depreciated at 1.9, it's 1.14 now.

We have two deprecated taint key here: `DeprecatedTaintNodeNotReady = "node.alpha.kubernetes.io/notReady"` and `DeprecatedTaintNodeUnreachable = "node.alpha.kubernetes.io/unreachable"`; and we removed `alpha` from the key to avoid backward compatibility. It's time to remove them after 5 releases :)

**Comment by shivnagarajan** [comment]
I can put together a PR to remove those deprecated taint values

**Pull request closed without merging**
