### PR TITLE
Fix mungedocs TOC generation for duplicate headers

### PR DESCRIPTION
**Pull request by timstclair**
Fix TOC links in the presence duplicate headers, such as the downloads links in the CHANGELOG (previously all downloads went to the latest version).

### CODE REVIEW

**Comment by david-mcmahon** [comment]
LGTM.  Thanks!

**Comment by timstclair** [comment]
Rebased. Reapplying LGTM.

**Comment by timstclair** [comment]
Rebased. Reapplying LGTM.

**Comment by timstclair** [comment]
@k8s-bot e2e test this issue #27524

**Comment by timstclair** [comment]
@k8s-bot e2e test this issue https://github.com/kubernetes/kubernetes/issues/28641

**Comment by fejta** [comment]
Manually merging for @krousey

**Pull request merged**
