### PR TITLE
improve kubectl completion help

### PR DESCRIPTION
**Pull request by xlgao-zju**
**What this PR does / why we need it**:
Add note that 'bash-completion' is required on Linux too.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Just like what we did in #64361

**Special notes for your reviewer**:
cc @neolit123

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xlgao-zju** [comment]
/assgin @neolit123 
Since you have reviewed #64361

**Comment by neolit123** [comment]
@xlgao-zju 
thanks. i think the change is appropriate, given the previous similar commit for kubeadm.

@kubernetes/sig-cli-pr-reviews

**Comment by xlgao-zju** [comment]
/assign @derekwaynecarr
/assign @rootfs
Since the GitHub suggested you.

**Comment by neolit123** [comment]
/lgtm
bump for @kubernetes/sig-cli-pr-reviews

**Review by dixudx — APPROVED** [review]
/lgtm

**Pull request merged**
