### PR TITLE
Remove duplicate judgment logic 'utilfeature.DefaultMutableFeatureGate.SetFormMap

### PR DESCRIPTION
**Pull request by wawa0210**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

/kind cleanup

**What this PR does / why we need it**:
In this initialization code, DefaultMutableFeatureGate has been assigned, and the assignment here seems redundant

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L151

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Remove duplicate judgment logic 'utilfeature.DefaultMutableFeatureGate.SetFormMap when kubelet init
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
this was added in https://github.com/kubernetes/kubernetes/pull/46254/files#diff-e0160f895346669c2e4495acfd858ea7R223

I'm reasonably sure this is required because the feature gates loaded from the config file might not match the CLI-specified feature gates. I'll let @mtaufen verify.

**Comment by mtaufen** [comment]
This assignment applies it from the config, which overrides the default values.
Since `Run`, which calls `run`, is public, we don't have any guarantee that the feature gates have been updated based on the config yet, so we need to do it here before validating the config.

**Comment by mtaufen** [comment]
I think this may have been defensive coding, but we know that other packages like kubemark call into public functions in this package, and we'd need to audit very carefully before removing this so that we don't break anything that hasn't also taken care to set the feature gates out-of-band.

**Comment by wawa0210** [comment]
> I think this may have been defensive coding, but we know that other packages like kubemark call into public functions in this package, and we'd need to audit very carefully before removing this so that we don't break anything that hasn't also taken care to set the feature gates out-of-band.

thanks your replay, i will close this pr

**Pull request closed without merging**
