### PR TITLE
Remove stubs from docs/

### LINKED ISSUE #37827: Move docs: design, proposals, devel to community repo
- [x] Move docs/design, docs/design, and docs/proposals to the community repo under [`contributors/`.](https://github.com/kubernetes/community/tree/master/contributors) and combine design and proposals docs under design-proposals directory

- [x] Freeze PRs on the moved directories (cc/ @grodrigues3)

- [x] Make announcement about freeze

- [x] Update the files in those directories in this repo to contain a forwarding link to the new location of the files using a script. _Note: There was a script used during the docs move for kubernetes.github.io. If you know where it is, it would be helpful. :)_

- [x] Make announcement on updated locations of those files

- [ ] Update any links that point to the moved files

- [ ] Delete the moved docs from the kubernetes repo

- [x] Remove freeze
 

cc/ @kubernetes/contributor-experience

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
Removes the remaining stubs from `docs/` so that all that's left is auto generated.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #37827

**Special notes for your reviewer**:
This is pending https://github.com/kubernetes/test-infra/pull/3175 as that will allow this to auto merge.

**Release note**:

```release-note
NONE
```

/assign @thockin

### CODE REVIEW

**Comment by cblecker** [comment]
Also, PTAL @kubernetes/sig-docs-maintainers @chenopis. Thank you!

**Comment by chenopis** [comment]
@cblecker It looks like we have some links in k8s.io that point to some of these docs. Are they being relocated to a different repo or directory so that I can update the links?

**Comment by ahmetb** [comment]
I think we have many links from repos like `kubernetes/examples` that also link to these pages. Maybe first we can try cleaning up references to docs/ in other places, then actually come and delete these?

**Comment by cblecker** [comment]
Everything under this PR is a stub that links somewhere else:
- `docs/design/` -> https://git.k8s.io/community/contributors/design-proposals/
- `docs/devel/` -> https://git.k8s.io/community/contributors/devel/
- `docs/proposals/` -> https://git.k8s.io/community/contributors/design-proposals/

I agree with @ahmetb that we should clean up any links we can find in the docs before merging this.

**Comment by thockin** [comment]
This needs an associated issue and a `closes #12345` in the FIRST COMMENT, or it can not be approved.

**Comment by cblecker** [comment]
@thockin Done. Would you rather merge this manually? Or would you rather we remove the blocked paths (https://github.com/kubernetes/test-infra/pull/3175) so that this can auto merge. I don't think we need to block these paths anymore if they don't exist.

**Comment by thockin** [comment]
@chenopis @devin-donnelly @bgrant0607 Any reason not to merge this?

**Comment by thockin** [comment]
Fire in the hole!

**Comment by chenopis** [comment]
Is it too late? /lgtm =)

**Comment by ahmetb** [comment]
Hah this just impacted me. I landed to https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/network-policy.md from a Google Seach query, and I've been following the redirection stub for the past few weeks, now it's broken. I suppose we’ll wait for the search engines to catch up.

**Comment by cblecker** [comment]
@ahmetb What was the query (for the record)?

**Comment by ahmetb** [comment]
network policy design md
lol

**Comment by ahmetb** [comment]
Hit another one, was searching "mesos-style.md", this came up first: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/mesos-style.md

**Pull request merged**
