### PR TITLE
Build kubectl on Darwin with CGO enabled

### LINKED ISSUE #23130: kubectl does not respect osx VPN dns
I have a feeling this is more related to Go than kubernetes specifically but the `CGO_ENABLED=0` builds cause this problem to occur.

```
➜  amd64 ./kubectl get po
Unable to connect to the server: dial tcp: lookup kube-apiserver01.internal: no such host
```

When rebuilding off the v1.2.0 tag with `CGO_ENABLED=1` in the `hack/lib/golang.sh` DNS works as expected:

```
➜  kubernetes git:(5cb86ee) ./_output/local/bin/darwin/amd64/kubectl get po
NAME                            READY     STATUS    RESTARTS   AGE
pod123   3/3       Running   0          19h
```

You can also reproduce that the go dns implementation is lacking with the `CGO_ENABLED=1` bin via env variables:

```
➜  kubernetes git:(5cb86ee) GODEBUG=netdns=go ./_output/local/bin/darwin/amd64/kubectl get po
Unable to connect to the server: dial tcp: lookup kube-apiserver01.internal on 8.8.8.8:53: no such host
```

As expected, it isn't an option to force cgo resolution via runtime env variables for the `CGO_ENABLED=0` bin:

```
➜  amd64 GODEBUG=netdns=cgo ./kubectl get po
Unable to connect to the server: dial tcp: lookup prod-kube-apiserver01.nyc3.internal.digitalocean.com: no such host
```

### PR DESCRIPTION
**Pull request by stepanstipl**
**What this PR does / why we need it**:
When building kubectl on darwin, CGO should be enabled.

This has following two major benefits:
- kubectl will use macOS native DNS resolver - this causes issues
  typically with VPNs and/or when domain specific DNS servers are set
- Custom CA certificates in keychain will be picked up - this needs go
  1.7 (golang/go#14514)

**Which issue this PR fixes**
fixes #23130 (when kubectl is built locally on darwin)

**Special notes for your reviewer**:
I'm not familiar enough with release process for kubernetes, but I believe all the binaries for macOs are cross-compiled currently. I think it would be more comfortable for users to have kubectl for mac with CGO enabled (I have come across issues with DNS and certs couple of times, especially in environments where you use VPNs and internal CAs). Do you think it would be interesting to look into something like https://github.com/karalabe/xgo ? That would allow cross-compile of kubectl with CGO enabled.

**Release note**:

```
kubectl will use CGO when building natively on darwin
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35200)

### CODE REVIEW

**Comment by jbeda** [comment]
I'm not sure that this really fixes the issue.  While it will work as we build natively on darwin, most of our build/release process is structured to be built and released form Linux.  Unless we start building on macOS for official releases this'll create a strange situation where some custom non-official binaries will have features that other binaries don't.

**Comment by jbeda** [comment]
cc @ixdy @mikedanese

**Comment by stepanstipl** [comment]
@jbeda I was thinking if it would make sense to look into something like xgo? Or do you plan to build natively for official releases in future?

Btw. looks like since 3193174142b0b7dfb1fad4938659d9d8be96d76d (at least on my setup with go 1.7.3 and macOS Sierra) kubectl built natively won't start

**Comment by ixdy** [comment]
cc @david-mcmahon 

I'm not entirely sure yet how cross-compilation will work in Bazel.

We don't have any plans at this time to do native builds for official releases.

@stepanstipl can you elaborate on "kubectl built natively won't start"? Maybe file a separate issue for that?

**Comment by stepanstipl** [comment]
@ixdy master will build fine, but when you actually run kubectl it won't do anything, nor print anything.. just hangs, I'll try to look into it a bit more and eventually open separate issue.

I would still be interested in getting kubectl built with CGO enabled for macOS for official release (currently we have to distribute custom version of it across majority of our users, as without CGO it does not play nicely with vpn (dns) and system certificates

**Comment by luxas** [comment]
Everything official should be cross-compiled. There is no other way.

I think you mostly ran into that we used go1.6 for v1.4.0, which breaks totally on Sierra.

All other arches are using Go's native resolver; if there's a problem with that, file an issue against golang/go.

**Comment by stepanstipl** [comment]
@luxas Is there some downside of compiling kubectl with CGO enabled?

Cross-compilation is not a showstopper for this, it can still be done (and looks like it's being done for some ppc & arm platforms). Actually I've played around a bit with xgo and can get kubectl co compile with CGO enabled inside linux based container.

Problems are:
- not respecting macOS standard DNS resolution mechanism
- not respecting system certificates

There's couple of tickets around this in golang itself, but I believe that it's not a golang's problem as such, as you have option of using CGO and given kubectl is application user interacts with directly I think that the user experience is important and that it should behave according to given system standards.

**Comment by ixdy** [comment]
x-ref https://github.com/kubernetes/release/issues/469

**Pull request closed without merging**
