### PR TITLE
make kubectl create --edit iterate

### PR DESCRIPTION
**Pull request by mengqiy**
`kubectl create --edit` is broken after #36148 merged.
`kubectl create --edit` will fail when a manifest that contains multiple resources.
I guess the root cause is that dynamic typer doesn't support a list of resources currently.

This PR makes `kubectl create --edit` iterate again as `kubectl create`.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36764)

### CODE REVIEW

**Comment by pwittrock** [comment]
*[pkg/kubectl/cmd/edit.go, line 335 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36764#-KWZQUu_nfF_jXUSo25W:-KWZQUu_nfF_jXUSo25X:b-sad8te) ([raw file](https://github.com/kubernetes/kubernetes/blob/2c7d64fac56a26dee5cd0092dc5a69879e977caa/pkg/kubectl/cmd/edit.go#L335)):*
> ```Go
> 	switch editMode {
> 	case NormalEditMode:
> 		return editFn(nil, nil)
> ```

Add comments explaining the difference between these explaining why we use visit for the createmode.

// If doing normal edit we cannot use Visit because we need to edit a list for convenience.
// If doing an edit before created, we don't want a list and instead want the normal create behavior.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36764)*

**Comment by ymqytw** [comment]
Updated. PTAL

**Comment by pwittrock** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/36764)*

**Comment by ymqytw** [comment]
@pwittrock Need `v1.5` milestone label and remove `do-not-merge` label.

**Comment by pwittrock** [comment]
@saad-ali FYI this is fixing a bug in kubectl that was introduced in 1.5

**Comment by pwittrock** [comment]
Also, most of the changes you see in GH are whitespace

**Comment by liggitt** [comment]
Why don't we want a list when editing from create?

**Comment by liggitt** [comment]
cc @smarterclayton @kargakis

**Comment by liggitt** [comment]
We should be able to handle a list here… iterating in this mode doesn't seem right

**Comment by liggitt** [comment]
Tagging until we resolve whether this is the right fix

**Comment by ymqytw** [comment]
@liggitt There are 2 reasons:
1) We want to make `create --edit` consist with normal `create`which is iterating. i.e. normal `create` will create resources one by one before a failure occurs.
2) We want to make `create --edit` use the same `typer (dynamic typer)` as normal `create` which is different from `edit`.

**Comment by liggitt** [comment]
I see edit mode isn't new... can you open up a follow up issue for the typer issue? It should be able to handle a list

**Comment by saad-ali** [comment]
> @saad-ali FYI this is fixing a bug in kubectl that was introduced in 1.5

Ack. Thanks.

**Comment by ymqytw** [comment]
> can you open up a follow up issue for the typer issue? It should be able to handle a list

Opened #36968

**Pull request merged**
