### PR TITLE
Fix the log for current and desired number of replicas in sample controller

### LINKED ISSUE #129012: The current and desired number of replicas in the sample controller is incorrect.
### What happened?

The current and desired number of replicas in the sample controller is incorrect.

`Say, we have the replicas of the crd start with 1 and change to 2.`

we got this:
`"Update deployment resource" objectRef="default/example-foo" currentReplicas=2 desiredReplicas=1`

image

### What did you expect to happen?

When updating the replicas of the crd and the log level set to 4, the log should show `current 1, desired 2`.

### How can we reproduce it (as minimally and precisely as possible)?

- Run sample controller and set log level to 4
- Apply crd.yaml and `example-foo.yaml` file in artifacts folder
- Change the replicas of `example-foo.yaml` from 1 to 2 and apply the changes

### Anything else we need to know?

_No response_

### Kubernetes version
<details>
```console
$ kubectl version
v1.28.1
```

</details>

### Cloud provider

<details>
Local cluster
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by RogerTaylor130**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR fixes the logs for the incorrect current and desired number of replicas when updating CRD's replicas attribute.

`Say, we have the replicas of the crd start with 1 and change to 2.`
When updating the replicas of the crd and the log level set to 4, the log should show `current 1, desired 2`. But we got this:
`"Update deployment resource" objectRef="default/example-foo" currentReplicas=2 desiredReplicas=1`
#### Which issue(s) this PR fixes:

Fixes #129012

#### Does this PR introduce a user-facing change?
NONE

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by mengjiao-liu — COMMENTED** [review]
/ok-to-test
/area logging
/sig apps
/remove-sig api-machinery

**Comment by RogerTaylor130** [comment]
Just wondering if there will be anyone here to review this PR? Should I do something or just leave it here? 😄

**Comment by munnerz** [comment]
Thank you! 😊

/approve
/lgtm

**Pull request merged**
