### PR TITLE
Add ClusterUpgrade tests

### PR DESCRIPTION
**Pull request by ikehz**
This is a manual cherrypick of half of #22962.

@eparis, @bgrant0607, how do you all want to do this?

cc @spxtr as reviewer of #22962.

### CODE REVIEW

**Comment by eparis** [comment]
re-assigning to @roberthbailey since he owns 1.2 now. I added both the 1.2 milestone and the cp-candidate label to THIS PR. I'll leave it up to him to figure out exactly how he wants to handle it.

**Comment by roberthbailey** [comment]
@ihmccreery It would be easier if you'd split the original PR into 2 PRs (you split it into two commits but the cherry pick tool works on PRs rather than commits).

**Comment by roberthbailey** [comment]
I think I've added the right labels for this to get merged into the release branch. We'll see if I've appeased the merge bot.

**Comment by eparis** [comment]
The bot won't touch it because jenkins unit tests failed   :-(   but the labels look good!

**Comment by zmerlynn** [comment]
Yeah, and I haven't found an appropriate flake for this one.

**Comment by zmerlynn** [comment]
@k8s-bot unit test this, issue #24207.

**Comment by ihmccreery** [comment]
> @ihmccreery It would be easier if you'd split the original PR into 2 PRs (you split it into two commits but the cherry pick tool works on PRs rather than commits).

Ack.

**Comment by ihmccreery** [comment]
@roberthbailey Why did you add `release-note`?  I disagree that this deserves a release note.

**Comment by roberthbailey** [comment]
All cherry picks require a release note.

**Pull request merged**
