### PR TITLE
Update Error logging for Pod+PodStatus resource lifecycle test 

### LINKED ISSUE #96819: Update Error logging for Pod+PodStatus resource lifecycle test
**What is this issue addressing?**
[Comment](https://github.com/kubernetes/kubernetes/pull/96485#issuecomment-732335344
) in #96485 require more useful logging message 

**Requiered outcome:**
Improve log messages

### PR DESCRIPTION
**Pull request by riaankleinhans**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it:**
This is PR is in response to  the comments in [#96485](https://github.com/kubernetes/kubernetes/pull/96485#issuecomment-732335344) 
- was the watch event not for a Pod? - addressed in Line 498
- was the Pod missing the test-pod-static: true label? addressed in Line 942
- was the Pod's Phase not PodRunning? - addressed in Line 942 

**Which issue(s) this PR fixes:**
Fixes #96819

**Special notes for your reviewer:**
This PR will clarify logging of errors

**Does this PR introduce a user-facing change?:**
```
NONE

```

**Release note:**
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:**
```
NONE

```

/sig testing
/sig architecture

### CODE REVIEW

**Comment by heyste** [comment]
/test pull-kubernetes-e2e-gce-ubuntu-containerd
flake
```
[sig-network] Conntrack should be able to preserve UDP traffic when server pod cycles for a NodePort service
FAIL: Failed to connect to backend 1
```

**Comment by knabben** [comment]
/lgtm

this can help debug the failures on the conformance suite.

**Pull request merged**
