### PR TITLE
Make JuJu charm Python files executable.

### LINKED ISSUE #8252: changing permissions broke the kubernetes-master charm
We tried to deploy the kubernetes Juju bundle and found that the commit f416289a85c9e55fffb6f84bd85b7298733737db changed the permissions on some key python files that broke the deployment of the Juju cluster.

Specifically: cluster/juju/charms/trusty/kubernetes-master/hooks/hooks.py                          100755 → 100644  

@eparis I see that the commit was largely to add a copyright header.  Was the change in permissions on purpose?  For these charms to work with Juju some files have to be executable.

### PR DESCRIPTION
**Pull request by vmarmol**
Fixes #8252.

### CODE REVIEW

**Comment by vmarmol** [comment]
@mbruzek would love if you could verify this is good :)

**Comment by vishh** [comment]
LGTM

**Comment by mbruzek** [comment]
@vmarmol This change makes too many files.  We are working on our own PR to fix this file.

**Comment by vmarmol** [comment]
Closing in favor of #8282

**Pull request closed without merging**
