### PR TITLE
api: update Service.Spec.IPFamily docs

### PR DESCRIPTION
**Pull request by danwinship**
**What type of PR is this?**
/kind cleanup
/kind documentation

**What this PR does / why we need it**:
Updates the docs on `Service.Spec.IPFamily` to be more accurate and to warn that users shouldn't rely on it other than as specifically documented (following up on discussions on the mailing list and elsewhere, which make it seem likely that we will probably change it in a future release).

**Does this PR introduce a user-facing change?**:
```release-note
Updated the API documentation for Service.Spec.IPFamily to warn that its exact
semantics will probably change before the dual-stack feature goes GA, and users
should look at ClusterIP or Endpoints, not IPFamily, to figure out if an existing
Service is IPv4, IPv6, or dual-stack.
```

/sig network
/priority important-soon

/assign @thockin

### CODE REVIEW

**Comment by aojea** [comment]
/label api-review
/assign @liggitt 
for api review process

**Comment by danwinship** [comment]
/remove-label api-review
it doesn't need api-review; there is no API change, just a doc change

**Comment by liggitt** [comment]
I'll defer to thockin for the doc review

**Comment by danwinship** [comment]
@thockin so should this be merged, rewritten, or closed now?

**Comment by thockin** [comment]
I'm ambivalent about fixing anything related to the ipFamily model, but this seems strictly better than before, so I'll approve.

@khenidak - this will cause a rebase pain for you but it should be easy to resolve, I think?

/lgtm
/approve

**Pull request merged**
