### PR TITLE
openapi: remove postprocessing for old paths, deprecated in 1.9

### PR DESCRIPTION
**Pull request by sttts**
```release-note
The kube-apiserver OpenAPI definitions with the prefix "io.k8s.kubernetes.pkg" (deprecated since 1.9) have been removed.
```

### CODE REVIEW

**Comment by sttts** [comment]
/assign @liggitt 

This is formally an API change. Please take a look.

**Comment by liggitt** [comment]
/approve

suggest being specific in the release note about the old definition prefix that was removed

**Comment by sttts** [comment]
Made the release-notes more specific.

**Pull request merged**
