### PR TITLE
genericapiserver: cut off more dependencies – episode 6

### PR DESCRIPTION
**Pull request by sttts**
Follow-up of https://github.com/kubernetes/kubernetes/pull/40808

approved based on #40363

### CODE REVIEW

**Comment by sttts** [comment]
@k8s-bot unit test this

**Comment by sttts** [comment]
@k8s-bot unit test this issue #36351

**Comment by deads2k** [comment]
@k8s-bot unit test this

**Comment by sttts** [comment]
@k8s-bot cri e2e test this

**Pull request merged**
