### PR TITLE
Automated cherry pick of #79552: Add support for windows to AWS EBS

### PR DESCRIPTION
**Pull request by wongma7**
Cherry pick of #79552 on release-1.14.

#79552: Add support for windows to AWS EBS

### CODE REVIEW

**Comment by wongma7** [comment]
/cc @leakingtapan 
cherry-pick of aws ebs for 1.14

**Comment by wongma7** [comment]
@gnufied PTAL at this and https://github.com/kubernetes/kubernetes/pull/80500. Want to cherrypick to 1.14 as 1.15 as otherwise ebs is plain broken for windows workers.

**Comment by tpepper** [comment]
/kind feature
as per the master branch PR.  We don't backport features to the stable release branches.

**Comment by wongma7** [comment]
I think it's a bugfix also because otherwise volumes are broken on windows nodes with little indication as to why they are broken (the pod gets stuck in ContainerCreating, wait for attach times out even though the volume is clearly attached). Windows went "production-ready" in 1.14, some users will expect stateful workloads to work.

In terms of risk this code only touches what it's trying to fix, aws ebs on windows.

**Comment by tpepper** [comment]
/area provider/aws

A feature that wasn't fully enabled/tested and is broken seems to me like a feature that hasn't yet been delivered.

@kubernetes/provider-aws-misc and @kubernetes/sig-storage-pr-reviews are ya'll sure this is a valid cherry pick?

**Comment by tpepper** [comment]
I've confirmed with SIG Windows that this was a feature not included in the initial GA support, eg:
https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#storage

**Comment by tpepper** [comment]
Discussed with
/sig windows
and @kubernetes/patch-release-team and there is not support for merging this cherry pick.

**Comment by gnufied** [comment]
For posterity - since most of us who are CCed in this PR weren't part of discussion that happened with sig-windows and patch-release-team, can you post summary of why was this PR not approved for backport?

**Comment by benmoss** [comment]
I disagree with @tpepper's conclusion here. The storage drivers that were supported in the initial Windows GA were only the ones that were intentionally fixed prior to 1.14 shipping. The rest of them were left as broken as they were the day the kubelet began being compiled for Windows. They are more akin to "known bugs" than omitted features, since the code paths still allow users to attempt to mount volumes for all the other broken in-tree providers, but with a terrible user experience and no documentation stating that these features are all broken.

**Comment by gnufied** [comment]
I agree that decision to not backport this was taken in not a transparent manner. I am yet to hear an explanation about why - when this was approved by both sig-storage and sig-aws owners.

**Comment by PatrickLang** [comment]
https://kubernetes.slack.com/archives/GMER31U0P/p1565825050000700

**Comment by PatrickLang** [comment]
So at 1.14 release, there was no testing on AWS so we had no data that this was broken. AWS support wasn't listed in the 1.14 storage docs https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#storage.

The criteria given by the release team (@tpepper) was 
"From patch release team's perspective, this is a feature add, and not a candidate for cherry picking.  Of course folks assert "I tried to X and it didn't work so it's a bug."  Every non-enabled feature is a bug."

@m2 and I asserted that this was a non-enabled feature

**Comment by tpepper** [comment]
Also FTR record, I've made no decision here.  My comments continue to be about attempting to collect information to arrive at agreement.

The PR was closed by @wongma7.  It was they who had indicated "Windows went "production-ready" in 1.14, some users will expect stateful workloads to work" as justification for this being required.  Thus my question to SIG Windows on whether they intended this to work in 1.14.

**Comment by tpepper** [comment]
If there's overriding consensus that this is truly a critical bug fix, then we can move forward with it. From the patch release side reading through the documented artifacts we haven't yet seen it.

**Comment by wongma7** [comment]
Closing  again--the behavior of unsupported/partially-supported/broken volume  plugins is pretty unpleasant for users, but correcting it does not meet the bar for a "critical bug fix."

**Pull request closed without merging**
