### PR TITLE
Use Node-Problem-Detector v0.6.0 on GCI

### LINKED ISSUE #227: NPD HEAD not working on GKE
How to reproduce:

1. Create GKE cluster with version v1.10.9-gke.5 (The NPD shipped with this GKE version is using NPD v0.5.0, with log counter support. See https://github.com/kubernetes/kubernetes/pull/65342).
2. Log onto a node and verify that NPD is working fine.
3. Compile NPD at HEAD and get tarball.
4. Copy newly built NPD tarball to the node.
4. Untar NPD.
5. Run the following commands:
```
sudo systemctl stop node-problem-detector.service
sudo cp -f bin/node-problem-detector /home/kubernetes/bin/node-problem-detector
sudo systemctl start node-problem-detector.service
```
6. Verify that NPD is not working. Saw logs as follows:
```
$ sudo journalctl -u node-problem-detector.service
...
Nov 26 20:02:44 gke-npd-default-pool-17da7bcb-kb52 systemd[1]: Started Kubernetes node problem detector.
Nov 26 20:02:44 gke-npd-default-pool-17da7bcb-kb52 node-problem-detector[14438]: I1126 20:02:44.918435   14438 log_monitor.go:64] Finish parsing log monitor config file: {WatcherConfig:{Plugin:kmsg PluginConfig:map[] LogPath:/dev/kmsg Lookback:5m} BufferSize:10 Source:kernel-monitor DefaultConditions:[{Type:KernelDeadlock Stat
Nov 26 20:02:44 gke-npd-default-pool-17da7bcb-kb52 node-problem-detector[14438]: I1126 20:02:44.919043   14438 log_watchers.go:40] Use log watcher of plugin "kmsg"
Nov 26 20:02:44 gke-npd-default-pool-17da7bcb-kb52 node-problem-detector[14438]: I1126 20:02:44.919373   14438 log_monitor.go:64] Finish parsing log monitor config file: {WatcherConfig:{Plugin:journald PluginConfig:map[source:docker] LogPath:/var/log/journal Lookback:5m} BufferSize:10 Source:docker-monitor DefaultConditions:[]
Nov 26 20:02:44 gke-npd-default-pool-17da7bcb-kb52 node-problem-detector[14438]: I1126 20:02:44.919558   14438 log_watchers.go:40] Use log watcher of plugin "journald"
Nov 26 20:02:44 gke-npd-default-pool-17da7bcb-kb52 node-problem-detector[14438]: I1126 20:02:44.919812   14438 custom_plugin_monitor.go:67] Finish parsing custom plugin monitor config file: {Plugin:custom PluginGlobalConfig:{InvokeIntervalString:0xc00030b4c0 TimeoutString:0xc00030b4d0 InvokeInterval:5m0s Timeout:1m0s MaxOutput
Nov 26 20:02:44 gke-npd-default-pool-17da7bcb-kb52 node-problem-detector[14438]: panic: invalid configuration: no server found for cluster "local"
Nov 26 20:02:44 gke-npd-default-pool-17da7bcb-kb52 node-problem-detector[14438]: goroutine 1 [running]:
Nov 26 20:02:44 gke-npd-default-pool-17da7bcb-kb52 node-problem-detector[14438]: k8s.io/node-problem-detector/pkg/problemclient.NewClientOrDie(0xc0002f0f80, 0xc0002e69c0, 0xc0000405a0)
Nov 26 20:02:44 gke-npd-default-pool-17da7bcb-kb52 node-problem-detector[14438]:         /usr/local/google/home/zhenw/go/src/k8s.io/node-problem-detector/pkg/problemclient/problem_client.go:69 +0x3f7
Nov 26 20:02:44 gke-npd-default-pool-17da7bcb-kb52 node-problem-detector[14438]: main.main()
Nov 26 20:02:44 gke-npd-default-pool-17da7bcb-kb52 node-problem-detector[14438]:         /usr/local/google/home/zhenw/go/src/k8s.io/node-problem-detector/cmd/node_problem_detector.go:90 +0x302
Nov 26 20:02:44 gke-npd-default-pool-17da7bcb-kb52 systemd[1]: node-problem-detector.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 26 20:02:44 gke-npd-default-pool-17da7bcb-kb52 systemd[1]: node-problem-detector.service: Unit entered failed state.
Nov 26 20:02:44 gke-npd-default-pool-17da7bcb-kb52 systemd[1]: node-problem-detector.service: Failed with result 'exit-code'.
```

I manually tried commits in the history and found that the culprit PR is https://github.com/kubernetes/node-problem-detector/pull/187.

/cc @Random-Liu 
/cc @andyxning 
/cc @jiayingz

### PR DESCRIPTION
**Pull request by wangzhen127**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Use [Node-Problem-Detector v0.6.0](https://github.com/kubernetes/node-problem-detector/releases/tag/v0.6.0) on GCI. NPD v0.6.0 added a few more plugins to detect more node problems. It also fixed a custom plugin bug. This is part of #71526.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
This PR also updates the kubeconfig needed by NPD and fixes https://github.com/kubernetes/node-problem-detector/issues/227

**Special notes for your reviewer**:
Currently v0.5.0 is being used. 

**Does this PR introduce a user-facing change?**:

```release-note
On GCI, NPD starts to monitor kubelet, docker, containerd crashlooping, read-only filesystem and corrupt docker overlay2 issues.
```

### CODE REVIEW

**Comment by wangzhen127** [comment]
Just verified `node-problem-detector.log` in `pull-kubernetes-e2e-gke` and `pull-kubernetes-e2e-gce` and NPD is working correctly.

/assign @yguo0905

**Comment by yguo0905** [comment]
/lgtm
/hold
hold if you also want others to lgtm.

**Comment by wangzhen127** [comment]
Cherry picks are all merged. NPD v0.6.0 will be available in the following releases:
v1.10.12, v1.11.6, v1.12.4, v1.13.1, v1.14+

**Pull request merged**
