### PR TITLE
Automated cherry pick of #116134: fix: After a Node is down and take some time to get back to up again, the mount point of the evicted Pods cannot be cleaned up successfully.

### PR DESCRIPTION
**Pull request by cvvz**
Cherry pick of #116134 on release-1.27.

#116134: fix: After a Node is down and take some time to get back to up again, the mount point of the evicted Pods cannot be cleaned up successfully.

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by msau42** [comment]
/hold

There is a regression with the new reconstruction logic that this change depends on. https://github.com/kubernetes/kubernetes/issues/117745

**Comment by jsafrane** [comment]
/hold cancel

[Fix for volume reconstruction](https://github.com/kubernetes/kubernetes/pull/119363) actually depends on this fix.

**Review by xmudrii — APPROVED** [review]
As per https://github.com/kubernetes/kubernetes/pull/116134#issuecomment-1498783027, this cherry-pick is only suitable for 1.27
For RelEng:
/lgtm
/approve

**Pull request merged**
