### PR TITLE
e2e: better ginkgo progress reports

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

When a test is stuck it is useful to know where and why. [Ginkgo progress reports](https://onsi.github.io/ginkgo/#getting-visibility-into-long-running-specs) can help with that.

#### Special notes for your reviewer:

To see what the output looks like, check out https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/112352/pull-kubernetes-e2e-kind/1571158066349477888 from an earlier revision of this PR which had one test that intentionally timed out.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
/assign @aojea 

For review. We already discussed this on #sig-testing.

/assign @dims 

For the dependency approval.

**Comment by dims** [comment]
/approve
(dependency change looks good)

/assign @liggitt @thockin 
(for root OWNERS approval)

**Comment by aojea** [comment]
```
Progress Report for Ginkgo Process #16
[sig-apps] StatefulSet Basic StatefulSet functionality [StatefulSetBasic] should perform rolling updates and roll backs of template modifications with PVCs (Spec Runtime: 5m40.098s)
  test/e2e/apps/statefulset.go:292
  In [It] (Node Runtime: 5m40.005s)
    test/e2e/apps/statefulset.go:292
    At [By Step] Rolling back update in reverse ordinal order (Step Runtime: 38.787s)
      test/e2e/apps/statefulset.go:1638

    Begin Captured GinkgoWriter Output >>
      ...
      Sep 18 08:53:43.379: INFO: Waiting for Pod statefulset-478/ss-0 to have revision ss-bcccf8464 update revision ss-774f5f65f
      Sep 18 08:53:43.379: INFO: Waiting for Pod statefulset-478/ss-1 to have revision ss-bcccf8464 update revision ss-774f5f65f
      Sep 18 08:53:43.379: INFO: Waiting for Pod statefulset-478/ss-2 to have revision ss-bcccf8464 update revision ss-774f5f65f
      Sep 18 08:53:53.400: INFO: Waiting for StatefulSet statefulset-478/ss to complete update
      Sep 18 08:53:53.400: INFO: Waiting for Pod statefulset-478/ss-0 to have revision ss-bcccf8464 update revision ss-774f5f65f
      Sep 18 08:53:53.400: INFO: Waiting for Pod statefulset-478/ss-1 to have revision ss-bcccf8464 update revision ss-774f5f65f
      Sep 18 08:53:53.400: INFO: Waiting for Pod statefulset-478/ss-2 to have revision ss-bcccf8464 update revision ss-774f5f65f
      Sep 18 08:54:03.385: INFO: Waiting for StatefulSet statefulset-478/ss to complete update
      Sep 18 08:54:03.385: INFO: Waiting for Pod statefulset-478/ss-0 to have revision ss-bcccf8464 update revision ss-774f5f65f
      Sep 18 08:54:03.385: INFO: Waiting for Pod statefulset-478/ss-1 to have revision ss-bcccf8464 update revision ss-774f5f65f
    << End Captured GinkgoWriter Output

    Spec Goroutine
    goroutine 3514 [select]
      k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.WaitForWithContext({0x7b39e28, 0xc000082078}, 0xc003600a38, 0x2e9e2ea?)
        vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:660
      k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.poll({0x7b39e28, 0xc000082078}, 0x48?, 0x2e9ce85?, 0x28?)
        vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:596
      k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.PollImmediateWithContext({0x7b39e28, 0xc000082078}, 0x2e9ce85?, 0xc0028e3c98?, 0x250a967?)
        vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:528
      k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.PollImmediate(0xc0023d4df8?, 0x0?, 0x8bb2c97000?)
        vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:514
      k8s.io/kubernetes/test/e2e/framework/statefulset.WaitForState({0x7b74da8?, 0xc0006af680}, 0xc001e2f900, 0xc0023d4df8)
        test/e2e/framework/statefulset/wait.go:64
    > k8s.io/kubernetes/test/e2e/apps.waitForRollingUpdate({0x7b74da8, 0xc0006af680}, 0xc001e2f900)
        test/e2e/apps/wait.go:124
          | 		set.Spec.UpdateStrategy.Type)
          | }
          > e2estatefulset.WaitForState(c, set, func(set2 *appsv1.StatefulSet, pods2 *v1.PodList) (bool, error) {
          | 	set = set2
          | 	pods = pods2
    > k8s.io/kubernetes/test/e2e/apps.rollbackTest({0x7b74da8, 0xc0006af680}, {0xc0032bd9a0, 0xf}, 0xc001e2f400)
        test/e2e/apps/statefulset.go:1643
          | restorePodHTTPProbe(ss, &pods.Items[1])
          | ss, _ = e2estatefulset.WaitForPodReady(c, ss, pods.Items[1].Name)
          > ss, pods = waitForRollingUpdate(c, ss)
          | framework.ExpectEqual(ss.Status.CurrentRevision, priorRevision, fmt.Sprintf("StatefulSet %s/%s current revision %s does not equal prior revision %s on rollback completion",
          | 	ss.Namespace,
    > k8s.io/kubernetes/test/e2e/apps.glob..func10.2.6()
        test/e2e/apps/statefulset.go:296
          | 	e2epv.SkipIfNoDefaultStorageClass(c)
          | 	*(ss.Spec.Replicas) = 3
          > 	rollbackTest(c, ns, ss)
          | })
          | 
      k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func2()
        vendor/github.com/onsi/ginkgo/v2/internal/suite.go:685
      k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/v2/internal.(*Suite).runNode
        vendor/github.com/onsi/ginkgo/v2/internal/suite.go:673
```

/lgtm

@pohly @onsi this is really cool
Thanks

**Pull request merged**
