### PR TITLE
Remove generally available feature gate HPAContainerMetrics

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

HPAContainerMetrics GA: v1.30

A follow-up of https://github.com/kubernetes/kubernetes/pull/123482

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Removed generally available feature gate `HPAContainerMetrics`
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve

/cc @gjtempleton

**Review by hashim21223445 — APPROVED** [review]

**Comment by carlory** [comment]
/cc @liggitt 

Could you take a look if you have time?

It was approved by @sanposhiho but is removed due to rebasing uptream code.

**Comment by tengqm** [comment]
Please do propose a change to the website for this removal.

**Comment by carlory** [comment]
cc @tengqm https://github.com/kubernetes/website/pull/47625

**Pull request merged**
