### PR TITLE
Return information about which int tests failed in the summary - followup

### PR DESCRIPTION
**Pull request by soltysh**
@stevekuznetsov you asked about it in https://github.com/kubernetes/kubernetes/pull/59486#discussion_r169351176

/assign @stevekuznetsov 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
/retest
/approve

LGTM to Steve

**Comment by deads2k** [comment]
@soltysh what have you done to the CLA? Yours normally says yes.

**Comment by stevekuznetsov** [comment]
@deads2k it's a test-infra bugaboo with the labels on this one by the look

**Comment by stevekuznetsov** [comment]
@deads2k the bots that add the label run off of the CLA context being set in the status for the PR. That's not going to be re-triggered at this point so I think the redress is adding the human approved CLA label -- can you do that?

**Comment by stevekuznetsov** [comment]
Or @soltysh rebase on `master` and retrigger the flow

**Comment by cblecker** [comment]
Adding CLA label manually. CLA bot is reporting green.

**Pull request merged**
