### PR TITLE
[WIP] Add failing test for kubectl explain

### PR DESCRIPTION
**Pull request by tcharding**
**What this PR does / why we need it**:

Adds test to catch missing resource documentation. See #50248 for explanation of issue.

**Special notes for your reviewer**:

I discovered this bug, raised an issue and implemented the test but I am new to k8s dev. If there is a better way to have gone about this please do not hesitate to nudge me in the right direction.

thanks

/sig cli
/release-note-none

### CODE REVIEW

**Comment by tcharding** [comment]
Tests on this PR fail by design.

**Comment by thockin** [comment]
We can't checking a change that breaks tests.  Where is the fix?

**Comment by tcharding** [comment]
@thockin no worries. I thought a [WIP] labeled PR could leave the code in a non-sane state since it was not a merge candidate. Is this understanding incorrect?

I have an idea for a fix, will see what I can put together.

thanks

**Comment by tcharding** [comment]
Some more information. An example of the types of errors this issue is tracking;
```
kubectl explain cluster
error: API version: federation/v1beta1 is not supported by the server. Use one of: [authentication.k8s.io/v1 authentication.k8s.io/v1beta1 authorization.k8s.io/v1 authorization.k8s.io/v1beta1 autoscaling/v1 autoscaling/v2alpha1 batch/v1 batch/v2alpha1 certificates.k8s.io/v1beta1 extensions/v1beta1 policy/v1beta1 rbac.authorization.k8s.io/v1beta1 rbac.authorization.k8s.io/v1alpha1 settings.k8s.io/v1alpha1 storage.k8s.io/v1beta1 storage.k8s.io/v1 apps/v1beta1 v1]
```

Digging around `explain.go` it seems this error is intentionally returned. `cmdutil.CheckErr` prepends the `error:` to indicate an unknown error.

Is this what we want to return to the user? I am only new to the k8s project but it does not seem like a useful error message for users to see.

**Pull request closed without merging**
