### PR TITLE
update util/sets to use standard package cmp

### LINKED ISSUE #121740: replace k8s.io/apimachinery/pkg/util/sets with standard package cmp
Package k8s.io/apimachinery/pkg/util/sets use a custom-defined type `ordered`. Go 1.21 support an official package cmp which has `cmp.Ordered`.

### PR DESCRIPTION
**Pull request by xgp01**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Package k8s.io/apimachinery/pkg/util/sets use a custom-defined type ordered. Go 1.21 support an official package cmp which has cmp.Ordered.
#### Which issue(s) this PR fixes:

Fixes #121740

### CODE REVIEW

**Comment by xgp01** [comment]
cc @weilaaa

**Comment by weilaaa** [comment]
/lgtm
thanks.
cc @derekwaynecarr

**Comment by pacoxu** [comment]
> /milestone v1.29

v1.29 code freezes now. This has to wait for the v1.30 release cycle which will be after the v1.29.0 release(plan to be Dec 5th).

**Comment by xgp01** [comment]
@apelisse  please 

> > /milestone v1.29
> 
> v1.29 code freezes now. This has to wait for the v1.30 release cycle which will be after the v1.29.0 release(plan to be Dec 5th).

Thanks for reminding :)

**Comment by xgp01** [comment]
> > /milestone v1.29
> 
> v1.29 code freezes now. This has to wait for the v1.30 release cycle which will be after the v1.29.0 release(plan to be Dec 5th).

Thanks for reminding :)

**Pull request merged**
