### PR TITLE
Ubuntu-distro: Kubelet and kube-proxy talk to apiserver not etcd.

### PR DESCRIPTION
**Pull request by erictune**

### CODE REVIEW

**Comment by erictune** [comment]
@WIZARD-CXY
Could you review test this change please?
We have moved to a model where only apiserver should access kubernetes objects directly from apiserver.  Also, kubelet and kube-proxy need to POST to apiserver to record events.  This change points them at the apiserver url instead of etcd url.

**Comment by WIZARD-CXY** [comment]
OK, I will look into it asap

**Comment by WIZARD-CXY** [comment]
@erictune The changing in the cluster/ubuntu directory is ok, because it handles the single node situation     where master and minion component is on the same machine.
But ubuntu-cluster is not fine since minion node is not on the same machine where apiserver lives ,so 127.0.0.1:8080 is not correct. Maybe I will send a pr and fix this,it needs to change the configure.sh which  I writed.

**Comment by WIZARD-CXY** [comment]
diff --git a/cluster/ubuntu-cluster/configure.sh b/cluster/ubuntu-cluster/configure.sh
index 0667728..810ea19 100755
--- a/cluster/ubuntu-cluster/configure.sh
+++ b/cluster/ubuntu-cluster/configure.sh
@@ -130,6 +130,8 @@ do
     item="$name=http://$i:2380"
     if [ "$ii" == 1 ]; then 
         cluster=$item
+        #record the masterIP for later use.
+        masterIP=$i
     else
         cluster="$cluster,$item"
         if [ "$ii" -gt 2 ]; then
@@ -192,6 +194,8 @@ while true; do
             configEtcd $etcdName $myIP $cluster
             # set MINION IP in default_scripts/kubelet
             sed -i "s/MY_IP/${myIP}/g" default_scripts/kubelet
+            sed -i "s/MASTER_IP/${masterIP}/g" default_scripts/kubelet         
+            sed -i "s/MASTER_IP/${masterIP}/g" default_scripts/kube-proxy        
 	        cpMinion
 	        break
 	        ;;
diff --git a/cluster/ubuntu-cluster/default_scripts/kube-proxy b/cluster/ubuntu-cluster/default_scripts/kube-proxy
index 82a41b8..1122464 100644
--- a/cluster/ubuntu-cluster/default_scripts/kube-proxy
+++ b/cluster/ubuntu-cluster/default_scripts/kube-proxy
@@ -4,7 +4,7 @@
 # KUBE_PROXY="/opt/bin/kube-proxy"
 
 # Use KUBE_PROXY_OPTS to modify the start/restart options
-KUBE_PROXY_OPTS="--etcd_servers=http://127.0.0.1:4001 \
+KUBE_PROXY_OPTS="--master=http://MASTER_IP:8080 \
 --logtostderr=true"
 
 # Add more envionrment settings used by kube-apiserver here
diff --git a/cluster/ubuntu-cluster/default_scripts/kubelet b/cluster/ubuntu-cluster/default_scripts/kubelet
index 64a4eb5..9da03d8 100644
--- a/cluster/ubuntu-cluster/default_scripts/kubelet
+++ b/cluster/ubuntu-cluster/default_scripts/kubelet
@@ -8,7 +8,7 @@
 KUBELET_OPTS="--address=0.0.0.0 \
 --port=10250 \
 --hostname_override=MY_IP \
---etcd_servers=http://127.0.0.1:4001 \
+--master=http://MASTER_IP:8080 \
 --logtostderr=true"
 
 # Add more envionrment settings used by kube-scheduler here

The above diff will do the change work.

**Comment by resouer** [comment]
@erictune Hi eric, it's so kind of you to notify us by a PR. :smile: 

We think you should also update `configure.sh` like the comment above. BTW, from which release Kubelet and kube-proxy will talk to apiserver? We'd like to test it.

**Comment by erictune** [comment]
Thanks.  Fixed.

**Comment by erictune** [comment]
@resouer 
Please test when you have a chance.

**Comment by resouer** [comment]
@erictune LGTM!

cc @WIZARD-CXY

**Comment by WIZARD-CXY** [comment]
LGTM too!

**Comment by erictune** [comment]
LGTM.  Oncall please merge.

**Comment by erictune** [comment]
@jlowdermilk

**Pull request merged**
