### PR TITLE
kubeadm: rename cri-socket-path -> cri-socket

### PR DESCRIPTION
**Pull request by bart0sh**
**What this PR does / why we need it**:

Renamed command line option cri-socket-path for 2 reasons:
- to be consistent with the rest of kubeadm code
  reset/init/join/apply subcommands use --cri-socket
- name is misleading as CRI socket can be also an url, not just a path

**Release note**:
```release-note
renamed command line option  --cri-socket-path of the kubeadm subcommand "kubeadm config images pull" to --cri-socket to be consistent with the rest of kubeadm subcommands.
```

### CODE REVIEW

**Comment by kad** [comment]
This change would need to have a release note.

**Comment by bart0sh** [comment]
@kad 
> This change would need to have a release note.

done

**Review by luxas — COMMENTED** [review]
This is in itself ok, but we need backwards compat as the kubeadm CLI is beta.
Register both versions of the flag, with the old flag marked as deprecated. The new flag should have higher priority.

**Review by timothysc — APPROVED** [review]
/approve 

You need to ensure backward compatibility, after that lgtm.

**Comment by bart0sh** [comment]
done, pleaser review&lgtm

**Review by luxas — COMMENTED** [review]
idk what flag would have priority if both options were specified now (hypothetically), but this looks good to me.
e.g. @chuckha or @timothysc can do the final `/lgtm`

**Review by timothysc — APPROVED** [review]
/lgtm

**Pull request merged**
