### PR TITLE
Update Cluster Autoscaler version to 0.6.4

### PR DESCRIPTION
**Pull request by aleksandra-malinowska**
Update Cluster Autoscaler version to 0.6.4

```release-note:
Update Cluster Autoscaler version to 0.6.4 to fix security vulnerabilities 
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
@aleksandra-malinowska - why do we want to bump it? Can you add a release note what is changing?

**Comment by aleksandra-malinowska** [comment]
@wojtek-t We're updating all non-deprecated minor releases of Cluster Autoscaler with images built using Debian base.

**Comment by wojtek-t** [comment]
@krzyzacy - we are facing the problem of non-compiling test-infra again:
```
W0322 04:54:36.733] 2018/03/22 04:54:36 e2e.go:146: Updating kubetest binary...
W0322 04:54:51.000] # k8s.io/test-infra/vendor/github.com/json-iterator/go
W0322 04:54:51.001] ../../test-infra/vendor/github.com/json-iterator/go/config.go:107: undefined: sync.Map
```

Is there anything we can do with it one more time?

**Comment by krzyzacy** [comment]
/retest
pushed again temporarily

**Pull request merged**
