### PR TITLE
Automated cherry pick of #88099: Fix gce-cos-master-reboot test

### PR DESCRIPTION
**Pull request by cheftako**
Cherry pick of #88099 on release-1.17.

#88099: Fix gce-cos-master-reboot test
Fixes: #88243 

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by BenTheElder** [comment]
/lgtm
the cherry pick team will need to approve

**Comment by justaugustus** [comment]
Patch Release approval:
/lgtm
/approve
/release-note-none

/hold @cheftako -- Do we need to CP this to 1.15 and 1.16 as well?

**Comment by cheftako** [comment]
> /hold Walter Fender -- Do we need to CP this to 1.15 and 1.16 as well?

The fix is specifically to get the test code to work for network behaviors introduced in COS m77.
1.15 and 1.16 are on COS m73 and should not need the fix.

**Comment by justaugustus** [comment]
Sounds good, @cheftako!
/hold cancel

**Pull request merged**
