### PR TITLE
remove feature-gate StableLoadBalancerNodeSet

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

StableLoadBalancerNodeSet GA in 1.30,  removed in 1.32

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Removed generally available feature gate `StableLoadBalancerNodeSet`.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Shubham82** [comment]
@carlory, In the description of the PR you mentioned

> StableLoadBalancerNodeSet: {Default: true, PreRelease: featuregate.GA, LockToDefault: true}, // GA in 1.30, remove in 1.31

but instead of 1.31, it should be 1.32

> StableLoadBalancerNodeSet: {Default: true, PreRelease: featuregate.GA, LockToDefault: true}, // GA in 1.30, remove in 1.32


Please update it, so that it won't create any confusion.

Thanks!

**Comment by thockin** [comment]
@alexanderConstantinescu ICYMI

/lgtm
/approve

**Pull request merged**
