### PR TITLE
add kubelet flag to provide capabilities for enable aws credetial provider

### LINKED ISSUE #86805: provide capabilities to enable aws credential provider manually
**What would you like to be added**:

i would like to add a flag in kubelet to provide capabilities to enable aws credential provider manually. just like the `--azure-container-registry-config` flag did.

**Why is this needed**:

for some private user, some credential provider (like aws/azure) is unnecessary. and aws credential provider will be initialized automatically during kubelet startup, which will block for some time if we don't have a proper config of aws-sdk. i think providing capabilities to enable the initialization manually can speedup the startup and make it more elegant.

the blocking startup log is shown below.

```
I0103 09:35:13.261265   12179 plugins.go:64] Registering credential provider: .dockercfg
I0103 09:35:13.261286   12179 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{/var/run/dockershim.sock 0  <nil>}]
I0103 09:35:13.261306   12179 clientconn.go:796] ClientConn switching balancer to "pick_first"
I0103 09:35:13.261343   12179 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{/var/run/dockershim.sock 0  <nil>}]
I0103 09:35:13.261357   12179 clientconn.go:796] ClientConn switching balancer to "pick_first"
I0103 09:35:13.261389   12179 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc000c72090, CONNECTING
I0103 09:35:13.261411   12179 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc0004cb180, CONNECTING
I0103 09:35:13.262741   12179 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc0004cb180, READY
I0103 09:35:13.262780   12179 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc000c72090, READY
E0103 09:35:16.266863   12179 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
I0103 09:35:16.267132   12179 azure_credentials.go:161] Azure config unspecified, disabling
```

### PR DESCRIPTION
**Pull request by lancelot1989**
**What type of PR is this?**
> /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #86805 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
setting `--enable-aws-credentials=false` can disable the aws-credentials-provider if not needed
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/hold

please don't add another flag, we are trying to get rid of the existing ones related to cloud providers!

**Review by mattjmcnaughton — COMMENTED** [review]
Welcome to k8s @lancelot1989 :)

Thanks for your thoughts here!

I agree with @dims - I think kubelet is trying to move away from provider specific flags. I also view this as slightly different from the `azure` flag you mention in the pr issue, as that flag is actually pointing to a specific file, as opposed to turning a credential provider on/off.

Can you share more about the blocking call you are seeing from trying to register the aws credentials provider? Specifically, what is it blocking and for how long?

Thanks, and again, welcome :)

**Comment by lancelot1989** [comment]
> Welcome to k8s @lancelot1989 :)
> 
> Thanks for your thoughts here!
> 
> I agree with @dims - I think kubelet is trying to move away from provider specific flags. I also view this as slightly different from the `azure` flag you mention in the pr issue, as that flag is actually pointing to a specific file, as opposed to turning a credential provider on/off.
> 
> Can you share more about the blocking call you are seeing from trying to register the aws credentials provider? Specifically, what is it blocking and for how long?
> 
> Thanks, and again, welcome :)

Thanks for reply. Logs is provided in my issue #86805 .you can see an error log print about aws-sdk-go which spent about 3 seconds after last log. According the error log said and after roughly reading the source code, i think the problem happens when initializing the aws-sdk but some env or config was missing in my environment. And after adding flag to disable the aws-credential-provider, everything seems ok.

**Comment by mattjmcnaughton** [comment]
> > Welcome to k8s @lancelot1989 :)
> > Thanks for your thoughts here!
> > I agree with @dims - I think kubelet is trying to move away from provider specific flags. I also view this as slightly different from the `azure` flag you mention in the pr issue, as that flag is actually pointing to a specific file, as opposed to turning a credential provider on/off.
> > Can you share more about the blocking call you are seeing from trying to register the aws credentials provider? Specifically, what is it blocking and for how long?
> > Thanks, and again, welcome :)
> 
> Thanks for reply @mattjmcnaughton . Logs is provided in my issue #86805 .you can see an error log print about aws-sdk-go which spent about 3 seconds after last log. According the error log said and after roughly reading the source code, i think the problem happens when initializing the aws-sdk but some env or config was missing in my environment. And after adding flag to disable the aws-credential-provider, everything seems ok.

Gotcha, thanks for the additional info. To be sure I'm understanding - is the 3 second error more of a code cleanliness issue or did it have business impact?

**Comment by lancelot1989** [comment]
@dims 

ok, i understand it. But i'm also curious and interest in how to get rid of these flags and how to provide options for users to decide whether these providers to be initialized ?

**Comment by dims** [comment]
@lancelot1989 please see the KEP where we are trying to streamline things specifically for the credential providers - https://github.com/kubernetes/enhancements/pull/1406/files

**Pull request closed without merging**
