### PR TITLE
Bump images, dependencies and versions to go 1.23.0

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature
/hold

#### What this PR does / why we need it:

- Bump images, dependencies and versions to go 1.23.0

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/release/issues/3650

/assign @MadhavJivrajani @liggitt @puerco @xmudrii  @saschagrunert 
cc @kubernetes/release-managers 

#### Does this PR introduce a user-facing change?

```release-note
Kubernetes is now built with go 1.23.0
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tt-kkaiser** [comment]
@cpanato Isn't this a duplicate of #126992? (I can close my pull request if you prefer to proceed with yours.)

**Comment by cpanato** [comment]
> @cpanato Isn't this a duplicate of #126992? (I can close my pull request if you prefer to proceed with yours.)

@tt-kkaiser Sorry, this work was coordinated in the sig-release (release engineering team), and the images were not published when you opened the pr. But if you want to help please show up in the sig-release meetings, then we can have a better coordination and avoid duplications

**Comment by tt-kkaiser** [comment]
Oh okay, I asked in the sig-release slack about it. The reason I opened my pull request in the first place was to resolve the issue I had with kubernetes (#126965) and not really as a new release for kubernetes.

**Comment by cpanato** [comment]
> Oh okay, I asked in the sig-release slack about it. The reason I opened my pull request in the first place was to resolve the issue I had with kubernetes (#126965) and not really as a new release for kubernetes.

there are a lot of other things to happen before opening the PR, we need to have other things in place, please, before doing anything, talk with us in Slack.

**Comment by tt-kkaiser** [comment]
Okay, thanks for the info, for next time i'll let you know in slack beforehand and not afterwards.

**Review by saschagrunert — APPROVED** [review]
Thank you!

**Pull request merged**
