### PR TITLE
Bump fluentd-gcp version

### PR DESCRIPTION
**Pull request by x13n**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
fluentd-gcp updated to version 2.0.13.
```

### CODE REVIEW

**Comment by x13n** [comment]
/hold

There was a bug in 2.0.12. Putting on hold until the next version is released.

**Comment by x13n** [comment]
2.0.13 was released, switching to it here.

/hold cancel

**Comment by x13n** [comment]
@crassirostris @piosz PTAL

**Comment by crassirostris** [comment]
Thanks!

**Pull request merged**
