### PR TITLE
kep-3836: promote to beta in 1.30

### PR DESCRIPTION
**Pull request by cyclinder**
#### What type of PR is this?

/kind cleanup
/kind feature

#### What this PR does / why we need it:

graduate KubeProxyDrainingTerminatingNodes to beta in 1.30. 

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

this is a part of https://github.com/kubernetes/kubernetes/pull/122914.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
https://github.com/kubernetes/kubernetes/pull/122914
https://github.com/kubernetes/enhancements/issues/3836
```

### CODE REVIEW

**Comment by sftim** [comment]
Would this need a changelog entry?

**Comment by aojea** [comment]
follow up on https://github.com/kubernetes/kubernetes/pull/122914

@sftim this was a gap, this feature will be GA this release, so I think that a release not for beta and GA in the same release will be confusing for users
/assign @alexanderConstantinescu @thockin 
/lgtm
/approve

**Comment by thockin** [comment]
@aojea - it's beta, not GA?

**Comment by thockin** [comment]
Oh, I see - it was already beta, but the comment was not updated.

/approve

**Pull request merged**
