### PR TITLE
Proposal to add @wlan0 to appropriate owner files

### PR DESCRIPTION
**Pull request by wlan0**
@thockin @luxas

### CODE REVIEW

**Comment by deads2k** [comment]
@luxas confirm you want to be in these files

**Comment by deads2k** [comment]
lgtm, but having been on the receiving end, I'd like @luxas to confirm that he's good with being auto-assigned via owners

**Comment by luxas** [comment]
Thanks @deads2k for pinging!
I'm okay with having me here for now; if I find later that I don't have time to look at these PRs, I'll just opt-out later. But as I am pretty involved in this thing it makes sense to me.

**Comment by wlan0** [comment]
/assign @mikedanese 

cc @thockin

**Pull request merged**
