### PR TITLE
Build: Push .md5 and .sha1 files for every file we push to GCS

### PR DESCRIPTION
**Pull request by zmerlynn**
Also by pre-staging and pushing all at once, and by doing the ACL
modify in parallel, this shaves the push time down anyways, despite
the extra I/O.

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @roberthbailey or someone to possibly test on OS X, too. (just `make release; build/push-devel-build.sh`)?

**Comment by roberthbailey** [comment]
The shell looks reasonable. @eparis - want to take a look as well?

**Comment by roberthbailey** [comment]
`push-devel-build.sh` just hangs for me on my mac. Maybe I'm not being patient enough?

```
!!! Error in ./build/../build/common.sh:840
  'gsutil -q -m "${gcs_options[@]+${gcs_options[@]}}" cp -r "${GCS_STAGE}"/* ${gcs_destination}' exited with status 1
Call stack:
  1: ./build/../build/common.sh:840 kube::release::gcs::copy_release_artifacts(...)
  2: ./build/../build/common.sh:779 kube::release::gcs::release(...)
  3: ./build/push-devel-build.sh:34 main(...)
Exiting with status 1
```

**Comment by zmerlynn** [comment]
It was mid-copy. Home DSL? I took the gsutil spam out a while ago or you might see intermediate progress.

**Comment by roberthbailey** [comment]
Yeah, could be the home network. I'll try again from work today.

**Comment by roberthbailey** [comment]
I noticed that this pushed to `gs://kubernetes-releases-9f55a` rather than using the longer hash that we use elsewhere (see #6615). Can you update this code path to use the longer hash as well?

**Comment by zmerlynn** [comment]
Done, PTAL

**Comment by roberthbailey** [comment]
Testing one more time before merging...

**Comment by roberthbailey** [comment]
Still waiting on travis but since this only changes shell script, the tests aren't going to cover it anyway.

**Pull request merged**
