### PR TITLE
refactor code in pkg/client/conditions/conditions.go

### PR DESCRIPTION
**Pull request by yu-song**
refactor code in pkg/client/conditions/conditions.go

### CODE REVIEW

**Comment by yu-song** [comment]
Test again

**Comment by yu-song** [comment]
@deads2k 
Excuse me, I do not know why the check of PR has been hanging? Can you give me some advice?

**Comment by deads2k** [comment]
> Excuse me, I do not know why the check of PR has been hanging? Can you give me some advice?

It requires being a member of a certain group to auto-trigger to avoid spamming.

**Comment by deads2k** [comment]
@k8s-bot ok to test

**Comment by deads2k** [comment]
The new code doesn't look much shorter or clearer than the old code.  I think I'd leave the existing code to keep the locality where it is.

**Pull request closed without merging**
