### PR TITLE
Automated cherry pick of #85920: Accept healthy instances in list of active instances

### PR DESCRIPTION
**Pull request by hoelzro**
Cherry pick of #85920 on release-1.15.

#85920: Accept healthy instances in list of active instances

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Cordoned nodes are now deregistered from AWS target groups.
```

### CODE REVIEW

**Comment by hoelzro** [comment]
More background on this - this cherry pick fixes #79581, which includes automated tests for the fixed behavior.  We also tested and verified the fix on a live cluster.

**Comment by tpepper** [comment]
Release 1.15 is out of support (https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md) and we're no longer doing cherry picks to the release-1.15 branch.

**Comment by hoelzro** [comment]
Ah, dang - well, thanks for letting me know!

**Pull request closed without merging**
