### PR TITLE
add file extension

### PR DESCRIPTION
**Pull request by jjmengze**
**What this PR does / why we need it**:

I noticed that this file does not have an file extension, should we add a file extension?

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
/ok-to-test

Does nothing link to this?

**Comment by MengZn** [comment]
@thockin The test failed, I do not know what happened. Can you help me?

**Comment by thockin** [comment]
It looks like `pkg/kubectl/resource/builder_test.go` references this file twice.  `git grep` is your friend.

**Comment by thockin** [comment]
Assign back to me once it is ready for review.

**Pull request closed without merging**
