### PR TITLE
Automated cherry pick of #69548: Fix find-binary to locate bazel e2e tests

### PR DESCRIPTION
**Pull request by neolit123**
Cherry pick of #69548 on release-1.11.

#69548: Fix find-binary to locate bazel e2e tests

### CODE REVIEW

**Comment by neolit123** [comment]
/assign @BenTheElder @ixdy
/assing @foxish 

[here](https://github.com/kubernetes/kubernetes/pull/74566) we backported to 1.12, but i realized that this will be a problem in 1.11 too and when testing 1.11->1.12 upgrades we are going to face the same problem.

/kind bug
/priority important-longterm
/release-note-none
/sig testing

**Review by BenTheElder — APPROVED** [review]
/lgtm
thank you!

**Comment by neolit123** [comment]
/retest
ping-pong

**Pull request merged**
