### PR TITLE
Release 1.3 - batch 2

### PR DESCRIPTION
**Pull request by eparis**
#27513: vSphere provider - Adding config for working dir
#28132: Substitute federation_domain_map parameter with its value in node bootstrap scripts.
#28261: Create a PD volume when deploying the federation with federation-up.
#25873: Fix problems with container restarts and flocker volumes
#28258: [kubelet] Allow opting out of automatic cloud provider detection in kubelet. By default kubelet will auto-detect cloud providers

### CODE REVIEW

**Comment by erictune** [comment]
Want #28261 and #25873 (if it merges in the next hour).

**Comment by erictune** [comment]
And #28258

**Comment by david-mcmahon** [comment]
@eparis We need to pull #27513 and add #28258 to this and hack/verify-all.sh is showing failures.

**Comment by eparis** [comment]
Why would I remove 27513? Because the pick messed up the `os/exec` import? I just redid the pick correctly. We'll see how this tests.

**Comment by erictune** [comment]
```
# k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere
pkg/cloudprovider/providers/vsphere/vsphere.go:164: undefined: path in path.Clean
```

**Pull request merged**
