### PR TITLE
kubectl cp: discard output from test command

### PR DESCRIPTION
**Pull request by BenTheElder**
we only care about the exit code

see https://github.com/kubernetes/kubernetes/issues/126669

#### What type of PR is this?

/kind bug
/sig cli

#### What this PR does / why we need it:

Discards unused output from executing the test command, to avoid OOM vector.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/retest
[CI pod scheduling timeout `pull-kubernetes-e2e-kind-ipv6` and `pull-kubernetes-node-e2e-containerd `]

**Comment by BenTheElder** [comment]
So far everything passes tests and works as expected, I haven't found any observable behavior difference besides mitigating "oom by way of malicious `test`"

Also this maybe deserves a release note since it partially fixes a reported vuln? I'm not sure what we want to do here.

Will wait for input from kubectl owners ...

**Comment by ardaguclu** [comment]
> So far everything passes tests and works as expected, I haven't found any observable behavior difference besides mitigating "oom by way of malicious `test`"
> 
> Also this maybe deserves a release note since it partially fixes a reported vuln? I'm not sure what we want to do here.
> 
> Will wait for input from kubectl owners ...

That is nice (I ensured that the exit code that `cp` requires is not derived from `out`, it is derived from it's own error code stream and after a test, saw that it is working as expected). 
However, although this definitely solves the memory problem, we still need to fix the _stuck_ issue. Corrupted `test` still blocks the whole cp command and I believe that we need to combine this PR and https://github.com/kubernetes/kubernetes/pull/126652

**Comment by soltysh** [comment]
I see Arda already picked your commit into https://github.com/kubernetes/kubernetes/pull/126652. I agree that both approach are complete each other in a different way, strengthening against potential vulnerabilities. 

/close

**Pull request closed without merging**
