### PR TITLE
Staticcheck: vendor/k8s.io/kubectl/pkg/scale etc.

### PR DESCRIPTION
**Pull request by gavinfish**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fix static check failures for:

```
vendor/k8s.io/kubectl/pkg/cmd/top
vendor/k8s.io/kubectl/pkg/cmd/util/editor
vendor/k8s.io/kubectl/pkg/cmd/wait
vendor/k8s.io/kubectl/pkg/describe/versioned
vendor/k8s.io/kubectl/pkg/scale
```

Ref #81657

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by YuikoTakada** [comment]
you need to run `./hack/update-bazel.sh` and apply the diff into this PR for passing pull-kubernetes-verify job.

**Comment by gavinfish** [comment]
@YuikoTakada Thanks, I missed to commit the automated change.

**Comment by liggitt** [comment]
lgtm, needs rebase

**Comment by gavinfish** [comment]
@liggitt, thanks for reviewing, and rebase is done.

**Pull request merged**
