### PR TITLE
bump dependencies: github.com/envoyproxy/go-control-plane to v0.11.0

### PR DESCRIPTION
**Pull request by tukwila**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR is supposed to update github.com/envoyproxy/go-control-plane to the latest version v0.11.0.

#### Which issue(s) this PR fixes:

Fixes # None

#### Does this PR introduce a user-facing change?
None

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
None

### CODE REVIEW

**Comment by tukwila** [comment]
@dims @liggitt could you please look at this upgrade? i think control-plane is somehow important -:P

**Comment by liggitt** [comment]
we don't actually use any code from github.com/envoyproxy/go-control-plane, so I think we can just wait to pull in an updated version the next time we bump grpc

**Pull request closed without merging**
