### PR TITLE
DO NOT MERGE: Move k8s.io/kubernetes/pkg/{api,apis} to k8s.io/internal-api/

### PR DESCRIPTION
**Pull request by smarterclayton**
Enables these components to be more easily accessed outside of staging.

```release-note
The internal API types and helpers in Kubernetes have been moved to k8s.io/internal-api.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by smarterclayton** [comment]
@dims @seans3 @deads2k @liggitt I suspect this will fail for a while, but the movement was not the hard part.

**Comment by deads2k** [comment]
The name makes it very clear that these are for internal usage.  We can make a similarly specific readme to match.

**Comment by smarterclayton** [comment]
The things in k/k referenced from internal-api:

```
 2 k8s.io/kubernetes/pkg/capabilities
  45 k8s.io/kubernetes/pkg/features
   2 k8s.io/kubernetes/pkg/fieldpath
   1 k8s.io/kubernetes/pkg/master/ports
   6 k8s.io/kubernetes/pkg/security/apparmor
   2 k8s.io/kubernetes/pkg/security/podsecuritypolicy/seccomp
   1 k8s.io/kubernetes/pkg/util/parsers
```

Some constants, some validation, some defaulting.

In general all of the constants should be in internal-api.  I think validation belongs in internal-api, although we don't have to move it if we don't want to (if we do that, most of these drop out).

Features would be the ugliest to move to internal API.

**Comment by deads2k** [comment]
> /cc @liggitt

and @lavalamp

**Comment by deads2k** [comment]
> In general all of the constants should be in internal-api. I think validation belongs in internal-api, although we don't have to move it if we don't want to (if we do that, most of these drop out).

I think I like the idea of co-locating the validation rules.  I do *not* like the idea of placing features in internal-api though.

**Comment by smarterclayton** [comment]
There is no way to do this without moving features into internal-api or a parent.

**Comment by smarterclayton** [comment]
Defaults and validation depend on features.

**Comment by smarterclayton** [comment]
The security ones can be copied and shims left in place.  The other ones are mostly minor and can be moved or snipped.  Security takes dependencies on the kubelet (it's mixing core control plane and kube types).  I think those packages just have to be split into "validating" and "runtime".

**Comment by lavalamp** [comment]
I haven't looked at this PR.

Why would we make it easy to access these? What can a client do with these that is not a bug waiting to happen?

**Pull request closed without merging**
