### PR TITLE
Fixing grammatical errors

### PR DESCRIPTION
**Pull request by xichengliudui**
**What this PR does / why we need it**:
Fixing grammatical errors

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
/hold
/kind cleanup

@xichengliudui 
please try finding more typos and combine them in the same commit / PR.
thanks.

**Comment by xichengliudui** [comment]
@neolit123  Ok, thanks for the warning！

**Review by neolit123 — COMMENTED** [review]
LGTM

**Pull request merged**
