### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by erictune**
Added bare-metal ubuntu getting started guide.
@jainvipin may I list you as a community supporter for bare-metal ubuntu?

described the Config Management for one of the  for the non-saltstack non-ansible version of vagrant+Fedora.
@eparis is there a better name for this thing?

### CODE REVIEW

**Comment by jainvipin** [comment]
@erictune - should be okay

**Comment by roberthbailey** [comment]
Eric, can you rebase so I can merge cleanly?

**Comment by erictune** [comment]
have we made a decision to start doing that?  It seems like a lot of busywork just to make the commit logs pretty.

**Comment by filbranden** [comment]
Here again this branch was created in the upstream project so anyone doing `git fetch` from it will end up receiving this branch... It should have been created on your personal project instead. (Don't worry, you're not the first one to do this, it's fairly common, apparently the GitHub mobile app makes it really easy to make this mistake.) Please avoid creating new work branches on the upstream project in the future.

**Pull request merged**
