### PR TITLE
Fix conformance daemon_set test failing in local cluster

### PR DESCRIPTION
**Pull request by lubinsz**
Fixing up conformance test related to:
1, ci-k8s-conformance-arm64-aws-cluster
https://storage.googleapis.com/k8s-conformance-arm/logs/ci-k8s-conformance-arm64-aws-cluster/84/build-log.txt

2, conformance test results for ppc64le
https://storage.googleapis.com/ppc64le-kubernetes/logs/ci-conformance-kubernetes/2809/build-log.txt

Signed-off-by: Bin Lu <bin.lu@arm.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind failing-test

**What this PR does / why we need it**:
Fix conformance daemon_set test failing in local cluster

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
Fix conformance daemon_set test failing in local cluster

**Does this PR introduce a user-facing change?**:
NONE

```release-note
NONE
```

### CODE REVIEW

**Comment by lubinsz** [comment]
@janetkuo @nikhiljindal @kargakis @mfojtik
Hi, 
Any comments?

**Comment by k-toyoda-pi** [comment]
Hello, your changed lines were changed in #72690 a while ago.
Is it necessary to return to the original?

**Comment by kargakis** [comment]
Maybe try fixing the actual error in the test in case we only have a single node?
From reviewing the test, I see that it probably fails at
```go
		Expect(len(existingPods)).NotTo(Equal(0))
		Expect(len(newPods)).NotTo(Equal(0))
```
Existing pods should be zero in case we only have one node.

**Comment by lubinsz** [comment]
> Maybe try fixing the actual error in the test in case we only have a single node?
> From reviewing the test, I see that it probably fails at
> 
> ```go
> 		Expect(len(existingPods)).NotTo(Equal(0))
> 		Expect(len(newPods)).NotTo(Equal(0))
> ```
> 
> Existing pods should be zero in case we only have one node.

@kargakis I have modified it. How about it?
Thanks.

**Pull request merged**
