### PR TITLE
If sandbox changed, related containers should be killed explicitly

### LINKED ISSUE #76416: When sandbox got recreated, related container were not killed explicitly
**What happened**:
When sandbox container got recreated, whatever reason(server reboot, sandbox got killed), the related container in the pod should be killed explicitly, otherwise the cpu manager would leave the container in the /var/lib/kubelet/cpu_manager_state, causing cpu leak

**What you expected to happen**:

the expected behavior should be: the containers in the pod got killed and the lifecycle hooks are invoked in order to lease the cpu occupied.

**How to reproduce it (as minimally and precisely as possible)**:

1. Enable cpu manager in kubelet
2. create a pod with guarantee QoS
3. reboot the server of the running pod
4. after server is up, check the `cid` of the terminated containers
5. checking the /var/lib/kubelet/cpu_manager_state, the entry of the `cid` was left there

here is the leak evidence：

```bash
root@ubuntu:~# docker kill  f0838c82f70b
f0838c82f70b
root@ubuntu:~# docker ps -a | grep my-pod-with-anovol
96041e11a37f        88dfbf70e51f                      "sleep 1000000"          54 seconds ago      Up 53 seconds                                         k8s_my-frontend_my-pod-with-anovol_default_38df0bd9-5c1b-11e9-a3f4-000c299ef3b7_1
9fda0a2c4905        k8s.gcr.io/pause:3.1              "/pause"                 55 seconds ago      Up 54 seconds                                         k8s_POD_my-pod-with-anovol_default_38df0bd9-5c1b-11e9-a3f4-000c299ef3b7_1
c105b5ecd642        88dfbf70e51f                      "sleep 1000000"          11 minutes ago      Exited (137) 55 seconds ago                           k8s_my-frontend_my-pod-with-anovol_default_38df0bd9-5c1b-11e9-a3f4-000c299ef3b7_0
f0838c82f70b        k8s.gcr.io/pause:3.1              "/pause"                 11 minutes ago      Exited (137) About a minute ago                       k8s_POD_my-pod-with-anovol_default_38df0bd9-5c1b-11e9-a3f4-000c299ef3b7_0
root@ubuntu:~# cat /var/lib/kubelet/cpu_manager_state
{"policyName":"static","defaultCpuSet":"0","entries":{"96041e11a37f600c75accb303066110db02736e5f8daa1d7753c710448dfa1a5":"2","c105b5ecd642a05055563095f1240ae82f9344cca4bba63fa67aee164882bb51":"1"},"checksum":340621555
```
NOTE: `f0838c82f70b` is the sandbox of the pod

**Anything else we need to know?**:

**Environment**:
```
kubelet --version
Kubernetes v1.13.3
```

### PR DESCRIPTION
**Pull request by peter-wangxu**
In some cases, if sandbox was dead, the pod containers are
not killed(forcibly) and new containers are created directly.

This behavior causes cpu leak since  cpu manager state was
not removed for these containers

Possible reasons lead to above issue:
1. System reboot
2. sandbox gets killed by docker

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #76416

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by matthyx** [comment]
@peter-wangxu can you fix those failing jobs?

**Comment by peter-wangxu** [comment]
@matthyx looks like this is no longer an issue in newer version, closing it...

**Pull request closed without merging**
