### PR TITLE
kubectl get: Added example for sorted output.

### PR DESCRIPTION
**Pull request by guettli**
I think this is handy for debugging.

#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:

This PR adds a new example to the output of `kubectl get -h`

#### Which issue(s) this PR fixes:

`kubectl get events` output is unsorted. This is confusing. Remembering the
line exactly is hard. That's why I think it would be good fit to have it in the help messages.

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by hwdef — COMMENTED** [review]
/ok-to-test
/release-note-none

**Comment by guettli** [comment]
sorry, I still think the example makes sense, but I have no time at the moment.

**Pull request closed without merging**
