### PR TITLE
Move PD on two hosts test to flaky

### PR DESCRIPTION
**Pull request by wojtek-t**

### CODE REVIEW

**Comment by wojtek-t** [comment]
cc @gmarek @davidopp

**Comment by gmarek** [comment]
LGTM, thanks for doing this.

**Comment by gmarek** [comment]
It's a test-config only change, thus I'm going to merge it.

**Comment by ixdy** [comment]
Do we have a tracking issue for this?

**Comment by wojtek-t** [comment]
@ixdy yes - see #11302

**Pull request merged**
