### PR TITLE
expect the new resource_scrape_error metric

### LINKED ISSUE #120079: Failure cluster [ca1a7cae...] E2eNode Suite [It] [sig-node] ResourceMetricsAPI [NodeFeature:ResourceMetrics] when querying /resource/metrics should report resource usage through the resource metrics api
##### Error text:
```
[FAILED] Timed out after 60.000s.
Expected
    <string>: KubeletMetrics
to match keys: {
."resource_scrape_error":
	unexpected key resource_scrape_error: map[container_cpu_usage_seconds_total:[container_cpu_usage_seconds_total{container="busybox-container", namespace="resource-metrics-9178", pod="stats-busybox-0"} => 0.0730633 @[1692500452.599] container_cpu_usage_seconds_total{container="busybox-container", namespace="resource-metrics-9178", pod="stats-busybox-1"} => 0.062580342 @[1692500450.843]] container_memory_working_set_bytes:[container_memory_working_set_bytes{container="busybox-container", namespace="resource-metrics-9178", pod="stats-busybox-0"} => 647168 @[1692500452.599] container_memory_working_set_bytes{container="busybox-container", namespace="resource-metrics-9178", pod="stats-busybox-1"} => 598016 @[1692500450.843]] container_start_time_seconds:[container_start_time_seconds{container="busybox-container", namespace="resource-metrics-9178", pod="stats-busybox-0"} => 1692500395.2908316 @[1692500395.29] container_start_time_seconds{container="busybox-container", namespace="resource-metrics-9178", pod="stats-busybox-1"} => 1692500395.0673323 @[1692500395.067]] node_cpu_usage_seconds_total:[node_cpu_usage_seconds_total => 233.839797991 @[1692500454.043]] node_memory_working_set_bytes:[node_memory_working_set_bytes => 1263235072 @[1692500454.043]] pod_cpu_usage_seconds_total:[pod_cpu_usage_seconds_total{namespace="resource-metrics-9178", pod="stats-busybox-0"} => 0.
```
#### Recent failures:
[8/20/2023, 4:28:05 AM ci-cos-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-containerd-node-e2e-features/1693193149679144960)
[8/20/2023, 12:26:05 AM ci-cos-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-containerd-node-e2e-features/1693132247189688320)
[8/20/2023, 12:06:05 AM ci-cos-cgroupv2-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv2-containerd-node-e2e-features/1693127214003916800)
[8/19/2023, 11:45:05 PM ci-cos-cgroupv1-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv1-containerd-node-e2e-features/1693121929189265408)
[8/19/2023, 11:25:04 PM ci-cos-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-containerd-node-e2e-features/1693116895877664768)

/kind failing-test

/sig node

### PR DESCRIPTION
**Pull request by tzneal**
#### What type of PR is this?
/kind failing-test

#### What this PR does / why we need it:

Updates test for the new metric name added in https://github.com/kubernetes/kubernetes/pull/116897 to resolve the failures at https://storage.googleapis.com/k8s-triage/index.html?sig=node&xjob=windows#ca1a7caee3e22eb5c8e8

#### Which issue(s) this PR fixes:

Fixes #120079

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tzneal** [comment]
Follow up to https://github.com/kubernetes/kubernetes/pull/116897/ which added a new `resource_scrape_error` metric that's causing E2E Node tests to fail.

Should resolve all of https://storage.googleapis.com/k8s-triage/index.html?sig=node&xjob=windows#ca1a7caee3e22eb5c8e8

**Comment by dims** [comment]
/approve

leaving `/lgtm` for @Richabanker or other reviewers

**Comment by Richabanker** [comment]
/lgtm
Sorry I didnt realize I broke this. Thanks for the fix @tzneal  !

**Pull request merged**
