### PR TITLE
chore: improve error message for unstructured helper method

### PR DESCRIPTION
**Pull request by crenshaw-dev**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The error message is incorrect. The problem detected is an invalid _value_, not an invalid _key_.

To further improve the message, I've added the key under which the invalid value is found.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

I don't _think_ this is considered user-facing? Please advise.

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jiahuif** [comment]
/label api-review
/assign @Jefftree 
Thank you.
/triage accepted

**Comment by crenshaw-dev** [comment]
I'm new in this town. Anything else needed from me, or do the maintainers take it from here? I don't see anything in the docs about "milestone".

**Comment by jiahuif** [comment]
Check the timeline at https://www.kubernetes.dev/resources/release/
scroll down for code thaw, for 1.28 it is on Tuesday 15th August 2023. After code thaw this PR should merge.

**Comment by crenshaw-dev** [comment]
Apologies for the ping one day before the question would have answered itself. 😆 Thanks!

**Pull request merged**
