### PR TITLE
remove redundant fake discovery code

### PR DESCRIPTION
**Pull request by yue9944882**
**Special notes for your reviewer**:
This PR removes fake discovery from `testing` package.
It is already moved to:
[https://github.com/kubernetes/kubernetes/blob/9c57bf74b302cb263b6a301be6b9df1ded8e10c7/staging/src/k8s.io/client-go/discovery/fake/discovery.go#L34](https://github.com/kubernetes/kubernetes/blob/9c57bf74b302cb263b6a301be6b9df1ded8e10c7/staging/src/k8s.io/client-go/discovery/fake/discovery.go#L34)

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
This seems fine? I'm not sure we want or need to push this through during code freeze though.

**Comment by yue9944882** [comment]
@BenTheElder Seems like this PR will affect nothing seriously because nothing is referencing these code.

**Comment by BenTheElder** [comment]
Right, but we need extra approvals during code freeze leading up to the release, because we're trying to make sure important last minute changes merge quickly and without conflict. We should *probably* do this in the next release.

**Comment by BenTheElder** [comment]
I'm not sure though, cc @krzyzacy @jberkus

**Comment by krzyzacy** [comment]
I have no context with this file, assign to folks who worked on this file

/assign @deads2k @smarterclayton

**Comment by cblecker** [comment]
Cleanup of this kind can wait until after freeze.

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60489)

**Comment by deads2k** [comment]
I think we should create a fake discovery client, but removing the old seems fine.  This looks questionable anyway.

/lgtm

It won't merge until the queue re-opens

**Pull request merged**
