### PR TITLE
Avoid sed bundled with Darwin for building test images

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I4fc1d495c9a42d081107829cfae0cad6d5aa29ff
Signed-off-by: Davanum Srinivas <davanum@gmail.com>

**What this PR does / why we need it**:
using plain old `sed` we run into problems on macOS. for example when you try `make all-container WHAT=net` under test/images. We should use the same pattern we use in all our scripts to ensure we use gsed or a version of sed from GNU.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/cc @mkumatag @BenTheElder @cjwagner 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by mkumatag — APPROVED** [review]
LGTM

**Review by BenTheElder — APPROVED** [review]
/lgtm
Thanks!

**Review by luxas — APPROVED** [review]
/approve
Thanks @dims!

**Pull request merged**
