### PR TITLE
fix: resolve goroutine leak in integration tests

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

#### What type of PR is this?
/kind cleanup
/sig testing

#### What this PR does / why we need it:
Take a first around of easy to find gorouting leaks

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/kubernetes/issues/108483

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kerthcet** [comment]
cc @aojea

**Comment by aojea** [comment]
can you split the `test/integration/volumescheduling/volume_capacity_priority_test.go` to a different commit , so each commit is independent, since it address different packages

**Comment by kerthcet** [comment]
> can you split the `test/integration/volumescheduling/volume_capacity_priority_test.go` to a different commit , so each commit is independent, since it address different packages

Pretty good, updated as advised.

**Comment by aojea** [comment]
/lgtm
/approve
:heart:

**Pull request merged**
