### PR TITLE
Fix structured logging for kuberuntime_manger.go

### PR DESCRIPTION
**Pull request by adisky**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Address review comments from https://github.com/kubernetes/kubernetes/pull/99841

#### Which issue(s) this PR fixes:

part of #98976

#### Special notes for your reviewer:
followup from https://github.com/kubernetes/kubernetes/pull/99841

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: <link> KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging

```

### CODE REVIEW

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by kikisdeliveryservice** [comment]
@adisky can you please update the description as this is user facing change that reqs a release note.

**Comment by navidshaikh** [comment]
@kikisdeliveryservice : This is a follow up to address review comments from https://github.com/kubernetes/kubernetes/pull/99841#pullrequestreview-606755275 and the release note for same is in place in #99841.

**Review by kikisdeliveryservice — COMMENTED** [review]
@adisky  could you also update pkg/kubelet/kuberuntime/kuberuntime_manager.go line 854 it has a missing "pod" as well (can't comment in file view unfortch):

```
klog.V(3).InfoS("Container start failed in pod", "containerType", typeName, "container", spec.container, klog.KObj(pod), "containerMessage", msg, "err", err)
```

**Comment by adisky** [comment]
@kikisdeliveryservice Thanks for noticing it, Updated.

**Comment by kikisdeliveryservice** [comment]
Looks like: https://github.com/kubernetes/kubernetes/issues/96068

/retest

**Comment by kikisdeliveryservice** [comment]
Thanks for updating @adisky !

/lgtm

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
