### PR TITLE
Automated cherry pick of #37783 upstream release 1.5

### PR DESCRIPTION
**Pull request by brendandburns**
@saad-ali

### CODE REVIEW

**Comment by jbeda** [comment]
Are you going to cherrypick #38584 also so that we don't break cross builds?

**Comment by brendandburns** [comment]
Thanks for pointing that out, I'll combine it into this PR.

**Comment by brendandburns** [comment]
Revert PR added.

**Comment by jbeda** [comment]
Not sure about the cherrypick process and approvals but this looks good to me.  Let me know if I'm the one that needs to flip a bit or do something.

**Comment by brendandburns** [comment]
@k8s-bot gci gke e2e test this

**Pull request merged**
