### PR TITLE
fix a syntax error in a comment

### PR DESCRIPTION
**Pull request by lioncruise**
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lioncruise** [comment]
@mtaufen @dashpole

**Comment by lioncruise** [comment]
Why does PR not have approved label? @mtaufen @dashpole @Random-Liu

**Comment by mtaufen** [comment]
It needs approval from someone in cmd/kubelet/OWNERS. I assigned @Random-Liu for that reason.

**Comment by lioncruise** [comment]
Would you please add an approved label to this pull request? Need your approval, thanks. @Random-Liu

**Comment by lioncruise** [comment]
Would you please add an approved label to this pull request? Need your approval, thanks.  @dchen1107 @derekwaynecarr @vishh @yujuhong

**Comment by lioncruise** [comment]
Would you please add an approved label to this pull request? Need your approval, thanks. @dchen1107 @derekwaynecarr @vishh @yujuhong @Random-Liu

**Comment by lioncruise** [comment]
Seems it need a `/approve no-issue` comment to merge this PR. @yujuhong

**Pull request merged**
