### PR TITLE
Promote DNS e2e verifying DNS resolution for hostname and subdomain

### LINKED ISSUE #73425: Tracking Issue - Conformance Coverage for Networking
**What would you like to be added**:
This is a place holder to track Conformance Coverage on the Topic.
This issue should remain open until all related work is accomplished in the k/k repo
This issue will contain analysis of the coverage. Existing tests and additional tests requested with links to those issues/PR's

**Why is this needed**:
Specifically address CNI networking, identify tests that tests pod-pod communication

/area conformance

### PR DESCRIPTION
**Pull request by mgdevstack**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Promotes DNS e2e which is verifying DNS resolution behavior for hostname and subdomain defined pods.

**Which issue(s) this PR fixes**:

Fixes #73425

**Special notes for your reviewer**:
- Maybe failing for windows.
- Not Flaking
- Promoting to Conformance as it verifies important functional scenario of resolving DNS when Pod is defined with hostname and subdomain and headless services having the same name as of subdomain.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/area conformance
/sig testing
@kubernetes/sig-network-pr-reviews

### CODE REVIEW

**Comment by brahmaroutu** [comment]
@caseydavenport  @danwinship    Can you please review and lgtm to promote this PR.

**Comment by danwinship** [comment]
I don't really know what the criteria for making something a conformance test are. 

I see that #73425 claims that this was approved by the SIG "for the most part"... was that on the mailing list or in a meeting or... ?

**Comment by johnbelamaric** [comment]
Rebase on #75591 once that merges.

**Comment by bclau** [comment]
I have a PR that splits this test into 2 parts here: https://github.com/kubernetes/kubernetes/pull/75591

The reason this is done is because individual files cannot be mounted on Windows Containers at the moment, which is required by this test, as it checks the ``/etc/hosts`` entries.

So, first of all, because of the reason above, this test should be labeled ``[LinuxOnly]`` first in order to avoid any failures in the Windows testgrid, and / or merge my PR first and promote the Subdomain part to conformance.

**Comment by johnbelamaric** [comment]
Let me poke to get that PR merged so we can move forward.

**Comment by mgdevstack** [comment]
Awaiting for rectification on https://github.com/kubernetes/kubernetes/pull/75591#issuecomment-489503477 before promoting following two e2e to Conformance in this PR.
1. should provide DNS for pods for Hostname [LinuxOnly]
2. should provide DNS for pods for Subdomain

**Comment by spiffxp** [comment]
/approve
for the test/e2e part
/milestone v1.15
I think this is worth allowing in during code freeze, this doesn't change the tests, and they are already present in https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=DNS

**Pull request merged**
