### PR TITLE
Fix godeps

### PR DESCRIPTION
**Pull request by eparis**
They started picking up other LICENSE files, so now
https://github.com/kubernetes/kubernetes/pull/20033
is failing.

### CODE REVIEW

**Comment by eparis** [comment]
@karlkfi didn't you add the LICENSES.md thing? Does it get checked/enforced if it is up2date anywhere?

**Comment by eparis** [comment]
This is a very simple set of mechanical fixes.
```
godep restore
rm -rf Godeps
godep save ./...
hack/update-godep-licenses.sh
```
And is blocking other PRs....

**Comment by pmorie** [comment]
Looks like the mode changes on all these files came fro godep?

**Comment by eparis** [comment]
In my GOPATH they are `+x`, but godep seems to have `-x`'d them when it imported them....

**Comment by pmorie** [comment]
Ok.  LGTM.

**Comment by karlkfi** [comment]
@eparis hacks/verify-godep-licenses.sh runs on pre-commit hook and on travis

**Comment by eparis** [comment]
@karlkfi are you sure the travis hook is being enforced?  It got out of date somehow and no one noticed (except me by random chance)

**Comment by karlkfi** [comment]
@eparis 
1. Travis calls `make verify`: https://github.com/kubernetes/kubernetes/blob/master/.travis.yml#L23
2. make verify calls `hack/verify-godep-licenses.sh`: https://github.com/kubernetes/kubernetes/blob/master/Makefile#L54

**Pull request merged**
