### PR TITLE
Remove kubectl create configmap dependencies on kubernetes/pkg/api

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:
ref https://github.com/kubernetes/kubectl/issues/83

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zjj2wry** [comment]
@pwittrock ptal

**Comment by zjj2wry** [comment]
ping @fabianofranz @pwittrock ptal

**Comment by apelisse** [comment]
thank you for doing that!

**Pull request closed without merging**
