### PR TITLE
fix a comment

### PR DESCRIPTION
**Pull request by guoweikuang**
**What this PR does / why we need it**:
fix a comment in pkg/kubelet/dockershim/docker_container.go
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by guoweikuang** [comment]
signed

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/59187)

**Pull request closed without merging**
