### PR TITLE
Updating code to use TempDir in manifest test

### PR DESCRIPTION
**Pull request by nikhiljindal**
Follow up based on comments in https://github.com/kubernetes/kubernetes/pull/59234

```release-note
NONE
```

cc @MrHohn @madhusudancs @G-Harmon

### CODE REVIEW

**Review by madhusudancs — COMMENTED** [review]
/lgtm
/approve

**Comment by G-Harmon** [comment]
Looks like you have to run ./hack/update-bazel.sh?

other than that, code LGTM.

**Comment by nikhiljindal** [comment]
Updated to fix the failing test.
I had a wrong import (ioutil instead of io/ioutil)

**Pull request merged**
