### PR TITLE
Remove lowercasing the import path for the first part of import.

### LINKED ISSUE #20: Imports lowercased
Several packages are lowercased during package generation. This causes import errors if, for instance, your Github account uses uppercase characters.

Some packages are also generated under lowercased paths so these packages are generated under a different directory than your project. For example my project might be in $GOPATH/src/github.com/IanLewis/myapp and code-generator will generate some files under $GOPATH/src/github.com/ianlewis/myapp

### PR DESCRIPTION
**Pull request by n3wscott**
This fixes https://github.com/kubernetes/code-generator/issues/20#issuecomment-389311739

If your project is hosted in a github url with capital letters, the imports get lowercase and golang does not like this.

```release-note
Fixing clientset-gen import casing.
```

### CODE REVIEW

**Comment by n3wscott** [comment]
I do not understand what this failure is telling me.

**Comment by n3wscott** [comment]
the error on the details page for pull-kube-verify : `TypeError: sequence item 0: expected string, NoneType found`

😕

**Comment by n3wscott** [comment]
OK I was able to find a real issue with running verify-codegen.sh and fixed it... lets see now.

**Comment by lavalamp** [comment]
/assign @caesarxuchao 
/assign @sttts 
/unassign @lavalamp

I see a bunch of merge commits; I find life is easier if you fetch & rebase instead of pull / merge.

**Comment by sttts** [comment]
@n3wscott can you add an example to _examples for your case? Would like to see this special case in action.

**Comment by n3wscott** [comment]
> can you add an example to _examples for your case? Would like to see this special case in action.

@sttts good idea, added.

in the code-gen dir, locally if I run `./hack/verify-codegen.sh` I get the following output:
```
Generating deepcopy funcs
Generating defaulters
Generating conversions
Generating clientset for example:v1 example2:v1 at k8s.io/code-generator/_examples/apiserver/clientset
Generating listers for example:v1 example2:v1 at k8s.io/code-generator/_examples/apiserver/listers
Generating informers for example:v1 example2:v1 at k8s.io/code-generator/_examples/apiserver/informers
Generating deepcopy funcs
Generating clientset for example:v1 example2:v1 at k8s.io/code-generator/_examples/crd/clientset
Generating listers for example:v1 example2:v1 at k8s.io/code-generator/_examples/crd/listers
Generating informers for example:v1 example2:v1 at k8s.io/code-generator/_examples/crd/informers
Generating deepcopy funcs
Generating clientset for example:v1 at k8s.io/code-generator/_examples/CamelCased/clientset
Generating listers for example:v1 at k8s.io/code-generator/_examples/CamelCased/listers
Generating informers for example:v1 at k8s.io/code-generator/_examples/CamelCased/informers
diffing ./hack/../_examples against freshly generated codegen
./hack/../_examples up to date.
Smoke testing _examples by compiling...
warning: "./_examples/..." matched no packages
warning: "./_examples/..." matched no packages
```

`go build ${SCRIPT_ROOT}/_examples/...` seems to be an invalid go cli invocation.  Did this change for golang 1.10 ?

**Comment by n3wscott** [comment]
There must have been a change that added `apiserver` and `crd` as supfolders to `_examples`. (I had to change that dir to `_examples` in this PR.) 

I can run:

```
⦿ go build ./_examples/apiserver/...
can't load package: package k8s.io/kubernetes/staging/src/k8s.io/code-generator/_examples/apiserver/apis/example: code in directory /Users/nicholss/go/src/k8s.io/kubernetes/staging/src/k8s.io/code-generator/_examples/apiserver/apis/example expects import "k8s.io/code-generator/_examples/apiserver/apis/example"
can't load package: package k8s.io/kubernetes/staging/src/k8s.io/code-generator/_examples/apiserver/apis/example2: code in directory /Users/nicholss/go/src/k8s.io/kubernetes/staging/src/k8s.io/code-generator/_examples/apiserver/apis/example2 expects import "k8s.io/code-generator/_examples/apiserver/apis/example2"
```

And then I am not sure how other k8s developers have their local setup working with k8s/k8s. Maybe you all checkout into a dir and then symlink the staging/k8s.io dir into your gopath?

**Comment by sttts** [comment]
> And then I am not sure how other k8s developers have their local setup working with k8s/k8s. Maybe you all checkout into a dir and then symlink the staging/k8s.io dir into your gopath?

there is a symlink in kube's vendor dir. That should work.

**Comment by sttts** [comment]
Tried go build `go build ./_examples/crd/apis/example/v1/` from within staging/src/k8s.io/code-generator and that worked. Can you double check in your setup?

**Comment by sttts** [comment]
Also please squash changes: generator changes in one commit, _example test files in one and all generated files in another commit.

**Comment by n3wscott** [comment]
CamelCased repos are not supported.

**Comment by caesarxuchao** [comment]
Can someone kindly explain why this PR is closed? I'm trying to learn the prior arts before reviewing #68484.

> CamelCased repos are not supported.

Not supported by whom?

**Comment by jsturtevant** [comment]
For anyone who lands here a fix has been merged: https://github.com/kubernetes/kubernetes/pull/68484

**Pull request closed without merging**
