### PR TITLE
Add session affinity flags to kubectl expose

### PR DESCRIPTION
**Pull request by brendandburns**

### CODE REVIEW

**Comment by thockin** [comment]
LGTM

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by bgrant0607** [comment]
LGTM.

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by brendandburns** [comment]
self LGTM'd on LGTMs above from @thockin and @bgrant0607

**Comment by alex-mohr** [comment]
@k8s-bot test this [testing build queue, sorry for the noise]

**Comment by alex-mohr** [comment]
Automatic merge from SubmitQueue

**Pull request merged**
