### PR TITLE
[1.24] Cherry Pick of #114766: [Prepare for go1.20] *: Bump versions and fix tests

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
#### What type of PR is this?

/kind failing-test
/priority important-soon

#### What this PR does / why we need it:

Cherry pick of #114766

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/assign @liggitt @dims

### CODE REVIEW

**Comment by liggitt** [comment]
we'll still hold this until we're closer to updating this release branch to go1.20, but would you mind rebasing this on latest release-1.24 to exercise this with the go-compatibility unit and integration tests?

**Comment by liggitt** [comment]
/test pull-kubernetes-dependencies
/test pull-kubernetes-integration
/test pull-kubernetes-integration-go-compatibility
/test pull-kubernetes-unit
/test pull-kubernetes-unit-go-compatibility
/hold cancel

we'll be ready to bump to go1.20 in a couple weeks, so resuming test/prep on this

**Comment by liggitt** [comment]
cc @kubernetes/release-managers 
this would be good to get in after the May patch releases are cut

**Comment by xmudrii** [comment]
/hold
to avoid accidentally merging those PRs before May patch releases are cut

**Comment by liggitt** [comment]
patch releases are out

/hold cancel
/test pull-kubernetes-dependencies
/test pull-kubernetes-integration
/test pull-kubernetes-integration-go-compatibility
/test pull-kubernetes-unit
/test pull-kubernetes-unit-go-compatibility

**Pull request merged**
