### PR TITLE
Curating Owners: pkg/storage

### PR DESCRIPTION
**Pull request by apelisse**
cc @lavalamp @timothysc @liggitt @xiang90 @wojtek-t

In an effort to expand the existing pool of reviewers and establish a
two-tiered review process (first someone lgtms and then someone
experienced in the project approves), we are adding new reviewers to
existing owners files.

If You Care About the Process:
------------------------------

We did this by algorithmically figuring out who’s contributed code to
the project and in what directories.  Unfortunately, that doesn’t work
well: people that have made mechanical code changes (e.g change the
copyright header across all directories) end up as reviewers in lots of
places.

Instead of using pure commit data, we generated an excessively large
list of reviewers and pruned based on all time commit data, recent
commit data and review data (number of PRs commented on).

At this point we have a decent list of reviewers, but it needs one last
pass for fine tuning.

Also, see https://github.com/kubernetes/contrib/issues/1389.

TLDR:
-----

As an owner of a sig/directory and a leader of the project, here’s what
we need from you:

1. Use PR https://github.com/kubernetes/kubernetes/pull/35715 as an example.

2. The pull-request is made editable, please edit the `OWNERS` file to
remove the names of people that shouldn't be reviewing code in the
future in the **reviewers** section. You probably do NOT need to modify
the **approvers** section. Names asre sorted by relevance, using some
secret statistics.

3. Notify me if you want some OWNERS file to be removed.  Being an
approver or reviewer of a parent directory makes you a reviewer/approver
of the subdirectories too, so not all OWNERS files may be necessary.

4. Please use ALIAS if you want to use the same list of people over and
over again (don't hesitate to ask me for help, or use the pull-request
above as an example)

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36522)

### CODE REVIEW

**Comment by apelisse** [comment]
his name is missing from the list, but consider adding "AdoHe"

**Comment by timothysc** [comment]
Gotta be honest here.. This area of the code is critical to the operation of the cluster, without it, nothing works.  So I'm reluctant to open it, unless the history is harrowed to just this year as it's been completely re-jig'd.  

Also, I don't believe we've witnessed a delayed review period in this area of the codebase, when compared to others.

**Comment by apelisse** [comment]
@timothysc Remember that the `approvers` list is not changing, and that each pull-request will still be gated by the same current set of people.

I would be completely fine with keeping the list as narrow as possible (including keeping it as it is now) if needed.

What's your opinion other approvers: @lavalamp @liggitt @xiang90 @wojtek-t ?

**Comment by xiang90** [comment]
LGTM. I would suggest to move @hongchaodeng from reviewer to approver list if other people also agree.

**Comment by timothysc** [comment]
LGTM  

> I would suggest to move @hongchaodeng from reviewer to approver list if other people also agree.

+1

**Comment by lavalamp** [comment]
I think I would still be more comfortable if we kept this approvers list very tight.

this LGTM now.

**Comment by liggitt** [comment]
> I think I would still be more comfortable if we kept this approvers list very tight.
> this LGTM now.

I think I agree.

**Comment by philips** [comment]
@xiang90 @timothysc @lavalamp @liggitt On the topic of adding new approvers, my understand is that we aren't adding new approvers anywhere in the tree until all of the reviewers get merged: https://github.com/kubernetes/kubernetes/pull/37640

**Comment by apelisse** [comment]
Rebased lavalamp's commits. Please lgtm @philips

**Comment by apelisse** [comment]
@k8s-bot bazel test this

**Comment by apelisse** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
