### PR TITLE
Add missing test cases for `RunAsGroup` and `SetRunAsGroup` methods

### PR DESCRIPTION
**Pull request by mengjiao-liu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Improve unit test coverage: Add missing test cases for `RunAsGroup` and `SetRunAsGroup` methods.

#### Which issue(s) this PR fixes:

related #13868

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/area test
/sig testing

### CODE REVIEW

**Comment by mengjiao-liu** [comment]
Request review @brendandburns @dchen1107 @dims @lavalamp @smarterclayton @thockin

**Comment by mengjiao-liu** [comment]
ping @smarterclayton

**Comment by mengjiao-liu** [comment]
Request Review @dchen1107 @dims @thockin

**Review by endocrimes — APPROVED** [review]
/lgtm

**Review by ehashman — COMMENTED** [review]
/lgtm
/assign @dims

**Comment by dims** [comment]
/approve
/lgtm

@ehashman need this for v1.24? please add a milestone if so (qualifies for test freeze)

**Pull request merged**
