### PR TITLE
Fix panic when using `kubeadm init` with vsphere cloud-provider

### LINKED ISSUE #44603: kubelet panic `invalid memory address or nil pointer dereference` using `kubeadm init` with vsphere cloud-provider
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

`BUG REPORT`

**Kubernetes version** (use `kubectl version`):

`v1.6.1`

**Environment**:
- **Cloud provider or hardware configuration**: 
4 VMs via ESXI 6.5 on a single physical server
- **OS** (e.g. from /etc/os-release): 
Ubuntu 16.04.2
- **Kernel** (e.g. `uname -a`): 
`Linux kube-master-1 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- **Install tools**: 
kubeadm `1.6.1-00`
- **Others**:
docker `1.12.6`

**What happened**:

When bootstraping a new cluster with `kubeadm v1.6.1` and the `vsphere` cloud-provider, the `kubelet` cant' start because of the following `invalid memory address or nil pointer dereference` panic error.

```
Apr 18 10:33:09 kube-master-1 kubelet[14075]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 18 10:33:09 kube-master-1 kubelet[14075]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x120cd37]
Apr 18 10:33:09 kube-master-1 kubelet[14075]: goroutine 1 [running]:
Apr 18 10:33:09 kube-master-1 kubelet[14075]: panic(0x2d9d660, 0xc420010040)
Apr 18 10:33:09 kube-master-1 kubelet[14075]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
Apr 18 10:33:09 kube-master-1 kubelet[14075]: k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere.getVMName(0xc42034d440, 0xc420745d90, 0x0, 0x0, 0x0, 0x0)
Apr 18 10:33:09 kube-master-1 kubelet[14075]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vsphere.go:255 +0x6a7
Apr 18 10:33:09 kube-master-1 kubelet[14075]: k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere.newVSphere(0xc4203bdfe8, 0x4, 0xc420270aa0, 0x14, 0xc420396400, 0xd, 0xc420396608, 0x3, 0x1, 0xc420396b40, ...)
Apr 18 10:33:09 kube-master-1 kubelet[14075]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vsphere.go:285 +0x15b
Apr 18 10:33:09 kube-master-1 kubelet[14075]: k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere.init.1.func1(0x4d38520, 0xc420026708, 0x7ffdd2920d33, 0x7, 0xc420296cc8, 0xc4208a9201)
Apr 18 10:33:09 kube-master-1 kubelet[14075]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/providers/vsphere/vsphere.go:204 +0xa8
Apr 18 10:33:09 kube-master-1 kubelet[14075]: k8s.io/kubernetes/pkg/cloudprovider.GetCloudProvider(0x7ffdd2920d33, 0x7, 0x4d38520, 0xc420026708, 0x0, 0x0, 0x0, 0x0)
Apr 18 10:33:09 kube-master-1 kubelet[14075]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/plugins.go:87 +0xda
Apr 18 10:33:09 kube-master-1 kubelet[14075]: k8s.io/kubernetes/pkg/cloudprovider.InitCloudProvider(0x7ffdd2920d33, 0x7, 0x7ffdd2920d4a, 0x1c, 0x0, 0x0, 0x0, 0x0)
Apr 18 10:33:09 kube-master-1 kubelet[14075]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/cloudprovider/plugins.go:119 +0x141
Apr 18 10:33:09 kube-master-1 kubelet[14075]: k8s.io/kubernetes/cmd/kubelet/app.run(0xc420953800, 0x0, 0xc4208a9ec0, 0x456eb0)
Apr 18 10:33:09 kube-master-1 kubelet[14075]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:424 +0x1567
Apr 18 10:33:09 kube-master-1 kubelet[14075]: k8s.io/kubernetes/cmd/kubelet/app.Run(0xc420953800, 0x0, 0x22, 0xc4203bd640)
Apr 18 10:33:09 kube-master-1 kubelet[14075]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:285 +0x39
Apr 18 10:33:09 kube-master-1 kubelet[14075]: main.main()
Apr 18 10:33:09 kube-master-1 kubelet[14075]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/kubelet.go:48 +0x92
```

Moreover, it is not possible to specify the [VMName](https://github.com/kubernetes/kubernetes/blob/67f2a7cc00931cf9df909e6665ab9ece4b8497b3/pkg/cloudprovider/providers/vsphere/vsphere.go#L137) manually in the cloud-provider config file because of the following error:

```
Apr 18 10:30:39 kube-master-1 kubelet[13962]: error: failed to run Kubelet: could not init cloud provider "vsphere": invalid variable: section "Global" subsection "" variable "vm-name"
```

**What you expected to happen**:

My `v1.6.1` kubernetes cluster initialized on my master node with `vsphere` cloud-provider enabled.

**How to reproduce it** (as minimally and precisely as possible):

*/etc/systemd/system/kubelet.service.d/10-kubeadm.conf*

```
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true"
Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"
Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"
Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"
Environment="KUBELET_EXTRA_ARGS=--cloud-provider=vsphere --cloud-config=/etc/kubernetes/cloud-config"
ExecStart=
ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_EXTRA_ARGS
```

*/etc/kubernetes/cloud-config*

```
[Global]
        user = kube
        password = {PASSWORD}
        server = {ESXI-IP}
        port = 443
        insecure-flag = 1
        datacenter = ha-datacenter
        datastore = datastore-ssd-2
        working-dir =
[Disk]
    scsicontrollertype = pvscsi
```

*/etc/kubernetes/kubeadm.conf*

```
kind: MasterConfiguration
apiVersion: kubeadm.k8s.io/v1alpha1
cloudProvider: vsphere
```

*kubeadm init*
```
root@kube-master-1:/etc/kubernetes# kubeadm init --skip-preflight-checks --config=/etc/kubernetes/kubeadm.conf --apiserver-advertise-address 192.168.0.10 --kubernetes-version v1.6.1 --token {TOKEN}
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.6.0
[init] Using Authorization mode: RBAC
[init] WARNING: For cloudprovider integrations to work --cloud-provider must be set for all kubelets in the cluster.
	(/etc/systemd/system/kubelet.service.d/10-kubeadm.conf should be edited for this purpose)
[preflight] Skipping pre-flight checks
[preflight] Starting the kubelet service
[certificates] Generated CA certificate and key.
[certificates] Generated API server certificate and key.
[certificates] API Server serving cert is signed for DNS names [kube-master-1 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 {PUBLIC-IP}]
[certificates] Generated API server kubelet client certificate and key.
[certificates] Generated service account token signing key and public key.
[certificates] Generated front-proxy CA certificate and key.
[certificates] Generated front-proxy client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/scheduler.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/controller-manager.conf"
[apiclient] Created API client, waiting for the control plane to become ready
...
```

**Anything else we need to know**:

Each VM has 2 network interfaces, one with a public IP (requirement of `online.net` when doing virtualisation on a single physical server) and one with a private IP.

*/etc/docker/daemon.json*

```json
{
    "ip-masq": false, 
    "iptables": false, 
    "live-restore": true, 
    "log-level": "warn", 
    "log-opts": {
        "max-file": "10", 
        "max-size": "100m"
    }, 
    "storage-driver": "overlay2"
}
```

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Check if the reference is nil when finding machine reference by UUID.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #44603

**Special notes for your reviewer**:
This is just a quick fix for the panic.

**Release note**:

```release-note
Fix panic when using `kubeadm init` with vsphere cloud-provider.
```

### CODE REVIEW

**Review by luxas — COMMENTED** [review]
LGTM

Could you add some more testing so that this doesn't happen again please?

**Comment by xiangpengzhao** [comment]
Thanks @luxas ! Will add a test case.

**Comment by xiangpengzhao** [comment]
Should we cherry-pick this on v1.6.1? @sdurrheimer find this issue on that version.

**Comment by xiangpengzhao** [comment]
Test case added. @luxas PTAL

**Comment by divyenpatel** [comment]
@BaluDontu @tusharnt

**Review by kerneltime — APPROVED** [review]

**Comment by xiangpengzhao** [comment]
@kerneltime Should we cherry-pick this?

**Comment by kerneltime** [comment]
This is not a critical bug, I don't mind approving a cherry-pick if you want to do it. I would wait for the fix @divyenpatel is working on as mentioned in the original issue #44603

**Comment by xiangpengzhao** [comment]
@kerneltime Thanks Ritesh ! Then I won't cherry-pick this :)

**Pull request merged**
