### PR TITLE
Make root approvers list non-recursive, shift from individuals to sig/subproject aliases

### LINKED ISSUE #112867: All reviewers and approvers in root OWNERS are from google
Please see:
https://github.com/kubernetes/kubernetes/blob/master/OWNERS#L5-L18

There are six approvers and reviewers, ALL of them are from google. This is not a good look for a really diverse project like Kubernetes with contributors from all over the world.

/assign @dchen1107 @lavalamp @smarterclayton @thockin @wojtek-t @liggitt

Yes, we keep saying that needs to be solved by fixing things in prow and that it is ok to leave it as is ... BUT this is still not right.

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Restructures root approvers to be limited to files in the root directory (primarily OWNERS_ALIASES and dependency-related files).

Moves current root approvers down into relevant subdir OWNERS files.

Best reviewed commit by commit

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/112867

```release-note
NONE
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
Thanks a lot for taking care of it Jordan!

/lgtm

**Review by thockin — COMMENTED** [review]
ACK from me

**Comment by liggitt** [comment]
/assign @dchen1107 @smarterclayton 
for last two acks

**Comment by dchen1107** [comment]
/lgtm 

Thanks for pushing it through.

**Pull request merged**
