### PR TITLE
Add a flag to disable dumpig logs after e2e test failure

### PR DESCRIPTION
**Pull request by gmarek**
cc @kubernetes/sig-testing

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM

**Comment by gmarek** [comment]
Need for scalability testing.

**Comment by ixdy** [comment]
> Needed for scalability testing.

Do you have an issue filed on why you need this?

**Comment by jayunit100** [comment]
I was thinking we could just use the DebugF stuff for this but maybe that is orthogonal

**Comment by jayunit100** [comment]
@gmarek i think one alternative, if we don't want yet another flag, is to use #24615 so that we can use native `-v` glog stuff to control this, rather than add yet another flag  .  At the heart of the problem is bumping log granularity controls to something that is more natural for users to select against.

**Comment by gmarek** [comment]
I didn't file an issue - the problem is that when we're testing 2k Node clusters and a test fails, we need to wait for ~1h for this dump to finish. I'll be OK with anything that can accomplish the same thing, if it can be merged this night (read: today in US).

**Comment by jayunit100** [comment]
yup, i saw the same problem. @gmarek if we
- p0 the other patch, 
- then all you need to do is move those logs to use `Debugf` instead of `Logf`, and 
- users can launch with `-v 2` and won't see those noisy per-node logs anymore.
that kills two birds w/ one stone :):)

**Comment by gmarek** [comment]
I'm not quite sure it's enough - IIUC it'll still loop through everything, but it won't print it out. It'll help a bit, but gating all the looping is preferable.

**Comment by wojtek-t** [comment]
I agree with @gmarek - we want to avoid not only printing this information, but most of all gathering it.

**Comment by wojtek-t** [comment]
It's gathering that is expensive - not logging it.

**Comment by jayunit100** [comment]
@gmarek @wojtek-t agreed, implemented this:

```
func DumpAllNamespaceInfo(c *client.Client, namespace string) {
	if glog.V(3) {
		Logf("Skipping namespace info debugging, since the verbosity is lower than 3.")
		return
	}
```

**Pull request merged**
