### PR TITLE
Add contrib netperf-tester tool.

### PR DESCRIPTION
**Pull request by BenTheElder**
Adds a test-tool/script in contrib for running netperf latency tests on a k8s cluster.

### CODE REVIEW

**Comment by BenTheElder** [comment]
Here are some example results from a GCE cluster.
- Raw CSV data: https://gist.github.com/BenTheElder/8ad343913fbe876e219a
- Histogram of mean latency:
gce-netperf-histogram

Tests were run with:
```
export KUBERNETES_PROVIDER=gce
export NUM_MINIONS=4
export KUBE_ENABLE_CLUSTER_MONITORING=google
export KUBE_ENABLE_CLUSTER_UI=false
cluster/kube-up.sh
contrib/for-tests/netperf-tester/run.sh --output=$HOME/gce-userspace-1000rr-number1000.csv
```

**Comment by thockin** [comment]
you're going to have to re-offer this against https://github.com/kubernetes/contrib - all contrib repos moved there.  Sorry.

**Comment by BenTheElder** [comment]
Ah, ok. I'll do that.

**Pull request closed without merging**
