### PR TITLE
Lint ttl_controller

### PR DESCRIPTION
**Pull request by Git-Jiro**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
ref #68026

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by spiffxp — COMMENTED** [review]
/ok-to-test
/approve
for the hack/ changes

**Comment by Git-Jiro** [comment]
Hi @spiffxp,
do you know whom of https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/OWNERS is most likely to have time to take a look at this PR?

**Review by janetkuo — APPROVED** [review]

**Comment by Git-Jiro** [comment]
Hi @janetkuo!
Can you add the missing lgtm label as well?

**Pull request merged**
