### PR TITLE
cluster/gce:  Move build-kube-env to util.sh

### PR DESCRIPTION
**Pull request by yifan-gu**
This allows all 3 distros(coreos, debian, trusty) to share the same
build-kube-env.

cc @dchen1107 @andyzheng0831

### CODE REVIEW

**Comment by yifan-gu** [comment]
Something to point out: This PR will break kube-up for coreos/gce, until following PRs are merged (#17241 #17243)

**Comment by dchen1107** [comment]
Can we not break existing kube-up for gce/coreos? We do have ppl running coreos cluster on gce, not many, but still such breakage should be avoid and can be avoided.

**Comment by andyzheng0831** [comment]
Agree with @dchen1107 about avoiding breakage. Maybe we should hold fire until the required PR is merged. Or you can have this change but let coreos keep using the old function build-kube-env defined in  cluster/gce/coreos/helper.sh. After the PR for processing yaml in coreos is merged, you source the function in util.sh

**Comment by yifan-gu** [comment]
@dchen1107 @andyzheng0831 I updated the kube-env service in node.yaml to change the yaml to env file on the fly, I am testing to see if that breaks or not.
This will introduce some merge conflicts, but that can be handled :)

**Comment by yifan-gu** [comment]
Updated, the core/gce should not be broken when this is merged.

**Comment by yifan-gu** [comment]
Rebased

**Comment by yifan-gu** [comment]
Saw errors while starting the jenkins e2e from https://github.com/kubernetes/kubernetes/pull/17240#issuecomment-157507474

```
+++ Staging server tars to Google Storage: gs://kubernetes-staging-b6e85ca3f3/devel-0
+++ kubernetes-server-linux-amd64.tar.gz uploaded (sha1 = 1a3570a1adcca46244ff3971cd79079fddaa2f26)
+++ kubernetes-salt.tar.gz uploaded (sha1 = 7302776818d15bb6bab135d1f492ab977142bf8b)
Starting master and configuring firewalls
ERROR: (gcloud.compute.firewall-rules.create) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins-pull/global/firewalls/pull-e2e-0-master-https' already exists

ERROR: (gcloud.compute.disks.create) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins-pull/zones/us-central1-f/disks/pull-e2e-0-master-pd' already exists

2015/11/17 21:07:09 e2e.go:309: Error running up: exit status 1
2015/11/17 21:07:09 e2e.go:305: Step 'up' finished in 14.92001889s
2015/11/17 21:07:09 e2e.go:141: Error starting e2e cluster. Aborting.
exit status 1
```

Seems there are resources not being cleaned up??

**Comment by yifan-gu** [comment]
e2e is happy now, do you want to review this? @andyzheng0831 @dchen1107

**Comment by andyzheng0831** [comment]
Sorry for the late reply. I agree that we need this functionality. But I am wondering if we should do it through such a big code block. If comparing the yaml format kube-env with shell style, there are two differences: (1) replace the first "" '" with "="; (2) remove the ' at end of a line.

**Comment by yifan-gu** [comment]
> Sorry for the late reply. I agree that we need this functionality. But I am wondering if we should do it through such a big code block. If comparing the yaml format kube-env with shell style, there are two differences: (1) replace the first "" '" with "="; (2) remove the ' at end of a line.

Isn't this what I do in https://github.com/kubernetes/kubernetes/pull/17240/files#diff-85a752942460b9e24dd30d59ca69ca96R84

Before this PR, the coreos version of `build-kube-env` is copyting the yaml to the shell style, creating two almost identical big pieces. And in this PR I reverted the changes, so all distros share the same yaml, and if it's coreos, we will do a sed to change to the shell style.

Sorry, seems I didn't follow what you mean here?

**Comment by yifan-gu** [comment]
But I should change the doc in `trusty/helper.sh` as it no longer imports the `debian/helper.sh` to reuse the `build-kube-env`, because `build-kube-env` in now in the `util.sh`

**Comment by andyzheng0831** [comment]
Ah, sorry I messed it with another PR. 
I guess you may need to sync your PR to head, as https://github.com/kubernetes/kubernetes/pull/16960 conflicts with this PR. Moreover, please update the trusty/helper.sh comments to reflect this change.

**Comment by yifan-gu** [comment]
@andyzheng0831 I should point out that this PR essentially just moves the `build-kube-env` from `debian/helper.sh` into `util.sh`

**Comment by yifan-gu** [comment]
@andyzheng0831 I already rebased. Also updated the comments.

**Comment by andyzheng0831** [comment]
LGTM

**Comment by yifan-gu** [comment]
Made a force push to trigger the tests without changing anything.
From the log of the last run of the e2e tests, seems it failed because the master is suddenly not reachable during the tests. Not sure about the reason.

**Comment by dchen1107** [comment]
LGTM

**Pull request merged**
