### PR TITLE
Fixing etcd version for 1.10.X kubernetes

### LINKED ISSUE #56254: incorrect etcd version in constants.go
constants.go uses non existing etcd version for k8s 1.10.0.
/kind bug
/sig cluster-lifecycle

### PR DESCRIPTION
**Pull request by sbezverk**
Closes #56254

### CODE REVIEW

**Review by luxas — APPROVED** [review]
/lgtm

**Review by luxas — COMMENTED** [review]
/lgtm

**Comment by jberkus** [comment]
/priority critical-urgent

/remove-priority important-soon

adjusting priorities for code freeze

**Pull request merged**
