### PR TITLE
Pass HTTP{,S}_PROXY into docker image build

### LINKED ISSUE #3687: Make it easy to build with HTTP proxy
Hi
when i tried to compile kubernetes in proxy network its give below error 

```
Step 5 : RUN go get code.google.com/p/go.tools/cmd/cover github.com/tools/godep
 ---> Running in 7183a3b93842
package code.google.com/p/go.tools/cmd/cover: Get https://code.google.com/p/go/source/checkout?repo=tools: dial tcp 173.194.33.168:443: i/o timeout
# cd .; git clone https://github.com/tools/godep /go/src/github.com/tools/godep
Cloning into '/go/src/github.com/tools/godep'...
fatal: unable to access 'https://github.com/tools/godep/': Failed to connect to github.com port 443: Connection timed out
package github.com/tools/godep: exit status 128
time="2015-01-21T11:03:30-08:00" level="info" msg="The command [/bin/sh -c go get code.google.com/p/go.tools/cmd/cover github.com/tools/godep] returned a non-zero code: 1"
```

i think this error is because of proxy setting

### PR DESCRIPTION
**Pull request by anfernee**
**What this PR does / why we need it**: Make it easy to build with HTTP_PROXY and HTTPS_PROXY

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3687

**Special notes for your reviewer**:

**Release note**:
```release-note
none
```

### CODE REVIEW

**Comment by anfernee** [comment]
cc @zmerlynn @blecker

**Comment by cblecker** [comment]
Repeating my comment (https://github.com/kubernetes/kubernetes/pull/54705#issuecomment-368604777):
> I ran a bunch of testing locally, and it looks like Docker has changed the way proxies are handled. In Docker 17.07 and later, you configure a proxy directly in the docker client, and it manages that from a network overlay level, instead of in containers: https://docs.docker.com/network/proxy/

**Comment by anfernee** [comment]
OK. Since docker 17.07 fixed it, closing this PR.

**Pull request closed without merging**
