### PR TITLE
Kubemark using cobra commands 

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by shyamjvs** [comment]
/test pull-kubernetes-kubemark-e2e-gce-big

Running kubemark-500 presubmit just as an extra check. LGTM overall.

**Comment by shyamjvs** [comment]
@hzxuzhonghu Could you please squash the commits?

**Comment by hzxuzhonghu** [comment]
sure

**Comment by hzxuzhonghu** [comment]
@shyamjvs done

**Comment by shyamjvs** [comment]
Thanks @hzxuzhonghu 

/lgtm
/approve no-issue

**Pull request merged**
