### PR TITLE
optimize syncLoopIteration performance and  reduce pod startup latency

### PR DESCRIPTION
**Pull request by snowplayfire**
**What type of PR is this?**
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Improve syncLoopIteration performance, reduce pod startup latency

**Which issue(s) this PR fixes**:
Deploy some pods in one node(about 20 pods in my cluster), find some pods take too long to start. 

kubelet log:

```
I1011 11:05:10.922156   22527 config.go:414] Receiving a new pod "testpod_testns"

...
  
I1011 11:07:10.584241   22527 kubelet.go:1909] SyncLoop (ADD, "api"): "testpod_testns"
```
We can see the pod's (named testpod) SyncLoop waits for a long time about 2 minutes.

Some other operations consume the 2 minutes such as:
```
SyncLoop (housekeeping)
SyncLoop (ADD, "api"):
SyncLoop (RECONCILE, "api")
SyncLoop (PLEG):
```

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
/ok-to-test

Thanks for your pr!

Could you share more about your thought process behind switching the `Handle*` processes to async? I definitely see how there could be performance advantages, but I'm wondering if this introduces risks of logic bugs? The `syncLoopIteration` is a fairly critical path, so I think we always want to be very cautious with changes to it :)

Would love @tallclair and/or @dashpole to weigh in too :)

**Comment by dashpole** [comment]
/hold
Pod admissions, removals, and updates must be serialized.  I can't tell from your log what caused it to take 2 minutes... It would be useful to know what was going on in the kubelet's housekeeping function during that time that took so long.

**Pull request closed without merging**
