### PR TITLE
Remove unused KUBE_TEST_API logic

### LINKED ISSUE #87075: Unit tests with coverage failed due to KUBE_TEST_API variable unset
**What happened**:
```
$ make test KUBE_COVER=y
hack/make-rules/test.sh: line 277: KUBE_TEST_API: unbound variable
!!! [0110 20:03:49] Call tree:
!!! [0110 20:03:49]  1: hack/make-rules/test.sh:368 runTests(...)
make: *** [Makefile:185: test] Error 1

```
**What you expected to happen**:

unit tests with coverage succeed

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Cleans up unused logic remove KUBE_TEST_API vars removed in https://github.com/kubernetes/kubernetes/pull/86256

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/87075

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Comment by liggitt** [comment]
fixed shellcheck error by removing now-unused envvar:

```
In ./hack/make-rules/test.sh line 38:
  SHA1SUM="sha1sum"
  ^-----^ SC2034: SHA1SUM appears unused. Verify use (or export if used externally).
```

**Pull request merged**
