### PR TITLE
[examples] high-availability 1x upgrade

### PR DESCRIPTION
**Pull request by jayunit100**
do not merge, wip.  but i have some questions for google folks so creating a PR to start a dialogue.

@brendandburns @mikedanese 
- what container tags should i use? 
- I  don't see a way to browse the gcr.io repo from the web.  

cc @timothysc @rrati @pmorie

### CODE REVIEW

**Comment by mikedanese** [comment]
cc @bgrant0607

**Comment by bgrant0607** [comment]
Please convert the json to yaml and change .manifest to .yaml.

**Comment by bgrant0607** [comment]
Browse gcr using gcs API. For example:
```
https://www.googleapis.com/storage/v1/b/kubernetes-release/o?prefix=release/v0.19&fields=items(name)
```

**Comment by jayunit100** [comment]
@bgrant0607, so, need the exact tags for the docker containers which we want in this release.   

From what i can tell, it seems there isnt a "gcr.io/google_containers/kube-controller-manager" latest tagged image.  I wasn't able to find anyhting in the GCR json fragments from the schema above.  probably im missing something obvious here :)... but in any case, can you give me a hint?

**Comment by bgrant0607** [comment]
I'm not sure we push every release to gcr. We do push images to gcs. IIRC, our installation scripts+salt download the images and copy them directly to the master.

I can see the files here:
```
https://www.googleapis.com/storage/v1/b/kubernetes-release/o?prefix=release/v1.0.1&fields=items(name)
```

That said, I did:
```
$ gcloud docker pull gcr.io/google_containers/kube-controller-manager
Pulling repository gcr.io/google_containers/kube-controller-manager
fffe58ad0de2: Download complete 
cf2616975b4a: Download complete 
6ce2e90b0bc7: Download complete 
8c2e06607696: Download complete 
$ docker images
cr.io/google_containers/kube-apiserver            9680e782e08a1a1c94c656190011bd02   089cff502208        6 weeks ago         37.54 MB
gcr.io/google_containers/kube-controller-manager   fda24638d51a48baa13c35337fcd4793   fffe58ad0de2        6 weeks ago         30.39 MB
```

If those dates are right, they're not the latest release.

cc @brendandburns

**Comment by jayunit100** [comment]
well.  interestingly i just discovered that our existing vagrant (salt) recipes already have **containerized all the master services**.... so examples/high-availability** ~ almost redundant (w/ exception of podmaster, which isnt used the in salt recipes).     So maybe we should merge this entire directory as a salt option, rather than maintain it separately ?

**Comment by derekwaynecarr** [comment]
It tells Salt to run the latest high state over all nodes for the current
built release - which will update the images for the containers during the
docker import step from the local tar.

The Salt stuff will also respect any changes you made to manifests or other
things unrelated to the containers for how the node is configured.

kube-up and kube-push do the exact same things when it comes to Salt, but
the bash script that is run for each command before telling Salt to do its
high state differs and is really provider specific in current model.  I
think for most of them though kube-push is just salt high state but kube-up
differs more widely for initial config (cert gen , etc)

**Comment by bgrant0607** [comment]
I need someone else to finish the review.

**Comment by jayunit100** [comment]
I'm not sure on the container versions we should be using ; so we can't merge just yet....

**Comment by mikedanese** [comment]
Please address @bgrant0607's comment:

> Please convert the json to yaml and change .manifest to .yaml.

**Comment by bgrant0607** [comment]
Re. https://github.com/GoogleCloudPlatform/kubernetes/pull/11337#issuecomment-123801302:

Yes, we should merge this as an optional configuration rather than keeping it separate.

**Comment by jayunit100** [comment]
will do (re: yaml).

- are we standardizing on YAML across the code base ?
- i still dont know what 1x images to pull down for this, so its frozen in this state at the moment. 

i will circle back around tonite after i take care of a couple of other things.

**Comment by bgrant0607** [comment]
Yes, we are trying to standardize on YAML.

Re. images: I don't think they've been pushed to GCR, unfortunately. See, for instance, #11751 and #8686. I believe we currently distribute images for the components the same way we distributed raw binaries.

cc @zmerlynn @lavalamp

**Comment by pmorie** [comment]
@jayunit100 We generally have used tags like `0.1`, `0.2` etc for test images.

**Comment by jayunit100** [comment]
Lets close this, pending #17301 , as this will all be subsumed by native lease/locking/masterelectng in one way or another, and then, wont need a separate vagrant recipe - instead HA will be the norm.

**Pull request closed without merging**
