### PR TITLE
KEP-3221: Promote StructuredAuthorizationConfiguration to GA

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Promotes https://github.com/kubernetes/enhancements/issues/3221 to GA

#### Does this PR introduce a user-facing change?
```release-note
kube-apiserver: Promoted the `StructuredAuthorizationConfiguration` feature gate to GA. The `--authorization-config` flag now accepts `AuthorizationConfiguration` in version `apiserver.config.k8s.io/v1` (with no changes from `apiserver.config.k8s.io/v1beta1`).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3221-structured-authorization-configuration
- [Other doc]: https://kubernetes.io/docs/reference/access-authn-authz/authorization/#authz-config-example
```

/sig auth
/cc @ritazh @palnabarun

### CODE REVIEW

**Comment by sftim** [comment]
Changelog suggestion
```diff
-kube-apiserver: The StructuredAuthorizationConfiguration feature is promoted to GA, and the --authorization-config file `AuthorizationConfiguration` version promoted to `apiserver.config.k8s.io/v1`
+kube-apiserver: Promoted the `StructuredAuthorizationConfiguration` feature gate to GA. Accompanying this, switched the the `--authorization-config` file format `AuthorizationConfiguration` to `apiserver.config.k8s.io/v1` (with no changes from `apiserver.config.k8s.io/v1beta1`)
```

Please fact check this before accepting!

**Comment by liggitt** [comment]
> Changelog suggestion

tweaked and updated

**Pull request merged**
