### PR TITLE
Extract a number of short description strings for translation

### PR DESCRIPTION
**Pull request by brendandburns**
@fabianofranz 
@kubernetes/sig-cli-pr-reviews 

Follow on for https://github.com/kubernetes/kubernetes/pull/39223

### CODE REVIEW

**Comment by brendandburns** [comment]
ping to @jbeda for lgtm/approve?

**Comment by fabianofranz** [comment]
@brendandburns I'll add an OWNERS file to `translations/kubectl` with the same folks from `pkg/kubectl` so that we can handle this. I'll try to be faster in reviews to avoid Rebases From Hell®.  :)

**Comment by brendandburns** [comment]
pre-emptive lgtm on rebase to avoid rebase hell...

**Pull request merged**
