### PR TITLE
removing generic_scheduler todo after discussion (#46027)

### PR DESCRIPTION
**Pull request by yastij**
**What this PR does / why we need it**:

**Which issue this PR fixes** #46027 

**Special notes for your reviewer**: just a quick clean cc @wojtek-t 

**Release note**:
```release-note
```

### CODE REVIEW

**Comment by yastij** [comment]
CLA signed

**Comment by wojtek-t** [comment]
@k8s-bot ok to test

**Comment by k82cn** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by k82cn** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by yastij** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by wojtek-t** [comment]
@yastij - FYI there is no point in kicking federation, because it's broken and not required for merging.

**Comment by yastij** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Pull request merged**
