### PR TITLE
Powershell script to start kubelet and kube-proxy

### PR DESCRIPTION
**Pull request by jbhurat**
**What this PR does / why we need it**:
This PR adds a powershell script to run kubelet and kube-proxy on Windows. It expects the required arguments like `API Server` location and uses appropriate defaults.

**Which issue this PR fixes** : 
fixes # https://github.com/kubernetes/kubernetes/issues/34270

**Special notes for your reviewer**:
This PR is for supporting Windows Server Containers for k8s, the work for which is covered under https://github.com/kubernetes/features/issues/116
This PR should be merged after https://github.com/kubernetes/kubernetes/pull/31707 and https://github.com/kubernetes/kubernetes/pull/36079 PRs are merged

**Release note**:

```release-note
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36250)

### CODE REVIEW

**Comment by jbhurat** [comment]
cc: @brendandburns

**Comment by jbhurat** [comment]
@eparis, can you please review this PR when you get a chance. https://github.com/kubernetes/kubernetes/pull/31707 has been merged and https://github.com/kubernetes/kubernetes/pull/36079 has lgtm label and should be merged soon

**Comment by eparis** [comment]
@brendondburns I'm traveling until next week. Can't figure out how to reassign in the mobile UI...

**Comment by eparis** [comment]
@brendandburns

**Comment by dragon9783** [comment]
@jbhurat I have a question about launch kubelet on window, how can i configure kubelet output log to window Event Log, and i see that there is RedirectStandError flag in script, How can i redirect kubelet log to Event Log using this flag? thanks

**Comment by jbhurat** [comment]
@dragon9783 I don't think there is way the output logs be configured to log to Event Log, without having an intermediary process which would tail the log file and write to event log.

**Comment by dragon9783** [comment]
@jbhurat thank you

**Comment by jbhurat** [comment]
@k8s-bot kops aws e2e test this

**Comment by xiaolou86** [comment]
Can nssm limit the number of logfiles? That's mean, if the number exceeds N, the new log file will replace the oldest one.

**Comment by jbhurat** [comment]
@xiaolou86 I went through the documentation for `nssm` and I don't think it is possible to limit the number of log files.

**Comment by eparis** [comment]
@k8s-bot test this

**Comment by brendandburns** [comment]
@k8s-bot cri e2e test this

/lgtm

**Pull request merged**
