### PR TITLE
Manual cherry pick of #119800: Fixes CEL estimated cost to propagate result sizes correctly

### PR DESCRIPTION
**Pull request by jpbetz**
Cherry pick of #119800 on release-1.26.

#119800: Fixes CEL estimated cost to propagate result sizes correctly

The version bump was performed manually since we depend on a different CEL version in 1.27 than on 1.28 and master.

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fixed a bug where CEL expressions in CRD validation rules would incorrectly compute a high estimated cost for functions that return strings, lists or maps.
The incorrect cost was evident when the result of a function was used in subsequent operations.
```

### CODE REVIEW

**Comment by jpbetz** [comment]
/priority important-soon
/sig api-machinery

/hold
Until https://github.com/kubernetes/kubernetes/pull/119800 merges

**Comment by jpbetz** [comment]
/hold cancel
This is ready for backport.

/assign @jeremyrickard

**Comment by jpbetz** [comment]
/hold cancel
This is updated with fixes from https://github.com/kubernetes/kubernetes/pull/120097 and ready to merge.

**Review by Verolop — COMMENTED** [review]
/lgtm

**Pull request merged**
