### PR TITLE
cleanup: remove scheduler_perf unused parameters

### PR DESCRIPTION
**Pull request by likakuli**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
remove unused parameters for scheduler_perf
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
cc @macsko 

Is the verbosity level actually unused? I think we want to run the tests at level 2.

**Comment by macsko** [comment]
> Is the verbosity level actually unused? I think we want to run the tests at level 2.

It looks like we run the tests at level 0 at the moment. #111395 removed rest of the code related to `MinVerbosity` variable and didn't introduce any replacement.

**Comment by likakuli** [comment]
https://github.com/kubernetes/kubernetes/blob/cee43048c72403ae0f56f04053cb7e3361de1415/test/integration/scheduler_perf/main_test.go#L38-L42

defaultVerbosity is 2 now

**Comment by macsko** [comment]
> https://github.com/kubernetes/kubernetes/blob/cee43048c72403ae0f56f04053cb7e3361de1415/test/integration/scheduler_perf/main_test.go#L38-L42
> 
> defaultVerbosity is 2 now

That's right, thanks for clarifying.

**Pull request merged**
