### PR TITLE
kubeadm: improve kubeadm command output

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
kubeadm: improve kubeadm command output

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#1627
Ref: #79267

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/cc @luxas @neolit123 @rosti

### CODE REVIEW

**Review by Klaven — COMMENTED** [review]
looks good. I did a few quick greps and did not see anything else to change! thanks!

**Review by luxas — APPROVED** [review]
/lgtm
/approve
/milestone v1.15

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Comment by neolit123** [comment]
cc @kubernetes/patch-release-team

**Comment by SataQiu** [comment]
PTAL @kubernetes/patch-release-team

**Review by neolit123 — APPROVED** [review]

**Pull request merged**
