### PR TITLE
to have a libvirt-coreos cluster running

### PR DESCRIPTION
**Pull request by sdminonne**
@lhuard1A thanks to have  a look at this. At least to have libvirt-coreos cluster to boostrap

### CODE REVIEW

**Comment by jlowdermilk** [comment]
@k8s-bot ok to test

**Comment by mbforbes** [comment]
(unsure who has context--@zmerlynn please feel free to shuffle around)

**Comment by zmerlynn** [comment]
@lhuard1A - Ping? I don't have a lot of context here, either. It looks like valid bash.

**Comment by sdminonne** [comment]
@zmerlynn  Spoken with @lhuard1A and he's going to submit a reacher PR with a better fix. Many apologizes for the noise.
Closing this.

**Pull request closed without merging**
