### PR TITLE
fix shellcheck in hack/...

### PR DESCRIPTION
**Pull request by xichengliudui**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
fix shellcheck in hack/...

**Which issue(s) this PR fixes**:

Ref #74228

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xichengliudui** [comment]
/assign @BenTheElder  @spiffxp
The original https://github.com/kubernetes/kubernetes/pull/74205 was very confusing due to the conflict, so I had to close and resubmit a pr

**Comment by mrbobbytables** [comment]
@xichengliudui
Are you still planning on tackling the others you referenced in PR #74205 and your [comment on the main thread](https://github.com/kubernetes/kubernetes/issues/72956#issuecomment-464680958)? If not, would you mind updating it so others can work on them?

Thanks!

**Pull request merged**
