### PR TITLE
Structured Logging migration: modify kube-proxy

### PR DESCRIPTION
**Pull request by lojies**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Structured Logging migration: modify part logs of kube-proxy.
xref:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
part of kubernetes/enhancements#1602
As it is related to log, change the log here to structured log.
#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yangjunmyfm192085** [comment]
https://github.com/kubernetes/kubernetes/pull/100518

**Comment by lojies** [comment]
@bowei @m1093782566

**Comment by pacoxu** [comment]
Since #98913 get a LGTM and this PR is dup with it.
I suggest to close this one.

**Pull request closed without merging**
