### PR TITLE
AWS Debian Jessie Support

### PR DESCRIPTION
**Pull request by justinsb**
Fixes the bootstrap script & Salt scripts to add support for Debian Jessie:
- Don't try to install the linux-image-extra package, not available on Debian, and only needed as a workaround for an Ubuntu problem with aufs
- Add a block to the Salt script for installation of Docker, to recognize Debian Jessie and install the correct package (they are packaged per-distro)

### CODE REVIEW

**Comment by justinsb** [comment]
These are the common pieces of Debian support, whether we choose to make Wily or Debian the default, and whether we choose to do an AMI or not.

**Comment by brendandburns** [comment]
@justinsb is this a dup?  There are similar salt changes elsewhere...

**Comment by justinsb** [comment]
I don't think it's a dup (?).  Nothing merged anyway; we do have similar changes for other distros because the Docker install is per-distro.  But it is perfectly possible this overlaps with someone else's PR or even one of my own - is there one in particular you're thinking of?

**Comment by justinsb** [comment]
@k8s-bot unit test this github flake #21188

**Comment by brendandburns** [comment]
LGTM, but needs rebase.

**Comment by justinsb** [comment]
@k8s-bot test this github flake #21491

**Comment by justinsb** [comment]
@brendandburns apparently we're moving to Docker 1.9.1 for 1.2, so I have to bump each of the Docker versions.  This one needed a rebase anyway, so I did it first...

**Comment by justinsb** [comment]
@brendandburns can we get this merged?  If we go back to docker 1.8 then I'll just rewind them all

**Comment by brendandburns** [comment]
@a-robinson build cop for the day...

**Comment by a-robinson** [comment]
submit-queue is struggling today, merging manually

**Pull request merged**
