### PR TITLE
Remove duplicate code

### LINKED ISSUE #22470: Kubelet: Cleanup node status related unit test in kubelet_test
There is quite a number of duplicated code in different node status related test functions, such as mock cadvisor intialization, expected node status etc.

It should be cleaned up. :)

### PR DESCRIPTION
**Pull request by tcharding**
This PR cleans up Kubelet test code. Adds a function enabling the removal of duplicate code for Mock chaining. Also adds a function to check the pod status, again enabling removal of duplicate code.

Fixes #22470

**Special notes for your reviewer**:

This is my first PR for the Kubernetes project. Keeping it simple.

### CODE REVIEW

**Comment by resouer** [comment]
Change lgtm from first glance, let's see CI result.

**Comment by derekwaynecarr** [comment]
thank you for you contribution.

/lgtm
/approve

**Pull request merged**
