### PR TITLE
Automated cherry pick of #11694 #14984 #15152 #15445 #15875 #16473 #16979

### PR DESCRIPTION
**Pull request by j3ffml**
Cherry pick of #11694 #14984 #15152 #15445 #15875 #16473 #16979 on release-1.1.

### CODE REVIEW

**Comment by jlowdermilk** [comment]
This absurdly long chain of cherrypicks is primarily to pick up #16979. All the others were pulled in to auto-resolve as many conflicts as possible (and because they should have been in the 1.1 branch to begin with).

**Comment by lavalamp** [comment]
Why is #16979 important to cherrypick? Is that the right number?

**Comment by jlowdermilk** [comment]
#16979 Is somewhat poorly titled. It fixes the GCE L7 LoadBalancer e2e test which has broken logic on the 1.1 branch causing spurious failures. The other cherrypicks are also either e2e tests or e2e test improvements.

**Comment by lavalamp** [comment]
I'm not 100% sure it's OK to pick the @ncdc commits you have by themselves, there may have been more to that change. @ncdc, what do you think?

**Comment by alex-mohr** [comment]
@brendandburns would be nice to get this set of CPs for 1.1.2.

**Comment by ncdc** [comment]
@lavalamp is this a regular pick of all the commits from 11694 (plus the follow-on 15875)? If so, I would think they can go in... what thoughts did you have in mind for what might be incomplete?

cc @ashcrow

**Comment by jlowdermilk** [comment]
@ncdc yep, this includes regular pick of all commits from #11694 and #15875

**Comment by lavalamp** [comment]
OK, LGTM.

**Pull request merged**
