### PR TITLE
Use pod logs subresource from e2e

### PR DESCRIPTION
**Pull request by smarterclayton**
Means that e2e code doesn't need to access the proxy

@liggitt bypasses the problem I was seeing with admin cert privs

### CODE REVIEW

**Comment by liggitt** [comment]
I like using the pods/log subresource, and would allow a lower level of access to run the test, but wouldn't resolve any master<->node communication issues

**Comment by smarterclayton** [comment]
I still think this is a permission issue with the kubelet trying to
authorize the user's access request from the proxy for a client cert.

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
Jenkins cluster didn't started

@k8s-bot test this please

**Pull request merged**
