### PR TITLE
Add test case for namespace

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
Unit test case need add that when name is "".

**Special notes for your reviewer**:
refer to https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/namespace.go#L74

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gyliu513** [comment]
@k8s-bot ok to test

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-unit test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by fabianofranz** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by fabianofranz** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
