### PR TITLE
Don't downgrade etcd version when downgrade cluster to 1.8.

### LINKED ISSUE #57013: gce-1.9-1.8-downgrade fails due to etcd crashloopbacking
/kind bug
/priority failing-test
/sig cluster-lifecycle testing

This test fails:
https://k8s-testgrid.appspot.com/sig-release-1.9-all#gce-1.9-1.8-downgrade

Some clues:

- waiting for new master timeout:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-beta-stable1-downgrade-cluster/33/build-log.txt
```
== Waiting for new master to respond to API requests ==
W1204 16:55:41.879] 2017/12/04 16:54:57 util.go:196: Interrupt after 15h0m0s timeout during kubetest --test --test_args=--ginkgo.focus=\[Feature:ClusterDowngrade\] --upgrade-target=ci/k8s-stable1 --upgrade-image=gci --report-dir=/workspace/_artifacts --disable-log-dump=true --report-prefix=upgrade --v=true --check-version-skew=false. Will terminate in another 15m
```

- master healthz check failed:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-beta-stable1-downgrade-cluster/33/artifacts/bootstrap-e2e-master/kube-apiserver.log
```
logging error output: "[+]ping ok
[-]etcd failed: reason withheld
[+]poststarthook/generic-apiserver-start-informers ok
[+]poststarthook/start-apiextensions-informers ok
[+]poststarthook/start-apiextensions-controllers ok
[-]poststarthook/bootstrap-controller failed: reason withheld
[-]poststarthook/rbac/bootstrap-roles failed: reason withheld
[-]poststarthook/ca-registration failed: reason withheld
[+]poststarthook/start-kube-apiserver-informers ok
[+]poststarthook/start-kube-aggregator-informers ok
[+]poststarthook/apiservice-registration-controller ok
[+]poststarthook/apiservice-status-available-controller ok
[+]poststarthook/apiservice-openapi-controller ok
[+]poststarthook/kube-apiserver-autoregistration ok
[-]autoregister-completion failed: reason withheld
healthz check failed
"
 [[curl/7.38.0] 35.184.43.102:54282]
```

- etcd is crashloopbacking:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-beta-stable1-downgrade-cluster/33/artifacts/bootstrap-e2e-master/etcd.log
```
2017-12-04 02:24:01.495921 I | etcdserver: starting server... [version: 3.0.17, cluster version: to_be_decided]
2017-12-04 02:24:01.506968 I | membership: added member a97d80ddc090126a [https://bootstrap-e2e-master:2380] to cluster 91078bdbe2ed539b
2017-12-04 02:24:01.507103 N | membership: set the initial cluster version to 3.1
2017-12-04 02:24:01.507116 C | membership: cluster cannot be downgraded (current version: 3.0.17 is lower than determined cluster version: 3.1).
```

I guess the cause may be something associated with etcd version compatibility. @xiang90 @hongchaodeng any thoughts or suggestions? Thanks!

This is also posted in https://groups.google.com/forum/#!topic/kubernetes-sig-cluster-lifecycle/c4MW3R5v4v0

/cc @enisoc @luxas @krzyzacy  @kubernetes/sig-cluster-lifecycle-test-failures @kubernetes/sig-release-test-failures

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
As the title says. This is a workaround for now.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #57013 
xref: https://github.com/kubernetes/test-infra/pull/5909

**Special notes for your reviewer**:
/cc @jpbetz @wojtek-t @krousey @krzyzacy @enisoc @luxas @spiffxp @jberkus 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
> For the immediate term, I proposed kubernetes/test-infra#5909 earlier today to unblock testing. This will just deploy the initial 1.9 cluster with the older version of etcd.

@krousey - that sounds bad to me. It seems to me as making tests passed, but not in the environment that we will have in production. In production we will have clusters with etcd in 3.1.10 version. So setting up a cluster with a different etcd seems like a bad choice to me.

**Comment by enisoc** [comment]
@wojtek-t I approved https://github.com/kubernetes/test-infra/pull/5909 for now because we currently have no downgrade signal at all, so something is better than nothing. Once we have a better solution we can remove the temporary change.

**Comment by wojtek-t** [comment]
@enisoc - I think *this* is a better solution.

**Comment by enisoc** [comment]
@wojtek-t Is that an LGTY? :)

**Comment by wojtek-t** [comment]
It's not perfect, but I'm fine with that to get any signal from downgrade testing. We can clean this up later.

/approve no-issue

**Comment by krousey** [comment]
I think we need to move away from coupling etcd versions to k8s versions completely. The 2 components should be both upgraded and downgraded separately. This change is introduction a lot of noise into the upgrade framework for a cluster/gce/upgrade.sh problem, and it will be harder to clean up than simply just pinning the etcd version during the gce downgrade tests.

**Comment by wojtek-t** [comment]
> I think we need to move away from coupling etcd versions to k8s versions completely. The 2 components should be both upgraded and downgraded separately.

I agree. And that's what we already did for GKE btw.
However, we are still coupling those two in OSS. And as long as we won't split it, to have a real upgrade/downgrade testing we need to test whatever the releases and not something that we thing should be done. We should first decouple and then change upgrade/downgrade tests, not the other way around.

**Comment by krousey** [comment]
@wojtek-t I think we're agreeing on the main issue. I'm just pointing out that for now to get signal, we're pinning the version. We should not pin it in the e2e upgrade framework. We should just pin it in the test job config.

But I think we agree that we need to change upgrade.sh to be better about etcd.

**Comment by spiffxp** [comment]
Agree with @krousey this really doesn't seem like the right place to have this logic, do our job configs not support this level of pinning or something? I don't understand how https://github.com/kubernetes/test-infra/pull/5909 isn't sufficient to solve this?

**Comment by enisoc** [comment]
This PR is basically simulating the instructions we intend to give users for how to downgrade from 1.9 to 1.8. I think that's appropriate for an e2e test.

**Comment by krousey** [comment]
@enisoc I would think the instructions would be

1) find out what version of etcd you're running
1) pin that and only upgrade the control plane (eg. `ETCD_VERSION=3.0.10 ./cluster/gce/upgrade.sh -M v1.9.0`)
1) roll back if there are problems with `./cluster/gce/upgrade.sh -M v1.8.6`
1) upgrade etcd (take a snapshot because that's the only way to roll back)

This change is assuming etcd was upgraded first and you're already beyond the point of return. It also uses test-only env vars to accomplish this.

**Comment by xiangpengzhao** [comment]
/hold
as per #57121 and @krousey opinion.
Also, let's see if the next test can pass since https://github.com/kubernetes/test-infra/pull/5909 has already been merged.

**Comment by xiangpengzhao** [comment]
If that workaround doesn't work, we can push this forward. I think @enisoc 's verification flow in https://github.com/kubernetes/kubernetes/issues/57013#issuecomment-351244989 is the same with this PR does.

```
Before upgrading, my 1.8 cluster had etcd 3.0.17.
After upgrading, my 1.9 cluster had etcd 3.1.10.
After downgrading, my 1.8 cluster had etcd 3.1.10 still.
```

**Comment by xiangpengzhao** [comment]
/close
for now in favor of https://github.com/kubernetes/test-infra/pull/5920 since it makes the test pass. https://github.com/kubernetes/kubernetes/issues/56879#issuecomment-351280463.

Final solution may be #57121.

Reopen if we think we still need this fix.

**Pull request closed without merging**
