### PR TITLE
automatically tag tests in test/integration/* as integration

### LINKED ISSUE #78527: hack/update-bazel doesn't add integration tags
**What happened**:
when running `hack/update-bazel.sh` integration tags were missing on `BUILD` files

**What you expected to happen**:
add the needed tags on test/integration `BUILD` files

**How to reproduce it (as minimally and precisely as possible)**:

add an integration test package under `test/integration`

cc @liggitt

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: ensures all tests in `test/integration/*` are automatically marked as integration tests in bazel.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/78527

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/sig testing
/priority backlog

### CODE REVIEW

**Review by fejta — APPROVED** [review]
/lgtm
/approve

**Review by yastij — COMMENTED** [review]
/lgtm

**Pull request merged**
