### PR TITLE
Update github.com/evanphx/json-patch to e83c0a1c26c884f8ec4fb743f6db9…

### LINKED ISSUE #91615: JSON patch with kubectl has exponential time complexity for nesting depth of manifest
**What happened**:

When updating a deeply nested CRD in a local k8s cluster with `kubectl apply`,
the command finishes after more than 5 minutes.
The CRD has a field like [`corev1.PodSpec`](https://godoc.org/k8s.io/api/core/v1#PodSpec).

I did a brief experiment for how the nesting depth of manifests affects computation time,
and found that JSON patch creation with `kubectl apply` has exponential time complexity for the depth.

**What you expected to happen**:

Finish updating deeply nested CRDs with `kubectl apply` in some seconds, at most 5s.

**How to reproduce it (as minimally and precisely as possible)**:

Please execute `kubectl apply -f https://gist.githubusercontent.com/tapih/f339a2d558cf49b0cd6320b7b2f1821b/raw/2fa11c4935f1976059c6517caef647115e1dcbda/crd.yaml` twice.
The second one will take too long to finish.

This is the detail of my experiment.

1. Create a `Foo` CRD project of which API version is `apiextensions.k8s.io/v1` with [kubebuilder](https://book.kubebuilder.io/quick-start.html).
2. Change the type definition of the CRD to have deeply nested slices.

```go
type FooSpec struct {
	// +optional
	T1 []T1 `json:"t1,omitempty"`
}

type T9 struct {
	// +optional
	T8 []T8 `json:"t8,omitempty"`
}

type T8 struct {
	// +optional
	T7 []T7 `json:"t7,omitempty"`
}

type T7 struct {
	// +optional
	T6 []T6 `json:"t6,omitempty"`
}

:

type T1 struct {
	// +optional
	Field string `json:"field"`
}
```

3. Run `make manifests` and create the CRD manifest.
4. Create a CRD object with `kubectl apply -f ./config/crd/bases/your.domain.name_foo.yaml`.
5. Update the CRD object with `kubectl apply -f ./config/crd/bases/your.domain.name_foo.yaml`.
6. Repeat this with incrementing the nesting depth of `FooSpec` like T1, T2, T3...T8.

The wall-clock time to finish the second `kubectl apply -f ./config/crd/bases/your.domain.name_foo.yaml` was as follow:

```
...
T4 => 0.1s
T5 => 1.2s
T6 => 8.7s
T7 => 68s
T8 => 544s
```

**Anything else we need to know?**:

https://github.com/evanphx/json-patch/pull/87 has already resolved this issue.
However, [kubernetes/kubernetes/go.mod](https://github.com/kubernetes/kubernetes/blob/413bc1a1d238efb7c4ba9e3aac2c381c93295aec/go.mod#L239) at master `HEAD` does not take this fix.

https://github.com/kubernetes/kubectl/issues/698 is about the same problem.
However, it was closed without fixing this problem.

**Environment**:
- Kubernetes version:  
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-02-07T01:05:17Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Hardware: VM on Hyper-V
- OS: Ubuntu 18.04
- Kernel: 4.15.0-66-generic
- Install tools: kind v0.8.1

### PR DESCRIPTION
**Pull request by tapih**
Signed-off-by: Hiroshi Muraoka <h.muraoka714@gmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR fixes a bug that JSON patch with `kubectl apply` has exponential time complexity for the nesting depth of manifest.

**Which issue(s) this PR fixes**:
Fixes #91615 .

**Special notes for your reviewer**:
The existing PR https://github.com/kubernetes/kubernetes/pull/91622 breaks the compatibility to conform to RFC6902 in [this patch](https://github.com/evanphx/json-patch/pull/85).
This PR takes an intermediate commit to avoid the compatibility break and fixes just #91615.

**Does this PR introduce a user-facing change?**:
```release-note
Fixed a performance issue applying json patches to deeply nested objects
```

### CODE REVIEW

**Comment by tapih** [comment]
@liggitt Could you review this PR ??

**Comment by fedebongio** [comment]
Thank you Jordan for looking into it

**Comment by vincepri** [comment]
@liggitt Was just wondering, is this going to be backported as well? Planning to cut `controller-runtime` releases that depend on 1.17 and 1.18; given that we're heavily dependent on json-patch to calculate merge patches, I've opened a PR to match these changes.

**Comment by liggitt** [comment]
This seems eligible to backport to me. @logicalhan or @tapih, can you open backports of this to 1.16-1.18 release branches for testing?

**Comment by vincepri** [comment]
Thanks!

**Pull request merged**
