### PR TITLE
e2e_node: does not rely on Kubelet automatic restart service under hugepages tests

### PR DESCRIPTION
**Pull request by cynepco3hahue**
#### What type of PR is this?

/kind failing-test
/kind bug

#### What this PR does / why we need it:

We should not rely on the kubelet service automatic restart anymore because it is disabled by default.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@SergeyKanzhelev And additional follow-up fix :(

**Review by SergeyKanzhelev — APPROVED** [review]

**Pull request merged**
