### PR TITLE
Fix 404 link in kube-scheduler command usage description

### PR DESCRIPTION
**Pull request by xinydev**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

fix 404 link in kube-scheduler command usage description

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

NONE

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by Hsiny** [comment]
CLA signed

**Comment by alculquicondor** [comment]
sigh...

/approve
/lgtm

**Pull request merged**
