### PR TITLE
Revert "Graduate API Server tracing to beta"

### LINKED ISSUE #113791: apiserver tracing: port forwarding broke
### What happened?

This is a regression caused by https://github.com/kubernetes/kubernetes/pull/113693. It worked with master a14601a77fa (last merge commit before that PR) and is broken in b2c72feca83.

Disabling the APIServerTracing feature gate works avoids the problem.

The problem is that port forwarding in https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/drivers/proxy/portproxy.go fails when used against a kind cluster built from Kubernetes master. https://github.com/kubernetes/kubernetes/pull/111023 depends on that for testing in pull-kubernetes-kind-dra.

The symptom is:
```
E1109 14:48:20.616608   67398 portproxy.go:134] port forwarding for dra-4197/dra-test-driver-57hbd:9001: no connection: error creating error stream: Timeout occurred
```

### What did you expect to happen?

Should work as before...

### How can we reproduce it (as minimally and precisely as possible)?

* merge https://github.com/kubernetes/kubernetes/pull/111023 with master
* test/e2e/dra/kind-build-image.sh csiprow/node:latest
* kind create cluster --config test/e2e/dra/kind.yaml --image csiprow/node:latest
* KUBECONFIG=$HOME/.kube/config _output/bin/ginkgo -v -focus="DynamicResourceAllocation.*multiple drivers work" ./test/e2e

### Anything else we need to know?

CSI mock tests should use the same port forwarding, but don't seem to be affected.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by dashpole**
Reverts kubernetes/kubernetes#113693

Fixes https://github.com/kubernetes/kubernetes/issues/113791

See https://github.com/kubernetes/kubernetes/issues/113791#issuecomment-1309391196.  There appears to be an issue with how the request body is wrapped in the otelhttp library.  This is unlikely to be fixed, released, and vendored during code freeze.

I removed the release notes from the reverted PR as well.
```release-note
NONE
```

/assign @liggitt 

cc @kubernetes/sig-instrumentation-leads

### CODE REVIEW

**Comment by liggitt** [comment]
Sad, but thanks for the quick investigation and resolution. If there's been no release cut since the beta promotion we can empty the release notes in both PRs to avoid confusion in the generated notes

**Comment by dashpole** [comment]
> If there's been no release cut since the beta promotion we can empty the release notes in both PRs to avoid confusion in the generated notes

Removed the release notes from both PRs.

**Comment by liggitt** [comment]
@jkh52 hmm, saw "error dialing backend: dial timeout, backstop failed" errors in the test run at https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/113803/pull-kubernetes-e2e-gce-ubuntu-containerd/1590565648713388032/

not sure if that's noise from an unrelated issue, related to the uds dial timeout added, or something else

**Comment by liggitt** [comment]
yeah, looks like that error jumped up in frequency after the timeout merge - https://github.com/kubernetes/kubernetes/pull/113486#issuecomment-1310322562

**Pull request merged**
