### PR TITLE
Revert "Revert "Revert "Kubelet: Add rkt as a runtime option"""

### PR DESCRIPTION
**Pull request by zmerlynn**
Comically re-revert #7743

Because @zmerlynn is an idiot and can't read his own build results.

Reverts GoogleCloudPlatform/kubernetes#7811

### CODE REVIEW

**Comment by zmerlynn** [comment]
If you want to see what success is, run

```
make release
$ ldd -v _output/release-stage/server/linux-amd64/kubernetes/server/bin/kubelet | grep GLIBC_2.14
                libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
```

If you see those GLIBC_2.14 tags, that's bad. :)

**Comment by vmarmol** [comment]
LGTM

**Comment by vmarmol** [comment]
Ah yes, we do have that issue...

**Comment by dchen1107** [comment]
Yes, I totally ran into this issue when I hacked the demo for rkt and k8s. The way for me to fix the issue is I linked kubelet statically. Our debian image has old libc, but rkt requires a newer version.

**Comment by dchen1107** [comment]
Of course we fix is just a workaround.

**Comment by zmerlynn** [comment]
I left the issue open as #7803.

**Comment by liggitt** [comment]
The title of this reads like http://en.wikipedia.org/wiki/Buffalo_buffalo_Buffalo_buffalo_buffalo_buffalo_Buffalo_buffalo

**Comment by zmerlynn** [comment]
I felt a little comical here. Apologies for the in and out. :)

**Pull request merged**
