### PR TITLE
delete the useless "gv" in Errorf

### PR DESCRIPTION
**Pull request by yu8833**
Signed-off-by: yupengzte <yu.peng36@zte.com.cn>

**What this PR does / why we need it**:
Fix "no formatting directive in Errorf call"
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by YuPengZTE** [comment]
@k8s-bot ok to test

**Comment by caesarxuchao** [comment]
@k8s-bot ok to test

**Comment by caesarxuchao** [comment]
Thanks, @YuPengZTE

**Comment by wojtek-t** [comment]
@k8s-bot kops aws e2e test this

**Comment by caesarxuchao** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by wojtek-t** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by caesarxuchao** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by wojtek-t** [comment]
@k8s-bot pull-kubernetes-kubemark-e2e-gce test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Pull request merged**
