### PR TITLE
Fixed typo in hack/serve-prom-scrapes.sh

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This PR fixes a typo in a comment in a helper script.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@sig testing

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
