### PR TITLE
WIP (DON'T REVIEW): For test only

### PR DESCRIPTION
**Pull request by chendave**
/cc @chendave 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
@dims the status of `pull-kubernetes-node-arm64-e2e-containerd-serial-ec2` is not correct, it shouldn't be succeed with such a lot of failure. https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/118650/pull-kubernetes-node-arm64-e2e-containerd-serial-ec2/1671855587857534976

**Comment by dims** [comment]
yep, still iterating on getting that fixed.

**Pull request closed without merging**
