### PR TITLE
kubeadm: Use the v1.7 branch by default

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:

Makes kubeadm use the v1.7 branch instead of v1.6

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
This should be merged right before the rc.0 is cut I guess

**Release note**:

```release-note
NONE
```
@kubernetes/sig-cluster-lifecycle-pr-reviews

### CODE REVIEW

**Comment by pipejakob** [comment]
/lgtm
/kind bug

In addition to this PR (which is waiting on rc.0), maybe we should just change the default to `latest-1.7` now?

**Comment by pipejakob** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by pipejakob** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Review by timothysc — APPROVED** [review]
/lgtm

**Comment by caesarxuchao** [comment]
It will take some time to fast-forward the release branch and then waiting for the tests run before we can make release-candidate. Because the next tag we make will be release-rc, can we merge it now?

**Comment by luxas** [comment]
Merging today and cutting rc.0 tomorrow sounds good to me. I'll remove the do-not-merge label later today.

In this short period of time in between the merge and the cut it's expected that `kubeadm init` with no args will fail because it's trying to use a version that doesn't exist yet.

@caesarxuchao Can you confirm that `stable-1.7.txt` will point to `rc.0` after the cut?

**Comment by caesarxuchao** [comment]
What is `stable-1.7.txt`? 

Can we merge it this afternoon? Serial tests take long time to run, and i want to have some tests results by tmr morning.

**Comment by luxas** [comment]
@caesarxuchao Feel free to merge any minute?

> What is stable-1.7.txt?

So I was referring to this:
```
$ curl -sSL dl.k8s.io/release/stable.txt
v1.6.6
$ curl -sSL dl.k8s.io/release/latest.txt
v1.8.0-alpha.1
$ curl -sSL dl.k8s.io/release/stable-1.6.txt
v1.6.6
$ curl -sSL dl.k8s.io/release/latest-1.6.txt
v1.6.7-beta.0
$ curl -sSL dl.k8s.io/release/stable-1.7.txt
404
$ curl -sSL dl.k8s.io/release/latest-1.7.txt
v1.7.0-beta.2
```

As you see, there is no `stable-1.7`. But @dchen1107 said that the `stable-1.7` will be created on the `rc.0` cut and point to that. Then, on the `v1.7.0` cut, both `stable-1.7` and `stable` will point to that version.

@caesarxuchao OK? This PR makes kubeadm v1.7 default to deploying `stable-1.7` clusters.

**Pull request merged**
