### PR TITLE
AWS: Find the correct security group by looking at tags

### LINKED ISSUE #21986: AWS: Should not make arbitrary choice between instance security groups
If there are two security groups on an instance, we currently make an arbitrary choice.  We should choose based on tags, as we normally do.

For back-compat, we need to cope if there is one security group and it is not tagged.

We should make sure kube-up tags our security groups, though it isn't really required for kube-up, but it is just good behaviour.

cf #20790

### PR DESCRIPTION
**Pull request by justinsb**
Like everything else AWS, we differentiate between k8s-owned security
groups and k8s-not-owned security groups using tags.

When we are setting up the ingress rule for ELBs, pick the security
group that is tagged over any others.

We continue to tolerate a single security group being untagged, but
having multiple security groups without tagging is now an error, as it
leads to undefined behaviour.

We also log at startup if the cluster tag is not defined.

Fix #21986

### CODE REVIEW

**Comment by justinsb** [comment]
cc @therc

**Comment by therc** [comment]
I'll test it as soon as it lands. Thanks!

**Comment by justinsb** [comment]
Removed WIP; working in my testing

**Comment by brendandburns** [comment]
LGTM.

**Pull request merged**
