### PR TITLE
Print ephemeral containers in kubectl describe

### PR DESCRIPTION
**Pull request by verb**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**: Ephemeral containers were added (in alpha) to the core API in #59416. This updates `kubectl describe` to print ephemeral containers if they exist.

**Which issue(s) this PR fixes**:
WIP #27140

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

Release notes are included in #59484
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
- [KEP]: https://git.k8s.io/enhancements/keps/sig-node/20190212-ephemeral-containers.md
```

### CODE REVIEW

**Review by dixudx — APPROVED** [review]
/lgtm

**Comment by verb** [comment]
@mengqiy There's no rush, but will you have time to review this in time for 1.16 or should I look for additional reviewers?

/retest

**Comment by ttousai** [comment]
Hello! I'm a bug triage shadow for the 1.16 release cycle and considering this issue is tagged for 1.16, I'd like to check its status. Code freeze is starting on August 29th (about 3 days from now), which means that this PR must merged by then.

Do we still target this issue to be fixed for 1.16?

**Comment by verb** [comment]
@ttousai yes, this should be included in 1.16 (cc @seans3)

**Pull request merged**
