### PR TITLE
docs/local_docker: fix documentation  and bootstrap

### LINKED ISSUE #2378: Error building kubernetes docker images
While following the documentation to build the kubernetes docker image:  https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/local_docker.md

An error is encountered when executing: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/build/make-run-images.sh

```
exec: "build/build-image/make-binaries.sh": stat build/build-image/make-binaries.sh: no such file or directory2014/11/14 12:01:41 Error response from daemon: Cannot start container 28112fb62d1135832380e518f86a0ddf1b929cce68d5ceedac0d6495f5dd0836: exec: "build/build-image/make-binaries.sh": stat build/build-image/make-binaries.sh: no such file or directory
!!! Error in ./build/../build/common.sh:385
  '"${docker_cmd[@]}" "$@"' exited with status 1
Call stack:
  1: ./build/../build/common.sh:385 kube::build::run_build_command(...)
  2: ./build/make-run-images.sh:32 main(...)
Exiting with status 1
```

Unsure if the documentation is out of date or if there is a valid bug here.

### PR DESCRIPTION
**Pull request by proppy**
Starting a PR to fix #2378

### CODE REVIEW

**Comment by pires** [comment]
Can someone validate and merge this, please?

**Comment by jbeda** [comment]
Hi @pires -- running kubernetes inside of docker isn't something we are testing and supporting right now.  While most components will run just fine, the kubelet itself does some host side management that isn't appropriate to run in a container all of the time.

Specifically, we'll adjust install IPtables for service redirection (which might work with --net=host) and we'll create/mount/format/manage volumes.  The volumes thing is really a sticking point.

Eventually I'd love to support testing running the bulk of kubernetes in docker containers (on kubernetes, of course) it isn't a super high priority right now.  As such, this stuff is likely to break often.

With that in mind, I'm going to remove the run-image stuff from `build/*` and let @proppy move some of this stuff to `contrib` if he likes.

Most of my effort is going to be going in to https://github.com/GoogleCloudPlatform/kubernetes/issues/2303 right now.

**Comment by jbeda** [comment]
Also see #19 for eventually completing this work.

**Comment by pires** [comment]
Thanks @jbeda for clarifying. For me, as Mac-user, it's been really a major PITA to get k8s cluster up&running. For now, I've been using GCE but it comes at a cost :-(

Will follow #2303.

**Comment by proppy** [comment]
@pires, it would be nice to have static VMs image (build with packer?) with a preconfigured cluster, should we start a new issue about that.

**Comment by pires** [comment]
That would be great. How can I help @proppy?

**Comment by proppy** [comment]
@pires let's discuss that on a new issue. (care to file it?).

**Comment by pires** [comment]
@proppy sure thing #3244

**Comment by jbeda** [comment]
Closing this as we are putting "kubernetes in docker" on the back burner.  When we pick it up we'll track it in #19.

**Pull request closed without merging**
