### PR TITLE
Add support to disable /debug/pprof and /debug/flags/v endpoint

### LINKED ISSUE #84165: Add --profiling flag to kubelet
**What would you like to be added**:

The control plane components have a `--profiling` flag that controls `/debug/pprof/*` and `/debug/flags/v` being enabled or disabled. Kubelet has both these endpoints, but it doesn't allow them to be independently disabled from all other debugging endpoints that support `kubectl {exec,logs,portforward}`.

**Why is this needed**:

Administrators who don't want to solely rely on RBAC roles for debug endpoints should be able to disable remote profiling and log level setting. 

See Also:
#64601
#63777

/sig node
/kind feature
/area kubelet

### PR DESCRIPTION
**Pull request by SaranBalaji90**
Co-authored-by: xiaofei.sun <sunxiaofei@kuaishou.com>
Co-authored-by: SaranBalaji90 <srisaranbalaji@gmail.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR adds `"EnableProfilingHandler"` and `"EnableDebugFlagsHandler"` flag to kubelet configuration similar to `"EnableSystemLogHandler"`. Based on the value of `EnableProfilingHandler`, `/debug/pprof` endpoint will be made available in kubelet and similarly based on `"EnableDebugFlagsHandler"`, `/debug/flags` will be enabled . Default value for these flag is true.

**Special notes for your reviewer**:
This change is similar to https://github.com/kubernetes/kubernetes/pull/87273

Special credit to xiaoanyunfei@ for the initial commit.

**Which issue(s) this PR fixes**:
Fixes #84165

**Does this PR introduce a user-facing change?**:
```release-note
Cluster admins can now turn off /debug/pprof and /debug/flags/v endpoint in kubelet by setting enableProfilingHandler and enableDebugFlagsHandler to false in their kubelet configuration file. enableProfilingHandler and enableDebugFlagsHandler can be set to true only when enableDebuggingHandlers is also set to true.
```

/sig node

**Testing result:**

Updated `/etc/kubernetes/kubelet/kubelet-config.json` with the following values

```
  "enableDebuggingHandlers": true,
  "enableSystemLogHandler": false,
  "enableDebugFlagsHandler": false,
  "enableProfilingHandler": false,
```
```
[ec2-user@ip-192-168-30-66 ~]$ curl -k https://localhost:10250/debug/pprof/symbol
profiling endpoint is disabled.
[ec2-user@ip-192-168-30-66 ~]$ curl -k https://localhost:10250/logs/
logs endpoint is disabled.
[ec2-user@ip-192-168-30-66 ~]$ curl -X PUT -k https://localhost:10250/debug/flags/v -d "2"
flags endpoint is disabled
```
After updating the values to `true` again
```
[ec2-user@ip-192-168-30-66 ~]$ curl -k https://localhost:10250/debug/pprof/symbol
num_symbols: 1
[ec2-user@ip-192-168-30-66 ~]$ curl -k https://localhost:10250/logs/
<pre>
<a href="alternatives.log">alternatives.log</a>
<a href="audit/">audit/</a>
```

/sig node
/area kubelet
/assign @derekwaynecarr
/assign @dchen1107

### CODE REVIEW

**Comment by SaranBalaji90** [comment]
Second commit is mostly to improve readability and make future enhancements easier - https://github.com/kubernetes/kubernetes/pull/98458/commits/a88066876bdd65b4f9a7443782e5a9e190ae23d9

**Comment by dims** [comment]
@SaranBalaji90 looks great. one question though, we are not adding any command line flags here by design. right? ( i am ok with this being available just from the config file, but just asking )
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go#L470

**Comment by ehashman** [comment]
> looks great. one question though, we are not adding any command line flags here by design. right? ( i am ok with this being available just from the config file, but just asking )
> https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go#L470

@dims my understanding from the issue is that we do want the flags? https://github.com/kubernetes/kubernetes/issues/84165#issuecomment-771201052

/assign @derekwaynecarr

**Comment by SaranBalaji90** [comment]
> @SaranBalaji90 looks great. one question though, we are not adding any command line flags here by design. right? ( i am ok with this being available just from the config file, but just asking )
> https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go#L470

@dims thank you for taking time. You're right we are not adding any command line argument in this PR. This was suggested on one of my previous pull request - https://github.com/kubernetes/kubernetes/pull/87273

**Comment by SaranBalaji90** [comment]
> > looks great. one question though, we are not adding any command line flags here by design. right? ( i am ok with this being available just from the config file, but just asking )
> > https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go#L470
> 
> @dims my understanding from the issue is that we do want the flags? [#84165 (comment)](https://github.com/kubernetes/kubernetes/issues/84165#issuecomment-771201052)
> 
> /assign @derekwaynecarr

I guess @derekwaynecarr meant separate knob(flag) in config file but not necessarily command-line argument flag. But I can get it clarified with him :)

**Comment by dims** [comment]
@SaranBalaji90 either way this can ship, we just need to line up `/approve` :) we can always add it later

/unassign (as i don't have approval rights)
/assign @mrunalp @sjenning

**Comment by lavalamp** [comment]
Release note claims:

> Cluster admins can now turn off /debug/pprof and /debug/flags/v endpoint in kubelet by setting enableProfilingHandler and enableDebugFlagsHandler to false in their kubelet configuration file. enableProfilingHandler and enableDebugFlagsHandler can be set to true only when enableDebuggingHandlers is also set to true.

However I don't see any code enforcing that. Maybe the implementation happens to work this way but it's not easy at all to verify. Apart from this the api is fine. I think it's important that these things don't suddenly turn on for people who have them off currently.

**Comment by SaranBalaji90** [comment]
> Release note claims:
> 
> > Cluster admins can now turn off /debug/pprof and /debug/flags/v endpoint in kubelet by setting enableProfilingHandler and enableDebugFlagsHandler to false in their kubelet configuration file. enableProfilingHandler and enableDebugFlagsHandler can be set to true only when enableDebuggingHandlers is also set to true.
> 
> However I don't see any code enforcing that. Maybe the implementation happens to work this way but it's not easy at all to verify. Apart from this the api is fine. I think it's important that these things don't suddenly turn on for people who have them off currently.

Thank you for reviewing the PR @lavalamp :)

We are using `enableDebuggingHandlers` as the parent knob to turn on/off all the sub handlers like` /logs` or `/pprof` and other handlers. If at present if admin has `enableDebuggingHandlers` set to false then it wont turn on these handlers. Like you mentioned we decided this route earlier just to avoid turning on the feature accidentally and also to make it backward compatible.

we enforce that here - https://github.com/kubernetes/kubernetes/pull/98458/files#diff-c3e7f724d1b0dcee40df80716ed57d90d2649710150fa92bf9822bdad35e0429R239 `enableDebuggingHandlers` should be set to true to enable/disable other child handlers.

**Comment by lavalamp** [comment]
> we enforce that here

I guess I'm not sure why you install a "not turned on" handler if it is off? I think it would be easier to audit if the section of code you linked me to was just if statements.

I also don't really like that this is so inconsistent with how apiserver handles this, but I don't know that anything can be done about that.

Anyway, kubelet is not my binary so I don't really have a strong opinion, if you all are certain enough then that's fine.

For the API: 
/approve

**Comment by SaranBalaji90** [comment]
> I guess I'm not sure why you install a "not turned on" handler if it is off? I think it would be easier to audit if the section of code you linked me to was just if statements.

If its `off`, Kubelet just return messages like "logs(profiling) endpoint is disabled."

**Comment by SaranBalaji90** [comment]
> I also don't really like that this is so inconsistent with how apiserver handles this, but I don't know that anything can be done about that.

@lavalamp is it due to the fact that single --profiling cmd line argument takes care of turning off /debug/pprof and /debug/flags/v endpoints in ApiServer but we are turning off in Kubelet with two different flags?

**Comment by lavalamp** [comment]
>> I guess I'm not sure why you install a "not turned on" handler if it is off? I think it would be easier to audit if the section of code you linked me to was just if statements.

> If its off, Kubelet just return messages like "logs(profiling) endpoint is disabled."

Yes, I understood, I just am not sure why that's desirable.

**Comment by SaranBalaji90** [comment]
> > > I guess I'm not sure why you install a "not turned on" handler if it is off? I think it would be easier to audit if the section of code you linked me to was just if statements.
> 
> > If its off, Kubelet just return messages like "logs(profiling) endpoint is disabled."
> 
> Yes, I understood, I just am not sure why that's desirable.

Ah ok.. I can remove if we don't need to return anything.. I added with assumption that it provides better wording(UX) when disabled.

**Comment by ehashman** [comment]
From what I can see the latest update has changed quite a bit from the last... @sjenning can you PTAL?

**Comment by SaranBalaji90** [comment]
actually @ehashman I didn't make any change though https://github.com/kubernetes/kubernetes/commit/3944e1d1d132b414bfb4b491465c6a97bf65409e and https://github.com/kubernetes/kubernetes/commit/51c5401bd67785f661a5c26fe3c4194c72d71708 but for some reason robot reported - "New changes are detected"

**Comment by lavalamp** [comment]
> I added with assumption that it provides better wording(UX) when disabled.

It's up to the Kubelet owners. :)

**Comment by ehashman** [comment]
> actually @ehashman I didn't make any change though between [3944e1d](https://github.com/kubernetes/kubernetes/commit/3944e1d1d132b414bfb4b491465c6a97bf65409e) and [51c5401](https://github.com/kubernetes/kubernetes/commit/51c5401bd67785f661a5c26fe3c4194c72d71708) but for some reason robot reported - "New changes are detected"

When I tried to diff the branches the diff numbers didn't match... I didn't do the initial review but I am not the right person to LGTM this :)

**Comment by SaranBalaji90** [comment]
> > actually @ehashman I didn't make any change though between [3944e1d](https://github.com/kubernetes/kubernetes/commit/3944e1d1d132b414bfb4b491465c6a97bf65409e) and [51c5401](https://github.com/kubernetes/kubernetes/commit/51c5401bd67785f661a5c26fe3c4194c72d71708) but for some reason robot reported - "New changes are detected"
> 
> When I tried to diff the branches the diff numbers didn't match... I didn't do the initial review but I am not the right person to LGTM this :)

looks like there was some log format changes in master which was missed after rebase. Fixed it now :)

**Comment by derekwaynecarr** [comment]
/approve
/lgtm

@andrewsykim maybe you can help restructure this in a follow-on to make the code path clearer per @lavalamp comments as part of overall `/pkg/kubelet/server` cleanup?

**Pull request merged**
