### PR TITLE
Fix spelling typos: scheduable -> schedulable

### PR DESCRIPTION
**Pull request by justinsb**
Bulk fix of a common typo.

/kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve
/triage accepted

**Review by abdelrahman89 — APPROVED** [review]

**Comment by justinsb** [comment]
/assign @liggitt 

Do you mind OKing this one Jordan?  Noticed this when I couldn't find the function, in case you're wondering!

**Pull request merged**
