### PR TITLE
kubeadm: Cut unnecessary kubectl dependency

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:

Removes unnecessary dep

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
@kubernetes/sig-cli-pr-reviews

### CODE REVIEW

**Comment by luxas** [comment]
On an approval from someone in sig-cli, I'll rebase and get this merged.

**Comment by luxas** [comment]
Could a build/visible_to owner please approve this PR?
e.g. @ixdy @mikedanese @thockin or @jbeda 

This is really trivial in any case...
/retest

**Comment by monopole** [comment]
/approve

Nice, thanks!

**Pull request merged**
