### PR TITLE
Create pkg/kubelet/apis/deviceplugin/v1beta1 directory.

### PR DESCRIPTION
**Pull request by jiayingz**
The proto stays the same as v1alpha. Only changes Version in
constants.go to "v1beta1" and the BUILD file to pick up the new dir.

```release-note
Adding pkg/kubelet/apis/deviceplugin/v1beta1 API.
```

### CODE REVIEW

**Comment by jiayingz** [comment]
/assign @RenaudWasTaken @vishh @derekwaynecarr @ConnorDoyle 

I have added an agenda in next week's rmwg meeting to discuss creating deviceplugin/v1beta1 directory now, but as we have a couple of pending PRs that will make incompatible API changes, I would like to send out this PR now to get some early opinions. I think making incompatible api changes in the v1beta1 directory can avoid breaking existing device plugins and also makes it easy for a device plugin to support both v1alph api and v1beta1 api if it needs to.

Please let me know if you have any objections. Thanks a lot!

**Comment by vishh** [comment]
LGTM for the overall plan! I haven't looked closely at the individual fields yet. If there has been no changes since `v1alpha2`, then I can approve this PR.

**Comment by jiayingz** [comment]
@vishh thanks a lot for reviewing this! The actual v1beta1 API stays the same as v1alpha2 in this PR.

**Review by vishh — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
