### PR TITLE
Fix statefulset absent of kubectl autoscale bash completions

### PR DESCRIPTION
**Pull request by pandaamanda**
**What type of PR is this?**
/kind bug
/kind cleanup

**What this PR does / why we need it**:

Since autoscale support statefulset, we should add statefulset to the bash completions.
```
[root@node24 /]# kubectl autoscale
deployment             --max=                 replicaset             replicationcontroller
```

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by pandaamanda** [comment]
Please take a look, thanks.
/assign @dixudx  @pwittrock

**Comment by pandaamanda** [comment]
PTAL  /assign @rikatz

**Comment by pandaamanda** [comment]
please take a look, tks.
/assign @liggitt

**Review by dixudx — APPROVED** [review]
/ok-to-test
/lgtm

**Pull request merged**
