### PR TITLE
Automated cherry pick of #61146: Add missing binaryData field to the ConfigMap Hash

### PR DESCRIPTION
**Pull request by dims**
Cherry pick of #61146 on release-1.10.

#61146: Add missing binaryData field to the ConfigMap Hash

```release-note
The value of of BinaryData is now used in calculating the hash for the configmap
```

### CODE REVIEW

**Comment by MaciekPytel** [comment]
/hold 
For 1.10.6

**Comment by dims** [comment]
looks like v1.10.6 released today.

/hold cancel

**Pull request merged**
