### PR TITLE
Cleanup: Use a generic Set instead of a specified Set

### PR DESCRIPTION
**Pull request by bzsuni**
What type of PR is this?
/kind cleanup
What this PR does / why we need it:
Use a generic Set instead of a deprecated specified Set

### CODE REVIEW

**Comment by bart0sh** [comment]
@bzsuni As far as I can see there are a lot more usage of the string set in the codebase:
```
ed@devel ~/go/src/k8s.io/kubernetes (118785) $ git grep sets.String |wc -l
519
ed@devel ~/go/src/k8s.io/kubernetes (118785) $ git grep sets.NewString |wc -l
1426
```

I'm not proposing to fix all of them in one PR, but rather wondering why did you pick up these particular modules?

**Comment by bzsuni** [comment]
> I'm not proposing to fix all of them in one PR, but rather wondering why did you pick up these particular modules?


I was only concerned with the code under the /pkg and wasn't sure that these changes were really necessary

**Comment by bart0sh** [comment]
@bzsuni This PR touches codebases of 3 different SIGS, which would theoretically require review and approval from all of them. The PR doesn't fix all usages of the deprecated string set either.

I'd suggest to narrow the scope of this PR to one subdirectory (e.g. pkg/kubelet or pkg/controller) and clean it up **entirelly** by replacing all `sets.NewString` and `sets.String`. This way it would be easier to review and approve the PR.

PS: all CI test failures need to be fixed as well.

**Comment by bzsuni** [comment]
The relevant content has been updated. Thank you for your attention and comments @bart0sh
I am now closing the PR

**Pull request closed without merging**
