### PR TITLE
updates generated runtime for cri v1alpha2

### PR DESCRIPTION
**Pull request by pbarker**
**What this PR does / why we need it**:
Running `make update` on a fresh branch the proto file for cri runtime changes.

**Release note**:
```release-note
updates generated runtime for cri v1alpha2
```

### CODE REVIEW

**Comment by feiskyer** [comment]
Not sure why this has happened. FileDescriptorProto bytes are only different on different platforms, but we're using Docker to generate those files. Maybe someone generates those files manually?

/cc @yujuhong

**Comment by yujuhong** [comment]
Thanks, but this has been fixed in another PR which updated the api. Closing.

**Pull request closed without merging**
