### PR TITLE
Update Azure SDK.

### PR DESCRIPTION
**Pull request by brendandburns**
Updates to the Azure SDK to pick up new APIs.

### CODE REVIEW

**Comment by brendandburns** [comment]
ugh, something is broken here...

**Comment by brendandburns** [comment]
@jbeda this is good to go (once a flaky tests passes) can I get an LGTM?

**Comment by brendandburns** [comment]
@rootfs @colemickens @jbeda This is ready to go (again), can I get an LGTM?  There is nothing here except SDK updates and necessary small changes to the azure client code.

Thanks!

**Comment by rootfs** [comment]
/lgtm

thanks!

**Comment by ixdy** [comment]
I think this may have broken the crossbuild.

From https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-cross-build/2320/:
```
I0712 10:13:02.637] +++ [0712 10:11:46] windows/amd64: go build started
I0712 10:13:02.637] # k8s.io/kubernetes/vendor/github.com/docker/docker/pkg/term/windows
I0712 10:13:02.637] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:139: undefined: winterm.WORD
I0712 10:13:02.637] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:146: undefined: winterm.WORD
I0712 10:13:02.637] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:210: undefined: winterm.WORD
I0712 10:13:02.637] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:210: undefined: winterm.DWORD
I0712 10:13:02.638] vendor/github.com/docker/docker/pkg/term/windows/ansi_reader.go:226: undefined: winterm.DWORD
```

**Comment by ixdy** [comment]
looks like https://github.com/moby/moby/commit/fab67ab677e14c908f879e362f8805c8e91570c6 made it into docker v1.12, but we vendor v1.11. :\

**Pull request merged**
