### PR TITLE
Prune CR typer/defaulter delegation to parameter scheme

### PR DESCRIPTION
**Pull request by yue9944882**
/kind cleanup
/area custom-resources
/sig api-machinery

CR typer/defaulter should always receive unstructured, falling back to parameter scheme seems useless. 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
> CR typer/defaulter should always receive unstructured, falling back to parameter scheme seems useless.

Don't the parameter structs get passed through the typer/defaulter? If so, the code seems more correct as is

**Comment by yue9944882** [comment]
> Don't the parameter structs get passed through the typer/defaulter?

for few legacy resources like `pod/log`, yes. but currently for CR[D], we don't apply the typer/defaulter to parameter structs. or rather, only those resources implements `rest.GetterWithOptions` interface will reuse the parameter codec from request scope struct. for now, CR[D] doesn't implement the interface (and we won't in the future unless we allow declaring parameter structs definition, are we?) so it'd be safe to prune the delegation.  

[https://github.com/kubernetes/kubernetes/blob/6e182ed5ea51b4538c002c67a5c0ceba236e45ad/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/get.go#L163](https://github.com/kubernetes/kubernetes/blob/6e182ed5ea51b4538c002c67a5c0ceba236e45ad/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/get.go#L163)

mostly, when we're decoding json payload as parameter struct (as is shown in the following code), it's using a private scheme w/ pre-defined parameters registered regardless of the parameter codec provided by request scope struct. 


[https://github.com/kubernetes/kubernetes/blob/6e182ed5ea51b4538c002c67a5c0ceba236e45ad/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/delete.go#L89](https://github.com/kubernetes/kubernetes/blob/6e182ed5ea51b4538c002c67a5c0ceba236e45ad/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/delete.go#L89)

**Pull request closed without merging**
