### PR TITLE
Automated cherry pick of #97700: OWNERS: Update SIG Release aliases

### PR DESCRIPTION
**Pull request by hasheddan**
Cherry pick of #97700 on release-1.20.

#97700: OWNERS(sig-release): Remove SIG Release approvers alias

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by liggitt** [comment]
do we want to pick https://github.com/kubernetes/kubernetes/pull/98701 instead so that sig-release can manage this themselves going forward?

**Comment by hasheddan** [comment]
@liggitt yep in my queue for today :+1:

**Comment by hasheddan** [comment]
@liggitt this has been updated to include #98701, which turned out to be a little cleaner than trying to run a separate cherry-pick of only #98701.

**Comment by liggitt** [comment]
/approve

will leave lgtm to sig-release reviewer

**Pull request merged**
