### PR TITLE
Promote Node Instance Type Label to GA

### PR DESCRIPTION
**Pull request by andrewsykim**
**What type of PR is this?**
/kind api-change

**What this PR does / why we need it**:
This PR promotes the beta instance type label to GA:
```
beta.kubernetes.io/instance-type -> node.kubernetes.io/instance-type
```

In addition, both the kubelet and cloud node controller now backfill `node.kubernetes.io/instance-type` to existing nodes so existing clusters upgrading will get the new labels as well. 

The instance type label is widely adopted and should be renamed to reflect it's general availability. The beta instance-type label will be removed in a future release (see KEP below for more details).

**Which issue(s) this PR fixes**:
KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-cloud-provider/20190215-promoting-cloud-provider-labels.md

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Deprecate the instance type beta label ("beta.kubernetes.io/instance-type") in favor of it's GA equivalent: "node.kubernetes.io/instance-type"
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
Actual code here looks good to me - I will let someone with slightly more context on the KEP approve.

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by andrewsykim** [comment]
/hold 

Currently discussing if we need to backfill the new label to existing nodes

**Comment by andrewsykim** [comment]
/milestone v1.17 

Turns out we need to backfill the instance type label so existing nodes get updated, since it's pretty late in the release we're going to add this in v1.17

**Comment by josiahbjorgaard** [comment]
Bug triage for 1.17 here. Code freeze is Nov. 18th. Will this PR be merged by then? If not, can we move it out of the milestone?

**Comment by andrewsykim** [comment]
A lot has changed since this PR was last approved so I'm removing the initial approval. Added backfill logic in the kubelet and cloud node controller so nodes from existing clusters get an update.e 

/approve cancel
/assign @liggitt 

Should be very similar to https://github.com/kubernetes/kubernetes/pull/81431

**Comment by liggitt** [comment]
NodeRestriction admission unit test needs updating with the final GA label:

```
--- FAIL: Test_nodePlugin_Admit (0.04s)
    --- FAIL: Test_nodePlugin_Admit/allow_update_of_my_node:_add_allowed_labels (0.00s)
        admission_test.go:1264: nodePlugin.Admit() error = nodes "mynode" is forbidden: is not allowed to modify labels: kubernetes.io/instance-type, expected 
    --- FAIL: Test_nodePlugin_Admit/allow_update_of_my_node:_remove_allowed_labels (0.00s)
        admission_test.go:1264: nodePlugin.Admit() error = nodes "mynode" is forbidden: is not allowed to modify labels: kubernetes.io/instance-type, expected 
    --- FAIL: Test_nodePlugin_Admit/allow_update_of_my_node:_modify_allowed_labels (0.00s)
        admission_test.go:1264: nodePlugin.Admit() error = nodes "mynode" is forbidden: is not allowed to modify labels: kubernetes.io/instance-type, expected 
    --- FAIL: Test_nodePlugin_Admit/allow_update_of_my_node:_add_allowed_labels_while_forbidden_labels_exist_unmodified (0.00s)
        admission_test.go:1264: nodePlugin.Admit() error = nodes "mynode" is forbidden: is not allowed to modify labels: kubernetes.io/instance-type, expected 
    --- FAIL: Test_nodePlugin_Admit/allow_update_of_my_node:_remove_allowed_labels_while_forbidden_labels_exist_unmodified (0.00s)
        admission_test.go:1264: nodePlugin.Admit() error = nodes "mynode" is forbidden: is not allowed to modify labels: kubernetes.io/instance-type, expected
```

**Comment by liggitt** [comment]
lgtm otherwise

**Comment by andrewsykim** [comment]
Fixed, thanks!

**Comment by liggitt** [comment]
can you open a doc PR to update https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#noderestriction with the final GA labels?

**Pull request merged**
