### PR TITLE
Automated cherry pick of #37392 #37231 #37412 #37255 #37665 #37451 #37810 upstream release 1.5

### PR DESCRIPTION
**Pull request by saad-ali**
Batch cherry pick PRs #37392 #37231 #37412 #37255 #37665 #37451 #37810 from master to release-1.5 branch.

None had merge conflicts that needed to be resolved

CC PR Authors: @Random-Liu @janetkuo @jingxu97 @ixdy @jszczepkowski

### CODE REVIEW

**Comment by ixdy** [comment]
If pulling #37665 you really want #37834 too, which should have merged by now, except SQ sadness.

**Comment by saad-ali** [comment]
> If pulling #37665 you really want #37834 too, which should have merged by now, except SQ sadness.

Ack, will cherry-pick that PR once it merges

**Comment by saad-ali** [comment]
Tests are acting strange. Only 6 tests started. 4 are stuck yellow with "Build started"

**Comment by saad-ali** [comment]
@k8s-bot test this

**Comment by thockin** [comment]
LGTM

**Comment by saad-ali** [comment]
Spoke with @fejta. Looks like the pull request builder is really backlogged so it's taking a while for tests to kick in for each new PR.

**Comment by saad-ali** [comment]
Bumping priority to have cherry picks merge at head of queue once tests are green. Want to give as much time as possible for CI to run against these changes.

**Comment by dims** [comment]
@k8s-bot gci gce e2e test this
@k8s-bot gce etcd3 e2e test this
@k8s-bot kops aws e2e test this

**Comment by dims** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by jszczepkowski** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
