### PR TITLE
Clarify ExternalNames are hostnames

### LINKED ISSUE #52266: Clarify ExternalNames are hostnames not DNS names
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
The documentation claims that `ExternalNames` should be DNS names, but stricter RFC-1123 hostname validation is enforced.

**What you expected to happen**:
The documentation should either specify that they need to be valid RFC-1123 hostnames, or the code should not reject valid DNS names.

**How to reproduce it (as minimally and precisely as possible)**:
Create a `Service` with an `externalName` of `db_eu.example.com`, it throws the following error:

```
The Service "db-eu" is invalid: spec.externalName: Invalid value: "db_eu.example.com": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.2

### PR DESCRIPTION
**Pull request by adnavare**
Updates the documentation for ExternalName to clarify
that they adhere RFC-1123 hostname and are not DNS names.

Fixes #52266

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by cblecker** [comment]
/lgtm
/assign @thockin 
Mind taking a look for api approval, @thockin ?

**Comment by adnavare** [comment]
Thanks @cblecker

**Pull request merged**
