### PR TITLE
kube-gen: cut off dependencies

### PR DESCRIPTION
**Pull request by sttts**
Only gengo is left and apimachinery/pkg/openapi. The later will go away when #48861 merges.

This is the preparation that we can use kube-gen also from apimachinery without circular dependencies.

### CODE REVIEW

**Comment by cblecker** [comment]
The hack/ changes LGTM. Verify is failing on golint (a bunch of stuff under `k8s.io/kube-gen/test/clientset/test_internalclientset`)

**Comment by mbohlool** [comment]
@sttts  in #48861 I kept the main.go file as it cannot be imported go godep.

**Comment by sttts** [comment]
> #48861 I kept the main.go file as it cannot be imported go godep.

@mbohlool that import of kube-openapi should be fine. Your code does not need generated code from kube-gen. So we don't get a circle.

**Comment by cblecker** [comment]
Man is that etcd3 test flaky :\
/test pull-kubernetes-e2e-gce-etcd3

**Comment by caesarxuchao** [comment]
> This is the preparation that we can use kube-gen also from apimachinery without circular dependencies.

Do you plan to import kube-gen from apimachinery?

**Comment by sttts** [comment]
> Do you plan to import kube-gen from apimachinery?

Yes. At least in a future with real authorative repository instead of staging this will be mandatory to recreate generated code in each of them, including apimachinery.

**Pull request merged**
