### PR TITLE
Delete unuse const and fix some typos

### PR DESCRIPTION
**Pull request by ping035627**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
Delete unuse const and fix some typos.

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

/release-note-none
/priority backlog

### CODE REVIEW

**Review by rosti — APPROVED** [review]
Hi @ping035627 and thank you for your contribution!
/lgtm

**Comment by rosti** [comment]
/assign @neolit123 @fabriziopandini 
For approval

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
