### PR TITLE
fixtypo

### PR DESCRIPTION
**Pull request by x1957**
**What this PR does / why we need it**:
fixtypo
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by resouer** [comment]
/assign @timothysc

For approve.

**Comment by jberkus** [comment]
/lgtm

can we just merge this already?  It's a typo, in a comment.

**Pull request merged**
