### PR TITLE
WIP: node: fix for memory manager tests

### PR DESCRIPTION
**Pull request by Tal-or**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:
WIP
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by swatisehgal** [comment]
From the memory manager test failures ( https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/123580/pull-kubernetes-cos-cgroupv2-containerd-node-e2e-serial/1763168457257390080 and https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/123580/pull-kubernetes-node-kubelet-serial-containerd-kubetest2/1763168457072840704) it appears that we have a pod running in the cluster prior to the execution of memory manager metrics test suite.

I think this is a result of us failing to do pod cleanup somewhere.

**Comment by Tal-or** [comment]
superseded by https://github.com/kubernetes/kubernetes/pull/123468

**Pull request closed without merging**
