### PR TITLE
added calico-kubernetes-fedora-digitalocean demo

### PR DESCRIPTION
**Pull request by ozdanborne**

### CODE REVIEW

**Comment by roberthbailey** [comment]
@k8s-bot ok to test

**Comment by djosborne** [comment]
@google-admin Anything I can do to get this merged?

**Comment by erictune** [comment]
I'm on vacation this week (:house: :mouse:) and will take a look next week.

**Comment by erictune** [comment]
lgtm

**Comment by erictune** [comment]
@djosborne flags with underscores are deprecated.  Can you please update the instructions to use the same flags but with dashes.  In particular, in `docs/getting-started-guides/fedora/fedora-calico.md`:

- `--hostname_override=127.0.0.1` :arrow_right: `--hostname-override=127.0.0.1`
- `--api_servers=http://kube-master:8080`  :arrow_right:  `--api-servers=http://kube-master:8080`
- `--admission_control=...`  :arrow_right: `--admission-control-...`
- `--etcd_servers=...` :arrow_right: `--etcd-servers=...`

**Comment by erictune** [comment]
LGTM

**Pull request merged**
