### PR TITLE
Fix various typos in pkg/api

### PR DESCRIPTION
**Pull request by pigmej**
Just fixed some typos + "englishify" in pkg/api

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31229)

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks @pigmej 

Checks failed.

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/31229/kubernetes-pull-verify-all/10690/

A number of files are generated from api/v1/types.go, including the proto and swagger files. Run hack/update-all.sh.

```
/go/src/k8s.io/kubernetes/api/swagger-spec is out of date. Please run hack/update-swagger-spec.sh
FAILED   hack/make-rules/../../hack/verify-swagger-spec.sh	150s
```

**Comment by pigmej** [comment]
@bgrant0607 yeah noticed that, generating them :)

**Comment by pigmej** [comment]
@mbohlool updated PR for autogenerated stuff.

**Comment by pigmej** [comment]
The failed test is rather unrelated to that PR.

**Comment by pigmej** [comment]
@mbohlool can't we merge this in 1.4? It's just typo fix.

**Comment by mbohlool** [comment]
Sure, I had a little concern about changing error messages in validation package, that may break some poor client, but I think we should be fine.

**Pull request merged**
