### PR TITLE
framework.NewNodeInfo: drop pods parameter

### PR DESCRIPTION
**Pull request by ingvagabund**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

NewNodeInfo with a list of pods is used only in unit tests.
It has no other use. Also, the pods can be added to existing
NodeInfo object through AddPod.

No need to have two ways how to pass a list of pods to a NodeInfo
object.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

Towards https://github.com/kubernetes/kubernetes/issues/91782. The next step is to inject featuregating, resp. resource name qualifier (https://github.com/kubernetes/kubernetes/pull/101489) to allow `Resource` data type to be abstracted from `schedutil.IsScalarResourceName` which relies on `k8s.io/kubernetes/pkg/apis/core/v1/helper` helpers.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
I'll wait until #101489 is ready. As it is, I don't see any benefit from this change.

**Review by ehashman — COMMENTED** [review]
/lgtm
/priority important-longterm
/triage accepted

**Comment by ahg-g** [comment]
why is this needed?

**Comment by ingvagabund** [comment]
To minimize the final PR removing the corev1 helpers from pkg/scheduler.

> I'll wait until #101489 is ready. As it is, I don't see any benefit from this change.

/close

**Pull request closed without merging**
