### PR TITLE
CollisionCount should have type int32 across controllers that use it for collision avoidance

### LINKED ISSUE #50530: CollisionCount should have type int32 instead of int64 in all relevant controllers
**What happened**:
While working on PR #49983 (see @thockin's comment on the type), we reached agreement that `CollisionCount` used by the `Deployment`, `DaemonSet`, and `StatefulSet` controllers for name collision avoidance should have type int32 rather than int64. 

**What you expected to happen**:
`CollisionCount` should have type int32 across controllers that use it for collision avoidance.

**How to reproduce it (as minimally and precisely as possible)**:
N/A.

**Anything else we need to know?**:
@kow3ns @thockin @janetkuo

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50530

**Special notes for your reviewer**:
/cc @liyinan926
/assign @kow3ns @thockin @janetkuo 

**Release note**:

```release-note
Change CollisionCount from int64 to int32 across controllers
```

### CODE REVIEW

**Comment by dixudx** [comment]
ping @liyinan926 @kow3ns @janetkuo
Rebased. PTAL. Thanks.

**Comment by thockin** [comment]
As much as I am OK with this, and it should have been int32 to begin with, I was probably wrong about JSON issues wrt fuzzing.  It seems our system is doing the right thing in all places, so we could probably abandon this.

**Comment by dixudx** [comment]
@janetkuo @thockin Rebased and regenerated the files. PTAL. Need your `lgtm` again. Thanks.

**Comment by dixudx** [comment]
/assign @caesarxuchao @davidopp 

Need your `/lgtm` to get it merged. PTAL. Thanks.

**Comment by dixudx** [comment]
ping @thockin @caesarxuchao @davidopp @kow3ns

Rebased. Need your `/lgtm` again. PTAL. Thanks.

**Pull request merged**
