### PR TITLE
add DESIRED and CURRENT columns to rcs,ds,rs

### PR DESCRIPTION
**Pull request by adohe-zz**
@bgrant0607 I just add DESIRED and CURRENT into to ReplicationController, DaemonSet, and ReplicaSet. would you mind reviewing this?

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks!

LGTM

**Comment by bgrant0607** [comment]
@AdoHe Could you send PRs to change the CONTROLLER and JOB column titles to NAME, and to display DESIRED for Job (Spec.Completions), in addition to SUCCESSFUL?

**Comment by AdoHe** [comment]
@bgrant0607 of course I will send a PR.

**Comment by bgrant0607** [comment]
ok to test

**Comment by janetkuo** [comment]
@k8s-bot unit test this issue: #IGNORE (test didn't start)

**Comment by AdoHe** [comment]
@janetkuo would you mind taking a look at the e2e failure? I have opened an issue #21468 I want to get PR merged soon and then I will open other PRs to make kubectl more consistent. Thanks very much :)

**Pull request merged**
