### PR TITLE
Delete load balancers if the UIDs for services don't match.

### LINKED ISSUE #43730: Cloud Provider PublicIP resource Leak when deleting and re-creating multiple services at the same time.
**BUG REPORT**:

**Kubernetes version** (use `kubectl version`):

````
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:40:50Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-15T06:34:56Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
````

**Environment**:
- **Cloud provider or hardware configuration**:
````
azure
````
- **OS** (e.g. from /etc/os-release): 
````
PRETTY_NAME="CentOS Linux 7 (Core)"
````
- **Kernel** (e.g. `uname -a`):
````
Linux kubemaster0 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
````
- **Install tools**: 
````
in-house
````
- **Others**:
CC: @colemickens @brendandburns 

**What happened**:

There are resource leaks in the cloud with respect to PublicIp and LoadBalancer Frontend Ip Pool and HealthProbe

**What you expected to happen**:

All created cloud resources, associated with a deleted service, should be destroyed. This is causing the Azure Load Balancer to fill up its frontend IP Pool which is currently limited to 10 entries. After a few resource leak, the new kuberntes services cannot get valid External IP since the Azure Load Balancer is full. 

**How to reproduce it** (as minimally and precisely as possible):

- Create 5 namespaces and deploy the guestbook-all-in-one.yml example. (making sure you turn on the LoadBalancer type for the frontend service)
- Wait for all of the 5 PublicIP to be provisioned in the Azure Load Balancer.
- Delete all of the 5 namespaces using the `kubectl delete ns <nsX>`
- Poll the namespaces until they are totally gone from kubernetes and recreate them.
- Redeploy the guestbook-all-in-one.yml in all 5 namespaces.

You will probably end up with 5 new IPs BUT not all of the previous ones will be deleted. 

**Anything else we need to know**:

**Kube-Controller-Manager Logs**

[kube-controller-manager.txt](https://github.com/kubernetes/kubernetes/files/874318/kube-controller-manager.txt)

Service IP after the first pod creation
````
[root@saltmaster ~]# kubectl get services --all-namespaces
NAMESPACE     NAME                     CLUSTER-IP        EXTERNAL-IP      PORT(S)                       AGE
default       kubernetes               192.168.0.1       <none>           443/TCP                       8h
kube-system   grafana                  192.168.28.80     52.184.156.62    80:31953/TCP                  7h
kube-system   heapster                 192.168.175.45    <none>           80/TCP                        7h
kube-system   influxdb                 192.168.38.109    52.184.157.3     8083:8083/TCP,8086:8086/TCP   7h
kube-system   k8s-dashboard-dpl-tool   192.168.164.238   <nodes>          9090:9090/TCP                 7h
kube-system   kapacitor                192.168.167.191   <nodes>          9092:9092/TCP                 7h
kube-system   kube-dns                 192.168.0.10      <none>           53/UDP,53/TCP,10054/TCP       7h
kube-system   kube-state-metrics       192.168.109.99    <none>           80/TCP                        7h
kube-system   kubernetes-dashboard     192.168.173.127   <none>           80/TCP                        7h
test1         frontend                 192.168.26.73     52.167.216.18    80:28459/TCP                  6m
test1         redis-master             192.168.94.101    <none>           6379/TCP                      6m
test1         redis-slave              192.168.21.41     <none>           6379/TCP                      6m
test2         frontend                 192.168.182.80    52.184.158.235   80:23436/TCP                  6m
test2         redis-master             192.168.15.131    <none>           6379/TCP                      6m
test2         redis-slave              192.168.137.122   <none>           6379/TCP                      6m
test3         frontend                 192.168.203.37    52.184.157.149   80:18365/TCP                  6m
test3         redis-master             192.168.237.227   <none>           6379/TCP                      6m
test3         redis-slave              192.168.217.46    <none>           6379/TCP                      6m
test4         frontend                 192.168.44.177    52.184.158.222   80:21141/TCP                  6m
test4         redis-master             192.168.56.115    <none>           6379/TCP                      6m
test4         redis-slave              192.168.94.50     <none>           6379/TCP                      6m
test5         frontend                 192.168.96.186    52.184.154.45    80:21171/TCP                  6m
test5         redis-master             192.168.228.221   <none>           6379/TCP                      6m
test5         redis-slave              192.168.98.239    <none>           6379/TCP                      6m
````
Service IP after the re-creation
````
[root@kubemaster0 ~]# kubectl get service --all-namespaces
NAMESPACE     NAME                     CLUSTER-IP        EXTERNAL-IP      PORT(S)                       AGE
default       kubernetes               192.168.0.1       <none>           443/TCP                       8h
kube-system   grafana                  192.168.28.80     52.184.156.62    80:31953/TCP                  8h
kube-system   heapster                 192.168.175.45    <none>           80/TCP                        8h
kube-system   influxdb                 192.168.38.109    52.184.157.3     8083:8083/TCP,8086:8086/TCP   8h
kube-system   k8s-dashboard-dpl-tool   192.168.164.238   <nodes>          9090:9090/TCP                 8h
kube-system   kapacitor                192.168.167.191   <nodes>          9092:9092/TCP                 8h
kube-system   kube-dns                 192.168.0.10      <none>           53/UDP,53/TCP,10054/TCP       8h
kube-system   kube-state-metrics       192.168.109.99    <none>           80/TCP                        7h
kube-system   kubernetes-dashboard     192.168.173.127   <none>           80/TCP                        8h
test1         frontend                 192.168.217.229   52.184.182.50    80:30532/TCP                  9m
test1         redis-master             192.168.241.171   <none>           6379/TCP                      9m
test1         redis-slave              192.168.47.101    <none>           6379/TCP                      9m
test2         frontend                 192.168.116.19    52.184.185.178   80:13829/TCP                  7m
test2         redis-master             192.168.128.86    <none>           6379/TCP                      7m
test2         redis-slave              192.168.221.99    <none>           6379/TCP                      7m
test3         frontend                 192.168.140.231   52.167.213.164   80:14027/TCP                  7m
test3         redis-master             192.168.21.217    <none>           6379/TCP                      7m
test3         redis-slave              192.168.37.14     <none>           6379/TCP                      7m
test4         frontend                 192.168.194.229   52.184.181.215   80:7269/TCP                   7m
test4         redis-master             192.168.113.141   <none>           6379/TCP                      7m
test4         redis-slave              192.168.138.243   <none>           6379/TCP                      7m
test5         frontend                 192.168.111.68    52.167.212.141   80:13231/TCP                  7m
test5         redis-master             192.168.249.202   <none>           6379/TCP                      7m
test5         redis-slave              192.168.65.147    <none>           6379/TCP                      7m
````

Azure frontend Pool Screen Shot
screen shot 2017-03-27 at 22 17 38

### PR DESCRIPTION
**Pull request by brendandburns**
An attempt to fix https://github.com/kubernetes/kubernetes/issues/43730

@thockin @djsly

### CODE REVIEW

**Comment by quinton-hoole** [comment]
This does not compile:

I0811 23:56:00.722] pkg/controller/service/service_controller.go:227: undefined: ok
I0811 23:56:00.722] pkg/controller/service/service_controller.go:792: invalid method expression cachedService.nextRetryDelay (needs pointer receiver: (*cachedService).nextRetryDelay)
I0811 23:56:00.723] pkg/controller/service/service_controller.go:792: cachedService.nextRetryDelay undefined (type cachedService has no method nextRetryDelay)
I0811 23:56:00.723] pkg/controller/service/service_controller.go:795: undefined: key
I0811 23:56:00.723] pkg/controller/service/service_controller.go:797: invalid method expression cachedService.resetRetryDelay (needs pointer receiver: (*cachedService).resetRetryDelay)
I0811 23:56:00.723] pkg/controller/service/service_controller.go:797: cachedService.resetRetryDelay undefined (type cachedService has no method resetRetryDelay)
I

**Comment by brendandburns** [comment]
@quinton-hoole hah, that's what I get for using CI/CD as my compiler...

Fixed (I think)

**Comment by djsly** [comment]
LTGM!, simple and clean fix.  thanks @brendanburns 

It will increase the LB creation time if a namespace with 10/20 services get deleted and recreated right after, which I think is acceptable considering that the leak issue will be gone. (that the major complaint)

The only potential issue I can see, would be that a service using the same `key` will never see the day iff it's previous instance could not be cleaned up properly, the deletion logic will go on forever preventing the creation of the new LB.
At least, the deletion error events sent to the service describe page, might puzzle the user who just asked for the service to be created, but will provide some insight as to what might be going on with the service.

**Comment by bowei** [comment]
is there any way to test this?

**Comment by brendandburns** [comment]
@bowei it might be possible to unit test, but tricky to get the sequence correct. Id prefer to merge and add an issue to add the test.

**Comment by djsly** [comment]
@brendanburns and @jdumars Possible to make it a 1.7 candidate?

**Comment by brendandburns** [comment]
marked, though we're getting pretty close to 1.8

**Pull request merged**
