### PR TITLE
Updating stale api-reference docs

### PR DESCRIPTION
**Pull request by nikhiljindal**
PR produced by running:

```
./hack/gen-swagger-doc/run-gen-swagger-docs.sh v1
```

We need to ensure that these docs are updated each time swagger spec is changed: https://github.com/kubernetes/kubernetes/issues/14069

cc @caesarxuchao

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Glad to see that script is still working. Now the html contains the descriptions for types as well. Thank you.

One thing I noticed that's wrong in the types.go:
https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L594

And there are other occurances of "Required:" in the comments in types.go, which shouldn't be there.

Could you also fix those in this PR? Thanks.

**Comment by nikhiljindal** [comment]
Good catch!
As much as I would love to see that fixed, I wont be able to get to that before 1.1. Any chance you can get to it?

And should we wait for the fix before submitting this PR or is it fine to submit this since the docs are way too stale right now (They were last updated more than 5 weeks back).

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
Jenkins failed on:
```
Kubernetes e2e suite.ReplicationController should serve a basic image on each replica with a public image
```
This is a docs only change and should not have any effect on that.

@k8s-bot ok to test

**Comment by caesarxuchao** [comment]
Thank you @nikhiljindal. I'll open another issue.

**Pull request merged**
