### PR TITLE
Ensure that init containers are preserved during pruning

### LINKED ISSUE #25919: flake: Pods should invoke init containers on a RestartNever pod
https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gke/7330/

```
[It] should invoke init containers on a RestartNever pod
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:725
STEP: creating the pod
W0519 14:55:33.521095    4451 request.go:347] Field selector: v1 - pods - metadata.name - pod-init-6935827c-1e0c-11e6-95d8-0242ac110014: need to check if this is versioned correctly.
E0519 15:00:33.521615    4451 streamwatcher.go:109] Unable to decode an event from the watch stream: net/http: request canceled (Client.Timeout exceeded while reading body)
[AfterEach] [k8s.io] Pods
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:109
STEP: Collecting events from namespace "e2e-tests-pods-eisug".
May 19 15:00:33.554: INFO: At {2016-05-19 14:55:33 -0700 PDT} - event for pod-init-6935827c-1e0c-11e6-95d8-0242ac110014: {default-scheduler } Scheduled: Successfully assigned pod-init-6935827c-1e0c-11e6-95d8-0242ac110014 to gke-jenkins-e2e-default-pool-0df8cd6f-fnc6
May 19 15:00:33.554: INFO: At {2016-05-19 14:55:35 -0700 PDT} - event for pod-init-6935827c-1e0c-11e6-95d8-0242ac110014: {kubelet gke-jenkins-e2e-default-pool-0df8cd6f-fnc6} Pulled: Container image "gcr.io/google_containers/busybox:1.24" already present on machine
May 19 15:00:33.554: INFO: At {2016-05-19 14:55:35 -0700 PDT} - event for pod-init-6935827c-1e0c-11e6-95d8-0242ac110014: {kubelet gke-jenkins-e2e-default-pool-0df8cd6f-fnc6} Created: Created container with docker id 9d754e3d878d
May 19 15:00:33.554: INFO: At {2016-05-19 14:55:35 -0700 PDT} - event for pod-init-6935827c-1e0c-11e6-95d8-0242ac110014: {kubelet gke-jenkins-e2e-default-pool-0df8cd6f-fnc6} Started: Started container with docker id 9d754e3d878d
May 19 15:00:33.554: INFO: At {2016-05-19 14:55:37 -0700 PDT} - event for pod-init-6935827c-1e0c-11e6-95d8-0242ac110014: {kubelet gke-jenkins-e2e-default-pool-0df8cd6f-fnc6} Created: Created container with docker id cbf2532f0b70
May 19 15:00:33.554: INFO: At {2016-05-19 14:55:37 -0700 PDT} - event for pod-init-6935827c-1e0c-11e6-95d8-0242ac110014: {kubelet gke-jenkins-e2e-default-pool-0df8cd6f-fnc6} Started: Started container with docker id cbf2532f0b70
May 19 15:00:33.554: INFO: At {2016-05-19 14:55:39 -0700 PDT} - event for pod-init-6935827c-1e0c-11e6-95d8-0242ac110014: {kubelet gke-jenkins-e2e-default-pool-0df8cd6f-fnc6} Created: Created container with docker id df6944338ff1
May 19 15:00:33.554: INFO: At {2016-05-19 14:55:39 -0700 PDT} - event for pod-init-6935827c-1e0c-11e6-95d8-0242ac110014: {kubelet gke-jenkins-e2e-default-pool-0df8cd6f-fnc6} Started: Started container with docker id df6944338ff1
May 19 15:00:33.566: INFO: POD                                                               NODE                                        PHASE    GRACE  CONDITIONS
May 19 15:00:33.566: INFO: foo-nnhfd                                                         gke-jenkins-e2e-default-pool-0df8cd6f-mxoo  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:54:35 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:54:38 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:54:35 -0700 PDT}  }]
May 19 15:00:33.566: INFO: foo-y536v                                                         gke-jenkins-e2e-default-pool-0df8cd6f-fnc6  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:54:35 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:54:37 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:54:35 -0700 PDT}  }]
May 19 15:00:33.566: INFO: pod-init-6935827c-1e0c-11e6-95d8-0242ac110014                     gke-jenkins-e2e-default-pool-0df8cd6f-fnc6  Pending  30s    [{Initialized False {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:55:41 -0700 PDT} ContainersNotInitialized containers with incomplete status: [init1]} {Ready False {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:55:33 -0700 PDT} ContainersNotReady containers with unready status: [run1]} {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:55:33 -0700 PDT}  }]
May 19 15:00:33.566: INFO: foo-9tpg5                                                         gke-jenkins-e2e-default-pool-0df8cd6f-fnc6  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:56:27 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:56:29 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:56:27 -0700 PDT}  }]
May 19 15:00:33.566: INFO: foo-z8s4m                                                         gke-jenkins-e2e-default-pool-0df8cd6f-mxoo  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:56:27 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:56:29 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:56:27 -0700 PDT}  }]
May 19 15:00:33.566: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-0df8cd6f-fnc6  gke-jenkins-e2e-default-pool-0df8cd6f-fnc6  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:59 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:21 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:59 -0700 PDT}  }]
May 19 15:00:33.566: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-0df8cd6f-mxoo  gke-jenkins-e2e-default-pool-0df8cd6f-mxoo  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:59 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:21 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:59 -0700 PDT}  }]
May 19 15:00:33.566: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-0df8cd6f-yust  gke-jenkins-e2e-default-pool-0df8cd6f-yust  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:53 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:17 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:53 -0700 PDT}  }]
May 19 15:00:33.566: INFO: heapster-v1.1.0.beta1-2658213798-otbd7                            gke-jenkins-e2e-default-pool-0df8cd6f-mxoo  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:29 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:36 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:29 -0700 PDT}  }]
May 19 15:00:33.566: INFO: kube-dns-v11-ykwl2                                                gke-jenkins-e2e-default-pool-0df8cd6f-yust  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:53 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:53:03 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:51 -0700 PDT}  }]
May 19 15:00:33.566: INFO: kube-proxy-gke-jenkins-e2e-default-pool-0df8cd6f-fnc6             gke-jenkins-e2e-default-pool-0df8cd6f-fnc6  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:59 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:34 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:59 -0700 PDT}  }]
May 19 15:00:33.566: INFO: kube-proxy-gke-jenkins-e2e-default-pool-0df8cd6f-mxoo             gke-jenkins-e2e-default-pool-0df8cd6f-mxoo  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:59 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:14 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:59 -0700 PDT}  }]
May 19 15:00:33.566: INFO: kube-proxy-gke-jenkins-e2e-default-pool-0df8cd6f-yust             gke-jenkins-e2e-default-pool-0df8cd6f-yust  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:53 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:11 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:53 -0700 PDT}  }]
May 19 15:00:33.566: INFO: kubernetes-dashboard-v1.0.1-lpmgq                                 gke-jenkins-e2e-default-pool-0df8cd6f-yust  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:53 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:25 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:51 -0700 PDT}  }]
May 19 15:00:33.566: INFO: l7-lb-controller-v0.6.0-hqjq8                                     gke-jenkins-e2e-default-pool-0df8cd6f-yust  Running         [{Initialized True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:53 -0700 PDT}  } {Ready True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:52:40 -0700 PDT}  } {PodScheduled True {0001-01-01 00:00:00 +0000 UTC} {2016-05-19 14:51:51 -0700 PDT}  }]
May 19 15:00:33.566: INFO: 
May 19 15:00:33.571: INFO: 
Logging node info for node gke-jenkins-e2e-default-pool-0df8cd6f-fnc6
May 19 15:00:33.575: INFO: Node Info: kind:"" apiVersion:"" 
May 19 15:00:33.576: INFO: 
Logging kubelet events for node gke-jenkins-e2e-default-pool-0df8cd6f-fnc6
May 19 15:00:33.607: INFO: 
Logging pods the kubelet thinks is on node gke-jenkins-e2e-default-pool-0df8cd6f-fnc6
May 19 15:00:33.619: INFO: foo-9tpg5 started at 2016-05-19T14:56:27-07:00 (0+1 container statuses recorded)
May 19 15:00:33.619: INFO: 	Container c ready: true, restart count 0
May 19 15:00:33.619: INFO: kube-proxy-gke-jenkins-e2e-default-pool-0df8cd6f-fnc6 started at <nil> (0+0 container statuses recorded)
May 19 15:00:33.619: INFO: foo-y536v started at 2016-05-19T14:54:35-07:00 (0+1 container statuses recorded)
May 19 15:00:33.619: INFO: 	Container c ready: true, restart count 0
May 19 15:00:33.619: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-0df8cd6f-fnc6 started at <nil> (0+0 container statuses recorded)
W0519 15:00:33.625505    4451 metrics_grabber.go:74] Master node is not registered. Grabbing metrics from Scheduler and ControllerManager is disabled.
May 19 15:00:33.690: INFO: 
Latency metrics for node gke-jenkins-e2e-default-pool-0df8cd6f-fnc6
May 19 15:00:33.690: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.99 Latency:1m15.178872s}
May 19 15:00:33.690: INFO: {Operation:SyncPod Method:container_manager_latency_microseconds Quantile:0.99 Latency:49.623859s}
May 19 15:00:33.690: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.9 Latency:41.109646s}
May 19 15:00:33.690: INFO: {Operation:stop_container Method:docker_operations_latency_microseconds Quantile:0.99 Latency:30.172187s}
May 19 15:00:33.690: INFO: {Operation:pull_image Method:docker_operations_latency_microseconds Quantile:0.99 Latency:19.312087s}
May 19 15:00:33.690: INFO: {Operation:pull_image Method:docker_operations_latency_microseconds Quantile:0.9 Latency:10.909938s}
May 19 15:00:33.690: INFO: 
Logging node info for node gke-jenkins-e2e-default-pool-0df8cd6f-mxoo
May 19 15:00:33.694: INFO: Node Info: kind:"" apiVersion:"" 
May 19 15:00:33.694: INFO: 
Logging kubelet events for node gke-jenkins-e2e-default-pool-0df8cd6f-mxoo
May 19 15:00:33.783: INFO: 
Logging pods the kubelet thinks is on node gke-jenkins-e2e-default-pool-0df8cd6f-mxoo
May 19 15:00:33.816: INFO: kube-proxy-gke-jenkins-e2e-default-pool-0df8cd6f-mxoo started at <nil> (0+0 container statuses recorded)
May 19 15:00:33.816: INFO: foo-z8s4m started at 2016-05-19T14:56:27-07:00 (0+1 container statuses recorded)
May 19 15:00:33.816: INFO: 	Container c ready: true, restart count 0
May 19 15:00:33.816: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-0df8cd6f-mxoo started at <nil> (0+0 container statuses recorded)
May 19 15:00:33.816: INFO: foo-nnhfd started at 2016-05-19T14:54:35-07:00 (0+1 container statuses recorded)
May 19 15:00:33.816: INFO: 	Container c ready: true, restart count 0
May 19 15:00:33.816: INFO: heapster-v1.1.0.beta1-2658213798-otbd7 started at 2016-05-19T14:52:29-07:00 (0+2 container statuses recorded)
May 19 15:00:33.816: INFO: 	Container heapster ready: true, restart count 0
May 19 15:00:33.816: INFO: 	Container heapster-nanny ready: true, restart count 0
W0519 15:00:33.827717    4451 metrics_grabber.go:74] Master node is not registered. Grabbing metrics from Scheduler and ControllerManager is disabled.
May 19 15:00:33.909: INFO: 
Latency metrics for node gke-jenkins-e2e-default-pool-0df8cd6f-mxoo
May 19 15:00:33.909: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.99 Latency:2m12.940414s}
May 19 15:00:33.909: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.9 Latency:40.007999s}
May 19 15:00:33.909: INFO: {Operation: Method:pod_worker_start_latency_microseconds Quantile:0.99 Latency:40.00792s}
May 19 15:00:33.909: INFO: {Operation:SyncPod Method:container_manager_latency_microseconds Quantile:0.99 Latency:37.240203s}
May 19 15:00:33.909: INFO: {Operation:stop_container Method:docker_operations_latency_microseconds Quantile:0.99 Latency:30.054067s}
May 19 15:00:33.909: INFO: {Operation:pull_image Method:docker_operations_latency_microseconds Quantile:0.99 Latency:19.222831s}
May 19 15:00:33.909: INFO: {Operation:pull_image Method:docker_operations_latency_microseconds Quantile:0.9 Latency:14.438603s}
May 19 15:00:33.909: INFO: 
Logging node info for node gke-jenkins-e2e-default-pool-0df8cd6f-yust
May 19 15:00:33.913: INFO: Node Info: kind:"" apiVersion:"" 
May 19 15:00:33.914: INFO: 
Logging kubelet events for node gke-jenkins-e2e-default-pool-0df8cd6f-yust
May 19 15:00:33.920: INFO: 
Logging pods the kubelet thinks is on node gke-jenkins-e2e-default-pool-0df8cd6f-yust
May 19 15:00:33.933: INFO: kube-proxy-gke-jenkins-e2e-default-pool-0df8cd6f-yust started at <nil> (0+0 container statuses recorded)
May 19 15:00:33.933: INFO: kube-dns-v11-ykwl2 started at 2016-05-19T14:51:53-07:00 (0+4 container statuses recorded)
May 19 15:00:33.933: INFO: 	Container etcd ready: true, restart count 0
May 19 15:00:33.933: INFO: 	Container healthz ready: true, restart count 0
May 19 15:00:33.933: INFO: 	Container kube2sky ready: true, restart count 0
May 19 15:00:33.933: INFO: 	Container skydns ready: true, restart count 0
May 19 15:00:33.933: INFO: kubernetes-dashboard-v1.0.1-lpmgq started at 2016-05-19T14:51:53-07:00 (0+1 container statuses recorded)
May 19 15:00:33.933: INFO: 	Container kubernetes-dashboard ready: true, restart count 0
May 19 15:00:33.933: INFO: l7-lb-controller-v0.6.0-hqjq8 started at 2016-05-19T14:51:53-07:00 (0+2 container statuses recorded)
May 19 15:00:33.933: INFO: 	Container default-http-backend ready: true, restart count 0
May 19 15:00:33.933: INFO: 	Container l7-lb-controller ready: true, restart count 0
May 19 15:00:33.933: INFO: fluentd-cloud-logging-gke-jenkins-e2e-default-pool-0df8cd6f-yust started at <nil> (0+0 container statuses recorded)
W0519 15:00:33.938564    4451 metrics_grabber.go:74] Master node is not registered. Grabbing metrics from Scheduler and ControllerManager is disabled.
May 19 15:00:34.052: INFO: 
Latency metrics for node gke-jenkins-e2e-default-pool-0df8cd6f-yust
May 19 15:00:34.052: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.99 Latency:1m27.970115s}
May 19 15:00:34.052: INFO: {Operation: Method:pod_worker_start_latency_microseconds Quantile:0.99 Latency:40.011826s}
May 19 15:00:34.052: INFO: {Operation: Method:pod_start_latency_microseconds Quantile:0.9 Latency:37.427391s}
May 19 15:00:34.052: INFO: {Operation:SyncPod Method:container_manager_latency_microseconds Quantile:0.99 Latency:35.279983s}
May 19 15:00:34.052: INFO: {Operation:stop_container Method:docker_operations_latency_microseconds Quantile:0.99 Latency:30.050298s}
May 19 15:00:34.052: INFO: {Operation:pull_image Method:docker_operations_latency_microseconds Quantile:0.99 Latency:24.778446s}
May 19 15:00:34.052: INFO: {Operation:create Method:pod_worker_latency_microseconds Quantile:0.99 Latency:20.007326s}
May 19 15:00:34.052: INFO: {Operation:create Method:pod_worker_latency_microseconds Quantile:0.9 Latency:20.007326s}
May 19 15:00:34.052: INFO: Waiting up to 1m0s for all nodes to be ready
STEP: Destroying namespace "e2e-tests-pods-eisug" for this suite.


â€¢ Failure [305.635 seconds]
[k8s.io] Pods
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:508
  should invoke init containers on a RestartNever pod [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:725

  Expected
      <*errors.errorString | 0xc820095f10>: {
          s: "timed out waiting for the condition",
      }
  to be nil

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:710
```

### LINKED ISSUE #26131: [k8s.io] Pods should invoke init containers on a RestartNever pod {Kubernetes e2e suite}
https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gke/7628/

Failed: [k8s.io] Pods should invoke init containers on a RestartNever pod {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:725
Expected
    <*errors.errorString | 0xc8200e5060>: {
        s: "timed out waiting for the condition",
    }
to be nil
```

### PR DESCRIPTION
**Pull request by smarterclayton**
Pods with multiple init containers were getting the wrong containers
pruned. Fix an error message and add a test.

Fixes #26131

### CODE REVIEW

**Comment by yujuhong** [comment]
@k8s-oncall please consider manually merging this PR to fix the init container tests, once the e2e tests are green.

**Comment by smarterclayton** [comment]
gofmt changes, reapplied label

**Comment by smarterclayton** [comment]
@k8s-bot test this issue #IGNORE (e2e tests never reran)

**Comment by smarterclayton** [comment]
@k8s-bot test this issue #IGNORE (e2e tests never reran)

**Comment by smarterclayton** [comment]
New unit test had an ordering problem, sorted the output from the FakeDockerClient.

**Comment by smarterclayton** [comment]
@k8s-bot test this issue #26204 

Recreate deployment flaked, but it looked like a teardown problem, not a init container problem.

**Comment by yujuhong** [comment]
@k8s-bot test this issue #26187

**Comment by yujuhong** [comment]
@k8s-bot test this issue #26187

**Comment by yujuhong** [comment]
@k8s-bot test this issue #26187

**Comment by sttts** [comment]
@k8s-bot test this issue #20576

**Comment by yujuhong** [comment]
@k8s-bot test this issue #26180

**Comment by roberthbailey** [comment]
Bumping to P0 since this addresses a flaky test.

**Comment by roberthbailey** [comment]
e2e failed 25 tests, which seems like an aberration given that the previous run only failed one flake. 

@k8s-bot test this: issue: #IGNORE

**Comment by roberthbailey** [comment]
Possibly a coincidence, but kubernetes-e2e-gce-slow run 5980 also just failed 25 tests.

**Comment by yujuhong** [comment]
> Possibly a coincidence, but kubernetes-e2e-gce-slow run 5980 also just failed 25 tests.

5989 failed because the kube-system pods are not ready.

**Comment by yujuhong** [comment]
The failures were partially due to images not being pre-pulled: https://github.com/kubernetes/kubernetes/pull/25784#issuecomment-221656690

**Comment by yujuhong** [comment]
@k8s-bot test this issue: #25277

**Comment by yujuhong** [comment]
@k8s-bot test this issue: #26270

**Comment by yujuhong** [comment]
@k8s-oncall, the submit queue is currently blocked because of the init container flake, which will be fixed by this PR.

**Pull request merged**
