### PR TITLE
correct errorLog format

### PR DESCRIPTION
**Pull request by caiyixiang**
Error strings should not be capitalized (unless beginning with proper nouns or acronyms) or end with punctuation.I read this in Go Code Review Comments,but that's a bigger fight,need to step by step

### CODE REVIEW

**Comment by thockin** [comment]
You're opening a can of worms.  Across our codebase (quick grep, probably inaccurate) we have about 3x as many log lines that start with [A-Z] than [a-z].  I have a personal preference for lower-case, since it is more consistent with error messages (which Go does proscribe to start with lower-case).  But Are we really going to change literally thousands of log lines AND try to police that over the long term?

If you're signing up to do all that work - and some of it is just going to be manual, looking for proper nouns, type names, field names, acronyms, etc - we can have a discussion about including this as a convention.  It's my base position that it is not worth the energy, but if you want to spend your own energy on it, I probably won't say no.  I can think of more meaningful changes to the way we do logging, though, if you want ideas :)

@bgrant0607 @smarterclayton @timstclaitr @piosz

**Comment by bgrant0607** [comment]
Thanks, but this change is not worth the cost IMO.

**Comment by smarterclayton** [comment]
I agree with Brian.

**Comment by timstclair** [comment]
From https://github.com/golang/go/wiki/CodeReviewComments#error-strings, emphasis mine:

> Error strings should not be capitalized (unless beginning with proper nouns or acronyms) or end with punctuation, since they are usually printed following other context. That is, use `fmt.Errorf("something bad")` not `fmt.Errorf("Something bad")`, so that `log.Printf("Reading %s: %v", filename, err)` formats without a spurious capital letter mid-message. **This does not apply to logging, which is implicitly line-oriented and not combined inside other messages.**

**Pull request closed without merging**
