### PR TITLE
Use log functions of core framework on testsuites/topology.go

### PR DESCRIPTION
**Pull request by k-toyoda-pi**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR makes test/e2e/storage/testsuites/topology.go to use log functions of core framework.

**Which issue(s) this PR fixes**:
Ref #81427

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by oomichi** [comment]
Thanks for doing this.

/lgtm
/approve

**Review by copejon — APPROVED** [review]
lgtm

**Comment by oomichi** [comment]
oops, need to be rebased.
@k-toyoda-pi Could you rebase this for the latest master?

/lgtm cancel

**Review by odinuge — APPROVED** [review]
/lgtm

**Pull request merged**
