### PR TITLE
changelog: add changelogs for all release back due branch FF merge issue

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**
/kind bug
/kind cleanup

Please let me know if this is the correct thing to do
/cc @liggitt @saschagrunert @justaugustus 

**What this PR does / why we need it**:
Add changelogs from the previous release back to the release branch. For more context: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1584125100036500

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by cpanato** [comment]
did the branch FF based on this PR and it works
```
root@ubuntu-s-6vcpu-16gb-fra1-01:~/k/kubernetes#  git branch --set-upstream-to=origin/release-1.99 release-1.99
Branch 'release-1.99' set up to track remote branch 'release-1.99' from 'origin'.
root@ubuntu-s-6vcpu-16gb-fra1-01:~/k/kubernetes# cd ../release/
root@ubuntu-s-6vcpu-16gb-fra1-01:~/k/release# ../../bin/krel ff --branch release-1.99 --repo /root/k/kubernetes
INFO Preparing to fast-forward origin/master onto the release-1.99 branch
INFO Using dry mode, which does not modify any remote content
INFO Checking if "release-1.99" is a release branch
INFO Checking if branch is available on the default remote
INFO Verifying release-1.99 branch exists on the remote
INFO Found branch release-1.99
INFO Checking out release branch
INFO Finding merge base between "master" and "release-1.99"
INFO merge base is 55bb72b77444f7279fb268652df377422792c9f0
INFO Merge base tag is: v1.11.0-alpha.0
INFO Verified that the latest master tag is the same as the merge base tag
INFO Latest release branch revision is 8f07cdcc91ef750356c991cfec1a7d99b4f1832b
INFO Merging master changes into release branch
Merge made by the 'recursive' strategy.
 CHANGELOG/CHANGELOG-1.15.md                        | 166 +++++++++++++------
 CHANGELOG/CHANGELOG-1.16.md                        | 175 +++++++++++++++------
 CHANGELOG/CHANGELOG-1.17.md                        | 150 ++++++++++++++----
 api/openapi-spec/swagger.json                      |   2 +-
 build/release-images.sh                            |   4 +-
 cluster/addons/dns/nodelocaldns/nodelocaldns.yaml  |   4 +
 cluster/gce/gci/configure.sh                       |   2 +-
 cluster/gce/manifests/cluster-autoscaler.manifest  |   2 +-
 cmd/kubelet/app/server.go                          |   4 +-
 pkg/apis/networking/types.go                       |   7 +-
 pkg/controller/endpointslice/reconciler.go         |  42 ++---
 pkg/controller/util/endpoint/controller_utils.go   |   8 +-
 .../util/endpoint/controller_utils_test.go         |  43 ++++-
 pkg/scheduler/scheduler.go                         |   2 +-
 .../k8s.io/api/networking/v1beta1/generated.proto  |   7 +-
 staging/src/k8s.io/api/networking/v1beta1/types.go |   7 +-
 .../v1beta1/types_swagger_doc_generated.go         |   2 +-
 test/e2e/framework/metrics/metrics_grabber.go      |   4 +-
 18 files changed, 462 insertions(+), 169 deletions(-)
Go look around in /root/k/kubernetes to make sure things look okay before pushing…

Check for files left uncommitted using:

        git status -s

Validate the fast-forward commit using:

        git show

Validate the changes pulled in from master using:

        git log origin/release-1.99..origin/master

Once the branch fast-forward is complete, the diff will be available after push at:

        https://github.com/kubernetes/kubernetes/compare/8f07cdcc91e...2b976da4f23
```

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
