### PR TITLE
missing the format string

### PR DESCRIPTION
**Pull request by yanxuean**
Signed-off-by: yanxuean <yan.xuean@zte.com.cn>

**What this PR does / why we need it**:
missing the format string
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by yanxuean** [comment]
@smarterclayton   PTAL

**Comment by yanxuean** [comment]
/assign @Random-Liu @yujuhong 
ping for approve

**Comment by yanxuean** [comment]
ping for approve  @yujuhong

**Comment by yanxuean** [comment]
ping for approve @yujuhong @Random-Liu

**Comment by yujuhong** [comment]
I don't have permission to approve. 
/unassign

**Comment by yanxuean** [comment]
sorry. thanks. @yujuhong

**Comment by yanxuean** [comment]
/assign @liggitt 
PTAL

**Pull request merged**
