### PR TITLE
Remove deprecated insecure serving

### PR DESCRIPTION
**Pull request by navist2020**
#### What type of PR is this?
/kind cleanup
/kind deprecation

#### What this PR does / why we need it:
Remove deprecated insecure serving
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by fedebongio** [comment]
Daniel, hopefully you can take this one?
/triage accepted

**Comment by lavalamp** [comment]
/ok-to-test

I expected this to be a 1k line change, I'm pretty sure there's a ton of references but let's see

**Pull request closed without merging**
