### PR TITLE
Fixes wrong "kubectl config set-credentials" examples

### PR DESCRIPTION
**Pull request by fabianofranz**

### CODE REVIEW

**Comment by jlowdermilk** [comment]
Thanks for the fix! You'll need to run `hack/run-gendocs.sh` to regenerate the kubectl docs (examples are included in help text).

**Comment by fabianofranz** [comment]
@jlowdermilk fixed, thanks.

**Comment by jlowdermilk** [comment]
@k8s-bot ok to test

**Comment by jlowdermilk** [comment]
lgtm

**Comment by jlowdermilk** [comment]
Shippable failure is known issue dealt with in #10199. @quinton-hoole assigned for second pair of eyes.

**Comment by quinton-hoole** [comment]
LGTM

**Comment by quinton-hoole** [comment]
@dchen1107 for second ok-to-merge approval.  The usual suspects are OOTO.

**Comment by dchen1107** [comment]
This is doc related changes, not need for second. But still lgtm and thanks.

**Pull request merged**
