### PR TITLE
Make NodeController test utils usable from outside

### PR DESCRIPTION
**Pull request by gmarek**
Required to fix tests for #37365 and useful in general.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37370)

### CODE REVIEW

**Comment by saad-ali** [comment]
This is in the 1.5 milestone. Does this need to be cherry-picked to 1.5? If so make sure to add `cherrypick-candidate` label

**Comment by gmarek** [comment]
Depend in #37365 will need to be cherry-picked. It's @davidopp call.

**Comment by davidopp** [comment]
This is useful but I don't think we should cherrypick it.

**Comment by saad-ali** [comment]
> This is useful but I don't think we should cherrypick it.

Will not cherry pick to 1.5

**Pull request merged**
