### PR TITLE
Automated cherry pick of #58223: Adjust the Stackdriver Logging length test

### PR DESCRIPTION
**Pull request by crassirostris**
Cherry pick of #58223 on release-1.9.

#58223: Adjust the Stackdriver Logging length test

This cherry-pick also includes changes from https://github.com/kubernetes/kubernetes/pull/57335

```release-note
NONE
```

### CODE REVIEW

**Comment by crassirostris** [comment]
To fix testing logging in 1.9 branch (https://k8s-testgrid.appspot.com/google-gke-stackdriver#sd-logging-gci-1.9)

**Comment by mbohlool** [comment]
@crassirostris the parent PR is a one line change but this cherrypick is touching more than that line. can you check that?

**Comment by crassirostris** [comment]
@mbohlool This cherry-pick includes https://github.com/kubernetes/kubernetes/pull/57335, sorry for not mentioning this earlier

**Comment by mbohlool** [comment]
test only cherrypick is approved.

@crassirostris thanks.

**Pull request merged**
