### PR TITLE
fix logging on e2e metrics grabber test

### PR DESCRIPTION
**Pull request by aojea**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature

/kind flake

**What this PR does / why we need it**:

Logging the wrong variable as error
https://github.com/kubernetes/kubernetes/issues/86318#issuecomment-598480036

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/approve
/retest

/milestone v1.18
test-only change working to resolve prominent flake

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Pull request merged**
