### PR TITLE
add myself as pkg/kubelet/server approver

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kim.andrewsy@gmail.com>

Spoke with Derek about possible areas in kubelet to help clean up, `pkg/kubelet/server` came up as a good candidate.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
We definitely need to better organize `/pkg/kubelet/server` so that the endpoints kubelet itself serves are better structured.

A good candidate to follow-up from would be here:
https://github.com/kubernetes/kubernetes/pull/98458

**Comment by andrewsykim** [comment]
sgtm, will re-open then :) 

/close

**Pull request closed without merging**
