### PR TITLE
Gang scheduling proposal doc

### PR DESCRIPTION
**Pull request by mali11**
Following the discussion of the gang scheduling #16845, I would like to raise a proposal to describe an initial design and address the issues more specifically.

The proposal does not cover the conflicts handling introduced by multiple schedulers because:
1. Multiple schedulers or horizontal scaling schedulers are not yet implemented
2. It involves significant amount of complexity which I think it's better to be addressed separately

cc @davidopp @bgrant0607 @timothysc

### CODE REVIEW

**Comment by davidopp** [comment]
This is a substantial change and I'm still not understanding your use case. Let's continue discussing the motivation on the issue thread before we take up a review of the proposal.

**Comment by timothysc** [comment]
Umm, imho gang scheduling should be outside of the core with the core enabling the ability to do gang scheduling.  e.g. (reservations, etc.)  

I think this may be a good topic for the SIG.

**Comment by bgrant0607** [comment]
I tend to agree with @timothysc.

More generally, we need to slow down on adding new APIs. We're working on some API extension mechanisms, which perhaps could be used. I don't foresee adding a new API for this directly at the current time, however.

We would like to understand the use case and ensure it's possible to build on top of Kubernetes, though.

**Comment by alex-mohr** [comment]
Closing as inactive.  Please re-open if you'd like to pursue this!

**Pull request closed without merging**
