### PR TITLE
Automated cherry pick of #16413 upstream release 1.1

### PR DESCRIPTION
**Pull request by davidopp**
Automated cherry pick of #16413 upstream release 1.1

@lavalamp

### CODE REVIEW

**Comment by davidopp** [comment]
@lavalamp This didn't work (see the test failure). I'm going to sleep now, could you prepare a cherrypick?

**Comment by lavalamp** [comment]
lgtm

**Comment by lavalamp** [comment]
@davidopp tests are very sad, though

**Comment by davidopp** [comment]
@lavalamp Yes, I know about the tests (see earlier comment) - could you redo this PR and make the tests work? I am juggling several others...

**Comment by lavalamp** [comment]
Remaking in #16599

**Comment by davidopp** [comment]
Thanks!

**Pull request closed without merging**
