### PR TITLE
Remove feature gate CustomResourceValidationExpressions

### PR DESCRIPTION
**Pull request by cici37**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Removed feature gate `CustomResourceValidationExpressions`.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
/assign @liggitt 
When you have time for api related approval. Thanks

**Comment by carlory** [comment]
@cici37 please update the website.

**Pull request merged**
