### PR TITLE
Cleanup netexec image and usage.

### PR DESCRIPTION
**Pull request by bprashanth**
Get tests onto 1.7 and fix a bug in netexec's http handler

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33006)

### CODE REVIEW

**Comment by freehan** [comment]
```
FAIL	k8s.io/kubernetes/federation/pkg/federation-controller/ingress	2.551s
```

got a unit test failure

**Comment by bprashanth** [comment]
@k8s-bot unit test this github issue: https://github.com/kubernetes/kubernetes/issues/32685

**Comment by MrHohn** [comment]
LGTM, though I don't have the privilege to apply label :(

**Comment by bprashanth** [comment]
cool thanks self applying

**Pull request merged**
