### PR TITLE
Allow an empty service selector

### PR DESCRIPTION
**Pull request by smarterclayton**
Services that wish to maintain their own endpoints can specify an empty pod selector.  The controller now ignores services without a selector when setting endpoints.  The kubernetes and kubernetes-ro services now have empty selectors to reflect this.

Fixes #2358

### CODE REVIEW

**Comment by thockin** [comment]
Was there a followup to this that actually implements the external service endpoints?

**Comment by smarterclayton** [comment]
What would the follow up be?  In this case you just post endpoints if you want them set.

**Comment by thockin** [comment]
oh, I thought maybe you were going to add a block to Service that had a
static endpoints list

**Comment by smarterclayton** [comment]
Might be valuable, just had not done it (nor the v1beta3 work around splitting out service "source" described above).

----- Original Message -----

**Pull request merged**
