### PR TITLE
Treat token which starts with space as invalid

### LINKED ISSUE #106142: kube-apiserver incorrectly parses tokens starting with ' '
### What happened?

kube-apiserver authenticated the token " TOKEN" as `system:anonymous` (note the leading space).

### What did you expect to happen?

kube-apiserver should reject the invalid authorization header.

The bearer token [RFC](https://datatracker.ietf.org/doc/html/rfc6750#section-2.1) specifies a single space between "Bearer" and the token value.

### How can we reproduce it (as minimally and precisely as possible)?

```
$ IP=<address of kube-apiserver>
$ curl -k https://IP -H "Authorization: Bearer asdf"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
$ curl -k https://IP -H "Authorization: Bearer  asdf"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.18-dispatcher", GitCommit:"de944d802c49735ad0f4bfe82ddfa19737ebe962", GitTreeState:"clean", BuildDate:"2021-05-13T17:51:55Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-gke.901", GitCommit:"db8463aecdfe0eb5d9067effa2fd5ab3ff7a988e", GitTreeState:"clean", BuildDate:"2021-08-04T23:27:42Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
```go
auth := strings.TrimSpace(req.Header.Get("Authorization"))  // trim spaces for 'Bearer token' string
if auth == "" {
    return nil, false, nil
}
parts := strings.SplitN(auth, " ", 3)
if len(parts) < 2 || strings.ToLower(parts[0]) != "bearer" {  
    return nil, false, nil
}

token := parts[1]  
// Empty bearer tokens aren't valid
if len(token) == 0 { // if len(parts) >= 2 and len(token) == 0, that means there has been two or more spaces between Bearer and token
    // invalid token found
}

```
Treat token which starts with space as invalid.

#### Which issue(s) this PR fixes:

Fixes #106142

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by enj** [comment]
1. Not sure if this actually addresses the issue (the issue would expect it to hard error, not ignore the extra space)
2. Not sure if the issue is valid as you could argue that the client did not try to authenticate by sending an invalid header (i.e. if a client sent `authorizations` as the header, we would ignore it, not error).

**Comment by SataQiu** [comment]
> 1. Not sure if this actually addresses the issue (the issue would expect it to hard error, not ignore the extra space)
> 2. Not sure if the issue is valid as you could argue that the client did not try to authenticate by sending an invalid header (i.e. if a client sent `authorizations` as the header, we would ignore it, not error).

Thanks @enj 
Ideally, I think we should match strictly under the `Authorization: Bearer OF MF_9.B5F-4.1JQM` format.
If this were new code, being strict would be fine.
However, we have already ignored the space after the token, and we can no longer simply use `strings.SplitN(auth, " ", 2)` to get token, it can break a request that included a trailing space after the token. FYI: https://github.com/kubernetes/kubernetes/pull/94803#discussion_r488729872
Do you think it makes sense to keep the space before the token？

**Comment by SataQiu** [comment]
> 1. Not sure if this actually addresses the issue (the issue would expect it to hard error, not ignore the extra space)
> 2. Not sure if the issue is valid as you could argue that the client did not try to authenticate by sending an invalid header (i.e. if a client sent `authorizations` as the header, we would ignore it, not error).

Thanks @enj 
I notice that we have already trimed the header value by `auth := strings.TrimSpace(req.Header.Get("Authorization"))`.
So `len(token) == 0` means that the token starts with spaces,  and it is not valid.

We can just fix this issue by:
```
index 292b4f57d07..ae74dfe149e 100644
--- a/staging/src/k8s.io/apiserver/pkg/authentication/request/bearertoken/bearertoken.go
+++ b/staging/src/k8s.io/apiserver/pkg/authentication/request/bearertoken/bearertoken.go
@@ -48,7 +48,7 @@ func (a *Authenticator) AuthenticateRequest(req *http.Request) (*authenticator.R
 
        // Empty bearer tokens aren't valid
        if len(token) == 0 {
-               return nil, false, nil
+               return nil, false, invalidToken
        }
 
        resp, ok, err := a.auth.AuthenticateToken(req.Context(), token)
```

The following use cases were tested:
```
# 1. no token specified
# curl -k https://127.0.0.1:6443 -H "Authorization: Bearer"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
---
# 2. no token specified (one space after Bearer)
# curl -k https://127.0.0.1:6443 -H "Authorization: Bearer "
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
---
# 3. no token specified (tow or more spaces after Bearer)
# curl -k https://127.0.0.1:6443 -H "Authorization: Bearer  "
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
---
# 4. token specified (one space between Bearer and token)
# curl -k https://127.0.0.1:6443 -H "Authorization: Bearer abc"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
---
# 5. token specified (tow or more spaces between Bearer and token)
# curl -k https://127.0.0.1:6443 -H "Authorization: Bearer  abc"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}
```

**Comment by enj** [comment]
I am skeptical of this change, per my last comment.

I could by an argument that the presence of any authorization header signals an authentication attempt, but that should probably be handled at a higher layer.

If we so make a change, I would expect associated integration tests to assert the exact behavior we expect.

**Pull request closed without merging**
