### PR TITLE
Add atiratree as sig-apps reviewer

### PR DESCRIPTION
**Pull request by soltysh**
#### What type of PR is this?
/kind documentation
/sig apps

#### What this PR does / why we need it:
Filip has been a member of kubernetes org for [over a year](https://github.com/kubernetes/org/issues/3026) now,  but he has been actively working with sig-apps for longer than that. Initially joining our bi-weekly calls, but over time sharing opinions, reviewing and finally contributing code. By now he authored [more than 20 PRs](https://github.com/kubernetes/kubernetes/pulls/atiratree), reviewed [more than 30 PRs](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+reviewed-by%3Aatiratree+) across majority of the controllers (replica set, hpa, cronjob, daemonset, statefulset, controller revision), out of which [more than 10](https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+assignee%3Aatiratree+) he was acting as the primary reviewer. Recently he has been responsible for delivering [PodHealthyPolicy for PodDisruptionBudget feature](https://github.com/kubernetes/enhancements/issues/3017). Finally, he recently graduated from [sig-apps mentoring](https://github.com/kubernetes/community/issues/6665). 

With all of the above, I can confidently promote Filip to sig-apps reviewer. 

#### Special notes for your reviewer:
/assign @janetkuo @kow3ns @dims 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by soltysh** [comment]
/hold
for @dims approval

**Comment by aojea** [comment]
+1

**Comment by dims** [comment]
/approve
/lgtm

@atiratree totally new ball game being a reviewer! :)

**Comment by atiratree** [comment]
Thanks a lot everyone! :tada:

**Pull request merged**
