### PR TITLE
Cleanup: fix linting failures for pkg/{kubectl, kubelet} and related packages

### PR DESCRIPTION
**Pull request by ESWZY**
**What type of PR is this?**

/kind cleanup

**What this PR does?**

Fix golint failures for package `pkg/kubectl`, `pkg/kubelet` and related packages.

**Which issue this PR fixes?**

Ref: #68026 [Fix golint failures](https://github.com/kubernetes/kubernetes/issues/68026)

**Special notes for your reviewer**:

Following is the failure kinds I fixed. Because I don't have the right to interpret the code, I skiped some comment and type name golint failures. If you have some good idea, please tell me. Glad to help. 🥰

Additionally, you can inspect the changes of sub-package by corresponding commit.

- Linting failures fixed:

```
XXX.go:X:2: struct field CpuXxx should be CPUXxx
XXX.go:X:3: var xxxJson should be xxxJSON
XXX.go:X:8: const xxxId should be xxxID
xxx_xxx.go:X:1: don't use an underscore in package name
XXX.go:X:2: don't use underscores in Go names; var xxx_xxx should be xxxXxx
XXX.go:X:30: error strings should not be capitalized or end with punctuation or a newline
```

- Linting failures partly fixed:

```
XXX.go:X:2: comment on exported XXX should be of the form "XXX ..."
XXX.go:X:1: exported XXX should have comment or be unexported
XXX.go:X:6: type name will be used as xxx.XxxID by other packages, and that stutters; consider calling this ID
XXX.go:X:1: package comment should be of the form "Package types ..."
XXX.go:295:9: if block ends with a return statement, so drop this else and outdent its block
```

- Linting failures not fixed:

```
XXX.go:X:42: exported func XXX returns unexported type *XX.xXX which can be annoying to use
pkg\kubelet\dockershim\network\plugins.go:49:2: don't use ALL_CAPS in Go names; use CamelCase
XXX.go:X:1: package comment is detached; there should be no blank lines between it and the package statement
```

The involved sub packages are:

- Packages removed from [.golint_failures list](https://github.com/kubernetes/kubernetes/blob/master/hack/.golint_failures):

```
pkg/kubectl/cmd/convert	
pkg/kubelet/apis/config/v1beta1
pkg/kubelet/cri/remote
pkg/kubelet/dockershim/network/hostport/testing	
pkg/kubelet/dockershim/network/kubenet
```

- Packages modified:

```
pkg/kubelet/cm
pkg/kubelet/container/testing
pkg/kubelet/dockershim/libdocker
pkg/kubelet/dockershim/network
pkg/kubelet/dockershim/network/cni/testing
pkg/kubelet/dockershim/network/hostport
pkg/kubelet/dockershim/network/testing
pkg/kubelet/pod/testing
pkg/kubelet/preemption
pkg/kubelet/types
```

- Packages under `pkg/kubelet/` but not modified:

```
pkg/kubelet/container
pkg/kubelet/dockershim
pkg/kubelet/pluginmanager/pluginwatcher
pkg/kubelet/stats
pkg/kubelet/sysctl
```

Thanks for your review! If you have any reply, I will respond as soon as possible!

### CODE REVIEW

**Comment by ESWZY** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).

**Comment by ESWZY** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

/retest

**Review by mattjmcnaughton — CHANGES_REQUESTED** [review]
Thanks for your pr @ESWZY !

You fixed a lot of linting failures in this pr (which is great), but do think that the review process will be faster if we split this PR into multiple smaller PRs.

Would you be open to closing this PR and splitting it up into as many small, independent pull requests as possible? Happy to chat more around how to do that if it could be helpful :)

I think doing so will help us review it quickly and get these fixes merged. Thanks!

**Comment by ESWZY** [comment]
> Thanks for your pr @ESWZY !
> 
> You fixed a lot of linting failures in this pr (which is great), but do think that the review process will be faster if we split this PR into multiple smaller PRs.
> 
> Would you be open to closing this PR and splitting it up into as many small, independent pull requests as possible? Happy to chat more around how to do that if it could be helpful :)
> 
> I think doing so will help us review it quickly and get these fixes merged. Thanks!

Thanks for your detailed reply! 

That's a good idea, I will try my best!

**Comment by ESWZY** [comment]
> Thanks for your pr @ESWZY !
> 
> You fixed a lot of linting failures in this pr (which is great), but do think that the review process will be faster if we split this PR into multiple smaller PRs.
> 
> Would you be open to closing this PR and splitting it up into as many small, independent pull requests as possible? Happy to chat more around how to do that if it could be helpful :)
> 
> I think doing so will help us review it quickly and get these fixes merged. Thanks!

I am worried about whether submitting too many PRs at one time will cause trouble to the community.

**Comment by mattjmcnaughton** [comment]
On Sun, Jul 19, 2020 at 11:01:23AM -0700, Woa wrote:
> > Thanks for your pr @ESWZY !
> > 
> > You fixed a lot of linting failures in this pr (which is great), but do think that the review process will be faster if we split this PR into multiple smaller PRs.
> > 
> > Would you be open to closing this PR and splitting it up into as many small, independent pull requests as possible? Happy to chat more around how to do that if it could be helpful :)
> > 
> > I think doing so will help us review it quickly and get these fixes merged. Thanks!
> 
> Thanks for your detailed reply! 
> 
> That's a good idea, I will try my best!
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/93222#issuecomment-660684111

Wonderful, thank you!

**Pull request closed without merging**
