### PR TITLE
Format apiserver options

### PR DESCRIPTION
**Pull request by olegshaldybin**
Trivial change, code formatting only: it was hard to read long lines, and my editor was really slow when scrolling through them.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
LGTM, thanks!

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by olegshaldybin** [comment]
@nikhiljindal Rebased the change, PTAL.

**Comment by olegshaldybin** [comment]
@nikhiljindal Is there a way to re-trigger tests other than rebasing (as rebasing would make it lose an lgtm label)?

**Comment by nikhiljindal** [comment]
@k8s-bot node e2e test this issue: https://github.com/kubernetes/kubernetes/issues/28100

**Comment by nikhiljindal** [comment]
sigh, another flake.
@k8s-bot e2e test this issue: https://github.com/kubernetes/kubernetes/issues/28188

**Comment by nikhiljindal** [comment]
ok to test

@k8s-bot e2e test this issue: #28188

**Comment by olegshaldybin** [comment]
It seems to be hitting flakes and build errors a lot.

**Comment by olegshaldybin** [comment]
@nikhiljindal Can you re-trigger tests please?

**Comment by nikhiljindal** [comment]
@olegshaldybin You can trigger the tests by typing the following:

@k8s-bot e2e test this issue: #IGNORE

Its better to use the issue number corresponding to the flake, if you know it. #IGNORE is the fallback.

**Pull request merged**
