### PR TITLE
Supplement unit test for kubectl annotate

### PR DESCRIPTION
**Pull request by YuxiJin-tobeyjin**
**What this PR does / why we need it**:
Supplement unit test for kubectl annotate
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/ok-to-test

@YuxiJin-tobeyjin Can you please rebase?

**Comment by YuxiJin-tobeyjin** [comment]
ping @janetkuo  PTAL
Many thanks.

**Comment by YuxiJin-tobeyjin** [comment]
Rebase seems can not fix the test fail, I will close and open a new one.

**Pull request closed without merging**
