### PR TITLE
allocator ETCD: remove unused Refresh()

### PR DESCRIPTION
**Pull request by hongchaodeng**

### CODE REVIEW

**Comment by hongchaodeng** [comment]
@xiang90

**Comment by hongchaodeng** [comment]
@justinsb 
Can you help review this too and apply the label?

**Comment by smarterclayton** [comment]
Is there a particular reason to be removing this, other than it is unused at the current time?

**Comment by hongchaodeng** [comment]
Have you heard about the notorious [openssl PRNG bug](https://www.schneier.com/blog/archives/2008/05/random_number_b.html)? The openssl community was so broken that someone threw in unuseful code to make it compiled. After two years, the vulnerability was found and it caused massive worldwide regeneration of keys.

> other than it is unused at the current time?

I'm not sure if I understand "current time". Is this something gonna be used soon? I have searched through the git history and it looks like this was not used at the beginning. ref: https://github.com/kubernetes/kubernetes/pull/7704

**Comment by smarterclayton** [comment]
We had discussed using it, but seeing as we haven't had the need in the last year (and we're unlikely to change services behavior until V2) I'm fine with removing it.

**Comment by ixdy** [comment]
@k8s-bot test this please, issue #27462

**Pull request merged**
