### PR TITLE
Automated cherry pick of #34524

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #34524 on release-1.3.
#34524: Test x509 intermediates correctly

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35212)

### CODE REVIEW

**Comment by roberthbailey** [comment]
@erictune @jessfraz FYI

**Comment by fabioy** [comment]
@k8s-bot verify test this

**Comment by fabioy** [comment]
@liggitt Sorry, the boilerplace verification is failing. I think there may have been a boilerplate change between 1.4 and 1.3. Can you fix that (while I chase down the other errors)? Thanks.

**Comment by liggitt** [comment]
fixed boilerplate

**Pull request merged**
