### PR TITLE
Add a kubectl 'import' command for imported services

### PR DESCRIPTION
**Pull request by brendandburns**
This PR adds a command to kubectl for easily importing 'headless' services into a cluster.

Usage examples:

```
# Create a Service for an existing MySQL that is serving at 24.1.2.3.
$ kubectl import 24.1.2.3 mysql --ports=3306

# Create a Service for an existing MySQL that is serving at 24.1.2.3, create the Service/Endpoints in 'my-namespace'.
$ kubectl import 24.1.2.3 mysql --ports=3306 --namespace=my-namespace


# Create a service for an existing Cassandra cluster that has three nodes at 10.0.0.1, 10.0.0.2, & 10.0.0.3
$ kubectl import 10.0.0.1 10.0.0.2 10.0.0.3 cassandra --ports=9042,9160
```

@jlowdermilk @deads2k 

I know it is missing unit tests, I'll add those once the rest LG.

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/19509)

### CODE REVIEW

**Comment by thockin** [comment]
I don't think 'import' is the right name for this - I would *never* guess that this is what import means.  What about `create`.

To riff on your examples:

```
# Create a headless service "mysql" pointing to an external IP
$ kubectl create service mysql --headless --port 3306 --endpoints=24.1.2.3

# Create a headless service "cassandra" pointing to a set of external IPs
$ kubectl create service cassandra --headless --port 9042 --port 9160 --endpoints=10.0.0.1,10.0.0.2,10.0.0.3

# Create a "normal" service "foobar" pointing to an external IP
$ kubectl create service mysql --port 3306 --endpoints=24.1.2.3
```

Issues: I don't think we currently validate that you don't remap ports or other nonsense things with headless.  We need a way to specify port names and protocols, and if we allow non-headless then also target-ports.  If we want to allow multiple ports we need flag syntax once and for all (I like docker's way of re-specifying a flag over again).  Same for endpoints and ports.

**Comment by brendandburns** [comment]
@thockin hrm, I feel like "import" is right.  You have this external service (e.g. MySQL) running at some random IP address and you want to "import" it into your cluster.

I see it as the opposite of 'expose'

It's analogous to `kubectl run ...` in my mind.

`kubectl import-service ...`?

`kubectl import-existing ...`?

`kubectl external-service ...`?

**Comment by thockin** [comment]
I think `kubectl create service` is purpose built for nesting new kinds of
semi-generic construction operations.  I don't think this is such a common
operation that it demands a top-level command, nor is it generator-based
(making it even more abstract, like expose).  Also, `create resource` is
being used for other in this vein, so consistency is a win, for me.

**Comment by deads2k** [comment]
I prefer the idea of `kubectl create service` over `kubectl import`.  I would also say that I like the idea of `kubectl create headless-service` or something to more specifically limit flag combinations even better.

**Comment by kargakis** [comment]
cc @kubernetes/kubectl

**Comment by smarterclayton** [comment]
Yeah, I'd like to reserve import for importing things from Compose / other cluster management systems.  We only have a limited number of "good" verbs.  I prefer create service as well.

**Comment by deads2k** [comment]
> Yeah, I'd like to reserve import for importing things from Compose / other cluster management systems. We only have a limited number of "good" verbs. I prefer create service as well.

How do you feel about having a command specifically focused on different sorts of services, similar to the way we handled different sorts of secrets.  That allows for distinct flagsets that really help to guide a user.

**Comment by smarterclayton** [comment]
I thought we agreed somewhere to have kubectl create dockercfg-secret or
something?  This would be analogous to me

**Comment by brendandburns** [comment]
Ok, I will switch this over as `kubectl create imported-service ...`?  `headless` is meaningless to external users.

**Comment by smarterclayton** [comment]
I'm wondering if we should stop calling them headless in general, and use
either external service or imported service.

**Comment by brendandburns** [comment]
@smarterclayton does that mean `imported-service` is ok with you as a term?

**Comment by brendandburns** [comment]
@smarterclayton switched to:

`kubectl create imported-service ...`

ptal.

thanks
--brendan

**Comment by kargakis** [comment]
Let's implement our generators from now on based on what was introduced in https://github.com/kubernetes/kubernetes/pull/16028 (StructuredGenerator pattern)

**Comment by deads2k** [comment]
> Let's implement our generators from now on based on what was introduced in #16028 (StructuredGenerator pattern)

I agree.  The strict specificity for what you're trying to build makes it easier to read and re-use.

**Comment by bgrant0607** [comment]
This has nothing to do with headless services.

**Comment by bgrant0607** [comment]
cc @kubernetes/kubectl

**Comment by bgrant0607** [comment]
We don't have any other examples of `kubectl create` being applied to something that isn't an actual resource type. The pattern we adopted with `kubectl create secret` was to create subtypes.
cc @derekwaynecarr

**Comment by bgrant0607** [comment]
Example:
https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_create_secret_docker-registry.md

**Comment by kargakis** [comment]
> We don't have any other examples of kubectl create being applied to something that isn't an actual resource type. The pattern we adopted with kubectl create secret was to create subtypes.

Agreed. I would vote for kubectl create service and a subcommand for external services

**Comment by derekwaynecarr** [comment]
+1 on `kubectl create secret`

**Comment by bgrant0607** [comment]
Regarding terminology:

*import*: Import sounds like the opposite of export, which is a thing in kubectl and the API already. Users have requested a bulk import mechanism. #21582  "Imported service" is the term I have been using for services without selectors (http://kubernetes.io/docs/user-guide/services/#services-without-selectors), but that term is not used in documentation that I'm aware of.

*Headless* services are something totally different -- services without VIPs. This term IS documented:
http://kubernetes.io/docs/user-guide/services/#headless-services
I coined the term (#1607) and it never referred to services without selectors.

We've also discussed allowing services to resolve to CNAMEs: #13748, which is fairly similar. I think both services without selectors, which map to IP addresses, and services mapping to CNAMEs could be thought of as service aliases (though ALIAS has an existing meaning in DNS). 

```
kubectl alias service mysql --address=24.1.2.3 --port=3306
```

The presence of the `service` resource type makes this possible to extend to other resource types later. kubectl can accept multiple arguments of the same type, so additional address and port flags could be specified. This would be in keeping with conventions of other commands.

I don't want to introduce `create` subcommands for things that aren't actual resource types, like `service-alias` or `imported-service`. If we did want to use `create`, it would have to be `kubectl create service <type> <service-name> <flags>`.

**Comment by rata** [comment]
@bgrant0607 alias seems way better IMHO. And as you say, it makes sense to create a service that will be a CNAME too this way.

Do you have any thoughts on how will this can be reflected in the service api/yaml? Or just nothing for now, have the endpoints manually and CNAMEs will be discussed later? (because for service using only IP addresses that would be enough)

**Comment by bgrant0607** [comment]
@rata I don't think we're ready to make an API change yet.

**Comment by bgrant0607** [comment]
@brendandburns Please close this if you don't plan to finish it.

**Comment by rata** [comment]
@bgrant0607 is there consensus on what's needed to finish this?

I maybe can work to finish this, especially if there is consensus on how to do the CNAME dns for services like AWS RDS or almost anything hosted on amazon :-)

**Comment by thockin** [comment]
@rata I know I am delinquent in providing you enough feedback to make progress on this front, and I am deeply sorry.  I will try to give it some time very soon, now that 1.3 is more or less out the door.  We have been trying to scale the team, and we've had some success, so hopefully I will get more time soon. :)

**Comment by thockin** [comment]
@bgrant0607 `kubectl alias service` sounds like it is something you do with an extant Service, which is NOT what imported Services are about (I know you know, but for the record :).  I still think `kubectl create service ...` is the right construct.

With regards to name (oh boy), again for the record, we have a couple mostly-orthogonal axes.

x | selector | clusterIP | type | endpoints | called
-- | ----------- | ----------- | ------ | ------------- | -------
1 | user-defined | auto-assigned | any | auto-assigned from selector | a "normal" service
2 | user-defined | user-defined | any | auto-assigned from selector | a "normal" service with a manual IP assigned
3 | user-defined | "None" | "ClusterIP" | auto-assigned from selector | a "headless" service
4 | user-defined | "None" | "NodePort" or "LoadBalancer" | NA | invalid
5 | none | auto-assigned | any | user-assigned | an "external" service
6 | none | user-defined | any | auto-assigned from selector | an "external" service with a manual IP assigned
7 | none | "None" | "ClusterIP" | user-assigned | an "external headless" service
8 | none | "None" | "NodePort" or "LoadBalancer" | NA | invalid

We have not yet really defined how CNAME fits in here.

We can argue about "headless" being too cute, but it sticks.  "External" is what we're arguing about here, I think.  "Imported" is OK as long as it is in the context of a Service.  "Alias" is OK, but less obvious.  "Injected", as in dependency injection?  "Ambassadored"?  "Gatewayed"?  

To me, this leads to:

```
kubectl create service my-normal --selector=<selector-spec> [--cluster-ip=<ip-address>] [--type=<service-type>]

kubectl create service my-headless --selector=<selector-spec> --cluster-ip=None [--type="ClusterIP"]

kubectl create service my-external --selector="" [--cluster-ip=<ip-address>] [--type=<service-type>]

kubectl create service my-external-headless --selector="" --cluster-ip=None [--type="ClusterIP"]
```

Note that I did not try to promote "headless" or "external" or anything else up to first- or second- order keywords.  We have a matrix of parameters, most (but not all) of which are reasonably well understood.  Naming is hard, let's not make it harder.

**Comment by bgrant0607** [comment]
@thockin I'm fine with `create service`

**Comment by deads2k** [comment]
> @thockin I'm fine with create service

There is a pull in progress adding some `kubectl create service` commands: https://github.com/kubernetes/kubernetes/pull/27109

**Comment by brendandburns** [comment]
@thockin `create service --selector=""` is bad UX, since you are embuing the empty string with some sort of magical power that will be extremely opaque. (unless you're assuming that empty string is default and just being explicit in the example for clarity)

I still don't think that `create` is the right verb.  This is how people bring some external thing into their Kubernetes cluster (hence `import`) *sigh*

**Comment by smarterclayton** [comment]
So I agree with import being a way to bring things into the cluster, but it
needs to be a nested sub command, and space really has to be left for new
imports to be created.   `kubectl import external-service` is probably the
shortest name I can think of, and it's probably not totally accurate.

I generally agree that --selector="" is bad UX, but if the outcome is a
single arg to replace it (like --external-name=foo) I don't think that's
enough justification for a whole new command by itself.  And we'd probably
still want it to be possible to be created via `kubectl create service` for
other reasons.

**Pull request closed without merging**
