### PR TITLE
Fix federation e2e tests by correctly managing cluster clients

### PR DESCRIPTION
**Pull request by ghost**
1. The main fix: Correct overall BeforeEach() to create a new set of cluster clients, rather than just append to the set created by all previous tests.  This was screwing up a lot of stuff in difficult to diagnose ways.
2. Add lots of debug logging.
3. Be better about cleaning up after each test.

```
SUCCESS! -- 6 Passed | 0 Failed :-)
```

cc @nikhiljindal @madhusudancs @mfanjie @colhom FYI

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@nikhiljindal FYI after rebasing, it looks like this probably ran into "federation: Upgrading the groupversion to v1beta1 #28186".  It would be great if you could take a look when you get in in the morning.

**Comment by quinton-hoole** [comment]
Come to think of it,I was running a new test binary against an old cluster, so that's probably the problem.  I'll rebuild and recheck in the morning.

**Comment by mml** [comment]
LGTM.  It is a bad smell that it was so easy to do this and not notice in any way until we added the debug logging.

Factoring this stuff into the framework will help, but there is probably also a rule of thumb that modifying shared state variables is error-prone, and you need to think about if/how to reset them between runs, not just how to "set things up".

**Comment by quinton-hoole** [comment]
@mml, yes, absolutely.  A few assertions along the way (probably in BeforeEach and AfterEach) would also help.  In this case the number of API clients was not equal to the number of clusters.

**Pull request merged**
