### PR TITLE
update go version to 1.9.4

### PR DESCRIPTION
**Pull request by oilbeater**
**What this PR does / why we need it**:
update golang version to latest

**Release note**:
```none

```

### CODE REVIEW

**Comment by cblecker** [comment]
We still need go1.9.4 to be supported in the bazel toolchains (https://github.com/bazelbuild/rules_go/pull/1311). Once that is merged, we can bump the WORKSPACE rules_go (https://github.com/kubernetes/kubernetes/pull/59012/files#diff-7f1c98c90062b56dffdcdd67c36a0e79)

**Comment by oilbeater** [comment]
@cblecker update the bazel ,but the build seems still failed

**Comment by cblecker** [comment]
@oilbeater Can you try rebasing this? The rules should now be updated to a version that is compatible with go1.9.4

**Comment by oilbeater** [comment]
seems like the k8s.gcr.io/kube-cross:v1.9.4-1 cannot be build

**Comment by cblecker** [comment]
/assign @ixdy 
/hold
Over to you for image pushes, @ixdy :)

**Comment by ixdy** [comment]
how strongly do we feel like we need this? the only fix in go1.9.4 is around go get, so that shouldn't affect our build.

**Pull request closed without merging**
