### PR TITLE
Automated cherry pick of #32718

### PR DESCRIPTION
**Pull request by caesarxuchao**
Cherry pick of #32718 on release-1.4.

``` release-note
Make the informer library available for the go client library.
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33699)

### CODE REVIEW

**Comment by caesarxuchao** [comment]
People want it to be back-ported to client-go/1.4, which gets its contents from the release-1.4 branch, so I need to cherry-pick #32718 first.

**Comment by caesarxuchao** [comment]
@mikedanese could you help review it?

**Comment by lavalamp** [comment]
Breaking the interface means we need to bump the major version, to 2.0.0...

**Comment by lavalamp** [comment]
This is a nice-to-have one. @jessfraz 's call.

**Comment by jessfraz** [comment]
ooo that is kinda a large patch, it looks like it also includes a refactor? Is it fixing a bug too?

**Comment by lavalamp** [comment]
@mikedanese can say more-- I thought this was just a movement + fix up
import paths.

**Comment by mikedanese** [comment]
This contains no logic modification. It's a large patch because transplants a commonly used and highly useful utility. We want to be more commonly used so we want to include it in the client repo. Cherry pick LGTM

**Pull request merged**
