### PR TITLE
cluster/eks: initial commit

### LINKED ISSUE #12: kubernetes/kubernetes.cluster/kubectl.sh fails
```
W1121 19:22:20.855] 2018/11/21 19:22:20 process.go:155: Step '/tmp/aws-k8s-tester767933017 eks —path=/tmp/aws-k8s-tester510470242 check cluster' finished in 6.625144142s
W1121 19:22:20.904] 2018/11/21 19:22:20 process.go:153: Running: ./cluster/kubectl.sh —match-server-version=false version
W1121 19:22:21.341] The connection to the server localhost:8080 was refused - did you specify the right host or port?
W1121 19:22:21.345] 2018/11/21 19:22:21 process.go:155: Step './cluster/kubectl.sh —match-server-version=false version' finished in 440.928862ms
W1121 19:22:21.345] 2018/11/21 19:22:21 e2e.go:341: Failed to reach api. Sleeping for 10 seconds before retrying…
W1121 19:22:31.345] 2018/11/21 19:22:31 process.go:153: Running: ./cluster/kubectl.sh —match-server-version=false version
W1121 19:22:31.438] The connection to the server localhost:8080 was refused - did you specify the right host or port?
W1121 19:22:31.441] 2018/11/21 19:22:31 process.go:155: Step './cluster/kubectl.sh —match-server-version=false version' finished in 96.048207ms
W1121 19:22:31.441] 2018/11/21 19:22:31 e2e.go:341: Failed to reach api. Sleeping for 10 seconds before retrying…
W1121 19:22:41.442] 2018/11/21 19:22:41 process.go:153: Running: ./cluster/kubectl.sh —match-server-version=false version
W1121 19:22:41.539] The connection to the server localhost:8080 was refused - did you specify the right host or port?
W1121 19:22:41.542] 2018/11/21 19:22:41 process.go:155: Step './cluster/kubectl.sh —match-server-version=false version' finished in 100.389731ms
W1121 19:22:41.542] 2018/11/21 19:22:41 e2e.go:341: Failed to reach api. Sleeping for 10 seconds before retrying…
W1121 19:22:51.542] 2018/11/21 19:22:51 process.go:153: Running: ./cluster/kubectl.sh —match-server-version=false version
W1121 19:22:51.638] The connection to the server localhost:8080 was refused - did you specify the right host or port?
W1121 19:22:51.640] 2018/11/21 19:22:51 process.go:155: Step './cluster/kubectl.sh —match-server-version=false version' finished in 97.6761ms
W1121 19:22:51.640] 2018/11/21 19:22:51 e2e.go:341: Failed to reach api. Sleeping for 10 seconds before retrying…
```

### PR DESCRIPTION
**Pull request by gyuho**
Add EKS e2e script.

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Kubernetes e2e tests require each provider to implement its own util script, and EKS does not have one (fix https://github.com/aws/aws-k8s-tester/issues/12).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Trying to fix https://github.com/aws/aws-k8s-tester/issues/12.

**Special notes for your reviewer**:

@krzyzacy @BenTheElder 

ref. https://github.com/kubernetes/test-infra/issues/9814

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gyuho** [comment]
To give more background on this PR, we've recently added EKS test plugin to kubetest, but haven't been able to get the kubectl to work. And find out it was calling `cluster/kubectl.sh`, which calls

https://github.com/kubernetes/kubernetes/blob/2b0212de9cdf4c2cc8d5619dcc26c1c0b8917203/cluster/kubectl.sh#L34

Which calls

https://github.com/kubernetes/kubernetes/blob/2b0212de9cdf4c2cc8d5619dcc26c1c0b8917203/cluster/kube-util.sh#L39

I hope having this script helps us debug the `kubectl` failures.

Thanks!

**Comment by mikedanese** [comment]
Can kubetest call kubectl directly? This seems like a pretty round about way of fixing this. Note that cluster/kubectl.sh has been deprecated for 4 years https://github.com/kubernetes/kubernetes/pull/9342 .

Please also see the deprecation notice in https://github.com/kubernetes/kubernetes/blob/master/cluster/README.md and https://github.com/kubernetes/kubernetes/issues/49213.

How does this work for GKE?

**Comment by krzyzacy** [comment]
ouch
/shrug

by default kubectl is from the image (which is from gcloud sdk), and cluster/kubectl.sh is from the extracted k8s tarball and we were not mucking with PATH :-\

We probably can change how skew tests work, cc @pwittrock @mengqiy @fejta on thoughts

**Comment by gyuho** [comment]
@mikedanese @krzyzacy 

> Can kubetest call kubectl directly?

That would make things easier for us as provider plugin maintainers.

> cluster/kubectl.sh is from the extracted k8s tarball and we were not mucking with PATH

Yeah, I would like to specify the kubectl path and all the flags (e.g. `--kubeconfig`). Seems like setting  `KUBECTL_PATH` inside test plugin does not have any effects.

**Comment by gyuho** [comment]
Found out kubetest is setting `KUBECTL=./cluster/kubectl.sh KUBE_CONFIG_FILE=config-test.sh`. Let me try to overwrite this envs inside our plugin.

**Comment by gyuho** [comment]
Sorry for spamming. There are so many unknowns for a new kubetest plugin provider.

```
I1121 23:23:41.131] [91m[1mFailure [0.000 seconds][0m
I1121 23:23:41.131] [91m[1m[BeforeSuite] BeforeSuite [0m
I1121 23:23:41.131] [37m_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:67[0m
I1121 23:23:41.131] 
I1121 23:23:41.132]   [91mNode 1 disappeared before completing BeforeSuite[0m
I1121 23:23:41.132] 
I1121 23:23:41.132]   _output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:67
I1121 23:23:41.132] [90m------------------------------[0m
I1121 23:23:41.132] Nov 21 23:23:41.098: INFO: Running AfterSuite actions on all nodes
I1121 23:23:41.132] 
I1121 23:23:42.107] 
I1121 23:23:42.108] 	 -------------------------------------------------------------------
I1121 23:23:42.108] 	|                                                                   |
I1121 23:23:42.108] 	|  Ginkgo timed out waiting for all parallel nodes to report back!  |
I1121 23:23:42.108] 	|                                                                   |
I1121 23:23:42.108] 	 -------------------------------------------------------------------
I1121 23:23:42.108] 
I1121 23:23:42.109] [1] W1121 23:23:40.823290    1313 test_context.go:385] Unknown provider "eks", proceeding as for --provider=skeleton.
I1121 23:23:42.109] [1] I1121 23:23:40.823472    1313 e2e.go:224] Starting e2e run "77a6749e-ede4-11e8-9c49-0a580a3c191f" on Ginkgo node 1
I1121 23:23:42.109] [2] W1121 23:23:40.651025    1308 test_context.go:385] Unknown provider "eks", proceeding as for --provider=skeleton.
I1121 23:23:42.109] [2] I1121 23:23:40.651217    1308 e2e.go:224] Starting e2e run "778e3684-ede4-11e8-bbfc-0a580a3c191f" on Ginkgo node 2
```

Error from 

https://github.com/kubernetes/kubernetes/blob/2b0212de9cdf4c2cc8d5619dcc26c1c0b8917203/test/e2e/framework/test_context.go#L371-L385

That requires 

https://github.com/kubernetes/kubernetes/blob/2b0212de9cdf4c2cc8d5619dcc26c1c0b8917203/test/e2e/framework/provider.go#L79-L99

Do we still require `ProviderInterface` for Kubernetes/Kubernetes e2e tests? I was expecting that as long as we provide kubetest deployer interface, everything would work. Do we need implement this? If yes, is there any reference implementation that I can follow?

Thanks.

**Comment by BenTheElder** [comment]
I agree with @mikedanese that we should really stop using and adding to cluster/ :/ we should fix kubetest instead.


`ProviderInterface` is for storage mainly IIRC, and actually something recent-ish? cc @pohly 
For say, conformance testing we do not need this. Some storage tests might, but many of those also do something like skip the test if not on GCP... :grimacing:

**Comment by gyuho** [comment]
Yeah `ProviderInterface` has some implementations in https://github.com/kubernetes/kubernetes/tree/master/test/e2e/framework/providers, but I might wait until cloud provider moves out-of-tree. Running conformance tests should be good enough for us now.

> stop using and adding to cluster/ :/ we should fix kubetest instead.

Sounds good.

Please let me know if you need any help! Looks like they are hardcoded in https://github.com/kubernetes/test-infra/blob/master/kubetest/e2e.go#L52.

**Comment by BenTheElder** [comment]
Help would definitely be appreciated! I'm still trying to help review work here but not really working on kubetest these days, mostly [kind](https://sigs.k8s.io/kind). We definitely want to get this working nicely with out of tree and without the cluster/* scripts as much as possible ...

OTOH, @krzyzacy and I have some rough plans for a kubetest rewrite that would avoid these from the start, we might get to that in the spring (?) ...

**Comment by gyuho** [comment]
@BenTheElder Yes, I will create a proposing PR to allow provider to pass kubectl paths, in kubetest package. I think we can make changes in `kubectl/main.go/run`. Thanks!

**Pull request closed without merging**
