### PR TITLE
1.20 Major Themes Changelog Restructure

### PR DESCRIPTION
**Pull request by wilsonehusin**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:
The release notes for 1.20 had duplicated lines which looks confusing. This PR removes the duplicated lines.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve
/priority critical-urgent
/milestone v1.20

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
