### PR TITLE
Automated cherry pick of #62649: Ensure service routing resolves kubernetes.default.svc

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #62649 on release-1.10.

#62649: Ensure service routing resolves kubernetes.default.svc

### CODE REVIEW

**Comment by jennybuckley** [comment]
cc @MaciekPytel

**Comment by MaciekPytel** [comment]
The discussion seems to be still ongoing on the base PR. I'll wait with approving cherry-pick until base PR is finalized and merged.

**Comment by liggitt** [comment]
fixed up server wiring in the integration test to match 1.10-era startup:

```difff
--- a/test/integration/examples/setup_test.go
+++ b/test/integration/examples/setup_test.go
@@ -97,21 +97,17 @@ func startTestServer(t *testing.T, stopCh <-chan struct{}, setup TestServerSetup
        kubeAPIServerOptions.Authentication.RequestHeader.AllowedNames = []string{"kube-aggregator"}
        kubeAPIServerOptions.Authentication.RequestHeader.ClientCAFile = proxyCACertFile.Name()
        kubeAPIServerOptions.Authentication.ClientCert.ClientCA = clientCACertFile.Name()
-       kubeAPIServerOptions.Authorization.Modes = []string{"Node", "RBAC"}
+       kubeAPIServerOptions.Authorization.Mode = "Node,RBAC"
 
        if setup.ModifyServerRunOptions != nil {
                setup.ModifyServerRunOptions(kubeAPIServerOptions)
        }
 
-       completedOptions, err := app.Complete(kubeAPIServerOptions)
+       tunneler, proxyTransport, err := app.CreateNodeDialer(kubeAPIServerOptions)
        if err != nil {
                t.Fatal(err)
        }
-       tunneler, proxyTransport, err := app.CreateNodeDialer(completedOptions)
-       if err != nil {
-               t.Fatal(err)
-       }
-       kubeAPIServerConfig, sharedInformers, versionedInformers, _, _, _, err := app.CreateKubeAPIServerConfig(completedOptions, tunneler, proxyTransport)
+       kubeAPIServerConfig, sharedInformers, versionedInformers, _, _, _, err := app.CreateKubeAPIServerConfig(kubeAPIServerOptions, tunneler, proxyTransport)
        if err != nil {
                t.Fatal(err)
        }
@@ -119,7 +115,7 @@ func startTestServer(t *testing.T, stopCh <-chan struct{}, setup TestServerSetup
        if setup.ModifyServerConfig != nil {
                setup.ModifyServerConfig(kubeAPIServerConfig)
        }
-       kubeAPIServer, err := app.CreateKubeAPIServer(kubeAPIServerConfig, genericapiserver.NewEmptyDelegate(), sharedInformers, versionedInformers)
+       kubeAPIServer, err := app.CreateKubeAPIServer(kubeAPIServerConfig, genericapiserver.EmptyDelegate, sharedInformers, versionedInformers)
        if err != nil {
                t.Fatal(err)
        }
```

**Comment by deads2k** [comment]
diff lgtm

/lgtm

**Pull request merged**
