### PR TITLE
make the addons docker registry configurable

### PR DESCRIPTION
**Pull request by kwmonroe**
**What this PR does / why we need it**:
Allow users to configure the docker registry used when applying cdk-addons templates.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Depends on https://github.com/juju-solutions/cdk-addons/pull/45

**Release note**:

```release-note
Expose docker registry config for addons used in Juju deployments
```

### CODE REVIEW

**Comment by hyperbolic2346** [comment]
/retest
LGTM

**Comment by Cynerva** [comment]
/lgtm

Thanks!

**Pull request merged**
