### PR TITLE
Increase build verbosity for verify-generated-{protobuf,runtime}.sh

### PR DESCRIPTION
**Pull request by ixdy**
Print out more details of the build process to help with debugging #34675.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34745)

### CODE REVIEW

**Comment by spxtr** [comment]
LGTM

**Comment by ixdy** [comment]
this is actually way more spammy than I realized. I'm gonna tweak things a bit.

**Comment by ixdy** [comment]
I've dropped the status lines to V=3 instead of V=6, and set verbosity level to 3 instead. The `rsync -iv` output was too much.

**Comment by ixdy** [comment]
This looks more reasonable. @spxtr @jbeda PTAL?

**Comment by jbeda** [comment]
LGTM -- not sure where the V=6 stuff came from.  I like the split you have here better.

**Comment by ixdy** [comment]
@jbeda I think that came from your PR. :) so many rebases though, who knows.

**Pull request merged**
