### PR TITLE
remove unused const dockerDaemonConfigName in docker_util.go

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by oomichi** [comment]
This seems unused at all since https://github.com/kubernetes/kubernetes/commit/9f1f83020b9fcee98300cbbc0a046240db55facc which added dockerDaemonConfigName at first time.

/lgtm

**Comment by oomichi** [comment]
Oh, need to change the indent for passing `pull-kubernetes-verify`.

**Comment by oomichi** [comment]
Thanks for updating

/lgtm

**Comment by qingsenLi** [comment]
/cc @vishh @yujuhong 
Needs approved label.thanks

**Pull request merged**
