### PR TITLE
Automated cherry pick of #60346: fix device name change issue for azure disk

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #60346 on release-1.9.

#60346: fix device name change issue for azure disk
**Release note**:

```
fix disk unavailable issue when mounting multiple azure disks due to dev name change
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
kind/bug

**Comment by mbohlool** [comment]
Is there any test for this?

**Comment by andyzhangx** [comment]
hi @mbohlool we have tested on azure platform, and we have identified it's a azure specific issue.

**Comment by mbohlool** [comment]
@andyzhangx It would be better to have a e2e/conformance/unit test but accepting manual test for this CP.

**Pull request merged**
