### PR TITLE
Fix kubeup.kerneltime

### PR DESCRIPTION
**Pull request by kerneltime**
**What this PR does / why we need it**:
This fixes kube-up to correctly install and configure on vSphere.
https://github.com/kubernetes/kubernetes/issues/34992
https://github.com/kubernetes/kubernetes/issues/34847
To test and socialize the fixes we need kube-up support for cloud provider which is cherry picked from master.  Without this we are finding it difficult to get devs and users testing the cloud provider framework. 
I will also move these fixes into master.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34993)

### CODE REVIEW

**Comment by kerneltime** [comment]
cc @dagnello @imkin @abrarshivani @luomiao

**Comment by zmerlynn** [comment]
Thanks for the PR! Unless there's some extenuating circumstance I don't see, this PR needs to be against `master` instead of `release-1.4`. Then it can be cherry-picked back to 1.4 as appropriate.

**Comment by kerneltime** [comment]
They extenuating circumstance is that we need this in 1.4 release train ASAP, we were hoping to get this into 1.4.3 but it was cut almost in the same week as 1.4.2. This is currently blocking all deployment of vSphere for 1.4 release train and no way to use the vSphere cloud provider.

**Comment by zmerlynn** [comment]
Not to be pedantic, but that's still a fast PR to master and get it through the process to cherry-pick back. Otherwise there's the risk is this gets dropped for v1.5.

**Comment by kerneltime** [comment]
@zmerlynn makes sense.
As long as we can cherry pick it to 1.4 it should be fine. 
Thank you.

**Comment by kerneltime** [comment]
Done https://github.com/kubernetes/kubernetes/pull/34997

**Pull request closed without merging**
