### PR TITLE
Added alejandrox1 to pkg/kubelet reviewers

### PR DESCRIPTION
**Pull request by alejandrox1**
Signed-off-by: alejandrox1 <alarcj137@gmail.com>

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:
I have been working with @kubernetes/sig-node-test-failures team and have had the chance to dive into the kubelet.
I would like to become a reviewer to get more experience here and to help out triage and review the incoming work this part of the project. 

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by alejandrox1** [comment]
/assign @dchen1107 @derekwaynecarr 
ptal

**Comment by derekwaynecarr** [comment]
Can you add more details to describe the requirements met per community guidelines:
https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer

Thanks!

**Comment by alejandrox1** [comment]
ha that's a good point!
I've been focusing on the testing side of the kubelet but have not directly participated to /pkg/kubelet.
So I don't meet the requirement for having collaborated on code directly for /pkg/kubelet.
I wanted to become a reviewer to get do that more formally but I will start from there.
Sorry for jumping the gun but thank you very much for your comment @derekwaynecarr 

/close

**Pull request closed without merging**
