### PR TITLE
promote component SLIs to GA; remove feature gates for component slis

### PR DESCRIPTION
**Pull request by logicalhan**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Component SLIs is GAing. This PR removes the feature gates associated with component SLIs.

#### Does this PR introduce a user-facing change?

```release-note
The metrics controlled by the ComponentSLIs feature-gate and served at /metrics/slis are now GA and unconditionally enabled. The feature-gate will be removed in 1.31.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/3466
```

### CODE REVIEW

**Review by kerthcet — COMMENTED** [review]
/lgtm
/approve 
for sig-scheduling side

**Comment by liggitt** [comment]
/approve

can you update the release note with more details of the user-facing impact? e.g. "The metrics controlled by the `ComponentSLIs` feature-gate and served at `/metrics/slis` are now GA and unconditionally enabled. The feature-gate will be removed in 1.31."

**Comment by pacoxu** [comment]
/test pull-kubernetes-e2e-kind-ipv6
flake https://github.com/kubernetes/kubernetes/issues/120650

**Pull request merged**
