### PR TITLE
rename elasticsearch addon port to be IANA_SVC_NAME

### LINKED ISSUE #10537: elasticsearch-logging-v1 spec:  invalid value 'es-transport-port'
Error from kubectl when the addon controller is created:

```
The ReplicationController "elasticsearch-logging-v1" is invalid:spec.template.spec.containers[0].ports[1].name: spec.template.spec.containers[0].ports[1].name: invalid value 'es-transport-port': must be an IANA_SVC_NAME (at most 15 characters, matching regex [a-z0-9]([a-z0-9-]*[a-z0-9])*, it must contain at least one letter [a-z], and hypens cannot be adjacent to other hyphens): e.g. "http"
```

### PR DESCRIPTION
**Pull request by marekbiskup**
fixes #10537

### CODE REVIEW

**Comment by zmerlynn** [comment]
@k8s-bot: ok to test

**Comment by zmerlynn** [comment]
@k8s-bot: retest this please

**Comment by zmerlynn** [comment]
@marekbiskup: Did you happen to run the (flakey but still valuable signal) Elasticsearch e2e?

**Comment by marekbiskup** [comment]
@zmerlynn, I'll try now.

**Comment by zmerlynn** [comment]
LGTM. I assume this removes the validation complaint loading Elasticsearch.

@thockin - Stamps quickly would be appreciated. This is at the bottom of a split chain that goes #10609  -> #10618 -> #10487

cc @quinton-hoole as well.

**Comment by marekbiskup** [comment]
elasticsearch e2e test passes when run manually

**Comment by zmerlynn** [comment]
@marekbiskup: Thanks!

**Comment by zmerlynn** [comment]
@marekbiskup: Actually, is there anyone around on that end who can give a second LGTM? I'm willing to skirt process a slight bit on this and #10237 so we can have #10618 in a fully mergeable state soon, but the spirit of the process is to ensure that this meets the needs and quality of the v1 release.

**Comment by zmerlynn** [comment]
Superseded by #10453.

**Pull request closed without merging**
