### PR TITLE
Prune directxman12 from metrics/autoscaling OWNERS

### PR DESCRIPTION
**Pull request by DirectXMan12**
Since I'm not really working on metrics or autoscaling stuff any more, I
figured it was time to remove myself from the approvers list.

/kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Comment by DirectXMan12** [comment]
@brancz this leaves k8s.io/metrics with only one approver.  Can you or someone else step in?

**Comment by brancz** [comment]
@s-urbaniak are you interested in stepping up for this?

**Comment by s-urbaniak** [comment]
@brancz I'd love to yes :+1:

**Comment by DirectXMan12** [comment]
awesome

**Comment by DirectXMan12** [comment]
@liggitt or someone can we get this merged?

**Pull request merged**
