### PR TITLE
Delete Makefile as it is useless

### LINKED ISSUE #16292: Kubelet Image Makefile out of date
Are reported on kubernetes-dev, cluster/images/kubelet/Makefile says `VERSION=v0.16`.

Suggested deleting this file since clearly it has not been used recently and is confusing to people.

### PR DESCRIPTION
**Pull request by resouer**
Remove `cluster/images/kubelet/Makefile` since it is out of date @erictune 

Fix #16292

Otherwise, we need to update the version, maybe, to a env. But I didn't see where this Makefile is referenced, for now.

### CODE REVIEW

**Comment by roberthbailey** [comment]
@fgrzadkowski -- is this used for the kubelet-in-docker work?

**Comment by dchen1107** [comment]
cc/ @pmorie Are you, or openshift still trying to run kubelet as docker container?

**Comment by dchen1107** [comment]
Ok, let's delete this one for now. If it is required later, we can add it back. 

LGTM

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by pmorie** [comment]
@dchen1107 I'm sorry I missed your ping on this in the flood somehow :)  We do still have a containerization use-case for the Kubelet that I use this makefile to test.  I'd like to have it back.

**Comment by dchen1107** [comment]
No problem. Just both you and @fgrzadkowski who had been actively playing with containerinzed Kubelet didn't response, and the Makefile looks like very out-of-dated too, we decided to remove it to clean our codebase. :-)

Feel free to revert this PR and update it to reflect the current status. Thanks!

**Comment by pmorie** [comment]
@dchen1107 I'll add a better Makefile in a new PR, thanks :)

**Comment by fgrzadkowski** [comment]
I'm sorry for late response. I was on vacations for the last 2.5 weeks. This file is not used in kube-in-docker setup (it uses hyperkube image).

**Pull request merged**
