### PR TITLE
refactor for node lifecycle controller

### PR DESCRIPTION
**Pull request by pandaamanda**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Small changes to increase code readability.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by valaparthvi** [comment]
@soltysh The changes in this PR lgtm. I do not think I have missed anything because the refactor is straightforward but I'm tagging you so that you can tell in case I have.

**Comment by pandaamanda** [comment]
PTAL
/assign @k82cn

**Pull request closed without merging**
