### PR TITLE
Automated cherry pick of #41929 #42974 #42024 upstream release 1.6

### PR DESCRIPTION
**Pull request by BaluDontu**
Cherry pick of #41929 #42974 #42024 on release-1.6.

#41929: vSphere Cloud Provider: Fstype in storage class
#42974: VSAN policy support for storage volume provisioning inside kubernetes
#42024: Remove VCenterPort from vsphere cloud provider.

### CODE REVIEW

**Comment by BaluDontu** [comment]
@lavalamp : This is a cherrypick request, somehow my PR didn't have a cherry-pick label. Can u add it?
@jingxu97 @saad-ali

**Comment by enisoc** [comment]
This appears to be adding new functionality, which does not meet the requirements for inclusion in a [patch release](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/versioning.md#patch-releases). If this is somehow necessary to fix a critical bug that is causing breakage for users, please elaborate.

**Comment by BaluDontu** [comment]
@enisoc : #41929 and #42024 are bug fixes and #42974 is a new feature which is already checked into master. 

We want this feature and bug fixes to be part of next 1.6 release. Unless we cherry-pick, how can we make this as part of next release.

**Comment by enisoc** [comment]
New features are not allowed in patch releases (v1.6.x). They will have to wait until v1.7.

**Pull request closed without merging**
