### PR TITLE
Refresh root, build, cluster OWNERS files from main branch

### PR DESCRIPTION
**Pull request by spiffxp**
Cherry pick of #93935 on release-1.18.  EDIT: Plus a manually added commit, see comments below

#93935: Promote spiffxp to build/ approver

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by spiffxp** [comment]
Added another commit to refresh OWNERS files from 1e8f7a9265a3ecf9b3f551342f8d09ea0514a134 (when https://github.com/kubernetes/kubernetes/pull/93935 landed), specifically:
- OWNERS
- OWNERS_ALIASES
- build/OWNERS
- cluster/OWNERS

/cc @liggitt 
since this now touches root OWNERS

**Comment by spiffxp** [comment]
/retitle Refresh root, build, cluster OWNERS files from main branch

**Comment by liggitt** [comment]
verified zero diff with:

> `git diff upstream/master spiffxp/automated-cherry-pick-of-#93935-upstream-release-1.18 -- OWNERS OWNER_ALIASES build/OWNERS cluster/OWNERS`

/lgtm
/approve

**Comment by spiffxp** [comment]
/test pull-kubernetes-integration
flake https://github.com/kubernetes/kubernetes/issues/89712

**Pull request merged**
