### PR TITLE
Correct a syntax error in a comment

### PR DESCRIPTION
**Pull request by lioncruise**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by lioncruise** [comment]
Seems need to retest due to `pull-kubernetes-e2e-kops-aws` job failed. @sttts @php-coder

**Comment by php-coder** [comment]
@lioncruise When the PR will be approved it will run all the tests again and if pull-kubernetes-e2e-kops-aws  check fail again, it will be automatically rerun. So, I don't see a reason of triggering this check again and again prior approval.

**Comment by lioncruise** [comment]
@sttts  Seems need your `/approve no-issue` to merge this PR.

**Comment by lioncruise** [comment]
@php-coder  Seems need your /approve no-issue to merge this PR.

**Comment by php-coder** [comment]
@lioncruise I don't have permissions for approve.

@sig-cli-maintainers PTAL

**Comment by lioncruise** [comment]
@sttts @smarterclayton  Seems need your /approve no-issue to merge this PR.

**Comment by liggitt** [comment]
The comment is correct as is
/close

**Pull request closed without merging**
