### PR TITLE
Remove etcd2 storage backend

### PR DESCRIPTION
**Pull request by liggitt**
**What this PR does / why we need it**:
Removes the deprecated etcd2 backend

**Which issue(s) this PR fixes**:
xref https://github.com/kubernetes/features/issues/622

**Special notes for your reviewer**:

**Release note**:

```release-note
kube-apiserver has removed support for the `etcd2` storage backend (deprecated since v1.9). Existing clusters must migrate etcd v2 data to etcd v3 storage before upgrading to v1.13.
```

cc @kubernetes/sig-api-machinery-pr-reviews @kubernetes/sig-cluster-lifecycle-pr-reviews 

/assign @lavalamp @deads2k

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/sig-testing-pr-reviews for impact on test jobs
cc @justinsb

**Comment by liggitt** [comment]
holding to make sure there are no CI jobs still intentionally starting on etcd2 for test signal

**Comment by fejta** [comment]
Do we still have tests that run on etcd2? Is plan to remove them before or after this?

**Comment by liggitt** [comment]
> Do we still have tests that run on etcd2?

I don't know. The only tests we should have at this point are ones that specifically exist to ensure we continue to function on etcd2.

> Is plan to remove them before or after this?

They should be removed before this merges.

**Review by timothysc — APPROVED** [review]
/lgtm 
/hold 

per @fejta 's comment.  Once someone cross-verifies test-grid feel free to cancel the hold.

**Comment by BenTheElder** [comment]
see: https://github.com/kubernetes/test-infra/issues/7602

there are a few test-infra things to cleanup when we make the switch. cc @spiffxp

**Comment by lavalamp** [comment]
/approve

Tests look angry though.

**Comment by BenTheElder** [comment]
This doesn't build currently:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/69310/pull-kubernetes-typecheck/26323/#verify-typecheck

```
2018/10/01 20:58:15 Code for OpenAPI definitions generated
ERROR(all) vendor/k8s.io/apiserver/pkg/registry/generic/testing/tester.go:139:12: EtcdCreate not declared by package etcd
ERROR(all) vendor/k8s.io/apiserver/pkg/registry/generic/testing/tester.go:139:36: EtcdDelete not declared by package etcd
ERROR(all) vendor/k8s.io/apiserver/pkg/registry/generic/testing/tester.go:188:7: EtcdCreate not declared by package etcd
ERROR(all) vendor/k8s.io/apiserver/pkg/registry/generic/testing/tester.go:190:7: EtcdDelete not declared by package etcd
exit status 1
!!! Type Check has failed. This may cause cross platform build failures.
!!! Please see https://git.k8s.io/kubernetes/test/typecheck for more information.
````

**Comment by liggitt** [comment]
Yup, will fix

**Comment by dims** [comment]
@liggitt at what point do we remove the following?
- ./third_party/forked/etcd221
- ./third_party/forked/etcd237

**Comment by liggitt** [comment]
> @liggitt at what point do we remove the following?
> 
> * ./third_party/forked/etcd221
> * ./third_party/forked/etcd237

that's not related to support of the etcd v2 backend... @wojtek-t, @ixdy, @xiang90 - do you know what those are used for and whether they can be removed at this point? if so, let's remove those in a separate PR

**Comment by wojtek-t** [comment]
Awesome - this is great to see it happening!

Though there are tests that still fail.
In particular I think node-e2e tests are still using etcd v2:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/services/etcd.go

We should probably fix that earlier in a separate PR.
[I think I files an issue for that some time ago, but I can't find it now]

**Comment by justinsb** [comment]
kops is green :-)

**Comment by liggitt** [comment]
I'll fix the verify error and take a look at the node e2e

**Comment by liggitt** [comment]
/assign @wojtek-t 
can you review the "Switch e2e_node to etcd3" commit?

**Comment by liggitt** [comment]
presubmit tests are green

waiting on @wojtek-t for review of e2e node commit, and @spiffxp for ack that tests look good after https://github.com/kubernetes/test-infra/pull/9672 merged

**Comment by wojtek-t** [comment]
> can you review the "Switch e2e_node to etcd3" commit?

This looks great.

/lgtm

**Comment by wojtek-t** [comment]
/hold

Since we want to wait for other tests results.
@liggitt - feel free to unhold it when you're ready.

**Comment by spiffxp** [comment]
/lgtm
I'm confident enough in what I've seen over the past 12 hours to say we're good to go.  That said, I waited until overnight PT to let my changes merge, so I got N runs against the same commit.  I leave it to @liggitt to remove the /hold when ready

**Comment by liggitt** [comment]
rebased

**Pull request merged**
