### PR TITLE
WIP: Remove deprecated publicIPs

### PR DESCRIPTION
**Pull request by thockin**

### CODE REVIEW

**Comment by kelseyhightower** [comment]
Code LGTM, can't see why the e2e test is failing.

**Comment by thockin** [comment]
@k8s-bot test this please

On Mon, Jul 27, 2015 at 12:48 PM, Kelsey Hightower <notifications@github.com

**Comment by juntagabor** [comment]
Just a question. Once this gets committed, is it expected to have #10323 addressed more or less at the same time?

**Comment by thockin** [comment]
This is targetting 1.1 - I intend for #10323 to be resolved in 1.1, yes.

**Comment by thockin** [comment]
In fact, this is a fair point.  Let's NOT commit this until we have a solution.

**Pull request closed without merging**
