### PR TITLE
Validate CRD stored messageExpressions with the correct CEL environment

### LINKED ISSUE #125702: CEL stored messageExpressions of CRDs are not validated with the correct CEL environment
### What happened?

Noticed a copy & paste issue when reading through the CEL code.

Basically here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go#L182

This should be 
> expressions.messageExpressions.Insert(v.MessageExpression)
instead of:
> expressions.messageExpressions.Insert(v.Rule)

The impact of this issue should be that messageExpressions are always evaluated with the CEL environment of the compatibility version. But stored (i.e. pre-existing) messageExpressions should be evaluated with a CEL environment with the "max" version instead.

For users of Kubernetes this means that messageExpressions deployed with one minor version of Kubernetes might not work anymore if they rollback e.g. by one minor version.

### What did you expect to happen?

messageExpressions should be treated the same way as rules in that regard.

### How can we reproduce it (as minimally and precisely as possible)?

* Deploy Kubernetes 1.30
* Deploy CRD that uses messageExpression that is using Sets (which became available with Kubernetes 1.30 that is using compatibilty version 1.29)
* Rollback to Kubernetes 1.29
* Update something in the CRD
  * => CRD update will fail because messageExpression is evaluated with the wrong CEL environment (it should still work)

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

At least on Kubernetes main, but I would assume this isuse is there since CEL was implemented

</details>

### Cloud provider

-

### OS version

-

### Install tools

-

### Container runtime (CRI) and version (if applicable)

-

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #125702

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
change looks good to me with a cursory review

/assign @jpbetz @cici37 
for test review

**Comment by jpbetz** [comment]
/approve
/lgtm
The tests look right here.  Thanks for fixing!

**Pull request merged**
