### PR TITLE
Fix typo in docstring of DeepEqual

### PR DESCRIPTION
**Pull request by daxmc99**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

/kind cleanup

**What this PR does / why we need it**:
Change "imformative" to informative

Small change but I hope it keeps others from googling what "imformative" means

**Which issue(s) this PR fixes**:

Fixes NONE

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by zouyee — APPROVED** [review]

**Comment by zacharysarah** [comment]
@daxmc99 Thanks for the fix.

/sig docs
/priority important-soon
/lgtm

**Comment by alejandrox1** [comment]
/retest

pref err: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/83385/pull-kubernetes-kubemark-e2e-gce-big/1181714356509872128/

**Comment by neolit123** [comment]
seems like a typo that was introduced in our fork, so LGTM.

**Comment by alejandrox1** [comment]
/assign @lavalamp
ptal
/cc @thockin @smarterclayton

**Comment by daxmc99** [comment]
Bump @lavalamp

**Pull request merged**
