### PR TITLE
fix shellcheck in node-api

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

fix shellcheck failures in `staging/src/k8s.io/node-api`

**Which issue(s) this PR fixes**:

work towards #72956

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by BenTheElder — APPROVED** [review]
/lgtm
thanks!

**Comment by danielqsj** [comment]
rebased
@dchen1107 for approve

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Comment by nikhita** [comment]
/retest
/sig node

/assign @tallclair 
for node-api approval

/assign @cblecker 
for hack/ approval

**Comment by tallclair** [comment]
/approve
Thanks!

**Pull request merged**
