### PR TITLE
Replace ioutil with io and os

### PR DESCRIPTION
**Pull request by ahrtr**
The ioutil package has already been deprecated in golang 1.16, please see [go1.16#ioutil](https://golang.org/doc/go1.16#ioutil). So we also need to replace all the ioutil with os and io.

ioutil.ReadDir is a special case, it returns a slice of fs.FileInfo, but os.ReadDir returns a slice of os.DirEntry. So let's fix ioutil.ReadDir in a separate PR.

### CODE REVIEW

**Comment by ahrtr** [comment]
> Yes please... try to make the changes per SIG

Sure, will do.

**Review by neolit123 — COMMENTED** [review]
the tracking issue for this is here:
https://github.com/kubernetes/kubernetes/issues/100367

please ask there if this is desired.

**Comment by neolit123** [comment]
also someone already sent a related PR here:
https://github.com/kubernetes/kubernetes/pull/105716

if these changes are desired, might be best to coordinate.

**Comment by ahrtr** [comment]
> also someone already sent a related PR here: #105716
> 
> if these changes are desired, might be best to coordinate.

Thanks. Closing this PR.

**Comment by ahrtr** [comment]
Some smaller PRs are submitted below, more PRs will be submitted later per the SIGs, 
https://github.com/kubernetes/kubernetes/pull/106021 
https://github.com/kubernetes/kubernetes/pull/106020 
https://github.com/kubernetes/kubernetes/pull/106019
https://github.com/kubernetes/kubernetes/pull/106018
https://github.com/kubernetes/kubernetes/pull/106015

**Comment by ahrtr** [comment]
Reopen this one, and once all the smaller PRs are merged, will close this again. Thanks

**Comment by neolit123** [comment]
> Some smaller PRs are submitted below, more PRs will be submitted later per the SIGs, #106021 #106020 #106019 #106018 #106015 #106062

i think you can link these in https://github.com/kubernetes/kubernetes/issues/100367 and this PR can be closed?

**Comment by ahrtr** [comment]
> > Some smaller PRs are submitted below, more PRs will be submitted later per the SIGs, #106021 #106020 #106019 #106018 #106015 #106062
> 
> i think you can link these in #100367 and this PR can be closed?

Sure, thanks for the comment.

**Pull request closed without merging**
