### PR TITLE
Update github.com/prometheus/common/...

### PR DESCRIPTION
**Pull request by orisano**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
update github.com/prometheus/common/... for performance.
https://github.com/prometheus/common/pull/148
https://github.com/prometheus/common/pull/150

kubelet
labelPairToText improvement.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by orisano** [comment]
I signed it

**Comment by orisano** [comment]
what is status this PR?

**Comment by smarterclayton** [comment]
/assign @kubernetes/sig-instrumentation-pr-reviews 
@brancz

**Comment by danielqsj** [comment]
I think we can directly update to the newest release `v0.2.0`.

**Comment by mxinden** [comment]
:+1:  for getting [prometheus/common#148](https://github.com/prometheus/common/pull/148) and [prometheus/common#150](https://github.com/prometheus/common/pull/150) in.

Preferably with a released version (v0.2.0) like suggested by @danielqsj in https://github.com/kubernetes/kubernetes/pull/74248. Not sure what the best practice in terms of vendoring is for Kubernetes.

**Comment by danielqsj** [comment]
@mxinden the discussion about go modules is here https://github.com/kubernetes/kubernetes/issues/63607. 
IMHO, `go modules` is definitely the future, but before the migration,  we can only follow the current vendoring management.

**Comment by danielqsj** [comment]
Go modules discussion also here https://github.com/kubernetes/kubernetes/issues/68577

**Comment by mxinden** [comment]
Given that https://github.com/kubernetes/kubernetes/pull/74248 merged, I think this can be closed.

**Pull request closed without merging**
