### PR TITLE
Fix the confusing kubelet logs about imageGC

### LINKED ISSUE #69256: Log of imageGCManager is confusing
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/sig node

**What happened**:
following is kubelet logs
`[imageGCManager]: Disk usage on image filesystem is at 85%  which is over the high threshold (85%). Trying to free 3285922611 bytes`

It's confusing that why kubelet still try to free **3285922611** bytes when **usage(85%)** equals to **high threshold(85%)**

With the code, I understood that kubelet tried to keep freeing **down to the LowThresholdPercen(80%)** not  the HighThresholdPercent
```
	if usagePercent >= im.policy.HighThresholdPercent {
		amountToFree := capacity*int64(100-im.policy.LowThresholdPercent)/100 - available
		glog.Infof("[imageGCManager]: Disk usage on image filesystem is at %d%% which is over the high threshold (%d%%). Trying to free %d bytes", usagePercent, im.policy.HighThresholdPercent, amountToFree)
```

**What you expected to happen**:
`[imageGCManager]: Disk usage on image filesystem is at 85% which is over the high threshold (85%). Trying to free 3285922611 bytes down to the low threshold  (80%).`

**How to reproduce it (as minimally and precisely as possible)**:
Reduce the imagefs capacity to trigger image gc

**Environment**:
- latest Kubernetes

### PR DESCRIPTION
**Pull request by chestack**
**What this PR does / why we need it**:
optimize the kubelet log about imageGC to make it more understandable

**Which issue(s) this PR fixes** *
Fixes #69256

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Comment by nikhita** [comment]
/retest
/kind bug

/assign @yujuhong 
for approval

**Comment by chestack** [comment]
Job pull-kubernetes-local-e2e-containerized failed several times

**Pull request merged**
