### PR TITLE
Fixed loop error on popstate change when using forward and back browser buttons

### PR DESCRIPTION
**Pull request by RichieEscarez**
This loop error is seen in the console when navigating to URLs with anchors. Otherwise in the browser you seen that the page does not load when you navigate to a URL (browser back/forward) that has an anchor (#) in the URL.

### CODE REVIEW

**Comment by thockin** [comment]
I'm unequipped to review this, so I'm just going to approve it.  I confirm the existence of the error

**Comment by thockin** [comment]
I still see an error when using the forward button.


Uncaught RangeError: Maximum call stack   services.html:1205

**Comment by thockin** [comment]
Also an error loading google jsapi

**Comment by thockin** [comment]
Actually, the error now shows when I click any anchor link within a doc.

http://kubernetes.io/v1.0/docs/user-guide/services.html - click a TOC link

**Comment by RichieEscarez** [comment]
Sorry @thockin, I failed to copy over the remaining changes for this fix into this PR (out of my gh-pages branch im testing in (and pushing to my fork)). #12034 includes the change i missed copying and should clear up any other console errors.

**Comment by RichieEscarez** [comment]
ill troubleshoot the google jsapi error next

**Comment by RichieEscarez** [comment]
The google jsapi error appears to be a known google cse issue: https://productforums.google.com/forum/#!category-topic/customsearch/9WJ2G1rJXWE

Per the thread, there is no solution but suggests to try the v1 code (will try that next).

**Pull request merged**
