### PR TITLE
Fix comments; switch to watching nodes

### PR DESCRIPTION
**Pull request by lavalamp**
@davidopp following up.

I'm running e2e to make sure the node watching change works.

### CODE REVIEW

**Comment by lavalamp** [comment]
OK, turns out the integration test caught the problem (but I mistook it for a common flake) and there's probably no need to run e2e. I'll start it running anyway.

**Comment by davidopp** [comment]
LGTM

**Comment by wojtek-t** [comment]
What is the status of this PR - is that ready for merge?

**Comment by dchen1107** [comment]
What is the e2e test result? Can we merge?

**Comment by lavalamp** [comment]
Let's just merge. My e2e run mysteriously paused itself when I went home on friday.

**Comment by lavalamp** [comment]
But I'm pretty confident that the integration test found all the issues.

**Pull request merged**
