### PR TITLE
Build using go1.9.3

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: more minor bugfixes, which I guess we probably want. https://github.com/golang/go/issues?q=milestone%3AGo1.9.3

**Special notes for your reviewer**: I haven't built/pushed the crossbuild image yet, but will do so if we think this is a good idea. I don't have plans to rebuild the test images.

**Release note**:

```release-note
Build using go1.9.3.
```

Who are good people to review this?
/assign @cblecker @luxas 
(for lack of better ideas)

### CODE REVIEW

**Comment by cblecker** [comment]
@ixdy Looks good to me (pending image push)

**Comment by ixdy** [comment]
crossbuild image pushed.

/retest

**Comment by ixdy** [comment]
cherrypick PR: #59498

**Comment by cblecker** [comment]
@ixdy go1.9.4 is coming out today with a security fix. we should probably pause for that before cherry pick.

**Comment by ixdy** [comment]
good call.

**Pull request merged**
