### PR TITLE
Fix job backoff limit for restart policy Never

### LINKED ISSUE #93559: job fails before the `.spec.backoffLimit`
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
$oc create job -f job.yaml
$ oc get job jobname -ojson | jq .status
{
  "active": 1,
  "failed": 1,
  "startTime": "2020-07-30T06:45:37Z"
}
{
  "active": 1,
  "failed": 2,
  "startTime": "2020-07-30T06:45:37Z"
}
{
  "active": 1,
  "failed": 3,
  "startTime": "2020-07-30T06:45:37Z"
}
{
  "active": 1,
  "failed": 4,
  "startTime": "2020-07-30T06:45:37Z"
}
{
  "conditions": [
    {
      "lastProbeTime": "2020-07-30T06:53:10Z",
      "lastTransitionTime": "2020-07-30T06:53:10Z",
      "message": "Job has reached the specified backoff limit",
      "reason": "BackoffLimitExceeded",
      "status": "True",
      "type": "Failed"
    }
  ],
  "failed": 5,
  "startTime": "2020-07-30T06:45:37Z"
}
$ oc get job jobname -ojson | jq .spec.backoffLimit
6
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: 4.5.3
Server Version: 4.4.13
Kubernetes Version: v1.17.1+b8568b
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="Red Hat Enterprise Linux CoreOS"
VERSION_ID="4.4"
OPENSHIFT_VERSION="4.4"
RHEL_VERSION="8.2"
ID="rhcos"
ID_LIKE="rhel fedora"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::coreos"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.4"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.4"
OSTREE_VERSION='44.82.202007141430-0'
- Kernel (e.g. `uname -a`):
Linux ip-10-0-192-232 4.18.0-193.13.2.el8_2.x86_64 #1 SMP Mon Jul 13 23:17:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
apiVersion: batch/v1
kind: Job
metadata:
  name: sre-build-test-fail
  namespace: openshift-build-test
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io
                operator: In
                values:
                - infra
      containers:
      - command:
        - /bin/bash
        - -c
        - |
          # ensure we fail if something exits non-zero
          set -o errexit
          set -o nounset
          set -o pipefail
          exit 1

        imagePullPolicy: Always
        name: sre-build-test
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io
        operator: Equal
        value: infra

### PR DESCRIPTION
**Pull request by yodarshafrir1**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
The Job controller currently uses `NumRequeues` to decide wether or not the job has exceeded the backoffLimit. `NumRequeues` represents the number of times a job has been requeued, a requeue can occur due to several reasons and not only for Fail events. This makes backoffLimit unpredictable.

This PR sets the job controller to use the number of `Failed` pods to decide if the job has exceeded the backoffLimit.

According to the documentation: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/apps/job.md#backoff-policy-and-failed-pod-limit

> For Never we count actual pod failures (reflected in .status.failed field). With OnFailure, we take an approximate value of pod restarts (as reported in .status.containerStatuses[*].restartCount). 

For restart policy of `OnFailure` - the logic is handled in `pastBackoffLimitOnFailure` as described above.
For restart policy of `Never` - this PR fixes the logic to be as described above.

This solution has been discussed in the past by @janetkuo  in: https://github.com/kubernetes/kubernetes/issues/70251#issuecomment-433507671 

**Which issue(s) this PR fixes**:

Fixes #93559, #92245, #70251, #64787

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by georgettica** [comment]
Wow! Thanks so much for the PR! Can't wait to use this on my cluster

**Comment by yodarshafrir1** [comment]
retest

**Comment by georgettica** [comment]
tests are passing, can someone PTAL?

**Comment by farah** [comment]
@yodarshafrir1 Spent a few days working on this and testing and was just about to submit a PR  when I saw this. I don't mind but wish you had pinged #92245 so I could've spent time on something else.

**Comment by yodarshafrir1** [comment]
pinging @soltysh, @smarterclayton, @krmayankk for review/comments

**Comment by yodarshafrir1** [comment]
@soltysh @smarterclayton @krmayankk could you please have a look?

**Comment by yodarshafrir1** [comment]
@soltysh @smarterclayton @krmayankk could you please review?

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
