### PR TITLE
Merge release 0.19.3 to master

### PR DESCRIPTION
**Pull request by zmerlynn**
Git gymnastics to get 0.19.3 into master.

### CODE REVIEW

**Comment by zmerlynn** [comment]
Hmm. Something fishy here, please hold.

**Comment by zmerlynn** [comment]
So, the git tags and the version files are divergent because of failed pull #10184. I had to mess with the file manually again here, but I think I understand why. Good to go now.

**Comment by zmerlynn** [comment]
cc @roberthbailey @jlowdermilk

**Comment by jlowdermilk** [comment]
lgtm

**Comment by roberthbailey** [comment]
@eparis

**Comment by roberthbailey** [comment]
LGTM.

**Comment by eparis** [comment]
I'm not going to do the git digging to see what went wrong this time, but on the surface it looks ok.

**Pull request merged**
