### PR TITLE
Use supplied etcd2 with CoreOS

### PR DESCRIPTION
**Pull request by rassie**
Commit https://github.com/GoogleCloudPlatform/kubernetes/commit/11556dc927247b96d1a18e45e48876e75ce3edab has introduced an extra download for `etcd` 2.0.9 with the intention to revert when CoreOS shipped `etcd2`. This is now the case, however `etcd` 0.4.9 is shipped as `etcd` and `etcd` 2.0.11 as `etcd2`. This PR reverts to using shipped `etcd` and makes use of `etcd2`.

### CODE REVIEW

**Comment by rassie** [comment]
Please check again!

**Comment by rassie** [comment]
I'm the author, however since there is a reverting commit, I'd add @lhuard1A to the mix, since it's his commit I'm reverting.

**Comment by roberthbailey** [comment]
I understand why you might not want to run two instances of etcd on your CoreOS cluster as one (or now two?) instances already exist, but at this point, the etcd used by the master should be considered a private implementation detail of the master. 

We haven't tested the master with etcd 2.0.11 and it may or may not work properly. As CoreOS updates the version of etcd2 you will automatically get bumped up to newer versions during deployments, which may break your cluster creation in unexpected ways.

**Comment by rassie** [comment]
The original reverted patch installed an `etcd` 2.0.9, which at that point wasn't supported either IIRC, so there is probably no harm in using 2.0.11. In any case, `libvirt-coreos` is normally not used for complete productive cluster installation, but instead usually used for development and testing, which is what I'm using it for.

Speaking of which: isn't `etcd` supposed to run in a container anyway? In this case, using CoreOS's version might become irrelevant.

**Comment by jakexks** [comment]
We've been using Kubernetes with etcd2, it seems to work fine despite being unsupported!

**Comment by rassie** [comment]
@jakexks: the point seems to be that Kubernetes supports `etcd2` (version 2.0.x seems to be a requirement nowadays), just not necessarily the latest version.

**Comment by lhuard1A** [comment]
Indeed, my initial intention was to revert to using the etcd2 shipped within CoreOS.
In fact, I already submitted a PR for that: #7227

There are pros and cons for both having dedicated etcd instances for CoreOS on one side and for Kubernetes on the other side and for sharing the same instance.

I understand that Kubernetes is regularly tested only with a given minor version of etcd2, but the initial goal of the `libvirt-coreos` cluster provider was not to be as “production look-alike” as possible, it was to be a way to spawn a local multi-node cluster as fast as possible and in the lighter way as possible.
With that goal in mind, having to download an extra version of etcd2 sounded superfluous to me.

The question is now: is the behavior of minor versions of etcd2 expected to change so much that Kubernetes can’t afford being run with the lastest one?

**Comment by saad-ali** [comment]
Assigning @dchen1107 
v1.0 triage needed

**Comment by dchen1107** [comment]
@rassie I am closing this pr in favor of #7227. Thanks!

**Pull request closed without merging**
