### PR TITLE
fix all the typos across the project

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:
There are lots of typos across the project. We should avoid small PRs on fixing those annoying typos, which is time-consuming and low efficient.

This PR does fix all the typos across the project currently. And with #59463, typos could be avoided when a new PR gets merged.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/sig testing
/area test-infra
/sig release
/cc @ixdy 
/assign @fejta 

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by dixudx** [comment]
/assign @liggitt @smarterclayton 
PTAL. Thanks.

**Comment by dixudx** [comment]
ping @liggitt @smarterclayton Rebased. PTAL. Thanks.

**Review by BenTheElder — APPROVED** [review]
/lgtm
that's a lot of typos, thanks! :-)

**Comment by fejta** [comment]
/assign @bgrant0607 @brendandburns @dchen1107 @wojtek-t

Can we get an /approve on this bulk spelling fix PR so we can merge the spelling verify check PR so we can stop getting spelling fix PRs forever more? :)

**Comment by dixudx** [comment]
ping @fejta  @bgrant0607 @brendandburns @dchen1107 @wojtek-t
Rebased. PTAL. Thanks.

**Comment by dixudx** [comment]
ping @bgrant0607 @smarterclayton for approval. Thanks.

**Pull request merged**
