### PR TITLE
Adding SIG owners for GPU e2es

### PR DESCRIPTION
**Pull request by vishh**
cc @davidopp @mindprince

### CODE REVIEW

**Comment by mindprince** [comment]
This seems to contain unrelated changes.

**Comment by vishh** [comment]
Sorry. Base branch had a commit. Fixed

**Review by rohitagarwal003 — APPROVED** [review]

**Comment by grodrigues3** [comment]
@vishh sorry to be a pain, but for consistency with our owners mechanism a few people suggested we use subdirectories to indicate ownership.  Instead of the comments, can you move the tests to

**test/e2e/[scheduling](https://github.com/kubernetes/kubernetes/tree/master/test/e2e/scheduling)** to indicate they should be owned by scheduling.

**Pull request closed without merging**
