### PR TITLE
Update topology tests for windows

### PR DESCRIPTION
**Pull request by jingxu97**
Update storage topology tests setup for Windows

Change-Id: I9a2773b91806a10553db06f61f7259db4df71c3b

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jingxu97** [comment]
assign @Jiawei0227

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
