### PR TITLE
genericapiserver: cut off more dependencies – episode 3

### PR DESCRIPTION
**Pull request by sttts**
Compare commit subjects.

This is the first step to get `apiserver_test.go` and `watch_test.go` in `pkg/genericapiserver/endpoints` cutoff from k8s.io/kubernetes dependencies.

After this we have to sync client-go and then "episode 4" can go in.

approved based on #40363

### CODE REVIEW

**Comment by deads2k** [comment]
```

httpstream - fine
trace.go - i think we're better off with a copy in the long run (weird dependency we'll have to cut later), but its ok
split fuzzer - definitely in favor of the change, I think we can go further, but if this solves your immediate need its a fine starting point
api/resource - you deleted all package content, just left a doc.go right?
move semantic - this global should probably be coupled to an individual scheme instead, right?

```

**Comment by sttts** [comment]
@deads api/resource: I left a copy to make the cyclic appc/spec dep working. When appc is updated, we can delete that.

**Comment by sttts** [comment]
Will take another look at "move semantic", good point.

**Comment by deads2k** [comment]
> @deads2k api/resource: I left a copy to make the cyclic appc/spec dep working. When appc is updated, we can delete that.

Once this merges you'll make the pull upstream?  After this merges, update the package to be .readonly.  Also, can you remove everything but what appc is using?

**Comment by sttts** [comment]
Yes, will create a PR upstream to change the dependency.

**Comment by jayunit100** [comment]
Thanks ! For the record we need this to import dependencies transitively from the scheduler into other projects.

**Comment by sttts** [comment]
@jayunit100 upstream already removed the dependency by copying our Quantity implementation. So I will bump the godep.

**Comment by sttts** [comment]
@k8s-bot cvm gke e2e test this

**Comment by sttts** [comment]
@dgonyeo @s-urbaniak commit 4 and 5 lgty?

**Comment by sttts** [comment]
@k8s-bot bazel test this issue #40295

**Comment by sttts** [comment]
@deads2k semantic equality belongs into a scheme, I agree. Right now, it is independent from any scheme, but of course the equality funcs are fixed. Follow-up ok?

**Comment by sttts** [comment]
@deads2k appc/spec is bumped to the latest version, which cuts the cyclic dependency. Godep still complains if `pkg/api/resource` is gone. So I left yet another `doc.go` there.

**Comment by sttts** [comment]
@k8s-bot test this

**Comment by sttts** [comment]
@deads2k ptal

**Comment by deads2k** [comment]
lgtm

**Comment by deads2k** [comment]
api.Semantic should be per scheme eventually.

**Comment by s-urbaniak** [comment]
The bump and refactor in the rkt-kubelet LGTM, thanks! /cc @lucab @squeed

**Comment by dgonyeo** [comment]
Posthumous comment: You should probably update the appc/spec dependencies added here to point to a tagged release commit the next time one is made, as this set the dependency to a commit between releases.

**Pull request merged**
