### PR TITLE
Automated cherry pick of #60125: Add clusterid tags to the instances in AWS tests

### PR DESCRIPTION
**Pull request by chen-anders**
Cherry pick of #60125 on release-1.9.

#60125: Add clusterid tags to the instances in AWS tests

### CODE REVIEW

**Comment by jpbetz** [comment]
/hold
Hold all unmerged cherrypicks for cut of patch release on Monday.

**Comment by vainu-arto** [comment]
Does someone know why the CLA label is missing? Is there a way to trigger the bot to retry? Alternatively can someone add the label manually to get this merged?

**Comment by cblecker** [comment]
Closing and reopening to try and trigger CLA bot

**Comment by cblecker** [comment]
The context is passing. Manually applying label.

**Pull request merged**
