### PR TITLE
Automated cherry pick of #66863: attachdetach controller: attach volumes immediately when

### PR DESCRIPTION
**Pull request by cofyc**
Cherry pick of #66863 on release-1.10.

#66863: attachdetach controller: attach volumes immediately when

### CODE REVIEW

**Comment by cofyc** [comment]
cc @saad-ali for approval

**Comment by MaciekPytel** [comment]
@cofyc @saad-ali This needs to be reviewed today to make it into 1.10.7.

**Comment by MaciekPytel** [comment]
/hold
Freezing branch 1.10.7

**Pull request merged**
