### PR TITLE
Upload kubeconfig to master metadata in tests.

### PR DESCRIPTION
**Pull request by mm4tt**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test

/kind feature

> /kind flake

**What this PR does / why we need it**:
Till a few days ago, it was possible to ssh into master and access cluster via insecure master port.
Now, the master insecure port has been disabled, we're not able to do that anymore.

This PR aims to fix that by uploading the kubeconfig to the master metadata during cluster setup in tests.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mm4tt** [comment]
/hold 
WIP, will ping once I fix the issues

**Comment by mm4tt** [comment]
/hold cancel

Should be good now.

**Comment by mm4tt** [comment]
Once this is in, kubeconfig will be accessible via cloud ui or gcloud command
eEd3JsZrfTr

**Comment by cjcullen** [comment]
This feels a little gross, but is probably fine to do for tests.

/lgtm

**Comment by wojtek-t** [comment]
Given lgtm from security side, I'm approving this one.
/approve

**Pull request merged**
