### PR TITLE
Dont attach a GPU to ubuntu test machines for node e2e serial tests

### PR DESCRIPTION
**Pull request by dashpole**
This should fix flakes in the e2e_node serial suite.

@vishh I think this is what you were asking for...

/assign @vishh

### CODE REVIEW

**Comment by dashpole** [comment]
@k8s-bot pull-kubernetes-unit test this
@k8s-bot pull-kubernetes-kubemark-e2e-gce test this

**Comment by cmluciano** [comment]
@vishh Do you want me to create an issue for enabling these tests on Ubuntu?

**Comment by vishh** [comment]
Yeah. An issue will be useful. I'd like to get help from the Canonical team
on enabling GPU e2es without much disruption to other tests.

**Pull request merged**
