### PR TITLE
fixtodo:Add TestValidateMutatingWebhookConfiguration for mutating webhooks

### PR DESCRIPTION
**Pull request by hanxiaoshuai**
**What this PR does / why we need it**:
fixtodo:Add TestValidateMutatingWebhookConfiguration to test validation for mutating webhooks
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
There is a TODO: Add TestValidateMutatingWebhookConfiguration to test validation for mutating webhooks. So I add the unit test
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hanxiaoshuai** [comment]
cc @hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
I donot see any difference between `ValidateValidatingWebhookConfiguration` and `ValidateMutatingWebhookConfiguration`. Maybe we should remove this TODO.

**Pull request closed without merging**
