### PR TITLE
ipvs: add descriptions to ipset unit tests

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kiman@vmware.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Adds naming to ipset unit tests so it's easier to debug 

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/assign @lbernail
/sig network
/area ipvs
/priority backlog

### CODE REVIEW

**Comment by lbernail** [comment]
Thanks for this, output is much cleaner now
/lgtm

**Comment by m1093782566** [comment]
/approve

Thanks!

**Pull request merged**
