### PR TITLE
[WIP]implement first version of kube-proxy via ipvs

### PR DESCRIPTION
**Pull request by mqliang**
This implement the first version of ipvs based kube-proxy , using seesaw's [ipvs](https://github.com/google/seesaw/tree/master/ipvs) package to talk with ipvs.
### Requirements
- [libnl](https://www.infradead.org/~tgr/libnl/) - There is a compile and runtime dependency on libnl:

```
apt-get install libnl-3-dev libnl-genl-3-dev
```

kube-proxy also expects a few kernel modules to be loaded:
- ip_vs - IP Virtual Server module. Used to handle transport layer switching within the Linux kernel.
- nf_conntrack_ipv4 - Used by the Linux kernel to maintain the state of all logical network connections and relate packets to the sessions.

BTW, Is there any scripts I should update to install [libnl](https://www.infradead.org/~tgr/libnl/) and the ip_vs kernel modules on each node?

@bprashanth Mind to spend some time to take a look and give some instruction?

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30134)

### CODE REVIEW

**Comment by bprashanth** [comment]
@thockin @kubernetes/sig-network 
@mqliang thanks for the prototype. I haven't taken a close look yet but from what I recall see-saw wouldn't work on cloud providers because vms are not on the same L2 network. Does this prototype also have the same limitation?

**Comment by mqliang** [comment]
@bprashanth 
> I haven't taken a close look yet but from what I recall see-saw wouldn't work on cloud providers because vms are not on the same L2 network. Does this prototype also have the same limitation?

No. I just use seesaw's ipvs package(which then use netlink by libnl) to communicate with kernel

**Comment by bprashanth** [comment]
I guess the easiest way to confirm would be to get on a vm and implement a poor mans service vip with the same rules the seesaw's `AddService` method comes up with. I think we should be fine as long as it doesn't rely on the mac address for eg: dsr style loadbalancing.

**Comment by mqliang** [comment]
@bprashanth I also look through the [GORB](https://github.com/kobolog/gorb) project, it actually use [gnl2go](https://github.com/kobolog/gorb) (which is a ipvs lib in go using Linux Generic Netlink Sockets to work with ipvs). [gnl2go](https://github.com/kobolog/gorb) has no compile and runtime dependency on [libnl](https://www.infradead.org/~tgr/libnl/) since it use Netlink Sockets, but seesaw's ipvs package is much more powerful.

**Comment by girishkalele** [comment]
cc @MrHohn  who was looking into IPVS

**Comment by bprashanth** [comment]
I'm going to hold off on reviewing this till I have some time to play around with seesaw and get more familiar with the specifics. Anyone else should feel free to jump on it if they have cycles.

**Comment by bprashanth** [comment]
@kubernetes/rh-networking might have people familiar with ipvs who have cycles now

**Comment by smarterclayton** [comment]
When I looked at this a few months back I started with this route - seesaw did so much more that I had some concerns about losing focus on the goal.  Seesaw integration is interesting but also more complex.

It's worth asking about our design goals for service IPs.  Do they grow up to something like maglev?  Or is being able to easily plug and play the local proxy more important (because everyone has different SDNs, network requirements, latency trade offs, and security policies to apply)?

**Comment by smarterclayton** [comment]
Sorry, I meant "seesaw as a project was fairly interesting" vs "seesaw library vs gnl2go".  I preferred the pure go approach of gnl2go but was concerned about the level of testing and code structure I saw there - the latter may have some growing pains.

**Comment by smarterclayton** [comment]
This looks roughly what I expected at the top level.  Weee you able to validate you got clean backend failover when a node went down?

**Comment by bprashanth** [comment]
> Weee you able to validate you got clean backend failover when a node went down?

I think the question is does this give us the ability to handle the health of our backend pool based on observed traffic? I think ipvsadm is pretty dumb, it has a bunch of algorithms that help route traffic sendto a vip. Routing daemons like keepalived maintain a set of checkers, the output of which control ipvs' server table, much like kube-proxy and iptables. 

@mqliang does this patch give us something closer to the latter? Not having to wait for the readiness probe failure to reroute traffic would be great. 

I was somewhat hopeful about the ipvs loadbalancing algorithm "sed". I though it would count backend failure as infinite delay, but from some high level testing that wasn't the case. Maybe I misconfigured.

**Comment by smarterclayton** [comment]
I asked it that way because it's the thing end users see.  Even if
IPVS was a wash on everything else, if a connection refused went to
another backend it would be significantly better than what we have in
iptables.

I agree we need better health check observation in general as per your
proposal for the local checkers.

**Comment by knobunc** [comment]
We've been playing with a splice() implementation in the userspace proxy.  We're still testing the performance, and it shows a definite improvement over the old behvior, but may not be as good as the iptables performance.

**Comment by boynux** [comment]
Any updates regarding this feature? I'm really interested in the implementation of LVS in Kuberenetes. If there is anything that I can do to speed up the development and review process please let me know.

**Comment by mqliang** [comment]
@boynux The reason this PR is in WIP status is because I use seesaw's [ipvs](https://github.com/google/seesaw/tree/master/ipvs) package to talk sync ipvs configuration, which has a [libn](https://www.infradead.org/~tgr/libnl/) compile and runtime dependency, so we need to update some build/deploy scripts.

I am recently trying to use a pure go approach of netlink(github.com/vishvananda/netlink/nl) to talk with ipvs kernel module. Unfortunately, I am not a netlink expert, if you are familiar with netlink(for example, know how to construct a "ipvsadm --restore" netlink request), it will definitely help a lot to speed up the development process.

**Comment by mqliang** [comment]
@boynux On a side note, libnetwork have a netlink ipvs package we could leverage on, see https://github.com/docker/libnetwork/tree/master/ipvs . But unfortunately, it only has Create/Update/Delete methods for ipvs Service and Destination, missing Get methods. netlink request for Get is not hard to construct actuallt, but it's challenging to parse the netlink response.

**Comment by boynux** [comment]
@mqliang cool, I'll have look.

**Comment by mqliang** [comment]
close this favor of https://github.com/kubernetes/kubernetes/pull/38817, which use [gnl2go](github.com/tehnerd/gnl2go), a pure go netlink based ipvs lib.

**Comment by quinton-hoole** [comment]
We have a tested implementation of IPVS kubeproxy in https://github.com/kubernetes/kubernetes/issues/44063
Busy tying the various related issues and PR's together now.

**Comment by dhilipkumars** [comment]
@mqliang We have implemented Get Methods in libnetwork. Would be great to get your feedback
https://github.com/docker/libnetwork/pull/1770

**Pull request closed without merging**
