### PR TITLE
cadvisor is obsoleted so kubelet service does not require it.

### PR DESCRIPTION
**Pull request by aveshagarwal**

### CODE REVIEW

**Comment by vmarmol** [comment]
LGTM, thanks! Will merge on green.

**Comment by ddysher** [comment]
wait, totally out of context.. cAdvisor is obsolete?  Aren't we still create cAdvisor in kubelet, is it replaced by docker stats?

**Comment by aveshagarwal** [comment]
The reason for this change is that kubelet does not depend upon cadvisor running as a separate systemd service any more, as kubelet has it inbuilt now.

**Comment by vmarmol** [comment]
@ddysher "obsolete" as in "no longer running as a standalone service" :)

**Comment by kelseyhightower** [comment]
@vmarmol So there is no need to install cadvisor if the kubelet is installed.

**Comment by vmarmol** [comment]
@kelseyhightower that is correct (assuming a new enough Kubelet)

**Comment by ddysher** [comment]
@vmarmol @aveshagarwal Thanks!

**Comment by KostyaSha** [comment]
Can cadvisor be installed without kubernetes?

**Comment by vishh** [comment]
Yes. Kubelet does not require a separate cadvisor container.

**Comment by KostyaSha** [comment]
On centos 7 if i want install cadvisor package in installs kubernetes and then says `Package cadvisor-0.4.1-0.3.git6906a8ce.el7.x86_64 is obsoleted by kubernetes-1.0.0-0.8.gitb2dafda.el7.x86_64 which is already installed` . Does it mean that cadvisor as package can't exist itself?

**Comment by vishh** [comment]
AFAIK we do not maintain cadvisor packages. We recommend using the binaries
published on github or using our docker images.

**Pull request merged**
