### PR TITLE
Improved the quality of output when the test fails

### PR DESCRIPTION
**Pull request by NikhilSharmaWe**
#### What type of PR is this?
Enhancement

#### What this PR does / why we need it:
Improved the quality of output when the test fails
#### Which issue(s) this PR fixes:

Part of #105678 

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pohly** [comment]
@NikhilSharmaWe: there are syntax errors in this PR.

**Comment by dims** [comment]
@NikhilSharmaWe will you be revisiting this PR? or can we close it?

**Comment by NikhilSharmaWe** [comment]
@dims Apologies for the inconvenience , I will keep better track of my PR's in future.

**Pull request closed without merging**
