### PR TITLE
fix etcd compaction doc

### PR DESCRIPTION
**Pull request by sanwishe**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

etcd compaction runs every 5 mintues， not 10 mintues.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
"NONE"
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by yangjunmyfm192085 — COMMENTED** [review]
/ok-to-test

**Review by yangjunmyfm192085 — COMMENTED** [review]
/cc @wojtek-t

**Comment by dims** [comment]
/approve

(just changes in text, no code change)

**Pull request merged**
