### PR TITLE
refactor:use const instead of hard code pluginName in unit test

### PR DESCRIPTION
**Pull request by linyouchong**
use const instead of hard code pluginName in unit test

### CODE REVIEW

**Comment by rootfs** [comment]
I would rather keep tests as they are. These unit tests are expected to verify the plugin names are really in use. Replacing them with variables loses such test coverage.

**Comment by linyouchong** [comment]
I make this PR because I found that later added volume plugin use variables rather than hard code.
e.g.  https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/local/local_test.go
If it is not appropriate to do this, I will close this PR

**Pull request closed without merging**
