### PR TITLE
Add missing API groups to 1.4 client

### PR DESCRIPTION
**Pull request by wongma7**
SOrry, fat-fingered enter key without adding a description

@caesarxuchao doing the steps outlined here https://github.com/kubernetes/kubernetes/pull/32502#issuecomment-248733799

fixes https://github.com/kubernetes/kubernetes/issues/33096

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33851)

### CODE REVIEW

**Comment by wongma7** [comment]
@caesarxuchao I am addressing https://github.com/kubernetes/kubernetes/issues/33096 for 1.4 api groups. not sure if you got the ping because I had to edit the original comment.

I have one question left, this would put the master branch's release-1.4 clientset behind the release-1.4 branch's client, is that okay?

**Comment by caesarxuchao** [comment]
The changes LGTM.

> I have one question left, this would put the master branch's release-1.4 clientset behind the release-1.4 branch's client, is that okay?

Right. I think it's ok. I was thinking of running client-gen for the release-1.4 clientset in the master branch,  then I realized it was a bad idea, because types might had changed since we cut the release, so let's leave it as it is.

**Comment by caesarxuchao** [comment]
@k8s-bot ok to test

**Comment by caesarxuchao** [comment]
> I have one question left, this would put the master branch's release-1.4 clientset behind the release-1.4 branch's client, is that okay?

@wongma7, I talked with @lavalamp, and we think that will be a problem. If later we make another change the 1.4 clientset in the master branch, we wont' be able to cherry-pick that back.

So we devised a more complicated process: 
1. on the master branch, checkout the revision where we cut the 1.4 branch (this is to make sure the types.go are the same as those in the 1.4 branch), run update-codegen.sh to update 1.4 clientset 
2. replace the 1.4 clientset in the HEAD of master branch with the generated 1.4 clientset, send a PR.
3. use the hack/cherry_pick_pull.sh to generate a cherrypick against the 1.4 branch; download the cherrypick PR to the local machine, run copy.sh to update the staging area, and push the commit to the cherrypick PR.

Sorry for making you jump through hoops. Let me know if the process makes sense.

**Comment by wongma7** [comment]
OK, make sense, will do. No problem, I am happy to see this through.

**Comment by lavalamp** [comment]
@wongma7 thanks for being our guinea pig here. We haven't had to do a cherry pick sequence for the client-go repo yet, which is why this is hard. :) Please let us know if you run into any problems with the steps @caesarxuchao gave.

**Pull request closed without merging**
