### PR TITLE
Let verify/integration upload to the correct artifact path

### PR DESCRIPTION
**Pull request by krzyzacy**
will try to make it path for both python and podutil version

/hold
/sig testing
/kind cleanup
/release-note-none
/priority important-soon

### CODE REVIEW

**Comment by ixdy** [comment]
looks like it failed in the right way at least?

**Comment by krzyzacy** [comment]
ohhhh boy... any clue what's actuallly failing?

**Comment by krzyzacy** [comment]
ok not too bad: 
1. `error: unable to read directory "/go/bin" in your PATH: open /go/bin: no such file or directory`
2. need to port golint
3. `fatal: Not a valid object name /master` need to figure out why `master` becomes `/master`

**Comment by krzyzacy** [comment]
https://github.com/kubernetes/kubernetes/blob/b1aed1593e5c22a5f7fa4890fc87808dca9ad9e1/pkg/kubectl/cmd/plugin/plugin.go#L113-L118

let's get this in and will open another one for fixes

/release-note-none
/hold cancel
/skip

**Comment by krzyzacy** [comment]
@ixdy I think that's because `$GOPATH/bin` does not exist and that check decides to give an error. (I didn't see we hard-code /go which is good)

**Comment by krzyzacy** [comment]
oh, we probably want to make the dir before https://github.com/kubernetes/test-infra/blob/master/images/kubekins-e2e/Dockerfile#L27

**Pull request closed without merging**
