### PR TITLE
Implementing ImageManager to take over image lifecycle.

### PR DESCRIPTION
**Pull request by vmarmol**
This is the first step in implementing GC of images. This has the functionality for both untagged images as well as unused images.

### CODE REVIEW

**Comment by vmarmol** [comment]
Assigning @dchen1107

**Comment by vmarmol** [comment]
Adding some extra context from discussions with @dchen1107 

Untagged images can be created in a few ways
- A newer version of the tag is made available (from a build or a pull)
- A build's output is not tagged (not run with `-t`)
- Manually untagged

When Docker is building/pulling an image it does not tag them until the build/pull is complete. Thus we see the current layer being built/pulled as an untagged image. Once that layer is built/pulled and the next layer is started, the old layer is no longer seen as an untagged image but rather a parent image of the current image (which is now considered untagged). That is why in this PR we assume that an untagged image that is more than 2hrs old is very unlikely to be in the process of a build/pull since a single layer shouldn't take that long to build/pull.

Since Kubernetes uses tagged images there is no way for an application to ask to use an untagged image [1]. This means that once an image is untagged, no Kubernetes application will use it. This makes it safe to remove from the Kubernetes perspective. For users who are logging in and building untagged images, I think it is sensible for us to ask them to tag them :) we won't break them if they don't, we will just remove them in 2hrs

My plan is to GC old untagged images every ~10min and GC unused tagged images only when we need space.

[1] OK there is one way I could think of, which involves the user specifying the raw image ID as their image. This will only work if I already know the raw image ID will actually be on the machine. This is probably not a use case anyone has, and if someone does it we should probably discourage it.

**Comment by erictune** [comment]
update Godeps in separate PR please.

**Comment by vmarmol** [comment]
@erictune I thought the policy was in a separate commit no? I think I've gotten complaints both ways :) Either way, happy to do and sending a PR your way.

**Comment by pmorie** [comment]
@ncdc @bparees

**Comment by dchen1107** [comment]
Separate commit for Godeps should be fine.

**Comment by dchen1107** [comment]
I am still not comfortable with removing untagged one. I think you are going to run into exact the same issue we had with the first version of image gc: some image intermediate layers during pulling will be removed, which cause image_not_found issue later when run container. Here is the reason in detail

```
+		if time.Since(time.Unix(image.Created, 0)) < maxTimeAllowedUntagged {
+			continue
+		}
```

In above code you check image.Created to decide if you can remove that untagged image layers. image. Created is the timestamp when that image first time created and pushed to the repository. For example, I just inspect kubernetes:pause image on my newly build cluster:

```
root@kubernetes-minion-2ren:/var/log# docker inspect 6c4579af347b | grep Created
    "Created": "2014-07-19T07:02:32.267701596Z",
```

**Comment by dchen1107** [comment]
Ok further prove my theory, I quickly did this experimental:

on terminal 1:
```
root@kubernetes-minion-2ren:/var/log# while true; do images=$(docker images -f "dangling=true" -q); for image in $images; do echo $image; docker inspect $image | grep Created; done; sleep 1; done
67b66f26d423
    "Created": "2014-10-01T20:41:22.205967397Z",
25c4824a5268
    "Created": "2014-10-01T20:41:22.934462634Z",
8b1c48305638
    "Created": "2014-10-01T20:41:23.303381521Z",
c900195dcbf3
    "Created": "2014-10-01T20:41:47.709802643Z",
6b4e8a7373fe
    "Created": "2014-10-01T20:41:48.345033365Z",
6b4e8a7373fe
    "Created": "2014-10-01T20:41:48.345033365Z",
6b4e8a7373fe
....
```
One terminal 2:
```
root@kubernetes-minion-2ren:/var/log# docker pull spotify/cassandra
Pulling repository spotify/cassandra
0286e0913e65: Download complete 
511136ea3c5a: Download complete 
b18d0a2076a1: Download complete 
67b66f26d423: Download complete 
25c4824a5268: Download complete 
8b1c48305638: Download complete 
c900195dcbf3: Download complete 
6b4e8a7373fe: Download complete 
2e4f12cdbd1a: Download complete 
643f3a03d7b8: Download complete 
5e58bba8aa8e: Download complete 
4a7881fdecdd: Download complete 
...
```

From above experimental, you can see your code definitely run into exact the same issue old image gc has. @brendandburns 

Again, I think we should remove unused images from top stack proactively.

**Comment by vmarmol** [comment]
Ah yes you're right. I incorrectly took the creation time to be when the image was loaded and not when it was created/pushed.

Keeping a live cache (while the Kubelet is up) should achieve a similar goal. It won't help if we're in a low-disk situation and the Kubelet restarts. But that is just a +1 to checkpointing :)

Will re-work and send out.

**Comment by ncdc** [comment]
I'm working on adding "pull by digest" support to Docker (https://github.com/docker/docker/pull/11109) to coincide with that feature being added to the v2 Docker registry (https://github.com/docker/distribution/pull/211). The way things are currently working, if you pull an image by digest, it comes in to the Docker daemon as an untagged image. We're discussing the best way to handle images pulled by digest and whether or not they should be considered untagged/dangling, but I did at least want to point out that if we don't change the behavior in my PR, then having Kubernetes automatically remove untagged images would potentially remove images that were recently used and might be used again in the near future.

**Comment by dchen1107** [comment]
@vmarmol when kubelet restart, we could rebuild image_used map from on_disk state anyway.

**Comment by vmarmol** [comment]
That's what I was thinking too :) we will also treat untagged images as any other image. They should age out first if they're not used

**Comment by vmarmol** [comment]
Implemented tracking of images (both creation and usage). We now evict according to least recently used and break ties by first created (so older images get removed before newer ones). We don't handle untagged images any differently, if their usage if what we expect they will be the first to age out. If they're used more along the lines of how @ncdc described they will stick around much longer.

PTAL @dchen1107 :)

**Comment by ncdc** [comment]
FYI I've modified my pull-by-digest branch so images pulled by digest aren't considered dangling any more.

**Comment by vmarmol** [comment]
haha thanks for the heads up @ncdc!

**Comment by dchen1107** [comment]
LGTM overall.

But I still have one concern: Based on today's policy, we decided to remove one image no one is using, but separate routine decides to start a new container with that image. In this case, we might run into the same bad situation? Let me run some quick test to verify this.

**Comment by dchen1107** [comment]
Ok, my quick test shows that concurrently pulling and remove the same image from the TOP LAYER shouldn't run into problems at all.

**Comment by dchen1107** [comment]
@brendandburns any objection on this PR?
@vmarmol Please rabase it so that I can merge. 

LGTM

**Comment by vmarmol** [comment]
Thanks @dchen1107! Rebased and re-pushed.

There may be a race between pull and run in a case where we're on a very small disk and are turning over images very quickly. That seems unlikely. There is also the case of the Kubelet restarting, but we will pull the images we're interested in and that should mark them as "newer" and less likely to be evicted. Maybe we should add a min time in cache before eviction if we're really worried.

**Comment by vishh** [comment]
A point to note is that image garbage collection will be dependent on container garbage collection. This might not be an issue to begin with.

**Comment by dchen1107** [comment]
@vishh very important note. We need to take this into count when integrating ImageManager to kubelet.

**Pull request merged**
