### PR TITLE
Allow at most one pod to mount GCE PD read-write

### PR DESCRIPTION
**Pull request by ghost**
When multiple pods mount the same GCE PD it is acceptable for one pod
to mount a GCE PD as read-write. The rest must be read-only.

### CODE REVIEW

**Comment by swagiaal** [comment]
@k8s-bot test this. git hub issue: #21490

**Comment by lavalamp** [comment]
I actually thought the existing code was correct. I understood that GCE does not allow both read and read-write mounts at the same time. @saad-ali can you confirm?

**Comment by saad-ali** [comment]
> I actually thought the existing code was correct. I understood that GCE does not allow both read and read-write mounts at the same time. @saad-ali can you confirm?

A GCE PD can only be attached to one node as read-write. To attach to more than one node, the PD must be attached to all nodes as read-only.

So, yes, I too think that aligns with the existing code.

**Comment by swagiaal** [comment]
Ah.. my mistake. I thought multiple attachments are allow as long as at most 1 of them is read-write.

**Pull request closed without merging**
