### PR TITLE
[WIP] [DNM] Exclude ~half of node serial tests

### PR DESCRIPTION
**Pull request by ehashman**
Follow-on to #102691.

/sig node

### CODE REVIEW

**Comment by fromanirh** [comment]
OK, let me plan the next step should the current run timeout as well. I'm a bit baffled it stills timeout so let's start from known-good tests and build incrementally.
Considering the [logs of my successfull test runs]() - but they run on baremetal node I have locally:
```
$ xzcat e2e_node.3.log.xz | grep '^\[sig-node' | grep -v Disruptinve
[sig-node] Dockershim [Serial] [Disruptive] [Feature:Docker][Legacy:Docker]
[sig-node] Dockershim [Serial] [Disruptive] [Feature:Docker][Legacy:Docker]
[sig-node] NVIDIA GPU Device Plugin [Feature:GPUDevicePlugin][NodeFeature:GPUDevicePlugin][Serial] [Disruptive]
[sig-node] Node Performance Testing [Serial] [Slow]
[sig-node] POD Resources [Serial] [Feature:PodResources][NodeFeature:PodResources]
[sig-node] [Feature:DynamicKubeletConfig][NodeFeature:DynamicKubeletConfig][Serial][Disruptive]
[sig-node] Restart [Serial] [Slow] [Disruptive] [NodeFeature:ContainerRuntimeRestart]
[sig-node] [Feature:DynamicKubeletConfig][NodeFeature:DynamicKubeletConfig][Serial][Disruptive]
[sig-node] [Feature:DynamicKubeletConfig][NodeFeature:DynamicKubeletConfig][Serial][Disruptive]
[sig-node] Dockershim [Serial] [Disruptive] [Feature:Docker][Legacy:Docker]
[sig-node] GarbageCollect [Serial][NodeFeature:GarbageCollect]
[sig-node] [Feature:DynamicKubeletConfig][NodeFeature:DynamicKubeletConfig][Serial][Disruptive]
[sig-node] [Feature:DynamicKubeletConfig][NodeFeature:DynamicKubeletConfig][Serial][Disruptive]
[sig-node] NodeProblemDetector [NodeFeature:NodeProblemDetector] [Serial]
[sig-node] Resource-usage [Serial] [Slow]
[sig-node] LocalStorageCapacityIsolationQuotaMonitoring [Slow] [Serial] [Disruptive] [Feature:LocalStorageCapacityIsolationQuota][NodeFeature:LSCIQuotaMonitoring]
[sig-node] Downward API [Serial] [Disruptive] [NodeFeature:DownwardAPIHugePages]
[sig-node] SystemNodeCriticalPod [Slow] [Serial] [Disruptive] [NodeFeature:SystemNodeCriticalPod]
[sig-node] LocalStorageCapacityIsolationQuotaMonitoring [Slow] [Serial] [Disruptive] [Feature:LocalStorageCapacityIsolationQuota][NodeFeature:LSCIQuotaMonitoring]
[sig-node] Topology Manager [Serial] [Feature:TopologyManager][NodeFeature:TopologyManager]
[sig-node] [Feature:DynamicKubeletConfig][NodeFeature:DynamicKubeletConfig][Serial][Disruptive]
[sig-node] Density [Serial] [Slow]
[sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial]
[sig-node] ContainerLogRotation [Slow] [Serial] [Disruptive]
[sig-node] Node Container Manager [Serial]
[sig-node] PodPidsLimit [Serial]
[sig-node] POD Resources [Serial] [Feature:PodResources][NodeFeature:PodResources]
[sig-node] [Feature:DynamicKubeletConfig][NodeFeature:DynamicKubeletConfig][Serial][Disruptive]
[sig-node] Node Performance Testing [Serial] [Slow]
[sig-node] [Feature:DynamicKubeletConfig][NodeFeature:DynamicKubeletConfig][Serial][Disruptive]
[sig-node] CriticalPod [Serial] [Disruptive] [NodeFeature:CriticalPod]
[sig-node] Node Performance Testing [Serial] [Slow]
[sig-node] Density [Serial] [Slow]
[sig-node] POD Resources [Serial] [Feature:PodResources][NodeFeature:PodResources]
[sig-node] [Feature:DynamicKubeletConfig][NodeFeature:DynamicKubeletConfig][Serial][Disruptive]
[sig-node] POD Resources [Serial] [Feature:PodResources][NodeFeature:PodResources]
[sig-node] Dockershim [Serial] [Disruptive] [Feature:Docker][Legacy:Docker]
[sig-node] Docker features [Feature:Docker][Legacy:Docker]
[sig-node] Topology Manager [Serial] [Feature:TopologyManager][NodeFeature:TopologyManager]
[sig-node] Downward API [Serial] [Disruptive] [NodeFeature:DownwardAPIHugePages]
[sig-node] GarbageCollect [Serial][NodeFeature:GarbageCollect]
[sig-node] Topology Manager [Serial] [Feature:TopologyManager][NodeFeature:TopologyManager]
[sig-node] Dockershim [Serial] [Disruptive] [Feature:Docker][Legacy:Docker]
[sig-node] GarbageCollect [Serial][NodeFeature:GarbageCollect]
```
Excluding disruptive tests
```
$ xzcat e2e_node.3.log.xz | grep '^\[sig-node' | grep -v Disruptive
[sig-node] Node Performance Testing [Serial] [Slow]
[sig-node] POD Resources [Serial] [Feature:PodResources][NodeFeature:PodResources]
[sig-node] GarbageCollect [Serial][NodeFeature:GarbageCollect]
[sig-node] NodeProblemDetector [NodeFeature:NodeProblemDetector] [Serial]
[sig-node] Resource-usage [Serial] [Slow]
[sig-node] Topology Manager [Serial] [Feature:TopologyManager][NodeFeature:TopologyManager]
[sig-node] Density [Serial] [Slow]
[sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial]
[sig-node] Node Container Manager [Serial]
[sig-node] PodPidsLimit [Serial]
[sig-node] POD Resources [Serial] [Feature:PodResources][NodeFeature:PodResources]
[sig-node] Node Performance Testing [Serial] [Slow]
[sig-node] Node Performance Testing [Serial] [Slow]
[sig-node] Density [Serial] [Slow]
[sig-node] POD Resources [Serial] [Feature:PodResources][NodeFeature:PodResources]
[sig-node] POD Resources [Serial] [Feature:PodResources][NodeFeature:PodResources]
[sig-node] Docker features [Feature:Docker][Legacy:Docker]
[sig-node] Topology Manager [Serial] [Feature:TopologyManager][NodeFeature:TopologyManager]
[sig-node] GarbageCollect [Serial][NodeFeature:GarbageCollect]
[sig-node] Topology Manager [Serial] [Feature:TopologyManager][NodeFeature:TopologyManager]
[sig-node] GarbageCollect [Serial][NodeFeature:GarbageCollect]
```

From these tests I know pretty well podresources + topologymanager so I'd say start with these combined + few more which seems safe enough. Also let's keep an eye about the execution time, I can't rule out the option "bugs + just too slow" yet.

**Comment by ehashman** [comment]
@fromanirh it was running against master rather than the PR previously per https://github.com/kubernetes/test-infra/pull/22493 -- rerunning now properly to see if it completes

**Comment by fromanirh** [comment]
/test pull-kubernetes-node-kubelet-serial-topology-manager
to get a sense of how much this test alone takes

**Comment by ehashman** [comment]
It ran!! and it only took an hour!

**Pull request closed without merging**
