### PR TITLE
Make upload-to-gcs.sh include BUILD_METADATA_* env vars in started.json.

### PR DESCRIPTION
**Pull request by rmmh**
This is initially intended for storing GCI image versions.

Example output:

```
$ TEST_STARTED_JSON=1 BUILD_METADATA_GCE_IMAGE=m53 \
BUILD_METADATA_VARIANT=reliableforreal BUILD_NUMBER=123 \
WORKSPACE="blaga" JOB_NAME="test-e2e" hack/jenkins/upload-to-gcs.sh
{
  "version": "v1.5.0-alpha.0.806+fa943089125df4-dirty",
  "timestamp": 1473894301,
  "metadata": {
    "gce_image": "m53",
    "variant": "reliableforreal"
  },
  "jenkins-node": ""
}
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32740)

### CODE REVIEW

**Comment by fejta** [comment]
Will you please add a TODO to convert this to python?

Aside from the barbariac use of bash and environment variables instead of python and argument parsing this looks great.

**Comment by wonderfly** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32740#-:-KRf5kOFD07bZ-b9gyKX:bnfp4nl)*

**Comment by ixdy** [comment]
hm, this doesn't really help node e2e or unit/integration with multiple API levels tested.

**Comment by rmmh** [comment]
Woops, this should be touching upload-to-gcs.sh in test-infra!

**Comment by ixdy** [comment]
why do we still have two of those?

**Comment by fejta** [comment]
I think we have a post-step builder that curls it

**Comment by fejta** [comment]
Possibly related to the can't pull multiple repos issue?

**Comment by ixdy** [comment]
looks like some builds are still `curl`ing this one, but should be easy to fix.

**Comment by rmmh** [comment]
Ugh. The e2e-runner image build curls this, too. As far as I can tell, *nothing* uses test-`infra/jenkins/upload-to-gcs.sh`, apart from `fejta-pull`.

**Comment by fejta** [comment]
LGTM

**Comment by rmmh** [comment]
@k8s-bot retest this issue: #31962 #32548

**Comment by rmmh** [comment]
@k8s-bot test this issue: #31962 #32548

**Comment by rmmh** [comment]
@k8s-bot unit test this issue #IGNORE

**Comment by rmmh** [comment]
@k8s-bot test this issue: #31962

**Pull request merged**
