### PR TITLE
replace sync.Mutex with atomic pkg to realize integer arithmetic exclusive

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:
optimize job_controller.go mutual exclusive integer arithmetic
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
atomic low-level atomic memory primitives useful for implementing synchronization algorithms. It is more efficient than higher sync.Mutex
**Release note**:

```release-note
```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@janetkuo could you please review

**Comment by mikedanese** [comment]
godoc for sync/atomic says:

> These functions require great care to be used correctly. Except for special, low-level applications, synchronization is better done with channels or the facilities of the sync package. 

I don't think we want to use it unless there is a large and quantifiable performance improvement.

**Comment by hzxuzhonghu** [comment]
@mikedanese I found this, previously I see this code in [pkg/controller/controller_utils.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/controller_utils.go#L253-L256)
```
// Add increments the add and del counters.
func (e *ControlleeExpectations) Add(add, del int64) {
	atomic.AddInt64(&e.add, add)
	atomic.AddInt64(&e.del, del)
}
```
So I decided to rewrite the mutual exclusive logic use sync/atomic. This may not have obvious performance improvements.

**Pull request closed without merging**
