### PR TITLE
Manual-cherry-pick-for-1.22: kubeadm: apply registry.k8s.io changes

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

manual, kubeadm scoped backport of:
https://github.com/kubernetes/kubernetes/pull/109938
https://github.com/kubernetes/kubernetes/pull/110343

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/kubeadm/issues/2671

#### Special notes for your reviewer:

it is essentially a feature backport, as discussed with k8s-infra and sig-release

https://kubernetes.slack.com/archives/C2C40FMNF/p1666723622759119
https://github.com/kubernetes/kubeadm/issues/2671#issuecomment-1290991218

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: use the image registry registry.k8s.io instead of k8s.gcr.io for new clusters. During upgrade, migrate users to registry.k8s.io if they were using the default of k8s.gcr.io.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
/approve

**Review by pacoxu — APPROVED** [review]
/lgtm
/approve

**Comment by pacoxu** [comment]
Pull image failed in e2e:
> Oct 27 12:44:53 kind-control-plane kubelet[285]: E1027 12:44:53.404880     285 remote_image.go:114] "PullImage from image service failed" err="rpc error: code = NotFound desc = failed to pull and unpack image \"registry.k8s.io/kube-scheduler:v1.22.16-rc.0.9_50a72fa1cb5b4a\": failed to resolve reference \"registry.k8s.io/kube-scheduler:v1.22.16-rc.0.9_50a72fa1cb5b4a\": registry.k8s.io/kube-scheduler:v1.22.16-rc.0.9_50a72fa1cb5b4a: not found" image="registry.k8s.io/kube-scheduler:v1.22.16-rc.0.9_50a72fa1cb5b4a"

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubeadm/pull/2705 
I remembered that we changed kubeadm for this registry name migration. 
Not sure if it is related.

**Review by BenTheElder — COMMENTED** [review]
/lgtm

**Comment by BenTheElder** [comment]
the release note might need to note the build changes as well

**Comment by BenTheElder** [comment]
we're going to need a prominent notice more generally though

**Review by SataQiu — COMMENTED** [review]
/lgtm
/approve

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
/hold

need to wait the other CP for the other branches get approved so we can merge all

**Comment by neolit123** [comment]
> /hold
> 
> need to wait for the other CP for the other branches to get approved so we can merge all or that is not required in this case?

https://github.com/kubernetes/kubernetes/pull/113388
https://github.com/kubernetes/kubernetes/pull/113395

need /build/

**Comment by puerco** [comment]
#113395 is still failing one test :(

**Comment by neolit123** [comment]
> this is good to merge?

yez

**Comment by neolit123** [comment]
@pacoxu @SataQiu 
this broke the upgrade ci job, but the kubeadm upgrade itself should be fine.
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1-22-1-23

i think the problem is in kinder and how it prepulls images begore upgrade. if you can have a look it would be great. if not i can have a look at monday.

**Comment by pacoxu** [comment]
I remembered that we have a trick change in kinder.

https://github.com/kubernetes/kubeadm/blob/36c79748f78f226da5402eae51d0fb3cca619a6a/kinder/pkg/cri/host/archive.go#L94

Should we fix it in kinder after all cherry-picks are merged? (Currently, only the v1.22 cherry-pick is merged, and https://github.com/kubernetes/kubernetes/pull/113395 and https://github.com/kubernetes/kubernetes/pull/113393 are still open.)

**Comment by neolit123** [comment]
> Should we fix it in kinder after all cherry-picks are merged? 

yes, i think we should fix kinder to be "at least" 1.22. otherwise our upgrade jobs will fail.

**Pull request merged**
