### PR TITLE
cluster/addons: add labels to fluentd owner files

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:
this PR adds SIG labels to fluentd OWNER files:
- cluster/addons/fluentd-elasticsearch/OWNERS
- cluster/addons/fluentd-gcp/OWNERS

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
let me know if the labels need adjustment.

**Release note**:

```release-note
NONE
```

/assign @roberthbailey @mikedanese 
/cc @timothysc 
/sig gcp
/sig instrumentation
/kind cleanup

### CODE REVIEW

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Comment by cblecker** [comment]
/milestone v1.12
OWNERS change that increases documentation.

**Pull request merged**
