### PR TITLE
podresource-api: getAllocatableResources to Beta

### PR DESCRIPTION
**Pull request by swatisehgal**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Move the getAllocatableResources endpoint in podresource-api to beta.

#### Special notes for your reviewer:
Issue link: Extend podresources API to report allocatable resources https://github.com/kubernetes/enhancements/issues/2403

#### Does this PR introduce a user-facing change?

```release-note
Move the getAllocatableResources endpoint in podresource-api to the beta that will make it enabled by default.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
 [KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/2403-pod-resources-allocatable-resources/README.md
```

### CODE REVIEW

**Comment by fromanirh** [comment]
these two fixes should land before we move to beta, both posted from quite some time:
https://github.com/kubernetes/kubernetes/pull/103289
https://github.com/kubernetes/kubernetes/pull/104123
@ehashman I'm not sure about the process: should we add the above two fixes to the 1.23 milestone?

**Comment by swatisehgal** [comment]
Thanks Kevin and Francesco.

/assign @derekwaynecarr
for `pkg/features` changes

**Comment by swatisehgal** [comment]
Thank @dims!

**Pull request merged**
