### PR TITLE
Move discovery endpoint package into discovery/unaggregated

### PR DESCRIPTION
**Pull request by Jefftree**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Move discovery package into discovery/unaggregated to prepare for aggregated discovery. This reduces the size and # files changed on the next PR.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
it's not clear why this needs to move... we lose file history, etc, when we do this. can the aggregated bits go in `discovery/aggregated` instead?

**Comment by Jefftree** [comment]
Hmm that's a good point. I was trying to separate this into `discovery/aggregated` and `discovery/unaggregated` so the original package can be used for a handler for the root `apis` endpoint that will determine which handler to send to request to based on the content negotiation. We could probably put that into a new package instead to preserve file history

**Pull request closed without merging**
