### PR TITLE
hairpin ipset could only contain local endpoints

### PR DESCRIPTION
**Pull request by honkiko**
**What this PR does / why we need it**:
Currently all endpoints in the cluster are inserted into the hairpin ipset KUBE-LOOP-BACK.  This ipset is only for local hairpin traffic. No need to take all endpoints in the cluster.

There may be scaling problem if we have all endpoints in the ipset.  By only take local ones, we get slightly less memory consumption, faster matching and faster updating.
 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Review by Lion-Wei — APPROVED** [review]
I think this is a good optimization, thanks.

**Comment by Lion-Wei** [comment]
@m1093782566 , PTAL

**Comment by m1093782566** [comment]
> This ipset is only for local hairpin traffic. No need to take all endpoints in the cluster.

That's not true. Suppose Service A is cluster-wide and people still have chance to access the endpoints in the same host as kube-proxy. If we don't put the endpoints into the LOOP-BACK ipset, there would be a hairpin issue.

**Comment by m1093782566** [comment]
/hold

for discussion.

**Comment by m1093782566** [comment]
I think I almost lost this thread.

I thought hard about it and seems it's a good optimism. So, we can merge this PR now.

/lgtm
/approve

**Comment by honkiko** [comment]
waiting for mergeable time window?

**Pull request merged**
