### PR TITLE
kubeadm: fix typos in  code comments

### PR DESCRIPTION
**Pull request by mysunshine92**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
 /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mysunshine92** [comment]
ping @yagonobre

**Review by yagonobre — COMMENTED** [review]
Thanks!
/lgtm
/ok-to-test
/kind cleanup
/priority backlog

**Comment by ereslibre** [comment]
Thank you @mysunshine92!

Nit: please, prefix the commit message with `kubeadm:` and possibly state in the commit description/message that it's fixing code comments. The PR description could have more information as well.

**Comment by mysunshine92** [comment]
cc @neolit123 
please add an approved label, thanks.

**Review by neolit123 — COMMENTED** [review]
/approve

**Pull request merged**
