### PR TITLE
bump etcd version to 2.2.1 in Makefile

### PR DESCRIPTION
**Pull request by mikedanese**
Please validate that the image looks good.

ref #16618
cc @dchen1107

### CODE REVIEW

**Comment by mikedanese** [comment]
Image is pushed

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
Are you going to update master's etcd server manifest file to test against your newly pushed image?

**Comment by mikedanese** [comment]
I believe @jbeda is planning on doing that.

**Comment by a-robinson** [comment]
Manual merge while merge-bot is down due to a single flake from a known issue.

**Comment by dalanlan** [comment]
yay

**Comment by luxas** [comment]
Good to have a newer version :)

**Pull request merged**
