### PR TITLE
cherry pick of #95269: fix the panic when kubelet registers if a node object already exists with no Status.Capacity or Status.Allocatable

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Cherry pick of #95269 on release-1.19.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix the panic when kubelet registers if a node object already exists with no Status.Capacity or Status.Allocatable
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by NicolasT — APPROVED** [review]

**Review by TeddyAndrieux — APPROVED** [review]

**Comment by dims** [comment]
@cpanato this is ready for cherry-pick approval.

**Comment by NicolasT** [comment]
In our experience this only affects 1.19, not 1.18 or 1.17, at least we don't run into the issue when following the same 'scenario' which *does* cause breakage in 1.19.

Looking at Git history, it appears the code causing #95188 was introduced in 283082744235 which landed in `v1.19.0-beta.2`.

**Comment by dims** [comment]
@cpanato from @NicolasT 's analysis, we should be good. @SataQiu please confirm.

**Comment by SataQiu** [comment]
Thanks for the detailed analysis, and I agree with @NicolasT 
This panic is caused by `reconcileHugePageResource` which was landed in v1.19.0-beta.2.
So we cherry-pick this to 1.19 should be ok.
/cc @dims @cpanato

**Comment by cpanato** [comment]
@dims @NicolasT we discussed this in this 🧵 https://kubernetes.slack.com/archives/CJH2GBF7Y/p1606841299338600 we will not cherry-pick this right now also because the main PR is not merged yet as well.

this will be cherry-picked asap.

**Comment by dims** [comment]
thanks @cpanato thanks for catching that!

**Comment by NicolasT** [comment]
Now #95269 is merged, can this cherry-pick be approved? :pray:

**Comment by SataQiu** [comment]
ping @cpanato

**Comment by cpanato** [comment]
@SataQiu i will review early next week

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
/triage accepted

from parent PR
/priority important-soon

**Pull request merged**
