### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by d-kuro**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fixed typo

**Which issue(s) this PR fixes**:

Fixes # N/A

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by yagonobre — COMMENTED** [review]
Thanks @d-kuro
/priority backlog
/ok-to-test
/lgtm

**Review by fabriziopandini — APPROVED** [review]
/approve
Merge will be deferred to after release cut

**Pull request merged**
