### PR TITLE
Bump cAdvisor to v0.50.0

### PR DESCRIPTION
**Pull request by cwangVT**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Bump to the latest cAdvisor release v0.50

Changelog - https://github.com/google/cadvisor/compare/v0.49.0...v0.50.0

Release notes - https://github.com/google/cadvisor/releases/tag/v0.50.0

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```
Bump cAdvisor to v0.50.0
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cwangVT** [comment]
From the discussion with @dims: 

This is our very first `exclude` in go.mod, @liggitt do you have a better way to do this?

**Comment by liggitt** [comment]
Uh… why do we need the exclude?

**Comment by liggitt** [comment]
We cannot use `exclude`. From go docs:

> exclude directives only apply in the main module’s go.mod file and are ignored in other modules. See [Minimal version selection](https://go.dev/ref/mod#minimal-version-selection) for details.

That means the version resolution kubernetes and our libraries build and test with will be different than the version selected / built by components using our libraries. 

Are there details/discussions of why this PR is adding `exclude`?

**Comment by cwangVT** [comment]
> We cannot use `exclude`. From go docs:
> 
> > exclude directives only apply in the main module’s go.mod file and are ignored in other modules. See [Minimal version selection](https://go.dev/ref/mod#minimal-version-selection) for details.
> 
> That means the version resolution kubernetes and our libraries build and test with will be different than the version selected / built by components using our libraries.
> 
> Are there details/discussions of why this PR is adding `exclude`?

@dims and @akhilerm may have more context here.

We are bumping cAdvisor version on k/k. 

And when updating dependency on k/k, we got the errors like:

```
go: k8s.io/kubernetes/cmd/kubelet/app/options imports
    github.com/google/cadvisor/container/containerd imports
    github.com/containerd/containerd/api/services/containers/v1: ambiguous import: found package github.com/containerd/containerd/api/services/containers/v1 in multiple modules:
    github.com/containerd/containerd v1.4.9 (/.../kubernetes/_output/local/go/cache/mod/github.com/containerd/containerd@v1.4.9/api/services/containers/v1)
    github.com/containerd/containerd/api v1.7.19
(/.../kubernetes/_output/local/go/cache/mod/github.com/containerd/containerd/api@v1.7.19/services/containers/v1)
```

(Those imports are introduced in this commit in cadvisor: https://github.com/google/cadvisor/commit/3152233d32099c66570f6ffb557d047ecd7c8601)

We found that add the `exclude` can fix the issue. But according to what you said, that is not the best solution. 

Do you have a better way to fix the ambiguous import error above?

**Comment by BenTheElder** [comment]
/hold

> Remove s390x support by @bobbypage in https://github.com/google/cadvisor/pull/3485

This seems like a big deal, since Kubernetes / kubelet still supports s390x AFAIK ..?

**Comment by dims** [comment]
@akhilerm there are 3 flags there in total from what i can tell:

https://github.com/kubernetes/kubernetes/blob/aab56e9b70b7d80f2a5a5f2907e172de257662b5/vendor/github.com/google/cadvisor/container/containerd/factory.go#L34-L37

If we can figure out a way to specify them using alternate means or decide that we really don't need them .. then we should be good

**Comment by bobbypage** [comment]
> /hold
> 
> Reading the release notes:
> 
> > Remove s390x support by @bobbypage in [google/cadvisor#3485](https://github.com/google/cadvisor/pull/3485)
> 
> This seems like a big deal, since Kubernetes / kubelet still supports s390x AFAIK ..?

This was dropping the docker build for s390x for cAdvisor, it doesn't affect anything for k8s.

**Comment by liggitt** [comment]
ok... so... we're in gridlock...

1. cadvisor started referencing the carved out github.com/containerd/containerd/api module in v0.50.0
2. that means that we either have to eliminate github.com/containerd/containerd from our graph completely or update to a version new enough that it excludes the carved out github.com/containerd/containerd/api
   * Updating to a containerd version that carves out the API submodule (v1.7.19+ - https://github.com/containerd/containerd/blob/v1.7.19/go.mod#L15) isn't doable because it *also* adds dependencies on k8s.io staging libraries - https://github.com/containerd/containerd/blob/v1.7.19/go.mod#L79-L84
   * I *think* eliminating github.com/containerd/containerd from our graph completely means dropping it from github.com/Microsoft/hcsshim:
     ```
     go mod graph | grep " github.com/containerd/containerd@"
     github.com/Microsoft/hcsshim@v0.8.26 github.com/containerd/containerd@v1.4.9
     ```

     which does not seem feasible (hcsshim uses containerd in almost 100 places):
     ```
     hcsshim$ git grep "github.com/containerd/containerd" | grep \.go | grep -v vendor | wc -l
     98
     ```

     or dropping our use of github.com/Microsoft/hcsshim (used in 4 files in k/k, I don't know how feasible this is)

* We can't update github.com/containerd/containerd past v1.4.x (so a 2-year-old version) because v1.5.0+ adds a go.mod which surfaces the loopback dependency on k8s.io staging libraries
* We can't update github.com/microsoft/hcsshim past v0.8.26 (so a 3-year-old version) because v0.9.0+ pulls in containerd/containerd v1.5.x+
* We can't update cadvisor to v0.50.0 because it depends on the carved out containerd/containerd/api module which is ambiguous about which containerd module provides that package until we update containerd/containerd to v1.7.19+ (which we can't do) or eliminate containerd/containerd entirely

**Comment by dims** [comment]
@BenTheElder note from slack

image

**Comment by BenTheElder** [comment]
slack is at https://kubernetes.slack.com/archives/CHGFYJVAN/p1722559235435279?thread_ts=1722556541.361709&cid=CHGFYJVAN

though it's not clear where we can track

**Comment by cwangVT** [comment]
/hold

Will wait for https://github.com/microsoft/hcsshim/issues/2236

**Comment by kiashok** [comment]
> ok... so... we're in gridlock...
> 
> 1. cadvisor started referencing the carved out github.com/containerd/containerd/api module in v0.50.0
> 2. that means that we either have to eliminate github.com/containerd/containerd from our graph completely or update to a version new enough that it excludes the carved out github.com/containerd/containerd/api
>    
>    * Updating to a containerd version that carves out the API submodule (v1.7.19+ - https://github.com/containerd/containerd/blob/v1.7.19/go.mod#L15) isn't doable because it _also_ adds dependencies on k8s.io staging libraries - https://github.com/containerd/containerd/blob/v1.7.19/go.mod#L79-L84
>    * I _think_ eliminating github.com/containerd/containerd from our graph completely means dropping it from github.com/Microsoft/hcsshim:
>      ```
>      go mod graph | grep " github.com/containerd/containerd@"
>      github.com/Microsoft/hcsshim@v0.8.26 github.com/containerd/containerd@v1.4.9
>      ```
>      
>      
>          
>            
>          
>      
>            
>          
>      
>          
>        
>      which does not seem feasible (hcsshim uses containerd in almost 100 places):
>      ```
>      hcsshim$ git grep "github.com/containerd/containerd" | grep \.go | grep -v vendor | wc -l
>      98
>      ```
>      
>      
>          
>            
>          
>      
>            
>          
>      
>          
>        
>      or dropping our use of github.com/Microsoft/hcsshim (used in 4 files in k/k, I don't know how feasible this is)
> 
> * We can't update github.com/containerd/containerd past v1.4.x (so a 2-year-old version) because v1.5.0+ adds a go.mod which surfaces the loopback dependency on k8s.io staging libraries
> * We can't update github.com/microsoft/hcsshim past v0.8.26 (so a 3-year-old version) because v0.9.0+ pulls in containerd/containerd v1.5.x+
> * We can't update cadvisor to v0.50.0 because it depends on the carved out containerd/containerd/api module which is ambiguous about which containerd module provides that package until we update containerd/containerd to v1.7.19+ (which we can't do) or eliminate containerd/containerd entirely

Sent a PR out with updated hcsshim tag: https://github.com/kubernetes/kubernetes/pull/126799

**Comment by dims** [comment]
/close

please see https://github.com/kubernetes/kubernetes/pull/126799

**Pull request closed without merging**
