### PR TITLE
fix typo and format for klog

### PR DESCRIPTION
**Pull request by pandaamanda**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by pandaamanda** [comment]
/assign @msau42 
need /milestone v1.20 to merge?

**Comment by msau42** [comment]
Right now only critical bug fixes are being allowed to 1.20, so we'll have to target 1.21 for this fix.

**Pull request merged**
