### PR TITLE
populate ready replicas and aviable replicas to federated replicaset …

### PR DESCRIPTION
**Pull request by jianhuiz**
populate ready replicas and aviable replicas to federated replicaset status

@nikhiljindal #33312
#29481 #32771

@deepak-vij

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36602)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
@mwielgus Assigning this to you since you wrote this code.
Thanks @jianhuiz !

**Comment by nikhiljindal** [comment]
Also adding to 1.5 milestone.
cc @saad-ali as FYI.
This is a bug fix. We added a few fields to replicaset status, but do not set it in federation replicaset. This PR fixes that.

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by saad-ali** [comment]
> Also adding to 1.5 milestone.
> cc @saad-ali as FYI.
> This is a bug fix. We added a few fields to replicaset status, but do not set it in federation replicaset. This PR fixes that.

Ack, thanks!

**Comment by dims** [comment]
@k8s-bot cvm gke e2e test this

**Comment by mwielgus** [comment]
LGTM

**Pull request merged**
