### PR TITLE
/pkg/client/listers: fix some typo

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test
/release-note-none
/lgtm

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by zjj2wry** [comment]
@k8s-bot verify test this

**Comment by cblecker** [comment]
@zjj2wry: verify test is a real failure, not a flake. please investigate.

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-verify test this

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-verify test this

**Comment by cblecker** [comment]
@zjj2wry Please check the test results before re-testing. Again, the `pull-kubernetes-verify` errors are legitimate errors.

You can also run `make verify` locally to check for these errors in your local environment.

**Comment by zjj2wry** [comment]
@cblecker i will check it next time. think you ~

**Pull request merged**
