### PR TITLE
Fix comments and function names are different

### PR DESCRIPTION
**Pull request by xichengliudui**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by SataQiu** [comment]
thanks @xichengliudui 
/kind cleanup
/sig testing
/priority backlog
/lgtm

**Comment by xichengliudui** [comment]
cc @SataQiu @yagonobre  
Ref: https://github.com/kubernetes/kubernetes/pull/76019
`#76019` caused so much confusion that I shut it down.

**Comment by yagonobre** [comment]
Thanks @xichengliudui, and sorry for the confusion. 
/remove-sig testing
/assign @neolit123

**Comment by xichengliudui** [comment]
@yagonobre  It was my fault. I'm sorry.

**Review by neolit123 — COMMENTED** [review]
/approve

**Pull request merged**
