### PR TITLE
e2e_node: fix nil pointer exception under quota lsci test

### LINKED ISSUE #106377: Node e2e tests panics trying to set KubeletConfig
### Which jobs are flaking?

https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial&width=5

### Which tests are flaking?

Seen in this job failing on multiple tests, this is just one of the stack traces

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106371/pull-kubernetes-node-kubelet-serial/1459076579521990656/

```
E2eNode Suite: [sig-node] LocalStorageCapacityIsolationQuotaMonitoring [Slow] [Serial] [Disruptive] [Feature:LocalStorageCapacityIsolationQuota][NodeFeature:LSCIQuotaMonitoring] when we run containers that should cause use quotas for LSCI monitoring (quotas enabled: false) should eventually evict all of the correct pods expand_less | 11s
-- | --
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/util.go:165 Test Panicked /usr/local/go/src/runtime/map_faststr.go:204  Panic: assignment to entry in nil map  Full stack: k8s.io/kubernetes/test/e2e_node.runOneQuotaTest.func1.1(0xc00003d400) 	_output/local/go/src/k8s.io/kubernetes/test/e2e_node/quota_lsci_test.go:69 +0x133 k8s.io/kubernetes/test/e2e_node.tempSetCurrentKubeletConfig.func1() 	_output/local/go/src/k8s.io/kubernetes/test/e2e_node/util.go:171 +0xc3 k8s.io/kubernetes/test/e2e_node.TestE2eNode(0x409659) 	_output/local/go/src/k8s.io/kubernetes/test/e2e_node/e2e_node_suite_test.go:187 +0x765 testing.tRunner(0xc00012f6c0, 0x55f10c0) 	/usr/local/go/src/testing/testing.go:1259 +0x102 created by testing.(*T).Run 	/usr/local/go/src/testing/testing.go:1306 +0x35a

```

### Since when has it been flaking?

it seems that for a long time :smile: https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial&width=5

### Testgrid link

https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial&width=5

### Reason for failure (if possible)

it panics here https://github.com/kubernetes/kubernetes/blob/c98b388a847f84019609f6422b4ab00b89c4603c/test/e2e_node/util.go#L171

I don't have a good understanding of those tests mechanics, but it seems a complex setup embedding functions and goroutines before the test setup, I suggest to move to something more simple 

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by cynepco3hahue**
#### What type of PR is this?

/kind failing-test
/kind bug

#### What this PR does / why we need it:

Initialize feature gates KubeletConfig section if it is nil.

#### Which issue(s) this PR fixes:

Fixes #106377

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Comment by pacoxu** [comment]
> Test name	Commit	Details	Required	Rerun command
> pull-kubernetes-node-kubelet-serial	[cf2f21d](https://github.com/kubernetes/kubernetes/commit/cf2f21dd3ec7b14bbf7d597de7e4702d5902dde3)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106408/pull-kubernetes-node-kubelet-serial/1459822195130765312/)	false	`/test pull-kubernetes-node-kubelet-serial`

The failure is #105686.

/test pull-kubernetes-node-kubelet-serial

**Review by pacoxu — APPROVED** [review]
/lgtm

**Comment by ehashman** [comment]
flake https://github.com/kubernetes/kubernetes/issues/105686

**Review by ehashman — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
