### PR TITLE
Make naming of kubectl subcommands consistent

### PR DESCRIPTION
**Pull request by ghodss**
Some of the kubectl subcommands do not respect the convention we have across the rest of the CLI interface, specifically that words are separated by dashes. Specifically, this PR changes `rollingupdate` to `rolling-update`, `clusterinfo` to `cluster-info`, and `apiversions` to `api-versions`. If there's somewhere we can document this as a conventions, please point me to it and I can update it.

### CODE REVIEW

**Comment by thockin** [comment]
I am on a phone, so not reviewing at the moment.  Is this a compatible
change or breaking?

**Comment by ghodss** [comment]
Breaking. I don't know of a way to continue to support the old versions in parallel that doesn't make things really messy. You could abstract the relevant cobra commands and add them twice under two different names, though that would also make both new and old names show up when you run `kubectl help`.

I do think we need to not delay doing this since we should set and stick to the convention now before 1.0 when we can't change it at all. These are also fortunately three of the less-oft-used commands so IMO the change is unfortunate but acceptable at this point.

**Comment by thockin** [comment]
Is supporting both old and new at the same time such a bad answer?

**Comment by vmarmol** [comment]
Assigning @thockin, feel free to re-assign.

**Comment by bgrant0607** [comment]
At minimum, a breaking change would need to be pre-announced on kubernetes-announce.

What commands adhere to this convention now? Just port-forward and run-container, which almost nobody even knows about? I'd guess that rollingupdate is more widely used than those.

FWIW, our resource types (e.g., replicationcontroller) are not hyphenated.

**Comment by bgrant0607** [comment]
It looks like cobra does support command aliases:
https://github.com/spf13/cobra/blob/master/command.go#L38

**Comment by bgrant0607** [comment]
Users shouldn't need to worry about what's hyphenated and what's not hyphenated. How about we make the canonical names hyphenated for readability, but also support unhyphenated forms, and potentially abbreviations as well?

**Comment by ghodss** [comment]
> It looks like cobra does support command aliases

I missed that - I will add aliases to make this a non-breaking change.

> What commands adhere to this convention now? Just port-forward and run-container, which almost nobody even knows about? I'd guess that rollingupdate is more widely used than those.

This is more about the future than the present. As we add more commands we should follow a convention, and already all of our command line parameters and half our subcommands follow hyphens, so I propose we keep that.

> Users shouldn't need to worry about what's hyphenated and what's not hyphenated. How about we make the canonical names hyphenated for readability, but also support unhyphenated forms, and potentially abbreviations as well?

I like the git way of doing this - have only one built-in way of doing it, and allow people to configure custom aliases in their .kubectlcfg files. I think we should add these aliases for backwards compatibility for now, announce that we're deprecating them, and eventually remove them by 1.0. Otherwise it's just too much cruft in the long run to juggle several aliases for every subcommand.

**Comment by thockin** [comment]
I'm fine with aliasing and deprecating.

**Comment by bgrant0607** [comment]
@jlowdermilk re. protocol for deprecating commands in kubectl

**Comment by jlowdermilk** [comment]
I think the nice way to deprecate commands is to have the deprecated command issue a warning but continue working for at least one release. This gives a window to fix up tests/scripts/documentation/etc that use the command before it breaks

**Comment by ghodss** [comment]
This is no longer a breaking change. Using the old version prints a deprecation warning but still works.

This is ready for review - the implementation of the deprecation warning is not abstract, but it's because cobra doesn't tell us the actual command that was run (that I could tell), and automatically extracting the right param that matches the command that is being run is non-trivial. If anyone can see a better way to do it I'm happy to implement it.

Likely the right long-term solution is to port this into cobra itself, but for now since this code hopefully only needs to be in here for a couple releases, and we shouldn't be needing to do rename subcommands like this too often in the future, this seems sufficient.

**Comment by bgrant0607** [comment]
LGTM. Thanks for making it non-breaking.

**Pull request merged**
