### PR TITLE
Automated cherry pick of #44053 #44313

### PR DESCRIPTION
**Pull request by thockin**
Cherry pick of #44053 #44313 on release-1.6.

#44053: Add tests for kube-proxy healthcheck, fix bug
#44313: Zero-out healthchecks when no endpoints

```release-note
Fix corner-case with OnlyLocal Service healthchecks
```

### CODE REVIEW

**Comment by thockin** [comment]
This brings in the rest of #44053

**Review by MrHohn — APPROVED** [review]
LGTM

The failures seem to be introduced by commit 2a6083c3e73ac997a164d481f2857a17a6d1a8d1, which is not in 1.6.

**Comment by MrHohn** [comment]
Sorry, the commits seem a bit weird to me...Why we have two federation commits in the middle?

**Comment by freehan** [comment]
Need to clean those federation commits. This is generally caused by reverts in HEAD.

**Pull request merged**
