### PR TITLE
Change Oom to OOM

### LINKED ISSUE #14434: "Oom" should be "OOM" or "oom"
We have a number of symbols that use the "Oom" denotation and others that use "OOM".   This is an acronym, not a word, and as per Go style rules should be consistent-case, not first-letter-caps.

e.g.

`type OomAdjuster`, `ApplyOomScoreAdj`, `NewOomAdjuster`

### PR DESCRIPTION
**Pull request by liguangbo**
fix #14434 
@thockin

### CODE REVIEW

**Comment by liguangbo** [comment]
There are two things need take another look.
1. Oom in `pkg/kubelet/oom_watcher` line 52 `EventOom` rely on cAdvisor. I didn't change it.
2. I didn't change Godeps Oom.

**Comment by vishh** [comment]
LGTM

**Comment by vishh** [comment]
ok to test

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
Jenkins GCE e2e failures shouldn't be caused by this pr.

ok to test

**Comment by liguangbo** [comment]
@vishh I reopened the PR, but it can't restart the e2e. 
image
I think it wasn't caused by PR.
Thanks.

**Comment by brendandburns** [comment]
@k8s-bot test this please

@k8s-bot ok to test

**Pull request merged**
