### PR TITLE
Dual stack tests: cover hostnetwork endpoints on dual stack

### PR DESCRIPTION
**Pull request by fedepaol**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This creates a test similar to "should function for service endpoints using hostNetwork" for dual stack tests, using the secondary clusterip / nodeip.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
tests are passing
>  Kubernetes e2e suite: [sig-network] [Feature:IPv6DualStackAlphaFeature] [LinuxOnly] Granular Checks: Services Secondary IP Family should function for service endpoints using hostNetwork

failure on `pull-kubernetes-e2e-kind-ipvs-dual-canary` is unrelated
/lgtm
/assign @MrHohn

**Review by MrHohn — APPROVED** [review]
/approve

**Pull request merged**
