### PR TITLE
fix spelling mistakes

### PR DESCRIPTION
**Pull request by tanshanshan**
**What this PR does / why we need it**:
fix spelling mistakes
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
/assign @thockin 
for approval

**Comment by thockin** [comment]
Are there going to be more of these spelling PRs?  Can we get one mondo PR with all of them?

**Pull request merged**
