### PR TITLE
coreos/azure: Kubernetes version bump to 0.17, various other fixes

### PR DESCRIPTION
**Pull request by errordeveloper**
- Bump CLI tools version to 0.9.2
- Add curl wrapper as Azure DNS seems flaky
- Bump to 0.17
- Bump CoreOS image IDs
- Update docs URL
- Fix permissions
- Always restart Weave services (coreos/bugs#334)

### CODE REVIEW

**Comment by errordeveloper** [comment]
I haven't update the outputs the outputs of `kubectl` in the documentation, but promise to that on 1.0 :)

**Comment by errordeveloper** [comment]
ping @jeffmendoza @erictune @roberthbailey @kelseyhightower

**Comment by errordeveloper** [comment]
This should close #8159.

**Comment by roberthbailey** [comment]
@errordeveloper thanks for the change (and sorry I didn't get to reviewing it sooner). Travis and Shippable are both failing, so I just restarted shippable. Can you squash your commits before I merge?

**Comment by errordeveloper** [comment]
@roberthbailey ok, rebased.

**Comment by roberthbailey** [comment]
LGTM. Travis and shippable both failed so I kicked them (since it doesn't seem like these changes should have broken unit/integration tests). 

FYI there is currently a merge freeze in place (see #8534) so this won't be merged until that is lifted.

**Comment by errordeveloper** [comment]
Looks like #8534 is closed now and all tests are green :+1:

**Pull request merged**
