### PR TITLE
Add description check for spaces around omitempty directive

### PR DESCRIPTION
**Pull request by pmorie**
Saw someone doing this in a review earlier today so I added a check for it.

@mikedanese @eparis I'm asking myself how this could be running given line 72 in this diff.  Am I nuts?

cc @bgrant0607

### CODE REVIEW

**Comment by bgrant0607** [comment]
Good catch. We've been bit several times by silent failures in this script. I'm guessing the if statement eats the non-zero exit code.

cc @nikhiljindal @caesarxuchao

**Comment by bgrant0607** [comment]
Probably we should explicitly verify that the types files exist.

**Comment by pmorie** [comment]
@bgrant0607 I'll add a check to ensure the files all exist.

**Comment by pmorie** [comment]
@bgrant0607 yep, what's happening is that the pipeline for internal files eats the exit code, and we don't check `PIPESTATUS`

**Comment by pmorie** [comment]
@k8s-bot test this
@k8s-bot unit test this

**Comment by pmorie** [comment]
@bgrant0607 updated to check for the existence of internal types files

**Comment by bgrant0607** [comment]
LGTM, thanks

**Pull request merged**
