### PR TITLE
replace golang.org/x/exp/inotify with standalone library

### LINKED ISSUE #68478: gonum.org/v1/gonum module conflicts with use of golang.org/x/exp/inotify
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

the `gonum.org/v1/gonum` module as a whole depends on `golang.org/x/exp/rand`, which has been introduced after `golang.org/x/exp/inotify` (which we depend on) was retired.

We are currently "lucky" in the sense that the subset of `gonum.org/v1/gonum` we use actually doesn't depend on `golang.org/x/exp`, so that we get away with using an outdated version of golang.org/x/exp by virtue of the fact that godep doesn't track any of this.

Go modules are not that forgiving though, and the current situation is not a valid solution to the system of constraints they consider. Therefore this issue blocks a migration to go modules.

**What you expected to happen**:

The dependency graph should be more consistent

**Anything else we need to know?**:

`inotify` is a can of worms, and past migrations to the maintained `fsnotify` have been repeatedly reverted. It's unclear that there is an easy way out.
Arguably the path of least resistance would be to properly fork the old `inotify` codebase into a standalone package, that both `kubelet` and `cadvisor` can depend on without holding back other parts of the dependency graph. Then migration to `fsnotify` can proceed at its own pace.

### PR DESCRIPTION
**Pull request by sigma**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

The inotify code was removed from golang.org/x/exp several years ago. Therefore
importing it from that path prevents downstream consumers from using any module
that makes use of more recent features of golang.org/x/exp.

This change is a followup to google/cadvisor#2060 which was merged with #70889

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes #68478

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/ok-to-test

we need this in 1.13  since cadvisor has already moved to it

/milestone v1.13

**Comment by mikedanese** [comment]
If we are creating a fork just for k8s.io/kubernetes (e.g. nothing in staging/ needs it), we usually drop code in https://github.com/kubernetes/kubernetes/tree/master/third_party/forked

**Comment by dims** [comment]
@mikedanese cadvisor needs it

**Comment by mikedanese** [comment]
ok, thanks.

**Comment by vishh** [comment]
@dims we should prioritize switching to https://github.com/fsnotify/fsnotify in the next release given that the existing library is unmaintained (unless we (k8s community) take on ownership).
Would it make sense to create a third_party folder for cAdvisor as well instead of the current approach?

**Comment by dims** [comment]
@vishh the last time we tried things broke - https://github.com/google/cadvisor/pull/1807 someone has to go back and see if we can do something in fsnotify (or figure out if it has been fixed since)

**Comment by dims** [comment]
@vishh am ok with adding a third_party/ in cadvisor repo if there is enough time  ( cc @dashpole )

**Comment by dashpole** [comment]
@dims I have bandwidth to review PRs and cut a new release

**Comment by sigma** [comment]
out of curiosity, what's the expected benefit of having that code in 2 third_party locations?
I'm still trying to figure out how we approach forking in general, it all feels very ad-hoc so far :)

**Comment by vishh** [comment]
It is indeed ad-hoc (unless it is documented somewhere and I'm oblivious to
it). My understanding (and as @mikedanese mentioned earlier), we generally
fork dependencies that need to be forked (deleted, unmaintained) into
either third_party directory, or to a separate repo in k8s organization if
active development is expected (recent fork of glog is an example here).
@dims are you aware of any formal process?

**Comment by cblecker** [comment]
/approve
/hold

I'm good with this PR as is, but if we change direction to something in third_party, I'd like to re-review.

**Comment by vishh** [comment]
@thockin are we ok with taking on third party forks of deleted official golang repositories as dependencies?

**Comment by AishSundar** [comment]
@sigma @dims @vishh is this critical for 1.13? we are in code freeze and if possible, I would like to defer this until 1.14. let me know otherwise

/remove-priority critical-urgent

**Comment by sigma** [comment]
@AishSundar personally I don't mind if it's pushed out. It should hopefully be a functionally neutral change, as the code in the old and new package is identical (it's slightly uglier not to merge it since said code is currently duplicated)

**Comment by nikopen** [comment]
@dims what do you think about this one?

**Comment by dims** [comment]
@nikopen i'd prefer that this gets in so k/k and cadvisor repos are in sync.  (won't be terrible if it does not happen)

**Comment by cblecker** [comment]
I think we should just go ahead with this path as it's deduping to code that is already vendored. We can look in 1.14 if we want to move to fsnotify. At this point, this would just ensure that we don't have conflicting versions with cadvisor.

/hold cancel

**Comment by nikopen** [comment]
/priority critical-urgent

for merging

needs an approval

**Comment by cblecker** [comment]
Manually approving for the kubelet. We're only changing the package import path to use the existing vendored code, but at a different path.

**Pull request merged**
