### PR TITLE
Fix strategic merge patch input mutation leading to broken PATCH retry logic

### PR DESCRIPTION
**Pull request by sttts**
`mergeMap` is in-place, i.e. modifies the input. A number of derived funcs are therefore in-place as well. This broke the retry logic of the PATCH handler. It applied the given patch to the original object and cached the `originalObjMap` for later retries. But this `originalObjMap` was modified and all retries afterwards failed.

This PR also moves @liggitt's integration test from OpenShift to kube which uncovered this issue.

It's not 100% clear whether this bug has any inconsistency implications anywhere. It seems that the PATCH handler worked fine, but retries were broken.

This is a candidate for 1.6.

### CODE REVIEW

**Comment by ncdc** [comment]
Jordan has a pull just like this

**Comment by ncdc** [comment]
#43871

**Comment by sttts** [comment]
@ncdc thanks for the link. Should have known this 2h ago, missed the mail for the PR it seems :-/

**Comment by liggitt** [comment]
superceded by https://github.com/kubernetes/kubernetes/pull/43871

**Pull request closed without merging**
