### PR TITLE
Revert "Audit use buffered backend"

### PR DESCRIPTION
**Pull request by tallclair**
Reverts kubernetes/kubernetes#60237

Fixes https://github.com/kubernetes/kubernetes/issues/60719#issuecomment-370025956

See https://github.com/kubernetes/kubernetes/issues/60719#issuecomment-370024193 for rollforward steps.

```release-note
NONE
```

### CODE REVIEW

**Comment by tallclair** [comment]
Oops, the github revert button did not work as I expected. Do we have an automated rollback flow? Should I delete this PR (and branch) and open a PR out of my fork?

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/60727)

**Comment by crassirostris** [comment]
Thanks for the PR!

I'm OK with merging it, but I think it's better to fix tests. As I've mentioned in https://github.com/kubernetes/kubernetes/issues/60719#issuecomment-370363151, it should work, including large clusters

**Comment by liggitt** [comment]
/unassign
will let @tallclair weigh in on whether this is required for 1.10 now

**Comment by tallclair** [comment]
Closing this since https://github.com/kubernetes/kubernetes/pull/60794 fixed the tests.

**Pull request closed without merging**
