### PR TITLE
Refactor gec-pd to seperate builder and cleaner

### LINKED ISSUE #9139: Volume plugins Builder/Cleaner can be type-asserted incorrectly
For many of the volume plugins, we do something like:

```
func NewBuilder(...) volume.Builder {
  return &whatever {
      name: ...
      type: ...
      path: ...
  }
}

func NewCleaner(...) volume.Cleaner {
  return &whatever {
      name: ...
  }
}
```

Specifically we return the same type but only partially filled in (since we only have partial info at Cleaner time).  Unfortunately, Go will let you type-assert a Cleaner to a Builder in this case.  But calling Builder methods WILL NOT WORK.

Instead, we should have distinct types for whateverBuilder and whateverCleaner that embed a common core which implements volume.Plugin.

@markturansky

### PR DESCRIPTION
**Pull request by jiangyaoguo**
Resolves  #9139 for gce-pd.

### CODE REVIEW

**Comment by jiangyaoguo** [comment]
@thockin @markturansky @pmorie

**Comment by saad-ali** [comment]
Thanks for the PR @jiangyaoguo. There have been a bunch of changes, could you please rebase.

**Comment by jiangyaoguo** [comment]
@saad-ali Have rebased. Hope for reviews.

**Comment by thockin** [comment]
lgtm

**Comment by saad-ali** [comment]
LGTM

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Pull request merged**
