### PR TITLE
Change persistentDisk to gcePersistentDisk for v1beta3

### LINKED ISSUE #3785: v1beta3: GCE PD is JSON "persistentDisk"
As long as we have it in the API, it should maybe be renamed to gcePersistentDisk ?

### PR DESCRIPTION
**Pull request by brendandburns**
@thockin @bgrant0607 
Closes #3785

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM

**Comment by thockin** [comment]
I was about to ask about internal, but then I realized - why do we have JSON tags on internal at all?  We should never be reading or writing serialized internal structs...

**Comment by bgrant0607** [comment]
@thockin Just because nobody has bothered to remove them yet AFAIK. I agree that removing the tags would make it clearer that the internal form should not be serialized.

**Comment by thockin** [comment]
Is there an open issue for this?  I'd hate to forget it..

**Comment by bgrant0607** [comment]
Previous discussion was in #1004, IIRC. I'll file a new issue.

**Pull request merged**
