### PR TITLE
Adding OWNERS for federation

### PR DESCRIPTION
**Pull request by nikhiljindal**
Adding OWNERS for the federation dir

cc @kubernetes/sig-cluster-federation

### CODE REVIEW

**Comment by quinton-hoole** [comment]
LGTM

**Comment by philips** [comment]
Where is the file format of the OWNERS file documented?

**Comment by philips** [comment]
Currently OWNERS files docs say it is "not implemented" https://github.com/kubernetes/kubernetes/blob/master/docs/devel/owners.md#owners-files

**Comment by colhom** [comment]
@quinton-hoole @nikhiljindal can I be on this list?

**Comment by quinton-hoole** [comment]
@colhom Sure, want to send me a PR?

**Comment by nikhiljindal** [comment]
@philips: Yes that design (for blocking all changes to a dir until someone in the OWNERS file has approved) is not yet implemented.

My understanding (which could be wrong) is that the bot looks at the OWNERS file to assign PR reviews. That was my understanding after looking at https://github.com/kubernetes/kubernetes/pull/27402.

This is what the [munger README](https://github.com/kubernetes/contrib/blob/88a39c5468e099705386e5b63c2583ed49b79b12/mungegithub/README.md) says:
```
blunderbuss - assigned PRs to individuals based on the contents of OWNERS files in the main repo
```

**Pull request merged**
