### PR TITLE
Adding support for deployments to client library

### PR DESCRIPTION
**Pull request by nikhiljindal**
Ref: #1743

### CODE REVIEW

**Comment by ncdc** [comment]
@ironcladlou @kubernetes/rh-cluster-infra

**Comment by ironcladlou** [comment]
LGTM

**Comment by nikhiljindal** [comment]
Thanks @ironcladlou . Adding the LGTM tag as per the above LGTM

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
sigh fetching git repo failed.

@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
@lavalamp save me!
Without any code change, the tests have passed 2 times and failed 4 times.

**Comment by nikhiljindal** [comment]
Service test timed out which is https://github.com/kubernetes/kubernetes/issues/13478.
Trying again

@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
Its the same service test time out.

@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
Rebased to see if that reduces some flakiness in tests.

**Comment by nikhiljindal** [comment]
Adding the LGTM since it was just a rebase

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by ironcladlou** [comment]
I think @k8s-bot is just messing with you at this point...

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
All tests passed in the last run

Ran 86 of 150 Specs in 674.333 seconds
SUCCESS! -- 86 Passed | 0 Failed | 2 Pending | 62 Skipped 

Not sure why it reported as failure.
Self merging.

**Pull request merged**
