### PR TITLE
Improve the performance when Resource Clone

### PR DESCRIPTION
**Pull request by sourcelliu**
#### What type of PR is this?
/kind cleanup
/sig scheduling

#### What this PR does / why we need it:
Improve the performance when Resource Clone
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by sanposhiho — COMMENTED** [review]
/ok-to-test
/lgtm

👍

**Comment by sanposhiho** [comment]
/assign @damemi

for approval

**Review by damemi — COMMENTED** [review]
/approve

**Pull request merged**
