### PR TITLE
more concise to merge the slice

### PR DESCRIPTION
**Pull request by wgliang**
**What this PR does / why we need it**:
more concise to merge the slice

**Special notes for your reviewer**:

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm

**Comment by wgliang** [comment]
@derekwaynecarr @rootfs PTAL.

**Comment by sttts** [comment]
@deads2k 

for approval.

**Comment by sttts** [comment]
@rootfs this needs your approval

**Pull request merged**
