### PR TITLE
Move pkg/scheduler/algorithm/well_known_labels.go out

### LINKED ISSUE #69138: Move pkg/scheduler/algorithm/well_known_labels.go out
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind cleanup
/sig scheduling

**Description**:

It's better to move `pkg/scheduler/algorithm/well_known_labels.go` to `pkg/scheduler/api/` to avoid dependency cycle.  for example, `pkg/scheduler/algorithm/types.go` includes `schedulercache` which may also dependent on other pkgs.

Should be part of #68951 .

### PR DESCRIPTION
**Pull request by tanshanshan**
**What this PR does / why we need it**:
Move pkg/scheduler/algorithm/well_known_labels.go out
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #69138 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by krmayankk** [comment]
is this also part of the scheduler cleanup ?

**Comment by misterikkit** [comment]
If this fixes an import loop problem, then I am in favor.
/lgtm

Also, these constants are used by several packages outside of scheduler. So removing their dependency on the `algorithm` package is a bonus.

**Comment by tanshanshan** [comment]
I fixed the build error , PTAL @misterikkit

**Comment by misterikkit** [comment]
@tanshanshan Did you mean to close this? If not, please re-open and I will review it.

**Comment by tanshanshan** [comment]
PTAL @misterikkit

**Review by misterikkit — APPROVED** [review]
/lgtm

This is a simple move of some constant strings from a package where they did not belong.

**Comment by misterikkit** [comment]
@k82cn  @bsalamat can one of you approve this one? Afterward, we will seek approval from other SIGs or a global approver.

**Comment by k82cn** [comment]
/approve

Thanks very much for this cleanup :)

**Comment by misterikkit** [comment]
@deads2k  Do you mind giving this a look? It just changes import paths.

**Review by bsalamat — APPROVED** [review]
/lgtm

Thanks, @tanshanshan! I am glad to see this clean-up.

**Comment by misterikkit** [comment]
@derekwaynecarr @deads2k Do you have time to review these simple import changes for controller, kubelet, admission, and test?

**Comment by misterikkit** [comment]
Looks like this needs a rebase.

**Review by misterikkit — APPROVED** [review]
/lgtm

**Pull request merged**
