### PR TITLE
Make kubelet assign a UID if it finds none

### PR DESCRIPTION
**Pull request by thockin**
We can _almost_ disable the "if blank" logic for UID, except for tests that
call APIs that do not run through SyncPods.  We really ought to be enforcing
invariants better.

### CODE REVIEW

**Comment by thockin** [comment]
Awesome.  Integration test fails reliably on Travis, but fails in a TOTALLY different way for me locally.  The output of it is inscrutable, to make things more fun.  This test is a giant waste of time, it is so brittle.

**Comment by erictune** [comment]
It appears that this PR is not ready for review, so not assigning a reviewer.

**Comment by dchen1107** [comment]
I planed to have UID for Pods generated from config files, but didn't get to it. One reason is that once we have Kubelet taking Pod instead of BoundPod, we should invoke the same validation logic and assign the defaults if missing.

**Comment by thockin** [comment]
OK, it seems that the wrong arg to spew included the pointer values.  That fixes integration tests.  I have other feedback to consider before this can be committed, still, so please do not commit yet.

**Comment by bgrant0607** [comment]
What currently happens to pods created via containerVM manifests? Do they have uids?

**Comment by thockin** [comment]
No.  I'm expanding my PR to ensure that pods from all config sources (in
kubelet) have Name, Namespace, UID set propoerly.

**Comment by thockin** [comment]
#3382 supercedes this

**Pull request closed without merging**
