### PR TITLE
changed unused fmt statement to be a log statement

### PR DESCRIPTION
**Pull request by mikedanese**

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by alex-mohr** [comment]
LGTM was before last commit, removing LGTM

**Comment by mikedanese** [comment]
this is why I'm not worried about skynet or the singularity.

**Comment by alex-mohr** [comment]
@k8s-bot test this [testing build queue, sorry for the noise]

**Comment by alex-mohr** [comment]
Automatic merge from SubmitQueue

**Pull request merged**
