### PR TITLE
delete some unused const

### PR DESCRIPTION
**Pull request by lcfang**
**What this PR does / why we need it**:

delete some unused const

fixed the bad url which had been moved to another place.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by cblecker** [comment]
reiterating hold
/hold

**Comment by lcfang** [comment]
Hi @ncdc , I have committed another pr https://github.com/kubernetes/kubernetes/pull/59565 about the solution you commented. Can you have a look and give me some suggestions?

**Comment by ncdc** [comment]
@lcfang will comment over there.

**Pull request closed without merging**
