### PR TITLE
Simplify construction of /metrics request

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This PR simplifies some test code that constructs a request for metrics, as suggested in https://github.com/kubernetes/kubernetes/pull/115259/files#r1097498214 .

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by logicalhan — COMMENTED** [review]
/lgtm
/approve

**Comment by liggitt** [comment]
build issue is https://github.com/kubernetes/test-infra/issues/28655

**Pull request merged**
