### PR TITLE
Use ExpectEqual in e2e/kubectl

### PR DESCRIPTION
**Pull request by k-toyoda-pi**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This makes e2e tests use ExpectEqual() under test/e2e/kubectl.

**Which issue(s) this PR fixes**:
Ref #79686

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by oomichi** [comment]
Thanks for doing this,

/lgtm

**Comment by k-toyoda-pi** [comment]
/assign @monopole
for approval

**Pull request merged**
