### PR TITLE
Update Dashboard UI to version v1.1.1

### PR DESCRIPTION
**Pull request by bryk**
Release tag: https://github.com/kubernetes/dashboard/releases/tag/v1.1.1

Release issue: https://github.com/kubernetes/dashboard/issues/1078

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30273)

### CODE REVIEW

**Comment by bryk** [comment]
@janetkuo How can I cherry-pick it to the 1.3 branch?

**Comment by janetkuo** [comment]
The doc for cherrypick: https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md

Once this PR is cherrypick-approved you use `hack/cherry_pick_pull.sh` script to create another PR against release-1.3. Here's an example https://github.com/kubernetes/kubernetes/pull/30297

**Comment by janetkuo** [comment]
@k8s-bot smoke e2e test this issue: #30331

**Comment by fabioy** [comment]
@bryk Cherrypick approved. Please create a cherrypick PR. Thanks.

**Pull request merged**
