### PR TITLE
Demote some Docker e2e tests to flaky as per #7840

### PR DESCRIPTION
**Pull request by ghost**
Replaces #10904 
@yujuhong @ixdy @wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
The Jenkins failure seems unrelated to this change - LGTM

cc @davidopp for "ok-to-merge" label

**Comment by davidopp** [comment]
LGTM

**Comment by wojtek-t** [comment]
@quinton-hoole - how is it related to #10880 - didn't it fix the problem?

**Comment by quinton-hoole** [comment]
@wojtek-t Yes, you're right.  It has not flaked since #10880, as far as I can tell (barring what look like unrelated DNS errors).   Closing and will re-open if necessary.

**Pull request closed without merging**
