### PR TITLE
Remove HostPort conflict checking.

### PR DESCRIPTION
**Pull request by erictune**
We decided to get rid of boundPods.   Removing this check is
a prerequisite for that.  This check had some value before we had
IP-per-Pod.  However, AIUI, use of HostPort is strongly discouraged
in Kubernetes.  It still exists as part of a Pod spec because
of ContainerVM, where it is used.  But, this change does not affect
ContainerVM, where there is no master.

If someone did create pods with HostPort using kubernetes, the following
would happen:
- The scheduler would try not to put two conflicting pods on the same
  machine (pkg/scheduler/predicates.go : PodFitsPorts() )
- I'm not sure if it is currently possible for a race to occur where
  the PodFitsPorts check were bypassed.   Maybe it could happen.
- If the kubelet was sent conflicting pods, it would detect them in
  ( pkg/kubelet/kubelet.go :  filterHostPortConflicts() ).  It would
  arbitrarily pick one pod to run and another to ignore.
- If all of the above happened and the user filed and issue on github,
  we might figure out that the user used HostPort and tell the user to stop.

TODO:
- e2e test
- Several of the demos in examples/ use hostPort.  Change them to
  not specify hostPort and have a service instead.

### CODE REVIEW

**Comment by erictune** [comment]
Don't merge yet.

I still need to e2e test this, and I predict it will need changes to the examples/ directory in order to get it
to pass e2e reliably, because some examples use hostPort.

**Comment by roberthbailey** [comment]
FYI, I'm working on taking host ports out of the update-demo example.

**Comment by erictune** [comment]
Cleaning up the examples is issue #1487 or #1693 or #4333 or #4267 or #4460

**Comment by erictune** [comment]
Awesome @roberthbailey

**Comment by erictune** [comment]
Once either #4623 or @roberthbailey work is done, then this will definitely be safe to merge.

**Comment by thockin** [comment]
This makes me anxious - HostPorts are a supported (if discouraged) feature and there are some (very rare) cases where it is useful.  If I understand, this means that the only error given to users in case of a conflict is something deep from the bowels of kubelet.  Is that acceptable UX?

**Comment by erictune** [comment]
@thockin see #4623

**Comment by erictune** [comment]
@thockin when that issue is implemented, then the pod will be failed with a helpful reason.  if there is a replication controller then a new instance will be created and the scheduler will hopefully try a different node.

**Comment by lavalamp** [comment]
Does kubelet make an event of the form "can't start pod because hostPort conflicts with X"? it should.

(other concerns addressed IRL conversation)

**Comment by thockin** [comment]
OK, I can buy this.

**Comment by brendandburns** [comment]
I'm ok with this PR (though not removing hostPort for the reasons Tim describes) The scheduler won't allow two pods with hostPort to co-schedule anyway.

Eric did you run e2e?

**Comment by bgrant0607** [comment]
cc @yujuhong

**Comment by erictune** [comment]
I think it is going to make some of the examples flaky. 
So I don't want to submit it yet.

**Comment by bgrant0607** [comment]
All the examples that still have hostPort set (api/examples, I think) should be deleted.

**Comment by erictune** [comment]
Status: 
all the examples except `examples/openshift-origin/resource-generator.sh` don't use `hostPort`.  That example has only one pod instance.  So, we are in good shape there.

@yujuhong is working on making kubelets reject pods that have conflicts, so that will get them rescheduled if they have an RC.

I'll run the e2e on this.

**Comment by erictune** [comment]
Everything passes e2e except guestbook.sh.

**Comment by erictune** [comment]
The guestbook.sh failure appears to be #5268.

**Comment by erictune** [comment]
I think this is ready to merge.

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
