### PR TITLE
Automated cherry pick of #15479 upstream release 1.1

### PR DESCRIPTION
**Pull request by mikedanese**
Automated cherry pick of #15479 upstream release 1.1

Fixes docs/admin component docs

cc @bgrant0607

### CODE REVIEW

**Comment by bgrant0607** [comment]
Please re-run build/versionize-docs.sh

**Comment by mikedanese** [comment]
Reran versionize

**Comment by bgrant0607** [comment]
LGTM, thanks

**Comment by bgrant0607** [comment]
@k8s-bot unit test this

**Comment by bgrant0607** [comment]
Merging.

cc @caesarxuchao

**Pull request merged**
