### PR TITLE
Upgrade snapshot controller to 3.0.0

### PR DESCRIPTION
**Pull request by saikat-royc**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Upgrade snapshot controller to 3.0.0
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by saikat-royc** [comment]
@xing-yang the rbac rule for [customresourcedefinitions](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/volumesnapshots/volume-snapshot-controller/rbac-volume-snapshot-controller.yaml#L46) is not present in https://github.com/kubernetes-csi/external-snapshotter/blob/master/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml. We can remove this now from cluster/addons/volumesnapshots/volume-snapshot-controller/rbac-volume-snapshot-controller.yam?

**Comment by xing-yang** [comment]
> @xing-yang the rbac rule for customresourcedefinitions is not present in https://github.com/kubernetes-csi/external- snapshotter/blob/master/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml. We can remove this now from cluster/addons/volumesnapshots/volume-snapshot-controller/rbac-volume-snapshot-controller.yaml?

I wouldn't want to remove that unless we are sure it is present somewhere else and that it is added before we install snapshot CRDs.

**Comment by saikat-royc** [comment]
> > @xing-yang the rbac rule for customresourcedefinitions is not present in https://github.com/kubernetes-csi/external- snapshotter/blob/master/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml. We can remove this now from cluster/addons/volumesnapshots/volume-snapshot-controller/rbac-volume-snapshot-controller.yaml?
> 
> I wouldn't want to remove that unless we are sure it is present somewhere else and that it is added before we install snapshot CRDs and controller.

Ok. So the current patch with only the image bump is sufficient

**Pull request merged**
