### PR TITLE
fix all grammar and spelling issues in releases of 20210113

### PR DESCRIPTION
**Pull request by pacoxu**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
use grammar check plugin 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm
/triage accepted
/priority backlog

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by pacoxu** [comment]
After 1.21.0-alpha.2, add another two typo fixes here.

**Review by xmudrii — APPROVED** [review]
/lgtm

**Comment by wilsonehusin** [comment]
hmm looks like the 1.21 notes might get overwritten since it's still pre-release right now. for edits on pre-release, can you help us to port the changes on [k/sig-release](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.21/release-notes-draft.md)? the CHANGELOG on k/k came from k/sig-release. we'll need to create the mapping and edits for each entry so it won't get overwritten by automation.

**Comment by wilsonehusin** [comment]
@pacoxu hmm looks like the 1.21 notes might get overwritten since it's still pre-release right now. for edits on pre-release, can you help us to port the changes on k/sig-release? the CHANGELOG on k/k came from k/sig-release. we'll need to create the mapping and edits for each entry so it won't get overwritten by automation.

**Comment by pacoxu** [comment]
ok @wilsonehusin

**Pull request merged**
