### PR TITLE
Revert "Add density (batch pods creation latency and resource) and resource performance tests to `test-e2e-node'"

### PR DESCRIPTION
**Pull request by gmarek**
Reverts kubernetes/kubernetes#29764 as it broke kubernetes-build

### CODE REVIEW

**Comment by wojtek-t** [comment]
It seems that "kubernetes-build" doesn't see the vendor dependency in the original PR.
@kubernetes/test-infra-maintainers

**Comment by ixdy** [comment]
What broke?

**Comment by gmarek** [comment]
kubernetes-build

**Comment by ixdy** [comment]
Are there logs of what broke and how?

**Comment by gmarek** [comment]
3 consecutive kubernetes-build runs? E.g. https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-build/11363

**Comment by ixdy** [comment]
As I noted in #29764, I think the issue is that the PR only builds for linux, not darwin/windows. PR Jenkins only builds for linux.

**Pull request merged**
