### PR TITLE
Move quota usage testing for loadbalancers into unit tests

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Fixes https://github.com/kubernetes/kubernetes/issues/26319
- moved testing for node port and load balancer usage in quota to unit tests
- remove node port and node port -> loadbalancer service testing out of e2e
  - covered already in replenishment_controller_test scenario

Given the time it takes to even allocate a load balancer, it seems better to test that outside of this test case to avoid unnecessary flakes.

/cc @bprashanth

### CODE REVIEW

**Comment by bgrant0607** [comment]
@derekwaynecarr Do you have a preferred reviewer?

**Comment by derekwaynecarr** [comment]
@sdminonne - could you take a pass and then maybe we can have @ncdc review?

@sdminonne - i added a better unit test for service type update here:
https://github.com/kubernetes/kubernetes/pull/26806

**Comment by derekwaynecarr** [comment]
Bumped priority to align with flake priority, looking at jenkins error.

**Comment by sdminonne** [comment]
LGTM, thanks for the fix!

**Comment by ncdc** [comment]
@derekwaynecarr 

> remove node port and node port -> loadbalancer service testing out of e2e
covered already in replenishment_controller_test scenario

replenishment_controller_test only tests the individual *UpdateFuncs. It doesn't actually unit test the replenishment controller. I feel like we're losing some test coverage with this change. Assuming we closed this gap, you're saying that the fact that the replenishment controller sees the updated Service and calls ServiceReplenishmentUpdateFunc is a sufficient replacement for the e2e test cases you're removing?

**Comment by derekwaynecarr** [comment]
@ncdc - I am saying that this change plus https://github.com/kubernetes/kubernetes/pull/26806 provides a sufficient replacement.

**Comment by derekwaynecarr** [comment]
To elaborate, https://github.com/kubernetes/kubernetes/pull/26803/files#diff-90866ff5cb0e94dde7701f2827e8c915L56 provides general coverage for service's being observed by quota and replenished.  #26806 provides coverage for nodeport -> loadbalancer or loadbalancer -> node port service type changes.

**Comment by ncdc** [comment]
Perfect, thanks. LGTM

**Comment by zmerlynn** [comment]
@k8s-bot test this, issue #IGNORE (wondering if I can kick submit queue this way)

**Comment by derekwaynecarr** [comment]
Rebased and pushed to try and make the PR checks happy...

**Comment by yujuhong** [comment]
@k8s-bot node e2e test this issue: #26431

**Pull request merged**
