### PR TITLE
fix typo kubeadm joiń -> kubeadm join

### PR DESCRIPTION
**Pull request by cqy0532**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
fix typo kubeadm joiń -> kubeadm join

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cqy0532** [comment]
I signed

**Review by yagonobre — COMMENTED** [review]
Thanks @cqy0532
/ok-to-test
/lgtm
/priority backlog

**Comment by cqy0532** [comment]
@yagonobre I already CNCF - cla agreement, why label or ` no` ?

**Comment by cqy0532** [comment]
I signed

**Comment by fabriziopandini** [comment]
Thanks for this PR
/approve

**Pull request merged**
