### PR TITLE
error strings should not end with punctuation

### PR DESCRIPTION
**Pull request by yu8833**
**What this PR does / why we need it**:
Delete the end punctuation of error strings
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
https://github.com/golang/go/wiki/CodeReviewComments#error-strings
**Release note**:

```release-note
```

Signed-off-by: yupeng <yu.peng36@zte.com.cn>

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36734)

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by quinton-hoole** [comment]
Wow, what a lot of assignees!

**Comment by madhusudancs** [comment]
@k8s-bot kops aws e2e test this

**Comment by madhusudancs** [comment]
@k8s-bot bazel test this

**Comment by madhusudancs** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
