### PR TITLE
azure: remove GA IPv6DualStack feature-gate

### PR DESCRIPTION
**Pull request by jackfrancis**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This PR removes the GA-graduated feature-gate `IPv6DualStack`.

Until we merge this upstream azure tests against k8s @ HEAD are broken.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jackfrancis** [comment]
@khenidak @aramase FYI, congrats on graduating dual stack to GA!!!

<insert Joe Biden BFD gif here>

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by andyzhangx** [comment]
/assign @andrewsykim @cheftako 
for approval, thanks

**Comment by jsturtevant** [comment]
The Windows Aks-engine job would require updates to aks-engine to pass the tests as there are other harded coded values in the templates.  We should use the capz job on main branch. I've updated the aks-engine jobs to move them to capz here: https://github.com/kubernetes/test-infra/pull/26238

This change will allow the capz tests to pass: 

/test pull-kubernetes-e2e-capz-windows-containerd

**Comment by jackfrancis** [comment]
@andrewsykim @cheftako this is ready for approval/merge now, if you have cycles can you take a look?

thank you!

**Comment by jsturtevant** [comment]
/lgtm
The `pull-kubernetes-e2e-aks-engine-windows-containerd ` job is not required and is being removed. See https://github.com/kubernetes/test-infra/pull/26238.  The capz-windows job did pass (`pull-kubernetes-e2e-capz-windows-containerd `)

Marking this as urgent as this is blocking sig-windows release informing tests.
/priority critical-urgent

**Pull request merged**
