### PR TITLE
kube-controller-manager: remove unused option deployment-controller-sync-period for deployment controller

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
kube-controller-manager: remove unused option deployment-controller-sync-period for deployment controller.
Ref: #103538

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
The deprecated kube-controller-manager flag '--deployment-controller-sync-period' has been removed, it is not used by the deployment controller.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by ialidzhikov** [comment]
```
Unexpected dirty working directory:
[911](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/107178/pull-kubernetes-verify/1508999183279853568#1:build-log.txt%3A911)
[912](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/107178/pull-kubernetes-verify/1508999183279853568#1:build-log.txt%3A912)
  diff --git a/pkg/generated/openapi/zz_generated.openapi.go b/pkg/generated/openapi/zz_generated.openapi.go
[913](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/107178/pull-kubernetes-verify/1508999183279853568#1:build-log.txt%3A913)
  index 6245426ad39..02371746082 100644
[914](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/107178/pull-kubernetes-verify/1508999183279853568#1:build-log.txt%3A914)
  --- a/pkg/generated/openapi/zz_generated.openapi.go
[915](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/107178/pull-kubernetes-verify/1508999183279853568#1:build-log.txt%3A915)
  +++ b/pkg/generated/openapi/zz_generated.openapi.go
```

@SataQiu looks like something is not properly generated after the changes from this PR? Can you check?

**Comment by SataQiu** [comment]
@dims @thockin @soltysh @ialidzhikov  Looks like all the tests have passed.
Waiting for `LGTM`.

**Review by pacoxu — APPROVED** [review]
/lgtm

**Comment by pacoxu** [comment]
/retest
😂

**Comment by SataQiu** [comment]
It looks like it will take multiple retries to pass the test :(

**Pull request merged**
