### PR TITLE
new test case to util.go

### PR DESCRIPTION
**Pull request by tianshapjq**
**What this PR does / why we need it**:
add a new test case to util.go

### CODE REVIEW

**Comment by dashpole** [comment]
@k8s-bot ok to test

**Comment by tianshapjq** [comment]
@dashpole anything wrong with the test? It seems failed but ran fine in my environment.

**Comment by dashpole** [comment]
`FAILED   hack/make-rules/../../hack/verify-bazel.sh	4s`
You need to run ./hack/update-bazel.sh

**Comment by tianshapjq** [comment]
@dashpole I have updated the Bazel and merged. Could you please check if this is alright? Seems some unrelated commit also been merged.

**Comment by dashpole** [comment]
please squash your commits.  Otherwise, lgtm

**Comment by tianshapjq** [comment]
@dashpole I re-push the commit, please check if it's ok.

**Comment by dashpole** [comment]
@k8s-bot unit test this

**Comment by tianshapjq** [comment]
@dashpole anything wrong with my testcase?

**Comment by dashpole** [comment]
@k8s-bot unit test this

**Comment by dashpole** [comment]
The federation test was added recently.  Try rebasing to get it to run...
/release-note-none

**Pull request closed without merging**
