### PR TITLE
Munger

### PR DESCRIPTION
**Pull request by lavalamp**
@thockin these are my latest changes.

### CODE REVIEW

**Comment by thockin** [comment]
LGTM

**Comment by rjnagal** [comment]
needs a rebase and retest.

**Comment by bgrant0607** [comment]
Was this obsoleted by #11113?

**Comment by bgrant0607** [comment]
Hmm. This includes a bunch of other changes, also. 

Are we going to try to merge this?

**Comment by thockin** [comment]
I think you can remove the bits about skipping munges (unless you want to
keep them, in which case they can be a different PR) and about running
munge on the tmp docroot

**Comment by lavalamp** [comment]
OK, my collected fixes working w/out oscillation and on the examples directory.

* Add analytics munger w/ munge heading
* More link autofixes
* Allow running a subset of munges
* Fix repo root detection
* Only process non-preformatted blocks
* Gendocs no longer adds the analytics link; mungedocs does that in a
  second pass.

**Comment by thockin** [comment]
Minor points then LGTM

**Comment by lavalamp** [comment]
Comments addressed

**Comment by thockin** [comment]
LGTM but I just merged a PR with a doc - while we're waiting for shippable to fail, you should re-un gendocs

**Comment by lavalamp** [comment]
Rebased & pushed

**Pull request merged**
