### PR TITLE
Rename root BUILD to BUILD.bazel, and rename build-tools/ back to build/

### LINKED ISSUE #38126: rename build-tools/ back to build/
As part of the Bazel effort, in #35453 we had to rename `build/` to `build-tools/`, as `build/` and `BUILD` conflicted on case-insensitive filesystems (like macOS).

Bazel 0.4.1 has now been released, which includes the fix for https://github.com/bazelbuild/bazel/issues/552, allowing us to use `BUILD.bazel` instead of `BUILD`.

I'd like to rename `build-tools/` back to `build/`, to be consistent with how the repo has been in older releases, and I'd like to cherry-pick this into 1.5 as well, so we don't have to special case in other repos for months. It's probably too close to cherry-pick for 1.5.0, but it should be fairly safe for 1.5.1 IMO.

cc @mikedanese @spxtr @thockin @saad-ali

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: undoes #35453. `build-tools/` was intended to be a temporary workaround until https://github.com/bazelbuild/bazel/issues/552 was fixed, which is has been, as of bazel 0.4.1.

**Which issue this PR fixes**: fixes #38126

FYI @thockin 

since this is likely to be rebase hell, my list of actions:
```console
$ git mv BUILD BUILD.bazel
$ git commit -a
$ git mv build-tools/ build/
$ sift -l 'build-tools' | xargs sed -i -e 's:build-tools/:build/:g'
$ git checkout HEAD docs/
$ git commit -a
```

### CODE REVIEW

**Comment by ixdy** [comment]
@k8s-bot build this
@k8s-bot bazel test this

**Comment by ixdy** [comment]
reverted docs/ changes, because pain.

**Comment by mikedanese** [comment]
@k8s-bot bazel test this

**Comment by ixdy** [comment]
@k8s-bot build this

**Comment by mikedanese** [comment]
will we need to update bazel in the build container?

**Comment by spxtr** [comment]
https://github.com/kubernetes/test-infra/blob/master/images/pull-kubernetes-bazel/Dockerfile

**Comment by ixdy** [comment]
oh, good call. we also need https://github.com/kubernetes/test-infra/pull/1373 to merge before this.

**Comment by ixdy** [comment]
@k8s-bot build this
@k8s-bot bazel test this

**Comment by ixdy** [comment]
@k8s-bot cvm gke e2e test this

**Comment by ixdy** [comment]
GKE builds have been rather flaky of late.
@k8s-bot gci gke e2e test this

**Pull request merged**
