### PR TITLE
change event count type

### PR DESCRIPTION
**Pull request by knightXun**
event count type had better to be uint.

thx all.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by caesarxuchao** [comment]
Thanks, @knightXun.

**Comment by knightXun** [comment]
can any merge my pr？

**Comment by nikhiljindal** [comment]
> can any merge my pr？

It wasnt getting merged because of release note label. Fixed it now so the merge bot should merge it once all the tests pass.

**Comment by knightXun** [comment]
@nikhiljindal thx

**Pull request merged**
