### PR TITLE
move openapi parsing to api machinery

### PR DESCRIPTION
**Pull request by mengqiy**
Move some common openapi parsing and indexing code to the apimachinery repo.

kubectl will depend on this. And [strategic merge patch](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch) will also depend on this in https://github.com/kubernetes/kubernetes/pull/51321

After discussing with @mbohlool and @caesarxuchao, this piece of code is not generic to go to kube-openapi repo, since it has some k8s related GVK logic.

```release-note
NONE
```

/assign @apelisse @caesarxuchao

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Still I feel the code doesn't belong to apimachinery.

Is it possible to make the map key string, instead of gvk? Then you can keep the code in openapi and don't import any kubernetes code. It looks like the [gvk.String()](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/runtime/schema/group_version.go#L138) is unique if gvk is unique.

**Comment by apelisse** [comment]
> Is it possible to make the map key string, instead of gvk?

GVK is pretty much POD anyway, we can do without it.

**Comment by mengqiy** [comment]
@mbohlool What's your thought on https://github.com/kubernetes/kubernetes/pull/51674#issuecomment-326220256? If you are OK I will proceed as @caesarxuchao suggested.

**Comment by mengqiy** [comment]
@deads2k What's your option?

**Comment by deads2k** [comment]
> @deads2k What's your option?

Based on the title, I'm a -1 on this.  I don't think our machinery is or should be directly tied to the openapi.  There is an openapi repo that @mehdy made and that off-the-cuff, that sounds like a good home for parsing code.

**Comment by mbohlool** [comment]
@mengqiy My main concern was having GVK in this source code. If you can get rid of it and make the code completely kubernetes independent, I think kube-openapi is the repo for it. Keep in mind that you cannot import any kubernetes repo from kube-openapi (except gengo). Sorry for sending you back and forth between these two repos.

**Comment by mengqiy** [comment]
Closing in favor of https://github.com/kubernetes/kube-openapi/pull/10.

**Pull request closed without merging**
