### PR TITLE
Automated cherry pick of #66499: kubeadm: Pull sidecar and dnsmasq-nanny images when using

### PR DESCRIPTION
**Pull request by neolit123**
Cherry pick of #66499 on release-1.11.

#66499: kubeadm: Pull sidecar and dnsmasq-nanny images when using

### CODE REVIEW

**Comment by neolit123** [comment]
had a little bit of a rebase conflict.
hopefully this can make it in 1.11.2.

/kind bug
/priority important-soon
/label cherrypick-candidate

/assign @luxas @timothysc @foxish

**Comment by neolit123** [comment]
`GetGenericArchImage` is missing in 1.11.
i need to fix that...
/cc @rosti

**Review by luxas — APPROVED** [review]
/approve
/lgtm
/milestone v1.11
/assign @foxish 
/status approved-for-milestone
/kind bug
/priority important-soon

**Review by luxas — APPROVED** [review]
/lgtm

**Comment by timothysc** [comment]
@foxish ready to go.

**Pull request merged**
