### PR TITLE
Change the master to control plane

### PR DESCRIPTION
**Pull request by xichengliudui**
/kind cleanup

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by yagonobre — COMMENTED** [review]
Thanks @xichengliudui, can you change this across the project?

**Comment by xichengliudui** [comment]
@yagonobre ,Of course, we can modify this in the whole project, but I seem to remember that we only need to modify the master to be control plane in kubeadm for the time being. It seems that the other modules don't need to modify for the time being.

**Comment by xichengliudui** [comment]
If other modules such as: kubectl, kubelet also need to be modified, please let me know.

**Comment by yagonobre** [comment]
sorry, but for the whole project I wanted do means "kubeadm"

**Comment by neolit123** [comment]
yes, please search if there are more places where we can modify this so that we can include this in the same PR.
thanks.

**Comment by neolit123** [comment]
given the taint is "master" i think we are OK without making this change.
the current kubeadm codebase does not have user facing text or public objects that use "master".

thanks
/close

**Pull request closed without merging**
