### PR TITLE
clarify kubelet address flag and healthz-bind-address flag usage

### PR DESCRIPTION
**Pull request by notpad**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

From the listen godoc:

For TCP networks, if the host in the address parameter is empty or a
literal unspecified IP address, Listen listens on all available unicast
and anycast IP addresses of the local system.

Since the `Address` option and `HealthzBindAddress` option are both "tcp" by default, using an unspecified address doesn't bind the listener to the IP family.

**Which issue(s) this PR fixes**:

Part of #88458

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
/assign @random-liu

I think this documentation is definitely clearer than what exists now. I defer to @aojea , who knows much more about the networking stack than I do :)

**Comment by aojea** [comment]
/lgtm
Both seem to use `http.ListenAndServe`

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L792
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L1138
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L1142

That uses net.Listen 

https://golang.org/src/net/http/server.go?s=88453:88494#L2808

Thus they have the behavior described in the referring issue
https://github.com/kubernetes/kubernetes/issues/88458

**Comment by notpad** [comment]
Removed the backquote as it may cause pflag to parse out the wrong flag type

**Comment by notpad** [comment]
@aojea  Can you give another LGTM, thanks~

**Comment by aojea** [comment]
@notpad the criteria in this PR 

https://github.com/kubernetes/kubernetes/pull/88512

was to replace the backquote by `'`


we should try to be coherent along the codebase. 
@SataQiu you created the linked PR, can you advice here?

**Comment by derekwaynecarr** [comment]
this makes sense.

/approve
/lgtm

**Comment by derekwaynecarr** [comment]
/approve cancel
/lgtm cancel

sorry, we should keep ticks to be consistent with https://github.com/kubernetes/kubernetes/pull/85850/files#diff-440efa89fc197eb244da0254f14241aaR368

**Pull request closed without merging**
