### PR TITLE
Prepare for periodic runner

### PR DESCRIPTION
**Pull request by wojtek-t**
Rerevert https://github.com/kubernetes/kubernetes/pull/46004 with the fix.

For now, built on top of #45816

### CODE REVIEW

**Comment by wojtek-t** [comment]
@thockin - FYI, this is revert of the PR, but built on top of #45816 (so I would prefer having that one merged first)

**Comment by thockin** [comment]
Excellent!  You are one step ahead of me.

**Comment by thockin** [comment]
LGTM modulo comments on base PR

**Comment by wojtek-t** [comment]
Thanks @thockin . Rebased on top of the already merged base PR.
Applying label based on comment above.

**Comment by wojtek-t** [comment]
@k8s-bot etcd3 test this

**Pull request merged**
