### PR TITLE
fix issue(#36733)Add node tains info in wide

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:
#36733 #38768

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
Please run `hack/verify-gofmt.sh` and fix it.

**Comment by zjj2wry** [comment]
@xiangpengzhao thanks

**Comment by smarterclayton** [comment]
How wide is wide here?  Include some realistic sample output.  I'm concerned about the width here.

**Comment by zjj2wry** [comment]
```
NAME            STATUS                     AGE       VERSION        EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION          CONTAINER-RUNTIME   TAINTS
kube-master-1   Ready,SchedulingDisabled   127d      v1.6.2-dirty   <none>        CentOS Linux 7 (Core)   3.10.0-514.el7.x86_64   docker://1.11.2     <none>
kube-master-2   Ready                      127d      v1.6.2-dirty   <none>        CentOS Linux 7 (Core)   3.10.0-514.el7.x86_64   docker://1.11.2     <none>
kube-master-3   Ready                      127d      v1.6.2-dirty   <none>        CentOS Linux 7 (Core)   3.10.0-514.el7.x86_64   docker://1.11.2     <none>
kube-node-1     Ready                      127d      v1.6.2-dirty   <none>        CentOS Linux 7 (Core)   3.10.0-514.el7.x86_64   docker://1.11.2     PreferNoSchedule
kube-node-2     Ready                      127d      v1.6.2-dirty   <none>        CentOS Linux 7 (Core)   3.10.0-514.el7.x86_64   docker://1.11.2     <none>
kube-node-3     Ready                      127d      v1.6.2-dirty   <none>        CentOS Linux 7 (Core)   3.10.0-514.el7.x86_64   docker://1.11.2     <none>
kube-node-4     Ready                      127d      v1.6.2-dirty   <none>        CentOS Linux 7 (Core)   3.10.0-514.el7.x86_64   docker://1.11.2     PreferNoSchedule
kube-node-5     Ready                      127d      v1.6.2-dirty   <none>        CentOS Linux 7 (Core)   3.10.0-514.el7.x86_64   docker://1.11.2     <none>
```

**Comment by zjj2wry** [comment]
@smarterclayton this is output in my 2560 x 1600 mac book, have enough space add column, can add this field in ```kubectl get node```?

**Pull request closed without merging**
