### PR TITLE
cleanup the kubeadm integration tests and related scripts

### LINKED ISSUE #1383: Tests are not passing with unprivileged user
## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): 1.14+

## What happened?

Tests are not passing when run with an unprivileged user that has no rights to mkdir `/var/lib/etcd`.

## What you expected to happen?

Tests should pass.

## How to reproduce it (as minimally and precisely as possible)?

Run tests with unprivileged user that is not able to mkdir `/var/lib/etcd`.

## Anything else we need to know?

The problem was introduced in https://github.com/kubernetes/kubernetes/commit/836f413cf1096c9b020b20319d0767aee4f9b990, because it's trying to `os.MkdirAll(cfg.Etcd.Local.DataDir, 0700)` unconditionally.

### PR DESCRIPTION
**Pull request by neolit123**
**What type of PR is this?**
/kind bug
/kind cleanup

**What this PR does / why we need it**:

This PR contains multiple commits; please look at the commit messages.

`make test-cmd WHAT=kubeadm` executes into a `/hack` rule that sources a `/test/cmd` script function that executes code in `/cluster` and then the result of the `/cluster` call is passed as a flag to an "integration" test in `cmd/kubeadm/test` . tempted to pull some `git blame` on this one, but let's leave it a mystery. fascinating...

this is now simplified to `make test-cmd` executes a `/hack/` rule that sets an environment variable and runs the same integration tests. unwanted scripts are deleted.

also kubernetes/kubeadm#1383 is fixed by using another environment variable.
open to alternative ideas on this one, but i don't see what else is possible...and this is for dry-run so...

apply other minor cleanups to the tests too.

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#1383

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/assign @bentheelder
PTAL at the /hack, /test/, /cluster changes.

/assign @rosti
PTAL at the /cmd/kubeadm changes.

**Comment by spiffxp** [comment]
/approve
for the hack/ cluster/ test/ stuff.  Tested locally on macOS.  Before this PR, `make test-cmd` and `make test-cmd WHAT=kubeadm` wouldn't pass, after this PR they do.  Thank you for untangling this

**Review by rosti — APPROVED** [review]
Thanks @neolit123 !
/lgtm

**Comment by BenTheElder** [comment]
thanks @spiffxp @neolit123

**Pull request merged**
