### PR TITLE
Upgrade to docker 1.8.3 for GCE cluster

### PR DESCRIPTION
**Pull request by dchen1107**
#15563

### CODE REVIEW

**Comment by dchen1107** [comment]
Shippable failure is caused by known timeout issue.

**Comment by roberthbailey** [comment]
@dchen1107 Is the plan to ship the 1.1 release with docker 1.8.3 instead of 1.8.2?

**Comment by dchen1107** [comment]
@roberthbailey Yes, the new plan is shipping 1.1 release with docker 1.8.3. I want to merge this asap so that we can have it for soaking test. Thanks!

**Comment by dchen1107** [comment]
cc/ @kubernetes/goog-gke

**Pull request merged**
