### PR TITLE
allow for more easily customized kubelet creation and initialization

### PR DESCRIPTION
**Pull request by jdef**
The kubernetes-mesos project leverages a modified kubelet implementation. Part of those modifications involve customizations to the kubelet startup sequence. This PR introduces some abstractions that more easily facilitate such customizations.

### CODE REVIEW

**Comment by jdef** [comment]
i've signed the CLA as james.defelice at ishisystems.com

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/128

**Comment by ConnorDoyle** [comment]
@jdef looks like this one needs a rebase.

**Comment by jdef** [comment]
Yes it's on my list for next week. Should be fun now that we've fully
vendored.

--sent from my phone

**Comment by dchen1107** [comment]
Ping once you are done with rebase, thanks!

**Comment by jdef** [comment]
ping @dchen1107

**Comment by jdef** [comment]
of two test builds, one passed and the second failed. a test case failed with the following error, unrelated?
```
--- FAIL: TestSyncPodsDeletesWithNoPodInfraContainer (0.03 seconds)
	kubelet_test.go:119: expected []string{"list", "list", "list", "list", "inspect_container", "inspect_container", "list", "inspect_container", "inspect_container", "stop", "create", "start", "inspect_container", "create", "start", "list", "inspect_container", "inspect_container"}, got []string{"list", "list", "list", "stop", "create", "start", "inspect_container", "create", "start", "list", "inspect_container", "inspect_container", "list", "inspect_container", "inspect_container", "list", "inspect_container", "inspect_container"}
```

**Comment by jdef** [comment]
it looks like a test case problem that's already been fixed in master:
```go
	verifyUnorderedCalls(t, fakeDocker, []string{
		"list", "list", "list", "list", "inspect_container", "inspect_container", "list", "inspect_container", "inspect_container", "stop", "create", "start", "inspect_container", "create", "start", "list", "inspect_container", "inspect_container"})
```

**Comment by timothysc** [comment]
@dchen1107 please label with mesos flags please.

**Comment by jdef** [comment]
PTAL @dchen1107 @bgrant0607

**Comment by jdef** [comment]
cc @guenter

**Comment by vmarmol** [comment]
LGTM, re-running tests.

**Comment by vmarmol** [comment]
Looks like we have failures:

```
# github.com/GoogleCloudPlatform/kubernetes/cmd/kubelet/app
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/kubelet/app/server.go:437: cannot use k (type KubeletBootstrap) as type kubelet.HostInterface in argument to kubelet.ListenAndServeKubeletReadOnlyServer:
	KubeletBootstrap does not implement kubelet.HostInterface (missing ExecInContainer method)
```

**Comment by jdef** [comment]
sounds like another rebase is necessary. will take a look

On Mon, Apr 6, 2015 at 12:08 PM, Victor Marmol <notifications@github.com>
wrote:

> Looks like we have failures:
>
> # github.com/GoogleCloudPlatform/kubernetes/cmd/kubelet/app
> _output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/kubelet/app/server.go:437 <http://github.com/GoogleCloudPlatform/kubernetes/cmd/kubelet/app_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/cmd/kubelet/app/server.go:437>: cannot use k (type KubeletBootstrap) as type kubelet.HostInterface in argument to kubelet.ListenAndServeKubeletReadOnlyServer:
>     KubeletBootstrap does not implement kubelet.HostInterface (missing ExecInContainer method)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/4842#issuecomment-90126319>
> .
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)

**Comment by jdef** [comment]
@vmarmol rebased version is passing PTAL

**Comment by vmarmol** [comment]
LGTM

**Pull request merged**
