### PR TITLE
`exec` away the shell for node-problem-detector

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by asottile** [comment]
Ideally this should use [an init system of some sort](https://github.com/Yelp/dumb-init#why-you-need-an-init-system), but that's a little more involved of a PR

**Comment by roberthbailey** [comment]
@dchen1107 - can someone from sig-node look first before we look for approvers?

@asottile - we are past the code freeze for 1.9 so unless you are planning to ask for an exception this won't be merged until the master branch re-opens.

**Comment by dchen1107** [comment]
/lgtm 

cc/ @Random-Liu for the change.

**Comment by asottile** [comment]
seems the build is stuck?

**Comment by ericchiang** [comment]
Per @dchen1107 's comment https://github.com/kubernetes/kubernetes/pull/55971#issuecomment-356696470, I'm manually adding the approved label.

**Comment by asottile** [comment]
I trivial rebased, maybe that'll help with the e2e test

**Comment by asottile** [comment]
Fixed the tests, but now approval is gone :(

**Pull request merged**
