### PR TITLE
Cleanup --dry-run values in tests, docs, and scripts

### PR DESCRIPTION
**Pull request by julianvmodesto**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

/kind cleanup

**What this PR does / why we need it**:

This PR updates the `--dry-run` values to use `client` or `server` values where appropriate in tests, docs, and scripts. 

We need this because the flag `--dry-run` without a value and `--dry-run=true|false` are deprecated and should be removed.

**Which issue(s) this PR fixes**:

Cleanup for https://github.com/kubernetes/kubernetes/issues/85652.

Part of https://github.com/kubernetes/kubernetes/issues/86526.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
- [KEP]: https://github.com/kubernetes/community/blob/master/keps/sig-api-machinery/0015-dry-run.md
```

/sig cli
cc @apelisse 
/priority important-soon

### CODE REVIEW

**Comment by julianvmodesto** [comment]
Oops, I missed one: `kubectl auth reconcile`. This looks weirder because it uses `pkg/registry/`, which has an interface for client-side dry-run. I've updated `kubectl auth reconcile` to only support `--dry-run=client` for now.

**Comment by apelisse** [comment]
Can you squash or rename the wip test? I think that looks great.

**Comment by julianvmodesto** [comment]
Squashed!

**Comment by apelisse** [comment]
Thanks!
/lgtm
/approve

**Comment by apelisse** [comment]
/assign @vishh

Can you approve the changes in `cluster/gce`. This is mostly updating dry-run flags since the value has become deprecated.

**Comment by julianvmodesto** [comment]
Reassigning to a more active CODEOWNER.

/assign @mtaufen 

Could you please take a look at the `cluster/gce/` change? We have fixed a `--dry-run` flag in a script from a deprecated value to the updated new value.

**Pull request merged**
