### PR TITLE
Fixed typo for kubectl top pod

### PR DESCRIPTION
**Pull request by lauchokyip**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Fixed the typo for `kubectl top pod`

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by eddiezane** [comment]
Nice catch. Looks like this is also in `top_node.go`.

**Comment by lauchokyip** [comment]
FIxed @eddiezane

**Review by eddiezane — APPROVED** [review]
/approve

**Comment by rikatz** [comment]
/lgtm

Thank you!

**Pull request merged**
