### PR TITLE
pkg/cloudprovider - fix golint failures

### PR DESCRIPTION
**Pull request by saravanan30erd**
**What this PR does / why we need it**:
Fixes golint issues - pkg/cloudprovider

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #68026 

**Special notes for your reviewer**:

**Release note**:

```release-note
Fixes golint issues - pkg/cloudprovider
```

### CODE REVIEW

**Comment by saravanan30erd** [comment]
@eparis @jbeda @anguslees Since the go-lint fixes in `pkg/cloudprovider` made lot of changes in providers packages(aws, vsphere,..), I think its better to start providers packages after this one merged OR add golint fixes of providers(aws,vsphere) in this same PR with separate commits.
Please advice.

**Comment by neolit123** [comment]
@saravanan30erd thanks for the PR.
please rebase this so that we can run the tests on it.

**Comment by saravanan30erd** [comment]
@neolit123 I messed up during rebase, so I created new branch as well as PR #68206

**Pull request closed without merging**
