### PR TITLE
Automated cherry pick of #105188: fix: consolidate logs for instance not found error

### PR DESCRIPTION
**Pull request by nilo19**
Cherry pick of #105188 on release-1.22.

#105188: fix: consolidate logs for instance not found error

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
fix: consolidate logs for instance not found error
```

### CODE REVIEW

**Comment by nilo19** [comment]
/sig cloud-provider
/area provider/azure
/priority critical-urgent
/triage accepted
/kind bug
cc @feiskyer

**Review by feiskyer — APPROVED** [review]
/lgtm
/retest

**Comment by feiskyer** [comment]
@cheftako @andrewsykim CI green now. could you help to approve?

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
