### PR TITLE
AWS: Use the SSH key fingerprint, not the AWS fingerprint

### PR DESCRIPTION
**Pull request by justinsb**
This is unfortunate, because it means we have two fingerprints,
although arguably the OpenSSH key fingerprint is much more common.
However, the OSX Mavericks version of ssh-keygen can't compute
the AWS fingerprint correctly (e.g. https://www.netmeister.org/blog/ssh2pkcs8.html)

So we can work on OSX Mavericks, we use the more common OpenSSH fingerprint.

Consequences of this:
- we will re-upload every SSH key (no real problem there).
- the same key will now have two different names for people that ran older k8s versions (confusing, but no real problem)
- the fingerprint AWS displays will be different from the (SSH) fingerprint embedded in the name (confusing, but the AWS fingerprint is arguably the cause of the confusion)

Upsides: we should work on OSX Mavericks and generally much more robust.

If we moved these scripts e.g. to Go, we could compute the AWS key ourselves.  But I think for now it is more important to run on Mavericks than to compute the same fingerprints.

@iterion PTAL

### CODE REVIEW

**Comment by iterion** [comment]
LGTM, this change also works on El Capitan with the same caveats as above.
The two different fingerprints might be confusing, but I'm not sure people will really care or notice.

**Comment by zmerlynn** [comment]
Blech. But LGTM.

**Comment by zmerlynn** [comment]
Over to @quinton-hoole to finish.

**Comment by quinton-hoole** [comment]
LGTM, ok-to-merge.  Thanks Justin!

**Pull request merged**
