### PR TITLE
Add group, version, namespace, name, and subresource to apiserver tracing

### LINKED ISSUE #120156: Add additional span attributes to APIServer tracing spans
### What would you like to be added?

Feedback originally provided on slack: https://kubernetes.slack.com/archives/C0EG7JC6T/p1692869878675069?thread_ts=1692653423.769159&cid=C0EG7JC6T

It would be helpful to have additional fields on APIServer spans.  This is the current set of attributes we provide:

https://github.com/kubernetes/kubernetes/blob/9ce03d9254cbd47d82a4b2d88e2a915943d90e26/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/trace_util.go#L25-L36

It would be helpful to add: group, version, namespace, name, and subresource, if possible.

### Why is this needed?

Part of https://github.com/kubernetes/enhancements/issues/647.

### PR DESCRIPTION
**Pull request by HirazawaUi**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
This PR adds group, version, namespace, name, and subresource as trace attribute

#### Which issue(s) this PR fixes:

Fixes #120156

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by eddycharly** [comment]
cc @dashpole

**Review by dashpole — APPROVED** [review]
/lgtm

**Comment by dashpole** [comment]
/assign @apelisse 
for approval

**Comment by apelisse** [comment]
Sure,
/approve

**Pull request merged**
