### PR TITLE
Tweak quantity docs

### LINKED ISSUE #31967: Serialization format on https://k8s.io/docs/reference/kubernetes-api/common-definitions/quantity/ is hard to read
The page does not show the serialization format in a readable way: it seems like there should've been a code block.

### PR DESCRIPTION
**Pull request by tengqm**
#### What type of PR is this?

/kind documentation
/kind api-change

#### What this PR does / why we need it:

This PR changes the format of the doc strings for the `Quantity` type for ease of reference documentation generation.

#### Which issue(s) this PR fixes:

This PR partially fixes kubernetes/website#31967

#### Special notes for your reviewer:

This PR is not changing any function or logic.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tengqm** [comment]
Maybe I have to abandon this PR because I have got some problems building the docker images used to generate protobuf files. The build command `docker buildx build` doesn't support proxy settings. As a developer from behind the damn firewall, there is nothing I can do at the moment. Hopefully someone else can help get this job done?

**Comment by tengqm** [comment]
Maybe I have to abandon this PR because I have got some problems building the docker images used to generate protobuf files. The build command `docker buildx build` doesn't support proxy settings. As a developer from behind the damn firewall, there is nothing I can do at the moment. Hopefully someone else can help get this job done?

**Comment by roycaihw** [comment]
https://github.com/kubernetes/kubernetes/pull/109172#issuecomment-1084356232: I hope this helps https://github.com/tengqm/kubernetes/pull/1

/lgtm

**Comment by tengqm** [comment]
@roycaihw Thanks for the help. 

Looks like we need to refresh the generated files.

**Pull request closed without merging**
