### PR TITLE
Fix golint issues in test/e2e_node

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix golint issues in test/e2e_node

**Which issue(s) this PR fixes**:

Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hvaara — COMMENTED** [review]
Thanks for the PR!
I'm not a reviewer, but this looks good to me

**Review by oomichi — COMMENTED** [review]
/approve

**Pull request merged**
