### PR TITLE
Remove update.sh now that e2e/kubectl.go is stable

### PR DESCRIPTION
**Pull request by j3ffml**
cc @roberthbailey

### CODE REVIEW

**Comment by roberthbailey** [comment]
I'm not convinced that the Go tests are quite as stable as the shell test. In the last 24 runs, the shell test has passed 24 times and the Go tests have passed (23, 22, 22) times respectively for the 3 sub tests. 

All five failures of the Go tests have the same output

```Timed out waiting for name=update-demo pods to reach valid state```

Is our timeout inside the Go tests too short?

**Comment by jlowdermilk** [comment]
Hmmm... the failures all appear to be the result of slow (~40s) pull times on images. But the timeout is pretty similar to update.sh. I think kubectl.go is actually no flakier than update.sh, it just happens to run first and is taking the hit for the initial image pull. Happy to hold off on this and try bumping the timeout first.

**Comment by jlowdermilk** [comment]
Actually, nevermind, the timeout on kubectl.go is only 30s, compared to > 40s for update.sh. I'll bump that to 60s.

**Comment by roberthbailey** [comment]
With the increased timeout the Go tests now seem much more stable.

**Pull request merged**
