### PR TITLE
add back the double dollar sign

### LINKED ISSUE #17155: API Reference: shows "(VAR_NAME)" instead of "$$(VAR_NAME)"
In <http://kubernetes.io/v1.1/docs/api-reference/v1/definitions.html#_v1_container> it reads `The $(VAR_NAME) syntax can be escaped with a double , ie: (VAR_NAME).` but it should read `The $(VAR_NAME) syntax can be escaped with a double $$, i.e. $$(VAR_NAME).`

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #17155 on gh-pages.

cc @orfjackal

### CODE REVIEW

**Comment by nikhiljindal** [comment]
LGTM, you did the changes manually?

**Comment by caesarxuchao** [comment]
@nikhiljindal, yeah, this one is manual.

**Comment by nikhiljindal** [comment]
@caesarxuchao The correct way would have been to cherrypick https://github.com/kubernetes/kubernetes/pull/17298 in release-1.1 and import the docs in gh-pages from there rather than directly fixing docs on gh-pages.

These changes are now getting reverted with https://github.com/kubernetes/kubernetes/pull/18059

**Comment by caesarxuchao** [comment]
Thanks! I didn't think we will reimport the docs again for 1.1. I'll cherry-pick this.

**Comment by caesarxuchao** [comment]
Just take a quick look, it's too difficult to cherry-pick #17298 now. I'll just make a manual patch and see if it works.

**Pull request merged**
