### PR TITLE
Update links in PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by mikebryant**
**What this PR does / why we need it**:
Improve the contributor experience: Send people directly to the right document instead of to a redirect

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by MHBauer — APPROVED** [review]
update looks good to me. I agree that the links should go directly to there rather than redirect.

**Comment by mikebryant** [comment]
Pretty sure that was a flake, since I'm just updating the docs.

Couldn't find an open issue for this flake? - but I'm not really experience reading those build logs so I'm not sure what I'm looking for really

**Comment by mikebryant** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by spxtr** [comment]
@k8s-bot ok to test

**Comment by smarterclayton** [comment]
@k8s-bot cvm gce e2e test this
@k8s-bot non-cri e2e test this

**Comment by mikebryant** [comment]
@k8s-bot cvm gce e2e test this

**Comment by mikebryant** [comment]
@k8s-bot cvm gce e2e test this

**Pull request closed without merging**
