### PR TITLE
Scheduler: remove direct import to /pkg/util/parsers

### PR DESCRIPTION
**Pull request by gavinfish**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Scheduler: remove direct import to /pkg/util/parsers

**Which issue(s) this PR fixes**:

Ref #89930

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
none
```

### CODE REVIEW

**Review by damemi — APPROVED** [review]
This looks good, but some things I'm thinking that we might want to consider:

This const is only used in 1 other spot ([pkg/kubelet/images](https://github.com/kubernetes/kubernetes/blob/5bfe8fe2b9024f0319c053d5514b491f7c18aad8/pkg/kubelet/images/image_manager.go#L164)), so could it be cleaned up there too? 

Going even further, does `latest` really need to be a constant for the default image tag? Ie, do we foresee having to change that? It's actually shorter to type `latest` than `defaultImageTag` in the first place so I'm not sure what's gained by having a constant for something that's kind of assumed. But I'm not strict about that, just thinking out loud.

/lgtm

**Comment by gavinfish** [comment]
@damemi 
> This const is only used in 1 other spot (pkg/kubelet/images), so could it be cleaned up there too?
Letting kubelet depend on k/util looks good to me. I think it is unnecessary to duplicate it in kubelet too.

> Going even further, does latest really need to be a constant for the default image tag? Ie, do we foresee having to change that? It's actually shorter to type latest than defaultImageTag in the first place so I'm not sure what's gained by having a constant for something that's kind of assumed. But I'm not strict about that, just thinking out loud.

+1. This constant is introduced five years ago in #17278. It is never changed and I cannot foresee any cases it may change. I can remove the constant if it looks better.

**Comment by damemi** [comment]
@gavinfish would you like to add another commit removing the const entirely? We'll need kubelet owners to approve that and then we can get their opinion on it

**Comment by gavinfish** [comment]
@damemi I just remove the `DefaultImageTag` const to make it more consice.

**Review by damemi — APPROVED** [review]
/lgtm
will need approval from a pkg owner as well

**Comment by damemi** [comment]
/assign @lavalamp 
could you ptal at this? it's removing the `DefaultImageTag` which has been `latest` unchanged for 5 years

**Comment by derekwaynecarr** [comment]
kubelet change lgtm.

/approve
/lgtm

**Comment by damemi** [comment]
Thanks @derekwaynecarr 

@lavalamp polite ping, this needs a `pkg/` approver

**Comment by damemi** [comment]
> pull-kubernetes-files-remake Expected — Waiting for status to be reported 

this looks new, anything we need to do to poke it?

**Pull request merged**
