### PR TITLE
adding `--ssh-key` and `--ssh-user` for kubetest2

### PR DESCRIPTION
**Pull request by Namanl2001**
Signed-off-by: Namanl2001 <namanlakhwani@gmail.com>

This PR is part of the CI migration from kubetest to kubetest2
https://github.com/kubernetes/enhancements/tree/master/keps/sig-testing/2464-kubetest2-ci-migration

`--ssh-key` and `--ssh-user` are not present for kubetest2, which is leading to this error: `failed to run SSH command: out: Warning: Identity file /root/.ssh/google_compute_engine not accessible: No such file or directory :`
ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/92316/pull-kubernetes-node-e2e-kubetest2/1446852497472753664#1:build-log.txt%3A114

Using these args in kubetest2 via https://github.com/kubernetes-sigs/kubetest2/pull/169

### CODE REVIEW

**Comment by amwat** [comment]
let's see if pull-kubernetes-node-e2e-kubetest2 passes (or atleast goes past the error) on this PR

**Comment by amwat** [comment]
ohh this hasn't merged yet https://github.com/kubernetes/test-infra/pull/23995
poking @dims 

till then can we test it out here by making a commit like `ssh_user=${SSH_USER:-${USER}}` we can remove the commit before merging the PR (or we can even keep it)
``

**Comment by dims** [comment]
problem in ci job definition?

```
bash: [Slow]: command not found
sh: -c: line 0: unexpected EOF while looking for matching `"'
sh: -c: line 1: syntax error: unexpected end of file
```

**Comment by Namanl2001** [comment]
> problem in ci job definition?

Umm I don't think so....the main problem problem seems to be with SSH: `failed to run SSH command: out:`

```
failed to run SSH command: out: prow@35.233.245.207: Permission denied (publickey).
```
also
```
failed to run SSH command: out: ssh: connect to host 34.83.204.219 port 22: Connection refused
```

**Comment by dims** [comment]
ah ok

**Review by jlebon — COMMENTED** [review]
Hi! I was working on a related patch to this to add support for specifying the SSH key and more (as part of an effort to set up `test-e2e-node` [on Fedora CoreOS](https://github.com/coreos/fedora-coreos-tracker/issues/990)) so this is well-timed! Good to know there's some alignment with what I'd like to add. :)

I provided some feedback based on my experience so far hacking on these parts of the codebase, but might be missing context.

**Comment by amwat** [comment]
> Ahh fun, gotcha. That looks odd and prone to cause issues (like this one), though I'm sure there's a lot of history behind it.

yup, I guess setting something like `runAsUser` on the jobs would be more sophisticated but would be much more involved and have a large blast radius.

Back to the current failures, I think the 1 permission denied is a red herring, I also see it in non kubetest2 jobs
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/105712/pull-kubernetes-node-e2e-containerd/1450218726728142848/#1:build-log.txt%3A320

might be a quoting issue in the config.

/test pull-kubernetes-node-e2e-containerd-kubetest2

**Comment by Namanl2001** [comment]
reverted previous commit change: https://github.com/kubernetes/kubernetes/pull/105637/commits/c6e0564f53e19baf30fe6ef1fc841a723db57f73
 As it makes `pull-kubernetes-e2e-gce-ubuntu-containerd` to fail

**Comment by amwat** [comment]
looks like more quoting errors 😅 

```
... ./ginkgo  -nodes=8  -focus=""\[NodeConformance\]""  -skip=""\[Flaky\]|\[Slow\]|\[Serial\]"" ...
```

the makefile seems to be adding it's own quotes https://github.com/kubernetes/kubernetes/blob/6cbe18544d90c29d6b3e460dffa6d795a88257ae/hack/make-rules/test-e2e-node.sh#L57-L63

so we probably need to just pass it raw without any quotes

**Pull request merged**
