### PR TITLE
fix a small error in description

### PR DESCRIPTION
**Pull request by WanLinghao**
**What this PR does / why we need it**:
The example in create job subcommand lacks job-name, this patch fixes this
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by WanLinghao** [comment]
@deads2k @juanvallejo PTAL

**Review by juanvallejo — APPROVED** [review]

**Pull request merged**
