### PR TITLE
Automated cherry pick of #90645: kubeadm: fix flakes when performing etcd MemberAdd on slower

### PR DESCRIPTION
**Pull request by neolit123**
Cherry pick of #90645 on release-1.17.

#90645: kubeadm: fix flakes when performing etcd MemberAdd on slower

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by neolit123** [comment]
/kind bug
/priority important-soon
/assign @fabriziopandini 
@kubernetes/patch-release-team

**Comment by fabriziopandini** [comment]
Thanks @neolit123 for this fix.
This is a nice bug fix that could reduce bootstrap errors for users in case of temporary etcd problems.
/approve
/lgtm

**Comment by neolit123** [comment]
@kubernetes/patch-release-team 

this PR seems to have both `do-not-merge/cherry-pick-not-approved` and `cherry-pick-approved` and i think it missed the latest 1.17 patch release because of that. :thinking:

**Comment by tpepper** [comment]
> @kubernetes/patch-release-team
> 
> this PR seems to have both `do-not-merge/cherry-pick-not-approved` and `cherry-pick-approved` and i think it missed the latest 1.17 patch release because of that. 🤔

Argh.  Manually removing the label.

**Comment by justaugustus** [comment]
(Could've been a glitch in the matrix when GH services were flapping)

**Pull request merged**
