### PR TITLE
FIX Ceph RBD secret encode bug

### PR DESCRIPTION
**Pull request by xxyztwz**
Fix a small problem
[https://github.com/kubernetes/kubernetes/issues/24728](url)

### CODE REVIEW

**Comment by xxyztwz** [comment]
ok to test

**Comment by pmorie** [comment]
@k8s-bot ok to test

**Comment by pmorie** [comment]
@kubernetes/sig-storage

**Comment by rootfs** [comment]
why do you need to base64 encode the secret? Secret is already encoded.

**Comment by pmorie** [comment]
I have the same question as @rootfs

**Comment by saad-ali** [comment]
As @chakri-nelluri mentioned in the issue (https://github.com/kubernetes/kubernetes/issues/24728). The existing behavior is correct. The flex volume passes the secret to other volumes and thus needs to encode for a consistent API. RBD consumes the secret so that is not necessary.

**Comment by pmorie** [comment]
So then, sounds like we can close this?

**Comment by saad-ali** [comment]
> So then, sounds like we can close this?

@xxyztwz ?

**Pull request closed without merging**
