### PR TITLE
Update github.com/evanphx/json-patch to version v5.0.0

### LINKED ISSUE #91615: JSON patch with kubectl has exponential time complexity for nesting depth of manifest
**What happened**:

When updating a deeply nested CRD in a local k8s cluster with `kubectl apply`,
the command finishes after more than 5 minutes.
The CRD has a field like [`corev1.PodSpec`](https://godoc.org/k8s.io/api/core/v1#PodSpec).

I did a brief experiment for how the nesting depth of manifests affects computation time,
and found that JSON patch creation with `kubectl apply` has exponential time complexity for the depth.

**What you expected to happen**:

Finish updating deeply nested CRDs with `kubectl apply` in some seconds, at most 5s.

**How to reproduce it (as minimally and precisely as possible)**:

Please execute `kubectl apply -f https://gist.githubusercontent.com/tapih/f339a2d558cf49b0cd6320b7b2f1821b/raw/2fa11c4935f1976059c6517caef647115e1dcbda/crd.yaml` twice.
The second one will take too long to finish.

This is the detail of my experiment.

1. Create a `Foo` CRD project of which API version is `apiextensions.k8s.io/v1` with [kubebuilder](https://book.kubebuilder.io/quick-start.html).
2. Change the type definition of the CRD to have deeply nested slices.

```go
type FooSpec struct {
	// +optional
	T1 []T1 `json:"t1,omitempty"`
}

type T9 struct {
	// +optional
	T8 []T8 `json:"t8,omitempty"`
}

type T8 struct {
	// +optional
	T7 []T7 `json:"t7,omitempty"`
}

type T7 struct {
	// +optional
	T6 []T6 `json:"t6,omitempty"`
}

:

type T1 struct {
	// +optional
	Field string `json:"field"`
}
```

3. Run `make manifests` and create the CRD manifest.
4. Create a CRD object with `kubectl apply -f ./config/crd/bases/your.domain.name_foo.yaml`.
5. Update the CRD object with `kubectl apply -f ./config/crd/bases/your.domain.name_foo.yaml`.
6. Repeat this with incrementing the nesting depth of `FooSpec` like T1, T2, T3...T8.

The wall-clock time to finish the second `kubectl apply -f ./config/crd/bases/your.domain.name_foo.yaml` was as follow:

```
...
T4 => 0.1s
T5 => 1.2s
T6 => 8.7s
T7 => 68s
T8 => 544s
```

**Anything else we need to know?**:

https://github.com/evanphx/json-patch/pull/87 has already resolved this issue.
However, [kubernetes/kubernetes/go.mod](https://github.com/kubernetes/kubernetes/blob/413bc1a1d238efb7c4ba9e3aac2c381c93295aec/go.mod#L239) at master `HEAD` does not take this fix.

https://github.com/kubernetes/kubectl/issues/698 is about the same problem.
However, it was closed without fixing this problem.

**Environment**:
- Kubernetes version:  
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-02-07T01:05:17Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Hardware: VM on Hyper-V
- OS: Ubuntu 18.04
- Kernel: 4.15.0-66-generic
- Install tools: kind v0.8.1

### PR DESCRIPTION
**Pull request by tapih**
Signed-off-by:  Hiroshi Muraoka <h.muraoka714@gmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR fixes the bug that JSON patch with `kubectl apply` has exponential time complexity for the nesting depth of manifest.

**Which issue(s) this PR fixes**:
Fixes #91615 .

**Special notes for your reviewer**:
- I read the [code diff](https://github.com/evanphx/json-patch/compare/v4.2.0...v5.0.0) of `evanphx/json-patch`, and checked there was no breaking change.
- I confirmed that a [deeply nested CRD](https://gist.github.com/tapih/f339a2d558cf49b0cd6320b7b2f1821b) resource could be updated with `kubectl apply -f https://gist.githubusercontent.com/tapih/f339a2d558cf49b0cd6320b7b2f1821b/raw/2fa11c4935f1976059c6517caef647115e1dcbda/crd.yaml` on a v1.17.2 cluster created with kind.
- `github.com/evanphx/json-patch => github.com/evanphx/json-patch v4.2.0+incompatible` still exists in the `replace` block in `go.mod`.
  I suppose that this is because `sigs.k8s.io/kustomize` still imports `github.com/evanphx/json-patch`.

**Does this PR introduce a user-facing change?**:
```release-note
JSON patch implemented by https://github.com/evanphx/json-patch now conforms to RFC6902 replacement semantics and does not accept "replace" patch operations if the specified path does not exist.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by liggitt** [comment]
test failure looks legitimate:

```
=== RUN   TestWebhookReinvocationPolicyWithWatchCache/all_webhooks_reinvoked_when_any_webhook_reinvocation_causes_mutation
    --- FAIL: TestWebhookReinvocationPolicyWithWatchCache/all_webhooks_reinvoked_when_any_webhook_reinvocation_causes_mutation (0.07s)
        reinvocation_test.go:440: Internal error occurred: replace operation does not apply: doc is missing key: /metadata/labels/fight: missing value
```

is that an expected behavior change in json-patch?

**Comment by liggitt** [comment]
same issue was hit in https://github.com/kubernetes/kubernetes/pull/89988#issuecomment-611296066

**Comment by liggitt** [comment]
looks like an intentional change in https://github.com/evanphx/json-patch/pull/85

**Comment by liggitt** [comment]
it looks like the test is depending on invalid jsonpatch semantics, which is really unfortunate (it is likely real kubernetes clients exist that do so as well)

the following patch would likely fix the flawed test:
```diff
diff --git a/test/integration/apiserver/admissionwebhook/reinvocation_test.go b/test/integration/apiserver/admissionwebhook/reinvocation_test.go
index 8688cb67ac1..584ce7bcbc1 100644
--- a/test/integration/apiserver/admissionwebhook/reinvocation_test.go
+++ b/test/integration/apiserver/admissionwebhook/reinvocation_test.go
@@ -571,9 +571,9 @@ func newReinvokeWebhookHandler(recorder *invocationRecorder) http.Handler {
                case "/noop":
                        allow(w)
                case "/settrue":
-                       patch(w, `[{"op": "replace", "path": "/metadata/labels/fight", "value": "true"}]`)
+                       patch(w, `[{"op": "add", "path": "/metadata/labels/fight", "value": "true"}]`)
                case "/setfalse":
-                       patch(w, `[{"op": "replace", "path": "/metadata/labels/fight", "value": "false"}]`)
+                       patch(w, `[{"op": "add", "path": "/metadata/labels/fight", "value": "false"}]`)
                case "/addlabel":
                        labels := pod.GetLabels()
                        if a, ok := labels["a"]; !ok || a != "true" {
```

at a minimum, this needs a release note calling out the behavior change

**Comment by tapih** [comment]
@liggitt 
I fixed the integration test as you said, and wrote a release note in the PR comment which mentions to the internal change in https://github.com/evanphx/json-patch.

Then, the integration test now fails at a different line. Do you have any thoughts on [this error](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/91622/pull-kubernetes-integration/1267726014935470080)?
I thought the error comes from [here](https://github.com/tapih/kubernetes/blob/update-json-patch-v5.0.0/test/cmd/apply.sh#L150) at first glance, but I don't understand what's happening with the JUnit messages (so I'm now trying to run the integration test in my local environment with the development guide).

**Comment by liggitt** [comment]
both of those tests look like flakes

/retest

**Comment by kramvan1** [comment]
@liggitt What is the process for getting this back ported?  At least for the CLI and client.

**Comment by liggitt** [comment]
the compatibility break makes this problematic to backport

**Comment by lavalamp** [comment]
Personally, I think it should be OK for us to fix bugs. Just breaking people is like 100x easier for us.

However it could be REALLY awkward for users to keep their controllers working over an upgrade.

Is there really no way to fix the exponential behavior without completely upgrading the library? @logicalhan and/or @DirectXMan12 have fixed some similar exponential behavior in the past, I thought it was in this library or in the kubectl code that uses it but maybe I misremember.

This is a good example of why we want only standards-compliant functionality in our libraries. We have similar accidental support for extras in one or two other places. Personally I think that if we can fix this and break users, we should fix the others, too, in the same release, so that we don't have to do this again in the future.

I agree that breaking changes via backport have a super high bar and I don't think that this meets it.

**Comment by liggitt** [comment]
> However it could be REALLY awkward for users to keep their controllers working over an upgrade.

As best as I understand it, controllers should switch to use an "add" operation when they mean "set whether present or not", and that operation would work against old and new versions.

**Comment by lavalamp** [comment]
> As best as I understand it, controllers should switch to use an "add" operation when they mean "set whether present or not", and that operation would work against old and new versions.

Right, the change is simple, but knowing you have non-conformant controllers prior to breaking them by upgrading is NOT simple.

The controller authors and the cluster admin are probably not even the same people.

**Comment by logicalhan** [comment]
> Is there really no way to fix the exponential behavior without completely upgrading the library? @logicalhan and/or @DirectXMan12 have fixed some similar exponential behavior in the past, I thought it was in this library or in the kubectl code that uses it but maybe I misremember.

I think this may actually be my fix (https://github.com/evanphx/json-patch/pull/87). I had thought it was merged upstream already but it looks like I was mistaken.

**Comment by liggitt** [comment]
> I think this may actually be my fix ([evanphx/json-patch#87](https://github.com/evanphx/json-patch/pull/87)). I had thought it was merged upstream already but it looks like I was mistaken.

It looks like the same release that made that available (v4.6.0) included the RFC-honoring breaking change: https://github.com/evanphx/json-patch/compare/v4.5.0...v4.6.0

**Comment by logicalhan** [comment]
We can fork and cherry pick the exponential fix as one option. It's a really small delta.

**Comment by lavalamp** [comment]
Can we take an intermediate commit? Is there one with the right properties?

... worst case, we can make a temporary fork...

**Comment by liggitt** [comment]
looks like e83c0a1c26c884f8ec4fb743f6db92a941f605f1 merged Han's fix before the RFC changes

**Comment by logicalhan** [comment]
> looks like e83c0a1c26c884f8ec4fb743f6db92a941f605f1 merged Han's fix before the RFC changes

oh that's awesome. then we will not need this request: https://github.com/evanphx/json-patch/pull/85#issuecomment-640741129.

**Comment by mcristina422** [comment]
So the choice is to continue to not fully conform to RFC6902? Can we open a tracking issue for fully conforming to RFC6902 for if/when we do need to make the breaking change?

**Comment by lavalamp** [comment]
Well, we won't break old versions with a backport. What we do for 1.19 is still an open question IMO.

**Comment by tapih** [comment]
I rebased this branch with the master.
What's the next step??

**Comment by liggitt** [comment]
I think we should first try updating master to the SHA we intend to backport (e83c0a1c26c884f8ec4fb743f6db92a941f605f1). That can be done in a separate PR. Once that is in and backported, we can pick this back up and consider the implications of the RFC fix / compatibility break.

**Comment by kramvan1** [comment]
@liggitt How to track the back ports for this one?   And will it go back to 1.16, 1.17, 1.18?

**Comment by liggitt** [comment]
> @liggitt How to track the back ports for this one? And will it go back to 1.16, 1.17, 1.18?

https://github.com/kubernetes/kubernetes/pull/92069#issuecomment-647611443 is what will be backported. The backport PRs will be linked to that PR

**Comment by kramvan1** [comment]
@liggitt Thx for the response.

**Pull request closed without merging**
