### PR TITLE
Fix vagrant with etcd in pod

### LINKED ISSUE #6372: Move to Kubelet on Master running Etcd in Pod broke Vagrant
Self-assigning as I work out a reliable fix.

### PR DESCRIPTION
**Pull request by derekwaynecarr**
@csrwng - can you confirm this works for you on Mac from a fresh kube-up?

Closes https://github.com/GoogleCloudPlatform/kubernetes/issues/6372

### CODE REVIEW

**Comment by dchen1107** [comment]
@derekwaynecarr Sorry for breakage, and thanks for the fix.

**Comment by derekwaynecarr** [comment]
@dchen1107 - no problem... it's not a big deal to get kubelet, what hung me up was why in one instance systemd would not restart kubelet... i think we have a race condition in a part of kubelet where if docker does get stopped momentarily (like we do when installing our sdn) that kubelet went into a strange enough fail state that for some reason systemd was not restarting it.  i think its because docker was down at the same time, but i still need to investigate the root of that, but this appears to work stable enough for me, and if the kubelet fails at any time after initial startup, it does appear to be restarting as expected... good enough for development now.

**Comment by dchen1107** [comment]
Can you config systemd to periodically do a healthcheck to kubelet & docker like what I did through monit? I observed the similar race before between kubelet and docker, and healthchecking both daemon make sure they are not hang / unresponse does help.

**Comment by derekwaynecarr** [comment]
@dchen1107 - i am sure i can, or i can convert the monit scripts to not be init.d specific, but since i am not trying to build the most rock solid of deployments in vagrant, i am happy enough for now that this is stable on initial provision, in normal interaction docker/kubelet are getting restarted if killed, and if not, a kube-push will always get things happy again.

or to put another way, i am happy for someone in community to help with that, but i cant spend more time on it ;-)

anyway, i am self-merging this now, kube-up a number of times now and things are stable again.

**Pull request merged**
