### PR TITLE
update aws-sdk to support new region cn-northwest-1

### PR DESCRIPTION
**Pull request by eisig**
Update aws sdk to support region  cn-northwest-1 in China.

**What this PR does / why we need it**:
need newer aws-sdk  version to support new region cn-northwest-1

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by idealhack** [comment]
@eisig Thanks for your work. Please sign the CLA.

/sig aws

**Comment by eisig** [comment]
CLA is ok.

**Comment by idealhack** [comment]
/ok-to-test
/assign @sttts
@kubernetes/sig-aws-misc

**Comment by sttts** [comment]
/approve
for godep change.

**Pull request merged**
