### PR TITLE
Allow a DaemonSet pod template to be updated in storage. [LGTM]

### PR DESCRIPTION
**Pull request by madhusudancs**
Required for DaemonSet graduation as listed here - https://github.com/kubernetes/kubernetes/issues/15310#issuecomment-177062027

### CODE REVIEW

**Comment by bgrant0607** [comment]
cc @mikedanese @mml @janetkuo

**Comment by bgrant0607** [comment]
k8s.io/kubernetes/pkg/registry/daemonset/etcd test failed

**Comment by madhusudancs** [comment]
@bgrant0607 Removed that whole function.

**Comment by bgrant0607** [comment]
LGTM.

A test to verify that the template can be updated would be nice, though.

**Comment by bgrant0607** [comment]
Also waiting for the other PR to merge before applying the label.

**Comment by madhusudancs** [comment]
> A test to verify that the template can be updated would be nice, though.

I added a line here - [diff-f78176](https://github.com/kubernetes/kubernetes/pull/21101/files#diff-f78176ef5767abb1129386160a18e95dR106) that effectively tests template update and thought that would be sufficient. It is not that obvious though. Let me know if you think we need more tests.

**Pull request merged**
