### PR TITLE
delete new defined para name in fc volume

### PR DESCRIPTION
**Pull request by jianglingxia**
What type of PR is this?
/kind cleanup

**What this PR does / why we need it**:
there is no need defined new para name and logs info %q to %s
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jsafrane** [comment]
/approve
please rebase

**Comment by jianglingxia** [comment]
@jsafrane @msau42  can lable lgtm?thanks very much!

**Pull request merged**
