### PR TITLE
Remove NONE release notes in CHANGELOG 1.9

### PR DESCRIPTION
**Pull request by yuexiao-wang**
Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

**What this PR does / why we need it**:
There are some None release notes in 1.9. We should  fix none release notes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
-->
```release-note
NONE

```

### CODE REVIEW

**Comment by yuexiao-wang** [comment]
ping   @jbeda @lavalamp

**Comment by yuexiao-wang** [comment]
@jbeda  @lavalamp PTAL

**Comment by yuexiao-wang** [comment]
ping @Bradamant3

**Comment by yuexiao-wang** [comment]
@thockin PTAL

**Comment by yuexiao-wang** [comment]
ping @thockin

**Comment by xiangpengzhao** [comment]
These `NONE` lines can be removed directly, IMO.

**Comment by yuexiao-wang** [comment]
I will update

**Comment by yuexiao-wang** [comment]
@thockin PTAL

**Comment by yuexiao-wang** [comment]
@jbeda  any suggestion?

**Comment by yuexiao-wang** [comment]
@jbeda Could you approve this PR? Thanks

**Comment by yuexiao-wang** [comment]
@thockin Could you approve this PR? Thanks

**Pull request closed without merging**
