### PR TITLE
Automated cherry pick of #16497 upstream release 1.1

### PR DESCRIPTION
**Pull request by a-robinson**
Cross reference #16497

@zmerlynn

### CODE REVIEW

**Comment by a-robinson** [comment]
Huh, somehow the name got borked. Fixed.

**Comment by a-robinson** [comment]
@k8s-bot test this please

**Comment by a-robinson** [comment]
@k8s-bot test this please

**Comment by a-robinson** [comment]
pinging @zmerlynn

**Comment by zmerlynn** [comment]
LGTM

**Pull request merged**
