### PR TITLE
Fix Node soft-lockup

### PR DESCRIPTION
**Pull request by gmarek**
Ref. #37853

After those two reverts I can't reproduce kernel soft lockup using kubemark experiments.

This is a cherry-pick version of the fix.

cc @smarterclayton @mtaufen @vishh @sjenning @derekwaynecarr @smarterclayton @jeremyeder @timothysc @kubernetes/sig-node @fgrzadkowski @wojtek-t

### CODE REVIEW

**Comment by eparis** [comment]
The decision was made last night to gate this behind a flag if it turned out to be tickling the kernel bug. Not to revert. Remember, this patch is fine, so we need a path forward when the kernel gets fixed.

**Comment by eparis** [comment]
https://github.com/kubernetes/kubernetes/pull/38258

**Comment by timothysc** [comment]
shouldn't we just flag this as do-not-merge?

**Comment by derekwaynecarr** [comment]
The PR that flag gates this kernel feature is here: https://github.com/kubernetes/kubernetes/pull/38296

I prefer we take that change instead.

**Comment by thockin** [comment]
I also patched this out and it DID trigger for me.  I will try this exact PR.

**Comment by dims** [comment]
We can close this out i think since we merged https://github.com/kubernetes/kubernetes/pull/38296

**Comment by gmarek** [comment]
Yup.

**Pull request closed without merging**
