### PR TITLE
Refactor certificate controller to make approval an interface

### PR DESCRIPTION
**Pull request by smarterclayton**
@mikedanese

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37169)

### CODE REVIEW

**Comment by mikedanese** [comment]
LGTM but needs a rebase.

**Comment by smarterclayton** [comment]
@k8s-bot gce e2e test this

**Comment by smarterclayton** [comment]
@k8s-bot test this

**Comment by smarterclayton** [comment]
@k8s-bot test this issue #IGNORE

**Comment by smarterclayton** [comment]
reapplying label after trivial rebase

**Pull request merged**
