### PR TITLE
Cherry pick of #16025 to release-1.1

### LINKED ISSUE #21669: kubectl describe hpa broken
```
$ kubectl describe hpa php-apache
...
Min pods:			833358050696
...
```

### PR DESCRIPTION
**Pull request by piosz**
Fixed incorrect Min replicas value in kubectl describe

Fix #21669

### CODE REVIEW

**Comment by piosz** [comment]
cc @roberthbailey @zmerlynn

**Comment by zmerlynn** [comment]
I'm not sure this meets the cherry-pick bar. It's a fit and finish bug.

**Comment by piosz** [comment]
I'm fine with not merging this. @roberthbailey WDYT?

**Comment by dchen1107** [comment]
This is pretty straightforward fix. I am manually merging it to unblock our 1.1.8 cut. Thanks!

**Pull request merged**
