### PR TITLE
make client-go klog warning through callback

### LINKED ISSUE #94428: client-go prints a klog warning by default in library code which is not allowed
**What happened**:

A code change was merged that used `klog.Warningf` in library code by default (`NewDefaultClientLoadingRules` changed in a way that impacted all code in the world which uses that default, which is pretty common), which is not allowed by convention in Kube because client libraries may be used in UIs that wish to control output (klog is not consistent with other output).  The code change should have had a callback that allowed clients to optionally decide to print, not print to Warningf by default.

https://github.com/kubernetes/kubernetes/pull/78185#issuecomment-685765692

We should also document the convention for other reviewers that logging by default in client libraries is disallowed.

For instance, a callback would have allowed kubectl to print a human readable message `warning: KUBECONFIG does not exist` in general, and in specific cases (like `kubectl config` or login flows where KUBECONFIG not existing is totally reasonable) not print a message.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by vorburger**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #94428

#### Special notes for your reviewer:

This is my first ([non-doc](https://github.com/kubernetes/kubernetes/pulls/vorburger)) contribution here.

I'm also fairly new to Go - if there's a better way to do this, I'm happy to learn.

I am a maintainer on many other (non Kubernetes) open source projects.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by vorburger** [comment]
@smarterclayton would this be useful for #94428 ?

**Comment by vorburger** [comment]
Please note I wasn't clear if API backwards compatibility is a thing around here or not.

Based solely on reading #94428 I just assumed that's OK to go ahead and add an argument for the callback requested in the issue.

If that's not so, I'm happy to learn how this would typically be handle. New method name? Variadic function hack?

**Comment by fedebongio** [comment]
/triage accepted
Thank you for your first contribution!

**Comment by yliaog** [comment]
thanks for the pr,

it looks the following pr is fixing the same issue,
https://github.com/kubernetes/kubernetes/pull/95517

**Comment by soltysh** [comment]
Yes, this is duplicate, lemme see if author is still interested in completing it first. 
/hold

**Pull request closed without merging**
