### PR TITLE
federation: Remove manifests which are no longer used

### PR DESCRIPTION
**Pull request by shashidharatd**
Federation manifests files which are meant to be used by CI jobs are no longer used and are out-dated and no longer maintained. So removing them.

**Release note**:
```release-note
NONE
```

/cc @kubernetes/sig-federation-pr-reviews @madhusudancs

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Thanks!

/lgtm
/approve

**Comment by nikhiljindal** [comment]
@shashidharatd Do you have an issue for moving federation out of core?
Please file one if you dont have it already and refer it here.

**Comment by shashidharatd** [comment]
this pr is one of many to cleanup unused code in federation before we move federation related code to its own repo. here is the associated issue for [moving out federation out of core kubernetes](https://github.com/kubernetes/kubernetes/issues/52992)

**Comment by shashidharatd** [comment]
@spxtr, request an lgtm for the build related change.
/assign @spxtr

**Comment by shashidharatd** [comment]
@ixdy, this PR touches a little of build scripts to not package federation manifests into k8s release.
Could i request you to take a look and give lgtm from build scripts perspective. Thanks !
/assign @ixdy

**Pull request merged**
