### PR TITLE
[FEATURE-SERVERSIDE-APPLY] Refactor FieldManager code into single class

### PR DESCRIPTION
**Pull request by apelisse**
**What type of PR is this?**
/kind cleanup

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by apelisse** [comment]
Other things that I want to do on top of that:
- Unexport symbols from apply that shouldn't be used elsewhere (I suspect that's ALL of them but the `FieldManager`),
- Rename package apply into ... smd?
- Add tests :-/
- Test with the feature enabled

**Comment by jennybuckley** [comment]
in favor of #72066

**Pull request closed without merging**
