### PR TITLE
Add kubeup label instead of a feature label

### PR DESCRIPTION
**Pull request by upodroid**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Follow up from #121768

/cc @pohly @BenTheElder 

#### Which issue(s) this PR fixes:

Part of #120989 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pohly — APPROVED** [review]
/lgtm
/approve

**Comment by upodroid** [comment]
/retest
/hold cancel

PR created to update jobs

**Comment by pohly** [comment]
/hold

Let's lift the hold once that infra PR is merged. Can you add a link to it?

**Comment by pohly** [comment]
/hold cancel

Job was updated: https://github.com/kubernetes/test-infra/pull/31237

/assign @aojea 

For milestone.

**Comment by aojea** [comment]
OMG I lost all these changes , sorry , catching up

**Pull request merged**
