### PR TITLE
Automated cherry pick of #96417: Fix double counting of IP addresses

### PR DESCRIPTION
**Pull request by hvenev-vmware**
Cherry pick of #96417 on release-1.19.

#96417: Fix double counting of IP addresses

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fixes a regression in 1.19 double-counting IP address in the IPAM allocator
```

### CODE REVIEW

**Comment by aojea** [comment]
/hold 
/ok-to-test
until original PR merges

**Review by hasheddan — COMMENTED** [review]
/release-note none
/priority critical-urgent

**Comment by hvenev-vmware** [comment]
The original PR has been merged.

**Pull request merged**
