### PR TITLE
kubeadm: remove leftover DynamicKubeletConfig constant

### PR DESCRIPTION
**Pull request by neolit123**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

cleans up a constant that was leftover after the dynamic kubelet config feature gate was removed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
NONE

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/assign @rosti @fabriziopandini 
/priority backlog

### CODE REVIEW

**Comment by neolit123** [comment]
@kubernetes/sig-cluster-lifecycle-pr-reviews

**Review by yagonobre — APPROVED** [review]
Thanks!

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Comment by fabriziopandini** [comment]
@neolit123 thanks!
/approve
/lgtm

**Pull request merged**
