### PR TITLE
test: refactor remote test running

### PR DESCRIPTION
**Pull request by tzneal**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by tzneal** [comment]
@dims This is the PR with the AWS code removed. I believe that @upodroid tested the previous version of this, but I don't have a GCE account and haven't been able to test the changes.

**Comment by dims** [comment]
cc @adisky

**Review by upodroid — APPROVED** [review]
/lgtm

The E2E logic ran in the `pull-kubernetes-node-e2e-containerd` prow job and it is passing.

**Pull request merged**
