### PR TITLE
Fix addon-manager image build

### PR DESCRIPTION
**Pull request by imikushin**
addon-manager: remove `kube-addon-update.sh` from Dockerfile

the file no longer exists, so the build fails trying to add this file

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35338)

### CODE REVIEW

**Comment by luxas** [comment]
@k8s-bot ok to test

**Comment by luxas** [comment]
This LGTM

**Comment by imikushin** [comment]
@k8s-bot cvm gke e2e test this

**Comment by mikedanese** [comment]
@k8s-bot cvm gke e2e test this

**Pull request merged**
