### PR TITLE
Remove the dependency between create deploy command and generators

### PR DESCRIPTION
**Pull request by aubm**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

@soltysh mentioned in the Slack `#sig-cli` channel that he'd like the create sub commands to get rid of their dependency to the generators, and ultimately remove them entirely.

This work is an attempt to do just that for the `kubectl create deploy` command.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

The work is inspired from the `kubectl create job` command. Getting rid of  `CreateSubcommandOptions` results in a few duplicated boilerplate code, especially in the `Complete` method and in the dry run logic in the `Run` method. I reckon that `CreateSubcommandOptions` is meant to avoid duplicating the logic around `o.StructuredGenerator.StructuredGenerate()`, maybe once the other create sub commands are rewritten without the generators, we can reevaluate what can be factorized?

This PR removes the support for alternative deployment generators, I guess I can put it back but as it is already marked as deprecated, I wanted a confirmation that it is expected to be maintained.

I found unit tests to be a bit flaky. I was surprised not to see this assertion fail : `assert.Error(t, err, "at least one image must be specified")` in `TestCreateDeploymentNoImage`. I meant to rewrite them by leveraging a fake HTTP server in order to create assertions on the received request payload (directly comparing the create deployment json payload), but I wanted to get a first impression on the work first. Also I figured that maybe it could be part of a separate PR?

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/ok-to-test
/lgtm
/approve

**Comment by zhouya0** [comment]
/lgtm 
Just a little question about whether `kubectl creat deployment ` should support multiple images or not, because https://github.com/kubernetes/kubernetes/pull/91113 seems only image is required.
And I also would like to have a function like `createDeployment()` to build deployment spec. 
Anyway, as https://github.com/kubernetes/kubernetes/pull/91113 is based on this PR, let's  merge it first.

**Pull request merged**
