### PR TITLE
apiserver: update borrowing parameters for apf bootstrap objects

### PR DESCRIPTION
**Pull request by tkashem**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
update borrowing parameters for APF bootstrap objects, as dictated in the KEP https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/1040-priority-and-fairness/README.md#dispatching

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by MikeSpreitzer — APPROVED** [review]
/LGTM

**Comment by MikeSpreitzer** [comment]
This would build and run successfully if it _were actually_ based on #113830 .

**Comment by tkashem** [comment]
@MikeSpreitzer I did another rebase on top of https://github.com/kubernetes/kubernetes/pull/112830 and tested it locally. CI should fail for this now as expected, once 112830 merges it should be green and ready to be tagged

**Review by MikeSpreitzer — APPROVED** [review]
(assuming CI will hold this until after the API change.)
/LGTM

**Comment by tkashem** [comment]
/close

it was included in https://github.com/kubernetes/kubernetes/pull/113485

**Pull request closed without merging**
