### PR TITLE
Fixing unbound bash variable.

### PR DESCRIPTION
**Pull request by Q-Lee**
**What this PR does / why we need it**: this fixes a bug introduced in 1.6 for ABAC.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**: without this, we hit an unbound variable and fail to bring up the kube-apiserver with ABAC enabled.

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by Q-Lee** [comment]
A block of code moved around, and ${src_dir} wasn't bound early enough. We should cherry-pick this for 1.6.

**Comment by Q-Lee** [comment]
@k8s-bot kops aws e2e test this

**Comment by Q-Lee** [comment]
@k8s-bot kops aws e2e test this

**Comment by Q-Lee** [comment]
Adding v1.6 milestone, because this is an important bug fix.

**Comment by gmarek** [comment]
@k8s-bot node e2e test this

**Pull request merged**
