### PR TITLE
Add the ability to customize federation system namespace in e2e turn up scripts.

### PR DESCRIPTION
**Pull request by madhusudancs**
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by madhusudancs** [comment]
@k8s-bot cvm gce e2e test this

**Comment by enisoc** [comment]
Note that we have stopped doing fast-forwards. If this needs to go into the release-1.6 branch, please apply the cherrypick-candidate label.

Please also indicate whether you think this is a blocker for v1.6.0 and if so, why. Otherwise, this should be moved to the v1.6.1 milestone.

**Comment by madhusudancs** [comment]
@enisoc sure, thanks for the update.

**Comment by enisoc** [comment]
Since you did not apply cherrypick-candidate, I will assume this is not targeting v1.6.0.

**Comment by madhusudancs** [comment]
This is a test change. We will eventually need to cherry-pick this. But I do not want to destabilize 1.6 branch  until we are absolutely sure that this doesn't destabilize master.

**Pull request merged**
