### PR TITLE
dockershim: remove corrupt checkpoints immediately upon detection

### PR DESCRIPTION
**Pull request by sjenning**
Fixes https://github.com/kubernetes/kubernetes/issues/55620

The current checkpoint abstraction leaks the handling of corrupt checkpoints to the user.

If the user does a `GetCheckpoint()` and the checkpoint is corrupt, the corrupt checkpoint is returned to the user (why??) with an error indicating the corruption.  It is then up to the user to detect the corruption via the error msg and call `RemoveCheckpoint()` to remove the corrupted checkpoint.

The checkpoint abstraction should not expose corruption to the user.  If it is corrupt, it is as good as not found to the user.  The checkpoint code should handle cleanup of corrupt entries and report "not found" to the user.

@derekwaynecarr @eparis @dcbw @freehan

### CODE REVIEW

**Comment by sjenning** [comment]
fyi @jupierce

**Comment by yujuhong** [comment]
> If the user does a GetCheckpoint() and the checkpoint is corrupt, the corrupt checkpoint is returned to the user (why??) with an error indicating the corruption. It is then up to the user to detect the corruption via the error msg and call RemoveCheckpoint() to remove the corrupted checkpoint.

I think the caller may choose to handle the corruption error different in some cases, but since the code here doesn't do much, it makes sense to remove the corrupt checkpoint as early as possible. 

The changes look good, but we may want to patch 1.8 as well. 
Please update the bazel files.

**Comment by derekwaynecarr** [comment]
Pending fix of golint, this is lgtm.  This is a much less brittle implementation.

**Comment by yujuhong** [comment]
@sjenning could you cherrypick this to 1.8? Thanks!

**Pull request merged**
