### PR TITLE
Fix waiting for CRD sync at server start

### LINKED ISSUE #118103: APIServices can be deleted at the apiserver startup
### What happened?

Initially reported at 1.24.10, but it seems to be present in master as well:

We observe that a part of apiservices objects have been removed by "system:apiserver" right after the kubernetes upgrade.

It looks like there is race between "autoregister controller" [1] deleting apiservices and "crd-autoregister controller" populating a map of desired apiservices, i.e. in logs we see:
```
INFO 2023-05-16T14:21:35.070841Z Starting autoregister controller
INFO 2023-05-16T14:21:35.070858Z Waiting for caches to sync for autoregister controller
INFO 2023-05-16T14:21:35.071116Z Starting crd-autoregister controller
INFO 2023-05-16T14:21:35.071128Z Waiting for caches to sync for crd-autoregister
INFO 2023-05-16T14:21:35.270943Z Caches are synced for autoregister controller
INFO 2023-05-16T14:21:35.471323Z Caches are synced for crd-autoregister
```

The unwanted APIServices delete happened at 14:21:35.438 GMT so between crd-autoregister sync and autoregister controller.

It looks like we attempt to wait with "autoregister controller" for crd-autoregister to initialize here: https://github.com/kubernetes/kubernetes/blob/5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02/cmd/kube-apiserver/app/aggregator.go#L148-L154

but for some reason we don't enter the if branch.

@liggitt tried adding this diff at HEAD:
```
diff --git a/cmd/kube-apiserver/app/aggregator.go b/cmd/kube-apiserver/app/aggregator.go
index 397c151e66a..8b755ab3179 100644
--- a/cmd/kube-apiserver/app/aggregator.go
+++ b/cmd/kube-apiserver/app/aggregator.go
@@ -148,7 +148,11 @@ func createAggregatorServer(aggregatorConfig *aggregatorapiserver.Config, delega
 			// this prevents the autoregistration controller's initial sync from deleting APIServices for CRDs that still exist.
 			// we only need to do this if CRDs are enabled on this server.  We can't use discovery because we are the source for discovery.
 			if aggregatorConfig.GenericConfig.MergedResourceConfig.ResourceEnabled(apiextensionsv1.SchemeGroupVersion.WithResource("customresourcedefinitions")) {
+				klog.Infof("waiting for initial CRD sync...")
 				crdRegistrationController.WaitForInitialSync()
+				klog.Infof("initial CRD sync complete...")
+			} else {
+				klog.Infof("CRD API not enabled, starting APIService registration without waiting for initial CRD sync")
 			}
 			autoRegistrationController.Run(5, context.StopCh)
 		}()
```
and then started a default cluster with local-up-cluster gave:
```
I0518 08:31:16.826743   94479 aggregator.go:155] CRD API not enabled, starting APIService registration without waiting for initial CRD sync
```

which suggest we have a bug in master and the bug is around the "customresourcedefinitions if"

### What did you expect to happen?

APIServices are not deleted, there is no race between crd-autoregister and autoregister controllers

### How can we reproduce it (as minimally and precisely as possible)?

Restart apiserver with apiservices from crds?

Add a patch proposed by liggit@ and watch the initialization race.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
1.24.10 but also seems to be present in master
</details>

### Cloud provider

<details>
gce/local-up-cluster
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind bug
/priority critical-urgent

#### What this PR does / why we need it:

Fixes logic checking whether we should wait for CRD sync at server start before reconciling APIService objects

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/118103

Test commit best reviewed ignoring whitespace (https://github.com/kubernetes/kubernetes/pull/118104/files?w=1)

#### Does this PR introduce a user-facing change?
```release-note
Fixes a bug at kube-apiserver start where APIService objects for custom resources could be deleted and recreated.
```

/assign @deads2k
/sig api-machinery

### CODE REVIEW

**Comment by liggitt** [comment]
verified this resolves the issue by starting a server and looking at logs, but need to figure out how to exercise this with a test

**Comment by liggitt** [comment]
added an integration test and ensured it failed on master without the startup fix

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by liggitt** [comment]
forgot to close the etcd client I created in the integration test, pushed test fix

**Review by logicalhan — COMMENTED** [review]
/lgtm

**Comment by liggitt** [comment]
picks open:

* 1.27: https://github.com/kubernetes/kubernetes/pull/118111
* 1.26: https://github.com/kubernetes/kubernetes/pull/118112
* 1.25: https://github.com/kubernetes/kubernetes/pull/118113
* 1.24: https://github.com/kubernetes/kubernetes/pull/118114

**Pull request merged**
