### PR TITLE
Manually cherry pick of #125398: [scheduler] When the hostname and nodename of a node do not match, ensure that pods carrying PVs with nodeAffinity are scheduled correctly. 

### PR DESCRIPTION
**Pull request by AxeZhan**
Cherry pick of #125398 on release-1.28.

#125398: [scheduler] When the hostname and nodename of a node do not match, ensure that pods carrying PVs with nodeAffinity are scheduled correctly.

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fix a bug when the hostname label of a node does not match the node name, pods bound to a PV with nodeAffinity using the hostname may be scheduled to the wrong node or experience scheduling failures.
```

### CODE REVIEW

**Comment by AxeZhan** [comment]
/assign @msau42 
For sig/storage

**Comment by saschagrunert** [comment]
v1.28 is EOL, closing

**Pull request closed without merging**
