### PR TITLE
add list of served versions to storage version

### PR DESCRIPTION
**Pull request by deads2k**
wire the served group/versions from the installation flow.

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
I think the concept here works, but even with master I'm seeing

```
	logging error output: "k8s\x00\n\f\n\x02v1\x12\x06Status\x12\xa4\x01\n\x06\n\x00\x12\x00\x1a\x00\x12\aFailure\x1azwait for storage version registration to complete for resource: apiservices.apiregistration.k8s.io, last seen error: <nil>\"\x12ServiceUnavailable0\xf7\x03\x1a\x00\"\x00"

E0712 18:30:09.606112  195781 autoregister_controller.go:195] v1beta3.flowcontrol.apiserver.k8s.io failed with : wait for storage version registration to complete for resource: apiservices.apiregistration.k8s.io, last seen error: <nil>
I0712 18:30:09.618766  195781 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes,poststarthook/priority-and-fairness-config-producer,poststarthook/built-in-resources-storage-version-updater,autoregister-completion check failed: readyz
[-]poststarthook/rbac/bootstrap-roles failed: not finished
[-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
[-]poststarthook/priority-and-fairness-config-producer failed: not finished
[-]poststarthook/built-in-resources-storage-version-updater failed: not finished
[-]autoregister-completion failed: missing APIService: [v1. v1.admissionregistration.k8s.io v1.apiextensions.k8s.io v1.apps v1.authentication.k8s.io v1.authorization.k8s.io v1.autoscaling v1.batch v1.certificates.k8s.io v1.coordination.k8s.io v1.discovery.k8s.io v1.events.k8s.io v1.networking.k8s.io v1.node.k8s.io v1.policy v1.rbac.authorization.k8s.io v1.scheduling.k8s.io v1.storage.k8s.io v1beta2.flowcontrol.apiserver.k8s.io v1beta3.flowcontrol.apiserver.k8s.io v2.autoscaling]
```

When I try `FEATURE_GATES=StorageVersionAPI=true,APIServerIdentity=true hack/local-up-cluster.sh`

**Comment by deads2k** [comment]
oh, I bet I didn't enable the API with runtime-config `retry 2, failed to update storage version for podtemplates.core: the server could not find the requested resource (post storageversions.internal.apiserver.k8s.io)`

**Comment by deads2k** [comment]
This works, will clean up tomorrow.  I think it's simpler than looping back.

**Comment by deads2k** [comment]
/hold cancel

this was cleaned up

/kind cleanup

**Comment by Richabanker** [comment]
thanks a lot for this clean and quick patch @deads2k !

**Pull request merged**
