### PR TITLE
Bumped Heapster to v1.1.0-beta1

### PR DESCRIPTION
**Pull request by piosz**
should help for #22176

### CODE REVIEW

**Comment by piosz** [comment]
I've also re-added version to deployment names to make sure it works with kube-addon updater script, which was removed in #22893.

cc @Q-Lee

**Comment by piosz** [comment]
cc @mwielgus

**Comment by fgrzadkowski** [comment]
LGTM

**Comment by wojtek-t** [comment]
Merging manually to help with autoscaling tests.

**Pull request merged**
