### PR TITLE
Update cluster autoscaler image to 1.16.0-beta.1

### PR DESCRIPTION
**Pull request by losipiuk**
This PR updates CA version in gce manifests to 1.16.0-beta.1

We need to merge it during freeze because, Cluster Autoscaler imports large amount of k8s code to simulate scheduler behavior, yet it lives in separate repository. Therefore
we need to build final release candidate just at the end of k8s release cycle.

We verified image manually yet the manifest in `cluster/gce/manifests/cluster-autoscaler.manifest` needs to be updated to trigger e2e tests run. If those prove that thera are no issues with new release, we will send out yet another PR which updates the image to non-beta version. The release notes will be provided in that followup PR.

/kind bug
/priority critical-urgent
/sig autoscaling
/assign @mwielgus

```release-note
NONE
```

### CODE REVIEW

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by liggitt** [comment]
A few questions:
- What's the timeframe for updating this to a non-beta tag? 
- Is this exercised in CI before merge?
- If problems are discovered, would resolving them block cutting a release candidate? Would reverting to the 1.15.0 tag be reasonable in that scenario?

**Comment by losipiuk** [comment]
> A few questions:
> 
> * What's the timeframe for updating this to a non-beta tag?

If E2E tests (https://k8s-testgrid.appspot.com/sig-autoscaling-cluster-autoscaler#gci-gce-autoscaling) show everything is fine I will cut the non-beta release (just with version update) early next week (Mon/Tue).

> * Is this exercised in CI before merge?

No. Unfortunately current release process of CA is far from perfect. To have a full E2E test coverage we need to bump the image in cluster-autoscaler.manifest (which this PR does).
I did the basic manual testing though.

> * If problems are discovered, would resolving them block cutting a release candidate? Would reverting to the 1.15.0 tag be reasonable in that scenario?

If tests will show that 1.16-beta.1 is broken (in a way that cannot be immediately fixed) then reverting to 1.15 will be reasonable step. Generally we should run CA in version which matches k8s minor. The reason for that is that CA is vendoring scheduler code and simulates its behavior. We want the simulated decisions to be as accurate as possible. 
Yet even older version which is working (at least to extent covered by tests) is better than one which is up-to-date but broken.

**Comment by losipiuk** [comment]
>> Is this exercised in CI before merge?
> No. Unfortunately current release process of CA is far from perfect. To have a full E2E test coverage we need to bump the image in cluster-autoscaler.manifest (which this PR does). I did the basic manual testing though.

It seem to make sense to add add a presubmit which would run the tests shown on https://k8s-testgrid.appspot.com/sig-autoscaling-cluster-autoscaler#gci-gce-autoscaling to PRs which change the `cluster-autoscaler.manifest`.

**Comment by lachie83** [comment]
👋 1.16 release lead here. Heads up that this PR currently 1.16 release-blocking. We are a little over 48 hours out from cutting 1.16.0-rc.1 and code thaw (Tuesday, September 10). Please prioritize this accordingly so we can ensure clean CI-Signal before cutting rc.1

**Comment by losipiuk** [comment]
@lachie83 as for presubmit job I rather meant next minor release. Can we finish the current process (I agree it is suboptimal) for this release. And work work on presubmit CI definition after 1.16 is cut?

**Comment by losipiuk** [comment]
> Lachlan Evenson as for presubmit job I rather meant next minor release. Can we finish the current process (I agree it is suboptimal) for this release. And work work on presubmit CI definition after 1.16 is cut?

I prepared a PR to add presubmit job (https://github.com/kubernetes/test-infra/pull/14238) - yet given how late it is I have low hopes I can get it tested and merged before 1.16 release. As mentioned in previous comment I would opt for postsubmit validation this time. And move to presubmit for patch releases and 1.17.

**Comment by lachie83** [comment]
@losipiuk - Thanks for the updates. Can you please get the approval as soon as possible so we can get 24h of CI-Signal once this is merged?

**Comment by losipiuk** [comment]
Thanks for merging. Tests are running with new CA already (https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling/1170942041002086402). So far good. I will keep an eye on that and keep you posted.

**Comment by lachie83** [comment]
Looks like it failed. Please let us know the next steps.

**Comment by liggitt** [comment]
looks like that is an existing flake (40% of the previous 10 runs failed the same test with the same error)

**Comment by losipiuk** [comment]
Yeah - looks like flake. Another run is in progress. Hopefully green. I would leave the updated image anyway.
I will prepare a PR which bumps the version to 1.16.0 (without beta.1 suffix) image with no code changes.

**Comment by losipiuk** [comment]
Next run is green.

**Pull request merged**
