### PR TITLE
Revert "Revert "bump golang.org/x/oauth2""

### PR DESCRIPTION
**Pull request by nikhita**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Re-applies https://github.com/kubernetes/kubernetes/pull/114822/, which was reverted in https://github.com/kubernetes/kubernetes/pull/114829.

/hold
Will need https://github.com/kubernetes/publishing-bot/pull/305 for the publishing-bot to be fixed first.

xref https://github.com/kubernetes/kubernetes/issues/113366, https://github.com/kubernetes/publishing-bot/issues/304

```release-note
NONE
```

/cc @dims  @liggitt

### CODE REVIEW

**Comment by nikhita** [comment]
/hold
https://github.com/kubernetes/publishing-bot/pull/305#discussion_r1062414743

**Comment by liggitt** [comment]
/hold

I'm not sure about the way the publishing bot got fixed. Seems like tidy should work without hijinks or we risk other consumers of the staging repos hitting issues.

**Comment by nikhita** [comment]
Closing. We'll need to fix https://github.com/kubernetes/kubernetes/issues/113366 avoid breaking the publishing-bot again.

**Pull request closed without merging**
