### PR TITLE
Move kubelet volume code to volumes.go

### PR DESCRIPTION
**Pull request by pmorie**
Chipping away at the boulder again, hoping to pare down kubelet.go to just the skeleton.

@kubernetes/sig-node @kubernetes/sig-storage

### CODE REVIEW

**Comment by swagiaal** [comment]
@pmorie can you hold off on this for a bit. It will cause a lot of conflicts for me. Also I am trying to encapsulate all the volume code within volume_manager so I might need to move these functions in a different direction

**Comment by pmorie** [comment]
@swagiaal what is the dependency and how far out is it?

**Comment by swagiaal** [comment]
@pmorie first there is this #24036. The second thing (encapsulation of volume code in volume_manager) is the first step in the implementation of #21931 which is sitting in a local branch which I have not pushed yet

**Comment by pmorie** [comment]
@swagiaal does it help to know you're probably going to have to rebase already? :)  check to see if you don't already have conflicts, i'd bet $1 that you do

**Comment by pmorie** [comment]
for the record that is one loonie

**Comment by swagiaal** [comment]
> @swagiaal does it help to know you're probably going to have to rebase already?

hmm.. I am sure I do but this change but this change is guaranteed to introduce more. I would appreciate it if you could hold off on it

**Comment by swagiaal** [comment]
> for the record that is one loonie

1.25 loonies in fact! :).. I cannot gamble with that kinda money

**Comment by pmorie** [comment]
@dchen1107 PTAL

**Comment by pmorie** [comment]
Actually, I am going to close this, having found an end result I want to do better

**Comment by yujuhong** [comment]
I really want volumes to be in a separate package, but this is a step forward regardless :-)

**Comment by pmorie** [comment]
@yujuhong check out #25028

**Pull request closed without merging**
