### PR TITLE
Using const() defines constants together

### PR DESCRIPTION
**Pull request by xichengliudui**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by SataQiu** [comment]
Thanks @xichengliudui 
/lgtm

**Review by thockin — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
