### PR TITLE
Use EventTypeWarning instead of EventTypeNormal when failure

### PR DESCRIPTION
**Pull request by FengyunPan**

### CODE REVIEW

**Review by xiangpengzhao — APPROVED** [review]

**Comment by nikhiljindal** [comment]
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
Looks like these were missed in https://github.com/kubernetes/kubernetes/pull/44083

/lgtm
/approve

**Comment by NickrenREN** [comment]
Yes,they were introduced revently some in #41050

**Pull request merged**
