### PR TITLE
Update etcd default ports for v3, and validate tests

### PR DESCRIPTION
**Pull request by timothysc**
This PR simply updates the ports to switch from legacy 4001 to etcd3 default 2379.  This probably should have been updated a while ago.  

Same rules apply on this PR as #30508, there are legacy references that need addressing outside this scope.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30514)

### CODE REVIEW

**Comment by timothysc** [comment]
self applying from comments.

**Comment by wojtek-t** [comment]
@timothysc - is it really the case that 2379 port is the one? I've always used 4001 port. I don't really understand this change.

@xiang90 @hongchaodeng - can you shed light on it?

**Comment by xiang90** [comment]
@wojtek-t 2379 is the official port. 4001 has been deprecated for more than a year or so.

**Comment by timothysc** [comment]
So this is weird, I need to change the 'old-docs' b/c it affects the tests... 
 
```make test-cmd``` reaches into docs. 

@eparis - is there a process to ignore the bot for this case?

**Comment by eparis** [comment]
1. find someone to merge by hand
better yet
2. update https://github.com/kubernetes/contrib/blob/master/mungegithub/block-path.yaml to allow the file in question..

**Comment by timothysc** [comment]
@wojtek-t any objections?  The reason for the change is I found issues in the node e2es, that someone else caught and figured since we are making the change we should pay down the technical debt.

**Comment by timothysc** [comment]
This will need to be explicitly merged.  It appears the bot either hasn't reloaded or something about the regex is incorrect.

**Comment by wojtek-t** [comment]
Sorry - it was a holiday in Poland yesterday.

LGTM

**Comment by timothysc** [comment]
@wojtek-t this will need to be merged by hand.  The bot seems to be having an issue with an update to a docs file.  That file is called by our tests in this repo so it's not really a doc.

**Comment by timothysc** [comment]
@krousey This is the issue that needs a bot-reset with the updated rules.   Either that or explicit merge, already lgtm.

**Comment by wojtek-t** [comment]
LGTM

This needs to be manually merged. Merging.

**Pull request merged**
