### PR TITLE
kubectl/cmd: remove a bunch of unused parameters

### PR DESCRIPTION
**Pull request by mvdan**
Found with github.com/mvdan/unparam.

**Release note**: NONE

### CODE REVIEW

**Comment by mvdan** [comment]
Boy those are a lot of comments. Signed it.

**Comment by soltysh** [comment]
The change itself, lgtm, @mvdan mind updating your PR?

**Comment by mvdan** [comment]
@soltysh done

**Comment by soltysh** [comment]
@k8s-bot ok to test

**Comment by mvdan** [comment]
Rebased again and fixed the test builds.

**Comment by soltysh** [comment]
@mvdan you are failing bazel build, still.

**Comment by mvdan** [comment]
@soltysh apologies, finally done

**Comment by mvdan** [comment]
bump - needs an additional approver?

**Comment by soltysh** [comment]
@nikhiljindal can you approve the federation part, it's pretty simple change.

**Comment by mvdan** [comment]
bump @nikhiljindal

**Pull request merged**
