### PR TITLE
mount teamcity git workspace if running in TC

### LINKED ISSUE #767: TC smoke tests broken
- fixed here: https://github.com/kubernetes/kubernetes/pull/20683
  - investigation: https://github.com/kubernetes/kubernetes/pull/20531

### PR DESCRIPTION
**Pull request by jdef**
fixes https://github.com/mesosphere/kubernetes-mesos/issues/767

### CODE REVIEW

**Comment by jdef** [comment]
@k8s-oncall any chance to get a quick merge on this? it resolves a mesos-only CI system bug and will allow us to re-enable smoke testing for commits merged to k8s/master ASAP.

**Comment by lavalamp** [comment]
Sure.

**Comment by jdef** [comment]
thanks @lavalamp

**Pull request merged**
