### PR TITLE
Update ubuntu-calico getting started guide

### PR DESCRIPTION
**Pull request by luke-mino-altherr**
Fix the way we get kube_proxy

### CODE REVIEW

**Comment by L-MA** [comment]
I am part of the company Metaswitch Networks

**Comment by mikedanese** [comment]
Can you please describe what is broken about the original approach?

**Comment by L-MA** [comment]
Calling `sudo wget https://github.com/projectcalico/calico-kubernetes/releases/download/v0.1.1/kube-proxy -P /usr/bin/` downloads the kube_proxy directly into `/usr/bin`; however, since a kube_proxy already exists there, wget renames the newly downloaded file to kube_proxy.1. This can easily be overlooked and the user will continue to use the incorrect version of kube_proxy. This PR ensures that the kube_proxy is replaced with the version we want.

**Comment by mikedanese** [comment]
@L-MA Thanks for the explanation. LGTM.

**Pull request merged**
