### PR TITLE
Update selenium docker images

### PR DESCRIPTION
**Pull request by aledbf**
**What this PR does / why we need it**:

Updates selenium docker images (2.47 was released a year ago)

**Which issue this PR fixes**
-

**Special notes for your reviewer**:
-

**Release note**:
`NONE`

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37701)

**Comment by rmmh** [comment]
@k8s-bot verify test this
@k8s-bot kubemark e2e test this

**Pull request merged**
