### PR TITLE
Fix typo for ServiceAccount

### PR DESCRIPTION
**Pull request by corehello**
What type of PR is this?
/kind bug

What this PR does / why we need it:
Fix typo

Which issue(s) this PR fixes:

Fixes #

fix typo for ServiceAccount

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
```release-note
NONE
```

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm

**Comment by MikeSpreitzer** [comment]
https://github.com/kubernetes/kubernetes/issues/97002

**Comment by liggitt** [comment]
/approve

@lavalamp, can you recommend approvers for the flowcontrol package to keep things like this from bubbling all the way up to the top of the component

**Comment by lavalamp** [comment]
> can you recommend approvers for the flowcontrol package to keep things like this from bubbling all the way up to the top of the component

I think @MikeSpreitzer, @yue9944882, @deads2k, and myself would be good for a new owners file here. I was actually talking to Mike about this a few days ago.

**Pull request merged**
