### PR TITLE
Set Calico MTU to 1460 on GCE

### PR DESCRIPTION
**Pull request by caseydavenport**
**What this PR does / why we need it**:

GCE uses an MTU of 1460, but Calico defaults to 1500. Set the value used by Calico to match.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
That location doesn't seem to be GCE specific, and hardcoding it bound to break one day - should this be something that the CNI plugin itself does dynamically?  E.g. on-host default-route PMTU discovery ? :)

**Comment by caseydavenport** [comment]
> That location doesn't seem to be GCE specific

D'oh, yes. That's true. Though, I don't believe these specific manifests are tested on anything but GCE.

> should this be something that the CNI plugin itself does dynamically

Yes, probably although it doesn't do it today. This seems like the quickest workaround while something more dynamic is added to the plugin.

**Comment by thockin** [comment]
I'm concerned that we don't know who is using this, so making a hard-coded change like this is potentially impactful.

@jingax10 

What would be involved in fixing it "right" ?

**Comment by jingax10** [comment]
Thanks @caseydavenport! I have #65024, which would allow GKE specifies custom MTU.

**Comment by caseydavenport** [comment]
> What would be involved in fixing it "right" ?

At a glance doing some auto-discovery in the CNI plugin sounds "right" but I suspect there might be more complexity than meets the eye due to the number of environments in which the Calico CNI plugin needs to work (with+without Calico BGP networking, ipip encapsulation, flannel, multiple host interfaces, etc).

I'm not against pursuing it, but it's not going to be a quick change.

>  I have #65024, which would allow GKE specifies custom MTU.

I think this sounds like a good solution for GKE for now.

**Comment by thockin** [comment]
Did this get fixed?

**Comment by caseydavenport** [comment]
I believe @jingax10 was going to fix this for GKE using the machinery added in https://github.com/kubernetes/kubernetes/pull/65024

**Pull request closed without merging**
