### PR TITLE
Automated cherry pick of #79446: Fix AWS DHCP option set domain names causing garbled

### PR DESCRIPTION
**Pull request by wongma7**
Cherry pick of #79446 on release-1.12.

#79446: Fix AWS DHCP option set domain names causing garbled

### CODE REVIEW

**Comment by jsafrane** [comment]
I don't think we still support 1.12: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#supported-releases-and-component-skew

**Comment by wongma7** [comment]
yes I think I missed the boat on 1.12.x. https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#112 . Closing for now, will try to confirm.

**Comment by wongma7** [comment]
@kubernetes/patch-release-team is there going to be a 1.12.11?

**Comment by hoegaarden** [comment]
@wongma7 `1.12.10` will be the last release of the `1.12` line

**Pull request closed without merging**
