### PR TITLE
Automated cherry pick of #52324:Fix bug:Kubelet failure to umount mount points

### PR DESCRIPTION
**Pull request by linyouchong**
Cherry pick of #52324 on release-1.9.
#52324 Fix bug:Kubelet failure to umount mount points

Release note:
```
Fix bug: kubelet failure to unmount corrupted mount points
```

### CODE REVIEW

**Comment by mbohlool** [comment]
@linyouchong this is not a test PR and deserve a release note. Please add a release note to the parent PR.

**Comment by linyouchong** [comment]
@mbohlool DONE

**Comment by mbohlool** [comment]
PR still needs usual approval/lgtm. just a reminder that 1.9.3 deadline is monday 5pm.

**Comment by linyouchong** [comment]
@saad-ali need approval/lgtm, thank you!

**Comment by qmfrederik** [comment]
@saad-ali Any chance we can get this in 1.9.3? This fix would be really helpful to us. Thanks!

**Comment by mbohlool** [comment]
/hold

the release branch is frozen for 1.9.3 release.

**Comment by linyouchong** [comment]
@saad-ali need approval/lgtm. Thanks!

**Comment by mbohlool** [comment]
@saad-ali friendly ping

**Comment by mbohlool** [comment]
@linyouchong I know you waited so long for this and I am sorry, but is it ok if we push this back to 1.9.5? 
/hold

**Comment by linyouchong** [comment]
Yes, it is ok

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/58906)

**Comment by jpbetz** [comment]
/hold
Hold all unmerged cherrypicks for cut of patch release on Monday.

**Pull request merged**
