### PR TITLE
client-go/consistencydetector: refactor TestDataConsistencyChecker to work with unstructured data

### PR DESCRIPTION
**Pull request by p0lyn0mial**
#### What type of PR is this?
/kind feature

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by wojtek-t** [comment]
/hold

test failure is related

**Comment by p0lyn0mial** [comment]
> /hold
>
> test failure is related

fixed, sorry, i wanted to make sure the test fails when data doesn't match and i added additional entry to the list rsp and i didn't removed it before sending the pr.

**Pull request merged**
