### PR TITLE
code-generator: add openapi-gen to top-level scripts

### PR DESCRIPTION
**Pull request by sttts**
Midterm goal: enable https://github.com/kubernetes-client/* for CRDs

Not sure whether this is the right way for CRDs though as we want to create OpenAPI specs from the validation JSON Schema https://github.com/kubernetes/kubernetes/issues/49878. This PR requires that you write Golang types for the CRD. This does not mix well with a validation JSON Schema. 

TODOs:
- [ ] serve openapi in sample-apiserver
- [ ] add an integration test checking that the openapi spec is good
- [x] remove `_examples` types from pkg/generated/openapi/zz_generated.openapi.go
- [ ] ~~for CRDs find a way to convert the Golang OpenAPI spec to json, maybe add a json-output to openapi-gen?~~ not necessary: for CRDs this is not the right approach, for UASs we will run the UAS and curl the spec.

### CODE REVIEW

**Comment by deads2k** [comment]
the upstream commit looks like a useability fix.

**Comment by deads2k** [comment]
> This does not mix well with a validation JSON Schema.

That would be a problem.  The openapi generation like this has value to aggregated API servers (anything making generation easier is good), but probably not the CRD use-case then

**Comment by sttts** [comment]
> the upstream commit looks like a useability fix.

Yes, will open that up independently from the destiny of this PR.

**Comment by sttts** [comment]
> but probably not the CRD use-case then

Exactly.

**Pull request closed without merging**
