### PR TITLE
Pass SubnetID to vips.Create()

### LINKED ISSUE #12131: OpenStack implementation does not pass SubnetID when creating a VIP
When creating a load balancer in OpenStack, the call to vips.create() does not pass the subnet ID - this is required, thus all calls fail.

### PR DESCRIPTION
**Pull request by jpgxs**
Fixes #12131

### CODE REVIEW

**Comment by jgriffiths1993** [comment]
I signed it!

**Comment by alex-mohr** [comment]
@k8s-bot ok to test

**Comment by thockin** [comment]
@anguslees

**Comment by anguslees** [comment]
lgtm

**Comment by thockin** [comment]
LGTM

**Pull request merged**
