### PR TITLE
Support custom Fedora repos in vagrant provider

### PR DESCRIPTION
**Pull request by ivan4th**
Sometimes `KUBERNETES_PROVIDER=vagrant cluster/kube-up.sh` fails due to problems
with Fedora's metalink URL:

```
Timeout was reached for https://mirrors.fedoraproject.org/metalink?repo=fedora-23&arch=x86_64 [Connection timed out after 120002 milliseconds]
```

This PR makes it possible to specify a custom Fedora repository URL:

```
export CUSTOM_FEDORA_REPOSITORY_URL=https://download.fedoraproject.org/pub/fedora/
```

[Analytics]()

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/28778)

### CODE REVIEW

**Comment by ivan4th** [comment]
@smarterclayton on some days the metalink URL just won't work, and some of my colleagues are having similar problems too. Also, using local Fedora mirror can speed up vagrant-based kube-up which is important for testing.

**Comment by ivan4th** [comment]
sorry, clicked a wrong button

**Comment by ivan4th** [comment]
@smarterclayton can we have this merged? Or maybe I should make some changes (rename the var, add docs)?

**Comment by jellonek** [comment]
Bump up.

**Comment by smarterclayton** [comment]
@derekwaynecarr can you take a look at this?

**Comment by ivan4th** [comment]
@derekwaynecarr ping ... and also please take a look at #29610 if you have chance.

**Comment by ivan4th** [comment]
@derekwaynecarr another gentle ping... There are times when metalink url breaks + sometimes kube-up may be sped up by using local Fedora mirror

**Comment by ivan4th** [comment]
Just got the error again:
```
==> master: Downloading Packages:
==> master:
==> master: The downloaded packages were saved in cache till the next successful transaction.
==> master: You can remove cached packages by executing 'dnf clean packages'.
==> master: Error: Error downloading packages:
==> master:   Curl error (28): Timeout was reached for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f23&arch=x86_64 [Operation too slow. Less than 1000 bytes/sec transferred the last 120 seconds]
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.```

**Comment by nhlfr** [comment]
I'm encountering this error very often, I think it's critical for Vagrant users.

**Comment by derekwaynecarr** [comment]
lgtm, sorry for delay.

**Pull request merged**
