### PR TITLE
unrevert genrule for bindata

### PR DESCRIPTION
**Pull request by mikedanese**
https://github.com/kubernetes/kubernetes/commit/0a896a9e57e2d186b2bd73f9c2b79b4c4c699cdb#diff-c6b8e249299c953e99c9ca032a1b0d00L15

cc @caesarxuchao

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35702)

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot unit test this

**Comment by caesarxuchao** [comment]
I don't know what happened to that file. Thanks.

**Comment by spxtr** [comment]
How do we prevent this in the future? It looks like @caesarxuchao deleted the build file and then ran `update-bazel.sh`, which seems like a perfectly reasonable thing to do, at least for now.

Do we just need to get bazel builds as a presubmit to fix this?

**Comment by spxtr** [comment]
https://github.com/kubernetes/test-infra/issues/897

**Comment by foxish** [comment]
Manually merging this to fix all bazel issues. Thanks @mikedanese

**Pull request merged**
