### PR TITLE
Automated cherry pick of #42024 #41929 #42422 #42974 upstream release 1.5

### LINKED ISSUE #42399: vSphere: Cannot add disks to more than one scsi adapter (disk count per node > 16)
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): v1.4.x v1.5.x v1.6.x master

**Environment**: vSphere based install with vSphere Cloud Provider enabled.
- **Cloud provider or hardware configuration**: vSphere
- **OS** (e.g. from /etc/os-release): NA
- **Kernel** (e.g. `uname -a`):NA
- **Install tools**:kubernetes-anywhere
- **Others**:

**What happened**: vSphere Cloud Provider configures additional SCSI adapters to scale the number of volumes that can be attached to a VM (1 adapter = 16 disks). The code within the cloud provider does not handle this correctly. Additional disks attach successfully to the VM but when k8s verifies the attach status it fails leading to k8s retrying the attach that never succeeds. In addition to this when the SCSI adapter is created for the first time the code does not use it to attach the disk leading to a failed attach disk request to the cloud provider.

**What you expected to happen**: Additional disks should be added to the VM upto the max number supported. 

**How to reproduce it** (as minimally and precisely as possible): Create a single node cluster and create a statefulset with > 16 replicas or have a pod with more than 16 disks.

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by BaluDontu**
Cherry pick of #42024 #41929 #42422 #42974 on release-1.5.

#42024: Remove VCenterPort from vsphere cloud provider. 
#41929: vSphere Cloud Provider: Fstype in storage class
#42422: Fix adding disks to more than one scsi adapter. Fixes #42399
#42974: VSAN policy support for storage volume provisioning inside kubernetes

@saad-ali

### CODE REVIEW

**Comment by BaluDontu** [comment]
@saad-ali : Can you please take a look at this PR. I didn't have the cherry-pick label on this PR. Can you add one.

**Comment by saad-ali** [comment]
/lgtm

CC 1.5 branch manager, @mwielgus, for approval

**Comment by saad-ali** [comment]
/approve cancel

Withdrawing my approval based on https://github.com/kubernetes/kubernetes/pull/44375#issuecomment-293698733, since this PR is adding new functionality "fstype" and "VSAN policy" and which patch releases shouldn't do. 

Will defer decision to patch release manager for 1.5 @mwielgus

**Comment by BaluDontu** [comment]
@mwielgus : This PR is a new capability. The problem is right now we only limit our users to create persistent volumes of a single file system type. This is too narrow for us and a very basic functionality from us.
Allowing users to have create a persistent volume of multiple file system types and configuring it with a VSAN policy is a big ask from our customers as most of our kubernetes deployment on vSphere are on VSAN platform.

The point is that we just missed the 1.6 release cut by a few days. Isn't possible to have these included as part of patch releases ? Otherwise we would have wait next 1.7 release for these features which would be too late for us.

**Comment by mwielgus** [comment]
@BaluDontu Unfortunately, I have to deny the request for cherry-pick to 1.5 (did you really mean 1.5? PR text suggests you wanted 1.6). 

1.5.x branch is slowly coming to a complete freeze and only bug fixes and/or minor changes will be accepted. If 1.7 is too late for you then you should rather try convincing 1.6 guys to make an "exception" for you than pushing it to 1.5 without having it in 1.6 as it would create a broken experience for the users.

**Pull request closed without merging**
