### PR TITLE
Add attach==nil check

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Add attach==nil check

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by jingxu97** [comment]
@cwdsuzhou, Thank you for the PR. Just want to know in what case you see attach==nil ?

**Comment by cwdsuzhou** [comment]
@jingxu97 seems would not be nil, sorry

/close

**Comment by cwdsuzhou** [comment]
Seems it would be nil for fake interfaces

**Pull request closed without merging**
