### PR TITLE
improve readability, code nesting too deep

### PR DESCRIPTION
**Pull request by aimuz**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
Improve readability, code nesting too deep
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by aimuz** [comment]
What do I need to do to fix this error?
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/112675/pull-kubernetes-e2e-gce-ubuntu-containerd/1580371576140861440/#1:build-log.txt%3A29

```
fatal: Couldn't find remote ref refs/pull/112675/head
```

**Comment by aimuz** [comment]
/test pull-kubernetes-node-e2e-containerd
--


<br class="Apple-interchange-newline">

**Comment by soltysh** [comment]
I did notice having issues with this PR when trying to pull it locally, somehow github can't recognize this one. I'd suggest openning a new one and ping me on slack for approval.
/lgtm cancel
/approve cancel

**Comment by aimuz** [comment]
github seems to have a problem, waiting for the official reply

https://github.com/orgs/community/discussions/36097

**Comment by aimuz** [comment]
> 

After rebase, the problem is solved

@soltysh

**Comment by aimuz** [comment]
All tests passed so far, Is it possible to merge? @soltysh

**Pull request merged**
