### PR TITLE
the code in function [AllReady] have too many spaces, so, we need to …

### PR DESCRIPTION
**Pull request by heqg**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
the code in function [AllReady] have too many spaces, so, we need to make adjustments.

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

```release-note
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Comment by pacoxu** [comment]
Would you look into the link https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/97784/pull-kubernetes-verify/1347098760903135232 for failure reason before triggering new test ?

**Comment by heqg** [comment]
> Would you look into the [link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/97784/pull-kubernetes-verify/1347098760903135232) for failure reason before triggering new test ?
> 
> > `Run ./hack/update-gofmt.sh before commit` would help.


I have executed the above scripts three times in a row, but there is no problem.

Why is there a problem in [pull-kubernetes-verify]? Can you help to analyze it? Thank you.

**Comment by heqg** [comment]
> Would you look into the [link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/97784/pull-kubernetes-verify/1347098760903135232) for failure reason before triggering new test ?
> 
> > `Run ./hack/update-gofmt.sh before commit` would help.

when running  ./verify-gofmt.sh,  The problem is reproduced. thks

**Comment by heqg** [comment]
The modification is unreasonable, and the gofmt.sh check fails.

**Pull request closed without merging**
