### PR TITLE
Release 1.8

### PR DESCRIPTION
**Pull request by dilshan000**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by munnerz** [comment]
Hey - what was the original intention of this pull request (and #54942)?

The release-* branches are used to cut releases of Kubernetes releases, and for back-porting patches. The release branches shouldn't be merged into master, as well of the changes in the release branches should already exist in master 😄 

/close

**Comment by dilshan000** [comment]
Hi James,

Thanks for the guidelines.
Sorry for newbie's work.




Dilshan Fernando

**Comment by resouer** [comment]
Oh, it really shocked my to see "Release 1.8", haha.

Feel free to submit new PRs :)

**Comment by dilshan000** [comment]
Hi All,

Can some advice me to how join k8s development in github?
I want to work as active member in community?


Dilshan Fernando

**Pull request closed without merging**
