### PR TITLE
del unuse var in pkg/controller

### PR DESCRIPTION
**Pull request by hwdef**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

delete unused global variables and constants in pkg/controller

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
I think this comes from static check issues. And I remember it has been picked by @sadlil .

Maybe in this PR: https://github.com/kubernetes/kubernetes/pull/81749

**Comment by hwdef** [comment]
@RainbowMango 
sorry.
I think we have some different part.
I will delete the same part.

**Pull request merged**
