### PR TITLE
Update template.pot with latest message IDs

### PR DESCRIPTION
**Pull request by stormqueen1990**
#### What type of PR is this?

Update the `template.pot` file with the current state of the messages in kubectl. That allows localized messages to be updated accordingly and picked up correctly.

These changes were generated using `hack/update-translations.sh -x`.

/kind documentation

#### What this PR does / why we need it:

Updates the message keys for localization in kubectl with the latest kubectl state. It allows localized messages to be picked up correctly.

#### Which issue(s) this PR fixes:

No associated issue.

#### Special notes for your reviewer:

These changes were generated using `hack/update-translations.sh -x`. No manual changes are being introduced.

#### Does this PR introduce a user-facing change?

Indirectly, as it changes the `msgid` for localizations of kubectl texts.

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by rikatz** [comment]
/lgtm
/assign  @brianpursley @seans3 

A question: shouldn't this be automated somehow? I though this file was autogenerated 😬

**Comment by rikatz** [comment]
/assign @brianpursley @seans3 
2nd time should work :P

**Comment by brianpursley** [comment]
> /lgtm /assign @brianpursley @seans3
> 
> A question: shouldn't this be automated somehow? I though this file was autogenerated grimacing

There is a script that updates the template.pot file, but it is not run in an automated job.

It might be difficult to automate because it needs to run and then commit back any changes that are made to the template.pot file.  I don't know if we have any jobs that commit changes currently.

One idea I had would be to add a unit test or some kind of other test or build step that checks to see if template.pot is out of date, and if so, fail.  That way, people who update strings in code will be required to run the script to update template.pot before their build will pass.  This might be a good first step.

**Review by brianpursley — APPROVED** [review]
/lgtm
/approve
Thanks for updating this, @stormqueen1990

**Comment by mpuckett159** [comment]
> One idea I had would be to add a unit test or some kind of other test or build step that checks to see if template.pot is out of date, and if so, fail. That way, people who update strings in code will be required to run the script to update template.pot before their build will pass. This might be a good first step.

@brianpursley yeah this is a common pattern for e.g. making sure black/flake8/mypy has been run for Python based repos, as well as like golangci-lint in the Kubernetes repo. Definitely a good idea.

**Pull request merged**
