### PR TITLE
Add second CIDR for l7 testing

### LINKED ISSUE #45671: L7 GCE should create ingress with given static-ip broken in 3 1.6 suites
Failure cluster: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=should%20create%20ingress#171d3d9981699b3a3a86

Testgrid: https://k8s-testgrid.appspot.com/release-1.6-all#gci-gke-ingress-1.6 (note that this is only one job)

Clicking the "changes" button suggests this is related to #45068 
https://github.com/kubernetes/kubernetes/compare/9d68760c3...8118c50c0

Example error:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/ingress.go:140
Expected error:
    <*errors.errorString | 0xc4214e04d0>: {
        s: "incorrect source ranges [130.211.0.0/22 35.191.0.0/16], expected [130.211.0.0/22]: found differences: map[35.191.0.0/16:{}]",
    }
    incorrect source ranges [130.211.0.0/22 35.191.0.0/16], expected [130.211.0.0/22]: found differences: map[35.191.0.0/16:{}]
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/ingress.go:129
```

@kubernetes/sig-network-test-failures 
/assign @bowei @nicksardo

### PR DESCRIPTION
**Pull request by nicksardo**
**Which issue this PR fixes**:
Fixes #45671 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by fejta** [comment]
Thanks so much!
/approve

/unassign
/assign @bowei 
Bowei, any chance you can reassign this to someone familiar with this feature and its tests to review?

@kubernetes/sig-network-pr-reviews

**Review by bowei — APPROVED** [review]

**Comment by bowei** [comment]
looks like this needs to be run `hack/update-federation-openapi-spec.sh`

**Comment by cblecker** [comment]
@k8s-bot verify test this, flake: https://github.com/kubernetes/kubernetes/issues/44232

**Comment by nicksardo** [comment]
Anthony ran the update-all script in another commit.  :-)

**Comment by bowei** [comment]
needs a cherry-pick label?

**Pull request merged**
