### PR TITLE
Stop referring to loop variable inside closure.

### LINKED ISSUE #33137: disruption e2e tests are not really running
Due to a bug in the disruption e2e test, we really only run one test case 5 times instead of all 5 test cases.  This will be fixed when #33133 is merged.

### PR DESCRIPTION
**Pull request by mml**
Prior to this, I was actually running the same (last) test 5 times in a row.  :-(

Fixes #33137

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33133)

### CODE REVIEW

**Comment by madhusudancs** [comment]
I guess this idiosyncrasy [of Go's loop vars] has to bite every single of us!

:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33133#-:-KS8jNaM73kw7Cq4nSSd:b7igaun)*

**Comment by mml** [comment]
Since this causes the e2e tests to **actually run**, I think it should be cherry picked.

**Comment by pwittrock** [comment]
Scary.  So we really have no signal on a bunch of e2e tests.

**Comment by janetkuo** [comment]
@madhusudancs @pwittrock Do we need to cherrypick this? `evictionCases` does not exist in 1.4 code https://github.com/kubernetes/kubernetes/blob/release-1.4/test/e2e/disruption.go

**Comment by mml** [comment]
@janetkuo Not sure if we want these test cases picked onto 1.4 or not.  @davidopp this is the more expansive set of test cases that I wrote.  Do we want to cherry pick those cases onto 1.4?  If not, then this PR, which makes them actually run, is moot.

**Comment by jessfraz** [comment]
was cherry-picked in #33251, removing cherry-pick candidate label

**Pull request merged**
