### PR TITLE
Leak filling for newline format on benchmark-go.sh

### PR DESCRIPTION
**Pull request by ghost**
**What this PR does / why we need it**:  make hack/benchmark-go.sh work 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**: First commit :D , did I make a wrong modification? 

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by aaron12134** [comment]
"I signed it!



xuliker@zju.edu.cn
 
From: k8s-ci-robot
Date: 2016-12-10 17:23
To: kubernetes/kubernetes
CC: Aaron Xu; Mention
Subject: Re: [kubernetes/kubernetes] Leak filling for newline format on benchmark-go.sh (#38557)
Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
???? Please follow instructions at https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ to sign the CLA.
Once you've signed, please reply here (e.g. "I signed it!") and we'll verify. Thanks.


If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data and verify that your email is set on your git commits.
If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
If you have questions or suggestions related to this bot's behavior, please file an issue against the kubernetes/test-infra repository.

**Comment by zmerlynn** [comment]
@k8s-bot ok to test

**Comment by zmerlynn** [comment]
@k8s-bot cvm gke e2e test this

**Pull request merged**
