### PR TITLE
 Migrated `pkg/scheduler/framework/plugins/volumebinding` to contextual logging

### PR DESCRIPTION
**Pull request by mengjiao-liu**
#### What type of PR is this?
/kind feature
/kind cleanup

#### What this PR does / why we need it:
 Migrated `pkg/scheduler/framework/plugins/volumebinding` to contextual logging

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/kubernetes/issues/91633#issuecomment-1467645065

#### Special notes for your reviewer:

~There are some dependencies on package `pkg/scheduler/framework`, the PR is added first to make the test pass, and then the PR is rebase after the framework package code is merged.~
#### Does this PR introduce a user-facing change?

```release-note
Migrated the volumebinding scheduler plugins to use [contextual logging](https://k8s.io/docs/concepts/cluster-administration/system-logs/#contextual-logging).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/3077-contextual-logging
```

### CODE REVIEW

**Comment by mengjiao-liu** [comment]
Depending on the framework package which needs to wait for framework packages to merge first.

Or use `klog.TODO()` to get the initialized `logger`.

**Comment by mengjiao-liu** [comment]
Dependent on PR https://github.com/kubernetes/kubernetes/pull/116842
Wait for the PR https://github.com/kubernetes/kubernetes/pull/116842 to merge first.

/hold

**Comment by mengjiao-liu** [comment]
> Dependent on PR #116842 Wait for the PR #116842 to merge first.
> 
> /hold

/hold cencel

**Comment by mengjiao-liu** [comment]
> Dependent on PR #116842 Wait for the PR #116842 to merge first.
> 
> /hold

/unhold

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by pohly** [comment]
/assign @xing-yang 

For approval.

**Pull request merged**
