### PR TITLE
Patch and replace take the resourceVersion option

### LINKED ISSUE #742: All operations modifying resources (patch, replace) should take --resource-version
kubectl's annotate, label and scale operations take `--resource-version`. This allows to prevent a change overwriting another change that happens between reading a resource and updating it.

The same reasoning applies to all operations that update a resource, like `patch` and `replace`.

Specifically for me the use case to modify values in a configmap but while making sure there were no changes between getting the configmap and writing the changes back.

### PR DESCRIPTION
**Pull request by somtochiama**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test

kind feature
> /kind flake

**What this PR does / why we need it**:
It allows the patch and replace cmd commands take `--resource-version` so the command exits if the resource version specified doesn't match the one on the server.

**Which issue(s) this PR fixes**:

Fixes [kubectl/#742](https://github.com/kubernetes/kubectl/issues/742)

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
for patch, if you want resourceVersion as a precondition, you need to embed it in the patch content

**Comment by SomtochiAma** [comment]
> for patch, if you want resourceVersion as a precondition, you need to embed it in the patch content

How can I embed it in the patch content?

**Comment by liggitt** [comment]
for json merge patch, for example: `{"metadata":{"resourceVersion":"..."}, ...}`

**Comment by SomtochiAma** [comment]
> for json merge patch, for example: `{"metadata":{"resourceVersion":"..."}, ...}`

That means there is no need for it to take the resource Version flag?

**Comment by liggitt** [comment]
correct... not only no need, but taking it as a flag could be ambiguous if the flag and the content conflicted

**Comment by SomtochiAma** [comment]
> correct... not only no need, but taking it as a flag could be ambiguous if the flag and the content conflicted

But it is still fine for the replace?

**Comment by liggitt** [comment]
for replace operations, the resourceVersion is also able to be specified in the manifest

**Comment by SomtochiAma** [comment]
> for replace operations, the resourceVersion is also able to be specified in the manifest

Alright. I will close the PR

**Pull request closed without merging**
