### PR TITLE
Extract strings from the rollout command.

### PR DESCRIPTION
**Pull request by brendandburns**
@fabianofranz @kubernetes/sig-cli-pr-reviews

### CODE REVIEW

**Comment by lavalamp** [comment]
wow, I hope you made a tool to automate this :) :)

**Comment by smarterclayton** [comment]
This would be a good topic for the inaugural Kubernetes-dev-announce
mailing list!

**Comment by brendandburns** [comment]
@lavalamp yep, see https://github.com/kubernetes/kubernetes/pull/39223

Work in progress, of course, only knows about certain strings, but it will know about more eventually

**Comment by fabianofranz** [comment]
@k8s-bot unit test this

**Comment by fabianofranz** [comment]
@brendandburns this didn't require bindata changes?

**Comment by brendandburns** [comment]
oops, fixed.  thanks for the catch.

**Comment by brendandburns** [comment]
Rebased, please take another look.

**Comment by brendandburns** [comment]
Friendly ping on this one to @smarterclayton @fabianofranz 

Thanks
--brendan

**Comment by brendandburns** [comment]
Friendly ping to @smarterclayton @fabianofranz 

Side note, there are going to be lots of mechanical PRs like this, do we want to require reviews for everyone?

**Comment by fabianofranz** [comment]
/lgtm

@brendandburns sorry for the delay, I was on paternity leave.  ;)

**Pull request merged**
