### PR TITLE
Use RWMutex replace Mutex

### PR DESCRIPTION
**Pull request by knightXun**
I notice we can use RWMutex replace Mutex in servicecontroller.thx all.

### CODE REVIEW

**Comment by knightXun** [comment]
can anyone review my pr ?

**Comment by thockin** [comment]
Do you have a test or benchmark that shows this being a problem?

**Comment by knightXun** [comment]
@thockin that's not problem,but i think using RWMutex is better.just a advisor

**Comment by thockin** [comment]
Unless you can point to a problem, this is probably a premature
optimization.

@wojtek-t

**Pull request closed without merging**
