### PR TITLE
client-go/events: avoid referencing a nil related object

### PR DESCRIPTION
**Pull request by Iceber**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
If the `related` is nil, `GetReference` returns an error and then prints a log.
It is common for the `related` to be nil, and there is no need to call `GetReference` and print the log.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jpbetz** [comment]
/lgtm

This seems reasonable to me.

**Comment by Iceber** [comment]
@brancz @wojtek-t PTAL, Thanks

**Comment by Iceber** [comment]
@RainbowMango PTAL, Is there anything else that needs to be changed? Thanks :smiley:

**Comment by RainbowMango** [comment]
/remove-kind bug
/kind cleanup
It's not a bug but a cleanup I think.

/approve

**Pull request merged**
