### PR TITLE
remove timed_queue from workqueue

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix https://github.com/kubernetes/kubernetes/issues/40494.

It's added to gather metrics of the workqueue used in the garbage collector. Now that a regular workqueue has supported the metrics, we can remove timed_queue.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@k8s-bot bazel test this

**Comment by kargakis** [comment]
We will need a queue that holds time for implementing virtual clocks in controllers.

**Comment by deads2k** [comment]
> We will need a queue that holds time for implementing virtual clocks in controllers.

This was slightly different. This one was gathering metrics before our regular work queues gathered metrics like time spent waiting.

**Comment by deads2k** [comment]
its vendor/BUILD again. approving.

**Pull request merged**
