### PR TITLE
kubeadm: prefer to use pkg/errors package and cleanup fmt.Errorf

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
[kubeadm: prefer to use pkg/errors package and cleanup fmt.Errorf]

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
we should just use the pkg/errors package and Wrap(f) instead. despite deprecated the library gives us the consistent wrapping that we need. stdlib and %w dont have that.

we might actually fork it at some point.

**Comment by SataQiu** [comment]
> we should just use the pkg/errors package and Wrap(f) instead. despite deprecated the library gives us the consistent wrapping that we need. stdlib and %w dont have that.
> 
> we might actually fork it at some point.

Emm... On second check, we do use `errors.Wrap(f)` a lot. So should we use `errors.Wrapf` instead of `fmt.Errorf()` in our  kubeadm codebase? @neolit123

**Comment by neolit123** [comment]
> So should we use errors.Wrapf instead of fmt.Errorf() in our kubeadm codebase?

yes. in fact we had an effort to clean all usage of fmt.Errorf.

**Review by neolit123 — COMMENTED** [review]
/lgtm
thanks

**Comment by SataQiu** [comment]
Thanks @neolit123 Need LGTM again
This PR also replaces `errors` package with prefered `"github.com/pkg/errors"` package.

**Pull request merged**
