### PR TITLE
azure: Move configuration of resource group in storage class.

### PR DESCRIPTION
**Pull request by jsafrane**
**What this PR does / why we need it**:
This moves configuration of Azure resource group into storage class. Users can't configure dynamic provisioning in PVCs, because that makes the PVC not portable to other Kubernetes installations, possibly on other clouds.

/sig storage
/assign @andyzhangx 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
@jsafrane Thanks for the PR, let me test it first.

**Comment by andyzhangx** [comment]
FYI @rootfs @khenidak we are going to add another field in azure disk storage class: `resourcegroup`, I over estimated the orignal API change impact, actually it's a little change... Anyway, I would like to do a test for this scenario first, just wait for my test result, thanks.

**Comment by jsafrane** [comment]
@andyzhangx, I removed the annotation completely, this would be the first case where user can configure dynamic provisioning in PVC and it would make the PVC not portable to other cloud. Please proceed with the review and picks to older releases.

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by andyzhangx** [comment]
@jsafrane thanks,  I will cherry-pick this PR later.

**Pull request merged**
