### PR TITLE
Remove unused e2e test image config

### PR DESCRIPTION
**Pull request by bart0sh**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

node_e2e tests uses benchmark image configs from test-infra repository
This one is outdated and not used anywhere.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by MHBauer — APPROVED** [review]
/lgtm
Similar idea in #91471. This directory has been migrated to test-infra and should go away, or maybe point over there.

**Review by vpickard — APPROVED** [review]
```
[~/go/src/k8s.io/kubernetes-upstream] (master *%=)$ grep -iR benchmark-config.yaml *
[~/go/src/k8s.io/kubernetes-upstream] (master *%=)$ find . -name benchmark-config.yaml
./test/e2e_node/jenkins/benchmark/benchmark-config.yaml


[~/go/src/k8s.io/test-infra] (master>)$ !gre
grep -iR benchmark-config.yaml *
config/jobs/kubernetes/sig-node/node-kubelet.yaml:      - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/benchmark-config.yaml
config/jobs/kubernetes/sig-node/node-kubelet.yaml:      - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/benchmark-config.yaml --test-suite=conformance
config/jobs/kubernetes/sig-node/containerd.yaml:      - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/containerd/cri-master/benchmark-config.yaml
[~/go/src/k8s.io/test-infra] (master>)$ !find
find . -name benchmark-config.yaml
./jobs/e2e_node/benchmark-config.yaml
./jobs/e2e_node/containerd/cri-master/benchmark-config.yaml

```

**Comment by vpickard** [comment]
assign @dashpole

**Comment by dashpole** [comment]
/lgtm
this only has images that are many years old...

**Comment by bart0sh** [comment]
/assign @dashpole @krzyzacy @Random-Liu @yguo0905 @yujuhong
Please, approve.

**Pull request merged**
