### PR TITLE
Automated cherry pick of #65533: fix ipset creation fails on centos

### PR DESCRIPTION
**Pull request by islinwb**
Cherry pick of #65533 on release-1.11.

#65533: fix ipset creation fails on centos

/sig network
/area ipvs
/assign @thockin @m1093782566 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by m1093782566** [comment]
/lgtm
/appvoe


@thockin as it's a bug fix.

**Comment by nikhita** [comment]
@m1093782566 can you reapply lgtm?

**Comment by nikhita** [comment]
/assign @foxish 
for cherry-pick approval

**Comment by islinwb** [comment]
@m1093782566 The `lgtm` was removed earlier after my push.  Actually I made no modifications to the content.

**Comment by xiajidexue** [comment]
marked as i encountered the same problem on Centos

**Pull request merged**
