### PR TITLE
tests: Ports volume unit tests to Windows

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind failing-test

/sig testing
/sig windows
/priority important-soon
/milestone v1.25

#### What this PR does / why we need it:

Adds Windows file permissions.

The Windows file permissions / ACLs are a bit more complex and fine-grained than the Linux file permissions. However, the Linux file permissions could be translated to some extent to Windows ACLs.

We could translate the Linux user / group / other to the Windows SIDs: Creator Owner ID / Creator Group ID / World, or more precisely, ``S-1-3-0`` / ``S-1-3-1`` / ``S-1-1-0``.

As for the permissions, we can use the Generic Access Rights: ``GENERIC_READ`` / ``GENERIC_WRITE`` / ``GENERIC_EXECUTE``.

Adds ``GetFileMode``, which will return the mode of the given file. For Windows, the mode is retrieved using the Windows API, and returns a Linux-like ``FileMode``, based on the file's owner, owner group, and ``Everyone``.

Ports the ``atomic_writer`` unit tests to Windows.
Fixes a few other unit tests for Windows.

#### Which issue(s) this PR fixes:

Related: #51540

#### Does this PR introduce a user-facing change?

```release-note
File permissions will now be set on files and volumes on Windows pods.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by claudiubelu** [comment]
> 

Hello. The linked PR has the same idea as this PR. Either one is fine to merge, this PR has one additional commit which adds more unit test coverage for Windows.

**Comment by jayunit100** [comment]
Looks good to me

**Comment by helayoty** [comment]
@claudiubelu @dchen1107 👋 the release 1.25 bug triage Lead. I'm reaching out to see the status of this PR and if we are still targeting the current release. Also, is it a release blocker?

**Comment by dims** [comment]
way past test freeze
/milestone clear

**Comment by ddebroy** [comment]
Note: some more context at https://github.com/kubernetes/kubernetes/pull/104660#issuecomment-1291620100

**Comment by msau42** [comment]
@ddebroy and I were discussing the backwards compatibility implications of this change. It seems like it does have the potential to break existing workloads because they could be specifying these fields already and be depending on the current behavior.

**Comment by marosset** [comment]
> @ddebroy and I were discussing the backwards compatibility implications of this change. It seems like it does have the potential to break existing workloads because they could be specifying these fields already and be depending on the current behavior.

I think even if this does introduce some backwards compatibility implications, I think we would want these changes because we would be preventing unwanted/unauthorized access to files on the host.

**Comment by ddebroy** [comment]
Can an approach similar to the introduction of `runAsUserName` as a new dedicated field for Windows (rather than trying to fit the Windows requirement in the existing `runAsUser` field for Linux) apply here? 

Instead of trying to roughly map Linux permission modes into Windows, how about fully surfacing the Windows ACL system (in a manner similar to `icacls`) through a dedicated field. Since this will be new and opt-in only, any backward compat concerns also go away.

**Comment by SergeyKanzhelev** [comment]
@claudiubelu is this comment https://github.com/kubernetes/kubernetes/pull/110921#issuecomment-1302614556 still stands?

**Comment by jsturtevant** [comment]
this may be related to https://github.com/kubernetes/kubernetes/pull/104660

**Pull request closed without merging**
