### PR TITLE
Fix field vs. JSON names

### LINKED ISSUE #9083: RBD json tags don't match field names
There may be others but I saw this today...

```
type RBDVolumeSource struct {
    // Required: CephMonitors is a collection of Ceph monitors
    CephMonitors []string `json:"monitors"`
    // Required: RBDImage is the rados image name
    RBDImage string `json:"image"`
    // Required: Filesystem type to mount.
    // Must be a filesystem type supported by the host operating system.
    // Ex. "ext4", "xfs", "ntfs"
    // TODO: how do we prevent errors in the filesystem from compromising the machine
    FSType string `json:"fsType,omitempty"`
    // Optional: RadosPool is the rados pool name,default is rbd
    RBDPool string `json:"pool"`
    // Optional: RBDUser is the rados user name, default is admin
    RadosUser string `json:"user"`
```

I think that, in general we want field names and JSON tags to match unless there's a good reason for them not to.  I see no good reason here.  Probably field names should change, leaving tags (the API) untouched.

@markturansky @rootfs

### PR DESCRIPTION
**Pull request by thockin**
/kind cleanup

Fixes #9083

```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
Re-pushed with lint fixed

**Comment by humblec** [comment]
Thanks Tim. Just to mention , this looks to be covering more than #9083 and specifically some plugins here touched here are deprecated.

**Comment by thockin** [comment]
Deprecated or not, I don't see a reason not to fix them and remove the warnings?

**Comment by apelisse** [comment]
This is breaking client-go compatibility.

Would it be worth trying to detect these occurrences somewhere possibly with a warning that can be turned off?

**Comment by thockin** [comment]
Ugh, of course.  THAT's the rub.  The API is not just the REST API, sadly.

Abandon ship!  Sorry to waste CI resources.

**Pull request closed without merging**
