### PR TITLE
Log more url metadata in requestinfo.go

### LINKED ISSUE #95073: Log more url metadata in requestinfo.go when failures happen
**What would you like to be added**:

requestinfo.go should log the url , as well as the parameters that are failing in a request:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/request/requestinfo.go#L214

However only logs

```
 req.URL.Query()
```

**Why is this needed**:

otherwise, its not easy to know what component is failing due to label selectors,   

```
E0925 19:23:52.079668       1 requestinfo.go:214] Couldn't parse request url.Values{"labelSelector":[]string{"name=kube-controller-manager-ip-10-0-4-229.us-west-2.compute.internal"}}: unable to parse requirement: invalid label value: "kube-controller-manager-ip-10-0-4-229.us-west-2.compute.internal": at key: "name": must be no more than 63 characters
```

### PR DESCRIPTION
**Pull request by wawa0210**
**What type of PR is this?**

/kind bug
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #95073

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Log more url metadata in requestinfo.go when failures happen
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by lavalamp** [comment]
Sorry for delay.

Logging isn't the right way to expose errors like this. They need to be returned to the user and the request probably should be failed.

**Comment by wawa0210** [comment]
> Sorry for delay.
> 
> Logging isn't the right way to expose errors like this. They need to be returned to the user and the request probably should be failed.

You are right, the code just log error not return the error https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/request/requestinfo.go#L214

There is an error  judgment at the call of the function, should we return error directly instead of continuing to process it?

**Comment by lavalamp** [comment]
> we return error directly instead of continuing to process it?

It's not 100% clear how to do that in this function, but more or less,
yeah, this should probably abort the request, especially if it could lose
things like dry run markers. I'm swamped today so won't be able to help
with the mechanics, sorry.

**Pull request closed without merging**
