### PR TITLE
fix the build

### LINKED ISSUE #24340: verify-godeps.sh fails at head
http://submit-queue.k8s.io/#/e2e

```sh
+++ /tmp/gopath.sUnZ3U/src/k8s.io/kubernetes/Godeps/Godeps.json	2016-04-15 09:58:12.408021895 -0700
@@ -1079,14 +1079,6 @@
 			"Rev": "833a04a10549a95dc34458c195cbad61bbb6cb4d"
 		},
 		{
-			"ImportPath": "golang.org/x/tools/go/ast/astutil",
-			"Rev": "4f50f44d7a3206e9e28b984e023efce2a4a75369"
-		},
-		{
-			"ImportPath": "golang.org/x/tools/imports",
-			"Rev": "4f50f44d7a3206e9e28b984e023efce2a4a75369"
-		},
-		{
 			"ImportPath": "google.golang.org/api/cloudmonitoring/v2beta2",
 			"Rev": "77e7d383beb96054547729f49c372b3d01e196ff"
 		},
Removing /tmp/gopath.sUnZ3U
FAILED   ./hack/../hack/verify-godeps.sh	275s
```

### PR DESCRIPTION
**Pull request by mikedanese**
verify godeps is failing. we don't run verify godeps unless the Godeps directory is modified but it's possible that a change outside of godeps could cause verify-godeps to fail, namely removing an import to a package that causes the package to become unused

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-test-go/10956/

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go/

fixes #24340

cc @wojtek-t

### CODE REVIEW

**Comment by eparis** [comment]
@freeformz we are still using v53, but changes outside our repo shouldnt ever cause us to fail our verification script...

**Comment by eparis** [comment]
I'm not going to be able to take a look for a couple hours. Cable guy is trying to get my internet hooked up and is having some troubles...

**Comment by mikedanese** [comment]
@eparis no worries, we can handle this. The change was in our repo but not in Godeps/. Someone removed an import which caused a package to become unused.

**Comment by lavalamp** [comment]
lgtm

**Comment by wojtek-t** [comment]
@mikedanese - thanks for fixing (and sorry for problems)

**Pull request merged**
