### PR TITLE
Add cluster-level AppArmor E2E test

### PR DESCRIPTION
**Pull request by timstclair**
My goal is to reuse this test for an automated cluster upgrade test.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37258)

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM

**Comment by timstclair** [comment]
Squashed & rebased (reapplying LGTM)

**Comment by timstclair** [comment]
@k8s-bot test this

**Comment by timstclair** [comment]
Fixed build (imports) post rebase.

**Comment by timstclair** [comment]
@k8s-bot cvm gce e2e test this, issue https://github.com/kubernetes/kubernetes/issues/33175

**Pull request merged**
