### PR TITLE
Fixed error check in graceful shutdown test

### PR DESCRIPTION
**Pull request by damemi**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixes a small typo in error checking in the test

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by alejandrox1 — COMMENTED** [review]
This looks like it has the right intent (wish there were some comments).
Thank you for working on this @damemi 
Though we should change the title here, this is not just a typo.
/retitle Fixed error check in graceful shutdown test
/lgtm
/priority critical-urgent
/milestone v1.17

/cc @sttts 
ptal

**Review by draveness — APPROVED** [review]
/retest

**Pull request merged**
