### PR TITLE
kubectl describe <kind> command works with --all

### PR DESCRIPTION
**Pull request by feihujiang**
#10305 `kubectl describe \<kind\>` should work with no arguments, But someone maybe forget resource name when using describe command, and if "kubectl describe <kind>" works, lot's of information output is a little boring. I think "kubectl describe< kind> --all" is better. So I new this PR. "kubectl describe <kind> command works with --all"

### CODE REVIEW

**Comment by jlowdermilk** [comment]
code LGTM, but please add a test to `hack/test-cmd.sh` so we have some coverage of the option.

**Comment by feihujiang** [comment]
@jlowdermilk Sorry, I'm on a business trip, will be back next week, and then I'll do this as soon as possible.

**Comment by bgrant0607** [comment]
I don't agree with this change.

**Comment by feihujiang** [comment]
@bgrant0607 OK, I will open a new PR to reference `kubectl describe <kind>` work with no arguments

**Pull request closed without merging**
