### PR TITLE
Remove alpha message

### PR DESCRIPTION
**Pull request by apelisse**
Update API documentation to remove alpha message about ManagedFields.

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/unassign deads2k davidopp 
/assign

API docs change that got missed when switching the gate to beta

/wg apply
/sig api-machinery

/priority critical-urgent
/milestone v1.16

including in the milestone to ensure 1.16 docs are accurate and avoid user confusion

**Comment by liggitt** [comment]
cc @kubernetes/sig-release for visibility

no risk (godoc-only change), and doesn't invalidate rc1 testing/feedback. including in the milestone to ensure 1.16 docs are accurate and avoid user confusion

**Comment by josiahbjorgaard** [comment]
Bug Triage team on 1.16 release here. Since we have passed code freeze, PRs intended for 1.16 will need to go through approval to be cherry-picked. The deadline for cherry-picks is tomorrow EOD. Description of the approval process for cherry-picks is available [here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md).

**Pull request merged**
