### PR TITLE
Revert "ScheduledJob tests"

### PR DESCRIPTION
**Pull request by piosz**
Reverts kubernetes/kubernetes#25737

This probably broke intergration tests

cc @wojtek-t @soltysh @caesarxuchao @erictune

### CODE REVIEW

**Comment by jszczepkowski** [comment]
The original PR #25737 probably caused failure of integration tests:
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-test-go/12909

**Comment by soltysh** [comment]
@mikedanese fyi

**Comment by wojtek-t** [comment]
Merging manually to fix test-go suite.

**Comment by piosz** [comment]
Thanks @wojtek-t. I was waiting for tests to pass;)

**Pull request merged**
