### PR TITLE
Fix for man pages do not build reproducibly

### LINKED ISSUE #52269: man pages do not build reproducibly
/kind bug

**What happened**:
When building kubernetes-1.7.0 packages for openSUSE, results differ for each build in `/usr/share/man/man1/kubectl.1` and other man pages.
> -\fB\-\-cloud\-provider\-gce\-lb\-src\-cidrs\fP=209.85.152.0/22,209.85.204.0/22,130.211.0.0/22,35.191.0.0/16
> +\fB\-\-cloud\-provider\-gce\-lb\-src\-cidrs\fP=35.191.0.0/16,209.85.152.0/22,209.85.204.0/22,130.211.0.0/22

coming from `pkg/cloudprovider/providers/gce/gce_loadbalancer.go`
that uses `netsets.ParseIPNets([]string{"130.211.0.0/22", "35.191.0.0/16", "209.85.152.0/22", "209.85.204.0/22"}...)`
and probably sets do not have any specific order, so it would need to be sorted on output.

**What you expected to happen**:
Every build should give identical results. See https://reproducible-builds.org/ for why this matters.

**How to reproduce it (as minimally and precisely as possible)**:
See #48710

**Anything else we need to know?**:

**Environment**:
- Kubernetes version: 1.7.0
- OS (e.g. from /etc/os-release): openSUSE Tumbleweed

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

In different distros or environments, we may end up with a different
order of the strings printed during help and man page generation,
So we should sort so the strings in the man pages is the same everytime.

Change-Id: Id8fcbd89336aad8d709ba3adac4b29c808d97ebe

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #52269

**Special notes for your reviewer**:
Please see https://github.com/kubernetes/kubernetes/issues/48710#issuecomment-422326597

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by bmwiedemann** [comment]
still had a diff:
```diff
 \fB\-o\fP, \fB\-\-output\fP="yaml"
-    Output format. One of: json|yaml|name|templatefile|template|go\-template|go\-template\-file|jsonpath|jsonpath\-file.
+    Output format. One of: json|yaml|name|template|go\-template|go\-template\-file|templatefile|jsonpath|jsonpath\-file.
```

**Comment by dims** [comment]
@bmwiedemann can you please paste the whole diff somewhere?

**Comment by bmwiedemann** [comment]
I had not properly applied the patch - will retest later.

**Comment by bmwiedemann** [comment]
yes! patch works :+1:

**Comment by juanvallejo** [comment]
@dims Thanks!

/lgtm

**Review by soltysh — APPROVED** [review]
/lgtm

**Pull request merged**
