### PR TITLE
GCI: fix multizone setting in issue #27150

### PR DESCRIPTION
**Pull request by andyzheng0831**
This PR is for fixing the issue. We gradually added more cases of using /etc/gce.conf, but in the config code we did not update the condition of computing env variables. As a result, the muitlzone setting was ignored.

I manually verified that with the fix we can create a multi-zone cluster with master on GCI.

cc/ @chrislovecnm @kubernetes/goog-image

### CODE REVIEW

**Comment by jlowdermilk** [comment]
Just to clarify my understanding, what calls `configure-helper.sh` on the master?

**Comment by andyzheng0831** [comment]
Master: https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/master.yaml#l36
Node: https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/node.yaml#l36

**Comment by andyzheng0831** [comment]
I will add "cherrypick-approved" as we need to merge the cherrypick #27326 ASAP to unblock the 1.3.0-beta release

**Comment by chrislovecnm** [comment]
@andyzheng0831 thanks

**Comment by fejta** [comment]
@k8s-bot node e2e test this issue #24479

**Comment by piosz** [comment]
This PR probably broke cluster autoscaler on GCE. We are investigating it.

@andyzheng0831 could you please include at least one of us in PR when you are changing something that is related to cluster autoscaler? 

Removing cherrypick-approvaed label. This should be done by the @erictune 

cc @mwielgus @fgrzadkowski @jszczepkowski

**Comment by piosz** [comment]
I fixed it in https://github.com/kubernetes/contrib/pull/1217, thought it's quite weird behavior for me that we are passing config to cluster autoscaler which doesn't configure anything.

**Comment by andyzheng0831** [comment]
@piosz I guess when the autoscaler was added, there was no enough test coverage, either by e2e or manual verification. Otherwise, you may already notice the autoscaler did not work as expected. Due the bug fixed by this PR, the cloud_config_mount and cloud_config_volume were not correctly mounted and the flag "--cloud-config=gce" was not shown in the autoscaler's cmd line. This PR fixes the bug in the config, and helps you catch the bug in autoscaler. It is not this PR breaks autoscaler.

**Comment by fgrzadkowski** [comment]
@andyzheng0831 Actually we have e2e tests and we did number of manual tests. Cluster autoscaler in GCE was working before this PR. Obviously it's up for discussion what should be the behavior if unexpected config is being passed, but the fact is that autoscaler stopped working after this one got merged.

I don't want to get into discussion what should happen if incomplete config is passed (exit vs ignore), but your statement that this PR helps catch a bug in autoscaler is surprising.

Thankfully, now everything is working :)

**Pull request merged**
