### PR TITLE
Fix range for min value in imagepolicy admission 

### PR DESCRIPTION
**Pull request by Raffo**
**What this PR does / why we need it**:
This makes the range for imagepolicy admission work properly. Currently if we specify `1s` for the value of `AllowTTL` or `DenyTTL` in the configuration yaml, we get a message like the following: 

```
Error: failed to initialize plugins: Couldn't init admission plugin "ImagePolicyWebhook": valid value is between 1s and 30m0s, got 1s
```

This is due to a wrong comparison which is fixed in this PR. The rest of the PR just adds tests for this behaviour.

### CODE REVIEW

**Comment by Raffo** [comment]
@derekwaynecarr any update on this PR?

**Comment by Raffo** [comment]
Flaky tests seems to be related to  https://github.com/kubernetes/kubernetes/issues/42086 as also reported in https://github.com/kubernetes/kubernetes/issues/49966#issuecomment-323088871

**Comment by Raffo** [comment]
@derekwaynecarr sorry for pinging, this has been pending for more than 2 months now, can we do something about it?

**Comment by derekwaynecarr** [comment]
apologize for the delay here.  change looks good.  feel free to poke on slack in future.

/approve no-issue
/lgtm

**Pull request merged**
