### PR TITLE
staging/copy.sh: fix for mac – take two

### PR DESCRIPTION
**Pull request by sttts**
- use gsed on Mac

### CODE REVIEW

**Comment by sttts** [comment]
@stevekuznetsov do you know a more elegant way?

**Comment by stevekuznetsov** [comment]
We use a very similar function in [Origin](https://github.com/openshift/origin/blob/master/hack/lib/util/misc.sh#L110-L126). 

```sh
# os::util::sed attempts to make our Bash scripts agnostic to the platform
# on which they run `sed` by glossing over a discrepancy in flag use in GNU.
function os::util::sed() {
	if LANG=C sed --help 2>&1 | grep -q "GNU sed"; then
		sed -i'' "$@"
	else
		sed -i '' "$@"
	fi
}
readonly -f os::util::sed
```

**Comment by sttts** [comment]
@stevekuznetsov it should work with xargs. That's why it's no function.

**Comment by stevekuznetsov** [comment]
I would suggest the function over the envar, the envar seems weird to me. I feels more natural to call a function for functionality than to expand a var.

**Comment by stevekuznetsov** [comment]
I would also suggest not using `xargs` wherever possible. It is _very_ rare that

```sh
create_output "${ARG}" | xargs do_something
```

Is more clear to non-Bash people reading your script than

```sh
for item in $( create_output "${ARG}" ); do
    do_something "${item}"
done
```

**Comment by sttts** [comment]
I suggest to depend on `gsed` for Mac and error out if it's not installed. You only call `copy.sh` as a kube developer. Installing gsed is OK IMO.

**Comment by deads2k** [comment]
> I suggest to depend on gsed for Mac and error out if it's not installed. You only call copy.sh as a kube developer. Installing gsed is OK IMO.

what is gsed?

**Comment by sttts** [comment]
@deads2k @stevekuznetsov switch to gsed. Looks much better IMO.

**Comment by sttts** [comment]
@deads2k the GNU sed installed by homebrew (http://brew.sh/)

**Comment by deads2k** [comment]
still nasty, but at least I can read it.  I'd like to wait for the latest sync to merge, then I'll pull, run the original, pull this, run it and make sure they agree before tagging.

**Comment by sttts** [comment]
People invented things like automake/conf two decades ago to hide this ugliness. It didn't work out and makes this code look pretty in contrast.

**Comment by sttts** [comment]
Merged through other PR.

**Pull request closed without merging**
