### PR TITLE
chore(cleanup): strict golangci-lint

### PR DESCRIPTION
**Pull request by cndoit18**
#### What type of PR is this?

/kind feature
#### What this PR does / why we need it:

Link: https://github.com/kubernetes/kubernetes/issues/117288#issuecomment-1507015995

#### Which issue(s) this PR fixes:
Related: #117288

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
 use `strings.ReplaceAll` method in `strings.Replace(file, dir, "", -1)`
```

### CODE REVIEW

**Review by kerthcet — COMMENTED** [review]
LGTM from sig-scheduling side only one-line code related.

**Comment by jiahuif** [comment]
/assign @pohly 
for context of #117288
/triage accepted

**Comment by pohly** [comment]
I know that https://github.com/kubernetes/kubernetes/issues/117288#issuecomment-1507015995 had a slight tendency towards fixing this in existing code, but the size of this PR shows that the work required for it (mostly time spent by reviewers and approvers) is not worth it.

Let's only fix golangci-lint warnings when there is a separate issue that asks for making that change - some votes in https://github.com/kubernetes/kubernetes/issues/117288 alone are not good enough justification for it.

**Pull request closed without merging**
