### PR TITLE
fix golint errors in pkg/apis/node/v1alpha1

### PR DESCRIPTION
**Pull request by Aresforchina**
**What type of PR is this?**

>

> /kind cleanup

**What this PR does / why we need it**:
fix golint errors in pkg/apis/node/v1alpha1
**Which issue(s) this PR fixes**:

Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
pkg/apis/node/v1alpha1/conversion.go:27:6: don't use underscores in Go names; func Convert_v1alpha1_RuntimeClass_To_node_RuntimeClass should be ConvertV1alpha1RuntimeClassToNodeRuntimeClass
pkg/apis/node/v1alpha1/conversion.go:48:6: don't use underscores in Go names; func Convert_node_RuntimeClass_To_v1alpha1_RuntimeClass should be ConvertNodeRuntimeClassToV1alpha1RuntimeClass

```

### CODE REVIEW

**Comment by neolit123** [comment]
@Aresforchina 
fixing golint problems in conversion function names is not possible at this point.
these files are generated by a tool and the tool has to be fixed instead.

**Comment by Aresforchina** [comment]
> @Aresforchina
> fixing golint problems in conversion function names is not possible at this point.
> these files are generated by a tool and the tool has to be fixed instead.

Do you know any tools to fix these files or means it could not be fixed at this time?

**Comment by neolit123** [comment]
see https://github.com/kubernetes/code-generator/issues/30

**Comment by Aresforchina** [comment]
> see [kubernetes/code-generator#30](https://github.com/kubernetes/code-generator/issues/30)
I want to know if means I can not fix it at this moment? Is that the case ?

**Pull request closed without merging**
