### PR TITLE
tar command

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jianglingxia** [comment]
ping @yifan-gu @feiskyer
thanks for review

**Comment by cblecker** [comment]
Why do we need to remove the verbose flag here?

**Comment by feiskyer** [comment]
@jianglingxia Didn't understand why do we need this patch. Could you clarify what's this patch for?

**Comment by jianglingxia** [comment]
tar -xf archive.tar          # Extract all files from archive.tar.
-v：Show All procedures
Related PR in the file ：cluster\gce\gci\configure.sh
tar xf /tmp/mounter.tar -C "${CONTAINERIZED_MOUNTER_HOME}/rootfs"
@cblecker @feiskyer  thanks！

**Comment by cblecker** [comment]
I still don't understand how removing the v flag helps with anything. Is this fixing a bug or issue?

**Comment by jianglingxia** [comment]
maybe delete v flag will not show all procedures,If think not need then I will close it,but why in the file ：cluster\gce\gci\configure.sh use xf flag?Is it different in some place? thanks@cblecker @feiskyer

**Comment by cblecker** [comment]
These tests being verbose is a good thing. It sounds like this change isn't needed, and this PR can be closed.

**Comment by jianglingxia** [comment]
ok,thanks,I close it!

**Pull request closed without merging**
