### PR TITLE
Stop sorting downward api file lines

### LINKED ISSUE #65159: Volume downward api sorts lines of rendered files
/kind bug

**What happened**:

When using the downward api to render a file via a volume mount from and annotation that has newlines in it, it appears that the file is rendered with the content sorted by line. A concrete example:

```
$ cat pod.yml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    a: "a\nb\nc"
    b: "c\nb\na"
  name: pod-test
spec:
  volumes:
    - name: config
      downwardAPI:
        items:
        - path: "a"
          fieldRef:
            fieldPath: metadata.annotations['a']
        - path: "b"
          fieldRef:
            fieldPath: metadata.annotations['b']
  containers:
  - command:
    - /bin/sh
    - -c
    - |
      sleep 1000
    image: busybox
    volumeMounts:
    - name: config
      mountPath: /configmount
    name: pod-test

$ kubectl apply -f pod.yml
pod "pod-test" configured
$ kubectl exec -ti  pod-test sh
/ # cat configmount/a
a
b
c/ # cat configmount/b
a
b
c/ #
/ #
```

Expected is that `configmount/b` would contain
```
c
b
a
```
But it does not

The above is obviously contrived, this is creating a problem for my team when we are trying to use the downward api to render a yaml file (which obviously has newlines)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.7
- Cloud provider or hardware configuration: aws
- OS (e.g. from /etc/os-release): centos

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #65159

```release-note
fixes an issue with multi-line annotations injected via downward API files getting scrambled
```

### CODE REVIEW

**Comment by liggitt** [comment]
@kubernetes/sig-storage-pr-reviews

**Review by xiaoxubeii — APPROVED** [review]

**Comment by liggitt** [comment]
/assign @thockin 
for pkg/fieldpath change

**Comment by ryanmcnamara** [comment]
Thanks @liggitt 

Can we backport this fix to 1.11? @liggitt  or @thockin ? 
Since 1.12 is a ways out

**Comment by liggitt** [comment]
> Can we backport this fix to 1.11?

I think that's reasonable. Opened #66077

**Pull request merged**
