### PR TITLE
Kubelet changes

### PR DESCRIPTION
**Pull request by gmarek**
Add knobs needed for Kubemark and clean up a little bit.

### CODE REVIEW

**Comment by wojtek-t** [comment]
@gmarek - can you please revert to a specific issue (and create it if there isn't one already)?

**Comment by wojtek-t** [comment]
LGTM, but I will let someone from the node team to also look into it.

cc @yujuhong @dchen1107

**Comment by gmarek** [comment]
I could if Kubemark doc (#12530) were already submitted

**Comment by yujuhong** [comment]
LGTM with one nit.

**Comment by gmarek** [comment]
Done.

**Comment by dchen1107** [comment]
LGTM

**Comment by caesarxuchao** [comment]
needs rebase

**Pull request merged**
