### PR TITLE
Temporarily ignore some verify failures in go1.18 and other broken things

### PR DESCRIPTION
**Pull request by dims**
Some of the verify scripts are failing after the go 1.18 based images made it to prow.

- https://github.com/kubernetes/test-infra/commit/825a16104d96e7f42bb3b6e111b25f3ead65e109
- https://github.com/kubernetes/test-infra/commit/a0cb66c30495bd019d2a02d1edb406e7743f9e18

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### What type of PR is this?
/kind failing-test

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kolyshkin** [comment]
@dims most probably you need to update to golangci-lint 1.45.0, which supports go 1.18.

Actually, here's a PR to try this: https://github.com/kubernetes/kubernetes/pull/108902

**Comment by dims** [comment]
@kolyshkin looks like we got hit by something that just got fixed but not released yet - https://github.com/golangci/golangci-lint/issues/2649#issuecomment-1075237733

**Comment by dims** [comment]
am testing some other changes to avoid ignoring things here - https://github.com/kubernetes/kubernetes/pull/108900

**Comment by kolyshkin** [comment]
> @kolyshkin looks like we got hit by something that just got fixed but not released yet - [golangci/golangci-lint#2649 (comment)](https://github.com/golangci/golangci-lint/issues/2649#issuecomment-1075237733)

It seems that golangci-lint 1.45.0 works fine (see https://github.com/kubernetes/kubernetes/pull/108902), but there are a bunch of other go 1.18 related changes. I hope I have fixed some more of those in that PR (#108902).

**Comment by dims** [comment]
> > @kolyshkin looks like we got hit by something that just got fixed but not released yet - [golangci/golangci-lint#2649 (comment)](https://github.com/golangci/golangci-lint/issues/2649#issuecomment-1075237733)
> 
> It seems that golangci-lint 1.45.0 works fine (see #108902), but there are a bunch of other go 1.18 related changes. I hope I have fixed some more of those in that PR (#108902).

Ack. Let me see how far i get with the things here. I have the golangci-lint commented out in this PR temporarily, we can re-enable it in your PR @kolyshkin thanks for digging in!

**Comment by MadhavJivrajani** [comment]
Thanks dims!

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by endocrimes — APPROVED** [review]
/lgtm

**Pull request merged**
