### PR TITLE
Automated cherry pick of #107565: upgrade sigs.k8s.io/structured-merge-diff/v4 to v4.2.1

### PR DESCRIPTION
**Pull request by jiahuif**
Cherry pick of #107565 on release-1.20.

#107565: upgrade sigs.k8s.io/structured-merge-diff/v4 to v4.2.1

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
```release-note
kube-apiserver: when merging lists, Server Side Apply now prefers the order of the submitted request instead of the existing persisted object
```

### CODE REVIEW

**Comment by jiahuif** [comment]
Could you take a look at the backports too?
/assign @apelisse @liggitt

**Comment by liggitt** [comment]
/lgtm
/approve

no integration test change on this branch?

**Comment by jiahuif** [comment]
> /lgtm /approve
> 
> no integration test change on this branch?

Correct. The integration test case in question did not exist in 1.20.

**Comment by liggitt** [comment]
/approve cancel

discussed with @apelisse and @jiahuif ... in 1.20, SSA was still in beta, and this change likely isn't critical enough to justify adding it to the very last patch release of 1.20

**Pull request closed without merging**
