### PR TITLE
sig-instrumentation: add rexagod to other groups

### PR DESCRIPTION
**Pull request by rexagod**
#### What type of PR is this?

Add one of the following kinds:
/kind documentation

#### Special notes for your reviewer: PTAL https://github.com/kubernetes/community/pull/7664.

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by rexagod** [comment]
/priority important-soon
/triage accepted

(accepting triage based on the /lgtm above)

**Comment by rexagod** [comment]
/sig architecture

(w.r.t. https://github.com/kubernetes/kubernetes/blob/master/OWNERS#L10)

**Pull request merged**
