### PR TITLE
Make sure the previously legacy symlink deleted before create a new one

### LINKED ISSUE #61257: when delete a continer managed by k8s manually,the previously legacy symlink will not be deleted
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
/sig node

**What happened**:
when running a pod, k8s will create a symlink in /var/log/containers
```
[root@hpa-vm:/var/log/containers]$ docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
695a1e105873 6b60a9253836 "nginx -g 'daemon off" 2 minutes ago Up 2 minutes k8s_nginx_nginx-fwjjj_default_ee8301d7-290e-11e8-80e8-002dc92800b3_0
02fec5a353c1 gcr.io/google_containers/pause-amd64:3.0 "/pause" 2 minutes ago Up 2 minutes k8s_POD_nginx-fwjjj_default_ee8301d7-290e-11e8-80e8-002dc92800b3_0

[root@hpa-vm:/var/log/containers]$ ll
total 0
lrwxrwxrwx 1 root root 62 Mar 16 19:41 nginx-fwjjj_default_nginx-695a1e105873440d0b48b0ffa2cc800930035e3d5235e917795e480b7c022e7c.log -> /var/log/pods/ee8301d7-290e-11e8-80e8-002dc92800b3/nginx/0.log
```

then we delete the container manually, k8s will start a new container ,but now there are two symlinks in /var/log/containers

```
[root@hpa-vm:~]$ docker ps
CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS              PORTS               NAMES
d5dcce4761e2        6b60a9253836                                      "nginx -g 'daemon off"   3 hours ago         Up 3 hours                              k8s_nginx_nginx-fwjjj_default_ee8301d7-290e-11e8-80e8-002dc92800b3_0
02fec5a353c1        gcr.io/google_containers/pause-amd64:3.0          "/pause"                 3 hours ago         Up 3 hours                              k8s_POD_nginx-fwjjj_default_ee8301d7-290e-11e8-80e8-002dc92800b3_0

[root@hpa-vm:/var/log/containers]$ ll
total 0
lrwxrwxrwx 1 root root 62 Mar 16 19:41 nginx-fwjjj_default_nginx-695a1e105873440d0b48b0ffa2cc800930035e3d5235e917795e480b7c022e7c.log -> /var/log/pods/ee8301d7-290e-11e8-80e8-002dc92800b3/nginx/0.log
lrwxrwxrwx 1 root root 62 Mar 16 19:47 nginx-fwjjj_default_nginx-d5dcce4761e244275f0f49d0a56a0c1be097530a9a727476d41b68e528130525.log -> /var/log/pods/ee8301d7-290e-11e8-80e8-002dc92800b3/nginx/0.log
```

these two symlinks are healthy and link same log file.
**What you expected to happen**:
the previously legacy symlink could be deleted
**How to reproduce it (as minimally and precisely as possible)**:
use docker rm -f <containerid> delete a container managed by k8s

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-alpha.0.428+5d144152e4d07f", GitCommit:"5d144152e4d07f3752c05ec24e31d840adcd90a2", GitTreeState:"clean", BuildDate:"2018-02-26T02:37:04Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-alpha.0.428+5d144152e4d07f", GitCommit:"5d144152e4d07f3752c05ec24e31d840adcd90a2", GitTreeState:"clean", BuildDate:"2018-02-26T02:37:04Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by Pingan2017**
**What this PR does / why we need it**:
It can delete the possibly exiting legacy container log symlink.
When we delete a container manually,k8s start a new container. But the previous container log symlink in the dir /var/log/containers won't be deleted.  
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #61257 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by feiskyer** [comment]
dup of #58563?

**Comment by Pingan2017** [comment]
@feiskyer  It's different. Now, When we delete a container manually,the old container log symlink in the dir /var/log/containers won't be deleted. And the status of symlink is healthy. The kube gc won't delete it.

**Comment by Pingan2017** [comment]
@feiskyer 
this pr fix bug below:
when running a pod, k8s will create a symlink in /var/log/containers
[root@hpa-vm:/var/log/containers]$ docker ps
CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS              PORTS               NAMES
695a1e105873        6b60a9253836                                      "nginx -g 'daemon off"   2 minutes ago       Up 2 minutes                            k8s_nginx_nginx-fwjjj_default_ee8301d7-290e-11e8-80e8-002dc92800b3_0
02fec5a353c1        gcr.io/google_containers/pause-amd64:3.0          "/pause"                 2 minutes ago       Up 2 minutes                            k8s_POD_nginx-fwjjj_default_ee8301d7-290e-11e8-80e8-002dc92800b3_0

[root@hpa-vm:/var/log/containers]$ ll
total 0
lrwxrwxrwx 1 root root 62 Mar 16 19:41 nginx-fwjjj_default_nginx-695a1e105873440d0b48b0ffa2cc800930035e3d5235e917795e480b7c022e7c.log -> /var/log/pods/ee8301d7-290e-11e8-80e8-002dc92800b3/nginx/0.log

then we delete the container manually, k8s will start a new container and there are two symlinks in /var/log/containers
[root@hpa-vm:/var/log/containers]$ ll
total 0
**lrwxrwxrwx 1 root root 62 Mar 16 19:41 nginx-fwjjj_default_nginx-695a1e105873440d0b48b0ffa2cc800930035e3d5235e917795e480b7c022e7c.log -> /var/log/pods/ee8301d7-290e-11e8-80e8-002dc92800b3/nginx/0.log
lrwxrwxrwx 1 root root 62 Mar 16 19:47 nginx-fwjjj_default_nginx-d5dcce4761e244275f0f49d0a56a0c1be097530a9a727476d41b68e528130525.log -> /var/log/pods/ee8301d7-290e-11e8-80e8-002dc92800b3/nginx/0.log**

these two symlinks are healthy and link same log file.

**Comment by dixudx** [comment]
> dup of #58563?

They are doing the same thing, but for different purposes.

**Comment by Pingan2017** [comment]
@dixudx 
#58563 resolve the unhealthy symlink in /var/log/containers , but in this case , the symlink is healthy.
I think it can not be deleted by the kube gc.
```
[root@hpa-vm:/var/log/containers]$ ll
total 0
lrwxrwxrwx 1 root root 62 Mar 16 19:41 nginx-fwjjj_default_nginx-695a1e105873440d0b48b0ffa2cc800930035e3d5235e917795e480b7c022e7c.log -> /var/log/pods/ee8301d7-290e-11e8-80e8-002dc92800b3/nginx/0.log
lrwxrwxrwx 1 root root 62 Mar 16 19:47 nginx-fwjjj_default_nginx-d5dcce4761e244275f0f49d0a56a0c1be097530a9a727476d41b68e528130525.log -> /var/log/pods/ee8301d7-290e-11e8-80e8-002dc92800b3/nginx/0.log
```

**Pull request closed without merging**
