### PR TITLE
rename service port name variable #108806

### LINKED ISSUE #108806: Cleanup: kube-proxy internal naming
We have sort of a mish-mash of "service" and "servicePort" and similar.

We should think about changing ALL of the places that actually relate to a service-port (a specific port of a service, not the whole service) and rename them to some new term that means "service port". E.g. "svcpt" or "spt" or "sport".

See https://github.com/kubernetes/kubernetes/pull/106497/commits/8fffae321d66487f776922e0c313b33af7bf27e3 in pkg/proxy/iptables/proxier.go and friends.  e.g. `info.serviceNameString` -> `info.svcptNameString` ?

### PR DESCRIPTION
**Pull request by ak20102763**
Signed-off-by: ak20102763
This PR is intended to update the service port name string with appropriate naming convention

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it:**
changed service port string variable with appropriate names like svcPortNameString, svcptNameString

**Which issue(s) this PR fixes:**
Fixes #108806

**Special notes for your reviewer:**

**Does this PR introduce a user-facing change?**

```
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:**
```

```

/cc @justinsb

### CODE REVIEW

**Comment by gkarthiks** [comment]
there's already a PR on this: https://github.com/kubernetes/kubernetes/pull/109424

please close this.

**Comment by ak20102763** [comment]
@justinsb and @MrHohn can you please review this PR?

**Comment by ak20102763** [comment]
@k8s-ci-robot label added

**Comment by danwinship** [comment]
> there's already a PR on this: #109424

which has merged

/close

**Pull request closed without merging**
