### PR TITLE
HTTPExtender: should close resp.Body even when StatusCode not ok

### PR DESCRIPTION
**Pull request by sakeven**
Signed-off-by: sakeven <jc5930@sina.cn>

**What this PR does / why we need it**:

close resp.Body even when StatusCode isn't ok

**Special notes for your reviewer**:

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by allencloud** [comment]
good catch. 👍

**Comment by sakeven** [comment]
PTAL @davidopp @jayunit100, thanks!

**Comment by sakeven** [comment]
@k82cn could you approve no-issue?

**Comment by k82cn** [comment]
is there anyway to test it, e.g. by integration test?

**Comment by sakeven** [comment]
I think not. It's a memory leak bug, while I don't know how to test it in integration test. Any suggestion?

**Comment by k82cn** [comment]
@ravigadde , do you have any comments for this PR? If not, I'm going to get it merged.

**Comment by ravigadde** [comment]
@k82cn lgtm

**Comment by sakeven** [comment]
@k82cn PTAL,  thanks.

**Pull request merged**
