### PR TITLE
Revert 44714 manually

### LINKED ISSUE #47448: PodSecurityContext API compatibility broken between 1.6 and 1.7
** BUG REPORT** 

**Kubernetes version**: 
1.7.x with a 1.6.x kubectl or any version of helm based on a vendored client at that version.

**Environment**: 
This is an API issue affecting all environments.

**What happened**:
When you attempt to apply or create a manifest containing any containers (e.g. DaemonSet, StatefulSet, Deployment) with a PodTemplateSpec with any Container having PodSecurityContext that attempts to set RunAsUser or FSGroup you will get an error message indicating that those fields are invalid.

**What you expected to happen**:
I expect to be able to create a Pods that do not run as root.

**How to reproduce it**:
Build and install a 1.6.3 client and kube-up a cluster off of master. Attempt to create a manifest that uses the described features of security context. [Here](https://github.com/kow3ns/kubernetes-zookeeper/blob/master/manifests/zookeeper.yaml) is an example.

**Anything else we need to know**:
[This](https://github.com/kubernetes/kubernetes/commit/9440a68744ea97a45ceeef6d75466405ac101ea1) looks like the commit that modifies the v1/types.go in an incompatible way.

### PR DESCRIPTION
**Pull request by mbohlool**
#44714 broke backward compatibility for old swagger spec that kubectl still uses. The decision on #47448 was to revert this change but the change was not automatically revertible. Here I semi-manually remove all references to UnixUserID and UnixGroupID and updated generated files accordingly.

Please wait for tests to pass then review that as there may still be tests that are failing.

Fixes #47448

Adding release note just because the original PR has a release note. If possible, we should remove both release notes as they cancel each other.

**Release note**: (removed by caesarxuchao)

UnixUserID and UnixGroupID is reverted back as int64 to keep backward compatibility.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Probably we should nuke the release note in the original PR and this PR.

**Comment by caesarxuchao** [comment]
The manual changes look good. The original PR touched 120 files, this one touched 117 files, wonder what are missed.

**Comment by dchen1107** [comment]
/lgtm

xref: https://github.com/kubernetes/kubernetes/issues/38120

**Comment by caesarxuchao** [comment]
This is blocking lifting code freeze, so apply the label.

**Pull request merged**
