### PR TITLE
Delete unused return

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
We do not use the function return, it's better not to write the return.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by k82cn** [comment]
@k8s-bot ok to test

**Comment by jayunit100** [comment]
@zhangxiaoyu-zidif I'm all for cleanup, but can you audit predicates.go for other cleanup as well ? 
There is other cleanup, for example: -
- functions like `haveSame` (i wonder, if that functionality exists elsewhere / should that be a util)? 
- `getMatchingAntiAffinityTerms` , `satisfiesExistingPodsAntiAffinity` have no function comments, and are relatively important.
- `isPodBestEffort` has the wrong godoc comment format and so on?

Maybe  cleaning up all the comment headers along side this variable cleanup would be a great patch to predicates.go :)

**Comment by zhangxiaoyu-zidif** [comment]
@jayunit100 Thanks, I would like to do more cleanup work.
I fix other similar cleanup in this file.
As you mentioned function and comment, that is in 'kubernetes/plugin/pkg/scheduler/algorithm/predicates', I will check that file later. :)

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by gyliu513** [comment]
FYI, another clean up here https://github.com/kubernetes/kubernetes/pull/47566 @jayunit100

**Comment by brendandburns** [comment]
/lgtm

/release-note-none

LGTM + release-note-none from the bulk LGTM tool

**Comment by k82cn** [comment]
@brendandburns , /approve no-issue please :).

**Pull request merged**
