### PR TITLE
move no k8s.io/kubernetes dependencies round 01

### PR DESCRIPTION
**Pull request by deads2k**
Builds on the previous, adds unit testing the staging dir.

moves

 1. pkg/healthz -> apiserver/pkg/healthz
 2. pkg/util/flushwriter -> apiserver/pkg/util/flushwriter
 3. pkg/auth/authenticator -> apiserver/pkg/authentication/authenticator
 4. pkg/auth/authorizer -> apiserver/pkg/authorization/authorizer

@sttts

### CODE REVIEW

**Comment by fejta** [comment]
@k8s-bot unit test this

**Comment by sttts** [comment]
lgtm

**Comment by deads2k** [comment]
@k8s-bot cvm gce e2e test this

**Comment by thockin** [comment]
This broke `make test WHAT=local/path`  I can't see what justified that
change to the test script?

**Comment by deads2k** [comment]
> This broke `make test WHAT=local/path`  I can't see what justified that
> change to the test script?

Creating fake repos in the `staging` folder (suggested by @lavalamp since CI can't coordinate multiple repos yet) means that the root is not always `k8s.io/kubernetes`.  Sometimes it is `k8s.io/apiserver`.  The unit tests still need to be run, but since the base of the packages can be different, it is possible to have collisions.  `pkg/foo` is not unambiguous.  Did you mean `k8s.io/kubernetes/pkg/foo` or `k8s.io/apiserver/pkg/foo`?  You have to provide unambiguous input, so you must say `make test WHAT=k8s.io/kubernetes/pkg/foo`.

**Comment by thockin** [comment]
This is not the semantic that has existed and been offered through
Makefile.  The semantic is that a WHAT is a local path.

**Pull request merged**
