### PR TITLE
build: update to klog v2.70.1

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

This makes ktesting more resilient against logging from leaked goroutines,
which is a problem that came up in kubelet node shutdown
tests (https://github.com/kubernetes/kubernetes/issues/110854).

#### Which issue(s) this PR fixes:
Related-To: https://github.com/kubernetes/kubernetes/issues/110854 - a more complete fix of that test would be to not leak goroutines

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/approve
/lgtm
/assign @liggitt 

Small update to klog to fix something we got wrong.

**Comment by pohly** [comment]
/retest

Some overall flakiness, test cluster didn't come up?

**Pull request merged**
