### PR TITLE
Change merge key for VolumeMount to mountPath

### LINKED ISSUE #34800: kubectl edit brokenness editing volumeMounts (list of struct)
Start with:

```        
       volumeMounts:
        - mountPath: /vol
          name: vol 
        - mountPath: /vol-456                                                                                                                                 
          name: vol 
          subPath: d456
```

Edit to:

```
        volumeMounts:
        - mountPath: /vol
          name: vol 
        - mountPath: /vol-d2
          name: vol
          subPath: d2     
```

Read back what happened:

```
        volumeMounts:
        - mountPath: /vol-d2
          name: vol 
          subPath: d2
        - mountPath: /vol-456
          name: vol 
          subPath: d456
```

It synthesized a COMPLETELY WRONG result.  At this point, I can not, in good conscience, advocate using kubectl edit.

Can I please have `kubectl edit --replace` that doesn't go through patch brokenness.  Or better, make that default for 1.5 and make `kubectl edit --patch`   be the broken (but eventually fixed) path.

### PR DESCRIPTION
**Pull request by thockin**
Fixes #34800

``` release-note
Change merge key for VolumeMount to mountPath
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35071)

### CODE REVIEW

**Comment by ymqytw** [comment]
@k8s-bot gci gke e2e test this

**Comment by adambom** [comment]
This is a breaking change. Any reason you'd include this in a patch version update (1.4.3 -> 1.4.4)?

**Comment by pwittrock** [comment]
Link to 1.5 Issue Accumulator #37134

Summary:

```
The strategicmerge patchMergeKey for VolumeMounts was changed from "name" to "mountPath".  This is because the name field  is the name of the Volume, not the unique key of the VolumeMount.  Multiple VolumeMounts will have the same Volume name if mounting the same volume.  The "mountPath" is intended to be unique and can act as the mergekey.
```

**Pull request merged**
