### PR TITLE
Fixes and minor cleanups to pod (anti)affinity predicate

### PR DESCRIPTION
**Pull request by wojtek-t**

### CODE REVIEW

**Comment by bsalamat** [comment]
/lgtm

Thanks, @wojtek-t!

**Comment by wojtek-t** [comment]
@k8s-bot unit test this

**Comment by wojtek-t** [comment]
@bsalamat - thanks; though to be clear, this is not fixing the main issue we were discussing, it's still not debugged

**Comment by bsalamat** [comment]
Yes, I am aware that this is not addressing that issue.

**Comment by davidopp** [comment]
LGTM

**Comment by k82cn** [comment]
LGTM.

**Comment by k82cn** [comment]
btw, it seems the unit test did not check this issue. Should we add one for it? I can help to create PR to update unit test as a follow up.

**Comment by davidopp** [comment]
Sure, if you can create a test case for it that would be great.

**Comment by wojtek-t** [comment]
@k8s-bot bazel test this

**Comment by k82cn** [comment]
#45152 was created for unit test of this fix.

**Pull request merged**
