### PR TITLE
Convert controller garbage files to structured logs

### PR DESCRIPTION
**Pull request by scottilee**
#### What type of PR is this?
/kind cleanup
/sig instrumentation

#### What this PR does / why we need it:
Converts log statements to use structured logging.

#### Which issue(s) this PR fixes:
N/A

#### Special notes for your reviewer:
N/A

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
- [KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1602-structured-logging/kep.yaml
```

### CODE REVIEW

**Comment by scottilee** [comment]
@yangjunmyfm192085 What else do I need to do to get this diff approved and landed?

**Review by yangjunmyfm192085 — COMMENTED** [review]
/lgtm
we need  approvers of pkg/controller/garbagecollector/OWNERS and pkg/hack to label /approve

**Review by yangjunmyfm192085 — COMMENTED** [review]
/assign @caesarxuchao

**Review by yangjunmyfm192085 — COMMENTED** [review]
/assign @SataQiu

**Pull request closed without merging**
