### PR TITLE
delete unused cache

### PR DESCRIPTION
**Pull request by mikedanese**
We aren't using this anywhere and it's not named properly for what it
is. We should either rename it or delete it (both break the package
API).

Opening as draft before mailing  to make sure I ran all the tests.

/kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
We have TWO of these monstrosities?

/approve

No good deed goes unpunished: 

> Some packages in hack/.golint_failures are passing golint. Please remove them.
>      `staging/src/k8s.io/apimachinery/pkg/util/cache`

**Comment by mikedanese** [comment]
@lavalamp tests are green.

**Comment by lavalamp** [comment]
/lgtm

It doesn't seem to be recognizing your release note, not sure why.

**Pull request merged**
