### PR TITLE
Run client-go/copy.sh

### PR DESCRIPTION
**Pull request by wongma7**
I ran client-go/copy.sh in branch `release-1.4` and cherrypicked the commit onto master. I am not sure what I should have done, I assume just running it in master is not okay because it brings in 1.5 code.

Doing this for the new storage api group in 1.4 https://github.com/kubernetes/kubernetes/pull/31886

@caesarxuchao since client-go and you looked at my previous

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32502)

### CODE REVIEW

**Comment by wongma7** [comment]
Oops, I did not even regenerate a 1.4 clientset for `StorageClasses`

**Comment by caesarxuchao** [comment]
Can you wait for https://github.com/kubernetes/contrib/pull/1719 to be merged? That PR will make our publisher bot pull contents from the 1.4 branch and publish it to the client-go/1.4 folder. And the staging area of the master branch will only have a 1.5 folder.

So after https://github.com/kubernetes/contrib/pull/1719 get merged, you can run the copy.sh in the 1.4 branch and send a PR agianst the 1.4 branch.

**Comment by wongma7** [comment]
@caesarxuchao I see the publisher merged (subscribed), so just to make sure this is how I will proceed in order to get the storage api group into 1.4 clientset? It's not too late right?

Working in release-1.4 branch...
1. Edit hack/update-codegen.sh to add the missing storage api group to the --input argument of clientgen
2. Run hack/update-codegen.sh to generate the latest 1.4 clientset
3. Target all the changes to the release-1.4 branch.

Storage is not the only api group missing (https://github.com/kubernetes/kubernetes/issues/33096) so I can also add certificates and rbac in the same PR, is that okay?

**Comment by caesarxuchao** [comment]
@wongma7 thanks for taking care of this! The steps you described look good.

I talked to @pwittrock who's in charge of the 1.4 release, we want to make the 1.4 release this Friday or next Monday. We'd better not destabilize the branch before then. I think making client-go complete is less urgent, we can wait until next week.

Could you make the PR as you described, I'll review it, and let's get it merged once the 1.4 release is done?

**Comment by wongma7** [comment]
OK, to keep things organized I will close this, open a fresh new PR when the time comes and ping you with it.

**Pull request closed without merging**
