### PR TITLE
Make testing service validation easier

### PR DESCRIPTION
**Pull request by thockin**
Part of multi-port services.

If people like this, we could start to apply this pattern elsewhere.

TL;DR: don't redefine objects over and over changing one thing each
time.  Instead provide a func that mutates a base object to test facets
of validation.  Much easier to read and to update.

### CODE REVIEW

**Comment by alex-mohr** [comment]
FWIW, I'm kind of ambivalent about these kinds of factorings.  I think for pure validation testing having a base valid object and changing it to make it invalid is good -- as done here.

But for most testing, I generally prefer less indirect code in tests and more "this specific configuration is supposed to be valid" as it's sometimes less prone to issues where you're not actually testing what you think you're testing.  Don't feel amazingly strongly though.  Note there was a ToTT in the last year on this issue, but I can't find it via a quick search -- and happy to defer to @ixdy on this.

**Comment by thockin** [comment]
In general I agree.  In this case I found myself doing REALLY dumb, repetitious changes over and over due to something totally unrelated to the test.  In so doing I could not even figure out what the different test cases were actually testing.

Ideally a test case contains JUST the code needed to capture the exact scenario.  I think this approach does that much better.  Of course, this kind of test is very specific, so this pattern may not apply to other cases.

**Comment by bgrant0607** [comment]
We've talked about various solutions, including "test fixtures", such as this -- common patterns could go into testing libraries. 

Personally, I think we shouldn't ever be directly creating objects using the internal representation.

But this doesn't seem worse than what existed.

**Comment by thockin** [comment]
It's a step towards constructors, anyway

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
