### PR TITLE
Add SELinux security context to ContainerLogPath test

### LINKED ISSUE #101311: ContainerLogPath test fails on SELinux based system
#### Which jobs are failing:
ci-crio-cgroupv1-node-e2e-conformance

#### Which test(s) are failing:
ContainerLogPath

#### Since when has it been failing:
It was failing last week, then I disabled the SELinux while we investigated the issue https://github.com/kubernetes/test-infra/pull/21846. Once this PR merges, I will enable the SELinux again for CRIO jobs. 

#### Testgrid link:
https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-conformance

#### Reason for failure:
Once the SELinux is turned on and all the required components in the OS (e.g. crio, runc) are compiled with SELinux support we observed following errors in audit logs,

```
[ 9497.346906] audit: type=1400 audit(1618571675.758:5100): avc: denied { open } for pid=54978 comm="grep" path="/var/log/pods/kubelet-container-log-path-7796_log-pod-e327937f-399f-4859-aa55-3307477fc420_343482f0-2622-414d-94ee-8d0371ddda65/logger/0.log" dev="sda4" ino=58879108 scontext=system_u:system_r:container_t:s0:c743,c914 tcontext=system_u:object_r:container_log_t:s0 tclass=file permissive=1
[ 9497.387702] audit: type=1400 audit(1618571675.758:5101): avc: denied { ioctl } for pid=54978 comm="grep" path="/var/log/pods/kubelet-container-log-path-7796_log-pod-e327937f-399f-4859-aa55-3307477fc420_343482f0-2622-414d-94ee-8d0371ddda65/logger/0.log" dev="sda4" ino=58879108 ioctlcmd=0x5401 scontext=system_u:system_r:container_t:s0:c743,c914 tcontext=system_u:object_r:container_log_t:s0 tclass=file permissive=1
```
Which points towards incorrect SELinux labeling.

### PR DESCRIPTION
**Pull request by harche**
Signed-off-by: Harshal Patil <harpatil@redhat.com>

#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:
Without this fix the test `ContainerLogPath` fails on the system with SELinux support

#### Which issue(s) this PR fixes:

Fixes #101311 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by harche** [comment]
/hold 

Will remove it after some more local test runs.

**Comment by harche** [comment]
Results from the node where SELinux is enabled,
```bash
[root@localhost core]# getenforce 
Enforcing
```

```
Ran 198 of 346 Specs in 789.994 seconds
SUCCESS! -- 198 Passed | 0 Failed | 0 Pending | 148 Skipped
```

/hold cancel

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by harche** [comment]
Thanks @saschagrunert 

/cc @mrunalp for the approval

**Pull request merged**
