### PR TITLE
Bring PVC Protection feature to Beta

### PR DESCRIPTION
**Pull request by pospispa**
**What this PR does / why we need it**:
Brings PVC Protection feature to Beta.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # N/A

**Special notes for your reviewer**:
xref https://github.com/kubernetes/features/issues/498

**Release note**:

```release-note
PVC Protection alpha feature was renamed to Storage Protection. Storage Protection feature is beta.
```

### CODE REVIEW

**Comment by jsafrane** [comment]
/lgtm
/assign @lavalamp @liggitt 
for approvals

**Comment by NickrenREN** [comment]
@pospispa  I rename the `PVCProtection` feature gate to `StorageProtection` and reuse it for `PVProtection` according to the discussion with @jsafrane .  See https://github.com/kubernetes/kubernetes/pull/58743 Could you please update this PR ? 
cc @jsafrane

**Comment by pospispa** [comment]
@NickrenREN I forgot about the rename. Thank you for reminding me. I updated this PR accordingly.

**Comment by liggitt** [comment]
policy LGTM
/approve

**Comment by jsafrane** [comment]
/assign @thockin @smarterclayton 
for approval
Note discussion in https://github.com/kubernetes/kubernetes/issues/59639

**Comment by jsafrane** [comment]
@thockin, please approve

**Pull request merged**
