### PR TITLE
On AttachDetachController node status update, do not retry when node …

### LINKED ISSUE #50721: Pod stuck in ContainerCreating with log message "Volume is not yet attached according to node"
**Is this a BUG REPORT or FEATURE REQUEST?**: bug

/kind bug

**What happened**:
* Deployment running with read-only GCE PD.
* A node containing one of the deployment pods is deleted and recreated soon after.
* New pod is scheduled to the same node, but is stuck in ContainerCreating state. The node's kubelet logs show continuous "Volume is not yet attached according to node" errors.

**What you expected to happen**: Pod recreated successfully.

**Anything else we need to know?**: Cause by PR https://github.com/kubernetes/kubernetes/pull/45923

The issue happens as follows:
* When the node is deleted, GCE PD is detached from the cloud provider.
* AttachDetachController discovers the PD has been detached, and marks it as detached.
* The original pod still exists in the API server (i.e. before garbage collection), so AttachDetachController reattaches the PD, successfully.
* Before the node recovers, ADC tries to update the node status but finds that the node doesn't exist. Following the logic introduced in https://github.com/kubernetes/kubernetes/pull/45923 it never attempts to update the node status again.
* The node recovers, a new pod is scheduled to it, waits for a successful attach signal in the node status but never gets it.

/cc @jingxu97 @msau42 
/sig storage

### PR DESCRIPTION
**Pull request by verult**
…doesn't exist but keep the node entry in cache.

**What this PR does / why we need it**: An alternative fix for https://github.com/kubernetes/kubernetes/issues/42438 which also fixes #50721.

Instead of removing the node entry entirely from the node status update cache (which prevents the node from ever being updated even when it recovers), here the node status updater does nothing, so that there won't be an update retry until the node is re-added, where the cache entry is set to true.

Will cherry pick to prior versions after this is merged.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50721 

**Release Note**:
``` release-note
Fix for Pod stuck in ContainerCreating with error "Volume is not yet attached according to node".
```

/assign @jingxu97 
/cc @saad-ali 
/sig storage
/release-note

### CODE REVIEW

**Review by saad-ali — APPROVED** [review]
Removing code == best kind of fix!

/lgtm
/approve

Make sure to cherry pick as appropriate

**Comment by saad-ali** [comment]
Modify the first comment to include a user friendly release note in the correct release note format.

**Comment by wojtek-t** [comment]
Cherrypick approved and created in https://github.com/kubernetes/kubernetes/pull/51177

**Pull request merged**
