### PR TITLE
Change "speter.net/go/exp/math/dec/inf" dependency to new location

### LINKED ISSUE #23529: package "speter.net/go/exp/math/dec/inf" caused godep failure
I have encountered the following error in CI:
```
Starting to download all kubernetes godeps. This takes a while
godep: error downloading dep (speter.net/go/exp/math/dec/inf): unrecognized import path "speter.net/go/exp/math/dec/inf"
godep: Error downloading some deps. Aborting restore and check.
!!! Error in hack/../hack/verify-godeps.sh:71
  '"${GODEP}" restore' exited with status 1
Call stack:
  1: hack/../hack/verify-godeps.sh:71 main(...)
Exiting with status 1
```

link: https://travis-ci.org/kubernetes/kubernetes/builds/118770263

### PR DESCRIPTION
**Pull request by saad-ali**
This PR fixes https://github.com/kubernetes/kubernetes/issues/23529 by:
- Changing "speter.net/go/exp/math/dec/inf" dependency to "https://gopkg.in/inf.v0"
- Updating vendor dir and Godeps.json with new Godep
- Updating Godep licenses

### CODE REVIEW

**Comment by saad-ali** [comment]
CC @eparis This should unblock the merge queue. Will merge on green

**Comment by eparis** [comment]
looks like PR was created with v54+ (and my script)  gotta use v53

**Comment by saad-ali** [comment]
Just pushed a new commit to modify `verify-godeps` to use v63 with your hack patched in. That should fix it, will wait for green to verify.

After your change goes in, we can modify verify-godeps to call `godep-save.sh` so that we don't have to maintain the list of exceptions in two different places.

@thockin says he'll try to vendor Godep itself so that everyone ends up with the same version.

**Comment by saad-ali** [comment]
Looks good:
```
SUCCESS  ./hack/../hack/verify-api-reference-docs.sh	30s
SUCCESS  ./hack/../hack/verify-boilerplate.sh	0s
SUCCESS  ./hack/../hack/verify-codecgen.sh	512s
SUCCESS  ./hack/../hack/verify-codegen.sh	36s
SUCCESS  ./hack/../hack/verify-description.sh	2s
SUCCESS  ./hack/../hack/verify-generated-docs.sh	147s
SUCCESS  ./hack/../hack/verify-generated-protobuf.sh	46s
SUCCESS  ./hack/../hack/verify-generated-swagger-docs.sh	39s
SUCCESS  ./hack/../hack/verify-godep-licenses.sh	42s
SUCCESS  ./hack/../hack/verify-godeps.sh	460s
SUCCESS  ./hack/../hack/verify-gofmt.sh	7s
SUCCESS  ./hack/../hack/verify-govet.sh	179s
SUCCESS  ./hack/../hack/verify-import-boss.sh	10s
    /go/src/k8s.io/kubernetes/hack/../api/swagger-spec
+++ [0511 18:33:36] SUCCESS
SUCCESS  ./hack/../hack/verify-swagger-spec.sh	51s
SUCCESS  ./hack/../hack/verify-symbols.sh	31s
SUCCESS  ./hack/../hack/verify-flags-underscore.py	26s
SUCCESS  ./hack/../hack/verify-flags-underscore.py	26s
```

Manually merging

**Comment by freeformz** [comment]
Why not v66 ?

**Comment by thockin** [comment]
We can't try every release.  we tried 63 and it worked.  Given the
propensity for godep to fail for unknown reasons, we need to just stay
locked until we have a reason to change.

**Comment by freeformz** [comment]
@thockin Test coverage is better then ever. ;-)

**Comment by Seb-Solon** [comment]
Hi,

 Will this be backported to previous version? I  may need to rebuild kubernetes and the dep will fail. 

Regards

**Comment by eparis** [comment]
I don't plan to. Previous versions will still build just fine. They build from godeps. (That's about 99% of our value of Godeps)

This will only impact you if you try to run `verfiy-godeps.sh` on a previous version. (which might be a problem in CI and I'll help @roberthbailey and @zmerlynn if they do run into CI issues with future 1.2 cherrypicks.

**Pull request merged**
