### PR TITLE
Kubelet rkt CRI ImageService

### PR DESCRIPTION
**Pull request by tmrts**
Contains the ImageService stub and the basic tests for the implementation.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29914)

### CODE REVIEW

**Comment by euank** [comment]
LGTM as a stub.

The more important thing to be sure of before merging this is whether we're confident this is the right place for the code to live at the moment. I know that where it lives now does not mean it will always live here (and I personally lean towards it living as a separate server-impl repository akin to how hyper's CRI is setup).
I'm okay with it as, pending us having an external client/server-like implementation, this does seem like the most sane place.

cc @yujuhong if you want to throw in an opinion on the code living here for the moment.

**Comment by tmrts** [comment]
@euank this is just so we can progress, I don't believe the pkg name should be `rktshim` for example, so there are some placeholders that we'll definitely be eliminating in the future (e.g. maybe a separate repository?)

**Comment by yujuhong** [comment]
> @euank this is just so we can progress, I don't believe the pkg name should be rktshim for example, so there are some placeholders that we'll definitely be eliminating in the future (e.g. maybe a separate repository?). As you pointed out those are not blockers for the CRI implementation

I think we should start with a new repository if the code is not going to live here in the future. @tmrts, could you elaborate more on how this placeholder could help with the progress? If the reasons are valid, we can temporarily host the code in kubelet.

By the way, a minor thing -- the dockershim is kind of a misnomer, since it's actually a kubelet shim for docker. I take full responsibility of that, but suggestions of better names are always welcome.

**Comment by tmrts** [comment]
>
> @euank <https://github.com/euank> this is just so we can progress, I
> don't believe the pkg name should be rktshim for example, so there are some
> placeholders that we'll definitely be eliminating in the future (e.g. maybe
> a separate repository?). As you pointed out those are not blockers for the
> CRI implementation
>
> I think we should start with a new repository if the code is not going to
> live here in the future. @tmrts <https://github.com/tmrts>, could you
> elaborate more on how this placeholder could help with the progress? If the
> reasons are valid, we can temporarily host the code in kubelet.
>
I was referring to the location of runtime shims being undecided. If we
choose to proceed with a separate repo, we can move the code there easily
since the point of CRI is loose-coupling, therefore rktshim doesn't
introduce an additional overhead.

Basically, hosting the rktshim in the main repo is either temporary or
permanent, in both cases implementing/refactoring in the main repo makes
sense the most, so that we have the new pkg (rktshim) and the pkg to be
deprecated (kubelet/rkt) close for making the transition as smooth as
possible


> By the way, a minor thing -- the dockershim is kind of a misnomer, since
> it's actually a kubelet shim for docker. I take full responsibility of
> that, but suggestions of better names are always welcome.
>
I feel the same, I was looking for a name and decided to call it rktshim
temporarily, I'd be surprised if this name happens to be the final name
after all is said and done :)

**Comment by yujuhong** [comment]
> Basically, hosting the rktshim in the main repo is either temporary or
> permanent, in both cases implementing/refactoring in the main repo makes
> sense the most, so that we have the new pkg (rktshim) and the pkg to be
> deprecated (kubelet/rkt) close for making the transition as smooth as
> possible

I think rktshim will be significantly different than the current rkt package, so keeping them side-by-side for transition may not add much value. You could benefit from higher velocity (e.g., merging process) in a separate repo. Just my two cents.

**Comment by yifan-gu** [comment]
Stub LGTM. 
Nit for the testing is I feel some of them are little bit too verbose even for later. I imagine we will have a rkt API client to do API calls, and we mock the client, so all we need to test is for each interface here we end up with expected rkt API requests, so that we don't need to implement a fake rkt API server logic. If that makes sense? But since they are all skipped tests, we can leave as is for now.

+1 on a separate repo for velocity.

**Comment by tmrts** [comment]
@yujuhong I agree about merge velocity, but its undecided whether rktnetes code will be imported or invoked via RPC methods and I don't want to get into the dependency vendoring with Kubernetes (vendoring k8s util packages & interfaces). Temporarily, I'll continue within the main repo, however that's not to say that I'm opposed to a separate repo

**Comment by yujuhong** [comment]
> @yujuhong I agree about merge velocity, but its undecided whether rktnetes code will be imported or invoked via RPC methods and I don't want to get into the dependency vendoring with Kubernetes (vendoring k8s util packages & interfaces). Temporarily, I'd like to continue within the main repo, however that's not to say that I'm opposed to a separate repo

I am fine with this as a temporary solution, but `rktshim` package should avoid importing non-k8s-api packages (e.g., the utils). This would make the future transition (spinning off to a separate repository) easier.

**Comment by tmrts** [comment]
@yujuhong thanks, definitely will be paying attention to component coupling 👍 

Applying LGTM per @euank and @yifan-gu s review

**Comment by yujuhong** [comment]
In the sig-node meeting today, @dchen1107 has volunteered to setup a separate repository for rkt integration. @tmrts, is this PR still necessary?

**Comment by tmrts** [comment]
Discussed with @yujuhong OOB, there was a misunderstanding regarding the goal of this PR. The goal is to gradually refactor the current rktnetes code to use the new CRI types (e.g. ImageService, PodSandboxManager) so that this code is tested and rktnetes stability for the moment is increased

**Pull request merged**
