### PR TITLE
Use RWMutex for accessing scheduler factory obj

### LINKED ISSUE #76248: Use RWMutex for accessing plugins
**What would you like to be added**:
Currently Mutex lock is acquired in plugins.go for accessing different maps.
Some functions only read map entry:
```
func IsFitPredicateRegistered(name string) bool {
        schedulerFactoryMutex.Lock()
        defer schedulerFactoryMutex.Unlock()
        _, ok := fitPredicateMap[name]
```
We can utilize RWMutex where the above function acquires read lock.

**Why is this needed**:
For concurrent calls to IsFitPredicateRegistered / IsPriorityFunctionRegistered, read lock would lower contention.

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This is continuation of #76245 

**Which issue(s) this PR fixes**:
Fixes #76248

```release-note
NONE
```

### CODE REVIEW

**Comment by tedyu** [comment]
cc @Huang-Wei

**Comment by tedyu** [comment]
@Huang-Wei 
All tests passed

**Comment by tedyu** [comment]
ping @bsalamat and @k82cn for review

**Comment by tedyu** [comment]
@Huang-Wei
According to your comment from Sunday, I thought you would review my PR (after your change went in).

**Review by Huang-Wei — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
