### PR TITLE
Remove prometheus dependencies for volume

### PR DESCRIPTION
**Pull request by mengjiao-liu**
Co-authored-by: gavinfish <drfish.me@gmail.com>

#### What type of PR is this?
/kind feature
/kind cleanup

#### What this PR does / why we need it:
Cleanup: remove prometheus dependencies for volume.

#### Which issue(s) this PR fixes:

Part of #89267
Ref https://github.com/kubernetes/enhancements/issues/1238

Previous PR https://github.com/kubernetes/kubernetes/pull/98729

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1209-metrics-stability/metrics-stability-migration.md
```

/sig instrumentation
/sig storage

### CODE REVIEW

**Comment by lavalamp** [comment]
/approve

tests are unhappy, you can get an LGTM from someone else when you get them fixed.

**Comment by mengjiao-liu** [comment]
test passed.

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

Thanks for cleaning this up! This is great!

**Pull request merged**
