### PR TITLE
audit/request.go remove inaccurate TODO and fix typo

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

 remove one inaccurate `TODO` and fix a typo

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by crassirostris** [comment]
It's not unused, it's been added recently and is going to be used e.g. in https://github.com/kubernetes/kubernetes/pull/58807

**Comment by crassirostris** [comment]
@sttts Are you sure those are really unused methods?

**Comment by sttts** [comment]
https://github.com/kubernetes/kubernetes/pull/58679 needs a rebase. 

Maybe @CaoShuFeng is out, if anybody wants to take over.

**Comment by CaoShuFeng** [comment]
I am back from Chinese new year holiday.
@hzxuzhonghu will also show up soon, I guess.

**Comment by hzxuzhonghu** [comment]
@CaoShuFeng I see your following pr, and actually these functions are useful.

**Comment by hzxuzhonghu** [comment]
reverted and only fix little bug.

**Pull request merged**
