### PR TITLE
Add Jordan Liggitt as a top-level owner

### PR DESCRIPTION
**Pull request by thockin**
I was surprised to find that his lgtm was not enough to merge some change.

 /kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Comment by bgrant0607** [comment]
We should have done this years ago, or at least when adding Jordan as an API approver.
/lgtm
/approve

**Comment by dims** [comment]
/lgtm 

👍

**Comment by smarterclayton** [comment]
As Tim said, get crackin on those changelog typo PRs

**Pull request merged**
