### PR TITLE
Updated auto generated codes.

### PR DESCRIPTION
**Pull request by k82cn**
Fixes missed generated codes.

Generated by `./hack/update-federation-api-reference-docs.sh`, `./hack/update-generated-swagger-docs.sh`
, `./hack/update-federation-generated-swagger-docs.sh`, `./hack/update-federation-swagger-spec.sh`

### CODE REVIEW

**Comment by k82cn** [comment]
@k8s-bot unit test this

**Comment by k82cn** [comment]
@k8s-bot gci gke e2e test this

**Comment by k82cn** [comment]
@shashidharatd , would you help to remove `do-not-merge` label to get it merge :).

**Comment by shashidharatd** [comment]
@madhusudancs, please approve this pr

**Review by madhusudancs — COMMENTED** [review]
/approve

**Comment by k82cn** [comment]
@shashidharatd , sorry for update :(, found another missed updated doc, generated by script.

**Comment by shashidharatd** [comment]
no problem
/lgmt

**Comment by shashidharatd** [comment]
no problem
/lgtm

**Comment by k82cn** [comment]
@k8s-bot gci gke e2e test this

**Comment by k82cn** [comment]
@k8s-bot cvm gce e2e test this

**Comment by k82cn** [comment]
@k8s-bot cvm gce e2e test this

**Pull request merged**
