### PR TITLE
Remove the nesting directory webhook/webhook

### PR DESCRIPTION
**Pull request by caesarxuchao**
A mechanical change to remove the accidental nesting webhook/webhok directory.

@deads2k lgtm'ed the change and approved for self tagging over a slack chat.

### CODE REVIEW

**Comment by deads2k** [comment]
9 tests are still wedged.  that's weird

/test all

**Comment by caesarxuchao** [comment]
Rebased to see if the godep failure resolved.

**Comment by caesarxuchao** [comment]
@sttts do you know if there is any godep save/restore glitch in the kuberentes repo?

The first commit of this PR moves a folder, it shouldn't cause any change in k8s.io/kubernetes/Godeps/Godeps.json. However, I need the second commit to remove three packages  from the Godeps.json:
```
github.com/aws/aws-sdk-go/private/protocol/restxml
github.com/aws/aws-sdk-go/service/route53
github.com/miekg/coredns/middleware/etcd/msg
```

The removal is legit, those packages are not vendored by anyone. But I don't know why they were not removed earlier.

**Comment by sttts** [comment]
> do you know if there is any godep save/restore glitch in the kuberentes repo?

Nothing I know of.

**Pull request merged**
