### PR TITLE
Fix crash of kube-proxy when disabled healthz

### LINKED ISSUE #88020: kube-proxy will crash with healthz-port=0
kube-proxy crash like this:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x14363f6]

goroutine 123 [running]:
k8s.io/kubernetes/pkg/proxy/healthcheck.(*ProxierHealthServer).Updated(0x0)
	/data1/choury/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/healthcheck/proxier_health.go:84 +0x26
k8s.io/kubernetes/pkg/proxy/iptables.(*Proxier).SyncLoop(0xc000477800)
	/data1/choury/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/proxy/iptables/proxier.go:513 +0x62
k8s.io/kubernetes/cmd/kube-proxy/app.(*ProxyServer).Run(0xc00012d7a0, 0xc000128600, 0xc000128600)
	/data1/choury/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:724 +0x712
k8s.io/kubernetes/cmd/kube-proxy/app.(*Options).runLoop.func1(0xc0004caa80)
	/data1/choury/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:333 +0x34
created by k8s.io/kubernetes/cmd/kube-proxy/app.(*Options).runLoop
	/data1/choury/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:332 +0x50
```
It should check nil interfaces properly

/sig network
/kind bug
/assign

### PR DESCRIPTION
**Pull request by choury**
**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #88020

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix crash of kube-proxy when disabled healthz
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
is this a duplicate of https://github.com/kubernetes/kubernetes/pull/87870?

**Comment by choury** [comment]
> is this a duplicate of #87870?

ooh, there is another fix, I didn't notice that.

**Comment by danwinship** [comment]
Thanks for the PR, but this version is definitely wrong. If we don't want something like #87870 we want something like #49137
/close

**Comment by danwinship** [comment]
> this version is definitely wrong

(that sounded harsher than I meant it to...)

**Pull request closed without merging**
