### PR TITLE
Start deprecating all generators in run except for run-pod/v1

### PR DESCRIPTION
**Pull request by soltysh**
**What this PR does / why we need it**:
This was discussed during SIG-CLI meetings over several past months. The direction is that we want to move away from `kubectl run` because it's over bloated and complicated for both users and developers. We want to mimic `docker run` with `kubectl run` so that it *only* creates a pod, and if you're interested in other resources `kubectl create` is the intended replacement. 

This PR starts with deprecating all of the generator except for the pod one.

/assign @juanvallejo 
/sig cli
/milestone v1.12

**Release note**:
```release-note
Deprecate kubectl run generators, except for run-pod/v1
```

### CODE REVIEW

**Review by juanvallejo — APPROVED** [review]

**Comment by brendandburns** [comment]
@soltysh can we get some clarification here, it seems that 'kubectl run <pod>' will remain, but the deprecation warning for 'kubectl run' seems to indicate that it's all going to be deprecated.

I think that this is because the default for `kubectl run` is `Deployment` based, not run Pod, but I think that is leading to some confusion (e.g. https://stackoverflow.com/questions/52890718/kubectl-run-is-deprecated-looking-for-alternative)

I think we should make it clear that a user can run:

`kubectl run --generator=run-pod/v1 ...` to get the behavior they likely want rather than looking for a new command.

**Comment by soltysh** [comment]
@brendandburns the main gist is, we want the `kubectl run` to mimic `docker run` in k8s world. For creating resources we already have a bunch of `kubectl create` sub-commands. Additionally, the vast majority of different options and their influence on the actual resource produces by `kubectl run` is another reason we're going into simple and straightforward direction. I've replied in the SO thread. I'll also post that on my personal twitter, appreciate retweets for greater audience.

**Comment by soltysh** [comment]
I've also opened https://github.com/kubernetes/kubernetes/pull/70288 to improve the deprecation warning.

**Comment by mbigras** [comment]
This change breaks the example in the most recent [Kubernetes Up & Running](https://hello-tanzu.vmware.com/kubernetes-up-and-running-2/) in the Service Discovery section. The following command is used:

```
$ kubectl run alpaca-prod \
 --image=gcr.io/kuar-demo/kuard-amd64:blue \
 --replicas=3 \
 --port=8080 \
 --labels="ver=1,app=alpaca,env=prod"
```

Using the `--generator=run-pod/v1` flag idea like @brendanburns suggested doesn't work either:

```
$ kubectl run alpaca-prod --generator=run-pod/v1 --image=gcr.io/kuar-demo/kuard-amd64:blue --port=8080 --labels="app=foo,ver=1,env=prod" --replicas=3
Flag --generator has been deprecated, has no effect and will be removed in the future.
Flag --replicas has been deprecated, has no effect and will be removed in the future.
pod/foo-prod created
```

To continue along with the Kubernetes Up & Running example use this procedure:

1. Delete the `alpaca-prod` pod

   ```
   kubectl delete pod alpaca-prod
   ```

1. Read a [blog post](https://alexellisuk.medium.com/kubernetes-1-18-broke-kubectl-run-heres-what-to-do-about-it-2a88e5fb389a) learn about the situation

1. Use this bash heredoc

   ```
   some_yaml=$(mktemp)
   cat <<EOF > $some_yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: alpaca-prod
     labels:
       app: alpaca
       ver: 1
       env: prod
   spec:
     replicas: 3
     selector:
       matchLabels:
         app: alpaca
     template:
       metadata:
         labels:
           app: alpaca
       spec:
         containers:
         - name: alpaca-prod
           image: gcr.io/kuar-demo/kuard-amd64:blue
           ports:
           - containerPort: 8080
   EOF
   kubectl apply -f $some_yaml
   error: unable to decode "/var/folders/_r/52tr69g54qvbxtg8fx7548tm0000gq/T/tmp.L5mckdlN": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Name: Labels: ReadString: expects " or n, but found 1, error found in #10 byte of ...|d","ver":1},"name":"|..., bigger context ...|ta":{"labels":{"app":"alpaca","env":"prod","ver":1},"name":"alpaca-prod"},"spec":{"replicas":3,"sele|...
   ```

1. Install a command-line tool to check if the YAML is right

   ```
   brew install yj
   yj < $some_yaml
   {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"name":"alpaca-prod","labels":{"app":"alpaca","ver":1,"env":"prod"}},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"alpaca"}},"template":{"metadata":{"labels":{"app":"alpaca"}},"spec":{"containers":[{"name":"alpaca-prod","image":"gcr.io/kuar-demo/kuard-amd64:blue","ports":[{"containerPort":8080}]}]}}}}
   ```

1. Read the error message more closely and then use this YAML instead

   ```
   some_yaml=$(mktemp)
   cat <<EOF > $some_yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
    name: alpaca-prod
    labels:
      app: alpaca
      ver: "1"
      env: prod
   spec:
    replicas: 3
    selector:
      matchLabels:
        app: alpaca
    template:
      metadata:
        labels:
          app: alpaca
      spec:
        containers:
        - name: alpaca-prod
          image: gcr.io/kuar-demo/kuard-amd64:blue
          ports:
          - containerPort: 8080
   EOF
   kubectl apply -f $some_yaml
   deployment.apps/alpaca-prod created
   ```

   * Labels need to be strings

1. Expose the `alpaca-prod` service

   ```
   kubectl expose deployment alpaca-prod
   ```

1. Continue with the Kubernetes Up & Running example

   ```
   kubectl expose deployment alpaca-prod
   kubectl get services -o wide
   ALPACA_POD=$(kubectl get pods -l app=alpaca \
    -o jsonpath='{.items[0].metadata.name}')
   kubectl port-forward $ALPACA_POD 48858:8080
   ```

1. Connect to the app

   ```
   open http://localhost:48858
   ```

**Pull request merged**
