### PR TITLE
cleanup: log message typo fix

### PR DESCRIPTION
**Pull request by beautytiger**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
correct words in logs, make log message more readable for enduser.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by odinuge — COMMENTED** [review]
Good catch! Thanks for the fix!

/ok-to-test

**Review by divyenpatel — APPROVED** [review]

**Pull request merged**
