### PR TITLE
Simplify Watch() signature in clients.

### PR DESCRIPTION
**Pull request by wojtek-t**
Depends on #17836 and #17823

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by lavalamp** [comment]
cc @caesarxuchao - will affect your client generation :)

**Comment by wojtek-t** [comment]
@caesarxuchao - I'm happy to change your client generator once this is merge (in a separate PR).

**Comment by wojtek-t** [comment]
@krousey - can you please take a look (this is mostly mechanical PR)

**Comment by krousey** [comment]
In the middle of looking now.

**Comment by krousey** [comment]
This seems like a drastic change in the public client interface that would break many users outside of our code base. Would you consider instead keeping the same Watch signature in the unversioned client and populating the options struct with the selector parameters before passing it to RESTClient's Watch?

I agree that this is a cleaner signature and preferred, but is this something we should get right in the versioned clients we're going to generate and just paper it over here?

cc @smarterclayton @liggitt

**Comment by caesarxuchao** [comment]
@wojtek-t Thanks! Or we can update the templates of client generator before we release the tool, it's impractical to update the generator every time there is a change to the client code.

**Comment by wojtek-t** [comment]
>
This seems like a drastic change in the public client interface that would break many users outside of our code base. Would you consider instead keeping the same Watch signature in the unversioned client and populating the options struct with the selector parameters before passing it to RESTClient's Watch?
I agree that this is a cleaner signature and preferred, but is this something we should get right in the versioned clients we're going to generate and just paper it over here?

I don't think it's a drastic change. We already wanted to cleanup our codebase as part of 1.2 and this in my opinion is a step in a good direction.
Also, I don't think that it will break that many clients and fixing it is relatively simple (also note that we are not changing the official k8s API here).

@lavalamp @smarterclayton - I think we need your opinion on that.

**Comment by smarterclayton** [comment]
I think we can live with this - it's a bit more of mechanical change, and i originally pushed for this so I don't mind taking a small hit :)

**Comment by lavalamp** [comment]
I think it's good to think carefully about whether we're breaking clients for a good reason or not, but we *do* have the client in an "unversioned" directory for a reason. In this case I'm happy if @smarterclayton is happy.

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Pull request merged**
