### PR TITLE
cleanUp:check existence using basic method of set

### PR DESCRIPTION
**Pull request by zzr93**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
sets.String struct already has existence check method, we should use it
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by sanposhiho — APPROVED** [review]
/lgtm

**Comment by kerthcet** [comment]
> /milestone v1.24

kubernetes v1.24 is code freezed, you have to wait until the next cycle.

**Pull request merged**
