### PR TITLE
Hack local-up-cluster should enforce cpu limits by default

### PR DESCRIPTION
**Pull request by derekwaynecarr**
CPU CFS quota should be enforced by default.

/cc @vishh

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31165)

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
not enforcing cpu quota by default (like we do in all our other providers), makes debugging kubelet stats issues really tricky ;-)

/cc @kubernetes/rh-cluster-infra @DirectXMan12

**Comment by derekwaynecarr** [comment]
@k8s-bot test this issue https://github.com/kubernetes/kubernetes/issues/31083

**Comment by pmorie** [comment]
@k8s-bot test this issue: #27465

**Comment by dims** [comment]
@k8s-bot test this issue: #IGNORE

**Pull request merged**
