### PR TITLE
Stop overriding the git version in built binaries.

### LINKED ISSUE #5868: git describe returns incorrect version
The latest release is v0.13.2, git describe returns v0.12.0-1145-ged68c8e. How does the master branch relates to the latest release? Is "git describe"'s output intended to be v0.12.0 or is it a bug? This is not the first time inconsistency. Thanks.

### PR DESCRIPTION
**Pull request by j3ffml**
This was resulting in unexpected binary versions; in particular, the kubectl client version did not match the `gitVersion in`pkg/version/base.go` due to new tags not being created on the master branch/ tags being unreachable. In the future we need to be more diligent about creating versions on the master branch and cherrypicking to release branch (Note that 0.13.1 and 0.13.2 were _not_ created on the master branch).

Edit: closes #5868

cc @smarterclayton, @brendandburns, @zmerlynn

### CODE REVIEW

**Comment by jlowdermilk** [comment]
cc @fabioy

**Comment by eparis** [comment]
NAK   people use this when building from src instead of from a git tree

**Comment by jlowdermilk** [comment]
@eparis, won't the built binary be unchanged if building from src with no git tree?

**Comment by eparis** [comment]
I guess what I need is the 'dirty,' more than the version.  What's in the bin is fine for that....

**Comment by eparis** [comment]
isn't the real problem that the tag isn't on a branch?  nothing wrong with this code, its git that's broken?

**Comment by zmerlynn** [comment]
I'm going to continue this discussion in #5868.

**Comment by jlowdermilk** [comment]
I'll let @brendandburns and @zmerlynn chime in, but I think it is confusing if the binary version doesn't match the version in `pkg/version/base.go`. That is the way releases are defined, so the we shouldn't base the binary version on the presence of an annotated tag in the branch. It's useful to get the git commit and tree state, and that info is kept. Example output with this change (rebased to head)

```
# running a binary build with uncommitted local changes
current-context: "jeffmltest_e2e-test-jeffml"
Running: cluster/../cluster/gce/../../cluster/../_output/local/bin/linux/amd64/kubectl version
Client Version: version.Info{Major:"0", Minor:"13.0+", GitVersion:"v0.13.0-dev", GitCommit:"ceffa489d018b89d5b913cb2a4b723dbcdb246fd", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"12+", GitVersion:"v0.12.0-979-g6918a4d32ed200", GitCommit:"6918a4d32ed200e6e5e4715fcf049c32d86c5488", GitTreeState:"clean"}

# running a binary build with no local changes
current-context: "jeffmltest_e2e-test-jeffml"
Running: cluster/../cluster/gce/../../cluster/../_output/local/bin/linux/amd64/kubectl version
Client Version: version.Info{Major:"0", Minor:"13.0+", GitVersion:"v0.13.0-dev", GitCommit:"ceffa489d018b89d5b913cb2a4b723dbcdb246fd", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"12+", GitVersion:"v0.12.0-979-g6918a4d32ed200", GitCommit:"6918a4d32ed200e6e5e4715fcf049c32d86c5488", GitTreeState:"clean"}

```

**Comment by jlowdermilk** [comment]
Ping @brendandburns, @zmerlynn, @eparis. #5868 was closed, but it's not clear to me whether we want to merge or abandon this PR.

**Comment by eparis** [comment]
Trying to decide how I feel.  Going from 
```
Client Version: version.Info{Major:"0", Minor:"12+", GitVersion:"v0.12.0-1041-gef758881d108bb", GitCommit:"ef758881d108bb53a128126c503689104d17f477", GitTreeState:"clean"}
```

To:
```
Client Version: version.Info{Major:"0", Minor:"12+", GitVersion:"v0.12.0-dev", GitCommit:"ef758881d108bb53a128126c503689104d17f477", GitTreeState:"clean"}
```

It's a change, but I guess not an important one.  I'm not sure what the point of "gitVersion" is at all, since it has nothing at all to do with git...

**Comment by eparis** [comment]
I guess I'm ok either way, but if we are going to back stuff out, why not just drop "gitVersion" from all of the code entirely?

**Comment by zmerlynn** [comment]
We definitely want the patch version in there if we're going to drop the
gitVersion, and adding "Patch" would be pretty big change. Maybe we should
just throw it into the breaking change day. :)

**Comment by eparis** [comment]
What do you mean by "patch version"  you still have gitCommit...

**Comment by zmerlynn** [comment]
Right now the only fields are "Major" (0), Minor ("12+"). That's not enough
to express the semantic version "0.13.2". The GitVersion is the only place
the entire semantic version exists today.

**Comment by eparis** [comment]
$ git checkout origin/master:
major (0) minor (13.0+) gitVersion(v0.13.0-dev)

$ git checkout v0.13.2:
major(0)  minor(13.2)   gitVersion(v0.13.2)

I'm not exactly sure what you are saying it missing in the 0.13.2 semantic....

The tagging of things is still totally screwed up, but that's unrelated....
$ git describe --tags --abbrev=14 origin/master
v0.13.1-dev-652-ge4fc45c26fdecd

**Comment by zmerlynn** [comment]
You seem to be arguing from a position of including `gitVersion` after having said:

> I guess I'm ok either way, but if we are going to back stuff out, why not just drop "gitVersion" from all of the code entirely?

... which is arguing the opposite.

**Comment by eparis** [comment]
I'm saying that everything in gitVersion is in gitMajor, gitMinor, and gitCommit.  And thus gitVersion is unnecessary.

(unrelated I'm saying that tags/git describe are still messed up)

**Comment by zmerlynn** [comment]
No, gitVersion is Major, Minor, Patch, as in [semantic versioning](http://semver.org/). It also happens to include enough hash for a git describe. I really need that Patch level as well, so gitVersion is *not* unnecessary, unless you include Patch elsewhere. Where are you putting the "2" of 0.13.2? You still haven't answered that part.

**Comment by eparis** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/version/base.go#L39

**Comment by zmerlynn** [comment]
Also, what's your objecting to the current tag?

**Comment by eparis** [comment]
or if you meant specifically the "2"
https://github.com/GoogleCloudPlatform/kubernetes/blob/release-0.13/pkg/version/base.go#L39

**Comment by zmerlynn** [comment]
Bleh.

**Comment by eparis** [comment]
I am saying that I believe gitVersion is entirely unnecessary as it is currently contained in the major/minor/gitCommit fields.  Releases also seem to screw up tagging often enough that git describe isn't accurate and thus isn't great for generating gitVersion anyway.

(The problem with git describe right now is that it says master is 0.13.1 + 652 commits.  It should either say it is 0.13.0 + some number of commits, or it should say it is 0.13.2 + some number of commits.  Since all commits from 0.13.2 are in master.  I don't care which we call 'correct' but what it gives right now is wrong)

**Comment by zmerlynn** [comment]
Sorry, I actually totally forgot that the `.0` version looked different than the `.2` version. I've been staring at the .0 versions too long.

**Comment by zmerlynn** [comment]
Actually, the git describe is as correct as I could make it, believe it or not. `0.13.1-dev` is the branch point for `v0.13.1`, so that git describe of "0.13.1 + 652" pretty much nails it. I couldn't even fix the tag v0.13.0 because it was so badly broken.

**Comment by zmerlynn** [comment]
(There's no relevant tag for `v0.13.2` on master because it doesn't make sense.)

**Comment by jlowdermilk** [comment]
Oops. Accidentally garbage collected the pr branch. Reopened as #6065

**Comment by eparis** [comment]
What is 'correct'.  In 2 months should we call master:

0.14.0 + 1000 commits
  or
0.14.3 + 997 commits

**Comment by zmerlynn** [comment]
Okay, I'm fine with this change. Should we just stop tagging in git as
well? The use of last-good-e2e-run means the tags are always time traveling
(which is why there's -dev tag, even though the actual bump to 0.13.1 is a
bit later in the log.)

**Comment by zmerlynn** [comment]
We should call master a git hash and be done :p

**Comment by eparis** [comment]
last-good-e2e-run must be some google internal thing, I don't see that name in the repo.....  Is that what's breaking things constantly?  This all seems like your internal release process is broken...

It seems we should be doing:

git checkout -b possible-v-14 origin/master
edit base.go to set to 0.14;
git commit;
edit base.go to set to 0.14+;
git commit;
run e2e on that middle commit;
if it works
   tag the middle commit as v0.14.0
if it fails
   delete your possible-v-14 branch and goto start;
merge possible-v-14 into master on github
git checkout -b v0.14 v0.14.0
edit base.go to set to 0.14.0+
push new "v0.14" branch to github.

What do we do differently?

**Comment by zmerlynn** [comment]
"last-good-e2e-run" was my shorthand for "picking a validated git hash from our Jenkins server". In other words, instead of the *very expensive* process of the middle step, we essentially elevate a known good build. For `v0.x.0` with known-good-hash from Jenkins, we did:
```
git checkout -b release-0.x known-good-hash
./build/mark-new-version.sh v0.x.0
git checkout v0.x.0
make clean; make release # To build the binaries that actually have the new version number
git push https://github.com/GoogleCloudPlatform/kubernetes tags/v0.x
git push https://github.com/GoogleCloudPlatform/kubernetes release-0.x
# merge the resulting PR, the version numbers appear a little later in the stream
# push binaries up
# change github page
```

Unfortunately, that doesn't quite work because the `v0.x` tag create by `mark-new-version.sh` is effectively created on a release branch and not reachable from HEAD. And so it requires the introduction of a branch point tag so that `git describe` doesn't freak out entirely.

FWIW, before you consider this broken, please consider that we all have quite busy jobs outside of the release process and being able to escalate a known good build is quite advantageous versus squatting on somewhat flakey e2e runs.

**Pull request closed without merging**
