### PR TITLE
[Federation][init-03] Print the federation API server address on success.

### PR DESCRIPTION
**Pull request by madhusudancs**
Please review only the last commit here. This is based on PR #35859 which will be reviewed independently.

Design Doc: PR #34484

cc @kubernetes/sig-cluster-federation @nikhiljindal

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35860)

### CODE REVIEW

**Comment by quinton-hoole** [comment]
LGTM, thanks @madhusudancs

**Comment by madhusudancs** [comment]
@k8s-bot test this

**Comment by madhusudancs** [comment]
@k8s-bot cvm gke e2e test this

**Comment by madhusudancs** [comment]
@k8s-bot gci gce e2e test this

**Comment by madhusudancs** [comment]
@k8s-bot gci gce e2e test this

**Pull request merged**
