### PR TITLE
Replace x.Sub(time.Now()) with time.Until(x)

### PR DESCRIPTION
**Pull request by chuntaochen**
What type of PR is this?
/kind cleanup

 What this PR does / why we need it:
https://staticcheck.io/docs/checks#S1024

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?

```release-note
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by rikatz** [comment]
I have no strong opinion if this is really something we want to change.

I understand that time.Until is better readable, but does this justify a code change?

**Comment by caesarxuchao** [comment]
`time.Until` is slightly more readable to me.

/lgtm
/approve

**Comment by GreenApple10** [comment]
/recc @caesarxuchao
Reverted the modification of other areas but kubectl.
Thanks!

**Comment by caesarxuchao** [comment]
still lgtm.

/lgtm

/assign @seans3 for approval

**Pull request closed without merging**
