### PR TITLE
Install protoc into kube-cross Docker image

### PR DESCRIPTION
**Pull request by smarterclayton**
Reruns #19359 but forces g++ to be installed now.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Forces g++, but I still want to be sure that something isn't broken in the build env and using the wrong image.

**Comment by zmerlynn** [comment]
I'm actually a little confused on why the PR builder didn't catch the last one.

**Comment by zmerlynn** [comment]
This `apt-get install` seems to be a no-op for me on both `golang:1.4.2` (which I think Jenkins has installed) and `golang:1.4`:

```
zml@zml:~/kubernetes$ docker images 
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
zml@zml:~/kubernetes$ docker run -it golang:1.4.2 /bin/bash
Unable to find image 'golang:1.4.2' locally
1.4.2: Pulling from library/golang
0b12df66f608: Pull complete 
b9c1c5f483f7: Pull complete 
afc814718fc0: Pull complete 
123bb2b94ece: Pull complete 
96078bbbd113: Pull complete 
febf15f5ad77: Pull complete 
d8ce0e768827: Pull complete 
6e9498732718: Pull complete 
37b4b0311101: Pull complete 
1c74a5702253: Pull complete 
d2c7a6b2c32c: Pull complete 
754132ccd1cd: Pull complete 
8188850ff5a4: Pull complete 
d34fc4760dd5: Pull complete 
Digest: sha256:a661a9a57b864de1d08b350c8dfc944b72daea8fb4292c63bbbf534ba489474b
Status: Downloaded newer image for golang:1.4.2
root@bd5d17444b0c:/go# apt-get install -y g++
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++ is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@bd5d17444b0c:/go# 
zml@zml:~/kubernetes$ docker rmi -f $(docker images -q)
Untagged: golang:1.4.2
Deleted: d34fc4760dd53ab4b12f01032afb18f1a8004cb3c1939da492753761894cc26e
Deleted: 8188850ff5a485ac346ff026325cc47c17ee996b8b546cf81ef796c1752e4098
Deleted: 754132ccd1cd6296a0a8a2986eb1d9d73ea0eafe51eb66080969c90a7bbcb70e
Deleted: d2c7a6b2c32c4704fbdfcd06b455d00ece83ec6c2415b03668933e610216cb1e
Deleted: 1c74a57022531837c57c1603a0135f075949b82447bcae26d3706862613a87fa
Deleted: 37b4b03111016cba50bb0bc68976d7675cd04dba5e5fe87bfc91ac4b5d9ca8ce
Deleted: 6e9498732718b5df9d05864becb5337c4136466fb52a39441ebc4ece693fb8aa
Deleted: d8ce0e7688273179489fdbb425695a40fe965807d3c56ee6e9a1b6e96a8dacdf
Deleted: febf15f5ad77f3085a6e7ba51c78bd3010fe6c7dee8b8f48892a0543570d0923
Deleted: 96078bbbd1133a7af654b85a2219273eeac3a85e4e60e45b9fdf4fd048ad8106
Deleted: 123bb2b94eceaec275718da18e7f5bcd992e699ba62142754ee7b0826b6cb135
Deleted: afc814718fc08e54a3ee3220fc52ea30301ca308281154192178fffe84049de8
Deleted: b9c1c5f483f79322058cdecab1869252376615997cc3c5d51dba68467f1f242a
Deleted: 0b12df66f6087b113293cf5b2a3c64728fb681078293e94e822c2f87d9911b07
zml@zml:~/kubernetes$ docker images 
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
zml@zml:~/kubernetes$ docker run -it golang:1.4 /bin/bash
Unable to find image 'golang:1.4' locally
1.4: Pulling from library/golang
523ef1d23f22: Pull complete 
140f9bdfeb97: Pull complete 
5c63804eac90: Pull complete 
ce2b29af7753: Pull complete 
1830aadefe84: Pull complete 
e1169a2ffea9: Pull complete 
76d74181bce3: Pull complete 
d95967a4998b: Pull complete 
0d921c61cc4e: Pull complete 
e17851511e34: Pull complete 
b2d2a5ff14e9: Pull complete 
55e6d2ea858a: Pull complete 
0d352b2187d1: Pull complete 
36a45c1746c9: Pull complete 
Digest: sha256:c0d9c308e2c0737c572b5160e76b4c46e78c21ce7011c12df1d68dfb9029516d
Status: Downloaded newer image for golang:1.4
root@a14170521a00:/go# apt-get install -y g++
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++ is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@a14170521a00:/go# 
```

Am I missing something? We're both probably missing something from what happened on Jenkins, I'd guess.

**Comment by zmerlynn** [comment]
Oh, what I'm missing is that the Jenkins image is an even older version of `golang:1.4.2`, blech.

**Comment by zmerlynn** [comment]
```
zml@jenkins-master:~$ sudo docker run -it golang:1.4 /bin/bash
root@3ce797cd7c5f:/go# g++
bash: g++: command not found
```

**Comment by zmerlynn** [comment]
I did a docker pull to reup the image. cc @ixdy, we're going to need a better way to handle that in the future.

Stamping this version.

**Comment by zmerlynn** [comment]
I'm guessing the PR Builder Jenkins has a better `golang:1.4` image, to answer my question from earlier. :) (Sigh.)

**Comment by smarterclayton** [comment]
I love release engineering!  All the best problems. :)

**Comment by ixdy** [comment]
How do docker image dependencies even work?

cc @david-mcmahon

**Comment by smarterclayton** [comment]
If the image is on the box, docker build won't pull it automatically.

On Jan 15, 2016, at 3:15 PM, Jeff Grafton <notifications@github.com> wrote:

How do docker image dependencies even work?

cc @david-mcmahon <https://github.com/david-mcmahon>

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/19703#issuecomment-172077968>
.

**Comment by luxas** [comment]
Maybe you should specify full versions? E. g. `golang:1.4.2` instead of `golang:1.4`
That maybe fixes the problem.

However, soon `golang` will be upgraded to `1.5.3` anyway...

**Comment by david-mcmahon** [comment]
@ixdy I'm not yet familiar (enough) with docker dependencies to answer your question.

**Comment by zmerlynn** [comment]
@luxas: `golang:1.4.2` was effectively the image that was sitting on Jenkins, so that wouldn't've helped unless we had actually updated to `golang:1.4.3` along the way. See https://github.com/kubernetes/kubernetes/pull/19703#issuecomment-172045484 and https://github.com/kubernetes/kubernetes/pull/19703#issuecomment-172044767 where you can see what a stale `golang:1.4.2` on Jenkins looks like.

@ixdy: As @smarterclayton said, if the tag is present on the box at all, `docker` just won't repull it. In this case, `golang:1.4` has been sitting on Jenkins for a *long* time, long enough that it's not only effectively a `golang:1.4.2` image, but an old one that behaves differently than the current image.

@david-mcmahon: I think @smarterclayton was just giving you a heads up that this is an issue, not for help resolving the question.

I used to have something in the `hack/jenkins/build` script that would do a `docker rmi` to purge all the old images every build cycle, but I took it out because it seemed too paranoid. I guess it wasn't. We can throw it back in, or stick something in to do it once a day...

**Comment by ixdy** [comment]
I wonder if this is the root cause of #17524. If so, we should expect the next scalability run (4208, not yet started) to fail...

**Comment by zmerlynn** [comment]
@ixdy: Interesting theory. Possibly, and if so it would suck. I basically just bumped our build/e2e up to `golang:1.4.3`, and it's been languishing at `golang:1.4.2`.

**Comment by smarterclayton** [comment]
ok to test

**Comment by smarterclayton** [comment]
ok to test

**Comment by smarterclayton** [comment]
@k8s-bot unit test this

**Pull request merged**
