### PR TITLE
Correct wrong syntax

### PR DESCRIPTION
**Pull request by zhoumingcheng**
Signed-off-by: zhoumingcheng <zhoumingcheng@beyondcent.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
For the overall rigour of the code
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Thank you！
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yxxhero** [comment]
@zhoumingcheng Hello, the change of this PR is too small. Can you find similar problems as much as possible and concentrate on one PR. Thanks very much.

**Comment by zhoumingcheng** [comment]
> @zhoumingcheng Hello, the change of this PR is too small. Can you find similar problems as much as possible and concentrate on one PR. Thanks very much.

Thanks for the suggestion, I have corrected the syntax errors I could find in the staging directory.

**Comment by zhoumingcheng** [comment]
> @zhoumingcheng Hello, the change of this PR is too small. Can you find similar problems as much as possible and concentrate on one PR. Thanks very much.

Thanks for the suggestion, I've changed the syntax errors I could find in that directory.

**Pull request closed without merging**
