### PR TITLE
Migrate the leader election to use v1beta1 Events

### LINKED ISSUE #82846: migrate the leader election to use v1beta1 Events
the leader election code should be emitting events against the v1beta1 Events API. This change also concerns any kubernetes component (such as kube-scheduler or the controller-manager) that uses the `leaderelection` package.

Part of #76674

/kind feature
/sig scalability
/sig instrumentation
/priority important-soon

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/kind feature
/sig scalability
/sig instrumentation

**What this PR does / why we need it**:

this migrate the leader election to the v1beta1 Event API

**Which issue(s) this PR fixes**:

Fixes #82846

**Special notes for your reviewer**:

/assign @yastij
/priority important-soon

**Does this PR introduce a user-facing change?**:

```release-note
Migrate leader election to use v1beta1 Event API. Action required: any tool that relies on leader election needs to use v1beta1 Event API
```

### CODE REVIEW

**Review by yastij — COMMENTED** [review]
I did a first pass on the structure. I'll take another look on the Events later

**Comment by liggitt** [comment]
/hold
for https://github.com/kubernetes/kubernetes/issues/76674#issuecomment-534101819

**Comment by yastij** [comment]
@danielqsj - let me know when you can address the comments and rebase to do a final pass

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/82861#issuecomment-534102523 still applies, FYI... we shouldn't switch components to require using a beta API in favor of a v1 API

**Comment by yastij** [comment]
@liggitt - with the fallback we can still the v1 API. But I'm fine with promoting then switching too

**Comment by danielqsj** [comment]
hi @yastij, I will update it soon.

**Pull request closed without merging**
