### PR TITLE
Bump klog to v2.9.0

### PR DESCRIPTION
**Pull request by ehashman**
#### What type of PR is this?

/kind bug cleanup
/priority important soon

#### What this PR does / why we need it:

Fixes broken patch status lines in component logs.

#### Which issue(s) this PR fixes:

Address https://github.com/kubernetes/kubernetes/issues/101714 on 1.21 branch.

#### Does this PR introduce a user-facing change?

```release-note
fixes regression in 1.21 in log displaying patches as byte arrays; update klog v2.9.0
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ehashman** [comment]
/priority important-soon
rationale: these log lines are unusable.

HEAD:

```
I1001 10:53:43.759524  976667 status_manager.go:621] "Patch status for pod" pod="kube-system/coredns-755cd654d4-fqk2t" patch="{\"metadata\":{\"uid\":\"1167e1b4-a5c7-4012-884e-ed1776852bb7\"},
\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"Initialized\"},{\"type\":\"Ready\"},{\"type\":\"ContainersReady\"},{\"type\":\"PodScheduled\"}],\"conditions\":[{\"lastProbeTime\":nul
l,\"lastTransitionTime\":\"2021-10-01T17:53:43Z\",\"status\":\"True\",\"type\":\"Initialized\"},{\"lastProbeTime\":null,\"lastTransitionTime\":\"2021-10-01T17:53:43Z\",\"message\":\"container
s with unready status: [coredns]\",\"reason\":\"ContainersNotReady\",\"status\":\"False\",\"type\":\"Ready\"},{\"lastProbeTime\":null,\"lastTransitionTime\":\"2021-10-01T17:53:43Z\",\"message
\":\"containers with unready status: [coredns]\",\"reason\":\"ContainersNotReady\",\"status\":\"False\",\"type\":\"ContainersReady\"}],\"containerStatuses\":[{\"image\":\"k8s.gcr.io/coredns/c
oredns:v1.8.0\",\"imageID\":\"\",\"lastState\":{},\"name\":\"coredns\",\"ready\":false,\"restartCount\":0,\"started\":false,\"state\":{\"waiting\":{\"reason\":\"ContainerCreating\"}}}],\"host
IP\":\"127.0.0.1\",\"startTime\":\"2021-10-01T17:53:43Z\"}}"
```

1.21: 

```
I1001 11:28:00.431923 1032046 status_manager.go:586] "Patch status for pod" pod="kube-system/kube-dns-5bc69b84c5-hjgxw" patchBytes=[123 34 109 101 116 97 100 97 116 97 34 58 123 34 117 105 100 34 58 34 101 98 49 97 55 99 102 101 45 56 100 101 55 45 52 51 98 56 45 98 54 100 98 45 51 50 53 52 49 51 53 101 52 48 50 102 34 125 44 34 115 116 97 116 117 115 34 58 123 34 36 115 101 116 69 108 101 109 101 110 116 79 114 100 101 114 47 99 111 110 100 105 116 105 111 110 115 34 58 91 123 34 116 121 112 101 34 58 34 73 110 105 116 105 97 108 105 122 101 100 34 125 44 123 34 116 121 112 101 34 58 34 82 101 97 100 121 34 125 44 123 34 116 121 112 101 34 58 34 67 111 110 116 97 105 110 101 114 115 82 101 97 100 121 34 125 44 123 34 116 121 112 101 34 58 34 80 111 100 83 99 104 101 100 117 108 101 100 34 125 93 44 34 99 111 110 100 105 116 105 111 110 115 34 58 91 123 34 108 97 115 116 80 114 111 98 101 84 105 109 101 34 58 110 117 108 108 44 34 108 97 115 116 84 114 97 110 115 105 116 105 111 110 84 105 109 101 34 58 34 50 48 50 49 45 49 48 45 48 49 84 49 56 58 50 56 58 48 48 90 34 44 34 115 116 97 116 117 115 34 58 34 84 114 117 101 34 44 34 116 121 112 101 34 58 34 73 110 105 116 105 97 108 105 122 101 ... ]
```

**Comment by dims** [comment]
/assign @liggitt 

@ehashman not quite sure that this is a very critical bug that needs fixing?

**Comment by ehashman** [comment]
> @ehashman not quite sure that this is a very critical bug that needs fixing?

The affected kubelet log lines (and anything else that writes byte arrays) are currently unusable for debugging at v=4. Ran into this when trying to fix/repro #105358.

The effective diff is quite small: https://github.com/kubernetes/kubernetes/pull/105407/files#diff-3b6e1d099424e0a21a123b4b97e4fab655c3b3f82f1ef3a3b8179226377c5603

**Comment by liggitt** [comment]
/retest

I tend to agree it is not severe, but also seems very low-risk and makes the 1.21 branch easier to support... I'll hold off until monday to tag, but would tend to be in favor of this

Was this issue introduced in 1.21?

**Comment by ehashman** [comment]
I believe the issue was introduced with structured logging. The kubelet is the only component fully migrated to structured logging, and that happened in 1.21. It's possible there were other calls that were migrated piecemeal that could be affected, but if so I don't know where they are. This would fix it.

**Comment by liggitt** [comment]
ack

/approve
/lgtm

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
