### PR TITLE
AWS: use CoreOS for nodes

### PR DESCRIPTION
**Pull request by bakins**
@justinsb 

Adds ability to run CoreOS for the nodes.   Currently is still just docker for the container runtime.

A bit of a WIP, but it all works (for me at least). The OS split is a bit of a kludge, TBH.

Based on the GCE work.

### CODE REVIEW

**Comment by justinsb** [comment]
I think this is a good patch (although why can't I have a CoreOS master?  And why can't I have rkt?)

I am concerned though that we're really hitting the maintenance limits of shell scripting by duplicating the create-minion function.  Is the same thing needed with GCE?  (What is/was the PR there?)

All in all, +1, because CoreOS & rkt support is important, but I really hope we can rethink these scripts...

**Comment by bakins** [comment]
The GCE work was done mostly in #7445 - uses the split Debian vs CoreOS helpers that I based mine on.  rkt support should be fairly straightforward, but I wanted to get this out for discussion.  I think some of the code in Ubuntu/CoreOS utils can be factored out.

I'm in agreement that the bash scripting needs to be reworked.

Anything in particular you think we should do before considering merging this?

**Comment by bakins** [comment]
Also, CoreOS master is a bit more thorny.  I'd need to untangle the salt stuff to do it on CoreOS in a more "normal" way.

**Comment by justinsb** [comment]
I was joking about CoreOS master & rkt - sorry!  I know we'll get there, I just want it yesterday :-)

This LGTM.  (I would love one day to eliminate the bash scripts & salt, and I think this gets us closer.)

**Comment by iterion** [comment]
+1 as well. It would be great to have CoreOS everywhere.

Are there any major blockers to a CoreOS master on AWS?

**Comment by bakins** [comment]
@justinsb ;)  I tweaked it a bit so you can choose container runtime.  Done same as GCE code provider. (Copying around code from provider to provider bugs me as well.)

@iterion Currently salt is used to set up master.  Assumptions are made in the e2e about how the master is set up, and someone (me?) needs to "port" that from salt into something else for CoreOS.  Obviously, you can run CoreOS as a master - see that various guides - but just need to spend the time to do it in the "kube-up" form.

**Comment by dchen1107** [comment]
@justinsb I have a pending master.yaml for CoreOS master. It requires rkt integration with port supports. Once that is done, I will clean up this to have master node running coreos and rkt. :-)

**Comment by bakins** [comment]
@dchen1107 nice!

I'm rebasing and cleaning this up a bit. I'll squash and push in a bit.

**Comment by justinsb** [comment]
I'm happy for this to merge whenever people want.  When it does, we'll have to double check that we haven't lost any concurrent changes to the AWS scripts.  But, as it is "opt-in", and won't/shouldn't break AWS/Ubuntu, I say we merge it whenever makes sense.

**Comment by bakins** [comment]
@justinsb let me do a final rebase and test run of both CoreOS and Ubuntu, just to be sure.

**Comment by bakins** [comment]
@justinsb tested on CoreOS stable. Also tested Ubuntu and it still works.

**Comment by iterion** [comment]
@bakins This looks good, excited to see it get merged!

**Comment by dchen1107** [comment]
LGTM.

**Comment by iterion** [comment]
Any blockers to merge? Would love to see this merged so I can test it out.

**Comment by dchen1107** [comment]
We are temporarily on merge freeze to solve e2e test breakage.

**Comment by iterion** [comment]
Ahh, I was not aware! Sorry to be a bother!

**Pull request merged**
