### PR TITLE
Automated cherry pick of #103895: Update to using apiserver-network-proxy v1.22

### PR DESCRIPTION
**Pull request by cheftako**
Cherry pick of #103895 on release-1.20.

#103895: Update to using apiserver-network-proxy v1.22

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by liggitt** [comment]
needs `hack/update-vendor.sh` rerun

**Comment by puerco** [comment]
Thanks @cheftako !
/lgtm

**Pull request merged**
