### PR TITLE
bump(github.com/elazarl/go-bindata-assetfs): 3dcc96556217539f50599357fb481ac0dc7439b9

### PR DESCRIPTION
**Pull request by liggitt**
Syncs versions with OpenShift, picks up https://github.com/elazarl/go-bindata-assetfs/pull/19

### CODE REVIEW

**Comment by deads2k** [comment]
I'm all for bumping, but shouldn't there be some go files generated by this new level?

**Comment by liggitt** [comment]
Assetfs just serves, bindata generates

**Comment by deads2k** [comment]
lgtm, though you should check out your jenkins failures.

**Comment by liggitt** [comment]
Weird, getting travis failures on verifying godeps for things I didn't change:
```
hack/verify-godeps.sh master

Starting to download all kubernetes godeps. This takes a while

package github.com/prometheus/client_golang/extraction

	imports github.com/prometheus/client_golang/extraction

	imports github.com/prometheus/client_golang/extraction: cannot find package "github.com/prometheus/client_golang/extraction" in any of:

	/home/travis/.gimme/versions/go1.4.linux.amd64/src/github.com/prometheus/client_golang/extraction (from $GOROOT)

	/tmp/gopath.BgKGNC/src/github.com/prometheus/client_golang/extraction (from $GOPATH)

godep: restore: exit status 1

package github.com/prometheus/client_golang/model

	imports github.com/prometheus/client_golang/model

	imports github.com/prometheus/client_golang/model: cannot find package "github.com/prometheus/client_golang/model" in any of:

	/home/travis/.gimme/versions/go1.4.linux.amd64/src/github.com/prometheus/client_golang/model (from $GOROOT)

	/tmp/gopath.BgKGNC/src/github.com/prometheus/client_golang/model (from $GOPATH)

godep: restore: exit status 1

!!! Error in hack/verify-godeps.sh:46

  '"${GODEP}" restore' exited with status 1

Call stack:

  1: hack/verify-godeps.sh:46 main(...)
```

**Comment by deads2k** [comment]
> Weird, getting travis failures on verifying godeps for things I didn't change:

@liggitt take a look here: https://github.com/kubernetes/kubernetes/pull/14179.  I didn't even know they did that.

**Comment by liggitt** [comment]
e2e error:
```
ERROR: (gcloud.compute.networks.create) Some requests did not succeed:
 - The resource 'projects/kubernetes-jenkins-pull/global/networks/pull-e2e-parallel-4' already exists
```
closing/reopening to kick

**Comment by deads2k** [comment]
green!

lgtm

**Pull request merged**
