### PR TITLE
Add 'ep' as a shortcut for 'endpoints'

### PR DESCRIPTION
**Pull request by thockin**

### CODE REVIEW

**Comment by thockin** [comment]
Very minor UX point, could wait until after 1.0

**Comment by nikhiljindal** [comment]
cc @bgrant0607 @jlowdermilk as potential reviewers.
@bgrant0607 to triage for 1.0 as well.

**Comment by bgrant0607** [comment]
LGTM

**Comment by jlowdermilk** [comment]
lgtm

**Comment by bprashanth** [comment]
Will merge during work hours

**Pull request merged**
