### PR TITLE
Code style update

### PR DESCRIPTION
**Pull request by LexCC**
**What type of PR is this?**
> /kind cleanup

**What this PR does / why we need it**:
Fix golint: 

- ``if block ends with a return statement, so drop this else and outdent its block``.
- ``rename underscore variable``

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Review by dcbw — APPROVED** [review]
/lgtm

**Comment by JieJhih** [comment]
ping @dcbw @thockin 
for approval.

**Comment by thockin** [comment]
Thanks!

/approve

**Pull request merged**
