### PR TITLE
start-kubemark.sh: clean up the shell script.

### PR DESCRIPTION
**Pull request by ipuustin**
**What this PR does / why we need it**:

I took a look at `start-kubemark.sh` to see if there is something wrong with the script itself which might be related to https://github.com/kubernetes/kubernetes/issues/66475 (answer: I didn't see any obvious error in the script logic). However, the file had some small problems which were identified by `shellcheck`, and I fixed those while at it.

1. Add double quotes around variables which are expanded. This is done even on those variables which probably won't have spaces, globs or similar (such as `$MASTER_IP`) to stay consistent.

2. In one place, change old-type backtick command substitution to `$(...)` to stay consistent through the file.

3. Remove useless echo commands in expressions: `FOO=$(echo "$bar")` becomes `FOO="$bar"`.

4. In a few places, remove double quotes around variables when an expression is already inside them: the variables would have been effectively unquoted.

The last change in the patch changes the printing a bit -- the old way did not print whitespace correctly due to inner echo missing the quotes around it. The change should fix the printout:

    -      echo $(echo "${pods}" | grep -v "Running")
    +      echo "${pods}" | grep -v Running

The PR is tested only in parts, because my local setup doesn't apparently support running kubemark. I would appreciate if someone who does run `start-kubemark.sh` regularly would try out the changes.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ipuustin** [comment]
Ping @shyamjvs @wojtek-t !

**Comment by wojtek-t** [comment]
I'm not bash expert, but if that works, I agree it looks better.

/lgtm

**Pull request merged**
