### PR TITLE
promote complex daemonset test out of flaky

### PR DESCRIPTION
**Pull request by mikedanese**

### CODE REVIEW

**Comment by gmarek** [comment]
Reassigning to @fgrzadkowski - today's build cop.

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by gmarek** [comment]
@k8s-bot unit test this

**Comment by fgrzadkowski** [comment]
@k8s-bot unit test this please

**Comment by fgrzadkowski** [comment]
@k8s-bot unit test this please

**Pull request merged**
