### PR TITLE
Fix kubelet help typo

### PR DESCRIPTION
**Pull request by ncdc**
Fix double percent (%%) typo for image-gc-high-threshold and
image-gc-low-threshold help text.

Before the fix:

```
vagrant@localhost:~/go/src/k8s.io/kubernetes (fix-typo) kubelet -h 2>&1 | grep '%'
      --image-gc-high-threshold=90: The percent of disk usage after which image garbage collection is always run. Default: 90%%
      --image-gc-low-threshold=80: The percent of disk usage before which image garbage collection is never run. Lowest disk usage to garbage collect to. Default: 80%%
```

After the fix:

```
vagrant@localhost:~/go/src/k8s.io/kubernetes (fix-typo) kubelet -h 2>&1 | grep '%'
      --image-gc-high-threshold=90: The percent of disk usage after which image garbage collection is always run. Default: 90%
      --image-gc-low-threshold=80: The percent of disk usage before which image garbage collection is never run. Lowest disk usage to garbage collect to. Default: 80%
```

### CODE REVIEW

**Comment by yujuhong** [comment]
lgtm. Thanks for the fix.

**Comment by ncdc** [comment]
@yujuhong I forgot to update the generated docs. I just force pushed an updated commit w/that change as well.

**Comment by yujuhong** [comment]
Re-applied the lgtm label to prevent @k8s-bot from complaining. lgtm.

**Comment by ncdc** [comment]
e2e flake, fwiw:

```
Summarizing 1 Failure:

[Fail] Probing container [It] with readiness probe should not be ready before initial delay and never restart [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:59

```

**Comment by ncdc** [comment]
@k8s-bot test this

**Comment by lavalamp** [comment]
@k8s-bot unit test this please

**Pull request merged**
