### PR TITLE
add LocalNode test tag definition

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@smarterclayton ptal

**Comment by smarterclayton** [comment]
@kubernetes/sig-testing I suggested this because we have a few examples of tests that can only be run with host access - just wanted to establish a convention for marking them.

**Comment by smarterclayton** [comment]
This isn't to encourage its use (especially in conformance), but to identify those that fall in that space.

**Comment by ixdy** [comment]
Can you point to some examples of tests? This smells like an antipattern for test-writing...

**Comment by ihmccreery** [comment]
:-1: I'd really like to keep the number of tags we have to as small a number as possible.  Could you explore an option similar to `skipIfProviderIs`?

**Comment by smarterclayton** [comment]
We don't have providers as such - we'll just use it on our side.  Ben,
you can go ahead and close this.

**Pull request closed without merging**
