### PR TITLE
kube-apiserver: wait for synched caches before /healthz returns OK

### LINKED ISSUE #45786: /healthz of the apiserver should return ok first when ready to serve requests
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Kubernetes version** (use `kubectl version`):

v1.6.3 (and HEAD I think)

**What happened**:

The apiserver returns `ok` on `/healthz` before it's ready to serve requests correctly.

Example of the race condition when doing self-hosting with kubeadm:
```
[self-hosted] Found 1 self-hosted-kube-apiserver pods
[self-hosted] Pod self-hosted-kube-apiserver-2d146 status: Pending
[self-hosted] Found 1 self-hosted-kube-apiserver pods
[self-hosted] Pod self-hosted-kube-apiserver-2d146 status: Running
[apiclient] All control plane components are healthy after 4.550770 seconds
[self-hosted] self-hosted kube-apiserver ready after 13.904822 seconds
failed to create self-hosted "kube-scheduler" deployment [deployments.extensions "self-hosted-kube-scheduler" is forbidden: not yet ready to handle request]
```

**What you expected to happen**:

The api server should actually be ready when `/healthz` is `ok`

**How to reproduce it** (as minimally and precisely as possible):

* Install kubeadm v1.6.3
* Create this config file:
   ```yaml
   kind: MasterConfiguration
   apiVersion: kubeadm.k8s.io/v1alpha1
   selfHosted: true
   ```
* Run kubeadm: `kubeadm init --config kubeadm.yaml`

cc @kubernetes/sig-cluster-lifecycle-misc 

Is this a sig-apimachinery bug? @kubernetes/sig-api-machinery-bugs

### PR DESCRIPTION
**Pull request by sttts**
(Might) fix https://github.com/kubernetes/kubernetes/issues/45786.

### CODE REVIEW

**Comment by luxas** [comment]
@k8s-bot pull-kubernetes-kubemark-e2e-gce test this

**Comment by luxas** [comment]
Thanks @sttts! 
I'll try to cherrypick this into the release-1.6 branch locally and see if it fixes the issue right away :+1:

**Comment by deads2k** [comment]
This would stop the API server from reporting healthy for the sake of a few endpoints waiting on caches for admission. Are you sure you want to do this?

**Comment by luxas** [comment]
@deads2k Where do you think `deployments.extensions "self-hosted-kube-scheduler" is forbidden: not yet ready to handle request` in v1.6.3 comes from then?

**Comment by deads2k** [comment]
> @deads2k Where do you think deployments.extensions "self-hosted-kube-scheduler" is forbidden: not yet ready to handle request in v1.6.3 comes from then?

At a guess?  Namespace lifecycle plugin.

Calls that would succeed: everything cluster scoped, every get, list, watch, delete call.

**Comment by luxas** [comment]
> At a guess? Namespace lifecycle plugin.

@deads2k This happens on master as well and is very annoying. Very error prone to start setting sleep(1) or so just to wait for the API server to be ready when it actually isn't. Is there any way we can fix the Namespace lifecycle plugin in that case?

**Comment by deads2k** [comment]
Hmmm... External detection is a good point.  Most of these *could* punch through and do direct reads if they weren't ready.  I really don't want to end up at a point where the API server keeps getting killed for failing readiness.  This means its taking more than 10 seconds to prime your caches, which seems weird on an empty set up.

**Comment by luxas** [comment]
@deads2k Currently there is a race condition in kubeadm self-hosting where kubeadm checks `/healthz` of the API server every second or so, and when green it directly goes and creates a Deployment.
And flakes on:
```
deployments.extensions "self-hosted-kube-scheduler" is forbidden: not yet ready to handle request
```

**Comment by luxas** [comment]
So it's creating something probably in less than 2 seconds from ok /healthz

**Comment by deads2k** [comment]
> So it's creating something probably in less than 2 seconds from ok /healthz

The admission plugin holds requests up to 10 seconds until the caches prime.

**Comment by luxas** [comment]
> The admission plugin holds requests up to 10 seconds until the caches prime.

@deads2k What can we do to miligate this issue then? Is this PR enough?

**Comment by luxas** [comment]
@deads2k Status on this? Can we proceed? Do we think this will fix the issue linked?

**Comment by sttts** [comment]
@luxas the conclusion with this was that we already block any admission request at least 10 seconds until caches are primed. So if your apiserver startup takes less, it "should" work even without this PR. That's why the hope was to produce a smaller test-case with https://github.com/kubernetes/kubernetes/pull/46865/files#diff-a2fc901d5f88bf99ad9d19777dd646f4R145. Until then we do not really understand the problem.

**Comment by luxas** [comment]
@sttts But don't we think the problem might be the NamespaceLifecycle admission controller in combination with kube-system? Commented on your PR to test kube-system instead...

**Comment by dchen1107** [comment]
I moved this pr to v.18 per above discussion. Also the issue #45786 is not marked for v1.7.

**Comment by sttts** [comment]
Closing, until we better understand the problem.

**Comment by luxas** [comment]
SGTM, haven't seen it at HEAD lately so hopefully fixed...

**Pull request closed without merging**
