### PR TITLE
Add e2e test to test default-deny all Egress

### PR DESCRIPTION
**Pull request by abhiraut**
Currently, only an ingress default-deny NetworkPolicy is being tested. This commit adds a test
for default-deny all egress NetworkPolicy.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by abhiraut** [comment]
Related issue: https://github.com/kubernetes/kubernetes/issues/88375

**Comment by danwinship** [comment]
maybe not relevant since the tests will hopefully be rewritten soon?

**Comment by abhiraut** [comment]
> maybe not relevant since the tests will hopefully be rewritten soon?

hopefully we can get the testing KEP merged soon and start working on porting the framework over. I pushed this PR just in case there is a delay on the KEP end.

**Pull request closed without merging**
