### PR TITLE
federation: Adding deep copy funcs for v1 objects in federation apiserver

### LINKED ISSUE #26111: federation-apiserver: error in converting api.ServiceList to v1.ServiceList
I started the federation-apiserver and went to `/api/v1/services` and got the following output:

```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "converting (api.ServiceList).[0].ObjectMeta.CreationTimestamp.Time.sec to (v1.ServiceList).[0].ObjectMeta.CreationTimestamp.Time.sec: Cannot set dest. (Tried to deep copy something with unexported fields?)",
  "code": 500
}
```

Expected: I should have got an empty v1.ServiceList

@kubernetes/sig-api-machinery @wojtek-t Any idea on what we are doing wrong?

@jianhuiz @mfanjie @kubernetes/sig-cluster-federation Have you guys seen this error?

### PR DESCRIPTION
**Pull request by nikhiljindal**
Trying to fix https://github.com/kubernetes/kubernetes/issues/26111

### CODE REVIEW

**Comment by jianhuiz** [comment]
@nikhiljindal I saw that you added deep copy for v1, do you think it is needed for unversioned as well?

**Comment by nikhiljindal** [comment]
You were right @jianhuiz.
Updated the code and verified that https://github.com/kubernetes/kubernetes/issues/26111 is fixed now.
This is what I see on `/api/v1/services/` now:

```
{
  "kind": "ServiceList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/services/",
    "resourceVersion": "30"
  },
  "items": [
    {
      "metadata": {
        "name": "kubernetes",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/services/kubernetes",
        "uid": "ab91d95e-21f1-11e6-ab68-6c3be516adae",
        "resourceVersion": "8",
        "creationTimestamp": "2016-05-24T20:54:13Z",
        "labels": {
          "component": "apiserver",
          "provider": "kubernetes"
        }
      },
      "spec": {
        "ports": [
          {
            "name": "https",
            "protocol": "TCP",
            "port": 443,
            "targetPort": 443
          }
        ],
        "clusterIP": "10.0.0.1",
        "type": "ClusterIP",
        "sessionAffinity": "ClientIP"
      },
      "status": {
        "loadBalancer": {}
      }
    }
  ]
}
```

We do not need the kubernetes service on federation-apiserver. But the conversions are atleast working fine now. So this PR should be good to go.
cc @kubernetes/sig-cluster-federation

**Comment by nikhiljindal** [comment]
Not sure why @k8s-merge-robot didnt automatically assign someone.
@k8s-oncall as FYI.

Manually assigning to @lavalamp

**Comment by lavalamp** [comment]
It seems unlikely that this will stay correct if it was manually entered. Can you change the input args to the deep copy generator?

**Comment by lavalamp** [comment]
Discussed offline. Will hold my nose and LGTM, and clean up this mess when I have time to work on my refactoring in this area.

**Comment by nikhiljindal** [comment]
Not all code is autogenerated by our scripts. And right now they generate code for all structs in types.go.
If we are fine with including conversion, deep copy funcs for all objects in schema then we can just call v1.addDeepCopyFuncs from here.

So this is the best we have I think if we do not want to register all objects in schema.
Re: staying correct: hopefully our tests will catch it :)

**Comment by nikhiljindal** [comment]
@k8s-bot e2e test this issue: https://github.com/kubernetes/kubernetes/issues/26187

**Comment by nikhiljindal** [comment]
Same failure again.
@k8s-bot e2e test this issue: #26187

**Comment by nikhiljindal** [comment]
I will let @fejta fix #26187 before trying again.
This is clearly consistently failing, not flaky.

**Comment by nikhiljindal** [comment]
@k8s-bot e2e test this issue: #26187

**Comment by nikhiljindal** [comment]
@k8s-bot e2e test this issue: https://github.com/kubernetes/kubernetes/issues/26191

**Comment by nikhiljindal** [comment]
Adding e2e-not-required since there are no e2e tests yet for this part of code

**Pull request merged**
