### PR TITLE
Remove unused funcs in certutil

### PR DESCRIPTION
**Pull request by awly**
https://github.com/kubernetes/kubernetes/issues/71004

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
how do we know they are unused given they are public exports and part of the go client library? ;)

**Comment by mikedanese** [comment]
The cert* packages in client-go are a dumpster fire. We should remove everything that we don't need to support the go client and make as much as we can internal. IIUC, client-go is version bumped per k8s release so we are within the compatibility guarantees of the library:

https://github.com/kubernetes/client-go#compatibility-your-code---client-go

cc @liggitt

**Comment by awly** [comment]
@neolit123 you are right in that they could be used outside of k8s codebase.
The code still exists in the repo history (so vendored versions are still usable). And as Mike mentioned there's compatibility guarantees.

It's a trade-off: cleaner k8s codebase vs easy-to-fix external code breakages.

**Pull request merged**
