### PR TITLE
kube-proxy: handle cmd error

### PR DESCRIPTION
**Pull request by jonyhy96**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

catch error when `MarkFlagFilename`

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/ok-to-test

**Comment by jonyhy96** [comment]
ping @neolit123 for all tests has been passed

**Comment by neolit123** [comment]
/triage accepted
/release-note-none

LGTM, leaving the review to kube-proxy maintainers.

**Comment by jonyhy96** [comment]
PTAL @aojea @neolit123

**Comment by aojea** [comment]
/lgtm
/approve
Thanks
it doesn't seem possible to do anything with the error raised by that method,

**Pull request merged**
