### PR TITLE
Automated cherry pick of #62668: add metrics to cinder

### PR DESCRIPTION
**Pull request by zetaab**
Cherry pick of #62668 on release-1.10.

#62668: add metrics to cinder

### CODE REVIEW

**Comment by zetaab** [comment]
@FengyunPan2 can you review and add LGTM?

**Comment by MaciekPytel** [comment]
@FengyunPan2 can you review by tomorrow EOD? Otherwise this will miss 1.10.2.

**Comment by MaciekPytel** [comment]
/hold
Release branch is now frozen for 1.10.2 release. This will have to wait until the release.

**Comment by dims** [comment]
/hold cancel

looks like we released 1.10.2

**Pull request merged**
