### PR TITLE
insert space after comment character in cmd folder

### PR DESCRIPTION
**Pull request by nagarjung**
Patch which inserts space after the comment character(as per golang conventions in kubernetes) in the cmd folder.

### CODE REVIEW

**Comment by lavalamp** [comment]
ok to test

**Comment by lavalamp** [comment]
LGTM, thanks

**Comment by nagarjung** [comment]
@k8s-bot test this

**Comment by ixdy** [comment]
Both test failures look like flakes.
@k8s-bot test this again please

**Comment by nagarjung** [comment]
Can someone please re-run the tests.

**Comment by lavalamp** [comment]
@k8s-bot test this again

**Comment by nikhiljindal** [comment]
@k8s-bot unit test this

**Comment by nagarjung** [comment]
Can someone please re test this

**Comment by ixdy** [comment]
@nagarjung this change needs to be rebased.

**Comment by nagarjung** [comment]
Can someone please re test this

**Comment by mwielgus** [comment]
@k8s-bot test this please.

**Comment by jayunit100** [comment]
@k8s-bot test this please.

**Pull request merged**
