### PR TITLE
Version-guard Kubectl client Guestbook application test against deployments

### PR DESCRIPTION
**Pull request by ikehz**
Cherry pick of #24342.

### CODE REVIEW

**Comment by roberthbailey** [comment]
Did you change the title? Why doesn't it say "Automated cherry pick of #24342."?

**Comment by ihmccreery** [comment]
@roberthbailey Oh, because I didn't use the auto-cherry-pick tool.  Fixed.

**Comment by zmerlynn** [comment]
Why did you skip the tool?

**Comment by ihmccreery** [comment]
> Why did you skip the tool?

Laziness.  It wasn't going to be a clean cherry pick anyway because of the `framework` package change, so I just did it by hand.  Took 60 seconds rather than 4 minutes.  😨

**Comment by david-mcmahon** [comment]
Since more tooling is relying on the state provided by the cherry_pick_pull.sh tool, lets stick to using that.  If changes do get applied directly to a release branch, do not attempt to make the PR look like it came from the tool ("Automated cherrypick") because they will not get deref'd back to a master PR.
See also https://github.com/kubernetes/kubernetes/blob/master/docs/devel/pull-requests.md#release-notes

**Comment by ihmccreery** [comment]
Ack.

**Pull request merged**
