### PR TITLE
support -E and -S command in iptables

### PR DESCRIPTION
**Pull request by 7ing**
**What this PR does / why we need it**:
This PR is to support two more commands in iptables tool.
-E to rename old chain name to new one
-S to list all rules or rules in specific chain

### CODE REVIEW

**Comment by 7ing** [comment]
I signed CLA before.

**Comment by thockin** [comment]
You need to sign the CNCF CLA, which is different that the Google CLA (in name)

**Comment by thockin** [comment]
Do we need this for something?  This pkg wasn't intended to support every possible thing iptables does, just what we actually use.  If we plan to use it, I am OK to add it.

**Comment by thockin** [comment]
@k8s-bot ok to test

**Comment by 7ing** [comment]
will close this one since the commit has been messed up..

**Pull request closed without merging**
