### PR TITLE
Fix golint issues for pkg/volume/{fc,flocker} packages

### PR DESCRIPTION
**Pull request by leakingtapan**
**What this PR does / why we need it**:
Fix golint issues for pkg/volume/{fc,flocker} packages

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Ref #68026

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by leakingtapan** [comment]
/assign @lavalamp @rootfs
Can you take a look?

**Review by saad-ali — APPROVED** [review]
/lgtm
/approve

**Comment by nikhita** [comment]
/kind cleanup

/assign @cblecker 
for hack/ approval

**Comment by cblecker** [comment]
/approve

Thanks @leakingtapan!

**Pull request merged**
