### PR TITLE
No change PR for testing CI

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This PR makes no change and is intended to investigate problems with CI.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
I looked at the logs from https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106413/pull-kubernetes-kubemark-e2e-gce-scale/1461164903535480832 .  I looked at why the pod named `medium-statefulset-0-0` in namespace `test-l63ebb-26` never got to running.  The proximal reason is that that pod's PVC never got bound.  Following is the audit log's entry for the pod status patch that shows the pod waiting for the PVC to be bound (with linebreaks added for readability).  After that nothing happened to the pod or PVC until the clusterloader started deleting things at the end of the test.

```
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"RequestResponse",
"auditID":"9a910081-2633-4f05-a1f4-c79936487804",
"stage":"ResponseComplete",
"requestURI":"/api/v1/namespaces/test-l63ebb-26/pods/medium-statefulset-0-0/status",
"verb":"patch","user":{"username":"system:kube-scheduler","uid":"uid:system:kube-scheduler","groups":["system:authenticated"]},"sourceIPs":["::1"],"userAgent":"kube-scheduler/v1.23.0 (linux/amd64) kubernetes/737b8da/scheduler",
"objectRef":{"resource":"pods","namespace":"test-l63ebb-26",
    "name":"medium-statefulset-0-0","apiVersion":"v1","subresource":"status"},"responseStatus":{"metadata":{},"code":200},
"requestObject":{"status":{"conditions":[{"lastProbeTime":null,"lastTransitionTime":"2021-11-18T03:42:22Z",
  "message":"0/5001 nodes are available: 5001 pod has unbound immediate PersistentVolumeClaims.","reason":"Unschedulable","status":"False","type":"PodScheduled"}]}},
"responseObject":{"kind":"Pod","apiVersion":"v1","metadata":{"name":"medium-statefulset-0-0","generateName":"medium-statefulset-0-","namespace":"test-l63ebb-26","uid":"25316bea-ff08-4944-ad4a-19f5fb4f4a00","resourceVersion":"720652","creationTimestamp":"2021-11-18T03:42:22Z","labels":{"controller-revision-hash":"medium-statefulset-0-758846c595","group":"load","name":"medium-statefulset-0","statefulset.kubernetes.io/pod-name":"medium-statefulset-0-0"},"ownerReferences":[{"apiVersion":"apps/v1","kind":"StatefulSet","name":"medium-statefulset-0","uid":"ef627588-c76a-47cd-9ba0-a8005d705dbc","controller":true,"blockOwnerDeletion":true}],"managedFields":[{"manager":"kube-controller-manager","operation":"Update","apiVersion":"v1","time":"2021-11-18T03:42:22Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:generateName":{},"f:labels":{".":{},"f:controller-revision-hash":{},"f:group":{},"f:name":{},"f:statefulset.kubernetes.io/pod-name":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"ef627588-c76a-47cd-9ba0-a8005d705dbc\"}":{}}},"f:spec":{"f:containers":{"k:{\"name\":\"medium-statefulset-0\"}":{".":{},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":80,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:name":{},"f:protocol":{}}},"f:resources":{".":{},"f:requests":{".":{},"f:cpu":{},"f:memory":{}}},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{},"f:volumeMounts":{".":{},"k:{\"mountPath\":\"/var/pv\"}":{".":{},"f:mountPath":{},"f:name":{}}}}},"f:dnsPolicy":{},"f:enableServiceLinks":{},"f:hostname":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:subdomain":{},"f:terminationGracePeriodSeconds":{},"f:tolerations":{},"f:volumes":{".":{},"k:{\"name\":\"pv\"}":{".":{},"f:name":{},"f:persistentVolumeClaim":{".":{},"f:claimName":{}}}}}}},{"manager":"kube-scheduler","operation":"Update","apiVersion":"v1","time":"2021-11-18T03:42:22Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:conditions":{".":{},"k:{\"type\":\"PodScheduled\"}":{".":{},"f:lastProbeTime":{},"f:lastTransitionTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}}}},"subresource":"status"}]},"spec":{"volumes":[{"name":"pv","persistentVolumeClaim":{"claimName":"pv-medium-statefulset-0-0"}},{"name":"kube-api-access-q59tm","projected":{"sources":[{"serviceAccountToken":{"expirationSeconds":3607,"path":"token"}},{"configMap":{"name":"kube-root-ca.crt","items":[{"key":"ca.crt","path":"ca.crt"}]}},{"downwardAPI":{"items":[{"path":"namespace","fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}]}}],"defaultMode":420}}],"containers":[{"name":"medium-statefulset-0","image":"k8s.gcr.io/pause:3.1","ports":[{"name":"web","containerPort":80,"protocol":"TCP"}],"resources":{"requests":{"cpu":"10m","memory":"10M"}},"volumeMounts":[{"name":"pv","mountPath":"/var/pv"},{"name":"kube-api-access-q59tm","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":1,"dnsPolicy":"ClusterFirst","serviceAccountName":"default","serviceAccount":"default","securityContext":{},"hostname":"medium-statefulset-0-0","subdomain":"medium-statefulset-0","schedulerName":"default-scheduler","tolerations":[{"key":"node.kubernetes.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":900},{"key":"node.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":900}],"priority":0,"enableServiceLinks":true,"preemptionPolicy":"PreemptLowerPriority"},
"status":{"phase":"Pending","conditions":[
  {"type":"PodScheduled","status":"False","lastProbeTime":null,
    "lastTransitionTime":"2021-11-18T03:42:22Z","reason":"Unschedulable",
    "message":"0/5001 nodes are available: 5001 pod has unbound immediate PersistentVolumeClaims."}
],"qosClass":"Burstable"}},"requestReceivedTimestamp":"2021-11-18T03:42:22.689359Z","stageTimestamp":"2021-11-18T03:42:22.693539Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"system:kube-scheduler\" of ClusterRole \"system:kube-scheduler\" to User \"system:kube-scheduler\""}}
```

**Comment by MikeSpreitzer** [comment]
Following is the audit log entry for the creation of that PVC (with linebreaks added for readability).

```
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"RequestResponse","auditID":"67692a6b-722d-417c-9901-f17f13d4632a",
"stage":"ResponseComplete",
"requestURI":"/api/v1/namespaces/test-l63ebb-26/persistentvolumeclaims",
"verb":"create","user":{"username":"system:serviceaccount:kube-system:statefulset-controller","uid":"2d73172f-7562-4f9b-af99-06858a71e110","groups":["system:serviceaccounts","system:serviceaccounts:kube-system","system:authenticated"]},"sourceIPs":["::1"],"userAgent":"kube-controller-manager/v1.23.0 (linux/amd64) kubernetes/737b8da/system:serviceaccount:kube-system:statefulset-controller",
"objectRef":{"resource":"persistentvolumeclaims",
    "namespace":"test-l63ebb-26",
    "name":"pv-medium-statefulset-0-0","apiVersion":"v1"},
"responseStatus":{"metadata":{},"code":201},
"requestObject":{"kind":"PersistentVolumeClaim","apiVersion":"v1","metadata":{"name":"pv-medium-statefulset-0-0","namespace":"test-l63ebb-26","creationTimestamp":null,"labels":{"group":"load","name":"medium-statefulset-0"}},
  "spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"100Mi"}},"volumeMode":"Filesystem"},"status":{"phase":"Pending"}},
"responseObject":{"kind":"PersistentVolumeClaim","apiVersion":"v1",
  "metadata":{"name":"pv-medium-statefulset-0-0","namespace":"test-l63ebb-26","uid":"6a836e85-cffe-4c5b-a452-ef326a4bbd0e","resourceVersion":"720636",
    "creationTimestamp":"2021-11-18T03:42:22Z","labels":{"group":"load","name":"medium-statefulset-0"},"finalizers":["kubernetes.io/pvc-protection"],"managedFields":[{"manager":"kube-controller-manager","operation":"Update","apiVersion":"v1","time":"2021-11-18T03:42:22Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:group":{},"f:name":{}}},"f:spec":{"f:accessModes":{},"f:resources":{"f:requests":{".":{},"f:storage":{}}},"f:volumeMode":{}}}}]},
  "spec":{"accessModes":["ReadWriteOnce"],
    "resources":{"requests":{"storage":"100Mi"}},"volumeMode":"Filesystem"},
  "status":{"phase":"Pending"}},
"requestReceivedTimestamp":"2021-11-18T03:42:22.672432Z","stageTimestamp":"2021-11-18T03:42:22.675814Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"system:controller:statefulset-controller\" of ClusterRole \"system:controller:statefulset-controller\" to ServiceAccount \"statefulset-controller/kube-system\""}}
```

**Comment by MikeSpreitzer** [comment]
The kube-controller-manager.log has the following entry.

```
I1118 03:42:22.676127      12 event.go:294] "Event occurred" object="test-l63ebb-26/pv-medium-statefulset-0-0" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="FailedBinding" message="no persistent volumes available for this claim and no storage class is set"
```

and many more like it later.

**Comment by wojtek-t** [comment]
The test config has been fixed and works. We're already making significant progress on other PRs. Closing this one.

**Pull request closed without merging**
