### PR TITLE
Move service affinity predicate logic to its plugin.

### LINKED ISSUE #86263: Move ServiceAffinity predicate logic to its plugin [Migration Phase 2]
/assign @ahg-g 
/sig scheduling
/priority important-soon

This includes moving the metadata logic into prefilter.

Part of #85822

### PR DESCRIPTION
**Pull request by ahg-g**
**What type of PR is this?**

/kind cleanup

**Which issue(s) this PR fixes**:
Fixes #86263

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cc @Huang-Wei

### CODE REVIEW

**Comment by Huang-Wei** [comment]
LGTM generally. Will /lgtm after rebasing.

**Comment by ahg-g** [comment]
@Huang-Wei rebased.

**Pull request merged**
