### PR TITLE
client-gen: avoid panic for empty groups

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by mrIncompetent** [comment]
I ran into this issue when i tried to generate a client for 2 groups.
This PR fixes my problem!

```
Removing old client
Generating clientset
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/kubermatic/kubermatic/api/vendor/k8s.io/code-generator/cmd/client-gen/generators.(*genGroup).Filter(0xc4286b5b80, 0xc428f1b980, 0xc425f67290, 0x882688)
	/home/henrik/work/src/github.com/kubermatic/kubermatic/api/vendor/k8s.io/code-generator/cmd/client-gen/generators/generator_for_group.go:49 +0x3e
github.com/kubermatic/kubermatic/api/vendor/k8s.io/gengo/generator.(Generator).Filter-fm(0xc428f1b980, 0xc425f67290, 0xc42bbd9828)
	/home/henrik/work/src/github.com/kubermatic/kubermatic/api/vendor/k8s.io/gengo/generator/execute.go:221 +0x43
github.com/kubermatic/kubermatic/api/vendor/k8s.io/gengo/generator.(*Context).filteredBy(0xc428f1b980, 0xc42bbd9ab8, 0x882688)
	/home/henrik/work/src/github.com/kubermatic/kubermatic/api/vendor/k8s.io/gengo/generator/execute.go:182 +0x108
github.com/kubermatic/kubermatic/api/vendor/k8s.io/gengo/generator.(*Context).ExecutePackage(0xc428654600, 0xc42000c9a0, 0x15, 0x84d5a0, 0xc42a69a200, 0x0, 0x0)
	/home/henrik/work/src/github.com/kubermatic/kubermatic/api/vendor/k8s.io/gengo/generator/execute.go:221 +0x3c6
github.com/kubermatic/kubermatic/api/vendor/k8s.io/gengo/generator.(*Context).ExecutePackages(0xc428654600, 0xc42000c9a0, 0x15, 0xc42a69aa00, 0x7, 0x8, 0x0, 0xc420017140)
	/home/henrik/work/src/github.com/kubermatic/kubermatic/api/vendor/k8s.io/gengo/generator/execute.go:51 +0xa7
github.com/kubermatic/kubermatic/api/vendor/k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc420078500, 0xc420017290, 0x70029d, 0x6, 0x7147d8, 0x1, 0x4)
	/home/henrik/work/src/github.com/kubermatic/kubermatic/api/vendor/k8s.io/gengo/args/args.go:166 +0x22c
main.main()
	/home/henrik/work/src/github.com/kubermatic/kubermatic/api/vendor/k8s.io/code-generator/cmd/client-gen/main.go:201 +0x650
```

**Comment by lavalamp** [comment]
@grodrigues3 This PR is fine and good, but the queue shouldn't have merged it. Did someone forget to make the queue require the approved for milestone label??

**Comment by lavalamp** [comment]
@caesarxuchao can you double check this PR?

**Comment by caesarxuchao** [comment]
lgtm

**Pull request merged**
