### PR TITLE
Cherry pick of #112074: e2e: use custom timeouts in GetSnapshotContentFromSnapshot()

### PR DESCRIPTION
**Pull request by AnishShah**
#### What type of PR is this?

/kind bug
/kind flake

#### What this PR does / why we need it:

This patch replaces a hardcoded timeout for volume deletion and use the custom timeout instead. This was fixed in 1.26 but I'm backporting it to 1.25.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by msau42** [comment]
In the title, can you reference the PR that you are cherry picking?

For future reference, this script makes the cherry picking process easier: https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh

**Comment by saschagrunert** [comment]
Any reason to not backport this to 1.23/24?

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
