### PR TITLE
Improve the prompt message when kubeadm init is successful

### PR DESCRIPTION
**Pull request by hs0210**
Signed-off-by: Hu Shuai <hus.fnst@cn.fujitsu.com>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add a prompt message to the root user who uses kubeadm to create a cluster.
**Which issue(s) this PR fixes**:
NONE

**Special notes for your reviewer**:
NONE
**Does this PR introduce a user-facing change?**:
NONE

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by hs0210** [comment]
```release-note
NONE
```

**Comment by neolit123** [comment]
this seems fine to me.

/priority backlog
/lgtm
/approve
/ok-to-test

**Pull request merged**
