### PR TITLE
Cherrypick of #58439 #56408: Fix decoding of admission config file

### PR DESCRIPTION
**Pull request by liggitt**
Manual pick of #58439 and #56408 into release-1.9

```release-note
kube-apiserver: fixes loading of `--admission-control-config-file` containing AdmissionConfiguration apiserver.k8s.io/v1alpha1 config object
```

### CODE REVIEW

**Comment by liggitt** [comment]
@mbohlool for cherrypick approval

**Comment by mbohlool** [comment]
@jennybuckley

**Pull request merged**
