### PR TITLE
code fmt in  pkg/controller/daemon/daemon_controller.go

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:
code convention
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
ping @kargakis @janetkuo could you please review this pr in your spare time?

**Comment by hzxuzhonghu** [comment]
@kargakis please review this, thanks

**Review by janetkuo — APPROVED** [review]

**Comment by janetkuo** [comment]
@hzxuzhonghu thanks for the patch. This lgtm. Would you squash these two commits into one?

**Comment by hzxuzhonghu** [comment]
sure, @janetkuo

**Comment by hzxuzhonghu** [comment]
kindly ping @janetkuo @kargakis  I  squash these two commits into one, and need your approve again.

**Comment by hzxuzhonghu** [comment]
ping @janetkuo @kargakis and I need your approve again.

**Comment by kargakis** [comment]
@kubernetes/sig-apps-pr-reviews do we want to handle this holistically throughout the controllers? I don't feel strong for checking in changes like this in individual places.

**Pull request closed without merging**
