### PR TITLE
Add Docker caching support to CoreOS' clusters.

### PR DESCRIPTION
**Pull request by AntonioMeireles**
```
a more idiomatic take on #4378. as a bonus, and to be nice on
resources, an ultra lightweight docker-registry container is
consumed.
```

### CODE REVIEW

**Comment by nikhiljindal** [comment]
@brendandburns : Are you the right person to assign this to?

**Comment by erictune** [comment]
fyi @pires

**Comment by pires** [comment]
@erictune I favor this one instead of my old #4378. LGTM

**Comment by AntonioMeireles** [comment]
guys, i've appended an extra patchlet to simplify fleet's intrumentation. IMHO, it also would make sense to handle flannels' invocation in a similar way (taking advantage of what already ships nativelly) and just consume the (units in) currently shipping CoreOS. So, is there any good reason to be using the blob at https://storage.googleapis.com/k8s/flanneld instead of the upstream bits shipping in plain CoreOS ? (fwiw in the [kubernetes-vagrant-coreos-cluste](https://github.com/pires/kubernetes-vagrant-coreos-cluster)r project we've been using plain upstream flannel without any (obvious) issues ).

**Comment by brendandburns** [comment]
Looks good to me.  merging.

(the reason we use the blob in google storage is idempotentcy of deploy, but given that we haven't updated it in a while, I'm ok with relying on the CoreOS version)

**Pull request merged**
