### PR TITLE
Update the re-fetched pod with deployment labels.

### PR DESCRIPTION
**Pull request by bprashanth**
https://github.com/kubernetes/kubernetes/issues/21803#issuecomment-190470366

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Good catch, thanks!

LGTM

**Comment by bprashanth** [comment]
@k8s-bot test this github issue: #10136

**Comment by bprashanth** [comment]
@k8s-oncall this can probably get a hand merge if the submit queue is deep

**Comment by bgrant0607** [comment]
Good catch @bprashanth!

**Pull request merged**
