### PR TITLE
Added missed KUBECTL_OPTS for KUBECTL

### PR DESCRIPTION
**Pull request by hfrog**
**What this PR does / why we need it**:
PR fixes kubectl call in the script cluster/addons/addon-manager/kube-addons.sh by adding ${KUBECTL_OPTS}. Without this fix the following error can be seen in the kube-addon-manager.log:
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
Thanks for the fix!

/lgtm

**Comment by hfrog** [comment]
thank you @zmerlynn

**Comment by MrHohn** [comment]
/retest
/assign @mikedanese 
for approval.

**Pull request closed without merging**
