### PR TITLE
KEP-4222: Test response content negotiation for each CBOR enablement state.

### PR DESCRIPTION
**Pull request by benluddy**
#### What type of PR is this?

/kind cleanup
/sig api-machinery

#### What this PR does / why we need it:

Integration test coverage of response content negotiation involving CBOR is a requirement for KEP-4222.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

This depends on the integration test wiring introduced in https://github.com/kubernetes/kubernetes/pull/128243.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://kep.k8s.io/4222
```

### CODE REVIEW

**Comment by jpbetz** [comment]
LGTM, happy to tag once https://github.com/kubernetes/kubernetes/pull/128243 merges

**Comment by benluddy** [comment]
> LGTM, happy to tag once #128243 merges

PTAL, this PR became smaller as some of the tests had to be implemented as part of feature gate enablement testing (dynamic client doesn't accept arbitrary content config and is tested in https://github.com/kubernetes/kubernetes/blob/a15840a34bf69b9341441499447669aa8d2fca0a/test/integration/client/dynamic_client_test.go#L304, and arbitrary content configs are only tested in https://github.com/kubernetes/kubernetes/blob/a15840a34bf69b9341441499447669aa8d2fca0a/test/integration/client/client_test.go#L1363 to demonstrate that they can be force disabled at runtime by feature gate). Now it's mainly adding cases to demonstrate that response content negotiation honors relative preference properly.

**Pull request merged**
