### PR TITLE
Revert "Update prometheus library usage"

### LINKED ISSUE #14228: Integration tests are failing on head:
```
E0919 19:59:14.204169   21911 handlers.go:37] Unable to authenticate the request due to an error: Token has been invalidated
E0919 19:59:14.605255   21911 handlers.go:37] Unable to authenticate the request due to an error: Token has been invalidated
E0919 19:59:15.005427   21911 handlers.go:37] Unable to authenticate the request due to an error: Token has been invalidated
FAIL
FAIL    k8s.io/kubernetes/test/integration      91.656s
```

### PR DESCRIPTION
**Pull request by gmarek**
Reverts kubernetes/kubernetes#14202

Fixes #14228

cc @eparis @timstclair @thockin

### CODE REVIEW

**Comment by eparis** [comment]
and yours is now going to fail too, because of other broken godeps.

**Comment by gmarek** [comment]
How exactly we ended up in this situation?

**Comment by eparis** [comment]
about 3 different problems.   :-(  Let me verify this PR and I'll merge by hand.

**Comment by timstclair** [comment]
:/ Thanks for dealing with this. Let me know if you need anything.

**Comment by eparis** [comment]
I don't see how the prometheus PR, which only touches e2e could cause integration failures. But after https://github.com/kubernetes/kubernetes/pull/14198 we should be able to trust CI again.

**Comment by eparis** [comment]
If either @timstclair or @gmarek want to review that PR, it should get us moving forward...

**Comment by gmarek** [comment]
As for integration tests, AFAICT it broke `test/integration/metrics_test.go` - I don't know what happened with `process_goroutines` metric but: 
```
--- FAIL: TestMasterProcessMetrics (0.17s)
        metrics_test.go:84: Master metrics did not include expected metric "process_goroutines"
```

**Comment by timstclair** [comment]
FYI, it looks like the update of the prometheus dep broke that test since they renamed that metric: https://github.com/prometheus/client_golang/pull/123

I'll fix the test and roll-forward.

**Pull request merged**
