### PR TITLE
Add wojtek to global approvers

### PR DESCRIPTION
**Pull request by timothysc**
**What this PR does / why we need it**:
Allows @wojtek-t to globally approve, as he was the right person to approve 
https://github.com/kubernetes/kubernetes/pull/40176 and is a top contributor across the project.

In general, cross cutting code changes should probably allow an override by a maintainer "in the know", until a time where the approvers is fully populated.  

**Special notes for your reviewer**:
Doesn't default him as a reviewer across the whole project, unless he thinks that is correct.

**Release note**:

```release-note
NONE
```

/cc @bgrant0607 @wojtek-t @kubernetes/sig-contributor-experience-bugs

### CODE REVIEW

**Comment by bgrant0607** [comment]
@fgrzadkowski raised this issue this morning. There's no top-level approver in non-American timezones. 

Wojtek is the third biggest contributor. The alternative would be to add him to every top-level subdirectory.

The responsibilities, power, and process for adding top-level approvers is still under discussion (https://github.com/kubernetes/community/issues/277), but we don't need to wait for that in this case, IMO.

cc @thockin @smarterclayton @brendandburns @dchen1107 @jbeda @lavalamp

**Comment by bgrant0607** [comment]
/lgtm

Will wait for comment before approving.

**Comment by smarterclayton** [comment]
Looks good to me.

**Comment by timothysc** [comment]
stamping from feedback so we can unblock other work items.

**Review by smarterclayton — APPROVED** [review]

**Pull request merged**
