### PR TITLE
Automated cherry pick of #96742: Update ingress conformance test for finalizers

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #96742 on release-1.19.

#96742: Update ingress conformance test for finalizers

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by hasheddan** [comment]
/retest

Will open an issue for this: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/96953/pull-kubernetes-node-e2e/1333411311995850752/

**Comment by liggitt** [comment]
cc @kubernetes/release-managers

for cherrypick approval

**Pull request merged**
