### PR TITLE
removing kubelet's flag chaos-chance

### PR DESCRIPTION
**Pull request by wangyysde**
#### What type of PR is this?
/kind cleanup
/area kubelet

#### What this PR does / why we need it:
The kubelete testing flag chaos-chance has been marked as deprecated in v1.19.  After the deprecation period,now the flag has be removed in 1.22. 

#### Which issue(s) this PR fixes:

ref #90499

#### Does this PR introduce a user-facing change?

```release-note
After the deprecation period,now the Kubelet's  `--chaos-chance` flag  are removed.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by knabben** [comment]
can you change the PR description indicating it's now removed after the deprecation period? otherwise

/lgtm

cc @adisky

**Comment by wangyysde** [comment]
@knabben Thanks.  I have changed the title and the description.

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
