### PR TITLE
Automated cherry pick of #11106 upstream release 1.0

### PR DESCRIPTION
**Pull request by davidopp**
Justification: fixes Shippable failure.

@zmerlynn

### CODE REVIEW

**Comment by zmerlynn** [comment]
LGTM. Crosslink: #11106

**Comment by davidopp** [comment]
@k8s-bot test this please

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Comment by davidopp** [comment]
@zmerlynn do you have any thoughts on the jenkins failure? It seems deterministic since it failed twice. Yet this PR has nothing to do with the failure. And the other cherrypick I did (#11189) passes Jenkins.

**Comment by davidopp** [comment]
@k8s-bot test this

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Comment by zmerlynn** [comment]
@davidopp No idea, let's give it one more try. (Why am I not seeing the @k8s posts here?)

**Comment by zmerlynn** [comment]
@ixdy: Can you tell if @k8s-bot is ignoring us or something else? Results aren't getting posted to this PR, which is odd.

**Comment by zmerlynn** [comment]
@ixdy: Oh. I see what's going on here, and it's bad news bears for the interaction of the PR-builder and the release branch. If you click through on the internal results of this PR by @k8s-bot, it looks like it's assuming this is the same as #11185. But that's actually really bad, because it means it may have no clue about "base:release-1.0" when it's doing it's work. Opening a separate bug to track this - it's not a huge priority because I have a Jenkins job on this branch anyways, but it's going to be kind of noisy if PRs constantly fail later because of merge conflicts as the release branch drifts.

**Pull request merged**
