### PR TITLE
remove resyncPeriod from NewStatefulSetController

### PR DESCRIPTION
**Pull request by NickrenREN**
remove resyncPeriod arg from NewStatefulSetController since it is never used

### CODE REVIEW

**Comment by dhilipkumars** [comment]
Good catch ,other controllers dont have it. 
cc @kow3ns

**Comment by smarterclayton** [comment]
@ncdc

**Comment by ncdc** [comment]
@NickrenREN would you object to me pulling this change into https://github.com/kubernetes/kubernetes/pull/41482?

**Comment by NickrenREN** [comment]
@ncdc Go ahead

**Comment by ncdc** [comment]
@NickrenREN thanks, I have incorporated this into #41482, so I'm closing this one.

**Pull request closed without merging**
