### PR TITLE
Fix CSI CRD installation for Alpha clusters

### LINKED ISSUE #70760: CSI alpha tests are failing
**What happened**:
Probably caused by https://github.com/kubernetes/kubernetes/pull/70193

/kind bug

### PR DESCRIPTION
**Pull request by saad-ali**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
/kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Undo changes to `cluster/gce/config-default.sh`
Moves alpha check to `cluster/gce/gci/configure-helper.sh`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/kubernetes/issues/70760

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by mikedanese** [comment]
lgtm
/approve

Do you need to change anything in /cluster/gce/config-test.sh to modify test cluster deployment config? Often these fails are kept in lockstep.

**Comment by saad-ali** [comment]
> Do you need to change anything in /cluster/gce/config-test.sh to modify test cluster deployment config? Often these fails are kept in lockstep.

I just removed the `config-` changes altogether.

**Pull request merged**
