### PR TITLE
e2e delete namespaces after finish

### PR DESCRIPTION
**Pull request by aojea**
**What type of PR is this?**

/kind bug
/kind cleanup
/kind failing-test
/kind flake

**What this PR does / why we need it**:

The test `[sig-network] [Feature:PerformanceDNS][Serial] Should answer DNS query for maximum number of services per cluster` is not cleaning up the resources after it runs, and causes etcd to exhaust the quota, thus, causing the subsequent tests to fail because of

```
"error":"error initializing the store: etcdserver: mvcc: database space exceeded","level":"fatal","msg":"error executing sensu-backend","time":"2019-10-30T09:27:15Z"Unexpected Error: "500"
```

xref https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-network/1291532747889709057

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by wojtek-t** [comment]
Seems like misconfigured etcd to me too (this single test shouldn't result in exceeding etcd quota).
But the PR is obviously a reasonable mitigation.

/lgtm
/approve

**Comment by aojea** [comment]
> Seems like misconfigured etcd to me too (this single test shouldn't result in exceeding etcd quota).
> But the PR is obviously a reasonable mitigation.
> 

It's the default configuration for KIND, that uses kubeadm
where is this limit for services/etcd configured?

**Comment by aojea** [comment]
/cc @hasheddan 
for milestone approvad, is a e2e test fix

**Comment by aojea** [comment]
> > Seems like misconfigured etcd to me too (this single test shouldn't result in exceeding etcd quota).
> > But the PR is obviously a reasonable mitigation.
> 
> It's the default configuration for KIND, that uses kubeadm
> where is this limit for services/etcd configured?

for the record, @BenTheElder answered it
https://github.com/kubernetes/kubernetes/blob/92e51c19017a9e417df291e469ffebb13b6b51e2/cmd/kubeadm/app/phases/etcd/local.go#L281

**Comment by BenTheElder** [comment]
e2e-gce seems to also have the same snapshot count though, and I don't see anything else relevant, though I'm not an expert.

**Pull request merged**
