### PR TITLE
kubectl wait should wait for non-existent resources.

### LINKED ISSUE #1516: `kubectl wait` for un-existed resource.
**What happened**:

I can not avoid exit with error for uncreated resource, which is misleading by the command name:

`kubectl wait --selector=foo=bar --for=condition=complete jobs`
`kubectl wait --for=condition=complete jobs/foo`

Even if this behavior if intentional the user should have an option to continue waiting instead of exit with error code.

In the contrast, if the resource already exists everything works as it should.

**What you expected to happen**:

Kubectl should at least to have the ability (option) to wait un-existed resource.

**Anything else we need to know?**:

Connect kubernetes/kubernetes#75227

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.2
- OS (e.g: `cat /etc/os-release`): mac Os 10.14.6
- Kernel (e.g. `uname -a`): Darwin Kernel Version 18.7.0

### PR DESCRIPTION
**Pull request by tamalsaha**
Fixes: kubernetes/kubectl#1516

Signed-off-by: Tamal Saha <tamal@appscode.com>

/kind bug
/sig cli

```release-note
NONE
```

### CODE REVIEW

**Comment by tamalsaha** [comment]
cc: @rikatz, @dims @liggitt

**Comment by rikatz** [comment]
/remove-lifecycle rotten
/lifecycle frozen
/assign @soltysh 

Need someone with better knowledge here, honestly I don't know if this is the best way for kubectl wait to wait for objects that does not exists

**Comment by Raffo** [comment]
This looks really simple, but on a similar fashion to my comment in https://github.com/kubernetes/kubernetes/issues/95759#issuecomment-770754693, can we reuse the work in kstatus?

**Comment by prune998** [comment]
What about this ? 
Should we drop this PR and create a new one ?  Update this one ? 
It's a simple change to wait... option, that is requested by many for CRD management... Is there any blocker ?

**Comment by prune998** [comment]
@tamalsaha Where are you with this PR ?

To me, it would make sens that:
- we add a "--wait-if-nonexistant"
- we stop waiting after the `timeout` period
- we keep retrying to get the non-existant object in the main `getObjAndCheckCondition` function from the master branch (this branch is really outdated)
(https://github.com/kubernetes/kubernetes/blob/9968b0eff06f109792e64f37ee92889711713a88/staging/src/k8s.io/kubectl/pkg/cmd/wait/wait.go#L412)

wdyt ? 
is it worth putting some time and effort ?

**Comment by dims** [comment]
Is this PR still needed, please rebase if so (or we can close it?)

**Comment by MurzNN** [comment]
It is very needed, related issue is still open with many votes!

**Comment by dims** [comment]
@MurzNN please see the `needs-rebase` label and the tide ci job failure. this needs a rebase to newest master branch

image

**Comment by dims** [comment]
This PR is older than 4 weeks and needs as rebase.

Please rebase the PR against latest master and reopen if still needed.

/close

**Comment by DARB-CCM-S-20** [comment]
Where are we with this PR?

**Pull request closed without merging**
