### PR TITLE
kubeadm: fix flaky test TestRetrieveValidatedConfigInfo

### LINKED ISSUE #2965: fix flaky test TestRetrieveValidatedConfigInfo
calling this:
```
go test ./cmd/kubeadm/app/discovery/token/... -count=1
```

sometimes panics but on a very rare occasion:

```
--- FAIL: TestRetrieveValidatedConfigInfo (0.24s)
    --- FAIL: TestRetrieveValidatedConfigInfo/valid:_retrieve_a_valid_kubeconfig_with_CA_verification_and_delayed_JWS_signature (0.24s)
        token_test.go:268: expected error false, got true, error: could not find a JWS signature in the cluster-info ConfigMap for token ID "123456"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16309e6]

goroutine 21 [running]:
testing.tRunner.func1.2({0x17d1600, 0x29329b0})
	/usr/local/go/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1548 +0x397
panic({0x17d1600?, 0x29329b0?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
k8s.io/kubernetes/cmd/kubeadm/app/discovery/token.TestRetrieveValidatedConfigInfo.func1(0xc0001e2680)
	/home/lubo/go/src/k8s.io/kubernetes/cmd/kubeadm/app/discovery/token/token_test.go:277 +0x7c6
testing.tRunner(0xc0001e2680, 0xc0003660d0)
	/usr/local/go/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 20
	/usr/local/go/src/testing/testing.go:1648 +0x3ad
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/discovery/token	0.292s
```

it panics here:
https://github.com/kubernetes/kubernetes/blob/94f15bbbcbe952762b7f5e6e3f77d86ecec7d7c2/cmd/kubeadm/app/discovery/token/token_test.go#L277
bacause of `*kubeconfig`.

to prevent the panic this:
https://github.com/kubernetes/kubernetes/blob/94f15bbbcbe952762b7f5e6e3f77d86ecec7d7c2/cmd/kubeadm/app/discovery/token/token_test.go#L271-L274

can be changed to:
```
if err != nil {
    return
}`.
```

but this fix is not enough. we have to understand why the case:
https://github.com/kubernetes/kubernetes/blob/94f15bbbcbe952762b7f5e6e3f77d86ecec7d7c2/cmd/kubeadm/app/discovery/token/token_test.go#L88
is failing.

one possibility is to increase this timeout to 1 second or more:
https://github.com/kubernetes/kubernetes/blob/94f15bbbcbe952762b7f5e6e3f77d86ecec7d7c2/cmd/kubeadm/app/discovery/token/token_test.go#L251

it could be that the go routine to apply the JWS token (60ms) completes after the timeout (200ms).

maybe, instead of trying to fix this test case we can just remove it? it tests the delayed apply of the JWS, but this is already tested in e2e:
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm

### PR DESCRIPTION
**Pull request by my-git9**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/2965

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks!

/lgtm
/approve
/triage accepted

please change this:
> Fixes # https://github.com/kubernetes/kubeadm/issues/2965

to:
> > Fixes https://github.com/kubernetes/kubeadm/issues/2965

to

**Comment by neolit123** [comment]
if the PR is LGTM / approved it will merge one 1.30 work starts...in one week or so.

**Comment by my-git9** [comment]
> thanks!
> 
> /lgtm /approve /triage accepted
> 
> please change this:
> 
> > Fixes # [kubernetes/kubeadm#2965](https://github.com/kubernetes/kubeadm/issues/2965)
> 
> to:
> 
> > > Fixes [kubernetes/kubeadm#2965](https://github.com/kubernetes/kubeadm/issues/2965)
> 
> to

Updated, thanks

**Pull request merged**
