### PR TITLE
Widen margins of TestDifferentWidths and TestTooWide

### LINKED ISSUE #104860: TestDifferentWidths flakes
#### Which jobs are flaking:
pull-kubernetes-unit

#### Which test(s) are flaking:
TestDifferentWidths

#### Testgrid link:
 https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/104801/pull-kubernetes-unit/1435825901991366656

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-unit

#### Reason for failure:
```
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset: TestDifferentWidths expand_less | 0s
-- | --
=== RUN   TestDifferentWidths     queueset_test.go:211: 2021-09-09 05:03:38.347675904: Start TestDifferentWidths, doSplit=false, clk=0xc00024ec80, grc=0xc0000416d4     queueset_test.go:270: 2021-09-09 05:03:38.347675904: 0, 0, 0 got req=0xc000411c70, idle=false     queueset_test.go:286: 2021-09-09 05:03:38.347675904: 0, 0, 0 executing; seats=1     queueset_test.go:270: 2021-09-09 05:03:38.347675906: 1, 0, 0 got req=0xc000120d00, idle=false

<br class="Apple-interchange-newline">
```

#### Anything else we need to know:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
#### What type of PR is this?

/kind bug
/kind failing-test
/kind flake

#### What this PR does / why we need it:
This PR modifies the queueset behavioral unit tests TestDifferentWidths and TestTooWide, expanding the allowed relative difference from the ideal results.  This is good because the allowed relative differences were too small, causing flakiness of the tests.

With the old margins, I was able to reproduce the test failures with a handful of trials. With the new margins I tried 100 times and got no failures.

#### Which issue(s) this PR fixes:

Fixes #104860

#### Special notes for your reviewer:
This is an alternative to #104856 , which I think mis-attributes the blame.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs 
/cc @lavalamp 
/cc @deads2k 
/cc @wojtek-t

**Comment by pacoxu** [comment]
/test pull-kubernetes-unit
flake which will be fixed in #104069

**Comment by pacoxu** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/104854/pull-kubernetes-unit/1436143460418588672
```fairqueuing/queueset: TestTooWide```
This test flakes today. 😓

**Pull request merged**
