### PR TITLE
refactor destroy func in unit testing

### PR DESCRIPTION
**Pull request by hongchaodeng**
Continued on https://github.com/kubernetes/kubernetes/pull/31390#issuecomment-242572312

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31495)

### CODE REVIEW

**Comment by hongchaodeng** [comment]
@k8s-bot test this issue: #IGNORE
```
ERROR: (gcloud.container.clusters.delete) Some requests did not succeed:
 - args: ['ResponseError: code=404, message=The resource "projects/k8s-jkns-pr-gke/zones/us-central1-f/clusters/e2e-gke-agent-pr-67-0" was not found.\nNo cluster named \'e2e-gke-agent-pr-67-0\' in k8s-jkns-pr-gke.']
   exit_code: 1
   message: ResponseError: code=404, message=The resource "projects/k8s-jkns-pr-gke/zones/us-central1-f/clusters/e2e-gke-agent-pr-67-0" was not found.
No cluster named 'e2e-gke-agent-pr-67-0' in k8s-jkns-pr-gke.
```

**Comment by wojtek-t** [comment]
LGTM - thanks

**Comment by apelisse** [comment]
@pwittrock @hongchaodeng @wojtek-t Hi, I wanted to clarify does this fix a bug and why it should be in 1.4? Thanks

**Comment by hongchaodeng** [comment]
https://github.com/kubernetes/kubernetes/pull/31390 fixed some serious resoruce leaking.
@lavalamp reviewed it late when it's already in merging. And there is something left to be fixed as well, e.g. https://github.com/kubernetes/kubernetes/pull/31494

**Comment by apelisse** [comment]
@hongchaodeng Thanks for clarifying

**Comment by lavalamp** [comment]
I actually think this can wait for the pre-1.5-general batch of changes. This is resource leakage that wasn't important until we turned on the etcd3 client in unit tests, and we rolled that back. So this isn't important until we roll that forward again. Correct?

**Comment by lavalamp** [comment]
Oh, wait, that merged already. Haha. OK, this is cleanup I asked for. I agree it should go in if the original change went in.

**Pull request merged**
