### PR TITLE
Remove node termination handler addon

### PR DESCRIPTION
**Pull request by bobbypage**
xref: https://github.com/kubernetes/kubernetes/issues/101285

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

[Graceful Node shutdown](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/) (beta in 1.22) replaces the need for k8s node termination handler. 

It's also not needed to be an explicit addon hosted in k/k since it has a separate [repo](https://github.com/GoogleCloudPlatform/k8s-node-termination-handler/). 

Let's clean it up and remove it from k/k.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by roycaihw** [comment]
This looks good to me. Is it still WIP as the title suggested?

**Comment by bobbypage** [comment]
This is ready to review, removing WIP.

**Comment by endocrimes** [comment]
/lgtm

glad we have first class support for this now 🎉

**Pull request merged**
