### PR TITLE
WIP: add kubectl reverse port forwarding

### LINKED ISSUE #20227: kubectl port-forward container listener to local port
It would be great if `kubectl port-forward` offered the equivalent of `ssh -R`, such that it would open a _listening_ port on the container that forwards to a port on the local machine. I would be perfectly content if that port were only available to the container (i.e. just the 3-tuple `-R` flavor, without `bind_address`; no need to have other containers be able to connect to the port)

Since there is no `kubectl cp` command that I could find, this would make for a painless way to get content into a running container via http from a workstation

### PR DESCRIPTION
**Pull request by vfreex**
**What this PR does / why we need it**:
This adds remote port forwarding feature to kubectl and
kubelet, which means users are able to make a request to a Pod port,
and the request will be forwarded to a local port on the machine running
`kubectl`. 
More information is described in #20227.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #20227

**Special notes for your reviewer**:
Currently, this PR only covers the `kubectl` part:
A new argument `--remote/-r` is introduced to `port-forward`
subcommand. 

For example, if you want to open a listening port `8080` on
the Pod that forwards to port `80` on the local machine, you should run
`kubectl port-forward --remote $POD_NAME 8080:80`.

This is a draft implementation over SPDY tunnels to show it is feasible.
Please help review if this feature and the command line syntax is
reasonable.

Following describes the design of this feature. I'll open a KEP to kubernetes/community for elaborating more details.
1. Whenever a user requests a remote port forwarding, a pair of SPDY channels are established to kubelet. This step is similar to what existing (local) port forwarding function does. The `error` channel is used to transfer error messages between client and server, while the `data` channel is for heartbeats.
2. A Unix domain socket listener is started and waits for connections from the forwarded pod.
3. A `socat` process is started and attached to the network namespace of the forwarded pod. The socat process listens on a TCP port of the pod, and any TCP connections made to the port is forwarded to the Unix domain socket.
4. Whenever the Unix domain socket listener receives a new connection, a new pair of SPDY channels will be initiated to `kubectl`.
5. Whenever a new channel request is received on the client side,  `kubectl` accepts the channels and opens a new TCP connection to the specified `local port`, and forwards traffic between the local port and the `data` channel of the channel pair.
6. When kubelet receives no more heartbeats, the Unix domain socket listener and the `socat` process will be stopped.

**Release note**:

```release-note
kubectl port-forward Pod ports to local ports
```

### CODE REVIEW

**Comment by vfreex** [comment]
The basic functionality of reverse (remote) port forwarding is working now, although there are some issues in current implementation:
1. If new kubectl requests a reverse (remote) port forwarding to a old kubelet, kubelet will do (local) port forwarding.
2. Some interface changes are involved, which should be discussed.
3. rkt is not supported.
4. IPv6 support is not fully supported.
5. local port equals remote port is assumed.
6. SPDY only. WebSocket is not supported.

**Comment by dims** [comment]
@vfreex please rebase or close this.

**Comment by vfreex** [comment]
Thanks for your reminder.
I'll rebase it. Hopefully before the end of this week.

**Comment by ttomsu** [comment]
I'd love to have this functionality

**Comment by discordianfish** [comment]
@vfreex Can you rebase or should I pick up the changes and re-submit them?

**Comment by ttomsu** [comment]
@discordianfish It looks like @vfreex has abandoned this change. Are you still willing to pick it up?

**Comment by vfreex** [comment]
The proof-of-work code for TCP remote port forwarding is completed and rebased. Next, I will open a formal proposal doc to request this feature and describe the design in this PR.
If everything goes fine, I'll break this PR into smaller pieces and file the formal PRs.

**Comment by sjungwirth** [comment]
@vfreex are you still working on this?

**Comment by discordianfish** [comment]
@sjungwirth What needs to be done here?

@vfreex went through the trouble of completing and rebasing this, just to not get any response and have his work closed by a bot. That's such a unfortunate contribution experience..

**Comment by discordianfish** [comment]
Can we somehow make sure this will be actually merged if @vfreex goes through the trouble of rebasing this again?

**Comment by vfreex** [comment]
Update: @shiywang and I will try to confirm streaming based functionalities will be separated from api-server soon or not. If that will happen, we are trying to get reverse port forwarding and UDP forwarding into that separated module

**Comment by aurolle** [comment]
Hi could this be merged?

**Comment by smarterclayton** [comment]
@mikedanese and I have been talking about security and safety related changes to how kubelet to apiserver communication works in light of last months security vulnerability.  Until we have some time to discuss how that might evolve, we want to limit the number of changes made to the related protocols.

For that reason I’m going to put a hold on this - we may decide to remove Spdy altogether and this needs to be a part of that usecase.

Did this get a kep?  I didn’t see a link in here but might have missed it.

/hold

**Comment by nilsonsfj** [comment]
It's been a year... any chance this could be reviewed and merged or similar functionality added somehow?

/remove-lifecycle rotten
/reopen

**Comment by Eriner** [comment]
@smarterclayton as it has been a year, is there any reason to keep this on hold?

>Until we have some time to discuss how that might evolve, we want to limit the number of changes made to the related protocols.

**Pull request closed without merging**
