### PR TITLE
apimachinery: protobuf: Test protobuf compatibility

### LINKED ISSUE #69638: Add test coverage of protobuf compatibility between versions
During review of a [etcd client version upgrade](https://github.com/kubernetes/kubernetes/pull/69322) that also required a gogo/protobuf upgrade, we noticed that we lack of test coverage to ensure that previously serialized protobuf data decodes correctly and changes like this stay wire-compatible. We should aim for our wire protocol compatibility testing should be exhaustive.

### PR DESCRIPTION
**Pull request by emmmmygold**
This patch adds a test which makes sure that protobuf
marshal and unmarshal behave as expected. If protobuf
breaks their api, this test should fail.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #69638 

**Special notes for your reviewer**:

As this is my first pr against k8s, all feedback is greatly appreciated.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jonathangold** [comment]
@yliaog @jpbetz Do one of you want to take a look at this?

**Comment by yliaog** [comment]
the issue  #69638 is to add tests for the encoding/decoding wire level comptability across gogo/protobuf upgrades for *all* kubernetes resources, like pods, services, deployments, etc etc

**Comment by jonathangold** [comment]
> the issue #69638 is to add tests for the encoding/decoding wire level comptability across gogo/protobuf upgrades for _all_ kubernetes resources, like pods, services, deployments, etc etc

Ok, Closing for now. Will open a new one if/when I have the time.

**Pull request closed without merging**
