### PR TITLE
Add Example for Sematext Docker Agent as DaemonSet 

### PR DESCRIPTION
**Pull request by megastef**
More Info about @sematext Docker Agent: https://github.com/sematext/sematext-agent-docker

### CODE REVIEW

**Comment by megastef** [comment]
I signed it!

**Comment by megastef** [comment]
I signed it!

**Comment by megastef** [comment]
I signed it!

**Comment by bgrant0607** [comment]
Thanks for the example.

However, it will be a while before we can merge this, for a few reasons:
* We're doing major surgery on docs and examples, and will probably move them to another repo: #20874
* We're in crunch mode for the 1.2 release, and only critical changes are being merged
* We're trying to figure out conventions for examples: #15193

**Comment by bgrant0607** [comment]
Examples aren't being moved yet.

First cut of example guidelines is in:
https://github.com/kubernetes/kubernetes/blob/master/examples/guidelines.md

We have cut the 1.2 branch, but are still in crunch mode trying to wrap up the release.

I did find the CLA (though personal rather than corporate?), but it appears the last 3 commits were not made under the github account you registered.

cc @kubernetes/examples

**Comment by bgrant0607** [comment]
Also, are you willing to support this example if users report problems, file issues, etc.?

Do you have Kubernetes instructions on your own site / github repo?

**Comment by megastef** [comment]
Yes, I can support this example and and started with initial Kubernetes instructions in Github https://github.com/sematext/sematext-agent-docker#installation-on-kubernetes
Signing the CLA needs a google account, so my Google account was used. The commit was made by accident with a wrong e-mail address from a new Laptop with wrong git settings. I did not recognize it until I pushed the PR here, sorry about that.  Please let me know if I have to change anything. 

This example is very much like other existing Examples (see e.g. NewRelic).

**Comment by bgrant0607** [comment]
@megastef Please squash the commits so that there's just 1 commit under the proper account.

@vishh Could we do something to consolidate the monitoring examples? Maybe under examples/monitoring?

**Comment by bgrant0607** [comment]
Also, please take a look at the examples guidelines. We're trying to improve examples quality and consistency.

**Pull request closed without merging**
