### PR TITLE
nop numbered list in doc to use manual numbering

### PR DESCRIPTION
**Pull request by thockin**
@lavalamp

### CODE REVIEW

**Comment by thockin** [comment]
@krousey for fast merge if @lavalamp OKs

**Comment by krousey** [comment]
@k8s-bot test this

**Comment by lavalamp** [comment]
I really don't like this. I guess I'll hold my nose and LGTM because we can search & replace later.

**Comment by thockin-cc** [comment]
@lavalamp - replace with what?

**Comment by lavalamp** [comment]
I mean, when we fix our html generator to do the lists correctly, we can remove all the `<nop>`s in one go.

**Pull request merged**
