### PR TITLE
Fix broken link to logging documentation

### LINKED ISSUE #39891: This dead link points to another dead link
https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/logging.md

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
Fix a broken link in docs

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #39891 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by calebamiles** [comment]
Could someone from @kubernetes/sig-docs-misc please take a look. Thanks!

**Comment by bgrant0607** [comment]
LGTM thanks

**Comment by bgrant0607** [comment]
@k8s-bot ok to test

**Comment by bgrant0607** [comment]
I'll need to manually merge this once verification checks pass

**Comment by cblecker** [comment]
@bgrant0607 All verification checks have passed!

**Pull request merged**
