### PR TITLE
add verify case in index_test.go

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

There only verify the length of the result in the index_test and we should  also verify the content of the result.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ncdc** [comment]
I feel like we could probably do this a bit cleaner, but maybe it's good enough as-is.

**Comment by ncdc** [comment]
@liggitt @deads2k thoughts?

**Comment by deads2k** [comment]
> I feel like we could probably do this a bit cleaner, but maybe it's good enough as-is.

I may have created a helper to check the values, but I wouldn't press on it.  This improves the test.

**Pull request merged**
