### PR TITLE
Fix minor err in kubeadm

### PR DESCRIPTION
**Pull request by stewart-yu**
**What this PR does / why we need it**:
fix minor text error in kubeadm.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by stewart-yu** [comment]
cc @xiangpengzhao

**Review by jamiehannaford — APPROVED** [review]
/lgtm

**Comment by xiangpengzhao** [comment]
/ok-to-test
in case there is test flake, then you can trigger retesting.
/lgtm as well
/kind cleanup

**Review by luxas — APPROVED** [review]
I'll approve when merge conflict with https://github.com/kubernetes/kubernetes/pull/57139 is fixed :+1:

**Comment by stewart-yu** [comment]
cc @luxas  please help review this PR, thanks

**Comment by xiangpengzhao** [comment]
/lgtm

defer to @luxas for approval :)

**Review by luxas — APPROVED** [review]
/lgtm
/approve no-issue

**Pull request merged**
