### PR TITLE
Correct logic for failing after % of containers fail. #7790

### PR DESCRIPTION
**Pull request by rrati**

### CODE REVIEW

**Comment by brendandburns** [comment]
LGTM, can you update your CLA state?  (I know you already signed, but it would be useful to have the automation work for you...)

Thanks!
--brendan

**Comment by rrati** [comment]
@brendandburns I believe the CLA issue should be resolved now.  Can you re-run the bot?

**Comment by brendandburns** [comment]
Needs gofmt.  (sorry I should have noticed that earlier), thanks for fixing the CLA.

**Comment by rrati** [comment]
Fixed

**Comment by brendandburns** [comment]
Merging on green from Shippable.

**Pull request merged**
