### PR TITLE
Mark deprecated info in short description of deprecated commands.

### LINKED ISSUE #20: Mark deprecated commands in 'kubectl help'
We have several deprecated commands. When running `kubectl help`, we get below (I don't list other commands here).

```
Basic Commands (Beginner):
  run            Run a particular image on the cluster
  run-container  Run a particular image on the cluster

Deploy Commands:
  rolling-update Perform a rolling update of the given ReplicationController
  rollingupdate  Perform a rolling update of the given ReplicationController
  scale          Set a new size for a Deployment, ReplicaSet, Replication Controller, or Job
  resize         Set a new size for a Deployment, ReplicaSet, Replication Controller, or Job

Cluster Management Commands:
  cluster-info   Display cluster info
  clusterinfo    Display cluster info

Advanced Commands:
  replace        Replace a resource by filename or stdin
  update         Replace a resource by filename or stdin
```

For new end-users, they are confused by the different commands with the same usage. They might be not sure which one to use until they get `Command "foo" is deprecated, use "bar" instead`. We need to mark the deprecated commands in the help info.

I will create a PR to mark them in help info. However, I wonder if we still need to keep these deprecated commands. Most of them have been deprecated for a long time. For example, `rollingupdate` was marked in https://github.com/kubernetes/kubernetes/pull/6118 two years ago. We might want to delete them.

@bgrant0607 Do we have deprecation policy for such case?

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Mark deprecated commands in 'kubectl help'. See https://github.com/kubernetes/kubectl/issues/20

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/kubernetes/kubectl/issues/20

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
The output of `kubectl help` is as below.
`run-container  Run a particular image on the cluster. This command is deprecated, use "run" instead`

**Comment by xiangpengzhao** [comment]
/cc @php-coder @fejta @pweil- 
The cc is a test for assignment. Sorry for bothering you guys.

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by xiangpengzhao** [comment]
@k8s-bot pull-kubernetes-kubemark-e2e-gce test this
@k8s-bot pull-kubernetes-unit test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Comment by fabianofranz** [comment]
@k8s-bot pull-kubernetes-unit test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by mengqiy** [comment]
Do we want to get this in 1.7 to improve the help text?

**Comment by fabianofranz** [comment]
@mengqiy desired, but not required.

**Comment by fabianofranz** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Pull request merged**
