### PR TITLE
Update translation files for kubectl patch and replace

### LINKED ISSUE #74339: Link is not working
**What happened**:
I got one link from `kubectl patch --help` but link is not working
error:
```
Error: Cannot load https://raw.githubusercontent.com/kubernetes/kubernetes/HEAD/docs/api-reference/v1/definitions.html: 404 Not Found
```

https://htmlpreview.github.io/?https://github.com/kubernetes/kubernetes/blob/HEAD/docs/api-reference/v1/definitions.html
```
$ kubectl patch --help
Update field(s) of a resource using strategic merge patch, a JSON merge patch, or a JSON patch. 

JSON and YAML formats are accepted. 

Please refer to the models in
https://htmlpreview.github.io/?https://github.com/kubernetes/kubernetes/blob/HEAD/docs/api-reference/v1/definitions.html
to find if a field is mutable.

Examples:
  # Partially update a node using a strategic merge patch. Specify the patch as JSON.
  kubectl patch node k8s-node-1 -p '{"spec":{"unschedulable":true}}'
  
  # Partially update a node using a strategic merge patch. Specify the patch as YAML.
  kubectl patch node k8s-node-1 -p $'spec:\n unschedulable: true'
  
  # Partially update a node identified by the type and name specified in "node.json" using strategic merge patch.
  kubectl patch -f node.json -p '{"spec":{"unschedulable":true}}'
  
  # Update a container's image; spec.containers[*].name is required because it's a merge key.
  kubectl patch pod valid-pod -p '{"spec":{"containers":[{"name":"kubernetes-serve-hostname","image":"new image"}]}}'
  
  # Update a container's image using a json patch with positional arrays.
  kubectl patch pod valid-pod --type='json' -p='[{"op": "replace", "path": "/spec/containers/0/image", "value":"new
image"}]'
```

**What you expected to happen**:

It need to show some info!!

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**

/kind bug
/kind cleanup
/kind documentation

**What this PR does / why we need it**:
Update translation files for `kubectl patch` and `kubectl replace` .
Remove the invalid links :
```
https://github.com/kubernetes/kubernetes/blob/HEAD/docs/api-reference/v1/definitions.html
```

**Which issue(s) this PR fixes**:
Fixes #74339

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mattjmcnaughton** [comment]
I"m not sure if I'm just missing something with Git, but I'm not seeing these links included in the `patch.go` or `replace.go` in the current master.

Additionally, I see this commit reflected in the Github history from https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/patch/patch.go... even though it hasn't been merged.

I'm pretty confused about what's going on :) Any insights?

**Comment by SataQiu** [comment]
@mattjmcnaughton Although these links have been removed from `replace.go` and `patch.go`, the translation files have not been updated now. I resubmitted to update these files.

**Pull request closed without merging**
