### PR TITLE
fix S1017 and S1002 in pkg/apis/core/validation/validation.go

### PR DESCRIPTION
**Pull request by shawnhanx**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
fix:
pkg/apis/core/validation/validation.go:3182:4: should replace this if statement with an unconditional strings.TrimSuffix (S1017)
pkg/apis/core/validation/validation.go:6323:6: should omit comparison to bool constant, can be simplified to !hostNetwork (S1002)

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/assign @smarterclayton @thockin 

NOTE: easy review, just a few lines (fixing something that linter is telling them to)

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
