### PR TITLE
Clean-up CoreOS documentation.

### PR DESCRIPTION
**Pull request by pires**
Removed deprecated and unmaintained AWS + CoreOS docs in favor of `coreos/coreos_multinode_cluster.md`. Refs #11975

Removed deprecated and unmaintained fork of pires/kubernetes-vagrant-coreos-cluster linked in the docs.
Removed deprecated and unmaintained VMware + CoreOS section of `coreos/coreos_multinode_cluster.md`. Refs #13143
Refs #9178

### CODE REVIEW

**Comment by yujuhong** [comment]
Please rerun hack/update-generated-docs.sh. Thanks.

**Comment by pires** [comment]
@yujuhong done.

**Comment by erictune** [comment]
LGTM.  Thanks for the cleanup!

**Pull request merged**
