### PR TITLE
Eliminate MaintainObservations function in P&F

### PR DESCRIPTION
**Pull request by wojtek-t**
```release-note
NONE
```

/kind cleanup
/priority important-longterm
/sig api-machinery

/assign @MikeSpreitzer

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
It goes deeper than this. We can delete the UpdateObservations method of the QueueSet interface.  A TimingHistogram does not need any external maintenance.

**Comment by wojtek-t** [comment]
> It goes deeper than this. We can delete the UpdateObservations method of the QueueSet interface. A TimingHistogram does not need any external maintenance.

Yeah I know. Just found that in my working directory and opened a PR from it.
But I'm happy to make this step further before merging it - let me take a look at it soon.

**Comment by wojtek-t** [comment]
@MikeSpreitzer - PTAL

[there are a bit more cleanups I would like to do, but I'm not sure I get to them before 1.25 codefreeze]

**Review by MikeSpreitzer — APPROVED** [review]
/LGTM
Thanks!

**Pull request merged**
