### PR TITLE
Automated cherry pick of #61926: Update libcontainer to include PRs with fixes to systemd

### PR DESCRIPTION
**Pull request by filbranden**
Cherry pick of #61926 on release-1.10.

#61926: Update libcontainer to include PRs with fixes to systemd

### CODE REVIEW

**Comment by filbranden** [comment]
/retest

Not sure what needs to be done about "do-not-merge/cherry-pick-not-approved" ...

**Comment by filbranden** [comment]
/assign @cblecker 
(Who has OWNERS and approved the original PR.)

**Comment by cblecker** [comment]
I can approve for Godeps, but @derekwaynecarr will have to approve that this is worthwhile to cherry pick back to 1.10.

**Comment by filbranden** [comment]
@derekwaynecarr Can you please take a look?

The main reason I'm proposing this gets backported in 1.10 is that when the 1.10 branch was cut, our vendored libcontainer included opencontainers/runc#1683 and as such kubelet startup will **hang** when running with the systemd cgroup driver.

Backporting all the subsequent fixes to libcontainer should fix that in 1.10 as well.

Cheers,
Filipe

**Comment by filbranden** [comment]
Need to remove the labels (`do-not-merge/cherry-pick-not-approved`, etc.)... @cblecker can you please do that? Thanks!

**Comment by cblecker** [comment]
No further action needed on your part :)

@derekwaynecarr Does this need a release note?

**Comment by MaciekPytel** [comment]
If this fixes a bug where kubelet could hang in some scenario, I think it's worth adding a release note so the users who run into the bug know it's been fixed in a patch release.

@filbranden Can you add a release note to the base PR (#61926)? It will be automatically used for cherrypick.

**Comment by filbranden** [comment]
> Can you add a release note to the base PR (#61926)? It will be automatically used for cherrypick.

Sure... How do I do that?

**Comment by MaciekPytel** [comment]
Just edit your initial message on that PR, replacing NONE in relase note section with actual release note.

**Comment by filbranden** [comment]
Ah, of course... Done now!

**Comment by MaciekPytel** [comment]
Thanks. I guess the bot should notice that there is a release note and remove the do-not-merge label. If not I'll just remove it manually tomorrow. Either way this PR should be good to go, no further action needed on your side.

**Comment by filbranden** [comment]
Thank you @MaciekPytel !

**Pull request merged**
