### PR TITLE
Use buildx in favor of `FROM --platform` syntax

### PR DESCRIPTION
**Pull request by saschagrunert**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

The container images we build can use `docker buildx` instead of the `FROM --platform` syntax.
**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:
None
**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Did a little test with building a release with my user fork in GCB, and it seems to work seamlessly:
```
+++ [0128 15:31:45] Starting docker build for image: kube-apiserver-amd64
+++ [0128 15:31:45] Starting docker build for image: kube-controller-manager-amd64
+++ [0128 15:31:45] Starting docker build for image: kube-scheduler-amd64
+++ [0128 15:31:45] Starting docker build for image: kube-proxy-amd64
+++ [0128 15:31:45] Building conformance image for arch: amd64
+++ [0128 15:32:01] Building tarball: node linux-arm
+++ [0128 15:32:04] Deleting docker image k8s.gcr.io/kube-scheduler-amd64:v1.21.0-alpha.3
+++ [0128 15:32:04] Deleting docker image k8s.gcr.io/kube-controller-manager-amd64:v1.21.0-alpha.3
+++ [0128 15:32:04] Deleting docker image k8s.gcr.io/kube-proxy-amd64:v1.21.0-alpha.3
+++ [0128 15:32:04] Deleting docker image k8s.gcr.io/kube-apiserver-amd64:v1.21.0-alpha.3
+++ [0128 15:32:10] Deleting conformance image k8s.gcr.io/conformance-amd64:v1.21.0-alpha.3
+++ [0128 15:32:10] Docker builds done
+++ [0128 15:32:10] Building images: linux-arm
+++ [0128 15:32:10] Starting docker build for image: kube-apiserver-arm
+++ [0128 15:32:10] Starting docker build for image: kube-controller-manager-arm
+++ [0128 15:32:10] Starting docker build for image: kube-scheduler-arm
+++ [0128 15:32:10] Starting docker build for image: kube-proxy-arm
+++ [0128 15:32:10] Building conformance image for arch: arm
+++ [0128 15:32:14] Building tarball: node linux-arm64
+++ [0128 15:32:23] Deleting docker image k8s.gcr.io/kube-scheduler-arm:v1.21.0-alpha.3
+++ [0128 15:32:23] Deleting docker image k8s.gcr.io/kube-controller-manager-arm:v1.21.0-alpha.3
+++ [0128 15:32:23] Deleting docker image k8s.gcr.io/kube-apiserver-arm:v1.21.0-alpha.3
+++ [0128 15:32:23] Deleting docker image k8s.gcr.io/kube-proxy-arm:v1.21.0-alpha.3
+++ [0128 15:32:29] Deleting conformance image k8s.gcr.io/conformance-arm:v1.21.0-alpha.3
+++ [0128 15:32:29] Docker builds done
+++ [0128 15:32:29] Building images: linux-arm64
+++ [0128 15:32:29] Building tarball: node linux-s390x
+++ [0128 15:32:29] Starting docker build for image: kube-apiserver-arm64
+++ [0128 15:32:29] Starting docker build for image: kube-controller-manager-arm64
+++ [0128 15:32:29] Starting docker build for image: kube-scheduler-arm64
+++ [0128 15:32:29] Starting docker build for image: kube-proxy-arm64
+++ [0128 15:32:29] Building conformance image for arch: arm64
+++ [0128 15:32:42] Deleting docker image k8s.gcr.io/kube-scheduler-arm64:v1.21.0-alpha.3
+++ [0128 15:32:42] Deleting docker image k8s.gcr.io/kube-controller-manager-arm64:v1.21.0-alpha.3
+++ [0128 15:32:42] Deleting docker image k8s.gcr.io/kube-apiserver-arm64:v1.21.0-alpha.3
+++ [0128 15:32:42] Deleting docker image k8s.gcr.io/kube-proxy-arm64:v1.21.0-alpha.3
+++ [0128 15:32:48] Building tarball: node linux-ppc64le
+++ [0128 15:32:48] Deleting conformance image k8s.gcr.io/conformance-arm64:v1.21.0-alpha.3
+++ [0128 15:32:49] Docker builds done
+++ [0128 15:32:49] Building images: linux-s390x
+++ [0128 15:32:49] Starting docker build for image: kube-apiserver-s390x
+++ [0128 15:32:49] Starting docker build for image: kube-controller-manager-s390x
+++ [0128 15:32:49] Starting docker build for image: kube-scheduler-s390x
+++ [0128 15:32:49] Starting docker build for image: kube-proxy-s390x
+++ [0128 15:32:49] Building conformance image for arch: s390x
+++ [0128 15:33:02] Deleting docker image k8s.gcr.io/kube-scheduler-s390x:v1.21.0-alpha.3
+++ [0128 15:33:03] Deleting docker image k8s.gcr.io/kube-controller-manager-s390x:v1.21.0-alpha.3
+++ [0128 15:33:03] Deleting docker image k8s.gcr.io/kube-apiserver-s390x:v1.21.0-alpha.3
+++ [0128 15:33:03] Deleting docker image k8s.gcr.io/kube-proxy-s390x:v1.21.0-alpha.3
+++ [0128 15:33:03] Building tarball: node windows-amd64
+++ [0128 15:33:10] Deleting conformance image k8s.gcr.io/conformance-s390x:v1.21.0-alpha.3
+++ [0128 15:33:10] Docker builds done
+++ [0128 15:33:10] Building images: linux-ppc64le
+++ [0128 15:33:10] Starting docker build for image: kube-apiserver-ppc64le
+++ [0128 15:33:10] Starting docker build for image: kube-controller-manager-ppc64le
+++ [0128 15:33:10] Starting docker build for image: kube-scheduler-ppc64le
+++ [0128 15:33:10] Starting docker build for image: kube-proxy-ppc64le
+++ [0128 15:33:10] Building conformance image for arch: ppc64le
+++ [0128 15:33:23] Deleting docker image k8s.gcr.io/kube-scheduler-ppc64le:v1.21.0-alpha.3
+++ [0128 15:33:23] Deleting docker image k8s.gcr.io/kube-controller-manager-ppc64le:v1.21.0-alpha.3
+++ [0128 15:33:23] Deleting docker image k8s.gcr.io/kube-apiserver-ppc64le:v1.21.0-alpha.3
+++ [0128 15:33:26] Deleting docker image k8s.gcr.io/kube-proxy-ppc64le:v1.21.0-alpha.3
+++ [0128 15:33:30] Deleting conformance image k8s.gcr.io/conformance-ppc64le:v1.21.0-alpha.3
+++ [0128 15:33:30] Docker builds done
+++ [0128 15:33:30] Building tarball: server linux-amd64
+++ [0128 15:34:25] Building tarball: server linux-arm
+++ [0128 15:35:10] Building tarball: server linux-arm64
+++ [0128 15:36:00] Building tarball: server linux-s390x
+++ [0128 15:37:02] Building tarball: server linux-ppc64le
+++ [0128 15:37:52] Building tarball: final
+++ [0128 15:37:56] Starting tarball: test linux-amd64
+++ [0128 15:37:56] Starting tarball: test linux-arm
+++ [0128 15:37:56] Starting tarball: test linux-arm64
+++ [0128 15:37:56] Starting tarball: test linux-ppc64le
+++ [0128 15:37:56] Starting tarball: test darwin-amd64
+++ [0128 15:37:56] Starting tarball: test linux-s390x
+++ [0128 15:37:56] Starting tarball: test windows-amd64
```

**Comment by saschagrunert** [comment]
This is ready for review. PTAL @justaugustus @lavalamp @spiffxp

cc @kubernetes/release-engineering

**Review by hasheddan — COMMENTED** [review]
@saschagrunert do you think it would make sense to switch over test images and other non-release artifact images to using buildx as well here? That would avoid an intermediate state of having some built using "traditional" method and some with buildx. That being said, I would really like for all of the image building in release pipeline to go ahead and transition, so I would be in favor of pushing this forward.

**Comment by justaugustus** [comment]
Great cleanup, Sascha!
/lgtm
/approve

**Comment by hasheddan** [comment]
> anything that we build ideally builds with docker buildx

@justaugustus does we here imply release team, or k8s in general? I think after this PR the only gaps would be test / cluster images

**Comment by justaugustus** [comment]
> @justaugustus does we here imply release team, or k8s in general? I think after this PR the only gaps would be test / cluster images

Yeppers, sorry for the ambiguity!
We == RelEng, so primarily images that we maintain in k/release and in k/k/build.

We can fix up test/ and cluster/, but I'd say check-in w/ OWNERS first.
(There are already PRs in-flight for a few image changes in both dirs.)

**Comment by saschagrunert** [comment]
> -q option is not supported by docker buildx and this produces the following warning
> 
> ```
> WARN[0000] quiet currently not implemented.
> ```
> 
> Should we just remove it?

Yes, I'm following up on that in https://github.com/kubernetes/kubernetes/pull/98568

**Pull request merged**
