### PR TITLE
Ephemeral storage quota cleanup

### PR DESCRIPTION
**Pull request by RobertKrawitz**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Cleans up some leftover nits from #66928 

**Does this PR introduce a user-facing change?**: no

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

thanks for making these clean up changes - agree `fsquota` is a clearer name :)

**Review by saad-ali — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
