### PR TITLE
start cadvisor manager after initialization

### LINKED ISSUE #48452: storage.kubernetes.io/scratch is always kept 0
**Is this a BUG REPORT or FEATURE REQUEST?**: 

/kind bug

**What happened**:

When LocalStorageCapacityIsolation feature is enabled, `storage.kubernetes.io/scratch` in node status is always kept 0.

**What you expected to happen**:

`storage.kubernetes.io/scratch` in node status should reflect the real storage capacity.

**How to reproduce it (as minimally and precisely as possible)**:

Enable LocalStorageCapacityIsolation feature and run 

```sh
kubectl describe node | grep storage.kubernetes.io/scratch
```

**Anything else we need to know?**:

Advisor reports error on calling `cadvisorInterface.RootFsInfo()` (refer [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/container_manager_linux.go#L228)): `unable to find data for container /`

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7
- Cloud provider or hardware configuration**: no
- OS (e.g. from /etc/os-release): Ubuntu Xenial
- Kernel (e.g. `uname -a`): 4.8
- Install tools: kubeadm

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

The cadvisor manager did not get started after initialization. So `obj.manager.memoryCache` kept nil.

**Which issue this PR fixes** : fixes #48452 

**Special notes for your reviewer**:

cc @feiskyer @k82cn 

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by feiskyer** [comment]
@dixudx Thanks for the fix.

**Comment by dixudx** [comment]
@feiskyer waiting your approval. Thanks.

**Comment by feiskyer** [comment]
Hmm, advisor manager has already started [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1247). With this fix, it will be started twice, which is not expected.

#48567 introduced another way to fix the problem, which seems more reasonable.

**Comment by dixudx** [comment]
@feiskyer Thanks for pointing out. Close this PR in favor of #48567

**Pull request closed without merging**
