### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by u2takey**
**What this PR does / why we need it**:
Fix typos in package tunneler.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
Not sure why bot doesn't label `cncf-cla`. @u2takey Can you confirm that if your CLA has been signed?

I sent an issue in test-infra for this. https://github.com/kubernetes/test-infra/issues/4069

**Comment by u2takey** [comment]
@xiangpengzhao  i found my closed pr here https://github.com/kubernetes/kubernetes/pull/50652 get cncf-cla:yes. (that is same pr, closed because i changeed commit author email), should i reopen 50652, or close all and reopen a new one?

**Comment by u2takey** [comment]
Bump to verify CLA

**Comment by xiangpengzhao** [comment]
reopen that PR would be ok, IMO.

**Comment by u2takey** [comment]
@xiangpengzhao  changed commit id, ok now, thanks

**Comment by xiangpengzhao** [comment]
Great!

/ok-to-test
/lgtm

**Comment by xiangpengzhao** [comment]
/assign @nikhiljindal
for approval. Thanks!

**Comment by u2takey** [comment]
@nikhiljindal, need approval, tks.

**Comment by xiangpengzhao** [comment]
ping @nikhiljindal for approval. thanks!

**Comment by dims** [comment]
@xiangpengzhao @u2takey looks like a bazel failure needs to be fixed

**Comment by u2takey** [comment]
@dims ok now

**Comment by u2takey** [comment]
ping @dims  for approval. thanks

**Comment by u2takey** [comment]
ping @nikhiljindal for approval. thanks!

**Comment by spiffxp** [comment]
friendly v1.8 release ping

/unassign @nikhiljindal 
/assign @sttts
for the `/approve no-issue`, looked at github activity for approvers in the listed OWNERS file

**Pull request merged**
