### PR TITLE
Fix some env variable settings in test config.

### PR DESCRIPTION
**Pull request by andyzheng0831**
These environmental variables are incorrectly set to string "TEST_CLUSTER_LOG_LEVEL", instead of the value of the variable "${TEST_CLUSTER_LOG_LEVL}".

### CODE REVIEW

**Comment by andyzheng0831** [comment]
cc/ @dchen1107 cc/ @yinghan cc/ @wonderfly cc/ @roberthbailey

**Comment by roberthbailey** [comment]
@k8s-bot add to whitelist

**Comment by roberthbailey** [comment]
@gmarek (who added this) and @bprashanth (who reviewed it)

**Comment by andyzheng0831** [comment]
Seems like shippable failure is not related with my change. Can on-call restart it? Thanks.

**Comment by roberthbailey** [comment]
I just restarted it for you.

**Pull request merged**
