### PR TITLE
test/e2e: fix the OIDC discovery test with ECDSA service account key

### LINKED ISSUE #100674: e2e test OIDC discovery fails with ECDSA service account key
#### What happened:

e2e test `[sig-auth] ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]` fails with ECDSA Service Account key

#### What you expected to happen:

e2e test to succeed with ECDSA Service Account key

#### How to reproduce it (as minimally and precisely as possible):

Use ECDSA key for the service account key.

#### Anything else we need to know?:

Logs from the started test container:

```
2021/03/30 14:13:47 OK: Got token
2021/03/30 14:13:47 OK: got issuer https://172.20.0.1:6443
2021/03/30 14:13:47 Full, not-validated claims: 
openidmetadata.claims{Claims:jwt.Claims{Issuer:"https://172.20.0.1:6443", Subject:"system:serviceaccount:svcaccounts-4993:default", Audience:jwt.Audience{"oidc-discovery-test"}, Expiry:1617114224, NotBefore:1617113624, IssuedAt:1617113624, ID:""}, Kubernetes:openidmetadata.kubeClaims{Namespace:"svcaccounts-4993", ServiceAccount:openidmetadata.kubeName{Name:"default", UID:"d28680f5-302a-4824-95cd-46dc0fbf8018"}}}
2021/03/30 14:13:47 OK: Constructed OIDC provider for issuer https://172.20.0.1:6443
2021/03/30 14:13:47 oidc: id token signed with unsupported algorithm, expected ["RS256"] got "ES256"
```

`go-oidc` library defaults to `RS256` by default as the only supported method while `ES256` should be added explicitly: https://pkg.go.dev/github.com/coreos/go-oidc/v3/oidc#Config

Relevant code: https://github.com/kubernetes/kubernetes/blob/master/test/images/agnhost/openidmetadata/openidmetadata.go#L100

On the API server side:

```
$ curl -k --cert client.crt --key client.key  https://172.20.0.2:6443/.well-known/openid-configuration
{"issuer":"https://172.20.0.1:6443","jwks_uri":"https://172.20.0.1:6443/openid/v1/jwks","response_types_supported":["id_token"],"subject_types_supported":["public"],"id_token_signing_alg_values_supported":["ES256"]}
```

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21.0-rc.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Talos
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by smira**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

Fixes the e2e test with ECDSA service account key.

By default oidc library enables only `RS256` signature validation
method.

#### Which issue(s) this PR fixes:

Fixes #100674

#### Does this PR introduce a user-facing change?

```release-note
Fixes an overly restrictive conformance test to accept service account tokens signed by an ECDSA key
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
the immediate change looks good
/lgtm
/approve
/assign @mtaufen 

does this also need to bump test/images/agnhost/VERSION? once merged, and the agnhost image built and pushed, a second PR to update the agnhost image version used

/hold for agnhost version staging instructions

**Comment by aojea** [comment]
@smira you have an example here of the files that you need to modify in this PR
https://github.com/kubernetes/kubernetes/pull/98639/files?file-filters%5B%5D=.go
build/dependencies.yaml
test/images/agnhost/VERSION
test/images/agnhost/agnhost.go

**Comment by smira** [comment]
the documentation is a bit confusing on bumping image versions, should I bump version for agnhost image like in #99860 ? or should I wait for some image promotion process first?

**Comment by aojea** [comment]
> the documentation is a bit confusing on bumping image versions, should I bump version for agnhost image like in #99860 ? or should I wait for some image promotion process first?

yeah, like that PR ... then there is a postsubmit job that will generate the new image.
The new image has to be promoted in k8s.io repo
Once the new image is available, another PR here

**Comment by smira** [comment]
re-pushed with image version bumped for agnhost

**Comment by dims** [comment]
Once this lands, you will need to promote like @aojea said:
https://github.com/kubernetes/k8s.io/pull/1809/files

followed by:
https://github.com/kubernetes/kubernetes/commit/42011ecfe43f02a1775f095310ca8be1d79f2e12

**Comment by dims** [comment]
Also please cherry pick to release-1.21 branch as this needs to be in that branch.

**Comment by smira** [comment]
looks like postsubmit job failed, not sure how to restart it: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-agnhost-test-images/1377002984130482176

**Comment by aojea** [comment]
I did restart it, ping dims or I if it fails again,

**Comment by smira** [comment]
@aojea looks like failed once again https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-agnhost-test-images/1377006048765808640

**Comment by dims** [comment]
i tried again, still failed. https://prow.k8s.io/?repo=kubernetes%2Fkubernetes&job=post-kubernetes-push-e2e-agnhost-test-images

We need to check with @claudiubelu @BenTheElder etc

**Comment by dims** [comment]
@smira looks like it succeeded now!

**Comment by smira** [comment]
Looks like it finally succeeded, I'll get promote image PR soon

**Comment by dims** [comment]
verified using:
```skopeo inspect --raw docker://gcr.io/k8s-staging-e2e-test-images/agnhost:2.31```
```docker pull gcr.io/k8s-staging-e2e-test-images/agnhost:2.31```

**Comment by BenTheElder** [comment]
s390x flakes :|
at least it eventually built ...

**Pull request merged**
