### PR TITLE
Add SIG ownership to controller/nodelifecycle

### LINKED ISSUE #116771: Define ownership of controller/nodelifecycle
/kind cleanup
/kind documentation

/sig scheduling
/sig node
/sig apps

The ownership of controller/nodelifecycle is unclear.

The [OWNERS file of pkg/controller/nodelifecycle](https://github.com/kubernetes/kubernetes/blob/15894cfc85cab64df081bb753b8ccf32a243da68/pkg/controller/nodelifecycle/OWNERS) currently has some individual names and no labels, although it gets a sig/apps label from the parent pkg/controller OWNERS.

This controller has the following functionality:
- Add taints based on health of the node (from conditions)
- Evict Pods based on NoExecute taints.

The candidates for long term ownership are:
1. Scheduling: The ones who introduced it and overall maintain taints and tolerations.
2. Node: Because it's called "node lifecycle", although this could be a misnomer.
3. Apps: Due to implications to the lifecycle of applications and because they are the main shepherds of kcm.

I think it makes the most sense under scheduling, but wanted to gather all stakeholder's feedback.

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Add the following ownership:

- SIG Node: Setting taints based on Node conditions
- SIG Scheduling: Evicting pods that don't tolerate NoExecute taints

#### Which issue(s) this PR fixes:

Fixes #116771 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
cc @bowei @k82cn @smarterclayton @ingvagabund as current reviewers/approvers

**Comment by alculquicondor** [comment]
cc @kubernetes/sig-scheduling-leads @kubernetes/sig-node-leads as new owners

**Comment by aojea** [comment]
> /hold for a bit of review, will unhold tomorrow afternoon

/hold cancel 

😄

**Comment by aojea** [comment]
/hold

I miss some node folks

**Comment by aojea** [comment]
@smarterclayton I let you handle it , sorry for the intrusion :)

**Pull request merged**
