### PR TITLE
Fix duplicate port name within pod

### LINKED ISSUE #122150: Ports with duplicate names should not be allowed to exist in the pod.
### What happened?

The same port name exists in the pod, but it is not allowed in the document.

https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#ports

image

image

### What did you expect to happen?

Each named port in a pod must have a unique name.

### How can we reproduce it (as minimally and precisely as possible)?

I think it can't be repaired and there will be problems with upgrading.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

v1.25.8

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by HirazawaUi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
If a pod has multiple containers with the same port name, the pod will be allowed to be created, we should reject this behavior during the validation.

#### Which issue(s) this PR fixes:

Fixes #122150

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
Thanks for the PR, but unfortunately this is not a backwards compatible change and would break applications that are currently working properly. 

We should update the documentation to *recommend* the name be unique and document what the actual uniqueness requirements are

/close

**Comment by HirazawaUi** [comment]
That is, this could be a permanent bug, but we won't make a fix for it to ensure backwards compatibility?

If we need to change the documentation to indicate that it is only suggesting that the name is unique, do we need to change the api documentation? or just the website documentation?

**Comment by liggitt** [comment]
We should change the API and website documentation, and describe the things that may not work as desired if there are duplicate named ports in a pod

**Pull request closed without merging**
