### PR TITLE
Add Deployment conformance tests

### PR DESCRIPTION
**Pull request by janetkuo**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**: @kubernetes/sig-apps-pr-reviews @kubernetes/sig-architecture-pr-reviews 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by timothysc** [comment]
/lgtm 
/assign @smarterclayton @bgrant0607 @spiffxp @jdumars  

Requires sig-arch approval.

**Comment by bgrant0607** [comment]
/approve

@janetkuo Why were some of the tests not added? Are they not stable?

**Pull request merged**
