### PR TITLE
e2e:remove func of framework/replicaset to e2e/upgrades/apps/replicas…

### PR DESCRIPTION
**Pull request by yuxiaobo96**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

remove func of framework/replicaset to /upgrades/apps/replicasets.go

**Which issue(s) this PR fixes**:

Ref #86052 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by yuxiaobo96** [comment]
/cc @SataQiu 
Please help me check when you are free.
:)

**Review by SataQiu — COMMENTED** [review]
Thanks @yuxiaobo96 
/lgtm
/approve

**Comment by bskiba** [comment]
sig-autoscaling tests have been using the NewReplicaSet function, which seems to be quite generic:
https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/e2e/v1/actuation.go#L512

We're updating our dependencies from 1.16 to 1.18, so now we will have to duplicate this functionality.

**Pull request merged**
