### PR TITLE
Added ISCSI to PV structs

### PR DESCRIPTION
**Pull request by markturansky**
@thockin similar to #7564, this adds ISCSI to PV.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
LGTM

**Comment by thockin** [comment]
LGTM

**Comment by markturansky** [comment]
Travis came back green.  One of the tests flaked last time.

**Comment by ArtfulCoder** [comment]
According the shippable, the build is failing. @markturansky can you take a look ?

**Comment by markturansky** [comment]
I have no insight into the shippable build.  Can you tell me what went wrong?

**Comment by ArtfulCoder** [comment]
```
./hack/build-go.sh
+++ [0507 18:52:35] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    cmd/hyperkube
    cmd/kubernetes
    plugin/cmd/kube-scheduler
    cmd/kubectl
    cmd/e2e
    cmd/integration
    cmd/gendocs
    cmd/genman
    cmd/genbashcomp
    examples/k8petstore/web-server
    github.com/onsi/ginkgo/ginkgo
# github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1beta3
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1beta3/conversion_generated.go:2256: in.NFS undefined (type *PersistentVolumeSource has no field or method NFS)
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1beta3/conversion_generated.go:2257: out.NFS undefined (type *api.PersistentVolumeSource has no field or method NFS)
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1beta3/conversion_generated.go:2258: in.NFS undefined (type *PersistentVolumeSource has no field or method NFS)
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1beta3/conversion_generated.go:2258: out.NFS undefined (type *api.PersistentVolumeSource has no field or method NFS)
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1beta3/conversion_generated.go:2262: out.NFS undefined (type *api.PersistentVolumeSource has no field or method NFS)
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1beta3/conversion_generated.go:2303: in.NFS undefined (type *api.PersistentVolumeSource has no field or method NFS)
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1beta3/conversion_generated.go:2304: out.NFS undefined (type *PersistentVolumeSource has no field or method NFS)
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1beta3/conversion_generated.go:2305: in.NFS undefined (type *api.PersistentVolumeSource has no field or method NFS)
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1beta3/conversion_generated.go:2305: out.NFS undefined (type *PersistentVolumeSource has no field or method NFS)
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1beta3/conversion_generated.go:2309: out.NFS undefined (type *PersistentVolumeSource has no field or method NFS)
_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1beta3/conversion_generated.go:2309: too many errors
!!! Error in /root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:341
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${nonstatics[@]:+${nonstatics[@]}}"' exited with status 2
Call stack:
  1: /root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:341 kube::golang::build_binaries_for_platform(...)
  2: /root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:466 kube::golang::build_binaries(...)
  3: ./hack/build-go.sh:26 main(...)
Exiting with status 1
!!! Error in /root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:384
  'kube::golang::build_binaries "$@"' exited with status 1
Call stack:
  1: /root/workspace/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:384 kube::golang::build_binaries(...)
  2: ./hack/build-go.sh:26 main(...)
Exiting with status 1
``

**Comment by markturansky** [comment]
ah, i see.  conversion generation fun and mixup with the NFS branch.

**Comment by markturansky** [comment]
Rebased and regenerated conversions.  Waiting for green.

**Comment by ArtfulCoder** [comment]
Shippable still fails:
```
 PATH=$HOME/gopath/bin:./third_party/etcd:$PATH ./hack/test-cmd.sh
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified

etcd -data-dir /tmp/test-etcd.F7WYFr --bind-addr 127.0.0.1:4001 >/dev/null 2>/dev/null

Waiting for etcd to come up.
+++ [0507 22:31:03] etcd:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100    87  100    87    0     0     73      0  0:00:01  0:00:01 --:--:--    73
100    87  100    87    0     0     73      0  0:00:01  0:00:01 --:--:--    73
{"action":"set","node":{"key":"/_test","value":"","modifiedIndex":3,"createdIndex":3}}
+++ [0507 22:31:04] Running kubectl with no options
kubectl controls the Kubernetes cluster manager.

Find more information at https://github.com/GoogleCloudPlatform/kubernetes.

Usage: 
  kubectl [flags]
  kubectl [command]

Available Commands: 
  get            Display one or many resources
  describe       Show details of a specific resource
  create         Create a resource by filename or stdin
  update         Update a resource by filename or stdin.
  delete         Delete a resource by filename, stdin, resource and ID, or by resources and label selector.
  namespace      SUPERCEDED: Set and view the current Kubernetes namespace
  log            Print the logs for a container in a pod.
  rolling-update Perform a rolling update of the given ReplicationController.
  resize         Set a new size for a Replication Controller.
  exec           Execute a command in a container.
  port-forward   Forward one or more local ports to a pod.
  proxy          Run a proxy to the Kubernetes API server
  run-container  Run a particular image on the cluster.
  stop           Gracefully shut down a resource by id or filename.
  expose         Take a replicated application and expose it as Kubernetes Service
  label          Update the labels on a resource
  config         config modifies kubeconfig files
  cluster-info   Display cluster info
  api-versions   Print available API versions.
  version        Print the client and server version information.
  help           Help about any command

Flags:
      --alsologtostderr=false: log to standard error as well as files
      --api-version="": The API version to use when talking to the server
  -a, --auth-path="": Path to the auth info file. If missing, prompt the user. Only used if using https.
      --certificate-authority="": Path to a cert. file for the certificate authority.
      --client-certificate="": Path to a client key file for TLS.
      --client-key="": Path to a client key file for TLS.
      --cluster="": The name of the kubeconfig cluster to use
      --context="": The name of the kubeconfig context to use
  -h, --help=false: help for kubectl
      --insecure-skip-tls-verify=false: If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure.
      --kubeconfig="": Path to the kubeconfig file to use for CLI requests.
      --log_backtrace_at=:0: when logging hits line file:N, emit a stack trace
      --log_dir=: If non-empty, write log files in this directory
      --log_flush_frequency=5s: Maximum number of seconds between log flushes
      --logtostderr=true: log to standard error instead of files
      --match-server-version=false: Require server version to match client version
      --namespace="": If present, the namespace scope for this CLI request.
      --password="": Password for basic authentication to the API server.
  -s, --server="": The address and port of the Kubernetes API server
      --stderrthreshold=2: logs at or above this threshold go to stderr
      --token="": Bearer token for authentication to the API server.
      --user="": The name of the kubeconfig user to use
      --username="": Username for basic authentication to the API server.
      --v=0: log level for V logs
      --validate=false: If true, use a schema to validate the input before sending it
      --vmodule=: comma-separated list of pattern=N settings for file-filtered logging


Use "kubectl help [command]" for more information about a command.

+++ [0507 22:31:04] Starting kubelet in masterless mode
W0507 22:31:04.647618    1147 server.go:346] Could not load kubernetes auth path: stat /var/lib/kubelet/kubernetes_auth: no such file or directory. Continuing with defaults.
I0507 22:31:04.647818    1147 server.go:236] Using root directory: /tmp/kubelet.1088
I0507 22:31:04.648158    1147 manager.go:113] cAdvisor running in container: "/docker/fa0a2d0f5bc084da2633fdbfdc8cc5c6afcece5efc655e1bd61c9ddfd5e0626c"
I0507 22:31:04.648881    1147 fs.go:87] Filesystem partitions: map[/dev/disk/by-label/DOROOT:{mountpoint:/ds major:253 minor:1}]
I0507 22:31:04.683945    1147 machine.go:223] Couldn't collect info from any of the files in "/etc/machine-id,/var/lib/dbus/machine-id"
I0507 22:31:04.684089    1147 manager.go:134] Machine: {NumCores:16 CpuFrequency:2399998 MemoryCapacity:50650255360 MachineID: SystemUUID:C534616D-F1A7-43C0-B92E-C69F3EDB0E37 BootID:28104c8f-4958-4b7e-83e2-be56270ca18d Filesystems:[{Device:/dev/disk/by-label/DOROOT Capacity:507172954112}] DiskMap:map[253:0:{Name:vda Major:253 Minor:0 Size:515396075520 Scheduler:none}] NetworkDevices:[{Name:eth0 MacAddress:02:42:ac:11:17:d3 Speed:10000 Mtu:1500}] Topology:[{Id:0 Memory:50650255360 Cores:[{Id:0 Threads:[0] Caches:[]}] Caches:[]} {Id:1 Memory:0 Cores:[{Id:0 Threads:[1] Caches:[]}] Caches:[]} {Id:2 Memory:0 Cores:[{Id:0 Threads:[2] Caches:[]}] Caches:[]} {Id:3 Memory:0 Cores:[{Id:0 Threads:[3] Caches:[]}] Caches:[]} {Id:4 Memory:0 Cores:[{Id:0 Threads:[4] Caches:[]}] Caches:[]} {Id:5 Memory:0 Cores:[{Id:0 Threads:[5] Caches:[]}] Caches:[]} {Id:6 Memory:0 Cores:[{Id:0 Threads:[6] Caches:[]}] Caches:[]} {Id:7 Memory:0 Cores:[{Id:0 Threads:[7] Caches:[]}] Caches:[]} {Id:8 Memory:0 Cores:[{Id:0 Threads:[8] Caches:[]}] Caches:[]} {Id:9 Memory:0 Cores:[{Id:0 Threads:[9] Caches:[]}] Caches:[]} {Id:10 Memory:0 Cores:[{Id:0 Threads:[10] Caches:[]}] Caches:[]} {Id:11 Memory:0 Cores:[{Id:0 Threads:[11] Caches:[]}] Caches:[]} {Id:12 Memory:0 Cores:[{Id:0 Threads:[12] Caches:[]}] Caches:[]} {Id:13 Memory:0 Cores:[{Id:0 Threads:[13] Caches:[]}] Caches:[]} {Id:14 Memory:0 Cores:[{Id:0 Threads:[14] Caches:[]}] Caches:[]} {Id:15 Memory:0 Cores:[{Id:0 Threads:[15] Caches:[]}] Caches:[]}]}
I0507 22:31:04.684938    1147 manager.go:141] Version: {KernelVersion:3.13.0-43-generic ContainerOsVersion:Ubuntu precise (12.04.5 LTS) DockerVersion:Unknown CadvisorVersion:0.13.0}
E0507 22:31:04.685180    1147 manager.go:148] Docker container factory registration failed: unable to communicate with docker daemon: dial unix /var/run/docker.sock: no such file or directory.
E0507 22:31:04.685840    1147 manager.go:154] Registration of the raw container factory failed: failed to get cgroup subsystems: failed to find cgroup mounts
I0507 22:31:04.685871    1147 manager.go:897] Started watching for new ooms in manager
E0507 22:31:04.687334    1147 manager.go:206] Failed to start OOM watcher, will not get OOM events: exec: "journalctl": executable file not found in $PATH
I0507 22:31:04.690675    1147 plugins.go:69] No cloud provider specified.
I0507 22:31:04.690700    1147 server.go:251] Successfully initialized cloud provider: "" from the config file: ""
!!! [0507 22:31:10] Timed out waiting for http://127.0.0.1:10248/healthz
!!! Error in ./hack/test-cmd.sh:43
  'return 1' exited with status 1
Call stack:
  1: ./hack/test-cmd.sh:43 main(...)
Exiting with status 1
+++ [0507 22:31:10] Clean up complete

**Comment by markturansky** [comment]
@ArtfulCoder I can run test-cmd locally just fine on box OS X and Fedora 20.

I don't see an error in the text above that looks related to ISCSCI conversion.

**Comment by markturansky** [comment]
I just kicked it again after passing all tests locally.

**Comment by markturansky** [comment]
@ArtfulCoder All green but for Shippable.

**Comment by ArtfulCoder** [comment]
will do one last run of shippable. its failing for go 1.3 and v1beta3, passes for go 1.4 v1beta1..

**Comment by ArtfulCoder** [comment]
@markturansky can you check if there is a real issue here ? (go 1.3, v1beta3 combo)

**Comment by markturansky** [comment]
@ArtfulCoder any suggestions for recreating this? My F20 box is running Go 1.3.1 and all tests pass for me.

**Pull request merged**
