### PR TITLE
Graduate TTLAfterFinished to beta

### PR DESCRIPTION
**Pull request by ahg-g**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
Graduates TTLAfterFinished feature to beta.

**Which issue(s) this PR fixes**:
Part of https://github.com/kubernetes/enhancements/issues/592

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
TTLAfterFinished is now beta and enabled by default
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/592-ttl-after-finish
```

### CODE REVIEW

**Review by janetkuo — APPROVED** [review]

**Comment by ahg-g** [comment]
/assign @mikedanese

for bootstrap policy test changes

**Pull request merged**
