### PR TITLE
Adjust the architecture diagram

### PR DESCRIPTION
**Pull request by hw-qiaolei**
Some modifications of the architecture diagram:
1. adjust the order of authz and authn; since the API server usually first authenticate user, if it is a valid user then authorize it
2. adjust the arrow to point to kubelet instead of to node of the second node
3. change `replication controller` to `controller manager(replication controller etc.)` which connects to the REST API Server
4. some tiny adjustments of the arrow position
5. affected files: `architecture.svg`, `architecture.png` and `architecture.dia`

### CODE REVIEW

**Comment by hw-qiaolei** [comment]
@davidopp @benmccann is this PR reasonable and acceptable to you? Thanks

**Comment by benmccann** [comment]
I'm probably not a good person to ask

**Comment by hw-qiaolei** [comment]
@benmccann sorry for the disturbance, I saw you also fixed the diagram so I presumed to ask you for review...
Would somebody please look at this PR?

**Comment by brendandburns** [comment]
I'm disappointed in github's lack of PNG diff support ;)

LGTM, thanks for the fix!

**Comment by davidopp** [comment]
LGTM

**Comment by hw-qiaolei** [comment]
@brendandburns and @davidopp thank you very much for reviewing this PR. I did a little extra modification, as follows:
1. change `replication controller` to `controller manager(replication controller etc.)` which connects to the REST API Server
2. redraw these pictures. First I modify the architecture using `Dia`, and then export to `svg`. Then I opened `svg` with `Inkscape` and export as `png`. So that different formats(`dia`, `svg`, `png`) of the architecture diagram keep consistent.

**Pull request merged**
