### PR TITLE
Support graceful termination in the Kubelet (5/7)

### PR DESCRIPTION
**Pull request by smarterclayton**
Adds function in the Kubelet to support graceful deletion. Does not actually enable
graceful termination without the master setting TerminationGracePeriodSeconds on the
server.

Only the last commit is part of this pull.

Extracted from #9165

### CODE REVIEW

**Comment by yujuhong** [comment]
Still LGTM, assuming there is no additional change. Not sure why jenkins failed.

**Comment by smarterclayton** [comment]
I think it depends on the other e2e pull getting merged.  Digging into it
next.

On Aug 20, 2015, at 12:40 PM, Yu-Ju Hong <notifications@github.com> wrote:

Still LGTM, assuming there is no additional change. Not sure why jenkins
failed.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/12959#issuecomment-133071175>
.

**Comment by smarterclayton** [comment]
ok to test

**Comment by smarterclayton** [comment]
@bgrant0607 I added a timebox around prestop to guarantee it does not prevent deletion within the grace period.  Stop will terminate the running exec session automatically.

**Comment by smarterclayton** [comment]
Flake was unrelated

```
ok k8s.io/kubernetes/pkg/util/flushwriter	1.041s	coverage: 100.0% of statements
--- FAIL: TestKubenates (0.02 seconds)
jsonpath_test.go:47: in recursive name, expect to get "127.0.0.1 127.0.0.2 myself e2e", got "myself e2e 127.0.0.1 127.0.0.2"
FAIL
coverage: 90.2% of statements
FAIL	k8s.io/kubernetes/pkg/util/jsonpath	0.129s
```

**Comment by yujuhong** [comment]
@k8s-bot ok to test

**Comment by smarterclayton** [comment]
The kubectl service timeout should probably be bumped to 60 seconds - it could easily take that long to download guestbook-go if the docker hub is overloaded.

**Comment by smarterclayton** [comment]
Opened #13039 for the kubectl flake

**Comment by yujuhong** [comment]
@zmerlynn (oncall), this should be ok to merge.

**Comment by zmerlynn** [comment]
Just merged a hunk, it'll be an hour-ish.

**Comment by yujuhong** [comment]
> Just merged a hunk, it'll be an hour-ish.

Cool. Thanks for letting me know. :-)

**Comment by smarterclayton** [comment]
I'll be around to watch - I blame all flakes on the network.

**Comment by zmerlynn** [comment]
Blargh. It'll be another 2h before the `e2e-gce` really resets, but `e2e-gce-parallel` is shiny, so let's do it.

**Comment by zmerlynn** [comment]
And apparently I forced a few PRs into rebase from this one, so my work today must be done.

**Comment by yujuhong** [comment]
Thanks! That's why I wanted to get this one merged -- to avoid more rebase for this PR and other PRs affected by the previous revert.

**Pull request merged**
