### PR TITLE
Bump k8s.io/utils version

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Bump k8s.io/utils version

This is part of kubernetes/kubeadm#1925

**Which issue(s) this PR fixes**:

Ref kubernetes/kubeadm#1925
Ref kubernetes/utils#123
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
@SataQiu 

looks like the testing failures are legit - I think an issue with type mismatches?

Also, would you mind updating your PR with the correct link: https://github.com/kubernetes/kubeadm/issues/1925? Thanks :)

**Comment by fedebongio** [comment]
/assign @liggitt 
(assumed that you will have to look at this one anyways!)

**Comment by cblecker** [comment]
/hold
To prevent retest loop. Test failures look legitimate.

**Comment by SataQiu** [comment]
@cblecker Thanks for doing this.
I've rebased the code. Need LGTM again!

**Pull request merged**
