### PR TITLE
Upgrade to go 1.11.13

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Update to use go 1.11.13
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/cc @cblecker 
I'm working on the kube-cross image now.
/sig release
since this patches CVEs:
/priority critical-urgent

**Comment by BenTheElder** [comment]
(those jobs failed due to the kube-cross image not being up yet, it's rolling out currently)

**Comment by BenTheElder** [comment]
looks like bazel worked fine but failed on that malformed port in the vsphere/vclib test fixed in https://github.com/kubernetes/kubernetes/commit/f713ec89ed81b0860b9b312987529dc5534d0824

**Comment by BenTheElder** [comment]
picked in https://github.com/kubernetes/kubernetes/commit/f713ec89ed81b0860b9b312987529dc5534d0824, `k8s.gcr.io/kube-cross:v1.11.13-1` is now live so hopefully tests should pass this time ...

**Review by dougm — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
