### PR TITLE
Automated cherry pick of #64598: Remove optimization from getWork in

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
Cherry pick of #64598 on release-1.10.

#64598: Remove optimization from getWork in

### CODE REVIEW

**Comment by MaciekPytel** [comment]
@MikeSpreitzer Can you add a release note to #64598, so that users know this was fixed in patch release?

**Comment by MikeSpreitzer** [comment]
@MaciekPytel : how do I add a release-specific release note?  Wouldn't it go here rather than in the base PR?

**Comment by MaciekPytel** [comment]
@MikeSpreitzer AFAIK you can't add a release-specific release note. The same one will be used for every release base commit is cherry-picked into. Tooling that generates release notes takes them from parent PRs and ignores whatever is set on cherry-pick PR.

The preference is for anything that goes into patch release to have a release note, unless it's something with no impact on users (like fixing a bug in test, etc).

**Pull request merged**
