### PR TITLE
CR conversion: protect from converter input edits

### LINKED ISSUE #114958: CR conversion needs to protect against a converter that mutates the input list
### What happened?

If a CR converter is wired in and it modifies the input list, the delegating CR converter does not protect against this.

### What did you expect to happen?

A converter cannot effect the input list

### How can we reproduce it (as minimally and precisely as possible)?

Not really possible externally - it's a coding issue that the current converters don't hit.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
master```

</details>


### Cloud provider

<details>
N/A
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by ncdc**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Deep copy the input list before invoking the converter to protect from a converter that mutates the input list.

#### Which issue(s) this PR fixes:

Fixes #114958

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ncdc** [comment]
Fun fact: the conversion test code was only passing before **because** the input is mutated. With this change, I had to add `metadata` to all the objects in the unit test because we're now hitting the part of the conversion code that validates the converted objects have the appropriate data.

**Comment by ncdc** [comment]
@liggitt PTAL

**Comment by liggitt** [comment]
heh, sounds good... always nice when passing unit tests means something actually works properly

/lgtm

**Pull request merged**
