### PR TITLE
AWS: Hopefully fix e2e?

### PR DESCRIPTION
**Pull request by zmerlynn**
**What this PR does / why we need it**: Fix AWS e2e
**Which issue this PR fixes**: fixes build broken by #28499 
**Special notes for your reviewer**: This is a pump & dump, I probably won't be around to respond to comments after this. If it needs a cherry-pick or anything, please check?

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31295)

### CODE REVIEW

**Comment by zmerlynn** [comment]
@justinsb: Ping

**Comment by zmerlynn** [comment]
cc @mikedanese (or anyone who feels like LGTM)

**Comment by justinsb** [comment]
Sorry @zmerlynn !  LGTM

**Comment by zmerlynn** [comment]
@k8s-bot: test this, issue #unknown

**Comment by pwittrock** [comment]
@k8s-bot: test this issue: #unknown

**Comment by pwittrock** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by foxish** [comment]
Already in 1.4 at this point. Removing cherrypick labels. @zmerlynn @pwittrock Please re-add if you think this is a mistake.

**Pull request merged**
