### PR TITLE
bug fixes in GCE cloud provider

### LINKED ISSUE #49657: GCP network resources are being created on the wrong network
Causes failures in:
* https://github.com/kubernetes/kubernetes/issues/49150

### PR DESCRIPTION
**Pull request by freehan**
fixes: #49657 #49150
 

```release-note
NONE
```

### CODE REVIEW

**Comment by freehan** [comment]
2 lines fix. 

One saves compute alpha API client.
One should fix the GKE test failures.

**Comment by bowei** [comment]
Please update the commit message to. E more descriptive of what the bug was

**Comment by nicksardo** [comment]
Looks like it's been broken for almost a month: https://github.com/kubernetes/kubernetes/pull/47881/files#diff-b3d75e3586a2c9a5140cd549861da9c0R200.  
/lgtm
/approve

**Comment by freehan** [comment]
updated commit message.

**Comment by msau42** [comment]
I think this will fix #49150, which is seeing issues with pod->pod communication only on gke.

**Comment by nicksardo** [comment]
Fixes #49150

**Comment by foxish** [comment]
ping @bowei @freehan, can you open up an issue please? This needs to merge to track and resolve any other failures in the GKE master tests.

**Comment by nicksardo** [comment]
We can use #49150 as @msau42 points out, but @freehan needs to update the PR description.

**Comment by bowei** [comment]
@freehan -- ideal commit message would be 

```
Fixes bug where the network used in the cloud provider was not taken from the /etc/gce.conf configuration.
```

**Comment by bowei** [comment]
Issue: https://github.com/kubernetes/kubernetes/issues/49657

**Comment by bowei** [comment]
Fixes #49657

**Comment by fejta** [comment]
/retest
Failure was caused by https://github.com/kubernetes/kubernetes/issues/49679

**Pull request merged**
