### PR TITLE
add front proxy to kubeadm created kube-apiservers

### PR DESCRIPTION
**Pull request by deads2k**
The front proxy authenticator configuration has been in a release or two.  It allows a front proxy (secured by mutual TLS auth) to provide user information for a request.  The kube-aggregator uses this to securely terminate authentication (has to terminate TLS and thus client-certs) and communicate user info to backing API servers.

Since the kube-apiserver always verifies the front-proxy via a client certificate, this isn't open for abuse unless you already have access to either the signing key or client cert which kubeadm creates locally.  If you got there, you already owned the box.  Therefore, this adds the authenticator unconditionally.

@luxas Are there e2e tests for `kubeadm`?
@liggitt @kubernetes/sig-auth-misc

### CODE REVIEW

**Comment by liggitt** [comment]
seems reasonable

**Comment by luxas** [comment]
this lgtm although I haven't dealt with the aggregated apiserver proxy before

**Comment by deads2k** [comment]
Front proxy authenticator described here: https://kubernetes.io/docs/admin/authentication/#authenticating-proxy

**Comment by deads2k** [comment]
> this lgtm although I haven't dealt with the aggregated apiserver proxy before

@luxas anyone else you want to take a look?

**Comment by luxas** [comment]
@deads2k I'd like @mikedanese to take a look at this as well, therefore I assigned him.

But I don't mind merging now and reverting in the very unlikely case he would have objections to this.
@liggitt also approved this so...

WDYT?

**Comment by luxas** [comment]
btw, what I wondered was how do we set up the front proxy when we have this?
Do you have any pointers to a yaml spec or something that we could have as an example for those who'd like to deploy such a configuration? Also, how do we transfer the client cert to the front proxy?

**Comment by deads2k** [comment]
> btw, what I wondered was how do we set up the front proxy when we have this?

You give the client certs to whatever wants to proxy and then they can wire it up.



> Do you have any pointers to a yaml spec or something that we could have as an example for those who'd like to deploy such a configuration? Also, how do we transfer the client cert to the front proxy?

Funny you should ask.  I'm in the process of making an easy example right now.  For `local-up-cluster.sh` its pretty simply.  This gets you pretty close: https://github.com/kubernetes/kubernetes/pull/41514.

Once this goes in and I'm able to see and set up a comparable system, I can make a similar example.

**Comment by deads2k** [comment]
> But I don't mind merging now and reverting in the very unlikely case he would have objections to this.
> @liggitt also approved this so...
> 
> WDYT?

I think its reasonable to move this forward.

**Comment by luxas** [comment]
SGTM

/lgtm
/approve

**Pull request merged**
