### PR TITLE
Remove heapster flag in 'kubectl top'

### PR DESCRIPTION
**Pull request by chymy**
Signed-off-by: chymy <chang.min1@zte.com.cn>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Heapster is no longer supported for `kubectl top`, heapster flag is redundant, should be removed.
ref: #87498, kubernetes/kubectl#806
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by rikatz** [comment]
/priority backlog
/lgtm

/assign @soltysh @pwittrock 

Don't know if we can, but I guess it would be good to remove heapster flags from kubectl at all :)

There are some references of heapster also in the docs/book pages, but don't know if this is still in use, otherwise maybe can also be removed from the book

**Comment by rikatz** [comment]
@chymy maybe I guess the TODO on line 182 of top_pod.go can also be removed, or changed to something not related to Heapster.

**Comment by chymy** [comment]
> @chymy maybe I guess the TODO on line 182 of top_pod.go can also be removed, or changed to something not related to Heapster.

Thanks @rikatz , done. Please take a look.

**Review by dougsland — COMMENTED** [review]
In general, I believe it's a good move. However, it seems more work to be done. We have a bunch of places with heapster.  Are you planing to split the work by group or have a single patch ?

==== GCE folks===
cluster/gce/config-test.sh
cluster/gce/config-default.s
cluster/gce/util.sh
cluster/kubemark/gce/config-default.sh
cluster/addons/dashboard/dashboard.yaml

============ kube-controller-manager ==========
cmd/kube-controller-manager/app/autoscaling.go

============= hack/profiles =====================
hack/grab-profiles.sh

========= still worth having heapster on tests/client?=========
pkg/controller/podautoscaler/legacy_horizontal_test.go
pkg/controller/podautoscaler/legacy_replica_calculator_test.go
pkg/controller/podautoscaler/metrics/legacy_metrics_client_test.go
pkg/controller/podautoscaler/metrics/legacy_metrics_client.go

staging/src/k8s.io/kubectl/docs/book/pages/resource_printing/cluster_information.md
etc..

**Comment by chymy** [comment]
Thanks for your reviews @dougsland .
The PR is to delete the parameters related to heapster of `kubectl top` which is no longer used. Does not affect other code.
I am planing to split the work by group.

**Review by rikatz — APPROVED** [review]
/lgtm

Will ping folks on sig-cli to see if we can get this merged

**Pull request merged**
