### PR TITLE
updated import restrictions

### PR DESCRIPTION
**Pull request by mkenigs**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Update import-boss restrictions

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
refs #68201

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
Looks like this PR was created during the github outage and prow missed some webhooks. Closing and reopening.
/close

**Comment by nikhita** [comment]
I guess this is sig architecture?

/sig architecture

**Comment by mkenigs** [comment]
@dims ran the script https://github.com/kubernetes/kubernetes/issues/68201#issuecomment-462950396 on pkg/.import-restrictions and it looks like there isn't anything that needs to be removed. So should I close this PR?

**Comment by dims** [comment]
@mkenigs the main reason for adding the import restriction here was to make sure we don't use any code from `"k8s.io/kubernetes/cmd"`, we don't really need to police anything else. So let's please close this PR

**Pull request closed without merging**
