### PR TITLE
dependencies: update {vishvananda/netns,xlab/treeprint}

### PR DESCRIPTION
**Pull request by humblec**
- [x] gh/vishvananda/netns: v0.0.4 :
https://github.com/vishvananda/netns/compare/v0.0.2...v0.0.4 ( mainly the go version bump to 1.17.0)
- [x] gh/xlab/treeprint v1.2.0 
https://github.com/xlab/treeprint/compare/v1.1.0...v1.2.0

/kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
Any specific improvements, bug fixes, breaking changes ...?
Why these two packages?

**Comment by dims** [comment]
changes are:
- https://github.com/vishvananda/netns/compare/v0.0.2...v0.0.4
- https://github.com/xlab/treeprint/compare/v1.1.0...v1.2.0

/assign @BenTheElder @liggitt

**Comment by liggitt** [comment]
> ps# #117241

this PR looks ~fine, but I'm curious what the relationship between this and the runc bump is?

**Pull request merged**
