### PR TITLE
Create new deployment e2e test suite.

### PR DESCRIPTION
**Pull request by janetkuo**
cc @ihmccreery

### CODE REVIEW

**Comment by janetkuo** [comment]
@k8s-bot e2e test this issue: #20606

**Comment by roberthbailey** [comment]
Why create a new suite instead of just enabling the Deployment tests in the existing suite?

**Comment by janetkuo** [comment]
@roberthbailey #19667 marked all deployment e2e tests as ` [Feature:Deployment]` and therefore they aren't tested anywhere currently (they're tested in gce before). Chatted with @ihmccreery earlier today, and we agreed that we need to create a new build for these tests.

**Comment by ihmccreery** [comment]
Are deployments in experimental still?

**Comment by janetkuo** [comment]
Didn't see https://github.com/kubernetes/kubernetes/blob/master/docs/devel/e2e-tests.md#kinds-of-tests until now. Looks like we should remove `[Feature:Deployment]` tags everywhere once Deployment graduate to beta (i.e. #20517 is merged). Is that correct?

**Comment by ihmccreery** [comment]
> Looks like we should remove [Feature:Deployment] tags everywhere once Deployment graduate to beta (i.e. #20517 is merged). Is that correct?

Yup, sorry that wasn't clear before.  That will trigger all deployment tests to run in our core suite (the ones that run in parallel will block the submit queue, the ones that run in serial will go into the `-serial` critical builds).

**Comment by janetkuo** [comment]
Got it. Closing this since the new test suite is no longer needed.

**Pull request closed without merging**
