### PR TITLE
rename build/ dirs to other things.

### PR DESCRIPTION
**Pull request by mikedanese**
#35359

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35453)

### CODE REVIEW

**Comment by jbeda** [comment]
LGTM but it will probably be disruptive for those that script this from outside of the kubernetes repo.  I'm thinking test-infra and such.  This probably merits an announcement to kubernetes-dev.

**Comment by spxtr** [comment]
The test-infra should be calling `make` rather than directly into `build`. I'm not sure if the node tests work properly.

A couple of them don't, I'll fix.

**Comment by mikedanese** [comment]
@k8s-bot cvm gke e2e test this
@k8s-bot gci gke e2e test this

**Comment by ixdy** [comment]
LGTM, though agree that we probably need an announcement since this may break folks outside kubernetes. (Distro release scripts, for example.)

**Comment by ixdy** [comment]
cc @smarterclayton @ingvagabund @thockin any comments?

**Comment by ixdy** [comment]
Hm, I think we need changes to `kubernetes/release` too.

Handling the name switch for the next 9 months is going to be annoying.

**Comment by spxtr** [comment]
Oh right, anago calls `make release` but it also has a call to `build/versionize-docs.sh`...

**Comment by thockin** [comment]
This is super annoying.  What's the ETA on a fix in Bazel?

**Comment by spxtr** [comment]
https://github.com/bazelbuild/bazel/issues/552 looks like someone is working on it but not high priority.

**Comment by thockin** [comment]
Ugh, Propose to roll this back until Bazel fix...

**Comment by thockin** [comment]
Can we give them a chance to reply before we do this?

**Comment by ixdy** [comment]
@thockin it sounds like the bazel fix might land in a month or so. I'm not sure we want to wait that long to test bazel stuff. (I also don't like the rename. I'm not sure what's a better option here. I guess live with `build-tools` for a month and then switch back?)

**Comment by thockin** [comment]
I acquiesce.  As long as I don't have to clean up the mess

**Pull request merged**
