### PR TITLE
apiextensions-apiserver: change k8s.io/apimachinery/pkg/util/diff to github.com/google/go-cmp/cmp

### PR DESCRIPTION
**Pull request by aimuz**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

k8s.io/apimachinery/pkg/util/diff.{ObjectDiff,ObjectGoPrintDiff,ObjectReflectDiff} Marked as DEPRECATED

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/diff/diff.go#L63

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Jefftree** [comment]
Thanks!
/lgtm
/assign @sttts

**Comment by aimuz** [comment]
Is there anything missing from this PR?

**Pull request merged**
