### PR TITLE
Shorten name of stable-current-release job on GCE

### PR DESCRIPTION
**Pull request by ikehz**
Name was too long; couldn't create resources. :crying_cat_face:

### CODE REVIEW

**Comment by ihmccreery** [comment]
@k8s-bot unit test this again please.

**Comment by ihmccreery** [comment]
Reassigned to @spxtr for review.

**Comment by spxtr** [comment]
@k8s-bot unit test this please

**Comment by ihmccreery** [comment]
Merging manually to fix tests.

**Pull request merged**
