### PR TITLE
fix wrong path for all registries

### PR DESCRIPTION
**Pull request by lixiaobing1**
fix wrong path for all registries, registry path should be "pkg/registry/generic/registry", under this path, it is the package registry.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30623)

### CODE REVIEW

**Comment by thockin** [comment]
ok to test

**Comment by lixiaobing10051267** [comment]
@k8s-bot test this issue: [30732](https://github.com/kubernetes/kubernetes/issues/30732)

**Comment by thockin** [comment]
@k8s-bot test this: github issue #IGNORE

**Comment by Random-Liu** [comment]
@k8s-bot test this issue https://github.com/kubernetes/kubernetes/issues/30779.

**Comment by thockin** [comment]
This is a one-word docs change.  It doesn't need e2e.

**Pull request merged**
