### PR TITLE
Release 1.2 cherrypick batch

### PR DESCRIPTION
**Pull request by eparis**
#22989: Fix non-masquerade CIDR
#22942: Allow up to 39 PVs attached to AWS node
#22969: Disable kubectl validation for upgrade e2e
#22993: Bumped Heapster to stable version 1.0.0
#22948: Separate GetOldRS and GetNewRS in deployment controller (get and mutate) and deployment util (get only)
#23012: Make fullyLabeledReplicas optional in rc status
#23005: Trusty: Fix heapster breakage caused by #22940
#23020: Updating cadvisor deps to v0.22.2

### CODE REVIEW

**Comment by eparis** [comment]
can't pick 23020 until it merges, but I will just update this PR.

**Comment by bgrant0607** [comment]
Thanks @eparis. Looking more carefully this time :-)

**Comment by eparis** [comment]
We've got bots for that   :)

**Comment by eparis** [comment]
and now with cadvisor update

**Comment by bgrant0607** [comment]
Looks like we got them this time! Thanks much. LGTM

**Comment by eparis** [comment]
[Fail] Kubectl client Kubectl describe [It] should check if kubectl describe prints relevant information for rc and pods [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:506

[Fail] Kubectl client Kubectl expose [It] should create services for rc [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/examples.go:506

**Comment by eparis** [comment]
@k8s-bot e2e test this flake: #IGNORE 
because i think it is a flake, but hard to be sure...

**Comment by bgrant0607** [comment]
@eparis Why are we running examples test?

**Comment by bgrant0607** [comment]
I guess there are some conformance tests mixed in there.

**Comment by bgrant0607** [comment]
Green now. 

@eparis A couple kubectl tests flaked in head around the same time. I can't see the test artifacts yet, though, so I can't determine for certain that it's correlated.

**Comment by bgrant0607** [comment]
Merging.

**Pull request merged**
