### PR TITLE
Automated cherry pick of #71276: WIP: Handle failed attach operation leave uncertain

### PR DESCRIPTION
**Pull request by jingxu97**
Cherry pick of #71276 on release-1.13.

#71276: WIP: Handle failed attach operation leave uncertain

### CODE REVIEW

**Comment by jingxu97** [comment]
cc @msau42

**Comment by davidz627** [comment]
Looks like something might have to be fixed manually with godeps for the verify test?

**Comment by spiffxp** [comment]
verify seems to be failing for this branch: https://github.com/kubernetes/kubernetes/issues/80204

**Comment by spiffxp** [comment]
/test pull-kubernetes-verify
verifying whether #80559 fixed verify

**Comment by misterikkit** [comment]
pull-kubernetes-verify is currently green. Can this be approved?

**Comment by tpepper** [comment]
/release-note-none
as per the master branch PR

**Pull request merged**
