### PR TITLE
update pending statefulset pod

### LINKED ISSUE #88896: StatefulSet does not update the Pod image
**What happened**:
StatefulSet does not reflect image change to the Pod.

**What you expected to happen**:
StatefulSet to reflect image change to the Pod.

**How to reproduce it (as minimally and precisely as possible)**:
1. Apply a StatefulSet with a wrong image - `.spec.template.spec.containers[0].image`.
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:foo
        ports:
        - containerPort: 80
          name: web
```

2. Ensure that the Pod fails to pull the image
```
$ k get po
NAME                             READY   STATUS             RESTARTS   AGE
web-0                            0/1     ImagePullBackOff   0          1m
```

3. Update the StatefulSet `.spec.template.spec.containers[0].image` to a valid image - `k8s.gcr.io/nginx-slim:0.8`

4. Ensure that the StatefulSet does not update the Pod and the Pod still tries to pull the old image
```
$ k get po
NAME                             READY   STATUS             RESTARTS   AGE
web-0                            0/1     ImagePullBackOff   0          19m

$ k get po web-0 -o jsonpath='{.spec.containers[0].image}'
k8s.gcr.io/nginx-slim:foo

$ k get sts web -o jsonpath='{.spec.template.spec.containers[0].image}'
k8s.gcr.io/nginx-slim:0.8
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by silenceper**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix update pending statefulset pod.

**Which issue(s) this PR fixes**:

Fixes #88896

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by silenceper** [comment]
PTAL @soltysh @kow3ns

**Comment by soltysh** [comment]
Duplicate of #89801.
Closing in favor of the other one.
/close

**Pull request closed without merging**
