### PR TITLE
Switch disruption controller to shared informers

### PR DESCRIPTION
**Pull request by ncdc**
Originally part of #40097, but I'm splitting that up into multiple smaller ones.

cc @mml @deads2k @liggitt @sttts @smarterclayton @wojtek-t @gmarek @timothysc @davidopp @kubernetes/sig-scalability-pr-reviews

### CODE REVIEW

**Comment by deads2k** [comment]
looks ok.  it appears the existing code already deepcopied just before mutation.  Go it.


I'd feel a lot more confident if we could sort out https://github.com/kubernetes/kubernetes/pull/40243

**Comment by kargakis** [comment]
PDB changes lgtm

**Comment by ncdc** [comment]
Rebased on top of #41114

**Comment by ncdc** [comment]
@smarterclayton rebased

**Comment by ncdc** [comment]
@k8s-bot node e2e test this

**Pull request merged**
