### PR TITLE
Introduced LastTerminateState to ContainerStatus

### PR DESCRIPTION
**Pull request by dchen1107**
Part of #4919

Next PR is on reporting last terminated containerStatus

cc/ @bgrant0607

### CODE REVIEW

**Comment by roberthbailey** [comment]
Dawn, in #4919 you said that you were going to add this to the v1beta3 api first, but in this PR you are adding it to v1beta{1,2,3} at the same time. Do we care about back-porting this feature to the older APIs?

LGTM, but assigning to @bgrant0607 to take a second look at the API changes.

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
Yes, it needs to exist in v1beta1/2 for now, since we roundtrip objects through the older API versions.

**Comment by dchen1107** [comment]
backing port is just avoid unnecessary conversion logic.

**Pull request merged**
