### PR TITLE
Revert "Skip node container manager test on systemd" and fix test

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind failing-test
#### What this PR does / why we need it:
replaces https://github.com/kubernetes/kubernetes/pull/104425, fixes the test, and adds a test verifying the kubelet recreates kubepods{,.slice} on restart
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by ffromani — COMMENTED** [review]
/lgtm

thanks a ton!

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

the change in test looks good. This https://github.com/kubernetes/kubernetes/pull/125923#issuecomment-2276636740 is interesting question

**Pull request merged**
