### PR TITLE
Remove use of testapi package

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Removes use of the testapi package in favor of small local helpers, literal API request paths, or using real codecs/storage configuration.

**Special notes for your reviewer**:
The testapi package has many problems:
* non-hermetic, influenced by envvars
* inaccurate implementations (selflink implementation is completely wrong)
* parallel maintenance to real API setup / codecs, etc

```release-note
NONE
```

/assign @smarterclayton 
/sig api-machinery

### CODE REVIEW

**Comment by liggitt** [comment]
cc @deads2k @mikedanese @lavalamp for various run-ins with this package in the past

**Comment by liggitt** [comment]
cc @deads2k @mikedanese @lavalamp for various run-ins with this package in the past

**Comment by deads2k** [comment]
party!

/lgtm

**Comment by liggitt** [comment]
(pull-kubernetes-node-e2e-containerd failure is pre-existing and unrelated)

**Pull request merged**
