### PR TITLE
sigs.k8s.io/json go 1.23 bump

### PR DESCRIPTION
**Pull request by liggitt**
picks up https://github.com/kubernetes-sigs/json/pull/21

slight alloc improvements, no particular other changes, but keeps us up to date so we are prepped to pick up the omitzero change in go 1.24 to fix `creationTimestamp: null` :)

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
Looks like a bunch of changes in the past week will get picked up:
https://github.com/kubernetes-sigs/json/compare/bc3834ca7abd...9aa6b5e7a4b3

No changes in direct/indirect dependencies!

Big +1 to prep to `pick up the omitzero change in go 1.24`

/approve
/lgtm

**Comment by jpbetz** [comment]
> we are prepped to pick up the omitzero change in go 1.24 to fix creationTimestamp: null

Looking forward to this part in particular!

**Pull request merged**
