### PR TITLE
Update GlusterFS examples readme.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
Can anyone trigger the tests on this PR ? Thanks in advance !

**Comment by rootfs** [comment]
@k8s-bot ok to test

**Comment by humblec** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by humblec** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Comment by jsafrane** [comment]
@eparis, please approve

**Pull request merged**
