### PR TITLE
Remove unbounded connection creation; also change worst case delay from 50s to 5s

### PR DESCRIPTION
**Pull request by lavalamp**
**What type of PR is this?**

/kind bug

/kind flake
**What this PR does / why we need it**:

The worst case delay of this test is quite bad. From the message it appears the author didn't intend to make 10 timers every loop.

Also the other test made almost 400,000 connections on my system.

**Which issue(s) this PR fixes**:

Maybe helps #98486

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by lavalamp** [comment]
It runs super fast on my system either way of course. It seems that if this takes a long time, the author's intention was for the test to fail.

**Comment by lavalamp** [comment]
New push makes the channel buffered. That was probably the actual problem, unbuffered channel means a ton of context switches.

**Comment by liggitt** [comment]
how fast did it run locally before/after with ‘-race`?

**Comment by lavalamp** [comment]
30s before and after, no difference.

**Comment by lavalamp** [comment]
OK this push removes an unbounded connection creation in the other test, it made as many as it could in 1 second. On my local system, that was almost 400k.

Now go test -race is down below 2s so I think this definitely did something.

**Comment by liggitt** [comment]
> On my local system, that was almost 400k.

that seems useful… the first 399k might just have gotten lucky :)

nice find

**Comment by liggitt** [comment]
sigh, the irony is that I added that in https://github.com/kubernetes/kubernetes/commit/aa4113d777dd6c699233e0b6d903e9734e182686#diff-be7ac4a80e49b1128598fa376a073e52ab7977fbe4f843256ea850989c91cca5

the intent of the test is to race CloseAll and Dial, so the number of connections is not important, it's the fact that both calls are happening simultaneously. Clearly letting dials happen in a hot loop for 1s was not a good way to do that

**Comment by lavalamp** [comment]
OK, I rewrote it a bit.

**Comment by lavalamp** [comment]
(and yes it still catches races)

**Comment by liggitt** [comment]
/lgtm
/approve

thanks

**Comment by liggitt** [comment]
/retest

looks like the dry run integration test doesn't tolerate conflict errors (which it should)… worth a separate issue to track

**Pull request merged**
