### PR TITLE
[1.20.1] Add AcceleratorStats to cri_stats_provider for 1.20

### PR DESCRIPTION
**Pull request by ruiwen-zhao**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This is a cherry-pick of #96873
**Which issue(s) this PR fixes**:

Fixes #
See #96873
**Special notes for your reviewer**:
See #96873

**Does this PR introduce a user-facing change?**:

```release-note
AcceleratorStats will be available in the Summary API of kubelet when cri_stats_provider is used.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by hasheddan** [comment]
@justaugustus I think we are running into the same issues here that we are on the periodic of trying to grab 1.20 from latest instead of stable

**Comment by ruiwen-zhao** [comment]
> @justaugustus I think we are running into the same issues here that we are on the periodic of trying to grab 1.20 from latest instead of stable

are you talking about the failing tests?

**Comment by hasheddan** [comment]
@ruiwen-zhao yep :+1:

**Comment by ruiwen-zhao** [comment]
> @ruiwen-zhao yep 👍

Sorry I didn't find any existing issue related to this. Is there anything we should do other than hitting retest?

**Comment by SergeyKanzhelev** [comment]
/hold

to stop retesting it over and over

**Comment by SergeyKanzhelev** [comment]
Failure:

```
W1210 00:28:32.091] 2020/12/10 00:28:32 extract_k8s.go:302: U=file:///go/src/k8s.io/kubernetes/_output/gcs-stage R=v1.20.0-3+31b0840fed6005 get-kube.sh failed: error during /workspace/get-kube.sh: exit status 1
W1210 00:28:32.091] 2020/12/10 00:28:32 process.go:153: Running: /workspace/get-kube.sh
W1210 00:28:32.091] Version doesn't match regexp
```

Version used seems to be `v1.20.0-3+31b0840fed6005`. Code validating the version:

https://github.com/kubernetes/kubernetes/blob/f58c4d8cd72581c263c786f775166cfca7400519/cluster/get-kube.sh#L186-L204

**Comment by justaugustus** [comment]
/hold cancel
/retest
ref: https://github.com/kubernetes/kubernetes/issues/97178, https://kubernetes.slack.com/archives/C2C40FMNF/p1607573485130800?thread_ts=1607570073.126300&cid=C2C40FMNF

**Pull request merged**
