### PR TITLE
make private method private

### PR DESCRIPTION
**Pull request by wlan0**
@thockin

### CODE REVIEW

**Comment by thockin** [comment]
@k8s-bot ok to test

**Comment by luxas** [comment]
@k8s-bot kops aws e2e test this

**Comment by wlan0** [comment]
@thockin can the kops e2e steps be manually started? @luxas' comment just lead to another error.

**Comment by thockin** [comment]
@k8s-bot kops aws e2e test this

**Comment by thockin** [comment]
if it fails again, let's confirm it is not real and consider manual merge

**Pull request merged**
