### PR TITLE
`kubectl get priorityclass` prints value column

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What this PR does / why we need it**:

Prints out `value` column when running `kubectl get priorityclass`.

```console
$ kubectl get priorityclass
NAME                      VALUE        AGE
system-cluster-critical   2000000000   6m33s
system-node-critical      2000001000   6m33s
```

Before:

```console
$ kubectl get priorityclass
NAME                      CREATED AT
system-cluster-critical   2018-10-04T06:18:27Z
system-node-critical      2018-10-04T06:18:27Z
```

**Special notes for your reviewer**:
- If necessary, other columns can be added as well, or to `-o wide` columns.
- Optionally we can follow storageclass way to append `(global default)` to the name if it's a global default priorityclass.

**Release note**:
```release-note
`kubectl get priorityclass` now prints value column by default.
```

/kind feature
/sig cli
/sig scheduling

### CODE REVIEW

**Comment by Huang-Wei** [comment]
@kubernetes/sig-cli-pr-reviews

**Comment by Huang-Wei** [comment]
@bsalamat @liggitt could you take a chance to review this? Thanks.

**Review by dixudx — APPROVED** [review]
/lgtm

**Comment by liggitt** [comment]
should we include the GlobalDefault field value? that seems more useful than the creation time

**Comment by dixudx** [comment]
> should we include the GlobalDefault field value? that seems more useful than the creation time

Yeah. Correct.  @liggitt  👍

**Comment by Huang-Wei** [comment]
@liggitt I think so. Just like how StorageClass prints.

BTW: as PriorityClass is mostly used and design by @bsalamat in preemption logic. I'd like to hear about Bobby's comments.

**Comment by bsalamat** [comment]
Thanks Wei for this improvement. I would prefer the following output:

```
NAME         VALUE        GLOBAL_DEFAULT      AGE
priority1    2000000000   true                6m33s
```

This is very similar to what you wrote. It just puts "value" before "global default". Value is more important in my opinion. Hence, it is show before global default.
This is just my personal preference though. It has nothing to do with the fact that I have designed pod priority. In other words, there is no technical wisdom behind my suggestion! :-)

**Comment by Huang-Wei** [comment]
Added `GLOBAL-DEFAULT` column. @bsalamat @liggitt @dixudx PTAL.

BTW: according to [kubectl dev guide](https://github.com/kubernetes/community/blob/master/contributors/devel/kubectl-conventions.md), it said:

> Column titles and values should not contain spaces in order to facilitate commands that break lines into fields: cut, awk, etc. Instead, use `-` as the word separator.

So I used `-` over `_`:

```console
NAME                      VALUE        GLOBAL-DEFAULT   AGE
system-cluster-critical   2000000000   false            38s
system-node-critical      2000001000   false            38s
```

And I do see other API objects follow this convention:

```console
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.0.0.1     <none>        443/TCP   3m11s
```

**Review by bsalamat — COMMENTED** [review]
/lgtm

Thanks, @Huang-Wei! We should add "Description" to "-o wide" as well.

**Comment by Huang-Wei** [comment]
@bsalamat hmm, I'm a little hesitant on adding `Description` column, as:

1. there is no API object has this kind of column
1. it will breaks `Column titles and values should not contain spaces`, and maybe has string truncation issue.

So maybe better for users to use `-o json/yaml/...` to get "description" info.

**Comment by Huang-Wei** [comment]
@bsalamat yeap, that makes sense.

/cc @liggitt @deads2k for approval.

**Pull request merged**
