### PR TITLE
make kubelet sysctl constants private

### PR DESCRIPTION
**Pull request by Aresforchina**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
add some comments for const variables
**Which issue(s) this PR fixes**:

Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by Aresforchina** [comment]
@mattjmcnaughton These are some comments . please help me review them.

**Review by mattjmcnaughton — CHANGES_REQUESTED** [review]
I took another look at this diff, and noticed that all of these constants are only used in `pkg/kubelet/sysctl`. As a result, I think that we can make them not exported (i.e. `IpcNamespace` becomes `ipcNamespace`). Then, the Go linter will not complain about them not having a comment.

We could also add comments... but in my mind, the comments aren't really adding any useful information because the name is already explanatory.

**Comment by Aresforchina** [comment]
@mattjmcnaughton ok,I will changed back to the comments as before and capitalized the variables.Can you help me check prs where two tests suit did not pass ? I am not sure why they are failed ,thanks a lot.

**Comment by Aresforchina** [comment]
Ok,I will changed back to the comments as before and capitalized the constant variables in `pkg/kubelet/sysctl `.

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/ok-to-test

**Comment by derekwaynecarr** [comment]
its a net benefit to make the constants private.

updating the pr title.

/approve
/lgtm

**Pull request merged**
