### PR TITLE
Add test file

### PR DESCRIPTION
**Pull request by stewart-yu**
**What this PR does / why we need it**:
No test file for testutil.go

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jayunit100** [comment]
Should we add a test for Codec just for completeness ? Otherwise lgtm

**Comment by stewart-yu** [comment]
Yeah， I'll finish it.

**Comment by stewart-yu** [comment]
@jayunit100 @resouer  /assign @k82cn

**Pull request merged**
