### PR TITLE
Fix node-perf test tf-wide-deep: bumped image version, and removed arm64 arch testing #109295

### LINKED ISSUE #109295: [sig-node] Node Performance Testing [Serial] [Slow] Run node performance testing with pre-defined workloads TensorFlow workload
### Which jobs are failing?

[sig-node-containerd#node-kubelet-containerd-performance-test](https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-performance-test)

### Which tests are failing?

E2eNode Suite.[sig-node] Node Performance Testing [Serial] [Slow] Run node performance testing with pre-defined workloads TensorFlow workload

### Since when has it been failing?

From the testgrid, it has been 1/2 flaky since the start of history (03/20/2022) and has been failing constantly (0/2) since 04/01/2022

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-performance-test

### Reason for failure (if possible)

```
E2eNode Suite: [sig-node] Node Performance Testing [Serial] [Slow] Run node performance testing with pre-defined workloads TensorFlow workload expand_less | 37s
-- | --
{ Failure test/e2e_node/node_perf_test.go:172 wait for pod "tensorflow-wide-deep-pod" to succeed Expected success, but got an error:     <*errors.errorString \| 0xc000722840>: {         s: "pod \"tensorflow-wide-deep-pod\" failed with reason: \"\", message: \"\"",     }     pod "tensorflow-wide-deep-pod" failed with reason: "", message: "" test/e2e/framework/pods.go:240}
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by xmcqueen**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

This PR is to fix the failing sig-node perf test documented in this tracking ticket: #109295 

The previous PR #112869 did not produce a fully functional build.  The multi-arch builds failed.

This PR upgrades the linux to *buster* and bumps the *QEMUVERSION* to v7.1.0-2.

It also includes the missing version bump that should have been part of the previous PR.  This is expected to produce version 1.3 of the node-perf/tf-wide-deep image from this testgrid link:

https://testgrid.k8s.io/sig-testing-images#post-kubernetes-push-e2e-node-perf-tf-wide-deep-test-images

#### Which issue(s) this PR fixes:

Fixes #109295

https://testgrid.k8s.io/sig-testing-images#post-kubernetes-push-e2e-node-perf-tf-wide-deep-test-images

Fixes #

#### Special notes for your reviewer:

Tested locally via local build and local execution of tensorflow job with the resulting image (amd64 only).

`make all WHAT=node-perf/tf-wide-deep` 

Test system has very poor qemu support so I could not verify the fix to the multi-arch builds, but the local build does confirm the upgrades were successful applied, and that they produce a runnable docker image.  The intended tensorflow job did run in the new upgraded docker image for amd64.

Quite a bit more testing was done, and notes are available.

#### Does this PR introduce a user-facing change?
NONE

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by xmcqueen** [comment]
I found a server where I can do wider testing, including full testing of the multiarch builds.

This PR is close, but its not good enough.

I'll add to this PR and update when I get both the node-perf/tf-wide-deep build going, and I'll run the build for the other images to verify the jobs pass.

**Comment by mkumatag** [comment]
> I found a server where I can do wider testing, including full testing of the multiarch builds.
> 
> This PR is close, but its not good enough.
> 
> I'll add to this PR and update when I get both the node-perf/tf-wide-deep build going, and I'll run the build for the other images to verify the jobs pass.

yes, that will be helpful..
/hold

**Comment by xmcqueen** [comment]
I think have the appropriate solution.

This commit restores the tf-wide-deep test to running condition for linux/arm64.  It has been tested (see below).  I could not get the tensorflow jobs to run on the linux/arch64 without an unreasonable level of effort that would impact the complexity of the test image build.  Nor could I upgrade to an equivalent or siimilar tensorflow test for the same reasons.  This commit gets the load existing tf-wide-deep test working again, by removing linux/amd64 from the tested architectures (see below).  

The other load tests do still test the other architectures (see below).

There is no longer a risk due to bumping QEMUVERSION.  **The QEMUVERSION bump is herein reverted**.

This PR fixes the node-perf/tf-wide-deep, and it has no risk of directly effecting anything else.

### testing

- node-perf/tf-wide-deep (linux/arm64)
- node-perf/npb-ep (linux/amd64, linux/s390x, linux/ppc64le)

### test results truncated

here it is running node-perf/tf-wide-deep (linux/amd64)

```less
bmcqueen@instance-2:~$ docker image ls | grep 779db9bcecc5
registry.k8s.io/e2e-test-images/node-perf/tf-wide-deep   1.3-linux-amd64     779db9bcecc5   36 minutes ago   546MB
bmcqueen@instance-2:~$ docker run -it 779db9bcecc5 sh | head
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
```
here is a different test node-perf/npb-ep running linux/amd64
```less
bmcqueen@instance-2:~$ docker image ls | grep b588763fb806
registry.k8s.io/e2e-test-images/node-perf/npb-ep         1.2-linux-amd64     b588763fb806   45 minutes ago   96.4MB
bmcqueen@instance-2:~$ docker run -it b588763fb806 sh | head
 NAS Parallel Benchmarks (NPB3.3-OMP) - EP Benchmark

 Number of random numbers generated:    137438953472
 Number of available threads:                      2

^Cbmcqueen@instance-2:~$
```

here is node-perf/npb-ep running linux/s390x
```less
bmcqueen@instance-2:~$ docker image ls | grep ad0275a7083f
registry.k8s.io/e2e-test-images/node-perf/npb-ep         1.2-linux-s390x     ad0275a7083f   15 minutes ago   97.8MB
bmcqueen@instance-2:~$ 
bmcqueen@instance-2:~/kubernetes/test/images$ docker run -it ad0275a7083f sh
WARNING: The requested image's platform (linux/s390x) does not match the detected host platform (linux/amd64) and no specific platform was requested

 NAS Parallel Benchmarks (NPB3.3-OMP) - EP Benchmark

 Number of random numbers generated:    137438953472
 Number of available threads:                      2
```

here it is running node-perf/npb-ep (linux/ppc64le)

```less
bmcqueen@instance-2:~$ docker image ls | grep 368d8a4796ea
registry.k8s.io/e2e-test-images/node-perf/npb-ep         1.2-linux-ppc64le   368d8a4796ea   19 minutes ago   131MB
bmcqueen@instance-2:~$ 
bmcqueen@instance-2:~/kubernetes/test/images$ docker run -it 368d8a4796ea sh
WARNING: The requested image's platform (linux/ppc64le) does not match the detected host platform (linux/amd64) and no specific platform was requested

 NAS Parallel Benchmarks (NPB3.3-OMP) - EP Benchmark

 Number of random numbers generated:    137438953472
 Number of available threads:                      2
```

### **notes about tf-wide-deep and tensorflow**

- its very old and was not ported to tf2
- it is [specifically deprecated](https://github.com/tensorflow/models/pull/6503#issuecomment-618827609) in tf2
- tf version 2 is already very far advanced from version 1
- tensorflow support for aarch64 is very limited
- the required published tensorflow modules do not install without conflict on aarch64
- to upgrade to tf2 requires pulling bazel into the docker build
- to upgrade to tf2 requires many more modules some of which need to be built on-demand for aarch64

**Comment by xmcqueen** [comment]
The title of the PR is now quite wrong.  Shall I revise the title?  It should be like, "bumped image version, and removed arm64 testing for tf-wide-deep".

**Comment by BenTheElder** [comment]
Thank you, I think this is a reasonable approach to deflake the test, seeing as we don't have this running on other architectures.

Long term I'd encourage multi-arch test images, but I think SIG node has somewhat more complex problems like this than what we can do with https://github.com/kubernetes/kubernetes/tree/master/test/images/agnhost

**Review by SergeyKanzhelev — APPROVED** [review]
/unhold
/release-note-none
/priority important-soon
/triage accepted
/lgtm
/approve

**Pull request merged**
