### PR TITLE
Fix a broken link in the fluentd-elasticsearch addon README

### PR DESCRIPTION
**Pull request by cimomo**
**What this PR does / why we need it**:
Fix a broken link in the fluentd-elasticsearch addon README.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by coffeepac — APPROVED** [review]
Thanks for catching this!

**Comment by cimomo** [comment]
Thank you @coffeepac @cblecker for the review.

**Pull request merged**
