### PR TITLE
Export HAIRPIN_MODE environment variable for soaking test.

### PR DESCRIPTION
**Pull request by dchen1107**
cc/ @bprashanth

### CODE REVIEW

**Comment by dchen1107** [comment]
#20096

**Comment by bprashanth** [comment]
We both simultaneously created the exact same pr. LGTM.

**Comment by ixdy** [comment]
yup, LGTM

**Comment by dchen1107** [comment]
I am manually merging this so that we can kick out soaking test asap.

**Comment by ixdy** [comment]
Note that the continuous e2e soak job downloads `hack/jenkins/e2e.sh` from master each run, so there's no need to rebuild the soak cluster.

**Comment by bprashanth** [comment]
>  each run, so there's no need to rebuild the soak cluster.

Meaning currently we're at 4675, so 4676 will have it? or next week's push?

**Comment by ixdy** [comment]
Build 4676 should get it.

**Pull request merged**
