### PR TITLE
Prune internal aggregator client/informer/ from aggregator

### PR DESCRIPTION
**Pull request by yue9944882**
/hold
/sig apimachinery
/kind cleanup

this pull will be pending until we fixes code-generating scripts #68559

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yue9944882** [comment]
ref: #70217 (i guess?)

**Comment by sttts** [comment]
@deads2k @lavalamp @liggitt what do you think about starting removing internal clients whereever possible?

**Comment by liggitt** [comment]
> @deads2k @lavalamp @liggitt what do you think about starting removing internal clients whereever possible?

probably makes sense. there are few (no?) places we're still recommending they be used, and they have problems with sparse versions and cross-group subresources.

**Comment by deads2k** [comment]
> @deads2k @lavalamp @liggitt what do you think about starting removing internal clients whereever possible?

Yes, we probably should.

**Comment by yue9944882** [comment]
/assign @sttts 

it's now happy for a review 👌🏻

**Pull request closed without merging**
