### PR TITLE
Reduce simultaneous calls to quota queries

### LINKED ISSUE #22422: Admission controllers can cause unnecessary significant load on apiserver
Recently we observed high latencies on POST pods on our scalability tests.
For more context see: https://github.com/kubernetes/kubernetes/issues/22340

It appeared to be throttling related, e.g.:

```
W0302 21:38:28.190204       5 request.go:627] Throttling request took 1.281100127s, request: GET:http://127.0.0.1:8080/api/v1/namespaces/e2e-tests-load-6cqci/limitranges
I0302 21:38:28.191235       5 handlers.go:152] GET /api/v1/namespaces/e2e-tests-load-6cqci/limitranges: (853.53Âµs) 200 [[kube-apiserver/v1.2.0 (linux/amd64) kubernetes/2cf9157] 127.0.0.1:58515]
I0302 21:38:28.193396       5 trace.go:57] Trace "Create /api/v1/namespaces/e2e-tests-load-6cqci/pods" (started 2016-03-02 21:38:26.908795629 +0000 UTC):
[20.412Âµs] [20.412Âµs] About to convert to expected version
[239.558Âµs] [219.146Âµs] Conversion done
[1.282815499s] [1.282575941s] About to store object in database
[1.284377959s] [1.56246ms] Object stored in database
[1.284389884s] [11.925Âµs] Self-link added
[1.284548334s] [158.45Âµs] END
```

As an example look at resource quota admission controller.
In https://github.com/kubernetes/kubernetes/pull/20446 there was some fallback added to use lru cache in case of on objects.
However, not what happens if we are sending multiple POST pods at the same time to apiserver.
What happens in Admit() if there are no results in Indexer, we list ResourceQuotas.
But if there are multiple calls at the same time, there can be multiple LISTs before the cache is updated:
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/resourcequota/admission.go#L131
But this can cause throttling of these requests.

What we should do is: if there is List() in flight, we should wait until it is finished and lookupCache is updated.

@derekwaynecarr

### PR DESCRIPTION
**Pull request by DrAuYueng**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Use singleflight to avoid throttling if there are multiple quota queries at the same time and cache has just expired.
#### Which issue(s) this PR fixes:

Follows https://github.com/kubernetes/kubernetes/pull/112696
Fixes https://github.com/kubernetes/kubernetes/issues/22422

#### Does this PR introduce a user-facing change?

```release-note
None.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by DrAuYueng** [comment]
@liggitt @aojea Please take a moment to review the code, thanks.

**Comment by moficodes** [comment]
@aojea @liggitt 

1.28 Bug Triage Shadow here.

Just checking-in, if this is still on track for the 1.28 release?

**Comment by furkatgofurov7** [comment]
@DrAuYueng hey, Bug Triage Team here!

Can you please label it with kind and priority? Also, this PR has not been updated for long time, so I'd like to check what's the status and if there are plans moving it forward.

Please be aware that the code freeze is starting [01:00 UTC Wednesday 19th July 2023 / 18:00 PDT Tuesday 18th July 2023](https://everytimezone.com/s/72ee8496) (about less than 2 weeks from now).

As the PR is tagged for 1.28, is it still planned for this release?

**Comment by DrAuYueng** [comment]
Rebased.

**Comment by moficodes** [comment]
Week 9 update: Code Freeze is approaching!

Hey! We are currently in Week 9, and Code Freeze is just over a week away. It will begin at 01:00 UTC on Wednesday, 19th July 2023 / 18:00 PDT on Tuesday, 18th July 2023. Please ensure all necessary submissions are made before the deadline. Let me know if you need any assistance. :)

**Pull request closed without merging**
