### PR TITLE
Fix an else branch in trusty/configure-helper.sh

### PR DESCRIPTION
**Pull request by yujuhong**
Similar to #37358, for fixing #37257 on trusty.

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37388)

### CODE REVIEW

**Comment by yujuhong** [comment]
@k8s-bot cvm gke e2e test this.

**Comment by roberthbailey** [comment]
Dupe of https://github.com/kubernetes/kubernetes/pull/37358 (sorry I didn't cc you on that PR).

**Comment by roberthbailey** [comment]
Sorry, just realized this was for the trusty code.

**Pull request merged**
