### PR TITLE
enhance kubectl config delete command

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:
ref #20605
```kubectl config delete-cluster``` and ```kubectl config delete-context``` should support delete multi cluster or context

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
thanks

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/sig cli

@kubernetes/sig-cli-feature-requests

**Comment by zjj2wry** [comment]
cc @kubernetes/sig-cli-pr-reviews we should not limit user delete multi cluster or context?

**Comment by zjj2wry** [comment]
@deads2k Do you have bandwidth review this? thanks.

**Pull request closed without merging**
