### PR TITLE
Modify e2e tests to use priorityClass beta client version & switch priorityClass to beta

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
**What this PR does / why we need it**:
/cc @bsalamat @aveshagarwal @liggitt 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #57471

**Special notes for your reviewer**:
Once #57963 merges, this could go in.

**Release note**:

```release-note
Modify e2e tests to use priorityClass beta version & switch priorityClass feature to beta
```

### CODE REVIEW

**Review by bsalamat — COMMENTED** [review]
/lgtm

Thanks, @ravisantoshgudimetla!

**Comment by ravisantoshgudimetla** [comment]
Thanks for review @bsalamat. Shouldn't sig-scheduling-approvers be part of test/owners as we have scheduling directory in test/e2e and test/integration?

**Comment by bsalamat** [comment]
> Not related to this PR, shouldn't sig-scheduling-approvers be part of test/owners as we have scheduling directory in test/e2e and test/integration?

Apparently, the convention is to add individuals to the test/OWNERS (with the exception of sig-test-approvers). I can try adding myself there.

**Comment by ravisantoshgudimetla** [comment]
Waiting on this PR to be merged to get sig-cli lgtm- https://github.com/kubernetes/kubernetes/pull/63928. This PR removes versioned printer..

**Comment by bsalamat** [comment]
@kubernetes/sig-testing-pr-reviews @kubernetes/sig-cluster-lifecycle-api-reviews for approval

**Comment by liggitt** [comment]
enabling priority by default is holding until the quota PR is reviewed and merged, correct?

**Comment by bsalamat** [comment]
> enabling priority by default is holding until the quota PR is reviewed and merged, correct?

The quota PR is not a pre-requisite for enabling priority. At least we never had any such plan, but it would be great if both can be done in 1.11.

**Comment by bsalamat** [comment]
We need to merge this ASAP to enable Beta version of priority and preemption by default and start running e2e tests with the feature.

**Comment by dims** [comment]
/assign @deads2k
/sig node

cc @liggitt @kubernetes/sig-node-pr-reviews

**Comment by ravisantoshgudimetla** [comment]
ping @liggit - Since #57963 got approval and it is going to merge, can you please approve this PR?

**Comment by liggitt** [comment]
/lgtm
the change to v1beta1 types in the e2e tests looks good to me.

> We need to merge this ASAP to enable Beta version of priority and preemption by default and start running e2e tests with the feature.

agreed. can you link to the PR enabling this feature in a CI job?

**Pull request merged**
