### PR TITLE
Promote apiserver.config.k8s.io/v1, kind=WebhookAdmissionConfiguration

### PR DESCRIPTION
**Pull request by liggitt**
This promotes the WebhookAdmissionConfiguration config file version to apiserver.config.k8s.io/v1 API group. The corresponding feature (mutating/validating webhook admission) went to v1 in 1.16.0

This PR:
* This promotes `apiserver.config.k8s.io/v1alpha1, kind=WebhookAdmission` to `apiserver.config.k8s.io/v1, kind=WebhookAdmissionConfiguration`
  * The `Configuration` suffix is used consistently for top-level configuration types
* adds unit tests for decoding v1alpha1 and v1 configs
* docs update in https://github.com/kubernetes/website/pull/17549

```release-note
kube-apiserver: Authentication configuration for mutating and validating admission webhooks referenced from an `--admission-control-config-file` can now be specified with `apiVersion: apiserver.config.k8s.io/v1, kind: WebhookAdmissionConfiguration`.
```

/sig api-machinery
/cc @deads2k

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm

mismatching the struct and serialization is annoying, but I guess we should deal with it until we drop the alpha version in a year or so.

**Comment by liggitt** [comment]
the pull-kubernetes-node-e2e-containerd failure is known, not a flake, non-blocking, and being worked on - https://github.com/kubernetes/kubernetes/issues/85040

**Pull request merged**
