### PR TITLE
Automated cherry pick of #41929 #42974 upstream release 1.6

### PR DESCRIPTION
**Pull request by BaluDontu**
Cherry pick of #41929 #42974 on release-1.6.

#41929: vSphere Cloud Provider: Fstype in storage class
#42974: VSAN policy support for storage volume provisioning inside kubernetes

@saad-ali

### CODE REVIEW

**Comment by BaluDontu** [comment]
@saad-ali : Can you please take a look at this PR. I didn't have the cherry-pick label on this PR. Can you add one.

**Comment by enisoc** [comment]
@BaluDontu On the surface, this looks like it adds a new capability, which is not allowed in patch releases. If this is somehow needed to fix a bug, please explain or link to context that shows the severity of the issue.

**Comment by BaluDontu** [comment]
@enisoc : Yes its a new capability. The problem is right now we only limit our users to create persistent volumes of a single file system type. This is too narrow for us.
Allowing users to have create a persistent volume of multiple file system types and configuring it with a VSAN policy is a big ask from our customers.

The point is that we just missed the 1.6 release cut by a few days. Isn't possible to have these included as part of patch releases ? Otherwise we would have wait next 1.7 release for these features which would be too late for us.

**Comment by enisoc** [comment]
@saad-ali @childsb Could one of you weigh in on behalf of sig-storage? Is this change appropriate for a patch release?

**Comment by BaluDontu** [comment]
@saad-ali @childsb : Any updates on this one?

**Comment by saad-ali** [comment]
@enisoc By the [strictly definition of a patch release](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/versioning.md#patch-releases
), since this introduces new functionality, it does not qualify:
```
Patch releases are intended for critical bug fixes to the latest minor version, such as addressing security vulnerabilities, fixes to problems affecting a large number of users, severe problems with no workaround, and blockers for products based on Kubernetes.

They should not contain miscellaneous feature additions or improvements, and especially no incompatibilities should be introduced between patch versions of the same minor version (or even major version).
```

That said it is isolated to the VSphere volume plugin and the changes appear to be backwards compatible, so I would be ok granting an exception. Final call is yours.

**Comment by enisoc** [comment]
@saad-ali Thanks. I will go with your recommendation since it's in the storage area.

@k8s-bot ok to test

/lgtm

**Comment by BaluDontu** [comment]
@enisoc : Can you rerun the test - @k8s-bot cvm gce e2e test this?

**Comment by enisoc** [comment]
It looks like you have the power. :)

**Pull request merged**
