### PR TITLE
Fix shellcheck output streams

### LINKED ISSUE #102975: shellcheck output not capture properly by shell2junit in CI
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102960/pull-kubernetes-verify/1405766623234625536

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/102960/pull-kubernetes-verify/1405766623234625536/artifacts/junit_verify.xml

junit output:

```
Unable to find image 'koalaman/shellcheck-alpine:v0.7.1@sha256:d6147f30864ddb7c9cf983fc277d345bc315e798e309ddf70062b194843ee252' locally
docker.io/koalaman/shellcheck-alpine@sha256:d6147f30864ddb7c9cf983fc277d345bc315e798e309ddf70062b194843ee252: Pulling from koalaman/shellcheck-alpine
aad63a933944: Pulling fs layer
8f6fa390fe7b: Pulling fs layer
8f6fa390fe7b: Verifying Checksum
8f6fa390fe7b: Download complete
aad63a933944: Verifying Checksum
aad63a933944: Download complete
aad63a933944: Pull complete
8f6fa390fe7b: Pull complete
Digest: sha256:d6147f30864ddb7c9cf983fc277d345bc315e798e309ddf70062b194843ee252
Status: Downloaded newer image for koalaman/shellcheck-alpine@sha256:d6147f30864ddb7c9cf983fc277d345bc315e798e309ddf70062b194843ee252

Please review the above warnings. You can test via "./hack/verify-shellcheck.sh"
If the above warnings do not make sense, you can exempt this warning with a comment
 (if your reviewer is okay with it).
In general please prefer to fix the error, we have already disabled specific lints
 that the project chooses to ignore.
See: https://github.com/koalaman/shellcheck/wiki/Ignore#ignoring-one-specific-instance-in-a-file
```

full output with actual error (expand build-log.txt and grep around)

```
Verifying verify-shellcheck.sh
+++ Running case: verify.shellcheck 
+++ working dir: /home/prow/go/src/k8s.io/kubernetes
+++ command: bash "hack/make-rules/../../hack/verify-shellcheck.sh"
Using shellcheck 0.7.1 docker image.
Unable to find image 'koalaman/shellcheck-alpine:v0.7.1@sha256:d6147f30864ddb7c9cf983fc277d345bc315e798e309ddf70062b194843ee252' locally
docker.io/koalaman/shellcheck-alpine@sha256:d6147f30864ddb7c9cf983fc277d345bc315e798e309ddf70062b194843ee252: Pulling from koalaman/shellcheck-alpine
aad63a933944: Pulling fs layer
8f6fa390fe7b: Pulling fs layer
8f6fa390fe7b: Verifying Checksum
8f6fa390fe7b: Download complete
aad63a933944: Verifying Checksum
aad63a933944: Download complete
aad63a933944: Pull complete
8f6fa390fe7b: Pull complete
Digest: sha256:d6147f30864ddb7c9cf983fc277d345bc315e798e309ddf70062b194843ee252
Status: Downloaded newer image for koalaman/shellcheck-alpine@sha256:d6147f30864ddb7c9cf983fc277d345bc315e798e309ddf70062b194843ee252
In ./hack/make-rules/test-integration.sh line 74:
      KUBE_RACE=""
      ^-------^ SC2034: KUBE_RACE appears unused. Verify use (or export if used externally).
For more information:
  https://www.shellcheck.net/wiki/SC2034 -- KUBE_RACE appears unused. Verify ...
Please review the above warnings. You can test via "./hack/verify-shellcheck.sh"
If the above warnings do not make sense, you can exempt this warning with a comment
 (if your reviewer is okay with it).
In general please prefer to fix the error, we have already disabled specific lints
 that the project chooses to ignore.
See: https://github.com/koalaman/shellcheck/wiki/Ignore#ignoring-one-specific-instance-in-a-file
+++ exit code: 1
+++ error: 1
FAILED   verify-shellcheck.sh	89s
```

we want the actual error to be included in the junit so it will be displayed at the top, right now the error at the top is confusing and useless.

/sig testing

### PR DESCRIPTION
**Pull request by YuviGold**
#### What type of PR is this?

/kind documentation
/kind failing-test

#### What this PR does / why we need it:

`shellcheck` errors are printed to stdout by default, hence they need to be redirected
to stderr in order to be well parsed for Junit representation by `juLog` function.

#### Which issue(s) this PR fixes:

Fixes #102975

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

Now the generated Junit would have the correct failures in it to be shown later on by Spyglass:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite failures="1" assertions="" name="verify" tests="1" errors="1" time="33.3179">
    
    <testcase assertions="1" name="shellcheck" time="33.3179" classname="verify">
    
      <failure type="ScriptError" message="Script Error"><![CDATA[
In ./hack/verify-shellcheck.sh line 25:
BLA=3
^-^ SC2034: BLA appears unused. Verify use (or export if used externally).

For more information:
  https://www.shellcheck.net/wiki/SC2034 -- BLA appears unused. Verify use (o...]]></failure>
  
    <system-err><![CDATA[
In ./hack/verify-shellcheck.sh line 25:
BLA=3
^-^ SC2034: BLA appears unused. Verify use (or export if used externally).

For more information:
  https://www.shellcheck.net/wiki/SC2034 -- BLA appears unused. Verify use (o...]]></system-err>
    </testcase>
  
    </testsuite>
</testsuites>
```

### CODE REVIEW

**Comment by YuviGold** [comment]
e2e flaky test failed
/retest

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve
🎉  thank you!

**Pull request merged**
