### PR TITLE
examples/cluster-dns and examples/downward-api to v1

### PR DESCRIPTION
**Pull request by caesarxuchao**
#9286

@nikhiljindal @krousey @bgrant0607

### CODE REVIEW

**Comment by yifan-gu** [comment]
FWIW, I was not able to run this example on localhost or gce yesterday and today. 
/cc @ddysher

**Comment by ddysher** [comment]
@yifan-gu thanks
I think I know the reason, just need to find some time to bring up a cluster ..

**Comment by caesarxuchao** [comment]
Thanks @yifan-gu and @ddysher. I guess this PR is not going to make things worse, right?

**Comment by yifan-gu** [comment]
@caesarxuchao This LGTM :)

**Comment by ddysher** [comment]
Unable to bring up a cluster due to #9540  :(

**Pull request merged**
