### PR TITLE
Update to use go1.12.10

### PR DESCRIPTION
**Pull request by cblecker**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
ref #83138

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Update to go 1.12.10
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by cblecker** [comment]
@javier-b-perez @BenTheElder would one of you mind having a look at building this image?

**Comment by BenTheElder** [comment]
LGTM

**Comment by BenTheElder** [comment]
pushed `staging-k8s.gcr.io/kube-cross:v1.12.10-1@sha256:c5a1a501310883f47642cc711fe5228d585d7e881acb661387bcb00e2e674a2a`, will need to file an image promotion CL

**Comment by BenTheElder** [comment]
cl/271260136 promotes this image, pending approve + lgtm

**Comment by BenTheElder** [comment]
/uncc @ixdy 
Jeff you should probably update OWNERS :^)

**Comment by BenTheElder** [comment]
[also note the hold is until the image exists, so we don't get retest spam]

**Comment by BenTheElder** [comment]
cl/271260136 has been submitted but the image is not available yet

**Comment by BenTheElder** [comment]
we should also update test-infra images to reflect this

**Pull request merged**
