### PR TITLE
Create DeepCopy benchmarks

### PR DESCRIPTION
**Pull request by wojtek-t**
cc @fgrzadkowski

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
LGTM. Will merge on green

**Comment by lavalamp** [comment]
This package import isn't good... pkg/conversion should be separable from the rest of the repo. Can you put the benchmark in e.g. api package?

**Comment by wojtek-t** [comment]
Moved to pkg/api.

PTAL

**Comment by fgrzadkowski** [comment]
Travis didn't even start. I'm gonna merge it as shippable is green.

**Pull request merged**
