### PR TITLE
alternate random string generator - avoid /dev/random

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

/dev/random takes way too much time. let's Avoid `/dev/random`, and use $RANDOM which is an internal Bash function.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by immutableT** [comment]
$RANDOM should not be used for generating encryption keys.
http://tldp.org/LDP/abs/html/randomvar.html

**Comment by dims** [comment]
@immutableT then let's please revert the PR while we figure out how to unblock everyone else

**Comment by immutableT** [comment]
Could you, please, describe the blocking issue.

**Comment by dims** [comment]
@immutableT yep, we blocked all commits to k/k main repository - https://github.com/kubernetes/kubernetes/issues/61893

**Comment by immutableT** [comment]
Ok, reverting [61902](https://github.com/kubernetes/kubernetes/pull/61902)

**Pull request closed without merging**
