### PR TITLE
Automated cherry pick of #56969

### PR DESCRIPTION
**Pull request by mwielgus**
Cherry pick of #56969 on release-1.9.

#56969: Cluster Autoscaler 1.1.0

### CODE REVIEW

**Comment by enisoc** [comment]
@mwielgus We're still in code freeze, so it should be enough that this went into master, unless I'm misunderstanding your intent.

**Comment by mwielgus** [comment]
Will it be automatically cherry-picked to 1.9?

**Comment by enisoc** [comment]
@mwielgus Yes, we are still in the fast-forward phase, so anything that's already in master as of now will make it into release-1.9 automatically.

**Pull request closed without merging**
