### PR TITLE
Fix table in getting-started-guides README.md

### PR DESCRIPTION
**Pull request by dchen1107**
cc/ @erictune

### CODE REVIEW

**Comment by dchen1107** [comment]
cc/ @zmerlynn

**Comment by zmerlynn** [comment]
LGTM

**Comment by thockin** [comment]
@erictune is "latest" ok with you?

**Comment by erictune** [comment]
lgtm

**Comment by erictune** [comment]
lgtm

**Comment by dchen1107** [comment]
ok to test

**Pull request merged**
