### PR TITLE
remove redundant comment

### PR DESCRIPTION
**Pull request by AxeZhan**
#### What type of PR is this?
/kind cleanup
/sig testing
/sig release

#### What this PR does / why we need it:
There is a line of comment that is redundant, and I just removed it
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
Hi, everyone. I'm just starting to learn kubernetes, and I really want to make my contribution to the  community. This is my first pull request, just to get familiar with the process. Please correct me if something is wrong. Thanks.
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ping035627** [comment]
ok-to-test

**Comment by kidddddddddddddddddddddd** [comment]
/cc @deads2k  @wojtek-t 
Please reivew the PR, thanks!

**Comment by sftim** [comment]
@kidddddddddddddddddddddd thanks for working on this. We might be able to make an exception here but _usually_ we ask contributors to [avoid trivial edits](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits).

**Comment by kidddddddddddddddddddddd** [comment]
> @kidddddddddddddddddddddd thanks for working on this. We might be able to make an exception here but _usually_ we ask contributors to [avoid trivial edits](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits).

I'm sorry I really didn't know about this before, it won't happen again

**Comment by kidddddddddddddddddddddd** [comment]
@deads2k hi can you review this pr? really appreciate it

**Pull request closed without merging**
