### PR TITLE
core/v1: remove note about hostAliases not working with hostNetwork

### LINKED ISSUE #122420: PodSpec.hostAliases has a potentially misleading comment about hostNetwork
### What happened?

there is a note above hostAliases that this feature does not work with hostNework=true, yet it seems it does:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/core/v1/types.go#L3672-L3679

> This is only valid for non-hostNetwork pods.

when testing with a hostNetwork pod + hostAliases, there are no errors in kubelet logs at --v=10 related to this, in fact i don't see any hostAlias entries at all in there.

i could not find anything blocking this in the kubelet, in fact there is normal handling of hostNetwork:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L330

i could not find any validation performed on the hostAliases field of PodSpec if hostNetwork is true on the API level.
https://github.com/kubernetes/kubernetes/blob/38f4f9d8c4c0519917464b40997e8bcb478c8f8c/pkg/apis/core/validation/validation.go#L3888

i could not find any unit tests or e2e tests related to this.

### What did you expect to happen?

- the godoc should contain valid information
- if the feature is not supposed to work, it must be patched to not have the entries in the hosts file (perhaps?)
- we should have tests that ensure this type of requirement is guaranteed

### How can we reproduce it (as minimally and precisely as possible)?

these steps confirm that a static pod with hostNework (deployed by kubeadm) does make use of hostAliases.

- create a kubeadm single node cluster directly with `kubeadm init` or one with `kind create cluster`
- modify the `/etc/kubernetes/manifests/kube-apiserver.yaml` to include:
```
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
```
- wait some time for the new static pod spec to resync
- find the PID of the kube-apiserver
```
ps -ax | grep kube-apiserver
```
- get the hosts file
```
cat /proc/<pid>/root/etc/hosts
```

```
# Kubernetes-managed hosts file (host network).
127.0.0.1	localhost
127.0.1.1	lubo-it

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

# Entries added by HostAliases.
127.0.0.1	kubernetes
```

```
$ sudo cat /etc/kubernetes/manifests/kube-apiserver.yaml
```

```
...
  hostNetwork: true
  hostAliases:
  - hostnames:
    - kubernetes
    ip: 127.0.0.1
...
```

### Anything else we need to know?

n/a

### Kubernetes version

latest master 1.30.0-alpha.0

### Cloud provider

not applicable

### OS version

<details>

```
$ uname -a
Linux lubo-it 5.8.0-38-generic #43~20.04.1-Ubuntu SMP Tue Jan 12 16:39:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

</details>

### Install tools

kubeadm

### Container runtime (CRI) and version (if applicable)

containerd github.com/containerd/containerd v1.6.14 9ba4b250366a5ddde94bb7c9d1def331423aa323

### Related plugins (CNI, CSI, ...) and versions (if applicable)

kindnet

-----------------

### Changes

- add test:
https://github.com/kubernetes/kubernetes/pull/122423

- update godoc:
https://github.com/kubernetes/kubernetes/pull/122422

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?

/kind cleanup documentation

#### What this PR does / why we need it:

Support for this was added in 1.8 by PR #50646.
Local tests confirm that the feature indeed works. E2e tests seem to be missing.

#### Which issue(s) this PR fixes:

fixes https://github.com/kubernetes/kubernetes/issues/122420

#### Special notes for your reviewer:

a working test was added here:
- https://github.com/kubernetes/kubernetes/pull/122423

#### Does this PR introduce a user-facing change?

```release-note
PodSpec API: remove note that hostAliases are not supported on hostNetwork Pods. The feature has been supported since v1.8.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
some files in staging were not updated, no idea why:
```
$ grep "HostAliases is an optional" * -rl 
src/k8s.io/kubectl/testdata/openapi/v3/api/v1.json
src/k8s.io/kubectl/testdata/openapi/v3/apis/apps/v1.json
src/k8s.io/kubectl/testdata/openapi/swagger.json
src/k8s.io/kubectl/pkg/explain/v2/templates/batch.k8s.io_v1.json
src/k8s.io/cli-runtime/artifacts/openapi/swagger-with-shared-parameters.json
src/k8s.io/cli-runtime/artifacts/openapi/swagger.json
src/k8s.io/apimachinery/pkg/util/managedfields/internal/testdata/swagger.json
src/k8s.io/client-go/openapi/openapitest/testdata/api__v1_openapi.json
src/k8s.io/client-go/openapi/openapitest/testdata/apis__batch__v1_openapi.json
src/k8s.io/client-go/openapi/openapitest/testdata/apis__apps__v1_openapi.json
src/k8s.io/client-go/discovery/testdata/apis/batch/v1beta1.json
src/k8s.io/client-go/discovery/testdata/apis/batch/v1.json
```

**Comment by aojea** [comment]
> some files in staging were not updated, no idea why:
> 
> ```
> $ grep "HostAliases is an optional" * -rl 
> src/k8s.io/kubectl/testdata/openapi/v3/api/v1.json
> src/k8s.io/kubectl/testdata/openapi/v3/apis/apps/v1.json
> src/k8s.io/kubectl/testdata/openapi/swagger.json
> src/k8s.io/kubectl/pkg/explain/v2/templates/batch.k8s.io_v1.json
> src/k8s.io/cli-runtime/artifacts/openapi/swagger-with-shared-parameters.json
> src/k8s.io/cli-runtime/artifacts/openapi/swagger.json
> src/k8s.io/apimachinery/pkg/util/managedfields/internal/testdata/swagger.json
> src/k8s.io/client-go/openapi/openapitest/testdata/api__v1_openapi.json
> src/k8s.io/client-go/openapi/openapitest/testdata/apis__batch__v1_openapi.json
> src/k8s.io/client-go/openapi/openapitest/testdata/apis__apps__v1_openapi.json
> src/k8s.io/client-go/discovery/testdata/apis/batch/v1beta1.json
> src/k8s.io/client-go/discovery/testdata/apis/batch/v1.json
> ```
> 
> maybe these files were manually copied as testdata.

/lgtm
/approve

/assign @thockin

**Comment by neolit123** [comment]
/assign @msau42 @liggitt 
PTAL, when possible.

**Comment by pacoxu** [comment]
ACK for approval

/lgtm
/approve

**Comment by liggitt** [comment]
seems reasonable, but will defer to @thockin's ack

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by BenTheElder** [comment]
/retest
https://github.com/kubernetes/test-infra/issues/32157

**Pull request merged**
