### PR TITLE
[trival] fix typo

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
some file word spell error that amend correct
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE

### CODE REVIEW

**Comment by jianglingxia** [comment]
ping @mikedanese @mfojtik 
/assign @mikedanese
thanks!

**Comment by xiangpengzhao** [comment]
@jianglingxia please remove the **```** and just leave `NONE` in the "Release note:" block when you creates PR. Then the bot can add `release-note-none` label automatically.

**Comment by jianglingxia** [comment]
ok ,thanks for your advices ,but why the pr always failed?

**Comment by xiangpengzhao** [comment]
Seems like it's due to flake. Try to retest another time.

**Comment by cblecker** [comment]
/unassign
Please do not randomly assign people. Your PR is already assigned, and was opened only two days ago.

**Pull request merged**
