### PR TITLE
cadvisor bump to 0.16.0.2

### PR DESCRIPTION
**Pull request by jimmidyson**

### CODE REVIEW

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
@jimmidyson: Just to be sure, can you run e2e a couple of times? I will try to kick the bot as well to run the e2e a few times.

**Comment by jimmidyson** [comment]
Good idea :) One problem I had was running e2e even with pre-broken PR was that it some tests failed for me anyway & I have no idea if there are known flakes.

**Comment by vishh** [comment]
Some tests can be skipped. I think hack/jenkins/e2e.sh has a list of flaky
tests.

**Comment by jimmidyson** [comment]
@vishh Run this through twice successfully, at least the flakes are unrelated AFAICT.

**Comment by vishh** [comment]
@k8s-bot: test this please

**Comment by jimmidyson** [comment]
Same failure as always: `[Fail] Services [It] should be able to up and down services`

**Comment by jimmidyson** [comment]
@vishh Would you be able to rekick this too?

**Comment by vishh** [comment]
@k8s-bot: ok to test

**Comment by yujuhong** [comment]
I'd suggest checking kubelet.log of the e2e runs to see if kubelet is unstable (e.g., grep "cbr0").

e2e has some tolerance to unstable nodes, so it could be deceiving sometimes.

**Comment by jimmidyson** [comment]
@yujuhong Good idea. I'll go through the kubelet logs from each e2e run & double/triple/quadruple check.

Could someone kick the tests off a couple more times please?

**Comment by jimmidyson** [comment]
@vishh Kick please?

**Comment by vishh** [comment]
@k8s-bot: ok to test

**Comment by vishh** [comment]
@k8s-bot retest this please

**Comment by jimmidyson** [comment]
For some reason the build logs haven't been linked & so I can't review them to check for cbr0 problems as @yujuhong suggested.

**Comment by yujuhong** [comment]
> For some reason the build logs haven't been linked & so I can't review them to check for cbr0 problems as @yujuhong suggested.

Ah...I don't think you have access to the logs. I grep'd for cbr0 and the result seemed fine:

```
104.154.51.228:22-kubelet.log:I0904 21:47:54.799146    3604 container_bridge.go:58] Recreated cbr0 and restarted docker
104.154.81.67:22-kubelet.log:I0904 21:47:54.491552    3588 container_bridge.go:58] Recreated cbr0 and restarted docker
104.197.67.112:22-kubelet.log:I0904 21:47:54.500295    3635 container_bridge.go:58] Recreated cbr0 and restarted docker
130.211.116.155:22-kubelet.log:I0904 21:46:32.096456    3371 container_bridge.go:58] Recreated cbr0 and restarted docker
130.211.116.155:22-kubelet.log:I0904 21:46:40.487297    3761 manager.go:158] Machine: {NumCores:2 CpuFrequency:2500000 MemoryCapacity:7863918592 MachineID: SystemUUID:D4AD3C82-62EA-BA08-D8CB-A77C37BC2198 BootID:f1ea95e1-1109-46b0-af9c-127259eb4812 Filesystems:[{Device:/dev/disk/by-uuid/3e07d02c-c373-4daf-ac26-d29550f95545 Capacity:10432602112} {Device:/dev/sdb Capacity:21003628544}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:10737418240 Scheduler:cfq} 8:16:{Name:sdb Major:8 Minor:16 Size:21474836480 Scheduler:cfq}] NetworkDevices:[{Name:cbr0 MacAddress:96:0f:5c:99:fc:8c Speed:0 Mtu:1460} {Name:eth0 MacAddress:42:01:0a:f0:75:e2 Speed:0 Mtu:1460}] Topology:[{Id:0 Memory:7863918592 Cores:[{Id:0 Threads:[0 1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:31457280 Type:Unified Level:3}]}] CloudProvider:GCE InstanceType:n1-standard-2}
130.211.183.239:22-kubelet.log:I0904 21:47:54.158572    3636 container_bridge.go:58] Recreated cbr0 and restarted docker
130.211.190.55:22-kubelet.log:I0904 21:48:00.252138    3569 container_bridge.go:58] Recreated cbr0 and restarted docker
146.148.79.44:22-kubelet.log:I0904 21:47:54.472078    3568 container_bridge.go:58] Recreated cbr0 and restarted docker
```

**Comment by jimmidyson** [comment]
Yeah that LGTM. Thanks @yujuhong!

**Comment by vishh** [comment]
I'd say let's get this merged. Let me know if you want to test a bit more @jimmidyson.

**Comment by caesarxuchao** [comment]
@k8s-bot test this

**Pull request merged**
