### PR TITLE
update azure vmsizeclient log format

### PR DESCRIPTION
**Pull request by lovebaby979**
```docs
update azure vmsizeclient log format
```

### CODE REVIEW

**Comment by feiskyer** [comment]
is this a required change? since we won't add new features in existing cloud providers, we shouldn't make more changes in cloud providers if it's not required (e.g. bugs or CVEs).

**Comment by yangjunmyfm192085** [comment]
@feiskyer I am not sure if the following requirements is working for cloud providers part. if we wrong, you can close this.
https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md

**Comment by feiskyer** [comment]
let's keep the log format as-is (only bug fixes would be added for in-tree cloud providers).

/close

**Pull request closed without merging**
