### PR TITLE
LimitRanger and PodSecurityPolicy need to check more on init containers

### PR DESCRIPTION
**Pull request by smarterclayton**
Container limits not applied to init containers. HostPorts not checked on podsecuritypolicy

@pweil- @derekwaynecarr

### CODE REVIEW

**Comment by smarterclayton** [comment]
@kubernetes/autoscaling for someone to review initial resources changes

**Comment by piosz** [comment]
LGTM for IR part

**Comment by pweil-** [comment]
`hostPorts` LGTM.  I'll take a TODO on this to look closer at these calls and refactor them.  It looks like old cruft from when PSC was introduced, they should really just be passing in the container that was given to the method call and it wouldn't have missed `initContainers` in that case.  As-is it looks like you can receive duplicate errors which is annoying.

**Comment by smarterclayton** [comment]
@derekwaynecarr just needs review from you then

**Comment by derekwaynecarr** [comment]
LGTM

**Comment by smarterclayton** [comment]
@k8s-bot test this issue #IGNORE

**Pull request merged**
