### PR TITLE
feat: initialize node status plugin

### PR DESCRIPTION
**Pull request by draveness**
**What type of PR is this?**

/kind feature
/sig node
/priority important-longterm

**What this PR does / why we need it**:

Create a node status plugin interface and convert the existing node address to plugin.

Some components of the kubelet depend on the `GetNode` function of kubelet, and `GetNode` function has a complicated process which finally depends on the components of kubelet and causes circular dependency.

With the node status plugin and registry, we could create the node status registry before the creation of the kubelet and register plugins after the initialization.

After we create the node status registry and convert all the node status functions to plugins, we could make a new struct to provide the `GetNode` function and start to break the dependency here

https://github.com/kubernetes/kubernetes/blob/ee81b306815268cfbc01501f9dae12ce38974405/pkg/kubelet/kubelet.go#L559-L562

The process of migration wouldn't break the code or any unit tests and could be done by trunks.

**Which issue(s) this PR fixes**:

Part of https://github.com/kubernetes/kubernetes/issues/85672

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by tallclair** [comment]
I'm actually not sure that lazy initialization is the best way to break the circular dependency in this case.

I'd rather look over all the `defaultNodeStatusFuncs`, and see what data they require.

- A lot of it is static configuration or info that is scraped from the host at startup, e.g. nodeIP, hostname, cadvisor.VersionInfo, etc.
- Some of it is coming from standalone modules, e.g. `cloud`, `containerManager` and `cadvisor`.
- Some of the dependencies are on Kubelet functions, like `kl.GetCachedMachineInfo`, `kl.recordEvent`

It's this last category that really creates the circular dependency problems. To fix these, I think it's better to pull that functionality out into separate modules that both the Kubelet and the status functions can depend on, e.g. `MachineInfoProvider` and `NodeRefProvider`*

Once we do the work to break those circular dependencies, we may still find that factoring out node status plugins is useful for the dependency injection approach, but I'd prefer to start with breaking the circular dependencies. Does this make sense?

* `NodeRefProvider` is actually what is needed for the `recordEvent` function, since that's the piece provided by the Kubelet beyond the event recorder. I actually started on this refactor, ran into this circular dependency, and abandoned it (feel free to take over this change if it's useful: https://github.com/kubernetes/kubernetes/compare/master...tallclair:nodeinfo-refactor)

**Comment by draveness** [comment]
> I'm actually not sure that lazy initialization is the best way to break the circular dependency in this case.
> 
> I'd rather look over all the `defaultNodeStatusFuncs`, and see what data they require.
> 
> * A lot of it is static configuration or info that is scraped from the host at startup, e.g. nodeIP, hostname, cadvisor.VersionInfo, etc.
> * Some of it is coming from standalone modules, e.g. `cloud`, `containerManager` and `cadvisor`.
> * Some of the dependencies are on Kubelet functions, like `kl.GetCachedMachineInfo`, `kl.recordEvent`
> 
> It's this last category that really creates the circular dependency problems. To fix these, I think it's better to pull that functionality out into separate modules that both the Kubelet and the status functions can depend on, e.g. `MachineInfoProvider` and `NodeRefProvider`*
> 
> Once we do the work to break those circular dependencies, we may still find that factoring out node status plugins is useful for the dependency injection approach, but I'd prefer to start with breaking the circular dependencies. Does this make sense?
> 
> * `NodeRefProvider` is actually what is needed for the `recordEvent` function, since that's the piece provided by the Kubelet beyond the event recorder. I actually started on this refactor, ran into this circular dependency, and abandoned it (feel free to take over this change if it's useful: [master...tallclair:nodeinfo-refactor](https://github.com/kubernetes/kubernetes/compare/master...tallclair:nodeinfo-refactor))

Thanks for the review, the reason for lazy initialization is many components still depends on the kubelet, e.g. containerRuntime. I have tried the approach to extract `defaultNodeStatusFuncs` as a whole and ended up with circular dependency...

https://github.com/kubernetes/kubernetes/blob/0d58709016f3358f34a52c12087d707a64cc6cb0/pkg/kubelet/kubelet.go#L673-L699

Since the `defaultNodeStatusFuncs` depends on the containerRuntime, and containerRuntime depends on the kubelet, we didn't break the circular dependency. 

```
defaultNodeStatusFuncs -> containerRuntime -> kubelet
```


With lazy initialization, we could

1. Create a plugin registry before the initialization of kubelet.
2. Initialize a module which provides `GetNode` method
3. Register some node status plugin which doesn't have a circular dependency
4. Initialize kubelet
5. Register some node status plugin which depends on the kubelet.

**Comment by tallclair** [comment]
That's a good example, but I think we should be focusing on breaking the circular dependency by extracting the pieces of the Kubelet that the ContanierRuntime depends on.

I think one way we could frame this is, "nothing should depend on the Kubelet". If something depends on the Kubelet itself, then that functionality it's depending on should probably be extracted into a separate component. The `NewKubeGenericRuntimeManager` function actually illustrates this well - it doesn't take the Kubelet as an argument, rather it takes a few interfaces that the Kubelet implements, e.g. `podStateProvider` and `kubecontainer.RuntimeHelper`. Therefore, we should work on extracting those pieces into a separate sub-component.

WDYT?

**Comment by draveness** [comment]
> That's a good example, but I think we should be focusing on breaking the circular dependency by extracting the pieces of the Kubelet that the ContanierRuntime depends on.
> 
> I think one way we could frame this is, "nothing should depend on the Kubelet". If something depends on the Kubelet itself, then that functionality it's depending on should probably be extracted into a separate component. The `NewKubeGenericRuntimeManager` function actually illustrates this well - it doesn't take the Kubelet as an argument, rather it takes a few interfaces that the Kubelet implements, e.g. `podStateProvider` and `kubecontainer.RuntimeHelper`. Therefore, we should work on extracting those pieces into a separate sub-component.
> 
> WDYT?

I agree, but this PR's purpose is to extract `GetNode` from kubelet and break the circular dependency between `configMapManager`, `secretManager`, and kubelet.

```go
	var secretManager secret.Manager
	var configMapManager configmap.Manager
	switch kubeCfg.ConfigMapAndSecretChangeDetectionStrategy {
	case kubeletconfiginternal.WatchChangeDetectionStrategy:
		secretManager = secret.NewWatchingSecretManager(kubeDeps.KubeClient)
		configMapManager = configmap.NewWatchingConfigMapManager(kubeDeps.KubeClient)
	case kubeletconfiginternal.TTLCacheChangeDetectionStrategy:
		secretManager = secret.NewCachingSecretManager(
			kubeDeps.KubeClient, manager.GetObjectTTLFromNodeFunc(klet.GetNode))
		configMapManager = configmap.NewCachingConfigMapManager(
			kubeDeps.KubeClient, manager.GetObjectTTLFromNodeFunc(klet.GetNode))
	case kubeletconfiginternal.GetChangeDetectionStrategy:
		secretManager = secret.NewSimpleSecretManager(kubeDeps.KubeClient)
		configMapManager = configmap.NewSimpleConfigMapManager(kubeDeps.KubeClient)
	default:
		return nil, fmt.Errorf("unknown configmap and secret manager mode: %v", kubeCfg.ConfigMapAndSecretChangeDetectionStrategy)
	}
```

`GetNode` depends on `initialNode`, and `initialNode` depends on `setNodeStatusFuncs`, with a node status plugin registry we could break the dependency.

**Comment by mattjmcnaughton** [comment]
Thanks for your thoughts on this difficult project!

Out of curiosity, is there a KEP for either this specific proposal or the overall goal of breaking the circular dependencies in the Kubelet? Given that, I presume, this project will be fairly long running and require non-trivial refactors, I think a KEP could be a really good idea.

**Review by mattjmcnaughton — COMMENTED** [review]
Thanks for your thoughts on this difficult project!

Out of curiosity, is there a KEP for either this specific proposal or the overall goal of breaking the circular dependencies in the Kubelet? Given that, I presume, this project will be fairly long running and require non-trivial refactors, I think a KEP could be a really good idea.

**Comment by draveness** [comment]
> Thanks for your thoughts on this difficult project!
> 
> Out of curiosity, is there a KEP for either this specific proposal or the overall goal of breaking the circular dependencies in the Kubelet? Given that, I presume, this project will be fairly long running and require non-trivial refactors, I think a KEP could be a really good idea.

Yes, the refactor could take quite a long time. I don't think we could be very precise on every step of the refactoring process,  but I'll try my best to give a preliminary document that explains what we need to get it done.

**Comment by mattjmcnaughton** [comment]
On Fri, Dec 27, 2019 at 01:49:37AM -0800, Draven wrote:
> > Thanks for your thoughts on this difficult project!
> > 
> > Out of curiosity, is there a KEP for either this specific proposal or the overall goal of breaking the circular dependencies in the Kubelet? Given that, I presume, this project will be fairly long running and require non-trivial refactors, I think a KEP could be a really good idea.
> 
> Yes, the refactor could take quite a long time. I don't think we could be very precise on every step of the refactoring process,  but I'll try my best to give a preliminary document that explains what we need to get it done.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/85665#issuecomment-569234708

Thanks! I think having that preliminary document will be helpful both in
allowing us to avoid potentially unfruitful paths and in ensuring everyone is on
the same page re the steps we will take for this refactor.

**Pull request closed without merging**
