### PR TITLE
Bump GCI to gci-stable-56-9000-84-2

### PR DESCRIPTION
**Pull request by dchen1107**
Changelogs since gci-beta-56-9000-80-0:

- Fixed google-accounts-daemon breaks on GCI when network is unavailable.
- Fixed iptables-restore performance regression.

cc/ @adityakali @Random-Liu @fabioy

### CODE REVIEW

**Comment by adityakali** [comment]
/lgtm

Thanks Dawn!

**Comment by dchen1107** [comment]
cc/ @saad-ali for 1.5 release; and @jessfraz for 1.4 release. 

@freehan who is upgrade both 1.4 and 1.5 to the latest GCI / COS release for network related fix. @kubernetes/sig-network-misc

**Comment by dchen1107** [comment]
https://github.com/kubernetes/kubernetes/issues/41829 causes above failures which should be addressed now.

@k8s-bot cvm gce e2e test this
@k8s-bot gci gce e2e test this

**Comment by Random-Liu** [comment]
LGTM

**Comment by freehan** [comment]
@k8s-bot verify test this

**Comment by freehan** [comment]
Verification is failing:

```
 FAILED   hack/make-rules/../../hack/verify-staging-godeps.sh	220s
```

**Comment by eparis** [comment]
fixed about 5 minutes ago
@k8s-bot verify test this

**Comment by eparis** [comment]
@k8s-bot verify test this

**Pull request merged**
