### PR TITLE
Restore honoring --version build ID overrides

### LINKED ISSUE #126663: kube-apiserver and other components no longer honor --version build ID overrides
### What happened?

Starting in 1.31, --version no longer works to modify the build ID of the running components.

/kind regression
/priority important-soon

### What did you expect to happen?

Running kube-apiserver v1.31.0 with `--version=v1.31.0-example.123` ignores the modified build ID and reports `v1.31.0`

In 1.28, 1.29, and 1.30 (since https://github.com/kubernetes/kubernetes/pull/117688), this allowed modifying the build ID of the running server.

/sig api-machinery
/assign @jpbetz @siyuanfoundation

### How can we reproduce it (as minimally and precisely as possible)?

Run `kube-apiserver` v1.31.0 with `--version=v1.31.0-example.123`

### Anything else we need to know?

_No response_

### Kubernetes version

1.31.0

### Cloud provider

n/a

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

Minimal fix to restore honoring `--version` build ID overrides for 1.31

Added a simple test around the behavior at the start of test-cmd, where we're starting a real built API server

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/126663

#### Does this PR introduce a user-facing change?
```release-note
kube-apiserver: Fixes a 1.31 regression that stopped honoring build ID overrides with the --version flag
```

/sig api-machinery
/assign @jpbetz 
/hold for tests

### CODE REVIEW

**Comment by liggitt** [comment]
```
+++ [0814 00:59:07] On try 4, apiserver: ok
Successful
(Bmessage:{
  "major": "1",
  "minor": "32",
  "gitVersion": "v1.32.0-alpha.0.34+67202bdb1d4932-custom",
  "gitCommit": "67202bdb1d49321b05481461725b326a072960b8",
  "gitTreeState": "clean",
  "buildDate": "2024-08-13T21:44:43Z",
  "goVersion": "go1.22.5",
  "compiler": "gc",
  "platform": "linux/amd64"
}
has:gitVersion.*-custom
```

test passed

**Comment by liggitt** [comment]
/hold cancel

This will need revisiting if we actually start letting people override the binary version (I'm not sure if that's planned or not), but this is a minimal version to resolve the regression for 1.30 / 1.31

**Review by BenTheElder — COMMENTED** [review]
/lgtm

**Review by BenTheElder — COMMENTED** [review]
/lgtm
[discussed shellcheck fix, see diff link above in "compare" button]

**Pull request merged**
