### PR TITLE
Fixed typo - cluser -> cluster, and replicasets -> ReplicaSet for consistency

### PR DESCRIPTION
**Pull request by saturnism**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36719)

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by madhusudancs** [comment]
@saturnism thanks! LGTM! You will have to sign the linux foundation CLA for us to accept this PR.

**Comment by dims** [comment]
@madhusudancs : got word that just google cla is enough right now.

**Comment by madhusudancs** [comment]
@dims alright, noted.

**Pull request merged**
