### PR TITLE
Register api.DeleteOptions for internal batch group

### LINKED ISSUE #36806: Unable to delete Job using batch client
**Kubernetes version**: HEAD

**What happened**: Using `RESTClient` interface to delete Job throws an error `api.DeleteOptions is not suitable for converting to "batch/v1"`.

**What you expected to happen**: Job should be deleted.

We've found that issue after dependency update on dashboard: https://github.com/kubernetes/dashboard/pull/1408. We are using [RESTClient](https://github.com/kubernetes/dashboard/blob/master/src/app/backend/resource/common/verber.go#L76) to delete resources. It works fine for all other resources. I've investigated that and it appears to be the core issue.

Other `pkg/apis` groups have `api.DeleteOptions` registered as a known type.
[apps](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/register.go#L53)
[extensions](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/register.go#L71)
[authentication](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/authentication/register.go#L49)

however batch is missing it
[batch](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/batch/register.go#L48)

After adding `api.DeleteOptions` I was able to successfully delete Job using our code.

I can quickly create PR for that. Just need a confirmation that this is indeed a bug.

cc @caesarxuchao @rf232

### PR DESCRIPTION
**Pull request by floreks**
**What this PR does / why we need it**: Registers api.DeleteOptions for internal batch group

**Which issue this PR fixes**: fixes #36806

**Release note**:

```release-note
Register api.DeleteOptions for internal batch group
Register api.DeleteOptions for internal autoscaling group
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36879)

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Could you also register it in the autoscaling group?

**Comment by caesarxuchao** [comment]
@saad-ali this is a bug fix, so I added 1.5 milestone.

**Comment by floreks** [comment]
> Could you also register it in the autoscaling group?

Sure, adding this now.

**Comment by floreks** [comment]
@caesarxuchao Done. PTAL

**Comment by floreks** [comment]
Any update here?

**Comment by caesarxuchao** [comment]
LGTM. Thanks!

**Comment by caesarxuchao** [comment]
@saad-ali this is a bug fix.

**Comment by saad-ali** [comment]
> @saad-ali this is a bug fix.


Ack. Thanks @caesarxuchao

**Pull request merged**
