### PR TITLE
avoid newline "\n" in the error to break log msg to 2 lines

### LINKED ISSUE #49813: AWS error messages printed on 2 lines
/kind bug

**What happened**:
#47789 didn't completely solve the problem.  AWS error messages are formed with a \n in them, but are still printed with %v so they are interpreted.  The result is:

E0705 01:58:36.269603   16962 nestedpendingoperations.go:262] Operation for <vol> failed. No retries permitted until 2017-07-05 01:58:36.769575117 -0400 EDT (durationBeforeRetry 500ms). Error: Failed to attach volume <vol> on node <node> with: Error attaching EBS volume <vol> to instance <instance>: IncorrectState: <vol> is not 'available'.

status code: 400, request id: <request-id>

**What you expected to happen**:
E0705 01:58:36.269603   16962 nestedpendingoperations.go:262] Operation for <vol> failed. No retries permitted until 2017-07-05 01:58:36.769575117 -0400 EDT (durationBeforeRetry 500ms). Error: Failed to attach volume <vol> on node <node> with: Error attaching EBS volume <vol> to instance <instance>: IncorrectState: <vol> is not 'available'. status code: 400, request id: <request-id>

**Anything else we need to know?**:
Problem is that in 
pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go

The errors are still printed with %v instead of %q, so the \n in the log messages is being interpreted.

There may be other places where this would come to light.

@kubernetes/sig-aws-misc @justinsb

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #49813

**Special notes for your reviewer**:
/cc @justinsb @rrati 

**Release note**:

```release-note
avoid newline "\n" in the error to break log msg to 2 lines
```

### CODE REVIEW

**Comment by justinsb** [comment]
Although for #49813 I wonder if we should wrap the AWS error - i.e. we should never return a bare AWS error (they tend to not print well), and then we should use %q to avoid newlines there (we could also have our own AWS-error-sanitizer function)

**Comment by lpabon** [comment]
@justinsb @dixudx Doesn't this just print out the `\n` character also? It is not interpreted, but it is also printed out. Wouldn't it look like this: `IncorrectState: is not 'available'.\nstatus code: 400, request id:` (using the example from the issue)

**Comment by dixudx** [comment]
@lpabon `%q` will treat `\n` as string. Will not print newline.

Please take a look of [my example](https://play.golang.org/p/qyKzmMRd8S).

**Comment by dixudx** [comment]
ping @saad-ali PTAL. Needs your `approval`. Thanks.

**Comment by rrati** [comment]
lgtm

**Comment by dixudx** [comment]
ping @saad-ali PTAL. Needs your approval. Thanks.

**Comment by dixudx** [comment]
ping @saad-ali PTAL. Needs your approval. Thanks.

**Pull request merged**
