### PR TITLE
cleanup: fix the format of kubectl proxy examples

### PR DESCRIPTION
**Pull request by pandaamanda**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
/ok-to-test

**Review by zhouya0 — COMMENTED** [review]
/lgtm

**Review by soltysh — APPROVED** [review]
/triage accepted
/approve

**Pull request merged**
