### PR TITLE
Allow settings --service-node-port-range option using a config variable

### PR DESCRIPTION
**Pull request by mamikonyana**
Introduce `SERVICE_NODE_PORT_RANGE` variable which gets passed to `kube-apiserver` as a `--service-node-port-range` argument.

### CODE REVIEW

**Comment by mamikonyana** [comment]
fixes #11945

**Comment by thockin** [comment]
I'm surprised anyone really cares about setting this - is there a use case for it?  It's not an unreasonable PR, just seems not very useful

**Comment by thockin** [comment]
LGTM

**Comment by mamikonyana** [comment]
Yes it's a use case for us. I'm setting up a cluster using ubuntu VMs, and I want to expose a service at port 80. And since I can't use `type: LoadBalancer` since it's not supported out of the box, I have to do `type: NodePort` and set nodePort to 80.

**Comment by thockin** [comment]
I figured that would be what you were up to.  Note that this is an exposure
that is very hard to debug.

If you set the node port range down to 80, that means ANY service might get
randomly allocated port 80.  It also means that any Pod that asks for a
HostPort migh conflict with NodePorts and we don't really have a good way
to detect report that.

You might be happier with
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/contrib/for-demos/proxy-to-service

**Comment by mikedanese** [comment]
Needs rebase

**Comment by mamikonyana** [comment]
rebased

**Comment by bmeck** [comment]
Does this not work with the vagrant provider?

**Comment by mikedanese** [comment]
This is specific to the ubuntu provider.

**Pull request merged**
