### PR TITLE
Move e2e fromManifest funcs to manifest package

### LINKED ISSUE #37007: test/e2e/framework cannot be imported into external projects
**Problem**
If you try to compile a project that has a test/e2e/framework as a dependency, we see the following error:
```
# github.com/sjug/project/vendor/k8s.io/kubernetes/test/e2e/framework
vendor/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go:30: undefined: generated.Asset
vendor/k8s.io/kubernetes/test/e2e/framework/gobindata_util.go:33: undefined: generated.AssetNames
```
When we import test/e2e/framework as a dependency the `ReadOrDie(filepath string) []byte` depends on two assets that are generated by gobindata.

**Solution**
Modify test/e2e/framework to not depend on bindata.

### PR DESCRIPTION
**Pull request by wongma7**
fixes https://github.com/kubernetes/kubernetes/issues/37007 again

The goal here is to remove e2e/framework's dependence on e2e/generated so that external projects can import e2e/framework without issue. I reorganize & try to make all the 'fromManifest' funcs consistent (to all use generated, return err) to prevent any reintroduction of generated into framework

```release-note
NONE
```

### CODE REVIEW

**Comment by wongma7** [comment]
Darn, https://github.com/kubernetes/kubernetes/pull/43066 throws a wrench into this :) the non-statefulset parts & general idea of this PR can still be reviewed though...

**Comment by wongma7** [comment]
@foxish, here https://github.com/kubernetes/kubernetes/pull/43637/files#diff-20a9335743239e362032f5839bb81f98L106 why do we use `RunKubectlOrDieInput`? Wouldn't it be better to use the client and create the objects directly? To isolate the tests from kubectl

**Comment by foxish** [comment]
@wongma7 The change in that PR from fix from `RunKubectlOrDie` to `RunKubectlOrDieInput` were because the `RunKubectlOrDie` method was changing the cwd causing the manifests to not be found at all. It would be good to remove the dependency on kubectl entirely like you've done. I think it should still be possible, because all that #43066 changed is to read the YAML file and supply it to kubectl in stdin, rather than supplying the  YAML file path to it.

**Comment by wongma7** [comment]
@erictune can you review or assign another reviewer, thanks! this is purely a mechanical & refactoring PR, no major additions.

**Comment by wongma7** [comment]
@erictune ping please reassign

**Comment by spiffxp** [comment]
@k8s-bot ok to test

**Comment by wongma7** [comment]
Just added package to "hack/.linted_packages" to fix jenkins verification

**Comment by wongma7** [comment]
@k8s-bot gce etcd3 e2e test this

"Ginkgo timed out waiting for all parallel nodes to report back!"

**Comment by wongma7** [comment]
@kubernetes/sig-testing-pr-reviews  @kubernetes/sig-testing-misc this PR is consistently failing at Jenkins GCE etcd3 e2e with e.g.

`I0508 14:23:33.184] 	|  Ginkgo timed out waiting for all parallel nodes to report back!  |`

It happens shortly after all tests appear to pass.

Any ideas what is happening? Do I have to do something special because I'm changing the e2e test stuff itself? thanks...

**Comment by wongma7** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by wongma7** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by wongma7** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Comment by wongma7** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
