### PR TITLE
Bumped Heapster version to 1.4.3

### PR DESCRIPTION
**Pull request by loburm**
```release-note
Bumped Heapster version to 1.4.3 - more details https://github.com/kubernetes/heapster/releases/tag/v1.4.3
```

### CODE REVIEW

**Comment by loburm** [comment]
cc @wojtek-t @piosz

**Comment by piosz** [comment]
/lgtm
/approve no-issue

Please add release notes

**Comment by wojtek-t** [comment]
@loburm @piosz - don't we want this in 1.8 and master too?

**Comment by loburm** [comment]
I'm working on PR for 1.8

**Comment by piosz** [comment]
@wojtek-t in master we use 1.5-beta.0 and we need to reach stable 1.5 at some point

**Comment by loburm** [comment]
Done for 1.8: https://github.com/kubernetes/kubernetes/pull/53377

**Pull request merged**
