### PR TITLE
Update storageclass version to v1 in examples

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/cc @jsafrane 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
Also /cc @wongma7 @msau42

**Comment by zhangxiaoyu-zidif** [comment]
LGTM

**Comment by xiangpengzhao** [comment]
/assign @brendandburns
for approval, thanks!

**Pull request merged**
