### PR TITLE
add scale endpoint for statefulsets

### LINKED ISSUE #46005: No scale subresource for StatefulSets
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.): no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):
update using patch
scaleSimple

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Kubernetes version** (use `kubectl version`): v1.6.3 for both client and server

**Environment**:
- **Cloud provider or hardware configuration**: GKE
- **OS** (e.g. from /etc/os-release): 
```
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
VERSION_ID="14.04"
```
- **Kernel** (e.g. `uname -a`): ```Linux 4.4.0-75-generic #96~14.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux```
- **Install tools**: N/A
- **Others**: N/A

**What happened**:
Current implementation uses Put instead of Patch when running `kubectl scale`, which may result in validation errors when running client and server of **different** versions. We currently round-trip the entire spec from the YAML file to change number of replicas. Instead, we can use Patch and change only the `replicas` field.

**What you expected to happen**:
Use Patch when scaling replicas.

**How to reproduce it** (as minimally and precisely as possible):
N/A

**Anything else we need to know**:
I will work on this. :)

### PR DESCRIPTION
**Pull request by crimsonfaith91**
**What this PR does / why we need it**:
Add a scale endpoint for statefulsets.
 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #46005

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by kargakis** [comment]
@kubernetes/sig-apps-pr-reviews

**Comment by deads2k** [comment]
The title doesn't seem to match the code.

**Comment by foxish** [comment]
@k8s-bot ok to test

**Comment by crimsonfaith91** [comment]
Sorry for the title mismatch. I will close this PR now. Thanks!

**Pull request closed without merging**
