### PR TITLE
expose: Create objects in a generic way

### PR DESCRIPTION
**Pull request by 0xmichalis**
cc: @smarterclayton

### CODE REVIEW

**Comment by brendandburns** [comment]
LGTM.

**Comment by smarterclayton** [comment]
Michail can you explain why you need this (so the change is documented here)?

**Comment by kargakis** [comment]
Well, since the ability to expose more kinds of resources than just services is already in place (`--generator` flag) it's only natural for this change to happen. With this merged, it'll be easy for someone to register a new resource generator and use expose to generate such resources eg. we want to generate routes from services: https://github.com/openshift/origin/pull/2045

**Comment by smarterclayton** [comment]
Merging

**Pull request merged**
