### PR TITLE
Add dgrisonnet as sig-instrumentation reviewer

### PR DESCRIPTION
**Pull request by dgrisonnet**
List of sig-instrumentation PRs that I reviewed: https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+commenter%3Adgrisonnet+-author%3Adgrisonnet+label%3Asig%2Finstrumentation+

/sig instrumentation

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

/cc @ehashman 
/hold
(let's wait for @ehashman's signoff)

**Review by ehashman — COMMENTED** [review]
/lgtm
/approve

Your reviews have been in depth and high quality, thank you!

/hold cancel
/kind cleanup
/priority backlog
/triage accepted

**Comment by ehashman** [comment]
/assign @liggitt 
for top-level approve

**Comment by aojea** [comment]
+1

**Pull request merged**
