### PR TITLE
[DO NOT MERGE]Service ports issue 101393

### LINKED ISSUE #101393: Consider changing service.spec.Ports to "atomic"
The strategic merge patch support for service ports is broken (insufficiently unique key) and has been a problem for a long time.  In #101029 we discussed a little whether we could just change it to "atomic".  

It might be simple, but strategic merge patch is too poorly documented to know for sure.  E.g. a quick test:

Given this initial Service:
```
apiVersion: v1
kind: Service
metadata:
  name: ports
spec:
  type: ClusterIP
  selector:
    app: hostnames
  ports:
  - port: 80
    protocol: TCP
    name: tcp
```

...use `kubectl apply` on this:
```
apiVersion: v1
kind: Service
metadata:
  name: ports
spec:
  type: ClusterIP
  selector:
    app: hostnames
  ports:
  - port: 80
    protocol: TCP
    name: tcp
  - port: 80
    protocol: UDP
    name: udp
```

...and see that it doesn't "stick" (because it de-dups on port number alone):
```
$ k get svc ports -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"ports","namespace":"default"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":9376},{"port":80,"protocol":"UDP","targetPort":9376}],"selector":{"app":"hostnames"},"type":"ClusterIP"}}
  creationTimestamp: "2021-04-23T00:04:15Z"
  name: ports
  namespace: default
  resourceVersion: "5097270"
  uid: 5eb1358f-64d8-4dab-a4c2-cc271846f3c9
spec:
  clusterIP: 10.0.27.156
  clusterIPs:
  - 10.0.27.156
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp
    port: 80
    protocol: TCP
    targetPort: 9376
  selector:
    app: hostnames
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

apply this patch:
```
diff --git a/staging/src/k8s.io/api/core/v1/types.go b/staging/src/k8s.io/api/core/v1/types.go
index 3eadb45674c9..98de8e63057b 100644
--- a/staging/src/k8s.io/api/core/v1/types.go
+++ b/staging/src/k8s.io/api/core/v1/types.go
@@ -4069,12 +4069,9 @@ const (
 type ServiceSpec struct {
        // The list of ports that are exposed by this service.
        // More info: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
-       // +patchMergeKey=port
-       // +patchStrategy=merge
-       // +listType=map
-       // +listMapKey=port
-       // +listMapKey=protocol
-       Ports []ServicePort `json:"ports,omitempty" patchStrategy:"merge" patchMergeKey:"port" protobuf:"bytes,1,rep,name=ports"`
+       // +patchStrategy=replace
+       // +listType=atomic
+       Ports []ServicePort `json:"ports,omitempty" patchStrategy:"replace" protobuf:"bytes,1,rep,name=ports"`
```

...rebuild apiserver and run it.  Retry the patch anfd get the object:
```
$ k get svc ports -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"ports","namespace":"default"},"spec":{"ports":[{"name":"tcp","port":80,"protocol":"TCP","targetPort":9376},{"name":"udp","port":80,"protocol":"UDP","targetPort":9376}],"selector":{"app":"hostnames"},"type":"ClusterIP"}}
  creationTimestamp: "2021-04-23T00:04:15Z"
  name: ports
  namespace: default
  resourceVersion: "5098422"
  uid: 5eb1358f-64d8-4dab-a4c2-cc271846f3c9
spec:
  clusterIP: 10.0.27.156
  clusterIPs:
  - 10.0.27.156
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp
    port: 80
    protocol: TCP
    targetPort: 9376
  - name: udp
    port: 80
    protocol: UDP
    targetPort: 9376
  selector:
    app: hostnames
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

It seems to work.  I am surprised I didn't have to recompile the client.  Even if a client had this baked in, it wouldn't actuaally be worse than today, right?

Is this "safe"?  What trap am I missing?

### PR DESCRIPTION
**Pull request by khenidak**
a functional PR implementing the proposal here: https://github.com/kubernetes/kubernetes/issues/101393

/sig network
/assign @thockin 

fixes #101393

### CODE REVIEW

**Comment by thockin** [comment]
This looks OK to me, but I don't know those tests or even how to read the output, frankly.

**Comment by aojea** [comment]
what is the current kubectl skew policy?
I think we don't have tests about skewed kubectl, do you know @liggitt ?

**Comment by liggitt** [comment]
there are tests that use skewed kubectl, though I don't know their status, or whether they cover this scenario... cc @eddiezane / @seans3 / @soltysh for pointers to those

at first glance, a couple of the test failures _seem_ to indicate this is not a compatible change:

integration test:

>     apply_test.go:148: Failed to re-apply object using Apply patch: Apply failed with 1 conflict: conflict with "apply_test": .spec.ports

unit test:

```
    edit_test.go:150: edit-error-reedit, step 4: diff in edit content:
        {
        	"spec": {
        		"
        
        A: ports": [
        			{
        				"name": "80",
        				"port": 82,
        				"protocol": "TCP",
        				"targetPort": 80
        			}
        		]
        	}
        }
        
        B: $setElementOrder/ports": [
        			{
        				"port": 82
        			}
        		],
        		"ports": [
        			{
        				"name": "80",
        				"port": 82,
        				"protocol": "TCP",
        				"targetPort": 80
        			},
        			{
        				"$patch": "delete",
        				"port": 81
        			}
        		]
        	}
        }
        
    edit_test.go:151: If the change in input is expected, rerun tests with UPDATE_EDIT_FIXTURE_DATA=true to update input fixtures
```

Is it safe for a client built against an older version of k8s.io/api (or a client sending a manually-built strategic merge patch that includes the ports var) to speak to a server with this change (or vice-versa)?

At first glance, it seems like this is what would happen:
* a new client treats ports as atomic, and generates/sends a strategic merge patch that an old server will merge leaving old ports in the port list
* an old client will treat ports as mergeable, and generates/sends a strategic merge patch that a new server will merge dropping ports the client intended to leave unchanged

**Comment by khenidak** [comment]
Am i understanding this correctly: This means there is no way to change current behavior. Is there is another way?

> there are tests that use skewed kubectl, though I don't know their status, or whether they cover this scenario... cc @eddiezane / @seans3 / @soltysh for pointers to those
> ...

**Comment by liggitt** [comment]
> Am i understanding this correctly: This means there is no way to change current behavior.

for server-side apply (the `patchStrategy` and `patchMergeKey` directives), that's where we ended up previously (https://github.com/kubernetes/kubernetes/issues/44111#issuecomment-292004913, https://github.com/kubernetes/kubernetes/pull/97906#issuecomment-757945545)

**Comment by khenidak** [comment]
closing in favor of https://github.com/kubernetes/kubernetes/issues/105610

**Pull request closed without merging**
