### PR TITLE
Update JWT check to check secretName and not namespace again.

### PR DESCRIPTION
**Pull request by bweston92**
**What this PR does / why we need it**:

To check the correct claim.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by bweston92** [comment]
@liggitt @mikedanese would you want test cases?

**Comment by dims** [comment]
/ok-to-test

the code is clearly wrong :)

**Comment by mikedanese** [comment]
@bweston92 test cases are always appreciated.

**Pull request merged**
