### PR TITLE
Fix godep race in local builds

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
This fixes a small race condition when building a godep version other than the latest. As you're building godep once, and then building it again after checkout, this can cause inconsistency in the version selected for use. This fix tells the first `go get` to only download and not build. Then we build manually after checking out the target version.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ixdy** [comment]
@k8s-bot ok to test
/lgtm

**Comment by cblecker** [comment]
@ixdy As this is a bug fix, would it qualify for the 1.6 milestone so it can be merged to master?

**Comment by ixdy** [comment]
seems fine. it's also a fairly harmless fix to a utility script. @ethernetdan

**Comment by ethernetdan** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by cblecker** [comment]
@ethernetdan All tests passing 🎉

**Comment by cblecker** [comment]
Of note: I found the race condition was introduced in #41987 (3 days ago).

**Pull request merged**
