### PR TITLE
[FG:InPlacePodVerticalScaling] Equate CPU limits below the minimum effective limit (10m)

### LINKED ISSUE #128769: [FG:InPlacePodVerticalScaling] containers with a CPU limit below 10m have a resize status of InProgress indefinetly
There is an implicit minimum of `10m` for CPU limits, so the actual resource limit is always clamped at a minimum of 10m. If the desired CPU limit is below 10m, the comparison of desired == actual fails, and the resize status is set to in-progress.

This is very similar to the case of minimum shares addressed in https://github.com/kubernetes/kubernetes/pull/128680

/kind bug
/sig node
/priority important-soon
/milestone v1.32

### PR DESCRIPTION
**Pull request by tallclair**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

We clamp the minimum CPU quota, which translates to an effective minimum CPU limit of `10m`. When we compare actual vs desired resources, we need to account for this clamping.

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/128769

#### Special notes for your reviewer:

Extension request: https://groups.google.com/g/kubernetes-sig-release/c/DvRlV9mBZ-Q/m/AGmOk6avBwAJ

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/sig node
/priority important-soon
/milestone v1.32

### CODE REVIEW

**Comment by tallclair** [comment]
tests coming soon...

**Review by yujuhong — COMMENTED** [review]
Change itself looks okay. 

I think we are on the verge of factoring out the code for reusability. Something for the future changes..

**Comment by tallclair** [comment]
Added unit tests, caught a bug in `convertToAPIContainerStatuses` (forgot to remove the unconditional copy when adding the condition for using the actual resources)

**Comment by yujuhong** [comment]
/lgtm

It'd be good to add a test case in the e2e tests to ensure the issue is fixed.

**Comment by tallclair** [comment]
Added e2e tests, and fixed the cross platform builds

**Pull request merged**
