### PR TITLE
Revert "Make kubelet touch iptables lock file during initialization"

### PR DESCRIPTION
**Pull request by MrHohn**
**What this PR does / why we need it**: Revert #47212. #36485 is fixed so this is no longer needed.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #NONE

**Special notes for your reviewer**:
/assign @yujuhong @dchen1107 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by bboreham** [comment]
I would like to note that I think #46597 is what allows this to be reverted; the init-container thing was only used as a workaround, as mentioned at https://github.com/kubernetes/kubernetes/issues/47186#issuecomment-307229471

**Comment by MrHohn** [comment]
> I would like to note that I think #46597 is what allows this to be reverted; the init-container thing was only used as a workaround, as mentioned at #47186 (comment)

Yeah the init-container thing was a just workaround, it was removed by https://github.com/kubernetes/kubernetes/pull/53093.

**Pull request merged**
