### PR TITLE
support record for kubectl set env

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zjj2wry** [comment]
cc @kubernetes/sig-cli-pr-reviews

**Comment by liggitt** [comment]
I’d actually like to see the record feature removed, not propagated. See https://github.com/kubernetes/kubernetes/issues/40422

**Comment by zjj2wry** [comment]
@liggitt thanks~

**Pull request closed without merging**
