### PR TITLE
Update Azure Go SDK to v19.0.0 and get availability zone for VirtualMachineScaleSetVM

### PR DESCRIPTION
**Pull request by feiskyer**
**What this PR does / why we need it**:

Continue of #66242. This PR updates Azure Go SDK to v19.0.0 (with compute API 2018-04-01) and gets availability zones for VirtualMachineScaleSetVM.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Azure Go SDK has been upgraded to v19.0.0 and VirtualMachineScaleSetVM now supports availability zones.
```

/sig azure
/assign @brendandburns @khenidak @andyzhangx

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
looks good to me in general, I will leave `lgtm` trigger to @khenidak

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by feiskyer** [comment]
ping @brendandburns for vendor updates approval

**Pull request merged**
