### PR TITLE
node: e2e: topology-mgr: Determine threads per core to disambiguage cores from cpus

### LINKED ISSUE #120725: [sig-node] Topology Manager Metrics [Serial] [Feature:TopologyManager] when querying /metrics should report admission failures when the topology manager alignment is known to fail
##### Error text:
```
[FAILED] Timed out after 60.000s.
Expected
    <string>: KubeletMetrics
to match keys: {
."kubelet_topology_manager_admission_errors_total"[]:
	Expected
	    <string>: Sample
	to match fields: {
	.Value:
		Expected
		    <model.SampleValue>: 0
		to be ==
		    <int>: 1
	}
	
}
In [It] at: test/e2e_node/topology_manager_metrics_test.go:121 @ 09/13/23 03:11:29.024

```
#### Recent failures:
[2023/9/18 07:03:04 ci-kubernetes-node-kubelet-containerd-resource-managers](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-containerd-resource-managers/1703545104645492736)
[2023/9/18 03:03:03 ci-kubernetes-node-kubelet-containerd-resource-managers](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-containerd-resource-managers/1703484706013581312)
[2023/9/18 02:12:03 ci-kubernetes-node-kubelet-serial-topology-manager](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-topology-manager/1703471871372038144)
[2023/9/17 23:03:04 ci-kubernetes-node-kubelet-containerd-resource-managers](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-containerd-resource-managers/1703424307356504064)
[2023/9/17 19:03:03 ci-kubernetes-node-kubelet-containerd-resource-managers](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-containerd-resource-managers/1703363908724592640)

/kind failing-test

/sig node

started to fail since 09-13.

### PR DESCRIPTION
**Pull request by swatisehgal**
#### What type of PR is this?
/kind failing-test

#### What this PR does / why we need it:
This PR is to fix topology manager metrics e2e tests by determining threads per cores on the system and use that information to disambiguate cores on the machine from cpus. In the current implementation we are conflating cores on the machine with cpus on the node but that is not accurate. 

In the current implementation of the tests, we obtain`coresPerSocket` in the [hostCheck](https://github.com/kubernetes/kubernetes/blob/release-1.28/test/e2e_node/topology_manager_metrics_test.go#L154) but call the [returned variable](https://github.com/kubernetes/kubernetes/blob/release-1.28/test/e2e_node/topology_manager_metrics_test.go#L53)  as `cpusNumPerNuma` which in my opinion is wrong and is causing the confusion. Let's assume that we have a 1-1 mapping of NUMA Node to Socket (which appears to be the case on the CI machine) we have 8 cores per socket/numa. Subsequently, the test creates a pod that requests 9 cpus (by doing cpusNumPerNuma+1 i.e. 8+1=9). The aim here was to create a pod that requests cpus (not cores!) greater than those available on a single NUMA. This particular node had 8 cores per NUMA but what we need is the count of cpus per NUMA which we do by checking threads per core on the node. The system has hyperthreading enabled so we have 16 cpus per NUMA and need to actually request 17 cpus for the pod that should result in Topology affinity error. Since we requested 9 cpus which is less than number of cpus per NUMA (16) the pod succeeded to run and didn't end up in Topology affinity error which explains point 3 in my initial assessment [here](https://github.com/kubernetes/kubernetes/issues/120725#issuecomment-1768935761).

With the changes proposed in this PR, we can see that the topology manager [build log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/121442/pull-kubernetes-node-kubelet-serial-topology-manager/1716426748461060096/build-log.txt) shows us the following:  
```
  Oct 23 12:26:35.381: INFO: numaNodes on the system 2
  Oct 23 12:26:35.381: INFO: Cores per NUMA on the system 8
  Oct 23 12:26:35.381: INFO: Threads per Core on the system 2
  Oct 23 12:26:35.381: INFO: CPUs per NUMA on the system 16
```
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/120725

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by ffromani** [comment]
the individual commits makes sense to me and it seems a straightforward and nice addition, but is not clear how this helps to solve the linked issue. Could you please elaborate (more)?

**Comment by ffromani** [comment]
> > the individual commits makes sense to me and it seems a straightforward and nice addition, but is not clear how this helps to solve the linked issue. Could you please elaborate (more)?
> 
> Sure, I see the topology manager test is passing now so looks like this PR is fixing the failing test. I will use the system in the CI as an example for my explanation:
> 
> In the current implementation of the tests, we obtain`coresPerSocket` in the [hostCheck](https://github.com/kubernetes/kubernetes/blob/release-1.28/test/e2e_node/topology_manager_metrics_test.go#L154) but call the [returned variable](https://github.com/kubernetes/kubernetes/blob/release-1.28/test/e2e_node/topology_manager_metrics_test.go#L53) as `cpusNumPerNuma` which in my opinion is wrong and is causing the confusion. Let's assume that we have a 1-1 mapping of NUMA Node to Socket (which appears to be the case on the CI machine) we have 8 cores per socket/numa. Subsequently, the test creates a pod that requests 9 cpus (by doing cpusNumPerNuma+1 i.e. 8+1=9). The aim here was to create a pod that requests cpus (not cores!) greater than those available on a single NUMA. This particular node had 8 cores per NUMA but what we need is the count of cpus per NUMA which we do by checking threads per core on the node. The system has hyperthreading enabled so we have 16 cpus per NUMA and need to actually request 17 cpus for the pod that should result in Topology affinity error. Since we requested 9 cpus which is less than number of cpus per NUMA (16) the pod succeeded to run and didn't end up in Topology affinity error which explains point 3 in my initial assessment [here](https://github.com/kubernetes/kubernetes/issues/120725#issuecomment-1768935761).
> 
> With the changes proposed in this PR, you can see that the topology manager [build log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/121442/pull-kubernetes-node-kubelet-serial-topology-manager/1716426748461060096/build-log.txt) shows us the following:
> 
> ```
>   Oct 23 12:26:35.381: INFO: numaNodes on the system 2
>   Oct 23 12:26:35.381: INFO: Cores per NUMA on the system 8
>   Oct 23 12:26:35.381: INFO: Threads per Core on the system 2
>   Oct 23 12:26:35.381: INFO: CPUs per NUMA on the system 16
> ```
> 
> Hope this helps.

it does help a lot. Could you please copy-paste (add) this info in the section "why we need it" of your https://github.com/kubernetes/kubernetes/pull/121442#issue-1957012799 ?

**Review by ffromani — COMMENTED** [review]
/lgtm

now that the purpose is clear, codewise this seems fine

**Comment by swatisehgal** [comment]
/assign @SergeyKanzhelev 
for approval

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
