### PR TITLE
metav1.TypeMeta: Implement metav1.Type

### PR DESCRIPTION
**Pull request by alvaroaleman**
The metav1 package exports the Type interface but it is not implemented
by metav1.TypeMeta which is pretty surprising as it is likely the only
type that could reasonably be expected to implement it.

It is useful to have this as it allows to get/set the apiVersion and
kind of objects.

#### What type of PR is this?

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/assign @lavalamp @deads2k

### CODE REVIEW

**Comment by deads2k** [comment]
/hold

While it seem natural at first to have TypeMeta implement this interface, the information available and attributable to an in-memory representation of the data does not lend it self to a consistent group,version,kind (GVK).

Can you clarify the values you would like returned from this interface?

An in-memory representation of the data doesn't have a single GVK, it has any number of potential GVKs (this is what the scheme mapping is for).  The in-memory content may never have been serialized (assembled in memory).  It may have been deserialized and later converted.  And it may be serialized as a different target GVK at some later time.

**Comment by dims** [comment]
this PR has been on hold for about 2 weeks. Can you please see how to unblock this by reviewing comments etc? or please close this out (Trying to declutter our open list of PRs)

**Comment by lavalamp** [comment]
I think we set this data inconsistently in memory, and I'm nervous about making it more accessible. I think we should probably not touch this until https://github.com/kubernetes/kubernetes/issues/80609 is decided.

Additionally given that these functions aren't here, I kind of think that must be deliberate? I'm not sure what the ramifications of making everything embedding this suddenly implement the interface.

There should be other ways of setting these with any of the normal objects, although they may be less convenient. If this isn't true then I'd be more willing to consider this change.

**Comment by alvaroaleman** [comment]
@lavalamp The reason for wanting this is not to Get the apiversion/kind but to set it, for example for creating a bunch of objects in a CLI and then printing it. Combined with something like controller-runtimes `GVKForObject` it allows to set apiVersion and kind for a set of objects generically. I ended up defining an inline-interface for this but it would be nice if it was supported natively: https://github.com/openshift/hypershift/blob/d87e565c0169392a2a9799f2a6409c2ac76afabf/cmd/install/install.go#L487-L496

The only reason I also implemented the Getters was because I thought it would be nice to re-use the existing interface, not because it is needed for this usecase

**Comment by lavalamp** [comment]
> not to Get the apiversion/kind but to set it

1. But other people may call the Getters and not get the contract they expect.
2. Setting this is dangerous! Very strange things may happen if it is set wrong.

**Comment by alvaroaleman** [comment]
> But other people may call the Getters and not get the contract they expect.

Right, I don't have strong feelings for these getters and I can remove them.

> Setting this is dangerous! Very strange things may happen if it is set wrong.

Well yes, but that is true for almost all fields in all objects and we do not consider that a reason to not make them settable. Using something like the `GVKForObject` works reliably until someone registers the same go type in different GVKs, but that happens seldom enough that no one even bothered to handle this better than to just error.

**Comment by lavalamp** [comment]
> that is true for almost all fields in all objects and we do not consider that a reason to not make them settable.

Other fields are dangerous to users, but not necessarily to the encoding system :)

Probably the right thing to do is to have getters but no setters, and have the decoding system set these fields correctly all the time. (the unstructured types need setters, of course.) The problem is what to do with newly declared objects? It is weird to require users to set this correctly for a new object they just made. (Since we don't have constructors. Which maybe we could add...) I believe this was the reason for the original rule of "set on disk, but not in memory" that I had.

**Pull request closed without merging**
