### PR TITLE
Fix invalid url link in cluster/addons/registry/auth/README.md

### PR DESCRIPTION
**Pull request by fisherxu**
**What this PR does / why we need it**:
Fix invalid url link in `cluster/addons/registry/auth/README.md`.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fisherxu** [comment]
thanks @NickrenREN  : )

**Comment by fisherxu** [comment]
Kindly ping @eparis  @jbeda for review this pr, thanks!

**Comment by fisherxu** [comment]
Kindly ping @mikedanese @roberthbailey @zmerlynn @eparis @jbeda help review this fix, thanks!

**Comment by fisherxu** [comment]
@pipejakob @dchen1107 Can you help review this pr?

**Comment by pipejakob** [comment]
The change itself looks fine to me (it's just a trivial URL fix), so you have my LGTM. I'm not sure if we have a preference for using github links to the master branch in these .md files instead of links to kubernetes.io, but since the existing link is broken, I would say either one is an improvement. :-)

Can one of the `cluster/` owners approve this as well?

**Comment by fisherxu** [comment]
> I'm not sure if we have a preference for using github links to the master branch in these .md files instead of links to kubernetes.io

I think it should be using the github links to the master branch, so I have fixed it!

**Comment by fisherxu** [comment]
@roberthbailey because fix is very simple, I don't open an issue, can you help**add approve no-issue**? Thanks

**Pull request merged**
