### PR TITLE
Fix the nil pointer dereference in addHashKeyToRSAndPods

### LINKED ISSUE #21765: e2e flake: panic in 'RollingUpdateDeployment should scale up and down in the right order' [nil pointer dereference]
Seen here https://github.com/kubernetes/kubernetes/pull/17913#issuecomment-187724995

http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/29960/
https://pantheon.corp.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/17913/kubernetes-pull-build-test-e2e-gce/29960/artifacts/?debugUI=CLOUD
```
â€¢! Panic [38.920 seconds]
Deployment
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:72
  RollingUpdateDeployment should scale up and down in the right order [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:50

  Test Panicked
  runtime error: invalid memory address or nil pointer dereference
  /usr/src/go/src/runtime/panic.go:387

  Full Stack Trace
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/deployment/deployment.go:194 (0xa13d3e)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/deployment/deployment.go:157 (0xa1364a)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/deployment/deployment.go:73 (0xa12159)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/deployment/deployment.go:58 (0xa11f90)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/util.go:2111 (0x56d42f)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:181 (0x8ca0e0)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:143 (0x8c9efb)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:137 (0x8c9e4c)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/util.go:2148 (0x531960)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:328 (0x480d4d)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:49 (0x58c4aa)
  /go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/onsi/ginkgo/internal/leafnodes/runner.go:109 (0x13aff25)
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:28 (0x541cb8)
  /usr/src/go/src/testing/testing.go:447 (0x46112f)
  /usr/src/go/src/runtime/asm_amd64.s:2232 (0x440541)
```

### PR DESCRIPTION
**Pull request by janetkuo**
Fixes #21765

cc @bgrant0607 @nikhiljindal @ironcladlou @kargakis @kubernetes/sig-config @madhusudancs @mqliang

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM

**Comment by janetkuo** [comment]
@k8s-bot e2e test this issue: #21809 #21798 #21753

**Comment by janetkuo** [comment]
@k8s-bot e2e test this issue: #21809 #21753

**Comment by janetkuo** [comment]
#21809 is especially flaky in this PR. Finding the cause and removing LGTM.

**Comment by bgrant0607** [comment]
@k8s-bot test this issue: #21753

**Comment by janetkuo** [comment]
The flake is due to timeout labeling rs's label and selector. Add the fix to prevent conflict.

**Comment by bgrant0607** [comment]
@k8s-bot test this issue: #21809

**Comment by janetkuo** [comment]
@k8s-bot e2e test this issue: #IGNORE (test cluster failed to start)

**Comment by bgrant0607** [comment]
@k8s-bot test this issue: #21809

**Comment by bgrant0607** [comment]
I merged  #21856, so hopefully that will fix the e2e flake. Or we'll know it's something else. :-)

**Comment by bgrant0607** [comment]
Still fails with `total pods available: 0, less than the min required: 2`

**Comment by janetkuo** [comment]
I believe I've found the cause of #21809. 

The 3 old pods are labeled with correctly (let's say hash = A). However, after we add new hash label to rs's pod template, the hash value of this pod template changed (hash = B). Before rs selector being updated, the 3 old pods may be labeled again with hash value B but the rs has hash value A. And thus the adopted rs needs to re-created 3 new pods. 

The last commit is the fix. @bgrant0607 PTAL

**Comment by bgrant0607** [comment]
LGTM.

Merging to fix this flake.

**Pull request merged**
