### PR TITLE
Check pod RestartPolicy before restarting unhealthy containers

### PR DESCRIPTION
**Pull request by timstclair**
Fixes https://github.com/kubernetes/kubernetes/issues/14930

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by ncdc** [comment]
Does this also fix #14491 (is that issue a dupe of 14930)?

**Comment by yujuhong** [comment]
> Does this also fix #14491 (is that issue a dupe of 14930)?

No, #14491 will be fixed by #15082

**Comment by ncdc** [comment]
@yujuhong thanks for the clarification

**Pull request merged**
