### PR TITLE
Validate pod spec.nodeName

### PR DESCRIPTION
**Pull request by liggitt**
Ensure pod nodeName is well formed

### CODE REVIEW

**Comment by liggitt** [comment]
cc @fabianofranz

**Comment by deads2k** [comment]
unit test.

**Comment by fabianofranz** [comment]
LGTM

**Comment by deads2k** [comment]
lgtm

**Comment by liggitt** [comment]
rebased

**Comment by liggitt** [comment]
@k8s-bot test this

**Comment by liggitt** [comment]
updated for fieldPath validation change

**Comment by liggitt** [comment]
@k8s-bot unit test this

**Pull request merged**
