### PR TITLE
kubeadm: fix test failures in the e2e_kubeadm suite

### LINKED ISSUE #106311: [Failing test][sig-cluster-lifecycle] kubeadm-kinder-latest-on-1-22
### Which jobs are failing?

kubeadm-kinder-latest-on-1-22

### Which tests are failing?

* E2EKubeadm suite.[sig-cluster-lifecycle] [area-kubeadm] proxy addon kube-proxy ServiceAccount should be bound to the system:node-proxier cluster role
* ci-kubernetes-e2e-kubeadm-kinder-latest-on-1-22.Overall
* task-06-e2e-kubeadm

### Since when has it been failing?

2021-11-09 23:31 CET

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-latest-on-1-22

### Reason for failure (if possible)

[Run](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-latest-on-1-22/1458443045455269888): E2EKubeadm suite: [sig-cluster-lifecycle] [area-kubeadm] proxy addon kube-proxy ServiceAccount should be bound to the system:node-proxier cluster role 
```bash
_output/local/go/src/k8s.io/kubernetes/test/e2e_kubeadm/proxy_addon_test.go:65
error getting ClusterRoleBindings "kubeadm:node-proxier"
Unexpected error:
    <*errors.StatusError | 0xc000416960>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "clusterrolebindings.rbac.authorization.k8s.io \"kubeadm:node-proxier\" not found",
            Reason: "NotFound",
            Details: {
                Name: "kubeadm:node-proxier",
                Group: "rbac.authorization.k8s.io",
                Kind: "clusterrolebindings",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
    clusterrolebindings.rbac.authorization.k8s.io "kubeadm:node-proxier" not found
occurred
_output/local/go/src/k8s.io/kubernetes/test/e2e_kubeadm/util.go:136
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig cluster-lifecycle

### LINKED ISSUE #106318: [Failing test][sig-cluster-lifecycle] kubeadm-kinder-latest
### Which jobs are failing?

kubeadm-kinder-latest

### Which tests are failing?

* ci-kubernetes-e2e-kubeadm-kinder-latest.Overall
* E2EKubeadm suite.[sig-cluster-lifecycle] [area-kubeadm] proxy addon kube-proxy ServiceAccount should be bound to the system:node-proxier cluster role

### Since when has it been failing?

2021-11-09 23:32 CET

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-latest

### Reason for failure (if possible)

([job run](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-latest/1458473496693706752))
E2EKubeadm suite: [sig-cluster-lifecycle] [area-kubeadm] proxy addon kube-proxy ServiceAccount should be bound to the system:node-proxier cluster role
```bash
_output/local/go/src/k8s.io/kubernetes/test/e2e_kubeadm/proxy_addon_test.go:65
error getting ClusterRoleBindings "kubeadm:node-proxier"
Unexpected error:
    <*errors.StatusError | 0xc0005259a0>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "clusterrolebindings.rbac.authorization.k8s.io \"kubeadm:node-proxier\" not found",
            Reason: "NotFound",
            Details: {
                Name: "kubeadm:node-proxier",
                Group: "rbac.authorization.k8s.io",
                Kind: "clusterrolebindings",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
    clusterrolebindings.rbac.authorization.k8s.io "kubeadm:node-proxier" not found
occurred
_output/local/go/src/k8s.io/kubernetes/test/e2e_kubeadm/util.go:136
```

```bash
   _output/local/go/src/k8s.io/kubernetes/test/e2e_kubeadm/proxy_addon_test.go:65
[AfterEach] [sig-cluster-lifecycle] [area-kubeadm] proxy addon
  /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:186
Nov 10 16:51:29.201: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready

• Failure [0.015 seconds]
[sig-cluster-lifecycle] [area-kubeadm] proxy addon
_output/local/go/src/k8s.io/kubernetes/test/e2e_kubeadm/framework.go:23
  kube-proxy ServiceAccount
  _output/local/go/src/k8s.io/kubernetes/test/e2e_kubeadm/proxy_addon_test.go:60
    should be bound to the system:node-proxier cluster role [It]

[Fail] [sig-cluster-lifecycle] [area-kubeadm] proxy addon kube-proxy ServiceAccount [It] should be bound to the system:node-proxier cluster role 
_output/local/go/src/k8s.io/kubernetes/test/e2e_kubeadm/util.go:136
Ran 31 of 37 Specs in 0.766 seconds
FAIL! -- 30 Passed | 1 Failed | 0 Pending | 6 Skipped
--- FAIL: TestE2E (0.78s)
FAIL

Ginkgo ran 1 suite in 842.396245ms
Test Suite Failed
Error: error running test: exit status 1
 exit status 1

Deleting cluster "kinder-regular" ...
 completed!
Ran 10 of 11 tasks in 0.000 seconds
FAIL! -- 9 tasks Passed | 1 Failed | 1 Skipped

see junit-runner.xml and task logs files for more details

Error: failed executing the workflow 
```

### Anything else we need to know?

This issue seems to be linked to #106311 

FYI: [slack discussion](https://kubernetes.slack.com/archives/CN0K3TE2C/p1636555957038200)

/cc @neolit123 

### Relevant SIG(s)

/sig cluster-lifecycle
/area kubeadm

### PR DESCRIPTION
**Pull request by neolit123**
#### What this PR does / why we need it:

```
kubeadm: fix typo in KubeProxyClusterRoleBindingName constant 

kubeam:node-proxier -> kubeadm:node-proxier
This causes e2e test failures:
"[area-kubeadm] proxy addon kube-proxy ServiceAccount should
be bound to the system:node-proxier cluster role"

in:
- kubeadm-kinder-latest
- kubeadm-kinder-latest-on-...
- other tests
```

```
kubeadm: fix failure in e2e_kubeadm related to kubelet-config 

The featureGates field in ClusterConfiguration ends up
as a map[interface{}]interface{} in the test suite
and cannot be casted to map[string]bool directly.
Adapt the test to use map[interface{}]interface{}.

fixes failures in:
- kubeadm-kinder-rootless-latest
```

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/106318
Fixes https://github.com/kubernetes/kubernetes/issues/106311

#### Special notes for your reviewer:
NONE

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
tested locally and should fix these failures:
```
Fixes #106318
Fixes #106311
```

https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm

**Comment by neolit123** [comment]
> kubeadm: fix typo in KubeProxyClusterRoleBindingName constant 

introduced in https://github.com/kubernetes/kubernetes/pull/106243
cc @calvin0327

**Comment by calvin0327** [comment]
> > kubeadm: fix typo in KubeProxyClusterRoleBindingName constant
> 
> introduced in #106243 cc @calvin0327 (i missed the typo, but our e2e test caught it...)

Thanks for reminding me.

**Pull request merged**
