### PR TITLE
make sure to check for errors and close the request body in the cluster size autoscaling e2e test

### PR DESCRIPTION
**Pull request by tanshanshan**
**What this PR does / why we need it**:
make sure to check for errors and close the request body in the cluster size autoscaling e2e test
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by DirectXMan12** [comment]
this needs a better description (e.g. "make sure to check for errors and close the request body in the cluster size autoscaling e2e test")

**Comment by oomichi** [comment]
This just adds an error handling and @DirectXMan12's point seems to be fixed.
So for getting approval

/assign @spiffxp

**Pull request merged**
