### PR TITLE
Add HTTP cAdvisor dependencies.

### PR DESCRIPTION
**Pull request by vmarmol**
Also removed unused goamz.

### CODE REVIEW

**Comment by vishh** [comment]
Are you planning on exposing cadvisor HTTP endpoints via kubelet?

**Comment by vmarmol** [comment]
Yes, primarily for container VMs. It'll still be exported in its own port.

**Comment by vishh** [comment]
Ok. Since cadvisor uses a different versioning scheme than kubelet, I hope it doesn't confuse users.

**Comment by vmarmol** [comment]
We should be okay since it is on a different port. The change should be invisible from the outside :)

**Comment by vishh** [comment]
Ack. LGTM

**Comment by justinsb** [comment]
@vmarmol  Wondering why you removed the goamz elb dependency?  Was it causing a problem?

The elb dependency will be needed for AWS ELB support.  There's a WIP PR that I'm working on #5225.  But I'm trying to do many smaller patches, rather than one big patch.

**Comment by vmarmol** [comment]
@justinsb godep made the change and I figured it was a stale dependency we no longer used. Sorry about that :) feel free to send a PR with it and I'll gladly merge.

**Pull request merged**
