### PR TITLE
Remove ericchiang from OWNERS files

### PR DESCRIPTION
**Pull request by ericchiang**
Kept myself in the OpenID Connect ones.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ericchiang** [comment]
/assign @smarterclayton

Since I'll need a top level approver 😃

**Comment by smarterclayton** [comment]
:)

/approve

**Pull request merged**
