### PR TITLE
Fix reboot test to use system namespace

### LINKED ISSUE #11079: Reboot (and probably many other) tests no longer have pods to look at
They used to look at all pods in the default namespace, which used to contain all of the vital infrastructure pods. The purpose of looking at these was to ensure the system was fully healthy after a reboot, restart, upgrade, etc.

However, now I see in the test:

```
INFO: Wanted all 0 pods to be running and ready. Result: true. Pods: []
```

I'm guessing this was related to the big namespace change? When moving all of the pods out of the default namespace we must have forgotten to update all of the tests that check the infrastructure pods.

I think this is fairly important because all of these tests are far weaker as a result. (We've caught many bugs in DNS, elasticsearch, kubelet, salt, ... by ensuring pods are running & ready in tests.)

Relatedly, if we switch the minimum here from 0 to 1 in GCE (it was 1 before), we could catch a test regression like this from happening again.

### PR DESCRIPTION
**Pull request by satnam6502**
Fixes #11079

### CODE REVIEW

**Comment by satnam6502** [comment]
```
Reboot 
  each node by ordering clean reboot and ensure they function upon restart
  /usr/local/google/home/satnam/gocode/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/reboot.go:65
[BeforeEach] Reboot
  /usr/local/google/home/satnam/gocode/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/reboot.go:59
>>> testContext.KubeConfig: /usr/local/google/home/satnam/.kube/config
[It] each node by ordering clean reboot and ensure they function upon restart
  /usr/local/google/home/satnam/gocode/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/reboot.go:65
INFO: Getting e2e-test-satnam-minion-bhvc
INFO: Getting e2e-test-satnam-minion-smvb
INFO: Waiting up to 20s for node e2e-test-satnam-minion-bhvc readiness to be true
INFO: Waiting up to 20s for node e2e-test-satnam-minion-smvb readiness to be true
INFO: Node e2e-test-satnam-minion-bhvc condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transistion time: 2015-07-10 14:03:29 -0700 PDT
INFO: Successfully found node e2e-test-satnam-minion-bhvc readiness to be true
INFO: Node e2e-test-satnam-minion-bhvc has 4 pods: [elasticsearch-logging-v1-swml7 fluentd-elasticsearch-e2e-test-satnam-minion-bhvc kube-dns-v6-zteq4 kube-ui-v1-rgj8t]
INFO: Waiting up to 20s for the following 4 pods to be running and ready: [elasticsearch-logging-v1-swml7 fluentd-elasticsearch-e2e-test-satnam-minion-bhvc kube-dns-v6-zteq4 kube-ui-v1-rgj8t]
INFO: Waiting up to 20s for pod elasticsearch-logging-v1-swml7                          status to be running and ready
INFO: Waiting up to 20s for pod fluentd-elasticsearch-e2e-test-satnam-minion-bhvc       status to be running and ready
INFO: Waiting up to 20s for pod kube-dns-v6-zteq4                                       status to be running and ready
INFO: Waiting up to 20s for pod kube-ui-v1-rgj8t                                        status to be running and ready
INFO: Node e2e-test-satnam-minion-smvb condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transistion time: 2015-07-10 14:03:31 -0700 PDT
INFO: Successfully found node e2e-test-satnam-minion-smvb readiness to be true
INFO: Node e2e-test-satnam-minion-smvb has 5 pods: [monitoring-heapster-v5-p6yth monitoring-influx-grafana-v1-7je13 elasticsearch-logging-v1-hiovw fluentd-elasticsearch-e2e-test-satnam-minion-smvb kibana-logging-v1-m5qx0]
INFO: Waiting up to 20s for the following 5 pods to be running and ready: [monitoring-heapster-v5-p6yth monitoring-influx-grafana-v1-7je13 elasticsearch-logging-v1-hiovw fluentd-elasticsearch-e2e-test-satnam-minion-smvb kibana-logging-v1-m5qx0]
INFO: Waiting up to 20s for pod monitoring-heapster-v5-p6yth                            status to be running and ready
INFO: Waiting up to 20s for pod monitoring-influx-grafana-v1-7je13                      status to be running and ready
INFO: Waiting up to 20s for pod elasticsearch-logging-v1-hiovw                          status to be running and ready
INFO: Waiting up to 20s for pod fluentd-elasticsearch-e2e-test-satnam-minion-smvb       status to be running and ready
INFO: Waiting up to 20s for pod kibana-logging-v1-m5qx0                                 status to be running and ready
INFO: Wanted all 4 pods to be running and ready. Result: true. Pods: [elasticsearch-logging-v1-swml7 fluentd-elasticsearch-e2e-test-satnam-minion-bhvc kube-dns-v6-zteq4 kube-ui-v1-rgj8t]
INFO: Getting external IP address for e2e-test-satnam-minion-bhvc
INFO: Calling nohup sh -c 'sleep 10 && sudo reboot' >/dev/null 2>&1 & on e2e-test-satnam-minion-bhvc
INFO: Using SSH key: /usr/local/google/home/satnam/.ssh/google_compute_engine
INFO: Waiting up to 2m0s for node e2e-test-satnam-minion-bhvc readiness to be false
INFO: Wanted all 5 pods to be running and ready. Result: true. Pods: [monitoring-heapster-v5-p6yth monitoring-influx-grafana-v1-7je13 elasticsearch-logging-v1-hiovw fluentd-elasticsearch-e2e-test-satnam-minion-smvb kibana-logging-v1-m5qx0]
INFO: Getting external IP address for e2e-test-satnam-minion-smvb
INFO: Calling nohup sh -c 'sleep 10 && sudo reboot' >/dev/null 2>&1 & on e2e-test-satnam-minion-smvb
INFO: Using SSH key: /usr/local/google/home/satnam/.ssh/google_compute_engine
INFO: Node e2e-test-satnam-minion-bhvc condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transistion time: 2015-07-10 14:03:29 -0700 PDT
INFO: Waiting up to 2m0s for node e2e-test-satnam-minion-smvb readiness to be false
INFO: Node e2e-test-satnam-minion-smvb condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transistion time: 2015-07-10 14:03:31 -0700 PDT
INFO: Node e2e-test-satnam-minion-bhvc condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transistion time: 2015-07-10 14:03:29 -0700 PDT
INFO: Node e2e-test-satnam-minion-smvb condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transistion time: 2015-07-10 14:03:31 -0700 PDT
INFO: Node e2e-test-satnam-minion-bhvc condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transistion time: 2015-07-10 14:03:29 -0700 PDT
INFO: Node e2e-test-satnam-minion-smvb condition 1/1: type: Ready, status: True, reason: "kubelet is posting ready status", message: "", last transistion time: 2015-07-10 14:03:31 -0700 PDT

```

**Comment by satnam6502** [comment]
@quinton-hoole

**Comment by mbforbes** [comment]
Thank you @satnam6502! Let me take a quick skim over some other tests to see if we can fix them at the same time...

**Comment by mbforbes** [comment]
I've got a few more in Restart:
- https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/restart.go#L67
- https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/restart.go#L92

The following function uses the default namespace and is dead code (no one calls it):
- https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/util.go#L555

The following is in `e2e/util.go` that I think we could probably safely switch from default to system as it's likely not doing anything right now:
- https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/util.go#L1226

There are a few others in `e2e/util.go` (`waitForPodRunning()`, `testContainerOutput()`) that use the default namespace that we should probably audit but I don't have time for right now because they're called in one or more "real" tests... would you be kind enough to open an issue to finish flushing this out? I worry we have more silent passes..

**Comment by satnam6502** [comment]
Fixed `restart.go`, removed dead code from `util.go`

**Comment by mbforbes** [comment]
This LGTM. +cc @ixdy @roberthbailey @davidopp for reviews?

**Comment by roberthbailey** [comment]
LGTM.

**Comment by ixdy** [comment]
LGTM, @satnam6502 did you run all affected tests locally? (They won't run in the pull request builder.)

**Comment by satnam6502** [comment]
No. I ran out of time.

**Comment by satnam6502** [comment]
About to start running the e2e tests locally... will report back.

**Comment by satnam6502** [comment]
`expose_test.go` failed locally -- looking into it.

**Comment by satnam6502** [comment]
Unit test perhaps failing for unrelated reason #11115

**Comment by davidopp** [comment]
LGTM

Shippable failure is indeed #11105

**Comment by satnam6502** [comment]
I ran a local full e2 suit for this in a screen session but when I went to resume it I somehow lost the context. I am not totally confident I have a recent full e2e good run for this PR. Please can we be vigilant with Jenkins etc. in case this turns out to be a breaking PR.

**Pull request merged**
