### PR TITLE
Automated cherry pick of #120942: Fix issue in enabling evented pleg feature gate

### PR DESCRIPTION
**Pull request by sairameshv**
Cherry pick of #120942 on release-1.28.

#120942: Fix issue in enabling evented pleg feature gate

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fixed a regression in the Kubelet's behavior while creating a container when the `EventedPLEG` feature gate is enabled
```

### CODE REVIEW

**Comment by liggitt** [comment]
this feature was reverted to alpha in January and backported (see https://github.com/kubernetes/kubernetes/pull/122697 and backports)

I'm -1 on backporting more changes related to this feature while it is in alpha state.

**Comment by sairameshv** [comment]
> this feature was reverted to alpha in January and backported (see #122697 and backports)
> 
> I'm -1 on backporting more changes related to this feature while it is in alpha state.

Hello @liggitt , 
This is one of the critical fixes required to avoid the creation of duplicate containers irrespective of the feature's state.

However, I'm okay with delaying this fix till the feature gets stabilized.

**Comment by yujuhong** [comment]
/close

since the feature was in alpha state

**Pull request closed without merging**
