### PR TITLE
cherry-pick #53647

### PR DESCRIPTION
**Pull request by wenlxie**
cherry-pick https://github.com/kubernetes/kubernetes/pull/53647

**Release note**:

```release-note
scheduler: Fix issue were a new pod with affinity gets stuck at `creating` because the node had been deleted but the pod still exists.
```

### CODE REVIEW

**Comment by k82cn** [comment]
I'm ok with that. Please ping 1.8 release manger to get approval :).

**Comment by wenlxie** [comment]
thanks @k82cn  
@jpbetz  This is a fix for kube-scheduler, pod can't get scheduled when node get deleted but pod are still exists. Can we get this merged  to k8s 1.8?

**Comment by jpbetz** [comment]
@wenlxie please add a release note. The bot will not merge this without one.

**Comment by wenlxie** [comment]
@jpbetz  Thanks, release-note added.

**Pull request merged**
