### PR TITLE
Make error messages more helpful in some e2e tests

### LINKED ISSUE #34059: destroy the "Expect(err).NotTo(HaveOccurred())" anti-pattern in e2e tests
I'm getting tired of seeing flake issues like https://github.com/kubernetes/kubernetes/issues/33647 where every single failure is of the form

```
Expected error:
    <*errors.errorString | 0xc820412c10>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
```

This is about as unhelpful an error message as you can get.

The problem is that we have

``` go
Expect(err).NotTo(HaveOccurred())
```

peppered throughout the code everywhere, and in this form, you can only figure out what failed if you read the Ginkgo error, remember which line has the line number you actually want, and then try to read surrounding code in that file.

Possible improvements given in http://onsi.github.io/gomega/#handling-errors:
- Use `Succeed()`
- Annotate the assertions
- Basically, do anything except just Expect(err).NotTo(HaveOccurred())

cc @kubernetes/sig-testing

### PR DESCRIPTION
**Pull request by vikramk7**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This cleans up the assertions in the test code.

**Which issue(s) this PR fixes**:
Fixes #34059

Fixes #34059

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```
NONE
```

```release-note

```

### CODE REVIEW

**Comment by vikramk7** [comment]
Verified the email address on the CLA.

**Comment by ixdy** [comment]
@vikramk7 it looks like the email address you used to author the commit included your workstation's hostname rather than your real email domain.

Check your git config:
```console
$ git config user.email
```

and then if that looks correct, reset the author on your commit:
```console
$ git checkout <whatever-branch>
$ git commit --amend --reset-author
$ git push -f
```

**Comment by ibrasho** [comment]
Do we generally follow the practice of error messages starting with a lower-case letter?

**Comment by ibrasho** [comment]
/kind cleanup

@vikramk7 Could you  please update the PR description to move `NONE` inside the code block?

From this:

> \**Does this PR introduce a user-facing change?**:
> NONE
> 
> \```
> 
> \```

To this:

> \**Does this PR introduce a user-facing change?**:
> 
> \```
> NONE
> \```

**Comment by vikramk7** [comment]
> Do we generally enforce "errors should start with a lower character"?

It looked like the right thing to do as it made the test more readable IMO. I can change it to whatever style is preferred (this is my first commit to k8s).


> @vikramk7 Could you please update the PR description to move `NONE` inside the code block?
 
Done. Thanks.

**Comment by vikramk7** [comment]
> @vikramk7 it looks like the email address you used to author the commit included your workstation's hostname rather than your real email domain.

I have fixed the issue. Please let me know if this looks OK now.

**Pull request merged**
