### PR TITLE
Deps: update gonum from 0.6.1, drop rsc.io/pdf.

### PR DESCRIPTION
**Pull request by dlorenc**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

rsc.io/pdf was being pulled in through a few indirect dependencies. This
commit updates those far enough to drop that archived dependency. Note that
there are still several other (unmaintained) PDF libraries in the vendor tree.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
@dlorenc my apologies, i totally did not see this. let's try to land this once 1.22 opens up in master.

**Comment by dlorenc** [comment]
> @dlorenc my apologies, i totally did not see this. let's try to land this once 1.22 opens up in master.

No worries! I think you noticed but this didn't work anyway back then and wasn't really possible. gonum and goplot have now released enough new versions to break the cycle! This should be good now.

**Comment by dims** [comment]
@dlorenc this adds more stuff ... we need to look deeper?

```
2c2
< 	"totalDependencies": 364,
---
> 	"totalDependencies": 373,
4c4
< 	"transitiveDependencies": 238
---
> 	"transitiveDependencies": 247
```

**Comment by dlorenc** [comment]
Whoops, this one can get closed!

**Comment by dlorenc** [comment]
I'll followup with more when I figure out where these are coming from!

**Pull request closed without merging**
