### PR TITLE
vendor: downgrade github.com/matttproud/golang_protobuf_extensions to v1.0.1

### PR DESCRIPTION
**Pull request by thaJeztah**
This dependency was updated in 6b864dc4e10bf62508ecbfa3106ac7952004ea9e, but using a version that's 1 commit ahead of the latest (v1.0.1) release. As a consequence, any project that uses k8s.io/component-base as a dependency, but that prefers to use tagged releases, will be required to add a `replace` rule in their `go.mod`.

Looking at the difference between the currently used version and the last release, the only difference is the addition of a `go.mod`:
https://github.com/matttproud/golang_protobuf_extensions/compare/v1.0.1...c182affec369

While it can help to have a `go.mod` to resolve the minimum version of (indirect) dependencies, in this case, the (minimum) versions of dependencies defined in this module's `go.mod` are quite a bit behind the version defined in k8s' own go.mod, so would already be up-to-date.

Based on the above, it looks like the `go.mod` (currently) doesn't provide much value, and it would be safe to roll back 1 commit to use the tagged/released version of this module.

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

See description above

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by thaJeztah** [comment]
/cc @dims 

I went looking where the v1.0.2-0.20181231171920-c182affec369 version came from, which brought me to https://github.com/kubernetes/kubernetes/commit/6b864dc4e10bf62508ecbfa3106ac7952004ea9e. Definitely not "urgent", but downgrading made for a slightly cleaner dependency tree (and reduces `replace` rules); let me know what you think though (happy to close it you prefer not to make this change)

**Comment by dims** [comment]
@thaJeztah this is a good suggestion. Let's hold onto this one until we bump the cadvisor + containerd (when containerd 1.6 ships and cadvisor picks up that version). We can try to ensure this dependency stays in 1.0.1 there in that PR. If needed we can apply this after that (if we do it before, then we may regress when we do that PR).

**Comment by thaJeztah** [comment]
Makes sense! I'll keep it opened here; ping me if updates or rebases are needed 👍

**Comment by dims** [comment]
> Makes sense! I'll keep it opened here; ping me if updates or rebases are needed 👍

Will do. thanks @thaJeztah !

**Comment by ritazh** [comment]
/remove-sig auth
Feel free to add us back if needed.

**Comment by thaJeztah** [comment]
forgot I had this one open; rebased; 

@dims was there any change in https://github.com/kubernetes/kubernetes/pull/108108#issuecomment-1039335899, or still the same?

> @thaJeztah this is a good suggestion. Let's hold onto this one until we bump the cadvisor + containerd (when containerd 1.6 ships and cadvisor picks up that version). We can try to ensure this dependency stays in 1.0.1 there in that PR. If needed we can apply this after that (if we do it before, then we may regress when we do that PR).

**Comment by dims** [comment]
/retest
/approve
/lgtm

/assign @liggitt @smarterclayton 
(for root OWNERS approval)

**Comment by dims** [comment]
@thaJeztah let's get this in!

**Comment by thaJeztah** [comment]
whoop! thx!

**Comment by liggitt** [comment]
fyi, there's a 1.0.2 tag now that includes go.mod info

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/112738 to pick that up

**Pull request merged**
