### PR TITLE
Fixes crash when proxy is run with --cleanup-iptables=true.

### PR DESCRIPTION
**Pull request by aveshagarwal**
Fixes crash when proxy is run with --cleanup-iptables=true.

### CODE REVIEW

**Comment by ncdc** [comment]
@aveshagarwal is this covered by a test case somewhere?

**Comment by aveshagarwal** [comment]
@ncdc I dont think so.

**Comment by ncdc** [comment]
Would you be able to add one?

**Comment by aveshagarwal** [comment]
@ncdc ok I wlll  look into that.

**Comment by aveshagarwal** [comment]
Rebased and updated PR.

**Comment by aveshagarwal** [comment]
@k8s-bot test this

**Comment by aveshagarwal** [comment]
@k8s-bot test this

**Comment by aveshagarwal** [comment]
@k8s-bot test this again  Not sure why shippable shows failed.

**Comment by aveshagarwal** [comment]
@k8s-bot test this

**Comment by aveshagarwal** [comment]
@k8s-bot test this.

**Pull request merged**
