### PR TITLE
[Federation] Marked the tests that don't need registered clusters so.

### PR DESCRIPTION
**Pull request by madhusudancs**
Somewhat related to issue #40766. 

cc @kubernetes/sig-federation-pr-reviews

### CODE REVIEW

**Comment by shashidharatd** [comment]
There is one test case in [federated-service.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_federation/federated-service.go#L98) which is not dependent on registered cluster. The describe clauses are little messed up in that file. @madhusudancs, request to correct the describe clauses and add a [NoCluster] to that test case too.

**Comment by shashidharatd** [comment]
LGTM. we can handle the correcting the describe clauses in federated-services.go in subsequent pr's
/lgtm

**Comment by shashidharatd** [comment]
test timed out. triggering again to see if its a random issue.
@k8s-bot cvm gke e2e test this

**Comment by madhusudancs** [comment]
> There is one test case in federated-service.go which is not dependent on registered cluster.

Wow! Good catch! Thanks. 

> The describe clauses are little messed up in that file. @madhusudancs, request to correct the describe clauses and add a [NoCluster] to that test case too.

Ok, admittedly that file is absurd. Made the suggested change in PR #40786. PTAL.

**Pull request merged**
