### PR TITLE
KEP-4222: Bump github.com/fxamacker/cbor/v2 to v2.7.0.

### PR DESCRIPTION
**Pull request by benluddy**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://kep.k8s.io/4222
```

### CODE REVIEW

**Comment by benluddy** [comment]
/cc @dims 

This is the promised non-beta CBOR bump.

**Comment by liggitt** [comment]
/approve

needs rebase, then can lgtm

**Comment by benluddy** [comment]
@liggitt PTAL, rebased.

**Pull request merged**
