### PR TITLE
fix errror message

### PR DESCRIPTION
**Pull request by mqliang**
fix errror message

### CODE REVIEW

**Comment by ashcrow** [comment]
:+1: looks good and replaces the erroneous error message with a valid one.

@smarterclayton

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
@k8s-bot ok to test

**Comment by ashcrow** [comment]
I don't think these failures in Jenkins e2e are related to the error string change.

```
Summarizing 3 Failures:

[Fail] Pod Disks [It] should schedule a pod w/ a RW PD shared between multiple containers, write to PD, delete pod, verify contents, and repeat in rapid succession 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:207

[Fail] Pod Disks [It] should schedule a pod w/two RW PDs both mounted to one container, write to PD, verify contents, delete pod, recreate pod, verify contents, and repeat in rapid succession 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:266

[Fail] Addon update [BeforeEach] should propagate add-on file changes 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:72
```

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by ashcrow** [comment]
e2e timeout flake.

**Comment by ArtfulCoder** [comment]
manually merging since merge-bot isnt working because of scalability test failure issues

**Pull request merged**
