### PR TITLE
Automated cherry pick of #104146: Remove duplicate dependencies from 1.22 changelog

### PR DESCRIPTION
**Pull request by cpanato**
Cherry pick of #104146 on release-1.22.

#104146: Remove duplicate dependencies from 1.22 changelog

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by cpanato** [comment]
@kubernetes/release-managers @saschagrunert PTAL

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
