### PR TITLE
Update fluentd-gcp version

### PR DESCRIPTION
**Pull request by crassirostris**
Updates the `fluent-plugin-google-cloud` version to `0.6.3`. This patch containes bug fixes

### CODE REVIEW

**Comment by piosz** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by crassirostris** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by crassirostris** [comment]
@piosz @igorpeshansky Turns out new google cloud output plugin has a regression, it doesn't specify namespace name and pod name in the exported resource and that's why tests are failing

**Comment by igorpeshansky** [comment]
For the record, the regression @crassirostris mentioned is fixed in version `0.6.3`.

**Comment by crassirostris** [comment]
Yes, thanks to @igorpeshansky and @qingling128 for a quick fix!

**Comment by crassirostris** [comment]
Since the only change since lgtm is `v2.0.3` -> `v2.0.4` and the point of this PR hasn't changed, re-applying the lgtm label from https://github.com/kubernetes/kubernetes/pull/45892#issuecomment-302023025

**Pull request merged**
