### PR TITLE
[1.12] Automated cherry pick of #75144: kubelet: updated logic of verifying a static critical pod

### PR DESCRIPTION
**Pull request by Huang-Wei**
Cherry pick of #75144 on release-1.12.

#75144: kubelet: updated logic of verifying a static critical pod

### CODE REVIEW

**Comment by Huang-Wei** [comment]
/assign @derekwaynecarr
for approval

/assign @feiskyer
for 1.12 patch release

**Comment by Huang-Wei** [comment]
/unhold

Good to be merged now.

**Comment by Huang-Wei** [comment]
/hold cancel

Good to be merged now.

**Comment by feiskyer** [comment]
ping @derekwaynecarr for approval

**Comment by Huang-Wei** [comment]
@derekwaynecarr could you help to /approve? @feiskyer wants to include this in upcoming 1.12 release. Thanks!

**Pull request merged**
