### PR TITLE
Revert "add rolling update daemonset existing pod adoption integration test"

### PR DESCRIPTION
**Pull request by crimsonfaith91**
Reverts kubernetes/kubernetes#59013

### CODE REVIEW

**Comment by mikedanese** [comment]
Reason for the revert? Can you link a bug?

**Comment by crimsonfaith91** [comment]
@mikedanese This [issue](https://github.com/kubernetes/kubernetes/issues/61513) shows that the test is flaky. I am setting this PR up in case there is a need to revert the codes so that the test doesn't slow down merges.

**Comment by crimsonfaith91** [comment]
Closing as there is another [PR](https://github.com/kubernetes/kubernetes/pull/61556) to fix the flakiness.

**Comment by crimsonfaith91** [comment]
@janetkuo As sync by person and [here](https://github.com/kubernetes/kubernetes/pull/61556#issuecomment-375501667), there is a need to move the test back to end-to-end testing environment. This PR reverts the test.

**Comment by crimsonfaith91** [comment]
Is it fine for someone to LGTM this PR? Thanks!

**Review by janetkuo — APPROVED** [review]

**Pull request merged**
