### PR TITLE
fix typo: result is of that -> result of that

### PR DESCRIPTION
**Pull request by knelasevero**
**What this PR does / why we need it**:

Simple typo fix in the cluster/addons/addon-manager/kube-addons.sh file.

**Special notes for your reviewer**:

I am studying the code and trying to find something useful that I can contribute with. Found this simple typo and decided to fix it and familiarize myself with the PR process.

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by nikhita** [comment]
/ok-to-test
/lgtm

@aldarionsevero Thanks for your first contribution! :tada: 

/assign @mikedanese 
for approval

**Comment by cblecker** [comment]
/kind cleanup
/milestone v1.12

As it's a comment typo and won't impact the release, I'm okay signing off for this to merge.
cc: @tpepper

**Review by tpepper — APPROVED** [review]
/approve

**Comment by nikhita** [comment]
/retest

so many flakes :scream:

**Pull request merged**
