### PR TITLE
Report project and zone only once for GCE

### PR DESCRIPTION
**Pull request by satnam6502**
Address issue #3527 to only report the project only once and to also report the zone.

### CODE REVIEW

**Comment by roberthbailey** [comment]
Wouldn't it make more sense to only detect the project once and then plumb that through the shell scripts? This just makes it less obvious that we are constantly calling 'gcloud config list project' a zillion times in these scripts.

**Comment by satnam6502** [comment]
A very good point -- here I was hoping to just make a minimal change because when bringing up a very large cluster the output log is strewn with this repeated output.

However, I think the shall functions were written in this way because some of them can be called from a context that does not know the project.

We could try and it plumb it through somehow -- I think it would be a bit of work -- and then this work would be thrown away as we port these scripts to Go.

**Comment by satnam6502** [comment]
Also, I think `gcloud` is only called when the environment variable `PROJECT` is not set.
We could add code in `config-default.sh` (as well as the test variant) to set this variable using `gcloud` is if is not set already. That would reduce a lot how often `gcloud` is called to obtain the project (likewise for `ZONE`).

**Comment by roberthbailey** [comment]
We'll leave the larger plumbing issues for a separate refactor (#3536).

**Pull request merged**
