### PR TITLE
Automated cherry pick of #57569: Fix AWS NLB delete error

### PR DESCRIPTION
**Pull request by micahhausler**
Cherry pick of #57569 on release-1.9.

#57569: Fix AWS NLB delete error

### CODE REVIEW

**Comment by mbohlool** [comment]
is there a test?

**Comment by mbohlool** [comment]
/hold

This will not get into 1.9.8 patch release. Please contact me if you think it should be otherwise it will be included in next patch release.

**Comment by justinsb** [comment]
/lgtm

We didn't do a test for this one @mbohlool - I thought it was clear enough

**Pull request merged**
