### PR TITLE
Split controller manager options from init

### PR DESCRIPTION
**Pull request by smarterclayton**
Make defaults and flags clearly distinct from initialization code.

Similar to #19089

### CODE REVIEW

**Comment by Ap123456** [comment]
Ap123456

**Comment by smarterclayton** [comment]
ok to test

**Comment by smarterclayton** [comment]
ok to test

**Comment by smarterclayton** [comment]
ok to test

**Comment by smarterclayton** [comment]
@mikedanese can you review these - they set up the ability (in the future) to isolate and separate the command flags and their defaults from the code that runs and starts them.

**Comment by mikedanese** [comment]
@smarterclayton sorry, needs a rebase again

**Comment by smarterclayton** [comment]
ok to test

**Comment by smarterclayton** [comment]
ok to test

**Pull request merged**
