### PR TITLE
sample-controller: add usage instructions to README

### PR DESCRIPTION
**Pull request by nikhita**
Add instructions on how to run the sample controller.

Add the following sections (taken from [`apiextensions-apiserver/examples/client-go`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/examples/client-go/README.md)):

- Use Cases
- Defining Types
- Cleanup

**Release note**:

```release-note
NONE
```

/assign @sttts @munnerz

### CODE REVIEW

**Comment by nikhita** [comment]
Other examples in client-go and in apiextensions-apiserver create the resources automatically i.e. we don't have to create it explicitly using `kubectl`. 

https://github.com/kubernetes/kubernetes/blob/6f06408eea554b3f2cb76f2e2b54bb892ab8f6f7/staging/src/k8s.io/apiextensions-apiserver/examples/client-go/main.go#L81-L94

Should the sample-controller also be adapted to behave in the same manner to remain consistent?

**Comment by sttts** [comment]
> Should the sample-controller also be adapted to behave in the same manner to remain consistent?

@ncdc had a good point in his blog post https://medium.com/@andy.goldstein/an-introduction-to-extending-kubernetes-with-customresourcedefinitions-76deb675b27a that the controller should not have the authorization to modify CRDs. So it's a good practice to keep that separate.

**Comment by munnerz** [comment]
Yep I'd much rather not create the CRD from the controller itself - I've also found some users on older clusters require the use of TPRs, and despite the warnings on my part, it does largely work with TPRs too.

**Pull request merged**
