### PR TITLE
Add missed status code description in comment.

### PR DESCRIPTION
**Pull request by jfbai**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Add the missed status code descriptions in comments, help to understand the status code more easier.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

None

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

/sig api-machinery

### CODE REVIEW

**Comment by jfbai** [comment]
Ping @draveness to review, thanks a lot.

**Review by yue9944882 — APPROVED** [review]

**Comment by jfbai** [comment]
ping @liggitt to help review and approve, thanks a lot. :)

**Pull request merged**
