### PR TITLE
e2e: node remove: kubevirt device plugin

### PR DESCRIPTION
**Pull request by ffromani**
#### What type of PR is this?

/kind cleanup
/kind failing-test

#### What this PR does / why we need it:
The podresources e2e tests want to exercise the case on which a device  plugin doesn't report topology affinity. The only known device plugin  which had this requirement and didn't depend on specialized hardware was the kubevirt device plugin, which was however deprecated after we started using it.
 To unblock the state and preserve some e2e signal, we switch to the  sample device plugin, which is a stub implementation and which is managed in-tree, so we can maintain it and ensure it fits the e2e test  usecase.

The upside is that using a OS-neutral device plugin for the tests enables us to run on all the supported platform (windows!) so this could enable us to transition these tests to conformance.

#### Which issue(s) this PR fixes:
Fixes N/A

#### Special notes for your reviewer:
I'd like to propose to graduate podresources e2e tests to Conformance (NodeConformance?) so we can use them also on windows platform (xref: https://github.com/kubernetes/enhancements/pull/3863). Switching to the sample-device-plugin helps a lot here

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by ffromani** [comment]
FYI @moshe010

**Comment by ffromani** [comment]
the PR is now ready for review

**Comment by ffromani** [comment]
/retest
```

=== SKIP: vendor/k8s.io/legacy-cloud-providers/vsphere TestVolumes (0.00s)
    vsphere_test.go:943: No config found in environment
=== Failed
=== FAIL: vendor/k8s.io/kube-aggregator/pkg/apiserver TestLegacyFallbackNoCache (0.11s) 

```

**Review by endocrimes — COMMENTED** [review]
/approve

leaving the LGTM to a second reviewer (having two folks do reviews of test changes is a good practice in case someone misses a behavior diff)

**Pull request merged**
