### PR TITLE
Fix extraneous entries in iscsi path format, update README and sample json

### PR DESCRIPTION
**Pull request by anish**
Commit messages for each of the patches explain issues and fixes in detail.

### CODE REVIEW

**Comment by brendandburns** [comment]
@markturansky @eparis 

I don't know the iscsi code...

**Comment by markturansky** [comment]
@rootfs is the author.  PTAL?

**Comment by rootfs** [comment]
First commit looks good to me.

I am not convinced with the README change. The mentioning of iSCSI target is for testing purpose. Bringing additional target providers is unnecessary and hard to verify.

**Comment by anish** [comment]
@rootfs I am okay with removing examples, I did not particular like the external links as the information is quite dated at this point (IET no longer compiles without patching on newer kernels without patching), and was looking for a replacement.

**Comment by rootfs** [comment]
@anish cool, let's keep the `iscsi_util.go` change.

**Comment by anish** [comment]
Should I completely remove the examples then ? I'm mostly trying to ensure the next person does not mix up target iqn and initiator name again

**Comment by rootfs** [comment]
yes, example change is a good to me.

**Comment by anish** [comment]
@rootfs Please see if README is acceptable now. Fyi, I have more changes incoming to improve iscsi support, specifically adding iscsi transport support.

**Comment by rootfs** [comment]
@anish i thought we had an agreement not to bring other iscsi providers. The external source on iscsi target installation and configuration is useful for people to bring up iscsi for tests. This is what we use for e2e test too.

**Comment by anish** [comment]
@rootfs I've left the links as is right now, but they are out of date and have some wrong recommendations and need to be updated.

**Comment by brendandburns** [comment]
Waiting on lgtm from @rootfs

**Comment by rootfs** [comment]
please squash then LGTM

**Comment by anish** [comment]
@rootfs squashed

**Comment by rootfs** [comment]
@anish thanks 
@brendandburns LGTM

**Comment by markturansky** [comment]
Added LGTM for @brendandburns

**Comment by markturansky** [comment]
Label added, bot.

**Pull request merged**
