### PR TITLE
Add check for Git remote

### LINKED ISSUE #25807: Unfriednly error while executing ./hack/update-generated-docs.sh script
I tried to use update-generated-docs.sh script to update docs and it failed with next log:

> $ ./hack/update-generated-docs.sh 
> Go version: go version go1.6 linux/amd64
> +++ [0518 16:29:07] Building go targets for linux/amd64:
>     cmd/gendocs
>     cmd/genkubedocs
>     cmd/genman
>     cmd/genyaml
>     cmd/genbashcomp
>     cmd/mungedocs
> +++ [0518 16:29:08] Placing binaries
> output: fatal: Not a valid object name upstream/release-1.2
> ,
> ERROR: exit status 128
> `git ls-tree -r --name-only upstream/release-1.2 failed. We'll ignore this error locally, but Jenkins may pick an error. Munger uses the output of this command to determine in unversioned warning, if it should add a link to the doc in release branch.
> output: fatal: Not a valid object name upstream/release-1.2
> ,
> ERROR: exit status 128
> `git ls-tree -r --name-only upstream/release-1.2 failed. We'll ignore this error locally, but Jenkins may pick an error. Munger uses the output of this command to determine in unversioned warning, if it should add a link to the doc in release branch.
> output: fatal: Not a valid object name upstream/release-1.2
> ,
> ERROR: exit status 128
> `git ls-tree -r --name-only upstream/release-1.2 failed. We'll ignore this error locally, but Jenkins may pick an error. Munger uses the output of this command to determine in unversioned warning, if it should add a link to the doc in release branch.

It is hard to understand how can I fix this error without reading code. 

Imo, we need additional check `[[ `git remote` == *$KUBE_GIT_UPSTREAM* ]]` and print user-friendly error if not.

### PR DESCRIPTION
**Pull request by andreykurilin**
fixes #25807

### CODE REVIEW

**Comment by goltermann** [comment]
@k8s-bot ok to test

**Comment by andreykurilin** [comment]
@goltermann hi! Tests are passed. Should I do something to get it merged?

**Comment by goltermann** [comment]
You just need a code review approval from someone (they'll apply an "lgtm" label, and once that's on the PR, the submit queue will process it).  @zmerlynn @lavalamp

**Comment by zmerlynn** [comment]
The check here looks like it was wrecked by #27808. Sorry about the slow review, I've been backlogged on PRs for a while. I'm going to close this for the time being, but please feel free to reopen if you want to rework the check on the new code.

**Pull request closed without merging**
