### PR TITLE
aws: make it possible to have multiple k8s clusters in one vpc

### PR DESCRIPTION
**Pull request by manolitto**
I think it should be possible to have multiple k8s clusters in one VPC.
Example scenario:
- VPC "kubernetes-vpc" CIDR 172.20.0.0/16
- cluster "kube-frontend-1a" in availability zone "1a" with CIDR 172.20.1.0/24
- cluster "kube-frontend-1b" in availability zone "1b" with CIDR 172.20.2.0/24
- cluster "kube-frontend-1c" in availability zone "1c" with CIDR 172.20.3.0/24

Therefore there should be no filter for "KubernetesCluster" when looking for an existing vpc during setup.

### CODE REVIEW

**Comment by mbforbes** [comment]
@justinsb Could you please take a look at this?

**Comment by mbforbes** [comment]
Assigning to @erictune just so we have someone on the PR; feel free to reassign (never sure who aws changes should go to).

**Comment by justinsb** [comment]
I think it should also be possible to have multiple clusters in one AZ, and that is why I put a tag in there.  It isn't completely wired up though (yet).

I guess if we filtered on AZ _and_ on tag:KubernetesCluster it would make both me & @manolitto happy?

**Comment by justinsb** [comment]
Actually, I'm not sure what I just wrote makes sense.  I need to think about the various use cases a little more I think...  but please don't pull out that tag just yet!

**Comment by manolitto** [comment]
Another scenario that comes to my mind:

Example scenario for a company "acme" with two applications "foo" and "bar". "foo" and "bar both have separate tier clusters for front-end and back-end.

- VPC "acme-kubernetes-vpc" CIDR 172.20.0.0/16
- cluster subnet "foo-frontend-1a" in AZ "1a" with CIDR 172.20.11.0/24
- cluster subnet "foo-frontend-1b" in AZ "1b" with CIDR 172.20.12.0/24
- cluster subnet "foo-backend-1a" in AZ "1a" with CIDR 172.20.13.0/24
- cluster subnet "foo-backend-1b" in AZ "1b" with CIDR 172.20.14.0/24
- cluster subnet "bar-frontend-1a" in AZ "1a" with CIDR 172.20.21.0/24
- cluster subnet "bar-frontend-1b" in AZ "1b" with CIDR 172.20.22.0/24
- cluster subnet "bar-backend-1a" in AZ "1a" with CIDR 172.20.23.0/24
- cluster subnet "bar-backend-1b" in AZ "1b" with CIDR 172.20.24.0/24

So, what we have here is: multiple apps ("foo" and "bar"), multiple tiers ("frontend" and "backend"), multiple clusters. We have a total of eight k8s clusters.

There are multiple hierarchy levels here. What terms shall we use? One suggestion would be:
- all eight clusters together make a "kubernetes cloud": e.g. the "acme kubernetes cloud"
- clusters belonging to one application make a "kubernetes cluster ensemble": e.g. the "foo cluster ensemble" and the "bar cluster ensemble"
- clusters belonging to one tier also make a "kubernetes cluster ensemble": e.g. the "foo frontend cluster ensemble" or "bar backend cluster ensemble"

By introducing these new AWS tags we could accomplish a complex scenario like the one above:
- "KubernetesCloud" (instead of "KubernetesCluster") on VPC level
- "KubernetesCluster" on subnet level

WDYT?

**Comment by erictune** [comment]
@mbforbes I'm out this week and next.  Reassigning to @thockin  for networking expertise.

**Comment by thockin** [comment]
@justinsb

**Comment by benmccann** [comment]
just a reminder that this needs to be reviewed

**Comment by justinsb** [comment]
I just put up #9295 - the idea is that we filter everything by cluster id.  So you can have as many Kubernetes clusters as you want, all in the same AZ even, as long as you give them different names.  If they are in the same VPC, you'll have to choose non-overlapping subnets so this will always be an advanced option.

We don't yet have the concept of combining multiple kubernetes clusters together ("ubernetes"), but this should support that.

It might also be nice to let you have the same clusterid on different AZs, but as we have to set up different CIDRs anyway it doesn't seem that much of an issue.

**Comment by mbforbes** [comment]
I think this might need a rebase so Travis can find itself?

**Comment by mbforbes** [comment]
Wow, this has lasted two rounds of me being the oncall assigner!

Without @justinsb I'm generally tossing things onto @brendandburns temporarily, but @erictune mentioned @thockin as a potential reviewer, so adding him for now.

@manolitto, are you still interested in getting this in / would you mind doing a rough sanity check to see if this still fits in the way it had when you wrote it over 3 months ago?

**Comment by manolitto** [comment]
closing this PR because it is already fully merged by commit 034412aff1cb932f0e10267fd052655cd2456d84

**Pull request closed without merging**
