### PR TITLE
Remove deprecated centos/local support

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I4a451ec0125c05e66202daf781a4e5a1d895efb4

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
We deprecated the providers back in k8s 1.8 release via commit 89bf771e51c0a6fa07867756766b371dc66f1d2a

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kube-up.sh no longer supports "centos" and "local" providers
```

### CODE REVIEW

**Review by zouyee — APPROVED** [review]

**Comment by liggitt** [comment]
/approve

In the release note, note which release they were deprecated in

**Comment by chendave** [comment]
Could you pls let me know what's the right way to run e2e testcase with local cluster? The document below seems outdated 
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md.

**Comment by chendave** [comment]
ping @dims

**Pull request merged**
