### PR TITLE
Revert "certs: only append locally discovered addresses when we got none from the cloudprovider"

### PR DESCRIPTION
**Pull request by liggitt**
This reverts commit 7354bbe5ac838af560ca5dbabcd7d05e28ef8f59.

https://github.com/kubernetes/kubernetes/pull/61869 caused a mismatch between the requested CSR and the addresses in node status.

Instead of computing addresses in two places, the cert manager should derive its CSR request from the addresses in node status. This would enable the kubelet to react to address changes, as well as be driven by an external cloud provider.

/cc @mikedanese

```release-note
NONE
```

### CODE REVIEW

**Comment by mikedanese** [comment]
cc @awly I suspect this might break GKE alpha clusters.

**Comment by liggitt** [comment]
/assign @tallclair 
for approval

> cc @awly I suspect this might break GKE alpha clusters.

see follow-up in https://github.com/kubernetes/kubernetes/pull/65594 that I think does everything we want:
* makes the cloud provider authoritative on addresses
* makes the kubelet wait for those addresses before getting a certificate
* makes the kubelet react to changes in those addresses by getting a new certificate

**Pull request merged**
