### PR TITLE
Update cluster autoscaler to 1.12.0-beta.1

### PR DESCRIPTION
**Pull request by losipiuk**
Update Cluster Autoscaler to version 1.12.0-beta.1 which is compatible with k8s 1.12.
Note: this is pre release version. Update to the final version of CA image will be done a week before k8s release deadline.

Version skip from 1.3.x to 1.12.x is to synchronize version numbering between Cluster Autoscaler and k8s core.
```release-note
NONE
```

### CODE REVIEW

**Comment by losipiuk** [comment]
@dougm Could you please approve this one for milestone. I create the PR on Sept 3, but it was on hold waiting for Cluster Autoscaler image for k8s 1.12 to be built and uploaded into gcr.

**Review by dougm — COMMENTED** [review]
/milestone v1.12

**Pull request merged**
