### PR TITLE
combine two logics avoid for range the same thing

### PR DESCRIPTION
**Pull request by LexCC**
**What type of PR is this?**
> /kind cleanup

**What this PR does / why we need it**:
combine two logics that can avoid ``for range endpointChains`` again
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
LGTM
/ok-to-test
/priority backlog

**Comment by JieJhih** [comment]
@neolit123 Is this change going to affect the ``TestPreemptionRaces`` function?
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/77298/pull-kubernetes-integration/1123588040720125953/

**Comment by neolit123** [comment]
@JieJhih could be a test flake.
try `/retest`

/retest

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
