### PR TITLE
refine chinese translation for kubectl

### PR DESCRIPTION
**Pull request by ziyi-yan**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
refine Chinese help message in `kubectl help` to be easier to understand

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
 I'm not sure whether the help message changes are user-facing.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by ziyi-yan** [comment]
I signed it

**Comment by pigletfly** [comment]
@ziyi-yan there is a conflict file

**Comment by ziyi-yan** [comment]
I have rebased this pr on master. PTAL @pigletfly

**Pull request closed without merging**
