### PR TITLE
Tolerate when LICENSE file is missing in artifacts

### PR DESCRIPTION
**Pull request by dims**
Temporary fix for failing jobs!

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
failing jobs info is in https://github.com/kubernetes/kubernetes/issues/85196

**Comment by liggitt** [comment]
I'd rather revert https://github.com/kubernetes/kubernetes/pull/76586, we need to understand why we're missing LICENSE in our artifacts

**Comment by dims** [comment]
`LICENSES` was the old name and it is still there in the tar.gz.

**Pull request closed without merging**
