### PR TITLE
replace proxy with kubelet at kubeadm v1beta1 docs

### PR DESCRIPTION
**Pull request by odacremolbap**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Typo at kubeadm docs

**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note
NONE
```

### CODE REVIEW

**Comment by yagonobre** [comment]
Thanks @odacremolbap, but you need to sign in the CLA. Also edit the release note to `NONE`

**Review by rosti — APPROVED** [review]
Well spotted! Thank you @odacremolbap !
/lgtm

**Comment by rosti** [comment]
/assign @fabriziopandini 
For approval.

**Review by fabriziopandini — APPROVED** [review]
@odacremolbap good catch!
Happy to see your first time contribution!
/approve
/lgtm

**Pull request merged**
