### PR TITLE
[WIP] Move ENV for jobs from e2e.sh to YAML

### PR DESCRIPTION
**Pull request by ikehz**
Diffbased off of #20996.

Move almost ENV configs from `e2e.sh` to YAML files in `job-configs`.

cc @kubernetes/goog-testing @kubernetes/sig-testing

### CODE REVIEW

**Comment by ixdy** [comment]
What about the stuff on L178-190 of e2e.sh?

**Comment by ixdy** [comment]
Also, the whole "export" section at the bottom, including some which have defaults set...

**Comment by ixdy** [comment]
I guess I kinda feel like this is still missing the actual benefit of moving these variables; we still have a large chunk of inconsistent values, just now in a different file.

I'd like to see us move towards something more templated, where most jobs have certain defaults (e.g., `E2E_UP=true`, `E2E_TEST=true`, `E2E_DOWN=true`, `GINKGO_PARALLEL=true`) and then individual jobs can override as necessary.

(Bonus points where you use properties already defined in the config, e.g. `suffix`, to define env vars.)

It's infeasible to do all of that in one PR, but I'm not sure this current approach leads us in a more maintainable direction.

**Comment by ihmccreery** [comment]
@ixdy Ack; I will attempt a refactor of `e2e.sh` before doing this and see if things fall out better there.

**Comment by ihmccreery** [comment]
Closing in favor of #21122.

**Pull request closed without merging**
