### PR TITLE
[release-1.19] Backport SIG Node approvers to 1.19

### PR DESCRIPTION
**Pull request by ehashman**
#### What type of PR is this?

/kind cleanup
/priority important-longterm

#### What this PR does / why we need it:

Backports SIG Node approvers to 1.19 so our regular approvers can approve backport PRs.

Current list: 

https://github.com/kubernetes/kubernetes/blob/e6b4fa381152d66ebace4dfd837add5275fd8e1e/OWNERS_ALIASES#L245-L252

#### Which issue(s) this PR fixes:

N/A

#### Special notes for your reviewer:

https://kubernetes.slack.com/archives/C0BP8PW9G/p1619629576301100?thread_ts=1619629009.298200&cid=C0BP8PW9G

/cc @liggitt @mrunalp @klueska @sjenning 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
verified this matches `sig-node-approvers` in `master`

**Comment by ehashman** [comment]
/assign @hasheddan 
for cherry-pick

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
