### PR TITLE
fix typo in know-flags

### PR DESCRIPTION
**Pull request by xilabao**
ref to https://github.com/kubernetes/kubernetes/pull/41417

### CODE REVIEW

**Comment by xilabao** [comment]
@derekwaynecarr

**Comment by brendandburns** [comment]
/lgtm

/release-note-none

LGTM + release-note-none from the bulk LGTM tool

**Comment by xilabao** [comment]
@k8s-bot non-cri e2e test this

**Comment by xilabao** [comment]
@k8s-bot non-cri e2e test this

**Comment by derekwaynecarr** [comment]
@k8s-bot non-cri e2e test this

**Comment by derekwaynecarr** [comment]
this is a bug fix for our verification scripts, and should be in 1.6 milestone.

**Review by derekwaynecarr — APPROVED** [review]
lgtm too

**Pull request merged**
