### PR TITLE
Automated cherry pick of #79370: Migrate TaintManager to use watch for listing pods instead of

### PR DESCRIPTION
**Pull request by jfbai**
Cherry pick of #79370 on release-1.14.

#79370: Migrate TaintManager to use watch for listing pods instead of

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by jfbai** [comment]
/sig scalability

/assign @wojtek-t
/assign @k82cn
/assign @mborsz

Backport to v1.14. 

It would be very big improvement in a inflight v1.14 cluster.

**Comment by k82cn** [comment]
Do we cherry pick performance enhancement PR? IMO, we only cherry pick functional issue :)

**Comment by jfbai** [comment]
> Do we cherry pick performance enhancement PR? IMO, we only cherry pick functional issue :)

@k82cn IC, thanks a lot. :)

BTW, do we have any backport policy documented? I'd like to learn.

**Comment by tpepper** [comment]
/kind feature
/priority important-soon
/release-note-note
as per parent PR.

**Comment by tpepper** [comment]
> BTW, do we have any backport policy documented? I'd like to learn.

See here: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#cherry-pick-review

**Comment by tpepper** [comment]
While this is a a feature, SIG Scalability is doing extra work (see https://kubernetes.slack.com/archives/CJH2GBF7Y/p1569417566142500) to prove this is worthy of being an exception.

**Comment by tpepper** [comment]
/hold
pending SIG Scalability's rest results and subsequent discussion.

**Comment by wojtek-t** [comment]
xref https://github.com/kubernetes/kubernetes/pull/83666

not sure which PR we want to proceed with...
@tpepper ^

**Comment by jfbai** [comment]
Closed, since duplicated with #83666 which provides detailed test result.

**Pull request closed without merging**
