### PR TITLE
Remove unnecessary nil check for cloud

### PR DESCRIPTION
**Pull request by hello2mao**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Remove unnecessary nil check for cloud since we already check it at the very beginning and it should be fail-fast when cloud is nil.
Previous check is here:
```golang
func Run(c *cloudcontrollerconfig.CompletedConfig, stopCh <-chan struct{}) error {
        ...
	cloud, err := cloudprovider.InitCloudProvider(c.ComponentConfig.KubeCloudShared.CloudProvider.Name, c.ComponentConfig.KubeCloudShared.CloudProvider.CloudConfigFile)
	if err != nil {
		klog.Fatalf("Cloud provider could not be initialized: %v", err)
	}
	if cloud == nil {
		klog.Fatalf("cloud provider is nil")
	}

        ...
	run := func(ctx context.Context) {
		if err := startControllers(c, ctx.Done(), cloud, newControllerInitializers()); err != nil {
			klog.Fatalf("error running controllers: %v", err)
		}
	}
        ...
}

```

```release-note
None
```

### CODE REVIEW

**Comment by andrewsykim** [comment]
/approve
/lgtm

thank you @hello2mao

**Comment by hello2mao** [comment]
@andrewsykim hi，need your ok-to-test before merge. Thanks.

**Comment by andrewsykim** [comment]
/ok-to-test 

thanks

**Pull request merged**
