### PR TITLE
minor update

### PR DESCRIPTION
**Pull request by prasadkatti**
Added a missing period.

```release-note
NONE
```

### CODE REVIEW

**Comment by prasadkatti** [comment]
This is a minor fix to the docs. It is just adding a missing period. There are no API changes being proposed in this PR.

**Comment by liggitt** [comment]
thanks for the PR. can you fix this in all three places:
* staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/types.go
* staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/types.go
* staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/types.go

you'll also need to update generated files with `make update` to propagate the doc change everywhere it needs to go

**Comment by prasadkatti** [comment]
thanks @liggitt, i have updated the 2 other files and updated the generated files

**Comment by prasadkatti** [comment]
I am not sure that the test failure is related to the changes in the PR.

**Pull request merged**
