### PR TITLE
[WIP] fake dynamic client: support *List kinds

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: Andrew Sy Kim <kim.andrewsy@gmail.com

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Today the dynamic fake client is not aware of *List kinds, so List calls return `UnstructuredList` objects without TypeMeta (see https://github.com/kubernetes/kubernetes/pull/95117 for more details). This patch updates client-go's fake object tracker to store a map of GVR to list GVKs. In this way, the list GVK can be set for UnstructuredList objects.  

**Which issue(s) this PR fixes**:
Based on https://github.com/kubernetes/kubernetes/pull/95117#discussion_r512894153 

**Special notes for your reviewer**:
The heuristic for determining the GVR for a list GVK is best guess and is not deterministic. Could use some input on whether this is safe to do. 

**Does this PR introduce a user-facing change?**:

```release-note
fake dynamic client now preserves TypeMeta in UnstructuredList when listing resources.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by deads2k** [comment]
/assign

I'm looking at this.  I think we want to keep it out a layer, but it's proving a little resistant to change.

**Comment by andrewsykim** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/pull/96020

/close

**Pull request closed without merging**
