### PR TITLE
Remove unused aggregator ca key

### PR DESCRIPTION
**Pull request by wenjiaswe**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
In cluster/gce/gci/configure-healper.sh, AGGREGATOR_CA_KEY is written but not needed. Remove unnecessary storage of the key.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awly** [comment]
/lgtm
The fewer credentials passed around the better!
Although I'm not sure where this aggregator CA is used.

**Comment by wenjiaswe** [comment]
@awly it was introduce in https://github.com/kubernetes/kubernetes/pull/47606 to "a proxy client certificate for the aggregated API servers to trust in order to effectively proxy authentication", "Without it the customer either has to set them up themselves or re-use the master CA which is a security vulnerability.Currently this creates everything on GCE."

**Pull request merged**
