### PR TITLE
kubelet/container: Refactor runtime cache.

### PR DESCRIPTION
**Pull request by yifan-gu**
Rmove unnecessary caching loop. Replace with smaller cache time.

@vmarmol @dchen1107 @yujuhong 

I read the kubelet log, the original `startUpdatingCache()` is creating 20 `GetPods` operations within 2s, and most of them are unnecessary.

### CODE REVIEW

**Comment by mbforbes** [comment]
Assigning to @yujuhong; feel free to pass around, of course.

**Comment by yujuhong** [comment]
FYI, I have a PR under review to fix bugs in the runtime cache (#7749).

I am in favor of removing the updating thread in general. It is a performance optimization, but I have not yet seen concrete proof that we need it (and what update interval we should use). It'd be nice to have a performance comparison though. @vmarmol, what do you think (since you suggested the async update originally in #4592)?

**Comment by vmarmol** [comment]
The reason this exists is that we were observing high latency (seconds) of Docker operations when we were doing a lot of creations. Having the async cache update meant that all read operations returned immediately and we only suffered the cache miss the first time. If we use a typical cache we suffer the cache miss every time the information ages out. Outside of potentially more resource usage, is there a concern with the many calls to GetPods()?

**Comment by yifan-gu** [comment]
@vmarmol OK, thanks for explanation. I think then that will depend on the frequency and the pattern of the requests. I think the async will benefits only when the requests are constantly frequent. I don't think we have that pattern now, do we? I agree with @yujuhong we need more concrete performance bench or examples to verify this.

**Comment by yujuhong** [comment]
I can see that the async updates may lower the average cache miss penalty. The problem is that I don't have a good grasp on the overall performance impact. The resource usage could be a factor too if the node is resource constrained, and the frequency of aysnc updates is also debatable.

Since we don't have any data to support removing the async update, I suggest we leave it as is until proved otherwise :)

**Comment by vmarmol** [comment]
+1 to leaving alone a until we see an issue :)

I agree about the performance metrics though. We introduced this trying to schedule a bunch (50-100) pods from an RC. These came from different updates and it led us to call GetPods() a ton and this had very high latency. This reduced the latency to start these pods by over 60%. See the PR that introduced it #4592 and the issue that it targetted #4119.

**Comment by yifan-gu** [comment]
@vmarmol @yujuhong Thank you for finding the issues! +1 for leaving it. I will try to run some experiments later to get some data :)

**Comment by yujuhong** [comment]
@vmarmol, I agreed that the cache itself helps relieve the load, but I was uncertain about the effect of the async updating thread. More benchmarking would be good. FYI, I added some general description of the runtime cache, and some very basic unit tests in my PR (#7749).

**Comment by yifan-gu** [comment]
@yujuhong I am not sure about the async loop as well. Seems that in the old issue, the pods are created in a burst. Which may or may not take advantage of the async loop based on how long actually the burst period is.

**Pull request closed without merging**
