### PR TITLE
Kevogich patch 1

### PR DESCRIPTION
**Pull request by Kevogich**
unused comments removed

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
/assign @thockin
**Release note**:

```release-note
release-note-none

ok-to-merge
```

### CODE REVIEW

**Comment by Kevogich** [comment]
cla comment.

**Comment by nikhita** [comment]
@Kevogich Thanks for sending this PR! However, this is a dupe of https://github.com/kubernetes/kubernetes/pull/53758.

**Pull request closed without merging**
