### PR TITLE
Use gcloud for gce_runner

### PR DESCRIPTION
**Pull request by dims**
While experimenting with completely eliminating all cloud provider specific libraries from kubernetes in [122966](https://github.com/kubernetes/kubernetes/pull/122966) It became clear that `pull-kubernetes-node-e2e-containerd` would be hard to get working when we drop GCP specific libraries from vendor/ directory since it used the following two libraries:
-  "google.golang.org/api/compute/v1"
- "google.golang.org/api/option"

Given that this job triggers [hack/make-rules/test-e2e-node.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/make-rules/test-e2e-node.sh) which uses `gcloud` extensively, it made sense to switch `test/e2e_node/remote/gce/gce_runner.go` to use `gcloud` calls instead of using the above libraries so we could keep the `gce` runner for node e2e tests in the tree itself for now.

NOTE: we moved the node e2e runner for `aws` [here](https://github.com/kubernetes-sigs/provider-aws-test-infra/tree/main/test/e2e_node/remote/aws) but that required a bunch of gymnastics over time to get it all working, we can do that, but in small steps. The first step here is to drop the libraries and use the CLI

Landing this quickly and making sure we don't break anyone will make it easier to drop all the GCP library usage sooner!

#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
I'm not very familiar with this code, @SergeyKanzhelev or @bobbypage will know better

**Comment by kannon92** [comment]
> /test pull-kubernetes-node-crio-cgrpv2-e2e

Just want to trigger a crio job. We use these jobs a lot as periodics but they are not covered that extensively in presubmits.

**Comment by dims** [comment]
@kannon92 of course, please run which ever presubmits are of interest to you here. if we can catch them fail here it is easier for me to go fix it!

**Comment by kannon92** [comment]
@dims I don't think we change that code based on type of job. I think really there are crio/containerd jobs so I think that given the crio jobs passing I think this is fine from crio side. And containerd has a required presubmit.

@haircommander @saschagrunert wdyt? Any other tests we should try to make sure this works from crio side?

**Comment by haircommander** [comment]
yeah I'm happy to move forward with this and then revert if something breaks

**Comment by dims** [comment]
@haircommander I'd like a whack at fixing things before a revert :) Let's try as many presubmits as possible before we land this as well (if we do have presubmits!)

(i pored over a bunch of things for the last 3-4 days and am reasonably certain that the CLI can be an effective replacement)

**Comment by kannon92** [comment]
> @haircommander I'd like a whack at fixing things before a revert :) Let's try as many presubmits as possible before we land this as well (if we do have presubmits!)
> 
> (i pored over a bunch of things for the last 3-4 days and am reasonably certain that the CLI can be an effective replacement)

I don't know if we have 1on1 on presubmits with all periodics in node_e2e so I think when we merge we still want to monitor test grid.

**Comment by dims** [comment]
i can only see one presubmit that i'll have to fix ... https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/123006/pull-kubernetes-node-arm64-e2e-containerd-ec2/1752099585326583808/artifacts/build-log.txt

**Comment by saschagrunert** [comment]
CRI-O jobs look sane for now, but I'm not even sure if we use those code paths in the tests.

**Comment by dims** [comment]
Duh! 

> i can only see one presubmit that i'll have to fix ... https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/123006/pull-kubernetes-node-arm64-e2e-containerd-ec2/1752099585326583808/artifacts/build-log.txt

This job uses the ec2 runner as it runs on AWS/EC2 LOL, so this does not go through the code in this PR and instead uses:
https://github.com/kubernetes-sigs/provider-aws-test-infra/tree/main/test/e2e_node/remote/aws

Also, i've started the same set of presubmits in another PR https://github.com/kubernetes/kubernetes/pull/123035 if the failures match those that we see here, we are then ready to merge this PR!

**Comment by kannon92** [comment]
/lgtm
Since both @haircommander and @saschagrunert also thing this looks good, I think we can go ahead with merge.

**Comment by dims** [comment]
/skip

thanks @kannon92

**Pull request merged**
