### PR TITLE
Fix staticcheck failures for vendor/k8s.io/apiserver/pkg/storage

### PR DESCRIPTION
**Pull request by njuptlzf**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Part of #92402
vendor/k8s.io/apiserver/pkg/storage/selection_predicate_test.go:33:6: type IgnoredList is unused (U1000)
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yliaog** [comment]
better to add test code to use the IgnoredList than removing it

**Comment by njuptlzf** [comment]
> better to add test code to use the IgnoredList than removing it

Sounds great, let me see

**Comment by njuptlzf** [comment]
hi,@yliaog
I checked selection_predicate.go, and I think there is no need to implement test code for `IgnoredList`, because there is no way to handle **list runtime.Object** in selection_predicate.go.

WDYT :)

**Comment by BenTheElder** [comment]
/approve
for hack/

thanks for working on these!
/test pull-kubernetes-node-e2e-containerd

**Comment by liggitt** [comment]
/approve

needs to be squashed to a single commit before merge

**Comment by njuptlzf** [comment]
/remove-sig  area/cloudprovider area/code-generation area/dependency area/kubectl area/test sig/cli sig/cloud-provider sig/cluster-lifecycle sig/instrumentation sig/node sig/storage sig/testing

**Comment by njuptlzf** [comment]
/remove area/cloudprovider area/code-generation area/dependency area/kubectl area/test sig/cli sig/cloud-provider sig/cluster-lifecycle sig/instrumentation sig/node sig/storage sig/testing

**Comment by njuptlzf** [comment]
Hi, @fedebongio , I know that you are proficient in tag management. Here, can you help me remove the tags that were added by mistake? thank.
image

**Comment by BenTheElder** [comment]
the trick is to do:
/remove-sig cli cloud-provder cluster-lifecycle instrumentation node storage testing
/remove-area cloudprovider code-generation dependency kubectl test
(don't mix SIG and area, different commands)
but I should have displayed this before removing them manually.
/priority important-longterm

**Comment by BenTheElder** [comment]
seems the bot missed handling the size change as well

**Comment by BenTheElder** [comment]
it was squashed to a single commit, and is passing tests https://github.com/kubernetes/kubernetes/pull/100771#issuecomment-866875507
/lgtm

**Comment by njuptlzf** [comment]
Thank you @BenTheElder, I think I will also be able to help others in the correct triage. :- )

**Pull request merged**
