### PR TITLE
Add labels to containers in pod according to annotations

### LINKED ISSUE #26275: Need a way for user to specify container labels
I need a way for a client creating a pod to put something in the pod that specifies some container labels.  Please note that I am **_not_** talking about making a pod's containers inherit all the pod's labels.  Rather, I am talking about a new bit of specification for labels that are intended just for the containers.

For my use case, it suffices to give the client a way to specify one set of labels, and that set gets put on every container of the pod.  I could also use a more flexible interface that gives independent control over the labels going on to each container.

To be concrete, the less expressive interface would be an additional pod spec field whose name is something like `containerLabels` and whose value is a map from label name to label value.  The more expressive interface would be an additional container spec field like that, but named something simpler like `labels`.

For prototyping the less expressive interface, we might start with supporting annotations of the form `alpha.kubernetes.io/containers-labels/XXX=YYY`, each meaning to put the label `XXX=YYY` on each container of the pod.

The more expressive interface could be prototyped with something like annotations of the form `alpha.kubernetes.io/container-labels/ZZZ/XXX=YYY`, each meaning that the label `XXX=YYY` is to be put on the pod's container named `ZZZ`.

### PR DESCRIPTION
**Pull request by phanhuyn**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
/sig node
This PR implements adding container labels via pod's annotation, as suggested in #26275

**Which issue(s) this PR fixes**:
Fixes #26275

**Special notes for your reviewer**:
This is my first PR, sorry in advance if I missed some steps. For this PR, I've verified with `make test WHAT=./pkg/kubelet`. The updated kubelet has been built and tested in an actual k8s cluster.

**Does this PR introduce a user-facing change?**:

```release-note
Implement setting containers' label by pod's annotation. 
```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
@phanhuy1502 welcome to the project and thanks for your contribution :)

@dims I saw you were involved in the original convo on the issue. I'm wondering, is this an open enough question that it should go through the [KEP](https://github.com/kubernetes/enhancements/tree/master/keps) process?

**Comment by dashpole** [comment]
This warrants at least a discussion at sig-node.

**Comment by phanhuy1502** [comment]
@dims @mattjmcnaughton thanks for the comment. I've read through the KEP & I've joined the sig-node slack group. How shall I proceed on this MR? (starting a discussion in the slack group/drafting a KEP?)

**Comment by dashpole** [comment]
The referenced issue was originally closed in favor of lifecycle hooks, but then reopened.  Can you describe your use-case in the issue?  Depending on your use-case a KEP may or may not be required.  We have historically been against opaque APIs, such as plumbing labels or annotations to plugins or runtimes, as that makes it harder to guarantee portability.

**Comment by phanhuy1502** [comment]
@dashpole thanks for your reply

> The referenced issue was originally closed in favor of lifecycle hooks, but then reopened. Can you describe your use-case in the issue? 

The use-case is I want a way to set the labels for the individual containers under the pod, via the Pod spec. As far as I know, this is currently not supported. I'm not aware of how it can be achieved by using [lifecycle hooks](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/).

In #26275, there are mentions of #28789, which I think is the proposal for CRI. CRI does allow setting labels for the runtime container, but the Kubernetes API doesn't support that. Say I want to create a pod with 2 containers, and set different labels for these 2 containers; I can't do that by the Kubernetes API. 

> Depending on your use-case a KEP may or may not be required. 

The general use case is to set per-container label. I think that might have different applications. For my case, I want to attach the label to the container so Cadvisor can have more information when getting the metrics.

> We have historically been against opaque APIs, such as plumbing labels or annotations to plugins or runtimes, as that makes it harder to guarantee portability.

I see. If we want to avoid opaque APIs and still needs to support this feature, does it mean introducing new fields in the Pod Spec / updating the Kubernetes API?

**Comment by dashpole** [comment]
> The general use case is to set per-container label. I think that might have different applications. For my case, I want to attach the label to the container so Cadvisor can have more information when getting the metrics.

Can you use the kube_pod_labels metric from kube-state-metrics and join with metrics coming from cAdvisor?  That is generally the preferred mechanism to add additional metadata to metrics.

**Comment by phanhuy1502** [comment]
> Can you use the kube_pod_labels metric from kube-state-metrics and join with metrics coming from cAdvisor? That is generally the preferred mechanism to add additional metadata to metrics.

This method would add all the pod labels to the cadvisor metrics right? I'd like more fine-grained control over what labels should be added to the metrics, and to which specific container under the pod.

**Comment by phanhuy1502** [comment]
@dashpole I opened the MR since I saw the open issue https://github.com/kubernetes/kubernetes/issues/26275 with some users wanting the feature. If the feature goes against the general design guideline, should I close the MR? Or if you feel like some modifications are needed, I can see if I can work on that :)

**Comment by dashpole** [comment]
> This method would add all the pod labels to the cadvisor metrics right? I'd like more fine-grained control over what labels should be added to the metrics, and to which specific container under the pod.

This is a query-time join (using `group_left` in promql), so you have control over which labels appear in your graph.

> If the feature goes against the general design guideline, should I close the MR? Or if you feel like some modifications are needed, I can see if I can work on that :)

I'm not saying the change is necessarily bad, but that we consider it to be a _significant_ change.  When we considered it as an option in the past for other use-cases, we ended up choosing more targeted approaches.  There are a few steps that would have to happen before I can accept the PR.  This is a significant enough change that it at least discussion at Sig-Node, and probably a KEP (Kubernetes Enhancements Proposal).  This is so that we can ensure the proposed changes are justified by the use-cases, and that it is the best way to satisfy those use-cases.  In your case, there appears to be a reasonably simple alternative, which is to join the information you want with the metric post-collection.  I've personally done this join before, so i'm pretty confident we can meet your use-case without needing this change.

**Pull request closed without merging**
