### PR TITLE
Updated latest Kubernetes version to variable

### PR DESCRIPTION
**Pull request by idvoretskyi**
Added method to set a Kubernetes variable to the latest actual version.

Updated command with added variable.

### CODE REVIEW

**Comment by idvoretskyi** [comment]
@smarterclayton, how to solve a build issue?
Docs seemed to be correct, but error shows us that in a current state they're outdated.

**Comment by smarterclayton** [comment]
Typically you need to rebase and run hack/update-generated-docs.sh again

**Comment by idvoretskyi** [comment]
@smarterclayton 
> run hack/update-generated-docs.sh

Where should I run it? I thought that Travis CI has to run this script.

**Comment by fgrzadkowski** [comment]
@idvoretskyi Run in your local copy of repo. Travis will only check you have run it :)

This PR looks good. My only concern is that once we release `v1.2` this instruction will stop working (hyperkube at HEAD will start etcd and proxy, so running it manually will cause crash loop for of the copies). That might be OK as we will mark old docs out-dated anyway.

**Comment by eparis** [comment]
Docs have moved to github.com/kubernetes/kubernetes.github.io/   I apologize for the inconvenience but would ask that you make the updates there (where you won't have so much trouble!!)

**Comment by idvoretskyi** [comment]
@eparis thank you.

**Pull request closed without merging**
