### PR TITLE
add spec.host as a synonym for spec.nodeName in v1

### PR DESCRIPTION
**Pull request by brendandburns**
This fixes a breaking change between different v1 api clients (0.19.3 to head)

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM

**Comment by bgrant0607** [comment]
cc @nikhiljindal @caesarxuchao

**Comment by bgrant0607** [comment]
Addresses incompatible change made in #10076, which was made after v1 was enabled by default in #9269

**Comment by nikhiljindal** [comment]
ah LGTM, thanks!
Sorry for not catching this earlier.

**Comment by lavalamp** [comment]
LGTM

**Comment by bgrant0607** [comment]
cc @rjnagal for merge

**Comment by roberthbailey** [comment]
Thanks @brendandburns!

**Comment by caesarxuchao** [comment]
Thank you @brendanburns !

So the mistake is that I failed to catch #10076 before sending #9269.

**Comment by rjnagal** [comment]
waiting to merge: shippable is slow

**Comment by zmerlynn** [comment]
I'm prepping the release branch anyways - we've done some amount of internal validation. If there's a unit test failure or something else, we can push a minor change, but integration tests seem to be fine.

**Comment by zmerlynn** [comment]
(To be clear, this passes on my own testing.)

**Comment by rjnagal** [comment]
shippable failure:

 ./hack/verify-gofmt.sh
!!! 'gofmt -s' needs to be run on the following files:
./pkg/api/v1/conversion.go

**Comment by zmerlynn** [comment]
Yeah. It's a shame `make release` doesn't even catch that. Sigh.

**Comment by zmerlynn** [comment]
Merging so I can get #11097 in (so master can look like v0.21.2 sometime tonight).

**Comment by zmerlynn** [comment]
(Shippable just went green, finally.)

**Pull request merged**
