### PR TITLE
Automated cherry pick of #41658 upstream release 1.5

### PR DESCRIPTION
**Pull request by janetkuo**
Automated cherry pick of #41658 upstream release 1.5

@soltysh @mwielgus

### CODE REVIEW

**Comment by soltysh** [comment]
Adding cherry-pick approved label to satisfy bot, since the original PR has one.

**Comment by mwielgus** [comment]
@soltysh 
I'm ok with this PR but in general you should rather not merge anything to a patch release without lgtm/approval from the patch release manager.

**Comment by soltysh** [comment]
@mwielgus sorry, but looking at the original PR it already had approval from @saad-ali

**Comment by mwielgus** [comment]
Anyway - thank you and @janetkuo for the fix.

**Pull request merged**
