### PR TITLE
Update etcd client to v3.4.13

### LINKED ISSUE #12144: Upgrading from v3.4.9 to v3.4.10 requires manual action
After upgrading existing cluster from version `v3.4.9` to `v.3.4.10`, etcd fails to start with following error:
```
{"level":"fatal","ts":"2020-07-17T07:11:27.596Z","caller":"etcdmain/etcd.go:271","msg":"discovery failed","error":"cannot access data directory: directory \"/theory-controllers-1.etcd\",\"drwxr-xr-x\" exist without desired file permission \
"-rwx------\".","stacktrace":"go.etcd.io/etcd/etcdmain.startEtcdOrProxyV2\n\t/tmp/etcd-release-3.4.10/etcd/release/etcd/etcdmain/etcd.go:271\ngo.etcd.io/etcd/etcdmain.Main\n\t/tmp/etcd-release-3.4.10/etcd/release/etcd/etcdmain/main.go:46\nm
ain.main\n\t/tmp/etcd-release-3.4.10/etcd/release/etcd/main.go:28\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}
```

To get it to work, manual `sudo chmod 0700` execution is required on all members user data directories to get etcd running again. This seems to be a new requirement (or old one, which was not enforced) and it is not mentioned in the changelog nor in the upgrade guide, which was unexpected.

Perhaps this should be documented somewhere?

### PR DESCRIPTION
**Pull request by jingyih**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
We are bumping etcd client version to v3.4.13 in this PR. Then we can bump etcd server (used in testing and manifests) to the same version to pick up https://github.com/etcd-io/etcd/pull/12242 which fixes https://github.com/etcd-io/etcd/issues/12144 and https://github.com/etcd-io/etcd/issues/12148.

Related:
https://github.com/kubernetes/kubernetes/issues/94141
https://github.com/kubernetes/kubernetes/pull/94102
https://github.com/kubernetes/kubeadm/issues/2256

**Does this PR introduce a user-facing change?**:
```release-note
Update etcd client side to v3.4.13
```

/sig api-machinery
/area etcd

cc @kubernetes/release-engineering @neolit123 @justaugustus @saschagrunert @BenTheElder @wojtek-t @wenjiaswe

### CODE REVIEW

**Comment by neolit123** [comment]
LGTM, thanks @jingyih

**Comment by jingyih** [comment]
Can we still get this in Kubernetes v1.19?

**Comment by neolit123** [comment]
> Can we still get this in Kubernetes v1.19?

i don't think we can because 1.19 is releasing later today and usually new etcd needs to be tested in CI for a while.

**Comment by hasheddan** [comment]
@jingyih @neolit123 v1.19 is now live

**Comment by jingyih** [comment]
Got it. Thanks:)

/milestone v1.20

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by wojtek-t** [comment]
Milestone will be applied by release team later according to staged merge proposal.

/approve

**Comment by liggitt** [comment]
does this actually matter on the client side? the permission check being fixed is run by the server, right?

**Comment by jingyih** [comment]
> does this actually matter on the client side? the permission check being fixed is run by the server, right?

You are correct. The fix is on server side. But I think it is a good idea to keep the client and server versions match.

**Comment by liggitt** [comment]
sure, just wanting to make sure this is characterized correctly

**Comment by jingyih** [comment]
> sure, just wanting to make sure this is characterized correctly

Oh I see. Thanks! Let me correct the PR description.

**Pull request merged**
