### PR TITLE
Apparently conformance tests have to run serially

### PR DESCRIPTION
**Pull request by dims**
There are 10+ conformance tests marked [Serial], So we can't run things
in parallel by default.

Change-Id: I58afbb356899fb38caf4f9f6704bfb47f745b338

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
Context : please see the failures in https://testgrid.k8s.io/sig-testing-kind#conformance-image,%20master%20(dev)

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Comment by spiffxp** [comment]
/lgtm
It would be nice to run in parallel what we could, and in serial what we can't.  I don't think kubetest supports that mode of operation today though.

**Comment by BenTheElder** [comment]
> It would be nice to run in parallel what we could, and in serial what we can't. I don't think kubetest supports that mode of operation today though.

When I get back to kubetest2 at some point I want to build a mode like this.

**Pull request merged**
