### PR TITLE
.*: update vendor dir and cleanup

### LINKED ISSUE #116946: pull-kubernetes-dependencies is failing
### Which jobs are failing?

pull-kubernetes-dependencies

### Which tests are failing?

verify.Vendor

### Since when has it been failing?

27 March 2023, 15:28 IST (9:58 UTC)

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-dependencies

### Reason for failure (if possible)

```
Your vendored results are different:
diff -Naupr -x 'AUTHORS*' -x 'CONTRIBUTORS*' vendor/k8s.io/api/go.mod /home/prow/go/src/k8s.io/kubernetes/_tmp/kube-vendor.3Sq7Hh/kubernetes/vendor/k8s.io/api/go.mod
--- vendor/k8s.io/api/go.mod	2023-03-27 10:01:13.097931396 +0000
+++ /home/prow/go/src/k8s.io/kubernetes/_tmp/kube-vendor.3Sq7Hh/kubernetes/vendor/k8s.io/api/go.mod	2023-03-27 10:04:41.397038952 +0000
@@ -21,7 +21,7 @@ require (
 	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
 	github.com/modern-go/reflect2 v1.0.2 // indirect
 	github.com/pmezard/go-difflib v1.0.0 // indirect
-	github.com/rogpeppe/go-internal v1.9.0 // indirect
+	github.com/rogpeppe/go-internal v1.10.0 // indirect
 	github.com/spf13/pflag v1.0.5 // indirect
 	golang.org/x/net v0.8.0 // indirect
 	golang.org/x/text v0.8.0 // indirect
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig architecture testing

### LINKED ISSUE #116951: [Failing test] verify-master
### Which jobs are failing?

master-blocking

- verify-master

### Which tests are failing?

- verify-vendor
Screenshot from 2023-03-27 22-08-51

### Since when has it been failing?

2023-03-27 02:51 PDT

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#verify-master

### Reason for failure (if possible)

```
hack/update-vendor.sh
go version go1.20.2 linux/amd64
All pinned versions of checked dependencies match their preferred version.
Removing /home/prow/go/src/k8s.io/kubernetes/_tmp/kube-vendor.DK6Qay
+++ exit code: 1
+++ error: 1
[0;31mFAILED   verify-vendor.sh	80s
Verifying verify-yamlfmt.sh
+++ Running case: verify.yamlfmt 
+++ working dir: /home/prow/go/src/k8s.io/kubernetes
+++ command: bash "hack/make-rules/../../hack/verify-yamlfmt.sh"
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig testing
cc @kubernetes/ci-signal

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

Runs `hack/update-vendor.sh`

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/116946
Fixes https://github.com/kubernetes/kubernetes/issues/116951

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/assign @dims @liggitt 
/priority important-soon

### CODE REVIEW

**Comment by dims** [comment]
/triage accepted

this is a transitive dependency, not sure why our golang harness wanted to pick this up ... now.. anyway to unblock the CI signal let's land this

cc @salaxander @kubernetes/sig-release-leads @liggitt 

/approve
/lgtm

**Comment by liggitt** [comment]
disconcerted lgtm...

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
@salaxander this is low impact we should merge, will leave on you to unhold it

**Pull request merged**
