### PR TITLE
remove unnecessary vendoring of cmd/cfssl

### PR DESCRIPTION
**Pull request by dims**
During dc9def6f93bae23aef3b57e58f7bdd9edda63c43, which was a revert for
7a10073e4aefbda1d0e026353fd055db5cf8f140 we forgot to remove the extra
thing we started vendoring.

Change-Id: I308dc41cdb9b990f2b4ab8d59ad0445d5ac02e8c

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
We don't really need to vendor `cmd/cfssl`

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
are we still downloading and using an ancient binary because they stopped publishing binaries?

**Comment by dims** [comment]
/test pull-kubernetes-kubemark-e2e-gce-big

@BenTheElder yes, we are using the old 1.2 version. i don't see them publish anything newer.

**Comment by BenTheElder** [comment]
needs rebase :robot: 

also that is unfortunate.. probably something to fix at some point.

**Comment by liggitt** [comment]
> also that is unfortunate.. probably something to fix at some point.

not really... in this case it was an actual conflict:

```diff
++<<<<<<< HEAD
 +      github.com/mattn/go-sqlite3 v1.6.0 // indirect
 +      github.com/mesos/mesos-go v0.0.9 // indirect
++=======
+       github.com/mesos/mesos-go v0.0.0-20180906210748-ff8175bfda54 // indirect
++>>>>>>> remove unnecessary vendoring of cmd/cfssl
```

other non-overlapping vendor changes went in fine without rebase issues

**Comment by BenTheElder** [comment]
er sorry: the unfortunate bit is that we're still in a state with a rather
old CFSSL binary, they're publishing new releases, just not binaries

**Pull request merged**
