### PR TITLE
Automated cherry pick of #63248: fix formatAndMount func issue on Windows

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #63248 on release-1.9.

#63248: fix formatAndMount func issue on Windows

### CODE REVIEW

**Comment by jsafrane** [comment]
/approve no-issue
?

**Comment by mbohlool** [comment]
please make sure this PR has approval and merged before the deadline for 1.9.9.

**Comment by andyzhangx** [comment]
@jsafrane it requires `/approve` not `/lgtm` thanks.

**Comment by andyzhangx** [comment]
it's a rebase, PTAL again, thanks. @jsafrane

**Pull request merged**
