### PR TITLE
should use time.Since instead of time.Now().Sub

### PR DESCRIPTION
**Pull request by wgliang**
**What this PR does / why we need it**:

should use time.Since instead of time.Now().Sub

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
NONE
**Special notes for your reviewer**:
NONE
**Release note**:

```release-note
```
NONE

### CODE REVIEW

**Comment by wgliang** [comment]
Who will add lgtm label?

**Comment by dims** [comment]
@wgliang i can only review, lgtm has to be one of the approvers in the pkg/controller/deployment/OWNERS file

**Comment by wgliang** [comment]
Why need lgtm again? @dims

**Comment by dims** [comment]
Sorry i meant "you need approval from those in the OWNERS file, as i am not there my approval does not help"

**Review by janetkuo — APPROVED** [review]
Would you squash commits into one?

**Comment by wgliang** [comment]
Will multiple submissions affect the merger? what should I do? Re-raised a PR？

**Comment by aleksandra-malinowska** [comment]
@wgliang Just squash commits and force push to this branch. It will be the same PR, but approve and lgtm labels will have to be added again

**Comment by wgliang** [comment]
I have squash commits and force push to this branch.

**Comment by wgliang** [comment]
How to solve the test failed? It was not my change.

**Comment by wgliang** [comment]
@janetkuo

**Comment by wgliang** [comment]
Who will have to review？

**Comment by wgliang** [comment]
@janetkuo

**Pull request merged**
