### PR TITLE
Fix staticcheck failures for pkg/controller/replicaset and pkg/kubelet/dockershim

### PR DESCRIPTION
**Pull request by chymy**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Part of #92402
```
pkg/controller/replicaset/replica_set_test.go:508:6: type byName is unused (U1000)
pkg/controller/replicaset/replica_set_test.go:1128:5: this value of err is never used (SA4006)
pkg/controller/replicaset/replica_set_test.go:1221:2: this value of rsExp is never used (SA4006)
pkg/kubelet/dockershim/docker_container.go:183:42: config.GetLinux().GetSecurityContext().GetSeccompProfilePath is deprecated: Do not use.  (SA1019)

```
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]
/approve

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
