### PR TITLE
Use cobra

### PR DESCRIPTION
**Pull request by deads2k**
pick of https://github.com/kubernetes/kubernetes/pull/58407, https://github.com/kubernetes/kubernetes/pull/58398, and https://github.com/kubernetes/kubernetes/pull/58405 with the ultimate goal of picking https://github.com/kubernetes/kubernetes/pull/58408 and having a consistent hyperkube for 1.9

/assign mtaufen
/assign ncdc
@smarterclayton for approval
@liggitt who is the release decider?

### CODE REVIEW

**Comment by mtaufen** [comment]
kubelet stuff looks good

**Comment by deads2k** [comment]
@liggitt have a look at the rest.  Changes aren't that big.

**Comment by mbohlool** [comment]
as this is not an automated cherrypick, it needs a release note. I will also need lgtm and approval from usual people to approve this cherrypick.

**Comment by mbohlool** [comment]
@deads2k The deadline for 1.9.3 is Monday. If this change need to go into 1.9.3, the approver and reviewers of original PRs need to approve/lgtm it. Also it needs a release note.

**Comment by deads2k** [comment]
> @deads2k The deadline for 1.9.3 is Monday. If this change need to go into 1.9.3, the approver and reviewers of original PRs need to approve/lgtm it. Also it needs a release note.

I'll try to get my ducks lined up for 1.9.4 rather than rush this now.

**Comment by mbohlool** [comment]
@deads2k I really like that idea for this PR :)

**Pull request closed without merging**
