### PR TITLE
Drop 1.19 release branch rules for publishing-bot

### PR DESCRIPTION
**Pull request by dims**
Last release from 1.19 branch of k/k has shipped (1.19.6). We don't need to process this branch anymore.

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm
/hold
for @palnabarun to take a look

**Comment by dims** [comment]
looks like @palnabarun had this covered already in https://github.com/kubernetes/kubernetes/pull/106781

**Pull request closed without merging**
