### PR TITLE
cleanup after JobPodFailurePolicy is promoted to GA

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

A following-up of https://github.com/kubernetes/kubernetes/pull/125442

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by alculquicondor — COMMENTED** [review]
/approve

**Comment by mimowo** [comment]
/assign @deads2k 
For strategy cleanup

**Comment by carlory** [comment]
/cc @mimowo 

rebased.

**Review by mimowo — COMMENTED** [review]
/lgtm
Thanks!

**Pull request merged**
