### PR TITLE
[WIP] Adding Keystone Trust Support

### PR DESCRIPTION
**Pull request by codevulture**
``` release-note
* Use the release-note-* labels to set the release note state 
* Clear this block to use the PR title as the release note 
-OR-
* Enter your extended release note here
```

[Analytics]()

This change would be merged after below is completed.
Adding Support in Gopherhead Library:[wip] https://github.com/rackspace/gophercloud/pull/580

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/26037)

### CODE REVIEW

**Comment by codevulture** [comment]
I signed it!

**Comment by mkumatag** [comment]
Make sure you bump godeps package as well once rackspace/gophercloud#580 get merged.

**Comment by mikedanese** [comment]
cc @kubernetes/sig-openstack

**Comment by feiskyer** [comment]
@mikedanese Think we should remove lgtm label until rackspace/gophercloud#580 is in and godeps is updated.

**Comment by mikedanese** [comment]
@feiskyer done. cc @kubernetes/sig-openstack

**Comment by codevulture** [comment]
Unfortunately, I was getting error in dependency update and have asked the same on : https://github.com/rackspace/gophercloud/pull/448 , once i get the solution of dependency update i will submit the changes.It would be great if someone could let me know what might be going wrong would be helpful.Thanks.

**Comment by liggitt** [comment]
this looks like the same thing as #32111. I have a slight preference for that one, since it doesn't export a new function, but I'll leave it up to you and @MatMaul to coordinate and pick a PR to go forward with

**Comment by anguslees** [comment]
@liggitt: Agreed, we should merge the other one.  Slightly neater code, and this PR is still WIP (missing the required godep update).

**Comment by codevulture** [comment]
It took a bit long for this PR because i have to add the library code first in the gophercloud repo which took much time to get merged to get this working or maybe other pr to work, I don't have a problem with the Pr as long it serves the same purpose, but maybe this code may not be neater but maybe a bit correct ;), i will comment on other PR for the same.Thanks for reviews everyone, really appreciate it.
So, as reviewer's choice i will abandon this patch, as angus is the original maintainer i guess ;) .Thanks guys.

**Comment by MatMaul** [comment]
Hi @codevulture, sorry I didn't see your PR before sending mine. Thanks for your work on trust support in gophercloud.

**Comment by MatMaul** [comment]
And BTW if you want to rebase your changes to merge yours instead no problem for me, as long as it works in the end.

**Comment by codevulture** [comment]
@MatMaul : Thanks, let's work together for the change, doesn't matter which PR, let's go with yours :)

**Pull request closed without merging**
