### PR TITLE
Revert "Passing `KUBE_TEST_ARGS` variable to make through process environment"

### LINKED ISSUE #66782: KUBE_TEST_ARGS in make command did not pass to hack/make-rules/test.sh
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

After change in #66061, if you still set`KUBE_TEST_ARGS` in make command, its amended value will not be passed to `hack/make-rules/test.sh`

P.S.  `KUBE_TEST_ARGS` is amended  with default values here: https://github.com/kubernetes/kubernetes/blob/28b6fb5f7d4ec9fc0be2843d61543ef70b748e70/hack/make-rules/test-integration.sh#L73

**How to reproduce it (as minimally and precisely as possible)**:

```bash
make test-integration WHAT=./test/integration/scheduler_perf GOFLAGS="-v=1" KUBE_TEST_VMODULE="''" KUBE_TEST_ARGS="-run=xxx -bench=BenchmarkScheduling"

...
+++ [0730 15:14:06] Running integration test cases
[KUBE_TEST_ARGS in test-integration.sh:] -run=xxx -bench=BenchmarkScheduling -short=true --vmodule='' --alsologtostderr=true
[KUBE_TEST_ARGS in test.sh:]: -run=xxx -bench=BenchmarkScheduling
Running tests for APIVersion: v1
...
```
/sig testing

**Anything else we need to know?**:

/assign @cofyc

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by cofyc**
This reverts commit fda0edcd1c853f08ce3c3d8662d38cd8ed84512d.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #66782

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by resouer** [comment]
Thanks!

/lgtm

**Comment by resouer** [comment]
kindly ping @cblecker for approve

**Comment by cofyc** [comment]
/assign @cblecker 

We need to revert #66061.

`VAR=NEWVAL make test` or `export VAR=NEWVAL; make test` cannot change VAR in sub-make because [make get its variables from `MAKEFLAGS` variable](https://www.gnu.org/software/make/manual/html_node/Options_002fRecursion.html#Options_002fRecursion.), so isub-makes will always use `KUBE_TEST_ARGS` in command line args.

To fix special use case when KUBE_TEST_ARGS contains `$`, we need find another way (escaping `$` or hacking with new variable names).

**Pull request merged**
