### PR TITLE
Fixing nits for client-gen

### PR DESCRIPTION
**Pull request by caesarxuchao**
Some trivial fixes for client-gen.
commit "Fix UpdateStatus" has been reviewed in #19737.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@k8s-bot e2e test this please

**Comment by smarterclayton** [comment]
LGTM

**Comment by caesarxuchao** [comment]
@k8s-bot test this please

**Comment by caesarxuchao** [comment]
@k8s-bot unit test this please

**Pull request merged**
