### PR TITLE
Removed outdated metrics docs

### PR DESCRIPTION
**Pull request by piosz**
cc @jszczepkowski @vishh @kubernetes/sig-instrumentation

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36606)

### CODE REVIEW

**Comment by vishh** [comment]
lgtm

**Comment by vishh** [comment]
Why does this have to be in `v1.5`?

**Comment by piosz** [comment]
It doesn't have to be in 1.5. Removing the milestone.

**Comment by piosz** [comment]
@k8s-bot node e2e test this

**Comment by piosz** [comment]
@k8s-bot cvm gke e2e test this

**Pull request merged**
