### PR TITLE
kubeadm: Only create bootstrap configmap if not exists.

### PR DESCRIPTION
**Pull request by pipejakob**
**What this PR does / why we need it**:
The fact that this method was not idempotent was breaking kubeadm upgrades.

https://github.com/kubernetes/kubeadm/issues/278

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by pipejakob** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by pipejakob** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by pipejakob** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by luxas** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Review by luxas — APPROVED** [review]

**Comment by dchen1107** [comment]
/approve no-issue

I am adding the approved label back for this pr since it has issue from kubernetes/kubeadm. We need to fix the script to take that repo too.

**Comment by pipejakob** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
