### PR TITLE
Tear down resources before tear down the cluster for ubuntu

### LINKED ISSUE #13077: When kube-down the cluster,we need to umount the volume of pods.
when we run kube-down.sh to move a k8s cluster, we want a clean env to deploy a new cluster next time. https://github.com/kubernetes/kubernetes/pull/12075. we need to move all remains, includes volumes of pod. https://github.com/kubernetes/kubernetes/pull/12704
However, if we can add a command like "kubectl remove all pods", or  let Kubelet clean up volumes. It is better than writing script.
So i want to add a new command to remove all mount volumes, before kube-down a cluster.

### PR DESCRIPTION
**Pull request by dalanlan**
Fix #13077. 
Test passed locally.
/cc @resouer @huangyuqi

### CODE REVIEW

**Comment by pmorie** [comment]
@k8s-bot ok to test

**Comment by dalanlan** [comment]
@pmorie  
Just wondering if you can spare some time for this pr. Seems good to go ;-)

**Comment by jlowdermilk** [comment]
LGTM. Will get merged by robot during regular hours.

**Comment by dalanlan** [comment]
Rebased and "lgtm" was removed. Not sure whether this would block auto-merge.

**Comment by huangyuqi** [comment]
Hi, @dalanlan , i met two issues.

1. If the api-server is down of not working, the kube-down.sh script will exit.
2. The function tear_down_alive_resources should copy to the master node to execute. Not in the local machine.
What do you think? : )

**Comment by dalanlan** [comment]
Addressed by #14225

**Pull request merged**
