### PR TITLE
Fix misspelling of condition.

### PR DESCRIPTION
**Pull request by yangjunmyfm192085**
Signed-off-by: JUN YANG <yang.jun22@zte.com.cn>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Fix misspelling of condition. 
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
"NONE"
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
"NONE"
```

### CODE REVIEW

**Comment by fedebongio** [comment]
leaving this one untriaged so we can come back later

**Comment by caesarxuchao** [comment]
Please don't change the vendor files.

Otherwise lgtm.

**Comment by yangjunmyfm192085** [comment]
@caesarxuchao I have fixed it. thanks.

**Pull request merged**
