### PR TITLE
move system node critical test to eviction test lane

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Move system_critical test to eviction as it is testing disk pressure.

It is a long test so trying to move it out of general serial test.
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kannon92** [comment]
/assign @mrunalp @dims 

Opening this up so we can make some room. This test can take anywhere up to 10-30 minutes in CI. It is testing eviction for a static pod. Since our eviction tests are really set up for this already, I think moving this to eviction makes sense.

I can confirm that this test is covered in the eviction job while it is dropped in the serial jobs now.

**Comment by bart0sh** [comment]
@kannon92 In my last serial job run this test took 16 sec: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/120459/pull-kubernetes-node-kubelet-serial-crio-cgroupv1/1769356436250300416/build-log.txt

/hold
I'd propose to wait until https://github.com/kubernetes/kubernetes/issues/123589 is fixed.
Its last run with almost everything enabled [took 2hours](https://github.com/kubernetes/kubernetes/issues/123589#issuecomment-2002597106)

**Comment by kannon92** [comment]
IMO I still think I'd prefer to move this test to eviction anyway. It reuses the eviction manager code and even tests DiskPressure.

Logically I would prefer it in the eviction tests rather.

**Comment by bart0sh** [comment]
ok, unholding
/unhold
/lgtm

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

good idea. I hope it will not break the eviction lane with timeout =)

**Comment by kannon92** [comment]
@SergeyKanzhelev I have a fix for the crio timeouts: https://github.com/kubernetes/test-infra/pull/32451

**Pull request merged**
