### PR TITLE
Sync master into feature branch

### PR DESCRIPTION
**Pull request by lavalamp**

### CODE REVIEW

**Comment by lavalamp** [comment]
Instead of merging this, I could just do a rebase from the command line and push to the feature branch. That might make for cleaner history but direct pushing is a bit risky. Thoughts?

**Comment by foxish** [comment]
Is the direct push dangerous? 
We already have protected branches turned on preventing force pushes on the master & release branches I think.

**Comment by lavalamp** [comment]
This PR will definitely weirdify the git history, and I'm leaning against it.

**Comment by lavalamp** [comment]
After chatting around, I will just do a rebase & push.

**Pull request closed without merging**
