### PR TITLE
Remove global vSphere framework variable

### LINKED ISSUE #115862: vSphere e2e tests panic in cleanup
### What happened?

Running e2e tests with vSphere cloud panics in `vspheretest.GetReadySchedulableNodeInfos`: https://github.com/kubernetes/kubernetes/blob/1c97dbc8c9096495706b1e141b0fe256ff3185e9/test/e2e/storage/vsphere/vsphere_utils.go#L755-L756 when it sues global variable `f`: https://github.com/kubernetes/kubernetes/blob/1c97dbc8c9096495706b1e141b0fe256ff3185e9/test/e2e/storage/vsphere/bootstrap.go#L29

`GetReadySchedulableNodeInfos` is called in all in-tree vSphere tests during cleanup ([here](https://github.com/kubernetes/kubernetes/blob/1c97dbc8c9096495706b1e141b0fe256ff3185e9/test/e2e/storage/drivers/in_tree.go#L1284)). At that time, the variable is always invalid / nil.

### What did you expect to happen?

tests don't panic

### How can we reproduce it (as minimally and precisely as possible)?

Run e2e tests with vSphere cloud provider.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
v1.26.0+c729678
```

</details>

### Cloud provider

<details>
vSphere
</details>

### OS version

_No response_

### Install tools

<details>
OpenShift
</details>

### Container runtime (CRI) and version (if applicable)

<details>
CRI-O
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by jsafrane**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:
Remove `f framework.Framework` global variable in vSphere tests. It's used only on a few places that can get necessary data (clientset, timeout config) from its caller.

This fixes `vSphereDriver.PrepareTest()` in `in_tree.go` that schedules `ginkgo.DeferCleanup()` that uses the global `f` variable, but its value is not valid at the time of ginkgo cleanup. The clientset will be set in DeferCleanup closure.

#### Which issue(s) this PR fixes:

Fixes #115862

#### Does this PR introduce a user-facing change?

```release-note
Fixed panic in vSphere e2e tests.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dcbw** [comment]
@jsafrane 

```
 test/e2e/storage/vsphere/bootstrap.go:29:5: var `f` is unused (unused)
var f *framework.Framework
    ^
```

**Comment by jsafrane** [comment]
Oops, the point of the PR was to remove the variable.

Fixed.

**Review by soltysh — APPROVED** [review]
/lgtm
/hold
until we can confirmation this is working as expected

**Comment by soltysh** [comment]
Confirmed it's working as intended
/hold cancel

**Pull request merged**
