### PR TITLE
checking goimports

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:
Depends on #64020, which fixes up all the formats of imports.

This PR adds checking scripts to help format imports using `goimports`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:
/cc ixdy fejta
/assign BenTheElder
/sig testing
/area test-infra

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dixudx** [comment]
@wgliang FYI.

With this PR, we can enable auto checking.

**Comment by wgliang** [comment]
@dixudx 
This is exactly what I want to do next. Very good supplement.

**Comment by luxas** [comment]
cc @kubernetes/sig-testing-pr-reviews @kubernetes/sig-contributor-experience-pr-reviews

**Review by luxas — APPROVED** [review]
/approve
for my part at least

**Comment by fejta** [comment]
Please pass unit tests

**Comment by BenTheElder** [comment]
How much time does this add to `verify`? We need to push verify to be faster and less flaky, I'm moderately concerned already by how much we've piled on to `make verify` :|

**Comment by dixudx** [comment]
> How much time does this add to verify?

@BenTheElder No more than 1 min.

**Comment by cblecker** [comment]
I’m going to say that we probably don’t need this at this time.

**Pull request closed without merging**
