### PR TITLE
[Controller]: cidr nil ptr dereference

### PR DESCRIPTION
**Pull request by gaurav1086**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Possible nil pointer deference
**Which issue(s) this PR fixes**:

Fixes # segmentation fault

**Special notes for your reviewer**:
N/A
**Does this PR introduce a user-facing change?**:

NONE

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
fix null pointer dereference.
```

```release-note
NONE
```

### CODE REVIEW

**Comment by gaurav1086** [comment]
Signed the CLA. Thank you.

**Comment by aojea** [comment]
@gaurav1086  please check that you fill correctly the `release note` field in the description to remove the `do-not-merge/release-note-label-needed`

/lgtm
/assign @bowei

**Comment by gaurav1086** [comment]
@aojea done, thank you.

**Comment by gaurav1086** [comment]
@aojea , I believe the tests are failing due to some timeouts (timeout=65m)

subprocess.CalledProcessError: Command '('kubetest', '--dump=/workspace/_artifacts', '--gcp-service-account=/etc/service-account/service-account.json', '--up', '--down', '--test', '--deployment=node', '--provider=gce', '--cluster=bootstrap-e2e', '--gcp-network=bootstrap-e2e', '--gcp-project=k8s-c8d-pr-node-e2e', '--gcp-zone=us-west1-b', '--node-test-args=--container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock --container-runtime-process-name=/usr/bin/containerd --container-runtime-pid-file= --kubelet-flags="--cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\\"name\\": \\"containerd.log\\", \\"journalctl\\": [\\"-u\\", \\"containerd\\"]}"', '--node-tests=true', '--test_args=--nodes=8 --focus="\\[NodeConformance\\]" --skip="\\[Flaky\\]|\\[Slow\\]|\\[Serial\\]"', '**--timeout=65m'**, '--node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/containerd/image-config.yaml')' returned non-zero exit status 1
E0407 02:40:10.284] Command failed
I0407 02:40:10.285] **process 547 exited with code 1 after 65.0m**

**Comment by gaurav1086** [comment]
@aojea thoughts ?

**Comment by gaurav1086** [comment]
@aojea @bowei @freehan could you run the retest command again ? Thank you.

**Comment by alculquicondor** [comment]
/unassign @ahg-g @alculquicondor 

We are not controller owners

**Pull request merged**
