### PR TITLE
Update checks.go

### LINKED ISSUE #119667: Typos in checks.go,width.go,types_swagger_doc_generated.go,swagger.json
### What happened?

Typos in checks.go,width.go,types_swagger_doc_generated.go,swagger.json

### PR DESCRIPTION
**Pull request by deveshgoyal1000**
Fixed typo in line number 97

#### What type of PR is this?

/kind bug
/kind documentation

#### What this PR does / why we need it:
Corrected the typo

#### Which issue(s) this PR fixes:

Fixes #119667
.

### CODE REVIEW

**Comment by liggitt** [comment]
there's a few other occurrences of this typo:

```
	// by finding the highest request/limit for each resource type, and then using the max of
	// of that value or the sum of the normal containers. Limits are applied to init containers
```

```
// estimate the work of of incoming requests.
```

can you resolve those as well?

**Comment by kumarankit999** [comment]
Hey @aramase what we are doing with this PR??

**Comment by deveshgoyal1000** [comment]
@liggitt  Hello, can you reopen this ?

**Comment by deveshgoyal1000** [comment]
> there's a few other occurrences of this typo:
> 
> ```
> 	// by finding the highest request/limit for each resource type, and then using the max of
> 	// of that value or the sum of the normal containers. Limits are applied to init containers
> ```
> 
> ```
> // estimate the work of of incoming requests.
> ```
> 
> can you resolve those as well?

I have 

> there's a few other occurrences of this typo:
> 
> ```
> 	// by finding the highest request/limit for each resource type, and then using the max of
> 	// of that value or the sum of the normal containers. Limits are applied to init containers
> ```
> 
> ```
> // estimate the work of of incoming requests.
> ```
> 
> can you resolve those as well?

I have resolved that as well.

**Comment by deveshgoyal1000** [comment]
> there's a few other occurrences of this typo:
> 
> ```
> 	// by finding the highest request/limit for each resource type, and then using the max of
> 	// of that value or the sum of the normal containers. Limits are applied to init containers
> ```
> 
> ```
> // estimate the work of of incoming requests.
> ```
> 
> can you resolve those as well?

I have resolved that as well.

**Pull request closed without merging**
