### PR TITLE
Update deployment status only when there is a new scaling update during a rollout

### PR DESCRIPTION
**Pull request by 0xmichalis**
@kubernetes/deployment

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36432)

### CODE REVIEW

**Comment by mfojtik** [comment]
LGTM, reduces number of conflicts I guess.

**Comment by saad-ali** [comment]
Looks like this PR was LGTMed [after code freeze](https://github.com/kubernetes/features/blob/master/release-1.5/release-1.5.md) for 1.5 was in effect. Is this a bug fix?

Removing milestone and adding `do-not-merge` until verification.

**Comment by saad-ali** [comment]
> @saad-ali an improvement to the way the deployment controller does updates. I think it can wait for the next release.

Ack, thanks @kargakis

**Comment by kargakis** [comment]
@saad-ali any idea why the PR is queued for merging since the 1.5 milestone is not set? I removed the do-not-merge label but didn't expect this to queue up for merging.

**Comment by saad-ali** [comment]
@kubernetes/test-infra-admins Any idea why this PR was queued for submit when @kargakis added the 1.6 milestone?

Submit queue history:
```
kargakis
#36432: Update deployment status only when there is a new scaling update during a rollout
Will not auto merge because do-not-merge is present
Nov 11, 2016 4:57:09 AM

kargakis
#36432: Update deployment status only when there is a new scaling update during a rollout
Running github e2e tests a second time.
Nov 11, 2016 4:19:57 AM

kargakis
#36432: Update deployment status only when there is a new scaling update during a rollout
Requested and waiting for github e2e test to start running a second time.
Nov 11, 2016 4:19:27 AM

kargakis
#36432: Update deployment status only when there is a new scaling update during a rollout
Queued to run github e2e tests a second time.
Nov 11, 2016 4:19:10 AM
```

The submit queue parameter `submit-queue.do-not-merge-milestones` is `next-candidate,v1.6,`

**Comment by saad-ali** [comment]
> The submit queue parameter `submit-queue.do-not-merge-milestones` is `next-candidate,v1.6,`

Ah, I think `v1.6` should be `1.6` in https://github.com/kubernetes/contrib/pull/1990

CC @foxish

**Comment by saad-ali** [comment]
Changing all the `1.6` milestones to `v1.6` for consistency with previous milestone labels.

**Comment by foxish** [comment]
@saad-ali Did `1.6` get used quite a bit? Then we can add that to the submit-queue config to ensure it is ignored. Else, we should delete the 1.6 milestone and stick with `v1.6` to ensure there is no confusion. Which do you prefer?

**Comment by saad-ali** [comment]
> @saad-ali Did 1.6 get used quite a bit? Then we can add that to the submit-queue config to ensure it is ignored. Else, we should delete the 1.6 milestone and stick with v1.6 to ensure there is no confusion. Which do you prefer?

I moved all `1.6` PRs and Issues to `v1.6` and deleted the `1.6` milestone. So all's good now.

Thanks @kargakis for raising the issue.

**Comment by kargakis** [comment]
Reapplying lgtm after the rebase

**Comment by kargakis** [comment]
@k8s-bot kubemark e2e test this issue: #IGNORE

**Comment by kargakis** [comment]
Rebased conflicts, reapplying lgtm

**Comment by kargakis** [comment]
@k8s-bot test verify this

**Comment by kargakis** [comment]
@k8s-bot verify this

**Comment by kargakis** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by kargakis** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by kargakis** [comment]
@k8s-bot cvm gce e2e test this

**Comment by kargakis** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
