### PR TITLE
ktesting: several fixes and better unit testing

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The new ktesting still had some issues. Not relevant for anything yet, but it will be once more tests start using it.

#### Special notes for your reviewer:

Overall coverage is now at 80.4%. Running the examples would cover some more code, but cannot be done easily in a unit test.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
There are some more fixes that I want to include here:
- [ ] https://github.com/kubernetes/kubernetes/blob/781da7595167f872662db3bb62290d1b0522f666/test/utils/ktesting/assert.go#L110-L119 should use `tCtx.ExpectNoError`
- [ ] https://github.com/kubernetes/kubernetes/blob/781da7595167f872662db3bb62290d1b0522f666/test/utils/ktesting/assert.go#L142 misses some quotation marks and should explain that the message *replaces*, not *extends*, the normal failure message, so it must include all relevant details.
- [ ] https://github.com/kubernetes/kubernetes/blob/781da7595167f872662db3bb62290d1b0522f666/test/utils/ktesting/tcontext.go#L82 must say "last-in-first-out" (LIFO).

**Review by mengjiao-liu — COMMENTED** [review]
/lgtm

**Pull request merged**
