### PR TITLE
Remove invalid comments in hack/lib/version.sh

### PR DESCRIPTION
**Pull request by HecarimV**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Some of the information suggested in the comments has expired

### CODE REVIEW

**Comment by SataQiu** [comment]
Hi @HecarimV Cloud you please also clean up the rest of the code as well？

https://github.com/kubernetes/kubernetes/blob/bd2776e0c930ab149d8c0656e83f979fb017ce0a/hack/lib/version.sh#L158

https://github.com/kubernetes/kubernetes/blob/bd2776e0c930ab149d8c0656e83f979fb017ce0a/hack/print-workspace-status.sh#L38

**Comment by HecarimV** [comment]
> Hi @HecarimV Cloud you please also clean up the rest of the code as well？
> 
> https://github.com/kubernetes/kubernetes/blob/bd2776e0c930ab149d8c0656e83f979fb017ce0a/hack/lib/version.sh#L158
> 
> https://github.com/kubernetes/kubernetes/blob/bd2776e0c930ab149d8c0656e83f979fb017ce0a/hack/print-workspace-status.sh#L38

Sure, I have cleaned up.

**Review by hwdef — COMMENTED** [review]
/lgtm
Thanks!

**Review by SataQiu — APPROVED** [review]
thanks
/lgtm
/approve

**Pull request merged**
