### PR TITLE
Remove gcp cloud-provider checks for kubelet version >= 1.7.2

### LINKED ISSUE #117756: node.status.nodeInfo.kubeProxyVersion is a lie
`v1.Node` has a field `.status.nodeInfo.kubeProxyVersion`, about which [the API docs](https://github.com/kubernetes/kubernetes/blob/v1.27.0/staging/src/k8s.io/api/core/v1/types.go#L5250) say:

```
// KubeProxy Version reported by the node.
KubeProxyVersion string `json:"kubeProxyVersion" protobuf:"bytes,8,opt,name=kubeProxyVersion"`
```

but the field is [set by kubelet](https://github.com/kubernetes/kubernetes/blob/v1.27.0/pkg/kubelet/nodestatus/setters.go#L401), which does not actually know the kube-proxy version:

```
node.Status.NodeInfo.KubeletVersion = version.Get().String()
// TODO: kube-proxy might be different version from kubelet in the future
node.Status.NodeInfo.KubeProxyVersion = version.Get().String()
```

Not only is it possible that the kube-proxy version is different from the kubelet version, it's also possible that kube-proxy isn't even running on the machine.

This field should be marked as deprecated. Ideally kubelet would stop setting it but that might be considered an API break? If kubelet is going to continue setting it, then the API docs and the kubelet source should both be updated to indicate that the field is just an alias for `kubeletVersion` and does not actually indicate the kube-proxy version, and will be set even if kube-proxy is not running.

(Noticed by @liggitt)

/sig node
/sig network

### PR DESCRIPTION
**Pull request by danwinship**
#### What type of PR is this?
/kind bug
/kind cleanup

#### What this PR does / why we need it:
cloud-provider-gcp checks if `node.status.nodeInfo.kubeProxyVersion` is >= 1.7.2 before using certain health check features. I think it is safe to say that it will not be run against clusters with nodes older than that.

(More importantly, `node.status.nodeInfo.kubeProxyVersion` is being deprecated (because it actually indicates the kubelet version, not the kube-proxy version, https://github.com/kubernetes/kubernetes/issues/117756) so the cloud-provider should stop checking it.)

also https://github.com/kubernetes/cloud-provider-gcp/pull/533 for external provider

#### Which issue(s) this PR fixes:
none; encountered while trying to address #117756

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @bowei @thockin 

this seems something at least one of them should remember, it seems right to remove it but who knows 😄

**Review by thockin — COMMENTED** [review]
I don't know if we are really merging changes under legacy-cloud anymore, and I don't actually have approval there.

@andrewsykim 

/lgtm
/approve

**Comment by danwinship** [comment]
> I don't know if we are really merging changes under legacy-cloud anymore

In this case, it's needed to prevent a regression when we make kubelet stop incorrectly setting `KubeProxyVersion`. If we still support people _running_ the legacy cloud provider, then we should fix this.

**Comment by thockin** [comment]
ping @andrewsykim @cheftako @bridgetkromhout @dims

**Pull request merged**
