### PR TITLE
don't wait blindly

### LINKED ISSUE #60463: [Flaky Test] : [sig-api-machinery] Garbage collector should orphan RS created by deployment when deleteOptions.PropagationPolicy is Orphan [Conformance]
## Flaky Jobs:
* [presubmits-kubernetes-blocking#pull-kubernetes-integration](https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&show-stale-tests=)
* [ci-kubernetes-e2e-gci-gce](https://k8s-testgrid.appspot.com/sig-api-machinery#gce&width=5)

## Flakiest test :
* [[sig-api-machinery] Garbage collector should orphan RS created by deployment when deleteOptions.PropagationPolicy is Orphan [Conformance]](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/64957/pull-kubernetes-e2e-gce/40826)

## Triage link
https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-06-15&sig=api-machinery&job=ci-kubernetes-e2e-gci-gce&test=Garbage%20collector%20should%20orphan%20RS%20created%20by%20deployment%20when%20deleteOptions.PropagationPolicy%20is%20Orphan

/priority failing-test
/priority important-soon
/kind flake
/sig-api-machinery
@kubernetes/sig-api-machinery-bugs 

this failure is currently one of the top flake and repros in both Presubmits and CI jobs. This test is also part of the Conformance suite, which makes the flake far more critical. Can one of you please help triage this issue.

### PR DESCRIPTION
**Pull request by lavalamp**
/kind flake

**What this PR does / why we need it**:
See comment.

**Which issue(s) this PR fixes**:
Fixes #60463

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by logicalhan — COMMENTED** [review]
/lgtm

**Comment by lavalamp** [comment]
/hold

I forgot to do something with the error

**Review by logicalhan — COMMENTED** [review]
/lgtm

**Pull request merged**
