### PR TITLE
Move audit logs e2e to the default test suite.

### PR DESCRIPTION
**Pull request by loburm**
Fixes https://github.com/kubernetes/kubernetes/issues/56235

```release-note
NONE
```

### CODE REVIEW

**Comment by crassirostris** [comment]
I would concur. This tests are testing concrete configuration, that's only present in GCE, it doesn't make sense to enable it by default

**Comment by loburm** [comment]
What if we add gce guard to this test? We have already some gce specific tests in default test suite.

**Comment by crassirostris** [comment]
SGTM

**Comment by tallclair** [comment]
Yeah, I like having this in the core suite. When this goes to GA I think we should consider making audit logs enabled by default, and then you can remove the GCE test restriction.

**Comment by crassirostris** [comment]
Problems I see with it are policy and a file name. Having a streaming API would help to write such tests audit backend-agnostic and maybe we should consider defaulting policy to the one used in GCE: it's not actually gce-specific.

**Comment by tallclair** [comment]
> defaulting policy to the one used in GCE: it's not actually gce-specific.

Parts of it are:
- legacy kubelet names
- insecure port rules
- HPA rules
- etc.

We could probably come up with a more generic one to set as the default, and overwrite it with our GCE-specific one when relevant.

**Comment by crassirostris** [comment]
Created a follow-up issue: https://github.com/kubernetes/kubernetes/issues/56210

Meanwhile, @loburm, could you please add [a platform guard](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/instrumentation/logging/stackdrvier/basic.go#L42) that restricts these tests to gce and gke environments?

**Comment by loburm** [comment]
Sure, but why gke. At least in current version this test reads data from the file, which means that it's going to fail for gke platform, isn't it?

**Comment by crassirostris** [comment]
It reaches out to the apiserver `/logs` endpoint to get logs. AFAIR, it works on GKE also

**Comment by crassirostris** [comment]
@loburm Friendly ping

**Comment by crassirostris** [comment]
@cblecker It's not going to pass on AWS just yet. We're in CET, @loburm will fix it tomorrow morning

**Comment by crassirostris** [comment]
Turns out Marian is OOO today, will fix it on Monday

**Comment by crassirostris** [comment]
/lgtm

@sttts Could you please approve?

**Comment by crassirostris** [comment]
@loburm I think you need to wrap it in `BeforeEach`:

```go
ginkgo.BeforeEach(func() {
	framework.SkipUnlessProviderIs("gce", "gke")
})
```

**Comment by loburm** [comment]
Thanks Mik,
Now all test are passing.

**Comment by crassirostris** [comment]
@tallclair If you could approve, that would also be perfect

**Comment by spiffxp** [comment]
If we're happy with this, will there be a corresponding PR to remove the [audit-specific job](https://k8s-testgrid.appspot.com/sig-release-master-blocking#gci-gce-audit)?

**Comment by crassirostris** [comment]
@loburm Could you please make one?

**Comment by loburm** [comment]
I'll do it

**Comment by aleksandra-malinowska** [comment]
Looks like presubmits are failing on audit logs tests: https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gke-gci :(

**Pull request merged**
