### PR TITLE
Include the key of invalid label's value in error message

### PR DESCRIPTION
**Pull request by kenegozi**
For e.g., when specifying an invalid value for a label, it is not always
clear which label the value was specified for. Including the key in the
error message makes debugging easier.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
When specifying an invalid value for a label, it was not always
clear which label the value was specified for. Starting with this release, the
label's key is included in such error messages, which makes debugging easier.
```

### CODE REVIEW

**Comment by kenegozi** [comment]
```release-note
When specifying an invalid value for a label, it was not always
clear which label the value was specified for. Starting with this release, the
label's key is included in such error messages, which makes debugging easier.```

**Comment by kenegozi** [comment]
Not sure about `kind`, should a clearer user visible error message be counter as `documentation`?

**Review by logicalhan — APPROVED** [review]
This seems reasonable to me. 

/lgtm

**Review by neolit123 — COMMENTED** [review]
/ok-to-test
/kind cleanup
/priority backlog

**Comment by kenegozi** [comment]
Thanks for taking a look at this.

I copied the release note block from the in-discussion comment to the top comment, in hope it would now get picked up.

**Comment by caesarxuchao** [comment]
lgtm

**Comment by kenegozi** [comment]
Is there any more steps I need to do for this PR to be merged?

**Comment by kenegozi** [comment]
Thanks for the guidance and for looking into this!

**Pull request merged**
