### PR TITLE
Remove unused parameter (pod) in `pkg/scheduler/core/generic_scheduler`

### PR DESCRIPTION
**Pull request by wgliang**
**What this PR does / why we need it**:

Remove unused parameter (pod) in `pkg/scheduler/core/generic_scheduler`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wgliang** [comment]
/ping @k82cn @resouer 
PTAL

**Review by resouer — COMMENTED** [review]
/lgtm

Please make sure @bsalamat take the final pass.

**Comment by wgliang** [comment]
@bsalamat
for /approve

**Comment by wgliang** [comment]
@bsalamat @misterikkit 
for /approve

**Comment by misterikkit** [comment]
/kind cleanup
(I don't actually have approve power yet.)

**Review by bsalamat — APPROVED** [review]
/lgtm

Thanks, @wgliang!

**Pull request merged**
