### PR TITLE
client-go: rename variable that gates the WatchList feature

### PR DESCRIPTION
**Pull request by p0lyn0mial**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
renames `ENABLE_CLIENT_GO_WATCH_LIST_ALPHA` to `KUBE_FEATURE_GATE_USE_WATCH_LIST`.
this environment variable controls whether the WatchList feature will be used.

xref: https://github.com/kubernetes/enhancements/issues/3157
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
client-go: renames ENABLE_CLIENT_GO_WATCH_LIST_ALPHA to KUBE_FEATURE_GATE_USE_WATCH_LIST. this environment variable controls whether the WatchList feature will be used.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3157-watch-list
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
Let's wait with this PR until we have clarify how the enablement mechanism looks like.

/hold

**Comment by p0lyn0mial** [comment]
/close

as we have decided to introduce feature gates to client-go

xref: https://github.com/kubernetes/kubernetes/pull/122571

**Pull request closed without merging**
