### PR TITLE
Add RainbowMango to reviewers for component-base/metrics

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Add myself as a reviewer for component-base/metrics.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

/assign @logicalhan 
/cc @brancz

### CODE REVIEW

**Comment by brancz** [comment]
why not sig instrumentation reviewers?

**Comment by RainbowMango** [comment]
> why not sig instrumentation reviewers?

@brancz Thanks, please take a look.

**Pull request merged**
