### PR TITLE
Revert "Turning on pod autoscaler on GCE."

### PR DESCRIPTION
**Pull request by j3ffml**
Reverts kubernetes/kubernetes#13547 to unbreak gke-ci

### CODE REVIEW

**Comment by mikedanese** [comment]
LGTM. Wait for green?

**Comment by jlowdermilk** [comment]
Wait for e2e sounds good. I want to stop the bleeding, but good idea to make sure the rollback doesn't break gce e2e.

**Comment by mikedanese** [comment]
```
k8s.io/kubernetes/test/integration / integration / TestServiceAccountTokenAuthentication
FAIL
````

**Comment by mikedanese** [comment]
cc @jszczepkowski

**Pull request merged**
