### PR TITLE
Use forward plugin instead of proxy plugin in the default configuration of CoreDNS

### LINKED ISSUE #73254: CoreDNS to use forward plugin instead of proxy
**What would you like to be added**:
Modify the CoreDNS configuration to use the [`forward` plugin](https://coredns.io/plugins/forward/) instead of the existing `proxy` plugin.

**Why is this needed**:
The `forward` plugin is the “new” version of the `proxy` plugin  and is faster because it re-uses connections to the upstreams.

/assign

### PR DESCRIPTION
**Pull request by rajansandeep**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Modify the default corefile configuration of CoreDNS to use the `forward` plugin instead of the `proxy` plugin.

**Which issue(s) this PR fixes**:

Fixes #73254 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
The CoreDNS configuration now has the forward plugin for proxy in the default configuration instead of the proxy plugin. 
```

/cc @chrisohaver

### CODE REVIEW

**Review by rosti — COMMENTED** [review]
Thanks @rajansandeep ! Looks good from kubeadm perspective.
/assign @fabriziopandini @timothysc

**Review by chrisohaver — APPROVED** [review]
Corefile syntax lgtm

**Review by fabriziopandini — APPROVED** [review]
The kubeadm part is ok; for the CoreDNS part I'm echoing @chrisohaver comment
/approve
/lgtm

**Review by MrHohn — APPROVED** [review]
/approve

**Pull request merged**
