### PR TITLE
Skip OOMKilled Jobs if Swap is enabled.

### LINKED ISSUE #121702: Swap Tests failing for OOM
### Which jobs are failing?

https://testgrid.k8s.io/sig-node-cri-o#kubelet-gce-e2e-swap-fedora

### Which tests are failing?

The swap fedora job is failing consistently for OOM.  

### Since when has it been failing?

For a while.

### Testgrid link

https://testgrid.k8s.io/sig-node-cri-o#kubelet-gce-e2e-swap-fedora

### Reason for failure (if possible)

```
{ failed [FAILED] Failed waiting for pod to terminate, oomkiller-test-9468/oomkill-target-pod: Timed out after 300.001s.
expected pod to be terminated with reason , got instead:
```

It looks like OOM is not actually killing these pods when swap is enabled.  I did not see any examples of this failing without swap enabled so I think this is a real issue.

### Anything else we need to know?

There is a failure in OOMKilled as part of the serial fedora job but that is not related to this.

This is part of https://github.com/kubernetes/enhancements/issues/2400 and should be required for promotion to Beta2.

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind failing-test

#### What this PR does / why we need it:
Fix fedora-swap tests for OOM.
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/121702

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

Part of https://github.com/kubernetes/enhancements/issues/2400

```docs

```

### CODE REVIEW

**Comment by haircommander** [comment]
/test pull-crio-cgroupv1-node-e2e-features
/test pull-kubernetes-cos-cgroupv1-containerd-node-e2e-features

(hijacking for https://github.com/kubernetes/kubernetes/pull/121193 testing)

**Comment by kannon92** [comment]
/hold

I have no idea but these test failures look legit. May go a different route and skip these tests on swap.

**Comment by pacoxu** [comment]
/lgtm

This fixed `should report resource usage through the stats api` e2e.

/assign @SergeyKanzhelev @endocrimes

**Comment by kannon92** [comment]
Im aware of these failures. I’ll admit I am still surprised why these configs set in OOM cause flakiness in otherwise stable tests.

I will look into this this week.

https://github.com/kubernetes/kubernetes/pull/121706#issuecomment-1791830090

**Comment by kannon92** [comment]
/test pull-kubernetes-node-swap-fedora
/test pull-kubernetes-node-swap-fedora-serial

@pacoxu @dims I found out the problem.  I am not able to change the configs for swap in conformance tests.  Restarting kubelet during conformance tests is bad news.  So the solution is to skip these tests for Swap at the moment.

I think this should fix the OOM issues in swap for now.

**Pull request merged**
