### PR TITLE
Set PriorityClassName when there's a default PirorityClass.

### LINKED ISSUE #66853: Also set priority class name when there's Default PriorityClass
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind cleanup
/sig scheduling

**Description**:

If Pod did not set `.spec.PriorityClassName`, `Priority` admission controller will set `.spec.Priority` to "default value". If the default value are from default priority class, it's better to also set `.spec.PriorityClassName` of pod.

### PR DESCRIPTION
**Pull request by k82cn**
Signed-off-by: Da K. Ma <klaus1982.cn@gmail.com>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #66853 

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by k82cn** [comment]
@derekwaynecarr , @bsalamat , PTAL :)

**Comment by k82cn** [comment]
@derekwaynecarr , PTAL :)

**Comment by k82cn** [comment]
@deads2k , PTAL :)

**Comment by bsalamat** [comment]
I just saw this today. I don't have any strong objections, but I wonder if there is any particular use-case that would need the priority class name to be set. Does it work better with ResourceQuota?

One scenario that could be slightly confusing for users after this PR is:
1. No default priority class exists in a cluster.
1. User creates a collection (ReplicaSet, etc) with no priority class name in the pod template.
1. Pods are created and their priority class names are empty.
1. A new default priority class is added.
1. One of the Pods of the collection dies and a replacement is created. This replacement is the only one among the other pods in the collection that has a priority class name set.

**Comment by k82cn** [comment]
If Pod did not set `.spec.PriorityClassName`, Priority admission controller will set `.spec.Priority` to "default value"; but for ResourceQuota per Priority, it can not do restriction for the default priority class.

> One scenario that could be slightly confusing for users after this PR is:

Yes,  the value maybe also changed if default priority class's value is not zero. I think that's align with  current behaviour.

**Review by bsalamat — APPROVED** [review]
/lgtm

**Comment by nikhita** [comment]
/assign @deads2k 
for approval

**Pull request merged**
