### PR TITLE
fix some typo

### PR DESCRIPTION
**Pull request by timchenxiaoyu**
fix some typo

**Release note**:

```NONE
```

### CODE REVIEW

**Comment by brendandburns** [comment]
/lgtm

/release-note-none

LGTM + release-note-none from the bulk LGTM tool

**Comment by brendandburns** [comment]
@k8s-bot unit test this
@k8s-bot kops aws e2e test this
@k8s-bot gce etcd3 e2e test this

**Comment by timchenxiaoyu** [comment]
@k8s-bot kops aws e2e test this

**Comment by grodrigues3** [comment]
@k8s-bot ok to test

**Comment by grodrigues3** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
