### PR TITLE
Add controllerrevisions as valid resource in kubectl help

### PR DESCRIPTION
**Pull request by janetkuo**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**: controllerrevisions is a new resource added in 1.7 @kubernetes/sig-cli-maintainers 

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by janetkuo** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by janetkuo** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by janetkuo** [comment]
/assign @mengqiy 
would you take a look at this too?

**Comment by mengqiy** [comment]
@janetkuo Can you update https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/kubectl-overview.md as well? Thanks.

**Comment by mengqiy** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by janetkuo** [comment]
> @janetkuo Can you update https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/user-guide/kubectl-overview.md as well? Thanks.

@mengqiy Yes. Filed https://github.com/kubernetes/kubernetes.github.io/issues/3991

**Pull request merged**
