### PR TITLE
Parallelize YAML processing for pods in APIserver.

### PR DESCRIPTION
**Pull request by gmarek**
I'm not sure how useful is this change. In single threaded environment it's bad, as it's impossible to fail fast. In multithreaded it helps a bit.

### CODE REVIEW

**Comment by erictune** [comment]
We should probably hold off on adding parallelizing optimizations to the APIserver until we have consistently run the existing apiserver code with multiple threads.  AFAICS, we don't set GOMAXPROCS for apiserver.

**Comment by gmarek** [comment]
As per #4521 we're setting GOMAXPROCS now. But I agree that we should hold this change until we know how APIserver works in multithreaded environment.

**Comment by erictune** [comment]
gmarek what is the status on this?

**Comment by erictune** [comment]
@gmarek

**Comment by gmarek** [comment]
That I don't know. I wrote this in hope that it'll speed up APIserver, but gains are not very big. The side effect that I didn't fix in this PR is that ordering of the output is not deterministic anymore. There'll need to be some kind of sorting somewhere later in the code path. I'll do it, if you think this PR makes sense, as a part or general parallelization of Kubernetes. If not, we can just drop it.

**Comment by erictune** [comment]
I don't think this makes sense at this time if the wins are not big.

**Pull request closed without merging**
