### PR TITLE
Revert "RC/RS: Fully Respect ControllerRef"

### PR DESCRIPTION
**Pull request by gmarek**
Reverts kubernetes/kubernetes#41984

It seems that it blocked submit queue

### CODE REVIEW

**Comment by gmarek** [comment]
Let's try the fix first.

**Comment by yujuhong** [comment]
FYI, I filed an issue: #42461

**Comment by yujuhong** [comment]
The cause was in the kops repositor: https://github.com/kubernetes/kubernetes/issues/42461#issuecomment-283847465

**Comment by gmarek** [comment]
The fixe seems to work.

**Pull request closed without merging**
