### PR TITLE
e2e: Remove specific Gluster repo.

### PR DESCRIPTION
**Pull request by jsafrane**
Debian Wheezy image in GCE has already the correct one.

### CODE REVIEW

**Comment by eparis** [comment]
Was this hurting the GCE debian wheezy images? Do other non-GCE debian wheezy images usually have the right version or it is just the images they use in GCE which don't need this?

**Comment by jsafrane** [comment]
Yes, it was hurting e2e tests on GCE, as it failed to import appropriate signing key and salt then refused to install ceph and iscsi tools (gluster was already installed).

I can't say anything about any other Debian images, I expect there is some variety.

**Comment by jsafrane** [comment]
Also note that this patch influences only salt installation with `KUBE_E2E_STORAGE_TEST_ENVIRONMENT=true`. Regular installation is not affected in any way.

**Comment by eparis** [comment]
I guess my real question is 'does it break vagrant'  which i believe is the other common test platform.

**Comment by jsafrane** [comment]
No, it can't break Vagrant, Vagrant uses Fedora images.

**Pull request merged**
