### PR TITLE
issue(#51078) add statefulset info into kubectl cluster-info dump

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:
#51078

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
please remove the bin file `cmd/kubectl/kubectl` in the PR files :)

**Comment by zjj2wry** [comment]
this command will deleted in near furture?

**Comment by spzala** [comment]
@zjj2wry hello, just trying to understand why the PR was closed? is it because statefulset are in beta? Is the related issue still valid? Thanks!

**Comment by zjj2wry** [comment]
i feel this command will depecated. Are you still need this feature?

**Comment by spzala** [comment]
@zjj2wry hi, nope..I thought this issue should be closed :-) so glad you closed it. Thanks!!

**Comment by zjj2wry** [comment]
open issue https://github.com/kubernetes/kubectl/issues/171

**Pull request closed without merging**
