### PR TITLE
Cleanup cluster/images/conformance/go-runner test data after test done

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
After UT (cluster/images/conformance/go-runner) run, the test data `tartest/out.tar.gz` should be removed. 

Reproduce:
```shell
[root@ecs-d8b6 kubernetes]# go test ./cluster/images/conformance/go-runner -run=TestTar        
ok  k8s.io/kubernetes/cluster/images/conformance/go-runner0.004s
[root@ecs-d8b6 kubernetes]# git status
# On branch master
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#cluster/images/conformance/go-runner/testdata/tartest/out.tar.gz
nothing added to commit but untracked files present (use "git add" to track)
```
It is the residues `cluster/images/conformance/go-runner/testdata/tartest/out.tar.gz`.

After cleanup, it looks like: 
```shell
[root@ecs-d8b6 kubernetes]# go test ./cluster/images/conformance/go-runner -run=TestTar
ok  k8s.io/kubernetes/cluster/images/conformance/go-runner0.005s
[root@ecs-d8b6 kubernetes]# git status
# On branch pr_cleanup_testtar_testdata
nothing to commit, working directory clean
```

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:
```release-note
NONE
```
[edit]: add release-note, none.

**Does this PR introduce a user-facing change?**:

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by neolit123** [comment]
thanks for the PR @RainbowMango 

/cc @johnSchnake 
for review as he authored the go-runner.

/approve
/hold
/ok-to-test

**Review by johnSchnake — APPROVED** [review]
/lgtm

**Comment by RainbowMango** [comment]
Thanks @neolit123 and @johnSchnake for quick response.

Seems we can continue now.

/hold cancel

**Comment by liggitt** [comment]
/hold

per [release-managers discussion](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1567084773002200), holding low-priority, non-milestone-targeted PRs in order to free merge pool bandwidth for 1.16-targeted PRs

feel free to unhold once there are no [lgtm+approve+green 1.16-targeted PRs](https://github.com/kubernetes/kubernetes/pulls?utf8=✓&q=is%3Apr+is%3Aopen+label%3Algtm+label%3Aapproved+milestone%3Av1.16+status%3Asuccess) remaining.

**Comment by RainbowMango** [comment]
@neolit123 @johnSchnake 
Please help to add lgtm back.

**Comment by neolit123** [comment]
@RainbowMango we are in code freeze and this PR doesn't have a `v1.16` milestone, which means it needs to wait for "code thaw" (10th of September).
i will leave it to @lachie83 and @johnSchnake to decided whether this is needed for release 1.16.

**Comment by lachie83** [comment]
@RainbowMango please [file an exception](https://github.com/kubernetes/sig-release/blob/master/releases/EXCEPTIONS.md) and tag @kacole2 and myself in the email if this should be considered for 1.16

**Comment by johnSchnake** [comment]
> Exceptions will be granted on the basis of risk and length of exception required.

IMO it is low priority, but all the criteria listed in the given link indicate an extension could be approved:
 - very well contained (to just a single test)
 - virtually 0 risk (just an tiny cleanup to a single test)
 - short time horizon (no extra time needed after the label is added. It is already good-to-go)

No reason to keep this out, at least one person wants this in; I don't see a reason to prohibit it.

**Pull request merged**
