### PR TITLE
enable docs and man page autogeneration for cloud-controller-manager

### PR DESCRIPTION
**Pull request by wlan0**
@chenopis These are docs for cloud-controller-manager. 

PTAL

### CODE REVIEW

**Comment by chenopis** [comment]
In terms of the content, docs lgtm.

**Comment by wlan0** [comment]
@chenopis What's needed to get a LGTM? Should I ping someone?

**Comment by chenopis** [comment]
Unfortunately, I'm not a maintainer of this repo, so I can't give the lgtm myself. Let's ping @thockin and @smarterclayton to see if they can do it.

**Comment by chenopis** [comment]
@dchen1107 Who else can do a tech review for this?

**Comment by cblecker** [comment]
@chenopis This looks good to me, but won't be able to auto merge right now because some of the paths are still defined as "old docs". I have https://github.com/kubernetes/test-infra/pull/3175 open to modify that. Hopefully if that gets merged, then this change can be approved and merged by the bot.

**Comment by chenopis** [comment]
@cblecker Ok, great! Thanks for the update.

**Comment by thockin** [comment]
manual merge

**Pull request merged**
