### PR TITLE
Migrate resource relevant e2e test files to sig scheduling

### PR DESCRIPTION
**Pull request by guangxuli**
**What this PR does / why we need it**:

Migrate resource relevant e2e test files to sig scheduling. Not fully sure whether these e2e files belong to sig-node or sig-scheduling, feel free to contact me if you have better solution.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Ref Umbrella issue #49161

**Special notes for your reviewer**:

**Release note**:
```release-note
none
```

### CODE REVIEW

**Comment by resouer** [comment]
Please fix release note, general lgtm

**Comment by guangxuli** [comment]
@resouer done.

**Comment by resouer** [comment]
kindly ping @enisoc for apporve

**Pull request merged**
