### PR TITLE
directly break the loop if condition map

### PR DESCRIPTION
**Pull request by guangxuli**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33155)

### CODE REVIEW

**Comment by quinton-hoole** [comment]
Thanks @guangxuli .

@k8s-bot federation gce e2e test this

**Comment by quinton-hoole** [comment]
This code looks good to me.  Will add LGTM label and merge as soon as the "Jenkins Federation GCE e2e" tests above have passed.

**Comment by guangxuli** [comment]
@quinton-hoole can you take a look this PR, It looks like the failure is not relative to this PR. thanks.

**Comment by quinton-hoole** [comment]
Yup, those test failures are known issues.  Fixes for them are in #33502.  I'm happy to merge this PR in the mean time.

**Comment by nikhiljindal** [comment]
@k8s-bot gci gce e2e test this

**Pull request merged**
