### PR TITLE
Autoscaling: advance v2 as the preferred API version over v1

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind api-change

#### What this PR does / why we need it:
According to https://kubernetes.io/docs/reference/using-api/deprecation-policy/:
> Rule #4b: The "preferred" API version and the "storage version" for a given group may not advance until after a release has been made that supports both the new version and the previous version  

We may have forgotten to do this in v1.24, and this PR tries to advance v2 as the preferred API version over v1.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/lgtm cancel

needs rebase @SataQiu

**Comment by SataQiu** [comment]
Thanks @dims , the code was rebased.

**Comment by dims** [comment]
/lgtm
/approve

reapplying lgtm after rebase

**Comment by sftim** [comment]
My suggestion for the changelog entry:
```markdown
For the `autoscaling` API group, mark the v2 APIs as preferred (was previously v1)
```

**Comment by liggitt** [comment]
I actually think this does not need a release note, the change is not user facing (the v2 REST API was already preferred over v1, this is talking about the etcd storage version)

**Comment by sftim** [comment]
OK! Even better.

**Pull request merged**
