### PR TITLE
Automated cherry pick of #58547: Send correct resource version for delete events from watch

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #58547 on release-1.9.

#58547: Send correct resource version for delete events from watch

### CODE REVIEW

**Comment by justinsb** [comment]
(looking into why this one failed kops)

**Comment by justinsb** [comment]
I accidentally flipped 1.9 to default to stretch, will default it back to jessie until we get that e2e test sorted out: https://github.com/kubernetes/kops/pull/4309

**Comment by mbohlool** [comment]
@liggitt looks good for cherrypick. can you make the release note brief if possible?

**Comment by liggitt** [comment]
abbreviated it a little

**Pull request merged**
