### PR TITLE
Automated cherry pick of #67743: Support extra prune resources in kube-addon-manager.

### PR DESCRIPTION
**Pull request by Random-Liu**
Cherry pick of #67743 on release-1.11.

#67743: Support extra prune resources in kube-addon-manager.

### CODE REVIEW

**Comment by Random-Liu** [comment]
https://github.com/kubernetes/kubernetes/pull/68489 is created. I think we can get this in now.

**Review by MrHohn — APPROVED** [review]
/lgtm

**Comment by foxish** [comment]
Can you please add some more details about the bug that this fixes?

**Comment by foxish** [comment]
based on discussion offline - looks like it prevents a bad state in cluster when using custom admission webhooks.

**Pull request merged**
