### PR TITLE
Switch COS image to m81.

### PR DESCRIPTION
**Pull request by cheftako**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Switching to the latest COS LTS line.

**Which issue(s) this PR fixes**:
Fixes # N/A

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
NONE
```

### CODE REVIEW

**Comment by oxddr** [comment]
/hold

There was an issue with recent gce5000 test. Let me understand it first before merging this change.

**Comment by oxddr** [comment]
The issue with `gce-master-scale-performance` seemed to be infrastructure, but since we don't have signal from the test, let's wait for the next, hopefully green run.

**Comment by cheftako** [comment]
> The issue with `gce-master-scale-performance` seemed to be infrastructure problem, but since we don't have signal from the test, let's wait for the next, hopefully green run.

Looks like there were some flaky tests but everything is green now.

**Comment by wojtek-t** [comment]
Cancelling hold - the last run finished successfully.
/hold cancel

**Pull request merged**
