### PR TITLE
add 'kubectl get all' command specification

### PR DESCRIPTION
**Pull request by ZP-AlwaysWin**
**What type of PR is this?**

> /kind bug
> /kind cleanup

**What this PR does / why we need it**:

I think we need this help manual, otherwise we can't get all the resources in the namespace clearly.

**Which issue(s) this PR fixes**:
Ref [#82979 ](https://github.com/kubernetes/kubernetes/issues/82979)

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```
None
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/ok-to-test
/kind cleanup

**Comment by pavgup** [comment]
This looks great and I'm a little embarrassed I didn't do this myself. Thanks for adding this example, here's hoping it's merged.

**Comment by liggitt** [comment]
Thanks for the PR, but this was intentionally removed from documentation due to wide confusion about it. See https://github.com/kubernetes/kubernetes/issues/82979#issuecomment-534340121

/close

**Pull request closed without merging**
