### PR TITLE
Update version of GLBC controller to 1.4.0. Switch managed certificates alpha feature to on by default, switch backend config feature to on.

### PR DESCRIPTION
**Pull request by krzykwas**
/sig network

/kind feature

This PR updates version of GLBC controller to 1.4.0 and switches managed certificates alpha feature to on by default, and switches backend config feature to on.

```release-note
Update version of GLBC controller to 1.4.0. Switch managed certificates alpha feature to on by default. Switch backend config feature to on.
```

### CODE REVIEW

**Comment by rramkumar1** [comment]
@krzykwas This looks fine. Before we approve, can you make sure that this yaml deploys properly?

**Comment by krzykwas** [comment]
I added also a definition of ManagedCertificate CRD

**Comment by krzykwas** [comment]
I verified that yaml deploys and it is possible to get a managed certificate in a cluster with Ingress 1.4.0 using the CRD in k8s/k8s.

**Pull request closed without merging**
