### PR TITLE
CHANGELOG-1.19.md: Fix Spelling error about [function]

### PR DESCRIPTION
**Pull request by heqg**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
CHANGELOG-1.19.md: Fix Spelling error about [function]

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

```release-note
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Comment by heqg** [comment]
/assign @liggitt
can you help me to review or approve this pr ?
If it will be merged, it is much better.
Thank you very much.

**Comment by liggitt** [comment]
Please combine into https://github.com/kubernetes/kubernetes/pull/97519#issue-comment-box

**Comment by justaugustus** [comment]
Approving since https://github.com/kubernetes/kubernetes/pull/97519 was closed.

Echoing Elana in https://github.com/kubernetes/kubernetes/pull/97709#issuecomment-759838487 and further raising awareness about our policy on [trivial edits](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits):

## Trivial Edits

Each incoming Pull Request needs to be reviewed, checked, and then merged.

While automation helps with this, each contribution also has an engineering cost.
Therefore it is appreciated if you do NOT make trivial edits and fixes, but
instead focus on giving the entire file a review.

If you find one grammatical or spelling error, it is likely there are more in
that file, you can really make your Pull Request count by checking the formatting,
checking for broken links, and fixing errors and then submitting all the fixes
at once to that file.

**Some questions to consider:**

* Can the file be improved further?
* Does the trivial edit greatly improve the quality of the content?

/lgtm
/approve
cc: @wilsonehusin

**Comment by heqg** [comment]
> Approving since #97519 was closed.
> 
> Echoing Elana in [#97709 (comment)](https://github.com/kubernetes/kubernetes/pull/97709#issuecomment-759838487) and further raising awareness about our policy on [trivial edits](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits):
> 
> ## Trivial Edits
> Each incoming Pull Request needs to be reviewed, checked, and then merged.
> 
> While automation helps with this, each contribution also has an engineering cost.
> Therefore it is appreciated if you do NOT make trivial edits and fixes, but
> instead focus on giving the entire file a review.
> 
> If you find one grammatical or spelling error, it is likely there are more in
> that file, you can really make your Pull Request count by checking the formatting,
> checking for broken links, and fixing errors and then submitting all the fixes
> at once to that file.
> 
> **Some questions to consider:**
> 
> * Can the file be improved further?
> * Does the trivial edit greatly improve the quality of the content?
> 
> /lgtm
> /approve
> cc: @wilsonehusin

Since this pr is submitted earlier, so, similar problems still exist. 
then, I will pay more attention in the future.

**Pull request merged**
