### PR TITLE
chore: move the scheduler internal components out of internal dir

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

In Golang, directories named `internal` has a special role; If you put implementation under /internal, you can import them only within the go module, but cannot import them from other repositories.
https://go.dev/doc/go1.4#internalpackages

We currently have some implementation in [/pkg/scheduler/internal](https://github.com/kubernetes/kubernetes/tree/master/pkg/scheduler/internal), and it sometimes makes testing in other repositories difficult.

This PR moves the scheduler internal components out of internal dir.
context: https://kubernetes.slack.com/archives/C09TP78DV/p1724422553018969

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

I named it `backend`, but the idea of a better name is welcome.
Or, maybe we should just move them to /pkg/scheduler?

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sanposhiho** [comment]
/hold

Make sure it's approved by the approver.

**Comment by alculquicondor** [comment]
`backend` sgtm.

@Huang-Wei ?

**Pull request merged**
