### PR TITLE
WIP: DEBUG DO NOT MERGE

### PR DESCRIPTION
**Pull request by bobbypage**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bobbypage** [comment]
Capturing failure

> @bobbypage: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-kubernetes-dependencies	[c7059a6](https://github.com/kubernetes/kubernetes/commit/c7059a6ae0abbc6074f48998857b641bdb67280d)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/109608/pull-kubernetes-dependencies/1517311086099959808)	true	`/test pull-kubernetes-dependencies`
> pull-kubernetes-node-e2e-containerd	[c7059a6](https://github.com/kubernetes/kubernetes/commit/c7059a6ae0abbc6074f48998857b641bdb67280d)	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/109608/pull-kubernetes-node-e2e-containerd/1517311086393561088/)	true	`/test pull-kubernetes-node-e2e-containerd`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=109608). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Abobbypage). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

**Comment by bobbypage** [comment]
Very interesting finding from the last failure that I think shows why the network stats is null.

In the run https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/109608/pull-kubernetes-node-e2e-containerd/1517311086393561088/ , `stats-busybox-0` had network stats, but `stats-busybox-1` did not have network stats.

```
pod name: stats-busybox-0
pod uid: 55731d83-2831-4ae9-9b3e-37149381f2a1
pod sandbox id: 3c98234d8d43b92f78548d9ba24cfa35a30495198b7d6adb8f1a40ccbcb451ef
```

Has the following log:


```
122:kubelet.log:I0422 01:28:36.600730    1206 handler.go:106] ruiwen-zhao: Fetching stats for container: /kubepods/burstable/pod55731d83-2831-4ae9-9b3e-37149381f2a1/3c98234d8d43b92f78548d9ba24cfa35a30
495198b7d6adb8f1a40ccbcb451ef h.pid: 6124
```

notice `h.pid` is != 0 

and network stats returned:

```
53:kubelet.log:I0422 01:28:36.600814    1206 handler.go:132] ruiwen-zhao: Trying to add network stats for container from proc: /kubepods/burstable/pod55731d83-2831-4ae9-9b3e-37149381f2a1/3c98234d8d43b
92f78548d9ba24cfa35a30495198b7d6adb8f1a40ccbcb451ef. netStats: [{Name:eth0 RxBytes:446 RxPackets:5 RxErrors:0 RxDropped:0 TxBytes:558 TxPackets:7 TxErrors:0 TxDropped:0}], err: <nil>
```

In the bad case:

```
pod name: stats-busybox-1
pod uid: 0172852c-4762-486f-ad90-dd50d337cd5a
pod sandbox id: b730207b7b7c21caca8e3e1a9c4e17f85b9cd1dd45a700b19b7e82dc0cbe2f2b


```
120:kubelet.log:I0422 01:28:35.855694    1206 handler.go:106] ruiwen-zhao: Fetching stats for container: /kubepods/burstable/pod0172852c-4762-486f-ad90-dd50d337cd5a/b730207b7b7c21caca8e3e1a9c4e17f85b9
cd1dd45a700b19b7e82dc0cbe2f2b h.pid: 0
```

`h.pid` is zero. 

If `h.pid` is zero, we don't fetch network stats - https://github.com/kubernetes/kubernetes/blob/f0791b50143856177878e21bb44beb5e3e36cc78/vendor/github.com/google/cadvisor/container/libcontainer/handler.go#L120-L123

**Comment by bobbypage** [comment]
Just like in https://github.com/kubernetes/kubernetes/pull/109371#issuecomment-1105863506, I see the same containerd error:

```
3515:Apr 22 01:28:35 tmp-node-e2e-8b869857-cos-97-16919-29-16 containerd[659]: time="2022-04-22T01:28:35.847444336Z" level=error msg="get state for b730207b7b7c21caca8e3e1a9c4e17f85b9cd1dd45a700b19b7e82dc0cbe2f2b" error="context deadline exceeded: unknown"
```

**Comment by mikebrow** [comment]
> Just like in [#109371 (comment)](https://github.com/kubernetes/kubernetes/pull/109371#issuecomment-1105863506), I see the same containerd error:
> 
> ```
> 3515:Apr 22 01:28:35 tmp-node-e2e-8b869857-cos-97-16919-29-16 containerd[659]: time="2022-04-22T01:28:35.847444336Z" level=error msg="get state for b730207b7b7c21caca8e3e1a9c4e17f85b9cd1dd45a700b19b7e82dc0cbe2f2b" error="context deadline exceeded: unknown"
> ```

let's see.. we create a new 2s context timeout (unless the config toml has a shorter one) 
```
[timeouts]
  "io.containerd.timeout.task.state" = "2s"

func getProcessState(ctx context.Context, p runtime.Process) (*task.Process, error) {
	ctx, cancel := timeout.WithContext(ctx, stateTimeout)
	defer cancel()

	state, err := p.State(ctx)
	if err != nil {
		if errdefs.IsNotFound(err) {
			return nil, err
		}
		log.G(ctx).WithError(err).Errorf("get state for %s", p.ID())
	}
```
This works via ttrpc to the shim.. 

Noting from my code skim where state is returned.. there exist mux semaphores that may affect the ability for the state to be returned until other operations have completed, thus resulting in a context deadline (looks to me those also have 2second default context timeouts) @AkihiroSuda @fuweid @dmcgowan Thoughts?

**Comment by SergeyKanzhelev** [comment]
Can this comment be the cause:

https://github.com/google/cadvisor/blob/808d2f5cb5ef808348cfab250b11ecd6e2400e8d/container/containerd/handler.go#L90

I cannot find any place we retry handler creation, but I don't know code well enough there

**Comment by bobbypage** [comment]
pushed another revision with more logs around response from containerd to dig deeper into why sometimes why cAdvisor returns a zero pid...

**Comment by SergeyKanzhelev** [comment]
> pushed another revision with more logs around response from containerd to dig deeper into why sometimes why cAdvisor returns a zero pid from task api

To add more details here - one of the theories is that cAdvisor reads the Task status just before the process has started (has a pid), but right after the task was created (handler is being created). In this case pid will indeed be zero and we will see this effect.

BTW, @bobbypage do you think this behavior may account to other failures we see intermittedly, for example with the missing memory stats that we see here: https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-ubuntu?

**Comment by bobbypage** [comment]
> BTW, @bobbypage do you think this behavior may account to other failures we see intermittedly, for example with the missing memory stats that we see here: https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-ubuntu?

I'm not sure if it's related... I believe for memory stats, cAdvisor fetches them using the cgroup name (see https://github.com/kubernetes/kubernetes/blob/f02682c628c530219966a00ae002d799f0d813dc/vendor/github.com/google/cadvisor/container/libcontainer/handler.go#L97 and https://github.com/kubernetes/kubernetes/blob/f02682c628c530219966a00ae002d799f0d813dc/vendor/github.com/google/cadvisor/container/libcontainer/handler.go#L920) and it does not need the pid. The pid is mostly required only for network stats see [this block](https://github.com/kubernetes/kubernetes/blob/f02682c628c530219966a00ae002d799f0d813dc/vendor/github.com/google/cadvisor/container/libcontainer/handler.go#L120-L168)

**Comment by bobbypage** [comment]
See last run: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/109608/pull-kubernetes-node-e2e-containerd/1517607023825391616/

Last run with updated logs did not fail the test. However, it does prove we do hit some cases where we get a zero pid from containerd task api:

```
I0422 21:03:34.769830    1204 client.go:121] ruiwen-zhao: Got zero pid from containerd task. container id: 2ec4d59c8e7e757bde2b4470761fb846cf3866169e5ed33063d03b77910ebb70 , pid: 0, status: UNKNOWN
I0422 21:03:34.769853    1204 handler.go:130] ruiwen-zhao: creating containerd handler name: /kubepods/besteffort/pod9d68027e-0312-4dee-8cc9-5ea0a0aec412/2ec4d59c8e7e757bde2b4470761fb846cf3866169e5ed33063d03b77910ebb70, id: 2ec4d59c8e7e757bde2b4470761fb846cf3866169e5ed33063d03b77910ebb70, with taskPid: 0
```

also see the containerd error:

```
Apr 22 21:03:34 tmp-node-e2e-495ffaef-cos-97-16919-29-16 containerd[658]: time="2022-04-22T21:03:34.768703725Z" level=error msg="get state for 2ec4d59c8e7e757bde2b4470761fb846cf3866169e5ed33063d03b77910ebb70" error="context deadline exceeded: unknown"
```

**Comment by bobbypage** [comment]
We have this current logic for getting pid in cAdvisor from containerd: https://github.com/kubernetes/kubernetes/blob/f02682c628c530219966a00ae002d799f0d813dc/vendor/github.com/google/cadvisor/container/containerd/handler.go#L96-L110

However, it only retries on error. It seems like when we get a zero pid, there is no error returned from the task api, rather the pid is zero and task state is `UNKNOWN`. Since the pid is zero, we continue with creating the handler, and eventually we fail to get network stats since it requires a pid - https://github.com/kubernetes/kubernetes/blob/f0791b50143856177878e21bb44beb5e3e36cc78/vendor/github.com/google/cadvisor/container/libcontainer/handler.go#L120-L123

So one solution is to add retry if we get back `UNKNOWN` process status from containerd task api. However, I'm not sure if it's possible for a task always be in `UNKNOWN` status, for example a user container that exists on startup... So the retry logic may need to retry a few times on `UNKNOWN`, but still proceed with creating the handler even if we don't get a pid (so we can get rest of metrics, like cpu, memory, etc).

For k8s usecase, we don't actually need the pid for all containers, only for the pod sandbox since we only fetch network stats from the pod sandbox.

**Comment by SergeyKanzhelev** [comment]
> /pull-kubernetes-node-e2e-containerd

Did we break the robot? Test doesn't seems to be running

**Comment by dims** [comment]
@bobbypage testing your theory here: https://github.com/kubernetes/kubernetes/pull/109628/files

**Comment by dims** [comment]
folks,
the theory was good! good job getting to the bottom of the problem. 

what's left to be done is logged here: https://github.com/kubernetes/kubernetes/issues/109082#issuecomment-1107850050

**Pull request closed without merging**
