### PR TITLE
Wait for post-hooks to run before checking the healthz output

### PR DESCRIPTION
**Pull request by mfojtik**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:

Under some circumstances (when starting go routines is slow?) this test can fail as the result will return `[-]poststarthook/delegate-post-start-hook` failed (reason withheld). This is because we start checking the output before the hook is ran.

Sample failure:

```
expected [+]ping ok
        [+]log ok
        [-]wrapping-health failed: reason withheld
        [-]delegate-health failed: reason withheld
        [+]poststarthook/generic-apiserver-start-informers ok
        [+]poststarthook/delegate-post-start-hook ok
        [+]poststarthook/wrapping-post-start-hook ok
        healthz check failed
        , got [+]ping ok
        [+]log ok
        [-]wrapping-health failed: reason withheld
        [-]delegate-health failed: reason withheld
        [+]poststarthook/generic-apiserver-start-informers ok
        [-]poststarthook/delegate-post-start-hook failed: reason withheld
        [+]poststarthook/wrapping-post-start-hook ok
        healthz check failed
```

With this change we will wait until the hooks ran and only after that check the healthz endpoint result.

```release-note
NONE
```

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]

**Review by soltysh — APPROVED** [review]
/lgtm
/retest

**Comment by soltysh** [comment]
Not sure why the bot didin't pick up the approval from @sttts, adding the label manually.

**Pull request merged**
