### PR TITLE
Remove useless code in api/v1 conversion function.

### PR DESCRIPTION
**Pull request by xingzhou**
Remove useless code in api/v1 pod v1 to api conversion function.

Found this issue while investigating #47264
**Release note**:
```
None
```

### CODE REVIEW

**Review by luxas — COMMENTED** [review]
I don't see anything wrong with this code, LGTM I guess.

However, I want others to verify as well

**Comment by luxas** [comment]
@k8s-bot ok to test

**Comment by xingzhou** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by xingzhou** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by caesarxuchao** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by xingzhou** [comment]
@caesarxuchao @luxas @rootfs, rebased the code to latest master, PTAL, thanks for your time!

**Comment by caesarxuchao** [comment]
Still lgtm.

**Comment by caesarxuchao** [comment]
@erictune could you help approve the change? Thanks.

**Pull request closed without merging**
