### PR TITLE
fix Security Context should run with an image specified user ID

### LINKED ISSUE #82816: [Failing Test] Security Context should run with an image specified user ID
**Which jobs are failing**:
ci-kubernetes-node-kubelet-orphans

**Which test(s) are failing**:
[k8s.io] Security Context should run with an image specified user ID [It]
[k8s.io] Security Context When creating a container with runAsNonRoot should not run with an explicit root user ID [LinuxOnly] [It]

**Since when has it been failing**:

**Testgrid link**:
https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-orphans

**Reason for failure**:
"gcr.io/kubernetes-e2e-test-images/nonroot:1.0" is not in the white list

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by zouyee**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
Add "gcr.io/kubernetes-e2e-test-images/nonroot:1.0" into the white list

**Which issue(s) this PR fixes**:

Fixes #82816

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/cc @odinuge @alejandrox1 @oomichi @tallclair

### CODE REVIEW

**Review by odinuge — COMMENTED** [review]
Thanks for looking into this!

This looks good to me, but there is also another PR https://github.com/kubernetes/kubernetes/pull/82155/files adding it to the image list `test/e2e/common/util.go`. Both approaches should work, and I am not sure what the best approach is. Defering that to someone from sig-testing.

/cc @oomichi

**Comment by oomichi** [comment]
One of example of the failures is https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-orphans/1176059029915439107
The error message is 
```
[k8s.io] Security Context When creating a container with runAsNonRoot should run with an image specified user ID expand_less
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/security_context.go:145 Image "gcr.io/kubernetes-e2e-test-images/nonroot:1.0" is not in the white list, consider adding it to CommonImageWhiteList in test/e2e/common/util.go or NodeImageWhiteList in test/e2e_node/image_list.go Expected     <bool>: false to be true /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/pods.go:210
```
And the corresponding issue of this PR is for fixing `[Failing Test] Security Context should run with an image specified user ID` which is in `test/e2e/common/security_context.go` not e2e node test.
So I guess `CommonImageWhiteList in test/e2e/common/util.go` is good place to fix the issue.

**Comment by oomichi** [comment]
Thanks for updating

/lgtm

**Comment by zouyee** [comment]
@tallclair gentle ping

**Comment by liggitt** [comment]
this looks identical to https://github.com/kubernetes/kubernetes/pull/82155

/assign @random-liu

**Pull request merged**
