### PR TITLE
Automated cherry pick of #79029: Add missing API groups to compatibility test

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #79029 on release-1.15.

#79029: Add missing API groups to compatibility test

### CODE REVIEW

**Comment by smarterclayton** [comment]
/approve

This needs to be in 1.15 at some point, but agree is not release blocking

**Comment by liggitt** [comment]
this is ready to merge now (completes API compat unit tests against the 1.15 release branch)

**Comment by liggitt** [comment]
rebased on v1.15.0 to verify this passed on the release tag

**Comment by liggitt** [comment]
cc @kubernetes/patch-release-team 
this is a test-only change that would good to get merged to ensure compatibility for 1.15.x patch releases

**Pull request merged**
