### PR TITLE
Split the version metric out to its own package

### PR DESCRIPTION
**Pull request by krousey**
This PR breaks a client dependency on prometheus. Combined with #30638, the client will no longer depend on these packages.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30902)

### CODE REVIEW

**Comment by caesarxuchao** [comment]
> the client will no longer depend on these packages

By "client" do you mean the restclient?

**Comment by caesarxuchao** [comment]
LGTM. Thanks!

**Comment by krousey** [comment]
@caesarxuchao Yes. I meant restclient.

**Comment by krousey** [comment]
Just a rebase.

**Comment by krousey** [comment]
@k8s-bot unit test this issue: #31079

**Pull request merged**
