### PR TITLE
Add self to sig-instrumentation leads

### PR DESCRIPTION
**Pull request by richabanker**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Adding myself to sig-instrumentation leads

#### Which issue(s) this PR fixes:

Issue link #https://github.com/kubernetes/community/issues/8149

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by thockin** [comment]
Congrats!

/lgtm
/approve

**Pull request merged**
