### PR TITLE
remove unused milestone-maintainers OWNERS_ALIASES entry

### PR DESCRIPTION
**Pull request by tpepper**
The k/k top level OWNERS_ALIASES entry for milestone-maintainers
is unused.  Currently everything around milestone maintanence
continues to happen via the kubernetes-milestone-maintainers GitHub
group (see: https://github.com/kubernetes/sig-release/issues/241 for
similar cleaning up effort there).  The hope is in the future this will
move to in repo yaml and Peribolos, but in the meantime this duplicated
and unused list only adds to confusion.

Signed-off-by: Tim Pepper <tpepper@vmware.com>

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
iirc, one concern around github groups was lack of history / audibility. was this alias intended as the authoritative source (albeit manual) for the github group membership?

**Comment by cblecker** [comment]
I don't think the list has been kept up to date. Criteria for membership is here: https://github.com/kubernetes/sig-release/tree/master/release-team#milestone-maintainers

**Comment by justaugustus** [comment]
Thanks Tim!

/lgtm
/approve

**Comment by tpepper** [comment]
For the historical record: regardless of possible past intent, this alias in tree and the GitHub team were very much NOT kept in sync, which only makes for confusion.  I look forward to a Peribolos future where we the authoritative info in tree, but in the meantime it was confusion.

**Pull request merged**
