### PR TITLE
Check claimRef UID when processing a recycled PV, take 2

### PR DESCRIPTION
**Pull request by ncdc**
Reorder code a bit so it doesn't allow a case where you get some error other than "not found"
combined with a non-nil Claim.

Add test case.

cc @kubernetes/rh-cluster-infra @kubernetes/rh-storage @liggitt

### CODE REVIEW

**Comment by ncdc** [comment]
unit/int tests are 404

@k8s-bot unit this this issue: #IGNORE

**Comment by markturansky** [comment]
LGTM

**Comment by ncdc** [comment]
@k8s-bot unit test this issue: #23533

**Comment by ncdc** [comment]
@k8s-bot unit test this issue: #23361

**Comment by ncdc** [comment]
cc @kubernetes/sig-storage

**Comment by swagiaal** [comment]
LGTM

**Pull request merged**
