### PR TITLE
kube-up: install updates & reboot automatically on boot

### PR DESCRIPTION
**Pull request by justinsb**
We run unattened-upgrades manually, and then reboot automatically if we
find /var/run/reboot-required; then we check if any services need
restarting and restart them automatically using the needrestart tool.

This should mean we don't _have_ to build new images on every security
update, though we can do so to avoid a reboot.

Issue #21382

### CODE REVIEW

**Comment by justinsb** [comment]
@zmerlynn What do you think?  Would this avoid needing to build an image on every security update?  Is it just too dangerous to do on boot (even with the safety valves)?  Would you rather prove it first on AWS?  Or should we just spin a new image regularly?

(so many questions!)

**Comment by justinsb** [comment]
@k8s-bot test this github flake #21467

**Comment by zmerlynn** [comment]
LGTM

**Comment by justinsb** [comment]
@zmerlynn I should pull this out of GCE and make it AWS only, right?

**Comment by justinsb** [comment]
Removing LGTM for now

**Comment by zmerlynn** [comment]
@justinsb: We don't set `AUTO_UPGRADE` on GCE, do we? It looked like the way you had it factored you were just adding code for AWS anyways.

**Comment by zmerlynn** [comment]
Oh! I can't read, it defaults to `auto`.

**Comment by zmerlynn** [comment]
Sorry, my previous review hinged on a misreading of `[[ "${AUTO_UPGRADE:-auto}" != "no" ]]`

You can:
* leave this in, default it to `no`, and send AWS down the `AUTO_UPGRADE=auto` explicit path
* move it entirely to AWS

**Comment by justinsb** [comment]
@zmerlynn great suggestion.  I left it in the GCE path, but defaulted it off, so that GCE users that do want it can still have it.

I also changed from auto/no to true/false for consistency and sanity.

**Comment by justinsb** [comment]
@zmerlynn what do you think?  This is blocking closing a P0 issue for 1.2, so I think it would make some people happy this afternoon if we can get it merged!

**Comment by justinsb** [comment]
Actually I think it's only a P1... so would only bring people some contentment.

**Comment by zmerlynn** [comment]
LGTM

**Pull request merged**
