### PR TITLE
Automated cherry pick of #110110: Fix issue that Audit Server could not correctly encode

### PR DESCRIPTION
**Pull request by sxllwx**
Cherry pick of #110110 on release-1.23.

#110110: Fix issue that Audit Server could not correctly encode

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm
/approve
/retest

@kubernetes/release-managers - for cherrypick approval

**Comment by sxllwx** [comment]
@xmudrii PTAL thx.

**Comment by Verolop** [comment]
@sxllwx looks like this needs a rebase (and approval) after https://github.com/kubernetes/kubernetes/pull/113967 was merged. Thanks!

**Comment by sxllwx** [comment]
> @sxllwx looks like this needs a rebase (and approval) after #113967 was merged. Thanks!

Thank you for your guidance.

Already rebase, PTAL

**Review by xmudrii — APPROVED** [review]
Discussed on Slack: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1673882647806869

/lgtm
/approve
/release-note-none
(from the parent PR)

**Pull request merged**
