### PR TITLE
Improve retry logic in services e2e test.

### PR DESCRIPTION
**Pull request by ghost**
- Use standard wait.Poll retry library rather than arbitrary loop with sleeps (which was taking 100*10 seconds to fail, which is plain silly).
- Use Logf rather than Printf to be more consistent.

### CODE REVIEW

**Comment by mbforbes** [comment]
LGTM with a quick pass but passing to @zmerlynn for a second set of eyes

**Comment by zmerlynn** [comment]
LGTM

**Comment by mbforbes** [comment]
Cool—e2e runs look good, @quinton-hoole ?

**Comment by quinton-hoole** [comment]
Yup, e2e passed.  Thanks for checking.

**Comment by mbforbes** [comment]
NP! Thanks for the change!

**Pull request merged**
