### PR TITLE
Use kube-dns:1.11.0

### PR DESCRIPTION
**Pull request by sadlil**
Use [kube-dns:1.11.0](https://github.com/kubernetes/dns/releases/tag/1.11.0)

With: kubernetes/dns#25
Fixes kubernetes/kubernetes#26752
Fixes kubernetes/kubernetes#33470

@bowei @thockin

### CODE REVIEW

**Comment by GheRivero** [comment]
looks good to me

**Comment by bowei** [comment]
can you fix all of the references? git grep 'kube-dns:1\.' should show

**Comment by sadlil** [comment]
@bowei updated all references.

**Review by pires — APPROVED** [review]
lgtm

**Comment by pires** [comment]
@sadlil sorry for breaking your PR. @luxas PTAL this is a trivial change.

**Comment by TamalSaha** [comment]
@sadlil @bowei I have rebased the pr.

**Comment by kargakis** [comment]
Can you guys squash the commits into one? Then I will tag it for merging.

**Comment by TamalSaha** [comment]
@kargakis , if you can squash and merge, please go ahead and do that. It is hard to keep up with various random changes affecting a PR. If you can't do that. please let me know. We can do that.

Also, fyi @thockin asked for a release note, https://github.com/kubernetes/dns/pull/25#issuecomment-272363779

**Comment by kargakis** [comment]
Added the release-note label, please squash into one, and I'll tag it

**Comment by TamalSaha** [comment]
@kargakis , squashed.

**Pull request merged**
