### PR TITLE
Collapse integration test storage setup onto actual storage config

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Deduplicates the places we set up api server storage. Would simplify changes like https://github.com/kubernetes/kubernetes/pull/77139

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
tentatively looks reasonable, but i'm not familiar enough with this code, we should probably assign another reviewer

**Comment by sttts** [comment]
Less custom test master plumbing is always good. We still have far too much of that. So this goes into the right direction.

We might want to look into more use of https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/testing/testserver.go#L76.

/lgtm

**Pull request merged**
