### PR TITLE
[kubeadm] skip cri detection for kubeadm token create

### LINKED ISSUE #1559: Fail to create token when multi CRI sockets exist
## Is this a BUG REPORT or FEATURE REQUEST?
BUG REPORT

Choose one: BUG REPORT or FEATURE REQUEST

## Versions

**kubeadm version** (use `kubeadm version`):
kubeadm version: &version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.0-alpha.2.323+b3a73f761f5b67", GitCommit:"b3a73f761f5b67f783d40a8b89dce47c5a015909", GitTreeState:"clean", BuildDate:"2019-05-07T06:02:57Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"archive", BuildDate:"2019-04-15T07:32:37Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=29250
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"

- **Kernel** (e.g. `uname -a`):
Linux 5.0.13-751.native #1 SMP Sun May 5 14:14:30 UTC 2019 x86_64 GNU/Linux
- **Others**:

## What happened?
When I run "kubeadm token create --print-join-command", it show error as below
```
Found multiple CRI sockets, please use --cri-socket to select one: /var/run/dockershim.sock, /var/run/crio/crio.sock
```
Actually, I have executed "kubeadm init --cri-socket=/var/run/crio/crio.sock" when setup cluster.

If I pass --cri-socket with "kubeadm token create --cri-socket=/var/run/crio/crio.sock", it show
```Error: unknown flag: --cri-socket```

## What you expected to happen?
show token created, maybe complete join command

## How to reproduce it (as minimally and precisely as possible)?
1) install crio plugin
2) kubeadm init --cri-socket=/var/run/crio/crio.sock
3) kubeadm token create --print-join-command

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
Add --cri-socket for kubeadm token create

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#1559

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by rosti — CHANGES_REQUESTED** [review]
Thanks for taking this one @SataQiu !
However this is not what we are looking for. In `token create` we don't do any CRI ops at all, so no need to detect it or to provide a command line switch either. To force skipping the detection, we need to do something like:
```
cfg.NodeRegistration.CRISocket = constants.DefaultDockerCRISocket
```

This needs to be done in `RunCreateToken` before the call to `LoadOrDefaultInitConfiguration`.
/hold

**Comment by rosti** [comment]
P.S. We should also add a comment to the fix, as to why we do that.
/priority important-longterm

**Comment by SataQiu** [comment]
ok, thanks. I will do it later.

**Comment by ereslibre** [comment]
While @rosti's suggestion will workaround the issue we probably want to revisit the root cause and eventually remove this bypassing workarounds.

I can have a look at that and potentially open a PR with a proposal if I get to something reasonable.

For the time being the workaround @rosti proposed SGTM.

**Comment by ereslibre** [comment]
/lgtm

Thank you @SataQiu.

**Review by neolit123 — COMMENTED** [review]
/lgtm
approve on @rosti 

do we have other commands affected by this issue?

**Review by rosti — APPROVED** [review]
Thanks @SataQiu !
/approve

**Comment by rosti** [comment]
@ereslibre the usual root cause for this is `InitConfiguration` being used for other non-`kubeadm init` related purposes. Hopefully some day we'll do enough iterations over the code base to fix all such instances, but until then, we have to do this sort of stuff.

**Comment by ereslibre** [comment]
> @ereslibre the usual root cause for this is InitConfiguration being used for other non-kubeadm init related purposes. Hopefully some day we'll do enough iterations over the code base to fix all such instances, but until then, we have to do this sort of stuff.

I wholeheartedly agree. In this specific instance though it looks like the only reason we use it is to generate the bootstrap token and just fill `cfg.BootstrapTokens = []kubeadmapiv1beta2.BootstrapToken{*bto.BootstrapToken}`.

That's what I meant with a refactor in this sense (at least for this specific case). It's probably not as simple as it seems, but it seems a bit of an overkill to create the whole init configuration to just fill the tokens with the fresh generated token. Then we just use the structure: `tokenphase.CreateNewTokens(client, internalcfg.BootstrapTokens)` (and in other places).

I will take a look if something can be done at least in this case, as said it probably looks easier than it really is :)

**Comment by rosti** [comment]
@ereslibre totally agree on that, unfortunately this is a backlog priority for now. If you do something there, I'll be happy to review it (this was a thorn in my eyes for a very long time).

**Pull request merged**
