### PR TITLE
docs: `-l/--selector` example for set-based requirements

### PR DESCRIPTION
**Pull request by rotsix**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

add an example of set-based requirement when using `-l/--selector` as it's a (less known) filtering capability: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#list-and-watch-filtering

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

Thanks :)

#### Does this PR introduce a user-facing change?

```release-note
Give example of set-based requirement for -l/--selector flag
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

None.

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/ok-to-test
/lgtm
/approve

**Comment by soltysh** [comment]
@rotsix thank you, I'm always happy to get more clarification from our `--help` docs :)

**Comment by rotsix** [comment]
Hey @soltysh, thanks a lot for that prompt review!

I'm glad it pleases you. For the story I asked ChatGPT if this option existed and it answered that _obviously_ I could do it. I didn't expect `-l` to handle this but here we are :)

**Pull request merged**
