### PR TITLE
fix formatting of md documents

### PR DESCRIPTION
**Pull request by ingvagabund**
*.md files in doc/man directory have some issues:
- some options are not correctly marked by **
- kube-proxy.md is missing space between # and NAME heading

### CODE REVIEW

**Comment by ingvagabund** [comment]
@eparis

**Comment by eparis** [comment]
ok to test

**Comment by eparis** [comment]
@ingvagabund I would love if you could find a way to un-revert the removal of the .1 man pages.  But this PR itself looks good.

**Comment by ingvagabund** [comment]
In order to generate man pages from md, go-md2man has to be installed on a system. go-md2man is not a dependency of kubernetes. Man pages need to be generated in a pre commit hook script which has to either install go-md2man on a system and run transformation. Or run transformation in a container that requires containerization tools. I don't want to replicate Mike Danese's job. Plus there is no assurance that format of md files is not going to change (e.g. options items) as Mike is going to update md files manually. At the moment additional script with 3 seds is neeed to transform md files into a form suitable for transformation. The script can change over time so it is more suitable to have it as a part of distro's spec file until Mike comes with its solution.

@mikedanese, when do you think man pages will be generated? Btw. can you keep formatting of md files as they are now? Without changing a structure of a list of options? The current format is:
\*[[:space:]]*\*\*--option=value**:[[:space:]]DESCRIPTION_OF_OPTION

**Comment by mikedanese** [comment]
I have a branch that autogens with cobra. I'm aiming to get this in for v1.0 (so next week or so). I REALLY want this to be autogenerated during run-gendoc.sh. If you have a different solution that generates everything (markdown and man) reasonably quickly during ./hack/run-gendoc.sh, I will happily review and get it into v1.0

**Comment by zmerlynn** [comment]
The doc changes look fine. @mikedanese - Do we want to take manual changes or just wait for auto-changes?

**Comment by mikedanese** [comment]
Let's LGTM this and we can see which get's in first.

**Comment by mikedanese** [comment]
Fyi #10594

**Pull request merged**
