### PR TITLE
Fix hack/update-api-reference-docs on master and (future) branches

### PR DESCRIPTION
**Pull request by sttts**
- update toplevel api object pattern in swagger doc script: the format of the `register.go` file was changed in https://github.com/kubernetes/kubernetes/pull/27168/commits/e3af3451c8445639c33644bbcbdc94da16968b87. This fixes the bleeding.
- make `hack/update-api-reference-docs.sh` independent from master during **container run**. Container build is still dependent on master, but container rebuilds never happen I guess on a branch.

A rebuild of `gcr.io/google_containers/gen-swagger-docs:v6` is necessary, plus a cherry-pick onto the v1.3 branch.

Fixes the symptoms of #27685 and makes sure future branches do not break again.

### CODE REVIEW

**Comment by sttts** [comment]
The actual root cause of the trouble is that we run scripts from HEAD accessing files from master. If we change the later, the former might get incompatible. Why is that necessary?

**Comment by ncdc** [comment]
FYI @smarterclayton

**Comment by caesarxuchao** [comment]
Thank you @sttts for the quick fix! LGTM.

**Comment by caesarxuchao** [comment]
I've pushed the v6 image.

**Comment by caesarxuchao** [comment]
Since the v6 image is pushed,  @sttts could you revert #27686 in this PR and see if the verification passes?

I'm removing the lgtm label, feel free to re-apply it if the test passes.

**Comment by sttts** [comment]
@caesarxuchao will do

**Comment by lavalamp** [comment]
Thanks!

**Comment by sttts** [comment]
@caesarxuchao I wonder whether it makes sense to move the top_level_models pattern out of the container, into the caller. Otherwise, we won't be able to reuse the container for v1.2.

**Comment by sttts** [comment]
Alternative of course: we create another 1.2-v6 for 1.2 with the right (old) pattern.

**Comment by caesarxuchao** [comment]
@sttts sorry, I don't see why it won't work with release 1.2, it seems to have the same pattern: https://github.com/kubernetes/kubernetes/blob/release-1.2/pkg/api/v1/register.go#L40

I agree in general moving the top_level_object pattern to the caller is preferable.

Also could you squash before merge? Thanks.

**Comment by sttts** [comment]
@caesarxuchao you are right. Didn't check 1.2's register.go.

Will squash.

**Comment by sttts** [comment]
Squashed. Will apply lgtm. When tests are green, it's ready to merge.

**Comment by sttts** [comment]
@caesarxuchao will stop for today. If anything is left to do, feel free to take over the PR.

**Comment by caesarxuchao** [comment]
Thanks @sttts!

**Comment by ncdc** [comment]
Looks like some sort of timeouts or other env issue in the node e2e. I don't have time to dig in right now, but let's see if another round of testing will pass...

@k8s-bot node e2e test this issue: #IGNORE

**Comment by david-mcmahon** [comment]
cc @david-mcmahon

**Comment by lavalamp** [comment]
I think we need to cherry-pick this into 1.2 to get the tests passing there again.

**Comment by fabioy** [comment]
@roberthbailey Sorry, I think this is the CL that we need in 1.2 to fix "test-go-release-1.2".

**Comment by roberthbailey** [comment]
cherry pick approved for 1.2 branch.

**Comment by roberthbailey** [comment]
This was cherry picked to the 1.2 branch in https://github.com/kubernetes/kubernetes/pull/27817 so I'm removing the cherrypick-candidate label.

**Pull request merged**
