### PR TITLE
OWNERS: add pohly as SIG Instrumentation review and component-base/logs approver

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

SIG Instrumentation needs more reviewers.

#### Special notes for your reviewer:

I've helped review PRs already, mostly around structured logging for SIG Instrumentation and various areas for SIG Storage. I'm a co-chair of the structured logging working group.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/cc @ehashman @serathius

### CODE REVIEW

**Comment by aojea** [comment]
+1

**Comment by serathius** [comment]
/lgtm
/hold
For get approval from @ehashman as representative of SIG Instrumentation

**Review by ehashman — COMMENTED** [review]
/lgtm
/approve

/assign @logicalhan 
for final approval

**Comment by ehashman** [comment]
/hold cancel

/assign @liggitt 
for top-level

**Pull request merged**
