### PR TITLE
Added e2e test to verify zone support across datacenters

### PR DESCRIPTION
**Pull request by sandeeppsunny**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This change adds tests which verify multi-zone volume provisioning across different Datacenters in a single VC. The testbed environment for multi-zone support is now updated to spread kubernetes nodes across multiple datacenters. The testbed description has been updated accordingly. 

Updated jenkins automation script link : https://github.com/sandeeppsunny/k8s-jenkins-automation-scripts/blob/k8s-jenkins-testsetup/jobs-scripts/run-zone-tests.sh

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
These tests cover the changes in pull request #75187
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by divyenpatel — APPROVED** [review]

**Comment by cchengleo** [comment]
LGTM

**Comment by gnufied** [comment]
feel free to fix the conflict and re-add lgtm.

/approve

**Pull request merged**
