### PR TITLE
kubeadm: move defaulting to the api group

### PR DESCRIPTION
**Pull request by mikedanese**
ref #35796

@pires @kubernetes/sig-cluster-lifecycle

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36025)

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot node e2e test this

**Comment by pires** [comment]
I'm okay with these commits being contributed to Google.

It seems I was really close but that's not enough for the bot. Thanks @mikedanese!

**Comment by mikedanese** [comment]
@k8s-bot node e2e test this

**Comment by luxas** [comment]
Thank you @mikedanese!

**Comment by luxas** [comment]
@k8s-bot verify test this

**Pull request merged**
