### PR TITLE
Update getting-started for docker on 1.0 branch.

### PR DESCRIPTION
**Pull request by thockin**
This is unfortunately manual.  We should find a way to auto-update things liek this as part of cutting a release.  @ihmccreery for thoughts on getting it into that process.

### CODE REVIEW

**Comment by thockin** [comment]
once this is in I can re-import docs to gh-pages.

**Comment by thockin** [comment]
Fixes #16087

**Comment by ihmccreery** [comment]
The hyperkube docs should be covered in #11751.

The `etcd` references should have been changed when we bumped that dependency, no?

**Comment by thockin** [comment]
@k8s-bot test this please

**Comment by aanm** [comment]
@thockin Shouldn't you change this https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/master.sh#L30 and this https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/worker.sh#L30 accordingly? :-)

**Comment by brendandburns** [comment]
LGTM.

**Pull request merged**
