### PR TITLE
Update github.com/prometheus/{client_golang,client_model,common}

### PR DESCRIPTION
**Pull request by bmcustodio**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Part of https://github.com/kubernetes/kubernetes/issues/69776 involves updating `github.com/prometheus/{client_golang,client_model,common}`. This is my take on that one.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
N/A

**Special notes for your reviewer**:

I ran the following commands against `master`:

```
hack/run-in-gopath.sh hack/godep-restore.sh
hack/run-in-gopath.sh bash -c 'rm -rf $GOPATH/src/github.com/prometheus/client_golang'
hack/run-in-gopath.sh go get -d github.com/prometheus/client_golang/...
hack/run-in-gopath.sh bash -c 'git -C $GOPATH/src/github.com/prometheus/client_golang checkout v0.9.0'
hack/run-in-gopath.sh bash -c 'rm -rf $GOPATH/src/github.com/prometheus/client_model'
hack/run-in-gopath.sh go get -d github.com/prometheus/client_model/...
hack/run-in-gopath.sh bash -c 'git -C $GOPATH/src/github.com/prometheus/client_model checkout 5c3871d'
hack/run-in-gopath.sh bash -c 'rm -rf $GOPATH/src/github.com/prometheus/common'
hack/run-in-gopath.sh go get -d github.com/prometheus/common/...
hack/run-in-gopath.sh bash -c 'git -C $GOPATH/src/github.com/prometheus/common checkout 7e9e6ca'
hack/run-in-gopath.sh hack/godep-save.sh
hack/run-in-gopath.sh hack/update-staging-godeps.sh
```

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/sig instrumentation

cc @piosz @brancz

/assign @cblecker

**Comment by bmcstdio** [comment]
I must look into https://github.com/prometheus/client_golang/pull/453 to understand whether there's an alternative to the now-unexported `LabelPairSorter`.

**Comment by cblecker** [comment]
@bmcstdio Looks like at minimum, you'll also need to run `hack/update-staging-godeps.sh`

**Comment by bmcstdio** [comment]
@cblecker thank you - just amended the commit!

**Comment by cblecker** [comment]
@kubernetes/sig-node-pr-reviews Would someone from sig node mind reviewing the test changes?

**Comment by jennybuckley** [comment]
cc @mbohlool

**Pull request closed without merging**
