### PR TITLE
update godep to pull from containernetworking/cni

### PR DESCRIPTION
**Pull request by freehan**
WIP

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/28859)

### CODE REVIEW

**Comment by freehan** [comment]
@k8s-bot test this issue: #28569

**Comment by luxas** [comment]
@freehan Please rebase this now so we may get the latest `libcni` changes into Kubernetes.
BTW, we should also build new binaries from current HEAD.

**Comment by freehan** [comment]
rebased

**Comment by luxas** [comment]
@freehan Could you please update to https://github.com/containernetworking/cni/commit/9d5e6e60e79491207834ae8439e80c943db65a69 (current HEAD)?

verify-godeps also broken right now.
I think this is something we want in v1.4, so adding the milestone. Remove if you strongly disagree

**Comment by freehan** [comment]
This PR is mainly updating the libcni though. 

Will push a separate PR for cni binary

**Comment by luxas** [comment]
Yep, but I'd also like libcni be at HEAD (since they introduced a function called `InjectConf` that we're gonna use)

But yes, binaries should be uploaded again, but for all arches: `amd64`, `arm`, `arm64` and `ppc64le`!

**Comment by freehan** [comment]
@luxas PTAL

**Comment by luxas** [comment]
LGTM

**Comment by luxas** [comment]
@freehan Unfortunately needs a rebase, ping me when you've done that

**Comment by freehan** [comment]
bumping priority due to 2 rebases

**Pull request merged**
