### PR TITLE
Make autoscaling team the autoscaler_contract package approver

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

#### What type of PR is this?
/kind cleanup
/sig scheduling

#### What this PR does / why we need it:

As mentioned by @sanposhiho in https://github.com/kubernetes/kubernetes/pull/110717#discussion_r977130869, now even we modify the files under  `autoscaler_contract` package, because we randomly picked two reviewers from all the qualified ones, so autoscaling team may be just missed. Let's make them the approvers then they won't miss this changes anymore.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kerthcet** [comment]
cc @kubernetes/sig-scheduling-leads

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Comment by alculquicondor** [comment]
Is the desire that only sig-autoscaling can approve?

Then you need to add `no_parent_owners` https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#owners

**Comment by kerthcet** [comment]
> Is the desire that only sig-autoscaling can approve?
> 
> Then you need to add `no_parent_owners` https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#owners

yes, or approvers  from sig-scheduling may be picked rather than from sig autoscaling. I'll take a look of the document.

**Comment by kerthcet** [comment]
Updated @alculquicondor

**Comment by kerthcet** [comment]
It reports spelling error of `be awared`😂, plz take a look again.

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Pull request merged**
