### PR TITLE
use appsv1beta1 for statefulsets

### LINKED ISSUE #46922: Update controllers/statefulset and controllers/history to use AppsV1Beta vs Apps client.
The statefulset controller and controller history implementations should be migrated off of the Apps client (deprecated) and onto the AppsV1BetaClient. Currently there is no user facing issue caused by the use of the deprecated resource, but we should maintain good code hygiene.

### PR DESCRIPTION
**Pull request by krmayankk**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
fixes https://github.com/kubernetes/kubernetes/issues/46922

### CODE REVIEW

**Comment by kow3ns** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by kow3ns** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Review by kow3ns — APPROVED** [review]
/lgtm

**Comment by krmayankk** [comment]
@kow3ns does this need to go in 1.7 or its punted to 1.8

**Pull request merged**
