### PR TITLE
Add --cloud-provider-timeout option to Kubelet

### PR DESCRIPTION
**Pull request by ingvagabund**
**What this PR does / why we need it**:

The the cloud provider request timeout configurable. The default 10s does not seem to be sufficient for all cloud providers.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ingvagabund** [comment]
@mtaufen are we still open to accept new flags out of the kubelet config?

**Review by luxas — CHANGES_REQUESTED** [review]
I would not expect us to add more code for the deprecated in-tree cloud providers. Talk to SIG Cloud Provider about this first please
cc @andrewsykim @wlan0

**Comment by ingvagabund** [comment]
@sjenning if this can not go in, the second option is to introduce back-off. In case the timeout is already over 1 minute (or 30 seconds?), then report the timeout error.

**Comment by mtaufen** [comment]
>@mtaufen are we still open to accept new flags out of the kubelet config?

We generally try not to. Also what @luxas said regarding deprecated in-tree cloud providers.

**Comment by sjenning** [comment]
@ingvagabund is this PR still the direction we want to go or should we close it?

With cloud providers moving out of tree I think a timeout like this would only be enforcable I we wrapped all our cloudprovider calls in a safety layer kubelet-side.  We wouldn't want to do it in each cloud provider.

The cloudprovider API has a `context` that is passed but I don't think that many cloudproviders actually honor it.

**Comment by andrewsykim** [comment]
At the moment the context is not used by any cloud providers that I am aware of but the goal was to let out-of-tree cloud provider implementations set those timeouts as they see fit.

**Comment by ingvagabund** [comment]
No longer needed.

**Pull request closed without merging**
