### PR TITLE
fix the gcfg typo

### PR DESCRIPTION
**Pull request by zhouhaibing089**
little fix in the openstack cloud provider.

### CODE REVIEW

**Comment by zhouhaibing089** [comment]
It is kind of flake https://github.com/kubernetes/kubernetes/issues/23321.

@k8s-bot test this

**Comment by zhouhaibing089** [comment]
@k8s-bot e2e test this issue: #23321

**Comment by zhouhaibing089** [comment]
@mikedanese not in the whitelist, could not trigger the retest, could you help?

**Comment by mikedanese** [comment]
@k8s-bot ok to test issue: #IGNORE

**Pull request merged**
