### PR TITLE
typos: spelling fixes in pkg/util/wait/wait.go

### PR DESCRIPTION
**Pull request by justinsb**
```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
/lgtm

LGTM from the bulk LGTM tool

**Comment by justinsb** [comment]
Rebased after file moved, readding lgtm

/lgtm

**Comment by brendandburns** [comment]
@k8s-bot kops aws e2e test this

**Comment by justinsb** [comment]
@k8s-bot kops aws e2e test this

**Comment by justinsb** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Pull request merged**
