### PR TITLE
kubeadm: allow mixing of command line flags and config file on init

### PR DESCRIPTION
**Pull request by rosti**
**What this PR does / why we need it**:

This change allows command line flags and config file to be specified during kubeadm init. Command line flags take precedence over config file settings. Thus it's now possible to do something like this:
`kubeadm init --config=my-config.yaml --node-name=Node3456`

and it should work as expected.

There are a couple of quirks that may need to be changed in the current PR though:
- If --token is specified on the command line, it completely overrides any bootstrap tokens in the config file.
- This also increases kubeadm cmd tests timeout from 2 minutes to 10 minutes (due to large amount of test cases that finish on my machine in ~130 sec)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Refs kubernetes/kubeadm#906

**Special notes for your reviewer**:
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews
/area kubeadm
/kind feature
/assign @luxas
/assign @timothysc
/assign @fabriziopandini 
/assign @chuckha 

**Release note**:

```release-note
kubeadm: init allows mixing of command line flags and config file with the former one overriding the settings of the latter one
```

### CODE REVIEW

**Comment by rosti** [comment]
/assign @liggitt 

For the kubeadm cmd tests timeout bump.

**Review by timothysc — COMMENTED** [review]
I'm torn by this.  Things like viper exist to solve this problem in a cleaner more general way.

**Comment by liggitt** [comment]
> command line flags and config file to be specified during kubeadm init. Command line flags take precedence over config file settings

mixing these has been a nightmare in kubelet. using either the config file or the flags has been much cleaner in other projects like the openshift apiserver

**Comment by rosti** [comment]
This effectively tries to mimic the current approach of kubelet. It's much more clean from implementation standpoint to use config file or command line flags (and not mix them), but the fact is, that sometimes you may want to change some settings and do that from the command line.

Another approach to solving this is to stick to the original issue - for kubeadm, do this only for join, and only for certain settings (such as the node name).

@timothysc @luxas @fabriziopandini WDYT?

**Comment by liggitt** [comment]
> This effectively tries to mimic the current approach of kubelet

I wouldn't recommend that. I hope to avoid that mix with the other components we add config files to

**Comment by luxas** [comment]
@mtaufen the current recommendation is parsing the flags and the config file. I think that is sensible for overriding e.g. instance-specific configuration in some cases. Is it worth the complexity? We need "official" guidelines for all the other components here.

**Comment by mtaufen** [comment]
That had nothing to do with overriding instance-specific stuff in the
Kubelet, it was strictly backwards compatibility concerns related to
incrementally migrating flags into the config file. Today the Kubelet only
allows instance-specific stuff in flags; these never merge with the config
file.

I do think there are simpler and more explicit ways to handle the merge in
the Kubelet vs how I did it the first time, but haven't had time to focus
on that lately.

If you can get away with just the config file, and not merging, I would
recommend doing so. This is the endgame for the Kubelet anyway; the plan is
still to get rid of most of the flags.

**Comment by neolit123** [comment]
> This is the endgame for the Kubelet anyway; the plan is
still to get rid of most of the flags.

and i think we should do this for kubeadm as well.
if we apply this PR right now we get the strict override rule that defines an expected behavior, but then we can start deprecating all the flags.

just faced the same issue in kube-proxy. the flags and config there are mutually exclusive ATM, which creates all sorts of issues.

**Comment by liggitt** [comment]
> if we apply this PR right now we get the strict override rule that defines an expected behavior, but then we can start deprecating all the flags.

Mixing the two is likely more painful than you expect, with little benefit. For example, the kubelet has had to reimplement most of cobra flag parsing, help generation, etc. If you can make config file and flags exclusive, that is far more straightforward.

**Comment by neolit123** [comment]
@liggitt 

> Mixing the two is likely more painful than you expect, with little benefit. For example, the kubelet has had to reimplement most of cobra flag parsing, help generation, etc. If you can make config file and flags exclusive, that is far more straightforward.

for the kube-proxy case at least _mutually exclusive_ is not the correct term i guess... 
from what i'm seeing if a config is loaded it overwrites the CLI flags, which is the opposite to what the kubelet does and this can be considered a bug since the flags are deprecated, but not removed yet:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go#L204

there has to be precedence, [viper](https://github.com/spf13/viper) (as @timothysc suggested) also has it - CLI over config.

did the kubelet consider viper?
we kind of need this for the whole kubeadm not only for `kubeadm init`, so if viper works for us we should consider it instead of home brewing this.

**Comment by neolit123** [comment]
@timstclair on slack says:
> I think how sonobuoy works is much cleaner CLI->args->config with a clean separation

**Comment by timothysc** [comment]
/hold 

Let's KEP out https://github.com/kubernetes/kubeadm/issues/1040 with input from folks.

**Pull request closed without merging**
