### PR TITLE
Release 0.19.1

### PR DESCRIPTION
**Pull request by brendandburns**
@roberthbailey @dchen1107 @cjcullen @jlowdermilk

### CODE REVIEW

**Comment by roberthbailey** [comment]
LGTM.

**Comment by dchen1107** [comment]
LGTM.

@k8s-bot ok to test

**Comment by brendandburns** [comment]
Please don't merge this, we're waiting on some more changes.

(also, I don't think k8s-bot knows how to test changes to release branches)

**Comment by brendandburns** [comment]
Ok, this passes e2e on my client.  @dchen1107 @vishh @cjcullen @roberthbailey @jlowdermilk @a-robinson 

Please check this build out to make sure I got everything we want/need.

**Comment by roberthbailey** [comment]
I don't know what's in heapster 0.14.2, but you have 0.14.0 and 0.14.1 and 0.14.2 was merged today as well (in https://github.com/GoogleCloudPlatform/kubernetes/pull/9917). @vishh

**Comment by brendandburns** [comment]
@vishh claimed that 0.14.1 was sufficient...  I'd really rather not have to re-cut/re-qual this build...

**Comment by roberthbailey** [comment]
If @vishh is happy then I'm good -- just wanted to check so we didn't have to re-cut another build tomorrow.

**Comment by a-robinson** [comment]
0.14.1 had a bug (https://github.com/GoogleCloudPlatform/heapster/issues/348) that 0.14.2 fixes

**Comment by vishh** [comment]
Is it possible to include #9917?

**Comment by roberthbailey** [comment]
With the recent cherry picks, this now LGTM.

**Comment by roberthbailey** [comment]
@satnam6502 feel free to merge.

**Pull request merged**
