### PR TITLE
accurate hint

### PR DESCRIPTION
**Pull request by timchenxiaoyu**
accurate hint

same err hint (Error adding network) in one method,cann't position problem

### CODE REVIEW

**Comment by danwinship** [comment]
I don't know why k8s-merge-bot assigned this to me since afaik I don't have merge rights, and I've never touched any of the files in that directory, but...

/lgtm

?

**Comment by timchenxiaoyu** [comment]
release-note-none

**Comment by timchenxiaoyu** [comment]
cc @thockin  please give this pr approve,thanks

**Pull request merged**
