### PR TITLE
client-go: default user agent if empty

### LINKED ISSUE #108726: kubelet's requests are reported as 'Go-http-client/2.0'
### What happened?

It looks like kubelet started using generic user agent like "Go-http-client/2.0" and makes it harder to attribute the request to kubelet.

In the past we have used "kubelet" user-agent which was providing some value.

Sample logs: https://storage.googleapis.com/sig-scalability-logs/ci-kubernetes-e2e-gci-gce-scalability/1503729543293177856/e2e-big-master/kube-apiserver.log
```
I0315 14:13:15.198270      11 httplog.go:131] "HTTP" verb="DELETE" URI="/api/v1/namespaces/test-1w3fvz-1/pods/latency-deployment-67-5cb8c6bf86-psrtn" latency="5.033096ms" userAgent="Go-http-client/2.0" audit-ID="447f2e58-4649-4fbd-9631-50a862f18d6f" srcIP="10.40.3.224:35364" apf_pl="system" apf_fs="system-nodes" resp=200
```

### What did you expect to happen?

Kubelet's requests are using customised user-agent

### How can we reproduce it (as minimally and precisely as possible)?

* Run kubelet
* Check kube-apiserver's logs: https://storage.googleapis.com/sig-scalability-logs/ci-kubernetes-e2e-gci-gce-scalability/1503729543293177856/e2e-big-master/kube-apiserver.log

### Anything else we need to know?

_No response_

### Kubernetes version

master

### Cloud provider

tested on gce

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by aojea**
/kind bug
/kind regression

Fixes #108726

The kubernetes clientset generates one clientset per group/version.
The defaulting of the user-agent is done per group/version, but since https://github.com/kubernetes/kubernetes/pull/105490, all clientset share the same transport, so we should default the user-agent on the global contructor.

```release-note
fixes a 1.23 regression: client-go clientset was not defaulting the user agent, using the default golang agent for all the requests.
```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @liggitt 
/cc @mborsz 

/hold
holding to verify that nothing is missing and all the components are using the correct user-agent

**Comment by aojea** [comment]
Kubernetes e2e suite: [sig-api-machinery] Aggregator Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance] expand_less	
/retest

**Comment by aojea** [comment]
@mborsz from the gce-100 performance job

```sh
$ wget https://storage.googleapis.com/sig-scalability-logs/pull-kubernetes-e2e-gce-100-performance/1504498650846334976/e2e-108772-95a39-master/kube-apiserver.log
$ grep -oP 'userAgent=".*"' kube-apiserver.log  | cut -d\" -f2 | sort | uniq -c | sort -nr
 153463 kubelet/v1.24.0 (linux/amd64) kubernetes/df8d5a9
  22142 kubectl/v1.24.0 (linux/amd64) kubernetes/df8d5a9
  16158 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:generic-garbage-collector
  15790 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:replicaset-controller
  15724 kubectl/v1.20.2 (linux/amd64) kubernetes/faecb19
  13430 kube-scheduler/v1.24.0 (linux/amd64) kubernetes/df8d5a9/scheduler
  10360 clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format
   9897 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:deployment-controller
   6781 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:endpointslice-controller
   3295 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:endpoint-controller
   2371 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:resourcequota-controller
   1947 kube-probe/1.24+
   1843 kube-apiserver/v1.24.0 (linux/amd64) kubernetes/df8d5a9
   1760 kube-scheduler/v1.24.0 (linux/amd64) kubernetes/df8d5a9/leader-election
   1752 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/leader-election
   1716 glbc/v0.0.0 (linux/amd64) kubernetes/$Format/leader-election
   1665 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:daemon-set-controller
   1303 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/controller-discovery
   1300 node-problem-detector/v0.8.9
   1292 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:node-controller
   1280 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:namespace-controller
   1270 glbc/v0.0.0 (linux/amd64) kubernetes/$Format
   1250 kube-proxy/v1.24.0 (linux/amd64) kubernetes/df8d5a9
    988 csi-attacher/v0.0.0 (linux/amd64) kubernetes/$Format
    879 csi-provisioner/v0.0.0 (linux/amd64) kubernetes/$Format
    821 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:job-controller
    631 csi-snapshotter/v0.0.0 (linux/amd64) kubernetes/$Format
    631 csi-resizer/v0.0.0 (linux/amd64) kubernetes/$Format
    622 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:persistent-volume-binder
    349 cluster-proportional-autoscaler/v0.0.0 (linux/amd64) kubernetes/$Format
    341 Prometheus/2.25.0
    301 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:attachdetach-controller
    300 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:certificate-controller
    229 metrics-server/v0.5.2 (linux/amd64) kubernetes/93b9ddc
    213 operator/v0.0.0 (linux/amd64) kubernetes/$Format
    208 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:statefulset-controller
    201 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:ttl-controller
    200 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/shared-informers
    151 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/kube-controller-manager
    117 kubectl/v1.23.4 (linux/amd64) kubernetes/e6c093d
    113 pod_nanny/1.8.14
    112 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9
    103 coredns/v0.0.0 (linux/amd64) kubernetes/$Format
    102 kube-scheduler/v1.24.0 (linux/amd64) kubernetes/df8d5a9
    100 proxy-server/v0.0.0 (linux/amd64) kubernetes/$Format
    100 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:pvc-protection-controller
    100 Go-http-client/2.0
     62 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/metadata-informers
     58 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:pv-protection-controller
     50 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:expand-controller
     27 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:root-ca-cert-publisher
     21 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:service-account-controller
     18 snapshot-controller/v0.0.0 (linux/amd64) kubernetes/$Format
      6 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:clusterrole-aggregation-controller
      6 curl/7.69.1
      4 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:cloud-provider
      2 kube-controller-manager/v1.24.0 (linux/amd64) kubernetes/df8d5a9/system:serviceaccount:kube-system:endpointslicemirroring-controller
      1 Go-http-client/1.1
      1 curl/7.64.0
```

so this fixes https://github.com/kubernetes/kubernetes/issues/108726

**Comment by liggitt** [comment]
```
    100 Go-http-client/2.0
      1 Go-http-client/1.1
```

I guess we do make some requests with just stock http clients

**Comment by aojea** [comment]
> ```
>     100 Go-http-client/2.0
>       1 Go-http-client/1.1
> ```
> 
> I guess we do make some requests with just stock http clients

those can come from the perf-tests framework, they don't show up in kind

https://github.com/kubernetes/kubernetes/pull/108772#issuecomment-1071122811

and there is a strong correlation against to the ones reported in the bug 

https://github.com/kubernetes/kubernetes/issues/108726#issuecomment-1068929971

**Comment by aojea** [comment]
:thinking: 
Kubernetes e2e suite: [sig-node] Pods Extended Pod Container lifecycle should not create extra sandbox if all containers are done expand_less	

/retest

**Pull request merged**
