### PR TITLE
Remove e2e test for least requested prioirty function

### LINKED ISSUE #47769: SchedulerPriorities - swarm of 1.6 -> 1.7 upgrade failures
## [Triage dashboard](https://storage.googleapis.com/k8s-gubernator/triage/index.html?job=1-5-.*-1-7.*upgrade&test=SchedulerPriorities)

Includes links to these:
* SchedulerPriorities [Serial] Pods should be scheduled to low resource use rate node
* SchedulerPriorities [Serial] Pod should be prefer scheduled to node that satisify the NodeAffinity
* SchedulerPriorities [Serial] [Pod should avoid to schedule to node that have avoidPod annotation](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cvm-1-5-gci-1-7-upgrade-cluster-new/18#k8sio-schedulerpriorities-serial-pod-should-avoid-to-schedule-to-node-that-have-avoidpod-annotation)

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:85
Expected error:
    <*errors.errorString | 0xc420c35060>: {
        s: "1 / 15 pods in namespace \"kube-system\" are NOT in RUNNING and READY state in 5m0s\nPOD                                 NODE                                         PHASE   GRACE CONDITIONS\nkube-dns-autoscaler-300991650-0bb9q gke-bootstrap-e2e-default-pool-55863395-k993 Pending       [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-06-19 17:03:21 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-06-19 17:03:21 +0000 UTC ContainersNotReady containers with unready status: [autoscaler]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-06-19 17:03:21 +0000 UTC  }]\n",
    }
    1 / 15 pods in namespace "kube-system" are NOT in RUNNING and READY state in 5m0s
    POD                                 NODE                                         PHASE   GRACE CONDITIONS
    kube-dns-autoscaler-300991650-0bb9q gke-bootstrap-e2e-default-pool-55863395-k993 Pending       [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2017-06-19 17:03:21 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2017-06-19 17:03:21 +0000 UTC ContainersNotReady containers with unready status: [autoscaler]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2017-06-19 17:03:21 +0000 UTC  }]
    
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:84
```

/sig scheduling
/assign @davidopp 

See also #47767

### PR DESCRIPTION
**Pull request by bsalamat**
**What this PR does / why we need it**:
Deletes a flaky e2e test for "least requested" priority function of the scheduler. This priority function is tested more extensively in our unit tests.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #47769 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by bsalamat** [comment]
@kubernetes/sig-scheduling-pr-reviews 
@davidopp @k82cn @timothysc

**Comment by dchen1107** [comment]
Look good to me! We are finally moving toward to this step and indicate that all those test scenario are covered by the unit tests. Our e2e test environment is not deterministic enough for this kind of tests. If we really want to have integration tests, we should introduce simulated node. 

cc/ @kubernetes/kubernetes-release-managers

**Comment by k82cn** [comment]
@bsalamat , LTGM; for scheduling policy, I think "unit test" + "integration test" is enough with simulated nodes, pods.

**Comment by bsalamat** [comment]
Could one of the approvers approve this?

**Comment by davidopp** [comment]
I think we need to cherrypick this into the 1.7 release branch (also 1.6, to cover the upgrade tests?) if we want it to stop giving us red tests.

**Pull request merged**
