### PR TITLE
Cherrypick fixes for timeout errors upgrade tests

### PR DESCRIPTION
**Pull request by jessfraz**
**What this PR does / why we need it**:

Some of the upgrade tests from 1.3 to 1.4 are failing in waiting for load balancers. This cherrypicks commits from 1.4 to 1.3 tests to fix that.

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #

**Special notes for your reviewer**:

**Release note**:

``` release-note
NONE
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31896)

### CODE REVIEW

**Comment by jfrazelle** [comment]
ok to test

**Comment by jfrazelle** [comment]
ok to test

**Comment by lavalamp** [comment]
this lgtm, but will it fix the problem? It doesn't change behavior except on large clusters, and I didn't think we ran large clusters through the upgrade test?

**Comment by jfrazelle** [comment]
I did a huge git bisect which lead me to these so I'm hoping that it will

**Comment by pwittrock** [comment]
Lets try it an find out.  Can always roll it back.

**Comment by lavalamp** [comment]
@jfrazelle did you make this PR with our cherrypick script? I'm not entirely sure why we have it but it might be good to use it unless you're doing something fancy.

**Comment by jfrazelle** [comment]
im so used to doing cherry-picks manually haha

**Pull request merged**
