### PR TITLE
Use a different port for the kubectl proxy in the shell and go tests.

### PR DESCRIPTION
**Pull request by roberthbailey**
Help narrow down the cause of #4807. Alternatively, we could roll back my change from yesterday that adds the proxying but since no one has done that I'm going to work on rolling forward.

### CODE REVIEW

**Comment by roberthbailey** [comment]
@zmerlynn @jlowdermilk

**Comment by zmerlynn** [comment]
LGTM

**Comment by zmerlynn** [comment]
Actually, we're going to revert #4791. Reverting this first.

**Comment by roberthbailey** [comment]
Thanks. Sorry for the break. :/

**Pull request merged**
