### PR TITLE
WIP: custom serialization for field set

### PR DESCRIPTION
**Pull request by lavalamp**
This is to show how https://github.com/kubernetes-sigs/structured-merge-diff/pull/90 might be used.

### CODE REVIEW

**Comment by lavalamp** [comment]
```
benchmark                       old ns/op     new ns/op     delta
BenchmarkApplyNewObject-12      2065260       1903735       -7.82%
BenchmarkUpdateNewObject-12     2415312       2178154       -9.82%
BenchmarkRepeatedUpdate-12      967089        784110        -18.92%
BenchmarkSetToFields-12         22058         8862          -59.82%
BenchmarkFieldsToSet-12         15648         11641         -25.61%
BenchmarkYAMLToTyped-12         65407         63847         -2.39%

benchmark                       old allocs     new allocs     delta
BenchmarkApplyNewObject-12      7168           6861           -4.28%
BenchmarkUpdateNewObject-12     8396           7953           -5.28%
BenchmarkRepeatedUpdate-12      2887           2342           -18.88%
BenchmarkSetToFields-12         130            42             -67.69%
BenchmarkFieldsToSet-12         91             94             +3.30%
BenchmarkYAMLToTyped-12         152            152            +0.00%
```

I expected more impact so there's probably some more to do here.

**Comment by apelisse** [comment]
This is very important for the read path too, so I'm excited to get that merged soon.

**Comment by lavalamp** [comment]
```
benchmark                       old ns/op     new ns/op     delta
BenchmarkApplyNewObject-12      2230683       1957508       -12.25%
BenchmarkUpdateNewObject-12     2624417       2166853       -17.43%
BenchmarkRepeatedUpdate-12      1031653       765925        -25.76%
BenchmarkSetToFields-12         24778         5217          -78.95%
BenchmarkFieldsToSet-12         33876         10303         -69.59%
BenchmarkYAMLToTyped-12         68377         62136         -9.13%

benchmark                       old allocs     new allocs     delta
BenchmarkApplyNewObject-12      8632           6827           -20.91%
BenchmarkUpdateNewObject-12     11210          7913           -29.41%
BenchmarkRepeatedUpdate-12      3057           2288           -25.16%
BenchmarkSetToFields-12         124            14             -88.71%
BenchmarkFieldsToSet-12         147            82             -44.22%
BenchmarkYAMLToTyped-12         150            152            +1.33%
```

This needs to fix up validation code and comments and other things before it's acceptable to merge.

**Comment by apelisse** [comment]
I'm expecting this PR will get closed. Thanks

**Comment by lavalamp** [comment]
Closing in favor of #80730

**Pull request closed without merging**
