### PR TITLE
Don't use global rand for nodeport and IP allocs

### PR DESCRIPTION
**Pull request by thockin**
Seed it at construction.

### CODE REVIEW

**Comment by smarterclayton** [comment]
Release critical?

**Comment by thockin** [comment]
Not critical

On Mar 16, 2017 7:23 PM, "Clayton Coleman" <notifications@github.com> wrote:

Release critical?

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/43260#issuecomment-287249106>,
or mute the thread

**Comment by thockin** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
