### PR TITLE
Switch to k8s.io/utils/inotify

### LINKED ISSUE #80092: Switch to k8s.io/utils/inotify
- [x] Fix fd leak
- [x] Fixing golint issues in k8s.io/utils/inotify 
- [x] Switch cadvisor to use k8s.io/utils/inotify  ( https://github.com/google/cadvisor/pull/2269 )
- [ ] Switch k/k to use k8s.io/utils/inotify  ( https://github.com/kubernetes/kubernetes/pull/80689 )
- [ ] Switch k/k to use cadvisor (with the change above)

### PR DESCRIPTION
**Pull request by Pothulapati**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Replaces `github.com/go-sigma/inotify` with `k8s.io/utils/inotify`

**Which issue(s) this PR fixes**:

Fixes #80092

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
@dims

### CODE REVIEW

**Comment by cblecker** [comment]
Dupe of #80613
/close

**Comment by cblecker** [comment]
Actually, I just saw that this was intended.
/reopen
/ok-to-test

**Comment by cblecker** [comment]
1. Needs a rebase, resolve conflicts, and a `hack/update-vendor.sh`
2. Needs a `hack/update-gofmt.sh`

Otherwise lgtm. Dependency linting comes up clean.

**Review by cblecker — APPROVED** [review]
/lgtm
/assign @liggitt

**Comment by liggitt** [comment]
mechanics lgtm. any tests in k8s.io/utils or in k8s to prove https://github.com/kubernetes/utils/pull/101 fixes the leak?

**Comment by dims** [comment]
@cpuguy83 @sigma - please see @liggitt 's query above

**Comment by dims** [comment]
@Pothulapati Can you please rebase?

**Comment by Pothulapati** [comment]
@dims Updated.

**Comment by liggitt** [comment]
> any tests in k8s.io/utils or in k8s to prove [kubernetes/utils#101](https://github.com/kubernetes/utils/pull/101) fixes the leak?

was this answered?

**Comment by dims** [comment]
@liggitt hmm i thought i figured out, but missed adding a comment. Please see manual steps in the [fsnotify PR](https://github.com/fsnotify/fsnotify/pull/178#issuecomment-251799596) which is very similar to this change 

```
dims@bigbox:~/junk$ /bin/cat test.go
package main

import (
    "fmt"
    "log"
    "os"
    "os/exec"
    "time"

    "k8s.io/utils/inotify"
)

func main() {
    if len(os.Args) == 1 { // parent
        watcher, err := inotify.NewWatcher()
        if err != nil {
            log.Fatal(err)
        }
        defer watcher.Close()

        child := exec.Command(os.Args[0], "child")
        err = child.Start()
        if err != nil {
            log.Fatal(err)
        }

        fmt.Println("Parent", os.Getpid(), "child", child.Process.Pid)
    }

    fmt.Println(os.Args, "going into sleep")
    for {
        time.Sleep(time.Second)
    }
}
```

```
dims@bigbox:~/junk$ go run test.go
Parent 18870 child 18875
[/tmp/go-build617179765/b001/exe/test] going into sleep
```

```
dims@bigbox:~$ lsof -p 18870
COMMAND   PID USER   FD      TYPE DEVICE SIZE/OFF     NODE NAME
test    18870 dims  cwd       DIR  253,0     4096 41816258 /home/dims/junk
test    18870 dims  rtd       DIR  253,0     4096        2 /
test    18870 dims  txt       REG  253,0  1664448  1576577 /tmp/go-build617179765/b001/exe/test
test    18870 dims    0u      CHR  136,0      0t0        3 /dev/pts/0
test    18870 dims    1u      CHR  136,0      0t0        3 /dev/pts/0
test    18870 dims    2u      CHR  136,0      0t0        3 /dev/pts/0
test    18870 dims    3r  a_inode   0,13        0    14824 inotify
test    18870 dims    5u  a_inode   0,13        0    14824 [eventpoll]
dims@bigbox:~$ lsof -p 18875
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
test    18875 dims  cwd    DIR  253,0     4096 41816258 /home/dims/junk
test    18875 dims  rtd    DIR  253,0     4096        2 /
test    18875 dims  txt    REG  253,0  1664448  1576577 /tmp/go-build617179765/b001/exe/test
test    18875 dims    0r   CHR    1,3      0t0        6 /dev/null
test    18875 dims    1w   CHR    1,3      0t0        6 /dev/null
test    18875 dims    2w   CHR    1,3      0t0        6 /dev/null
```

**Comment by liggitt** [comment]
ok, glad there's a manual test. any possibility of an automated one? I don't block on it, but would like to at least see an issue for tracking that

**Comment by dims** [comment]
@liggitt Added an issue - https://github.com/kubernetes/utils/issues/106

**Comment by Pothulapati** [comment]
Looks like https://github.com/kubernetes/kubernetes/pull/78610 , updated `k8s.io/utils` to a more latest commit and there were conflicts as were using an older version.

I updated the PR, to use the latest commit of `k8s.io/utils` i.e same as the one in the PR. :)

**Comment by liggitt** [comment]
sorry for the churn. does this need to be rebased on master? It looks like this still has commits that conflict with https://github.com/kubernetes/kubernetes/pull/78610. If so, I'd recommend:
* rebasing on master, dropping the commits that mess with vendor
* run `hack/update-vendor.sh` and make a new commit (you shouldn't need to do any pin-dependency work any more)
* run `hack/lint-dependencies.sh` and make sure the results are clean

**Comment by Pothulapati** [comment]
Got it @liggitt, Thanks for the help!
Updated as per your comment :)

**Comment by liggitt** [comment]
thanks

/lgtm

**Pull request merged**
