### PR TITLE
Fix test name in e2e resource metrics api test

### PR DESCRIPTION
**Pull request by hasheddan**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Updates resouce to resource.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

**Which issue(s) this PR fixes**:

n/a
/priority backlog

**Special notes for your reviewer**:

n/a

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by egernst — APPROVED** [review]

**Comment by dims** [comment]
/milestone v1.20
/assign @mrunalp

typo fix Mrunal, 1 liner.

**Pull request merged**
