### PR TITLE
Remove 'stop' subcommand from 'kubectl'

### PR DESCRIPTION
**Pull request by hurf**
Fixes: #11384

All functionality of 'kubectl stop' is coverd by 'kubectl delete',
remove 'stop' to avoid confusion.

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks, but we can't just remove stop. We need to add a deprecation warning for some period of time.

**Comment by hurf** [comment]
Then I'll create a new PR to add deprecated flag to 'stop' and abandon this one.

**Comment by hurf** [comment]
@bgrant0607 - Can we remove `stop` command now? It has been deprecated for some time and 1.1 is coming.

**Comment by bgrant0607** [comment]
#11973 was merged after 1.0 was cut, so 1.1 is the first minor release in which stop will be deprecated, so we can't remove stop in 1.1.

**Pull request closed without merging**
