### PR TITLE
/test/e2e_kubeadm: adjust label / taint checks for 1.23

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?

NOTE: this is not a cherry pick for 1.23, since the file at master is different:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e_kubeadm/controlplane_nodes_test.go#L33-L37

/kind failing-test

#### What this PR does / why we need it:

In the 1.23 release we should have updated the kubeadm
e2e test suite to only check for the "control-plane" label.

If the 1.24 suite is run against kubeadm 1.24 clusters only
there are on problems, but since kubeadm supports skew with the
control plane of N-1, this means that the old suite running against
a kubeadm 1.24 cluster will fail because kubeadm 1.24 removes
the master label.

Update the 1.23 suite to only test for the "control-plane" label which
is present in both kubeadm 1.23 and 1.24 clusters.

Check for either the "control-plane" OR "master" taint on nodes
(1.23 only has "master", 1.24 has both "master" and "control-plane").

#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/kubeadm/issues/2200#issuecomment-1041827446
xref https://github.com/kubernetes/kubeadm/pull/2638

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/triage accepted
/priority important-soon
(due to failing tests)

/cc @pacoxu 
PTAL for review.

**Comment by pacoxu** [comment]
This would fix https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-latest-on-1-23/1494093800799211520. 
/lgtm

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Comment by pacoxu** [comment]
kindly ping @kubernetes/release-managers

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
