### PR TITLE
kubectl proxy was ignoring reject-methods flag

### PR DESCRIPTION
**Pull request by suyogbarve**
**What this PR does / why we need it**:
"kubect proxy" command had a bug and was not support feature to reject http methods 
--reject-methods='POST,PUT,PATCH'
this was due to missing filter for RejectMethods in kubectl/cmd/proxy.go 

Issue not created and no existing issue found

### CODE REVIEW

**Comment by eparis** [comment]
/assign @brendandburns 
Assigning to brendan since he wrote this a couple years ago. This patch will cause the proxy to stop allowing POST,PUT,PATCH by default. Which seems a bit odd..   Do we need to wire it up and change that default?

**Comment by eparis** [comment]
@k8s-bot ok to test

**Comment by suyogbarve** [comment]
thanks @eparis 
@brendandburns please let me know if you would like me to change - 

Option 1)  default to be more permissive /pkg/kubectl/proxy_server.go
const (
	.....
	DefaultMethodRejectRE = "POST,PUT,PATCH"
)
to 
const (
	----
	DefaultMethodRejectRE = ""
)
** this would also force removal of PUT, POST,PATCH test cases in proxy_server_test.go

Option 2) Update kubectl.DefaultMethodRejectRE comment to include (default rejected methods PUT, POST and PATCH)

**Comment by eparis** [comment]
It seems to me you'd want to do that and to change the _test.go to have a 'per test' method reject, like it does the other 3 things. Which we set to 'POST,PUT,PATCH' only where we are explicitly testing they work.

**Comment by suyogbarve** [comment]
I am providing a new pull request with all the changes suggested in this PR.
https://github.com/kubernetes/kubernetes/pull/44908

**Pull request closed without merging**
