### PR TITLE
comment spelling correction in custommetrics

### PR DESCRIPTION
**Pull request by siggy**
**What this PR does / why we need it**: fix spelling in a comment

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by sjpotter** [comment]
I'd just change the PR name to comment spelling correction in custommetrics otherwise LGTM

**Comment by supereagle** [comment]
LGTM.  @k8s-bot test this

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Pull request merged**
