### PR TITLE
Update to golang@1.13.5

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What this PR does / why we need it**:
Update to golang@1.13.5.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Before merge:
- [x] build/push cross-build image for 1.13.5 (`k8s.gcr.io/kube-cross:v1.13.5-1`)

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
@cblecker, can you help with building and pushing `k8s.gcr.io/kube-cross:v1.13.5-1`. I guess I won't have the needed access rights.

**Comment by cblecker** [comment]
Can you please update rules go? You need to bump it to a release that actually includes the new toolchain before this will pass.

/assign

**Comment by ialidzhikov** [comment]
> Can you please update rules go? You need to bump it to a release that actually includes the new toolchain before this will pass.
> 
> /assign

Nice catch. Updated rules_go to `v0.19.9`.

**Comment by ialidzhikov** [comment]
@cblecker , looks like the checks fail because `k8s.gcr.io/kube-cross:v1.13.5-1` image is missing. I guess we can build and push it and then retest. WDYT?

**Comment by ialidzhikov** [comment]
Any update @cblecker?

**Comment by fejta** [comment]
Please pass unit tests

**Comment by cblecker** [comment]
/unassign @cblecker
/assign @BenTheElder @javier-b-perez 

All tests are passing that can be without image being built. Assigning over to Ben/Javier to build and push cross image.

**Comment by javier-b-perez** [comment]
Image should be there soon...
/test pull-kubernetes-cross

**Comment by BenTheElder** [comment]
/cc
/lgtm
/approve
we should also update test-infra
https://github.com/kubernetes/test-infra/blob/36bc0ec358c9c154656dc9ab4740233f900d858b/images/kubekins-e2e/variants.yaml#L15

**Pull request merged**
