### PR TITLE
Switch pod eviction client from v1alpha1 to v1beta

### PR DESCRIPTION
**Pull request by mwielgus**
Generated client 1.5 has a function to evict a pod. The function uses v1alpha1.Eviction object instead of v1beta1. This pr changes the api version that is being used.

cc: @davidopp @caesarxuchao

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36651)

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Thanks @mwielgus . Could you also run hack/udpate-staging-client-go.sh?

**Comment by mwielgus** [comment]
client-go updated. PTAL.

**Comment by caesarxuchao** [comment]
LGTM. Thanks.

**Comment by davidopp** [comment]
Thanks @mwielgus. I assume this is a bug fix, and not something we need to file an exception request for?

**Comment by caesarxuchao** [comment]
Yes, it's an bug fix.

**Comment by saad-ali** [comment]
>> Thanks @mwielgus. I assume this is a bug fix, and not something we need to file an exception request for?
> Yes, it's an bug fix.

Thanks!

**Pull request merged**
