### PR TITLE
AWS: Remove parallel test suite

### PR DESCRIPTION
**Pull request by justinsb**
Equivalent of #20348 for AWS

### CODE REVIEW

**Comment by justinsb** [comment]
Also @ihmccreery I'm not sure if we should still be setting `NUM_NODES=${NUM_NODES_PARALLEL}`?

**Comment by ihmccreery** [comment]
This is actually incorporated into #20353, I believe.  :+1: 

I don't care much about `NUM_NODES=${NUM_NODES_PARALLEL}`; if you have strong feelings, I can change it (open an issue?).

**Comment by justinsb** [comment]
Ah great @ihmccreery .  Do you think AWS should also have the same regex as GCE?  My personal feeling is "yes" - that we should run the same tests in the corresponding test suites.

GCE has:

```
 ${GINKGO_TEST_ARGS:="--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|\[Skipped\]"}
```

Right now AWS has this:

```
    : ${GINKGO_TEST_ARGS:="--ginkgo.skip=$(join_regex_allow_empty \
          ${GCE_DEFAULT_SKIP_TESTS[@]:+${GCE_DEFAULT_SKIP_TESTS[@]}} \
          ${GCE_FLAKY_TESTS[@]:+${GCE_FLAKY_TESTS[@]}} \
          ${GCE_SLOW_TESTS[@]:+${GCE_SLOW_TESTS[@]}} \
          )"}
```

But other than that, looks like most of this got done in #20558 - thanks!

**Comment by ihmccreery** [comment]
Closing this as this change was incorporated elsewhere.

**Pull request closed without merging**
