### PR TITLE
Automated cherry pick of #27961 #29140 upstream release 1.3

### PR DESCRIPTION
**Pull request by maisem**
Cherry pick of #27961 and #29140 on release-1.3.

### CODE REVIEW

**Comment by fabioy** [comment]
@k8s-bot test this #IGNORE

**Comment by fabioy** [comment]
@k8s-bot test this #IGNORE

**Comment by fabioy** [comment]
@k8s-bot test this issue #ignore

**Comment by spxtr** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by fabioy** [comment]
@maisem Jenkins verification fails - "FAILED   ./hack/../hack/verify-boilerplate.sh". Please fix and push new PR. Thanks.

**Pull request merged**
