### PR TITLE
Add bash dependency to Redis e2e image

### PR DESCRIPTION
**Pull request by johscheuer**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
https://github.com/kubernetes/kubernetes/pull/73194 added the bash dependency for ZooKeeper but missed to add the dependency for the Redis installer as well.

**Which issue(s) this PR fixes**:
-

**Special notes for your reviewer**:
I also updated the image version.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/ok-to-test
/priority backlog

**Comment by ixdy** [comment]
cc @listx

**Comment by listx** [comment]
I ran `make all-push WHAT=pets/redis-installer` and the gcr.io/kubernetes-e2e-test-images/pets/redis-installer:1.3 image is live.

**Pull request merged**
