### PR TITLE
Ginkgo naming conventions (fixed)

### PR DESCRIPTION
**Pull request by jayunit100**

### CODE REVIEW

**Comment by jayunit100** [comment]
cc @bgrant0607 @erictune

**Comment by bgrant0607** [comment]
Thanks, @jayunit100. Are you able to run e2e to try this out?

**Comment by bgrant0607** [comment]
LGTM

**Comment by jayunit100** [comment]
hi brian.  just saw.  sorry , yes i am able to run some but not all of the e2es on this branch.
of course, it wont match exactly to GCE , though.

**Comment by jayunit100** [comment]
in any case, yes i did run this on the `kubectl` E2Es/.... thanks for the quick review!

```• [SLOW TEST:10.696 seconds]
Kubectl client
/home/jay/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:131
  Update Demo
  /home/jay/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:107
    should create and stop a replication controller
    /home/jay/gopath/src/github.com/GoogleCloudPlatform/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/kubectl.go:82
------------------------------
SSSSSS

```

**Pull request merged**
