### PR TITLE
docs(api): 📝  Fix HPA docs with addition of "External" type

### PR DESCRIPTION
**Pull request by ghostsquad**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Documentation did not accurately describe the valid values of `Type` for HPAs.

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:
N/A

**Does this PR introduce a user-facing change?**:
N/A

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
N/A

```release-note
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
You will need to regenerate all the stuff. hack/update-generated-all.sh or something like that.

**Comment by ghostsquad** [comment]
@lavalamp what's next here? there's still a `do-not-merge` label, and I'm not sure what I need to do.

**Pull request merged**
