### PR TITLE
Add CentOS to SaltStack configuration for Kubernetes

### PR DESCRIPTION
**Pull request by zreigz**
As a Fujitsu we are interested to add support for CentOS distribution. Currently we have patch for this file but the best approach is adding this to repository.

### CODE REVIEW

**Comment by davidopp** [comment]
How does this change the instructions here?
https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/centos/centos_manual_config.md

**Comment by zreigz** [comment]
This is manual step how to create kubernetes on CentOS. My change is for salt script. We would like make installation fully automatic. Currently salt installation supports pure Fedora but not CentOS distribution. Maybe my commit is misleading . It should be "Add CentOS to SaltStack configuration for Kubernetes"

**Comment by davidopp** [comment]
Thanks for the explanation. I don't know anything about Salt syntax, but is there some way to use parentheses to do grouping so this reads "if (X and Y) or (A and B)" rather than "if X and Y or A and B"  to make it clearer?

**Comment by davidopp** [comment]
ok to test

**Comment by davidopp** [comment]
ping -- please see my question here
https://github.com/kubernetes/kubernetes/pull/20704#issuecomment-185084625

**Comment by zreigz** [comment]
Sorry for delay I will check and test this grouping and let you know

**Comment by zreigz** [comment]
I've added additional brackets and tested it. Works fine. PTAL

**Comment by davidopp** [comment]
LGTM

**Comment by zreigz** [comment]
Thanks a lot

**Pull request merged**
