### PR TITLE
Automated cherry pick of #46360 upstream release 1.7

### PR DESCRIPTION
**Pull request by seanknox**
Cherry pick of #46360 on release-1.7.

#46360: Azure PD (Managed/Blob)

### CODE REVIEW

**Comment by seanknox** [comment]
This builds on other cherry picks in progress. Please merge these PRs first:
- #48961 
- #49049 
- #49054

The actual change set is identical to PR #46360.

**Comment by seanknox** [comment]
I need to fix go/BUILD dependencies in one of the preceding PRs. On it.

**Comment by jdumars** [comment]
@wojtek-t this and #49054 (a pre-requisite for this implementation of the fix) Addresses the current issues with Blob Disks:
* Significantly faster attach process. Disks are now usually available for pods on nodes under 30 sec if formatted, under a min if not formatted.
* Adds support to move disks between nodes.
* Adds consistent attach/detach behavior, checks if the disk is leased/attached on a different node before attempting to attach to target nodes.
* Fixes a random hang behavior on Azure VMs during mount/format (for both blob + managed disks).
* Fixes a potential conflict by avoiding the use of disk names for mount paths

**Comment by jdumars** [comment]
@wojtek-t this PR is a pre-requisite for this implementation of the fixes below (as outlined in #49056 ).

Addresses the current issues with Blob Disks:
* Significantly faster attach process. Disks are now usually available for pods on nodes under 30 sec if formatted, under a min if not formatted.
* Adds support to move disks between nodes.
* Adds consistent attach/detach behavior, checks if the disk is leased/attached on a different node before attempting to attach to target nodes.
* Fixes a random hang behavior on Azure VMs during mount/format (for both blob + managed disks).
* Fixes a potential conflict by avoiding the use of disk names for mount paths

**Comment by wojtek-t** [comment]
Can you please squash the commits?

**Comment by wojtek-t** [comment]
@seanknox - can you please fix the tests and squash commits (I'm assuming this is built on top of the other PR, right)?

@brendandburns - can you please lgtm and approve this PR?

**Comment by seanknox** [comment]
@wojtek-t absolutely. will do.

**Comment by brendandburns** [comment]
/retest

Something is messed up, those declarations are gone...

**Comment by seanknox** [comment]
Hey @wojtek-t, @brendanburns is happy to baby-sit the PR. Are you ok with with him marking it cherry-pick approved?

**Comment by brendandburns** [comment]
/lgtm
/approve

@wojtek-t these is ready to merge...

**Pull request merged**
