### PR TITLE
Automated cherry pick of #46542

### PR DESCRIPTION
**Pull request by jsravn**
Cherry pick of #46542  on release-1.7.

#53239: Ignore pods for quota marked for deletion whose node is unreachable

### CODE REVIEW

**Comment by jsravn** [comment]
Not sure why, but the cherry pick tool failed to create the PR so I did it manually.
```
+++ Creating a pull request on GitHub at jsravn:automated-cherry-pick-of-#46542-upstream-release-1.7     
Aborted: 1 commits are not yet pushed to upstream/release-1.7                                            
(use `-f` to force submit a pull request anyway)                                                         
                          
+++ Returning you to the master branch and cleaning up.                                                  
```

**Comment by wojtek-t** [comment]
@jsravn - this doesn't pass validate (gofmt is failing) - please fix.

**Pull request merged**
