### PR TITLE
fix: code style untidy  and update version.sh

### PR DESCRIPTION
**Pull request by cubxxw**
#### What type of PR is this?

/kind cleanup

Fixed code style untidy

### CODE REVIEW

**Review by justankiit — COMMENTED** [review]
Looks ok, What others say?

**Review by swatisehgal — COMMENTED** [review]
/lgtm

**Comment by cubxxw** [comment]
@swatisehgal When you have a moment, would you kindly consider taking a look at this PR? I would greatly appreciate it. Thank you so much for your time and assistance.

**Comment by swatisehgal** [comment]
The PR looks good to me. We need SIG CLI approval on this PR.

/assign @soltysh
for approval

**Comment by dims** [comment]
one liner to fix a space

/approve
/lgtm

**Pull request merged**
