### PR TITLE
kubeadm: remove the manual conversion from versioned cluster cfg to internal cfg

### PR DESCRIPTION
**Pull request by chendave**
The manual conversion was needed to adapt `ClusterConfiguration.DNS` from v1beta2 to v1beta3, now that v1beta2 is removed from the code base, the manual conversion is unnecessary as well.

This helps to reduce the maintenance efforts.

/kind cleanup

Signed-off-by: Dave Chen <dave.chen@arm.com>

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
As I asked, I am not sure the drop of the v1beta2 support is the right thing to do, but if it does then this change make sense. @neolit123 @pacoxu

**Review by neolit123 — COMMENTED** [review]
/approve

**Pull request merged**
