### PR TITLE
kubelet: remove unused bandwidth shaping teardown code

### PR DESCRIPTION
**Pull request by dcbw**
Since v1.5 and the removal of --configure-cbr0:

0800df74abab11ba43ac53b345653e4b814ed77b "Remove the legacy networking mode --configure-cbr0"

kubelet hasn't done any shaping operations internally.  They
have all been delegated to network plugins like kubenet or
external CNI plugins.  But some shaping code was still left
in kubelet, so remove it now that it's unused.

@freehan @thockin @bprashanth

### CODE REVIEW

**Comment by freehan** [comment]
woohoo
/lgtm
/approve

There is a PR open against the cni repo to add a tc traffic shaper plugin

**Comment by thockin** [comment]
/approve

Fix relnotes please

**Comment by dcbw** [comment]
removing do-not-merge because release-note-none has been added.  hope that's ok

**Comment by dcbw** [comment]
@thockin I did fix them like 30s after the bot added the label, but it seems the bot doesn't recheck that often?

**Comment by dcbw** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this issue https://github.com/kubernetes/kubernetes/issues/46982

**Comment by dcbw** [comment]
@freehan what should this one get milestoned to?  1.8?

**Review by pmichali — COMMENTED** [review]
/lgtm

**Comment by dcbw** [comment]
@freehan @pmichali rebased to fix conflict, another lgtm would be great thanks!

**Pull request merged**
