### PR TITLE
[Federation] Remove federat{ed,ion} prefixes from e2e file names since they are all now scoped under the e2e_federation package.

### PR DESCRIPTION
**Pull request by madhusudancs**
This is purely cosmetic.

```release-note
NONE
```

cc @kubernetes/sig-federation-pr-reviews

### CODE REVIEW

**Comment by shashidharatd** [comment]
@madhusudancs, need to update bazel build files for this. please update.

**Comment by madhusudancs** [comment]
@shashidharatd pushed the BUILD file updates. Thanks for the LGTM.

**Comment by liggitt** [comment]
removing from milestone, not sure why this would need to be in 1.6

**Comment by madhusudancs** [comment]
Federation e2es are still not fully green or are very flaky. I expect to make a number of changes in those files in the coming weeks, in the v1.6 timeframe. I don't want to be rebasing this trivial PR. I would like to get this merged ASAP. Adding the milestone back.

**Comment by madhusudancs** [comment]
@liggitt rebase hell is here! And it is real! This was exactly what I wanted to avoid.

**Comment by liggitt** [comment]
this was when the queue was 80 deep a day before code freeze. was trying to clear the queue of cosmetic refactors

**Comment by madhusudancs** [comment]
@liggitt fair enough.

**Comment by madhusudancs** [comment]
@k8s-bot kops aws e2e test this

**Comment by madhusudancs** [comment]
@k8s-bot kops aws e2e test this
@k8s-bot cvm gce e2e test this

**Pull request merged**
