### PR TITLE
Use Go canonical import paths

### LINKED ISSUE #29014: Use Go canonical import paths
I think we should follow https://golang.org/doc/go1.4#canonicalimports and decorate all of our packages with their canonical paths.  It's sort of tedious, but I have heard a few people who were unhappy that our code lives in `github.com/kubernetes/kubernetes`, but our go import is `k8s.io/kubernetes`.

This should at least cause a more obvious error.

I suppose that means that every package gets a doc.go with this declaration.

### PR DESCRIPTION
**Pull request by dims**
Add canonical imports only in existing doc.go files.
https://golang.org/doc/go1.4#canonicalimports

Fixes #29014

### CODE REVIEW

**Comment by dims** [comment]
@thockin PTAL when you get a chance

**Comment by thockin** [comment]
LGTM.  Copying a few Go wizards for cross -check for bad-idea-ness :)

@lavalamp @krousey @jfrazelle 

I'm going to assign this to Jessie, since I will be out for a few days, and see no other reason not to merge this.

**Comment by jfrazelle** [comment]
cool changes look good to me, is there a way to make sure new ones added have this I wonder?

**Comment by jfrazelle** [comment]
we could probably make some sort of script but I'll save for a follow up PR, and play with somethings

**Comment by dims** [comment]
@thockin @jfrazelle thanks for the vote of confidence :)

**Pull request merged**
