### PR TITLE
Simplified return statements in conversion.go in v1beta1 and v1beta2

### PR DESCRIPTION
**Pull request by surajnarwade**
Simplifies return statements

```release-note
NONE
```

### CODE REVIEW

**Comment by m1093782566** [comment]
@surajnarwade Thanks for this cleanup,

I find,

https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/v1beta1/conversion.go#L312-L315

https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/v1beta1/conversion.go#L328-L331

...

have the same issue, can you fix them in passing?

**Comment by surajnarwade** [comment]
@m1093782566 , Thanks, will send the fix soon :)

**Comment by m1093782566** [comment]
/lgtm

thanks!

**Comment by surajnarwade** [comment]
keep-open

**Pull request closed without merging**
