### PR TITLE
Fix API comment for the Job ready field

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind documentation
/kind api-change

#### What this PR does / why we need it:

Fixes the comment after graduation to GA.

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/enhancements/issues/2879

#### Does this PR introduce a user-facing change?

```release-note
Fix API comment for the Job Ready field in status
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2879-ready-pods-job-status
```

### CODE REVIEW

**Review by liggitt — COMMENTED** [review]
/lgtm
/approve

**Comment by kannon92** [comment]
needs a label for 1.29 if we want it in this release.

@liggitt can you add a milestone to this?

**Comment by liggitt** [comment]
/milestone v1.29

doc-only change reflecting field state in 1.29

**Pull request merged**
