### PR TITLE
kubelet/rkt: Add KillPod() and GetPodStatus() for rkt.

### PR DESCRIPTION
**Pull request by yifan-gu**
@vmarmol @dchen1107 @jonboulle @bakins

This adds KillPod() and GetPodStatus() .

Woo! Final PR to close #7244

We need another one or two for implementing the `syncPod` for rkt, so we can have it running!

:zap: :zap: :zap:

### CODE REVIEW

**Comment by vmarmol** [comment]
LGTM

**Comment by yifan-gu** [comment]
Rebased, think the last three will conflict with each other. But I will rebase

**Comment by vmarmol** [comment]
LGTM

**Comment by vmarmol** [comment]
@yifan-gu and this one needs a rebase too

**Comment by yifan-gu** [comment]
Rebased. Think will need another one for this.

Git doesn't report conflict when both commits add the same thing. Awesome!

**Comment by vmarmol** [comment]
CI failure:

```
pkg/kubelet/rkt/rkt.go:551: r.GetPods undefined (type *Runtime has no field or method GetPods)
```

**Comment by yifan-gu** [comment]
I know, it depends that GetPods PR..

**Comment by vmarmol** [comment]
aaah, got it :)

**Comment by vmarmol** [comment]
@yifan-gu GetPods should be in

**Comment by yifan-gu** [comment]
@vmarmol Should be good now!

**Comment by vmarmol** [comment]
LGTM, will wait for the CI before merging. Looks like this is the last one for the day :) I have the `SyncPod` PR almost ready, will likely send out later tonight. Thanks for the heroic push @yifan-gu! The end is in sight.

**Comment by yifan-gu** [comment]
THANK YOU FOR FAST REVIEW AND MERGE!!!! @vmarmol !!
I will have the SyncPod for rkt tonight too!

Might need one or two more to make the interfaces same. And will need one for adding flags to enable rkt in kubelet!

:rocket: :rocket: :rocket:

**Comment by vmarmol** [comment]
In #7610 I do have the runningPod in `SyncPod()` I need to think a bit more if we need it or not. Safer if we have it...

**Comment by vmarmol** [comment]
IT IS GREEN! Merging.

**Comment by yifan-gu** [comment]
@vmarmol Yes, as I remember, the pods are splitted into pod by pod workers. We need to rethink about that. But it's safer and smoother to have runningPod for now :)

**Comment by pmorie** [comment]
Teamwork! :trophy:

**Pull request merged**
