### PR TITLE
Multi-arch images for apparmor-loader container

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

Originally from:
https://github.com/kubernetes/contrib/tree/master/apparmor/loader

Moving the code here to prevent bit-rot and to be sure we can recreate
or update the images on demand. Moving it here also ensures we can use
the common harness to build the multi-arch manifests needed for running
the apparmor e2e test can run on multiple architectures.

Change-Id: Idece17c494fc944c0aaef64805d2f0e3c4d7fb28

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
related to https://github.com/kubernetes/kubernetes/issues/66986

**Review by mkumatag — APPROVED** [review]
nit: update the copyright year to 2018 for dockerfile, makefile.
/lgtm

**Comment by mkumatag** [comment]
@dims make sure we remove files from that targeted repo and add a redirection here!

**Comment by mkumatag** [comment]
@dims do you mind adding that README.md file as well?

**Comment by spiffxp** [comment]
contacted by @dims on slack, pushed new images

https://gist.github.com/spiffxp/276178abc4682a7ae3089b2bb5ea2b35

**Comment by spiffxp** [comment]
/approve
I'll leave someone else to /lgtm

/hold
Please remove once you've opened an issue to remove this code from contrib once this is proven to work.  

Yay removing code from contrib.

**Pull request merged**
