### PR TITLE
fix todo in util/iptables

### PR DESCRIPTION
**Pull request by Lion-Wei**
**What this PR does / why we need it**:

1. Use 'iptables -S` add `checkChain` function.

2. Check Chain exists before delete it.

3. Add `checkChain` in `ensureChain`, so that we don't need create a chain to see whether it already exist.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
First, you have to remove the .a file :)

Second, I appreciate cleaning up the mess!  Before we can merge this, though, we need to do scale testing.  We know that, with 10,000 Services some iptables operations slow down dramatically (e.g. 10s of seconds to iptables-restore).  I don't know if that applies to `-S` but I have to believe it does, which means this will hurt us badly (2x as many operations on create/destroy).  If we want to push this through, can you please instantiate 5000 Services on your test cluster, and see how bad iptables-save/iptables-restore is, and then run `time iptables -S` on both existing and non-existing chains, and bring that data back here?

**Comment by Lion-Wei** [comment]
@thockin Thanks  for replaying.
I understand your concern. I haven't tested it yet, but I think it very likely take more time.
On the other hand, I do think when we using `DeleteChain` and get an error, we need to find out this it is because the chain doesn't not exist or other reason. And may also need this check chain exist or not when using `FlushChain/EnsureChain`. 
Besides, when there are lots chain to delete, people may not use `DeleteChain` but use `Save` and `Restore` instead.
So IMO, we do need a interface to check a chain exist or not, or maybe make some change in `DeleteChain` to let people get more information.
If there are something wrong in my thought, please point it out, thanks.

**Comment by thockin** [comment]
Do some scale tests and assign back to me when ready to discuss.

**Pull request closed without merging**
