### PR TITLE
Make CRI v1 the default and allow a fallback to v1alpha2

### PR DESCRIPTION
**Pull request by ehashman**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Picks up from https://github.com/kubernetes/kubernetes/pull/106006 - @saschagrunert is OOO.

#### Which issue(s) this PR fixes:

Beta implementation for https://github.com/kubernetes/enhancements/issues/2040

#### Special notes for your reviewer:

Identical to https://github.com/kubernetes/kubernetes/pull/106006 but rebased against latest master and adds unit test suggested in https://github.com/kubernetes/kubernetes/pull/106006#issuecomment-971004230

/assign @liggitt @mrunalp 

#### Does this PR introduce a user-facing change?

```release-note
CRI v1 is now the project default. If a container runtime does not support the v1 API, Kubernetes will fall back to the v1alpha2 implementation.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/2040
```

### CODE REVIEW

**Comment by liggitt** [comment]
/approve
for vendor update

Thanks for pulling in the equality unit test check 

will defer the node API approval to node folks

**Review by mrunalp — APPROVED** [review]

**Comment by ehashman** [comment]
flake https://github.com/kubernetes/kubernetes/issues/106367

/test pull-kubernetes-node-e2e-containerd

**Comment by wyuan1704** [comment]
Hi @ehashman, this PR is a great example for migrating CRI v1alpha2 to v1.  pkg/kubelet/cri/remote/conversion.go and 
something in pkg/kubelet/cri/remote/remote_image.go like determineAPIVersion are the common code for the migration. Do you mind porting those common things to https://github.com/kubernetes/cri-api/tree/master/pkg/apis/runtime?

**Comment by liggitt** [comment]
I wouldn't recommend that… that would immediately attract external callers and remove our ability to easily drop this code when the v1 and v1alpha2 types diverge, which was the plan for this

**Pull request merged**
