### PR TITLE
Automated cherry pick of #11137 upstream release 1.0

### PR DESCRIPTION
**Pull request by davidopp**
Justification: fixes a Shippable failure

@zmerlynn

### CODE REVIEW

**Comment by zmerlynn** [comment]
It doesn't look like #11129 is present on `release-1.0`. Do you want to propose the combo #11129 & #11137, or neither? (You can tell from the actual content of this c-p, btw. It's a noop.)

**Comment by davidopp** [comment]
Good question.

Before sending this cherrypick, I tried to figure out whether it is actually necessary.

I used the Github source code browser to select the release-1.0 branch, and examined the file ```docs/kubectl_patch.md```. The "Auto generated..." line I saw at the bottom of that file matched the "source" version of the file in the diff for this PR (#11190). So I assumed that this PR was necessary.

However, I think you're probably right that #11129 is the PR that actually caused the breakage, hence this PR is not necessary.

**Comment by davidopp** [comment]
BTW is Shippable that runs against these cherrypick PRs actually running against the 1.0 branch rather than master?

**Comment by zmerlynn** [comment]
Yeah, Shippable is actually pulling `release-1.0`. It went green after #11160 went in, I think.

**Comment by zmerlynn** [comment]
Closing this for now.

**Pull request closed without merging**
