### PR TITLE
Automated cherry pick of #27265

### LINKED ISSUE #32704: MetricsGrabber should grab all metrics from API server.
MetricsGrabber should grab all metrics from API server.

https://k8s-testgrid.appspot.com/release-1.4-blocking#gke-1.2-1.4-upgrade-cluster

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke-1.2-1.4-upgrade-cluster/6162

### PR DESCRIPTION
**Pull request by gmarek**
Fix #32704

Cherry pick of #27265 on release-1.2.

cc @davidopp 

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33078)

### CODE REVIEW

**Comment by gmarek** [comment]
@eparis - the milestone 1.2 is set, but cherrypick-bot keeps removing `cherrypick-candidate` label.

**Comment by eparis** [comment]
who created a milestone called `1.2`? That's not a valid milestone....  /me goes to delete whatever that junk is.

**Comment by pwittrock** [comment]
@gmarek I think I cherrypicked a change to skip these tests in 1.2 yesterday.  Does your PR revert that (looks like it is addressing the root cause)?

**Comment by gmarek** [comment]
It should fix the test, if that's what you're asking.

**Comment by pwittrock** [comment]
@gmarek Sorry, I meant to say that the test isn't going to run unless you remove this line that I added to skip it: `SkipUnlessServerVersionLT(serverVersion13, c)`

**Comment by gmarek** [comment]
IIUC smoke tests failed because they are not running for legacy releases - it shouldn't block the merge. @ixdy

**Comment by pwittrock** [comment]
@ixdy IIRC, none of the pull tests should be failing on the 1.2 branch anymore right?

**Comment by gmarek** [comment]
```
+ case "${ghprbTargetBranch:-}" in
+ echo 'PR GKE job disabled for legacy branches.'
PR GKE job disabled for legacy branches.
+ exit
[xUnit] [INFO] - Starting to record.
[xUnit] [INFO] - Processing JUnit
[xUnit] [INFO] - [JUnit] - No test report file(s) were found with the pattern '_artifacts/**.xml' relative to '/var/lib/jenkins/workspace/kubernetes-pull-build-test-gci-e2e-gke' for the testing framework 'JUnit'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'JUnit'?
[xUnit] [ERROR] - No test reports found for the metric 'JUnit' with the resolved pattern '_artifacts/**.xml'. Configuration error?.
[xUnit] [INFO] - Failing BUILD.
[xUnit] [INFO] - There are errors when processing test results.
[xUnit] [INFO] - Skipping tests recording.
[xUnit] [INFO] - Stop build.
```

**Comment by ixdy** [comment]
The GCI GKE build snuck in without my fix in https://github.com/kubernetes/test-infra/pull/607, so you can ignore this failure (and I'll fix it from occurring again).

**Comment by pwittrock** [comment]
@vishh Do you know why the GCI GKE smoke e2e is failing?

**Comment by vishh** [comment]
@pwittrock https://github.com/kubernetes/test-infra/pull/666 should have fixed it I think. The tests don't have to be run on this branch.

**Comment by gmarek** [comment]
@k8s-bot gke test this issue: #IGNORE
Fixed by kubernetes/test-infra#666

**Comment by gmarek** [comment]
Hmm... previous comment didn't work.

**Pull request merged**
