### PR TITLE
Do not dirname on the dependency file's path twice while generating types using codecgen.

### LINKED ISSUE #18907: Codecgen diff in master
I get a diff when I run hack/update-codecgen in master, and the validation script fails it.  That seems wrong.

Changed files afterward:

```
$ git status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   cmd/libs/go2idl/client-gen/testdata/apis/testgroup/types.generated.go
        modified:   cmd/libs/go2idl/client-gen/testdata/apis/testgroup/v1/types.generated.go
        modified:   pkg/apis/extensions/types.generated.go
        modified:   pkg/apis/extensions/v1beta1/types.generated.go
        modified:   pkg/apiserver/testing/types.generated.go
        modified:   pkg/kubectl/testing/types.generated.go
        modified:   pkg/storage/testing/types.generated.go
```

@ncdc has been able to reproduce something similar, but not exactly equivalent.

I'm running go 1.5.1 on Fedora 22

### PR DESCRIPTION
**Pull request by madhusudancs**
Fixes #18907.

CC'ing a lot of people to cast a wide net for reviews. The pain caused by this bug is immense, so need to get this in soon. It won't be an exaggeration if I claim that I have spent over 50% of my time since https://github.com/kubernetes/kubernetes/pull/16900#discussion_r48243033 fighting against this problem. PTAL.

cc @mikedanese @davidopp @pmorie @lavalamp

### CODE REVIEW

**Comment by pmorie** [comment]
@madhusudancs looking at the diff, it seems like we should extract some of these funcs into a utility file

**Comment by madhusudancs** [comment]
@pmorie I thought about it, but what I am afraid about extracting these into util functions and using them instead in both update- and verify- is, introducing the same bugs in both the scripts. But OTOH, we are copying the code from one another now anyway. So I am fine either way, but if we want to extract these into util functions I would like to do that in a separate follow up PR.

**Comment by pmorie** [comment]
@madhusudancs Those are valid concerns but I think copying the code is a time bomb waiting to happen. +1 to a follow-up

**Comment by smarterclayton** [comment]
I'm going to test this locally - if it works against my problem I'm going to direct merge it.

**Comment by smarterclayton** [comment]
Fixed problems I was having with #17922 on both Mac and Linux. LGTM

**Comment by pmorie** [comment]
@madhusudancs If my calculations are correct, I owe you approximately one key of beer

**Comment by pmorie** [comment]
Looks like this unblocked a branch I was having trouble in as well.  Thanks a lot @madhusudancs

**Comment by wojtek-t** [comment]
Sorry - I'm on paternity leave now.

Those changes LGTM - I missed the fact that "dirname" was added in readlinkf function during review.
Thanks for merging @smarterclayton !

**Comment by madhusudancs** [comment]
@smarterclayton Thanks for merging.

@pmorie You are welcome. I think I should also treat myself, there was so much productivity that was lost due this bug over the last few weeks :)

@wojtek-t Thanks for taking a look despite being on leave.

**Pull request merged**
