### PR TITLE
replace global registry in apimachinery with global registry in k8s.io/kubernetes

### PR DESCRIPTION
**Pull request by deads2k**
We'd like to remove all globals, but our immediate problem is that a shared registry between k8s.io/kubernetes and k8s.io/client-go doesn't work.  Since client-go makes a copy, we can actually keep a global registry with other globals in pkg/api for now.

@kubernetes/sig-api-machinery-misc @lavalamp @smarterclayton @sttts

### CODE REVIEW

**Comment by deads2k** [comment]
wow, this has been excruciatingly manual and pain filled.

**Comment by smarterclayton** [comment]
First commit looks good to me.

**Comment by smarterclayton** [comment]
I do think eventually api.Registry should be folded into Scheme, but we can do that later.  Everything Registry is doing scheme needs.

**Comment by deads2k** [comment]
> I do think eventually api.Registry should be folded into Scheme, but we can do that later. Everything Registry is doing scheme needs.

I could see that, but at the moment, I think the registry is smaller and more readable.

**Comment by deads2k** [comment]
@k8s-bot verify test this

**Pull request merged**
