### PR TITLE
storage interface: remove Backends()

### PR DESCRIPTION
**Pull request by hongchaodeng**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30197)

### CODE REVIEW

**Comment by hongchaodeng** [comment]
@xiang90

**Comment by xiang90** [comment]
Lgtm

**Comment by timothysc** [comment]
I know it's legacy that it is unused, but I think it would be useful if this were plumbed through, such that the user could see the member list.  

Thoughts?

**Comment by xiang90** [comment]
@timothysc I would suggest to remove it for now. We can always add it back when we have a real use case.

**Comment by hongchaodeng** [comment]
@timothysc 
There is already another backends() doing the same thing in storage_factory:
https://github.com/kubernetes/kubernetes/blob/master/pkg/genericapiserver/storage_factory.go#L49

For storage interface, we don't need it. Can we clean it up?

**Comment by hongchaodeng** [comment]
xref for tracking: #29888

**Pull request merged**
