### PR TITLE
[WIP] Update evanphx/json patch to v5

### PR DESCRIPTION
**Pull request by dims**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Why do we need this?
- evanphx/json-patch now has go modules - yay!
- There are some good updates for better error messages ( https://github.com/evanphx/json-patch/commit/026c730a0dcc5d11f93f1cf1cc65b01247ea7b6f )
- some panics ( https://github.com/evanphx/json-patch/commit/6c9bd73542a047157f1ec00be155eec2893a3673 )
- cleanup some RFC specified behavior ( https://github.com/evanphx/json-patch/commit/a5df74aab0efb032ca893c048330abcad0b78e6f )
- etc ...

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
ugh! we still have a reference in kustomize

```
dims@dims-a01:~/go/src/k8s.io/kubernetes$ rg '"github.com/evanphx/json-patch"'
vendor/github.com/evanphx/json-patch/BUILD
11:    importpath = "github.com/evanphx/json-patch",

vendor/github.com/evanphx/json-patch/README.md
57:	jsonpatch "github.com/evanphx/json-patch"
101:	jsonpatch "github.com/evanphx/json-patch"
148:	jsonpatch "github.com/evanphx/json-patch"
193:	jsonpatch "github.com/evanphx/json-patch"

vendor/sigs.k8s.io/kustomize/pkg/patch/transformer/patchjson6902json.go
22:	"github.com/evanphx/json-patch"
```

**Comment by lavalamp** [comment]
/assign @caesarxuchao 

Please double check since we've had ... issues with JSON libraries before. :)

**Comment by liggitt** [comment]
diff between the current patch.go (at v4.2.0) and the patch.go in v5.0.0:

```diff
git diff v4.2.0 v5.0.0 -- patch.go

diff --git a/patch.go b/patch.go
index c9cf590..e736759 100644
--- a/patch.go
+++ b/patch.go
@@ -6,6 +6,8 @@ import (
 	"fmt"
 	"strconv"
 	"strings"
+
+	"github.com/pkg/errors"
 )
 
 const (
@@ -24,6 +26,14 @@ var (
 	AccumulatedCopySizeLimit int64 = 0
 )
 
+var (
+	ErrTestFailed   = errors.New("test failed")
+	ErrMissing      = errors.New("missing value")
+	ErrUnknownType  = errors.New("unknown object type")
+	ErrInvalid      = errors.New("invalid state detected")
+	ErrInvalidIndex = errors.New("invalid index referenced")
+)
+
 type lazyNode struct {
 	raw   *json.RawMessage
 	doc   partialDoc
@@ -31,10 +41,11 @@ type lazyNode struct {
 	which int
 }
 
-type operation map[string]*json.RawMessage
+// Operation is a single JSON-Patch step, such as a single 'add' operation.
+type Operation map[string]*json.RawMessage
 
-// Patch is an ordered collection of operations.
-type Patch []operation
+// Patch is an ordered collection of Operations.
+type Patch []Operation
 
 type partialDoc map[string]*lazyNode
 type partialArray []*lazyNode
@@ -59,7 +70,7 @@ func (n *lazyNode) MarshalJSON() ([]byte, error) {
 	case eAry:
 		return json.Marshal(n.ary)
 	default:
-		return nil, fmt.Errorf("Unknown type")
+		return nil, ErrUnknownType
 	}
 }
 
@@ -91,7 +102,7 @@ func (n *lazyNode) intoDoc() (*partialDoc, error) {
 	}
 
 	if n.raw == nil {
-		return nil, fmt.Errorf("Unable to unmarshal nil pointer as partial document")
+		return nil, ErrInvalid
 	}
 
 	err := json.Unmarshal(*n.raw, &n.doc)
@@ -110,7 +121,7 @@ func (n *lazyNode) intoAry() (*partialArray, error) {
 	}
 
 	if n.raw == nil {
-		return nil, fmt.Errorf("Unable to unmarshal nil pointer as partial array")
+		return nil, ErrInvalid
 	}
 
 	err := json.Unmarshal(*n.raw, &n.ary)
@@ -191,6 +202,10 @@ func (n *lazyNode) equal(o *lazyNode) bool {
 			return false
 		}
 
+		if len(n.doc) != len(o.doc) {
+			return false
+		}
+
 		for k, v := range n.doc {
 			ov, ok := o.doc[k]
 
@@ -198,6 +213,10 @@ func (n *lazyNode) equal(o *lazyNode) bool {
 				return false
 			}
 
+			if (v == nil) != (ov == nil) {
+				return false
+			}
+
 			if v == nil && ov == nil {
 				continue
 			}
@@ -227,7 +246,8 @@ func (n *lazyNode) equal(o *lazyNode) bool {
 	return true
 }
 
-func (o operation) kind() string {
+// Kind reads the "op" field of the Operation.
+func (o Operation) Kind() string {
 	if obj, ok := o["op"]; ok && obj != nil {
 		var op string
 
@@ -243,39 +263,41 @@ func (o operation) kind() string {
 	return "unknown"
 }
 
-func (o operation) path() string {
+// Path reads the "path" field of the Operation.
+func (o Operation) Path() (string, error) {
 	if obj, ok := o["path"]; ok && obj != nil {
 		var op string
 
 		err := json.Unmarshal(*obj, &op)
 
 		if err != nil {
-			return "unknown"
+			return "unknown", err
 		}
 
-		return op
+		return op, nil
 	}
 
-	return "unknown"
+	return "unknown", errors.Wrapf(ErrMissing, "operation missing path field")
 }
 
-func (o operation) from() string {
+// From reads the "from" field of the Operation.
+func (o Operation) From() (string, error) {
 	if obj, ok := o["from"]; ok && obj != nil {
 		var op string
 
 		err := json.Unmarshal(*obj, &op)
 
 		if err != nil {
-			return "unknown"
+			return "unknown", err
 		}
 
-		return op
+		return op, nil
 	}
 
-	return "unknown"
+	return "unknown", errors.Wrapf(ErrMissing, "operation, missing from field")
 }
 
-func (o operation) value() *lazyNode {
+func (o Operation) value() *lazyNode {
 	if obj, ok := o["value"]; ok {
 		return newLazyNode(obj)
 	}
@@ -283,6 +305,23 @@ func (o operation) value() *lazyNode {
 	return nil
 }
 
+// ValueInterface decodes the operation value into an interface.
+func (o Operation) ValueInterface() (interface{}, error) {
+	if obj, ok := o["value"]; ok && obj != nil {
+		var v interface{}
+
+		err := json.Unmarshal(*obj, &v)
+
+		if err != nil {
+			return nil, err
+		}
+
+		return v, nil
+	}
+
+	return nil, errors.Wrapf(ErrMissing, "operation, missing value field")
+}
+
 func isArray(buf []byte) bool {
 Loop:
 	for _, c := range buf {
@@ -353,13 +392,17 @@ func (d *partialDoc) add(key string, val *lazyNode) error {
 }
 
 func (d *partialDoc) get(key string) (*lazyNode, error) {
-	return (*d)[key], nil
+	v, ok := (*d)[key]
+	if !ok {
+		return v, errors.Wrapf(ErrMissing, "unable to get nonexistent key: %s", key)
+	}
+	return v, nil
 }
 
 func (d *partialDoc) remove(key string) error {
 	_, ok := (*d)[key]
 	if !ok {
-		return fmt.Errorf("Unable to remove nonexistent key: %s", key)
+		return errors.Wrapf(ErrMissing, "unable to remove nonexistent key: %s", key)
 	}
 
 	delete(*d, key)
@@ -385,7 +428,7 @@ func (d *partialArray) add(key string, val *lazyNode) error {
 
 	idx, err := strconv.Atoi(key)
 	if err != nil {
-		return err
+		return errors.Wrapf(err, "value was not a proper array index: '%s'", key)
 	}
 
 	sz := len(*d) + 1
@@ -395,17 +438,17 @@ func (d *partialArray) add(key string, val *lazyNode) error {
 	cur := *d
 
 	if idx >= len(ary) {
-		return fmt.Errorf("Unable to access invalid index: %d", idx)
+		return errors.Wrapf(ErrInvalidIndex, "Unable to access invalid index: %d", idx)
 	}
 
-	if SupportNegativeIndices {
-		if idx < -len(ary) {
-			return fmt.Errorf("Unable to access invalid index: %d", idx)
+	if idx < 0 {
+		if !SupportNegativeIndices {
+			return errors.Wrapf(ErrInvalidIndex, "Unable to access invalid index: %d", idx)
 		}
-
-		if idx < 0 {
-			idx += len(ary)
+		if idx < -len(ary) {
+			return errors.Wrapf(ErrInvalidIndex, "Unable to access invalid index: %d", idx)
 		}
+		idx += len(ary)
 	}
 
 	copy(ary[0:idx], cur[0:idx])
@@ -424,7 +467,7 @@ func (d *partialArray) get(key string) (*lazyNode, error) {
 	}
 
 	if idx >= len(*d) {
-		return nil, fmt.Errorf("Unable to access invalid index: %d", idx)
+		return nil, errors.Wrapf(ErrInvalidIndex, "Unable to access invalid index: %d", idx)
 	}
 
 	return (*d)[idx], nil
@@ -439,17 +482,17 @@ func (d *partialArray) remove(key string) error {
 	cur := *d
 
 	if idx >= len(cur) {
-		return fmt.Errorf("Unable to access invalid index: %d", idx)
+		return errors.Wrapf(ErrInvalidIndex, "Unable to access invalid index: %d", idx)
 	}
 
-	if SupportNegativeIndices {
-		if idx < -len(cur) {
-			return fmt.Errorf("Unable to access invalid index: %d", idx)
+	if idx < 0 {
+		if !SupportNegativeIndices {
+			return errors.Wrapf(ErrInvalidIndex, "Unable to access invalid index: %d", idx)
 		}
-
-		if idx < 0 {
-			idx += len(cur)
+		if idx < -len(cur) {
+			return errors.Wrapf(ErrInvalidIndex, "Unable to access invalid index: %d", idx)
 		}
+		idx += len(cur)
 	}
 
 	ary := make([]*lazyNode, len(cur)-1)
@@ -462,140 +505,189 @@ func (d *partialArray) remove(key string) error {
 
 }
 
-func (p Patch) add(doc *container, op operation) error {
-	path := op.path()
+func (p Patch) add(doc *container, op Operation) error {
+	path, err := op.Path()
+	if err != nil {
+		return errors.Wrapf(ErrMissing, "add operation failed to decode path")
+	}
 
 	con, key := findObject(doc, path)
 
 	if con == nil {
-		return fmt.Errorf("jsonpatch add operation does not apply: doc is missing path: \"%s\"", path)
+		return errors.Wrapf(ErrMissing, "add operation does not apply: doc is missing path: \"%s\"", path)
+	}
+
+	err = con.add(key, op.value())
+	if err != nil {
+		return errors.Wrapf(err, "error in add for path: '%s'", path)
 	}
 
-	return con.add(key, op.value())
+	return nil
 }
 
-func (p Patch) remove(doc *container, op operation) error {
-	path := op.path()
+func (p Patch) remove(doc *container, op Operation) error {
+	path, err := op.Path()
+	if err != nil {
+		return errors.Wrapf(ErrMissing, "remove operation failed to decode path")
+	}
 
 	con, key := findObject(doc, path)
 
 	if con == nil {
-		return fmt.Errorf("jsonpatch remove operation does not apply: doc is missing path: \"%s\"", path)
+		return errors.Wrapf(ErrMissing, "remove operation does not apply: doc is missing path: \"%s\"", path)
+	}
+
+	err = con.remove(key)
+	if err != nil {
+		return errors.Wrapf(err, "error in remove for path: '%s'", path)
 	}
 
-	return con.remove(key)
+	return nil
 }
 
-func (p Patch) replace(doc *container, op operation) error {
-	path := op.path()
+func (p Patch) replace(doc *container, op Operation) error {
+	path, err := op.Path()
+	if err != nil {
+		return errors.Wrapf(err, "replace operation failed to decode path")
+	}
 
 	con, key := findObject(doc, path)
 
 	if con == nil {
-		return fmt.Errorf("jsonpatch replace operation does not apply: doc is missing path: %s", path)
+		return errors.Wrapf(ErrMissing, "replace operation does not apply: doc is missing path: %s", path)
 	}
 
 	_, ok := con.get(key)
 	if ok != nil {
-		return fmt.Errorf("jsonpatch replace operation does not apply: doc is missing key: %s", path)
+		return errors.Wrapf(ErrMissing, "replace operation does not apply: doc is missing key: %s", path)
 	}
 
-	return con.set(key, op.value())
+	err = con.set(key, op.value())
+	if err != nil {
+		return errors.Wrapf(err, "error in remove for path: '%s'", path)
+	}
+
+	return nil
 }
 
-func (p Patch) move(doc *container, op operation) error {
-	from := op.from()
+func (p Patch) move(doc *container, op Operation) error {
+	from, err := op.From()
+	if err != nil {
+		return errors.Wrapf(err, "move operation failed to decode from")
+	}
 
 	con, key := findObject(doc, from)
 
 	if con == nil {
-		return fmt.Errorf("jsonpatch move operation does not apply: doc is missing from path: %s", from)
+		return errors.Wrapf(ErrMissing, "move operation does not apply: doc is missing from path: %s", from)
 	}
 
 	val, err := con.get(key)
 	if err != nil {
-		return err
+		return errors.Wrapf(err, "error in move for path: '%s'", key)
 	}
 
 	err = con.remove(key)
 	if err != nil {
-		return err
+		return errors.Wrapf(err, "error in move for path: '%s'", key)
 	}
 
-	path := op.path()
+	path, err := op.Path()
+	if err != nil {
+		return errors.Wrapf(err, "move operation failed to decode path")
+	}
 
 	con, key = findObject(doc, path)
 
 	if con == nil {
-		return fmt.Errorf("jsonpatch move operation does not apply: doc is missing destination path: %s", path)
+		return errors.Wrapf(ErrMissing, "move operation does not apply: doc is missing destination path: %s", path)
 	}
 
-	return con.add(key, val)
+	err = con.add(key, val)
+	if err != nil {
+		return errors.Wrapf(err, "error in move for path: '%s'", path)
+	}
+
+	return nil
 }
 
-func (p Patch) test(doc *container, op operation) error {
-	path := op.path()
+func (p Patch) test(doc *container, op Operation) error {
+	path, err := op.Path()
+	if err != nil {
+		return errors.Wrapf(err, "test operation failed to decode path")
+	}
 
 	con, key := findObject(doc, path)
 
 	if con == nil {
-		return fmt.Errorf("jsonpatch test operation does not apply: is missing path: %s", path)
+		return errors.Wrapf(ErrMissing, "test operation does not apply: is missing path: %s", path)
 	}
 
 	val, err := con.get(key)
-
-	if err != nil {
-		return err
+	if err != nil && errors.Cause(err) != ErrMissing {
+		return errors.Wrapf(err, "error in test for path: '%s'", path)
 	}
 
 	if val == nil {
 		if op.value().raw == nil {
 			return nil
 		}
-		return fmt.Errorf("Testing value %s failed", path)
+		return errors.Wrapf(ErrTestFailed, "testing value %s failed", path)
 	} else if op.value() == nil {
-		return fmt.Errorf("Testing value %s failed", path)
+		return errors.Wrapf(ErrTestFailed, "testing value %s failed", path)
 	}
 
 	if val.equal(op.value()) {
 		return nil
 	}
 
-	return fmt.Errorf("Testing value %s failed", path)
+	return errors.Wrapf(ErrTestFailed, "testing value %s failed", path)
 }
 
-func (p Patch) copy(doc *container, op operation, accumulatedCopySize *int64) error {
-	from := op.from()
+func (p Patch) copy(doc *container, op Operation, accumulatedCopySize *int64) error {
+	from, err := op.From()
+	if err != nil {
+		return errors.Wrapf(err, "copy operation failed to decode from")
+	}
 
 	con, key := findObject(doc, from)
 
 	if con == nil {
-		return fmt.Errorf("jsonpatch copy operation does not apply: doc is missing from path: %s", from)
+		return errors.Wrapf(ErrMissing, "copy operation does not apply: doc is missing from path: %s", from)
 	}
 
 	val, err := con.get(key)
 	if err != nil {
-		return err
+		return errors.Wrapf(err, "error in copy for from: '%s'", from)
 	}
 
-	path := op.path()
+	path, err := op.Path()
+	if err != nil {
+		return errors.Wrapf(ErrMissing, "copy operation failed to decode path")
+	}
 
 	con, key = findObject(doc, path)
 
 	if con == nil {
-		return fmt.Errorf("jsonpatch copy operation does not apply: doc is missing destination path: %s", path)
+		return errors.Wrapf(ErrMissing, "copy operation does not apply: doc is missing destination path: %s", path)
 	}
 
 	valCopy, sz, err := deepCopy(val)
 	if err != nil {
-		return err
+		return errors.Wrapf(err, "error while performing deep copy")
 	}
+
 	(*accumulatedCopySize) += int64(sz)
 	if AccumulatedCopySizeLimit > 0 && *accumulatedCopySize > AccumulatedCopySizeLimit {
 		return NewAccumulatedCopySizeError(AccumulatedCopySizeLimit, *accumulatedCopySize)
 	}
 
-	return con.add(key, valCopy)
+	err = con.add(key, valCopy)
+	if err != nil {
+		return errors.Wrapf(err, "error while adding value during copy")
+	}
+
+	return nil
 }
 
 // Equal indicates if 2 JSON documents have the same structural equality.
@@ -651,7 +743,7 @@ func (p Patch) ApplyIndent(doc []byte, indent string) ([]byte, error) {
 	var accumulatedCopySize int64
 
 	for _, op := range p {
-		switch op.kind() {
+		switch op.Kind() {
 		case "add":
 			err = p.add(&pd, op)
 		case "remove":
@@ -665,7 +757,7 @@ func (p Patch) ApplyIndent(doc []byte, indent string) ([]byte, error) {
 		case "copy":
 			err = p.copy(&pd, op, &accumulatedCopySize)
 		default:
-			err = fmt.Errorf("Unexpected kind: %s", op.kind())
+			err = fmt.Errorf("Unexpected kind: %s", op.Kind())
 		}
 
 		if err != nil {
```

**Comment by BenTheElder** [comment]
FWIW this is only a "major" version because I fixed it being an importable go module, otherwise this would have been a +1 minor upgrade (v4.5.0 => v4.6.0, v4.6.0 was an invalid module)

**Comment by liggitt** [comment]
and for merge.go:
```diff
git diff v4.2.0 v5.0.0 -- merge.go

diff --git a/merge.go b/merge.go
index 6806c4c..5dc6d34 100644
--- a/merge.go
+++ b/merge.go
@@ -307,10 +307,8 @@ func matchesValue(av, bv interface{}) bool {
 		return true
 	case map[string]interface{}:
 		bt := bv.(map[string]interface{})
-		for key := range at {
-			if !matchesValue(at[key], bt[key]) {
-				return false
-			}
+		if len(bt) != len(at) {
+			return false
 		}
 		for key := range bt {
 			if !matchesValue(at[key], bt[key]) {
```

**Comment by BenTheElder** [comment]
Do we have a test suite targeting the kind of issues we experience previously?

**Pull request closed without merging**
