### PR TITLE
kubeadm: Move directory ./master to ./phases/controlplane

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:

 - Moves app/master into phases/controlplane. It should be in the phases directory, was just overlooked earlier
 - Harmonizes the import names in phases/controlplane with the similar import names in cmd/kubeadm

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

Please review only second and third commit, based on https://github.com/kubernetes/kubernetes/pull/47339

Targets v1.8

**Release note**:

```release-note
NONE
```
@kubernetes/sig-cluster-lifecycle-pr-reviews @timothysc @pipejakob

### CODE REVIEW

**Comment by timothysc** [comment]
@luxas is there a Readme.md to outline the phases that we can update as we progress this cycle.

**Comment by luxas** [comment]
@timothysc Here's my WIP: https://github.com/kubernetes/kubeadm/pull/156. Will add more details soon.
When I've finalized this, I'm gonna submit it as a proposal to kubernetes/community

**Comment by timothysc** [comment]
I have no issues with the last two commits...

**Comment by luxas** [comment]
Rebased

**Pull request merged**
