### PR TITLE
v1beta1: bugfix in Event struct definition

### PR DESCRIPTION
**Pull request by beautytiger**
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>

**What type of PR is this?**

 /kind bug

**What this PR does / why we need it**:
struct definition use wrong word, it's problematic where transfer to json. mybe a bug, maybe a cleanup, you say it.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/ok-to-test

thanks for the fix, this will require regenerating API-related files. `make update` should rebuild everything needed, then commit the results.

**Comment by ethan-daocloud** [comment]
> /ok-to-test
> 
> thanks for the fix, this will require regenerating API-related files. `make update` should rebuild everything needed, then commit the results.

@liggitt 
Thanks for your guide. 
`make update` have been done, the only diff is as below:
```git
diff --git a/api/openapi-spec/swagger.json b/api/openapi-spec/swagger.json
index b77e3c3d0b..6f2dd4d8dc 100644
--- a/api/openapi-spec/swagger.json
+++ b/api/openapi-spec/swagger.json
@@ -19260,7 +19260,7 @@
   },
   "info": {
     "title": "Kubernetes",
-    "version": "v1.17.0"
+    "version": "v1.16.0"
   },
   "paths": {
     "/api/": {
```
the swagger version have downgraded. better not commit this change, right?

**Comment by liggitt** [comment]
ah, the `+optional` in the comments already marked the openapi fields as optional

/lgtm
/approve

**Comment by liggitt** [comment]
This fixed a staticcheck failure. Please remove the line from the staticcheck blocked list. 

/lgtm cancel

**Comment by liggitt** [comment]
See https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/81359/pull-kubernetes-verify/1164689223266078721 for details

**Comment by beautytiger** [comment]
@liggitt 
Thanks, done as your guide.

**Pull request merged**
