### PR TITLE
test/e2e: fix `ginkgo ./test/e2e`

### LINKED ISSUE #74827: test/e2e: no longer started correctly by gingko
**What happened**:

When invoking ./test/e2e under ginkgo, for example with `ginkgo -focus=thereisnosuchttest ./test/e2e`, the `e2e.test` binary no longer gets passed the `-ginkgo.focus` parameter (can be verified with `strace -e trace=execve -f`). This does not break the Kubernetes CI because `kubetest` always uses `-ginkgo.focus`. I and others (https://kubernetes.slack.com/messages/C09QZ4DQB/) noticed this when testing manually.

But parallel test execution also no longer works. ~~I suspect that some Prow jobs now run slower than before~~. Actually not, the Kubernetes CI probably isn't affected because it uses a pre-built e2e.test binary. Such binaries are always assumed to be Ginkgo test suites by the ginkgo runner.

**What you expected to happen**:

The `ginkgo` test runner must recognize that `./test/e2e` contains a Ginkgo test suite and then treat it accordingly.

**How to reproduce it (as minimally and precisely as possible)**:

`strace -e trace=execve -f ginkgo -focus=nosuchtest ./test/e2e`

**Anything else we need to know?**:

In ef5f1012f687cd633f29b5e9b2b1c7ded2145195, the code that initializes Ginkgo was moved out of `e2e_test.go`. This broke the `filesHaveGinkgoSuite` test because it loads all `*_test.go` files and searches for `ginkgo` in them. In Kubernetes, the `e2e_test.go` file no longer contains the magic strings.

https://github.com/onsi/ginkgo/blob/dbaca8e5ae554fdc9905dabc83fa43d806f5d7ab/ginkgo/testsuite/test_suite.go#L101-L115

/sig testing
/cc @jayunit100

### PR DESCRIPTION
**Pull request by pohly**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

When running ginkgo directly against the source code of the test suite
instead of using some pre-compiled e2e.test binary, ginkgo no longer
recognized that it runs a Ginkgo testsuite, which broke "-focus" and
"-p".

By re-inserting the magic strings that ginkgo looks for into a
comment, we can restore the desired behavior without affecting the
code.

**Which issue(s) this PR fixes**:
Fixes #74827

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig testing
/priority important-soon

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
this is quite hacky but LGTM.
i.e. i don't have alternative proposals.

/lgtm
/assign @saad-ali @timothysc

**Review by timothysc — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
