### PR TITLE
Fix apiserver_request_count metric

### LINKED ISSUE #16421: "apiserver_request_count" metric doesn't handle correctly http codes
When looking into those metrics, the code is always 200.

I explicitly send a bad request:
wojtekt@wojtekt-work:~/go/src/k8s.io/kubernetes/pkg/labels$ curl localhost:8080/api/v1/pods?timeoutSeconds=xxx
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "strconv.ParseInt: parsing \"xxx\": invalid syntax",
  "reason": "BadRequest",
  "code": 400
}

and in metrics it was reported as code "200".

cc @lavalamp @kubernetes/goog-csi

### PR DESCRIPTION
**Pull request by wojtek-t**
Previously, the code in this metric was always "200"

Fix #16421

@lavalamp @smarterclayton

### CODE REVIEW

**Comment by wojtek-t** [comment]
BTW - thanks to this PR, we will get ~ metric of "too old RV" for free (IIUC, we are using 410 error only for this now) <-- @lavalamp

**Comment by smarterclayton** [comment]
This change was deliberate (to not use the go-restful wrapper), because with the upcoming watch changes watch won't be on go-restful.  Is there a way to fix this without changing scope error?

**Comment by smarterclayton** [comment]
Shouldn't our error handling be on the underlying request, not on
go-restful?

**Comment by wojtek-t** [comment]
T problem is that IIUC, ResponseWriter that we were using so far doesn't give you access to the StatusCode that has been set.

@smarterclayton - what are the plans for watch changes? I'm not aware of them...

**Comment by wojtek-t** [comment]
Also, I think that even if we don't change it for watch, but just for create/update/delete/list/get, this will add value itself.

**Comment by smarterclayton** [comment]
For protobuf serialization it's being fixed to properly deal with codecs
and streaming codecs.  As part of that split it's in a code path that
doesn't have access to go restful.  In addition, we've been trying to
firewall go-restful so that we aren't so dependent on it and can rip and
replace later.

Could we extend httplog to handle this recording aspect?  I realize our
metrics wrapper leverages go-restful, but we are also missing things like
watches, downloads, logs, and exec today because those unwrap the response
writer.

On Mon, Feb 8, 2016 at 2:40 PM, Wojciech Tyczynski <notifications@github.com

**Comment by lavalamp** [comment]
I see lots of call site changes but no change to the functions; is this a case where people were passing the wrong thing to an interface? Can we add some assertions or change the type to make sure people pass the right thing? Otherwise stuff will silently get dropped if anyone accidentally passes the wrong thing.

**Comment by lavalamp** [comment]
Also, the log hooks into this by replacing the ResponseWriter-- could you hook into that mechanism instead? I have more confidence that that will always be right.

**Comment by smarterclayton** [comment]
One downside is that those also unwrap the response object as normal,
so all log running operations (or most), escape.  I agree having a
test would be good.

I really want to stay independent of go-restful - it adds very little
to our flow except route handling and swagger.

**Comment by wojtek-t** [comment]
Thanks for comments! I will try to do it in a slightly different way.

**Comment by wojtek-t** [comment]
Actually - it was already fixed by #19559 :)

**Pull request closed without merging**
