### PR TITLE
Take the context as the first argument of Schedule

### PR DESCRIPTION
**Pull request by wgliang**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
According to https://github.com/kubernetes/kubernetes/pull/81876#discussion_r318098972

FYI:https://golang.org/pkg/context/
The Context should be the first parameter

So we will take the context as the first argument of Schedule()

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Take the context as the first argument of Schedule.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
Technically yes, although this is not the real context.Context.

Prefer to incorporate this changes in #82072 where introduced the real context.Context.

cc/ @draveness

**Comment by wgliang** [comment]
> Technically yes, although this is not the real context.Context.
> 
> Prefer to incorporate this changes in #82072 where introduced the real context.Context.
> 
> cc/ @draveness

Agree with that. It looks better.

**Comment by wgliang** [comment]
/cc @ahg-g 
Any suggestions? Does this PR need to continue?

**Comment by draveness** [comment]
> Any suggestions? Does this PR need to continue?

I believe this was superseded by #82072 :)

**Comment by Huang-Wei** [comment]
@wgliang Would you mind closing this in favor of #82072?

**Pull request merged**
