### PR TITLE
Cleanup: Remove unused lastContainerStartedTime time.Cache lru

### PR DESCRIPTION
**Pull request by azylinski**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

On Jul 21, 2020 @liggitt added "Ensure runtimeCache contains all observed started containers on pod delete": [change](https://github.com/kubernetes/kubernetes/commit/d195fc2ec864988d1375f8a14bc7dbaacc6a1b95#diff-67dd9e8f3ee257072765326cb4f242852554a2c0753563fa51e292c0a63a7b94R1662)

On Jul 9, 2021 main part of this functionality was replaced: [change](https://github.com/kubernetes/kubernetes/commit/dab6f6a43d5a41ef3e2aa11d4a85c45a268ac6cd#diff-67dd9e8f3ee257072765326cb4f242852554a2c0753563fa51e292c0a63a7b94L1801) , but the lastContainerStartedTime cache left.

The lru cache is being populated and updated, but it's no longer read from.
As a result, since v1.22 onwards, we're building a latest containerStarted events log which is unnecessary.
And, IMHO, it could/should be removed.

#### Does this PR introduce a user-facing change?

NONE

### CODE REVIEW

**Comment by pacoxu** [comment]
/release-note-none
SGTM and will take a look later

**Review by endocrimes — COMMENTED** [review]
makes sense to me.

/lgtm

**Comment by azylinski** [comment]
@endocrimes , since there're LGTMs and tests passed, my I ask kindly for Approval? :)

**Comment by endocrimes** [comment]
/triage accepted

/priority important-longterm
(code hygiene is important, wanna stop backlogging it) 

@azylinski I don't have node approver bits outside of `test/{e2e,e2e_node}/`

/assign @mrunalp

**Comment by azylinski** [comment]
Closing in favor of https://github.com/kubernetes/kubernetes/pull/111932

**Pull request closed without merging**
