### PR TITLE
kubeadm-validators: bump the latest validated Docker version to 19.03

### LINKED ISSUE #1821: Update min Docker-CE Version more recent version
Testing locally - 

[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 19.03.2. Latest validated version: 18.09

### LINKED ISSUE #82326: Support newer versions of docker: 19.x
**What would you like to be added**:
Support for newer docker versions: 19.x

**Why is this needed**:
New users trying to use kubernetes install the latest docker version. It's inconvenient see the following warning and have to uninstall docker and then install an older version.

`[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 19.03.2. Latest validated version: 18.09`

Also, it's not clear what could happen if someone uses a newer version of docker.
Lastly, I believe that kubernetes should be able to keep up with docker.
Is there any roadmap for this, that I have missed?

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:

19.03 has been validated for a while, see:
https://github.com/kubernetes/kubernetes/issues/82326#issuecomment-546464495

also kubekins @ test-infra is already at 19*.

**Which issue(s) this PR fixes**:

Fixes #82326
Fixes kubernetes/kubeadm#1821

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update the latest validated version of Docker to 19.03
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/assign @BenTheElder @yastij @timothysc 
/kind feature
/priority important-longterm

### CODE REVIEW

**Comment by neolit123** [comment]
@yastij if we move the validators to the new repository how would the ./hack/verify script work?
does it have to be extended to download files from another repo and check them?

**Comment by yastij** [comment]
If we want to keep them in sync yes. we’d need to discuss this with sig-release, as we’ll need to pin repo at specific git ref on `dependencies.yaml`

**Review by yastij — COMMENTED** [review]
/lgtm

**Pull request merged**
