### PR TITLE
Make etcd pass health checks on kubeadm clusters.

### PR DESCRIPTION
**Pull request by Q-Lee**
**What this PR does / why we need it**: etcd fails all health checks from the kubelet.

1. The probe is HTTP, but the endpoint is HTTPS
1. The endpoint rejects all requests without client auth

This is sub-optimal, but we need to choose between auth and health checks.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # https://github.com/kubernetes/kubeadm/issues/720

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by praseodym** [comment]
Related to https://github.com/kubernetes/kubernetes/pull/60728?

**Comment by stealthybox** [comment]
Thanks for working to address this.
@praseodym is right -- that PR implements mutual TLS on the liveness probe

**Comment by krousey** [comment]
Should we close this in favor of https://github.com/kubernetes/kubernetes/pull/60728 ?

**Comment by stealthybox** [comment]
@krousey I believe that's appropriate

**Pull request closed without merging**
