### PR TITLE
Check for initial kubelet certificates more frequently

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Improves response time of kubelet to initial client certificate issuance

#### Which issue(s) this PR fixes:

Related to https://github.com/kubernetes/kubernetes/issues/112170

#### Special notes for your reviewer:

Alternative to https://github.com/kubernetes/kubernetes/pull/112240

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by chenk008** [comment]
It looks good to me. @liggitt Is there anything else that I can do to help expedite the PR process?

**Comment by liggitt** [comment]
cc @enj for review

**Pull request merged**
