### PR TITLE
Delete evictions_test.go

### LINKED ISSUE #39412: go vet check failed
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

go vet check
src\github.com\kubernetes\kubernetes\test\integration\evictions\eviction
s_test.go:214: unreachable code
src\github.com\kubernetes\kubernetes\test\integration\evictions\eviction
s_test.go:188: result of fmt.Errorf call not used

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

### PR DESCRIPTION
**Pull request by calebamiles**
There seem to be several problems with the test for parallel eviction

1. The check `if errors.IsConflict(err)` on line 187 seems to incorrectly use `err` declared on line 138 rather than using `e` declared on line 177

2. Lines 213 - 226 are unreachable due to the non terminating `for` loop on line 199

3. Line 188 _creates_ a new `error` but does nothing with it, possibly `t.Errorf` was intended to be called rather than `fmt.Errorf`

4. Line 226 will likely leak `stopCh` as the line is unreachable due to #2

5. Neither `doneCh` or `errCh` are ever closed and will probably leak

6. Reading errors from `errCh` on line 201 will return after the first error which prevents any other errors sent on the channel from being exposed

This test is probably important but I have fairly little confidence in the correctness of the current implementation so it might be better to try again.

**What this PR does / why we need it**:

Deletes a probably broken test

**Which issue this PR fixes** 

fixes #39412

**Special notes for your reviewer**:

This functionality probably needs testing but I can't claim to have the expertise required to do so correctly.

**Release note**:

`NONE`

### CODE REVIEW

**Comment by calebamiles** [comment]
Could someone from @kubernetes/sig-api-machinery-misc please take a look. Thanks!


cc: @ymqytw

**Comment by ymqytw** [comment]
> 3. Line 226 will likely leak stopCh as the line is unreachable due to #2
> 4. Neither doneCh or errCh are ever closed and will probably leak

It's not leaking channels. See: [this](http://stackoverflow.com/questions/8593645/is-it-ok-to-leave-a-channel-open)
Closing a channel is used only to signal the channel’s receivers.

> Reading errors from errCh on line 201 will return after the first error which prevents any other errors sent on the channel from being exposed.

This is intended. When an error occurs, we can just stop and error out. No need to wait for all of goroutines to complete.

I will send an PR tomorrow to fix the other bugs and make go vet happy. I will cc you on that PR.
This test is added in 1.6, we should keep it. I think we can close this PR.

**Comment by calebamiles** [comment]
Thanks for the updates @ymqytw, closing this PR. Please remember to link https://github.com/kubernetes/kubernetes/issues/39412 in your PR. Thanks!

**Comment by ymqytw** [comment]
> Please remember to link #39412 in your PR. 

Sure.

**Pull request closed without merging**
