### PR TITLE
replace contents of docs/design with stubs

### PR DESCRIPTION
**Pull request by michelleN**
**What this PR does / why we need it**:
This PR replaces the contents of docs/design with stubs to the new location of the files.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: 
This addresses part of #37827 

**Special notes for your reviewer**:
The .png files are still in place and have not been deleted in this PR.

**Release note**:

```NONE
```

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks!

@michelleN 

verify-boilerplate.sh failed for the non-markdown files. I suggest just deleting them, since they are less likely to be linked to from elsewhere.

**Comment by bgrant0607** [comment]
@michelleN Do you have time to finish this PR this week?

**Comment by michelleN** [comment]
@k8s-bot verify test this

**Comment by michelleN** [comment]
@k8s-bot cri node e2e test this

**Comment by michelleN** [comment]
sure thing @bgrant0607

**Pull request merged**
