### PR TITLE
convert current "kubectl attach" to a clean "wait" behavior

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:
When working on #52224, I found below TODO.

> // TODO: convert this to a clean "wait" behavior

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
/assign @kubernetes/sig-cli

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by shiywang** [comment]
@dixudx seems tests are broken, could you fix that ?

**Comment by dixudx** [comment]
ping @ncdc @smarterclayton PTAL.

Seems simply using `waitForPod` is not correct. If the pod status is `completed`, this will work as expected. But if the pod status is already `running`, `waitForPod` will timeout on waiting for the condition change. Actually the conditions will not get changed for such running pods.

So shall we keep it as it is or add a more complex logic to handle this?

**Comment by ncdc** [comment]
Options that might be viable:

1. Just remove the TODO and accept the current behavior
1. Modify `waitForPod` so that it does a `Get()` first and generates a synthetic `watch.Event` with the pod as `event.Object` so it can pass it to `exitCondition` to check the condition. If it's false, then start the watch loop.
1. Leave `waitForPod` alone and do something custom here (my least favorite)

**Comment by dixudx** [comment]
Option 1 is definitely the easiest way. And it is not harmful, but does not fix/improve anything.

I prefer option 2, that's exactly what I want. @ncdc Thanks for your clear clarification.

Will implement it when we reach a consensus.

**Comment by ncdc** [comment]
Option 2 has far reaching possible effects, since waitForPod is used in a lot of places. Hopefully none of the effects is harmful, but I would definitely want others to weigh in before you start any coding. cc @sttts as I think you were involved with some of this code at one point.

**Comment by smarterclayton** [comment]
The desire was to fix the generic client waiter (watch.Wait) to handle
this, either by using something like an informer (preferred) or a simpler
version.  I would prefer we fix this fundamentally and stop punting the
issue.  I.e. all of these cases basically are just a single item informer
which should be easy to create and run generically, and satisfy watch.Wait
and wait.Poll

**Comment by zjj2wry** [comment]
@dixudx ```kubectl run command --attach``` will use attachopt.run(), and in  ```kubectl run command --attach```have ```waitForPodRunning()```, this change seems will cause ```kubectl run --attach``` alway wait. please check it.

**Pull request closed without merging**
