### PR TITLE
Fix static check for pkg/controller/podautoscaler 

### PR DESCRIPTION
**Pull request by benhxy**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix static check failure for pkg/controller/podautoscaler 

**Which issue(s) this PR fixes**:
Part of #92402

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
No
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Comment by justaugustus** [comment]
/ok-to-test
LGTM for `hack/`

**Review by SataQiu — COMMENTED** [review]
/approve
for hack

**Comment by MaciekPytel** [comment]
Do we need those legacy tests @josephburnett @mwielgus? lgtm, but I'd like your opinion.

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by mwielgus** [comment]
Approving, looks like the legacy tests are not run anymore.

**Pull request merged**
