### PR TITLE
delete the for loops that done nothing

### PR DESCRIPTION
**Pull request by jianglingxia**
in the for loops do nothing

### CODE REVIEW

**Comment by enisoc** [comment]
/assign @kow3ns 

Ken, was this meant to wrap the whole test and run it multiple times?

**Comment by enisoc** [comment]
@k8s-bot ok to test

**Review by kow3ns — APPROVED** [review]
LGTM

**Comment by jianglingxia** [comment]
as i can not find the branch to rebase it ,so i push it in a new branch ,then i close the pr,thanks

**Pull request closed without merging**
