### PR TITLE
[1.21] vendor: bump runc to 1.0.1

### PR DESCRIPTION
**Pull request by kolyshkin**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Bumping runc dependency to 1.0.1, fixing a few issues.

For runc release notes, see
* 1.0.1: https://github.com/opencontainers/runc/releases/tag/v1.0.1
* 1.0.0: https://github.com/opencontainers/runc/releases/tag/v1.0.0

This is a backport of #103743 to release-1.21 branch, replacing #103392.

#### Which issue(s) this PR fixes:
Fixes: #102676

#### Special notes for your reviewer:

I am not backporting the second commit from PR #103743  as it's not important (a cleanup).

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

none

### CODE REVIEW

**Review by ehashman — COMMENTED** [review]
/ok-to-test
/triage accepted
/priority critical-urgent

/test pull-kubernetes-node-crio-cgrpv2-e2e
/test pull-kubernetes-node-kubelet-serial-crio-cgroupv1
/test pull-kubernetes-node-kubelet-serial-crio-cgroupv2
/test pull-kubernetes-node-kubelet-serial

**Comment by chrischdi** [comment]
I tried this patch by cherry-picking it to `v1.21.4-rc.0`.

I'm getting an issue regarding "slice already exists":
```
Jul 26 10:27:08 my-kube-master01 kubelet[3484]: E0726 10:27:08.143733    3484 pod_workers.go:190] "Error syncing pod, skipping" err="failed to ensure that the pod: 18f843901cb9a36d0581ec83bafff43f cgroups exist and are correctly applied: failed to create container for [kubepods burstable pod18f843901cb9a36d0581ec83bafff43f] : Unit kubepods-burstable-pod18f843901cb9a36d0581ec83bafff43f.slice already exists." pod="kube-system/etcd-my-kube-master01" podUID=18f843901cb9a36d0581ec83bafff43f
```

This log is from a fresh control plane node which uses `kubeadm init` to bootstrap the first control plane node.

However the process got stuck due to the missing etcd pod.

I also cherry-picked https://github.com/kubernetes/kubernetes/pull/102250 but I don't think this caused the issue because without this PR it was working.

We are using the systemd cgroupDriver via kubeadm config:
```
cat /tmp/kubeadm.yaml  | grep cgroup
cgroupDriver: systemd
```

**Comment by kolyshkin** [comment]
@chrischdi I took a look at the commit in this PR and it does the fix to the problem we were having (the fix is https://github.com/opencontainers/runc/pull/2997https://github.com/opencontainers/runc/pull/2997).

From what I see, this seems like a problem with cherry-picking, or building, or something similar -- but if runc/libcontainer/cgroups/systemd is used to create a slice, it never returns "unit already exist" error.

**Comment by chrischdi** [comment]
> @chrischdi I took a look at the commit in this PR and it does the fix to the problem we were having (the fix is [opencontainers/runc#2997](https://github.com/opencontainers/runc/pull/2997)).
> 
> From what I see, this seems like a problem with cherry-picking, or building, or something similar -- but if runc/libcontainer/cgroups/systemd is used to create a slice, it never returns "unit already exist" error.

@kolyshkin thanks for taking a look again and sorry for the above message. You are totally right, I made a mistake building the cherry-picked variant (typo in our build pipeline :-( so the patch was there but did not get applied)

**Comment by manugupt1** [comment]
Looks good to me. thanks
/lgtm

**Comment by liggitt** [comment]
what is the status on this? does it resolve the reported regressions in 1.21, or is there still work to do?

**Comment by kolyshkin** [comment]
> what is the status on this? does it resolve the reported regressions in 1.21, or is there still work to do?

@liggitt from my perspective, it does.

**Comment by dims** [comment]
@kolyshkin you mean this one https://github.com/kubernetes/kubernetes/issues/102676 right? are there others?

**Comment by liggitt** [comment]
dependency mechanics lgtm

needs node approval

**Comment by ehashman** [comment]
/lgtm
(late, but we need this to fix #102676 on 1.21 which is a critical regression)

**Comment by liggitt** [comment]
cc @kubernetes/release-managers for branch approval

**Comment by odinuge** [comment]
Sorry for being late, as I have had some time of/AFK after delivering my thesis.

The issues are still present here ref. https://github.com/kubernetes/kubernetes/pull/103743#issuecomment-896339048. Should we merge this, or should we hold off until properly fixed? The new "bug" is even harder to spot, and "impossible" to debug... :/

This is too late for 1.21.4 anyways, so we still need to wait for 1.21.5 either way.. :/

**Pull request closed without merging**
