### PR TITLE
reduce memory allocations in GetAllEventsSinceThreadUnsafe

### PR DESCRIPTION
**Pull request by hormes**
Ref #73958

Reduce memory copy by improving the cyclic buffer of events.

@wojtek-t

### CODE REVIEW

**Comment by wojtek-t** [comment]
@hormes - I think the gain from this PR isn't as clear as one can think so I would like to see a measured impact on our test in different dimension. I'm happy to help with that, but as of now, we have probably 3 or 4 regressions in flight and don't have enough resources to test additional stuff.

But the reason why i say it's not as obvious is that:
- once we switch on bookmarks, the number of "init events" should be drastically reduced (thus, much much less copies)
- in this PR you trade copies for additional memory allocations (and their cost is non-negligible)

So while I think it should have somewhat positive impact, it's not obvious - thus holding until we have clear data confirming this.

/hold

**Comment by hormes** [comment]
> So while I think it should have somewhat positive impact, it's not obvious - thus holding until we have clear data confirming this.

In our scenario, a list for CRs(100,000 object, similar to pod) will take up to 1 minute, and thousands of new events are generated in this minute.

**Comment by wojtek-t** [comment]
We're proceeding with a different approach which is now being implemented as part of https://github.com/kubernetes/kubernetes/issues/105274

Closing this one.

**Pull request closed without merging**
