### PR TITLE
[go1.16] Update to go1.16.4

### PR DESCRIPTION
**Pull request by justaugustus**
#### What type of PR is this?

/kind feature
/area dependency release-eng release-eng/security security

#### What this PR does / why we need it:

Cherry pick of https://github.com/kubernetes/kubernetes/pull/101809.
Update Kubernetes to go1.16.4

Tracking issue: https://github.com/kubernetes/release/issues/2060

Signed-off-by: Stephen Augustus <foo@auggie.dev>

/assign @dims @liggitt 
cc: @kubernetes/release-engineering 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Kubernetes is now built with Golang 1.16.4
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by justaugustus** [comment]
/test all
(clicked the wrong branch accidentally when opening the PR)

**Comment by justaugustus** [comment]
(wow, choosing the wrong branch is _impressively_ noisy)
/retest
/check-cla

**Comment by justaugustus** [comment]
Ahhh, these are likely jobs only on the `master` branch.

Let's try to clear the contexts...
/skip pull-kubernetes-conformance-image-test
/skip pull-kubernetes-e2e-gce-csi-serial
/skip pull-kubernetes-e2e-gce-storage-slow
/skip pull-kubernetes-e2e-gce-storage-snapshot
/skip pull-kubernetes-e2e-ubuntu-gce-network-policies
/skip pull-kubernetes-local-e2e

**Comment by justaugustus** [comment]
_grumbles_

**Comment by justaugustus** [comment]
Override for the non-existent jobs? 🤔

/override pull-kubernetes-conformance-image-test
/override pull-kubernetes-e2e-gce-csi-serial
/override pull-kubernetes-e2e-gce-storage-slow
/override pull-kubernetes-e2e-gce-storage-snapshot
/override pull-kubernetes-e2e-ubuntu-gce-network-policies
/override pull-kubernetes-local-e2e

**Comment by dims** [comment]
/approve
/lgtm

It's been a looong week for you @justaugustus :)

**Comment by justaugustus** [comment]
@kubernetes/release-managers -- Needs cherry pick approval.

/hold cancel
https://github.com/kubernetes/kubernetes/pull/101809#event-4705042126 has merged

**Comment by puerco** [comment]
Inception

**Comment by justaugustus** [comment]
Hehe, thanks Adolfo!

**Pull request merged**
