### PR TITLE
fix allow-priviledge not work in local-up-cluster

### PR DESCRIPTION
**Pull request by zhangmingld**
**What this PR does / why we need it**:
The flag --allow-priviledge does not work when we set the env "ALLOW_PRIVILEGED"
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
Is this worth doing? It's slated to be deprecated.
https://github.com/kubernetes/kubernetes/blob/bc6cb90820761699073e8c2e796b2d73c3d4310b/cmd/kubelet/app/options/options.go#L409-L411

https://github.com/kubernetes/kubernetes/issues/58010

**Comment by dims** [comment]
It's still going to be a few cycles to get rid of it. let's get it in and we can clean up when the flag is removed.

/lgtm
/approve

**Comment by cblecker** [comment]
SGTM @dims :) 👍

**Pull request merged**
