### PR TITLE
Automated cherry pick of #53239

### PR DESCRIPTION
**Pull request by enj**
Cherry pick of #53239 on release-1.8.

#53239: Correct APIGroup for RoleBindingBuilder Subjects

### CODE REVIEW

**Comment by liggitt** [comment]
/lgtm
pick needed to avoid accumulating subjects in auto-reconciled rolebindings

**Comment by liggitt** [comment]
@jpbetz for cherrypick approval

**Comment by enj** [comment]
@jpbetz bump

This is already merged in 1.7 and 1.9.

**Pull request merged**
