### PR TITLE
fix typo for daemon_controller_test.go

### PR DESCRIPTION
**Pull request by mamil**
#### What type of PR is this?
/kind documentation

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mamil** [comment]
CLA done

**Comment by mamil** [comment]
CLA check

**Review by mahalrs — APPROVED** [review]

**Review by janetkuo — APPROVED** [review]

**Comment by mamil** [comment]
hi, @mahalrs may you add the milestone v1.22 tag for this PR?

**Pull request merged**
