### PR TITLE
Automated cherry pick of #120870: update filepath-securejoin dependency to 0.2.4 to fix

### PR DESCRIPTION
**Pull request by kmala**
Cherry pick of #120870 on release-1.28.

#120870: update filepath-securejoin dependency to 0.2.4 to fix

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by liggitt** [comment]
note that this dependency is only used by the alpha kubelet system logging feature

**Pull request merged**
