### PR TITLE
Add Digital Ocean volume support

### LINKED ISSUE #32334: support for digital ocean volumes
I was wondering if there are any plans to support digital ocean volumes (similar to awsElasticBlockStore)? If not, are you open to pull requests for this feature?

### LINKED ISSUE #39326: Digital Ocean block storage
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

No.

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

Digital Ocean, digitalocean

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST.

**Kubernetes version** (use `kubectl version`):

v1.5.1

**Environment**:
- **Cloud provider or hardware configuration**: Digital Ocean 
- **OS** (e.g. from /etc/os-release): CoreOS 1185.5.0 (MoreOS)
- **Kernel** (e.g. `uname -a`): 4.7.3-coreos-r3
- **Install tools**: manual
- **Others**: Flocker v1.15.0

**What happened**:

Seems that now there is no way to use Digital Ocean block storage as persistent volumes in k8s (cloud provider doesn't exist in `pkg/cloudprovider/providers`). Tried it in conjunction with flocker (with [this dataset plugin](https://github.com/ngrewe/digitalocean_flocker_plugin)) and got:

`Output: mount: special device /flocker/b3beb5d6-0919-47b4-9a05-1f6d9b45eb3c does not exist`.

**What you expected to happen**:

Successful mount of volume.

**How to reproduce it** (as minimally and precisely as possible):

Install flocker as per their manual, install Digital Ocean plugin, then try k8s flocker-web demo application.

**Anything else do we need to know**:

I searched issues and found #34783, but it focuses on cluster initial install rather than storage support.

### PR DESCRIPTION
**Pull request by odacremolbap**
**What this PR does / why we need it**:
This PR Adds Digital Ocean Volume plugin for Kubernetes.
Provisioning is done using Digital Ocean API, using [godo](https://github.com/digitalocean/godo).

**Which issue this PR fixes** 
fixes #39326 , fixes #32334

**Special notes for your reviewer**:
~~No generated items have been added~~
~~No dependencies have been added~~
The plugin is heavily based on existing plugins

To try this plugin:
Create a secret at kube-system namespace that includes
- DO API Token
- DO Region for the kubernetes cluster
- secret type `kubernetes.io/digitalocean-volume`
```
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean
  namespace: kube-system
type: kubernetes.io/digitalocean-volume
data:
  token: <digital-ocean-token>
  region: <digital-ocean-region>
```

Create a storage class using `kubernetes.io/digitalocean-volume` provisioner.
(setting the SC as default is optional)
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  annotations:
    storageclass.beta.kubernetes.io/is-default-class=true
  name: do
provisioner: kubernetes.io/digitalocean-volume
```
**Edit 1:**
Since tests were not passing, I added staging and generated files.
This comparison should be handy to review code:
https://github.com/kubernetes/kubernetes/compare/master...01ff9261c2495830b84be261a36a92d1a088ccee

**Release note**:

```
Digital Ocean Volumes for Kubernetes.
```

### CODE REVIEW

**Comment by andrewsykim** [comment]
related: https://github.com/kubernetes/features/issues/88#issuecomment-313985056. 

I think volume related controller changes are still accepted into core until CSI is a thing, correct me if I'm wrong @luxas.

**Comment by baldwinSPC** [comment]
tagging @joonas so he's able to follow along

**Comment by odacremolbap** [comment]
@andrewsykim @luxas @saad-ali 
that's what I understood. We will be willing to move to CSI when it's ready.

On a different page, I will need some guidance on how to contribute the API changes, since `/pkg/api/v1/types.go` is no longer here.

https://github.com/StackPointCloud/api/tree/digitalocean-volumes

**Comment by andrewsykim** [comment]
@odacremolbap https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/api/core/v1 (you'll need to regenerate the files, see scripts under `hack/`)

**Comment by klausenbusk** [comment]
Does the code include logic to prevent attaching more than 5 volume to a droplet? Which is max per the [DO API doc](https://developers.digitalocean.com/documentation/v2/#attach-a-block-storage-volume-to-a-droplet): `However, up to five volumes may be attached to a Droplet at a time.`

**Comment by odacremolbap** [comment]
@klausenbusk thanks for pointing that out

No, we are not checking that limit. I will take a look at what other providers are doing, but I think I hit that a 4 disk attached limit using the Azure provider some time ago.

I'm not totally sure we should control that limit, but return the provisioning error. It's up to the scheduler to scatter pods, not the volume provider. I'll be on very limited connectivity until the end of this week, but will read about this and if this is an issue we'll fix it. Thanks a lot!

@andrewsykim yes, I'm modifying the staging folder at my local dev env to update API and vendors, but didn't know if I had to push that folder so I left that out. Thanks.

**Comment by klausenbusk** [comment]
I'm wondering if this is gonna get superseded by https://github.com/digitalocean/digitalocean-cloud-controller-manager

**Comment by andrewsykim** [comment]
@klausenbusk not anytime soon since adding volume plugins to external cloud controller managers has some work required before it's viable. It is recommended to use flex volumes for the time being.

**Comment by odacremolbap** [comment]
Closing in favor of
 - Digital Ocean Flex Plugin
 - Digital Ocean External Provisioner

**Pull request closed without merging**
