### PR TITLE
Drop go-colortext and its usage

### PR DESCRIPTION
**Pull request by dims**
We ONLY use it in one method, cleaning up!

#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ardaguclu** [comment]
I was thinking the same thing a few days ago and looks reasonable to me. Consequently will there be a dependency drop from go module?.

/triage accepted
/priority backlog

**Comment by ardaguclu** [comment]
/lgtm
/approve
/hold
In case @soltysh @seans3 have a look at

**Review by soltysh — APPROVED** [review]
/lgtm
/hold cancel

**Comment by soltysh** [comment]
Thank you :heart:

**Pull request merged**
