### PR TITLE
Refactor the client in job controller, daemon controller, and replication controller

### PR DESCRIPTION
**Pull request by caesarxuchao**
First two commits are #19737.

I'll assign it to myself until it passes all tests.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
e2e failure:
```
Kubernetes e2e suite.Kubectl client Kubectl describe should check if kubectl describe prints relevant information for rc and pods [Conformance]
```

**Comment by caesarxuchao** [comment]
@k8s-bot e2e test this please

**Comment by caesarxuchao** [comment]
Tests passed. Ready for review now. First two commits are #19737.

**Comment by lavalamp** [comment]
I left some comments in #19737

**Comment by caesarxuchao** [comment]
Merging this one with the refactoring of Deployment

**Pull request closed without merging**
