### PR TITLE
remove repetitive word in annotation

### PR DESCRIPTION
**Pull request by qingsenLi**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>

> /kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by resouer — APPROVED** [review]
Thanks! I'm interested in how did you find this typo? Is it possible to find other similar bugs throughout the repo?

**Comment by qingsenLi** [comment]
/cc @FengyunPan2  @vishh  @derekwaynecarr 
Needs approved, lgtm labels.thanks

**Review by resouer — APPROVED** [review]
/lgtm

Thanks for the fix!

**Comment by qingsenLi** [comment]
/cc @FengyunPan2 @vishh @derekwaynecarr
Needs approved labels.thanks

**Review by vishh — APPROVED** [review]
/lgtm
/approve

**Comment by qingsenLi** [comment]
/assign @deads2k  @FengyunPan2 
Needs approved labels.thanks

**Review by FengyunPan2 — APPROVED** [review]

**Comment by qingsenLi** [comment]
@FengyunPan2 
Needs approval from an approver in each of these files:
pkg/kubectl/OWNERS
pkg/kubelet/OWNERS [vishh]
pkg/volume/cinder/OWNERS

I think the PR need /approver lable by each of owners,could you add /approver lable,so it will work

**Comment by Pingan2017** [comment]
/cc @deads2k @soltysh 
 for approval.

**Comment by qingsenLi** [comment]
/assign @deads2k @soltysh 
for approval.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
