### PR TITLE
Automated cherry pick of #41851 and #41961 upstream release 1.5

### PR DESCRIPTION
**Pull request by janetkuo**
Automated cherry pick of #41851 and #41961 upstream release 1.5

### CODE REVIEW

**Comment by kargakis** [comment]
lgtm but don't you need to update bazel for the 1.5 branch?

**Comment by janetkuo** [comment]
Can't find hack/verify-bazel.sh or hack/update-bazel.sh in release-1.5 branch...

**Comment by janetkuo** [comment]
Looks like we don't need to update bazel in 1.5 branch, see #38310 @spxtr

**Comment by janetkuo** [comment]
Applying tag due to approval

**Comment by kargakis** [comment]
@janetkuo the do-not-merge label is still on

**Comment by kargakis** [comment]
> @janetkuo the do-not-merge label is still on

Not sure if someone else needs to remove it so I am not touching it

**Comment by janetkuo** [comment]
Oh yeah, need 1.5 release czar approval by adding cherrypick-approved tag @mwielgus

**Pull request merged**
