### PR TITLE
image Switched to Agnhost

### LINKED ISSUE #115781: Switch image in gRPC probe tests to agnhost
- Tests in `test/e2e/common/node/container_probe.go` are using `etcd` image for gRPC probe tests:
  - should not be restarted with a GRPC liveness probe
  - should be restarted with a GRPC liveness probe

We should use `agnhost` image for these tests as it is much smaller size.

/sig node
/kind cleanup
/priority important-soon
/area tests
/help-wanted
/good-first-issue

KEP: https://github.com/kubernetes/enhancements/issues/2727

### PR DESCRIPTION
**Pull request by Lauquik**
#### What type of PR is this?
/kind cleanup
-->

#### What this PR does / why we need it:
Tests in test/e2e/common/node/container_probe.go are using etcd image for gRPC probe tests
We should use agnhost image for these tests as it is much smaller size.
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/115781

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
please check the logs on the failing jobs before retesting, the job that you are modifying is the one is failing

> Kubernetes e2e suite: [It] [sig-node] Probing container should *not* be restarted with a GRPC liveness probe [NodeConformance] expand_more

**Comment by SergeyKanzhelev** [comment]
it is being worked on here: https://github.com/kubernetes/kubernetes/pull/115749

Thank you for your interest

/close

**Pull request closed without merging**
