### PR TITLE
populate priorityclassname in priority admission controller

### LINKED ISSUE #54911: populate priorityclassname in priority admission controller
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 

 /kind bug

**What happened**:

**What you expected to happen**:

As https://github.com/kubernetes/kubernetes/pull/54625 say, 

> I still think both of them are useful for a couple of reasons:
> The case that you described (a priority class is deleted and added with a different value) will not be resolved by not showing PriorityClassName. Imagine this scenario: user creates a pod with "high-priority" class name and the pod is resolved to 1000. Admin changes the value of "high-priority" class from 1000 to 2000. Now, user looks at his pod finds his pod to have 1000 value. He looks at the yaml/JSON/template that he created the pod from and sees that the priority class name was "high-priority". He finds this inconsistent and thinks that there was a bug in the system. If we show "PriorityClassName" in describe, at least the user will know that the priority class of the pod is the same as what he put in his config.
> It is useful in most cases to know what is the priority class name of the pod.

we print `priority` and `priorityclassname` when describe pod, but now the priority admission controller only populate priority for pod, so the priorityclassname may be empty and it is strange for user.so we should also populate priorityclassname in priority admission controller

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

populate priorityclassname in priority admission controller

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:Fixes #54911

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
@kubernetes/sig-scheduling-pr-reviews ping after review for approval.

**Comment by bsalamat** [comment]
@wackxu I am not sure about this PR. Why do we need it? It is totally fine for a pod to not have any PriorityClassName and we should not set it explicitly.

**Comment by bsalamat** [comment]
In fact setting PriorityClassName explicitly will interfere with our plans for doing quota management per priority class.

**Comment by wackxu** [comment]
@bsalamat What we set is the global default  `priorityclass` name to the pod that does not has `priorityclassname` in priority admission controller, I think it is necessary because we have agree that we should print priorityclassname when describe pod.

**Comment by resouer** [comment]
> I think it is necessary because we have agree that we should print priorityclassname when describe pod.

Why not leave it empty if there's no `PriorityClassName` ? 

I am also not very sure if behavior match to @bsalamat 's original design.

**Comment by bsalamat** [comment]
@wackxu We should leave it empty. Populating it invalidates some of the assumptions we have made in the design (most importantly the design of ResourceQuota per priority). It is ok to print nothing for PriorityClassName in describe pod.

**Comment by wackxu** [comment]
@bsalamat Thanks for you explication. It maybe cause something wrong if we populate priorityclassname. I will close this PR.

**Pull request closed without merging**
