### PR TITLE
make salt return non-zero exit code on failure

### PR DESCRIPTION
**Pull request by mikedanese**
Fixes https://github.com/kubernetes/kubernetes/issues/32478

### CODE REVIEW

**Comment by spxtr** [comment]
I don't know how salt works, but is the problem that it was running, failing, but not retrying because this argument wasn't set?

**Comment by mikedanese** [comment]
@spxtr yes

@k8s-bot verify test this

**Comment by spxtr** [comment]
That's a bother. Is this the only place in the codebase where we do such a thing?

/lgtm

**Comment by mikedanese** [comment]
@spxtr yes

**Pull request merged**
