### PR TITLE
Deprecate the term "Ubernetes" 

### PR DESCRIPTION
**Pull request by ghost**
Deprecate the term "Ubernetes" in favor of "Cluster Federation" and  "Multi-AZ Clusters"

### CODE REVIEW

**Comment by dims** [comment]
Big 👍

**Comment by matchstick** [comment]
@quinton-hoole @kubernetes/sig-cluster-federation Why did this fail a test by the merge bot? Do we still need this?

**Comment by davidopp** [comment]
@k8s-bot test this issue: #27023

**Comment by quinton-hoole** [comment]
Thanks @davidopp . @matchstick it was a test flake, unrelated to this PR.  Could you please give it an LGTM, whereafter the bot should auto-merge it for us.

**Comment by matchstick** [comment]
@quinton-hoole Sorry for the delay. I read the changes. Looks Good!

**Pull request merged**
