### PR TITLE
modify package name

### PR DESCRIPTION
**Pull request by yuexiao-wang**
Signed-off-by: yuexiao-wang <wang.yuexiao@zte.com.cn>

**What this PR does / why we need it**:
1. Modify package name in unittest and keep consistency between test and code.
2. Change some test messages.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by yuexiao-wang** [comment]
@adohe PTAL

**Review by dims — APPROVED** [review]
LGTM

**Comment by yuexiao-wang** [comment]
@adohe any suggestion?

**Comment by yuexiao-wang** [comment]
@adohe PTAL

**Pull request closed without merging**
