### PR TITLE
Adding windows clusterIP service test and statefulset test

### PR DESCRIPTION
**Pull request by iXinqi**
#### What this PR does / why we need it:
Adding clusterIP service test and statefulset test to e2e/windows to increase the test coverage of windows operational readiness test.

- clusterIP service test case is testing the following items in [KEP-2578](https://github.com/knabben/enhancements/blob/3ee6784895d650caa99e3ad23a361465478effb5/keps/sig-windows/2578-windows-conformance/README.md#basic-networking):

`Ability to access Linux container IPs by service IP from Windows containers`
`Ability to access Windows container IPs by service IP from Linux containers`

- statefulset test case is testing the following items in [KEP-2578](https://github.com/knabben/enhancements/blob/3ee6784895d650caa99e3ad23a361465478effb5/keps/sig-windows/2578-windows-conformance/README.md#basic-networking):
`Ability to delete and recreate pods for StatefulSets which preserve their ability to serve as routed endpoints for services, while also having unchanging IP addresses.`

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
https://github.com/kubernetes/enhancements/tree/master/keps/sig-windows/2578-windows-conformance
```

### CODE REVIEW

**Comment by iXinqi** [comment]
> Is there a statefuleset test that already exists that does this? We run a few of these: https://testgrid.k8s.io/sig-windows-signal#capz-windows-containerd-master&include-filter-by-regex=StatefulSetBasic
> 
> in particular `Kubernetes e2e suite.[sig-apps] StatefulSet Basic StatefulSet functionality [StatefulSetBasic] should validate Statefulset Status endpoints [Conformance]` seems like it might do something similar?

Yes, it's very similar. The major difference is that my test has windows node selector on the pod to guarantee the pod will be scheduled on the windows node. Is it worthy adding a new test case? If it's okay to re-use the linux statefulset test for windows, I can delete this test case from the PR.

**Comment by jsturtevant** [comment]
> The major difference is that my test has windows node selector on the pod to guarantee the pod will be scheduled on the windows node. Is it worthy adding a new test case? If it's okay to re-use the linux statefulset test for windows, I can delete this test case from the PR.

We do this for the majority of the tests (as you can see at https://testgrid.k8s.io/sig-windows-signal#capz-windows-containerd-master) by using a taint on the control plane nodes. This way if there is a change to the test we don't have to track them or maintain it.  @claudiubelu @marosset to chime in just in case I am missing something here

**Comment by iXinqi** [comment]
> > The major difference is that my test has windows node selector on the pod to guarantee the pod will be scheduled on the windows node. Is it worthy adding a new test case? If it's okay to re-use the linux statefulset test for windows, I can delete this test case from the PR.
> 
> We do this for the majority of the tests (as you can see at https://testgrid.k8s.io/sig-windows-signal#capz-windows-containerd-master) by using a taint on the control plane nodes. This way if there is a change to the test we don't have to track them or maintain it. @claudiubelu @marosset to chime in just in case I am missing something here

Thanks @jsturtevant. It makes sense to me to use the control plane node taint to prevent scheduling pods on Linux nodes. I'll close this pr and add the creating a destroying services to the test/e2e/network/service.go since it's not a windows-only test.

**Pull request closed without merging**
