### PR TITLE
test images: Update CudaVectorAdd test image to support arm64

### PR DESCRIPTION
**Pull request by brianwang12**
tested on arm64/amd64

Signed-off-by: briwan01 <Brian.Wang@arm.com>

What type of PR is this?
/sig-testing

What this PR does / why we need it:
This PR update CudaVectorAdd test image to support arm64

Build:
 $make all WHAT=cuda-vector-add
There is a detailed log in the build process of cuda-vector-add. [cuda_vector_add_build_image.txt](https://github.com/kubernetes/kubernetes/files/10380328/cuda_vector_add_build_image.txt)

The results are as followed:
registry.k8s.io/e2e-test-images/cuda-vector-add   2.2-linux-ppc64le                                9dd5d7c994ba   16 minutes ago   5.18GB
registry.k8s.io/e2e-test-images/cuda-vector-add   2.2-linux-arm64                                  172ebac45e7c   22 minutes ago   4.98GB
registry.k8s.io/e2e-test-images/cuda-vector-add   2.2-linux-amd64                                  4c3ff3bcf0d7   26 minutes ago   5.02GB

### CODE REVIEW

**Comment by chendave** [comment]
/release-note-none

if you need to add release note, pls edit it by yourself.

**Comment by brianwang12** [comment]
> @brianwang12 please update [VERSION](https://github.com/kubernetes/kubernetes/blob/master/test/images/cuda-vector-add/VERSION) file.

Thanks for your reply, I updated the version from 2.2 to 2.3

**Review by mkumatag — APPROVED** [review]
/lgtm

**Pull request merged**
