### PR TITLE
Skip NVidia GPU test in node e2e CI jobs for containerd and other runtimes

### PR DESCRIPTION
**Pull request by dims**
Since this is consistently failing in one of the cos-stable images (and probably needs a bit more tweaking of the ci infrastructure), let's skip for now:
https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial-containerd

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### What type of PR is this?
/kind cleanup
/kind failing-test

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/hold cancel

(now that we have lgtm from Sergey)

**Comment by SergeyKanzhelev** [comment]
/cc @ruiwen-zhao 

this is the test I mentioned yesterday, FYI

**Pull request merged**
