### PR TITLE
Fix leaking process in hostport proxy

### LINKED ISSUE #10494: Boilerplate check for sh should allow non-bash shells
I have a shell script that runs in a container that has 'sh' but not 'bash'.  I have to work around this for now.

### PR DESCRIPTION
**Pull request by thockin**
...also allow non-bash shell scripts.

Fixes #10494 and #10496 

I verified the boilerplate against invalid files and it still flags them but now allows #!/bin/sh to pass.

low risk.

### CODE REVIEW

**Comment by thockin** [comment]
Can I get a review on this?

**Comment by thockin** [comment]
@ArtfulCoder for review

**Comment by thockin** [comment]
ping @ArtfulCoder

**Comment by ArtfulCoder** [comment]
I somehow missed this. reviewing now. sorry for the delay.

**Pull request merged**
