### PR TITLE
delete all duplicate empty blanks

### PR DESCRIPTION
**Pull request by daixiang0**
Delete all duplicate empty blanks for master branch. Not only docs, also codes.

Signed-off-by: Xiang Dai <764524258@qq.com>

```release-note
NONE
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
changing a license file in particular seems like a bad idea.
I'm not sure we should do this. I'd lean towards leaving these as is.

**Comment by daixiang0** [comment]
> changing a license file in particular seems like a bad idea.
> I'm not sure we should do this. I'd lean towards leaving these as is.

get it, i keep them as they were.

**Review by neolit123 — COMMENTED** [review]
SGTM for cmd/kubeadm
/approve

**Comment by liggitt** [comment]
there are several test file changes as well that this change breaks. I'm not sure this worth the effort to separate out the changes that don't affect licenses or tests

**Comment by daixiang0** [comment]
> there are several test file changes as well that this change breaks. I'm not sure this worth the effort to separate out the changes that don't affect licenses or tests

I will check out test files first.

**Comment by daixiang0** [comment]
> @daixiang0: The following tests **failed**, say `/retest` to rerun them all:
> 
> Test name	Commit	Details	Rerun command
> pull-kubernetes-bazel-test	[fd28633](https://github.com/kubernetes/kubernetes/commit/fd2863301f0e0df00f178da57ad3b6db875a5d9c)	[link](https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/74328/pull-kubernetes-bazel-test/76847/)	`/test pull-kubernetes-bazel-test`
> pull-kubernetes-integration	[fd28633](https://github.com/kubernetes/kubernetes/commit/fd2863301f0e0df00f178da57ad3b6db875a5d9c)	[link](https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/74328/pull-kubernetes-integration/45833/)	`/test pull-kubernetes-integration`
> [Full PR test history](https://gubernator.k8s.io/pr/74328). [Your PR dashboard](https://gubernator.k8s.io/pr/daixiang0). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

/retest

**Comment by daixiang0** [comment]
@liggitt hi, any input?

**Comment by liggitt** [comment]
no api review required, this just touched files under k8s.io/api so the bot thought it might be necessary

**Pull request merged**
