### PR TITLE
Automated cherry pick of #69227: CHANGELOG-1.12: fix outdated information

### PR DESCRIPTION
**Pull request by neolit123**
Cherry pick of #69227 on release-1.12.

#69227: CHANGELOG-1.12: fix outdated information

### CODE REVIEW

**Review by dims — APPROVED** [review]

**Comment by neolit123** [comment]
is this going to miss `.1`?

**Comment by feiskyer** [comment]
> is this going to miss .1?

This is a changelog update for v1.12.0, so I think it's ok not included.

@tpepper @dougm could you help to approve this changelog update?

**Review by dougm — COMMENTED** [review]
/lgtm

Don't think I can help with /approve though, we need one of the top-level OWNERS to do so

**Comment by feiskyer** [comment]
@tpepper @bgrant0607 Could you help to approve this change?

**Comment by feiskyer** [comment]
Kindly ping @tpepper @bgrant0607. Could you help to approve this change?

**Comment by feiskyer** [comment]
Kindly ping @tpepper @bgrant0607. Could you help to approve this change?

**Comment by feiskyer** [comment]
Applied approval labels since this is only a release note update.

**Pull request merged**
