### PR TITLE
fix resource typo

### PR DESCRIPTION
**Pull request by timchenxiaoyu**
fix resource typo

### CODE REVIEW

**Comment by timchenxiaoyu** [comment]
cc @derekwaynecarr

**Comment by DirectXMan12** [comment]
I'm not entirely sure this is worth fixing all by itself in a PR.  we can fix the comment typo next time we actually update that code.

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by sttts** [comment]
/lgtm

/release-note-none

LGTM + release-note-none from the bulk LGTM tool

**Comment by timchenxiaoyu** [comment]
cc @derekwaynecarr ,please check,give approve

**Comment by spiffxp** [comment]
@k8s-bot ok to test

**Pull request merged**
