### PR TITLE
Disable the public cadvisor port by default

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:
Quoting @tallclair in #56523:
> We should add the deprecation warning in 1.10 along with a release note, but not change the default. The notes should warn that the default will change in 1.11. We disable the flag by default in 1.11, and remove it entirely in 1.12 or 1.13.
> If you currently depend on the UI or the API, speak up! Going forward, the recommended way of taking advantage of those features will be to run cAdvisor as a DaemonSet.

Disabling the publicly-available cAdvisor port is beneficial for security, as you might not want to expose the UI with lots of information about what your system is doing. We already did this for all kubeadm deployments in v1.7, and haven't recieved any issues for that. This should be okay to do at this stage, as this flag was deprecated in v1.10. Given we need to support this flag for one more release (v1.11), it makes perfect sense to instead switch it off in preparation for v1.12 when we can delete it (see the [deprecation policy](https://kubernetes.io/docs/reference/deprecation-policy/#deprecating-a-flag-or-cli))

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #56523

**Special notes for your reviewer**:

I removed the e2e test that expects cAdvisor to be running, as we don't expect it to be anymore.

**Release note**:

```release-note
[action required] The formerly publicly-available cAdvisor web UI that the kubelet ran on port 4194 by default is now turned off by default. The flag configuring what port to run this UI on `--cadvisor-port` was deprecated in v1.10. Now the default is `--cadvisor-port=0`, in other words, to not run the web server. The recommended way to run cAdvisor if you still need it, is via a DaemonSet. The `--cadvisor-port` will be removed in v1.12
```
cc @kubernetes/sig-cluster-lifecycle-pr-reviews @kubernetes/sig-auth-pr-reviews @kubernetes/sig-node-pr-reviews

### CODE REVIEW

**Comment by dashpole** [comment]
Will it have been depreciated for 6 months as of the 1.11 release?  I don't think it has been 6 months since the 1.10 release at this point...
```
Rule #5b: CLI elements of admin-facing components (e.g. kubelet) must function after their announced deprecation for no less than:

  * GA: 6 months or 1 release (whichever is longer)
```

**Comment by dashpole** [comment]
Reading it more closely, I guess it doesn't prevent us from changing defaults.  @mtaufen WDYT?

**Review by timothysc — COMMENTED** [review]
/lgtm

**Comment by dims** [comment]
/lgtm

/assign @dchen1107
/assign @derekwaynecarr 

Dawn, Derek, Can you PTAL?

**Comment by derekwaynecarr** [comment]
i am fine with this change.

we are still able to collect cAdvisor prom metrics via `/metrics/cadvisor` endpoint and those metrics are decorated correctly for the pod cgroup, so major concerns from me.

/approve
/lgtm

**Comment by luxas** [comment]
@tallclair ?? This made it into v1.11 for sure.

**Comment by tallclair** [comment]
Huh, sorry. I don't know what I was looking at before. Maybe I got my tabs crossed.

**Comment by luxas** [comment]
No problem

**Comment by jimangel** [comment]
@luxas do you have a PR against the 1.12 docs branch open for this? I have a feeling this will create a snowball of doc PRs, but maybe you could help find a spot for a general announcement? Thanks!

**Pull request merged**
