### PR TITLE
Promote apiserver.config.k8s.io to v1

### PR DESCRIPTION
**Pull request by php-coder**
**What this PR does / why we need it**:
This PR is introducing `apiserver.config.k8s.io/v1`. This version should be used instead of `v1alpha1` that is deprecated from now.

**Which issue(s) this PR fixes**:
Related to https://github.com/kubernetes/kubernetes/pull/63032#issuecomment-383705778

**Release note**:
```release-note
The `apiserver.config.k8s.io/v1alpha1` API has been promoted to `apiserver.config.k8s.io/v1` with no changes.
```

### CODE REVIEW

**Comment by php-coder** [comment]
PTAL @liggitt @deads2k 
CC @simo5

**Comment by deads2k** [comment]
/hold

This surprises me.  What and why?

**Comment by php-coder** [comment]
@deads2k We're looking for a place for EncryptionConfiguration. `apiserver.config.k8s.io` is good fit for that but our current EncryptionConfig is v1 already, so before moving it to this group, we need to promote the group to v1. See: https://github.com/kubernetes/kubernetes/pull/63032#issuecomment-383705778

**Comment by php-coder** [comment]
> We're looking for a place for EncryptionConfiguration. apiserver.config.k8s.io is a good fit for that ...

@deads2k Do you have a better option, perhaps? :)

**Comment by deads2k** [comment]
> @deads2k Do you have a better option, perhaps? :)

Seems like you could promote only that type.

**Comment by php-coder** [comment]
As per David's answer, we don't need to promote the whole group to v1 but we can introduce v1 version with only one required type.

/close

**Pull request closed without merging**
