### PR TITLE
Allow all special characters in the environment variable name except "="

### LINKED ISSUE #47: Rejecting valid Environment Variable Names
**Kubernetes version:**

```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23 15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18 21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Azure Container Service
- **OS**: Windows 10
- **Install tools**: 
- **Others**:

**What happened**:
I was invoking the following command:
`kubectl run myname --image=myimage:86 --port=80 --env="ConnectionStrings:DefaultConnection=Data Source=tcp:mySqlServer,1433;Initial Catalog=myDB;User Id=myUser;Password=mypassword;"`
I got errors about invalid env:
error: invalid env: ConnectionStrings:DefaultConnection=Data Source=tcp:mySqlServer

I tried this with a YAML file as well and got a better error message stating I was using invalid characters for my name. However, : is valid the only values not allowed in names is "=".  To work around this I removed the : then I got an error because it split my value on "," between my server and port.

**What you expected to happen**:
I expected a new environment variable to be created with the following information:
- name: ConnectionStrings:DefaultConnection
- value: Data Source=tcp:mySqlServer,1433;Initial Catalog=myDB;User Id=myUser;Password=mypassword;

**How to reproduce it** (as minimally and precisely as possible):
Just try and set the environment variable name to something that includes a ":" and have a value that contains a ",".  The splitting should not split on "," in the value of the environment variable. 

**Anything else we need to know**:
I am using .NET Core and it allows you to create nested configurations that are built using a : in the environment variable name.  I was able to use this just fine with docker run commands against my own host because docker and Linux does support the string as I originally submitted it. This only breaks because of the validation of values and parsing logic of kubectl.

### PR DESCRIPTION
**Pull request by hpandeycodeit**
**What type of PR is this?**

>
/kind api-change

**What this PR does / why we need it**:
This PR relaxes the restrictions on the use of special characters in the Environment variable names. It allows all the characters except `=` 

**Which issue(s) this PR fixes**:

Fixes [Issue 47](https://github.com/kubernetes/kubectl/issues/47)

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Relaxing the restrictions on the use of special characters in the Environment variable names. It allows all the characters except `=` . A valid variable name should not start with a digit. Older version of Kubelet ignores the environment variable names having other than [-._a-zA-Z0-9] characters and using these variables names will prevent api-server rollback to older versions.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by hpandeycodeit** [comment]
sig/api-machinery

**Comment by hpandeycodeit** [comment]
Ref: #69415

**Comment by liggitt** [comment]
thanks for the PR. let's coordinate on desired approach in https://github.com/kubernetes/kubernetes/issues/53201#issuecomment-534647130 before proceeding

**Comment by jeanfrancoislarente** [comment]
@alex-slynko , @hpandeycodeit - any chance this is in the cards for the near future?

**Pull request closed without merging**
