### PR TITLE
Always resync after resyncInterval

### LINKED ISSUE #14076: flaky e2e: Probing container with readiness probe should not be ready before initial delay and never restart
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-e2e-gce/8799/testReport/junit/(root)/Kubernetes%20e2e%20suite/Probing_container_with_readiness_probe_should_not_be_ready_before_initial_delay_and_never_restart/

### PR DESCRIPTION
**Pull request by timstclair**
The current resync implementation can have an arbitrarily long delay between pod status updates, if API server initiated sync events continually reset the resync timer. Switching to a `time.Ticker` to time the pod resyncs ensures that the resync period stays close to its target.

Fixes https://github.com/kubernetes/kubernetes/issues/14076

cc/ @dchen1107

### CODE REVIEW

**Comment by ncdc** [comment]
@kubernetes/rh-cluster-infra

**Comment by ncdc** [comment]
@kubernetes/rh-scalability

**Comment by yujuhong** [comment]
This fix was included in my PR #13571, which has been sitting there for a long time, unfortunately.

lgtm.

**Comment by yujuhong** [comment]
@timstclair, could you also cherry pick this to release-1.1

/cc @dchen1107

**Comment by dchen1107** [comment]
LGTM

**Pull request merged**
