### PR TITLE
Add the seccomp profile loading test to dockershim

### PR DESCRIPTION
**Pull request by yujuhong**
The test was originally in docker_manager_test.go (now removed). I
copied and adapated the logic for the new test. Also move the origina
test fixtures needed for the test.

ref: the original test is at https://github.com/kubernetes/kubernetes/blob/v1.6.2/pkg/kubelet/dockertools/docker_manager_linux_test.go#L294

This is part of #43234

### CODE REVIEW

**Comment by yujuhong** [comment]
@k8s-bot kubemark e2e test this

**Comment by yujuhong** [comment]
@k8s-bot kubemark e2e test this

**Comment by feiskyer** [comment]
LGTM

**Pull request merged**
