### PR TITLE
Stop Cache in scheduler when tests tear down

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: Kante Yin <kerthcet@gmail.com>

#### What type of PR is this?
/kind cleanup
/sig scheduling

#### What this PR does / why we need it:

Stop the Cache when tests tear down. 
```
func (cache *cacheImpl) run() {
	go wait.Until(cache.cleanupExpiredAssumedPods, cache.period, cache.stop)
}
```

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by sanposhiho — APPROVED** [review]
/lgtm

**Comment by sanposhiho** [comment]
/retest
https://github.com/kubernetes/kubernetes/issues/114438

**Comment by kerthcet** [comment]
cc @alculquicondor for approval

**Review by alculquicondor — COMMENTED** [review]
Awesome!

/approve

**Comment by alculquicondor** [comment]
It looks like an unrelated flaky test. Please open an issue for it.

**Comment by kerthcet** [comment]
> 

Yes, it's a flake one. https://github.com/kubernetes/kubernetes/issues/114852

**Pull request merged**
