### PR TITLE
fix for openstack member cleanup for multiple port cases

### LINKED ISSUE #60976: Openstack loadbalancer deletion issue with multiple ports exposed
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I have exposed a service on multiple ports (80,443).
**What you expected to happen**:
After deletion kube-controller could not clean up the loadbalancer from openstack.
**How to reproduce it (as minimally and precisely as possible)**:
Create a service with multiple port exposed and try to delete it on a k8s cluster with openstack provider.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3
- Cloud provider or hardware configuration: Openstack
- OS (e.g. from /etc/os-release): Ubuntu Xenial
- Kernel (e.g. `uname -a`): Linux 4.4.0-116-generic ubuntu
- Install tools: kubeadm
- Others:

### PR DESCRIPTION
**Pull request by n-marton**
**What this PR does / why we need it**:
Fixing an openstack lb issue.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes: #60976

**Special notes for your reviewer**:
The problem with the code was that if multiple ports were exposed then that created multiple members for each listener, and the deletion process iterated over each listener with an array of every member resulting listener - member mismatch, which caused not found exception from lbaasv2.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by FengyunPan2** [comment]
@n-marton If isNotFound() can check the 'not found exception', lbaasv2 cloud work fine.
So I think the isNotFound() can't work on openstack cloud provider.
OTOH, I like your PR, your PR has a better way to delete all the members.

**Comment by FengyunPan2** [comment]
BTW, we should fix the isNotFound() later.
When user delete one member of pool on openstack, kubernetes can't found that member, which caused not found exception too.

**Comment by n-marton** [comment]
Could this be picked back for some 1.9.x release?

**Review by FengyunPan2 — APPROVED** [review]
/lgtm

**Comment by FengyunPan2** [comment]
/approve cancel
Any thought? @anguslees @dims

**Comment by n-marton** [comment]
Or could this be merged before 1.10.0 release?

**Comment by dims** [comment]
@n-marton at this point in the schedule ... we will have to cherry pick into 1.9.x and 1.10.x branch after v1.10 ships. the release time is quick to issue patch releases, so should take a couple of weeks to get a 1.10.1 i think

**Comment by n-marton** [comment]
cool

**Pull request merged**
