### PR TITLE
Fix typo in guestbook-go

### PR DESCRIPTION
**Pull request by rafax**
Fixes a typo in guestbook-go example.

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot ok to test

**Comment by rafax** [comment]
Console blocks in the same tutorial are not formatted properly - can I fix them in this PR (same file as the commit above) or should I open a separate one?

**Comment by wojtek-t** [comment]
Please open another one.

**Comment by wojtek-t** [comment]
Jenkins test failure is a flake:
Kubernetes e2e suite.Services should serve multiport endpoints from pods

Rerunning.

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
LGTM

**Pull request merged**
