### PR TITLE
kubectl: fix 'create deployment' to set container name correctly

### PR DESCRIPTION
**Pull request by 0xmichalis**
@kubernetes/kubectl @kubernetes/sig-cli

### CODE REVIEW

**Comment by mfojtik** [comment]
nice, LGTM

**Comment by kargakis** [comment]
Fixed a unit test, reapplying lgtm

**Comment by kargakis** [comment]
> Fixed a unit test, reapplying lgtm

And a template fix for my test-cmd stanza.

**Comment by kargakis** [comment]
@k8s-bot node e2e test this

**Pull request merged**
