### PR TITLE
Apply go-junit-report/pull/83 so we can capture better log output

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I1e4c1b83533c1e534b01bdaab3583fdd3ca9e15c

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Patch up what we use until https://github.com/jstemmer/go-junit-report/pull/83 merges

Added some defensive steps so we don't keel over when the PR merges.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
Merged upstream, I think we can drop this. Do we have any vendored or pinned versions we need to update?

**Comment by dims** [comment]
@liggitt nope. we should be good

**Pull request closed without merging**
