### PR TITLE
Do not create selector and namespaces in a loop where possible

### PR DESCRIPTION
**Pull request by dshulyak**
cherry-pick from #37691

Not automated cause i had to change versions of api objects

### CODE REVIEW

**Comment by dshulyak** [comment]
@wojtek-t Hi, please take a look at this cherry-pick when you will have time. It would be awesome to land it before 1.5.2 is released.

**Comment by wojtek-t** [comment]
/lgtm

@saad-ali needs to also approve cherrypick

**Comment by saad-ali** [comment]
Ok to merge to 1.5 once LGTM'd by assignee or reviewer.

**Comment by wojtek-t** [comment]
LGTM - thanks @saad-ali !

**Pull request merged**
