### PR TITLE
Allow zero value for the 'nominalConcurrencyShares' field

### LINKED ISSUE #121510: APF: in 1.30, allow zero values for the 'nominalConcurrencyShares' field
### What happened?

In 1.30, Priority and Fairness should allow a zero value, either via v1 or v1beta3 (with the roundtrip annotation) in create and update requests

See: https://github.com/kubernetes/kubernetes/pull/121089

### PR DESCRIPTION
**Pull request by tkashem**
#### What type of PR is this?

/kind feature

#### Which issue(s) this PR fixes:
Fixes #121510

#### Does this PR introduce a user-facing change?
```release-note
allow a zero value for the 'nominalConcurrencyShares' field of the PriorityLevelConfiguration object 
either using the flowcontrol.apiserver.k8s.io/v1 or flowcontrol.apiserver.k8s.io/v1beta3 API
```
#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by wojtek-t** [comment]
I will take a look in the next few days

**Review by MikeSpreitzer — APPROVED** [review]
/lgtm
Thanks!

**Pull request merged**
