### PR TITLE
Used ObjectReference for events.

### LINKED ISSUE #42701: kubelet failed to record some events.
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Kubernetes version** (use `kubectl version`):
master

**What happened**:
```
E0306 07:26:10.013767    3385 event.go:259] Could not construct reference to: '&v1.Node{...}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'NodeAllocatableEnforced' '       Updated Node Allocatable limit across pods'
```

### PR DESCRIPTION
**Pull request by k82cn**
fixes #42701 

```release-note
None
```

### CODE REVIEW

**Comment by k82cn** [comment]
@k8s-bot cvm gce e2e test this

**Comment by k82cn** [comment]
@k8s-bot cvm gce e2e test this

**Comment by k82cn** [comment]
@k8s-bot kubemark e2e test this
@k8s-bot gce etcd3 e2e test this
@k8s-bot non-cri e2e test this
@k8s-bot gci gce e2e test this
@k8s-bot kops aws e2e test this
@k8s-bot cvm gce e2e test this

**Comment by k82cn** [comment]
`./hack/local-cluster-up.sh` works with several nginx pods, but e2e keep failed; working on it.

**Comment by k82cn** [comment]
@k8s-bot cvm gce e2e test this

**Comment by sjpotter** [comment]
I'd see if I can bring up a gce cluster.  and look at the kubelet logs in that case if it fails (as that's what hte e2e tests are trying to do and failing at).

**Comment by k82cn** [comment]
@sjpotter , thanks very much; do you think we should print kubelet parameters for debugability?

**Comment by vishh** [comment]
This PR looks good to me. Can you get the tests to pass?

**Comment by k82cn** [comment]
@k8s-bot cvm gce e2e test this

**Comment by sjpotter** [comment]
look at the kubelet logs, on master

```
I0313 05:01:29.490538    1387 server.go:127] Starting to listen on 0.0.0.0:10250
I0313 05:01:29.492732    1387 server.go:144] Starting to listen read-only on 0.0.0.0:10255
I0313 05:01:29.493986    1387 server.go:345] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"k6k-e2e-agent-pr-38-0-master", UID:"k6k-e2e-agent-pr-38-0-master", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'Starting' Starting kubelet.
I0313 05:01:29.494277    1387 server.go:345] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"k6k-e2e-agent-pr-38-0-master", UID:"k6k-e2e-agent-pr-38-0-master", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'ImageGCFailed' unable to find data for container /
E0313 05:01:29.494600    1387 event.go:208] Unable to write event: 'Post https://146.148.39.205/api/v1/namespaces/default/events: dial tcp 146.148.39.205:443: getsockopt: connection refused' (may retry after sleeping)
```

and it rise and repeats

```
I0313 05:01:29.618452    1387 kubelet_node_status.go:379] Recording NodeHasSufficientDisk event message for node k6k-e2e-agent-pr-38-0-master
I0313 05:01:29.618658    1387 kubelet_node_status.go:379] Recording NodeHasSufficientMemory event message for node k6k-e2e-agent-pr-38-0-master
I0313 05:01:29.618882    1387 kubelet_node_status.go:379] Recording NodeHasNoDiskPressure event message for node k6k-e2e-agent-pr-38-0-master
I0313 05:01:29.619171    1387 kubelet_node_status.go:379] Recording NodeNotSchedulable event message for node k6k-e2e-agent-pr-38-0-master
I0313 05:01:29.619496    1387 kubelet_node_status.go:77] Attempting to register node k6k-e2e-agent-pr-38-0-master
I0313 05:01:29.620383    1387 server.go:345] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"k6k-e2e-agent-pr-38-0-master", UID:"k6k-e2e-agent-pr-38-0-master", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeHasSufficientDisk' Node k6k-e2e-agent-pr-38-0-master status is now: NodeHasSufficientDisk
I0313 05:01:29.620639    1387 server.go:345] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"k6k-e2e-agent-pr-38-0-master", UID:"k6k-e2e-agent-pr-38-0-master", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeHasSufficientMemory' Node k6k-e2e-agent-pr-38-0-master status is now: NodeHasSufficientMemory
I0313 05:01:29.620844    1387 server.go:345] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"k6k-e2e-agent-pr-38-0-master", UID:"k6k-e2e-agent-pr-38-0-master", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeHasNoDiskPressure' Node k6k-e2e-agent-pr-38-0-master status is now: NodeHasNoDiskPressure
I0313 05:01:29.621059    1387 server.go:345] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"k6k-e2e-agent-pr-38-0-master", UID:"k6k-e2e-agent-pr-38-0-master", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeNotSchedulable' Node k6k-e2e-agent-pr-38-0-master status is now: NodeNotSchedulable
E0313 05:01:29.622678    1387 kubelet_node_status.go:101] Unable to register node "k6k-e2e-agent-pr-38-0-master" with API server: Post https://146.148.39.205/api/v1/nodes: dial tcp 146.148.39.205:443: getsockopt: connection refused
```

the above is probably just a symptom, guess that apiserver isn't coming up?

**Comment by k82cn** [comment]
> the above is probably just a symptom, guess that apiserver isn't coming up?

Yes, I also found those logs. It seems apiserver is started by kubelet, the kubelet can not startup in time. Not sure which flag is missed :(, opened a PR for startup flags at #43061 .

**Comment by k82cn** [comment]
Just go through the code, if we try register Node to apiserver, the syncLoop will not start which will block static pods. No evidence now, but suppose apiserver was started by static pods or http.

**Comment by sjpotter** [comment]
yes, that's exact;y how the apiserver is started.  the "master" node starts the "master" services as static pods in the cluster/kube-up case.

**Comment by k82cn** [comment]
> yes, that's exact;y how the apiserver is started. the "master" node starts the "master" services as static pods in the cluster/kube-up case.

Let me find another way to fix this issue :).

**Comment by k82cn** [comment]
@k8s-bot cvm gce e2e test this

**Comment by k82cn** [comment]
@sjpotter / @vishh , updated PR to use `ObjectReference` if node is not registered. But I think we can use `ObjectReference` directly, same as other events did.

**Comment by k82cn** [comment]
ping @vishh :).

**Comment by k82cn** [comment]
@vishh , any comments?

**Comment by k82cn** [comment]
@sjpotter / @vishh , ping :).

**Comment by k82cn** [comment]
@k8s-bot bazel test this

**Comment by k82cn** [comment]
@k8s-bot bazel test this

**Pull request merged**
