### PR TITLE
Automated cherry pick of #68874: update vendor #66012: ipvs support graceful termination #69268: fix bugs introduced by ipvs graceful termination

### PR DESCRIPTION
**Pull request by Lion-Wei**
Cherry pick of #68874 #66012 #69268 on release-1.11.

#68874: update vendor
#66012: ipvs support graceful termination
#69268: fix bugs introduced by ipvs graceful termination

### CODE REVIEW

**Comment by Lion-Wei** [comment]
/assign @sttts @feiskyer @m1093782566 
Please take a look, this is same thing as https://github.com/kubernetes/kubernetes/pull/70006, cherry-pick to 1.11, since we claimed ipvs is GA in 1.11 release.

**Comment by nonspecialist** [comment]
So this missed 1.11.4 but got into 1.12.2 with #70006 , which is disappointing as they were submitted at the same time. Could we at least get a yay or nay for 1.11.5? @foxish appears to be on the hook for this.

**Comment by idealhack** [comment]
@nonspecialist This has to be approved by all OWNERS (`dep-approvers` left) before approved by a patch release manager.

/assign @cblecker @thockin

**Pull request merged**
