### PR TITLE
Remove gcp and azure auth plugins

### LINKED ISSUE #103498: Remove gcp and azure auth plugins in v1.25
This serves as a milestoned issue to track removal of gcp and azure auth plugin code per #102181

/assign
/milestone v1.25

### PR DESCRIPTION
**Pull request by enj**
Signed-off-by: Monis Khan <mok@vmware.com>

#### What type of PR is this?

/kind cleanup
/kind deprecation
/triage accepted
/priority important-soon
/milestone v1.25
/assign @liggitt @mikedanese @ritazh @aramase 

Fixes #103498

```release-note
The `gcp` and `azure` auth plugins have been removed from client-go and kubectl. See https://github.com/Azure/kubelogin and https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke for details about the cloud-specific replacements.
```

### CODE REVIEW

**Comment by liggitt** [comment]
/lgtm
/approve
for deps and gcp removal

cc @kubernetes/provider-azure for ack on azure plugin removal

**Comment by ritazh** [comment]
/lgtm
/approve
for azure removal

**Comment by marosset** [comment]
`pull-kubernetes-e2e-capz-windows-containerd` is currently broken and we're working to fix this.
Our CNI setup was using `discovery.k8s.io/v1beta1` which was removed with https://github.com/kubernetes/kubernetes/pull/108797

**Pull request merged**
