### PR TITLE
remove rescheduler since scheduling DS pods by default scheduler is moving to beta

### LINKED ISSUE #64725: Remove rescheduler once scheduling DS pods by default scheduler moves to beta.
/kind feature

Plan to remove rescheduler

For pods generated by DS controller, if we use default-scheduler for scheduling, since priority and preemption is going to beta in 1.11, we except the preemption to happen but as of now, the `scheduling DS pods by default scheduler` is still in alpha and we need to rely on rescheduler to make enough space for pods scheduled by DS controller. Once it moves to beta, we should remove rescheduler. 

xref: https://github.com/kubernetes/kubernetes/issues/57471

### PR DESCRIPTION
**Pull request by Lion-Wei**
**What this PR does / why we need it**:

remove rescheduler since scheduling DS pods by default scheduler is moving to beta

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #64725

**Special notes for your reviewer**:

**Release note**:
```release-note
Remove rescheduler since scheduling DS pods by default scheduler is moving to beta.
```

### CODE REVIEW

**Comment by Lion-Wei** [comment]
/cc @ravisantoshgudimetla @Huang-Wei 
PTAL, thanks.

**Review by ravisantoshgudimetla — APPROVED** [review]
Thanks for the PR @Lion-Wei 

/lgtm

**Comment by ravisantoshgudimetla** [comment]
/cc @bsalamat @eparis @yujuhong @derekwaynecarr @ixdy - Can you please approve this? - This ensures rescheduler is removed from master. We don't need it anymore as scheduler is going to schedule DS pods.

cc @Huang-Wei

**Comment by Lion-Wei** [comment]
@ravisantoshgudimetla Thanks.
/assign @bsalamat @eparis @yujuhong @derekwaynecarr 
 Can you please approve this? - This ensures rescheduler is removed from master. We don't need it anymore as scheduler is going to schedule DS pods.

**Comment by Huang-Wei** [comment]
@Lion-Wei thanks for the PR. The changes look good to me.

BTW: it still needs approval from one owner of cluster/OWNERS:
- eparis
- jbeda
- mikedanese
- roberthbailey
- zmerlynn

**Comment by derekwaynecarr** [comment]
kubelet change is fine.

/approve

**Comment by Lion-Wei** [comment]
Thanks all. : )

**Pull request merged**
