### PR TITLE
Fix garbled code in kubeadm output

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
This fixes the garbled code:
image

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by fabriziopandini — APPROVED** [review]
/lgtm
Thanks for this PR!

**Comment by xiangpengzhao** [comment]
Thanks @detiber @fabriziopandini !
/assign @timothysc
for approval :)

**Review by timothysc — APPROVED** [review]
/approve

**Pull request merged**
