### PR TITLE
Clean-up and additional test cases for socket-mask unit test.

### PR DESCRIPTION
**Pull request by nolancon**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR adds additional test cases and edits some test names in the BitMask abstraction for Topology Manager.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nolancon** [comment]
I will rebase once #78587 is merged.

**Comment by draveness** [comment]
Great work, thanks!

/ok-to-test
/priority backlog
/assign @dchen1107

**Review by mattjmcnaughton — COMMENTED** [review]
Thanks for the refinement here!

Looks like some of the unit tests are failing, but overall agree with the direction this is going.
Can you assign this to the user recommended by the k8s-ci-robot after the tests are passing? Thanks :)

**Comment by nolancon** [comment]
> Thanks for the refinement here!
> 
> Looks like some of the unit tests are failing, but overall agree with the direction this is going.
> Can you assign this to the user recommended by the k8s-ci-robot after the tests are passing? Thanks :)

Sure, unit tests will pass once #78587 is merged and this is PR rebased.

**Comment by nolancon** [comment]
@mattjmcnaughton  this PR has been rebased and is passing tests now that #78587 is merged.
/assign @dchen1107

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

thank you for the ping!

**Pull request merged**
