### PR TITLE
Sketch: Registry plugins

### PR DESCRIPTION
**Pull request by thockin**

### CODE REVIEW

**Comment by roberthbailey** [comment]
Assigning to @davidopp for triage.

**Comment by smarterclayton** [comment]
#4248 is going to make a lot of this go away as I refractor out REST (boilerplate, hard to write).

**Comment by erictune** [comment]
@thockin can this be closed now that Clayton is taking on a bunch of refactoring in this area?

**Comment by thockin** [comment]
sure, I still have my branch if I need it :)

**Pull request closed without merging**
