### PR TITLE
Delete all dead containers only after the syncing for the evicted pod is done.

### PR DESCRIPTION
**Pull request by ronnielai**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30487)

### CODE REVIEW

**Comment by Random-Liu** [comment]
*[pkg/kubelet/pod_container_deletor.go, line 61 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30487#-KPELC_GzENWu6eI8RlR:-KPELC_GzENWu6eI8RlS:bdr36tf) ([raw file](https://github.com/kubernetes/kubernetes/blob/11986fd69bbfae2c075d870e4a4dd14f97b69a7d/pkg/kubelet/pod_container_deletor.go#L61)):*
> ```Go
> }
> 
> // getContainersToDeleteInPod returns the exited containers in a pod whose name matches the name inferred from filterContainerId (if not empty), ordered by the creation time from the latest to the earliest.
> ```

IIUC, if it is empty, all containers will be removed. We should also describe this behaviour in the comment.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30487)*

**Comment by Random-Liu** [comment]
*[pkg/kubelet/pod_container_deletor.go, line 66 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30487#-KPELu87KhbLsjprFJW9:-KPELu87KhbLsjprFJWA:b-hdyqlj) ([raw file](https://github.com/kubernetes/kubernetes/blob/11986fd69bbfae2c075d870e4a4dd14f97b69a7d/pkg/kubelet/pod_container_deletor.go#L66)):*
> ```Go
> 	var exitedContainers []*kubecontainer.ContainerStatus
> 	// Find all exited containers in the pod
> 	for _, containerStatus := range podStatus.ContainerStatuses {
> ```

The logic is right, but seems a little indirect here. Why not use one loop and filter with `ContainerStateExited` and `filterContainerId`?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30487)*

**Comment by ronnielai** [comment]
Addressed comments. PTAL

**Comment by Random-Liu** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/30487#-:-KPFIGiVYS8GBa32iNXT:bnfp4nl)*

**Pull request merged**
