### PR TITLE
Automated cherry pick of #115620: client-go/cache: fix missing delete event on replace  (+ #116623)

### PR DESCRIPTION
**Pull request by odinuge**
Cherry pick of #115620 on release-1.25.

#115620: client-go/cache: fix missing delete event on replace

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fix missing delete events on informer re-lists to ensure all delete events are correctly emitted and using the latest known object state, so that all event handlers and stores always reflect the actual apiserver state as best as possible
```

### CODE REVIEW

**Comment by odinuge** [comment]
Adding a hold while we discuss https://github.com/kubernetes/kubernetes/issues/115658#issuecomment-1450614656.

/hold

**Comment by Verolop** [comment]
@lavalamp per @odinuge last comment on https://github.com/kubernetes/kubernetes/issues/115658#issuecomment-1463661460, I'm happy to add this as a cherry pick for the upcoming patches. Can you please remove the hold tag? thanks!

**Comment by lavalamp** [comment]
Please add https://github.com/kubernetes/kubernetes/pull/116623 to this cherry pick and then it should be good to go.

**Comment by odinuge** [comment]
/hold cancel

cc @kubernetes/release-managers for approval

**Comment by cici37** [comment]
Shouldn't the release note be added together as in original PR?

**Review by xmudrii — APPROVED** [review]
For RelEng:
/lgtm
/approve

**Pull request merged**
