### PR TITLE
Fix broken link to api-conventions doc.

### PR DESCRIPTION
**Pull request by kkkkun**
Signed-off-by: kkkkun <scuzk373x@gmail.com>

#### What type of PR is this?
/kind documentation
/release-note-none

#### What this PR does / why we need it:
Follow up on https://github.com/kubernetes/kubernetes/pull/81770
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
/release-note-none
/ok-to-test
/lgtm
Thanks for the fix!

**Comment by cici37** [comment]
/assign @lavalamp 
for approval. Thanks

**Comment by lavalamp** [comment]
is that .proto file really generated? if so, need to fix the source too.

**Comment by kkkkun** [comment]
> is that .proto file really generated? if so, need to fix the source too.

They are not generated. I do not found how to generated this.  But https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/apis/example2/v1/types.go#L31 has changed before, but .proto do not changed. It's strange.

**Comment by kkkkun** [comment]
It seems resovled in PR https://github.com/kubernetes/kubernetes/pull/116106.
/close

**Pull request closed without merging**
