### PR TITLE
remove unless healthz.DefaultHealthz() in controller-manager

### LINKED ISSUE #52405: controller-manager can remove the healthz.DefaultHealthz()
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

The health endpoint is already registered in https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L204. And we can safely remove it.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

remove unless healthz.DefaultHealthz() in controller-manager

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #52405

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
Do we not need healthz in controller manager?

**Comment by wojtek-t** [comment]
> Do we not need healthz in controller manager?

We need. I think it's registered twice :)

**Comment by luxas** [comment]
@wojtek-t Where in that case is it already registered?

**Comment by wackxu** [comment]
@luxas The health endpoint is already registered in https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L204.

**Pull request merged**
