### PR TITLE
delete one testcase from json_test.go for duplicated data

### PR DESCRIPTION
**Pull request by tianshapjq**
in json_test.go there are 2 duplicated tesecases. Here I'm going to delete one of them. Please review for this. thanks!

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36736)

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by deads2k** [comment]
lgtm

**Comment by tianshapjq** [comment]
I signed it!

**Comment by tianshapjq** [comment]
Sorry for fixing the conflicts so late, could you please check the modifications? 
@deads2k

**Comment by rmmh** [comment]
@k8s-bot verify test this

**Pull request merged**
