### PR TITLE
bugfix for pr#71114. if we use ipvs mode on node which linux version …

### LINKED ISSUE #82065: bug in pr#71114：if i use ipvs mode on node with linux 3.10，kube-proxy will not work
**What happened**:
when I use ipvs mode on node with linux 3.10，my kube-proxy can not work.

**What you expected to happen**:
when I use ipvs mode on node with linux 3.10，my kube-proxy can work.

**How to reproduce it (as minimally and precisely as possible)**:
prepare a node with linux 3.10（<4.1），install k8s，and start kube-proxy with ipvs mode(/kube-proxy --proxy-mode=ipvs)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.10.5 1.12.4
- Kernel (e.g. `uname -a`):
Linux VM_32_219_centos 3.10.107

**test**:
- use ipvs mode
```
/kube-proxy --kubeconfig=/etc/kubernetes/kubeproxy-kubeconfig --hostname-override=172.21.240.111 --v=2 --proxy-mode=ipvs --ipvs-min-sync-period=1s --ipvs-sync-period=5s --ipvs-scheduler=rr --masquerade-all=true
```
- service.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    run: my-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-nginx
```
- curl ${CLUSTER-IP}
    - compare with kube-proxy before and after bugfix

### PR DESCRIPTION
**Pull request by ivan-cai**
…<4.1, our kube-proxy also can work

**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:
bugfix for pr #71114. 71114,when i use ipvs mode on node which linux version <4.1， my kube-proxy can not work

**Which issue(s) this PR fixes**:

Fixes #82065

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by cmluciano — COMMENTED** [review]
I believe this check is by design so that we know settings are being propagated for correct kube-proxy usage. @danwinship @dcdw Any thoughts on this?

**Comment by danwinship** [comment]
I don't know about the ipvs proxier

**Comment by thockin** [comment]
@andrewsykim how much do we care about really old kernels?  I can't speak to the correctness of the IPVS proxier if this fails to set...

**Comment by danwinship** [comment]
> how much do we care about really old kernels?

4.1 is old, but not "really old". (eg, Debian 8/jessie/oldoldstable has an older kernel than that).

I guess the question is really "what distro versions does kubernetes support?" This came up with some of the iptables PRs too.

**Comment by cmluciano** [comment]
Do we have more comments on the expected kernel/distros that we support?

**Comment by andrewsykim** [comment]
>  I can't speak to the correctness of the IPVS proxier if this fails to set..

Many users (and from my own experience) have reported really bad IPVS performance if you don't disable `conn_reuse_mode`. I would strongly be in favor of requiring this sysctl config, however, I didn't realize that this was introduced on 4.1 which I agree with @danwinship is old but not super old to the point we shouldn't support it. 

re: supported kernel versions, my impression was that the minimum supported kernel version is 3.10, which is inline with docker's minimum kernel version though I don't see this written/documented anywhere officially.

**Comment by andrewsykim** [comment]
@lbernail any opinions here?

**Comment by lbernail** [comment]
@andrewsykim makes complete sense to me. Probably worth a comment in the code: the behavior in kernels <4.1 will be the exact same one we get for more recent kernels (before the sysctl existed, the behavior was the same as `conn_reuse_mode=0`).

Ideally we'd want not to try and set it for older kernels to be able to catch actual errors (the warning here could mean either: "kernel is too old" or "there was an error applying the sysctl" which are very different situations)

**Comment by lbernail** [comment]
The best would probably be to use the `GetKernelVersion` helper and only set the sysctl for kernels >= 4.1

**Comment by yyx** [comment]
Hello everyone：
      We are very fortunate to tell you that this bug has been fixed by us and has been verified to work very well.  The patch（[ipvs: avoid drop first packet to reuse conntrack](https://lkml.org/lkml/2020/6/11/272)） is being submitted to the Linux kernel community. You can also apply this patch to your own kernel, and then only need to set net.ipv4.vs.conn_reuse_mode=1. 
That Can solve the following problems:
1. Rolling update, IPVS keeps scheduling traffic to the destroyed Pod
2. Unbalanced IPVS traffic scheduling after scaled up or rolling update
3. fix IPVS low throughput issue #71114
https://github.com/kubernetes/kubernetes/pull/71114
4. One second connection delay in masque
https://marc.info/?t=151683118100004&r=1&w=2
5. IPVS low throughputÂ #70747
https://github.com/kubernetes/kubernetes/issues/70747  
6. Apache Bench can fill up ipvs service proxy in seconds #544
https://github.com/cloudnativelabs/kube-router/issues/544
7. Additional 1s latency in `host -> service IP -> pod` when upgrading from `1.15.3 -> 1.18.1` on RHEL 8.1 #90854
https://github.com/kubernetes/kubernetes/issues/90854

  Thank you.
  By Yang Yuxi （TencentCloudContainerTeam）

**Comment by andrewsykim** [comment]
Following-up on @yyx's comment above for posterity. 

The patch mentioned above didn't make it to the kernel but there are two recently merged patches worth highlighting. One of them fixes the 1 second delay issue and the other fixes dropped packets when stale connection entries in the IPVS table are used:
1) http://patchwork.ozlabs.org/project/netfilter-devel/patch/20200701151719.4751-1-ja@ssi.bg/ 
2) http://patchwork.ozlabs.org/project/netfilter-devel/patch/20200708161638.13584-1-kim.andrewsy@gmail.com/

**Comment by lbernail** [comment]
@andrewsykim this is great news
1: Does this mean we will be able remove `conn_reuse_mode=0` ?  This would be very good news
2: 🎉 Great job. Looking forward to kernels supporting this. Thanks!

**Comment by andrewsykim** [comment]
1. Yes, but I guess we'd have to do it based on the kernel version?
2. Thanks! Hoping this fixes the various issues we've seen with UDP packets dropping. Maybe we can remove some of the special cases for UDP in the graceful termination logic.

**Pull request closed without merging**
