### PR TITLE
components pprof profiling make use of existing genericapiserver's

### LINKED ISSUE #60278: kube-controller-manager scheduler and proxy should use common generic apiserver's profiling
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Currently kube-controller-manager scheduler and proxy have their own private pprofiling code. They should reuse the existing generic apiserver's profiling.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

fix #60278

Instead of writing private pprof, all components make use of generic apiserver existing profiling.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
This is another PR that turns apiserver functionally into something more generic. kube-proxy importing k8s.io/apiserver is kind of strange.

I am not against having a base library, but neither k8s.io/apimachinery, nor k8s.io/apiserver seem to be the right place for this functionality. Cannot come up with a good name though either. k8s.io/controlplane? k8s.io/server? k8s.io/genericserver?

/cc @deads2k

**Comment by deads2k** [comment]
> This is another PR that turns apiserver functionally into something more generic. kube-proxy importing k8s.io/apiserver is kind of strange.
> 
> I am not against having a base library, but neither k8s.io/apimachinery, nor k8s.io/apiserver seem to be the right place for this functionality. Cannot come up with a good name though either. k8s.io/controlplane? k8s.io/server? k8s.io/genericserver?
> 
> /cc @deads2k

I'd like to see how the controller-manager updates end up landing.  My suspicion is that the controller-managers really are just slightly simplified apiservers.

**Comment by hzxuzhonghu** [comment]
rebased

**Comment by deads2k** [comment]
needs a squash

/approve

if its just the cloud controller, I'm comfortable tagging for this

**Comment by thockin** [comment]
/approve no-issue

really should have a tracking issue

**Pull request merged**
