### PR TITLE
fix kubeadm token create

### PR DESCRIPTION
**Pull request by xilabao**
1. allow run `kubeadm ex token create --token=""` or `kubeadm ex token create` to create token
2. validate the token format at first

### CODE REVIEW

**Comment by xilabao** [comment]
@luxas

**Comment by xilabao** [comment]
@luxas Could you review this pr?

**Comment by luxas** [comment]
@xilabao I'm sorry on this one. I've had https://github.com/kubernetes/kubernetes/pull/41663 up for 10 days that fixes this and much more, and it's LGTM'd, just gonna rebase it and merge today.

Under normal circumstances, I would happily merge this PR first and rebase upon this one to add my other bits, but today is code freeze and that makes it not possible. The thing that makes it hard is that this is a bugfix indeed (which is super-encouraged during the code freeze/stabilization period), but it conflicts with a "feature" PR which is #41663, and which also has this fully incorporated.

I hope you understand. Anyway, if you find other bugs in kubeadm, I hope you never doubt about sending them :smile:! I'm really happy you're taking your time to contribute!
However, have you joined our Slack channel yet? To me, it seems like you haven't.
To avoid these situations in the future, we might be able to coordinate better via Slack on bugfixes, features, etc. Also, feel free to join our weekly sig meetings at Zoom at Tuesdays 5pm UTC+0 :clap:

**Comment by xilabao** [comment]
@luxas Never mind. It's my fault. I didn't notice your PR. In addition, thank you for your suggestion. the Slack channel seems to be a good place for discussing. I will join in :-)

**Pull request closed without merging**
