### PR TITLE
Parse system logs into structured messages in fluentd.

### PR DESCRIPTION
**Pull request by a-robinson**
This allows you to filter based on components of the log, like their severity, in the GCP log viewer or elasticsearch.

The metadata in the cloud log viewer looks like this:

screen shot 2016-02-04 at 12 18 02 am

cc @jimmidyson

### CODE REVIEW

**Comment by a-robinson** [comment]
And for future reference in case someone else needs to mess with these, http://fluentular.herokuapp.com/ is a good place to test regexes like this out

**Comment by jimmidyson** [comment]
LGTM we do something similar for OpenShift, albeit with different log files, formats, etc.

**Comment by a-robinson** [comment]
Sorry, I forgot to push the commit that actually enabled this change. It's pushed now.

**Comment by a-robinson** [comment]
@k8s-bot test this github issue: #IGNORE

**Comment by a-robinson** [comment]
There was an issue with some aspect of the new fluentd-es image caused by one of the underlying layers, seemingly the kubernetes_metadata plugin, since it was refusing to start without access to the apiserver.

I rebuilt the image using the same underlying version of fluentd and the metadata plugin as the previous image, and now it works. @jimmidyson, I'm assuming you're aware of this?

**Comment by a-robinson** [comment]
@k8s-bot test this github issue: #IGNORE

**Comment by a-robinson** [comment]
@k8s-bot test this github issue: #20646

**Comment by a-robinson** [comment]
@k8s-bot test this github issue: #20646

**Comment by a-robinson** [comment]
@k8s-bot test this github issue: #20646

**Comment by jimmidyson** [comment]
@a-robinson What version of the plugin were you using? Could you raise an issue in fabric8io/fluent-plugin-kubernetes_metadata_filter with details please?

**Comment by a-robinson** [comment]
I'm not sure, and I don't have the logs around anymore, but it was the version of the agent that got pulled in by the Dockerfile by default, which is just the most recent version judging by the command the pulls it in:
```
td-agent-gem install fluent-plugin-kubernetes_metadata_filter fluent-plugin-elasticsearch
```

**Pull request merged**
