### PR TITLE
Add scalability label to kubemark OWNERS

### PR DESCRIPTION
**Pull request by ehashman**
#### What type of PR is this?

/kind cleanup
/sig scalability
/assign @wojtek-t @mm4tt @shyamjvs

#### What this PR does / why we need it:

Auto-apply SIG scalability label to pkg/kubemark PRs. It's on other code but not here for some reason:

```
ehashman@fedora:~/src/k8s$ git grep 'sig/scalability'
cluster/images/kubemark/OWNERS:- sig/scalability
cluster/kubemark/OWNERS:- sig/scalability
cluster/log-dump/OWNERS:- sig/scalability
cluster/pre-existing/OWNERS:- sig/scalability
test/kubemark/OWNERS:  - sig/scalability
```

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm
/approve

thanks!

**Comment by mm4tt** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
