### PR TITLE
Automated cherry pick of #75295 upstream release 1.14

### PR DESCRIPTION
**Pull request by lbernail**
#75295: Add flag to enable strict ARP

/sig network
/area ipvs
/kind bug

/assign @m1093782566 

```release-note
[IPVS] Introduces flag ipvs-strict-arp to configure stricter ARP sysctls, defaulting to false to preserve existing behaviors. This was enabled by default in 1.13.0, which impacted a few CNI plugins.
```

### CODE REVIEW

**Comment by lbernail** [comment]
@m1093782566 could you ok-to-test and lgtm?

**Comment by lbernail** [comment]
@yastij thanks for the ok-to-test. Can you also lgtm?

**Review by yastij — APPROVED** [review]
/lgtm
/priority important-soon

as this breaks some of the CNI implementations

**Comment by lbernail** [comment]
@m1093782566 or maybe @thockin could you approve this cherry-pick?

**Comment by m1093782566** [comment]
/assign @thockin 

for approval.

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
