### PR TITLE
Rename controller pkg/registry/core/controller to pkg/registry/core/r…

### PR DESCRIPTION
**Pull request by ReneSaenz**
…eplicationcontroller

**What this PR does / why we need it**:

Rename controller pkg/registry/core/controller to pkg/registry/core/replicationcontroller
This will clarify the purpose of the controller since intent is replicationcontroller

Please refer to 
https://github.com/kubernetes/kubernetes/issues/17648

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
NONE
**Release note**:

```NONE
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
@k8s-bot ok to test

**Comment by ncdc** [comment]
@ReneSaenz you need to run `hack/update-bazel.sh`

**Pull request merged**
