### PR TITLE
kubeadm: use T.Run API in app/util

### PR DESCRIPTION
**Pull request by bart0sh**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Used [T.Run API](https://golang.org/pkg/testing/#T.Run) for kubeadm tests in the rest of app/util code

This should improve testing output and make it more visible
which test is doing what.

**Special notes for your reviewer**:

This is a third PR of a series aiming to usage of [T.Run API](https://golang.org/pkg/testing/#T.Run)  in all kubeadm tests. If this is accepted I'll send more PRs of this kind. 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by fabriziopandini — APPROVED** [review]
Thanks @bart0sh !
/approve
Let me know when all the taste pass so I will give final lgtm

**Comment by bart0sh** [comment]
@fabriziopandini merging is still blocked. It requires /lgtm I guess.

**Comment by bart0sh** [comment]
> Let me know when all the taste pass so I will give final lgtm

Sorry, missed your message. All tests are green now, please lgtm.

**Pull request merged**
