### PR TITLE
fix kube::log::error in `start_rsyncd_container`.

### PR DESCRIPTION
**Pull request by xuxinkun**
fix kube::log::error of `start_rsyncd_container` in common.sh.
Signed-off-by: xuxinkun <xuxinkun@gmail.com>

### CODE REVIEW

**Comment by xuxinkun** [comment]
ping @dims @lavalamp . May this PR be tested again ?

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by xuxinkun** [comment]
@dims May you call @k8s-bot gci gke e2e test this？

**Comment by dims** [comment]
@k8s-bot gci gke e2e test this

**Comment by xuxinkun** [comment]
Can this PR be merged? @dims

**Comment by dims** [comment]
@xuxinkun that would be upto @lavalamp (i am not a maintainer)

**Comment by xuxinkun** [comment]
@ixdy Can this PR be merged?

**Comment by ixdy** [comment]
/lgtm
@k8s-bot test this
@k8s-bot build this

thanks!

**Pull request merged**
