### PR TITLE
kubectl get hpa should print number of replicas

### PR DESCRIPTION
**Pull request by andrewsykim**
**What this PR does / why we need it**:
Prints number of replicas on deployment managed by HPA. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
None, couldn't find one related.

**Special notes for your reviewer**:
Couldn't find any tests for validating kubectl output for hpa, if there are please point me to them and I will add. 

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
@k8s-bot ok to test

**Comment by deads2k** [comment]
@k8s-bot kops aws e2e test this

**Comment by andrewsykim** [comment]
@deads2k can we kick the AWS tests again?

**Comment by deads2k** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
