### PR TITLE
Fix a debugging line

### PR DESCRIPTION
**Pull request by caesarxuchao**
A trivial update. @k8s-oncall can we manually merge it?

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM :)

**Comment by caesarxuchao** [comment]
@k8s-bot test this, issue #IGNORE

**Comment by caesarxuchao** [comment]
@k8s-oncall can we manually merge this one line change?

**Comment by lavalamp** [comment]
Sorry, not manually merging this that aren't emergencies. If you get the unit tests green then the merge queue will merge it almost immediately.

**Comment by caesarxuchao** [comment]
@k8s-bot unit test this, issue #27179

**Comment by caesarxuchao** [comment]
@k8s-bot unit test this, issue #27179

**Pull request merged**
