### PR TITLE
CRI: Rename container/sandbox states

### PR DESCRIPTION
**Pull request by yujuhong**
The enum constants are not namespaced. The shorter, unspecifc names are likely
to cause naming conflicts in the future.

Also replace "SandBox" with "Sandbox" in the API for consistency.

/cc @kubernetes/sig-node

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35998)

### CODE REVIEW

**Comment by euank** [comment]
Good call, :+1:

**Comment by Random-Liu** [comment]
LGTM

**Comment by Random-Liu** [comment]
@k8s-bot cri test this.

**Comment by yujuhong** [comment]
Applying lgtm based on the comments above.

**Comment by feiskyer** [comment]
lgtm

**Pull request merged**
