### PR TITLE
Automated cherry pick of #55262

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #55262 on release-1.8.

#55262: Fix 'Schedulercache is corrupted' error

### CODE REVIEW

**Comment by liggitt** [comment]
fixed gofmt error

**Comment by liggitt** [comment]
actually fixed gofmt error

**Comment by jpbetz** [comment]
According to [prow](http://prow.k8s.io/?pull=55266) logs, the last run of `pull-kubernetes-verify` [was successful](http://prow.k8s.io/log?job=pull-kubernetes-verify&id=60660) but for some reasons the status is still pending..

**Comment by jpbetz** [comment]
Manually merging this, since all remaining test passed:

- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/55266/pull-kubernetes-kubemark-e2e-gce/61091/
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/55266/pull-kubernetes-e2e-kops-aws/57951/
- https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/55266/pull-kubernetes-verify/60660/

Not sure what's going on with prow.

**Pull request merged**
