### PR TITLE
Rework proto generation scripts and add tests

### PR DESCRIPTION
**Pull request by sttts**
* added a `// +k8s:protobuf-gen=package` tag and removed the long (incomplete) package lists from the protobuf update and verify script.
* added proto roundtrip tests where missing

### CODE REVIEW

**Comment by liggitt** [comment]
the ordering and generation is problematic... proto files in other packages are picking up all core/v1 types

split the unit test commit into https://github.com/kubernetes/kubernetes/pull/74937 for earlier merge

**Comment by sttts** [comment]
@liggitt added topological sorting to go-to-protobuf. Diff is zero now  🎉

**Comment by sttts** [comment]
@liggitt can you tag? this needs api approval due to the new tags in the doc.go files.

**Comment by liggitt** [comment]
/approve

/hold
for cblecker review

do we need a sanity check that the package-finding part actually locates a non-zero number of packages?

**Comment by liggitt** [comment]
actually, cblecker is out of the office. 

/cc @BenTheElder 
for bash/test ack?

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Pull request merged**
