### PR TITLE
Fix the kube-aggregator help message

### LINKED ISSUE #51930: kube-aggregator help message needs improvement
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
> /kind feature

**What happened**:
```
kube-aggregator --help
...
      --proxy-client-cert-file string    client certificate used identify the proxy to the API server
      --proxy-client-key-file string     client certificate key used identify the proxy to the API server
...
```

**What you expected to happen**:

```
kube-aggregator --help
...
      --proxy-client-cert-file string    client certificate used to identify the proxy to the API server
      --proxy-client-key-file string     client key used to identify the proxy to the API server
...
```

**How to reproduce it (as minimally and precisely as possible)**:
As above.

**Anything else we need to know?**:
No.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by tengqm**
**What this PR does / why we need it**:
This fixes the help message for kube-aggregator.

**Which issue this PR fixes**: fixes #51930

**Special notes for your reviewer**:
Trivial fix.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
ping @lavalamp for approval :)

**Comment by tengqm** [comment]
@k8s-ci-robot please stop the ping-pong game ...

**Review by cheftako — APPROVED** [review]
/lgtm

**Comment by tengqm** [comment]
rebased for CI to reverify ... sigh.

**Comment by tengqm** [comment]
@liggitt ping

**Comment by tengqm** [comment]
7 months is long enough for patience.

**Pull request closed without merging**
