### PR TITLE
Add dnsmasq to test/images/dnsutils

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

We currently use k8s.gcr.io/k8s-dns-dnsmasq:1.14.5 in the
dns_common.go file. Looking deeper, all we need is "/usr/sbin/dnsmasq"
from that image. So just enhance the dnsutils image and throw dnsmasq
into it. This makes it easier as the dockerfiles/sidecars etc in
kubernetes/dns is not really needed. Note that a previous attempt to add
manifests to that repo fell through in PR 30 in that repo (since we were
moving to coredns).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/cc @luxas 
/cc @ixdy 
/cc @mkumatag 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
related to https://github.com/kubernetes/dns/pull/30

Note that once we fix this, we can remove the reference to `k8s-dns-dnsmasq` in manifest.go and just use the `dnsutils` image.

**Comment by dims** [comment]
related to https://github.com/kubernetes/kubernetes/issues/66626

**Review by luxas — APPROVED** [review]
I approve this change as-is, it makes sense for dnsmasq to be in this e2e test image. But I don't approve this test image replacing the existing prod kube-dns images we have, let's just stick with those as they are. CoreDNS is the answer to DNS multi-arch support, kube-dns is phased out in any case.

/approve

**Comment by spiffxp** [comment]
>I don't approve this test image replacing the existing prod kube-dns images we have, let's just stick with those as they are

+1

**Comment by dims** [comment]
@luxas this image will be used only the few spots where we use `dnsmasq` and not for any other purpose.

**Comment by luxas** [comment]
> only the few spots where we use dnsmasq

which I assume is in testing?

**Comment by dims** [comment]
@luxas specifically https://cs.k8s.io/?q=sbin.*dnsmasq&i=nope&files=&repos=kubernetes

**Comment by dims** [comment]
@ixdy oops. done https://github.com/kubernetes/kubernetes/pull/66727/

**Pull request merged**
