### PR TITLE
AWS: Update SDK

### PR DESCRIPTION
**Pull request by justinsb**
This PR updates our aws-sdk-go godep, and then makes a minor change to configure authentication logging for the new SDK.  This is primarily about updating the SDK so we can e.g. enable more logging.

```release-note
AWS: Configure verbose authentication logging and update SDK 
```

### CODE REVIEW

**Comment by justinsb** [comment]
A GoDep riddle:

* aws-sdk-go has removed the `github.com/aws/aws-sdk-go/private/endpoints` package
* k8s has a dependency on `github.com/docker/distribution`
* `github.com/docker/distribution/Godeps/Godeps.json` has a dependency on `github.com/aws/aws-sdk-go/private/endpoints`
* godep save failed with `W0112 22:00:53.725] godep: Package (github.com/aws/aws-sdk-go/private/endpoints) not found`
* this causes `hack/verify-godeps.sh` to fail

At least I believe that is the dependency chain.  Is there any way to update the aws-sdk-go library?  @thockin ?

**Comment by ncdc** [comment]
As discussed in Slack, if the vendored copy of docker/distribution is not actually using the package that has been removed from aws-sdk-go, you can put a hack in veryify-godeps.sh to add an empty doc.go (with a package statement) to $GOPATH/src/github.com/aws/aws-sdk-go/private/endpoints, and that should get you past the current issue.

The better solution is to bump the vendored copy of aws-sdk-go in docker/distribution, then bump both docker/distribution and aws-sdk-go in kube.

**Comment by thockin** [comment]
This is the gordian knot of vendoring.  How is it resolvable?  X -> (Y, Z);
Y -> Z; X wants to update to Z'; Z' is not compatible with Y.

**Comment by justinsb** [comment]
This was done in 9737b4118924be1fd2d862cf360a2d25813b1b2d

**Pull request closed without merging**
