### PR TITLE
Configmap enhancements

### PR DESCRIPTION
**Pull request by zefciu**
This is submitted for a discussion and tests. Please comment the features and submit any proposals.

This PR introduces three ConfigMap enhancements.
1. You can now interpolate Pod facts in configmap values. Eg:
   '{{ .Pod.PodIP }}' will interpolate current pod IP.
2. Values from other configmaps can be interpolated as well:
   '{{ (.ConfigMap "cm").foo }}' will interpolate key 'foo' from
   configmap 'cm'
3. You can render configmaps as files in downwardAPI volumes. Eg:

```
items:
    - path: "cfg.ini"
      configMapRef: "special-config"
      template: |
          [DEFAULT]
          LABELS = {{ .speciallabels }}
          POD_NAME = {{ .specialname }}

Will render a "cfg.ini" file with values from "special-config" configmap
interpolated.

<!-- Reviewable:start -->

---
This change is [<img src="https://reviewable.kubernetes.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30502)
<!-- Reviewable:end -->
```

### CODE REVIEW

**Comment by thockin** [comment]
Ideas like this are generally better discussed as proposal docs, rather than code.  It's far easier to get the intentions through words than through code.

(a) is already handled by downwardAPI

(b) means this is no longer ConfigMap and is instead some uber-volume, which I am not AGAINST but I'd need to see justification for.  We have a "budget" for idea and complexity, and whatever we spend on this idea can't be spent elsewhere.

(c) is stepping in the grey area of what Kubernetes isn't.  I'm not strictly against templating, because I know how useful simple templates can be, but I also know that it is a slipper slope to complex expressions.  I'd rather build a sidecar container for some templating tool (or tools) and have that sidecar ingest a config map with template and expansions, and write out a config file.

**Comment by derekwaynecarr** [comment]
It appears to me that the desired goal in this PR is to allow a single projection that spans values from multiple `ConfigMap` objects, or the pod downward API.  The proposed solution is to support this uber-projection by modifying `ConfigMap`.  That is a less than ideal factoring versus having another object that supports that aggregated projection concept.

**Comment by pmorie** [comment]
This is also the second PR for this, please see discussion on the original PR: #29607

I would really prefer to find a solution for this that is more than configmap.  The right solution will encompass templating from secrets, configmap, and downward API.

**Comment by jberkus** [comment]
What about calling it new ConfigTemplate object?  Or maybe FileTemplate? 

That avoids some of the recursiveness of the concept.

**Comment by pmorie** [comment]
@jberkus what I would really like to see is a proposal before code.  Templates have been pretty controversial in the past (everyone wants their own pet preferred template engine, amongst other things).  So, we really need to hash this out in a proposal and discussion first.

**Comment by thockin** [comment]
As a PR this is not going anywhere as-is, so I am going to close it for the sake of the bots that scan all PRs.  We should have a proposal with a crisp problem statement and evaluation of the implementation options

**Comment by pmorie** [comment]
+1 @thockin

**Comment by jberkus** [comment]
@thockin , @pmorie discussion started.

**Comment by thockin** [comment]
Thanks!

**Comment by ludwikbukowski** [comment]
Whats the status?

**Comment by zefciu** [comment]
@ludwikbukowski I no longer work on kubernetes. If you are interested in these changes, feel free to submit a PR yourself.

**Pull request closed without merging**
