### PR TITLE
Always masquerade node-originating traffic with a service VIP source ip

### LINKED ISSUE #63241: IPVS proxy does not SNAT service IPs
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When using IPVS and not natting (no cluster-cidr specified) requests from the host to service IPs are send with the service ip as the source ip.

Let `10.120.0.1` be the kubernetes API IP. Kubeproxy will set up `kube-ipvs0` with `10.120.0.1/32`. This means that traffic from the host (which sees the `kube-ipvs0`) will originate from `10.120.0.1` (best matching ip/network).

**What you expected to happen**:

The source ip should be natted to the host ip.

**How to reproduce it (as minimally and precisely as possible)**:

1. Use a ipvs based cluster
1. Remove any cluster-cidr from kube-proxy
1. Send traffic to a service ip (e.g. http to the kubernetes api server) from the node / host network pod
1. tcpdump the outgoing interface looking for the service ip (`tcpdump .... host 10.120.0.1`)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:26:04Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"clean", BuildDate:"2018-04-12T14:14:26Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: baremetal
- OS (e.g. from /etc/os-release): `Debian GNU/Linux 8 (jessie)`
- Kernel (e.g. `uname -a`): `4.15.3+soundcloud2` (based on the Ubuntu 18.04 kernel)
- Install tools: custom repackaging of kubernetes release tarballs
- Others:

/sig network

### PR DESCRIPTION
**Pull request by rtreffer**
**What this PR does / why we need it**:
This is a follow up to make IPVS work on systems without cluster-cidr or masquerade-all.
On these systems the best matching network / source IP to reach the service VIP is the service VIP itself - at least for the host network.
The workaround is simple: Everything originating on the host (OUTPUT nat chain) with a source IP that is the VIP should be masqueraded.

The relevant rule change is the first rule in `KUBE-SERVICES`:
```
Chain KUBE-SERVICES (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-MARK-MASQ  all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set KUBE-CLUSTER-IP src,dst
  104  6240 KUBE-MARK-MASQ  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp match-set KUBE-NODE-PORT-TCP dst
```

The matching rule could be stricter by matching src(ip),dst(ip),dst(port) but the src ip will only be selected if the VIP should be reached.

**Which issue(s) this PR fixes**
Fixes #63241

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by rtreffer** [comment]
/assign @m1093782566 

@Lion-Wei I think this is an actual fix for the issue. The device up just changed our routing while this one masqueraded traffic correctly. I've also tested that it does not impact container traffic.

**Comment by rtreffer** [comment]
That does not look like a related error, the garbagecolletor test failed.

Could this be retested? Or should I try a rebase on master?

k8s-ci-robot <notifications@github.com> schrieb am Di., 1. Mai 2018, 03:03:

**Comment by m1093782566** [comment]
@rtreffer 

I am afraid you changes will break the source IP reservation of ClusterIP type traffic? 

@Lion-Wei WDTY?

**Comment by rtreffer** [comment]
@m1093782566 I don't think so.... The service VIP should only exist on the node and not on output.

A POD contacts the service VIP, ipvs does the natting to the target IP. After that the connection is tracked and will get the right ips passed through. It would break IPVS DR. But the service VIP only exists on the node-local receive path....

It should be tested on a full cluster...

I've just upgraded our test cluster to a custom 1.10 build with this patch. We create a service for just about every service we deploy (which is also why we would like to use ipvs).

We run a simple test app on that cluster that exposes port 80
```
  spec:
    clusterIP: 10.120.229.237
    externalTrafficPolicy: Cluster
    ports:
    - name: http
      nodePort: 32230
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      component: web
      env: production
      system: rocket
    sessionAffinity: None
    type: NodePort
```

- The nodePort works.
- Reaching 10.120.229.237 from the host network works
- Reaching 10.120.229.237 from a pod works

I've installed tcpdump in a pod to verify that I do see the service VIP on returned traffic... Here is a tcpdump of the TCP handshake from a pod ip to the service ip (captured inside the pod)
```
19:58:17.756678 IP 10.128.9.109.36754 > 10.120.229.237.80: Flags [S], seq 2250761412, win 29200, options [mss 1460,sackOK,TS val 3945048769 ecr 0,nop,wscale 9], length 0                      
19:58:17.756843 IP 10.120.229.237.80 > 10.128.9.109.36754: Flags [S.], seq 1602031708, ack 2250761413, win 28960, options [mss 1460,sackOK,TS val 3767689189 ecr 3945048769,nop,wscale 9], length 0
19:58:17.756866 IP 10.128.9.109.36754 > 10.120.229.237.80: Flags [.], ack 1, win 58, options [nop,nop,TS val 3945048769 ecr 3767689189], length 0
```

Anyway, all of that is hard to reason about, I could add a rule specifically for matching `(service VIP, service VIP, port)` (`src,dst,dst`). Would that be better? Or am I missing something else?

**Comment by rtreffer** [comment]
The POD IP won't be masqueraded. This rule only masquerades new traffic
coming _from_ a service VIP. This should only ever happen on the host
network where the VIP is assigned to the kube-ipvs0 interface.

Anything that does not own the VIP won't select it as source IP.

DuJun <notifications@github.com> schrieb am Mi., 2. Mai 2018, 04:19:

**Comment by m1093782566** [comment]
@rtreffer 

Please rebase this PR if you want to let it in on v1.11 circle.

**Comment by m1093782566** [comment]
@murali-reddy 

I find there is a similar fix for kube-router. Would you please take a look at this when you have a chance. Much appreciate.

**Comment by igorvpcleao** [comment]
Hi @rtreffer,
Is there a reason why this was not merged to kube 1.10.x?

**Comment by Lion-Wei** [comment]
Hi, @rtreffer I think that was because ipvs feature was in beta in 1.10, not sure.

**Pull request merged**
