### PR TITLE
Refactor `fmt.Errorf` to use `%w` to wrap other errors instead of `%v`

### LINKED ISSUE #123234: Make `fmt.Errorf` use `%w` to wrap error instead of `%v`
### What would you like to be added?

Make it canonical to use `%w` for all `fmt.Errorf` to wrap error. If it's believed a good idea, we can add lint check.

### Why is this needed?

According to [fmt.Errorf doc](https://pkg.go.dev/fmt#Errorf), verb `%w` will make it return a new error wrapping the operand error, which allows using `errors.As()`. Many error [handling functions](https://github.com/kubernetes/apimachinery/blob/v0.29.1/pkg/api/errors/errors.go#L546) in k8s rely on `errors.As()`. However, the majority of `fmt.Errorf` in current k8s code is using verb `%v`, which may lead to false assumption in using `errors.As()`.

There might be good reasons to use `%v` to abstract the implementation details as well, but it should be rare.

### PR DESCRIPTION
**Pull request by ah8ad3**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Refactor to use %w for all fmt.Errorf to wrap error. Inside component base.

#### Which issue(s) this PR fixes:

Fixes #123234
Fixes the issue for component base.
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by ah8ad3** [comment]
If the changes are too big we can reduce them to each directory, but that would become more challenging to make so much commits.

**Comment by ah8ad3** [comment]
Kindly
/cc thockin

**Comment by ah8ad3** [comment]
If we are not using this method on resolving this issue please do not hesitate to close this PR, thanks.
Otherwise i am happy to help.
@pohly

**Review by pohly — COMMENTED** [review]
/close

We decided in the issue to not make sweeping changes to all fmt.Errorf calls. Looking at these specific examples it's not clear whether anyone would unwrap the errors, so there's no need to merge this.

Thanks for preparing the PR, though!

**Pull request closed without merging**
