### PR TITLE
Automated cherry pick of #40892

### LINKED ISSUE #40819: Wrong VM name is retrieved by the vSphere Cloud Provider
**What keywords did you search in Kubernetes issues before filing this one?**: VMware, vSphere, IP, UUID

---

BUG REPORT. 

**Kubernetes version**:

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0", GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", BuildDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: VMware vSphere 6.5.0
- **OS** : Debian GNU/Linux 8.7 (jessie)
- **Kernel** :` Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux`
- **Install tools**: Kargo

**What happened**:

Some containers were launched on a node with a name containing the hostname of a different node and the `kubelet_node_status.go` does not retrieve the right node name :

```
Feb  1 18:11:16 k8s.minionpp-01.adm kubelet[1009]: I0201 18:11:16.953239    1060 kubelet_node_status.go:74] Attempting to register node k8s.minionpp-02
Feb  1 18:11:16 k8s.minionpp-01.adm kubelet[1009]: I0201 18:11:16.972697    1060 kubelet_node_status.go:113] Node k8s.minionpp-02 was previously registered
Feb  1 18:11:16 k8s.minionpp-01.adm kubelet[1009]: I0201 18:11:16.972783    1060 kubelet_node_status.go:77] Successfully registered node k8s.minionpp-02
```

Here `k8s.minionpp-02` is retrieved instead of `k8s.minionpp-01`.

When using the VSphere Cloud provider, the node name is retrieved from the `getVMName` function in https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L204. 

Since this PR (https://github.com/kubernetes/kubernetes/pull/27331/files), the node data are retrieved based on the IP address instead of the UUID. The function gets all the IP address and check if one of the IP on any interface matches a VM on vSphere. The problem is that the docker0 interface has the same IP on all the nodes (usually 172.17.0.1) and this IP is referenced into VMware. As this IP may be the first to appear in the [addr list](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L205) it will match the first VM that vSphere gives with the [FindByIp](https://github.com/vmware/govmomi/blob/f9184c1d704efa615d419dd8d1dae1ade94701d1/object/search_index.go#L100) function and this can be any VM running Docker on vSphere. Thus, the provider has a big chance to not get the informations for the VM it is running on, leading to an inconsistent state in the cluster (wrong pod name for example). 

**Anything else we need to know**:

An idea would be to first retrieve the VM name with the [FindByDnsName](https://github.com/vmware/govmomi/blob/f9184c1d704efa615d419dd8d1dae1ade94701d1/object/search_index.go#L59) function and if no results use the IP address (and add an exclusion to not use the `docker0` interface).  What do you think ? If you think this might be the right way to do, we can try to propose the PR.

Thanks for your feedback.

### PR DESCRIPTION
**Pull request by kerneltime**
Cherry pick of #40892 on release-1.4.

#40892: Fixes #40819

### CODE REVIEW

**Comment by kerneltime** [comment]
@k8s-bot verify test this

**Comment by kerneltime** [comment]
@k8s-bot verify test this

**Comment by jessfraz** [comment]
@k8s-bot test this please

**Comment by kerneltime** [comment]
@k8s-bot unit test this

**Comment by jessfraz** [comment]
@k8s-bot unit test this

**Comment by jessfraz** [comment]
all green merging

**Pull request merged**
