### PR TITLE
Add cluster autoscaler to aws kube-up

### PR DESCRIPTION
**Pull request by andrewsykim**
Adds cluster autoscaler support for `kube-up` in aws.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36387)

### CODE REVIEW

**Comment by andrewsykim** [comment]
@mwielgus @justinsb

**Comment by mwielgus** [comment]
@eparis Could you please take a look?

**Comment by mwielgus** [comment]
@justinsb Could you please take a look?

**Comment by andrewsykim** [comment]
I was told that kube-up was deprecating in favour of kops for E2E testing (hence https://github.com/kubernetes/kops/pull/914). Would it make more sense to close this and open another PR for getting it working in kops?

**Comment by mwielgus** [comment]
@justinsb Could you please confirm that we should not add new AWS features to kube_up.sh?

**Pull request closed without merging**
