### PR TITLE
fix: Fix multiple typos in docs under content/en/docs/reference

### PR DESCRIPTION
**Pull request by n0vad3v**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:

This PR is related with https://github.com/kubernetes/website/pull/46178, aims to fix upstream typos which will reflect in docs.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/website/pull/46178

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by wangyysde** [comment]
@n0vad3v As if you should run some scripts(such as hack/update-all.sh) in hack directory before submit PR.

**Comment by n0vad3v** [comment]
@wangyysde Thanks for pointing out, `./hack/update-all.sh has been replaced by 'make update'`, I've tried `make update`, and it changed lot's of files:

```
On branch typo
Your branch is up to date with 'origin/typo'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   api/discovery/aggregated_v2.json
	modified:   api/discovery/aggregated_v2beta1.json
	modified:   api/discovery/apis.json
	modified:   api/discovery/apis__flowcontrol.apiserver.k8s.io.json
	modified:   api/openapi-spec/swagger.json
	modified:   api/openapi-spec/v3/apis__storage.k8s.io__v1_openapi.json
	modified:   pkg/generated/openapi/zz_generated.openapi.go
	modified:   staging/src/k8s.io/api/storage/v1alpha1/generated.proto
	modified:   staging/src/k8s.io/api/storage/v1alpha1/types_swagger_doc_generated.go

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	api/discovery/apis__flowcontrol.apiserver.k8s.io__v1beta1.json
	api/discovery/apis__flowcontrol.apiserver.k8s.io__v1beta2.json
	api/openapi-spec/v3/apis__flowcontrol.apiserver.k8s.io__v1beta1_openapi.json
	api/openapi-spec/v3/apis__flowcontrol.apiserver.k8s.io__v1beta2_openapi.json

no changes added to commit (use "git add" and/or "git commit -a")
```

I've pushed to `typo` branch at https://github.com/kubernetes/kubernetes/pull/124696/commits/c25b1ef662616855d1272108b87cdca6db03f551, but I'm not sure whether it's correct.🤔

**Review by dgrisonnet — APPROVED** [review]
Approving changing to the metrics documentation.

/approve

**Pull request closed without merging**
