### PR TITLE
Automated cherry pick of #24924 upstream release 1.2

### PR DESCRIPTION
**Pull request by roberthbailey**
Cherry pick of #24924 on release-1.2.

### CODE REVIEW

**Comment by roberthbailey** [comment]
@k8s-bot test this issue: #24207

**Comment by roberthbailey** [comment]
@k8s-bot unit test this issue: #24207

**Comment by roberthbailey** [comment]
@smarterclayton @liggitt This PR has failed unit tests twice in a row with etcd-related issues, e.g.

```
FAIL: TestDelete (13.21s)
	utils.go:244: Unexpected error in waitUntilUp (timeout on waiting for etcd cluster)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x752ea4]

goroutine 216 [running]:
testing.tRunner.func1(0xc8204af290)
	/tmp/workdir/go/src/testing/testing.go:450 +0x1f5
k8s.io/kubernetes/pkg/registry/registrytest.NewEtcdStorage(0xc8204af290, 0x0, 0x0, 0x0, 0x0, 0x0)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/registrytest/etcd.go:40 +0x204
k8s.io/kubernetes/pkg/registry/limitrange/etcd.newStorage(0xc8204af290, 0x200, 0xc8200d46e0)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/limitrange/etcd/etcd_test.go:33 +0x3f
k8s.io/kubernetes/pkg/registry/limitrange/etcd.TestDelete(0xc8204af290)
	/workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/registry/limitrange/etcd/etcd_test.go:107 +0x41
testing.tRunner(0xc8204af290, 0x24b6230)
	/tmp/workdir/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:561 +0xaa4
...
```

If we are going to cut a 1.2.4 imminently I'm concerned this won't have enough bake time for us to fully understand why this isn't working properly.

**Comment by liggitt** [comment]
I don't see how these would affect registry unit tests in a different package

**Comment by liggitt** [comment]
fyi, other release-1.2 pulls are hitting etcd unit test failures as well:

https://github.com/kubernetes/kubernetes/pull/25164

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/pr-logs/pull/25164/kubernetes-pull-test-unit-integration/24232/

```
FAIL	k8s.io/kubernetes/pkg/registry/controller/etcd	57.335s
FAIL	k8s.io/kubernetes/pkg/registry/daemonset/etcd	40.083s
FAIL	k8s.io/kubernetes/pkg/registry/deployment/etcd	55.486s
FAIL	k8s.io/kubernetes/pkg/registry/namespace/etcd	40.212s
FAIL	k8s.io/kubernetes/pkg/storage	116.501s
```

**Comment by roberthbailey** [comment]
@k8s-bot unit test this issue: #24207

**Pull request merged**
