### PR TITLE
Automated cherry pick of #11692

### PR DESCRIPTION
**Pull request by wojtek-t**
Swich to new gcloud API for GCE MIGs

### CODE REVIEW

**Comment by roberthbailey** [comment]
LGTM.

**Comment by alex-mohr** [comment]
@k8s-bot test this [contrib/submit-queue: candidate for merging]

**Comment by alex-mohr** [comment]
@k8s-bot test this [deflake attempt]

**Comment by alex-mohr** [comment]
@k8s-bot test this [contrib/submit-queue: candidate for merging]

**Comment by alex-mohr** [comment]
Automatic merge from SubmitQueue

**Pull request merged**
