### PR TITLE
Add pod_infra_container_image support to local-up-cluster.sh script

### PR DESCRIPTION
**Pull request by nkwangleiGIT**
**What this PR does / why we need it**:
This PR will add the support to customize pod_infra_container_image parameter of kubelet using environment variable, so we can easily use the infra image of ourself, it'll help in two cases:
1) The user customize the infra image and need to let kubelet pull from the private docker registry

2) Due to GFW in China, we're not able to pull images from gcr.io, so we need this parameter to use local docker registry service to pull the image

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by gyliu513** [comment]
lgtm, +1 for this even though I think most people behind the GFW would have their own proxy running, thanks @nkwangleiGIT .

**Comment by nkwangleiGIT** [comment]
@lavalamp @eparis 
Can you help check if this PR can be merged? Thanks!

**Comment by vishh** [comment]
I'm not in favor of adding more parameters. Why not use `KUBELET_FLAGS` parameter?
I'd like to add new parameters only for widely used flags.

**Comment by nkwangleiGIT** [comment]
@vishh  how can I add KUBELET_FLAGS when run local-up-cluster script without modifying the script? If it works, yes, I can close this PR, thanks!

**Comment by vishh** [comment]
`KUBELET_FLAGS="foo=bar" hack/local-up-cluster.sh`

**Pull request closed without merging**
