### PR TITLE
code cleanup for kubectl apply_edit_last_applied.go ,completion.go,cp.go,wait.go

### PR DESCRIPTION
**Pull request by changshuchao**
Signed-off-by: changshuchao <chang.shuchao1@zte.com.cn>

#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by eddiezane** [comment]
Nice looks like you got them all.

/approve
/triage accepted
/priority backlog

**Comment by changshuchao** [comment]
@eddiesimeon  can this pr be merged？

**Comment by eddiezane** [comment]
@changshuchao we're currently in [code freeze](https://groups.google.com/g/kubernetes-sig-release/c/rhVJmlazdCs?pli=1) for v1.21. It should merge automatically after the release is cut.

**Pull request merged**
