### PR TITLE
Automated cherry pick of #103794: feat: Provide IPv6 support for internal load balancer

### PR DESCRIPTION
**Pull request by ialidzhikov**
Cherry pick of #103794 on release-1.22.

#103794: feat: Provide IPv6 support for internal load balancer

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by ialidzhikov** [comment]
/assign @cheftako 
for approval

**Comment by puerco** [comment]
@cheftako could you take a look at this one? :pray:

**Comment by puerco** [comment]
Thanks for handling this @ialidzhikov !
/lgtm

**Pull request merged**
