### PR TITLE
Volunteer to help with OpenStack provider reviews

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

I'd like to help with keeping the OpenStack cloud provider up-to-date

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FengyunPan** [comment]
LGTM

**Comment by anguslees** [comment]
/lgtm
(about time! ;)

**Pull request merged**
