### PR TITLE
add test for String

### PR DESCRIPTION
**Pull request by muyangren2**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Add UT
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
"NONE"
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
i think we can use regular compare without testify.

/approve
/ok-to-test

**Comment by muyangren2** [comment]
> i think we can use regular compare without testify.
> 
> /approve /ok-to-test

I will modify it according to your opinion，thank you

**Comment by dims** [comment]
/assign @neolit123 

Lubomir, this is ready!

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
