### PR TITLE
Remove duplicated code in secret e2e tests

### PR DESCRIPTION
**Pull request by rata**
**What this PR does / why we need it**: This come up when writing another PR: https://github.com/kubernetes/kubernetes/pull/28936 as a comment from @thockin. 

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: 

**Special notes for your reviewer**:

**Release note**:

``` NONE
```

This patch just removes duplicated code in secret e2e tests.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33978)

### CODE REVIEW

**Comment by rata** [comment]
This may fail a few times as it's not easy for me to test it in my old hardware. But if you can authorize it to test, it would be great :)

**Comment by fejta** [comment]
Nice improvement @rata! Will someone from @kubernetes/sig-storage give assign this to themselves and give it a quick review?

**Comment by rata** [comment]
@fejta thanks! Do you think it's "ok to test" so we can actually see it works fine?

**Comment by saad-ali** [comment]
@k8s-bot ok to test

**Comment by saad-ali** [comment]
LGTM

**Comment by rata** [comment]
@saad-ali thanks! :)

**Comment by saad-ali** [comment]
No problem! Thanks for the cleanup

**Comment by rata** [comment]
@saad-ali I've just rebased and pushed today, because I thought the last fail were flaky. And it seems they are, as one now passed and the other failed.

Should I just retry until this passes? Or what should I do in this case? (looking at the error, it seems unrelated)

**Comment by saad-ali** [comment]
> Should I just retry until this passes? Or what should I do in this case? (looking at the error, it seems unrelated)

Yes, but you don't have to do a rebase/push to trigger retest.

**Comment by saad-ali** [comment]
@k8s-bot gke e2e test this, Issue: #33175

**Comment by rata** [comment]
@saad-ali thanks! I do rebase/amend and push because I think I don't have permissions to send that command to the bot :-)

**Comment by saad-ali** [comment]
Right, sorry about that

**Pull request merged**
