### PR TITLE
WIP: CR encryption

### LINKED ISSUE #104165: Custom resources don't get encrypted in etcd
#### What happened:
Trying to encrypt a custom resource in etcd with the following EncryptionConfiguration in kube-apiserver does not lead to encrypted state in etcd.

In this example the custom resource is named "tokens" and belongs to the group "management.cattle.io":

`apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
- providers:
  - aescbc:
      keys:
      - name: some-key
        secret: some-secret
  - identity: {}
  resources:
  - tokens.management.cattle.io
- providers:
  - aescbc:
      keys:
      - name: some-key
        secret: some-secret
  - identity: {}
  resources:
  - secrets`

#### What you expected to happen:
Expecting custom resources to be encrypted in etcd if queries e.g. like this:
`etcdctl get /registry/management.cattle.io/tokens/some-token`

#### How to reproduce it (as minimally and precisely as possible):

Activate encryption on the kube-apiserver with a `EncryptionConfiguration` definition on any custom resource and query state in etcd.

#### Anything else we need to know?:
Tested this both with namespaced and non-namespaced custom resources. In both cases encryption does not work.

#### Environment:
- Kubernetes version: v1.20.6
- Cloud provider or hardware configuration: Openstack
- OS: flatcar 2765.2.3
- Kernel: Linux host-10-13-39-90 5.10.32-flatcar #1 SMP Tue Apr 27 22:38:30 -00 2021 x86_64 Intel Core Processor (Haswell, no TSX, IBRS) GenuineIntel GNU/Linux
- Install tools: rke version v1.2.9

### PR DESCRIPTION
**Pull request by ankeesler**
Note: this doesn't work right now - I am simply posting a WIP to show my progress.

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

- Enable encryption of custom resources in ETCD (see https://github.com/kubernetes/kubernetes/issues/104165)

#### Which issue(s) this PR fixes:

Fixes #104165

#### Does this PR introduce a user-facing change?

```release-note
Custom resources can now be encrypted in ETCD
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
Custom resources can now be encrypted in ETCD
```

### CODE REVIEW

**Comment by fedebongio** [comment]
/triage accepted
Triaging for now, if you need our attention please tag us back. On a related comment, the feedback from the triage meeting was that this either will require a KEP or to be discussed in the SIG Meeting to move forward when you are ready. Thanks!

**Comment by enj** [comment]
> Triaging for now, if you need our attention please tag us back. On a related comment, the feedback from the triage meeting was that this either will require a KEP or to be discussed in the SIG Meeting to move forward when you are ready. Thanks!

https://github.com/kubernetes/kubernetes/issues/104165#issuecomment-904093168

I do not think a KEP is needed to fix this bug (see above comment).  @deads2k mentioned that this is simply a bug in the implementation.

**Comment by lavalamp** [comment]
IMO we can fix this bug without a KEP.

**Comment by deads2k** [comment]
Fixing the bug to honor this flag for all resources is ok without a KEP.

You will need an integration test to prove that the new code functions properly.

**Comment by enj** [comment]
/milestone v1.24

Andrew does not have cycles this release.  Hopefully next release 😄

**Comment by dims** [comment]
please reopen if you still need this WIP PR. Trying to declutter the open PR(s)

**Pull request closed without merging**
