### PR TITLE
[WIP] Secret generation REST API

### PR DESCRIPTION
**Pull request by jimmidyson**
Discussed previously in #12732, this PR adds pluggable secret generation to the REST API via a subresource (`GenerateSecretRequest`) on secret at `/api/v1/secrets/<name>/generate`. This PR also provides 2 generator implementations, password & ssh-key (2 that I personally need of course ;)). Generators return the `data` content for a secret (`map[string][]byte`).

Generators should provide a default (unparameterized) with sane defaults (e.g. password: 16 chars length; ssh key: RSA, 2048bit; etc). Generators may need parameters (e.g. ssh key type/length). Due to the free-form nature of secret types & contents, this is currently implemented by passing parameters in annotations on the `GenerateSecretRequest`. Annotations are copied to the generated secret to allow for future work such as TTLs & secret re-generation.

I'm more interested in feedback on the idea & REST API implementation atm than the implemented generators.

This functionality currently exists in various clients, including `openshift` & `gofabric8`. Moving this into the API server will provide a consistent experience as well being able to centralise security requirements. such as generating/requesting a TLS certificate from an external provider, especially letsencrypt (something people have been asking for - Certs as a Service).

### CODE REVIEW

**Comment by jimmidyson** [comment]
@thockin This is what I was talking about in NY.

**Comment by bgrant0607** [comment]
cc @kelseyhightower @bprashanth @roberthbailey

**Comment by bgrant0607** [comment]
Thanks, @jimmidyson.

Generally it's a good idea to start with a proposal.

Please see:
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/faster_reviews.md
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api_changes.md
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md

But before we do a detailed review and we both do more work on this, we need to decide whether/when we might want this. We need to be careful about growing our API surface further.

Don't spend time changing it yet, but FYI, we don't add new APIs to v1. It would be added to extensions/v1beta1.

In addition to #12732, also related: #11725, #16987, #8866

**Comment by bgrant0607** [comment]
Sort of related: #5754

**Comment by thockin** [comment]
Jimmi,

I know we talked about it and I was generally in favor of the idea, but I need a refresher on the idea.  Can you write up a short proposal/design doc?

**Pull request closed without merging**
