### PR TITLE
Fix  some typos

### PR DESCRIPTION
**Pull request by riverzhang**
**Release note**:

```release-note
```

### CODE REVIEW

**Comment by dashpole** [comment]
@k8s-bot ok to test

**Comment by riverzhang** [comment]
I signed it!

**Comment by riverzhang** [comment]
@k8s-bot unit test this

**Comment by riverzhang** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by riverzhang** [comment]
@dchen1107

**Comment by riverzhang** [comment]
@yujuhong

**Pull request merged**
