### PR TITLE
Label Windows test as Serial.

### LINKED ISSUE #89134: [Failing Test] aks-engine-azure-1-18-windows (ci-kubernetes-e2e-aks-engine-azure-1-18-windows )
**Which jobs are failing**:
`aks-engine-azure-1-18-windows (ci-kubernetes-e2e-aks-engine-azure-1-18-windows )`

**Which test(s) are failing**:
`[sig-windows] [Feature:Windows] Cpu Resources Container limits should not be exceeded after waiting 2 minutes`

**Since when has it been failing**:
`14th March 14:14 PDT`

**Testgrid link**:
https://testgrid.k8s.io/sig-release-1.18-informing#aks-engine-azure-1-18-windows

**Reason for failure**:
```console
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/windows/cpu_limits.go:41
Mar 15 14:12:07.063: Error grabbing node summary stats
Unexpected error:
    <*errors.StatusError | 0xc00227c320>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "an error on the server (\"Internal Error: failed to list pod stats: failed to list all container stats: rpc error: code = Unknown desc = hcsshim::OpenComputeSystem 0353fe37881a435485cc7014f9bad28ce64beb6fdfc5545ad7ada48e9878c9f9: A virtual machine or container with the specified identifier does not exist.\") has prevented the request from succeeding (get nodes 2813k8s010:10250)",
            Reason: "InternalError",
            Details: {
                Name: "2813k8s010:10250",
                Group: "",
                Kind: "nodes",
                UID: "",
                Causes: [
                    {
                        Type: "UnexpectedServerResponse",
                        Message: "Internal Error: failed to list pod stats: failed to list all container stats: rpc error: code = Unknown desc = hcsshim::OpenComputeSystem 0353fe37881a435485cc7014f9bad28ce64beb6fdfc5545ad7ada48e9878c9f9: A virtual machine or container with the specified identifier does not exist.",
                        Field: "",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 500,
        },
    }
    an error on the server ("Internal Error: failed to list pod stats: failed to list all container stats: rpc error: code = Unknown desc = hcsshim::OpenComputeSystem 0353fe37881a435485cc7014f9bad28ce64beb6fdfc5545ad7ada48e9878c9f9: A virtual machine or container with the specified identifier does not exist.") has prevented the request from succeeding (get nodes 2813k8s010:10250)
occurred
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/windows/cpu_limits.go:74

```

**Anything else we need to know**:
/sig windows
/cc @kubernetes/ci-signal 
/priority critical-urgent
/milestone v1.18

### PR DESCRIPTION
**Pull request by adelina-t**
Windows test "[sig-windows] [Feature:Windows] Cpu Resources Container
limits should not be exceeded after waiting 2 minutes" should be run
serially to prevent flakyness.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
/kind failing-test

Fixes #89134

**Special notes for your reviewer**:

Needs backport to 1.18

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by marosset** [comment]
/assign @benmoss @michmike 
Can you one of take a look and approve?

**Review by michmike — APPROVED** [review]

**Pull request merged**
