### PR TITLE
Add some test case in default_test.go

### PR DESCRIPTION
**Pull request by wackxu**
**What this PR does / why we need it**:

Add some test case in default_test.go

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by resouer** [comment]
pull-kubernetes-federation-e2e-gce is flaky

**Comment by resouer** [comment]
@wackxu Thanks!  

Before start interview, I would like to see some measurement for the test coverage improvement. Could you please post a result of `coverprofile` with & without your PR for the tested file?

e.g.
```
go get golang.org/x/tools/cmd/cover
go test -coverprofile <filename> <package name>
```

**Comment by wackxu** [comment]
@resouer Thanks for your look at this PR. The test coverage is as bellow.

Before:
```
coverage: 95.8% of statements
ok  	k8s.io/kubernetes/plugin/pkg/scheduler/algorithmprovider/defaults	0.089s
```
After:
```
coverage: 100.0% of statements
ok  	k8s.io/kubernetes/plugin/pkg/scheduler/algorithmprovider/defaults	0.079s
```
I look at the code again.The reason why there is a high coverage before I add the test case is that there is a init() func that will call these code but not do some verify.

**Review by resouer — APPROVED** [review]
/lgtm

**Pull request merged**
