### PR TITLE
cache: return watchHandler errors from reflectors

### PR DESCRIPTION
**Pull request by 0xmichalis**
Fixes https://github.com/kubernetes/kubernetes/issues/26065

@xiang90 @wojtek-t PTAL

### CODE REVIEW

**Comment by kargakis** [comment]
cc: @piosz

**Comment by wojtek-t** [comment]
It should already be fixed by #26059

**Comment by kargakis** [comment]
@wojtek-t shouldn't we return the errors from ListAndWatch? It seems that reflectors are just logging them at the moment.

**Comment by wojtek-t** [comment]
@kargakis - I think it depends on the error. If this is an errors coming from storage and/or parsing what came from storage, then probably we should. If this is a user-error (which in this case it basically is), then I'm not that convinced, because we don't really want to force relists because of some user error.

**Comment by kargakis** [comment]
> @kargakis - I think it depends on the error. If this is an errors coming from storage and/or parsing what came from storage, then probably we should. If this is a user-error (which in this case it basically is), then I'm not that convinced, because we don't really want to force relists because of some user error.

Agreed, that's why we can have [different error handlers](https://github.com/kubernetes/kubernetes/blob/8f104a7b0f2298caaf5f8a4ab901855646172886/pkg/util/runtime/runtime.go#L63), right?

**Comment by wojtek-t** [comment]
>
Agreed, that's why we can have different error handlers, right?

To be honest, I'm not sure it usable in this particular usecase. And I'm super busy now. But if you think we can use it, I'm happy to review a PR (though, probably not this week).

**Pull request closed without merging**
