### PR TITLE
MESOS: Stop the kubelet from taking control over cgroups and other processes

### PR DESCRIPTION
**Pull request by sttts**
The kubelet tries to move different system processes into its own cgroup hierarchy for resource accounting and measurement. This patch sets all those container name to `""` which stops this behaviour.

In the Mesos world the cgroup of the executor is set by the slave and should be inherited (possibly as a sub-cgroup) by the kubelet. But in any case the kubelet _must not do cgroup management for system processes_ like the docker daemon.

### CODE REVIEW

**Comment by sttts** [comment]
/cc @jdef for further discussion.

The relevant code path in the kubelet can be found here: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container_manager_linux.go#L83

**Comment by jdef** [comment]
I'm OK with these defaults. If a parent cgroup is specified, it might be worth experimenting with `ResourceContainer = mesosCgroup+"/kubelet"` -- to better isolate kubelet resources from the pod containers. I wonder if such an approach would bring us at least 1 (partial?) step closer to passing conformance (if we could adjust also the conformance test's reliance upon the literal "/kubelet" container -- in a separate PR).

**Comment by sttts** [comment]
If I read the kubelet code correctly, `ResourceContainer = mesosCgroup+"/kubelet"` actually has no effect other than kubelet being in its own Cgroup: there is no `ensureStateFunc` set for the kubelet container.

**Comment by jdef** [comment]
LGTM.

can you tell if this helps the kubelet/cadvisor w/ its resource accounting?

**Pull request merged**
