### PR TITLE
Automated cherry pick of #73239: Add back --cert-dir option for init phase certs sa

### PR DESCRIPTION
**Pull request by mattkelly**
Cherry pick of #73239 on release-1.13.

#73239: Add back --cert-dir option for init phase certs sa

### CODE REVIEW

**Comment by mattkelly** [comment]
/assign @neolit123 
/assign @rosti 
/assign @yagonobre 

Just assigning original reviewers.

**Review by neolit123 — COMMENTED** [review]
@mattkelly 
so we usually don't cherry pick fixes unless they are `critical-urgent`.
that said, this is a regression fix that adds a missing flag and does not remove one, also i don't see how this can break upgrades, so i'm +1 for cherry pick.

but i will leave the decision to Fabrizio and Tim on this one.
/assign @fabriziopandini @timothysc

**Comment by mattkelly** [comment]
Thanks @neolit123, I should have done more research/communication before opening this, as I was unaware that that was the exact requirement.

That said, I do strongly feel that this should be merged (though I am obviously biased 😉), as it is a clear regression in usage for which the fix is trivial.

What do you think, @fabriziopandini @timothysc?

**Review by rosti — APPROVED** [review]
Thanks @mattkelly !
Given the fact, that we could use this option in the past, then I count this as a regression and therefore worthy of cherry-picking.
However @timothysc @fabriziopandini @tpepper will need to have the final call on this.
/lgtm
/kind bug
/ok-to-test
/assign @tpepper

**Comment by fabriziopandini** [comment]
I agree this is a regression introduced when graduating phases. On top of that the change is minimal and well scoped, so 
/approve
/lgtm

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Comment by timothysc** [comment]
poke @kubernetes/sig-release

**Comment by justaugustus** [comment]
1.13 PRMT:
/assign @tpepper @aleksandra-malinowska

**Pull request merged**
