### PR TITLE
Add OWNERS file for gce/manifests

### PR DESCRIPTION
**Pull request by MrHohn**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Adding an OWNERS file (that includes myself) to gce/manifest so I can help reviewing/approving changes like https://github.com/kubernetes/kubernetes/pull/77282.

**Which issue(s) this PR fixes**:

Fixes #NONE 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yujuhong** [comment]
Looks good but I think it's good to have more than one approve if possible. 
@tallclair would you like to be an owner?

**Comment by MrHohn** [comment]
Added @tallclair as an OWNER as that makes total sense :)

To keep this rolling
/assign @tallclair

**Comment by yujuhong** [comment]
/approve

Leaving lgtm to @tallclair

**Comment by tallclair** [comment]
/lgtm
Thanks!

**Pull request merged**
