### PR TITLE
The custom metrics client should expect a MetricValue instead of a MetricValueList in single-value contexts

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:

Currenly, the hpa v2 fails with these errors when trying to autoscale a resource:
```
W0318 20:28:31.201134       1 horizontal.go:126] Failed to reconcile my-hpa: failed to compute desired number of replicas based on listed metrics for Deployment/default/my-nginx: failed to get object metric value: unable to get metric connections-per-seconds: Service on default my-nginx/unable to fetch metrics from API: the custom metrics API server returned %!v(MISSING) results when we asked for exactly one
W0318 20:29:01.183890       1 horizontal.go:126] Failed to reconcile my-hpa: failed to compute desired number of replicas based on listed metrics for Deployment/default/my-nginx: failed to get object metric value: unable to get metric connections-per-seconds: Service on default my-nginx/unable to fetch metrics from API: the custom metrics API server returned %!v(MISSING) results when we asked for exactly one
W0318 20:29:31.183609       1 horizontal.go:126] Failed to reconcile my-hpa: failed to compute desired number of replicas based on listed metrics for Deployment/default/my-nginx: failed to get object metric value: unable to get metric connections-per-seconds: Service on default my-nginx/unable to fetch metrics from API: the custom metrics API server returned %!v(MISSING) results when we asked for exactly one
W0318 20:30:01.184192       1 horizontal.go:126] Failed to reconcile my-hpa: failed to compute desired number of replicas based on listed metrics for Deployment/default/my-nginx: failed to get object metric value: unable to get metric connections-per-seconds: Service on default my-nginx/unable to fetch metrics from API: the custom metrics API server returned %!v(MISSING) results when we asked for exactly one
W0318 20:30:31.185585       1 horizontal.go:126] Failed to reconcile my-hpa: failed to compute desired number of replicas based on listed metrics for Deployment/default/my-nginx: failed to get object metric value: unable to get metric connections-per-seconds: Service on default my-nginx/unable to fetch metrics from API: the custom metrics API server returned %!v(MISSING) results when we asked for exactly one
```

The resource it's requesting is this one:
```
curl -k https://10.96.42.64/apis/custom-metrics.metrics.k8s.io/v1alpha1/namespaces/default/services/my-nginx/connections-per-second
{
  "kind": "MetricValue",
  "apiVersion": "custom-metrics.metrics.k8s.io/v1alpha1",
  "describedObject": {
    "kind": "Service",
    "namespace": "default",
    "name": "my-nginx",
    "apiVersion": "/__internal"
  },
  "metricName": "connections-per-second",
  "timestamp": "2017-03-18T20:31:45Z",
  "value": "600m"
}
```

and the HPA looks like this:
```yaml
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2alpha1
metadata:
  name: my-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: my-nginx
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      target:
        kind: Service
        name: my-nginx
      metricName: connections-per-seconds
      targetValue: 10
```

The custom metrics server is a variant of: https://github.com/DirectXMan12/custom-metrics-boilerplate which returns a `MetricValue` on single-value queries instead of a `MetricValueList` with one object.

If I understood the proposal correctly, the right behavior here is to return only one object (a MetricValue). This can be compared to getting a Pod:
```
$ curl https://10.132.0.2:6443/api/v1/namespaces/default/pods/my-nginx-858393261-1p983
{"kind":"Pod","apiVersion":"v1","metadata":{"name":"my-nginx-858393261-1p983","generateName":"my-nginx-858393261-","namespace":"default","selfLink":"/api/v1/namespaces/default/pods/my-nginx-858393261-1p983","uid":"f817323e-0c18-11e7-8776-42010a840002","resourceVersion":"560594","creationTimestamp":"2017-03-18T20:25:03Z","labels":{"pod-template-hash":"858393261","run":"my-nginx"},"annotations":{"kubernetes.io/created-by":"{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicaSet\",\"namespace\":\"default\",\"name\":\"my-nginx-858393261\",\"uid\":\"93edc052-0c18-11e7-8776-42010a840002\",\"apiVersion\":\"extensions\",\"resourceVersion\":\"5568\"}}\n"},"ownerReferences":[{"apiVersion":"extensions/v1beta1","kind":"ReplicaSet","name":"my-nginx-858393261","uid":"93edc052-0c18-11e7-8776-42010a840002","controller":true,"blockOwnerDeletion":true}]},"spec":{"volumes":[{"name":"default-token-r1wtp","secret":{"secretName":"default-token-r1wtp","defaultMode":420}}],"containers":[{"name":"my-nginx","image":"nginx","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"volumeMounts":[{"name":"default-token-r1wtp","readOnly":true,"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","serviceAccountName":"default","serviceAccount":"default","nodeName":"rook-test","securityContext":{},"schedulerName":"default-scheduler","tolerations":[{"key":"node.alpha.kubernetes.io/notReady","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"node.alpha.kubernetes.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}]},"status":{"phase":"Running","conditions":[{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2017-03-18T20:25:03Z"},{"type":"Ready","status":"True","lastProbeTime":null,"lastTransitionTime":"2017-03-18T20:25:06Z"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2017-03-18T20:25:03Z"}],"hostIP":"10.132.0.2","podIP":"10.32.0.24","startTime":"2017-03-18T20:25:03Z","containerStatuses":[{"name":"my-nginx","state":{"running":{"startedAt":"2017-03-18T20:25:05Z"}},"lastState":{},"ready":true,"restartCount":0,"image":"nginx:latest","imageID":"docker-pullable://nginx@sha256:52a189e49c0c797cfc5cbfe578c68c225d160fb13a42954144b29af3fe4fe335","containerID":"docker://0b5d235ad9e0b95ad479a085ae7101017c8e056d4395c65ae43cff06d6ca6726"}],"qosClass":"BestEffort"}}
```

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

If this is the right and intended approach, it should be merged as a bug fix into the v1.6 release
@DirectXMan12 @piosz @deads2k

### CODE REVIEW

**Comment by luxas** [comment]
Just noticed that the metrics repo isn't under staging which I thought, so sent a similar PR to the real metrics repo, will bump godep here after that's merged.
ref: https://github.com/kubernetes/metrics/pull/3

**Comment by DirectXMan12** [comment]
> If I understood the proposal correctly, the right behavior here is to return only one object (a MetricValue). This can be compared to getting a Pod:

This is actually a quirk of the way Kubernetes APIs work -- since we have to use GET for both single-object and label selector operations, that endpoint must always return a list type.

Note the proposal (https://github.com/kubernetes/community/blob/master/contributors/design-proposals/custom-metrics-api.md#api-objects)

> The request URLs listed above will return the MetricValueList type described below (when a name is given that is not *, the API should simply return a list with a single element):

**Comment by enisoc** [comment]
Should this block v1.6.0, or can it wait for v1.6.1? If it's a release-blocker, when do you expect a fix?

**Comment by enisoc** [comment]
I'm removing the v1.6 milestone since we are lifting code freeze soon and it doesn't seem like we need to hold the branch cut for this. Please follow the [cherrypick procedure](https://github.com/kubernetes/community/blob/master/contributors/devel/cherry-picks.md) if you still think this should go into the release-1.6 branch.

**Comment by luxas** [comment]
@enisoc This was not a release blocker, thanks for moving it out.

However, seems like we'll solve this in other ways

**Pull request closed without merging**
