### PR TITLE
promote ProxyTerminatingEndpoints to GA

### PR DESCRIPTION
**Pull request by aojea**
/kind feature

```release-note
kube-proxy handles Terminating EndpointSlices conditions and enables zero downtime deployments for Services with ExternalTrafficPolicy=Local author: @andrewsykim 
```

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/1669
- [Usage]: https://kubernetes.io/blog/2022/12/30/advancements-in-kubernetes-traffic-engineering/
- [Example1]: https://gist.github.com/aojea/84fc66fde269f8aef1a4932d074285db
- [Example2]: https://gist.github.com/aojea/cd72e17b7238114a35cb9c82bf2324cb
```

There are also e2e test with loadbalancers and deployments performing rolling updates

https://testgrid.k8s.io/google-gce#gci-gce-ingress&include-filter-by-regex=should%20not%20have%20connectivity%20disruption%20during%20rolling%20update%20with%20externalTrafficPolicy

### CODE REVIEW

**Comment by aojea** [comment]
/assign @thockin @andrewsykim 

The next step is to promote some test to conformance, but it has to demonstrate they are stable for more than 1 week

**Comment by aojea** [comment]
unrelated

> TestFormat

/test pull-kubernetes-unit

run it again

/test pull-kubernetes-e2e-gce

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by aojea** [comment]
> : [It] [sig-network] LoadBalancers should be able to preserve UDP traffic when server pod cycles for a LoadBalancer service on the same nodes

unrelated, but why is this test running here?
/test pull-kubernetes-e2e-gce

**Comment by BenTheElder** [comment]
Is this related to #117824 ?

**Comment by aojea** [comment]
> Is this related to #117824 ?

it just removed the feature tag from the test name so the test started to be exercised on all jobs

**Pull request merged**
