### PR TITLE
WIP: Experiment with in-memory storage backend, for testability

### PR DESCRIPTION
**Pull request by justinsb**
WIP

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36315)

### CODE REVIEW

**Comment by roberthbailey** [comment]
@kubernetes/sig-api-machinery @wojtek-t

**Comment by smarterclayton** [comment]
Why isn't the in memory etcd server enough?  I know there were some bugs there that made it slower than it needed to be, but seems simpler.

Also, why this over the fake storage client (or did we remove that)?

**Comment by justinsb** [comment]
@smarterclayton this is more fun

**Comment by smarterclayton** [comment]
Ok.

**Pull request closed without merging**
