### PR TITLE
split of test-cmd

### PR DESCRIPTION
**Pull request by deads2k**
This pull moves test-cmd to a `test/cmd` folder for team maintenance.  The next commit splits the mega (6 thousand lines or so?) into files based on function.  No changes, just moves.

@kubernetes/sig-cli-maintainers 
@fejta per request

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
If this starts to conflict, I'm going to pull that second commit so we still get the team maintenance aspects.

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by soltysh** [comment]
I'm bumping the priority on this one, since this has a potential of conflicts, but is very useful in the long run.

**Comment by deads2k** [comment]
got bazel happy. retagging.

**Pull request merged**
