### PR TITLE
Automated cherry pick of #17973

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #17973 on release-1.0.

### CODE REVIEW

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by liggitt** [comment]
@k8s-bot test this

**Comment by liggitt** [comment]
@k8s-bot test this

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by gmarek** [comment]
It looks like a second flake to me - reruning tests.
@k8s-bot test this

**Comment by gmarek** [comment]
@liggitt - tests are reliably failing, can you investigate? It still looks unrelated to me...

```
	Test Result (4 failures / +4)
Kubernetes e2e suite.Services should be able to change the type and nodeport settings of a service
Kubernetes e2e suite.Pod Disks should schedule a pod w/ a RW PD shared between multiple containers, write to PD, delete pod, verify contents, and repeat in rapid succession
Kubernetes e2e suite.Probing container with readiness probe that fails should never be ready and never restart
Kubernetes e2e suite.Pods should *not* be restarted with a docker exec "cat /tmp/health" liveness probe
```

```
01:02:43 • Failure [120.572 seconds]
01:02:43 Pod Disks
01:02:43 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:232
01:02:43   should schedule a pod w/ a RW PD shared between multiple containers, write to PD, delete pod, verify contents, and repeat in rapid succession [It]
01:02:43   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:231
01:02:43 
01:02:43   Expected error:
01:02:43       <*exec.ExitError | 0xc20802eab8>: {
01:02:43           ProcessState: {
01:02:43               pid: 15633,
01:02:43               status: 256,
01:02:43               rusage: {
01:02:43                   Utime: {Sec: 0, Usec: 684000},
01:02:43                   Stime: {Sec: 0, Usec: 88000},
01:02:43                   Maxrss: 17604,
01:02:43                   Ixrss: 0,
01:02:43                   Idrss: 0,
01:02:43                   Isrss: 0,
01:02:43                   Minflt: 1532,
01:02:43                   Majflt: 0,
01:02:43                   Nswap: 0,
01:02:43                   Inblock: 0,
01:02:43                   Oublock: 0,
01:02:43                   Msgsnd: 0,
01:02:43                   Msgrcv: 0,
01:02:43                   Nsignals: 0,
01:02:43                   Nvcsw: 6330,
01:02:43                   Nivcsw: 519,
01:02:43               },
01:02:43           },
01:02:43       }
01:02:43       exit status 1
01:02:43   not to have occurred
```

```
01:04:14 • Failure in Spec Setup (BeforeEach) [10.234 seconds]
01:04:14 Pods
01:04:14 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:695
01:04:14   should *not* be restarted with a docker exec "cat /tmp/health" liveness probe [BeforeEach]
01:04:14   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:493
01:04:14 
01:04:14   Expected error:
01:04:14       <*url.Error | 0xc208266510>: {
01:04:14           Op: "Get",
01:04:14           URL: "https://104.197.45.201/api/v1/namespaces/e2e-tests-pods-6f8dc/serviceaccounts/default",
01:04:14           Err: {
01:04:14               Op: "dial",
01:04:14               Net: "tcp",
01:04:14               Addr: {
01:04:14                   IP: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xffh\xc5-\xc9",
01:04:14                   Port: 443,
01:04:14                   Zone: "",
01:04:14               },
01:04:14               Err: 0x6f,
01:04:14           },
01:04:14       }
01:04:14       Get https://104.197.45.201/api/v1/namespaces/e2e-tests-pods-6f8dc/serviceaccounts/default: dial tcp 104.197.45.201:443: connection refused
01:04:14   not to have occurred
```

```
01:04:16 • Failure [50.246 seconds]
01:04:16 Probing container
01:04:16 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:101
01:04:16   with readiness probe that fails should never be ready and never restart [It]
01:04:16   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:99
01:04:16 
01:04:16   expecting wait timeout error but got: Get https://104.197.45.201/api/v1/namespaces/e2e-tests-container-probe-xzfu6/pods/test-webserver-bcaa4182-999c-11e5-be1d-42010af00003: dial tcp 104.197.45.201:443: connection refused
```

```
01:08:54 • Failure [450.241 seconds]
01:08:54 Services
01:08:54 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:808
01:08:54   should be able to change the type and nodeport settings of a service [It]
01:08:54   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:503
01:08:54 
01:08:54   Error waiting for the url http://104.197.128.118:80 to be reachable
01:08:54   Expected error:
01:08:54       <*errors.errorString | 0xc208120360>: {
01:08:54           s: "timed out waiting for the condition",
01:08:54       }
01:08:54       timed out waiting for the condition
01:08:54   not to have occurred
01:08:54 
01:08:54   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1069
```

**Comment by liggitt** [comment]
with no changes on my side, failures have ranged from 2-6, most with non-overlapping failures:

https://github.com/kubernetes/kubernetes/pull/17984#issuecomment-160776937
```
Summarizing 5 Failures:

[Fail] Services [It] should serve multiport endpoints from pods 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:957

[Fail] Services [It] should serve a basic endpoint from pods 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:957

[Fail] Networking [It] should provide Internet connection for containers 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/networking.go:80

[Fail] Pods [It] should *not* be restarted with a docker exec "cat /tmp/health" liveness probe 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:69

[Fail] Services [BeforeEach] should be able to create a functioning NodePort service 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:55
```

https://github.com/kubernetes/kubernetes/pull/17984#issuecomment-160803049
```
Summarizing 2 Failures:

[Fail] Pods [It] should *not* be restarted with a docker exec "cat /tmp/health" liveness probe 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:69

[Fail] Pod Disks [AfterEach] should schedule a pod w/ a readonly PD on two hosts, then remove both. 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:93
```

https://github.com/kubernetes/kubernetes/pull/17984#issuecomment-160921771
```
Summarizing 2 Failures:

[Fail] Pod Disks [AfterEach] should schedule a pod w/ a readonly PD on two hosts, then remove both. 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:93

[Fail] Pods [It] should *not* be restarted with a docker exec "cat /tmp/health" liveness probe 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:69
```

https://github.com/kubernetes/kubernetes/pull/17984#issuecomment-161047630
```
Summarizing 6 Failures:

[Fail] Pods [It] should be restarted with a docker exec "cat /tmp/health" liveness probe 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:69

[Fail] Pods [It] should *not* be restarted with a docker exec "cat /tmp/health" liveness probe 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:69

[Panic!] Kubectl client [BeforeEach] Kubectl label should update the label on a resource 
/usr/src/go/src/runtime/panic.go:387

[Fail] Probing container [It] with readiness probe that fails should never be ready and never restart 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:88

[Fail] Services [It] should be able to change the type and nodeport settings of a service 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:346

[Fail] Pod Disks [AfterEach] should schedule a pod w/ a RW PD, remove it, then schedule it on another host 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:93
```

https://github.com/kubernetes/kubernetes/pull/17984#issuecomment-161553384
```
Summarizing 2 Failures:

[Fail] Pods [It] should *not* be restarted with a docker exec "cat /tmp/health" liveness probe 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:69

[Fail] hostDir [It] should give a volume the correct mode 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/util.go:903
```

https://github.com/kubernetes/kubernetes/pull/17984#issuecomment-161559369
```
Summarizing 4 Failures:

[Fail] Pod Disks [It] should schedule a pod w/ a RW PD shared between multiple containers, write to PD, delete pod, verify contents, and repeat in rapid succession 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:253

[Fail] Pods [BeforeEach] should *not* be restarted with a docker exec "cat /tmp/health" liveness probe 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework.go:66

[Fail] Probing container [It] with readiness probe that fails should never be ready and never restart 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/container_probe.go:88

[Fail] Services [It] should be able to change the type and nodeport settings of a service 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1069
```

the same change passes fine in master and 1.1. not sure what to do with this.

**Comment by liggitt** [comment]
@fabianofranz is seeing similar inconsistent non-overlapping flakes on his release-1.0 pull https://github.com/kubernetes/kubernetes/pull/17954

**Comment by liggitt** [comment]
@k8s-bot test this

**Comment by liggitt** [comment]
aaaaaaand got a clean run :-) :-/

**Comment by liggitt** [comment]
@brendandburns clean test runs against release-1.0 branch, which is showing flaky e2e tests... I would recommend merging this

**Comment by brendandburns** [comment]
manual merge...

lifespan of maintaining the 1.0 branch is diminishing anyway...

**Pull request merged**
