### PR TITLE
Fix the EventSink in HPA controller

### LINKED ISSUE #21763: HPA in unable to write an event
```
W0223 12:36:00.484745       6 horizontal.go:300] Failed to reconcile aaa: failed to compute desired number of replicas based on CPU utilization for ReplicationController/default/aaa: failed to get cpu utilization: failed to get CPU consumption and request: metrics obtained for 0/1 of pods
E0223 12:36:00.484956       6 event.go:202] Unable to write event: 'an empty namespace may not be set during creation' (may retry after sleeping)
E0223 12:36:07.826586       6 event.go:202] Unable to write event: 'an empty namespace may not be set during creation' (may retry after sleeping)
...
E0223 12:37:37.829904       6 event.go:202] Unable to write event: 'an empty namespace may not be set during creation' (may retry after sleeping)
E0223 12:37:47.830297       6 event.go:202] Unable to write event: 'an empty namespace may not be set during creation' (may retry after sleeping)
E0223 12:37:47.830345       6 event.go:136] Unable to write event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"aaa.14359257d69de0a0", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"HorizontalPodAutoscaler", Namespace:"default", Name:"aaa", UID:"f1517844-da29-11e5-b948-42010af00003", APIVersion:"extensions", ResourceVersion:"392", FieldPath:""}, Reason:"FailedGetMetrics", Message:"failed to get CPU consumption and request: metrics obtained for 0/1 of pods", Source:api.EventSource{Component:"horizontal-pod-autoscaler", Host:""}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63591827760, nsec:484704416, loc:(*time.Location)(0x2636ce0)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63591827760, nsec:484704416, loc:(*time.Location)(0x2636ce0)}}, Count:1, Type:"Warning"}' (retry limit exceeded!)
```

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #21763.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@piosz could you double check if this fixes the issue? I don't know how to reproduce the problem you reported.

**Comment by piosz** [comment]
LGTM
Thanks for the fix! I'll check today.

**Comment by piosz** [comment]
I can confirm that this fixed the problem.

**Comment by caesarxuchao** [comment]
Thanks @piosz for the confirmation :)

**Comment by caesarxuchao** [comment]
Manually merging.

**Pull request merged**
