### PR TITLE
Rename a few API types (non-breaking change)

### PR DESCRIPTION
**Pull request by thockin**
Rename a few API types that had the word "Type" in their name but were not very good names.

This should have no user-impact.

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM, but I think you're going to need to rebase and regenerate the swagger, since it just got updated.

**Comment by thockin** [comment]
Docs seem to be good, am I missing something?  I rebased this morning.

```
$ ./hack/verify-gendocs.sh
+++ [0518 16:43:18] Building go targets for linux/amd64:
    cmd/gendocs
    cmd/genman
    cmd/genbashcomp
+++ [0518 16:43:25] Placing binaries
diffing /usr/local/google/home/thockin/src/kubernetes/docs/ against freshly
generated docs
/usr/local/google/home/thockin/src/kubernetes/docs/ up to date.
/usr/local/google/home/thockin/src/kubernetes/contrib/completions up to
date.
```

**Comment by bgrant0607** [comment]
Swagger is generated by hack/update-swagger-spec.sh, not gendocs.sh.

**Comment by thockin** [comment]
Ahh.  Done in an additional commit.

**Comment by bgrant0607** [comment]
Thanks. LGTM. Shippable passed.

**Pull request merged**
