### PR TITLE
replace strings.Index  with strings.Contains 

### PR DESCRIPTION
**Pull request by mingregister**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
In the current code, it use `strings.Index(action.Path, "/{name}") != -1` to present `action.Path Contains "/{name}"`, it would be more easy to understanding when use `strings.Contains(action.Path, "/{name}")`.

So I replace the `strings.Index(action.Path, "/{name}") != -1` with `strings.Contains(action.Path, "/{name}")`

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by AxeZhan** [comment]
Please fill the description. We can't ignore that even if the pr is easy :)

**Comment by hzxuzhonghu** [comment]
I donot see much diff, anyone lgtm

**Comment by mingregister** [comment]
> Please fill the kind and release note in description. We can't ignore them even if the pr is easy :)

Done

**Comment by charles-chenzz** [comment]
> I donot see much diff, anyone lgtm

+1, I think it's same

**Comment by mingregister** [comment]
@hzxuzhonghu @jpbetz Sorry to bother you.  If possible, could you please take a look at my pull request and provide your feedback? Your suggestions and any improvements you can suggest will be highly appreciated.

**Comment by jpbetz** [comment]
/lgtm
/approve

The bots won't merge unless the release note section of the description is added back (set it to "NONE" for a noop PR like this).

There are a bunch of similar uses of `strings.Index` in the codebase.  If you're planning to fix any other usages, please do so in batches (>1 per PR). Thanks!

**Comment by mingregister** [comment]
> /lgtm /approve
> 
> The bots won't merge unless the release note section of the description is added back (set it to "NONE" for a noop PR like this).
> 
> There are a bunch of similar uses of `strings.Index` in the codebase. If you're planning to fix any other usages, please do so in batches (>1 per PR). Thanks!

ok, thank you for taking the time to review this and provide valuable suggestions.

**Pull request merged**
