### PR TITLE
Validate-cluster finishes shortly after at most ALLOWED_NOTREADY_NODE…

### LINKED ISSUE #26691: Don't wait for more nodes when 99% of the cluster is up.
Currently we assume that the cluster is healthy if 99% of Nodes are. We keep on waiting for more nodes even after 99% are up, until all Nodes are ready or we reach the timeout, even though we know that the cluster will be considered healthy.

The question is shouldn't we finish validation when 99% of the cluster is up. This will increase the possibility that some additional Nodes will join the cluster after it started, but I'm not sure that's bad.

My proposal is to do it, i.e. validate cluster should wait only for first 99% of the cluster.

@smarterclayton @lavalamp @wojtek-t @zmerlynn @davidopp

### PR DESCRIPTION
**Pull request by gmarek**
Fixes #26691

cc @wojtek-t @lavalamp

### CODE REVIEW

**Comment by gmarek** [comment]
Ping @zmerlynn

**Comment by zmerlynn** [comment]
@gmarek: Ack, sorry. :(

**Comment by gmarek** [comment]
@k8s-bot unit test this issue: #25940

**Comment by goltermann** [comment]
@k8s-bot e2e test this issue: #IGNORE

**Pull request merged**
