### PR TITLE
Minor kubeadm housekeeping

### PR DESCRIPTION
**Pull request by timothysc**
**What this PR does / why we need it**:
- Cleans out old v1alpha1 directory
- add neolit123 to kubeadm reviewer

**Release note**:

```
NONE
```

/assign @fabriziopandini @neolit123

### CODE REVIEW

**Comment by neolit123** [comment]
> add neolit123 to kubeadm reviewer

thanks. i knew i had to submit a PR and explain the list of changes and reviews that i have done.

LGTM
/test pull-kubernetes-e2e-kops-aws

**Comment by neolit123** [comment]
@timothysc 
`cmd/kubeadm/app/apis/kubeadm/BUILD` seems to be conflicting.

**Review by fabriziopandini — APPROVED** [review]
+100 for adding @neolit123 to reviewers

v1alpha1 beta folder was removed by #69055 :wink: 
/approve

**Comment by timothysc** [comment]
Other PRs merged before this one, closing.

**Pull request closed without merging**
