### PR TITLE
Bump CoreDNS version to 1.5.0 and update manifest

### LINKED ISSUE #78003: Upgrade coredns to v1.4.0 or v1.5.0
**What would you like to be added**:
A newer version of coredns

**Why is this needed**:
Currently shipped v1.3.1 is affected by https://github.com/coredns/coredns/issues/2629 issue, which causes the cluster outage if API server goes away temporarily.

### PR DESCRIPTION
**Pull request by rajansandeep**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
Updates the version of CoreDNS to 1.5.0 and also updates the manifests.

**Which issue(s) this PR fixes**:

Fixes #78003 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
CoreDNS is now version 1.5.0
    - A `ready` plugin has been included to report pod readiness
    - The `proxy` plugin has been deprecated. The `forward` plugin is to be used instead.
    - CoreDNS fixes the logging now that kubernetes’ client lib switched to klog from glog.
```

### CODE REVIEW

**Review by chrisohaver — APPROVED** [review]

**Review by neolit123 — COMMENTED** [review]
thanks @rajansandeep 
/approve
cc @kubernetes/sig-cluster-lifecycle-pr-reviews

**Review by MrHohn — APPROVED** [review]
/lgtm
/approve

**Comment by neolit123** [comment]
@rajansandeep 
looks like the bump broke kubeadm upgrade e2e:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-stable-master
https://github.com/kubernetes/kubernetes/compare/72f69546142a84...a67f128f5ee706

i will have a look, but we might have to revert if there is no apparent solution
cc @fabriziopandini

**Comment by neolit123** [comment]
creating a cluster from the master k/k branch works fine with the new coredns version.
however, creating an older k/k version cluster and upgrading it to master causes the coredns pods to not ready-up.

nothing apparent in the container logs:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-stable-master/1129638974428549121/artifacts/kinder-upgrade-control-plane/containers/coredns-fb8b8dccf-v9qj7_kube-system_coredns-2b0e095354f65aab8941d4a50b23ec24e86ec441395edeae5a7a318ac948c4bf.log
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-stable-master/1129638974428549121/artifacts/kinder-upgrade-control-plane/containers/

**Comment by rajansandeep** [comment]
@neolit123 I believe this is due to the CoreDNS ConfigMap retained during upgrade and the ‘ready’ plugin not included in the upgraded version. This causes the coredns pods to report as not-ready. 

This is one of the reasons why #78033 is important.

**Comment by neolit123** [comment]
ok, understood
it would have been better to get #78033 in first to have the migrate logic in place before the version bump.

**Comment by chrisohaver** [comment]
Can the failing upgrade tests be run ad-hoc in a PR?

**Comment by neolit123** [comment]
No. Not on a pr remotelly but locally yes using the tool kinder. However i think the failure is reproducible with a regular 1.14 - master upgrade

**Pull request merged**
