### PR TITLE
Better scale max-inflight request limits to correlate them with master VM size

### PR DESCRIPTION
**Pull request by wojtek-t**
@MaciekPytel - FYI

```release-note
Scale max-inflight limits together with master VM sizes.
```

### CODE REVIEW

**Comment by MaciekPytel** [comment]
@wojtek-t Can we cherry-pick this? Preferable all the way to 1.11.

**Comment by wojtek-t** [comment]
Yes - we should, I will create cherrypicks.

**Comment by wojtek-t** [comment]
Cherrypicks are now opened.

**Pull request merged**
