### PR TITLE
Automated cherry pick of #97954: fixes nil panic for nil delegated auth options

### PR DESCRIPTION
**Pull request by yue9944882**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

ref: #97954

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
/hold until after tomorrow's patch release

**Comment by yue9944882** [comment]
@hasheddan not sure if i get the point, why not getting this in the next-coming release?

**Comment by tosi3k** [comment]
`pull-kubernetes-e2e-gce-100-performance` failed due to kubernetes/test-infra#20476 which is now fixed.

/retest

**Comment by hasheddan** [comment]
> @hasheddan not sure if i get the point, why not getting this in the next-coming release?

@yue9944882 cherry picks must be opened by the [cherry-pick deadline](https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#cherry-picks) to be included in a specific patch release. Patch releases are now out so we can move forward with this now and it will be included in the next patch 👍

**Pull request merged**
