### PR TITLE
Automated cherry pick of #114998: Throw error if OpenAPIV3 config is not provided

### PR DESCRIPTION
**Pull request by jwcesign**
Cherry pick of #114998 on release-1.27.

#114998: Throw error if OpenAPIV3 config is not provided

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fix SSA being silently disabled by lack of OpenAPI config
```

### CODE REVIEW

**Comment by jwcesign** [comment]
Hi @alexzielenski @deads2k @apelisse
I am doing this cherry-pick because I meet a problem when upgrading the dependency:
the API installation will fail if not init `openAPIV3Config` and `openAPIConfig` at the same time.  

the code [here](https://github.com/kubernetes/kubernetes/blob/6d31f4b31ba1294c4844ec94ea2f67c5f8bf42f4/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go#L962) should be:
```
pathsToIgnore := openapiutil.NewTrie(s.openAPIV3Config.IgnorePrefixes)
```

**Comment by jiahuif** [comment]
/assign @alexzielenski @deads2k @apelisse
Could you confirm this is a good candidate to backport? Thank you.
/triage accepted

**Comment by RainbowMango** [comment]
/close
In favor of https://github.com/kubernetes/kubernetes/pull/114998#issuecomment-1668361629.

**Pull request closed without merging**
