### PR TITLE
optimize dedupCurHistories func in DaemonSetsController

### PR DESCRIPTION
**Pull request by LastNight1997**
Signed-off-by: LastNight1997 <934104625@qq.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Optimize dedupCurHistories func in DaemonSetsController. Relabeling pods before dedup needn't in for loop.
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by LastNight1997** [comment]
@krmayankk PTAL

**Comment by pacoxu** [comment]
/remove-lifecycle rotten
/ok-to-test
/kind cleanup
for performance improvement
/cc @krmayankk @atiratree

**Pull request merged**
