### PR TITLE
Update generated deepcopy code

### LINKED ISSUE #49755: Method names are not correct in comments generated by deepcopy-gen
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**:
[pkg/apis/apps/zz_generated.deepcopy.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/zz_generated.deepcopy.go#L88-L96):
```go
// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, creating a new ControllerRevision.
func (x *ControllerRevision) DeepCopy() *ControllerRevision {
	if x == nil {
		return nil
	}
	out := new(ControllerRevision)
	x.DeepCopyInto(out)
	return out
}
```

The method name in comment does not match the real method name.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Regenerate these codes and update the dependency in vendor after kubernetes/gengo#69 merged.

### PR DESCRIPTION
**Pull request by supereagle**
**What this PR does / why we need it**:
In generated deepcopy code, the method names in comments do not match the real method names.

**Which issue this PR fixes**: fixes #49755

**Special notes for your reviewer**:
/assign @sttts @caesarxuchao 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
@supereagle have you fixed it manually? Would have expected a PR for https://github.com/kubernetes/gengo and a revendoring here.

**Comment by supereagle** [comment]
@sttts  These changes are generated by gengo. The kubernetes/gengo#69 for this has been merged, and the revendoring is in process.

As not sure how to regenerate these files, I write a script for that by referring to [kubernetes/gengo/examples/deepcopy-gen/Makefile](https://github.com/kubernetes/gengo/blob/master/examples/deepcopy-gen/Makefile). Do you know the correct method for that?

**Comment by sttts** [comment]
@supereagle not sure I can follow what you did for this PR. As the gengo PR is merged, you have to vendor it into kube again:

```
$ hack/godep-restore.sh
$ cd ../gengo; git fetch origin; git checkout origin/master; cd -
$ hack/godep-save.sh
```

Then check in the changes in vendor/ and Godeps/.

Then `make` will update the generated files. Commit these into a second commit.

**Comment by supereagle** [comment]
@sttts  Thanks for your help. Now all work has been finished. Could you help to review, thanks a lot.

/cc @caesarxuchao

**Comment by sttts** [comment]
@supereagle can you rename the vendoring commit to: `bump(k8s.io/gengo): <sha1>`?

**Comment by sttts** [comment]
@supereagle and please squash the other two commits.

**Comment by sttts** [comment]
@supereagle https://github.com/kubernetes/gengo/pull/66 just merged. Can you revendor with that one included?

**Comment by supereagle** [comment]
@sttts  OK, I will revendor for `k8s.io/gengo`. As kubernetes/gengo#66 will change all zz_generated.deepcopy.go files, I think I need to regenerate these files in this PR, is it right?

**Comment by sttts** [comment]
@supereagle yes, just do a `make WHAT=cmd/hyperkube`.

**Comment by supereagle** [comment]
@sttts  As all of these commits in this PR have to been changed, I think it will be better to close this PR, and recreate a new PR.

**Comment by sttts** [comment]
@supereagle no, no need to close. Just force push into that branch.

**Comment by supereagle** [comment]
@sttts Have finished the work, PTAL, thanks a lot.

**Comment by supereagle** [comment]
/assign @smarterclayton
for /approve

**Pull request merged**
