### PR TITLE
gce/util: $replica-pd --> $replica_pd

### LINKED ISSUE #32997: federation e2e tests failing consistently with gce/util.sh: line 1192: local: `replica-pd=jenkins-us-central1-b-master-pd': not a valid identifier
./hack/e2e-internal/.../cluster/gce/util.sh: line 1192: local: `replica-pd=jenkins-us-central1-b-master-pd': not a valid identifier

@colhom @madhusudancs FYI - this looks related to your recent work?  I don't see any obvious PR to blame, but I seem to remember you guys touching this part of the code recently?

BTW, I deleted a bunch of leaked resources in the relevant test project on Friday (9/16), assuming that the test scripts would re-create whatever they needed.  It's possible (but unlikely) that this has anything to do with that.

### PR DESCRIPTION
**Pull request by colhom**
\cc @quinton-hoole @madhusudancs 

fixes #32997

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33039)

### CODE REVIEW

**Comment by madhusudancs** [comment]
@k8s-bot ok to test

**Comment by madhusudancs** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33039#-:-KS2zJWnqgGIMag58DH5:bnfp4nl)*

**Comment by quinton-hoole** [comment]
@k8s-bot federation gce e2e test this

**Comment by madhusudancs** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/33039)*

**Comment by quinton-hoole** [comment]
@k8s-bot test this issue #IGNORE

**Comment by pwittrock** [comment]
@k8s-bot unit test this issue: #32770

**Comment by pwittrock** [comment]
@madhusudancs @colhom Is this supposed to get cherrypicked into 1.4?  This references a launch blocking issues for 1.4.  Is that issue not launch blocking, or is this a launch blocking PR?

**Comment by madhusudancs** [comment]
@pwittrock this is not exactly a release blocker. This is in kube-down. In some small set of cases, users can hit this code path if the previous kube-up run failed to clean up resources during an earlier run correctly. I don't see it as that big of an issue, but it might look bad if the user actually hits this. I would like to get this cherry-picked, but I wouldn't hold the release. Can go in a patch release.

**Comment by pwittrock** [comment]
Does this fix #32997?  Is #32997 a release blocker?

**Comment by madhusudancs** [comment]
#32997 is not a release blocker.

**Comment by madhusudancs** [comment]
@k8s-bot unit test this issue: #IGNORE

**Comment by janetkuo** [comment]
@madhusudancs @pwittrock Do we need to cherrypick this? $replica_pd does not exist in 1.4 code  https://github.com/kubernetes/kubernetes/blob/release-1.4/cluster/gce/util.sh#L1191-L1198

**Comment by madhusudancs** [comment]
@janetkuo Talked to @pwittrock about this. If the original code isn't in v1.4 we don't have to cherry pick this.

**Comment by quinton-hoole** [comment]
Yes, I can confirm that the bug that this PR fixes was never cherrypicked into v1.4 branch, so no need for this fix to be cherrypicked either.

**Pull request merged**
