### PR TITLE
Add link to diagram of `kubectl drain`

### PR DESCRIPTION
**Pull request by andreykurilin**
issue kubernetes/kubernetes.github.io#501

### CODE REVIEW

**Comment by deads2k** [comment]
You'll need to generate docs and such:  `hack/update-all.sh`.  If that fails, you can try `update-generated-docs.sh`, but I'm not certain that will get everything.

**Comment by asalkeld** [comment]
you should also add "fixes kubernetes/kubernetes.github.io#501" to the PR message.

**Comment by deads2k** [comment]
> @andreykurilin PR needs rebase

Sorry, github didn't send a notification when you re-pushed.  Tag me when you update.  Also, double check that link.

**Comment by andreykurilin** [comment]
@deads2k, PR is rebased

**Comment by deads2k** [comment]
The link: http://kubernetes.io/images/docs/kubectl_drain.svg still 404's for me.  Should I be seeing something?

**Comment by andreykurilin** [comment]
@deads2k I have separate PR to kubernetes.github.io and it doesn't merged yet. Also it hasn't reviews.

see https://github.com/kubernetes/kubernetes.github.io/pull/521

**Comment by deads2k** [comment]
Alright, the link works now.  Run the hack/update-all.sh again.  https://github.com/kubernetes/kubernetes/pull/25736#issuecomment-219699416

@bgrant0607 @kubernetes/kubectl Any guidance on providing deep links from CLI help?  I've seen products decide in both directions and neither is clearly better in my mind.

**Comment by andreykurilin** [comment]
@deads2k It looks like I do not need to run any updaters. See https://github.com/kubernetes/kubernetes/commit/1d25410c3b4a412bdb3af52a4d855297554121b8

**Comment by smarterclayton** [comment]
We need to make a consistent decision here for https://github.com/kubernetes/kubernetes/pull/25810 as well.  Adding SVG links to what are effectively `man` pages is not the end of the world, but it's an unusual step.  Links to help from man pages makes sense, but in our case the help we would be linking to is exactly what is in the man page.

**Comment by bgrant0607** [comment]
@smarterclayton I agree consistency is important. 

We need to think holistically about what we'd like to do with kubectl help. 

We're collecting ideas here:
https://github.com/kubernetes/community/wiki/Roadmap:-kubectl#improve-help--error-messages--output

Among other things, we'll probably need to start to embed formatting. I'm thinking we should write the text in a form (markdown?) that can be post-processed for the various ways in which the text would be published/viewed.

**Comment by bgrant0607** [comment]
I don't have particular concerns about the image links.

**Comment by smarterclayton** [comment]
Fine with that as well.

**Comment by deads2k** [comment]
> I don't have particular concerns about the image links.

 Alright, if I get the choice I'd prefer to include the link.  Rebase once more for merge?

**Comment by andreykurilin** [comment]
@deads2k done

**Pull request merged**
