### PR TITLE
Enable HPA metrics REST clients by default

### PR DESCRIPTION
**Pull request by DirectXMan12**
Now that the metrics APIs are in beta and metrics-server has the appropriate support (as of #52548), we should enable the REST metrics clients by default instead of using the legacy clients.

```release-note
The --horizontal-pod-autoscaler-use-rest-clients flag now defaults to true.  You must have metrics-server enabled for this to work.
```

### CODE REVIEW

**Comment by piosz** [comment]
Test failures look real.

**Review by luxas — COMMENTED** [review]
Kind of LGTM, but the other PR has to be merged first.
Also I want to know what the upgrade scenario looks like.
Can this break any user in any condition?

cc @kubernetes/sig-autoscaling-pr-reviews @kubernetes/sig-auth-pr-reviews (for RBAC changes)
@kubernetes/sig-api-machinery-pr-reviews (for the API group changes)

FYI @kubernetes/kubernetes-release-managers

**Comment by DirectXMan12** [comment]
So, the story on upgrades is this: previously, since this flag was off by default, if you didn't pass this flag explicitly, your HPA controller would fetch metrics by directly connecting to Heapster over legacy API paths.

After this PR, by default, the HPA controller tries to look for metrics by checking the API at metrics.k8s.io, via the "main" API server (which in turn uses aggregation).  Thus, while doing the upgrade, you'd either have to start up metrics server (now run by default in the 1.8 kube-up), or explicitly set this flag to false.  If you don't do one of those two, your HPA won't work.

**Comment by DirectXMan12** [comment]
We'd meant to actually put this PR in earlier in the release, but were delayed by some repository synchronization issues -- in order for things to pass tests, we needed a properly updated version of metrics server.

**Comment by ericchiang** [comment]
> After this PR, by default, the HPA controller tries to look for metrics by checking the API at metrics.k8s.io, via the "main" API server (which in turn uses aggregation). Thus, while doing the upgrade, you'd either have to start up metrics server (now run by default in the 1.8 kube-up), or explicitly set this flag to false. If you don't do one of those two, your HPA won't work.

This sounds like a breaking change. Where there notices in the last release about deprecating the current behavior?

**Comment by DirectXMan12** [comment]
> This sounds like a breaking change. Where there notices in the last release about deprecating the current behavior?

@ericchiang The intention was there in the original PR that introduced this functionality, but unfortunately, looking over the previous iteration's release notes, the wording did not actually get into the release notes :-/.  I'd love to have this enabled by default this release, but I understand if we have to wait until next.

**Comment by ericchiang** [comment]
Okay, per our deprecation policy, it sounds likes we need to announce the existing flag as deprecated for a release before making it the default.

https://kubernetes.io/docs/reference/deprecation-policy/

Removing this from the milestone and adding https://github.com/kubernetes/kubernetes/pull/52572 to the milestone in its place.

**Comment by luxas** [comment]
I also agree with @ericchiang (although I'd like to see this personally)
However, @DirectXMan12 please announce _this time_ in the relnotes that this is gonna change :smile:

**Comment by DirectXMan12** [comment]
> However, @DirectXMan12 please announce this time in the relnotes that this is gonna change 😄

Done :-)

**Comment by mwielgus** [comment]
What is the status of this PR?

**Comment by luxas** [comment]
/retest
@mwielgus We should now merge this PR, code freeze has lifted.

**Comment by luxas** [comment]
@DirectXMan12 You broke out some of this code to other PRs, right?

**Comment by luxas** [comment]
@DirectXMan12 What's the status of this PR?

**Comment by DirectXMan12** [comment]
This got enabled as part of https://github.com/kubernetes/kubernetes/pull/53205.  Closing this PR

**Pull request closed without merging**
