### PR TITLE
break the loop when found true

### PR DESCRIPTION
**Pull request by lixiaobing1**
break the loop when found true.

### CODE REVIEW

**Comment by gmarek** [comment]
\lgtm

**Comment by gmarek** [comment]
@k8s-bot ok to test

**Comment by gmarek** [comment]
@lixiaobing1 - please sign CLA

**Comment by lixiaobing1** [comment]
@gmarek I have signed CLA, thx :)

**Comment by lixiaobing1** [comment]
@gmarek I have operated as to the flowing indication:

  :memo: Please follow instructions at https://github.com/kubernetes/kubernetes/wiki/CLA-FAQ to sign the CLA.

and the next:

    A Contributor License Agreement has been sent to your email address. This must be signed electronically to complete the contributor signup process.

  but I didn't receive the email, do you know why?

**Comment by gmarek** [comment]
@lixiaobing10051267 - I have no idea...

cc @kubernetes/test-infra-maintainers - do you know who deals with the cla-bot now?

**Comment by ixdy** [comment]
per the CLA FAQ, you may want to comment on https://github.com/kubernetes/kubernetes/issues/27796.

**Comment by lixiaobing10051267** [comment]
@gmarek @ixdy I have signed the CNCF CLA, another PR is normal, but why is this PR abnormal?

**Comment by lixiaobing10051267** [comment]
@k8s-ci-robot ok-to-test

**Comment by gmarek** [comment]
@k8s-bot unit test this

**Pull request merged**
