### PR TITLE
selectively move to client-go packages

### PR DESCRIPTION
**Pull request by deads2k**
selectively update some low hanging fruit to use client-go.

@sttts

### CODE REVIEW

**Comment by sttts** [comment]
Looks unsuspicious. What is the long-term goal? client-go copies utils from kube. We move parts of kube using client-go. This feels like we should have a shared top-level repo used by genericapiserver, kube, client.

**Comment by deads2k** [comment]
> Looks unsuspicious. What is the long-term goal? client-go copies utils from kube. We move parts of kube using client-go. This feels like we should have a shared top-level repo used by genericapiserver, kube, client.

I don't think there's ever going to be a pretty place to put "stuff".  @caesarxuchao's goal is put enough into client-go that its one stop shopping for a controller, so I'm not sure he'll want a top level repo for utils.  I'm not particularly opinionated about where the utils go.

**Comment by sttts** [comment]
I am not against using client-go as the one stop shopping place, as long as we define it as that and are consequent everywhere.

**Comment by sttts** [comment]
Another thought which came up: client-go is not generic-client-go. It is tightly coupled with kube. If you now create your own apiserver variant, how will you get your-client-go (and pkg/util/...) for your controllers?

And will the future generic client-go generator script fetch pkg/util/... & friends from k8s.io/apiserver (i.e. not from kube) ? This would mean we have to move everything into k8s.io/apiserver that is needed for a client.

**Pull request merged**
