### PR TITLE
dependencies: update to sigs.k8s.io/yaml v1.3.0

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

No particular benefit and no relevant changes, it's just to stay up-to-date and to avoid having to pull that in when merging
https://github.com/kubernetes/kubernetes/pull/111023 which indirectly depends on the newer release.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve
https://github.com/kubernetes-sigs/yaml/compare/v1.2.0...v1.3.0

**Comment by pohly** [comment]
/assign @liggitt

For root-approval of a dependency update.

**Comment by liggitt** [comment]
```
Files /logs/artifacts/stats-base.json and /logs/artifacts/stats.json are identical
```

**Pull request merged**
