### PR TITLE
Fix 'not patched' kubectl error

### LINKED ISSUE #42384: kubectl patch always show not patched
The bug is introduced in https://github.com/kubernetes/kubernetes/pull/38538

The oldData, newData in [line215](https://github.com/kubernetes/kubernetes/blob/01bfbb5fa0462189932b704be32401822a991627/pkg/kubectl/cmd/patch.go#L215) seem always to be the same. So it always showing `not patched`.

After digging a bit, I found that:

- the place where we save the `oldData` may be wrong.
- sometimes oldData and newData are different because of different `resourceVersion`s, even though the patch is `{}`.

cc: @juanvallejo @fabianofranz

### PR DESCRIPTION
**Pull request by liggitt**
fixes #42384

### CODE REVIEW

**Comment by shiywang** [comment]
hi, @liggitt, I think you just fixed the problem introduced by your pr, but those scenario below still doesn't work
```console
$ kubectl patch -f deployment.yaml -p '{}'
not patched
```
so I made a another pr to address this

**Comment by liggitt** [comment]
the "patched" message simply means a PATCH request was sent to the server and the object returned differed from the last known version of the object.

**Comment by ymqytw** [comment]
The change make it better than before, but I found this `patched`|`not patched` message is not quite helpful considering the following:

1) If using `-f`, the 2 objects are always different. 
```
$ kubectl patch -f ../depl.yaml -p '{}'
{"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"name":"samename","namespace":"default"},"spec":{"replicas":1,"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.7.9","imagePullPolicy":"Always","name":"nginx","ports":[{"containerPort":80}]},{"image":"nginx","name":"nginx2","ports":[{"containerPort":81}]}]}}}}
{"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2017-03-02T17:55:03Z","generation":1,"labels":{"app":"nginx"},"name":"samename","namespace":"default","resourceVersion":"58980","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/samename","uid":"5d153bbf-ff71-11e6-92c1-480fcf4a5275"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nginx"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.7.9","imagePullPolicy":"Always","name":"nginx","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"},{"image":"nginx","imagePullPolicy":"Always","name":"nginx2","ports":[{"containerPort":81,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulername":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"conditions":[{"lastTransitionTime":"2017-03-02T17:55:03Z","lastUpdateTime":"2017-03-02T17:55:03Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":1,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
deployment "samename" patched
```

2) empty patch, but `resourceVersion` changed.
```
$ kubectl patch deployment samename -p '{}'
{"apiVersion":"apps/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2017-03-02T17:55:03Z","generation":1,"labels":{"app":"nginx"},"name":"samename","namespace":"default","resourceVersion":"58980","selfLink":"/apis/apps/v1beta1/namespaces/default/deployments/samename","uid":"5d153bbf-ff71-11e6-92c1-480fcf4a5275"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nginx"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.7.9","imagePullPolicy":"Always","name":"nginx","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"},{"image":"nginx","imagePullPolicy":"Always","name":"nginx2","ports":[{"containerPort":81,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulername":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"conditions":[{"lastTransitionTime":"2017-03-02T17:55:03Z","lastUpdateTime":"2017-03-02T17:55:03Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":1,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
{"apiVersion":"apps/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2017-03-02T17:55:03Z","generation":2,"labels":{"app":"nginx"},"name":"samename","namespace":"default","resourceVersion":"59075","selfLink":"/apis/apps/v1beta1/namespaces/default/deployments/samename","uid":"5d153bbf-ff71-11e6-92c1-480fcf4a5275"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":2,"selector":{"matchLabels":{"app":"nginx"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.7.9","imagePullPolicy":"Always","name":"nginx","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"},{"image":"nginx","imagePullPolicy":"Always","name":"nginx2","ports":[{"containerPort":81,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulername":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"conditions":[{"lastTransitionTime":"2017-03-02T17:55:03Z","lastUpdateTime":"2017-03-02T17:55:03Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":1,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
deployment "samename" patched
```

3) empty patch, but `resourceVersion`not changed.
```
$ kubectl patch deployment samename -p '{}'
{"apiVersion":"apps/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2017-03-02T17:55:03Z","generation":2,"labels":{"app":"nginx"},"name":"samename","namespace":"default","resourceVersion":"59209","selfLink":"/apis/apps/v1beta1/namespaces/default/deployments/samename","uid":"5d153bbf-ff71-11e6-92c1-480fcf4a5275"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":2,"selector":{"matchLabels":{"app":"nginx"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.7.9","imagePullPolicy":"Always","name":"nginx","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"},{"image":"nginx","imagePullPolicy":"Always","name":"nginx2","ports":[{"containerPort":81,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulername":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"conditions":[{"lastTransitionTime":"2017-03-02T17:55:03Z","lastUpdateTime":"2017-03-02T17:55:03Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2017-03-02T17:59:22Z","lastUpdateTime":"2017-03-02T17:59:22Z","message":"ReplicaSet \"samename-763895170\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":2,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
{"apiVersion":"apps/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2017-03-02T17:55:03Z","generation":2,"labels":{"app":"nginx"},"name":"samename","namespace":"default","resourceVersion":"59209","selfLink":"/apis/apps/v1beta1/namespaces/default/deployments/samename","uid":"5d153bbf-ff71-11e6-92c1-480fcf4a5275"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":2,"selector":{"matchLabels":{"app":"nginx"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.7.9","imagePullPolicy":"Always","name":"nginx","ports":[{"containerPort":80,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"},{"image":"nginx","imagePullPolicy":"Always","name":"nginx2","ports":[{"containerPort":81,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulername":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"conditions":[{"lastTransitionTime":"2017-03-02T17:55:03Z","lastUpdateTime":"2017-03-02T17:55:03Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2017-03-02T17:59:22Z","lastUpdateTime":"2017-03-02T17:59:22Z","message":"ReplicaSet \"samename-763895170\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":2,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
deployment "samename" not patched
```

**Comment by ymqytw** [comment]
@k8s-bot gci gke e2e test this
@k8s-bot cvm gke e2e test this

**Comment by liggitt** [comment]
if a patch request is sent to the server and a different object returned, from the client's perspective, the patch was applied, so I think the message is reasonable

**Pull request merged**
