### PR TITLE
Removed the reverted changes from Changelogv1.26.md

### PR DESCRIPTION
**Pull request by Shubham82**
#### What type of PR is this?
/kind bug
/kind cleanup
#### What this PR does / why we need it:
This PR removed the below context from the Changelog.md v1.26, as this PR #112127  has been reverted by PR #113733 in v1.26 and it was missed out to remove that point.

> Fixed DaemonSet to update the status even if it fails to create a pod. (https://github.com/kubernetes/kubernetes/pull/112127, [@gjkim42](https://github.com/gjkim42))

#### Which issue(s) this PR fixes:
None
#### Does this PR introduce a user-facing change?

```
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```
NONE
```

### CODE REVIEW

**Comment by Shubham82** [comment]
Hi @laxmikantbpandhare, @ramrodo
PTAL!

**Comment by Shubham82** [comment]
Once it will merge, then will cherry-pick the fix to the release-1.26 branch.

**Comment by ramrodo** [comment]
Thanks!
/lgtm
/approve

**Pull request merged**
