### PR TITLE
kubeadm: fix godoc formatting for v1beta3

### PR DESCRIPTION
**Pull request by neolit123**
#### What this PR does / why we need it:

Fix indentation of entries in the changelog and the migration steps.
fixes formatting at https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta3

v1beta2 has similar indentation:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/apis/kubeadm/v1beta2/doc.go#L25-L37

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/cc @pacoxu @wangyysde
PTAL for LGTM.

**Comment by neolit123** [comment]
/sig cluster-lifecycle
/area kubeadm
/approve
(? label not added)

**Comment by tengqm** [comment]
Why do we use TABs in comments when plain spaces are good.

**Comment by neolit123** [comment]
> Why do we use TABs in comments when plain spaces are good.

No reason. That's how it was done in v1beta2.

**Pull request merged**
