### PR TITLE
Allow configuring etcd progress notify interval on GCE

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref https://github.com/kubernetes/enhancements/issues/1904

```release-note
NONE
```

/kind feature
/priority important-soon

### CODE REVIEW

**Comment by wojtek-t** [comment]
/hold
until I check if it works as expected

**Comment by wojtek-t** [comment]
/retest
/hold cancel

@jpbetz - works as expected; PTAL

**Comment by jpbetz** [comment]
This looks right. Since it's obvious when it is working (ps output of etcd process will show that flag is set) and @wojtek-t has verified that, I'm satisfied.

/lgtm

**Pull request merged**
