### PR TITLE
set persistenet to false

### PR DESCRIPTION
**Pull request by like-inspur**
this config can reduce disk io usage
/kind bug

### CODE REVIEW

**Comment by coffeepac** [comment]
@like-inspur this will lower disk I/O but only in the 'happy state' where the fluentd container is very stable.  if the fluentd container is not stable then fluentd will be re-pulling lots and lot of logs.

do you have any number on how much this decreases I/O and what the number of pods and log files being read are?

**Comment by like-inspur** [comment]
@coffeepac  no, I just found if config persistent to false, fluentd will not always occupy pos file and change filed , so the cpu and disk usage of fluentd will not be always high

**Comment by like-inspur** [comment]
@coffeepac I add suppress_repeated_stacktrace to prevent form fluentd print lot of logs when it is not stable

**Comment by coffeepac** [comment]
@like-inspur I think the suppression flag is a full positive, but I am hesitant to okay the removal of the pos file.  fluentd is commonly run in a daemonset on long-running nodes.  we should be able to release a new version of the fluentd image without repeating a whole bunch of log messages.  

this feels like something that would better as a config option in a helm chart and not this fairly basic but conservative add-on.

**Comment by like-inspur** [comment]
@coffeepac this config not represent that ths removal of this pos, but represent change pos every 10 seconds not each fluentd read journal file, this code and default config of fluentd is under this: https://github.com/fluent/fluentd/blob/b593e6f4adb08dd9f2d2fd69f83fe7a6a1514d43/lib/fluent/plugin/storage.rb#L31

**Comment by coffeepac** [comment]
@like-inspur I will admit I am not terribly familiar with this part of fluentd so I'm reading code as I go.

In the interest of being both conservative and obvious, can we also set the autosave_interval for all of this plugins to be 10 seconds?  While this will have no immediate practical effect, it will provide a clue to users of this plugin who don't know fluentd very well that there is an important knob here.

also, this requires bumping the fluentd image version values starting here: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-ds.yaml#L48 (a few locations) and here:  https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Makefile#L19

and please note there are already out of sync so please do a patch bump to v3.0.5 in all locations.  

and thank you!

**Comment by like-inspur** [comment]
@coffeepac ok, I wil wait 3.0.5 version issue and recommit a new pull request that contain autosave_interval config, thak you

**Comment by pacoxu** [comment]
This PR still needs LGTM from @sig-instrumentation-reviewers ? 
Should this have a release note?

**Comment by coffeepac** [comment]
@pacoxu we can close this.

@like-inspur this plugin is moving to https://github.com/kubernetes-sigs/instrumentation-addons/pull/1, when that PR is merged, feel free to re-open this if you still want it.

/close

**Pull request closed without merging**
