### PR TITLE
Stop using github.com/pkg/errors

### PR DESCRIPTION
**Pull request by bhumijgupta**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR removes the use of github.com/pkg/errors and migrates to native go errors

#### Which issue(s) this PR fixes:

Part of #103043

#### Does this PR introduce a user-facing change?

```release-note
NONE

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bhumijgupta** [comment]
I signed it

**Comment by bhumijgupta** [comment]
Seems like flake, re triggering the tests
/retest

**Comment by ehashman** [comment]
duplicate https://github.com/kubernetes/kubernetes/pull/103059

/close

**Pull request closed without merging**
