### PR TITLE
Change the version of storage class from alpha to beta

### PR DESCRIPTION
**Pull request by harryge00**
**What this PR does / why we need it**:
Update the yamls in /example. 
**Which issue this PR fixes** 
The current storage-class version is beta. Replace `volume.alpha.kubernetes.io/storage-class` with `volume.beta.kubernetes.io/storage-class` in yamls.
**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by foxish** [comment]
I'm not sure we want to do this yet. 
Perhaps @kubernetes/sig-storage-misc can comment on whether this is appropriate at this stage.

**Comment by gnufied** [comment]
Alpha provisioner is still Alpha - there are two distinct storage classes:

1. Alpha provisioner - that these examples use, it doesn't require a defined StorageClass. Not certain yet, but this method of provisioning might be deprecated/removed.
2. Beta provisioner - that these examples don't use, requires a predefined StorageClass (so values like `any`, `anything` won't work unless those are really names of storageclasses). We are trying to get this feature GA for 1.6

**Comment by thockin** [comment]
I'm throwing this at @jsafrane

**Comment by jsafrane** [comment]
We're preparing for GA in 1.6 and changing all examples is part of it, watch https://github.com/kubernetes/features/issues/163.

@gnufied is right, value of  annotation `volume.beta.kubernetes.io/storage-class` actually matters and it won't work without users editing the yaml file. We'll probably use the default storage class in examples.

**Pull request closed without merging**
