### PR TITLE
Update README.md files in sample-controller

### PR DESCRIPTION
**Pull request by xichengliudui**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xichengliudui** [comment]
Ref: #76306

**Comment by xichengliudui** [comment]
here.

**Comment by xichengliudui** [comment]
here.

**Comment by munnerz** [comment]
Thanks for the x-ref including context for this change 😄 

/lgtm
/approve

**Pull request merged**
