### PR TITLE
hack/*.sh: re-add staging dirs to verify+update scripts

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by deads2k** [comment]
@k8s-bot bazel test this

**Comment by rmmh** [comment]
@sttts #41466 added code that wasn't passed through gofmt

**Comment by sttts** [comment]
Assigned P2 to get it through the queue as every new, un-gofmt-ed change breaks this PR.

**Comment by sttts** [comment]
@k8s-bot unit test this

**Comment by sttts** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by sttts** [comment]
@k8s-bot cross build this

**Comment by sttts** [comment]
@k8s-bot non-cri e2e test this

**Comment by sttts** [comment]
@k8s-bot unit test this

**Comment by sttts** [comment]
@k8s-bot cross build this

**Pull request merged**
