### PR TITLE
Extract volume relevant events reason

### PR DESCRIPTION
**Pull request by NickrenREN**
Extract volume relevant events reason and make them const

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by saad-ali** [comment]
/lgtm

@jsafrane ?

**Comment by NickrenREN** [comment]
@saad-ali  @justinsb  @jsafrane   Rebased and ready for review

**Comment by jsafrane** [comment]
While I like the change, I don't think that `pkg/controller/events/event.go` is the right place. Should it be in `pkg/controller/volume` or even `pkg/controller/volume/persistentvolume `? Or do you plan to extract events from all controllers here?

**Comment by NickrenREN** [comment]
Yes, I think we should extract all controller events and put them in pkg/controller/events, just like kubelet does.

**Comment by jsafrane** [comment]
good lick then
/lgtm

**Comment by NickrenREN** [comment]
ping @deads2k  for approval

**Comment by deads2k** [comment]
I'm not in favor of moving these to a shared package.  They are very specific in nature and we should avoid dependency magnet packages.  I think direction for our controllers should be further subdivision to be run separately, not further coupling of the source code.

A package under controller/volume would be ok.

**Comment by NickrenREN** [comment]
@jsafrane  @deads2k  Moved to pkg/controller/volume

**Comment by deads2k** [comment]
> @deads2k Should we separate them in kubelet package too ?

I'm not familiar with the section in kubelet, but to my knowledge kubelet plans to forever remain a monolith without the intention of supporting addon-like functionality.  The apiserver (and therefore controllers) are intentionally moving towards subdivision.

**Comment by deads2k** [comment]
> @jsafrane @deads2k Moved to pkg/controller/volume

Thanks.

/approve

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Pull request merged**
