### PR TITLE
use host uts namespace when pod.Spec.HostNetwork is true

### PR DESCRIPTION
**Pull request by lvlv**
#12893 set pod utsMode to "host" when host network is used.

### CODE REVIEW

**Comment by thockin** [comment]
Change LGTM.  We don't seem to have any tests of this logic - I'm going to defer to Dawn on whether to ask for one at this point.  It would be super fantastic if you did that.  Just something that verifies that when you pass HostNetwork you get a docker call with net and uts set to "host"

@dchen1107

**Comment by lvlv** [comment]
sure, I'll add a test.

**Comment by lvlv** [comment]
Test added.

**Comment by thockin** [comment]
@dchen1107 or @yujuhong to review or reassign

**Comment by ghodss** [comment]
Thanks for implementing @lvlv, this is great.

**Comment by dchen1107** [comment]
LGTM

**Comment by bgrant0607** [comment]
Fixed #12893

**Pull request merged**
