### PR TITLE
only update Azure data disks when attach/detach

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
only update Azure data disks when attach/detach, update other filelds is not necessary.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
only update Azure data disks when attach/detach
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
none
```

/priority important-soon
/sig cloud-provider
/area provider/azure

### CODE REVIEW

**Comment by andyzhangx** [comment]
@chewong there is no public ip quota in westus2 now:

```
2020/08/27 01:33:56 main.go:312: Something went wrong: starting e2e cluster: error creating cluster: cannot deploy: cannot get the create deployment future response: Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details." Details=[{"code":"BadRequest","message":"{\r\n  \"error\": {\r\n    \"code\": \"PublicIPCountLimitReached\",\r\n    \"message\": \"Cannot create more than 40 public IP addresses for this subscription in this region.\",\r\n    \"details\": []\r\n  }\r\n}"}]
```

**Review by feiskyer — COMMENTED** [review]
/lgtm
/approve

**Review by feiskyer — COMMENTED** [review]
/milestone v1.20

**Pull request merged**
