### PR TITLE
Cherry-pick #52803: AllowPrivilegeEscalation: add validations

### LINKED ISSUE #52454: AllowPrivilegeEscalation missing API validation
**What happened**:
The new `AllowPrivilegeEscalation` feature has silent defaulting logic performed in the kubelet, related to whether the container requests privileged mode or the CAP_SYS_ADMIN capability. Instead, the kubelet should just use the value of the field if specified, and validation should be added to prevent setting the field to true for privileged or CAP_SYS_ADMIN containers.

/cc @jessfraz

### PR DESCRIPTION
**Pull request by jessfraz**
Cherry-pick of #52803: AllowPrivilegeEscalation: add validations

Fixes #52454

### CODE REVIEW

**Comment by abgworrall** [comment]
If someone wants to get regular approval for this, I can get on with the cherrypicking

**Comment by liggitt** [comment]
I consider the approval in #52803 transitive

**Comment by abgworrall** [comment]
Jolly good, that's your call to make :) cherrypick started.

**Pull request merged**
