### PR TITLE
Automated cherry pick of #12283 #14618 #15961

### PR DESCRIPTION
**Pull request by ncdc**
Cherry pick of #12283 #14618 #15961 on release-1.1.

### CODE REVIEW

**Comment by ncdc** [comment]
@lavalamp @smarterclayton

**Comment by smarterclayton** [comment]
Does this have the fix to attach?

**Comment by ncdc** [comment]
D'oh, probably not. That's #15053, right?

**Comment by smarterclayton** [comment]
Should only be commit 7f6f85b
<https://github.com/smarterclayton/kubernetes/commit/7f6f85bd7b47db239868bcd868ae3472373a4f05>
out
of there, but we were also supposed to back port stdinOnce

**Comment by ncdc** [comment]
Or maybe that's too big to pull in for 1.1? I could just cherry-pick https://github.com/smarterclayton/kubernetes/commit/7f6f85bd7b47db239868bcd868ae3472373a4f05 if we wanted to keep it simpler.

**Comment by smarterclayton** [comment]
Brian gave his ok on putting it in 1.1 because attach was new for 1.1 and
we wanted to be consistent with docker run (which the original attach impl
was not)

**Comment by ncdc** [comment]
I can work on trying to pull in attach tomorrow morning. It looks like it probably can't be a straight cherry-pick of the entire PR, since master uses codecgen but 1.1 does not.

**Comment by smarterclayton** [comment]
The last commit can be dropped in the PR - that should be the only codec
gen.

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by ncdc** [comment]
I manually cherry-picked #15053 and #14764 and resolved the conflicts and fixed 1 compilation error - hope that's ok. If not, I can close this PR and create a new one.

**Comment by smarterclayton** [comment]
Cherrypicks look ok to me.

**Comment by lavalamp** [comment]
Adding the lgtm tag. Hopefully shippable will finish soon.

**Comment by ncdc** [comment]
Thanks. Shippable passed once already - any reason for the rerun?

**Comment by lavalamp** [comment]
Oh, it was failed when I looked at it. If it already passed I don't have
objections to merging. @k8s-oncall's discretion.

**Comment by ncdc** [comment]
Really? Hmm. I could've sworn it was all green but maybe I was looking at
something else.

**Comment by lavalamp** [comment]
Actually, IIRC, it just wasn't in the list, which is why I started it again.

**Comment by krousey** [comment]
@lavalamp this has passed all checks now. ok to manually merge?

**Comment by lavalamp** [comment]
@krousey yes, please merge!

**Pull request merged**
