### PR TITLE
Run Function of exception handling, abnormal information effectively

### PR DESCRIPTION
**Pull request by StudyNick**
This PR do the exception handling and effective message. Convenient development debug

Modify Code:
err := app.Run(s)

if err != nil {
fmt.Fprintf(os.Stderr, "%v\n", err)
}

return err

Which issue this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged): fixes #

Special notes for your reviewer:
path: cmd/kube-controller-manager/controller-manager.go
Example:
if err := app.Run(s); err != nil {
fmt.Fprintf(os.Stderr, "%v\n", err)
os.Exit(1)
}

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37674)

**Comment by StudyNick** [comment]
I signed it!

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
This causes the error to be double printed. It's already printed here: https://github.com/kubernetes/kubernetes/blob/master/cmd/hyperkube/hyperkube.go#L181

**Pull request closed without merging**
