### PR TITLE
Modification: revise some errors about golint in some packages.

### PR DESCRIPTION
**Pull request by houminz**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

According to this issue: #68026, I revise some errors about golint in some packages as below
1. pkg/scheduler/apis/config/v1/conversion.go
2. pkg/scheduler/apis/config/v1/conversion_test.go

**Which issue(s) this PR fixes**:

Related to: #68026

**Special notes for your reviewer**:
After I revised above errors, I run hack/update-bazel.sh and hack/update-gofmt.sh to make sure I fix any problems with gofmt or bazel.

@dims

**Does this PR introduce a user-facing change?**:

```release-note
No
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
I don't think these are strictly intended to pass golint, the snake_case naming and lack of comments is how all the conversion functions are written (see example: https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/v1/conversion.go).

I don't know if this is just convention for manual conversions or some requirement of the conversion generator though

**Review by adtac — COMMENTED** [review]
I don't know about the API change but you'll need to run `make generated_files` and `./hack/verify-generated-files.sh` to make sure the generated files are up-to-date.

**Comment by SimpCosm** [comment]
Hi, @damemi Thanks for your comment. I am not sure if we should strictly pass all golint. If this is the convention, I am wondering why don't we follow the golint style.

This is my first PR for k8s and I am trying to contribute. If this PR is not appropriate, I would close it.

**Comment by SimpCosm** [comment]
Hi @adtac, thanks for your reminder, I have update the generated files

**Pull request closed without merging**
