### PR TITLE
Automated cherry pick of #75781: kube-aggregator: bump openapi aggregation log level

### PR DESCRIPTION
**Pull request by roycaihw**
Cherry pick of #75781 on release-1.14.

#75781: kube-aggregator: bump openapi aggregation log level

### CODE REVIEW

**Review by liggitt — COMMENTED** [review]
/lgtm
/approve

**Comment by roycaihw** [comment]
/assign @aleksandra-malinowska @tpepper 

could one of you approve this cherrypick as patch release manager? thanks

**Pull request merged**
