### PR TITLE
Automated cherry pick of #107030: tests: Lowers the number of pods returned by

### PR DESCRIPTION
**Pull request by claudiubelu**
Cherry pick of #107030 on release-1.23.

#107030: tests: Lowers the number of pods returned by

#### What type of PR is this?

/kind flake

/sig testing
/sig windows
/sig apps

#### What this PR does / why we need it:

The Conformance test "should orphan pods created by rc if delete options say so" is spawning 80% of the Cluster's Pod Capacity (on a 2 node setup, with 30 Pods capacity each, it spawns 48 pods).

Because of this, tests that are running in parallel with this test has a higher chance to flake, causing them to timeout because they didn't get to spawn the necessary Pods within the expected 1 minute time.

Lowering the percentage should reduce the amount of flakes we see.

Sample test failures caused by running in parallel with this test can be seen here: https://github.com/kubernetes/kubernetes/issues/106750

#### Which issue(s) this PR fixes:

Fixes #https://github.com/kubernetes/kubernetes/issues/106750

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by liggitt** [comment]
/unassign
/assign @smarterclayton 
I think clayton put this logic in place originally, I'm not sure what the intent is

**Comment by claudiubelu** [comment]
> /unassign /assign @smarterclayton I think clayton put this logic in place originally, I'm not sure what the intent is

Nonetheless, it is a cherry-pick. We've seen quite a lot of flakes because of this, hence why the commit was created, and why the cherry-pick is also done.

**Pull request closed without merging**
