### PR TITLE
Comment that godep versions 54 or above do not play nice with Kubernetes

### PR DESCRIPTION
**Pull request by derekwaynecarr**
I lost a lot of time to this today.

/cc @eparis thanks for the secret knowledge.

### CODE REVIEW

**Comment by eparis** [comment]
I hope the jenkins failure is caused by: https://github.com/kubernetes/kubernetes/pull/22812   it is obviously unrelated to this PR

**Comment by bgrant0607** [comment]
Open and closed to re-run Travis

**Comment by ghodss** [comment]
@derekwaynecarr Can you give some more details on why it doesn't work, and what errors you were running into? Is there a corresponding issue on godep?

**Comment by eparis** [comment]
It fails because https://github.com/kubernetes/kubernetes/pull/22807 never gets merged.  Godep (improved) what they vendor and you cannot used anything greater and reproduce out Godeps/_workspace.

**Pull request merged**
