### PR TITLE
node: e2e: clarify findKubeletService

### PR DESCRIPTION
**Pull request by ffromani**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Address pending comments from https://github.com/kubernetes/kubernetes/pull/105516#pullrequestreview-780230582

#### Which issue(s) this PR fixes:
Fixes N/A

#### Special notes for your reviewer:
Very low priority, but I think the docstrings are a worthy addition

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by fromanirh** [comment]
/sig node
suggested priority: backlog
cc @ehashman @endocrimes @matthyx xref https://github.com/kubernetes/kubernetes/pull/105516#pullrequestreview-780230582

**Review by endocrimes — APPROVED** [review]
/lgtm

Good explanation that is significantly clearer than folks needing to read through and understand systemd

**Comment by fromanirh** [comment]
> /triage accepted /priority backlog
> 
> (I'll lgtm again when the typo gets fixed)

yuck, sorry about the mispelling. fixing.

**Comment by endocrimes** [comment]
np - I get caught out by spellcheck all the time 🤣😭

/lgtm
/assign @ehashman

**Review by ehashman — APPROVED** [review]
:100: 

/lgtm
/approve

**Pull request merged**
