### PR TITLE
Trusty: Fix heapster breakage caused by #22940

### PR DESCRIPTION
**Pull request by andyzheng0831**
The PR #22940 renamed a variable and added a new variable in the heapster pod files. This breaks heapster pod in cluster on Trusty.

@roberthbailey @dchen1107 @vishh please review it. The PR #22940 will be cherry picked for 1.2. Accordingly, please mark this PR as cherrypick-candidate.

### CODE REVIEW

**Comment by andyzheng0831** [comment]
Here is e2e test result. The failed add-on test is expected, as the testing code use ContainerVM method to restart add-on watcher service.

Summarizing 1 Failure:

[Fail] Addon update [BeforeEach] should propagate add-on file changes 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/addon_update.go:358

Ran 158 of 265 Specs in 4135.158 seconds
FAIL! -- 157 Passed | 1 Failed | 0 Pending | 107 Skipped --- FAIL: TestE2E (4135.65s)
FAIL

**Comment by andyzheng0831** [comment]
cc/ @wonderfly @fabioy @Amey-D FYI

**Comment by bgrant0607** [comment]
cc @mwielgus @davidopp

**Comment by dchen1107** [comment]
I asked in previous PR #22940 about e2e test result on trusty node since it is not enabled by default for pr builder, how come the failure isn't capture then?

**Comment by dchen1107** [comment]
Sorry, ignore my question above. It is a different pr for heapster, not trusty one.

**Comment by dchen1107** [comment]
LGTM

**Comment by bgrant0607** [comment]
@pwittrock Please manually merge when ready

**Comment by pwittrock** [comment]
Looks like this is running through the queue now

**Pull request merged**
