### PR TITLE
refactor events utils in e2e

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/kind feature
/sig testing

**What this PR does / why we need it**:

`test/e2e/common` is a mixture of tests (`test/e2e/common/downward_api.go`) and utility code (`test/e2e/common/events.go`). It would be nice to refactor it so that the utility code can be imported without also importing the tests. Most likely a better place for the utility code is under `test/e2e/framework`.

For this PR, the specific reason was the usage of `WaitTimeoutForEvent` in a storage test, which then made it impossible to import the storage tests without those other tests. See #83609. Once `WaitTimeoutForEvent` is in an independent utility package, the copied waitTimeoutForEvent can be removed from `test/e2e/storage/testsuites/volumemode.go` again.

**Which issue(s) this PR fixes**:

part of https://github.com/kubernetes/kubernetes/issues/83937

**Special notes for your reviewer**:

/cc @pohly

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by danielqsj** [comment]
weird, how to retest this case `pull-kubernetes-conformance-image-test` ?
@dims @BenTheElder

**Comment by danielqsj** [comment]
it looks like same as https://github.com/kubernetes/kubernetes/pull/85128

**Comment by dims** [comment]
you can safely ignore `pull-kubernetes-conformance-image-test` failures. it won't affect merging this PR as it is not a `REQUIRED` job.

**Comment by dims** [comment]
we are waiting for kind 0.6.0 to ship

**Comment by danielqsj** [comment]
thanks @dims

**Comment by BenTheElder** [comment]
`/retest` takes no arguments, `/test` takes a test name.
https://prow.k8s.io/command-help

**Comment by danielqsj** [comment]
As #84439 and #84510 were merged.
Could we speed up this PR ? @pohly  @oomichi

**Comment by oomichi** [comment]
This seems good for me to share common code between e2e tests as subpackage of e2e framework without any invalid additional dependencies.

/retest
/lgtm

**Comment by danielqsj** [comment]
@fejta could you help review this PR which related to sig-testing ? thanks

**Pull request merged**
