### PR TITLE
Remove rollbackTo in deployment controller

### PR DESCRIPTION
**Pull request by pigletfly**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Since `spec.rollbackTo` is removed in 1.16, we can remove rollback related logic in deployment controller.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
   NONE

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
   NONE

```

### CODE REVIEW

**Review by janetkuo — APPROVED** [review]

**Comment by pigletfly** [comment]
cc @kubernetes/sig-apps-pr-reviews

**Pull request closed without merging**
