### PR TITLE
unittests: Fixes unit tests for Windows (part 10)

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/sig windows
/sig testing

/kind failing-test
/priority important-soon

#### What this PR does / why we need it:

Currently, there are some unit tests that are failing on Windows due to various reasons:

- Different ``File not found`` error messages on Windows.
- Files need to be closed on Windows before removing them.
- The default ``RootHnsEndpointName`` (``root-hnsendpoint-name``) flag value is ``cbr0``.
- On Windows, Unix Domain sockets are not checked in the same way in golang, which is why ``hostutils_windows.go`` checks for it differently. ``GetFileType`` will return an error in this case. We need to check for it, and see if it's actually a Unix Domain Socket.

#### Which issue(s) this PR fixes:

Related: https://github.com/kubernetes/kubernetes/issues/51540

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kannon92** [comment]
Reviewing from sig-node side (stats), this looks good to me.

LGTM.

Leaving the label for someone else because this has a lot more changes in other areas.

**Comment by marosset** [comment]
@kannon92 @SergeyKanzhelev @yujuhong Can someone help us move this along toward getting merged?

**Comment by kannon92** [comment]
@marosset there are a lot of stakeholders for this PR. The ones you tagged can help with kubelet but you may need to find someone to help with all the other ones.

/cc @thockin @dims

**Comment by yujuhong** [comment]
Q: Is there a CI job running Windows unit tests?

**Review by alculquicondor — COMMENTED** [review]
/approve
for scheduler

**Comment by jsturtevant** [comment]
> Q: Is there a CI job running Windows unit tests?

@yujuhong  https://testgrid.k8s.io/sig-windows-signal#windows-unit-master

**Comment by yujuhong** [comment]
/approve 

for the kubelet side change. 

Curious, what's the plan of preventing regression in the future? Do we intent to run this in presubmits?

**Comment by claudiubelu** [comment]
> /approve
> 
> for the kubelet side change.
> 
> Curious, what's the plan of preventing regression in the future? Do we intent to run this in presubmits?

I think this was an option we discussed at one point, and planned to revisit this once we have the job passing. At this point, it is pretty much a chicken and egg problem: we can't run this in presubmits because some tests are failing, and more test failures are being introduced because we can't run this in presubmits. There are only a few PRs left open for addressing these issues for Windows unit tests, with a bit of focused reviews, we could resolve the problem.

**Comment by dims** [comment]
gonna pull rank here especially as 4 of the 7 files are _test.go. these are small changes across files and they look good to me.

/approve
/lgtm

**Pull request merged**
