### PR TITLE
Support stdinOnce, which allows run-once STDIN injection

### PR DESCRIPTION
**Pull request by smarterclayton**
This change allows containers to wait for input before startup by listening on STDIN, and after STDIN is closed, continue running. 

Currently, the STDIN of the container is never closed (with Stdin true on the container). A container that starts and reads STDIN will block until a third party attaches to the container.  When that user attaches to the container, they will write N bytes and then close their attach session.  When they close the attach session, STDIN inside the container will not be closed.  This pull request allows a caller to request that after the first attach session closes, the STDIN in the container is also closed.

Examples:
- Container with Stdin
  - command: `cat`
  - User 1 attaches, writes `hello` to container, disconnects
  - User 2 attaches, writes `world` to container, disconnects
  - Container logs contain `hello world`
- Container with Stdin and StdinOnce
  - command: `cat`
  - User 1 attaches, writes `hello` to container, disconnects
  - Container writes `hello`, then `cat` exits (STDIN closed) and container exits
- Container with Stdin and StdinOnce
  - command: `cat && sleep 100`
  - User 1 attaches, writes `hello` to container, disconnects
  - Container writes `hello`, then `cat` exits (STDIN closed) and container stays open
  - User 2 attaches, writes `world` to container, gets "write to closed stream" or similar error

StdinOnce makes it possible to:
- Start a run-once container and pass a ZIP via STDIN to extract inside the container
- Start a run-always container and have it block, waiting for a private key to be injected via STDIN

### CODE REVIEW

**Comment by smarterclayton** [comment]
@kubernetes/kube-api involves adding `stdinOnce` to the `Container`

@brendandburns regarding attach.

**Comment by thockin** [comment]
What does it mean to block a restarting container  How can I attach to it after it restarts?

**Comment by brendandburns** [comment]
Presumably it always blocks when it restarts?  That seems kind of like a broken semantic.

--brendan

**Comment by brendandburns** [comment]
(although I'm actually ok with wiring through stuff like this, but we should be _super_ clear to end users about what this means, because I could easily see someone bricking their app with this)

**Comment by smarterclayton** [comment]
@thockin You would just attach again - so the block would happen in the process inside the container.  

@brendandburns this is primarily targeted at jobs and run-once containers.  I did include the run-always container because we have customers with "advanced" security needs who prefer to have manual intervention in restart cases to provide keys (that are only ever in memory, for example, and only flow through one channel).  It's certainly not what I would consider a normal scenario, but for example someone would build automation to watch service endpoints and when a pod becomes unready, attach to the container and provide the private key (which then allows the pod to become ready again).  You could argue someone would use a KSM instead, although we have people who SSH into individual machines and deliver keys on demand to restart, so it's not a huge stretch today.

**Comment by smarterclayton** [comment]
A note - the default Docker run behavior is "StdinOnce" - it's only docker run -d that omits stdin once.  That's another reason why stdinOnce defaults false.

**Comment by thockin** [comment]
I ... did not realize we had an `attach` command :)

**Comment by thockin** [comment]
I don't understand what this does, or maybe I don't understand what the default DOESN'T do?

**Comment by smarterclayton** [comment]
The default behavior opens stdin in the docker daemon and leaves it open. A container that starts and reads STDIN will block until a third party attaches to the container.  When that user attaches to the container, they will write N bytes and then close their attach session.  When they close the attach session, STDIN inside the container will not be closed.  This pull request allows a caller to request that after the first attach session closes, the STDIN in the container is also closed.

Examples:

* Container with Stdin
  * command: `cat`
  * User 1 attaches, writes `hello` to container, disconnects
  * User 2 attaches, writes ` world` to container, disconnects
  * Container logs contain `hello world`
* Container with Stdin and StdinOnce
  * command: `cat`
  * User 1 attaches, writes `hello` to container, disconnects
  * Container writes `hello`, then `cat` exits (STDIN closed) and container exits
* Container with Stdin and StdinOnce
  * command: `cat && sleep 100`
  * User 1 attaches, writes `hello` to container, disconnects
  * Container writes `hello`, then `cat` exits (STDIN closed) and container stays open
  * User 2 attaches, writes ` world` to container, gets "write to closed stream" or similar error

**Comment by smarterclayton** [comment]
I still need to add an e2e test before this is ready to merge.

**Comment by thockin** [comment]
Thanks!  Put that in the docs.

**Comment by smarterclayton** [comment]
ok to test

**Comment by ncdc** [comment]
LGTM

**Comment by ncdc** [comment]
Latest e2e error:

```
• Failure [157.854 seconds]
Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:711
  Simple pod
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:243
    should support inline execution and attach [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:225

    Expected
        <*errors.errorString | 0xc208118e10>: {
            s: "timed out waiting for the condition",
        }
    to be nil

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:222
```

@smarterclayton perhaps something is flakey?

**Comment by smarterclayton** [comment]
There something different when logs are run on the cluster vs not.  Going
to look at it today, but don't know what's wrong yet.

On Oct 8, 2015, at 9:42 AM, Andy Goldstein <notifications@github.com> wrote:

Latest e2e error:

• Failure [157.854 seconds]
Kubectl client
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:711
  Simple pod
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:243
    should support inline execution and attach [It]
    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:225

    Expected
        <*errors.errorString | 0xc208118e10>: {
            s: "timed out waiting for the condition",
        }
    to be nil

    /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:222

@smarterclayton <https://github.com/smarterclayton> perhaps something is
flakey?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/15053#issuecomment-146549166>
.

**Comment by smarterclayton** [comment]
Fixed it - Docker logs won't write to the log unless a line is complete.  The test now writes a complete line.  Ready for review.  Note that this changes "run attach" default behavior to be equivalent to Docker for restart=Never, instead of the current value which leaves an open STDIN.  I choose to believe that Docker's behavior is more correct and that the current behavior is a bug.  For the other use case it exposes `--leave-stdin-open`.

**Comment by smarterclayton** [comment]
Needs @kubernetes/kube-api API change sign off

**Comment by smarterclayton** [comment]
Gentle ping on API review - this is likely something we would carry (because it is required to enable our perform direct binary build from a client by passing a gzip tar to the input stream), so wanted to get buy in on the API change before we do that.

**Comment by bgrant0607** [comment]
Had been ignoring post-1.1 PRs. WTAL.

**Comment by bgrant0607** [comment]
API and kubectl changes LGTM.

--leave-stdin-open is a breaking CLI change, but only for features that were introduced after 1.0. We need to cherrypick it into 1.1.

**Comment by smarterclayton** [comment]
@brendandburns any other comments?

On Oct 14, 2015, at 4:08 PM, Brian Grant <notifications@github.com> wrote:

API and kubectl changes LGTM.

--leave-stdin-open is a breaking CLI change, but only for features that
were introduced after 1.0. We need to cherrypick it into 1.1.

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/15053#issuecomment-148180739>
.

**Comment by smarterclayton** [comment]
ok to test

**Comment by smarterclayton** [comment]
The new e2e test caught a failure in attach introduced by the old refactor (attach was previously uncovered by e2e test).  That is now fixed in the last commit, and a new unit test is in place.  @ncdc please review.

**Comment by ncdc** [comment]
@smarterclayton did you see my commit comment from yesterday?

**Comment by smarterclayton** [comment]
No, and I'm on PTO today.  This fixes the break is master and we can add new tests as a follow up (e2e also tests the query parameters).

**Comment by ncdc** [comment]
Ok, LGTM added

**Comment by ncdc** [comment]
Travis is failing on `hack/verify-codecgen.sh` - do you need to regenerate anything?

**Comment by ncdc** [comment]
@smarterclayton looks like a rebase is needed + a call to hack/update-codecgen.sh

**Comment by smarterclayton** [comment]
Added generation, reapplying LGTM.

For cherrypick, only the first two should be back ported to 1.1 (the 3rd commit is only necessary if #14618 was back ported, which it wasn't afaik), and the 4th commit won't be in 1.1.

**Pull request merged**
