### PR TITLE
Remove ability to disable quorum reads

### PR DESCRIPTION
**Pull request by liggitt**
This flag was defaulted to true (#53717) and deprecated in 1.9 (#53795).

Setting it to false causes bugs in controllers because of stale reads.

Those bugs can lead to runaway controllers (creating too many objects), stuck controllers (not acting on latest state), and controllers breaking invariants (reacting to objects in different parts of their lifecycle than they are actually in).

Quorum reads perform badly on etcd2, which was also marked as deprecated in 1.9, and is scheduled for removal ~1.13.

```release-note
kube-apiserver: the --etcd-quorum-read flag (deprecated in 1.9) has been removed. etcd client connections now always run using quorum reads.
```

### CODE REVIEW

**Comment by liggitt** [comment]
/assign mikedanese
for /cluster approval

**Comment by justinsb** [comment]
I'm not sure this is following out deprecation policy, and may have some unexpected impact on kops.  I'd like to ask for a bit of time to figure out the impact on kops.

**Comment by liggitt** [comment]
> I'm not sure this is following our deprecation policy

Can you be more specific? The relevant portion seems to be:
*Rule #5b: CLI elements of admin-facing components (e.g. kubelet) must function after their announced deprecation for no less than: 
GA: 6 months or 1 release (whichever is longer)*

1.11 meets both criteria after deprecation was announced in 1.9

> I'd like to ask for a bit of time to figure out the impact on kops.

I would expect any cluster intentionally setting this to false with a multi-member etcd cluster (knowing the correctness issues it causes) to be unsupported. I have a hard time justifying allowing a flag to remain that is known to cause bugs and is not supported.

I did look into single-member performance and it appears as though etcd2 still pays the quorum read penalty, even though a quorum read is not required to get a consistent result from a single-member etcd.

Opened https://github.com/kubernetes/kubernetes/pull/61637 as an alternative to complete removal that limits use of non-quorum mode to etcd setups that can still work correctly with it.

**Comment by deads2k** [comment]
> Opened #61637 as an alternative to complete removal that limits use of non-quorum mode to etcd setups that can still work correctly with it.

I don't think we need to keep the flag.  Etcd3 has been around a long time, so the performance penalty in a non-production cluster using a very old level of storage doesn't concern me.  On production clusters (HA), this flag has just been a risk.

lgtm

**Comment by lavalamp** [comment]
Although I think this flag is evil and should be removed, I can see an argument that it should exist as long as etcd2 exists. Can we just make the etcd3 backend ignore this flag for now?

**Comment by liggitt** [comment]
I think https://github.com/kubernetes/kubernetes/pull/61637 is what I'd recommend to accommodate etcd2. Single-member etcd setups don't require explicit quorum read.

**Comment by liggitt** [comment]
Closing this, can continue discussion in https://github.com/kubernetes/kubernetes/pull/61637

**Pull request closed without merging**
