### PR TITLE
custom resource De-Registration testcase

### PR DESCRIPTION
**Pull request by sdminonne**
@deads2k  as discussed via IRC

Built on top of #45732
To reproduce #45767

Uncomment code in `TestDeRegistrationAndReRegistration` to reproduce `panic`

### CODE REVIEW

**Comment by deads2k** [comment]
I think you will be fixed by https://github.com/kubernetes/kubernetes/pull/45804

**Comment by sdminonne** [comment]
@deads2k thanks, wait for the fix then.

**Comment by deads2k** [comment]
> @deads2k thanks, wait for the fix then.

it merged.

**Comment by sdminonne** [comment]
@deads2k thanks

**Comment by sdminonne** [comment]
@deads2k my understanding is that this test fails due to a bug: opened #45878 to track it.

**Comment by sdminonne** [comment]
xref #45511

**Comment by sdminonne** [comment]
@deads2k updated adding a Delete for the created instance.
Added a TODO for finalizers.
Already squashed. 
ptal

**Comment by deads2k** [comment]
@k8s-bot ok to test

**Comment by sdminonne** [comment]
@deads2k  sorry hope this is the last time :(

**Comment by deads2k** [comment]
@k8s-bot kops aws e2e test this

**Comment by sdminonne** [comment]
@deads2k thanks

**Pull request merged**
