### PR TITLE
fixed detection of the docker version #22485:

### LINKED ISSUE #22485: fixing detecting docker version
In the getting-started-guides matches the detection of the docker version not with a version 1.1x.

https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/master.sh#L108

https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/worker.sh#L105

### PR DESCRIPTION
**Pull request by pstauffer**
changed detection of the docker version. Should now match docker 1.1x.x.

Should fix #22485

### CODE REVIEW

**Comment by jlowdermilk** [comment]
@k8s-bot ok to test

**Comment by a-robinson** [comment]
cc @kubernetes/sig-node - looks like this got missed

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
cc @pwittrock

**Comment by yujuhong** [comment]
@pstauffer could you rebase, thanks!

**Comment by pstauffer** [comment]
Hi,

It looks like this is not possible, because the `docs/getting-started-guides/docker-multinode` directory is no more available in the master branch.
I see, that there are many changes and the part is outsourced in the https://github.com/kubernetes/kube-deploy repository. And there are other scripts...

Shall I close this issue?

Greets
Pascal

**Comment by pwittrock** [comment]
This lives here now: https://github.com/kubernetes/kubernetes.github.io/tree/master/docs/getting-started-guides/docker-multinode

**Comment by yujuhong** [comment]
Based on https://github.com/kubernetes/kubernetes/pull/22488#issuecomment-228206183, the doc has been moved to a different repo. Closing this PR.

**Pull request closed without merging**
