### PR TITLE
cleanup translations and fix update-translations.sh

### PR DESCRIPTION
**Pull request by atiratree**
#### What type of PR is this?

/kind cleanup
/sig cli

#### What this PR does / why we need it:

- the script hack/update-translations.sh stopped working
- translations include old currently unused msgids and do not include new msgids

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

- I added a new option to the `update-translations.sh` script to fix old/new msgids. I am not sure if we should include this logic with already present `-g` option or have it as a new standalone option `-k`.
- I am deprecating old msgids but keeping them in the file as obsolete (`#~`). It is like that, because it is nice to run this script automatically, but to keep the old unused translations in the file. So the translators can easily copy changed translation when for example only one letter changed. The obsoleted translations need to be removed manually, which is easy since they are at the end of the file.
- I am not sure if I should split this PR into multiple ones? The first commit is fixing/adding new logic to `update-translations.sh` and the rest are various generated changes

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by dougsland — COMMENTED** [review]
@atiratree could you please squash your patches so would be easier to review it?

**Comment by atiratree** [comment]
@dougsland I have squashed all the generated changes to one commit, but kept the features commits for better clarity

**Comment by atiratree** [comment]
rebased

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by hwdef** [comment]
I'm a bit confused about this pr, if an English language is not translated and it needs to be translated, it won't be added to the corresponding language's `po` file after running this script with `-k`.

The result now is that the [`en_US`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/util/i18n/translations/kubectl/en_US/LC_MESSAGES/k8s.po) file has 6,000+ lines but the other languages have only a few lines. For example, [`zh_CN`](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubectl/pkg/util/i18n/translations/kubectl/zh_CN/LC_MESSAGES/k8s.po) has only 3000+ lines and [`ko_KR`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/util/i18n/translations/kubectl/ko_KR/LC_MESSAGES/k8s.po) has less than a hundred lines.

@atiratree 
Can you help me with something?

**Comment by atiratree** [comment]
@hwdef We are only storing the translated parts. The rest will be defaulted to english. If you want to add new translations. you need to first generate the `template.pot` file, then you can open the `k8s.po` file for each language in `poedit` where you can import the empty lines from the `template.pot`. Then you can manually translate and edit in `poedit`. You may find some of  the commented out translations good for reuse if only for an example a punctuation changed in the source text

Nevertheless, the translations and the script are not really well maintained. So, if you want to help with this effort , I suggest to visit sig-cli call and ask there first.

- https://www.gnu.org/software/gettext/manual/gettext.html#Template

**Comment by hwdef** [comment]
```
 then you can open the k8s.po file for each language in poedit where you can import the empty lines from the template.pot
```

Do you mean this?

截屏2023-08-23 10 37 15

**Comment by atiratree** [comment]
yes, although for some finer tuning, you may need to consult the gettext CLI tools/documentation or do it manually

**Comment by hwdef** [comment]
Thank you very much!

**Pull request merged**
