### PR TITLE
Add DCOS getting started guide (gh-pages)

### PR DESCRIPTION
**Pull request by karlkfi**
- Add DCOS guide to table of solutions

master changes:
DCOS guide (docs): #17198
DCOS guide in guide list (docs): #17689

cherry-picks to release-1.1:
DCOS guide (docs): #17712
DCOS guide in guide list (docs): #18034

This PR adds the content that #17695 was added to link to (currently it 404s).

### CODE REVIEW

**Comment by karlkfi** [comment]
As demonstrated by #17695, the merge bot doesn't know how to merge to gh-pages. So this must be merged manually.

**Comment by nikhiljindal** [comment]
Arent you importing from release branch?
The unversioned warnings shouldnt be there. Also the title isnt set correctly.
Whats the command you ran?

**Comment by karlkfi** [comment]
I ran exactly the example command:

```
git checkout upstream/gh-pages
git checkout -b gh-pages-dcos-guide

rm -rf _v1.1/docs/ _v1.1/examples/
go run _tools/release_docs/main.go _tools/release_docs/api-reference-process.go --branch release-1.1 --output-dir _v1.1 --version v1.1

git add _v1.1/docs/getting-started-guides/README.md
git add _v1.1/docs/getting-started-guides/dcos.md
git commit
```

Should I have run something else?

**Comment by karlkfi** [comment]
It looks like the cherry-pick #17712 to release-1.1 kept the unversioned warnings. It's possible it was not done correctly. Do I need to remove them there first?

**Comment by nikhiljindal** [comment]
aah am very sorry, I missed pointing out a step in cherrypicking a doc change to release branch.
You need to run ./hack/versionize-docs.sh to versionize the doc in release branch (it removes the unversioned warning and updates links to point to release docs rather than HEAD).
Checkout the release branch and run versionize docs there.

We can definitely make all this simpler.

**Comment by nikhiljindal** [comment]
The exact command to run is
```
./build/versionize-docs.sh release-1.1
```

**Comment by karlkfi** [comment]
which requires gnu-sed -_-

**Comment by nikhiljindal** [comment]
You dont have sed? :)
I can send a PR running that script, if it helps.

**Comment by karlkfi** [comment]
I'm on a mac and don't particularly want the gnu tools on my box. I have bsd sed. Trying to see if I can run it in a container.

**Comment by karlkfi** [comment]
For posterity...

```
$ ./cluster/mesos/docker/test/build.sh
$ docker run -it \
  -v "$(pwd):/go/src/github.com/GoogleCloudPlatform/kubernetes" \
  -v "/var/run/docker.sock:/var/run/docker.sock" \
  mesosphere/kubernetes-mesos-test \
  -c './build/versionize-docs.sh release-1.1'
```

but of course it fails, likely due to docker client/daemon mismatch:

```
...
+++ [1202 02:11:48] Clean up complete
Generating api reference docs at v1
Reading swagger spec from: /go/src/github.com/GoogleCloudPlatform/kubernetes/./hack/gen-swagger-doc/../api/swagger-spec/
Error response from daemon: v1/v1/ includes invalid characters for a local volume name, only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
```

@nikhiljindal can you go ahead and make a fix PR for release-1.1?

**Comment by nikhiljindal** [comment]
Sure on it

**Comment by karlkfi** [comment]
Looks like i get the same problem running it locally, after having installed gnu-sed. So it's not a docker client/daemon mismatch. It's probably an incompatibility with the docker 1.9.0 I have installed.

**Comment by karlkfi** [comment]
`-v $V1_TMP_IN_HOST:/output:z` became `-v v1/v1/:/output:z`. It looks like the volume name syntax might have changed in a reverse incompatible way for docker 1.9. I didn't even know they could have names...

**Comment by karlkfi** [comment]
Looks like the error message is just confusing: https://github.com/docker/docker/issues/17734

The host-dir can either be an absolute path or a volume name. In this case it's a relative path, which is no longer allowed since volume name support was added.

**Comment by nikhiljindal** [comment]
Thanks for digging into that @karlkfi 
I got that error too, but we can ignore it for now since nothing changed in types.go so no need to run update-api-reference-docs.

Sent https://github.com/kubernetes/kubernetes/pull/18051

**Comment by karlkfi** [comment]
Went ahead and merged #18051 after it passed unit/integration and travis tests. Now I'll need to redo this one.

**Comment by karlkfi** [comment]
amended. PTAL @nikhiljindal

**Comment by nikhiljindal** [comment]
LGTM, thanks!

**Comment by nikhiljindal** [comment]
Self merging since its gh-pages

**Comment by karlkfi** [comment]
@nikhiljindal Thanks for your help! I'm off for the night. I'll leave the rest of the gh-pages sync to you, unless you need help tomorrow. Probably a good idea to document the update-api-reference-docs bug too!

**Comment by nikhiljindal** [comment]
Thanks @karlkfi!
Updating a doc should be far simpler! Lots of work to do.

Sent https://github.com/kubernetes/kubernetes/pull/18059 to update rest of docs.
Filed https://github.com/kubernetes/kubernetes/issues/18055 for the versionize-docs issue.

**Pull request merged**
