### PR TITLE
Add ability to disable dumping logs

### PR DESCRIPTION
**Pull request by wojtek-t**

### CODE REVIEW

**Comment by wojtek-t** [comment]
fixed gofmt

**Comment by wojtek-t** [comment]
Merging manually - it's needed to large scale testing and the risk for this PR is super low.

**Comment by zmerlynn** [comment]
@shyamjvs: This PR needs to be cherry-picked if you're expecting kubernetes/test-infra#3974 to work.

**Comment by shyamjvs** [comment]
This change already exists in 1.7 and 1.6. So cherry-picking for 1.5 and 1.4 should be enough I think.
I can send cherry-pick PRs for them, though I'm not too inclined towards the way how our test-infra is so tightly coupled to k8s that we require changes to be backward compatible with all earlier release branches. Can we do something better? Like filter all flags that're undefined in the k8s code against which we're running kubetest or sth?

**Comment by zmerlynn** [comment]
Why am I not seeing cherrypicks associated with this PR if it was picked into 1.7/1.6? Did it violate process?

**Comment by zmerlynn** [comment]
Oh, it's just ancient. Nevermind. :)

**Comment by zmerlynn** [comment]
I agree with your meta-point that this is a pain, but we've gradually been unwinding the inter-dependencies.

**Pull request merged**
