### PR TITLE
GCE: Fix network/subnet url logic

### LINKED ISSUE #48521: GCE: Config's network name ignored when it's not a url
#47881 broke support for specifying network name.

### PR DESCRIPTION
**Pull request by nicksardo**
Split if conditions: fixes #48521

/assign @bowei 

```release-note
NONE
```

### CODE REVIEW

**Comment by bowei** [comment]
Just so I understand, the bug is that the two names should remain empty string if specified as such, rather than go through the get...URL() func

**Comment by nicksardo** [comment]
The previous logic and fix is that networkURL and subnetURL remain their default values (generated before parsing config).  The break happened when subneturl and networkurl were overwritten when the network name and subnetwork name are missing.

**Comment by nicksardo** [comment]
1.7 branch has https://github.com/kubernetes/kubernetes/blob/release-1.7/pkg/cloudprovider/providers/gce/gce.go#L191-L204

**Review by bowei — APPROVED** [review]
/lgtm

**Pull request merged**
