### PR TITLE
feat: use framework.ExpectNoError instead in e2e test

### PR DESCRIPTION
**Pull request by draveness**
/kind cleanup
/priority backlog
/sig testing

**What this PR does / why we need it**:

ref: https://github.com/kubernetes/kubernetes/issues/77103

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by oomichi** [comment]
@draveness Thanks for doing this.
We just need to remove the following lines for passing CI jobs:
```
/b/f/w/test/e2e/apimachinery/crd_watch.go:34:2: imported and not used: "k8s.io/kubernetes/vendor/github.com/onsi/gomega"
/b/f/w/test/e2e/apimachinery/garbage_collector.go:45:2: imported and not used: "k8s.io/kubernetes/vendor/github.com/onsi/gomega"
/b/f/w/test/e2e/apimachinery/watch.go:33:2: imported and not used: "k8s.io/kubernetes/vendor/github.com/onsi/gomega"
```
I much prefer to see such gomega removals anyways :-)

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Comment by oomichi** [comment]
much better, thanks

/lgtm

**Pull request merged**
