### PR TITLE
Bump go.opentelemetry.io/otel to 1.17.0 and go.opentelemetry.io/contrib to 0.42.0

### PR DESCRIPTION
**Pull request by MartinForReal**
bump go.opentelemetry.io/otel to 1.16.0 and go.opentelemetry.io/contrib to 0.42.0

#### What type of PR is this?
/sig instrumentation
/kind feature

#### What this PR does / why we need it:

Update otel contrib dependencies from v0.35.0 to v0.42.0
Update otel dependencies from v1.10.0to v1.17.0

As part of kubelet tracing beta, we should add tracing support to the kubelet's read-only endpoint, which currently does not have tracing. It should use WithPublicEndpoint to prevent callers from influencing sampling decisions.

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/kubernetes/issues/109829

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
[KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/647-apiserver-tracing
```

### CODE REVIEW

**Comment by MartinForReal** [comment]
related: https://github.com/kubernetes/kubernetes/issues/113366

**Comment by dashpole** [comment]
I think this might be blocked by https://github.com/kubernetes/kubernetes/issues/113366.  Do you need the OTel dependency update?

**Review by neolit123 — COMMENTED** [review]
/remove-sig cluster-lifecycle

**Pull request closed without merging**
