### PR TITLE
Don't re-run EnsureChain/EnsureRules on partial syncs

### PR DESCRIPTION
**Pull request by danwinship**
#### What type of PR is this?
/kind cleanup
/kind feature

#### What this PR does / why we need it:
As discussed in https://github.com/kubernetes/kubernetes/pull/110268#issuecomment-1329246104, `MinimizeIPTablesRestore` is helping a lot, but maybe not as much as it could, and I suspect part of that is the resyncing of the `iptablesJumpChains` on each resync

We currently invoke `/sbin/iptables` 24 times on each `syncProxyRules` before calling `iptables-restore`. Since even trivial iptables invocations are slow on hosts with lots of iptables rules, this adds a lot of time to each sync. Since these checks are expected to be a no-op 99% of the time, skip them on partial syncs.

#### Which issue(s) this PR fixes:
none

#### Does this PR introduce a user-facing change?
```release-note
NONE
```
(this is just a tweak on top of #110268 and doesn't need a separate release note)

/sig network
/priority important-soon
cc @wojtek-t

### CODE REVIEW

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-kind-ipv6

doesn't look related

> Kubernetes e2e suite: [It] [sig-node] Ephemeral Containers [NodeConformance] will start an ephemeral container in an existing pod [Conformance] expand_less	

/lgtm

good one

/hold
for others to review

**Comment by wojtek-t** [comment]
Nice - looking forwards to seeing impact of this.

/lgtm

/milestone v1.27

/hold cancel

@thockin - FYI

**Comment by wojtek-t** [comment]
FTR - with this change we seem to be ~2x better on 50th percentile of network programming latency, but neither 90th nor 99th changed visibly:
https://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=Network&metricname=Load_NetworkProgrammingLatency&Metric=NetworkProgrammingLatency

I think that 50th percentile looks really great at this point.
I would like to understand a bit better at some point why 90th and 99th (especially 90th) are so much higher, but that's not of a huge priority right now.

**Comment by aojea** [comment]
@wojtek-t how do we know if was this change or this one https://github.com/kubernetes/kubernetes/pull/114229 ?

**Comment by wojtek-t** [comment]
> @wojtek-t how do we know if was this change or this one https://github.com/kubernetes/kubernetes/pull/114229 ?

Good question. I initially didn't realize they both merged roughly at the same time.
So we don't know. Or at least - I don't know :)

The easiest way would be to run 5000-node optional pull test against revert of one of those to double check.

But my guess (the fact that it only affected 50-th percentile and not 90 and 99-th is that it's probably your PR that helped here...)

**Comment by danwinship** [comment]
The metrics cover both partial syncs and full syncs, but the PR only improves the speed of partial syncs. Since most syncs are expected to be partial, the 50th percentile time drops, because that measurement is mostly the average partial sync time. But the 90th and 99th percentile times are unaffected, since they are mostly indicating the speed of the slowest full syncs.

We probably need to add separate full and partial sync metrics.

**Comment by wojtek-t** [comment]
> We probably need to add separate full and partial sync metrics.

Good point! 
+1 for being able to distinguish those via metrics

**Pull request merged**
