### PR TITLE
Fix nodeShutdownReason for node shutdown e2e

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?

/kind bug
/kind failing-test

#### Which issue(s) this PR fixes:

The #102840 modified the `Status.Reason` of shutdown, but e2e did not modify it accordingly. 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by ehashman** [comment]
`"GracefulNodeShutdown [Serial] [NodeAlphaFeature:GracefulNodeShutdown]"` these tests are only running on their own CI tab and don't have a corresponding presubmit job. Can we just nix the NodeAlphaFeature selector and have them run as part of the serial job? This is beta now so the feature flag should be getting set, no? https://testgrid.k8s.io/sig-node-kubelet#kubelet-serial-gce-e2e-graceful-node-shutdown

I can't find any matching failures for this error message: https://storage.googleapis.com/k8s-triage/index.html?text=Expecting%20non-critcal%20pod%20to%20be%20shutdown%2C%20but%20it%27s%20not%20currently.

Test failures for this job all fail on waiting on /configz, so I think perhaps the jobs don't have a valid config to enable gracefulshutdown: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-graceful-node-shutdown/1442540619628023808

/hold
/cc @bobbypage @rphillips @wgahnagl

**Comment by bobbypage** [comment]
@ehashman I agree we should eventually remove this separate job and move into serial. However, I think we should first ensure to get this job fully stable and working and only after migrate this existing serial tests.

I think we still need this change as described in https://github.com/kubernetes/kubernetes/pull/104540#issue-977806564

The waiting on `configz` failure is because the job relies on DynamicKubeletConfig, but it was turned off by default in https://github.com/kubernetes/kubernetes/pull/102966 

I will send separate PR to turn it back on for this job for now, so we can get it back to green.

In terms of this change here
/lgtm

**Comment by bobbypage** [comment]
PR for enabling DynamicKubeletConfig to fix ` waiting on /configz` errors - https://github.com/kubernetes/test-infra/pull/23791

**Comment by bobbypage** [comment]
kubernetes/test-infra#23791 was merged to fix `configz` errors. 

@ehashman can we remove the hold on this so we can start fixing the test? Thanks!

**Review by ehashman — APPROVED** [review]
/lgtm
/approve

```
ï¿½[1mSTEPï¿½[0m: Verifying that non-critical pods are shutdown
Oct 19 22:21:05.208: INFO: Expecting non-critcal pod to be shutdown, but it's not currently. Pod: "period-120", Pod Status Phase: "Running", Pod Status Reason: "Terminated"
```

from 

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-graceful-node-shutdown/1450585087165861888

**Pull request merged**
