### PR TITLE
Omit timeAdded from taint when empty.

### LINKED ISSUE #42394: taint fields: timeAdded not set
I set taints on a node using the kubelet, but the timeAdded field was not set:

```
 taints:
  - effect: NoSchedule
    key: dedicated
    timeAdded: null
    value: master
```

In addition, I think we prefer to omit null fields.

### PR DESCRIPTION
**Pull request by k82cn**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #42394

**Release note**:

```release-note
Update 'Taint.TimeAdded' to pointer so it's omitted from 'Taint' when empty.
```

### CODE REVIEW

**Comment by k82cn** [comment]
@liggitt , just created a new PR based on yours (not sure how to patch to your PR :( ).

**Comment by liggitt** [comment]
sorry, just rebased https://github.com/kubernetes/kubernetes/pull/43016

**Comment by thockin** [comment]
I have no context.  @ me when if you need approval.

**Comment by k82cn** [comment]
Continue the work in #43016 :).

**Pull request closed without merging**
