### PR TITLE
Fix Bugs in CPUManager distribute NUMA policy option

### LINKED ISSUE #106571: [Flaky Test][sig-node] kubernetes-unit-test TestTakeByTopologyNUMADistributed is being Flaky
### Which jobs are flaking?

periodic-kubernetes-unit-test-ppc64le

### Which tests are flaking?

1. pkg/kubelet/cm/cpumanager.TestTakeByTopologyNUMADistributed
2. pkg/kubelet/cm/cpumanager.TestTakeByTopologyNUMADistributed/allocate_24_full_cores_with_8_distributed_across_the_first_3_NUMA_nodes_(filling_the_first_NUMA_node)

### Since when has it been flaking?

Not sure about the exact date. But it is for sure flaking from 6th November 2021.
We have logs from then. Do not have the earlier logs now.

### Testgrid link

https://k8s-testgrid.appspot.com/sig-node-ppc64le#unit-tests

### Reason for failure (if possible)

Seems like https://github.com/kubernetes/kubernetes/pull/105631 added the test.

### Anything else we need to know?

Below is the failure trace from Job:
```
 === Failed
=== FAIL: pkg/kubelet/cm/cpumanager TestTakeByTopologyNUMADistributed/allocate_24_full_cores_with_8_distributed_across_the_first_3_NUMA_nodes_(filling_the_first_NUMA_node) (0.01s)
    cpu_assignment_test.go:830: expected result [2-17,30-37,42-57,70-77] to equal [2-17,20-27,42-57,60-67]
    --- FAIL: TestTakeByTopologyNUMADistributed/allocate_24_full_cores_with_8_distributed_across_the_first_3_NUMA_nodes_(filling_the_first_NUMA_node) (0.01s)
=== FAIL: pkg/kubelet/cm/cpumanager TestTakeByTopologyNUMADistributed (0.13s) 
```

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by klueska**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix bugs in CPUManager distribute NUMA policy introduced for 1.23 in https://github.com/kubernetes/kubernetes/pull/105631

This includes:
* Fixing #106571 by rounding the mean and stddev calculations to the nearest 1000th. Without this, rounding errors could lead to different results, causing flaky unit tests.
* Making sure we balance any remainder CPUs we want to allocate across *all* NUMA nodes (not just the NUMA nodes in the distribution set).
* Fixing a bug in the map.Keys() and map.Values() implementations. We were appending to lists that had been preallocated with a specific size, leading to a bunch of leading zeros in these lits. When passed to the mean/stddev functions this caused obvious issues.
* Updating the calculation for the minimum number of NUMA nodes required to satisfy the allocation. Previously we would calculate a value larger than the true minimum, causing the algorithm to think it couldn't distribute CPUs properly and fall back to the packed algorithm unnecessarily.
* Fixing an accounting bug in the NUMA distribution algorithm. Without this fix, the algorithm may decide to allocate "remainder" CPUs from a NUMA node that has no more CPUs to allocate. Moreover, it was only considering allocation of remainder CPUs from NUMA nodes such that each NUMA node in the remainderSet could only allocate 1 (i.e. 'cpuGroupSize') more CPUs. With these two issues in play, one could end up with an accounting error where not enough CPUs were allocated by the time the algorithm runs to completion.

I have added / updated a number of unit tests to verify that each of these bugs are indeed fixed. That said, the code could still benefit from more extensive testing. We will make sure to include that before promoting this feature to `beta`.

#### Which issue(s) this PR fixes:
Fixes #106571

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by fromanirh** [comment]
/triage accepted
it seems to me a extremely low risk fix whose gains greatly exceeded the risks, and since we are still before test freeze,  we should have this in. I'll check  ASAP if my understanding is correct.

**Comment by fromanirh** [comment]
It would be nice, for documentation purposes, to have some more details on the scenario which triggers this bug, because it's surprising we cannot trigger this with the unit tests. This area of the code is easily testable (and because of this it has comprehensive testing). Besides this, LGTM.

**Comment by swatisehgal** [comment]
The changes look reasonable and I have no objections but I agree with @fromanirh, it would be helpful to pinpoint what exactly caused this and how it can be reproduced. 
@klueska Can you share the CPU Distribution of the live machine where this issue occurred and what the CPU request looked like for better understanding?

**Comment by klueska** [comment]
To actually pinpoint this bug, I did, in fact reproduce the exact failure scenario it in a unit test. But I had to add a new machine that matched the live machine in order to do this. I was hoping to not add the new machine (since for all intents and purposes it is similar to the `topoDualSocketMultiNumaPerSocketHT` we already have. The main difference being that it has 256 CPUs instead of 80, and 8 NUMA nodes instead of 4. As such, I was hoping to just reproduce this issue on the existing `topoDualSocketMultiNumaPerSocketHT`, but wasn't able to. If you think it's worthwhile, I can add this new machine with the test to reproduce this issue to the PR.

**Comment by fromanirh** [comment]
> To actually pinpoint this bug, I did, in fact reproduce the exact failure scenario it in a unit test. But I had to add a new machine that matched the live machine in order to do this. I was hoping to not add the new machine (since for all intents and purposes it is similar to the `topoDualSocketMultiNumaPerSocketHT` we already have. The main difference being that it has 256 CPUs instead of 80, and 8 NUMA nodes instead of 4. As such, I was hoping to just reproduce this issue on the existing `topoDualSocketMultiNumaPerSocketHT`, but wasn't able to. If you think it's worthwhile, I can add this new machine with the test to reproduce this issue to the PR.

I think it is important indeed to have this machine, because it allows to exercise a flow and verify the bug which (surprisingly?) we cannot do with """just""" 80 cores. But if this is the case, it can wait a followup PR.

**Comment by fromanirh** [comment]
/lgtm
codewise looks fine, it's low-to-none risk, fixes an actual bug, we have clarity about the test scenario and a path forward.
Won't merge automatically because ` Pending — Not mergeable. Must be in milestone v1.23. `

**Comment by swatisehgal** [comment]
> To actually pinpoint this bug, I did, in fact reproduce the exact failure scenario it in a unit test. But I had to add a new machine that matched the live machine in order to do this. I was hoping to not add the new machine (since for all intents and purposes it is similar to the `topoDualSocketMultiNumaPerSocketHT` we already have. The main difference being that it has 256 CPUs instead of 80, and 8 NUMA nodes instead of 4. As such, I was hoping to just reproduce this issue on the existing `topoDualSocketMultiNumaPerSocketHT`, but wasn't able to. If you think it's worthwhile, I can add this new machine with the test to reproduce this issue to the PR.

Very interesting indeed! Since, `topoDualSocketMultiNumaPerSocketHT` does not allow us to reproduce this issue, I believe its best we add the new machine with the test to go along with the fix here in this PR itself. This would help explain the rationale behind these changes better.

**Comment by fromanirh** [comment]
/lgtm cancel
because https://github.com/kubernetes/kubernetes/pull/106599#issuecomment-976517484

**Comment by klueska** [comment]
I will add the new machine with the test case soon.

In the meantime, I have added the test locally (along with some logging) to demonstrate the issue. This can be seen below.

TestCase:
```
        {
            "ensure bestRemainder chosen with NUMA nodes that have enough CPUs to satisfy the request",
            topoDualSocketMultiNumaPerSocketHTLarge,
            mustParseCPUSet(t, "0,128,30,31,158,159,43-47,171-175,62,63,190,191,75-79,203-207,94,96,222,223,101-111,229-239,126,127,254,255"),
            28,
            1,
            "",
            mustParseCPUSet(t, "..."),
        },
```

The available CPUs in this test case are:
```
Node 0: 0,128
Node 1: 30,31,158,159
Node 2: 43-47,171-175
Node 3: 62,63,190,191
Node 4: 75-79,203-207
Node 5: 94,96,222,223
Node 6: 101-111,229-239
Node 7: 126,127,254,255
```

The error we see is;
```
I1123 13:24:39.124891   87414 cpu_assignment.go:691] "bestCombo found" distribution=4 bestCombo=[1 3 2 7 4 6] bestRemainder=[1 2 4 6]

--- FAIL: TestTakeByTopologyNUMADistributed (0.01s)
    --- FAIL: TestTakeByTopologyNUMADistributed/Bug_reproduce (0.00s)
        cpu_assignment_test.go:837: unexpected error [accounting error, not enough CPUs allocated, remaining: 4]
```

From the log line you can see that:
```
distribution=4, bestCombo=[1 3 2 7 4 6], bestRemainder=[1 2 4 6]
```
With a total CPU allocation of 28 and a distribution of 4, this means that 24 CPUs are to be allocated across `bestCombo=[1 3 2 7 4 6] (with 4 CPUs coming from each) and the remaining 4 CPUs (i.e. 28 - 24) are to come from `bestRemainder=[1 2 4 6]` (with 1 CPU coming from each).

However, NUMA node 1 only has 4 CPUs to start with, so it is not possible to allocate an "extra" CPU from it for the remainder set after the first 4 CPUs have been allocated from it.

Adding the check that this PR introduces removes the possibility for Node 1 (or any similar nodes) from being considered for inclusion in the `bestRemainder` set. With this change in place, we see CPUs being allocated as:
```
0,11-15,37,64,75-79,101,128,139-143,165,192,203-207,229
```
which is basically the equivalent of *not* finding a `bestCombo` at all and just doing a "packed" allocation instead of a "distributed" one.

This is less than ideal, but at least it's not errorring out on an accounting error.

I have a feeling for why this might be happening, so I will dig into this a bit before publishing the next ireration of this PR.

**Comment by reylejano** [comment]
/milestone clear
Release Managers are cutting 1.23.0-rc.0 and creating the `release-1.23` branch

**Comment by klueska** [comment]
When debugging this issue, I found a number of bugs that have now been resolved as part of this PR. I am still not quite done with everything I want to do here, but it is getting closer. Since it seems it did not make the 1.23 test freeze, I will put this on /hold for the time being until we get all issues resolved and can cherry-pick it back for 1.23.1.

**Review by ffromani — COMMENTED** [review]
overall all looks good, but the fact that we had unit tests which passes while the logic was actually not correct calls for deeper review. I will allocate more time to look into this more deeply in the next couple days.

**Comment by klueska** [comment]
Im not done yet. There are at least 4 more commits that will come on too of this. I’ll let you know when it’s ready for review again.

**Comment by fromanirh** [comment]
> Im not done yet. There are at least 4 more commits that will come on too of this. I’ll let you know when it’s ready for review again.

Sure, and just to be clear, I meant my own review needs to be deeper. Issues like the wrong stddev computation may happen, but still let me try harder.

**Comment by klueska** [comment]
> Sure, and just to be clear, I meant my own review needs to be deeper. Issues like the wrong stddev computation may happen (EDIT: meaning: can slip past the review), but still let me try harder.

Actually the `stddev` calculation itself was correct -- the list of values passed into it was incorrect because of this:
```
 func (m mapIntInt) Values() []int {
-   values := make([]int, len(m))
+   var values []int
    for _, v := range m {
        values = append(values, v)
    }
```
The values arrays were then much longer than they should have been (front padded with 0s) becuase we fist initialized them to the size of `len(m)` and then appended to them.

Performing a `stddev` on one of these lists  then gave us a skewed result because of all the leading 0s. The result sort of looked correct on the surface without actually double checking inputs and the the results closely.

**Comment by klueska** [comment]
I have all of the code updates added now, but will rework the PR a bit and add more unit tests. Feel free to take a cursory look to begin with. The changes are best reviewed commit-by-commit with a detailed reading of each commit message.

**Comment by klueska** [comment]
OK. PR is now ready for review.

**Review by ffromani — COMMENTED** [review]
initial review. Looks good overall and the series is nicely laid to be as easy to review as possible.
However a number of issues fixed here could have been caught in the initial review (of mine) so I want to deep dive in the algorithm and and in the changes.

I think we aim for 1.23.1 anyway (out of necessity) so timing should not be a too pressing factor in this regard.

Last but not least, a fair amount of utility functions have been added. This is fine, and I don't think it's time yet to generalize them and/or move them outside the cpumanager package, but some focused unit testing of these can improve the code quality/reliabilty even more, at a very little cost (https://github.com/kubernetes/kubernetes/pull/106599/commits/4008ea0b4c1835152b587bd2cef7e313e6d2c452 comes to mind).

**Comment by klueska** [comment]
Thanks @fromanirh. I agree that more unit testing (especially of the utility functions) will be useful here. We have plans to move all of this logic to a subpackage (i.e. `cpuassignment`) to help clean some of this up in general. Maybe it makes sense to focus on the correctness of the algorithm for now and then move the code to a subpackage / add unit tests for the utility functions in a follow-on PR.

**Comment by fromanirh** [comment]
> Thanks @fromanirh. I agree that more unit testing (especially of the utility functions) will be useful here. We have plans to move all of this logic to a subpackage (i.e. `cpuassignment`) to help clean some of this up in general. Maybe it makes sense to focus on the correctness of the algorithm for now and then move the code to a subpackage / add unit tests for the utility functions in a follow-on PR.

On one hand I do agree that it makes sense to add these tests as part as the cleanup and code movement, which also I like and agree with, as prep work to graduate to beta or in general later.
On the other hand testing these utility functions also contributes to correctness to the algorithm, because we have more coverage and more trust in the algorithm building blocks.

Overall, adding more content to this PR considering again we aim for 1.23.1, is probably not a good idea, so better to defer these additions to the future cleanup PR, backporting fixes and their minimal test coverage if needed.

**Comment by fromanirh** [comment]
update: I expect to complete my review by (end of) December 10, worst case.

**Comment by fromanirh** [comment]
/lgtm
all my comments have been addressed, we have plans we all agree about for further cleanup and improvements. For example, I think we should review the logging to let cpumanager emit the attempts like we do in the tests; but this needs discussion (finding the right log level doesn't seem too easy) and there is no point to discuss in the context of this PR.

**Comment by swatisehgal** [comment]
/lgtm

Agree with @fromani that the PR is nicely laid out! Thanks for addressing the review comments and adding additional tests.

**Pull request merged**
