### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by lvjiangzhao**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by lvjiangzhao** [comment]
@dims all checks passed, please add lgtm label. Thx

**Comment by lvjiangzhao** [comment]
cc @smarterclayton

**Comment by wojtek-t** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by wojtek-t** [comment]
@k8s-bot pull-kubernetes-unit test this

**Pull request merged**
