### PR TITLE
Replace client with clientset

### PR DESCRIPTION
**Pull request by ingvagabund**
Replace client with clientset in some places

Fixes: #34637

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34905)

### CODE REVIEW

**Comment by caesarxuchao** [comment]
sub/

**Comment by caesarxuchao** [comment]
Thanks, @ingvagabund. The PR is quite large, it might be easier to review if you separate the "Replace client with clientset in code" commit to its own PR.

**Comment by ingvagabund** [comment]
@caesarxuchao I am building this PR over the #34138 so only the fourth one is relevant. Once #34138 gets merged I will rebase.

**Comment by deads2k** [comment]
> @caesarxuchao I am building this PR over the #34138 so only the fourth one is relevant. Once #34138 gets merged I will rebase.

Ping when its rebased.  I'm in favor of the change indicated by the title.

**Comment by ingvagabund** [comment]
@k8s-bot gci gke e2e test this

**Comment by ingvagabund** [comment]
@k8s-bot cvm gce e2e test this

**Comment by ingvagabund** [comment]
@kubernetes/rh-cluster-infra anyone willing to help with the review? A lot of changes in the code
@kubernetes/sig-api-machinery

Only the last commit is relevant, I will remove the first three once #34138 is merged.

**Comment by ingvagabund** [comment]
> > @caesarxuchao I am building this PR over the #34138 so only the fourth one is relevant. Once #34138 gets merged I will rebase.
> 
> Ping when its rebased. I'm in favor of the change indicated by the title.

@deads2k rebased, all test pass

**Comment by deads2k** [comment]
This is an old objective, bumping priority so it won't end up in rebase hell.

**Comment by ingvagabund** [comment]
@deads2k thanks

**Comment by ingvagabund** [comment]
@caesarxuchao anything else to do wrt. client -> clientset migration?

**Comment by deads2k** [comment]
> @caesarxuchao anything else to do wrt. client -> clientset migration?

Yeah, there are some stragglers.  I'm looking at it now.

**Comment by caesarxuchao** [comment]
This is cool. Thank you both.

**Pull request merged**
