### PR TITLE
[WIP] Convert Kubelet to use legacyflag

### PR DESCRIPTION
**Pull request by mtaufen**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This converts Kubelet flag registrations that target Kubelet's ComponentConfig type (KubeletConfiguration) to use the legacyflag approach. Flag registrations become more verbose, but enforcing "flag precedence" (#56171) when parsing various sources of KubeletConfiguration becomes much more straightforward, because we no longer have to re-parse the command-line multiple times (with careful logic to avoid unwanted side-effects). Instead, legacyflag lets us parse the command-line once, store values for flags that target KubeletConfiguration in a scratch space, and apply values from explicitly set flags onto multiple KubeletConfigurations with no risk of distant side-effects.

legacyflag: https://github.com/kubernetes-sigs/legacyflag
legacyflag KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190129-legacyflag.md

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/assign @liggitt @sttts
/cc @stealthybox 

PTAL when you have a chance. I'm only working on this as I have time, but fortunately had some time today to get this started.

### CODE REVIEW

**Comment by MonzElmasry** [comment]
Hello :wave: ! Bug triage here, This PR has not been updated for a long time, so I'd like to check what's the status. The code freeze is starting 12.11.2020 (about 2 weeks from now) and while there is still plenty of time, we want to ensure that each PR has a chance to be merged on time.

As the PR is tagged for 1.20, is it still planned for this release?

**Comment by mtaufen** [comment]
Whoops, thanks for the head's up! I untagged it from the milestone to avoid any confusion.

As this hasn't gotten traction I'm going to close it for now. It may still serve as a useful example if we come back to this in the future.

**Pull request closed without merging**
