### PR TITLE
Synchronize help message between describe and get

### PR DESCRIPTION
**Pull request by hurf**
small nits left by #10742, change 'resources' to 'resource types'

### CODE REVIEW

**Comment by hurf** [comment]
@erictune can you look at this? just a small nit left by previous patch.

**Comment by wojtek-t** [comment]
@hurf please rebase

**Comment by wojtek-t** [comment]
@hurf - can you please rebase?

**Comment by erictune** [comment]
lgtm

**Comment by hurf** [comment]
@wojtek-t rebased.

**Comment by piosz** [comment]
Shippable is flaky. Merging. Thanks for the change.

**Pull request merged**
