### PR TITLE
Add Readme.md for cluster/centos

### PR DESCRIPTION
**Pull request by xiaoping378**
**What this PR does / why we need it**:
add readme.md file, help beginner to start quickly.

**Which issue this PR fixes**
nothing

**Special notes for your reviewer**:
nothing

**Release note**:
`NONE`

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32554)

### CODE REVIEW

**Comment by roberthbailey** [comment]
lgtm

**Comment by xiaoping378** [comment]
Hi @roberthbailey,  can you merge it ?

**Comment by roberthbailey** [comment]
I thought a bot would do it after I added an lgtm comment... let me try a label.

**Comment by roberthbailey** [comment]
@kubernetes/test-infra-maintainers why is this being tested? It's labeled as retest-not-required.

**Comment by spxtr** [comment]
I think retest not required means it won't require a retest before merging, but the tests still need to pass for the latest commit.

**Comment by xiaoping378** [comment]
maybe in china, I can't access the [Build log](http://pr-test.k8s.io/32554/kubernetes-pull-build-test-e2e-gce/59450/build-log.txt),  I have deleted my forked k8s. this is failed reason ?
image

**Comment by roberthbailey** [comment]
@xiaoping378 can you squash your 3 commits into 1?

**Comment by xiaoping378** [comment]
@roberthbailey I have made a new PR #33069 .
The ``cluster/centos`` still exists some other issues. ... After finishing I will send the PR.

**Comment by roberthbailey** [comment]
Can we close this PR in favor of #33069?

**Pull request closed without merging**
