### PR TITLE
Update prometheus libraries to new versions.

### PR DESCRIPTION
**Pull request by timstclair**
This PR includes the changes from https://github.com/kubernetes/kubernetes/pull/14202 (fixes for https://github.com/kubernetes/kubernetes/issues/14159), and also fixes the regression introduced by that PR (and reverted in https://github.com/kubernetes/kubernetes/pull/14233)

cc/ @eparis @thockin @gmarek

### CODE REVIEW

**Comment by gmarek** [comment]
Shippable looks like flake.

**Comment by timstclair** [comment]
Friendly ping. Please let me know if I should reassign this.

**Comment by timstclair** [comment]
@karlkfi - FYI

**Comment by karlkfi** [comment]
hack/verify-godeps.sh needs an update to remove the Prometheus kludge there

**Comment by eparis** [comment]
totally missed this!

will look into the failures...

**Comment by timstclair** [comment]
Oh yeah, I thought I had updated hack/verify-godeps.sh in this PR - I'll add it.

**Comment by thockin** [comment]
status on this?

**Comment by timstclair** [comment]
Just waiting for a LGTM.

**Comment by gmarek** [comment]
@k8s-bot test this please

**Comment by thockin** [comment]
This does fix godeps (thanks).  It does not apply cleanly to release-1.1
and I am not sure what the right answer is.  Can you please try the cherry
pick and figure out what needs to be done?

**Comment by timstclair** [comment]
I bet the issue is a conflict with https://github.com/kubernetes/kubernetes/commit/3ae276cc0bebeca841a3003c9db3462d2b113693, which refactored some methods from `test/e2e/util.go` to a new file `test/e2e/metrics_util.go`. Should I just go through the process described [here](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md)?

**Comment by thockin** [comment]
metrics_util was, in fact, the conflict

But now that I know you don't know how to do it, I want you to do it even
more. :)  Yes, follow that doc, it's straight-forward

You can cherry pick both PRs at the same time, and it should be simple.

**Comment by timstclair** [comment]
Not so straight-forward :) Any idea what is wrong?

```
[master] ~/k8s$ hack/cherry_pick_pull.sh upstream/release-1.1 14827 14302
+++ Updating remotes...
Fetching origin
Fetching upstream
remote: Counting objects: 53, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 53 (delta 43), reused 45 (delta 35), pack-reused 0
Unpacking objects: 100% (53/53), done.
From https://github.com/kubernetes/kubernetes
   392f33e..3bbfe48  master     -> upstream/master
   16bb43d..458010e  release-1.1 -> upstream/release-1.1
+++ Creating local branch automated-cherry-pick-of-#14827-#14302-upstream-release-1.1-1444437556
Branch automated-cherry-pick-of-#14827-#14302-upstream-release-1.1-1444437556 set up to track remote branch release-1.1 from upstream.
Switched to a new branch 'automated-cherry-pick-of-#14827-#14302-upstream-release-1.1-1444437556'
+++ Downloading patch to /tmp/14827.patch (in case you need to do this again)

+++ About to attempt cherry pick of PR. To reattempt:
  $ git am -3 /tmp/14827.patch

Applying: Print latency metrics in too-friendly way.
+++ Downloading patch to /tmp/14302.patch (in case you need to do this again)

+++ About to attempt cherry pick of PR. To reattempt:
  $ git am -3 /tmp/14302.patch

Applying: Update prometheus libraries to new versions.

+++ I'm about to do the following to push to GitHub (and I'm assuming origin is your personal fork):

  git push origin automated-cherry-pick-of-#14827-#14302-upstream-release-1.1-1444437556:automated-cherry-pick-of-#14827-#14302-upstream-release-1.1

+++ Proceed (anything but 'y' aborts the cherry-pick)? [y/n] y
Counting objects: 128, done.
Delta compression using up to 12 threads.
Compressing objects: 100% (104/104), done.
Writing objects: 100% (128/128), 71.67 KiB | 0 bytes/s, done.
Total 128 (delta 55), reused 0 (delta 0)
To git@github.com:timstclair/kubernetes.git
 + c5806fe...b7f0467 automated-cherry-pick-of-#14827-#14302-upstream-release-1.1-1444437556 -> automated-cherry-pick-of-#14827-#14302-upstream-release-1.1 (forced update)
+++ Creating a pull request on github
Aborted: the origin remote doesn't point to a GitHub repository.

+++ Returning you to the master branch and cleaning up.

[master] ~/k8s$ git remote -v
origin	git@github.com:timstclair/kubernetes.git (fetch)
origin	git@github.com:timstclair/kubernetes.git (push)
upstream	https://github.com/kubernetes/kubernetes.git (fetch)
upstream	no_push (push)
```

It looks like an issue with `hub`, since I get the same problem trying to use that. I'll keep digging...

**Comment by timstclair** [comment]
Figured it out: https://github.com/kubernetes/kubernetes/pull/15419. It's just a partial failure (I think due to https://github.com/github/hub/issues/876), but the PR can still be created through the github UI (thanks roberthbailey)

**Pull request merged**
