### PR TITLE
kubelet: Remove GetRecentDockerContainersWithNameAndUUID.

### PR DESCRIPTION
**Pull request by yifan-gu**
Changed it to GetRecentContainersWithNameAndUUID, make it more generic.
Also replaced inspecting the containers in the function with parsing
the state from docker.ListContainer directly.

@vmarmol @dchen1107 @yujuhong

### CODE REVIEW

**Comment by yifan-gu** [comment]
Going to run the e2e, will report the result.

**Comment by vmarmol** [comment]
Thanks @yifan-gu! I think it's better to do the inspect though. Parsing the text status sounds brittle :( Is there a problem you're running into?

**Comment by yifan-gu** [comment]
@vmarmol, updated. Actually removed the GetRecentDockerContainersWithNameAndUUID.

**Comment by yujuhong** [comment]
LGTM overall! Leave it to @vmarmol for further feedback.

We should add/move tests accordingly after the refactoring is largely done :)

**Comment by yifan-gu** [comment]
@yujuhong Agree, I have checked all the fake docker calls and commented respectively in another PR:
https://github.com/GoogleCloudPlatform/kubernetes/pull/6169/files#diff-1e7657ffc53feeb1a99dd257a3ea303dR554

Think it will be more readable once this and that PR get merged :)

**Comment by vmarmol** [comment]
LGTM, thanks @yifan-gu!

**Comment by quinton-hoole** [comment]
It looks like this might be the cause of an e2e test regression in #6537

**Comment by yifan-gu** [comment]
@quinton-hoole 
Oops :( let me take a look

**Comment by quinton-hoole** [comment]
Thanks Yifan. I've confirmed on a local branch and test cluster that reverting this commit fixes the test.  I'm going to revert it in upstream/master now.

It would be great if you could fix it and confirm that the e2e test succeeds before resubmitting.  Feel free to assign to me for review.

**Comment by yifan-gu** [comment]
@quinton-hoole NP. Sorry abt the flaky test :(  I think I have fixed that bug, e2e is passing on my machine. But I am going to add some unit tests to exercising the restart policy (Surprisingly there is nothing testing that...) Will poke you when ready :)

**Comment by yujuhong** [comment]
@yifan-gu, just saw your latest comment, and seems like you've already figured out the problem. Since I've already typed up my comment, I'd still paste it anyway.

---

@yifan-gu, the problem here is that you are using a "cached" pod status which will always have state == Running because it was written right after the last sync. This caused your if statement (`if containerStatus.Name == container.Name && containerStatus.State.Termination`) to *always* fail. Since the function always returns true, kubelet would restart the dead container even though restartPolicy == Never. Kubelet should be careful when relying on the status cache like this....we need to make this more clear.

To reproduce this bug, you can simply create a pod with restart policy == never, kill the container of the pod, and watch whether kubelet would restart your container. In general, we should add some tests for restart=never pods in integration test, so that such errors are caught earlier (instead of relying on the logging e2e test for this).

**Comment by yifan-gu** [comment]
@yujuhong Thank you very much! I found the same conclusion. I just replaced with the uncached one. Also move it outside of the `if pod infra container != nil` sentence.

**Comment by yifan-gu** [comment]
@yujuhong Or you think there is some better way? I will think about it tonight.

**Pull request merged**
