### PR TITLE
Automated cherry pick of #103733 upstream release 1.21 

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #103697

```release-note
NONE
```

/kind bug
/priority important-soon
/sig cloud-provider

### CODE REVIEW

**Comment by wojtek-t** [comment]
cc @kubernetes/release-managers @cpanato 

this is needed to make 1.21 → 1.22 master upgrade test jobs pass again (only cluster upgrade was fixed by the previous PR)
would it be possible to have it approved?

**Review by cpanato — APPROVED** [review]
from RelEng:
/lgtm

**Pull request merged**
