### PR TITLE
remove legacy NetworkPolicy tests

### LINKED ISSUE #114389: We forgot to remove the old netpol tests that are covered by new matrix based tests
### What happened?

  we can follow up on https://github.com/kubernetes/kubernetes/pull/102933 now, by finishing removing all but the SCTP tests in the old legacy filters.

### What did you expect to happen?

we would have removed the old tests by now :) but we didnt wanna break OVN .  I think OVN CI is passing now w/ the new tests though so we're good ! 

### How can we reproduce it (as minimally and precisely as possible)?

NA

### Anything else we need to know?

_No response_

### Kubernetes version

main

### Cloud provider

all

### OS version

all

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by astoycos**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This PR removes the legacy network policy tests and NetworkPolicy API tests (which were duplicated within `network_policy_api.go`) from `network_legacy.go`, intentionally leaving the [Feature:SCTPConnectivity] tests which don't have coverage in the new netpol suite.

#### Which issue(s) this PR fixes:

Fixes #114389

#### Does this PR introduce a user-facing change?

```release-note
The NetworkPolicyLegacy test suite (deprecated in v1.21) has now officially been removed in favor of the new table driven e2e tests.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by astoycos** [comment]
/sig/network

**Comment by astoycos** [comment]
/assign @jayunit100 

cc @danwinship 

I'm thinking this is the right short term action to take here... But ultimately all the tests from `network_legacy.go` should be converted to truth table tests OR just moved into `network_policy.go` right?

**Comment by jayunit100** [comment]
yeah sure.  We can convert the SCTP ones over after this , ill do that unless someone else wants to take it up.

**Comment by astoycos** [comment]
I'm happy to do it @jayunit100! I'll probably just need some pointers 👍

**Comment by aojea** [comment]
/approve

please add a release note indicating these tests are removed and replaced by the ... ones

@danwinship or Jay for final LGTM

**Comment by danwinship** [comment]
> intentionally leaving the [Feature:SCTPConnectivity] tests which don't have coverage in the new netpol suite.

that was true at one point but appears to have been fixed by #97897

**Comment by astoycos** [comment]
Yep thanks I just double checked @danwinship looks like we can remove the legacy one in it's entirety 🥳

**Comment by danwinship** [comment]
/lgtm
/approve
whew! finally!

**Comment by aojea** [comment]
Kubernetes e2e suite: [It] [sig-apps] StatefulSet Basic StatefulSet functionality [StatefulSetBasic] Should recreate evicted statefulset [Conformance] expand_more	8s
Kubernetes e2e suite: [It] [sig-api-machinery] Watchers should observe an object deletion if it stops meeting the requirements of the selector [Conformance] expand_more
/test pull-kubernetes-conformance-kind-ipv6-parallel 


@astoycos the release note is missing

> Should not have do-not-merge/release-note-label-needed label.

**Comment by astoycos** [comment]
Ah sorry @aojea I thought it was in like a follow up issue or something, doing it now 👍

**Pull request merged**
