### PR TITLE
Handle condition where minion cbr0 interface is up, but not yet readdressed, when vSphere script sets up cluster networking

### LINKED ISSUE #31310: Following Getting Started Guide for vSphere results in incomplete Pod network routes on minion nodes
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Kubernetes version** (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:29:08Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:21:58Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: VMware vSphere 5.5
- **OS** (e.g. from /etc/os-release): Debian 8 jessie (via kube.vmdk referenced by Getting Started Guide)
- **Kernel** (e.g. `uname -a`): Linux kubernetes-minion-1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u2 (2016-01-02) x86_64 GNU/Linux
- **Install tools**: bundled cluster/kube-up.sh script 
- **Others**:

**What happened**: Following the 'Getting Started' guide exactly results in successful deployment of 1 master and 4 minion machines in vSphere, however the first three minions lack the ip routing table entry necessary to reach the pod network on the 4th minion (ie. 10.244.3.0/24).

Editing cluster/vsphere/config-default.sh and Increasing NUM_NODES to a higher value, such as 8, also results in the expected 8 minions however as previously minions 1 through 7 are missing the IP routing table for the pod network on the 8th minion (ie. 10.244.7.0/24).

Manually ssh'ing in and adding the missing route on all the appropriate minions restores the correct behavior of the cluster.

**What you expected to happen**:

Each minion must have routing table entries for the pod networks of all other minions in the cluster, otherwise Bad Things(tm) will happen.

**How to reproduce it** (as minimally and precisely as possible):

Exactly follow the quickstart documentation at http://kubernetes.io/docs/getting-started-guides/vsphere/

**Anything else do we need to know**:

Console logs and routing table inspection of resulting minion nodes are attached below for deployment of both a 4 node and a separate 8 node cluster.

root@kubernetes-console:~/kubernetes# cat cluster/vsphere/config-default.sh | grep NUM_NODES
NUM_NODES=4

root@kubernetes-console:~/kubernetes# KUBERNETES_PROVIDER=vsphere cluster/kube-up.sh
... Starting cluster using provider: vsphere
... calling verify-prereqs
... calling kube-up
Identity added: /root/.ssh/id_rsa (rsa w/o comment)
Starting master VM (this can take a minute)...
kubernetes-server-linux-amd64.tar.gz                                                                                                                                100%  351MB 175.7MB/s   00:02
kubernetes-salt.tar.gz                                                                                                                                              100%   45KB  44.6KB/s   00:00
uploaded /tmp/kubernetes.q1La14/master-start.sh to /tmp/master-start.sh
Using master: kubernetes-master (external IP: 172.16.6.156)

Starting node VMs (this can take a minute)...
uploaded /tmp/kubernetes.q1La14/node-start-3.sh to /tmp/node-start-3.sh
uploaded /tmp/kubernetes.q1La14/node-start-0.sh to /tmp/node-start-0.sh
uploaded /tmp/kubernetes.q1La14/node-start-1.sh to /tmp/node-start-1.sh
uploaded /tmp/kubernetes.q1La14/node-start-2.sh to /tmp/node-start-2.sh
Found kubernetes-minion-1 at 172.16.6.141
Found kubernetes-minion-2 at 172.16.6.169
Found kubernetes-minion-3 at 172.16.6.217
Found kubernetes-minion-4 at 172.16.6.137
Waiting for salt-master to be up on kubernetes-master ...
This may take several minutes. Bound to 60 attempts........
[salt-master running]

Waiting for all packages to be installed on kubernetes-master ...

This may take several minutes. Bound to 60 attempts...................
[sudo salt "kubernetes-master" state.highstate -t 30 | grep -E "Failed:[[:space:]]+0"] passed

Waiting for salt-minion to be up on kubernetes-minion-1 ....
This may take several minutes. Bound to 60 attempts
[salt-minion running]

Waiting for all salt packages to be installed on kubernetes-minion-1 ....

This may take several minutes. Bound to 60 attempts
[sudo salt kubernetes-minion-1 state.highstate -t 30 | grep -E "Failed:[[:space:]]+0"] passed

 OK
Waiting for salt-minion to be up on kubernetes-minion-2 ....
This may take several minutes. Bound to 60 attempts
[salt-minion running]

Waiting for all salt packages to be installed on kubernetes-minion-2 ....

This may take several minutes. Bound to 60 attempts
[sudo salt kubernetes-minion-2 state.highstate -t 30 | grep -E "Failed:[[:space:]]+0"] passed

 OK
Waiting for salt-minion to be up on kubernetes-minion-3 ....
This may take several minutes. Bound to 60 attempts
[salt-minion running]

Waiting for all salt packages to be installed on kubernetes-minion-3 ....

This may take several minutes. Bound to 60 attempts
[sudo salt kubernetes-minion-3 state.highstate -t 30 | grep -E "Failed:[[:space:]]+0"] passed

 OK
Waiting for salt-minion to be up on kubernetes-minion-4 ....
This may take several minutes. Bound to 60 attempts
[salt-minion running]

Waiting for all salt packages to be installed on kubernetes-minion-4 ....

This may take several minutes. Bound to 60 attempts
[sudo salt kubernetes-minion-4 state.highstate -t 30 | grep -E "Failed:[[:space:]]+0"] passed

 OK

Waiting for master and node initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This might loop forever if there was some uncaught error during start up.

 OK
Waiting for kubernetes-minion-1 to become available... OK
Waiting for kubernetes-minion-2 to become available... OK
Waiting for kubernetes-minion-3 to become available... OK
Waiting for kubernetes-minion-4 to become available... OK
Setting up routes
check if cbr0 bridge is ready on kubernetes-minion-1

This may take several minutes. Bound to 60 attempts
[sudo ifconfig cbr0 | grep -oP "inet addr:\K\S+"] passed

check if cbr0 bridge is ready on kubernetes-minion-2

This may take several minutes. Bound to 60 attempts
[sudo ifconfig cbr0 | grep -oP "inet addr:\K\S+"] passed

check if cbr0 bridge is ready on kubernetes-minion-3

This may take several minutes. Bound to 60 attempts
[sudo ifconfig cbr0 | grep -oP "inet addr:\K\S+"] passed

check if cbr0 bridge is ready on kubernetes-minion-4

This may take several minutes. Bound to 60 attempts
[sudo ifconfig cbr0 | grep -oP "inet addr:\K\S+"] passed

 finding network of cbr0 bridge on node  kubernetes-minion-1
 finding network of cbr0 bridge on node  kubernetes-minion-2
 finding network of cbr0 bridge on node  kubernetes-minion-3
 finding network of cbr0 bridge on node  kubernetes-minion-4
setting up routes for kubernetes-minion-1setting up routes for kubernetes-minion-2setting up routes for kubernetes-minion-3setting up routes for kubernetes-minion-4Kubernetes cluster created.
cluster "vsphere_kubernetes" set.
user "vsphere_kubernetes" set.
context "vsphere_kubernetes" set.
switched to context "vsphere_kubernetes".
Wrote config for vsphere_kubernetes to /root/.kube/config

Sanity checking cluster...

Kubernetes cluster is running. The master is running at:

  https://172.16.6.156

The user name and password to use is located in /root/.kube/config

... calling validate-cluster
Waiting for 4 ready nodes. 3 ready nodes, 4 registered. Retrying.
Waiting for 4 ready nodes. 3 ready nodes, 4 registered. Retrying.
Found 4 node(s).
NAME           STATUS    AGE
172.16.6.137   Ready     36s
172.16.6.141   Ready     2m
172.16.6.169   Ready     2m
172.16.6.217   Ready     1m
Validate output:
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok
scheduler            Healthy   ok
etcd-1               Healthy   {"health": "true"}
etcd-0               Healthy   {"health": "true"}
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at https://172.16.6.156
KubeDNS is running at https://172.16.6.156/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://172.16.6.156/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'
# 

kube@kubernetes-minion-1:~$ ip ro sh
default via 172.16.6.1 dev eth0
10.244.0.0/24 dev cbr0  proto kernel  scope link  src 10.244.0.1
10.244.1.0/24 via 172.16.6.169 dev eth0
10.244.2.0/24 via 172.16.6.217 dev eth0
172.16.6.0/24 dev eth0  proto kernel  scope link  src 172.16.6.141
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
172.18.0.0/16 via 172.16.6.137 dev eth0
# 

kube@kubernetes-minion-2:~$ ip ro sh
default via 172.16.6.1 dev eth0
10.244.0.0/24 via 172.16.6.141 dev eth0
10.244.1.0/24 dev cbr0  proto kernel  scope link  src 10.244.1.1
10.244.2.0/24 via 172.16.6.217 dev eth0
172.16.6.0/24 dev eth0  proto kernel  scope link  src 172.16.6.169
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
172.18.0.0/16 via 172.16.6.137 dev eth0
# 

kube@kubernetes-minion-3:~$ ip ro sh
default via 172.16.6.1 dev eth0
10.244.0.0/24 via 172.16.6.141 dev eth0
10.244.1.0/24 via 172.16.6.169 dev eth0
10.244.2.0/24 dev cbr0  proto kernel  scope link  src 10.244.2.1
172.16.6.0/24 dev eth0  proto kernel  scope link  src 172.16.6.217
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
172.18.0.0/16 via 172.16.6.137 dev eth0
# 

kube@kubernetes-minion-4:~$ ip ro sh
default via 172.16.6.1 dev eth0
10.244.0.0/24 via 172.16.6.141 dev eth0
10.244.1.0/24 via 172.16.6.169 dev eth0
10.244.2.0/24 via 172.16.6.217 dev eth0
10.244.3.0/24 dev cbr0  proto kernel  scope link  src 10.244.3.1
172.16.6.0/24 dev eth0  proto kernel  scope link  src 172.16.6.137
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
# 

root@kubernetes-console:~/kubernetes# cat cluster/vsphere/config-default.sh | grep NUM_NODES
NUM_NODES=8

root@kubernetes-console:~/kubernetes# KUBERNETES_PROVIDER=vsphere cluster/kube-up.sh
... Starting cluster using provider: vsphere
... calling verify-prereqs
... calling kube-up
Identity added: /root/.ssh/id_rsa (rsa w/o comment)
Starting master VM (this can take a minute)...
kubernetes-server-linux-amd64.tar.gz                                                                                                                                100%  351MB 117.1MB/s   00:03
kubernetes-salt.tar.gz                                                                                                                                              100%   45KB  44.6KB/s   00:00
uploaded /tmp/kubernetes.3bDOMi/master-start.sh to /tmp/master-start.sh
Using master: kubernetes-master (external IP: 172.16.6.158)

Starting node VMs (this can take a minute)...
uploaded /tmp/kubernetes.3bDOMi/node-start-4.sh to /tmp/node-start-4.sh
uploaded /tmp/kubernetes.3bDOMi/node-start-7.sh to /tmp/node-start-7.sh
uploaded /tmp/kubernetes.3bDOMi/node-start-5.sh to /tmp/node-start-5.sh
uploaded /tmp/kubernetes.3bDOMi/node-start-0.sh to /tmp/node-start-0.sh
uploaded /tmp/kubernetes.3bDOMi/node-start-2.sh to /tmp/node-start-2.sh
uploaded /tmp/kubernetes.3bDOMi/node-start-6.sh to /tmp/node-start-6.sh
uploaded /tmp/kubernetes.3bDOMi/node-start-3.sh to /tmp/node-start-3.sh
uploaded /tmp/kubernetes.3bDOMi/node-start-1.sh to /tmp/node-start-1.sh
Found kubernetes-minion-1 at 172.16.6.239
Found kubernetes-minion-2 at 172.16.6.130
Found kubernetes-minion-3 at 172.16.6.124
Found kubernetes-minion-4 at 172.16.6.198
Found kubernetes-minion-5 at 172.16.6.84
Found kubernetes-minion-6 at 172.16.6.160
Found kubernetes-minion-7 at 172.16.6.208
Found kubernetes-minion-8 at 172.16.6.98
Waiting for salt-master to be up on kubernetes-master ...
This may take several minutes. Bound to 60 attempts..........
[salt-master running]

Waiting for all packages to be installed on kubernetes-master ...

This may take several minutes. Bound to 60 attempts.......................
[sudo salt "kubernetes-master" state.highstate -t 30 | grep -E "Failed:[[:space:]]+0"] passed

Waiting for salt-minion to be up on kubernetes-minion-1 ....
This may take several minutes. Bound to 60 attempts
[salt-minion running]

Waiting for all salt packages to be installed on kubernetes-minion-1 ....

This may take several minutes. Bound to 60 attempts
[sudo salt kubernetes-minion-1 state.highstate -t 30 | grep -E "Failed:[[:space:]]+0"] passed

 OK
Waiting for salt-minion to be up on kubernetes-minion-2 ....
This may take several minutes. Bound to 60 attempts
[salt-minion running]

Waiting for all salt packages to be installed on kubernetes-minion-2 ....

This may take several minutes. Bound to 60 attempts
[sudo salt kubernetes-minion-2 state.highstate -t 30 | grep -E "Failed:[[:space:]]+0"] passed

 OK
Waiting for salt-minion to be up on kubernetes-minion-3 ....
This may take several minutes. Bound to 60 attempts
[salt-minion running]

Waiting for all salt packages to be installed on kubernetes-minion-3 ....

This may take several minutes. Bound to 60 attempts
[sudo salt kubernetes-minion-3 state.highstate -t 30 | grep -E "Failed:[[:space:]]+0"] passed

 OK
Waiting for salt-minion to be up on kubernetes-minion-4 ....
This may take several minutes. Bound to 60 attempts
[salt-minion running]

Waiting for all salt packages to be installed on kubernetes-minion-4 ....

This may take several minutes. Bound to 60 attempts
[sudo salt kubernetes-minion-4 state.highstate -t 30 | grep -E "Failed:[[:space:]]+0"] passed

 OK
Waiting for salt-minion to be up on kubernetes-minion-5 ....
This may take several minutes. Bound to 60 attempts
[salt-minion running]

Waiting for all salt packages to be installed on kubernetes-minion-5 ....

This may take several minutes. Bound to 60 attempts
[sudo salt kubernetes-minion-5 state.highstate -t 30 | grep -E "Failed:[[:space:]]+0"] passed

 OK
Waiting for salt-minion to be up on kubernetes-minion-6 ....
This may take several minutes. Bound to 60 attempts
[salt-minion running]

Waiting for all salt packages to be installed on kubernetes-minion-6 ....

This may take several minutes. Bound to 60 attempts
[sudo salt kubernetes-minion-6 state.highstate -t 30 | grep -E "Failed:[[:space:]]+0"] passed

 OK
Waiting for salt-minion to be up on kubernetes-minion-7 ....
This may take several minutes. Bound to 60 attempts
[salt-minion running]

Waiting for all salt packages to be installed on kubernetes-minion-7 ....

This may take several minutes. Bound to 60 attempts
[sudo salt kubernetes-minion-7 state.highstate -t 30 | grep -E "Failed:[[:space:]]+0"] passed

 OK
Waiting for salt-minion to be up on kubernetes-minion-8 ....
This may take several minutes. Bound to 60 attempts
[salt-minion running]

Waiting for all salt packages to be installed on kubernetes-minion-8 ....

This may take several minutes. Bound to 60 attempts
[sudo salt kubernetes-minion-8 state.highstate -t 30 | grep -E "Failed:[[:space:]]+0"] passed

 OK

Waiting for master and node initialization.

  This will continually check to see if the API for kubernetes is reachable.
  This might loop forever if there was some uncaught error during start up.

 OK
Waiting for kubernetes-minion-1 to become available... OK
Waiting for kubernetes-minion-2 to become available... OK
Waiting for kubernetes-minion-3 to become available... OK
Waiting for kubernetes-minion-4 to become available... OK
Waiting for kubernetes-minion-5 to become available... OK
Waiting for kubernetes-minion-6 to become available... OK
Waiting for kubernetes-minion-7 to become available... OK
Waiting for kubernetes-minion-8 to become available... OK
Setting up routes
check if cbr0 bridge is ready on kubernetes-minion-1

This may take several minutes. Bound to 60 attempts
[sudo ifconfig cbr0 | grep -oP "inet addr:\K\S+"] passed

check if cbr0 bridge is ready on kubernetes-minion-2

This may take several minutes. Bound to 60 attempts
[sudo ifconfig cbr0 | grep -oP "inet addr:\K\S+"] passed

check if cbr0 bridge is ready on kubernetes-minion-3

This may take several minutes. Bound to 60 attempts
[sudo ifconfig cbr0 | grep -oP "inet addr:\K\S+"] passed

check if cbr0 bridge is ready on kubernetes-minion-4

This may take several minutes. Bound to 60 attempts
[sudo ifconfig cbr0 | grep -oP "inet addr:\K\S+"] passed

check if cbr0 bridge is ready on kubernetes-minion-5

This may take several minutes. Bound to 60 attempts
[sudo ifconfig cbr0 | grep -oP "inet addr:\K\S+"] passed

check if cbr0 bridge is ready on kubernetes-minion-6

This may take several minutes. Bound to 60 attempts
[sudo ifconfig cbr0 | grep -oP "inet addr:\K\S+"] passed

check if cbr0 bridge is ready on kubernetes-minion-7

This may take several minutes. Bound to 60 attempts
[sudo ifconfig cbr0 | grep -oP "inet addr:\K\S+"] passed

check if cbr0 bridge is ready on kubernetes-minion-8

This may take several minutes. Bound to 60 attempts
[sudo ifconfig cbr0 | grep -oP "inet addr:\K\S+"] passed

 finding network of cbr0 bridge on node  kubernetes-minion-1
 finding network of cbr0 bridge on node  kubernetes-minion-2
 finding network of cbr0 bridge on node  kubernetes-minion-3
 finding network of cbr0 bridge on node  kubernetes-minion-4
 finding network of cbr0 bridge on node  kubernetes-minion-5
 finding network of cbr0 bridge on node  kubernetes-minion-6
 finding network of cbr0 bridge on node  kubernetes-minion-7
 finding network of cbr0 bridge on node  kubernetes-minion-8
setting up routes for kubernetes-minion-1setting up routes for kubernetes-minion-2setting up routes for kubernetes-minion-3setting up routes for kubernetes-minion-4setting up routes for kubernetes-minion-5setting up routes for kubernetes-minion-6setting up routes for kubernetes-minion-7setting up routes for kubernetes-minion-8Kubernetes cluster created.
cluster "vsphere_kubernetes" set.
user "vsphere_kubernetes" set.
context "vsphere_kubernetes" set.
switched to context "vsphere_kubernetes".
Wrote config for vsphere_kubernetes to /root/.kube/config

Sanity checking cluster...

Kubernetes cluster is running. The master is running at:

  https://172.16.6.158

The user name and password to use is located in /root/.kube/config

... calling validate-cluster
Waiting for 8 ready nodes. 7 ready nodes, 8 registered. Retrying.
Waiting for 8 ready nodes. 7 ready nodes, 8 registered. Retrying.
Found 8 node(s).
NAME           STATUS    AGE
172.16.6.124   Ready     4m
172.16.6.130   Ready     4m
172.16.6.160   Ready     2m
172.16.6.198   Ready     3m
172.16.6.208   Ready     1m
172.16.6.239   Ready     5m
172.16.6.84    Ready     2m
172.16.6.98    Ready     42s
Validate output:
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok
scheduler            Healthy   ok
etcd-1               Healthy   {"health": "true"}
etcd-0               Healthy   {"health": "true"}
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at https://172.16.6.158
KubeDNS is running at https://172.16.6.158/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://172.16.6.158/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

Found kubernetes-minion-1 at 172.16.6.239
Found kubernetes-minion-2 at 172.16.6.130
Found kubernetes-minion-3 at 172.16.6.124
Found kubernetes-minion-4 at 172.16.6.198
Found kubernetes-minion-5 at 172.16.6.84
Found kubernetes-minion-6 at 172.16.6.160
Found kubernetes-minion-7 at 172.16.6.208
Found kubernetes-minion-8 at 172.16.6.98
# 

kube@kubernetes-minion-1:~$ ip ro sh
default via 172.16.6.1 dev eth0
10.244.0.0/24 dev cbr0  proto kernel  scope link  src 10.244.0.1
10.244.1.0/24 via 172.16.6.130 dev eth0
10.244.2.0/24 via 172.16.6.124 dev eth0
10.244.3.0/24 via 172.16.6.198 dev eth0
10.244.4.0/24 via 172.16.6.84 dev eth0
10.244.5.0/24 via 172.16.6.160 dev eth0
10.244.6.0/24 via 172.16.6.208 dev eth0
172.16.6.0/24 dev eth0  proto kernel  scope link  src 172.16.6.239
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
172.18.0.0/16 via 172.16.6.98 dev eth0
# 

kube@kubernetes-minion-2:~$ ip ro sh
default via 172.16.6.1 dev eth0
10.244.0.0/24 via 172.16.6.239 dev eth0
10.244.1.0/24 dev cbr0  proto kernel  scope link  src 10.244.1.1
10.244.2.0/24 via 172.16.6.124 dev eth0
10.244.3.0/24 via 172.16.6.198 dev eth0
10.244.4.0/24 via 172.16.6.84 dev eth0
10.244.5.0/24 via 172.16.6.160 dev eth0
10.244.6.0/24 via 172.16.6.208 dev eth0
172.16.6.0/24 dev eth0  proto kernel  scope link  src 172.16.6.130
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
172.18.0.0/16 via 172.16.6.98 dev eth0
# 

kube@kubernetes-minion-3:~$ ip ro sh
default via 172.16.6.1 dev eth0
10.244.0.0/24 via 172.16.6.239 dev eth0
10.244.1.0/24 via 172.16.6.130 dev eth0
10.244.2.0/24 dev cbr0  proto kernel  scope link  src 10.244.2.1
10.244.3.0/24 via 172.16.6.198 dev eth0
10.244.4.0/24 via 172.16.6.84 dev eth0
10.244.5.0/24 via 172.16.6.160 dev eth0
10.244.6.0/24 via 172.16.6.208 dev eth0
172.16.6.0/24 dev eth0  proto kernel  scope link  src 172.16.6.124
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
172.18.0.0/16 via 172.16.6.98 dev eth0
# 

kube@kubernetes-minion-4:~$ ip ro sh
default via 172.16.6.1 dev eth0
10.244.0.0/24 via 172.16.6.239 dev eth0
10.244.1.0/24 via 172.16.6.130 dev eth0
10.244.2.0/24 via 172.16.6.124 dev eth0
10.244.3.0/24 dev cbr0  proto kernel  scope link  src 10.244.3.1
10.244.4.0/24 via 172.16.6.84 dev eth0
10.244.5.0/24 via 172.16.6.160 dev eth0
10.244.6.0/24 via 172.16.6.208 dev eth0
172.16.6.0/24 dev eth0  proto kernel  scope link  src 172.16.6.198
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
172.18.0.0/16 via 172.16.6.98 dev eth0
# 

kube@kubernetes-minion-5:~$ ip ro sh
default via 172.16.6.1 dev eth0
10.244.0.0/24 via 172.16.6.239 dev eth0
10.244.1.0/24 via 172.16.6.130 dev eth0
10.244.2.0/24 via 172.16.6.124 dev eth0
10.244.3.0/24 via 172.16.6.198 dev eth0
10.244.4.0/24 dev cbr0  proto kernel  scope link  src 10.244.4.1
10.244.5.0/24 via 172.16.6.160 dev eth0
10.244.6.0/24 via 172.16.6.208 dev eth0
172.16.6.0/24 dev eth0  proto kernel  scope link  src 172.16.6.84
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
172.18.0.0/16 via 172.16.6.98 dev eth0
# 

kube@kubernetes-minion-6:~$ ip ro sh
default via 172.16.6.1 dev eth0
10.244.0.0/24 via 172.16.6.239 dev eth0
10.244.1.0/24 via 172.16.6.130 dev eth0
10.244.2.0/24 via 172.16.6.124 dev eth0
10.244.3.0/24 via 172.16.6.198 dev eth0
10.244.4.0/24 via 172.16.6.84 dev eth0
10.244.5.0/24 dev cbr0  proto kernel  scope link  src 10.244.5.1
10.244.6.0/24 via 172.16.6.208 dev eth0
172.16.6.0/24 dev eth0  proto kernel  scope link  src 172.16.6.160
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
172.18.0.0/16 via 172.16.6.98 dev eth0
# 

kube@kubernetes-minion-7:~$ ip ro sh
default via 172.16.6.1 dev eth0
10.244.0.0/24 via 172.16.6.239 dev eth0
10.244.1.0/24 via 172.16.6.130 dev eth0
10.244.2.0/24 via 172.16.6.124 dev eth0
10.244.3.0/24 via 172.16.6.198 dev eth0
10.244.4.0/24 via 172.16.6.84 dev eth0
10.244.5.0/24 via 172.16.6.160 dev eth0
10.244.6.0/24 dev cbr0  proto kernel  scope link  src 10.244.6.1
172.16.6.0/24 dev eth0  proto kernel  scope link  src 172.16.6.208
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1
172.18.0.0/16 via 172.16.6.98 dev eth0
# 

kube@kubernetes-minion-8:~$ ip ro sh
default via 172.16.6.1 dev eth0
10.244.0.0/24 via 172.16.6.239 dev eth0
10.244.1.0/24 via 172.16.6.130 dev eth0
10.244.2.0/24 via 172.16.6.124 dev eth0
10.244.3.0/24 via 172.16.6.198 dev eth0
10.244.4.0/24 via 172.16.6.84 dev eth0
10.244.5.0/24 via 172.16.6.160 dev eth0
10.244.6.0/24 via 172.16.6.208 dev eth0
10.244.7.0/24 dev cbr0  proto kernel  scope link  src 10.244.7.1
172.16.6.0/24 dev eth0  proto kernel  scope link  src 172.16.6.98
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1

### PR DESCRIPTION
**Pull request by kb1ca**
**What this PR does / why we need it**: Resolves bug reported in https://github.com/kubernetes/kubernetes/issues/31310

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #31310

**Special notes for your reviewer**: 

**Release note**: `NONE`

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31672)

### CODE REVIEW

**Comment by imkin** [comment]
@zmerlynn I can verify this fix for you. Do you need any different help for this?

**Comment by zmerlynn** [comment]
I just haven't seen it in a while, sorry for the delay.

@k8s-bot test this

**Comment by zmerlynn** [comment]
The CNCF CLA issue has to be resolved. You should squash the commits anyways, so if you fix the CLA issues and squash, it should tickle the bot.

**Comment by kerneltime** [comment]
@zmerlynn I am including a fix for the issue here with updates in a PR that is in the works. Will update this PR when it is posted.
@kb1ca Thank you for root causing and posting this PR.

**Comment by kerneltime** [comment]
@zmerlynn posted https://github.com/kubernetes/kubernetes/pull/35232

**Pull request closed without merging**
