### PR TITLE
e2e_kubeadm: clean up non-recommended import

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
e2e_kubeadm: clean up non-recommended import
We have done a lot of work to clean up code like this in `test/e2e`.
Ref: #74512

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
@SataQiu 
the change SGTM.
does the e2e_kubeadm package fail golint?

**Comment by SataQiu** [comment]
Yes. But this PR can not address golint problem completely as the package name contains '_'.

**Comment by SataQiu** [comment]
I'm not sure it's worthy to change the package name to make golint pass.

**Comment by neolit123** [comment]
> Yes. But this PR can not address golint problem completely as the package name contains '_'.

ok, thanks.
we may have to fix this eventually, but let's not send PRs yet.

/lgtm
/approve
/priority backlog

**Pull request merged**
