### PR TITLE
Print human readable times in 'kubectl'

### LINKED ISSUE #12280: Human readable times in `kubectl`
Instead of:
```console
$ kubectl get events
FIRSTSEEN                         LASTSEEN                          COUNT     NAME          KIND      SUBOBJECT   REASON             SOURCE         MESSAGE
Tue, 21 Jul 2015 16:25:06 -0700   Wed, 05 Aug 2015 08:56:09 -0700   416805    frontend4     Pod                   failedScheduling   {scheduler }   Failed for reason MatchNodeSelector and possibly others
```
let's print
```console
$ kubectl get events
FIRSTSEEN        LASTSEEN         COUNT     NAME          KIND      SUBOBJECT   REASON             SOURCE         MESSAGE
15 days ago      30 seconds ago   416805    frontend4     Pod                   failedScheduling   {scheduler }   Failed for reason MatchNodeSelector and possibly others
```

That save about 30 characters of width.  We could have a flag like `--machine-readable-time` or something to enable the old behavior.  Default to the new.

We could use https://gowalker.org/github.com/dustin/go-humanize or just write a 20 line function that specifically handles humanized time printing.

### PR DESCRIPTION
**Pull request by hurf**
Closes #12280

Use github.com/dunstin/go-humanize to format time to a more
human friendly format.

Added --machine-readable option for 'get' and 'describe' command
to keep the old style(old style is more precise)

### CODE REVIEW

**Comment by hurf** [comment]
@erictune - I used 'dustin/go-humanize' to implement this. It's more generic and can handle other units. But the unit it's using is not short enough, other person may have different ideas. To solve this problem, we can
1. create a PR to 'dustin/go-humanize' to enable shorter display
2. In existing code there's a function:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L363
and before we use this to translate time to human readable format. We can still use this function.

After we have a conclusion on which option shall be chosen. I can clean the code to unify the usage. Personall I prefer the first option.

**Comment by mikedanese** [comment]
Please send dependency updates in separate commits within your PR, for easier reviewing.

**Comment by hurf** [comment]
@mikedanese commits seperated. I also modified dependecy to make the output same as old style. If most people think use `go-humanize` package is resonable, I'll clean the old format function to unify the usage.

**Comment by hurf** [comment]
@erictune @bgrant0607 - The output now looks like:
    FIRSTSEEN        LASTSEEN                
    15m                     15m

**Comment by bgrant0607** [comment]
Why is the existing function not sufficient? It's pretty simple.

cc @deads2k @jlowdermilk @kargakis

**Comment by kargakis** [comment]
> @mikedanese commits seperated. I also modified dependecy to make the output same as old style. If most people think use go-humanize package is resonable, I'll clean the old format function to unify the usage.

Isn't [units.HumanDuration](https://github.com/GoogleCloudPlatform/kubernetes/blob/f53e0ff5a8cd856afaa0738639a5032c77ff8f71/Godeps/_workspace/src/github.com/docker/docker/pkg/units/duration.go#L10) enough for this?

**Comment by hurf** [comment]
@kargakis - Output of [units.HumanDuration](https://github.com/GoogleCloudPlatform/kubernetes/blob/f53e0ff5a8cd856afaa0738639a5032c77ff8f71/Godeps/_workspace/src/github.com/docker/docker/pkg/units/duration.go#L10) is too long, before we use [shortHumanDuration](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/resource_printer.go#L363) to format time.

@bgrant0607 - Existing function is fine with time format, but `go-humanize` package is more flexible, and it can handle more situations. I just think if we need to format other things like big numbers or units of storage, we can also use this package.

**Comment by jwforres** [comment]
cc @fabianofranz

**Comment by bgrant0607** [comment]
If we don't need go-humanize in this PR, let's not add it yet.

**Comment by bgrant0607** [comment]
Why do you want --machine-readable? You could just use `-o template` (or soon `-o jsonpath`) to get the raw field.

**Comment by hurf** [comment]
@bgrant0607 - The flag allows users to view precise event time in old style, it's not really for machine to read. With `-o template`, command is always long. But if you don't like the flag, I created a new PR #12461 for this.

**Comment by mikedanese** [comment]
How did you update Godeps? `Godeps/Godeps.json didn't change but it appears that  a dependency was added.

**Comment by bgrant0607** [comment]
Thanks, yes, I strongly prefer #12461.

For the machine-readable times, please try the new jsonpath-style template syntax.

**Comment by hurf** [comment]
@mikedanese - I just manually put it into Godep/_workspace. I tried to upstream the custom format feature, and planned to save the dependency after the upstream PR get merged.

**Pull request closed without merging**
