### PR TITLE
kubeadm: set priority class name to `system-cluster-critical` for all master components

### LINKED ISSUE #1291: RFE: Audit default limits and priorities
We need to update limit defaults and make certain we are using sane values for priorities.  We have legacy cruft that also needs to be audited. 

xref: https://github.com/kubernetes/kubernetes/pull/69734

### PR DESCRIPTION
**Pull request by ereslibre**
**What type of PR is this?**
/kind api-change

**What this PR does / why we need it**:
Remove the deprecated `scheduler.alpha.kubernetes.io/critical-pod` pod annotation and use
the `priorityClassName` first class attribute instead, setting all master components to
`system-cluster-critical`.

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubeadm/issues/1291

**Does this PR introduce a user-facing change?**:
```release-note
kubeadm: all master components are now exclusively relying on the `PriorityClassName` pod spec for annotating them as cluster critical components. Since `scheduler.alpha.kubernetes.io/critical-pod` annotation is no longer supported by Kubernetes 1.14 this annotation is no longer added to master components.
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks @ereslibre 
LGTM

**Review by timothysc — CHANGES_REQUESTED** [review]
I think just adding some tests to verify, but otherwise it's looking good.

**Comment by ereslibre** [comment]
> I think just adding some tests to verify, but otherwise it's looking good.

I would say all changes are covered in the current tests, are you missing other specific tests?

**Comment by timothysc** [comment]
If someone were to muck the field on a different PR we should verify that it's always set.

**Comment by seh** [comment]
Does this address kubernetes/kubeadm#1337 (CoreDNS)? It looks like you covered kube-proxy, but not the DNS servers.

**Comment by ereslibre** [comment]
> Does this address [kubernetes/kubeadm#1337](https://github.com/kubernetes/kubeadm/issues/1337) (CoreDNS)? It looks like you covered kube-proxy, but not the DNS servers.

You are right, I will update the PR. Thank you!

**Comment by ereslibre** [comment]
All feedback addressed, PTAL when you can, thanks! cc/ @timothysc

**Review by fabriziopandini — APPROVED** [review]
Thanks @ereslibre 
/approve

**Review by fabriziopandini — APPROVED** [review]
thanks @ereslibre !
/approve
/lgtm

**Pull request merged**
