### PR TITLE
AWS: Restore (erroneously) removed get_instance_private_ip

### LINKED ISSUE #11201: Error exec "cluster/kube-up.sh". aws without public ip
When you run the "Cluster / kube.up.sh" error below

./../cluster/aws/util.sh: line 182: get_instance_private_ip: command not found

i add the function in cluster/aws/util.s
```bash
function get_instance_private_ip {
  local instance_id=$1
  $AWS_CMD --output text describe-instances \
    --instance-ids ${instance_id} \
    --query Reservations[].Instances[].NetworkInterfaces[0].PrivateIpAddress
}
```

### PR DESCRIPTION
**Pull request by justinsb**
Fix #11201

### CODE REVIEW

**Comment by thockin** [comment]
Required for AWS support.  Justin, I presume this would need to be cherry-picked into release-1.0?

**Comment by thockin** [comment]
@justinsb cherry pick for 1.0 or not?

**Comment by justinsb** [comment]
It's only for KUBE_ENABLE_MINION_PUBLIC_IP=false, which is not the common configuration, but we do document it.  The patch is low risk (adds a function to a bash file), so I think we should probably merge it, but I'm not sure exactly how problematic it is to cherry-pick things to 1.0 at this point in the cycle.  If we have a 1.0.1 backlog this might be a candidate for that.

**Comment by thockin** [comment]
Cherry picking IS the 1.0.1 queue-up :)

Can you try running  ./hack/cherry_pick_pull.sh (so someone outside of us
can try it :) ?

**Pull request merged**
