### PR TITLE
cleanup TODO comment that has been resolved.

### PR DESCRIPTION
**Pull request by kidlj**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

cleanup Todo comment that has been resolved.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/retest

/assign @liggitt @smarterclayton 

NOTE: 3 lines ONLY, just cleanup of comments, still needs api approval, has a lgtm from @leilajal so should be quick

**Comment by liggitt** [comment]
this doc change affects generated docs/files, so `make update` is needed to make the CI verification pass

**Comment by kidlj** [comment]
> this doc change affects generated docs/files, so `make update` is needed to make the CI verification pass

Thank you, I didn't know this. But my network behind proxy always fails to run `make update`. So I think I'd better close this PR.

/close

**Pull request closed without merging**
