### PR TITLE
Explicit bump to go 1.20

### PR DESCRIPTION
**Pull request by enj**
/kind feature

xref: #115935

```release-note
NONE
```

### CODE REVIEW

**Comment by enj** [comment]
Well this is fun:

```
 === Failed
=== FAIL: pkg/kubelet TestSyncKnownPods (0.16s)
==================
WARNING: DATA RACE
Write at 0x00c00128cf30 by goroutine 1396:
  runtime.mapdelete_faststr()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.2.linux.amd64/src/runtime/map_faststr.go:301 +0x0
  k8s.io/kubernetes/pkg/kubelet.(*podWorkers).cleanupPodUpdates()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:1648 +0x299
  k8s.io/kubernetes/pkg/kubelet.(*podWorkers).completeTerminated()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:1420 +0x1f4
  k8s.io/kubernetes/pkg/kubelet.(*podWorkers).podWorkerLoop()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:1260 +0x18b6
  k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod.func1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:920 +0x175
Previous read at 0x00c00128cf30 by goroutine 1381:
  k8s.io/kubernetes/pkg/kubelet.TestSyncKnownPods()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers_test.go:1640 +0x1056
  testing.tRunner()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.2.linux.amd64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.2.linux.amd64/src/testing/testing.go:1629 +0x47
Goroutine 1396 (running) created at:
  k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:915 +0x5131
  k8s.io/kubernetes/pkg/kubelet.TestSyncKnownPods()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers_test.go:1534 +0xc4
  testing.tRunner()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.2.linux.amd64/src/testing/testing.go:1576 +0x216
  testing.(*T).Run.func1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.2.linux.amd64/src/testing/testing.go:1629 +0x47
Goroutine 1381 (running) created at:
  testing.(*T).Run()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.2.linux.amd64/src/testing/testing.go:1629 +0x805
  testing.runTests.func1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.2.linux.amd64/src/testing/testing.go:2036 +0x8d
  testing.tRunner()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.2.linux.amd64/src/testing/testing.go:1576 +0x216
  testing.runTests()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.2.linux.amd64/src/testing/testing.go:2034 +0x87c
  testing.(*M).Run()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.2.linux.amd64/src/testing/testing.go:1906 +0xb44
  main.main()
      _testmain.go:281 +0x2e9
  runtime.main()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.2.linux.amd64/src/runtime/proc.go:250 +0x206
  k8s.io/kubernetes/vendor/github.com/cilium/ebpf/link.init()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/cilium/ebpf/link/syscalls.go:50 +0x2a8
  k8s.io/kubernetes/vendor/github.com/cilium/ebpf/link.init()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/cilium/ebpf/link/syscalls.go:29 +0x24a
  runtime.doInit()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.2.linux.amd64/src/runtime/proc.go:6506 +0x125
  k8s.io/kubernetes/vendor/github.com/cilium/ebpf.init()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/cilium/ebpf/syscalls.go:438 +0x6f0
  k8s.io/kubernetes/vendor/github.com/cilium/ebpf.init()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/cilium/ebpf/syscalls.go:412 +0x690
  k8s.io/kubernetes/vendor/github.com/cilium/ebpf.init()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/cilium/ebpf/syscalls.go:390 +0x630
  k8s.io/kubernetes/vendor/github.com/cilium/ebpf.init()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/cilium/ebpf/syscalls.go:372 +0x5d0
  k8s.io/kubernetes/vendor/github.com/cilium/ebpf.init()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/cilium/ebpf/syscalls.go:191 +0x570
  k8s.io/kubernetes/vendor/github.com/cilium/ebpf.init()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/cilium/ebpf/syscalls.go:175 +0x510
  k8s.io/kubernetes/vendor/github.com/cilium/ebpf.init()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/cilium/ebpf/syscalls.go:158 +0x4b0
  k8s.io/kubernetes/vendor/github.com/cilium/ebpf.init()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/cilium/ebpf/syscalls.go:140 +0x44e
  runtime.doInit()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.2.linux.amd64/src/runtime/proc.go:6506 +0x125
  k8s.io/kubernetes/vendor/github.com/cilium/ebpf/internal/btf.init()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/cilium/ebpf/internal/btf/btf.go:727 +0x1bc
==================
    testing.go:1446: race detected during execution of test
DONE 38566 tests, 23 skipped, 1 failure in 2.090s 
```

**Comment by liggitt** [comment]
Just started flaking badly https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=TestSyncKnownPods

Probably related to merge of https://github.com/kubernetes/kubernetes/pull/113145

cc @smarterclayton

**Pull request merged**
