### PR TITLE
Remove comment about restricting error for failedGroups

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
In fetchGroupVersionResources, the comment about restricting the error from d.ServerResourcesForGroupVersion should be removed since there are other errors than not found error.
```
I1219 19:06:57.404151       1 discovery_client.go:369] fetchGroupVersionResources got: the server is currently unable to handle the request
```

**Which issue(s) this PR fixes**:
Fixes #

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by tedyu** [comment]
Checking for not found error alone for failedGroups is not enough.
Here is one other error:
```
I1219 12:57:04.908521   51114 discovery_client.go:368] fetchGroupVersionResources got: groupVersion shouldn't be empty
```

**Comment by caesarxuchao** [comment]
@tedyu we shouldn't exclude this error. If we exclude this error, GC and the namespace controller will think they have a complete picture of group/versions, while they don't, that would lead to unexpected behavior.
/hold

**Comment by tedyu** [comment]
@caesarxuchao 
Since we cannot restrict to NotFound errors, how about removing that comment (as the only change) ?

**Pull request closed without merging**
