### PR TITLE
Use markdown headers instead of bold text for PR template

### PR DESCRIPTION
**Pull request by saschagrunert**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

The usage of markdown headers will provide a more eye-friendly
formatting without having a need to add additional newlines to the PR.
This is reasoned by the GitHub markdown parser which adds additional
space before and after the header.

**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

##### Before
The markdown:
```
**What type of PR is this?**
/kind documentation
**What this PR does / why we need it**:
Lorem ipsum
```

Renders:

**What type of PR is this?**
/kind documentation
**What this PR does / why we need it**:
Lorem ipsum

##### After
The markdown:
```
#### What type of PR is this?
/kind documentation
#### What this PR does / why we need it:
Lorem ipsum
```

Renders:

#### What type of PR is this?
/kind documentation
#### What this PR does / why we need it:
Lorem ipsum

### CODE REVIEW

**Review by justaugustus — CHANGES_REQUESTED** [review]
@saschagrunert -- Could you do the same for all of the templates in https://github.com/kubernetes/kubernetes/tree/master/.github/ISSUE_TEMPLATE?

**Comment by saschagrunert** [comment]
> @saschagrunert -- Could you do the same for all of the templates in https://github.com/kubernetes/kubernetes/tree/master/.github/ISSUE_TEMPLATE?

Yep sure, done :+1:

**Comment by saschagrunert** [comment]
/test pull-kubernetes-e2e-kind
--

**Comment by saschagrunert** [comment]
@justaugustus do you see anything which has to be done here?

**Comment by mrbobbytables** [comment]
/triage accepted
/approve
/hold
/assign @cblecker @nikhita @alisondy 
For any additional comments

**Review by nikhita — APPROVED** [review]
/lgtm
/approve

Please free to cancel the hold at your discretion :)

**Pull request merged**
