### PR TITLE
image: Change the download url from http to https

### PR DESCRIPTION
**Pull request by wzshiming**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @claudiubelu 
both url works for me, any reason we should switch, security?

**Comment by wzshiming** [comment]
> /assign @claudiubelu
> both url works for me, any reason we should switch, security?

Yes, The other two zip packages are downloaded through https, and this one through http, it doesn’t feel good, https can also work

**Comment by aojea** [comment]
> > /assign @claudiubelu
> > both url works for me, any reason we should switch, security?
> 
> Yes, The other two zip packages are downloaded through https, and this one through http, it doesn’t feel good, https can also work

/lgtm
Thanks

**Pull request merged**
