### PR TITLE
remove scheduler policy config

### LINKED ISSUE #92143: Deprecate Policy scheduling config
/sig scheduling

As we move forward with graduating component config #89701 (targetting beta for 1.19), Policy APIs are redundant and thus can be removed.

Following API guidelines, we should have a GA alternative for 2 releases. Given current projections, we can remove Policy config in 1.23

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

#### What type of PR is this?
/kind cleanup
/sig scheduling

#### What this PR does / why we need it:
Part of https://github.com/kubernetes/enhancements/issues/2901

#### Which issue(s) this PR fixes:

Fixes #92143

#### Does this PR introduce a user-facing change?

```release-note
Action required: The legacy scheduler policy config is removed in v1.23, the associated flags policy-config-file, policy-configmap, policy-configmap-namespace and use-legacy-policy-config are also removed. Migrate to Component Config instead, see https://kubernetes.io/docs/reference/scheduling/config/ for details.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/2901
```

### CODE REVIEW

**Comment by ahg-g** [comment]
can you please rebase? also, is this still a draft?

**Comment by kerthcet** [comment]
> can you please rebase? also, is this still a draft?

yes it's still a draft now since a related pr is merged today. I'll let you know if i finished my work.💪

**Comment by Huang-Wei** [comment]
Note that this PR needs a `Action Required` portion. See guidance here: https://www.kubernetes.dev/docs/guide/release-notes/

Please also open a k/website PR to track the changes.

**Comment by ahg-g** [comment]
@neolit123 can you please approve the change to test/integration/node/lifecycle_test.go

Other than that, this looks good to me.

**Comment by kerthcet** [comment]
> Please replace the release note with the following:
> 
> ```
> Action required: The legacy scheduler policy config is removed in v1.23, the associated flags policy-config-file, policy-configmap, policy-configmap-namespace and use-legacy-policy-config are also removed. Migrate to Component Config instead, see https://kubernetes.io/docs/reference/scheduling/config/ for details.
> ```

done :)

**Review by neolit123 — COMMENTED** [review]
/approve

**Comment by kerthcet** [comment]
> please squash the commits

done :)

**Pull request merged**
