### PR TITLE
Remove directxman12 from OWNERS

### PR DESCRIPTION
**Pull request by DirectXMan12**
As per
https://groups.google.com/g/kubebuilder/c/-5hOFa_adr4/m/Sp_Zb755AwAJ,
directxman12 is stepping down.

#### What type of PR is this?

/kind cleanup

```release-note
NONE
```

```docs

```

### CODE REVIEW

**Comment by DirectXMan12** [comment]
(moved to emeritus as per general k8s policy)

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by dashpole** [comment]
@logicalhan is going to close and rebase this

**Pull request closed without merging**
