### PR TITLE
`kubectl taint` update for `NoExecute`.

### LINKED ISSUE #42774: Update kubectl to reflect the latest `NoExecute` update
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Kubernetes version** (use `kubectl version`):

**Environment**:
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Install tools**:
- **Others**:

**What happened**:
The  help for `kubectl taint` needs to be updated to reflect the latest `NoExecute` change.

```
root@k8s001:~/go/src/k8s.io/kubernetes# kubectl taint --help | grep No
  * The effect must be NoSchedule or PreferNoSchedule.
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
Fixes #42774
**Release note**:

```release-note
```

### CODE REVIEW

**Comment by gyliu513** [comment]
@k8s-bot kops aws e2e test this

**Comment by gyliu513** [comment]
@k8s-bot kops aws e2e test this

**Comment by fabianofranz** [comment]
Tks @gyliu513
/lgtm
/approve

**Comment by gyliu513** [comment]
@fabianofranz do you know why this POR does not got merged? Thanks.

**Comment by gyliu513** [comment]
@k8s-bot test this

**Comment by fabianofranz** [comment]
@gyliu513 Master is closed except for PR's intended to land in the 1.6 milestone.

**Comment by gyliu513** [comment]
I think this need to be landed in 1.6 as this belong to part of documentation work here https://github.com/kubernetes/kubernetes.github.io/issues/2737 @fabianofranz

**Comment by fabianofranz** [comment]
> I think this need to be landed in 1.6 as this belong to part of documentation work here kubernetes/kubernetes.github.io#2737 @fabianofranz

Ok, @ethernetdan @calebamiles are you ok with tagging this for 1.6?

**Comment by ethernetdan** [comment]
@fabianofranz sgtm

**Comment by kevin-wangzefeng** [comment]
Thanks for the fix!

**Comment by kevin-wangzefeng** [comment]
@k8s-bot kops aws e2e test this

**Comment by gyliu513** [comment]
@k8s-bot kops aws e2e test this

**Comment by gyliu513** [comment]
@k8s-bot kops aws e2e test this

**Comment by cmluciano** [comment]
@gyliu513 try to trigger the kops build again. I think they fixed the rate-limiting [here](https://github.com/kubernetes/kops/commit/2a44aa0c05ccfa0beb6d96ee21a7883947664f76)

**Comment by fabianofranz** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
