### PR TITLE
fix: rename RegisterPriorityFunction2 to RegisterPriorityMapReduceFunction

### PR DESCRIPTION
**Pull request by draveness**
/kind cleanup
/sig scheduling
/priority backlog

Rename RegisterPriorityFunction2 to RegisterPriorityMapReduceFunction followed @Huang-Wei 's advice.

```release-note
NONE
```

### CODE REVIEW

**Review by Huang-Wei — COMMENTED** [review]
Thanks @draveness .

The `FIXME` suggestion was put 3 years ago, and the logic changed vastly since then. So we can come up with a better function name.

Given that there are 2 functions for registering Priority Function: the old style and map-reduce style, and both calls `RegisterPriorityConfigFactory` ultimately. So IMO `RegisterPriorityMapReduceFunction` makes more sense.

**Comment by draveness** [comment]
> Thanks @draveness .
> 
> The `FIXME` suggestion was put 3 years ago, and the logic changed vastly since then. So we can come up with a better function name.
> 
> Given that there are 2 functions for registering Priority Function: the old style and map-reduce style, and both calls `RegisterPriorityConfigFactory` ultimately. So IMO `RegisterPriorityMapReduceFunction` makes more sense.

Sounds Good, Please take another look, thanks!

**Comment by Huang-Wei** [comment]
/lgtm
/approve

/hold
for a couple of days in case someones have better naming.

**Comment by bsalamat** [comment]
/hold cancel

Naming is fine for now. We will soon covert all predicate and priority functions into plugins and then we can remove the code around registering them.

**Pull request merged**
