### PR TITLE
Automated cherry pick of #66400: Return correct error type and HTTP Status code for operation

### PR DESCRIPTION
**Pull request by nicksardo**
Cherry pick of #66400 on release-1.10.

#66400: Return correct error type and HTTP Status code for operation

### CODE REVIEW

**Comment by MaciekPytel** [comment]
@calebamiles You could have just pinged me first :) I talked with @nicksardo and this is critically important for 1.10.6, so I'm ok with it merging after deadline.

**Comment by nicksardo** [comment]
Thanks Folks! Sorry for pinging the wrong person.

**Pull request merged**
