### PR TITLE
cleanup: fix errors in wrapped format and log capitalization in controller

### PR DESCRIPTION
**Pull request by wangyx1992**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
This PR fixes errors in wrapped format and log capitalization in controller.

#### Which issue(s) this PR fixes:
Ref #15863

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by wangyx1992** [comment]
Hi, @thockin. We upgrade the commit to solve `pull-kubernetes-unit` failure, previous `LGTM ` label has been removed, waiting for your review with pleasure.

**Pull request merged**
