### PR TITLE
Automated cherry pick of #12022 #13148 upstream release 1.0

### PR DESCRIPTION
**Pull request by pwittrock**
Cherry pick cadvisor updates into release 1.0 to prevent incorrect VersionInfo caching.

### CODE REVIEW

**Comment by pwittrock** [comment]
Saw this e2e failure in the jenkins logs:

> Shutting down test cluster in background.

> ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:

> \- The resource 'projects/kubernetes-jenkins-pull/global/firewalls/pull-e2e-2-minion-pull-e2e-2-http-alt' was not found

> ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:

> \- The resource 'projects/kubernetes-jenkins-pull/global/firewalls/pull-e2e-2-minion-pull-e2e-2-nodeports' was not found


Does this look like a transient error, or something I should dig into?

**Comment by bprashanth** [comment]
@ixdy about the cluster tear down errors

**Comment by ixdy** [comment]
Those errors are red herrings (we always try to tear down the cluster at the beginning of the run, and that "fails" if the cluster is already down).

The real failure was
```
ERROR: (gcloud.compute.disks.create) Some requests did not succeed:
 - Internal Error
```

which is probably a transient error in the Google cloud platform.

**Comment by ixdy** [comment]
@k8s-bot test this again please

**Comment by pwittrock** [comment]
Quick question before this is merged.

In my branch when I run (from k8s.io/kubernetes) 

`$ godep restore`
`$ godep save ./...`

I get:

> godep save ./...
> godep: cannot find package "github.com/GoogleCloudPlatform/kubernetes/pkg/api/resource" in any of:
>	/usr/lib/google-golang/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/resource (from $GOROOT)
>	<redacted>/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/resource (from $GOPATH)
> godep: error loading dependencies

Perhaps this means we need to remove go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/resource?

**Comment by pwittrock** [comment]
Or maybe that issue was caused by the name change of the repo?

**Comment by vishh** [comment]
LGTM. Are you trying godep on the release branch @pwittrock? The path changes and switching to a vanity domain happened post v1.0.

**Comment by pwittrock** [comment]
Thanks all.  Re Vish: Yeah I was trying to run go deps on the 1.0 branch as a sanity check to make sure everything looked good, but I ran into some errors that seemed to be related to the path switches and how project was structured.

**Pull request merged**
