### PR TITLE
Updating swagger-ui to the latest version

### PR DESCRIPTION
**Pull request by nikhiljindal**
As per the suggestion here: https://github.com/swagger-api/swagger-ui/issues/1455.
But latest version hasnt made it any faster, as far as I can tell.

Verified that the UI works as before.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
@bgrant0607 @caesarxuchao @thockin

**Comment by thockin** [comment]
I would guess we don't want to change this before 1.0, right?

**Comment by bgrant0607** [comment]
if it doesn't help, it can wait

**Comment by nikhiljindal** [comment]
Can I get the LGTM label now?

**Comment by bgrant0607** [comment]
LGTM

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Pull request merged**
