### PR TITLE
Automated cherry pick of #23996

### PR DESCRIPTION
**Pull request by andyzheng0831**
Cherry pick of #23996 on release-1.2.

### CODE REVIEW

**Comment by andyzheng0831** [comment]
@dchen1107 @vishh please review this cherry pick

cc/ @wonderfly @roberthbailey @fabioy FYI.

**Comment by vishh** [comment]
LGTM

**Comment by andyzheng0831** [comment]
@zmerlynn Any question about this cherry-pick?

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
cc/ @roberthbailey

**Comment by andyzheng0831** [comment]
@dchen1107 you may also need to update the milestone and labels. There is a "do-not-merge" label

**Comment by roberthbailey** [comment]
You should only need to put the milestone and labels on the original PR.

**Comment by andyzheng0831** [comment]
I guess the "do-not-merge" label will prevent this cherry pick from being merged.

**Pull request merged**
