### PR TITLE
client-go/transport: make TLS transport caching optional

### LINKED ISSUE #125818: client-go: global transport cache grows unbounded when requesting configs with non-nil `Dial` functions
### What happened?

client-go 1.26+ changed the semantics of `kubernetes.NewForConfig(restConfig)` by caching TLS transport objects in some cases which were not cached in earlier versions (notably, configurations with non-nil `Dial` functions).

Unfortunately the cache does not have any expire or pruning mechanism, leading in worst case to unbounded growth of memory usage (see for example kubernetes/kubernetes#117250).

The change is: kubernetes/kubernetes#112450

This issue is for a program using client-go (Rancher) requesting clientsets with non-nil Dial functions over time.

### What did you expect to happen?

TLS transport objects not to be internally cached by client-go, like in 1.25 and earlier versions.

### How can we reproduce it (as minimally and precisely as possible)?

`	clientset, err := kubernetes.NewForConfig(config)`

with `config.Dial` being non-nil.

I will be submitting a PR that unit-test covers this.

### Anything else we need to know?

_No response_

### Kubernetes version

1.26 and over

### Cloud provider

any

### OS version

any

### Install tools

any

### Container runtime (CRI) and version (if applicable)

n/a

### Related plugins (CNI, CSI, ...) and versions (if applicable)

n/a

### PR DESCRIPTION
**Pull request by moio**
#### What type of PR is this?
/kind bug
/kind regression

#### What this PR does / why we need it:

client-go 1.26+ changed the semantics of `kubernetes.NewForConfig(restConfig)` by caching TLS transport objects in some cases which were not cached in earlier versions (notably, configurations with non-nil `Dial` functions).

Unfortunately the cache does not have any expire or pruning mechanism, leading to unbounded growth of memory usage (see for example kubernetes/kubernetes#117250).

The change is: kubernetes/kubernetes#112450

This patch allows client-go users to explicitly request pre-1.26 behavior.

#### Which issue(s) this PR fixes:

Fixes #125818

#### Does this PR introduce a user-facing change?
```release-note
- client-go: added a `DisableTransportCaching` config flag to explicitly disable caching of TLS transports
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

n/a

### CODE REVIEW

**Comment by dims** [comment]
xref: 
- https://github.com/kubernetes/kubernetes/issues/117250
- https://github.com/kubernetes/kubernetes/pull/112450
- https://github.com/kubernetes/kubernetes/pull/112017

**Comment by dims** [comment]
@moio would you consider suggestions made in https://github.com/kubernetes/kubernetes/pull/117248/files ?

**Comment by moio** [comment]
> @moio would you consider suggestions made in [#117248 (files)](https://github.com/kubernetes/kubernetes/pull/117248/files) ?

I agree with discussions there that either limiting the size of the cache or putting a maximum time-to-leave to cached entries would require a way to close connections from clients cleanly, which I do not have good ideas how to do either.

With this PR users have at least a way to control the cache in that they could decide to disable it and cache transports instead at an upper level, using whichever caching policies make sense for the end application.

**Comment by BenTheElder** [comment]
/remove-triage accepted

(I think that was a bit premature, it's not clear if OWNERS are onboard with this approach)

Let's drive discussion on approach in https://github.com/kubernetes/kubernetes/issues/125818 which is more general.

**Comment by moio** [comment]
@BenTheElder is there anything I could do to move this PR forward?

**Comment by aojea** [comment]
we are in code freeze so until 1.32 there is no point in reviewing. 
Changes in this area are very complicated and with a very large blast radius with very subtle bugs that usually take several releases on show up.

It is also important to understand why is the transport cache growing?
what are you specifically doing to make this happen?
we don't want to hide or workaround incorrect uses of the REST client constructor

**Comment by moio** [comment]
> we are in code freeze so until 1.32 there is no point in reviewing. Changes in this area are very complicated and with a very large blast radius with very subtle bugs that usually take several releases on show up.

I understand it takes time.

> It is also important to understand why is the transport cache growing?

Because, according to my understanding, there is no mechanism to remove elements from it.

The cache is defined here:

https://github.com/kubernetes/kubernetes/blob/dbc2b0a5c7acc349ea71a14e49913661eaf708d2/staging/src/k8s.io/client-go/transport/cache.go#L38C2-L38C12

No code seems to ever delete from that map.

> what are you specifically doing to make this happen?

Creating clients by specifing non-nil `Dial`. That is sufficient to add to the `transport` cache above. We have application reasons to recycle those often.

> we don't want to hide or workaround incorrect uses of the REST client constructor

Completely agreed, if there is a way to prevent the cache that I am not getting I am happy to change client code.

> If you need to pass a custom dialer you can solve the problem like in #117258

As mentioned in https://github.com/kubernetes/kubernetes/issues/125818#issuecomment-2265172761, I am passing a custom dialer but the problem and approach in that PR seem to be different from what I am trying to solve.

Does that make sense to you?

**Pull request closed without merging**
