### PR TITLE
Add Close() for profile

### PR DESCRIPTION
**Pull request by sunzhaochang**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This will cause memory leak if the file is not closed.

#### Which issue(s) this PR fixes:

Fixes memory leak when profile enabled

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Comment by eddiezane** [comment]
@sunzhaochang thanks for the PR and good catch!

Could you please share how you came across this?

**Comment by sunzhaochang** [comment]
@eddiezane I just read the code in order to figure out how the profile works, and then came across this by accident.

**Comment by brianpursley** [comment]
Thanks for finding this and submitting a PR to fix it

/lgtm
/approve

**Pull request merged**
