### PR TITLE
Move pkg/util/interrupt to apimachinery

### PR DESCRIPTION
**Pull request by smarterclayton**
This package is a helper to assist in doing guaranteed cleanup on signals,
primarily used by kubectl, but also by other one off processes that might
run in pods. Move it out of k8s.io/kubernetes first, before potentially
moving it to a library package or other.

@deads2k @sttts there are a few ecosystem tools that want to do proper
nesting of signal handlers, and this is currently the only mechanism we
have for someone to either guarantee a signal handle (plus clean shutdown
afterwards) for either kubectl or things that run in pods.

```release-note
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
Why not move it into k8s.io/utils? It has no dependencies which speak against it.

**Comment by smarterclayton** [comment]
yeah, @deads2k suggested that.  will reopen there and leave this for the change to classes

**Review by cheftako — APPROVED** [review]
/lgtm

**Pull request closed without merging**
