### PR TITLE
Automated cherry pick of #61394: Remove 'system' prefix from Metadata Agent rbac configuration

### PR DESCRIPTION
**Pull request by kawych**
Cherry pick of #61394 on release-1.10.

#61394: Remove 'system' prefix from Metadata Agent rbac configuration

**Release note**:
```release-note
Remove 'system' prefix from Metadata Agent rbac configuration
```

### CODE REVIEW

**Comment by MaciekPytel** [comment]
@kawych Can you add release not to #61394? AFAIK the release notes for cherrypicks done with script are generated from original PR, not cherry-pick.

**Comment by kawych** [comment]
@ericchiang Friendly PING

**Comment by ericchiang** [comment]
Woops

/lgtm

**Pull request merged**
