### PR TITLE
Add kms-plugin-container.manifest to release manifest tarball.

### PR DESCRIPTION
**Pull request by immutableT**
**What this PR does / why we need it**:
cluster/gce/manifests/kms-plugin-container.manifest needs to be included into the manifests' release tarball. 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Include kms-plugin-container.manifest to master manifests tarball.
```

### CODE REVIEW

**Comment by dims** [comment]
@mikedanese you may have to remove the `milestone/incomplete-labels` by hand

**Comment by immutableT** [comment]
I build a release of this PR using release/push-build.sh and my test cluster (with KMS integration) came-up fine.

**Pull request merged**
