### PR TITLE
Automated cherry pick of #65373: BUGFIX: must use ID, not name, of the node security group

### PR DESCRIPTION
**Pull request by dims**
Cherry pick of #65373 on release-1.11.

#65373: BUGFIX: must use ID, not name, of the node security group

### CODE REVIEW

**Comment by nikhita** [comment]
@anguslees lgty?

/assign @foxish 
for cherry-pick approval

**Comment by foxish** [comment]
Which SIG owns this? Can someone tag this with the right SIG label?

**Review by anguslees — APPROVED** [review]

**Pull request merged**
