### PR TITLE
Local Storage Operations QOS support

### PR DESCRIPTION
**Pull request by ailusazh**
Implementation of Storage operations of Future resource types in https://github.com/kubernetes/community/blob/master/contributors/design-proposals/resources.md

Add two new StorageReadIOps and StorageWriteIOps resources to support local storage operations qos . The value of the two resources will eventually be set in I/O throttling tunable parameters of the block I/O (blkio) subsystem in container-level cgroup. StorageReadIOps corresponds to blkio.throttle.read_iops_device and StorageWriteIOps corresponds to blkio.throttle.write_iops_device.

Add a new configuration blkio-device-path to kubelet, possible values: "/dev/sda", "/dev/sdb". Default: "/dev/sda". Finally blkio-device-path will be converted to major and minor numbers which are device types and node numbers specified in Linux Allocated Devices. Then the major and minor numbers will be set as part of the value of blkio.throttle.read_iops_device and blkio.throttle.write_iops_device.

The introduction to blkio: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Resource_Management_Guide/ch-Subsystems_and_Tunable_Parameters.html#blkio-throttling

The code is implemented in docker_manager of kubelet. Only enable-cri set to false will take effect.

### CODE REVIEW

**Comment by ailusazh** [comment]
@smarterclayton @yujuhong

**Comment by derekwaynecarr** [comment]
Have you been following:

https://github.com/kubernetes/community/pull/306

/cc @sjenning

**Comment by msau42** [comment]
What use case is this trying to solve?  Who will use blkdevicepath and how?

**Comment by ailusazh** [comment]
@derekwaynecarr i have read [kubernetes/community#306](https://github.com/kubernetes/community/pull/306/files), and i think this feature is a supplement to Local Storage Management.

**Comment by ailusazh** [comment]
@msau42 thankyou for you question.
In the case of using emptydir or flexvolume as volume plugin, without iops limit, especially write iops, containers of different pods will meet the impact because of competition. And when the user continues to write a large number of data to the containers in the pod, the load on the physical machine will be too high without iops limit. So we add this feature to ensure the stability of physical machine in production environment.

BlkioDevicePath refers to the device where the emptydir volume is located.

Create a pod using the following yaml, then the rate of the direct write operations won't exceed 100 time per second and the rate of the direct  read operations won't exceed 200 time per second.

example for emptydir:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: test-container
    resources:
      limits:
        alpha.kubernetes.io/storage-read-iops: 200
        alpha.kubernetes.io/storage-write-iops: 100
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
```

example for flexvolume:

```
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: test-container
    resources:
      limits:
        alpha.kubernetes.io/storage-read-iops: 200
        alpha.kubernetes.io/storage-write-iops: 100
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
    - name: cache-volume
      flexVolume:
      driver: "kubernetes.io/lvm"
      fsType: "ext4"
      options:
        volumeID: "cache_volume"
        size: "2G"
        volumegroup: "testvg"
```
BlkioDevicePath is the device  where cache-volume is located.

**Comment by ailusazh** [comment]
@msau42 thankyou for you question.
In the case of using emptydir or flexvolume as volume plugin, without iops limit, especially write iops, containers of different pods will meet the impact because of competition. And when the user continues to write a large number of data to the containers in the pod, the load on the physical machine will be too high without iops limit. So we add this feature to ensure the stability of physical machine in production environment.

BlkioDevicePath refers to the device where the emptydir volume is located.

Supporting cache-volume is located on /dev/sda, set blkio-device-path to /dev/sda, and create a pod using the following yaml, then the rate of the direct write operations to /cache dir won't exceed 100 time per second and the rate of the direct read operations to /cache dir won't exceed 200 time per second.

example for emptydir:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: test-container
    resources:
      limits:
        alpha.kubernetes.io/storage-read-iops: 200
        alpha.kubernetes.io/storage-write-iops: 100
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
```

example for flexvolume:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: test-container
    resources:
      limits:
        alpha.kubernetes.io/storage-read-iops: 200
        alpha.kubernetes.io/storage-write-iops: 100
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
    - name: cache-volume
      flexVolume:
      driver: "kubernetes.io/lvm"
      fsType: "ext4"
      options:
        volumeID: "cache_volume"
        size: "2G"
        volumegroup: "testvg"
```

**Comment by ailusazh** [comment]
cc @kubernetes/sig-storage
cc @msau42 @derekwaynecarr @smarterclayton @yujuhong @mml  Please give some advice.

**Comment by liangxiaoping** [comment]
looking forward to this feature.

**Comment by xuxinkun** [comment]
Actually, iops especially write-iops must be limited in production environment. Containers in my company may compete for writing operation. So, I'd love to see adding this feature as soon as possible.

**Pull request closed without merging**
