### PR TITLE
fix nits in pkg apis

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

**What this PR does / why we need it**:
fix some nits lin pkg apis

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
NONE

**Special notes for your reviewer**:
NONE

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Thanks @allencloud

**Comment by allencloud** [comment]
ping @errordeveloper 😄 🍺

**Comment by allencloud** [comment]
ping @errordeveloper 😄 🍺

**Pull request closed without merging**
