### PR TITLE
Add ethtool to hyperkube

### LINKED ISSUE #18251: ethtool not found in $PATH, containerized hyperkube
```
I1205 13:35:11.775742   30973 hairpin.go:49] Unable to find pair interface, setting up all interfaces: exec: "ethtool": executable file not found in $PATH
I1205 13:35:11.960131   30973 hairpin.go:49] Unable to find pair interface, setting up all interfaces: exec: "ethtool": executable file not found in $PATH
I1205 13:35:12.631919   30973 hairpin.go:49] Unable to find pair interface, setting up all interfaces: exec: "ethtool": executable file not found in $PATH
I1205 13:35:13.138438   30973 hairpin.go:49] Unable to find pair interface, setting up all interfaces: exec: "ethtool": executable file not found in $PATH
```

Maybe just add `ethtool` to `hyperkube` Dockerfile?
/cc @dalanlan @fgrzadkowski

### PR DESCRIPTION
**Pull request by thockin**
Fixes #18251

### CODE REVIEW

**Comment by thockin** [comment]
e2e not useful for this

**Comment by luxas** [comment]
Oh, I forgot to make a PR myself...
Glad you catched it
I'll close the issue

**Comment by thockin** [comment]
semi-random reassign

**Comment by Random-Liu** [comment]
I just found that I was assigned. LGTM, :)

**Pull request merged**
