### PR TITLE
Use the kubectl binary rather than the wrapper shell script in the kubectl e2e test.

### PR DESCRIPTION
**Pull request by roberthbailey**

### CODE REVIEW

**Comment by jlowdermilk** [comment]
LGTM, assuming e2e passes for gce|gke.

**Comment by satnam6502** [comment]
Great, I assume all will continue to work with invocations with `go ...blah.go` (which end up in a temporary directory if they need to be compiled) as well as executing binaries directly.

**Comment by roberthbailey** [comment]
@satnam6502 I've been testing with ```go run hack/e2e.go -v -test``` to verify that the e2e tests run correctly (as described on https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/development.md#flag-options). 

Can you give me an example of the alternative invocation I should be testing?

**Comment by satnam6502** [comment]
No,  that's great,  thanks.

**Comment by roberthbailey** [comment]
@jlowdermilk This passes for gce e2e test but is failing the gke e2e test. I'm seeing the kubectl subprocess exit with an auth error:

```F0301 20:58:33.958575   18864 create.go:83] Post https://x.x.x.x/api/v1beta1/replicationControllers?namespace=default: x509: certificate signed by unknown authority```

I compared the command lines for how kubectl is run from inside the gcloud container wrapper and what I'm generating for the e2e test and the difference is that the gcloud wrapper passes ```--server=https://y.y.y.y``` as an extra command line option. It may just be my local configuration and the order in which I ran the e2e tests (gce first then gke) but since gcloud doesn't update the ```~/.kube/.kubeconfig``` file I don't see how it would know the endpoint of the gke cluster.

**Comment by roberthbailey** [comment]
I added an extra check for gke and verified that the tests worked after the change on gke & gce. PTAL.

**Pull request merged**
