### PR TITLE
Automated cherry pick of #80675: fix-file-discovery

### PR DESCRIPTION
**Pull request by neolit123**
Cherry pick of #80675 on release-1.14.

#80675: autogenerated

### CODE REVIEW

**Comment by neolit123** [comment]
/kind bug
/priority critical-urgent
/assign @fabriziopandini

this one required minor rebase (v1beta1 vs v1beta2), so please double check the last commit.

**Comment by fabriziopandini** [comment]
@kubernetes/patch-release-team
PTAL

**Comment by fabriziopandini** [comment]
Thanks, @kubernetes/patch-release-team!
Awesome!

**Pull request merged**
