### PR TITLE
Automated cherry pick of #87648: Update to golang@1.13.8

### PR DESCRIPTION
**Pull request by ialidzhikov**
Cherry pick of #87648 on release-1.16.

#87648: Update to golang@1.13.8

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by ialidzhikov** [comment]
Ref kubernetes/release#1134.

/assign @justaugustus

**Comment by justaugustus** [comment]
Thanks @ialidzhikov!
As a heads up, this will need https://github.com/kubernetes/kubernetes/pull/88596 to merge before all of the tests will pass.

**Comment by justaugustus** [comment]
@liggitt @BenTheElder @cblecker @dims -- https://github.com/kubernetes/kubernetes/pull/88596 has merged, so this is ready for approval now.
/lgtm
/approve
/retest

**Pull request merged**
