### PR TITLE
Cherry pick of #93908: Updating EndpointSlice controllers to return i…

### PR DESCRIPTION
**Pull request by ping035627**
Cherry pick of #93908 on release-1.18.

#93908 : Updating EndpointSlice controllers to return if error encountered

For details on the cherry pick process, see the cherry pick requests page.

/sig network
/priority critical-urgent
/kind bug

### CODE REVIEW

**Comment by aojea** [comment]
@robscott do we backport  this while in beta?

**Comment by robscott** [comment]
I'm not 100% sure if this needs a cherry-pick. I think it's a relatively safe bug fix though. Since the controller was enabled by default in 1.18 it's probably worth fixing.

/lgtm

**Comment by ping035627** [comment]
Need cherry-pick-approved label, thanks!

**Comment by ping035627** [comment]
@kubernetes/release-managers

**Comment by ping035627** [comment]
@hasheddan Hi, can you review this pr? Need cherry-pick-approved label, thanks!

**Comment by ping035627** [comment]
@tpepper Hi, can you review this pr? Need cherry-pick-approved label, thanks!

**Comment by tpepper** [comment]
Checking on https://github.com/kubernetes/kubernetes/pull/94095 to see if it was just missed otherwise is preferable to keep things in sync and merge both the 1.18 and 1.17 variants of the cherry pick.

**Comment by robscott** [comment]
Sorry I'd missed the rebase earlier!

/lgtm

**Pull request merged**
