### PR TITLE
golangci-lint update and support for Go 1.21

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

v1.54.0 is the first release with official support for Go 1.21. go-ruleguard
must be >= 0.3.20 because of
https://github.com/quasilyte/go-ruleguard/issues/449 with Go
1.21. golangci-lint itself doesn't depend on a recent enough release yet, so
this was done manually.
    
One downside of updating golangci-lint to v1.54.0 without also updating
logcheck is that golangci-lint now complains about logcheck using the old
plugin API:
    
        ERROR: level=warning msg="plugin: 'AnalyzerPlugin' plugins are deprecated, please use the new plugin signature: https://golangci-lint.run/contributing/new-linters/#create-a-plugin"

Related-to: https://github.com/kubernetes/release/issues/3076

#### Special notes for your reviewer:

There is an [issue with go-critic and ruleguard](https://github.com/go-critic/go-critic/issues/1359) which needs a workaround in `verify-golangci-lint.sh`: the Go toolchain used for compiling the linter must not be inside a Go module.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
This is WIP because:
- [ ] new golangcli-lint has to be released
- [ ] https://github.com/kubernetes-sigs/logtools/pull/18 needs to be merged and included in a release
- [ ] [templating and inlining support](https://github.com/kubernetes/kubernetes/pull/118502) for the `logcheck.conf` needs to be merged

**Comment by liggitt** [comment]
there may be a fix for the go1.21 / go-critic issue to try, see https://github.com/kubernetes/kubernetes/pull/119037#issuecomment-1672150122

**Comment by pohly** [comment]
I've tried that fix by bumping the github.com/quasilyte/go-ruleguard dependency and that seems to work.

**Comment by liggitt** [comment]
In order to bump release branches to go1.21, we'll need to pick any *required* changes to support go1.21 back. Can this PR be split into the minimal set to run on go1.21, and a follow-up to switch to the new plugin interface to keep the size of the backports as small as possible?

**Comment by pohly** [comment]
This PR now only has the golangci-lint and ruleguard update.

I filed an issue about the plugin warning: https://github.com/golangci/golangci-lint/issues/4001

**Comment by pohly** [comment]
https://github.com/golangci/golangci-lint/pull/4002/files added an env variable for suppressing the warning. This is included in this PR now.

**Comment by pohly** [comment]
/hold 

To prevent merging without additional approval from someone else.

**Comment by liggitt** [comment]
/lgtm
/approve
/hold cancel

go ahead and open picks to release-1.25+ branches once this merges so those will be prepped for go1.21 whenever it makes it back to those branches

**Comment by pohly** [comment]
Cherry-picks created.

**Pull request merged**
