### PR TITLE
test_context.go: add "windows" to the list of options for "--node-os-distro"

### PR DESCRIPTION
**Pull request by jayunit100**
/kind cleanup

Quick update to windows flag for NodeOSDistro.

### CODE REVIEW

**Review by oomichi — COMMENTED** [review]
/triage accepted
/lgtm

**Review by neolit123 — COMMENTED** [review]
/approve

**Comment by neolit123** [comment]
/priority backlog
should be able to merge post the 1.20 release.

**Comment by neolit123** [comment]
/retitle test_context.go: add "windows" to the list of options for "--node-os-distro"

**Pull request merged**
