### PR TITLE
upgrade k8s to v1.1.2 on ubuntu

### PR DESCRIPTION
**Pull request by dalanlan**
- upgrade k8s to v1.1.2 on ubuntu
- fix quote thing: $PROXY_SETTING could expect blank within

### CODE REVIEW

**Comment by robdaemon** [comment]
@dalanlan - Looks like I have the same PROXY_SETTING fix in #17615 :)

**Comment by resouer** [comment]
@robdaemon Thanks for your work! Actually you guys are not fixing the same issue, just incidentally included a same minor fix in the PR. So, don't mind it.

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
