### PR TITLE
Fix updated github link

### PR DESCRIPTION
**Pull request by hnwolf**
In github, the document is changed to other name and I fix it in Kubernetes.

### CODE REVIEW

**Comment by apelisse** [comment]
that seems wrong, I don't think we edit vendor files directly.

I do expect the tests to fail here:
/ok-to-test

**Comment by apelisse** [comment]
> diff -Naupr -x BUILD -x 'AUTHORS*' -x 'CONTRIBUTORS*' vendor/github.com/elazarl/goproxy/doc.go /tmp/gopath.QSCp8E/src/k8s.io/kubernetes/vendor/github.com/elazarl/goproxy/doc.go
> --- vendor/github.com/elazarl/goproxy/doc.go	2019-02-21 04:14:35.167929578 +0000
> +++ /tmp/gopath.QSCp8E/src/k8s.io/kubernetes/vendor/github.com/elazarl/goproxy/doc.go	2019-02-21 04:26:54.689630257 +0000
> @@ -67,7 +67,7 @@ we close the body of the original repson
>  
>  Example use cases:
>  
> -1. https://github.com/elazarl/goproxy/tree/master/examples/goproxy-stats
> +1. https://github.com/elazarl/goproxy/tree/master/examples/goproxy-avgsize
>  
>  To measure the average size of an Html served in your site. One can ask
>  all the QA team to access the website by a proxy, and the proxy will
> Godeps Verify failed.

As expected, what are you trying to do?

**Comment by hnwolf** [comment]
@apelisse: Thank for your comment, I will left for vendor update the link.

**Pull request closed without merging**
