### PR TITLE
Enforce strict handling of deprecated APIs in alpha

### PR DESCRIPTION
**Pull request by liggitt**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Turns off deprecated APIs that will no longer be served in 1.26 ahead of beta, so we can start flushing out usage during alpha.

#### Does this PR introduce a user-facing change?
```release-note
ACTION REQUIRED: Deprecated beta APIs scheduled for removal in 1.26 are no longer served. See https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-26 for more information. 
```

/cc @deads2k 
/milestone v1.26

### CODE REVIEW

**Comment by dims** [comment]
Looks like we are trying again:
- https://github.com/kubernetes/kubernetes/pull/111784
- https://github.com/kubernetes/kubernetes/pull/108797

@liggitt wanna copy over the release note from https://github.com/kubernetes/kubernetes/pull/108797#issue-1173724457 ?

/lgtm

**Comment by liggitt** [comment]
yeah, updated

**Comment by liggitt** [comment]
rebased

**Pull request merged**
