### PR TITLE
Automated cherry pick of #65726: Update to go1.10.3

### PR DESCRIPTION
**Pull request by ixdy**
Cherry pick of #65726 on release-1.11.

#65726: Update to go1.10.3

### CODE REVIEW

**Comment by ixdy** [comment]
I've also added a commit to update rules_go from 0.10.4 to 0.10.5. It includes minor bug fixes as well as go1.10.3 support.

**Review by mkumatag — APPROVED** [review]

**Comment by foxish** [comment]
Not sure which sig this should be tagged under. @cblecker @ixdy

**Pull request merged**
