### PR TITLE
Fix Spelling error about [errrors]

### PR DESCRIPTION
**Pull request by heqg**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
Fix Spelling error about [errrors]

Which issue(s) this PR fixes:

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

```release-note
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

### CODE REVIEW

**Comment by ehashman** [comment]
Hi @heqg,

Per our PR policy on [trivial edits](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits), I am not sure this PR adds much value---it appears to be fixing a typo in a third-party file. You might want to try fixing the typo upstream?

/close

**Comment by lavalamp** [comment]
/reopen

This part of the file is not forked.

/lgtm
/approve

**Comment by ehashman** [comment]
/ok-to-test

although it seems to be testing just fine

**Comment by heqg** [comment]
> /ok-to-test
> 
> although it seems to be testing just fine



hi @lavalamp
Recnetly. I want to apply for a member in commmunity, can you sponsor me and reply +1 ? 
Because In the last year, I have been engaged in kubenetes related work. 
Besides, I want to make my own contributions to the community, and also to improve my abilities. 
I am sure that If I can become a member, I will make greater efforts to contribute to the community, and I can do better in future.

Looking forward to get your sponsorship.

my apply address is https://github.com/kubernetes/org/issues/2407
Thank you very much. Thanks again.

**Pull request merged**
