### PR TITLE
added more fields in type Fake struct for improving tests

### LINKED ISSUE #108181: support specifiy node resources  in kubemark
### What would you like to be added?

support specifiy node resources  in kubemark

### Why is this needed?

make hollow nodes  with various capacity is neccessary, especially when doing some test related to scheduler

a sample solution is support pass args to cadivisor fake

eg: kubemark --cpu=10 --memory=24Gi ......

and pass through to pkg/kubelet/cadvisor/testing/cadvisor_fake.go

```go
type Fake struct {
	NodeName       string
	NumCores       int
	MemoryCapacity uint64
}
```go

### PR DESCRIPTION
**Pull request by NikhilSharmaWe**
#### What type of PR is this?

/kind feature
#### What this PR does / why we need it:
supports specifiy node resources in kubemark
#### Which issue(s) this PR fixes:

Fixes #108181

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by NikhilSharmaWe** [comment]
@xrmzju and @MadhavJivrajani Could you please explain after changing the `type Fake struct`, how and what changes will it need to improve the tests. Also what is the use of [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cadvisor/testing/cadvisor_fake.go#L42) line in the code and will it effect the tests when we change the `type Fake struct`.

Looking forward to collaborate.

**Comment by SergeyKanzhelev** [comment]
/close

please re-open once it's needed. As described, it is unclear what PR is trying to achieve and impossible to review it adequately. Thank you for your contribution

**Pull request closed without merging**
