### PR TITLE
generate-cert: allow for alternative paths

### PR DESCRIPTION
**Pull request by eparis**
Instead of hard coding kube-cert and /srv/kubernetes allow these to be
overwritten by environment variables.  / is immutable on some systems
and so /srv is not a possible location to store data.

### CODE REVIEW

**Comment by eparis** [comment]
@jeffbean

**Comment by eparis** [comment]
came from a discussion in #9213

**Comment by jeffbean** [comment]
Also the addon script here: `kubernetes/cluster/saltbase/salt/kube-addons/kube-addons.sh` has /srv/kubernetes hardcoded.

**Comment by eparis** [comment]
ok, updated it there as well.

**Comment by saad-ali** [comment]
Assigning @erictune 
v1.0 triage needed

**Comment by erictune** [comment]
This looks good and is low risk.  But, since we are so close to cutting a 1.0 release candidate, we aren't taking any code changes except bug fixes.  We should be able to merge this no problem after 1.0 is released.

**Comment by erictune** [comment]
needs rebase.
LGTM.
It looks like several of the non-salt distros are using this script.

Wonder if it is practical to move this file out of cluster/saltbase and into someplace like cluster/common.  @zmerlynn can you comment on previous two sentences.

**Comment by mikedanese** [comment]
@eparis needs rebase

**Comment by jeffbean** [comment]
@eparis What about our newest version over here? https://github.com/GoogleCloudPlatform/kubernetes/blob/master/contrib/ansible/roles/kubernetes/files/make-ca-cert.sh 

Pending the fix posted here: https://github.com/GoogleCloudPlatform/kubernetes/pull/11837

**Comment by alex-mohr** [comment]
LGTM was before last commit, removing LGTM

**Comment by alex-mohr** [comment]
@k8s-bot test this [contrib/submit-queue: candidate for merging]

**Comment by alex-mohr** [comment]
@k8s-bot test this [testing build queue, sorry for the noise]

**Pull request merged**
