### PR TITLE
Remove useless master component images after saving image as tar file.

### PR DESCRIPTION
**Pull request by dchen1107**
cc/ @ixdy @ArtfulCoder 

This pr should prevent disk full issue caused by uncleaned master component images.

### CODE REVIEW

**Comment by ixdy** [comment]
LGTM. Jenkins PR builder seems to show this doing the right thing, too:

```
+++ [0528 14:41:07] Starting Docker build for image: kube-apiserver
+++ [0528 14:41:07] Starting Docker build for image: kube-controller-manager
+++ [0528 14:41:07] Starting Docker build for image: kube-scheduler
+++ [0528 14:41:13] Deleting docker image gcr.io/google_containers/kube-scheduler:06f6b1f50dd3706f2a27696d637e692e
+++ [0528 14:41:15] Deleting docker image gcr.io/google_containers/kube-controller-manager:4fda5aea4e4663c3e833ad955bcf7c35
Untagged: gcr.io/google_containers/kube-scheduler:06f6b1f50dd3706f2a27696d637e692e
Deleted: c2965f2a184a0ccf3b102343e98a9b9cf39cda4b1a19424e863737a9352a8d81
Untagged: gcr.io/google_containers/kube-controller-manager:4fda5aea4e4663c3e833ad955bcf7c35
Deleted: 66e94061c449e0f37496e7afde87ed6fbb7562dbd7ecd635426182b34a08b09a
+++ [0528 14:41:19] Deleting docker image gcr.io/google_containers/kube-apiserver:ae17605d353a3981e88bc9f0cccd0998
Untagged: gcr.io/google_containers/kube-apiserver:ae17605d353a3981e88bc9f0cccd0998
Deleted: aad0db4db39ea272a9772e648a1d1f1089d23b504e5d1cd84d1af010732ec7d4
+++ [0528 14:41:22] Docker builds done
```

Thanks!

**Comment by zmerlynn** [comment]
I don't think this is consistently working. We've had several failed builds with logs like:

```
+++ [0530 09:06:18] Starting Docker build for image: kube-scheduler
+++ [0530 09:06:19] Deleting docker image gcr.io/google_containers/kube-scheduler:dfc5261458a6d8bfa3a0454eaca66d5a
Error response from daemon: EOF
time="2015-05-30T09:06:20-07:00" level=fatal msg="Error: failed to remove one or more images" 
!!! Error in /jenkins-master-data/jobs/kubernetes-build/workspace/hack/e2e-internal/../../cluster/gce/../../cluster/../build/../build/common.sh:636
  '"${DOCKER[@]}" rmi ${docker_image_tag}' exited with status 1
Call stack:
  1: /jenkins-master-data/jobs/kubernetes-build/workspace/hack/e2e-internal/../../cluster/gce/../../cluster/../build/../build/common.sh:636 kube::release::create_docker_images_for_server(...)
  2: /jenkins-master-data/jobs/kubernetes-build/workspace/hack/e2e-internal/../../cluster/gce/../../cluster/../build/../build/common.sh:573 kube::release::package_server_tarballs(...)
  3: /jenkins-master-data/jobs/kubernetes-build/workspace/hack/e2e-internal/../../cluster/gce/../../cluster/../build/../build/common.sh:510 kube::release::package_tarballs(...)
  4: /jenkins-master-data/jobs/kubernetes-build/workspace/hack/e2e-internal/../../cluster/gce/../../cluster/../build/release.sh:40 main(...)
Exiting with status 1
```

But it's flaky. Investigating.

**Comment by zmerlynn** [comment]
The good news is that #9042 kind of gets builds back running. The bad news is that I inspected the wrong image and didn't just glance at a full `docker images` output, so my analysis was wrong. `docker images` clearly shows things still around, so we're now leaking images (again).

I tried this manually on Jenkins, picking on an old image:
```
gcr.io/google_containers/kube-controller-manager   418b9a7e072b0668e3ef6645c714dfd4   0827dc3d3acd        29 hours ago        29.26 MB
gcr.io/google_containers/kube-apiserver            38d25cb080790897ad11b20881f2ba47   0e31d4e5d31d        29 hours ago        36.37 MB
gcr.io/google_containers/kube-scheduler            bb49bf866e6da81b9d0e695aa6eac76b   7eaa0abc15c9        29 hours ago        20.37 MB
root@jenkins-master:~# docker rmi gcr.io/google_containers/kube-controller-manager:418b9a7e072b0668e3ef6645c714dfd4
Error response from daemon: EOF
FATA[0000] Error: failed to remove one or more images   
```

**Comment by zmerlynn** [comment]
Anyways, someone can pick this back up later. It seems to work reasonably in a dev environ. Jenkins may actually have something more systemically wrong.

**Pull request merged**
