### PR TITLE
check admit for ConnectResource in resthandler.go

### PR DESCRIPTION
**Pull request by seanchann**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37282)

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by smarterclayton** [comment]
`admit` I don't think should ever be nil.  How did you hit this?

**Comment by seanchann** [comment]
for some reason, use separate apiserver, it may be not config admit

**Comment by smarterclayton** [comment]
We have "no-op" admission chains for that.  Generally we don't check for
null on structural interfaces (because it increases the chance of bugs and
complicates the code).

On Nov 22, 2016, at 8:27 PM, seanchann.zhou <notifications@github.com>
wrote:

for some reason, use separate apiserver, it may be not config admit

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/37282#issuecomment-262421800>,
or mute the thread

**Comment by seanchann** [comment]
@smarterclayton  I agree with you.  but, other places have similar checks.   not check it will be work for k8s.  but not fill my situation,  may be i need to fork it, thanks!

**Comment by smarterclayton** [comment]
If we check admit != nil elsewhere, then this is ok.  I notice you changed the filesystem permissions for the file, can you change those back?

**Comment by seanchann** [comment]
@k8s-bot kops aws e2e test this

**Comment by seanchann** [comment]
Implementing authorization for child resource. if want to match sub resource in `abac` policy file, will broken.

**Comment by smarterclayton** [comment]
@k8s-bot cvm gke e2e test this
@k8s-bot gce etcd3 e2e test this

**Comment by seanchann** [comment]
File name and file location is changed, do I need to regenerate pr, close the current pr

**Comment by seanchann** [comment]
I signed it!

**Comment by seanchann** [comment]
@k8s-ci-robot  I signed it!

**Comment by smarterclayton** [comment]
You can either open a new one or simply reset your branch to HEAD and then make your patch and force push to the PR branch.

**Comment by seanchann** [comment]
@k8s-ci-robot  I signed it!

**Comment by smarterclayton** [comment]
Looks like this still has all the conflicts.  If you can rebase and push the right code please reopen.

**Pull request closed without merging**
