### PR TITLE
Backport fix for flaky ESIPP test to 1.21

### PR DESCRIPTION
**Pull request by jupblb**
#### What type of PR is this
/kind flake

#### What this PR does / why we need it:
Backport fix for #103058 as [testgrid](https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness) is green
#### Which issue(s) this PR fixes:

N/A, followup after https://github.com/kubernetes/kubernetes/pull/103071

#### Special notes for your reviewer:
/assign @jkaniuk 
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by ialidzhikov** [comment]
/assign @MrHohn
for approval

**Review by MrHohn — APPROVED** [review]
/lgtm
/approve

**Comment by aojea** [comment]
/ok-to-test
ping @kubernetes/release-managers

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
Fixed the release note in the original comment.

**Pull request merged**
