### PR TITLE
Remove mention about --etcd-config from kube-apiserver options

### PR DESCRIPTION
**Pull request by maclof**
The --etcd-config option has been removed from kube-apiserver so we no longer need to mention about it being mutually exclusive.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Thanks.
Travis is complaining that you need to run `hack/update-generated-docs.sh`

**Comment by maclof** [comment]
Thanks @nikhiljindal 

I'm getting this error when running the command:

```bash
maclof@de1 ~/kubernetes # ./hack/update-generated-docs.sh
Go version: go version go1.6 linux/amd64
+++ [0322 20:49:15] Building go targets for linux/amd64:
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genbashcomp
    cmd/mungedocs
+++ [0322 20:50:39] Placing binaries
output: fatal: Not a valid object name upstream/release-1.2
,
ERROR: exit status 128
`git ls-tree -r --name-only upstream/release-1.2 failed. We'll ignore this error locally, but Jenkins may pick an error. Munger uses the output of this command to determine in unversioned warning, if it should add a link to the doc in release branch.
/home/maclof/kubernetes/docs/admin/kube-apiserver.md
----
unversioned-warning:
contents were modified

analytics:
contents were modified

output: fatal: Not a valid object name upstream/release-1.2
,
ERROR: exit status 128
`git ls-tree -r --name-only upstream/release-1.2 failed. We'll ignore this error locally, but Jenkins may pick an error. Munger uses the output of this command to determine in unversioned warning, if it should add a link to the doc in release branch.
```

**Comment by maclof** [comment]
Sorry ignore that error.

**Comment by nikhiljindal** [comment]
Yes as it says it ignores that error locally.
It says that it modified kube-apiserver.md. Just include that change in the PR

**Comment by nikhiljindal** [comment]
thanks, lgtm.

@k8s-bot ok to test

**Pull request merged**
