### PR TITLE
CHANGELOG: fix punctuation errors in 1.22

### PR DESCRIPTION
**Pull request by songxiao-wang87**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
none

Which issue(s) this PR fixes:
none

Special notes for your reviewer:
none

Does this PR introduce a user-facing change?
none

```release-note

NONE

```

### CODE REVIEW

**Comment by wilsonehusin** [comment]
I will defer this to 1.22 release notes lead

/unassign
/assign @pmmalinov01

**Comment by pmmalinov01** [comment]
Thanks for the heads up @wilsonehusin. Also thank you @songxiao-wang87 for this PR. If you want you can join the slack channel [release-notes](https://kubernetes.slack.com/archives/CN1KH4K9A) if you want to contribute or monitor the release notes, also keep an eye for the shadow program if you want to be part of the next release cycle of Kubernetes.

/lgtm
/approve

**Pull request merged**
