### PR TITLE
Remove mutex for extender prioritization in PrioritizeNodes

### PR DESCRIPTION
**Pull request by tedyu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
In PrioritizeNodes, the loop over extenders uses mutex to guard against concurrent access per host.

This PR removed the mutex by introducing scores data structure which is indexed by extender and host.

```release-note
NONE
```

### CODE REVIEW

**Comment by ahg-g** [comment]
I guess this PR conflicts with #78339. Do you have any performance numbers measuring which one performs better?

**Comment by tedyu** [comment]
performance numbers are yet to be collected.

**Pull request closed without merging**
