### PR TITLE
cleanup: use sets.Len() insead of len(sets.List())

### PR DESCRIPTION
**Pull request by binacs**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Get the length directly to avoid memory allocation.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Review by alexzielenski — APPROVED** [review]
This seems like a great change. As you said the `List()` function allocates an entire list.

/lgtm

**Comment by BinacsLee** [comment]
kindly ping @deads2k for approval

**Comment by BinacsLee** [comment]
kindly ping @liggitt for approval

**Comment by liggitt** [comment]
/lgtm
/approve

fwiw, the allocation here doesn't really matter since this is done a single time at startup

**Pull request merged**
