### PR TITLE
fix: use `ErrorContains(t, err` instead of `Contains(t, err.Error()`

### PR DESCRIPTION
**Pull request by mmorel-35**
#### What type of PR is this?

/area test
/kind cleanup
/priority backlog
/sig testing

#### What this PR does / why we need it:

This remplaces  `Contains(t, err.Error()` by  `ErrorContains(t, err`  as it is simpler to read and safer as err is checked for nullity before `err.Error()` being called.

### CODE REVIEW

**Review by ffromani — COMMENTED** [review]
/ok-to-test

**Review by ffromani — COMMENTED** [review]
LGTM for `pkg/kubelet/cm/...`

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Pull request merged**
