### PR TITLE
Remove pod status.phase check from pod event handlers

### PR DESCRIPTION
**Pull request by bsalamat**
**What this PR does / why we need it**:
The scheduler pod informer already filters out pods which are terminated (succeeded or failed). As a result, we do not need to check pods' phase again in the scheduler event handlers.

**Release note**:

```release-note
NONE
```

/sig scheduling

### CODE REVIEW

**Review by yastij — APPROVED** [review]
/lgtm

**Comment by yastij** [comment]
/hold

Mostly LGTM but adding a hold, feel free to remove it once everyone is okay

**Review by misterikkit — COMMENTED** [review]
/lgtm

**Pull request merged**
