### PR TITLE
Fix the method name of BuiltInAuthenticationOptions.WithAnyonymous

### PR DESCRIPTION
**Pull request by ghost**
change the BuiltInAuthenticationOptions.WithAnyonymous to
WithAnonymous would be better.

**What this PR does / why we need it**:
The BuiltInAuthenticationOptions.WithAnyonymous method name should be a meaningful name of  WithAnonymous

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by yujunzhang** [comment]
check cla authorized

**Comment by zhangxiaoyu-zidif** [comment]
It‘s a typo
LGTM

**Review by zhangxiaoyu-zidif — APPROVED** [review]

**Comment by zhangxiaoyu-zidif** [comment]
@yujunzhang 
Did you sign CLA yet?

**Comment by yujunzhang** [comment]
recheck CLA authorized.

**Comment by yujunzhang** [comment]
recheck

**Review by FengyunPan — APPROVED** [review]

**Pull request merged**
