### PR TITLE
enable profiling by default in kube-proxy

### LINKED ISSUE #98410: Enable profiling by default in kube-proxy
**What would you like to be added**:

Enable profiling by default in kube-proxy.

**Why is this needed**:
Profiling is a very useful feature when debugging performance issues. Except kube-proxy, other k8s components all enable profile by default. 

kube-apiserver, kubelet and kube-scheduler also support dynamically setting log level, which depends on enabling profiling.

### PR DESCRIPTION
**Pull request by borgerli**
**What type of PR is this?**
/kind feature
/sig network

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #98410

**Does this PR introduce a user-facing change?**:
```release-note
Profiling is enabled by default in the kube-proxy. 
```

### CODE REVIEW

**Comment by aojea** [comment]
@deads2k it seems  you've enabled it in all the other components https://github.com/kubernetes/kubernetes/commit/aa07992a44186452de261ba0bdd3a4afb5dfe678 , is really recommended to enable profiling by default?
I feel old here, I always assumed it is something to not enable it in production ...

**Comment by bowei** [comment]
We have to be careful about changing /defaults/. Is there a strong motivation to make this choice for downstream consumers?

Any particular user/distribution of Kubernetes can always flip the flag to true on their own wrt their own policy...

**Comment by knabben** [comment]
@borgerli any updates on this? if we are not enabling it, can we close the ticket?

**Pull request closed without merging**
