### PR TITLE
fix a few typos i ran into during setup

### PR DESCRIPTION
**Pull request by mattf**

### CODE REVIEW

**Comment by yujuhong** [comment]
LGTM. Thanks for the PR! Could you sign the CLA so that I can merge the PR?

**Comment by a-robinson** [comment]
I don't believe we should be making changes to Godeps packages. Fixes for those should go to the upstream repository (github.com/miekg/dns, in this case)

**Comment by yujuhong** [comment]
@a-robinson, uhh you're right. The file paths escaped my eye. The rest of the (non-Godeps) changes look good.

**Comment by mattf** [comment]
fyi - https://github.com/miekg/dns/pull/182

**Comment by mattf** [comment]
> LGTM. Thanks for the PR! Could you sign the CLA so that I can merge the PR?

i work for red hat and should be covered by the corp cla, matt@redhat.com

**Pull request merged**
