### PR TITLE
[WIP] Fix cluster scripts to support arm64 GCE tests

### PR DESCRIPTION
**Pull request by upodroid**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
This PR adds support for running e2e tests on arm64 gce nodes with kubetest2.

kubetest2 changes https://github.com/kubernetes-sigs/kubetest2/pull/240
#### Special notes for your reviewer:

The VMs are being created properly right now, but the kube api is failing to run on the master instance.

I'm running kubetest2 with the following flags:

```
# you'll need to build the version of kubetest2 in the PR above to get this to run.
kubetest2 gce -v=2 --repo-root=. --up --down --legacy-mode --target-build-arch=linux/arm64 --gcp-project=borg-env  --master-size=t2a-standard-2  --node-size=t2a-standard-2  --env=KUBE_MASTER_OS_DISTRIBUTION=ubuntu  --env=KUBE_IMAGE_FAMILY=ubuntu-2204-lts-arm64  --env=KUBE_NODE_OS_DISTRIBUTION=ubuntu --env=KUBE_GCE_MASTER_PROJECT=ubuntu-os-cloud --env=KUBE_GCE_NODE_PROJECT=ubuntu-os-cloud
```
/cc @dims @chendave @ruquanzhao 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by upodroid** [comment]
I'm seeing the following:

```
root@kt2-1c8cd36a-6b85-master:/home/mahamed# netstat -tlpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      477/systemd-resolve
tcp        0      0 127.0.0.1:45161         0.0.0.0:*               LISTEN      4756/containerd
tcp        0      0 10.128.0.2:2380         0.0.0.0:*               LISTEN      5437/etcd
tcp        0      0 10.128.0.2:2381         0.0.0.0:*               LISTEN      5444/etcd
tcp        0      0 127.0.0.1:8134          0.0.0.0:*               LISTEN      5382/proxy-server
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      890/sshd: /usr/sbin
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      4834/kubelet
tcp6       0      0 :::4002                 :::*                    LISTEN      5444/etcd
tcp6       0      0 :::8132                 :::*                    LISTEN      5382/proxy-server
tcp6       0      0 :::8133                 :::*                    LISTEN      5382/proxy-server
tcp6       0      0 :::10250                :::*                    LISTEN      4834/kubelet
tcp6       0      0 :::10255                :::*                    LISTEN      4834/kubelet
tcp6       0      0 :::2379                 :::*                    LISTEN      5437/etcd
tcp6       0      0 :::2382                 :::*                    LISTEN      5437/etcd
tcp6       0      0 :::22                   :::*                    LISTEN      890/sshd: /usr/sbin
root@kt2-1c8cd36a-6b85-master:/home/mahamed# systemctl status kubelet
● kubelet.service - Kubernetes kubelet
     Loaded: loaded (/etc/systemd/system/kubelet.service; disabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-08-23 22:42:05 UTC; 21min ago
   Main PID: 4834 (kubelet)
      Tasks: 13 (limit: 9459)
     Memory: 34.7M
        CPU: 12.528s
     CGroup: /system.slice/kubelet.service
             └─4834 /home/kubernetes/bin/kubelet --v=4 --serialize-image-pulls=false --cloud-provider=gce --experimental-mounter-path=/home/kubernetes/containerized_mounter/mounter --cert-dir=/var/lib/kubelet/pki/>

Aug 23 23:03:43 kt2-1c8cd36a-6b85-master kubelet[4834]: I0823 23:03:43.585269    4834 csi_plugin.go:913] Failed to contact API server when waiting for CSINode publishing: Get "https://34.72.78.127/apis/storage.k8s>
Aug 23 23:03:43 kt2-1c8cd36a-6b85-master kubelet[4834]: I0823 23:03:43.653406    4834 kuberuntime_manager.go:436] "Retrieved pods from runtime" all=true
Aug 23 23:03:43 kt2-1c8cd36a-6b85-master kubelet[4834]: E0823 23:03:43.765176    4834 event.go:289] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kt>
Aug 23 23:03:44 kt2-1c8cd36a-6b85-master kubelet[4834]: I0823 23:03:44.259586    4834 worker.go:222] "Probe target container not found" pod="kube-system/kube-apiserver-kt2-1c8cd36a-6b85-master" containerName="kube>
Aug 23 23:03:44 kt2-1c8cd36a-6b85-master kubelet[4834]: I0823 23:03:44.388215    4834 prober.go:139] "Exec-Probe runProbe" pod="kube-system/etcd-server-kt2-1c8cd36a-6b85-master" containerName="etcd-container" exec>
Aug 23 23:03:44 kt2-1c8cd36a-6b85-master kubelet[4834]: I0823 23:03:44.395740    4834 apiserver.go:50] "node sync has not completed yet"
Aug 23 23:03:44 kt2-1c8cd36a-6b85-master kubelet[4834]: I0823 23:03:44.456448    4834 exec.go:62] Exec probe response: "127.0.0.1:2379 is healthy: successfully committed proposal: took = 4.693323ms\n+ exec /usr/lo>
Aug 23 23:03:44 kt2-1c8cd36a-6b85-master kubelet[4834]: I0823 23:03:44.456494    4834 prober.go:116] "Probe succeeded" probeType="Liveness" pod="kube-system/etcd-server-kt2-1c8cd36a-6b85-master" podUID="d496122277>
Aug 23 23:03:44 kt2-1c8cd36a-6b85-master kubelet[4834]: I0823 23:03:44.585501    4834 csi_plugin.go:913] Failed to contact API server when waiting for CSINode publishing: Get "https://34.72.78.127/apis/storage.k8s>
Aug 23 23:03:44 kt2-1c8cd36a-6b85-master kubelet[4834]: I0823 23:03:44.654732    4834 kuberuntime_manager.go:436] "Retrieved pods from runtime" all=true

```

kubelet is complaining about failed cni config

**Comment by upodroid** [comment]
:( 

```
root@kt2-1c8cd36a-6b85-master:/home/kubernetes# cat /etc/kubernetes/manifests/* | grep amd64
  - image: gcr.io/k8s-ingress-image-push/ingress-gce-glbc-amd64:v1.23.1
    "image": "registry.k8s.io/kube-controller-manager-amd64:v1.29.0-alpha.0.203_210a97e48bc6ca",
    "image": "registry.k8s.io/kube-scheduler-amd64:v1.29.0-alpha.0.203_210a97e48bc6ca",
```

**Comment by neolit123** [comment]
is this PR and
https://github.com/kubernetes-sigs/kubetest2/pull/240
being done as part of some SIG effort?

please see:
https://github.com/kubernetes/kubernetes/issues/78995#issuecomment-1707025083

if possible, we should not touch the /cluster directory with more features.
k0ps already has ARM64 e2e tests.

**Pull request closed without merging**
