### PR TITLE
e2e_node/mount_rro_linux_test.go: remove unneeded WithSerial

### PR DESCRIPTION
**Pull request by AkihiroSuda**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Remove unneeded `WithSerial`.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:
None

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by ffromani** [comment]
thanks for your PR! why is the label not needed?

**Comment by AkihiroSuda** [comment]
> thanks for your PR! why is the label not needed?

Because the test does not seem to have anything that conflicts with other tests AFAICS

**Review by ffromani — COMMENTED** [review]
/lgtm

thanks for elaborating

**Comment by AkihiroSuda** [comment]
@tallclair Could you take a look?

**Review by endocrimes — APPROVED** [review]
/approve

**Pull request merged**
