### PR TITLE
GCE Windows: Upgrade to fluent-bit 1.7.7, 1.7.6 had a major regression.

### PR DESCRIPTION
**Pull request by jeremyje**
#### What type of PR is this?
/kind bug
/kind regression

#### What this PR does / why we need it:
Fluent-bit 1.7.6 has a regression that breaks Stackdriver Logs exporting.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
/sig windows
/hold
/priority important-soon

### CODE REVIEW

**Comment by jeremyje** [comment]
/unhold
1.7.7 is confirmed to work. There's other issues that will be fixed in a follow up change.

**Review by ibabou — APPROVED** [review]

**Pull request merged**
