### PR TITLE
cleanup useless functions

### PR DESCRIPTION
**Pull request by tianshapjq**
cleanup some useless functions, for they get no references from others during my search. Please remind me if I'm wrong.

### CODE REVIEW

**Comment by tianshapjq** [comment]
@brendanburns @dims I submit another commit for removing useless variables, not sure if is appropriate to commit in this branch. Correct me if i'm wrong :)

**Comment by brendandburns** [comment]
Deleting unused functions seems good to me. Deleting the constants seems less good, but I kind of have mixed feelings.

Can we limit this to deleting unused functions, and then do a separate PR for the constants?

**Comment by tianshapjq** [comment]
@brendanburns ok, I've reset this pr and created another one including variables deletion. at #57118 PTAL :)

**Pull request merged**
