### PR TITLE
Fix golint issue in pkg/apis/abac/latest

### PR DESCRIPTION
**Pull request by kaleocheng**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Fix golint failures of pkg/apis/abac/latest

**Which issue(s) this PR fixes**:
Ref https://github.com/kubernetes/kubernetes/issues/68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xichengliudui** [comment]
/priority backlog
/lgtm
thanks.

**Comment by kaleocheng** [comment]
@xichengliudui not sure why I got those two tests failed.  any suggestion?

**Pull request merged**
