### PR TITLE
Fix make quick-release failures under bash 4.3

### LINKED ISSUE #77521: build/release.sh (hack/lib/golang.sh) requires minimum bash v4.4
**What happened**:  building Kubernetes release and it failed due to a variable not being set ([with `set -u` enabled](https://github.com/kubernetes/kubernetes/blob/caf9d94d697ce327e0c1c3dee71a1f06a6fc918e/build/release.sh#L25)). It appears a [recent commit](https://github.com/kubernetes/kubernetes/commit/dcee810a3f544cd0669c252945b29bfeedcd119b) does not function as expected on `bash v4.3` (used Ubuntu 16). Additional details will be provided in comment below
```
kubernetes/hack/lib/golang.sh: line 295: KUBE_SERVER_PLATFORMS[@]: unbound variable
```

**What you expected to happen**: successful build of Kuberentes release or documented minimum supported OS releases (i.e., bash versions)

**How to reproduce it (as minimally and precisely as possible)**: using Ubuntu 16 (`bash v4.3`), run [build/release.sh] using `release-1.14`, `v1.15.0-alpha.2` or `master` (containing https://github.com/kubernetes/kubernetes/commit/dcee810a3f544cd0669c252945b29bfeedcd119b or subsequent cherry pick)

**Anything else we need to know?**:  It appears the issue is with how `bash v4.3` and `bash v4.4` create `readonly` variables, where I believe `v4.3` does not create the variables with the expected scope (created using `local` scope versus `global` scope). This creates a minimum supported OS version when running `build/release.sh` from the best I can tell.

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.15.0-alpha.2` [`release-1.14`](https://github.com/kubernetes/kubernetes/commit/ffa6160e087d699282daca15085f9cb968240b80)
- Cloud provider or hardware configuration:  N/A
- OS (e.g: `cat /etc/os-release`):
```
release 
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- Kernel (e.g. `uname -a`):  `Linux armada-lb-build 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:  `build/release.sh`
- Network plugin and version (if this is a network-related bug):  N/A
- Others:

/sig release

### PR DESCRIPTION
**Pull request by dims**
Change-Id: I83cc56c5d234eb87cb749fa22d7eafe88878e9f1

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #77521

**Special notes for your reviewer**:
We use the same technique as used in https://github.com/kubernetes/kubernetes/pull/74970/files

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
both `make quick-release` not `make quick-release-images` should work now.

**Comment by BenTheElder** [comment]
Both flakes are unrelated.

**Comment by BenTheElder** [comment]
/retest
we should consider updating the CI docker

**Comment by cblecker** [comment]
I'm not sure this is the right fix.. we always expect these to be set, don't we?

**Comment by dims** [comment]
@cblecker seems to be doing the right thing looking at the logs..

**Comment by BenTheElder** [comment]
+1 on not sure, are we failing to set these somewhere? is this a bug in quick-release-images or kind? (if so sorry about that!) I feel like I'm missing something here

**Comment by BenTheElder** [comment]
xref: https://github.com/theopenlab/openlab/issues/254#issuecomment-492065808

**Comment by dims** [comment]
@BenTheElder i have a ubuntu box where i can recreate the problem 

```
dims@bigbox:~/go/src/k8s.io/kubernetes$ uname -a
Linux bigbox 4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
dims@bigbox:~/go/src/k8s.io/kubernetes$ cat /etc/*release*
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /etc/lsb-release
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ DISTRIB_ID=Ubuntu
   2   │ DISTRIB_RELEASE=16.04
   3   │ DISTRIB_CODENAME=xenial
   4   │ DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /etc/os-release
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ NAME="Ubuntu"
   2   │ VERSION="16.04.5 LTS (Xenial Xerus)"
   3   │ ID=ubuntu
   4   │ ID_LIKE=debian
   5   │ PRETTY_NAME="Ubuntu 16.04.5 LTS"
   6   │ VERSION_ID="16.04"
   7   │ HOME_URL="http://www.ubuntu.com/"
   8   │ SUPPORT_URL="http://help.ubuntu.com/"
   9   │ BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
  10   │ VERSION_CODENAME=xenial
  11   │ UBUNTU_CODENAME=xenial
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by dims** [comment]
bash

```
dims@bigbox:~/go/src/k8s.io/kubernetes$ bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by dims** [comment]
output from `make quick-release`

```
dims@bigbox:~/go/src/k8s.io/kubernetes$ make quick-release
+++ [0514 11:05:30] Verifying Prerequisites....
+++ [0514 11:05:31] Building Docker image kube-build:build-c7769b13af-5-v1.12.5-1
+++ [0514 11:05:41] Syncing sources to container
+++ [0514 11:05:47] Running build command...
+++ [0514 11:06:31] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/cloud-controller-manager
    cmd/kubelet
    cmd/kubeadm
    cmd/hyperkube
    cmd/kube-scheduler
    vendor/k8s.io/apiextensions-apiserver
    cluster/gce/gci/mounter
+++ [0514 11:07:59] Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kubeadm
    cmd/kubelet
+++ [0514 11:08:44] Building go targets for linux/amd64:
    cmd/kubectl
+++ [0514 11:09:07] Building go targets for linux/amd64:
    cmd/gendocs
    cmd/genkubedocs
    cmd/genman
    cmd/genyaml
    cmd/genswaggertypedocs
    cmd/linkcheck
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
+++ [0514 11:10:22] Building go targets for linux/amd64:
    cmd/kubemark
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e_node/e2e_node.test
+++ [0514 11:11:23] Syncing out of container
+++ [0514 11:11:46] Building tarball: src
+++ [0514 11:11:46] Building tarball: manifests
+++ [0514 11:11:46] Starting tarball: client linux-amd64
+++ [0514 11:11:46] Waiting on tarballs
+++ [0514 11:11:50] Building tarball: final
+++ [0514 11:11:50] Waiting on test tarballs
+++ [0514 11:11:50] Building tarball: test portable
+++ [0514 11:11:51] Building tarball: test mondo (deprecated by KEP sig-testing/20190118-breaking-apart-the-kubernetes-test-tarball)
```

**Review by fejta — APPROVED** [review]
/lgtm
/approve

**Comment by cblecker** [comment]
/hold

I really thing there’s something up with this. Let me test locally..

**Comment by spiffxp** [comment]
From the original issue:

>It appears the issue is with how bash v4.3 and bash v4.4 create readonly variables, where I believe v4.3 does not create the variables with the expected scope (created using local scope versus global scope)

Is `export readonly` a bad idea?

**Comment by cblecker** [comment]
/lgtm cancel
/hold

Confirmed that this is the wrong fix. This fixes the bash errors, by skipping parts of the build. What it should look like:
```
+++ [0514 15:09:28] Syncing out of container
+++ [0514 15:10:14] Building tarball: manifests
+++ [0514 15:10:14] Building tarball: src
+++ [0514 15:10:14] Starting tarball: client darwin-amd64
+++ [0514 15:10:14] Starting tarball: client linux-amd64
+++ [0514 15:10:14] Waiting on tarballs
+++ [0514 15:10:22] Building tarball: node linux-amd64
+++ [0514 15:10:22] Building images: linux-amd64
+++ [0514 15:10:23] Starting docker build for image: cloud-controller-manager-amd64
+++ [0514 15:10:23] Starting docker build for image: kube-apiserver-amd64
+++ [0514 15:10:23] Starting docker build for image: kube-controller-manager-amd64
+++ [0514 15:10:23] Starting docker build for image: kube-scheduler-amd64
+++ [0514 15:10:23] Starting docker build for image: kube-proxy-amd64
+++ [0514 15:10:23] Building hyperkube image for arch: amd64
+++ [0514 15:10:23] Building conformance image for arch: amd64
+++ [0514 15:10:43] Deleting docker image k8s.gcr.io/kube-scheduler:v1.15.0-alpha.3.279_0252a323423080
+++ [0514 15:10:43] Deleting docker image k8s.gcr.io/kube-proxy:v1.15.0-alpha.3.279_0252a323423080
+++ [0514 15:10:48] Deleting docker image k8s.gcr.io/cloud-controller-manager:v1.15.0-alpha.3.279_0252a323423080
+++ [0514 15:10:48] Deleting docker image k8s.gcr.io/kube-controller-manager:v1.15.0-alpha.3.279_0252a323423080
+++ [0514 15:10:49] Deleting docker image k8s.gcr.io/kube-apiserver:v1.15.0-alpha.3.279_0252a323423080
+++ [0514 15:11:01] Deleting hyperkube image k8s.gcr.io/hyperkube-amd64:v1.15.0-alpha.3.279_0252a323423080
+++ [0514 15:11:05] Deleting conformance image k8s.gcr.io/conformance-amd64:v1.15.0-alpha.3.279_0252a323423080
+++ [0514 15:11:06] Docker builds done
+++ [0514 15:11:06] Building tarball: server linux-amd64
+++ [0514 15:12:12] Building tarball: final
+++ [0514 15:12:12] Starting tarball: test linux-amd64
+++ [0514 15:12:12] Waiting on test tarballs
+++ [0514 15:12:42] Building tarball: test portable
+++ [0514 15:12:43] Building tarball: test mondo (deprecated by KEP sig-testing/20190118-breaking-apart-the-kubernetes-test-tarball)
```

In particular, we're not building node or server tarballs at all with this fix:
https://github.com/kubernetes/kubernetes/blob/0e224ad3f38d9ab0ffa34bcd0774458f5834b7fa/build/lib/release.sh#L91-L94

**Comment by BenTheElder** [comment]
> In particular, we're not building node or server tarballs at all with this fix:

just to clarify, this is in reference to `make quick-release`, since dims also mentioned `make quick-release-images` which intentionally does not build those.

**Comment by ShubhasisMathur** [comment]
I still see the error after running make quick-release.

Makefile.generated_files:152: recipe for target 'gen_deepcopy' failed
make[2]: *** [gen_deepcopy] Error 1
Makefile:557: recipe for target 'generated_files' failed
make[1]: *** [generated_files] Error 2
Makefile:518: recipe for target 'cross' failed
make: *** [cross] Error 1
!!! [0525 16:16:27] Call tree:
!!! [0525 16:16:27]  1: build/../build/common.sh:519 kube::build::run_build_command_ex(...)
!!! [0525 16:16:27]  2: build/release.sh:36 kube::build::run_build_command(...)
make: *** [Makefile:461: quick-release] Error 1

request to /sig/reopen ?

**Comment by ShubhasisMathur** [comment]
@dims , its throwing me the error after I run the make quick-release command. I am running this on aws Ec2 RHEL 8 box

**Comment by cblecker** [comment]
Need more output. What you’ve shown doesn’t indicate the error

**Comment by ShubhasisMathur** [comment]
SUre. attached is the full log.
[error.log](https://github.com/kubernetes/kubernetes/files/3219572/error.log)

**Comment by cblecker** [comment]
`fatal error: runtime: out of memory`

How much memory does your box have?

**Comment by ShubhasisMathur** [comment]
I have an ec2 of 20 gb memory. The box still has 15 GB memory on it.

**Pull request closed without merging**
