### PR TITLE
[WIP] debug netpol job flakiness

### PR DESCRIPTION
**Pull request by aojea**
/kind flake

**What this PR does / why we need it**:

The job is flaky, random test fail, usually showing symptons that can be related to endpoints or pods not coming up on time ... that is a theory though :/

xref: 
https://github.com/kubernetes/test-infra/pull/20367

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
let's see the results of https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/97690/pull-kubernetes-e2e-ubuntu-gce-network-policies/1346145859917582336/ :)

**Comment by knabben** [comment]
An odd behavior is the client connectivity pod test:
```Jan  4 11:46:21.235: INFO: Waiting for client-can-connect-80-db95g to complete.``` 

It should be Completed with `agnhost` 8 seconds internal timeout, but somehow the pod is still running.
```client-can-connect-81-cl5cs  bootstrap-e2e-minion-group-r9pm  Running  30s```

**Comment by aojea** [comment]
> An odd behavior is the client connectivity pod test:
> `Jan 4 11:46:21.235: INFO: Waiting for client-can-connect-80-db95g to complete.`
> 
> It should be Completed with `agnhost` 8 seconds internal timeout, but somehow the pod is still running, failing the test bootstrap.
> `client-can-connect-81-cl5cs bootstrap-e2e-minion-group-r9pm Running 30s`
> 
> This happens very often in the flaky old netpol ones.

do you have a link to the logs of that failure?

**Comment by knabben** [comment]
@aojea the last ones of the scheduled job shows it

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-network-policies/1346055461534699520

**Comment by aojea** [comment]
/hold
let me use this PR to try to debug more this
```
Jan  4 17:53:43.260: Pod pod-b-4cmhj should be able to connect to service svc-pod-a, but was not able to connect.
Pod logs:
REFUSED
REFUSED
REFUSED
REFUSED
REFUSED
```

refused can me that the service hasn't endpoints ... :thinking:

**Comment by aojea** [comment]
well, it seems that the old network policies tests are not causing the problem, new tests fail with connection refused messages too :/
```
Jan  4 18:56:07.787: Unexpected error, Failed to find "0-", last result: "connect failed: Connection refused
```

**Comment by aojea** [comment]
I found this message confusing :thinking:  I think is a bug
This is not a headless service, is a service that is not matching the pods
```
I0104 18:55:31.221840      10 utils.go:413] couldn't find ipfamilies for headless service: network-perf-3702/service-for-iperf-e2e. This could happen if controller manager is connected to an old apiserver that does not support ip families yet. EndpointSlices for this Service will use IPv4 as the IP Family based on familyOf(ClusterIP:10.0.98.217).
I0104 18:55:31.222288      10 taint_manager.go:400] Noticed pod update: types.NamespacedName{Namespace:"network-perf-3702", Name:"iperf-e2e-pod-0"}
I0104 18:55:31.222310      10 taint_manager.go:400] Noticed pod update: types.NamespacedName{Namespace:"kubelet-test-3660", Name:"busybox-readonly-fsef912123-9b88-4bc9-8902-fea8821887a4"}

```

**Comment by jayunit100** [comment]
These seem to be generally running alongside the other tests during failures... not sure wether they also are capable of slowing down the apiserver.
  
```
In general, ```
   2 {"msg":"PASSED [k8s.io] Container Lifecycle Hook when create a pod with lifecycle hook should execute poststart http hook properly [NodeConformance] [Conformance]","total":-1,"completed":10,"skipped":95,"failed":0}
   2 {"msg":"PASSED [k8s.io] Kubelet when scheduling a busybox command that always fails in a pod should have an terminated reason [NodeConformance] [Conformance]","total":-1,"completed":12,"skipped":211,"failed":0}
   2 {"msg":"PASSED [k8s.io] Variable Expansion should succeed in writing subpaths in container [sig-storage][Slow] [Conformance]","total":-1,"completed":6,"skipped":99,"failed":0}
   2 {"msg":"PASSED [sig-api-machinery] Garbage collector should keep the rc around until all its pods are deleted if the deleteOptions says so [Conformance]","total":-1,"completed":7,"skipped":45,"failed":0}
   2 {"msg":"PASSED [sig-api-machinery] Watchers should be able to restart watching from the last resource version observed by the previous watch [Conformance]","total":-1,"completed":9,"skipped":108,"failed":1,"failures":["[sig-network] NoSNAT [Feature:NoSNAT] [Slow] Should be able to send traffic between Pods without SNAT"]}
   2 {"msg":"PASSED [sig-cli] Kubectl client Kubectl run pod should create a pod from an image when restart is Never  [Conformance]","total":-1,"completed":10,"skipped":93,"failed":0}
   2 {"msg":"PASSED [sig-network] Networking Granular Checks: Services should function for endpoint-Service: http","total":-1,"completed":18,"skipped":363,"failed":0}
   2 {"msg":"PASSED [sig-network] Services should be able to switch session affinity for NodePort service [LinuxOnly] [Conformance]","total":-1,"completed":10,"skipped":168,"failed":0}
   2 {"msg":"PASSED [sig-node] ConfigMap should run through a ConfigMap lifecycle [Conformance]","total":-1,"completed":6,"skipped":45,"failed":0}
   2 {"msg":"PASSED [sig-storage] Projected configMap should be consumable from pods in volume as non-root [NodeConformance] [Conformance]","total":-1,"completed":8,"skipped":82,"failed":0}
  ```

**Comment by jayunit100** [comment]
the fact that `StatefulSet` and `IPerf` are failing  is suspicious.  Those are both long running tests that are resource intensive.  Imo we could skip them both.

**Comment by jayunit100** [comment]
ok so now we have a positive control in place.  good thinking @aojea . ill run some experiments on my end now...

**Comment by jayunit100** [comment]
ok, so the "easy" fix is default polling concurrency to 1 or 2... that is plenty fast enough, and won't stress out the other parallel ginkgo tests.
  - `:= 1`  tests run in 255 seconds 
  - `:= 2` tests run in 132 seconds, roughly 2 minutes putting them on par with other test times
  - `:= 3` tests run in 93 seconds, roughly 1.5 minutes 
  - `:= 30` tests run in 25 seconds.
 

Maybe that will move us forward, for now.  At some point, I think we should try to make other tests more resilient.

@aojea can you change `maxConcurrency := 3` and then we merge this ? That will probably ease the burden on other tests, and give us 'good enough' performance characteristics to retain our original test properties.

**Comment by jayunit100** [comment]
ok, I implemented the lesson here in https://github.com/kubernetes/kubernetes/pull/97702 .... thx again folks for all the digging on this one

**Comment by aojea** [comment]
fixed by #97702

**Pull request closed without merging**
