### PR TITLE
[Cherrypick #115537][1.26]*: Bump golangci-lint version and adapt to new linters

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
#### What type of PR is this?

Cherry-pick of https://github.com/kubernetes/kubernetes/pull/115537

/kind cleanup
/sig testing
/priority backlog

#### What this PR does / why we need it:

Bump golangci-lint version. This version
adds support for go1.20.

This consequently also bumps the version of
staticcheck. Note that this was changed to
use master to be compatible with 1.20(https://github.com/kubernetes/kubernetes/pull/115129). This
commit reverts back to using a tagged release.

golangci-lint release: https://github.com/golangci/golangci-lint/releases/tag/v1.51.1 
staticcheck release: https://github.com/dominikh/go-tools/releases/tag/2023.1

#### Which issue(s) this PR fixes:

Fixes #
NA

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/assign @liggitt @dims

### CODE REVIEW

**Comment by ameukam** [comment]
cc @kubernetes/release-managers

**Review by cpanato — APPROVED** [review]
/lgtm
/triage accepted

**Pull request merged**
