### PR TITLE
Correct versioned.Event output in Swagger

### LINKED ISSUE #24240: Remove *versioned.Event (should not be pointer) from swagger spec
Ref https://github.com/kubernetes/kubernetes/pull/24226

https://github.com/kubernetes/kubernetes/pull/23806 added *versioned.Event to swagger spec.
It should not be a pointer.

cc @smarterclayton

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes #24240

``` release-note
The value of the `versioned.Event` object (returned by watch APIs) in the Swagger 1.2 schemas has been updated from `*versioned.Event` which was not expected by many client tools. The new value is consistent with other structs returned by the API.
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33007)

### CODE REVIEW

**Comment by smarterclayton** [comment]
@nikhiljindal @mbohlool

**Comment by smarterclayton** [comment]
x-ref #24240

**Comment by smarterclayton** [comment]
I think this is a cherry-pick candidate for 1.4.x because it will block integrators

**Comment by nikhiljindal** [comment]
LGTM, thanks!


> I think this is a cherry-pick candidate for 1.4.x because it will block integrators

Sorry what do you mean by integrators?

**Comment by smarterclayton** [comment]
Anyone using our swagger spec to do anything useful (the *versioned.Event broke a few generators I tried).

**Comment by mbohlool** [comment]
LGTM too, I saw this among many validation failures in swagger 1.2. Assumed moving to swagger 2.0 will fixed it (briefly checked 2.0, it looks fine. The 2.0 spec is a valid spec that I can generate clients from).

**Comment by smarterclayton** [comment]
@k8s-bot unit test this issue #33184

**Pull request merged**
