### PR TITLE
Automated cherry pick of #32588

### PR DESCRIPTION
**Pull request by maisem**
Cherry pick of #32588 on release-1.2.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32619)

### CODE REVIEW

**Comment by pwittrock** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by foxish** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by foxish** [comment]
@spxtr These tests appear to be failing in an odd way.

**Comment by spxtr** [comment]
@k8s-bot gce e2e test this issue: #32688

**Comment by foxish** [comment]
@maisem This PR needs rebase.

**Comment by spxtr** [comment]
Feel free to merge after rebase if you think it's safe. The GCE test passed and the others are broken on 1.2 anyway.

**Pull request merged**
