### PR TITLE
Update go version in Godeps.json

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
Update go version in Godeps.json to go1.8. Looks like the staging ones were already done, but not the top level one.
```
godeps update -goversion
```

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
Hit https://github.com/kubernetes/kubernetes/issues/44232 again.
@k8s-bot verify test this

**Comment by cblecker** [comment]
/assign @sttts 
Hey @sttts, would you mind reviewing this if you have a moment? Then I can hunt for a top-level approver once it's LGTM'd.

Thanks!

**Comment by sttts** [comment]
Am not against this. Just out of curiosity: does this fix any issue?

**Comment by cblecker** [comment]
Other than contributor confusion (there was a question on Slack), no, not that I'm aware of.

**Comment by cblecker** [comment]
@k8s-bot kops aws e2e test this

**Comment by cblecker** [comment]
does this work for you, @sttts ? :)

**Pull request merged**
