### PR TITLE
Use full gopath for externalTypes

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Seems like @soltysh has no thread to fix the testing failure and rebase to solve the conflict in #55703. This PR cherry-pick it's commit and supersedes it to avoid the change to be rebase-blocker.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #55703

**Special notes for your reviewer**:
/cc @soltysh @sttts @smarterclayton @liggitt 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
>rebase blocker, ...would like to get this merged.

@sttts do you want this change in 1.9?

**Comment by sttts** [comment]
Copying approval from  #55703.

**Comment by sttts** [comment]
> rebase blocker, ...would like to get this merged.
> @sttts do you want this change in 1.9?

It's not blocking us in OpenShift because we can carry this patch. But it hits everybody vendoring kube and generating conversions. IMO we should get it into 1.9.

**Comment by xiangpengzhao** [comment]
Thanks @sttts !

/kind cleanup

**Comment by deads2k** [comment]
> It's not blocking us in OpenShift because we can carry this patch. But it hits everybody vendoring kube and generating conversions. IMO we should get it into 1.9.

I agree. I stumbled into it downstream too.

**Comment by deads2k** [comment]
/priority critical-urgent

Without this, you can't effectively vendor and regen for other types (as I recall)

**Comment by sttts** [comment]
/retest

GC flake.

**Pull request merged**
