### PR TITLE
e2e_node/dra: fix nil pointer dereference

### PR DESCRIPTION
**Pull request by huww98**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

e2e_node/dra: fix nil pointer dereference

#### Which issue(s) this PR fixes:

Fixes: ee0340a8281636a67f09a30cd1a77da23e835a56

#### Special notes for your reviewer:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/122460/pull-kubernetes-node-e2e-crio-cgrpv2-dra/1813848106849013760

/cc @bart0sh 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by huww98** [comment]
/cc @pohly
Because you are the reviewer of the referred commit.

**Comment by pohly** [comment]
I think I am already fixing this in https://github.com/kubernetes/kubernetes/pull/125488

**Comment by huww98** [comment]
OK, that one should fix the panic, but the test itself still seems wrong. https://github.com/kubernetes/kubernetes/pull/125488#discussion_r1683187961

If you don't expect that one to be merged in several days, I think we should work on this small PR first to avoid other people spending useless time investigating the test failure.

**Comment by pohly** [comment]
This small PR would force me to rebase https://github.com/kubernetes/kubernetes/pull/125488, which is already hard enough to get merged before code freeze. Let's focus on that PR.

> to avoid other people spending useless time investigating the test failure

If people run into issues related to DRA, feel free to ask on #wg-device-management before spending time on something that might already be known.

**Comment by haircommander** [comment]
https://github.com/kubernetes/kubernetes/pull/125488/files#diff-1c4135e0242bd4e7cf54377251824606b34b66e28d4ea32a5d4678a19d2e5d62R437-R439 merged, should we close this?

**Comment by pohly** [comment]
Yes, it shouldn't be needed anymore.

/close

@huww98: thanks for your contribution. It just came in at the wrong moment.

**Pull request closed without merging**
