### PR TITLE
Update serve_hostname private authenticated test tag in Makefile

### PR DESCRIPTION
**Pull request by pwittrock**

### CODE REVIEW

**Comment by pwittrock** [comment]
@bprashanth Do you know how to login to gcr and who should have perms to push images?  I don't think I have the necessary permissions.

**Comment by bprashanth** [comment]
Is this needed (we had a conversation but didn't conclusively determine anything, right?)

**Comment by thockin-cc** [comment]
Nuke, I think

**Comment by pwittrock** [comment]
Needed for these 2 tests:

https://github.com/kubernetes/kubernetes/blob/da582561870f48f9eaee610aae355f60398e7cbc/test/e2e/replica_set.go#L45
https://github.com/kubernetes/kubernetes/blob/da582561870f48f9eaee610aae355f60398e7cbc/test/e2e/rc.go#L43

Created #23391 for migrating to from b.gcr.io to gcr.io

**Pull request merged**
