### PR TITLE
fix help message of kubeconfig-dir option(kubeadm alpha phase kubeconfig all)

### PR DESCRIPTION
**Pull request by ghost**
**What this PR does / why we need it**:
This patch will fix wrong help message.

The command is kubeadm alpha phase kubeconfig [command]
The help message is for --kubeconfig-dir option.

kubeconfig-dir is not port.(It is directory)
So, I fixed the message.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

 `NONE`

/sig cluster-lifecycle

### CODE REVIEW

**Review by mattkelly — APPROVED** [review]
lgtm :+1:

**Comment by kad** [comment]
@shun-miyoshi-com please edit description of PR and put back from template section for release notes.
For such small fix it can be set to 
```
NONE
```

**Comment by shun-miyoshi-com** [comment]
@kad I'm sorry.
I fixed my PR message.

**Comment by shun-miyoshi-com** [comment]
Any task what I should do?

**Comment by dixudx** [comment]
ping @luxas @timothysc for approval.

**Review by timothysc — APPROVED** [review]
/approve

**Pull request merged**
