### PR TITLE
Automated cherry pick of #33868

### PR DESCRIPTION
**Pull request by wongma7**
Cherry pick of #33868 on release-1.4.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33940)

### CODE REVIEW

**Comment by wongma7** [comment]
@caesarxuchao this is the cherrypick + copy.sh PR for the final step https://github.com/kubernetes/kubernetes/pull/33851#issuecomment-250851272

**Comment by caesarxuchao** [comment]
@k8s-bot ok to test

**Comment by caesarxuchao** [comment]
@pwittrock could you approve the cherrypick? The steps we took are these: https://github.com/kubernetes/kubernetes/pull/33851#issuecomment-250851272. This PR is the last step.

**Comment by caesarxuchao** [comment]
The contents LGTM. Thanks @wongma7!

**Comment by wongma7** [comment]
@k8s-bot gce e2e test this

**Comment by caesarxuchao** [comment]
@jessfraz I heard you are the release czar. Could you approve this cherry-pick? I can explain to you what this PR does if needed. Thanks!

**Comment by jessfraz** [comment]
This is a huge diff, what happened as to why this wasn't in 1.4 to begin with? Are we sure this isnt adding things that shouldn't be included? Just want to make sure.

**Comment by caesarxuchao** [comment]
> This is a huge diff,

Most code are generated, so it's low risk.

> what happened as to why this wasn't in 1.4 to begin with?

In 1.4, hack/update-gen required developer to manually [specify the API groups](https://github.com/kubernetes/kubernetes/blob/release-1.4/hack/update-codegen.sh#L42). Some new API groups were not added to the script.

> Are we sure this isnt adding things that shouldn't be included?

The parent of this PR (#33868) generated clients based on the API types in the 1.4 branch (@wongma7 is that right?), so everything in (#33868) should be back-ported to 1.4.

Additionally, this PR includes changes to `./staging/`, those are needed because that's the only way for client-go/1.4 to pick up the changes.

**Comment by wongma7** [comment]
That's right, only API types that are present in 1.4 had clients generated for them as I did the generating from within 1.4

**Comment by jessfraz** [comment]
ok gotcha (as a tanget I wonder if there's a way to modify the script so the same thing doesnt happen with 1.5)

**Comment by caesarxuchao** [comment]
The script in 1.5 is automated. New groups will be automatically added.

**Comment by caesarxuchao** [comment]
@k8s-bot GCE e2e test this, issue #33867

**Comment by jessfraz** [comment]
ah nice!

**Comment by jessfraz** [comment]
@k8s-bot GCE e2e test this, issue #33867

**Comment by jessfraz** [comment]
@k8s-bot GCE e2e test this, issue #30632

**Comment by jessfraz** [comment]
@k8s-bot test this issue #33388

**Pull request merged**
