### PR TITLE
Small readability improvements in Kubelet

### PR DESCRIPTION
**Pull request by peterlamar**
Rename kubelet variable pods to maxPods in kubelet pkg to match corresponding maxPods variable in cmd/kubelet/server.go.

Remove comment requesting modification of mesos contrib file, dependencies such as this are maintained in unit tests

### CODE REVIEW

**Comment by PeterLamar** [comment]
@smarterclayton Did I do something wrong in the PR? Is it too small? I wanted to get familiar with the process before I attempted larger modifications.

**Comment by smarterclayton** [comment]
No you did not - just on PTO.  Transferring you to someone with more bandwidth.

**Comment by mikedanese** [comment]
@k8s-bot ok to test. @PeterLamar sorry for slow review (we are amidst the holidays). I'll take a look today.

**Comment by PeterLamar** [comment]
Thanks @mikedanese !

**Comment by mikedanese** [comment]
@k8s-bot ok tot test

**Comment by gmarek** [comment]
@k8s-bot test this

**Pull request merged**
