### PR TITLE
Increase the timeout for integration tests.

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes https://github.com/kubernetes/kubernetes/issues/14680 (I hope)
Fixes https://github.com/kubernetes/kubernetes/issues/10257 (I hope)
Fixes https://github.com/kubernetes/kubernetes/issues/14531(I hope)

### CODE REVIEW

**Comment by brendandburns** [comment]
closing and re-opening to trick Shippable into running...

**Comment by wojtek-t** [comment]
LGTM

**Comment by brendandburns** [comment]
Marking LGTM on @wojtek-t 's LGTM above.

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
