### PR TITLE
 change the QueueingHintFn to pass a logger

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

See https://github.com/kubernetes/kubernetes/pull/119155#discussion_r1260139494

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by sanposhiho — COMMENTED** [review]
/lgtm

**Comment by alculquicondor** [comment]
This probably requires an update after https://github.com/kubernetes/kubernetes/pull/119078 merged

**Comment by ahg-g** [comment]
/lgtm

Thanks!

**Pull request merged**
