### PR TITLE
Automated cherry pick of #43766 release 1.6

### PR DESCRIPTION
**Pull request by mikedanese**
Automated cherry pick of #43766 release 1.6

### CODE REVIEW

**Comment by ixdy** [comment]
what's with the `verify-federation-openapi-spec.sh` failure?

I wonder if there's anything we can do to avoid needing to fix dependencies like these on all branches.

**Comment by enisoc** [comment]
@ixdy Hm weird. I already ran `update-all.sh`, but now when I run `update-openapi-spec.sh` it produces a diff. I will push a commit to the branch to fix this soon.

**Comment by enisoc** [comment]
@ixdy I think the long-term fix is that anago needs to run the proper update scripts after it bumps the version.

**Comment by ixdy** [comment]
Sorry, I conflated issues in my comment.

anago definitely should be doing the right thing. (`update-openapi-spec.sh` is newer, which is probably why it's not being run.)

My other comment was regarding the bazel fix. It's frustrating that the bazel build can break on release branches without us changing anything.

**Comment by mikedanese** [comment]
@k8s-bot verify test this please

**Comment by mikedanese** [comment]
I'm gonna tag this as approved to get some overnight testing considering I'd like to get this into a release tomorrow and we were just waiting for this to enter master (which it has).

**Pull request merged**
