### PR TITLE
add unit test

### PR DESCRIPTION
**Pull request by wongearl**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
add unit test 
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by changshuchao** [comment]
Why add this unit test？

**Comment by wongearl** [comment]
@changshuchao good question, I just think it is good to add more unit test.

**Comment by slaskawi** [comment]
@wongearl Could you please add a meaningful title and a meaningful description of what you're trying to achieve?

I'm also OK with adding these tests. The `defaults_test.go` is currently empty (maybe it has been pushed by a mistake?). 

@liggitt I think you're the author of this one. Could you please tell us what you think about this PR?

**Comment by liggitt** [comment]
effective defaults are already tested via staging/src/k8s.io/pod-security-admission/admission/api/load/load_test.go

**Pull request closed without merging**
