### PR TITLE
Fix typo in comment, and generate OpenAPI spec so docs can be regener…

### PR DESCRIPTION
**Pull request by steveperry-53**
…ated.

**What this PR does / why we need it**:
The purpose of this PR is for me to learn the process of updating the [Kubernetes API reference documentation](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.9/), and then to document that process. I'm working on getting the process documented in [PR 6366](https://github.com/kubernetes/website/pull/6366) in the kubernetes/website repository. Here's a [preview of the new topic](https://deploy-preview-6366--kubernetes-io-master-staging.netlify.com/docs/home/contribute/generated-reference/kubernetes-api/).

In the docs, I would like to refer to this PR as an example. So I have kept the change simple: fix one typo.

Related issues:
https://github.com/kubernetes/website/issues/921
https://github.com/kubernetes/website/issues/922

**Special notes for your reviewer**:
In the future, we might want to make the doc generation process a bit more automatic. But for now I think it's important to get the current process documented.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by steveperry-53** [comment]
@mbohlool Can you take a look at this? Thanks.

**Comment by mbohlool** [comment]
why this PR is against a release branch not master?

**Comment by steveperry-53** [comment]
@mbohlool I need your advice on what branch this PR should be against. I'm trying to demonstrate what to do in this scenario: Suppose one of our readers spots a mistake in our 1.9 ref docs, and wants to fix it. The fix involves changing source code, generating an new swagger.json, and then generating a new HTML file from the swagger.json. It seemed to me that we should generate the new swagger.json in the release-1.9 branch. If we generate a new swagger.json in the master branch, we might pick up 1.10 features that shouldn't be published yet.

**Comment by mbohlool** [comment]
@steveperry-53 The process should look like this: We would send a fix to the master branch with source code changes and generated changes (swagger.json and htmls) in two separate commits (same PR). Once it is merged, we can use automatic tools to cherrypick the PR into release branch. In the process, verify scripts will fail as we apply source code changes but the generated changes would be wrong. We need to manually regenerate those files in the cherrypick PR and update the relevant commit and send it for review of the patch manager. There could be very special cases that this may not work (e.g. the API we are fixing document for does not exists in master branch anymore or moved) and in that case we can send a PR directly to release branch with a reference to a PR that fixes master branch (if the API is moved).

**Comment by steveperry-53** [comment]
Closing. Starting over in #57758.

**Pull request closed without merging**
