### PR TITLE
Reduce leaderelection's renewed lease verbosity

### LINKED ISSUE #69743: Leader election spamming scheduling logs
**Is this a BUG REPORT or FEATURE REQUEST?**:
@kubernetes/sig-scheduling-bugs 

**What happened**:
Here's an example from an e2e test:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/4196/artifacts/bootstrap-e2e-master/kube-scheduler.log

```
I1011 00:01:23.747194       1 wrap.go:42] GET /healthz: (21.155µs) 200 [kube-probe/1.13+ 127.0.0.1:35748]
I1011 00:01:25.678930       1 leaderelection.go:227] successfully renewed lease kube-system/kube-scheduler
I1011 00:01:27.721975       1 leaderelection.go:227] successfully renewed lease kube-system/kube-scheduler
I1011 00:01:29.778759       1 leaderelection.go:227] successfully renewed lease kube-system/kube-scheduler
I1011 00:01:31.825248       1 leaderelection.go:227] successfully renewed lease kube-system/kube-scheduler
I1011 00:01:33.748955       1 wrap.go:42] GET /healthz: (23.09µs) 200 [kube-probe/1.13+ 127.0.0.1:35770]
I1011 00:01:33.890292       1 leaderelection.go:227] successfully renewed lease kube-system/kube-scheduler
I1011 00:01:35.935005       1 leaderelection.go:227] successfully renewed lease kube-system/kube-scheduler
I1011 00:01:37.984695       1 leaderelection.go:227] successfully renewed lease kube-system/kube-scheduler
I1011 00:01:40.027758       1 leaderelection.go:227] successfully renewed lease kube-system/kube-scheduler
I1011 00:01:42.084951       1 leaderelection.go:227] successfully renewed lease kube-system/kube-scheduler
```

**What you expected to happen**:
leader election success logs to be at a higher log level.

### PR DESCRIPTION
**Pull request by seunghunee**
**What this PR does / why we need it**:
This patch changes the renewed lease log level from 4 to 5 of leaderelection.go

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #69743

```release-note
NONE
```

### CODE REVIEW

**Comment by seunghunee** [comment]
I signed it

**Comment by jpbetz** [comment]
According to https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-output-verbosity-and-debugging, 4 looks to me to be the correct level. Level 4 is for "Debug level verbosity." while Level 5 is for "Display requested resources".

If level is too verbose for ones needs, how about running with `--v=3` instead?

**Comment by mikedanese** [comment]
Per https://github.com/kubernetes/community/pull/2887

/lgtm
/approve

**Pull request merged**
