### PR TITLE
Update kube-dns 1.14.7

### PR DESCRIPTION
**Pull request by bowei**
kube-adm change will be in a separate commit

```release-note
* Logging cleanups
* Updates kube-dns to use client-go 3
* Updates containers to use alpine as the base image on all platforms
* Adds support for IPv6
```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm

**Comment by dghubble** [comment]
Should there be a separate 1.14.7 release tag in https://github.com/kubernetes/dns/releases?

**Comment by bowei** [comment]
yes -- that was an oversight, let me push the tag

**Comment by bowei** [comment]
The tag should now exist.

**Pull request merged**
