### PR TITLE
[WIP] Graduate Kubelet Device Plugin API to GA

### PR DESCRIPTION
**Pull request by swatisehgal**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
The Device Plugin API has been beta since Kubernetes v1.10 making it a suitable candidate for GA graduation.

- [X] Added a "version 1" of the API
- [ ] TODO: Ensure that the kubelet supports both v1Beta1 and  v1
- [ ] TODO: End to end tests 

#### Which issue(s) this PR fixes:

Fixes: TODO

#### Does this PR introduce a user-facing change?

```release-note
 Graduate Kubelet Device Plugin API to GA
```
#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
[Slack discussion on Device Plugin API graduation]: https://kubernetes.slack.com/archives/C0BP8PW9G/p1667481109075849
[KEP]: https://github.com/kubernetes/enhancements/pull/3574
[Code: Device Manager GA graduation]: https://github.com/kubernetes/kubernetes/pull/112980
```

### CODE REVIEW

**Comment by swatisehgal** [comment]
/hold
Device Plugin API is not being graduated in 1.26. Please refer to more details on the slack thread [here](https://kubernetes.slack.com/archives/C0BP8PW9G/p1667481109075849).

**Comment by dims** [comment]
This PR has the label work-in-progress, please revisit to see if you still need this, please close if not

**Comment by swatisehgal** [comment]
This work still needs to be done but I don't have the bandwidth to drive it in this cycle. I might pick it up if/when time allows but for now we can close it unless someone else is interested to work on this.

**Comment by akhilerm** [comment]
@swatisehgal I can take up this and continue working on it.

**Comment by swatisehgal** [comment]
> https://kubernetes.slack.com/archives/C0BP8PW9G/p1667481109075849

Sure, that is great. Please note that this work has dependency on additional work that needs to be done before we to graduate the API to GA. Refer to https://kubernetes.slack.com/archives/C0BP8PW9G/p1667481109075849 for details.

The gist is that:

1. We should have a v1beta2 that allows us to have API specific call requests.
2. Determine if the community still want to pursue adding [Deallocate and PostStopContainer](https://github.com/kubernetes/enhancements/pull/3080).

**Comment by dims** [comment]
This work-in-progress PR needs a rebase. please rebase if this PR is still needed for the upcoming release.

**Pull request closed without merging**
