### PR TITLE
Refactor pkg/kubectl/{scale.go|rollingupdater.go} for move to staging

### PR DESCRIPTION
**Pull request by seans3**
* Moves `pkg/kubectl/scale.go` and test to staging.
* Moves `pkg/kubectl/rolling_update.go` and test to `pkg/kubectl/cmd/rollingupdate`, which is the only place it is used.
* Publishes this code to the new kubectl repository: https://github.com/kubernetes/kubectl/pkg/scale.
* Code will be available for re-use after publishing.

/kind cleanup
/sig cli
/area kubectl
/area code-organization
/priority important-soon

```release-note
NONE
```

### CODE REVIEW

**Comment by seans3** [comment]
/assign @BenTheElder 

for `vendor/modules.txt`

**Review by BenTheElder — APPROVED** [review]
/lgtm
/approve

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Pull request merged**
