### PR TITLE
fix the if judge sentences

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
the clean always TRUE so no need if Judge sentences！
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jsafrane** [comment]
I used to set `clean` to false when debugging the tests, but I guess we can live without it now. Please completely remove  `clean` variable at line 88.

**Comment by jsafrane** [comment]
And please fix hack/verify-gofmt.sh error.

**Comment by jianglingxia** [comment]
thanks @jsafrane but I think can not remove clean variable at line 88,because there has some place need to assignment so I left it! and I have updated the gofmt error,thanks for your review again!
image

**Comment by msau42** [comment]
I think it is fine to remove clean from testGCEPD

**Comment by jianglingxia** [comment]
yeah,Before I keep it because （clean bool）parameter if remove it better latter I set TRUE in it and remove clean in function  testGCEPD，thanks！

**Comment by jianglingxia** [comment]
PTAL @jsafrane
thanks

**Comment by msau42** [comment]
Please remove the `clean` variable entirely.

**Comment by jianglingxia** [comment]
thanks for your advice and I have removed the clean variable entirely and format the defer func,please review it! @msau42 @jsafrane

**Pull request merged**
