### PR TITLE
Display pod node selectors with kubectl describe.

### PR DESCRIPTION
**Pull request by aveshagarwal**
**What this PR does / why we need it**:
This PR fixes kubectl describe so that it now shows associated node selectors with pods.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

@kubernetes/rh-cluster-infra @kubernetes/kubectl

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36396)

### CODE REVIEW

**Comment by AdoHe** [comment]
@aveshagarwal could you paste describe output here?

**Comment by aveshagarwal** [comment]
@AdoHe 
```
.
.
Conditions:
  Type		Status
  PodScheduled 	False 
Volumes:
  default-token-w3gyf:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-w3gyf
QoS Class:	Burstable
Node-Selectors:	disktype=ssd
                region=east
Tolerations:	<none>
.
.
.
```

**Comment by aveshagarwal** [comment]
And if there are no node selectors, output would be:
```
QoS Class:	Burstable
Node-Selectors:	<none>
Tolerations:	<none
```

**Comment by AdoHe** [comment]
LGTM. @aveshagarwal thanks very much.

**Comment by aveshagarwal** [comment]
please keep it open.

**Comment by soltysh** [comment]
@aveshagarwal is there anything more that needs to be done for this PR, or it's good for merge as is?

**Comment by aveshagarwal** [comment]
Good to merge as is. Thanks.

**Pull request merged**
