### PR TITLE
Refactoring and extra tests for kubectl portforward (required for a new feature)

### PR DESCRIPTION
**Pull request by m1kola**
**What this PR does / why we need it**:

This change is required in order to implement https://github.com/kubernetes/kubectl/issues/538

This PR:

* e875fd463934ee089990e72fbd9a4575cdc13e2b - Makes the `LookupContainerPortNumberByName` function in `k8s.io/kubernetes/pkg/kubectl/util` to be exportable, so I can reuse it while working on https://github.com/kubernetes/kubectl/issues/538
* 6bbc4fe2cc9eaa1b7dafd50bf633826c444bae2f - Adds extra tests for the `kubectl portforward` command

**Special notes for your reviewer**:

I also moved the `LookupContainerPortNumberByName` function into a separate file (`pod_port.go`), because `service_port.go` doesn't sound like a good location for a function that operates on a Pod.

**Release note**:

```release-note
NONE
```

/kind cleanup
/sig cli

### CODE REVIEW

**Comment by neolit123** [comment]
SGTM, thanks.
/ok-to-test

**Comment by m1kola** [comment]
Assigning the ticket as the bot suggests:
/assign @droot

Thanks for marking this "ok to test" so quickly :)

Tests were failing, because I didn't run `./hack/update-bazel.sh`. Fixed now and ready for review.

**Comment by m1kola** [comment]
Rebased

**Comment by m1kola** [comment]
It was reviewed as part of #69477, so closing this one and squashing into a single commit in #69477

**Pull request closed without merging**
