### PR TITLE
Revert #32751 and #35840 in 1.6

### PR DESCRIPTION
**Pull request by caesarxuchao**
Revert backward compatibility hacks (#36004, #32751) that are no-longer needed in release 1.6

@kubernetes/sig-api-machinery @liggitt

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36004)

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Rebased. Also reverted #32751. @liggitt PTAL. Thanks.

**Comment by cjcullen** [comment]
This breaks 1.4 kubectl against 1.6 masters. Doesn't that go against our versioning policy?

**Comment by caesarxuchao** [comment]
Our [policy](https://github.com/kubernetes/kubernetes/blob/master/docs/design/versioning.md#supported-releases-and-component-skew) says only supporting one minor version skew for kubectl: "a client should be skewed no more than one minor version from the master, but may lead the master by up to one minor version."

**Comment by cjcullen** [comment]
Ah you're right. I misread the client policy.

**Pull request merged**
