### PR TITLE
switch back to promiscuous-bridge mode

### LINKED ISSUE #27498: unregister_netdevice kernel race on coreos image
Doesn't seem to haven been caused by my change: https://storage.cloud.google.com/kubernetes-jenkins/pr-logs/pull/27083/node-pull-build-e2e-test/10720/build-log.txt

```
Summarizing 3 Failures:

[Fail] [k8s.io] Downward API [It] should provide pod name and namespace as env vars [Conformance] 
/var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2022

[Fail] [k8s.io] Downward API [It] should provide pod IP as an env var 
/var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2022

[Fail] [k8s.io] Downward API [It] should provide container's limits.cpu/memory and requests.cpu/memory as env vars 
/var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2022

Ran 19 of 22 Specs in 1130.000 seconds
FAIL! -- 16 Passed | 3 Failed | 0 Pending | 3 Skipped --- FAIL: TestE2eNode (1130.00s)
FAIL

Ginkgo ran 1 suite in 18m50.080565864s
Test Suite Failed
```

```
[k8s.io] Downward API
/var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:660
  should provide container's limits.cpu/memory and requests.cpu/memory as env vars [It]
  /var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/downward_api_test.go:130

  Expected error:
      <*errors.errorString | 0xc8207f9770>: {
          s: "gave up waiting for pod 'downward-api-63e732e1-334a-11e6-b754-42010af00048' to be 'success or failure' after 5m0s",
      }
      gave up waiting for pod 'downward-api-63e732e1-334a-11e6-b754-42010af00048' to be 'success or failure' after 5m0s
  not to have occurred

  /var/lib/jenkins/workspace/node-pull-build-e2e-test/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:2022
```

### PR DESCRIPTION
**Pull request by freehan**
fix: #27498

### CODE REVIEW

**Comment by euank** [comment]
LGTM

**Comment by yujuhong** [comment]
LGTM. 

We should try this anyway, but @freehan, is it possible that this is a completely different bug?

**Comment by euank** [comment]
@k8s-bot test this issue: #27335

**Comment by yujuhong** [comment]
@k8s-bot test this issue: IGNORE

**Comment by yujuhong** [comment]
@k8s-bot node e2e test this issue: #IGNORE

**Pull request merged**
