### PR TITLE
tests: Uses newly promoted httpd and nginx images

### LINKED ISSUE #99047: Windows httpd and httpd-new test images breaks due to incorrect architecture for PHP library.
#### Which test(s) are failing:
* Kubernetes e2e suite: [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should have a working scale subresource [Conformance]
* Kubernetes e2e suite: [sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should perform canary updates and phased rolling updates of template modifications [Conformance]

and a few others.

#### Reason for failure: httpd and httpd-new images startup immediately crashing with
`httpd.exe: Syntax error on line 73 of C:/usr/local/apache2/conf/httpd.conf: Cannot load c:/tools/php74/php7apache2_4.dll into server: %1 is not a valid Win32 application. `

### LINKED ISSUE #99325: [sig-windows] k8s.gcr.io/e2e-test-images/nginx image not working on Windows clusters
/sig windows
/cc @claudiubelu @jsturtevant 

#### Which test(s) are failing:

```
Kubernetes e2e suite.[sig-apps] ReplicationController should test the lifecycle of a ReplicationController [Conformance]
```

#### Since when has it been failing:

After https://github.com/kubernetes/kubernetes/pull/98964 was merged I think.

#### Testgrid link:

https://testgrid.k8s.io/sig-windows-azure#aks-engine-azure-windows-master-staging

#### Reason for failure:

```
azureuser@k8s-master-13847661-0:~$ k get po -A
NAMESPACE                     NAME                                            READY   STATUS             RESTARTS   AGE
kube-system                   azure-cni-networkmonitor-bbql7                  1/1     Running            0          171m
kube-system                   azure-ip-masq-agent-pxzvh                       1/1     Running            0          171m
kube-system                   blobfuse-flexvol-installer-w7n7g                1/1     Running            0          171m
kube-system                   coredns-6bbfb77cb5-4bnfx                        1/1     Running            0          171m
kube-system                   coredns-autoscaler-87b67c5fd-npmfh              1/1     Running            0          171m
kube-system                   csi-secrets-store-dkttq                         3/3     Running            0          171m
kube-system                   csi-secrets-store-provider-azure-dkqx8          1/1     Running            0          170m
kube-system                   kube-addon-manager-k8s-master-13847661-0        1/1     Running            0          171m
kube-system                   kube-apiserver-k8s-master-13847661-0            1/1     Running            0          170m
kube-system                   kube-controller-manager-k8s-master-13847661-0   1/1     Running            0          171m
kube-system                   kube-proxy-phqgd                                1/1     Running            0          171m
kube-system                   kube-scheduler-k8s-master-13847661-0            1/1     Running            0          171m
kube-system                   metrics-server-6c8cc7585b-nhmwj                 1/1     Running            0          171m
replication-controller-6324   rc-test-j5sb7                                   0/1     CrashLoopBackOff   33         144m
replication-controller-6324   rc-test-vdb7h                                   0/1     CrashLoopBackOff   32         144m

azureuser@k8s-master-13847661-0:~$ k logs rc-test-j5sb7 -n replication-controller-6324
nginx: [alert] could not open error log file: CreateFile() "logs/error.log" failed (3: The system cannot find the path specified)
2021/02/22 23:03:44 [emerg] 6668#10944: CreateFile() "C:\/conf/nginx.conf" failed (3: The system cannot find the path specified)
```

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind cleanup
/sig windows
/sig testing

/priority important-soon

#### What this PR does / why we need it:

The new images contain a few Windows fixes required to run properly.

#### Which issue(s) this PR fixes:

Fixes #99325
Fixes #99047
Related: #99363 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/approve

please ping when the CI is green. thanks!

**Comment by claudiubelu** [comment]
It seems that the job ``pull-kubernetes-e2e-aks-engine-azure-windows`` is configured to use the ``k8sprow.azurecr.io/kubernetes-e2e-test-images`` registry, which does not contain these new images. The jobs will have to be reconfigured to use the regular Kubernetes k8s.io registry after this merged.

But we've run this job here: https://github.com/kubernetes/kubernetes/pull/87607 , where the staging images were used to run the tests and there was no failure related to the nginx or httpd images.

**Comment by jsturtevant** [comment]
correct, `pull-kubernetes-e2e-aks-engine-azure-windows`  @chewong created /test pull-kubernetes-e2e-aks-engine-windows-contianerd-test-images so we could test the new images to test before merging  as part of the plan in https://github.com/kubernetes/kubernetes/issues/99363#issuecomment-784550317

**Comment by jsturtevant** [comment]
the failure in `pull-kubernetes-e2e-aks-engine-windows-contianerd-test-images` is a known flake https://github.com/kubernetes/kubernetes/issues/99365 being worked on by @ravisantoshgudimetla 

/retest

**Comment by jsturtevant** [comment]
spelling was wrong

/test pull-kubernetes-e2e-aks-engine-windows-containerd-test-images

**Review by chewong — COMMENTED** [review]
/lgtm
Thanks, Claudiu!

**Comment by chewong** [comment]
/hold 
for others to review

**Review by pacoxu — APPROVED** [review]

**Comment by pacoxu** [comment]
/override pull-kubernetes-e2e-aks-engine-windows-contianerd-test-images

**Comment by pacoxu** [comment]
/override pull-kubernetes-e2e-aks-engine-windows-contianerd-test-images

**Comment by pacoxu** [comment]
@nikhita  would you run override for this PR?

**Comment by dims** [comment]
@pacoxu `pull-kubernetes-e2e-aks-engine-windows-contianerd-test-images` is not a required job. even if it fails, the PR can merge if it has approved / lgtm and there is no hold

**Comment by jsturtevant** [comment]
The test doesn't exist it was renamed to `pull-kubernetes-e2e-aks-engine-windows-containerd-test-images` noticed the containerd was spelled wrong which was fixed in testinfra.

> The specified target(s) for /test were not found.

**Comment by pacoxu** [comment]
@dims in https://github.com/kubernetes/kubernetes/pull/98985#issuecomment-789547099 
override works to remove the unused test.

**Comment by nikhita** [comment]
:wave: 

> @pacoxu pull-kubernetes-e2e-aks-engine-windows-contianerd-test-images is not a required job. even if it fails, the PR can merge if it has approved / lgtm and there is no hold

Like @dims mentioned, this isn't a `Required` job so once the `do-not-merge/hold` label is removed, this PR should get merged. :)

If you still run into trouble with the broken job blocking this PR, please ping me again and I will override it!

**Comment by jsturtevant** [comment]
Since we the test `pull-kubernetes-e2e-aks-engine-windows-containerd-test-images` which uses this images passes I think we are good to go. @chewong Are you ok with removing the hold?

**Comment by jsturtevant** [comment]
@nikhita looks like we do need an override. I am guess since the test no longer exists it is failing. Which repo do I log a bug for something like that against? Test-infra?

**Comment by nikhita** [comment]
/override pull-kubernetes-e2e-aks-engine-windows-contianerd-test-images

> @nikhita looks like we do need an override. I am guess since the test no longer exists it is failing. Which repo do I log a bug for something like that against? Test-infra?

Yes, test-infra would be the right repo. :+1:

**Pull request merged**
