### PR TITLE
Rename CronJob controller file

### PR DESCRIPTION
**Pull request by soltysh**
**What type of PR is this?**
/kind cleanup
/sig apps
/priority important-longterm 

**What this PR does / why we need it**:
This renames CronJob controller file to `cronjob_controller.go` since we need to be able to easily distinguish which logs come from which controller file. 

**Special notes for your reviewer**:
/assign @janetkuo @tnozicka 
/cc @pmcalpine @deads2k 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by tnozicka** [comment]
Fixes the unfortunate rename from https://github.com/kubernetes/kubernetes/pull/74678
This is important for correct klog logs which are identified by filename

/lgtm

**Comment by pmcalpine** [comment]
My apologize if #74678 caused confusion. It certainly was not my intent.

I was prompted to rename the file when golint complained that the struct name stutters, and in the process of updating the struct name decided that the package name also stuttered ("cronjob/cronjob_controller.go"). In my opinion, the renamed "controller/cronjob.go" is more aligned with golang package naming guidance which indicates that package names should be "judiciously" abbreviated: https://blog.golang.org/package-names.

I will not rename any such files in the future, but I don't see this dependency of the logging infrastructure and controller filenames documented anywhere obvious. I recommend you document that controller source files must have unique file names in:
1. the package comment file of each controller, and
2. a pkg/controller/README.md file
Without this documentation, it's possible another well-intentioned contributor will bump into the logging infrastructure's naming constraint in the future.

**Review by janetkuo — APPROVED** [review]

**Comment by janetkuo** [comment]
We probably need to improve logging instead of requiring unique file names.

**Comment by soltysh** [comment]
> We probably need to improve logging instead of requiring unique file names.

Yes, yes, yes x 1000 times.

**Pull request merged**
