### PR TITLE
cleanup: remove TODO(resolved) and var(unused)

### PR DESCRIPTION
**Pull request by NickrenREN**
**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dashpole** [comment]
Can you point me to the PR where the TODO was resolved?

**Comment by NickrenREN** [comment]
@dashpole  it it resolved in [27970](https://github.com/kubernetes/kubernetes/pull/27970)

**Comment by NickrenREN** [comment]
@saad-ali  PTAL

**Comment by NickrenREN** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by NickrenREN** [comment]
ping @saad-ali

**Pull request merged**
