### PR TITLE
fix: recovery variable same as object name

### PR DESCRIPTION
**Pull request by agxmaster**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by r0b2g1t — CHANGES_REQUESTED** [review]
What are the benefits of the additional "e"?
In relation to clean code, it would be better to use one word. Such as recovery or recover.

**Comment by agxmaster** [comment]
> What are the benefits of the additional "e"? In relation to clean code, it would be better to use one word. Such as recovery or recover.

`
func main() {
	var t Test
	t.func1()
}

type Test string

func (r Test) func1() {
	fmt.Println("func1")
	defer func() {
                //if there used r , r is panic not instanceof Test Type
		if re := recover(); re != nil {
			fmt.Println("re")
			r.func2()
		}
	}()
	panic("aaa")

}

func (r Test) func2() {
	fmt.Println("func2")
}
`

**Comment by jiahuif** [comment]
/close
Sorry but this PR seems unhelpful.
/triage accepted

**Pull request closed without merging**
