### PR TITLE
update: bump anp image to v0.1.4

### PR DESCRIPTION
**Pull request by ipochi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

Updates apiserver-network-proxy to v0.1.4 version which adds new features (smart readiness check), quiets unnecessary logs, fixes bugs, bump k8s dependencies to 1.27

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

Changes: https://github.com/kubernetes-sigs/apiserver-network-proxy/compare/v0.1.2...v0.1.4
Notable feature : https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/485, https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/494

Manual edits:

vendor/modules.txt
cluster/gce/addons/konnectivity-agent/konnectivity-agent-ds.yaml
cluster/gce/manifests/konnectivity-server.yaml

Commands:

./hack/pin-dependency.sh sigs.k8s.io/apiserver-network-proxy/konnectivity-client v0.1.2
./hack/update-codegen.sh
./hack/update-vendor.sh

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jkh52** [comment]
@ipochi a seeming regression was surfaced: https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/513

let me look to see if this is a quick fix, we may want to wait for 0.1.5 before introducing to k/k.

**Comment by cheftako** [comment]
/lgtm
/hold
I agree it would be nice to get https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/513 resolved. Do we know if 0.1.2 had the regression in it? If so it should be fine to push. Otherwise it would be good to wait.

**Comment by jkh52** [comment]
> /lgtm /hold I agree it would be nice to get [kubernetes-sigs/apiserver-network-proxy#513](https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/513) resolved. Do we know if 0.1.2 had the regression in it? If so it should be fine to push. Otherwise it would be good to wait.

Yes, 0.1.2 does introduce the [suspected culprit](https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/463), per: [compare/v0.1.1...v0.1.2](https://github.com/kubernetes-sigs/apiserver-network-proxy/compare/v0.1.1...v0.1.2)

So, fine to push this.

/remove-hold

**Review by pacoxu — APPROVED** [review]

**Comment by jkh52** [comment]
@ipochi this PR needs a rebase; but we now have tag 0.28.0 which would supercede 0.1.4 for k/k master branch. Maybe we should just update this PR to use 0.28.0?

**Comment by jkh52** [comment]
@ipochi 

Let's close this PR and replace it with https://github.com/kubernetes/kubernetes/pull/120836

**Pull request closed without merging**
