### PR TITLE
kubeadm: Don't downgrade etcd on cluster downgrade

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:
 - Don't try downgrade etcd on k8s downgrade -- that doesn't work
 - Mark self-hosting as alpha as discussed in the SIG
 - Don't print the beta warning as it confuses users
 - Slightly make the wording around upgrade/downgrade clearer

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
@kubernetes/sig-cluster-lifecycle-pr-reviews

### CODE REVIEW

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Comment by luxas** [comment]
```
W1211 16:18:00.700] cmd/kubeadm/app/phases/upgrade/staticpods.go:181:28: error strings should not be capitalized or end with punctuation or a newline
W1211 16:18:00.701] cmd/kubeadm/app/phases/upgrade/staticpods.go:209:28: error strings should not be capitalized or end with punctuation or a newline
```
_sigh_. Re-pushing

**Pull request merged**
