### PR TITLE
Fix AWS options doc

### PR DESCRIPTION
**Pull request by justinsb**
Fix formatting, and ZONE should have been KUBE_AWS_ZONE.

### CODE REVIEW

**Comment by mbforbes** [comment]
Docs-only so only one review needed.

**Comment by roberthbailey** [comment]
LGTM.

**Comment by roberthbailey** [comment]
Closing and re-opening to kick shippable.

**Comment by justinsb** [comment]
Persuaded shippable all was well via a rebase :-)

**Comment by roberthbailey** [comment]
Doc only change.

**Pull request merged**
