### PR TITLE
keep processing other nodes for the nil node error

### PR DESCRIPTION
**Pull request by snowplayfire**
**What type of PR is this?**
> /kind bug
> /kind feature

**What this PR does / why we need it**:
want to reopen #79507, but the branch has been deleted. so I re-submit a PR.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by snowplayfire** [comment]
@Huang-Wei  please take a look, thanks

**Review by Huang-Wei — COMMENTED** [review]
Thanks @snowplayfire. Please update the release-note section as `NONE`.

Otherwise,
/lgtm
/approve

**Review by draveness — COMMENTED** [review]
/ok-to-test
/kind cleanup

**Pull request merged**
