### PR TITLE
Fix broken list of 'Service/Publishing services - service types'

### PR DESCRIPTION
**Pull request by nsega**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind documentation

**What this PR does / why we need it**:
I fixed the broken list of "Service/Publishing services - service types".

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
This PR is only modifying the broken list.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nsega** [comment]
Could you please to check this PR?
/assign @smarterclayton

**Comment by liggitt** [comment]
thanks for the PR, rebase is needed

**Comment by nsega** [comment]
@liggitt 

Thank you for reviewing my PR. I just resolved the conflict after doing rebase. 
Please confirm my PR again.

**Comment by smarterclayton** [comment]
Corrected the release note text.

**Pull request merged**
