### PR TITLE
Enable finalizers independent of GC enablement

### LINKED ISSUE #50528: Finalizers are broken for CRDs in 1.7
Create a CRD (`kubectl create -f`):

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:  
  name: databases.example.com
spec:
  group: example.com
  version: v1
  names:
    kind: Database
    plural: databases
    scope: Namespaced
```

and a CR  (`kubectl create -f`):
```
apiVersion: example.com/v1
kind: Database
metadata:
  name: wordpress
spec:
  user: wp
  password: secret
  encoding: unicode
```

Then add a finalizer: ```kubectl edit database wordpress``` by changing it to:
```
apiVersion: example.com/v1
kind: Database
metadata:
  name: wordpress
  ...
  finalizers:
  - foo
spec:
  ...
```

Delete the resource:
```
$ kubectl delete database wordpress
```

The resource is gone, but shouldn't.

### PR DESCRIPTION
**Pull request by ironcladlou**
Decouple finalizer processing from garbage collection configuration.
Finalizers should be effective even when garbage collection is disabled
for a given store.

Fixes #50528.

Backport of https://github.com/kubernetes/kubernetes/pull/51148.

```release-note
Finalizers are now honored on custom resources, and on other resources even when garbage collection is disabled via the apiserver flag `--enable-garbage-collector=false`
```

/cc @kubernetes/sig-api-machinery-bugs 
/cc @caesarxuchao @liggitt @sttts @pmorie

### CODE REVIEW

**Comment by wojtek-t** [comment]
@caesarxuchao @liggitt - can one of you lgtm?

**Comment by liggitt** [comment]
backport of that commit LGTM. @caesarxuchao @ironcladlou were there any prior changes in 1.8 related to custom resource GC that would have intersected with this?

**Comment by ironcladlou** [comment]
@liggitt 

>backport of that commit LGTM. @caesarxuchao @ironcladlou were there any prior changes in 1.8 related to custom resource GC that would have intersected with this?

The other significant change to the store related to GC for 1.8 came with https://github.com/kubernetes/kubernetes/commit/312fb1e1fa198f4715598feac659f5eeffd05032, which I don't *think* is required for this fix.

**Pull request merged**
