### PR TITLE
ObjectReflectDiff needs a few more checks for nil

### PR DESCRIPTION
**Pull request by smarterclayton**
Catches even more diffs correctly

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32434)

### CODE REVIEW

**Comment by brendandburns** [comment]
LGTM, but add tests for the new behavior.

**Comment by brendandburns** [comment]
ping to @smarterclayton for tests...

**Comment by smarterclayton** [comment]
Will do.

**Comment by smarterclayton** [comment]
Added more tests across the common cases this PR fixes

**Comment by smarterclayton** [comment]
From smoke

```
ERROR: (gcloud.container.clusters.create) ResponseError: code=500, message=Internal error encountered.
2016/09/27 14:31:03 e2e.go:468: Step 'up' finished in 31.560832197s
2016/09/27 14:31:03 e2e.go:133: Saved XML output to /workspace/_artifacts/junit_runner.xml.
2016/09/27 14:31:03 e2e.go:145: Something went wrong: starting e2e cluster: error running up: exit status 1
```

**Comment by brendandburns** [comment]
@k8s-bot test this issue:  #33611

**Comment by brendandburns** [comment]
@smarterclayton this looks to be an actual problem with some downward API tests.  Not sure why it only shows up in the GCI tests...

**Comment by smarterclayton** [comment]
@k8s-bot test this issue #33678

**Comment by smarterclayton** [comment]
Ok, GCI was a flake. Does this have your LGTM?

**Comment by smarterclayton** [comment]
@k8s-bot gci test this

**Comment by smarterclayton** [comment]
@k8s-bot gke test this

**Comment by smarterclayton** [comment]
@deads2k can you do a final review on this real quick?

**Comment by deads2k** [comment]
lgtm, but the reflect package is a mass of panics so I can't be sure I didn't miss something.

**Comment by smarterclayton** [comment]
I'm not aware of any diff logic that is used outside of tests.

**Pull request merged**
