### PR TITLE
Update sig-auth OWNERS

### PR DESCRIPTION
**Pull request by enj**
/kind cleanup
/sig auth
/priority important-longterm
/triage accepted
/milestone v1.22
/assign @mikedanese @liggitt 
@kubernetes/sig-auth-pr-reviews

xref: https://github.com/kubernetes/community/pull/5701

```release-note
NONE
```

### CODE REVIEW

**Comment by mikedanese** [comment]
/lgtm
/approve

For sig-auth. There are a few OWNERS files unrelated to sig-auth in here.

**Comment by liggitt** [comment]
first two commits lgtm. I'd suggest splitting the third general commit into its own PR

**Pull request merged**
