### PR TITLE
Add -x to du commands to not traverse other file systems

### LINKED ISSUE #71012: DiskUsage measurement doesn't ignore sub-mounts
I'm using K8S 1.10 and have a specific use case where I'm trying to use an emptyDir to share mounts between two containers in a pod.
I'm using the MountPropagation feature successfully, but while debugging another issue I noticed that the node was running a very long running du command.
Looking into the source I noted:
https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/pkg/volume/util/fs/fs.go

Which runs du on any emptyDir, do measure disk usage. I recommend that in this case we should add the -x flag that will skip any mounted directories as they do not count against the file usage and would make these scans a lot faster.

I could of course add a simple pull request for this but first wanted to see if this was known and on purpose.

To reproduce bind mount/loop mount/device mount any large/slow directory into an emptyDir volume and watch as the du process slogs away

**Environment**:
- Kubernetes 1.10
- GKE

/kind bug

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**

/kind bug 

**What this PR does / why we need it**:

See https://github.com/kubernetes/kubernetes/pull/71293
Since we can not get  feedback from @ehmm, I would like open this PR to fix it

**Which issue(s) this PR fixes**:

Fixes #71012
**Special notes for your reviewer**:

/cc @jingxu97 @msau42 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by msau42** [comment]
/assign @jingxu97 @dashpole 
#71293 tried to fix it by changing the cadvisor call, whereas this PR is fixing it in the VolumeMetrics interface, which gets output as pod volume usage under summary metrics.  Can you clarify where the cadvisor usage metric is used and if we should look into fixing that too?

**Comment by dashpole** [comment]
/lgtm
The cadvisor change was for collection of metrics for the container writable layer.  However, we had already switched to a golang implementation to replace `du` and `find`.  We should probably transition the volume metrics collection to use the golang implementation, but can do this in the meantime.

**Comment by msau42** [comment]
Thanks for the explanation! lgtm

@cwdsuzhou can you update your PR title to reflect that it's adding "-x" option, not "-s"

**Comment by cwdsuzhou** [comment]
@msau42  should we cherry pick this PR to other release versions?

**Pull request merged**
