### PR TITLE
Convert * users/groups to system:authenticated group in ABAC

### PR DESCRIPTION
**Pull request by liggitt**
Part of enabling anonymous auth by default in 1.6 means protecting earlier policies that did not intend to grant access to anonymous users.

This modifies ABAC policies that match `user` or `group` `*` to only match authenticated users.

Docs PR to update examples to use `system:authenticated` or `system:unauthenticated` groups explicitly: https://github.com/kubernetes/kubernetes.github.io/pull/1992

```release-note
ABAC policies using "user":"*" or "group":"*" to match all users or groups will only match authenticated requests. To match unauthenticated requests, ABAC policies must explicitly specify "group":"system:unauthenticated"
```

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm

**Comment by liggitt** [comment]
cc @kubernetes/sig-auth-misc

**Comment by liggitt** [comment]
@k8s-bot gci gke e2e test this
@k8s-bot cvm gke e2e test this

**Comment by liggitt** [comment]
Flake on https://github.com/kubernetes/kubernetes/issues/37982
@k8s-bot unit test this

**Pull request merged**
