### PR TITLE
Bugfix: checkpoint.go#LoadPods ignores error

### LINKED ISSUE #81273: Error not well handled in checkpoint.go
/kind bug

During reading the codes of pkg/kubelet/checkpoint/checkpoint.go 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/checkpoint/checkpoint.go#L98
I find we missed the error returned since https://github.com/kubernetes/kubernetes/pull/56040.
See https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/config/config.go#L125 , we would alway send `PodUpdate` to `updates` when we call `LoadPods(c.checkpointManager)`

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

I find since this PR https://github.com/kubernetes/kubernetes/pull/56040, we ignore error. I have found the reason to remove it and it seems this error is necessary.

**Which issue(s) this PR fixes**: 

Fixes #81273 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
/hold

Thanks for your pr @cwdsuzhou 

I think we want to be carefully think through the ramifications of this pr before merging it - I'm not sure that all of its consequences are ones we desire.

Most prominently, if we return an error from `LoadPods`, then I believe that error will eventually bubble up to `pkg/kubelet.NewMainKubelet`. In other words, we won't be able to start the Kubelet.

I'd love confirmation from the original authors (cc @yujuhong @tallclair), but my guess is that a failure in `LoadPods` is not supposed to cause an overall Kubelet failure.

Regardless, I think there's some room for better documentation around the goal and importance of `LoadPods`, perhaps as a function level comment. Again, hoping @yujuhong and @tallclair can weigh in on this :)

**Comment by cwdsuzhou** [comment]
> opi

@yujuhong @tallclair can you give us some description about this change, thanks!

**Comment by liggitt** [comment]
based on feedback in https://github.com/kubernetes/kubernetes/pull/72202 (see https://github.com/kubernetes/kubernetes/pull/72202#issuecomment-528366080 this will be removed in 1.17

/close

**Pull request closed without merging**
