### PR TITLE
Upgrade sample-apiserver image to be built based on 1.9 k8s 

### LINKED ISSUE #63622: Flaky Test : [sig-api-machinery] Aggregator Should be able to support the 1.7 Sample API Server using the current Aggregator fails on "pull-kubernetes-e2e-gce" and "ci-kubernetes-e2e-gci-gce"
## Flaky Tests
* [pull-kubernetes-e2e-gce](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/pr-logs/pull/59284/pull-kubernetes-e2e-gce/)
* [ci-kubernetes-e2e-gci-gce](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/)

## Flakiest test 
[sig-api-machinery] Aggregator Should be able to support the 1.7 Sample API Server using the current Aggregator

## Failures in TestGrid
* [pull-kubernetes-e2e-gce](https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&include-filter-by-regex=Aggregator%20Should%20be%20able%20to%20support%20th)
* [ci-kubernetes-e2e-gci-gce](https://k8s-testgrid.appspot.com/sig-api-machinery#gce)

## Triage link
More nuanced logs and details can be found at https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=api-machinery&job=ci-kubernetes-e2e-gci-gce&test=Aggregator%20Should%20be%20able%20to%20support%20the%201.7%20Sample%20AP

# Error
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/aggregator.go:76
gave up waiting for apiservice wardle to come up successfully
Expected error:
    <*errors.errorString | 0xc420131150>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/aggregator.go:337

/priority failing-test
/priority important-soon
/kind flake
/sig-api-machinery
@kubernetes/sig-api-machinery-bugs 
/assign @liggitt 

@liggitt can you please help triage this issue?

### PR DESCRIPTION
**Pull request by fedebongio**
**What this PR does / why we need it**:
It upgrades the parameters on the sample-apiserver generation scripts to generate a 1.9 version of the sample api sever 

**Which issue(s) this PR fixes**:
Fixes #63622

**Special notes for your reviewer**:
Let me know if I'm missing anything

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by yliaog** [comment]
the commit be06b2223ed022c8ff2d488ce2a3bdfdc556dd33 "Merge pull request #1 from fedebongio/fedebongio-patch-1 " should be removed.

**Comment by fedebongio** [comment]
Opening #68545 and closing this one for a better commit history

**Pull request closed without merging**
