### PR TITLE
Automated cherry pick of #59172: Remove YEAR field of all generated files and fix kubernetes boilerplate 

### PR DESCRIPTION
**Pull request by fisherxu**
Cherry pick of #59172 on release-1.10.

#59172: Remove YEAR field of all generated files and fix kubernetes boilerplate

### CODE REVIEW

**Comment by fisherxu** [comment]
Along with #60866, pick it to 1.10 branch. cc @thockin @sttts

**Comment by thockin** [comment]
Is this really important to cherry pick?

**Comment by fisherxu** [comment]
@thockin The other half of new year checker for not generated files #60866 has milestone 1.10, so I also pick this half. Will helpful to users who use this release until 2019.

**Comment by MaciekPytel** [comment]
Do we want to proceed with this given that it missed 1.10.0? It looks like a very strange thing to change in patch release and I'd rather not do it, unless someone comes up with a very good reason for it.

**Comment by liggitt** [comment]
> It looks like a very strange thing to change in patch release and I'd rather not do it,

agree... smallest diff possible in release branches is preferred

**Comment by fisherxu** [comment]
ok, so we close it.

**Pull request closed without merging**
