### PR TITLE
build: Bump kube-cross to v1.12.17-2

### PR DESCRIPTION
**Pull request by justaugustus**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Unblocks [Kubernetes 1.15.12 release](https://github.com/kubernetes/sig-release/issues/1051)**
build: Bump kube-cross to v1.12.17-2

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

~This PR intentionally targets the staging kube-cross image to test changes happening in https://github.com/kubernetes/release/pull/1258.~

**Does this PR introduce a user-facing change?**:

```release-note
build: Bump kube-cross to v1.12.17-2
```

### CODE REVIEW

**Comment by justaugustus** [comment]
Retesting as a new staging image has been pushed:
/test pull-kubernetes-cross

**Comment by justaugustus** [comment]
kube-cross promotion PR has merged: https://github.com/kubernetes/k8s.io/pull/838

/assign @cblecker @fejta 
cc: @kubernetes/release-engineering

**Comment by tpepper** [comment]
With https://github.com/kubernetes/k8s.io/pull/838 merged and expecting OWNERS approval shortly, preemptively adding
/lgtm
and cherry-pick-approved.

**Pull request merged**
