### PR TITLE
[WIP] Fix bug  in scheduler preemption

### LINKED ISSUE #76836: Bug exist in  Pod Priority and Preemption
**What happened**:

I set up a cluster with 2 nodes. I used 2 rs to test preemption.  2  yamls of rs are as flow:

```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx
  name: webcritial1
  namespace: default
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginxcritial1
  template:
    metadata:
      labels:
        app: nginxcritial1
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginxcritial1
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
``` 
```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx
  name: webcritial
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginxcritial
  template:
    metadata:
      labels:
        app: nginxcritial
    spec:
      priorityClassName: system-node-critical
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginxcritial
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

1. I first created  the rs webcritial.
2. created  the rs webcritial1.

results are like this:

image

image

image

webcritial with high priority can not creatiepod successfully.

**What you expected to happen**:

webcritial with high priority can create pod successfully. pods of webcritial1 would be deleted.

**How to reproduce it (as minimally and precisely as possible)**:

write the yaml as I pasted and run it.

**Anything else we need to know?**:

When set the priority directly,  preemption can work which use priorityClass can not work

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**

/kind bug
/kind design

**What this PR does / why we need it**:

Fix bug https://github.com/kubernetes/kubernetes/issues/76836

**Which issue(s) this PR fixes**:

Fixes #76836, priorityClass can not work

**Special notes for your reviewer**:

/cc @k82cn @bsalamat 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Huang-Wei — COMMENTED** [review]
Priority value is mixed into pod spec by Priority admission plugin. This is as design.

**Comment by cwdsuzhou** [comment]
> Priority value is mixed into pod spec by Priority admission plugin. This is as design.

Yes, but I found priority of pod is not set. Currently, I am just trying t o fix it.

**Comment by cwdsuzhou** [comment]
Close it until we ensure the issue exist.

**Comment by bsalamat** [comment]
@cwdsuzhou as @Huang-Wei noted, priority of a pod is resolved by "Priority" admission plugin and is set in pod spec. If you don't see the priority, chances are that the Priority admission plugin is not enabled in your setup.
I know you have spent a lot of time to investigate the issue and to prepare this PR. Next time if you encounter a bug, you may want to file an issue to verify that it actually exists, before spending time on it.

**Comment by cwdsuzhou** [comment]
> @cwdsuzhou as @Huang-Wei noted, priority of a pod is resolved by "Priority" admission plugin and is set in pod spec. If you don't see the priority, chances are that the Priority admission plugin is not enabled in your setup.
> I know you have spent a lot of time to investigate the issue and to prepare this PR. Next time if you encounter a bug, you may want to file an issue to verify that it actually exists, before spending time on it.

Thanks very much for your clarification and kind suggestions.

**Comment by Huang-Wei** [comment]
I felt the same as @bsalamat. We do like people to contribute to scheduling, and really appreciate contributors' time, esp. on investigating issues.

As @bsalamat said, in order to save your time, if you have a doubt on whether it's an issue or not, don't hesitate to raise an issue first. If it's confirmed an issue, we will make it fair to ensure the issue author has the "Priority" to work out a PR first (if he/she wants to).

So I hope you won't be upset ending up with a closed PR with a lot of efforts :)

**Comment by cwdsuzhou** [comment]
> I felt the same as @bsalamat. We do like people to contribute to scheduling, and really appreciate contributors' time, esp. on investigating issues.
> 
> As @bsalamat said, in order to save your time, if you have a doubt on whether it's an issue or not, don't hesitate to raise an issue first. If it's confirmed an issue, we will make it fair to ensure the issue author has the "Priority" to work out a PR first (if he/she wants to).
> 
> So I hope you won't be upset ending up with a closed PR with a lot of efforts :)

Thanks for your encouragement, I would continue trying to contribute  to k8s. Though this PR is closed, it helps me realize some issues in our online cluster caused by configuration due to some historical reasons

**Pull request closed without merging**
