### PR TITLE
Fix a comment in job_controller

### PR DESCRIPTION
**Pull request by kolorful**
/kind documentation

**What this PR does / why we need it**:

Fixed an error in a job_controller's comment

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Review by php-coder — APPROVED** [review]
/lgtm
/ok-to-test
/kind cleanup

**Comment by kolorful** [comment]
Hi @foxish @enisoc, would you be able to take a quick look at this trivial change, thank you!

**Comment by kolorful** [comment]
Hi @foxish @enisoc @php-coder , would you be able to take a quick look at this trivial change, thank you! It's been 3 months.

**Comment by php-coder** [comment]
@kubernetes/sig-apps-misc PTAL and approve this trivial fix.

**Review by janetkuo — APPROVED** [review]

**Pull request merged**
