### PR TITLE
pkg/api: extract Scheme/Registry/Codecs into pkg/api/legacyscheme

### PR DESCRIPTION
**Pull request by sttts**
This serves as

- a preparation for the pkg/api->pkg/apis/core move
- and makes the dependency to the scheme explicit when vizualizing
  left depenncies.

The later helps with our our efforts to split up the monolithic repo
into self-contained sub-repos, e.g. for kubectl, controller-manager
and kube-apiserver in the future.

### CODE REVIEW

**Comment by deads2k** [comment]
This appears mechanical.

/lgtm
/approve no-issue

@smarterclayton approval

**Comment by sttts** [comment]
Bitbucket is down and CI doesn't like that.

**Comment by sttts** [comment]
@smarterclayton is this approved?

**Comment by sttts** [comment]
/retest

TestCRD flake.

**Pull request merged**
