### PR TITLE
update gophercloud/gophercloud dependency

### LINKED ISSUE #44461: openstack cloud provider fails to reauthenticate
**Is this a request for help?** (If yes, you should use our troubleshooting guide and community support channels, see http://kubernetes.io/docs/troubleshooting/.):
no

**What keywords did you search in Kubernetes issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

cinder / openstack / reauth

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+coreos.0", GitCommit:"9212f77ed8c169a0afa02e58dce87913c6387b3e", GitTreeState:"clean", BuildDate:"2017-04-04T00:32:53Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1+coreos.0", GitCommit:"9212f77ed8c169a0afa02e58dce87913c6387b3e", GitTreeState:"clean", BuildDate:"2017-04-04T00:32:53Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: OpenStack
- **OS** (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`):
```
Linux mgmt-01 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
- **Install tools**:
Kargo
- **Others**:
Kubelet running in rkt via systemd service; docker still used for kubernetes workloads

**What happened**:
When kubelet initially starts up, it is able to successfully authenticate to openstack and openstack integration works great ( dynamic provisioning with cinder, pulling instance data, etc ). However, after 12h ( our token TTL ), kubelet ( and other kubernetes components ) attempt to reauthenticate and fail to do so --  
```
Apr 11 16:01:36 control-01 rkt[24916]: I0411 16:01:36.851732   24916 openstack_instances.go:80] Claiming to support Instances
Apr 11 16:01:38 control-01 rkt[24916]: I0411 16:01:38.892420   24916 container_manager_linux.go:439] Discovered runtime cgroups name: /system.slice/docker.service
Apr 11 16:01:42 control-01 rkt[24916]: I0411 16:01:42.974724   24916 server.go:778] GET /metrics: (60.65808ms) 200 [[Go-http-client/1.1] 10.232.255.10:57764]
Apr 11 16:01:47 control-01 rkt[24916]: W0411 16:01:47.858585   24916 openstack_instances.go:75] Failed to find compute flavors: Successfully re-authenticated, but got error executing request: Invalid requst
```
After it fails to re-authenticate, cinder persistent volumes can no longer be created. 

We did some packet captures and found that during kubelet startup, it sends in the correctly scoped request --
```
{
    "auth": {
        "identity": {
            "methods": [
                "password"
            ], 
            "password": {
                "user": {
                    "domain": {
                        "name": "domainname"
                    }, 
                    "name": "username", 
                    "password": "password"
                }
            }
        }, 
        "scope": {
            "project": {
                "id": "9dedeb58b40044c5a93946bfec716429"
            }
        }
    }
}
```
When doing the reauth, the scope is missing from the request, 
```
{
    "auth": {
        "identity": {
            "methods": [
                "password"
            ], 
            "password": {
                "user": {
                    "domain": {
                        "name": "domainname"
                    }, 
                    "name": "username", 
                    "password": "password"
                }
            }
        }
    }
}
```
Which results in openstack responding with
```
{
    "badRequest": {
        "code": 400, 
        "message": "Malformed request URL: URL's project_id '9dedeb58b40044c5a93946bfec716429' doesn't match Context's project_id 'None'"
    }
}
```

**What you expected to happen**:
Kubernetes components can reauthenticate with Openstack as necessary

**How to reproduce it** (as minimally and precisely as possible):
Provision an environment with openstack cloud provider, let it sit around for 12h ( or longer depending on the configuration for the session to expire ). You should be able to see log messages in kubelet and controller-manager about failing to connect with openstack. You can also attempt to provision a pv/pvc using cinder and see it get stuck in a pending state. 

**Anything else we need to know**:
I believe this was working correctly in 1.5.x
It looks like between 1.5 -> 1.6, gophercloud was replaced/updated. I'm suspecting it has something to do with this, but not positive.

### PR DESCRIPTION
**Pull request by stuart-warren**
**What this PR does / why we need it**:

**Which issue this PR fixes** 
fixes #44461

**Special notes for your reviewer**:

**Release note**:

```release-note
update gophercloud/gophercloud dependency for reauthentication fixes
```

### CODE REVIEW

**Review by bradbeam — APPROVED** [review]

**Comment by stuart-warren** [comment]
I've signed the CLA

**Comment by stuart-warren** [comment]
I've really signed the CLA

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by dims** [comment]
@stuart-warren - Do you have some time to freshen up this patch? Thanks!

**Comment by stuart-warren** [comment]
@dims done I believe
Updating deps is a pain :(

**Comment by dims** [comment]
@stuart-warren yes that it is!!! thanks

**Comment by dims** [comment]
@jbeda @lavalamp - is it appropriate to update dependencies at this stage in the game? Thanks!

/unassign

**Comment by dims** [comment]
@dchen1107 - yes, let us please merge this PR for 1.7 (on behalf of sig-openstack)

**Comment by anguslees** [comment]
Yes, we need this cherrypicked or the openstack cloud provider is going to be basically unusable for 1.7 (at least, after it's been running for 12h).

You can see from the vendor/ diffs that the _only_ changes are 1) the desired gophercloud `auth_options.go` fix, and 2) some harmless additions of new gophercloud constants in `requests.go`.   This is a very targeted vendor/ update.

**Pull request merged**
