### PR TITLE
Add unit test case for controller/disruption

### PR DESCRIPTION
**Pull request by houjun41544**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
needs milestone to be included before code freeze.

**Comment by idealhack** [comment]
@kubernetes/sig-apps-pr-reviews 
/remove-lifecycle stale

**Comment by mikedanese** [comment]
This looks fine. It could be easily rolled into other tests in this package with a table test.

/lgtm
/approve

**Pull request merged**
