### PR TITLE
Update ConfigMap test

### PR DESCRIPTION
**Pull request by BobyMCbobs**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Updates test to suggestions in PR #81205

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by alejandrox1 — APPROVED** [review]
/lgtm
/ok-to-test

**Review by neolit123 — COMMENTED** [review]
/lgtm
/priority backlog

**Comment by neolit123** [comment]
thanks for the update. we are in code freeze until the 10th.

**Comment by devaips** [comment]
cc @kubernetes/sig-node-pr-reviews

**Pull request merged**
