### PR TITLE
Revert "fieldmanager: Strip managedfields BEFORE we update the timestamp"

### PR DESCRIPTION
**Pull request by pacoxu**
Reverts kubernetes/kubernetes#100032

for testing

### CODE REVIEW

**Comment by pacoxu** [comment]
#101019 related

**Comment by pacoxu** [comment]
/test pull-kubernetes-integration
3rd run

**Comment by pacoxu** [comment]
/kind flake
/release-note-none

I think we should revert this change and check why it flakes.

**Comment by apelisse** [comment]
That's clearly the problem, but we have #101076 that is probably better, thanks!

**Pull request closed without merging**
