### PR TITLE
[1.18] Cleanup CHANGELOG/README.md

### PR DESCRIPTION
**Pull request by saschagrunert**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

We have no automatism in place right now to do this automatically, so
we're adapting the CHANGELOG/README.md manually.

**Which issue(s) this PR fixes**:

None

**Special notes for your reviewer**:

None

**Does this PR introduce a user-facing change?**:

```release-note
None
```

/cc @kubernetes/release-engineering

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
How do we proceed with the cherrypick-not-approved label? :)

**Pull request merged**
