### PR TITLE
kubeadm: Update v1beta2 doc.go

### PR DESCRIPTION
**Pull request by rosti**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

This change updates the doc.go file for v1beta2 config of kubeadm.

**Which issue(s) this PR fixes**:

refs kubernetes/enhancements#970 kubernetes/kubeadm#1439

**Special notes for your reviewer**:

/cc @kubernetes/sig-cluster-lifecycle-pr-reviews
/area kubeadm
/priority important-longterm
/assign @fabriziopandini
/assign @neolit123

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Comment by makoscafee** [comment]
Hi @rosti Sorry, Since this PR is meant for release 1.15 would you mind opening it against branch `dev-1.15`?. Thank you

/milestone 1.15

**Pull request merged**
