### PR TITLE
Kubelet: remove name filter from CRI

### PR DESCRIPTION
**Pull request by feiskyer**
Since #30753 and #30463, `name` is not used to identify the container/sandbox, so remove it from CRI.

cc @yujuhong @kubernetes/sig-node @kubernetes/sig-rktnetes

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31576)

### CODE REVIEW

**Comment by tmrts** [comment]
LGTM-lite :+1:

**Comment by yujuhong** [comment]
This is going to cause more rebases, so I am holding on to it until other PRs land.

**Comment by euank** [comment]
:lgtm: waiting to avoid rebase-hell elsewhere sgtm too.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31576#-:-KQXZ6zLUpLc7JBBA3O3:b-a0o031)*

**Comment by feiskyer** [comment]
@yujuhong @tmrts @euank Rebased. PTAL.

**Comment by yujuhong** [comment]
Since this PR needs to rebased again, let's wait until #31804 also lands to avoid further conflict (thanks!)

**Comment by yujuhong** [comment]
#31804 has been merged. @feiskyer feel free to rebase

**Comment by feiskyer** [comment]
@yujuhong Rebased. PTAL.

**Comment by feiskyer** [comment]
@k8s-bot test this please, issue #IGNORE

**Comment by feiskyer** [comment]
@k8s-bot test this please, issue #IGNORE

**Comment by feiskyer** [comment]
Rebased several times, still have SCM problem. @yujuhong do you know the cause of this problem?

```
ERROR: Error fetching remote repo 'remote'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/kubernetes/kubernetes
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:810)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1066)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1097)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
... skipping 2 lines ...
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: hudson.plugins.git.GitException: Command "/usr/bin/git -c core.askpass=true fetch --tags --progress https://github.com/kubernetes/kubernetes +refs/heads/*:refs/remotes/upstream/*" returned status code 128:
stdout: 
stderr: error: object file .git/objects/17/d4cf1af43a03a5997ea9142b19e5b1ac2d8747 is empty
fatal: loose object 17d4cf1af43a03a5997ea9142b19e5b1ac2d8747 (stored in .git/objects/17/d4cf1af43a03a5997ea9142b19e5b1ac2d8747) is corrupt
fatal: The remote end hung up unexpectedly
```

**Comment by yujuhong** [comment]
@k8s-bot test this issue: #32574

**Pull request merged**
