### PR TITLE
staging/publishing: add release-1.26 branch

### PR DESCRIPTION
**Pull request by salaxander**
#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
Adds publishing config for new 1.26 release branch after RC.0 cut

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

`NONE`
```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jeremyrickard** [comment]
/hold cancel 

release is done

**Comment by liggitt** [comment]
required https://github.com/kubernetes/kubernetes/pull/113937 to get a clean verify run

**Comment by jeremyrickard** [comment]
This was done as part of https://github.com/kubernetes/sig-release/issues/2087

**Pull request merged**
