### PR TITLE
GCE provider: Create TargetPool with 200 instances, then update with rest

### PR DESCRIPTION
**Pull request by zmerlynn**
GCE provider: Create TargetPool with 200 instances, then update with rest

Tested with 2000 nodes, this actually meets the GCE API specifications (which is nutty). Previous PR (#25178) was based on a mistaken understanding of a poorly documented set of limitations, and even poorer testing, for which I am embarassed.

Also includes the revert of #25178 (review commits separately).

[Analytics]()

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Comment by thockin** [comment]
@chrislovecnm

**Comment by chrislovecnm** [comment]
@thockin ... I think I MIGHT be able to get ingress, up.  I set affinity rules so that the RC would only be on two nodes.  @bprashanth is assisting.

**Comment by zmerlynn** [comment]
@chrislovecnm: We'll also have a v1.2.5 that includes this PR soon.

**Comment by roberthbailey** [comment]
[v1.2.5](https://github.com/kubernetes/kubernetes/releases/tag/v1.2.5) is now out!

**Comment by chrislovecnm** [comment]
@zmerlynn I am running 1.3 beta 2 and have 1009 nodes ... I am guessing I am going to hit a gce error...

**Comment by zmerlynn** [comment]
I thought this made it into `beta.2`.

**Comment by chrislovecnm** [comment]
@zmerlynn ping me on slack .. I am working with @bprashanth to figure out what is going on.  May be user error.

**Comment by chrislovecnm** [comment]
So GCE api is blowing up on me:

```console
E0628 02:26:40.427634       7 utils.go:103] Requeuing pet-race-ui/pet-race-ui, err googleapi: Error 403: Exceeded limit 'MAX_INSTANCES_IN_INSTANCE_GROUP' on resource 'k8s-ig--c9a6052e1676112c'. Limit: 1000.0, limitExceeded, unable to get loadbalancer: Loadbalancer pet-race-ui-pet-race-ui--c9a6052e1676112c not in pool
I0628 02:26:40.429150       7 event.go:216] Event(api.ObjectReference{Kind:"Ingress", Namespace:"pet-race-ui", Name:"pet-race-ui", UID:"fb01f977-3cd5-11e6-af56-42010a800002", APIVersion:"extensions", ResourceVersion:"57749081", FieldPath:""}): type: 'Warning' reason: 'GCE :Quota' googleapi: Error 403: Exceeded limit 'MAX_INSTANCES_IN_INSTANCE_GROUP' on resource 'k8s-ig--c9a6052e1676112c'. Limit: 1000.0, limitExceeded
E0628 02:26:41.827753       7 utils.go:103] Requeuing pet-race-ui/pet-race-ui, err googleapi: Error 403: Exceeded limit 'MAX_INSTANCES_IN_INSTANCE_GROUP' on resource 'k8s-ig--c9a6052e1676112c'. Limit: 1000.0, limitExceeded, unable to get loadbalancer: Loadbalancer pet-race-ui-pet-race-ui--c9a6052e1676112c not in pool
I0628 02:26:41.827937       7 event.go:216] Event(api.ObjectReference{Kind:"Ingress", Namespace:"pet-race-ui", Name:"pet-race-ui", UID:"fb01f977-3cd5-11e6-af56-42010a800002", APIVersion:"extensions", ResourceVersion:"57749081", FieldPath:""}): type: 'Warning' reason: 'GCE :Quota' googleapi: Error 403: Exceeded limit 'MAX_INSTANCES_IN_INSTANCE_GROUP' on resource 'k8s-ig--c9a6052e1676112c'. Limit: 1000.0, limitExceeded
```

**Comment by bprashanth** [comment]
That's a different type of lb. 
This bug is about service.type=loadbalancer and target pools.
youre hitting the max limit on a single instance group. 
Try making your serivce of type=lb and see if you get an error about taret pool size.

**Comment by bprashanth** [comment]
Hmm, for the record apparently either the fix isn't in beta.2, or Chris is not using beta.2, because he got:
```
to create load balancer for service pet-race-ui/pet-race-ui: failed to create target pool afadfae6f3cd511e6af5642010a80000: googleapi: Error 413: Value for field 'resource.instances' is too large: maximum size 200 element(s); actual size 1000.
More details:
Reason: fieldSizeTooLarge, Message: Value for field 'resource.instances' is too large: maximum size 200 element(s); actual size 1000.
Reason: fieldSizeTooLarge, Message: Value for field 'resource.instances' is too large: maximum size 200 element(s); actual size 1000.
```

**Comment by zmerlynn** [comment]
I just glanced, and this PR didn't make `beta.2`. I was thinking of the other scalability limitation from the same day, #27741. With #27741 and not this PR, the results above are consistent (which I should have remembered, since this was only an intermediate state that existed on my branch when I was testing on large clusters, and annoyingly in `1.3.0-beta.2`).

**Comment by chrislovecnm** [comment]
@zmerlynn I think we have a bug as well.  Backend services are not being removed, upon deletion.

**Comment by zmerlynn** [comment]
Please file an issue with details. This PR has already merged, there's no reason to have a conversation here.

**Comment by chrislovecnm** [comment]
As soon as I hit enter I realized that. Need sleep ;)

**Pull request merged**
