### PR TITLE
Move cmd/genutils to pkg/util/

### PR DESCRIPTION
**Pull request by whzghb**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

I think the genutils directory should be placed within the util directory, There is no main function in genutils, so it should not be placed in the cmd directory

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
are these binaries still used? can they be consolidated into a single docs-generating package and this util kept in the same package? I don't love spreading doc utils into the k/k package structure

**Comment by whzghb** [comment]
> are these binaries still used? can they be consolidated into a single docs-generating package and this util kept in the same package? I don't love spreading doc utils into the k/k package structure

/cc @liggitt Do you want the current directory structure, or do you want to merge them into a single binary?

**Comment by liggitt** [comment]
> > are these binaries still used? can they be consolidated into a single docs-generating package and this util kept in the same package? I don't love spreading doc utils into the k/k package structure
> 
> /cc @liggitt Do you want the current directory structure, or do you want to merge them into a single binary?

if we can check with sig-docs folks if these are still used, clean up any that are unused, and collapse the rest into a single docs-generating binary, I think that would be a good cleanup

**Comment by whzghb** [comment]
> if we can check with sig-docs folks if these are still used, clean up any that are unused, and collapse the rest into a single docs-generating binary (and inline this util package), I think that would be a good cleanup

yes that would be better

**Pull request closed without merging**
