### PR TITLE
Remove deprecated AlwaysAdmit admission

### PR DESCRIPTION
**Pull request by mengjiao-liu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
AlwaysAdmit admission is deprecated in version 1.10 
so we can remove deprecated AlwaysAdmit admission now.

Ref #58123 #61104

#### Does this PR introduce a user-facing change?

```release-note
Removed the deprecated `AlwaysAdmit` admission controller
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Both `AlwaysAdmit` and `AlwaysDeny` have been declared deprecation since v1.13, according to the [doc](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#what-does-each-admission-controller-do). I think it's safe to remove both. We can remove the `AlwaysDeny` in a followup.

We need to update the [doc](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#what-does-each-admission-controller-do) as well.

/lgtm
/cc @deads2k @sttts

**Comment by sftim** [comment]
I'd write
```
Removed the deprecated `AlwaysAdmit` admission controller
```
for the release note

**Comment by mengjiao-liu** [comment]
> I'd write
> 
> ```
> Removed the deprecated `AlwaysAdmit` admission controller
> ```
> 
> for the release note

Updated. Thanks!

**Comment by mengjiao-liu** [comment]
> We can remove the `AlwaysDeny` in a followup.

I also think it is safe to remove the `AlwaysDeny` admission controller according to the deprecation rules.
/cc @liggitt

**Comment by mengjiao-liu** [comment]
Request review @deads2k @lavalamp @liggitt @sttts

**Comment by caesarxuchao** [comment]
/assign @deads2k

for approval.

**Comment by mengjiao-liu** [comment]
ping @deads2k

**Comment by mengjiao-liu** [comment]
ping @deads2k

**Comment by mengjiao-liu** [comment]
Request review @derekwaynecarr @deads2k

**Comment by mengjiao-liu** [comment]
ping @liggitt  @derekwaynecarr @deads2k

**Comment by lavalamp** [comment]
I'd like @deads2k to sign off on this

API Machinery might be the code owner but I think you're getting nowhere with this because SIG Security owns the concept in general

/sig security
/remove-sig api-machinery
/remove-triage

**Comment by enj** [comment]
> I'd like @deads2k to sign off on this
> 
> API Machinery might be the code owner but I think you're getting nowhere with this because SIG Security owns the concept in general
> 
> /sig security
> /remove-sig api-machinery
> /remove-triage

/remove-sig security
/sig auth

David is still the right person, but SIG security doesn't own any code or concepts in this repo.  All of that belongs to SIG Auth.

**Comment by aramase** [comment]
/triage accepted

@deads2k Could you take a look at this PR when you get a chance?

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by mengjiao-liu** [comment]
> If you still need this PR then please rebase, if not, please close the PR

Rebased.

**Comment by mengjiao-liu** [comment]
ping @deads2k

**Comment by mengjiao-liu** [comment]
> David is still the right person, but SIG security doesn't own any code or concepts in this repo. All of that belongs to SIG Auth.

@deads2k @liggitt @mikedanese  Can somebody take a look at this PR? It's been open for a long time.

**Pull request closed without merging**
