### PR TITLE
Move pkg/kubectl/util/hash to staging

### PR DESCRIPTION
**Pull request by seans3**
* Moves `pkg/kubectl/util/hash` to staging.
* Publishes this code to the new kubectl repository: https://github.com/kubernetes/kubectl/pkg/util/hash.
* Code will be available for re-use after publishing.

/kind cleanup
/sig cli
/area kubectl

```release-note
NONE
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
although you need to update import restrictions

**Comment by nikhita** [comment]
Needs another rebase, sorry! :(

**Review by nikhita — APPROVED** [review]
/lgtm

**Pull request merged**
