### PR TITLE
[WIP] DO NOT MERGE: Experiment: Disable client-side rate-limitting

### PR DESCRIPTION
**Pull request by wojtek-t**
Experimental PR to better understand the effect of disabling client-side rate-limitting in scalability tests.

We will need to run a slightly tuned version of tests too as currently the tests are also artifically throttled, but we will need this PR opened for that anyone to modify run the presubmit with it.

@MikeSpreitzer @tkashem @deads2k - FYI

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
See also #111854

**Comment by MikeSpreitzer** [comment]
The pull-kubernetes-verify failure is because linting got pickier.  https://golangci-lint.run/usage/false-positives/ documents how to selectively disable linting.  Also, I have found that wrapping code with `if true { ... }`  makes a difference to some checks.

The pull-kubernetes-unit failure is because there is now a unit test for the config behavior that this PR hacks.

**Comment by dims** [comment]
This PR has the label work-in-progress, please revisit to see if you still need this, please close if not

**Comment by wojtek-t** [comment]
Something seems to be wrong with this PR, as the test isn't at all faster than the regular 5k-node test...

**Comment by wojtek-t** [comment]
> Something seems to be wrong with this PR, as the test isn't at all faster than the regular 5k-node test...

Should be fixed with the second commit.

**Comment by aojea** [comment]
are we progressing or regressing 😄

**Comment by MikeSpreitzer** [comment]
test pull-kubernetes-e2e-gce-scale-performance-manual to investigate further

**Comment by dims** [comment]
still need this @wojtek-t ?

**Comment by wojtek-t** [comment]
> still need this @wojtek-t ?

Yes - it's a PR that we will still use to validate some APF changes - currently waiting on https://github.com/kubernetes/perf-tests/pull/2205 for further progress.

**Comment by wojtek-t** [comment]
With https://github.com/kubernetes/perf-tests/pull/2205 already merged, let's see how the test will look like.

/test pull-kubernetes-e2e-gce-scale-performance-manual

**Comment by wojtek-t** [comment]
With https://github.com/kubernetes/perf-tests/pull/2258 merged we should no longer have clusterloader calls in exempt. Let's see where we are now

/test pull-kubernetes-e2e-gce-scale-performance-manual

**Comment by dims** [comment]
This work-in-progress PR needs a rebase. please rebase if this PR is still needed for the upcoming release.

**Pull request closed without merging**
