### PR TITLE
Update Web UI Bar Gauge Graphs

### PR DESCRIPTION
**Pull request by bcbroussard**
- Changed file system abbreviation from 'FS' to Filesystem (#9350)
- Made chart height dynamic and incorporated legend height change into the master code/datafile.go binary (#8726, #10165, #9347)
- Updated the max colors for the graph, eliminating the black background (#9350)
- Realigned the graph numbers

bar-num

### CODE REVIEW

**Comment by bcbroussard** [comment]
Admins, this is a low risk change, ok for v1

**Comment by roberthbailey** [comment]
@lavalamp can you take a look at this?

**Comment by roberthbailey** [comment]
@k8s-bot ok to test

**Comment by lavalamp** [comment]
LGTM @davidopp for second LGTM

**Comment by davidopp** [comment]
LGTM

**Pull request merged**
