### PR TITLE
Adds new tests to improve coverage and removes unused params passed to proxy server.

### PR DESCRIPTION
**Pull request by aveshagarwal**
This patch:
1. Removes unused params passed to proxy server.
2. Adds a new test case and increases code coverage.

### CODE REVIEW

**Comment by pmorie** [comment]
@kubernetes/rh-networking

**Comment by dchen1107** [comment]
Nice work! LGTM

**Comment by dchen1107** [comment]
Noticed there is new push after my first lgtm. Remove lgtm for now. @aveshagarwal what are the new changes?

**Comment by aveshagarwal** [comment]
@dchen1107 tests for cmd/kube-proxy/app/ in Shippable tests are failing and It does not show any logs explaining why are they failing? Even though those tests passes locally on my machine. So I have been trying some changes to understand why they are failing.

**Comment by aveshagarwal** [comment]
I have updated this PR with one test case that passes. I have removed other test cases as I am not sure right now why are they failing with Shippable.

**Comment by pmorie** [comment]
did you mean to close this?

**Comment by aveshagarwal** [comment]
@pmorie No, Shippable 's all tests passed but still Shippable were showing failed. So I just closed and reopend to run Shippable again.

**Comment by aveshagarwal** [comment]
All checks passed now.

**Comment by aveshagarwal** [comment]
@dchen1107 updated PR and all checks passed.

**Comment by aveshagarwal** [comment]
Would appreciate any feedback.

**Pull request merged**
