### PR TITLE
Fix  #25606: Add the length detection of the "predicateFuncs" in generic_scheduler.go

### PR DESCRIPTION
**Pull request by ping035627**
Fix  #25606

The PR add the length detection of the "predicateFuncs" for "findNodesThatFit" function of generic_scheduler.go. 
In “findNodesThatFit” function, if the length of the "predicateFuncs" parameter is 0, it can set filtered equals nodes.Items, and needn't to traverse the nodes.Items.

### CODE REVIEW

**Comment by ping035627** [comment]
@lavalamp need to test, thanks.

**Comment by ping035627** [comment]
@davidopp   test  this, please,  fix #25606, thanks.

**Comment by davidopp** [comment]
ok to test

**Comment by ping035627** [comment]
@davidopp  need  ok-to-merge label, thanks

**Comment by ping035627** [comment]
@wojtek-t  need ok-to-merge label, can help? thanks

**Comment by ping035627** [comment]
@davidopp  Fix #25606, and now all test passed, can this merge? thanks.

**Comment by davidopp** [comment]
LGTM

**Comment by ping035627** [comment]
@davidopp The Gce e2e test is passed before, but now "1 failed". The change should' t cause the result. help, thanks!

The information:
Dumping master and node logs to /var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace@2/_artifacts
scp: /var/log/cluster-autoscaler.log: No such file or directory
scp: /var/log/kern.log: No such file or directory
scp: /var/log/startupscript.log: No such file or directory
ERROR: (gcloud.compute.copy-files) [/usr/bin/scp] exited with return code [1]. See https://cloud.google.com/compute/docs/troubleshooting#ssherrors for troubleshooting hints.

Summarizing 1 Failure:

[Fail] [k8s.io] Proxy version v1 [It] should proxy through a service and a pod [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/proxy.go:258

Ran 184 of 313 Specs in 974.458 seconds
FAIL! -- 183 Passed | 1 Failed | 0 Pending | 129 Skipped 

proxy.go:258
		if len(errs) != 0 {
			body, err := f.Client.Pods(f.Namespace.Name).GetLogs(pods[0].Name, &api.PodLogOptions{}).Do().Raw()
			if err != nil {
				framework.Logf("Error getting logs for pod %s: %v", pods[0].Name, err)
			} else {
				framework.Logf("Pod %s has the following error logs: %s", pods[0].Name, body)
			}

			Fail(strings.Join(errs, "\n"))    //this is 258
		}

**Comment by ping035627** [comment]
Milestone is for a future release and cannot be merged？

**Comment by davidopp** [comment]
Yes, we are still in the "code freeze" for 1.3 release. Once that is over (should be within a week or so), we will start accepting regular PRs again.

**Pull request merged**
