### PR TITLE
Temporary fix for alpha features test

### PR DESCRIPTION
**Pull request by jennybuckley**
**What type of PR is this?**
/kind failing-test
/sig api-machinery
/priority important-soon
/test pull-kubernetes-e2e-gce-alpha-features
cc @apelisse @lavalamp @kwiesmueller 

**What this PR does / why we need it**:
This is to fix the alpha test suite, until we can update the kube-openapi vendor version, https://github.com/kubernetes/kubernetes/pull/73756

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by jennybuckley** [comment]
It looks like this PR does fix [pull-kubernetes-e2e-gce-alpha-features](https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/73763/pull-kubernetes-e2e-gce-alpha-features/86/)

**Comment by dims** [comment]
applied `cncf-cla:yes`  label by hand

**Pull request merged**
