### PR TITLE
Use Fatalf instead of Fatal while formatting the output is needed

### PR DESCRIPTION
**Pull request by YuxiJin-tobeyjin**
**What this PR does / why we need it**:
Should use Fatalf instead of Fatal while formatting the output is needed

**Release note**:
NONE 

```release-note
```

### CODE REVIEW

**Comment by YuxiJin-tobeyjin** [comment]
ping@timothysc PTAL

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Comment by YuxiJin-tobeyjin** [comment]
@timothysc 
As there is no issue related，would you please approve with /approve no-issue,sir?
Many thanks. ^v^

**Comment by YuxiJin-tobeyjin** [comment]
ping @timothysc

**Comment by YuxiJin-tobeyjin** [comment]
ping @timothysc

**Comment by YuxiJin-tobeyjin** [comment]
ping @timothysc

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Comment by YuxiJin-tobeyjin** [comment]
ping @timothysc 
Could you please "/approve no-issue",thanks.

**Comment by YuxiJin-tobeyjin** [comment]
ping @timothysc
Could you please "/approve no-issue",thanks.

**Comment by YuxiJin-tobeyjin** [comment]
ping @timothysc
Could you please "/approve no-issue",thanks,please.

**Comment by YuxiJin-tobeyjin** [comment]
ping @timothysc
Could you please "/approve no-issue".
Thanks,please.

**Comment by YuxiJin-tobeyjin** [comment]
ping @timothysc
Could you please "/approve no-issue".
Thanks,please.

**Comment by YuxiJin-tobeyjin** [comment]
@timothysc Would you please use "/approve no-issue". Thanks.

**Comment by YuxiJin-tobeyjin** [comment]
@timothysc Could you please use "/approve no-issue". Thanks.

**Comment by YuxiJin-tobeyjin** [comment]
@timothysc Could you please use "/approve no-issue". Thanks.

**Comment by YuxiJin-tobeyjin** [comment]
ping @timothysc PTAL sir

**Comment by YuxiJin-tobeyjin** [comment]
@timothysc Could you please "/approve no-issue". Thanks.

**Comment by YuxiJin-tobeyjin** [comment]
ping @timothysc

**Comment by YuxiJin-tobeyjin** [comment]
ping @madhusudancs PTAL

**Comment by YuxiJin-tobeyjin** [comment]
ping @hongchaodeng PTAL

**Comment by YuxiJin-tobeyjin** [comment]
ping @hongchaodeng PTAL

**Pull request merged**
