### PR TITLE
Parametrize KubeDNS ndots

### PR DESCRIPTION
**Pull request by bogdando**
Add ndots (defaults to a 5) as:
- DNSNdots(json dnsNdots) to kubeadmapi and --service-dns-ndots to
  kubeadm flags
- ClusterDNSNdots(json clusterDNSNdots) to kube APIs
- --cluster-dns-ndots to kubelet flags and its templates everywhere
- dns_ndots/DNS_NDOTS for pillar and cluster's addons, templating,
  examples, hack and zillion places like gce, mesos, openstack,
  vmware, rackspace, hazelcast, photon etc.
  Add e2e conformance for cluster-dns-ndots

Fixes https://github.com/kubernetes/kubernetes/issues/33554

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35525)

### CODE REVIEW

**Comment by bogdando** [comment]
This is not for merge, yet. Please review this very carefully, it affects all cluster addons by adding new var to define ndots:5 (although it must change nothing for them as the default value matches the current hardcoded value)

**Comment by bogdando** [comment]
`./build/run.sh make cross` works for me, and I can build hyperkube and kubeadm. Kubelet invoked from the kube, has the ndots param (--cluster-dns-ndots). The `kubeadm init --help` contains is as --service-dns-ndots as well.  Not sure how could I verify the rest of the changes of the patch, removing WIP. Feel free to finish review/testing and merge perhaps!

**Comment by bogdando** [comment]
@MrHohn @macb @thockin

**Comment by thockin** [comment]
I am still not convinced that this is the right thing to do.  Any cluster with this changed will, for example, not work with all of the published examples, all over the web.  That aside, I don't know that this is the right way to go about it, anyway.  Why not make it a different DNSPolicy or a DNS AdmissionController?

**Comment by macb** [comment]
One problem I see with a `DNSPolicy` is someone may want to use ndots 1 but I want to use ndots 2. So now we need 2 more `DNSPolicy`s.

I think I'm ok with a documented configuration breaking examples. This doesn't seem like a knob everyone will reach for and those that do should be informed enough on what it does (and the side effects wrt how different applications may react).

Using a different `DNSPolicy` breaks a lot of examples as well doesn't it?

**Comment by thockin** [comment]
DNSPolicy could come with additional parameters, e.g. a sibling field
per-pod to set ndots.

Setting it globally means ALL your users are opted in.  Also, we have too
many flags as it is.  Flags are the most clumsy way to do something like
this (as you can see with the salt mess).

Other ways to achieve something like this:
* `dnsPolicy: ClusterFirst_ndots1` (hacky)
* new field `dnsOptions: ndots:1`, user-defined
* change the meaning of ClusterFirst to look for a ConfigMap before
hardcoded defaults
* same as above but with an admission controller
* admission controller which reads a ConfigMap and applies DNS policy from
that
* a new API kind for DNSPolicy

**Comment by bogdando** [comment]
While flags may be clumsy, they are simple and straightforward to use:
- See help
- Run with a flag needed
- ???
- Profit!

Changes to API plus DNSPolicy or adding ConfigMaps to be moving parts looks like an unneeded added complexity and seems over-engineering to me

**Comment by fluxrad** [comment]
It appears this problem is also solvable with a `configMap`. You can use the `subPath` volume option to override a specific file. In this case `/etc/resolv.conf` (It's worth noting the subPath documentation doesn't exist in the docs on kubernetes.io. I found it in a GitHub issue).

#### Config

This is the `/etc/resolv.conf` generated by minikube, but with `ndots: 5` removed.

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: resolvconf
  namespace: default
data:
  resolv.conf: |
    search default.svc.cluster.local svc.cluster.local cluster.local
    nameserver 10.0.0.10

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: dns-test
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dns-test
    spec:
      containers:
        - name: dns-test
          image: ubuntu:xenial
          volumeMounts:
            - name: resolv-conf
              mountPath: /etc/resolv.conf
              subPath: resolv.conf
          args:
            - "sleep"
            - "3600"
      volumes:
        - name: resolv-conf
          configMap:
            name: resolvconf
            items:
            - key: resolv.conf
              path: resolv.conf
```

#### Validate:

```
$ k exec -it dns-test-1952153205-9g9t2 -- nslookup -debug kubernetes.io
Server:         10.0.0.10
Address:        10.0.0.10#53

------------
    QUESTIONS:
        kubernetes.io, type = A, class = IN
    ANSWERS:
    ->  kubernetes.io
        internet address = 192.30.252.153
        ttl = 17474
    ->  kubernetes.io
        internet address = 192.30.252.154
        ttl = 17474
    AUTHORITY RECORDS:
    ADDITIONAL RECORDS:
------------
Non-authoritative answer:
Name:   kubernetes.io
Address: 192.30.252.153
Name:   kubernetes.io
Address: 192.30.252.154
```

**Comment by bogdando** [comment]
Folks, If you think the subPath trick is good to go, feel free to close this

**Comment by macb** [comment]
While the configmap change can work it's a bit of a hack imo since it's circumventing the intention of the `dnsPolicy`.

**Comment by kcrawley** [comment]
Is this being revisited in a different PR/issue? Manually applying a `resolv.conf` through a volume is not a viable solution to this issue. (even if it _technically_ does work).

**Comment by bowei** [comment]
@kcrawley -- I am working on a proposal for better configurability of kube-dns in the cluster

**Comment by zihaoyu** [comment]
@bowei when it's done could you post a link to it in this thread? It will be helpful pointing people to the right direction.

**Pull request closed without merging**
