### PR TITLE
Automated cherry pick of #74301: do not return error on invalid mac address in vsphere cloud

### PR DESCRIPTION
**Pull request by andrewsykim**
Cherry pick of #74301 on release-1.12.

#74301: do not return error on invalid mac address in vsphere cloud

### CODE REVIEW

**Comment by andrewsykim** [comment]
/assign @feiskyer

PTAL, this is another patch needed in relation to #73721 & #74082. Sorry for the trouble with so many PRs, much appreciated!

**Comment by feiskyer** [comment]
Could you also add a release note in the original PR?

**Review by dougm — COMMENTED** [review]
/lgtm

**Comment by andrewsykim** [comment]
/release-note-none

We intentionally left release note out for this because it should fall under the original cherry-pick PR

**Pull request merged**
