### PR TITLE
Update podFailurePolicy comment from alpha-level to beta

### PR DESCRIPTION
**Pull request by mimowo**
/sig apps
/wg batch

#### What type of PR is this?

/kind bug
/kind documentation

#### What this PR does / why we need it:

podFailurePolicy is beta now.

#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:

Comments were updated before in this PR: https://github.com/kubernetes/kubernetes/pull/117802, but didn't cover this place.

#### Does this PR introduce a user-facing change?

```release-note
Update the comment about the feature-gate level for PodFailurePolicy from alpha to beta
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by soltysh — COMMENTED** [review]
/lgtm
/triage accepted
/priority backlog

**Comment by alculquicondor** [comment]
/label api-review

although this file is less priority, as it's the internal types.

**Pull request merged**
