### PR TITLE
dependencies: update otel-go dependencies

### PR DESCRIPTION
**Pull request by howardjohn**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
The current set uses an awkward mix of otel-go libraries (caused by the upstream doing the same!!), where we have `go.opentelemetry.io/otel v1.10.0` but `go.opentelemetry.io/otel/metric v0.31.0`. This makes it pretty hard to import anything under this repo that uses these metrics, and a reasonably modern otel-go metrics library.

Note this is not from importing k/k directly or anything. `controller-runtime` as of v0.16.0 transitively imports these, meaning anyone with controller-runtime cannot have a new CR version and a new otel-go version.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
what interesting result, lots of jobs are flaking with this PR

**Comment by bart0sh** [comment]
@howardjohn please rebase and fix CI test failures, thanks.
/cc

**Comment by howardjohn** [comment]
Probably blocked by https://github.com/kubernetes/kubernetes/pull/119865

**Comment by KastenMike** [comment]
> Probably blocked by #119865

Would it be? It seems it just updates the same library to the same version as here. So this merging first would make the other pointless only rather than depending on it

**Comment by howardjohn** [comment]
> > Probably blocked by #119865
> 
> Would it be? It seems it just updates the same library to the same version as here. So this merging first would make the other pointless only rather than depending on it

That is true, but I also couldn't figure out the fixes that PR adds :-) so I could just copy+paste them but seems better to let that work

**Comment by KastenMike** [comment]
https://github.com/kubernetes/kubernetes/pull/119865 is merged 👍

**Comment by dashpole** [comment]
Should we bump to otel-go 1.19 now?  I'm also happy with this bump if something is blocking that.

**Comment by howardjohn** [comment]
> Should we bump to otel-go 1.19 now? I'm also happy with this bump if something is blocking that.

Good call, let me see if it causes any issues

**Comment by howardjohn** [comment]
> Should we bump to otel-go 1.19 now? I'm also happy with this bump if something is blocking that.

Just tried and it updates go/compute module which pulls in some "unwanted dependencies". I asked on slack how to deal with it, but for now just reverted to the older version. I can update if we have a resolution for that.

**Comment by dashpole** [comment]
```
    tracing_test.go:854: Timed out waiting for trace
    --- FAIL: TestAPIServerTracing/create_node (30.00s)
```

Seems like something broke the trace integration tests.  I'll take a look.

**Comment by dashpole** [comment]
It looks like the http.target attribute was removed in https://github.com/open-telemetry/opentelemetry-go-contrib/issues/3743.  I'm looking for workarounds

**Comment by dashpole** [comment]
I found a workaround: https://github.com/kubernetes/kubernetes/compare/master...dashpole:kubernetes:update_otel_deps. See traces.go and utils.go

**Comment by howardjohn** [comment]
https://github.com/kubernetes/kubernetes/pull/121111/files handles this. Thanks!

**Pull request closed without merging**
