### PR TITLE
Default HTTP2 on, post fixes from #29001

### PR DESCRIPTION
**Pull request by timothysc**
This reverts commit 8cb799c7897c029863cd9051b8e033991d29fe88.

Enables HTTP2 on by default post fixes from https://github.com/kubernetes/kubernetes/issues/29001 for 1.5 

NOTE:  We are nearing lb connection limits at current thresholds. 

/cc @bradfitz @lavalamp @smarterclayton

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32231)

### CODE REVIEW

**Comment by krousey** [comment]
Remind me what this broke last time and why it's ok now.

**Comment by timothysc** [comment]
@krousey https://github.com/kubernetes/kubernetes/issues/29001 has the gory history.  

We will likely want to loop in @gmarek before we flip this switch too.  

We're starting to enter into hard constraints due to the 1.5 goals of 5k nodes.  Without this, we're simply going to start running out of ports.

**Comment by krousey** [comment]
This looks fine to me. I'll leave it to @gmarek for the final OK.

**Comment by gmarek** [comment]
@timothysc - how urgent it is? We're running last scalability tests on master, so I'd rather wait a day or two until we're finished. Then we'll give it a try and see what happens.

**Comment by timothysc** [comment]
@gmarek no rush.. hoping to flush out for 1.5

**Comment by wojtek-t** [comment]
@timothysc - I'm fine with it, but please wait until 1.4 is out. Let's merge it next week.

**Comment by timothysc** [comment]
sgtm.

**Comment by timothysc** [comment]
So were all branched, unless someone objects I was going to apply today.

**Comment by smarterclayton** [comment]
We have the TLS `.NextProtos = ["h2"]` thing right?

**Comment by timothysc** [comment]
@smarterclayton not yet.  I suppose we should block on https://github.com/kubernetes/kubernetes/pull/28742 then.

**Comment by smarterclayton** [comment]
Can we not set that field also on Go 1.6?  I thought it worked on both
versions, but was required for client cert on 1.7?

**Comment by bradfitz** [comment]
You can set it on 1.6 too.

**Comment by timothysc** [comment]
i'll update the pr.

**Comment by gmarek** [comment]
@timothysc - we can merge this now, ping me when you'll update it for 1.6.

**Comment by timothysc** [comment]
@gmarek ready.

**Comment by gmarek** [comment]
LGTM

FYI @thockin

**Pull request merged**
