### PR TITLE
Automated cherry pick of #94936: Return the Kubernetes version which stopped serving

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #94936 on release-1.19.

#94936: Return the Kubernetes version which stopped serving

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Review by errordeveloper — APPROVED** [review]
/lgtm

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
from parent PR
/release-note-none

**Pull request merged**
