### PR TITLE
Automated cherry pick of #76974: Restrict builds to officially supported platforms

### PR DESCRIPTION
**Pull request by mtaufen**
Cherry pick of #76974 on release-1.14.

#76974: Restrict builds to officially supported platforms

```release-note
NONE
```

### CODE REVIEW

**Comment by mtaufen** [comment]
This fixes a critical bug that breaks certain release workflows that try to build Linux and Windows binaries, but not build every supported arch.

**Comment by mtaufen** [comment]
/assign @hoegaarden @aleksandra-malinowska @tpepper 
Can one of you please approve?

/cc @thockin @yujuhong

**Comment by mtaufen** [comment]
Filed a bug for the godeps test: https://github.com/kubernetes/kubernetes/issues/77238

**Comment by mtaufen** [comment]
/retest
godeps test should be fixed now

**Comment by hoegaarden** [comment]
@mtaufen 

> Can one of you please approve the cherry-pick?

The cherrypick needs to be [approved by one of the `/hack` approvers](https://github.com/kubernetes/community/blame/488a921b57fcfd1c0782492ca3dcbc1a79b0b91a/contributors/devel/sig-release/cherry-picks.md#L39).

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by yujuhong** [comment]
/assign @tpepper @aleksandra-malinowska
for cherrypick approval

**Comment by yujuhong** [comment]
Ping! 1.14 patch managers, could you take a look at this PR? Thanks!

**Pull request merged**
