### PR TITLE
Upgrade Stackdriver Logging Agent addon image to 0.6-1.6.0-1 to use Fluentd v1.2.

### PR DESCRIPTION
**Pull request by qingling128**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
/kind feature
> /kind flake

**What this PR does / why we need it**:
Upgrade Stackdriver Logging Agent addon image to 0.6-1.6.0-1 to use Fluentd v1.2.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Upgrade Stackdriver Logging Agent addon image to 0.6-1.6.0-1 to use Fluentd v1.2. This provides nanoseconds timestamp granularity for logs.
```

### CODE REVIEW

**Comment by qingling128** [comment]
@x13n - Any chance you could help with the `Must be in milestone v1.13.` blocker?

**Comment by x13n** [comment]
I cannot add this to the milestone myself. Also, note that you still need cluster/gce/OWNERS approval.

@AishSundar Is it possible to add this PR to 1.13 milestone, given that change is GCP-specific and doesn't affect non-GCP code?

**Comment by qingling128** [comment]
Could someone (from cluster/gce/OWNERS) help take a look at this PR? @vishh @MaciekPytel

**Comment by qingling128** [comment]
Friendly ping.
@AishSundar @vishh @MaciekPytel

**Pull request merged**
