### PR TITLE
Fix resource metrics e2e test

### LINKED ISSUE #103428: ResourceMetricsAPI failing on containerd and cri-o
#### Which jobs are failing:
https://testgrid.k8s.io/sig-node-containerd#containerd-node-features (containerd)
https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-features (crio)

#### Which test(s) are failing:
[sig-node] ResourceMetricsAPI [NodeFeature:ResourceMetrics] when querying /resource/metrics should report resource usage through the resource metrics api

#### Since when has it been failing:
Ever since this commit was merged https://github.com/kubernetes/kubernetes/pull/102444

#### Testgrid link:
https://testgrid.k8s.io/sig-node-containerd#containerd-node-features (containerd)
https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-features (crio)

#### Reason for failure:
We need to see what the commit is breaking this particular NodeFeatures test on both crio and containerd.

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

Fixes the broken resource metrics node feature test.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/103428

#### Special notes for your reviewer:

Refers to https://github.com/kubernetes/kubernetes/pull/102444

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Is there any way to trigger node features e2e test from a PR? I can't find a target executing these tests.

**Comment by saschagrunert** [comment]
Half of the issue is fixed, while we still see:

```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/resource_metrics_test.go:66
Timed out after 60.000s.
Expected
    <string>: KubeletMetrics
to match keys: {
[."container_start_time_seconds"[resource-metrics-1693::stats-busybox-0::busybox-container]:
	Expected
	    <string>: Sample
	to match fields: {
	.Timestamp:
		Expected
		    <time.Time>: 1970-01-01T00:00:00Z
		to be >=
		    <time.Time>: 2021-07-02T10:55:00.692760705Z
	}
	, ."container_start_time_seconds"[resource-metrics-1693::stats-busybox-1::busybox-container]:
	Expected
	    <string>: Sample
	to match fields: {
	.Timestamp:
		Expected
		    <time.Time>: 1970-01-01T00:00:00Z
		to be >=
		    <time.Time>: 2021-07-02T10:55:00.692763081Z
	}
	]
}
```

**Comment by saschagrunert** [comment]
For the record, the issue still persists:
```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/resource_metrics_test.go:66
Timed out after 60.003s.
Expected
    <string>: KubeletMetrics
to match keys: {
[."container_start_time_seconds"[resource-metrics-3667::stats-busybox-0::busybox-container]:
	Expected
	    <string>: Sample
	to match fields: {
	.Timestamp:
		Expected
		    <time.Time>: 1970-01-01T00:00:00Z
		to be >=
		    <time.Time>: 2021-07-02T12:10:13.662376032Z
	}
	, ."container_start_time_seconds"[resource-metrics-3667::stats-busybox-1::busybox-container]:
	Expected
	    <string>: Sample
	to match fields: {
	.Timestamp:
		Expected
		    <time.Time>: 1970-01-01T00:00:00Z
		to be >=
		    <time.Time>: 2021-07-02T12:10:13.662378585Z
	}
	]
}
```
cc @sanwishe

**Comment by sanwishe** [comment]
> For the record, the issue still persists:
> 
> ```
> _output/local/go/src/k8s.io/kubernetes/test/e2e_node/resource_metrics_test.go:66
> Timed out after 60.003s.
> Expected
>     <string>: KubeletMetrics
> to match keys: {
> [."container_start_time_seconds"[resource-metrics-3667::stats-busybox-0::busybox-container]:
> 	Expected
> 	    <string>: Sample
> 	to match fields: {
> 	.Timestamp:
> 		Expected
> 		    <time.Time>: 1970-01-01T00:00:00Z
> 		to be >=
> 		    <time.Time>: 2021-07-02T12:10:13.662376032Z
> 	}
> 	, ."container_start_time_seconds"[resource-metrics-3667::stats-busybox-1::busybox-container]:
> 	Expected
> 	    <string>: Sample
> 	to match fields: {
> 	.Timestamp:
> 		Expected
> 		    <time.Time>: 1970-01-01T00:00:00Z
> 		to be >=
> 		    <time.Time>: 2021-07-02T12:10:13.662378585Z
> 	}
> 	]
> }
> ```
> 
> cc @sanwishe

I'm terribly sorry for introducing this, and still working to find out what happened under containerd and cri-o.

**Comment by fuweid** [comment]
https://github.com/kubernetes/kubernetes/pull/102444/files#r663449796 

cc @saschagrunert and @sanwishe

**Comment by saschagrunert** [comment]
> The metric doesn't have timestamp so that the matcher show epoch. Should use metrics.NewLazyMetricWithTimestamp for container_start_tkme_seconds

Thank you for the hint, let me give it a try.

/test pull-kubernetes-node-crio-e2e

**Comment by saschagrunert** [comment]
The test is now green: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/103429/pull-kubernetes-node-crio-e2e/1411945586160046080/

**Comment by saschagrunert** [comment]
Okay I'm not sure if that's the metrics output we really want:
```
  # HELP container_cpu_usage_seconds_total [ALPHA] Cumulative cpu time consumed by the container in core-seconds
        # TYPE container_cpu_usage_seconds_total counter
        container_cpu_usage_seconds_total{container="container_a",namespace="namespace_a",pod="pod_a"} 10 1624396278302
        container_cpu_usage_seconds_total{container="container_a",namespace="namespace_b",pod="pod_b"} 10 1624396278302
        container_cpu_usage_seconds_total{container="container_b",namespace="namespace_a",pod="pod_a"} 10 1624396278302
        # HELP container_memory_working_set_bytes [ALPHA] Current working set of the container in bytes
        # TYPE container_memory_working_set_bytes gauge
        container_memory_working_set_bytes{container="container_a",namespace="namespace_a",pod="pod_a"} 1000 1624396278302
        container_memory_working_set_bytes{container="container_a",namespace="namespace_b",pod="pod_b"} 1000 1624396278302
        container_memory_working_set_bytes{container="container_b",namespace="namespace_a",pod="pod_a"} 1000 1624396278302
        # HELP container_start_time_seconds [ALPHA] Start time of the container since unix epoch in seconds
        # TYPE container_start_time_seconds gauge
        container_start_time_seconds{container="container_a",namespace="namespace_a",pod="pod_a"} 1.6243962483020916e+09
        container_start_time_seconds{container="container_a",namespace="namespace_b",pod="pod_b"} 1.6243956783020916e+09
        container_start_time_seconds{container="container_b",namespace="namespace_a",pod="pod_a"} 1.6243961583020916e+09
        # HELP scrape_error [ALPHA] 1 if there was an error while getting container metrics, 0 otherwise
        # TYPE scrape_error gauge
        scrape_error 0
        
        got:
        
        # HELP container_cpu_usage_seconds_total [ALPHA] Cumulative cpu time consumed by the container in core-seconds
        # TYPE container_cpu_usage_seconds_total counter
        container_cpu_usage_seconds_total{container="container_a",namespace="namespace_a",pod="pod_a"} 10 1624396278302
        container_cpu_usage_seconds_total{container="container_a",namespace="namespace_b",pod="pod_b"} 10 1624396278302
        container_cpu_usage_seconds_total{container="container_b",namespace="namespace_a",pod="pod_a"} 10 1624396278302
        # HELP container_memory_working_set_bytes [ALPHA] Current working set of the container in bytes
        # TYPE container_memory_working_set_bytes gauge
        container_memory_working_set_bytes{container="container_a",namespace="namespace_a",pod="pod_a"} 1000 1624396278302
        container_memory_working_set_bytes{container="container_a",namespace="namespace_b",pod="pod_b"} 1000 1624396278302
        container_memory_working_set_bytes{container="container_b",namespace="namespace_a",pod="pod_a"} 1000 1624396278302
        # HELP container_start_time_seconds [ALPHA] Start time of the container since unix epoch in seconds
        # TYPE container_start_time_seconds gauge
        container_start_time_seconds{container="container_a",namespace="namespace_a",pod="pod_a"} 1.624396248e+09 1624396248302
        container_start_time_seconds{container="container_a",namespace="namespace_b",pod="pod_b"} 1.624395678e+09 1624395678302
        container_start_time_seconds{container="container_b",namespace="namespace_a",pod="pod_a"} 1.624396158e+09 1624396158302
        # HELP scrape_error [ALPHA] 1 if there was an error while getting container metrics, 0 otherwise
        # TYPE scrape_error gauge
        scrape_error 0
```

**Review by fuweid — APPROVED** [review]
LGTM（nb）

**Comment by saschagrunert** [comment]
/priority critical-urgent
since it break existing e2e tests

**Comment by ehashman** [comment]
/test pull-kubernetes-node-crio-e2e
/test pull-kubernetes-node-kubelet-swap-ubuntu

couldn't find an equivalent presubmit for containerd so trying the swap on Ubuntu job which selects on NodeFeature ^ https://github.com/kubernetes/test-infra/blob/b56e4cfd375c106cb6160ae549a2d5fb35a5d8db/config/jobs/kubernetes/sig-node/sig-node-presubmit.yaml#L600

**Comment by ehashman** [comment]
beforesuite on test looks broken, I'll file a bug

/skip

**Comment by saschagrunert** [comment]
> /test pull-kubernetes-node-crio-e2e

Is still green: https://prow.k8s.io/?pull=103429&job=pull-kubernetes-node-crio-e2e

**Comment by dashpole** [comment]
Can you provide more detail about why this fixes the failure?  The linked issue is closed without any comments about why it is failing

**Comment by fuweid** [comment]
> Can you provide more detail about why this fixes the failure?  The linked issue is closed without any comments about why it is failing

The boundedSample will check the metric exported timestamp but the container_start_tkme_seconds was exported with timestamp

**Comment by fuweid** [comment]
can we merge this patch? A lot of containerd pull requestes has been blocked by this issue. Thanks!

**Review by yangjunmyfm192085 — COMMENTED** [review]
/assign @mrunalp

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/103429#issuecomment-875599088

it would be helpful to add a note like this to any of:
- the commit
- the PR body
- the code

github comments down the thread get hidden as the thread expands, making it harder for approvers to find or future folks to understand why this change was previously made

**Review by mrunalp — APPROVED** [review]

**Comment by BenTheElder** [comment]
/retest
https://github.com/kubernetes/kubernetes/issues/103512

**Comment by BenTheElder** [comment]
/retest
#103512

**Pull request merged**
