### PR TITLE
[Kubemark] Add init container in hollow node for setting inotify limit of node to 200

### LINKED ISSUE #41713: kubemark is still failing.
The PR https://github.com/kubernetes/kubernetes/pull/41703 fixed hollow npd. Now hollow npd can work properly. However, I found that npd can't update node condition, and keep reporting error:
```
E0219 10:05:23.100125       1 manager.go:160] failed to update node conditions: nodes "hollow-node-w9fkf" not found
```
The reason is that hollow kubelet never registers the node.

I checked the hollow kubelet. Most of them are empty, but in some of them I saw tons of the following log:
```
0219 09:59:54.303624       9 file.go:72] unable to read config path "/tmp/hollow-kubelet.037396831/manifest013003570": unable to create i
notify: inotify_init: too many open files
```

BTW, we really need hollow node log. I can't reproduce this in my own kubemark cluster, I can only wait for the kubemark test running, and login into the running node to get some debug information.

/cc @shyamjvs @wojtek-t @gmarek

### PR DESCRIPTION
**Pull request by shyamjvs**
Fixes #41713 

Along with adding the init container, I also changed the manifest to a yaml as otherwise the entire init container annotation would have to be in a single line (with escaped characters), as json doesn't allow multi-line strings.

cc @kubernetes/sig-scalability-misc @wojtek-t @gmarek @Random-Liu

### CODE REVIEW

**Comment by Random-Liu** [comment]
LGTM @shyamjvs Thanks for the change!

**Comment by shyamjvs** [comment]
Adding lgtm label based on the above comments.

**Comment by Random-Liu** [comment]
Mark v1.6 because:
* This is test only change.
* This is needed for NPD scalability verification.

**Comment by Random-Liu** [comment]
@shyamjvs I checked an existing kubemark cluster. The inotify limit is not changed:
```
lantaol@kubemark-500-minion-group-6vhf ~ $ sudo sysctl -a | grep inotify
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 128
fs.inotify.max_user_watches = 8192
```

**Comment by Random-Liu** [comment]
NVM, it works now. I think the previous cluster didn't include this change.

**Pull request merged**
