### PR TITLE
pkg/storage: fix sort.Search (bst on sorted)

### PR DESCRIPTION
**Pull request by gyuho**
[Analytics]()

https://golang.org/pkg/sort/#Search 

Go's sort.Search does binary search tree, but current code does binary search on un-sorted slice.
If the slice is not sorted, the binary search won't work.

In the test cache:

```
{resourceVersion:4 watchCacheEvent:{Type:ADDED Object:0xc8202e6c80 PrevObject:<nil> ResourceVersion:4}}
{resourceVersion:3 watchCacheEvent:{Type:ADDED Object:0xc8202e6f00 PrevObject:<nil> ResourceVersion:3}}
{resourceVersion:2 watchCacheEvent:{Type:ADDED Object:0xc8202e7180 PrevObject:<nil> ResourceVersion:2}}
{resourceVersion:1 watchCacheEvent:{Type:ADDED Object:0xc8202e7400 PrevObject:<nil> ResourceVersion:1}}
{resourceVersion:0 watchCacheEvent:{Type:ADDED Object:0xc8202e7680 PrevObject:<nil> ResourceVersion:0}}
```

Without sort, target resourceVersion 1, find the next smallest next resource version:

```
{Type:ADDED Object:kind:"" apiVersion:""  PrevObject:<nil> ResourceVersion:4}
{Type:ADDED Object:kind:"" apiVersion:""  PrevObject:<nil> ResourceVersion:3}
{Type:ADDED Object:kind:"" apiVersion:""  PrevObject:<nil> ResourceVersion:2}
{Type:ADDED Object:kind:"" apiVersion:""  PrevObject:<nil> ResourceVersion:1}
{Type:ADDED Object:kind:"" apiVersion:""  PrevObject:<nil> ResourceVersion:0}
```

It returns all. This seems wrong. It should only return 2,3,4.

With sort:

```
{Type:ADDED Object:kind:"" apiVersion:""  PrevObject:<nil> ResourceVersion:2}
{Type:ADDED Object:kind:"" apiVersion:""  PrevObject:<nil> ResourceVersion:3}
{Type:ADDED Object:kind:"" apiVersion:""  PrevObject:<nil> ResourceVersion:4}
```

### CODE REVIEW

**Comment by gyuho** [comment]
/cc @xiang90 @hongchaodeng I am not familiar with this package. So if my approach is wrong, please feel free to close it.

Thanks.

**Comment by xiang90** [comment]
the items in watchCache should be ordered already. we need to make that more clear though. the current comment only says the first one has the smallest index.

**Comment by gyuho** [comment]
Right, I just saw that `cache` comment:

> its first element (with the smallest `resourceVersion`)

Maybe just document something like:

> `its first element must have smallest index`

So Kubernetes never writes to cache in reverse order?
Maybe this is not needed then since it's already documented as above.

Thanks.

**Comment by lavalamp** [comment]
I believe this is kept in sorted state, and if not, that would be the desired fix. @wojtek-t can reopen if I'm mistaken. Thanks @gyuho for looking.

**Comment by gyuho** [comment]
Thanks!

**Comment by wojtek-t** [comment]
Yes - it's already sorted right now. I will send a PR to update the comment.

**Pull request closed without merging**
