### PR TITLE
Fix parallel image pullers event messages with reasons constants.

### PR DESCRIPTION
**Pull request by aveshagarwal**

### CODE REVIEW

**Comment by bgrant0607** [comment]
Reassigned to @dchen1107 for delegation.

**Comment by aveshagarwal** [comment]
Rebased.

**Comment by aveshagarwal** [comment]
Rebased.

**Comment by fejta** [comment]
Can someone on node to look at this?

**Comment by vishh** [comment]
LGTM. Thanks for the cleanup @aveshagarwal

**Pull request merged**
