### PR TITLE
Don't pull flannel from github

### PR DESCRIPTION
**Pull request by bprashanth**

### CODE REVIEW

**Comment by imesh** [comment]
@bprashanth What would be the reason for this change?

**Comment by bprashanth** [comment]
@imesh so we don't pull flannel from github, which 500s from time to time. It's also not polite to hammer github, cloud object stores are designed for exactly this.

**Comment by thockin** [comment]
I assume you already pushed this up?

**Comment by bprashanth** [comment]
> I assume you already pushed this up?

Yes pushed

**Pull request merged**
