### PR TITLE
clean unused function in file pkg/volume/projected/projected.go

### PR DESCRIPTION
**Pull request by WanLinghao**
**What this PR does / why we need it**:
It was imported by https://github.com/kubernetes/kubernetes/pull/37237
And it is unusable at first place when it was imported
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by WanLinghao** [comment]
@rootfs PTAL

**Comment by WanLinghao** [comment]
@saad-ali PTAL thanks~

**Comment by WanLinghao** [comment]
@matchstick PTAL

**Review by saad-ali — APPROVED** [review]

**Pull request merged**
