### PR TITLE
Create a generic interface from kubelet to cadvisor

### PR DESCRIPTION
**Pull request by huang195**
This is to implement the issue discussed in #18769. In summary, a generic collector interface has been implemented, so kubelet can use tools other than cadvisor to collect node and container information. Two additional flags are introduced: `--collector` and `--collector-url`. By default `--collector=cadvisor` and `--collector-url=4194`, and this will have the same behavior as before, where kubelet will start a local cadvisor process that listens to port 4194. Alternatively, one can specify  `--collector=cadvisor` and `--collector-url=http://localhost:43210`, in which case, we're telling kubelet to not start the builtin cadvisor process, but rather it should connect to an existing cadvisor that listens at http://localhost:43210. 

Currently, there are only 2 drivers created behind this generic interfaces, and both are cadvisor drivers. One is the builtin cadvisor driver, and the other ones communicates with a cadvisor process 
via its REST APIs.

I haven't touched upon separating core metrics vs. non-essential in the generic interface. This PR retains the same functionality as before, but allows developers to write additional drivers to hook up kubelet with other monitoring tools. In issue #18770 where it is proposed to have cadvisor running in its own pod, this PR will allow kubelet to communicate with that cadvisor process the same way it communicates with a builtin one.

### CODE REVIEW

**Comment by huang195** [comment]
cc: @yujuhong @vishh @dchen1107 @timstclair ptal

**Comment by vishh** [comment]
@huang195: Can you explain why the existing cAdvisor interface doesn't satisfy your use case? Are you trying to avoid re-using cAdvisor structs inside of kubelet?

**Comment by vishh** [comment]
cc @timstclair

**Comment by huang195** [comment]
@vishh My thought is the interface should be generic and not tied to a particular tool, so kubelet can use monitoring tools other than cadvisor to collect node and container information. I only implemented 2 cadvisor drivers so far, so it might look like not re-using cadvisor structs over complicates the problem. But the goal is to cater kubernetes to any monitoring tool that implements this generic interface.

**Comment by vishh** [comment]
@huang195: Take a look at #18770. The goal is not to make metrics providers pluggable, instead have a single metrics core in kubelet for its functionality and separate out monitoring. 
I don't see a reason for making the core metrics that are needed for kubelet pluggable.

**Comment by huang195** [comment]
@vishh I'm not sure I understand what would be the benefit of not making it pluggable. By default, the bundled cadvisor is used to collect the information. For new users, that's a big plus as Kubernetes works out of the box. But as folks are standing up their own production environments, they have different requirements and preferences. Why not give them the choice?

**Comment by vishh** [comment]
Monitoring will be pluggable. But core metrics will not be pluggable.
Kubelet will be self-sufficient and not force everybody to use cAdvisor for
monitoring.

**Comment by huang195** [comment]
@vishh IMO, making the core metrics pluggable does not make Kubelet any less self-sufficient than what it is today. The benefit is one can have a choice to choose whatever tool he prefers for his environment rather than getting locked in to a certain tool. You obviously see a down side of this.

BTW, is there a clear definition of what core metrics and monitoring data are?

**Comment by vishh** [comment]
> BTW, is there a clear definition of what core metrics and monitoring data are?

Unfortunately this is not explicit from the code since #18770 is still a WIP. But in theory, core metrics are `cpu` and `memory` cgroup stats and `filesystem` stats. In the future, we might need basic `network` stats and `cpu load` stats.

**Comment by huang195** [comment]
I think I mentioned about our use case in #18769 before, but let me summarize it here again and see if the motivation of doing this work makes sense. We're building a kubernetes cluster on top of mesos, and along with kubernetes, we also have swarm, spark, and other frameworks. This means on a single node, we could have containers created and managed by kubernetes, swarm, spark, marathon, etc. all at the same time. We don't want every framework to use its own tool to collect runtime data (whether it's metrics or monitoring data), and instead, we want a single tool (let's call it X) that monitors for all of them, as it would lower overhead and create a consistent view across the different frameworks. 

So, if X is able to collect both core metrics as well as monitoring data, and it can format the data to a form that is consumable to Kubernetes (by means of writing a driver for X that implements the generic collector interface), why not use it? 

The pluggable collector interface gives a choice to Kubernetes users to pick and choose what and how metrics and monitoring data are collected. If they stick with the default, cadvisor will be used for ease of deployment. If they want to use another tool, at least there's a way for them to do it so now. What is there to lose?

**Comment by vishh** [comment]
The entire kubernetes resource management stack will depend on the validity
of the data coming from this metrics collector. That's why I'm weary of
supporting a pluggable solution for that.

Once cAdvisor is separated out of Kubelet, do you have any other issues
with having kubelet being self-sufficient?

**Comment by huang195** [comment]
> The entire kubernetes resource management stack will depend on the validity
> of the data coming from this metrics collector. That's why I'm weary of
> supporting a pluggable solution for that.

That is true, but metrics collectors and monitoring tools are pretty mature technology. I'd be surprised if one is that much better than its peers in terms of stability and data validity. In the long term, I think decoupling Kubernetes from these dependencies will only lead to its wider adoption.

> Once cAdvisor is separated out of Kubelet, do you have any other issues
> with having kubelet being self-sufficient?

So what you're saying is there is a separate cadvisor instance running in a pod, but the kubelet doesn't talk to it to get core metrics information, and instead it calls cadvisor routines locally to get the core metrics information. If so, aren't the core metrics information being collected in 2 places, i.e., one in kubelet and one by the cadvisor running in the pod? I'd rather see the kubelet talking directly to the cadvisor running in the pod to collect the core metrics information over REST APIs.

Your major concern seems to be the validity of the data coming from the metrics collectors if they're pluggable. Is my understanding correct?

**Comment by huang195** [comment]
I'd like to propose some ways of making progress on this PR. Let me first summarize the pros and cons of this PR said so far (folks on the cc list, please chime in if you have other comments).

Pros:
- Allows a pluggable interface to metrics and monitoring data so Kubernetes is no longer tied to cadvisor. This interface allows developers to write new drivers to support additional metrics and monitoring tools to work with Kubernetes. 
- Kubelet code is cleaned up so cadvisor structs are not spread all over the kubelet code. Instead, cadvisor code and structs are now all aggregated within the cadvisor driver located in the pkg/kubelet/collectors/ directory, making the code structure cleaner. Moreover, even if we decide to not make the interface pluggle today, it would still be a good practice to decouple cadvisor code from the kubelet code.

Cons:
- Metrics data's validity is critical to Kubernete's resource management stack, and making the interface pluggable will more likely cause problems to the data's validity.

I'd like to propose several options going forward:
1) I would still advocate the current design as is, because this PR is not about forcing users to not choose cadvisor, but rather allowing users to choose whatever metrics and monitoring tools of their choice. It also makes it easier for developers to write new drivers for additional metrics and monitoring tools. While I do agree metrics data's validity is vital to Kubernetes, I don't think making it pluggable is going to cause more problems (otherwise, Linux kernel would only support 1 file system today, although file system is a integral part of it :-), but we need to be careful with the interface design. 
2) This PR by default still uses the builtin cadvisor, so if command line options are not changed, kubelet will work exactly as is. It will only behave differently when the `--collector` and `--collector-url` are explicitly set to something else. Can we label these as `experimental` to emphasize that they might cause stability issues if one chooses to not use cadvisor? 
3) This is my least favorite option, which is to disable the `--collector` and `--collector-url` options for now so they're not exposed to users at all. However, developers can still work under the covers to fine-tune the pluggable interface and develop new drivers. Once this part of the code is more stable, we can re-enable these options to expose them to users.

Your thoughts? Thanks!

**Comment by derekwaynecarr** [comment]
In general, I would feel better about a pluggable solution if/when we felt we had the minimum set of stats defined for `cpu` `memory` `filesystem` `cpu load` in place / plumbed / and tuned for a single driver to support a variety of use cases (pod eviction, etc.) before we then look to define an additional plug-in model.  I worry if we factor too soon we will have to account for differences in plug-ins pre-maturely where instead it may help us to be a little more opinionated.

**Comment by huang195** [comment]
@derekparker Good point. If a pluggable interface is defined too early and then we have drivers written against it, frequent changes to the interface could cause unnecessary work in the drivers' code. 

One thing we can still benefit from this PR is that it restructures the kubelet code so that cadvisor code and structs are no longer spread all over the place but only placed in its driver code. If we don't clean up the code now, this problem will only get worse over time as more cadvisor use cases are identified over time and added to kubelet code in an adhoc way. This also forces code related to kubelet collecting metrics and monitoring data to be written in an "interface-friendly" way to prep for pluggability in the future.

**Comment by vishh** [comment]
Can you post a PR with just the new interface you intend to introduce? That
will help with reviewing.
And thanks a lot for picking this up +1

**Comment by huang195** [comment]
@vishh Will do. Appreciate your help shepherding this work.

**Comment by yujuhong** [comment]
@huang195, should we close this PR in favor of #19951?

**Comment by huang195** [comment]
@yujuhong #19951 is just the interface functions and data structs of the proposed collector interface, for easier design/code review. Once that is done, this PR will restructure the rest of the code to make use of the new interface.

**Pull request closed without merging**
