### PR TITLE
[cronjob]: make cronjob,job,pod control implementation the same

### PR DESCRIPTION
**Pull request by ideapark**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by soltysh — CHANGES_REQUESTED** [review]
/hold
/assign 
can you elaborate more why this change is needed?

**Comment by thinpark** [comment]
Since realJobControl,realCJControl,realPodControl have almost the same
implemetation details. Keep them the same idiomatic pointer syntax will help us
get a more fluent comprehensable.

This is not a prioritize between `pass by pointer` and `pass by value`, it is
just more about code readablity and fluetency.

**Pull request closed without merging**
