### PR TITLE
Fix hairpin mode

### PR DESCRIPTION
**Pull request by NikolayMurha**

### CODE REVIEW

**Comment by thockin** [comment]
ok to test

**Comment by thockin** [comment]
@MurgaNikolay thanks!  That's a pretty silly bug.  Can you sort out the CLA - I'd like to get this in as a cherry pick for next patch release.

**Comment by MurgaNikolay** [comment]
>  Can you sort out the CLA 

I signed it

**Comment by bprashanth** [comment]
Indeed. 
Well, at least the logs called this out and --hairpin-mode=veth is still possible. 
We should really get some unittests around this part of the kubelet (even though this flag hackery is short term).

**Pull request merged**
