### PR TITLE
Update dashboard version to v1.5.1

### PR DESCRIPTION
**Pull request by rf232**
**What this PR does / why we need it**:
Latest Dashboard developments, including a CSRF issue in the dashboard POST handlers

**Release note**:
```
Set Dashboard UI version to v1.5.1
```

### CODE REVIEW

**Review by bryk — APPROVED** [review]
LGTM

**Comment by bryk** [comment]
@k8s-bot unit test this

**Comment by rf232** [comment]
#39604

**Comment by bryk** [comment]
@k8s-bot unit test this

**Pull request merged**
