### PR TITLE
Fix golint pkg/kubelet/stats/client.go

### PR DESCRIPTION
**Pull request by obitech**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Small increases in code quality as some golinting issues will be fixed in:
- `pkg/kubelet/client/kubelet_client.go`
- `pkg/kubelet/stats/log_metrics_provider.go`

**Which issue(s) this PR fixes**:

Ref #78179 

**Special notes for your reviewer**:
I have not removed `pkg/kubelet/stats` from `hack/.golint_failures` as it would require changing the name of  `stats.StatsProvider` to `stats.Provider`. I don't know the best practice for this in the kubelet code base, but in another PR it has been [suggested](https://github.com/kubernetes/kubernetes/pull/75202#pullrequestreview-231460270) to leave those changes out.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
/ok-to-test

+1 that I'm not sure what to do about these stuttering issues, but I still think this pr is a step in the right direction. Thank you :)

**Review by mattjmcnaughton — CHANGES_REQUESTED** [review]
@obitech , I believe you running into some linting/codegen issues because we changed the source code, but didn't necessarily update the auxiliary generated files. Try running `hack/update-all.sh` (and you can check if you caught all the uses with `hack/verify-all.sh`). That should be a good first step for resolving the test failures you're seeing.

/lgtm cancel

Please feel free to ping me when the test suite is passing again, and I'm happy to rereview :) thanks!

**Comment by obitech** [comment]
@mattjmcnaughton all tests are green now! Actually I forgot to change an occurrence of `EnableHTTPS` in `cmd/kube-apiserver/app/options/options`, which is why it failed. I really appreciate you pointing those things out though, it helps new contributors like me to understand a bit more of what I have to do in order to make things work :)

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

nice work!

**Comment by obitech** [comment]
This has been open for a while, any reason why we can't merge it?

**Comment by derekwaynecarr** [comment]
kubelet changes lgtm.

/lgtm
/approve

**Comment by obitech** [comment]
Who do I need to ping to make this pass? :(

**Comment by mattjmcnaughton** [comment]
/assign @deads2k 
/assign @BenTheElder 

added a couple more reviewers :) as the robot says, you need approvers from each of the different components of the code this modifies.

**Pull request merged**
