### PR TITLE
CHANGELOG-1.20: fix anchor point err

### PR DESCRIPTION
**Pull request by chymy**
Signed-off-by: chymy <chang.min1@zte.com.cn>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/sig release
/ok-to-test
/lgtm

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by chymy** [comment]
/assign @damemi 

Thanks!

**Review by damemi — COMMENTED** [review]
/unassign
maybe a typo, I am not a changelog approver 🙂

**Comment by chymy** [comment]
/assign @justaugustus 

Thanks!

**Comment by chymy** [comment]
/assign @liggitt
Thanks!

**Comment by justaugustus** [comment]
Thanks!
/lgtm
/approve

**Pull request merged**
