### PR TITLE
[DO NOT MERGE] test change for kops presubmit

### PR DESCRIPTION
**Pull request by shyamjvs**
xref https://github.com/kubernetes/kubernetes/issues/73444#issuecomment-461167558

/cc me
/assign me

### CODE REVIEW

**Comment by shyamjvs** [comment]
The presubmit is now failing with:

```
error reading cluster configuration "e2e-121498-dba53.test-cncf-aws.k8s.io": error reading s3://k8s-kops-prow/e2e-121498-dba53.test-cncf-aws.k8s.io/config: Unable to list AWS regions: AuthFailure: AWS was not able to validate the provided access credentials
```

Seems like the credentials aren't valid. Can we fix the secret with new credentials?
@BenTheElder @krzyzacy

**Comment by krzyzacy** [comment]
hummmm I cannot login to the cncf account anymore?! :man_shrugging: 

maybe @justinsb or @spiffxp can poke?

**Comment by shyamjvs** [comment]
Ok, kops presubmit is running now - https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/73797/pull-kubernetes-e2e-kops-aws/121514/
The job failed, but that's unrelated to cncf account issue (it's a bunch of e2e tests failing).
Closing this PR as the purpose is served..

**Pull request closed without merging**
