### PR TITLE
Automated cherry pick of #59686: Add cloud-provider policies to be applied via addon mgr

### PR DESCRIPTION
**Pull request by grayluck**
Cherry pick of #59686 on release-1.8.

#59686: Add cloud-provider policies to be applied via addon mgr

### CODE REVIEW

**Comment by tallclair** [comment]
I thought we were done with 1.8 releases?

**Comment by grayluck** [comment]
Yes seems like we are. Thanks Tim!
But we still need https://github.com/kubernetes/kubernetes/pull/66872 for 1.9.

**Pull request closed without merging**
