### PR TITLE
[WIP] Secret generation

### PR DESCRIPTION
**Pull request by jimmidyson**
Putting in this PR early on to get feedback on whether this is the right approach or if it's even wanted (I want it of course!), as discussed in #12732.

This allows for pluggable secret generators to be implemented, selection of secret generator is done via the `SecretType` of the secret, with plugins adding their own types in as required.

The only implemented plugin right now is for generation of self-signed TLS certificates. 

The added godeps are there to be reused by the next plugin I aim to implement based on a remote [cfssl](https://github.com/cloudflare/cfssl) service running in the cluster.

Questions:
- How do I get configuration through to plugins via the controllers? I'd like to pass this in via the `ProbePlugins` method to enable secret generators only if the appropriate configuration is available.
- How to handle multiple plugins generating for the same `SecretType`? Only one should be registered & enabled for a `SecretType` at a time. Should I use separate `SecretType`s for each plugin? I'd like to be able to have multiple implementations for a generator, e.g. for a `SecretType` of `kubernetes.io/server-certificate` there can be self-signed; remote cfssl; letsencrypt.org; generic REST endpoint; etc. This could be configurable via master config. How would I do this?

### CODE REVIEW

**Comment by eparis** [comment]
@pmorie

**Comment by jimmidyson** [comment]
I've left this for a little while & need to think more on it. The current approach uses a new controller & secrets are generated async which means that pods could be started with references to the secrets before the secrets are actually generated. If secret generation is desirable, as I think it is, then secrets should be generated synchronously with the create secret  request so they are available for use immediately. I don't think there is such a way to do this right now is there? Would appreciate pointers.

**Comment by pmorie** [comment]
@k8s-bot ok to test

**Comment by pmorie** [comment]
@liggitt

**Comment by jimmidyson** [comment]
As I said above, ignore this implementation. Perhaps best to close this PR & discuss more on #12732?

**Comment by liggitt** [comment]
Related (though narrower in scope) https://github.com/kubernetes/kubernetes/pull/8866

**Comment by bgrant0607** [comment]
Could you please explain what this PR is doing? We normally recommend submitting a proposal first:
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/faster_reviews.md#1-dont-build-a-cathedral-in-one-pr

**Comment by bgrant0607** [comment]
"This allows for pluggable secret generators to be implemented"

Pluggable where?

**Comment by jimmidyson** [comment]
Closing while thinking about a better way to implement than using a async controller which leads to empty secrets before generation & failed pods - oops.

**Pull request closed without merging**
