### PR TITLE
Add support for ppc64le architecture.

### PR DESCRIPTION
**Pull request by Pensu**
This patch includes ppc64le arch as a valid host option.

### CODE REVIEW

**Comment by roberthbailey** [comment]
@k8s-bot ok to test

**Comment by Pensu** [comment]
@roberthbailey Hi, I am not able to understand the errors here. Could you please help me with that? TIA.

**Comment by roberthbailey** [comment]
Here's the relevant snippet from the unit test failure (which seems unrelated to your change):

```
+++ [1210 06:35:02] Starting kubectl proxy
+++ [1210 06:35:02] On try 1, use proxy port 60486 if it's free

netcat isn't installed, can't verify if 127.0.0.1:60486 is free, skipping the check...

F1210 06:35:02.799440   18247 proxy.go:132] listen tcp 127.0.0.1:60486: bind: address already in use
I1210 06:35:07.522381   13642 kubelet.go:2289] skipping pod synchronization - [Failed to start ContainerManager system validation failed - Following Cgroup subsystem not mounted: [memory]]
I1210 06:35:12.523387   13642 kubelet.go:2289] skipping pod synchronization - [Failed to start ContainerManager system validation failed - Following Cgroup subsystem not mounted: [memory]]
!!! [1210 06:35:15] Timed out waiting for kubectl proxy to answer at http://127.0.0.1:60486/healthz; tried 25 waiting 0.5 between each
!!! Error in ./hack/test-cmd.sh:48
  'return 1' exited with status 1
Call stack:
  1: ./hack/test-cmd.sh:48 start-proxy(...)
  2: ./hack/test-cmd.sh:236 runTests(...)
  3: ./hack/test-cmd.sh:1270 main(...)
Exiting with status 1
```

**Comment by roberthbailey** [comment]
@k8s-bot unit test this

**Comment by roberthbailey** [comment]
The logs from the e2e failure are gone, so let's try it again.

@k8s-bot test this please

**Pull request merged**
