### PR TITLE
Add simple reference to synopsis of kube-scheduler

### PR DESCRIPTION
**Pull request by hase1128**
**What type of PR is this?**
 /kind documentation

**What this PR does / why we need it**:
Address the https://github.com/kubernetes/website/issues/17170
The objective is making the document into more polite for user.

**Which issue(s) this PR fixes**:
https://github.com/kubernetes/website/issues/17170

**Special notes for your reviewer**:
Would you please inform me if some required steps are missing?

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
NONE

### CODE REVIEW

**Comment by hase1128** [comment]
do-not-merge/release-note-label-needed

**Review by wgliang — APPROVED** [review]

**Comment by hase1128** [comment]
@wgliang @ravisantoshgudimetla 
Could you add `approval` label to this PR?

**Review by wgliang — APPROVED** [review]
/lgtm

Thanks @hase1128

**Comment by hase1128** [comment]
> /lgtm
> 
> Thanks @hase1128

Thanks the labeling! but I think `approved` label is needed (not `lgtm` label)

**Pull request merged**
