### PR TITLE
Automated cherry pick of #105046: Skip check for all topology labels when using system default

### PR DESCRIPTION
**Pull request by alculquicondor**
Cherry pick of #105046 on release-1.21.

#105046: Skip check for all topology labels when using system default

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
Fix regression in 1.19+ in scheduler system default topology spreading when nodes don't have zone labels. Pods correctly spread by default now.
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
@kubernetes/release-managers

**Comment by cpanato** [comment]
/triage accepted

From parent PR
/priority important-soon

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
