### PR TITLE
update iscsi example for best practices

### PR DESCRIPTION
**Pull request by jijun2**
related to #11361

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/15067)

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks. Currently hashing out how we'd like examples to look in #14256. Will get back to this after I finish that review.

**Comment by jijun2** [comment]
@bgrant0607 , Ok, thanks！

**Comment by bgrant0607** [comment]
We have published examples guidelines now:
https://github.com/kubernetes/kubernetes/blob/master/examples/guidelines.md

@saad-ali Could we please consolidate all of the storage examples, such as under examples/storage?

cc @kubernetes/examples

**Comment by bgrant0607** [comment]
cc @kubernetes/sig-storage

**Comment by rootfs** [comment]
LGTM

**Comment by saad-ali** [comment]
> @saad-ali Could we please consolidate all of the storage examples, such as under examples/storage?

Will do: issue https://github.com/kubernetes/kubernetes/issues/23671

**Comment by bgrant0607** [comment]
@jijun2 Please update this or close it.

**Pull request closed without merging**
