### PR TITLE
Set up generation of protobuf from our Go structs for use as a serialization format

### PR DESCRIPTION
**Pull request by smarterclayton**
This commit adds support for generation of protobuf IDL and marshallers via gogo/protobuf by ensuring that the generated IDL can create identical structs to our source Go structs.

Depends on gogo/protobuf#121, which will add the necessary support for identical struct generation.

Continues #16649, first 3 commits have been extracted into #17852 and #17853

Todo:
- [x] Finish gogo/protobuf#121
- [x] Add hack/ scripts to generate and verify the protobuf marshallers
- [x] Refactor runtime.Unknown#RawJSON to be generic to codec - followup
- [x] Split runtime.Codec into two parts - conversion, and encoding. Make the conversion a wrapper on the encoding - #17922
- [x] Split the JSON Codec into its own package - #17922
- [x] Refactor apiserver to support multiple codecs via Content-Type and Accept handling - #17922
- [x] Investigate doing string enumerations for our constant value Protobuf structs - won't bother now
- [x] Determine whether to support XXX_unrecognized - not now
- [x] Split serialization tests into versioned round tripping (to serialization codec) and conversion round tripping - not now

@lavalamp please take a look at the TODO comments about runtime codec changes

### CODE REVIEW

**Comment by lavalamp** [comment]
I think I am on board with codec changes-- it might be helpful to see the proposed split, though. I am thinking right now that there should just be a codec interface, and if people want conversion magic they should write a wrapper implementing that same interface. That may not work, though.

**Comment by smarterclayton** [comment]
Yes, that's what I did

**Comment by lavalamp** [comment]
Cool-- this has WIP in the title, is it ready for a review?

**Comment by smarterclayton** [comment]
Looking at the generated protobuf and the high level go2idl structure is
the important part.  I'm not a protobuf expert by any means so I took the
path of least resistance. What's not shown - the step that would take the
generated protobuf struct tag and back port them to our external structs so
we have locked tag numbers.



On Dec 1, 2015, at 6:56 PM, Daniel Smith <notifications@github.com> wrote:

Cool-- this has WIP in the title, is it ready for a review?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/17854#issuecomment-161135734>
.

**Comment by lavalamp** [comment]
Looks pretty good. Some of these commits are already merged or in other PRs, right?

**Comment by smarterclayton** [comment]
I would say the first four but github reordered them.  The easy splits are
split.  I'll probably split go-to-protobuf and we can do deep review and
then merge (and iterate until we are happy with output).  The decoder is
waiting for my codec split.  The actual generation is the last full step.


On Dec 2, 2015, at 5:08 PM, Daniel Smith <notifications@github.com> wrote:

Looks pretty good. Some of these commits are already merged or in other
PRs, right?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/17854#issuecomment-161449004>
.

**Comment by smarterclayton** [comment]
Ok, this is ready for review.  I've added hack/* scripts (which aren't invoked yet) that handle updating and generating the protobufs, building protoc-gen-gogo from Godeps, and picked up the most recent changes to go2idl.  Everything generates to the "proto" go build tag, so if you want to build you'll need to:

    hack/update-generated-protobuf.sh
    KUBE_GOFLAGS="-tags proto" hack/build-go.sh

Once this gets merged, a follow on will actually enable the generation of protobuf and enforce it remaining up to date in builds. That follow on will also add it to the API once #17922 merges as an optional serialization target, and flag it experimental while we play with the protobuf to ensure it's stable and usable by other clients.

**Comment by smarterclayton** [comment]
@k8s-bot unit test this

**Comment by smarterclayton** [comment]
blocked on #19104

**Comment by smarterclayton** [comment]
@k8s-bot unit test this

**Comment by smarterclayton** [comment]
@kubernetes/sig-api-machinery if @krousey can't handle this now.  As noted this doesn't actually change behavior of the system, just lands the code and basic processes.

**Comment by krousey** [comment]
@smarterclayton Sorry. Just got back yesterday and I missed that this was no longer WIP. I'm looking at it now.

**Comment by smarterclayton** [comment]
Since this is going to be something that evolves over time (and will be
experimental regardless for a long time), don't feel that you have to nit
pick the actual protobuf schema.  We'll slate time for that and the pattern
over multiple pulls.

**Comment by smarterclayton** [comment]
I refactored so that everything wasn't in the main package and addressed your first comments in https://github.com/kubernetes/kubernetes/commit/979611e2e249ec656bb4d11360241311142c8581

**Comment by krousey** [comment]
Ok I've made a full pass. Thanks for being patient.

**Comment by smarterclayton** [comment]
Comments addressed

**Comment by smarterclayton** [comment]
Follow up items I'll address in another pull:

* After we generate the marshallers, extract the new protobuf struct tags and write them back to the source Go structs (so that we lock tags in our source of truth) - Go unfortunately is going to require me to copy their struct tag parsing logic to strip only the field we want (protobuf) and leave the others untouched.
* After we do that, regenerate the .proto without the gogoprotobuf extensions for easier client use (something I saw the cockroachdb guys were doing) - then I tested that locally and was able to get Java, Ruby, and Python decoder libraries generated locally.

**Comment by krousey** [comment]
Looks good to me. Squash and apply the label after.

**Comment by smarterclayton** [comment]
@k8s-bot unit test this

**Comment by smarterclayton** [comment]
@k8s-bot unit test this

**Pull request merged**
