### PR TITLE
Update KUBE_IMAGE

### PR DESCRIPTION
**Pull request by swarren83**
updating KUBE_IMAGE to pull latest RAX CoreOS(Beta) image.

### CODE REVIEW

**Comment by mikedanese** [comment]
@doublerr

**Comment by mikedanese** [comment]
@swarren83  can you please sign the CLA?

**Comment by doublerr** [comment]
@swarren83 did you verify this works on latest beta? There were issues on 717.x.x I believe.

**Comment by swarren83** [comment]
I tested the image on release v1.0 and it built without issues but then I ran into an etcd conflict. Not sure if the etcd conflict is related. I will perform more testing.

**Comment by swarren83** [comment]
Tested v0.18.1 and confirmed CoreOS 723.3.0 works.
Tested v0.21.0, it built successfully but etcd fails after the master or any minion is rebooted.
Tested v1.0.1, it built using the k8s build script but etcd fails after the master or any minion is rebooted.

All releases above v0.21.0 failed to build using the dev-build-and-up method.

**Comment by mikedanese** [comment]
@swarren83 so do we actually want this if it breaks for releases above v0.21.0?

**Comment by doublerr** [comment]
@mikedanese We can close this. I'm going through and updating a lot of stuff this week to get 1.x working. I'll update the image in that PR.

**Pull request closed without merging**
