### PR TITLE
update deployment, daemonset, replicaset, statefulset to apps/v1

### PR DESCRIPTION
**Pull request by islinwb**
**What this PR does / why we need it**:
The core workloads API is GA in Kubernetes 1.9.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by deads2k** [comment]
I'm fine with the update, but I'd expect to see someone from @kubernetes/sig-apps-pr-reviews  having a look.

/assign @tnozicka

**Review by tnozicka — CHANGES_REQUESTED** [review]
we shouldn't leave tests and cli behind when doing the switch
```bash
$ grep -RIni --exclude-dir={staging,vendor} -E -e '\.ExtensionsV1beta1\(\)\.(Deployments|DaemonSets|StatefulSets)' | wc -l
46
```

**Comment by islinwb** [comment]
@tnozicka Thanks for pointing out that! I'll update it.

**Comment by liggitt** [comment]
@islinwb are you able to update this? I'm interested in seeing these uses resolved in 1.13

**Comment by liggitt** [comment]
rebased and included in https://github.com/kubernetes/kubernetes/pull/70370

/close

**Pull request closed without merging**
