### PR TITLE
Automated cherry pick of #11804

### PR DESCRIPTION
**Pull request by rubenv**
Cherry pick of #11804 on release-1.0.

### CODE REVIEW

**Comment by rubenv** [comment]
I signed it!

**Comment by rubenv** [comment]
@sgotti OK to satisfy the CLA enforcer?

**Comment by rubenv** [comment]
CLA problem might have been due to the fact that I commit under a different e-mail address as my normal Google account. Signed with that one as well.

**Comment by rubenv** [comment]
So, eh, how do I poke that CLA bot again?

I signed it! (again)

**Comment by roberthbailey** [comment]
I'm not sure how best to appease the CLA bot. If you don't mind opening a new PR with the right email address that might be easiest. Otherwise I'll see if there's anything I can do on this end.

**Comment by zmerlynn** [comment]
@k8s-bot ok to test

LGTM

Don't worry about the CLA issue. See [cherry-picks] (https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md).

**Comment by roberthbailey** [comment]
Thanks for the clarification about the CLA @zmerlynn.

**Pull request merged**
