### PR TITLE
Add 201/Status to the list of returned objects.

### PR DESCRIPTION
**Pull request by brendandburns**
**What this PR does / why we need it**:
Adds 201/202 to the list of codes/objects returned by `POST` and 201 to the list of codes returned by `PUT` requests in Swagger/OpenAPI

**Special notes for your reviewer**:
This helps fix 
https://github.com/kubernetes-client/csharp/issues/29

**Release note**:
```release-note
Adds 201/202 to the list of codes/objects returned by `POST` and 201 to the list of codes returned by `PUT` requests in Swagger/OpenAPI
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
The changes lgtm.

In addition, 
* 201 could be returned by PUT as well: https://github.com/kubernetes/kubernetes/blob/v1.9.0-alpha.1/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go#L920

* POST can return 202: https://github.com/kubernetes/kubernetes/blob/v1.9.0-alpha.1/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go#L485

**Comment by nikhiljindal** [comment]
xref https://github.com/kubernetes/kubernetes/issues/6167?

**Comment by smarterclayton** [comment]
201 can also be the type returned - was your client not barfing on that?  We can return Kind on 200 or 201, and the rest of the codes (except 204) return a status.

**Comment by brendandburns** [comment]
@smarterclayton 

It looks like go-restful doesn't know how to do `oneOf` style returns...  What is the recommended course of action? If we don't specify a type, the generated code is going to be ugly, if we do specify a type it's going to explode if the wrong type goes in.

The right answer ultimately is probably to fix go-restful, but that will take a while to accomplish and I'd like to have a working client :)

**Comment by smarterclayton** [comment]
GG go-restful.  201 on almost everything should always be the type from the input, although there are exceptions in a few cases.  If you set Returns(201, ..., versionedType) I think that's more correct than status (if we can only pick one)

**Comment by brendandburns** [comment]
Ok, updated to pass the versioned object. Also added 201 to `PUT` and `202` to `POST`

Please take another look.

--brendan

**Comment by brendandburns** [comment]
self-lgtm since it was just fixing the `hack-*` scripts.

**Comment by brendandburns** [comment]
self-lgtm again, due to script cleanups.

**Pull request merged**
