### PR TITLE
[DO NOT REVIEW][DO NOT SUBMIT] Experimental

### PR DESCRIPTION
**Pull request by wojtek-t**

### CODE REVIEW

**Comment by shyamjvs** [comment]
/test pull-kubernetes-kubemark-e2e-gce-scale

We should now be able to runs this.. Let's try.

**Comment by wojtek-t** [comment]
The results weren't satisfying here.
So I changed the approach a little bit one more time.

Closing in favor of https://github.com/kubernetes/kubernetes/pull/60067

**Pull request closed without merging**
