### PR TITLE
update generated protobuf for audit v1beta1 api

### PR DESCRIPTION
**Pull request by CaoShuFeng**
**Release note**:
```
NONE
```

### CODE REVIEW

**Comment by CaoShuFeng** [comment]
/area/audit

**Comment by sttts** [comment]
Overriding approval label as the addition of the path is trivial.

**Comment by CaoShuFeng** [comment]
Rebase on #50007

**Comment by CaoShuFeng** [comment]
/LGTM

Can I label it my self as a member?

**Pull request merged**
