### PR TITLE
Added alejandrox1 as test/* reviewer

### PR DESCRIPTION
**Pull request by alejandrox1**
Signed-off-by: alejandrox1 <alarcj137@gmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Added myself as reviewer for test/*

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alejandrox1** [comment]
/priority backlog
/sig testing

/assign @timothysc @oomichi 
ptal

**Review by neolit123 — COMMENTED** [review]
/lgtm
from me. thanks for the efforts.

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve

**Comment by oomichi** [comment]
Oh, I didn't think @alejandrox1 was not a reviewer yet.
Thanks for your contribution.

/lgtm

**Pull request merged**
