### PR TITLE
update metrics to conform promlint

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Update metrics name from `scheduler_total_preemption_attempts` to `scheduler_preemption_attempts_total` as per `promlint` rules: `counter metrics should have "_total" suffix`.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
kube-scheduler: The metric name `scheduler_total_preemption_attempts` has been renamed to `scheduler_preemption_attempts_total`.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

/priority important-soon

### CODE REVIEW

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by ahg-g** [comment]
/hold

this is like deprecating and adding a new metric!

**Comment by RainbowMango** [comment]
> this is like deprecating and adding a new metric!

There usually two methods for modifying a metric, especially for an alpha metric:
- 1 Modify directly as it's in the alpha state;
- 2 deprecate the old one and create a new replacement.

Seems @ahg-g like method 2, right? 

/cc @Huang-Wei

**Comment by ahg-g** [comment]
/lgtm
/approve

since it is an alpha metric

**Comment by Huang-Wei** [comment]
LGTM, thanks @RainbowMango.

**Pull request merged**
