### PR TITLE
Remove unused enable_node_monitoring

### PR DESCRIPTION
**Pull request by eparis**
Back in 1a7f7245e7117d5cecd6dc12a57845ea8fe83b31 we dropped the one
place this was used, but left all of the variable and definitions and
garbage around cluster/

### CODE REVIEW

**Comment by eparis** [comment]
@vmarmol since you removed it's purpose.

**Comment by mbforbes** [comment]
@vmarmol for a one-over and pass to most relevant TL for triage / initial review

**Comment by vmarmol** [comment]
Thanks for the cleanup @eparis! LGTM, sending over to @dchen1107 for triaging.

**Comment by dchen1107** [comment]
Thanks for cleanup the code. Even this is not target to any 1.0 issue, but it is very safe and indeed get rid of those confusion on cluster  configurations. 

LGTM

**Comment by roberthbailey** [comment]
LGTM.

**Comment by satnam6502** [comment]
I did think about removing this variable earlier but I wanted to wait until I could speak to a GKE person so it could be done in sync and without risking a GKE breakage (as has happened in similar situations before).

**Pull request merged**
