### PR TITLE
kubectl: include init containers when determining pod QoS

### LINKED ISSUE #98782: Determining pod QoS should keep consistent with kubelet in kubectl library
**What happened**:
In kubectl library, `GetPodQOS` logic is not the same as the one in `pkg/apis/core/helper/qos/qos.go`
**What you expected to happen**:
`GetPodQOS` logic should be the same.
**How to reproduce it (as minimally and precisely as possible)**:
Create a pod with a guaranteed QoS class and a best-effort QoS initcontainer.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by pacoxu**
/kind bug
Fixes #98782
/sig cli
/assign soltysh

```release-note
NONE
```
sync #75223 logics to kubectl like #98783

### CODE REVIEW

**Comment by eddiezane** [comment]
Can you please add a comment to the original function?

Something like

```
// When this function is updated please also update staging/src/k8s.io/kubectl/pkg/util/qos/qos.go
```

**Comment by eddiezane** [comment]
Can you please also rename the `corev1` import to `core` so we can diff cleanly?

```diff
diff pkg/apis/core/helper/qos/qos.go staging/src/k8s.io/kubectl/pkg/util/qos/qos.go
2c2
< Copyright 2017 The Kubernetes Authors.
---
> Copyright 2015 The Kubernetes Authors.
17,18d16
< // NOTE: DO NOT use those helper functions through client-go, the
< // package path will be changed in the future.
21a20
>       corev1 "k8s.io/api/core/v1"
24d22
<       "k8s.io/kubernetes/pkg/apis/core"
27c25
< var supportedQoSComputeResources = sets.NewString(string(core.ResourceCPU), string(core.ResourceMemory))
---
> var supportedQoSComputeResources = sets.NewString(string(corev1.ResourceCPU), string(corev1.ResourceMemory))
```

**Comment by pacoxu** [comment]
Updated @eddiezane 
Thanks for the comments.

```
➜  kubernetes git:(kubectl-qos) diff pkg/apis/core/helper/qos/qos.go staging/src/k8s.io/kubectl/pkg/util/qos/qos.go
2c2
< Copyright 2017 The Kubernetes Authors.
---
> Copyright 2015 The Kubernetes Authors.
17,18d16
< // NOTE: DO NOT use those helper functions through client-go, the
< // package path will be changed in the future.
```

**Review by eddiezane — APPROVED** [review]

**Comment by eddiezane** [comment]
/assign @lavalamp

For the comment approval.

**Comment by pacoxu** [comment]
Kindly ping @liggitt @lavalamp

**Comment by pacoxu** [comment]
@eddiezane approved the change in kubectl `staging/src/k8s.io/kubectl/OWNERS [eddiezane]`
There is a small change in `pkg/apis/OWNERS` comment.

**Comment by kerthcet** [comment]
maybe it's better to add a note like `init containers are included also`
whatever /lgtm

**Pull request merged**
