### PR TITLE
Remove an e2e test specific to kubeup clusters - Part One

### PR DESCRIPTION
**Pull request by upodroid**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Deletes an e2e test that tests how kubeup clusters are created. This test fails if a cluster was created via kops or another tool because the firewall rules are different. kops firewall rules and cluster bootstrapping are tested extensively at kubernetes/kops.

#### Which issue(s) this PR fixes:

Should fix this failing error
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeup-to-kops#ci-kubernetes-e2e-cos-gce-canary&include-filter-by-regex=Firewall

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
https://github.com/kubernetes/enhancements/issues/4224

### CODE REVIEW

**Review by pohly — COMMENTED** [review]
Is this test going to be moved elsewhere or is it simply obsolete? I sounds like it's obsolete, I just want to be sure.

It would be good to get someone who is working on cloud provider support to LGTM. I'm not up-to-date on what the plans there are.

For SIG Testing, removing special cases from e2e/framework/... is always good, so:
/approve

**Comment by hakman** [comment]
@aojea @justinsb Could you take a look? Thanks!

**Pull request merged**
