### PR TITLE
[WIP] update dependencies to remove form3tech-oss/jwt-go

### LINKED ISSUE #104007: Use golang-jwt/jwt instead of form3tech-oss/jwt-go
We used to have dgrijalva/jwt-go a while ago which was unmaintained. So folks switched to a fork in `form3tech-oss` org. However there is a community maintained fork at https://github.com/golang-jwt/jwt we should be using.

Links:
- https://github.com/Azure/go-autorest/issues/642
- https://cloud-native.slack.com/archives/C01GVR8SY4R/p1627562086149400

```
vendor/github.com/heketi/heketi/client/api/go-client/client.go:	jwt "github.com/form3tech-oss/jwt-go"
vendor/github.com/Azure/go-autorest/autorest/adal/token.go:	"github.com/form3tech-oss/jwt-go"
vendor/go.etcd.io/etcd/server/v3/auth/jwt.go:	jwt "github.com/form3tech-oss/jwt-go"
vendor/go.etcd.io/etcd/server/v3/auth/options.go:	jwt "github.com/form3tech-oss/jwt-go"
```

So what do we need to do? Persuade the folks maintaining the following repos to switch to the community fork.
- https://github.com/heketi/heketi/
- https://github.com/Azure/go-autorest/
- https://github.com/etcd-io/etcd/

By first filing issues to raise their awareness and following it up with PRs

/area code-organization

### PR DESCRIPTION
**Pull request by slaskawi**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This Pull Request updates dependencies to remove an obsolete `form3tech-oss/jwt-go` depenedncy.

#### Which issue(s) this PR fixes:

Fixes #104007

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
I only see `vendor/github.com/golang-jwt/jwt/v4/` being added and no removals 🤔

**Comment by slaskawi** [comment]
@BenTheElder Thanks for the interest in this issue.

This is a work-in-progress PR that got blocked on Heketi upgrade. I put a detailed status here: https://github.com/kubernetes/kubernetes/issues/104007#issuecomment-1106200371

**Comment by ritazh** [comment]
@slaskawi any updates on this PR?

**Pull request closed without merging**
