### PR TITLE
Update Azure Go SDK to v55.0.0

### PR DESCRIPTION
**Pull request by feiskyer**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Update Azure Go SDK to v55.0.0.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Update Azure Go SDK to v55.0.0
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by feiskyer** [comment]
Rebased again. @dims could you have a look?

**Review by dims — APPROVED** [review]
We are picking up one new dependency `josharian/intern` (MIT license) since the transitive dependency of `mailru/easyjson` picked that up. 

all the changes are using tags, so that's a good sign.

Dependency changes look good.

thanks @feiskyer 

/approve
/lgtm
/assign @smarterclayton @liggitt (for root approval)

**Comment by feiskyer** [comment]
Rebased the PR 
/hold cancel

**Comment by liggitt** [comment]
/hold

is it expected the azure jobs are failing?

**Comment by feiskyer** [comment]
Rebased again.
/hold cancel

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> /hold
> 
> is it expected the azure jobs are failing?

Below two test cases started failing on ppc64le since yesterday:
vendor/k8s.io/legacy-cloud-providers/azure/auth: 

- TestGetServicePrincipalTokenFromMSIWithUserAssignedID
- TestGetServicePrincipalTokenFromMSI
https://k8s-testgrid.appspot.com/sig-node-ppc64le#unit-tests

@feiskyer @liggitt Can you please let us know if this is somehow related?
Below is the Error Message:
```
azure_auth_test.go:73: 
        	Error Trace:	azure_auth_test.go:73
        	Error:      	Received unexpected error:
        	            	MSI not available
        	Test:       	TestGetServicePrincipalTokenFromMSIWithUserAssignedID
```
@mkumatag ^^

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/compare/503d0487d...a68644b was the delta between the passing and failing tests, so yes... this is the culprit

**Comment by Rajalakshmi-Girish** [comment]
@liggitt Please let us know if an issue can be raised?

**Comment by liggitt** [comment]
Please open an issue and assign to @feiskyer

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> Please open an issue and assign to @feiskyer

https://github.com/kubernetes/kubernetes/issues/102987 looks like it has to be triaged before assigning to someone.

**Pull request merged**
