### PR TITLE
Memory consumption added to Resource Consumer

### PR DESCRIPTION
**Pull request by socaa**
Part of #11570 

@piosz

### CODE REVIEW

**Comment by piosz** [comment]
@k8s-bot test this please

**Comment by piosz** [comment]
LGTM

**Comment by derekwaynecarr** [comment]
Any reason why this didn't accept resource.Quantity style strings?

**Comment by piosz** [comment]
Nope. We can add this.

**Comment by derekwaynecarr** [comment]
@piosz - am I mistaken that this is not really consumable yet?  

It looks like the memory consumer will call stress command, but stress is not in the image for the container.

I am interested in using this to demonstrate OOM situations in overcommit, so wanted to know if I am missing something.

**Comment by piosz** [comment]
@derekwaynecarr the PR which adds stress to the Docker file is in flight https://github.com/kubernetes/kubernetes/pull/13736. Once it is merged I'll build an image and upload it into GCR. It should be done tomorrow. Meanwhile if you need it feel free to build your own image.

Also some reference how to use Resource Consumer can be find here https://github.com/kubernetes/kubernetes/blob/master/test/e2e/autoscaling_utils.go

**Comment by derekwaynecarr** [comment]
thanks @piosz

**Pull request merged**
