### PR TITLE
Replace sets.List() with sets.UnsortedList() in pkg/proxy

### PR DESCRIPTION
**Pull request by m1093782566**
**What this PR does / why we need it**:

Replace sets.List() with sets.UnsortedList() in pkg/proxy - sets.List() will sort the result array, we don't need sorted array in pkg/proxy. Using sets.UnsortedList() can reduce the unnecessary overhead spending.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

@wojtek-t wdyt ^_^

**Release note**:

```release-note
NONE
```

/sig network

### CODE REVIEW

**Comment by thockin** [comment]
Does this fix a real bug?  where's the issue?

/lgtm
/approve no-issue

**Comment by m1093782566** [comment]
> Does this fix a real bug? where's the issue?

No one report it yet. I just scanned the code base and find them. BTW, I don't think it's a bug - it's an optimization instead?

**Pull request merged**
