### PR TITLE
e2e network tests with host network should Skip if ports are occupied

### PR DESCRIPTION
**Pull request by aojea**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

since we added tests to check connectivity against pods with
hostNetwork: true, there is the possibility that those pods
fail to run because the port is being used in the host.

Current test were using port 8080,8081 and 8082 that are commonly
used in hosts for other applications.

We could change the ports, but that will not be sustainable in the long term, so
we skip if the service fails to be created if hostNetwork is true and we'll
encourage new tests with host network to use more "uncommon" ports

**Which issue(s) this PR fixes**:

Failing jobs

https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-kube-dns-nodecache
https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-coredns-nodecache

**Special notes for your reviewer**:

The new tests were added yesterday https://github.com/kubernetes/kubernetes/pull/94812 and are covering a legit scenario that wasn't test until now, so this is kind of expected :upside_down_face: 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @MrHohn @andrewsykim 
The other option is to change the jobs to not have anything listening on port 8080,8081
/cc @prameshj

**Comment by aojea** [comment]
it seems those jobs have something listening on port 8080
```

I1111 02:50:40.233] NAME                                  NETWORK               DIRECTION  PRIORITY  ALLOW            DENY  DISABLED
I1111 02:50:40.234] e2e-0a09feb058-a5e3b-minion-http-alt  e2e-0a09feb058-a5e3b  INGRESS    1000      tcp:80,tcp:8080        False
I1111 02:50:41.226] allowed:
I1111 02:50:41.227] - IPProtocol: tcp
I1111 02:50:41.227]   ports:
I1111 02:50:41.227]   - '80'
I1111 02:50:41.227] - IPProtocol: tcp
I1111 02:50:41.227]   ports:
I1111 02:50:41.227]   - '8080'
```

**Comment by MrHohn** [comment]
> The other option is to change the jobs to not have anything listening on port 8080,8081

I guess that may be harder to change? I do wonder with more tests running pods in hostnetwork that bind to a host port, would we have increasing risk of conflicting ports? There isn't a central place to track the test ports and could be tricky to debug if random combination of tests run in parallel.

Or maybe running in hostnetwork is just a rarer special case that isn't too concerning?

/lgtm

**Comment by aojea** [comment]
/hold

> I guess that may be harder to change? I do wonder with more tests running pods in hostnetwork that bind to a host port, would we have increasing risk of conflicting ports? 

you are right, we should have a strategy here,

>There isn't a central place to track the test ports and could be tricky to debug if random combination of tests run in parallel.
> 

let me try a different approach, we can add an skipper based on the port availability, this way we can scale. I don't like th

> Or maybe running in hostnetwork is just a rarer special case that isn't too concerning?

it may be rare, but they are legit ... what we know for sure is that we don't have a good coverage :upside_down_face:

**Comment by aojea** [comment]
/hold cancel
@MrHohn what do you think about this approach?

**Comment by aojea** [comment]
/retest
sig-storage failures

**Review by MrHohn — APPROVED** [review]
Sorry for the delay, looks fine to me as the interim approach.
/lgtm
/approve

**Pull request merged**
