### PR TITLE
move GetPodSecretUpdateTimeout from framework/utils to test/e2e/framework/pod/

### PR DESCRIPTION
**Pull request by tanjunchen**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

ref:https://github.com/kubernetes/kubernetes/issues/77095

**Special notes for your reviewer**:

break up and simplify test/e2e/framework/utils.go , make it more common and helpful.
so this move function GetPodSecretUpdateTimeout to  test/e2e/framework/pod/

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Review by alejandrox1 — COMMENTED** [review]
Thank you @tanjunchen for finding this!
/approve
/lgtm

**Comment by oomichi** [comment]
Nice work

/lgtm

**Pull request merged**
