### PR TITLE
README examples updated

### PR DESCRIPTION
**Pull request by VivekBhat**
**What this PR does / why we need it**:
  - The table in the readme for /examples seemed broken. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
 - #43763 

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by VivekBhat** [comment]
I have signed the cla

**Comment by cblecker** [comment]
/assign
@VivekBhat: Please squash the commits (you have two with the same commit message)

**Comment by VivekBhat** [comment]
I have squashed the commits

**Comment by cblecker** [comment]
@k8s-ci-robot ok to test
/assign

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by supereagle** [comment]
LGTM

**Pull request merged**
