### PR TITLE
Fix golint failures of pkg/kubelet/checkpointmanager/checksum

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Fix golint failures of pkg/kubelet/checkpointmanager/checksum

**Which issue(s) this PR fixes**:

Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by SataQiu** [comment]
I have rebased the PR. Could you LGTM again? @yujuhong

**Review by fejta — COMMENTED** [review]
/lgtm

**Pull request merged**
