### PR TITLE
replace mesosphere PNG with up-to-date branding

### PR DESCRIPTION
**Pull request by air**
Hi @davidopp, replacing the Mesosphere logo as discussed on email. Thanks!

### CODE REVIEW

**Comment by air** [comment]
> CLA
I work for Mesosphere.

**Comment by davidopp** [comment]
LGTM

**Comment by davidopp** [comment]
@air I think you need to make your mesosphere.io email address public in your Github account to make the CLA bot happy in the future. Can you do that?

(We will still merge this, since you work for Mesosphere, but it's best to fix this so you don't have the problem in the future.)

**Comment by air** [comment]
Email now public. Thanks @davidopp

**Pull request merged**
