### PR TITLE
Use dedent for completion.go

### PR DESCRIPTION
**Pull request by lojies**
Use dedent for completion.go

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32104)

### CODE REVIEW

**Comment by lojies** [comment]
@janetkuo

**Comment by janetkuo** [comment]
ok to test

**Comment by lojies** [comment]
@janetkuo lgtm needed, thks.

**Comment by lojies** [comment]
@janetkuo

**Comment by lojies** [comment]
@janetkuo lgtm needed, thks.

**Comment by janetkuo** [comment]
sorry, missed this one, lgtm

**Pull request merged**
