### PR TITLE
kubenet: fix up CNI bridge TX queue length if needed

### LINKED ISSUE #25092: default htb qdisc configured on cbr0 sometimes drops all packets
I'm not sure where the defaults come from but they sometimes drop all packets causing container IPs to become unreachable. ARP fails.
```console
root@k-0-minion-c9mq:/home/mikedanese# tc qdisc replace dev cbr0 root htb
root@k-0-minion-c9mq:/home/mikedanese# ping 10.244.0.2                                                                                                                                                                                 
PING 10.244.0.2 (10.244.0.2) 56(84) bytes of data.
From 10.244.0.1 icmp_seq=1 Destination Host Unreachable
From 10.244.0.1 icmp_seq=2 Destination Host Unreachable
From 10.244.0.1 icmp_seq=3 Destination Host Unreachable
root@k-0-minion-c9mq:/home/mikedanese# tc -p -s qdisc show dev cbr0
qdisc htb 8001: root refcnt 2 r2q 10 default 0 direct_packets_stat 0 direct_qlen 0
 Sent 0 bytes 0 pkt (dropped 9, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0
root@k-0-minion-c9mq:/home/mikedanese# tc qdisc replace dev cbr0 root pfifo_fast
root@k-0-minion-c9mq:/home/mikedanese# ping 10.244.0.2                                                                                                                                                                                 
PING 10.244.0.2 (10.244.0.2) 56(84) bytes of data.
64 bytes from 10.244.0.2: icmp_seq=1 ttl=64 time=0.106 ms
64 bytes from 10.244.0.2: icmp_seq=2 ttl=64 time=0.066 ms
```
I'm not sure if this is related but I also noticed on this machine that the default pfifo qdisc drops all packets. pfifo is the default qdisc for an htb node so it's used in the unconfigured htb qdisc:
```console
root@k-0-minion-c9mq:/home/mikedanese# tc qdisc replace dev cbr0 root pfifo
root@k-0-minion-c9mq:/home/mikedanese# ping 10.244.0.2
PING 10.244.0.2 (10.244.0.2) 56(84) bytes of data.
From 10.244.0.1 icmp_seq=1 Destination Host Unreachable
From 10.244.0.1 icmp_seq=2 Destination Host Unreachable
From 10.244.0.1 icmp_seq=3 Destination Host Unreachable
root@k-0-minion-c9mq:/home/mikedanese# ping 10.244.0.2^C
root@k-0-minion-c9mq:/home/mikedanese# tc -p -s qdisc show dev cbr0
qdisc pfifo 8004: root refcnt 2 limit 0p
 Sent 0 bytes 0 pkt (dropped 18, overlimits 0 requeues 0) 
 backlog 0b 0p requeues 0 
```
This is because the default value for queue size is zero. On other machines I've seen the default value set to 1 packet and 1000 packets. When I set the limit explicitly the container becomes reachable again.
```console
root@k-0-minion-c9mq:/home/mikedanese# tc qdisc replace dev cbr0 root pfifo limit 1000
root@k-0-minion-c9mq:/home/mikedanese# ping 10.244.0.2                                                                                                                                               
PING 10.244.0.2 (10.244.0.2) 56(84) bytes of data.
64 bytes from 10.244.0.2: icmp_seq=1 ttl=64 time=0.078 ms
64 bytes from 10.244.0.2: icmp_seq=2 ttl=64 time=0.054 ms
```

The broken configuration is applied by kubelet to implement traffic shapping and there is no option to turn this off. This patch fixes the kubelet on broken machines by disabling traffic shapping:
https://gist.github.com/mikedanese/31d1e60e2659180fad4d352cce30dead

cc @dcbw @freehan @kubernetes/sig-network @kubernetes/goog-cluster

### PR DESCRIPTION
**Pull request by dcbw**
CNI's bridge plugin mis-handles the TxQLen when creating the bridge,
leading to a zero-length TX queue.  This doesn't typically cause
problems (since virtual interfaces don't have hard queue limits)
but when adding traffic shaping, some qdiscs pull their packet
limits from the TX queue length, leading to a packet limit of 0
in some cases.  Until we can depend on a new enough version of
CNI, fix up the TX queue length internally.

Closes: https://github.com/kubernetes/kubernetes/issues/25092

### CODE REVIEW

**Comment by dcbw** [comment]
@bprashanth @steveeJ

**Comment by dcbw** [comment]
@mikedanese give this a shot, does it fix the issue?

**Comment by mikedanese** [comment]
We should make a workaround-removal issue to track this. I'll test this out today. Thanks!

**Comment by mikedanese** [comment]
I verified this fix.

**Comment by freehan** [comment]
@dcbw I am seeing significant increase in failures within kubenet suite after this is merged.

**Comment by mikedanese** [comment]
https://github.com/containernetworking/cni/pull/199 is the upstream fix. Can you descibe the errors?

**Comment by freehan** [comment]
Here are the symptoms. Not all nodes ran into problem. When one node went into problematic state, cannot create/delete pod on that node. Kubelet crashed and restarted many times. And there are lots of martian source complains in kernel log.

FYI, one of the failure: 
http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce-kubenet/1557/consoleFull

**Comment by dcbw** [comment]
Can you copy & paste some of the failures in here?  I don't have access to that test job output.

**Comment by yujuhong** [comment]
@dcbw, the google storage bucket is public: https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce-kubenet/1557/

**Comment by dcbw** [comment]
@yujuhong is there any way I can get 'ip route' and 'ip addr' output from a machine that has the problem?

**Comment by yujuhong** [comment]
@dcbw, all the VM instances were already deleted at the end of the test. You may want to to reproduce this in your own GCE cluster.

**Comment by dcbw** [comment]
@yujuhong do you happen to know what IP range the minions get configured for their eth0 interface?  the martian packet kernel messages indicate there may be some IP range overlap between eth0 and cbr0.

**Comment by freehan** [comment]
The node ip usually starts from 10.240.0.2/24.

**Comment by dcbw** [comment]
@freehan Any chance you could point me to a test run without this commit, so I can compare the two?  Thanks!

**Comment by yujuhong** [comment]
This is the latest build from kubenet: https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce-kubenet/1773/

**Comment by freehan** [comment]
@dcbw The flakiness does not come up anymore. I notice there is also failures spikes in GCE suite (with default docker networking) around the same time. I think someone might have fixed it.

**Comment by freehan** [comment]
FYI, I did not revert this PR. I put the revert PR on hold. It was not merged.

**Comment by dcbw** [comment]
@freehan Ok, I'll keep poking around a bit more, let me know if/when any failures come up again.

**Comment by freehan** [comment]
@dcbw Thank you for jumping in!

**Pull request merged**
