### PR TITLE
sync default qps of kubelet change everywhere

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind cleanup
#### Which issue(s) this PR fixes:
follow up of  #116121

/assign @wojtek-t 

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Comment by wojtek-t** [comment]
/lgtm
/approve

/assign @lavalamp 
For api-approval

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Pull request merged**
