### PR TITLE
fix-staticcheck:pkg/volume/scaleio/

### PR DESCRIPTION
**Pull request by Aresforchina**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

ref:#81657

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by msau42** [comment]
/lgtm
/assign @BenTheElder 
for hack/ approval

**Comment by BenTheElder** [comment]
/approve
for hack/
sorry for the delay!

**Pull request merged**
