### PR TITLE
Convert ExpectEqual(err, nil) to ExpectNoError(err)

### LINKED ISSUE #85933: e2e_node tests are failing due to "Refusing to compare <nil> to <nil>"
**Which jobs are failing**:
kubernetes/node-problem-detector/node-problem-detector-ci: ci-npd-e2e-node
See the [Prow config](https://github.com/kubernetes/test-infra/blob/c08ecc49e1939e90f0aefad4dcab87e5fd5f0fa5/config/jobs/kubernetes/node-problem-detector/node-problem-detector-ci.yaml#L57)

**Which test(s) are failing**:
[k8s.io] NodeProblemDetector [NodeFeature:NodeProblemDetector] [k8s.io] SystemLogMonitor should generate node condition and events for corresponding errors

**Since when has it been failing**:
Dec 03. [Last green test](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-npd-e2e-node/1202072191361880066) was at 19:50 PST, [first red test](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-npd-e2e-node/1202102643455954945) was at 21:51 PST.

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-node-node-problem-detector#ci-npd-e2e-node

**Reason for failure**:

```
• Failure in Spec Setup (BeforeEach) [0.160 seconds]
[k8s.io] NodeProblemDetector [NodeFeature:NodeProblemDetector]
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:716
  [k8s.io] SystemLogMonitor
  /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:716
    should generate node condition and events for corresponding errors [BeforeEach]
    _output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_problem_detector_linux.go:246
    Refusing to compare <nil> to <nil>.
      
    Be explicit and use BeNil() instead.  This is to avoid mistakes where both sides of an assertion are erroneously uninitialized.
    _output/local/go/src/k8s.io/kubernetes/test/e2e_node/node_problem_detector_linux.go:107
```
Apparently [this](https://github.com/kubernetes/kubernetes/blob/d9ed6110e88e73da597cc03a38ee1357f9b67ed3/test/e2e_node/node_problem_detector_linux.go#L107) is the culprit.

**Anything else we need to know**:

This is likely caused by some library upgrade. Nothing big.

### PR DESCRIPTION
**Pull request by xueweiz**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation

/kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Convert `ExpectEqual(err, nil)` pattern to `ExpectNoError(err)` for all e2e tests.

**Which issue(s) this PR fixes**:

Fixes #85933

**Special notes for your reviewer**:

No behavioral change introduced.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by xueweiz** [comment]
This is to fix #85933 introduced by #85787

/cc @tanjunchen 
/cc @oomichi 
/cc @tallclair 
/cc @wangzhen127

**Comment by xueweiz** [comment]
I searched for regex pattern `.*ExpectEqual.*nil.*`, which should be an exhaustive list of all bugs related to #85933 , and fixed all the affected ones.

**Review by alejandrox1 — COMMENTED** [review]
This looks good!
/lgtm
/priority critical-urgent

**Comment by xueweiz** [comment]
#85787 was just reverted in #85931. I just rebased this patch on top of master to resolve conflict.

**Comment by bclau** [comment]
/lgtm

pretty simple PR, everything passes, no reason not to approve it.

**Comment by BenTheElder** [comment]
/lgtm
/approve
> /priority critical-urgent

hmm is it? :upside_down_face:

**Comment by xueweiz** [comment]
> hmm is it? 

:) it's no longer critical now.

It was critical yesterday, as many CIs were broken (#85933) due to #85787. The PR was reverted in #85931 later yesterday's night, and fixed the CIs. So it's no longer critical now.

**Pull request merged**
