### PR TITLE
Fixed typo in getting started documentation

### PR DESCRIPTION
**Pull request by hvolkmer**

### CODE REVIEW

**Comment by vmarmol** [comment]
LGTM, thanks @hvolkmer! As @googlebot said, when you have the time could you sign the CLA? We're ask to ask for it even for small changes like this.

**Comment by wojtek-t** [comment]
@hvolkmer - as @vmarmol said, we have to ask you for signing the CLA so that we can merge your PR. Can you please do sign it (the instructions for it are above)?

**Comment by vmarmol** [comment]
@hvolkmer will close this PR for now, but feel free to re-open :)

**Comment by hvolkmer** [comment]
I found the time to read and signed the CLA now. :)

**Comment by hvolkmer** [comment]
Created a new PR: #7363

**Comment by wojtek-t** [comment]
Thanks @hvolkmer - will take a look.

**Pull request closed without merging**
