### PR TITLE
Fix restore-from-backup.sh script

### PR DESCRIPTION
**Pull request by wojtek-t**

### CODE REVIEW

**Comment by shyamjvs** [comment]
Please change the name to etcd-version-monitor and then lgtm.

**Comment by wojtek-t** [comment]
I can't do it - it's what the name is.

**Comment by shyamjvs** [comment]
Sorry misunderstood.
/lgtm

**Comment by wojtek-t** [comment]
@k8s-bot etcd3 test this, issue: #28337

**Pull request merged**
