### PR TITLE
Fix golint failures - pkg/cloudprovider/providers/ovirt

### PR DESCRIPTION
**Pull request by saravanan30erd**
**What this PR does / why we need it**:
Fix golint failures - pkg/cloudprovider/providers/ovirt 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Ref #68026 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by saravanan30erd** [comment]
/assign @vishh 
please look on this

**Comment by saravanan30erd** [comment]
/assign @dims 
Could you please look on this?

**Comment by andrewsykim** [comment]
Would be good to get a review from someone who better understands this provider but seems like it has no OWNERs at the moment :(. PR looks good to me though, thank you @saravanan30erd! 

/approve
/lgtm

**Comment by nikhita** [comment]
/assign @cblecker 
for hack/ approval

**Comment by nikhita** [comment]
@saravanan30erd Could you squash the commits into a single commit?

**Comment by nikhita** [comment]
Re-adding lgtm
/lgtm

**Comment by cblecker** [comment]
/approve
for `hack/`

**Pull request merged**
