### PR TITLE
Fix mismatched types Verbose and bool

### PR DESCRIPTION
**Pull request by NickrenREN**
Fix invalid operation: mismatched types Verbose and bool

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by NickrenREN** [comment]
Simple test :

> nickren@nickren-ubuntu14:~/test/gotest$ cat types.go 
package main

import "fmt"

type Verbose bool

func main() {
     var a Verbose
     var b bool
     a = true
     b = true
     if a && b {
        fmt.Println("Yes")
     } else {
        fmt.Println("No")
     }      
}
nickren@nickren-ubuntu14:~/test/gotest$ go run types.go 
# command-line-arguments
./types.go:12: invalid operation: a && b (mismatched types Verbose and bool)
nickren@nickren-ubuntu14:~/test/gotest$

**Comment by NickrenREN** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by bsalamat** [comment]
/lgtm

@NickrenREN Nice catch! Thanks for the fix!

**Comment by NickrenREN** [comment]
ping @davidopp @timothysc @k82cn for approval

**Comment by k82cn** [comment]
@NickrenREN , how to trigger this within k8s?

The example makes sense, but `make WHAT=./plugin/cmd/kube-scheduler/` works; so I'd like to know why :).

**Comment by NickrenREN** [comment]
Sorry for the delay @k82cn . I do not know why the script does not trigger this neither.

**Comment by k82cn** [comment]
@NickrenREN , I'm OK with this PR. It's better to check it by tools, e.g. `go build` :). would you help to log an issue to trace that if you do not have time for it?

**Comment by NickrenREN** [comment]
@k82cn  Sure, done.  #48024

**Comment by CaoShuFeng** [comment]
I modified your example, and it runs happily:
`
package main

import "fmt"

type Verbose bool

func main() {
        var a Verbose
        var b int
        a = true
        if a && b == 0 {
                fmt.Println("Yes")
        } else {
                fmt.Println("No")
        }
}
`

**Pull request merged**
