### PR TITLE
api: remove useless json:",inline"

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

"inline" is not an option that encoding/json supports. These types happened to work as intended although "inline" was ignored because embedded structs get inlined by default.

Listing an option that doesn't do anything is confusing and probably has some small performance overhead (not measured), therefore it is better to remove it.

#### Special notes for your reviewer:

See also:
- https://github.com/IBM/portieris/pull/346
- https://github.com/golang/go/issues/6213
- https://kubernetes.slack.com/archives/C0EG7JC6T/p1680895221225319

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/cc @lavalamp

### CODE REVIEW

**Comment by pohly** [comment]
I can split this up if it helps with review or merging - not sure whether it would.

**Comment by pohly** [comment]
Several code generators depend on the json tag. I'll try to fix them.

**Comment by dims** [comment]
This work-in-progress PR needs a rebase. please rebase if this PR is still needed for the upcoming release.

**Comment by dims** [comment]
This work-in-progress PR needs a rebase. please rebase if this PR is still needed for the upcoming release.

**Comment by pohly** [comment]
/close

No time to finish this and perhaps not worth it...

**Pull request closed without merging**
