### PR TITLE
use Patch API to add namespace label

### LINKED ISSUE #100197: namespace update fails in AdmissionWebhook e2e tests
In VMware Tanzu Supervisor Cluster k8s setup, we observed that the AdmissionWebhook tests fail intermittently while updating the namespace with the error: "the object has been modified; please apply your changes to the latest version and try again". This is because the update conflicts with an update being performed by another controller.

The test could use Patch while adding labels via types.StrategicMergePatchType to prevent the conflict.

https://github.com/kubernetes/kubernetes/blob/9d59046ee5e1838363c84470cedf72be4ff69825/test/e2e/apimachinery/webhook.go#L2136

/sig testing
/sig api-machinery

### PR DESCRIPTION
**Pull request by chaitanyabandi**
Signed-off-by: Chaitanya Bandi <kbandi@cs.stonybrook.edu>

#### What type of PR is this?
/kind failing-test
/kind flake

#### What this PR does / why we need it:

Fixes how the namespace is labeled in AdmissionWebhook tests.
Avoids conflicts with other updates to the namespace.

#### Which issue(s) this PR fixes:

Fixes #100197

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chaitanyabandi** [comment]
@liggitt , thanks for adding the *ok-to-test* tag. Do you think this would be for milestone v1.22 when it exists?

**Comment by liggitt** [comment]
/lgtm
/approve
/priority important-longterm
/triage accepted
/milestone v1.21

test-only change that makes a conformance test more robust in a variety of environments

**Pull request merged**
