### PR TITLE
Move pkg/api/rest into genericapiserver

### PR DESCRIPTION
**Pull request by sttts**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by deads2k** [comment]
lgtm, squash bazel.

**Comment by sttts** [comment]
@k8s-bot kubemark e2e test this

**Comment by sttts** [comment]
@k8s-bot kubemark e2e test this

**Comment by sttts** [comment]
@k8s-bot test this

**Pull request merged**
