### PR TITLE
refactor WaitForWithContext

### PR DESCRIPTION
**Pull request by tkashem**
#### What type of PR is this?

/kind cleanup

#### Which issue(s) this PR fixes:
Fixes #

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cici37** [comment]
/assign @apelisse 
Would you mind to take a look when have time? Thanks
/triage accepted

**Comment by apelisse** [comment]
Why is this better? Why are you doing that? What problem are you trying to solve?

**Comment by tkashem** [comment]
my apology for not labeling the pr as WIP, i opened it for a discussion, we don't need it any longer

/close

**Pull request closed without merging**
