### PR TITLE
Admissionregistration nonnamespace

### PR DESCRIPTION
**Pull request by caesarxuchao**
The two types are root scoped.

Just adding a couple of tags. Other code is generated.

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Updated bazel.

**Comment by smarterclayton** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by caesarxuchao** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by caesarxuchao** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by smarterclayton** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (175/150 (116%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
------ The body of the message is 7867 characters long; only the first
------ 5000 or so are included here.
Received: from o5.sgmail.github.com ([192.254.113.10]:55363)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-5c7e-dev=imwiz.com@sgmail.github.com>)
	id 1dGU8G-000QTj-AC
	for dev@imwiz.com; Thu, 01 Jun 2017 11:43:36 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=h4HnkpLlbDq+mTYsWyonButGHTU=; b=k6RlU9f/TuJ0DTvV
	mZ8kHPUmDeOn2+AYD7SjpzpJ4bns4FJY6LJPuHr8Ttq4MHwyXXj3Wa13F11yzBav
	nmKG77djKhQ+ZugtPScNB1TtbUbaOJH0Bx3w0HI/W+sQGl1YUwAn2avfbKlPTA0H
	3JuGYOgOOYlW8bnu8WulDZ55Sy8=
Received: by filter0419p1mdw1.sendgrid.net with SMTP id filter0419p1mdw1-3201-5930523C-A
        2017-06-01 17:43:24.307608783 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id qNGYbwCqRO6OZrNO7LUI1Q
	for <dev@imwiz.com>; Thu, 01 Jun 2017 17:43:24.292 +0000 (UTC)
Date: Thu, 01 Jun 2017 10:43:23 -0700

**Comment by smarterclayton** [comment]
Hrm, the bot forgot about this.

**Comment by caesarxuchao** [comment]
@k8s-bot pull-kubernetes-verify test this

**Comment by caesarxuchao** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Pull request merged**
