### PR TITLE
use node hostname for pod while HostNetwork is true

### LINKED ISSUE #12893: Set pod hostname to node name if --net=host
Forked from #4825 - there seems to be no disagreement.  If a pod uses host networking, the host's UTS should be used, too (or at least hostname and domainname fields in the docker API).

This seems like a pretty easy change that just about anyone could make (hint hint)

### PR DESCRIPTION
**Pull request by wb14123**
This fixes #12893

### CODE REVIEW

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
LGTM. Is it possible to add a test for this @wb14123 ?

**Comment by thockin** [comment]
Isn't #12895 also solving this?

**Comment by ghodss** [comment]
Isn't this covered by #12895, since I thought using the UTS namespace of the host gives it the host's hostname in the container?

**Comment by vishh** [comment]
@thockin @ghodss: This is indeed a dup of #12895. Closing this PR. Sorry about the confusion @wb14123.

**Pull request closed without merging**
