### PR TITLE
Fix kubelet panic when accessing metrics/resource endpoint

### LINKED ISSUE #111136: kubelet panic when accessing metrics/resource endpoint
### What happened?

kubelet panic when accessing metrics/resource endpoint

kubelet log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x20de3cf]

goroutine 1055 [running]:
k8s.io/kubernetes/pkg/kubelet/metrics/collectors.(*resourceMetricsCollector).collectContainerCPUMetrics(0xc000df87c0, 0xc000f34ae0, 0xc0008f3340, 0x1b, 0xc000e80334, 0xb, 0xc0008f3360, 0x20, 0x1ce2f6d0, 0xeda4efe4f, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/metrics/collectors/resource_metrics.go:178 +0xcf
k8s.io/kubernetes/pkg/kubelet/metrics/collectors.(*resourceMetricsCollector).CollectWithStability(0xc000df87c0, 0xc000f34ae0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/metrics/collectors/resource_metrics.go:136 +0x318
k8s.io/kubernetes/vendor/k8s.io/component-base/metrics.(*BaseStableCollector).Collect.func1(0xc000df87c0, 0xc000f34ae0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/collector.go:83 +0x3e
created by k8s.io/kubernetes/vendor/k8s.io/component-base/metrics.(*BaseStableCollector).Collect
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/component-base/metrics/collector.go:82 +0x6b

```

### What did you expect to happen?

kubelet works fine

### How can we reproduce it (as minimally and precisely as possible)?

 access metrics/resource endpoint of kubelet

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
 kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"......", GitTreeState:"archive", BuildDate:".....", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:".........", GitTreeState:"archive", BuildDate:"........", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
INFO[2022-07-14 05:36:21.474173892Z] Starting CRI-O, version: 1.23.0, git: 9b7f5ae815c22a1d754abfbc2890d8d4c10e240d(dirty) 
Version:          1.23.0
GitCommit:        9b7f5ae815c22a1d754abfbc2890d8d4c10e240d
GitTreeState:     dirty
BuildDate:        1980-01-01T00:00:00Z
GoVersion:        go1.17.4
Compiler:         gc
Platform:         linux/amd64
Linkmode:         static
BuildTags:        apparmor, exclude_graphdriver_devicemapper, seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  true

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by yangjunmyfm192085**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix kubelet panic when accessing metrics/resource endpoint
#### Which issue(s) this PR fixes:

Fixes #111136

#### Does this PR introduce a user-facing change?

```release-note
 "NONE"
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by wzshiming — APPROVED** [review]
/lgtm

**Review by yangjunmyfm192085 — COMMENTED** [review]
/retest

**Review by yangjunmyfm192085 — COMMENTED** [review]
/retest

**Review by yangjunmyfm192085 — COMMENTED** [review]
/retest

**Comment by ialidzhikov** [comment]
@yangjunmyfm192085 can you backport to all effected versions? Thanks in advance!

**Comment by 249043822** [comment]
Have cherry-picked to 1.24 1.23 1.22

**Pull request merged**
