### PR TITLE
e2e-kind-cloud-provider-loadbalancer fixes, part 1

### PR DESCRIPTION
**Pull request by danwinship**
#### What type of PR is this?
/kind failing-test

#### What this PR does / why we need it:
Pulling out the definitely-right parts of #124371:

1. Make the "no UDP endpoints" behavior match the "no TCP endpoints" behavior. (Only assert "not reachable" rather than "ICMP reject".)
2. Bail out on the "source IP is preserved" tests if the cloud returns "Proxy"-type load balancers.

(The latter will hopefully be improved later, KEP-4361.)

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/sig network
/priority important-soon
/triage accepted
/assign @aojea

### CODE REVIEW

**Comment by aojea** [comment]
something weird happens with the affinity tests, it starts ok
```
I0514 23:58:00.423157 72774 utils.go:1097] Poke("http://172.18.0.6:80"): success
I0514 23:58:00.423195 72774 service.go:242] Received response from host: affinity-lb-transition-lzn7d
I0514 23:58:00.423210 72774 service.go:242] Received response from host: affinity-lb-transition-9jtlc
```

but suddenly is like it polling a different pod
```
I0514 23:58:15.506819 72774 utils.go:1097] Poke("http://172.18.0.6:80"): success
I0514 23:58:15.506868 72774 utils.go:1044] Poking "http://172.18.0.6:80"
I0514 23:58:15.515916 72774 utils.go:1097] Poke("http://172.18.0.6:80"): success
I0514 23:58:15.515948 72774 service.go:242] Received response from host: NOW: 2024-05-14 23:58:15.442459642 +0000 UTC m=+5.912911116
I0514 23:58:15.515960 72774 service.go:242] Received response from host: NOW: 2024-05-14 23:58:15.447083765 +0000 UTC m=+5.370207411
I0514 23:58:15.515969 72774 service.go:242] Received response from host: NOW: 2024-05-14 23:58:15.459644455 +0000 UTC m=+5.930095929
I0514 23:58:15.515977 72774 service.go:242] Received response from host: NOW: 2024-05-14 23:58:15.476969597 +0000 UTC m=+5.947421078
I0514 23:58:15.515986 72
```

instead of returning the hostname returns the timestamp, that is the default behavior of `agnhost netexec`, but the pods use `agnhost hostname` 🤔

**Comment by aojea** [comment]
hmm,  I think the possible problem is that the way to apply the config in cloud-provider-kind is to restart the container, and once it restarts it may not get the same ip ... and clients expect the loadbalancer ip to be stable across time 

I need to fix the envoy config restart, AFAIK it can be implementing the hot restart https://github.com/nathanbrock/hot-restarting-envoy or using dynamic configuration 🤔

**Comment by danwinship** [comment]
> something weird happens with the affinity tests

(but this PR doesn't change the affinity tests, so that's just an existing flake)

**Comment by aojea** [comment]
> > something weird happens with the affinity tests
> 
> (but this PR doesn't change the affinity tests, so that's just an existing flake)

this seems related to the flakes https://github.com/kubernetes-sigs/cloud-provider-kind/issues/66

**Pull request merged**
