### PR TITLE
Disk space check can return earlier without checking all the cases

### PR DESCRIPTION
**Pull request by ronnielai**

### CODE REVIEW

**Comment by vishh** [comment]
LGTM

**Comment by dchen1107** [comment]
LGTM

**Comment by Random-Liu** [comment]
@ronnielai Why did you close this one? :)

**Comment by ronnielai** [comment]
It's subsumed by #27209

**Comment by Random-Liu** [comment]
@ronnielai Ha, I see. A simple close description would be helpful~

**Pull request closed without merging**
