### PR TITLE
add deprecation comments to apps/v1beta2 types.go

### LINKED ISSUE #56868: No deprecation message for apps/v1beta2 core controllers and controller revision
**What happened**:
There is no deprecation message for `apps/v1beta2` core controllers and controller revision in `types.go`.

**What you expected to happen**:
There should be a deprecation message for each of the controllers and controller revision as they will be GA in v1.9 release.

### PR DESCRIPTION
**Pull request by crimsonfaith91**
**What this PR does / why we need it**:
This PR adds deprecation comments for `apps/v1beta2` statefulset, deployment, replicaset, daemonset, and controller revision in `types.go`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #56868

**Release note**:

```release-note
Deprecates apps/v1beta2 StatefulSet, Deployment, ReplicaSet, DaemonSet, and ControllerRevision.
```

### CODE REVIEW

**Review by janetkuo — APPROVED** [review]

**Comment by janetkuo** [comment]
`apps/v1beta2` shouldn't be capitalized. Changed to active voice in the release note.

**Comment by crimsonfaith91** [comment]
@janetkuo Thanks for the review and LGTM! :)

**Comment by crimsonfaith91** [comment]
@liggitt Do you mind to approve this PR?

**Comment by liggitt** [comment]
Are apps/v1beta1 marked deprecated as well?

**Comment by liggitt** [comment]
And to be clear, this doesn't mean we can remove these types/conversions until a migration mechanism is settled on and ensured to be run as part of upgrading

**Comment by crimsonfaith91** [comment]
@liggitt `apps/v1beta1` has been marked as deprecated 3 months ago via another PR. Yes, we can only remove the codes after 6 months or 2 releases based on this policy: https://kubernetes.io/docs/reference/deprecation-policy/.

**Comment by liggitt** [comment]
> we can only remove the codes after 6 months or 2 releases (whichever is longer) based on this policy

We can't remove the types and conversions until we have migrated all stored instances to newer versions

**Comment by crimsonfaith91** [comment]
> We can't remove the types and conversions until we have migrated all stored instances to newer versions

Got it! Thanks for the clarification!

**Comment by crimsonfaith91** [comment]
@janetkuo @liggitt 
Do you mind to add `priority/critical-urgent` label to this PR? I am not able to do so. Thanks!

**Pull request merged**
