### PR TITLE
WIP - build in module mode

### PR DESCRIPTION
**Pull request by liggitt**
xref https://github.com/kubernetes/kubernetes/issues/82531#issuecomment-781806805

builds on extracted PRs that can be reviewed/merged separately:
- [x] https://github.com/kubernetes/kubernetes/pull/104330
- [x] https://github.com/kubernetes/kubernetes/pull/104363
- [x] https://github.com/kubernetes/kubernetes/pull/105169
- [x] https://github.com/kubernetes/kubernetes/pull/105170
- [x] https://github.com/kubernetes/kubernetes/pull/105171
- [x] https://github.com/kubernetes/kubernetes/pull/105330
- [ ] https://github.com/kubernetes/kubernetes/pull/105408
- [ ] https://github.com/kubernetes/gengo/pull/215
- [ ] https://github.com/kubernetes/kubernetes/pull/105299

starting to flush out what fails

- [ ] go2make takes forever (known, discussing in https://github.com/golang/go/issues/31087#issuecomment-763176827)
  - takes ~6 seconds currently
  - takes ~20+ minutes on gomodules with current code
  - [ ] https://github.com/kubernetes/kubernetes/pull/105408 reduces time back to ~16 seconds
- [ ] https://github.com/kubernetes/gengo/pull/215
  - [x] gengo package loading is also extremely slow for the same reason
  - [x] gengo is hitting mismatches in dirs / import paths (with/without k8s.io/kubernetes/vendor prefix) - fixed in this PR by normalizing on import paths

### CODE REVIEW

**Comment by justaugustus** [comment]
WIP, but FYI @kubernetes/release-engineering

**Comment by liggitt** [comment]
looks like the kind build failure is coming from https://github.com/kubernetes-sigs/kind/blob/3e8741e4dc3a57ead78d63fa4cfa26d486690704/hack/ci/e2e-k8s.sh#L62 use of vendor paths instead of go paths

**Comment by enj** [comment]
/remove-sig auth

Feel free to tag SIG Auth back if we need to review this.

**Comment by dims** [comment]
please reopen if you still need this WIP PR. Trying to declutter the open PR(s)

**Pull request closed without merging**
