### PR TITLE
Chmod password and token files.

### LINKED ISSUE #7808: /srv/kubernetes/basic_auth.csv and /srv/kubernetes/known_tokens.csv on the master are world-readable

### PR DESCRIPTION
**Pull request by erictune**
Fixes #7808.

### CODE REVIEW

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Comment by mikedanese** [comment]
LGTM

**Comment by eparis** [comment]
#k8s-bot test this issue: #IGNORE

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

**Pull request merged**
