### PR TITLE
Add a container runtime mock for testing

### PR DESCRIPTION
**Pull request by yujuhong**

### CODE REVIEW

**Comment by yujuhong** [comment]
Forked from #17700

/cc @Random-Liu @yifan-gu

**Comment by yifan-gu** [comment]
LGTM

**Comment by yujuhong** [comment]
@k8s-bot test this

**Comment by yujuhong** [comment]
Applied lgtm based on https://github.com/kubernetes/kubernetes/pull/19392#issuecomment-169905970

**Comment by yujuhong** [comment]
@k8s-bot unit test this

**Comment by Random-Liu** [comment]
LGTM

**Comment by gmarek** [comment]
Failure: #19299
@k8s-bot test this

**Comment by gmarek** [comment]
@k8s-bot unit test this

**Comment by yujuhong** [comment]
@saad-ali would you mind manually merging this PR? This only modifies the unit test and will allow easier review for my other dependent PRs.

**Comment by saad-ali** [comment]
Sure. Merging now.

**Pull request merged**
