### PR TITLE
Include swaggerapi urls in system:discovery role

### PR DESCRIPTION
**Pull request by liggitt**
Used by client side API validation and for client schema generation

### CODE REVIEW

**Comment by deads2k** [comment]
> Used by client side API validation and for client schema generation

Does this include the swagger options things under `/apis`?

lgtm

**Comment by liggitt** [comment]
> Does this include the swagger options things under /apis?

Not sure what you're referring to

**Comment by zmerlynn** [comment]
@k8s-bot aws e2e test this

**Comment by zmerlynn** [comment]
@k8s-bot aws e2e test this

**Pull request merged**
