### PR TITLE
Fix kubeadm reset return code

### PR DESCRIPTION
**Pull request by drpaneas**
**What type of PR is this?**
Right now there are error happening while `kubeadm reset` runs. The error are visible due to `klog.Errorf`. Although they are not fatal, they are still error, thus I expect the final return code of the `kubeadm reset` to be a non-zero one. This doesn't happen atm:

```bash
 caasp-worker-panos-0:/home/sles # kubeadm reset --cri-socket /var/run/crio/crio.sock --force

 [preflight] Running pre-flight checks
 [preflight] Running pre-flight checks
 [reset] Stopping the kubelet service
 [reset] Unmounting mounted directories in "/var/lib/kubelet"
E0731 13:57:02.240390   10336 cleanupnode.go:82] [reset] Failed to remove containers: output: time="2019-07-31T13:57:02Z" level=fatal msg="failed to connect: --runtime-endpoint is not set"
, error: exit status 1
 [reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
 [reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim /var/run/kubernetes]
 The reset process does not reset or clean up iptables rules or IPVS tables.
 If you wish to reset iptables, you must do so manually.
 For example:
 iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
 
 If your cluster was setup to utilize IPVS, run ipvsadm --clear (or similar)
 to reset your system's IPVS tables.
 
 The reset process does not clean your kubeconfig files and you must remove them manually.
 Please, check the contents of the $HOME/.kube/config file.
  
 caasp-worker-panos-0:/home/sles # echo $?
 0
```

After applying this PR:

```
I0731 23:26:32.734955    9545 ssh.go:167] running command: "sudo sh -c 'kubeadm reset --cri-socket /var/run/crio/crio.sock --force '"
I0731 23:26:33.040880    9545 ssh.go:190] stderr | W0731 21:26:32.963089   11593 removeetcdmember.go:79] [reset] No kubeadm config, using etcd pod spec to get data directory
I0731 23:26:33.040905    9545 ssh.go:190] stdout | [preflight] Running pre-flight checks
I0731 23:26:33.040915    9545 ssh.go:190] stdout | [reset] No etcd config found. Assuming external etcd
I0731 23:26:33.040919    9545 ssh.go:190] stdout | [reset] Please, manually reset etcd to prevent further issues
I0731 23:26:33.040926    9545 ssh.go:190] stdout | [reset] Stopping the kubelet service
I0731 23:26:33.059928    9545 ssh.go:190] stdout | [reset] Unmounting mounted directories in "/var/lib/kubelet"
I0731 23:26:35.084668    9545 ssh.go:190] stderr | E0731 21:26:35.006202   11593 cleanupnode.go:87] [reset] Failed to remove containers: output: time="2019-07-31T21:26:35Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
I0731 23:26:35.084714    9545 ssh.go:190] stderr | , error: exit status 1
I0731 23:26:35.084706    9545 ssh.go:190] stdout | [reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
I0731 23:26:35.084747    9545 ssh.go:190] stderr | error execution phase cleanup-node: output: time="2019-07-31T21:26:35Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
I0731 23:26:35.084776    9545 ssh.go:190] stderr | , error: exit status 1
I0731 23:26:35.084774    9545 ssh.go:190] stdout | [reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
F0731 23:26:35.088733    9545 reset.go:50] error resetting node: failed to apply state kubeadm.reset: Process exited with status 1
tux@ultron:~/go/src/github.com/SUSE/skuba/ci/infra/openstack(fix_bsc_1142360)$ echo $?
255
```

/kind bug

**What this PR does / why we need it**:

For kubeadm wrapper (such as https://github.com/SUSE/skuba) it is expected to fetch the correct return codes from kubeadm when there's an error. Otherwise, there's false indication.

**Which issue(s) this PR fixes**:
I haven't created an issue.

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:
NONE

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
NONE

### CODE REVIEW

**Comment by neolit123** [comment]
>  Although they are not fatal, they are still error, thus I expect the final return code of the kubeadm reset to be a non-zero one.

i'd prefer if the errors are delivered as warnings instead (i.e. possibly change the klog context).
changing the return code to non-zero at this point can break existing setups.

/hold

**Comment by drpaneas** [comment]
> i'd prefer if the errors are delivered as warnings instead (i.e. possibly change the klog context).
> changing the return code to non-zero at this point can break existing setups.

most probably the existing setups are already broken -- they just don't know about it. Ignorance is a bless :P Indeed I can suppress the errors with warnings. That would mean `kubeadm reset` doesn't consider these _bad enough_.

I will `push` again. Thanks for your review.

**Comment by neolit123** [comment]
note to readers: this PR is replaced by https://github.com/kubernetes/kubernetes/pull/80862
which is waiting for more review.

**Comment by rosti** [comment]
> > i'd prefer if the errors are delivered as warnings instead (i.e. possibly change the klog context).
> > changing the return code to non-zero at this point can break existing setups.
> 
> most probably the existing setups are already broken -- they just don't know about it. Ignorance is a bless :P Perhaps we can merge this in the _next_ version and not the current?
> 
> Indeed I can suppress the errors with warnings. That would mean `kubeadm reset` doesn't consider these _bad enough_. In that case, do you think we have to change the documentation of the [kubeadm reset](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-reset/) as well?
> 
> ```
> - This command reverts any changes made by kubeadm init or kubeadm join.
> + This command might be able to revert some of the changes made by kubeadm init or kubeadm join.
> ```

The idea of kubeadm reset is to sweep as much as possible and just warn about things it couldn't cleanup. It does its best to try to cleanup the machine, however, not all reset steps can be executed sometimes.
For example, pods may have crashed, failed storage could prevent deleting some files, lost connectivity to the control plane...

**Comment by drpaneas** [comment]
> The idea of kubeadm reset is to sweep as much as possible and just warn about things it couldn't cleanup.

Ok, in that case I think we need to reflect this in the documentation as well. Right now it gives me the impression that `reset` is a binary operation, either succeeds or not; that is why I would expect a non-zero exit-code in case something went wrong through the cleanup process.

```
kubeadm reset --help
Run this to revert any changes made to this host by 'kubeadm init' or 'kubeadm join'

The "reset" command executes the following phases:

preflight              Run reset pre-flight checks
update-cluster-status  Remove this node from the ClusterStatus object.
remove-etcd-member     Remove a local etcd member.
cleanup-node           Run cleanup node.
```

If I understand correctly, the only _fatal_ errors would be:

```
update-cluster-status  Remove this node from the ClusterStatus object.
remove-etcd-member     Remove a local etcd member.
```

right? I can close this PR and prepare another one, updating the docs to reflect that mindset.

**Comment by ereslibre** [comment]
I don't think any operation on `kubeadm reset` should be fatal, meaning, even if any step fails we want to continue trying to clean, it's a best effort operation.

Having said that, it's not trivial to determine what error code should be returned by it. For example:`etcd` node removal: did it fail because it never joined (this should be a retcode of 0), or did it fail because it failed to remove the member? (maybe a retcode != 0).

For me the trickiest part is thinking about what cases should return != 0. E.g., if I ran `kubeadm reset` with an unprivileged user that wasn't able to remove the static manifests & secrets from the filesystem, maybe it would make sense to return an errcode != 0, but for the configmap & etcd logic I think this is a lot trickier.

**Comment by neolit123** [comment]
#80862 merged, i will close this PR but feel free to continue the discussion if needed.
hopefully with this feature https://github.com/kubernetes/kubeadm/issues/494
we will be able to distinguish the warnings from the rest of the output.

/close

**Comment by drpaneas** [comment]
> I don't think any operation on `kubeadm reset` should be fatal, meaning, even if any step fails we want to continue trying to clean, it's a best effort operation.

If you look closer at the code, there are `return err` statements which are pretty fatal. So, for me the first level of understanding is what is considered fatal and what's not. Otherwise, if nothing is fatal, maybe we need to fix those `return err` statements as well.

**Comment by ereslibre** [comment]
@drpaneas, hmm, I only can find it on the preflight phase when asking for confirmation (what makes sense). Every phase will always return `nil` (modulo the casting operations that should never fail).

**Pull request closed without merging**
