### PR TITLE
Fix typos and add comments in functions for `kubectl create` subcommands

### PR DESCRIPTION
**Pull request by sachinkumarsingh092**
Certain missing comments and typos in comments are fixed in the files
that implement `kubectl create` subcommands.

Hope these are the right labels!

**What type of PR is this?**
/kind cleanup /sig cli

**What this PR does / why we need it**:
FIxes typos and adds comments.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
/cc @dims

### CODE REVIEW

**Comment by dims** [comment]
@sachinkumarsingh092 while you are doing this ... can you fix all the golint failures in this package and remove the line from https://github.com/kubernetes/kubernetes/blob/master/hack/.golint_failures#L424 ?

See https://github.com/kubernetes/kubernetes/issues/72956 for more context

**Comment by sachinkumarsingh092** [comment]
I fixed all the linting errors around comments. The remaining linting errors are due to the name of the structs like this one in create_cronjobs.go with the struct named `CreateCronJobOptions`:
```
type name will be used as `create.CreateCronJobOptions` by other packages, and that stutters; consider calling this CronJobOptions
```
I talked to @soltysh and he suggested not to change the name as they are more readable the way they are. So should I just remove this package name from `/hack/.golint_failures`?

**Comment by dims** [comment]
yes, please remove this package name from /hack/.golint_failures

/ok-to-test

**Comment by liggitt** [comment]
the typo fixes and comment additions look fine, but this PR does not resolve all lint errors:

```
Errors from golint:
staging/src/k8s.io/kubectl/pkg/cmd/create/create.go:50:6: type name will be used as create.CreateOptions by other packages, and that stutters; consider calling this Options
staging/src/k8s.io/kubectl/pkg/cmd/create/create.go:342:6: type name will be used as create.CreateSubcommandOptions by other packages, and that stutters; consider calling this SubcommandOptions
staging/src/k8s.io/kubectl/pkg/cmd/create/create_clusterrole.go:65:6: type name will be used as create.CreateClusterRoleOptions by other packages, and that stutters; consider calling this ClusterRoleOptions
staging/src/k8s.io/kubectl/pkg/cmd/create/create_cronjob.go:53:6: type name will be used as create.CreateCronJobOptions by other packages, and that stutters; consider calling this CronJobOptions
staging/src/k8s.io/kubectl/pkg/cmd/create/create_deployment.go:60:6: type name will be used as create.CreateDeploymentOptions by other packages, and that stutters; consider calling this DeploymentOptions
staging/src/k8s.io/kubectl/pkg/cmd/create/create_ingress.go:105:6: type name will be used as create.CreateIngressOptions by other packages, and that stutters; consider calling this IngressOptions
staging/src/k8s.io/kubectl/pkg/cmd/create/create_job.go:56:6: type name will be used as create.CreateJobOptions by other packages, and that stutters; consider calling this JobOptions
staging/src/k8s.io/kubectl/pkg/cmd/create/create_role.go:123:6: type name will be used as create.CreateRoleOptions by other packages, and that stutters; consider calling this RoleOptions
```

we've declined to rename these in the past just to satisfy lint; I would suggest restoring the lint exception for this package

**Comment by sachinkumarsingh092** [comment]
@liggitt can I get a `/approve ` and `/lgtm` for it?

**Pull request merged**
