### PR TITLE
move well known cloud provider taints to k8s.io/cloud-provider/api

### PR DESCRIPTION
**Pull request by andrewsykim**
Signed-off-by: andrewsykim <kiman@vmware.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Moves well known cloud provider taints from `pkg/scheduler/api` to `k8s.io/cloud-provider/api`. This is part of an effort to remove internal deps in all cloud controllers so they can be moved to a staging repo.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
LGTM from sig-node perspective. I don't think we have any opinions around whether we import these values from `pkg/scheduler` or `pkg/cloud-provider`. It looks like we already depend on both :)

**Comment by cheftako** [comment]
Vendor Verify failed.
If you're seeing this locally, run the below command to fix your directories:
hack/update-vendor.sh

**Comment by ahg-g** [comment]
/approve 

for the scheduler changes.

**Review by cheftako — COMMENTED** [review]
/lgtm

**Comment by andrewsykim** [comment]
ref https://github.com/kubernetes/kubernetes/issues/81172

**Pull request merged**
