### PR TITLE
Migrate pkg/kubelet/cm/cgroup_manager_linux.go to structured logging

### PR DESCRIPTION
**Pull request by utsavoza**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Migrate the following files to structured logging:
- `pkg/kubelet/cm/cgroup_manager_linux.go`

#### Which issue(s) this PR fixes:

Part of #98976 

#### Special notes for your reviewer:
None

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

[KEP]: [Structured Logging](https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging)

/sig instrumentation
/sig node
/priority important-soon
/cc @ehashman

### CODE REVIEW

**Comment by BenTheElder** [comment]
failure appears unrelated
/skip

**Review by ehashman — COMMENTED** [review]
/lgtm

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
