### PR TITLE
kubeadm: fix "eliptic" typo in API package

### PR DESCRIPTION
**Pull request by neolit123**
/kind cleanup

#### What this PR does / why we need it:

Should be "elliptic".

#### Which issue(s) this PR fixes:

NONE

#### Special notes for your reviewer:
was found in this PR:
https://github.com/kubernetes/kubernetes/pull/121268

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by chendave — COMMENTED** [review]
/lgtm

**Review by pacoxu — COMMENTED** [review]
/lgtm

**Pull request merged**
