### PR TITLE
[OpenStack-Heat] Add link to the OpenStack CLI install documentation

### PR DESCRIPTION
**Pull request by sc68cal**
**What this PR does / why we need it**:

More helpful diagnostic text 

**Special notes for your reviewer**:

Trivial patch

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by sc68cal** [comment]
I signed it!

**Comment by sc68cal** [comment]
@k8s-ci-robot I signed it

**Comment by sc68cal** [comment]
@k8s-bot kubemark e2e test this

**Comment by roberthbailey** [comment]
@k8s-bot kubemark e2e test this

**Pull request merged**
