### PR TITLE
remove core repo dependency for `auth reconcile` command

### PR DESCRIPTION
**Pull request by juanvallejo**
/kind cleanup

Addresses part of https://github.com/kubernetes/kubectl/issues/80

```release-note
NONE
```

/sig cli

cc @soltysh @seans3

### CODE REVIEW

**Comment by juanvallejo** [comment]
Work in progress... Opening now to get feedback mainly on how to approach code duplication for `registry/rbac`

**Review by soltysh — APPROVED** [review]
The direction is good, can you update the PR, you're missing `hack/update-bazel.sh`.
/cc @liggitt I think Juan already mentioned you this one some time go, this is copying the functionality from `pkg/registry/rbac` and make a kubectl copy using external types

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/priority important-longterm

**Comment by liggitt** [comment]
That's a significant amount of duplication. What's the plan for avoiding drift? 

Is this required for 1.14?

/hold

**Comment by spiffxp** [comment]
v1.14 release lead here, this is a size/XXL PR that is attempting to land right before Code Freeze... are you _really sure_ this is a good idea?

Thanks for the /hold @liggitt

**Comment by soltysh** [comment]
> v1.14 release lead here, this is a size/XXL PR that is attempting to land right before Code Freeze... are you _really sure_ this is a good idea?

> Is this required for 1.14?

I'm sure, it's not required for 1.14. We'll need to do it eventually to be able to split kubectl out, though. Unless I hear a better option for solving this.

**Comment by liggitt** [comment]
The question at https://github.com/kubernetes/kubernetes/pull/74879#issuecomment-470513773 is still open. This is a really complex thing to duplicate. As-is, I'd put the chances of the two implementations staying in sync near zero.

The implications of this drifting are worse than human-readable printers not picking up a new field

We have a couple options:
1. relocate the covers/reconcile code to where it can be referenced by an out-of-tree kubectl
2. come up with a way to verify the kubectl copy of the impl doesn't drift

Option 1 is what I expected, and is why @deads2k switched the helpers to use external API types in https://github.com/kubernetes/kubernetes/pull/63967

**Pull request closed without merging**
