### PR TITLE
RFC: Remove restriction on probes' successThreshold

### PR DESCRIPTION
**Pull request by thockin**
LivenessProbe and StartupProbe demand SuccesssThreshold == 1.  Why?  The semantics seem clear for both.  The kubelet implementation seems to work fine.

IF we were to do this it would need a gate and a dark release to ensure rollback safety.

/kind cleanup
/kind api-change

```release-note
Pod `startupProbe`s and `livenessProbe`s may now set the `successThreshold` to values greater than 1. 
```

### CODE REVIEW

**Comment by aojea** [comment]
> F we were to do this it would need a gate and a dark release to ensure rollback

???🤔

**Comment by thockin** [comment]
@aojea - 1 release which tolerates but does not accept new uses of values > 1.  Now that I type that out, though...this is all about validation, it's probably just a gate

**Comment by aojea** [comment]
this is a similar precedent https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1972-kubelet-exec-probe-timeouts

**Comment by ehashman** [comment]
/hold

I don't understand the rationale behind this change, let's prevent it from accidentally getting merged.

**Comment by thockin** [comment]
@ehashman The goal was primarily to remove a place where a field exists but can't be used in some contexts.  It makes for confusing code and in this case, I didn't see any real value to the restriction.  Convincing or no?

**Comment by dims** [comment]
this PR has been on hold for about 2 weeks. Can you please see how to unblock this by reviewing comments etc? or please close this out (Trying to declutter our open list of PRs)

**Comment by thockin** [comment]
I'm doing some house-cleaning and realized I let this age-out.  Reviving it now.

The goal is simply this: less branches in our API docs, which cause users to have to think harder.  In this case, we were demanding that the value be exactly 1 but I am not sure I understand why this is important.

This PR is an RFC - to proceed it needs a KEP, probably, since there would be a gate involved.

**Comment by thockin** [comment]
FWIW, I would also like to see this type refactored so `.ProbeTerminationGracePeriod` does not appear in the type for Readiness, a la https://github.com/kubernetes/kubernetes/pull/105979

**Comment by bobbypage** [comment]
This change makes sense to me, but we should probably add some type of kubelet e2e to ensure that `successThreshold > 1` works (and does not regress) on the kubelet side.

**Comment by BenTheElder** [comment]
+1 re: https://github.com/kubernetes/kubernetes/pull/106025#issuecomment-1176952571 ... makes sense, definitely want a test.

I feel like you'll get more "RFC" traction circulating a KEP.

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by thockin** [comment]
Rebased.

@bobbypage can you help me craft an e2e for this?  There are unit tests which cover this already and there are lots of e2es in this area in test/e2e/common/node/container_probe.go but I can't find any that are checking that a probe took at least X time (e.g. set the startupProbe successThreshold to 5 with a period of 2 seconds and then ensure that at least 10 seconds have passed).

This is harder still with liveness - maybe it really doesn't make sense there?  For example, consider a pod with liveness failureThreshold = 2 and successThreshold = 2. 
* t0: live
* t1: passes liveness
* t2: passes liveness (unambiguously satisfying successThreshold)
* t3: fails liveness (no restart because failureThreshold is not met)
* t4: passes liveness (successThreshold is not met)
* t5: fails liveness

It has now failed twice: satisfying the failureThrteshold and not the successThreshold - does this get a restart, or is that just toooooo baroque?

**Comment by bobbypage** [comment]
Thanks @thockin, let me follow up and try to come up with an e2e test for this.

Regarding the second scenario, you mentioned: I was under the impression that `failureThreshold` was only considered if the failures were consecutive. So in the scenario you provided, at t4, the failure threshold would be "reset" and the second failure would not result in hitting the threshold.

**Comment by thockin** [comment]
> Regarding the second scenario, you mentioned: I was under the impression that failureThreshold was only considered if the failures were consecutive. So in the scenario you provided, at t4, the failure threshold counter would be "reset" and the second failure would not result in hitting the threshold.

That "reset" is because the successThreshold is required to be 1, which this PR breaks.  That's what I mean maybe it just doesn't make sense

**Comment by NovemberZulu** [comment]
Is there any chance we can revive this?

**Comment by thockin** [comment]
@NovemberZulu Can you say more about the issue you need solved?

**Comment by NovemberZulu** [comment]
We (an infra team) have an application on our hands that we want both to check often and ensure it is running stable. Increased `successThreshold` works fine with readiness probes, so we were going to do the same for liveness.

**Comment by thockin** [comment]
Lets think about the state-machine of liveness.  Assume failureThreshold=3

We tend to think of it like:

```
+-----------+     +---------+                 +-------+
|           |     |         |                 |       |
| (re)start |---->| unknown |--(succeed 1x)-->| alive |
|           |     |         |                 |       |
+-----------+     +---------+                 +-------+
     ^                                            |
     +-------- (fail 3x) -------------------------+
```

But really it's:

```
+-----------+     +---------+                 +-------+
|           |     |         |                 |       |
| (re)start |---->| unknown |--(succeed 1x)-->| alive |<---+
|           |     |         |                 |       |    |
+-----------+     +---------+                 +-------+    |
     ^                                            |        |
     |                                        (fail 1x)    |
     |              +---------+                   |        |
     |              |         |<------------------+        |
     +--(fail 2x)---| trouble |                            |
                    |         |--------(succeed 1x)--------+
                    +---------+
```

It's important to note that when a pod is in "trouble" it is still considered alive and running.  Traffic is still routed to it.

Suppose we allow to set successThreshold=5.  It's pretty clear what it means on the "unknown" to "alive" transition.  But what does it mean when you are currently in "trouble"?

Specifically, assume the probe passed and we're now "alive".  Then it fails once.  Now we are in "trouble".  Then it succeeds once.  Remember the successThreshold is 5, so we are still in "trouble".  It succeeds again, and again, for a total of 4.  Still "trouble".  Then it fails once.  Still in trouble,  It succeeds again 4 times.  Still trouble.

All that time, it stays alive.  I guess that would be true even today, it would just be "alive" instead of "trouble".  I don't think we represent "in trouble" anywhere in the API.

So, after writing that out, I guess I am not against it.  It's meaningful on the startup path, and "not worse" on the trouble path.  But I wonder if we could do better?

What if, while "in trouble" we tracked both the success count and fail count.  fail count is not reset until we transition out.  So looking at the above sequence again:

Specifically, assume the probe passed and we're now "alive".  Then it fails once.  Now we are in "trouble", with failCount=1.  Then it succeeds once, passCount=1. We are still in "trouble".  It succeeds again, and again, for a total of 4.  Still "trouble".  Then it fails once failCount=2, passCount resets to 0.  Still in trouble,  It succeeds again 4 times.  Still trouble.  passCount=4, failCount=2.  If it passes one more time, we can move back to "alive".  If it fails one more time, we restart.

It's more complex, but it means you don't stay in "trouble" forever.  Not sure it's what people would expect?   "My probe fails one out of 5 times, so it gets killed ever 15 probes"

**Comment by NovemberZulu** [comment]
Traffic is controlled by readiness probes -- and readiness probes have `successThreshold`. With that out of the way, I think the state machine is even _more_ complicated. This is what we have currently with `failureThreshold =3`:
[](https://mermaid.live/edit#pako:eNp1kD0LwjAQhv9KuEmhDu3YQSiIk5PSqXE4kosG00TSxCrqfzd-FFH0puO95x64O4NwkqAEZVwvtugDWyy5ZamWDYeRp3EXUsphzSaTKaubaHfW9Xb9hOpHeumiEESS5ccLqxo0-kAvoPoBfEwUavOI53lz7xPkrBjW5_nf_WH0FhSDIPT6bSj-G4ovQ7ocMmjJt6hlesr5znEIW2qJQ5laSQqjSe_g9ppQjMGtTlZAGXykDOJeYqCZxo3HFkqFpqPrDZbbbio)
A single success means we are alive.

I am thinking about something like this when `failureThreshold =3` and `successThreshold=3`:
[](https://mermaid.live/edit#pako:eNp9kjFvwyAQhf8KuqmVksGMHipFqjy1S6xMkAHBuUHFUGGoWyX57yXGbezULdPx7ntPJ44jSKcQSmiM6-VB-ECettySdLaMw53H-y4klcOerNcPZMeifbWut_sM7Qb11EUpERUpPk6kLth4TYKzEudoI7QZuKpgl3oO1cVCIJ0Ehl7_gieRuVEtpdz0rib6Pcc0u6L_RNCbiPHF6gXPhgmj338mpn9MvMn6wGbfTB95cjXAClr0rdAqLe940TiEA7bIoUylwkZEk9bG7TmhIgZXf1oJZfARVxDflAj4qMWLFy2UjTBdUlHp4Pxz_hDDvzh_Ab5zpUU)
We need three success in a row to become alive, if we got only one or two -- we are still in Limbo.
@thockin does that make sense to you?

**Comment by thockin** [comment]
Nice drawings.  In the first, I think we're saying the same thing, I just flattened your "failed" states into one.

> We need three success in a row to become alive, if we got only one or two -- we are still in Limbo.

That's the "obvious" behavior, but I don't love it.  Limbo is not good.  Repeated failures can be happening with no real visibility.

**Comment by NovemberZulu** [comment]
> That's the "obvious" behavior, but I don't love it. Limbo is not good. Repeated failures can be happening with no real visibility.

Fair point, but as far as I understand the current behaviour, one or two failures can happen, and the container is not restarted (assuming `failureThreshold=3`), i.e. if we allow `successThreshold=3`, we will not make the situation worse than it is now.

**Comment by thockin** [comment]
Help me understand what the operational benefit is for supporting `successThreshold` > 1 ?  Both of our drawings included states that don't exist as far as the API is concerned.

Today: as long as you succeed 1/N times (N being `failureThreshold`) your pod will not be killed.  Once you fail N times in a row, we will restart you.

If we implement this idea, what changes?  Unless you buy the more complex idea I wrote (I am not sure I buy it, myself), I think the observable state-machines are identical.

```
+-----------+     +-------+
|           |     |       |
| (re)start |---->| alive |<----+
|           |     |       |     |
+-----------+     +-------+ (succeed 1x)
     ^               |  |       |
     +-- (fail 3x) --+  +-------+
```

**Comment by thockin** [comment]
For `startupProbe` it at least makes sense - don't proceed to liveness/readiness checking until some initial condition passes N times.  It may not be meaningful to users, but it's consistent.  My original reason for opening this was to streamline the API spec and code, so at least for startup it could maybe go.

Assume `failureThreshold: 5` and `successThreshold: 3`

```
+-----------+     +----------+                 +---------+
|           |     |          |                 |         |
| (re)start |---->| starting |--(succeed 3x)-->| running |
|           |     |          |                 |         |
+-----------+     +----------+                 +---------+
     ^                 |
     +--- (fail 5x) ---+
```

It's still meaningless for `livenessProbe`, unless we change that semantic, and
I don't have any evidence that it is warranted.

From a code-simplicity POV, maybe one could argue that "meaningless" is OK if
it removes some special-case code/spec?

**Pull request closed without merging**
