### PR TITLE
Make one fluentd image and config for both GCI and CVM

### PR DESCRIPTION
**Pull request by crassirostris**
There're two different configs and two different pod specs for fluentd agent for GCL: one for GCI and one for CVM. This PR makes it possible to use only one config and only one pod spec.

Also it fixes the version of ruby and fluentd, rather than relying on treasure data debian package with a lot of unnecessary gems and documentation pages.

This PR also reduces the size of the image by 100MB.

CC @piosz

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37501)

### CODE REVIEW

**Comment by roberthbailey** [comment]
@Crassirostris - I assume you are ok with this not being part of the 1.5 release, right? (also re-assigning to @piosz -- note that if you know who you want to review your PR, you should just assign it to them rather than let the bot try to guess an appropriate reviewer).

**Comment by Crassirostris** [comment]
@roberthbailey Yes, true, thanks!

**Comment by piosz** [comment]
@roberthbailey thanks. Unfortunately @Crassirostris doesn't have permissions to do assignments.

**Comment by roberthbailey** [comment]
@piosz - maybe we can make the PR template has a "suggested reviewer" field and have the auto-assigner stick that person in the assignee field if they don't have permission.

**Comment by Crassirostris** [comment]
@roberthbailey That would be really great! I've troubled a lot of people with auto-assigning so far :)

**Comment by roberthbailey** [comment]
@Crassirostris can you file an issue and assign it to @pwittrock & @grodrigues3 (as they run the contribex sig) to get it on their radar?

**Comment by Crassirostris** [comment]
@roberthbailey Yes, thank you very much for pointing to the right direction!

**Comment by Crassirostris** [comment]
Talked with @piosz offline and decided to proceed with the other solution, saving this for a history though

**Pull request closed without merging**
