### PR TITLE
Add prometheus scrape port to CoreDNS service

### PR DESCRIPTION
**Pull request by rajansandeep**
**What this PR does / why we need it**:
Add prometheus scrape port

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #https://github.com/kubernetes/kubeadm/issues/955

**Special notes for your reviewer**:

**Release note**:

```release-note
Add prometheus scrape port to CoreDNS service
```

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm

**Comment by neolit123** [comment]
thanks @rajansandeep :+1:

**Comment by neolit123** [comment]
FYI, i'm pretty sure we want this fix for 1.11.1.

**Comment by rajansandeep** [comment]
Is there any process for that?
Or this automatically gets picked.

**Comment by neolit123** [comment]
it needs special labels from sig maintainers:
`cherrypick-candidate`
`priority/critical-urgent`
`status/approved-for-milestone`

**Review by luxas — APPROVED** [review]
/approve

Thanks!

**Comment by luxas** [comment]
@rajansandeep please cherrypick this against the release-1.11 branch

**Comment by rajansandeep** [comment]
@luxas done!
https://github.com/kubernetes/kubernetes/pull/65650

**Pull request merged**
