### PR TITLE
Delete "hugetlb" from whitelistControllers

### LINKED ISSUE #50770: kubelet set parameter --system-reserved work error.
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
In kubernetes 1.6.4, I configure kubelet with parameter ' --system-reserved=cpu=500m,memory=400Mi --system-reserved-cgroup=/system --enforce-node-allocatable=pods,system-reserved'. kubelet work failed, and output group /system not exist. 
the output kublet log is:
kubelet.go:1246] Failed to start ContainerManager Failed to enforce System Reserved Cgroup Limits on "/system": "/system" cgroup does not exist.

**What you expected to happen**:
kublet work well, and setting --system-reserved can isolate the resources reserved for system process.

**How to reproduce it (as minimally and precisely as possible)**:
run kubernetes 1.6.4 on fedora atomic 25. and setting the startup parameters(--system-reserved=cpu=500m,memory=400Mi --system-reserved-cgroup=/system --enforce-node-allocatable=pods,system-reserved) for kubelet process

**Anything else we need to know?**:
from the kubelet code v1.6.4, know it will first check --system-reserved-cgroup cgroup exist. the check way is see system.slice is exist in all subsystem.

check the fedora os, I can know
[fedora@fedora-atomic ~]$ sudo find /sys/fs/cgroup -name "system.slice"
/sys/fs/cgroup/memory/system.slice
/sys/fs/cgroup/devices/system.slice
/sys/fs/cgroup/pids/system.slice
/sys/fs/cgroup/cpu,cpuacct/system.slice
/sys/fs/cgroup/systemd/system.slice

and check the latest kubelet code, I find the code is like this
```
// Exists checks if all subsystem cgroups already exist
func (m *cgroupManagerImpl) Exists(name CgroupName) bool {
	// Get map of all cgroup paths on the system for the particular cgroup
	cgroupPaths := m.buildCgroupPaths(name)

	// the presence of alternative control groups not known to runc confuses
	// the kubelet existence checks.
	// ideally, we would have a mechanism in runc to support Exists() logic
	// scoped to the set control groups it understands.  this is being discussed
	// in https://github.com/opencontainers/runc/issues/1440
	// once resolved, we can remove this code.
	whitelistControllers := sets.NewString("cpu", "cpuacct", "cpuset", "memory", "hugetlb", "systemd")

	// If even one cgroup path doesn't exist, then the cgroup doesn't exist.
	for controller, path := range cgroupPaths {
		// ignore mounts we don't care about
		if !whitelistControllers.Has(controller) {
			continue
		}
		if !libcontainercgroups.PathExists(path) {
			return false
		}
	}

	return true
}
```
only check the  subsystem defined in whitelistControllers. But the default system, system.slice not exists in  hugetlb subsystem.

and more important, in kubelet, this is not relevant to hugetlb subsystem. I think can delete 'hugetlb' from the  whitelistControllers.

**Environment**:
- Kubernetes version (use `kubectl version`):kubernetes 1.6.4 
- Cloud provider or hardware configuration**:None
- OS (e.g. from /etc/os-release):
[fedora@test2 cgroup]$ cat  /etc/os-release
NAME=Fedora
VERSION="25 (Atomic Host)"
ID=fedora
VERSION_ID=25
PRETTY_NAME="Fedora 25 (Atomic Host)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:25"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=25
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=25
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
VARIANT="Atomic Host"
VARIANT_ID=atomic.host

- Kernel (e.g. `uname -a`):
Linux test2.novalocal 4.10.14-200.fc25.x86_64 #1 SMP Wed May 3 22:52:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by huzhengchuan**
**What this PR does / why we need it**:
Delete "hugetlb" from whitelistControllers

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50770

**Special notes for your reviewer**:

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by huzhengchuan** [comment]
cc @derekwaynecarr
I'd like you to do a code review, I see your comment about the 'whitelistControllers'.
Correct me if I am wrong. thanks!

**Comment by derekwaynecarr** [comment]
hugetlb is not yet natively supported by kubelet, but i will add support behind a feature flag here:
https://github.com/kubernetes/kubernetes/pull/50773

this is a fine change now though.  i will need to record a note to update the whitelist if the alpha feature is enabled in the linked pr.

**Pull request merged**
