### PR TITLE
Add client-server runtime support to local-up-cluster.sh

### PR DESCRIPTION
**Pull request by nhlfr**
**What this PR does / why we need it**: It provides support for using `--container-runtime-endpoint` and `--image-service-endpoint` arguments for kubelet in `local-up-cluster.sh` script.

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: ref #28789

**Special notes for your reviewer**:

**Release note**:

``` release-note
```

Provide support for --container-runtime-endpoint and
--image-service-endpoint in kubelet.

Ref #28789

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31339)

### CODE REVIEW

**Comment by feiskyer** [comment]
@nhlfr Thanks for adding this. lgtm.

**Comment by feiskyer** [comment]
ok to test

**Comment by euank** [comment]
LGTM as wel

**Comment by yujuhong** [comment]
@k8s-bot test this issue: #IGNORE

**Pull request merged**
