### PR TITLE
Run fluentd on the master to collect the core master logs

### LINKED ISSUE #10596: Run fluentd on the master to collect the master components' logs

### PR DESCRIPTION
**Pull request by a-robinson**
This involves adding the logging-write scope to the master VM when running on GCE.

It might be slightly less confusing if we used a separate image for this rather than tailing the master log files on all nodes, but fluentd is perfectly fine with being told to tail a file that doesn't exist, and it has no tangible effect on resource usage.

Fixes #10596.

### CODE REVIEW

**Comment by a-robinson** [comment]
cc @dchen1107

**Comment by zmerlynn** [comment]
Give me a risk assessment. I feel like we went down this route once before and ran into some weird bumpy road that led us to backing out fluentd on the master. Am I crazy?

**Comment by zmerlynn** [comment]
@k8s-bot: test this please

**Comment by a-robinson** [comment]
I don't remember going down this route before, and neither @dchen1107 nor @satnam6502 said they knew of any reasons not to do this, but is there something we're missing?

I'd mark this as low-medium risk, entirely due to adding slightly more resource usage to the master. @saad-ali, in your scalability testing in #5880, did you measure anything about fluentd on each node or just elasticsearch?

In a past life I measured fluentd's performance a fair amount, and while my numbers are a little out of date and weren't within a container, the least intensive benchmark I have recorded is that it only used 35MB of memory and 5% of an n1-standard-1 CPU when processing 1000 log lines per second. We shouldn't ever be hitting it with nearly that many logs on the master. Having fluentd around could exacerbate an issue like #10482, though.

**Comment by a-robinson** [comment]
@k8s-bot test this please

**Comment by satnam6502** [comment]
Have you already pushed the image with the 1.6 tag? I think it has over-written the 1.6 tag I was using for the namespace change which in the config changes `elasticsearch-logging.default` to `elasticsearch-logging`.

**Comment by a-robinson** [comment]
Done, sorry about the conflict!

**Comment by satnam6502** [comment]
Thanks for the quick action @a-robinson

**Comment by zmerlynn** [comment]
@a-robinson: I think I'm just crazy and misremembering. It sounds helpful.

**Comment by saad-ali** [comment]
@a-robinson For both https://github.com/GoogleCloudPlatform/kubernetes/issues/5880#issuecomment-113984085 and https://github.com/GoogleCloudPlatform/kubernetes/issues/10335#issuecomment-117340323 I measured the `fluentd-elasticsearch` container (defined [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/saltbase/salt/fluentd-es/fluentd-es.yaml)) which [runs](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Dockerfile) FluentD with the Elasticsearch plugin.

**Comment by a-robinson** [comment]
Thanks @saad-ali!

cc some combination of @dchen1107 @davidopp @alex-mohr for lead approvals

**Comment by davidopp** [comment]
I don't know Salt (and certainly not the fluentd config language) well enough to comment on this PR. Who is the best second reviewer besides @satnam? I'm fine with it once one other person who actually knows this stuff reviews it...

**Comment by alex-mohr** [comment]
LGTM -- only potential issue:
- what happens if logging api isn't enabled on a project?  fluentd fails gracefully?

**Comment by satnam6502** [comment]
Fleuntd issues a log warning in that case and carries on. We only log
errors so we should not have to worry about overflowing log files.

**Comment by davidopp** [comment]
LGTM if @satnam6502 and @alex-mohr and @a-robinson are all good with it, which appears to be the case...

**Comment by satnam6502** [comment]
My LGTM stands.

**Comment by a-robinson** [comment]
Before merging -- Satnam, I'm not actually convinced we'll drop them. It [looks like](https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/blob/master/lib/fluent/plugin/out_google_cloud.rb#L332) the plugin considers the API not being enabled as a retriable error, and we're explicitly disabling fluentd's retry limit in these configs. I think we may want to keep a retry limit of some sort so that we do eventually give up. I'll check into it a little closer.

**Comment by a-robinson** [comment]
So I refreshed my memory today about how buffered outputs work in fluentd. The memory (or disk, if using disk-based buffering) used is configurable based on the max buffer chunk size and the max number of buffer chunks. I'm adding a new commit to this PR to explicitly set these in all our configs. The default values (8MiB per chunk * 256 chunks) are high enough that they'll cause us to exceed the memory limit added in #10653.

**Comment by a-robinson** [comment]
This is now good from my perspective, so if you're happy with the new buffer settings @satnam6502, please re-add the ok-to-merge label.

**Comment by zmerlynn** [comment]
I would rather us start collecting logs ASAP. Merging and watching Jenkins.

**Comment by satnam6502** [comment]
I assume the `:1.6` image on gcr.io has been updated? Thanks.

**Comment by a-robinson** [comment]
Yes, both images should be updated with my last commit.

**Pull request merged**
