### PR TITLE
Remove scheduler/algorithm/priorities/util package

### LINKED ISSUE #86993: Remove scheduler/algorithm/priorities/util package [Migration Phase 2]
The logic should move to the plugins using the util logic, or to plugins/helper package if it is shared with multiple plugins.

/assign @Huang-Wei 
/sig scheduling
/priority important-soon
Part of #85822

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind cleanup
/sig scheduling

**What this PR does / why we need it**:

`non_zero.go` and `topologies.go` have been both moved to `scheduler/util` to eliminate the `scheduler/algorithm/priorities/util` package.

**Which issue(s) this PR fixes**:

Fixes #86993

**Special notes for your reviewer**:

- cannot move `non_zero.go` to `framework/plugins/helper` as it would cause cycling dependency (nodeinfo -> framework/plugins/helper -> framework/v1alpha1 -> listers -> nodeinfo)
- `topologies.go` is moved into `scheduler/util` is because other than "framework/plugins/interpodaffinity", "internal/queue" is also dependent on it, and "internal/queue" already depends on `scheduler/util`.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/cc @ahg-g

### CODE REVIEW

**Review by ravisantoshgudimetla — COMMENTED** [review]
/approve

Will wait for other to review

**Review by alculquicondor — COMMENTED** [review]
What should go in `/pkg/scheduler/util` vs `/pkg/scheduler/framework/plugins/helper`?

**Comment by Huang-Wei** [comment]
> What should go in `/pkg/scheduler/util` vs `/pkg/scheduler/framework/plugins/helper`?

IMO utilities needed by one plugin, it should go to that plugin package; if needed by multiple plugins, then `/pkg/scheduler/framework/plugins/helper`. And if it's used generally, it should go to `/pkg/scheduler/util`.

**Comment by alculquicondor** [comment]
> > What should go in `/pkg/scheduler/util` vs `/pkg/scheduler/framework/plugins/helper`?
> 
> IMO if the utilities are needed by **one plugin**, it should go to that plugin package; if needed by **multiple plugins**, then `/pkg/scheduler/framework/plugins/helper`. And if it's used generally in multiple packages, say not only by plugins, it should go to `/pkg/scheduler/util`.

In a quick first glance, it looks like some functions need re-location, but we can do that in follow ups.

/lgtm

**Pull request merged**
