### PR TITLE
Fix to not allow empty topology key when the feature AffinityInAnnotations is disabled.

### PR DESCRIPTION
**Pull request by aveshagarwal**
Fix https://github.com/kubernetes/kubernetes/issues/44360
@davidopp @kubernetes/sig-scheduling-pr-reviews

### CODE REVIEW

**Comment by bsalamat** [comment]
Thanks, @aveshagarwal. Could you please add a test for this scenario?

**Comment by wojtek-t** [comment]
The change looks ok - just please add a test for it.

**Comment by aveshagarwal** [comment]
@bsalamat @wojtek-t added tests. PTAL.

**Comment by davidopp** [comment]
Sorry for the last-minute comment. I would suggest removing the "when the feature AffinityInAnnotations is disabled" part of the error message. People might see this and enable the feature, when really we are deprecating it and don't want them to use it.

**Comment by aveshagarwal** [comment]
@davidopp @bsalamat fixed. PTAL.

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Pull request merged**
