### PR TITLE
[kubeadm] Remove usage of `PersistentVolumeLabel` in phases/controlplane/manifests*.go

### LINKED ISSUE #866: Remove usage of `PersistentVolumeLabel` in phases/controlplane/manifests*.go
This PR added usage of `--disable-admission-plugins=PersistentVolumeLabel` as an APIServer argument:
https://github.com/kubernetes/kubernetes/pull/64165
https://github.com/kubernetes/kubernetes/pull/64165/files#diff-366b1adfb12059a0ddf31d524e8827cbR145
it was done because we need to support 1.10 and because `--admission-control` is deprecated.

TODO (do this on a later stage in 1.11, not now)
remove `PersistentVolumeLabel` as it's will be automatically disabled in v1.11:

references:
kubernetes/kubernetes#64326
kubernetes/kubernetes#52618
kubernetes/kubernetes#52617

### PR DESCRIPTION
**Pull request by xlgao-zju**
**What this PR does / why we need it**:
Remove usage of `PersistentVolumeLabel` in phases/controlplane/manifests*.go

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Close [kubernetes/kubeadm#866](https://github.com/kubernetes/kubeadm/issues/866)

**Special notes for your reviewer**:
/assign @neolit123 

**Release note**:

```release-note
kubeadm: Remove usage of `PersistentVolumeLabel`
```

### CODE REVIEW

**Comment by neolit123** [comment]
seems good. thanks @xlgao-zju 

/assign @luxas 
/assign @timothysc 
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews

**Review by luxas — APPROVED** [review]
/lgtm
/approve
Thanks for this PR :tada:!

**Comment by neolit123** [comment]
@xlgao-zju
> @neolit123 I'd like to help more, any of other issues I can help?

much appreciated. :+1: 
you can give this one a shot, but feel free to ask questions in the issue:
https://github.com/kubernetes/kubeadm/issues/805

maybe @detiber and @chuckha have some potential tasks for you as well?

**Comment by neolit123** [comment]
we also have a lot of issues with `help wanted`:
https://github.com/kubernetes/kubeadm/issues?q=label%3A%22help+wanted%22

feel free to help us debug or fix some of the problems there!

**Pull request merged**
