### PR TITLE
remove deprecated /proxy paths

### PR DESCRIPTION
**Pull request by mikedanese**
These were deprecated in v1.2.
ref https://github.com/kubernetes/kubernetes/issues/59885
```release-note
kube-apiserver: the root /proxy paths have been removed (deprecated since v1.2). Use the /proxy subresources on objects that support HTTP proxying.
```

@kubernetes/sig-api-machinery-api-reviews

### CODE REVIEW

**Comment by liggitt** [comment]
> vendor/k8s.io/apiserver/pkg/endpoints/installer.go:243:30: isRedirector declared and not used

intent lgtm, likely requires test updates as well

**Comment by mikedanese** [comment]
I should probably get rid of rest.Redirector while I'm in here. New proxy storages implement rest.Connector

**Comment by mikedanese** [comment]
To review removal of conformance tests testing old proxy path:

/assign @smarterclayton

**Comment by smarterclayton** [comment]
/approve

Conformance removal is acceptable because these paths have been deprecated for 8 releases.

**Comment by bgrant0607** [comment]
LGTM, thanks

**Pull request merged**
