### PR TITLE
Multiarch nonewprivs test image

### LINKED ISSUE #50498: Multiarch nonewprivs test image
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

This issue is for creating `nonewprivs` image as multiarch

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:
This PR is for converting nonewprivs image which pushed very recently part of https://github.com/kubernetes/kubernetes/pull/47019.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Fixes #50498 
**Special notes for your reviewer**:

**Release note**:

```NONE```

### CODE REVIEW

**Comment by mkumatag** [comment]
ping @luxas @ixdy

**Comment by mkumatag** [comment]
@ixdy Can you please push these images?

**Comment by ixdy** [comment]
> @ixdy Can you please push these images?

Done.

**Pull request merged**
