### PR TITLE
Fix golint error in apiserver/plugin/pkg/authenticator/token/webhook

### PR DESCRIPTION
**Pull request by KobayashiD27**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix golint error in apiserver/plugin/pkg/authenticator/token/webhook/webhook.go

**Which issue(s) this PR fixes**:

part of #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/approve

(hack/ directory)

**Comment by KobayashiD27** [comment]
Ping @mikedanese
Could you review this PR?

**Comment by KobayashiD27** [comment]
/assign @liggitt 
Could you review this PR?

**Comment by liggitt** [comment]
thanks for the PR, but renaming exported types to satisfy lint is not generally worth the disruption to consumers

**Comment by KobayashiD27** [comment]
Thank you for your review.  
Do you mean this lint error need not to be fixed? However, in k/kubernetes code, I think this exported type is not referred. (https://github.com/kubernetes/kubernetes/search?q=WebhookTokenAuthenticator)
If my understanding is wrong, I'm sorry and I will close this PR.

**Comment by liggitt** [comment]
yeah, in this case, I would not change the exported type to satisfy lint

**Comment by KobayashiD27** [comment]
I see. Thank you for your comment.
/close

**Pull request closed without merging**
