### PR TITLE
[staging/apiextensions] StartTestServer: fix goroutine leak

### PR DESCRIPTION
**Pull request by gaurav1086**
Signed-off-by: Gaurav Singh <gaurav1086@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR fixes the goroutine leak possibly caused since its trying to write to the errCh and if the main routine returns before reading from the channel errCh: 

```
    client, err := kubernetes.NewForConfig(server.GenericAPIServer.LoopbackClientConfig)
    if err != nil {
        return result, fmt.Errorf("failed to create a client: %v", err)
    }  
```

**Which issue(s) this PR fixes**:

Fixes #
N/A
**Special notes for your reviewer**:
N/A
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by gaurav1086** [comment]
cc @sttts @liggitt

**Comment by gaurav1086** [comment]
cc @lavalamp

**Comment by lavalamp** [comment]
Do you have evidence that this goroutine actually leaks, or is it just theoretical?

*Please don't fix goroutine leaks by inserting a `, 1`*. This style of fix always turns a goroutine leak into an error (or other) value that is never examined. The goroutine leak is at least visible. The unexamined error is not visible. So, this style of fix makes things worse. There's (thus far in my experience) always a better way. I'm sorry to be a little blunt here. But I have seen a number of these changes from you, and even though I feel like I say some variation of this in every one, I guess I haven't been clear enough: please don't fix things like this, even in first drafts.

**Comment by gaurav1086** [comment]
@lavalamp thanks for the pointers. However this an old PR. I will close this one and re-open another one with an alternative solution. Thanks.

**Comment by fedebongio** [comment]
@gaurav1086 did you reopen this on purpose? I thought it was closed in the past. Could you clarify? 
Thanks!

**Comment by gaurav1086** [comment]
@fedebongio Reopened this mistake. Closing.

**Pull request closed without merging**
