### PR TITLE
add unit test case for nodenames comparison

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
ref https://github.com/kubernetes/kubernetes/pull/60486

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
please merge it after https://github.com/kubernetes/kubernetes/pull/60486

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
Thanks!  Another battle scar supporting the need for good unit tests :)

/approve no-issue
/lgtm

**Comment by zhangxiaoyu-zidif** [comment]
@jdumars
I will appreciate it if we can release it with 1.10, many thanks!

**Comment by jdumars** [comment]
@zhangxiaoyu-zidif can you please message me on Slack (@jdumars) as soon as #60486 is merged, and all tests are passing?  I'll let this in, but please be mindful of code freeze in the future.

**Comment by zhangxiaoyu-zidif** [comment]
@jdumars 
OK, no problems! I will call you. thanks.

**Pull request merged**
