### PR TITLE
StatefulSet e2e: verify stateful pod hostname

### PR DESCRIPTION
**Pull request by janetkuo**
cc @erictune @foxish @kubernetes/sig-apps

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36022)

### CODE REVIEW

**Comment by foxish** [comment]
LGTM

**Comment by erictune** [comment]
lgtm

**Comment by soltysh** [comment]
@k8s-bot node e2e test this `Build Still Running!`

**Comment by kow3ns** [comment]
@k8s-bot node e2e test this

**Pull request merged**
