### PR TITLE
Automated cherry pick of #63270: remove format operation in WaitForAttach

### PR DESCRIPTION
**Pull request by feiskyer**
Cherry pick of #63270 on release-1.9.

#63270: remove format operation in WaitForAttach

### CODE REVIEW

**Comment by feiskyer** [comment]
/sig azure
/kind bug

/assign @andyzhangx @khenidak

@andyzhangx Could you verify whether the cherry pick is reasonable?

**Comment by andyzhangx** [comment]
This PR depends on https://github.com/kubernetes/kubernetes/pull/64684 merge into v1.9 first.
/hold

**Comment by feiskyer** [comment]
#64684 is only for windows, seems on direct dependency?

**Comment by andyzhangx** [comment]
@feiskyer this PR will remove format func in Azure module, thus lead to azure disk on windows not work(no format func). So we need to add format func in mount_windows.go first.

**Comment by feiskyer** [comment]
#64684 merged now. ping @andyzhangx

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Comment by feiskyer** [comment]
ping @brendandburns for approval

**Comment by feiskyer** [comment]
ping @brendandburns @rootfs for approval

**Comment by mbohlool** [comment]
/hold

1.9 branch is frozen for the release.

**Comment by feiskyer** [comment]
ping @brendandburns @rootfs for approval

**Pull request merged**
