### PR TITLE
Build hyperkube in hack/local-up-cluster instead of separate binaries

### PR DESCRIPTION
**Pull request by luxas**
This speeds up the build time a lot. 
Also add arm64 as a valid arch

This is quite trivial. Let's get it in asap
@thockin @pmorie @liggitt @eparis @zmerlynn @smarterclayton

### CODE REVIEW

**Comment by luxas** [comment]
This isn't covered by e2e

**Comment by smarterclayton** [comment]
Part of the purpose of hack/local-up-cluster is to validate that the individual components start cleanly (i.e., to test cmd/kube-apiserver/... in isolation).  I wouldn't necessarily expect us to make this change until we were adding hyperkube to the core setup.

**Comment by luxas** [comment]
Okay, understand that.
Can I create an option for it?

**Comment by smarterclayton** [comment]
On the other hand, the only place local up is used is to assist local development, and if hyperkube is faster then I think that's more important.  E2e probably covers the other entry point sufficiently.  So I think this is a net win.

**Comment by luxas** [comment]
Maybe we should add a release note for this so people notice that it has changed?

**Pull request merged**
