### PR TITLE
kube-proxy react on Node PodCIDR changes

### PR DESCRIPTION
**Pull request by code-elinka**
Cherry pick of #113247 on release-1.24.

#113247: service update event should be triggered when appProtocol

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
kube-proxy, will restart in case it detects that the Node assigned pod.Spec.PodCIDRs have changed
```

### CODE REVIEW

**Comment by aojea** [comment]
this commit should not be here [service update event should be triggered when appProtocol in port is …](https://github.com/kubernetes/kubernetes/pull/113252/commits/ddc62aa3682d931b0a6473c034541f32d583c112)

**Comment by code-elinka** [comment]
> this commit should not be here [service update event should be triggered when appProtocol in port is …](https://github.com/kubernetes/kubernetes/pull/113252/commits/ddc62aa3682d931b0a6473c034541f32d583c112)
> 
> [ddc62aa](https://github.com/kubernetes/kubernetes/commit/ddc62aa3682d931b0a6473c034541f32d583c112)
> 
> /hold

Done, I dropped unrelated changes.

**Comment by aojea** [comment]
/retitle kube-proxy react on Node PodCIDR changes

**Comment by aojea** [comment]
/lgtm
/approve
ping @kubernetes/release-managers

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Comment by sftim** [comment]
My suggestion for the changelog text:
```markdown
`kube-proxy` will now restart if it detects changes to the `.spec.podCIDRs` field of its node
```
What do we mean by “restart”? Do we mean “exit”, and then the restart is implicit?

**Comment by aojea** [comment]
> What do we mean by “restart”? Do we mean “exit”, and then the restart is implicit?

yeah, it will really exit, the restart is the implicit, :/

**Pull request merged**
