### PR TITLE
Set minimum memory limits to be 4MB for docker driver

### PR DESCRIPTION
**Pull request by vishh**
Resurrecting #9519

Improve node e2e testing along the way

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/23156)

### CODE REVIEW

**Comment by vishh** [comment]
@pwittrock: Take a look at the node tests

**Comment by vishh** [comment]
@k8s-bot test node e2e experimental

**Comment by vishh** [comment]
@k8s-bot test node e2e experimental

**Comment by dchen1107** [comment]
Actually I like the initial proposal #9519 made by @brendandburns, and I only asked him to update the API description in the original pr. :-) 
I think setting minimum memory limits for all runtimes, not just docker is the right way to go.

**Comment by vishh** [comment]
This is a docker limitation. It is not applicable to all runtimes. Applying these limit validations to the API is painful to rollout.

**Comment by dchen1107** [comment]
I know this is docker limitation, but it do have the reason. The number is actually align with what we are having with our internal system. :-)

**Comment by vishh** [comment]
Runc does not have this limitation anymore. Its been fixed in the recent
past. It is just a matter of time (I hope) before the daemon drops this.
Can we get done with this quick fix for now and re-visit this if it really
is a limitation for rkt, hyper, etc?

**Comment by vishh** [comment]
Ping @dchen1107

**Comment by dchen1107** [comment]
@k8s-bot e2e test this please

**Comment by dchen1107** [comment]
k8s-bot test this issue: #IGNORE

**Comment by vishh** [comment]
@dchen1107 I fixed the e2es. PTAL

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
Still fail node e2e ...

**Pull request closed without merging**
