### PR TITLE
Automated cherry pick of #122261: Add unit test for Job Controller for panic when PodFailurePolicy is used

### PR DESCRIPTION
**Pull request by mimowo**
Cherry pick of #122261 on release-1.28.

#122261: Add unit test for Job Controller for panic when PodFailurePolicy is used

Note:  manually adjusted `ptr` to `pointer`, and removed in the assert `expectedReady`, because `jobReadyPodsEnabled` was false in the test in 1.28.

**Motivation**:

I consider it an important unit test to cherry-pick because it should go in tandem with the fix in
https://github.com/kubernetes/kubernetes/pull/121147, which is now cherry-picked
to 1.28: https://github.com/kubernetes/kubernetes/pull/122267.

This scenario was not initially attributed to the fix, but it turns out it causes Job controller
panics on 1.28: https://github.com/kubernetes/kubernetes/issues/122235.

```release-note

```

### CODE REVIEW

**Comment by mimowo** [comment]
cc @kannon92

**Comment by kannon92** [comment]
/kind bug
please add a release note.

**Comment by alculquicondor** [comment]
/approve
/cc kubernetes/release-managers

Note that this is a follow up to https://github.com/kubernetes/kubernetes/pull/122267.

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
