### PR TITLE
Cherry pick: Remove gcloud components update from e2e.sh

### PR DESCRIPTION
**Pull request by spxtr**
#18846

### CODE REVIEW

**Comment by spxtr** [comment]
Reassigned since @jlowdermilk is out. This is a cherry pick of #18897.

**Comment by ihmccreery** [comment]
LGTM.

**Comment by spxtr** [comment]
@k8s-bot e2e test this please

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by gmarek** [comment]
@k8s-bot unit test this

**Pull request merged**
