### PR TITLE
fix typo "udp" -> "UDP"

### PR DESCRIPTION
**Pull request by zgfh**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
fix a typo
```
kubectl expose deploy test1 --port=4100 --protocol=udp --name=video-stream
The Service "video-stream" is invalid: spec.ports[0].protocol: Unsupported value: "udp": supported values: "SCTP", "TCP", "UDP"
```
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by poothia** [comment]
lgtm

**Review by neolit123 — APPROVED** [review]
thanks for the PR.
/priority backlog
/lgtm

**Comment by nikhita** [comment]
/assign @soltysh 
for approval

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
