### PR TITLE
Remove manifest copies from Trusty support

### PR DESCRIPTION
**Pull request by andyzheng0831**
This change revises the way to provide kube-system manifests for clusters on Trusty. Originally, we maintained copies of some manifests under cluster/gce/trusty/kube-manifests, which is not scalable and hard to maintain. With this change, clusters on Trusty will use the same source of manifests as ContainerVM. This change also fixes some minor problems such as shell variables and comments to meet the style guidance better.

### CODE REVIEW

**Comment by andyzheng0831** [comment]
@dchen1107 please review it. This is the change I talked with you offline for improvement.

cc/ @roberthbailey @wonderfly

**Comment by andyzheng0831** [comment]
Found 'illegal' flags usage. Update the file hack/verify-flags/exceptions.txt in the new version using "hack/verify-flags-underscore.py -e > hack/verify-flags/exceptions.txt". Not sure why several lines not related my changes are removed by the script.

**Comment by andyzheng0831** [comment]
Rebase done

**Comment by andyzheng0831** [comment]
@dchen1107 , do you mind to take a look?

**Comment by andyzheng0831** [comment]
Done for rebase.

@dchen1107 and @roberthbailey please take a look if you have time.

**Comment by roberthbailey** [comment]
lgtm, but waiting for @dchen1107 to take a look before applying the lgtm label

**Comment by dchen1107** [comment]
LGTM

**Pull request merged**
