### PR TITLE
Fix broken link for common.sh

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind domumentation

#### What this PR does / why we need it:

The link is broken.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Thanks!
/lgtm
/ok-to-test

**Comment by sanposhiho** [comment]
For approve
/assign @lavalamp

**Pull request merged**
