### PR TITLE
modify the error url of autoscaler

### PR DESCRIPTION
**Pull request by timyinshi**
What type of PR is this?
/kind documentation
/sig docs

What this PR does / why we need it:
the url is 404:https://github.com/kubernetes/autoscaler/releases/tag/1.12.0 t
the right url is: https://github.com/kubernetes/autoscaler/releases/tag/cluster-autoscaler-1.12.0

Which issue(s) this PR fixes:

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

NONE
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```release-note
NONE
```

### CODE REVIEW

**Comment by hwdef** [comment]
/lgtm
/ok-to-test
Thanks for your contribution.

**Comment by lavalamp** [comment]
/approve

(I edited your PR description to fix the release note section)

**Comment by tanjunchen** [comment]
ref:https://github.com/kubernetes/kubernetes/issues/85495

**Pull request merged**
