### PR TITLE
Extend authentication webhook to pass extra headers in addition to Bearer token 

### PR DESCRIPTION
**Pull request by alexblyzn**
Extend webhook authenticator to take headers from request and pass to authenticator interface.
Google GKE authenticator implementation needs extra information in addition to bearer token to authenticate and later authorize the request. This PR contains a generic implementation allowing admins to list what headers(if any) they want to include in token review call.

### CODE REVIEW

**Comment by cjcullen** [comment]
@liggitt @deads2k thoughts? This is the "extra header" token authenticator stuff we had briefly talked about.

**Comment by liggitt** [comment]
I'm not immediately sold on it, but we can discuss it more (probably after 1.6 freeze). The current API mirrors the `authentication.Token` interface, which has really bounded inputs/outputs. I wouldn't want to expand one without the other, and I'm hesitant to change the interface. This would also affect the kubelet token auth delegation and cacheability of the webhook. 


cc @kubernetes/sig-auth-api-reviews

**Comment by cjcullen** [comment]
Another option would be to plumb request headers directly into the `Extra` of the SubjectAccessReview (which is where we need them anyway). That wouldn't require changing any types, but feels a little more spaghetti-ish code-wise.

**Comment by cjcullen** [comment]
I think we are going to go a different route with this. Closing.

**Pull request closed without merging**
