### PR TITLE
[WIP] prototyping service.spec.includeTerminating

### PR DESCRIPTION
**Pull request by andrewsykim**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Experimenting with an alternative approach to the existing ProxyTerminatingEndpoints alpha feature, where instead of automatically falling back to terminating endpoints in specific scenarios (externalTrafficPolicy=Local), we allow the Service to indicate whether terminating endpoints should be included in the entire set of endpoints based on their readiness.

Some advantages of this change are:
* Simpler to reason about as a user. Terminating and non-terminating endpoints are more or less treated the same based on their actual readiness.
* Simpler kube-proxy implementation. The implementation of this feature also becomes a lot simpler because it's just a matter of checking the "ready" condition or the "serving" condition in kube-proxy. We no longer have to implement a fall-back mechanism based on # of endpoints available in each condition.
* Safer. Because we're not changing any default behavior, it is safer to introduce. A user can try to enable "includeTerminating" to see if their workloads can handle traffic on termination and always disable it if there are issues.

The disadvantages would be:
* API Bloating/Complexity. We would be bloating an already bloated API like Service.
* More onus on users. We are pushing the responsibility to users to enable this capability and possibly update their workloads based on how they're workloads should handle terminating endpoints. 

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
TBD
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by fedebongio** [comment]
let us know when it's ready for review
/triage accepted

**Review by thockin — COMMENTED** [review]
I'll look more deeply soon, but my initial reaction is that this is the stuff we DON'T want to put in a user's face.  I'm struggling to find a case where it's actually a bad thing to do automatically, and you know how I feel about APIs - less is more.

**Comment by danwinship** [comment]
I think we decided against this?

**Pull request closed without merging**
