### PR TITLE
kubeadm init phase for apiserver does not accept multi valued flag in…

### LINKED ISSUE #1413: kubeadm init phase for apiserver does not accept multi valued flag in extra-args
BUG REPORT 
## Versions
**kubeadm version** (use `kubeadm version`):
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:36:44Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
Hardware
- **Kubernetes version** (use `kubectl version`):

- **Cloud provider or hardware configuration**:
Hardware: 1x1 cluster. 8 cpu, 16 GB memory

- **OS** (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
- **Kernel** (e.g. `uname -a`):
3.10.0-693.2.2.el7.x86_64

## What happened?
executing `kubeadm init phase control-plane apiserver --apiserver-extra-args "enable-admission-plugins=LimitRanger,NamespaceExists"` throwing following error.

```
 error: invalid argument "enable-admission-plugins=LimitRanger,NamespaceExists" for "--apiserver-extra-args" flag: malformed pair, expect string=string
````

`apiserver-extra-args` expects map[string]string which will be comma separated nameX=valueX pairs.
however the `enable-admission-plugins` is a multi valued flag for api-server. so kubeadm errors out if the value of the flag is multi valued as shown in example above.

## What you expected to happen?
`kubeadm init phase control-plane apiserver` flag `--apiserver-extra-args` should be able to accept extra args with multi valued flag.

## How to reproduce it (as minimally and precisely as possible)?
Fail: execute with multi valued flag. `kubeadm init phase control-plane apiserver --apiserver-extra-args "enable-admission-plugins=LimitRanger,NamespaceExists"`

Pass: execute with single valued flag. `kubeadm init phase control-plane apiserver --apiserver-extra-args "enable-admission-plugins=LimitRanger"`

## Anything else we need to know?
After little bit exploring the code:
 The flag `--apiserver-extra-args` is instance of MapStringString (https://github.com/kubernetes/apiserver/blob/master/pkg/util/flag/map_string_string.go#L30) with `NoSplit=false` which will not accept multi valued flag.
The flag initialization: https://github.com/kubernetes/kubernetes/blob/release-1.13/cmd/kubeadm/app/cmd/options/generic.go#L49

Please also suggest if there is any work around until this issue is resolved.

### PR DESCRIPTION
**Pull request by RA489**
kubeadm init phase for apiserver does not accept multi valued flag in extra-args 
fixes https://github.com/kubernetes/kubeadm/issues/1413

### CODE REVIEW

**Review by rosti — CHANGES_REQUESTED** [review]
@RA489 thanks for picking that up, but this is not at all the solution to the original problem. In fact, currently it will only break stuff and the function you are modifying is not invoked by kubeadm.

Let's get back to the issue for discussing this.

/hold

**Comment by RA489** [comment]
@rosti Thanks! for the review .

**Comment by neolit123** [comment]
yes, let's close as we have a different problem here.
we either need a new flag (+flag value parser) or instruct the users to only use config for this.
/close

**Pull request closed without merging**
