### PR TITLE
[WIP] apiextensions: add integration test for GC

### PR DESCRIPTION
**Pull request by nikhita**
Two CRs are created such that one of them owns the other. Delete the owner and the dependent should also get deleted. However this does not happen currently (even after polling).

/cc @sttts 

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by sttts** [comment]
@caesarxuchao @deads2k is this already supposed to work?

**Comment by sttts** [comment]
@k8s-bot ok to test

**Comment by sttts** [comment]
This is probably necessary: https://github.com/kubernetes/kubernetes/pull/46000

**Comment by nikhita** [comment]
Will update this once https://github.com/kubernetes/kubernetes/pull/47665 is merged.

**Comment by nikhita** [comment]
@sttts Rebased and updated.

#47665 has been merged but this still does not work. Can you take a look at the test to check if anything is wrong? Or is the case - two CRs are created such that one of them owns the other - not supported?

**Comment by nikhita** [comment]
Closing since https://github.com/kubernetes/kubernetes/pull/47665 already has tests.

**Pull request closed without merging**
