### PR TITLE
Pass proxy environment variables to static pods

### LINKED ISSUE #36573: kube-controller-manager with AWS cloud provider crash loop if using http_proxy using "kubeadm init --cloud-provider aws"
**Is this a request for help?** No

**What keywords did you search in Kubernetes issues before filing this one?** http proxy, http_proxy, https_proxy, AWS, kubeadm, kubectl, cloud-provider

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Kubernetes version** (use `kubectl version`): v1.4.4
```
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:48:38Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.4", GitCommit:"3b417cc4ccd1b8f38ff9ec96bb50a81ca0ea9d56", GitTreeState:"clean", BuildDate:"2016-10-21T02:42:39Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

kubeadm version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.2.421+a6bea3d79b8bba", GitCommit:"a6bea3d79b8bbaa5e8b57482c9fff9265d402708", GitTreeState:"clean", BuildDate:"2016-11-03T06:54:50Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: kubeadm on EC2 instances on AWS
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS
- **Kernel** (e.g. `uname -a`): Linux ip-10-0-133-99 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm
- **Others**: _http_proxy_, _https_proxy_ and _no_proxy_ set in /etc/environment, Docker config as well on startup scripts that run `kubeadm init`

**What happened**:
`kubeadm init --cloud-provider aws` won't complete and gets stuck on it's first deployment.  When one looks through the logs it shows that the pods are downloading fine but we are stuck due to the kube-controller-manager continually crashing as it can't contact AWS.  Elsewhere in kubernetes I see references to `http.ProxyFromEnvironment` and if the AWS cloud provider could use that it would be able to connect as well.  From the POD if I manually set http_proxy and https_proxy and no_proxy I am able to use the AWS CLI without any issues.

```
root@ip-10-2-221-240:/home/ubuntu# kubectl logs kube-controller-manager-ip-10-2-221-240 --namespace=kube-system
E1108 13:58:14.493903       1 event.go:258] Could not construct reference to: '&api.Endpoints{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"kube-controller-manager", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]api.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:""}, Subsets:[]api.EndpointSubset(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' '%v became leader' 'ip-10-2-221-240'
I1108 13:58:14.494179       1 leaderelection.go:214] sucessfully acquired lease kube-system/kube-controller-manager
I1108 13:58:14.499388       1 aws.go:745] Building AWS cloudprovider
I1108 13:58:14.499484       1 aws.go:699] Zone not specified in configuration file; querying AWS metadata service
I1108 13:58:14.499651       1 replication_controller.go:219] Starting RC Manager
I1108 13:58:14.605138       1 endpoints_controller.go:326] Waiting for pods controller to sync, requeuing service default/kubernetes`

[10:25]  
I1108 15:24:09.602100       1 endpoints_controller.go:326] Waiting for pods controller to sync, requeuing service default/kubernetes
I1108 15:24:09.602100       1 endpoints_controller.go:326] Waiting for pods controller to sync, requeuing service default/kubernetes
I1108 15:24:09.602100       1 endpoints_controller.go:326] Waiting for pods controller to sync, requeuing service default/kubernetes
I1108 15:24:09.602100       1 endpoints_controller.go:326] Waiting for pods controller to sync, requeuing service default/kubernetes
....
F1108 15:24:09.625221       1 controllermanager.go:227] Cloud provider could not be initialized: could not init cloud provider "aws": error finding instance i-052a60ad4cc805154: error listing AWS instances: RequestError: send request failed
caused by: Post https://ec2.us-west-1.amazonaws.com/: dial tcp 176.32.118.53:443: i/o timeout
```

**What you expected to happen**:
I would expect `kubeadm init --cloud-provider aws` to successfully complete and use the environment proxies set up on the system so as not to depend on a default Internet Gateway being connected to the VPC just for AWS access.

**How to reproduce it** (as minimally and precisely as possible):
- Set up a public VPC with Squid set up as a proxy
- Set up a private VPC peered to the public VPC
- Set up a master node and run `kubeadm init --cloud-provider aws`
- Set up a regular node and run `kubeadm join`

`kubeadm` will never fully initialize.  If you remove the --cloud-provider aws` then it will complete and nodes will register.

**Anything else do we need to know**:

### PR DESCRIPTION
**Pull request by kad**
**What this PR does / why we need it**:

To access outside world or cloud provider APIs it might be
required to use proxy. kubeadm will be passing proxy variables to static pods during init stage.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes kubernetes/kubernetes#36573, kubernetes/kubeadm#5

**Special notes for your reviewer**:

**Release note**:
```release-note
- kubeadm will pass proxy environment variables to static pods.
```

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37494)

### CODE REVIEW

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by luxas** [comment]
@kad Have you tested this manually and verified it's working?
As a follow-up, you could add unit tests for this, but not now since we don't want it to conflict with the unit test PR that's already up

**Comment by kad** [comment]
@luxas I only verified that those are properly passed to written manifests and doesn't conflict with usual installation of k8s in my lab cluster.
I provided prebuilt binary linked in kubernetes/kubeadm#5 for @druidsbane (originator of the issue) to verify that it works in his environment, but no answer so far.

**Comment by mikedanese** [comment]
We should just add unit tests now. The rebase should be simple.

**Comment by kad** [comment]
@mikedanese we don't have unit tests for generating manifests at all now. Rebase is not an issue... adding bit that is touched by this PR to unit test for writing manifests is also fine. But writing whole set of unit tests for static manifests seems like out of scope for this particular PR, which intended to solve only  kubernetes/kubernetes#36573. This should be done as separate PR.

**Comment by druidsbane** [comment]
@kad thanks for this, I will test it out, hopefully that will fix the underlying issue!

**Comment by druidsbane** [comment]
@kad @mikedanese I've tested this and commented here https://github.com/kubernetes/kubeadm/issues/5#issuecomment-264571961 on the possibility that it should be enabled through a flag.  It works great for what I need though.  kubelet also needs its own configuration but that is in addition to this fix.  Thanks!

**Comment by luxas** [comment]
@k8s-bot gce etcd e2e test this

**Comment by luxas** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by luxas** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by kad** [comment]
```
error dialing jenkins@i.do.not.exist: 'dial tcp: missing port in address i.do.not.exist', retrying
```
something broken in Jenkins setup ?

**Comment by kad** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by luxas** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by luxas** [comment]
If tests are passing, I'm gonna add lgtm

**Comment by luxas** [comment]
@k8s-bot cvm gce e2e test this

**Comment by luxas** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by luxas** [comment]
LGTM, thanks

**Comment by luxas** [comment]
@k8s-bot unit test this

**Comment by luxas** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by luxas** [comment]
@k8s-bot unit test this

**Comment by deads2k** [comment]
flaked on https://github.com/kubernetes/kubernetes/issues/38198

**Comment by luxas** [comment]
@k8s-bot unit test this

**Comment by luxas** [comment]
Unit has now flaked three times in a row...
etcd3 flaked once so far

**Comment by luxas** [comment]
@k8s-bot unit test this

**Comment by luxas** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by luxas** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
