### PR TITLE
Remove feature label from Indexed Job E2E test

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

To allow the test to run during presubmit and other suites.
IndexedJob is graduating to beta in this release.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

**Review by ravisantoshgudimetla — APPROVED** [review]
Test available at https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102012/pull-kubernetes-e2e-gce-ubuntu-containerd/1395756561485271040/

/lgtm

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/priority backlog

**Pull request merged**
