### PR TITLE
kubeadm: use etcd 3.5.11's /livez and /readyz endpoints for probes

### LINKED ISSUE #3039: Change etcd liveness probes to the new livez and readyz endpoints
This is related to https://github.com/etcd-io/etcd/issues/16007

Since v3.5.11, etcd has added [new livez/readyz HTTP endpoints](https://github.com/etcd-io/etcd/blob/main/CHANGELOG/CHANGELOG-3.5.md#v3511-2023-12-07)
The design for the new probes is documented in [etcd livez and readyz probes](https://docs.google.com/document/d/1PaUAp76j1X92h3jZF47m32oVlR8Y-p-arB5XOB7Nb6U/edit?usp=sharing)

The new probes are Kubernetes API compliant, have more fine-grained metrics, and are better suited for liveness and readiness checks than  `/health?exclude=NOSPACE&serializable=true`, and `/health?serializable=false`

| Probe | endpoint used by kubeadm | endpoint proposed to use | difference |
| ------ | --------------------------- | -------------------------- | ---------- |
| LivenessProbe | `/health?exclude=NOSPACE&serializable=true` | `/livez` | `/livez` does not check for leaders because restarting local server does not mitigate the problem of cluster missing leader, while a crashing loop would worsen the problem. |
| StartupProbe | `/health?serializable=false` | `/readyz` | `/readyz` ignores the `NOSPACE` alarm, because if the local server is out of quota, the server is still able to take read/delete requests, and still able forward write requests to the leader to write successfully in the cluster. | 
| ReadinessProbe | None | `/readyz` | |

We should switch the current etcd `LivenessProbe` and `StartupProbe` to the new endpoints which are Kubernetes API compliant.

## Is this a BUG REPORT or FEATURE REQUEST?

FEATURE REQUEST

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?

Add a unit test to block on this.

/kind feature

#### What this PR does / why we need it:

etcd >= 3.5.11 includes new endpoints for liveness, startup
and readyness probes. Use them in 1.31.

there is another commit here:

There is no point to track more than 3 etcd versions at a time
where each etcd versions maps to a k8s CP version.

It's 3 instead of 2 (k8s CP / kubeadm version skew size) because
there is a period of time where the 3rd version (newest) will
be WIP at k/k master - e.g. at the time of this commit it's 1.31.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/3039

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: switch to using the new etcd endpoints introduced in 3.5.11 - /livez (for liveness probe) and /readyz (for readyness and startup probe). With this change it is no longer possible to deploy a custom etcd version older than 3.5.11 with kubeadm 1.31. If so, please upgrade.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by SataQiu — COMMENTED** [review]
/lgtm
/hold 
feel free to cancel hold

**Comment by neolit123** [comment]
> New changes are detected. LGTM label has been removed.

fixed merge conflict after etcd was just bumped to 3.5.13

**Review by neolit123 — COMMENTED** [review]
@SataQiu PTAL again for LGTM
after i fixed merge conflict.

**Comment by ahrtr** [comment]
/lgtm
/approve

The change is straightforward, looks good to me.

**Comment by neolit123** [comment]
kind presubmit e2e passed, lets see how it goes in the kubeadm e2e tests.
should be good.

/hold cancel

**Pull request merged**
