### PR TITLE
Fix golint failures of test/e2e/autoscaling

### PR DESCRIPTION
**Pull request by s-ito-ts**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This fixes golint failures of the following file:
- test/e2e/autoscaling/autoscaling_timer.go
- test/e2e/autoscaling/cluster_autoscaler_scalability.go
- test/e2e/autoscaling/cluster_size_autoscaling.go
- test/e2e/autoscaling/custom_metrics_stackdriver_autoscaling.go
- test/e2e/autoscaling/dns_autoscaling.go
- test/e2e/autoscaling/framework.go
- test/e2e/autoscaling/horizontal_pod_autoscaling.go

**Which issue(s) this PR fixes**:
Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/ok-to-test
/priority backlog

/assign @oomichi

**Comment by s-ito-ts** [comment]
I rebased to resolve conflicts.
Could you review again?

**Comment by oomichi** [comment]
/lgtm

Thanks for doing this.

**Review by fejta — COMMENTED** [review]
/approve

**Pull request merged**
