### PR TITLE
Remove Ingress-GCE upgrade + downgrade tests from k/k

### PR DESCRIPTION
**Pull request by rramkumar1**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
We have similar tests in k/ingress-gce now that we block releases on so there is no point in having these too. 

https://github.com/kubernetes/test-infra/pull/11638 removed the prow jobs so the tests are no longer running. 

```release-note
None
```

/assign @bowei

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm

**Comment by rramkumar1** [comment]
@spiffxp Can we get this in the 1.14 milestone?

**Comment by spiffxp** [comment]
From https://github.com/kubernetes/test-infra/pull/11638
>We have similar tests now in k/ingress-gce that we use to block releases so there is no reason for these to hang around.

Where can I see these tests running?

**Comment by spiffxp** [comment]
After offline chat:
- tests are defined here: https://github.com/kubernetes/ingress-gce/blob/master/cmd/e2e-test/upgrade_test.go
- tests are run internally in Google and not on prow.k8s.io
- there's no immediate urgency to remove this prior to v1.14.0 and this can wait until v1.14.1 or v1.15 as needed

**Comment by spiffxp** [comment]
/priority important-longterm
/lgtm
to go in once code freeze is lifted

**Pull request merged**
