### PR TITLE
promote PodTolerationRestriction admission controller annotations to stable

### PR DESCRIPTION
**Pull request by colemickens**
**What this PR does / why we need it**:
* promotes the `PodTolerationRestriction` admission controller and annotations to stable, per discussion on #57424
* PodTolerationRestriction: `scheduler.alpha.kubernetes.io/defaultTolerations` is deprecated in favor of `scheduler.kubernetes.io/default-tolerations`
* PodTolerationRestriction: `scheduler.alpha.kubernetes.io/tolerationsWhitelist` is deprecated in favor of `scheduler.kubernetes.io/tolerations-whitelist`
* for both annotations, both are considered and merged, per discussion on #57424
* adds tests showing the alpha and stable annotations are merged and considered correctly
* adds v1 Configuration api, tests for it
* **NOTE:** This stacks on top of: https://github.com/kubernetes/kubernetes/pull/59367

**Which issue(s) this PR fixes**: Partially addresses #57424 (the other half, addressing `PodNodeSeelctor` is #60284).

Corresponding Docs PR: https://github.com/kubernetes/website/pull/7135 (This will be updated again to discuss the versioned config, etc).

**Release note**:

```release-note
* PodTolerationRestriction: `scheduler.alpha.kubernetes.io/defaultTolerations` is deprecated in favor of `scheduler.kubernetes.io/default-tolerations`
* PodTolerationRestriction: `scheduler.alpha.kubernetes.io/tolerationsWhitelist` is deprecated in favor of `scheduler.kubernetes.io/tolerations-whitelist`
* PodTolerationRestriction: support for `v1` plugin configuration is added. support for `v1alpha1` plugin configuration is deprecated.
```

cc: @ericchiang @liggitt

### CODE REVIEW

**Comment by ericchiang** [comment]
```
W0223 09:09:15.524]     raise CalledProcessError(retcode, cmd)
W0223 09:09:15.525] subprocess.CalledProcessError: Command '('bazel', 'version')' returned non-zero exit status 37
E0223 09:09:15.530] Command failed
```
/test pull-kubernetes-bazel-build

**Comment by timothysc** [comment]
/assign @bsalamat 

You'd need to promote pretty much all of taints and tolerations imo.

**Comment by bsalamat** [comment]
@timothysc We cannot promote all the techniques that use taints and tolerations in one release. There are other usages such as tainting nodes by condition which are not fully stable and will remain in alpha, while the actual API of taints and tolerations go to GA in this release.

**Comment by gmarek** [comment]
FWIW I agree with @bsalamat

**Comment by colemickens** [comment]
So does PodTolerationRestriction need to wait for *all* of taints and tolerations to go GA, or is the API moving to stable sufficient for promoting the admission controller?

**Comment by bsalamat** [comment]
@colemickens The admission controller for PodTolerationRestriction can go to GA with Taints and Tolerations API if it is tested enough and we are confident that it is stable.

**Comment by lavalamp** [comment]
Same comments as #60284. Stable features should not be using annotations like this, I think. Has this been debated? Why is this api machinery?

**Comment by colemickens** [comment]
Apologies, sig-scheduling is probably more appropriate. Shall we discuss this usage of annotation on the original issue about promotion to stable #57424 so we can discuss it as it applies to both this PR and #60284? (Is the alternative to "using annotations this way" simply to put all configuration into the admission controller plugin configuration?)

/sig scheduling

**Comment by bsalamat** [comment]
+1 to @lavalamp's point about using annotations. There was a [similar proposal in this doc](https://docs.google.com/document/d/1HjAE8Aky3ebyHcbxIMkwaITBcz9j5-cCA21wBuUWoyA) and @bgrant0607 raised concerns about using annotations to convey policy. I believe we should design a policy object (CRD) to restrict certain properties that affect scheduling of Pods.

I totally agree with Brian that:
"I would like to see a policy API specifying constraints on scheduling properties admins would like to control, such as:
* allowed priority classes
* allowed tolerations
* required node selectors/affinity
* allowed pod anti-affinity
* required/allowed schedulers"

**Comment by bsalamat** [comment]
Should we close this PR?

**Comment by yastij** [comment]
To me this should be closed.

**Pull request closed without merging**
