### PR TITLE
fix: typo in stateful_set_control

### PR DESCRIPTION
**Pull request by draveness**
**What type of PR is this?**

/kind documentation

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — APPROVED** [review]
thаnks.

/lgtm
/priority backlog
/ok-to-test

**Comment by draveness** [comment]
Hi @neolit123, it still requires approved to be merged 🤣

**Comment by neolit123** [comment]
> Hi @neolit123, it still requires approved to be merged

true, it's up to the maintainers at this point.

**Comment by draveness** [comment]
@neolit123 I see, thanks

**Comment by draveness** [comment]
ping @enisoc @ foxish for approval

**Comment by dims** [comment]
/assign @smarterclayton 

Clayton, simple typo! PTAL

**Pull request merged**
