### PR TITLE
Revise wording for Secret stringData field

### PR DESCRIPTION
**Pull request by sftim**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
    
The previous term “method” is confusing when this text becomes part of the API reference, where `stringData` is just a field (you can write a conforming implementation of Kubernetes in a language without methods). Reword to avoid this.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kwiesmueller** [comment]
I don't think the `method` referred to the programming concept, but to the actual thing of being a method to do something.
Not sure if I agree with this change, even as a non-native english speaker I didn't read it as a problem.

**Comment by fedebongio** [comment]
/assign @liggitt 
(a secret source told us you may know about this one) thanks!
/triage accepted

**Pull request merged**
