### PR TITLE
kubeadm: Fix a small bug in the self-hosting code

### PR DESCRIPTION
**Pull request by luxas**
**What this PR does / why we need it**:

`apps/v1beta2` requires that `DaemonSet.spec.selector.matchLabels` equals `DaemonSet.spec.template.metadata.labels`. Without this change, the API server rejects the DaemonSet in the validation stage.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
@kubernetes/sig-cluster-lifecycle-pr-reviews @xiangpengzhao

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
@luxas bazel test failed:

```
//cmd/kubeadm/app/phases/selfhosting:go_default_test 0.00s
bazel test //cmd/kubeadm/app/phases/selfhosting:go_default_test
--- FAIL: TestBuildDaemonSet (0.19s)
```

**Comment by luxas** [comment]
fixed unit test failure

**Comment by xiangpengzhao** [comment]
:+1:
/lgtm

**Pull request merged**
