### PR TITLE
Fix pods/log OpenAPI/Swagger spec to return string instead of v1.Pod

### LINKED ISSUE #37881: Unable to fetch logs with Swagger generated code
As of commit: `c758c00b1a597f4629d9f608598452fc3b2fb81b`

**Kubernetes version** (use `1.4.3`):

**Environment**:
- **Ubuntu 16.04**:

**What happened**:
Unable to fetch logs from a pod using the spec provided by [v1.json](https://github.com/kubernetes/kubernetes/blob/master/api/swagger-spec/v1.json)

**How to reproduce it** (as minimally and precisely as possible):
```
wget https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/swagger-spec/v1.json
swagger-codegen generate -i v1.json -l python
```

calling `read_namespaced_pod_log(namespace='default', name=name`) returns a bare v1Pod:

```python
ipdb> kube.api.read_namespaced_pod_log(namespace='default', name=name)
/Users/quasiben/anaconda/envs/kubelab/lib/python3.5/site-packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
{'api_version': None,
 'kind': None,
 'metadata': None,
 'spec': None,
 'status': None}
```

**Anything else do we need to know**:
Relevant issue: https://github.com/kubernetes/kubernetes/issues/14071
Older PR: https://github.com/kubernetes/kubernetes/pull/25707

The PR above has been merged into master but I still only see bare v1Pod dicts returned.  My initial thought was that the `deserialization` can't handle strings and/or isn't appropriately applying `PodLogOptions`.  I could very well be wrong about this.  First time diving into Kubernetes code

### PR DESCRIPTION
**Pull request by mbohlool**
log operation is part of pod and had the assumption of returning a v1.Pod. First I added the support for an operation to be able to customize its return object then added the support to "pods/log" operation to return an string as an object sample.

Fixes #37881
Cc @kubernetes/sig-api-machinery

### CODE REVIEW

**Comment by liggitt** [comment]
cc @smarterclayton

**Comment by lavalamp** [comment]
/lgtm

(I'll avoid quibbling with the names since you were hoping to cherry-pick this :) )

@saad-ali, this is a bugfix we'd like in 1.5 if the door isn't closed yet.

**Comment by mbohlool** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by smarterclayton** [comment]
Is this *really* returning a string (as defined by openapi)?

**Comment by mbohlool** [comment]
Return content is plain/text. Is it not string?

**Comment by mbohlool** [comment]
@k8s-bot cvm gce e2e test this

**Comment by smarterclayton** [comment]
Might be.  Reread the spec but not clearly defined.  There was this about
response objects:

> As an extension to the Schema Object
<https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject>,
its root type value may also be "file". This SHOULD be accompanied by a
relevant produces mime-type.

But there's not enough definition to see whether that implies the more
classic attach.

On Dec 6, 2016, at 8:32 PM, mbohlool <notifications@github.com> wrote:

Return content is plain/text. Is it not string?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/kubernetes/pull/38219#issuecomment-265328970>,
or mute the thread

**Comment by mbohlool** [comment]
@saad-ali I don't think I need to do anything other than applying cherrypick-candidate label according to cherry-pick document (for before the release instructions). Let me know if that is not the case.

**Comment by mbohlool** [comment]
@smarterclayton true, plain/text can be interpreted as file too. The way I saw it in the client code generation (swagger-gen) it produces a file if we set this type to file and return the path. It is much easier to get the string value and also it won't work with streaming (the logs have an option to stream result). The way one of the tools work should not define behavior of the spec, but when in doubt between two (maybe equal) options here, it makes string slightly more preferable.

**Comment by saad-ali** [comment]
@mbohlool I am skipping this PR in my batch cherry pick to 1.5 since there is a merge conflict. Please create a separate cherry pick to release-1.5 (with conflicts resolved) for this PR.

**Pull request merged**
