### PR TITLE
Removed staled docker artifacts on GCE minions.

### LINKED ISSUE #2411: Stale docker artifacts on GCE minions
I suspect this is dues to the recent change to container VMs as the base image?  @dchen1107 

ifconfig docker0 - exists but should not.

iptables-save | grep docker - 4 docker rules that should not exist.

### PR DESCRIPTION
**Pull request by dchen1107**
Fix #2411 

Eventually we can move this to our image, but not now. cc/ @thockin @ArtfulCoder

### CODE REVIEW

**Comment by roberthbailey** [comment]
Is there a reason to inject this here (where we mostly set environment variables) rather than in the scripts that are bundled onto the nodes automatically (e.g. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/gce/templates/common.sh)? As it is, it seems like we'll need to do some copy/pasting of this fix for other similar cloud providers.

**Comment by dchen1107** [comment]
The only reason is that common.sh is invoked for both master and minion nodes, but I only want to change minion nodes here. cc/ @ArtfulCoder on if we really need this for flannel case for etcd_server as pod? Otherwise, I could even push this to containervm image eventually.

**Comment by thockin** [comment]
Can I punt on this review - I am buried and I don't feel like i have current context on the scripts.

@roberthbailey can you take it?

**Comment by roberthbailey** [comment]
Yes, I'll take a closer look this afternoon.

**Comment by ArtfulCoder** [comment]
I am taking a look to see if minion can just start the docker bridge with name docker0, instead of cbr0.

**Pull request merged**
