### PR TITLE
Fix compilation of nsenter code on Mac

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by cblecker** [comment]
/test pull-kubernetes-cross
Running one more cross build, but this looks to fix a cross build issue introduced in https://github.com/kubernetes/kubernetes/pull/52648

**Comment by rmmh** [comment]
/lgtm

Thanks, ran into this today rebasing #59289. :-)

**Comment by cblecker** [comment]
/lgtm
/assign @thockin 
for approval

**Comment by thockin** [comment]
Curious what about this fails on mac but not others?

**Comment by cblecker** [comment]
It fails on windows too from the [ci logs](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-cross-build/4852):
```
I0222 23:03:03.158] +++ [0222 23:02:03] linux/amd64: go build started
I0222 23:03:03.159] +++ [0222 23:02:22] linux/amd64: go build finished
I0222 23:03:03.160] +++ [0222 23:02:03] linux/arm: go build started
I0222 23:03:03.160] +++ [0222 23:02:21] linux/arm: go build finished
I0222 23:03:03.161] +++ [0222 23:02:03] linux/arm64: go build started
I0222 23:03:03.161] +++ [0222 23:02:21] linux/arm64: go build finished
I0222 23:03:03.162] +++ [0222 23:02:03] linux/s390x: go build started
I0222 23:03:03.162] +++ [0222 23:02:21] linux/s390x: go build finished
I0222 23:03:03.163] +++ [0222 23:02:03] linux/ppc64le: go build started
I0222 23:03:03.163] +++ [0222 23:02:21] linux/ppc64le: go build finished
I0222 23:03:03.164] +++ [0222 23:02:03] windows/amd64: go build started
I0222 23:03:03.164] # k8s.io/kubernetes/pkg/util/io
I0222 23:03:03.165] pkg/util/io/writer.go:61:21: cannot use echoArgs (type []string) as type string in argument to ne.Exec
I0222 23:03:03.165] pkg/util/io/writer.go:71:29: cannot use chmodArgs (type []string) as type string in argument to ne.Exec
```

**Comment by rmmh** [comment]
The functions have different signatures on different platforms, but it wasn't actually *used* until the recent PR.

**Comment by dixudx** [comment]
Sorry for bringing in such an error. My fault.
Thanks @sttts for fixing it.

**Comment by cblecker** [comment]
Adding queue/fix label as batch merges are failing because of the cross build failure.

**Pull request merged**
