### PR TITLE
Change VolumeTestCleanup to not fail when pod already deleted

### PR DESCRIPTION
**Pull request by davidz627**
/kind bug
/sig storage
/assign @msau42 

Inspired by: #68581

-->
```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
The previous method also would handle the already deleted case right?

**Comment by davidz627** [comment]
Unfortunately no because:
```
pod, err := cs.CoreV1().Pods(config.Namespace).Get(config.Prefix+"-client", metav1.GetOptions{})
ExpectNoError(err, "Failed to get client pod: %v", err)
```
the `Get` would give a `NotFound` type error and fail.

**Pull request merged**
