### PR TITLE
Generate API docs for new groups

### PR DESCRIPTION
**Pull request by caesarxuchao**
~~I haven't checked the validity of the generated html yet. Will do it later today.~~
cc @bgrant0607

### CODE REVIEW

**Comment by caesarxuchao** [comment]
To see the generated files:
https://htmlpreview.github.io/?https://github.com/caesarxuchao/kubernetes/blob/generate-api-docs/docs/api-reference/autoscaling/v1/definitions.html
https://htmlpreview.github.io/?https://github.com/caesarxuchao/kubernetes/blob/generate-api-docs/docs/api-reference/autoscaling/v1/operations.html
https://htmlpreview.github.io/?https://github.com/caesarxuchao/kubernetes/blob/generate-api-docs/docs/api-reference/batch/v1/definitions.html
https://htmlpreview.github.io/?https://github.com/caesarxuchao/kubernetes/blob/generate-api-docs/docs/api-reference/batch/v1/operations.html

One problem I noticed is the title of each object is in the form of `<version>.<Kind>`, we should add the `<group>` into the title. I think this problem originates in the swagger file we output.

**Comment by caesarxuchao** [comment]
Acutall we can't generate reference docs for other groups like abac, authorization, etc. because we don't generate swagger spec for them.

**Comment by bgrant0607** [comment]
cc @piosz @erictune @lavalamp @nikhiljindal @johndmulhausen

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
