### PR TITLE
Revert "scheduler: clean up NoDiskConflict code in predicates.go"

### PR DESCRIPTION
**Pull request by hongchaodeng**
Reverts kubernetes/kubernetes#18452

### CODE REVIEW

**Comment by hongchaodeng** [comment]
Requested in #20011 to revert the change.
@davidopp

**Comment by davidopp** [comment]
LGTM, thanks for the quick revert!

**Comment by davidopp** [comment]
IIUC, you're sure this won't help the problem? If so, please close the PR.

**Comment by hongchaodeng** [comment]
Closing this. I'm inclined to HollowKubelet being the root of problem. Verifying it.

**Pull request closed without merging**
