### PR TITLE
Deployment e2e tests minor fixes

### PR DESCRIPTION
**Pull request by janetkuo**
@bgrant0607 @kargakis @kubernetes/sig-config

### CODE REVIEW

**Comment by bgrant0607** [comment]
LGTM, but please look at why so many e2e tests failed. It's likely something systemic rather than independent flakes. There may be an open issue for whatever the root cause is. We've been seeing such multi-test failures a fair amount on jenkins.

**Comment by janetkuo** [comment]
Failed e2e tests:
```
Kubernetes e2e suite.Deployment deployment should create new pods
Kubernetes e2e suite.Kubectl client Kubectl logs should be able to retrieve and filter logs [Conformance]
Kubernetes e2e suite.Kubectl client Kubectl patch should add annotations for pods in rc [Conformance]
Kubernetes e2e suite.Kubectl client Kubectl run --rm job should create a job from an image, then delete the job [Conformance]
Kubernetes e2e suite.Deployment RecreateDeployment should delete old pods and create new ones
Kubernetes e2e suite.Deployment RollingUpdateDeployment should delete old pods and create new ones
```
```
Kubernetes e2e suite.Kubectl client Kubectl describe should check if kubectl describe prints relevant information for rc and pods [Conformance]
Kubernetes e2e suite.Kubectl client Kubectl patch should add annotations for pods in rc [Conformance]
Kubernetes e2e suite.Deployment deployment should create new pods
Kubernetes e2e suite.Deployment RollingUpdateDeployment should delete old pods and create new ones
Kubernetes e2e suite.Kubectl client Guestbook application should create and stop a working application [Conformance]
Kubernetes e2e suite.Deployment deployment should label adopted RSs and pods
Kubernetes e2e suite.Deployment deployment should support rollover
```

**Comment by bgrant0607** [comment]
Looks like a docker outage
```
Failed: Failed to pull image "redis": Error pulling image (latest) from docker.io/library/redis, Server error: Status 500 while fetching image layer ...
```

**Comment by bgrant0607** [comment]
@k8s-bot test this issue: #13288

**Pull request merged**
