### PR TITLE
Automated cherry pick of #121566: etcd: Update to version 3.5.10

### PR DESCRIPTION
**Pull request by mzaian**
Cherry pick of #121566 on release-1.26.

#121566: etcd: Update to version 3.5.10

**Does this PR introduce a user-facing change?**:

```release-note
etcd: Update to version 3.5.10
```

### CODE REVIEW

**Review by jmhbnz — APPROVED** [review]
/lgtm
/approve

Thanks @mzaian

**Review by justaugustus — APPROVED** [review]
/lgtm
/approve
/assign @liggitt

**Review by jmhbnz — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
For RelEng:
/lgtm
/approve

**Pull request merged**
