### PR TITLE
Requesting Review/Approve privileges for cluster/OWNERS

### PR DESCRIPTION
**Pull request by dims**
I'd like to help get rid of `/cluster`, looks like existing set of folks are not very active. Could i please be added to keep things moving and get to the end.

Thanks,
Dims

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
context / example - https://github.com/kubernetes/kubernetes/pull/83454

**Comment by jbeda** [comment]
/lgtm

Also feel free to move me to emeritus.

**Pull request merged**
