### PR TITLE
Update CNI version to 1.2.0

### PR DESCRIPTION
**Pull request by adisky**
Signed-off-by: Aditi Sharma <adi.sky17@gmail.com>

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
We haven't updated CNI versions from quite a while, updating to cni v1.2.0

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by adisky** [comment]
cc @dims @SergeyKanzhelev

**Comment by saschagrunert** [comment]
Would be awesome to switch directly to v1.2.0. 😊

**Comment by dims** [comment]
/lgtm cancel

+1 to move to newest one

**Comment by sftim** [comment]
Does this PR definitely have no change in behavior that is visible to end users in any way?

Also, do we need to update any documentation in respect of this bump?

**Comment by adisky** [comment]
@sftim This version bump mostly related to CNI version we use in our CI. As far as I know for users it is recommended to use CNI version compatible with the container runtime

**Comment by sftim** [comment]
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/ is the page that we'd change, if needed. Possibly https://github.com/kubernetes/release/pull/2863 is the trigger for that?

**Comment by saschagrunert** [comment]
> https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/ is the page that we'd change, if needed. Possibly [kubernetes/release#2863](https://github.com/kubernetes/release/pull/2863) is the trigger for that?

I can take care of an update tomorrow if nobody beats me to it.

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
