### PR TITLE
integration: fix race with the controller in TestDSCUpdatesPodLabelAfterDedupCurHistories

### LINKED ISSUE #113036: [Flaky test] k8s.io/kubernetes/test/integration/daemonset
### Which jobs are flaking?

- pr:pull-kubernetes-integration
- ci-kubernetes-integration-master

### Which tests are flaking?

- k8s.io/kubernetes/test/integration/daemonset 
   TestDSCUpdatesPodLabelAfterDedupCurHistories

### Since when has it been flaking?

https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=TestDSCUpdatesPodLabelAfterDedupCurHistories
Maybe since 9.30?
image

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1580295864935518208

### Reason for failure (if possible)

I didn't find err msg in test files. Instead I found:
```
I1012 19:09:56.872061  102520 event.go:294] "Event occurred" object="one-node-daemonset-test/foo" fieldPath="" kind="DaemonSet" apiVersion="apps/v1" type="Warning" reason="FailedCreate" message="Error creating: Post \"https://127.0.0.1:40641/api/v1/namespaces/one-node-daemonset-test/pods\": context canceled"
E1012 19:09:56.872142  102520 daemon_controller.go:1020] Post "https://127.0.0.1:40641/api/v1/namespaces/one-node-daemonset-test/pods": context canceled
E1012 19:09:56.871741  102520 scheduling_queue.go:982] "Error while retrieving next pod from scheduling queue" err="scheduling queue is closed"
```

12 other tests failed because of `context canceled` these days.
https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=context%20canceled

Maybe it's because of bad network? Simple timeout?

### Anything else we need to know?

Some other failed links:

- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1580295864935518208
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1580203756920770560
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/112219/pull-kubernetes-integration/1580266306991558656

Also, [flakes-latest.json](http://storage.googleapis.com/k8s-metrics/flakes-latest.json) shows this is a flaky test.
```
"pr:pull-kubernetes-integration": {
    "consistency":0.968,
    "flakes":10,
    "test_flakes":{
        "k8s.io/kubernetes/test/integration/daemonset TestDSCUpdatesPodLabelAfterDedupCurHistories":3,
        "test-cmd run_kubectl_apply_tests":2,
        "test-cmd run_exec_credentials_tests":1,
        "k8s.io/kubernetes/test/integration/scheduler TestPDBInPreemption/A_non-PDB_violating_pod_is_preempted_despite_its_higher_priority":1,
        "k8s.io/kubernetes/test/integration/scheduler TestPDBInPreemption/A_node_without_any_PDB_violating_pods_is_preferred_for_preemption":1,
        "k8s.io/kubernetes/test/integration/volume TestPVCBoundWithADC":1,
        "k8s.io/kubernetes/test/integration/scheduler TestPDBInPreemption":1,
        "k8s.io/kubernetes/test/integration/scheduler TestPDBInPreemption/A_node_with_fewer_PDB_violating_pods_is_preferred_for_preemption":1,
        "test-cmd run_kubectl_request_timeout_tests":1,
        "test-cmd run_storage_class_tests":1
    }
}
```
```
"ci-kubernetes-integration-master":  {
    "consistency":0.714,
    "flakes":8,
    "test_flakes":{
        "k8s.io/kubernetes/test/integration/daemonset TestDSCUpdatesPodLabelAfterDedupCurHistories":4,
        "test-cmd run_kubectl_server_side_apply_tests":2,
        "test-cmd run_crd_tests":2,
        "k8s.io/kubernetes/test/integration/evictions TestEvictionWithFinalizers":1,
        "test-cmd run_kubectl_apply_tests":1,
        "k8s.io/kubernetes/test/integration/evictions TestEvictionWithFinalizers/running_pod_with_PodDisruptionConditions_disabled":1,
        "k8s.io/kubernetes/test/integration/evictions TestEvictionWithFinalizers/running_pod_with_PodDisruptionConditions_enabled":1
    }
}
```

### Relevant SIG(s)

_No response_

### PR DESCRIPTION
**Pull request by atiratree**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

Fixes a race with the daemonset controller. In congested environment, if the test is faster for observing patched pods before the controller deletes the revision here

https://github.com/kubernetes/kubernetes/blob/d7bff1c80912b20bc969111ac52825b67909bbe8/pkg/controller/daemon/update.go#L389

the test will observe the revision as not deleted.

We should just wait for a bit, before we can pronounce the revision deleted.

#### Which issue(s) this PR fixes:

Fixes #113036

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
The fix looks correct to me, but I have to ask, did you run it with with `stress ./` to be completely sure?  

https://gist.github.com/liggitt/6a3a2217fa5f846b52519acfc0ffece0#running-integration-tests-to-reproduce-flakes

**Comment by atiratree** [comment]
yes I did. I have also emulated it with an artificial timeout in the controllers.

**Comment by aojea** [comment]
lots of timeouts lately onthe kind job 🤔 , but totally unrelated to this

/lgtm
/approve
/milestone v1.26

Solving flakes and improve testing qualifies for milestone

Thanks

**Comment by atiratree** [comment]
integration failed with `TestBlockingOwnerRefDoesBlock`
/test pull-kubernetes-integration

**Comment by aojea** [comment]
flakes probably caused by https://github.com/kubernetes/kubernetes/issues/113852

**Pull request merged**
