### PR TITLE
Cherrypick of #45990

### PR DESCRIPTION
**Pull request by dashpole**
Fixes disk eviction for the 1.6 branch.  This has been manually verified to pass the inode eviction test.

Cherrypick of #45990

cc @dchen1107 
/assign @enisoc 

```release-note
Fix kubelet panic during disk eviction introduced in 1.6.3.
```

### CODE REVIEW

**Comment by enisoc** [comment]
Readded `do-not-merge` due to message from @dashpole:

> I am running a manual test to verify that this fixes it. Please wait for the result before merging

**Comment by dashpole** [comment]
Manual testing just finished.  This is all set to merge.  Thanks @enisoc

**Comment by dashpole** [comment]
does it matter that this has not been merged in master yet?

**Comment by dchen1107** [comment]
The test result looks good, removing do-not-merge.

**Pull request merged**
