### PR TITLE
Topology Manager Policy: single-numa-node

### PR DESCRIPTION
**Pull request by lmdaly**
**What type of PR is this?**
 /kind feature

**What this PR does / why we need it**:
Issue for tracking PRs: #72828

This PR introduces a new Topology Manager policy which aligns resources on a single NUMA Node or fails the pod if this is not possible. The restricted policy previously implicitly did this. Based on discussions with @ConnorDoyle & @klueska, it was determined that a specific policy to cater for this would be more clear for the users.

The restricted policy will fail pods that have the preferred policy set to false, this can occur when a sub-optimal NUMA affinity is determined for the pod. 

**Does this PR introduce a user-facing change?**:
This adds an additional option to the `--topology-manager-policy` called `single-numa-node`.
The `topology-manager-policy` has not been used in previous releases and is being introduced in the 1.16 release.

### CODE REVIEW

**Comment by klueska** [comment]
/cc @erictune @liggitt @bgrant0607 @lavalamp @smarterclayton @thockin

This does not introduce any user-facing API change because this is a new feature for 1.16

**Comment by derekwaynecarr** [comment]
the code changes look fine, and the policy is clear.  before this graduates in future releases beyond alpha, we need to clarify the strategy to test this with mock device plugins.

/approve
/lgtm

will need an api review for new token , but looks fine to me for sig-node.

**Comment by liggitt** [comment]
/approve

field is still alpha gated and is new in 1.16

**Comment by adrianchiris** [comment]
PR #81586 "strict" policy already deals with aligning resources to a single NUMA node.
just to make sure i understand, this PR will affect #81586  in a way that:
1. will require a rename of the policy to singleNumaPolicy
2. an additional policy called restrictedPolicy which is identical to the bestEffortPolicy but will fail if a hint is not preferred  (or a configuration of the existing policy)

is my understanding correct ?

**Comment by ConnorDoyle** [comment]
@adrianchiris yes your description is accurate. We decided to make this change to meet the needs of everyone involved in the design discussions and to make the policy semantics as easy to understand as possible.

**Comment by klueska** [comment]
> PR #81586 "strict" policy already deals with aligning resources to a single NUMA node.
> just to make sure i understand, this PR will affect #81586 in a way that:
> 
> 1. will require a rename of the policy to singleNumaPolicy
> 2. an additional policy called restrictedPolicy which is identical to the bestEffortPolicy but will fail if a hint is not preferred  (or a configuration of the existing policy)
> 
> is my understanding correct ?

@adrianchiris The long term plan is still to add the Merge() method you have in your / @moshe010's PR. This is a short term fix to unblock the release of these policies.

**Comment by liggitt** [comment]
/priority important-soon
/milestone v1.16

important to include this before shipping the config field

**Pull request merged**
