### PR TITLE
Windows: Updates getSystemUUID to use WMI instead

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/sig windows
/kind cleanup

#### What this PR does / why we need it:

The wmic command is deprecated on Windows. We can use WMI calls instead to get the System UUID.

This PR uses the ``github.com/go-ole/go-ole`` library, which allows us to run WMI queries to get the information we need.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by claudiubelu** [comment]
I've built a kubelet using this PR and checked if the ``systemUUID`` is still being reported properly by a Windows node (after it the node was removed from Kubernetes as well). Had the same ``systemUUID``.

The ``pull-kubernetes-e2e-aks-engine-windows-containerd`` job passed too.

**Comment by jsturtevant** [comment]
It looks like this is only called during start up so might not be major impact on overall performance, but is there a difference in the speed of the call?

This is called via the cadvisor interface.  Is this something that will be removed eventually (with the introduction of CRI only stats)?

**Comment by marosset** [comment]
Does this overlap with the CRI based stats work?

**Comment by dims** [comment]
/assign @bobbypage @marosset 

(for initial review! and lgtm, please assign @smarterclayton or @liggitt for root OWNERS approval after that)

**Comment by marosset** [comment]
The code changes look good to me (at least as good as wmi queries can be).
I'm still trying to decide if making native wmi calls is worth bringing in the new dependecies or if we should just shell out to powershell with `powershell.exe (Get-WmiObject -Class Win32_ComputerSystemProduct).UUID` instead of using wmic.exe (which is deprecated).

**Comment by marosset** [comment]
@jsturtevant @dcantah any opinions here?

**Comment by jsturtevant** [comment]
> @jsturtevant @dcantah any opinions here?

This is called via the cadvisor interface. I think this is something that will be removed eventually (with the introduction of CRI only stats) so do we want to be bringing in a new dep for this right now?

**Comment by dcantah** [comment]
@jsturtevant Well before I answer, are you saying this code path (and the need to grab the UUID in the first place) will no longer be relevant once the cri only stats is adopted, or something else?

**Comment by jsturtevant** [comment]
I am not sure on that but I know there is movement toward [Cri only stats](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2371-cri-pod-container-stats).  I am not sure if the cadvisor pacakge will be completely removed.  Or if it only means container stats will no longer be gathered from there.  

I might wrong that it will be removed based on https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2371-cri-pod-container-stats#cadvisor @haircommander might be able to help clarify?

This is call via the windows casdvisor pacakge: https://github.com/kubernetes/kubernetes/blob/c1e69551be1a72f0f8db6778f20658199d3a686d/pkg/kubelet/cadvisor/cadvisor_windows.go#L71

It is used to get node info: https://github.com/kubernetes/kubernetes/blob/c1e69551be1a72f0f8db6778f20658199d3a686d/pkg/kubelet/nodestatus/setters.go#L275-L278

**Comment by haircommander** [comment]
node level stats will still come from cadvisor. Eventually container and pod level stats will only come from cri, though

**Comment by dcantah** [comment]
This change looks to be only affecting node level stats so seems like the change is warranted (unless I'm missing something). I'm in favor of reaching for powershell here to avoid the dep as Mark suggests. From a quick search I see two other spots in k8s that shell out to powershell to grab volume related info so seems it wouldn't be the first time we've went this route.

**Comment by bobbypage** [comment]
+1 to https://github.com/kubernetes/kubernetes/pull/106093#issuecomment-1006940484, the long term plan is to move container and pod stats out to CRI, node stats will come from cAdvisor. However, it may be refactored to not depend on cAdvisor interfaces directly (perhaps some slimmed down node stats only package).

Either way, I'm also in favor of shelling out, since it seems to be a large dependency and I'm guessing the SystemUUID can be cached and is not expected to change?

**Comment by jsturtevant** [comment]
@haircommander  @bobbypage Thanks for the confirmation.

We need to look at how often this code path is called.  We have seen instances where shelling out powershell or equivalents adds quite a bit of overhead from latency and cpu usage over using native system calls.

**Comment by dcantah** [comment]
> We need to look at how often this code path is called. We have seen instances where shelling out powershell or equivalents adds quite a bit of overhead from latency and cpu usage over using native system calls.

Ahh, I was going off of your previous message that mentioned this might only be called during startup. Regardless, if it is called more than once in some code path we can cache the result and skip actually doing the work again like @bobbypage mentions.

**Comment by helayoty** [comment]
@claudiubelu 👋 I'm in the release 1.24 bug triage shadow. Does this issue still target release 1.24? If yes, would you please update the priority field for us to track it better?

**Comment by helayoty** [comment]
@claudiubelu  @jsturtevant  @dcantah  👋  the release 1.24 bug triage shadow. Does this PR still target release 1.24? I can see it needs the priority field to be set. The code freeze is soon.

**Comment by jsturtevant** [comment]
I think the outcome of the conversation was we need to change this but since this a one time thing when kubelet boots it would be preferable to do this via via powershell (or manually covert the calls to syscalls) the over bringing in a library?  Does this make sense?

**Comment by claudiubelu** [comment]
I think we can close this for now. We can revisit this later if it becomes a bigger concern, or if the library used in this PR is needed for other things as well.

**Comment by mahenarayan** [comment]
@claudiubelu @jsturtevant @marosset We should revisit this? This is a major concern for hardened machines using deprecated features in the production. When starting kubelet on all of our bare metal production machines, this is a major finding (using deprecated tool) which needs to be addressed.
image

**Comment by marosset** [comment]
> @claudiubelu @jsturtevant @marosset We should revisit this? This is a major concern for hardened machines using deprecated features in the production. When starting kubelet on all of our bare metal production machines, this is a major finding (using deprecated tool) which needs to be addressed. image

I'm adding this for discussion at the next SIG-Windows community meeting.
[Agenda](https://docs.google.com/document/d/1aCcqSDBuXQ2gTbBg6QuGvLxCmzlSrAbTfflCTmo-960)

I don't personally think there is much risk to using wmic since only the command line tool (which is very simple) is being deprecated and not WMI or any of the WMI interfaces.

Happy to revisit the discussion again

**Comment by mahenarayan** [comment]
@marosset Thank you, I am interested in supporting in getting this change. I will try to join SIG-Windows community meeting.

**Pull request closed without merging**
