### PR TITLE
Increase cluster resize timeout in e2e tests from 2 min to 5 min

### PR DESCRIPTION
**Pull request by mwielgus**
cc: @piosz @fgrzadkowski

### CODE REVIEW

**Comment by mwielgus** [comment]
It is trivial, test only change. Merging without LGTM to fix the tests.

**Comment by piosz** [comment]
LGTM, unfortunately it didn't help.

**Comment by fgrzadkowski** [comment]
I think we should revert this PR as it was not the cause of failures and I believe we should be more sensitive than 5 minutes timeout.

@mwielgus @piosz

**Comment by piosz** [comment]
Let's leave it as for now. The timeout should be significantly higher than our target to avoid flakiness when for example operations on MIGs fail.

**Pull request merged**
