### PR TITLE
Fix TODO pkg/api/v1/node merge with pkg/util/node

### PR DESCRIPTION
**Pull request by jianglingxia**
**What this PR does / why we need it**:
Fix TODO pkg/api/v1/node merge with pkg/util/node
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jianglingxia** [comment]
can anybody help me with the problem that the ci failed ：
W0207 09:24:21.862] ERROR: /go/src/k8s.io/kubernetes/test/e2e_node/BUILD:82:1: GoCompile test/e2e_node/linux_amd64_stripped/go_default_test~/k8s.io/kubernetes/test/e2e_node.a failed (Exit 1): compile failed: error executing command 
I tested in my enviroment and make paas! thanks very much!

**Comment by jianglingxia** [comment]
thanks @thockin  can you help me with the ci failed problem？

**Comment by thockin** [comment]
Start with this:  Run ./hack/update-bazel.sh

**Comment by thockin** [comment]
@kubernetes/sig-contributor-experience-bugs This PR and many other appear to have no assignee (I just assigned myself).  Is that a valid state?  Should we maybe have a "parking lot" where we can assign issues that need work?

@grodrigues3

**Comment by jianglingxia** [comment]
sorry,run the ./update-bazel.sh failed  @thockin thanks
[root@localhost hack]# ./update-bazel.sh 
package golang.org/x/tools/go/vcs: unrecognized import path "golang.org/x/tools/go/vcs" (https fetch: Get https://golang.org/x/tools/go/vcs?go-get=1: cannotconnect)
!!! [0226 18:32:44] Call tree:
!!! [0226 18:32:44]  1: ./update-bazel.sh:34 kube::util::go_install_from_commit(...)
!!! Error in /home/src/k8s.io/kubernetes/hack/lib/util.sh:482
  Error in /home/src/k8s.io/kubernetes/hack/lib/util.sh:482. '((i<3-1))' exited with status 1
Call stack:
  1: /home/src/k8s.io/kubernetes/hack/lib/util.sh:482 kube::util::go_install_from_commit(...)
  2: ./update-bazel.sh:34 main(...)
Exiting with status 1

**Comment by thockin** [comment]
that looks transient - can't connect.

Try again?

**Comment by thockin** [comment]
Assign back to me once it is passing CI and ready for review

**Pull request closed without merging**
