### PR TITLE
Define const for metric name

### PR DESCRIPTION
**Pull request by houjun41544**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

### CODE REVIEW

**Review by ehashman — APPROVED** [review]
/approve
/lgtm

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve
/cc @dashpole

**Comment by ehashman** [comment]
/triage accepted

needs a SIG Node approver

**Pull request merged**
