### PR TITLE
Add a "DisableCompression" option to kubeconfig

### PR DESCRIPTION
**Pull request by shyamjvs**
#### What this PR does / why we need it:
Part-2 of the proposal here - https://github.com/kubernetes/kubernetes/issues/112296
/kind feature

#### Does this PR introduce a user-facing change?
```release-note
A new "DisableCompression" field (default = false) has been added to kubeconfig under cluster info. When set to true, clients using the kubeconfig opt out of response compression for all requests to the apiserver. This can help improve list call latencies significantly when client-server network bandwidth is ample (>30MB/s) or if the server is CPU-constrained.
```

/assign @lavalamp @deads2k 
/sig api-machinery

### CODE REVIEW

**Comment by lavalamp** [comment]
code looks fine, unit test is failing. Someone from SIG CLI should look at this also.

/assign @seans3

**Comment by shyamjvs** [comment]
I think I figured out the reason for failing unit test. There's also a `clientauthentication.Cluster` schema (seems to be used by exec provider plugin) that needs to be in sync with the `clientcmdapi.Cluster` schema. Updated it, hopefully works now.

**Comment by shyamjvs** [comment]
Besides `pull-kubernetes-verify` (which I'm looking into), others seem to be unrelated flakes

/test pull-kubernetes-e2e-kind
/test pull-kubernetes-integration

**Comment by dims** [comment]
@shyamjvs please make it clear in release notes and where ever else it is appropriate that this field is set to `false` by default (reflecting the current status quo). Other than that, looks good to me!

**Comment by lavalamp** [comment]
... honestly if it is easy to choose a non-go default, it would be more normal to name this in the positive (`EnableCompression`) and default to `true`.

**Comment by dims** [comment]
@lavalamp yep, was my first instinct as well. (`EnableCompression=true`) and folks can switch it off.

**Comment by shyamjvs** [comment]
@dims Good callout on mentioning default value. Updated the release note, thanks.

Regarding the field name `DisableCompression`, the reason I preferred it is because its the convention with both the [RestConfig field](https://github.com/kubernetes/client-go/blob/372575c38a08134a8918ddaf1e8269ea6ba85359/transport/config.go#L51-L53) and [go http library](https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/net/http/transport.go;l=190). Also I expect compression is something clients would mostly enable and rarely disable, so making the latter explicit. Also using EnableCompression will need us to negate before passing to restConfig at few places, but if you feel strongly about it I can switch.

**Comment by dims** [comment]
@shyamjvs good enough explanation for me :) ok from me to keep it the way it is.

**Comment by lavalamp** [comment]
I think we should double check w/ @deads2k or @liggitt -- I still slightly prefer naming things in the positive when user facing.

**Comment by shyamjvs** [comment]
@deads2k @liggitt - Thoughts on the above?

**Comment by liggitt** [comment]
if this were a new field in isolation, I'd maybe agree... but I think it's more usable to match the `rest.Config` field name and let the boolean zero value match the default (so we can omit it from serialization rather than having to default it to true)

**Comment by lavalamp** [comment]
OK, I guess that's a good enough reason for me.

/lgtm
/approve

**Pull request merged**
