### PR TITLE
Add get/delete cluster, delete context to kubectl config

### LINKED ISSUE #29794: Kubectl delete-cluster, list-clusters, delete-contexts, list-contexts
I make a lot of clusters and then I forget which ones I have.  I could do `kubectl config view` but that is a lot of spew.  I could do  `kubectl config view --minify` but that only shows the current context.

I'd like:
```
$ kubectl config list-clusters
NAME                              
eric-tune-6_kubernetes
gke_eric-tune-6_us-west1-a_cluster-2
gke_eric-tune-6_us-west1-a_cluster-3
local
minikube
```

I'd also like:
```
$ kubectl config list-contexts
NAME                                  CLUSTER                               NAMESPACE    IS-CURRENT
eric-tune-6_kubernetes                eric-tune-6_kubernetes                default      *
eric-tune-6_kubernetes-admin          eric-tune-6_kubernetes                kube-system        
gke_eric-tune-6_us-west1-a_cluster-2  gke_eric-tune-6_us-west1-a_cluster-2  default  
gke_eric-tune-6_us-west1-a_cluster-3  gke_eric-tune-6_us-west1-a_cluster-3  default
minikube                              minikube                              default
```
so I can see what contexts I have.

I'd also like:
```
$ kubectl config delete-clusters minikube
deleted cluster minikube from $HOME/.kube/config
```
or 
```
$ kubectl config delete-cluster minikube
cannot delete cluster minikube, not in $HOME/.kube/config.
```

I'd also like:
```
$ kubectl config delete-context minikube 
deleted context minikube from $HOME/.kube/config
```

Also, something needs to GC contexts that have no cluster, and authInfos that have no cluster?

This could be a good starter project for kubectl.

### PR DESCRIPTION
**Pull request by alexbrand**
Fixes #29794 by adding `get-clusters`, `delete-cluster` and `delete-context` actions to `kubectl config`.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29821)

### CODE REVIEW

**Comment by jlowdermilk** [comment]
@k8s-bot ok to test

**Comment by jlowdermilk** [comment]
You'll need to run `hack/update-generated-docs.sh`, but otherwise looks good. cc @janetkuo @bgrant0607

**Comment by alexbrand** [comment]
@jlowdermilk Running `hack/update-generated-docs.sh` doesn't result in any changed files according to git. Am I doing something wrong?

**Comment by alexbrand** [comment]
@jlowdermilk Updated docs. Thanks!

**Comment by jlowdermilk** [comment]
I'm apparently out of date on how we actually bump kubectl docs. @janetkuo what's the new procedure?

**Comment by jlowdermilk** [comment]
@alexbrand I believe generated docs are now good (sorry for confusion, we're apparently changing how we update them #26205), but looks like unit tests are failing.

**Comment by jlowdermilk** [comment]
cc @kubernetes/kubectl

**Comment by alexbrand** [comment]
Thanks @jlowdermilk. I'll take a look as soon as I can.

**Comment by janetkuo** [comment]
ok to test

**Comment by jlowdermilk** [comment]
@k8s-bot ok to test

**Comment by jlowdermilk** [comment]
@k8s-bot ok to test

**Comment by jlowdermilk** [comment]
Adding label. @janetkuo please remove if you see anything.

**Comment by jlowdermilk** [comment]
@k8s-bot test this issue: #31462

**Comment by erictune** [comment]
@alexbrand Thanks!  I am going to try this out right now!

**Pull request merged**
