### PR TITLE
Fix Heapster and Metrics Server configuration to enable overriding resource requirements.

### PR DESCRIPTION
**Pull request by kawych**
**What this PR does / why we need it**:
Configure resources for Heapster and Metrics Servier using Component Config. This will enable overriding default resource requirements for these components.

**Release note**:
```release-note
Fix Heapster configuration and Metrics Server configuration to enable overriding default resource requirements.
```

### CODE REVIEW

**Comment by mwielgus** [comment]
Please explain how it was tested.

**Comment by kawych** [comment]
I've started a cluster with Heapster and Metrics Server enabled using this configuration on 4-node cluster, both started successfully and Nanny scaled their resources using correct values.

**Comment by mwielgus** [comment]
/lgtm
I have nothing against this PR but please make sure that you get approvals from the key stakeholders.

**Comment by kawych** [comment]
As per discussion with @piosz we need both a way to change resources and allow a customer to overwrite them. For now, we think the solution is to add config map support on top of flags. This requires a small change in Addon Resizer. Closing this PR until it's implemented.

**Pull request closed without merging**
