### PR TITLE
Automated cherry pick of #124662: Updated & added visibility to apiserver x509 test

### PR DESCRIPTION
**Pull request by seantywork**
Cherry pick of #124662 on release-1.29.

#124662: Updated & added visibility to apiserver x509 test

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/release-managers

**Review by cpanato — APPROVED** [review]
/lgtm
/priority important-soon

**Pull request merged**
