### PR TITLE
Update glusterfs vendor dependencies to sha@7a54b6fc903feab1e7cb65731…

### PR DESCRIPTION
**Pull request by humblec**
…77ca09b544eb1e2

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

```NONE
```

### CODE REVIEW

**Comment by humblec** [comment]
@jsafrane @rootfs PTAL.

**Comment by humblec** [comment]
@k8s-bot ok to test

**Comment by jsafrane** [comment]
@k8s-bot ok to test

**Comment by rootfs** [comment]
@humblec any detail about this update?

**Comment by humblec** [comment]
@rootfs heketi version 4 (https://github.com/heketi/heketi/releases/  was released some time back with few enhancements and bug fixes . The reason behind this specific commit which is after v4 is mainly because there is an api change due to a new member in brickinfo struct. 

```
@@ -66,6 +62,7 @@ type BrickInfo struct {
        Path     string `json:"path"`
        DeviceId string `json:"device"`
        NodeId   string `json:"node"`
+       VolumeId string `json:"volume"`
```

**Comment by humblec** [comment]
@lavalamp @dchen1107 Can you please approve this PR ?

**Pull request merged**
