### PR TITLE
Cherry-picks for release 1.2

### PR DESCRIPTION
**Pull request by eparis**
This picks the following PRs:
#22430: Change scheduler logic from random to round-robin
#22709: enable master kubelet in gce-default to match gce-test
#22708: Take 2: continuously delete pods on nodes that don't exist
#22720: Don't list master node when looking to a NodePort node.
#22748: MESOS: fix broken km controller
#22749: Selector operator strings should all be lowercase to be consistent with other operators.
#22743: Make kubelet-perf 100 pod/node test work with registered master
#22606: Modify deployment.go to use nginx:1.73 and redis:e2e
#22769: Pass ResourceVersion in Scale object back to RC before updating RC so that it can be used to check for conflicts.
#22594: Ubernetes-Lite: reuse existing configuration when reusing master
#22762: Added job/v1 generator to kubectl run
#22801: Bumped Heapster to v0.20.0-alpha12
#22017: Fix thirdparty discovery and add unit tests
#22808: Copy replicaset example yamls to hack/testdata directory.
#22766: Fix validation of resources (cpu, memory, storage) for limit range types.
#22809: Add kubectl describe tests for replica sets.
#22811: Enable kubectl autoscale for replica sets.
#22756: MESOS: added proxy-kubeconfig flag
#22772: update wide option output
#22840: Prefer fetched version when determining HPA group version kind

The next two had conflicts which were solved by hand
#22724: Support for both map-based and set-based selectors in extensions/v1beta1.Scale
#22758: ReplicaSetSpec.Template shouldn't be a pointer.

And then 2 more that came in after I started.
#22804: bump(github.com/docker/spdystream): 449fdfce4d962303d702fec724ef0ad181c92528
#22849: Added api discovery to kubectl run, based on which we decide which generators to use

And then 1 which I guess I just missed!
#22602: Ubernetes Lite: apply auto-labels to dynamically provisioned volumes

### CODE REVIEW

**Comment by eparis** [comment]
@bgrant0607

**Comment by bgrant0607** [comment]
Thanks, @eparis. I'd also like to include #22602 and #22804 (just added cherrypick-approved), and #22849 if tests pass. We could create another PR for that, though.

**Comment by bgrant0607** [comment]
Hmm. Maybe a couple others merged, also. github says there should be 24:

https://github.com/kubernetes/kubernetes/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+label%3Acherrypick-approved

**Comment by bgrant0607** [comment]
I'm going to manually merge #22849 once unit tests pass.

**Comment by eparis** [comment]
Two had conflicts which I will have to solve by hand / look at: 22724 and 22758

Looks like 22804 came in after I did this. So there are at least a couple still to come.

**Comment by bgrant0607** [comment]
I merged #22849 into master.

**Comment by eparis** [comment]
@bgrant0607 take another look. Not entirely sure how I missed 22602....

**Comment by bgrant0607** [comment]
22602 was approved this morning. 

Do we have a way to automatically determine which thinks have been cherrypicked, for when we do the next round?

**Comment by eparis** [comment]
I was planning to (semi-manually) comment in each PR and will remove both the `-approved` and the `-candidate` labels...

**Comment by eparis** [comment]
My comment was going to be
```
This PR was sucessfully cherry picked in PR #22855
please verify that the release-1.2 branch contains these changes as you would expect and contact @eparis if there appear to be problems.
```

**Comment by bgrant0607** [comment]
Ok

**Comment by bgrant0607** [comment]
A couple more have merged, but let's do those in a separate sweep

**Comment by bgrant0607** [comment]
LGTM, assuming tests pass

**Comment by eparis** [comment]
This would have been INCREDIBLY easy if not for our docs/comment HEAD->release-1.2 stuff

**Comment by bgrant0607** [comment]
Yes, we should rethink that

**Comment by bgrant0607** [comment]
e2e passed. unit tests are much slower now

**Comment by eparis** [comment]
and there goes 'unit'

**Comment by bgrant0607** [comment]
All green. Merging.

**Pull request merged**
