### PR TITLE
revert Bump DynamicKubeConfig metric deprecation to 1.23 by delta update

### LINKED ISSUE #104041: Revert bump of DynamicKubeletConfig metrics deprecation to 1.23
This shipped in 1.22 as deprecated in 1.22. As a hacky fix to unbreak tests on 1.23 dev, I bumped the deprecation policy one release: https://github.com/kubernetes/kubernetes/pull/103980#issuecomment-888510879

We will need to revert that before 1.23 ships and figure out a better solution.

/kind cleanup
/milestone v1.23
/sig node

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

#### What type of PR is this?
/kind cleanup
/milestone v1.23
/sig node

#### What this PR does / why we need it:
revert a hacky fix which will fail tests

#### Which issue(s) this PR fixes:

Fixes #104041

#### Special notes for your reviewer:
Anything else I can follow up. I'm glad to provide some help.

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ehashman** [comment]
/hold

IMO the revert needs to land at the same time as the fix...

**Comment by kerthcet** [comment]
> /hold
> 
> IMO the revert needs to land at the same time as the fix...

**Comment by ehashman** [comment]
@kerthcet can you look into adding a commit that will set [`showHiddenMetricsForVersion=1.22`](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration) in the DynamicKubeletConfiguration in the [node-e2es](https://github.com/kubernetes/kubernetes/tree/master/test/e2e_node)? That will allow us to take the revert.

**Comment by kerthcet** [comment]
> @kerthcet can you look into adding a commit that will set [`showHiddenMetricsForVersion=1.22`](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration) in the DynamicKubeletConfiguration in the [node-e2es](https://github.com/kubernetes/kubernetes/tree/master/test/e2e_node)? That will allow us to take the revert.

absolutely, I'll do my best

**Comment by pacoxu** [comment]
/cc dashpole
for kubelet metrics change review/approve

**Comment by kerthcet** [comment]
> /approve
> /lgtm
> /skip

key @dims, I'm a little confused about `skip` cmd, can you help to explain the reason?

**Comment by dims** [comment]
@kerthcet https://go.k8s.io/bot-commands

**Comment by kerthcet** [comment]
> @kerthcet https://go.k8s.io/bot-commands

I mean why would you skip these two tests.`pull-kubernetes-node-kubelet-serial` and `@k8s-ci-robot
pull-kubernetes-node-kubelet-serial-containerd`

**Pull request merged**
