### PR TITLE
Remove ClientSetForVersion & ClientConfigForVersion from factory

### PR DESCRIPTION
**Pull request by soltysh**
**What this PR does / why we need it**:
This is further cleaning the factory.

**Special notes for your reviewer**:
/assign @deads2k 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by soltysh** [comment]
@juanvallejo fyi

**Comment by soltysh** [comment]
@pwittrock @kubernetes/sig-cli-pr-reviews fyi

**Comment by deads2k** [comment]
/lgtm

you've got a couple test refs to chase.

**Comment by soltysh** [comment]
Updated the failing bazel, nothing else chenaged so I'm re-applying the labels back.

**Comment by soltysh** [comment]
The test works fine on my local env. 
/retest

**Comment by juanvallejo** [comment]
/lgtm

@soltysh looks like test is not specific to this PR.
Saw it here as well: https://github.com/kubernetes/kubernetes/pull/60219

**Pull request merged**
