### PR TITLE
Add support for attach to kubectl

### PR DESCRIPTION
**Pull request by brendandburns**
Depends on #11957 

@jlowdermilk @bgrant0607 @deads2k @ncdc 

I know that I need to add unit tests, this is for initial review and parallelism.

### CODE REVIEW

**Comment by brendandburns** [comment]
(and please only review the [2nd commit](https://github.com/GoogleCloudPlatform/kubernetes/commit/b24479f07c2910e31bebe1b1e6fbc0727fdd455d))

**Comment by brendandburns** [comment]
Unit tests added.

**Comment by bgrant0607** [comment]
Ref #1521.

**Comment by bgrant0607** [comment]
Please document this in docs/user-guide/docker-cli-to-kubectl.md.

**Comment by jlowdermilk** [comment]
One small nit, but kubectl changes lgtm.

**Comment by brendandburns** [comment]
Comments addressed, please re-check.

Thanks
--brendan

**Comment by deads2k** [comment]
2nd commit lgtm

**Comment by brendandburns** [comment]
@k8s-bot test this please

**Comment by jlowdermilk** [comment]
lgtm

**Pull request merged**
