### PR TITLE
Add retry to the kubectl patch command

### PR DESCRIPTION
**Pull request by brendandburns**
@deads2k @bgrant0607 @smarterclayton @jlowdermilk 

Fixes https://github.com/kubernetes/kubernetes/issues/14467

### CODE REVIEW

**Comment by bgrant0607** [comment]
Putting this into just kubectl doesn't help any other clients deal with such conflicts. Why not put the retries in PatchResource, as was proposed by the issue?

**Comment by brendandburns** [comment]
This is simpler, and requires a bunch less plumbing in my opinion.  (and less discussion of the right interfaces too.)

Let's get this in, fix the problem for 99% of users and deflake the test.  Then we can add it to the client and rip it out from kubectl if we feel like it.

--brendan

**Comment by jlowdermilk** [comment]
lgtm. +1 for easy fix now, adding to client later.

**Comment by brendandburns** [comment]
marking LGTM on @jlowdermilk 's LGTM

**Comment by deads2k** [comment]
> marking LGTM on @jlowdermilk 's LGTM

Give me an hour to see if I can finish a fix to `PatchResource`?  I'm writing tests now.

**Comment by deads2k** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/14758 to demonstrate the server side fix

**Comment by liggitt** [comment]
I'd prefer a server-side implementation as well (to avoid building retry logic in every client using patch)

**Comment by jlowdermilk** [comment]
undo lgtm. @brendandburns thoughts on dropping client-side retry in favor of #14758?

**Comment by chrissnell** [comment]
Relevant related issue:  #14280 

Would love to see auto-retry (w/ optional backoff) available as an option for all API requests in the client.

**Comment by brendandburns** [comment]
I'm fine w/ doing this server side.  Closing this for now.

**Comment by bgrant0607** [comment]
I want the server-side solution. However, I would also be fine with this going in as a quick workaround if the max-retries flag were eliminated.

**Comment by liggitt** [comment]
agree with temp fix if we don't add flags

**Comment by bgrant0607** [comment]
cc @caesarxuchao @JanetKuo

**Comment by deads2k** [comment]
> cc @caesarxuchao @JanetKuo

https://github.com/kubernetes/kubernetes/pull/14758 has merged, is this still a problem?  I wasn't expecting the bump.

**Comment by caesarxuchao** [comment]
@deads2k, no, there is no problem. Brian just wants us to take this PR as a reference, as we are trying to add retry to `kubectl annotate` and `kubectl label`.

**Pull request closed without merging**
