### PR TITLE
Move kube-proxy networking utilities to staging

### PR DESCRIPTION
**Pull request by danwinship**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
We have discussed moving the proxy code out of k/k to make it easier for third party proxy implementations to vendor.

The last discussion of this (https://github.com/kubernetes/enhancements/pull/2635, hi @rikatz) got bogged down in trying to figure out exactly where to move all the various networking utilities (eg `pkg/util/iptables`). However, this discussion was predicated on the idea that other parts of kubernetes had legitimate reasons for using these packages and so it wouldn't make sense to just move them to `staging/src/k8s.io/kube-proxy` directly. But
- `pkg/util/conntrack`, `pkg/util/ipset`, and `pkg/util/ipvs` are literally only used by the proxy code
- `pkg/util/iptables` is only used by (a) the proxy code, (b) kubemark's fake proxy implementation, (c) kubelet stuff that is mostly deprecated/legacy.

So, let's just move them to the kube-proxy staging dir.

Admittedly, even after [`IPTablesOwnershipCleanup`](https://github.com/kubernetes/enhancements/issues/3178) finishes, kubelet will still use iptables a little bit (eg, to create `KUBE-IPTABLES-HINT`). But given that the point of moving the functions to `k8s.io/kube-proxy` is to make it easier for people to vendor them, it seems reasonable to have kubelet vendor it from there too...

(After this, the biggest remaining k/k dependency in the proxy code is `pkg/util/async`. [There was an attempt to move that out](https://github.com/kubernetes/utils/pull/165) but it failed because it upset the bots and required a force-merge and I never bothered to get anyone to agree to do that. But we could resurrect it.)

(There has also been discussion about "kpng will handle this", but if kpng is going to handle this, it will presumably handle it in a way that looks remarkably like this PR... At the moment, kpng just has its own forks of all of these packages...)

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/sig network
/priority backlog

### CODE REVIEW

**Comment by aojea** [comment]
is there a demand for this these days?

**Comment by danwinship** [comment]
Well, for example, right now kpng has its own forks of all of these libraries, and if we staged them to `k8s.io/kube-proxy`, then it could vendor them from there instead...

I think there's agreement that `k8s.io/kube-proxy` should eventually contain the core functionality needed to implement a proxy, though whether that would be in the form of the current `"k8s.io/kubernetes/pkg/proxy"` or the kpng equivalents or something else is still undecided.

**Comment by aojea** [comment]
yeah, I don't disagree, but making the move if is not going to be used sounds like too much code churn for small benefit

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by dims** [comment]
@danwinship Do we need this for 1.27?

**Comment by danwinship** [comment]
I guess I'll close this for now... might get resurrected as part of https://github.com/kubernetes/enhancements/pull/3649

**Pull request closed without merging**
