### PR TITLE
Fix golint errors in pkg/apis/apps

### PR DESCRIPTION
**Pull request by Dingshujie**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix golint errors in pkg/apis/apps

**Which issue(s) this PR fixes**:
Ref #68026

**Special notes for your reviewer**:
None
**Does this PR introduce a user-facing change?**:
None

```release-note
None
```

### CODE REVIEW

**Comment by Dingshujie** [comment]
```release-note
v1.17
```

**Review by hvaara — COMMENTED** [review]
Thanks for the PR, @Dingshujie! 🎉 
I'm not a reviewer, but this looks good to me

**Comment by hvaara** [comment]
Just noticed that this package has been reserved for a [KubeCon Contributor Workshop demo](https://github.com/kubernetes/kubernetes/issues/68026#issuecomment-487635715) and also noted in the [spreadsheet](https://docs.google.com/spreadsheets/d/1VhU6zCk-vaAnbu_XkgsIq5I7jVnezUquWBMhcIN6AJM/edit?ts=5dc6bc92#gid=0).

Is this still reserved for KubeCon @guineveresaenger?

**Pull request merged**
