### PR TITLE
AWS: Update Ubuntu Vivid AMIs

### PR DESCRIPTION
**Pull request by justinsb**
Pick up some updates, and reduce need for users to update manually.

### CODE REVIEW

**Comment by justinsb** [comment]
Source: http://cloud-images.ubuntu.com/locator/ec2/

**Comment by dchen1107** [comment]
@justinsb Do we want to cherrypick this pr to 1.1 branch? or leave it to HEAD?

**Comment by justinsb** [comment]
We should probably cherry-pick to 1.1, and then I plan on giving 1.1 some testing this weekend/next week on AWS!

**Comment by dchen1107** [comment]
cc/ @brendandburns @ihmccreery 

I am not sure if this is required or not for 1.1 release on AWS, but if you decide to do it, you can run script: 

$ hack/cherry_pick_pull.sh upstream/release-1.1 16922

Also I noticed that you sent a bunch of prs, and filed a bunch of issues. Please let us know the priorities and urgencies. We can address them based those. Thanks!

**Comment by roberthbailey** [comment]
LGTM.

**Comment by justinsb** [comment]
I don't think that any of the issues that I filed or my pull requests are
blockers for 1.1. I think this would be nice to get into 1.1, but it is
only a nice to have. I will call them out if I find any that are important
for 1.1

**Pull request merged**
