### PR TITLE
re-enable cascading deployment

### PR DESCRIPTION
**Pull request by jessfraz**
I couldn't reproduce #40433 locally sooo trying on the test infra to make sure I'm not crazy

### CODE REVIEW

**Comment by jessfraz** [comment]
@k8s-bot unit test this

**Comment by jessfraz** [comment]
@liggitt soooo do you think that is ok? or probably a flake or im crazy haha

**Comment by liggitt** [comment]
not sure. I saw it 5 times in a row running locally when trying to re-enable the tests.

**Comment by liggitt** [comment]
@k8s-bot unit test this

**Comment by liggitt** [comment]
@k8s-bot unit test this

**Comment by liggitt** [comment]
@k8s-bot unit test this

**Comment by liggitt** [comment]
@k8s-bot unit test this

**Comment by kargakis** [comment]
I am not able to reproduce this either and haven't seen it in our CI as well. @soltysh was able to repro locally though

**Comment by jessfraz** [comment]
@kargakis hmmm maybe it is something with setup/local env then (i will try on another box)

**Comment by jessfraz** [comment]
cant repro on a different machine :(

**Comment by soltysh** [comment]
I'll get back to this sometime next week and see what might be causing that.

**Comment by brendandburns** [comment]
/lgtm

LGTM from the bulk LGTM tool

**Comment by liggitt** [comment]
Well, five CI runs and no failures… maybe it just fixed itself? (hope springs eternal). Fine with me to re-enable.

**Comment by kargakis** [comment]
@liggitt can you paste logs from the controller manager when you run the test?

**Pull request merged**
