### PR TITLE
Automated cherry pick of #92442 and #98103

### PR DESCRIPTION
**Pull request by ehashman**
Cherry pick of #92442 on release-1.18.
Cherry pick of #98103 on release-1.18.

#92442: Respect grace period when removing mirror pod
#98103: kubelet: Delete static pods gracefully

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
terminationGracePeriodSeconds from pod spec is respected for the mirror pod
Static pods will be deleted gracefully
```

NOTE: I couldn't backport just #98103 as it built on the changes in #92442 which landed in 1.19+ but not 1.18.

### CODE REVIEW

**Comment by ehashman** [comment]
/hold

I also want to backport #98103 on top of this (this fix was blocking for 1.18).

**Review by hasheddan — APPROVED** [review]
/lgtm

**Pull request merged**
