### PR TITLE
Promote JobSuccessPolicy to beta

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Promote JobSuccessPolicy to beta

#### Which issue(s) this PR fixes:

Part of https://github.com/kubernetes/enhancements/issues/3998

#### Special notes for your reviewer:

Hi @tenzen-y, I searched the k/k repo but could not find the promotion PR, so I raised this PR to promote the feature to beta as the KEP is already approved and the doc is being updated. Feel free to close this PR if you have already worked on this in your local branch. Thanks!

I see you left some comments in https://github.com/kubernetes/kubernetes/pull/121863. That PR would be addressed as a part of Job SuccessPolicy beta graduation. 

Unfortunately, that PR is not ready to be merged yet and lacks activities. I want to confirm whether that PR is still in progress and whether it is a blocker for beta promotion.

/cc @alculquicondor @mimowo @kannon92 @tenzen-y

/hold
until the question is answered.

#### Does this PR introduce a user-facing change?

```release-note
Promote JobSuccessPolicy to beta
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/3998
```

### CODE REVIEW

**Review by mimowo — COMMENTED** [review]
/hold
The graduation to Beta requires also e2e tests and the `job_succeeded_total` metric (see [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3998-job-success-completion-policy#beta)). These can be either the same PR or separate, but if separate they should already be reviewed when merging this, to minimize the risk of them not getting into graduation.

**Comment by carlory** [comment]
@mimowo thanks for your reminder. I would  try to add e2e tests and metrics in this PR if @tenzen-y doesn't have bandwidth. BTW, I also want to confirm whether https://github.com/kubernetes/kubernetes/pull/121863 is still a blocker for beta promotion.

**Comment by tenzen-y** [comment]
Actually, I'm working on both tasks.
As my understanding, the deadline is 24th, July.

**Comment by carlory** [comment]
> Actually, I'm working on both tasks. As my understanding, the deadline is 24th, July.

Great. 

/close

**Comment by mimowo** [comment]
> @mimowo thanks for your reminder. I would try to add e2e tests and metrics in this PR if @tenzen-y doesn't have bandwidth. BTW, I also want to confirm whether #121863 is still a blocker for beta promotion.

It would be good to revisit this issue, but I actually think that this is a pre-existing issue, ticketed for a long time, and not part of agreed graduation criteria for Beta in the KEP, so I wouldn't block on it.

**Comment by tenzen-y** [comment]
> > Actually, I'm working on both tasks. As my understanding, the deadline is 24th, July.
> 
> Great.
> 
> /close

Thank you for reminding me.

**Pull request closed without merging**
