### PR TITLE
Graduate the kube-scheduler ComponentConfig to v1beta1

### PR DESCRIPTION
**Pull request by jfbai**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

https://github.com/kubernetes/enhancements/issues/785

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/enhancements/issues/785

**Special notes for your reviewer**:

None

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

/sig scheduling
/assign @ahg-g 
/cc @bsalamat
/cc @k82cn 
/cc @luxas

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
/ok-to-test
/priority important-soon

**Comment by Huang-Wei** [comment]
@ahg-g Do you think this release is a good moment to graduate CC to beta? I'm thinking we need to soak the framework a bit more, so as to gain the confidence to move some structs embedded in legacy Policy API to CC. And also we need to merge the PR that makes fields in CC nil-able first.

**Comment by ahg-g** [comment]
> API to CC. And also we need to merge the PR

Not in this release, but we should start engaging the component config working group to look into our setup, it may take a while, so we should start early.

**Comment by ahg-g** [comment]
/milestone v1.18

can you please rebase?

**Comment by annajung** [comment]
Hello @jfbai  👋 I'm one of the Bug Triage shadows for the 1.18 release. Since this issue is tagged for 1.18, I'd like to check its status. Is this issue intended for milestone 1.18?

Friendly reminder: Code freeze is scheduled for March 5th.

**Comment by annajung** [comment]
Hello @jfbai Checking with you again. Is this issue intended for milestone 1.18?

**Comment by Huang-Wei** [comment]
@annajung Nope, we will postpone it - we are still refining our alpha ComponentConfig APIs in 1.18, which is not stable to be promoted to beta yet.

**Comment by annajung** [comment]
@Huang-Wei Thank you for the update. I will defer the milestone to v.1.19.
/milestone v1.19

**Comment by alculquicondor** [comment]
/close

this is outdated

**Pull request closed without merging**
