### PR TITLE
Automated cherry pick of #69359: Add Create and Update Options to rest param installation

### PR DESCRIPTION
**Pull request by roycaihw**
Cherry pick of #69359 on release-1.12.

#69359: Add Create and Update Options to rest param installation

### CODE REVIEW

**Comment by roycaihw** [comment]
Targeting this cherrypick to 1.12.1.

/kind bug
/cc @apelisse
for review 
/assign @lavalamp
for approval 
/assign @feiskyer 
for cherry-pick approval

**Comment by apelisse** [comment]
Thanks for pushing this @roycaihw. We need to cherry-pick this since it's going to allow the option to appear in generated clients, and we also need to check this option in the openapi to allow dryRun from kubectl.

**Comment by roycaihw** [comment]
Forgot to mention the reason for cherrypicking... @apelisse Thanks for explaining!

**Comment by roycaihw** [comment]
I missed the email notifying that 1.12.1 was going to be cut today... thought it would be two weeks after [1.12.0](https://github.com/kubernetes/kubernetes/releases/tag/v1.12.0). 

We will target 1.12.2 now @feiskyer PTAL

**Pull request merged**
