### PR TITLE
Stop monit kube-addon on nodes.

### PR DESCRIPTION
**Pull request by dchen1107**
#11215

I think this is not critical for v1.0, but could be convinced otherwise. :-)

cc/ @wojtek-t @yujuhong @zmerlynn @brendandburns

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM

**Comment by yujuhong** [comment]
LGTM. Agreed that this is not critical, although monit tends to spam its log without this fix :)

**Comment by gmarek** [comment]
+1.

**Comment by thockin** [comment]
LGTM, after conversation worthwhile for 1.0

**Pull request merged**
