### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by RomanKrasavtsev**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
fix typo

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note
NONE
```

### CODE REVIEW

**Comment by krmayankk** [comment]
how come all tests ran without ok-to-test . Does lgtm does that ?  @BenTheElder  might have some insight ?

**Comment by RomanKrasavtsev** [comment]
Hi @derekwaynecarr @liggitt, I need you help to merge it. Thanks.

**Pull request merged**
