### PR TITLE
Fix misleading trace messages in Schedule

### PR DESCRIPTION
**Pull request by hex108**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
Fix misleading trace messages in Schedule

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig scheduling
/cc @misterikkit

### CODE REVIEW

**Comment by hex108** [comment]
Thanks @misterikkit ! I misunderstood these traces.

**Comment by ahg-g** [comment]
Thanks for fixing this, #78280 fixed this as well and already got LGTMed, so perhaps close this one.

**Comment by misterikkit** [comment]
(sorry the work got duplicated. Looks like both PRs were opened the same day.)

**Pull request closed without merging**
