### PR TITLE
fix missing apps/replicaset in kubectl

### LINKED ISSUE #53040: `kubectl set` commands on ReplicaSet and DaemonSet occasionally return version registration errors
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
create  a ReplicaSet then change its image by kubectl set image command. It returns an error ocassionally like 
error: replicasets/gakki-replicaset no kind "ReplicaSet" is registered for version "apps/v1beta1"

**What you expected to happen**:
image changes without error
**How to reproduce it (as minimally and precisely as possible)**:
yaml file as follows:
```
apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: test-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]}
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
```
execute command:
kubectl create -f test.yaml
kubectl set image rs test-replicaset php-redis=nginx:1.7.9 

**Anything else we need to know?**:
the error happens ocassionally, you can make  several tries to observe this error.  
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.1.51+14cedb9f581d6a-dirty", GitCommit:"14cedb9f581d6a6de367e780e31a8ca1c7b12112", GitTreeState:"dirty", BuildDate:"2017-09-23T08:08:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-alpha.1.281+ba1ab3fd559dd7-dirty", GitCommit:"ba1ab3fd559dd775863477f00a3e8d3bf86583a0", GitTreeState:"dirty", BuildDate:"2017-09-25T11:31:36Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration**:
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #53040

**Special notes for your reviewer**:
/assign @janetkuo 

**Release note**:

```release-note
fix missing apps/replicaset in kubectl
```

### CODE REVIEW

**Comment by janetkuo** [comment]
@dixudx thanks for the fix! Would you also add this to pkg/printers/internalversion/describe.go

**Review by janetkuo — COMMENTED** [review]
@dixudx thanks for the fix! Would you also add this to pkg/printers/internalversion/describe.go

**Comment by pwittrock** [comment]
@janetkuo If you have not already, could you also manually test this for all sorts of ReplicaSets for each of the commands?

**Comment by pwittrock** [comment]
@janetkuo Should we wait for describe?  Otherwise should you fork the commit and file another PR?

**Comment by janetkuo** [comment]
Already manually tested this. I'll fork this one and file another PR.

**Comment by janetkuo** [comment]
Superseded by #53067.

**Pull request closed without merging**
