### PR TITLE
fix golint errors in pkg/controller/volume/events/event

### PR DESCRIPTION
**Pull request by PengJi**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR fixes golint errors inside pkg/controller/volume/events/

**Which issue(s) this PR fixes**:

Fixes #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by BenTheElder** [comment]
/approve
for hack
/uncc
/retest

**Comment by PengJi** [comment]
@gnufied PTAL

**Pull request merged**
