### PR TITLE
Revert "Make fluentd pods critical"

### PR DESCRIPTION
**Pull request by dchen1107**
Reverts kubernetes/kubernetes#39146

### CODE REVIEW

**Comment by dchen1107** [comment]
I give the reason on why I want to revert this pr at: https://github.com/kubernetes/kubernetes/pull/39146#issuecomment-268917019

**Comment by bprashanth** [comment]
LGTM but build might be failing

**Comment by thockin** [comment]
@k8s-bot kubemark e2e test this

**Comment by thockin** [comment]
@k8s-bot bazel test this

**Pull request merged**
