### PR TITLE
Move from random SHA - update github.com/prometheus/client_model to v0.1.0

### PR DESCRIPTION
**Pull request by dims**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
No code changes, just updating go.mod/sum

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
/assign @liggitt 

yet another really easy one, no code changes!

**Comment by BenTheElder** [comment]
https://patch-diff.githubusercontent.com/raw/kubernetes/kubernetes/pull/87093.patch :heart: 
thanks @dims 
/lgtm
/approve

**Pull request merged**
