### PR TITLE
feat: graduate ResourceQuotaScopeSelectors to GA - part2

### PR DESCRIPTION
**Pull request by draveness**
/kind feature
/sig scheduling
/priority important-soon

**What this PR does / why we need it**:

Graduate ResourceQuotaScopeSelectors to GA

**Which issue(s) this PR fixes**:

ref:  https://github.com/kubernetes/kubernetes/issues/82480

**Does this PR introduce a user-facing change?**:

```release-note
The ResourceQuotaScopeSelectors feature has graduated to GA. The `ResourceQuotaScopeSelectors` feature gate is now unconditionally enabled and will be removed in 1.18.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/20190409-resource-quota-ga.md
```

### CODE REVIEW

**Review by ravisantoshgudimetla — APPROVED** [review]
/lgtm

Thanks for the PR @draveness 

/cc @ahg-g

**Comment by liggitt** [comment]
Remove all instances of checking `...Enabled(...ResourceQuotaScopeSelectors)` and assume the result is true. This means you can drop any code that only ran when the feature was disabled, like the code in the strategy fields that gated population of that field.

**Comment by draveness** [comment]
> Remove all instances of checking `...Enabled(...ResourceQuotaScopeSelectors)` and assume the result is true. This means you can drop any code that only ran when the feature was disabled, like the code in the strategy fields that gated population of that field (and associated unit test)

Thanks, Jordan. I have addressed the comments

**Pull request merged**
