### PR TITLE
Automated cherry pick of #31559

### PR DESCRIPTION
**Pull request by bprashanth**
Cherry pick of #31559 on release-1.4.

#31559: Networking test rewrite

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36786)

### CODE REVIEW

**Comment by bprashanth** [comment]
Fixes https://github.com/kubernetes/kubernetes/issues/33669 and some other issue that I can't remember the name of but was assigned to Bowei at some point, this is just a test cherry-pick into the 1.4 branch

**Comment by bprashanth** [comment]
The lint failure is from a file I didn't touch, maybe the branch itself fails verification? 
```
W1115 23:41:04.543] pkg/storage/etcd3/store_test.go:548:1: context.Context should be the first parameter of a function
W1115 23:41:04.543] 
W1115 23:41:04.543] Please fix the above errors. You can test via "golint" and commit the result.
W1115 23:41:04.543] 
```

So is the unittest failure: 
```
go test -v k8s.io/kubernetes/pkg/util/net -run TestCloneTLSConfig$
=== RUN   TestCloneTLSConfig
--- FAIL: TestCloneTLSConfig (0.00s)
	http_test.go:72: New fields seen in http.Transport: [DynamicRecordSizingDisabled Renegotiation]
		Add to CopyClientTLSConfig if client-relevant, then add to expected list in TestCopyClientTLSConfig
FAIL
exit status 1
FAIL	k8s.io/kubernetes/pkg/util/net	0.038s
```

@jessfraz ignore, retry or did I just bork the cherrypick?

**Comment by jessfraz** [comment]
can we just fix the lint error as well?

**Comment by jessfraz** [comment]
I an do it in another PR, but it looks like 2 other tests are failing aside from that

**Comment by jessfraz** [comment]
ping @ixdy I think the release branch is building with the wrong version of go, on further analysis of the lint errors

**Comment by ixdy** [comment]
sure is.

From https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/36786/pull-kubernetes-unit/5241/:
```
REPO_DIR=/var/lib/jenkins/workspace/pull-kubernetes-unit/go/src/k8s.io/kubernetes -e HOST_ARTIFACTS_DIR=/var/lib/jenkins/workspace/pull-kubernetes-unit/go/src/k8s.io/kubernetes/_artifacts -i gcr.io/k8s-testimages/kubekins-test:1.5-v20161109-d9a98f2 bash -c 'cd kubernetes && ./hack/jenkins/test-dockerized.sh'
```

We should be using a 1.4 kubekins-test image. @fejta @krzyzacy I don't know how we choose which test image to use, but it appears to be wrong.

**Comment by ixdy** [comment]
Oh, this worked correctly until https://github.com/kubernetes/test-infra/pull/1068.

**Comment by jessfraz** [comment]
Thanks so much!

**Comment by ixdy** [comment]
While we were using the wrong `kubekins-test` image, that has now been fixed, but we still have the `golint` failure, and it's due to a different reason: https://github.com/kubernetes/kubernetes/issues/37254

**Comment by krzyzacy** [comment]
test-go-release-1.4 is green now, retry this

**Comment by krzyzacy** [comment]
@k8s-bot test this

**Comment by krzyzacy** [comment]
@k8s-bot kops aws e2e test this

**Comment by jessfraz** [comment]
@k8s-bot verify test this

**Comment by jessfraz** [comment]
@k8s-bot verify test this

**Comment by jessfraz** [comment]
all is green merging

**Pull request merged**
