### PR TITLE
optimize DefaultTolerationSeconds admission controller

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

As `DefaultTolerationSeconds ` will be enabled by default, so this improves its performance.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
flaky test

/retest

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/59740)

**Pull request merged**
