### PR TITLE
kube-apiserver: add "client" and "cn" labels to client_certificate_expiration_seconds metric

### PR DESCRIPTION
**Pull request by gmiroshnykov**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This commit transforms `client_certificate_expiration_seconds` from a single
histogram into a histogram vector, adding two labels: `client` and `cn`.

`client` contains an IP address of a client that initiated a connection and
`cn` contains a Common Name of a client certificate.

This metric can be used to get an early warning for cluster admins that they have
(a certain amount of) clients talking to the apiserver using client certificates
that are about to expire. Without a client IP or a Common Name, it's very difficult
to pinpoint a particular client that has a stale certificate - you have to resort to
measures like capturing traffic with tcpdump and then look for TLS handshakes
involving stale certificates.

**Special notes for your reviewer**:

I don't think changing Prometheus metrics by adding labels constitutes a breaking API change, but you should probably note that.

This change can also lead a higher resource usage by Prometheus in case the list of client IPs or their Common Names is unbound - maybe in some public, multi-tenant Kubernetes installations?

**Does this PR introduce a user-facing change?**:

```release-note
kube-apiserver: add "client" and "cn" labels to client_certificate_expiration_seconds metric
```

### CODE REVIEW

**Comment by laggyluke** [comment]
CLA should be sorted now.

**Comment by logicalhan** [comment]
Adding labels is, in fact, a breaking metrics API change. Additionally, the client label you want to introduce is very unbounded, which is highly undesirable. We have had issues with unbounded metric labels causing memory leaks in the past, so this is something we are quite cautious about. 

/cc @brancz

**Comment by laggyluke** [comment]
I completely understand and share the concerns regarding unbounded metric labels.

But I also find the current, labelless version of this metric pretty frustrating: it will show you that *something*, *somewhere* is talking to your control plane using a client cert that's about to expire, but will give you zero details about what that something is and where the requests are coming from. And apiserver's logs won't mention anything until the certificate actually expires, at which point finding an offending client is very straightforward, but at that point you're basically dealing with an outage that could've been prevented.

By the way, if anyone has other ideas of how to deal with this problem in general - I'd be very happy to discuss them.

**Comment by sadlil** [comment]
> Adding labels is, in fact, a breaking metrics API change.
I think this can be handled by introducing a new metric instead of modifying `clientCertificateExpirationHistogram`.

And what do you guys think about adding log exposing `client` and `cn`, if certificates are about to expire instead of adding them in labels? @logicalhan @laggyluke

**Comment by brancz** [comment]
> Adding labels is, in fact, a breaking metrics API change. Additionally, the client label you want to introduce is very unbounded, which is highly undesirable. We have had issues with unbounded metric labels causing memory leaks in the past, so this is something we are quite cautious about.

There are no stability guarantees in place for metrics today, we are free to do these types of changes. These changes in particular are too high cardinality though I believe, at least client IP is. Common name *after* successful validation could be discussable, but likely to be in the same category. I think logging this is a better approach if the current data is not enough. We actually have great success with the metric as is. Could you elaborate on a situation where the current metrics were insufficient?

**Comment by logicalhan** [comment]
> There are no stability guarantees in place for metrics today, we are free to do these types of changes.

I agree that we have no explicit stability guarantees in place at the moment, but I don't think that means we are free to make these sorts of changes, which has demonstrably been true with the difficulty of getting changes through for metrics-overhaul.
 
>  ...logging this is a better approach if the current data is not enough.

Yes, given the unbounded cardinality of IP addresses, this sort of data is precisely the type we do not want to emit as a metric but instead log out. Why not log out warnings in the apiserver when cert expiration approach some threshold and alert against those?

**Comment by laggyluke** [comment]
> Could you elaborate on a situation where the current metrics were insufficient?

The current metrics can help us answer the following questions:

* Are there any clients talking to the apiserver with client certificates that are about to expire?
* Roughly how much time do we have until client certificates actually expire?
* What's the rate of the incoming requests from those clients?

It *does not* help to answer the following questions:

* *How many clients are there?*
* *Who are those clients?*

Sometimes you can infer the answers from the data that's already available, but as your setup gets more complex (multi-tenancy, multiple clusters talking to each other etc.) it gets progressively more difficult to immediately identify those clients.

> Why not log out warnings in the apiserver when cert expiration approach some threshold and alert against those?

Indeed, that might be a better approach. I guess we should make that threshold configurable to accommodate various certificate lifetimes.

So let me close this PR and start working on logging instead.

**Comment by silenceper** [comment]
@gmiroshnykov  Have you submitted relevant PR to document this client information?

**Comment by gmiroshnykov** [comment]
@silenceper Unfortunately I never finished that PR.

In retrospect, this problem sounds quite niche.
I'm no longer using long-lived client certificates.
Maybe a more pragmatic approach would be installing a front proxy in front of the API server and logging incoming connections with soon-to-be-expired client certs.

**Comment by silenceper** [comment]
Understood, thanks for the reply. @gmiroshnykov

**Pull request closed without merging**
