### PR TITLE
iscsi: use global path to retrieve iscsi portal and iqn

### LINKED ISSUE #18744: Panic when tearing down iscsi connection
Kubelet version: 1.1.3
OS: Centos 7.1

We are currently seeing an issue where each time an iscsi volume gets torn down there is a panic in iscsi_util.go. This prevents us from locking the iscsi target to only allowing one login per volume and can therefor cause (and has caused) data loss due to one volume being accessed by two hosts by mistake

```
W1216 07:18:31.527192    7970 kubelet.go:1588] Orphaned volume "d0ccbd99-a3c4-11e5-8a65-0cc47a4c5dae/data" found, tearing down volume
Dec 16 07:18:31 srv06 kubelet[7970]: E1216 07:18:31.556498    7970 util.go:82] Recovered from panic: "slice bounds out of range" (runtime error: slice bounds out of range)
Dec 16 07:18:31 srv06 kubelet[7970]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/util.go:76
Dec 16 07:18:31 srv06 kubelet[7970]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/util.go:64
Dec 16 07:18:31 srv06 kubelet[7970]: /usr/src/go/src/runtime/asm_amd64.s:402
Dec 16 07:18:31 srv06 kubelet[7970]: /usr/src/go/src/runtime/panic.go:387
Dec 16 07:18:31 srv06 kubelet[7970]: /usr/src/go/src/runtime/panic.go:18
Dec 16 07:18:31 srv06 kubelet[7970]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/iscsi/iscsi_util.go:138
Dec 16 07:18:31 srv06 kubelet[7970]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/iscsi/disk_manager.go:94
Dec 16 07:18:31 srv06 kubelet[7970]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/iscsi/iscsi.go:189
Dec 16 07:18:31 srv06 kubelet[7970]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/volume/iscsi/iscsi.go:185
Dec 16 07:18:31 srv06 kubelet[7970]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1592
Dec 16 07:18:31 srv06 kubelet[7970]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1770
Dec 16 07:18:31 srv06 kubelet[7970]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1987
Dec 16 07:18:31 srv06 kubelet[7970]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:808
Dec 16 07:18:31 srv06 kubelet[7970]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:777
Dec 16 07:18:31 srv06 kubelet[7970]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/util.go:125
Dec 16 07:18:31 srv06 kubelet[7970]: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/util/util.go:126
```

This seems to be the same as #15556.
Are there any plans on backporting that release into the 1.1 branch?

### PR DESCRIPTION
**Pull request by rootfs**
backport to branch release-1.1

this is to fix #18744 

@saad-ali

### CODE REVIEW

**Comment by saad-ali** [comment]
LGTM

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Pull request merged**
