### PR TITLE
replace the deprecated handler function with promhttp.Handler in kube-proxy

### PR DESCRIPTION
**Pull request by yeya24**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
replace the deprecated handler function with promhttp.Handler in kube-proxy

**Special notes for your reviewer**:

```release-note
None
```

### CODE REVIEW

**Comment by yeya24** [comment]
@brancz @AdamDang  I open a new PR for #73366. Please review

**Review by danielqsj — APPROVED** [review]
/lgtm

**Comment by brancz** [comment]
My comment https://github.com/kubernetes/kubernetes/pull/73366#issuecomment-461815935 still holds, so this looks good to me. I can't approve, but @mikedanese had some questions on the other PR that my comment should have resolved so assigning him.

/assign @mikedanese 

/lgtm

**Pull request closed without merging**
