### PR TITLE
Check loopback and link-local multicast endpoints

### LINKED ISSUE #10349: Block localhost service/endpoint addresses in apiserver proxy
In #8989 we blocked proxying to 169.254.0.0/16 but not to localhost addresses.
The first part can be bypassed by creating a proxy to localhost:4001 and talking to the etcd server directly. You can then insert a new endpoint that points to 169.254.169.254.

I could only verify this behaviour with the latest git version, but not on GKE since the minion - master communication has changed in the meantime. Though if this is not reproducible on GKE this might not be an issue at all since only admins should be able to add new endpoints. @thockin wdyt?

### PR DESCRIPTION
**Pull request by thockin**
Previously we just disallowed link-local (unicast).  This disallows loopback
and link-local multicast.

Fixes #10349

### CODE REVIEW

**Comment by bprashanth** [comment]
Do we need to document why we disallow link-local (it sounds like we're disallowing the other 2 because we really want to disallow link-local)? It might suffice to say they're special, though I think link-local is used by cloud providers to serve metadata, so it might be the one many people try first.

**Comment by thockin** [comment]
Good point, will push with a new comment.  will add to docs this week.

**Comment by thockin** [comment]
@nikhiljindal there's a problem here - swagger is emitting the "advertise address" flag here, but that's going to be different for every person since this PR makes 127.0.0.1 an invalid address to advertise.  Thoughts on how hard it would be to emit a different address in swagger files?

**Comment by thockin** [comment]
need 1.0 triage, I think this is (sadly) out for 1.0 at this point.

**Comment by bgrant0607** [comment]
Swagger needs to report an address that clients are likely going to be able to reach. We've had multiple bug reports about this. Can we strip out the hostname/address post-generation? @nikhiljindal: would validation and the UI work if we did that?

I'm fine with this change in principle. We need to be sure it ends up in the release notes, since it is a change of behavior.

**Comment by bgrant0607** [comment]
Needs rebase.

**Comment by bgrant0607** [comment]
I'm overloaded with API reviews. I need someone else to wrap up the code review.

**Comment by thockin** [comment]
@nikhiljindal Can we brainstorm some ideas on this?

**Comment by nikhiljindal** [comment]
Hey apologies for the delay in getting to this.

How about passing "advertise-address" flag in update-swagger-spec: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/update-swagger-spec.sh#L52
That ensures that it is the same for everyone?

**Comment by thockin** [comment]
I updated this with a fixed address for swagger.  It's not worse than before (in that it will still confuse users), but not better either.

**Comment by nikhiljindal** [comment]
Thanks!
The swagger-spec changes LGTM.

@bprashanth to give final LGTM.

**Comment by bprashanth** [comment]
LGTM, please file bug or do doc change when you have time

**Comment by thockin** [comment]
Updating docs now, fair point.

**Comment by thockin** [comment]
re-pushed with API and services docs updated

**Pull request merged**
