### PR TITLE
Migrate TaintManager to use watch for listing pods instead of expensi…

### PR DESCRIPTION
**Pull request by krzysied**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Cherry pick of #79370 on release-1.15.

#79370: Migrate TaintManager to use watch for pods instead of list call.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by krzysied** [comment]
Comparison of original kubernetes release 1.14 vs release 1.14 + taint manager fix.
Both versions were tested using density performance test.

## List calls (green line is client=node-controller):
- branch release-1.15 (eae0bfe8c80300a9191d95d8b2f22cb2a8f13a0f)
image
- branch release-1.15 + cherry-pick (#79370)
image

## Call latency:
- branch release-1.15 (eae0bfe8c80300a9191d95d8b2f22cb2a8f13a0f)
image
- branch release-1.15 + cherry-pick (#79370)
image

## Allocation rate:
- branch release-1.15 (eae0bfe8c80300a9191d95d8b2f22cb2a8f13a0f)
image
- branch release-1.15 + cherry-pick (#79370)
image

**Comment by mm4tt** [comment]
/lgtm
This is similar to https://github.com/kubernetes/kubernetes/pull/83666, see https://github.com/kubernetes/kubernetes/pull/83666#issuecomment-539897428 for justification why we should cherry-pick this.

**Pull request merged**
