### PR TITLE
Automated cherry pick of #65507: fix scheduler client construction from configuration files

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #65507 on release-1.11.

#65507: fix scheduler client construction from configuration files

### CODE REVIEW

**Review by bsalamat — APPROVED** [review]
/lgtm

**Comment by bsalamat** [comment]
@calebamiles This is approved for cherrypick from my side, but please take a look yourself.

**Comment by liggitt** [comment]
CI is green and no other commits have merged to the release-1.11 branch. Do we want to mark this retest not required to get the post-merge CI jobs running asap?

**Pull request merged**
