### PR TITLE
Mark namespace e2e [Serial]

### LINKED ISSUE #19026: Namespaces should delete fast enough is flaky in parallel
`Namespaces should delete fast enough (90 percent of 100 namespaces in 150 seconds)` is flaky in parallel.  It was marked as flaky-in-parallel in #13810.

It should be deflaked. Or, if they shouldn't be run in parallel, add the `[Disruptive]` or `[Serial]` label to the test.

### PR DESCRIPTION
**Pull request by derekwaynecarr**
Fixes #19026 

Marking this testing [Serial] to limit any throttling or etcd contention given the significant write load it can produce.

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
Running this test locally, I average a namespace deletion every second when nothing is running in parallel.  Assuming this deflakes the test, I would like to unpend this https://github.com/kubernetes/kubernetes/blob/master/test/e2e/namespace.go#L100

**Comment by ihmccreery** [comment]
Why do we expect this test to only work in serial?  Please add a comment with you reasoning.

Running tests in serial is expensive, so unless we have a good reason to do it, I think we should be investing effort to avoid it.

**Comment by derekwaynecarr** [comment]
@ihmccreery - I added a detailed comment explaining my rationale for marking this test Serial.

**Comment by ihmccreery** [comment]
@derekwaynecarr Wow, great!  Definitely wasn't expecting that much detail, but appreciate it.  LGTM.

**Comment by derekwaynecarr** [comment]
See https://github.com/kubernetes/kubernetes/pull/20076

For a PR that improves the performance of this E2E, but my recommendation to run  Serial still remains.

**Comment by derekwaynecarr** [comment]
Marking p0 since it fixes a p0 issue.

**Pull request merged**
