### PR TITLE
fix: volume stats disabled when value is negative.(Currently, 0 means defualt 1m)

### LINKED ISSUE #96674: --volume-stats-agg-period=0 cannot disable volume agg feature.
**What happened**:
After set --volume-stats-agg-period=0 in kubelet args, the kubelet logs still shows 
```
Nov 13 16:59:47 10-31-3-1 kubelet: I1113 16:59:47.852975    2889 fsHandler.go:135] du and find on following dirs took 37m0.97529016s: [ /var/lib/docker/containers/c99cdff4c4840c22c5d12e638cf3fe46672af9bca7164b0fb717b88acb650809]; will not log again for this container unless duration exceeds 4s
```

**What you expected to happen**:
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
> --volume-stats-agg-period duration     Default: `1m0s`
> --
>   | Specifies interval for kubelet to calculate and cache the volume disk usage for all pods and volumes. To disable volume calculations, set to `0`. (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's `--config` flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)

it should be disabled

**How to reproduce it (as minimally and precisely as possible)**:
add --volume-stats-agg-period=0 to your kubulet config
change du to a bin which will sleep more than 4s. 

**Anything else we need to know?**:
None

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration: vspher
- OS (e.g: `cat /etc/os-release`): centos
- Kernel (e.g. `uname -a`): 
- Install tools: DCE daocloud platform
- Network plugin and version (if this is a network-related bug): parcel( calico and vlan)
- Others:

### PR DESCRIPTION
**Pull request by pacoxu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
> --volume-stats-agg-period duration     Default: `1m0s`
> --
>   | Specifies interval for kubelet to calculate and cache the volume disk usage for all pods and volumes. To disable volume calculations, set to `0`. (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's `--config` flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)

the default  value of  volume-stats-agg-period is 1m0s
However when it is set to be 0, it means disable.

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/stats/fs_resource_analyzer.go#L60-62

- **nil means default, 1m0s.**
- **0  means disable**

I tested it. It will be disabled only if we set it to be '-1s'

I tried to fix it but found that the metav1.Duration default value is zeroDuration, and it cannot decide whether it is 0s or none(not set, which should use default value). 

Current logic: 1m0s will be used even you set it to `0s` or `0`.
So I fix it as a doc issue.

**Which issue(s) this PR fixes**:

Fixes #96674

**Special notes for your reviewer**:
I tested it. It will be disabled only if we set it to be '-1s'

Cause:

> https://github.com/kubernetes/kubernetes/blob/71331d8596575d58bc9089168447be26d5d1a877/cmd/kubelet/app/options/options.go#L484
> ```
>     value, _ := time.ParseDuration("")
>     value0, _ := time.ParseDuration("0s")
>     fmt.Println(value == value0)
> ```
> flag use ParseDuration and DurationVar which cannot distinguish no input and 0s.
> 

**Does this PR introduce a user-facing change?**:
```release-note
Set kubelet option `--volume-stats-agg-period` to negative value to disable volume calculations.
```
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
None
```

It is very confused to make it different for `none` and `0`. So I think doc fix would be a better way IMO.

### CODE REVIEW

**Comment by pacoxu** [comment]
@kubernetes/sig-node-pr-reviews

**Comment by pacoxu** [comment]
@derekwaynecarr Have you had a chance to look at this?

**Comment by ehashman** [comment]
I'm a bit confused. In the linked code in the first comment, it should be disabled for 0 or any negative number (logic is `x <= 0`, has not been changed in 5 years):

https://github.com/kubernetes/kubernetes/blob/e456b45a2a6cfa5998ae99bc3f25c205d4f7848c/pkg/kubelet/server/stats/fs_resource_analyzer.go#L58-L63

Where is the `= 0` case getting overridden to a default? According to https://github.com/kubernetes/kubernetes/issues/96674#issuecomment-730330411 the behaviour is different, but the linked code doesn't suggest it would be. cc @pacoxu

**Comment by pacoxu** [comment]
> I'm a bit confused. In the linked code in the first comment, it should be disabled for 0 or any negative number (logic is `x <= 0`, has not been changed in 5 years):
> 
> https://github.com/kubernetes/kubernetes/blob/e456b45a2a6cfa5998ae99bc3f25c205d4f7848c/pkg/kubelet/server/stats/fs_resource_analyzer.go#L58-L63
> 
> Where is the `= 0` case getting overridden to a default? According to [#96674 (comment)](https://github.com/kubernetes/kubernetes/issues/96674#issuecomment-730330411) the behaviour is different, but the linked code doesn't suggest it would be. cc @pacoxu

https://github.com/kubernetes/kubernetes/blob/71331d8596575d58bc9089168447be26d5d1a877/cmd/kubelet/app/options/options.go#L484

0s will be treated as default 1 minute indeed.
Before running into fs_resource_analyzer.go, the value was already converted to 1m.

**Comment by ehashman** [comment]
Okay I found where this gets overridden from 0 to 1m:

https://github.com/kubernetes/kubernetes/blob/5150d2f8394a35dbe6621e4589cab97935d1ecc7/pkg/kubelet/apis/config/v1beta1/defaults.go#L141-L143


/lgtm

**Comment by pacoxu** [comment]
@mrunalp would you have a look on this？

**Comment by pacoxu** [comment]
It seems only 2-3 active approvers here.   
/assign @mrunalp  @sjenning  
/unassign @dchen1107
 Could you have a look on this?

>     Most approvers seem to be not active now.
>     - Random-Liu
>     - dchen1107
>     - vishh
>     - yujuhong

**Review by mrunalp — APPROVED** [review]
/approve

**Comment by baryluk** [comment]
Shouldn't it say "set to non-positive duration to disable"? 0 will also disable it right?

**Pull request merged**
