### PR TITLE
Ensure container metrics are registered with prometheus even without cadvisor http server

### LINKED ISSUE #13200: Prometheus container metrics not exposed if cadvisor http server is disabled
If `--cadvisor-port=0` is passed to the kubelet, container metrics are not included in the Prometheus metrics endpoint.

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes #13200

### CODE REVIEW

**Comment by vishh** [comment]
@jimmidyson: Are prometheus metrics exposed via cadvisor port?

**Comment by jimmidyson** [comment]
@vishh Not but what happens is the cadvisor collector is registered with prometheus only when starting the cadvisor http server... so not starting the cadvisor http server means no cadvisor metrics available via prometheus.

**Comment by vishh** [comment]
With this change, if we set cadvisor port to `0`, I assume no metrics will be exported to prometheus as well?

**Comment by jimmidyson** [comment]
No that's the current behaviour. With this PR, setting the port to 0 we still get cadvisor metrics in prometheus as we should have. The trick is allowing cadvisor to register the cadvisor collector with prometheus, but never starting the http server for cadvisor. 

Before this PR we were blocking the registration of cadvisor collector with prometheus as well as not starting the http server for cadvisor.

**Comment by vishh** [comment]
Hmm. The reason for disabling cadvisor port is to not expose sensitive metrics data. Whether that data gets exposed via prometheus endpoints or cadvisor endpoints doesn't matter right?

**Comment by yujuhong** [comment]
@vishh, since you've already started reviewing, I assigned the issue to you. Let me know if you're swamped.

**Comment by jimmidyson** [comment]
It means it gets exposed alongside the `/stats` endpoint. The point in disabling the cadvisor port is so that cadvisor isn't directly exposed. Still need the metrics, with the hope in future to be able to disable the read-only port & have authenticated access to the metrics on secure kubelet port for scraping.

**Comment by jimmidyson** [comment]
@vishh Thinking about this a bit more, we're not exposing any info that's not already available via the `/stats` endpoint, just in a different format for ingestion into existing/new prometheus setups.

**Comment by vishh** [comment]
Thats true. I would still prefer for having some mechanism to turn this off, if a cluster admin chooses to. If and when we get rid of `/stats` endpoint, we can figure out a strategy for prometheus as well. WDYT?
Also, does enabling prometheus client take up a port on the node? If so, we need to document it.

**Comment by jimmidyson** [comment]
@vishh Enabling prometheus doesn't take up any extra ports - it just adds a handler to the read-only port, exactly as it does with cadvisor-pod > 0 currently. This can be disabled in the same way as disabling the other "debug" handlers.

**Comment by vishh** [comment]
Thanks for explaining! LGTM!

**Comment by jimmidyson** [comment]
It's always that same failure in all PRs... `[Fail] Services [It] should be able to up and down services`. Hoep someone is looking at fixing that or disabling it if it's so consistently flaky.

**Comment by vishh** [comment]
@jimmydyson: Has an issue been filed for that test?

**Comment by jimmidyson** [comment]
@vishh Yes - #13478

**Comment by jimmidyson** [comment]
@vishh Would you be able to rekick this?

**Comment by quinton-hoole** [comment]
e2e failure is a flake - work ongoing to deflake that test.
@k8s-bot test this again please

**Comment by jimmidyson** [comment]
Thanks @quinton-hoole!

**Pull request merged**
