### PR TITLE
chmod +x kubemark scripts

### PR DESCRIPTION
**Pull request by shyamjvs**
Just noticed. We don't need to do chmod each time.

/cc @wojtek-t @gmarek

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this
/lgtm

**Comment by shyamjvs** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Comment by shyamjvs** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-unit test this

**Pull request merged**
