### PR TITLE
Automated cherry pick of #79731: edit google dns hostname

### PR DESCRIPTION
**Pull request by BenTheElder**
Cherry pick of #79731 on release-1.12.

#79731: edit google dns hostname

### CODE REVIEW

**Review by MrHohn — APPROVED** [review]
/lgtm
/approve

**Comment by BenTheElder** [comment]
looks like an unrelated flake:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/79750/pull-kubernetes-bazel-test/1146531953139257346/
```
executing tests from //staging/src/k8s.io/apiserver/pkg/server:go_default_test
-----------------------------------------------------------------------------
--- FAIL: TestLoopbackHostPort (0.00s)
	config_selfclient_test.go:63: expected IPv6 host to be loopback, got "localhost"
W0703 21:35:56.877311      15 authorization.go:47] Authorization is disabled
W0703 21:35:56.877617      15 authentication.go:55] Authentication is disabled
[restful] 2019/07/03 21:35:56 log.go:33: [restful/swagger] listing is available at http://192.168.10.4:443/swaggerapi
[restful] 2019/07/03 21:35:56 log.go:33: [restful/swagger] http://192.168.10.4:443/swaggerui/ is mapped to folder /swagger-ui/
W0703 21:35:56.891142      15 authorization.go:47] Authorization is disabled
W0703 21:35:56.891289      15 authentication.go:55] Authentication is disabled
[restful] 2019/07/03 21:35:56 log.go:33: [restful/swagger] listing is available at http://192.168.10.4:443/swaggerapi
[restful] 2019/07/03 21:35:56 log.go:33: [restful/swagger] http://192.168.10.4:443/swaggerui/ is mapped to folder /swagger-ui/
W0703 21:35:56.917766      15 authorization.go:47] Authorization is disabled
W0703 21:35:56.917850      15 authentication.go:55] Authentication is disabled
W0703 21:35:56.921491      15 authorization.go:47] Authorization is disabled
W0703 21:35:56.921667      15 authentication.go:55] Authentication is disabled
W0703 21:35:56.991083      15 authorization.go:47] Authorization is disabled
W0703 21:35:56.991290      15 authentication.go:55] Authentication is disabled
[restful] 2019/07/03 21:35:57 log.go:33: [restful/swagger] listing is available at http://192.168.10.4:443/swaggerapi
[restful] 2019/07/03 21:35:57 log.go:33: [restful/swagger] http://192.168.10.4:443/swaggerui/ is mapped to folder /swagger-ui/
W0703 21:35:57.043776      15 authentication.go:55] Authentication is disabled
I0703 21:35:57.054585      15 secure_serving.go:156] Stopped listening on [::]:40071
FAIL
```

/retest

**Comment by aojea** [comment]
/retest
some of the tests are failing because of connectivity issues
> godep: error downloading dep (bitbucket.org/bertimus9/systemstat): https://api.bitbucket.org/1.0/repositories/bertimus9/systemstat: 410 Gone
godep: error downloading dep (bitbucket.org/ww/goautoneg): https://api.bitbucket.org/1.0/repositories/ww/goautoneg: 410 Gone
godep: Error downloading some deps. Aborting restore and check.

**Comment by aojea** [comment]
The pull-kubernetes-bazel-test is failing with 🤔 :
```
Executing tests from //staging/src/k8s.io/apiserver/pkg/server:go_default_test
-----------------------------------------------------------------------------
--- FAIL: TestLoopbackHostPort (0.00s)
	config_selfclient_test.go:63: expected IPv6 host to be loopback, got "localhost"
W0704 21:22:41.660485      15 authorization.go:47] Authorization is disabled
W0704 21:22:41.660873      15 authentication.go:55] Authentication is disabled
[restful] 2019/07/04 21:22:41 log.go:33: [restful/swagger] listing is available at http://192.168.10.4:443/swaggerapi
[restful] 2019/07/04 21:22:41 log.go:33: [restful/swagger] http://192.168.10.4:443/swaggerui/ is mapped to folder /swagger-ui/
W0704 21:22:41.672321      15 authorization.go:47] Authorization is disabled
W0704 21:22:41.672394      15 authentication.go:55] Authentication is disabled
[restful] 2019/07/04 21:22:41 log.go:33: [restful/swagger] listing is available at http://192.168.10.4:443/swaggerapi
[restful] 2019/07/04 21:22:41 log.go:33: [restful/swagger] http://192.168.10.4:443/swaggerui/ is mapped to folder /swagger-ui/
W0704 21:22:41.705711      15 authorization.go:47] Authorization is disabled
W0704 21:22:41.705830      15 authentication.go:55] Authentication is disabled
W0704 21:22:41.719233      15 authorization.go:47] Authorization is disabled
W0704 21:22:41.719406      15 authentication.go:55] Authentication is disabled
W0704 21:22:41.761554      15 authorization.go:47] Authorization is disabled
W0704 21:22:41.761754      15 authentication.go:55] Authentication is disabled
[restful] 2019/07/04 21:22:41 log.go:33: [restful/swagger] listing is available at http://192.168.10.4:443/swaggerapi
[restful] 2019/07/04 21:22:41 log.go:33: [restful/swagger] http://192.168.10.4:443/swaggerui/ is mapped to folder /swagger-ui/
W0704 21:22:41.821248      15 authentication.go:55] Authentication is disabled
I0704 21:22:41.832882      15 secure_serving.go:156] Stopped listening on [::]:43407
FAIL
```

**Comment by BenTheElder** [comment]
rebased. compile error doesn't make any sense...

**Comment by aojea** [comment]
@BenTheElder the verify job fails because is using the bitbucket API 1.0 that was deprecated 
```
godep: error downloading dep (bitbucket.org/bertimus9/systemstat): https://api.bitbucket.org/1.0/repositories/bertimus9/systemstat: 410 Gone
godep: error downloading dep (bitbucket.org/ww/goautoneg): https://api.bitbucket.org/1.0/repositories/ww/goautoneg: 410 Gone
```

> {"type": "error", "error": {"message": "Resource removed", "detail": "This API is no longer supported.\n\nFor information about its removal, please refer to the deprecation notice at: https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/"}

**Comment by BenTheElder** [comment]
1.12 is done :-)

**Pull request closed without merging**
