### PR TITLE
'ReplicationControllerNamespaeLister' word error

### PR DESCRIPTION
**Pull request by StudyNick**
'ReplicationControllerNamespaeLister' word error ,  

modify 'ReplicationControllerNamespaceLister'

### CODE REVIEW

**Comment by StudyNick** [comment]
I signed it!

**Comment by StudyNick** [comment]
I signed it!

**Review by xiangpengzhao — APPROVED** [review]

**Comment by kargakis** [comment]
@k8s-bot verify test this

**Comment by kargakis** [comment]
@StudyNick seems you also need to update https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/listers/core/v1/replicationcontroller_expansion.go#L33

**Comment by liggitt** [comment]
this typo exists in *lots* of files... a global find/replace would be good

**Comment by xiangpengzhao** [comment]
Jenkins verification failed, please run `hack/update-staging-client-go.sh` to fix it.

```
I0416 13:08:37.623]   -// ReplicationControllerNamespaeLister.
I0416 13:08:37.623]   +// ReplicationControllerNamespaceLister.
I0416 13:08:37.623]    type ReplicationControllerNamespaceListerExpansion interface{}
I0416 13:08:37.623]    
I0416 13:08:37.623]    // GetPodControllers returns a list of ReplicationControllers that potentially match a pod.
I0416 13:08:37.624]   /go/src/k8s.io/kubernetes/staging/src/k8s.io/client-go is out of date. Please run hack/update-staging-client-go.sh
I0416 13:08:37.624] FAILED   hack/make-rules/../../hack/verify-staging-client-go.sh	116s
```

**Comment by kargakis** [comment]
Agreed with @liggitt - please reopen if you plan to fix this holistically

**Pull request closed without merging**
