### PR TITLE
Nginx ingress e2es

### PR DESCRIPTION
**Pull request by bprashanth**
Runs the basic ingress conformance suite: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/ingress_utils.go#L85

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31172)

### CODE REVIEW

**Comment by girishkalele** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/e2e/ingress_utils.go, line 69 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172#-KPoOwtJDNWoG8mPSMb3:-KPoOwtJDNWoG8mPSMb4:b123idb) ([raw file](https://github.com/kubernetes/kubernetes/blob/676a18bbbbe64a6af2ea164d688c950ce89f4e8f/test/e2e/ingress_utils.go#L69)):*
> ```Go
> 	address string
> 	ing     *extensions.Ingress
> 	// class is the value of the annoation keyed under
> ```

spelling

---

*[test/e2e/ingress_utils.go, line 754 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172#-KPoOb5jHbL7ugOgTiIy:-KPoOb5jHbL7ugOgTiIz:bt25x30) ([raw file](https://github.com/kubernetes/kubernetes/blob/676a18bbbbe64a6af2ea164d688c950ce89f4e8f/test/e2e/ingress_utils.go#L754)):*
> ```Go
> 	pods, err := cont.c.Pods(cont.ns).List(api.ListOptions{LabelSelector: sel})
> 	ExpectNoError(err)
> 	cont.pod = &pods.Items[0]
> ```

Expect non-zero length for pods.Items before the [0] ?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172)*

**Comment by girishkalele** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/e2e/ingress.go, line 156 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172#-KPoPLWzTfLmmkJ7ztKV:-KPoPLX-fLFQ2DIePtAf:b-z9u1yx) ([raw file](https://github.com/kubernetes/kubernetes/blob/676a18bbbbe64a6af2ea164d688c950ce89f4e8f/test/e2e/ingress.go#L156)):*
> ```Go
> 			jig.class = "nginx"
> 			nginxController = &NginxIngressController{ns: ns, c: jig.client}
> 			ExpectNoError(gcloudCreate("firewall-rules", fmt.Sprintf("ingress-80-443-%v", ns), framework.TestContext.CloudConfig.ProjectID, "--allow", "tcp:80,tcp:443", "--network", "e2e"))
> ```

To deflake from GCE API flakes, probably need retries here or inside gcloudCreate()/gcloudDelete().

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172)*

**Comment by girishkalele** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/e2e/ingress_utils.go, line 566 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172#-KPoPdY4PJodDl2J-EMB:-KPoPdY4PJodDl2J-EMC:b-ozueiz) ([raw file](https://github.com/kubernetes/kubernetes/blob/676a18bbbbe64a6af2ea164d688c950ce89f4e8f/test/e2e/ingress_utils.go#L566)):*
> ```Go
> 	j.ing = ingFromManifest(mkpath("ing.yaml"))
> 	j.ing.Namespace = ns
> 	j.ing.Annotations = map[string]string{"kubernetes.io/ingress.class": j.class}
> ```

Is the annotation "kubernetes.io/ingress.class" defined somewhere else ? Seems duplicated.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172)*

**Comment by bprashanth** [comment]
*[test/e2e/ingress.go, line 156 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172#-KPoPLWzTfLmmkJ7ztKV:-KPsa2V1Am-P1vdOdrXW:b-b62ueo) ([raw file](https://github.com/kubernetes/kubernetes/blob/676a18bbbbe64a6af2ea164d688c950ce89f4e8f/test/e2e/ingress.go#L156)):*
<details><summary><i>Previously, girishkalele (Girish Kalele) wrote…</i></summary>
> To deflake from GCE API flakes, probably need retries here or inside gcloudCreate()/gcloudDelete().
</details>
I think this is a larger issue for all our e2es and kube-up (gcloud retries), right now it's pretty obvious when this fails from a gcloud flake and it's just ignored

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172)*

**Comment by girishkalele** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/e2e/ingress.go, line 156 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172#-KPoPLWzTfLmmkJ7ztKV:-KPsbEmb9BWEUBr14rph:b-n8h8r5) ([raw file](https://github.com/kubernetes/kubernetes/blob/676a18bbbbe64a6af2ea164d688c950ce89f4e8f/test/e2e/ingress.go#L156)):*
<details><summary><i>Previously, bprashanth (Prashanth B) wrote…</i></summary>
> I think this is a larger issue for all our e2es and kube-up (gcloud retries), right now it's pretty obvious when this fails from a gcloud flake and it's just ignored
</details>
This is true - I see gcloudCreate/gcloudDeletes that already exist without retries.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172)*

**Comment by girishkalele** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172)*

**Comment by bprashanth** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/e2e/ingress_utils.go, line 69 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172#-KPoOwtJDNWoG8mPSMb3:-KPsaLs19StyW_4wIrVm:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/676a18bbbbe64a6af2ea164d688c950ce89f4e8f/test/e2e/ingress_utils.go#L69)):*
<details><summary><i>Previously, girishkalele (Girish Kalele) wrote…</i></summary>
> spelling
</details>
Done.

---

*[test/e2e/ingress_utils.go, line 566 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172#-KPoPdY4PJodDl2J-EMB:-KPsaQki3BYsj3QuBwfE:btbiwgd) ([raw file](https://github.com/kubernetes/kubernetes/blob/676a18bbbbe64a6af2ea164d688c950ce89f4e8f/test/e2e/ingress_utils.go#L566)):*
<details><summary><i>Previously, girishkalele (Girish Kalele) wrote…</i></summary>
> Is the annotation "kubernetes.io/ingress.class" defined somewhere else ? Seems duplicated.
</details>
yeah in contrib/ingress, not worth importing as a godep for just the annotation names. Tests will break and we'll change it. Added comment.

---

*[test/e2e/ingress_utils.go, line 754 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172#-KPoOb5jHbL7ugOgTiIy:-KPsbXxv_fqjp5McAldD:brp1v03) ([raw file](https://github.com/kubernetes/kubernetes/blob/676a18bbbbe64a6af2ea164d688c950ce89f4e8f/test/e2e/ingress_utils.go#L754)):*
<details><summary><i>Previously, girishkalele (Girish Kalele) wrote…</i></summary>
> Expect non-zero length for pods.Items before the [0] ?
</details>
It doesn't actually need to be 1. We deploy the nginx controller as an RC, there will be as many as there are replicas for the RC. Currently that's one (we don't need to assert that an rc with replicas=1 only produces 1 replica). Each nginx pod will put the external ip of the node it's on into ingress status, we're just getting one of these ips to test. 

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172)*

**Comment by girishkalele** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/e2e/ingress_utils.go, line 754 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172#-KPoOb5jHbL7ugOgTiIy:-KPxWIRz8reap9KgdiaF:bwigukn) ([raw file](https://github.com/kubernetes/kubernetes/blob/676a18bbbbe64a6af2ea164d688c950ce89f4e8f/test/e2e/ingress_utils.go#L754)):*
<details><summary><i>Previously, bprashanth (Prashanth B) wrote…</i></summary>
> It doesn't actually need to be 1. We deploy the nginx controller as an RC, there will be as many as there are replicas for the RC. Currently that's one (we don't need to assert that an rc with replicas=1 only produces 1 replica). Each nginx pod will put the external ip of the node it's on into ingress status, we're just getting one of these ips to test. 
</details>
I meant if the list of pods was empty, the Items[0] would panic.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172)*

**Comment by girishkalele** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172)*

**Comment by bprashanth** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/e2e/ingress_utils.go, line 754 \[r1\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172#-KPoOb5jHbL7ugOgTiIy:-KPxXuug3CsDptcuOStv:b-korg6e) ([raw file](https://github.com/kubernetes/kubernetes/blob/676a18bbbbe64a6af2ea164d688c950ce89f4e8f/test/e2e/ingress_utils.go#L754)):*
<details><summary><i>Previously, girishkalele (Girish Kalele) wrote…</i></summary>
> I meant if the list of pods was empty, the Items[0] would panic.
</details>
That would happen if something deleted the pods out of band, and we list pods before the rc recreates them, because we wait for ready replicas in previous line. Added a check for a clearer failure mode. 

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172)*

**Comment by girishkalele** [comment]
Reviewed 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172)*

**Comment by girishkalele** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172#-:-KPxhM1h79Ga6uBY52yN:bnfp4nl)*

**Comment by girishkalele** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31172)*

**Comment by girishkalele** [comment]
LGTM from Reviewable did not turn into an LGTM label.

**Pull request merged**
