### PR TITLE
Use docker client instead of docker binary for image pulls in test/e2e_node

### PR DESCRIPTION
**Pull request by mattjmcnaughton**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Resolve a TODO in test/e2e_node around using the docker client instead of the docker
binary for image pulls.

While there are other uses of the docker binary in the test/e2e_node
test suite, we prefer to use pure Go when possible.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
cc @Random-Liu 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```

### CODE REVIEW

**Review by marcocali — APPROVED** [review]

**Comment by mattjmcnaughton** [comment]
cc @dims

Given our slack chat, I'm I correct you'd vote against this change? Happy to update this PR to just deleting the TODO instead :)

**Comment by dims** [comment]
/hold

yes let us please close this. we are trying to go the other way.... drop uses of docker/docker imports.

**Comment by mattjmcnaughton** [comment]
Sounds good :)

I'll create (and tag you in) a separate pr to remove the TODO comment so that future readers aren't confused.

**Pull request closed without merging**
