### PR TITLE
Detail supported media types within OpenAPI v2 data

### PR DESCRIPTION
**Pull request by lengrongfu**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Provides better clarity of all operations supported by a K8s cluster.
#### Which issue(s) this PR fixes:

Fixes #https://github.com/kubernetes/kubernetes/issues/113028

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lengrongfu** [comment]
🤕 My misoperation close this pr and will reopen it later.

**Comment by sftim** [comment]
/retitle Add HTTP content type negotiation for OpenAPI v2

**Comment by sftim** [comment]
Actually
/retitle Detail supported media types within OpenAPI v2 data

**Pull request closed without merging**
