### PR TITLE
add flag test function

### PR DESCRIPTION
**Pull request by NickrenREN**
add TestAddFlagsFlag() function to test kube-controller-manager's flags in new file options_test.go in cmd/kube-controller-manager/app/options/

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36639)

### CODE REVIEW

**Comment by NickrenREN** [comment]
@dims  i have already use the gofmt command to test my codes,  ok in my host.
but Jenkins verification always build failed .
Should i begin a new line with 8 space keys ?

**Comment by dims** [comment]
@NickrenREN Can you try `hack/verify-gofmt.sh` and `hack/update-gofmt.sh` and see if they work any better?

**Comment by NickrenREN** [comment]
@dims i have tried

nickren@nickren-ubuntu14:~/GoProject/src/NickrenREN/kubernetes$ hack/verify-gofmt.sh
nickren@nickren-ubuntu14:~/GoProject/src/NickrenREN/kubernetes$ hack/update-gofmt.sh
nickren@nickren-ubuntu14:~/GoProject/src/NickrenREN/kubernetes$

**Comment by dims** [comment]
@k8s-bot ok to test

**Comment by NickrenREN** [comment]
@lavalamp   Jenkins GCE e2e  build failed . But not related to the test code.

**Comment by NickrenREN** [comment]
@lavalamp  checks passed . please review

**Comment by NickrenREN** [comment]
@lavalamp   @dims   I add a test function and checks passed.  Could one of you help with review ? Thanks

**Comment by mikedanese** [comment]
This is a test of https://github.com/spf13/pflag, as such the unit test should be proposed there. We should not unit test our dependencies in the kubernetes code base.

**Comment by lavalamp** [comment]
Apologies for not being responsive on this pull, I was OOO most of last month but I'm not sure why I didn't see it before that.

**Pull request closed without merging**
