### PR TITLE
Bump ectd client and fix initializing IP/Port allocators when etcd is not reachable

### PR DESCRIPTION
**Pull request by fgrzadkowski**
This PR reintroduces newer version of go-etcd client library (reverted in #9447). It also adds additional debugging to service allocator code to help debug potential failures that I was not able to reproduce locally.

@wojtek-t @smarterclayton 
@saad-ali (currentl oncall)

NOTE 1: If you see other places where logging might be useful please add a comment.
NOTE 2: Please do not merge this PR. I will do this tomorrow morning so that I can closely watch jenkins and revert it once I gather more data for debugging.

### CODE REVIEW

**Comment by wojtek-t** [comment]
As discussed offline - it seems that the Jenkins failure is exactly the replication of the problem.

**Comment by mnemotiv** [comment]
I don't know where it should be put and whether it's related, but it would be very helpful if while using --etc-config (go-etcd) flag it would output any errors to kube-apiserver, because for now - if it fails - no logs are being shown.

**Comment by fgrzadkowski** [comment]
@k8s-bot test this please

**Comment by fgrzadkowski** [comment]
@k8s-bot test this please

**Comment by fgrzadkowski** [comment]
@k8s-bot test this please

**Comment by fgrzadkowski** [comment]
@k8s-bot test this please

**Comment by fgrzadkowski** [comment]
@k8s-bot test this please

**Comment by fgrzadkowski** [comment]
This is ready for review.

Assigning to @smarterclayton since one of the commits fixes a bug in allocator code.

**Comment by fgrzadkowski** [comment]
@davidopp 
Results from density test with 30 pods per node in 100 node cluster with n1-standard-4 master:

```
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.99 Latency:1.605515s}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.9 Latency:1.270142s}
INFO: Top latency metric: {Verb:LIST Resource:pods Quantile:0.5 Latency:529.251ms}
INFO: Top latency metric: {Verb:POST Resource:bindings Quantile:0.99 Latency:444.361ms}
INFO: Top latency metric: {Verb:PUT Resource:pods Quantile:0.99 Latency:426.816ms}
```

This is way better (~25%) than the usual run for density test.

**Comment by fgrzadkowski** [comment]
Shippable complains about ```hack/run-gendocs.sh``` but I run it locally and it was a no-op :/

@smarterclayton I can't find any of your comments (even those I've already addressed). Is there anything else I should fix with this PR? It'd be great to have it merged today.

**Comment by smarterclayton** [comment]
Had one comment that got last.

**Comment by smarterclayton** [comment]
LGTM but I'm not sure what the shippable failure is.

**Comment by satnam6502** [comment]
Issue? Risk level? Milestone? Does it need to be merged anyway?

**Comment by fgrzadkowski** [comment]
@satnam6502 This fixes #9444 and will improve performance by reducing cpu usage on master machine. Based on discussion with @davidopp we want to merge this change before v1.0.

I'd say that risk is medium-high due to multiple changes in etcd client library since our last update.

I've run e2e tests multiple times (using jenkins and locally) and it looks good.

**Comment by davidopp** [comment]
Thanks for merging. I think this merits being included in 1.0 since it substantially improves performance.

**Comment by quinton-hoole** [comment]
See #10146.  There is quite possibly a bug in this PR - it appears to be causing recovery after an etcd failure not to work reliably.

**Pull request merged**
