### PR TITLE
kubelet watch-manager test, restore watch-based manager default

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
* adds an integration test exercising the watch-based secret manager to ensure http/2 streaming issues are resolved
* restores the watch-based cache manager (reverts https://github.com/kubernetes/kubernetes/pull/74755)

**Which issue(s) this PR fixes**:
xref #74412

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
@liggitt `x/net` is tricky :) see https://github.com/kubernetes/kubernetes/pull/71501

**Comment by liggitt** [comment]
> @liggitt `x/net` is tricky :) see #71501

yeah :(

**Comment by spiffxp** [comment]
/milestone v1.14
Pretty sure we want this to land as part of the v1.14 release

**Comment by liggitt** [comment]
yeah, will coordinate with @dims and @cblecker on which of this or https://github.com/kubernetes/kubernetes/pull/71501 go in

**Comment by wenjiaswe** [comment]
@liggitt yes, this one is pretty tricky. Along with dependency update in K8s, a bunch of other places need to be updated too: https://github.com/kubernetes/kubernetes/pull/71501#issuecomment-466739003. 

/cc @PrasadG193

**Comment by liggitt** [comment]
this isn't a regression, so retargeting to 1.15

/milestone v1.15

**Comment by wojtek-t** [comment]
@liggitt - with upgrade to go1.12 already happened, IIUC, we only need the last commit from it, right?
If so, can we still have it in 1.14 (this is just test addition)?

**Comment by liggitt** [comment]
Unfortunately, since we explicitly vendor golang.org/x/net, no

**Comment by liggitt** [comment]
since https://github.com/kubernetes/kubernetes/pull/75289 was able to pick up the go 1.12 level of golang.org/x/net, and feedback from @kubernetes/sig-scalability-misc is that the cache-based manager does not perform as well in scale tests, moving this back into the milestone for consideration

**Comment by wojtek-t** [comment]
/lgtm

Thanks a lot for that PR Jordan!

/hold
To ensure that we don't merge it before we're sure we won't be forced to revert golang to 1.11.

**Comment by spiffxp** [comment]
Unclear if the test failure is related to this PR or not
```
I0313 16:37:21.458] --- FAIL: TestWatchBasedManager (0.97s)
I0313 16:37:21.459] testserver.go:195: failed to launch server: failed to set default ServerRunOptions: error creating self-signed certificates: unable to generate self signed cert: failed to write cert fixture to cmd/kube-apiserver/app/testing/testdata/127.0.0.1_10.0.0.1_kubernetes.default.svc-kubernetes.default-kubernetes-localhost.crt: open cmd/kube-apiserver/app/testing/testdata/127.0.0.1_10.0.0.1_kubernetes.default.svc-kubernetes.default-kubernetes-localhost.crt: no such file or directory
I0313 16:37:21.459] FAIL
```

**Comment by liggitt** [comment]
that's the test this PR added, but it should not be running in that suite... added a missing `integration` tag into the auto-generated BUILD file to match other tests

**Comment by liggitt** [comment]
CI is now green, holding pending the go1.12 decision

**Comment by wojtek-t** [comment]
@liggitt - with the go1.12.1 being merged (and it seems it helps with the issues), can we unhold this one?

**Comment by liggitt** [comment]
> with the go1.12.1 being merged (and it seems it helps with the issues), can we unhold this one?

Yes
/hold cancel

**Pull request merged**
