### PR TITLE
Fix API docs for audit APIs

### PR DESCRIPTION
**Pull request by tengqm**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

The `*`s in the source comment is confusing the API reference generator. They are treated as symbols for bold texts when generating reference docs. This PR replaces the quote marks with backtiqs so that the reference generator can properly handle them.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sftim** [comment]
LGTM

**Comment by sftim** [comment]
/priority backlog

Worth having, mind!

**Comment by tengqm** [comment]
Got this error when running `hack/update-codegen.sh` ...

```
$ hack/update-codegen.sh 
go version go1.21.1 darwin/amd64
+++ [1003 18:35:36] Generating protobufs for 66 targets
2023/10/03 18:35:40 Unrecognized package: k8s.io/apimachinery/pkg/apis/testapigroup/v1
!!! [1003 18:35:40] Call tree:
!!! [1003 18:35:40]  1: hack/update-codegen.sh:919 codegen::protobuf(...)
```

Don't know how to proceed now.

**Comment by cici37** [comment]
/triage accepted
Please apply api-review label when it is ready to review. Thanks!

**Pull request merged**
