### PR TITLE
[release-1.21] backports k/utils bump (PR#107637) to 1.21

### PR DESCRIPTION
**Pull request by rphillips**
What type of PR is this?
/kind bug

regenerated the k8s.io/utils inotify bump to 1.21: ref https://github.com/kubernetes/kubernetes/pull/107637

What this PR does / why we need it:
https://github.com/kubernetes/kubernetes/issues/100241#issuecomment-1016399463

Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/100241

Special notes for your reviewer:

Does this PR introduce a user-facing change?
```release-note
Kubelet: Fixes memory usage within the kubelet's inotify subsystem.
```

### CODE REVIEW

**Review by mrunalp — APPROVED** [review]

**Comment by rphillips** [comment]
/assign @liggitt @dims

for approval

**Comment by liggitt** [comment]
add a release note

/lgtm
/approve

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Pull request merged**
