### PR TITLE
delete gce/delete-stranded-load-balancers.sh

### PR DESCRIPTION
**Pull request by ahmetb**
This script was written by brendandburns but unmaintained since 2015 and is
not working anymore.

When a GKE cluster is deleted and therefore the networking/LB-related pieces
leak, this script is meant to clean them up.

I suspect this is completely broken:

1. For some reason, now when the cluster leaks these resources, the
"gcloud compute target-pools list" is returning empty results, so this script
is not deleting anything in practice today.

2. The algorithm not deleting a lot of important resources like backend-services,
url-maps, health-checks, target-http-proxies. I suspect it is not up to date
with how ingress-gce controller works today.

I propose we delete this. I do not think anyone knows/uses this script.

/sig gcp
/sig network
/kind cleanup
/area ingress

### CODE REVIEW

**Comment by nikhiljindal** [comment]
cc @bowei @nicksardo 
Related: https://github.com/kubernetes/ingress-gce/issues/136

**Comment by nicksardo** [comment]
Those resources are for an external network LB - not an L7 LB.  Although it's out of date, I think it's still useful. Can we find a better home for this or should it stay where it is?

**Comment by ahmetb** [comment]
@nicksardo my bad, I assumed they're for Ingress.

I think unless anyone is willing to maintain this script, we should consider deleting.

**Comment by nicksardo** [comment]
None of us knew about its existence. Let's get it working and maybe expand it to ingress and ILB. 
/close

**Pull request closed without merging**
