### PR TITLE
Use iteration to make the GeneralPredicates code cleaner

### PR DESCRIPTION
**Pull request by xiaoanyunfei**
**What type of PR is this?**

 /kind cleanup

**What this PR does / why we need it**:

Use iteration to make the GeneralPredicates code cleaner

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
/sig scheduling

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
/kind cleanup
/ok-to-test

**Review by draveness — COMMENTED** [review]
/lgtm

The code looks much more concise

Thanks @xiaoanyunfei

**Comment by alculquicondor** [comment]
I don't see this adding much value. But I'll leave it to approvers. Could you please be more explicit in your PR titles and/or descriptions?

**Pull request merged**
