### PR TITLE
fix completely typo

### PR DESCRIPTION
**Pull request by timchenxiaoyu**
fix completely typo

### CODE REVIEW

**Comment by rootfs** [comment]
@k8s-bot ok to test

**Comment by timchenxiaoyu** [comment]
@k8s-bot kops aws e2e test this
@k8s-bot unit test this
@k8s-bot gce etcd3 e2e test this

**Comment by timchenxiaoyu** [comment]
cc @saad-ali please give this pr approve and remove do-not-merge

**Comment by jsafrane** [comment]
@k8s-bot node e2e test this

**Pull request merged**
