### PR TITLE
Update docker dependencies.

### PR DESCRIPTION
**Pull request by rjnagal**
The current docker packages are synced between two different versions.

### CODE REVIEW

**Comment by rjnagal** [comment]
@thockin @dchen1107 running e2e...

**Comment by rjnagal** [comment]
local e2e passed, module flaky reboot test.

**Comment by dchen1107** [comment]
Can we promote them to recent release, not reset back to v1.4.1-4045-g2b27fe1?

**Comment by dchen1107** [comment]
Also @thockin has a pending #9362 to moving all to latest version. Two reasons that pr without LGTM:

1) Somehow it failed with shippable for last couple of days. I reran it several times
2) Another one is that no dependency packages are really uploaded. all same?

**Comment by rjnagal** [comment]
This is the latest docker head. Only the release branches get the latest release labels.

The code is from yesterday's docker head.

**Comment by rjnagal** [comment]
@vishh

**Comment by dchen1107** [comment]
Ahh, I missed read that one from your commit version. LGTM.

**Comment by ArtfulCoder** [comment]
http://kubekins.dls.corp.google.com/job/kubernetes-build/3029/

**Pull request merged**
