### PR TITLE
Automated cherry pick of #86252: Use legacyscheme's types rather than testapi ones

### LINKED ISSUE #86644: TestCommonKindsRegistered failing on release-1.17 as flowcontrol is not registered
**What happened**:
`TestCommonKindsRegistered ` is failiing on [release-1.17](https://github.com/kubernetes/kubernetes/tree/7d04da8a4a80f22b1a165edb36a02aa9e01514cf).

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Run command `make test` on release-1.17.

**Anything else we need to know?**:
Master is ok, and this test has been removed by https://github.com/kubernetes/kubernetes/pull/86256.

Should we cherry-pick #86256 to release-1.17?

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux ecs-d8b6 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by RainbowMango**
Cherry pick of #86252 on release-1.17.

#86252: Use legacyscheme's types rather than testapi ones

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

[edit]:
**Which issue(s) this PR fixes**:
Fixes #86644

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
> do-not-merge/release-note-label-needed

you must add a release note. see the PR template in the `.github` folder.

**Comment by RainbowMango** [comment]
> you must add a release note. see the PR template in the `.github` folder.

Done. I think it's ok if no release note. But it can't hurt to have one, right :)

**Comment by liggitt** [comment]
no release note needed

/lgtm
/approve

**Comment by justaugustus** [comment]
Looks like [this job was recently added](https://github.com/kubernetes/test-infra/pull/15705) and hasn't yet run against this PR:
/test pull-kubernetes-e2e-gce-100-performance

**Pull request merged**
