### PR TITLE
Move test/e2e/common to test/e2e_common

### PR DESCRIPTION
**Pull request by mtaufen**
The ongoing testing fixit encourages creating per-sig directories under test/e2e to manage ownership. This makes test/e2e/common, which contains common code between the e2e and e2e_node tests, look like it contains commonly-owned tests. This PR elevates test/e2e/common by one directory level to avoid this confusion.

### CODE REVIEW

**Comment by janetkuo** [comment]
approve no-issue

**Review by janetkuo — APPROVED** [review]

**Comment by ixdy** [comment]
I'm not sure if we want to do this. There's a lot of stuff in `test/e2e/common`, but `e2e_node` only uses a few functions; the rest seems to be mostly related to cluster e2e tests, and so I'd argue it should keep living under `test/e2e`.

**Comment by ixdy** [comment]
cc @kubernetes/sig-testing-pr-reviews

**Comment by spiffxp** [comment]
I think I agree with @ixdy here, I've forgotten context on how/why test/e2e/common is used though

**Comment by rmmh** [comment]
There's also framework, generated, and manifest directories under test/e2e/ that aren't sig-owned.

**Comment by spiffxp** [comment]
@rmmh that's the direction I was headed as well.. would it make sense to use `doc.go` to make the pattern clearer? or is the presence of a framework.SIGDescribe enough of a signal?

**Comment by mtaufen** [comment]
My understanding is that the tests in `common` actually get run by both the e2e test runner and the e2e_node test runner. We can double check with @Random-Liu when he gets back.

**Comment by mtaufen** [comment]
We could also just use a `sig-` prefix on the sig directories, which would have avoided confusion to begin with...

**Comment by grodrigues3** [comment]
Looks like build files need updating

**Comment by mtaufen** [comment]
I *think* the purpose of [this import](https://github.com/kubernetes/kubernetes/blob/d368afd8451229969156c4a37c1fff94643b1d82/test/e2e_node/e2e_node_suite_test.go#L40) is so that the *Describe blocks in test/e2e/common get bundled with the node e2e test binary and run in that suite. Lantao is back later this week so we can ask him them.

**Comment by ixdy** [comment]
oh, right, I forgot that simply importing a ginkgo library imports its tests.

**Comment by mtaufen** [comment]
Ok, rebased, PTAL and let's do this

**Comment by mtaufen** [comment]
I don't have time to keep rebasing this. If someone cares, feel free to reopen.

**Pull request closed without merging**
