### PR TITLE
Automated cherry pick of #11390 upstream release 1.0

### PR DESCRIPTION
**Pull request by jbeda**
Vagrant was failing reliably for me and hit this while reviewing content for an upcoming book with a chapter on kubernetes.

### CODE REVIEW

**Comment by bprashanth** [comment]
@thockin @brendanburns 
Unsure if our prerelease 2 leads rule still applies to cherry picks 
/ref https://github.com/GoogleCloudPlatform/kubernetes/pull/11390

**Comment by alex-mohr** [comment]
@derekwaynecarr for vagrant changes

**Comment by alex-mohr** [comment]
Sorry, these already went in, and vagrant on 1.0 has had a couple of other support issues, so I think merging is fine.

**Comment by jbeda** [comment]
I know that @derekwaynecarr suggested this to me and is supportive of cherrypicking too.

**Comment by derekwaynecarr** [comment]
Thanks for doing the cherry pick.

**Comment by derekwaynecarr** [comment]
Assume per our chat that this resolved the issue for you?

**Comment by jbeda** [comment]
It did! I'll do some more runs to make sure it is some level of reliable.

**Pull request merged**
