### PR TITLE
add support for CentOS via multi-docker

### LINKED ISSUE #14539: docker-multinode does not work on CentOS
- CentOS does not accept `DOCKER_OPTS` for its configuration file 
- typically CentOS does not have built-in `ifconfig` cmd
- `yum` requires `-y` or manual input "yes" to continue installation

i'll send a pr later today to fix this.

/cc @fgrzadkowski @resouer @brendandburns

### PR DESCRIPTION
**Pull request by dalanlan**
Fix #14539 

/cc @fgrzadkowski @resouer @brendandburns

### CODE REVIEW

**Comment by resouer** [comment]
@dalanlan Do not restrict this on centos, should be checked for all OSes we want to support.

Amzn ec2 is exactly the same as CentOS, the only thing you should take care is that ec2 use yum to install packages but use upstart (service) to manage daemons. I have ec2 instances if you want to test it out.

I hope you can delete linuxmint & fedora, which I think is useless when wizard included it in.

So would u mind to fix amzn in this PR?

ref: https://docs.docker.com/installation/

**Comment by dalanlan** [comment]
- add support for centos & amzn
- deprecate fedora & linuxmint for now, feel free to recover them

**Comment by fgrzadkowski** [comment]
This ```case``` statement becomes pretty unreadable and we have few of them already. How about we have one ```case``` and perform all of the operations in one block instead of having multiple ones? I think it'll be more readable even if some of the operations are repeated. WDYT?

**Comment by dalanlan** [comment]
Fair point. Done:)

**Comment by fgrzadkowski** [comment]
@dalanlan Thank for fixing this! LGTM.

**Comment by dalanlan** [comment]
@mikedanese Do you mind if you could review this for me? I'm hungry for an "ok-to-merge" :)

**Comment by dalanlan** [comment]
Jenkins is flanky. This patch doesn't require e2e though.

**Comment by dalanlan** [comment]
@fgrzadkowski Would you mind kicking off another run for Jenkins?

**Comment by mikedanese** [comment]
@k8s-bot ok to test

**Pull request merged**
