### PR TITLE
Restore missing WebUI breadcrumbs after refactor

### PR DESCRIPTION
**Pull request by ohohoreilly**
- Update paths to svg images
- Restore sections concept
- Tested with local cluster via `hack/local-up-cluster.sh`

### CODE REVIEW

**Comment by preillyme** [comment]
@lavalamp can you please review this change:
pr_8332

**Comment by preillyme** [comment]
Once these changes https://github.com/GoogleCloudPlatform/kubernetes/pull/8302 are merged the links will function correctly again. The move from running in a pod to running directly from the API Server seems to have definitely caused some issues.

**Comment by bcbroussard** [comment]
@preillyme - One little thing, can you change the url from `/minions` to `/nodes` to match the text update?

Other than that, looks good to me.

**Comment by bgrant0607** [comment]
cc @jackgr

**Comment by lavalamp** [comment]
Can you add a test to ensure that this doesn't get broken in the future?

Also, the bindata go file seems to have gotten its boilerplate header messed up, which is why travis & shippable are mad at you. Please fix it it (for extra credit, fix the thing that generated it?)

**Comment by jackgr** [comment]
Breadcrumbs and back button still don't work correctly:

1. Broken breadcrumbs:
   * Start the app. 
   * Click Views/Services. View changes to Services. Breadcrumbs show Dashboard > Services. Click Dashboard. View changes to Dashboard. OK so far, but... 
   * Breadcrumbs still show Dashboard > Services. 
2. Broken back button:
   * Start the App
   * Click Views/Nodes. View changes to Nodes. Click a node. See the Back button. OK so far, but...
   * Click the Back button. View changes to Services, instead of going back to Groups.

**Comment by preillyme** [comment]
@lavalamp it looks like currently that ```hack/build-ui.sh``` is just using ```cat hooks/boilerplate.go.txt > $TMP_DATAFILE``` to insert the boilerplate. I've manually fixed the date in the header for now. But a cleaner solution is in the works. @jackgr I'm reviewing your issue and I'm able to replicate it locally. I'll work on a fix shortly. By chance have you confirmed the same behavior in the older versions as well?

**Comment by jackgr** [comment]
@preillyme have not checked older versions.

**Comment by preillyme** [comment]
@jackgr Okay I'll check the older version shortly. I'm curious if it was always broken or just broke now. I suspect it's something with: ```https://docs.angularjs.org/api/ng/service/$location```

**Comment by bcbroussard** [comment]
@googlebot yes, I did author these commits

**Comment by bcbroussard** [comment]
@jackgr  PTAL, I've added another commit to address the issues in your comment, along with a few other minor updates.

- Update pod list back button
- Ignore duplicated README.md
- Rename /minions to /nodes
- Deactivate more buttons
- Updates to list selection and node detail page

**Comment by preillyme** [comment]
@googlebot @bcbroussard  authored these commits https://github.com/preillyme/kubernetes/commit/4ce6783a8ac3ad1a9a4e15a7619f7c8588cf8e18

**Comment by bcbroussard** [comment]
I’m okay with these commits https://github.com/preillyme/kubernetes/commit/4ce6783a8ac3ad1a9a4e15a7619f7c8588cf8e18 being contributed to Google

**Comment by preillyme** [comment]
pr_8332

This now looks good to me. @lavalamp can you take a look please.

**Comment by jackgr** [comment]
:+1:

**Comment by preillyme** [comment]
@lavalamp Can you please review this PR?

**Comment by bgrant0607** [comment]
@jackgr reviewed, so I'm going to put lgtm on this.

**Comment by dchen1107** [comment]
Please rebase so that I can merge your pr, sorry for the inconvienence.

**Comment by lavalamp** [comment]
Needs rebase.

**Comment by lavalamp** [comment]
Also this seems light on tests? Should I not worry about that?

**Comment by preillyme** [comment]
@lavalamp I've rebased.

**Pull request merged**
