### PR TITLE
Part 1: Allowing volumes to choose when to use securityContext 

### PR DESCRIPTION
**Pull request by mkurylec**
This PR is the result of [splitting this PR]( https://github.com/kubernetes/kubernetes/pull/65793) into 2 sections:
1) This part, addressing the refactor so eligible-test-for-conformance can use get rid of privileged security context.
2) a second part that will address the promotion of the testcases to be in conformance suite.

Changes:
a) demoted privileged mode for these tests (not needed)
b) regular tests (the other ones existing in the file) will still be using privileged security context.
b) adding privilegedSecurityContext field to VolInfo, so each volume-flavor can let the test know if the security context has to be privileged or not.
This allows granular changes and updates per volume).

### CODE REVIEW

**Comment by msau42** [comment]
Looks like there's some formatting issue, otherwise lgtm

**Comment by msau42** [comment]
lgtm, can you squash your commits

/release-note-none

**Comment by mkurylec** [comment]
Checks seem to be stuck since yesterday. Trying with retest
/retest

**Pull request merged**
