### PR TITLE
return error if make dir failed when setting up azure file volume

### PR DESCRIPTION
**Pull request by mlmhl**
**What this PR does / why we need it**:

When setting up an azure file, we will:

1. make according pod volume directory first
2. and then mount the volume to this directory.

Currently if the first step failed, the second step will still be executed and it will fail, which makes the error message confused. We should return the error immediately if create pod volume dir failed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```
release-note NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
/lgtm
@kubernetes/sig-storage-bugs

**Comment by nikhita** [comment]
/assign @feiskyer
for approval

**Pull request merged**
