### PR TITLE
[WIP] run kubernetes-discovery in e2e

### PR DESCRIPTION
**Pull request by deads2k**
Trying to run kubernetes-discovery as a pod in `kube-public`

### CODE REVIEW

**Comment by eparis** [comment]
@deads were you coming back to this, or still a ways off?

**Comment by sttts** [comment]
We have to.We are trying to finish the client-go + apiserver refactoring right now with all energy. We can work on these integration topics after freeze.

**Comment by shyamjvs** [comment]
@deads2k Is this PR still up?

**Comment by deads2k** [comment]
> @deads2k Is this PR still up?

No, we're taking a different path and trying to include it in the core api server for 1.7.

**Pull request closed without merging**
