### PR TITLE
Makefile: update test-e2e-node help

### PR DESCRIPTION
**Pull request by bart0sh**
**What type of PR is this?**

/kind documentation
/kind cleanup

**What this PR does / why we need it**:

- Fixed defaults
- Fixed indentation
- Added description of the TEST_SUITE option

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by vpickard — COMMENTED** [review]
/lgtm

**Review by spiffxp — APPROVED** [review]
/lgtm

(I don't have build /approve rights)

**Pull request merged**
