### PR TITLE
Support --all-namespaces in kubectl describe

### LINKED ISSUE #26303: --all-namespaces does not work with kubectl describe
This works:
```
$ kubectl get services --all-namespaces
```

This does not:
```
$ kubectl describe services --all-namespaces
```

cc @kubernetes/kubectl

### PR DESCRIPTION
**Pull request by dims**
Work In Progress :)

Fixes #26303

### CODE REVIEW

**Comment by nhlfr** [comment]
Are you sure that it works? I tried to use your code and it still has a problem with selecting the concrete service outside of the default namespace:

```
$ ./_output/local/bin/linux/amd64/kubectl --namespace=kopytko create -f ~/playground/k8s/downward-old.yaml                                                                                                 
pod "kubernetes-downwardapi-volume-example" created
$ ./_output/local/bin/linux/amd64/kubectl --namespace=kopytko create -f ~/playground/k8s/service.yaml 
service "my-service" created
$ ./_output/local/bin/linux/amd64/kubectl get --all-namespaces services                                                                                                                                  
NAMESPACE   NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
default     kubernetes   10.0.0.1     <none>        443/TCP   48m
kopytko     my-service   10.0.0.68    <none>        80/TCP    4m
$ ./_output/local/bin/linux/amd64/kubectl get --all-namespaces services my-service
error: namespace may not be empty when retrieving a resource by name
```

And the piece of code which shows this error seems to be untouched here.

**Comment by dims** [comment]
@nhlfr : my PR was for describe not get - "kubectl describe --all-namespaces services" (and not "kubectl get --all-namespaces services")

**Comment by nhlfr** [comment]
Um, sorry. Then LGTM

**Comment by rthallisey** [comment]
Hey Dims!. I think it should be 'kubectl describe services --all-namespaces' in your doc patch instead of 'kubectl get services --all-namespaces'.

**Comment by dims** [comment]
@rthallisey oops! thanks. fixed.

**Comment by jlowdermilk** [comment]
@k8s-bot ok to test

**Comment by jlowdermilk** [comment]
Apologies, I missed this pr right when we went into code slush for 1.3. Looks good, will add tag when tests are green.

**Comment by jlowdermilk** [comment]
@k8s-bot node e2e test this issue: #IGNORE

**Comment by jlowdermilk** [comment]
Please run `hack/verify-all.sh` and fix issues.

**Comment by jlowdermilk** [comment]
cc @johndmulhausen do you know why mergebot is blocking on docs?

**Comment by dims** [comment]
@k8s-oncall Any tips on how i can unblock this PR?

**Comment by krousey** [comment]
cc @david-mcmahon @lavalamp Will this have to be manually merged?

**Comment by david-mcmahon** [comment]
Hopefully @johndmulhausen can clarify.  AFAIK *most* docs are on the docs site, but I'm not sure why the bot still warns/blocks on some of the docs in the tree.

**Comment by dims** [comment]
@johndmulhausen @eparis : i've submitted another PR for the bot to whitelist the cheatsheet.md - https://github.com/kubernetes/contrib/pull/1332

**Comment by eparis** [comment]
I do not believe that `kubectl-cheatsheet.md` belongs in the repo at all.  This is not auto-generated and thus is an actual user doc which belongs in kubernetes.github.io.   @erictune

**Comment by dims** [comment]
@k8s-bot please test this: #IGNORE

**Comment by erictune** [comment]
@eparis I agree.  Filed https://github.com/kubernetes/kubernetes.github.io/issues/796

**Comment by dims** [comment]
@erictune @eparis thanks!

**Comment by dims** [comment]
@k8s-bot please test this: #IGNORE

**Comment by dims** [comment]
@k8s-bot please test this: #IGNORE

**Comment by dims** [comment]
@k8s-bot test this please, issue: #IGNORE

**Pull request merged**
