### PR TITLE
create docker image

### PR DESCRIPTION
**Pull request by zouyee**
**What this PR does / why we need it**:
add create_docker_images_for_server
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```NONE
```

### CODE REVIEW

**Comment by jbeda** [comment]
I haven't touched this in forever.  @brendandburns It looks like you were the last to muck with this part of this hairball.  Assigning to you.

**Comment by ixdy** [comment]
do we need this? I know it's a TODO, but I'm not sure what bug or feature this is solving.

**Comment by brendandburns** [comment]
Yeah, I think that TODO might date back to the "single-node cluster based on docker images" days.

I think in a world of `minikube` this is obsolete.  Maybe we can just make this PR delete the `TODO`?

**Comment by ixdy** [comment]
The TODO came from #38919; I think we wanted to build the node components for more platforms, but we didn't need docker images for them at the time.

https://github.com/kubernetes/kubernetes/pull/38919#issuecomment-268376590 notes that the more correct fix is to remove the images from the server tarball and put them in the node tarball, but I'm not sure whether this is worth doing at all.

**Pull request closed without merging**
