### PR TITLE
emeritus fejta

### PR DESCRIPTION
**Pull request by BenTheElder**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

emeritus fejta in owners, Erick is inactive after leaving google for spaceX

xref: https://github.com/kubernetes/test-infra/pull/27689

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
> pull-kubernetes-verify — Pod scheduling timeout

seeing this lately .. k8s infra might be over capacity, too many things on the k8s infra build cluster? cc @ameukam 

/retest

**Comment by ameukam** [comment]
> > pull-kubernetes-verify — Pod scheduling timeout
> 
> seeing this lately .. k8s infra might be over capacity, too many things on the k8s infra build cluster? cc @ameukam
> 
> /retest

Or the resources allocated to this job are no more sufficient to make it run. we got more jobs on k8s-infra but we rarely reached the threshold (240) over the last 6 weeks. bumping memory allocation could be a good start.

**Comment by BenTheElder** [comment]
> Or the resources allocated to this job are no more sufficient to make it run

we haven't increased usage for this job

**Pull request merged**
