### PR TITLE
Update cni-plugins to v1.6.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
Update to the latest release.
#### Which issue(s) this PR fixes:
None

#### Special notes for your reviewer:
cc @kubernetes/release-engineering 

#### Does this PR introduce a user-facing change?

```release-note
Updated cni-plugins to [v1.6.0](https://github.com/containernetworking/plugins/releases/tag/v1.6.0).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by bart0sh** [comment]
@saschagrunert Would it make sense to trigger more pull- jobs to ensure we don't break anything?

**Comment by saschagrunert** [comment]
`pull-kubernetes-e2e-gci-gce-nftables` was never really successful in the past
/skip
/test

**Review by xmudrii — APPROVED** [review]
/lgtm
/approve

**Review by mrunalp — APPROVED** [review]

**Comment by pacoxu** [comment]
/assign @thockin @aojea
for approval

**Comment by saschagrunert** [comment]
Rebased on top of the latest `master` branch.

**Pull request merged**
