### PR TITLE
add ingress output to "kubectl get all"

### PR DESCRIPTION
**Pull request by MasayaAoyama**
Add ingress output to kubectl get all.
I add "all" categories.

```
$ kubectl get all
NAME                                READY     STATUS             RESTARTS   AGE
pod/sample-configmap-multi-volume   1/1       Running            0          9d

NAME                            TYPE           CLUSTER-IP      EXTERNAL-IP             PORT(S)          AGE
service/kubernetes              ClusterIP      10.11.240.1     <none>                  443/TCP          91d

NAME                                HOSTS                ADDRESS          PORTS     AGE
ingress.extensions/sample-ingress   sample.example.com   xx.xxx.xxx.xxx   80, 443   3h
```

**What this PR does / why we need it**:
we use ingress generally, so we need ingress output by "kubectl get all"

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
add ingress output to "kubectl get all"
```

### CODE REVIEW

**Comment by MasayaAoyama** [comment]
@wgliang 
Thank your for your support!
can you give me lgtm?

@deads2k 
Hello, test is passed.
Can you give me a review?

**Comment by yue9944882** [comment]
Dup of #62546

/close

**Pull request closed without merging**
