### PR TITLE
vSphere ip address reordering to workaround strategic patch potential bug

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
**What this PR does / why we need it**:
While working on a bug related to node patch status, I encountered https://github.com/kubernetes/kubernetes/issues/62830 where sorted order of v1.NodeAddressType is needed. As a work around, this patch might help where we are forcing ordering before the node is patched. The code could be modified further.

Without this we would see errors like:

```
[map[address:127.0.0.1 type:ExternalIP] map[address:132.143.154.163 type:ExternalIP] map[address:127.0.0.1 type:InternalIP] map[address:132.143.154.163 type:InternalIP]]
                                                                            
 doesn't match $setElementOrder list:                                                         

[map[type:ExternalIP] map[type:InternalIP] map[type:ExternalIP] map[type:InternalIP] map[type:Hostname]]
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Reorder IPaddress to workaround strategic patch potential bug
```

### CODE REVIEW

**Review by dougm — COMMENTED** [review]
Can we avoid duplicating the logic in that loop?  For example:
```diff
modified   pkg/cloudprovider/providers/vsphere/vsphere.go
@@ -423,12 +423,12 @@ func (vs *VSphere) Instances() (cloudprovider.Instances, bool) {
 }
 
 func getLocalIP() ([]v1.NodeAddress, error) {
-	addrs := []v1.NodeAddress{}
 	ifaces, err := net.Interfaces()
 	if err != nil {
 		glog.Errorf("net.Interfaces() failed for NodeAddresses - %v", err)
 		return nil, err
 	}
+	var ips []string
 	for _, i := range ifaces {
 		localAddrs, err := i.Addrs()
 		if err != nil {
@@ -441,16 +441,7 @@ func getLocalIP() ([]v1.NodeAddress, error) {
 						var addressType v1.NodeAddressType
 						if strings.HasPrefix(i.HardwareAddr.String(), MacOuiVC) ||
 							strings.HasPrefix(i.HardwareAddr.String(), MacOuiEsx) {
-							v1helper.AddToNodeAddresses(&addrs,
-								v1.NodeAddress{
-									Type:    v1.NodeExternalIP,
-									Address: ipnet.IP.String(),
-								},
-								v1.NodeAddress{
-									Type:    v1.NodeInternalIP,
-									Address: ipnet.IP.String(),
-								},
-							)
+							ips = append(ips, ipnet.IP.String())
 						}
 						glog.V(4).Infof("Find local IP address %v and set type to %v", ipnet.IP.String(), addressType)
 					}
@@ -458,6 +449,19 @@ func getLocalIP() ([]v1.NodeAddress, error) {
 			}
 		}
 	}
+	var addrs []v1.NodeAddress
+	for _, ip := range ips {
+		v1helper.AddToNodeAddresses(&addrs, v1.NodeAddress{
+			Type:    v1.NodeExternalIP,
+			Address: ip,
+		})
+	}
+	for _, ip := range ips {
+		v1helper.AddToNodeAddresses(&addrs, v1.NodeAddress{
+			Type:    v1.NodeInternalIP,
+			Address: ip,
+		})
+	}
 	return addrs, nil
 }
```

**Comment by frapposelli** [comment]
@ravisantoshgudimetla can you address the changes requested in the review please?

**Pull request closed without merging**
