### PR TITLE
Rename ConditionFull->ConditionTrue, ConditionNone->ConditionFalse

### PR DESCRIPTION
**Pull request by deyuanix**

### CODE REVIEW

**Comment by ddysher** [comment]
Close #5701

**Comment by davidopp** [comment]
LGTM. I think you'll need to rebase?

**Comment by ddysher** [comment]
Rebased

**Comment by davidopp** [comment]
I re-ran shippable and it passed. (I guess it doesn't automatically update the issue?)

Merging now.

**Comment by davidopp** [comment]
Oops, actually it hadn't finished running yet. Reverting merge.

**Comment by davidopp** [comment]
Never mind, it just finished successfully. Not reverting.

**Pull request merged**
