### PR TITLE
Revert resource.Builder support for group/type

### PR DESCRIPTION
**Pull request by smarterclayton**
We're not comfortable enough in the syntax to introduce it.  Spawned from #15874

@lavalamp @bgrant0607

### CODE REVIEW

**Comment by bgrant0607** [comment]
Thanks.

**Comment by bgrant0607** [comment]
cc @JanetKuo

**Comment by JanetKuo** [comment]
This partially fixes #16039

**Comment by lavalamp** [comment]
LGTM

**Comment by lavalamp** [comment]
Please cherry pick.

**Comment by smarterclayton** [comment]
ok to test

**Comment by smarterclayton** [comment]
ok to test

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
Jenkins test flake:
"Pods should have their auto-restart back-off timer reset on image update"

@k8s-bot test this please

**Comment by smarterclayton** [comment]
ok to test

**Comment by bgrant0607** [comment]
This still needs to be cherrypicked into 1.1.

**Comment by janetkuo** [comment]
#14461 (what #16054 reverts) isn't in 1.1 yet so we don't need to cherry-pick this.

**Pull request merged**
