### PR TITLE
Error message optimization for podautoscaler controller

### PR DESCRIPTION
**Pull request by mysunshine92**
#### What type of PR is this?
/kind cleanup
/sig apps
/sig autoscaling

#### What this PR does / why we need it:
Error message optimization for podautoscaler controller

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by mwielgus — APPROVED** [review]
/lgtm
/approve

**Comment by mysunshine92** [comment]
cc @josephburnett

**Pull request merged**
