### PR TITLE
Removed guestbook.sh e2e test

### PR DESCRIPTION
**Pull request by piosz**
The test is rewritten in Go #5045 and is stable

### CODE REVIEW

**Comment by piosz** [comment]
cc @jlowdermilk

**Comment by satnam6502** [comment]
Was this test being kept around to cover some kubectl testing? @zmerlynn

**Comment by roberthbailey** [comment]
kubectl is now being sufficiently tested by the go tests. 

The shell test is being kept around until we are satisfied that the Go port is at least as good of an e2e test as the shell test was. For other transitions, we've waiting between 2 and 7 days to verify that we aren't losing test coverage during the migration.

**Comment by roberthbailey** [comment]
We've seen a few flakes in the new go test that have hopefully been fixed by #5595. I'm going to wait another day or two to merge this until we see the go test showing higher reliability than the shell test.

**Comment by piosz** [comment]
Should wait until #5604 is fixed.

**Comment by roberthbailey** [comment]
@piosz Can you rebase? I'm going to take a look again today and see if we can finally nuke this shell test.

**Comment by piosz** [comment]
Done.

**Comment by roberthbailey** [comment]
I've taken a detailed look at the test history for `Shell tests that guestbook.sh passes` and `kubectl guestbook should create and stop a working application` on both GCE and GKE. 

For `Shell tests that guestbook.sh passes`, I found that it was failing consistently on GKE until yesterday when #5749 was merged. Since then it is still a bit flaky on GKE (6 of 30 runs), both hitting timeouts and failing with `Wrong entry received: {"data": ""}`. It has been similarly flaky on GCE (also 6 in the last 30 runs but at different times), failing with similar errors.

On the other hand `kubectl guestbook should create and stop a working application` has flaked a few times on both GKE and GCE over the last 30 runs, mainly due to the 60 second timeout which was extended to 3 minutes in #5845. 

Overall, the replacement test seems more stable than the shell test so it's time to remove the shell test. 

There is a slight decrease in test coverage removing the shell test because the shell test was using the public IP associated with the service to read/write from the guestbook whereas the go test is using the kubernetes master as a proxy to reach the service (so the test will pass even if the external LB creation fails). This gap is now covered by `Services should be able to create a functioning external load balancer` which was added in #5772. 

I'll merge on green.

**Comment by roberthbailey** [comment]
Shippable beat travis! Merging.

**Comment by piosz** [comment]
Thanks!

**Pull request merged**
