### PR TITLE
test/e2e/windows/:Use e2eskipper package

### PR DESCRIPTION
**Pull request by tanjunchen**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

test/e2e/windows/:Use e2eskipper package

**Which issue(s) this PR fixes**:

ref:https://github.com/kubernetes/kubernetes/issues/87047

**Special notes for your reviewer**:

/cc @oomichi 
/cc @k-toyoda-pi

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Review by oomichi — COMMENTED** [review]
/lgtm
/approve

**Review by k-toyoda-pi — COMMENTED** [review]
/lgtm

**Pull request merged**
