### PR TITLE
fix e2e tests which set PodPriority are failing

### LINKED ISSUE #66357: [Failing Tests] Kubelet Serial GCE e2e tests which set PodPriority are failing
https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet-serial-gce-e2e

The following tests are broken:
 * NVIDIA GPU Device Plugin
 * PriorityLocalStorageEvictionOrdering
 * PriorityMemoryEvictionOrdering

Looks like some new validation was added to prevent two things:

1. Setting PodPriority directly
2. Using system-critical priority classes outside of the kube-system namespace.

To fix this, we need to create new priority classes for these tests.

cc @bsalamat 

/kind failing-test
/sig node
/sig scheduling
/priority important-soon

### PR DESCRIPTION
**Pull request by wackxu**
fix https://github.com/kubernetes/kubernetes/issues/66357
```release-note
NONE
```

### CODE REVIEW

**Comment by wackxu** [comment]
@dashpole done， PTAL

**Comment by dashpole** [comment]
/priority critical-urgent
I would like to get this in soon so we can get signal back for the features this covers.

**Comment by dashpole** [comment]
/assign @Random-Liu 
for approval

**Pull request merged**
