### PR TITLE
apiextensions-apiserver: generate applyconfigurations

### PR DESCRIPTION
**Pull request by stevekuznetsov**
These were omitted on accident.

/kind cleanup

```release-note
NONE
```
```docs

```

### CODE REVIEW

**Comment by sttts** [comment]
/lgtm
/approve

Verify test fails.

**Comment by stevekuznetsov** [comment]
Is there some hidden dependency for the update script? I can't get the verify to fail locally and the update generates no diff.

```
$ ./hack/update-generated-stable-metrics.sh 
go version go1.20.7 linux/amd64
Updated golden list of stable metrics.
$ echo $?
0
$ git status
On branch skuznets/generate-crd-applyconfigurations
Your branch is ahead of 'kubernetes/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
```

**Comment by pacoxu** [comment]
Here is my local run to update the generated stable metrics.

```
➜  kubernetes git:(skuznets/generate-crd-applyconfigurations) hack/update-generated-stable-metrics.sh 
go version go1.20.7 darwin/amd64
Updated golden list of stable metrics.
➜  kubernetes git:(skuznets/generate-crd-applyconfigurations) ✗ git status
位于分支 skuznets/generate-crd-applyconfigurations
尚未暂存以备提交的变更：
  （使用 "git add <文件>..." 更新要提交的内容）
  （使用 "git restore <文件>..." 丢弃工作区的改动）
        修改：     test/instrumentation/testdata/stable-metrics-list.yaml

修改尚未加入提交（使用 "git add" 和/或 "git commit -a"）
➜  kubernetes git:(skuznets/generate-crd-applyconfigurations) ✗ git diff | cat 
diff --git a/test/instrumentation/testdata/stable-metrics-list.yaml b/test/instrumentation/testdata/stable-metrics-list.yaml
index 6d8c6c642a0..59a79055a01 100644
--- a/test/instrumentation/testdata/stable-metrics-list.yaml
+++ b/test/instrumentation/testdata/stable-metrics-list.yaml
@@ -483,12 +483,6 @@
   - 1e+07
   - 1e+08
   - 1e+09
-- name: apiserver_storage_objects
-  help: Number of stored objects at the time of last check split by kind.
-  type: Gauge
-  stabilityLevel: STABLE
-  labels:
-  - resource
 - name: current_executing_requests
   subsystem: flowcontrol
   namespace: apiserver
@@ -571,6 +565,12 @@
   - 10
   - 15
   - 30
+- name: apiserver_storage_objects
+  help: Number of stored objects at the time of last check split by kind.
+  type: Gauge
+  stabilityLevel: STABLE
+  labels:
+  - resource
 - name: disabled_metrics_total
   help: The count of disabled metrics.
   type: Counter
```

**Comment by pacoxu** [comment]
/hold
until the `pull-kubernetes-verify` is green.

**Comment by logicalhan** [comment]
> Is there some hidden dependency for the update script? I can't get the verify to fail locally and the update generates no diff.

Not sure why you're not seeing update produce a diff locally, but the fact that there is a diff is a bug. Working on a fix.

**Comment by logicalhan** [comment]
> > Is there some hidden dependency for the update script? I can't get the verify to fail locally and the update generates no diff.
> 
> Not sure why you're not seeing update produce a diff locally, but the fact that there is a diff is a bug. Working on a fix.

https://github.com/kubernetes/kubernetes/pull/120197

**Comment by logicalhan** [comment]
> > Is there some hidden dependency for the update script? I can't get the verify to fail locally and the update generates no diff.
> 
> Not sure why you're not seeing update produce a diff locally, but the fact that there is a diff is a bug. Working on a fix.

Actually I'm guessing you have a diff because you haven't rebased in a while and files have been added to the codebase. https://github.com/kubernetes/kubernetes/pull/120197 fixes that.

**Comment by stevekuznetsov** [comment]
Thanks, @logicalhan - I assumed they were already sorted :facepalm: 

Rebased, re-ran the generator (no changes) and re-pushed. Let's see what verify has to say.

**Comment by perdasilva** [comment]
@sttts could you please re-/lgtm ^^?

**Review by logicalhan — APPROVED** [review]
/lgtm
/approve

**Comment by logicalhan** [comment]
> Thanks, @logicalhan - I assumed they were already sorted 🤦

They were sorted, but the problem was that we read 200 files into the go program at a time, then sort the metrics prior to outputting into a file. The bug was that if files are added, it changes the offsets, which changes the sort order.

**Pull request merged**
