### PR TITLE
Updated the term master to control plane

### PR DESCRIPTION
**Pull request by shavidissa**
**What type of PR is this?**
kind documentation

**What this PR does / why we need it**:
Updated the term master to control plane

**Which issue(s) this PR fixes**:

Fixes # n/a

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

NONE

### CODE REVIEW

**Comment by shavidissa** [comment]
cc @neolit123

**Review by rosti — APPROVED** [review]
Thanks for your contribution @shavidissa !

/lgtm
/ok-to-test
/priority backlog
/kind cleanup

**Review by neolit123 — APPROVED** [review]
/approve
thanks @shavidissa

**Pull request merged**
