### PR TITLE
Fixed completion of dash parameters arguments

### PR DESCRIPTION
**Pull request by tomerf**
Fixed a bug when completing a dash argument ending with "=" will duplicate the parameter if there is nothing after the "=" character.
Example:
kubectl --log-dir=\<tab\>
would cause:
kubectl --log-dir=--log-dir=

P.S. This is already merged in the mainstream spf13/cobra repository.

### CODE REVIEW

**Comment by cblecker** [comment]
Hi @tomerf,
We can't edit vendors directly -- we need to update using godep.

Give [this](https://github.com/cblecker/community/blob/10c59effbc147702e712b81fc13fa9bc46837876/contributors/devel/godep.md#using-godep) procedure a shot. Updating spf13/cobra should bring this change in.

**Comment by tomerf** [comment]
Hi @cblecker,
I tried to follow this procedure but can't save the changes. I don't have a directory src/k8s.io/kubernetes after running the restore script.
If I understand correctly the change is actually updating the commit hash in Godeps/Godeps.json and possibly also in the Godeps.json files under staging/src/k8s.io?

**Comment by tomerf** [comment]
Decided to try again and the godep-save.sh finally worked!
I did a _proper_ update for this fix. Can you merge it now?

**Comment by cblecker** [comment]
@tomerf  Can you rebase on master, and then run `make update`?

**Comment by cblecker** [comment]
@tomerf Still failing tests.. can you please run a `make update` and commit the resulting changes?

**Comment by cblecker** [comment]
@tomerf Still failing tests.. can you please run a make update and commit the resulting changes?

**Pull request closed without merging**
