### PR TITLE
Ensure timeout test handlers don't complete before timing out.

### LINKED ISSUE #118523: Failure cluster [5014820e...]: Flake in TestTimeoutRequestHeaders and TestTimeoutWithLogging
### Failure cluster [5014820e8364ad0bace3](https://go.k8s.io/triage#5014820e8364ad0bace3)

Similar to https://github.com/kubernetes/kubernetes/issues/107991 and easily reproducible. The handler occasionally completes and sends a response before timing out.

##### Error text:
```
Failed
=== RUN   TestTimeoutRequestHeaders
    timeout_test.go:299: got res.StatusCde 200; expected 503
--- FAIL: TestTimeoutRequestHeaders (0.01s)

```
#### Recent failures:
[3/25/2023, 12:31:20 AM ci-kubernetes-unit-eks-canary](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-eks-canary/1639484447109681152)
[3/24/2023, 5:17:10 PM pr:pull-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/116899/pull-kubernetes-unit/1639375305921531904)
[3/21/2023, 9:05:34 AM ci-kubernetes-unit-1-24](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-1-24/1638163804372078592)
[3/18/2023, 7:39:50 PM ci-kubernetes-unit-1-23](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-1-23/1637236887804448768)
[3/15/2023, 9:59:17 PM ci-kubernetes-unit-eks-canary](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-eks-canary/1636184694812839936)

/kind failing-test
/kind flake

/sig api-machinery

### PR DESCRIPTION
**Pull request by benluddy**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

TestTimeoutRequestHeaders and TestTimeoutWithLogging are designed to catch data races on request headers and include an HTTP handler that triggers timeout then repeatedly mutates request headers. Sometimes, the request header mutation loop could complete before the timeout filter observed the timeout, resulting in a test failure. The mutation loop now runs until the test ends.

#### Which issue(s) this PR fixes:

I can no longer reproduce the flakes in either test using `golang.org/x/tools/cmd/stress` with this patch. Without the patch, I observed somewhere around a 1/1000 flake rate.

Fix https://github.com/kubernetes/kubernetes/issues/118523.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
```

### CODE REVIEW

**Comment by benluddy** [comment]
For https://github.com/kubernetes/kubernetes/issues/118523.

**Comment by wojtek-t** [comment]
/lgtm
/approve

Thanks!

**Pull request merged**
