### PR TITLE
Increase job cache limit to 300 and leave a TODO.

### PR DESCRIPTION
**Pull request by david-mcmahon**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34749)

### CODE REVIEW

**Comment by saad-ali** [comment]
LGTM

**Review by ixdy — APPROVED** [review]

**Comment by ixdy** [comment]
FYI this change will need to be applied to https://github.com/kubernetes/test-infra/blob/master/jenkins/bootstrap.py#L201 too. @fejta

**Comment by david-mcmahon** [comment]
I was just made aware of this bootstrap.py soon to deprecate `upload-to-gcs.sh`. 
Take note of the TODO I also added, if you're feeling eager, there's a better way to do this that's less racy.

**Comment by david-mcmahon** [comment]
@k8s-bot cvm gke e2e test this

**Pull request merged**
