### PR TITLE
reform function fetchKubeConfigWithTimeout for simplicity

### PR DESCRIPTION
**Pull request by beautytiger**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
After checking the func fetchKubeConfigWithTimeout, I found it is a little bit complicated, so I reformat to a little more straightforward by removing the `WaitGroup`, hope it helpful.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by beautytiger** [comment]
Close, my bad, lesson learned.

**Comment by neolit123** [comment]
> Close, my bad, lesson learned.

hi, i was on vacation. why did you close this PR?

**Comment by beautytiger** [comment]
> > Close, my bad, lesson learned.
> 
> hi, i was on vacation. why did you close this PR?

@neolit123
I found the code is good, no need to change.
Sorry to bother you.

**Comment by neolit123** [comment]
i have a WIP PR to refactor the whole file.

**Pull request closed without merging**
