### PR TITLE
fix hack/test-cmd

### PR DESCRIPTION
**Pull request by deads2k**
https://github.com/kubernetes/kubernetes/pull/25584 broke hack/test-cmd.sh  Looks like a bad rebase.

@jayunit100 ptal

### CODE REVIEW

**Comment by sttts** [comment]
> 0 additions, 1,975 deletions not shown because the diff is too large. Please use a local Git client to view these changes.

Do I miss something?

**Comment by sttts** [comment]
Got it. lgtm

**Comment by lavalamp** [comment]
How did that even get merged with conflicts in the file???

**Comment by lavalamp** [comment]
lgtm

**Comment by timothysc** [comment]
umm wat?

**Comment by lavalamp** [comment]
@timothysc look at the history, this commit vs the one before it.

**Pull request merged**
