### PR TITLE
Batch update for 1.3

### PR DESCRIPTION
**Pull request by eparis**
#28030: Revert "Federation e2e supports aws"
#28026: Address outstanding review comments in #27999.
#28034: Adding lock files for kubeconfig updating
#28004: return nil from NewClientConfig instead of empty struct
#28032: Increase pod CPU/memory for fluentd, dns and kube-proxy.
#27208: Bump minimum API version for docker to 1.21
#28061: Remove extra double quotes in --federations.
#28060: rkt: Fix the 'privileged' check when stage1 annotation is provided.
#27996: Image GC logic should compensate for reserved blocks
#28044: rkt: Bump required rkt version to 1.9.1.
#28040: Tracked addition of federation, sed support in kube DNS
#28043: Set grace period to 0 when deleting namespaces after the test.
#28002: Fix startup type error in initializeCaches
#28087: Hotfix: Fixup the hyperkube dns manifest from a breaking federation PR
#28108: Fix initialization of volume controller caches.
#28056: Increase kube-dns requirements on CoreOS.
#28147: Fix error checks after cloning.
#28159: Use : as seccomp security option operator for Docker 1.10
#28165: Refactored, expanded and fixed federated-services e2e tests.
#28095: Kubelet should mark VolumeInUse before checking if it is Attached
#28172: Build: Add KUBE_GCS_RELEASE_BUCKET_MIRROR option to push-ci-build.sh
#28207: Bump cluster autoscaler to 0.2.2
#28160: Volume manager must verify containers terminated before deleting for ungracefully terminated pods
#28211: Fix federation e2e tests by correctly managing cluster clients
#27944: Fix pvc label selector validation error
#28186: federation: Upgrading the groupversion to v1beta1

### CODE REVIEW

**Comment by eparis** [comment]
@erictune updated as of 12:23 PM Eastern

**Comment by eparis** [comment]
cross your fingers, hopefully you just need to add LGTM...

**Comment by erictune** [comment]
LGTM

**Comment by eparis** [comment]
@k8s-bot e2e test this issue: #IGNORE

**Comment by eparis** [comment]
removing LGTM until @spxtr @ixdy @pwittrock or someone gets `node e2e` running on release-1.3.

Fixing that is a 1.3.0 blocker in my mind...

**Comment by vishh** [comment]
@k8s-bot test node e2e github issue #IGNORE

**Comment by vishh** [comment]
Attempting to re-open this PR to see if the node e2e jenkins project will pick up this PR.

**Comment by ixdy** [comment]
@k8s-bot node e2e test this, issue #IGNORE

**Comment by ixdy** [comment]
ok, it's running finally.

**Comment by erictune** [comment]
@k8s-bot node e2e test this, issue #IGNORE

**Comment by erictune** [comment]
Seems like a github transient failure.

**Comment by erictune** [comment]
@k8s-bot e2e test this, issue #IGNORE

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by eparis** [comment]
@erictune getting close to 'just merge it by hand already' time...

**Comment by ixdy** [comment]
@k8s-bot test this, issue #UGH

**Comment by ixdy** [comment]
go away @k8s-merge-robot, nobody likes you.

The issue appears to be that Jenkins is trying to check out the wrong PR. I don't know why it's doing this. I'm going to try updating the GitHub PR builder plugin to see if that bug has been fixed yet.

**Comment by ixdy** [comment]
@k8s-bot test this, issue #IGNORE

**Comment by ixdy** [comment]
@k8s-bot test this, issue #IGNORE

the new version of the GHPRB plugin is completely and utterly broken, even more so than the version we have installed. I give up.

**Comment by ixdy** [comment]
```
GitHub pull request #28119 of commit 83004a0158f6f535c472f3493a5418862a35448c, no merge conflicts.
...
Checking out Revision 2eeb8fd1621cfbb0e4f4d9ae9b6fd6532e2aa63e (origin/pr/27853/merge)
```

I give up.

**Comment by eparis** [comment]
I know I know let just try again!
@k8s-bot test this issue: #IGNORE

**Comment by eparis** [comment]
@k8s-bot e2e node test this issue: #IGNORE

**Comment by eparis** [comment]
@k8s-bot node e2e test this issue: #IGNORE

**Comment by eparis** [comment]
@k8s-bot e2e node test this issue: #IGNORE

**Comment by eparis** [comment]
@k8s-bot node e2e test this issue: #IGNORE

**Comment by eparis** [comment]
Where is commit 70dcb0c6b39a361ec1d474eb6e4b638ae5305c62 coming from?

Ugggh.  At this point I think @erictune needs to just click the big green button...

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by roberthbailey** [comment]
Can we pick up https://github.com/kubernetes/kubernetes/pull/28032 and https://github.com/kubernetes/kubernetes/pull/28056 in the cherry pick rollup as well?

**Comment by eparis** [comment]
I will wait on @erictune to approve more cherry-picks and will update....

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by ncdc** [comment]
28159 is now cherrypick-approved. Please pull in when you get a chance. Thanks!

**Comment by eparis** [comment]
seems easy enough to pick the v1beta2 PR if you like.

**Comment by eparis** [comment]
@erictune everything passed locally. if it passes here I think you should merge...

**Comment by erictune** [comment]
Okay, will merge when it passes.

**Pull request merged**
