### PR TITLE
pkg/kubelet/network/dns: omit unnecessary `fmt.Sprintf`

### PR DESCRIPTION
**Pull request by Octopusjust**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
omit unnecessary `fmt.Sprintf` when error message is presented

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by robscott** [comment]
Thanks @Octopusjust. Just so you know, this is going to wait for awhile until the 1.26 freeze is lifted.

/priority important-longterm
/approve

**Comment by Octopusjust** [comment]
> Thanks @Octopusjust. Just so you know, this is going to wait for awhile until the 1.26 freeze is lifted.
> 
> /priority important-longterm /approve

OK. Thank you for review :)

**Pull request merged**
