### PR TITLE
Promote Nodeport service creation E2E test to conformance

### PR DESCRIPTION
**Pull request by globervinodhn**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: Ths PR request to promote the E2E test to verify NodePort service creation functionality check to conformance.

**Which issue(s) this PR fixes**: This PR request for a promotion of an existing E2E test to conformance
Fixes #

**Special notes for your reviewer**:
1. The concerned E2E test takes approximately 14 seconds to complete its execution.
2. The test is non-flaky and is not disruptive in nature.

**Does this PR introduce a user-facing change?**: NONE

release-note-none
/area conformance

cc @brahmaroutu @mgdevstack @pontiyaraja

### CODE REVIEW

**Comment by mgdevstack** [comment]
/ok-to-test

As per code comment
>// [TODO:] Run this test against the userspace proxy and nodes
// configured with a default deny firewall to validate that the
// proxy whitelists NodePort traffic
Another e2e can be created which may not be part of Conformance due to firewall specific constraint.

**Comment by PatrickLang** [comment]
There's a separate test case `[sig-windows] Services should be able to create a functioning NodePort service for Windows` running on Windows nodes. We should see if these can be merged into 1, or add `[LinuxOnly]` if this test is covering something Linux-specific.

**Comment by PatrickLang** [comment]
The issue is in service.go:500 - this is using Linux-specific ways to check if the port is locked. Can this use an os-agnostic way instead to verify that the NodePort is reachable and can't be used by another service on the same host? If this os specific behavior isn't changed, then this will need `[LinuxOnly]`

My view here is that for conformance - if the service is reachable on the nodeport, then not reachable once the pod is terminated that should be success.

**Comment by johnbelamaric** [comment]
@PatrickLang I concur, we should use a neutral way to test this. Perhaps just trying to bind to the IP:port in the host namespace would do it.

**Comment by johnbelamaric** [comment]
@globervinodhn Please look into updating the test to verify the port is in use using a vendor-neutral mechanism.

**Comment by johnbelamaric** [comment]
Once #79667 merges we should modify this to use that function.

**Comment by mgdevstack** [comment]
#79667 simplifies this E2E.
https://github.com/kubernetes/kubernetes/blob/3ff4ec6020dd1db4265a293a8cb9cc713f515b04/test/e2e/network/service.go#L512-L528

Once it is merged, Conformance promotion can be continued with updated description.

**Comment by spiffxp** [comment]
moving back to in progres until https://github.com/kubernetes/kubernetes/pull/79667 merges and this is ready for another look

**Comment by johnbelamaric** [comment]
Closing in favor of #80655.

/close

**Pull request closed without merging**
