### PR TITLE
stop using testapi in a flaky way

### PR DESCRIPTION
**Pull request by deads2k**
Stops using global mutable state in the test.

Alternative to https://github.com/kubernetes/kubernetes/pull/60302

/assign @soltysh

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by deads2k** [comment]
/retest

aws not unit

**Comment by deads2k** [comment]
@soltysh this didn't fix it.  I think the original needs to be reverted.

**Comment by deads2k** [comment]
/hold

I fixed a testapi race and an output race, but something else in the test is still flaking.  We just need to revert the original.  Closing this.

**Pull request closed without merging**
