### PR TITLE
Automated cherry pick of #58219: Use the bazel version check function from bazel-skylib

### PR DESCRIPTION
**Pull request by ixdy**
Cherry pick of #58219 on release-1.9.

#58219: Use the bazel version check function from bazel-skylib

### CODE REVIEW

**Comment by ixdy** [comment]
It'd probably be good to be able to use bazel 0.10 on this branch, too.

/assign @BenTheElder @mikedanese
/release-note-none

**Comment by mbohlool** [comment]
build only cherrypick is approved. still need lgtm I guess.

**Comment by ixdy** [comment]
/retest

@BenTheElder can I get an lgtm?

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Pull request merged**
