### PR TITLE
Kube-proxy to use apiserver instead of etcd in CoreOS getting-started-guide.

### PR DESCRIPTION
**Pull request by erictune**

### CODE REVIEW

**Comment by erictune** [comment]
@pires can you tell me if this looks right?

**Comment by erictune** [comment]
I confirmed that the kube-proxy is reading the services from apiserver.  I can't reach the services, but I presume that is due to some other problem in the CoreOS + GCE setup.

**Comment by pires** [comment]
Yes, it seems alright. Is `--master` flag available in 0.11.0? Otherwise, we'll need to update everything to a newer version.

**Comment by erictune** [comment]
yes, it exists in 0.11.0

**Comment by alex-mohr** [comment]
@pires for LGTM?  or someone else?

**Comment by pires** [comment]
LGTM.

**Pull request merged**
