### PR TITLE
GCE/Windows: exclude gateways from the IPAM subnet

### LINKED ISSUE #74766: Creating windows pods flaky due to HNS error "failed to create the new HNSEndpoint: hnsCall failed in Win32: The object already exists. (0x1392)"
**What happened**:
Environment: On GCE with the win-bridge cni plugin

On a node when creating a pod for the first time, running podsandbox would fail with the error message below. "failed to create the new HNSEndpoint: hnsCall failed in Win32: The object already exists. (0x1392)"

```
Events:
  Type     Reason                  Age                From                                              Message
  ----     ------                  ----               ----                                              -------
  Warning  FailedCreatePodSandBox  15s                kubelet, e2e-test-yjhong-windows-node-group-rdt6  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "5a4a06b6983a52f678e15203f1e77e0e310933e5a506dc3167bf7f3e57782106" network for pod "shetland": NetworkPlugin cni failed to set up pod "shetland_default" network: error while ProvisionEndpoint(5a4a06b6983a52f678e15203f1e77e0e310933e5a506dc3167bf7f3e57782106_l2bridge,359CAE70-8CA4-4143-A42B-42644CF04022,5a4a06b6983a52f678e15203f1e77e0e310933e5a506dc3167bf7f3e57782106): failed to create the new HNSEndpoint: hnsCall failed in Win32: The object already exists. (0x1392), failed to clean up sandbox container "5a4a06b6983a52f678e15203f1e77e0e310933e5a506dc3167bf7f3e57782106" network for pod "shetland": NetworkPlugin cni failed to teardown pod "shetland_default" network: failed to find HNSEndpoint 5a4a06b6983a52f678e15203f1e77e0e310933e5a506dc3167bf7f3e57782106_l2bridge: Endpoint 5a4a06b6983a52f678e15203f1e77e0e310933e5a506dc3167bf7f3e57782106_l2bridge not found]
  Normal   SandboxChanged          12s (x2 over 14s)  kubelet, e2e-test-yjhong-windows-node-group-rdt6  Pod sandbox changed, it will be killed and re-created.

```
Subsequent retry would succeed, and launching other pods afterwards would also, generally, be fine. 

I've found https://github.com/Microsoft/SDN/issues/298, but in that issue, the creation failed permanently.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master (1.14, da5fd93e93f4)
- Cloud provider or hardware configuration: GCE
- OS (e.g: `cat /etc/os-release`): Windows 1809
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/cc @pjh @kubernetes/sig-windows-bugs

### PR DESCRIPTION
**Pull request by yujuhong**
Exclude IPs assigned for gateways in the IPAM configuration.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #74766

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yujuhong** [comment]
I manually verified the fix with a test cluster.

**Review by michmike — APPROVED** [review]

**Pull request merged**
