### PR TITLE
kubeadm reset cleanupnode log format optimization

### PR DESCRIPTION
**Pull request by lojies**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
kubeadm reset cleanupnode log format optimization
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
hi, could you explain why this change is needed?
what is the difference in the output?

**Comment by lojies** [comment]
> hi, could you explain why this change is needed?
> what is the difference in the output?

In fact there is no  difference in the output.
But i think this may cause misunderstanding that warningf will not start a new line.
Is it better to delete the '\n'?

**Comment by neolit123** [comment]
we are in code freeze for 1.21, so such a change has to wait for 1.22.

> In fact there is no difference in the output.

klog automatically adds `\n`. there should be a difference when another `\n` is present.
there should be a difference...so that's why i asked for the before and after.

what benefits do we gain from this change?

**Comment by lojies** [comment]
> klog automatically adds `\n`. there should be a difference when another `\n` is present.
> so the whole ouput should be slight different...so that's why i asked for the before and after.
> 
> ...and also what benefits do we gain from this change?
```golang
	if buf.Bytes()[buf.Len()-1] != '\n' {
		buf.WriteByte('\n')
	}
```
klog add '\n' when it isn't existed, so there is no difference.
Maybe package klog's design is different from package fmt.
Then i'm not sure why there have warning and warningln, it seems like they are the same.

Since the output is the same, i think there is no need to change.
@neolit123, thanks for the reply.

**Comment by neolit123** [comment]
> Then i'm not sure why there have warning and warningln, it seems like they are the same.

i think the reason was for compatibility reasons with old code.

**Pull request closed without merging**
