### PR TITLE
increase the timeout in GC orphan test

### LINKED ISSUE #42086: [e2e Flake] Garbage collector should orphan pods created by rc if delete options say so
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/41852/pull-kubernetes-e2e-kops-aws/14321/

Reported by @mml. @krmayankk told me he had seen this as well. IIRC @luxas told me about the issue on Slack a while ago. I'll look into it. 

I don't know why the robot hasn't filed an issue for this flake. @foxish @apelisse do you know who is working on the robot that reports flaky tests?

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fixes #42086

See the [justification](https://github.com/kubernetes/kubernetes/issues/42086#issuecomment-317521413).

### CODE REVIEW

**Comment by deads2k** [comment]
@caesarxuchao do we need to reconsider the qps and/or the single threaded nature of the patch?

**Comment by caesarxuchao** [comment]
Do we have benchmark on what QPS can the apiserver support? If the bottleneck is not the apiserver, then it makes sense to parallel the patch and increase the client qps.

**Comment by deads2k** [comment]
> Do we have benchmark on what QPS can the apiserver support? If the bottleneck is not the apiserver, then it makes sense to parallel the patch and increase the client qps.

We've tested order of 1000 without much trouble.  I'd try parallelization before qps to remove the latency induced first.

**Review by cheftako — APPROVED** [review]
/lgtm

**Comment by caesarxuchao** [comment]
Ok. I'll send a PR to parallel the patch.

**Pull request merged**
