### PR TITLE
Add timestamps to the liveness e2e test 

### PR DESCRIPTION
**Pull request by roberthbailey**
... by changing By -> Logf in places where the statement is for debugging rather than describing what the test is doing.

To help debug flake #20418.

### CODE REVIEW

**Comment by roberthbailey** [comment]
@gmarek -- Can you review (& merge) during your workday to help track down #20418? Thanks.

**Comment by gmarek** [comment]
Reassigning to @piosz, who's build cop today.

**Comment by fgrzadkowski** [comment]
Merging this manually as the queue is rather long it will help us debug e2e tests.

**Comment by roberthbailey** [comment]
Thanks @fgrzadkowski!

**Comment by eparis** [comment]
added label priority/P1 to move to the top of the merge queue (did you know it paid attention to that?) (e2e-not-required is even higher than p0!)

**Pull request merged**
