### PR TITLE
Added what seems to be the default allowable port range for NodePort to the docs

### LINKED ISSUE #9696: Document NodePort Address Rage
Just like it sounds.

### PR DESCRIPTION
**Pull request by pnovotnak**
Fixes #9696

### CODE REVIEW

**Comment by pnovotnak** [comment]
I signed it!

**Comment by justinsb** [comment]
Thanks!  The range is actually supposed to be 30000 - 32767, although I had an off-by-one error originally (as you spotted).  I fixed my mistake, so the default should now be 30000-32767.

**Comment by pnovotnak** [comment]
I was wondering about that :) 

Updated.

**Comment by justinsb** [comment]
LGTM

**Comment by mikedanese** [comment]
@pnovotnak can you squash your commits into one?

**Comment by pnovotnak** [comment]
Squashed.

**Comment by mikedanese** [comment]
@pnovotnak this is LGTM but I was unable to look up the CLA on our internal system. I looked up your username, the email on the commit, and the email on your github profile. Are you sure you signed it? Was it a corporate cla?

**Comment by mikedanese** [comment]
@googlebot check again!

**Comment by pnovotnak** [comment]
I just submitted another CLA for my personal email address and made sure my github username was attached.

The one submitted via my work address' email is: peter@cyrusbio [dot] com

**Comment by mikedanese** [comment]
@googlebot is pleased.

**Pull request merged**
