### PR TITLE
Fix typo for `kubeadm`

### PR DESCRIPTION
**Pull request by sebastiaanspeck**
Saw the typo when reading the CHANGELOG for 1.32.

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

Because it contains a typo in the CHANGELOG's right now, which could confuse users.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm

**Comment by satyampsoni** [comment]
lgtm

**Comment by neolit123** [comment]
/assign @dims 

PTAL for approval if possible.
users are creating more tickets about it
- https://github.com/kubernetes/kubernetes/issues/128460

**Review by obriensystems — APPROVED** [review]
lgtm

**Comment by dims** [comment]
@neolit123 unfortunately i don't have karma in this directory! :( 

cc @kubernetes/sig-release-leads

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
