### PR TITLE
Revert "Fix legacy fallback stale for aggregated discovery"

### PR DESCRIPTION
**Pull request by pacoxu**
Reverts kubernetes/kubernetes#115770

https://storage.googleapis.com/k8s-triage/index.html?text=TestLegacyFallbackNoCache#1bf2be60ce0078971afe

The test case was added recently and I am not sure how to fix it yet.

```
Failed
=== RUN   TestLegacyFallbackNoCache
I0222 09:04:49.496617  108495 handler_discovery.go:392] Starting ResourceDiscoveryManager
I0222 09:04:49.498038  108495 handler.go:149] Adding GroupVersion stable.example.com v1 to ResourceManager
I0222 09:04:49.502258  108495 handler.go:149] Adding GroupVersion stable.example.com v1alpha1 to ResourceManager
I0222 09:04:49.503313  108495 handler.go:149] Adding GroupVersion stable.example.com v1beta1 to ResourceManager
    handler_discovery_test.go:379: 
        	Error Trace:	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_discovery_test.go:379
        	Error:      	Not equal: 
        	            	expected: []v2beta1.APIGroupDiscovery{v2beta1.APIGroupDiscovery{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"stable.example.com", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Versions:[]v2beta1.APIVersionDiscovery{v2beta1.APIVersionDiscovery{Version:"v1beta1", Resources:[]v2beta1.APIResourceDiscovery{v2beta1.APIResourceDiscovery{Resource:"foos", ResponseKind:(*v1.GroupVersionKind)(0xc000bce7e0), Scope:"Cluster", SingularResource:"foo", Verbs:[]string{"get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"}, ShortNames:[]string(nil), Categories:[]string{"all"}, Subresources:[]v2beta1.APISubresourceDiscovery(nil)}}, Freshness:"Current"}, v2beta1.APIVersionDiscovery{Version:"v1alpha1", Resources:[]v2beta1.APIResourceDiscovery{v2beta1.APIResourceDiscovery{Resource:"foos", ResponseKind:(*v1.GroupVersionKind)(0xc000bce810), Scope:"Cluster", SingularResource:"foo", Verbs:[]string{"get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"}, ShortNames:[]string(nil), Categories:[]string{"all"}, Subresources:[]v2beta1.APISubresourceDiscovery(nil)}}, Freshness:"Current"}, v2beta1.APIVersionDiscovery{Version:"v1", Resources:[]v2beta1.APIResourceDiscovery{v2beta1.APIResourceDiscovery{Resource:"foos", ResponseKind:(*v1.GroupVersionKind)(0xc000bce840), Scope:"Cluster", SingularResource:"foo", Verbs:[]string{"get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"}, ShortNames:[]string(nil), Categories:[]string{"all"}, Subresources:[]v2beta1.APISubresourceDiscovery(nil)}}, Freshness:"Current"}}}}
        	            	actual  : []v2beta1.APIGroupDiscovery{v2beta1.APIGroupDiscovery{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"stable.example.com", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Versions:[]v2beta1.APIVersionDiscovery{v2beta1.APIVersionDiscovery{Version:"v1", Resources:[]v2beta1.APIResourceDiscovery{v2beta1.APIResourceDiscovery{Resource:"foos", ResponseKind:(*v1.GroupVersionKind)(0xc000bce720), Scope:"Cluster", SingularResource:"foo", Verbs:[]string{"get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"}, ShortNames:[]string(nil), Categories:[]string{"all"}, Subresources:[]v2beta1.APISubresourceDiscovery(nil)}}, Freshness:"Current"}, v2beta1.APIVersionDiscovery{Version:"v1beta1", Resources:[]v2beta1.APIResourceDiscovery{v2beta1.APIResourceDiscovery{Resource:"foos", ResponseKind:(*v1.GroupVersionKind)(0xc000bce750), Scope:"Cluster", SingularResource:"foo", Verbs:[]string{"get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"}, ShortNames:[]string(nil), Categories:[]string{"all"}, Subresources:[]v2beta1.APISubresourceDiscovery(nil)}}, Freshness:"Current"}, v2beta1.APIVersionDiscovery{Version:"v1alpha1", Resources:[]v2beta1.APIResourceDiscovery{v2beta1.APIResourceDiscovery{Resource:"foos", ResponseKind:(*v1.GroupVersionKind)(0xc000bce780), Scope:"Cluster", SingularResource:"foo", Verbs:[]string{"get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"}, ShortNames:[]string(nil), Categories:[]string{"all"}, Subresources:[]v2beta1.APISubresourceDiscovery(nil)}}, Freshness:"Current"}}}}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -30,2 +30,33 @@
        	            	   Versions: ([]v2beta1.APIVersionDiscovery) (len=3) {
        	            	+   (v2beta1.APIVersionDiscovery) {
        	            	+    Version: (string) (len=2) "v1",
        	            	+    Resources: ([]v2beta1.APIResourceDiscovery) (len=1) {
        	            	+     (v2beta1.APIResourceDiscovery) {
        	            	+      Resource: (string) (len=4) "foos",
        	            	+      ResponseKind: (*v1.GroupVersionKind)({
        	            	+       Group: (string) (len=18) "stable.example.com",
        	            	+       Version: (string) (len=2) "v1",
        	            	+       Kind: (string) (len=3) "Foo"
        	            	+      }),
        	            	+      Scope: (v2beta1.ResourceScope) (len=7) "Cluster",
        	            	+      SingularResource: (string) (len=3) "foo",
        	            	+      Verbs: ([]string) (len=8) {
        	            	+       (string) (len=3) "get",
        	            	+       (string) (len=4) "list",
        	            	+       (string) (len=5) "watch",
        	            	+       (string) (len=6) "create",
        	            	+       (string) (len=6) "update",
        	            	+       (string) (len=5) "patch",
        	            	+       (string) (len=6) "delete",
        	            	+       (string) (len=16) "deletecollection"
        	            	+      },
        	            	+      ShortNames: ([]string) <nil>,
        	            	+      Categories: ([]string) (len=1) {
        	            	+       (string) (len=3) "all"
        	            	+      },
        	            	+      Subresources: ([]v2beta1.APISubresourceDiscovery) <nil>
        	            	+     }
        	            	+    },
        	            	+    Freshness: (v2beta1.DiscoveryFreshness) (len=7) "Current"
        	            	+   },
        	            	    (v2beta1.APIVersionDiscovery) {
        	            	@@ -91,33 +122,2 @@
        	            	     Freshness: (v2beta1.DiscoveryFreshness) (len=7) "Current"
        	            	-   },
        	            	-   (v2beta1.APIVersionDiscovery) {
        	            	-    Version: (string) (len=2) "v1",
        	            	-    Resources: ([]v2beta1.APIResourceDiscovery) (len=1) {
        	            	-     (v2beta1.APIResourceDiscovery) {
        	            	-      Resource: (string) (len=4) "foos",
        	            	-      ResponseKind: (*v1.GroupVersionKind)({
        	            	-       Group: (string) (len=18) "stable.example.com",
        	            	-       Version: (string) (len=2) "v1",
        	            	-       Kind: (string) (len=3) "Foo"
        	            	-      }),
        	            	-      Scope: (v2beta1.ResourceScope) (len=7) "Cluster",
        	            	-      SingularResource: (string) (len=3) "foo",
        	            	-      Verbs: ([]string) (len=8) {
        	            	-       (string) (len=3) "get",
        	            	-       (string) (len=4) "list",
        	            	-       (string) (len=5) "watch",
        	            	-       (string) (len=6) "create",
        	            	-       (string) (len=6) "update",
        	            	-       (string) (len=5) "patch",
        	            	-       (string) (len=6) "delete",
        	            	-       (string) (len=16) "deletecollection"
        	            	-      },
        	            	-      ShortNames: ([]string) <nil>,
        	            	-      Categories: ([]string) (len=1) {
        	            	-       (string) (len=3) "all"
        	            	-      },
        	            	-      Subresources: ([]v2beta1.APISubresourceDiscovery) <nil>
        	            	-     }
        	            	-    },
        	            	-    Freshness: (v2beta1.DiscoveryFreshness) (len=7) "Current"
        	            	    }
        	Test:       	TestLegacyFallbackNoCache
--- FAIL: TestLegacyFallbackNoCache (0.11s)
```
/kind flake

### CODE REVIEW

**Comment by Jefftree** [comment]
Thanks for raising this. I've opened https://github.com/kubernetes/kubernetes/pull/115991 to fix it.

**Comment by pacoxu** [comment]
> Thanks for raising this. I've opened #115991 to fix it.

Thanks for the quick fix.

**Pull request closed without merging**
