### PR TITLE
Avoid too many  log about  pod

### PR DESCRIPTION
**Pull request by changyaowei**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind cleanup

**What this PR does / why we need it**:
When kubelet execute probe, it will log pod info, when pod was defined with a big size , the log file extend very fast 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
Can you post example log messages before and after this change to give a bit of a better sense of the information that we're loosing?

Thanks for thinking about this :)

**Comment by changyaowei** [comment]
> Can you post example log messages before and after this change to give a bit of a better sense of the information that we're loosing?
> 
> Thanks for thinking about this :)

I wrote a test case to show this change
``` go
func TestRunProbe(t *testing.T) {
	probe := &v1.Probe{
		Handler: v1.Handler{
			Exec: &v1.ExecAction{
				Command: []string{},
			},
		},
		TimeoutSeconds:   1,
		PeriodSeconds:    1,
		SuccessThreshold: 1,
		FailureThreshold: 3,
	}
	probePod := v1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			UID: "probe_pod",
		},
		Spec: v1.PodSpec{
			Containers: []v1.Container{{
				Name:           "container1",
				ReadinessProbe: probe,
				LivenessProbe:  probe,
			}},
		},
	}
	fmt.Printf("Exec-Probe Pod: %v, Container: %v, Command: %v \n", probePod, probePod.Spec.Containers[0], probePod.Spec.Containers[0].LivenessProbe.Exec.Command)
	fmt.Printf("Exec-Probe Pod: %q, Container: %q, Command: %v \n", format.Pod(&probePod), probePod.Spec.Containers[0].Name, probePod.Spec.Containers[0].LivenessProbe.Exec.Command)
}
```
The output is 
```
Before this pr is :
Exec-Probe Pod: {{ } {    probe_pod  0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] nil []  []} {[] [] [{container1  [] []  [] [] [] {map[] map[]} [] [] &Probe{Handler:Handler{Exec:&ExecAction{Command:[],},HTTPGet:nil,TCPSocket:nil,},InitialDelaySeconds:0,TimeoutSeconds:1,PeriodSeconds:1,SuccessThreshold:1,FailureThreshold:3,} &Probe{Handler:Handler{Exec:&ExecAction{Command:[],},HTTPGet:nil,TCPSocket:nil,},InitialDelaySeconds:0,TimeoutSeconds:1,PeriodSeconds:1,SuccessThreshold:1,FailureThreshold:3,} nil    nil false false false}]  <nil> <nil>  map[]   <nil>  false false false <nil> nil []   nil  [] []  <nil> nil [] <nil> <nil>} { []      <nil> [] [] }}, Container: {container1  [] []  [] [] [] {map[] map[]} [] [] &Probe{Handler:Handler{Exec:&ExecAction{Command:[],},HTTPGet:nil,TCPSocket:nil,},InitialDelaySeconds:0,TimeoutSeconds:1,PeriodSeconds:1,SuccessThreshold:1,FailureThreshold:3,} &Probe{Handler:Handler{Exec:&ExecAction{Command:[],},HTTPGet:nil,TCPSocket:nil,},InitialDelaySeconds:0,TimeoutSeconds:1,PeriodSeconds:1,SuccessThreshold:1,FailureThreshold:3,} nil    nil false false false}, Command: [] 
With this pr is :
Exec-Probe Pod: "_(probe_pod)", Container: "container1", Command: [] 
```
It ignore some not important pod information.

**Review by mattjmcnaughton — COMMENTED** [review]
Personally, this is fine with me. Curious to know if others feel that we are loosing anything by removing some of this info.

Not sure what is going on with the test suite... confirming you've verified this is compiling locally and the tests are passing?
/retest

**Comment by changyaowei** [comment]
@yifan-gu @Random-Liu PTAL

**Comment by resouer** [comment]
The change looks good, could you please fix the tests suite?

**Comment by changyaowei** [comment]
You can run  this  to contrast the output change which caused by this pr

``` go
package testing

import (
	"fmt"
	"testing"

	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/kubernetes/pkg/kubelet/util/format"
)

func TestRunProbe(t *testing.T) {
	probe := &v1.Probe{
		Handler: v1.Handler{
			Exec: &v1.ExecAction{
				Command: []string{},
			},
		},
		TimeoutSeconds:   1,
		PeriodSeconds:    1,
		SuccessThreshold: 1,
		FailureThreshold: 3,
	}
	probePod := v1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			UID: "probe_pod",
		},
		Spec: v1.PodSpec{
			Containers: []v1.Container{{
				Name:           "container1",
				ReadinessProbe: probe,
				LivenessProbe:  probe,
			}},
		},
	}
	fmt.Printf("Exec-Probe Pod: %v, Container: %v, Command: %v \n", probePod, probePod.Spec.Containers[0], probePod.Spec.Containers[0].LivenessProbe.Exec.Command)
	fmt.Printf("Exec-Probe Pod: %q, Container: %q, Command: %v \n", format.Pod(&probePod), probePod.Spec.Containers[0].Name, probePod.Spec.Containers[0].LivenessProbe.Exec.Command)
}

```

**Pull request closed without merging**
