### PR TITLE
dependencies: ginkgo v2.9.1, gomega v1.27.3

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

They contain some nice-to-have improvements (for example, better printing of errors with gomega/format.Object) but nothing that is critical right now.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/cc @soltysh

### CODE REVIEW

**Comment by pohly** [comment]
/hold

The double-printing of the `Error()` string isn't ideal. Might get fixed in gomega soon.

**Comment by pohly** [comment]
/hold cancel

This now uses a gomega version released today with a fix for the double-printing.

/assign @soltysh

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by dims** [comment]
@liggitt just a go.mod/sum change here under api review

**Comment by liggitt** [comment]
hrmm...

```
#13 3.082 go: updates to go.mod needed; to update it:
#13 3.082 	go mod tidy
#13 ERROR: process "/bin/sh -c CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH} GO111MODULE=on go build -a -o mock-kms-plugin plugin.go" did not complete successfully: exit code: 1
```

**Comment by liggitt** [comment]
@enj - does the kind-kms failure ring a bell?

**Comment by liggitt** [comment]
/approve
for API go.mod file

**Comment by pohly** [comment]
Let's lift the hold, the earlier rebase conflict is resolved.

/hold cancel

**Comment by enj** [comment]
Please run `go mod tidy` in `staging/src/k8s.io/kms/internal/plugins/mock` so that the KMS tests stops failing.

/hold

**Comment by liggitt** [comment]
> Please run go mod tidy in staging/src/k8s.io/kms/internal/plugins/mock so that the KMS tests stops failing.

@enj, can you add that to hack/update-internal-modules.sh?

**Comment by enj** [comment]
> > Please run go mod tidy in staging/src/k8s.io/kms/internal/plugins/mock so that the KMS tests stops failing.
> 
> @enj, can you add that to hack/update-internal-modules.sh?

#116613

**Comment by pohly** [comment]
> Please run `go mod tidy` in `staging/src/k8s.io/kms/internal/plugins/mock` so that the KMS tests stops failing.

Done: https://github.com/kubernetes/kubernetes/compare/d3a568c0b12158971cc2faf9a80ba49107988fc5..fe59e091eb3331db54cff2351f16eabfe0cb681d

**Comment by pohly** [comment]
/retest

pull-kubernetes-integration: k8s.io/kubernetes/test/integration/controlplane/transformation: TestKMSv2Healthz

**Comment by liggitt** [comment]
> pull-kubernetes-integration: k8s.io/kubernetes/test/integration/controlplane/transformation: TestKMSv2Healthz

cc @enj @aramase for visibility - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/116539/pull-kubernetes-integration/1635769728846794752

**Comment by enj** [comment]
> > pull-kubernetes-integration: k8s.io/kubernetes/test/integration/controlplane/transformation: TestKMSv2Healthz
> 
> cc @enj @aramase for visibility - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/116539/pull-kubernetes-integration/1635769728846794752

#116626 should fix the rare flake.

**Pull request merged**
