### PR TITLE
Automated cherry pick of #44781

### PR DESCRIPTION
**Pull request by wongma7**
Cherry pick of #44781 on release-1.5.

#44781: Ensure desired state of world populator runs before volume

### CODE REVIEW

**Comment by wongma7** [comment]
@jingxu97 this is for 1.5, 1.6 is here https://github.com/kubernetes/kubernetes/pull/45680 , as requested. https://github.com/kubernetes/kubernetes/pull/44781 needs milestone set to 1.5 + cherrypick-candidate (+ cherrypick-approved). And also a release note, let me reread the issue and write something sensible.

**Comment by feiskyer** [comment]
@k8s-bot ok to test

**Comment by wongma7** [comment]
@jingxu97 can you /lgtm this please? everything else is green. THanks!

**Comment by feiskyer** [comment]
@jingxu97 @wongma7 Do we still need this?

**Comment by wongma7** [comment]
@feiskyer wouldn't hurt, it prevents misleading log messages about volumes not being mounted when they actually are. @jingxu97 asked me to create cherrypick to 1.5, we already have the fix in 1.6+ I believe.

**Comment by jingxu97** [comment]
Sorry I missed this PR due to vacation. Reopen it @wongma7

**Comment by wongma7** [comment]
/retest
@jingxu97 thanks! please /lgtm and remove the 'do-not-merge', the bot is being dumb

**Comment by jingxu97** [comment]
@saad-ali could you please approve this cherrypick?

**Pull request merged**
