### PR TITLE
Default NODE_OS to gci on GCE installs

### PR DESCRIPTION
**Pull request by thockin**
Looking at https://github.com/kubernetes/test-infra/tree/master/jobs,
any job with "cvm" in the name explicitly sets this variable, so I hope
it is only the default.

**Release note**:
```release-note
Change GCE installs (kube-up.sh) to use GCI/COS for node OS, by default.
```
@mtaufen @dchen1107 @ixdy

### CODE REVIEW

**Comment by thockin** [comment]
@k8s-bot pull-kubernetes-node-e2e test this

**Comment by mtaufen** [comment]
The e2es rely on the setting in `config-test.sh`, IIRC.

**Comment by mtaufen** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by thockin** [comment]
all green

**Comment by mtaufen** [comment]
/lgtm

I'm assuming we aren't changing `cluster/gce/config-test.sh` because tests for debian will just assume they have the default test config, and tests for gci will manually set gci. If that's wrong please update `config-test.sh` as well.

**Comment by ixdy** [comment]
did we intend for this to get into 1.7?

**Pull request merged**
