### PR TITLE
Use RWMutex in watchBasedManager

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Use RWMutex in watchBasedManager to replace Mutex to accelerate map operation.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/cc @draveness 
I made mistake in this PR https://github.com/kubernetes/kubernetes/pull/81283, I mismatched my local branches, PTAL thanks

### CODE REVIEW

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

If you want, I think you could make a similar change in `pkg/kubelet/util/manager/cache_based_manager.go`. We could also do that in a separate pr :)

**Comment by cwdsuzhou** [comment]
> /lgtm
> 
> If you want, I think you could make a similar change in `pkg/kubelet/util/manager/cache_based_manager.go`. We could also do that in a separate pr :)

Thanks, cacheBasedManager could not simply use RWMutex to replace it and it’s more complex. I am working on it :)

**Comment by cwdsuzhou** [comment]
/assign @derekwaynecarr @tallclair 

PTAL thanks

**Pull request merged**
