### PR TITLE
Structured Logging migration: modify logs of kube-proxy in part of pkg

### PR DESCRIPTION
**Pull request by lojies**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Structured Logging migration: modify logs of kube-scheduler.
xref:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
part of kubernetes/enhancements#1602
As it is related to log, change the log here to structured log.
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lojies** [comment]
@freehan @rramkumar1

**Comment by nikhita** [comment]
Removing and re-adding the sig label, so that prow auto-removes the `do-not-merge/needs-sig` label

/remove-sig network

**Pull request closed without merging**
