### PR TITLE
[WIP] Possible vendoring fixes

### PR DESCRIPTION
**Pull request by freeformz**
This is some vendoring changes with https://github.com/tools/godep/pull/415 applied. I'm not sure how to build k8s yet, but I'm fairly sure (hand verified some of the changes) that these are legit. Going to follow up based on the status of the automated tests though.

### CODE REVIEW

**Comment by lavalamp** [comment]
I'm not 100% clear on why this adds so many dependencies. And I don't understand why they're only "possible" fixes? I think just nothing would work in our test/build environments if we didn't vendor enough stuff.

Also, we wouldn't be able to merge this until tools/godep#415 is merged-- our CI requires our godep directory to be reproducible.

**Comment by lavalamp** [comment]
We are making some changes to pin the version of godeps that we use. #21786 is then working on rolling forward our godeps to v54. You may want to look at that and combine effort instead of duplicating effort :)

**Comment by freeformz** [comment]
You should pin to v55. ;-)

**Comment by eparis** [comment]
@lavalamp So it 'appears' that it adds lines in Godeps.json, but it is actually then doing a better job of pruning dead code. It is more explicitly stating what subdirs/packages it needs in Godeps and killing those it doesn't.  Which in turns breaks us, because, just by buggy/lucky chance godep was vendoring the binaries/main for both github.com/onsi/ginkgo/ginkgo and github.com/ugorji/go/codec/codecgen. v54 started better tracking and stopped vendoring those in.

Mine is trying to hack up crap to get those vendored in. Although @freeformz pointed out, when we try to move to vendor/ we're going to run into new fun problems vendoring those....

**Comment by freeformz** [comment]
FWIW: The Godeps/LICENSES files may not be necessary anymore. Modern godep versions will copy the LICENSE files of dependencies. If there is a case where it doesn't, then it's a bug and should be fixed.

**Comment by freeformz** [comment]
Closing in favor of #21786

**Pull request closed without merging**
