### PR TITLE
Add an API server log parsing and analysis script.

### PR DESCRIPTION
**Pull request by porridge**
**What this PR does / why we need it**:

I wrote this script during investigation of an API server performance
problem, namely https://github.com/kubernetes/kubernetes/issues/55779

The problem is that while most lines in the log are easily ingestible by
tools such as awk and grep, this is not universally true. Especially the
stack traces embedded in the middle of such lines add a lot of noise.

This script can be used both for filtering out uninteresting log
entries leaving the interesting for further analysis using other tools,
as well as for direct analysis of the data, such as calculating latency
percentiles, etc.

**Special notes for your reviewer**:

There are two main problems with this code:
 - it's not in golang
 - it can be rather slow in case of large volumes of logs, which is the
   case on large (e.g. 5k-node) clusters
I do not have plans to rewrite this to Go, but I think sharing it with
the community makes sense - it was very useful for myself and I think it
can be useful to others who analyze API server logs.

**Release note**:
```release-note
Added a script for parsing API server logs.
```

### CODE REVIEW

**Comment by sttts** [comment]
We ready need structured logs. They would make those things much simpler.

**Comment by porridge** [comment]
@shyamjvs FYI

**Comment by liggitt** [comment]
I appreciate the tool, but I don't think it belongs in-repo

**Comment by porridge** [comment]
Can you suggest a better place?

**Comment by porridge** [comment]
(FWIW I chose this location because it's close to the code which generates the entries which the script parses, to make it easy to keep them in sync.)

**Comment by porridge** [comment]
ping @liggitt

**Comment by sttts** [comment]
@porridge how do you want to keep this in sync? This is probably really tedious. We need something better, less manual. Structured logs would helps.

**Comment by porridge** [comment]
@sttts I completely agree structured logs is a superior approach.
It's just that it will most likely take months to roll out fully, and this script is useful now, to debug current production and scalability issues.

**Comment by liggitt** [comment]
> Can you suggest a better place?

I would probably publish it in a gist or repo of your own

> this script is useful now, to debug current production and scalability issues

I agree, I just think it is better distributed out of the repo

**Comment by porridge** [comment]
@shyamjvs you might want to copy this somewhere since I'm not going to maintain it after I leave.

**Comment by shyamjvs** [comment]
Sure.. thanks. Could you add a small description below on how to run the script?

**Comment by porridge** [comment]
`./parse_kube_apiserver_log.py --help` should produce a reasonable usage message

**Pull request closed without merging**
