### PR TITLE
Make scheduler_perf integration tests shorter

### PR DESCRIPTION
**Pull request by macsko**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Unfortunately, the integration tests running in ci-kubernetes-integration-master have a timeout set to 10 minutes, so it's needed to remove the `integration-test` label from all mid-sized workloads. If it still would take too long, in the next PR I'll have to remove a few test cases from running as integration. 

#### Which issue(s) this PR fixes:

Probably #127178

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sanposhiho** [comment]
So, I may miss a discussion somewhere though, actually do we have to run scheduler-perf at `ci-kubernetes-integration-master`, given we have another periodic job running on master `ci-benchmark-scheduler-perf-master`?

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve

Anyways put the stamp on this so that we can solve the test failure soon.

**Comment by alculquicondor** [comment]
> actually do we have to run scheduler-perf at ci-kubernetes-integration-master, given we have another periodic job running on master ci-benchmark-scheduler-perf-master?

The thinking was that in CI there is time to spare and we might as well just run more tests. But yeah, if the timeout is also 10m, then we have to leave these tests out.

**Pull request merged**
