### PR TITLE
Add unit tests for deployment controller

### PR DESCRIPTION
**Pull request by ironcladlou**
Add some minimal unit tests for the deployment controller.

### CODE REVIEW

**Comment by ironcladlou** [comment]
cc @nikhiljindal

**Comment by nikhiljindal** [comment]
LGTM, thanks!

@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
@ironcladlou Did you get a chance to cherrypick this?

**Comment by ironcladlou** [comment]
@nikhiljindal I did not, and I won't have time today. Sorry about that!

**Comment by nikhiljindal** [comment]
np. I will do it

**Pull request merged**
