### PR TITLE
pkg/kubectl: preallocate slice

### PR DESCRIPTION
**Pull request by gyuho**
To avoid slice growth with append operations.

### CODE REVIEW

**Comment by deads2k** [comment]
I'm not strictly opposed, but I find the literal creation easier to read and the memory efficiency of the CLI doesn't much worry me.

@kubernetes/kubectl any preferences for or against?

**Comment by smarterclayton** [comment]
I'm fine with this - make() isn't the devil, just slightly less clear.

**Comment by AdoHe** [comment]
I'm fine with this though I prefer the original one.

**Comment by gyuho** [comment]
Just rebased.

PTAL.

Thanks all.

**Comment by kargakis** [comment]
LGTM

**Comment by kargakis** [comment]
@k8s-bot test this issue: #IGNORE

**Pull request merged**
