### PR TITLE
Release 0.18

### PR DESCRIPTION
**Pull request by brendandburns**

### CODE REVIEW

**Comment by brendandburns** [comment]
@dchen1107 this is the correct one *sigh*

**Comment by brendandburns** [comment]
#9426 was into master, not release-0.18, this one is into the correct branch.

**Comment by dchen1107** [comment]
LGTM 

But just noticed that previous release is called 0.18.1.1,  not 0.18.1. Why?

**Comment by brendandburns** [comment]
I messed up when I built the original thing I uploaded to github and it was in a dirty git client.  So I re-uploaded, and rather than overwrite 0.18.1, I added 0.18.1.1

**Pull request merged**
