### PR TITLE
Move scheduler fake artifacts to pkg/scheduler/testing

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind cleanup
/sig scheduling

**What this PR does / why we need it**:

This PR moves some fake artifacts from pkg/scheduler/core to pkg/scheduler/testing so it can be consumed by pkg/scheduler/core tests as well as plugin (atm it's defaultpreemption) plugin.

This PR doesn't have dependencies, but will hold the PR (postfilter-impl-4) which moves Preempt() function to defaultpreemption package.

**Which issue(s) this PR fixes**:

Part of #91038.

**Special notes for your reviewer**:

This PR doesn't add new functions, just code movement.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
/assign @alculquicondor 
(I think @ahg-g has too much stuff in his review plate 😃 )

**Comment by alculquicondor** [comment]
looks good, but golint is failing

**Comment by Huang-Wei** [comment]
> looks good, but golint is failing

Yes, public functions have to have comments. Updated, PTAL.

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Pull request merged**
