### PR TITLE
update validate-cluster.sh

### LINKED ISSUE #19166: ubuntu kube-up validation failure
Using master, running `./kube-up.sh`

The cluster is created but validation fails with:

```
Validating master
Validating ubuntu@10.89.49.245
Validating ubuntu@10.89.49.247
Validating ubuntu@10.89.49.249
Using master 10.89.49.242
cluster "ubuntu" set.
user "ubuntu" set.
context "ubuntu" set.
switched to context "ubuntu".
Wrote config for ubuntu to /home/ubuntu/.kube/config
... calling validate-cluster
Found 3 node(s).
./../cluster/../cluster/../cluster/../cluster/../cluster/../cluster/../cluster/ubuntu/util.sh: line 47: roles[${ii}]: unbound variable
```

Seem to be caused by `nodes` variable override here: https://github.com/kubernetes/kubernetes/blob/master/cluster/validate-cluster.sh#L43

Renaming the variable to `_nodes` fixes it.

### PR DESCRIPTION
**Pull request by dalanlan**
Fix #19166
/cc @sebv @Sunweicheng0001

### CODE REVIEW

**Comment by SunWeicheng0001** [comment]
@dalanlan Hi, I test it by my self. The unbound variable is fixed, while the problem of etcd is still there.
My platform is ubuntu 14.04.1, kernel is 3.19.0-25-generic, docker version is 1.9.1
I just pulled kubernetes from HEAD. In my configuration, there is only one node, which is either master.
OK, here is my output
```
➜  cluster git:(master) ✗ ./kube-up.sh 
... Starting cluster using provider: ubuntu
... calling verify-prereqs
Identity added: /home/weicheng/.ssh/id_rsa (/home/weicheng/.ssh/id_rsa)
... calling kube-up
~/work/src/k8s.io/kubernetes/cluster/ubuntu ~/work/src/k8s.io/kubernetes/cluster
Prepare flannel 0.5.5 release ...
Prepare etcd 2.2.1 release ...
Prepare kubernetes 1.1.2 release ...
Done! All your binaries locate in kubernetes/cluster/ubuntu/binaries directory
~/work/src/k8s.io/kubernetes/cluster

Deploying master and node on machine 192.168.1.70
make-ca-cert.sh 100% 3270     3.2KB/s   00:00      
...
flanneld               100%   16MB  15.8MB/s   00:00    
[sudo] password to start master: 
etcd start/running, process 8572
etcd cluster has no published client endpoints.
Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:2379,http://127.0.0.1:4001).
Error:  client: no endpoints available
etcd cluster has no published client endpoints.
Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:2379,http://127.0.0.1:4001).
Error:  client: no endpoints available
Error:  100: Key not found (/coreos.com) [18]
{"Network":"172.16.0.0/16", "Backend": {"Type": "vxlan"}}
{"Network":"172.16.0.0/16", "Backend": {"Type": "vxlan"}}
docker stop/waiting
docker start/running, process 8758
Connection to 192.168.1.70 closed.
Validating master
Validating weicheng@192.168.1.70
Using master 192.168.1.70
cluster "ubuntu" set.
user "ubuntu" set.
context "ubuntu" set.
switched to context "ubuntu".
Wrote config for ubuntu to /home/weicheng/.kube/config
... calling validate-cluster
Found 1 node(s).
NAME           LABELS                                STATUS    AGE
192.168.1.70   kubernetes.io/hostname=192.168.1.70   Ready     7s
Validate output:
NAME                 STATUS    MESSAGE              ERROR
scheduler            Healthy   ok                   nil
etcd-0               Healthy   {"health": "true"}   nil
controller-manager   Healthy   ok                   nil
Cluster validation succeeded
Done, listing cluster services:

Kubernetes master is running at http://192.168.1.70:8080

```

**Comment by dalanlan** [comment]
@SunWeicheng0001 My best guess it's a race condition. The code is clean there in #17419.

**Comment by dalanlan** [comment]
ping @zmerlynn, or could you please re-assign if you're not available currently;-)

**Comment by SunWeicheng0001** [comment]
@dalanlan The code in #17419 only refer to the url of etcd. You say that might be a race condition, how can I fix it?

**Comment by dalanlan** [comment]
```
Try '--no-sync' if you want to access non-published client endpoints(http://127.0.0.1:2379,http://127.0.0.1:4001).
```
@SunWeicheng0001

**Comment by dalanlan** [comment]
ping @brendandburns  who might be available today. It's a small patch yet kinda critical.

**Comment by dalanlan** [comment]
@k8s-bot test this please

**Comment by dalanlan** [comment]
@k8s-bot test this

**Comment by dalanlan** [comment]
@k8s-bot test this

**Pull request merged**
