### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by sdminonne**
To fix minor typos

### CODE REVIEW

**Comment by lavalamp** [comment]
LGTM, but the lawyers require a CLA before I can merge. Can you please fill one out? (See CONTRIBUTING.md)

**Comment by benmccann** [comment]
@sdminonne don't forget to fill out the CLA

**Comment by roberthbailey** [comment]
Status: Needs rebase and still waiting on a signed CLA.

**Comment by sdminonne** [comment]
@lavalamp @roberthbailey @benmccann sorry I didn't see this. My company Amadeus SAS has signed it for some reasons I'm not in the list.
On Monday I'll try get in touch to my company lawyers to understand what's wrong.

**Comment by sdminonne** [comment]
@lavalamp @benmccann @roberthbailey CLA should be  solved. 
And I've rebased as well.

Agreement	Name	Date Signed
Google Corporate CLA	Amadeus SAS	Jan 22, 2015 10:56 PST

**Pull request merged**
