### PR TITLE
Fix broken link to generic_scheduler.go.

### PR DESCRIPTION
**Pull request by azalio**
**What this PR does / why we need it**:

Just fix the broken link in documentation.

**Release note**:

```
NONE

```

### CODE REVIEW

**Comment by CaoShuFeng** [comment]
Why this is pulled to release 1.5?

**Comment by azalio** [comment]
@CaoShuFeng because I read doc about 1.5 release. In which release do I need to do PR?

**Comment by CaoShuFeng** [comment]
/assign @mwielgus 
assign the 1.5 release manager.

**Comment by brendandburns** [comment]
1.5 is super old at this point. I don't think we need/want to keep it up to date...

**Pull request closed without merging**
