### PR TITLE
MOD:fix typo errors

### PR DESCRIPTION
**Pull request by calmkart**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

cleanup: fix the spelling error

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by dixudx — APPROVED** [review]
/lgtm

**Comment by calmkart** [comment]
@dixudx @deads2k 
PTAL
thanks

**Pull request closed without merging**
