### PR TITLE
Initial adoption of Ginkgo in Kubernetes e2e tests

### PR DESCRIPTION
**Pull request by filbranden**
These commits are a first step in migrating e2e tests to Ginkgo and implementing #3837.

The last commit also starts generating JUnit XML output for the tests which should allow for cleaner better integration of the e2e tests with Jenkins.

My proposal is:
1. We start using Ginkgo but do not touch the test code (this PR)
2. We start converting the individual e2e tests to Ginkgo (follow up PRs)
3. We continue converting bash tests to Go+Ginkgo
4. We start using JUnit XML output in Jenkins test, we improve it to include more metadata of the tests execution, more logs, etc.
5. We get rid of the shell script tests in `hack/e2e-suite/` and of `hack/e2e.go`, having a single standalone `cmd/e2e` that can be used to run all or a subset of the end-to-end tests on an existing test cluster.

@satnam6502 @rrati @timothysc @roberthbailey @zmerlynn

### CODE REVIEW

**Comment by rrati** [comment]
@filbranden this looks to be a reasonable proposal.  Is there is time frame for the complete conversion?  We don't want to add to the conversion work by continuing either bash scripts or test conversions to go w/o ginkgo/gomega if that is the intended end goal, so I'd suggest adding to the proposal that all future e2e work be in ginkgo/gomega while porting of old tests is done to ginkgo/gomega.

**Comment by zmerlynn** [comment]
Can you add a parameter for the report file rather than just hardcoding it as `junit.xml` in the current directory? (Which is what it seems to be doing.) That option should probably dictate whether it happens or not, too.

I haven't really reviewed yet, either, just giving this a once over for what I'd want out of it.

**Comment by filbranden** [comment]
@zmerlynn Ok I'll include a --reports_dir or similar flag and only enable the JUnit custom reporter if that path is set.

I'm leaning towards doing a flag with a directory name instead of a file name since when we run parallel tests one XML is generated per worker:

http://onsi.github.io/ginkgo/#generating-junit-xml-output

I think specifying a directory should be enough control for us, I don't see a reason why we would *need* the files to be called something other than `junit*.xml`

**Comment by filbranden** [comment]
@satnam6502 can you please take a look at the code in particular `driver.go`? I want to try to get this one finished today but for every small change it takes quite a bit of time to get it tested, so I'd like to make sure we agree on the approach and on the code before getting a new version published...

**Comment by zmerlynn** [comment]
Generating a directory is fine, Jenkins can slurp entire wildcards.

**Comment by zmerlynn** [comment]
The godeps stuff is voodoo to me. The rest LGTM, modulo the --reports_dir. You still owe me an --except in `hack/e2e.go` :)

**Comment by satnam6502** [comment]
I've looked at driver.go and as far as I can tell (which might not be very far) I think it is fine.

**Comment by satnam6502** [comment]
One thing I can't tell from this is whether we continue to create a fresh client for each test. Is that still the case?

**Comment by filbranden** [comment]
@satnam6502 Yes still the case, each test gets `loadClientOrDie()` as its argument, so each uses its own client.

See this one here for example:
https://github.com/filbranden/kubernetes/blob/ginkgo1/test/e2e/basic.go#L200

**Comment by satnam6502** [comment]
That's fine. I was wrong about the rate limit being applied to each client connection. I think the rate limit applies to each instance of the apiserver. So having separate clients is not buying us anything here. So it is fine I think to switch back to using a shared client for all the tests -- if that makes things easier or run faster.

**Comment by filbranden** [comment]
OK I added --report_dir and modified the Jenkins setup to save the junit.xml file on top of the Jenkins tree.

PTAL, I'd like to get this one merged today so that we can start making progress on converting the Go tests to native Ginkgo.

Tested by running the full `hack/e2e-test.sh` and had all goe2e.sh tests succeed (only update.sh failed in that particular run.)

**Comment by zmerlynn** [comment]
LGTM except for minor nit on last commit.

**Comment by zmerlynn** [comment]
LGTM. Travis isn't going to say anything about hack/jenkins, so I'm merging this so we can see if we broke anything quickly.

**Comment by filbranden** [comment]
Awesome thanks!

@rrati I think this means you can send us a PR to bring e.g. https://github.com/rrati/kubernetes/blob/ginkgo/test/ginkgo/pods_test.go into our tree.

(I wouldn't do network_test.go just now because that test has been flaky for a while... I think the others are better candidates.)

**Comment by zmerlynn** [comment]
I believe I've also modified the Jenkins config to slurp junit*.xml (which
will also work for us for future parallel stuff), but it'll be another hour
or so before we can see if that worked.

**Comment by filbranden** [comment]
@zmerlynn I'm really looking forward to seeing this! Will be very helpful and at least solve one of our current P0's which is the visibility of what inside goe2e.sh went bonkers when it fails... :-)

**Pull request merged**
