### PR TITLE
WIP golang: Update to go1.19beta1

### PR DESCRIPTION
**Pull request by cpanato**
#### What type of PR is this?

/kind feature
/area dependency

#### What this PR does / why we need it:

Part of https://github.com/kubernetes/release/issues/2575

- golang: Update to go1.19beta1

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by cpanato** [comment]
For Golang pre-releases, the `go-canary` variant for kubekins/krte needs to be built ahead of the `master` variant to enable testing go canary presubmits.

PR: https://github.com/kubernetes/test-infra/pull/26654

**Comment by aojea** [comment]
Carlos, is the plan to have golang 1.19 in this release ?

**Comment by cpanato** [comment]
> Carlos, is the plan to have golang 1.19 in this release?

@aojea I'm not sure, the plan for go1.19 release is some time in August (https://tip.golang.org/doc/go1.19#:~:text=Go%201.19%20is%20expected%20to%20be%20released%20in%20August%202022.) and the release dates for 1.25 is also in August (https://github.com/kubernetes/sig-release/tree/master/releases/release-1.25)

So might be tricky to have go1.19 and also have enough time to see if we will not get any issues as we had in the go1.18

**Comment by aojea** [comment]
I was asking because of that, dates are too close and too much risk IMHO

**Comment by cpanato** [comment]
closing in favor of https://github.com/kubernetes/kubernetes/pull/111254

**Pull request closed without merging**
