### PR TITLE
Revert "NodeController waits for informer sync before doing anything"

### PR DESCRIPTION
**Pull request by wojtek-t**
Reverts kubernetes/kubernetes#34809

It seems this one broke scalability tests:
This PR broke scalability test, by significantly increasing controller-manager usage, e.g.:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-kubemark-500-gce/6776
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-kubemark-5-gce/15565
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-kubemark-5-gce/15566
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-kubemark-5-gce/15567

@ncdc @deads2k @liggitt @gmarek

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34844)

### CODE REVIEW

**Comment by wojtek-t** [comment]
Unfortunately - it's pretty clear that this is this PR fault:
before the revert:
```
99 percentile:
"kube-controller-manager/kube-controller-manager" 0.082      75.98
```
after the revert:
```
99 percentile:
"kube-controller-manager/kube-controller-manager" 0.025      73.62
```

The increase seems to be even higher than 2x for small clusters.

I think that we really need to revert it.

**Comment by deads2k** [comment]
> Unfortunately - it's pretty clear that this is this PR fault:
> before the revert:

Do you see the bug that makes it slow?

**Comment by wojtek-t** [comment]
@deads2k - no, I have no idea. @lavalamp @davidopp - FYI

**Comment by wojtek-t** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-kubemark-500-gce/6777

The increase is from ~1 core to 1.9 cores - it is huuuuge.
I don't understand it...

**Comment by ncdc** [comment]
Me either. Would it make more sense to add the cache sync check one time, before the 3 goroutines are spawned, and *then* spawn them?

**Comment by wojtek-t** [comment]
@ncdc - NodeController::Run() will be blocking (which is not the case now), which means you need to change the both controller-manager binary and tests; though it might be the easiest thing...

**Comment by ncdc** [comment]
@wojtek-t or run a 4th goroutine that is the only one that waits for caches to sync, and have it close a channel that the other 3 goroutines are waiting on when they are synced (ew?)

**Comment by wojtek-t** [comment]
@ncdc - oh yeah - that actually sounds great and pretty straightforward

**Comment by ncdc** [comment]
We do still need to figure out why the cpu spiked though

**Comment by liggitt** [comment]
well, there are three goroutines, each calling `Informer()` (which contends for locks) three times every 100ms... I would store the result of `Informer()` in the struct instead of calling .Informer() inside the goroutines

**Comment by wojtek-t** [comment]
@liggitt - I think that doing this once at the begining instead of doing it in those go-routines (the way how @ncdc suggested) is much better

**Comment by liggitt** [comment]
we should do both... grab the informers once, and wait for syncs before spawning goroutines

**Comment by wojtek-t** [comment]
@liggitt - if we do the latter (wait for sycs before spawning), then I don't think the former is needed...

**Comment by liggitt** [comment]
yeah, misread the loop. WaitForCacheSync is only called once per goroutine since it's given a `NeverStop` channel

**Comment by ncdc** [comment]
Working with @wojtek-t on a fix, removing lgtm

**Comment by ncdc** [comment]
#34851 hopefully will fix this

**Comment by wojtek-t** [comment]
#34851 fixed the problem and is already merged. Closing this one.

**Pull request closed without merging**
