### PR TITLE
Update CNI plugins v0.9.1

### LINKED ISSUE #102311: Update CNI plugins
The latest release of CNI plugins is [v0.9.1](https://github.com/containernetworking/plugins/releases/tag/v0.9.1), but we still have [v0.8.7 in the dependencies](https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml#L37).

I'll attempt to create a PR for this based on the [last update](https://github.com/kubernetes/kubernetes/pull/94367).

### PR DESCRIPTION
**Pull request by lentzi90**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Update CNI plugins v0.9.1
ref: https://github.com/containernetworking/plugins/releases/tag/v0.9.1

#### Which issue(s) this PR fixes:

Fixes #102311

#### Special notes for your reviewer:

Based on the [last update of CNI plugins](https://github.com/kubernetes/kubernetes/pull/94367) it looks like the release should be uploaded to some bucket. I don't think I have access to this so it would be very nice if someone could help out with it.

#### Does this PR introduce a user-facing change?

```release-note
Update CNI plugins to v0.9.1
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by dims** [comment]
cc: @kubernetes/sig-network-pr-reviews @kubernetes/release-engineering

@saschagrunert @hasheddan @justaugustus looks like one of the releng folks need to push stuff to `k8s-artifacts-cni` bucket.

**Comment by cpanato** [comment]
on it @dims

**Comment by cpanato** [comment]
@dims done
```
$ gsutil ls gs://k8s-artifacts-cni/release/v0.9.1
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-amd64-v0.9.1.tgz
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-amd64-v0.9.1.tgz.sha1
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-amd64-v0.9.1.tgz.sha256
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-amd64-v0.9.1.tgz.sha512
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-arm-v0.9.1.tgz
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-arm-v0.9.1.tgz.sha1
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-arm-v0.9.1.tgz.sha256
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-arm-v0.9.1.tgz.sha512
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-arm64-v0.9.1.tgz
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-arm64-v0.9.1.tgz.sha1
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-arm64-v0.9.1.tgz.sha256
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-arm64-v0.9.1.tgz.sha512
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-mips64le-v0.9.1.tgz
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-mips64le-v0.9.1.tgz.sha1
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-mips64le-v0.9.1.tgz.sha256
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-mips64le-v0.9.1.tgz.sha512
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-ppc64le-v0.9.1.tgz
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-ppc64le-v0.9.1.tgz.sha1
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-ppc64le-v0.9.1.tgz.sha256
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-ppc64le-v0.9.1.tgz.sha512
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-s390x-v0.9.1.tgz
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-s390x-v0.9.1.tgz.sha1
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-s390x-v0.9.1.tgz.sha256
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-linux-s390x-v0.9.1.tgz.sha512
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-windows-amd64-v0.9.1.tgz
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-windows-amd64-v0.9.1.tgz.sha1
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-windows-amd64-v0.9.1.tgz.sha256
gs://k8s-artifacts-cni/release/v0.9.1/cni-plugins-windows-amd64-v0.9.1.tgz.sha512
```

**Comment by dims** [comment]
/ok-to-test

thanks @cpanato

**Review by ehashman — COMMENTED** [review]
/priority important-longterm
/triage accepted
/lgtm

**Comment by lentzi90** [comment]
Looks like flaky test https://github.com/kubernetes/kubernetes/issues/101894
/retest

**Comment by justaugustus** [comment]
For `build/`:
/lgtm
/approve

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
