### PR TITLE
[WIP] Provider/Azure: Enrich unit tests.

### LINKED ISSUE #86841: Provider/Azure: Enrich unit test cases.
**What happened**:

Currently, the unit tests are not enough for cloud provider azure.

**What you expected to happen**:

Enrich the unit tests.

- [x] `azure_controller_vmss.go`
- [ ] `azure_vmss.go`
- [ ] `azure_instance_metadata.go`
- [ ] `azure_instance.go`
- [ ] `azure_managed_disk_controller.go`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/area provider/azure
/assign

### PR DESCRIPTION
**Pull request by nilo19**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Enrich unit tests.

**Which issue(s) this PR fixes**:

Fixes #86841 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/area provider/azure

### CODE REVIEW

**Comment by tanjunchen** [comment]
Which issue(s) this PR fixes:
ref  not fixes
fixes will close the issue

**Comment by nilo19** [comment]
> Which issue(s) this PR fixes:
> ref not fixes
> fixes will close the issue

yup, it'll fix and close #86841

**Comment by tanjunchen** [comment]
> > Which issue(s) this PR fixes:
> > ref not fixes
> > fixes will close the issue
> 
> yup, it'll fix and close #86841

done

**Pull request closed without merging**
