### PR TITLE
Refactor kube-proxy ServiceMap to ServicePortMap and BaseServiceInfo to BaseServicePort

### LINKED ISSUE #108806: Cleanup: kube-proxy internal naming
We have sort of a mish-mash of "service" and "servicePort" and similar.

We should think about changing ALL of the places that actually relate to a service-port (a specific port of a service, not the whole service) and rename them to some new term that means "service port". E.g. "svcpt" or "spt" or "sport".

See https://github.com/kubernetes/kubernetes/pull/106497/commits/8fffae321d66487f776922e0c313b33af7bf27e3 in pkg/proxy/iptables/proxier.go and friends.  e.g. `info.serviceNameString` -> `info.svcptNameString` ?

### PR DESCRIPTION
**Pull request by gkarthiks**
#### What type of PR is this?

Refactoring variable name (ServiceMap to ServicePortMap; BaseServiceInfo to BaseServicePort) for meaningful map and struct.

/kind cleanup

#### What this PR does / why we need it:
Renames the various occurrence of the BaseServiceInfo struct to BaseServicePort and ServiceMap to ServicePortMap to be unanimous for better redability.

#### Which issue(s) this PR fixes:

Fixes #108806 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/cc @thockin @danwinship

### CODE REVIEW

**Comment by danwinship** [comment]
/hold
this PR is messed up: it includes an (empty) merge commit, and then the commit with the code in it seems to include pieces of two different PRs

**Comment by gkarthiks** [comment]
> /hold this PR is messed up: it includes an (empty) merge commit, and then the commit with the code in it seems to include pieces of two different PRs

Sorry about that. Let me fix that.

**Comment by gkarthiks** [comment]
@danwinship @thockin should be fine now. Can you please review this?

**Comment by neolit123** [comment]
/remove-sig cluster-lifecycle
/remove-area kubeadm


the kubeadm change was already merged / needs rebase.

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by gkarthiks** [comment]
i'll close this for now and re-open to fix that in the month of Jan or Feb.

**Pull request closed without merging**
