### PR TITLE
Promote CronJobs to batch/v1beta1 - just the API

### PR DESCRIPTION
**Pull request by soltysh**
This PR promotes CronJobs to beta.

@erictune @kubernetes/sig-apps-api-reviews @kubernetes/api-approvers ptal

This builds on top of #41890 and needs #40932 as well

```release-note
Promote CronJobs to batch/v1beta1.
```

### CODE REVIEW

**Comment by soltysh** [comment]
@kubernetes/sig-api-machinery-pr-reviews ptal as well

**Comment by calebamiles** [comment]
Moved this issue into the next milestone @soltysh. This PR did not get `lgtm` before code freeze and needs rebase and or rework. Feel free to file an [exception](https://github.com/kubernetes/features/blob/master/EXCEPTIONS.md) if you feel it's warranted.

**cc: @ethernetdan, @kubernetes/kubernetes-release-managers**

**Comment by soltysh** [comment]
@calebamiles I did file an exception, I'm waiting for hearing back.

**Comment by soltysh** [comment]
It looks like the cronjob controller is tightly coupled with `batch/v2alpha` version and when `batch/v2alpha1` and `batch/v1beta1` are enabled at once it confuses `kubectl` on the other hand. So I need to put a lot more work to make it usable. Again multiversioning problems, sigh... 😕

**Comment by janetkuo** [comment]
@soltysh would it be easier if we remove `batch/v2alpha1` altogether?

**Comment by soltysh** [comment]
> @soltysh would it be easier if we remove batch/v2alpha1 altogether?

It would definitely be easier, not sure if desirable, though. @erictune any objections on Janet's suggestion? I'll bring it up during next sig-apps call, to have a broader audience.

**Comment by deads2k** [comment]
> It would definitely be easier, not sure if desirable, though. @erictune any objections on Janet's suggestion? I'll bring it up during next sig-apps call, to have a broader audience.

It seems mean to break users when the serialization and behavior is actually compatible.  Perhaps a series of simple reproducers will help us push past the problems with help from @kubernetes/sig-cli-bugs

**Comment by davidopp** [comment]
There's a proposal that could in theory subsume cron jobs
https://docs.google.com/document/d/1-H2hnZap7gQivcSU-9j4ZrJ8wE_WwcfOkTeAGjzUyLA/edit
but it will require a lot of work.

**Comment by soltysh** [comment]
@davidopp will you be able to attend sig-apps today and we can have a discussion.

**Comment by davidopp** [comment]
@soltysh Sorry, didn't see this in time.

We'll be discussing the proposal at the sig-scheduling meeting today at 2:30 PM PT https://zoom.us/j/966775765

**Comment by soltysh** [comment]
@davidopp sorry but too late for me :( I'll watch the recording and will catch up with you later this week.

**Comment by erictune** [comment]
@davidopp  I don't think that proposal subsumes cronjobs, does it?

**Comment by dchen1107** [comment]
I am moving this WIP pr to v1.8. The pr is not in ready state, and no activity for more than 19 days.

**Comment by janetkuo** [comment]
@soltysh this needs a rebase

**Comment by soltysh** [comment]
@janetkuo ptal, I've enabled only the API here so that we can move with this forward. I need to address the remaining bits, such us how to deal with CronJobs when both v2alpha1 and v1beta1 is enabled. But I'd prefer to do it as a followup, for now I've turned off this new API and when all the pieces will be in I'll re-enable it permanently.

**Comment by soltysh** [comment]
Forgot to actually comment the v1beta1 in master.go. Fixed, should be good.

**Comment by soltysh** [comment]
One more try, I've rebased `hack/update-all.sh`-ed and crossing my fingers.

**Comment by soltysh** [comment]
Fixed last bit, the `test/integration/etcd/etcd_storage_path_test.go`. Should be green now 🤞

**Comment by soltysh** [comment]
@erictune @janetkuo it's finally green 😄 mind pushing this forward?

**Pull request merged**
