### PR TITLE
fix flake integration rotation via informer

### LINKED ISSUE #102650: TestExecPluginRotationViaInformer flake and slow > 2min
### Failure cluster [670e16aa8066230be73b](https://go.k8s.io/triage#670e16aa8066230be73b)

    exec_test.go:627: wanted sync true, got sync false
    exec_test.go:740: wanted sync true, got sync false
    exec_test.go:750: wanted sync true, got sync false

    exec_test.go:771: informer never changed resource versions from "42606": timed out waiting for the condition

##### Error text:
```
=== RUN   TestExecPluginRotationViaInformer
=== PAUSE TestExecPluginRotationViaInformer
=== CONT  TestExecPluginRotationViaInformer
E0527 06:04:00.043307  121243 controller.go:184] Get "https://127.0.0.1:40847/api/v1/namespaces/default/endpoints/kubernetes": dial tcp 127.0.0.1:40847: connect: connection refused
    testserver.go:380: Resolved testserver package path to: "/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/testing"
I0527 06:04:02.747118  121243 serving.go:341] Generated self-signed cert (/tmp/kubernetes-kube-apiserver650002284/apiserver.crt, /tmp/kubernetes-kube-apiserver650002284/apiserver.key)
I0527 06:04:02.747132  121243 server.go:614] external host was not specified, using 127.0.0.1
W0527 06:04:02.747142  121243 authentication.go:524] AnonymousAuth is not allowed with the AlwaysAllow authorizer. Resetting AnonymousAuth to false. You should use a different authorizer
    testserver.go:215: runtime-config=map[api/all:true]
    testserver.go:216: Starting kube-apiserver on port 45509...
W0527 06:04:04.040009  121243 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0527 06:04:04.040050  121243 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0527 06:04:04.040068  121243 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0527 06:04:04.040611  121243 mutation_detector.go:53] Mutation detecto
```
#### Recent failures:
[2021/5/31 上午4:10:22 ci-kubernetes-integration-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1399095506172383232)
[2021/5/27 下午9:41:15 ci-kubernetes-integration-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1397910435235106816)
[2021/5/27 下午1:39:15 ci-kubernetes-integration-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1397789133039996928)

/kind failing-test
/kind flake

@ankeesler  @enj as it is added in #101726
/sig auth

Open it as it is the top flake of pull-kubernetes-integration: http://storage.googleapis.com/k8s-metrics/flakes-latest.json

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:

The first change of `waitForEvents` is only to reduce the test execution time(- 30 seconds):
- If wantEvents=false, wait only 15 seconds.
- If wantEvents=true, wait for all events 30 seconds

The second change of `waitForInformerSync` is to deflake.
https://github.com/kubernetes/kubernetes/blob/1b71cc567f45da25c82e63950b026e36c5060edc/cmd/kube-apiserver/app/options/options.go#L119 
IdentityLeaseRenewIntervalSeconds is by default 10 seconds which is the interval for lease renew.
```
 lease.go:233] Resetting endpoints for master service "kubernetes" to [127.0.0.1]
```
We can see the lease log to reset endpoints every 10 seconds. If the informer missed the sync in 20+ seconds, it will add 10  seconds to get the sync. 

During the local test, I failed for 30 seconds several times.
So I suggest adding to 60 seconds for this timeout.

#### Which issue(s) this PR fixes:

Fixes #102650
@ankeesler @enj as the test case was added in #101726
/sig auth

#### Special notes for your reviewer:
I still not find a better way to make it happen more quickly and another way(not enlarge the timeout) to make it less flaky. 

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Review by ankeesler — COMMENTED** [review]
I actually thought about adding this conditional wait timeout as well. That makes sense to me.

I originally had the timeouts at 60 seconds, and then @enj commented that the test was quite long. I dropped it to 30 seconds since it was stable with that timeout on my machine and in CI, but sounds like there were other environments that I did not consider. If this is failing on someone's laptop, I think we should increase the timeout or find a more synchronous way to assert this. I can't think of a more synchronous way to assert this.

I don't have approval rights, so maybe we can get @enj to take a look here. It would also be good to get his opinion on what to do here.

Does this change drop the test time to < 2 minutes as reported in the issue?

**Comment by pacoxu** [comment]
> Does this change drop the test time to < 2 minutes as reported in the issue?

The test time is similar. We wait for the condition more in the `waitForInformerSync` and wait for the condition with less time in `waitForEvents`.

**Pull request merged**
