### PR TITLE
Optimize priorities in scheduler

### PR DESCRIPTION
**Pull request by wojtek-t**
Ref #28590

It's probably easier to review it commit by commit, since those changes are kind of independent from each other.

@davidopp - FYI

### CODE REVIEW

**Comment by wojtek-t** [comment]
@gmarek @davidopp 
It's probably easier to review it commit by commit, since those changes are kind of independent from each other.

**Comment by wojtek-t** [comment]
Fixed compile error from the first commit.

**Comment by xiang90** [comment]
looks good to me.

**Comment by gmarek** [comment]
LGTM

**Pull request merged**
