### PR TITLE
Add test for cmd/kubeadm/app/constants/constants.go

### PR DESCRIPTION
**Pull request by Octopusjust**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Add UT

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/ok-to-test
/release-note-none
/approve

thanks. we are in code freeze and this pr can merge later

**Comment by Octopusjust** [comment]
> /ok-to-test /release-note-none /approve
> 
> thanks. we are in code freeze and this pr can merge later

OK :)

**Pull request merged**
