### PR TITLE
Bump Konnectivity to v0.0.35 in release-1.26

### PR DESCRIPTION
**Pull request by jkh52**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

*apiserver*: Bump konnectivity-client v0.0.35, and register the new metrics.
*proxy-server and proxy-agent*: Use v0.0.35 binaries (metrics and logging improvements).

When apiserver is configured to use Konnectivity, these new metrics help pinpoint cluster egress root cause. In particular, the client dial failures metric (by reason) will be very useful.

Clean cherry picks of:

* https://github.com/kubernetes/kubernetes/pull/114646 (support registration)
* https://github.com/kubernetes/kubernetes/pull/114789 (konnectivity-client/v0.0.35)
* https://github.com/kubernetes/kubernetes/pull/114832 (register metrics)

#### Special notes for your reviewer:

*Risk analysis*: see discussion at https://github.com/kubernetes/kubernetes/pull/114832; registered but unused metrics will not be emitted, therefore this PR should be a no-op whenever `apiserver` does not use `EgressSelectorConfiguration` options associated with Konnectivity.

The difference [from v0.0.33](https://github.com/kubernetes-sigs/apiserver-network-proxy/compare/konnectivity-client/v0.0.33...konnectivity-client/v0.0.35) is purely metrics and logging improvements.

Smaller diff (restricted to konnectivity-client library):
```
$ git log --summary v0.0.33..v0.0.35 konnectivity-client`

commit cce2a51b373023acdaa1becfe3d28ecf014a0a91
Author: Joseph Anttila Hall <jkh@google.com>
Date:   Tue Dec 20 19:46:25 2022 +0000

    konnectivity-client: add a tunnels gauge metric.


commit 005c7813d792a7228f83c8816e548cdd6ec839b2
Author: Joseph Anttila Hall <jkh@google.com>
Date:   Tue Dec 13 10:32:18 2022 -0800

    konnectivity-client: add dial failures metric by reason.

 create mode 100644 konnectivity-client/pkg/common/metrics/testing/metrics.go

commit bfa285eda65819424b3f6620c026fd791534e7ac
Author: Joseph Anttila Hall <jkh@google.com>
Date:   Mon Dec 12 23:06:47 2022 -0800

    konnectivity-client: make release-0.0 branch compatible with older k/k minor versions.


commit 869e056ba6aa811fb7c529d28365970c682da8f6
Author: Joseph Anttila Hall <jkh@google.com>
Date:   Sun Nov 13 23:39:35 2022 -0800

    Add several new metrics, including new KAS client package.

 create mode 100644 konnectivity-client/pkg/client/metrics/metrics.go
 create mode 100644 konnectivity-client/pkg/common/metrics/metrics.go

commit e928a49d8862852cb431af4fb90793e33a008eca
Merge: 6faac34 0de2942
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Tue Nov 22 16:40:15 2022 -0800

    Merge pull request #419 from tallclair/dial-rsp-log
    
    Improve dial response logging

commit 0de2942a4b4d708c829ee9d1b30d7d511f81e311
Author: Tim Allclair <tallclair@google.com>
Date:   Thu Nov 17 10:45:20 2022 -0800

    Improve dial response logging


commit a2dc6cf390d6de3ce7618296ec9ce41545050ba8
Author: Tim Allclair <tallclair@google.com>
Date:   Wed Nov 16 17:29:51 2022 -0800

    go mod tidy
```

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jkh52** [comment]
Test flakes:

```
{  error during ./hack/e2e-internal/e2e-down.sh (interrupted): signal: interrupt}
...
{  kubetest --timeout triggered}
```

/retest

**Comment by liggitt** [comment]
cc @kubernetes/release-managers

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
/triage accepted

for some reason when i added the cherry pick label it removed all the others :/
sorry about that

**Pull request merged**
