### PR TITLE
Update Travis and Coveralls URLs

### PR DESCRIPTION
**Pull request by senorflor**

### CODE REVIEW

**Comment by senorflor** [comment]
I signed it!

**Comment by mbforbes** [comment]
Thanks for doing this! it was bothering me too. Shippable looks like a flake so let me close/open your PR.

**Comment by senorflor** [comment]
Thanks for the rebuild!

**Comment by senorflor** [comment]
Putting this inferior coveralls.io migration approach on hold in order to get historical data in the same link–standby.

**Comment by mbforbes** [comment]
I'm fine with either way (not sure anyone will care about the history). +cc @mikedanese @brendandburns

**Comment by mikedanese** [comment]
Thanks. This is part of the last part of #12211.

**Comment by mbforbes** [comment]
@mikedanese do you care about coverage history? I was thinking it'd be fine to just switch to `kubernetes/kubernetes` with a clean slate and refer people to `GoogleCloudPlatform/kubernetes` for coverage history (as @senorflor had originally).

This LGTM, so if the above sounds good to you @mikedanese please add LGTM label and we can get this in.

**Comment by mikedanese** [comment]
I don't think history is very important.

**Comment by roberthbailey** [comment]
@senorflor I'm happy to merge if you agree that we don't care about history.

**Comment by senorflor** [comment]
Agreed; let's merge and :ship: on!

**Pull request merged**
