### PR TITLE
Update CNI plugins to v0.8.7

### PR DESCRIPTION
**Pull request by justaugustus**
**What type of PR is this?**

/kind cleanup
/area dependency release-eng
/sig network release

**What this PR does / why we need it**:

Update CNI plugins to v0.8.7

ref: https://github.com/containernetworking/plugins/releases/tag/v0.8.7

Signed-off-by: Stephen Augustus <saugustus@vmware.com>

/assign @dcbw @squeed 
cc: @kubernetes/sig-network-pr-reviews @kubernetes/release-engineering 

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

### Getting [gh2gcs](https://github.com/kubernetes/release/tree/master/cmd/gh2gcs)

```console
$ go install ./cmd/gh2gcs/...
```

### Uploading the new release

```console
$ time gh2gcs --org containernetworking --repo plugins --bucket k8s-artifacts-cni --release-dir release --tags v0.8.7
INFO Validating gh2gcs options...                 
INFO Downloading assets for the following containernetworking/plugins release tags: v0.8.7 
INFO Download assets for containernetworking/plugins@v0.8.7 
INFO Writing assets to /tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7 
INFO GitHub asset ID: 24314786, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-amd64-v0.8.7.tgz.asc 
INFO GitHub asset ID: 24314871, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-ppc64le-v0.8.7.tgz 
INFO GitHub asset ID: 24314972, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-amd64-v0.8.7.tgz 
INFO GitHub asset ID: 24314790, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-s390x-v0.8.7.tgz.sha512 
INFO GitHub asset ID: 24314782, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-ppc64le-v0.8.7.tgz.asc 
INFO GitHub asset ID: 24314792, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-ppc64le-v0.8.7.tgz.sha512 
INFO GitHub asset ID: 24314798, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-amd64-v0.8.7.tgz.sha512 
INFO GitHub asset ID: 24314807, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-s390x-v0.8.7.tgz.sha1 
INFO GitHub asset ID: 24314799, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-windows-amd64-v0.8.7.tgz.sha256 
INFO GitHub asset ID: 24314795, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-arm64-v0.8.7.tgz.sha512 
INFO GitHub asset ID: 24314809, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-mips64le-v0.8.7.tgz.sha1 
INFO GitHub asset ID: 24314785, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-arm64-v0.8.7.tgz.asc 
INFO GitHub asset ID: 24314802, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-mips64le-v0.8.7.tgz.sha256 
INFO GitHub asset ID: 24314794, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-mips64le-v0.8.7.tgz.sha512 
INFO GitHub asset ID: 24314796, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-arm-v0.8.7.tgz.sha512 
INFO GitHub asset ID: 24314922, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-arm64-v0.8.7.tgz 
INFO GitHub asset ID: 24314784, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-arm-v0.8.7.tgz.asc 
INFO GitHub asset ID: 24314810, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-arm64-v0.8.7.tgz.sha1 
INFO GitHub asset ID: 24314811, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-arm-v0.8.7.tgz.sha1 
INFO GitHub asset ID: 24314952, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-arm-v0.8.7.tgz 
INFO GitHub asset ID: 24314842, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-mips64le-v0.8.7.tgz 
INFO GitHub asset ID: 24314812, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-amd64-v0.8.7.tgz.sha1 
INFO GitHub asset ID: 24314800, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-s390x-v0.8.7.tgz.sha256 
INFO GitHub asset ID: 24314804, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-arm-v0.8.7.tgz.sha256 
INFO GitHub asset ID: 24314781, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-s390x-v0.8.7.tgz.asc 
INFO GitHub asset ID: 24314789, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-windows-amd64-v0.8.7.tgz.sha512 
INFO GitHub asset ID: 24314803, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-arm64-v0.8.7.tgz.sha256 
INFO GitHub asset ID: 24314808, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-ppc64le-v0.8.7.tgz.sha1 
INFO GitHub asset ID: 24314783, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-mips64le-v0.8.7.tgz.asc 
INFO GitHub asset ID: 24314805, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-amd64-v0.8.7.tgz.sha256 
INFO GitHub asset ID: 24314777, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-windows-amd64-v0.8.7.tgz.asc 
INFO GitHub asset ID: 24314806, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-windows-amd64-v0.8.7.tgz.sha1 
INFO GitHub asset ID: 24314813, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-windows-amd64-v0.8.7.tgz 
INFO GitHub asset ID: 24314801, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-ppc64le-v0.8.7.tgz.sha256 
INFO GitHub asset ID: 24314851, download URL: https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-s390x-v0.8.7.tgz 
INFO Files downloaded to /tmp/gh2gcs531637864 directory 
INFO Copying /tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7 to GCS (k8s-artifacts-cni/release/v0.8.7) 
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-amd64-v0.8.7.tgz.sha256 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-s390x-v0.8.7.tgz.sha512 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-s390x-v0.8.7.tgz.asc [Content-Type=text/plain]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-s390x-v0.8.7.tgz.sha256 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-arm64-v0.8.7.tgz [Content-Type=application/x-tar]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-s390x-v0.8.7.tgz [Content-Type=application/x-tar]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-s390x-v0.8.7.tgz.sha1 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-arm64-v0.8.7.tgz.sha1 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-mips64le-v0.8.7.tgz [Content-Type=application/x-tar]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-arm-v0.8.7.tgz.sha512 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-arm-v0.8.7.tgz.sha1 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-ppc64le-v0.8.7.tgz.sha256 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-ppc64le-v0.8.7.tgz.sha512 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-mips64le-v0.8.7.tgz.sha256 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-windows-amd64-v0.8.7.tgz.sha1 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-mips64le-v0.8.7.tgz.sha512 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-ppc64le-v0.8.7.tgz.asc [Content-Type=text/plain]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-windows-amd64-v0.8.7.tgz [Content-Type=application/x-tar]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-ppc64le-v0.8.7.tgz [Content-Type=application/x-tar]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-arm64-v0.8.7.tgz.sha512 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-amd64-v0.8.7.tgz.asc [Content-Type=text/plain]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-arm-v0.8.7.tgz [Content-Type=application/x-tar]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-amd64-v0.8.7.tgz.sha1 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-amd64-v0.8.7.tgz.sha512 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-ppc64le-v0.8.7.tgz.sha1 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-mips64le-v0.8.7.tgz.sha1 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-arm-v0.8.7.tgz.sha256 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-arm64-v0.8.7.tgz.asc [Content-Type=text/plain]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-arm-v0.8.7.tgz.asc [Content-Type=text/plain]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-arm64-v0.8.7.tgz.sha256 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-windows-amd64-v0.8.7.tgz.sha256 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-windows-amd64-v0.8.7.tgz.sha512 [Content-Type=application/octet-stream]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-mips64le-v0.8.7.tgz.asc [Content-Type=text/plain]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-windows-amd64-v0.8.7.tgz.asc [Content-Type=text/plain]...
Copying file:///tmp/gh2gcs531637864/containernetworking/plugins/v0.8.7/cni-plugins-linux-amd64-v0.8.7.tgz [Content-Type=application/x-tar]...
- [35/35 files][231.3 MiB/231.3 MiB] 100% Done   1.2 MiB/s ETA 00:00:00         
Operation completed over 35 objects/231.3 MiB.                                   
INFO Cleaning temporary directory /tmp/gh2gcs531637864 

real	3m6.569s
user	0m11.118s
sys	0m3.907s
```

### Getting the new SHAs

```console
$ gsutil cat gs://k8s-artifacts-cni/release/v0.8.7/cni-plugins-linux-amd64-v0.8.7.tgz.sha1
96a30cb67e33da95fb1d99f93dd787c2a3c08627  cni-plugins-linux-amd64-v0.8.7.tgz

$ for arch in amd64 arm arm64 ppc64le s390x; do gsutil cat gs://k8s-artifacts-cni/release/v0.8.7/cni-plugins-linux-$arch-v0.8.7.tgz.sha256 || true; done
977824932d5667c7a37aa6a3cbba40100a6873e7bd97e83e8be837e3e7afd0a8  cni-plugins-linux-amd64-v0.8.7.tgz
5757778f4c322ffd93d7586c60037b81a2eb79271af6f4edf9ff62b4f7868ed9  cni-plugins-linux-arm-v0.8.7.tgz
ae13d7b5c05bd180ea9b5b68f44bdaa7bfb41034a2ef1d68fd8e1259797d642f  cni-plugins-linux-arm64-v0.8.7.tgz
70a8c5448ed03a3b27c6a89499a05285760a45252ec7eae4190c70ba5400d4ba  cni-plugins-linux-ppc64le-v0.8.7.tgz
3a0008f98ea5b4b6fd367cac3d8096f19bc080a779cf81fd0bcbc5bd1396ace7  cni-plugins-linux-s390x-v0.8.7.tgz
```

**Does this PR introduce a user-facing change?**:

```release-note
Update CNI plugins to v0.8.7
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Review by xmudrii — APPROVED** [review]
/lgtm

**Comment by neolit123** [comment]
/lgtm
/approve
thanks!

**Comment by squeed** [comment]
/lgtm

thanks so much for being on top of this!

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by BenTheElder** [comment]
/lgtm
/approve
xref: https://github.com/kubernetes-sigs/kind/pull/1815

**Pull request merged**
