### PR TITLE
Consolidate dev-build*.sh

### LINKED ISSUE #72297: dev-build-and-push.sh is broken
Hi,

the `hack/dev-build-and-push.sh` script is broken because the `cluster/kube-push.sh` script has been removed from in this pull request: https://github.com/kubernetes/kubernetes/pull/58247 .

Is `dev-build-and-push.sh` deprecated too, shall we remove it?

/kind bug

### PR DESCRIPTION
**Pull request by dims**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Drop the kube-up and kube-push usage from scripts in hack/

Change-Id: I3c8b7f5ac1ebe6dccb1d5430a6b3ce445e9adda0

**Which issue(s) this PR fixes**:

Fixes #72297

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ixdy** [comment]
do we even need this script? all it's doing is calling `make quick-release` now.

**Comment by dims** [comment]
ack. i'll just remove it in another PR

**Pull request closed without merging**
