### PR TITLE
[addon-manager] Remove unneeded annotation codes

### PR DESCRIPTION
**Pull request by MrHohn**
**What this PR does / why we need it**:
Clean up addon-manager codes to make it less confusing. The annotation logics is only needed for 1.4->1.5 upgrade.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by MrHohn** [comment]
cc @mikedanese

**Comment by eparis** [comment]
/approve
but not deep code review
/assign @mikedanese

**Pull request merged**
