### PR TITLE
kubelet: add latency metrics to network plugin manager

### PR DESCRIPTION
**Pull request by sjenning**
This PR adds latency metrics to the network plugin operations, namely `GetPodNetworkStatus()`, `SetUpPod()`, and `TearDownPod()`.

I recently had to debug and issue where a PLEG relist hang was occurring due to a hang in a CNI plugin and it would have been really nice to have these.  Between the these new metrics and `docker_operations_latency_microseconds`, we will be able to account for nearly all the time consuming routines in the PLEG relist.

@derekwaynecarr @smarterclayton @eparis @vishh 

```release-note
Metrics were added to network plugin to report latency of CNI operations
```
/sig node

### CODE REVIEW

**Comment by sjenning** [comment]
/assign @thockin 

fyi, metrics look like this
```
# HELP kubelet_network_plugin_operations_latency_microseconds Latency in microseconds of network plugin operations. Broken down by operation type.
# TYPE kubelet_network_plugin_operations_latency_microseconds summary
kubelet_network_plugin_operations_latency_microseconds{operation_type="get_pod_network_status",quantile="0.5"} 11
kubelet_network_plugin_operations_latency_microseconds{operation_type="get_pod_network_status",quantile="0.9"} 13
kubelet_network_plugin_operations_latency_microseconds{operation_type="get_pod_network_status",quantile="0.99"} 13
kubelet_network_plugin_operations_latency_microseconds_sum{operation_type="get_pod_network_status"} 172
kubelet_network_plugin_operations_latency_microseconds_count{operation_type="get_pod_network_status"} 3
kubelet_network_plugin_operations_latency_microseconds{operation_type="set_up_pod",quantile="0.5"} 161
kubelet_network_plugin_operations_latency_microseconds{operation_type="set_up_pod",quantile="0.9"} 161
kubelet_network_plugin_operations_latency_microseconds{operation_type="set_up_pod",quantile="0.99"} 161
kubelet_network_plugin_operations_latency_microseconds_sum{operation_type="set_up_pod"} 161
kubelet_network_plugin_operations_latency_microseconds_count{operation_type="set_up_pod"} 1
kubelet_network_plugin_operations_latency_microseconds{operation_type="tear_down_pod",quantile="0.5"} 16
kubelet_network_plugin_operations_latency_microseconds{operation_type="tear_down_pod",quantile="0.9"} 16
kubelet_network_plugin_operations_latency_microseconds{operation_type="tear_down_pod",quantile="0.99"} 16
kubelet_network_plugin_operations_latency_microseconds_sum{operation_type="tear_down_pod"} 16
kubelet_network_plugin_operations_latency_microseconds_count{operation_type="tear_down_pod"} 1
```

**Comment by derekwaynecarr** [comment]
this would have been useful.

@jeremyeder -- can you start tracking this metric in your perf runs?

**Pull request merged**
