### PR TITLE
Update DefaultRESTMapper types

### PR DESCRIPTION
**Pull request by deads2k**
The last two commits are unique.  The rest are building up.

ref: https://github.com/kubernetes/kubernetes/issues/17216

@caesarxuchao @liggitt

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Is the 5th commit #17319? I guess you want me to review 4th and 6th?

**Comment by deads2k** [comment]
> Is the 5th commit #17319? I guess you want me to review 4th and 6th?

Yeah.  Hopefully the kube merge queue starts moving along soon :)

**Comment by deads2k** [comment]
rebased and made the order reversed again.

**Comment by caesarxuchao** [comment]
The last commit LGTM. You can apply the label when other dependencies are merged. Thanks.

**Comment by deads2k** [comment]
The only remaining dependency is https://github.com/kubernetes/kubernetes/pull/17319, the rest have merged.  Shall I tag this one and close https://github.com/kubernetes/kubernetes/pull/17319 to help our poor merge queue?

**Comment by caesarxuchao** [comment]
Sure. Thanks.

**Pull request merged**
