### PR TITLE
Collect l7 controller e2e logs

### PR DESCRIPTION
**Pull request by bprashanth**
https://github.com/kubernetes/kubernetes/pull/26048#issuecomment-222758050
I meant to check e2e output and see if the logs were being collected, but it merged before i could.

### CODE REVIEW

**Comment by spxtr** [comment]
LGTM

**Comment by bprashanth** [comment]
applying lgtm assuming Joe forgot

**Comment by bprashanth** [comment]
@k8s-oncall good candidate for hand merge, if required

**Comment by a-robinson** [comment]
@bprashanth - to confirm, glbc on the master logs to /var/log/glbc.log? I want to make sure GKE collects it as well

**Comment by bprashanth** [comment]
@a-robinson yes

**Pull request merged**
