### PR TITLE
Bump rkt stage1-fly to 1.18.0

### PR DESCRIPTION
**Pull request by mtaufen**
Bumps stage1-fly version.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35813)

### CODE REVIEW

**Comment by vishh** [comment]
lgtm

**Comment by jessfraz** [comment]
since this file doesn't exists on 1.4 i guess this is part of https://github.com/kubernetes/kubernetes/issues/35809 right?

**Comment by vishh** [comment]
@jessfraz Yeah. I will remove the milestone now.

**Comment by jessfraz** [comment]
thanks!

**Comment by mtaufen** [comment]
Looks like a ton of volume related failures in the e2e node tests.

**Comment by vishh** [comment]
@mtaufen Can you shepherd this PR through.

**Comment by mtaufen** [comment]
`I1028 12:56:47.622] mount: mount point /media/root/var/lib/kubelet/pods/6ca16626-9d42-11e6-a714-42010a800009/volumes/kubernetes.io~empty-dir/test-volume does not exist`

**Comment by mtaufen** [comment]
We decided to move to mounting everything under `/var/lib/kubelet` in this one, but something is still assuming `/media/root`. I will investigate.

**Comment by mtaufen** [comment]
Found it, `remote.go` needs a tweak, change on the way.

**Comment by mtaufen** [comment]
Should be fixed, theoretically. Waiting on tests to confirm.

**Comment by vishh** [comment]
Don't change these mounts in this PR. Just update the rkt version!

**Comment by mtaufen** [comment]
Ok, reverting both changes.

**Comment by mtaufen** [comment]
Now this *only* bumps the rkt version

**Pull request merged**
