### PR TITLE
Remove test/integration/* from hack/.golint_failures

### PR DESCRIPTION
**Pull request by emwalker**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fixes golint errors in several files under test/integration/.

**Which issue(s) this PR fixes**
See #68026 for more information.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ash2k** [comment]
ping @eparis for approval

**Comment by oomichi** [comment]
nice work,

/lgtm

**Comment by oomichi** [comment]
Oops, the commit 0e1d50e70fdc9ed838d75a7a1abbe5fa607d22a1 has added a new function DefaultOpenAPIConfig() which is against golint before merging this patch.
Could you take care of the function?

**Comment by oomichi** [comment]
/hold

for stopping unnecessary CI

**Comment by emwalker** [comment]
@oomichi — sure, I'll rebase and fix the golint error shortly.

**Comment by oomichi** [comment]
/hold cancel

Thanks

**Pull request merged**
