### PR TITLE
Remove conformance tag for internet connectivity

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

ICMP ping is not available in many environments, so we should avoid
using a e2e test based the premise as a conformance test.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
Part of Fix for #52098, Please see #51287 for more discussion

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
cc @bgrant0607 @liggitt

**Comment by bgrant0607** [comment]
Thanks.

This is necessary until we find a better solution.

/lgtm
/approve

**Comment by pires** [comment]
Actually, I think some people may want to run air-gapped Kubernetes clusters that run without any access to the Internet so it makes sense to me to permanently remove this from conformance tests.

**Comment by kevin-wangzefeng** [comment]
I think we also need to cherry pick this to 1.7.

**Comment by mjura** [comment]
@dims, @bgrant0607: can we backport this patch to 1.7 branch, please? we hit also this same issue

**Comment by dims** [comment]
@mjura @kevin-wangzefeng @bgrant0607 - Done!

**Pull request merged**
