### PR TITLE
fix golint errors in pkg/volume/*

### PR DESCRIPTION
**Pull request by mysunshine92**
**What this PR does / why we need it**:
fix golint for
pkg/volume/configmap
pkg/volume/cephfs
pkg/volume/secret/

some code fixed in 
pkg/volume/scaleio
pkg/volume/storageos

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
refer #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by idealhack** [comment]
@mysunshine92 It looks like you haven't rebased

**Comment by mysunshine92** [comment]
cc @idealhack

**Comment by idealhack** [comment]
you can run `./hack/update-gofmt.sh` and `make verify WHAT=typecheck` to fix things before push

**Comment by mysunshine92** [comment]
cc @gnufied @ivan4th need approved, lgtm labels，thank u

**Comment by mysunshine92** [comment]
/assign @zmerlynn 
would you like to help adding a approve label ? Thanks!

**Comment by nikhita** [comment]
/assign @cblecker 
for hack/ approval

**Pull request merged**
