### PR TITLE
chore: remove the redundant whitespce in the api.proto file

### PR DESCRIPTION
**Pull request by LinuxSuRen**
#### What type of PR is this?

/kind cleanup
/kind documentation

#### What this PR does / why we need it:
Clean the api.proto file style.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Review by aimuz — APPROVED** [review]

**Comment by bart0sh** [comment]
@LinuxSuRen Thank you for your PR. It seems to only contain trivial edits. Please
read [our trivial edits policy](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits). We encourage you to take a look at confirmed issues and bugs or issues marked help-wanted.

**Comment by LinuxSuRen** [comment]
hi @bart0sh Sure. Totally understand it. I didn't know the policy beore. I searched all the .proto files, only this one have the redundant whitespace. So, what's your suggestion? Close?

**Comment by bart0sh** [comment]
@LinuxSuRen Thank you for your understanding. My suggestion would be 'Close or extend'. Try to find more similar cases in the codebase and fix them if you want to proceed further.

**Comment by LinuxSuRen** [comment]
Got it. I'm going to close this for now until more work 
done.

**Pull request closed without merging**
