### PR TITLE
deprecated sets.String with sets.Set  kind/cleanup #113709

### PR DESCRIPTION
**Pull request by abhishekkhanna2710**
I have changed deprecated  sets.String with sets.Set Kindly plaese check and if there is any doubt you can tell me to fix it.

### CODE REVIEW

**Comment by alculquicondor** [comment]
Prefer to open multiple PRs targeting different SIGs, so it's easier to review among multiple reviewers.

**Comment by alculquicondor** [comment]
example: pkg/scheduler, pkg/controller, pkg/kubelet

**Comment by kerthcet** [comment]
Again, for sig-scheduling, we already have one settled. https://github.com/kubernetes/kubernetes/pull/113805

**Comment by bart0sh** [comment]
@abhishekkhanna2710 If you still need this PR then please rebase, if not, please close the PR

**Comment by dims** [comment]
Please remove merge commits, rebase and reopen this PR if necessary. It will not be merged as-is.

**Pull request closed without merging**
