### PR TITLE
Generate a better Stringer method for proto types

### LINKED ISSUE #28756: Stop using String() methods generated by protobuf
I don't believe we need them, and they actually make for worse output in many cases.

@wojtek-t fyi

### PR DESCRIPTION
**Pull request by smarterclayton**
This replaces the bad string output generated by golang/proto with gogo/protobuf stringer generation. Makes the output similar to %#v and more debuggable. We have to have a String() method to implement proto.Message, so this is strictly better.

@wojtek-t, @thockin for after your PR merges

Fixes #28756

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
We should remove do-not-merge lable when this will be ready for merge.

**Comment by wojtek-t** [comment]
@smarterclayton - can we merge it now?

**Comment by smarterclayton** [comment]
Rebasing

**Comment by smarterclayton** [comment]
Reapplying labels

**Comment by wojtek-t** [comment]
LGTM

**Comment by smarterclayton** [comment]
@k8s-bot test this issue #28411

**Pull request merged**
