### PR TITLE
docs(desired_state_of_world.go): log in desired_state_of_world.go seems to be wrong

### PR DESCRIPTION
**Pull request by KunWuLuan**
…ms to be wrong

#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:

wrong log makes debug harder.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by KunWuLuan** [comment]
Does this PR introduce a user-facing change?

None

/release-note-none

**Comment by pacoxu** [comment]
It seems to be a copy-and-paste typo.
https://github.com/kubernetes/kubernetes/blob/aea9f9887d08922378b9e7da0e81a46e733f2995/pkg/kubelet/pluginmanager/cache/actual_state_of_world.go#L94-L95

/lgtm
/priority backlog
/ok-to-test
/kind bug
/ok-to-test
/assign @saad-ali

**Comment by pacoxu** [comment]
> Fixes #

You may change the PR description to
```
Fixes #111753
```
Then the issue will be closed automatically once this pr is merged.

**Comment by KunWuLuan** [comment]
Fixes #111753

**Comment by derekwaynecarr** [comment]
agree it looks copy/paste from the peer file.

/approve
/lgtm

**Pull request merged**
