### PR TITLE
Build cache support into zsh completion

### LINKED ISSUE #82883: kubectl completion is too slow
**What happened**:

Kubectl shell completion might be depressingly slow.
Main problem that completion uses constructions like:

```
kubectl get -o template '--template={{ range .items  }}{{ .metadata.name }} {{ end }}' configmap
```

to get resource names. But in large installations they can be extremely slow.

**What you expected to happen**:

I expecting that completion will not download tens of megabytes for each `<TAB>` pressing and will work much faster, actually same speed which is need for getting all resources list.

**How to reproduce it (as minimally and precisely as possible)**:

For example if you use single helm tiller per cluster. And install ~200 releases. You can face with the next situation:

```bash
time kubectl get -n=kube-system -o template '--template={{ range .items  }}{{ .metadata.name }} {{ end }}' configmap > /dev/null

real    0m14.563s
user    0m9.625s
sys     0m1.257s
```

This is happening because of using template option will download all the resources body and then try parse it, but this is too a lot of information:

```bash
# kubectl get -n=kube-system -o json configmaps > /tmp/configmaps.yaml 
# du -hs /tmp/configmaps.yaml 
59M     /tmp/configmaps.yaml
```

You will face with the same problem if you have many pods:

```bash
# kubectl get pod -n kube-system | wc -l
1759

# kubectl get pod -n kube-system -o yaml > /tmp/pod.yaml
# du -hs /tmp/pod.yaml 
7.8M    /tmp/pod.yaml

# time kubectl get -n=kube-system -o template '--template={{ range .items  }}{{ .metadata.name }} {{ end }}' pod > /dev/null

real    0m4.018s
user    0m4.060s
sys     0m0.173s
```

**Anything else we need to know?**:

Simple solution for this issue is not using `-o template` for getting resource names.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: basremetal
- OS (e.g: `cat /etc/os-release`):
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```
- Kernel (e.g. `uname -a`):
```
Linux kvaps-laptop 5.2.9-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019 x86_64 GNU/Linux
```
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): bridget
- Others:

### PR DESCRIPTION
**Pull request by mikybars**
Kubernetes shell completion can be discouraging especially on medium to large clusters. Each `<TAB>` keypress triggers a new API request that can take hundreds of milliseconds. 

Zsh (as many shells) provides a cache mechanism that can improve dramatically the user experience in cases like this. With cache enabled, the first time you try to complete a resource you would wait for the request to finish as usual:

```bash
$ kubectl get pods co<TAB>
# after a while...
$ kubectl get pods command-
```
The difference now is that each subsequent `<TAB>` until you find the exact resource you're looking for has no cost. The results this time are fetched not from the server but from files that usually live under `~/.zcompcache`:

```
kubectl_pods_mynamespace1_mycluster1
kubectl_svc_mynamespace2_mycluster1
kubectl_deploy_mynamespace3_mycluster2
```
The cache validity interval can be customized by setting the variable `KUBECTL_COMPLETION_CACHE_INVALID_AFTER`:

```bash
export KUBECTL_COMPLETION_CACHE_INVALID_AFTER=1d
export KUBECTL_COMPLETION_CACHE_INVALID_AFTER=5h
export KUBECTL_COMPLETION_CACHE_INVALID_AFTER=15m  # default value
```
This value is meant to be tweaked according to the activity of your cluster.

Fixes #82883

### CODE REVIEW

**Comment by mperezi** [comment]
Registration done!

**Comment by kvaps** [comment]
Awesome! Thank you!

**Comment by mperezi** [comment]
That's odd because I do get completion working with `logs` and `describe`. Can you post your example?

**Comment by kvaps** [comment]
My bad, I don't know what exactly was wrong, but I've tried it second time, now it is fully working.

I'm not sure but I think that I were installing your patch on old completion version.

Now I just run:
```
kubectl completion zsh > ~/.oh-my-zsh/cache/kubectl_completion
curl https://patch-diff.githubusercontent.com/raw/kubernetes/kubernetes/pull/83879.diff | patch ~/.oh-my-zsh/cache/kubectl_completion
```
and everything is working

**Comment by kvaps** [comment]
Hi, there is one potential problem with using cache:

If you removed the pod, and then try to exec into new one, then zsh completion will continue showing old pod instead of new one.
Is there any idea how to solve that?

**Comment by mperezi** [comment]
Yes, that's a big issue with caches and cache invalidation. I don't see any clear solution to this except for tweaking the `KUBECTL_COMPLETION_CACHE_INVALID_AFTER` variable until you find a suitable value.

**Pull request closed without merging**
