### PR TITLE
Optimize SecurityContextDeny admission controller conditions

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
Optimization.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by php-coder** [comment]
I thought about refactor it by extracting methods: https://github.com/kubernetes/kubernetes/issues/43812 also there is a stale PR for that: https://github.com/kubernetes/kubernetes/pull/44089

**Comment by php-coder** [comment]
LGTM.

**Comment by xiangpengzhao** [comment]
@php-coder Thanks Vyacheslav for pointing it out. Will close this one.

**Comment by xiangpengzhao** [comment]
Seems like that what Nikita refactored in that PR is a bit complicated:)

**Comment by php-coder** [comment]
Yes, I agree: https://github.com/kubernetes/kubernetes/pull/44089/files#r109958930

**Comment by xiangpengzhao** [comment]
@php-coder let's wait for another refactoring by Nikita :)

**Pull request closed without merging**
