### PR TITLE
dra: PodScheduling -> PodSchedulingContext

### LINKED ISSUE #114283: dynamic resource allocation: rename PodScheduling
The name is not ideal. This already came up during the initial API review and again in https://github.com/kubernetes/enhancements/issues/3063#issuecomment-1336225191:

@sftim wrote:
> Pretty much everything that has a kind in Kubernetes looks broadly idiomatic if you put a definite or indefinite article in front of it. However, PodScheduling is a bit weird.
> 
> (Fictional) examples:
> 
>  -   “the driver watches for a PodScheduling that matches this driver's resource type”
>  -    “you can use the kubectl tool to manually delete the PodScheduling”
>  -    “the PodScheduling has an ownerReference to the Pod and is therefore a dependent object of that Pod”

My own proposal was `PodSchedulingState`.

@sftim had some more:

- PodSchedulingHint
- PodSchedulingReservation
- ProvisionalPodBinding

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup
/kind api-change

#### What this PR does / why we need it:

The name "PodScheduling" was unusual because in contrast to most other names,
it was impossible to put an article in front of it. Now PodSchedulingContext is
used instead.

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/114283

#### Special notes for your reviewer:

This replaces https://github.com/kubernetes/kubernetes/pull/116321.

#### Does this PR introduce a user-facing change?
```release-note
API: resource.k8s.io/v1alpha1.PodScheduling was renamed to resource.k8s.io/v1alpha2.PodSchedulingContext.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/3063
```

/assign @thockin

### CODE REVIEW

**Comment by pohly** [comment]
Only the last two commits are new. The first one comes from https://github.com/kubernetes/kubernetes/pull/116299.

**Comment by sftim** [comment]
Changelog tweak suggestion
```diff
-api: resource.k8s.io/v1alpha1.PodScheduling was renamed to resource.k8s.io/v1alpha2.PodSchedlingContext. This type is used internally, so no action is required.
+API: PodScheduling (from resource.k8s.io/v1alpha1) was renamed to PodSchedulingContext (resource.k8s.io/v1alpha2).
```
Do people who have existing PodSchedulings need to delete those before upgrade?

We should fix the typo in “PodSchedlingContext”, regardless.

**Comment by pohly** [comment]
> Do people who have existing PodSchedulings need to delete those before upgrade?

Yes, and we tell them to do that in https://github.com/kubernetes/kubernetes/pull/116299

We are spreading out the change over multiple PRs to simplify the review and merging.

> We should fix the typo in “PodSchedlingContext”, regardless.

Done. I still need to get my fingers used to it :sweat_smile:

**Comment by sftim** [comment]
After seeing the details of #116299, I still support removing:

> This type is used internally, so no action is required.

from the changelog for _this_ PR, as the changelog for #116299 is clear that action may well be required (by cluster operators who were already trying the alpha feature)

**Comment by pohly** [comment]
So we tell the user twice to delete PodScheduling? Sure, we can do that.

**Review by thockin — COMMENTED** [review]
I don't love context but I don't have a better (and non-"cute") name

/lgtm
/approve

**Comment by pohly** [comment]
> I don't love context but I don't have a better (and non-"cute") name

We should revert and bring back "kubectl get podschedulings" - not!

**Pull request merged**
