### PR TITLE
Automated cherry pick of #123562: Bump cel-go to v0.17.8 to pick up CEL estimated cost fix

### PR DESCRIPTION
**Pull request by liangyuanpeng**
Cherry pick of #123562 on release-1.29.

#123562: Bump cel-go to v0.17.8 to pick up CEL estimated cost fix

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by liangyuanpeng** [comment]
/assign @liggitt 
for  reviewer and approver of origin PR.

**Comment by liggitt** [comment]
is this resolving a regression or backporting a bugfix?

**Comment by liangyuanpeng** [comment]
> This is a somewhat rare edge case. I'd like to treat this as a bug and fix it and backport it.

As a bug, i'm happy to close it if we don't want it

**Comment by cici37** [comment]
/triage accepted
For context, it is to backport a long standing bug fix in cel-go 0.17.8.

**Comment by jpbetz** [comment]
Looking more closely at the backport criteria,let's not cherry pick this one. 1.30 will be available shortly

**Comment by liggitt** [comment]
> Looking more closely at the backport criteria,let's not cherry pick this one. 1.30 will be available shortly

thanks, I tend to agree

/close

**Pull request closed without merging**
