### PR TITLE
MESOS: Fix compilation of Mesos minion on Mac

### PR DESCRIPTION
**Pull request by sttts**
Fixes https://github.com/kubernetes/kubernetes/issues/13592

### CODE REVIEW

**Comment by sttts** [comment]
I remove the Pdeathsig which is not available on Mac. @jdef can you comment on the consequences? 

Of course, it's only on non-Linux, so probably will not be a problem on any production system.

**Comment by markturansky** [comment]
I checked out this branch and verified the fix.

**Comment by jdef** [comment]
Consequence is that on non-Linux systems if SIGTERM doesn't stop child
procs then they may "leak" and be reparented 'up the chain' somewhere when
the minion process terminates. For example, such child procs end up living
indefinitely as children of the mesos slave process (I think the slave
could handle this case, but currently doesn't do it very well). Pdeathsig
was a fallback/failsafe mechanism implemented to guard against this. I
don't know if OS X has any syscalls that do something similar.

Anyway, it might be worth leaving a comment along these lines in task_other
as part of this PR.

**Comment by markturansky** [comment]
@jdef In my case, tests wouldn't run because the mesos contrib package wasn't compiling.  I have no means of testing this issue more fully than that.

**Comment by jdef** [comment]
I added a comment in the PR. Should be good to do after passing CI

**Pull request merged**
