### PR TITLE
Remove myself from reviewers across the repo

### PR DESCRIPTION
**Pull request by roberthbailey**
So that PRs are no longer assigned to me by blunderbuss (which should improve the experience for contributors since I've been ignoring all k8s PRs for the last N months). 

Also move myself to be an emeritus approver for the cluster directory.

**What type of PR is this?**
/kind cleanup

**Does this PR introduce a user-facing change?**: No.

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**: _n/a_

/cc @justinsb (since I added you name to one of the files).

### CODE REVIEW

**Comment by liggitt** [comment]
/hold

per [release-managers discussion](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1567084773002200), holding low-priority, non-milestone-targeted PRs in order to free merge pool bandwidth for 1.16-targeted PRs

feel free to unhold once there are no [lgtm+approve+green 1.16-targeted PRs](https://github.com/kubernetes/kubernetes/pulls?utf8=✓&q=is%3Apr+is%3Aopen+label%3Algtm+label%3Aapproved+milestone%3Av1.16+status%3Asuccess) remaining.

**Comment by roberthbailey** [comment]
@lachie83 - any chance you could add the v1.16 milestone to my PR since it makes zero code changes and improves contributor experience (since their PRs will no longer be erroneously assigned to me)?

**Comment by roberthbailey** [comment]
Thanks!

**Pull request merged**
