### PR TITLE
Separate the build recipe in federation Makefile into separate phases.

### PR DESCRIPTION
**Pull request by madhusudancs**
This is based on PR #30744. Please review only the last commit here.

cc @kubernetes/sig-cluster-federation @colhom

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30745)

### CODE REVIEW

**Comment by quinton-hoole** [comment]
@madhusudancs This is still aimed at v1.4. right?  If so, and if @mml is not able to review today/tomorrow, then we need to find an alternative reviewer pronto.

**Comment by madhusudancs** [comment]
@quinton-hoole this PR is not strictly necessary for 1.4. This is just a Makefile change, so it's dev environment only. However, the PR that this depends on [PR #30744] is necessary for 1.4 for usability reasons we have discussed before.

**Comment by nikhiljindal** [comment]
LGTM, thanks!

Feel free to self apply the label once https://github.com/kubernetes/kubernetes/pull/30744 is merged and you have rebased.

**Comment by madhusudancs** [comment]
Thanks @nikhiljindal. Adding LGTM label now.

**Comment by madhusudancs** [comment]
@k8s-bot unit test this issue: #IGNORE

**Comment by madhusudancs** [comment]
@k8s-bot gce e2e test this

**Pull request merged**
