### PR TITLE
[Federation] Remove the pod informer from the ReplicaSet controller

### PR DESCRIPTION
**Pull request by perotinus**
Instead, get pods from the clusters directly if the ReplicaSet status implies a need to do so.

This should scale better than watching all pods in all joined clusters, and makes the ReplicaSet controller easier to refactor to use the shared sync controller.

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by perotinus** [comment]
cc @marun

**Comment by madhusudancs** [comment]
@k8s-bot ok to test

**Comment by marun** [comment]
Nice cleanup!  Would be good to see the tests passing before digging in further.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller.go, line 396 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKafI7O-GRZboKYV_M:-KjKafI7O-GRZboKYV_N:b-xxzlft) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/replicaset/replicasetcontroller.go#L396)):*
> ```Go
> 
> 	for _, clusterName := range clusterNames {
> 		lrsObj, exists, err := replicaSetGetter(clusterName, replicaSetKey)
> ```

is lrs intended to mean 'local replicaset'?  

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller.go, line 404 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKaVV5si8abFi1jFcn:-KjKaVV63Viq_lEZnWLz:b-h87sdp) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/replicaset/replicasetcontroller.go#L404)):*
> ```Go
> 		}
> 		lrs := lrsObj.(*extensionsv1.ReplicaSet)
> 		if int32(*lrs.Spec.Replicas) == lrs.Status.ReadyReplicas {
> ```

Why is the conversion to int32 but int64 on the line that follows?

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller.go, line 412 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKan8K11_9_qiWgzJi:-KjKan8K11_9_qiWgzJj:bo45y29) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/replicaset/replicasetcontroller.go#L412)):*
> ```Go
> 			}
> 			podStatus := podanalyzer.AnalyzePods(pods, time.Now())
> 			current[clusterName] = int64(podStatus.RunningAndReady) // include pending as well?
> ```

How did the previous code handle pending?

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller.go, line 415 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKb2fnOLlOjbTStDqI:-KjKb2fnOLlOjbTStDqJ:bujdgrp) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/replicaset/replicasetcontroller.go#L415)):*
> ```Go
> 			unschedulable := int64(podStatus.Unschedulable)
> 			if unschedulable > 0 {
> 				estimatedCapacity[clusterName] = int64(*lrs.Spec.Replicas) - unschedulable
> ```

Would it make sense to marshall replicas once?

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller.go, line 422 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKbJPeZ0eMgKU7yJT1:-KjKbJPeZ0eMgKU7yJT2:b-en8a9d) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/replicaset/replicasetcontroller.go#L422)):*
> ```Go
> }
> 
> type reconciliationStatus string
> ```

(No action required) Huh, yet another way to return status.   I guess I shouldn't be surprised that every controller does it differently.

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller.go, line 488 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKbijLmM-a_Wdr2tYL:-KjKbijLmM-a_Wdr2tYM:b-hl3mr5) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/replicaset/replicasetcontroller.go#L488)):*
> ```Go
> 		return statusError, err
> 	}
> 	var clusterNames []string
> ```

Consider breaking the entire block of scheduling code (including setup) into a separate function.

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller_test.go, line 188 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKcHTY_IVVXfuQKiT3:-KjKcHTY_IVVXfuQKiT4:b-tpfw0p) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/replicaset/replicasetcontroller_test.go#L188)):*
> ```Go
> }
> 
> func TestClusterReplicaState(t *testing.T) {
> ```

Would it be possible to refactor this test to be table-driven?   I think comments indicating what is being tested is usually a good indication of separable test cases.

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller_test.go, line 288 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKcrN7R83bholMV9K0:-KjKcrN7R83bholMV9K1:bbpv0lt) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/replicaset/replicasetcontroller_test.go#L288)):*
> ```Go
> }
> 
> func newPod(name string) *apiv1.Pod {
> ```

Can this module and pod_helper_test use a common function?

---

*[federation/pkg/federation-controller/util/podanalyzer/pod_helper.go, line 53 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKdEkPf9RpftxXwB_A:-KjKdEkPf9RpftxXwB_B:b-ih2lk8) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/util/podanalyzer/pod_helper.go#L53)):*
> ```Go
> 					result.RunningAndReady++
> 				}
> 			} else {
> ```

Consider simplifying this to ``else if``

---

*[federation/pkg/federation-controller/util/podanalyzer/pod_helper_test.go, line 94 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKdTYYbmCstfsI_JYq:-KjKdTYYbmCstfsI_JYr:b9s426v) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/util/podanalyzer/pod_helper_test.go#L94)):*
> ```Go
> 		ObjectMeta: metav1.ObjectMeta{
> 			Name:      name,
> 			Namespace: "default",
> ```

Consider using the metav1.NamespaceDefault constant as with ``replicasetcontroller_test.newPod``

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-:-KjKdmDZhgbamQiEMHh5:b814k10)*

**Comment by jianhuiz** [comment]
Is it possible to add unscheduled number (and maybe others needed) in replicaset status so that the list of the pods at the federation level is not required at all?

**Comment by perotinus** [comment]
It's probably possible, but I'd rather not make that change in this PR: what I have here is conceptually similar to what was there before, and I'd like to avoid having significant functional changes now. We can file an issue and think more about whether there are ways to change the ReplicaSet status for our needs, but that could be a long process.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller.go, line 396 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKafI7O-GRZboKYV_M:-KjejdzGcrahjxzpl9N6:bb77ufg) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/replicaset/replicasetcontroller.go#L396)):*
<details><summary><i>Previously, marun (Maru Newby) wrote…</i></summary><blockquote>

is lrs intended to mean 'local replicaset'?  
</blockquote></details>

Yes.

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller.go, line 404 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKaVV5si8abFi1jFcn:-KjejhkqFcvM17w7H1mW:b44d48w) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/replicaset/replicasetcontroller.go#L404)):*
<details><summary><i>Previously, marun (Maru Newby) wrote…</i></summary><blockquote>

Why is the conversion to int32 but int64 on the line that follows?
</blockquote></details>

No good reason. I've changed this so that ReadyReplicas is being converted both times, for conceptual consistency.

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller.go, line 412 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKan8K11_9_qiWgzJi:-KjejoPiLpkp80Z5ucTv:bu96z4q) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/replicaset/replicasetcontroller.go#L412)):*
<details><summary><i>Previously, marun (Maru Newby) wrote…</i></summary><blockquote>

How did the previous code handle pending?
</blockquote></details>

Exactly this way: this code is copied from the previous code.

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller.go, line 415 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKb2fnOLlOjbTStDqI:-Kjen9ZMkJLYV_YvL-Ti:b27ww4t) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/replicaset/replicasetcontroller.go#L415)):*
<details><summary><i>Previously, marun (Maru Newby) wrote…</i></summary><blockquote>

Would it make sense to marshall replicas once?
</blockquote></details>

I can buy that. Done.

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller.go, line 422 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKbJPeZ0eMgKU7yJT1:-KjekMDN_khfnn_NqiQj:b44bsks) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/replicaset/replicasetcontroller.go#L422)):*
<details><summary><i>Previously, marun (Maru Newby) wrote…</i></summary><blockquote>

(No action required) Huh, yet another way to return status.   I guess I shouldn't be surprised that every controller does it differently.
</blockquote></details>

Yeah. Hopefully this will be resolved soon enough.

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller.go, line 488 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKbijLmM-a_Wdr2tYL:-Kjeoi39MYBdARxRHQCS:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/replicaset/replicasetcontroller.go#L488)):*
<details><summary><i>Previously, marun (Maru Newby) wrote…</i></summary><blockquote>

Consider breaking the entire block of scheduling code (including setup) into a separate function.
</blockquote></details>

Done.

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller_test.go, line 188 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKcHTY_IVVXfuQKiT3:-Kjeoikxgoxmp3Boy-Pe:b-eb953a) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/replicaset/replicasetcontroller_test.go#L188)):*
<details><summary><i>Previously, marun (Maru Newby) wrote…</i></summary><blockquote>

Would it be possible to refactor this test to be table-driven?   I think comments indicating what is being tested is usually a good indication of separable test cases.
</blockquote></details>

Yes, that should be pretty straightforward.

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller_test.go, line 288 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKcrN7R83bholMV9K0:-KjiYKUjKdayvMlY53XG:bdnt0q5) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/replicaset/replicasetcontroller_test.go#L288)):*
<details><summary><i>Previously, marun (Maru Newby) wrote…</i></summary><blockquote>

Can this module and pod_helper_test use a common function?
</blockquote></details>

Hmm. They could, but I'm not sure that's more readable. Do you feel strongly about this? I'm inclined to prefer having the construction of the pods live in the test files, but I could be convinced that moving to federation-controller/util/test makes more sense.

---

*[federation/pkg/federation-controller/util/podanalyzer/pod_helper.go, line 53 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKdEkPf9RpftxXwB_A:-KjiYAXfCAKvQeaRrJQc:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/util/podanalyzer/pod_helper.go#L53)):*
<details><summary><i>Previously, marun (Maru Newby) wrote…</i></summary><blockquote>

Consider simplifying this to ``else if``
</blockquote></details>

Done.

---

*[federation/pkg/federation-controller/util/podanalyzer/pod_helper_test.go, line 94 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKdTYYbmCstfsI_JYq:-KjiYIvOKzJ_M8rBhznd:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/util/podanalyzer/pod_helper_test.go#L94)):*
<details><summary><i>Previously, marun (Maru Newby) wrote…</i></summary><blockquote>

Consider using the metav1.NamespaceDefault constant as with ``replicasetcontroller_test.newPod``
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-:-KjejIfXPfUTddqhKR5x:b-6gdi8m)*

**Comment by marun** [comment]
From a comment I left for #45563, I think you'll need to update the deployment controller in this PR to fix the build/test breakage, since it also relies on the pod helper that is changed here.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller.go, line 452 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-Kjn_qlnC9ZTVLAIiJMf:-Kjn_qlo9Mgs31bLJdqJ:bx2wjhj) ([raw file](https://github.com/kubernetes/kubernetes/blob/e751086df63b2263e4f525882963cba86c147cf6/federation/pkg/federation-controller/replicaset/replicasetcontroller.go#L452)):*
> ```Go
> 		return nil, err
> 	}
> 	return frsc.schedule(frs, clusterNames, current, estimatedCapacity), nil
> ```

I think this method is trying to do too much to allow for effective unit testing. Consider separate state determination from scheduling to limit the scope that a given test will need to consider.

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller_test.go, line 288 at r1](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-KjKcrN7R83bholMV9K0:-KjnaM9dL_XdPX__VPe_:b-jzipda) ([raw file](https://github.com/kubernetes/kubernetes/blob/3df1eedfc480ac2bb52effea1504bc489d2846b0/federation/pkg/federation-controller/replicaset/replicasetcontroller_test.go#L288)):*
<details><summary><i>Previously, perotinus (Jonathan MacMillan) wrote…</i></summary><blockquote>

Hmm. They could, but I'm not sure that's more readable. Do you feel strongly about this? I'm inclined to prefer having the construction of the pods live in the test files, but I could be convinced that moving to federation-controller/util/test makes more sense.
</blockquote></details>

I suspect helpers to create resources like pods are littered all over the codebase.  Ideally there would be one place to do it, but I'm not fixated on having you do that in this PR.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-:-KjnagnDVAoVJxwCkV5x:b19v1dw)*

**Comment by perotinus** [comment]
Hmm. I suppose that there's not really any harm in updating the deployment controller as well: if they work for ReplicaSets, they should work as well for deployments. Once the rest of this PR looks good, I'll migrate the changes to the deployment controller as well.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller.go, line 452 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-Kjn_qlnC9ZTVLAIiJMf:-KjoAv3kq0qykaPuxBPq:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/dbd2fd8252b6221cf7eb96a8b367279d386e8467/federation/pkg/federation-controller/replicaset/replicasetcontroller.go#L452)):*
<details><summary><i>Previously, marun (Maru Newby) wrote…</i></summary><blockquote>

I think this method is trying to do too much to allow for effective unit testing. Consider separate state determination from scheduling to limit the scope that a given test will need to consider.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-:-Kjo8viTLSVyT3jld8uU:b2ie2re)*

**Comment by marun** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller.go, line 452 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-Kjn_qlnC9ZTVLAIiJMf:-KjoODPc8X2UNz8ctHRd:b-kscy58) ([raw file](https://github.com/kubernetes/kubernetes/blob/dbd2fd8252b6221cf7eb96a8b367279d386e8467/federation/pkg/federation-controller/replicaset/replicasetcontroller.go#L452)):*
<details><summary><i>Previously, perotinus (Jonathan MacMillan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I see that you've split the code up, are you intending to do the same for the unit tests?

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252)*

**Comment by perotinus** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[federation/pkg/federation-controller/replicaset/replicasetcontroller.go, line 452 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252#-Kjn_qlnC9ZTVLAIiJMf:-KjteCLeHMuHTdQ5Y4uS:b-swriha) ([raw file](https://github.com/kubernetes/kubernetes/blob/dbd2fd8252b6221cf7eb96a8b367279d386e8467/federation/pkg/federation-controller/replicaset/replicasetcontroller.go#L452)):*
<details><summary><i>Previously, marun (Maru Newby) wrote…</i></summary><blockquote>

I see that you've split the code up, are you intending to do the same for the unit tests?
</blockquote></details>

I'm not sure: I could test calculateClusterCapacity, but I think it's really just scaffolding code for clustersReplicaState, and I'm not sure it's worth making its interface take several closures just so that we can test that it passes the right things to clustersReplicaState.

schedule is its own beast that we should test in a separate PR if we want tests for it.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/45252)*

**Comment by perotinus** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by marun** [comment]
So long as future PRs clean up the testing, I'm ok with this.  presubmit looks to be legitimately failing, though, holding off lgtm until it's passing.

**Comment by perotinus** [comment]
Yes, the presubmit failure is legitimate. I ran the tests locally with one cluster, and they passed; I'm running them again now with two clusters so I can debug.

**Comment by perotinus** [comment]
@k8s-bot test this

**Comment by perotinus** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by perotinus** [comment]
Given the impending submission of the ReplicaSet sync controller conversion and the fact that this PR fails inconsistently in CI, I'm closing.

**Pull request closed without merging**
