### PR TITLE
fix imported package names to not use under_scores

### LINKED ISSUE #15319: Fix imported package names to not use mixedCaps
Forked from #15200

@smarterclayton pointed out that all package names should be lower case, no under_scores or
mixedCaps. The same rule applies to renaming imported packages.
(https://blog.golang.org/package-names)

@timstclair generated a list of mixedCaps package names in our codebase: https://gist.github.com/timstclair/d63aac28d4201cf0c0f0

I will upload a PR later to rename kubeletTypes to kubetypes, and the rest is up for grabs.

### PR DESCRIPTION
**Pull request by mqliang**
This PR helps to fix https://github.com/kubernetes/kubernetes/issues/15319

### CODE REVIEW

**Comment by ashcrow** [comment]
nit: ```pkg_runtime``` :arrow_forward: ```pkgruntime``` makes a bit more sense to me. I assume the ```k``` is meant for kubernetes?

Looks good to me.

**Comment by brendandburns** [comment]
`kubeRuntime`?

although `kruntime` is fine with me too.

**Comment by mqliang** [comment]
@ashcrow 
@brendandburns 

If we want keep consistence with this file, it seems `kruntime` is better.
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/dns/kube2sky/kube2sky.go

**Comment by ashcrow** [comment]
@mqliang fair enough. Still looks good to me!

**Pull request merged**
