### PR TITLE
add unit test cases for kubelet.util.sliceutils

### LINKED ISSUE #47001: add unit test cases for kubelet.util.sliceutils

### PR DESCRIPTION
**Pull request by chentao1596**
What this PR does / why we need it:
I have not found any unit test case for this file, so i do it, thank you!

Fixes #47001

### CODE REVIEW

**Comment by Random-Liu** [comment]
@chentao1596 Thanks! Will review this soon.

**Comment by chentao1596** [comment]
@Random-Liu ok, thank you!

**Comment by derekwaynecarr** [comment]
@k8s-bot ok to test

**Comment by derekwaynecarr** [comment]
apologize for the delay getting to this pr.

the tests look generally pretty good to me.

/approve

**Comment by derekwaynecarr** [comment]
will tag when all things are green.

**Comment by chentao1596** [comment]
@derekwaynecarr Hi, i am sorry for this delay, all checks have been through, PTAL, thank you!

**Comment by resouer** [comment]
ping @derekwaynecarr, still need lgtm from you

**Comment by spiffxp** [comment]
/assign
I'll lgtm based on above comments

**Pull request merged**
