### PR TITLE
Use go1.8.1 for arm and ppc64le

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:
This PR is for moving from 1.8 rc2 version to 1.8.1 for cross compiling platform like ppc64le and arm.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Review by luxas — COMMENTED** [review]
LGTM

@ixdy please push the image

**Comment by ixdy** [comment]
/lgtm

@k8s-bot ok to test

**Comment by ixdy** [comment]
hm, I would've expected this to trigger cross-build too.
@k8s-bot build this

**Comment by ixdy** [comment]
@k8s-bot pull-kubernetes-cross test this

**Pull request merged**
