### PR TITLE
Remove duplicated ECDHE key handling

### PR DESCRIPTION
**Pull request by liggitt**
This PR removes the duplicated ECDHE private key handling. `x509.CreateCertificateRequest` picks the signature type for ECDHE keys already (see https://golang.org/src/crypto/x509/x509.go `signingParamsForPublicKey`). Only the RSA key signature needed customization.

It also defers to `CreateCertificateRequest` to return errors on unknown private key types.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32390)

### CODE REVIEW

**Comment by liggitt** [comment]
@gtank PTAL
cc @mikedanese @jayunit100

**Comment by jayunit100** [comment]
at first glance yes jason thanks, i think   this will fix the @kubernetes/sig-scheduling stress tests issues i was hitting.

**Comment by liggitt** [comment]
@gtank gentle bump

**Comment by mikedanese** [comment]
LGTM. What does this fix?

**Comment by liggitt** [comment]
rebased

**Comment by liggitt** [comment]
> What does this fix?

removes duplicated code that would require ongoing curve maintenance between golang releases, removes direct dependency on elliptic curves (some of which are not included in some distros' packaged golang installs)

**Pull request merged**
