### PR TITLE
Automated cherry pick of #76988: add shareName param in azure file storage class

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #76988 on release-1.13.

#76988: add shareName param in azure file storage class

### CODE REVIEW

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by tpepper** [comment]
I'm worried about the state of azure/storage patch backports. This one is at least smaller than the other size/xl one on the menu right now, but also feels feature-like.

But this one too was set to cherry pick to multiple branches 1.1[234] and is merged in master (1.15)  and 1.12, so it would be really odd to not merge in 1.13 and 1.14. :(

**Pull request merged**
