### PR TITLE
Automated cherry pick of #106657: Unversion and normalize openapi v3 fixtures

### PR DESCRIPTION
**Pull request by liggitt**
Cherry pick of #106657 on release-1.23.

#106657: Unversion and normalize openapi v3 fixtures

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
master PR merged

/hold cancel

**Comment by liggitt** [comment]
@kubernetes/release-managers

**Review by xmudrii — APPROVED** [review]
/lgtm
For RelEng:
/approve

**Comment by liggitt** [comment]
also needs the cherry-pick-approved label

**Comment by liggitt** [comment]
/hold cancel
jobs are live

**Comment by Jefftree** [comment]
LGTM as approver for original PR

**Comment by liggitt** [comment]
/hold

in favor of possible batch fast-forward of release-1.23 to master

**Pull request merged**
