### PR TITLE
Release 0.9.2

### PR DESCRIPTION
**Pull request by brendandburns**
@thockin

### CODE REVIEW

**Comment by thockin** [comment]
LGTM

**Comment by brendandburns** [comment]
Hang on don't merge...

**Comment by brendandburns** [comment]
Ok, this is ready to go.

**Comment by thockin** [comment]
You want an off-hours merge?  Can do if it lets you make progress.

**Comment by brendandburns** [comment]
not necessary, GKE isn't going to test it until tomorrow am anyway...

--brendan

**Comment by brendandburns** [comment]
Validated e2e passes.  This is good to merge tomorrow AM.

**Pull request merged**
