### PR TITLE
Make dockershim support kata-containers

### LINKED ISSUE #67007: Make dockershim support kata-containers
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
 At present, docker still the main and default container runtime engine for k8s, so I think making `dockershim` support `kata-containers` is very useful for the people of using secure containers. 

Now, kata-runtime have added support for dockershim pod annotations, see [dockershim/annotations.go](https://github.com/kata-containers/runtime/blob/master/virtcontainers/pkg/annotations/dockershim/annotations.go), 
and related PR have created in docker community, see: [moby/moby/pull/36181](https://github.com/moby/moby/pull/36181)

**What you expected to happen**:
Make dockershim support kata-containers

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by miaoyq**
**What this PR does / why we need it**:
This PR contains 3 commits
1. return IP info when setting up network
2. cache Pod IP
    Above two commits, mainly to obtain IP address of sandbox when cni pugin is called, and cache the sandbox IP locally. 

    Because the IP address that set by cni plugin will be removed from the veth device in network namespace by kata-runtime when creating the VM (in which containers will be created), if we use  `kata-containers` as the oci-runtime, This will cause dockershim to fail to get the pod IP through cni plugin.  Just like [this issue description](https://github.com/containerd/cri-containerd/issues/524) in `containerd/cri`. So, we should cache the pod IP.

3. make k8s(dockershim) to support selecting oci-runtime
    Add an annotation field in pod definition, so that dockershim can select the oci-runtime according to pod definition.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #67007

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by dixudx** [comment]
/kind node

@miaoyq Nice work!

**Comment by resouer** [comment]
Sorry, but I am not sure if we want to expand dockershim + Kata like this, as dockershim is not even a independent CRI shim, this is not align with RuntimeClass proposal https://github.com/kubernetes/kubernetes/pull/67049 we are trying to push recently.

Keeping dockershim as simple as the CRI shim for Docker, and use RuntimeClass to route request to another Kata shim (containerd, cri-o, frakti or DIY) sounds more reasonable to me.

**Comment by miaoyq** [comment]
@resouer Thanks for sharing the new feature. 
Make sense, but docker still the main and default container runtime engine for k8s at present, also if we switch to other runtime, there may be many incompatible scenarios. So I think, as a transition period, it is appropriate to support VM-Based oci-runtime in dockershim(only a few modifications). :-)

**Comment by xiangpengzhao** [comment]
I don't read through the RuntimeClass proposal. I'm not sure if there is still the issue this PR wants to fix even if we adopt RuntimeClass. If so, the fix is still needed :)
@kubernetes/sig-node-pr-reviews any thoughts?

**Comment by resouer** [comment]
> So I think, as a transition period, it is appropriate to support VM-Based oci-runtime in dockershim(only a few modifications). :-)

This actually concerns me. Personally, I don't think it's the right direction to use dockershim + Kata as I've mentioned, dockershim is not even a independent CRI implementation which is tightly coupled with kubelet code base, and shipping another temporary workaround will make this worse ...

Would like to know your thoughts, especially why not cri-containerd + Kata instead.

**Comment by yujuhong** [comment]
Making more changes to in-tree dockershim to support different types of runtimes defeats the purpose of creating CRI. I think in general, we should carefully examine new features being added to dockershim. In this case, I'd prefer not adding the support.

**Comment by tallclair** [comment]
Agree with @yujuhong . That said, we have discussed supporting [RuntimeClass](https://github.com/kubernetes/community/blob/master/keps/sig-node/0014-runtime-class.md) in dockershim.

**Comment by yujuhong** [comment]
RuntimeClass is a new api in kubernetes & CRI, which makes it very different from extending dockershim to support various runtimes that we don't even have tests for  :-)

**Comment by miaoyq** [comment]
> That said, we have discussed supporting RuntimeClass in dockershim.

@tallclair It's a good news.  That will do the same thing as this PR.
But if the runtimeHandler is VM-Based oci-runtime, we still need to cache the pod IP in dockershim.

**Pull request closed without merging**
