### PR TITLE
Revert CoreDNS to 1.3.1 in kube-up

### PR DESCRIPTION
**Pull request by rajansandeep**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Reverts CoreDNS to 1.3.1 for k8s 1.15
Reverts changes from https://github.com/kubernetes/kubernetes/pull/78030 and https://github.com/kubernetes/kubernetes/pull/78305

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Revert the CoreDNS version to 1.3.1
```

### CODE REVIEW

**Comment by mborsz** [comment]
/hold

Hi,
Could you say why are you reverting this? 
The upgrade to 1.5.0 is critical for keeping k8s 1.15 scalable. With 1.3.1 coredns is constantly OOMing in 5000-node scale after the cos upgrade to cos-beta-73-11647-64-0.

See https://github.com/kubernetes/kubernetes/issues/78562 and https://github.com/kubernetes/kubernetes/issues/76579#issuecomment-492982460 for context.

/cc @wojtek-t @mm4tt @oxddr

**Comment by chrisohaver** [comment]
@mborsz,

CoreDNS 1.5.0 is being reverted due to configuration migration troubles.  A non-trivial migration of the CoreDNS configuration is required between 1.3.1 and 1.5.0.  This migration step was not approved in kubeadm in 1.15 in time, so it is being reverted.   IMO, we should be testing the version of CoreDNS that will be used by most 1.15 deployments, which I think will be 1.3.1, since kubeadm will be installing that way.  Not everyone uses kubeadm I realize, but it is I think it is widely used as a reference.  Even if we upgrade to CoreDNS in the test framework to make tests pass, I think most people in the field will be using k8s 1.15 + CoreDNS 1.3.1, which potentially has this scaling issue.

Is the COS upgrade to the beta version critical? Can that be reverted?  Or would that cause more trouble (e.g. is it fixing other more important problems)?

If we leave the kube-up tests at CoreDNS 1.5.0, then I think CoreDNS 1.5.0 would be the "recommended" version of CoreDNS to use with K8s 1.15 (since that is what was tested).  Perhaps thats the easiest route.  Kubeadm would then need to release note that it doesn't upgrade to the version of CoreDNS recommended for 1.15 due to manual configuration migrations required (although it wont install a fresh build with 1.5.0 either).

**Review by chrisohaver — APPROVED** [review]
I think it's potentially problematic to release k8s using CoreDNS 1.3.1 for some tests (kubeadm cluster test), and 1.5.0 for another set of tests (kube up cluster tests).

Since we are reverting kubeadm back to 1.3.1, I think it makes sense to also revert kube-up.  If we dont, then kubeadm will be installing a version of CoreDNS that was not officially validated for 1.15 by e2e cluster tests (dns conformance, scalability, etc).  This would need to be release noted - but IMO better avoided if we can.

**Comment by mborsz** [comment]
I think keeping 1.5.0 in kube-up and saying that it's recommended version of coredns is a preferable solution -- it's already tested e2e.

If kubeadm doesn't support this setup, I think we should add release note about the fact that it's using the version that hasn't been tested for scalability.

**Comment by chrisohaver** [comment]
> I think keeping 1.5.0 in kube-up and saying that it's recommended version of coredns is a preferable solution -- it's already tested e2e.
> If kubeadm doesn't support this setup, I think we should add release note about the fact that it's using the version that hasn't been tested for scalability.

I think this is a bad idea because it would result in the majority of 1.15 users using 1.3.1, which has not tested well.

**Comment by mborsz** [comment]
> > I think keeping 1.5.0 in kube-up and saying that it's recommended version of coredns is a preferable solution -- it's already tested e2e.
> > If kubeadm doesn't support this setup, I think we should add release note about the fact that it's using the version that hasn't been tested for scalability.
> 
> I think this is a bad idea because it would result in the majority of 1.15 users using 1.3.1, which has not been tested in 1.15.
We only know that coredns 1.3.1 doesn't work well with cos version used in kube-up setup. We don't know what would happen in kubeadm clusters where IIUC we don't control OS running.

I agree that ideally kube-up and kubeadm should use the same coredns version, but on the other hand I don't think this is a big issue -- we don't test scalability of kubeadm clusters and given that we are doing some parameter tuning in kube-up scripts, I think it's safe to assume that kubeadm clusters will require manual work to make them scalable anyway.
Coredns upgrade is just another change that may be needed (or not; depending on the OS used on the nodes).

For me, this solution (using different coredns versions) is the easiest good enough solution, but if you disagree we can think about other options.

> 
> Edit: Ideally kubeadm would support coredns 1.5.0, but that is no longer happening in k8s 1.15.

**Comment by chrisohaver** [comment]
Being a CoreDNS maintainer, if we had known that the kubeadm PR to automatically upgrade to CoreDNS 1.5.0 would be rejected for k8s 1.15, we definitely would _not_ have upgraded the `/cluster` tests to use it.

> If kubeadm doesn't support this setup, I think we should add release note about the fact that it's using the version that hasn't been tested for scalability.

IIUC, _conformance_ tests have also not been tested for k8s 1.15 + coredns 1.3.1. The release note should disclose that. I would not expect to see any conformance failures for CoreDNS 1.3.1 on 1.15, since the same version was OK in 1.14, but I also would not have expected a scale failure for the same reason, and we did.

All that said, I _think_ CoreDNS 1.3.1 should work fine in 1.15 conformance wise.   **I'm OK with making CoreDNS 1.5.0 the "officially vetted" version for K8s 1.15, and releasing kubeadm with an unvetted/unofficial version of CoreDNS if everyone else is.**  I just want to make sure we are all waking into it with eyes open.  This certainly is the easier solution, for now.

**Comment by alejandrox1** [comment]
@rajansandeep @chrisohaver @mborsz will we continue with this PR instead of https://github.com/kubernetes/kubernetes/pull/78302 ? If so, to add it to the v1.15 milestone

**Comment by neolit123** [comment]
@chrisohaver 

> All that said, I think CoreDNS 1.3.1 should work fine in 1.15 conformance wise.

the conformance suite is already passing with 1.15 and coredns 1.3.1.

> I'm OK with making CoreDNS 1.5.0 the "officially vetted" version for K8s 1.15, and releasing kubeadm with an unvetted/unofficial version of CoreDNS if everyone else is. I just want to make sure we are all walking into it with eyes open. This certainly is the easier solution, for now.

kubeadm should release in 1.15 with 1.3.1 due to the complications we faced. the change to 1.5.x can still happen in 1.16 and this is planned.

kube-up requires a separate evaluation, but to my understanding the upgrade process from 1.3.1 -> 1.5.0 also had issues - thus this revert.

@mborsz

> For me, this solution (using different coredns versions) is the easiest good enough solution, but if you disagree we can think about other options.

separate versions for kubeadm and kube-up is fine.
a deployment can choose what version of an addon it installs, ideally we should sync them back for 1.16.

**Comment by chrisohaver** [comment]
> kube-up requires a separate evaluation, but to my understanding the upgrade process from 1.3.1 -> 1.5.0 also had issues - thus this revert.

The concerns there are that production kube-up users using the experimental upgrade script would lose custom configurations made to their Corefile.  We were operating under the understanding that kube-up is deprecated, not used in production capacity, and only in use by the e2e test infra.  This assumption however is now in doubt.

**Comment by liggitt** [comment]
Adding to the milestone for visibility until the discussion is resolved

/milestone v1.15

**Comment by mborsz** [comment]
> 
> kubeadm should release in 1.15 with 1.3.1 due to the complications we faced. the change to 1.5.x can still happen in 1.16 and this is planned.
> 
> kube-up requires a separate evaluation, but to my understanding the upgrade process from 1.3.1 -> 1.5.0 also had issues - thus this revert.
> 
That's a very good point. Do you know if anyone works on upgrade logic in kube-up? Is there such a logic?

If this problem is solved, I propose continuing with different coredns versions.

Otherwise we can try one of:
1. Increasing memory limit for coredns (the issue we were seeing is that in the new cos version, coredns memory increased and started OOMing, restarts of coredns were causing significant load on apiserver).
This would require more work to find a correct memory limit and see if such an increase is acceptable.

2. Rollback of cos version.
Personally I don't think it's a good option. The previous version is quite old, but @yguo0905 @yujuhong should be able to say more about this

**Comment by chrisohaver** [comment]
> That's a very good point. Do you know if anyone works on upgrade logic in kube-up? Is there such a logic?

There is an `upgrade.sh` script, that is labeled as "experimental" in /cluster. IIUC, it uses kube-up to do an upgrade. @rajansandeep can clarify/correct me if i'm wrong.

**Comment by chrisohaver** [comment]
Rehashing the current state of this...

* Upgrading kube-up to use CoreDNS 1.5.0 has caused several upgrade failures in e2e tests #78123.
* A fix for those failures (#78302) cannot be merged because it can cause a loss of user data in production clusters.
* I don't think we will be permitted at this stage in the release to develop, test and merge a lossless version of the upgrade fix.

Here are some options:
* **Stick with CoreDNS 1.5.0 and release k8s 1.15 with test still failing** in #78123. Assume this is not an option really, but listing it anyways.  We'd also need to warn users of /cluster/gce/upgrade.sh that manual migration of the CoreDNS Corefile may be required for CoreDNS to function after the upgrade.
* **Reverting the COS version bump and reverting to CoreDNS 1.3.1**.  I can't assess the feasibility of this.  The only thing I know about the new COS is that it is newer.
* **Bump up memory limits in CoreDNS 1.3.1**.  Proposed memory bumps to CoreDNS in the past have been rejected by the sig-scalability team.  So this is probably a no go.  Also, the increased memory usage in probably indicates another unidentified issue (hypothetically, it could be CoreDNS crashing due to trying to log an API error - a known issue in CoreDNS 1.3.1.  Furthermore, when CoreDNS restarts on a system with a very large number of endpoints, the API watch spikes memory (known issue with API watches).  So crashing and restarting in the middle of a scale test could cause subsequent OOM).
* **Stay with CoreDNS 1.5.0 in kube-up, merge the lossy upgrade fix #78302**, and warn people that upgrade.sh will automatically reset custom CoreDNS configurations.

**Comment by soggiest** [comment]
@kubernetes/sig-cluster-lifecycle Can someone provide some thoughts around this issue?

**Comment by neolit123** [comment]
@soggiest

> @kubernetes/sig-cluster-lifecycle Can someone provide some thoughts around this issue?

@chrisohaver just did. it's really up to the kube-up maintainers to make a decision.
my vote would be to apply this current PR.

**Comment by soggiest** [comment]
@spiffxp can you take a look at this and approve it if it's valid?

**Comment by spiffxp** [comment]
Thanks @chrisohaver for the summary.  When in doubt, I'm going to err on the side of user upgrade experience and suggest that we revert.  Going to read a bit more for context before making a call.

That said, in 1.11 [kubeadm switched to coredns](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.11.md#sig-cluster-lifecycle), while in 1.12 [kube-up still used kube-dns due to scalability concerns](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.12.md#known-issues), [finally switching in 1.13](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.13.md#sig-network)... so we have prior art for two different ways of standing up clusters using two different DNS implementations.

**Comment by spiffxp** [comment]
My opinion:
- code thaw is scheduled for Tue June 11th
- `cos-beta-73-11647-64-0` was introduced early March (https://github.com/kubernetes/kubernetes/pull/75149), we'd be in unknown territory if we rollback to `cos-stable-65-10323-64-0` this late
- we currently have an unacceptable upgrade path with `coredns 1.5.0`, and not enough time to reasonably develop an acceptable upgrade path, and so should revert to `coredns 1.13.1`, because user upgrade experience comes first
- this will result in `coredns` using more memory for reasons we don't yet know (https://github.com/kubernetes/kubernetes/issues/78562)
- this will cause the our 5000 node performance tests that use kube-up.sh to fail if they use the dns addon unmodified (https://github.com/kubernetes/kubernetes/issues/78562)
- in theory sig-scalability is supposed to report on the exact configuration they use to validate cluster performance (https://github.com/kubernetes/community/blob/master/sig-scalability/processes/scalability-validation.md#scalability-validation-of-the-release) though they have not done so since 1.9 (https://github.com/kubernetes/sig-release/issues/543)
- I think a good potential compromise would be to have scalability generate that report for 1.15, and include a non-default configuration of using coredns 1.15.0
- It's unclear to me whether kube-up.sh supports such a custom configuration, but I will start looking there (it supports using a custom COS image, but I don't think that would help us out here for the reason mentioned up top)

**Comment by jdumars** [comment]
@spiffxp this seems like a very reasonable path forward. I also agree that upgrade UX is the most high-impact aspect in play here.

**Comment by chrisohaver** [comment]
Sounds good to me.  Basically, rollback to CoreDNS 1.3.1, release k8s 1.15 with the failing 5k node test, and issue some kind of scaling exception notice advising use of coredns 1.5.0 for large clusters in the ballpark of 5K nodes.

Thanks @spiffxp!

**Comment by shyamjvs** [comment]
IIUC from above discussion, it seems like coredns 1.5.0 is having some correctness bugs but scalability improvements. We seem to have been using 1.3.1 even until 3 weeks ago (when it was bumped to 1.5.0 in https://github.com/kubernetes/kubernetes/pull/78030) and scalability tests were passing for last release where we were still using the old one (though IIRC we manually had to bump the resource requests). So if we're not at least regressing from last release wrt core-dns scalability, staying at old version to avoid correctness bugs seems better IMHO. I might be missing sth here.

@wojtek-t @mborsz - fyi

**Comment by jdumars** [comment]
Given release timing, is there a deadline for this decision?

**Comment by mborsz** [comment]
> IIUC from above discussion, it seems like coredns 1.5.0 is having some correctness bugs but scalability improvements. We seem to have been using 1.3.1 even until 3 weeks ago (when it was bumped to 1.5.0 in #78030) and scalability tests were passing for last release where we were still using the old one (though IIRC we manually had to bump the resource requests). So if we're not at least regressing from last release wrt core-dns scalability, staying at old version to avoid correctness bugs seems better IMHO. I might be missing sth here.
> 
> Wojciech Tyczynski Maciej Borsz - fyi

It's not really a full image.

http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=LoadRequestCountByClient&client=coredns%2Fv0.0.0%20(linux%2Famd64)%20kubernetes&code=200&component=apiserver&group=&resource=endpoints&scope=cluster&subresource=&verb=LIST&version=v1

shows number of LIST endpoints issued in load test which represents mostly number of coredns restarts.

There are 3 notable builds:
* 330 -- this is when cos version was bumped. The number of restart started being really high (300-1000 restarts). Debugging few runs after that has shown that it was OOMing mostly
* 1115162902861451269 -- the number of restarts has significantly decreased (to 5-20). I bet we already debugged this, but can't remember now what was the reason for decrease.
* 1120236390706057221 -- the number of restarts goes to zero -- this is because of https://github.com/kubernetes/kubernetes/pull/76819 got merged which basically removes the only dns client in scalability tests.

So the fact that in the test was passing before upgrading coredns to 1.5.0 was mostly because we removed the last dns client talking to it.

We see that in similar conditions (328 vs 330 builds) coredns 1.3.1 with newer cos is using more memory than before cos upgrade.

**Comment by mborsz** [comment]
I agree with @spiffxp suggestion.

We can also suggest increasing memory limit for coredns in big clusters (assuming the increase isn't that big). This seems to be more safe option than asking for coredns upgrade.

Just two concerns:
* We should make sure that it's possible to use custom coredns version if we are going to suggest doing so. I'm not aware of any knob that can be used in kube-up. Can we add something like that in 1.15?
* What we are doing here is moving the upgrade problem from all clusters to only big clusters. Given the current timeline this seems to be reasonable, but we still need to solve this issue somehow.

**Comment by mborsz** [comment]
https://github.com/kubernetes/kubernetes/pull/78851 adds a way to customize coredns version in kube-up scripts. Can we get merged in 1.15?

**Comment by alejandrox1** [comment]
Hi all, so what the plan?
will #78851 be merged/approved after this one?

**Comment by mborsz** [comment]
I suggest merging this one and then #78851.

**Comment by alejandrox1** [comment]
Awesome, thank you @mborsz !
Could we get an approval on this ?

**Comment by jdumars** [comment]
/lgtm
does someone want to remove the hold?  Or, I can.

**Pull request merged**
