### PR TITLE
Clean Godeps

### PR DESCRIPTION
**Pull request by eparis**
The eventual result of this series is that you can do

```
godep restore
rm -rf Godeps
godep save ./...
```

And get back what you started with. Every commit fixes some different problem.

67dbc4c is the most interesting. Its the only place I found where the code in Godeps/ was just plain not what was in Godeps.json.

### CODE REVIEW

**Comment by eparis** [comment]
@vmarmol (you did the one I think is bad)
@thockin @derekwaynecarr 

who is the mesos person?  I made a number of changes to their stuff, seems they did the most by hand...

**Comment by thockin** [comment]
@jdef @karlkfi for mesos

**Comment by thockin** [comment]
This looks OK, though it's not clear to me whether the fixes were automated or manual, and if manual, how do we ensure that new deps continue to work.

**Comment by eparis** [comment]
basically, I started trying to do exactly
```
mkdir /tmp/goroot
export GOPATH=/tmp/goroot
godep restore
rm -rf Godeps
godep save ./...
```

And then I, by hand, started looking at what was causing problems   :-(

We could pretty reasonable add this to a CI hook somewhere, but doing it on a per commit basis seems bad-ish...   Maybe just if a commit touched Godeps/

**Comment by jdef** [comment]
changes look ok to me

**Comment by derekwaynecarr** [comment]
lgtm

**Comment by derekwaynecarr** [comment]
+1 for a way to automate notifications for when it could godep restore gets upset in the future so we can be more proactive in not accumulating debt.

**Comment by alex-mohr** [comment]
label:lgtm on behalf of @derekwaynecarr

**Comment by alex-mohr** [comment]
@k8s-bot test this [testing build queue, sorry for the noise]

**Comment by alex-mohr** [comment]
@k8s-bot test this [deflake attempt]

**Comment by alex-mohr** [comment]
@k8s-bot test this [contrib/submit-queue: candidate for merging]

**Comment by alex-mohr** [comment]
Automatic merge from SubmitQueue

**Pull request merged**
