### PR TITLE
Add annotations to the PodSecurityPolicy Provider interface

### PR DESCRIPTION
**Pull request by timstclair**
@pweil- is this what you were thinking in terms of API changes? I really like to avoid functions with more than 2 return values, but couldn't think of a cleaner approach in this case.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30257)

### CODE REVIEW

**Comment by pweil-** [comment]
@timstclair yes, this is what I was thinking.  In my downstream implementation I did a copy of the annotations in the provider so it could be overwritten wholesale just like what's done for the security context.  Do you think there is value in that rather than a merge?  Perhaps if we ever have a use case where an annotation should be removed?  I can't think of an example.

**Comment by pweil-** [comment]
@pmorie thoughts on ^

**Comment by timstclair** [comment]
Yeah, that's the more general API -- I'll go with that.

**Comment by timstclair** [comment]
@pweil- friendly ping :)

**Comment by pweil-** [comment]
> @pweil- friendly ping :)

sorry, on PTO 😄 We should probably perform a copy in the provider and return the copy.  That way usage of the provider outside of admission still maintains the assumption that it will not modify the original values like we do with the SC.

Admission still needs to hang on to the original so it can apply the generated values (so that subsequent validations or container generations will be working on the latest and greatest), and rollback if necessary so I think that part is fine.

Other than that this LGTM.  WDYT? Nothing is using the provider outside of admission right now, just seems more reusable if we ever want to use the provider outside of admission.

**Comment by timstclair** [comment]
> on PTO 😄

Oh, np! I'll find someone else to review.

>  We should probably perform a copy in the provider and return the copy

My thought was that we should only perform the copy if we're actually modifying the annotations (for efficiency). I didn't do the copy here since this PR is just providing the API, and not actually touching the annotations.

**Comment by timstclair** [comment]
@erictune - Would you mind reviewing this since @pweil- is OOO?

**Comment by pweil-** [comment]
I'm ok with adding the copy when something actually starts changing
annotations. LGTM then.

**Comment by liggitt** [comment]
Spreading authz enforcement across two objects and returning a sometimes-copy seems dangerous to me

**Comment by timstclair** [comment]
@liggitt I hear you - I don't like returning multiple non-error values, but I don't see a great alternative. I suppose we could add a new method to the Provider interface for getting the Annotations, but it's not clear to me that that is any less error prone. Would you be more comfortable with always returning a copy, or do you have a better suggestion?

**Comment by timstclair** [comment]
This is currently blocking https://github.com/kubernetes/kubernetes/pull/30183, which needs to be merged by Friday for v1.4 feature-complete. Are there any outstanding concerns on this PR or can we move forward with it as-is?

**Comment by pweil-** [comment]
I think if this is updated to always return a copy of the annotations then @liggitt 's comment is satisfied?   I also think the multiple return values are the cleanest solution to having fields start off as annotations.

**Comment by timstclair** [comment]
Updated to always return a copy, squashed & rebased. PTAL.

**Comment by pweil-** [comment]
this LGTM

**Comment by dchen1107** [comment]
One of the verifications failed. Please fix it.

The pr lgtm. Feel free to apply the label once all checks passed.

**Comment by timstclair** [comment]
Done.

**Comment by timstclair** [comment]
Sorry, pushed to the wrong branch. Now done.

**Pull request merged**
