### PR TITLE
Prometheus/promdash replication controller

### PR DESCRIPTION
**Pull request by jayunit100**
Here is the replicatoinController implementation of the original pod for prometheus/promdash.

### CODE REVIEW

**Comment by tnguyen-rh** [comment]
It would be nice to see the YAML retained, IMHO.  Makes for a smaller diff, maybe.

**Comment by jayunit100** [comment]
@timothysc, heres the HA example with the service running.   
`kubectl create -f prometheus-all.json` and then `kubectl create -f prometheus-service.json` and then you can access everything via the service endpoint .


```
[jay@rhbd prometheus]$ wget 10.0.0.92:9090
--2015-05-19 18:55:31--  http://10.0.0.92:9090/
Connecting to 10.0.0.92:9090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2015-05-19 18:55:32--  (try: 2)  http://10.0.0.92:9090/
Connecting to 10.0.0.92:9090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2015-05-19 18:55:34--  (try: 3)  http://10.0.0.92:9090/
Connecting to 10.0.0.92:9090... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2015-05-19 18:55:37--  (try: 4)  http://10.0.0.92:9090/
Connecting to 10.0.0.92:9090... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2015-05-19 18:55:41--  (try: 5)  http://10.0.0.92:9090/
Connecting to 10.0.0.92:9090... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.1’

index.html.1                    [ <=>                                       ]   8.86K  --.-KB/s   in 0.001s 

2015-05-19 18:55:41 (9.52 MB/s) - ‘index.html.1’ saved [9075]
```

**Comment by yujuhong** [comment]
@jayunit100, could you suggest reviewers for this PR?

**Comment by jayunit100** [comment]
How about my buddy @zmerlynn .

Regarding the port to json:  The reason i ported it is that, simply, 
- YAML is more error prone than json (for me).  
- And regarding the diff - its bound to be pretty nasty since we're cleaning up the extra fields while also switching from pod to RC.
- @tnguyen-rh  i have an idea for you : in the next iteration: lets hide yaml and json from users : and  do something like `k8petstore.sh` which generates the files intermediately on the fly .

**Comment by tnguyen-rh** [comment]
Were this a serious concern, i would agree to the generative approach, but this is an example project, so IMHO it should be transparent and approachable by as wide an audience as possible.  Better to leave things out in the open, good, bad and/or ugly as they may be.  Any right-minded reader will obviously think along the lines you propose, anyway.  Let's just hope they do not fault us for thinking of the less-capable, as well.  (To preclude such noise, you can add a "exercise for the reader" blurb somewhere, perhaps.)

**Comment by jayunit100** [comment]
Okay, updated to use `publicIPs` so that graphing works properly.  Otherwise the web-root is all mucked up.  Also there is a prometheus `web-root` option that might be useful but that seems a little hacky
screenshot from 2015-05-20 10 35 00

**Comment by zmerlynn** [comment]
Agree with @tnguyen-rh. We've actually been preferring YAML - can we keep it here?

**Comment by jayunit100** [comment]
there are basically two reasons to use yaml.

1) yaml is preferred.  this is invalid, imo, here is why.
- right now, kubernetes supports fully **json** and **yaml**.  this is undisputed.
- kubernetes shouldn't, then, ever review a PR based on wether it is yaml or json - they are both first class citizens.
- more so - the best way to confirm json and yaml are at parity is by organically allowing developers to submit patches in either format which use the api liberally.  restricting this will inevitably lead to better support for one format than another.  

2) the original patch was yaml
- in this case - continuity is meaningless.  the original patch was not usable as a replication controller / introspective service and was just a placeholder to get the ball rolling. 

now, why did i pick json ?

not because i hate yaml , but just, because i think for complex applications, dealing with the idiosyncracies of yaml can be difficult for **some** teams.  my team (currently the ones maintaining this code), was able to get this working in json , but failed at getting it to work w/ yaml... and testing this is pretty nasty - as there is no 1-1 conversion as of yet.  

the long term solution ? 

im happy to standardize on Yaml, if and when either (1) kubernetes stops supporting json or (2) there is a conversion utility so that you dont have to rebuild a complex json kube application in yaml.  

personally... 

For me, right now, i have to look in `types.go` often, and grep around in the various examples/ snippets to get the right yaml syntax (which is highly variable), and so its quite tricky to get it right and do a full conversion.

either way, if you guys insist im happy to do it in YAML, but it will take some cycles to redo it again.  please do share your honest feedback on my argument and let me know the final decision. 

thanks for reading if you got this far :) :)

**Comment by tnguyen-rh** [comment]
I replied off-github w/ a json2yaml link (RH internal).
Probably it's a SMOP to put a GPLv3 on it and publish it to the world.
Let's see what the future holds.

**Comment by derekwaynecarr** [comment]
If you are comfortable with JSON, you can edit JSON and when you test it, just get the resource back in YAML from the server via kubectl get <resource> <name> -o yaml > file.yaml

Like you I sometimes struggle with YAML, but I find the ability to work in JSON and let server convert for me works well enough.

**Comment by jayunit100** [comment]
hi @zmerlynn .  Any final thoughts on this  ? 
If YAML is required to merge I'm happy to do it, just let me know :) !

ps thanks for the idea @derekwaynecarr .  based on zack's final feedback i  may need to use that trick.

**Comment by zmerlynn** [comment]
Sorry, been underwater. If it's easier for you to maintain in json right now, that's fine. 

LGTM

**Pull request merged**
