### PR TITLE
Automated cherry pick of #91835: Add csi-proxy installation into node setup script

### PR DESCRIPTION
**Pull request by jingxu97**
Cherry pick of #91835 on release-1.18.

#91835: Add csi-proxy installation into node setup script

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note
NONE
```

### CODE REVIEW

**Comment by jingxu97** [comment]
cc @YoubingLi @pjh

**Comment by jingxu97** [comment]
cc @ yujuhong

**Comment by jingxu97** [comment]
@pjh PTAL. thanks!

**Comment by pjh** [comment]
https://github.com/kubernetes/kubernetes/pull/91835/ has a bug that was fixed by https://github.com/kubernetes/kubernetes/pull/93789, right? Can we cherry-pick both at the same time to ensure we don't introduce that bug into this branch?

**Comment by jingxu97** [comment]
> 93789

good point. I created another one https://github.com/kubernetes/kubernetes/pull/94319 to replace this

**Pull request closed without merging**
