### PR TITLE
fix golint failures for some files under metrics k8s.io/metrics/pkg/apis

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This fixes golint failures for some files under `k8s.io/metrics/pkg/apis`.

ref: #68026

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by danielqsj** [comment]
`kind/api-change` should be removed.

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Comment by fejta** [comment]
/assign erictune lavalamp smarterclayton thockin liggitt
for metrics/pkg/apis/OWNERS approval

**Review by thockin — COMMENTED** [review]
/lgtm
/approve

**Comment by fejta** [comment]
/remove-kind api-change
/unassign erictune lavalamp smarterclayton liggitt
thanks Tim

**Pull request merged**
