### PR TITLE
Updating heapster to v0.16.1.

### PR DESCRIPTION
**Pull request by vishh**
@a-robinson: Can you validate heapster v0.16.1 once, before merging this PR?

### CODE REVIEW

**Comment by a-robinson** [comment]
@k8s-bot test this please

**Comment by a-robinson** [comment]
This looked significantly better for the first ~15 minutes I had it running. I was able to add new pods and have them monitored, delete them and have them garbage collected after around 5 minutes. I never saw endTimestamps more than 2 minutes old except when I'd just deleted a pod and they hadn't yet been GC'ed. I was also able to add a node and have it monitored

However, around 15 minutes in I tried deleting 2 of the 5 nodes in the instance group. Around this same time, heapster OOM'ed. After the OOM, it behaved wonkily for the next ~10 minutes. For the first 5-6 minutes after the restart, it served stale data that it had scraped just after restarting, even when it was 3-6 minutes old. Then for the next 4-5 minutes, it didn't return any data.

I doubt that this restart recovery behavior is a regression; it's probably broken in 0.16.0 as well (and likely 0.17.0). Because of that, I don't think that it should block using 0.16.1. However, we should try understanding why did it OOM so fast on such a small cluster? I only had 4 nodes (then 5, then 3 after the changes) and the system pods plus the guestbook-go pods. I'm giving @vishh access to the cluster.

**Comment by vishh** [comment]
I will look into the OOM issue. Since restarts are stateless, it seems
weird that the restart behavior was different.

**Comment by a-robinson** [comment]
Any idea yet whether the OOM is something we should be worried about here?

**Comment by vishh** [comment]
The memory limit as of now is set at 200MB. The average usage that I see is
around 150MB. I would suggest increasing the memory limit for heapster to
avoid OOMs.
I am digging deeper into memory usage of heapster now, to try and optimize
it further.

**Comment by a-robinson** [comment]
Ok, so you think we should merge this and also cherry-pick an increase of the memory limit?

**Comment by vishh** [comment]
yes.

**Pull request merged**
