### PR TITLE
available resources map make use of empty struct instead of bool as v…

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
…alue

**What this PR does / why we need it**:

Optimize ControllerContext.AvailableResources to reduce memory usage.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
kindly ping @mikedanese for review

**Review by ash2k — APPROVED** [review]
/lgtm

**Comment by hzxuzhonghu** [comment]
kindly ping @deads2k for approval

**Comment by deads2k** [comment]
I'm not worried about the extra space of a few bools.  I think this uglies up the code.

**Pull request closed without merging**
