### PR TITLE
Fix compile error on non-linux platform

### LINKED ISSUE #35252: kubernetes-cross-build: Does not compile on non-linux
Failed: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-cross-build/1164/

Run so broken it didn't make JUnit output!

### PR DESCRIPTION
**Pull request by feiskyer**
Fix #35252

cc/ @smarterclayton @spxtr

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35259)

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM merge when green

**Comment by feiskyer** [comment]
ping @smarterclayton

**Comment by smarterclayton** [comment]
Was merged yesterday in another PR

**Comment by smarterclayton** [comment]
Or not?  Hrm

**Comment by smarterclayton** [comment]
Weird

**Comment by sudhi-vm** [comment]
```
# k8s.io/kubernetes/pkg/util/mount
pkg/util/mount/mount.go:115: unknown Mounter field 'mounterRootfsPath' in struct literal
```

on Mac.

**Comment by smarterclayton** [comment]
@kubernetes/sig-testing can we add a Jenkins job or something to unit/integration that runs `GOOS=darwin go test -c ./pkg/... ./test/...` so we start catching these at merge time?

**Comment by fejta** [comment]
Sure send a PR that:

creates the job - https://github.com/kubernetes/test-infra/tree/master/jobs
adds it to jenkins - https://github.com/kubernetes/test-infra/blob/master/jenkins/job-configs/kubernetes-jenkins-pull/bootstrap-pull.yaml
defines how it triggers - https://github.com/kubernetes/test-infra/blob/master/prow/jobs.yaml

**Comment by smarterclayton** [comment]
Thanks.  Pengfei, is that something you might have time to set up (since
you and I always get broken on this stuff)? :)

**Comment by ixdy** [comment]
We already have a cross-build job. We just don't trigger it always.

**Comment by smarterclayton** [comment]
A really fast merge queue job would prevent lots of people having to fix
this *all* the time.  I think in the last month Mac users have had at least
one unit test broken for > 50% of the month.

**Comment by rmmh** [comment]
Based on [cross-build on testgrid](https://k8s-testgrid.appspot.com/misc#cross-build&width=5), just trying to cross-compile `k8s.io/kubernetes/pkg/util/mount` would have caught all the breakages in the last 2 weeks.

**Comment by smarterclayton** [comment]
test/e2e is also broken in release-1.4 on non linux right now (i didn't
have the energy to file the bug).

**Comment by ixdy** [comment]
@smarterclayton might be worth filing a bug, since https://k8s-testgrid.appspot.com/release-1.4-all#build-1.4 has been passing.

**Comment by feiskyer** [comment]
It seems the problem has been fixed in master. 

@fejta @smarterclayton @ixdy  Has someone started to add the jenkins job?

**Comment by fejta** [comment]
Not that I know of. The jenkins jobs are automatically created and deleted according to my above comment - https://github.com/kubernetes/kubernetes/pull/35259#issuecomment-256786616

**Pull request merged**
