### PR TITLE
Don't try executing bash variable in assignment.

### PR DESCRIPTION
**Pull request by Q-Lee**
``` release-note
* Use the release-note-* labels to set the release note state 
* Clear this block to use the PR title as the release note 
-OR-
* Enter your extended release note here
```

[Analytics]()

### CODE REVIEW

**Comment by Q-Lee** [comment]
This should fix the GCI problem from #26109 and #26159

**Comment by goltermann** [comment]
@k8s-oncall please merge this manually

**Comment by zmerlynn** [comment]
I'm just going to merge this. This is a clear GCI cluster bring-up issue.

**Comment by yujuhong** [comment]
Thanks for fixing this!

Another fix #26190 was uploaded and waiting to be merged by the oncall an hour before this PR. It might have saved everyone time if the oncall was involved in the decision of merging :-)

**Pull request merged**
