### PR TITLE
Improve negotiate media type

### PR DESCRIPTION
**Pull request by wojtek-t**
NegotiateOutputMediaType is responsible for ~3.5% of allocations in our scalability tests.
This PR significantly reduces number of allocations there.

Based on my simple benchmark:
- before:
```
BenchmarkNegotiateMediaTypeOptions-8   1000000      1197 ns/op     944 B/op      18 allocs/op
PASS
```
- after
```
BenchmarkNegotiateMediaTypeOptions-8   	 5000000	       383 ns/op	     128 B/op	       2 allocs/op
ASS
```

@munnerz - if the changes in autoneg dependency look reasonable to you, I will open a PR against your repo - just let me know.

/hold

### CODE REVIEW

**Comment by smarterclayton** [comment]
Looks fine to me, I saw this as well in benchmarks.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes-sigs/kind/pull/937

**Pull request merged**
