### PR TITLE
Add an event to pvc when node expand successfully

### LINKED ISSUE #84136: Kubelet did not send the pvc resize success events when expanding pvc (node expand) successfully
**What happened**:

Kubelet does send the pvc resize success events when expanding pvc (node expand)

**What you expected to happen**:

Kubelet sends the pvc resize success events when expanding pvc (node expand) successfully

**How to reproduce it (as minimally and precisely as possible)**:

1. CSI Plugin supports node expand
2. deploy the external-reszier(csi reszier)
3. deploy pvc pod
4. edit pvc
5. successfully expanded, but did not see the events

**Anything else we need to know?**:

**Environment**: 1.16.1
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

If we do not send the successful expansion event, it is hard to know the result. I think we should also send the event to pvc

**Which issue(s) this PR fixes**:

Fixes #84136

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by gnufied** [comment]
Can you confirm that you have tested it? Usually we don't use events for e2e, so I am not suggesting we write e2e for this but some basic verification will do.

**Comment by cwdsuzhou** [comment]
> Can you confirm that you have tested it? Usually we don't use events for e2e, so I am not suggesting we write e2e for this but some basic verification will do.

I confirm it. I found this when I developed a csi driver not e2e. The successful event would not send to pvc but to pod.

**Comment by cwdsuzhou** [comment]
When we using kubectl describe pvc, we can not see the successful expansion event, but we can the resizing event. So it is better add event to it when having expanded successfully.

**Review by yastij — COMMENTED** [review]
/lgtm

for the Events-side

**Pull request merged**
