### PR TITLE
Fix: Add toleration for calico-typha to allow scheduling on Azure spot nodes

### LINKED ISSUE #3539: [BUG] calico-typha cannot be scheduled on Spot VMs
**Describe the bug**
We have an aks cluster with 2 nodepools, one containing **Spot VM**s. We also have calico as NetworkPolicy enabled for our aks.

Aks tries to rollout the `calico-typha` deployment with 3 replicas in the `calico-system` namespace, which fails on the **Spot VM**s due to missing tolerations: `1 node(s) had untolerated taint {kubernetes.azure.com/scalesetpriority: spot}`

**To Reproduce**
1. Deploy an aks (1.24.9) with calico enabled
2. Create nodepool `Azure Spot Instance` feature enabled
3. See error

**Expected behavior**
Spot nodes should be tolerated.

**Screenshots**
image
image

**Environment (please complete the following information):**
 -  aks 1.24.9

### PR DESCRIPTION
**Pull request by dv0gt**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes https://github.com/Azure/AKS/issues/3539

#### Does this PR introduce a user-facing change?

```release-note
Typha pods are allowed to be scheduled on all kind of nodes (e.g. spot nodes).
```

### CODE REVIEW

**Comment by caseydavenport** [comment]
Hm, I wasn't aware that Azure was using these manifests for AKS.

**Comment by dv0gt** [comment]
> Hm, I wasn't aware that Azure was using these manifests for AKS.

Hey @caseydavenport,

I was a bit surprised as well, I opened a [PR](https://github.com/aks-lts/kubernetes/pull/1) in the [aks-lts repo](https://github.com/aks-lts/kubernetes), but they told me to do it here since this seems to be the upstream project for aks. See [this comment](https://github.com/aks-lts/kubernetes/pull/1#issuecomment-1550103094).

I think the toleration could be introduced in general, as it is in the [calico-node-daemonset.yaml](https://github.com/kubernetes/kubernetes/blob/cc131a6c2a4d7125e14018235f551133fe6686d0/cluster/addons/calico-policy-controller/calico-node-daemonset.yaml#LL182C17-L182C17) already.

What do you think?

**Comment by pacoxu** [comment]
https://github.com/projectcalico/calico/blob/e40707c5d30c353a78bed67a8c6596656b183121/manifests/calico-typha.yaml#L5058-L5106 

may need an update if this is  a general case.

**Comment by dv0gt** [comment]
> https://github.com/projectcalico/calico/blob/e40707c5d30c353a78bed67a8c6596656b183121/manifests/calico-typha.yaml#L5058-L5106
> 
> may need an update if this is a general case.

They seemed to update their code in the meantime, see https://github.com/projectcalico/calico/blob/master/manifests/calico-typha.yaml#L5169.

Will that be merged into the k8s policy controller manifests in this repository soon?

**Pull request closed without merging**
