### PR TITLE
Clean up fix for issue #22932 infinite pod restarts

### PR DESCRIPTION
**Pull request by dcbw**
This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/23069)

### CODE REVIEW

**Comment by dcbw** [comment]
@thockin the cleanup for https://github.com/kubernetes/kubernetes/pull/23050

**Comment by dcbw** [comment]
@thockin poke...  @bprashanth maybe you too, if you've got a few spare minutes

**Comment by dcbw** [comment]
@thockin poke... @bprashanth maybe you too, if you've got a few spare minutes

**Comment by dcbw** [comment]
@thockin @bprashanth @dchen1107 rebased, no other changes.  A review if anyone has time?

**Comment by bprashanth** [comment]
LGTM but tests are failing

**Comment by dchen1107** [comment]
The change looks good to me. Can you rebase?

**Comment by dcbw** [comment]
@dchen1107 rebased, PTAL thanks!

**Comment by dcbw** [comment]
@dchen1107 @bprashanth anyone have a chance to do a quick re-review + LGTM on the rebase?  Thanks!

**Comment by dcbw** [comment]
@k8s-bot test this issue: #25919

**Comment by dcbw** [comment]
@k8s-bot test this issue: #24905

**Comment by dcbw** [comment]
@dchen1107 @bprashanth rebased and passes tests, PTAL thanks!

**Comment by dcbw** [comment]
@dchen1107 any time to take a look at this small cleanup?  Thanks!

**Comment by dchen1107** [comment]
I believe this pr is not necessary anymore. Should we close this one? cc/ @freehan

**Comment by dcbw** [comment]
@dchen1107 I'll just close.

**Pull request closed without merging**
