### PR TITLE
Cherry pick #44744 on release-1.6

### PR DESCRIPTION
**Pull request by yguo0905**
**What this PR does / why we need it**:

Cherry pick of #44744 on release-1.6.

The changes need to cherry picked are relatively minimal so the risky is low. This allows us to run Ubuntu e2e tests against 1.6 branch.

**Special notes for your reviewer**:

**Release note**:

```
Support Ubuntu 16.04 image on GCE
```

### CODE REVIEW

**Comment by dchen1107** [comment]
Justification for cherrypick: 

*) The change is self-contained, and should only affect running K8S on GCE, not any other cloud providers. 
*) The change is minimal on GCE / GKE cloud provider. @kubernetes/ubuntu-image @roberthbailey @fabioy

**Comment by dchen1107** [comment]
LGTM but I will leave 1.6 release team to make the final decision on this.

**Comment by ethernetdan** [comment]
@yguo0905, what's the reasoning behind the GCI changes?

**Comment by yguo0905** [comment]
@ethernetdan, the change is required by Ubuntu but not GCI. However, since this change is a no-op in GCI, we just add it to GCI so that Ubuntu and GCI can share the same scripts for simplicity.

**Comment by calebamiles** [comment]
added to merge queue, @yguo0905.

**cc: @ethernetdan, @dchen1107, @kubernetes/kubernetes-release-managers**

**Pull request merged**
