### PR TITLE
update generated files

### PR DESCRIPTION
**Pull request by BenTheElder**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**: https://k8s-testgrid.appspot.com/sig-release-master-blocking#verify-master is red due to a missing codegen update

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig api-machinery
/priority critical-urgent

### CODE REVIEW

**Comment by BenTheElder** [comment]
/cc @cblecker @liggitt 
@cblecker is investigating why this wasn't caught in presubmit

**Comment by cblecker** [comment]
/hold
I'd rather get the presubmit testing fix in at the same time so that we can verify it works

**Comment by BenTheElder** [comment]
> I'd rather get the presubmit testing fix in at the same time so that we can verify it works

We can verify a presubmit fix by removing this file temporarily in the presubmit fix PR and seeing if it fails with the fix.

Presubmits are only going to test HEAD of the PR so you can't file that fix with this fix and verify anyhow.

**Comment by cblecker** [comment]
/hold cancel
Fix to presubmits: https://github.com/kubernetes/kubernetes/pull/80936

**Pull request merged**
