### PR TITLE
Update to repo-infra v0.0.4

### PR DESCRIPTION
**Pull request by fejta**
And use repo-infra to configure rules_go and rbe

/kind cleanup

```release-note
NONE
```

### CODE REVIEW

**Comment by justaugustus** [comment]
/hold
@fejta -- what does this mean for future Go updates?
cc: @markyjackson-taulia @Verolop @kubernetes/release-engineering

**Comment by fejta** [comment]
Nothing, the same rules, calls, etc are happening, just in a centralized location.

This should make it easier for the master branch to stay current with golang/bazel/etc updates. This is the pattern other repos use for their rules (test-infra, org, etc)

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by fejta** [comment]
Planning to merge this later today

**Pull request merged**
