### PR TITLE
Improve code coverage for pkg/kubelet/images/image_gc_manager

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:
#39559 #40780

code coverage from 74.5% to 77.4%

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by gyliu513** [comment]
Can you please update the summary of this PR, such as `pkg/kubelet/images/image_gc_manager` which may be more accurate, as this is just part of https://github.com/kubernetes/kubernetes/issues/40780

**Comment by gyliu513** [comment]
@k8s-bot ok to test

**Comment by gyliu513** [comment]
BTW: It would be great if you can clarify how much coverage was improved in your PR.

**Comment by zjj2wry** [comment]
@gyliu513 ok :)

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-e2e-kops-aws test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by dchen1107** [comment]
Submit queue redeployed. Now only allowing PRs with 1.7 milestone. Applying the milestone because this pr was lgtmed and approved before the deadline.

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
