### PR TITLE
Fixed detection of master during creation of multizone nodes cluster.

### PR DESCRIPTION
**Pull request by jszczepkowski**
```release-note
Fixed detection of master during creation of multizone nodes cluster by kube-up.
```

Fixed detection of master during creation of multizone nodes cluster by kube-up.

### CODE REVIEW

**Comment by jszczepkowski** [comment]
@k8s-bot cvm gce e2e test this
issue #38569

**Comment by jszczepkowski** [comment]
@k8s-bot cri e2e test this
issue #38569

**Comment by jszczepkowski** [comment]
Part of kubernetes/features#48

**Comment by saad-ali** [comment]
x-ref cherry picked in https://github.com/kubernetes/kubernetes/pull/38692

**Pull request merged**
