### PR TITLE
Revert "feat: cleanup pod critical pod annotations feature"

### PR DESCRIPTION
**Pull request by draveness**
/kind bug
/priority critical-urgent
/sig scheduling

**What this PR does / why we need it**:

Remove pod critical pod annotations cause regression for static pod.

**Which issue(s) this PR fixes**:

ref: #80203 #79548

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Revert "scheduler.alpha.kubernetes.io/critical-pod annotation is removed. Pod priority (spec.priorityClassName) should be used instead to mark pods as critical. Action required!"
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
/approve

Please strike the release note from the previous PR to avoid confusion

**Comment by draveness** [comment]
Thank you all for quick responding!

**Comment by draveness** [comment]
Rebased due to file `pkg/features/kube_features.go` conflicted with master.

**Pull request merged**
