### PR TITLE
Update basic example in client docs

### PR DESCRIPTION
**Pull request by errordeveloper**
This appeared to be out of date...

### CODE REVIEW

**Comment by deads2k** [comment]
You should take a look at `pkg/client/clientset_generated/release_1._2/typed/<package>` for external clients and the `internalclientset` for internal clients. 

We're generating those based on the API objects now.

**Comment by deads2k** [comment]
doc update lgtm.

**Comment by errordeveloper** [comment]
@deads2k that's good to know, that package needs more docs and probably some kind of a tutorial. Anyhow, I'll stick to `unversioned` for the time being...

**Comment by errordeveloper** [comment]
Jenkins seem to have failed, and the error doesn't seem to be related to this change, although I don't know what it does...

**Pull request merged**
