### PR TITLE
Record failure reasons for image pulling

### PR DESCRIPTION
**Pull request by yujuhong**

### CODE REVIEW

**Comment by yujuhong** [comment]
Hmm....okay. This needs more work. Don't review just yet.

**Comment by vmarmol** [comment]
lol, kk. Let me know

**Comment by yujuhong** [comment]
Ready for review finally :)

I think we can safely unexport RunContainer after this PR.

**Comment by vmarmol** [comment]
LGTM, thanks for adding a test!

**Comment by yujuhong** [comment]
An example of the output:
```
$ ./cluster/kubectl.sh get pods
POD       IP          CONTAINER(S)   IMAGE(S)    HOST                  LABELS    STATUS    CREATED          MESSAGE
foo       10.0.0.53                              127.0.0.1/127.0.0.1   <none>    Pending   About a minute   
                      bar1           fooimage1                                   Waiting                    Error: image library/fooimage1:latest not found
                      bar2           fooimage2                                   Waiting                    Error: image library/fooimage2:latest not found
```

```
./cluster/kubectl.sh describe pods foo
W0511 13:23:39.029576   13663 request.go:291] field selector: v1beta3 - events - involvedObject.namespace - default: need to check if this is versioned correctly.
W0511 13:23:39.029650   13663 request.go:291] field selector: v1beta3 - events - involvedObject.uid - 14feb2ff-f81b-11e4-b86a-c4346b658736: need to check if this is versioned correctly.
W0511 13:23:39.029664   13663 request.go:291] field selector: v1beta3 - events - involvedObject.name - foo: need to check if this is versioned correctly.
Name:				foo
Image(s):			fooimage1,fooimage2
Host:				127.0.0.1/127.0.0.1
Labels:				<none>
Status:				Pending
Replication Controllers:	<none>
Containers:
  bar1:
    Image:		fooimage1
    State:		Waiting
      Reason:		Error: image library/fooimage1:latest not found
    Ready:		False
    Restart Count:	0
  bar2:
    Image:		fooimage2
    State:		Waiting
      Reason:		Error: image library/fooimage2:latest not found
    Ready:		False
    Restart Count:	0
Conditions:
  Type		Status
  Ready 	False 
Events:
  FirstSeen				LastSeen			Count	From			SubobjectPath				Reason		Message
  Mon, 11 May 2015 13:19:52 -0700	Mon, 11 May 2015 13:19:52 -0700	1	{scheduler }							scheduled	Successfully assigned foo to 127.0.0.1
  Mon, 11 May 2015 13:19:52 -0700	Mon, 11 May 2015 13:19:52 -0700	1	{kubelet 127.0.0.1}	implicitly required container POD	pulled		Successfully pulled image "gcr.io/google_containers/pause:0.8.0"
  Mon, 11 May 2015 13:19:53 -0700	Mon, 11 May 2015 13:19:53 -0700	1	{kubelet 127.0.0.1}	implicitly required container POD	created		Created with docker id 9bcdcd2c4fd677a82cd4607aac2f325b090b9d69b9cd6f0da2ce560ec53d9b0a
  Mon, 11 May 2015 13:19:53 -0700	Mon, 11 May 2015 13:19:53 -0700	1	{kubelet 127.0.0.1}	implicitly required container POD	started		Started with docker id 9bcdcd2c4fd677a82cd4607aac2f325b090b9d69b9cd6f0da2ce560ec53d9b0a
  Mon, 11 May 2015 13:19:54 -0700	Mon, 11 May 2015 13:23:33 -0700	23	{kubelet 127.0.0.1}	spec.containers{bar1}			failed		Failed to pull image "fooimage1": Error: image library/fooimage1:latest not found
  Mon, 11 May 2015 13:19:55 -0700	Mon, 11 May 2015 13:23:34 -0700	23	{kubelet 127.0.0.1}	spec.containers{bar2}			failed		Failed to pull image "fooimage2": Error: image library/fooimage2:latest not found
```

**Pull request merged**
