### PR TITLE
add Unit Test for PodList Printer

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
Signed-off-by: zhangxiaoyu-zidif <zhang.xiaoyu33@zte.com.cn>

**What this PR does / why we need it**:
add Unit Test for PodList Printer

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by foxish** [comment]
@k8s-bot ok to test

**Comment by zhangxiaoyu-zidif** [comment]
ping @deads2k

**Comment by zhangxiaoyu-zidif** [comment]
ping @deads2k

**Comment by zhangxiaoyu-zidif** [comment]
ping @deads2k

**Comment by deads2k** [comment]
@fabianofranz do you want to try to enforce output stability like this?  Doesn't seem like it will play nice with server-side get in the long run.

**Comment by zhangxiaoyu-zidif** [comment]
@fabianofranz PTAL

**Comment by zhangxiaoyu-zidif** [comment]
@deads2k could you show me an example about "server-side get" to refer. I will be thankful. =)

**Comment by deads2k** [comment]
> @deads2k could you show me an example about "server-side get" to refer. I will be thankful. =)

https://github.com/kubernetes/community/blob/a5c36ce33262d7b77b18acf7c4048d0febc2c6c7/contributors/design-proposals/server-get.md

**Comment by fabianofranz** [comment]
@deads2k Yeah, won't play nicely with server-side get, but on the other hand we have already a number of places where we test the output like this, and I don't see client-side get going away anytime soon given client backwards compatibility. I'm ok with having this, sounds reasonable to you?

/approve

**Comment by deads2k** [comment]
> I'm ok with having this, sounds reasonable to you?

Sure.  I'll leave it with you.

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (185/150 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:54755)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-5c7e-dev=imwiz.com@sgmail.github.com>)
	id 1dGU9M-000RAD-9o
	for dev@imwiz.com; Thu, 01 Jun 2017 11:44:44 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=oxo60csGfAdcc4PGNtsredyRggA=; b=ayx0CNXm+26AGXTN
	NiLFgyv/kOdcTohu4snFsilP4pLcjVihyQat9j0XuMzhRmcFqguiU7qY0VTxFzxy
	fmnclSLf9VeOlUAADQGQMJGkdsUCSxt7iDdGOdzjcvJFcSX1EGVguvBnW/wZi0cp
	UhOAaw38lrdKBQGAuZVRAg/rY0w=
Received: by filter0533p1mdw1.sendgrid.net with SMTP id filter0533p1mdw1-8813-59305240-66
        2017-06-01 17:43:28.907667124 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id r443_7jhRgy313gq6q3e7A
	for <dev@imwiz.com>; Thu, 01 Jun 2017 17:43:28.837 +0000 (UTC)
Date: Thu, 01 Jun 2017 10:43:28 -0700

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-bazel test this
@k8s-bot pull-kubernetes-unit test this

**Comment by wojtek-t** [comment]
@k8s-bot pull-kubernetes-unit test this
@k8s-bot pull-kubernetes-bazel test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-bazel test this

**Comment by zhangxiaoyu-zidif** [comment]
Because of https://github.com/kubernetes/kubernetes/pull/40848, I refactor my PR.

**Comment by zhangxiaoyu-zidif** [comment]
Hi @fabianofranz , I need your lgtm label. Thanks.

**Comment by zhangxiaoyu-zidif** [comment]
Hi @fabianofranz , could you re-added the lgtm label? because I fix the PR since function interface changed.

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-unit test this

**Comment by zhangxiaoyu-zidif** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Pull request merged**
