### PR TITLE
Display config map data, not byte count.

### PR DESCRIPTION
**Pull request by brendandburns**
Begins to address https://github.com/kubernetes/kubernetes/issues/36222

Next step is:
`kubectl edit configmap <name> --key=<file-name>`

@kubernetes/sig-cli

### CODE REVIEW

**Comment by AdoHe** [comment]
LGTM.

**Comment by brendandburns** [comment]
@k8s-bot cvm gce e2e test this. issue: #27680

**Comment by soltysh** [comment]
LGTM as well.

**Comment by soltysh** [comment]
> Next step is:
> kubectl edit configmap <name> --key=<file-name>

@brendandburns see https://github.com/kubernetes/kubernetes/issues/37965 for some discussion in the topic.

**Pull request merged**
