### PR TITLE
Validation part 4

### PR DESCRIPTION
**Pull request by thockin**
Part 4 of several, builds on #17247

This is the big one.  Use a new FieldPath type to generate better/more consistent field names in errors.

@lavalamp

### CODE REVIEW

**Comment by thockin** [comment]
@k8s-bot unit test this please

@k8s-bot test this please

**Comment by thockin** [comment]
@k8s-bot unit test this please

**Comment by thockin** [comment]
This is rebased and ready for review (so are parts 5 and 6)

**Comment by thockin** [comment]
rebased again

**Comment by thockin** [comment]
@k8s-bot unit test this please

**Comment by lavalamp** [comment]
OK. So this is a huge change. Github won't even show me a diff for the main validation file, but looking at it, I saw at least one case in 20 seconds of skimming where the field path was not handled correctly, so presumably there are many such cases.

Presumably these are preexisting errors and we're comfortable leaving them in?

I think my idea of flipping it around (`fldPath.Child("operator").NewInvalidError(sr.Operator, "not a valid pod selector operator")`) would be a big readability/writeablity/maintenance win.

**Comment by lavalamp** [comment]
LGTM

**Comment by thockin** [comment]
rebased

**Comment by wojtek-t** [comment]
@thockin - needs rebase:

04:44:55 # k8s.io/kubernetes/pkg/api/validation
04:44:55 _output/dockerized/go/src/k8s.io/kubernetes/pkg/api/validation/events.go:30: cannot use "involvedObject.namespace" (type string) as type *validation.FieldPath in argument to validation.NewInvalidError

Can you please fix it?

**Comment by thockin** [comment]
rebased and fixed

**Pull request merged**
