### PR TITLE
Registering kube-proxy metrics on windows kernel mode

### LINKED ISSUE #106580: Windows Kube-Proxy metrics are not registered
### What happened?

`RegisterMetrics` function on `pkg/winkernel/metrics.go` is not being used, and kproxy metrics are not showing on endpoint.

### What did you expect to happen?

```
# HELP kubeproxy_sync_proxy_rules_duration_seconds [ALPHA] SyncProxyRules latency in seconds
# TYPE kubeproxy_sync_proxy_rules_duration_seconds histogram
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.001"} 1
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.002"} 1
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.004"} 1
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.008"} 1
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.016"} 19
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.032"} 30
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.064"} 32
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.128"} 36
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.256"} 36
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.512"} 36
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="1.024"} 37
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="2.048"} 37
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="4.096"} 37
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="8.192"} 37
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="16.384"} 37
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="+Inf"} 37
kubeproxy_sync_proxy_rules_duration_seconds_sum 1.5197857999999995
kubeproxy_sync_proxy_rules_duration_seconds_count 37
# HELP kubeproxy_sync_proxy_rules_last_timestamp_seconds [ALPHA] The last time proxy rules were successfully synced
# TYPE kubeproxy_sync_proxy_rules_last_timestamp_seconds gauge
kubeproxy_sync_proxy_rules_last_timestamp_seconds 1.6375262386492789e+09
```

See kube-proxy related metrics.

### How can we reproduce it (as minimally and precisely as possible)?

Access kube-proxy on `http://localhost:10249/metrics` and search for kube-proxy specific metrics.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

Kube-proxy build from master

```console
$ kube-proxy --version
Kubernetes v1.23.0-beta.0.69+ed07515ee01220-dirty
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by knabben**
1. Kube-proxy metrics are not registered, fixing on this PR for kernel mode.
2. Moving syncproxyrule gauge after exit due no endpoints checks. 
3. Reusing the `pkg/metrics` module metrics for DRY.
4. Increasing metrics coverage adding more gauges and counters:

```
    legacyregistry.MustRegister(SyncProxyRulesLatency)
    legacyregistry.MustRegister(SyncProxyRulesLastTimestamp)
    legacyregistry.MustRegister(EndpointChangesPending)
    legacyregistry.MustRegister(EndpointChangesTotal)
    legacyregistry.MustRegister(ServiceChangesPending)
    legacyregistry.MustRegister(ServiceChangesTotal)
    legacyregistry.MustRegister(SyncProxyRulesLastQueuedTimestamp)
```

#### What type of PR is this?
/sig windows
/sig network
/kind bug

#### Which issue(s) this PR fixes:

Fixes #106580

#### Special notes for your reviewer:

Metrics gathering after the change

```
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.001"} 0
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.002"} 0
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.004"} 0
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.008"} 0
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.016"} 0
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.032"} 0
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.064"} 0
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.128"} 0
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.256"} 0
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="0.512"} 0
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="1.024"} 1
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="2.048"} 1
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="4.096"} 1
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="8.192"} 1
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="16.384"} 1
kubeproxy_sync_proxy_rules_duration_seconds_bucket{le="+Inf"} 1
kubeproxy_sync_proxy_rules_duration_seconds_sum 0.6019167
kubeproxy_sync_proxy_rules_duration_seconds_count 1

# HELP kubeproxy_sync_proxy_rules_endpoint_changes_pending [ALPHA] Pending proxy rules Endpoint changes
# TYPE kubeproxy_sync_proxy_rules_endpoint_changes_pending gauge
kubeproxy_sync_proxy_rules_endpoint_changes_pending 0

# HELP kubeproxy_sync_proxy_rules_endpoint_changes_total [ALPHA] Cumulative proxy rules Endpoint changes
# TYPE kubeproxy_sync_proxy_rules_endpoint_changes_total counter
kkubeproxy_sync_proxy_rules_endpoint_changes_total 15

 # HELP kubeproxy_sync_proxy_rules_last_queued_timestamp_seconds [ALPHA] The last time a sync of proxy rules was queued
 # TYPE kubeproxy_sync_proxy_rules_last_queued_timestamp_seconds gauge
 kubeproxy_sync_proxy_rules_last_queued_timestamp_seconds 1.6375378693502028e+09

# HELP kubeproxy_sync_proxy_rules_last_timestamp_seconds [ALPHA] The last time proxy rules were successfully synced
# TYPE kubeproxy_sync_proxy_rules_last_timestamp_seconds gauge
kubeproxy_sync_proxy_rules_last_timestamp_seconds 1.6375378700543056e+09

# HELP kubeproxy_sync_proxy_rules_service_changes_pending [ALPHA] Pending proxy rules Service changes
 TYPE kubeproxy_sync_proxy_rules_service_changes_pending gauge
kubeproxy_sync_proxy_rules_service_changes_pending 0

# HELP kubeproxy_sync_proxy_rules_service_changes_total [ALPHA] Cumulative proxy rules Service changes
# TYPE kubeproxy_sync_proxy_rules_service_changes_total counter
kubeproxy_sync_proxy_rules_service_changes_total 15
```

#### Does this PR introduce a user-facing change?

```release-note
Publishing kube-proxy metrics for Windows kernel-mode
```

### CODE REVIEW

**Comment by aojea** [comment]
/lgtm
/approve
/hold
holding so windows folks can take a look, feel free to unhold
/assign @jsturtevant

**Comment by knabben** [comment]
failing due https://github.com/kubernetes/kubernetes/issues/106574

**Comment by jsturtevant** [comment]
windows issue should be resolved
/test pull-kubernetes-e2e-aks-engine-windows-containerd

**Comment by aojea** [comment]
/hold cancel
@jsturtevant for lgtm
Thanks

**Comment by jsturtevant** [comment]
Is this something we are trying to get in for 1.23 as it is a bug?  Are we past the point that this can go in?

**Comment by aojea** [comment]
> Is this something we are trying to get in for 1.23 as it is a bug? Are we past the point that this can go in?

I don't think this qualifies for milestone 1.23, but you can leave the lgtm and it will try to make its way once the gate open after the release

**Comment by jsturtevant** [comment]
/lgtm 

fyi @sbangari

**Comment by jsturtevant** [comment]
@knabben do you want to open backport prs for this?

**Pull request merged**
