### PR TITLE
Allow maxunavailable for a successful 

### PR DESCRIPTION
**Pull request by paulgmiller**
**What type of PR is this?**
 /kind feature

**What this PR does / why we need it**:
Allows rollout status to ignore maxunavailable failures to account 
**Which issue(s) this PR fixes**:
Haven't opened issue but can. 

**Special notes for your reviewer**:
I may be misreading nodeShouldRunDaemonPod . Maybe it is already smart enough to account for most not ready nodes and DesiredNumberScheduled  should just use shouldschedule rather than wanttorun from nodeShouldRunDaemonPod 

**Does this PR introduce a user-facing change?**:
```release-note
if max unavailable is set daemonset deployments that wouldn't have succeeded before would now. 
```

### CODE REVIEW

**Review by aixeshunter — APPROVED** [review]

**Comment by selfmanagingresource** [comment]
@janetkuo @kow3ns it seems like this is a change of contract in terms of what maxUnavailable means with DaemonSets and if we do something like this it should be changed in DaemonSets rather than kubectl. If we only change it in kubectl, different clients will then not have a shared notion of when a DaemonSet is complete. This actually seems related to  https://github.com/kubernetes-sigs/application/issues/78. However, there is really a clear way to get "Rollout Complete" status from DaemonSet currently.

**Review by soltysh — CHANGES_REQUESTED** [review]
/hold
I agree with what @selfmanagingresource is saying we can't break the contract just like that.

**Comment by soltysh** [comment]
@kubernetes/sig-apps-feature-requests fyi

**Review by kow3ns — COMMENTED** [review]
I do not think we can accept this contribution. It confuses what [max unavailable] (https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#max-unavailable) means. max unavailable is a knob that allows you to increased disruption for velocity. It was never intended to to indicate completeness. A rolling update is considered to be complete when all Nodes selected by the DameonSet have been updated to the new version. Blocking completion of the update due to troubled Nodes is intended behavior. Terminating early communicates to the user that all Nodes have been received an update when, in fact, some Nodes are at an inconsistent version and may never be updated.

**Comment by paulgmiller** [comment]
Thanks folks I'll close this out and take it up in deamonset controller. Thanks for the links

**Pull request closed without merging**
