### PR TITLE
[apimachinery]: cleanup deprecated const StatusTooManyRequests

### PR DESCRIPTION
**Pull request by ideapark**
`make all` goes happy

Signed-off-by: Zhou Peng <p@ctriple.cn>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> 
/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by yliaog** [comment]
/lgtm

please add release note label

**Comment by iobuf** [comment]
/assign @yliaog
kindly ping

**Comment by yliaog** [comment]
/assign @lavalamp 
for approval

**Comment by lavalamp** [comment]
/approve

(I don't see the harm in redeclaring, but since the value of this is rather unlikely to change, it's also not necessary)

**Pull request merged**
