### PR TITLE
Adding test-federation-cmd.sh for testing kubectl with federation-apiserver

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/kubernetes/kubernetes/issues/32826

This ensures that kubectl commands work as expected with federation-apiserver.

cc @kubernetes/sig-cluster-federation

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33414)

### CODE REVIEW

**Comment by quinton-hoole** [comment]
Can't we avoid all of the cut n paste here? Happy to do that in a separate
PR. By filtering the types down to those supported by federation, we should
be able to use the existing tests, after setting up the federation?

**Comment by nikhiljindal** [comment]
@quinton-hoole Yes I had thought about that. The advantage of the current setup is that federation and kube tests are independent of each other.
I can try refactoring the existing `test-cmd.sh` to run kubectl tests against both federation and kube-apiserver.

cc @kubernetes/sig-api-machinery.

**Comment by quinton-hoole** [comment]
@nikhiljindal Yes, I think that's a much better idea.  I'm concerned about the two sets of tests (federated and non-federated) diverging over time.  And every time a bug is found in them, it would have to be fixed in two places.  Or worse still, bugs that affect only one of those (federated or non-federated) get fixed in only that test and not the other, and over time the two API's are no longer compatible.

The benefit of having a single consistent set of tests seems to far outweigh the benefit of having independent tests, for the above reasons.  Agree?

**Comment by quinton-hoole** [comment]
ping @nikhiljindal

**Comment by dims** [comment]
@nikhiljindal do we still want to do this for v1.5? (if not, can we remove the milestone please?)

**Comment by nikhiljindal** [comment]
Removed from 1.5

**Comment by nikhiljindal** [comment]
Sent https://github.com/kubernetes/kubernetes/pull/38844 to reuse test cases with test-cmd.sh as suggested by @quinton-hoole

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/pull/38844 is now merged. Closing this

**Pull request closed without merging**
