### PR TITLE
kubeadm: fix minor typo in a comment

### PR DESCRIPTION
**Pull request by aerostitch**
Hi,

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

I just found a minor typo in a comment of a fine in kubeadm.

**Special notes for your reviewer**:

I looked at the rest of the file and didn't find any other ones.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

Thanks,
Joseph

### CODE REVIEW

**Comment by aerostitch** [comment]
As suggested by k8s-ci-robot:
/assign @rosti

**Review by neolit123 — COMMENTED** [review]
thanks for the PR, this will have to wait after the code freeze for 1.15 is lifted (11th of june)
/ok-to-test
/priority backlog

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

**Review by rosti — APPROVED** [review]
Thanks for the fix @aerostitch !
/approve

**Pull request merged**
