### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by KevinWang15**
/kind cleanup

Fix Typo: `masquared` -> `masquerade`
Fix Typo: `mataData` -> `metaData`

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
/priority backlog

@KevinWang15 Thanks for your first PR to Kubernetes! :tada: 

Can you squash the commits into a single commit?

**Comment by KevinWang15** [comment]
@nikhita Okay, I've squashed them into a single commit. Thank you!

**Comment by m1093782566** [comment]
/lgtm
/approve

THANKS!

**Pull request merged**
