### PR TITLE
Use framework.ConformanceIt for node e2e conformance tests

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
ref #54726 #53909

**Special notes for your reviewer**:
/cc @mml 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xiangpengzhao** [comment]
`pull-kubernetes-bazel-test` failed. @mml any thoughts? Thanks!

<details>

```
W1031 05:45:48.512] ____From Testing //test/conformance:conformance_test:
I1031 05:45:48.613] ==================== Test output for //test/conformance:conformance_test:
I1031 05:45:48.613] --- test/conformance/testdata/conformance.txt	2017-10-31 05:00:41.922880198 +0000
I1031 05:45:48.613] +++ test/conformance/conformance.txt	2017-10-31 05:45:46.967614739 +0000
I1031 05:45:48.613] @@ -148,20 +148,3 @@
I1031 05:45:48.614]  test/e2e/scheduling/predicates.go: "validates resource limits of pods that are allowed to run "
I1031 05:45:48.614]  test/e2e/scheduling/predicates.go: "validates that NodeSelector is respected if not matching "
I1031 05:45:48.614]  test/e2e/scheduling/predicates.go: "validates that NodeSelector is respected if matching "
I1031 05:45:48.614] -test/e2e_node/kubelet_test.go: "it should not write to root filesystem"
I1031 05:45:48.614] -test/e2e_node/kubelet_test.go: "it should print the output to logs"
I1031 05:45:48.615] -test/e2e_node/lifecycle_hook_test.go: "should execute poststart exec hook properly"
I1031 05:45:48.615] -test/e2e_node/lifecycle_hook_test.go: "should execute poststart http hook properly"
I1031 05:45:48.615] -test/e2e_node/lifecycle_hook_test.go: "should execute prestop exec hook properly"
I1031 05:45:48.615] -test/e2e_node/lifecycle_hook_test.go: "should execute prestop http hook properly"
I1031 05:45:48.616] -test/e2e_node/mirror_pod_test.go: "should be recreated when mirror pod forcibly deleted"
I1031 05:45:48.616] -test/e2e_node/mirror_pod_test.go: "should be recreated when mirror pod gracefully deleted"
I1031 05:45:48.616] -test/e2e_node/mirror_pod_test.go: "should be updated when static pod updated"
I1031 05:45:48.616] -test/e2e_node/runtime_conformance_test.go: "it should run with the expected status"
I1031 05:45:48.616] -test/e2e_node/runtime_conformance_test.go: "should be able to pull from private registry with credential provider"
I1031 05:45:48.617] -test/e2e_node/runtime_conformance_test.go: "should be able to pull from private registry with secret"
I1031 05:45:48.617] -test/e2e_node/runtime_conformance_test.go: "should be able to pull image from docker hub"
I1031 05:45:48.617] -test/e2e_node/runtime_conformance_test.go: "should be able to pull image from gcr.io"
I1031 05:45:48.617] -test/e2e_node/runtime_conformance_test.go: "should not be able to pull from private registry without secret"
I1031 05:45:48.618] -test/e2e_node/runtime_conformance_test.go: "should not be able to pull image from invalid registry"
I1031 05:45:48.618] -test/e2e_node/runtime_conformance_test.go: "should not be able to pull non-existing image from gcr.io"
I1031 05:45:48.618] ================================================================================
I1031 05:45:48.618] ==================== Test output for //test/conformance:conformance_test:
I1031 05:45:48.618] --- test/conformance/testdata/conformance.txt	2017-10-31 05:00:41.922880198 +0000
I1031 05:45:48.619] +++ test/conformance/conformance.txt	2017-10-31 05:45:46.967614739 +0000
I1031 05:45:48.619] @@ -148,20 +148,3 @@
I1031 05:45:48.619]  test/e2e/scheduling/predicates.go: "validates resource limits of pods that are allowed to run "
I1031 05:45:48.619]  test/e2e/scheduling/predicates.go: "validates that NodeSelector is respected if not matching "
I1031 05:45:48.620]  test/e2e/scheduling/predicates.go: "validates that NodeSelector is respected if matching "
I1031 05:45:48.620] -test/e2e_node/kubelet_test.go: "it should not write to root filesystem"
I1031 05:45:48.620] -test/e2e_node/kubelet_test.go: "it should print the output to logs"
I1031 05:45:48.620] -test/e2e_node/lifecycle_hook_test.go: "should execute poststart exec hook properly"
I1031 05:45:48.621] -test/e2e_node/lifecycle_hook_test.go: "should execute poststart http hook properly"
I1031 05:45:48.621] -test/e2e_node/lifecycle_hook_test.go: "should execute prestop exec hook properly"
I1031 05:45:48.621] -test/e2e_node/lifecycle_hook_test.go: "should execute prestop http hook properly"
I1031 05:45:48.621] -test/e2e_node/mirror_pod_test.go: "should be recreated when mirror pod forcibly deleted"
I1031 05:45:48.621] -test/e2e_node/mirror_pod_test.go: "should be recreated when mirror pod gracefully deleted"
I1031 05:45:48.622] -test/e2e_node/mirror_pod_test.go: "should be updated when static pod updated"
I1031 05:45:48.622] -test/e2e_node/runtime_conformance_test.go: "it should run with the expected status"
I1031 05:45:48.622] -test/e2e_node/runtime_conformance_test.go: "should be able to pull from private registry with credential provider"
I1031 05:45:48.622] -test/e2e_node/runtime_conformance_test.go: "should be able to pull from private registry with secret"
I1031 05:45:48.622] -test/e2e_node/runtime_conformance_test.go: "should be able to pull image from docker hub"
I1031 05:45:48.623] -test/e2e_node/runtime_conformance_test.go: "should be able to pull image from gcr.io"
I1031 05:45:48.623] -test/e2e_node/runtime_conformance_test.go: "should not be able to pull from private registry without secret"
I1031 05:45:48.623] -test/e2e_node/runtime_conformance_test.go: "should not be able to pull image from invalid registry"
I1031 05:45:48.623] -test/e2e_node/runtime_conformance_test.go: "should not be able to pull non-existing image from gcr.io"
I1031 05:45:48.624] ================================================================================
I1031 05:45:48.624] ==================== Test output for //test/conformance:conformance_test:
I1031 05:45:48.624] --- test/conformance/testdata/conformance.txt	2017-10-31 05:00:41.922880198 +0000
I1031 05:45:48.624] +++ test/conformance/conformance.txt	2017-10-31 05:45:46.967614739 +0000
I1031 05:45:48.624] @@ -148,20 +148,3 @@
I1031 05:45:48.625]  test/e2e/scheduling/predicates.go: "validates resource limits of pods that are allowed to run "
I1031 05:45:48.625]  test/e2e/scheduling/predicates.go: "validates that NodeSelector is respected if not matching "
I1031 05:45:48.625]  test/e2e/scheduling/predicates.go: "validates that NodeSelector is respected if matching "
I1031 05:45:48.625] -test/e2e_node/kubelet_test.go: "it should not write to root filesystem"
I1031 05:45:48.626] -test/e2e_node/kubelet_test.go: "it should print the output to logs"
I1031 05:45:48.626] -test/e2e_node/lifecycle_hook_test.go: "should execute poststart exec hook properly"
I1031 05:45:48.626] -test/e2e_node/lifecycle_hook_test.go: "should execute poststart http hook properly"
I1031 05:45:48.626] -test/e2e_node/lifecycle_hook_test.go: "should execute prestop exec hook properly"
I1031 05:45:48.626] -test/e2e_node/lifecycle_hook_test.go: "should execute prestop http hook properly"
I1031 05:45:48.627] -test/e2e_node/mirror_pod_test.go: "should be recreated when mirror pod forcibly deleted"
I1031 05:45:48.627] -test/e2e_node/mirror_pod_test.go: "should be recreated when mirror pod gracefully deleted"
I1031 05:45:48.627] -test/e2e_node/mirror_pod_test.go: "should be updated when static pod updated"
I1031 05:45:48.627] -test/e2e_node/runtime_conformance_test.go: "it should run with the expected status"
I1031 05:45:48.628] -test/e2e_node/runtime_conformance_test.go: "should be able to pull from private registry with credential provider"
I1031 05:45:48.628] -test/e2e_node/runtime_conformance_test.go: "should be able to pull from private registry with secret"
I1031 05:45:48.628] -test/e2e_node/runtime_conformance_test.go: "should be able to pull image from docker hub"
I1031 05:45:48.628] -test/e2e_node/runtime_conformance_test.go: "should be able to pull image from gcr.io"
I1031 05:45:48.628] -test/e2e_node/runtime_conformance_test.go: "should not be able to pull from private registry without secret"
I1031 05:45:48.629] -test/e2e_node/runtime_conformance_test.go: "should not be able to pull image from invalid registry"
I1031 05:45:48.629] -test/e2e_node/runtime_conformance_test.go: "should not be able to pull non-existing image from gcr.io"
I1031 05:45:48.629] ================================================================================

I1031 05:45:52.710] //test/conformance:conformance_test                                      FAILED in 3 out of 3 in 0.1s
```

</details>

**Comment by xiangpengzhao** [comment]
@mml I try to modify BUILD file as below, but it still doesn't work. Am I missing something? Thanks!

```
 genrule(
      name = "list_conformance_tests",
 -    srcs = ["//test/e2e:all-srcs"],
 +    srcs = [
 +        "//test/e2e:all-srcs",
 +        "//test/e2e_node:all-srcs",
 +    ],
      outs = ["conformance.txt"],
 -    cmd = "./$(location :conformance) $(locations //test/e2e:all-srcs) > $@",
 +    cmd = "./$(location :conformance) $(locations //test/e2e:all-srcs) $(locations //test/e2e_node:all-srcs) > $@",
      message = "Listing all conformance tests.",
      tools = [":conformance"],
  )
```

**Comment by mml** [comment]
@xiangpengzhao 

```
W1103 04:33:43.768] ERROR at test/e2e_node/runtime_conformance_test.go:316:29: framework.ConformanceIt() called with non-literal argument
```

You can test this yourself if you have bazel installed.  Just run `bazel test //test/conformance/...` and you should see an error like the above.

**Comment by xiangpengzhao** [comment]
@mml thanks! fixed. PTAL.

BTW, I guess there is possibly an issue with the ConformanceIt framework. I will track it by creating an issue.

**Review by mml — APPROVED** [review]
/lgtm

**Pull request merged**
