### PR TITLE
added possibility of memory consumption to  Dockerfile

### PR DESCRIPTION
**Pull request by socaa**
Part of #11570 

@piosz

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

**Comment by caesarxuchao** [comment]
@k8s-bot test this please

**Comment by wojtek-t** [comment]
@k8s-bot test this please

**Comment by caesarxuchao** [comment]
@k8s-bot test this please

**Comment by piosz** [comment]
@k8s-bot test this please

**Pull request merged**
