### PR TITLE
Jenkins: remove dead 'use server version' code

### PR DESCRIPTION
**Pull request by mbforbes**
This section of the code doesn't work with our GKE API change and isn't used by any Jenkins jobs (I audited all GKE ones). Removing it to avoid confusion and help code cleanliness before I add more GKE changes to the Jenkins config.

risk/impact: low

### CODE REVIEW

**Comment by mbforbes** [comment]
Likely reviewers: @quinton-hoole / @ixdy / @zmerlynn / @roberthbailey

**Comment by roberthbailey** [comment]
LGTM.

**Comment by quinton-hoole** [comment]
Assigning to @ixdy as a dry-run of my vacation, as agreed :-)

**Comment by ixdy** [comment]
Confirmed that this is not used by any Jenkins configurations:
```console
$ ls /var/lib/jenkins/*/jobs/config.xml | xargs grep JENKINS_USE_SERVER_VERSION
$
```

LGTM, ok to merge.

**Pull request merged**
