### PR TITLE
[1.16] CHANGELOG: Move changelogs into a subdir to delegate releng approvals

### PR DESCRIPTION
**Pull request by saschagrunert**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Analogous to https://github.com/kubernetes/kubernetes/pull/87879, we have to apply the changes to every supported release branch as well.

**Which issue(s) this PR fixes**:

Refers to https://github.com/kubernetes/kubernetes/pull/87879

**Special notes for your reviewer**:

None

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
/assign @liggitt @justaugustus
/cc @tpepper @hasheddan @evillgenius75 @JamesLaverack @puerco
cc: @kubernetes/release-engineering @kubernetes/release-team
/sig release
/area release-eng
/priority important-soon

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
Backported `OWNERS` and `OWNERS_ALIASES` from the master branch to align them with the release branch.

**Pull request merged**
