### PR TITLE
container_manager: use oomScoreAdj instead of default when set

### LINKED ISSUE #105820: kubelet resets its OOM score to -999 despite oomScoreAdj configuration value when running in a container
### What happened?

[Talos Linux](https://github.com/talos-systems/talos) runs `kubelet` in a container. Talos sets OOM score to -450 for the kubelet container and passes `oomScoreAdj: -450` in the kubelet config. 

End result is that `kubelet` OOM score adj is -999 though.

```
172.20.0.2: I1020 20:49:51.619550       1 container_manager_linux.go:929] "Attempting to apply oom_score_adj to process" oomScoreAdj=-999 pid=1
172.20.0.2: I1020 20:49:51.619561       1 oom_linux.go:65] attempting to set "/proc/1/oom_score_adj" to "-999"
```

### What did you expect to happen?

`kubelet` should have configured OOM score `-450`.

### How can we reproduce it (as minimally and precisely as possible)?

Source code analysis.

First, OOM score is set correctly from the config (flags):

https://github.com/kubernetes/kubernetes/blob/ae9ca48f01ddb03731e7903cfe91ef3db9ce8990/cmd/kubelet/app/server.go#L794-L797

But then, in container manager, OOM score is reset to -999 via the following:

https://github.com/kubernetes/kubernetes/blob/ae9ca48f01ddb03731e7903cfe91ef3db9ce8990/pkg/kubelet/cm/container_manager_linux.go#L538-L540

This function should skip action if the PID is not running on the host:

https://github.com/kubernetes/kubernetes/blob/ae9ca48f01ddb03731e7903cfe91ef3db9ce8990/pkg/kubelet/cm/container_manager_linux.go#L895-L903

But the function `isProcessRunningInHost` looks to be confusing:

https://github.com/kubernetes/kubernetes/blob/ae9ca48f01ddb03731e7903cfe91ef3db9ce8990/pkg/kubelet/cm/container_manager_linux.go#L808-L821

When kubelet runs in a container with PID namespace shared with the host, kubelet's PID namespace will be equal to PID 1 namespace. If kubelet runs in a container with unshared PID namespace, kubelet's PID is 1 and its PID namespace is identical to PID 1 namespace. So how this function can return `false` ever?

Moreover, function `ensureProcessInContainerWithOOMScore` is always setting OOM score to a hardcoded constant -999 ignoring configuation (`qos.KubeletOOMScoreAdj`).

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

`master`, reproduced with 1.22.
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by matthyx**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #105820

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/retest

**Review by endocrimes — APPROVED** [review]
/lgtm
/assign @derekwaynecarr

**Comment by matthyx** [comment]
@dims rebased!

**Comment by dims** [comment]
2 LGTM(s) from sig-node reviewers!

/approve
/lgtm

NOTE: this fixes the passing through of configuration from the command line to where it is needed. Some past refactoring seems to have dropped the option :(

**Pull request merged**
