### PR TITLE
Expose GET and PATCH for status subresource

### PR DESCRIPTION
**Pull request by caesarxuchao**
We can do this for other status subresource. I only updated node/status in this PR to unblock https://github.com/kubernetes/node-problem-detector/issues/9.

cc @Random-Liu @lavalamp

### CODE REVIEW

**Comment by smarterclayton** [comment]
```
package gopkg.in/yaml.v2: unrecognized import path "gopkg.in/yaml.v2" (https fetch: Get https://gopkg.in/yaml.v2?go-get=1: net/http: TLS handshake timeout)
```

**Comment by smarterclayton** [comment]
@k8s-bot test this issue #IGNORE (github was briefly down)

**Comment by smarterclayton** [comment]
I'm a little disappointed that the logic for PATCH requires GET on the subresource, but it's acceptable and not crazy.

**Comment by caesarxuchao** [comment]
@smarterclayton I updated the PR to include all the status subresource, does it still look good?

**Comment by smarterclayton** [comment]
Yes, @liggitt so you're aware.  I think status should support PATCH and your recent changes make me less worried than before.

**Comment by liggitt** [comment]
Patch doesn't require Get any more. I just didn't change the signature of the Patcher yet.

**Comment by liggitt** [comment]
I wasn't sure if we wanted to support patch on all of the resources that would suddenly get it if we removed GET from the interface requirements

**Comment by Random-Liu** [comment]
@caesarxuchao Thanks a lot for your help!! :)

**Comment by smarterclayton** [comment]
I don't think get is unnatural on status, but I could buy the argument
we want to be careful about adding it if we could avoid it.

I guess you could make the argument that it's one more thing that you
need to remember to deny access to if you don't want users to see it,
but that's a general argument against subresources

**Comment by caesarxuchao** [comment]
> I wasn't sure if we wanted to support patch on all of the resources that would suddenly get it if we removed GET from the interface requirements

Such resources must have already supported Update. I think it's nature to support Patch if Update is supported.

**Comment by liggitt** [comment]
I think I agree, but wanted to think about it a little more before blanketly enabling it

**Comment by Random-Liu** [comment]
Can we prioritize this a bit? Because https://github.com/kubernetes/node-problem-detector/issues/9 relies on this. :)

**Comment by dchen1107** [comment]
Marked this as P1 to unblock NodeProblemDetector work.

**Comment by Random-Liu** [comment]
@dchen1107 Thanks a lot! :)

**Comment by lavalamp** [comment]
Thanks for the quick fix, Chao!

**Pull request merged**
