### PR TITLE
remove baseline pod security in host pid sharing testing

### LINKED ISSUE #109096: E2eNode Suite: [sig-node] Security Context when creating a pod in the host PID namespace should show its pid in the host PID namespace [NodeFeature:HostAccess]
### Which jobs are failing?

https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-features

### Which tests are failing?

- E2eNode Suite: [sig-node] Security Context when creating a pod in the host PID namespace should show its pid in the host PID namespace [NodeFeature:HostAccess] expand_less 

```
{ Failure test/e2e_node/security_context_test.go:136
Error creating Pod
Unexpected error:
    <*errors.StatusError | 0xc000dc6aa0>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "pods \"nginx-hostpid-a497a22b-e503-41cd-8e45-da07c7563fbb\" is forbidden: violates PodSecurity \"baseline:latest\": host namespaces (hostPID=true)",
            Reason: "Forbidden",
            Details: {
                Name: "nginx-hostpid-a497a22b-e503-41cd-8e45-da07c7563fbb",
                Group: "",
                Kind: "pods",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 403,
        },
    }
    pods "nginx-hostpid-a497a22b-e503-41cd-8e45-da07c7563fbb" is forbidden: violates PodSecurity "baseline:latest": host namespaces (hostPID=true)
occurred
test/e2e/framework/pods.go:99}
```

### Since when has it been failing?

since last night.

### Testgrid link

https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-features

### Reason for failure (if possible)

https://github.com/kubernetes/kubernetes/pull/106454 

### Anything else we need to know?

NA

### Relevant SIG(s)

/sig auth node

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?

/kind failing-test

#### Which issue(s) this PR fixes:
Fixes #109096

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Comment by pacoxu** [comment]
/cc @s-urbaniak @liggitt
for https://github.com/kubernetes/kubernetes/pull/106454. (The failing seems to be after the pr merging)

**Review by ehashman — COMMENTED** [review]
/lgtm
/priority important-soon
/triage accepted

**Pull request merged**
