### PR TITLE
Cleanup SetPredicatesOrderingDuringTest due to deprecation of predicates

### PR DESCRIPTION
**Pull request by Huang-Wei**
/kind cleanup
/sig scheduling

Part of #86712

```release-note
NONE
```

/cc @ahg-g

### CODE REVIEW

**Comment by ahg-g** [comment]
Thanks, we should also move (predicatesOrdering)[https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/predicates.go#L103] to [legacy_registry](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/legacy_registry.go)

**Comment by Huang-Wei** [comment]
> Thanks, we should also move [predicatesOrdering](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/predicates.go#L103) to [legacy_registry](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/legacy_registry.go)

SG, so we are more close to eliminating the dependency on `predicates` package.

**Comment by ahg-g** [comment]
> > Thanks, we should also move [predicatesOrdering](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/predicates.go#L103) to [legacy_registry](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/legacy_registry.go)
> 
> SG, so we are more close to eliminating the dependency on `predicates` package.

indeed, can you please refer to #86712 instead of the umbrella issue?

**Comment by Huang-Wei** [comment]
> indeed, can you please refer to #86712 instead of the umbrella issue?

Done.

**Pull request merged**
