### PR TITLE
nodes: record an event on NodeReady changes

### PR DESCRIPTION
**Pull request by simon3z**

### CODE REVIEW

**Comment by simon3z** [comment]
@vmarmol this is somewhat similar to https://github.com/GoogleCloudPlatform/kubernetes/pull/6069 let me know if you have time to review it. Thanks!

**Comment by vmarmol** [comment]
LGTM, will merge on green.

**Comment by simon3z** [comment]
@vmarmol is there anyone that we should consult on the online/offline names? For me that will become an API (handle online/offline events)

**Comment by vmarmol** [comment]
Spoke offline with @bgrant0607, the name is fine. Although in general we discourage the use of events for any API. They're more meant for debugging and trace-ability. Is there some API you're planning to integrate this into?

Which also may be the reason why we don't have atomicity there.

**Comment by simon3z** [comment]
@vmarmol yes we're planning to give the ability to plug "automations" on these events.

**Pull request merged**
