### PR TITLE
Version bump to etcd v3.2.13, grpc v1.7.5

### LINKED ISSUE #51099: gRPC update causing failure of API calls with large responses
For e.g the density test started failing on all our kubemark jobs that are big (i.e on >= 100 nodes):
- https://k8s-testgrid.appspot.com/sig-scalability#kubemark-100
- https://k8s-testgrid.appspot.com/sig-scalability#kubemark-500

And it clearly seems to be a regression caused by this PR (from the diff) - https://github.com/kubernetes/kubernetes/pull/50531 - which updated gRPC vendor code. The error we're seeing is the following:

```
Expected error:
    <*errors.StatusError | 0xc42d8c0900>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "rpc error: code = ResourceExhausted desc = grpc: received message larger than max (26710706 vs. 4194304)",
            Reason: "",
            Details: nil,
            Code: 500,
        },
    }
    rpc error: code = ResourceExhausted desc = grpc: received message larger than max (26710706 vs. 4194304)
not to have occurred
```

It's coming from this line of the test - https://github.com/kubernetes/kubernetes/blob/master/test/e2e/scalability/density.go#L232 - where we list all pods across all namespaces. Seems like the MTU for gRPC calls changed as a result of the update.

cc @kubernetes/sig-scalability-bugs @RenaudWasTaken @wojtek-t

### PR DESCRIPTION
**Pull request by jpbetz**
Reapply https://github.com/kubernetes/kubernetes/pull/57160 but with etcd 3.2.13, which includes https://github.com/coreos/etcd/pull/9047 to fix https://github.com/kubernetes/kubernetes/issues/51099.

We need to scalability test this PR before merging it since the previous attempt to version bump to grpc v1.7+ resulted in a scalability test failure after the PR was merged to master, and we don't want to repeat that. No, no we don't.

Thanks @gyuho for fixing the etcd grpc issue and releasing etcd-3.2.13 on short notice.

**Release note**:

```release-note
Upgrade to etcd client 3.2.13 and grpc 1.7.5 to improve HA etcd cluster stability.
```

### CODE REVIEW

**Comment by jpbetz** [comment]
@shyamjvs Is there any to kick off a scalability test on this PR? We'd like to ensure it's passing before merging if possible since the last grpc bump caused scalability test instability on master and we'd prefer ensure we've fixed that issue before merging.

**Comment by gyuho** [comment]
@jpbetz etcd part LGTM.

I'd also like to know how kubernetes encountered https://github.com/kubernetes/kubernetes/issues/51099.
etcd didn't have any tests around this while upgrading gRPC.

If `etcd.embed.Etcd` were used, `embed.NewConfig().MaxRequestBytes` should be configured based on test workloads; otherwise, server-side request limit defaults to 1.5 MiB. For client-side, v3.2.12 defaults response limit to `math.MaxInt32`. So, just upgrading to v3.2.12 should fix the error `"rpc error: code = ResourceExhausted desc = grpc: received message larger than max (26710706 vs. 4194304)"`.

Thanks.

**Comment by wojtek-t** [comment]
Both big kubemark tests passed, but the suite timedout. My feeling is that it's long build and we can ignore it. @porridge ?

**Comment by porridge** [comment]
Yes, the timeout of `pull-kubernetes-kubemark-e2e-gce-big` is not a problem here.  This looks promising, but I'm running an additional 5k-node test manually to confirm.

**Comment by porridge** [comment]
On second thought, it's actually somewhat suspicious that 80 minutes were not enough for a test which passes in ~50 on master. I'll take a closer look.

**Comment by wojtek-t** [comment]
> On second thought, it's actually somewhat suspicious that 80 minutes were not enough for a test which passes in ~50 on master. I'll take a closer look.

In master we are not building - with presubmit we are doing building. It used to take 30m+ in the past, maybe it's still the case.

**Comment by porridge** [comment]
Right, just compared and the additional ~30 minutes are from quick-release. Let me fix the timeouts.

**Comment by porridge** [comment]
/test pull-kubernetes-kubemark-e2e-gce-big
just checking whether the bumped timeout works, don't worry if it fails again.

**Comment by porridge** [comment]
FWIW, those pull-kubernetes-bazel-test do **not** look like flakes.

**Comment by porridge** [comment]
FTR, the 5k-node cluster test is still running. I'll check its fate in a few hours.

**Comment by gyuho** [comment]
I don't know what bazel-test does but just by looking at etcd server log https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/57480/pull-kubernetes-bazel-test/22946/, it `grep`s with `failed` string:

> I1221 07:44:08.718] 2017-12-21 07:31:35.225279 W | etcdserver/api/v3rpc: **failed** to receive watch request from gRPC stream ("rpc error: code = Canceled desc = context canceled")

etcd logs this when it actually fails to receive stream from a client or the client closes the stream. This was added to https://github.com/coreos/etcd/releases/tag/v3.2.11, so if this test passed with v3.2.11, something else is wrong?

**Comment by jpbetz** [comment]
When I saw these context canceled errors in the logs last night, I also
suspected they might be a red herring.  I’ll dig in today.

**Comment by jpbetz** [comment]
@porridge Thanks, yes the `pull-kubernetes-bazel-test` failure appears to be consistent, we'll need to get to the bottom of that.

It looks like the scalability tests are passing now though? `pull-kubernetes-kubemark-e2e-gce-big` appears to be green.

**Comment by porridge** [comment]
@jpbetz yes, and my manual 5000-node cluster tests also passed, so
/lgtm
(hoping the fix for the bazel-test job does not cause a regression :-)

**Comment by luxas** [comment]
/retest

cc @kubernetes/sig-cluster-lifecycle-pr-reviews

**Comment by xiangpengzhao** [comment]
seems like the failure of `pull-kubernetes-bazel-test` is not just a flake?

**Comment by nilebox** [comment]
Just tried to bump `etcd` and `grpc` dependencies in Service Catalog, and found the same issue in the log: https://github.com/kubernetes-incubator/service-catalog/pull/1633#issuecomment-354228519
```
=== RUN   TestDeleteServiceInstance/asynchronous_deprovision_without_operation_key
2017-12-28 04:54:32.106592 W | etcdserver/api/v3rpc: failed to receive watch request from gRPC stream ("rpc error: code = Canceled desc = context canceled")
2017-12-28 04:54:32.115205 W | etcdserver/api/v3rpc: failed to receive watch request from gRPC stream ("rpc error: code = Canceled desc = context canceled")
```
So it is definitely not just flaky test.

**Comment by wojtek-t** [comment]
I have a feeling that bazel failure is still a real one.

**Comment by jpbetz** [comment]
@wojtek-t Yes, i'm relatively certain it is. Ignore the rebase, it was just to keep my branch current. We're digging in to the bazel issue now.

**Comment by xiang90** [comment]
> So it is definitely not just flaky test, seems to be some issue with this etcd version.

Probably because etcd added some warning level logging. i feel it is not a real problem.

**Comment by jpbetz** [comment]
`pull-kubernetes-bazel-test` times out after 5 minutes when running `bazel test //pkg/master:go_default_test`.  When running the same test locally, the test fails when [calling `NewClientV3` for each member of the cluster in the `NewClusterV3` function](https://github.com/coreos/etcd/blob/b19dae00651b890498bcca38ac2cc3cad471281e/integration/cluster.go#L945):

```
--- FAIL: TestAPIVersionOfDiscoveryEndpoints (44.73s)
	cluster.go:945: cannot create client: context deadline exceeded
```

I'll bump to etcd 3.2.13 now.

**Comment by jpbetz** [comment]
After bumping to etcd 3.2.13 locally, `//pkg/master:go_default_test` passes. Waiting on `pull-kubernetes-bazel-build` results.

**Comment by timothysc** [comment]
@jpbetz is your plan for still to backport this?  I'm hoping this is only a v1.10+ given the issues and changes, I'm guessing we want the whole cycle to verify. 

/cc @kubernetes/sig-cluster-lifecycle-misc

**Comment by jpbetz** [comment]
@timothysc I agree. Let's let this bake on 1.10+. Given the volume of upstream change this bump has pulled in, it be irresponsible to backport to 1.9 in the short term. Happy to revisit the decision if/when this proves stable, maybe after the 1.10 release.

**Comment by jpbetz** [comment]
/test pull-kubernetes-cross

(last two pull-kubernetes-cross failures were not the same)

**Comment by jpbetz** [comment]
/test pull-kubernetes-cross

(docker builds still failing to pull from registries)

**Comment by jpbetz** [comment]
https://github.com/kubernetes/kubernetes/issues/57822

**Comment by jpbetz** [comment]
@wojtek-t @porridge This is ready to merge, just need a lgtm with latest changes in place.

**Comment by porridge** [comment]
Thanks @jpbetz , I will start another  5k-node test today.

**Comment by wojtek-t** [comment]
/lgtm

I've added "no-not-merge" label to let @porridge do another larger test. But since it was previously passing, I think it will be passing now too.

**Comment by porridge** [comment]
Density test passed, load capacity test failed.
I will investigate closer next week, in the meantime I'm starting another run in case it was a flake.

**Comment by porridge** [comment]
This time load capacity passed and density failed.
/hold cancel
I will investigate in the background.

**Comment by jpbetz** [comment]
Clean rebase

**Comment by porridge** [comment]
FTR:
 - load capacity failed due to https://github.com/kubernetes/kubernetes/issues/55860
 - density failed due to something very similar to https://github.com/kubernetes/kubernetes/issues/56066

**Comment by jpbetz** [comment]
Thanks for following up @porridge

**Comment by mfojtik** [comment]
@jpbetz have you figured out what was causing the "context cancelled" errors? 

> When I saw these context canceled errors in the logs last night, I also
> suspected they might be a red herring.  I’ll dig in today.

**Comment by shyamjvs** [comment]
FYI - today while looking at apiserver mem usage in our 5k-node scalability tests, I noticed a huge drop across runs 93 and 95. From the [diff](https://github.com/kubernetes/kubernetes/compare/411881803f20a6...9f80ae741), this change seems to have most likely caused the improvement :)

etcd_update_change

Do we know why we see such improvement? What changed?

**Comment by jpbetz** [comment]
@shyamjvs I suspect it is a combination of things. In the grpc v1.3.0 -> v1.7.5 upgrade there are various performance improvements (see https://github.com/grpc/grpc-go/releases/tag/v1.5.0, https://github.com/grpc/grpc-go/releases/tag/v1.4.0) and there are quite a few etcd 3.1-3.2 client improvements (@gyuho any that you know of that would improve memory utilization this much?).

@cheftako It would be great to be able to run the memory analysis tool you've been trying out on scalability runs like this. Ideally, a tool like that would tell us exactly what changed from baseline.

**Comment by gyuho** [comment]
We did some performance work for 3.3 (https://github.com/coreos/etcd/blob/master/CHANGELOG-3.3.md#improved-1), but double client upgrade would have much effect. Yeah, I would be interested in what have caused this :)

**Comment by redbaron** [comment]
is this PR backportable?

**Pull request merged**
