### PR TITLE
add unit tests for TestSetNestedStringSlice, TestSetNestedSlice etc.

### PR DESCRIPTION
**Pull request by kidlj**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Add unit tests for several exported functions: `SetNestedStringSlice`, `SetNestedSlice`, `SetNestedStringMap`, `SetNestedMap`.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kidlj** [comment]
@apelisse Hi, would you please /approve again for this PR, it seems that the robot has lost your directions. Thanks.

**Comment by dims** [comment]
@kidlj this needs api approval

/assign @liggitt @smarterclayton 

NOTE: Jordan, Clayton, there's a lgtm/approve from @apelisse already, so quick approval from api side needed.

**Pull request merged**
