### PR TITLE
OPTIONS should be passed through the proxy

### PR DESCRIPTION
**Pull request by smarterclayton**
Options is used by some web servers and APIs for extra info - its omission means
that proxy can't service them.

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Change LGTM. You need to update the swagger spec, tough.
Not sure if this is eligible for v1.

**Comment by saad-ali** [comment]
@bgrant0607 for v1.0 triage

**Comment by nikhiljindal** [comment]
@smarterclayton You need to rebase and update swagger spec.

**Comment by bgrant0607** [comment]
This is a bug fix. We should take it.

**Comment by bgrant0607** [comment]
LGTM

**Pull request merged**
