### PR TITLE
Fix get with List

### PR DESCRIPTION
**Pull request by janetkuo**
Follow up https://github.com/kubernetes/kubernetes/pull/14793#discussion_r40866706
Make kubectl get -f [file of List] work. 

cc @bgrant0607

### CODE REVIEW

**Comment by jlowdermilk** [comment]
lgtm. While you're at it, uncomment/include the `test-cmd.sh` test that you added [here](https://github.com/kubernetes/kubernetes/pull/14793/files#diff-e2c8544666bb21f92286b190d5c8cb9aR776) in #14793?

**Comment by JanetKuo** [comment]
@k8s-bot test this please

**Comment by JanetKuo** [comment]
@k8s-bot test this

**Comment by JanetKuo** [comment]
@jlowdermilk the test for getting `List` in `test-cmd.sh`is now included.

**Comment by jlowdermilk** [comment]
lgtm, thanks Janet!

**Comment by bgrant0607** [comment]
Thanks!

**Comment by a-robinson** [comment]
This needs a rebase before it can be merged

**Comment by JanetKuo** [comment]
Rebased.

**Comment by JanetKuo** [comment]
I just found that sometimes when we do `kubectl annotate` in `test-cmd.sh` (see [here](https://github.com/kubernetes/kubernetes/pull/14888/files#diff-e2c8544666bb21f92286b190d5c8cb9aR780)), etcd complains `replicationControllers "mock" cannot be updated: the object has been modified; please apply your changes to the latest version and try again`. My guess is that it's because we did `kubectl label` [here](https://github.com/kubernetes/kubernetes/pull/14888/files#diff-e2c8544666bb21f92286b190d5c8cb9aR775) right before we annotate and somehow etcd is confused? cc @lavalamp @caesarxuchao

**Comment by lavalamp** [comment]
@JanetKuo It means something else modified the object. It should be safe to just retry. (Maybe kubectl itself should do the retry.)

**Comment by JanetKuo** [comment]
@k8s-bot test this

**Comment by mikedanese** [comment]
This made kubectl output really funky.

```
➜  kubernetes git:(master) k get po --namespace=kube-system                                 
NAME                             READY     STATUS    RESTARTS   AGE
elasticsearch-logging-v1-eqoex   1/1       Running   0          2h
NAME                             READY     STATUS    RESTARTS   AGE
elasticsearch-logging-v1-vfpyf   1/1       Running   0          2h
NAME                                                    READY     STATUS    RESTARTS   AGE
fluentd-elasticsearch-e2e-test-mikedanese-minion-1rwb   1/1       Running   0          2h
NAME                                                    READY     STATUS    RESTARTS   AGE
fluentd-elasticsearch-e2e-test-mikedanese-minion-ccus   1/1       Running   0          2h
NAME                                                    READY     STATUS    RESTARTS   AGE
fluentd-elasticsearch-e2e-test-mikedanese-minion-ofta   1/1       Running   0          2h
NAME                 READY     STATUS    RESTARTS   AGE
heapster-v10-v20fa   1/1       Running   0          2h
NAME                      READY     STATUS    RESTARTS   AGE
kibana-logging-v1-ht9sx   1/1       Running   1          2h
NAME                READY     STATUS    RESTARTS   AGE
kube-dns-v9-b0ym3   4/4       Running   0          2h
NAME               READY     STATUS    RESTARTS   AGE
kube-ui-v3-v0yrj   1/1       Running   0          2h
NAME                                   READY     STATUS    RESTARTS   AGE
monitoring-influxdb-grafana-v2-yy6u2   2/2       Running   0          2h
```
unintended?

**Comment by JanetKuo** [comment]
@mikedanese Hmm, yes it's unintended. Looks like after we add `Flatten()`, each retrieved List-style objects are expanded into individual items and then visited individually, and therefore aren't formatted well.

**Comment by mikedanese** [comment]
This PR caused #15853

**Pull request merged**
