### PR TITLE
fix: remove redundant error log print

### PR DESCRIPTION
**Pull request by qmloong**
#### What type of PR is this?
Remove redundant error log print introduced by #98138
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by serathius** [comment]
Please sign the CLA

**Comment by qmloong** [comment]
> Please sign the CLA

Is there anything wrong? I signed it before.

**Comment by qmloong** [comment]
> Please sign the CLA

Oh, sorry. I forgot to change my git username and email config.

**Review by yangjunmyfm192085 — COMMENTED** [review]
/lgtm

**Pull request merged**
