### PR TITLE
e2e: move funs of framework/viperconfig to e2e

### PR DESCRIPTION
**Pull request by clarklee92**
Signed-off-by: clarklee92 <clarklee1992@hotmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
e2e: move funs of framework/viperconfig to e2e
**Which issue(s) this PR fixes**:

Ref #86052

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
i'm fine with this move

cc @pohly 
please comment if you have any objections.

**Comment by johnSchnake** [comment]
The move doesnt jump out to me as problematic. The fact that we can unexport the function and it has so few callers makes it seem like this is a good move.

/lgtm

**Review by johnSchnake — APPROVED** [review]

**Comment by oomichi** [comment]
Thanks for doing this.
The comments of `test/e2e/framework/config/config.go` which contains `viperconfig.ViperizeFlags("my-config.yaml", "", Flags)` also need to be updated, but it is fine to follow up later.

/lgtm
/approve

**Pull request merged**
