### PR TITLE
Add support for Network Policies in client go -- client-go issue #57

### PR DESCRIPTION
**Pull request by FlorianOtel**
(Caveat: My first PR, so if something missing, pls advise accordingly):

As described in client-go issue nr 57 (see [here](https://github.com/kubernetes/client-go/issues/57)) client-go does not currently support extension methods for Network Policies. 

I have manually added those in my client-go branch located [here](https://github.com/FlorianOtel/client-go).  

However, as per the instructions in the issue above, the PR was  to performed by adding the "// +genclient=true in "pkg/apis/extensions/v1beta1/types.go" and updating the code gen. 

This PR reflects that change. 

Please advise accordingly. 

Thanks, 

/Florian

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by caesarxuchao** [comment]
LGTM.

**Comment by caesarxuchao** [comment]
@k8s-bot ok to tes

**Comment by caesarxuchao** [comment]
@k8s-bot ok to test

**Comment by caesarxuchao** [comment]
Bazel test is not happy, could run hack/update-bazel.sh and squash the changes?

**Comment by FlorianOtel** [comment]
@caesarxuchao Done. Not sure I've managed the squash though ...

**Comment by FlorianOtel** [comment]
Ping @caesarxuchao @deads2k 

Please advise

**Comment by deads2k** [comment]
> Ping @caesarxuchao @deads2k
> 
> Please advise

`git rebase --interactive master`  You'll get a prompt with some directions. You're looking for the `f` on your *second* commit (instead of `pick`).

**Comment by FlorianOtel** [comment]
@caesarxuchao @deads2k

Done. 

Fetched upstream, rebased as advised, kept only one commit log message (fixup) in my branch. 

Hope I got it right now :)

**Comment by FlorianOtel** [comment]
@k8s-bot verify test this

**Pull request closed without merging**
