### PR TITLE
Client gen file lowercase

### LINKED ISSUE #18939: Generated client files should not have mixed case
We do not use mixed case filenames in our codebase - a few have cropped up as part of generation `pkg/client/types/generated/unversioned/componentStatus.go` that should be nixed.  They should be `componentstatus.go` or `component_status.go`.  coding-conventions.md should be updated to call this out explicitly, which I will do in a separate PR.

@caesarxuchao @lavalamp @krousey not sure who is active in the generator right now

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #18939.

For convenience, I just change all the names of the generated files to the lowercase.

### CODE REVIEW

**Comment by smarterclayton** [comment]
LGTM once tests pass, feel free to self apply label.

**Comment by caesarxuchao** [comment]
@k8s-bot test this please

**Comment by caesarxuchao** [comment]
@k8s-bot unit test this please

**Comment by caesarxuchao** [comment]
Apply the lgtm per comment.

**Comment by caesarxuchao** [comment]
@k8s-bot e2e test this

**Comment by caesarxuchao** [comment]
Manually merge. Just changes of file names.

**Pull request merged**
