### PR TITLE
Minion->Node rename: docs/ machine names only, except gce/aws for #1111

### PR DESCRIPTION
**Pull request by 13rac1**
Yet another in the long line of exciting changes for the technical debt issue #1111, this renames all server/machine names in `/docs`: `-minion-`, `minion-`, `-minion`. Markdown files _only_, `e2e-not-required`.

Note: it's not just a simple sed, because extra spaces/tabs are required to keep text alignments.

I've excluded aws and gce because those should be handled when the specific providers are addressed. Only `/docs` and machine names to keep the number of changed lines lower for ease of review, avoid `size/XL`\+ labels, and make other following pull requests easier.

### CODE REVIEW

**Comment by eosrei** [comment]
@smarterclayton Can you please review or reassign this? Thanks!

**Comment by eosrei** [comment]
@bgrant0607 @thockin Hi Tim and/or Brian, can you look at this PR? It's yet another boring really simple minion->node for # 1111. No code, just markdown docs. I've gotten no response from the assignee for a week. Thank you

**Comment by eosrei** [comment]
@thockin Thanks!

**Comment by thockin** [comment]
No, thank you!  when the last "minion" is gone we'll have a party.

**Pull request merged**
