### PR TITLE
Automated cherry pick of #30351 #30354

### PR DESCRIPTION
**Pull request by ixdy**
Cherry pick of #30351 #30354 on release-1.3.
#30351: Debug kubemark startup problems
#30354: fix kubemark

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35720)

### CODE REVIEW

**Comment by ixdy** [comment]
I think this fixes the PR kubemark tests on release-1.3.

cc @gmarek @bprashanth

**Comment by gmarek** [comment]
Looks good to me.

**Comment by bprashanth** [comment]
Thanks! LGTM

**Comment by ixdy** [comment]
Now kubemark failed for a different reason, which is kinda like progress.

**Comment by fabioy** [comment]
@ixdy Thanks for continuing to work on this. Surprising how many other changes affect tests.

**Comment by ixdy** [comment]
Kubemark still appears to be broken on release-1.3 because
* `--garbage-collector-enabled` isn't defined for 1.3
* lots of `gcloud * list --zone`, which no longer works.

@gmarek should we just disable kubemark on 1.3?

**Comment by wojtek-t** [comment]
@ixdy - I think we can disable it on 1.3

**Comment by ixdy** [comment]
@wojtek-t OK, I'll just drop this PR in favor of disabling kubemark on 1.3.

**Comment by ixdy** [comment]
https://github.com/kubernetes/test-infra/pull/946

**Pull request closed without merging**
