### PR TITLE
Automated cherry pick of #56685: Fix ipvs proxier nodeport

### LINKED ISSUE #58202: ipvs NodePort is not working if host not using eth{i} as nic name in 1.9.0
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>

/kind bug

> /kind feature

**What happened**:
Deploy an application as following:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    run: my-nginx
  name: my-nginx
  namespace: default
spec:
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: my-nginx
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: my-nginx
  name: my-nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: my-nginx
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - image: nginx:1.8.1
        imagePullPolicy: IfNotPresent
        name: my-nginx
        ports:
        - containerPort: 80
          protocol: TCP
```

After application deployed:
```
[root@ib17b08 cases]# kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)        AGE
kubernetes   ClusterIP   10.0.0.1     <none>        443/TCP        1h
my-nginx     NodePort    10.0.0.13    <none>        80:30731/TCP   19m
```

ClusterIP works fine
```
[root@ib17b08 cases]# curl 10.0.0.13
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```
NodePort does not work
```
[root@ib17b08 cases]# curl 9.21.53.18:30731
^C
```

/cc @m1093782566 
/sig network
/area ipvs
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by Lion-Wei**
**What this PR does / why we need it**:

Cherry pick of #56685 on release-1.9.
#56685: Fix ipvs proxier nodeport

cherry-pick ipvs proxier nodeport related commit to release-1.9, since without those commit,  ipvs NodePort will not working if host not using eth{i} as nic name in 1.9.0.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #58202 #55923

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mbohlool** [comment]
What is the parent PR? Why this is not automatically cherrypicked?

**Comment by Lion-Wei** [comment]
Here is the parent pr: #56685 
I'm not familiar with automatically cherrypick, but this pr was merged in Dec 19, without this pr, ipvs nodeport may not work in some environment.

**Comment by gyliu513** [comment]
Thanks @Lion-Wei 

We already claimed ipvs is beta feature but it does not work if I was using `eth` as prefix for my network, this is a blocker issue for most of the end users. Without this back merge, we cannot claim 1.9.x ipvs is beta quality. 

@thockin @m1093782566 @lavalamp @mbohlool Can we speed up the process for this back merge? Thanks!

**Comment by Lion-Wei** [comment]
@gyliu513 . Thanks for your attention, unfortunately one unit test case failed, and I use the original release-1.9 branch ran this test also failed, very weird, you have any clue about this?
```
# go test -v k8s.io/kubernetes/test/integration/auth -run TestNodeAuthorizer$
# k8s.io/kubernetes/pkg/generated/openapi
pkg/generated/openapi/zz_generated.openapi.go:22536:33: resource.Quantity literal.OpenAPISchemaType undefined (type resource.Quantity has no field or method OpenAPISchemaType)
pkg/generated/openapi/zz_generated.openapi.go:22537:33: resource.Quantity literal.OpenAPISchemaFormat undefined (type resource.Quantity has no field or method OpenAPISchemaFormat)
pkg/generated/openapi/zz_generated.openapi.go:23481:28: v1.MicroTime literal.OpenAPISchemaType undefined (type v1.MicroTime has no field or method OpenAPISchemaType)
pkg/generated/openapi/zz_generated.openapi.go:23482:28: v1.MicroTime literal.OpenAPISchemaFormat undefined (type v1.MicroTime has no field or method OpenAPISchemaFormat)
pkg/generated/openapi/zz_generated.openapi.go:23931:23: v1.Time literal.OpenAPISchemaType undefined (type v1.Time has no field or method OpenAPISchemaType)
pkg/generated/openapi/zz_generated.openapi.go:23932:23: v1.Time literal.OpenAPISchemaFormat undefined (type v1.Time has no field or method OpenAPISchemaFormat)
pkg/generated/openapi/zz_generated.openapi.go:24385:34: intstr.IntOrString literal.OpenAPISchemaType undefined (type intstr.IntOrString has no field or method OpenAPISchemaType)
pkg/generated/openapi/zz_generated.openapi.go:24386:34: intstr.IntOrString literal.OpenAPISchemaFormat undefined (type intstr.IntOrString has no field or method OpenAPISchemaFormat)
FAIL	k8s.io/kubernetes/test/integration/auth [build failed]
```

**Comment by mbohlool** [comment]
please follow automated cherrypick procedure. This PR look like one, but has the wrong branch name.

**Comment by Lion-Wei** [comment]
@mbohlool Thanks, Then I think this pr need be closed, I'll create another pr.

**Pull request closed without merging**
