### PR TITLE
Bump GCE to container-vm-v20151215

### PR DESCRIPTION
**Pull request by zmerlynn**
New kubelet version (which doesn't matter), no new Docker version, new
base bits. Cherry-pickable to 1.1.

### CODE REVIEW

**Comment by zmerlynn** [comment]
cc @dchen1107 @roberthbailey

**Comment by roberthbailey** [comment]
LGTM.

**Comment by dchen1107** [comment]
LGTM

**Comment by roberthbailey** [comment]
@k8s-bot unit test this

**Comment by roberthbailey** [comment]
@k8s-bot unit test this

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by zmerlynn** [comment]
@k8s-bot e2e test this

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by wojtek-t** [comment]
@k8s-bot e2e test this please

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Pull request merged**
