### PR TITLE
Bump rules_go and build "static" binaries in pure Go mode

### PR DESCRIPTION
**Pull request by ixdy**
**What this PR does / why we need it**: uses latest set of enhancements in bazelbuild/rules_go to properly build the "static" Go binaries using pure Go (i.e. `CGO_ENABLED=0`), and to support cross compilation of these binaries. Cross compilation of cgo-enabled binaries is still not supported.

Also depends on https://github.com/kubernetes/repo-infra/pull/52, and requires bazel 0.8+ (which is not yet enabled in CI for kubernetes/kubernetes).

Note that for proper cross compilation we'll also need to remove the hardcoded "linux-amd64" that's strewn about several `BUILD` files.

**Release note**:

```release-note
NONE
```

/hold
/assign @BenTheElder @mikedanese @spxtr

### CODE REVIEW

**Comment by BenTheElder** [comment]
>  requires bazel 0.8+ (which is not yet enabled in CI for kubernetes/kubernetes).

We could probably do this now, though maybe we want to wait until after code freeze? :man_shrugging:
We could at least check that the canary works in the meantime
/test pull-test-infra-bazel-build-canary

**Comment by ixdy** [comment]
Canary will also fail until https://github.com/kubernetes/kubernetes/issues/56516 is fixed.

**Comment by luxas** [comment]
cc @kubernetes/sig-cluster-lifecycle-pr-reviews @kad for new bazel/release builds that we eventually can use in our new, shiny bazel debs :)

**Comment by ixdy** [comment]
I need to merge https://github.com/kubernetes/test-infra/pull/5990 (to use bazel 0.8+ on prow), but this is now working locally.

**Comment by ixdy** [comment]
/hold cancel

This is finally ready for review - all dependencies have been fixed.

**Comment by ixdy** [comment]
/assign @thockin
for autogenerated-BUILD file approval.

**Comment by ixdy** [comment]
This is hopefully one of the last "regenerate all of the `BUILD` files" PRs. The go rules are deprecating the `library` attribute in favor of `embed`, so we had to update every `go_binary` rule, and we now support every platform that go supports, so we are adding platform select rules in a bunch of places.

**Comment by cblecker** [comment]
> This is hopefully one of the last "regenerate all of the BUILD files" PRs.

🎉

**Comment by luxas** [comment]
Thanks @ixdy! This now seems unblocked, can we proceed?
Would be great to get this in ASAP to avoid rebase hell in v1.10

Also, this will make the bazel build spit out multiarch binaries, right?

**Review by BenTheElder — APPROVED** [review]
/lgtm

**Comment by BenTheElder** [comment]
> Also, this will make the bazel build spit out multiarch binaries, right?

It should make it possible to ask bazel to spit out binaries for any go-toolchain-supported-platform for the pure-go binaries (IE the ones switched in this PR, not other ones using CGO stuff).

**Comment by cblecker** [comment]
/lgtm cancel
To stop retesting loop

**Comment by ixdy** [comment]
Rebased and tried updating `rules_go` to latest, which exploded, so reverted back to `0.8.1`.

I'll watch tests, but this should be good to merge again.

**Comment by ixdy** [comment]
re-tagging LGTM

**Pull request merged**
