### PR TITLE
Optimize random string generator to avoid multiple locks & use bit-masking

### PR DESCRIPTION
**Pull request by shyamjvs**
Ref https://github.com/kubernetes/kubernetes/issues/53327

We recently started seeing a 50% decrease in scheduling throughput (for e.g in kubemark-500 scale job) and turns out https://github.com/kubernetes/kubernetes/pull/53135 introduced it.
The reason is [this call](https://github.com/jsafrane/kubernetes/blob/2caae38d323720a96be34606589f41488ba82b87/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L272) to create a random 32-length string.
From the code of the `rand` utility (which is being heavily used throughout the system for randomizing object names), I noticed following performance issues:
- to create an n-length string, we are making n calls to `rand.Intn()` each of which does a lock+unlock operation on the RNG.. while just 1 lock+unlock operation is enough for all
- we're choosing one character (from an alphabet of 27 chars) per each random integer.. while we can select 10 characters using a single int63 (by masking and bit-shifting) as 1 character uses just 5 bits of randomness
- the character set is defined as a global slice (mutable), so the compiler needs to fetch length of the slice on each invocation to `len()` (we're making n of those).. while we can just use a const string (immutable) which will make len directly available as a cached constant (yes, go does it!)

This PR is making the above fixes. I'll try to add some benchmarking to measure the difference (as @wojtek-t suggested).

/cc @kubernetes/sig-scalability-misc @kubernetes/sig-scheduling-bugs @kubernetes/sig-api-machinery-misc @wojtek-t @smarterclayton

### CODE REVIEW

**Comment by liggitt** [comment]
I don't object to improving this, but https://github.com/kubernetes/kubernetes/pull/53135 probably shouldn't be calling rand… is there a reason an incrementing counter couldn't be used instead?

**Comment by shyamjvs** [comment]
@jsafrane would be able to answer.

**Comment by smarterclayton** [comment]
Why are we using a global static utility function that needs a global static lock?  That seems... dumb.

We should be initializing a random source for whatever components need it and let them do their locking.  The volume controller should only be contending with itself, in which case just give it a seed per worker (which should be easy).

**Comment by shyamjvs** [comment]
@smarterclayton I filed https://github.com/kubernetes/kubernetes/issues/53888 for the issue you stated. I'd prefer having that change in a separate PR as there are multiple places where the change needs to be made (i.e replace global RNG references with `newRNG()` calls).

**Comment by wojtek-t** [comment]
> @smarterclayton I filed #53888 for the issue you stated. I'd prefer having that change in a separate PR as there are multiple places where the change needs to be made (i.e replace global RNG references with newRNG() calls).

I agree - let's not try to solve all the problems of random library as a resolving scalability regression.

/lgtm

**Comment by shyamjvs** [comment]
@wojtek-t Also added the benchmark (though I'm still trying to make it run locally). Could you re-lgtm?

**Comment by shyamjvs** [comment]
Results of benchmark:

without this PR:

```
BenchmarkRandomStringGeneration-12    	  300000	      4129 ns/op
```

with this PR:

```
BenchmarkRandomStringGeneration-12    	 5000000	       337 ns/op
```

**Comment by wojtek-t** [comment]
Cool, but that's something I expected.
Looking forward to see the impact on kubemark test jobs.

**Comment by smarterclayton** [comment]
Changing it is fine, I just want to make sure we don't continue the pattern
(i.e. if we cut ourselves on a sharp corner, we should fix the corner, not
put a sign up that says "don't touch").  This should be the last time
someone regresses on this by accidentally using this package.

**Comment by wojtek-t** [comment]
> Changing it is fine, I just want to make sure we don't continue the pattern
(i.e. if we cut ourselves on a sharp corner, we should fix the corner, not
put a sign up that says "don't touch").  This should be the last time
someone regresses on this by accidentally using this package.

Agree. I just wanted to fix regression ASAP and this seemed to fix it (and already existed).
But I completely agree that we should get rid of that package (or rework it somehow to at least not be global).

**Pull request merged**
