### PR TITLE
Bumped Heapster version to v0.20.0-alpha and Influxdb to 0.9.2.1

### PR DESCRIPTION
**Pull request by piosz**
ref #18826

### CODE REVIEW

**Comment by piosz** [comment]
cc @mwielgus @vishh @kubernetes/autoscaling @kubernetes/goog-control-plane

**Comment by piosz** [comment]
cc @fgrzadkowski

**Comment by mwielgus** [comment]
Can we have regular version in selector?

-    version: v12
+    version: v13

has nothing to do with v0.20.0-alpha1 and should be replaced.

**Comment by piosz** [comment]
I'm just following the pattern. Should confirm with someone responsible for introducing those versions, but let's move it out from the scope of this PR since it's complicated enough right now.

**Comment by mwielgus** [comment]
OK, this can wait.
The change looks good to me (disclaimer: i didn't manage to review 9k LOC of deps thoroughly - only flew over the diff) but lets give others a chance to protest.

**Comment by vishh** [comment]
Just a few comments. Otherwise LGTM

**Comment by mwielgus** [comment]
LGTM

**Comment by fgrzadkowski** [comment]
Merging this now to make sure we have at least few runs in CET timezone.

**Pull request merged**
