### PR TITLE
remove misterikkit from scheduler maintainers

### PR DESCRIPTION
**Pull request by misterikkit**
**What type of PR is this?**
/kind documentation

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by bsalamat — COMMENTED** [review]
/lgtm

Thanks, @misterikkit for all your contributions to SIG Scheduling. I wish you best with your new projects.

**Review by thockin — COMMENTED** [review]
As you wish :)

/lgtm
/approve

**Pull request merged**
