### PR TITLE
Fix small typo in ubernetes-lite E2E_ZONES

### PR DESCRIPTION
**Pull request by ixdy**
Introduced in #21122.

@quinton-hoole @ihmccreery @spxtr

### CODE REVIEW

**Comment by ixdy** [comment]
@k8s-bot e2e test this again please, flake #19299

**Comment by ihmccreery** [comment]
Gah, sorry.  Good catch.

**Comment by ihmccreery** [comment]
LGTM.

**Comment by ixdy** [comment]
Also realized that we need to export `MULTIZONE`, not `E2E_MULTIZONE`. Sorry for not doing a very thorough review on this section yesterday :\

**Comment by ixdy** [comment]
Well, I did not expect the SQ to merge that. Pretty sure it's OK though. TBR=@ihmccreery I guess :)

**Comment by ihmccreery** [comment]
Fine by me.

**Pull request merged**
