### PR TITLE
Improved code coverage for plugin/pkg/scheduler/algorithm/priorities…

### PR DESCRIPTION
**Pull request by gyliu513**
…/most_requested.go

**What this PR does / why we need it**:
Part of #39559 , code coverage improved from 70+% to 80+%

### CODE REVIEW

**Comment by timothysc** [comment]
@k8s-bot ok to test

**Comment by gyliu513** [comment]
@k8s-bot kops aws e2e test this

**Comment by gyliu513** [comment]
@k8s-bot unit test this

**Comment by gyliu513** [comment]
@k8s-bot cvm gke e2e test this

**Pull request merged**
