### PR TITLE
Thread user guide docs together

### PR DESCRIPTION
**Pull request by bgrant0607**
Thread user guide docs together with "What's next" sections, and add a couple missing TOCs.

### CODE REVIEW

**Comment by bgrant0607** [comment]
all green, if you're still merging stuff, @thockin :-)

**Comment by bgrant0607** [comment]
Rebased after user doc move. Should be good to go now.

**Comment by thockin** [comment]
LGTM

**Comment by bgrant0607** [comment]
The shippable failure can't be due to this PR:
```
--- FAIL: TestExampleObjectSchemas (0.54s)
examples_test.go:344: skipping : ../docs/user-guide/multi-pod.yaml/multi-pod
examples_test.go:339: ../examples/pod.yaml: pod does not have a test case defined
examples_test.go:344: skipping : ../examples/elasticsearch/apiserver-secret.yaml/apiserver-secret
FAIL
```
@mikedanese

**Comment by bgrant0607** [comment]
Was PR #11256

**Comment by erictune** [comment]
You probably need to rebase after #11191

**Comment by bgrant0607** [comment]
Rebased.

cc @thockin for merge once checks pass

**Comment by thockin** [comment]
LGTM

**Comment by bgrant0607** [comment]
all green

**Pull request merged**
