### PR TITLE
TODO:Merge package

### PR DESCRIPTION
**Pull request by stewart-yu**
**What this PR does / why we need it**:
This PR is a TODO
Merge package :pkg/api/v1/node to pkg/util/node.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by stewart-yu** [comment]
@cblecker@ncdc@gmarek

**Comment by stewart-yu** [comment]
Who can add A APPROVED flag? Thanks.@cblecker@ncdc@gmarek

**Comment by thockin** [comment]
Isn't there another PR to merge these libs?  I asked there - is this the right direction?  Since it uses versioned node objects, shouldn't it be a versioned lib?  will you also do the other resource-specific API helper libs?

**Pull request closed without merging**
