### PR TITLE
Update k8s.io/utils dependency and use ebtables from there

### PR DESCRIPTION
**Pull request by luigibk**
/kind cleanup

**What this PR does / why we need it**:

Following the move of ebtables to k8s.io/utils: 

https://github.com/kubernetes/utils/pull/175

This is a follow up (and clean up) PR to migrate to ebtables vendored from utils.

**Special notes for your reviewer**:

There is no specific issue attached to this as I am assuming a link to the k8s.io/utils PR (see above) is enough in this case. I hope that is correct.

The migration of the ebtables code was completed to allow for re-use in this kubernetes/dns PR:

https://github.com/kubernetes/dns/pull/390

```release-note
None
```

### CODE REVIEW

**Comment by aojea** [comment]
/lgtm

/assign @thockin @bowei 
as they did previous approvals on this topic

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by luigibk** [comment]
@aojea and @thockin I had to fix the bazel build scripts and I also rebased + squashed the commits. Sorry to bother you, but can you please give it another look (not much has changed)?

**Comment by luigibk** [comment]
Hi @dims could you please have a look at this? 

It's a follow up to:

https://github.com/kubernetes/utils/pull/175

which you reviewed

**Comment by dims** [comment]
@luigibk everything is done for this PR, it's waiting for master to reopen.

**Comment by luigibk** [comment]
> @luigibk everything is done for this PR, it's waiting for master to reopen.

@dims I see. Thanks!

**Pull request merged**
