### PR TITLE
fix broken link

### PR DESCRIPTION
**Pull request by zhanghuidinah**
**What this PR does / why we need it**:
fix broken link
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by zhanghuidinah** [comment]
i sign it!

**Comment by xiangpengzhao** [comment]
/ok-to-test
/lgtm

Thanks!

**Comment by xiangpengzhao** [comment]
ping @lavalamp for approval

**Comment by php-coder** [comment]
It's still there and I'm surprised that it's not merged yet.

PTAL @lavalamp @smarterclayton only your approval is required.

**Pull request merged**
