### PR TITLE
add yaml-quote for GCE_GLBC_IMAGE

### PR DESCRIPTION
**Pull request by freehan**
fix a bug that `GCE_GLBC_IMAGE` was not processed by yaml-quote.
```release-note
NONE
```

### CODE REVIEW

**Comment by bowei** [comment]
how did this work without yaml quote?

**Comment by freehan** [comment]
> how did this work without yaml quote?

Because the consumer does not care so far: https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure-helper.sh#L2221

**Comment by jberkus** [comment]
This PR is still pending approval and does not appear to be a blocker.   As such, it is being removed from 1.9.  If this is in error (because it does actually represent critical breakage) please escalate the priority and return it to the milestone (and approve it) within the next 24 hours.  Thanks!

/priority important-soon

**Comment by dims** [comment]
@eparis @jbeda @mikedanese @roberthbailey @zmerlynn - we need of of you to hit `/approve no-issue` for this one today or looks like it will be dropped from 1.9 per release team

**Comment by bowei** [comment]
@mikedanese looks like this needs your approval

**Pull request merged**
