### PR TITLE
Record PodSandbox creation failure event in a more human-readable way

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Record PodSandbox creation failure event in a more human-readable way

**Which issue(s) this PR fixes**:

Ref #91410

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
Thanks for your pr! Always in favor of making error messages as helpful as possible.

Could you please in your pr or in the commit message, write an example of old error message and an example of the new error message, so reviewers can compare them? Thanks!

**Comment by SataQiu** [comment]
> Thanks for your pr! Always in favor of making error messages as helpful as possible.
> 
> Could you please in your pr or in the commit message, write an example of old error message and an example of the new error message, so reviewers can compare them? Thanks!

Sure! `msg` contains [more context information](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_sandbox.go#L48-L50), not just the error information.

For example:

Before:
```
Failed to create pod sandbox: mkdir /var/log/pods/xxxxx: file name too long
```

After:
```
Create pod log directory for pod xxxx failed: mkdir /var/log/pods/xxxxx: file name too long
```

**Pull request closed without merging**
