### PR TITLE
Disable cAdvisor event storage by default

### PR DESCRIPTION
**Pull request by timstclair**
Fixes https://github.com/kubernetes/kubernetes/issues/24698

### CODE REVIEW

**Comment by timstclair** [comment]
Oops, looks like this requires https://github.com/google/cadvisor/pull/1243 or https://github.com/google/cadvisor/pull/1242.

**Comment by timstclair** [comment]
This is still blocked by https://github.com/kubernetes/kubernetes/pull/25914, but since it's on the 1.3 milestone I'd like to get it reviewed so it can be merged as soon as the dependencies are met (assuming tests pass at that point).

**Comment by vishh** [comment]
LGTM

**Comment by timstclair** [comment]
Dependency merged: removing do-not-merge

**Comment by timstclair** [comment]
@k8s-bot test this, issue #IGNORE

**Comment by timstclair** [comment]
@k8s-bot node e2e test this, issue https://github.com/kubernetes/kubernetes/issues/24508

**Pull request merged**
