### PR TITLE
Update 'fluentd-elasticsearch' image.

### PR DESCRIPTION
**Pull request by st4nson**
**What this PR does / why we need it**:

Plugins updated for `fluentd-elasticsearch`:
 - fluent-plugin-elasticsearch 1.5.0 -> 1.9.5
 - fluent-plugin-kubernetes_metadata 0.24.0 -> 0.27.0

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by crassirostris** [comment]
@st4nson Could you please also update the DaemonSet spec?

@k8s-bot ok to test

**Comment by st4nson** [comment]
@k8s-bot pull-kubernetes-cross test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by st4nson** [comment]
@k8s-bot pull-kubernetes-cross test this
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by st4nson** [comment]
@k8s-bot pull-kubernetes-cross test this

**Comment by st4nson** [comment]
@k8s-bot pull-kubernetes-cross test this

**Comment by crassirostris** [comment]
@k8s-bot pull-kubernetes-cross test this

**Comment by crassirostris** [comment]
Cross test is broken, more info in https://github.com/kubernetes/kubernetes/pull/46521

It doesn't block the queue, so don't bother

**Comment by st4nson** [comment]
Got it @crassirostris :+1:. Do we need anything else to merge it ?

**Comment by crassirostris** [comment]
@st4nson @coffeepac should take a look, he's currently a maintainer. He's in US, so hopefully later today. Yesterday was a holiday there

**Comment by crassirostris** [comment]
@coffeepac Yay, it works finally :)

**Pull request merged**
