### PR TITLE
Add myself to sig-scheduling maintainers/approvers list.

### PR DESCRIPTION
**Pull request by aveshagarwal**
@bsalamat @k82cn 

**Release note**: 
```release-note
None
```

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@kubernetes/sig-scheduling-misc

**Comment by bsalamat** [comment]
LGTM

**Comment by aveshagarwal** [comment]
@smarterclayton can you approve this?

**Review by bsalamat — COMMENTED** [review]
/lgtm

**Comment by k82cn** [comment]
btw, that'll better also to append your contribution for other reference :)

**Comment by smarterclayton** [comment]
/approve

Sig leads signed off

**Comment by aveshagarwal** [comment]
> btw, that'll better also to append your contribution for other reference :)

Just noticed, though its not very clear what you are asking,  but seems like about my contributions in scheduling area so here they are (whatever quickly comes to my mind):

- More than 100 commits to kubernetes, mostly in scheduling area and some in other areas too.
- One of the main contributors/leads to cluster-capacity (https://github.com/kubernetes-incubator/cluster-capacity) and descheduler (https://github.com/kubernetes-incubator/descheduler) projects (see the code changes in both of them).
- Gave a talk on cluster-capacity and scheduler in kubecon 2017 (Austin, USA) (https://www.youtube.com/watch?v=uNQt5Y8RTZk). 
- Active participation in sig-scheduling related stuff in Kubernetes.

**Pull request merged**
