### PR TITLE
Change redis image gcr

### PR DESCRIPTION
**Pull request by janetkuo**
Follow up https://github.com/kubernetes/kubernetes/pull/27577#discussion_r67809871:

> Any chance we can move these images somewhere in gcr.io?

I pushed `kubernetes/redis:v1` to `gcr.io/google_containers/redis:v1`.  

[Analytics]()

### CODE REVIEW

**Comment by fejta** [comment]
LGTM, thanks!

**Comment by aledbf** [comment]
@janetkuo please check #21424. I'm not sure which PR changed the yaml files. 
The new redis images size is 10MB.

**Comment by fejta** [comment]
@k8s-bot unit test this issue: #28076

**Comment by fejta** [comment]
@k8s-bot unit test this issue: #28076

**Pull request merged**
