### PR TITLE
Automated cherry pick of #70954: Upgrade Stackdriver Logging Agent addon image to 0.6-1.6.0-1

### PR DESCRIPTION
**Pull request by qingling128**
Cherry pick of #70954 on release-1.12.

#70954: Upgrade Stackdriver Logging Agent addon image to 0.6-1.6.0-1

### CODE REVIEW

**Comment by qingling128** [comment]
@MaciekPytel Could you help with this one as well? This one is for `v1.12`. It still needs an `approved` label.

**Comment by feiskyer** [comment]
cherry pick approved.

**Pull request merged**
