### PR TITLE
Drop cloud-controller-manager artifacts from k/k release

### LINKED ISSUE #81027: Deprecate and remove cloud-controller-manager binary
We dropped cloud-controller-manager deb from the release in https://github.com/kubernetes/kubernetes/pull/65338. Since all external cloud providers will end up having their own custom controller-manager, we should deprecate and eventually remove this binary and associated bits.

/sig cloud-provider

### PR DESCRIPTION
**Pull request by dims**
`cloud-controller-manager` was supposed to be a temporary artifact for making external cloud providers possible. But we end up shipping binaries/man pages etc. Let's stop doing that now in 1.16 so we can deprecate and remove this binary.

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #81027

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
cloud-controller-manager binaries and docker images are no longer shipped with kubernetes releases.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
pod pending timeout 🙄 
/retest

**Comment by BenTheElder** [comment]
build changes look good, should this also be removed from hyperkube?

**Review by BenTheElder — APPROVED** [review]
/approve
/lgtm
for build & hack

/hold
for discussion

**Review by thockin — COMMENTED** [review]
I guess I am OK with this, if we're confident that nobody is using this.  Are we?  How are we?

What about the code in cmd/... and maybe elsewhere?

**Comment by dims** [comment]
@thockin the code in cmd/ can be used as a template for folks who are getting started to write their own stuff. I will remove the references in hyperkube later. I want this focused on just the artifacts that we ship.

**Comment by thockin** [comment]
Should we move cmd to staging/.../cloud-controller-example or something?

Thanks!

/lgtm
/approve

**Comment by andrewsykim** [comment]
> Should we move cmd to staging/.../cloud-controller-example or something?

I'd like to move `cmd/cloud-controller-manager` to staging, but the tricky thing is that it imports controllers in `pkg/controllers` which depends on a bunch of internal imports. 

One thing we _could_ do is remove internal deps in cloud specific controllers (service, route, cloud node lifecylce, etc) to somewhere like `k8s.io/cloud-provider/controllers` (in staging) and that would unblock us from moving `cmd/cloud-controller-manager` to staging as well. @thockin @dims are you opposed to that idea?

**Comment by dims** [comment]
@andrewsykim I like that idea. please investigate that a bit more.

**Comment by andrewsykim** [comment]
Sounds good, opened an issue here https://github.com/kubernetes/kubernetes/issues/81172 - will update that issue with next steps

**Pull request merged**
