### PR TITLE
Update copyright string in gluster volume plugin.

### PR DESCRIPTION
**Pull request by humblec**
Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

### CODE REVIEW

**Comment by humblec** [comment]
@rootfs @jsafrane PTAL

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by jsafrane** [comment]
Why do you change it? All the other code has copyright from the year when the file was created.

**Comment by humblec** [comment]
@jsafrane then I misinterpreted it. My belief was that, the copyright string has to be updated on the way to reflect current.

**Pull request closed without merging**
