### PR TITLE
Automated cherry pick of #92331: fix: update max azure disk max count

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #92331 on release-1.18.

#92331: fix: update max azure disk max count

### CODE REVIEW

**Comment by tpepper** [comment]
With an initial review, this looks like a feature backport introducing support for new Azure virtual machine types.  Eg: https://github.com/MicrosoftDocs/azure-docs/commits/master/articles/virtual-machines/ev4-esv4-series.md shows these types introduced just this month.

**Comment by andyzhangx** [comment]
> With an initial review, this looks like a feature backport introducing support for new Azure virtual machine types. Eg: https://github.com/MicrosoftDocs/azure-docs/commits/master/articles/virtual-machines/ev4-esv4-series.md shows these types introduced just this month.

hi @tpepper this a hard to say it's a feature, since some users used new VM sizes, and then it got a wrong max count of data disk.

**Comment by feiskyer** [comment]
> With an initial review, this looks like a feature backport introducing support for new Azure virtual machine types.

@tpepper I think it should be OK to treat k8s broken caused by cloud platform changes as bugs. WDYT?

**Comment by ialidzhikov** [comment]
Is there something blocking the merge of this PR?

**Pull request merged**
