### PR TITLE
Bugfix: Force Godep check

### PR DESCRIPTION
**Pull request by mbohlool**
before this PR, verify-godeps.sh only ran if there is a change in `Godep/` folder, however that is not always the case. If you stop using a dependency, `Godep/` folder should be updated. If not, the PR will get merge, but the next person changing `Godep/` will have changes in `Godep/` that is not related to their change and if these kind of unchecked PR merged during code review, they will have a hard time merging their PR and will get rebase hell (that was the case for https://github.com/kubernetes/kubernetes/pull/45836).

### CODE REVIEW

**Comment by cblecker** [comment]
Doing this will drastically increase the time to run make verify (both locally and in presubmit CI) if godeps need to be downloaded and compared every time, even if deps don't change in that particular PR.

The `KUBE_FORCE_VERIFY_CHECKS` flag is set as part of `ci-kubernetes-verify-master`, so there are ways to catch if there is an issue with the Godeps.

@kubernetes/sig-contributor-experience-misc

**Comment by rmmh** [comment]
Agreed. We see a lot more breakage from 'make verify' failing because some dep timed out downloading than we do from PRs that aren't caught by this simple heuristic.

To be more precise, if you stop using a dependency in vendor/, but don't delete it manually, a future godep restore will fail? This could be a much faster check than the full `godep restore` pass.

**Comment by mbohlool** [comment]
Maybe we can at least run one check with `KUBE_FORCE_VERIFY_CHECKS`? Is `ci-kubernetes-verify-master` running as part of PR checks? It is happening to my PRs if I change Godep more than I expected and it is also odd to have a commit that says "Adding X dependency" while it is also "removing Y dependency" that I have nothing to do with.

**Comment by mbohlool** [comment]
Or even better we can make the robot to run and update Godep automatically in those cases. What do you guys suggest to decreasing rebases and less wasting engineering time?

**Comment by thockin** [comment]
We should run this once per day or something and auto-file bugs.

**Comment by fejta** [comment]
The `ci-*` jobs run at head. The `pull-` jobs run on PRs.

Please click and drag from the red to green cell and select "Search for changes" to list PRs that merged between the bad and good runs.

I'm inclined to close this version of the PR. It is okay to find the occasional problem after merging. This is why we have tests that run after merging. 

Alternatively we can improve the heuristic, although "has changes in Godeps and/or vendor" seems to work pretty well. Maybe add a new "did we remove a vendor import?"

**Comment by apelisse** [comment]
But `update-bazel.sh` automatically updates the vendor dependencies we have in the BUILD files. Can we use that to quickly detect if Godep needs to be updated?

**Comment by ixdy** [comment]
`update-bazel.sh` will update the `BUILD` files in the tree, but it doesn't affect `vendor/` unless you add a new package there.

I guess to continue on that idea: rather than triggering godep checks only on changes to `Godeps/` or `vendor/`, also trigger it if there are any `BUILD` changes that include `vendor/`. It'd probably run more than necessary, but less frequently than every time.

**Pull request closed without merging**
