### PR TITLE
E2E podresources: fix test checking esclusive cpus allocation

### PR DESCRIPTION
**Pull request by ffromani**
#### What type of PR is this?

/kind cleanup
/kind failing-test

#### What this PR does / why we need it:
Since commit 42dd01aa3f3 the cpuRequest is in millicores, hence  we need to properly check translating to exclusive cpus     when verifying the resource allocation.

#### Which issue(s) this PR fixes:
Fixes N/A

#### Special notes for your reviewer:
This issue is not evident in our CI because the machines on which CI runs don't have enough cpus to perform exclusive allocations, hence the e2e tests skips. We figured out thanks to RH's internal testing on BM.

#### Does this PR introduce a user-facing change?
<!--
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
N/A

### CODE REVIEW

**Comment by fromanirh** [comment]
/sig node
suggested priority: important-longterm (because the fix is trivial)

**Comment by fromanirh** [comment]
/hold
running final tests on the aforementioned BM

**Comment by SergeyKanzhelev** [comment]
> /hold running final tests on the aforementioned BM

@fromanirh do you still need this hold?

**Review by SergeyKanzhelev — APPROVED** [review]

**Comment by fromanirh** [comment]
> > /hold running final tests on the aforementioned BM
> 
> @fromanirh do you still need this hold?

yes, but I plan to lift it soon as the last internal verification is in progress (pending BM availability)

**Comment by fromanirh** [comment]
BM tests revealed an additional issue with kubelet restart. Investigating. Will keep updating.

**Comment by fromanirh** [comment]
ok, restarting the kubelet seems to be broken. I'll investigate.

**Comment by cynepco3hahue** [comment]
Can be related to recent PRs related to DynamicKubeletConfguration removal. I will re-check the code.

**Comment by fromanirh** [comment]
Our BM tests is green again; we managed to provide a couple extra fixes. Kudos to @cynepco3hahue for helping here!

**Pull request merged**
