### PR TITLE
Allow updating scheduling directives of suspended jobs that never started

### LINKED ISSUE #104714: Make NodeAffinity mutable for Jobs
#### What would you like to be added:

Make NodeAffinity constraints mutable for suspended Jobs. 

#### Why is this needed:

In https://github.com/kubernetes/kubernetes/issues/97170 we added a new flag to allow suspending jobs to control when the Pods of a Job get created by controller-manager. We proposed this as a primitive that higher-level controllers can use to support job queuing,

Allowing to mutate NodeAffinity constraints allows a higher-level queue controller to influence job placement by injecting node affinity constraints before un-suspending a job.

The implementation is basically relaxing the validation on job updates to allow for mutating the node affinity constraints of the pod template for suspended jobs.

/sig scheduling
/sig apps
/kind feature

### PR DESCRIPTION
**Pull request by ahg-g**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Implements https://github.com/kubernetes/enhancements/issues/2926

#### Which issue(s) this PR fixes:

Fixes #104714

#### Does this PR introduce a user-facing change?

```release-note
Node affinity, node selector and tolerations are now mutable for jobs that are suspended and have never been started
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
[KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/2926-job-mutable-scheduling-directives
```

### CODE REVIEW

**Comment by liggitt** [comment]
@alculquicondor can you take a first pass on the API bits for this?

**Review by alculquicondor — COMMENTED** [review]
API lgtm... good to squash.

**Comment by ahg-g** [comment]
> API lgtm... good to squash.

done.

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Pull request merged**
