### PR TITLE
[TESTING][DO NOT MERGE] .go-version: start testing with go1.22.0

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

go1.22rc1 is out: https://groups.google.com/d/msgid/golang-dev/i4w5OV_URQ2Ujw8qN1iw5g%40geopod-ismtpd-11?utm_medium=email&utm_source=footer

go1.22rc2 is out: https://groups.google.com/d/msgid/golang-dev/qZiVldckS2ejO6h8xowc1A%40geopod-ismtpd-canary-0?utm_medium=email&utm_source=footer

go1.22.0 is out: https://groups.google.com/d/msgid/golang-dev/PLf3BJQNTb2guUAF3D2JSg%40geopod-ismtpd-5?utm_medium=email&utm_source=footer

go1.22 is going to be a release with quite a few language changes and changes to the std lib. I'd like to start running the CI with it so that we can start getting fixes in and working with the other projects that we rely on if we need to.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MadhavJivrajani** [comment]
### pull-kubernetes-typecheck 

Failure:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5a90be]
goroutine 356 [running]:
go/types.(*Checker).handleBailout(0xc003697800, 0xc003c75bd0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.22rc1.linux.amd64/src/go/types/check.go:367 +0x88
panic({0x639460?, 0x82f360?})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.22rc1.linux.amd64/src/runtime/panic.go:770 +0x[13](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/122410/pull-kubernetes-typecheck/1737348733923758080#1:build-log.txt%3A13)2
go/types.(*StdSizes).Sizeof(0x0, {0x6d2b20, 0x8322a0})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.22rc1.linux.amd64/src/go/types/sizes.go:228 +0x31e
```

I see `SizeOf` at the top of the call stack, which internally uses an implementation of `types.Sizes`. From the go1.22 release notes (https://tip.golang.org/doc/go1.22):
> The implementation of [SizesFor](https://tip.golang.org/pkg/go/types#SizesFor) has been adjusted to compute the same type sizes as the compiler when the compiler argument for SizesFor is "gc". The default [Sizes](https://tip.golang.org/pkg/go/types#Sizes) implementation used by the type checker is now types.SizesFor("gc", "amd64").

**Comment by MadhavJivrajani** [comment]
No new failures 🎉

**Comment by MadhavJivrajani** [comment]
No new failures 🎉

**Comment by dims** [comment]
@MadhavJivrajani see https://github.com/containerd/containerd/pull/9794#issuecomment-1934750243 we may have to bump go-winio

**Pull request closed without merging**
