### PR TITLE
Change Azure global rate limit to per client

### LINKED ISSUE #86019: Change Azure global rate limit to per client
**What happened**:

There're a set of rate limit options in cloud provider config file:

| cloudProviderRateLimitQPS         | Rate limit QPS (Read)  | Float value, valid if `cloudProviderRateLimit` is true   |
| --------------------------------- | ---------------------- | -------------------------------------------------------- |
| cloudProviderRateLimitBucket      | Rate limit Bucket Size | Integar value, valid if `cloudProviderRateLimit` is true |
| cloudProviderRateLimitQPSWrite    | Rate limit QPS (Write) | Float value, valid if `cloudProviderRateLimit` is true   |
| cloudProviderRateLimitBucketWrite | Rate limit Bucket Size | Integer value, valid if `cloudProviderRateLimit` is true |

But today, these operations are applied and counted by all operations.

We should change it to per client, so that one client's issue won't block another client.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by feiskyer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind feature
/area provider/azure
/priority important-soon
/sig cloud-provider

**What this PR does / why we need it**:

Change Azure global rate limit to per client, so that one client's rate limit issue won't block another client.

Example configure:

```json
{
                 // default rate limit (enabled).
                 "cloudProviderRatelimit": true,
		"cloudProviderRateLimitBucket": 1,
		"cloudProviderRateLimitBucketWrite": 1,
		"cloudProviderRateLimitQPS": 1,
		"cloudProviderRateLimitQPSWrite": 1,
		"virtualMachineScaleSetRateLimit": {
			// VMSS specific (enabled).
			"cloudProviderRatelimit": true,
			"cloudProviderRateLimitBucket": 2,
			"CloudProviderRateLimitBucketWrite": 2,
			"cloudProviderRateLimitQPS": 0,
			"CloudProviderRateLimitQPSWrite": 0
		},
		"loadBalancerRateLimit": {
			// LB specific (disabled)
			"cloudProviderRatelimit": false,
		},
}
```

**Which issue(s) this PR fixes**:

Fixes #86019

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Azure global rate limit is switched to per-client. A set of new rate limit configure options are introduced, including routeRateLimit, SubnetsRateLimit, InterfaceRateLimit, RouteTableRateLimit, LoadBalancerRateLimit, PublicIPAddressRateLimit, SecurityGroupRateLimit, VirtualMachineRateLimit, StorageAccountRateLimit, DiskRateLimit, SnapshotRateLimit, VirtualMachineScaleSetRateLimit and VirtualMachineSizeRateLimit.

The original rate limit options would be default values for those new client's rate limiter.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by andyzhangx — COMMENTED** [review]
code lgtm
is there upgrade test from old config to new config, make sure old config still works in new config?

**Comment by feiskyer** [comment]
> is there upgrade test from old config to new config, make sure old config still works in new config?

@andyzhangx yep, old configured rate limits are still working.

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
