### PR TITLE
remove duplicate code

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
**What this PR does / why we need it**:

remove unused duplicate code

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

no impact on function

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by brendandburns** [comment]
/ok-to-test

If this is truly dead code, then LGTM, I guess we'll see if the unit tests run...

**Comment by hzxuzhonghu** [comment]
@brendandburns This is really unused code.

**Comment by hzxuzhonghu** [comment]
ping @brendandburns

**Comment by enisoc** [comment]
This seems like it can wait until after the release. Let me know if you disagree.

**Pull request merged**
