### PR TITLE
add kubeadm completion command

### PR DESCRIPTION
**Pull request by xilabao**
reference to `kubectl completion`

```
#kubeadm <tab><tab>
alpha       completion  init        join        reset       version
```

### CODE REVIEW

**Comment by pires** [comment]
Wow, this looks sweet! Is there a way to hide `kubeadm completion`?

**Comment by xilabao** [comment]
> Wow, this looks sweet! Is there a way to hide kubeadm completion?

@pires I'm afraid not. `completion` has to act as root command.

**Comment by pires** [comment]
Overall, this LGTM. But I'd like feedback from @luxas and @errordeveloper.

**Review by pires — APPROVED** [review]

**Comment by luxas** [comment]
I'd want some feedback from @kubernetes/sig-cli-pr-reviews, please
I think it's probably ok since kubectl also has this command visible

**Comment by pires** [comment]
@luxas if kubectl exposes similar behavior, then please approve this and let's have it merged before code-freeze.

**Comment by luxas** [comment]
Ok, this seems to be nearly exactly the same code as kubectl has, let's get it in (given tests are passing)

/approve

**Comment by pires** [comment]
@k8s-bot kops aws e2e test this

**Comment by xilabao** [comment]
rebased @luxas @pires

**Pull request merged**
