### PR TITLE
modify the  annotation 

### PR DESCRIPTION
**Pull request by jianglingxia**
modify the  annotation  that CreateKubeAPIServer

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by wojtek-t** [comment]
I'm not a native speaker, but I think what was before this change was correct. @ncdc ?

**Comment by ncdc** [comment]
@wojtek-t yes, "wires" is intentional. "Wires up" or "wires together" might be a bit more explicit, but "writes" is incorrect.

**Comment by ncdc** [comment]
@deads2k in case you have a grammatical opinion

**Comment by wojtek-t** [comment]
That's what I thought. So closing this PR.

**Pull request closed without merging**
