### PR TITLE
Automated cherry pick of #72143: Fix aad support in kubectl for sovereign cloud

### PR DESCRIPTION
**Pull request by andyzhangx**
Cherry pick of #72143 on release-1.11.

#72143: Fix aad support in kubectl for sovereign cloud

### CODE REVIEW

**Comment by andyzhangx** [comment]
ping @mikedanese @karataliu

**Comment by andyzhangx** [comment]
could you approve this PR: @mikedanese @smarterclayton @liggitt, thanks.

**Comment by liggitt** [comment]
I'll defer to @mikedanese as the original approver

**Comment by mikedanese** [comment]
Sorry I missed this.

/lgtm
/approve

**Comment by andyzhangx** [comment]
@liggitt could you approve then? Thanks.

**Comment by feiskyer** [comment]
v1.11.10 has been released 4 days ago. Since it's the last version of 1.11 branch, I think there's no way to get this merged any more. @foxish

**Comment by andyzhangx** [comment]
it's ok not get merged into v1.11, close this PR now.

**Pull request closed without merging**
