### PR TITLE
iSCSI Plugin: Remove remounting of device in global path.

### PR DESCRIPTION
**Pull request by ghost**
This code was originally added because the first mount call did not
respect the ro option. This no longer seems to be the cause so there
is no need to use remount.

cc @rootfs

### CODE REVIEW

**Comment by roberthbailey** [comment]
@thockin for 1.0 triage.

**Comment by thockin** [comment]
@swagiaal why is this not required any more?  Is there an e2e test that proves this?

Not required for 1.0, this can wait until after.

**Comment by swagiaal** [comment]
@thockin I am not quite sure why it is no longer required TBH. I just have not been able to reproduce the original bug that @rootfs wrote this to work around and it seemed very suspicious that 'mount' would ignore the ro option. I'll dig some more and see if I can create an e2e test.

**Comment by piosz** [comment]
Is this PR still active?

**Comment by swagiaal** [comment]
@piosz Yes. The test which @thockin asked for has been merged in #11054. I'll rebase and run the test

**Comment by thockin** [comment]
LGTM

needs rebase

**Comment by swagiaal** [comment]
@saad-ali can you help with this ? :/

**Comment by saad-ali** [comment]
@k8s-bot test this please

**Comment by saad-ali** [comment]
@swagiaal Can you take a look at why E2E is failing? I'll remove LGTM for now.

**Comment by swagiaal** [comment]
Thanks @saad-ali... looks like it was test flakiness

**Pull request merged**
