### PR TITLE
move manifestURLHeader initialization close to where it uses

### PR DESCRIPTION
**Pull request by chengyu-l**
**What type of PR is this?**

/kind cleanup
/area kubelet

**What this PR does / why we need it**:

move manifestURLHeader initialization close to where it uses

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

### CODE REVIEW

**Comment by chengyu-l** [comment]
signed

**Comment by chengyu-l** [comment]
signed

**Comment by chengyu-l** [comment]
> /test pull-kubernetes-node-e2e

/test pull-kubernetes-node-e2e

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm
Sensible refactor that doesn't change any behavior, so this should be safe to merge.

However, this current method doesn't have unit test coverage - I'd feel even more confident merging this if we could add a unit test that exercises the `makePodSourceConfig` function. Not necessarily a prerequisite for merging the diff, but it would be great to see!

**Comment by chengyu-l** [comment]
> /lgtm
> Sensible refactor that doesn't change any behavior, so this should be safe to merge.
> 
> However, this current method doesn't have unit test coverage - I'd feel even more confident merging this if we could add a unit test that exercises the `makePodSourceConfig` function. Not necessarily a prerequisite for merging the diff, but it would be great to see!

**Comment by chengyu-l** [comment]
> /lgtm
> Sensible refactor that doesn't change any behavior, so this should be safe to merge.
> 
> However, this current method doesn't have unit test coverage - I'd feel even more confident merging this if we could add a unit test that exercises the `makePodSourceConfig` function. Not necessarily a prerequisite for merging the diff, but it would be great to see!

@mattjmcnaughton  thx, I can add a unit test

**Comment by chengyu-l** [comment]
@mattjmcnaughton the unit test for #91322 pr have committed

**Comment by chengyu-l** [comment]
OMG, I finally solved the problem of GitHub compilation failure. @mattjmcnaughton please review it again for me, thanks

**Review by mattjmcnaughton — COMMENTED** [review]
/assign @mtaufen 
@mtaufen looks like you wrote the original function - are you able to review the new tests? thanks!

**Comment by chengyu-l** [comment]
@mtaufen  are you able to review the new tests? thanks!

**Pull request closed without merging**
