### PR TITLE
kuberuntime: don't override the pod IP for pods using host network

### PR DESCRIPTION
**Pull request by yujuhong**
This fixes the issue of not passing pod IP via downward API for host network pods.

### CODE REVIEW

**Comment by yujuhong** [comment]
This fixes #43531

Tested manually.
Writing a unit test for this can be tricky. I'll file an issue for adding a node e2e test.

**Comment by Random-Liu** [comment]
/lgtm

The logic is too confusing. We should clean this up at some point. :)

**Comment by yujuhong** [comment]
> The logic is too confusing. We should clean this up at some point. :)

I think we can push the responsibility of populating the ip to individual runtime packages (e.g., `kuberuntime` and `rkt`).

**Comment by dchen1107** [comment]
I remembered @freehan fixed this in old dockertool before. :-)

/lgtm

**Comment by jayunit100** [comment]
So to clarify, the `determineSandboxIp` is the reason this took so long ?

**Comment by yujuhong** [comment]
> So to clarify, the determineSandboxIp is the reason this took so long ?

Not sure what you meant. The bug is about not passing the pod ip to the container at creation time as environment variables. You'll still get the correct pod IP in the pod status.

**Pull request merged**
