### PR TITLE
- fixed the defencing of the rbd lock

### PR DESCRIPTION
**Pull request by gambol99**
Locking was working fine for me. The cleanup code however was throwing an exception when attempting to remove the lock. The code reads in a json file left in the <plugin>/rbd.json folder and then attempts to decode this into a rbdCleaner{*rbd} which doesn't support the field and later throws a 'divide by zero exception' due to size being zero (i.e. nothing as been reread)  ...a typo perhaps on the struct? ... Either way, changing the rbdCleaner to a rbdBuilder allows use to decode the file and successfully release the lock.  

https://github.com/GoogleCloudPlatform/kubernetes/issues/12481

### CODE REVIEW

**Comment by a-robinson** [comment]
cc @rootfs @markturansky

**Comment by a-robinson** [comment]
@k8s-bot ok to test

**Comment by rootfs** [comment]
@gambol99 thanks!

**Comment by gambol99** [comment]
As a side note, looks like the original PR (https://github.com/GoogleCloudPlatform/kubernetes/pull/10563) added the fields into the rbd{} ... but was later removed in (https://github.com/GoogleCloudPlatform/kubernetes/commit/72e899e1b585d7f43eef17feb2dfdaa648dd9843) ...

**Comment by rootfs** [comment]
@gambol99 right, a rbd e2e should catch this problem.

**Pull request merged**
