### PR TITLE
fix: fake clientset ApplyScale subresource from 'status' to 'scale'

### PR DESCRIPTION
**Pull request by a7i**
#### What type of PR is this?
/king bug

#### What this PR does / why we need it:

fake clientset is currently using the wrong subresource for scale

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
fix fake clientset ApplyScale subresource from 'status' to 'scale'
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by a7i** [comment]
@jpbetz ping 🙏🏼

**Review by jpbetz — APPROVED** [review]
/lgtm
/approve

Thanks!

**Pull request closed without merging**
