### PR TITLE
Fixing golint errors for pkg/registry/autoscaling/rest

### PR DESCRIPTION
**Pull request by forestoden**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
This PR fixes golint errors for `pkg/registry/autoscaling/rest`

**Which issue(s) this PR fixes**:

Ref #68026

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

**Review by fejta — COMMENTED** [review]
/approve

**Comment by forestoden** [comment]
Looks like this is no longer needed per #68026

Closing

**Pull request closed without merging**
