### PR TITLE
Bump konnectivity-client to v0.0.15 in release-1.20

### PR DESCRIPTION
**Pull request by jkh52**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Pick a memory leak fix for Konnectivity Proxy into release-1.20.

(https://github.com/kubernetes/kubernetes/pull/98790)

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

- [KEP]: <link>
- [Usage]: <link>
- [Other doc]: <link>
-->
```docs

```

### CODE REVIEW

**Comment by BenTheElder** [comment]
hmmm
/retest

**Comment by BenTheElder** [comment]
/retest
🤨

**Comment by jkh52** [comment]
ping @kubernetes/release-managers per instructions

**Comment by jkh52** [comment]
ping @cpanato (a release manager)

**Comment by caesarxuchao** [comment]
@kubernetes/release-engineering can someone approve this cherrypick?

**Comment by cpanato** [comment]
from main branch: https://github.com/kubernetes/kubernetes/pull/98790

**Comment by cpanato** [comment]
from parent PR
/priority important-soon

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by jkh52** [comment]
Thank you!

**Pull request merged**
