### PR TITLE
mirantis openstack getting started guide 1.0

### PR DESCRIPTION
**Pull request by jjainschigg-r**
I've submitted a Getting Started guide for Kubernetes Cluster, deployed with Murano on Mirantis OpenStack. Please advise next steps? Thank you.

### CODE REVIEW

**Comment by jjainschigg-r** [comment]
I signed it!

On Tue, Sep 1, 2015 at 3:48 PM, googlebot <notifications@github.com> wrote:

> Thanks for your pull request. It looks like this may be your first
> contribution to a Google open source project, in which case you'll need to
> sign a Contributor License Agreement (CLA).
>
> [image: :memo:] *Please visit https://cla.developers.google.com/
> <https://cla.developers.google.com/> to sign.*
>
> Once you've signed, please reply here (e.g. I signed it!) and we'll
> verify. Thanks.
> ------------------------------
>
>    - If you've already signed a CLA, it's possible we don't have your
>    GitHub username or you're using a different email address. Check your
>    existing CLA data <https://cla.developers.google.com/clas> and verify
>    that your email is set on your git commits
>    <https://help.github.com/articles/setting-your-email-in-git/>.
>    - If you signed the CLA as a corporation, please let us know the
>    company's name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/13456#issuecomment-136838513>
> .
>



-- 
John Jainschigg, MCA (200 - Professional)
<http://training.mirantis.com/verify/certificate/status/HNDv3jg7jzRQdcElNCTdEA/200-764-459>
917-405-3116
jjainschigg@mirantis.com

[image: OSSV-signature-2015.gif] <http://www.openstacksv.com/>

**Comment by jjainschigg-r** [comment]
This is my first contribution, and I'm afraid I don't understand why checks have failed above. MIght someone link me to a brief tutorial/readme about composing a valid Getting Started guide?

**Comment by jlowdermilk** [comment]
@jjainschigg-r, the test failures are due to missing autogenerated munge/boilerplate that gets added to all docs. You can fix by running `hack/update-generated-docs.sh`.

The other, unrelated check is for signed cla. We require one for all contributors. Click the link in the @googlebot comment and comment "I signed it" to clear the check.

**Comment by erictune** [comment]
ok-to-test

**Comment by erictune** [comment]
Hi, @jjainschigg-r, thanks for your contribution.  Sorry for not reviewing immediately, I was out of town. 

I've taken a look at this now.  I like how you have included screenshots and how the Mirantis solution includes a GUI to aid installation.  

I do have two high-level comments on the doc that I'd like to discuss before accepting it.

1.  The doc mentions Kubernetes version 0.15.  We'd really like all our getting-started-guides to have people using 1.0.x.  What would be involved in bringing your Kubernetes version up to that?
1. it seems like a lot of the steps in the pre-requisites section are not specific to Kubernetes, but are in fact required anytime you setup a new environment with a Murano Application Catalog.  Is it possible that some of the text that in that section could reference other docs?

**Comment by erictune** [comment]
@jjainschigg-r this looks like a great contribution.  anything I can do to help it along?  Issues getting CLA signed?  Or did my review comments ask too much?  Or just busy with other things?

**Comment by jjainschigg-r** [comment]
Hi, Eric -- thank you for asking. Based on your earlier recommendations,
we're working on finishing out our Murano integration with a post 1.0
version of Kubernetes, and will resubmit shortly (in slightly modified
form, obviously) with that 'contemporized' installation methodology.

On Tue, Oct 13, 2015 at 3:29 PM, Eric Tune <notifications@github.com> wrote:

> @jjainschigg-r <https://github.com/jjainschigg-r> this looks like a great
> contribution. anything I can do to help it along? Issues getting CLA
> signed? Or did my review comments ask too much? Or just busy with other
> things?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/13456#issuecomment-147823917>
> .
>



-- 
John Jainschigg, MCA (200 - Professional)
<http://training.mirantis.com/verify/certificate/status/HNDv3jg7jzRQdcElNCTdEA/200-764-459>
917-405-3116
jjainschigg@mirantis.com

**Comment by erictune** [comment]
Closing since idle for a while.  Please feel free to open a new PR when you are ready.

**Comment by jjainschigg-r** [comment]
Thanks, Eric. We're documenting a new version and will PR when complete.

On Wed, Dec 2, 2015 at 7:29 PM, Eric Tune <notifications@github.com> wrote:

> Closing since idle for a while. Please feel free to open a new PR when you
> are ready.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/13456#issuecomment-161476022>
> .
>



-- 
John Jainschigg, MCA (200 - Professional)
<http://training.mirantis.com/verify/certificate/status/HNDv3jg7jzRQdcElNCTdEA/200-764-459>
917-405-3116
jjainschigg@mirantis.com

**Pull request closed without merging**
