### PR TITLE
WIP: Proxy periodic runner

### PR DESCRIPTION
**Pull request by thockin**
This started with Tim St. Clair's kube-proxy async kube-proxy patch and encapsulates the async runner more.  If this meets with approval, the PeriodicRunner (better name needed?) needs tests.

### CODE REVIEW

**Comment by wojtek-t** [comment]
> I started merging the async rate-limiting logic, but it's somewhat more complicated now that we do no-op detection for Update calls. Have to rethink how to do it best.

I think I'm not really following. The no-op detection is only done in the concrete reason of resync. For example, you are only checking if endpoints change if the reason is "syncEndpoints".
So in case of periodic resync, you won't be doing any no-op detection, so it should just work.

What am I missing?

**Comment by thockin** [comment]
Trying to clean this up I found a number of issues.

First, I think this example is broken, but MAYBE the brokenness is OK,
since it avoids some of the issues when it is fixed.  The intention was to
ONLY run the periodic sync if nothing else called sync in the meantime.
Now that we have reason codes, what reason do we pass?  We could change it
to a bitmask and accumulate, but all runs would still consume one token,
even if they are early-return.

Ignore bursts for a second, and consider a config of 1 run per 5 seconds
and period of 1 minute.  We know that Endpoints is being updated at least
every couple seconds, though a no-op.  Every time that happens, we consume
the token for that 5 second window.  The periodic full-sync will never
trigger because we don't know that it didn't actually sync, so we
reschedule the periodic to +1 minute.  Any real change to Endpoints is
going to be forced onto the next 5-second window because "fake" changes are
more frequent.

T+0: EndpointsUpdate:
  Call Run(ReasonEndpoints)
    Call syncProxyRules
      Consume token
        Figure out that this is a no-op
        Return early without sync
T+1: ServiceUpdate:
  Call Run(ReasonService)
    Call syncProxyRules
      Try to consume token; fail
        Schedule for next available run, +4seconds
        Return early without sync
T+2: EndpointsUpdate:
  Call Run(ReasonEndpoints)
    Call syncProxyRules
      Try to consume token; fail
        Schedule for next available run, +4seconds
        Return early without sync

It just becomes a periodic timer at the 5 second interval. That wasn't the
intention of the design.

Ideas bouncing around my (non-pushed) client:

1) Pre-check for no-op.  Put a fast "is this a no-op" check into
OnServiceUpdate() and OnEndpointsUpdate(), if it is a no-op, don't call
Run() at all.  Accumulate reason codes in a bitmask and pass the OR to
syncProxyRules().  There would be some duplicate work in the per-check and
the building of new maps, but only "real" runs would be counted.

2) Have a PeriodicRunner for each of Sync(), OnEndpointsUpdate(), and
OnServiceUpdate().  Pass the reason code internally.  This would mean that,
worst case, we would have short bursts of syncs, as each of them could run
close together.  If we accumulate reason codes, this could actually be a
good thing.

3) Let the periodic timer run free without affecting delayed runs.  This
would mean that sometimes we would end up with 2 syncs in a short window.
We'd want the period and min to be prime, probably so they don't line up
very often...

**Comment by wojtek-t** [comment]
> Ignore bursts for a second, and consider a config of 1 run per 5 seconds
and period of 1 minute.  We know that Endpoints is being updated at least
every couple seconds, though a no-op.  

I don't understand. What is triggering this update? Obviously it happens if we create/delete a pod being part of some service or we change some other things, but in steady state where nothing happens in the system, endpoints shouldn't be updated, right?

> Every time that happens, we consume the token for that 5 second window.  The periodic full-sync will never trigger

I guess I'm missing something, but the only thing for which we are using the reason is to check whether something changed (endpoints, services) and early-return. So if something changes, then it doesn't really matter what was the reason of the sync, right?

> because we don't know that it didn't actually sync, so we
reschedule the periodic to +1 minute.  Any real change to Endpoints is
going to be forced onto the next 5-second window because "fake" changes are
more frequent.

So what you are saying is that the update of iptables will potentially be delayed by 5s after some endpoints changes, right? But with this approach this can happen anyway, right?


> 1) Pre-check for no-op.  Put a fast "is this a no-op" check into
OnServiceUpdate() and OnEndpointsUpdate(), if it is a no-op, don't call
Run() at all.  Accumulate reason codes in a bitmask and pass the OR to
syncProxyRules().  There would be some duplicate work in the per-check and
the building of new maps, but only "real" runs would be counted.

I would like to go in somewhat this direction anyway. https://github.com/kubernetes/kubernetes/pull/43702 is the first step.
The next step is basically instead of regenerating the endpoints map all the time, try to update it in place (checking if changes) which should be fairly simple. Once you review that PR, I will create the other PR (it should take me few hours or so).

**Comment by thockin** [comment]
On Mon, Apr 10, 2017 at 11:23 AM, Wojciech Tyczynski
<notifications@github.com> wrote:
>
>> Ignore bursts for a second, and consider a config of 1 run per 5 seconds
>> and period of 1 minute. We know that Endpoints is being updated at least
>> every couple seconds, though a no-op.
>
> I don't understand. What is triggering this update? Obviously it happens if we create/delete a pod being part of some service or we change some other things, but in steady state where nothing happens in the system, endpoints shouldn't be updated, right?

Endpoints get updated as the master lease, still, or they were on my
test cluster as of last week...

>> Every time that happens, we consume the token for that 5 second window. The periodic full-sync will never trigger
>
> I guess I'm missing something, but the only thing for which we are using the reason is to check whether something changed (endpoints, services) and early-return. So if something changes, then it doesn't really matter what was the reason of the sync, right?

If I trigger for reason X, detect a no-op, and then Y actually needs a
sync, Y is delayed artificially.

>> because we don't know that it didn't actually sync, so we
>> reschedule the periodic to +1 minute. Any real change to Endpoints is
>> going to be forced onto the next 5-second window because "fake" changes are
>> more frequent.
>
> So what you are saying is that the update of iptables will potentially be delayed by 5s after some endpoints changes, right? But with this approach this can happen anyway, right?

It can happen, but in an ideal state, only actual sync operations are
throttled.  No-op events should just detect the no-op and return
without consuming a token.

> Pre-check for no-op. Put a fast "is this a no-op" check into
> OnServiceUpdate() and OnEndpointsUpdate(), if it is a no-op, don't call
> Run() at all. Accumulate reason codes in a bitmask and pass the OR to
> syncProxyRules(). There would be some duplicate work in the per-check and
> the building of new maps, but only "real" runs would be counted.
>
> I would like to go in somewhat this direction anyway. #43702 is the first step.
> The next step is basically instead of regenerating the endpoints map all the time, try to update it in place (checking if changes) which should be fairly simple. Once you review that PR, I will create the other PR (it should take me few hours or so).

Will look.

**Comment by wojtek-t** [comment]
>> I don't understand. What is triggering this update? Obviously it happens if we create/delete a pod being part of some service or we change some other things, but in steady state where nothing happens in the system, endpoints shouldn't be updated, right?

> Endpoints get updated as the master lease, still, or they were on my
test cluster as of last week...

Aah ok, I forgot about them. Of course you're right with it, we didn't yet change it (and IIRC, we are updating endpoints for each component (which gives probably 5 or sth) every 2).

Maybe it's time to actually change it - we know for quite long time that endpoints isn't the best object for it. Maybe we should create some dedicated object for it now?

> If I trigger for reason X, detect a no-op, and then Y actually needs a
sync, Y is delayed artificially.

Yeah - I forgot about those no-op changes. 

> It can happen, but in an ideal state, only actual sync operations are
> throttled.  No-op events should just detect the no-op and return
> without consuming a token.

I completely agree and i think that we can definitely change the code to be in such state. I'm happy to help with it because it aligns with my plans :)

**Comment by thockin** [comment]
I probably won't have time to look at it again until the weekend, but I
will try the "fast pre-check" option.

**Comment by wojtek-t** [comment]
> I probably won't have time to look at it again until the weekend, but I
will try the "fast pre-check" option.

If it can wait few more days, I will try to send out a PR for review that should significantly simplify it.

**Comment by wojtek-t** [comment]
@thockin - I think that once:
https://github.com/kubernetes/kubernetes/pull/44756 is reviewed and merged
https://github.com/kubernetes/kubernetes/pull/44766 (built on top of previous is rebased and reviewed and merged)

this PR should be fairly simple to rebase and fix remaining problems.

**Comment by wojtek-t** [comment]
@thockin - all my PRs are already merged, so this one should be ready for rebase and "go".
Will you have time to do this? If not I'm happy to take this from you and finish it next week.

**Comment by wojtek-t** [comment]
I've opened https://github.com/kubernetes/kubernetes/pull/45343 as a rebase for this PR.

There are still some missing bits there though

**Pull request closed without merging**
