### PR TITLE
Remove sleep from DynamicProvisioner test.

### PR DESCRIPTION
**Pull request by jsafrane**
The comment says that the sleep is there because of 10 minute PV controller
sync. The controller sync is now 15 seconds and it should be quick enough
to hide this in subsequent `WaitForPersistentVolumeDeleted(.. , 20*time.Minute)`

### CODE REVIEW

**Comment by jsafrane** [comment]
I tested it a bit (<100 times) on my GCE deployment, it seems to work without problems, we'll see in real (overcommitted) Jenkins...

**Comment by jsafrane** [comment]
@k8s-bot unit test this issue: #39604

**Comment by gnufied** [comment]
lgtm

**Comment by gnufied** [comment]
@k8s-bot kops aws e2e test this

**Pull request merged**
