### PR TITLE
Add pod manifest path to local cluster

### PR DESCRIPTION
**Pull request by resouer**
Added `POD_MANIFEST_PATH` to local cluster up because we are frequently using this flag when testing static & mirror pod during local dev.

### CODE REVIEW

**Comment by ixdy** [comment]
Seems fine to me. Not sure if there's someone better to review this.

**Comment by resouer** [comment]
I think I would like to ping @lavalamp , do you think adding this flag reasonable?

**Comment by resouer** [comment]
@ixdy fixed rebase, please apply label again.

**Comment by ixdy** [comment]
@k8s-bot gci gke e2e test this
@k8s-bot cvm gke e2e test this
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
