### PR TITLE
[OpenStack]Remove the LbaasV1 of OpenStack cloud provider

### PR DESCRIPTION
**Pull request by FengyunPan**
The Neutron LbaasV1 has been declared obsolete, LbaasV2 is a
better choice.
So let's remove the codes of LbaasV1, only support LbaasV2.
xref: #52609
Reference OpenStack doc:
https://docs.openstack.org/mitaka/networking-guide/config-lbaas.html

**Special notes for your reviewer**:
/assign @dims 
/assign @anguslees 

**Release note**:
```release-note
Remove the LbaasV1 of OpenStack cloud provider, currently only support LbaasV2.
```

### CODE REVIEW

**Comment by thockin** [comment]
Assign back to me once it is LGTM'ed and ready for approval.

**Comment by anguslees** [comment]
lgtm on the code.  We haven't given a deprecation warning period, otoh openstack _has_ done so with LBaaSV1 afaik.  I think we should at least mention it in the sig-openstack meeting, and give people a day or two to shout that they still need this for some reason.  If we don't get an objection by then, I'm happy to /lgtm for real.

**Comment by hogepodge** [comment]
At least one large OpenStack user have LBaaSV1 in production, but not in conjunction with K8s. I'd suggest we deprecate for one release then remove.

**Comment by FengyunPan** [comment]
@hogepodge Ok, I'd like to deprecate LBaaSV1 at V1.8, then remove LBaaSV1 after V1.9.
PTAL #52821

**Comment by dims** [comment]
@FengyunPan PR needs rebase

**Comment by dims** [comment]
@FengyunPan Do you want to do this for 1.9 right? please rebase

**Comment by FengyunPan** [comment]
@dims Yes, I will do a rebase soon.

**Comment by FengyunPan** [comment]
/assign @thockin 
Can you please approve this PR? Thank you.

**Comment by FengyunPan** [comment]
ping @thockin
for approve

**Comment by thockin** [comment]
/approve

does this fix  #52609 or is it just related?  If it fixes it, change the first comment to say `fixes  #52609`

**Comment by FengyunPan** [comment]
@thockin It just related to  #52609.

**Pull request merged**
