### PR TITLE
Set Typha replica count to 0 when Calico is not enabled

### PR DESCRIPTION
**Pull request by caseydavenport**
**What this PR does / why we need it**:
A replacement for https://github.com/kubernetes/kubernetes/pull/47624, which turned out not to be the right fix. 

**Which issue this PR fixes**
https://github.com/kubernetes/kubernetes/issues/47622

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by bowei** [comment]
@dchen1107 @kubernetes/kubernetes-release-managers this needs to go into 1.7 milestone

**Comment by dchen1107** [comment]
/lgtm

Also marked this as critical fix since it blocks alpha-feature tests which has raised the priority.

**Comment by mindprince** [comment]
@caseydavenport I think the presubmit failures in this PR are because of the PR and not because of flakes.

**Comment by caseydavenport** [comment]
> I think the presubmit failures in this PR are because of the PR and not because of flakes.

yeah, it does seem that way.  I'm investigating now.  Things seem to work on my local machine.

**Comment by caseydavenport** [comment]
It looks like the nodes aren't registering and thus the "Up" part of the test is failing.

This all works fine locally.  Looking at the kubelet logs for why they might not be available, I see that it doesn't seem to be getting anywhere and is cyclically restarting.  I suspect that's why the nodes aren't coming up, but I'm not sure yet how this PR could be causing that.

**Comment by caseydavenport** [comment]
I think I've figured out what's going on with the failing tests.  Will push a fix shortly.

**Review by rohitagarwal003 — APPROVED** [review]

**Pull request merged**
