### PR TITLE
kubelet: refactor kubelet.Runtimehooks to container.ImagePuller.

### PR DESCRIPTION
**Pull request by yifan-gu**
This PR wraps the runtime hook functions (`ShouldPullImage`, `ReportImagePulling`, `ReportImagePulled`) and `DockerManger.pullImage` to `ImagePuller.PullImage`.
This new function can be called by other container runtimes to pull image and report events, as long as the runtime has implemented `IsImagePresent` and `PullImage` in the runtime interface.

/cc @dchen1107 @vmarmol @yujuhong

### CODE REVIEW

**Comment by a-robinson** [comment]
@k8s-bot ok to test

**Comment by yujuhong** [comment]
@dchen1107, if you are busy, feel free to re-assign to me :)

**Comment by dchen1107** [comment]
LGTM. Please rebase your pr to get this merged.

**Comment by yifan-gu** [comment]
@dchen1107 Rebased :)

**Comment by pmorie** [comment]
I was OOO last week, but this LGTM.

**Pull request merged**
