### PR TITLE
fix magic string for runtime type

### PR DESCRIPTION
**Pull request by andyxning**
**What this PR does / why we need it**:
This PR correct the magic string about container runtime to the constants.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
This PR correct the magic string about container runtime to the constants.
**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by ncdc** [comment]
1.9 is almost ready to be released. I recommend this wait until code freeze on master lifts, and this can then make it in for 1.10.

**Review by feiskyer — APPROVED** [review]
/lgtm

**Comment by andyxning** [comment]
> 1.9 is almost ready to be released. I recommend this wait until code freeze on master lifts, and this can then make it in for 1.10.

SGTM.

**Comment by yujuhong** [comment]
/approve no-issue

This can wait until 1.9 is cut.

**Comment by andyxning** [comment]
@yujuhong As stated in the mailing list, v1.9 has been lifted and master branch is open for v1.10. Could we merge this?

**Comment by yujuhong** [comment]
> @yujuhong As stated in the mailing list, v1.9 has been lifted and master branch is open for v1.10. Could we merge this?

Yes, but there is nothing we need to do since the submit queue should pick this up automatcally

**Comment by andyxning** [comment]
Ping @feiskyer @ncdc @yujuhong for lgtm and approve. :)

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Pull request merged**
