### PR TITLE
Change TTLAfterFinished state to beta in comment

### PR DESCRIPTION
**Pull request by Pingan2017**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
follow #98678 ,graduate TTLAfterFinished to beta in comment

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by xing-yang** [comment]
@Pingan2017  Can you change "kind" from "feature" to "cleanup"?

**Comment by Pingan2017** [comment]
> @Pingan2017 Can you change "kind" from "feature" to "cleanup"?

Changed

**Pull request merged**
