### PR TITLE
kubectl/describe: use function calls to build field selector

### PR DESCRIPTION
**Pull request by jingyuanliang**
Instead of using string concatenation.

#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

Code quality improvement.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

None

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

None

```docs

```

### CODE REVIEW

**Comment by xuzhenglun** [comment]
/priority important-longterm
/assign @eddiezane @soltysh
for approve

**Review by soltysh — APPROVED** [review]
/approve

**Pull request merged**
