### PR TITLE
enable s390x to test containers

### PR DESCRIPTION
**Pull request by jeffdyoung**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
Conformance testing on s390x https://github.com/kubernetes/kubernetes/issues/67721

**Which issue(s) this PR fixes**:

Fixes #
conformance failures on s390x

**Special notes for your reviewer**:
I'm assuming since other s390 containers are being built, that changing these value will automatically build them for s390?

cc: @dims

### CODE REVIEW

**Comment by jeffdyoung** [comment]
Thanks @ixdy! Curious, how long before the containers are built and published? I'm new to the k8s universe, not sure how this works.

**Comment by ixdy** [comment]
currently it requires a googler to manually build and push these images. cc @listx

**Comment by dims** [comment]
/release-note-none
/milestone v1.15

Let's queue it up for when master reopens.

**Comment by mkumatag** [comment]
> currently it requires a googler to manually build and push these images. cc @listx

@ixdy @dims we need to work on opening up this repo in the image promotion and give access to a couple of people to push the images.

**Comment by jeffdyoung** [comment]
If you all need help building any of these containers, I can help. I have access to s390x, aarch64 and ppc64le.

**Comment by mkumatag** [comment]
> If you all need help building any of these containers, I can help. I have access to s390x, aarch64 and ppc64le.

@jeffdyoung its not for building the images, it is about who can push to the repo after building them. Btw: all these images are cross built on amd64 arch.

**Comment by listx** [comment]
> > currently it requires a googler to manually build and push these images. cc @listx
> 
> @ixdy @dims we need to work on opening up this repo in the image promotion and give access to a couple of people to push the images.

@mkumatag There is ongoing work to enable non-googlers to do this (it will probably land in Q3 --- Q2 if I'm optimistic). The groundwork for this is the KEP at https://github.com/kubernetes/k8s.io/issues/157. After the Prow configs have been more or less stabilized for the [promoter tool](https://github.com/kubernetes-sigs/k8s-container-image-promoter), we can turn it "on" for reals for all images created by the community.

**Comment by mkumatag** [comment]
> @mkumatag There is ongoing work to enable non-googlers to do this (it will probably land in Q3 --- Q2 if I'm optimistic). The groundwork for this is the KEP at [kubernetes/k8s.io#157](https://github.com/kubernetes/k8s.io/issues/157). After the Prow configs have been more or less stabilized for the [promoter tool](https://github.com/kubernetes-sigs/k8s-container-image-promoter), we can turn it "on" for reals for all images created by the community.

@listx Good to hear, eager to see that in action :)

**Pull request merged**
