### PR TITLE
Add RunInContainer/ExecInContainer to container Runtime API.

### PR DESCRIPTION
**Pull request by vmarmol**
/cc @dchen1107 @yifan-gu

### CODE REVIEW

**Comment by dchen1107** [comment]
LGTM

**Comment by yifan-gu** [comment]
Are we adding PortForward also? It is also approachable from the kubectl I think.

**Comment by vmarmol** [comment]
@yifan-gu, yes there are a couple of others I'll add soon too.

**Comment by yifan-gu** [comment]
SGTM :)

**Pull request merged**
