### PR TITLE
Automated cherry pick of #13803

### PR DESCRIPTION
**Pull request by justinsb**
Cherry pick of #13803 on release-1.0.

### CODE REVIEW

**Comment by justinsb** [comment]
Suspect a test flake; closing & reopening...

**Comment by justinsb** [comment]
ping :-)

**Comment by dchen1107** [comment]
LGTM

**Comment by dchen1107** [comment]
@justinsb Thanks for fixing. I will leave it to Wasaw folk to merge tonight or I will merge it tomorrow morning. Thanks!

**Comment by wojtek-t** [comment]
e2e test failure is a flake:
"Kubectl client Guestbook application should create and stop a working application"

@k8s-bot test this please

**Comment by wojtek-t** [comment]
e2e failure is a flake:
"Kubectl client Guestbook application should create and stop a working application"

@k8s-bot test this please

**Pull request merged**
