### PR TITLE
upgrade etcd deps to v3.5.7

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
```
-	github.com/form3tech-oss/jwt-go v3.2.3+incompatible // indirect
```

```
-      "github.com/form3tech-oss/jwt-go": [
-        "go.etcd.io/etcd/server/v3"
-      ],
      "github.com/gogo/protobuf": [
-        "github.com/cockroachdb/datadriven",
      ],
      "github.com/pkg/errors": [
-        "github.com/cockroachdb/datadriven",
      ],
```
#### Which issue(s) this PR fixes:

xref https://github.com/kubernetes/kubernetes/issues/114942

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by pacoxu** [comment]
/test pull-kubernetes-unit
for flake

**Comment by pacoxu** [comment]
/cc @dims @liggitt 
for dep update

**Comment by dims** [comment]
This is a win from dependency point of view :)

```
-Direct Dependencies: 210 
-Transitive Dependencies: 235 
-Total Dependencies: 285 
+Direct Dependencies: 209 
+Transitive Dependencies: 234 
+Total Dependencies: 284 
```

/assign @serathius @liggitt 
/lgtm

**Comment by liggitt** [comment]
nice cleanup, thanks!

/approve

**Pull request merged**
