### PR TITLE
Cleanup staticcheck workarounds 

### PR DESCRIPTION
**Pull request by MadhavJivrajani**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:

Staticcheck and golangci-lint were bumped when we needed to make it work with go1.20 (https://github.com/kubernetes/kubernetes/pull/115537). As a part of this, we encountered a false positive in staticcheck (https://github.com/dominikh/go-tools/issues/1365), to mitigate this, we added exception comments. 

The above false positive has been fixed as part of the staticcheck v0.4.3 release, as a result, this PR cleans up the workarounds we put in place earlier.

#### Commit 1:
Bump golangci-lint and staticcheck

#### Commit 2:
Remove previously added exception comments

#### Which issue(s) this PR fixes:
Follow up to https://github.com/kubernetes/kubernetes/pull/115537

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
/assign @dims @pohly

### CODE REVIEW

**Comment by MadhavJivrajani** [comment]
/retest
I don't see any build logs, probably one-off

**Review by pohly — APPROVED** [review]
/lgtm
/approve

**Comment by pohly** [comment]
Several of the Ginkgo linter issues are valid (`gomega.Expect(len(nodes.Items) > 0)`!). Others are recommendations (`gomega.Expect(jobs.Items).To(gomega.HaveLen(0))` -> `BeEmpty`) that shouldn't be enabled in the default golangci-lint.yaml. `gomega.Eventually(ctx, framework.HandleRetry...` looks like a false positive. `HandleRetry` returns a function.

@MadhavJivrajani: do you want me to take over? I can take your commits and combine them with fixes for these issues and a suitable linter config update.

**Comment by MadhavJivrajani** [comment]
Sure @pohly, thank you!
Please cc me in your PR, I'd like to follow along and learn.

**Comment by MadhavJivrajani** [comment]
/close 
Based on above

**Pull request closed without merging**
