### PR TITLE
Upgrade to Docker 1.7.1 by default

### LINKED ISSUE #8918: Verify Kubernetes with Docker 1.7 RC
Looks like the 1.7 RC is out:

https://gist.github.com/vieux/42189ac13129efbadd15

### PR DESCRIPTION
**Pull request by dchen1107**
All e2e tests are passed. I also validate all master components too (Now everything is easier since we register master node too).

Fixed #8918

### CODE REVIEW

**Comment by dchen1107** [comment]
cc/ @zmerlynn

**Comment by zmerlynn** [comment]
Can you not remove the line 106-110 logic? I would eventually like to fall back to ContainerVM docker on GCE, so I'd rather this just be a comment saying something like "overriding docker on master until we figure out a better story for ContainerVM".

**Comment by dchen1107** [comment]
@zmerlynn What is your suggestion on this? Adding those back, and commented them out with a comment?

**Comment by zmerlynn** [comment]
Well, I was initially thinking just to override them to the same thing, but either way.

**Comment by dchen1107** [comment]
@zmerlynn Done, and PTAL? Thanks!

**Comment by zmerlynn** [comment]
LGTM

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Comment by zmerlynn** [comment]
@k8s-bot test this

**Comment by zmerlynn** [comment]
@dchen1107: @k8s-bot doesn't like that :(

**Comment by dchen1107** [comment]
I tested it in my local e2e cluster, and passed. It failed due to the timeout on cluster bringup stage. Still looking into it.

Removed your lgtm label to save oncall some trouble, and will ping you once it is resolved.

**Comment by dchen1107** [comment]
ok to test

**Comment by dchen1107** [comment]
@zmerlynn it turns out the failure was caused by restoring the logic of the line 106-110 from the initial init.sls. Those if/else, etc. statements are always evaluated  even they are commented out. :-(

**Comment by dchen1107** [comment]
ok to test

**Comment by zmerlynn** [comment]
LGTM

**Comment by derekwaynecarr** [comment]
@eparis - do you know if docker 1.7 is out of the testing repo for fedora
21 yet?

**Pull request merged**
