### PR TITLE
Add integration test for resource limits

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Promote resource limits priority function to beta along with a integration test.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
/cc @bsalamat @Huang-Wei 
**Does this PR introduce a user-facing change?**:

```release-note
Promote resource limits priority function to beta
```

### CODE REVIEW

**Review by bsalamat — APPROVED** [review]
/lgtm
/approve

Thanks, @ravisantoshgudimetla

**Review by Huang-Wei — COMMENTED** [review]
/lgtm

But want to confirm that we've decided to merge this (right) after 1.13, right? If so, we'd better put a temporary /hold.

**Comment by ravisantoshgudimetla** [comment]
Thanks @bsalamat and @Huang-Wei for review.

> But want to confirm that we've decided to merge this (right) after 1.13, right? If so, we'd better put a temporary /hold.

That's right, this is for 1.14. We have entered code-slush, without milestone 1.13 label nothing would get merged to master but I think you're right, it's better to have an explict /hold. Also, the integration tests are solid red on this PR. I will look more into them, if this PR is causing it(at this point of time, I think not).

/hold

**Comment by bsalamat** [comment]
@ravisantoshgudimetla What is the status of this PR? Do we still want to pursue it or we should close it?

**Pull request closed without merging**
