### PR TITLE
Update test owners

### PR DESCRIPTION
**Pull request by soltysh**
@nikhiljindal I've noticed you've duplicated the `test_owners.csv` contents in c1c2a12 was that intentional. I'm removing it here, since it's failing `hack/update_owners.py`

### CODE REVIEW

**Comment by soltysh** [comment]
Rebased. @spxtr ptal

**Comment by nikhiljindal** [comment]
Sorry it was unintentional.
It seems to have been fixed on head now.

**Comment by soltysh** [comment]
@nikhiljindal no worries, I've updated this PR with all the current state and added myself to test owners and approvers, any objections merging this?

**Comment by nikhiljindal** [comment]
Test_owners.csv changes LGTM assuming they are auto generated by script.

**Comment by soltysh** [comment]
Yes they are. I'm applying lgtm label based on previous approval.

**Comment by soltysh** [comment]
@k8s-bot kubemark e2e test this

**Comment by soltysh** [comment]
@k8s-bot cri e2e test this

**Comment by soltysh** [comment]
@k8s-bot cvm gce e2e test this

**Comment by soltysh** [comment]
@k8s-bot gce etcd3 e2e test this

**Pull request merged**
