### PR TITLE
Automated cherry pick of #127417: bugfix: endpoints controller track resource version

### PR DESCRIPTION
**Pull request by swetharepakula**
Cherry pick of #127417 on release-1.29.

#127417: bugfix: endpoints controller track resource version

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by aojea** [comment]
same as https://github.com/kubernetes/kubernetes/pull/127452#issuecomment-2359085946

**Comment by swetharepakula** [comment]
Due to the diff between release-1.29 and master, the test was modified slightly to initialize the context and use the util functions that are available in release-1.29. There is no logical difference between the tests.

**Comment by aojea** [comment]
> {Failed;  === RUN   TestPersistentVolumeProvisionMultiPVCs

/test pull-kubernetes-integration

> Kubernetes e2e suite: [It] [sig-node] Pods should run through the lifecycle of Pods and PodStatus [Conformance] expand_less	

/test pull-kubernetes-conformance-kind-ga-only-parallel

/lgtm
/approve
/kind bug

**Comment by swetharepakula** [comment]
> === FAIL: test/integration/volume TestPersistentVolumeProvisionMultiPVCs (unknown)

/test pull-kubernetes-integration

**Review by Verolop — COMMENTED** [review]
/lgtm

**Pull request merged**
