### PR TITLE
add azurefile protocol  parameter in azure cloud provider lib

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR add azurefile protocol  field protocal field in azure cloud provider lib, would support NFS in Azure File CSI driver.
Note: there is no plan to support NFS in in-tree driver, this PR just updates the lib used by CSI driver.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
none
```

/assign @feiskyer 
/priority important-soon
/sig cloud-provider
/area provider/azure

### CODE REVIEW

**Comment by andyzhangx** [comment]
/hold
```
Jun 20 13:37:19.402: INFO: At 2020-06-20 13:32:17 +0000 UTC - event for pvc-brrln: {persistentvolume-controller } ProvisioningFailed: Failed to provision volume with StorageClass "azurefile-4728-kubernetes.io-azure-file-dynamic-sc-nsnjn": failed to create share kubetest-ffc47bc3-b2f4-pvc-5f26c10f-89c6-4b86-ae83-8b574acc9672 in account fac6fa735da26449d9ce565: storage.FileSharesClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="FeatureUnavailableInLocation" Message="A feature was requested which is not yet available in this location."
```

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Pull request merged**
