### PR TITLE
added OpenStack instructions to coreos multinode cluster document.  C…

### PR DESCRIPTION
**Pull request by vallard**
Resolves issue #12587

### CODE REVIEW

**Comment by erictune** [comment]
lgtm, thanks for the contribution.

**Comment by brendandburns** [comment]
Thanks for the contribution.  You need to run:

`./hack/update-generated-docs.sh`

Thanks!

**Comment by vallard** [comment]
ah, didn't know about the hack.  Thanks for helping me out!

**Comment by vallard** [comment]
Is there anything more I need to do to get this pull request merged?

**Comment by mbforbes** [comment]
Two LGTMs and CI seems happy, so LGTM. Assigning to merger.

**Pull request merged**
