### PR TITLE
Replace unstructured conversion with simple json-iterator conversion

### PR DESCRIPTION
**Pull request by smarterclayton**
The unstructured benchmarks incorrectly charged setup of objects to the benchmark. While fixing that I noticed how bad unstructured was now (Go json marsha/unmarshal has substantially improved since 1.9 in this area). json-iterator to data and then decoding is faster than the current implementation. This currently uses Fastest to decode but has several unit test failures which need to be investigated.

Before:

```
BenchmarkToUnstructured-12                 	   10000	    194565 ns/op	   57428 B/op	     906 allocs/op
BenchmarkFromUnstructured-12               	   10000	    205167 ns/op	   47491 B/op	     796 allocs/op
```

After (not quite equivalent to raw, because we need to take into account correctness of output):

```
BenchmarkToUnstructured-12                 	   30000	     48740 ns/op	   20750 B/op	     440 allocs/op
BenchmarkFromUnstructured-12               	   50000	     36686 ns/op	   12790 B/op	     246 allocs/op
```

@liggitt

/kind bug

```release-note
Improve the performance of some conversion significantly.
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
This is actually ready for review.

**Comment by liggitt** [comment]
with the fixed up benchmark tests that correctly assign allocs, I'm seeing this:

before:
```
BenchmarkToUnstructured-8                	   30000	     59201 ns/op	   14110 B/op	     221 allocs/op
BenchmarkFromUnstructured-8              	   30000	     52846 ns/op	    6435 B/op	     185 allocs/op
```

after:
```
BenchmarkToUnstructured-8                	   20000	     53919 ns/op	   20193 B/op	     439 allocs/op
BenchmarkFromUnstructured-8              	   30000	     42873 ns/op	   12310 B/op	     245 allocs/op
```

run time is better, but allocs increased 40-90%

**Comment by smarterclayton** [comment]
Yeah, seeing this to.  Will split the benchmark out into #73973 and then come back to this if it really helps.

**Pull request closed without merging**
