### PR TITLE
Extend the timeout for the total integration test.

### LINKED ISSUE #19248: integration flake: timeouts in kubernetes-test-go-release-1.1
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-test-go-release-1.1/2055

I can't see anything immediately wrong, so it may be an honest timeout, i.e. solution would be to increase it.

We need an owner for integration tests in general...
@brendandburns @thockin @davidopp @dchen1107 @ixdy @bgrant0607

### PR DESCRIPTION
**Pull request by gmarek**
Fixes #19248 

cc @brendandburns @ixdy

### CODE REVIEW

**Comment by ixdy** [comment]
noting for linkage: cherry-pick of #14802.

**Comment by gmarek** [comment]
@k8s-bot unit test this

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by gmarek** [comment]
@k8s-bot test this

**Comment by gmarek** [comment]
ERROR: Error fetching remote repo 'origin'...
@k8s-bot unit test this

**Comment by gmarek** [comment]
@k8s-bot unit test this

**Pull request merged**
