### PR TITLE
Fix unit tests that need openstack

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:
Currently the unit tests that depend that they be on running inside an openstack vm fail as no one seem to have run them for a while.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
ref #56437

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
Here's what the output when running from my mac

```
[dims@dims-mac 14:03] ~/go/src/k8s.io/kubernetes ⟩ go test -v k8s.io/kubernetes/pkg/cloudprovider/providers/openstack
=== RUN   TestParseMetadata
--- PASS: TestParseMetadata (0.00s)
=== RUN   TestRoutes
--- SKIP: TestRoutes (0.75s)
	openstack_routes_test.go:41: router-id is empty. skipping test
=== RUN   TestReadConfig
--- PASS: TestReadConfig (0.00s)
=== RUN   TestToAuthOptions
--- PASS: TestToAuthOptions (0.00s)
=== RUN   TestCheckOpenStackOpts
--- PASS: TestCheckOpenStackOpts (0.00s)
=== RUN   TestCaller
--- PASS: TestCaller (0.00s)
=== RUN   TestNodeAddresses
--- PASS: TestNodeAddresses (0.00s)
	openstack_test.go:362: addresses is [{InternalIP 10.0.0.31} {InternalIP 10.0.0.32} {ExternalIP 2001:4800:780e:510:be76:4eff:fe04:84a8} {ExternalIP 2001:4800:790e:510:be76:4eff:fe04:82a8} {ExternalIP 50.56.176.35} {ExternalIP 50.56.176.36} {ExternalIP 50.56.176.99}]
=== RUN   TestNewOpenStack
--- PASS: TestNewOpenStack (0.79s)
=== RUN   TestLoadBalancer
--- PASS: TestLoadBalancer (2.44s)
	openstack_test.go:450: Trying LBVersion = 'v2'
	openstack_test.go:450: Trying LBVersion = ''
=== RUN   TestZones
--- PASS: TestZones (0.00s)
=== RUN   TestVolumes
--- PASS: TestVolumes (34.37s)
	openstack_test.go:523: Volume (5dc286af-1dbd-41a9-972e-d78fe6975c54) created
	openstack_test.go:65: Volume (5dc286af-1dbd-41a9-972e-d78fe6975c54) status changed to available after 30 seconds
	openstack_test.go:529: Cannot find instance id: error fetching http://169.254.169.254/openstack/2012-08-10/meta_data.json: Get http://169.254.169.254/openstack/2012-08-10/meta_data.json: dial tcp 169.254.169.254:80: i/o timeout - perhaps you are running this test outside a VM launched by OpenStack
	openstack_test.go:558: Volume (5dc286af-1dbd-41a9-972e-d78fe6975c54) deleted
=== RUN   TestInstanceIDFromProviderID
--- PASS: TestInstanceIDFromProviderID (0.00s)
PASS
ok  	k8s.io/kubernetes/pkg/cloudprovider/providers/openstack	38.414s
```

**Review by FengyunPan — APPROVED** [review]

**Comment by FengyunPan** [comment]
LGTM, I have tested too.
/approve

**Comment by dims** [comment]
@enisoc @jdumars - can we please mark this for 1.9? it just updates unit tests for openstack

**Review by anguslees — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
@idvoretskyi can you please "/approve no-issue" and apply the milestone tag?

**Pull request merged**
