### PR TITLE
use subtest for table units (pkg/scheduler/internal/cache)

### PR DESCRIPTION
**Pull request by eloyekunle**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Update scheduler's unit table tests to use subtest

**Special notes for your reviewer**:
Breaks up PR: #63281
Original Issue: #63267
Original PR: https://github.com/kubernetes/kubernetes/pull/63708

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```

### CODE REVIEW

**Review by draveness — COMMENTED** [review]
Can you cherry-pick related changes into one PR?

**Comment by eloyekunle** [comment]
@draveness Yes, just that the original PR at https://github.com/kubernetes/kubernetes/pull/63281 was broken down in favour of package-level PRs and that's what I've tried to do here.

**Comment by eloyekunle** [comment]
Closing because I'm merging this PR into #81356.

/close

**Pull request closed without merging**
