### PR TITLE
Fix lint errors in cmd package (see 68026)

### PR DESCRIPTION
**Pull request by jeffhajewski**
**What this PR does / why we need it**:
Fixes linting issues in `cmd` package

**Which issue(s) this PR fixes**:
Fix part of tracking issue #68026 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
thanks for the PR!
LGTM
/ok-to-test

**Comment by j-haj** [comment]
Removed `cmd/hypercube` from `hack/.golint_failures`

/retest

**Comment by j-haj** [comment]
`pull-kubernetes-e2e-kops-aws` looks flaky and `pull-kubernetes-kubemark-e2e-gce-big` seems to be recently failing. Neither of the made changes should impact these failures. I can retest when things look like they've become more stable.

**Comment by j-haj** [comment]
Rebased.

/retest

**Comment by j-haj** [comment]
@yue9944882 looks like the LGTM tag got dropped after the rebase. Is there a way to rebase without losing this label (for future reference).

Thanks!

**Comment by yue9944882** [comment]
/lgtm

sure. yw.

**Comment by j-haj** [comment]
@lavalamp ping

**Comment by shubheksha** [comment]
@j-haj, currently there is a code freeze due to the 1.12 release. Your PR will be merged once it's lifted towards the end of the September.

**Pull request closed without merging**
