### PR TITLE
Fix usage priority fraction in priorities e2e test

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
As of now, we are summing up all the requests for pods running on the node while computing fraction without checking the ceiling value for the fraction, as a result we are noticing values that are going beyond 1 for `cpuFraction` and `memFraction`, while this is not a problem when all the pods consume less that what we have on the node, this will be a problem when we are oversubscribing or having too many best effort pods.

/cc @bsalamat @Huang-Wei 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ravisantoshgudimetla** [comment]
At a higher level, the problem seems to be with way we are using `createBalancedPodsForNodes`(https://github.com/kubernetes/kubernetes/blob/484043a6d15973e20e35405a3acab862bc75ad5f/test/e2e/scheduling/priorities.go#L260), we are creating pods here https://github.com/kubernetes/kubernetes/blob/484043a6d15973e20e35405a3acab862bc75ad5f/test/e2e/scheduling/priorities.go#L300 but based on the values including besteffort pods which won't be accounted for while scheduling.(https://github.com/kubernetes/kubernetes/blob/484043a6d15973e20e35405a3acab862bc75ad5f/pkg/scheduler/algorithm/predicates/predicates.go#L794-L799)

**Comment by SataQiu** [comment]
Thanks @ravisantoshgudimetla 🤣 
But you need to run `./hack/update-gofmt.sh` to format the code firstly.

**Review by bsalamat — COMMENTED** [review]
Thanks @ravisantoshgudimetla for the fix. Every fix should come with a test that covers it. Could you please add a test that ensures the fractions never go higher than 1?

**Comment by bsalamat** [comment]
NVM my previous comment. I thought this PR changes the implementation the priority function. Please change the title and the PR description to reflect that it is fixing a test.

**Review by bsalamat — COMMENTED** [review]
/lgtm

**Comment by ravisantoshgudimetla** [comment]
/hold

I need to fix gofmt

**Comment by ravisantoshgudimetla** [comment]
I am waiting to see, if there are any corner cases, I am missing out. Will update this again, if the tests won't pass here:

https://github.com/openshift/origin/pull/22470

**Comment by ravisantoshgudimetla** [comment]
openshift/origin#22470  has passed for few runs, the remaining seem to be infrastructure flakes. So, @bsalamat can you please re-lgtm this PR?

**Pull request merged**
