### PR TITLE
Fix golint for openstack and cinder packages

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:
Fix golint for openstack and cinder packages

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by dims** [comment]
/assign @cblecker 

@cblecker a simple cleanup for the 2 openstack related packages. PTAL

**Comment by cblecker** [comment]
/approve
Looks like some failing tests still in the openstack provider

**Comment by dims** [comment]
@cblecker y, those cropped up with the rebase. fixing now.

**Comment by dims** [comment]
@FengyunPan @NickrenREN can you PTAL and lgtm?

**Pull request merged**
