### PR TITLE
fixtodo:Move ServeHostnameService constants and default settings to service_util.go

### PR DESCRIPTION
**Pull request by hanxiaoshuai**
**What this PR does / why we need it**:
fixtodo:Move ServeHostnameService constants and default settings to service_util.go
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by hanxiaoshuai** [comment]
cc @grayluck

**Comment by grayluck** [comment]
I am not a member of kubernetes (yet, but I should be shortly). But let me try.
/ok-to-test

**Comment by grayluck** [comment]
No worry I will assign someone to help.
/assign @MrHohn

**Review by MrHohn — APPROVED** [review]
/lgtm

**Comment by deads2k** [comment]
I don't think we should expose this more broadly unless there is a need.  I like the smallest scope possible.  

Unless there is somewhere else hardcoding these for exactly the same purpose, I'd recommend deleting the TODO instead.

/hold

**Comment by grayluck** [comment]
+1 to that. Let's see if we really need to share these constants before moving it to util.

**Comment by hanxiaoshuai** [comment]
cc @grayluck @deads2k I remove the TODO. Thanks for your review

**Pull request merged**
