### PR TITLE
Add conversion-gen between extensions and apps

### LINKED ISSUE #49738: Deployment is missing from apps/v1beta generated conversion code
https://github.com/kubernetes/kubernetes/blob/v1.8.0-alpha.2/pkg/apis/apps/v1beta1/zz_generated.conversion.go does not have Deployments 

This can be fixed by adding the following line to https://github.com/kubernetes/kubernetes/blob/v1.8.0-alpha.2/pkg/apis/apps/v1beta1/doc.go
```go
// +k8s:conversion-gen=k8s.io/kubernetes/pkg/apis/extensions
```
I didn't find this comment documented anywhere, though.

This means that Deployment conversion has not worked correctly as expected since the bump of apps/v1beta1. We may need to cherry pick fixes. 

A bigger underlying issue is #49734, cross-group conversions aren't covered by roundtrip tests. 

@kubernetes/sig-apps-bugs

### PR DESCRIPTION
**Pull request by janetkuo**
Fixes #49738

Generate conversion code for apps/v1beta1 <--> extensions and apps/v1beta2 <--> extensions

@kubernetes/sig-apps-api-reviews @kubernetes/sig-api-machinery-misc

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Can we merge this ***after*** we have the proper roundtrip tests?

**Comment by janetkuo** [comment]
@caesarxuchao would it be okay if I add this hack before the real fix is in?https://github.com/kubernetes/kubernetes/issues/49734#issuecomment-318482221

Several PRs depend on this one

**Comment by liggitt** [comment]
is there a reason this is going in the opposite direction of the other cross-group conversions?

https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/v1beta1/doc.go#L19-L21

**Comment by liggitt** [comment]
@kubernetes/api-reviewers

**Comment by janetkuo** [comment]
> is there a reason this is going in the opposite direction of the other cross-group conversions?

@liggitt no, I added it based on @caesarxuchao's suggestion, and I didn't find any document about how this comment should be used. Do you know where it's documented?

**Comment by caesarxuchao** [comment]
> is there a reason this is going in the opposite direction of the other cross-group conversions?
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/v1beta1/doc.go#L19-L21

I think /extensions/v1beta1/doc.go is wrong. I removed those tags and ran `make clean && make generated_files`, there is no change.

**Comment by janetkuo** [comment]
Just did a rebase because ReplicaSet was bumped to apps too

**Comment by sttts** [comment]
@janetkuo I have updated https://github.com/kubernetes/kubernetes/pull/49748. Here is a test run: https://gist.github.com/sttts/99acd67797f430bcddbb6251b4af36b2. There are a number of "no conversion" lines and a number of error arond NetworkPolicies. Could you take a look at them? They all look like related to the extensions apigroup.

**Comment by caesarxuchao** [comment]
The networking/v1 needs a similar fix to its doc.go

**Comment by janetkuo** [comment]
@sttts I saw several "no conversion" errors that are covered by this PR, however, the failure such as "no conversion from apps_internal DaemonSet to apps/v1beta2" is expected -- DaemonSet uses extensions internal version instead of apps, and so as Deployment and ReplicaSet.

**Comment by sttts** [comment]
> The networking/v1 needs a similar fix to its doc.go

@caesarxuchao not sure about this. There are manually written conversions already from extensions/internal to networking/v1. Hence, they pass the check in https://github.com/kubernetes/kubernetes/pull/49748. But, the line https://github.com/sttts/kubernetes/blob/3d4a396810468c2bec7e241d7297f24e5a2ca81a/staging/src/k8s.io/apimachinery/pkg/api/testing/roundtrip/roundtrip.go#L300-L300 tries to convert a `extensions/internal` object to the target version networking/v1. This fails at https://github.com/sttts/kubernetes/blob/5ea58748f10d5d9333df70d1d24881af5586ba66/staging/src/k8s.io/apimachinery/pkg/runtime/scheme.go#L509 because the GroupVersion versioner only knows about conversions from it's own group (compare https://github.com/sttts/kubernetes/blob/6a4d5cd7cc58e28c20ca133dab7b0e9e56192fe3/staging/src/k8s.io/apimachinery/pkg/runtime/schema/group_version.go#L176).

Here is the trace if anybody want to understand this further:

bildschirmfoto 2017-07-31 um 12 21 33

It seems that the apps/internal group just reuses the extensions types. Then the upper problem does not occur. I guess we have to do the same with networking. Two copies of internal types and shared external types does not work well with our encoders /cc @janetkuo @liggitt wdyt?

**Comment by caesarxuchao** [comment]
```
	roundtrip.go:160: round tripping apps/__internal, Kind=DaemonSet
	roundtrip.go:227: 	round tripping to extensions/v1beta1, Kind=DaemonSet via json
	roundtrip.go:224: 	no conversion to apps/v1beta2, Kind=DaemonSet
```

@janetkuo @sttts i didn't look at the code carefully, but the test is using the type to search for a conversion function, given than apps/_internal#DaemonSet is the [same type](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/register.go#L50) as extension/_internal#DaemonSet, so i expected no error here.

**Comment by caesarxuchao** [comment]
> It seems that the apps/internal group just reuses the extensions types. Then the upper problem does not occur. I guess we have to do the same with networking. Two copies of internal types and shared external types does not work well with our encoders

Agree. @thockin do you know why there are two internal versions of networkpolicy ([extensions](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/extensions/types.go#L1096) and [networking](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/networking/types.go#L29)? I remember we discussed with @lavalamp on this issue and the conclusion was to keep only one internal version of networkpolicy.

**Comment by sttts** [comment]
> so i expected no error here.

@caesarxuchao that was from my original gist? Here is current run, error is gone. Only the networking conversions error due to the two internal types. https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49748/pull-kubernetes-unit/43752/

**Comment by caesarxuchao** [comment]
@sttts thanks for the update. @thockin @danwinship can we remove one of the internal version of the networking group (https://github.com/kubernetes/kubernetes/pull/49751#issuecomment-319531126)?

**Comment by caesarxuchao** [comment]
@smarterclayton could you approve this PR? Thanks.

**Review by kow3ns — APPROVED** [review]

**Comment by janetkuo** [comment]
Would someone approve this? @kubernetes/sig-api-machinery-api-reviews @kubernetes/sig-apps-api-reviews

**Comment by danwinship** [comment]
> Agree. @thockin do you know why there are two internal versions of networkpolicy (extensions and networking? I remember we discussed with @lavalamp on this issue and the conclusion was to keep only one internal version of networkpolicy.

There is a bug open about removing the copy in extensions (#46626), but it got complicated

**Comment by caesarxuchao** [comment]
I'm manually approving this. The PR does not change the API, it's fixing a bug in the apimachinery.

**Pull request merged**
