### PR TITLE
cleanup: Remove_unnecessary_Sprintfs

### PR DESCRIPTION
**Pull request by gaurav1086**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
cleanup unnecessary sprintfs
**Which issue(s) this PR fixes**:

Fixes #
N/A
**Special notes for your reviewer**:
N/A
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/lgtm
/ok-to-test
/priority backlog

**Comment by neolit123** [comment]
@gaurav1086 
please see the cause for CI failures:
> test/integration/apiserver/max_request_body_bytes_test.go:21:2: "fmt" imported but not used (compile)

**Comment by gaurav1086** [comment]
@neolit123 thanks for pointing out. Changes done.

**Comment by neolit123** [comment]
please keep the commits squashed to one.

**Review by SataQiu — APPROVED** [review]
Thanks for doing this @gaurav1086 
/lgtm
/approve

**Pull request merged**
