### PR TITLE
[Federation] Add unit tests for `kubefed init`'s certificate generator.

### PR DESCRIPTION
**Pull request by madhusudancs**
Please review only the last commit here. This is based on PR #35594 which will be reviewed independently.

These are a subset of unit tests for code introduced in PR #35594

Design Doc: PR #34484

cc @kubernetes/sig-cluster-federation @quinton-hoole

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35856)

### CODE REVIEW

**Comment by nikhiljindal** [comment]
last commit LGTM, thx! :)

**Comment by madhusudancs** [comment]
@k8s-bot ok to test

**Comment by madhusudancs** [comment]
@k8s-bot verify test this

**Comment by madhusudancs** [comment]
@k8s-bot verify test this

**Comment by madhusudancs** [comment]
@k8s-bot verify test this

**Comment by madhusudancs** [comment]
Adding `retest-not-required` label because it only touches federation.

**Pull request merged**
