### PR TITLE
Fix vagrant client authorization.

### PR DESCRIPTION
**Pull request by BenTheElder**
Fixes https://github.com/GoogleCloudPlatform/kubernetes/issues/9359

### CODE REVIEW

**Comment by BenTheElder** [comment]
This just changes some of the scripts in `cluster/vagrant/` so it shouldn't need building or testing, and I can verify that at least on boot2docker + latest vagrant on OSX this works correctly.

**Comment by BenTheElder** [comment]
We still need to handle distributing certificates so that we can stop setting `insecure-skip-tls-verify` but as discussed in https://github.com/GoogleCloudPlatform/kubernetes/pull/9543 it looks like the plan is to do this through secrets which I'm not yet familiar with. Otherwise if simply copying the host copy of the CA cert to the minions is fine I can add code to `scp` the CA cert to the minions back to this.
 The way I was doing it was kind of hacky and added it to the system cert bundle then restarted the kube* services so I removed it since my original goal was just to get the vagrant cluster back to a functioning state where the minions could talk to master.

**Comment by derekwaynecarr** [comment]
Thank you for the help in updating this.  Will test this afternoon.

**Comment by BenTheElder** [comment]
YW, thanks for testing it out. I'm reliant on this for running integration tests on newer code.

**Comment by derekwaynecarr** [comment]
Worked well.  Thanks again!

**Comment by derekwaynecarr** [comment]
Can one of the Googlers on-call merge this?  I am getting a number of issues opened, and this fixes the environment again.  Thanks!

**Comment by karlkfi** [comment]
After merging this branch with master locally I still am unable to get vagrant up. It just loops forever on `Validating master`.

@derekwaynecarr said the apiserver is running in docker, but `sudo docker ps` on the master shows no containers running. The kublet is running on the minions, but they can't talk to the apiserver because it doesn't seem to be running...

**Comment by BenTheElder** [comment]
Huh. @karlkfi I just switched back to this branch and ran:
 `make clean && make quick-release && go run hack/e2e.go -v -up`
and everything completed smoothly. Further:
 ````
$ vagrant ssh master
Last login: Tue Feb 24 20:32:10 2015 from 10.0.2.2
[vagrant@kubernetes-master ~]$ sudo docker ps
CONTAINER ID        IMAGE                                                                               COMMAND                CREATED             STATUS              PORTS               NAMES
ae976d85e182        gcr.io/google_containers/etcd:2.0.9                                                 "/usr/local/bin/etcd   5 minutes ago       Up 5 minutes                            k8s_etcd-container.671e58e7_etcd-server-kubernetes-master_default_d1c3a1802080044d7f9fd4c0eb1fc6ac_9bfeb84c                        
e9a0c0e5e3c6        gcr.io/google_containers/kube-scheduler:203736793cfd1794966bbada1a81198b            "/bin/sh -c '/usr/lo   5 minutes ago       Up 5 minutes                            k8s_kube-scheduler.69d62403_kube-scheduler-kubernetes-master_default_6819b0133b97580eae2e484df2b436a9_91ddfb9b                     
9e5c5394ff8a        gcr.io/google_containers/kube-controller-manager:eff38a79afea58cff698a0806debda79   "/bin/sh -c '/usr/lo   5 minutes ago       Up 5 minutes                            k8s_kube-controller-manager.5a8b601d_kube-controller-manager-kubernetes-master_default_08305fc2eb73416416822b68a5d0e7ca_f37788aa   
85cdf882b291        gcr.io/google_containers/kube-apiserver:278df23932d4c72c2017d15c17c0bc8c            "/bin/sh -c '/usr/lo   5 minutes ago       Up 5 minutes                            k8s_kube-apiserver.ea5f1afb_kube-apiserver-kubernetes-master_default_62c95767d7dc6577c185a75bfb27b3d0_35e07380                     
26ba615f02a6        gcr.io/google_containers/pause:0.8.0                                                "/pause"               5 minutes ago       Up 5 minutes                            k8s_POD.e4cc795_kube-scheduler-kubernetes-master_default_6819b0133b97580eae2e484df2b436a9_4a018c27                                 
a0594060d53c        gcr.io/google_containers/pause:0.8.0                                                "/pause"               5 minutes ago       Up 5 minutes                            k8s_POD.e4cc795_kube-controller-manager-kubernetes-master_default_08305fc2eb73416416822b68a5d0e7ca_6893573e                        
4071db637f75        gcr.io/google_containers/pause:0.8.0                                                "/pause"               5 minutes ago       Up 5 minutes                            k8s_POD.e4cc795_kube-apiserver-kubernetes-master_default_62c95767d7dc6577c185a75bfb27b3d0_0c8bdf27                                 
e9a528647a28        gcr.io/google_containers/pause:0.8.0                                                "/pause"               5 minutes ago       Up 5 minutes                            k8s_POD.e4cc795_etcd-server-kubernetes-master_default_d1c3a1802080044d7f9fd4c0eb1fc6ac_1a1e4961                                    
````

**Comment by karlkfi** [comment]
Try rebasing against master. It's possible the problem is in master and not these changes.

**Comment by BenTheElder** [comment]
I ran:
`git fetch upstream`
`git rebase upstream/master`
`make clean && make quick-release && go run hack/e2e.go -v -up`
Same results as last time, ssh to master shows similar output.

**Comment by JasonGiedymin** [comment]
:+1: Ran e2e and `Cluster validation succeeded`.

**Comment by JasonGiedymin** [comment]
cc @quinton-hoole @ArtfulCoder - would be great to see this progress to fix master

**Comment by karlkfi** [comment]
Ok, sorry for the alarm. Looks like PEBCAK. My built release was stale.
I have now confirmed that the cluster comes up correctly on this branch.
I'll be running full e2e against it later.

**Comment by derekwaynecarr** [comment]
This still looks good to me and is labeled as such.  Would love a merge from someone on Google side as community committers are not merging as we close down :-)

**Comment by fabioy** [comment]
Seems to affect Vagrant only. Merging. Thanks.

**Pull request merged**
