### PR TITLE
add test and fix typo in daemoncontroller

### PR DESCRIPTION
**Pull request by zjj2wry**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot ok to test

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by zjj2wry** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by janetkuo** [comment]
The change looks good but the test (sort of) dup with #46695

**Comment by gyliu513** [comment]
@janetkuo I think that they are different, this PR test is focusing on the test of `AddNode` API but in @46695, the new added test cases is testing the case of running daemonset on multiple nodes: some can run the daemonset while some cannot, comments? Thanks.

**Review by janetkuo — APPROVED** [review]

**Comment by lukaszo** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Pull request merged**
