### PR TITLE
update RequireKubeConfig default value

### PR DESCRIPTION
**Pull request by xilabao**

### CODE REVIEW

**Comment by liggitt** [comment]
Need to sweep for kubelet invocations that are not wanting to use the API server (self hosted and bootstrap cases, etc), and explicitly opt out of using the kubeconfig

**Comment by xilabao** [comment]
@liggitt PTAL

**Comment by xilabao** [comment]
@smarterclayton PTAL

**Comment by liggitt** [comment]
hold until https://github.com/kubernetes/kubernetes/pull/40050#issuecomment-274117412 is resolved

**Pull request closed without merging**
