### PR TITLE
Remove last traces of old registry name

### PR DESCRIPTION
**Pull request by dims**
Change-Id: Ie1a5feaba20736d491242b4c971423c0a624f383

**What this PR does / why we need it**:

Close a TODO item updated in 89ceb7ef4667c35cbfcc89b7b74f1750044cbca8 to get rid of the old `gcr.io/google-containers` repo

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ixdy** [comment]
/lgtm

I think the cross failure is a (racy?) bug from #69368, and I'll work on a fix.

**Comment by dims** [comment]
@ixdy thanks! i've filed https://github.com/kubernetes/kubernetes/pull/69817 to help in the mean time.

**Comment by ixdy** [comment]
/approve
too

**Pull request merged**
