### PR TITLE
update vendoring of kustomize

### PR DESCRIPTION
**Pull request by Liujingfang1**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
update vendor of kustomize from 2.0.1 to 2.0.3

**Does this PR introduce a user-facing change?**:
no

```release-note
NONE
```

### CODE REVIEW

**Comment by monopole** [comment]
/lgtm

This PR is mostly generated.  There's some small changes at vendored code call points, which look right to me.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
