### PR TITLE
Automated cherry pick of #88006: Unregister csiplugin even if socket path is gone

### LINKED ISSUE #87282: kubelet can't unregister csiplugin after csiplugin pod is deleted from node
**What happened**:
```
Error: "UnregisterPlugin error -- dial failed at socket /var/lib/kubelet/plugins_registry/xxx-reg.sock, err: failed to dial socket /var/lib/kubelet/plugins_registry/xxx-reg.sock, err: context deadline exceeded"
```

Before deleting csiplugin pod, we will firstly remove register unix domain socket </var/lib/kubelet/plugins_registry/xxx-reg.sock>, which will trigger kubelet unregister csiplugin.
After we update our k8s cluster from v1.14.3 to v1.16.3, I noticed that above error logs, meanwhile `kubectl get csinode node-xxx`, I can see old plugin in spec.drivers list but it should not(The error does not happen in v1.14.3).

**What you expected to happen**:
csiplugin can be unregistered by kubelet exactly，and there are no error logs.

**How to reproduce it (as minimally and precisely as possible)**:
deploy csinode daemonset as describing at [here](https://github.com/kubernetes-csi/node-driver-registrar#example)

**Anything else we need to know?**:
maybe this issue was imported by the [commit](https://github.com/kubernetes/kubernetes/commit/5e185544421d5504b0fe2ae32c8ebfb3000a1224)
And after reading code implementation, I find kubelet will dial unix domain socket <var/lib/kubelet/plugins_registry/xxx-reg.sock> when it's trigger by removing xxx-reg.sock, which is confusing

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by tedyu**
Cherry pick of #88006 on release-1.18.

#88006: Unregister csiplugin even if socket path is gone

/kind bug

Fixes #87282

```release-note
NONE
```

### CODE REVIEW

**Comment by tedyu** [comment]
Still trying to figure out what caused the timeout.
From https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/89698/pull-kubernetes-kubemark-e2e-gce-big/1246181531039305728/artifacts/e2e-89698-ac87c-minion-group-1tnh/kubelet.log , there were warnings in the form:
```
W0403 21:37:01.707746    1328 watcher.go:87] Error while processing event ("/sys/fs/cgroup/blkio/kubepods/burstable/pod86b8a9f0-3d38-4928-a1c7-e7e6bfb6203f/45ac83d3e9ab9d735018790389c5c4d9cc066ae553e8e5a06e08cb0a3e8677cf": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/blkio/kubepods/burstable/pod86b8a9f0-3d38-4928-a1c7-e7e6bfb6203f/45ac83d3e9ab9d735018790389c5c4d9cc066ae553e8e5a06e08cb0a3e8677cf: no such file or directory
```
I will check more logs.

**Comment by saad-ali** [comment]
/hold

I have some concerns about https://github.com/kubernetes/kubernetes/pull/88006
Will comment there.

**Comment by tedyu** [comment]
The additional comments have been addressed by #89934

@saad-ali 
Can this be backported now ?

**Comment by saad-ali** [comment]
Once https://github.com/kubernetes/kubernetes/pull/89934 is merged, close this PR and open a new cherry pick that picks both https://github.com/kubernetes/kubernetes/pull/88006 and https://github.com/kubernetes/kubernetes/pull/89934 together.

**Pull request closed without merging**
