### PR TITLE
Updating hack/gen-swagger-doc to generate docs for extension resources

### PR DESCRIPTION
**Pull request by caesarxuchao**
output file structure:

```
docs/api-reference:
├── extensions
│   └── v1beta1
│       ├── definitions.html
│       ├── operations.html
└── v1
    ├── definitions.html
    ├── operations.html
```

caveats: definitions.html for extensions/v1beta1 contains models for v1 types that are referenced by extensions/v1beta1 types. And the inclusion is recursive.

supersede #15757
fix #13833

@nikhiljindal @bgrant0607

### CODE REVIEW

**Comment by caesarxuchao** [comment]
To view the html:

https://htmlpreview.github.io/?https://raw.githubusercontent.com/caesarxuchao/kubernetes/gen-docs-extensions/docs/api-reference/extensions/v1beta1/definitions.html

https://htmlpreview.github.io/?https://github.com/caesarxuchao/kubernetes/blob/gen-docs-extensions/docs/api-reference/extensions/v1beta1/operations.html

https://htmlpreview.github.io/?https://raw.githubusercontent.com/caesarxuchao/kubernetes/gen-docs-extensions/docs/api-reference/v1/definitions.html

https://htmlpreview.github.io/?https://raw.githubusercontent.com/caesarxuchao/kubernetes/gen-docs-extensions/docs/api-reference/v1/operations.html

**Comment by nikhiljindal** [comment]
If I click on a v1beta1 resource in v1beta operations.html, it does not go to the definitions file.
It tries to find that resource in operations.html itself.

**Comment by caesarxuchao** [comment]
@nikhiljindal those links work correctly locally. If you take a look at the source file, those links are:
```
<a href="definitions.html#_v1beta1_job">
```
It seems it's the htmlpreview website rewriting the hypelinks...

**Comment by caesarxuchao** [comment]
Those links are broken if you view the operations.html in our HEAD using htmlpreview:

https://htmlpreview.github.io/?https://raw.githubusercontent.com/kubernetes/kubernetes/master/docs/api-reference/operations.html

I guess what we care more about the webpage at k8s.io. These files should generate correct webpage there.

**Comment by caesarxuchao** [comment]
@nikhiljindal may I get the lgtm?

**Comment by nikhiljindal** [comment]
Thanks for the explanation.
LGTM.
Remember to cherrypick this. I guess you will have to run versionize-docs.sh to replace HEAD by v1.1.0 in these docs?

**Comment by nikhiljindal** [comment]
cc @RichieEscarez @MikeJeffrey

**Comment by nikhiljindal** [comment]
We moved operations and definitions files, but didnt update docs that are still pointing to their old location.
Link in https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_patch.md, for example, is now broken.
@caesarxuchao Can you please send a PR to update docs?

We really need https://github.com/kubernetes/kubernetes/issues/15916 to flag broken links!

**Pull request merged**
