### PR TITLE
The remaining API changes for PodDisruptionBudget.

### PR DESCRIPTION
**Pull request by mml**
It's mostly the boilerplate required for the registry, some extra codegen, and a few tests.

Will squash once we're sure it's good.

### CODE REVIEW

**Comment by mml** [comment]
Sigh.  Looks like we changed this after 2ffa3b4586923fbeccfac18777cdb09398b20490

Climbing back into the hole...

**Comment by mml** [comment]
@lavalamp this is passing now.

**Comment by lavalamp** [comment]
LGTM, please squash.

**Comment by mml** [comment]
squashed.  thanks for the review.

**Pull request merged**
