### PR TITLE
Revert "Bump GCE ContainerVM to container-v1-3-v20160517 (Docker 1.11.1)"

### PR DESCRIPTION
**Pull request by wojtek-t**
This PR seems to broke larger kubemarks.

It seems that we can't start more than ~60pods per node with the new container VM. I don't have time to investigate exact reason of that now.

@dchen1107 @zmerlynn @derekwaynecarr @kubernetes/sig-node @lavalamp 

Reverts kubernetes/kubernetes#25843

### CODE REVIEW

**Comment by lavalamp** [comment]
@dchen1107

**Comment by dchen1107** [comment]
When I saw the failure of kubernetes-kubemark-500-gce last night, I did suspect docker 1.11.1 image might be the cause. But all other jenkins jobs were fine including those density tests which run 110 pods per node. I also checked kubernetes-kubemark-500-gce's logs except kubelet logs since they are too big to open, and looks like docker & kubelet are all fine. Since I cannot take a look at kubelet log, it might be some kubemark-node running as pod stuck somewhere. @timstclair and I will take a look.

**Comment by dchen1107** [comment]
One thing we know with docker 1.11.1: 

1) Its performance is much better than previous releases. Its performance improvement might expose more issues with our integration. We found one related to init containers implementation immediately with docker 1.11.1, but docker 1.9.1 has rare failures which makes it harder debugging. 

2) Docker 1.11.1 uses more resource than previous releases. This might be another cause of the failures.

**Comment by yujuhong** [comment]
@dchen1107 see https://github.com/kubernetes/kubernetes/issues/25949#issuecomment-220659411

I didn't investigate fruther to see why the same error didn't show up when running other tests.

**Comment by dchen1107** [comment]
@yujuhong I also saw that logs too, and planed to file an issue. But I didn't think that was critical one cause then because all other jenkins jobs with the same errors are fine. Now I finally can open kubelet.log, and I saw a lot of errors like:
```
E0520 07:02:20.049171    3594 pod_workers.go:183] Error syncing pod 65f4c2dd-1e58-11e6-8012-42010af00002, skipping: [failed to "StartContainer" for "hollow-kubelet" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=hollow-kubelet pod=hollow-node-3luv3_kubemark(65f4c2dd-1e58-11e6-8012-42010af00002)"
, failed to "StartContainer" for "hollow-proxy" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=hollow-proxy pod=hollow-node-3luv3_kubemark(65f4c2dd-1e58-11e6-8012-42010af00002)"
```

**Pull request merged**
