### PR TITLE
Fix the problem in building hyperkube for 3rd party registry

### LINKED ISSUE #26620: Failed to run hyperkube is 3rd party registry is used when building
To build a dev version of hyperkube with 3rd party using command like:
 
KUBE_DOCKER_REGISTRY=localhost:5000 KUBE_DOCKER_OWNER=liyi KUBE_DOCKER_VERSION=1.3.0-kolla ./hack/dev-push-hyperkube.sh 
Will result in unusable images.  
The reason is that static pods in hyperkube did not point to the third party registry.

### PR DESCRIPTION
**Pull request by liyimeng**
Minor bugfix.  fixes #26620

[Analytics]()

### CODE REVIEW

**Comment by eparis** [comment]
ok to test

**Comment by eparis** [comment]
LGTM but I'll let @luxas @fgrzadkowski take a glance since they have touched this area the most.

**Comment by eparis** [comment]
You will need to sign the CLA before this can be merged.

**Comment by liyimeng** [comment]
I signed it!

**Comment by luxas** [comment]
LGTM

**Pull request merged**
