### PR TITLE
rkt: Bump required rkt version to 1.9.1.

### PR DESCRIPTION
**Pull request by yifan-gu**
Bump the rkt version to use the one that fixed the [go-systemd sdjournal issue](https://github.com/coreos/rkt/pull/2837), also match [release doc](https://github.com/kubernetes/kubernetes.github.io/blob/release-1.3/docs/getting-started-guides/rkt/index.md#prerequisite).

cc @kubernetes/sig-rktnetes @kubernetes/sig-node

### CODE REVIEW

**Comment by tmrts** [comment]
LGTM

**Comment by dchen1107** [comment]
LGTM

**Comment by yifan-gu** [comment]
The node-e2e failures seems unrelated.
@k8s-bot test this please, issue #IGNORE

**Comment by yifan-gu** [comment]
Fix https://github.com/kubernetes/kubernetes/issues/27228

**Comment by yifan-gu** [comment]
@k8s-bot test this please, issue #IGNORE

**Pull request merged**
