### PR TITLE
Set some default values and add some additional comments for clarity.

### PR DESCRIPTION
**Pull request by brendandburns**

### CODE REVIEW

**Comment by mikedanese** [comment]
Why apply these  to unversioned defaults as opposed to v1 defaults?

**Comment by brendandburns** [comment]
@mikedanese I'm not sure why `PodExecOptions` was there, but moving it breaks the serialization tests, so I just emulated what already existed.  If we really want to move it, I'd rather someone who knows that code better than I do work on that bit.

This code seems independent of that cleanup.

**Comment by krousey** [comment]
@brendanburns @mikedanese Putting it here for now is fine. We have plans to gut the unversioned API soon, so this can just be another item on that list.

**Comment by alex-mohr** [comment]
LGTM was before last commit, removing LGTM

**Comment by brendandburns** [comment]
test comment, please ignore

**Comment by alex-mohr** [comment]
@k8s-bot test this [testing build queue, sorry for the noise]

**Comment by alex-mohr** [comment]
Automatic merge from SubmitQueue

**Pull request merged**
