### PR TITLE
Juju: Fix shebangs in charm actions to use python3

### PR DESCRIPTION
**Pull request by Cynerva**
**What this PR does / why we need it**:

This fixes the microbot and create-rbd-pv actions by reverting them back to python3. We accidentally switched them to python2 to match the boilerplate checker's expectations for python files.

It looks like hack/verify-boilerplate.sh does not check these since they don't have the .py extension, so we should be good with no changes there.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:

https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/212

**Special notes for your reviewer**:

**Release note**:

```release-note
Juju: Fix shebangs in charm actions to use python3
```

### CODE REVIEW

**Comment by chuckbutler** [comment]
@k8s-bot ok to test

/approve

**Comment by mbruzek** [comment]
We need these fixes! Thanks @Cynerva 

/approve

**Comment by Cynerva** [comment]
@k8s-bot kubemark e2e test this
@k8s-bot kops aws e2e test this

**Pull request merged**
