### PR TITLE
Clean up Deployment overlap annotation code

### LINKED ISSUE #43322: Clean up Deployment overlap annotation code
The Deployment overlap annotation (`deployment.kubernetes.io/error-selector-overlapping-with`) is no longer populated nor used by 1.6+ on the server side. However, in #43239 we maintained knowledge of the annotation for 1.6 clients in case they talk to pre-1.6 servers. That PR also adds code to clean up the annotation whenever it's found in 1.6+ clusters, so that pre-1.6 clients don't see it and make the wrong assumptions.

The code handling this annotation should be removed when all the following conditions are met:
* We no longer support a 1.5.x client talking to the latest server version.
* We no longer support upgrading the server directly from 1.5.x to the latest version.

The soonest milestone that meets both conditions according to the [versioning guidelines](https://github.com/kubernetes/community/blob/854e9518703851ec79e26a47d46a0c70d829fe37/contributors/design-proposals/versioning.md) is **v1.8**. This issue should be moved to that milestone once it exists.

### PR DESCRIPTION
**Pull request by wanghaoran1988**
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #43322

**Special notes for your reviewer**:

**Release note**:

```
None
```

### CODE REVIEW

**Comment by wanghaoran1988** [comment]
@kargakis @janetkuo @enisoc

**Comment by enisoc** [comment]
There are still a couple more places that use the annotation as noted in https://github.com/kubernetes/kubernetes/issues/43322#issuecomment-308266306. We should remove those too.

**Comment by enisoc** [comment]
@k8s-bot ok to test

**Comment by janetkuo** [comment]
Please update PR description `fixes #43322` to `xref #43322` if this PR doesn't fully resolve the issue (or update the PR to fully resolve the issue).

**Comment by wanghaoran1988** [comment]
@janetkuo I think I should update all the related things, would you mind point me other things if I really missed something?

**Comment by janetkuo** [comment]
@wanghaoran1988 your updated commit has addressed the comment. 

/lgtm

**Review by janetkuo — APPROVED** [review]

**Pull request merged**
