### PR TITLE
Remove useless code

### PR DESCRIPTION
**Pull request by sakeven**
Signed-off-by: sakeven <jc5930@sina.cn>

**What this PR does / why we need it**:

Function checkErrWithPrefix is never used, so we can safely remove it.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by sakeven** [comment]
@xiangpengzhao cloud you approve it?

**Comment by xiangpengzhao** [comment]
@sakeven sorry I'm not file owner who can approve the PR.
ping @fabianofranz for approval :)

**Pull request merged**
