### PR TITLE
Address comments in #64006.

### PR DESCRIPTION
**Pull request by Random-Liu**
Address comments in #64006 

@tallclair @yujuhong 
@kubernetes/sig-node-pr-reviews 
Signed-off-by: Lantao Liu <lantaol@google.com>

**Release note**:

```release-note
none
```

### CODE REVIEW

**Comment by dims** [comment]
@tallclair needs `/status approved-for-milestone` for this to merge

**Comment by Random-Liu** [comment]
Not familiar with the policy. @tallclair for milestone approve.

**Comment by feiskyer** [comment]
LGTM

/status approved-for-milestone

**Comment by What871As** [comment]
[plugins.cri]
  stream_server_address = "127.0.0.1"
  stream_server_port = "0"
  enable_tls_streaming = false

**Comment by What871As** [comment]
[plugins.cri]
  stream_server_address = "127.0.0.1"
  stream_server_port = "0"
  enable_tls_streaming = false

**Pull request merged**
