### PR TITLE
when kubelet restarts pid/memory/disk pressure taints will not be wiped

### LINKED ISSUE #119645: previous node taint is wiped when kubelet restarts
### What happened?

I have a k8s cluster(v1.27.2) containing one node. I set `evictionHard: nodefs.available: 90%` and write a large amount of data to kubelet rootdir（used 8GB / total 10GB ） to trigger eviction. `node.kubernetes.io/disk-pressure` taint was added to this node. But when kubelet restarted, previous disk-pressure taint was wiped weirdly. And pending pod is normally scheduled to run on the current node. Then I checked the kubelet logs and found:

kubelet restart:
```
I0727 11:09:05.782733 3813426 flags.go:64] FLAG: --tls-private-key-file=""
I0727 11:09:05.782737 3813426 flags.go:64] FLAG: --topology-manager-policy="none"
I0727 11:09:05.782741 3813426 flags.go:64] FLAG: --topology-manager-scope="container"
I0727 11:09:05.782745 3813426 flags.go:64] FLAG: --v="8"
I0727 11:09:05.782749 3813426 flags.go:64] FLAG: --version="false"
I0727 11:09:05.782754 3813426 flags.go:64] FLAG: --vmodule=""
I0727 11:09:05.782757 3813426 flags.go:64] FLAG: --volume-plugin-dir="/usr/libexec/kubernetes/kubelet-plugins/volume/exec/"
I0727 11:09:05.782761 3813426 flags.go:64] FLAG: --volume-stats-agg-period="1m0s"
I0727 11:09:05.796690 3813426 mount_linux.go:222] Detected OS with systemd
```
update node status **NodeHasNoDiskPressure**
``` 
I0727 11:09:10.858628 3813426 kubelet_node_status.go:632] "Recording event message for node" node="192.168.2.107" event="NodeHasNoDiskPressure"
I0727 11:09:10.858640 3813426 kubelet_node_status.go:762] "Setting node status condition code" position=9 node="192.168.2.107"
```
eviction manager  start to synchronize 
```
I0727 11:09:13.373393 3813426 eviction_manager.go:292] "Eviction manager: synchronize housekeeping"
```

Q: Why does kubelet report **NodeHasNoDiskPressure** ?
A: Eviction manager has not yet executed the synchronize method

Normally, a node that was previously marked with taints should retain after reboot otherwise it doesn't make sense. Maybe we need to make sure that taints can't be deleted when kubelet restarts?

### What did you expect to happen?

previous node taint is not wiped 

### How can we reproduce it (as minimally and precisely as possible)?

Restart kubelet repeatedly after the disk pressure eviction is triggered. Observe `node.spec.taints`

### Anything else we need to know?

_No response_

### Kubernetes version

1.27.2

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by Chaunceyctx**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #119645

#### Does this PR introduce a user-facing change?

```release-note
when kubelet restarts pid/memory/disk pressure taints will not be wiped
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bart0sh** [comment]
@Chaunceyctx Thank you for your PR. Please [sign the CLA](https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet#signing-the-cla) to proceed further, thanks.

/cc

**Comment by Chaunceyctx** [comment]
> @Chaunceyctx Thank you for your PR. Please [sign the CLA](https://github.com/kubernetes/community/tree/master/contributors/guide/contributor-cheatsheet#signing-the-cla) to proceed further, thanks.
> 
> /cc

thanks! done

**Review by kannon92 — COMMENTED** [review]
Could you add a e2e test to replicate the original behavior?

**Comment by Chaunceyctx** [comment]
> Could you add a e2e test to replicate the original behavior?

i will add it

**Comment by Chaunceyctx** [comment]
> Could you add a e2e test to replicate the original behavior?

@kannon92 actually, it is hard to reproduce by using e2e test. The pr submitted is not quite right either, because kubelet could not be sure that it had collected all metrics provided by the cadvisor in synchronize method.

The impact of this problem is actually very small, and the taints of the node will appear briefly and then appear again. Therefore, I would like to ask if it is still necessary for us to repair this problem

**Comment by kannon92** [comment]
> > Could you add a e2e test to replicate the original behavior?
> 
> @kannon92 actually, it is hard to reproduce by using e2e test. 

You could induce disk pressure with dd and then restart kubelet. And then verify if the disk pressure labels still exist? 

The only thing I am not sure on is if e2e_node would actually have nodes but I think its worth exploring.

It would be nice to have a way to determine that this bug is fixed and to make sure we have some integration/e2e test that can confirm this.

> The pr submitted is not quite right either, because kubelet could not be sure that it had collected all metrics provided by > the cadvisor in synchronize method.

If the pr is not quite right, should we close the PR?


> The impact of this problem is actually very small, and the taints of the node will disappear briefly and then appear again. Therefore, I would like to ask if it is still necessary for us to repair this problem

Hmm I see. I mean that could cause a race where don't occur on a restart but then it could resolve itself.

**Comment by Chaunceyctx** [comment]
> > Could you add a e2e test to replicate the original behavior?
> 
> @kannon92 actually, it is hard to reproduce by using e2e test. The pr submitted is not quite right either, because kubelet could not be sure that it had collected all metrics provided by the cadvisor in synchronize method.
> 
> The impact of this problem is actually very small, and the taints of the node will disappear briefly and then appear again. Therefore, I would like to ask if it is still necessary for us to repair this problem

/cc @pacoxu @Random-Liu @mrunalp

**Pull request closed without merging**
