### PR TITLE
bump evanphx/json-patch to v5 and ensure path if not exists on json patch for kubeadm

### LINKED ISSUE #2770: kubeadm patch (type json - RFC 6902 conform) doesn't ensure path if not exists
## Is this a BUG REPORT or FEATURE REQUEST?

Choose one: BUG REPORT

## Versions

**kubeadm version** (use `kubeadm version`): `1.25.3`

**Environment**:
- **Kubernetes version** (use `kubectl version`): `1.25.3`
- **Cloud provider or hardware configuration**: `-`
- **OS** (e.g. from /etc/os-release): `ubuntu 22.04`
- **Kernel** (e.g. `uname -a`): `5.15.0-50-generic`
- **Container runtime (CRI)** (e.g. containerd, cri-o): `containerd`
- **Container networking plugin (CNI)** (e.g. Calico, Cilium): `cilium`
- **Others**: `-`

## What happened?

According to the [RFC 6902](https://datatracker.ietf.org/doc/html/rfc6902/#appendix-A.16), `kubeadm` doesn't accecpt a valid json patch. `kubeadm` fails, when items on `pod.spec.containers.env` should get appened if `env` doesn't exist:

```
[patches] Found the following patch files: [kube-apiserver+json.json]
error execution phase control-plane/apiserver: failed to patch static Pod manifest file for "kube-apiserver": could not apply the following patch of type "application/json-patch+json" to target "kube-apiserver":
[{"op":"add","path":"/spec/dnsPolicy","value":"ClusterFirstWithHostNet"},{"op":"add","path":"/spec/containers/0/env/-","value":{"name":"MY_COMPANY_VAR","value":"fancy_company_specific_value"}}]
: add operation does not apply: doc is missing path: "/spec/containers/0/env/-": missing value
```

The current `kubeadm` implementation make use of `github.com/evanphx/json-patch`. This implementation doesn't fully implemented RFC 6902. `v5` added some patch options where it's possible to set `EnsurePathExistsOnAdd` to `true`.

## What you expected to happen?

A generated manifest file where `env` is defined.

```
grep -C 6 env /etc/kubernetes/manifests/kube-apiserver.yaml 
    - --service-account-issuer=https://kubernetes.default.svc.cluster.local
    - --service-account-key-file=/etc/kubernetes/pki/sa.pub
    - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
    - --service-cluster-ip-range=10.96.0.0/12
    - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
    - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
    env:
    - name: MY_COMPANY_VAR
      value: fancy_company_specific_value
    image: registry.k8s.io/kube-apiserver:v1.26.0-alpha.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
```

## How to reproduce it (as minimally and precisely as possible)?

1. create a json-patch and save as `kube-apiserver+json.json` under `/tmp/mypatch`
   ```json
   [
       {
           "op": "add",
           "path": "/spec/dnsPolicy",
           "value": "ClusterFirstWithHostNet"
       },
       {
           "op": "add",
           "path": "/spec/containers/0/env/-",
           "value": {
                   "name": "MY_COMPANY_VAR",
                   "value": "fancy_company_specific_value"
           }
       }
   ]
   ```

1. run
   ```
   kubeadm init phase control-plane apiserver --patches /tmp/mypatch
   ```

### if `env` isn't empty, it works:

The json-patch from above works fine, if `env` already exist. The current implementation of `kubeadm` (todo link) add the `env` section if `HTTP_PROXY`/`HTTPS_PROXY` or `NO_PROXY` is set in the environment variables.

Therefore a
```
HTTP_PROXY="http://my-proxy-server:3128" kubeadm init phase control-plane apiserver --patches /root/files/patchv5
```

is working fine and result in following valid generated api-server manifest:

```
grep -C 6 env /etc/kubernetes/manifests/kube-apiserver.yaml
     - --service-account-issuer=https://kubernetes.default.svc.cluster.local
     - --service-account-key-file=/etc/kubernetes/pki/sa.pub
     - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
     - --service-cluster-ip-range=10.96.0.0/12
     - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
     - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
     env:
     - name: HTTP_PROXY
       value: http://my-proxy-server:3128
     - name: MY_COMPANY_VAR
       value: fancy_company_specific_value
    image: registry.k8s.io/kube-apiserver:v1.25.3
    imagePullPolicy: IfNotPresent
```

### we have to use the `ApplyWithOptions` method from `` instead of `Apply`

Example snippet on [go.dev/play](https://go.dev/play/p/SKTx8EHUj4Z)

The current `kubeadm` impl. make use of the `Apply` func (as in Line 73) and is failing.
By making use of `ApplyWithOptions` (Line 66) a json patch (according to RFC 6902) get applied and result in the desired output.

### PR DESCRIPTION
**Pull request by bavarianbidi**
Signed-off-by: Mario Constanti <mario@constanti.de>

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:
Fixes kubernetes/kubeadm#2770

#### Does this PR introduce a user-facing change?

```release-note
`kubeadm` now ensure a path if it doesn't exist for `json` patches.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
When I worked on https://github.com/kubernetes/kubernetes/pull/102467#issue-907829381, we don't choose v5.5.0 for its Break change.
/cc liggitt monopole

**Comment by bavarianbidi** [comment]
> When I worked on [#102467 (comment)](https://github.com/kubernetes/kubernetes/pull/102467#issue-907829381), we don't choose v5.5.0 for its Break change. /cc liggitt monopole

Thanks @pacoxu for refering to the related PR. For that reason i've only updated `json-patch` for `kubeadm` as i wasn't sure about the impact for entire `kubernetes`. Maybe (hopefully) it's ok to just update the package for `kubeadm` (:crossed_fingers: )

**Comment by pacoxu** [comment]
/assign @neolit123 
for kubeadm

**Review by neolit123 — COMMENTED** [review]
this v5 bump will need approval from dependency maintainers.

i am not quite sure what is the breaking change that you've mentioned on the linked issue. do you have an example?

in general i approve of this change.

**Comment by bavarianbidi** [comment]
> i am not quite sure what is the breaking change that you've mentioned on the linked issue. do you have an example?

to be honest, i didn't know a breaking change. I only could imagine that user might have a very complex setup of multiple patches and this change "could" lead to issues. As we internally use very small patches without too much complexity i didn't hit any issue with the proposed change.

**Comment by pacoxu** [comment]
The break change is https://github.com/evanphx/json-patch/pull/143 for Preserve "null" values in arrays (https://github.com/kubernetes/kubernetes/issues/98080).

**Comment by bavarianbidi** [comment]
> Is it possible for the bugfix this is trying to pick up to be picked to the evanphx 4.x stream (or add an option to let us update to v5 while allowing missing paths on replace for compatibility with v4 behavior in [#91622 (comment)](https://github.com/kubernetes/kubernetes/pull/91622#issuecomment-637087847))?

By comparing the test-cases of `evanphx/json-patch` of both versions, all cases which exist in the old `v4` implementation are still test-cases in the new `v5` implementation. The only difference is, that the test cases which already exist in the `v4` implementation are explicitly set the json patch options `{AllowMissingPathOnRemove: false, EnsurePathExistsOnAdd: false}` in the `v5` implementation.
Appart from that, there are new test cases where `AllowMissingPathOnRemove: true` *AND/OR `EnsurePathExistsOnAdd: true` are set.

For that reason it seems that an update to `v5` shouldn't break anything and if other [patch options than the default](https://github.com/evanphx/json-patch/blob/master/v5/patch.go#L90-L98) are required, we can change them on demand.

**Comment by bavarianbidi** [comment]
As the test-data was still equal, only the ordering changed, i've added a small `remarshalJSON` func ([impl](https://github.com/kubernetes/kubernetes/pull/113092/files#diff-4c9fdc97c03d2977165963633bd056256e0822caf14db90493b2cd670f36d19dR682-R692)) to do a proper test data validation. 

Without the remarshaling, and with the removal of the `jsonToYAMLOrError` helper for the test-result, you could see that the data is equal. 

As an alternative we could do the `reflect.DeepEqual` also on the `jsonToYAMLorError` object.

```
ok      k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/json      (cached)                                                                                                                                                                                                                                                                        
--- FAIL: TestCreateThreeWayJSONMergePatch (0.03s)                                                                                                                                                                                                                                                                                                      
    patch_test.go:683: error in test case: delete field from nested map with conflict                                                                                                                                                                                                                                                                   
        expected patch:                                                                                                                                                                                                                                                                                                                                 
        {"simpleMap":{"key1":1,"key2":null}}                                                                                                                                                                                                                                                                                                            
        got:                                                                                                                                                                                                                                                                                                                                            
        {"simpleMap":{"key2":null,"key1":1}}                                                                                                                                                                                                                                                                                                            
    patch_test.go:683: error in test case: add field and delete all fields from map with conflict
        expected patch:
        {"name":null,"other":"a","value":null}
        got:
        {"name":null,"value":null,"other":"a"}
FAIL
```

**Comment by liggitt** [comment]
> For that reason it seems that an update to `v5` shouldn't break anything and if other [patch options than the default](https://github.com/evanphx/json-patch/blob/master/v5/patch.go#L90-L98) are required, we can change them on demand.

Hmm, I didn't think that was the case when we last tried to bump to v5. If that is true, let's go ahead and do that and update to use v5 everywhere with the desired compatibility options set, rather than straddling both v4 and v5

**Comment by pacoxu** [comment]
link the issue in repo evanphx/json-patch https://github.com/evanphx/json-patch/issues/86

**Comment by liggitt** [comment]
if we want to try switching again to v5 and think there are compatibility options we can use to avoid changing server-side behavior, go ahead and switch all uses to it and we'll run it through our tests

**Comment by bavarianbidi** [comment]
> if we want to try switching again to v5 and think there are compatibility options we can use to avoid changing server-side behavior, go ahead and switch all uses to it and we'll run it through our tests

At least all unit tests are working fine but maybe there are some issues we might hit in the e2e tests. But to catch these, someone has to add the `/ok-to-test` label.

**Comment by neolit123** [comment]
> At least all unit tests are working fine but maybe there are some issues we might hit in the e2e tests. But to catch these, someone has to add the /ok-to-test label.

/ok-to-test

**Comment by liggitt** [comment]
the integration failures are what I remembered from https://github.com/kubernetes/kubernetes/pull/91622#issuecomment-637087847

>     reinvocation_test.go:440: Internal error occurred: replace operation does not apply: doc is missing key: /metadata/labels/fight: missing value

are there compatibility options we could set at the point where the server applies the patch that would make those patches work as-is?

https://github.com/kubernetes/kubernetes/blob/dc3c9c0101563f95ca5d844c525a095b4a231dff/staging/src/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/dispatcher.go#L329

If so, we would also need to sweep all places we apply json patches to set the same compatibility options

**Comment by dims** [comment]
If you still need this PR then please rebase, if not, please close the PR

**Comment by ritazh** [comment]
> If you still need this PR then please rebase, if not, please close the PR

@bavarianbidi We have reviewed this during the sig auth triage meeting. Since this PR has not had any activities for few months now and it needs a rebase, we will close it for now. Feel free to reopen.

/close

**Pull request closed without merging**
