### PR TITLE
Run hack/run-gendocs.sh

### PR DESCRIPTION
**Pull request by zmerlynn**
Someone is a bad, bad person.

### CODE REVIEW

**Comment by roberthbailey** [comment]
LGTM.

**Comment by zmerlynn** [comment]
Hold, @jlowdermilk is telling me I'm wrong.

**Comment by zmerlynn** [comment]
Nevermind, not needed. `make clean` fixed it.

**Comment by satnam6502** [comment]
`make clean` does not do it for me.
See also #4412 
```
satnam-macbookpro2:kubernetes satnam$ make clean
build/make-clean.sh
+++ Verifying Prerequisites....
+++ Cleaning out _output/dockerized/bin/ via docker build image
+++ Running build command....
+++ Removing data container
+++ Cleaning out local _output directory
+++ Deleting docker image kube-build:build-f835a
Untagged: kube-build:build-f835a
Deleted: 1a39cacc28d2ed47a66612ed786bf43cd9390d39095819f17bb45c9a8f5f60dc
Deleted: aa593d5ab8a9e9a717eee80257f986f0d59a41617b2ea32f91f9427020288bb8
Deleted: aad29dad938f2d1ee67cef1ae3c8f008b3f985f4ba97129d42d8df0c73c49ce6
Deleted: ee2d890cab2bb53fcf282b01f8be4522bc4be53f019ec7d7460182556e1d03ab
Deleted: 219d5ce615ac5342bbd2cb436cd8884c57617683f4c7d83c827500a119909a7e
Deleted: bf29683465c9dc31d77e45e51f531d2b0b795f3d824959e8e797f8376d84ef4a
Deleted: 5d9dbcb028d9fffe4ba7fe747d1582750ee092c302ef480ec106933a614b56cc
Deleted: abcf161227c0ca504d4445857ba1c1c112eafc7fd33321d1e7a422cbfb3254d2
Deleted: b9b792aea37a34b5e7b3ac8865b771f8ccf8dc16c70fa4fd1bd83bf0b6dde972
Deleted: b3dfad1568daba4f719cb69426431a1a22e1990f8596d432cf2d20fc7984746c
Deleted: eea0c236e2df11e405d717f5495acc2857c11d450fdd0113058b5ce399bd215a
Deleted: 21e570d69e00356ebaca21fa431ff4fe3eef6a3446dc6557a33c68fa9f36bfaa
Deleted: b715ab46cc935e4eed6336e4b0351b98e3d38156dda5de6af9a58ba7413da67b
Deleted: ece0039346c58b0a89bae77c1f5b5262e83c79642cb65a58093b1ab9b4645bcd
+++ Cleaning all other untagged docker images
rm -rf _output
rm -rf Godeps/_workspace/pkg
satnam-macbookpro2:kubernetes satnam$ build/release.sh
+++ Verifying Prerequisites....
+++ Setting boot2docker clock
+++ Building Docker image kube-build:cross.
+++ Building Docker image kube-build:build-f835a.
+++ Running build command....
+++ Creating data container
+++ Building go targets for linux/amd64:
    cmd/kube-proxy
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kubelet
    plugin/cmd/kube-scheduler
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/master/server/server.go:32:2:
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:20:1: expected 'STRING', found '<<'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:37:61: expected 'STRING', found 'go'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:42:1: expected 'STRING', found 'type'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:52:61: expected 'STRING', found 'go'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:56:1: expected 'STRING', found 'type'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:64:1: expected 'STRING', found 'var'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:67:61: expected 'STRING', found 'go'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:87:2: expected 'STRING', found 'for'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:97:2: expected 'STRING', found 'for'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:98:61: expected 'STRING', found 'go'
_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/apiserver/api_installer.go:99:3: expected 'STRING', found 'if'
!!! Error in /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:303
  'go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${binaries[@]}"' exited with status 1
Call stack:
  1: /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:303 kube::golang::build_binaries(...)
  2: hack/build-cross.sh:28 main(...)
Exiting with status 1
!!! Error in /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:238
  '( kube::golang::setup_env; local version_ldflags; version_ldflags=$(kube::version::ldflags); local host_platform; host_platform=$(kube::golang::host_platform); local goflags; eval "goflags=(${KUBE_GOFLAGS:-})"; local use_go_build; local -a targets=(); local arg; for arg in "$@";
do
    if [[ "${arg}" == "--use_go_build" ]]; then
        use_go_build=true;
    else
        if [[ "${arg}" == -* ]]; then
            goflags+=("${arg}");
        else
            targets+=("${arg}");
        fi;
    fi;
done; if [[ ${#targets[@]} -eq 0 ]]; then
    targets=("${KUBE_ALL_TARGETS[@]}");
fi; local -a platforms=("${KUBE_BUILD_PLATFORMS[@]:+${KUBE_BUILD_PLATFORMS[@]}}"); if [[ ${#platforms[@]} -eq 0 ]]; then
    platforms=("${host_platform}");
fi; local binaries; binaries=($(kube::golang::binaries_from_targets "${targets[@]}")); local platform; for platform in "${platforms[@]}";
do
    kube::golang::set_platform_envs "${platform}"; kube::log::status "Building go targets for ${platform}:" "${targets[@]}"; if [[ -n ${use_go_build:-} ]]; then
        local output_path="${KUBE_GOPATH}/bin"; if [[ $platform != $host_platform ]]; then
            output_path="${output_path}/${platform//\//_}";
        fi; for binary in "${binaries[@]}";
        do
            local bin=$(basename "${binary}"); if [[ ${GOOS} == "windows" ]]; then
                bin="${bin}.exe";
            fi; go build -o "${output_path}/${bin}" "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${binary}";
        done;
    else
        go install "${goflags[@]:+${goflags[@]}}" -ldflags "${version_ldflags}" "${binaries[@]}";
    fi;
done )' exited with status 1
Call stack:
  1: /go/src/github.com/GoogleCloudPlatform/kubernetes/hack/lib/golang.sh:238 kube::golang::build_binaries(...)
  2: hack/build-cross.sh:28 main(...)
Exiting with status 1
!!! Error in build/../build/common.sh:378
  '"${docker_cmd[@]}" "$@"' exited with status 1
Call stack:
  1: build/../build/common.sh:378 kube::build::run_build_command(...)
  2: build/release.sh:32 main(...)
Exiting with status 1
satnam-macbookpro2:kubernetes satnam$
```

**Pull request closed without merging**
