### PR TITLE
Remove WindowsGMSA and WindowsRunAsUserName feature gates

### LINKED ISSUE #95707: Remove WindowsGMSA and WindowsRunAsUserName feature gates in 1.20
Both WindowsGMSA and WindowsRunAsUserName feature gates have been GA since v1.18 and were scheduled to be removed in v1.20.

https://github.com/kubernetes/kubernetes/blob/2046f4212a355a3381da20c4d800283b98e9a081/pkg/features/kube_features.go#L714-L715

/sig windows
/milestone v1.20
/good-first-issue

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What type of PR is this?**
/kind cleanup

**Which issue(s) this PR fixes**:

Fixes #95707

**Does this PR introduce a user-facing change?**:

```release-note
The feature gates `WindowsGMSA` and `WindowsRunAsUserName` that are GA since v1.18 are now removed.
```

### CODE REVIEW

**Comment by marosset** [comment]
There is another PR already open for this https://github.com/kubernetes/kubernetes/pull/95834

**Comment by ialidzhikov** [comment]
@marosset , the required checks now passed.

**Comment by ialidzhikov** [comment]
Pping @marosset

**Comment by marosset** [comment]
Hi @ialidzhikov - as I mentioned above we have another contributor who has already opened a PR to address this and I want to give them a chance to get their changes merged. Thanks!

**Comment by vpnachev** [comment]
Hello @marosset 
I see the other PR has already been closed https://github.com/kubernetes/kubernetes/pull/95834 and another opened to replace it https://github.com/kubernetes/kubernetes/pull/96653, but it is still open and seems there were no activity in the last 2 months https://github.com/kubernetes/kubernetes/pull/96653#issuecomment-729801070.

Then how about merging this one which is ready and have waited enough time?

**Comment by marosset** [comment]
> Then how about merging this one which is ready and have waited enough time?

I agree.

**Comment by ialidzhikov** [comment]
/cc @wk8 @marosset
for approval

**Comment by ialidzhikov** [comment]
Friendly ping @derekwaynecarr @wk8 @marosset 

Why it takes months reviewing and approving such no-op cleanup PR that hurt nobody?

**Comment by ehashman** [comment]
/priority backlog

@ialidzhikov we have limited reviewer capacity and this is not a high-priority PR.

Please rebase so this can be merged.

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by ehashman** [comment]
/priority important-soon

ref KEP https://github.com/kubernetes/enhancements/issues/689

**Comment by ehashman** [comment]
I think that's a flaky test (#98084).

/retest

**Comment by marosset** [comment]
Yes this this a flaky test :(
It shouldn't be PR blocking tho - just informing.

**Comment by marosset** [comment]
@dims, @dchen1107, @derekwaynecarr Could one of you give `feature-approvers` approval here?

It looks like no-one from SIG-Windows is on the list after m2 left https://github.com/kubernetes/kubernetes/blob/df7f240dee840ec6a079e37c3fdec3a338244024/OWNERS_ALIASES#L556

**Comment by ehashman** [comment]
@ialidzhikov can you please rebase? looks like there's been another conflict merged

**Review by ehashman — COMMENTED** [review]
/lgtm

**Pull request merged**
