### PR TITLE
Simplify case conditions

### PR DESCRIPTION
**Pull request by littlejiancc**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
Condition is always 'true' because 'err' is always 'nil'
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by alculquicondor** [comment]
/retitle Simplify case conditions

Optimize is usually associated with performance, which this is not (at least, not in a meaningful way)

/lgtm

**Review by soltysh — APPROVED** [review]
/release-note-note
/triage accepted
/priority backlog

**Pull request merged**
