### PR TITLE
Remove GA featuregate about CSIMigrationvSphere in 1.29

### PR DESCRIPTION
**Pull request by bzsuni**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Remove GA featuregate about CSIMigrationvSphere in 1.29
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
none
```

### CODE REVIEW

**Comment by bzsuni** [comment]
/assign @dims 
Could you please review this pr?

**Review by mrunalp — APPROVED** [review]

**Comment by xing-yang** [comment]
We locked CSIMigrationvSphere feature gate to true in K8s 1.27. So it's fine to remove it in 1.29.
https://github.com/kubernetes/kubernetes/pull/116610

**Review by divyenpatel — APPROVED** [review]
/approve

**Pull request merged**
