### PR TITLE
Promote ardaguclu to approver for sig-cli related stuff

### PR DESCRIPTION
**Pull request by soltysh**
#### What type of PR is this?
/kind cleanup
/sig cli

#### What this PR does / why we need it:
@ardaguclu has consistently proven good judgement and quality of his contributions over the past few releases, so we've decided to promote him to approver.

I've also noticed that we have Doug in reviewers, but he wasn't around for a while now, so I'm removing him. 

#### Special notes for your reviewer:
/assign @eddiezane @KnVerey @seans3 
for sig-cli approval

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by soltysh** [comment]
/hold 
for all leads to leave their approval

**Comment by eddiezane** [comment]
+1 thank you Arda for your work!

**Comment by seans3** [comment]
LGTM

Well deserved.

**Comment by KnVerey** [comment]
+1 Thanks and congrats, Arda!

**Comment by ardaguclu** [comment]
Thank you very much for helping and guiding me!

/lgtm
/hold

**Comment by dims** [comment]
/approve
/lgtm
/hold cancel

awesome! thanks for all that you do @ardaguclu !!

**Pull request merged**
