### PR TITLE
Scheduler perf metrics server

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
**What this PR does / why we need it**:
Prometheus metrics server for scheduler perf.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:
@jayunit100 This for enabling prometheus metrics server in kubernetes. I have taken most of functions from your PR.

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by jayunit100** [comment]
Thanks yeah this will
Make these tests more robust and more useable for sure.

Let's make the 127 configurable and use this data verify scheduling throughput and kill that watch thingy . Is that easy enough to create a follow on PR for ?

Also leave a note to close my WIP pr around this.

Thanks

**Comment by ravisantoshgudimetla** [comment]
> Let's make the 127 configurable.

Are you talking about making 127.0.0.1 and port configurable?

> and use this data verify scheduling throughput and kill that watch thingy

Can you please elaborate on this? Are you talking about listing every pod across namespace and replace it with watch?

**Comment by ravisantoshgudimetla** [comment]
ping @jayunit100

**Comment by jayunit100** [comment]
is this working I.e. You've confirmed the scheduler metrics are all going into the endpoint and if so - can we kill the pod watch logic in a follow on PR and replace it with this ?

**Comment by ravisantoshgudimetla** [comment]
> is this working I.e. You've confirmed the scheduler metrics are all going into the endpoint and if so - can we kill the pod watch logic in a follow on PR and replace it with this ?

Yes @jayunit100. I will rebase this PR.

**Pull request closed without merging**
