### PR TITLE
Revert "Fix vagrant networking"

### PR DESCRIPTION
**Pull request by zmerlynn**
Reverts GoogleCloudPlatform/kubernetes#4204

### CODE REVIEW

**Comment by zmerlynn** [comment]
GCE can no longer create clusters, self-merging.

**Comment by derekwaynecarr** [comment]
What was the GCE issue so we can resolve?

**Comment by zmerlynn** [comment]
Clusters aren't coming up right now in either GCE or our GKE CI tests. I think the Salt config is busted, but I didn't poke at it long.

**Comment by derekwaynecarr** [comment]
Ok, I can see that this caused docker to go on kubernetes-master. 

@rajatchopra

**Pull request merged**
