### PR TITLE
Automated cherry pick of #110179: Prune defaults for CRD serving

### PR DESCRIPTION
**Pull request by Jefftree**
Cherry pick of #110179 on release-1.23.

#110179: Prune defaults for CRD serving

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

```release-note

```

### CODE REVIEW

**Comment by Jefftree** [comment]
/hold
Verifying whether [integration test failure](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/110578/pull-kubernetes-integration/1536801656086204416) is related
/test pull-kubernetes-integration

**Comment by dims** [comment]
/retest

@Jefftree is this still needed?

**Comment by puerco** [comment]
Thanks @Jefftree !
/lgtm
/priority important-soon

**Pull request merged**
