### PR TITLE
Apply strictCost for CEL used in DRA

### PR DESCRIPTION
**Pull request by cici37**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
I added [strictCost](https://github.com/kubernetes/kubernetes/pull/124675) to wire in the cost for extended lib of CEL and would recommend it to be on for anywhere using CEL. Otherwise the cost added for extended lib would not be used.

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by pohly — COMMENTED** [review]
This looks like a necessary first step towards solving https://github.com/kubernetes/kubernetes/issues/126819, but I am not sure whether it's worth merging on its own.

We also need to define limits (the hard part...) and add unit tests that everything is working as expected.

**Comment by cici37** [comment]
HI @pohly, Thanks for the comment. I am totally fine with closing this PR and have it together with the overall cost wiring. Although I wanna point out that it is kind of separate issue addressed: This PR is to turn on `strictCost` which will also be used by currently enabled per expression cost limit. By enabling `strictCost`, all the cel library cost will be calculated correctly. Missing overall cost limit is another issue which would require the overall cel cost calculated per resource depend on how DRA is using it.  :)

**Comment by pohly** [comment]
> Although I wanna point out that it is kind of separate issue addressed: This PR is to turn on strictCost which will also be used by currently enabled per expression cost limit. 

"Currently enabled" how and where? Is there some default cost limit that gets enforced?

**Comment by cici37** [comment]
> > Although I wanna point out that it is kind of separate issue addressed: This PR is to turn on strictCost which will also be used by currently enabled per expression cost limit.
> 
> "Currently enabled" how and where? Is there some default cost limit that gets enforced?

Yes. The per expression cost enforcement is currently enabled through cel program option: https://github.com/kubernetes/kubernetes/blob/d1b398caaa75d24cf9de4775711e36e42b4e8266/staging/src/k8s.io/apiserver/pkg/cel/environment/base.go#L84
Since CEL in DRA is using the same mechanism to build cel env, it will get the per expression cost enforcement for free :)

**Comment by pohly** [comment]
Hmm.

https://github.com/kubernetes/kubernetes/blob/1dbf0830c59038822f37eaf5a1d4f7583f1a1081/staging/src/k8s.io/apiserver/pkg/apis/cel/config.go#L20C1-L22C24

is defined as "PerCallLimit specify the actual cost limit per CEL validation call". That constant seems to be specific to VAP?

Why should it get applied to DRA? What if we want some different value? Can the DRA environment override that constant?

See also my question on Slack about how the values for those constants where determined: "current PerCallLimit gives roughly 0.1 second for each expression validation call" - on which machine and how was that measured?

**Comment by pohly** [comment]
/close

This commit was merged via some other PR into 1.32.

**Pull request closed without merging**
