### PR TITLE
Reference slack novice and dev channels in troubleshooting guide

### PR DESCRIPTION
**Pull request by mikebrow**
addresses issue #23702; promotes slack novice and dev channels
Signed-off-by: mikebrow brownwm@us.ibm.com

---

This change is [Reviewable](http://reviewable.k8s.io/reviews/kubernetes/kubernetes/23980)

### CODE REVIEW

**Comment by bgrant0607** [comment]
@johndmulhausen I believe this doc needs to be de-duped with one in kubernetes.github.io, correct?

**Comment by bgrant0607** [comment]
ok to test

**Comment by mikebrow** [comment]
Should put this edit in kubernetes.github.io and change this PR into an edit that point over there for the latest version of the document?

**Comment by sarahnovotny** [comment]
ok to test

**Comment by sarahnovotny** [comment]
ok to test

**Comment by sarahnovotny** [comment]
hey @mikebrow can you make this change in https://github.com/kubernetes/kubernetes.github.io/blob/master/docs/troubleshooting.md instead?  this page will be deprecated.

**Comment by mikebrow** [comment]
@sarahnovotny Sure np.. will move it there and close this one.

**Pull request closed without merging**
