### PR TITLE
Move Docker-specific log handling to DockerManager.

### PR DESCRIPTION
**Pull request by vmarmol**
Eases the separation of Docker-specific code into the Docker-specific
runtime.

### CODE REVIEW

**Comment by vmarmol** [comment]
@satnam6502 the main semantic change here is that the logs symlink is now made for the pod infra container as well. Is this a problem? I already have a fix if it is, but want to make sure we need it first :)

/cc @dchen1107  @yifan-gu @satnam6502

**Comment by dchen1107** [comment]
I re-run travis. LGTM and will merge once it is green.

**Comment by vmarmol** [comment]
Thanks for the quick review @dchen1107!

**Comment by yifan-gu** [comment]
LGTM!

**Pull request merged**
