### PR TITLE
Remove need for server connections for dry-run create

### PR DESCRIPTION
**Pull request by liggitt**
when running create commands in --dry-run mode, we don't need a server connection or restmapper information

```release-note
NONE
```

### CODE REVIEW

**Comment by liggitt** [comment]
cc @kubernetes/sig-cli-pr-reviews

**Comment by dixudx** [comment]
For other subcommands, like `run`, a server connection or restmapper information is not required as well in `--dry-run` mode. Right? Shall we add it here together.

**Comment by liggitt** [comment]
> For other subcommands, like run, a server connection or restmapper information is not required as well in --dry-run mode

not necessarily... many of those do live lookups to determine which generator to use. I'd rather keep this fix targeted

**Pull request merged**
