### PR TITLE
Utility functions for Gingko By and Fail

### PR DESCRIPTION
**Pull request by zmerlynn**
Split from #4269, let's argue about it here.

I think this is a twofold issue:
- Bikeshed over name: Logf is a little misleading in that it might suggest it's logging, when it's going to `GinkgoWriter`. I don't find it that misleading, because it _has_ to be something within the gingko package or our own due to the way it's called, so it's clearly a test function. I almost called it `Byf` to stick to Go patterns, but `Byf` is horri-bad name. Also, as @rrati points out on IRC, `By()` actually has a semantic distinction - even though I really do want all output going to `GinkgoWriter` to get all the output in the same place, `By()` is meant for step delineation, and it's a bit a perversion. (Just not a horrible one.) A better longer term solution would be a PR sent to Gingko for an actual first class `Log()` function, which sort of exists in their `testing` compatibility mode already but not in their normal mode. That part was meant to be a bit of a side-bar to say: This function might _ought_ to be named `Logf()` anyways, and doing something else: (maybe it needs to add "INFO:") so that people think to separate steps and logs. Maybe.
- ... or should we even bother. Arguably this is just some extra typing and people can stop being so damn lazy.

@filbranden @rrati @roberthbailey @satnam6502

### CODE REVIEW

**Comment by filbranden** [comment]
Yeah I still have to say -1 here since I think it hides a lot of Ginkgo and I'd prefer to stick to Ginkgo general style as much as possible...

I'd slightly prefer `Byf` and `Failf` as ugly as they are...

Maybe we can persuade Ginkgo guys to add something upstream on their end? @rrati what do you think? Would you be willing to take this to Ginkgo upstream and see what they have to say about it?

**Comment by rrati** [comment]
I don't feel too strongly either way about the helper functions.  The helper functions do make the code look cleaner and abstracting the logging/failing mechanism isn't a bad thing imo.  It's also not that bad to let the tests use raw ginkgo methods.

I'm happy to take the issue to the Ginkgo upstream and see if they'll provide a 1st class Log method or provide a means to do it.

**Comment by roberthbailey** [comment]
I think we should try to push something upstream. What is current exposed by the framework clearly isn't working for us, so either we are using it incorrectly or they should increase their API surface to add better logging support (and I think we shouldn't just push for vararg logging in By but rather a distinction between By and Log so that we can tell them apart in the test output).

**Comment by filbranden** [comment]
@roberthbailey I agree, I think it should be fairly straightforward to change the signatures of existing Fail() and By() so that they would take an extra vararg and apply fmt.Sprintf on everything they get. Existing use cases would continue working as they are. Anyone willing to fork Ginkgo repos and send them a PR for it?

**Comment by zmerlynn** [comment]
It's actually not as easy as that. By is already vararg. :) I did look at
it beforehand. But @rrati said he might look into it at some point. Let's
drop this PR for now ... I'd still like to at least get logging into By()
for now to clean up output (we're pretty close), and we can go back and do
the right thing when we have a direct line to the GinkgoWriter.

Actually, is there any contention over Errorf? Please note that Errorf() is
the same choice that golang testing makes:
http://golang.org/pkg/testing/#B.Errorf

I can drop the Logf PR and keep Errorf().

**Comment by filbranden** [comment]
@zmerlynn I still think we want to keep it familiar to Ginkgo users, if they come expecting to use `Fail` we shouldn't be telling them to use something else that looks like a different framework... I'd prefer if we didn't "hide" details of the frameworks we use.

I really don't have that much problem with `Fail(fmt.Sprintf(...))`, I think in 2014 we should be able to get our editors to type that for us if we don't like doing that all the time :-)

**Comment by rrati** [comment]
I was looking at the Ginkgo issues and it seems like we might be able to use fmt.Fprintln(GinkgoWriter, string) for logging that isn't intended to be a step.  It's not as clean as a 1st class logging method but it might work should we have to use it.

**Comment by roberthbailey** [comment]
If that's true then we could also use fmt.Fprintf(GinkgoWriter, fmtstr, args...) which would be much better than using By(...) everywhere.

**Comment by zmerlynn** [comment]
If that works, I'd be happy to rewrite this PR to just rewrite Logf as
fmt.Fprintf.

**Comment by filbranden** [comment]
I'm OK with `Logf` doing `fmt.Fprintf(GinkgoWriter, ...)` I think that makes sense.

I'd still prefer if we didn't *hide* `Fail` behind something like `Errorf` which actually belongs to a different framework... How about using `Failf` for it? And maybe pushing `Failf` upstream or asking them to modify the prototype of `Fail` to take a varadic argument and doing the Sprintf on the caller's behalf.

**Comment by zmerlynn** [comment]
I brushed this off and converted it to `Fprintf(GinkgoWriter)` with an "INFO:" preamble. I also changed `rc.go` to a mix of By() and Logf(), so that there's some hint of "here's the important stuff (the step) and here's some stuff I'm spamming you with (that's not in color)". Sample output:

```
ReplicationController
  should serve a basic image on each replica with a private image
  /usr/local/google/home/zml/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/rc.go:55
[BeforeEach] ReplicationController
  /usr/local/google/home/zml/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/rc.go:41
[It] should serve a basic image on each replica with a private image
  /usr/local/google/home/zml/kubernetes/_output/local/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/rc.go:55
STEP: Creating replication controller my-hostname-private-03614e86-b24c-11e4-976c-2c44fd1518ec
INFO: Controller my-hostname-private-03614e86-b24c-11e4-976c-2c44fd1518ec: Found 2 pods out of 2
STEP: Ensuring each pod is running and has a hostIP
INFO: Controller my-hostname-private-03614e86-b24c-11e4-976c-2c44fd1518ec: Replica 1 has hostIP: 104.154.36.239
INFO: Controller my-hostname-private-03614e86-b24c-11e4-976c-2c44fd1518ec: Replica 2 has hostIP: 104.154.57.215
STEP: Trying to dial each unique pod
INFO: Controller my-hostname-private-03614e86-b24c-11e4-976c-2c44fd1518ec: Got expected result from replica 1: my-hostname-private-03614e86-b24c-11e4-976c-2c44fd1518ec-5qipj
INFO: Controller my-hostname-private-03614e86-b24c-11e4-976c-2c44fd1518ec: Got expected result from replica 2: my-hostname-private-03614e86-b24c-11e4-976c-2c44fd1518ec-zb3h3
```

Obviously we could bikeshed about the exact test, but I think the point is more about the utility function.

I also s/`Errorf`/`Failf`/.

**Comment by roberthbailey** [comment]
LGTM.

**Comment by zmerlynn** [comment]
(FWIW, I agree that this is worth upstreaming, I'm just trying to help velocity internally first.)

**Comment by filbranden** [comment]
Looks good.

I think commit descriptions could use a little tuning (now that Logf doesn't use By anymore) but that's pretty minor so feel free to go ahead and merge it if you're happy with it now.

**Comment by zmerlynn** [comment]
Fixed!

**Pull request merged**
