### PR TITLE
Fix golint failures in pkg/securitycontext

### PR DESCRIPTION
**Pull request by gambtho**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Fixes golint failures in pkg/securitycontext

**Which issue(s) this PR fixes**:

Ref #68026

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
/ok-to-test
/priority backlog
/sig auth

**Comment by spiffxp** [comment]
/approve
only have rights for hack/
/lgtm

**Comment by dims** [comment]
/assign @liggitt 

(it's hard to get eyes from pkg/OWNERS ...)

**Pull request merged**
