### PR TITLE
Fix staticcheck failures of e2e/storage/utils e2e/storage/vsphere

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix staticcheck failures of e2e/storage/utils e2e/storage/vsphere

**Which issue(s) this PR fixes**:

Ref  #81657

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by hwdef** [comment]
/test pull-kubernetes-e2e-gce-storage-slow
/lgtm
Thanks for your contribution!

**Review by oomichi — COMMENTED** [review]
Thanks for doing this.

/approve

**Pull request merged**
