### PR TITLE
use metav1.ListOptions in fake_event_expansion.go

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix https://github.com/kubernetes/client-go/issues/145.

### CODE REVIEW

**Comment by floreks** [comment]
:lgtm

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43039#-:-KfBOUssLzNMc9707wtk:b-8eqf7b)*

**Comment by caesarxuchao** [comment]
Updated bazel BUILD files.

Applying the lgtm. Thanks @floreks.

**Comment by caesarxuchao** [comment]
@k8s-bot bazel test this

**Comment by floreks** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/43039)*

**Pull request merged**
