### PR TITLE
Automated cherry pick of #88251: fix incorrect configuration of kubepods.slice unit by kubelet

### PR DESCRIPTION
**Pull request by reegnz**
Cherry pick of #88251 on release-1.17.

#88251: fix incorrect configuration of kubepods.slice unit by kubelet

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by reegnz** [comment]
@odinuge related to #93863, this one is for 1.17.

**Comment by odinuge** [comment]
/lgtm
/kind bug
/assign @sjenning

Pretty sure sig-release enforce changelogs on all cherry-picks, but I guess you can try without and see.

**Review by odinuge — COMMENTED** [review]
/ok-to-test
/retest

**Comment by SergeyKanzhelev** [comment]
timeouts...

/retest

**Comment by reegnz** [comment]
Ping @kubernetes/release-managers

**Comment by SergeyKanzhelev** [comment]
CC @kubernetes/release-managers

**Comment by SergeyKanzhelev** [comment]
> Ping @kubernetes/release-managers
> 
> EDIT: I cannot seem to be able to ping this group.

I'm not sure why. Pinged them for you

**Comment by odinuge** [comment]
> EDIT: I cannot seem to be able to ping this group.

You have to be member of the kubernetes github org. in order to search for and tag groups.

**Comment by reegnz** [comment]
Thanks! 🎉

**Pull request merged**
