### PR TITLE
Add unit test for testing list tool

### PR DESCRIPTION
**Pull request by gaoguangze111**
**What type of PR is this?**
/kind cleanup

/kind flake

**What this PR does / why we need it**:
Add two unit test for testing list tool.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/ok-to-test
/lgtm

I prefer using subtests https://blog.golang.org/subtests and add more test cases, but seems this is aligned with the other tests in the same file and it is a helper function of the framework, so it is well enough for me

/assign @neolit123

**Review by neolit123 — COMMENTED** [review]
/approve

**Comment by neolit123** [comment]
@gaoguangze111 

gofmt is failing on your change, please see here:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/96905/pull-kubernetes-verify/1344200360666861568


run ./hack/update-gofmt.sh and commit the changes as part of the same commit.

**Comment by neolit123** [comment]
/lgtm cancel
until the gofmt issue is fixed.

**Pull request closed without merging**
