### PR TITLE
fix comment for cronjob utils.go

### PR DESCRIPTION
**Pull request by zhangxiaoyu-zidif**
**What this PR does / why we need it**:
fix comment for cronjob utils.go

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by FengyunPan — APPROVED** [review]
It's fix typo.
/ok-to-test

**Comment by zhangxiaoyu-zidif** [comment]
@wojtek-t 
PTAL

**Comment by soltysh** [comment]
@zhangxiaoyu-zidif thank you for your contribution! But I usually prefer actual changes to the code. Just updating the comments isn't sufficient argument for a merge. There are plenty of issue wrt to cronjob controller I'd like to see addressed. In the mean time I'll close this one.

**Comment by zhangxiaoyu-zidif** [comment]
@soltysh 
OK, I will deal with other PR on cronjob and fix this typo by the way.
=)

**Pull request closed without merging**
