### PR TITLE
Automated cherry pick of #50398

### PR DESCRIPTION
**Pull request by pci**
Cherry pick of #50398 on release-1.5.

#50398: Switch away from gcloud deprecated flags in compute resource

### CODE REVIEW

**Comment by pci** [comment]
Sorry, cherry pick to 1.5 not needed.

**Comment by ixdy** [comment]
why not? I think we are still supporting 1.5 until 1.8 is released.

**Comment by pci** [comment]
@ixdy that's what I had thought, but I re-read [this comment here](https://github.com/kubernetes/kubernetes/issues/50624#issuecomment-322721038) where @shyamjvs only mentioned 1.7 and 1.6. Happy to reopen if the 1.5 cherry pick is indeed needed?

**Comment by pci** [comment]
Reopening based on @ixdy comment, if this is not the case, or I've misunderstood, feel free to re-close the PR.

I'll do a rebase for the inevitable conflicts.

/cc @ixdy @shyamjvs

**Comment by ixdy** [comment]
/lgtm

though I think we now no longer support 1.5.

**Comment by shyamjvs** [comment]
Do we still need this PR? 1.5 is too old now.

**Comment by pci** [comment]
@shyamjvs agreed, closing.

**Pull request closed without merging**
